Unreal Engine 5.6 C++ API: FMath Struct Reference
FMath Struct Reference
Structure for all math helper functions, inherits from platform math to pick up platform-specific implementations Check GenericPlatformMath.h for additional math functions.
#include "UnrealMathUtility.h"
Public Member Functions
template<typename T>
FORCEINLINE_DEBUGGABLE T ClampAngle (T AngleDegrees, T MinAngleDegrees, T MaxAngleDegrees)
template<typename FReal>
FORCEINLINE UE::Math::TSphere< FReal > ComputeBoundingSphereForCone (UE::Math::TVector< FReal > const &ConeOrigin, UE::Math::TVector< FReal > const &ConeDirection, FReal ConeRadius, FReal CosConeAngle, FReal SinConeAngle)
Computes minimal bounding sphere encompassing given cone.
template<typename T>
bool IntersectPlanes2 (UE::Math::TVector< T > &I, UE::Math::TVector< T > &D, const UE::Math::TPlane< T > &P1, const UE::Math::TPlane< T > &P2)
template<typename T>
bool IntersectPlanes3 (UE::Math::TVector< T > &I, const UE::Math::TPlane< T > &P1, const UE::Math::TPlane< T > &P2, const UE::Math::TPlane< T > &P3)
template<typename T, typename U>
FORCEINLINE_DEBUGGABLE UE::Math::TRotator< T > LerpRange (const UE::Math::TRotator< T > &A, const UE::Math::TRotator< T > &B, U Alpha)
template<typename T>
UE::Math::TVector< T > LinePlaneIntersection (const UE::Math::TVector< T > &Point1, const UE::Math::TVector< T > &Point2, const UE::Math::TPlane< T > &Plane)
template<typename T>
UE::Math::TVector< T > LinePlaneIntersection (const UE::Math::TVector< T > &Point1, const UE::Math::TVector< T > &Point2, const UE::Math::TVector< T > &PlaneOrigin, const UE::Math::TVector< T > &PlaneNormal)
template<typename T>
bool LineSphereIntersection (const UE::Math::TVector< T > &Start, const UE::Math::TVector< T > &Dir, T Length, const UE::Math::TVector< T > &Origin, T Radius)
MIX_FLOATS_2_ARGS (GridSnap)
Allow mixing float/double arguments, promoting to highest precision type.
MIX_FLOATS_3_ARGS (Clamp)
Allow mixing float/double arguments, promoting to highest precision type.
template<typename T>
UE::Math::TVector< T > RayPlaneIntersection (const UE::Math::TVector< T > &RayOrigin, const UE::Math::TVector< T > &RayDirection, const UE::Math::TPlane< T > &Plane)
template<typename T>
T RayPlaneIntersectionParam (const UE::Math::TVector< T > &RayOrigin, const UE::Math::TVector< T > &RayDirection, const UE::Math::TPlane< T > &Plane)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (FRandRange)
RESOLVE_FLOAT_AMBIGUITY_3_ARGS (ClampAngle)
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS (IsNearlyEqual)
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS (IsNearlyZero)
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_3_ARGS (IsNearlyEqual)
template<typename T UE_REQUIRES>
UE_DEPRECATED (5.5, "Use of FMath::Wrap with non-floating point arguments is deprecated - consider FMath::WrapExclusive instead.") static const expr FORCEINLINE T Wrap(const T X
Static Public Member Functions
static void ApplyScaleToFloat (float &Dst, const FVector &DeltaScale, float Magnitude=1.0f)
Handy to apply scaling in the editor.
template<typename T, typename U UE_REQUIRES>
static constexpr FORCEINLINE_DEBUGGABLE T BiLerp (const T &P00, const T &P10, const T &P01, const T &P11, const U &FracX, const U &FracY)
Performs a 2D linear interpolation between four values values, FracX, FracY ranges from 0-1.
template<typename T, typename U UE_REQUIRES>
static FORCEINLINE_DEBUGGABLE T BiLerp (const T &P00, const T &P10, const T &P01, const T &P11, const U &FracX, const U &FracY)
Custom lerps defined for those classes not suited to the default implemenation.
template<typename T>
static FORCEINLINE void CartesianToPolar (const T X, const T Y, T &OutRad, T &OutAng)
Converts given Cartesian coordinate pair to Polar coordinate system.
template<typename T>
static FORCEINLINE void CartesianToPolar (const UE::Math::TVector2< T > InCart, UE::Math::TVector2< T > &OutPolar)
Converts given Cartesian coordinate pair to Polar coordinate system.
static FLinearColor CInterpTo (const FLinearColor &Current, const FLinearColor &Target, float DeltaTime, float InterpSpeed)
Interpolate Linear Color from Current to Target.
static constexpr FORCEINLINE double Clamp (const double X, const double Min, const double Max)
static constexpr FORCEINLINE float Clamp (const float X, const float Min, const float Max)
Clamps X to be between Min and Max, inclusive.
static constexpr FORCEINLINE int64 Clamp (const int64 X, const int32 Min, const int32 Max)
Clamps X to be between Min and Max, inclusive.
template<class T>
static constexpr FORCEINLINE T Clamp (const T X, const T MinValue, const T MaxValue)
Clamps X to be between Min and Max, inclusive.
template<typename T>
static T ClampAngle (T AngleDegrees, T MinAngleDegrees, T MaxAngleDegrees)
Clamps an arbitrary angle to be between the given angles.
static FVector ClosestPointOnInfiniteLine (const FVector &LineStart, const FVector &LineEnd, const FVector &Point)
Find the point on the infinite line between two points (LineStart, LineEnd) which is closest to Point.
template<typename T>
static UE::Math::TVector< T > ClosestPointOnLine (const UE::Math::TVector< T > &LineStart, const UE::Math::TVector< T > &LineEnd, const UE::Math::TVector< T > &Point)
Find the point on the line segment from LineStart to LineEnd which is closest to Point.
template<typename T>
static UE::Math::TVector< T > ClosestPointOnSegment (const UE::Math::TVector< T > &Point, const UE::Math::TVector< T > &StartPoint, const UE::Math::TVector< T > &EndPoint)
Returns closest point on a segment to a given point.
template<typename T>
static UE::Math::TVector2< T > ClosestPointOnSegment2D (const UE::Math::TVector2< T > &Point, const UE::Math::TVector2< T > &StartPoint, const UE::Math::TVector2< T > &EndPoint)
FVector2D version of ClosestPointOnSegment.
static FVector ClosestPointOnTetrahedronToPoint (const FVector &Point, const FVector &A, const FVector &B, const FVector &C, const FVector &D)
Returns closest point on a tetrahedron to a point.
static FVector ClosestPointOnTriangleToPoint (const FVector &Point, const FVector &A, const FVector &B, const FVector &C)
Returns closest point on a triangle to a point.
static FVector ComputeBaryCentric2D (const FVector &Point, const FVector &A, const FVector &B, const FVector &C)
Computes the barycentric coordinates for a given point in a 3D triangle.
static FVector4 ComputeBaryCentric3D (const FVector &Point, const FVector &A, const FVector &B, const FVector &C, const FVector &D)
Computes the barycentric coordinates for a given point on a tetrahedron (3D)
static bool ComputeBarycentricTri (const FVector &Point, const FVector &A, const FVector &B, const FVector &C, FVector &OutBarycentric, double Tolerance=(1.e-8))
Computes the barycentric coordinates for a given point in a triangle.
template<typename FReal>
static UE::Math::TSphere< FReal > ComputeBoundingSphereForCone (UE::Math::TVector< FReal > const &ConeOrigin, UE::Math::TVector< FReal > const &ConeDirection, FReal ConeRadius, FReal CosConeAngle, FReal SinConeAngle)
static uint32 ComputeProjectedSphereScissorRect (FIntRect &InOutScissorRect, FVector SphereOrigin, float Radius, FVector ViewOrigin, const FMatrix &ViewMatrix, const FMatrix &ProjMatrix)
template<class T>
static constexpr void CriticallyDampedSmoothing (T &InOutValue, T &InOutValueRate, const T &InTargetValue, const T &InTargetValueRate, const float InDeltaTime, const float InSmoothingTime)
Smooths a value using a critically damped spring.
template<class T>
static constexpr FORCEINLINE T Cube (const T A)
Cubes the value.
template<class U>
static constexpr FORCEINLINE_DEBUGGABLE U CubicCRSplineInterp (const U &P0, const U &P1, const U &P2, const U &P3, const float T0, const float T1, const float T2, const float T3, const float T)
template<class U>
static constexpr FORCEINLINE_DEBUGGABLE U CubicCRSplineInterpSafe (const U &P0, const U &P1, const U &P2, const U &P3, const float T0, const float T1, const float T2, const float T3, const float T)
template<typename T, typename U UE_REQUIRES>
static constexpr FORCEINLINE_DEBUGGABLE T CubicInterp (const T &P0, const T &T0, const T &P1, const T &T1, const U &A)
Performs a cubic interpolation.
template<typename T, typename U UE_REQUIRES>
static FORCEINLINE_DEBUGGABLE T CubicInterp (const T &P0, const T &T0, const T &P1, const T &T1, const U &A)
Custom lerps defined for those classes not suited to the default implemenation.
template<typename T, typename U UE_REQUIRES>
static constexpr FORCEINLINE_DEBUGGABLE T CubicInterpDerivative (const T &P0, const T &T0, const T &P1, const T &T1, const U &A)
Performs a first derivative cubic interpolation.
template<typename T, typename U UE_REQUIRES>
static constexpr FORCEINLINE_DEBUGGABLE T CubicInterpSecondDerivative (const T &P0, const T &T0, const T &P1, const T &T1, const U &A)
Performs a second derivative cubic interpolation.
static constexpr FORCEINLINE double DegreesToRadians (double const &DegVal)
static constexpr FORCEINLINE float DegreesToRadians (float const &DegVal)
template<class T>
static constexpr FORCEINLINE auto DegreesToRadians (T const &DegVal) -> decltype(DegVal *((3.1415926535897932f)/180.f))
Converts degrees to radians.
template<class T>
static constexpr FORCEINLINE T DivideAndRoundDown (T Dividend, T Divisor)
Divides two integers and rounds down.
template<class T>
static constexpr FORCEINLINE T DivideAndRoundNearest (T Dividend, T Divisor)
Divides two integers and rounds to nearest.
template<class T>
static constexpr FORCEINLINE T DivideAndRoundUp (T Dividend, T Divisor)
Divides two integers and rounds up.
template<typename T>
static T DynamicWeightedMovingAverage (T CurrentSample, T PreviousSample, T MaxDistance, T MinWeight, T MaxWeight)
Calculates the new value in a weighted moving average series using the previous value and a weight range.
static bool Eval (FString Str, float &OutValue)
Evaluates a numerical equation.
template<class T>
static constexpr void ExponentialSmoothingApprox (T &InOutValue, const T &InTargetValue, const float InDeltaTime, const float InSmoothingTime)
Smooths a value using exponential damping towards a target.
static constexpr bool ExtractBoolFromBitfield (const uint8 *Ptr, uint32 Index)
Get a bit in memory created from bitflags (uint32 Value:1), used for EngineShowFlags, TestBitFieldFunctions() tests the implementation.
static FORCEINLINE double FastAsin (double Value)
static FORCEINLINE float FastAsin (float Value)
Computes the ASin of a scalar value.
template<typename T, typename T2 UE_REQUIRES>
static constexpr auto FindDeltaAngleDegrees (T A1, T2 A2) -> decltype(A1 *A2)
Find the smallest angle between two headings (in degrees)
template<typename T, typename T2 UE_REQUIRES>
static constexpr auto FindDeltaAngleRadians (T A1, T2 A2) -> decltype(A1 *A2)
Find the smallest angle between two headings (in radians)
template<typename T1, typename T2 = T1, typename T3 = T2, typename T4 = T3>
static auto FInterpConstantTo (T1 Current, T2 Target, T3 DeltaTime, T4 InterpSpeed)
Interpolate float from Current to Target with constant step.
template<typename T1, typename T2 = T1, typename T3 = T2, typename T4 = T3>
static auto FInterpTo (T1 Current, T2 Target, T3 DeltaTime, T4 InterpSpeed)
Interpolate float from Current to Target.
static float FixedTurn (float InCurrent, float InDesired, float InDeltaRate)
Returns a new rotation component value.
static FORCEINLINE double Floor (double F)
Converts a double to a nearest less or equal integer.
static FORCEINLINE float Floor (float F)
Converts a float to a nearest less or equal integer.
template<typename IntegralType UE_REQUIRES>
static constexpr FORCEINLINE IntegralType Floor (IntegralType I)
Converts an integral type to a nearest less or equal integer.
static FString FormatIntToHumanReadable (int32 Val)
Formats an integer value into a human readable string (i.e.
static FORCEINLINE double FRandRange (double InMin, double InMax)
Util to generate a random number in a range.
static FORCEINLINE float FRandRange (float InMin, float InMax)
Util to generate a random number in a range.
static FVector2D GetAzimuthAndElevation (const FVector &Direction, const FVector &AxisX, const FVector &AxisY, const FVector &AxisZ)
Returns Azimuth and Elevation of vector 'Direction' in coordinate system O(AxisX,AxisY,AxisZ).
static FVector GetBaryCentric2D (const FVector &Point, const FVector &A, const FVector &B, const FVector &C)
Computes the barycentric coordinates for a given point in a triangle, only considering the XY coordinates - simpler than the Compute versions.
static FVector GetBaryCentric2D (const FVector2D &Point, const FVector2D &A, const FVector2D &B, const FVector2D &C)
Computes the barycentric coordinates for a given point in a triangle - simpler than the Compute versions.
static bool GetDistanceWithinConeSegment (FVector Point, FVector ConeStartPoint, FVector ConeLine, float RadiusAtStart, float RadiusAtEnd, float &PercentageOut)
Calculates whether a Point is within a cone segment, and also what percentage within the cone (100% is along the center line, whereas 0% is along the edge)
static bool GetDotDistance (FVector2D &OutDotDist, const FVector &Direction, const FVector &AxisX, const FVector &AxisY, const FVector &AxisZ)
Calculates the dotted distance of vector 'Direction' to coordinate system O(AxisX,AxisY,AxisZ).
template<class T>
static FORCEINLINE T GetMappedRangeValueClamped (const TRange< T > &InputRange, const TRange< T > &OutputRange, const T Value)
template<typename T, typename T2>
static FORCEINLINE auto GetMappedRangeValueClamped (const UE::Math::TVector2< T > &InputRange, const UE::Math::TVector2< T > &OutputRange, const T2 Value)
For the given Value clamped to the [Input:Range] inclusive, returns the corresponding percentage in [Output:Range] Inclusive.
template<typename T, typename T2>
static FORCEINLINE auto GetMappedRangeValueUnclamped (const UE::Math::TVector2< T > &InputRange, const UE::Math::TVector2< T > &OutputRange, const T2 Value)
Transform the given Value relative to the input range to the Output Range.
template<typename T, typename T2 UE_REQUIRES>
static constexpr FORCEINLINE auto GetRangePct (T MinValue, T MaxValue, T2 Value)
Calculates the percentage along a line from MinValue to MaxValue that Value is.
template<class T>
static FORCEINLINE double GetRangePct (TRange< T > const &Range, T Value)
template<typename T, typename T2 UE_REQUIRES>
static auto GetRangePct (UE::Math::TVector2< T > const &Range, T2 Value)
Same as above, but taking a 2d vector as the range.
template<class T>
static FORCEINLINE T GetRangeValue (TRange< T > const &Range, T Pct)
template<typename T, typename T2 UE_REQUIRES>
static auto GetRangeValue (UE::Math::TVector2< T > const &Range, T2 Pct)
Basically a Vector2d version of Lerp.
static FVector GetReflectionVector (const FVector &Direction, const FVector &SurfaceNormal)
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
static float GetTForSegmentPlaneIntersect (const FVector &StartPoint, const FVector &EndPoint, const FPlane &Plane)
returns the time (t) of the intersection of the passed segment and a plane (could be <0 or >1)
static constexpr int32 GreatestCommonDivisor (int32 a, int32 b)
template<class T>
static constexpr FORCEINLINE T GridSnap (T Location, T Grid)
Snaps a value to the nearest grid multiple.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpCircularIn (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a circular in function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpCircularInOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a circular in/out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpCircularOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a circular out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpEaseIn (const T &A, const T &B, float Alpha, float Exp)
Interpolate between A and B, applying an ease in function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpEaseInOut (const T &A, const T &B, float Alpha, float Exp)
Interpolate between A and B, applying an ease in/out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpEaseOut (const T &A, const T &B, float Alpha, float Exp)
Interpolate between A and B, applying an ease out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpExpoIn (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying an exponential in function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpExpoInOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying an exponential in/out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpExpoOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying an exponential out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpSinIn (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a sinusoidal in function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpSinInOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a sinusoidal in/out function.
template<class T>
static FORCEINLINE_DEBUGGABLE T InterpSinOut (const T &A, const T &B, float Alpha)
Interpolation between A and B, applying a sinusoidal out function.
template<class T>
static constexpr FORCEINLINE_DEBUGGABLE T InterpStep (const T &A, const T &B, float Alpha, int32 Steps)
Interpolation between A and B, applying a step function.
template<typename FReal>
static bool IntersectPlanes2 (UE::Math::TVector< FReal > &I, UE::Math::TVector< FReal > &D, const UE::Math::TPlane< FReal > &P1, const UE::Math::TPlane< FReal > &P2)
Compute intersection point and direction of line joining two planes.
template<typename FReal>
static bool IntersectPlanes3 (UE::Math::TVector< FReal > &I, const UE::Math::TPlane< FReal > &P1, const UE::Math::TPlane< FReal > &P2, const UE::Math::TPlane< FReal > &P3)
Compute intersection point of three planes.
template<class T>
static constexpr T InvExpApprox (T X)
Returns an approximation of Exp(-X) based on a Taylor expansion that has had the coefficients adjusted (using optimisation) to minimise the error in the range 0 < X < 1, which is below 0.1%.
static FORCEINLINE bool IsNearlyEqual (double A, double B, double ErrorTolerance=(1.e-8))
static FORCEINLINE bool IsNearlyEqual (float A, float B, float ErrorTolerance=(1.e-8f))
Checks if two floating point numbers are nearly equal.
static FORCEINLINE bool IsNearlyEqualByULP (double A, double B, int32 MaxUlps=4)
Check if two floating point numbers are nearly equal to within specific number of units of last place (ULP).
static FORCEINLINE bool IsNearlyEqualByULP (float A, float B, int32 MaxUlps=4)
Check if two floating point numbers are nearly equal to within specific number of units of last place (ULP).
static FORCEINLINE bool IsNearlyZero (double Value, double ErrorTolerance=(1.e-8))
Checks if a floating point number is nearly zero.
static FORCEINLINE bool IsNearlyZero (float Value, float ErrorTolerance=(1.e-8f))
Checks if a floating point number is nearly zero.
template<typename T>
static constexpr FORCEINLINE bool IsPowerOfTwo (T Value)
Checks whether a number is a power of two.
template<class T, class U>
static constexpr FORCEINLINE bool IsWithin (const T &TestValue, const U &MinValue, const U &MaxValue)
Checks if value is within a range, exclusive on MaxValue)
template<class T, class U>
static constexpr FORCEINLINE bool IsWithinInclusive (const T &TestValue, const U &MinValue, const U &MaxValue)
Checks if value is within a range, inclusive on MaxValue)
static constexpr int32 LeastCommonMultiplier (int32 a, int32 b)
template<typename T, typename U UE_REQUIRES>
static constexpr FORCEINLINE_DEBUGGABLE T Lerp (const T &A, const T &B, const U &Alpha)
Performs a linear interpolation between two values, Alpha ranges from 0-1.
template<typename T, typename U UE_REQUIRES>
static FORCEINLINE_DEBUGGABLE T Lerp (const T &A, const T &B, const U &Alpha)
Custom lerps defined for those classes not suited to the default implemenation.
template<typename T1, typename T2, typename T3 UE_REQUIRES>
static auto Lerp (const T1 &A, const T2 &B, const T3 &Alpha) -> decltype(A *B)
template<typename T, typename U>
static UE::Math::TRotator< T > LerpRange (const UE::Math::TRotator< T > &A, const UE::Math::TRotator< T > &B, U Alpha)
template<class T>
static constexpr FORCEINLINE_DEBUGGABLE T LerpStable (const T &A, const T &B, double Alpha)
Performs a linear interpolation between two values, Alpha ranges from 0-1.
template<class T>
static constexpr FORCEINLINE_DEBUGGABLE T LerpStable (const T &A, const T &B, float Alpha)
Performs a linear interpolation between two values, Alpha ranges from 0-1.
template<typename T1, typename T2, typename T3 UE_REQUIRES>
static auto LerpStable (const T1 &A, const T2 &B, const T3 &Alpha) -> decltype(A *B)
template<typename FReal>
static bool LineBoxIntersection (const UE::Math::TBox< FReal > &Box, const UE::Math::TVector< FReal > &Start, const UE::Math::TVector< FReal > &End, const UE::Math::TVector< FReal > &Direction)
Determines whether a line intersects a box.
template<typename FReal>
static bool LineBoxIntersection (const UE::Math::TBox< FReal > &Box, const UE::Math::TVector< FReal > &Start, const UE::Math::TVector< FReal > &End, const UE::Math::TVector< FReal > &Direction, const UE::Math::TVector< FReal > &OneOverDirection)
Determines whether a line intersects a box.
static bool LineExtentBoxIntersection (const FBox &inBox, const FVector &Start, const FVector &End, const FVector &Extent, FVector &HitLocation, FVector &HitNormal, float &HitTime)
template<typename FReal>
static UE::Math::TVector< FReal > LinePlaneIntersection (const UE::Math::TVector< FReal > &Point1, const UE::Math::TVector< FReal > &Point2, const UE::Math::TPlane< FReal > &Plane)
Find the intersection of a line and a plane.
template<typename FReal>
static UE::Math::TVector< FReal > LinePlaneIntersection (const UE::Math::TVector< FReal > &Point1, const UE::Math::TVector< FReal > &Point2, const UE::Math::TVector< FReal > &PlaneOrigin, const UE::Math::TVector< FReal > &PlaneNormal)
Find the intersection of a line and an offset plane.
template<typename FReal>
static bool LineSphereIntersection (const UE::Math::TVector< FReal > &Start, const UE::Math::TVector< FReal > &Dir, FReal Length, const UE::Math::TVector< FReal > &Origin, FReal Radius)
Determines whether a line intersects a sphere.
static FORCEINLINE double Log2 (double Value)
Computes the base 2 logarithm of the specified value.
static FORCEINLINE float Log2 (float Value)
Computes the base 2 logarithm of the specified value.
static float MakePulsatingValue (const double InCurrentTime, const float InPulsesPerSecond, const float InPhase=0.0f)
Simple function to create a pulsating scalar value.
static bool MatrixInverse (FMatrix44d *DstMatrix, const FMatrix44d *SrcMatrix)
static bool MatrixInverse (FMatrix44f *DstMatrix, const FMatrix44f *SrcMatrix)
Calculate the inverse of an FMatrix44.
template<class T>
static constexpr FORCEINLINE T Max3 (const T A, const T B, const T C)
Returns highest of 3 values.
template<class T>
static constexpr FORCEINLINE int32 Max3Index (const T A, const T B, const T C)
static bool MemoryTest (void *BaseAddress, uint32 NumBytes)
Tests a memory region to see that it's working properly.
template<class T>
static constexpr FORCEINLINE T Min3 (const T A, const T B, const T C)
Returns lowest of 3 values.
template<class T>
static constexpr FORCEINLINE int32 Min3Index (const T A, const T B, const T C)
Returns index of the lowest value.
template<typename ValueType, typename BaseType>
static constexpr FORCEINLINE auto Modulo (ValueType Value, BaseType Base)
static float PerlinNoise1D (float Value)
Generates a 1D Perlin noise from the given value.
static float PerlinNoise2D (const FVector2D &Location)
Generates a 2D Perlin noise sample at the given location.
static float PerlinNoise3D (const FVector &Location)
Generates a 3D Perlin noise sample at the given location.
static bool PlaneAABBIntersection (const FPlane &P, const FBox &AABB)
Determine if a plane and an AABB intersect.
static int32 PlaneAABBRelativePosition (const FPlane &P, const FBox &AABB)
Determine the position of an AABB relative to a plane: completely above (in the direction of the normal of the plane), completely below or intersects it.
template<typename FReal>
static bool PointBoxIntersection (const UE::Math::TVector< FReal > &Point, const UE::Math::TBox< FReal > &Box)
Determines whether a point is inside a box.
static float PointDistToLine (const FVector &Point, const FVector &Direction, const FVector &Origin)
static float PointDistToLine (const FVector &Point, const FVector &Direction, const FVector &Origin, FVector &OutClosestPoint)
Calculates the distance of a given Point in world space to a given line, defined by the vector couple (Origin, Direction).
static float PointDistToSegment (const FVector &Point, const FVector &StartPoint, const FVector &EndPoint)
Returns distance from a point to the closest point on a segment.
static float PointDistToSegmentSquared (const FVector &Point, const FVector &StartPoint, const FVector &EndPoint)
Returns square of the distance from a point to the closest point on a segment.
static bool PointsAreCoplanar (const TArray< FVector > &Points, const float Tolerance=0.1f)
Determines whether a given set of points are coplanar, with a tolerance.
template<typename T>
static FORCEINLINE void PolarToCartesian (const T Rad, const T Ang, T &OutX, T &OutY)
Converts given Polar coordinate pair to Cartesian coordinate system.
template<typename T>
static FORCEINLINE void PolarToCartesian (const UE::Math::TVector2< T > InPolar, UE::Math::TVector2< T > &OutCart)
Converts given Polar coordinate pair to Cartesian coordinate system.
template<class T>
static UE::Math::TQuat< T > QInterpConstantTo (const UE::Math::TQuat< T > &Current, const UE::Math::TQuat< T > &Target, float DeltaTime, float InterpSpeed)
Interpolate quaternion from Current to Target with constant step (in radians)
template<class T>
static UE::Math::TQuat< T > QInterpTo (const UE::Math::TQuat< T > &Current, const UE::Math::TQuat< T > &Target, float DeltaTime, float InterpSpeed)
Interpolate quaternion from Current to Target.
static uint8 Quantize8SignedByte (float x)
static uint8 Quantize8UnsignedByte (float x)
static constexpr FORCEINLINE double RadiansToDegrees (double const &RadVal)
static constexpr FORCEINLINE float RadiansToDegrees (float const &RadVal)
template<class T>
static constexpr FORCEINLINE auto RadiansToDegrees (T const &RadVal) -> decltype(RadVal *(180.f/(3.1415926535897932f)))
Converts radians to degrees.
static FORCEINLINE bool RandBool ()
Util to generate a random boolean.
static FORCEINLINE int32 RandHelper (int32 A)
Helper function for rand implementations.
static FORCEINLINE int64 RandHelper64 (int64 A)
static FVector RandPointInBox (const FBox &Box)
Returns a random point within the passed in bounding box.
static FVector2D RandPointInCircle (float CircleRadius)
Returns a random point, uniformly distributed, within the specified radius.
static FORCEINLINE double RandRange (double InMin, double InMax)
static FORCEINLINE float RandRange (float InMin, float InMax)
Util to generate a random number in a range.
static FORCEINLINE int32 RandRange (int32 Min, int32 Max)
Helper function for rand implementations.
static FORCEINLINE int64 RandRange (int64 Min, int64 Max)
template<typename FReal>
static UE::Math::TVector< FReal > RayPlaneIntersection (const UE::Math::TVector< FReal > &RayOrigin, const UE::Math::TVector< FReal > &RayDirection, const UE::Math::TPlane< FReal > &Plane)
Find the intersection of a ray and a plane.
template<typename FReal>
static FReal RayPlaneIntersectionParam (const UE::Math::TVector< FReal > &RayOrigin, const UE::Math::TVector< FReal > &RayDirection, const UE::Math::TPlane< FReal > &Plane)
Find the intersection of a ray and a plane.
static FRotator RInterpConstantTo (const FRotator &Current, const FRotator &Target, float DeltaTime, float InterpSpeed)
Interpolate rotator from Current to Target with constant step.
static FRotator RInterpTo (const FRotator &Current, const FRotator &Target, float DeltaTime, float InterpSpeed)
Interpolate rotator from Current to Target.
static FORCEINLINE double RoundFromZero (double F)
static FORCEINLINE float RoundFromZero (float F)
Converts a floating point number to an integer which is further from zero, "larger" in absolute value: 0.1 becomes 1, -0.1 becomes -1.
static double RoundHalfFromZero (double F)
static float RoundHalfFromZero (float F)
Converts a floating point number to the nearest integer, equidistant ties go to the value which is further from zero: -0.5 becomes -1.0, 0.5 becomes 1.0.
static double RoundHalfToEven (double F)
static float RoundHalfToEven (float F)
Converts a floating point number to the nearest integer, equidistant ties go to the value which is closest to an even value: 1.5 becomes 2, 0.5 becomes 0.
static double RoundHalfToZero (double F)
static float RoundHalfToZero (float F)
Converts a floating point number to the nearest integer, equidistant ties go to the value which is closer to zero: -0.5 becomes 0, 0.5 becomes 0.
static FORCEINLINE double RoundToNegativeInfinity (double F)
static FORCEINLINE float RoundToNegativeInfinity (float F)
Converts a floating point number to an integer which is more negative: 0.1 becomes 0, -0.1 becomes -1.
static FORCEINLINE double RoundToPositiveInfinity (double F)
static FORCEINLINE float RoundToPositiveInfinity (float F)
Converts a floating point number to an integer which is more positive: 0.1 becomes 1, -0.1 becomes 0.
static FORCEINLINE double RoundToZero (double F)
static FORCEINLINE float RoundToZero (float F)
Converts a floating point number to an integer which is closer to zero, "smaller" in absolute value: 0.1 becomes 0, -0.1 becomes 0.
static void SegmentDistToSegment (FVector A1, FVector B1, FVector A2, FVector B2, FVector &OutP1, FVector &OutP2)
Find closest points between 2 segments.
template<typename T>
static void SegmentDistToSegmentSafe (UE::Math::TVector< T > A1, UE::Math::TVector< T > B1, UE::Math::TVector< T > A2, UE::Math::TVector< T > B2, UE::Math::TVector< T > &OutP1, UE::Math::TVector< T > &OutP2)
Find closest points between 2 segments.
static bool SegmentIntersection2D (const FVector &SegmentStartA, const FVector &SegmentEndA, const FVector &SegmentStartB, const FVector &SegmentEndB, FVector &out_IntersectionPoint)
Returns true if there is an intersection between the segment specified by SegmentStartA and SegmentEndA, and the segment specified by SegmentStartB and SegmentEndB, in 2D space.
static bool SegmentPlaneIntersection (const FVector &StartPoint, const FVector &EndPoint, const FPlane &Plane, FVector &out_IntersectionPoint)
Returns true if there is an intersection between the segment specified by StartPoint and Endpoint, and the plane on which polygon Plane lies.
static bool SegmentTriangleIntersection (const FVector &StartPoint, const FVector &EndPoint, const FVector &A, const FVector &B, const FVector &C, FVector &OutIntersectPoint, FVector &OutTriangleNormal)
Returns true if there is an intersection between the segment specified by StartPoint and Endpoint, and the Triangle defined by A, B and C.
static constexpr void SetBoolInBitField (uint8 *Ptr, uint32 Index, bool bSet)
Set a bit in memory created from bitflags (uint32 Value:1), used for EngineShowFlags, TestBitFieldFunctions() tests the implementation.
static FORCEINLINE void SinCos (double *ScalarSin, double *ScalarCos, double Value)
template<typename T UE_REQUIRES>
static constexpr FORCEINLINE void SinCos (std::decay_t< T > *ScalarSin, std::decay_t< T > *ScalarCos, T Value)
Computes the sine and cosine of a scalar value.
template<typename T, typename U UE_REQUIRES>
static FORCEINLINE void SinCos (T *ScalarSin, T *ScalarCos, U Value)
template<typename T>
static constexpr T SmoothStep (T A, T B, T X)
Returns a smooth Hermite interpolation between 0 and 1 for the value X (where X ranges between A and B) Clamped to 0 for X <= A and 1 for X >= B.
template<typename FReal>
static bool SphereAABBIntersection (const UE::Math::TSphere< FReal > &Sphere, const UE::Math::TBox< FReal > &AABB)
Converts a sphere into a point plus radius squared for the test above.
template<typename FReal>
static bool SphereAABBIntersection (const UE::Math::TVector< FReal > &SphereCenter, const FReal RadiusSquared, const UE::Math::TBox< FReal > &AABB)
Performs a sphere vs box intersection test using Arvo's algorithm:
static bool SphereConeIntersection (const FVector &SphereCenter, float SphereRadius, const FVector &ConeAxis, float ConeAngleSin, float ConeAngleCos)
Assumes the cone tip is at 0,0,0 (means the SphereCenter is relative to the cone tip)
static void SphereDistToLine (FVector SphereOrigin, float SphereRadius, FVector LineOrigin, FVector LineDir, FVector &OutClosestPoint)
Find closest point on a Sphere to a Line.
template<class T>
static void SpringDamper (T &InOutValue, T &InOutValueRate, const T &InTargetValue, const T &InTargetValueRate, const float InDeltaTime, const float InUndampedFrequency, const float InDampingRatio)
Smooths a value using a spring damper towards a target.
template<class T>
static void SpringDamperSmoothing (T &InOutValue, T &InOutValueRate, const T &InTargetValue, const T &InTargetValueRate, const float InDeltaTime, const float InSmoothingTime, const float InDampingRatio)
Smooths a value using a spring damper towards a target.
template<class T>
static constexpr FORCEINLINE T Square (const T A)
Multiples value by itself.
static double TruncateToHalfIfClose (double F, double Tolerance=(1.e-8f))
static float TruncateToHalfIfClose (float F, float Tolerance=(1.e-8f))
Truncates a floating point number to half if closer than the given tolerance.
template<typename T UE_REQUIRES>
static constexpr T UnwindDegrees (T A)
Utility to ensure angle is between +/- 180 degrees by unwinding.
template<typename T UE_REQUIRES>
static constexpr T UnwindRadians (T A)
Given a heading which may be outside the +/- PI range, 'unwind' it back into that range.
static FVector2D Vector2DInterpConstantTo (const FVector2D &Current, const FVector2D &Target, float DeltaTime, float InterpSpeed)
Interpolate vector2D from Current to Target with constant step.
template<typename T>
static UE::Math::TVector2< T > Vector2DInterpTo (const UE::Math::TVector2< T > &Current, const UE::Math::TVector2< T > &Target, float DeltaTime, float InterpSpeed)
Interpolate vector2D from Current to Target.
static FVector VInterpConstantTo (const FVector &Current, const FVector &Target, float DeltaTime, float InterpSpeed)
Interpolate vector from Current to Target with constant step.
static FVector VInterpNormalRotationTo (const FVector &Current, const FVector &Target, float DeltaTime, float RotationSpeedDegrees)
Interpolate a normal vector Current to Target, by interpolating the angle between those vectors with constant step.
static FVector VInterpTo (const FVector &Current, const FVector &Target, float DeltaTime, float InterpSpeed)
Interpolate vector from Current to Target.
static FVector VRand ()
Return a uniformly distributed random unit length vector = point on the unit sphere surface.
static FVector VRandCone (FVector const &Dir, float ConeHalfAngleRad)
Returns a random unit vector, uniformly distributed, within the specified cone ConeHalfAngleRad is the half-angle of cone, in radians.
static FVector VRandCone (FVector const &Dir, float HorizontalConeHalfAngleRad, float VerticalConeHalfAngleRad)
This is a version of VRandCone that handles "squished" cones, i.e.
template<typename T>
static T WeightedMovingAverage (T CurrentSample, T PreviousSample, T Weight)
Calculates the new value in a weighted moving average series using the previous value and the weight.
static void WindRelativeAnglesDegrees (double InAngle0, double &InOutAngle1)
static void WindRelativeAnglesDegrees (float InAngle0, float &InOutAngle1)
Given two angles in degrees, 'wind' the rotation in Angle1 so that it avoids >180 degree flips.
template<typename T UE_REQUIRES>
static constexpr FORCEINLINE T Wrap (const T X, const T Min, const T Max)
Wraps X to be between Min and Max, inclusive.
template<typename T UE_REQUIRES>
static constexpr FORCEINLINE T WrapExclusive (const T X, const T Min, const T Max)
Wraps X to be between Min and Max, exclusive.
Data Fields
const T const T Max
const T Min
Static Public Attributes
static const uint32 BitFlag [32]
32 bit values where BitFlag[x] == (1<<x)
Static Private Member Functions
template<typename FloatType, typename IntegralType, IntegralType SignedBit>
static bool TIsNearlyEqualByULP (FloatType A, FloatType B, int32 MaxUlps)
template<class T>
static constexpr FORCEINLINE T WrapImpl (const T X, const T Min, const T Max)
Detailed Description
Structure for all math helper functions, inherits from platform math to pick up platform-specific implementations Check GenericPlatformMath.h for additional math functions.
Definition at line 266 of file UnrealMathUtility.h.
Member Function Documentation
ApplyScaleToFloat()
void FMath::ApplyScaleToFloat (float & Dst, const FVector & DeltaScale, float Magnitude = 1.0f) static
Handy to apply scaling in the editor.
Parameters
Dst in and out
References FVector.
BiLerp() [1/2]
template<typename T, typename U UE_REQUIRES> constexpr FORCEINLINE_DEBUGGABLE T FMath::BiLerp (const T & P00, const T & P10, const T & P01, const T & P11, const U & FracX, const U & FracY) inline static nodiscard constexpr
Performs a 2D linear interpolation between four values values, FracX, FracY ranges from 0-1.
Definition at line 1249 of file UnrealMathUtility.h.
References FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by FLandscapeConfigHelper::ResampleData().
BiLerp() [2/2]
template<typename T, typename U UE_REQUIRES> FORCEINLINE_DEBUGGABLE T FMath::BiLerp (const T & P00, const T & P10, const T & P01, const T & P11, const U & FracX, const U & FracY) inline static nodiscard
Custom lerps defined for those classes not suited to the default implemenation.
Definition at line 1264 of file UnrealMathUtility.h.
References FORCEINLINE_DEBUGGABLE.
CartesianToPolar() [1/2]
template<typename T> FORCEINLINE void FMath::CartesianToPolar (const T X, const T Y, T & OutRad, T & OutAng) inline static
Converts given Cartesian coordinate pair to Polar coordinate system.
Definition at line 1039 of file UnrealMathUtility.h.
References FORCEINLINE, Square(), X, and Y.
Referenced by CartesianToPolar().
CartesianToPolar() [2/2]
template<typename T> FORCEINLINE void FMath::CartesianToPolar (const UE::Math::TVector2< T > InCart, UE::Math::TVector2< T > & OutPolar) inline static
Converts given Cartesian coordinate pair to Polar coordinate system.
Definition at line 1046 of file UnrealMathUtility.h.
References CartesianToPolar(), FORCEINLINE, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
CInterpTo()
FLinearColor FMath::CInterpTo (const FLinearColor & Current, const FLinearColor & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate Linear Color from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
References DeltaTime, and Target.
Clamp() [1/4]
constexpr FORCEINLINE double FMath::Clamp (const double X, const double Min, const double Max) inline static nodiscard constexpr
Definition at line 601 of file UnrealMathUtility.h.
References Clamp(), FORCEINLINE, Max, Min, and X.
Clamp() [2/4]
constexpr FORCEINLINE float FMath::Clamp (const float X, const float Min, const float Max) inline static nodiscard constexpr
Clamps X to be between Min and Max, inclusive.
Explicitly defined here for floats/doubles because static analysis gets confused between template and int versions.
Definition at line 600 of file UnrealMathUtility.h.
References Clamp(), FORCEINLINE, Max, Min, and X.
Clamp() [3/4]
constexpr FORCEINLINE int64 FMath::Clamp (const int64 X, const int32 Min, const int32 Max) inline static nodiscard constexpr
Clamps X to be between Min and Max, inclusive.
Overload to support mixed int64/int32 types.
Definition at line 604 of file UnrealMathUtility.h.
References Clamp(), FORCEINLINE, Max, Min, and X.
Clamp() [4/4]
template<class T> constexpr FORCEINLINE T FMath::Clamp (const T X, const T MinValue, const T MaxValue) inline static nodiscard constexpr
Clamps X to be between Min and Max, inclusive.
Definition at line 592 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, and X.
Referenced by FFixedRGBASigned8::FFixedRGBASigned8(), FFrameTime::FFrameTime(), FKelvinletBrushOp::FKelvinletBrushOpProperties::FKelvinletBrushOpProperties(), FQuantizedSignedDistanceFieldShadowSample::FQuantizedSignedDistanceFieldShadowSample(), UE::Geometry::TBlendPairedKelvinlet< FTwistKelvinlet, FLaplacianPullKelvinlet >::TBlendPairedKelvinlet(), UE::Geometry::TSparseListSet< ElementType >::TSparseListSet(), FBaseKelvinletBrushOp::ApplyFalloff(), FBuoyancyComponentSim::ApplyLinearDrag(), FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation(), ArrangeChildrenInStack(), FFrameRate::AsFrameNumber(), FFrameRate::AsFrameTime(), UE::Geometry::TSampledScalarField2< double, double >::BilinearSampleClamped(), UE::Geometry::TSampledScalarField2< double, double >::BilinearSampleGradientClamped(), UE::Math::TVector< T >::BoundToBox(), UE::Math::TVector< T >::BoundToCube(), UE::StructUtils::CalcMidIndexAndCount(), FCachedSystemScalabilityCVars::CalculateFieldOfViewDistanceScale(), Harmonix::Dsp::AudioAnalysis::CalculatePSNR(), Clamp(), Clamp(), Clamp(), TInterval< float >::Clamp(), UE::Geometry::FImageDimensions::Clamp(), UE::Geometry::FImageDimensions::Clamp(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Clamp(), UE::Geometry::TAxisAlignedBox3< float >::Clamp(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox::Clamp(), UE::Math::TVector2< T >::Clamp(), UE::MovieScene::Interpolation::FCachedInterpolationRange::Clamp(), UE::MovieScene::Interpolation::FCachedInterpolationRange::Clamp(), UE::Math::TVector2< T >::ClampAxes(), HarmonixDsp::ClampDB(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::ClampInt32(), UE::MovieScene::ClampToDiscreteRange(), ClampVector(), UE::Geometry::TOrientedBox2< float >::ClosestPoint(), UE::Geometry::TOrientedBox3< float >::ClosestPoint(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_tri_bboxes(), FBuoyancyComponentSim::ComputeBuoyancy(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), ConvertFrameTime(), ConvertFromLinearColor< uint8 >(), FStaticMeshComponentHelper::CreateSceneProxy(), DECLARE_MULTICAST_DELEGATE_OneParam(), UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery0D(), UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery1D(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::DrainPool(), FTriangleRasterizer< RasterPolicyType >::DrawTriangleTrapezoid(), DynamicWeightedMovingAverage(), FLandscapeConfigHelper::ExpandData(), FilteredVolumeLookup(), FInterpCurve< T >::FindNearestOnSegment(), UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), FInterpConstantTo(), FInterpTo(), FFrameTime::FromDecimal(), TShear2< float >::FromShearAngles(), TDefaultNumericTypeInterface< NumericType >::FromString(), GetACESTonemapParameters(), FSquare2DGridHelper::FGrid2D::GetCellCoords(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoords(), FLinearColor::GetClamped(), UE::Math::TVector2< T >::GetClampedToSize(), UE::Math::TVector< T >::GetClampedToSize(), UE::Math::TVector< T >::GetClampedToSize2D(), FSimulationOutputRecord::GetInterpolated(), Audio::GetInterpolationParametersAtTimestamp(), GetMappedRangeValueClamped(), GetMappedRangeValueClamped(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::GetNodeLevelExtent(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetNodeLevelExtent(), UE::AnimNext::FTimelineState::GetPositionRatio(), UE::FTimeout::GetRemainingRoundedUpMilliseconds(), FTemporalLODState::GetTemporalLODTransition(), UWaterMeshComponent::GetTessellationFactor(), LandscapeDataAccess::GetTexHeight(), UE::Geometry::FImageTiling::GetTile(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), FSkinnedMeshComponentHelper::GetValidMinLOD(), SampledSequenceDrawingUtils::GroupInterleavedSampledTSIntoMinMaxBins(), TEvaluationTreeEntryContainer< ElementType >::Insert(), FAtmosphereSetup::InternalInit(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), FConstStructArrayView::Left(), FStructArrayView::Left(), TArrayView< FTransform >::Left(), TStringView< CharType >::Left(), FConstStructArrayView::LeftChop(), FStructArrayView::LeftChop(), TArrayView< FTransform >::LeftChop(), TStringView< CharType >::LeftChop(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial(), UE::Geometry::MakeUnitVector3(), TArrayView< FTransform >::Mid(), TStringView< CharType >::Mid(), MIX_FLOATS_3_ARGS(), URuntimeVirtualTextureComponent::NumStreamingMips(), FFrameNumber::operator*, FFrameNumber::operator/, FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedRGB10A2N::operator=(), FPackedRGB10A2N::operator=(), FPackedRGB10A2N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), UE::Geometry::FImageDimensions::PixelToCoords(), UE::Geometry::FSparseDynamicOctree3::PointToIndex(), UE::Geometry::FSparseDynamicPointOctree3::PointToIndex(), STreeView< FRigVMSearchResult >::PopulatePinnedItems(), SListView< TSharedPtr< FString > >::Private_SelectRangeFromCurrentTo(), SListView< TSharedPtr< FString > >::ReGenerateItems(), STileView< ItemType >::ReGenerateItems(), FConstStructArrayView::Right(), FStructArrayView::Right(), TArrayView< FTransform >::Right(), TStringView< CharType >::Right(), FConstStructArrayView::RightChop(), FStructArrayView::RightChop(), TArrayView< FTransform >::RightChop(), TStringView< CharType >::RightChop(), UE::Geometry::FNegativeSpaceSampleSettings::Sanitize(), STileView< ItemType >::ScrollIntoView(), TSimpleCellGrid< CellType, InvalidCellValue >::Serialize(), Harmonix::Dsp::Parameters::TParameter< uint8 >::Set(), FBaseKelvinletBrushOp::SetBaseProperties(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetBoneWeightsFromLerp(), FFloat16::SetClamped(), SGridPanel::FSlot::SetColumnSpan(), FMediaIOCoreSampleContainer< SampleType >::SetDataBufferSize(), FQuantizedSignedDistanceFieldShadowSample::SetFilterableComponent(), Harmonix::Dsp::Effects::TMultiChannelBiquadFilter< T, COUNT >::SetFreqTarget(), FStaticMeshInstanceData::SetInstanceLightMapDataInternal(), FSkeletalMeshStreamIn_IO::SetIORequest(), UE::Geometry::FGeneralizedCylinderGenerator::SetMiterLimitByAngle(), Audio::FMonoWaveTable::SetPosition(), SGridPanel::FSlot::SetRowSpan(), TLinearCircularRamper< T >::SetTarget(), UE::Geometry::FImageTiling::SetTiling(), TLinearCircularRamper< T >::SnapTo(), AnimEncoding::TimeToIndex(), FFloatAttributeColorMapper::ToColor(), FAnimNodeAlphaOptions::Update(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value(), FEvent::Wait(), WeightedMovingAverage(), and FArguments< ItemType >::ZoneFromPointerPosition().
ClampAngle() [1/2]
template<typename T> FORCEINLINE_DEBUGGABLE T FMath::ClampAngle (T AngleDegrees, T MinAngleDegrees, T MaxAngleDegrees)
Definition at line 947 of file Rotator.h.
References UE::Math::TRotator< T >::ClampAxis(), FORCEINLINE_DEBUGGABLE, and UE::Math::TRotator< T >::NormalizeAxis().
ClampAngle() [2/2]
template<typename T> T FMath::ClampAngle (T AngleDegrees, T MinAngleDegrees, T MaxAngleDegrees) static nodiscard
Clamps an arbitrary angle to be between the given angles.
Will clamp to nearest boundary.
Parameters
MinAngleDegrees "from" angle that defines the beginning of the range of valid angles (sweeping clockwise)
MaxAngleDegrees "to" angle that defines the end of the range of valid angles
Returns
Returns clamped angle in the range -180..180.
Referenced by RESOLVE_FLOAT_AMBIGUITY_3_ARGS().
ClosestPointOnInfiniteLine()
FVector FMath::ClosestPointOnInfiniteLine (const FVector & LineStart, const FVector & LineEnd, const FVector & Point) static nodiscard
Find the point on the infinite line between two points (LineStart, LineEnd) which is closest to Point.
References FVector, and Point.
ClosestPointOnLine()
template<typename T> UE::Math::TVector< T > FMath::ClosestPointOnLine (const UE::Math::TVector< T > & LineStart, const UE::Math::TVector< T > & LineEnd, const UE::Math::TVector< T > & Point) static nodiscard
Find the point on the line segment from LineStart to LineEnd which is closest to Point.
References Point.
ClosestPointOnSegment()
template<typename T> UE::Math::TVector< T > FMath::ClosestPointOnSegment (const UE::Math::TVector< T > & Point, const UE::Math::TVector< T > & StartPoint, const UE::Math::TVector< T > & EndPoint) static nodiscard
Returns closest point on a segment to a given point.
The idea is to project point on line formed by segment. Then we see if the closest point on the line is outside of segment or inside.
Parameters
Point point for which we find the closest point on the segment
StartPoint StartPoint of segment
EndPoint EndPoint of segment
Returns
point on the segment defined by (StartPoint, EndPoint) that is closest to Point.
References Point.
Referenced by UE::Math::TCapsuleShape< T >::IsInside().
ClosestPointOnSegment2D()
template<typename T> UE::Math::TVector2< T > FMath::ClosestPointOnSegment2D (const UE::Math::TVector2< T > & Point, const UE::Math::TVector2< T > & StartPoint, const UE::Math::TVector2< T > & EndPoint) static nodiscard
FVector2D version of ClosestPointOnSegment.
Returns closest point on a segment to a given 2D point. The idea is to project point on line formed by segment. Then we see if the closest point on the line is outside of segment or inside.
Parameters
Point point for which we find the closest point on the segment
StartPoint StartPoint of segment
EndPoint EndPoint of segment
Returns
point on the segment defined by (StartPoint, EndPoint) that is closest to Point.
References Point.
ClosestPointOnTetrahedronToPoint()
FVector FMath::ClosestPointOnTetrahedronToPoint (const FVector & Point, const FVector & A, const FVector & B, const FVector & C, const FVector & D) static nodiscard
Returns closest point on a tetrahedron to a point.
The idea is to identify the halfplanes that the point is in relative to each face of the tetrahedron
Parameters
Point point to check distance for
A,B,C,D four points defining a tetrahedron
Returns
Point on tetrahedron ABCD closest to given point
References A, B, FVector, and Point.
ClosestPointOnTriangleToPoint()
FVector FMath::ClosestPointOnTriangleToPoint (const FVector & Point, const FVector & A, const FVector & B, const FVector & C) static nodiscard
Returns closest point on a triangle to a point.
The idea is to identify the halfplanes that the point is in relative to each triangle segment "plane"
Parameters
Point point to check distance for
A,B,C counter clockwise ordering of points defining a triangle
Returns
Point on triangle ABC closest to given point
References A, B, FVector, and Point.
ComputeBaryCentric2D()
FVector FMath::ComputeBaryCentric2D (const FVector & Point, const FVector & A, const FVector & B, const FVector & C) static nodiscard
Computes the barycentric coordinates for a given point in a 3D triangle.
Note: Prefer the more accurately-named ComputeBarycentricTri instead.
Parameters
Point point to convert to barycentric coordinates (in plane of ABC)
A,B,C three non-collinear points defining a triangle in CCW
Returns
Vector containing the three weights a,b,c such that Point = a*A + b*B + c*C or Point = A + b*(B-A) + c*(C-A) = (1-b-c)*A + b*B + c*C
References A, B, FVector, and Point.
ComputeBaryCentric3D()
FVector4 FMath::ComputeBaryCentric3D (const FVector & Point, const FVector & A, const FVector & B, const FVector & C, const FVector & D) static nodiscard
Computes the barycentric coordinates for a given point on a tetrahedron (3D)
Parameters
Point point to convert to barycentric coordinates
A,B,C,D four points defining a tetrahedron
Returns
Vector containing the four weights a,b,c,d such that Point = a*A + b*B + c*C + d*D
References A, B, FVector, and Point.
ComputeBarycentricTri()
bool FMath::ComputeBarycentricTri (const FVector & Point, const FVector & A, const FVector & B, const FVector & C, FVector & OutBarycentric, double Tolerance = (1.e-8)) static nodiscard
Computes the barycentric coordinates for a given point in a triangle.
Parameters
Point point to convert to barycentric coordinates (in plane of ABC)
A,B,C three non-collinear points defining a triangle in CCW
OutBarycentric Vector containing the three weights a,b,c such that Point = a*A + b*B + c*C or Point = A + b*(B-A) + c*(C-A) = (1-b-c)*A + b*B + c*C
Tolerance Tolerance for ignoring too-small triangles
Returns
false if the result could not be computed (occurs when the triangle area is too small)
References A, B, FVector, Point, and UE_DOUBLE_SMALL_NUMBER.
ComputeBoundingSphereForCone() [1/2]
template<typename FReal> FORCEINLINE UE::Math::TSphere< FReal > FMath::ComputeBoundingSphereForCone (UE::Math::TVector< FReal > const & ConeOrigin, UE::Math::TVector< FReal > const & ConeDirection, FReal ConeRadius, FReal CosConeAngle, FReal SinConeAngle)
Computes minimal bounding sphere encompassing given cone.
Definition at line 394 of file Sphere.h.
References FORCEINLINE.
ComputeBoundingSphereForCone() [2/2]
template<typename FReal> UE::Math::TSphere< FReal > FMath::ComputeBoundingSphereForCone (UE::Math::TVector< FReal > const & ConeOrigin, UE::Math::TVector< FReal > const & ConeDirection, FReal ConeRadius, FReal CosConeAngle, FReal SinConeAngle) static nodiscard
ComputeProjectedSphereScissorRect()
uint32 FMath::ComputeProjectedSphereScissorRect (FIntRect & InOutScissorRect, FVector SphereOrigin, float Radius, FVector ViewOrigin, const FMatrix & ViewMatrix, const FMatrix & ProjMatrix) static nodiscard
References FVector.
CriticallyDampedSmoothing()
template<class T> constexpr void FMath::CriticallyDampedSmoothing (T & InOutValue, T & InOutValueRate, const T & InTargetValue, const T & InTargetValueRate, const float InDeltaTime, const float InSmoothingTime) inline static constexpr
Smooths a value using a critically damped spring.
Works for any type that supports basic arithmetic operations.
Note that InSmoothingTime is the time lag when tracking constant motion (so if you tracked a predicted position TargetVel * InSmoothingTime ahead, you'd match the target position)
An approximation is used that is accurate so long as InDeltaTime < 0.5 * InSmoothingTime
When starting from zero velocity, the maximum velocity is reached after time InSmoothingTime * 0.5
Parameters
InOutValue The value to be smoothed
InOutValueRate The rate of change of the value
InTargetValue The target to smooth towards
InTargetValueRate The target rate of change smooth towards. Note that if this is discontinuous, then the output will have discontinuous velocity too.
InDeltaTime Time interval
InSmoothingTime Timescale over which to smooth. Larger values result in more smoothed behaviour. Can be zero.
Definition at line 1680 of file UnrealMathUtility.h.
References A, B, Exp, InvExpApprox(), and UE_KINDA_SMALL_NUMBER.
Cube()
template<class T> constexpr FORCEINLINE T FMath::Cube (const T A) inline static nodiscard constexpr
Cubes the value.
Definition at line 585 of file UnrealMathUtility.h.
References A, and FORCEINLINE.
CubicCRSplineInterp()
template<class U> constexpr FORCEINLINE_DEBUGGABLE U FMath::CubicCRSplineInterp (const U & P0, const U & P1, const U & P2, const U & P3, const float T0, const float T1, const float T2, const float T3, const float T) inline static nodiscard constexpr
Definition at line 1486 of file UnrealMathUtility.h.
References FORCEINLINE_DEBUGGABLE.
CubicCRSplineInterpSafe()
template<class U> constexpr FORCEINLINE_DEBUGGABLE U FMath::CubicCRSplineInterpSafe (const U & P0, const U & P1, const U & P2, const U & P3, const float T0, const float T1, const float T2, const float T3, const float T) inline static nodiscard constexpr
Definition at line 1506 of file UnrealMathUtility.h.
References FORCEINLINE_DEBUGGABLE, and IsNearlyZero().
CubicInterp() [1/2]
template<typename T, typename U UE_REQUIRES> constexpr FORCEINLINE_DEBUGGABLE T FMath::CubicInterp (const T & P0, const T & T0, const T & P1, const T & T1, const U & A) inline static nodiscard constexpr
Performs a cubic interpolation.
Parameters
P - end points
T - tangent directions at end points
A - distance along spline
Returns
Interpolated value
Definition at line 1283 of file UnrealMathUtility.h.
References A, and FORCEINLINE_DEBUGGABLE.
Referenced by FInterpCurve< T >::Eval(), and FInterpCurve< T >::FindNearestOnSegment().
CubicInterp() [2/2]
template<typename T, typename U UE_REQUIRES> FORCEINLINE_DEBUGGABLE T FMath::CubicInterp (const T & P0, const T & T0, const T & P1, const T & T1, const U & A) inline static nodiscard
Custom lerps defined for those classes not suited to the default implemenation.
Definition at line 1297 of file UnrealMathUtility.h.
References A, and FORCEINLINE_DEBUGGABLE.
CubicInterpDerivative()
template<typename T, typename U UE_REQUIRES> constexpr FORCEINLINE_DEBUGGABLE T FMath::CubicInterpDerivative (const T & P0, const T & T0, const T & P1, const T & T1, const U & A) inline static nodiscard constexpr
Performs a first derivative cubic interpolation.
Parameters
P - end points
T - tangent directions at end points
A - distance along spline
Returns
Interpolated value
Definition at line 1316 of file UnrealMathUtility.h.
References A, and FORCEINLINE_DEBUGGABLE.
Referenced by FInterpCurve< T >::EvalDerivative().
CubicInterpSecondDerivative()
template<typename T, typename U UE_REQUIRES> constexpr FORCEINLINE_DEBUGGABLE T FMath::CubicInterpSecondDerivative (const T & P0, const T & T0, const T & P1, const T & T1, const U & A) inline static nodiscard constexpr
Performs a second derivative cubic interpolation.
Parameters
P - end points
T - tangent directions at end points
A - distance along spline
Returns
Interpolated value
Definition at line 1341 of file UnrealMathUtility.h.
References A, and FORCEINLINE_DEBUGGABLE.
Referenced by FInterpCurve< T >::EvalSecondDerivative().
DegreesToRadians() [1/3]
constexpr FORCEINLINE double FMath::DegreesToRadians (double const & DegVal) inline static constexpr
Definition at line 908 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_DOUBLE_PI.
DegreesToRadians() [2/3]
constexpr FORCEINLINE float FMath::DegreesToRadians (float const & DegVal) inline static constexpr
Definition at line 907 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_PI.
DegreesToRadians() [3/3]
template<class T> constexpr FORCEINLINE auto FMath::DegreesToRadians (T const & DegVal) -> decltype(DegVal * ((3.1415926535897932f) / 180.f)) inline static nodiscard constexpr
Converts degrees to radians.
Parameters
DegVal Value in degrees.
Returns
Value in radians.
Definition at line 902 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_PI.
Referenced by UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), FDisplayClusterWarpMPCDIAttributes::CalcProfile2DScreen(), FDisplayClusterWarpProjection::ConvertDegreesToProjection(), TShear2< float >::FromShearAngles(), UE::Math::TVector2< T >::GetRotated(), UE::Math::anonymous_namespace{ScaleRotationTranslationMatrix.h}::GetSinCos(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), BlendSpaceAnalysis::PitchQuat(), UE::Math::TVector< T >::RotateAngleAxis(), and BlendSpaceAnalysis::YawQuat().
DivideAndRoundDown()
template<class T> constexpr FORCEINLINE T FMath::DivideAndRoundDown (T Dividend, T Divisor) inline static nodiscard constexpr
Divides two integers and rounds down.
Definition at line 729 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by UE::Math::TIntPoint< IntType >::DivideAndRoundDown(), UE::Math::TIntPoint< IntType >::DivideAndRoundDown(), and TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl().
DivideAndRoundNearest()
template<class T> constexpr FORCEINLINE T FMath::DivideAndRoundNearest (T Dividend, T Divisor) inline static nodiscard constexpr
Divides two integers and rounds to nearest.
Definition at line 736 of file UnrealMathUtility.h.
References FORCEINLINE.
DivideAndRoundUp()
template<class T> constexpr FORCEINLINE T FMath::DivideAndRoundUp (T Dividend, T Divisor) inline static nodiscard constexpr
Divides two integers and rounds up.
Definition at line 722 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by FLandscapeGrassWeightExporter_RenderThread::FComponentInfo::FComponentInfo(), FQueuedDemoPacket::FQueuedDemoPacket(), FBitSet::CalculateNumWords(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), FCopyTextureCS::Dispatch(), UE::Math::TIntPoint< IntType >::DivideAndRoundUp(), UE::Math::TIntPoint< IntType >::DivideAndRoundUp(), UE::Math::TIntVector2< int32 >::DivideAndRoundUp(), UE::Math::TIntVector2< int32 >::DivideAndRoundUp(), UE::Math::TIntVector3< int32 >::DivideAndRoundUp(), UE::Math::TIntVector3< int32 >::DivideAndRoundUp(), UE::Math::TIntVector4< int32 >::DivideAndRoundUp(), UE::Math::TIntVector4< int32 >::DivideAndRoundUp(), ENUM_CLASS_FLAGS(), FHairStrandsBulkData::GetCurveAttributeSizeInBytes(), FComputeShaderUtils::GetGroupCount(), FComputeShaderUtils::GetGroupCount(), FComputeShaderUtils::GetGroupCount(), FComputeShaderUtils::GetGroupCount(), FComputeShaderUtils::GetGroupCount(), TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds >::GetGroupCount(), FComputeShaderUtils::GetGroupCountWrapped(), FComputeShaderUtils::GetGroupCountWrapped(), FMeshBatchDynamicPrimitiveData::GetPayloadFloat4Stride(), FHairStrandsBulkData::GetPointAttributeSizeInBytes(), FHairStrandsBulkData::GetPointToCurveSizeInBytes(), UE::FTimeout::GetRemainingRoundedUpMilliseconds(), FHairStrandsBulkData::GetTranscodedPositionSizeInBytes(), FInstanceAttributeTracker::MarkRemoved(), FInstanceAttributeTracker::SetNum(), and TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >::WriteMemoryImage().
DynamicWeightedMovingAverage()
template<typename T> T FMath::DynamicWeightedMovingAverage (T CurrentSample, T PreviousSample, T MaxDistance, T MinWeight, T MaxWeight) inline static nodiscard
Calculates the new value in a weighted moving average series using the previous value and a weight range.
The weight range is used to dynamically adjust based upon distance between the samples This allows you to smooth a value more aggressively for small noise and let large movements be smoothed less (or vice versa)
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
MaxDistance - Distance to use as the blend between min weight or max weight
MinWeight - The weight use when the distance is small
MaxWeight - The weight use when the distance is large
Returns
the next value in the series
Definition at line 2585 of file UnrealMathUtility.h.
References Clamp(), Distance, Lerp, Weight, and WeightedMovingAverage().
Eval()
bool FMath::Eval (FString Str, float & OutValue) static
Evaluates a numerical equation.
Operators and precedence: 1:+- 2:/% 3:* 4:^ 5:&| Unary: - Types: Numbers (0-9.), Hex ($0-$f) Grouping: ()
Parameters
Str String containing the equation.
OutValue Pointer to storage for the result.
Returns
1 if successful, 0 if equation fails.
ExponentialSmoothingApprox()
template<class T> constexpr void FMath::ExponentialSmoothingApprox (T & InOutValue, const T & InTargetValue, const float InDeltaTime, const float InSmoothingTime) inline static constexpr
Smooths a value using exponential damping towards a target.
Works for any type that supports basic arithmetic operations.
An approximation is used that is accurate so long as InDeltaTime < 0.5 * InSmoothingTime
Parameters
InOutValue The value to be smoothed
InTargetValue The target to smooth towards
InDeltaTime Time interval
InSmoothingTime Timescale over which to smooth. Larger values result in more smoothed behaviour. Can be zero.
Definition at line 1644 of file UnrealMathUtility.h.
References A, Exp, InvExpApprox(), and UE_KINDA_SMALL_NUMBER.
ExtractBoolFromBitfield()
constexpr bool FMath::ExtractBoolFromBitfield (const uint8 * Ptr, uint32 Index) inline static nodiscard constexpr
Get a bit in memory created from bitflags (uint32 Value:1), used for EngineShowFlags, TestBitFieldFunctions() tests the implementation.
Definition at line 2450 of file UnrealMathUtility.h.
References Mask.
FastAsin() [1/2]
FORCEINLINE double FMath::FastAsin (double Value) inline static nodiscard
Definition at line 874 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
FastAsin() [2/2]
FORCEINLINE float FMath::FastAsin (float Value) inline static nodiscard
Computes the ASin of a scalar value.
Parameters
Value input angle
Returns
ASin of Value
Definition at line 855 of file UnrealMathUtility.h.
References FASTASIN_HALF_PI, FORCEINLINE, and Value.
FindDeltaAngleDegrees()
template<typename T, typename T2 UE_REQUIRES> constexpr auto FMath::FindDeltaAngleDegrees (T A1, T2 A2) -> decltype(A1 * A2) inline static nodiscard constexpr
Find the smallest angle between two headings (in degrees)
Definition at line 928 of file UnrealMathUtility.h.
FindDeltaAngleRadians()
template<typename T, typename T2 UE_REQUIRES> constexpr auto FMath::FindDeltaAngleRadians (T A1, T2 A2) -> decltype(A1 * A2) inline static nodiscard constexpr
Find the smallest angle between two headings (in radians)
Definition at line 956 of file UnrealMathUtility.h.
References UE_PI, and UE_TWO_PI.
FInterpConstantTo()
template<typename T1, typename T2 = T1, typename T3 = T2, typename T4 = T3> auto FMath::FInterpConstantTo (T1 Current, T2 Target, T3 DeltaTime, T4 InterpSpeed) inline static nodiscard
Interpolate float from Current to Target with constant step.
Definition at line 1562 of file UnrealMathUtility.h.
References Clamp(), DeltaTime, Square(), Target, and UE_SMALL_NUMBER.
FInterpTo()
template<typename T1, typename T2 = T1, typename T3 = T2, typename T4 = T3> auto FMath::FInterpTo (T1 Current, T2 Target, T3 DeltaTime, T4 InterpSpeed) inline static nodiscard
Interpolate float from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
Definition at line 1581 of file UnrealMathUtility.h.
References Clamp(), DeltaTime, Square(), Target, and UE_SMALL_NUMBER.
FixedTurn()
float FMath::FixedTurn (float InCurrent, float InDesired, float InDeltaRate) static nodiscard
Returns a new rotation component value.
Parameters
InCurrent is the current rotation value
InDesired is the desired rotation value
InDeltaRate is the rotation amount to apply
Returns
a new rotation component value
Floor() [1/3]
FORCEINLINE double FMath::Floor (double F) inline static nodiscard
Converts a double to a nearest less or equal integer.
Definition at line 528 of file UnrealMathUtility.h.
References FORCEINLINE.
Floor() [2/3]
FORCEINLINE float FMath::Floor (float F) inline static nodiscard
Converts a float to a nearest less or equal integer.
Definition at line 522 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by anonymous_namespace{LandscapeLight.h}::GetTerrainExpandPatchCount(), GridSnap(), and Harmonix::Dsp::Parameters::TParameter< uint8 >::Set().
Floor() [3/3]
template<typename IntegralType UE_REQUIRES> constexpr FORCEINLINE IntegralType FMath::Floor (IntegralType I) inline static nodiscard constexpr
Converts an integral type to a nearest less or equal integer.
Unlike std::floor, it returns an IntegralType.
Definition at line 541 of file UnrealMathUtility.h.
References FORCEINLINE.
FormatIntToHumanReadable()
FString FMath::FormatIntToHumanReadable (int32 Val) static nodiscard
Formats an integer value into a human readable string (i.e.
12345 becomes "12,345")
Parameters
Val The value to use
Returns
FString The human readable string
FRandRange() [1/2]
FORCEINLINE double FMath::FRandRange (double InMin, double InMax) inline static nodiscard
Util to generate a random number in a range.
Definition at line 316 of file UnrealMathUtility.h.
References FORCEINLINE.
FRandRange() [2/2]
FORCEINLINE float FMath::FRandRange (float InMin, float InMax) inline static nodiscard
Util to generate a random number in a range.
Definition at line 310 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by RandRange(), RandRange(), and RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
GetAzimuthAndElevation()
FVector2D FMath::GetAzimuthAndElevation (const FVector & Direction, const FVector & AxisX, const FVector & AxisY, const FVector & AxisZ) static nodiscard
Returns Azimuth and Elevation of vector 'Direction' in coordinate system O(AxisX,AxisY,AxisZ).
Orientation: (consider 'O' the first person view of the player, and 'Direction' a vector pointing to an enemy)
positive azimuth means enemy is on the right of crosshair. (negative means left).
positive elevation means enemy is on top of crosshair, negative means below.
Parameters
Direction Direction of target.
AxisX X component of reference system.
AxisY Y component of reference system.
AxisZ Z component of reference system.
Returns
FVector2D X = Azimuth angle (in radians) (-PI, +PI) Y = Elevation angle (in radians) (-PI/2, +PI/2)
References FVector.
Referenced by FAtmosphereSetup::GetTransmittanceAtGroundLevel().
GetBaryCentric2D() [1/2]
FVector FMath::GetBaryCentric2D (const FVector & Point, const FVector & A, const FVector & B, const FVector & C) static nodiscard
Computes the barycentric coordinates for a given point in a triangle, only considering the XY coordinates - simpler than the Compute versions.
Parameters
Point point to convert to barycentric coordinates (in plane of ABC)
A,B,C three non-collinear points defining a triangle in CCW
Returns
Vector containing the three weights a,b,c such that Point = a*A + b*B + c*C or Point = A + b*(B-A) + c*(C-A) = (1-b-c)*A + b*B + c*C
References A, B, FVector, and Point.
GetBaryCentric2D() [2/2]
FVector FMath::GetBaryCentric2D (const FVector2D & Point, const FVector2D & A, const FVector2D & B, const FVector2D & C) static nodiscard
Computes the barycentric coordinates for a given point in a triangle - simpler than the Compute versions.
Parameters
Point point to convert to barycentric coordinates (in plane of ABC)
A,B,C three non-collinear points defining a triangle in CCW
Returns
Vector containing the three weights a,b,c such that Point = a*A + b*B + c*C or Point = A + b*(B-A) + c*(C-A) = (1-b-c)*A + b*B + c*C
References A, B, FVector, and Point.
GetDistanceWithinConeSegment()
bool FMath::GetDistanceWithinConeSegment (FVector Point, FVector ConeStartPoint, FVector ConeLine, float RadiusAtStart, float RadiusAtEnd, float & PercentageOut) static nodiscard
Calculates whether a Point is within a cone segment, and also what percentage within the cone (100% is along the center line, whereas 0% is along the edge)
Parameters
Point - The Point in question
ConeStartPoint - the beginning of the cone (with the smallest radius)
ConeLine - the line out from the start point that ends at the largest radius point of the cone
RadiusAtStart - the radius at the ConeStartPoint (0 for a 'proper' cone)
RadiusAtEnd - the largest radius of the cone
PercentageOut - output variable the holds how much within the cone the point is (1 = on center line, 0 = on exact edge or outside cone).
Returns
true if the point is within the cone, false otherwise.
References FVector, and Point.
GetDotDistance()
bool FMath::GetDotDistance (FVector2D & OutDotDist, const FVector & Direction, const FVector & AxisX, const FVector & AxisY, const FVector & AxisZ) static
Calculates the dotted distance of vector 'Direction' to coordinate system O(AxisX,AxisY,AxisZ).
Orientation: (consider 'O' the first person view of the player, and 'Direction' a vector pointing to an enemy)
positive azimuth means enemy is on the right of crosshair. (negative means left).
positive elevation means enemy is on top of crosshair, negative means below.
@Note: 'Azimuth' (.X) sign is changed to represent left/right and not front/behind. front/behind is the funtion's return value.
Parameters
OutDotDist .X = 'Direction' dot AxisX relative to plane (AxisX,AxisZ). (== Cos(Azimuth)) .Y = 'Direction' dot AxisX relative to plane (AxisX,AxisY). (== Sin(Elevation))
Direction direction of target.
AxisX X component of reference system.
AxisY Y component of reference system.
AxisZ Z component of reference system.
Returns
true if 'Direction' is facing AxisX (Direction dot AxisX >= 0.f)
References FVector.
GetMappedRangeValueClamped() [1/2]
template<class T> FORCEINLINE T FMath::GetMappedRangeValueClamped (const TRange< T > & InputRange, const TRange< T > & OutputRange, const T Value) inline static nodiscard
Definition at line 1175 of file UnrealMathUtility.h.
References Clamp(), FORCEINLINE, GetRangePct(), GetRangeValue(), and Value.
GetMappedRangeValueClamped() [2/2]
template<typename T, typename T2> FORCEINLINE auto FMath::GetMappedRangeValueClamped (const UE::Math::TVector2< T > & InputRange, const UE::Math::TVector2< T > & OutputRange, const T2 Value) inline static nodiscard
For the given Value clamped to the [Input:Range] inclusive, returns the corresponding percentage in [Output:Range] Inclusive.
Definition at line 1148 of file UnrealMathUtility.h.
References Clamp(), FORCEINLINE, GetRangePct(), GetRangeValue(), and Value.
GetMappedRangeValueUnclamped()
template<typename T, typename T2> FORCEINLINE auto FMath::GetMappedRangeValueUnclamped (const UE::Math::TVector2< T > & InputRange, const UE::Math::TVector2< T > & OutputRange, const T2 Value) inline static nodiscard
Transform the given Value relative to the input range to the Output Range.
Definition at line 1157 of file UnrealMathUtility.h.
References FORCEINLINE, GetRangePct(), GetRangeValue(), and Value.
GetRangePct() [1/3]
template<typename T, typename T2 UE_REQUIRES> constexpr FORCEINLINE auto FMath::GetRangePct (T MinValue, T MaxValue, T2 Value) inline static nodiscard constexpr
Calculates the percentage along a line from MinValue to MaxValue that Value is.
Definition at line 1110 of file UnrealMathUtility.h.
References FORCEINLINE, IsNearlyZero(), and Value.
Referenced by GetMappedRangeValueClamped(), GetMappedRangeValueClamped(), GetMappedRangeValueUnclamped(), GetRangePct(), GetRangePct(), and TInterval< float >::GetRangePct().
GetRangePct() [2/3]
template<class T> FORCEINLINE double FMath::GetRangePct (TRange< T > const & Range, T Value) inline static nodiscard
Definition at line 1163 of file UnrealMathUtility.h.
References FORCEINLINE, TRange< ElementType >::GetLowerBoundValue(), GetRangePct(), TRange< ElementType >::GetUpperBoundValue(), and Value.
GetRangePct() [3/3]
template<typename T, typename T2 UE_REQUIRES> auto FMath::GetRangePct (UE::Math::TVector2< T > const & Range, T2 Value) inline static nodiscard
Same as above, but taking a 2d vector as the range.
Definition at line 1130 of file UnrealMathUtility.h.
References GetRangePct(), Value, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
GetRangeValue() [1/2]
template<class T> FORCEINLINE T FMath::GetRangeValue (TRange< T > const & Range, T Pct) inline static nodiscard
Definition at line 1169 of file UnrealMathUtility.h.
References FORCEINLINE, TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBoundValue(), and Lerp().
GetRangeValue() [2/2]
template<typename T, typename T2 UE_REQUIRES> auto FMath::GetRangeValue (UE::Math::TVector2< T > const & Range, T2 Pct) inline static nodiscard
Basically a Vector2d version of Lerp.
Definition at line 1141 of file UnrealMathUtility.h.
References Lerp, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by GetMappedRangeValueClamped(), GetMappedRangeValueClamped(), and GetMappedRangeValueUnclamped().
GetReflectionVector()
FVector FMath::GetReflectionVector (const FVector & Direction, const FVector & SurfaceNormal) static nodiscard
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
Produces a result like shining a laser at a mirror!
Parameters
Direction Direction vector the ray is coming from.
SurfaceNormal A normal of the surface the ray should be reflected on.
Returns
Reflected vector.
References FVector.
GetTForSegmentPlaneIntersect()
float FMath::GetTForSegmentPlaneIntersect (const FVector & StartPoint, const FVector & EndPoint, const FPlane & Plane) static nodiscard
returns the time (t) of the intersection of the passed segment and a plane (could be <0 or >1)
Parameters
StartPoint - start point of segment
EndPoint - end point of segment
Plane - plane to intersect with
Returns
time(T) of intersection
References FVector, and Plane.
GreatestCommonDivisor()
constexpr int32 FMath::GreatestCommonDivisor (int32 a, int32 b) inline static nodiscard constexpr
Definition at line 2507 of file UnrealMathUtility.h.
Referenced by LeastCommonMultiplier().
GridSnap()
template<class T> constexpr FORCEINLINE T FMath::GridSnap (T Location, T Grid) inline static nodiscard constexpr
Snaps a value to the nearest grid multiple.
Definition at line 713 of file UnrealMathUtility.h.
References Floor(), FORCEINLINE, Grid, and Location.
Referenced by UE::Math::TRotator< T >::GridSnap(), UE::Math::TVector< T >::GridSnap(), and MIX_FLOATS_2_ARGS().
InterpCircularIn()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpCircularIn (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a circular in function.
Definition at line 1445 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpCircularInOut().
InterpCircularInOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpCircularInOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a circular in/out function.
Definition at line 1462 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, InterpCircularIn(), InterpCircularOut(), and Lerp.
InterpCircularOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpCircularOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a circular out function.
Definition at line 1453 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpCircularInOut().
InterpEaseIn()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpEaseIn (const T & A, const T & B, float Alpha, float Exp) inline static nodiscard
Interpolate between A and B, applying an ease in function.
Exp controls the degree of the curve.
Definition at line 1351 of file UnrealMathUtility.h.
References A, Alpha, B, Exp, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpEaseInOut().
InterpEaseInOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpEaseInOut (const T & A, const T & B, float Alpha, float Exp) inline static nodiscard
Interpolate between A and B, applying an ease in/out function.
Exp controls the degree of the curve.
Definition at line 1367 of file UnrealMathUtility.h.
References A, Alpha, B, Exp, FORCEINLINE_DEBUGGABLE, InterpEaseIn(), InterpEaseOut(), and Lerp.
InterpEaseOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpEaseOut (const T & A, const T & B, float Alpha, float Exp) inline static nodiscard
Interpolate between A and B, applying an ease out function.
Exp controls the degree of the curve.
Definition at line 1359 of file UnrealMathUtility.h.
References A, Alpha, B, Exp, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpEaseInOut().
InterpExpoIn()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpExpoIn (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying an exponential in function.
Definition at line 1420 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpExpoInOut().
InterpExpoInOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpExpoInOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying an exponential in/out function.
Definition at line 1436 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, InterpExpoIn(), InterpExpoOut(), and Lerp.
InterpExpoOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpExpoOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying an exponential out function.
Definition at line 1428 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and Lerp.
Referenced by InterpExpoInOut().
InterpSinIn()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpSinIn (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a sinusoidal in function.
Definition at line 1395 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, Lerp, and UE_HALF_PI.
Referenced by InterpSinInOut().
InterpSinInOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpSinInOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a sinusoidal in/out function.
Definition at line 1411 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, InterpSinIn(), InterpSinOut(), and Lerp.
InterpSinOut()
template<class T> FORCEINLINE_DEBUGGABLE T FMath::InterpSinOut (const T & A, const T & B, float Alpha) inline static nodiscard
Interpolation between A and B, applying a sinusoidal out function.
Definition at line 1403 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, Lerp, and UE_HALF_PI.
Referenced by InterpSinInOut().
InterpStep()
template<class T> constexpr FORCEINLINE_DEBUGGABLE T FMath::InterpStep (const T & A, const T & B, float Alpha, int32 Steps) inline static nodiscard constexpr
Interpolation between A and B, applying a step function.
Definition at line 1376 of file UnrealMathUtility.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and Lerp.
IntersectPlanes2() [1/2]
template<typename FReal> bool FMath::IntersectPlanes2 (UE::Math::TVector< FReal > & I, UE::Math::TVector< FReal > & D, const UE::Math::TPlane< FReal > & P1, const UE::Math::TPlane< FReal > & P2) static nodiscard
Compute intersection point and direction of line joining two planes.
Return 1 if valid, 0 if infinite.
IntersectPlanes2() [2/2]
template<typename T> bool FMath::IntersectPlanes2 (UE::Math::TVector< T > & I, UE::Math::TVector< T > & D, const UE::Math::TPlane< T > & P1, const UE::Math::TPlane< T > & P2) inline
Definition at line 699 of file Plane.h.
References Square(), UE::Math::TPlane< T >::W, and UE::Math::TVector< T >::ZeroVector.
IntersectPlanes3() [1/2]
template<typename FReal> bool FMath::IntersectPlanes3 (UE::Math::TVector< FReal > & I, const UE::Math::TPlane< FReal > & P1, const UE::Math::TPlane< FReal > & P2, const UE::Math::TPlane< FReal > & P3) static nodiscard
Compute intersection point of three planes.
Return 1 if valid, 0 if infinite.
IntersectPlanes3() [2/2]
template<typename T> bool FMath::IntersectPlanes3 (UE::Math::TVector< T > & I, const UE::Math::TPlane< T > & P1, const UE::Math::TPlane< T > & P2, const UE::Math::TPlane< T > & P3) inline
Definition at line 680 of file Plane.h.
References Square(), UE::Math::TPlane< T >::W, and UE::Math::TVector< T >::ZeroVector.
InvExpApprox()
template<class T> constexpr T FMath::InvExpApprox (T X) inline static nodiscard constexpr
Returns an approximation of Exp(-X) based on a Taylor expansion that has had the coefficients adjusted (using optimisation) to minimise the error in the range 0 < X < 1, which is below 0.1%.
Note that it returns exactly 1 when X is 0, and the return value is greater than the real value for values of X > 1 (but it still tends to zero for large X).
Definition at line 1625 of file UnrealMathUtility.h.
References A, B, and X.
Referenced by CriticallyDampedSmoothing(), AnimationMath::Damper(), ExponentialSmoothingApprox(), AnimationMath::SimpleSpringDamper(), AnimationMath::SimpleSpringDamperQuat(), and SpringDamper().
IsNearlyEqual() [1/2]
FORCEINLINE bool FMath::IsNearlyEqual (double A, double B, double ErrorTolerance = (1.e-8)) inline static nodiscard
Definition at line 390 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and UE_DOUBLE_SMALL_NUMBER.
IsNearlyEqual() [2/2]
FORCEINLINE bool FMath::IsNearlyEqual (float A, float B, float ErrorTolerance = (1.e-8f)) inline static nodiscard
Checks if two floating point numbers are nearly equal.
Parameters
A First number to compare
B Second number to compare
ErrorTolerance Maximum allowed difference for considering them as 'nearly equal'
Returns
true if A and B are nearly equal
Definition at line 385 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and UE_SMALL_NUMBER.
Referenced by FRK4SpringInterpolatorUtils::AreEqual(), FCachedSystemScalabilityCVars::CalculateFieldOfViewDistanceScale(), UE::Slate::CastToVector2f(), UE::Geometry::CreateSeamQuadric(), TAttributeInterpolator< NumericType >::Equals(), TAttributeInterpolator< NumericType >::Equals(), IKeyFrameManipulator< TimeType >::FindKey(), FSimulationOutputRecord::GetInterpolated(), SNumericDropDown< NumericType >::GetValueText(), TArriveAttributeInterpolator< NumericType >::IdenticalTo(), TEasingAttributeInterpolator< NumericType >::IdenticalTo(), TVerletAttributeInterpolator< NumericType >::IdenticalTo(), FTimecode::IsDropFormatTimecodeSupported(), FDisplayClusterWarpEye::IsEqual(), TMatrix2x2< float >::IsNearlyIdentity(), Audio::FQuartzClockTickRate::IsSameTickRate(), FRenderTransform::IsScaleNonUniform(), FSphericalSector::IsSphere(), UE::Math::TRotationMatrix< T >::MakeFromXY(), UE::Math::TRotationMatrix< T >::MakeFromXZ(), UE::Math::TRotationMatrix< T >::MakeFromYX(), UE::Math::TRotationMatrix< T >::MakeFromYZ(), UE::Math::TRotationMatrix< T >::MakeFromZX(), UE::Math::TRotationMatrix< T >::MakeFromZY(), operator==(), TMatrix2x2< float >::operator==(), TBaseBlendedCurve< InAllocatorType, InElementType >::Override(), RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS(), RESOLVE_FLOAT_PREDICATE_AMBIGUITY_3_ARGS(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetBoneWeightsFromBary(), FSlotProxy::UpdateFromSlot(), and USTRUCT().
IsNearlyEqualByULP() [1/2]
FORCEINLINE bool FMath::IsNearlyEqualByULP (double A, double B, int32 MaxUlps = 4) inline static nodiscard
Check if two floating point numbers are nearly equal to within specific number of units of last place (ULP).
A single ULP difference between two floating point numbers means that they have an adjacent representation and that no other floating point number can be constructed to fit between them. This enables making consistent comparisons based on representational distance between floating point numbers, regardless of their magnitude.
Note: Since IEEE 754 floating point operations are guaranteed to be exact to 0.5 ULP, a value of 4 ought to be sufficient for all but the most complex float operations.
Parameters
A First number to compare
B Second number to compare
MaxUlps The maximum ULP distance by which neighboring floating point numbers are allowed to differ.
Returns
true if the two values are nearly equal.
Definition at line 505 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and TIsNearlyEqualByULP().
IsNearlyEqualByULP() [2/2]
FORCEINLINE bool FMath::IsNearlyEqualByULP (float A, float B, int32 MaxUlps = 4) inline static nodiscard
Check if two floating point numbers are nearly equal to within specific number of units of last place (ULP).
A single ULP difference between two floating point numbers means that they have an adjacent representation and that no other floating point number can be constructed to fit between them. This enables making consistent comparisons based on representational distance between floating point numbers, regardless of their magnitude.
Use when the two numbers vary greatly in range. Otherwise, if absolute tolerance is required, use IsNearlyEqual instead.
Note: Since IEEE 754 floating point operations are guaranteed to be exact to 0.5 ULP, a value of 4 ought to be sufficient for all but the most complex float operations.
Parameters
A First number to compare
B Second number to compare
MaxUlps The maximum ULP distance by which neighboring floating point numbers are allowed to differ.
Returns
true if the two values are nearly equal.
Definition at line 483 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and TIsNearlyEqualByULP().
IsNearlyZero() [1/2]
FORCEINLINE bool FMath::IsNearlyZero (double Value, double ErrorTolerance = (1.e-8)) inline static nodiscard
Checks if a floating point number is nearly zero.
Parameters
Value Number to compare
ErrorTolerance Maximum allowed difference for considering Value as 'nearly zero'
Returns
true if Value is nearly zero
Definition at line 415 of file UnrealMathUtility.h.
References FORCEINLINE, UE_DOUBLE_SMALL_NUMBER, and Value.
IsNearlyZero() [2/2]
FORCEINLINE bool FMath::IsNearlyZero (float Value, float ErrorTolerance = (1.e-8f)) inline static nodiscard
Checks if a floating point number is nearly zero.
Parameters
Value Number to compare
ErrorTolerance Maximum allowed difference for considering Value as 'nearly zero'
Returns
true if Value is nearly zero
Definition at line 404 of file UnrealMathUtility.h.
References FORCEINLINE, UE_SMALL_NUMBER, and Value.
Referenced by ArrangeChildrenInStack(), FMediaIOCoreSampleContainer< SampleType >::CacheState(), IAnimationDataController::ConvertSecondsToFrameNumber(), UE::Geometry::CreateSeamQuadric(), CubicCRSplineInterpSafe(), FTriangleRasterizer< RasterPolicyType >::DrawTriangle(), GetFirstLoopStartOffsetAtTrimTime(), GetRangePct(), FSlateClippingZone::HasZeroArea(), FSphericalSector::IsNearlyZero(), HarmonixDsp::PanToGainsConstantPower(), IntersectionUtil::RayCircleIntersection(), RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS(), UE::Math::TRotator< T >::ToCompactString(), UE::Math::TVector< T >::ToCompactString(), UE::Math::TVector< T >::ToCompactText(), and USTRUCT().
IsPowerOfTwo()
template<typename T> constexpr FORCEINLINE bool FMath::IsPowerOfTwo (T Value) inline static nodiscard constexpr
Checks whether a number is a power of two.
Parameters
Value Number to check
Returns
true if Value is a power of two
Definition at line 516 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
Referenced by FHashTable::FHashTable(), THashTable< InAllocator >::THashTable(), TRangeAllocator< FAllocatorModifier >::Alloc(), FHashTable::Clear(), UE::Net::IsValidPingType(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::QuantizeSizeCommon(), TScriptSet< FDefaultSetAllocator, FScriptSet >::Rehash(), and TSet< class UObject * >::Rehash().
IsWithin()
template<class T, class U> constexpr FORCEINLINE bool FMath::IsWithin (const T & TestValue, const U & MinValue, const U & MaxValue) inline static nodiscard constexpr
Checks if value is within a range, exclusive on MaxValue)
Definition at line 365 of file UnrealMathUtility.h.
References FORCEINLINE.
IsWithinInclusive()
template<class T, class U> constexpr FORCEINLINE bool FMath::IsWithinInclusive (const T & TestValue, const U & MinValue, const U & MaxValue) inline static nodiscard constexpr
Checks if value is within a range, inclusive on MaxValue)
Definition at line 373 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by FStreamableRenderResourceState::IsValidForStreamingRequest().
LeastCommonMultiplier()
constexpr int32 FMath::LeastCommonMultiplier (int32 a, int32 b) inline static nodiscard constexpr
Definition at line 2520 of file UnrealMathUtility.h.
References GreatestCommonDivisor().
Lerp() [1/3]
template<typename T, typename U UE_REQUIRES> constexpr FORCEINLINE_DEBUGGABLE T FMath::Lerp (const T & A, const T & B, const U & Alpha) inline static nodiscard constexpr
Performs a linear interpolation between two values, Alpha ranges from 0-1.
Definition at line 1187 of file UnrealMathUtility.h.
References A, Alpha, B, and FORCEINLINE_DEBUGGABLE.
Referenced by UE::Curves::BezierInterp(), UE::AI::Bilinear(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::Blend(), UE::Math::TTransform< double >::Blend(), UE::Math::TTransform< double >::BlendWith(), FCachedSystemScalabilityCVars::CalculateFieldOfViewDistanceScale(), FBuoyancyComponentSim::ComputeWaterForce(), FInterpCurve< T >::Eval(), UE::CubicBezier::Eval(), UE::CubicBezier::EvalDerivate(), FInterpCurve< T >::FindNearestOnSegment(), UE::Geometry::FArrowGenerator::Generate(), UE::Geometry::FCylinderGenerator::Generate(), AEFConstantKeyLerp< FORMAT >::GetBoneAtomScale(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomScale(), AEFConstantKeyLerp< FORMAT >::GetBoneAtomTranslation(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomTranslation(), FFloatDistribution::GetRandomValue(), FVector4Distribution::GetRandomValue(), FVectorDistribution::GetRandomValue(), GetRangeValue(), FFloatDistribution::GetValue(), FVector4Distribution::GetValue(), FVectorDistribution::GetValue(), FRawDistribution::GetValue1None(), FRawDistribution::GetValue3None(), SWindowTitleBar::GetWindowTitleContentColor(), FNetworkPredictionPhysicsState::Interpolate(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), AnimationCompressionUtils::Interpolate< FVector3d >(), AnimationCompressionUtils::Interpolate< FVector3f >(), TBaseBlendedCurve< InAllocatorType, InElementType >::Lerp(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpTo(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpToValid(), UE::Math::TTransform< double >::LerpTranslationScale3D(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid(), and FFinalPostProcessSettings::UpdateEntry().
Lerp() [2/3]
template<typename T, typename U UE_REQUIRES> FORCEINLINE_DEBUGGABLE T FMath::Lerp (const T & A, const T & B, const U & Alpha) inline static nodiscard
Custom lerps defined for those classes not suited to the default implemenation.
Definition at line 1198 of file UnrealMathUtility.h.
References A, Alpha, B, and FORCEINLINE_DEBUGGABLE.
Lerp() [3/3]
template<typename T1, typename T2, typename T3 UE_REQUIRES> auto FMath::Lerp (const T1 & A, const T2 & B, const T3 & Alpha) -> decltype(A * B) inline static nodiscard
Definition at line 1210 of file UnrealMathUtility.h.
References A, Alpha, B, and Lerp.
LerpRange() [1/2]
template<typename T, typename U> FORCEINLINE_DEBUGGABLE UE::Math::TRotator< T > FMath::LerpRange (const UE::Math::TRotator< T > & A, const UE::Math::TRotator< T > & B, U Alpha)
Definition at line 940 of file Rotator.h.
References A, Alpha, B, FORCEINLINE_DEBUGGABLE, and UE::Math::TRotator< T >::GetNormalized().
LerpRange() [2/2]
template<typename T, typename U> UE::Math::TRotator< T > FMath::LerpRange (const UE::Math::TRotator< T > & A, const UE::Math::TRotator< T > & B, U Alpha) static nodiscard
References A, Alpha, and B.
LerpStable() [1/3]
template<class T> constexpr FORCEINLINE_DEBUGGABLE T FMath::LerpStable (const T & A, const T & B, double Alpha) inline static nodiscard constexpr
Performs a linear interpolation between two values, Alpha ranges from 0-1.
Handles full numeric range of T
Definition at line 1218 of file UnrealMathUtility.h.
References A, Alpha, B, and FORCEINLINE_DEBUGGABLE.
Referenced by LerpStable().
LerpStable() [2/3]
template<class T> constexpr FORCEINLINE_DEBUGGABLE T FMath::LerpStable (const T & A, const T & B, float Alpha) inline static nodiscard constexpr
Performs a linear interpolation between two values, Alpha ranges from 0-1.
Handles full numeric range of T
Definition at line 1225 of file UnrealMathUtility.h.
References A, Alpha, B, and FORCEINLINE_DEBUGGABLE.
LerpStable() [3/3]
template<typename T1, typename T2, typename T3 UE_REQUIRES> auto FMath::LerpStable (const T1 & A, const T2 & B, const T3 & Alpha) -> decltype(A * B) inline static nodiscard
Definition at line 1237 of file UnrealMathUtility.h.
References A, Alpha, B, and LerpStable().
LineBoxIntersection() [1/2]
template<typename FReal> bool FMath::LineBoxIntersection (const UE::Math::TBox< FReal > & Box, const UE::Math::TVector< FReal > & Start, const UE::Math::TVector< FReal > & End, const UE::Math::TVector< FReal > & Direction) inline static nodiscard
Determines whether a line intersects a box.
Definition at line 1026 of file Box.h.
References Box, End, LineBoxIntersection(), and UE::Math::TVector< T >::Reciprocal().
Referenced by LineBoxIntersection().
LineBoxIntersection() [2/2]
template<typename FReal> bool FMath::LineBoxIntersection (const UE::Math::TBox< FReal > & Box, const UE::Math::TVector< FReal > & Start, const UE::Math::TVector< FReal > & End, const UE::Math::TVector< FReal > & Direction, const UE::Math::TVector< FReal > & OneOverDirection) inline static nodiscard
Determines whether a line intersects a box.
This overload avoids the need to do the reciprocal every time.
Definition at line 1038 of file Box.h.
References Box, End, Max3(), Time, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
LineExtentBoxIntersection()
bool FMath::LineExtentBoxIntersection (const FBox & inBox, const FVector & Start, const FVector & End, const FVector & Extent, FVector & HitLocation, FVector & HitNormal, float & HitTime) static
References End, and FVector.
LinePlaneIntersection() [1/4]
template<typename FReal> UE::Math::TVector< FReal > FMath::LinePlaneIntersection (const UE::Math::TVector< FReal > & Point1, const UE::Math::TVector< FReal > & Point2, const UE::Math::TPlane< FReal > & Plane) static nodiscard
Find the intersection of a line and a plane.
Assumes that the line and plane do indeed intersect; you must make sure they're not parallel before calling.
Parameters
Point1 the first point defining the line
Point2 the second point defining the line
Plane the plane
Returns
The point of intersection between the line and the plane.
References Plane.
LinePlaneIntersection() [2/4]
template<typename FReal> UE::Math::TVector< FReal > FMath::LinePlaneIntersection (const UE::Math::TVector< FReal > & Point1, const UE::Math::TVector< FReal > & Point2, const UE::Math::TVector< FReal > & PlaneOrigin, const UE::Math::TVector< FReal > & PlaneNormal) static nodiscard
Find the intersection of a line and an offset plane.
Assumes that the line and plane do indeed intersect; you must make sure they're not parallel before calling.
Parameters
Point1 the first point defining the line
Point2 the second point defining the line
PlaneOrigin the origin of the plane
PlaneNormal the normal of the plane
Returns
The point of intersection between the line and the plane.
LinePlaneIntersection() [3/4]
template<typename T> UE::Math::TVector< T > FMath::LinePlaneIntersection (const UE::Math::TVector< T > & Point1, const UE::Math::TVector< T > & Point2, const UE::Math::TPlane< T > & Plane) inline
Definition at line 666 of file Plane.h.
References Plane.
LinePlaneIntersection() [4/4]
template<typename T> UE::Math::TVector< T > FMath::LinePlaneIntersection (const UE::Math::TVector< T > & Point1, const UE::Math::TVector< T > & Point2, const UE::Math::TVector< T > & PlaneOrigin, const UE::Math::TVector< T > & PlaneNormal) inline
Definition at line 2672 of file Vector.h.
LineSphereIntersection() [1/2]
template<typename FReal> bool FMath::LineSphereIntersection (const UE::Math::TVector< FReal > & Start, const UE::Math::TVector< FReal > & Dir, FReal Length, const UE::Math::TVector< FReal > & Origin, FReal Radius) static nodiscard
Determines whether a line intersects a sphere.
References Origin.
LineSphereIntersection() [2/2]
template<typename T> bool FMath::LineSphereIntersection (const UE::Math::TVector< T > & Start, const UE::Math::TVector< T > & Dir, T Length, const UE::Math::TVector< T > & Origin, T Radius) inline
Definition at line 2687 of file Vector.h.
References Origin, and Time.
Log2() [1/2]
FORCEINLINE double FMath::Log2 (double Value) inline static nodiscard
Computes the base 2 logarithm of the specified value.
Parameters
Value the value to perform the log on
Returns
the base 2 log of the value
Definition at line 765 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
Log2() [2/2]
FORCEINLINE float FMath::Log2 (float Value) inline static nodiscard
Computes the base 2 logarithm of the specified value.
Parameters
Value the value to perform the log on
Returns
the base 2 log of the value
Definition at line 750 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
Referenced by UE::Math::TTransform< double >::TTransform(), EV100ToLog2(), Log2ToEV100(), LuminanceToEV100(), LuminanceToEV100(), Harmonix::Dsp::Effects::TMultiChannelBiquadFilter< T, COUNT >::SetFreqTarget(), Harmonix::Dsp::Effects::TMultiChannelBiquadFilter< T, COUNT >::SetQTarget(), FRamper::SetTargetLog(), VectorLog2(), and VectorLog2().
MakePulsatingValue()
float FMath::MakePulsatingValue (const double InCurrentTime, const float InPulsesPerSecond, const float InPhase = 0.0f) inline static nodiscard
Simple function to create a pulsating scalar value.
Parameters
InCurrentTime Current absolute time
InPulsesPerSecond How many full pulses per second?
InPhase Optional phase amount, between 0.0 and 1.0 (to synchronize pulses)
Returns
Pulsating value (0.0-1.0)
Definition at line 1877 of file UnrealMathUtility.h.
References UE_TWO_PI.
MatrixInverse() [1/2]
bool FMath::MatrixInverse (FMatrix44d * DstMatrix, const FMatrix44d * SrcMatrix) static nodiscard
MatrixInverse() [2/2]
bool FMath::MatrixInverse (FMatrix44f * DstMatrix, const FMatrix44f * SrcMatrix) static nodiscard
Calculate the inverse of an FMatrix44.
Src == Dst is allowed
Parameters
DstMatrix FMatrix44 pointer to where the result should be stored
SrcMatrix FMatrix44 pointer to the Matrix to be inversed
Returns
bool returns false if matrix is not invertable and stores identity
Do not call this directly, use VectorMatrixInverse or Matrix::Inverse this is the fallback scalar implementation used by VectorMatrixInverse
Referenced by VectorMatrixInverse(), and VectorMatrixInverse().
Max3()
template<class T> constexpr FORCEINLINE T FMath::Max3 (const T A, const T B, const T C) inline static nodiscard constexpr
Returns highest of 3 values.
Definition at line 551 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and Max.
Referenced by FPrimitiveUniformShaderParametersBuilder::Build(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_tri_bboxes(), FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), UCapsuleComponent::InitCapsuleSize(), LineBoxIntersection(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial(), UE::Math::TVector< T >::Max3(), and UE::Geometry::FMarchingCubes::SetDimensions().
Max3Index()
template<class T> constexpr FORCEINLINE int32 FMath::Max3Index (const T A, const T B, const T C) inline static nodiscard constexpr
Definition at line 564 of file UnrealMathUtility.h.
References A, B, and FORCEINLINE.
MemoryTest()
bool FMath::MemoryTest (void * BaseAddress, uint32 NumBytes) static nodiscard
Tests a memory region to see that it's working properly.
Parameters
BaseAddress Starting address
NumBytes Number of bytes to test (will be rounded down to a multiple of 4)
Returns
true if the memory region passed the test
Min3()
template<class T> constexpr FORCEINLINE T FMath::Min3 (const T A, const T B, const T C) inline static nodiscard constexpr
Returns lowest of 3 values.
Definition at line 558 of file UnrealMathUtility.h.
References A, B, FORCEINLINE, and Min.
Referenced by UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_tri_bboxes(), Algo::LevenshteinDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial(), and UE::Math::TVector< T >::Min3().
Min3Index()
template<class T> constexpr FORCEINLINE int32 FMath::Min3Index (const T A, const T B, const T C) inline static nodiscard constexpr
Returns index of the lowest value.
Definition at line 571 of file UnrealMathUtility.h.
References A, B, and FORCEINLINE.
MIX_FLOATS_2_ARGS()
FMath::MIX_FLOATS_2_ARGS (GridSnap)
Allow mixing float/double arguments, promoting to highest precision type.
References GridSnap().
MIX_FLOATS_3_ARGS()
FMath::MIX_FLOATS_3_ARGS (Clamp)
Allow mixing float/double arguments, promoting to highest precision type.
References Clamp().
Modulo()
template<typename ValueType, typename BaseType> constexpr FORCEINLINE auto FMath::Modulo (ValueType Value, BaseType Base) inline static nodiscard constexpr
Definition at line 699 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
Referenced by WrapExclusive(), and WrapImpl().
PerlinNoise1D()
float FMath::PerlinNoise1D (float Value) static nodiscard
Generates a 1D Perlin noise from the given value.
Returns a continuous random value between -1.0 and 1.0.
Parameters
Value The input value that Perlin noise will be generated from. This is usually a steadily incrementing time value.
Returns
Perlin noise in the range of -1.0 to 1.0
References Value.
PerlinNoise2D()
float FMath::PerlinNoise2D (const FVector2D & Location) static nodiscard
Generates a 2D Perlin noise sample at the given location.
Returns a continuous random value between -1.0 and 1.0.
Parameters
Location Where to sample
Returns
Perlin noise in the range of -1.0 to 1.0
References Location.
Referenced by UE::Geometry::FractalBrownianMotionNoise().
PerlinNoise3D()
float FMath::PerlinNoise3D (const FVector & Location) static nodiscard
Generates a 3D Perlin noise sample at the given location.
Returns a continuous random value between -1.0 and 1.0.
Parameters
Location Where to sample
Returns
Perlin noise in the range of -1.0 to 1.0
References FVector, and Location.
PlaneAABBIntersection()
bool FMath::PlaneAABBIntersection (const FPlane & P, const FBox & AABB) static nodiscard
Determine if a plane and an AABB intersect.
Parameters
P - the plane to test
AABB - the axis aligned bounding box to test
Returns
if collision occurs
References AABB.
PlaneAABBRelativePosition()
int32 FMath::PlaneAABBRelativePosition (const FPlane & P, const FBox & AABB) static nodiscard
Determine the position of an AABB relative to a plane: completely above (in the direction of the normal of the plane), completely below or intersects it.
Parameters
P - the plane to test
AABB - the axis aligned bounding box to test
Returns
-1 if below, 1 if above, 0 if intersects
References AABB, Box, End, Point, and Sphere.
PointBoxIntersection()
template<typename FReal> bool FMath::PointBoxIntersection (const UE::Math::TVector< FReal > & Point, const UE::Math::TBox< FReal > & Box) inline static nodiscard
Determines whether a point is inside a box.
Definition at line 1014 of file Box.h.
References Box, and Point.
PointDistToLine() [1/2]
float FMath::PointDistToLine (const FVector & Point, const FVector & Direction, const FVector & Origin) static nodiscard
References FVector, Origin, and Point.
PointDistToLine() [2/2]
float FMath::PointDistToLine (const FVector & Point, const FVector & Direction, const FVector & Origin, FVector & OutClosestPoint) static
Calculates the distance of a given Point in world space to a given line, defined by the vector couple (Origin, Direction).
Parameters
Point Point to check distance to line
Direction Vector indicating the direction of the line. Not required to be normalized.
Origin Point of reference used to calculate distance
OutClosestPoint optional point that represents the closest point projected onto Axis
Returns
distance of Point from line defined by (Origin, Direction)
References FVector, Origin, and Point.
PointDistToSegment()
float FMath::PointDistToSegment (const FVector & Point, const FVector & StartPoint, const FVector & EndPoint) static nodiscard
Returns distance from a point to the closest point on a segment.
Parameters
Point point to check distance for
StartPoint StartPoint of segment
EndPoint EndPoint of segment
Returns
closest distance from Point to segment defined by (StartPoint, EndPoint).
References FVector, and Point.
PointDistToSegmentSquared()
float FMath::PointDistToSegmentSquared (const FVector & Point, const FVector & StartPoint, const FVector & EndPoint) static nodiscard
Returns square of the distance from a point to the closest point on a segment.
Parameters
Point point to check distance for
StartPoint StartPoint of segment
EndPoint EndPoint of segment
Returns
square of the closest distance from Point to segment defined by (StartPoint, EndPoint).
References FVector, and Point.
PointsAreCoplanar()
bool FMath::PointsAreCoplanar (const TArray< FVector > & Points, const float Tolerance = 0.1f) static nodiscard
Determines whether a given set of points are coplanar, with a tolerance.
Any three points or less are always coplanar.
Parameters
Points - The set of points to determine coplanarity for.
Tolerance - Larger numbers means more variance is allowed.
Returns
Whether the points are relatively coplanar, based on the tolerance
References Points.
PolarToCartesian() [1/2]
template<typename T> FORCEINLINE void FMath::PolarToCartesian (const T Rad, const T Ang, T & OutX, T & OutY) inline static
Converts given Polar coordinate pair to Cartesian coordinate system.
Definition at line 1053 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by PolarToCartesian().
PolarToCartesian() [2/2]
template<typename T> FORCEINLINE void FMath::PolarToCartesian (const UE::Math::TVector2< T > InPolar, UE::Math::TVector2< T > & OutCart) inline static
Converts given Polar coordinate pair to Cartesian coordinate system.
Definition at line 1060 of file UnrealMathUtility.h.
References FORCEINLINE, PolarToCartesian(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
QInterpConstantTo()
template<class T> UE::Math::TQuat< T > FMath::QInterpConstantTo (const UE::Math::TQuat< T > & Current, const UE::Math::TQuat< T > & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate quaternion from Current to Target with constant step (in radians)
References DeltaTime, and Target.
QInterpTo()
template<class T> UE::Math::TQuat< T > FMath::QInterpTo (const UE::Math::TQuat< T > & Current, const UE::Math::TQuat< T > & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate quaternion from Current to Target.
Scaled by angle to Target, so it has a strong start speed and ease out.
References DeltaTime, and Target.
Quantize8SignedByte()
uint8 FMath::Quantize8SignedByte (float x) inline static nodiscard
Definition at line 2498 of file UnrealMathUtility.h.
References Quantize8UnsignedByte().
Quantize8UnsignedByte()
uint8 FMath::Quantize8UnsignedByte (float x) inline static nodiscard
Definition at line 2485 of file UnrealMathUtility.h.
References check.
Referenced by Quantize8SignedByte().
RadiansToDegrees() [1/3]
constexpr FORCEINLINE double FMath::RadiansToDegrees (double const & RadVal) inline static constexpr
Definition at line 894 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_DOUBLE_PI.
RadiansToDegrees() [2/3]
constexpr FORCEINLINE float FMath::RadiansToDegrees (float const & RadVal) inline static constexpr
Definition at line 893 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_PI.
RadiansToDegrees() [3/3]
template<class T> constexpr FORCEINLINE auto FMath::RadiansToDegrees (T const & RadVal) -> decltype(RadVal * (180.f / (3.1415926535897932f))) inline static nodiscard constexpr
Converts radians to degrees.
Parameters
RadVal Value in radians.
Returns
Value in degrees.
Definition at line 888 of file UnrealMathUtility.h.
References FORCEINLINE, and UE_PI.
Referenced by FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation(), FDisplayClusterWarpProjection::ConvertProjectionToDegrees(), and BlendSpaceAnalysis::if().
RandBool()
FORCEINLINE bool FMath::RandBool () inline static nodiscard
Util to generate a random boolean.
Definition at line 324 of file UnrealMathUtility.h.
References FORCEINLINE, and RandRange().
RandHelper()
FORCEINLINE int32 FMath::RandHelper (int32 A) inline static nodiscard
Helper function for rand implementations.
Returns a random number in [0..A)
Definition at line 271 of file UnrealMathUtility.h.
References A, FORCEINLINE, and Min.
Referenced by RandRange().
RandHelper64()
FORCEINLINE int64 FMath::RandHelper64 (int64 A) inline static nodiscard
Definition at line 278 of file UnrealMathUtility.h.
References A, FORCEINLINE, and Min.
Referenced by Algo::RandomShuffle(), and RandRange().
RandPointInBox()
FVector FMath::RandPointInBox (const FBox & Box) static nodiscard
Returns a random point within the passed in bounding box.
References Box, and FVector.
RandPointInCircle()
FVector2D FMath::RandPointInCircle (float CircleRadius) static nodiscard
Returns a random point, uniformly distributed, within the specified radius.
RandRange() [1/4]
FORCEINLINE double FMath::RandRange (double InMin, double InMax) inline static nodiscard
Definition at line 304 of file UnrealMathUtility.h.
References FORCEINLINE, and FRandRange().
RandRange() [2/4]
FORCEINLINE float FMath::RandRange (float InMin, float InMax) inline static nodiscard
Util to generate a random number in a range.
Overloaded to distinguish from int32 version, where passing a float is typically a mistake.
Definition at line 299 of file UnrealMathUtility.h.
References FORCEINLINE, and FRandRange().
RandRange() [3/4]
FORCEINLINE int32 FMath::RandRange (int32 Min, int32 Max) inline static nodiscard
Helper function for rand implementations.
Returns a random number >= Min and <= Max
Definition at line 286 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, and RandHelper().
Referenced by RandBool().
RandRange() [4/4]
FORCEINLINE int64 FMath::RandRange (int64 Min, int64 Max) inline static nodiscard
Definition at line 292 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, and RandHelper64().
RayPlaneIntersection() [1/2]
template<typename FReal> UE::Math::TVector< FReal > FMath::RayPlaneIntersection (const UE::Math::TVector< FReal > & RayOrigin, const UE::Math::TVector< FReal > & RayDirection, const UE::Math::TPlane< FReal > & Plane) static nodiscard
Find the intersection of a ray and a plane.
The ray has a start point with an infinite length. Assumes that the line and plane do indeed intersect; you must make sure they're not parallel before calling.
Parameters
RayOrigin The start point of the ray
RayDirection The direction the ray is pointing (normalized vector)
Plane The plane to intersect with
Returns
The point of intersection between the ray and the plane.
References Plane.
Referenced by FCameraRectangle::PerspectiveProjection().
RayPlaneIntersection() [2/2]
template<typename T> UE::Math::TVector< T > FMath::RayPlaneIntersection (const UE::Math::TVector< T > & RayOrigin, const UE::Math::TVector< T > & RayDirection, const UE::Math::TPlane< T > & Plane) inline
Definition at line 645 of file Plane.h.
References Distance, and Plane.
RayPlaneIntersectionParam() [1/2]
template<typename FReal> FReal FMath::RayPlaneIntersectionParam (const UE::Math::TVector< FReal > & RayOrigin, const UE::Math::TVector< FReal > & RayDirection, const UE::Math::TPlane< FReal > & Plane) static nodiscard
Find the intersection of a ray and a plane.
The ray has a start point with an infinite length. Assumes that the line and plane do indeed intersect; you must make sure they're not parallel before calling.
Parameters
RayOrigin The start point of the ray
RayDirection The direction the ray is pointing (normalized vector)
Plane The plane to intersect with
Returns
The distance parameter along ray of the point of intersection between the ray and the plane.
References Plane.
Referenced by IntersectionUtil::RayCircleIntersection().
RayPlaneIntersectionParam() [2/2]
template<typename T> T FMath::RayPlaneIntersectionParam (const UE::Math::TVector< T > & RayOrigin, const UE::Math::TVector< T > & RayDirection, const UE::Math::TPlane< T > & Plane) inline
Definition at line 656 of file Plane.h.
References Plane.
RESOLVE_FLOAT_AMBIGUITY_2_ARGS()
FMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (FRandRange)
References FRandRange().
RESOLVE_FLOAT_AMBIGUITY_3_ARGS()
FMath::RESOLVE_FLOAT_AMBIGUITY_3_ARGS (ClampAngle)
References ClampAngle().
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS() [1/2]
FMath::RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS (IsNearlyEqual)
References IsNearlyEqual().
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS() [2/2]
FMath::RESOLVE_FLOAT_PREDICATE_AMBIGUITY_2_ARGS (IsNearlyZero)
References IsNearlyZero().
RESOLVE_FLOAT_PREDICATE_AMBIGUITY_3_ARGS()
FMath::RESOLVE_FLOAT_PREDICATE_AMBIGUITY_3_ARGS (IsNearlyEqual)
References IsNearlyEqual().
RInterpConstantTo()
FRotator FMath::RInterpConstantTo (const FRotator & Current, const FRotator & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate rotator from Current to Target with constant step.
References DeltaTime, and Target.
RInterpTo()
FRotator FMath::RInterpTo (const FRotator & Current, const FRotator & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate rotator from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
References DeltaTime, and Target.
RoundFromZero() [1/2]
FORCEINLINE double FMath::RoundFromZero (double F) inline static nodiscard
Definition at line 2274 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundFromZero() [2/2]
FORCEINLINE float FMath::RoundFromZero (float F) inline static nodiscard
Converts a floating point number to an integer which is further from zero, "larger" in absolute value: 0.1 becomes 1, -0.1 becomes -1.
Parameters
F Floating point value to convert
Returns
The rounded integer
Definition at line 2269 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundHalfFromZero() [1/2]
double FMath::RoundHalfFromZero (double F) static nodiscard
RoundHalfFromZero() [2/2]
float FMath::RoundHalfFromZero (float F) static nodiscard
Converts a floating point number to the nearest integer, equidistant ties go to the value which is further from zero: -0.5 becomes -1.0, 0.5 becomes 1.0.
Parameters
F Floating point value to convert
Returns
The rounded integer
RoundHalfToEven() [1/2]
double FMath::RoundHalfToEven (double F) static nodiscard
RoundHalfToEven() [2/2]
float FMath::RoundHalfToEven (float F) static nodiscard
Converts a floating point number to the nearest integer, equidistant ties go to the value which is closest to an even value: 1.5 becomes 2, 0.5 becomes 0.
Parameters
F Floating point value to convert
Returns
The rounded integer
Referenced by VectorRoundToIntHalfToEven().
RoundHalfToZero() [1/2]
double FMath::RoundHalfToZero (double F) static nodiscard
RoundHalfToZero() [2/2]
float FMath::RoundHalfToZero (float F) static nodiscard
Converts a floating point number to the nearest integer, equidistant ties go to the value which is closer to zero: -0.5 becomes 0, 0.5 becomes 0.
Parameters
F Floating point value to convert
Returns
The rounded integer
RoundToNegativeInfinity() [1/2]
FORCEINLINE double FMath::RoundToNegativeInfinity (double F) inline static nodiscard
Definition at line 2304 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundToNegativeInfinity() [2/2]
FORCEINLINE float FMath::RoundToNegativeInfinity (float F) inline static nodiscard
Converts a floating point number to an integer which is more negative: 0.1 becomes 0, -0.1 becomes -1.
Parameters
F Floating point value to convert
Returns
The rounded integer
Definition at line 2299 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundToPositiveInfinity() [1/2]
FORCEINLINE double FMath::RoundToPositiveInfinity (double F) inline static nodiscard
Definition at line 2319 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundToPositiveInfinity() [2/2]
FORCEINLINE float FMath::RoundToPositiveInfinity (float F) inline static nodiscard
Converts a floating point number to an integer which is more positive: 0.1 becomes 1, -0.1 becomes 0.
Parameters
F Floating point value to convert
Returns
The rounded integer
Definition at line 2314 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundToZero() [1/2]
FORCEINLINE double FMath::RoundToZero (double F) inline static nodiscard
Definition at line 2289 of file UnrealMathUtility.h.
References FORCEINLINE.
RoundToZero() [2/2]
FORCEINLINE float FMath::RoundToZero (float F) inline static nodiscard
Converts a floating point number to an integer which is closer to zero, "smaller" in absolute value: 0.1 becomes 0, -0.1 becomes 0.
Parameters
F Floating point value to convert
Returns
The rounded integer
Definition at line 2284 of file UnrealMathUtility.h.
References FORCEINLINE.
Referenced by FTimecode::FromFrameNumber(), operator FQualifiedFrameTime(), operator=(), and FTimecode::ToFrameNumber().
SegmentDistToSegment()
void FMath::SegmentDistToSegment (FVector A1, FVector B1, FVector A2, FVector B2, FVector & OutP1, FVector & OutP2) static
Find closest points between 2 segments.
If either segment may have a length of 0, use SegmentDistToSegmentSafe instance.
Parameters
(A1,B1) defines the first segment.
(A2,B2) defines the second segment.
OutP1 Closest point on segment 1 to segment 2.
OutP2 Closest point on segment 2 to segment 1.
References FVector.
SegmentDistToSegmentSafe()
template<typename T> void FMath::SegmentDistToSegmentSafe (UE::Math::TVector< T > A1, UE::Math::TVector< T > B1, UE::Math::TVector< T > A2, UE::Math::TVector< T > B2, UE::Math::TVector< T > & OutP1, UE::Math::TVector< T > & OutP2) static
Find closest points between 2 segments.
This is the safe version, and will check both segments' lengths. Use this if either (or both) of the segments lengths may be 0.
Parameters
(A1,B1) defines the first segment.
(A2,B2) defines the second segment.
OutP1 Closest point on segment 1 to segment 2.
OutP2 Closest point on segment 2 to segment 1.
SegmentIntersection2D()
bool FMath::SegmentIntersection2D (const FVector & SegmentStartA, const FVector & SegmentEndA, const FVector & SegmentStartB, const FVector & SegmentEndB, FVector & out_IntersectionPoint) static
Returns true if there is an intersection between the segment specified by SegmentStartA and SegmentEndA, and the segment specified by SegmentStartB and SegmentEndB, in 2D space.
If there is an intersection, the point is placed in out_IntersectionPoint
Parameters
SegmentStartA - start point of first segment
SegmentEndA - end point of first segment
SegmentStartB - start point of second segment
SegmentEndB - end point of second segment
out_IntersectionPoint - out var for the intersection point (if any)
Returns
true if intersection occurred
References FVector.
SegmentPlaneIntersection()
bool FMath::SegmentPlaneIntersection (const FVector & StartPoint, const FVector & EndPoint, const FPlane & Plane, FVector & out_IntersectionPoint) static
Returns true if there is an intersection between the segment specified by StartPoint and Endpoint, and the plane on which polygon Plane lies.
If there is an intersection, the point is placed in out_IntersectionPoint
Parameters
StartPoint - start point of segment
EndPoint - end point of segment
Plane - plane to intersect with
out_IntersectionPoint - out var for the point on the segment that intersects the mesh (if any)
Returns
true if intersection occurred
References FVector, and Plane.
SegmentTriangleIntersection()
bool FMath::SegmentTriangleIntersection (const FVector & StartPoint, const FVector & EndPoint, const FVector & A, const FVector & B, const FVector & C, FVector & OutIntersectPoint, FVector & OutTriangleNormal) static
Returns true if there is an intersection between the segment specified by StartPoint and Endpoint, and the Triangle defined by A, B and C.
If there is an intersection, the point is placed in out_IntersectionPoint
Parameters
StartPoint - start point of segment
EndPoint - end point of segment
A,B,C - points defining the triangle
OutIntersectPoint - out var for the point on the segment that intersects the triangle (if any)
OutTriangleNormal - out var for the triangle normal
Returns
true if intersection occurred
References A, B, and FVector.
SetBoolInBitField()
constexpr void FMath::SetBoolInBitField (uint8 * Ptr, uint32 Index, bool bSet) inline static constexpr
Set a bit in memory created from bitflags (uint32 Value:1), used for EngineShowFlags, TestBitFieldFunctions() tests the implementation.
Definition at line 2462 of file UnrealMathUtility.h.
References Mask.
SinCos() [1/3]
FORCEINLINE void FMath::SinCos (double * ScalarSin, double * ScalarCos, double Value) inline static
Definition at line 825 of file UnrealMathUtility.h.
References FORCEINLINE, and Value.
SinCos() [2/3]
template<typename T UE_REQUIRES> constexpr FORCEINLINE void FMath::SinCos (std::decay_t< T > * ScalarSin, std::decay_t< T > * ScalarCos, T Value) inline static constexpr
Computes the sine and cosine of a scalar value.
Parameters
ScalarSin Pointer to where the Sin result should be stored
ScalarCos Pointer to where the Cos result should be stored
Value input angles
Definition at line 784 of file UnrealMathUtility.h.
References FORCEINLINE, UE_HALF_PI, UE_INV_PI, UE_PI, UE_TWO_PI, and Value.
Referenced by UE::Math::TQuat< T >::TQuat(), UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), UE::Math::TVector2< T >::GetRotated(), UE::Math::anonymous_namespace{ScaleRotationTranslationMatrix.h}::GetSinCos(), UE::Math::TVector< T >::RotateAngleAxisRad(), SinCos(), SpringDamper(), and VectorSinCos().
SinCos() [3/3]
template<typename T, typename U UE_REQUIRES> FORCEINLINE void FMath::SinCos (T * ScalarSin, T * ScalarCos, U Value) inline static
Definition at line 837 of file UnrealMathUtility.h.
References FORCEINLINE, SinCos(), and Value.
SmoothStep()
template<typename T> constexpr T FMath::SmoothStep (T A, T B, T X) inline static nodiscard constexpr
Returns a smooth Hermite interpolation between 0 and 1 for the value X (where X ranges between A and B) Clamped to 0 for X <= A and 1 for X >= B.
Parameters
A Minimum value of X
B Maximum value of X
X Parameter
Returns
Smoothed value between 0 and 1
Definition at line 2432 of file UnrealMathUtility.h.
References A, B, and X.
SphereAABBIntersection() [1/2]
template<typename FReal> bool FMath::SphereAABBIntersection (const UE::Math::TSphere< FReal > & Sphere, const UE::Math::TBox< FReal > & AABB) inline static nodiscard
Converts a sphere into a point plus radius squared for the test above.
Definition at line 1213 of file Box.h.
References AABB, Sphere, SphereAABBIntersection(), and Square().
SphereAABBIntersection() [2/2]
template<typename FReal> bool FMath::SphereAABBIntersection (const UE::Math::TVector< FReal > & SphereCenter, const FReal RadiusSquared, const UE::Math::TBox< FReal > & AABB) inline static nodiscard
Performs a sphere vs box intersection test using Arvo's algorithm:
for each i in (x, y, z) if (SphereCenter(i) < BoxMin(i)) d2 += (SphereCenter(i) - BoxMin(i)) ^ 2 else if (SphereCenter(i) > BoxMax(i)) d2 += (SphereCenter(i) - BoxMax(i)) ^ 2
Parameters
SphereCenter the center of the sphere being tested against the AABB
RadiusSquared the size of the sphere being tested
AABB the box being tested against
Returns
Whether the sphere/box intersect or not.
Definition at line 1175 of file Box.h.
References AABB, Square(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by SphereAABBIntersection().
SphereConeIntersection()
bool FMath::SphereConeIntersection (const FVector & SphereCenter, float SphereRadius, const FVector & ConeAxis, float ConeAngleSin, float ConeAngleCos) static nodiscard
Assumes the cone tip is at 0,0,0 (means the SphereCenter is relative to the cone tip)
Returns
true: cone and sphere do intersect, false otherwise
References FVector.
SphereDistToLine()
void FMath::SphereDistToLine (FVector SphereOrigin, float SphereRadius, FVector LineOrigin, FVector LineDir, FVector & OutClosestPoint) static
Find closest point on a Sphere to a Line.
When line intersects Sphere, then closest point to LineOrigin is returned.
Parameters
SphereOrigin Origin of Sphere
SphereRadius Radius of Sphere
LineOrigin Origin of line
LineDir Direction of line. Needs to be normalized!!
OutClosestPoint Closest point on sphere to given line.
References FVector.
SpringDamper()
template<class T> void FMath::SpringDamper (T & InOutValue, T & InOutValueRate, const T & InTargetValue, const T & InTargetValueRate, const float InDeltaTime, const float InUndampedFrequency, const float InDampingRatio) inline static
Smooths a value using a spring damper towards a target.
The implementation uses approximations for Exp/Sin/Cos. These are accurate for all sensible values of InUndampedFrequency and DampingRatio so long as InDeltaTime < 1 / InUndampedFrequency (approximately), but are generally well behaved even for larger timesteps etc.
Parameters
InOutValue The value to be smoothed
InOutValueRate The rate of change of the value
InTargetValue The target to smooth towards
InTargetValueRate The target rate of change smooth towards. Note that if this is discontinuous, then the output will have discontinuous velocity too.
InDeltaTime Time interval
InUndampedFrequency Oscillation frequency when there is no damping. Proportional to the square root of the spring stiffness.
InDampingRatio 1 is critical damping. <1 results in under-damped motion (i.e. with overshoot), and >1 results in over-damped motion.
Definition at line 1744 of file UnrealMathUtility.h.
References A, B, InvExpApprox(), SinCos(), Square(), UE_SMALL_NUMBER, and UE_TWO_PI.
Referenced by SpringDamperSmoothing().
SpringDamperSmoothing()
template<class T> void FMath::SpringDamperSmoothing (T & InOutValue, T & InOutValueRate, const T & InTargetValue, const T & InTargetValueRate, const float InDeltaTime, const float InSmoothingTime, const float InDampingRatio) inline static
Smooths a value using a spring damper towards a target.
The implementation uses approximations for Exp/Sin/Cos. These are accurate for all sensible values of DampingRatio and InSmoothingTime so long as InDeltaTime < 0.5 * InSmoothingTime, but are generally well behaved even for larger timesteps etc.
Parameters
InOutValue The value to be smoothed
InOutValueRate The rate of change of the value
InTargetValue The target to smooth towards
InTargetValueRate The target rate of change smooth towards. Note that if this is discontinuous, then the output will have discontinuous velocity too.
InDeltaTime Time interval
InSmoothingTime Timescale over which to smooth. Larger values result in more smoothed behaviour. Can be zero.
InDampingRatio 1 is critical damping. <1 results in under-damped motion (i.e. with overshoot), and >1 results in over-damped motion.
Definition at line 1843 of file UnrealMathUtility.h.
References SpringDamper(), UE_PI, and UE_SMALL_NUMBER.
Square()
template<class T> constexpr FORCEINLINE T FMath::Square (const T A) inline static nodiscard constexpr
Multiples value by itself.
Definition at line 578 of file UnrealMathUtility.h.
References A, and FORCEINLINE.
Referenced by CartesianToPolar(), ComputeSquaredDistanceFromBoxToPoint(), UE::Math::TBox2< double >::ComputeSquaredDistanceToPoint(), FLinearColor::Dist(), UE::Math::TVector2< T >::DistSquared(), UE::Math::TVector< T >::DistSquared(), UE::Math::TVector< T >::DistSquaredXY(), FStaticSpatialIndex::FastConeAABBIntersection(), FInterpConstantTo(), FInterpTo(), FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement(), FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElement(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElement(), UE::Math::TVector2< T >::GetClampedToMaxSize(), UE::Math::TVector< T >::GetClampedToMaxSize(), UE::Math::TVector< T >::GetClampedToMaxSize2D(), TQuadTree< ElementType, NodeCapacity >::InsertElementRecursive(), IntersectPlanes2(), IntersectPlanes3(), UE::Math::TSphere< double >::Intersects(), FLinearColor::IsAlmostBlack(), UE::Math::TCapsuleShape< T >::IsInside(), UE::Math::TSphere< double >::IsInside(), UE::Math::TSphere< double >::IsInside(), UE::Math::TSphere< T >::operator+=(), FDebugRenderSceneProxy::PointInRange(), SphereAABBIntersection(), SphereAABBIntersection(), UE::Math::TBoxSphereBounds< float, float >::SpheresIntersect(), SpringDamper(), UProjectileMovementComponent::UFUNCTION(), LandscapeDataAccess::UnpackNormal(), and FRandomStream::VRandCone().
TIsNearlyEqualByULP()
template<typename FloatType, typename IntegralType, IntegralType SignedBit> bool FMath::TIsNearlyEqualByULP (FloatType A, FloatType B, int32 MaxUlps) inline static private
Definition at line 424 of file UnrealMathUtility.h.
References A, B, and Distance.
Referenced by IsNearlyEqualByULP(), and IsNearlyEqualByULP().
TruncateToHalfIfClose() [1/2]
double FMath::TruncateToHalfIfClose (double F, double Tolerance = (1.e-8f)) static nodiscard
References UE_SMALL_NUMBER.
TruncateToHalfIfClose() [2/2]
float FMath::TruncateToHalfIfClose (float F, float Tolerance = (1.e-8f)) static nodiscard
Truncates a floating point number to half if closer than the given tolerance.
Parameters
F Floating point number to truncate
Tolerance Maximum allowed difference to 0.5 in order to truncate
Returns
The truncated value
References UE_SMALL_NUMBER.
UE_DEPRECATED()
template<typename T UE_REQUIRES> FMath::UE_DEPRECATED (5. 5, "Use of FMath::Wrap with non-floating point arguments is deprecated - consider FMath::WrapExclusive instead.") const nodiscard
UnwindDegrees()
template<typename T UE_REQUIRES> constexpr T FMath::UnwindDegrees (T A) inline static nodiscard constexpr
Utility to ensure angle is between +/- 180 degrees by unwinding.
Definition at line 1003 of file UnrealMathUtility.h.
References A.
Referenced by UE::Math::TVector< T >::UnwindEuler().
UnwindRadians()
template<typename T UE_REQUIRES> constexpr T FMath::UnwindRadians (T A) inline static nodiscard constexpr
Given a heading which may be outside the +/- PI range, 'unwind' it back into that range.
Definition at line 983 of file UnrealMathUtility.h.
References A, UE_PI, and UE_TWO_PI.
Referenced by FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation().
Vector2DInterpConstantTo()
FVector2D FMath::Vector2DInterpConstantTo (const FVector2D & Current, const FVector2D & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate vector2D from Current to Target with constant step.
References DeltaTime, and Target.
Vector2DInterpTo()
template<typename T> UE::Math::TVector2< T > FMath::Vector2DInterpTo (const UE::Math::TVector2< T > & Current, const UE::Math::TVector2< T > & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate vector2D from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
References DeltaTime, and Target.
VInterpConstantTo()
FVector FMath::VInterpConstantTo (const FVector & Current, const FVector & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate vector from Current to Target with constant step.
References DeltaTime, FVector, and Target.
VInterpNormalRotationTo()
FVector FMath::VInterpNormalRotationTo (const FVector & Current, const FVector & Target, float DeltaTime, float RotationSpeedDegrees) static nodiscard
Interpolate a normal vector Current to Target, by interpolating the angle between those vectors with constant step.
References DeltaTime, FVector, and Target.
VInterpTo()
FVector FMath::VInterpTo (const FVector & Current, const FVector & Target, float DeltaTime, float InterpSpeed) static nodiscard
Interpolate vector from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
References DeltaTime, FVector, and Target.
VRand()
FVector FMath::VRand () inline static nodiscard
Return a uniformly distributed random unit length vector = point on the unit sphere surface.
Definition at line 2706 of file Vector.h.
References FVector, and UE_KINDA_SMALL_NUMBER.
VRandCone() [1/2]
FVector FMath::VRandCone (FVector const & Dir, float ConeHalfAngleRad) static nodiscard
Returns a random unit vector, uniformly distributed, within the specified cone ConeHalfAngleRad is the half-angle of cone, in radians.
Returns a normalized vector.
References FVector.
VRandCone() [2/2]
FVector FMath::VRandCone (FVector const & Dir, float HorizontalConeHalfAngleRad, float VerticalConeHalfAngleRad) static nodiscard
This is a version of VRandCone that handles "squished" cones, i.e.
with different angle limits in the Y and Z axes. Assumes world Y and Z, although this could be extended to handle arbitrary rotations.
References FVector.
WeightedMovingAverage()
template<typename T> T FMath::WeightedMovingAverage (T CurrentSample, T PreviousSample, T Weight) inline static nodiscard
Calculates the new value in a weighted moving average series using the previous value and the weight.
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
Weight - The weight to blend with
Returns
the next value in the series
Definition at line 2564 of file UnrealMathUtility.h.
References Clamp(), and Weight.
Referenced by DynamicWeightedMovingAverage().
WindRelativeAnglesDegrees() [1/2]
void FMath::WindRelativeAnglesDegrees (double InAngle0, double & InOutAngle1) static
WindRelativeAnglesDegrees() [2/2]
void FMath::WindRelativeAnglesDegrees (float InAngle0, float & InOutAngle1) static
Given two angles in degrees, 'wind' the rotation in Angle1 so that it avoids >180 degree flips.
Good for winding rotations previously expressed as quaternions into a euler-angle representation.
Parameters
InAngle0 The first angle that we wind relative to.
InOutAngle1 The second angle that we may wind relative to the first.
Wrap()
template<typename T UE_REQUIRES> constexpr FORCEINLINE T FMath::Wrap (const T X, const T Min, const T Max) inline static nodiscard constexpr
Wraps X to be between Min and Max, inclusive.
When X can wrap to both Min and Max, it will wrap to Min if it lies below the range and wrap to Max if it is above the range.
Definition at line 647 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, WrapImpl(), and X.
WrapExclusive()
template<typename T UE_REQUIRES> constexpr FORCEINLINE T FMath::WrapExclusive (const T X, const T Min, const T Max) inline static nodiscard constexpr
Wraps X to be between Min and Max, exclusive.
Will never return Max.
Definition at line 666 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, Modulo(), TSequenceHistory< HistorySize >::Size, and X.
WrapImpl()
template<class T> constexpr FORCEINLINE T FMath::WrapImpl (const T X, const T Min, const T Max) inline static nodiscard constexpr private
Definition at line 608 of file UnrealMathUtility.h.
References FORCEINLINE, Max, Min, Modulo(), TSequenceHistory< HistorySize >::Size, and X.
Referenced by Wrap().
Field Documentation
BitFlag
const uint32 FMath::BitFlag[32] static
32 bit values where BitFlag[x] == (1<<x)
Definition at line 2419 of file UnrealMathUtility.h.
Max
const T const T FMath::Max
Initial value:
{
        return WrapImpl(X, Min, Max)
Definition at line 656 of file UnrealMathUtility.h.
Referenced by FFloat3PackedSE::FFloat3PackedSE(), FKelvinletBrushOp::FKelvinletBrushOpProperties::FKelvinletBrushOpProperties(), UE::Geometry::FModuloIteration::FModuloIteration(), FRigidBodyIndexPair::FRigidBodyIndexPair(), UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds(), TNumericPropertyParams< NumericType >::TNumericPropertyParams(), UE::Sequencer::FOutlinerSizing::Accumulate(), FBinaryHeap< KeyType, IndexType >::Add(), FCompositeNavModifier::Add(), FHashTable::Add(), TEvaluationTreeEntryContainer< ElementType >::Add(), THashTable< InAllocator >::Add(), UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), FStructBuilder::AddMember(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddOrGetAnnotation(), FStatisticalValue< double >::AddSample(), FTextureLayout::AddSurfaceInner(), ArrangeUtils::AlignCenter(), AlignChild(), AlignChild(), ArrangeUtils::AlignFill(), TRangeAllocator< FAllocatorModifier >::Alloc(), TRangeAllocator< FAllocatorModifier >::FChunk::Alloc(), FSpanAllocator::Allocate(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AllocateAnnotation(), FVirtualAllocator::AllocateVirtualPages(), FBitWriter::AllowAppend(), UE::Geometry::FDynamicGraph::AppendEdge(), UE::Geometry::TOrientedBox2< float >::Area(), ArrangeChildrenInStack(), UE::Geometry::TImageBuilder< PixelType >::BilinearSample(), UE::Math::TIntRect< int32 >::Bottom(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BoxDistanceSqr(), FPrimitiveUniformShaderParametersBuilder::Build(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), RenderingSpatialHash::CalcLevelAndLocationClamped(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForDiffNodes(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForMatchingValues(), FGrowableMallocChunk::CanFitEntry(), UE::Geometry::FSparseDynamicPointOctree3::CheckValidity(), Clamp(), Clamp(), Clamp(), Clamp(), UE::Geometry::TIntrLine2Line2< double >::Classify(), UE::Math::TIntRect< int32 >::Clip(), UE::Geometry::FSizedDisjointSet::CompactedGroupIndexToGroupID(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CompactInvocationList(), UE::Math::TIntPoint< IntType >::ComponentMax(), UE::Math::TIntVector2< int32 >::ComponentMax(), UE::Math::TIntVector3< int32 >::ComponentMax(), UE::Math::TIntVector4< int32 >::ComponentMax(), UE::Math::TVector2< T >::ComponentMax(), UE::Math::TVector4< T >::ComponentMax(), UE::Math::TVector< T >::ComponentMax(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), FBuoyancyComponentSim::ComputeBuoyancy(), ComputeClampableFloatVectorCurveTangent(), UE::Geometry::FClusterKMeans::ComputeClusters(), FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), ComputeCurveTangent(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::ComputeMaxLookups(), FSkinnedMeshComponentHelper::ComputeMinLOD(), UE::Geometry::FSparseDynamicPointOctree3::ComputeStatistics(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::CreateArrayNoInit(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::CreateNoInit(), FStaticMeshComponentHelper::CreateSceneProxy(), CropUnmappedTexels(), DECLARE_STATS_GROUP(), UE::Geometry::TOrientedBox2< float >::DistanceSquared(), UE::Geometry::TOrientedBox3< float >::DistanceSquared(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::DumpStats(), TraceServices::TIntervalTimeline< EventType, SettingsType >::EmplaceBeginEvent(), TraceServices::TPointTimeline< EventType, SettingsType >::EmplaceEvent(), TBitArray< typename Allocator::BitArrayAllocator >::Empty(), TLruCache< KeyType, ValueType, KeyComp >::Empty(), TraceServices::TIntervalTimeline< EventType, SettingsType >::EndEvent(), ENUM_CLASS_FLAGS(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), Metasound::TArraySubsetOperator< ArrayType >::Execute(), FSlateRect::Expand(), FLandscapeConfigHelper::ExpandData(), FDisplayClusterWarpProjection::ExpandProjectionAngles(), UE::Geometry::FDynamicGraph::FindEdge(), FGrowableMallocChunk::Free(), TRangeAllocator< FAllocatorModifier >::FChunk::Free(), UE::Geometry::FCapsuleGenerator::Generate(), UE::Geometry::FCylinderGenerator::Generate(), UE::Geometry::FGridBoxMeshGenerator::Generate(), UE::Geometry::FSphereGenerator::Generate(), UE::Math::TIntVector2< int32 >::GetAbsMax(), UE::Math::TIntVector3< int32 >::GetAbsMax(), UE::Math::TIntVector4< int32 >::GetAbsMax(), UE::Math::TVector2< T >::GetAbsMax(), UE::Math::TVector< T >::GetAbsMax(), FPrimitiveSceneProxy::GetAbsMaxDisplacement(), FMusicalAudioBus::GetAudioLevel(), UE::Geometry::FSegmentTree3::GetBoxDistanceSqr(), UE::Geometry::TSparseListSet< ElementType >::GetCount(), FStaticMeshRenderData::GetCurrentFirstLODIdx(), FRigVMMemoryHandle::GetData_Internal(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEventInfo(), UE::Geometry::FGroupTopology::GetGroupID(), UE::Geometry::FConvexDecomposition3::FConvexPart::GetHullDepth(), TNetworkSimAuxBuffer< ElementType >::GetImpl(), Audio::GetInterpolationParametersAtTimestamp(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeys(), FMarqueeRect::GetLowerRight(), FLinearColor::GetMax(), FTwoVectors::GetMax(), UE::Math::TIntPoint< IntType >::GetMax(), UE::Math::TIntVector2< int32 >::GetMax(), UE::Math::TIntVector3< int32 >::GetMax(), UE::Math::TIntVector4< int32 >::GetMax(), UE::Math::TVector2< T >::GetMax(), UE::Math::TVector< T >::GetMax(), UE::Geometry::FDynamicGraph::GetMaxVtxEdgeCount(), FLandscapeTextureDataInfo::GetMipSizeX(), FLandscapeTextureDataInfo::GetMipSizeY(), FCompressibleAnimData::GetNumberOfFrames(), STileView< ItemType >::GetNumItemsPerLine(), FVirtualAllocator::GetPagesForSizeAndAlignment(), FSkeletalMeshRenderData::GetPendingFirstLODIdx(), FPerformanceTrackingChart::GetPercentMissedVSync(), UE::Geometry::CurveUtil::GetPrevNext(), FPropertyChangedParams::GetPropertyValue(), FDistributionLookupTable::GetRange(), TScriptSparseArray< typename Allocator::SparseArrayAllocator >::GetScriptLayout(), anonymous_namespace{LandscapeLight.h}::GetTerrainExpandPatchCount(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), FLinkedBoxManager::GetUniformCellSize(), FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc(), FSkinnedMeshComponentHelper::GetUsedMaterials(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetValueRange(), SampledSequenceDrawingUtils::GroupInterleavedSamplesIntoMinMaxBins(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Grow(), UE::Geometry::TMeshQueries< TriangleMeshType >::HausdorffDistance(), UE::Geometry::TMeshQueries< TriangleMeshType >::HausdorffDistanceSerial(), UE::Math::TIntRect< int32 >::Include(), UCapsuleComponent::InitCapsuleSize(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), UE::Geometry::FIndexFlagSet::InitManual(), FAttributesSetBase::Insert(), TEvaluationTreeEntryContainer< ElementType >::Insert(), TMeshAttributeArraySet< AttributeType >::Insert(), TMeshUnboundedAttributeArraySet< AttributeType >::Insert(), FAtmosphereSetup::InternalInit(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), FTextRange::Intersect(), TInterval< float >::Intersect, FSlateRect::IntersectionWith(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::IntersectRect(), UE::Math::TSphere< double >::Intersects(), Freeze::IntrinsicGetTargetAlignment(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), UE::Geometry::TPolygon2< double >::MakeRoundedRectangle(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::Malloc(), FInstanceAttributeTracker::MarkIndex(), UE::Math::TVector2< T >::Max(), UE::Math::TVector< T >::Max(), Max3(), UE::Shader::MaxBound(), UE::Geometry::TMeshQueries< TriangleMeshType >::MaxEdgeLength(), UE::Geometry::TOrientedBox3< float >::Merge(), FVirtualTextureLocalTileRequest::MergeWith(), UE::Geometry::TMeshQueries< TriangleMeshType >::MeshDistanceStatistics(), UE::Geometry::FPointPlanarSnapSolver::MinInternalPriority(), TFixedTickReplicator_SP< InModelDef >::NetRecv(), TIndependentTickReplicator_SP< InModelDef >::NetRecv(), FTextRange::Offset(), UE::Geometry::FIterativeOffsetMeshOp::Offset(), UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed(), FAIBasicCounter< TCounterType >::OnIndexForced(), SNodePanel::SNode::OnPaint(), UE::Math::TBoxSphereBounds< T, TExtent >::operator+(), FHistogram::operator+=(), UE::Math::TBox2< T >::operator+=(), UE::Math::TBox2< T >::operator+=(), UE::Math::TBox< T >::operator+=(), UE::Math::TBox< T >::operator+=(), UE::Geometry::FRefCountVector::operator==, FMaterialRelevance::operator|=(), UE::Math::TBox2< T >::Overlap(), UE::Math::TBox< T >::Overlap(), UE::Geometry::TOrientedBox2< float >::Perimeter(), FCurveEditorScreenSpaceH::PixelsPerInput(), FCurveEditorScreenSpaceV::PixelsPerOutput(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::PromoteToLargerBin(), FBlendableManager::PushBlendableData(), FMemStackBase::PushBytes(), FQuartLatencyTracker::PushSingleResult(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::QuantizeSizeCommon(), RandRange(), RandRange(), SListView< TSharedPtr< FString > >::ReGenerateItems(), STileView< ItemType >::ReGenerateItems(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Rehash(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveAll(), FInstanceAttributeTracker::RemoveAt(), FInstanceAttributeTracker::RemoveAtSwap(), UE::Geometry::FDynamicGraph::replace_edge_vertex(), FEditorViewportClient::RequestRealTimeFrames(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Reserve(), UE::Geometry::TPointHashGrid3< PointDataType, double >::Reset(), FTextureRenderTarget2DResource::Resize(), UE::Geometry::TDynamicVector< Type, BlockSize >::Resize(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), UE::Math::TIntRect< int32 >::Right(), UE::Geometry::FNegativeSpaceSampleSettings::Sanitize(), FBulkDataWriter::Serialize(), TBitArray< typename Allocator::BitArrayAllocator >::Serialize(), FBaseKelvinletBrushOp::SetBaseProperties(), Audio::FQuartzClockTickRate::SetBeatsPerMinute(), SGridPanel::FSlot::SetColumn(), UE::Geometry::TIntrLine2Line2< double >::SetDistThreshold(), UE::Geometry::TIntrLine2Line2< double >::SetDotThreshold(), UE::Geometry::TIntrSegment2Segment2< double >::SetDotThreshold(), UE::Geometry::FDynamicGraph::SetEdgeGroup(), UE::Geometry::FPolygroupSet::SetGroup(), UE::Geometry::TIntrSegment2Segment2< double >::SetIntervalThreshold(), TDefaultNumericTypeInterface< NumericType >::SetMaxFractionalDigits(), Audio::FQuartzClockTickRate::SetMillisecondsPerTick(), TDefaultNumericTypeInterface< NumericType >::SetMinFractionalDigits(), SGridPanel::FSlot::SetRow(), Audio::FQuartzClockTickRate::SetSampleRate(), Audio::FQuartzClockTickRate::SetThirtySecondNotesPerMinute(), UE::Geometry::FImageTiling::SetTiling(), UE::Geometry::FDynamicMesh3::SetTriangleGroup(), FDelayedDrag::SetTriggerScaleFactor(), UE::Geometry::TOrientedBox3< float >::SignedDistance(), UE::Math::TBoxSphereBounds< float, float >::SpheresIntersect(), FStreamableRenderResourceState::StreamOut(), UE::Geometry::TOrientedBox3< float >::SurfaceArea(), TSpring1D< float >::Tick(), AnimEncoding::TimeToIndex(), FMarqueeRect::ToSlateRect(), TDefaultNumericTypeInterface< NumericType >::ToString(), TLumenCardOBB< float >::Transform(), UE::Math::TSphere< T >::TransformBy(), UE::Geometry::TMeshQueries< TriangleMeshType >::TwoSidedHausdorffDistance(), UE::Geometry::TMeshQueries< TriangleMeshType >::TwoSidedHausdorffDistanceSerial(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Math::TIntRect< int32 >::Union(), LandscapeDataAccess::UnpackNormal(), FRK4SpringInterpolator< float >::Update(), FDisplayClusterWarpAABB::UpdateAABB(), FTextureLayout3d::UpdateSize(), FTextureLayout::UpdateSize(), FPlanarReflectionSceneProxy::UpdateTransform(), TBaseBlendedCurve< InAllocatorType, InElementType >::UseMaxValue(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), VectorIntMax(), FPixelStreamingVideoInputBackBufferComposited::VectorMax(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMax(), VectorMax(), VectorMax(), UE::Geometry::TOrientedBox3< float >::Volume(), Wrap(), WrapExclusive(), WrapImpl(), FCachedFileHandle::Write(), FManagedStorageFileWriteHandle::Write(), FMemoryImageSection::WriteAlignment(), TNetworkSimAuxBuffer< ElementType >::WriteAtFrame(), and UE::Color::xyYToXYZ().
Min
const T FMath::Min
Definition at line 656 of file UnrealMathUtility.h.
Referenced by FRigidBodyIndexPair::FRigidBodyIndexPair(), UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), TNumericPropertyParams< NumericType >::TNumericPropertyParams(), EHairResourceStatus::AddAvailableCurve(), FStatisticalValue< double >::AddSample(), ArrangeUtils::AlignCenter(), AlignChild(), AlignChild(), FVirtualAllocator::AllocateVirtualPages(), ArrangeChildrenInStack(), FFrameRate::AsFrameTime(), TAudioBuffer< DataType >::AssertEqualWithTolerance(), UE::Geometry::TImageBuilder< PixelType >::BilinearSample(), FMipBiasFade::CalcMipBias(), Clamp(), Clamp(), Clamp(), Clamp(), UE::Math::TIntRect< int32 >::Clip(), TMemoryView< const void >::CompareBytes(), UE::Math::TIntPoint< IntType >::ComponentMin(), UE::Math::TIntVector2< int32 >::ComponentMin(), UE::Math::TIntVector3< int32 >::ComponentMin(), UE::Math::TIntVector4< int32 >::ComponentMin(), UE::Math::TVector2< T >::ComponentMin(), UE::Math::TVector4< T >::ComponentMin(), UE::Math::TVector< T >::ComponentMin(), UE::Geometry::FClusterKMeans::ComputeClusters(), TAudioBuffer< DataType >::ComputeOverview(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), UE::LWC::ConvertArrayTypeClampMax(), ConvertFrameTime(), TAudioBuffer< DataType >::Copy(), TMeshAttributesRef< ElementIDType, AttributeType >::Copy(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Copy(), TStringView< CharType >::CopyString(), TChunkedArray< TUniquePtr< DescType > >::CopyToLinearArray(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CopyUnchecked(), CropUnmappedTexels(), FPrimitiveUniformShaderParametersBuilder::CustomPrimitiveData(), TAudioBuffer< DataType >::Deinterleave(), TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), UE::Geometry::FMarchingCubes::edge_hash(), TraceServices::TIntervalTimeline< EventType, SettingsType >::EmplaceBeginEvent(), TraceServices::TPointTimeline< EventType, SettingsType >::EmplaceEvent(), FFormatArgsTrace::EncodeArgumentInternal(), ENUM_CLASS_FLAGS(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), Metasound::TArraySubsetOperator< ArrayType >::Execute(), FSlateRect::Expand(), FLandscapeConfigHelper::ExpandData(), FDisplayClusterWarpProjection::ExpandProjectionAngles(), Harmonix::Dsp::Modulators::FAdsr::FastRelease(), UE::Geometry::FDynamicGraph::FindEdge(), FStreamingSourceShapeHelper::ForEachShape(), UE::Math::TIntVector2< int32 >::GetAbsMin(), UE::Math::TIntVector3< int32 >::GetAbsMin(), UE::Math::TIntVector4< int32 >::GetAbsMin(), UE::Math::TVector< T >::GetAbsMin(), FFormatArgsTrace::GetArgumentEncodedSize(), FInstanceAttributeTracker::GetChangedIterator(), FRDGPooledBuffer::GetCommittedSize(), FHairStrandsBulkData::GetCurveAttributeSizeInBytes(), FDistributionLookupTable::GetEntry(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeys(), FLinearColor::GetMin(), FTwoVectors::GetMin(), UE::Math::TIntPoint< IntType >::GetMin(), UE::Math::TIntVector2< int32 >::GetMin(), UE::Math::TIntVector3< int32 >::GetMin(), UE::Math::TIntVector4< int32 >::GetMin(), UE::Math::TVector2< T >::GetMin(), UE::Math::TVector< T >::GetMin(), FHairStrandsBulkData::GetPointAttributeSizeInBytes(), FHairStrandsBulkData::GetPointToCurveSizeInBytes(), UE::Geometry::CurveUtil::GetPrevNext(), FDistributionLookupTable::GetRange(), FAnimSequenceDecompressionContext::GetRelativePosition(), FDisplayClusterShaderParameters_GenerateMips::GetRequiredNumMips(), TSubSectionMixin< ParentSectionClass >::GetSectionToolTip(), anonymous_namespace{LandscapeLight.h}::GetTerrainExpandPatchCount(), FHairStrandsBulkData::GetTranscodedPositionSizeInBytes(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), UE::Geometry::FClusterKMeans::GetUniformSpacedInitialCenters(), FMarqueeRect::GetUpperLeft(), FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetValueRange(), SampledSequenceDrawingUtils::GroupInterleavedSamplesIntoMinMaxBins(), UE::Math::TIntRect< int32 >::Include(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), TAudioBuffer< DataType >::Interleave(), FTextRange::Intersect(), TInterval< float >::Intersect, FSlateRect::IntersectionWith(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::IntersectRect(), Freeze::IntrinsicGetTargetAlignment(), Freeze::IntrinsicGetTargetAlignment(), Freeze::IntrinsicGetTargetAlignment(), Freeze::IntrinsicGetTargetAlignment(), Freeze::IntrinsicGetTargetAlignment(), TMemoryView< const void >::LeftChopInline(), TMemoryView< const void >::LeftInline(), TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckBounds(), FInstanceAttributeTracker::LoadCountAndMask(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), FInstanceAttributeTracker::MarkIndex(), FInstanceAttributeTracker::MarkRemoved(), UE::Geometry::TMeshQueries< TriangleMeshType >::MeshDistanceStatistics(), UE::Math::TVector2< T >::Min(), UE::Math::TVector< T >::Min(), Min3(), UE::Shader::MinBound(), UE::Geometry::TMeshQueries< TriangleMeshType >::MinEdgeLength(), UE::Geometry::FPointPlanarSnapSolver::MinInternalPriority(), FInstanceAttributeTracker::FAnyValidIterator< Mask >::operator bool(), UE::Math::TBoxSphereBounds< T, TExtent >::operator+(), FColor::operator+=(), FHistogram::operator+=(), UE::Math::TBox2< T >::operator+=(), UE::Math::TBox2< T >::operator+=(), UE::Math::TBox< T >::operator+=(), UE::Math::TBox< T >::operator+=(), Metasound::TParamPackFixedArray< typename T::ElementType, MaxNumItems >::operator=(), UE::Math::TBox2< T >::Overlap(), UE::Math::TBox< T >::Overlap(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), TAllocPlaybackLog< FModifier, FAllocOp >::Play(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), MallocBinnedPrivate::TGlobalRecycler< NumSmallPools >::PopBundle(), TStringView< CharType >::PrivateCompare(), Experimental::RobinHoodHashTable_Private::TFreeList< AllocatorType >::Push(), TOctree2< ElementType, OctreeSemantics >::FFreeList::Push(), MallocBinnedPrivate::TGlobalRecycler< NumSmallPools >::PushBundle(), FQuartLatencyTracker::PushSingleResult(), RandHelper(), RandHelper64(), RandRange(), RandRange(), FCachedFileHandle::Read(), FMallocDebug::Realloc(), IMovieSceneKeyProxy::RefreshCurrentValue(), SListView< TSharedPtr< FString > >::ReGenerateItems(), TInstanceMap< T >::Remove(), TStableInstanceMap< T >::Remove(), FInstanceAttributeTracker::RemoveAt(), FInstanceAttributeTracker::RemoveAtSwap(), UE::Geometry::FDynamicGraph::replace_edge_vertex(), FLandscapeConfigHelper::ResampleData(), FSimpleStreamableAssetManager::TSimpleSparseArray< T >::Reset(), TNetworkPredictionBuffer< ElementType, SingleElement >::Resize(), TNetworkSimAuxBuffer< ElementType >::Resize(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), FBinaryHeap< KeyType, IndexType >::ResizeHeap(), TMemoryView< const void >::RightChopInline(), TMemoryView< const void >::RightInline(), UE::FPlatformIoDispatcherBase::ScatterGather(), TSimpleCellGrid< CellType, InvalidCellValue >::Serialize(), UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize(), Metasound::TAudioSender< TDataType >::SetDelay(), UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetGridCellSize(), UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetMeshCellSize(), SetShaderValue(), SetShaderValueArray(), FSlateTextElement::SetText(), TDeque< InElementType, InAllocatorType >::ShiftElementsLeft(), FTabManager::FArea::SplitAt(), FStreamableRenderResourceState::StreamIn(), TSpring1D< float >::Tick(), AnimEncoding::TimeToIndex(), FMarqueeRect::ToSlateRect(), FMemoryReader::TotalSize(), FMemoryReaderView::TotalSize(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), UE::Math::TIntRect< int32 >::Union(), FRK4SpringInterpolator< float >::Update(), FDisplayClusterWarpAABB::UpdateAABB(), TBaseBlendedCurve< InAllocatorType, InElementType >::UseMinValue(), USTRUCT(), VectorIntMin(), FPixelStreamingVideoInputBackBufferComposited::VectorMin(), UE::EditorPixelStreaming2::FVideoProducerBackBufferComposited::VectorMin(), VectorMin(), VectorMin(), Wrap(), WrapExclusive(), and WrapImpl().
The documentation for this struct was generated from the following files:
UnrealMathUtility.h
Box.h
Plane.h
Rotator.h
Sphere.h
Vector.h