Unreal Engine 5.6 C++ API: PropertyAccess Namespace Reference
PropertyAccess Namespace Reference
Data Structures
struct FCopyBatchId
Batch ID - organisation/batching strategy determined by client systems via compilation.
Functions
void GetAccessAddress (UObject *InObject, const FPropertyAccessLibrary &InLibrary, int32 InAccessIndex, TFunctionRef< void(const FProperty *, void *)> InFunction)
Gets the property and address of the specified access, minimally-resolving all compiled-in indirections.
void PatchPropertyOffsets (FPropertyAccessLibrary &InLibrary)
Called to patch up library after it is loaded or linked This converts all FName-based paths into node-based paths that provide an optimized way of accessing properties.
void ProcessCopies (UObject *InObject, const FPropertyAccessLibrary &InLibrary, const FCopyBatchId &InBatchId)
Process a 'tick' of a property access instance.
void ProcessCopy (UObject *InObject, const FPropertyAccessLibrary &InLibrary, const FCopyBatchId &InBatchId, int32 InCopyIndex, TFunctionRef< void(const FProperty *, void *)> InPostCopyOperation)
Process a single copy Note that this can potentially allocate via FMemStack, so inserting FMemMark before a number of these calls is recommended.
UE_DEPRECATED (5.0, "Please use PatchPropertyOffsets instead") 1 extern void PostLoadLibrary(FPropertyAccessLibrary &InLibrary)
UE_DEPRECATED (5.0, "Please use the signature that takes a FCopyBatchId BatchId") 1 extern void ProcessCopies(UObject *InObject
UE_DEPRECATED (5.0, "Property Access Events are no longer supported") 1 extern void BindEvents(UObject *InObject
Variables
const FPropertyAccessLibrary EPropertyAccessCopyBatch InBatchType
const FPropertyAccessLibrary EPropertyAccessCopyBatch int32 InCopyIndex
const FPropertyAccessLibrary & InLibrary
TArrayView< const FName > InPath
const FPropertyAccessLibrary EPropertyAccessCopyBatch int32 TFunctionRef< void(const FProperty *, void *)> InPostCopyOperation
Function Documentation
GetAccessAddress()
void PropertyAccess::GetAccessAddress (UObject * InObject, const FPropertyAccessLibrary & InLibrary, int32 InAccessIndex, TFunctionRef< void(const FProperty *, void *)> InFunction) extern
Gets the property and address of the specified access, minimally-resolving all compiled-in indirections.
References Array, GetAccessAddress(), InLibrary, Object, and UENUM.
Referenced by GetAccessAddress().
PatchPropertyOffsets()
void PropertyAccess::PatchPropertyOffsets (FPropertyAccessLibrary & InLibrary) extern
Called to patch up library after it is loaded or linked This converts all FName-based paths into node-based paths that provide an optimized way of accessing properties.
References InLibrary, and PatchPropertyOffsets().
Referenced by PatchPropertyOffsets().
ProcessCopies()
void PropertyAccess::ProcessCopies (UObject * InObject, const FPropertyAccessLibrary & InLibrary, const FCopyBatchId & InBatchId) extern
Process a 'tick' of a property access instance.
Note internally allocates via FMemStack and pushes its own FMemMark
References InLibrary, and ProcessCopies().
Referenced by ProcessCopies().
ProcessCopy()
void PropertyAccess::ProcessCopy (UObject * InObject, const FPropertyAccessLibrary & InLibrary, const FCopyBatchId & InBatchId, int32 InCopyIndex, TFunctionRef< void(const FProperty *, void *)> InPostCopyOperation) extern
Process a single copy Note that this can potentially allocate via FMemStack, so inserting FMemMark before a number of these calls is recommended.
References InCopyIndex, InLibrary, InPostCopyOperation, ProcessCopy(), and UE_DEPRECATED().
Referenced by ProcessCopy().
UE_DEPRECATED() [1/3]
PropertyAccess::UE_DEPRECATED (5. 0, "Please use PatchPropertyOffsets instead") &
References InLibrary.
Referenced by ProcessCopy(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
PropertyAccess::UE_DEPRECATED (5. 0, "Please use the signature that takes a FCopyBatchId BatchId")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
PropertyAccess::UE_DEPRECATED (5. 0, "Property Access Events are no longer supported")
References InLibrary, and UE_DEPRECATED().
Variable Documentation
InBatchType
const FPropertyAccessLibrary EPropertyAccessCopyBatch PropertyAccess::InBatchType
Definition at line 64 of file PropertyAccess.h.
InCopyIndex
const FPropertyAccessLibrary EPropertyAccessCopyBatch int32 PropertyAccess::InCopyIndex
Definition at line 73 of file PropertyAccess.h.
Referenced by ProcessCopy().
InLibrary
const FPropertyAccessLibrary & PropertyAccess::InLibrary
Definition at line 64 of file PropertyAccess.h.
Referenced by GetAccessAddress(), PatchPropertyOffsets(), ProcessCopies(), ProcessCopy(), UE_DEPRECATED(), and UE_DEPRECATED().
InPath
TArrayView<const FName> PropertyAccess::InPath
Definition at line 79 of file PropertyAccess.h.
InPostCopyOperation
const FPropertyAccessLibrary EPropertyAccessCopyBatch int32 TFunctionRef<void(const FProperty*, void*)> PropertyAccess::InPostCopyOperation
Definition at line 73 of file PropertyAccess.h.
Referenced by ProcessCopy().