Unreal Engine 5.6 C++ API: FGenericShaderStat Struct Reference
FGenericShaderStat Struct Reference
#include "ShaderCore.h"
Public Types
enum class EFlags : uint8 { None = 0 , Hidden = 1 << 0 }
Public Member Functions
FGenericShaderStat ()=default
bool operator== (const FGenericShaderStat &RHS) const
RENDERCORE_API void StreamArchive (FArchive &Ar)
Data Fields
EFlags Flags = EFlags::None
FName StatName
FName TagName
FShaderStatVariant Value
Friends
FArchive & operator<< (FArchive &Ar, FGenericShaderStat &Stat)
Detailed Description
Definition at line 68 of file ShaderCore.h.
Member Enumeration Documentation
EFlags
enum class FGenericShaderStat::EFlags : uint8 strong
Enumerator
None
Hidden
Definition at line 71 of file ShaderCore.h.
Constructor & Destructor Documentation
FGenericShaderStat()
FGenericShaderStat::FGenericShaderStat () default
Referenced by operator<<, and operator==().
Member Function Documentation
operator==()
bool FGenericShaderStat::operator== (const FGenericShaderStat & RHS) const
References FGenericShaderStat().
StreamArchive()
RENDERCORE_API void FGenericShaderStat::StreamArchive (FArchive & Ar)
References Ar.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FGenericShaderStat & Stat) friend
Definition at line 83 of file ShaderCore.h.
References FGenericShaderStat(), Ar, and Stat.
Field Documentation
Flags
EFlags FGenericShaderStat::Flags = EFlags::None
Definition at line 78 of file ShaderCore.h.
StatName
FName FGenericShaderStat::StatName
Definition at line 76 of file ShaderCore.h.
TagName
FName FGenericShaderStat::TagName
Definition at line 79 of file ShaderCore.h.
Value
FShaderStatVariant FGenericShaderStat::Value
Definition at line 77 of file ShaderCore.h.
The documentation for this struct was generated from the following file:
ShaderCore.h