Unreal Engine 5.6 C++ API: Verse::TNativeSubtype< T, BaseType > Class Template Reference
Verse::TNativeSubtype< T, BaseType > Class Template Reference
#include "VVMNativeType.h"
Public Member Functions
TNativeSubtype ()=delete
TNativeSubtype (BaseType &&Other)
TNativeSubtype (const BaseType &Other)
TNativeSubtype (EDefaultConstructNativeType)
TNativeSubtype (UClass *InType)
TNativeSubtype & operator= (BaseType &&Other)
TNativeSubtype & operator= (const BaseType &Other)
Public Member Functions inherited from Verse::FNativeType
UClass * AsUEClassCheckedUnsafeDoNotUse () const
FNativeTypeBase ()=delete
FNativeTypeBase (EDefaultConstructNativeType)
FNativeTypeBase (UClass *InType)
bool IsTypeOfUnsafeDoNotUse (UObject *Obj) const
Public Member Functions inherited from Verse::FNativeTypeBase
FNativeTypeBase ()=delete
FNativeTypeBase (EDefaultConstructNativeType)
FNativeTypeBase (UClass *InType)
UClass * AsUEClassNullableUnsafeDoNotUse () const
bool IsEqualUnsafeDoNotUse (const FNativeTypeBase &Other) const
bool IsNullUnsafeDoNotUse () const
Private Member Functions
void CheckValid () const
Additional Inherited Members
Protected Member Functions inherited from Verse::FNativeTypeBase
UClass * AsUEClassChecked () const
bool IsTypeOf (UObject *Obj) const
Protected Attributes inherited from Verse::FNativeTypeBase
TObjectPtr< UClass > Type
Detailed Description
template<class T, class BaseType = FNativeType>
class Verse::TNativeSubtype< T, BaseType >
Definition at line 77 of file VVMNativeType.h.
Constructor & Destructor Documentation
TNativeSubtype() [1/5]
template<class T, class BaseType = FNativeType> Verse::TNativeSubtype< T, BaseType >::TNativeSubtype () delete
TNativeSubtype() [2/5]
template<class T, class BaseType = FNativeType> Verse::TNativeSubtype< T, BaseType >::TNativeSubtype (EDefaultConstructNativeType) inline
Definition at line 81 of file VVMNativeType.h.
TNativeSubtype() [3/5]
template<class T, class BaseType = FNativeType> Verse::TNativeSubtype< T, BaseType >::TNativeSubtype (BaseType && Other) inline
Definition at line 83 of file VVMNativeType.h.
TNativeSubtype() [4/5]
template<class T, class BaseType = FNativeType> Verse::TNativeSubtype< T, BaseType >::TNativeSubtype (const BaseType & Other) inline
Definition at line 85 of file VVMNativeType.h.
TNativeSubtype() [5/5]
template<class T, class BaseType = FNativeType> Verse::TNativeSubtype< T, BaseType >::TNativeSubtype (UClass * InType) inline
Definition at line 103 of file VVMNativeType.h.
Member Function Documentation
CheckValid()
template<class T, class BaseType = FNativeType> void Verse::TNativeSubtype< T, BaseType >::CheckValid () const inline private
Definition at line 110 of file VVMNativeType.h.
Referenced by Verse::TNativeSubtype< T, FNativeCastableType >::TNativeSubtype(), Verse::TNativeSubtype< T, FNativeCastableType >::TNativeSubtype(), Verse::TNativeSubtype< T, FNativeCastableType >::TNativeSubtype(), Verse::TNativeSubtype< T, FNativeCastableType >::operator=(), and Verse::TNativeSubtype< T, FNativeCastableType >::operator=().
operator=() [1/2]
template<class T, class BaseType = FNativeType> TNativeSubtype & Verse::TNativeSubtype< T, BaseType >::operator= (BaseType && Other) inline
Definition at line 87 of file VVMNativeType.h.
operator=() [2/2]
template<class T, class BaseType = FNativeType> TNativeSubtype & Verse::TNativeSubtype< T, BaseType >::operator= (const BaseType & Other) inline
Definition at line 93 of file VVMNativeType.h.
The documentation for this class was generated from the following file:
VVMNativeType.h