Unreal Engine 5.6 C++ API: UE::Geometry::TIndexMap< IntType > Struct Template Reference
UE::Geometry::TIndexMap< IntType > Struct Template Reference
TIndexMap stores mappings between indices, which are assumed to be an integer type.
#include "GeometryTypes.h"
Public Member Functions
TIndexMap ()
void Add (IntType FromID, IntType ToID)
add mapping from one index to another
bool ContainsFrom (IntType FromID) const
bool ContainsTo (IntType ToID) const
const IntType * FindFrom (IntType ToID) const
const IntType * FindTo (IntType FromID) const
TMap< IntType, IntType > & GetForwardMap ()
const TMap< IntType, IntType > & GetForwardMap () const
IntType GetFrom (IntType ToID) const
TMap< IntType, IntType > & GetReverseMap ()
const TMap< IntType, IntType > & GetReverseMap () const
IntType GetTo (IntType FromID) const
void Reserve (int NumElements)
void Reset ()
constexpr IntType UnmappedID () const
Protected Attributes
bool bWantForward
bool bWantReverse
TMap< IntType, IntType > ForwardMap
TMap< IntType, IntType > ReverseMap
Detailed Description
template<typename IntType>
struct UE::Geometry::TIndexMap< IntType >
TIndexMap stores mappings between indices, which are assumed to be an integer type.
Both forward and backward mapping are stored
Todo
make either mapping optional
optionally support using flat arrays instead of TMaps
constructors that pick between flat array and TMap modes depending on potential size/sparsity of mapped range
identity and shift modes that don't actually store anything
Definition at line 95 of file GeometryTypes.h.
Constructor & Destructor Documentation
TIndexMap()
template<typename IntType> UE::Geometry::TIndexMap< IntType >::TIndexMap () inline
Definition at line 105 of file GeometryTypes.h.
Member Function Documentation
Add()
template<typename IntType> void UE::Geometry::TIndexMap< IntType >::Add (IntType FromID, IntType ToID) inline
add mapping from one index to another
Definition at line 126 of file GeometryTypes.h.
ContainsFrom()
template<typename IntType> bool UE::Geometry::TIndexMap< IntType >::ContainsFrom (IntType FromID) const inline
Returns
true if we can map forward from this value
Definition at line 134 of file GeometryTypes.h.
ContainsTo()
template<typename IntType> bool UE::Geometry::TIndexMap< IntType >::ContainsTo (IntType ToID) const inline
Returns
true if we can reverse-map from this value
Definition at line 142 of file GeometryTypes.h.
FindFrom()
template<typename IntType> const IntType * UE::Geometry::TIndexMap< IntType >::FindFrom (IntType ToID) const inline
Returns
reverse-map of input value or null if not found
Definition at line 177 of file GeometryTypes.h.
FindTo()
template<typename IntType> const IntType * UE::Geometry::TIndexMap< IntType >::FindTo (IntType FromID) const inline
Returns
forward-map of input value or null if not found
Definition at line 169 of file GeometryTypes.h.
GetForwardMap() [1/2]
template<typename IntType> TMap< IntType, IntType > & UE::Geometry::TIndexMap< IntType >::GetForwardMap () inline
Definition at line 119 of file GeometryTypes.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CopyThroughMapping(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CopyThroughMapping(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CopyThroughMapping().
GetForwardMap() [2/2]
template<typename IntType> const TMap< IntType, IntType > & UE::Geometry::TIndexMap< IntType >::GetForwardMap () const inline
Definition at line 120 of file GeometryTypes.h.
GetFrom()
template<typename IntType> IntType UE::Geometry::TIndexMap< IntType >::GetFrom (IntType ToID) const inline
Returns
reverse-map of input value
Definition at line 160 of file GeometryTypes.h.
GetReverseMap() [1/2]
template<typename IntType> TMap< IntType, IntType > & UE::Geometry::TIndexMap< IntType >::GetReverseMap () inline
Definition at line 122 of file GeometryTypes.h.
GetReverseMap() [2/2]
template<typename IntType> const TMap< IntType, IntType > & UE::Geometry::TIndexMap< IntType >::GetReverseMap () const inline
Definition at line 123 of file GeometryTypes.h.
GetTo()
template<typename IntType> IntType UE::Geometry::TIndexMap< IntType >::GetTo (IntType FromID) const inline
Returns
forward-map of input value
Definition at line 151 of file GeometryTypes.h.
Reserve()
template<typename IntType> void UE::Geometry::TIndexMap< IntType >::Reserve (int NumElements) inline
Definition at line 185 of file GeometryTypes.h.
Reset()
template<typename IntType> void UE::Geometry::TIndexMap< IntType >::Reset () inline
Definition at line 110 of file GeometryTypes.h.
UnmappedID()
template<typename IntType> IntType UE::Geometry::TIndexMap< IntType >::UnmappedID () const inline constexpr
Returns
the value used to indicate an ID is not present in the mapping
Definition at line 117 of file GeometryTypes.h.
Referenced by UE::Geometry::TIndexMap< int >::GetFrom(), and UE::Geometry::TIndexMap< int >::GetTo().
Field Documentation
bWantForward
template<typename IntType> bool UE::Geometry::TIndexMap< IntType >::bWantForward protected
Definition at line 100 of file GeometryTypes.h.
bWantReverse
template<typename IntType> bool UE::Geometry::TIndexMap< IntType >::bWantReverse protected
Definition at line 101 of file GeometryTypes.h.
ForwardMap
template<typename IntType> TMap<IntType, IntType> UE::Geometry::TIndexMap< IntType >::ForwardMap protected
Definition at line 98 of file GeometryTypes.h.
ReverseMap
template<typename IntType> TMap<IntType, IntType> UE::Geometry::TIndexMap< IntType >::ReverseMap protected
Definition at line 99 of file GeometryTypes.h.
The documentation for this struct was generated from the following file:
GeometryTypes.h