Unreal Engine 5.6 C++ API: THashTable< InAllocator > Class Template Reference
THashTable< InAllocator > Class Template Reference
#include "HashTable.h"
Public Types
using Allocator = InAllocator
using ElementAllocatorType
Public Member Functions
THashTable (const THashTable &Other)=delete
THashTable (THashTable &&Other)
THashTable (uint32 InHashSize=1024, uint32 InIndexSize=0)
~THashTable ()
void Add (uint16 Key, uint32 Index)
void Clear ()
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
uint32 First (uint16 Key) const
const uint32 * GetNextIndices () const
bool IsValid (uint32 Index) const
THashTable & MoveAssign (THashTable &&Other)
uint32 Next (uint32 Index) const
THashTable & operator= (const THashTable &Other)=delete
THashTable & operator= (THashTable &&Other)
void Remove (uint16 Key, uint32 Index)
void Resize (uint32 NewIndexSize)
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Private Member Functions
FORCEINLINE uint32 & HashAt (uint32 Index)
FORCEINLINE uint32 HashAt (uint32 Index) const
FORCEINLINE uint32 & NextIndexAt (uint32 Index)
FORCEINLINE uint32 NextIndexAt (uint32 Index) const
Private Attributes
ElementAllocatorType Hash
uint32 HashMask
uint32 IndexSize
ElementAllocatorType NextIndex
Detailed Description
template<typename InAllocator>
class THashTable< InAllocator >
Definition at line 466 of file HashTable.h.
Member Typedef Documentation
Allocator
template<typename InAllocator> using THashTable< InAllocator >::Allocator = InAllocator
Definition at line 469 of file HashTable.h.
ElementAllocatorType
template<typename InAllocator> using THashTable< InAllocator >::ElementAllocatorType
Initial value:
 std::conditional_t<
        Allocator::NeedsElementType,
        typename Allocator::template ForElementType<uint32>,
        typename Allocator::ForAnyElementType
    >
Definition at line 471 of file HashTable.h.
Constructor & Destructor Documentation
THashTable() [1/3]
template<typename InAllocator> FORCEINLINE THashTable< InAllocator >::THashTable (uint32 InHashSize = 1024, uint32 InIndexSize = 0) explicit
Definition at line 542 of file HashTable.h.
References check, FORCEINLINE, Hash, HashMask, IndexSize, FMath::IsPowerOfTwo(), FMemory::Memset(), and NextIndex.
Referenced by THashTable< FMemoryImageAllocator >::CopyUnfrozen(), and MoveAssign().
THashTable() [2/3]
template<typename InAllocator> THashTable< InAllocator >::THashTable (const THashTable< InAllocator > & Other) delete
THashTable() [3/3]
template<typename InAllocator> THashTable< InAllocator >::THashTable (THashTable< InAllocator > && Other) inline
Definition at line 479 of file HashTable.h.
~THashTable()
template<typename InAllocator> FORCEINLINE THashTable< InAllocator >::~THashTable ()
Definition at line 559 of file HashTable.h.
References FORCEINLINE.
Member Function Documentation
Add()
template<typename InAllocator> FORCEINLINE void THashTable< InAllocator >::Add (uint16 Key, uint32 Index)
Definition at line 609 of file HashTable.h.
References FORCEINLINE, HashAt(), HashMask, IndexSize, Key, FMath::Max, NextIndexAt(), and Resize().
Clear()
template<typename InAllocator> FORCEINLINE void THashTable< InAllocator >::Clear ()
Definition at line 576 of file HashTable.h.
References FORCEINLINE, Hash, HashMask, IndexSize, and FMemory::Memset().
CopyUnfrozen()
template<typename InAllocator> void THashTable< InAllocator >::CopyUnfrozen (const FMemoryUnfreezeContent & Context, void * Dst) const inline
Definition at line 526 of file HashTable.h.
First()
template<typename InAllocator> FORCEINLINE uint32 THashTable< InAllocator >::First (uint16 Key) const
Definition at line 586 of file HashTable.h.
References FORCEINLINE, HashAt(), HashMask, and Key.
GetNextIndices()
template<typename InAllocator> const uint32 * THashTable< InAllocator >::GetNextIndices () const inline
Definition at line 489 of file HashTable.h.
HashAt() [1/2]
template<typename InAllocator> FORCEINLINE uint32 & THashTable< InAllocator >::HashAt (uint32 Index) inline private
Definition at line 502 of file HashTable.h.
HashAt() [2/2]
template<typename InAllocator> FORCEINLINE uint32 THashTable< InAllocator >::HashAt (uint32 Index) const inline private
Definition at line 500 of file HashTable.h.
Referenced by Add(), First(), and Remove().
IsValid()
template<typename InAllocator> FORCEINLINE bool THashTable< InAllocator >::IsValid (uint32 Index) const
Definition at line 603 of file HashTable.h.
References FORCEINLINE.
MoveAssign()
template<typename InAllocator> THashTable< InAllocator > & THashTable< InAllocator >::MoveAssign (THashTable< InAllocator > && Other)
Definition at line 564 of file HashTable.h.
References THashTable(), Hash, HashMask, IndexSize, NextIndex, and Other.
Referenced by THashTable< FMemoryImageAllocator >::THashTable(), and THashTable< FMemoryImageAllocator >::operator=().
Next()
template<typename InAllocator> FORCEINLINE uint32 THashTable< InAllocator >::Next (uint32 Index) const
Definition at line 594 of file HashTable.h.
References checkSlow, FORCEINLINE, IndexSize, Next(), and NextIndexAt().
Referenced by Next().
NextIndexAt() [1/2]
template<typename InAllocator> FORCEINLINE uint32 & THashTable< InAllocator >::NextIndexAt (uint32 Index) inline private
Definition at line 503 of file HashTable.h.
NextIndexAt() [2/2]
template<typename InAllocator> FORCEINLINE uint32 THashTable< InAllocator >::NextIndexAt (uint32 Index) const inline private
Definition at line 501 of file HashTable.h.
Referenced by Add(), Next(), and Remove().
operator=() [1/2]
template<typename InAllocator> THashTable & THashTable< InAllocator >::operator= (const THashTable< InAllocator > & Other) delete
operator=() [2/2]
template<typename InAllocator> THashTable & THashTable< InAllocator >::operator= (THashTable< InAllocator > && Other) inline
Definition at line 483 of file HashTable.h.
Remove()
template<typename InAllocator> void THashTable< InAllocator >::Remove (uint16 Key, uint32 Index) inline
Definition at line 622 of file HashTable.h.
References HashAt(), HashMask, IndexSize, IsValid(), Key, and NextIndexAt().
Resize()
template<typename InAllocator> void THashTable< InAllocator >::Resize (uint32 NewIndexSize)
Definition at line 650 of file HashTable.h.
References IndexSize, and NextIndex.
Referenced by Add().
WriteMemoryImage()
template<typename InAllocator> void THashTable< InAllocator >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 511 of file HashTable.h.
Field Documentation
Hash
template<typename InAllocator> ElementAllocatorType THashTable< InAllocator >::Hash private
Definition at line 505 of file HashTable.h.
Referenced by THashTable(), Clear(), THashTable< FMemoryImageAllocator >::CopyUnfrozen(), and MoveAssign().
HashMask
template<typename InAllocator> uint32 THashTable< InAllocator >::HashMask private
Definition at line 507 of file HashTable.h.
Referenced by THashTable(), Add(), Clear(), First(), MoveAssign(), and Remove().
IndexSize
template<typename InAllocator> uint32 THashTable< InAllocator >::IndexSize private
Definition at line 508 of file HashTable.h.
Referenced by THashTable(), Add(), Clear(), MoveAssign(), Next(), Remove(), and Resize().
NextIndex
template<typename InAllocator> ElementAllocatorType THashTable< InAllocator >::NextIndex private
Definition at line 506 of file HashTable.h.
Referenced by THashTable(), THashTable< FMemoryImageAllocator >::CopyUnfrozen(), MoveAssign(), and Resize().
The documentation for this class was generated from the following file:
HashTable.h