Unreal Engine 5.6 C++ API: FSkinWeightProfilesData Struct Reference
FSkinWeightProfilesData Struct Reference
Runtime structure for keeping track of skin weight profile(s) and the associated buffer.
#include "SkinWeightProfile.h"
Public Member Functions
~FSkinWeightProfilesData ()
FRuntimeSkinWeightProfileData & AddOverrideData (const FName &ProfileName)
void ClearDynamicDefaultSkinWeightProfile (USkeletalMesh *Mesh, int32 LODIndex)
bool ContainsOverrideBuffer (const FSkinWeightProfileStack &InProfileStack) const
bool ContainsProfile (const FName &ProfileName) const
void CreateRHIBuffers (FRHICommandListBase &RHICmdList, TArray< TPair< FSkinWeightProfileStack, FSkinWeightRHIInfo > > &OutBuffers)
DECLARE_DELEGATE_RetVal_ThreeParams (int32, FOnPickOverrideSkinWeightProfile, const USkeletalMesh *, const TArrayView< const FSkinWeightProfileInfo >, int32)
SIZE_T GetCPUAccessMemoryOverhead () const
FSkinWeightVertexBuffer * GetDefaultOverrideBuffer () const
FSkinWeightProfileStack GetDefaultProfileStack () const
FSkinWeightVertexBuffer * GetOverrideBuffer (const FSkinWeightProfileStack &InProfileStack) const
const FRuntimeSkinWeightProfileData * GetOverrideData (const FName &ProfileName) const
SIZE_T GetResourcesSize () const
void Init (FSkinWeightVertexBuffer *InBaseBuffer)
void InitRHIForStreaming (const TArray< TPair< FSkinWeightProfileStack, FSkinWeightRHIInfo > > &IntermediateBuffers, FRHIResourceReplaceBatcher &Batcher)
bool IsDefaultOverridden () const
bool IsStaticOverridden () const
void ReleaseCPUResources ()
void ReleaseResources ()
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void SerializeMetaData (FArchive &Ar)
void SetDynamicDefaultSkinWeightProfile (USkeletalMesh *Mesh, int32 LODIndex, bool bSerialization=false)
void SetupDynamicDefaultSkinWeightProfile ()
Static Public Attributes
static FOnPickOverrideSkinWeightProfile OnPickOverrideSkinWeightProfile
Private Member Functions
void ApplyOverrideProfileStack (const FSkinWeightProfileStack &InProfileStack, FSkinWeightVertexBuffer *OverrideBuffer, const uint8 *BaseBufferData=nullptr)
void EnqueueDataReadback ()
void EnqueueGPUReadback ()
bool HasProfileStack (const FSkinWeightProfileStack &InProfileStack) const
void InitialiseProfileBuffer (const FSkinWeightProfileStack &InProfileStack)
bool IsDataReadbackFinished () const
bool IsDataReadbackPending () const
bool IsGPUReadbackFinished () const
bool IsPendingReadback () const
void ReleaseBuffer (const FSkinWeightProfileStack &InProfileStack, bool bForceRelease=false)
void ResetGPUReadback ()
Private Attributes
FSkinWeightVertexBuffer * BaseBuffer = nullptr
bool bDefaultOverridden = false
bool bStaticOverridden = false
FSkinWeightVertexBuffer * DefaultOverrideSkinWeightBuffer = nullptr
FSkinWeightProfileStack DefaultProfileStack
TMap< FName, FRuntimeSkinWeightProfileData > OverrideData
TMap< FSkinWeightProfileStack, FSkinWeightVertexBuffer * > ProfileStackToBuffer
FSkinWeightReadbackData ReadbackData
Friends
class FSkinWeightProfileManager
class FSkinWeightProfileManagerAsyncTask
FArchive & operator<< (FArchive &Ar, FSkinWeightProfilesData &OverrideData)
Detailed Description
Runtime structure for keeping track of skin weight profile(s) and the associated buffer.
Definition at line 237 of file SkinWeightProfile.h.
Constructor & Destructor Documentation
~FSkinWeightProfilesData()
FSkinWeightProfilesData::~FSkinWeightProfilesData ()
Member Function Documentation
AddOverrideData()
FRuntimeSkinWeightProfileData & FSkinWeightProfilesData::AddOverrideData (const FName & ProfileName)
ApplyOverrideProfileStack()
void FSkinWeightProfilesData::ApplyOverrideProfileStack (const FSkinWeightProfileStack & InProfileStack, FSkinWeightVertexBuffer * OverrideBuffer, const uint8 * BaseBufferData = nullptr) private
ClearDynamicDefaultSkinWeightProfile()
void FSkinWeightProfilesData::ClearDynamicDefaultSkinWeightProfile (USkeletalMesh * Mesh, int32 LODIndex)
References Mesh.
ContainsOverrideBuffer()
bool FSkinWeightProfilesData::ContainsOverrideBuffer (const FSkinWeightProfileStack & InProfileStack) const
ContainsProfile()
bool FSkinWeightProfilesData::ContainsProfile (const FName & ProfileName) const
CreateRHIBuffers()
void FSkinWeightProfilesData::CreateRHIBuffers (FRHICommandListBase & RHICmdList, TArray< TPair< FSkinWeightProfileStack, FSkinWeightRHIInfo > > & OutBuffers)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
DECLARE_DELEGATE_RetVal_ThreeParams()
FSkinWeightProfilesData::DECLARE_DELEGATE_RetVal_ThreeParams (int32 , FOnPickOverrideSkinWeightProfile , const USkeletalMesh * , const TArrayView< const FSkinWeightProfileInfo > , int32)
EnqueueDataReadback()
void FSkinWeightProfilesData::EnqueueDataReadback () private
EnqueueGPUReadback()
void FSkinWeightProfilesData::EnqueueGPUReadback () private
GetCPUAccessMemoryOverhead()
SIZE_T FSkinWeightProfilesData::GetCPUAccessMemoryOverhead () const
GetDefaultOverrideBuffer()
FSkinWeightVertexBuffer * FSkinWeightProfilesData::GetDefaultOverrideBuffer () const inline
Definition at line 253 of file SkinWeightProfile.h.
References DefaultOverrideSkinWeightBuffer.
GetDefaultProfileStack()
FSkinWeightProfileStack FSkinWeightProfilesData::GetDefaultProfileStack () const inline
Definition at line 282 of file SkinWeightProfile.h.
References DefaultProfileStack.
GetOverrideBuffer()
FSkinWeightVertexBuffer * FSkinWeightProfilesData::GetOverrideBuffer (const FSkinWeightProfileStack & InProfileStack) const
GetOverrideData()
const FRuntimeSkinWeightProfileData * FSkinWeightProfilesData::GetOverrideData (const FName & ProfileName) const
GetResourcesSize()
SIZE_T FSkinWeightProfilesData::GetResourcesSize () const
HasProfileStack()
bool FSkinWeightProfilesData::HasProfileStack (const FSkinWeightProfileStack & InProfileStack) const private
Init()
void FSkinWeightProfilesData::Init (FSkinWeightVertexBuffer * InBaseBuffer)
InitialiseProfileBuffer()
void FSkinWeightProfilesData::InitialiseProfileBuffer (const FSkinWeightProfileStack & InProfileStack) private
InitRHIForStreaming()
void FSkinWeightProfilesData::InitRHIForStreaming (const TArray< TPair< FSkinWeightProfileStack, FSkinWeightRHIInfo > > & IntermediateBuffers, FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
IsDataReadbackFinished()
bool FSkinWeightProfilesData::IsDataReadbackFinished () const private
IsDataReadbackPending()
bool FSkinWeightProfilesData::IsDataReadbackPending () const private
IsDefaultOverridden()
bool FSkinWeightProfilesData::IsDefaultOverridden () const inline
Definition at line 280 of file SkinWeightProfile.h.
References bDefaultOverridden.
IsGPUReadbackFinished()
bool FSkinWeightProfilesData::IsGPUReadbackFinished () const private
IsPendingReadback()
bool FSkinWeightProfilesData::IsPendingReadback () const private
IsStaticOverridden()
bool FSkinWeightProfilesData::IsStaticOverridden () const inline
Definition at line 281 of file SkinWeightProfile.h.
References bStaticOverridden.
ReleaseBuffer()
void FSkinWeightProfilesData::ReleaseBuffer (const FSkinWeightProfileStack & InProfileStack, bool bForceRelease = false) private
ReleaseCPUResources()
void FSkinWeightProfilesData::ReleaseCPUResources ()
ReleaseResources()
void FSkinWeightProfilesData::ReleaseResources ()
ReleaseRHIForStreaming()
void FSkinWeightProfilesData::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
ResetGPUReadback()
void FSkinWeightProfilesData::ResetGPUReadback () private
SerializeMetaData()
void FSkinWeightProfilesData::SerializeMetaData (FArchive & Ar)
References Ar.
SetDynamicDefaultSkinWeightProfile()
void FSkinWeightProfilesData::SetDynamicDefaultSkinWeightProfile (USkeletalMesh * Mesh, int32 LODIndex, bool bSerialization = false)
References Mesh.
SetupDynamicDefaultSkinWeightProfile()
void FSkinWeightProfilesData::SetupDynamicDefaultSkinWeightProfile ()
Friends And Related Symbol Documentation
FSkinWeightProfileManager
friend class FSkinWeightProfileManager friend
Definition at line 285 of file SkinWeightProfile.h.
References FSkinWeightProfileManager.
Referenced by FSkinWeightProfileManager.
FSkinWeightProfileManagerAsyncTask
friend class FSkinWeightProfileManagerAsyncTask friend
Definition at line 286 of file SkinWeightProfile.h.
References FSkinWeightProfileManagerAsyncTask.
Referenced by FSkinWeightProfileManagerAsyncTask.
operator<<
FArchive & operator<< (FArchive & Ar, FSkinWeightProfilesData & OverrideData) friend
References Ar, and OverrideData.
Field Documentation
BaseBuffer
FSkinWeightVertexBuffer* FSkinWeightProfilesData::BaseBuffer = nullptr private
Definition at line 301 of file SkinWeightProfile.h.
bDefaultOverridden
bool FSkinWeightProfilesData::bDefaultOverridden = false private
Definition at line 308 of file SkinWeightProfile.h.
Referenced by IsDefaultOverridden().
bStaticOverridden
bool FSkinWeightProfilesData::bStaticOverridden = false private
Definition at line 309 of file SkinWeightProfile.h.
Referenced by IsStaticOverridden().
DefaultOverrideSkinWeightBuffer
FSkinWeightVertexBuffer* FSkinWeightProfilesData::DefaultOverrideSkinWeightBuffer = nullptr private
Definition at line 302 of file SkinWeightProfile.h.
Referenced by GetDefaultOverrideBuffer().
DefaultProfileStack
FSkinWeightProfileStack FSkinWeightProfilesData::DefaultProfileStack private
Definition at line 310 of file SkinWeightProfile.h.
Referenced by GetDefaultProfileStack().
OnPickOverrideSkinWeightProfile
FOnPickOverrideSkinWeightProfile FSkinWeightProfilesData::OnPickOverrideSkinWeightProfile static
Definition at line 244 of file SkinWeightProfile.h.
OverrideData
TMap<FName, FRuntimeSkinWeightProfileData> FSkinWeightProfilesData::OverrideData private
Definition at line 306 of file SkinWeightProfile.h.
Referenced by operator<<.
ProfileStackToBuffer
TMap<FSkinWeightProfileStack, FSkinWeightVertexBuffer*> FSkinWeightProfilesData::ProfileStackToBuffer private
Definition at line 304 of file SkinWeightProfile.h.
ReadbackData
FSkinWeightReadbackData FSkinWeightProfilesData::ReadbackData private
Definition at line 312 of file SkinWeightProfile.h.
The documentation for this struct was generated from the following file:
SkinWeightProfile.h