Unreal Engine 5.6 C++ API: SequencerKeyStructGenerator.h File Reference
SequencerKeyStructGenerator.h File Reference
#include "Channels/MovieSceneChannelData.h"
#include "Channels/MovieSceneChannelHandle.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Curves/KeyHandle.h"
#include "Misc/FrameNumber.h"
#include "MovieSceneKeyStruct.h"
#include "Templates/Casts.h"
#include "Templates/SharedPointer.h"
#include "UObject/Class.h"
#include "UObject/FieldPath.h"
#include "UObject/GCObject.h"
#include "UObject/NameTypes.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/StructOnScope.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/UnrealType.h"
#include "SequencerKeyStructGenerator.generated.h"
Data Structures
class FSequencerKeyStructGenerator
Struct type that is generated from an FMovieSceneChannel type to create a single edit interface for a key/value pair.
Functions
UMovieSceneKeyStructType * InstanceGeneratedStruct (void *Channel, FSequencerKeyStructGenerator *Generator)
Function overload used to create a new generated struct for the specified channel.
template<typename ChannelType>
void PostConstructKeyInstance (const TMovieSceneChannelHandle< ChannelType > &ChannelHandle, FKeyHandle InHandle, FStructOnScope *Struct)
Called to initialize a newly allocated key struct for editing.
Function Documentation
InstanceGeneratedStruct()
UMovieSceneKeyStructType * InstanceGeneratedStruct (void * Channel, FSequencerKeyStructGenerator * Generator) inline
Function overload used to create a new generated struct for the specified channel.
Overload the first parameter for specific channel types to create specific instancing logic (such as that required for object or enum properties): UMovieSceneKeyStructType* InstanceGeneratedStruct(ChannelType* Channel, FSequencerKeyStructGenerator* Generator)
Definition at line 189 of file SequencerKeyStructGenerator.h.
Referenced by FSequencerKeyStructGenerator::CreateKeyStructInstance().
PostConstructKeyInstance()
template<typename ChannelType> void PostConstructKeyInstance (const TMovieSceneChannelHandle< ChannelType > & ChannelHandle, FKeyHandle InHandle, FStructOnScope * Struct)
Called to initialize a newly allocated key struct for editing.
Empty by default, but can be overridden to perform any per-instance setup required for specific channel's key structs
Definition at line 199 of file SequencerKeyStructGenerator.h.
References CastChecked(), TMovieSceneChannelHandle< ChannelType >::Get(), INDEX_NONE, and Struct.
Referenced by FSequencerKeyStructGenerator::CreateKeyStructInstance().