Unreal Engine 5.6 C++ API: UE::Serialization::Private::FCompressionSettings Struct Reference
UE::Serialization::Private::FCompressionSettings Struct Reference
A wrapper around the oodle compression settings used by FEditorBulkData.
#include "EditorBulkData.h"
Public Member Functions
FCompressionSettings ()
FCompressionSettings (const FCompressedBuffer &Buffer)
ECompressedBufferCompressionLevel GetCompressionLevel ()
ECompressedBufferCompressor GetCompressor () const
bool IsCompressed () const
bool IsSet () const
bool operator!= (const FCompressionSettings &Other) const
bool operator== (const FCompressionSettings &Other) const
void Reset ()
void Set (ECompressedBufferCompressor InCompressor, ECompressedBufferCompressionLevel InCompressionLevel)
void SetToDefault ()
void SetToDisabled ()
Private Attributes
bool bIsSet
ECompressedBufferCompressionLevel CompressionLevel
ECompressedBufferCompressor Compressor
Detailed Description
A wrapper around the oodle compression settings used by FEditorBulkData.
Definition at line 44 of file EditorBulkData.h.
Constructor & Destructor Documentation
FCompressionSettings() [1/2]
UE::Serialization::Private::FCompressionSettings::FCompressionSettings ()
Referenced by operator!=(), and operator==().
FCompressionSettings() [2/2]
UE::Serialization::Private::FCompressionSettings::FCompressionSettings (const FCompressedBuffer & Buffer)
References Buffer.
Member Function Documentation
GetCompressionLevel()
ECompressedBufferCompressionLevel UE::Serialization::Private::FCompressionSettings::GetCompressionLevel () nodiscard
GetCompressor()
ECompressedBufferCompressor UE::Serialization::Private::FCompressionSettings::GetCompressor () const nodiscard
IsCompressed()
bool UE::Serialization::Private::FCompressionSettings::IsCompressed () const nodiscard
IsSet()
bool UE::Serialization::Private::FCompressionSettings::IsSet () const nodiscard
operator!=()
bool UE::Serialization::Private::FCompressionSettings::operator!= (const FCompressionSettings & Other) const nodiscard
References FCompressionSettings(), and Other.
operator==()
bool UE::Serialization::Private::FCompressionSettings::operator== (const FCompressionSettings & Other) const nodiscard
References FCompressionSettings(), and Other.
Reset()
void UE::Serialization::Private::FCompressionSettings::Reset ()
Set()
void UE::Serialization::Private::FCompressionSettings::Set (ECompressedBufferCompressor InCompressor, ECompressedBufferCompressionLevel InCompressionLevel)
SetToDefault()
void UE::Serialization::Private::FCompressionSettings::SetToDefault ()
SetToDisabled()
void UE::Serialization::Private::FCompressionSettings::SetToDisabled ()
Field Documentation
bIsSet
bool UE::Serialization::Private::FCompressionSettings::bIsSet private
Definition at line 69 of file EditorBulkData.h.
CompressionLevel
ECompressedBufferCompressionLevel UE::Serialization::Private::FCompressionSettings::CompressionLevel private
Definition at line 67 of file EditorBulkData.h.
Compressor
ECompressedBufferCompressor UE::Serialization::Private::FCompressionSettings::Compressor private
Definition at line 66 of file EditorBulkData.h.
The documentation for this struct was generated from the following file:
EditorBulkData.h