Unreal Engine 5.6 C++ API: UE::Sequencer::TOutlinerModelMixin< BaseType > Class Template Reference
UE::Sequencer::TOutlinerModelMixin< BaseType > Class Template Reference
#include "OutlinerItemModel.h"
Public Member Functions
template<typename... ArgTypes>
TOutlinerModelMixin (ArgTypes &&... InArgs)
TOutlinerModelMixin (const TOutlinerModelMixin< BaseType > &)=delete
TOutlinerModelMixin (TOutlinerModelMixin< BaseType > &&)=delete
virtual FViewModel * AsViewModel ()
virtual const FViewModel * AsViewModel () const
TOutlinerModelMixin< BaseType > operator= (const TOutlinerModelMixin< BaseType > &)=delete
TOutlinerModelMixin< BaseType > operator= (TOutlinerModelMixin< BaseType > &&)=delete
Public Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
FOutlinerItemModelMixin ()
virtual void BuildContextMenu (FMenuBuilder &MenuBuilder)
Get context menu contents.
virtual void BuildSidebarMenu (FMenuBuilder &MenuBuilder)
TSharedPtr< SWidget > CreateContextMenuWidget (const FCreateOutlinerContextMenuWidgetParams &InParams) override
Build the context menu widget for this outliner item.
virtual void CreateCurveModels (TArray< TUniquePtr< FCurveModel > > &OutCurveModels) override
Populate the specified array with curve models that are represented by this tree item.
virtual TSharedPtr< SWidget > GenerateCurveEditorTreeWidget (const FName &InColumnName, TWeakPtr< FCurveEditor > InCurveEditor, FCurveEditorTreeItemID InTreeItemID, const TSharedRef< ITableRow > &InTableRow) override
Generate the widget content for the specified column name of the curve editor tree view.
virtual TSharedPtr< ICurveEditorTreeItem > GetCurveEditorTreeItem () const override
Gets the curve editor item for this view-model.
TSharedPtr< FSequencerEditorViewModel > GetEditor () const
FName GetIdentifier () const override
Return the identifier of the owning model.
FSlateColor GetLabelColor () const override
Gets the color for the outliner item label.
virtual TOptional< FString > GetUniquePathName () const override
Get optional unique path name.
virtual bool HasCurves () const override
Whether this view-model has any curves and needs to have a curve editor item created.
bool IsDimmed () const override
bool IsExpanded () const override
Gets whether this outliner item is expanded.
bool IsFilteredOut () const override
Gets whether this outliner item has been filtered out.
bool IsPinned () const override
Returns whether this item is pinned, or is in a pinned branch.
virtual bool PassesFilter (const FCurveEditorTreeFilter *InFilter) const override
Check whether this tree item passes the specified filter.
void SetExpansion (bool bInIsExpanded) override
Sets the expansion state of this outliner item.
Public Member Functions inherited from UE::Sequencer::FOutlinerExtensionShim
virtual EOutlinerSelectionState GetSelectionState () const override
Gets the outliner item's selection state.
virtual void SetFilteredOut (bool bInIsFilteredOut) override
Sets whether this outliner item is being filtered out.
virtual void SetSelectionState (EOutlinerSelectionState InState) override
Sets the outliner item's selection state.
virtual bool ShouldAnchorToTop () const override
Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
virtual TSharedRef< SWidget > CreateOutlinerView (const FCreateOutlinerViewParams &InParams)
(deprecated) Create the outliner view for the label column
virtual TSharedPtr< SWidget > CreateOutlinerViewForColumn (const FCreateOutlinerViewParams &InParams, const FName &InColumnName)
Create the visual outliner widget for the specified column.
virtual const FSlateBrush * GetIconBrush () const
Gets the icon for the outliner item.
virtual const FSlateBrush * GetIconOverlayBrush () const
Gets the overlay icon for the outliner item.
virtual FSlateColor GetIconTint () const
Gets the icon tint color for the outliner item.
virtual FText GetIconToolTipText () const
Gets the tooltip text for the outliner item icon.
virtual FText GetLabel () const
Gets the label for the outliner item.
virtual FSlateFontInfo GetLabelFont () const
Gets the font for the outliner item.
virtual FText GetLabelToolTipText () const
Gets the tooltip text for the outliner item.
virtual FOutlinerSizing GetOutlinerSizing () const =0
Return the desired size for the owning model.
virtual bool HasBackground () const
Gets whether the outliner item has a background.
virtual void ToggleSelectionState (EOutlinerSelectionState InState, bool bInValue)
Toggles a bit in the outliner item's selection state.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IOutlinerExtension) virtual ~IOutlinerExtension()
Public Member Functions inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry GetVirtualGeometry () const override
void ReportVirtualGeometry (const FVirtualGeometry &InVirtualGeometry) override
Public Member Functions inherited from UE::Sequencer::IGeometryExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGeometryExtension) virtual ~IGeometryExtension()
Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
virtual void ReportPinnedParent (bool bInIsInPinnedBranch) override
Lets parent items report to their children that they are in a pinned branch.
virtual void SetPinned (bool bInIsPinned) override
Sets whether this item is pinned.
Public Member Functions inherited from UE::Sequencer::IPinnableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IPinnableExtension) virtual ~IPinnableExtension()
Public Member Functions inherited from UE::Sequencer::FHoveredExtensionShim
virtual bool IsHovered () const
virtual void OnHovered ()
virtual void OnUnhovered ()
Public Member Functions inherited from UE::Sequencer::IHoveredExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IHoveredExtension) virtual ~IHoveredExtension()
Public Member Functions inherited from UE::Sequencer::IDimmableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDimmableExtension) virtual ~IDimmableExtension()
Public Member Functions inherited from UE::Sequencer::FCurveEditorTreeItemExtensionShim
FCurveEditorTreeItemID GetCurveEditorItemID () const override
Gets the curve editor ID for this view-model.
void OnAddedToCurveEditor (FCurveEditorTreeItemID ItemID, TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model has a curve editor item created for it.
void OnRemovedFromCurveEditor (TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model's curve editor item is removed.
Public Member Functions inherited from UE::Sequencer::ICurveEditorTreeItemExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ICurveEditorTreeItemExtension) virtual ~ICurveEditorTreeItemExtension()
Public Member Functions inherited from ICurveEditorTreeItem
virtual ~ICurveEditorTreeItem ()
Additional Inherited Members
Public Types inherited from UE::Sequencer::FOutlinerItemModelMixin
using Implements = TImplements<IOutlinerExtension, IGeometryExtension, IPinnableExtension, IHoveredExtension, IDimmableExtension, ICurveEditorTreeItemExtension>
Static Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
static FString GetPathName (const FViewModel &Item)
Utility method to get the full path name of the given model.
static void GetPathName (const FViewModel &Item, FStringBuilderBase &OutString)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TWeakPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
Static Public Member Functions inherited from UE::Sequencer::IGeometryExtension
static float UpdateVirtualGeometry (float InitialVirtualPosition, TSharedPtr< FViewModel > InInitialItem)
Static Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
static void UpdateCachedPinnedState (TSharedPtr< FViewModel > RootModel)
Looks for any direct child of RootModel that is pinnable, and reports all their descendants that they are in a pinned branch, to make that lookup faster.
Static Public Attributes inherited from ICurveEditorTreeItem
static const FColumnNames ColumnNames
Protected Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
virtual void BuildDisplayOptionsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildOrganizeContextMenu (FMenuBuilder &MenuBuilder)
virtual void BuildSectionColorTintsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildTrackOptionsMenu (FMenuBuilder &MenuBuilder, const TArray< UMovieSceneTrack * > &InTracks)
virtual void BuildTrackRowOptionsMenu (FMenuBuilder &MenuBuilder)
virtual bool GetDefaultExpansionState () const
Get the default expansion state if it wasn't saved in the movie-scene data.
void SetExpansionWithoutSaving (bool bInIsExpanded)
Set expansion state without saving it in the movie-scene data.
void SetIdentifier (FName InNewIdentifier)
Set identifier for computing node paths.
Protected Attributes inherited from UE::Sequencer::FOutlinerItemModelMixin
FViewModelListHead OutlinerChildList
Protected Attributes inherited from UE::Sequencer::FOutlinerExtensionShim
bool bIsExpanded = false
bool bIsFilteredOut = false
EOutlinerSelectionState SelectionState = EOutlinerSelectionState::None
Protected Attributes inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry VirtualGeometry
Protected Attributes inherited from UE::Sequencer::FHoveredExtensionShim
bool bIsHovered = false
Detailed Description
template<typename BaseType>
class UE::Sequencer::TOutlinerModelMixin< BaseType >
Definition at line 136 of file OutlinerItemModel.h.
Constructor & Destructor Documentation
TOutlinerModelMixin() [1/3]
template<typename BaseType> template<typename... ArgTypes> UE::Sequencer::TOutlinerModelMixin< BaseType >::TOutlinerModelMixin (ArgTypes &&... InArgs) inline
Definition at line 141 of file OutlinerItemModel.h.
References Forward().
Referenced by TOutlinerModelMixin(), TOutlinerModelMixin(), operator=(), and operator=().
TOutlinerModelMixin() [2/3]
template<typename BaseType> UE::Sequencer::TOutlinerModelMixin< BaseType >::TOutlinerModelMixin (const TOutlinerModelMixin< BaseType > &) delete
References TOutlinerModelMixin().
TOutlinerModelMixin() [3/3]
template<typename BaseType> UE::Sequencer::TOutlinerModelMixin< BaseType >::TOutlinerModelMixin (TOutlinerModelMixin< BaseType > &&) delete
References TOutlinerModelMixin().
Member Function Documentation
AsViewModel() [1/2]
template<typename BaseType> virtual FViewModel * UE::Sequencer::TOutlinerModelMixin< BaseType >::AsViewModel () inline virtual
Implements UE::Sequencer::FOutlinerItemModelMixin.
Definition at line 153 of file OutlinerItemModel.h.
AsViewModel() [2/2]
template<typename BaseType> virtual const FViewModel * UE::Sequencer::TOutlinerModelMixin< BaseType >::AsViewModel () const inline virtual
Implements UE::Sequencer::FOutlinerItemModelMixin.
Definition at line 154 of file OutlinerItemModel.h.
operator=() [1/2]
template<typename BaseType> TOutlinerModelMixin< BaseType > UE::Sequencer::TOutlinerModelMixin< BaseType >::operator= (const TOutlinerModelMixin< BaseType > &) delete
References TOutlinerModelMixin().
operator=() [2/2]
template<typename BaseType> TOutlinerModelMixin< BaseType > UE::Sequencer::TOutlinerModelMixin< BaseType >::operator= (TOutlinerModelMixin< BaseType > &&) delete
References TOutlinerModelMixin().
The documentation for this class was generated from the following file:
OutlinerItemModel.h