Unreal Engine 5.6 C++ API: FLatentResponse Struct Reference
FLatentResponse Struct Reference
#include "LatentActions.h"
Data Structures
struct FExecutionInfo
Public Member Functions
FLatentResponse (float InDeltaTime)
FLatentResponse & DoneIf (bool Condition)
float ElapsedTime () const
FLatentResponse & FinishAndTriggerIf (bool Condition, FName ExecutionFunction, int32 LinkID, FWeakObjectPtr InCallbackTarget)
FLatentResponse & TriggerLink (FName ExecutionFunction, int32 LinkID, FWeakObjectPtr InCallbackTarget)
Protected Attributes
bool bRemoveAction
float DeltaTime
TArray< FExecutionInfo, TInlineAllocator< 4 > > LinksToExecute
Friends
struct FLatentActionManager
Detailed Description
Definition at line 9 of file LatentActions.h.
Constructor & Destructor Documentation
FLatentResponse()
FLatentResponse::FLatentResponse (float InDeltaTime) inline
Definition at line 40 of file LatentActions.h.
References bRemoveAction, and DeltaTime.
Referenced by DoneIf(), FinishAndTriggerIf(), and TriggerLink().
Member Function Documentation
DoneIf()
FLatentResponse & FLatentResponse::DoneIf (bool Condition) inline
Definition at line 46 of file LatentActions.h.
References FLatentResponse(), and bRemoveAction.
ElapsedTime()
float FLatentResponse::ElapsedTime () const inline
Definition at line 68 of file LatentActions.h.
References DeltaTime.
FinishAndTriggerIf()
FLatentResponse & FLatentResponse::FinishAndTriggerIf (bool Condition, FName ExecutionFunction, int32 LinkID, FWeakObjectPtr InCallbackTarget) inline
Definition at line 58 of file LatentActions.h.
References FLatentResponse(), bRemoveAction, and LinksToExecute.
TriggerLink()
FLatentResponse & FLatentResponse::TriggerLink (FName ExecutionFunction, int32 LinkID, FWeakObjectPtr InCallbackTarget) inline
Definition at line 52 of file LatentActions.h.
References FLatentResponse(), and LinksToExecute.
Friends And Related Symbol Documentation
FLatentActionManager
friend struct FLatentActionManager friend
Definition at line 38 of file LatentActions.h.
References FLatentActionManager.
Referenced by FLatentActionManager.
Field Documentation
bRemoveAction
bool FLatentResponse::bRemoveAction protected
Definition at line 35 of file LatentActions.h.
Referenced by FLatentResponse(), DoneIf(), and FinishAndTriggerIf().
DeltaTime
float FLatentResponse::DeltaTime protected
Definition at line 36 of file LatentActions.h.
Referenced by FLatentResponse(), and ElapsedTime().
LinksToExecute
TArray< FExecutionInfo, TInlineAllocator<4> > FLatentResponse::LinksToExecute protected
Definition at line 34 of file LatentActions.h.
Referenced by FinishAndTriggerIf(), and TriggerLink().
The documentation for this struct was generated from the following file:
LatentActions.h