Unreal Engine 5.6 C++ API: IConsoleManager Struct Reference
IConsoleManager Struct Reference abstract
handles console commands and variables, registered console variables are released on destruction
#include "IConsoleManager.h"
Public Member Functions
virtual void AddConsoleHistoryEntry (const TCHAR *Key, const TCHAR *Input)=0
virtual void BatchUpdateTag (FName Tag, const TMap< FName, FString > &CVarsAndValues)=0
Add, replace, or remove cvars to match the passed in cvars.
virtual void CallAllConsoleVariableSinks ()=0
The sinks are only called if a change has been done since the last time Should be called in very few points:
virtual IConsoleObject * FindConsoleObject (const TCHAR *Name, bool bTrackFrequentCalls=true) const =0
Find a console variable or command.
virtual FString FindConsoleObjectName (const IConsoleObject *Obj) const =0
Lookup the name of a console object by its pointer.
virtual IConsoleVariable * FindConsoleVariable (const TCHAR *Name, bool bTrackFrequentCalls=true) const =0
Find a console variable.
TConsoleVariableData< bool > * FindTConsoleVariableDataBool (const TCHAR *Name) const
Find a typed console variable (faster access to the value, no virtual function call)
TConsoleVariableData< float > * FindTConsoleVariableDataFloat (const TCHAR *Name) const
Find a typed console variable (faster access to the value, no virtual function call)
TConsoleVariableData< int32 > * FindTConsoleVariableDataInt (const TCHAR *Name) const
Find a typed console variable (faster access to the value, no virtual function call)
virtual void ForEachConsoleObjectThatContains (const FConsoleObjectVisitor &Visitor, const TCHAR *ThatContains) const =0
Not case sensitive, does not guarantee that UnregisterConsoleObject() will work in the loop.
virtual void ForEachConsoleObjectThatStartsWith (const FConsoleObjectVisitor &Visitor, const TCHAR *ThatStartsWith=TEXT("")) const =0
Iterate in O(n), not case sensitive, does not guarantee that UnregisterConsoleObject() will work in the loop.
virtual void GetConsoleHistory (const TCHAR *Key, TArray< FString > &Out)=0
virtual bool IsNameRegistered (const TCHAR *Name) const =0
Check if a name (command or variable) has been registered with the console manager.
virtual FConsoleObjectWithNameMulticastDelegate & OnConsoleObjectUnregistered ()=0
virtual FConsoleVariableMulticastDelegate & OnCVarUnregistered ()=0
virtual bool ProcessUserConsoleInput (const TCHAR *Input, FOutputDevice &Ar, UWorld *InWorld)=0
Process user input e.g.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes no arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithArgsAndOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithArgsDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithWorldAndArgsDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithWorldArgsAndOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithWorldDelegate &Command, uint32 Flags=ECVF_Default)=0
Register a console command that takes arguments.
virtual IConsoleCommand * RegisterConsoleCommand (const TCHAR *Name, const TCHAR *Help, uint32 Flags=(uint32) ECVF_Default)=0
Register a console command that is handles by an Exec functions (for auto completion)
virtual IConsoleVariable * RegisterConsoleVariable (const TCHAR *Name, bool DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a bool console variable.
virtual IConsoleVariable * RegisterConsoleVariable (const TCHAR *Name, const FString &DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a string console variable.
virtual IConsoleVariable * RegisterConsoleVariable (const TCHAR *Name, const TCHAR *DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a string console variable.
virtual IConsoleVariable * RegisterConsoleVariable (const TCHAR *Name, float DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a float console variable.
virtual IConsoleVariable * RegisterConsoleVariable (const TCHAR *Name, int32 DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a int console variable.
virtual IConsoleVariable * RegisterConsoleVariableBitRef (const TCHAR *CVarName, const TCHAR *FlagName, uint32 BitNumber, uint8 *Force0MaskPtr, uint8 *Force1MaskPtr, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a show flag variable.
virtual IConsoleVariable * RegisterConsoleVariableRef (const TCHAR *Name, bool &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a bool console variable.
virtual IConsoleVariable * RegisterConsoleVariableRef (const TCHAR *Name, float &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a float console variable.
virtual IConsoleVariable * RegisterConsoleVariableRef (const TCHAR *Name, FName &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a name console variable.
virtual IConsoleVariable * RegisterConsoleVariableRef (const TCHAR *Name, FString &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a string console variable.
virtual IConsoleVariable * RegisterConsoleVariableRef (const TCHAR *Name, int32 &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)=0
Create a reference to a int console variable.
virtual FConsoleVariableSinkHandle RegisterConsoleVariableSink_Handle (const FConsoleCommandDelegate &Command)=0
The registered command is executed at few defined points (see CallAllConsoleVariableSinks)
virtual void RegisterThreadPropagation (uint32 ThreadId=0, IConsoleThreadPropagation *InCallback=0)=0
virtual void UnregisterConsoleObject (const TCHAR *Name, bool bKeepState=true)=0
Unregisters a console variable or command by name, if an object of that name was registered.
virtual void UnregisterConsoleObject (IConsoleObject *ConsoleObject, bool bKeepState=true)=0
Unregisters a console object, if that object was registered.
virtual void UnregisterConsoleVariableSink_Handle (FConsoleVariableSinkHandle Handle)=0
The registered command is executed at few defined points (see CallAllConsoleVariableSinks)
virtual void UnsetAllConsoleVariablesWithTag (FName Tag, EConsoleVariableFlags Priority=ECVF_SetByMask)=0
When a plugin is unmounted, it needs to unset cvars that it had set when it was mounted.
Static Public Member Functions
static FORCEINLINE IConsoleManager & Get ()
Returns the singleton for the console manager.
Protected Member Functions
virtual ~IConsoleManager ()
Static Private Member Functions
static void SetupSingleton ()
Function to create the singleton.
Static Private Attributes
static IConsoleManager * Singleton
Singleton for the console manager.
Detailed Description
handles console commands and variables, registered console variables are released on destruction
Definition at line 880 of file IConsoleManager.h.
Constructor & Destructor Documentation
~IConsoleManager()
virtual IConsoleManager::~IConsoleManager () inline protected virtual
Definition at line 1254 of file IConsoleManager.h.
Member Function Documentation
AddConsoleHistoryEntry()
virtual void IConsoleManager::AddConsoleHistoryEntry (const TCHAR * Key, const TCHAR * Input) pure virtual
Parameters
Input - must not be 0
References Input, and Key.
BatchUpdateTag()
virtual void IConsoleManager::BatchUpdateTag (FName Tag, const TMap< FName, FString > & CVarsAndValues) pure virtual
Add, replace, or remove cvars to match the passed in cvars.
CallAllConsoleVariableSinks()
virtual void IConsoleManager::CallAllConsoleVariableSinks () pure virtual
The sinks are only called if a change has been done since the last time Should be called in very few points:
after ini file loading
after user console input
user initiated a console variable change (it needs to be clear to user that a cvar can change e.g. game options menu)
beginning of Tick (to catch stray Set() calls, which are usually bad)
FindConsoleObject()
virtual IConsoleObject * IConsoleManager::FindConsoleObject (const TCHAR * Name, bool bTrackFrequentCalls = true) const pure virtual
Find a console variable or command.
Parameters
Name must not be 0
Returns
0 if the object wasn't found
References Name.
FindConsoleObjectName()
virtual FString IConsoleManager::FindConsoleObjectName (const IConsoleObject * Obj) const pure virtual
Lookup the name of a console object by its pointer.
Parameters
Object to lookup. Must not be null.
Returns
Name of the object, or an empty string if the object can't be found
FindConsoleVariable()
virtual IConsoleVariable * IConsoleManager::FindConsoleVariable (const TCHAR * Name, bool bTrackFrequentCalls = true) const pure virtual
Find a console variable.
Parameters
Name must not be 0
Returns
0 if the object wasn't found
References Name.
Referenced by DEFINE_LOG_CATEGORY_STATIC(), FindConsoleVarHelper(), FindTConsoleVariableDataBool(), FindTConsoleVariableDataFloat(), FindTConsoleVariableDataInt(), FShaderPlatformCachedIniValue< Type >::Get(), and FSkeletalMeshStreamIn_IO::SetIORequest().
FindTConsoleVariableDataBool()
TConsoleVariableData< bool > * IConsoleManager::FindTConsoleVariableDataBool (const TCHAR * Name) const inline
Find a typed console variable (faster access to the value, no virtual function call)
Parameters
Name must not be 0
Returns
0 if the object wasn't found
Definition at line 1111 of file IConsoleManager.h.
References IConsoleObject::AsVariableBool(), FindConsoleVariable(), and Name.
FindTConsoleVariableDataFloat()
TConsoleVariableData< float > * IConsoleManager::FindTConsoleVariableDataFloat (const TCHAR * Name) const inline
Find a typed console variable (faster access to the value, no virtual function call)
Parameters
Name must not be 0
Returns
0 if the object wasn't found
Definition at line 1135 of file IConsoleManager.h.
References IConsoleObject::AsVariableFloat(), FindConsoleVariable(), and Name.
FindTConsoleVariableDataInt()
TConsoleVariableData< int32 > * IConsoleManager::FindTConsoleVariableDataInt (const TCHAR * Name) const inline
Find a typed console variable (faster access to the value, no virtual function call)
Parameters
Name must not be 0
Returns
0 if the object wasn't found
Definition at line 1123 of file IConsoleManager.h.
References IConsoleObject::AsVariableInt(), FindConsoleVariable(), and Name.
Referenced by FMaterial::FMaterial(), Nanite::FNaniteResourcesHelper::AuditMaterials(), and FPrimitiveUniformShaderParametersBuilder::Build().
ForEachConsoleObjectThatContains()
virtual void IConsoleManager::ForEachConsoleObjectThatContains (const FConsoleObjectVisitor & Visitor, const TCHAR * ThatContains) const pure virtual
Not case sensitive, does not guarantee that UnregisterConsoleObject() will work in the loop.
Parameters
Visitor must not be 0
ThatContains must not be 0
ForEachConsoleObjectThatStartsWith()
virtual void IConsoleManager::ForEachConsoleObjectThatStartsWith (const FConsoleObjectVisitor & Visitor, const TCHAR * ThatStartsWith = TEXT("")) const pure virtual
Iterate in O(n), not case sensitive, does not guarantee that UnregisterConsoleObject() will work in the loop.
Parameters
Visitor must not be 0
ThatStartsWith must not be 0
Get()
FORCEINLINE IConsoleManager & IConsoleManager::Get () inline static
Returns the singleton for the console manager.
Definition at line 1190 of file IConsoleManager.h.
References check, FORCEINLINE, SetupSingleton(), and Singleton.
Referenced by FAutoConsoleVariableSink::FAutoConsoleVariableSink(), FConditionalAutoConsoleRegister::FConditionalAutoConsoleRegister(), FConditionalAutoConsoleRegister::FConditionalAutoConsoleRegister(), FMaterial::FMaterial(), FAutoConsoleObject::~FAutoConsoleObject(), Nanite::FNaniteResourcesHelper::AuditMaterials(), FPrimitiveUniformShaderParametersBuilder::Build(), DEFINE_LOG_CATEGORY_STATIC(), FindConsoleVarHelper(), FShaderPlatformCachedIniValue< Type >::Get(), and FSkeletalMeshStreamIn_IO::SetIORequest().
GetConsoleHistory()
virtual void IConsoleManager::GetConsoleHistory (const TCHAR * Key, TArray< FString > & Out) pure virtual
References Key.
IsNameRegistered()
virtual bool IConsoleManager::IsNameRegistered (const TCHAR * Name) const pure virtual
Check if a name (command or variable) has been registered with the console manager.
Parameters
Name - Name to check. Must not be 0
References Name.
OnConsoleObjectUnregistered()
virtual FConsoleObjectWithNameMulticastDelegate & IConsoleManager::OnConsoleObjectUnregistered () pure virtual
OnCVarUnregistered()
virtual FConsoleVariableMulticastDelegate & IConsoleManager::OnCVarUnregistered () pure virtual
ProcessUserConsoleInput()
virtual bool IConsoleManager::ProcessUserConsoleInput (const TCHAR * Input, FOutputDevice & Ar, UWorld * InWorld) pure virtual
Process user input e.g.
"MyCVar" to get the current value of the console variable "MyCVar -5.2" to set the value to -5.2 "MyCVar ?" to get the help text
Parameters
Input must not be 0
Ar archive
InWorld world context
Returns
true if the command was recognized
References Ar, and Input.
RegisterConsoleCommand() [1/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes no arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [2/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithArgsAndOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [3/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithArgsDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [4/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [5/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithWorldAndArgsDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [6/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithWorldArgsAndOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [7/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithWorldDelegate & Command, uint32 Flags = ECVF_Default) pure virtual
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleCommand() [8/8]
virtual IConsoleCommand * IConsoleManager::RegisterConsoleCommand (const TCHAR * Name, const TCHAR * Help, uint32 Flags = (uint32) ECVF_Default) pure virtual
Register a console command that is handles by an Exec functions (for auto completion)
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Flags Optional flags bitmask
References ECVF_Default, Flags, and Name.
RegisterConsoleVariable() [1/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariable (const TCHAR * Name, bool DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
Referenced by FConditionalAutoConsoleRegister::FConditionalAutoConsoleRegister(), FConditionalAutoConsoleRegister::FConditionalAutoConsoleRegister(), and FShaderPlatformCachedIniValue< Type >::Get().
RegisterConsoleVariable() [2/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariable (const TCHAR * Name, const FString & DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a string console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariable() [3/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariable (const TCHAR * Name, const TCHAR * DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a string console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariable() [4/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariable (const TCHAR * Name, float DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a float console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariable() [5/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariable (const TCHAR * Name, int32 DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a int console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableBitRef()
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableBitRef (const TCHAR * CVarName, const TCHAR * FlagName, uint32 BitNumber, uint8 * Force0MaskPtr, uint8 * Force1MaskPtr, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a show flag variable.
Parameters
CVarName must not be 0, e.g. "Show.PostProcessing"
FlagName must not be 0, e.g. "PostProcessing"
BitNumber in the memory defined by Force0MaskPtr and Force1MaskPtr
Force0MaskPtr memory that contains the bits that should be forced to 0
Force1MaskPtr memory that contains the bits that should be forced to 1
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, and Flags.
RegisterConsoleVariableRef() [1/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableRef (const TCHAR * Name, bool & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableRef() [2/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableRef (const TCHAR * Name, float & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a float console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableRef() [3/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableRef (const TCHAR * Name, FName & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a name console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableRef() [4/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableRef (const TCHAR * Name, FString & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a string console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableRef() [5/5]
virtual IConsoleVariable * IConsoleManager::RegisterConsoleVariableRef (const TCHAR * Name, int32 & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) pure virtual
Create a reference to a int console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
References ECVF_Default, Flags, and Name.
RegisterConsoleVariableSink_Handle()
virtual FConsoleVariableSinkHandle IConsoleManager::RegisterConsoleVariableSink_Handle (const FConsoleCommandDelegate & Command) pure virtual
The registered command is executed at few defined points (see CallAllConsoleVariableSinks)
Parameters
Command
Referenced by FAutoConsoleVariableSink::FAutoConsoleVariableSink().
RegisterThreadPropagation()
virtual void IConsoleManager::RegisterThreadPropagation (uint32 ThreadId = 0, IConsoleThreadPropagation * InCallback = 0) pure virtual
SetupSingleton()
void IConsoleManager::SetupSingleton () static private
Function to create the singleton.
Referenced by Get().
UnregisterConsoleObject() [1/2]
virtual void IConsoleManager::UnregisterConsoleObject (const TCHAR * Name, bool bKeepState = true) pure virtual
Unregisters a console variable or command by name, if an object of that name was registered.
Parameters
Name - name of object to remove
bKeepState if the current state is kept in memory until a cvar with the same name is registered
References Name.
UnregisterConsoleObject() [2/2]
virtual void IConsoleManager::UnregisterConsoleObject (IConsoleObject * ConsoleObject, bool bKeepState = true) pure virtual
Unregisters a console object, if that object was registered.
O(n), n is the console object count
Parameters
ConsoleObject - object to remove
bKeepState if the current state is kept in memory until a cvar with the same name is registered
Referenced by FAutoConsoleObject::~FAutoConsoleObject().
UnregisterConsoleVariableSink_Handle()
virtual void IConsoleManager::UnregisterConsoleVariableSink_Handle (FConsoleVariableSinkHandle Handle) pure virtual
The registered command is executed at few defined points (see CallAllConsoleVariableSinks)
Parameters
Command
References Handle.
UnsetAllConsoleVariablesWithTag()
virtual void IConsoleManager::UnsetAllConsoleVariablesWithTag (FName Tag, EConsoleVariableFlags Priority = ECVF_SetByMask) pure virtual
When a plugin is unmounted, it needs to unset cvars that it had set when it was mounted.
This will unset and fixup all variables with the given Tag
Parameters
Priority If set, then the internal search for CVars is restricted to this SetBy. This is an optimization, only to be used if you know that all CVars set with this tag were set at this priority. Any other priorites cannot be unset
References ECVF_SetByMask.
Field Documentation
Singleton
IConsoleManager* IConsoleManager::Singleton static private
Singleton for the console manager.
Definition at line 1258 of file IConsoleManager.h.
Referenced by Get().
The documentation for this struct was generated from the following file:
IConsoleManager.h