Unreal Engine 5.6 C++ API: UE::MovieScene::FPreAnimatedStateExtension Struct Reference
UE::MovieScene::FPreAnimatedStateExtension Struct Reference
Pre-animated state extension that houses all cached values for objects animated by a specific UMovieSceneEntitySystemLinker.
#include "MovieScenePreAnimatedStateExtension.h"
Data Structures
struct FAggregatePreAnimatedStateMetaData
struct FPreAnimatedGroupMetaData
Public Member Functions
MOVIESCENE_API FPreAnimatedStateExtension ()
MOVIESCENE_API ~FPreAnimatedStateExtension ()
MOVIESCENE_API void AddMetaData (const FPreAnimatedStateMetaData &MetaData)
MOVIESCENE_API void AddSourceMetaData (const FPreAnimatedStateEntry &Entry)
template<typename StorageType>
void AddStorage (TPreAnimatedStorageID< StorageType > InStorageID, TSharedPtr< StorageType > InStorage)
Add a specific storage type to this extension.
MOVIESCENE_API void AddWeakCaptureSource (TWeakPtr< IPreAnimatedCaptureSource > InWeakMetaData)
MOVIESCENE_API FPreAnimatedStorageGroupHandle AllocateGroup (TSharedPtr< IPreAnimatedStateGroupManager > GroupManager)
Called by group managers to allocate a new group.
bool AreEntriesInvalidated () const
Check whether any previously cached entries may have become invalid due to a recent call to RestoreGlobalState If this function returns true, clients should consider re-saving pre-animated state even if it already did so.
MOVIESCENE_API bool ContainsAnyStateForInstanceHandle (FRootInstanceHandle RootInstanceHandle) const
Search for any captured state that originated from the specified root instance handle WARNING: This is a linear search across all state, and so is potentially very slow.
MOVIESCENE_API void DiscardGlobalState (const FRestoreStateParams &Params)
Discards any state for any persistent tokens captured during the course of evaluation without restoring it.
void DiscardStaleObjectState ()
Called during Garbage Collection to clean up preanimated state on invalid bound objects.
MOVIESCENE_API void DiscardStateForGroup (FPreAnimatedStorageGroupHandle GroupHandle)
Discard any and all cached values for the specified group without restoring them.
MOVIESCENE_API void DiscardStateForStorage (FPreAnimatedStorageID StorageID, FPreAnimatedStorageIndex StorageIndex)
Discard the specified cached value and any and all capture source tracking related to it.
MOVIESCENE_API void DiscardTransientState ()
Discard any transient state and all meta-data for any currently animating objects, whilst preserving the cached values internally.
MOVIESCENE_API void EnsureMetaData (const FPreAnimatedStateEntry &Entry)
template<typename GroupManagerType>
TSharedPtr< GroupManagerType > FindGroupManager () const
Find a group manager by its type.
template<typename StorageType>
TSharedPtr< StorageType > FindStorage (TPreAnimatedStorageID< StorageType > InStorageID) const
Find a specific storage type by its ID.
MOVIESCENE_API void FreeGroup (FPreAnimatedStorageGroupHandle Index)
Called by group managers to free an existing group.
MOVIESCENE_API FPreAnimatedEntityCaptureSource * GetEntityMetaData () const
MOVIESCENE_API FPreAnimatedEvaluationHookCaptureSources * GetEvaluationHookMetaData () const
MOVIESCENE_API FPreAnimatedEntityCaptureSource * GetOrCreateEntityMetaData ()
MOVIESCENE_API FPreAnimatedEvaluationHookCaptureSources * GetOrCreateEvaluationHookMetaData ()
template<typename GroupManagerType>
TSharedPtr< GroupManagerType > GetOrCreateGroupManager ()
Get or create a group manager by its type.
template<typename StorageType>
TSharedPtr< StorageType > GetOrCreateStorage ()
Get a specific type of storage, creating it if it does not already exist.
template<typename StorageType>
TSharedPtr< StorageType > GetOrCreateStorage (TPreAnimatedStorageID< StorageType > InStorageID)
Get a specific type of storage, creating it if it does not already exist.
MOVIESCENE_API FPreAnimatedTemplateCaptureSources * GetOrCreateTemplateMetaData ()
MOVIESCENE_API FPreAnimatedTrackInstanceInputCaptureSources * GetOrCreateTrackInstanceInputMetaData ()
MOVIESCENE_API FPreAnimatedTrackInstanceCaptureSources * GetOrCreateTrackInstanceMetaData ()
TSharedPtr< IPreAnimatedStorage > GetStorageChecked (FPreAnimatedStorageID InStorageID) const
Get a genericly typed storage entry by its erased ID, failing an assertion if it does not exist.
MOVIESCENE_API EPreAnimatedStorageRequirement GetStorageRequirement (const FPreAnimatedStateEntry &Entry) const
MOVIESCENE_API FPreAnimatedTemplateCaptureSources * GetTemplateMetaData () const
MOVIESCENE_API FPreAnimatedTrackInstanceInputCaptureSources * GetTrackInstanceInputMetaData () const
MOVIESCENE_API FPreAnimatedTrackInstanceCaptureSources * GetTrackInstanceMetaData () const
MOVIESCENE_API bool HasActiveCaptureSource () const
MOVIESCENE_API void Initialize (UMovieSceneEntitySystemLinker *InLinker)
bool IsCapturingGlobalState () const
Check if this extension has any current requests to capture global (persistent) state entries.
MOVIESCENE_API bool MetaDataExists (const FPreAnimatedStateEntry &Entry) const
void OnObjectsReplaced (const TMap< UObject *, UObject * > &ReplacementMap)
Called to handle replaced objects.
MOVIESCENE_API void RemoveMetaData (const FPreAnimatedStateMetaData &MetaData)
MOVIESCENE_API void RemoveWeakCaptureSource (TWeakPtr< IPreAnimatedCaptureSource > InWeakMetaData)
MOVIESCENE_API void ReplaceObjectForGroup (FPreAnimatedStorageGroupHandle GroupHandle, const FObjectKey &OldObject, const FObjectKey &NewObject)
Called during blueprint re-instancing to replace the object bound to a specific group handle with another.
void ResetEntryInvalidation ()
Resets the entry invalidation flag.
MOVIESCENE_API void RestoreGlobalState (const FRestoreStateParams &Params)
Restore any state for any persistent tokens captured during the course of evaluation.
MOVIESCENE_API void RestoreStateForGroup (FPreAnimatedStorageGroupHandle GroupHandle, const FRestoreStateParams &Params)
Restore any state cached for the specified group.
MOVIESCENE_API void SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &Producer)
MOVIESCENE_API void SavePreAnimatedState (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &Producer)
MOVIESCENE_API void SavePreAnimatedStateDirectly (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &Producer)
MOVIESCENE_API void SavePreAnimatedStateDirectly (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &Producer)
MOVIESCENE_API void UpdateMetaData (const FPreAnimatedStateMetaData &MetaData)
Static Public Member Functions
template<typename StorageType>
static TPreAnimatedStorageID< StorageType > RegisterStorage ()
Called from TAutoRegisterPreAnimatedStorageID to register a new application-wide storage type.
Data Fields
uint32 NumRequestsForGlobalState
The number of requests that have been made to capture global state - only one should exist per playing sequence.
Private Types
using FContributionRemover = TFunctionRef<void(IPreAnimatedStorage&, FPreAnimatedStorageIndex)>
Private Member Functions
MOVIESCENE_API void AddReferencedObjects (UMovieSceneEntitySystemLinker *, FReferenceCollector &ReferenceCollector)
MOVIESCENE_API FAggregatePreAnimatedStateMetaData * FindMetaData (const FPreAnimatedStateEntry &Entry)
MOVIESCENE_API const FAggregatePreAnimatedStateMetaData * FindMetaData (const FPreAnimatedStateEntry &Entry) const
MOVIESCENE_API void FreeGroupInternal (FPreAnimatedStorageGroupHandle Handle)
MOVIESCENE_API FAggregatePreAnimatedStateMetaData * GetOrAddMetaDataInternal (const FPreAnimatedStateEntry &Entry)
void HandleMetaDataToRemove (const FRestoreStateParams &Params, TArrayView< FPreAnimatedStateMetaData > MetaDataToRemove, FContributionRemover RemoveFunc)
Static Private Member Functions
static MOVIESCENE_API FPreAnimatedStorageID RegisterStorageInternal ()
Private Attributes
bool bEntriesInvalidated
TUniquePtr< FPreAnimatedEntityCaptureSource > EntityCaptureSource
Meta-data pertaining to the entity IDs from which animated state originates.
TUniquePtr< UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources > EvaluationHookCaptureSource
Meta-data ledger for any pre-animated state that originates from evaluation hooks.
TSortedMap< FPreAnimatedStorageID, TWeakPtr< IPreAnimatedStateGroupManager > > GroupManagers
TSparseArray< FPreAnimatedGroupMetaData > GroupMetaData
UMovieSceneEntitySystemLinker * Linker
Linker is always valid because this extension is owned by the Linker.
TSortedMap< FPreAnimatedStorageID, TSharedPtr< IPreAnimatedStorage > > StorageImplementations
TUniquePtr< UE::MovieScene::FPreAnimatedTemplateCaptureSources > TemplateCaptureSource
Meta-data ledger for any pre-animated state that originates from track templates.
TUniquePtr< FPreAnimatedTrackInstanceCaptureSources > TrackInstanceCaptureSource
Meta-data pertaining to pre-animated state originating from track instances.
TUniquePtr< FPreAnimatedTrackInstanceInputCaptureSources > TrackInstanceInputCaptureSource
Meta-data pertaining to pre-animated state originating from track instances from a specific input.
TMap< FPreAnimatedStateCachedValueHandle, FAggregatePreAnimatedStateMetaData > UngroupedMetaData
TArray< TWeakPtr< IPreAnimatedCaptureSource > > WeakExternalCaptureSources
Weakly held meta data provided by FMovieScenePreAnimatedState for various other origins.
TWeakPtr< FAnimTypePreAnimatedStateObjectStorage > WeakGenericObjectStorage
Pointers to the storage for state bound to objects, organized by FMovieSceneAnimTypeID.
TWeakPtr< FAnimTypePreAnimatedStateRootStorage > WeakGenericRootStorage
Pointers to the storage for state created from root tracks, or otherwise not bound to objects.
Friends
struct ::FScopedPreAnimatedCaptureSource
Detailed Description
Pre-animated state extension that houses all cached values for objects animated by a specific UMovieSceneEntitySystemLinker.
- The presence of this extension denotes that pre-animated state should be stored in one form or another.
     If the extension is not present, this implies that there are no IMovieScenePlayers that need global Restore State, and no tracks set to 'Restore State'.
     FPreAnimatedStateExtension::NumRequestsForGlobalState defines whether this extension needs to cache any and all changes or not
- Each specific 'type' of pre-animated state is defined by a unique StorageID (TPreAnimatedStorageID), registered through RegisterStorage
- Pre-animated state is grouped into buckets in order to preserve significant ordering constraints (for instance, each object must restore state in the reverse order it was cached)
- Groups are managed by registered IPreAnimatedStateGroupManager instances. The main implementation is FPreAnimatedObjectGroupManager, which maintains an object to group mapping
Definition at line 72 of file MovieScenePreAnimatedStateExtension.h.
Member Typedef Documentation
FContributionRemover
using UE::MovieScene::FPreAnimatedStateExtension::FContributionRemover = TFunctionRef<void(IPreAnimatedStorage&, FPreAnimatedStorageIndex)> private
Definition at line 339 of file MovieScenePreAnimatedStateExtension.h.
Constructor & Destructor Documentation
FPreAnimatedStateExtension()
MOVIESCENE_API UE::MovieScene::FPreAnimatedStateExtension::FPreAnimatedStateExtension ()
~FPreAnimatedStateExtension()
MOVIESCENE_API UE::MovieScene::FPreAnimatedStateExtension::~FPreAnimatedStateExtension ()
Member Function Documentation
AddMetaData()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::AddMetaData (const FPreAnimatedStateMetaData & MetaData)
References MetaData.
AddReferencedObjects()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::AddReferencedObjects (UMovieSceneEntitySystemLinker * , FReferenceCollector & ReferenceCollector) private
AddSourceMetaData()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::AddSourceMetaData (const FPreAnimatedStateEntry & Entry)
AddStorage()
template<typename StorageType> void UE::MovieScene::FPreAnimatedStateExtension::AddStorage (TPreAnimatedStorageID< StorageType > InStorageID, TSharedPtr< StorageType > InStorage) inline
Add a specific storage type to this extension.
Definition at line 111 of file MovieScenePreAnimatedStateExtension.h.
References check, and StorageImplementations.
Referenced by GetOrCreateStorage().
AddWeakCaptureSource()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::AddWeakCaptureSource (TWeakPtr< IPreAnimatedCaptureSource > InWeakMetaData)
AllocateGroup()
MOVIESCENE_API FPreAnimatedStorageGroupHandle UE::MovieScene::FPreAnimatedStateExtension::AllocateGroup (TSharedPtr< IPreAnimatedStateGroupManager > GroupManager)
Called by group managers to allocate a new group.
AreEntriesInvalidated()
bool UE::MovieScene::FPreAnimatedStateExtension::AreEntriesInvalidated () const inline
Check whether any previously cached entries may have become invalid due to a recent call to RestoreGlobalState If this function returns true, clients should consider re-saving pre-animated state even if it already did so.
Definition at line 214 of file MovieScenePreAnimatedStateExtension.h.
References bEntriesInvalidated.
ContainsAnyStateForInstanceHandle()
MOVIESCENE_API bool UE::MovieScene::FPreAnimatedStateExtension::ContainsAnyStateForInstanceHandle (FRootInstanceHandle RootInstanceHandle) const
Search for any captured state that originated from the specified root instance handle WARNING: This is a linear search across all state, and so is potentially very slow.
DiscardGlobalState()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::DiscardGlobalState (const FRestoreStateParams & Params)
Discards any state for any persistent tokens captured during the course of evaluation without restoring it.
Parameters
Params Parameters for restoration - if TerminalInstanceHandle is invalid then all state will be discarded, regardless of the instance it was cached from
References Params.
DiscardStaleObjectState()
void UE::MovieScene::FPreAnimatedStateExtension::DiscardStaleObjectState ()
Called during Garbage Collection to clean up preanimated state on invalid bound objects.
Does not restore state.
DiscardStateForGroup()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::DiscardStateForGroup (FPreAnimatedStorageGroupHandle GroupHandle)
Discard any and all cached values for the specified group without restoring them.
Note
This function should only be used to forcibly serialize animated values into a level
DiscardStateForStorage()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::DiscardStateForStorage (FPreAnimatedStorageID StorageID, FPreAnimatedStorageIndex StorageIndex)
Discard the specified cached value and any and all capture source tracking related to it.
DiscardTransientState()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::DiscardTransientState ()
Discard any transient state and all meta-data for any currently animating objects, whilst preserving the cached values internally.
Calling this function will cause any currently animating 'RestoreState' sections to re-cache their values if they are re-evaluated Any 'RestoreState' sections which are deleted or subsequently not-evaluated will not cause their values to be restored
EnsureMetaData()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::EnsureMetaData (const FPreAnimatedStateEntry & Entry)
FindGroupManager()
template<typename GroupManagerType> TSharedPtr< GroupManagerType > UE::MovieScene::FPreAnimatedStateExtension::FindGroupManager () const inline
Find a group manager by its type.
Group managers enable logical grouping of entries to ensure the correct restoration order.
Note
The templated type must implement a static GroupManagerID member of type TPreAnimatedStorageID<GroupManagerType>
Returns
A pointer to the group manager, or nullptr if it does not exist.
Definition at line 164 of file MovieScenePreAnimatedStateExtension.h.
References GroupManagers, and StaticCastSharedPtr().
FindMetaData() [1/2]
MOVIESCENE_API FAggregatePreAnimatedStateMetaData * UE::MovieScene::FPreAnimatedStateExtension::FindMetaData (const FPreAnimatedStateEntry & Entry) private
FindMetaData() [2/2]
MOVIESCENE_API const FAggregatePreAnimatedStateMetaData * UE::MovieScene::FPreAnimatedStateExtension::FindMetaData (const FPreAnimatedStateEntry & Entry) const private
FindStorage()
template<typename StorageType> TSharedPtr< StorageType > UE::MovieScene::FPreAnimatedStateExtension::FindStorage (TPreAnimatedStorageID< StorageType > InStorageID) const inline
Find a specific storage type by its ID.
Returns
The typed storage, or nullptr if it does not exist in this linker
Definition at line 100 of file MovieScenePreAnimatedStateExtension.h.
References StaticCastSharedPtr(), and StorageImplementations.
Referenced by GetOrCreateStorage().
FreeGroup()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::FreeGroup (FPreAnimatedStorageGroupHandle Index)
Called by group managers to free an existing group.
FreeGroupInternal()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::FreeGroupInternal (FPreAnimatedStorageGroupHandle Handle) private
References Handle.
GetEntityMetaData()
MOVIESCENE_API FPreAnimatedEntityCaptureSource * UE::MovieScene::FPreAnimatedStateExtension::GetEntityMetaData () const
GetEvaluationHookMetaData()
MOVIESCENE_API FPreAnimatedEvaluationHookCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetEvaluationHookMetaData () const
GetOrAddMetaDataInternal()
MOVIESCENE_API FAggregatePreAnimatedStateMetaData * UE::MovieScene::FPreAnimatedStateExtension::GetOrAddMetaDataInternal (const FPreAnimatedStateEntry & Entry) private
GetOrCreateEntityMetaData()
MOVIESCENE_API FPreAnimatedEntityCaptureSource * UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateEntityMetaData ()
GetOrCreateEvaluationHookMetaData()
MOVIESCENE_API FPreAnimatedEvaluationHookCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateEvaluationHookMetaData ()
GetOrCreateGroupManager()
template<typename GroupManagerType> TSharedPtr< GroupManagerType > UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateGroupManager () inline
Get or create a group manager by its type.
Group managers enable logical grouping of entries to ensure the correct restoration order.
Note
The templated type must implement a static GroupManagerID member of type TPreAnimatedStorageID<GroupManagerType>
Returns
A pointer to the group manager, or nullptr if it does not exist.
Definition at line 176 of file MovieScenePreAnimatedStateExtension.h.
References GroupManagers, MakeShared(), and StaticCastSharedPtr().
GetOrCreateStorage() [1/2]
template<typename StorageType> TSharedPtr< StorageType > UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateStorage () inline
Get a specific type of storage, creating it if it does not already exist.
Note
The template type must have a static StorageID of type TPreAnimatedStorageID<StorageType>.
Definition at line 123 of file MovieScenePreAnimatedStateExtension.h.
References GetOrCreateStorage().
Referenced by GetOrCreateStorage().
GetOrCreateStorage() [2/2]
template<typename StorageType> TSharedPtr< StorageType > UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateStorage (TPreAnimatedStorageID< StorageType > InStorageID) inline
Get a specific type of storage, creating it if it does not already exist.
Definition at line 133 of file MovieScenePreAnimatedStateExtension.h.
References AddStorage(), FindStorage(), and MakeShared().
GetOrCreateTemplateMetaData()
MOVIESCENE_API FPreAnimatedTemplateCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateTemplateMetaData ()
GetOrCreateTrackInstanceInputMetaData()
MOVIESCENE_API FPreAnimatedTrackInstanceInputCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateTrackInstanceInputMetaData ()
GetOrCreateTrackInstanceMetaData()
MOVIESCENE_API FPreAnimatedTrackInstanceCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateTrackInstanceMetaData ()
GetStorageChecked()
TSharedPtr< IPreAnimatedStorage > UE::MovieScene::FPreAnimatedStateExtension::GetStorageChecked (FPreAnimatedStorageID InStorageID) const inline
Get a genericly typed storage entry by its erased ID, failing an assertion if it does not exist.
Definition at line 150 of file MovieScenePreAnimatedStateExtension.h.
References StorageImplementations.
GetStorageRequirement()
MOVIESCENE_API EPreAnimatedStorageRequirement UE::MovieScene::FPreAnimatedStateExtension::GetStorageRequirement (const FPreAnimatedStateEntry & Entry) const
GetTemplateMetaData()
MOVIESCENE_API FPreAnimatedTemplateCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetTemplateMetaData () const
GetTrackInstanceInputMetaData()
MOVIESCENE_API FPreAnimatedTrackInstanceInputCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetTrackInstanceInputMetaData () const
GetTrackInstanceMetaData()
MOVIESCENE_API FPreAnimatedTrackInstanceCaptureSources * UE::MovieScene::FPreAnimatedStateExtension::GetTrackInstanceMetaData () const
HandleMetaDataToRemove()
void UE::MovieScene::FPreAnimatedStateExtension::HandleMetaDataToRemove (const FRestoreStateParams & Params, TArrayView< FPreAnimatedStateMetaData > MetaDataToRemove, FContributionRemover RemoveFunc) private
References Params.
HasActiveCaptureSource()
MOVIESCENE_API bool UE::MovieScene::FPreAnimatedStateExtension::HasActiveCaptureSource () const
Initialize()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::Initialize (UMovieSceneEntitySystemLinker * InLinker)
IsCapturingGlobalState()
bool UE::MovieScene::FPreAnimatedStateExtension::IsCapturingGlobalState () const inline
Check if this extension has any current requests to capture global (persistent) state entries.
Definition at line 205 of file MovieScenePreAnimatedStateExtension.h.
References NumRequestsForGlobalState.
MetaDataExists()
MOVIESCENE_API bool UE::MovieScene::FPreAnimatedStateExtension::MetaDataExists (const FPreAnimatedStateEntry & Entry) const
OnObjectsReplaced()
void UE::MovieScene::FPreAnimatedStateExtension::OnObjectsReplaced (const TMap< UObject *, UObject * > & ReplacementMap)
Called to handle replaced objects.
RegisterStorage()
template<typename StorageType> TPreAnimatedStorageID< StorageType > UE::MovieScene::FPreAnimatedStateExtension::RegisterStorage () inline static
Called from TAutoRegisterPreAnimatedStorageID to register a new application-wide storage type.
Definition at line 87 of file MovieScenePreAnimatedStateExtension.h.
References RegisterStorageInternal().
RegisterStorageInternal()
MOVIESCENE_API FPreAnimatedStorageID UE::MovieScene::FPreAnimatedStateExtension::RegisterStorageInternal () static private
Referenced by RegisterStorage().
RemoveMetaData()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::RemoveMetaData (const FPreAnimatedStateMetaData & MetaData)
References MetaData.
RemoveWeakCaptureSource()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::RemoveWeakCaptureSource (TWeakPtr< IPreAnimatedCaptureSource > InWeakMetaData)
ReplaceObjectForGroup()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::ReplaceObjectForGroup (FPreAnimatedStorageGroupHandle GroupHandle, const FObjectKey & OldObject, const FObjectKey & NewObject)
Called during blueprint re-instancing to replace the object bound to a specific group handle with another.
References NewObject().
ResetEntryInvalidation()
void UE::MovieScene::FPreAnimatedStateExtension::ResetEntryInvalidation () inline
Resets the entry invalidation flag.
Definition at line 222 of file MovieScenePreAnimatedStateExtension.h.
References bEntriesInvalidated.
RestoreGlobalState()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::RestoreGlobalState (const FRestoreStateParams & Params)
Restore any state for any persistent tokens captured during the course of evaluation.
Parameters
Params Parameters for restoration - if TerminalInstanceHandle is invalid then all state will be restored, regardless of the instance it was cached from
References Params.
RestoreStateForGroup()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::RestoreStateForGroup (FPreAnimatedStorageGroupHandle GroupHandle, const FRestoreStateParams & Params)
Restore any state cached for the specified group.
@params GroupHandle Handle to the group to restore
Parameters
Params Parameters for restoration
References Params.
SavePreAnimatedState() [1/2]
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer & Producer)
SavePreAnimatedState() [2/2]
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::SavePreAnimatedState (UObject & InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer & Producer)
SavePreAnimatedStateDirectly() [1/2]
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::SavePreAnimatedStateDirectly (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer & Producer)
SavePreAnimatedStateDirectly() [2/2]
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::SavePreAnimatedStateDirectly (UObject & InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer & Producer)
UpdateMetaData()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedStateExtension::UpdateMetaData (const FPreAnimatedStateMetaData & MetaData)
References MetaData.
Friends And Related Symbol Documentation
::FScopedPreAnimatedCaptureSource
friend struct ::FScopedPreAnimatedCaptureSource friend
Definition at line 380 of file MovieScenePreAnimatedStateExtension.h.
Field Documentation
bEntriesInvalidated
bool UE::MovieScene::FPreAnimatedStateExtension::bEntriesInvalidated private
Definition at line 418 of file MovieScenePreAnimatedStateExtension.h.
Referenced by AreEntriesInvalidated(), and ResetEntryInvalidation().
EntityCaptureSource
TUniquePtr<FPreAnimatedEntityCaptureSource> UE::MovieScene::FPreAnimatedStateExtension::EntityCaptureSource private
Meta-data pertaining to the entity IDs from which animated state originates.
Definition at line 356 of file MovieScenePreAnimatedStateExtension.h.
EvaluationHookCaptureSource
TUniquePtr<UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources> UE::MovieScene::FPreAnimatedStateExtension::EvaluationHookCaptureSource private
Meta-data ledger for any pre-animated state that originates from evaluation hooks.
Definition at line 368 of file MovieScenePreAnimatedStateExtension.h.
GroupManagers
TSortedMap<FPreAnimatedStorageID, TWeakPtr<IPreAnimatedStateGroupManager> > UE::MovieScene::FPreAnimatedStateExtension::GroupManagers private
Definition at line 413 of file MovieScenePreAnimatedStateExtension.h.
Referenced by FindGroupManager(), and GetOrCreateGroupManager().
GroupMetaData
TSparseArray<FPreAnimatedGroupMetaData> UE::MovieScene::FPreAnimatedStateExtension::GroupMetaData private
Definition at line 408 of file MovieScenePreAnimatedStateExtension.h.
Linker
UMovieSceneEntitySystemLinker* UE::MovieScene::FPreAnimatedStateExtension::Linker private
Linker is always valid because this extension is owned by the Linker.
Definition at line 416 of file MovieScenePreAnimatedStateExtension.h.
NumRequestsForGlobalState
uint32 UE::MovieScene::FPreAnimatedStateExtension::NumRequestsForGlobalState
The number of requests that have been made to capture global state - only one should exist per playing sequence.
Definition at line 351 of file MovieScenePreAnimatedStateExtension.h.
Referenced by IsCapturingGlobalState().
StorageImplementations
TSortedMap<FPreAnimatedStorageID, TSharedPtr<IPreAnimatedStorage> > UE::MovieScene::FPreAnimatedStateExtension::StorageImplementations private
Definition at line 412 of file MovieScenePreAnimatedStateExtension.h.
Referenced by AddStorage(), FindStorage(), and GetStorageChecked().
TemplateCaptureSource
TUniquePtr<UE::MovieScene::FPreAnimatedTemplateCaptureSources> UE::MovieScene::FPreAnimatedStateExtension::TemplateCaptureSource private
Meta-data ledger for any pre-animated state that originates from track templates.
Definition at line 365 of file MovieScenePreAnimatedStateExtension.h.
TrackInstanceCaptureSource
TUniquePtr<FPreAnimatedTrackInstanceCaptureSources> UE::MovieScene::FPreAnimatedStateExtension::TrackInstanceCaptureSource private
Meta-data pertaining to pre-animated state originating from track instances.
Definition at line 359 of file MovieScenePreAnimatedStateExtension.h.
TrackInstanceInputCaptureSource
TUniquePtr<FPreAnimatedTrackInstanceInputCaptureSources> UE::MovieScene::FPreAnimatedStateExtension::TrackInstanceInputCaptureSource private
Meta-data pertaining to pre-animated state originating from track instances from a specific input.
Definition at line 362 of file MovieScenePreAnimatedStateExtension.h.
UngroupedMetaData
TMap<FPreAnimatedStateCachedValueHandle, FAggregatePreAnimatedStateMetaData> UE::MovieScene::FPreAnimatedStateExtension::UngroupedMetaData private
Definition at line 410 of file MovieScenePreAnimatedStateExtension.h.
WeakExternalCaptureSources
TArray<TWeakPtr<IPreAnimatedCaptureSource> > UE::MovieScene::FPreAnimatedStateExtension::WeakExternalCaptureSources private
Weakly held meta data provided by FMovieScenePreAnimatedState for various other origins.
Definition at line 371 of file MovieScenePreAnimatedStateExtension.h.
WeakGenericObjectStorage
TWeakPtr<FAnimTypePreAnimatedStateObjectStorage> UE::MovieScene::FPreAnimatedStateExtension::WeakGenericObjectStorage private
Pointers to the storage for state bound to objects, organized by FMovieSceneAnimTypeID.
Definition at line 374 of file MovieScenePreAnimatedStateExtension.h.
WeakGenericRootStorage
TWeakPtr<FAnimTypePreAnimatedStateRootStorage> UE::MovieScene::FPreAnimatedStateExtension::WeakGenericRootStorage private
Pointers to the storage for state created from root tracks, or otherwise not bound to objects.
Definition at line 376 of file MovieScenePreAnimatedStateExtension.h.
The documentation for this struct was generated from the following file:
MovieScenePreAnimatedStateExtension.h