Unreal Engine 5.6 C++ API: TFixedTickReplicator_SP< InModelDef > Class Template Reference
TFixedTickReplicator_SP< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using ModelDef = InModelDef
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TClientRecvData< ModelDef > &ClientRecvState, TModelDataStore< ModelDef > *DataStore, FFixedTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, const FFixedTickState *TickState)
Detailed Description
template<typename InModelDef>
class TFixedTickReplicator_SP< InModelDef >
Definition at line 577 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
ModelDef
template<typename InModelDef> using TFixedTickReplicator_SP< InModelDef >::ModelDef = InModelDef
Definition at line 581 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename InModelDef> void TFixedTickReplicator_SP< InModelDef >::NetRecv (const FNetSerializeParams & P, TClientRecvData< ModelDef > & ClientRecvState, TModelDataStore< ModelDef > * DataStore, FFixedTickState * TickState) inline static
Definition at line 586 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, TInstanceData< ModelDef >::CueDispatcher, FFixedTickState::FixedStepMS, TClientRecvData< ModelDef >::InstanceIdx, TModelDataStore< ModelDef >::Instances, FFixedTickState::Interpolation, FFixedTickState::FInterpolationState::LatestRecvFrameSP, FMath::Max, TCommonReplicator_SP< InModelDef >::NetRecv(), npEnsure, npEnsureSlow, FFixedTickState::Offset, FFixedTickState::PendingFrame, FNetworkPredictionSerialization::ReadCompressedFrame(), TClientRecvData< ModelDef >::ServerFrame, and UE_NP_TRACE_NET_RECV.
NetSend()
template<typename InModelDef> void TFixedTickReplicator_SP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, const FFixedTickState * TickState) inline static
Definition at line 607 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, ID, Instance, TModelDataStore< ModelDef >::Instances, Interpolators, TCommonReplicator_SP< InModelDef >::NetSend(), npCheckSlow, npEnsure, FFixedTickState::PendingFrame, SimulatedProxy, and FNetworkPredictionSerialization::WriteCompressedFrame().
The documentation for this class was generated from the following file:
NetworkPredictionSerialization.h