Unreal Engine 5.6 C++ API: UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType > Class Template Reference
UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType > Class Template Reference
Selection set that defines a fragment selection of a view model where each fragment is globally unique.
#include "SequencerCoreSelectionTypes.h"
Public Member Functions
FORCEINLINE TUniqueFragmentSelectionSetIterator< KeyType > begin () const
void Deselect (KeyType InKey)
Deselect an item.
void Empty ()
Empty this selection.
FORCEINLINE TUniqueFragmentSelectionSetIterator< KeyType > end () const
TViewModelPtr< ModelType > GetModelForKey (KeyType InKey) const
Retrieve the view model associated with the specified fragment selection.
const TSet< KeyType > & GetSelected () const
Returns the underlying selection set (including potentially invalid items)
bool IsSelected (KeyType InKey) const
Check whether a given item is currently selected.
int32 Num () const
Returns the number of selected items (including potentially invalid items)
template<typename Filter>
void RemoveByPredicate (Filter &&InFilter)
Remove all selected items that pass the specified filter.
void ReplaceWith (TUniqueFragmentSelectionSet< KeyType, ModelType > &&OtherSelection)
Replace this selection set with the contents from another.
void Select (TViewModelPtr< ModelType > InOwner, KeyType InKey, bool *OutNewlySelected=nullptr)
Select a key, optionally supplying a boolean to receieve a value indicating whether it was already selected or not.
template<typename RangeType>
void SelectRange (TViewModelPtr< ModelType > InOwner, RangeType Range, bool *OutAnySelected=nullptr)
Selects a range of keys, optionally supplying a boolean to receieve a value indicating whether any were newly selected or not.
Public Member Functions inherited from UE::Sequencer::FSelectionBase
SEQUENCERCORE_API void Empty ()
Empty this selection set.
bool HasPendingChanges () const
Check whether this selection set has reported changes that are currently pending.
Private Member Functions
void EmptyImpl () override
Abstract function for emptying this selection.
Private Attributes
TMap< KeyType, TWeakViewModelPtr< ModelType > > KeyToViewModel
Reverse mapping from item to its owning model.
TSet< KeyType > SelectionSet
The unique selection set of fragments.
Additional Inherited Members
Data Fields inherited from UE::Sequencer::FSelectionBase
FSimpleMulticastDelegate OnChanged
Broadcast if this selection set has changed when all event suppressors have been destroyed.
Protected Member Functions inherited from UE::Sequencer::FSelectionBase
FSelectionBase ()
Should only be used by derived types.
virtual ~FSelectionBase ()
FSequencerCoreSelection * GetOwner () const
Retrieve the owner of this instance, assuming it has been added to one.
SEQUENCERCORE_API void ReportChanges (bool bInSelectionChanged=true)
Called by derived classes when they have changed.
Detailed Description
template<typename KeyType, typename ModelType>
class UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >
Selection set that defines a fragment selection of a view model where each fragment is globally unique.
A good example is FKeyHandle or any other monotomic counter. Selection must be associated with a view model type defined by the template parameter ModelType.
Definition at line 321 of file SequencerCoreSelectionTypes.h.
Member Function Documentation
begin()
template<typename KeyType, typename ModelType> FORCEINLINE TUniqueFragmentSelectionSetIterator< KeyType > UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::begin () const inline
Definition at line 484 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE, and SelectionSet.
Deselect()
template<typename KeyType, typename ModelType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Deselect (KeyType InKey) inline
Deselect an item.
Definition at line 430 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), KeyToViewModel, UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Empty()
template<typename KeyType, typename ModelType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Empty () inline
Empty this selection.
Definition at line 445 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), KeyToViewModel, UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Referenced by EmptyImpl().
EmptyImpl()
template<typename KeyType, typename ModelType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::EmptyImpl () inline override private virtual
Abstract function for emptying this selection.
Implements UE::Sequencer::FSelectionBase.
Definition at line 489 of file SequencerCoreSelectionTypes.h.
References Empty().
end()
template<typename KeyType, typename ModelType> FORCEINLINE TUniqueFragmentSelectionSetIterator< KeyType > UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::end () const inline
Definition at line 485 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE, and SelectionSet.
GetModelForKey()
template<typename KeyType, typename ModelType> TViewModelPtr< ModelType > UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::GetModelForKey (KeyType InKey) const inline
Retrieve the view model associated with the specified fragment selection.
Definition at line 344 of file SequencerCoreSelectionTypes.h.
References KeyToViewModel.
GetSelected()
template<typename KeyType, typename ModelType> const TSet< KeyType > & UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::GetSelected () const inline
Returns the underlying selection set (including potentially invalid items)
Definition at line 336 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
IsSelected()
template<typename KeyType, typename ModelType> bool UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::IsSelected (KeyType InKey) const inline
Check whether a given item is currently selected.
Definition at line 352 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
Num()
template<typename KeyType, typename ModelType> int32 UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Num () const inline
Returns the number of selected items (including potentially invalid items)
Definition at line 328 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
RemoveByPredicate()
template<typename KeyType, typename ModelType> template<typename Filter> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::RemoveByPredicate (Filter && InFilter) inline
Remove all selected items that pass the specified filter.
Definition at line 460 of file SequencerCoreSelectionTypes.h.
References Filter, UE::Sequencer::FSelectionBase::GetOwner(), Key, KeyToViewModel, UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
ReplaceWith()
template<typename KeyType, typename ModelType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::ReplaceWith (TUniqueFragmentSelectionSet< KeyType, ModelType > && OtherSelection) inline
Replace this selection set with the contents from another.
Parameters
OtherSelection The selection set to replace this one with
Definition at line 412 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), KeyToViewModel, MoveTemp(), UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Select()
template<typename KeyType, typename ModelType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Select (TViewModelPtr< ModelType > InOwner, KeyType InKey, bool * OutNewlySelected = nullptr) inline
Select a key, optionally supplying a boolean to receieve a value indicating whether it was already selected or not.
Parameters
InKey The item to select
OutNewlySelected (Optional) When non-null, will be assigned true of false based on whether this item was newly selected as a result of this call
Definition at line 363 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), MakeArrayView(), and SelectRange().
Referenced by UE::Sequencer::FKeySelection::Select().
SelectRange()
template<typename KeyType, typename ModelType> template<typename RangeType> void UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::SelectRange (TViewModelPtr< ModelType > InOwner, RangeType Range, bool * OutAnySelected = nullptr) inline
Selects a range of keys, optionally supplying a boolean to receieve a value indicating whether any were newly selected or not.
Parameters
Range An arbitrary range of items to select. Must be implicitly convertible to KeyType.
OutNewlySelected (Optional) When non-null, will be assigned true of false based on whether this item was newly selected as a result of this call
Definition at line 376 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), Key, KeyToViewModel, UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Referenced by Select(), and UE::Sequencer::FKeySelection::SelectRange().
Field Documentation
KeyToViewModel
template<typename KeyType, typename ModelType> TMap<KeyType, TWeakViewModelPtr<ModelType> > UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::KeyToViewModel private
Reverse mapping from item to its owning model.
Definition at line 497 of file SequencerCoreSelectionTypes.h.
Referenced by Deselect(), Empty(), GetModelForKey(), RemoveByPredicate(), ReplaceWith(), and SelectRange().
SelectionSet
template<typename KeyType, typename ModelType> TSet<KeyType> UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::SelectionSet private
The unique selection set of fragments.
Definition at line 495 of file SequencerCoreSelectionTypes.h.
Referenced by begin(), Deselect(), Empty(), end(), GetSelected(), IsSelected(), Num(), RemoveByPredicate(), ReplaceWith(), and SelectRange().
The documentation for this class was generated from the following file:
SequencerCoreSelectionTypes.h