Unreal Engine 5.6 C++ API: FDynamicMeshBufferAllocator Class Reference
FDynamicMeshBufferAllocator Class Reference
This class provides the vertex/index allocator interface used by FDynamicMeshBuilder which is already implemented internally with caching in mind but can be customized if needed.
#include "DynamicMeshBuilder.h"
Public Member Functions
virtual ~FDynamicMeshBufferAllocator ()
virtual FBufferRHIRef AllocIndexBuffer (FRHICommandListBase &RHICmdList, uint32 NumElements)
virtual FBufferRHIRef AllocVertexBuffer (FRHICommandListBase &RHICmdList, uint32 Stride, uint32 NumElements)
int32 GetIndexBufferSize (uint32 NumElements) const
int32 GetVertexBufferSize (uint32 Stride, uint32 NumElements) const
virtual void ReleaseIndexBuffer (FBufferRHIRef &IndexBufferRHI)
virtual void ReleaseVertexBuffer (FBufferRHIRef &VertexBufferRHI)
UE_DEPRECATED (5.4, "AllocIndexBuffer requires a command list.") 1 virtual FBufferRHIRef AllocIndexBuffer(uint32 NumElements) final
UE_DEPRECATED (5.4, "AllocVertexBuffer requires a command list.") 1 virtual FBufferRHIRef AllocVertexBuffer(uint32 Stride
Data Fields
uint32 NumElements final
Detailed Description
This class provides the vertex/index allocator interface used by FDynamicMeshBuilder which is already implemented internally with caching in mind but can be customized if needed.
Definition at line 132 of file DynamicMeshBuilder.h.
Constructor & Destructor Documentation
~FDynamicMeshBufferAllocator()
virtual FDynamicMeshBufferAllocator::~FDynamicMeshBufferAllocator () virtual
Member Function Documentation
AllocIndexBuffer()
virtual FBufferRHIRef FDynamicMeshBufferAllocator::AllocIndexBuffer (FRHICommandListBase & RHICmdList, uint32 NumElements) virtual
Referenced by UE_DEPRECATED().
AllocVertexBuffer()
virtual FBufferRHIRef FDynamicMeshBufferAllocator::AllocVertexBuffer (FRHICommandListBase & RHICmdList, uint32 Stride, uint32 NumElements) virtual
GetIndexBufferSize()
int32 FDynamicMeshBufferAllocator::GetIndexBufferSize (uint32 NumElements) const
GetVertexBufferSize()
int32 FDynamicMeshBufferAllocator::GetVertexBufferSize (uint32 Stride, uint32 NumElements) const
ReleaseIndexBuffer()
virtual void FDynamicMeshBufferAllocator::ReleaseIndexBuffer (FBufferRHIRef & IndexBufferRHI) virtual
ReleaseVertexBuffer()
virtual void FDynamicMeshBufferAllocator::ReleaseVertexBuffer (FBufferRHIRef & VertexBufferRHI) virtual
UE_DEPRECATED() [1/2]
FDynamicMeshBufferAllocator::UE_DEPRECATED (5. 4, "AllocIndexBuffer requires a command list.") final
References AllocIndexBuffer(), and final.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FDynamicMeshBufferAllocator::UE_DEPRECATED (5. 4, "AllocVertexBuffer requires a command list.")
References UE_DEPRECATED().
Field Documentation
final
uint32 NumElements FDynamicMeshBufferAllocator::final
Definition at line 148 of file DynamicMeshBuilder.h.
Referenced by UE_DEPRECATED().
The documentation for this class was generated from the following file:
DynamicMeshBuilder.h