Unreal Engine 5.6 C++ API: TRange< ElementType > Class Template Reference
TRange< ElementType > Class Template Reference
Template for ranges.
#include "Range.h"
Public Types
typedef TRangeBound< ElementType > BoundsType
typedef TCallTraits< ElementType >::ParamType ElementValueOrConstRef
Public Member Functions
TRange ()
Default constructor (no initialization).
TRange (const BoundsType &InLowerBound, const BoundsType &InUpperBound)
Create and initializes a new range with the given lower and upper bounds.
TRange (ElementValueOrConstRef A)
Create a range with a single element.
TRange (ElementValueOrConstRef A, ElementValueOrConstRef B)
Create and initializes a new range with the given lower and upper bounds.
bool Adjoins (const TRange &Other) const
Check whether this range adjoins to another.
bool Conjoins (const TRange &X, const TRange &Y) const
Check whether this range conjoins the two given ranges.
bool Contains (const TRange &Other) const
Check whether this range contains another range.
bool Contains (ElementValueOrConstRef Element) const
Check whether this range contains the specified element.
bool Contiguous (const TRange &Other) const
Check if this range is contiguous with another range.
BoundsType GetLowerBound () const
Get the range's lower bound.
ElementValueOrConstRef GetLowerBoundValue () const
Get the value of the lower bound.
BoundsType GetUpperBound () const
Get the range's upper bound.
ElementValueOrConstRef GetUpperBoundValue () const
Get the value of the upper bound.
bool HasLowerBound () const
Check whether the range has a lower bound.
bool HasUpperBound () const
Check whether the range has an upper bound.
bool IsDegenerate () const
Check whether this range is degenerate.
bool IsEmpty () const
Check whether this range is empty.
bool operator!= (const TRange &Other) const
Compare this range with the specified range for inequality.
bool operator== (const TRange &Other) const
Compare this range with the specified range for equality.
bool Overlaps (const TRange &Other) const
Check whether this range overlaps with another.
void SetLowerBound (const BoundsType &NewLowerBound)
Assign the new lower bound for this range.
void SetLowerBoundValue (ElementValueOrConstRef NewLowerBoundValue)
Assign the new lower bound value for this range.
void SetUpperBound (const BoundsType &NewUpperBound)
Assign the new upper bound for this range.
void SetUpperBoundValue (ElementValueOrConstRef NewUpperBoundValue)
Assign the new upper bound value for this range.
template<typename DifferenceType>
DifferenceType Size () const
Compute the size (diameter, length, width) of this range.
TArray< TRange > Split (ElementValueOrConstRef Element) const
Split the range into two ranges at the specified element.
Static Public Member Functions
static FORCEINLINE TRange All ()
Create an unbounded (open) range that contains all elements of the domain.
static FORCEINLINE TRange AtLeast (ElementValueOrConstRef Value)
Create a left-bounded range that contains all elements greater than or equal to the specified value.
static FORCEINLINE TRange AtMost (ElementValueOrConstRef Value)
Create a right-bounded range that contains all elements less than or equal to the specified value.
static FORCEINLINE TArray< TRange > Difference (const TRange &X, const TRange &Y)
Calculate the difference between two ranges, i.e.
static FORCEINLINE TRange Empty ()
Return an empty range.
static FORCEINLINE TRange Exclusive (ElementValueOrConstRef Min, ElementValueOrConstRef Max)
Create a range that excludes the given minimum and maximum values.
static FORCEINLINE TRange GreaterThan (ElementValueOrConstRef Value)
Create a left-bounded range that contains all elements greater than the specified value.
static FORCEINLINE TRange Hull (const TArray< TRange > &Ranges)
Compute the hull of many ranges.
static FORCEINLINE TRange Hull (const TRange &X, const TRange &Y)
Compute the hull of two ranges.
static FORCEINLINE TRange Inclusive (ElementValueOrConstRef Min, ElementValueOrConstRef Max)
Create a range that includes the given minimum and maximum values.
static FORCEINLINE TRange Intersection (const TArray< TRange > &Ranges)
Compute the intersection of many ranges.
static FORCEINLINE TRange Intersection (const TRange &X, const TRange &Y)
Compute the intersection of two ranges.
static FORCEINLINE TRange LessThan (ElementValueOrConstRef Value)
Create a right-bounded range that contains all elements less than the specified value.
static FORCEINLINE TArray< TRange > Union (const TRange &X, const TRange &Y)
Return the union of two contiguous ranges.
Private Attributes
BoundsType LowerBound
Holds the range's lower bound.
BoundsType UpperBound
Holds the range's upper bound.
Friends
uint32 GetTypeHash (const TRange &Range)
Gets the hash for the specified range.
class FArchive & operator<< (class FArchive &Ar, TRange &Range)
Serializes the given range from or into the specified archive.
Detailed Description
template<typename ElementType>
class TRange< ElementType >
Template for ranges.
Note: This class is not intended for interval arithmetic (see TInterval for that).
A range represents a contiguous set of elements that only stores the set's lower and upper bound values (aka. endpoints) for storage efficiency. Bound values may be exclusive (the value is not part of the range), inclusive (the value is part of the range) or open (there is no limit on the values).
The template's primary focus is on continuous ranges, but it can be used for the representation of discrete ranges as well. The element type of discrete ranges has a well-defined stepping, such as an integer or a date, that separates the neighboring elements. This is in contrast with continuous ranges in which the step sizes, such as floats or time spans, are not of interest, and other elements may be found between any two elements (although, in practice, all ranges are discrete due to the limited precision of numerical values in computers).
When working with ranges, the user of this template is responsible for correctly interpreting the range endpoints. Certain semantics will be different depending on whether the range is interpreted in a continuous or discrete domain.
Iteration of a discrete range [A, B) includes the elements A to B-1. The elements of continuous ranges are generally not meant to be iterated. It is also important to consider the equivalence of different representations of discrete ranges. For example, the ranges [2, 6), (1, 5] and [2, 5] are equivalent in discrete domains, but different in continuous ones. In order to keep this class simple, we have not included canonicalization functions or auxiliary template parameters, such as unit and min/max domain elements. For ease of use in most common use cases, it is recommended to limit all operations to canonical ranges of the form [A, B) in which the lower bound is included and the upper bound is excluded from the range.
Parameters
ElementType The type of elements represented by the range
See also
RangeBound, TInterval
Definition at line 49 of file Range.h.
Member Typedef Documentation
BoundsType
template<typename ElementType> typedef TRangeBound<ElementType> TRange< ElementType >::BoundsType
Definition at line 53 of file Range.h.
ElementValueOrConstRef
template<typename ElementType> typedef TCallTraits<ElementType>::ParamType TRange< ElementType >::ElementValueOrConstRef
Definition at line 56 of file Range.h.
Constructor & Destructor Documentation
TRange() [1/4]
template<typename ElementType> TRange< ElementType >::TRange () inline nodiscard
Default constructor (no initialization).
Definition at line 59 of file Range.h.
Referenced by TRange< float >::All(), TRange< float >::AtLeast(), TRange< float >::AtMost(), TRange< float >::Difference(), TRange< float >::Empty(), TRange< float >::Exclusive(), TRange< float >::GreaterThan(), TRange< float >::Hull(), TRange< float >::Inclusive(), TRange< float >::Intersection(), TRange< float >::LessThan(), TRange< float >::Split(), and TRange< float >::Union().
TRange() [2/4]
template<typename ElementType> TRange< ElementType >::TRange (ElementValueOrConstRef A) inline explicit nodiscard
Create a range with a single element.
The created range is of the form [A, A].
Parameters
A The element in the range.
Definition at line 68 of file Range.h.
TRange() [3/4]
template<typename ElementType> TRange< ElementType >::TRange (ElementValueOrConstRef A, ElementValueOrConstRef B) inline explicit nodiscard
Create and initializes a new range with the given lower and upper bounds.
The created range is of the form [A, B).
Parameters
A The range's lower bound value (inclusive).
B The range's upper bound value (exclusive).
Definition at line 81 of file Range.h.
TRange() [4/4]
template<typename ElementType> TRange< ElementType >::TRange (const BoundsType & InLowerBound, const BoundsType & InUpperBound) inline explicit nodiscard
Create and initializes a new range with the given lower and upper bounds.
Parameters
InLowerBound The range's lower bound.
InUpperBound The range's upper bound.
Definition at line 92 of file Range.h.
Member Function Documentation
Adjoins()
template<typename ElementType> bool TRange< ElementType >::Adjoins (const TRange< ElementType > & Other) const inline nodiscard
Check whether this range adjoins to another.
Two ranges are adjoint if they are next to each other without overlapping, i.e. [A, B) and [B, C) or [A, B] and (B, C)
Parameters
Other The other range.
Returns
true if this range adjoins the other, false otherwise.
Definition at line 143 of file Range.h.
Referenced by TRangeSet< ElementType >::Add(), TRange< float >::Conjoins(), and TRange< float >::Contiguous().
All()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::All () inline static nodiscard
Create an unbounded (open) range that contains all elements of the domain.
Returns
A new range.
See also
AtLeast, AtMost, Empty, Exclusive, GreaterThan, Inclusive, LessThan
Definition at line 636 of file Range.h.
Referenced by FMovieSceneEvaluationTree::FMovieSceneEvaluationTree(), FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), IKeyArea::GetKeyHandles(), IKeyArea::GetKeyInfo(), IKeyArea::GetKeyTimes(), and FMovieSceneEvaluationTree::operator=().
AtLeast()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::AtLeast (ElementValueOrConstRef Value) inline static nodiscard
Create a left-bounded range that contains all elements greater than or equal to the specified value.
Parameters
Value The value.
Returns
A new range.
See also
All, AtMost, Empty, Exclusive, GreaterThan, Inclusive, LessThan
Definition at line 648 of file Range.h.
AtMost()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::AtMost (ElementValueOrConstRef Value) inline static nodiscard
Create a right-bounded range that contains all elements less than or equal to the specified value.
Parameters
Value The value.
Returns
A new range.
See also
All, AtLeast, Empty, Exclusive, GreaterThan, Inclusive, LessThan
Definition at line 660 of file Range.h.
Conjoins()
template<typename ElementType> bool TRange< ElementType >::Conjoins (const TRange< ElementType > & X, const TRange< ElementType > & Y) const inline nodiscard
Check whether this range conjoins the two given ranges.
A range conjoins two non-overlapping ranges if it adjoins both of them, i.e. [B, C) conjoins the two ranges [A, B) and [C, D).
Parameters
X The first range.
Y The second range.
Returns
true if this range conjoins the two ranges, false otherwise.
Definition at line 175 of file Range.h.
Contains() [1/2]
template<typename ElementType> bool TRange< ElementType >::Contains (const TRange< ElementType > & Other) const inline nodiscard
Check whether this range contains another range.
Parameters
Other The range to check.
Returns
true if the range contains the other range, false otherwise.
Definition at line 203 of file Range.h.
Contains() [2/2]
template<typename ElementType> bool TRange< ElementType >::Contains (ElementValueOrConstRef Element) const inline nodiscard
Check whether this range contains the specified element.
Parameters
Element The element to check.
Returns
true if the range contains the element, false otherwise.
Definition at line 191 of file Range.h.
Referenced by FMovieSceneContext::ReportOuterSectionRanges(), and TRange< float >::Split().
Contiguous()
template<typename ElementType> bool TRange< ElementType >::Contiguous (const TRange< ElementType > & Other) const inline nodiscard
Check if this range is contiguous with another range.
Two ranges are contiguous if they are adjoint or overlapping.
Parameters
Other The other range.
Returns
true if the ranges are contiguous, false otherwise.
Definition at line 217 of file Range.h.
Difference()
template<typename ElementType> FORCEINLINE TArray< TRange > TRange< ElementType >::Difference (const TRange< ElementType > & X, const TRange< ElementType > & Y) inline static nodiscard
Calculate the difference between two ranges, i.e.
X - Y.
Parameters
X The first range to subtract from.
Y The second range to subtract with.
Returns
Between 0 and 2 remaining ranges.
See also
Hull, Intersection, Union
Definition at line 469 of file Range.h.
Empty()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Empty () inline static nodiscard
Return an empty range.
Returns
Empty range.
See also
All, AtLeast, AtMost, Exclusive, GreaterThan, Inclusive, LessThan
Definition at line 671 of file Range.h.
Referenced by TMovieSceneChannelData< const ValueType >::GetTotalRange(), TRange< float >::Hull(), TRange< float >::Intersection(), TRange< float >::Intersection(), USTRUCT(), and USTRUCT().
Exclusive()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Exclusive (ElementValueOrConstRef Min, ElementValueOrConstRef Max) inline static nodiscard
Create a range that excludes the given minimum and maximum values.
Parameters
MinThe minimum value to be included.
Max The maximum value to be included.
Returns
A new range.
See also
All, AtLeast, AtMost, Empty, Exclusive, GreaterThan, Inclusive, LessThan
Definition at line 684 of file Range.h.
GetLowerBound()
template<typename ElementType> BoundsType TRange< ElementType >::GetLowerBound () const inline nodiscard
Get the range's lower bound.
Returns
Lower bound.
See also
GetLowerBoundValue, GetUpperBound, HasLowerBound
Definition at line 228 of file Range.h.
Referenced by TRangeSet< ElementType >::Add(), UE::MovieScene::ClampToDiscreteRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DilateRange(), UE::MovieScene::DiscreteInclusiveLower(), UE::MovieScene::DiscreteRangeIsEmpty(), LexToString(), and FFrameRate::operator/.
GetLowerBoundValue()
template<typename ElementType> ElementValueOrConstRef TRange< ElementType >::GetLowerBoundValue () const inline nodiscard
Get the value of the lower bound.
Use HasLowerBound() to ensure that this range actually has a lower bound.
Returns
Bound value.
See also
GetLowerBound, GetUpperBoundValue, HasLowerBound
Definition at line 263 of file Range.h.
Referenced by FSequencerTimeSliderController::FScrubRangeToScreen::FScrubRangeToScreen(), UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DiscreteRangeIsEmpty(), FMath::GetRangePct(), FMath::GetRangeValue(), UE::MovieScene::MakeHullRange(), MovieSceneToolHelpers::MergeChannels(), and FMovieSceneContext::ReportOuterSectionRanges().
GetUpperBound()
template<typename ElementType> BoundsType TRange< ElementType >::GetUpperBound () const inline nodiscard
Get the range's upper bound.
Returns
Upper bound.
See also
GetLowerBound, GetUpperBoundValue, HasUpperBound
Definition at line 274 of file Range.h.
Referenced by TRangeSet< ElementType >::Add(), UE::MovieScene::ClampToDiscreteRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DilateRange(), UE::MovieScene::DiscreteExclusiveUpper(), UE::MovieScene::DiscreteRangeIsEmpty(), LexToString(), and FFrameRate::operator/.
GetUpperBoundValue()
template<typename ElementType> ElementValueOrConstRef TRange< ElementType >::GetUpperBoundValue () const inline nodiscard
Get the value of the upper bound.
Use HasUpperBound() to ensure that this range actually has an upper bound.
Returns
Bound value.
See also
GetLowerBoundValue, GetUpperBound, HasUpperBound
Definition at line 309 of file Range.h.
Referenced by UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DiscreteRangeIsEmpty(), FMath::GetRangePct(), FMath::GetRangeValue(), UE::MovieScene::MakeHullRange(), MovieSceneToolHelpers::MergeChannels(), and FMovieSceneContext::ReportOuterSectionRanges().
GreaterThan()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::GreaterThan (ElementValueOrConstRef Value) inline static nodiscard
Create a left-bounded range that contains all elements greater than the specified value.
Parameters
Value The value.
Returns
A new range.
See also
All, AtLeast, AtMost, Empty, Exclusive, Inclusive, LessThan
Definition at line 696 of file Range.h.
HasLowerBound()
template<typename ElementType> bool TRange< ElementType >::HasLowerBound () const inline nodiscard
Check whether the range has a lower bound.
Returns
true if the range has a lower bound, false otherwise.
See also
GetLowerBound, GetLowerBoundValue, HasUpperBound
Definition at line 320 of file Range.h.
Referenced by UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::MakeHullRange(), and FMovieSceneContext::ReportOuterSectionRanges().
HasUpperBound()
template<typename ElementType> bool TRange< ElementType >::HasUpperBound () const inline nodiscard
Check whether the range has an upper bound.
Returns
true if the range has an upper bound, false otherwise.
See also
GetUpperBound, GetUpperBoundValue, HasLowerBound
Definition at line 331 of file Range.h.
Referenced by UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::MakeHullRange(), and FMovieSceneContext::ReportOuterSectionRanges().
Hull() [1/2]
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Hull (const TArray< TRange< ElementType > > & Ranges) inline static nodiscard
Compute the hull of many ranges.
Parameters
Ranges The ranges to hull.
Returns
The hull.
See also
Difference, Intersection, Union
Definition at line 528 of file Range.h.
Hull() [2/2]
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Hull (const TRange< ElementType > & X, const TRange< ElementType > & Y) inline static nodiscard
Compute the hull of two ranges.
The hull is the smallest range that contains both ranges.
Parameters
X The first range.
Y The second range.
Returns
The hull.
See also
Difference, Intersection, Union
Definition at line 506 of file Range.h.
Referenced by TRange< float >::Hull(), and Sequencer::PasteKeys().
Inclusive()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Inclusive (ElementValueOrConstRef Min, ElementValueOrConstRef Max) inline static nodiscard
Create a range that includes the given minimum and maximum values.
Parameters
Min The minimum value to be included.
Max The maximum value to be included.
Returns
A new range.
See also
All, AtLeast, AtMost, Empty, Exclusive, GreaterThan, LessThan
Definition at line 709 of file Range.h.
Intersection() [1/2]
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Intersection (const TArray< TRange< ElementType > > & Ranges) inline static nodiscard
Compute the intersection of many ranges.
Parameters
Ranges The ranges to intersect.
Returns
The intersection.
See also
Difference, Hull, Union
Definition at line 577 of file Range.h.
Intersection() [2/2]
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::Intersection (const TRange< ElementType > & X, const TRange< ElementType > & Y) inline static nodiscard
Compute the intersection of two ranges.
The intersection of two ranges is the largest range that is contained by both ranges.
Parameters
X The first range.
Y The second range.
Returns
The intersection, or an empty range if the ranges do not overlap.
See also
Difference, Hull, Union
Definition at line 555 of file Range.h.
Referenced by FMovieSceneContext::Clamp(), and TRange< float >::Intersection().
IsDegenerate()
template<typename ElementType> bool TRange< ElementType >::IsDegenerate () const inline nodiscard
Check whether this range is degenerate.
A range is degenerate if it contains only a single element, i.e. has the following form: [A, A]
Returns
true if the range is degenerate, false otherwise.
See also
IsEmpty
Definition at line 345 of file Range.h.
IsEmpty()
template<typename ElementType> bool TRange< ElementType >::IsEmpty () const inline nodiscard
Check whether this range is empty.
A range is empty if it contains no elements, i.e. (A, A) (A, A] [A, A)
Returns
true if the range is empty, false otherwise.
See also
IsDegenerate
Definition at line 361 of file Range.h.
Referenced by TRange< float >::Adjoins(), TRange< float >::Difference(), UE::MovieScene::IsEmptyOrZeroSize(), TRange< float >::operator!=(), TRange< float >::operator==(), and TRange< float >::Overlaps().
LessThan()
template<typename ElementType> FORCEINLINE TRange TRange< ElementType >::LessThan (ElementValueOrConstRef Value) inline static nodiscard
Create a right-bounded range that contains all elements less than the specified value.
Parameters
Value The value.
Returns
A new range.
See also
All, AtLeast, AtMost, Empty, Exclusive, GreaterThan, Inclusive
Definition at line 721 of file Range.h.
operator!=()
template<typename ElementType> bool TRange< ElementType >::operator!= (const TRange< ElementType > & Other) const inline nodiscard
Compare this range with the specified range for inequality.
Parameters
Other The range to compare with.
Returns
true if the ranges are not equal, false otherwise.
Definition at line 121 of file Range.h.
operator==()
template<typename ElementType> bool TRange< ElementType >::operator== (const TRange< ElementType > & Other) const inline nodiscard
Compare this range with the specified range for equality.
Parameters
Other The range to compare with.
Returns
true if the ranges are equal, false otherwise.
Definition at line 105 of file Range.h.
Overlaps()
template<typename ElementType> bool TRange< ElementType >::Overlaps (const TRange< ElementType > & Other) const inline nodiscard
Check whether this range overlaps with another.
Parameters
Other The other range.
Returns
true if the ranges overlap, false otherwise.
Definition at line 382 of file Range.h.
Referenced by TRangeSet< ElementType >::Add(), TRange< float >::Contiguous(), and FMediaIOCoreSampleContainer< SampleType >::FetchSample().
SetLowerBound()
template<typename ElementType> void TRange< ElementType >::SetLowerBound (const BoundsType & NewLowerBound) inline
Assign the new lower bound for this range.
Parameters
NewLowerBound The new lower bound to assign
See also
GetLowerBound
Definition at line 239 of file Range.h.
SetLowerBoundValue()
template<typename ElementType> void TRange< ElementType >::SetLowerBoundValue (ElementValueOrConstRef NewLowerBoundValue) inline
Assign the new lower bound value for this range.
Current lower bound must not be open to call this method.
Parameters
NewLowerBoundValue The new lower bound value to assign
See also
GetLowerBound
Definition at line 250 of file Range.h.
SetUpperBound()
template<typename ElementType> void TRange< ElementType >::SetUpperBound (const BoundsType & NewUpperBound) inline
Assign the new upper bound for this range.
Parameters
NewUpperBound The new upper bound to assign
See also
GetUpperBound
Definition at line 285 of file Range.h.
SetUpperBoundValue()
template<typename ElementType> void TRange< ElementType >::SetUpperBoundValue (ElementValueOrConstRef NewUpperBoundValue) inline
Assign the new upper bound value for this range.
Current upper bound must not be open to call this method.
Parameters
NewUpperBoundValue The new upper bound value to assign
See also
GetUpperBound
Definition at line 296 of file Range.h.
Size()
template<typename ElementType> template<typename DifferenceType> DifferenceType TRange< ElementType >::Size () const inline nodiscard
Compute the size (diameter, length, width) of this range.
The size of a closed range is the difference between its upper and lower bound values. Use IsClosed() on the lower and upper bounds before calling this method in order to make sure that the range is closed.
Returns
Range size.
Definition at line 427 of file Range.h.
Referenced by FSequencerTimeSliderController::FScrubRangeToScreen::FScrubRangeToScreen(), and UE::MovieScene::IsEmptyOrZeroSize().
Split()
template<typename ElementType> TArray< TRange > TRange< ElementType >::Split (ElementValueOrConstRef Element) const inline nodiscard
Split the range into two ranges at the specified element.
If a range [A, C) does not contain the element X, the original range is returned. Otherwise the range is split into two ranges [A, X) and [X, C), each of which may be empty.
Parameters
Element The element at which to split the range.
Definition at line 442 of file Range.h.
Union()
template<typename ElementType> FORCEINLINE TArray< TRange > TRange< ElementType >::Union (const TRange< ElementType > & X, const TRange< ElementType > & Y) inline static nodiscard
Return the union of two contiguous ranges.
A union is a range or series of ranges that contains both ranges.
Parameters
X The first range.
Y The second range.
Returns
The union, or both ranges if the two ranges are not contiguous, or no ranges if both ranges are empty.
See also
Difference, Hull, Intersection
Definition at line 604 of file Range.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename ElementType> uint32 GetTypeHash (const TRange< ElementType > & Range) friend
Gets the hash for the specified range.
Parameters
Range The range to get the hash for.
Returns
Hash value.
Definition at line 746 of file Range.h.
Referenced by TRange< float >::GetTypeHash.
operator<<
template<typename ElementType> class FArchive & operator<< (class FArchive & Ar, TRange< ElementType > & Range) friend
Serializes the given range from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Range The range to serialize.
Returns
The archive.
Definition at line 735 of file Range.h.
Field Documentation
LowerBound
template<typename ElementType> BoundsType TRange< ElementType >::LowerBound private
Holds the range's lower bound.
Definition at line 754 of file Range.h.
Referenced by TRange< float >::GetTypeHash, and TRange< float >::operator<<.
UpperBound
template<typename ElementType> BoundsType TRange< ElementType >::UpperBound private
Holds the range's upper bound.
Definition at line 757 of file Range.h.
Referenced by TRange< float >::GetTypeHash, and TRange< float >::operator<<.
The documentation for this class was generated from the following files:
ISequencerSection.h
Range.h