Unreal Engine 5.6 C++ API: FRigVMTreeContext Class Reference
FRigVMTreeContext Class Reference
The context is the top level object passed to anything that has to interact with the tree, like visible node traversal, task execution etc.
#include "RigVMTreeToolkitContext.h"
Public Types
typedef FRigVMTreeElement Super
Public Member Functions
DECLARE_EVENT_OneParam (FRigVMTreeContext, FLogTokenizedMessage, const TSharedRef< FTokenizedMessage > &) void LogMessage(const TSharedRef< FTokenizedMessage > &InMessage) const
bool FiltersNode (TSharedRef< FRigVMTreeNode > InNode) const
virtual FName GetType () const override
virtual uint32 GetVisibleChildrenHash () const
virtual bool IsOfType (const FName &InType) const override
void LogError (const FString &InString) const
void LogError (const FText &InText) const
void LogMessage (const FString &InString) const
void LogMessage (const FText &InText) const
void LogWarning (const FString &InString) const
void LogWarning (const FText &InText) const
TSharedPtr< FRigVMTreeContext > ToSharedPtr () const
TSharedRef< FRigVMTreeContext > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreeContext > Create (Types... Args)
static FAssetData FindAssetFromAnyPath (const FString &InPartialOrFullPath, bool bUseRootPath)
Data Fields
TArray< TSharedRef< FRigVMTreeFilter > > Filters
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeContext"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
uint32 HashOffset = 0
FLogTokenizedMessage OnLogTokenizedMessage
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeContext > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeContext > &InElement)
class FRigVMTreePhase
class SRigVMBulkEditWidget
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The context is the top level object passed to anything that has to interact with the tree, like visible node traversal, task execution etc.
Definition at line 18 of file RigVMTreeToolkitContext.h.
Member Typedef Documentation
Super
typedef FRigVMTreeElement FRigVMTreeContext::Super
Definition at line 21 of file RigVMTreeToolkitContext.h.
Member Function Documentation
Create()
template<typename... Types> TSharedRef< FRigVMTreeContext > FRigVMTreeContext::Create (Types... Args) inline static
Definition at line 21 of file RigVMTreeToolkitContext.h.
DECLARE_EVENT_OneParam()
FRigVMTreeContext::DECLARE_EVENT_OneParam (FRigVMTreeContext , FLogTokenizedMessage , const TSharedRef< FTokenizedMessage > &) const &
References DECLARE_EVENT_OneParam(), and LogMessage().
Referenced by DECLARE_EVENT_OneParam().
FiltersNode()
bool FRigVMTreeContext::FiltersNode (TSharedRef< FRigVMTreeNode > InNode) const
References FiltersNode().
Referenced by FiltersNode().
FindAssetFromAnyPath()
FAssetData FRigVMTreeContext::FindAssetFromAnyPath (const FString & InPartialOrFullPath, bool bUseRootPath) static
References FindAssetFromAnyPath().
Referenced by FindAssetFromAnyPath().
GetType()
virtual FName FRigVMTreeContext::GetType () const inline override virtual
Reimplemented from FRigVMTreeElement.
Definition at line 21 of file RigVMTreeToolkitContext.h.
GetVisibleChildrenHash()
virtual uint32 FRigVMTreeContext::GetVisibleChildrenHash () const virtual
Reimplemented in FRigVMSwapAssetReferencesContext, and FRigVMSwapFunctionContext.
References GetVisibleChildrenHash().
Referenced by GetVisibleChildrenHash().
IsOfType()
virtual bool FRigVMTreeContext::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeElement.
Definition at line 21 of file RigVMTreeToolkitContext.h.
LogError() [1/2]
void FRigVMTreeContext::LogError (const FString & InString) const
References LogError().
LogError() [2/2]
void FRigVMTreeContext::LogError (const FText & InText) const
References LogError().
Referenced by LogError(), and LogError().
LogMessage() [1/2]
void FRigVMTreeContext::LogMessage (const FString & InString) const
References LogMessage().
LogMessage() [2/2]
void FRigVMTreeContext::LogMessage (const FText & InText) const
References LogMessage().
Referenced by DECLARE_EVENT_OneParam(), LogMessage(), and LogMessage().
LogWarning() [1/2]
void FRigVMTreeContext::LogWarning (const FString & InString) const
References LogWarning().
LogWarning() [2/2]
void FRigVMTreeContext::LogWarning (const FText & InText) const
References LogWarning().
Referenced by LogWarning(), and LogWarning().
ToSharedPtr()
TSharedPtr< FRigVMTreeContext > FRigVMTreeContext::ToSharedPtr () const inline
Definition at line 21 of file RigVMTreeToolkitContext.h.
ToSharedRef()
TSharedRef< FRigVMTreeContext > FRigVMTreeContext::ToSharedRef () const inline
Definition at line 21 of file RigVMTreeToolkitContext.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeContext > & InElement) friend
Definition at line 21 of file RigVMTreeToolkitContext.h.
References FRigVMTreeElement::FRigVMTreeElement().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeContext > & InElement) friend
Definition at line 21 of file RigVMTreeToolkitContext.h.
FRigVMTreePhase
friend class FRigVMTreePhase friend
Definition at line 43 of file RigVMTreeToolkitContext.h.
References FRigVMTreePhase.
Referenced by FRigVMTreePhase.
SRigVMBulkEditWidget
friend class SRigVMBulkEditWidget friend
Definition at line 44 of file RigVMTreeToolkitContext.h.
References SRigVMBulkEditWidget.
Referenced by SRigVMBulkEditWidget.
Field Documentation
Filters
TArray<TSharedRef<FRigVMTreeFilter> > FRigVMTreeContext::Filters
Definition at line 26 of file RigVMTreeToolkitContext.h.
HashOffset
uint32 FRigVMTreeContext::HashOffset = 0 private
Definition at line 40 of file RigVMTreeToolkitContext.h.
OnLogTokenizedMessage
FLogTokenizedMessage FRigVMTreeContext::OnLogTokenizedMessage private
Definition at line 41 of file RigVMTreeToolkitContext.h.
Type
const FLazyName FRigVMTreeContext::Type = FLazyName(TEXT("FRigVMTreeContext")) inline static
Definition at line 21 of file RigVMTreeToolkitContext.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitContext.h