Unreal Engine 5.6 C++ API: UE::Geometry::IMeshSpatial Class Reference
UE::Geometry::IMeshSpatial Class Reference abstract
IMeshSpatial is an extension of ISpatial specifically for meshes.
#include "SpatialInterfaces.h"
Data Structures
struct FQueryOptions
Public Member Functions
virtual ~IMeshSpatial ()=default
virtual bool FindAllHitTriangles (const FRay3d &Ray, TArray< MeshIntersection::FHitIntersectionResult > &OutHits, const FQueryOptions &Options=FQueryOptions()) const =0
Find all triangles intersected by the given ray sorted by distance.
virtual int FindNearestHitTriangle (const FRay3d &Ray, const FQueryOptions &Options=FQueryOptions()) const
virtual bool FindNearestHitTriangle (const FRay3d &Ray, double &NearestT, int &TID, const FQueryOptions &Options=FQueryOptions()) const
Find nearest triangle from the given ray.
virtual bool FindNearestHitTriangle (const FRay3d &Ray, double &NearestT, int &TID, FVector3d &BaryCoords, const FQueryOptions &Options=FQueryOptions()) const =0
Find nearest triangle from the given ray.
virtual int FindNearestTriangle (const FVector3d &Point, double &NearestDistSqrOut, const FQueryOptions &Options=FQueryOptions()) const =0
virtual bool SupportsNearestTriangle () const =0
virtual bool SupportsTriangleRayIntersection () const =0
Public Member Functions inherited from UE::Geometry::ISpatial
virtual ~ISpatial ()=default
virtual bool IsInside (const FVector3d &Point) const =0
virtual bool SupportsPointContainment () const =0
Detailed Description
IMeshSpatial is an extension of ISpatial specifically for meshes.
Definition at line 50 of file SpatialInterfaces.h.
Constructor & Destructor Documentation
~IMeshSpatial()
virtual UE::Geometry::IMeshSpatial::~IMeshSpatial () virtual default
Member Function Documentation
FindAllHitTriangles()
virtual bool UE::Geometry::IMeshSpatial::FindAllHitTriangles (const FRay3d & Ray, TArray< MeshIntersection::FHitIntersectionResult > & OutHits, const FQueryOptions & Options = FQueryOptions()) const pure virtual
Find all triangles intersected by the given ray sorted by distance.
Parameters
Ray query ray
OutHits returned-by-reference hit infos sorted by distance
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Implemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >, UE::Geometry::TMeshAABBTree3< UE::Geometry::FColliderMesh >, and UE::Geometry::TMeshAABBTree3< UE::Geometry::FDynamicMeshUVMesh >.
References UE::Geometry::Options, and Ray.
FindNearestHitTriangle() [1/3]
virtual int UE::Geometry::IMeshSpatial::FindNearestHitTriangle (const FRay3d & Ray, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Parameters
Ray query ray
Options Query options (ex. max distance)
Returns
ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
Reimplemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >, UE::Geometry::TMeshAABBTree3< UE::Geometry::FColliderMesh >, and UE::Geometry::TMeshAABBTree3< UE::Geometry::FDynamicMeshUVMesh >.
Definition at line 104 of file SpatialInterfaces.h.
References FindNearestHitTriangle(), UE::Geometry::Options, and Ray.
Referenced by FindNearestHitTriangle(), and FindNearestHitTriangle().
FindNearestHitTriangle() [2/3]
virtual bool UE::Geometry::IMeshSpatial::FindNearestHitTriangle (const FRay3d & Ray, double & NearestT, int & TID, const FQueryOptions & Options = FQueryOptions()) const inline virtual
Find nearest triangle from the given ray.
Parameters
Ray query ray
NearestT returned-by-reference parameter of the nearest hit
TID returned-by-reference ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Reimplemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >.
Definition at line 120 of file SpatialInterfaces.h.
References FindNearestHitTriangle(), UE::Geometry::Options, and Ray.
FindNearestHitTriangle() [3/3]
virtual bool UE::Geometry::IMeshSpatial::FindNearestHitTriangle (const FRay3d & Ray, double & NearestT, int & TID, FVector3d & BaryCoords, const FQueryOptions & Options = FQueryOptions()) const pure virtual
Find nearest triangle from the given ray.
Parameters
Ray query ray
NearestT returned-by-reference parameter of the nearest hit
TID returned-by-reference ID of triangle intersected by ray within MaxDistance, or InvalidID if not found
BaryCoords returned-by-reference Barycentric coordinates of the triangle intersected by ray within MaxDistance, or FVector3d::Zero if not found.
Options Query options (ex. max distance)
Returns
true if hit, false if no hit found
Implemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >.
References UE::Geometry::Options, and Ray.
FindNearestTriangle()
virtual int UE::Geometry::IMeshSpatial::FindNearestTriangle (const FVector3d & Point, double & NearestDistSqrOut, const FQueryOptions & Options = FQueryOptions()) const pure virtual
Parameters
Query point
NearestDistSqrOut returned nearest squared distance, if triangle is found
Options Query options (ex. max distance)
Returns
ID of triangle nearest to Point within MaxDistance, or InvalidID if not found
Implemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >, UE::Geometry::TMeshAABBTree3< UE::Geometry::FColliderMesh >, and UE::Geometry::TMeshAABBTree3< UE::Geometry::FDynamicMeshUVMesh >.
References UE::Geometry::Options, and Point.
SupportsNearestTriangle()
virtual bool UE::Geometry::IMeshSpatial::SupportsNearestTriangle () const pure virtual
Returns
true if this object supports nearest-triangle queries
Implemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >, UE::Geometry::TMeshAABBTree3< UE::Geometry::FColliderMesh >, and UE::Geometry::TMeshAABBTree3< UE::Geometry::FDynamicMeshUVMesh >.
SupportsTriangleRayIntersection()
virtual bool UE::Geometry::IMeshSpatial::SupportsTriangleRayIntersection () const pure virtual
Returns
true if this object supports ray-triangle intersection queries
Implemented in UE::Geometry::TMeshAABBTree3< TriangleMeshType >, UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >, UE::Geometry::TMeshAABBTree3< UE::Geometry::FColliderMesh >, and UE::Geometry::TMeshAABBTree3< UE::Geometry::FDynamicMeshUVMesh >.
The documentation for this class was generated from the following file:
SpatialInterfaces.h