Unreal Engine 5.6 C++ API: ALight Class Reference
ALight Class Reference
#include "Light.h"
Public Member Functions
virtual void CheckForErrors () override
virtual void Destroyed () override
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
class ULightComponent * GetLightComponent () const
Returns LightComponent subobject.
virtual bool IsLevelBoundsRelevant () const override
bool IsToggleable () const
Return whether the light supports being toggled off and on on-the-fly.
virtual void PostLoad () override
void SetMobility (EComponentMobility::Type InMobility)
Function to change mobility type of light.
UPROPERTY() uint32 bEnabled UFUNCTION () 1 virtual void OnRep_bEnabled()
replicated copy of LightComponent's bEnabled property
UFUNCTION ()) 1 bool IsEnabled() const
UFUNCTION ()) 1 FLinearColor GetLightColor() const
UFUNCTION ()) 1 float GetBrightness() const
UFUNCTION ()) 1 void SetAffectTranslucentLighting(bool bNewValue)
UFUNCTION ()) 1 void SetBrightness(float NewBrightness)
UFUNCTION ()) 1 void SetCastShadows(bool bNewValue)
UFUNCTION ()) 1 void SetEnabled(bool bSetEnabled)
UFUNCTION ()) 1 void SetLightColor(FLinearColor NewLightColor)
UFUNCTION ()) 1 void SetLightFunctionFadeDistance(float NewLightFunctionFadeDistance)
UFUNCTION ()) 1 void SetLightFunctionMaterial(UMaterialInterface *NewLightFunctionMaterial)
UFUNCTION ()) 1 void SetLightFunctionScale(FVector NewLightFunctionScale)
UFUNCTION ()) 1 void ToggleEnabled()
Detailed Description
Definition at line 13 of file Light.h.
Member Function Documentation
CheckForErrors()
virtual void ALight::CheckForErrors () override virtual
Destroyed()
virtual void ALight::Destroyed () override virtual
GetLifetimeReplicatedProps()
virtual void ALight::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Todo
document
GetLightComponent()
class ULightComponent * ALight::GetLightComponent () const inline
Returns LightComponent subobject.
Definition at line 85 of file Light.h.
IsLevelBoundsRelevant()
virtual bool ALight::IsLevelBoundsRelevant () const inline override virtual
Definition at line 81 of file Light.h.
IsToggleable()
bool ALight::IsToggleable () const
Return whether the light supports being toggled off and on on-the-fly.
PostLoad()
virtual void ALight::PostLoad () override virtual
References PostLoad().
Referenced by PostLoad().
SetMobility()
void ALight::SetMobility (EComponentMobility::Type InMobility)
Function to change mobility type of light.
References SetMobility().
Referenced by SetMobility().
UFUNCTION() [1/13]
UPROPERTY() uint32 bEnabled ALight::UFUNCTION ()
replicated copy of LightComponent's bEnabled property
Replication Notification Callbacks
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/13]
ALight::UFUNCTION () const
References Category, meta, and UFUNCTION().
UFUNCTION() [3/13]
ALight::UFUNCTION () const
References Category, meta, and UFUNCTION().
UFUNCTION() [4/13]
ALight::UFUNCTION () const
References Category, meta, and UFUNCTION().
UFUNCTION() [5/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [6/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [7/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [8/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [9/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [10/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [11/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [12/13]
ALight::UFUNCTION ()
References Category, FVector, meta, and UFUNCTION().
UFUNCTION() [13/13]
ALight::UFUNCTION ()
References Category, meta, and UFUNCTION().
The documentation for this class was generated from the following file:
Light.h