Unreal Engine 5.6 C++ API: FMemoryImageName Struct Reference
FMemoryImageName Struct Reference
Predictably sized structure for representing an FName in memory images while allowing the size to be smaller than FScriptName when case-preserving behavior is not required.
#include "NameTypes.h"
Public Member Functions
FMemoryImageName ()
FORCEINLINE FMemoryImageName (const FName &Name)
FMemoryImageName (EName Name)
FORCEINLINE bool IsNone () const
bool operator== (EName Name) const
FString ToString () const
Data Fields
friend FName
Private Attributes
FNameEntryId ComparisonIndex
Encoded address of name entry (used to find String portion of the string/number pair used for comparison)
uint32 Number = 0
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Friends
void Freeze::ApplyMemoryImageNamePatch (void *NameDst, const FMemoryImageName &Name, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const FMemoryImageName &Object, void *OutDst)
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const FMemoryImageName &Object, const FTypeLayoutDesc &)
FORCEINLINE uint32 GetTypeHash (FMemoryImageName Name)
FORCEINLINE bool operator!= (FMemoryImageName Lhs, FMemoryImageName Rhs)
FORCEINLINE bool operator== (FMemoryImageName Lhs, FMemoryImageName Rhs)
Detailed Description
Predictably sized structure for representing an FName in memory images while allowing the size to be smaller than FScriptName when case-preserving behavior is not required.
Definition at line 513 of file NameTypes.h.
Constructor & Destructor Documentation
FMemoryImageName() [1/3]
FORCEINLINE FMemoryImageName::FMemoryImageName ()
Definition at line 1391 of file NameTypes.h.
References FMemoryImageName(), ComparisonIndex, FORCEINLINE, Number, and STRUCT_OFFSET.
Referenced by FMemoryImageName(), FMemoryImageName(), Freeze::ApplyMemoryImageNamePatch, Freeze::IntrinsicUnfrozenCopy, Freeze::IntrinsicWriteMemoryImage, GetTypeHash, operator!=, operator==(), and operator==.
FMemoryImageName() [2/3]
FORCEINLINE FMemoryImageName::FMemoryImageName (EName Name)
Definition at line 1407 of file NameTypes.h.
References FMemoryImageName(), FName, FORCEINLINE, and Name.
FMemoryImageName() [3/3]
FORCEINLINE FMemoryImageName::FMemoryImageName (const FName & Name)
Definition at line 1534 of file NameTypes.h.
References ComparisonIndex, FName, FORCEINLINE, Name, Number, and WITH_CASE_PRESERVING_NAME.
Member Function Documentation
IsNone()
FORCEINLINE bool FMemoryImageName::IsNone () const
Definition at line 1558 of file NameTypes.h.
References ComparisonIndex, FORCEINLINE, NAME_NO_NUMBER_INTERNAL, and Number.
operator==()
bool FMemoryImageName::operator== (EName Name) const inline
Definition at line 525 of file NameTypes.h.
References FMemoryImageName(), and Name.
ToString()
FString FMemoryImageName::ToString () const
Friends And Related Symbol Documentation
Freeze::ApplyMemoryImageNamePatch
void Freeze::ApplyMemoryImageNamePatch (void * NameDst, const FMemoryImageName & Name, const FPlatformTypeLayoutParameters & LayoutParams) friend
References FMemoryImageName(), and Name.
Freeze::IntrinsicUnfrozenCopy
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const FMemoryImageName & Object, void * OutDst) friend
References FMemoryImageName(), FName, FORCEINLINE, Name, and Object.
Freeze::IntrinsicWriteMemoryImage
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const FMemoryImageName & Object, const FTypeLayoutDesc &) friend
References FMemoryImageName(), and Object.
GetTypeHash
FORCEINLINE uint32 GetTypeHash (FMemoryImageName Name) friend
Definition at line 559 of file NameTypes.h.
References FMemoryImageName(), FORCEINLINE, GetTypeHash, and Name.
Referenced by GetTypeHash.
operator!=
FORCEINLINE bool operator!= (FMemoryImageName Lhs, FMemoryImageName Rhs) friend
Definition at line 564 of file NameTypes.h.
References FMemoryImageName(), and FORCEINLINE.
operator==
FORCEINLINE bool operator== (FMemoryImageName Lhs, FMemoryImageName Rhs) friend
Definition at line 555 of file NameTypes.h.
References FMemoryImageName(), ComparisonIndex, FORCEINLINE, and Number.
Field Documentation
ComparisonIndex
FNameEntryId FMemoryImageName::ComparisonIndex private
Encoded address of name entry (used to find String portion of the string/number pair used for comparison)
Definition at line 533 of file NameTypes.h.
Referenced by FMemoryImageName(), FMemoryImageName(), IsNone(), and operator==.
FName
friend FMemoryImageName::FName
Definition at line 515 of file NameTypes.h.
Referenced by FMemoryImageName(), FMemoryImageName(), and Freeze::IntrinsicUnfrozenCopy.
Number
uint32 FMemoryImageName::Number = 0 private
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Definition at line 538 of file NameTypes.h.
Referenced by FMemoryImageName(), FMemoryImageName(), IsNone(), and operator==.
The documentation for this struct was generated from the following file:
NameTypes.h