Unreal Engine 5.6 C++ API: TAsyncRunnable< ResultType > Class Template Reference
TAsyncRunnable< ResultType > Class Template Reference
Template for asynchronous functions that are executed in a separate thread.
#include "Async.h"
Public Member Functions
TAsyncRunnable (TUniqueFunction< ResultType()> &&InFunction, TPromise< ResultType > &&InPromise, TFuture< FRunnableThread * > &&InThreadFuture)
Creates and initializes a new instance.
virtual uint32 Run () override
Runs the runnable object.
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual class FSingleThreadRunnable * GetSingleThreadInterface ()
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
virtual bool Init ()
Initializes the runnable object.
virtual void Stop ()
Stops the runnable object.
Private Attributes
TUniqueFunction< ResultType()> Function
The function to execute on the Task Graph.
TPromise< ResultType > Promise
The promise to assign the result to.
TFuture< FRunnableThread * > ThreadFuture
The thread running this task.
Detailed Description
template<typename ResultType>
class TAsyncRunnable< ResultType >
Template for asynchronous functions that are executed in a separate thread.
Definition at line 173 of file Async.h.
Constructor & Destructor Documentation
TAsyncRunnable()
template<typename ResultType> TAsyncRunnable< ResultType >::TAsyncRunnable (TUniqueFunction< ResultType()> && InFunction, TPromise< ResultType > && InPromise, TFuture< FRunnableThread * > && InThreadFuture) inline
Creates and initializes a new instance.
Parameters
InFunction The function to execute asynchronously.
InPromise The promise object used to return the function's result.
InThreadFuture The thread that is running this task.
Definition at line 185 of file Async.h.
References Function, MoveTemp(), Promise, and ThreadFuture.
Member Function Documentation
Run()
template<typename ResultType> uint32 TAsyncRunnable< ResultType >::Run () override virtual
Runs the runnable object.
This is where all per object thread work is done. This is only called if the initialization was successful.
Returns
The exit code of the runnable object
See also
Init, Stop, Exit
Implements FRunnable.
Definition at line 469 of file Async.h.
References Async, Function, Promise, SetPromise(), TaskGraph, Thread, and ThreadFuture.
Field Documentation
Function
template<typename ResultType> TUniqueFunction<ResultType()> TAsyncRunnable< ResultType >::Function private
The function to execute on the Task Graph.
Definition at line 200 of file Async.h.
Referenced by TAsyncRunnable(), and Run().
Promise
template<typename ResultType> TPromise<ResultType> TAsyncRunnable< ResultType >::Promise private
The promise to assign the result to.
Definition at line 203 of file Async.h.
Referenced by TAsyncRunnable(), and Run().
ThreadFuture
template<typename ResultType> TFuture<FRunnableThread*> TAsyncRunnable< ResultType >::ThreadFuture private
The thread running this task.
Definition at line 206 of file Async.h.
Referenced by TAsyncRunnable(), and Run().
The documentation for this class was generated from the following file:
Async.h