Unreal Engine 5.6 C++ API: FVectorDistribution Class Reference
FVectorDistribution Class Reference
Raw distribution from which three floats can be looked up per entry.
#include "Distributions.h"
Public Member Functions
FVectorDistribution ()
Default constructor.
FORCEINLINE void GetRandomValue (float Time, float *RESTRICT OutValue, FRandomStream &RandomStream) const
Samples a value randomly distributed between two values.
void GetRange (FVector3d *OutMin, FVector3d *OutMax)
void GetRange (FVector3f *OutMin, FVector3f *OutMax)
Computes the range of the distribution.
FORCEINLINE void GetValue (float Time, float *RESTRICT OutValue) const
Samples a value from the distribution.
Private Attributes
FDistributionLookupTable LookupTable
The lookup table.
Friends
class FComposableDistribution
This distribution is built from composable distributions.
Detailed Description
Raw distribution from which three floats can be looked up per entry.
Definition at line 321 of file Distributions.h.
Constructor & Destructor Documentation
FVectorDistribution()
FVectorDistribution::FVectorDistribution ()
Default constructor.
Member Function Documentation
GetRandomValue()
FORCEINLINE void FVectorDistribution::GetRandomValue (float Time, float *RESTRICT OutValue, FRandomStream & RandomStream) const inline
Samples a value randomly distributed between two values.
Parameters
Time - Time at which to sample the distribution.
OutValue - Upon return contains the sampled value.
RandomStream - Random stream from which to retrieve random fractions.
Definition at line 352 of file Distributions.h.
References Alpha, checkDistribution, FORCEINLINE, FMath::Lerp(), LookupTable, RandomStream, RESTRICT, and Time.
GetRange() [1/2]
void FVectorDistribution::GetRange (FVector3d * OutMin, FVector3d * OutMax) inline
Definition at line 393 of file Distributions.h.
References GetRange().
GetRange() [2/2]
void FVectorDistribution::GetRange (FVector3f * OutMin, FVector3f * OutMax) inline
Computes the range of the distribution.
Parameters
OutMin - The minimum value in the distribution.
OutMax - The maximum value in the distribution.
Definition at line 387 of file Distributions.h.
References LookupTable.
Referenced by GetRange().
GetValue()
FORCEINLINE void FVectorDistribution::GetValue (float Time, float *RESTRICT OutValue) const inline
Samples a value from the distribution.
Parameters
Time - Time at which to sample the distribution.
OutValue - Upon return contains the sampled value.
Definition at line 332 of file Distributions.h.
References Alpha, checkDistribution, FORCEINLINE, FMath::Lerp(), LookupTable, RESTRICT, and Time.
Friends And Related Symbol Documentation
FComposableDistribution
friend class FComposableDistribution friend
This distribution is built from composable distributions.
Definition at line 406 of file Distributions.h.
References FComposableDistribution.
Referenced by FComposableDistribution.
Field Documentation
LookupTable
FDistributionLookupTable FVectorDistribution::LookupTable private
The lookup table.
Definition at line 403 of file Distributions.h.
Referenced by GetRandomValue(), GetRange(), and GetValue().
The documentation for this class was generated from the following file:
Distributions.h