Unreal Engine 5.6 C++ API: TActorDescViewMap< Type > Class Template Reference
TActorDescViewMap< Type > Class Template Reference
#include "WorldPartitionActorDescViewMap.h"
Public Member Functions
TActorDescViewMap ()
TActorDescViewMap (const TActorDescViewMap &)=delete
TActorDescViewMap (TActorDescViewMap &&)=default
Type * Emplace (const FGuid &InActorGuid, const Type &InActorDescView)
Type * Emplace (const FWorldPartitionActorDesc *InActorDesc)
template<class ClassType>
TArray< const Type * > FindByExactNativeClass () const
TArray< const Type * > FindByExactNativeClass (UClass *InExactNativeClass) const
const Type * FindByGuid (const FGuid &InGuid) const
const Type & FindByGuidChecked (const FGuid &InGuid) const
template<class Func>
void ForEachActorDescView (Func InFunc) const
const TMap< FGuid, Type * > & GetActorDescViewsByGuid () const
FORCEINLINE int32 Num () const
TActorDescViewMap & operator= (const TActorDescViewMap &)=delete
TActorDescViewMap & operator= (TActorDescViewMap &&)=default
Protected Attributes
TArray< TUniquePtr< Type > > ActorDescViewList
TMultiMap< FName, const Type * > ActorDescViewsByClass
TMap< FGuid, Type * > ActorDescViewsByGuid
Private Member Functions
Type * FindByGuid (const FGuid &InGuid)
Type & FindByGuidChecked (const FGuid &InGuid)
template<class Func>
void ForEachActorDescView (Func InFunc)
Friends
class FWorldPartitionStreamingGenerator
Detailed Description
template<class Type>
class TActorDescViewMap< Type >
Definition at line 10 of file WorldPartitionActorDescViewMap.h.
Constructor & Destructor Documentation
TActorDescViewMap() [1/3]
template<class Type> TActorDescViewMap< Type >::TActorDescViewMap () inline
Definition at line 44 of file WorldPartitionActorDescViewMap.h.
Referenced by TActorDescViewMap(), TActorDescViewMap(), operator=(), and operator=().
TActorDescViewMap() [2/3]
template<class Type> TActorDescViewMap< Type >::TActorDescViewMap (const TActorDescViewMap< Type > &) delete
References TActorDescViewMap().
TActorDescViewMap() [3/3]
template<class Type> TActorDescViewMap< Type >::TActorDescViewMap (TActorDescViewMap< Type > &&) default
References TActorDescViewMap().
Member Function Documentation
Emplace() [1/2]
template<class Type> Type * TActorDescViewMap< Type >::Emplace (const FGuid & InActorGuid, const Type & InActorDescView) inline
Definition at line 53 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewList, ActorDescViewsByClass, ActorDescViewsByGuid, and MakeUnique().
Referenced by Emplace().
Emplace() [2/2]
template<class Type> Type * TActorDescViewMap< Type >::Emplace (const FWorldPartitionActorDesc * InActorDesc) inline
Definition at line 66 of file WorldPartitionActorDescViewMap.h.
References Emplace(), and FWorldPartitionActorDesc::GetGuid().
FindByExactNativeClass() [1/2]
template<class Type> template<class ClassType> TArray< const Type * > TActorDescViewMap< Type >::FindByExactNativeClass () const inline
Definition at line 105 of file WorldPartitionActorDescViewMap.h.
References FindByExactNativeClass().
Referenced by FindByExactNativeClass().
FindByExactNativeClass() [2/2]
template<class Type> TArray< const Type * > TActorDescViewMap< Type >::FindByExactNativeClass (UClass * InExactNativeClass) const inline
Definition at line 110 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByClass, check, UObjectBase::GetFName(), and UObjectBaseUtility::IsNative().
FindByGuid() [1/2]
template<class Type> Type * TActorDescViewMap< Type >::FindByGuid (const FGuid & InGuid) inline private
Definition at line 29 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByGuid.
FindByGuid() [2/2]
template<class Type> const Type * TActorDescViewMap< Type >::FindByGuid (const FGuid & InGuid) const inline
Definition at line 90 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByGuid.
FindByGuidChecked() [1/2]
template<class Type> Type & TActorDescViewMap< Type >::FindByGuidChecked (const FGuid & InGuid) inline private
Definition at line 38 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByGuid.
FindByGuidChecked() [2/2]
template<class Type> const Type & TActorDescViewMap< Type >::FindByGuidChecked (const FGuid & InGuid) const inline
Definition at line 99 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByGuid.
ForEachActorDescView() [1/2]
template<class Type> template<class Func> void TActorDescViewMap< Type >::ForEachActorDescView (Func InFunc) inline private
Definition at line 16 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewList.
ForEachActorDescView() [2/2]
template<class Type> template<class Func> void TActorDescViewMap< Type >::ForEachActorDescView (Func InFunc) const inline
Definition at line 77 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewList.
GetActorDescViewsByGuid()
template<class Type> const TMap< FGuid, Type * > & TActorDescViewMap< Type >::GetActorDescViewsByGuid () const inline
Definition at line 119 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewsByGuid.
Num()
template<class Type> FORCEINLINE int32 TActorDescViewMap< Type >::Num () const inline
Definition at line 71 of file WorldPartitionActorDescViewMap.h.
References ActorDescViewList, and FORCEINLINE.
operator=() [1/2]
template<class Type> TActorDescViewMap & TActorDescViewMap< Type >::operator= (const TActorDescViewMap< Type > &) delete
References TActorDescViewMap().
operator=() [2/2]
template<class Type> TActorDescViewMap & TActorDescViewMap< Type >::operator= (TActorDescViewMap< Type > &&) default
References TActorDescViewMap().
Friends And Related Symbol Documentation
FWorldPartitionStreamingGenerator
template<class Type> friend class FWorldPartitionStreamingGenerator friend
Definition at line 12 of file WorldPartitionActorDescViewMap.h.
References FWorldPartitionStreamingGenerator.
Referenced by FWorldPartitionStreamingGenerator.
Field Documentation
ActorDescViewList
template<class Type> TArray<TUniquePtr<Type> > TActorDescViewMap< Type >::ActorDescViewList protected
Definition at line 122 of file WorldPartitionActorDescViewMap.h.
Referenced by Emplace(), ForEachActorDescView(), ForEachActorDescView(), and Num().
ActorDescViewsByClass
template<class Type> TMultiMap<FName, const Type*> TActorDescViewMap< Type >::ActorDescViewsByClass protected
Definition at line 125 of file WorldPartitionActorDescViewMap.h.
Referenced by Emplace(), and FindByExactNativeClass().
ActorDescViewsByGuid
template<class Type> TMap<FGuid, Type*> TActorDescViewMap< Type >::ActorDescViewsByGuid protected
Definition at line 124 of file WorldPartitionActorDescViewMap.h.
Referenced by Emplace(), FindByGuid(), FindByGuid(), FindByGuidChecked(), FindByGuidChecked(), and GetActorDescViewsByGuid().
The documentation for this class was generated from the following file:
WorldPartitionActorDescViewMap.h