Unreal Engine 5.6 C++ API: EnumClassFlags.h File Reference
EnumClassFlags.h File Reference
Macros
#define ENUM_CLASS_FLAGS(Enum)
#define FRIEND_ENUM_CLASS_FLAGS(Enum)
Functions
template<typename Enum>
void EnumAddFlags (Enum &Flags, Enum FlagsToAdd)
template<typename Enum>
constexpr bool EnumHasAllFlags (Enum Flags, Enum Contains)
template<typename Enum>
constexpr bool EnumHasAnyFlags (Enum Flags, Enum Contains)
template<typename Enum>
void EnumRemoveFlags (Enum &Flags, Enum FlagsToRemove)
Macro Definition Documentation
ENUM_CLASS_FLAGS
#define ENUM_CLASS_FLAGS (Enum)
Value:
    inline           Enum& operator|=(Enum& Lhs, Enum Rhs) { return Lhs = (Enum)((__underlying_type(Enum))Lhs | (__underlying_type(Enum))Rhs); } \
    inline           Enum& operator&=(Enum& Lhs, Enum Rhs) { return Lhs = (Enum)((__underlying_type(Enum))Lhs & (__underlying_type(Enum))Rhs); } \
    inline           Enum& operator^=(Enum& Lhs, Enum Rhs) { return Lhs = (Enum)((__underlying_type(Enum))Lhs ^ (__underlying_type(Enum))Rhs); } \
    inline constexpr Enum  operator| (Enum  Lhs, Enum Rhs) { return (Enum)((__underlying_type(Enum))Lhs | (__underlying_type(Enum))Rhs); } \
    inline constexpr Enum  operator& (Enum  Lhs, Enum Rhs) { return (Enum)((__underlying_type(Enum))Lhs & (__underlying_type(Enum))Rhs); } \
    inline constexpr Enum  operator^ (Enum  Lhs, Enum Rhs) { return (Enum)((__underlying_type(Enum))Lhs ^ (__underlying_type(Enum))Rhs); } \
    inline constexpr bool  operator! (Enum  E)             { return !(__underlying_type(Enum))E; } \
    inline constexpr Enum  operator~ (Enum  E)             { return (Enum)~(__underlying_type(Enum))E; }
Definition at line 6 of file EnumClassFlags.h.
Referenced by DECLARE_STATS_GROUP(), ENUM_CLASS_FLAGS(), and ENUM_CLASS_FLAGS().
FRIEND_ENUM_CLASS_FLAGS
#define FRIEND_ENUM_CLASS_FLAGS (Enum)
Value:
    friend           Enum& operator|=(Enum& Lhs, Enum Rhs); \
    friend           Enum& operator&=(Enum& Lhs, Enum Rhs); \
    friend           Enum& operator^=(Enum& Lhs, Enum Rhs); \
    friend constexpr Enum  operator| (Enum  Lhs, Enum Rhs); \
    friend constexpr Enum  operator& (Enum  Lhs, Enum Rhs); \
    friend constexpr Enum  operator^ (Enum  Lhs, Enum Rhs); \
    friend constexpr bool  operator! (Enum  E); \
    friend constexpr Enum  operator~ (Enum  E);
Definition at line 17 of file EnumClassFlags.h.
Function Documentation
EnumAddFlags()
template<typename Enum> void EnumAddFlags (Enum & Flags, Enum FlagsToAdd)
Definition at line 42 of file EnumClassFlags.h.
References Enum, and Flags.
Referenced by FMeshRenderBufferSet::FMeshRenderBufferSet(), FDisplayClusterShadersTextureUtilsSettings::AddFlags(), FMaterialKeyGeneratorContext::AddFlags(), UE::Insights::STableTreeView::AddInProgressAsyncOperation(), FAssetReferenceFilterContext::AddRole(), USTRUCT(), and FActionFilterTest::WithFlags().
EnumHasAllFlags()
template<typename Enum> bool EnumHasAllFlags (Enum Flags, Enum Contains) constexpr
Definition at line 28 of file EnumClassFlags.h.
References Enum, and Flags.
Referenced by FGCObject::FGCObject(), TRDGUniformBufferBinding< UniformBufferStructType >::TRDGUniformBufferBinding(), TUniformBufferBinding< UniformBufferStructType >::TUniformBufferBinding(), UE::Anim::FCurveUtils::BulkSet(), FNetworkPredictionServiceRegistry::ConditionalCallFuncOnService(), FAttributesSetBase::DoesAttributeHaveAllFlags(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), GetSimTickMask(), UClass::HasAllClassFlags(), FMaterialKeyGeneratorContext::HasAllFlags(), UE::PixelFormat::HasCapabilities(), FVertexFactoryType::HasFlags(), FSearchData::IsIndexingCompleted(), FSearchData::IsMarkedForDeletion(), FSlateDrawElement::IsPixelSnapped(), FCoreRedirect::IsPrefixMatch(), FCoreRedirect::IsSuffixMatch(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpToValid(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid(), UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray(), FRDGPooledBuffer::SetCommittedSize(), FWaterBodyQueryResult::SetWaveInfo(), LowLevelTasks::FTask::TryCancel(), TBaseBlendedCurve< InAllocatorType, InElementType >::UseMaxValue(), TBaseBlendedCurve< InAllocatorType, InElementType >::UseMinValue(), and UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::VisitUnlinkedEntities().
EnumHasAnyFlags()
template<typename Enum> bool EnumHasAnyFlags (Enum Flags, Enum Contains) constexpr
Definition at line 35 of file EnumClassFlags.h.
References Enum, and Flags.
Referenced by UE::AssetRegistry::FDependencyQuery::FDependencyQuery(), FGCObject::FGCObject(), FRDGPooledBuffer::FRDGPooledBuffer(), TFieldIterator< T >::TFieldIterator(), FVertexFactory::AccessStreamComponent(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FPixelShaderUtils::AddRasterizeToRectsPass(), LowLevelTasks::FTask::AllowBusyWaiting(), LowLevelTasks::FTask::AllowCancellation(), UE::Insights::FTableColumn::CanBeFiltered(), UE::Insights::FTableColumn::CanBeHidden(), TActorIteratorBase< FActorIterator >::CanIterateLevel(), TBaseBlendedCurve< InAllocatorType, InElementType >::Combine(), TBaseBlendedCurve< InAllocatorType, InElementType >::CombinePreserved(), TFObjectPropertyBase< InTCppType >::ContainsObjectReference(), UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), TManagedStoragePlatformFile< BaseClass >::CopyFile(), FAttributesSetBase::DoesAttributeHaveAnyFlags(), UE::Anim::FCurveUtils::ElementPassesFilter(), LowLevelTasks::FTask::ExecuteTask(), UE::Sequencer::FViewModelListIterator::FindNextValidIterator(), FNetworkPredictionServiceRegistry::ForEachService(), FPooledRenderTargetDesc::GenerateInfoString(), FLocalVertexFactory::GetColorOverrideStream(), FNetworkPredictionDriverBase< ModelDef >::GetConfig(), FNetworkPredictionDriverBase< ModelDef >::GetDefaultArchetype(), UE::Sequencer::FOutlinerSizing::GetSeparatorHeight(), FBuoyancyComponentSim::GetWaterHeight(), FWaterBodyQueryResult::GetWaveInfo(), FFieldClass::HasAnyClassFlags(), UClass::HasAnyClassFlags(), FDisplayClusterShadersTextureUtilsSettings::HasAnyFlags(), FDisplayClusterViewport_RenderSettings::HasAnyMediaStates(), FDisplayClusterViewport_TileSettings::HasAnyTileFlags(), SWidget::HasAnyUpdateFlags(), FPackageStoreEntryResource::HasCookError(), FCbFieldType::HasFieldName(), FCbFieldType::HasFieldType(), UE::MovieScene::FEntityGroupID::HasGroup(), UE::Insights::STableTreeView::HasInProgressAsyncOperation(), FPackageStoreEntryResource::HasOptionalSegment(), FPackageStoreEntryResource::HasPackageData(), UE::Serialization::FEditorBulkData::HasPayloadSidecarFile(), UE::Serialization::FEditorBulkData::HasPlaceholderPayloadId(), FAssetReferenceFilterContext::HasRole(), UScriptStruct::ICppStructOps::HasSerializerObjectReferences(), FArrayProperty::InitializeValueInternal(), FMapProperty::InitializeValueInternal(), FNetSimCueDispatcher::Invoke(), TActorIteratorBase< FActorIterator >::IsActorSuitable(), FPackageStoreEntryResource::IsAutoOptional(), LowLevelTasks::FTask::IsCompleted(), FRepLayout::IsCustomDeltaProperty(), IsCustomDeltaProperty(), UE::Serialization::FEditorBulkData::IsDataVirtualized(), UE::Insights::FTableColumn::IsDynamic(), FRepLayout::IsEmpty(), UE::Insights::FTableColumn::IsHierarchy(), FBufferOwner::IsImmutable(), FBufferOwner::IsMaterialized(), FBufferOwner::IsOwned(), LowLevelTasks::FTask::IsReady(), UE::Serialization::FEditorBulkData::IsReferencingByPackagePath(), UE::Serialization::FEditorBulkData::IsReferencingOldBulkData(), UE::Serialization::FEditorBulkData::IsReferencingWorkspaceDomain(), FRDGUniformBufferBinding::IsShader(), FUniformBufferBinding::IsShader(), FRDGUniformBufferBinding::IsStatic(), FUniformBufferBinding::IsStatic(), UE::Serialization::FEditorBulkData::IsStoredInPackageTrailer(), FPooledRenderTargetDesc::IsValid(), UE::SequenceNavigator::INavigationToolItem::IsViewModeSupported(), FCoreRedirect::IsWildcardMatch(), Algo::KahnTopologicalSort(), UE::MovieScene::FComponentRegistry::MakeComponentTypeInfoWithoutComponentOps(), TManagedStoragePlatformFile< BaseClass >::MoveFile(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), TNetSimCueDispatcher< ModelDef >::NetSendSavedCues(), UE::MovieScene::FComponentRegistry::NewComponentType(), UE::MovieScene::FComponentRegistry::NewComponentTypeNoAddReferencedObjects(), FNetworkPredictionServiceRegistry::RegisterInstance(), TStaticMeshVertexData< VertexDataType >::ResizeBuffer(), UE::Insights::FTableColumn::ShouldBeVisible(), ILocalizedTextSource::ShouldLoadAdditional(), ILocalizedTextSource::ShouldLoadEditor(), ILocalizedTextSource::ShouldLoadEngine(), ILocalizedTextSource::ShouldLoadGame(), ILocalizedTextSource::ShouldLoadNative(), ILocalizedTextSource::ShouldLoadNativeGameData(), UE::AnimNext::TLODPose< FDefaultAllocator >::ShouldPrepareForLOD(), FTabId::ShouldSaveLayout(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), LowLevelTasks::FTask::TryCancel(), LowLevelTasks::FTask::TryFinish(), TDirectoryTree< ValueType >::FTreeNode::TryGetChildren(), TDirectoryTree< ValueType >::TryGetChildren(), LowLevelTasks::FTask::TryPrepareLaunch(), LowLevelTasks::FTask::TryRevive(), FPersistentStorageCategory::TryUpdateQuota(), UCLASS(), UE::Anim::FNamedValueArrayUtils::Union(), USTRUCT(), FComputeShaderUtils::ValidateIndirectArgsBuffer(), LowLevelTasks::FTask::WasCanceled(), LowLevelTasks::FTask::WasCanceledOrIsExpediting(), and LowLevelTasks::FTask::WasExpedited().
EnumRemoveFlags()
template<typename Enum> void EnumRemoveFlags (Enum & Flags, Enum FlagsToRemove)
Definition at line 49 of file EnumClassFlags.h.
References Enum, and Flags.
Referenced by UE::AssetRegistry::FDependencyQuery::FDependencyQuery(), FDisplayClusterViewport_RenderSettingsICVFX::BeginUpdateSettings(), FMaterialKeyGeneratorContext::RemoveFlags(), FAssetReferenceFilterContext::RemoveRole(), and FRDGBarrierBatchBegin::SetUseCrossPipelineFence().