Unreal Engine 5.6 C++ API: FTextKey Class Reference
FTextKey Class Reference
Optimized representation of a case-sensitive string, as used by localization keys.
#include "TextKey.h"
Public Member Functions
FTextKey ()=default
FTextKey (const FString &InStr)
FTextKey (const TCHAR *InStr)
FTextKey (FStringView InStr)
void AppendString (FString &Out) const
void AppendString (FStringBuilderBase &Out) const
FORCEINLINE bool IsEmpty () const
Is this text key empty?
FORCEINLINE void Reset ()
Reset this text key to be empty.
void SerializeAsString (FArchive &Ar)
Serialize this text key as if it were an FString.
void SerializeAsString (FStructuredArchiveSlot Slot)
Serialize this text key as if it were an FString.
void SerializeDiscardHash (FArchive &Ar)
Serialize this text key including its hash value, discarding the hash on load (to upgrade from an older hashing algorithm)
void SerializeDiscardHash (FStructuredArchiveSlot Slot)
Serialize this text key including its hash value, discarding the hash on load (to upgrade from an older hashing algorithm)
void SerializeWithHash (FArchive &Ar)
Serialize this text key including its hash value (this method is sensitive to hashing algorithm changes, so only use it for generated files that can be rebuilt from another source)
void SerializeWithHash (FStructuredArchiveSlot Slot)
Serialize this text key including its hash value (this method is sensitive to hashing algorithm changes, so only use it for generated files that can be rebuilt from another source)
FString ToString () const
Convert this text key back to its string representation.
void ToString (FString &Out) const
void ToString (FStringBuilderBase &Out) const
UE_DEPRECATED (5.5, "GetChars is deprecated as FTextKey may now store its internal data as UTF-8. Use ToString/AppendString instead.") 1 const TCHAR *GetChars() const
Get the underlying chars buffer this text key represents.
Static Public Member Functions
static void CompactDataStructures ()
Compact any slack within the internal table.
static void TearDown ()
Do not use any FTextKey or FTextId after calling this.
Private Attributes
int32 Index = INDEX_NONE
Index of the internal FKeyData we reference.
Friends
class FTextKeyState
uint32 GetTypeHash (const FTextKey &A)
Get the hash of this text key.
FORCEINLINE bool operator!= (const FTextKey &A, const FTextKey &B)
Compare for inequality.
FORCEINLINE bool operator== (const FTextKey &A, const FTextKey &B)
Compare for equality.
Detailed Description
Optimized representation of a case-sensitive string, as used by localization keys.
This references an entry within a internal table to avoid memory duplication, as well as offering optimized comparison and hashing performance.
Definition at line 74 of file TextKey.h.
Constructor & Destructor Documentation
FTextKey() [1/4]
FTextKey::FTextKey () default
Referenced by GetTypeHash, operator!=, and operator==.
FTextKey() [2/4]
FTextKey::FTextKey (FStringView InStr)
FTextKey() [3/4]
FTextKey::FTextKey (const TCHAR * InStr)
FTextKey() [4/4]
FTextKey::FTextKey (const FString & InStr)
Member Function Documentation
AppendString() [1/2]
void FTextKey::AppendString (FString & Out) const
References AppendString().
Referenced by AppendString(), and AppendString().
AppendString() [2/2]
void FTextKey::AppendString (FStringBuilderBase & Out) const
References AppendString().
CompactDataStructures()
void FTextKey::CompactDataStructures () static
Compact any slack within the internal table.
IsEmpty()
FORCEINLINE bool FTextKey::IsEmpty () const inline
Is this text key empty?
Definition at line 127 of file TextKey.h.
References FORCEINLINE, Index, and INDEX_NONE.
Reset()
FORCEINLINE void FTextKey::Reset () inline
Reset this text key to be empty.
Definition at line 133 of file TextKey.h.
References FORCEINLINE, Index, and INDEX_NONE.
SerializeAsString() [1/2]
void FTextKey::SerializeAsString (FArchive & Ar)
Serialize this text key as if it were an FString.
References Ar.
SerializeAsString() [2/2]
void FTextKey::SerializeAsString (FStructuredArchiveSlot Slot)
Serialize this text key as if it were an FString.
SerializeDiscardHash() [1/2]
void FTextKey::SerializeDiscardHash (FArchive & Ar)
Serialize this text key including its hash value, discarding the hash on load (to upgrade from an older hashing algorithm)
References Ar.
SerializeDiscardHash() [2/2]
void FTextKey::SerializeDiscardHash (FStructuredArchiveSlot Slot)
Serialize this text key including its hash value, discarding the hash on load (to upgrade from an older hashing algorithm)
SerializeWithHash() [1/2]
void FTextKey::SerializeWithHash (FArchive & Ar)
Serialize this text key including its hash value (this method is sensitive to hashing algorithm changes, so only use it for generated files that can be rebuilt from another source)
References Ar.
SerializeWithHash() [2/2]
void FTextKey::SerializeWithHash (FStructuredArchiveSlot Slot)
Serialize this text key including its hash value (this method is sensitive to hashing algorithm changes, so only use it for generated files that can be rebuilt from another source)
TearDown()
void FTextKey::TearDown () static
Do not use any FTextKey or FTextId after calling this.
ToString() [1/3]
FString FTextKey::ToString () const
Convert this text key back to its string representation.
References ToString().
Referenced by ToString(), ToString(), and ToString().
ToString() [2/3]
void FTextKey::ToString (FString & Out) const
References ToString().
ToString() [3/3]
void FTextKey::ToString (FStringBuilderBase & Out) const
References ToString().
UE_DEPRECATED()
FTextKey::UE_DEPRECATED (5. 5, "GetChars is deprecated as FTextKey may now store its internal data as UTF-8. Use ToString/AppendString instead.") const
Get the underlying chars buffer this text key represents.
Friends And Related Symbol Documentation
FTextKeyState
friend class FTextKeyState friend
Definition at line 156 of file TextKey.h.
References FTextKeyState.
Referenced by FTextKeyState.
GetTypeHash
uint32 GetTypeHash (const FTextKey & A) friend
Get the hash of this text key.
References FTextKey(), and A.
operator!=
FORCEINLINE bool operator!= (const FTextKey & A, const FTextKey & B) friend
Compare for inequality.
Definition at line 100 of file TextKey.h.
References FTextKey(), A, B, and FORCEINLINE.
operator==
FORCEINLINE bool operator== (const FTextKey & A, const FTextKey & B) friend
Compare for equality.
Definition at line 94 of file TextKey.h.
References FTextKey(), A, B, and FORCEINLINE.
Field Documentation
Index
int32 FTextKey::Index = INDEX_NONE private
Index of the internal FKeyData we reference.
Definition at line 149 of file TextKey.h.
Referenced by IsEmpty(), and Reset().
The documentation for this class was generated from the following file:
TextKey.h