Unreal Engine 5.6 C++ API: UE::Geometry::TOrientedBox2< RealType > Struct Template Reference
UE::Geometry::TOrientedBox2< RealType > Struct Template Reference
#include "OrientedBoxTypes.h"
Public Member Functions
TOrientedBox2 ()
TOrientedBox2 (const TAxisAlignedBox2< RealType > &AxisBox)
Create oriented box from axis-aligned box.
TOrientedBox2 (const TVector2< RealType > &OriginIn, const TVector2< RealType > &ExtentsIn)
Create axis-aligned box with given Origin and Extents.
TOrientedBox2 (const TVector2< RealType > &OriginIn, const TVector2< RealType > &XAxisIn, const TVector2< RealType > &ExtentsIn)
Create oriented box with given Origin, X Axis and Extents.
TOrientedBox2 (const TVector2< RealType > &OriginIn, RealType AngleRad, const TVector2< RealType > &ExtentsIn)
Create oriented box with given Origin, Angle (in radians) and Extents.
RealType Area () const
TVector2< RealType > AxisX () const
TVector2< RealType > AxisY () const
TVector2< RealType > Center () const
TVector2< RealType > ClosestPoint (const TVector2< RealType > &Point) const
Find closest point on box.
bool Contains (const TVector2< RealType > &Point) const
TVector2< RealType > Diagonal () const
RealType DistanceSquared (const TVector2< RealType > &Point) const
Find squared distance to box.
template<typename PointFuncType>
void EnumerateCorners (PointFuncType CornerPointFunc) const
Call CornerPointFunc(TVector2<RealType>) for each of the 4 box corners.
TVector2< RealType > FromLocalSpace (const TVector2< RealType > &Point) const
TVector2< RealType > GetAxis (int AxisIndex) const
TVector2< RealType > GetCorner (int Index) const
RealType Perimeter () const
void SetAngleRadians (RealType AngleRad)
template<typename PointPredicateType>
bool TestCorners (PointPredicateType CornerPointPredicate) const
Call CornerPointPredicate(TVector2<RealType>) for each of the 4 box corners, with early-out if any call returns false.
TVector2< RealType > ToLocalSpace (const TVector2< RealType > &Point) const
Static Public Member Functions
static FIndex2i GetCornerSide (int Index)
Get whether the corner at Index (see GetCorner documentation comment) is in the negative or positive direction for each axis.
static TOrientedBox2< RealType > UnitPositive ()
static TOrientedBox2< RealType > UnitZeroCentered ()
Data Fields
TVector2< RealType > Extents
Half-dimensions of box measured along the two axes.
TVector2< RealType > Origin
TVector2< RealType > UnitAxisX
Detailed Description
template<typename RealType>
struct UE::Geometry::TOrientedBox2< RealType >
Definition at line 431 of file OrientedBoxTypes.h.
Constructor & Destructor Documentation
TOrientedBox2() [1/5]
template<typename RealType> UE::Geometry::TOrientedBox2< RealType >::TOrientedBox2 () inline
Definition at line 440 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox2< float >::UnitPositive(), and UE::Geometry::TOrientedBox2< float >::UnitZeroCentered().
TOrientedBox2() [2/5]
template<typename RealType> UE::Geometry::TOrientedBox2< RealType >::TOrientedBox2 (const TVector2< RealType > & OriginIn, const TVector2< RealType > & ExtentsIn) inline
Create axis-aligned box with given Origin and Extents.
Definition at line 445 of file OrientedBoxTypes.h.
TOrientedBox2() [3/5]
template<typename RealType> UE::Geometry::TOrientedBox2< RealType >::TOrientedBox2 (const TVector2< RealType > & OriginIn, const TVector2< RealType > & XAxisIn, const TVector2< RealType > & ExtentsIn) inline
Create oriented box with given Origin, X Axis and Extents.
Definition at line 453 of file OrientedBoxTypes.h.
TOrientedBox2() [4/5]
template<typename RealType> UE::Geometry::TOrientedBox2< RealType >::TOrientedBox2 (const TVector2< RealType > & OriginIn, RealType AngleRad, const TVector2< RealType > & ExtentsIn) inline
Create oriented box with given Origin, Angle (in radians) and Extents.
Definition at line 465 of file OrientedBoxTypes.h.
TOrientedBox2() [5/5]
template<typename RealType> UE::Geometry::TOrientedBox2< RealType >::TOrientedBox2 (const TAxisAlignedBox2< RealType > & AxisBox) inline
Create oriented box from axis-aligned box.
Definition at line 473 of file OrientedBoxTypes.h.
Member Function Documentation
Area()
template<typename RealType> RealType UE::Geometry::TOrientedBox2< RealType >::Area () const inline
Returns
area of box
Definition at line 509 of file OrientedBoxTypes.h.
AxisX()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::AxisX () const inline
Returns
X axis of the box
Definition at line 494 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox2< float >::Diagonal(), UE::Geometry::TOrientedBox2< float >::EnumerateCorners(), UE::Geometry::TOrientedBox2< float >::GetAxis(), and UE::Geometry::TOrientedBox2< float >::TestCorners().
AxisY()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::AxisY () const inline
Returns
Y axis of the box (the X axis rotated 90 degrees counter-clockwise)
Definition at line 497 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox2< float >::EnumerateCorners(), UE::Geometry::TOrientedBox2< float >::FromLocalSpace(), UE::Geometry::TOrientedBox2< float >::GetAxis(), UE::Geometry::TOrientedBox2< float >::GetCorner(), and UE::Geometry::TOrientedBox2< float >::TestCorners().
Center()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::Center () const inline
Returns
center of the box
Definition at line 491 of file OrientedBoxTypes.h.
ClosestPoint()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::ClosestPoint (const TVector2< RealType > & Point) const inline
Find closest point on box.
Parameters
Point input point
Returns
Closest point on box. Input point is returned if it is inside box.
Definition at line 622 of file OrientedBoxTypes.h.
Contains()
template<typename RealType> bool UE::Geometry::TOrientedBox2< RealType >::Contains (const TVector2< RealType > & Point) const inline
Returns
true if box contains point
Definition at line 534 of file OrientedBoxTypes.h.
Diagonal()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::Diagonal () const inline
Returns
vector from minimum-corner to maximum-corner of box
Definition at line 503 of file OrientedBoxTypes.h.
DistanceSquared()
template<typename RealType> RealType UE::Geometry::TOrientedBox2< RealType >::DistanceSquared (const TVector2< RealType > & Point) const inline
Find squared distance to box.
Parameters
Point input point
Returns
Squared distance from point to box, or 0 if point is inside box
Definition at line 608 of file OrientedBoxTypes.h.
EnumerateCorners()
template<typename RealType> template<typename PointFuncType> void UE::Geometry::TOrientedBox2< RealType >::EnumerateCorners (PointFuncType CornerPointFunc) const inline
Call CornerPointFunc(TVector2<RealType>) for each of the 4 box corners.
Order is the same as GetCorner(X).
Definition at line 561 of file OrientedBoxTypes.h.
FromLocalSpace()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::FromLocalSpace (const TVector2< RealType > & Point) const inline
Returns
Point transformed from the local space of the box (Origin at box center, Axes aligned to box)
Definition at line 528 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox2< float >::ClosestPoint().
GetAxis()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::GetAxis (int AxisIndex) const inline
Returns
an axis of the box
Definition at line 500 of file OrientedBoxTypes.h.
GetCorner()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::GetCorner (int Index) const inline
Parameters
Index corner index in range 0-3
Returns
Corner point on the box identified by the given index. Ordering is: [ (-x,-y), (x,-y), (x,y), (-x,y) ]
Definition at line 549 of file OrientedBoxTypes.h.
GetCornerSide()
template<typename RealType> FIndex2i UE::Geometry::TOrientedBox2< RealType >::GetCornerSide (int Index) inline static
Get whether the corner at Index (see GetCorner documentation comment) is in the negative or positive direction for each axis.
Parameters
Index corner index in range 0-4
Returns
Index2i with 0 or 1 for each axis, 0 if corner is in the negative direction for that axis, 1 if in the positive direction
Definition at line 592 of file OrientedBoxTypes.h.
Perimeter()
template<typename RealType> RealType UE::Geometry::TOrientedBox2< RealType >::Perimeter () const inline
Returns
perimeter of box
Definition at line 515 of file OrientedBoxTypes.h.
SetAngleRadians()
template<typename RealType> void UE::Geometry::TOrientedBox2< RealType >::SetAngleRadians (RealType AngleRad) inline
Definition at line 478 of file OrientedBoxTypes.h.
TestCorners()
template<typename RealType> template<typename PointPredicateType> bool UE::Geometry::TOrientedBox2< RealType >::TestCorners (PointPredicateType CornerPointPredicate) const inline
Call CornerPointPredicate(TVector2<RealType>) for each of the 4 box corners, with early-out if any call returns false.
Returns
true if all tests pass
Definition at line 576 of file OrientedBoxTypes.h.
ToLocalSpace()
template<typename RealType> TVector2< RealType > UE::Geometry::TOrientedBox2< RealType >::ToLocalSpace (const TVector2< RealType > & Point) const inline
Returns
Point transformed to the local space of the box (Origin at box center, Axes aligned to box)
Definition at line 521 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox2< float >::ClosestPoint(), UE::Geometry::TOrientedBox2< float >::Contains(), and UE::Geometry::TOrientedBox2< float >::DistanceSquared().
UnitPositive()
template<typename RealType> TOrientedBox2< RealType > UE::Geometry::TOrientedBox2< RealType >::UnitPositive () inline static
Returns
box with unit dimensions where minimum corner is at origin
Definition at line 487 of file OrientedBoxTypes.h.
UnitZeroCentered()
template<typename RealType> TOrientedBox2< RealType > UE::Geometry::TOrientedBox2< RealType >::UnitZeroCentered () inline static
Returns
box with unit dimensions centered at origin
Definition at line 484 of file OrientedBoxTypes.h.
Field Documentation
Extents
template<typename RealType> TVector2<RealType> UE::Geometry::TOrientedBox2< RealType >::Extents
Half-dimensions of box measured along the two axes.
Definition at line 438 of file OrientedBoxTypes.h.
Origin
template<typename RealType> TVector2<RealType> UE::Geometry::TOrientedBox2< RealType >::Origin
Definition at line 434 of file OrientedBoxTypes.h.
UnitAxisX
template<typename RealType> TVector2<RealType> UE::Geometry::TOrientedBox2< RealType >::UnitAxisX
Definition at line 436 of file OrientedBoxTypes.h.
The documentation for this struct was generated from the following file:
OrientedBoxTypes.h