Unreal Engine 5.6 C++ API: IModularFeatures::FScopedLockModularFeatureList Struct Reference
IModularFeatures::FScopedLockModularFeatureList Struct Reference
#include "IModularFeatures.h"
Public Member Functions
FScopedLockModularFeatureList ()
FScopedLockModularFeatureList (const FScopedLockModularFeatureList &)=delete
FScopedLockModularFeatureList (FScopedLockModularFeatureList &&)=delete
~FScopedLockModularFeatureList ()
FScopedLockModularFeatureList & operator= (const FScopedLockModularFeatureList &)=delete
FScopedLockModularFeatureList & operator= (FScopedLockModularFeatureList &&)=delete
Detailed Description
Definition at line 88 of file IModularFeatures.h.
Constructor & Destructor Documentation
FScopedLockModularFeatureList() [1/3]
IModularFeatures::FScopedLockModularFeatureList::FScopedLockModularFeatureList () inline
Definition at line 90 of file IModularFeatures.h.
References IModularFeatures::Get(), and IModularFeatures::LockModularFeatureList().
Referenced by FScopedLockModularFeatureList(), FScopedLockModularFeatureList(), operator=(), and operator=().
~FScopedLockModularFeatureList()
IModularFeatures::FScopedLockModularFeatureList::~FScopedLockModularFeatureList () inline
Definition at line 91 of file IModularFeatures.h.
References IModularFeatures::Get(), and IModularFeatures::UnlockModularFeatureList().
FScopedLockModularFeatureList() [2/3]
IModularFeatures::FScopedLockModularFeatureList::FScopedLockModularFeatureList (const FScopedLockModularFeatureList &) delete
References FScopedLockModularFeatureList().
FScopedLockModularFeatureList() [3/3]
IModularFeatures::FScopedLockModularFeatureList::FScopedLockModularFeatureList (FScopedLockModularFeatureList &&) delete
References FScopedLockModularFeatureList().
Member Function Documentation
operator=() [1/2]
FScopedLockModularFeatureList & IModularFeatures::FScopedLockModularFeatureList::operator= (const FScopedLockModularFeatureList &) delete
References FScopedLockModularFeatureList().
operator=() [2/2]
FScopedLockModularFeatureList & IModularFeatures::FScopedLockModularFeatureList::operator= (FScopedLockModularFeatureList &&) delete
References FScopedLockModularFeatureList().
The documentation for this struct was generated from the following file:
IModularFeatures.h