Unreal Engine 5.6 C++ API: GSLNotNull.h File Reference
GSLNotNull.h File Reference
#include "CoreTypes.h"
#include "Misc/OptionalFwd.h"
#include "Templates/UnrealTemplate.h"
#include <gsl/pointers>
Functions
template<typename ObjectType>
ObjectType * GetRawPointerOrNull (const TOptional< gsl::not_null< ObjectType * > > &Optional)
Utility function to turn an TOptional<gsl::not_null<T>> back into a nullable T.
template<typename ObjectType>
ObjectType * GetRawPointerOrNull (const TOptional< gsl::strict_not_null< ObjectType * > > &Optional)
Utility function to turn an TOptional<gsl::strict_not_null<T>> back into a nullable T.
template<typename ObjectType>
auto GetTypeHash (const gsl::not_null< ObjectType > &NotNull) -> decltype(GetTypeHash(*NotNull))
Utility function to hash a gsl::not_null<T>.
template<typename ObjectType>
auto GetTypeHash (const gsl::strict_not_null< ObjectType > &NotNull) -> decltype(GetTypeHash(*NotNull))
Utility function to hash a gsl::strict_not_null<T>.
template<typename ObjectType>
FArchive & operator<< (FArchive &Ar, gsl::not_null< ObjectType > &NotNull)
Utility function to serialize a `gsl::not_null<T>.
template<typename ObjectType>
FArchive & operator<< (FArchive &Ar, gsl::strict_not_null< ObjectType > &NotNull)
Utility function to serialize a gsl::strict_not_null<T>.
Function Documentation
GetRawPointerOrNull() [1/2]
template<typename ObjectType> ObjectType * GetRawPointerOrNull (const TOptional< gsl::not_null< ObjectType * > > & Optional) inline nodiscard
Utility function to turn an TOptional<gsl::not_null<T>> back into a nullable T.
Definition at line 14 of file GSLNotNull.h.
References Optional.
GetRawPointerOrNull() [2/2]
template<typename ObjectType> ObjectType * GetRawPointerOrNull (const TOptional< gsl::strict_not_null< ObjectType * > > & Optional) inline nodiscard
Utility function to turn an TOptional<gsl::strict_not_null<T>> back into a nullable T.
Definition at line 21 of file GSLNotNull.h.
References Optional.
GetTypeHash() [1/2]
template<typename ObjectType> auto GetTypeHash (const gsl::not_null< ObjectType > & NotNull) -> decltype(GetTypeHash(*NotNull)) inline nodiscard
Utility function to hash a gsl::not_null<T>.
Definition at line 45 of file GSLNotNull.h.
References GetTypeHash().
Referenced by GetTypeHash(), and GetTypeHash().
GetTypeHash() [2/2]
template<typename ObjectType> auto GetTypeHash (const gsl::strict_not_null< ObjectType > & NotNull) -> decltype(GetTypeHash(*NotNull)) inline nodiscard
Utility function to hash a gsl::strict_not_null<T>.
Definition at line 52 of file GSLNotNull.h.
References GetTypeHash().
operator<<() [1/2]
template<typename ObjectType> FArchive & operator<< (FArchive & Ar, gsl::not_null< ObjectType > & NotNull)
Utility function to serialize a `gsl::not_null<T>.
Definition at line 29 of file GSLNotNull.h.
References Ar.
operator<<() [2/2]
template<typename ObjectType> FArchive & operator<< (FArchive & Ar, gsl::strict_not_null< ObjectType > & NotNull)
Utility function to serialize a gsl::strict_not_null<T>.
Definition at line 37 of file GSLNotNull.h.
References Ar.