Unreal Engine 5.6 C++ API: FMemoryImageSection Class Reference
FMemoryImageSection Class Reference
#include "MemoryImage.h"
Data Structures
struct FSectionPointer
Public Member Functions
FMemoryImageSection (FMemoryImage *InImage)
void ComputeHash ()
uint32 Flatten (FMemoryImageResult &OutResult) const
uint32 GetOffset () const
uint32 WriteAlignment (uint32 Alignment)
template<typename T>
uint32 WriteBytes (const T &Data)
uint32 WriteBytes (const void *Data, uint32 Size)
uint32 WriteFMemoryImageName (int32 NumBytes, const FName &Name)
uint32 WriteFScriptName (const FScriptName &Name)
void WritePaddingToSize (uint32 Offset)
FMemoryImageSection * WritePointer (const FTypeLayoutDesc &StaticTypeDesc, const FTypeLayoutDesc &DerivedTypeDesc, uint32 *OutOffsetToBase=nullptr)
uint32 WriteRawPointerSizedBytes (uint64 PointerValue)
uint32 WriteVTable (const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
uint32 WriteZeroBytes (int32 Num)
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Data Fields
TArray< uint8 > Bytes
FSHAHash Hash
uint32 MaxAlignment
TArray< FMemoryImageNamePointer > MemoryImageNames
FMemoryImage * ParentImage
TArray< FSectionPointer > Pointers
TArray< FMemoryImageNamePointer > ScriptNames
TArray< FMemoryImageVTablePointer > VTables
Detailed Description
Definition at line 215 of file MemoryImage.h.
Constructor & Destructor Documentation
FMemoryImageSection()
FMemoryImageSection::FMemoryImageSection (FMemoryImage * InImage) inline
Definition at line 225 of file MemoryImage.h.
References MaxAlignment, and ParentImage.
Referenced by WritePointer().
Member Function Documentation
ComputeHash()
void FMemoryImageSection::ComputeHash ()
Flatten()
uint32 FMemoryImageSection::Flatten (FMemoryImageResult & OutResult) const
GetOffset()
uint32 FMemoryImageSection::GetOffset () const inline
Definition at line 230 of file MemoryImage.h.
References Bytes.
Referenced by WriteBytes(), and WriteZeroBytes().
WriteAlignment()
uint32 FMemoryImageSection::WriteAlignment (uint32 Alignment) inline
Definition at line 232 of file MemoryImage.h.
References Align, Bytes, FMath::Max, and MaxAlignment.
WriteBytes() [1/2]
template<typename T> uint32 FMemoryImageSection::WriteBytes (const T & Data) inline
Definition at line 263 of file MemoryImage.h.
References WriteBytes().
Referenced by WriteBytes().
WriteBytes() [2/2]
uint32 FMemoryImageSection::WriteBytes (const void * Data, uint32 Size) inline
Definition at line 247 of file MemoryImage.h.
References Bytes, GetOffset(), FMemory::Memcpy(), and TSequenceHistory< HistorySize >::Size.
WriteFMemoryImageName()
uint32 FMemoryImageSection::WriteFMemoryImageName (int32 NumBytes, const FName & Name)
References Name.
WriteFScriptName()
uint32 FMemoryImageSection::WriteFScriptName (const FScriptName & Name)
References Name.
WritePaddingToSize()
void FMemoryImageSection::WritePaddingToSize (uint32 Offset) inline
Definition at line 241 of file MemoryImage.h.
References Bytes, and check.
WritePointer()
FMemoryImageSection * FMemoryImageSection::WritePointer (const FTypeLayoutDesc & StaticTypeDesc, const FTypeLayoutDesc & DerivedTypeDesc, uint32 * OutOffsetToBase = nullptr)
References FMemoryImageSection().
WriteRawPointerSizedBytes()
uint32 FMemoryImageSection::WriteRawPointerSizedBytes (uint64 PointerValue)
WriteVTable()
uint32 FMemoryImageSection::WriteVTable (const FTypeLayoutDesc & TypeDesc, const FTypeLayoutDesc & DerivedTypeDesc)
WriteZeroBytes()
uint32 FMemoryImageSection::WriteZeroBytes (int32 Num) inline
Definition at line 255 of file MemoryImage.h.
References Bytes, GetOffset(), and Num.
Field Documentation
Bytes
TArray<uint8> FMemoryImageSection::Bytes
Definition at line 275 of file MemoryImage.h.
Referenced by GetOffset(), WriteAlignment(), WriteBytes(), WritePaddingToSize(), and WriteZeroBytes().
Hash
FSHAHash FMemoryImageSection::Hash
Definition at line 280 of file MemoryImage.h.
MaxAlignment
uint32 FMemoryImageSection::MaxAlignment
Definition at line 281 of file MemoryImage.h.
Referenced by FMemoryImageSection(), and WriteAlignment().
MemoryImageNames
TArray<FMemoryImageNamePointer> FMemoryImageSection::MemoryImageNames
Definition at line 279 of file MemoryImage.h.
ParentImage
FMemoryImage* FMemoryImageSection::ParentImage
Definition at line 274 of file MemoryImage.h.
Referenced by FMemoryImageSection().
Pointers
TArray<FSectionPointer> FMemoryImageSection::Pointers
Definition at line 276 of file MemoryImage.h.
ScriptNames
TArray<FMemoryImageNamePointer> FMemoryImageSection::ScriptNames
Definition at line 278 of file MemoryImage.h.
VTables
TArray<FMemoryImageVTablePointer> FMemoryImageSection::VTables
Definition at line 277 of file MemoryImage.h.
The documentation for this class was generated from the following file:
MemoryImage.h