Unreal Engine 5.6 C++ API: FLandscapeConfigHelper Class Reference
FLandscapeConfigHelper Class Reference
#include "LandscapeConfigHelper.h"
Static Public Member Functions
static LANDSCAPE_API ULandscapeInfo * ChangeConfiguration (ULandscapeInfo *InLandscapeInfo, const FLandscapeConfigChange &InNewConfig, TSet< AActor * > &OutActorsToDelete, TSet< AActor * > &OutModifiedActors)
static LANDSCAPE_API bool ChangeGridSize (ULandscapeInfo *InLandscapeInfo, uint32 InNewGridSizeInComponents, TSet< AActor * > &OutActorsToDelete)
template<typename T>
static void CopyData (const TArray< T > &InData, TArray< T > &OutData, const FIntRect &InSrcRegion, const FIntRect &InDestRegion, bool bInResample)
template<typename T>
static void CopySubregion (const TArrayView< T > &InData, TArray< T > &OutData, const FIntRect &InSrcRegion, uint32 InSrcDataPitch)
template<typename T>
static void ExpandData (const TArray< T > &InData, TArray< T > &OutData, const FIntRect &InSrcRegion, const FIntRect &InDestRegion, bool bOffset)
static LANDSCAPE_API ALandscapeProxy * FindOrAddLandscapeStreamingProxy (ULandscapeInfo *InLandscapeInfo, const FIntPoint &InSectionBase)
static LANDSCAPE_API bool PartitionLandscape (UWorld *InWorld, ULandscapeInfo *InLandscapeInfo, uint32 InGridSizeInComponents)
template<typename T>
static void ResampleData (const TArray< T > &InData, TArray< T > &OutData, const FIntRect &InSrcRegion, const FIntRect &InDestRegion)
Static Private Member Functions
static void CopyRegionToComponent (ULandscapeInfo *LandscapeInfo, const FIntRect &Region, bool bResample, ULandscapeComponent *Component)
static void ExtractLandscapeData (ULandscapeInfo *LandscapeInfo, const FIntRect &Region, const FGuid &LayerGuid, TArray< uint16 > &OutHeightData, TArray< FLandscapeImportLayerInfo > &OutImportMaterialLayerInfos)
static ALandscapeProxy * FindOrAddLandscapeStreamingProxy (UActorPartitionSubsystem *ActorPartitionSubsystem, ULandscapeInfo *LandscapeInfo, const UActorPartitionSubsystem::FCellCoord &CellCoord)
static void MoveFoliageToLandscape (ULandscapeInfo *InLandscapeInfo, ULandscapeInfo *InNewLandscapeInfo)
static void MoveSplinesToLandscape (ULandscapeInfo *InLandscapeInfo, ALandscapeProxy *InLandscape, float InScaleFactor)
Detailed Description
Definition at line 66 of file LandscapeConfigHelper.h.
Member Function Documentation
ChangeConfiguration()
LANDSCAPE_API ULandscapeInfo * FLandscapeConfigHelper::ChangeConfiguration (ULandscapeInfo * InLandscapeInfo, const FLandscapeConfigChange & InNewConfig, TSet< AActor * > & OutActorsToDelete, TSet< AActor * > & OutModifiedActors) static
ChangeGridSize()
LANDSCAPE_API bool FLandscapeConfigHelper::ChangeGridSize (ULandscapeInfo * InLandscapeInfo, uint32 InNewGridSizeInComponents, TSet< AActor * > & OutActorsToDelete) static
CopyData()
template<typename T> void FLandscapeConfigHelper::CopyData (const TArray< T > & InData, TArray< T > & OutData, const FIntRect & InSrcRegion, const FIntRect & InDestRegion, bool bInResample) inline static
Definition at line 83 of file LandscapeConfigHelper.h.
References ExpandData(), and ResampleData().
CopyRegionToComponent()
void FLandscapeConfigHelper::CopyRegionToComponent (ULandscapeInfo * LandscapeInfo, const FIntRect & Region, bool bResample, ULandscapeComponent * Component) static private
References Component.
CopySubregion()
template<typename T> void FLandscapeConfigHelper::CopySubregion (const TArrayView< T > & InData, TArray< T > & OutData, const FIntRect & InSrcRegion, uint32 InSrcDataPitch) inline static
Definition at line 143 of file LandscapeConfigHelper.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), UE::Math::TIntRect< InIntType >::Area(), check, TArray< InElementType, InAllocatorType >::Empty(), UE::Math::TIntRect< InIntType >::Height(), UE::Math::TIntRect< InIntType >::Min, UE::Math::TIntRect< InIntType >::Width(), UE::Math::TIntPoint< InIntType >::X, X, Y, and UE::Math::TIntPoint< InIntType >::Y.
ExpandData()
template<typename T> void FLandscapeConfigHelper::ExpandData (const TArray< T > & InData, TArray< T > & OutData, const FIntRect & InSrcRegion, const FIntRect & InDestRegion, bool bOffset) inline static
Definition at line 96 of file LandscapeConfigHelper.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), FMath::Clamp(), TArray< InElementType, InAllocatorType >::Empty(), UE::Math::TIntRect< InIntType >::Height(), FMath::Max, FMemory::Memcpy(), FMath::Min, UE::Math::TIntRect< InIntType >::Min, UE::Math::TIntRect< InIntType >::Width(), UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Referenced by CopyData().
ExtractLandscapeData()
void FLandscapeConfigHelper::ExtractLandscapeData (ULandscapeInfo * LandscapeInfo, const FIntRect & Region, const FGuid & LayerGuid, TArray< uint16 > & OutHeightData, TArray< FLandscapeImportLayerInfo > & OutImportMaterialLayerInfos) static private
FindOrAddLandscapeStreamingProxy() [1/2]
ALandscapeProxy * FLandscapeConfigHelper::FindOrAddLandscapeStreamingProxy (UActorPartitionSubsystem * ActorPartitionSubsystem, ULandscapeInfo * LandscapeInfo, const UActorPartitionSubsystem::FCellCoord & CellCoord) static private
FindOrAddLandscapeStreamingProxy() [2/2]
LANDSCAPE_API ALandscapeProxy * FLandscapeConfigHelper::FindOrAddLandscapeStreamingProxy (ULandscapeInfo * InLandscapeInfo, const FIntPoint & InSectionBase) static
MoveFoliageToLandscape()
void FLandscapeConfigHelper::MoveFoliageToLandscape (ULandscapeInfo * InLandscapeInfo, ULandscapeInfo * InNewLandscapeInfo) static private
MoveSplinesToLandscape()
void FLandscapeConfigHelper::MoveSplinesToLandscape (ULandscapeInfo * InLandscapeInfo, ALandscapeProxy * InLandscape, float InScaleFactor) static private
PartitionLandscape()
LANDSCAPE_API bool FLandscapeConfigHelper::PartitionLandscape (UWorld * InWorld, ULandscapeInfo * InLandscapeInfo, uint32 InGridSizeInComponents) static
ResampleData()
template<typename T> void FLandscapeConfigHelper::ResampleData (const TArray< T > & InData, TArray< T > & OutData, const FIntRect & InSrcRegion, const FIntRect & InDestRegion) inline static
Definition at line 169 of file LandscapeConfigHelper.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), FMath::BiLerp(), check, TArray< InElementType, InAllocatorType >::Empty(), float, UE::Math::TIntRect< InIntType >::Height(), FMath::Min, TArray< InElementType, InAllocatorType >::Num(), UE::Math::TIntRect< InIntType >::Width(), X, and Y.
Referenced by CopyData().
The documentation for this class was generated from the following file:
LandscapeConfigHelper.h