Unreal Engine 5.6 C++ API: FLocMetadataValueString Class Reference
FLocMetadataValueString Class Reference
A LocMetadata String Value.
#include "InternationalizationMetadata.h"
Public Member Functions
FLocMetadataValueString (const FString &InString)
FLocMetadataValueString (FStructuredArchive::FSlot Slot)
virtual FString AsString () override
Returns this value as a string, throwing an error if this is not a Metadata String.
virtual TSharedRef< FLocMetadataValue > Clone () const override
virtual ELocMetadataType GetType () const override
void SetString (const FString &InString)
virtual FString ToString () const override
Public Member Functions inherited from FLocMetadataValue
virtual ~FLocMetadataValue ()=0
virtual TArray< TSharedPtr< FLocMetadataValue > > AsArray ()
Returns this value as an array, throwing an error if this is not an Metadata Array.
virtual bool AsBool ()
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
virtual TSharedPtr< FLocMetadataObject > AsObject ()
Returns this value as an object, throwing an error if this is not an Metadata Object.
bool operator< (const FLocMetadataValue &Other) const
bool operator== (const FLocMetadataValue &Other) const
Static Public Member Functions
static void Serialize (FLocMetadataValueString &Value, FStructuredArchive::FSlot Slot)
Protected Member Functions
virtual bool EqualTo (const FLocMetadataValue &Other) const override
virtual FString GetTypeString () const override
virtual bool LessThan (const FLocMetadataValue &Other) const override
Protected Member Functions inherited from FLocMetadataValue
FLocMetadataValue ()
void ErrorMessage (const FString &InType)
Protected Attributes
FString Value
Detailed Description
A LocMetadata String Value.
Definition at line 180 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
FLocMetadataValueString() [1/2]
FLocMetadataValueString::FLocMetadataValueString (const FString & InString) inline
Definition at line 183 of file InternationalizationMetadata.h.
References Value.
Referenced by Serialize().
FLocMetadataValueString() [2/2]
FLocMetadataValueString::FLocMetadataValueString (FStructuredArchive::FSlot Slot)
Member Function Documentation
AsString()
virtual FString FLocMetadataValueString::AsString () inline override virtual
Returns this value as a string, throwing an error if this is not a Metadata String.
Reimplemented from FLocMetadataValue.
Definition at line 187 of file InternationalizationMetadata.h.
References Value.
Clone()
virtual TSharedRef< FLocMetadataValue > FLocMetadataValueString::Clone () const override virtual
Implements FLocMetadataValue.
EqualTo()
virtual bool FLocMetadataValueString::EqualTo (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
GetType()
virtual ELocMetadataType FLocMetadataValueString::GetType () const inline override virtual
Implements FLocMetadataValue.
Definition at line 194 of file InternationalizationMetadata.h.
References String.
GetTypeString()
virtual FString FLocMetadataValueString::GetTypeString () const inline override protected virtual
Implements FLocMetadataValue.
Definition at line 203 of file InternationalizationMetadata.h.
References TEXT.
LessThan()
virtual bool FLocMetadataValueString::LessThan (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
Serialize()
void FLocMetadataValueString::Serialize (FLocMetadataValueString & Value, FStructuredArchive::FSlot Slot) static
References FLocMetadataValueString(), and Value.
SetString()
void FLocMetadataValueString::SetString (const FString & InString) inline
Definition at line 190 of file InternationalizationMetadata.h.
References Value.
ToString()
virtual FString FLocMetadataValueString::ToString () const inline override virtual
Implements FLocMetadataValue.
Definition at line 192 of file InternationalizationMetadata.h.
References Value.
Field Documentation
Value
FString FLocMetadataValueString::Value protected
Definition at line 198 of file InternationalizationMetadata.h.
Referenced by FLocMetadataValueString(), AsString(), Serialize(), SetString(), and ToString().
The documentation for this class was generated from the following file:
InternationalizationMetadata.h