Unreal Engine 5.6 C++ API: SSCSEditor Class Reference
SSCSEditor Class Reference
#include "SSCSEditor.h"
Data Structures
struct FAddedNodeDetails
struct FAddNewComponentParams
Adds a component to the SCS tree.
Public Member Functions
~SSCSEditor ()
UActorComponent * AddNewComponent (UClass *NewComponentClass, UObject *Asset, const FAddNewComponentParams Params=FAddNewComponentParams())
Adds a component to the SCS Table.
void AddNewNode (FAddedNodeDetails &OutNodeDetails, TUniquePtr< FScopedTransaction > OngoingCreateTransaction, USCS_Node *NewNode, UObject *Asset, bool bMarkBlueprintModified, bool bSetFocusToNewItem=true)
Adds a new SCS Node to the component Table.
UActorComponent * AddNewNode (TUniquePtr< FScopedTransaction > OngoingCreateTransaction, USCS_Node *NewNode, UObject *Asset, bool bMarkBlueprintModified, bool bSetFocusToNewItem=true)
Adds a new SCS Node to the component Table.
void AddNewNodeForInstancedComponent (TUniquePtr< FScopedTransaction > OngoingCreateTransaction, UActorComponent *NewInstanceComponent, FSCSEditorTreeNodePtrType InParentNodePtr, UObject *Asset, bool bSetFocusToNewItem=true)
Adds a new component instance node to the component Table.
bool CanCopyNodes () const
bool CanCutNodes () const
bool CanDeleteNodes () const
bool CanDuplicateComponent () const
Callbacks to duplicate the selected component.
bool CanPasteNodes () const
void ClearSelection ()
Clears the current selection.
void CopySelectedNodes ()
Copy selected node(s)
void CutSelectedNodes ()
Cut selected node(s)
DECLARE_DELEGATE_OneParam (FOnHighlightPropertyInDetailsView, const class FPropertyPath &)
DECLARE_DELEGATE_OneParam (FOnItemDoubleClicked, const FSCSEditorTreeNodePtrType)
DECLARE_DELEGATE_OneParam (FOnSelectionUpdated, const TArray< FSCSEditorTreeNodePtrType > &)
DECLARE_DELEGATE_RetVal_OneParam (class USCS_Node *, FOnAddExistingComponent, class UActorComponent *)
DECLARE_DELEGATE_RetVal_OneParam (class USCS_Node *, FOnAddNewComponent, class UClass *)
void DumpTree ()
Dumps out the tree view contents to the log (used to assist with debugging widget hierarchy issues)
class AActor * GetActorContext () const
Returns the Actor context for which we are viewing/editing the SCS.
FSCSEditorActorNodePtrType GetActorNode () const
gets the actor root
class UBlueprint * GetBlueprint () const
Provides access to the Blueprint context that's being edited.
EComponentEditorMode::Type GetEditorMode () const
FText GetFilterText () const
Callback for the action trees to get the filter text.
FSCSEditorTreeNodePtrType GetNodeFromActorComponent (const UActorComponent *ActorComponent, bool bIncludeAttachedComponents=true) const
Given an actor component, attempts to find an associated tree node.
int32 GetNumSelectedNodes () const
Get the number of currently selected tree nodes.
FSCSEditorTreeNodePtrType GetSceneRootNode () const
get the root scene node
TArray< UObject * > GetSelectedEditableObjects () const
void GetSelectedItemsForContextMenu (TArray< FComponentEventConstructionData > &OutSelectedItems) const
Fills the supplied array with the currently selected objects.
TArray< FSCSEditorTreeNodePtrType > GetSelectedNodes () const
Get the currently selected tree nodes.
TSharedPtr< SWidget > GetToolButtonsBox ()
Return the button widgets that can add components or create/edit blueprints.
void HighlightTreeNode (const USCS_Node *Node, FName Property)
Highlight a tree node and, optionally, a property with in it.
void HighlightTreeNode (FName TreeNodeName, const class FPropertyPath &Property)
Highlight a tree node and, optionally, a property with in it.
bool IsComponentSelected (const UPrimitiveComponent *PrimComponent) const
Returns true if the specified component is currently selected.
bool IsEditingAllowed () const
Returns true if editing is allowed.
bool IsNodeInSimpleConstructionScript (USCS_Node *Node) const
Is this node still used by the Simple Construction Script.
TSharedRef< ITableRow > MakeTableRowWidget (FSCSEditorTreeNodePtrType InNodePtr, const TSharedRef< STableViewBase > &OwnerTable)
Used by tree control - make a widget for a table row from a node.
void OnActorSelected (const ECheckBoxState NewCheckedState)
Called when the Actor is selected.
void OnDeleteNodes ()
Removes existing selected component nodes from the SCS.
void OnDuplicateComponent ()
void OnFindReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags)
Callbacks to find references of the selected component.
void OnGetChildrenForTree (FSCSEditorTreeNodePtrType InNodePtr, TArray< FSCSEditorTreeNodePtrType > &OutChildren)
Used by tree control - get children for a specified node.
ECheckBoxState OnIsActorSelected () const
Called to determine if actor is selected.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
SWidget interface.
void OnPostTick (float)
Called at the end of each frame.
void OnTreeSelectionChanged (FSCSEditorTreeNodePtrType InSelectedNodePtr, ESelectInfo::Type SelectInfo)
Called when selection in the tree changes.
void PasteNodes ()
Pastes previously copied node(s)
void RefreshSelectionDetails ()
Forces the details panel to refresh on the same objects.
void RemoveComponentNode (FSCSEditorTreeNodePtrType InNodePtr)
Removes an existing component node from the tree.
void SelectNode (FSCSEditorTreeNodePtrType InNodeToSelect, bool IsCntrlDown)
Select the given tree node.
void SelectRoot ()
Select the root of the tree.
void SetItemExpansionRecursive (FSCSEditorTreeNodePtrType Model, bool bInExpansionState)
Handler for recursively expanding/collapsing items.
void SetNodeExpansionState (FSCSEditorTreeNodePtrType InNodeToChange, const bool bIsExpanded)
Set the expansion state of a node.
void SetSceneRootNode (FSCSEditorTreeNodePtrType NewSceneRootNode)
void SetSelectionOverride (UPrimitiveComponent *PrimComponent) const
Assigns a selection override delegate to the specified component.
void SetUICustomization (TSharedPtr< ISCSEditorUICustomization > InUICustomization)
Sets UI customizations of this SCSEditor.
SLATE_ARGUMENT (EComponentEditorMode::Type, EditorMode) SLATE_ARGUMENT(bool
IsDiffing PreviewActor SLATE_ATTRIBUTE (bool, AllowEditing) SLATE_ATTRIBUTE(bool
IsDiffing SLATE_ATTRIBUTE (class AActor *, ActorContext) SLATE_ATTRIBUTE(class AActor *
IsDiffing PreviewActor HideComponentClassCombo SLATE_ATTRIBUTE (TSubclassOf< UActorComponent >, ComponentTypeFilter) SLATE_EVENT(FOnSelectionUpdated
SLATE_BEGIN_ARGS (SSCSEditor)
IsDiffing PreviewActor HideComponentClassCombo OnSelectionUpdated SLATE_EVENT (FOnItemDoubleClicked, OnItemDoubleClicked) SLATE_EVENT(FOnHighlightPropertyInDetailsView
IsDiffing PreviewActor HideComponentClassCombo OnSelectionUpdated OnHighlightPropertyInDetailsView SLATE_EVENT (FSimpleDelegate, OnObjectReplaced) SLATE_END_ARGS() void Construct(const FArguments &InArgs)
FReply TryHandleAssetDragDropOperation (const FDragDropEvent &DragDropEvent)
Try to handle a drag-drop operation.
void UpdateSelectionFromNodes (const TArray< FSCSEditorTreeNodePtrType > &SelectedNodes)
Update any associated selection (e.g.
void UpdateTree (bool bRegenerateTreeNodes=true)
Refresh the tree control to reflect changes in the SCS.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static void BuildMenuEventsSection (FMenuBuilder &Menu, UBlueprint *Blueprint, UClass *SelectedClass, FCanExecuteAction CanExecuteActionDelegate, FGetSelectedObjectsDelegate GetSelectedObjectsDelegate)
Fills out an events section in ui.
static void SaveSCSCurrentState (USimpleConstructionScript *SCSObj)
Function to save current state of SimpleConstructionScript and nodes associated with it.
static void SaveSCSNode (USCS_Node *Node)
Function to save the current state of SCS_Node and its children.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields
TAttribute< class AActor * > ActorContext
Attribute that provides access to the Actor context for which we are viewing/editing the SCS.
TAttribute< bool > AllowEditing
Attribute to indicate whether or not editing is allowed.
TSharedPtr< FUICommandList > CommandList
Command list for handling actions in the SSCSEditor.
TAttribute< TSubclassOf< UActorComponent > > ComponentTypeFilter
Attribute to limit visible nodes to a particular component type when filtering the tree view.
TUniquePtr< FScopedTransaction > DeferredOngoingCreateTransaction
Scope the creation of a component which ends when the initial component 'name' is given/accepted by the user, which can be several frames after the component was actually created.
FName DeferredRenameRequest
Name of a node that has been requested to be renamed.
TAttribute< bool > HideComponentClassCombo
Attribute to indicate whether or not the "Add Component" button is visible.
FOnHighlightPropertyInDetailsView OnHighlightPropertyInDetailsView
Delegate to invoke when the given property should be highlighted in the details view (e.g.
FOnItemDoubleClicked OnItemDoubleClicked
Delegate to invoke when an item in the tree is double clicked.
FSimpleDelegate OnObjectReplaced
Delegate to invoke when objects within the SCS tree are replaced (eg, via re-instancing from a BP compile)
FOnSelectionUpdated OnSelectionUpdated
Delegate to invoke on selection update.
FDelegateHandle PostTickHandle
Used to unregister from the post tick event.
TAttribute< class AActor * > PreviewActor
Attribute that provides access to a "preview" Actor context (may not be same as the Actor context that's being edited.
TSharedPtr< SSCSTreeType > SCSTreeWidget
Tree widget.
Protected Member Functions
FSCSEditorTreeNodePtrType AddTreeNode (USCS_Node *InSCSNode, FSCSEditorTreeNodePtrType InParentNodePtr, const bool bIsInheritedSCS)
Helper method to add a tree node for the given SCS node.
FSCSEditorTreeNodePtrType AddTreeNodeFromChildActor (FSCSEditorTreeNodePtrType InNodePtr)
Helper method to add a tree node for the given node's child actor node, if present.
FSCSEditorTreeNodePtrType AddTreeNodeFromComponent (UActorComponent *InSceneComponent, FSCSEditorTreeNodePtrType InParentTreeNode=FSCSEditorTreeNodePtrType())
Helper method to add a tree node for the given actor component.
void BuildSubTreeForActorNode (FSCSEditorActorNodePtrType InActorNode)
Helper method to construct the subtree for the given actor (root) node.
bool CanRenameComponent () const
Checks to see if renaming is allowed on the selected component.
TSharedPtr< SWidget > CreateContextMenu ()
Called to display context menu when right clicking on the widget.
UClass * CreateNewBPComponent (TSubclassOf< UActorComponent > ComponentClass)
Creates a new Blueprint component from the specified class type The user will be prompted to pick a new subclass name and a blueprint asset will be created.
UClass * CreateNewCPPComponent (TSubclassOf< UActorComponent > ComponentClass)
Creates a new C++ component from the specified class type The user will be prompted to pick a new subclass name and code will be recompiled.
void DepthFirstTraversal (const FSCSEditorTreeNodePtrType &InNodePtr, TSet< FSCSEditorTreeNodePtrType > &OutVisitedNodes, const TFunctionRef< void(const FSCSEditorTreeNodePtrType &)> InFunction) const
Recursively visits the given node + its children and invokes the given function for each.
FSCSEditorTreeNodePtrType FindOrCreateParentForExistingComponent (UActorComponent *InActorComponent, FSCSEditorActorNodePtrType ActorRootNode)
FSCSEditorTreeNodePtrType FindParentForNewComponent (UActorComponent *NewComponent) const
FSCSEditorTreeNodePtrType FindParentForNewNode (USCS_Node *NewNode) const
FSCSEditorTreeNodePtrType FindTreeNode (const FName &InVariableOrInstanceName, FSCSEditorTreeNodePtrType InStartNodePtr=FSCSEditorTreeNodePtrType()) const
Helper method to recursively find a tree node for the given variable or instance name starting at the given tree node.
FSCSEditorTreeNodePtrType FindTreeNode (const UActorComponent *InComponent, FSCSEditorTreeNodePtrType InStartNodePtr=FSCSEditorTreeNodePtrType()) const
Helper method to recursively find a tree node for the given scene component starting at the given tree node.
FSCSEditorTreeNodePtrType FindTreeNode (const USCS_Node *InSCSNode, FSCSEditorTreeNodePtrType InStartNodePtr=FSCSEditorTreeNodePtrType()) const
Helper method to recursively find a tree node for the given SCS node starting at the given tree node.
void GetCollapsedNodes (const FSCSEditorTreeNodePtrType &InNodePtr, TSet< FSCSEditorTreeNodePtrType > &OutCollapsedNodes) const
Returns the set of expandable nodes that are currently collapsed in the UI.
EVisibility GetComponentClassComboButtonVisibility () const
EVisibility GetComponentsFilterBoxVisibility () const
EVisibility GetComponentsTreeVisibility () const
TSubclassOf< UActorComponent > GetComponentTypeFilterToApply () const
EVisibility GetEditBlueprintButtonVisibility () const
EVisibility GetPromoteToBlueprintButtonVisibility () const
const TArray< FSCSEditorTreeNodePtrType > & GetRootNodes () const
gets a root nodes of the tree
void HandleItemDoubleClicked (FSCSEditorTreeNodePtrType InItem)
Callback when a component item is double clicked.
void OnApplyChangesToBlueprint () const
Propagates instance changes to the blueprint.
void OnFilterTextChanged (const FText &InFilterText)
Recursively updates the filtered state for each component item.
FText OnGetApplyChangesToBlueprintTooltip () const
FText OnGetResetToBlueprintDefaultsTooltip () const
void OnItemScrolledIntoView (FSCSEditorTreeNodePtrType InItem, const TSharedPtr< ITableRow > &InWidget)
Callback when a component item is scrolled into view.
void OnLevelComponentRequestRename (const UActorComponent *InComponent)
Called when the level editor requests a component to be renamed.
void OnObjectsReplaced (const TMap< UObject *, UObject * > &OldToNewInstanceMap)
Called when component objects are replaced following construction script execution.
void OnOpenBlueprintEditor (bool bForceCodeEditing) const
Opens the blueprint editor for the blueprint being viewed by the scseditor.
FReply OnPromoteToBlueprintClicked ()
Called when the promote to blueprint button is clicked.
void OnRenameComponent ()
Requests a rename on the selected component.
void OnRenameComponent (TUniquePtr< FScopedTransaction > OngoingCreateTransaction)
Requests a rename on the selected component just after creation so that the user can provide the initial component name (overwriting the default generated one), which is considered part of the creation process.
void OnResetToBlueprintDefaults ()
Resets instance changes to the blueprint default.
UActorComponent * PerformComboAddClass (TSubclassOf< UActorComponent > ComponentClass, EComponentCreateAction::Type ComponentCreateAction, UObject *AssetOverride)
Add a component from the selection in the combo box.
void PopulateContextMenu (UToolMenu *InMenu)
Populate context menu on the fly.
void PromoteToBlueprint () const
Converts the current actor instance to a blueprint.
bool RefreshFilteredState (FSCSEditorTreeNodePtrType TreeNode, bool bRecursive)
Compares the filter bar's text with the item's component name.
void RegisterContextMenu ()
Registers context menu by name for later access.
void ReplaceComponentReferencesInTree (const TArray< FSCSEditorTreeNodePtrType > &Nodes, const TMap< UObject *, UObject * > &OldToNewInstanceMap, bool &OutHasChanges)
Update component pointers held by tree nodes if components have been replaced following construction script execution.
void ReplaceComponentReferencesInTree (FSCSEditorActorNodePtrType InActorNode, const TMap< UObject *, UObject * > &OldToNewInstanceMap, bool &OutHasChanges)
Helper method to update component pointers held by the given actor node's subtree.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static void ConstructEvent (UBlueprint *Blueprint, const FName EventName, const FComponentEventConstructionData EventData)
Function to construct an event for a node.
static void CreateEventsForSelection (UBlueprint *Blueprint, FName EventName, FGetSelectedObjectsDelegate GetSelectedObjectsDelegate)
Function to create events for the current selection.
static void ViewEvent (UBlueprint *Blueprint, const FName EventName, const FComponentEventConstructionData EventData)
Function to view an event for a node.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Private Attributes
TSharedPtr< FExtender > ActorMenuExtender
bool bAllowTreeUpdates
Controls whether or not to allow calls to UpdateTree()
bool bEnableComponentEditing
Flag to enable/disable component editing.
bool bIsDiffing
TRUE if this SCSEditor is currently the target of a diff.
bool bUpdatingSelection
Gate to prevent changing the selection while selection change is being broadcast.
TSharedPtr< SHorizontalBox > ButtonBox
The tools buttons box.
EComponentEditorMode::Type EditorMode
Indicates which editor mode we're in.
TSharedPtr< class SExtensionPanel > ExtensionPanel
SCSEditor UI extension.
TSharedPtr< SSearchBox > FilterBox
The filter box that handles filtering for the tree.
TArray< FSCSEditorTreeNodePtrType > RootNodes
Root set of tree.
TSharedPtr< ISCSEditorUICustomization > UICustomization
SCSEditor UI customizations.
Additional Inherited Members
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 1011 of file SSCSEditor.h.
Constructor & Destructor Documentation
~SSCSEditor()
SSCSEditor::~SSCSEditor ()
Member Function Documentation
AddNewComponent()
UActorComponent * SSCSEditor::AddNewComponent (UClass * NewComponentClass, UObject * Asset, const FAddNewComponentParams Params = FAddNewComponentParams())
Adds a component to the SCS Table.
Parameters
NewComponentClass (In) The class to add
Asset (In) Optional asset to assign to the component
Params (In) Parameter block of optional behavior flags
References Asset, and Params.
AddNewNode() [1/2]
void SSCSEditor::AddNewNode (FAddedNodeDetails & OutNodeDetails, TUniquePtr< FScopedTransaction > OngoingCreateTransaction, USCS_Node * NewNode, UObject * Asset, bool bMarkBlueprintModified, bool bSetFocusToNewItem = true)
Adds a new SCS Node to the component Table.
Parameters
OutNodeDetails (Out) Struct to be populated by the tree node pointers of the new node and its parent
OngoingCreateTransaction (In) The transaction containing the creation of the node. The transaction will remain ongoing until the node gets its initial name from user.
NewNode (In) The SCS node to add
Asset (In) Optional asset to assign to the component
bMarkBlueprintModified (In) Whether or not to mark the Blueprint as structurally modified
bSetFocusToNewItem (In) Select the new item and activate the inline rename widget (default is true)
References Asset.
AddNewNode() [2/2]
UActorComponent * SSCSEditor::AddNewNode (TUniquePtr< FScopedTransaction > OngoingCreateTransaction, USCS_Node * NewNode, UObject * Asset, bool bMarkBlueprintModified, bool bSetFocusToNewItem = true)
Adds a new SCS Node to the component Table.
Parameters
OngoingCreateTransaction (In) The transaction containing the creation of the node. The transaction will remain ongoing until the node gets its initial name from user.
NewNode (In) The SCS node to add
Asset (In) Optional asset to assign to the component
bMarkBlueprintModified (In) Whether or not to mark the Blueprint as structurally modified
bSetFocusToNewItem (In) Select the new item and activate the inline rename widget (default is true)
Returns
The reference of the newly created ActorComponent
References Asset.
AddNewNodeForInstancedComponent()
void SSCSEditor::AddNewNodeForInstancedComponent (TUniquePtr< FScopedTransaction > OngoingCreateTransaction, UActorComponent * NewInstanceComponent, FSCSEditorTreeNodePtrType InParentNodePtr, UObject * Asset, bool bSetFocusToNewItem = true)
Adds a new component instance node to the component Table.
Parameters
OngoingCreateTransaction (In) The transaction containing the creation of the node. The transaction will remain ongoing until the node gets its initial name from user.
NewInstanceComponent (In) The component being added to the actor instance
InParentNodePtr (In) The node this component will be added to
Asset (In) Optional asset to assign to the component
bSetFocusToNewItem (In) Select the new item and activate the inline rename widget (default is true)
References Asset.
AddTreeNode()
FSCSEditorTreeNodePtrType SSCSEditor::AddTreeNode (USCS_Node * InSCSNode, FSCSEditorTreeNodePtrType InParentNodePtr, const bool bIsInheritedSCS) protected
Helper method to add a tree node for the given SCS node.
AddTreeNodeFromChildActor()
FSCSEditorTreeNodePtrType SSCSEditor::AddTreeNodeFromChildActor (FSCSEditorTreeNodePtrType InNodePtr) protected
Helper method to add a tree node for the given node's child actor node, if present.
AddTreeNodeFromComponent()
FSCSEditorTreeNodePtrType SSCSEditor::AddTreeNodeFromComponent (UActorComponent * InSceneComponent, FSCSEditorTreeNodePtrType InParentTreeNode = FSCSEditorTreeNodePtrType()) protected
Helper method to add a tree node for the given actor component.
BuildMenuEventsSection()
void SSCSEditor::BuildMenuEventsSection (FMenuBuilder & Menu, UBlueprint * Blueprint, UClass * SelectedClass, FCanExecuteAction CanExecuteActionDelegate, FGetSelectedObjectsDelegate GetSelectedObjectsDelegate) static
Fills out an events section in ui.
Parameters
Menu the menu to add the events section into
Blueprint the active blueprint context being edited
SelectedClass the common component class to build the events list from
CanExecuteActionDelegate the delegate to query whether or not to execute the UI action
GetSelectedObjectsDelegate the delegate to fill the currently select variables / components
References Menu.
BuildSubTreeForActorNode()
void SSCSEditor::BuildSubTreeForActorNode (FSCSEditorActorNodePtrType InActorNode) protected
Helper method to construct the subtree for the given actor (root) node.
CanCopyNodes()
bool SSCSEditor::CanCopyNodes () const
CanCutNodes()
bool SSCSEditor::CanCutNodes () const
CanDeleteNodes()
bool SSCSEditor::CanDeleteNodes () const
CanDuplicateComponent()
bool SSCSEditor::CanDuplicateComponent () const
Callbacks to duplicate the selected component.
CanPasteNodes()
bool SSCSEditor::CanPasteNodes () const
CanRenameComponent()
bool SSCSEditor::CanRenameComponent () const protected
Checks to see if renaming is allowed on the selected component.
ClearSelection()
void SSCSEditor::ClearSelection ()
Clears the current selection.
ConstructEvent()
void SSCSEditor::ConstructEvent (UBlueprint * Blueprint, const FName EventName, const FComponentEventConstructionData EventData) static protected
Function to construct an event for a node.
Parameters
Blueprint the nodes blueprint
EventName the event to add
EventData the event data structure describing the node
CopySelectedNodes()
void SSCSEditor::CopySelectedNodes ()
Copy selected node(s)
CreateContextMenu()
TSharedPtr< SWidget > SSCSEditor::CreateContextMenu () protected
Called to display context menu when right clicking on the widget.
CreateEventsForSelection()
void SSCSEditor::CreateEventsForSelection (UBlueprint * Blueprint, FName EventName, FGetSelectedObjectsDelegate GetSelectedObjectsDelegate) static protected
Function to create events for the current selection.
Parameters
Blueprint the active blueprint context
EventName the event to add
GetSelectedObjectsDelegate the delegate to gather information about current selection
NodeIndex an index to a specified node to add event for or < 0 for all selected nodes.
CreateNewBPComponent()
UClass * SSCSEditor::CreateNewBPComponent (TSubclassOf< UActorComponent > ComponentClass) protected
Creates a new Blueprint component from the specified class type The user will be prompted to pick a new subclass name and a blueprint asset will be created.
Returns
The new class that was created
CreateNewCPPComponent()
UClass * SSCSEditor::CreateNewCPPComponent (TSubclassOf< UActorComponent > ComponentClass) protected
Creates a new C++ component from the specified class type The user will be prompted to pick a new subclass name and code will be recompiled.
Returns
The new class that was created
CutSelectedNodes()
void SSCSEditor::CutSelectedNodes ()
Cut selected node(s)
DECLARE_DELEGATE_OneParam() [1/3]
SSCSEditor::DECLARE_DELEGATE_OneParam (FOnHighlightPropertyInDetailsView , const class FPropertyPath &)
DECLARE_DELEGATE_OneParam() [2/3]
SSCSEditor::DECLARE_DELEGATE_OneParam (FOnItemDoubleClicked , const FSCSEditorTreeNodePtrType)
DECLARE_DELEGATE_OneParam() [3/3]
SSCSEditor::DECLARE_DELEGATE_OneParam (FOnSelectionUpdated , const TArray< FSCSEditorTreeNodePtrType > &)
DECLARE_DELEGATE_RetVal_OneParam() [1/2]
SSCSEditor::DECLARE_DELEGATE_RetVal_OneParam (class USCS_Node * , FOnAddExistingComponent , class UActorComponent *)
DECLARE_DELEGATE_RetVal_OneParam() [2/2]
SSCSEditor::DECLARE_DELEGATE_RetVal_OneParam (class USCS_Node * , FOnAddNewComponent , class UClass *)
DepthFirstTraversal()
void SSCSEditor::DepthFirstTraversal (const FSCSEditorTreeNodePtrType & InNodePtr, TSet< FSCSEditorTreeNodePtrType > & OutVisitedNodes, const TFunctionRef< void(const FSCSEditorTreeNodePtrType &)> InFunction) const protected
Recursively visits the given node + its children and invokes the given function for each.
DumpTree()
void SSCSEditor::DumpTree ()
Dumps out the tree view contents to the log (used to assist with debugging widget hierarchy issues)
FindOrCreateParentForExistingComponent()
FSCSEditorTreeNodePtrType SSCSEditor::FindOrCreateParentForExistingComponent (UActorComponent * InActorComponent, FSCSEditorActorNodePtrType ActorRootNode) protected
FindParentForNewComponent()
FSCSEditorTreeNodePtrType SSCSEditor::FindParentForNewComponent (UActorComponent * NewComponent) const protected
FindParentForNewNode()
FSCSEditorTreeNodePtrType SSCSEditor::FindParentForNewNode (USCS_Node * NewNode) const protected
FindTreeNode() [1/3]
FSCSEditorTreeNodePtrType SSCSEditor::FindTreeNode (const FName & InVariableOrInstanceName, FSCSEditorTreeNodePtrType InStartNodePtr = FSCSEditorTreeNodePtrType()) const protected
Helper method to recursively find a tree node for the given variable or instance name starting at the given tree node.
FindTreeNode() [2/3]
FSCSEditorTreeNodePtrType SSCSEditor::FindTreeNode (const UActorComponent * InComponent, FSCSEditorTreeNodePtrType InStartNodePtr = FSCSEditorTreeNodePtrType()) const protected
Helper method to recursively find a tree node for the given scene component starting at the given tree node.
FindTreeNode() [3/3]
FSCSEditorTreeNodePtrType SSCSEditor::FindTreeNode (const USCS_Node * InSCSNode, FSCSEditorTreeNodePtrType InStartNodePtr = FSCSEditorTreeNodePtrType()) const protected
Helper method to recursively find a tree node for the given SCS node starting at the given tree node.
GetActorContext()
class AActor * SSCSEditor::GetActorContext () const
Returns the Actor context for which we are viewing/editing the SCS.
Can return null. Should not be cached as it may change from frame to frame.
GetActorNode()
FSCSEditorActorNodePtrType SSCSEditor::GetActorNode () const
gets the actor root
References GetActorNode().
Referenced by GetActorNode().
GetBlueprint()
class UBlueprint * SSCSEditor::GetBlueprint () const
Provides access to the Blueprint context that's being edited.
GetCollapsedNodes()
void SSCSEditor::GetCollapsedNodes (const FSCSEditorTreeNodePtrType & InNodePtr, TSet< FSCSEditorTreeNodePtrType > & OutCollapsedNodes) const protected
Returns the set of expandable nodes that are currently collapsed in the UI.
GetComponentClassComboButtonVisibility()
EVisibility SSCSEditor::GetComponentClassComboButtonVisibility () const protected
Returns
The visibility of the Add Component combo button
GetComponentsFilterBoxVisibility()
EVisibility SSCSEditor::GetComponentsFilterBoxVisibility () const protected
Returns
The visibility of the components filter box
GetComponentsTreeVisibility()
EVisibility SSCSEditor::GetComponentsTreeVisibility () const protected
Returns
The visibility of the components tree
GetComponentTypeFilterToApply()
TSubclassOf< UActorComponent > SSCSEditor::GetComponentTypeFilterToApply () const protected
Returns
Type of component to filter the tree view with or nullptr if there's no filter.
GetEditBlueprintButtonVisibility()
EVisibility SSCSEditor::GetEditBlueprintButtonVisibility () const protected
Returns
The visibility of the Edit Blueprint button (only visible with an actor instance that is created from a blueprint)
GetEditorMode()
EComponentEditorMode::Type SSCSEditor::GetEditorMode () const inline
Returns
The current editor mode (editing live actors or editing blueprints)
Definition at line 1268 of file SSCSEditor.h.
References EditorMode.
GetFilterText()
FText SSCSEditor::GetFilterText () const
Callback for the action trees to get the filter text.
GetNodeFromActorComponent()
FSCSEditorTreeNodePtrType SSCSEditor::GetNodeFromActorComponent (const UActorComponent * ActorComponent, bool bIncludeAttachedComponents = true) const
Given an actor component, attempts to find an associated tree node.
Parameters
ActorComponent The component associated with the node.
bIncludeAttachedComponents Whether or not to include components attached to each node in the search (default is true).
Returns
A shared pointer to a tree node. The pointer will be invalid if no match could be found.
GetNumSelectedNodes()
int32 SSCSEditor::GetNumSelectedNodes () const inline
Get the number of currently selected tree nodes.
Definition at line 1187 of file SSCSEditor.h.
References SCSTreeWidget.
GetPromoteToBlueprintButtonVisibility()
EVisibility SSCSEditor::GetPromoteToBlueprintButtonVisibility () const protected
Returns
The visibility of the promote to blueprint button (only visible with an actor instance that is not created from a blueprint)
GetRootNodes()
const TArray< FSCSEditorTreeNodePtrType > & SSCSEditor::GetRootNodes () const protected
gets a root nodes of the tree
GetSceneRootNode()
FSCSEditorTreeNodePtrType SSCSEditor::GetSceneRootNode () const
get the root scene node
References GetSceneRootNode().
Referenced by GetSceneRootNode().
GetSelectedEditableObjects()
TArray< UObject * > SSCSEditor::GetSelectedEditableObjects () const
Returns
Array of the editable objects selected in the tree
GetSelectedItemsForContextMenu()
void SSCSEditor::GetSelectedItemsForContextMenu (TArray< FComponentEventConstructionData > & OutSelectedItems) const
Fills the supplied array with the currently selected objects.
Parameters
OutSelectedItems The array to fill.
GetSelectedNodes()
TArray< FSCSEditorTreeNodePtrType > SSCSEditor::GetSelectedNodes () const
Get the currently selected tree nodes.
GetToolButtonsBox()
TSharedPtr< SWidget > SSCSEditor::GetToolButtonsBox ()
Return the button widgets that can add components or create/edit blueprints.
HandleItemDoubleClicked()
void SSCSEditor::HandleItemDoubleClicked (FSCSEditorTreeNodePtrType InItem) protected
Callback when a component item is double clicked.
HighlightTreeNode() [1/2]
void SSCSEditor::HighlightTreeNode (const USCS_Node * Node, FName Property)
Highlight a tree node and, optionally, a property with in it.
Parameters
Node A Reference to the Node SCS_Node to be highlighted
Property The name of the property to be highlighted in the details view
References Property.
HighlightTreeNode() [2/2]
void SSCSEditor::HighlightTreeNode (FName TreeNodeName, const class FPropertyPath & Property)
Highlight a tree node and, optionally, a property with in it.
Parameters
TreeNodeName Name of the treenode to be highlighted
Property The name of the property to be highlighted in the details view
Returns
True if the node was found in this Editor, otherwise false
References Property.
IsComponentSelected()
bool SSCSEditor::IsComponentSelected (const UPrimitiveComponent * PrimComponent) const
Returns true if the specified component is currently selected.
IsEditingAllowed()
bool SSCSEditor::IsEditingAllowed () const
Returns true if editing is allowed.
References IsEditingAllowed().
Referenced by IsEditingAllowed().
IsNodeInSimpleConstructionScript()
bool SSCSEditor::IsNodeInSimpleConstructionScript (USCS_Node * Node) const
Is this node still used by the Simple Construction Script.
MakeTableRowWidget()
TSharedRef< ITableRow > SSCSEditor::MakeTableRowWidget (FSCSEditorTreeNodePtrType InNodePtr, const TSharedRef< STableViewBase > & OwnerTable)
Used by tree control - make a widget for a table row from a node.
References MakeTableRowWidget().
Referenced by MakeTableRowWidget().
OnActorSelected()
void SSCSEditor::OnActorSelected (const ECheckBoxState NewCheckedState)
Called when the Actor is selected.
OnApplyChangesToBlueprint()
void SSCSEditor::OnApplyChangesToBlueprint () const protected
Propagates instance changes to the blueprint.
OnDeleteNodes()
void SSCSEditor::OnDeleteNodes ()
Removes existing selected component nodes from the SCS.
OnDuplicateComponent()
void SSCSEditor::OnDuplicateComponent ()
OnFilterTextChanged()
void SSCSEditor::OnFilterTextChanged (const FText & InFilterText) protected
Recursively updates the filtered state for each component item.
OnFindReferences()
void SSCSEditor::OnFindReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags)
Callbacks to find references of the selected component.
References Flags.
OnGetApplyChangesToBlueprintTooltip()
FText SSCSEditor::OnGetApplyChangesToBlueprintTooltip () const protected
Returns
the tooltip describing how many properties will be applied to the blueprint
OnGetChildrenForTree()
void SSCSEditor::OnGetChildrenForTree (FSCSEditorTreeNodePtrType InNodePtr, TArray< FSCSEditorTreeNodePtrType > & OutChildren)
Used by tree control - get children for a specified node.
References OnGetChildrenForTree().
Referenced by OnGetChildrenForTree().
OnGetResetToBlueprintDefaultsTooltip()
FText SSCSEditor::OnGetResetToBlueprintDefaultsTooltip () const protected
Returns
the tooltip describing how many properties will be reset to the blueprint default
OnIsActorSelected()
ECheckBoxState SSCSEditor::OnIsActorSelected () const
Called to determine if actor is selected.
OnItemScrolledIntoView()
void SSCSEditor::OnItemScrolledIntoView (FSCSEditorTreeNodePtrType InItem, const TSharedPtr< ITableRow > & InWidget) protected
Callback when a component item is scrolled into view.
OnKeyDown()
virtual FReply SSCSEditor::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) virtual
SWidget interface.
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnLevelComponentRequestRename()
void SSCSEditor::OnLevelComponentRequestRename (const UActorComponent * InComponent) protected
Called when the level editor requests a component to be renamed.
OnObjectsReplaced()
void SSCSEditor::OnObjectsReplaced (const TMap< UObject *, UObject * > & OldToNewInstanceMap) protected
Called when component objects are replaced following construction script execution.
OnOpenBlueprintEditor()
void SSCSEditor::OnOpenBlueprintEditor (bool bForceCodeEditing) const protected
Opens the blueprint editor for the blueprint being viewed by the scseditor.
OnPostTick()
void SSCSEditor::OnPostTick (float)
Called at the end of each frame.
OnPromoteToBlueprintClicked()
FReply SSCSEditor::OnPromoteToBlueprintClicked () protected
Called when the promote to blueprint button is clicked.
OnRenameComponent() [1/2]
void SSCSEditor::OnRenameComponent () protected
Requests a rename on the selected component.
OnRenameComponent() [2/2]
void SSCSEditor::OnRenameComponent (TUniquePtr< FScopedTransaction > OngoingCreateTransaction) protected
Requests a rename on the selected component just after creation so that the user can provide the initial component name (overwriting the default generated one), which is considered part of the creation process.
Parameters
OngoingCreateTransaction The ongoing transaction started when the component was created.
OnResetToBlueprintDefaults()
void SSCSEditor::OnResetToBlueprintDefaults () protected
Resets instance changes to the blueprint default.
OnTreeSelectionChanged()
void SSCSEditor::OnTreeSelectionChanged (FSCSEditorTreeNodePtrType InSelectedNodePtr, ESelectInfo::Type SelectInfo)
Called when selection in the tree changes.
PasteNodes()
void SSCSEditor::PasteNodes ()
Pastes previously copied node(s)
PerformComboAddClass()
UActorComponent * SSCSEditor::PerformComboAddClass (TSubclassOf< UActorComponent > ComponentClass, EComponentCreateAction::Type ComponentCreateAction, UObject * AssetOverride) protected
Add a component from the selection in the combo box.
PopulateContextMenu()
void SSCSEditor::PopulateContextMenu (UToolMenu * InMenu) protected
Populate context menu on the fly.
PromoteToBlueprint()
void SSCSEditor::PromoteToBlueprint () const protected
Converts the current actor instance to a blueprint.
RefreshFilteredState()
bool SSCSEditor::RefreshFilteredState (FSCSEditorTreeNodePtrType TreeNode, bool bRecursive) protected
Compares the filter bar's text with the item's component name.
Use bRecursive to refresh the state of child nodes as well. Returns true if the node is set to be filtered out
RefreshSelectionDetails()
void SSCSEditor::RefreshSelectionDetails ()
Forces the details panel to refresh on the same objects.
RegisterContextMenu()
void SSCSEditor::RegisterContextMenu () protected
Registers context menu by name for later access.
RemoveComponentNode()
void SSCSEditor::RemoveComponentNode (FSCSEditorTreeNodePtrType InNodePtr)
Removes an existing component node from the tree.
ReplaceComponentReferencesInTree() [1/2]
void SSCSEditor::ReplaceComponentReferencesInTree (const TArray< FSCSEditorTreeNodePtrType > & Nodes, const TMap< UObject *, UObject * > & OldToNewInstanceMap, bool & OutHasChanges) protected
Update component pointers held by tree nodes if components have been replaced following construction script execution.
ReplaceComponentReferencesInTree() [2/2]
void SSCSEditor::ReplaceComponentReferencesInTree (FSCSEditorActorNodePtrType InActorNode, const TMap< UObject *, UObject * > & OldToNewInstanceMap, bool & OutHasChanges) protected
Helper method to update component pointers held by the given actor node's subtree.
SaveSCSCurrentState()
void SSCSEditor::SaveSCSCurrentState (USimpleConstructionScript * SCSObj) static
Function to save current state of SimpleConstructionScript and nodes associated with it.
Parameters
SimpleContructionScript object reference.
SaveSCSNode()
void SSCSEditor::SaveSCSNode (USCS_Node * Node) static
Function to save the current state of SCS_Node and its children.
Parameters
Reference of the SCS_Node to be saved
SelectNode()
void SSCSEditor::SelectNode (FSCSEditorTreeNodePtrType InNodeToSelect, bool IsCntrlDown)
Select the given tree node.
SelectRoot()
void SSCSEditor::SelectRoot ()
Select the root of the tree.
SetItemExpansionRecursive()
void SSCSEditor::SetItemExpansionRecursive (FSCSEditorTreeNodePtrType Model, bool bInExpansionState)
Handler for recursively expanding/collapsing items.
SetNodeExpansionState()
void SSCSEditor::SetNodeExpansionState (FSCSEditorTreeNodePtrType InNodeToChange, const bool bIsExpanded)
Set the expansion state of a node.
Parameters
InNodeToChange The node to be expanded/collapsed
bIsExpanded True to expand the node, false to collapse it
SetSceneRootNode()
void SSCSEditor::SetSceneRootNode (FSCSEditorTreeNodePtrType NewSceneRootNode)
References SetSceneRootNode().
Referenced by SetSceneRootNode().
SetSelectionOverride()
void SSCSEditor::SetSelectionOverride (UPrimitiveComponent * PrimComponent) const
Assigns a selection override delegate to the specified component.
SetUICustomization()
void SSCSEditor::SetUICustomization (TSharedPtr< ISCSEditorUICustomization > InUICustomization)
Sets UI customizations of this SCSEditor.
SLATE_ARGUMENT()
SSCSEditor::SLATE_ARGUMENT (EComponentEditorMode::Type , EditorMode)
References EditorMode.
SLATE_ATTRIBUTE() [1/3]
IsDiffing PreviewActor SSCSEditor::SLATE_ATTRIBUTE (bool , AllowEditing)
References AllowEditing, HideComponentClassCombo, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
IsDiffing SSCSEditor::SLATE_ATTRIBUTE (class AActor * , ActorContext)
References ActorContext, PreviewActor, and SLATE_ATTRIBUTE().
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/3]
IsDiffing PreviewActor HideComponentClassCombo SSCSEditor::SLATE_ATTRIBUTE (TSubclassOf< UActorComponent > , ComponentTypeFilter)
References ComponentTypeFilter, OnSelectionUpdated, SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_BEGIN_ARGS()
SSCSEditor::SLATE_BEGIN_ARGS (SSCSEditor) inline
Definition at line 1020 of file SSCSEditor.h.
SLATE_EVENT() [1/2]
IsDiffing PreviewActor HideComponentClassCombo OnSelectionUpdated SSCSEditor::SLATE_EVENT (FOnItemDoubleClicked , OnItemDoubleClicked)
References OnHighlightPropertyInDetailsView, OnItemDoubleClicked, and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [2/2]
IsDiffing PreviewActor HideComponentClassCombo OnSelectionUpdated OnHighlightPropertyInDetailsView SSCSEditor::SLATE_EVENT (FSimpleDelegate , OnObjectReplaced) const &
References OnObjectReplaced, SLATE_END_ARGS, and SLATE_EVENT().
TryHandleAssetDragDropOperation()
FReply SSCSEditor::TryHandleAssetDragDropOperation (const FDragDropEvent & DragDropEvent)
Try to handle a drag-drop operation.
UpdateSelectionFromNodes()
void SSCSEditor::UpdateSelectionFromNodes (const TArray< FSCSEditorTreeNodePtrType > & SelectedNodes)
Update any associated selection (e.g.
details view) from the passed in nodes
UpdateTree()
void SSCSEditor::UpdateTree (bool bRegenerateTreeNodes = true)
Refresh the tree control to reflect changes in the SCS.
ViewEvent()
void SSCSEditor::ViewEvent (UBlueprint * Blueprint, const FName EventName, const FComponentEventConstructionData EventData) static protected
Function to view an event for a node.
Parameters
Blueprint the nodes blueprint
EventName the event to view
EventData the event data structure describing the node
Field Documentation
ActorContext
TAttribute<class AActor*> SSCSEditor::ActorContext
Attribute that provides access to the Actor context for which we are viewing/editing the SCS.
Definition at line 1475 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
ActorMenuExtender
TSharedPtr<FExtender> SSCSEditor::ActorMenuExtender private
Definition at line 1512 of file SSCSEditor.h.
AllowEditing
TAttribute<bool> SSCSEditor::AllowEditing
Attribute to indicate whether or not editing is allowed.
Definition at line 1481 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
bAllowTreeUpdates
bool SSCSEditor::bAllowTreeUpdates private
Controls whether or not to allow calls to UpdateTree()
Definition at line 1521 of file SSCSEditor.h.
bEnableComponentEditing
bool SSCSEditor::bEnableComponentEditing private
Flag to enable/disable component editing.
Definition at line 1515 of file SSCSEditor.h.
bIsDiffing
bool SSCSEditor::bIsDiffing private
TRUE if this SCSEditor is currently the target of a diff.
Definition at line 1524 of file SSCSEditor.h.
bUpdatingSelection
bool SSCSEditor::bUpdatingSelection private
Gate to prevent changing the selection while selection change is being broadcast.
Definition at line 1518 of file SSCSEditor.h.
ButtonBox
TSharedPtr<SHorizontalBox> SSCSEditor::ButtonBox private
The tools buttons box.
Definition at line 1530 of file SSCSEditor.h.
CommandList
TSharedPtr< FUICommandList > SSCSEditor::CommandList
Command list for handling actions in the SSCSEditor.
Definition at line 1463 of file SSCSEditor.h.
ComponentTypeFilter
TAttribute<TSubclassOf<UActorComponent> > SSCSEditor::ComponentTypeFilter
Attribute to limit visible nodes to a particular component type when filtering the tree view.
Definition at line 1487 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
DeferredOngoingCreateTransaction
TUniquePtr<FScopedTransaction> SSCSEditor::DeferredOngoingCreateTransaction
Scope the creation of a component which ends when the initial component 'name' is given/accepted by the user, which can be several frames after the component was actually created.
Definition at line 1469 of file SSCSEditor.h.
DeferredRenameRequest
FName SSCSEditor::DeferredRenameRequest
Name of a node that has been requested to be renamed.
Definition at line 1466 of file SSCSEditor.h.
EditorMode
EComponentEditorMode::Type SSCSEditor::EditorMode private
Indicates which editor mode we're in.
Definition at line 1506 of file SSCSEditor.h.
Referenced by GetEditorMode(), and SLATE_ARGUMENT().
ExtensionPanel
TSharedPtr<class SExtensionPanel> SSCSEditor::ExtensionPanel private
SCSEditor UI extension.
Definition at line 1536 of file SSCSEditor.h.
FilterBox
TSharedPtr< SSearchBox > SSCSEditor::FilterBox private
The filter box that handles filtering for the tree.
Definition at line 1527 of file SSCSEditor.h.
HideComponentClassCombo
TAttribute<bool> SSCSEditor::HideComponentClassCombo
Attribute to indicate whether or not the "Add Component" button is visible.
If true, new components cannot be added to the Blueprint.
Definition at line 1484 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
OnHighlightPropertyInDetailsView
FOnHighlightPropertyInDetailsView SSCSEditor::OnHighlightPropertyInDetailsView
Delegate to invoke when the given property should be highlighted in the details view (e.g.
diff).
Definition at line 1496 of file SSCSEditor.h.
Referenced by SLATE_EVENT().
OnItemDoubleClicked
FOnItemDoubleClicked SSCSEditor::OnItemDoubleClicked
Delegate to invoke when an item in the tree is double clicked.
Definition at line 1493 of file SSCSEditor.h.
Referenced by SLATE_EVENT().
OnObjectReplaced
FSimpleDelegate SSCSEditor::OnObjectReplaced
Delegate to invoke when objects within the SCS tree are replaced (eg, via re-instancing from a BP compile)
Definition at line 1499 of file SSCSEditor.h.
Referenced by SLATE_EVENT().
OnSelectionUpdated
FOnSelectionUpdated SSCSEditor::OnSelectionUpdated
Delegate to invoke on selection update.
Definition at line 1490 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
PostTickHandle
FDelegateHandle SSCSEditor::PostTickHandle
Used to unregister from the post tick event.
Definition at line 1472 of file SSCSEditor.h.
PreviewActor
TAttribute<class AActor*> SSCSEditor::PreviewActor
Attribute that provides access to a "preview" Actor context (may not be same as the Actor context that's being edited.
Definition at line 1478 of file SSCSEditor.h.
Referenced by SLATE_ATTRIBUTE().
RootNodes
TArray<FSCSEditorTreeNodePtrType> SSCSEditor::RootNodes private
Root set of tree.
Definition at line 1509 of file SSCSEditor.h.
SCSTreeWidget
TSharedPtr<SSCSTreeType> SSCSEditor::SCSTreeWidget
Tree widget.
Definition at line 1460 of file SSCSEditor.h.
Referenced by GetNumSelectedNodes().
UICustomization
TSharedPtr<ISCSEditorUICustomization> SSCSEditor::UICustomization private
SCSEditor UI customizations.
Definition at line 1533 of file SSCSEditor.h.
The documentation for this class was generated from the following file:
SSCSEditor.h