Unreal Engine 5.6 C++ API: UE::Geometry::FAxisAlignedBox2i Struct Reference
UE::Geometry::FAxisAlignedBox2i Struct Reference
#include "IntBoxTypes.h"
Public Member Functions
FAxisAlignedBox2i ()
FAxisAlignedBox2i (const FVector2i &Min, const FVector2i &Max)
FAxisAlignedBox2i (int32 SquareSize)
FAxisAlignedBox2i (int32 Width, int32 Height)
int32 Area () const
void Contain (const FVector2i &V)
bool Contains (const FVector2i &V) const
FVector2i Diagonal () const
void Expand (int32 Radius)
FVector2i GetCorner (int Index) const
Corners are ordered to follow the perimeter of the bounding rectangle, starting from the (Min.X, Min.Y) corner and ending at (Min.X, Max.Y)
bool IsEmpty () const
bool operator!= (const FAxisAlignedBox2i &Other) const
bool operator== (const FAxisAlignedBox2i &Other) const
Static Public Member Functions
static FAxisAlignedBox2i Empty ()
Data Fields
FVector2i Max
FVector2i Min
Detailed Description
Definition at line 74 of file IntBoxTypes.h.
Constructor & Destructor Documentation
FAxisAlignedBox2i() [1/4]
UE::Geometry::FAxisAlignedBox2i::FAxisAlignedBox2i () inline
Definition at line 79 of file IntBoxTypes.h.
References FAxisAlignedBox2i(), and Empty().
Referenced by FAxisAlignedBox2i(), Empty(), operator!=(), and operator==().
FAxisAlignedBox2i() [2/4]
UE::Geometry::FAxisAlignedBox2i::FAxisAlignedBox2i (const FVector2i & Min, const FVector2i & Max) inline
Definition at line 84 of file IntBoxTypes.h.
References Max, and Min.
FAxisAlignedBox2i() [3/4]
UE::Geometry::FAxisAlignedBox2i::FAxisAlignedBox2i (int32 SquareSize) inline
Definition at line 89 of file IntBoxTypes.h.
References Max, and Min.
FAxisAlignedBox2i() [4/4]
UE::Geometry::FAxisAlignedBox2i::FAxisAlignedBox2i (int32 Width, int32 Height) inline
Definition at line 93 of file IntBoxTypes.h.
References UE::Geometry::Height, Max, Min, and Width.
Member Function Documentation
Area()
int32 UE::Geometry::FAxisAlignedBox2i::Area () const inline
Definition at line 140 of file IntBoxTypes.h.
References TMathUtil< RealType >::Max(), Max, and Min.
Contain()
void UE::Geometry::FAxisAlignedBox2i::Contain (const FVector2i & V) inline
Definition at line 157 of file IntBoxTypes.h.
References Max, Min, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Contains()
bool UE::Geometry::FAxisAlignedBox2i::Contains (const FVector2i & V) const inline
Definition at line 152 of file IntBoxTypes.h.
References Max, Min, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Diagonal()
FVector2i UE::Geometry::FAxisAlignedBox2i::Diagonal () const inline
Definition at line 147 of file IntBoxTypes.h.
References Max, and Min.
Empty()
FAxisAlignedBox2i UE::Geometry::FAxisAlignedBox2i::Empty () inline static
Definition at line 98 of file IntBoxTypes.h.
References FAxisAlignedBox2i().
Referenced by FAxisAlignedBox2i(), and UE::Geometry::TSparseGrid2< ElemType >::TSparseGrid2().
Expand()
void UE::Geometry::FAxisAlignedBox2i::Expand (int32 Radius) inline
Definition at line 132 of file IntBoxTypes.h.
References Max, and Min.
GetCorner()
FVector2i UE::Geometry::FAxisAlignedBox2i::GetCorner (int Index) const inline
Corners are ordered to follow the perimeter of the bounding rectangle, starting from the (Min.X, Min.Y) corner and ending at (Min.X, Max.Y)
Parameters
Index which corner to return, must be in range [0,3]
Returns
Corner of the bounding rectangle
Definition at line 119 of file IntBoxTypes.h.
References check, Max, Min, X, and Y.
IsEmpty()
bool UE::Geometry::FAxisAlignedBox2i::IsEmpty () const inline
Definition at line 127 of file IntBoxTypes.h.
References Max, and Min.
operator!=()
bool UE::Geometry::FAxisAlignedBox2i::operator!= (const FAxisAlignedBox2i & Other) const inline
Definition at line 109 of file IntBoxTypes.h.
References FAxisAlignedBox2i(), Max, Min, and Other.
operator==()
bool UE::Geometry::FAxisAlignedBox2i::operator== (const FAxisAlignedBox2i & Other) const inline
Definition at line 105 of file IntBoxTypes.h.
References FAxisAlignedBox2i(), Max, Min, and Other.
Field Documentation
Max
FVector2i UE::Geometry::FAxisAlignedBox2i::Max
Definition at line 77 of file IntBoxTypes.h.
Referenced by FAxisAlignedBox2i(), FAxisAlignedBox2i(), FAxisAlignedBox2i(), Area(), Contain(), Contains(), Diagonal(), Expand(), GetCorner(), IsEmpty(), operator!=(), and operator==().
Min
FVector2i UE::Geometry::FAxisAlignedBox2i::Min
Definition at line 76 of file IntBoxTypes.h.
Referenced by FAxisAlignedBox2i(), FAxisAlignedBox2i(), FAxisAlignedBox2i(), Area(), Contain(), Contains(), Diagonal(), Expand(), GetCorner(), IsEmpty(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
IntBoxTypes.h