Unreal Engine 5.6 C++ API: ContentBundlePaths Namespace Reference
ContentBundlePaths Namespace Reference
Functions
bool BuildActorDescContainerPackagePath (const FString &InContenBundleMountPoint, const FGuid &InContentBundleGuid, const FString &InLevelPackagePath, FString &OutContainerPackagePath)
bool BuildContentBundleExternalActorPath (const FString &InContenBundleMountPoint, const FGuid &InContentBundleGuid, FString &OutContentBundleRootPath)
FStringView GetActorPathRelativeToExternalActors (FStringView InContentBundleExternalActorPackagePath)
constexpr FStringView GetContentBundleFolder ()
constexpr FStringView GetContentBundleFolderName ()
FGuid GetContentBundleGuidFromExternalActorPackagePath (FStringView InContentBundleExternalActorPackagePath)
FString GetCookedContentBundleLevelFolder (const FContentBundleBase &ContentBundle)
constexpr FStringView GetGeneratedFolder ()
constexpr FStringView GetGeneratedFolderName ()
FStringView GetRelativeExternalActorPackagePath (FStringView InContentBundleExternalActorPackagePath)
FString GetRelativeLevelFolder (const FContentBundleBase &ContentBundle)
FStringView GetRelativePath (FStringView InContentBundlePath)
bool IsAContentBundleExternalActorPackagePath (FStringView InPackagePath)
bool IsAContentBundlePath (FStringView InContentBundlePath)
FString MakeExternalActorPackagePath (const FString &ContentBundleExternalActorFolder, const FString &ActorName)
Variables
constexpr FStringView ContentBundleFolder = TEXTVIEW("/ContentBundle/")
constexpr FStringView GeneratedFolder = TEXTVIEW("/_Generated_/")
Function Documentation
BuildActorDescContainerPackagePath()
bool ContentBundlePaths::BuildActorDescContainerPackagePath (const FString & InContenBundleMountPoint, const FGuid & InContentBundleGuid, const FString & InLevelPackagePath, FString & OutContainerPackagePath)
BuildContentBundleExternalActorPath()
bool ContentBundlePaths::BuildContentBundleExternalActorPath (const FString & InContenBundleMountPoint, const FGuid & InContentBundleGuid, FString & OutContentBundleRootPath)
GetActorPathRelativeToExternalActors()
FStringView ContentBundlePaths::GetActorPathRelativeToExternalActors (FStringView InContentBundleExternalActorPackagePath)
GetContentBundleFolder()
FStringView ContentBundlePaths::GetContentBundleFolder () constexpr
Definition at line 15 of file ContentBundlePaths.h.
References ContentBundleFolder.
Referenced by GetContentBundleFolderName().
GetContentBundleFolderName()
FStringView ContentBundlePaths::GetContentBundleFolderName () constexpr
Definition at line 18 of file ContentBundlePaths.h.
References GetContentBundleFolder().
GetContentBundleGuidFromExternalActorPackagePath()
FGuid ContentBundlePaths::GetContentBundleGuidFromExternalActorPackagePath (FStringView InContentBundleExternalActorPackagePath)
GetCookedContentBundleLevelFolder()
FString ContentBundlePaths::GetCookedContentBundleLevelFolder (const FContentBundleBase & ContentBundle)
GetGeneratedFolder()
FStringView ContentBundlePaths::GetGeneratedFolder () constexpr
Definition at line 25 of file ContentBundlePaths.h.
References GeneratedFolder.
Referenced by GetGeneratedFolderName().
GetGeneratedFolderName()
FStringView ContentBundlePaths::GetGeneratedFolderName () constexpr
Definition at line 28 of file ContentBundlePaths.h.
References GetGeneratedFolder().
GetRelativeExternalActorPackagePath()
FStringView ContentBundlePaths::GetRelativeExternalActorPackagePath (FStringView InContentBundleExternalActorPackagePath)
GetRelativeLevelFolder()
FString ContentBundlePaths::GetRelativeLevelFolder (const FContentBundleBase & ContentBundle)
GetRelativePath()
FStringView ContentBundlePaths::GetRelativePath (FStringView InContentBundlePath)
IsAContentBundleExternalActorPackagePath()
bool ContentBundlePaths::IsAContentBundleExternalActorPackagePath (FStringView InPackagePath)
IsAContentBundlePath()
bool ContentBundlePaths::IsAContentBundlePath (FStringView InContentBundlePath)
MakeExternalActorPackagePath()
FString ContentBundlePaths::MakeExternalActorPackagePath (const FString & ContentBundleExternalActorFolder, const FString & ActorName)
Variable Documentation
ContentBundleFolder
FStringView ContentBundlePaths::ContentBundleFolder = TEXTVIEW("/ContentBundle/") inline constexpr
Definition at line 11 of file ContentBundlePaths.h.
Referenced by GetContentBundleFolder().
GeneratedFolder
FStringView ContentBundlePaths::GeneratedFolder = TEXTVIEW("/_Generated_/") inline constexpr
Definition at line 12 of file ContentBundlePaths.h.
Referenced by GetGeneratedFolder().