Unreal Engine 5.6 C++ API: TUniquePtr< T[], Deleter > Class Template Reference
TUniquePtr< T[], Deleter > Class Template Reference
#include "UniquePtr.h"
Public Types
using ElementType = T
Public Member Functions
FORCEINLINE TUniquePtr ()
Default constructor - initializes the TUniquePtr to null.
TUniquePtr (const TUniquePtr &)=delete
FORCEINLINE TUniquePtr (TUniquePtr &&Other)
Move constructor.
template<typename OtherT, typename OtherDeleter UE_REQUIRES>
FORCEINLINE TUniquePtr (TUniquePtr< OtherT, OtherDeleter > &&Other)
Constructor from rvalues of other (usually less qualified) types.
FORCEINLINE TUniquePtr (TYPE_OF_NULLPTR)
nullptr constructor - initializes the TUniquePtr to null.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr)
Pointer constructor - takes ownership of the pointed-to array.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr, const Deleter &InDeleter)
Pointer constructor - takes ownership of the pointed-to array.
template<typename U UE_REQUIRES>
FORCEINLINE TUniquePtr (U *InPtr, Deleter &&InDeleter)
Pointer constructor - takes ownership of the pointed-to array.
FORCEINLINE ~TUniquePtr ()
Destructor.
FORCEINLINE T * Get () const
Returns a pointer to the owned array without relinquishing ownership.
FORCEINLINE Deleter & GetDeleter ()
Returns a reference to the deleter subobject.
FORCEINLINE const Deleter & GetDeleter () const
Returns a reference to the deleter subobject.
bool IsValid () const
Tests if the TUniquePtr currently owns an array.
FORCEINLINE operator bool () const
operator bool
template<typename RhsT>
FORCEINLINE bool operator!= (const TUniquePtr< RhsT > &Rhs) const
Inequality comparison operator.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
Inequality comparison operator against nullptr.
FORCEINLINE DummyT & operator* () const
Dereference operator.
FORCEINLINE T * operator-> () const
Indirection operator.
TUniquePtr & operator= (const TUniquePtr &)=delete
FORCEINLINE TUniquePtr & operator= (TUniquePtr &&Other)
Move assignment operator.
template<typename OtherT, typename OtherDeleter UE_REQUIRES>
FORCEINLINE TUniquePtr & operator= (TUniquePtr< OtherT, OtherDeleter > &&Other)
Assignment operator for rvalues of other (usually less qualified) types.
FORCEINLINE TUniquePtr & operator= (TYPE_OF_NULLPTR)
Nullptr assignment operator.
template<typename RhsT>
FORCEINLINE bool operator== (const TUniquePtr< RhsT > &Rhs) const
Equality comparison operator.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
Equality comparison operator against nullptr.
FORCEINLINE T & operator[] (SIZE_T Index) const
Indexing operator.
FORCEINLINE T * Release ()
Relinquishes control of the owned array to the caller and nulls the TUniquePtr.
FORCEINLINE void Reset (TYPE_OF_NULLPTR InPtr=nullptr)
template<typename U UE_REQUIRES>
FORCEINLINE void Reset (U *InPtr)
Gives the TUniquePtr a new array to own, destroying any previously-owned array.
Private Types
using PtrType
Private Member Functions
DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES (TUniquePtr, NonVirtual, Deleter)
LAYOUT_FIELD (PtrType, Ptr)
Private Attributes
T * Ptr
Friends
template<typename OtherT, typename OtherDeleter>
class TUniquePtr
Detailed Description
template<typename T, typename Deleter>
class TUniquePtr< T[], Deleter >
Definition at line 438 of file UniquePtr.h.
Member Typedef Documentation
ElementType
template<typename T, typename Deleter> using TUniquePtr< T[], Deleter >::ElementType = T
Definition at line 444 of file UniquePtr.h.
PtrType
using TUniquePtr< T, Deleter >::PtrType private
Definition at line 378 of file UniquePtr.h.
Constructor & Destructor Documentation
TUniquePtr() [1/8]
template<typename T, typename Deleter> TUniquePtr< T[], Deleter >::TUniquePtr (const TUniquePtr< T[], Deleter > &) delete
References TUniquePtr.
TUniquePtr() [2/8]
template<typename T, typename Deleter> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr () inline
Default constructor - initializes the TUniquePtr to null.
Definition at line 453 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
TUniquePtr() [3/8]
template<typename T, typename Deleter> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (U * InPtr) inline explicit
Pointer constructor - takes ownership of the pointed-to array.
Parameters
InPtr The pointed-to array to take ownership of.
Definition at line 468 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
TUniquePtr() [4/8]
template<typename T, typename Deleter> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (U * InPtr, Deleter && InDeleter) inline explicit
Pointer constructor - takes ownership of the pointed-to array.
Parameters
InPtr The pointed-to array to take ownership of.
Definition at line 483 of file UniquePtr.h.
References FORCEINLINE, MoveTemp(), and Ptr.
TUniquePtr() [5/8]
template<typename T, typename Deleter> template<typename U UE_REQUIRES> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (U * InPtr, const Deleter & InDeleter) inline explicit
Pointer constructor - takes ownership of the pointed-to array.
Parameters
InPtr The pointed-to array to take ownership of.
Definition at line 498 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
TUniquePtr() [6/8]
template<typename T, typename Deleter> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (TYPE_OF_NULLPTR) inline
nullptr constructor - initializes the TUniquePtr to null.
Definition at line 507 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
TUniquePtr() [7/8]
template<typename T, typename Deleter> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (TUniquePtr< T[], Deleter > && Other) inline
Move constructor.
Definition at line 516 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, GetDeleter(), MoveTemp(), Other, and Ptr.
TUniquePtr() [8/8]
template<typename T, typename Deleter> template<typename OtherT, typename OtherDeleter UE_REQUIRES> FORCEINLINE TUniquePtr< T[], Deleter >::TUniquePtr (TUniquePtr< OtherT, OtherDeleter > && Other) inline
Constructor from rvalues of other (usually less qualified) types.
Definition at line 531 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, GetDeleter(), MoveTemp(), Other, and Ptr.
~TUniquePtr()
template<typename T, typename Deleter> FORCEINLINE TUniquePtr< T[], Deleter >::~TUniquePtr () inline
Destructor.
Definition at line 594 of file UniquePtr.h.
References FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), and Ptr.
Member Function Documentation
DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES()
TUniquePtr< T, Deleter >::DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES (TUniquePtr< T[], Deleter > , NonVirtual , Deleter) private
Get()
template<typename T, typename Deleter> FORCEINLINE T * TUniquePtr< T[], Deleter >::Get () const inline nodiscard
Returns a pointer to the owned array without relinquishing ownership.
Returns
A copy of the pointer to the array owned by the TUniquePtr, or nullptr if no array is being owned.
Definition at line 634 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
GetDeleter() [1/2]
template<typename T, typename Deleter> FORCEINLINE Deleter & TUniquePtr< T[], Deleter >::GetDeleter () inline nodiscard
Returns a reference to the deleter subobject.
Returns
A reference to the deleter.
Definition at line 681 of file UniquePtr.h.
References FORCEINLINE.
Referenced by TUniquePtr(), and TUniquePtr().
GetDeleter() [2/2]
template<typename T, typename Deleter> FORCEINLINE const Deleter & TUniquePtr< T[], Deleter >::GetDeleter () const inline nodiscard
Returns a reference to the deleter subobject.
Returns
A reference to the deleter.
Definition at line 691 of file UniquePtr.h.
References FORCEINLINE.
IsValid()
template<typename T, typename Deleter> bool TUniquePtr< T[], Deleter >::IsValid () const inline nodiscard
Tests if the TUniquePtr currently owns an array.
Returns
true if the TUniquePtr currently owns an array, false otherwise.
Definition at line 604 of file UniquePtr.h.
References Ptr.
LAYOUT_FIELD()
TUniquePtr< T, Deleter >::LAYOUT_FIELD (PtrType , Ptr) private
operator bool()
template<typename T, typename Deleter> FORCEINLINE TUniquePtr< T[], Deleter >::operator bool () const inline explicit nodiscard
operator bool
Returns
true if the TUniquePtr currently owns an array, false otherwise.
Definition at line 614 of file UniquePtr.h.
References FORCEINLINE, and TUniquePtr< T, Deleter >::IsValid().
operator!=() [1/2]
template<typename T, typename Deleter> template<typename RhsT> FORCEINLINE bool TUniquePtr< T[], Deleter >::operator!= (const TUniquePtr< RhsT > & Rhs) const inline nodiscard
Inequality comparison operator.
Parameters
Lhs The first TUniquePtr to compare.
Rhs The second TUniquePtr to compare.
Returns
false if the two TUniquePtrs are logically substitutable for each other, true otherwise.
Definition at line 736 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, and TUniquePtr< T, Deleter >::Get().
operator!=() [2/2]
template<typename T, typename Deleter> FORCEINLINE bool TUniquePtr< T[], Deleter >::operator!= (TYPE_OF_NULLPTR) const inline nodiscard
Inequality comparison operator against nullptr.
Parameters
Rhs The TUniquePtr to compare.
Returns
true if the TUniquePtr is not null, false otherwise.
Definition at line 748 of file UniquePtr.h.
References FORCEINLINE, and TUniquePtr< T, Deleter >::IsValid().
operator*()
FORCEINLINE DummyT & TUniquePtr< T, Deleter >::operator* () const inline nodiscard
Dereference operator.
Returns
A reference to the object owned by the TUniquePtr.
Definition at line 314 of file UniquePtr.h.
operator->()
FORCEINLINE T * TUniquePtr< T, Deleter >::operator-> () const inline nodiscard
Indirection operator.
Returns
A pointer to the object owned by the TUniquePtr.
Definition at line 300 of file UniquePtr.h.
operator=() [1/4]
template<typename T, typename Deleter> TUniquePtr & TUniquePtr< T[], Deleter >::operator= (const TUniquePtr< T[], Deleter > &) delete
References TUniquePtr.
operator=() [2/4]
template<typename T, typename Deleter> FORCEINLINE TUniquePtr & TUniquePtr< T[], Deleter >::operator= (TUniquePtr< T[], Deleter > && Other) inline
Move assignment operator.
Definition at line 541 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), MoveTemp(), Other, and Ptr.
operator=() [3/4]
template<typename T, typename Deleter> template<typename OtherT, typename OtherDeleter UE_REQUIRES> FORCEINLINE TUniquePtr & TUniquePtr< T[], Deleter >::operator= (TUniquePtr< OtherT, OtherDeleter > && Other) inline
Assignment operator for rvalues of other (usually less qualified) types.
Definition at line 565 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), MoveTemp(), Other, and Ptr.
operator=() [4/4]
template<typename T, typename Deleter> FORCEINLINE TUniquePtr & TUniquePtr< T[], Deleter >::operator= (TYPE_OF_NULLPTR) inline
Nullptr assignment operator.
Definition at line 581 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), and Ptr.
operator==() [1/2]
template<typename T, typename Deleter> template<typename RhsT> FORCEINLINE bool TUniquePtr< T[], Deleter >::operator== (const TUniquePtr< RhsT > & Rhs) const inline nodiscard
Equality comparison operator.
Parameters
Lhs The first TUniquePtr to compare.
Rhs The second TUniquePtr to compare.
Returns
true if the two TUniquePtrs are logically substitutable for each other, false otherwise.
Definition at line 709 of file UniquePtr.h.
References TUniquePtr, FORCEINLINE, and TUniquePtr< T, Deleter >::Get().
operator==() [2/2]
template<typename T, typename Deleter> FORCEINLINE bool TUniquePtr< T[], Deleter >::operator== (TYPE_OF_NULLPTR) const inline nodiscard
Equality comparison operator against nullptr.
Parameters
Lhs The TUniquePtr to compare.
Returns
true if the TUniquePtr is null, false otherwise.
Definition at line 721 of file UniquePtr.h.
References FORCEINLINE, and TUniquePtr< T, Deleter >::IsValid().
operator[]()
template<typename T, typename Deleter> FORCEINLINE T & TUniquePtr< T[], Deleter >::operator[] (SIZE_T Index) const inline nodiscard
Indexing operator.
Returns
A reference to the object at the specified index by the TUniquePtr.
Definition at line 624 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
Release()
template<typename T, typename Deleter> FORCEINLINE T * TUniquePtr< T[], Deleter >::Release () inline nodiscard
Relinquishes control of the owned array to the caller and nulls the TUniquePtr.
Returns
The pointer to the array that was owned by the TUniquePtr, or nullptr if no array was being owned.
Definition at line 644 of file UniquePtr.h.
References FORCEINLINE, and Ptr.
Reset() [1/2]
template<typename T, typename Deleter> FORCEINLINE void TUniquePtr< T[], Deleter >::Reset (TYPE_OF_NULLPTR InPtr = nullptr) inline
Definition at line 668 of file UniquePtr.h.
References FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), and Ptr.
Reset() [2/2]
template<typename T, typename Deleter> template<typename U UE_REQUIRES> FORCEINLINE void TUniquePtr< T[], Deleter >::Reset (U * InPtr) inline
Gives the TUniquePtr a new array to own, destroying any previously-owned array.
Parameters
InPtr A pointer to the array to take ownership of.
Definition at line 660 of file UniquePtr.h.
References FORCEINLINE, TUniquePtr< T, Deleter >::GetDeleter(), and Ptr.
Friends And Related Symbol Documentation
TUniquePtr
template<typename T, typename Deleter> template<typename OtherT, typename OtherDeleter> friend class TUniquePtr friend
Definition at line 441 of file UniquePtr.h.
References TUniquePtr.
Referenced by TUniquePtr, TUniquePtr(), TUniquePtr(), TUniquePtr(), operator!=(), operator=(), operator=(), operator=(), operator=(), and operator==().
Field Documentation
Ptr
template<typename T, typename Deleter> T* TUniquePtr< T[], Deleter >::Ptr private
Definition at line 697 of file UniquePtr.h.
Referenced by TUniquePtr(), TUniquePtr(), TUniquePtr(), TUniquePtr(), TUniquePtr(), TUniquePtr(), TUniquePtr(), ~TUniquePtr(), Get(), IsValid(), operator=(), operator=(), operator=(), operator[](), Release(), Reset(), and Reset().
The documentation for this class was generated from the following file:
UniquePtr.h