Unreal Engine 5.6 C++ Documentation: UNavMovementComponent Class Reference
UNavMovementComponent Class Reference
NavMovementComponent defines base functionality for MovementComponents that move any 'agent' that may be involved in AI pathfinding.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/NavMovementComponent.h>
Public Member Functions
virtual UObject * GetOwnerAsObject () const override
Get the owner of the object consuming nav movement.
virtual TObjectPtr< UObject > GetUpdatedObject () const override
Get the component this movement component is updating.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const override
Get axis-aligned cylinder around this actor, used for simple collision checks in nav movement.
virtual FVector GetSimpleCollisionCylinderExtent () const override
Returns collision extents vector for this object, based on GetSimpleCollisionCylinder.
virtual FVector GetForwardVector () const override
Get forward vector of the object being driven by nav movement.
virtual FVector GetVelocityForNavMovement () const override
Get the current velocity of the movement component.
virtual float GetMaxSpeedForNavMovement () const override
Get maximum movement speed of the agent.
virtual void StopMovementImmediately () override
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
void SetUpdateNavAgentWithOwnersCollisions (bool bUpdateWithOwner)
bool ShouldUpdateNavAgentWithOwnersCollision () const
FVector GetActorLocation () const
Returns location of controlled actor - meaning center of collision bounding box.
virtual FVector GetActorFeetLocation () const
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
virtual FBasedPosition GetActorFeetLocationBased () const
Returns based location of controlled actor.
FVector GetActorNavLocation () const
Returns navigation location of controlled actor.
FTransform GetActorTransform () const
Returns the full world-coordinates transform of the associated scene component (the UpdatedComponent)
virtual FVector GetLocation () const override
Returns location of controlled actor - meaning center of collision bounding box.
virtual FVector GetFeetLocation () const override
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
virtual FBasedPosition GetFeetLocationBased () const override
Returns based location of controlled actor.
virtual void Serialize (FArchive &Ar) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void UpdateNavAgent (const UObject &ObjectToUpdateFrom) override
Set nav agent properties from an object.
virtual void RequestDirectMove (const FVector &MoveVelocity, bool bForceMaxSpeed) override
path following: request new velocity
virtual void RequestPathMove (const FVector &MoveInput) override
path following: request new move input (normal vector = full strength)
virtual bool CanStopPathFollowing () const override
check if current move target can be reached right now if positions are matching (e.g.
virtual FNavMovementProperties * GetNavMovementProperties () override
Get Nav movement props struct this component uses.
virtual const FNavMovementProperties & GetNavMovementProperties () const override
Returns the NavMovementProps(const)
void ClearFixedBrakingDistance ()
clears fixed braking distance
virtual void SetPathFollowingAgent (IPathFollowingAgentInterface *InPathFollowingAgent) override
Set the path following agent this interface uses.
virtual IPathFollowingAgentInterface * GetPathFollowingAgent () override
Get path following agent this interface uses.
virtual const IPathFollowingAgentInterface * GetPathFollowingAgent () const override
Get path following agent this interface uses(const)
const FNavAgentProperties & GetNavAgentPropertiesRef () const override
Returns the NavAgentProps(const)
FNavAgentProperties & GetNavAgentPropertiesRef () override
Returns the NavAgentProps.
virtual void ResetMoveState () override
Resets runtime movement state to character's movement capabilities.
virtual bool CanStartPathFollowing () const override
Returns true if path following can start.
bool IsJumpAllowed () const
Returns true if component is allowed to jump.
void SetJumpAllowed (bool bAllowed)
Sets whether this component is allowed to jump.
virtual bool IsCrouching () const override
Returns true if currently crouching.
virtual bool IsFalling () const override
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
virtual bool IsMovingOnGround () const override
Returns true if currently moving on the ground (e.g.
virtual bool IsSwimming () const override
Returns true if currently swimming (moving through a fluid volume)
virtual bool IsFlying () const override
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
virtual void RegisterComponentTickFunctions (bool bRegister) override
virtual void PostLoad () override
virtual void Deactivate () override
virtual void InitializeComponent () override
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
virtual void OnRegister () override
Overridden to update component properties that should be updated while being edited.
virtual float GetGravityZ () const
Returns gravity that affects this component.
virtual float GetMaxSpeed () const
Returns maximum speed of component in current movement mode.
virtual bool IsExceedingMaxSpeed (float MaxSpeed) const
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
virtual bool ShouldSkipUpdate (float DeltaTime) const
Possibly skip update if moved component is not rendered or can't move.
virtual APhysicsVolume * GetPhysicsVolume () const
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
virtual void PhysicsVolumeChanged (class APhysicsVolume *NewVolume)
Delegate when PhysicsVolume of UpdatedComponent has been changed.
virtual void SetUpdatedComponent (USceneComponent *NewUpdatedComponent)
Assign the component we move and update.
virtual bool IsInWater () const
Returns true if it's in PhysicsVolume with water flag.
virtual void UpdateTickRegistration ()
Update tick registration state, determined by bAutoUpdateTickRegistration.
virtual void HandleImpact (const FHitResult &Hit, float TimeSlice=0.f, const FVector &MoveDelta=FVector::ZeroVector)
Called for Blocking impact.
virtual void UpdateComponentVelocity ()
Update ComponentVelocity of UpdatedComponent.
virtual void InitCollisionParams (FCollisionQueryParams &OutParams, FCollisionResponseParams &OutResponseParam) const
Initialize collision params appropriately based on our collision settings.
virtual bool OverlapTest (const FVector &Location, const FQuat &RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape &CollisionShape, const AActor *IgnoreActor) const
Return true if the given collision shape overlaps other geometry at the given location and rotation.
bool MoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool MoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
bool K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult &OutHit, bool bSweep=true, bool bTeleport=false)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool SafeMoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
bool SafeMoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
virtual FVector GetPenetrationAdjustment (const FHitResult &Hit) const
Calculate a movement adjustment to try to move out of a penetration from a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Try to move out of penetration in an object after a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FRotator &NewRotation)
virtual FVector ComputeSlideVector (const FVector &Delta, const float Time, const FVector &Normal, const FHitResult &Hit) const
Compute a vector to slide along a surface, given an attempted move, time, and normal.
virtual float SlideAlongSurface (const FVector &Delta, float Time, const FVector &Normal, FHitResult &Hit, bool bHandleImpact=false)
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
virtual void TwoWallAdjust (FVector &Delta, const FHitResult &Hit, const FVector &OldHitNormal) const
Compute a movement direction when contacting two surfaces.
virtual void AddRadialForce (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff)
Adds force from radial force components.
virtual void AddRadialImpulse (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange)
Adds impulse from radial force components.
virtual void SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting)
Set the plane constraint axis setting.
EPlaneConstraintAxisSetting GetPlaneConstraintAxisSetting () const
Get the plane constraint axis setting.
virtual void SetPlaneConstraintNormal (FVector PlaneNormal)
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintFromVectors (FVector Forward, FVector Up)
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintOrigin (FVector PlaneOrigin)
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintEnabled (bool bEnabled)
Sets whether or not the plane constraint is enabled.
const FVector & GetPlaneConstraintNormal () const
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
const FVector & GetPlaneConstraintOrigin () const
Get the plane constraint origin.
virtual FVector ConstrainDirectionToPlane (FVector Direction) const
Constrain a direction vector to the plane constraint, if enabled.
virtual FVector ConstrainLocationToPlane (FVector Location) const
Constrain a position vector to the plane constraint, if enabled.
virtual FVector ConstrainNormalToPlane (FVector Normal) const
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
virtual void SnapUpdatedComponentToPlane ()
Snap the updated component to the plane constraint, if enabled.
virtual void OnTeleported ()
Called by owning Actor upon successful teleport from AActor::TeleportTo().
virtual UE_API void StopActiveMovement ()
Stops applying further movement (usually zeros acceleration).
virtual UE_API void StopMovementKeepPathing ()
Stops movement immediately (reset velocity) but keeps following current path.
UE_API FVector GetNavLocation () const
Returns navigation location of controlled agent.
virtual UE_API float GetPathFollowingBrakingDistance (float MaxSpeed) const
Returns braking distance for acceleration driven path following.
UE_API void SetFixedBrakingDistance (float DistanceToEndOfPath)
Set fixed braking distance.
UE_API bool UseAccelerationForPathFollowing () const
Returns true if acceleration should be used for path following.
virtual bool CanEverCrouch () const
Returns true if agent can crouch.
virtual bool CanEverJump () const
Returns true if agent can jump.
virtual bool CanEverMoveOnGround () const
Returns true if agent can move along the ground (walk, drive, etc)
virtual bool CanEverSwim () const
Returns true if agent can swim.
virtual bool CanEverFly () const
Returns true if agent can fly.
Static Public Member Functions
static void PhysicsLockedAxisSettingChanged ()
Public Attributes
FNavAgentProperties NavAgentProps
Properties that define how the component can move.
FMovementProperties MovementState
Expresses runtime state of character's movement.
uint8 bUpdateOnlyIfRendered:1
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
uint8 bAutoUpdateTickRegistration:1
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
uint8 bTickBeforeOwner:1
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
uint8 bAutoRegisterUpdatedComponent:1
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
uint8 bConstrainToPlane:1
If true, movement will be constrained to a plane.
uint8 bSnapToPlaneAtStart:1
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
uint8 bAutoRegisterPhysicsVolumeUpdates:1
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
uint8 bComponentShouldUpdatePhysicsVolume:1
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Protected Member Functions
FVector GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const
Helper to compute the plane constraint axis from the current setting.
virtual bool MoveUpdatedComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
virtual bool ResolvePenetrationImpl (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Protected Attributes
float FixedPathBrakingDistance_DEPRECATED
Braking distance override used with acceleration driven path following (bUseAccelerationForPaths)
uint8 bUpdateNavAgentWithOwnersCollision_DEPRECATED:1
If set to true NavAgentProps' radius and height will be updated with Owner's collision capsule size.
uint8 bUseAccelerationForPaths_DEPRECATED: 1
If set, pathfollowing will control character movement via acceleration values.
uint8 bUseFixedBrakingDistanceForPaths_DEPRECATED: 1
If set, FixedPathBrakingDistance will be used for path following deceleration.
uint8 bStopMovementAbortPaths_DEPRECATED:1
If set, StopActiveMovement call will abort current path following request.
FNavMovementProperties NavMovementProperties
FVector PlaneConstraintNormal
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
FVector PlaneConstraintOrigin
The origin of the plane that constrains movement, if plane constraint is enabled.
Detailed Description
NavMovementComponent defines base functionality for MovementComponents that move any 'agent' that may be involved in AI pathfinding.
Definition at line 25 of file NavMovementComponent.h.
Member Function Documentation
AddRadialForce()
virtual void UMovementComponent::AddRadialForce (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff) virtual inherited
Adds force from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
Reimplemented in UCharacterMovementComponent.
References AddRadialForce().
AddRadialImpulse()
virtual void UMovementComponent::AddRadialImpulse (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange) virtual inherited
Adds impulse from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
bVelChange If true, the Strength is taken as a change in velocity instead of an impulse (ie. mass will have no effect).
Reimplemented in UCharacterMovementComponent.
References AddRadialImpulse().
CanEverCrouch()
virtual bool INavMovementInterface::CanEverCrouch () const inline virtual inherited
Returns true if agent can crouch.
Definition at line 149 of file NavMovementInterface.h.
References CanEverCrouch(), and GetNavAgentPropertiesRef().
CanEverFly()
virtual bool INavMovementInterface::CanEverFly () const inline virtual inherited
Returns true if agent can fly.
Definition at line 161 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverJump()
virtual bool INavMovementInterface::CanEverJump () const inline virtual inherited
Returns true if agent can jump.
Definition at line 152 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverMoveOnGround()
virtual bool INavMovementInterface::CanEverMoveOnGround () const inline virtual inherited
Returns true if agent can move along the ground (walk, drive, etc)
Definition at line 155 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverSwim()
virtual bool INavMovementInterface::CanEverSwim () const inline virtual inherited
Returns true if agent can swim.
Definition at line 158 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanStartPathFollowing()
virtual bool UNavMovementComponent::CanStartPathFollowing () const inline override virtual
Returns true if path following can start.
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 159 of file NavMovementComponent.h.
CanStopPathFollowing()
virtual bool UNavMovementComponent::CanStopPathFollowing () const override virtual
check if current move target can be reached right now if positions are matching (e.g.
performing scripted move and can't stop)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
ClearFixedBrakingDistance()
void UNavMovementComponent::ClearFixedBrakingDistance ()
clears fixed braking distance
ComputeSlideVector()
virtual FVector UMovementComponent::ComputeSlideVector (const FVector & Delta, const float Time, const FVector & Normal, const FHitResult & Hit) const virtual inherited
Compute a vector to slide along a surface, given an attempted move, time, and normal.
Parameters
Delta Attempted move.
Time Amount of move to apply (between 0 and 1).
Normal Normal opposed to movement. Not necessarily equal to Hit.Normal.
Hit HitResult of the move that resulted in the slide.
Reimplemented in UCharacterMovementComponent.
References ComputeSlideVector().
ConstrainDirectionToPlane()
virtual FVector UMovementComponent::ConstrainDirectionToPlane (FVector Direction) const virtual inherited
Constrain a direction vector to the plane constraint, if enabled.
See also
SetPlaneConstraint
References ConstrainDirectionToPlane().
ConstrainLocationToPlane()
virtual FVector UMovementComponent::ConstrainLocationToPlane (FVector Location) const virtual inherited
Constrain a position vector to the plane constraint, if enabled.
References ConstrainLocationToPlane(), and Location.
ConstrainNormalToPlane()
virtual FVector UMovementComponent::ConstrainNormalToPlane (FVector Normal) const virtual inherited
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
References ConstrainNormalToPlane().
Deactivate()
virtual void UMovementComponent::Deactivate () override virtual inherited
Reimplemented in UCharacterMovementComponent.
GetActorFeetLocation()
virtual FVector UNavMovementComponent::GetActorFeetLocation () const inline virtual
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
Reimplemented in UCharacterMovementComponent.
Definition at line 104 of file NavMovementComponent.h.
GetActorFeetLocationBased()
virtual FBasedPosition UNavMovementComponent::GetActorFeetLocationBased () const virtual
Returns based location of controlled actor.
GetActorLocation()
FVector UNavMovementComponent::GetActorLocation () const inline
Returns location of controlled actor - meaning center of collision bounding box.
Definition at line 102 of file NavMovementComponent.h.
GetActorNavLocation()
FVector UNavMovementComponent::GetActorNavLocation () const inline
Returns navigation location of controlled actor.
Definition at line 108 of file NavMovementComponent.h.
GetActorTransform()
FTransform UNavMovementComponent::GetActorTransform () const inline
Returns the full world-coordinates transform of the associated scene component (the UpdatedComponent)
Definition at line 110 of file NavMovementComponent.h.
GetFeetLocation()
virtual FVector UNavMovementComponent::GetFeetLocation () const inline override virtual
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
Implements INavMovementInterface.
Definition at line 115 of file NavMovementComponent.h.
References GetActorFeetLocation().
GetFeetLocationBased()
virtual FBasedPosition UNavMovementComponent::GetFeetLocationBased () const inline override virtual
Returns based location of controlled actor.
Implements INavMovementInterface.
Definition at line 117 of file NavMovementComponent.h.
References GetActorFeetLocationBased().
GetForwardVector()
virtual FVector UNavMovementComponent::GetForwardVector () const override virtual
Get forward vector of the object being driven by nav movement.
Implements INavMovementInterface.
GetGravityZ()
virtual float UMovementComponent::GetGravityZ () const virtual inherited
Returns gravity that affects this component.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
References GetGravityZ(), and GetMaxSpeed().
GetLocation()
virtual FVector UNavMovementComponent::GetLocation () const inline override virtual
Returns location of controlled actor - meaning center of collision bounding box.
Implements INavMovementInterface.
Definition at line 113 of file NavMovementComponent.h.
References GetActorLocation().
GetMaxSpeed()
float UMovementComponent::GetMaxSpeed () const inline virtual inherited
Returns maximum speed of component in current movement mode.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
Definition at line 466 of file MovementComponent.h.
GetMaxSpeedForNavMovement()
virtual float UNavMovementComponent::GetMaxSpeedForNavMovement () const inline override virtual
Get maximum movement speed of the agent.
Implements INavMovementInterface.
Definition at line 93 of file NavMovementComponent.h.
References UMovementComponent::GetMaxSpeed().
GetNavAgentPropertiesRef() [1/2]
const FNavAgentProperties & UNavMovementComponent::GetNavAgentPropertiesRef () const inline override virtual
Returns the NavAgentProps(const)
Implements INavMovementInterface.
Definition at line 151 of file NavMovementComponent.h.
References NavAgentProps.
GetNavAgentPropertiesRef() [2/2]
FNavAgentProperties & UNavMovementComponent::GetNavAgentPropertiesRef () inline override virtual
Returns the NavAgentProps.
Implements INavMovementInterface.
Definition at line 153 of file NavMovementComponent.h.
References NavAgentProps.
GetNavLocation()
UE_API FVector INavMovementInterface::GetNavLocation () const inherited
Returns navigation location of controlled agent.
References GetNavLocation(), and UE_API.
GetNavMovementProperties() [1/2]
virtual const FNavMovementProperties & UNavMovementComponent::GetNavMovementProperties () const inline override virtual
Returns the NavMovementProps(const)
Implements INavMovementInterface.
Definition at line 141 of file NavMovementComponent.h.
References NavMovementProperties.
GetNavMovementProperties() [2/2]
virtual FNavMovementProperties * UNavMovementComponent::GetNavMovementProperties () inline override virtual
Get Nav movement props struct this component uses.
Implements INavMovementInterface.
Definition at line 139 of file NavMovementComponent.h.
References NavMovementProperties.
GetOwnerAsObject()
virtual UObject * UNavMovementComponent::GetOwnerAsObject () const inline override virtual
Get the owner of the object consuming nav movement.
Implements INavMovementInterface.
Definition at line 75 of file NavMovementComponent.h.
References GetOwnerAsObject().
GetPathFollowingAgent() [1/2]
virtual const IPathFollowingAgentInterface * UNavMovementComponent::GetPathFollowingAgent () const inline override virtual
Get path following agent this interface uses(const)
Implements INavMovementInterface.
Definition at line 148 of file NavMovementComponent.h.
GetPathFollowingAgent() [2/2]
virtual IPathFollowingAgentInterface * UNavMovementComponent::GetPathFollowingAgent () inline override virtual
Get path following agent this interface uses.
Implements INavMovementInterface.
Definition at line 147 of file NavMovementComponent.h.
GetPathFollowingBrakingDistance()
virtual UE_API float INavMovementInterface::GetPathFollowingBrakingDistance (float MaxSpeed) const virtual inherited
Returns braking distance for acceleration driven path following.
Reimplemented in UCharacterMovementComponent.
References GetPathFollowingBrakingDistance(), and UE_API.
GetPenetrationAdjustment()
virtual FVector UMovementComponent::GetPenetrationAdjustment (const FHitResult & Hit) const virtual inherited
Calculate a movement adjustment to try to move out of a penetration from a failed move.
Parameters
Hit the result of the failed move
Returns
The adjustment to use after a failed move, or a zero vector if no attempt should be made.
Reimplemented in UCharacterMovementComponent.
References GetPenetrationAdjustment(), and ResolvePenetration().
GetPhysicsVolume()
virtual APhysicsVolume * UMovementComponent::GetPhysicsVolume () const virtual inherited
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
References GetPhysicsVolume().
GetPlaneConstraintAxisSetting()
EPlaneConstraintAxisSetting UMovementComponent::GetPlaneConstraintAxisSetting () const inline inherited
Get the plane constraint axis setting.
Definition at line 477 of file MovementComponent.h.
References EPlaneConstraintAxisSetting.
GetPlaneConstraintNormal()
const FVector & UMovementComponent::GetPlaneConstraintNormal () const inherited
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
References GetPlaneConstraintNormal().
GetPlaneConstraintNormalFromAxisSetting()
FVector UMovementComponent::GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const protected inherited
Helper to compute the plane constraint axis from the current setting.
Parameters
AxisSetting Setting to use when computing the axis.
Returns
Plane constraint axis/normal.
References EPlaneConstraintAxisSetting, and GetPlaneConstraintNormalFromAxisSetting().
GetPlaneConstraintOrigin()
const FVector & UMovementComponent::GetPlaneConstraintOrigin () const inherited
Get the plane constraint origin.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
Returns
The origin of the plane that constrains movement, if the plane constraint is enabled.
References GetPlaneConstraintOrigin().
GetSimpleCollisionCylinder()
virtual void UNavMovementComponent::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const override virtual
Get axis-aligned cylinder around this actor, used for simple collision checks in nav movement.
Implements INavMovementInterface.
GetSimpleCollisionCylinderExtent()
virtual FVector UNavMovementComponent::GetSimpleCollisionCylinderExtent () const override virtual
Returns collision extents vector for this object, based on GetSimpleCollisionCylinder.
Implements INavMovementInterface.
GetUpdatedObject()
virtual TObjectPtr< UObject > UNavMovementComponent::GetUpdatedObject () const inline override virtual
Get the component this movement component is updating.
Implements INavMovementInterface.
Definition at line 78 of file NavMovementComponent.h.
GetVelocityForNavMovement()
virtual FVector UNavMovementComponent::GetVelocityForNavMovement () const inline override virtual
Get the current velocity of the movement component.
Implements INavMovementInterface.
Definition at line 91 of file NavMovementComponent.h.
References GetVelocityForNavMovement().
HandleImpact()
virtual void UMovementComponent::HandleImpact (const FHitResult & Hit, float TimeSlice = 0.f, const FVector & MoveDelta = FVector::ZeroVector) virtual inherited
Called for Blocking impact.
Parameters
Hit Describes the collision.
TimeSlice Time period for the simulation that produced this hit. Useful for putting Hit.Time in context. Can be zero in certain situations where it's not appropriate, be sure to handle that.
MoveDelta Attempted move that resulted in the hit.
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
References HandleImpact().
InitCollisionParams()
virtual void UMovementComponent::InitCollisionParams (FCollisionQueryParams & OutParams, FCollisionResponseParams & OutResponseParam) const virtual inherited
Initialize collision params appropriately based on our collision settings.
Use this before any Line, Overlap, or Sweep tests.
References InitCollisionParams().
InitializeComponent()
virtual void UMovementComponent::InitializeComponent () override virtual inherited
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
Reimplemented in UProjectileMovementComponent.
IsCrouching()
bool UNavMovementComponent::IsCrouching () const inline override virtual
Returns true if currently crouching.
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 189 of file NavMovementComponent.h.
References IsCrouching().
IsExceedingMaxSpeed()
virtual bool UMovementComponent::IsExceedingMaxSpeed (float MaxSpeed) const virtual inherited
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
Note that under normal circumstances updates cause by acceleration will not cause this to be true, however external forces or changes in the max speed limit can cause the max speed to be violated.
References IsExceedingMaxSpeed(), and StopMovementImmediately().
IsFalling()
bool UNavMovementComponent::IsFalling () const inline override virtual
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 194 of file NavMovementComponent.h.
IsFlying()
bool UNavMovementComponent::IsFlying () const inline override virtual
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 209 of file NavMovementComponent.h.
IsInWater()
virtual bool UMovementComponent::IsInWater () const virtual inherited
Returns true if it's in PhysicsVolume with water flag.
References IsInWater().
IsJumpAllowed()
bool UNavMovementComponent::IsJumpAllowed () const inline
Returns true if component is allowed to jump.
Definition at line 162 of file NavMovementComponent.h.
References INavMovementInterface::CanEverJump(), and MovementState.
IsMovingOnGround()
bool UNavMovementComponent::IsMovingOnGround () const inline override virtual
Returns true if currently moving on the ground (e.g.
walking or driving)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 199 of file NavMovementComponent.h.
IsSwimming()
bool UNavMovementComponent::IsSwimming () const inline override virtual
Returns true if currently swimming (moving through a fluid volume)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
Definition at line 204 of file NavMovementComponent.h.
K2_MoveUpdatedComponent()
bool UMovementComponent::K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult & OutHit, bool bSweep = true, bool bTeleport = false) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
References K2_MoveUpdatedComponent().
MoveUpdatedComponent() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled. \note This simply calls the virtual MoveUpdatedComponentImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
Definition at line 487 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 492 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponentImpl()
virtual bool UMovementComponent::MoveUpdatedComponentImpl (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) protected virtual inherited
References MoveUpdatedComponentImpl().
OnRegister()
virtual void UMovementComponent::OnRegister () override virtual inherited
Overridden to update component properties that should be updated while being edited.
Reimplemented in UCharacterMovementComponent.
OnTeleported()
virtual void UMovementComponent::OnTeleported () inline virtual inherited
Called by owning Actor upon successful teleport from AActor::TeleportTo().
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
Definition at line 459 of file MovementComponent.h.
References OnTeleported().
OverlapTest()
virtual bool UMovementComponent::OverlapTest (const FVector & Location, const FQuat & RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape & CollisionShape, const AActor * IgnoreActor) const virtual inherited
Return true if the given collision shape overlaps other geometry at the given location and rotation.
The collision params are set by InitCollisionParams().
References Location, MoveUpdatedComponent(), and OverlapTest().
PhysicsLockedAxisSettingChanged()
void UMovementComponent::PhysicsLockedAxisSettingChanged () static inherited
PhysicsVolumeChanged()
virtual void UMovementComponent::PhysicsVolumeChanged (class APhysicsVolume * NewVolume) virtual inherited
Delegate when PhysicsVolume of UpdatedComponent has been changed.
Reimplemented in UCharacterMovementComponent.
References PhysicsVolumeChanged().
PostEditChangeProperty()
virtual void UNavMovementComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from UMovementComponent.
Reimplemented in UCharacterMovementComponent.
PostLoad()
virtual void UMovementComponent::PostLoad () override virtual inherited
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
RegisterComponentTickFunctions()
virtual void UMovementComponent::RegisterComponentTickFunctions (bool bRegister) override virtual inherited
Reimplemented in UCharacterMovementComponent.
RequestDirectMove()
virtual void UNavMovementComponent::RequestDirectMove (const FVector & MoveVelocity, bool bForceMaxSpeed) override virtual
path following: request new velocity
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent.
RequestPathMove()
virtual void UNavMovementComponent::RequestPathMove (const FVector & MoveInput) override virtual
path following: request new move input (normal vector = full strength)
Implements INavMovementInterface.
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
ResetMoveState()
virtual void UNavMovementComponent::ResetMoveState () inline override virtual
Resets runtime movement state to character's movement capabilities.
Implements INavMovementInterface.
Definition at line 156 of file NavMovementComponent.h.
References MovementState, and NavAgentProps.
ResolvePenetration() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) inherited
Try to move out of penetration in an object after a failed move.
This function should respect the plane constraint if applicable. \note This simply calls the virtual ResolvePenetrationImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat)..
Parameters
Adjustment The requested adjustment, usually from GetPenetrationAdjustment()
Hit The result of the failed move
Returns
True if the adjustment was successful and the original move should be retried, or false if no repeated attempt should be made.
Definition at line 497 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetration() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FRotator & NewRotation) inherited
Definition at line 502 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetrationImpl()
virtual bool UMovementComponent::ResolvePenetrationImpl (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) protected virtual inherited
Reimplemented in UCharacterMovementComponent, and UFloatingPawnMovement.
References ResolvePenetrationImpl().
SafeMoveUpdatedComponent() [1/2]
bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
If this adjustment succeeds, the original movement will be attempted again. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
result of the final MoveUpdatedComponent() call.
References SafeMoveUpdatedComponent().
SafeMoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 482 of file MovementComponent.h.
References SafeMoveUpdatedComponent().
Serialize()
virtual void UNavMovementComponent::Serialize (FArchive & Ar) override virtual
Reimplemented from UMovementComponent.
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
SetFixedBrakingDistance()
UE_API void INavMovementInterface::SetFixedBrakingDistance (float DistanceToEndOfPath) inherited
Set fixed braking distance.
References SetFixedBrakingDistance(), and UE_API.
SetJumpAllowed()
void UNavMovementComponent::SetJumpAllowed (bool bAllowed) inline
Sets whether this component is allowed to jump.
Definition at line 165 of file NavMovementComponent.h.
References MovementState.
SetPathFollowingAgent()
virtual void UNavMovementComponent::SetPathFollowingAgent (IPathFollowingAgentInterface * InPathFollowingAgent) inline override virtual
Set the path following agent this interface uses.
Must implement IPathFollowingAgentInterface.
Implements INavMovementInterface.
Definition at line 146 of file NavMovementComponent.h.
SetPlaneConstraintAxisSetting()
virtual void UMovementComponent::SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting) virtual inherited
Set the plane constraint axis setting.
Changing this setting will modify the current value of PlaneConstraintNormal.
Parameters
NewAxisSetting New plane constraint axis setting.
References EPlaneConstraintAxisSetting, GetPlaneConstraintAxisSetting(), and SetPlaneConstraintAxisSetting().
SetPlaneConstraintEnabled()
virtual void UMovementComponent::SetPlaneConstraintEnabled (bool bEnabled) virtual inherited
Sets whether or not the plane constraint is enabled.
References SetPlaneConstraintEnabled().
SetPlaneConstraintFromVectors()
virtual void UMovementComponent::SetPlaneConstraintFromVectors (FVector Forward, FVector Up) virtual inherited
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintFromVectors().
SetPlaneConstraintNormal()
virtual void UMovementComponent::SetPlaneConstraintNormal (FVector PlaneNormal) virtual inherited
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
Changing the normal automatically sets PlaneConstraintAxisSetting to "Custom".
Parameters
PlaneNormal The normal of the plane. If non-zero in length, it will be normalized.
References SetPlaneConstraintNormal().
SetPlaneConstraintOrigin()
virtual void UMovementComponent::SetPlaneConstraintOrigin (FVector PlaneOrigin) virtual inherited
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintOrigin().
SetUpdatedComponent()
virtual void UMovementComponent::SetUpdatedComponent (USceneComponent * NewUpdatedComponent) virtual inherited
Assign the component we move and update.
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
References SetUpdatedComponent().
SetUpdateNavAgentWithOwnersCollisions()
void UNavMovementComponent::SetUpdateNavAgentWithOwnersCollisions (bool bUpdateWithOwner)
ShouldSkipUpdate()
virtual bool UMovementComponent::ShouldSkipUpdate (float DeltaTime) const virtual inherited
Possibly skip update if moved component is not rendered or can't move.
Parameters
DeltaTime
Todo
this parameter is not used in the function.
Returns
true if component movement update should be skipped
References ShouldSkipUpdate().
ShouldUpdateNavAgentWithOwnersCollision()
bool UNavMovementComponent::ShouldUpdateNavAgentWithOwnersCollision () const inline
Definition at line 99 of file NavMovementComponent.h.
References NavMovementProperties.
SlideAlongSurface()
virtual float UMovementComponent::SlideAlongSurface (const FVector & Delta, float Time, const FVector & Normal, FHitResult & Hit, bool bHandleImpact = false) virtual inherited
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
Calls HandleImpact for each surface hit, if requested. Uses SafeMoveUpdatedComponent() for movement, and ComputeSlideVector() to determine the slide direction.
Parameters
Delta Attempted movement vector.
Time Percent of Delta to apply (between 0 and 1). Usually equal to the remaining time after a collision: (1.0 - Hit.Time).
Normal Normal opposing movement, along which we will slide.
Hit [In] HitResult of the attempted move that resulted in the impact triggering the slide. [Out] HitResult of last attempted move.
bHandleImpact Whether to call HandleImpact on each hit.
Returns
The percentage of requested distance (Delta * Percent) actually applied (between 0 and 1). 0 if no movement occurred, non-zero if movement occurred.
Reimplemented in UCharacterMovementComponent.
References SlideAlongSurface().
SnapUpdatedComponentToPlane()
virtual void UMovementComponent::SnapUpdatedComponentToPlane () virtual inherited
Snap the updated component to the plane constraint, if enabled.
References SnapUpdatedComponentToPlane().
StopActiveMovement()
virtual UE_API void INavMovementInterface::StopActiveMovement () virtual inherited
Stops applying further movement (usually zeros acceleration).
Reimplemented in UCharacterMovementComponent.
References StopActiveMovement(), and UE_API.
StopMovementImmediately()
void UNavMovementComponent::StopMovementImmediately () inline override virtual
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
Reimplemented from UMovementComponent.
Definition at line 214 of file NavMovementComponent.h.
References INavMovementInterface::StopActiveMovement().
StopMovementKeepPathing()
virtual UE_API void INavMovementInterface::StopMovementKeepPathing () virtual inherited
Stops movement immediately (reset velocity) but keeps following current path.
References StopMovementKeepPathing(), and UE_API.
TickComponent()
virtual void UMovementComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual inherited
Reimplemented in UCharacterMovementComponent, and UProjectileMovementComponent.
TwoWallAdjust()
virtual void UMovementComponent::TwoWallAdjust (FVector & Delta, const FHitResult & Hit, const FVector & OldHitNormal) const virtual inherited
Compute a movement direction when contacting two surfaces.
Parameters
Delta [In] Amount of move attempted before impact. [Out] Computed adjustment based on impacts.
Hit Impact from last attempted move
OldHitNormal Normal of impact before last attempted move
Returns
Result in Delta that is the direction to move when contacting two surfaces.
Reimplemented in UCharacterMovementComponent.
References TwoWallAdjust().
UpdateComponentVelocity()
virtual void UMovementComponent::UpdateComponentVelocity () virtual inherited
Update ComponentVelocity of UpdatedComponent.
This needs to be called by derived classes at the end of an update whenever Velocity has changed.
References UpdateComponentVelocity().
UpdateNavAgent()
virtual void UNavMovementComponent::UpdateNavAgent (const UObject & ObjectToUpdateFrom) override virtual
Set nav agent properties from an object.
Implements INavMovementInterface.
UpdateTickRegistration()
virtual void UMovementComponent::UpdateTickRegistration () virtual inherited
Update tick registration state, determined by bAutoUpdateTickRegistration.
Called by SetUpdatedComponent.
Reimplemented in UProjectileMovementComponent.
References UpdateTickRegistration().
UseAccelerationForPathFollowing()
UE_API bool INavMovementInterface::UseAccelerationForPathFollowing () const inherited
Returns true if acceleration should be used for path following.
References UE_API, and UseAccelerationForPathFollowing().
Member Data Documentation
bAutoRegisterPhysicsVolumeUpdates
uint8 UMovementComponent::bAutoRegisterPhysicsVolumeUpdates inherited
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
If false, will not change bShouldUpdatePhysicsVolume on the UpdatedComponent at all.
See also
bComponentShouldUpdatePhysicsVolume
Definition at line 166 of file MovementComponent.h.
bAutoRegisterUpdatedComponent
uint8 UMovementComponent::bAutoRegisterUpdatedComponent inherited
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
Definition at line 148 of file MovementComponent.h.
bAutoUpdateTickRegistration
uint8 UMovementComponent::bAutoUpdateTickRegistration inherited
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
This will NOT enable tick at startup if bAutoActivate is false, because presumably you have a good reason for not wanting it to start ticking initially.
Definition at line 136 of file MovementComponent.h.
bComponentShouldUpdatePhysicsVolume
uint8 UMovementComponent::bComponentShouldUpdatePhysicsVolume inherited
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Only enabled if bAutoRegisterPhysicsVolumeUpdates is true. WARNING: UpdatePhysicsVolume is potentially expensive if overlap events are also disabled because it requires a separate query against all physics volumes in the world.
Definition at line 174 of file MovementComponent.h.
bConstrainToPlane
uint8 UMovementComponent::bConstrainToPlane inherited
If true, movement will be constrained to a plane.
See also
PlaneConstraintNormal, PlaneConstraintOrigin, PlaneConstraintAxisSetting
Definition at line 155 of file MovementComponent.h.
bSnapToPlaneAtStart
uint8 UMovementComponent::bSnapToPlaneAtStart inherited
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
Definition at line 159 of file MovementComponent.h.
bStopMovementAbortPaths_DEPRECATED
uint8 UNavMovementComponent::bStopMovementAbortPaths_DEPRECATED protected
If set, StopActiveMovement call will abort current path following request.
Definition at line 53 of file NavMovementComponent.h.
bTickBeforeOwner
uint8 UMovementComponent::bTickBeforeOwner inherited
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
This is important when our tick causes an update in the owner's position, so that when the owner ticks it uses the most recent position without lag. Disabling this can improve performance if both objects tick but the order of ticks doesn't matter.
Definition at line 144 of file MovementComponent.h.
bUpdateNavAgentWithOwnersCollision_DEPRECATED
uint8 UNavMovementComponent::bUpdateNavAgentWithOwnersCollision_DEPRECATED protected
If set to true NavAgentProps' radius and height will be updated with Owner's collision capsule size.
Definition at line 39 of file NavMovementComponent.h.
bUpdateOnlyIfRendered
uint8 UMovementComponent::bUpdateOnlyIfRendered inherited
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
Definition at line 129 of file MovementComponent.h.
bUseAccelerationForPaths_DEPRECATED
uint8 UNavMovementComponent::bUseAccelerationForPaths_DEPRECATED protected
If set, pathfollowing will control character movement via acceleration values.
If false, it will set velocities directly.
Definition at line 44 of file NavMovementComponent.h.
bUseFixedBrakingDistanceForPaths_DEPRECATED
uint8 UNavMovementComponent::bUseFixedBrakingDistanceForPaths_DEPRECATED protected
If set, FixedPathBrakingDistance will be used for path following deceleration.
Definition at line 49 of file NavMovementComponent.h.
FixedPathBrakingDistance_DEPRECATED
float UNavMovementComponent::FixedPathBrakingDistance_DEPRECATED protected
Braking distance override used with acceleration driven path following (bUseAccelerationForPaths)
Definition at line 34 of file NavMovementComponent.h.
MovementState
FMovementProperties UNavMovementComponent::MovementState
Expresses runtime state of character's movement.
Put all temporal changes to movement properties here
Definition at line 65 of file NavMovementComponent.h.
NavAgentProps
FNavAgentProperties UNavMovementComponent::NavAgentProps
Properties that define how the component can move.
Definition at line 61 of file NavMovementComponent.h.
NavMovementProperties
FNavMovementProperties UNavMovementComponent::NavMovementProperties protected
Definition at line 56 of file NavMovementComponent.h.
PlaneConstraintNormal
FVector UMovementComponent::PlaneConstraintNormal protected inherited
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
If for example you wanted to constrain movement to the X-Z plane (so that Y cannot change), the normal would be set to X=0 Y=1 Z=0. This is recalculated whenever PlaneConstraintAxisSetting changes. It is normalized once the component is registered with the game world.
See also
bConstrainToPlane, SetPlaneConstraintNormal(), SetPlaneConstraintFromVectors()
Definition at line 107 of file MovementComponent.h.
PlaneConstraintOrigin
FVector UMovementComponent::PlaneConstraintOrigin protected inherited
The origin of the plane that constrains movement, if plane constraint is enabled.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
See also
bConstrainToPlane, SetPlaneConstraintOrigin().
Definition at line 115 of file MovementComponent.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/NavMovementComponent.h