Unreal Engine 5.6 C++ API: FPrimitiveUniformShaderParametersBuilder Struct Reference
FPrimitiveUniformShaderParametersBuilder Struct Reference
#include "PrimitiveUniformShaderParametersBuilder.h"
Public Member Functions
FPrimitiveUniformShaderParametersBuilder & ActorWorldPosition (const FVector &InActorWorldPosition)
FPrimitiveUniformShaderParametersBuilder & AllowInstanceCullingOcclusionQueries (bool InAllowInstanceCullingOcclusionQueries)
const FPrimitiveUniformShaderParameters & Build ()
FPrimitiveUniformShaderParametersBuilder & CacheShadowAsStatic (bool InCacheShadowAsStatic)
FPrimitiveUniformShaderParametersBuilder & CastContactShadow (bool InCastContactShadow)
FPrimitiveUniformShaderParametersBuilder & CastHiddenShadow (bool InCastHiddenShadow)
FPrimitiveUniformShaderParametersBuilder & CastShadow (bool InCastShadow)
FPrimitiveUniformShaderParametersBuilder & CustomDepthStencil (uint8 StencilValue, EStencilMask StencilWriteMask)
FPrimitiveUniformShaderParametersBuilder & CustomPrimitiveData (const FCustomPrimitiveData *InCustomPrimitiveData)
FPrimitiveUniformShaderParametersBuilder & Defaults ()
FPrimitiveUniformShaderParametersBuilder & DisableMaterialInvalidations (bool InDisableMaterialInvalidations)
FPrimitiveUniformShaderParametersBuilder & EditorColors (const FLinearColor &InWireframeColor, const FLinearColor &InPrimitiveColor)
FPrimitiveUniformShaderParametersBuilder & EvaluateWorldPositionOffset (bool InEvaluateWorldPositionOffset)
FPrimitiveUniformShaderParametersBuilder & ForceHidden (bool InForceHidden)
FPrimitiveUniformShaderParametersBuilder & HasAlwaysEvaluateWPOMaterials (bool InHasAlwaysEvaluateWPOMaterials)
FPrimitiveUniformShaderParametersBuilder & HasCapsuleRepresentation (bool InHasCapsuleRepresentation)
FPrimitiveUniformShaderParametersBuilder & HasDistanceFieldRepresentation (bool InHasDistanceFieldRepresentation)
FPrimitiveUniformShaderParametersBuilder & HasInstanceLocalBounds (bool InHasInstanceLocalBounds)
FPrimitiveUniformShaderParametersBuilder & HasPerClusterDisplacementFallbackRaster (bool InHasPerClusterDisplacementFallbackRaster)
FPrimitiveUniformShaderParametersBuilder & HasPixelAnimation (bool InHasPixelAnimation)
FPrimitiveUniformShaderParametersBuilder & HiddenInSceneCapture (bool InHiddenInSceneCapture)
FPrimitiveUniformShaderParametersBuilder & Holdout (bool InHoldout)
FPrimitiveUniformShaderParametersBuilder & InstanceDrawDistance (FVector2f DistanceMinMax)
FPrimitiveUniformShaderParametersBuilder & InstanceLocalBounds (const FRenderBounds &InInstanceLocalBounds)
FPrimitiveUniformShaderParametersBuilder & InstancePayloadDataOffset (uint32 InInstancePayloadDataOffset)
FPrimitiveUniformShaderParametersBuilder & InstancePayloadDataStride (uint32 InInstancePayloadDataStride)
FPrimitiveUniformShaderParametersBuilder & InstancePayloadExtensionSize (uint32 InInstancePayloadExtensionSize)
FPrimitiveUniformShaderParametersBuilder & InstanceSceneDataOffset (uint32 InInstanceSceneDataOffset)
FPrimitiveUniformShaderParametersBuilder & InstanceWorldPositionOffsetDisableDistance (float WPODisableDistance)
FPrimitiveUniformShaderParametersBuilder & IsFirstPerson (bool InIsFirstPerson)
FPrimitiveUniformShaderParametersBuilder & LightingChannelMask (uint32 InLightingChannelMask)
FPrimitiveUniformShaderParametersBuilder & LightmapDataIndex (uint32 InLightmapDataIndex)
FPrimitiveUniformShaderParametersBuilder & LightmapUVIndex (uint32 InLightmapUVIndex)
FPrimitiveUniformShaderParametersBuilder & LocalBounds (const FBoxSphereBounds &InLocalBounds)
FPrimitiveUniformShaderParametersBuilder & LocalToWorld (const FMatrix &InLocalToWorld)
FPrimitiveUniformShaderParametersBuilder & MaterialCacheTextureDescriptor (FUintVector2 InMaterialCacheTextureDescriptor)
FPrimitiveUniformShaderParametersBuilder & MaterialDisplacementFadeOutSize (float InMaterialDisplacementFadeOutSize)
FPrimitiveUniformShaderParametersBuilder & MaxWorldPositionOffsetExtent (float InMaxExtent)
FPrimitiveUniformShaderParametersBuilder & MeshPaintTextureDescriptor (FUintVector2 InMeshPaintTextureDescriptor)
FPrimitiveUniformShaderParametersBuilder & MinMaxMaterialDisplacement (const FVector2f &InMinMaxDisplacement)
FPrimitiveUniformShaderParametersBuilder & NaniteAssemblyTransformOffset (uint32 InNaniteAssemblyTransformOffset)
FPrimitiveUniformShaderParametersBuilder & NaniteFilterFlags (uint32 FilterFlags)
FPrimitiveUniformShaderParametersBuilder & NaniteHierarchyOffset (uint32 InNaniteHierarchyOffset)
FPrimitiveUniformShaderParametersBuilder & NaniteImposterIndex (uint32 ImposterIndex)
FPrimitiveUniformShaderParametersBuilder & NaniteRayTracingDataOffset (uint32 InNaniteRayTracingDataOffset)
FPrimitiveUniformShaderParametersBuilder & NaniteResourceID (uint32 InNaniteResourceID)
FPrimitiveUniformShaderParametersBuilder & NumInstanceSceneDataEntries (uint32 InNumInstanceSceneDataEntries)
FPrimitiveUniformShaderParametersBuilder & ObjectBounds (const FVector3f &InObjectBounds)
FPrimitiveUniformShaderParametersBuilder & OutputVelocity (bool InOutputVelocity)
FPrimitiveUniformShaderParametersBuilder & PersistentPrimitiveIndex (int32 InPersistentPrimitiveIndex)
FPrimitiveUniformShaderParametersBuilder & PixelProgrammableDistance (float PixelProgrammableDistance)
FPrimitiveUniformShaderParametersBuilder & PreSkinnedLocalBounds (const FBoxSphereBounds &InPreSkinnedLocalBounds)
FPrimitiveUniformShaderParametersBuilder & PreviousLocalToWorld (const FMatrix &InPreviousLocalToWorld)
FPrimitiveUniformShaderParametersBuilder & PrimitiveComponentId (uint32 InPrimitiveComponentId)
FPrimitiveUniformShaderParametersBuilder & RayTracingFarField (bool InRayTracingFarField)
FPrimitiveUniformShaderParametersBuilder & RayTracingHasGroupId (bool InRayTracingHasGroupId)
FPrimitiveUniformShaderParametersBuilder & ReceivesDecals (bool InReceivesDecals)
FPrimitiveUniformShaderParametersBuilder & ReverseCulling (bool InReverseCulling)
FPrimitiveUniformShaderParametersBuilder & SingleCaptureIndex (int32 InSingleCaptureIndex)
FPrimitiveUniformShaderParametersBuilder & SkinnedMesh (bool InSkinnedMesh)
FPrimitiveUniformShaderParametersBuilder & SplineMesh (bool InSplineMesh)
FPrimitiveUniformShaderParametersBuilder & UseSingleSampleShadowFromStationaryLights (bool InUseSingleSampleShadowFromStationaryLights)
FPrimitiveUniformShaderParametersBuilder & UseVolumetricLightmap (bool InUseVolumetricLightmap)
FPrimitiveUniformShaderParametersBuilder & VisibleInEditor (bool InVisibleInEditor)
FPrimitiveUniformShaderParametersBuilder & VisibleInGame (bool InVisibleInGame)
FPrimitiveUniformShaderParametersBuilder & VisibleInLumenScene (bool InVisibleInLumenScene)
FPrimitiveUniformShaderParametersBuilder & VisibleInRayTracing (bool InVisibleInRayTracing)
FPrimitiveUniformShaderParametersBuilder & VisibleInRealTimeSkyCaptures (bool InVisibleInRealTimeSkyCaptures)
FPrimitiveUniformShaderParametersBuilder & VisibleInReflectionCaptures (bool InVisibleInReflectionCaptures)
FPrimitiveUniformShaderParametersBuilder & VisibleInSceneCaptureOnly (bool InVisibleInSceneCaptureOnly)
FPrimitiveUniformShaderParametersBuilder & WorldBounds (const FBoxSphereBounds &InWorldBounds)
Private Attributes
FVector AbsoluteActorWorldPosition
FMatrix AbsoluteLocalToWorld
FVector AbsoluteObjectWorldPosition
FMatrix AbsolutePreviousLocalToWorld
uint32 bAllowInstanceCullingOcclusionQueries: 1
uint32 bCacheShadowAsStatic: 1
uint32 bCastContactShadow: 1
uint32 bCastHiddenShadow: 1
uint32 bCastShadow: 1
uint32 bDisableMaterialInvalidations: 1
uint32 bEvaluateWorldPositionOffset: 1
uint32 bForceHidden: 1
uint32 bHasAlwaysEvaluateWPOMaterials: 1
uint32 bHasCapsuleRepresentation: 1
uint32 bHasCustomData: 1
uint32 bHasDistanceFieldRepresentation: 1
uint32 bHasInstanceDrawDistanceCull: 1
uint32 bHasInstanceLocalBounds: 1
uint32 bHasNaniteImposter: 1
uint32 bHasPerClusterDisplacementFallbackRaster: 1
uint32 bHasPixelAnimation: 1
uint32 bHasPreSkinnedLocalBounds: 1
uint32 bHasPreviousLocalToWorld: 1
uint32 bHasWPODisableDistance: 1
uint32 bHiddenInSceneCapture: 1
uint32 bHoldout: 1
uint32 bIsFirstPerson: 1
uint32 bOutputVelocity: 1
uint32 bRayTracingFarField: 1
uint32 bRayTracingHasGroupId: 1
uint32 bReceivesDecals: 1
uint32 bReverseCulling: 1
uint32 bSkinnedMesh: 1
uint32 bSplineMesh: 1
uint32 bUseSingleSampleShadowFromStationaryLights: 1
uint32 bUseVolumetricLightmap: 1
uint32 bVisibleInEditor: 1
uint32 bVisibleInGame: 1
uint32 bVisibleInLumenScene: 1
uint32 bVisibleInRayTracing: 1
uint32 bVisibleInRealTimeSkyCaptures: 1
uint32 bVisibleInReflectionCaptures: 1
uint32 bVisibleInSceneCaptureOnly: 1
uint32 bWritesCustomDepthStencil: 1
uint32 LightingChannels: 3
float ObjectRadius
FPrimitiveUniformShaderParameters Parameters
Detailed Description
Definition at line 20 of file PrimitiveUniformShaderParametersBuilder.h.
Member Function Documentation
ActorWorldPosition()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::ActorWorldPosition (const FVector & InActorWorldPosition) inline
Definition at line 219 of file PrimitiveUniformShaderParametersBuilder.h.
References AbsoluteActorWorldPosition, and FVector.
AllowInstanceCullingOcclusionQueries()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::AllowInstanceCullingOcclusionQueries (bool InAllowInstanceCullingOcclusionQueries) inline
Definition at line 138 of file PrimitiveUniformShaderParametersBuilder.h.
References AllowInstanceCullingOcclusionQueries().
Referenced by AllowInstanceCullingOcclusionQueries().
Build()
const FPrimitiveUniformShaderParameters & FPrimitiveUniformShaderParametersBuilder::Build () inline
Definition at line 325 of file PrimitiveUniformShaderParametersBuilder.h.
References AbsoluteActorWorldPosition, AbsoluteLocalToWorld, AbsoluteObjectWorldPosition, AbsolutePreviousLocalToWorld, bAllowInstanceCullingOcclusionQueries, bCacheShadowAsStatic, bCastContactShadow, bCastHiddenShadow, bCastShadow, bDisableMaterialInvalidations, bEvaluateWorldPositionOffset, bForceHidden, bHasAlwaysEvaluateWPOMaterials, bHasCapsuleRepresentation, bHasCustomData, bHasDistanceFieldRepresentation, bHasInstanceDrawDistanceCull, bHasInstanceLocalBounds, bHasNaniteImposter, bHasPerClusterDisplacementFallbackRaster, bHasPixelAnimation, bHasPreSkinnedLocalBounds, bHasPreviousLocalToWorld, bHasWPODisableDistance, bHiddenInSceneCapture, bHoldout, bIsFirstPerson, bOutputVelocity, bRayTracingFarField, bRayTracingHasGroupId, bReceivesDecals, bReverseCulling, bSkinnedMesh, bSplineMesh, bUseSingleSampleShadowFromStationaryLights, bUseVolumetricLightmap, bVisibleInEditor, bVisibleInGame, bVisibleInLumenScene, bVisibleInRayTracing, bVisibleInRealTimeSkyCaptures, bVisibleInReflectionCaptures, bVisibleInSceneCaptureOnly, bWritesCustomDepthStencil, IConsoleManager::FindTConsoleVariableDataInt(), FVector, IConsoleManager::Get(), TLargeWorldRenderPosition< TScalar >::GetOffset(), TLargeWorldRenderPosition< TScalar >::GetTile(), TConsoleVariableData< T >::GetValueOnAnyThread(), FDFVector3::High, InstanceLocalBounds(), UE::Math::TMatrix< T >::Inverse(), LightingChannels, FDFVector3::Low, FDFMatrix::MakeClampedToRelativeWorldMatrixDouble(), FDFMatrix::MakeToRelativeWorldMatrixDouble(), FMath::Max, FMath::Max3(), ObjectRadius, Parameters, ScaleX, ScaleY, ScaleZ, UE::Math::TVector< T >::Size(), TEXT, UE_KINDA_SMALL_NUMBER, and EAxis::Z.
CacheShadowAsStatic()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CacheShadowAsStatic (bool InCacheShadowAsStatic) inline
Definition at line 121 of file PrimitiveUniformShaderParametersBuilder.h.
References CacheShadowAsStatic().
Referenced by CacheShadowAsStatic().
CastContactShadow()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CastContactShadow (bool InCastContactShadow) inline
Definition at line 116 of file PrimitiveUniformShaderParametersBuilder.h.
References CastContactShadow().
Referenced by CastContactShadow().
CastHiddenShadow()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CastHiddenShadow (bool InCastHiddenShadow) inline
Definition at line 117 of file PrimitiveUniformShaderParametersBuilder.h.
References CastHiddenShadow().
Referenced by CastHiddenShadow().
CastShadow()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CastShadow (bool InCastShadow) inline
Definition at line 118 of file PrimitiveUniformShaderParametersBuilder.h.
References CastShadow().
Referenced by CastShadow().
CustomDepthStencil()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CustomDepthStencil (uint8 StencilValue, EStencilMask StencilWriteMask) inline
Definition at line 297 of file PrimitiveUniformShaderParametersBuilder.h.
References bWritesCustomDepthStencil, and Parameters.
CustomPrimitiveData()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::CustomPrimitiveData (const FCustomPrimitiveData * InCustomPrimitiveData) inline
Definition at line 254 of file PrimitiveUniformShaderParametersBuilder.h.
References bHasCustomData, FMemory::Memcpy(), FMemory::Memzero(), FMath::Min, and Parameters.
Defaults()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::Defaults () inline
Definition at line 23 of file PrimitiveUniformShaderParametersBuilder.h.
References bAllowInstanceCullingOcclusionQueries, bCacheShadowAsStatic, bCastContactShadow, bCastHiddenShadow, bCastShadow, bDisableMaterialInvalidations, bEvaluateWorldPositionOffset, bForceHidden, bHasAlwaysEvaluateWPOMaterials, bHasCapsuleRepresentation, bHasDistanceFieldRepresentation, bHasInstanceDrawDistanceCull, bHasInstanceLocalBounds, bHasNaniteImposter, bHasPerClusterDisplacementFallbackRaster, bHasPixelAnimation, bHasPreSkinnedLocalBounds, bHasPreviousLocalToWorld, bHasWPODisableDistance, bHiddenInSceneCapture, bHoldout, bIsFirstPerson, bOutputVelocity, bRayTracingFarField, bRayTracingHasGroupId, bReceivesDecals, bReverseCulling, bSkinnedMesh, bSplineMesh, bUseSingleSampleShadowFromStationaryLights, bUseVolumetricLightmap, bVisibleInEditor, bVisibleInGame, bVisibleInLumenScene, bVisibleInRayTracing, bVisibleInRealTimeSkyCaptures, bVisibleInReflectionCaptures, bVisibleInSceneCaptureOnly, bWritesCustomDepthStencil, CustomPrimitiveData, GetDefaultLightingChannelMask(), INDEX_NONE, LightingChannels, ObjectRadius, and Parameters.
DisableMaterialInvalidations()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::DisableMaterialInvalidations (bool InDisableMaterialInvalidations) inline
Definition at line 135 of file PrimitiveUniformShaderParametersBuilder.h.
References DisableMaterialInvalidations().
Referenced by DisableMaterialInvalidations().
EditorColors()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::EditorColors (const FLinearColor & InWireframeColor, const FLinearColor & InPrimitiveColor) inline
Definition at line 246 of file PrimitiveUniformShaderParametersBuilder.h.
References Parameters, FLinearColor::QuantizeRound(), and FColor::ToPackedRGBA().
EvaluateWorldPositionOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::EvaluateWorldPositionOffset (bool InEvaluateWorldPositionOffset) inline
Definition at line 123 of file PrimitiveUniformShaderParametersBuilder.h.
References EvaluateWorldPositionOffset().
Referenced by EvaluateWorldPositionOffset().
ForceHidden()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::ForceHidden (bool InForceHidden) inline
Definition at line 133 of file PrimitiveUniformShaderParametersBuilder.h.
References ForceHidden().
Referenced by ForceHidden().
HasAlwaysEvaluateWPOMaterials()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasAlwaysEvaluateWPOMaterials (bool InHasAlwaysEvaluateWPOMaterials) inline
Definition at line 139 of file PrimitiveUniformShaderParametersBuilder.h.
References HasAlwaysEvaluateWPOMaterials().
Referenced by HasAlwaysEvaluateWPOMaterials().
HasCapsuleRepresentation()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasCapsuleRepresentation (bool InHasCapsuleRepresentation) inline
Definition at line 114 of file PrimitiveUniformShaderParametersBuilder.h.
References HasCapsuleRepresentation().
Referenced by HasCapsuleRepresentation().
HasDistanceFieldRepresentation()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasDistanceFieldRepresentation (bool InHasDistanceFieldRepresentation) inline
Definition at line 113 of file PrimitiveUniformShaderParametersBuilder.h.
References HasDistanceFieldRepresentation().
Referenced by HasDistanceFieldRepresentation().
HasInstanceLocalBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasInstanceLocalBounds (bool InHasInstanceLocalBounds) inline
Definition at line 115 of file PrimitiveUniformShaderParametersBuilder.h.
References HasInstanceLocalBounds().
Referenced by HasInstanceLocalBounds().
HasPerClusterDisplacementFallbackRaster()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasPerClusterDisplacementFallbackRaster (bool InHasPerClusterDisplacementFallbackRaster) inline
Definition at line 143 of file PrimitiveUniformShaderParametersBuilder.h.
References HasPerClusterDisplacementFallbackRaster().
Referenced by HasPerClusterDisplacementFallbackRaster().
HasPixelAnimation()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HasPixelAnimation (bool InHasPixelAnimation) inline
Definition at line 140 of file PrimitiveUniformShaderParametersBuilder.h.
References HasPixelAnimation().
Referenced by HasPixelAnimation().
HiddenInSceneCapture()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::HiddenInSceneCapture (bool InHiddenInSceneCapture) inline
Definition at line 132 of file PrimitiveUniformShaderParametersBuilder.h.
References HiddenInSceneCapture().
Referenced by HiddenInSceneCapture().
Holdout()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::Holdout (bool InHoldout) inline
Definition at line 134 of file PrimitiveUniformShaderParametersBuilder.h.
References Holdout().
Referenced by Holdout().
InstanceDrawDistance()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstanceDrawDistance (FVector2f DistanceMinMax)
InstanceLocalBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstanceLocalBounds (const FRenderBounds & InInstanceLocalBounds) inline
Definition at line 231 of file PrimitiveUniformShaderParametersBuilder.h.
References bHasInstanceLocalBounds, FRenderBounds::GetCenter(), FRenderBounds::GetExtent(), and Parameters.
Referenced by Build().
InstancePayloadDataOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstancePayloadDataOffset (uint32 InInstancePayloadDataOffset) inline
Definition at line 148 of file PrimitiveUniformShaderParametersBuilder.h.
References InstancePayloadDataOffset().
Referenced by InstancePayloadDataOffset().
InstancePayloadDataStride()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstancePayloadDataStride (uint32 InInstancePayloadDataStride) inline
Definition at line 149 of file PrimitiveUniformShaderParametersBuilder.h.
References InstancePayloadDataStride().
Referenced by InstancePayloadDataStride().
InstancePayloadExtensionSize()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstancePayloadExtensionSize (uint32 InInstancePayloadExtensionSize) inline
Definition at line 150 of file PrimitiveUniformShaderParametersBuilder.h.
References InstancePayloadExtensionSize().
Referenced by InstancePayloadExtensionSize().
InstanceSceneDataOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstanceSceneDataOffset (uint32 InInstanceSceneDataOffset) inline
Definition at line 146 of file PrimitiveUniformShaderParametersBuilder.h.
References InstanceSceneDataOffset().
Referenced by InstanceSceneDataOffset().
InstanceWorldPositionOffsetDisableDistance()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::InstanceWorldPositionOffsetDisableDistance (float WPODisableDistance)
IsFirstPerson()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::IsFirstPerson (bool InIsFirstPerson) inline
Definition at line 144 of file PrimitiveUniformShaderParametersBuilder.h.
References IsFirstPerson().
Referenced by IsFirstPerson().
LightingChannelMask()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::LightingChannelMask (uint32 InLightingChannelMask) inline
Definition at line 167 of file PrimitiveUniformShaderParametersBuilder.h.
References LightingChannels.
LightmapDataIndex()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::LightmapDataIndex (uint32 InLightmapDataIndex) inline
Definition at line 159 of file PrimitiveUniformShaderParametersBuilder.h.
References LightmapDataIndex().
Referenced by LightmapDataIndex().
LightmapUVIndex()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::LightmapUVIndex (uint32 InLightmapUVIndex) inline
Definition at line 158 of file PrimitiveUniformShaderParametersBuilder.h.
References LightmapUVIndex().
Referenced by LightmapUVIndex().
LocalBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::LocalBounds (const FBoxSphereBounds & InLocalBounds) inline
Definition at line 204 of file PrimitiveUniformShaderParametersBuilder.h.
References UE::Math::TBoxSphereBounds< T, TExtent >::GetBoxExtrema(), and Parameters.
LocalToWorld()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::LocalToWorld (const FMatrix & InLocalToWorld) inline
Definition at line 225 of file PrimitiveUniformShaderParametersBuilder.h.
References AbsoluteLocalToWorld.
MaterialCacheTextureDescriptor()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::MaterialCacheTextureDescriptor (FUintVector2 InMaterialCacheTextureDescriptor) inline
Definition at line 162 of file PrimitiveUniformShaderParametersBuilder.h.
References MaterialCacheTextureDescriptor().
Referenced by MaterialCacheTextureDescriptor().
MaterialDisplacementFadeOutSize()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::MaterialDisplacementFadeOutSize (float InMaterialDisplacementFadeOutSize) inline
Definition at line 160 of file PrimitiveUniformShaderParametersBuilder.h.
References MaterialDisplacementFadeOutSize().
Referenced by MaterialDisplacementFadeOutSize().
MaxWorldPositionOffsetExtent()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::MaxWorldPositionOffsetExtent (float InMaxExtent) inline
Definition at line 173 of file PrimitiveUniformShaderParametersBuilder.h.
References Parameters.
MeshPaintTextureDescriptor()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::MeshPaintTextureDescriptor (FUintVector2 InMeshPaintTextureDescriptor) inline
Definition at line 161 of file PrimitiveUniformShaderParametersBuilder.h.
References MeshPaintTextureDescriptor().
Referenced by MeshPaintTextureDescriptor().
MinMaxMaterialDisplacement()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::MinMaxMaterialDisplacement (const FVector2f & InMinMaxDisplacement) inline
Definition at line 179 of file PrimitiveUniformShaderParametersBuilder.h.
References Parameters, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
NaniteAssemblyTransformOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteAssemblyTransformOffset (uint32 InNaniteAssemblyTransformOffset) inline
Definition at line 156 of file PrimitiveUniformShaderParametersBuilder.h.
References NaniteAssemblyTransformOffset().
Referenced by NaniteAssemblyTransformOffset().
NaniteFilterFlags()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteFilterFlags (uint32 FilterFlags) inline
Definition at line 289 of file PrimitiveUniformShaderParametersBuilder.h.
References check, and Parameters.
NaniteHierarchyOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteHierarchyOffset (uint32 InNaniteHierarchyOffset) inline
Definition at line 155 of file PrimitiveUniformShaderParametersBuilder.h.
References NaniteHierarchyOffset().
Referenced by NaniteHierarchyOffset().
NaniteImposterIndex()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteImposterIndex (uint32 ImposterIndex) inline
Definition at line 279 of file PrimitiveUniformShaderParametersBuilder.h.
References bHasNaniteImposter, check, INDEX_NONE, and Parameters.
NaniteRayTracingDataOffset()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteRayTracingDataOffset (uint32 InNaniteRayTracingDataOffset) inline
Definition at line 157 of file PrimitiveUniformShaderParametersBuilder.h.
References NaniteRayTracingDataOffset().
Referenced by NaniteRayTracingDataOffset().
NaniteResourceID()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NaniteResourceID (uint32 InNaniteResourceID) inline
Definition at line 154 of file PrimitiveUniformShaderParametersBuilder.h.
References NaniteResourceID().
Referenced by NaniteResourceID().
NumInstanceSceneDataEntries()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::NumInstanceSceneDataEntries (uint32 InNumInstanceSceneDataEntries) inline
Definition at line 147 of file PrimitiveUniformShaderParametersBuilder.h.
References NumInstanceSceneDataEntries().
Referenced by NumInstanceSceneDataEntries().
ObjectBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::ObjectBounds (const FVector3f & InObjectBounds) inline
Definition at line 186 of file PrimitiveUniformShaderParametersBuilder.h.
References Parameters, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
OutputVelocity()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::OutputVelocity (bool InOutputVelocity) inline
Definition at line 122 of file PrimitiveUniformShaderParametersBuilder.h.
References OutputVelocity().
Referenced by OutputVelocity().
PersistentPrimitiveIndex()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::PersistentPrimitiveIndex (int32 InPersistentPrimitiveIndex) inline
Definition at line 152 of file PrimitiveUniformShaderParametersBuilder.h.
References PersistentPrimitiveIndex().
Referenced by PersistentPrimitiveIndex().
PixelProgrammableDistance()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::PixelProgrammableDistance (float PixelProgrammableDistance)
References PixelProgrammableDistance().
Referenced by PixelProgrammableDistance().
PreSkinnedLocalBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::PreSkinnedLocalBounds (const FBoxSphereBounds & InPreSkinnedLocalBounds) inline
Definition at line 211 of file PrimitiveUniformShaderParametersBuilder.h.
References bHasPreSkinnedLocalBounds, UE::Math::TBoxSphereBounds< T, TExtent >::GetBoxExtrema(), and Parameters.
PreviousLocalToWorld()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::PreviousLocalToWorld (const FMatrix & InPreviousLocalToWorld) inline
Definition at line 239 of file PrimitiveUniformShaderParametersBuilder.h.
References AbsolutePreviousLocalToWorld, and bHasPreviousLocalToWorld.
PrimitiveComponentId()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::PrimitiveComponentId (uint32 InPrimitiveComponentId) inline
Definition at line 153 of file PrimitiveUniformShaderParametersBuilder.h.
References PrimitiveComponentId().
Referenced by PrimitiveComponentId().
RayTracingFarField()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::RayTracingFarField (bool InRayTracingFarField) inline
Definition at line 141 of file PrimitiveUniformShaderParametersBuilder.h.
References RayTracingFarField().
Referenced by RayTracingFarField().
RayTracingHasGroupId()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::RayTracingHasGroupId (bool InRayTracingHasGroupId) inline
Definition at line 142 of file PrimitiveUniformShaderParametersBuilder.h.
References RayTracingHasGroupId().
Referenced by RayTracingHasGroupId().
ReceivesDecals()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::ReceivesDecals (bool InReceivesDecals) inline
Definition at line 112 of file PrimitiveUniformShaderParametersBuilder.h.
References ReceivesDecals().
Referenced by ReceivesDecals().
ReverseCulling()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::ReverseCulling (bool InReverseCulling) inline
Definition at line 126 of file PrimitiveUniformShaderParametersBuilder.h.
References ReverseCulling().
Referenced by ReverseCulling().
SingleCaptureIndex()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::SingleCaptureIndex (int32 InSingleCaptureIndex) inline
Definition at line 151 of file PrimitiveUniformShaderParametersBuilder.h.
References SingleCaptureIndex().
Referenced by SingleCaptureIndex().
SkinnedMesh()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::SkinnedMesh (bool InSkinnedMesh) inline
Definition at line 137 of file PrimitiveUniformShaderParametersBuilder.h.
References SkinnedMesh().
Referenced by SkinnedMesh().
SplineMesh()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::SplineMesh (bool InSplineMesh) inline
Definition at line 136 of file PrimitiveUniformShaderParametersBuilder.h.
References SplineMesh().
Referenced by SplineMesh().
UseSingleSampleShadowFromStationaryLights()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::UseSingleSampleShadowFromStationaryLights (bool InUseSingleSampleShadowFromStationaryLights) inline
Definition at line 119 of file PrimitiveUniformShaderParametersBuilder.h.
References UseSingleSampleShadowFromStationaryLights().
Referenced by UseSingleSampleShadowFromStationaryLights().
UseVolumetricLightmap()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::UseVolumetricLightmap (bool InUseVolumetricLightmap) inline
Definition at line 120 of file PrimitiveUniformShaderParametersBuilder.h.
References UseVolumetricLightmap().
Referenced by UseVolumetricLightmap().
VisibleInEditor()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInEditor (bool InVisibleInEditor) inline
Definition at line 125 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInEditor().
Referenced by VisibleInEditor().
VisibleInGame()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInGame (bool InVisibleInGame) inline
Definition at line 124 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInGame().
Referenced by VisibleInGame().
VisibleInLumenScene()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInLumenScene (bool InVisibleInLumenScene) inline
Definition at line 130 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInLumenScene().
Referenced by VisibleInLumenScene().
VisibleInRayTracing()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInRayTracing (bool InVisibleInRayTracing) inline
Definition at line 129 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInRayTracing().
Referenced by VisibleInRayTracing().
VisibleInRealTimeSkyCaptures()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInRealTimeSkyCaptures (bool InVisibleInRealTimeSkyCaptures) inline
Definition at line 128 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInRealTimeSkyCaptures().
Referenced by VisibleInRealTimeSkyCaptures().
VisibleInReflectionCaptures()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInReflectionCaptures (bool InVisibleInReflectionCaptures) inline
Definition at line 127 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInReflectionCaptures().
Referenced by VisibleInReflectionCaptures().
VisibleInSceneCaptureOnly()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::VisibleInSceneCaptureOnly (bool InVisibleInSceneCaptureOnly) inline
Definition at line 131 of file PrimitiveUniformShaderParametersBuilder.h.
References VisibleInSceneCaptureOnly().
Referenced by VisibleInSceneCaptureOnly().
WorldBounds()
FPrimitiveUniformShaderParametersBuilder & FPrimitiveUniformShaderParametersBuilder::WorldBounds (const FBoxSphereBounds & InWorldBounds) inline
Definition at line 194 of file PrimitiveUniformShaderParametersBuilder.h.
References AbsoluteObjectWorldPosition, UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, ObjectRadius, UE::Math::TBoxSphereBounds< T, TExtent >::Origin, Parameters, UE::Math::TBoxSphereBounds< T, TExtent >::SphereRadius, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Field Documentation
AbsoluteActorWorldPosition
FVector FPrimitiveUniformShaderParametersBuilder::AbsoluteActorWorldPosition private
Definition at line 471 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by ActorWorldPosition(), and Build().
AbsoluteLocalToWorld
FMatrix FPrimitiveUniformShaderParametersBuilder::AbsoluteLocalToWorld private
Definition at line 468 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and LocalToWorld().
AbsoluteObjectWorldPosition
FVector FPrimitiveUniformShaderParametersBuilder::AbsoluteObjectWorldPosition private
Definition at line 470 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and WorldBounds().
AbsolutePreviousLocalToWorld
FMatrix FPrimitiveUniformShaderParametersBuilder::AbsolutePreviousLocalToWorld private
Definition at line 469 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and PreviousLocalToWorld().
bAllowInstanceCullingOcclusionQueries
uint32 FPrimitiveUniformShaderParametersBuilder::bAllowInstanceCullingOcclusionQueries private
Definition at line 510 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bCacheShadowAsStatic
uint32 FPrimitiveUniformShaderParametersBuilder::bCacheShadowAsStatic private
Definition at line 479 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bCastContactShadow
uint32 FPrimitiveUniformShaderParametersBuilder::bCastContactShadow private
Definition at line 483 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bCastHiddenShadow
uint32 FPrimitiveUniformShaderParametersBuilder::bCastHiddenShadow private
Definition at line 484 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bCastShadow
uint32 FPrimitiveUniformShaderParametersBuilder::bCastShadow private
Definition at line 482 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bDisableMaterialInvalidations
uint32 FPrimitiveUniformShaderParametersBuilder::bDisableMaterialInvalidations private
Definition at line 507 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bEvaluateWorldPositionOffset
uint32 FPrimitiveUniformShaderParametersBuilder::bEvaluateWorldPositionOffset private
Definition at line 481 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bForceHidden
uint32 FPrimitiveUniformShaderParametersBuilder::bForceHidden private
Definition at line 499 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasAlwaysEvaluateWPOMaterials
uint32 FPrimitiveUniformShaderParametersBuilder::bHasAlwaysEvaluateWPOMaterials private
Definition at line 503 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasCapsuleRepresentation
uint32 FPrimitiveUniformShaderParametersBuilder::bHasCapsuleRepresentation private
Definition at line 486 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasCustomData
uint32 FPrimitiveUniformShaderParametersBuilder::bHasCustomData private
Definition at line 489 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and CustomPrimitiveData().
bHasDistanceFieldRepresentation
uint32 FPrimitiveUniformShaderParametersBuilder::bHasDistanceFieldRepresentation private
Definition at line 485 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasInstanceDrawDistanceCull
uint32 FPrimitiveUniformShaderParametersBuilder::bHasInstanceDrawDistanceCull private
Definition at line 501 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasInstanceLocalBounds
uint32 FPrimitiveUniformShaderParametersBuilder::bHasInstanceLocalBounds private
Definition at line 488 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and InstanceLocalBounds().
bHasNaniteImposter
uint32 FPrimitiveUniformShaderParametersBuilder::bHasNaniteImposter private
Definition at line 500 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and NaniteImposterIndex().
bHasPerClusterDisplacementFallbackRaster
uint32 FPrimitiveUniformShaderParametersBuilder::bHasPerClusterDisplacementFallbackRaster private
Definition at line 514 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasPixelAnimation
uint32 FPrimitiveUniformShaderParametersBuilder::bHasPixelAnimation private
Definition at line 511 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHasPreSkinnedLocalBounds
uint32 FPrimitiveUniformShaderParametersBuilder::bHasPreSkinnedLocalBounds private
Definition at line 487 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and PreSkinnedLocalBounds().
bHasPreviousLocalToWorld
uint32 FPrimitiveUniformShaderParametersBuilder::bHasPreviousLocalToWorld private
Definition at line 490 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and PreviousLocalToWorld().
bHasWPODisableDistance
uint32 FPrimitiveUniformShaderParametersBuilder::bHasWPODisableDistance private
Definition at line 502 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHiddenInSceneCapture
uint32 FPrimitiveUniformShaderParametersBuilder::bHiddenInSceneCapture private
Definition at line 498 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bHoldout
uint32 FPrimitiveUniformShaderParametersBuilder::bHoldout private
Definition at line 506 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bIsFirstPerson
uint32 FPrimitiveUniformShaderParametersBuilder::bIsFirstPerson private
Definition at line 515 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bOutputVelocity
uint32 FPrimitiveUniformShaderParametersBuilder::bOutputVelocity private
Definition at line 480 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bRayTracingFarField
uint32 FPrimitiveUniformShaderParametersBuilder::bRayTracingFarField private
Definition at line 512 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bRayTracingHasGroupId
uint32 FPrimitiveUniformShaderParametersBuilder::bRayTracingHasGroupId private
Definition at line 513 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bReceivesDecals
uint32 FPrimitiveUniformShaderParametersBuilder::bReceivesDecals private
Definition at line 476 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bReverseCulling
uint32 FPrimitiveUniformShaderParametersBuilder::bReverseCulling private
Definition at line 505 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bSkinnedMesh
uint32 FPrimitiveUniformShaderParametersBuilder::bSkinnedMesh private
Definition at line 509 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bSplineMesh
uint32 FPrimitiveUniformShaderParametersBuilder::bSplineMesh private
Definition at line 508 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bUseSingleSampleShadowFromStationaryLights
uint32 FPrimitiveUniformShaderParametersBuilder::bUseSingleSampleShadowFromStationaryLights private
Definition at line 477 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bUseVolumetricLightmap
uint32 FPrimitiveUniformShaderParametersBuilder::bUseVolumetricLightmap private
Definition at line 478 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInEditor
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInEditor private
Definition at line 492 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInGame
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInGame private
Definition at line 491 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInLumenScene
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInLumenScene private
Definition at line 496 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInRayTracing
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInRayTracing private
Definition at line 495 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInRealTimeSkyCaptures
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInRealTimeSkyCaptures private
Definition at line 494 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInReflectionCaptures
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInReflectionCaptures private
Definition at line 493 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bVisibleInSceneCaptureOnly
uint32 FPrimitiveUniformShaderParametersBuilder::bVisibleInSceneCaptureOnly private
Definition at line 497 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), and Defaults().
bWritesCustomDepthStencil
uint32 FPrimitiveUniformShaderParametersBuilder::bWritesCustomDepthStencil private
Definition at line 504 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), CustomDepthStencil(), and Defaults().
LightingChannels
uint32 FPrimitiveUniformShaderParametersBuilder::LightingChannels private
Definition at line 475 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and LightingChannelMask().
ObjectRadius
float FPrimitiveUniformShaderParametersBuilder::ObjectRadius private
Definition at line 473 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), Defaults(), and WorldBounds().
Parameters
FPrimitiveUniformShaderParameters FPrimitiveUniformShaderParametersBuilder::Parameters private
Definition at line 466 of file PrimitiveUniformShaderParametersBuilder.h.
Referenced by Build(), CustomDepthStencil(), CustomPrimitiveData(), Defaults(), EditorColors(), InstanceLocalBounds(), LocalBounds(), MaxWorldPositionOffsetExtent(), MinMaxMaterialDisplacement(), NaniteFilterFlags(), NaniteImposterIndex(), ObjectBounds(), PreSkinnedLocalBounds(), and WorldBounds().
The documentation for this struct was generated from the following file:
PrimitiveUniformShaderParametersBuilder.h