Unreal Engine 5.6 C++ API: FPlatformTypeLayoutParameters Struct Reference
FPlatformTypeLayoutParameters Struct Reference abstract
#include "MemoryLayout.h"
Data Structures
struct InternalLinkType
struct InternalLinkType< __COUNTER__ - CounterBase >
Public Types
using DerivedType = PREPROCESSOR_REMOVE_OPTIONAL_PARENS(FPlatformTypeLayoutParameters)
enum Flags { Flag_Initialized = (1 << 0) , Flag_Is32Bit = (1 << 1) , Flag_AlignBases = (1 << 2) , Flag_WithEditorOnly = (1 << 3) }
Public Member Functions
void Append (FShaderKeyGenerator &KeyGen) const
void AppendKeyString (FString &KeyString) const
Allow the layout parameters to modify the given DDC key string.
uint32 GetRawPointerSize () const
bool HasAlignBases () const
void InitializeForArchive (FArchive &Ar)
void InitializeForClang ()
void InitializeForCurrent ()
void InitializeForMSVC ()
void InitializeForPlatform (const FString &PlatformName, bool bHasEditorOnlyData)
void InitializeForPlatform (const ITargetPlatform *TargetPlatform)
Initializes for the given platform, or for current platform if TargetPlatform is nullptr.
bool Is32Bit () const
bool IsCurrentPlatform () const
bool IsInitialized () const
PREPROCESSOR_JOIN (INTERNAL_LAYOUT_INTERFACE_PREFIX_, NonVirtual)(1) const FTypeLayoutDesc &GetTypeLayout() const PREPROCESSOR_JOIN(INTERNAL_LAYOUT_INTERFACE_SUFFIX_
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (uint32) Flags=0u
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (uint32) MaxFieldAlignment=0xffffffff
FArchive & Serialize (FArchive &Ar)
This is used for serializing into/from the DDC.
bool WithCasePreservingFName () const
bool WithEditorOnly () const
Static Public Member Functions
static FTypeLayoutDesc & StaticGetTypeLayout ()
Data Fields
PRAGMA_ENABLE_DEPRECATION_WARNINGS
Static Public Attributes
static NonVirtual constexpr int CounterBase = __COUNTER__
static constexpr ETypeLayoutInterface::Type InterfaceType = ETypeLayoutInterface::NonVirtual
Private Types
using InternalBaseType = typename TGetBaseTypeHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(FPlatformTypeLayoutParameters)>::Type
Private Member Functions
void Save (FCbWriter &Writer) const
bool TryLoad (FCbFieldView Field)
Static Private Member Functions
static void InternalDestroy (void *Object, const FTypeLayoutDesc &, const FPointerTableBase *PtrTable, bool bIsFrozen)
template<typename InternalType>
static void InternalInitializeBases (FTypeLayoutDesc &TypeDesc)
Friends
void Append (FShaderKeyGenerator &KeyGen, const FPlatformTypeLayoutParameters &Value)
bool LoadFromCompactBinary (FCbFieldView Field, FPlatformTypeLayoutParameters &OutValue)
bool operator!= (const FPlatformTypeLayoutParameters &Lhs, const FPlatformTypeLayoutParameters &Rhs)
FArchive & operator<< (FArchive &Ar, FPlatformTypeLayoutParameters &Ref)
FCbWriter & operator<< (FCbWriter &Writer, const FPlatformTypeLayoutParameters &Value)
bool operator== (const FPlatformTypeLayoutParameters &Lhs, const FPlatformTypeLayoutParameters &Rhs)
Detailed Description
Definition at line 798 of file MemoryLayout.h.
Member Typedef Documentation
DerivedType
using FPlatformTypeLayoutParameters::DerivedType = PREPROCESSOR_REMOVE_OPTIONAL_PARENS(FPlatformTypeLayoutParameters)
Definition at line 800 of file MemoryLayout.h.
InternalBaseType
using FPlatformTypeLayoutParameters::InternalBaseType = typename TGetBaseTypeHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(FPlatformTypeLayoutParameters)>::Type private
Definition at line 800 of file MemoryLayout.h.
Member Enumeration Documentation
Flags
enum FPlatformTypeLayoutParameters::Flags
Enumerator
Flag_Initialized
Flag_Is32Bit
Flag_AlignBases
Flag_WithEditorOnly
Definition at line 802 of file MemoryLayout.h.
Member Function Documentation
Append()
void FPlatformTypeLayoutParameters::Append (FShaderKeyGenerator & KeyGen) const
AppendKeyString()
void FPlatformTypeLayoutParameters::AppendKeyString (FString & KeyString) const
Allow the layout parameters to modify the given DDC key string.
Since layout parameters are part of e.g. material shadermap ID, they should result in two different DDC entries for two different IDs, even if binary layouts happen to be compatible.
GetRawPointerSize()
uint32 FPlatformTypeLayoutParameters::GetRawPointerSize () const inline
Definition at line 821 of file MemoryLayout.h.
References Is32Bit().
HasAlignBases()
bool FPlatformTypeLayoutParameters::HasAlignBases () const inline
Definition at line 815 of file MemoryLayout.h.
References Flag_AlignBases.
InitializeForArchive()
void FPlatformTypeLayoutParameters::InitializeForArchive (FArchive & Ar)
References Ar.
InitializeForClang()
void FPlatformTypeLayoutParameters::InitializeForClang ()
InitializeForCurrent()
void FPlatformTypeLayoutParameters::InitializeForCurrent ()
InitializeForMSVC()
void FPlatformTypeLayoutParameters::InitializeForMSVC ()
InitializeForPlatform() [1/2]
void FPlatformTypeLayoutParameters::InitializeForPlatform (const FString & PlatformName, bool bHasEditorOnlyData)
InitializeForPlatform() [2/2]
void FPlatformTypeLayoutParameters::InitializeForPlatform (const ITargetPlatform * TargetPlatform)
Initializes for the given platform, or for current platform if TargetPlatform is nullptr.
InternalDestroy()
void FPlatformTypeLayoutParameters::InternalDestroy (void * Object, const FTypeLayoutDesc & , const FPointerTableBase * PtrTable, bool bIsFrozen) static private
InternalInitializeBases()
template<typename InternalType> void FPlatformTypeLayoutParameters::InternalInitializeBases (FTypeLayoutDesc & TypeDesc) inline static private
Definition at line 800 of file MemoryLayout.h.
Is32Bit()
bool FPlatformTypeLayoutParameters::Is32Bit () const inline
Definition at line 814 of file MemoryLayout.h.
References Flag_Is32Bit.
Referenced by GetRawPointerSize(), and FMemoryImageWriter::Is32BitTarget().
IsCurrentPlatform()
bool FPlatformTypeLayoutParameters::IsCurrentPlatform () const
IsInitialized()
bool FPlatformTypeLayoutParameters::IsInitialized () const inline
Definition at line 813 of file MemoryLayout.h.
References Flag_Initialized.
PREPROCESSOR_JOIN()
FPlatformTypeLayoutParameters::PREPROCESSOR_JOIN (INTERNAL_LAYOUT_INTERFACE_PREFIX_ , NonVirtual) const &
PREPROCESSOR_REMOVE_OPTIONAL_PARENS() [1/2]
FPlatformTypeLayoutParameters::PREPROCESSOR_REMOVE_OPTIONAL_PARENS (uint32) pure virtual
PREPROCESSOR_REMOVE_OPTIONAL_PARENS() [2/2]
FPlatformTypeLayoutParameters::PREPROCESSOR_REMOVE_OPTIONAL_PARENS (uint32) pure virtual
Save()
void FPlatformTypeLayoutParameters::Save (FCbWriter & Writer) const private
Serialize()
FArchive & FPlatformTypeLayoutParameters::Serialize (FArchive & Ar)
This is used for serializing into/from the DDC.
References Ar.
StaticGetTypeLayout()
FTypeLayoutDesc & FPlatformTypeLayoutParameters::StaticGetTypeLayout () static
TryLoad()
bool FPlatformTypeLayoutParameters::TryLoad (FCbFieldView Field) private
WithCasePreservingFName()
bool FPlatformTypeLayoutParameters::WithCasePreservingFName () const inline
Definition at line 819 of file MemoryLayout.h.
References WithEditorOnly().
WithEditorOnly()
bool FPlatformTypeLayoutParameters::WithEditorOnly () const inline
Definition at line 816 of file MemoryLayout.h.
References Flag_WithEditorOnly.
Referenced by WithCasePreservingFName().
Friends And Related Symbol Documentation
Append
void Append (FShaderKeyGenerator & KeyGen, const FPlatformTypeLayoutParameters & Value) friend
Definition at line 864 of file MemoryLayout.h.
References Value.
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FPlatformTypeLayoutParameters & OutValue) friend
operator!=
bool operator!= (const FPlatformTypeLayoutParameters & Lhs, const FPlatformTypeLayoutParameters & Rhs) friend
Definition at line 833 of file MemoryLayout.h.
References operator==.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPlatformTypeLayoutParameters & Ref) friend
Definition at line 823 of file MemoryLayout.h.
References Ar.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FPlatformTypeLayoutParameters & Value) friend
Definition at line 872 of file MemoryLayout.h.
References Value.
operator==
bool operator== (const FPlatformTypeLayoutParameters & Lhs, const FPlatformTypeLayoutParameters & Rhs) friend
Definition at line 828 of file MemoryLayout.h.
Referenced by operator!=.
Field Documentation
CounterBase
NonVirtual constexpr int FPlatformTypeLayoutParameters::CounterBase = __COUNTER__ static constexpr
Definition at line 800 of file MemoryLayout.h.
InterfaceType
ETypeLayoutInterface::Type FPlatformTypeLayoutParameters::InterfaceType = ETypeLayoutInterface::NonVirtual static constexpr
Definition at line 800 of file MemoryLayout.h.
PRAGMA_ENABLE_DEPRECATION_WARNINGS
FPlatformTypeLayoutParameters::PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 810 of file MemoryLayout.h.
The documentation for this struct was generated from the following file:
MemoryLayout.h