Unreal Engine 5.6 C++ API: FWorldPartitionActorDescUtils Struct Reference
FWorldPartitionActorDescUtils Struct Reference
#include "WorldPartitionActorDescUtils.h"
Data Structures
struct FActorDescInitParams
Public Member Functions
UE_DEPRECATED (5.4, "Call the version that takes FAssetRegistryTagsContext instead.") static 1 void AppendAssetDataTagsFromActor(const AActor *InActor
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version instead") static void ReplaceActorDescriptorPointerFromActor(const AActor *InOldActor
Static Public Member Functions
static FName ActorMetaDataClassTagName ()
static FName ActorMetaDataTagName ()
static void AppendAssetDataTagsFromActor (const AActor *InActor, FAssetRegistryTagsContext Context)
Appends the actor's actor descriptor data into the provided asset registry tags.
static TUniquePtr< FWorldPartitionActorDesc > GetActorDescriptorFromAssetData (const FAssetData &InAssetData)
Creates a valid actor descriptor from the provided asset data.
static TUniquePtr< FWorldPartitionActorDesc > GetActorDescriptorFromInitParams (const FActorDescInitParams &InActorDescInitParams, FName InPackageName)
Creates a valid actor descriptor from the provided actor descriptor init params.
static UClass * GetActorNativeClassFromAssetData (const FAssetData &InAssetData)
Retrieve the actor's native class from the asset data.
static UClass * GetActorNativeClassFromString (const FString &InClassPath)
Retrieve the actor's native class from the string.
static FString GetAssetDataFromActorDescriptor (TUniquePtr< FWorldPartitionActorDesc > &InActorDesc)
Return the actor descriptor data.
static bool GetPatchedAssetDataFromAssetData (const FAssetData &InAssetData, FString &OutAssetData, FWorldPartitionAssetDataPatcher *InAssetDataPatcher)
Patches an actor descriptor's asset data.
static bool IsValidActorDescriptorFromAssetData (const FAssetData &InAssetData)
Checks if the provided asset data contains a valid actor descriptor.
static void ReplaceActorDescriptorPointerFromActor (const AActor *InOldActor, AActor *InNewActor, FWorldPartitionActorDescInstance *InActorDescInstance)
Replaces the actor descriptor's actor pointer with the provided new actor pointer.
static void UpdateActorDescriptorFromActor (const AActor *InActor, TUniquePtr< FWorldPartitionActorDesc > &OutActorDesc)
Update an actor descriptor with new values coming from the provided actor.
static void UpdateActorDescriptorFromActorDescriptor (TUniquePtr< FWorldPartitionActorDesc > &InActorDesc, TUniquePtr< FWorldPartitionActorDesc > &OutActorDesc)
Update an actor descriptor with new values coming from the provided actor descriptor.
Data Fields
AActor FWorldPartitionActorDesc * InActorDesc
AActor * InNewActor
TArray< UObject::FAssetRegistryTag > & OutTags
Detailed Description
Definition at line 13 of file WorldPartitionActorDescUtils.h.
Member Function Documentation
ActorMetaDataClassTagName()
FName FWorldPartitionActorDescUtils::ActorMetaDataClassTagName () static
Returns
The asset registry tag name for ActorMetaDataClass
ActorMetaDataTagName()
FName FWorldPartitionActorDescUtils::ActorMetaDataTagName () static
Returns
The asset registry tag name for ActorMetaData
AppendAssetDataTagsFromActor()
void FWorldPartitionActorDescUtils::AppendAssetDataTagsFromActor (const AActor * InActor, FAssetRegistryTagsContext Context) static
Appends the actor's actor descriptor data into the provided asset registry tags.
Parameters
InActor The actor that will append its actor descriptor.
OutTags Output tags to output into.
GetActorDescriptorFromAssetData()
TUniquePtr< FWorldPartitionActorDesc > FWorldPartitionActorDescUtils::GetActorDescriptorFromAssetData (const FAssetData & InAssetData) static
Creates a valid actor descriptor from the provided asset data.
Parameters
InAssetData The asset data to look into.
Returns
Actor descriptor retrieved from the provided asset data.
GetActorDescriptorFromInitParams()
TUniquePtr< FWorldPartitionActorDesc > FWorldPartitionActorDescUtils::GetActorDescriptorFromInitParams (const FActorDescInitParams & InActorDescInitParams, FName InPackageName) static
Creates a valid actor descriptor from the provided actor descriptor init params.
Parameters
InActorDescInitParams The actor dfescriptor input params.
InPackageName The package name the actor descriptor comes from.
Returns
Actor descriptor retrieved from the provided asset data.
GetActorNativeClassFromAssetData()
UClass * FWorldPartitionActorDescUtils::GetActorNativeClassFromAssetData (const FAssetData & InAssetData) static
Retrieve the actor's native class from the asset data.
Parameters
InAssetData The asset data to look into.
Returns
The actor's native class.
GetActorNativeClassFromString()
UClass * FWorldPartitionActorDescUtils::GetActorNativeClassFromString (const FString & InClassPath) static
Retrieve the actor's native class from the string.
Parameters
InClassPath The class path to resolve.
Returns
The actor's native class.
GetAssetDataFromActorDescriptor()
FString FWorldPartitionActorDescUtils::GetAssetDataFromActorDescriptor (TUniquePtr< FWorldPartitionActorDesc > & InActorDesc) static
Return the actor descriptor data.
Parameters
InActorDesc The actor descriptor that will generate the data.
Returns
The actor descriptor data.
References GetAssetDataFromActorDescriptor(), and InActorDesc.
Referenced by GetAssetDataFromActorDescriptor().
GetPatchedAssetDataFromAssetData()
bool FWorldPartitionActorDescUtils::GetPatchedAssetDataFromAssetData (const FAssetData & InAssetData, FString & OutAssetData, FWorldPartitionAssetDataPatcher * InAssetDataPatcher) static
Patches an actor descriptor's asset data.
Parameters
InAssetData The asset data to be patched.
OutAssetData The patched asset data.
InAssetDataPatcher The patcher object.
Returns
The actor descriptor patched data.
References GetPatchedAssetDataFromAssetData().
Referenced by GetPatchedAssetDataFromAssetData().
IsValidActorDescriptorFromAssetData()
bool FWorldPartitionActorDescUtils::IsValidActorDescriptorFromAssetData (const FAssetData & InAssetData) static
Checks if the provided asset data contains a valid actor descriptor.
Parameters
InAssetData The asset data to look into.
Returns
Whether the provideed asset data contains a valid actor descriptor or not.
ReplaceActorDescriptorPointerFromActor()
void FWorldPartitionActorDescUtils::ReplaceActorDescriptorPointerFromActor (const AActor * InOldActor, AActor * InNewActor, FWorldPartitionActorDescInstance * InActorDescInstance) static
Replaces the actor descriptor's actor pointer with the provided new actor pointer.
Parameters
InOldActor The old actor that the provided actor descriptor was representing.
InNewActor The new actor that the provided actor descriptor should be representing.
InActorDescInstance Actor descriptor instance that will get its actor pointer updated.
References InNewActor, and ReplaceActorDescriptorPointerFromActor().
Referenced by ReplaceActorDescriptorPointerFromActor().
UE_DEPRECATED() [1/2]
FWorldPartitionActorDescUtils::UE_DEPRECATED (5. 4, "Call the version that takes FAssetRegistryTagsContext instead.") const
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FWorldPartitionActorDescUtils::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version instead") const
References UE_DEPRECATED().
UpdateActorDescriptorFromActor()
void FWorldPartitionActorDescUtils::UpdateActorDescriptorFromActor (const AActor * InActor, TUniquePtr< FWorldPartitionActorDesc > & OutActorDesc) static
Update an actor descriptor with new values coming from the provided actor.
Parameters
InActor The actor to update from.
OutActorDesc Actor descriptor unique pointer that will get updated with the new actor descriptor.
References UpdateActorDescriptorFromActor().
Referenced by UpdateActorDescriptorFromActor().
UpdateActorDescriptorFromActorDescriptor()
void FWorldPartitionActorDescUtils::UpdateActorDescriptorFromActorDescriptor (TUniquePtr< FWorldPartitionActorDesc > & InActorDesc, TUniquePtr< FWorldPartitionActorDesc > & OutActorDesc) static
Update an actor descriptor with new values coming from the provided actor descriptor.
Parameters
InActorDesc The actor descriptor to update from.
OutActorDesc Actor descriptor unique pointer that will get updated with the new actor descriptor.
References InActorDesc, and UpdateActorDescriptorFromActorDescriptor().
Referenced by UpdateActorDescriptorFromActorDescriptor().
Field Documentation
InActorDesc
AActor FWorldPartitionActorDesc* FWorldPartitionActorDescUtils::InActorDesc
Initial value:
{}
    UE_DEPRECATED(5.3, "Use FWorldPartitionHelpers::FixupRedirectedAssetPath instead")
    static 1 bool FixupRedirectedAssetPath(FName& InOutAssetPath)
Definition at line 120 of file WorldPartitionActorDescUtils.h.
Referenced by GetAssetDataFromActorDescriptor(), and UpdateActorDescriptorFromActorDescriptor().
InNewActor
AActor* FWorldPartitionActorDescUtils::InNewActor
Definition at line 120 of file WorldPartitionActorDescUtils.h.
Referenced by ReplaceActorDescriptorPointerFromActor().
OutTags
TArray<UObject::FAssetRegistryTag>& FWorldPartitionActorDescUtils::OutTags
Definition at line 79 of file WorldPartitionActorDescUtils.h.
The documentation for this struct was generated from the following file:
WorldPartitionActorDescUtils.h