Unreal Engine 5.6 C++ API: SMyBlueprint Class Reference
SMyBlueprint Class Reference
#include "SMyBlueprint.h"
Public Member Functions
~SMyBlueprint ()
bool CanPasteGeneric ()
void ClearGraphActionMenuSelection ()
Clears the selection in the graph action menus.
void EnsureLastPinTypeValid ()
void ExpandCategory (const FText &CategoryName)
Expands any category with the associated name.
TWeakPtr< FBlueprintEditor > GetBlueprintEditor ()
Gets our parent blueprint editor.
UBlueprint * GetBlueprintObj () const
Accessor the blueprint object from the main editor.
FEdGraphPinType & GetLastFunctionPinTypeUsed ()
FEdGraphPinType & GetLastPinTypeUsed ()
Gets the last pin type selected by this widget, or by the function editor.
void GetSelectedItemsForContextMenu (TArray< FComponentEventConstructionData > &OutSelectedItems) const
Fills the supplied array with the currently selected objects.
bool MoveCategoryBeforeCategory (const FText &CategoryToMove, const FText &TargetCategory)
Move the category before the target category.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
void OnPasteGeneric ()
Callbacks for Paste Commands.
void OnRequestRenameOnActionNode ()
Initiates a rename on the selected action node, if possible.
void OnResetItemFilter ()
Called to reset the search filter.
void Refresh ()
Refreshes the graph action menu.
void ResetLastPinType ()
FEdGraphSchemaAction_BlueprintVariableBase * SelectionAsBlueprintVariable () const
Accessor for getting the current selection as a K2 blueprint base variable.
FEdGraphSchemaAction_K2Delegate * SelectionAsDelegate () const
Accessor for getting the current selection as a K2 delegate.
FEdGraphSchemaAction_K2Enum * SelectionAsEnum () const
Accessor for getting the current selection as a K2 enum.
FEdGraphSchemaAction_K2Event * SelectionAsEvent () const
Accessor for getting the current selection as a K2 event.
FEdGraphSchemaAction_K2Graph * SelectionAsGraph () const
Accessor for getting the current selection as a K2 graph.
FEdGraphSchemaAction_K2InputAction * SelectionAsInputAction () const
Accessor for getting the current selection as a K2 Input Action.
FEdGraphSchemaAction_K2LocalVar * SelectionAsLocalVar () const
Accessor for getting the current selection as a K2 local var.
FEdGraphSchemaAction_K2Struct * SelectionAsStruct () const
Accessor for getting the current selection as a K2 enum.
FEdGraphSchemaAction_K2Var * SelectionAsVar () const
Accessor for getting the current selection as a K2 var.
bool SelectionIsCategory () const
Accessor for determining if the current selection is a category.
void SelectItemByName (const FName &ItemName, ESelectInfo::Type SelectInfo=ESelectInfo::Direct, int32 SectionId=INDEX_NONE, bool bIsCategory=false)
Selects an item by name in either the main graph action menu or the local one.
void SetFocusedGraph (UEdGraph *InEdGraph)
void SetInspector (TSharedPtr< SKismetInspector > InInspector)
bool ShowUserVarsOnly () const
Gets whether we are showing user variables only or not.
SLATE_BEGIN_ARGS (SMyBlueprint)
SLATE_END_ARGS () void Construct(const FArguments &InArgs
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TWeakPtr< FBlueprintEditor > const UBlueprint * InBlueprint = nullptr)
TWeakPtr< FBlueprintEditor > InBlueprintEditor
Private Member Functions
void AddEventForFunctionGraph (UEdGraph *EdGraph, int32 const SectionId, FGraphActionSort &SortList, const FText &ParentCategory=FText::GetEmpty(), bool bAddChildGraphs=true) const
void BuildAddNewMenu (FMenuBuilder &MenuBuilder)
void BuildOverridableFunctionsMenu (FMenuBuilder &MenuBuilder)
bool CanAddNewElementToSection (int32 InSectionID) const
bool CanCopy () const
bool CanCut () const
bool CanDeleteEntry () const
bool CanDuplicateAction () const
bool CanFindAndReplaceReference () const
bool CanFindReference () const
bool CanFocusOnNode () const
bool CanImplementFunction () const
bool CanMoveFunctionToParent () const
bool CanMoveVariableToParent () const
bool CanOpenExternalGraph () const
bool CanOpenGraph () const
bool CanPasteFunction () const
bool CanPasteLocalVariable () const
bool CanPasteMacro () const
bool CanPasteVariable () const
bool CanRequestRenameOnActionNode () const
bool CanRequestRenameOnActionNode (TWeakPtr< struct FGraphActionNode > InSelectedNode) const
void CollectAllActions (FGraphActionListBuilderBase &OutAllActions)
Callback used to populate all actions list in SGraphActionMenu.
void CollectStaticSections (TArray< int32 > &StaticSectionIDs)
TSharedRef< SWidget > CreateAddNewMenuWidget ()
TSharedRef< SWidget > CreateAddToSectionButton (int32 InSectionID, TWeakPtr< SWidget > WeakRowWidget, FText AddNewText, FName MetaDataTag)
void ExecuteAction (TSharedPtr< FEdGraphSchemaAction > InAction)
bool GetAlwaysShowInterfacesInOverrides () const
void GetChildEvents (UEdGraph const *EdGraph, int32 const SectionId, FGraphActionSort &SortList, const FText &ParentCategory=FText::GetEmpty(), bool bInAddChildGraphs=true) const
void GetChildGraphs (UEdGraph *EdGraph, int32 const SectionId, FGraphActionSort &SortList, const FText &ParentCategory=FText::GetEmpty()) const
FText GetFilterText () const
Callback for the action trees to get the filter text.
UEdGraph * GetFocusedGraph () const
FText GetGraphCategory (UEdGraph *InGraph) const
Returns the displayed category, if any, of a graph.
EVisibility GetLocalActionsListVisibility () const
Handles the visibility of the local action list.
void GetLocalVariables (FGraphActionSort &SortList) const
FText GetPasteCategory () const
Gets the currently selected Category or returns default category name.
bool GetShowAccessSpecifier () const
bool GetShowParentClassInOverrides () const
void GotoNativeCodeVarDefinition ()
bool HandleActionMatchesName (FEdGraphSchemaAction *InAction, const FName &InName) const
void ImplementFunction (FEdGraphSchemaAction_K2Graph *GraphAction)
void ImplementFunction (TSharedPtr< FEdGraphSchemaAction_K2Graph > GraphAction)
bool IsDuplicateActionVisible () const
bool IsEditingMode () const
Helper function indicating whehter we're in editing mode, and can modify the target blueprint.
bool IsImplementationDesiredAsFunction (const UFunction *OverrideFunc) const
Check if the override of a given function is most likely desired as a blueprint function or as an event.
bool IsNativeVariable () const
bool IsShowingEmptySections () const
bool IsShowingInheritedVariables () const
Support functions for checkbox to manage displaying user variables only.
bool IsShowingReplicatedVariablesOnly () const
void OnActionDoubleClicked (const TArray< TSharedPtr< FEdGraphSchemaAction > > &InActions)
FReply OnActionDragged (const TArray< TSharedPtr< FEdGraphSchemaAction > > &InActions, const FPointerEvent &MouseEvent)
Callbacks for the graph action menu.
void OnActionSelected (const TArray< TSharedPtr< FEdGraphSchemaAction > > &InActions)
void OnActionSelectedHelper (TSharedPtr< FEdGraphSchemaAction > InAction, TWeakPtr< FBlueprintEditor > InBlueprintEditor, UBlueprint *Blueprint, TSharedRef< SKismetInspector > Inspector)
FReply OnAddButtonClickedOnSection (int32 InSectionID)
FReply OnAddNewLocalVariable ()
FReply OnCategoryDragged (const FText &InCategory, const FPointerEvent &MouseEvent)
void OnCategoryNameCommitted (const FText &InNewText, ETextCommit::Type InTextCommit, TWeakPtr< struct FGraphActionNode > InAction)
TSharedPtr< SWidget > OnContextMenuOpening ()
void OnCopy ()
TSharedRef< SWidget > OnCreateWidgetForAction (struct FCreateWidgetForActionData *const InCreateData)
Creates widgets for the graph schema actions.
void OnCut ()
void OnDeleteDelegate (FEdGraphSchemaAction_K2Delegate *InDelegateAction)
Helper function to delete a delegate in the MyBlueprint window.
void OnDeleteEntry ()
void OnDeleteGraph (UEdGraph *InGraph, EEdGraphSchemaAction_K2Graph::Type)
Helper function to delete a graph in the MyBlueprint window.
void OnDuplicateAction ()
void OnFilterTextChanged (const FText &InFilterText)
Callback when the filter is changed, forces the action tree(s) to filter.
void OnFindAndReplaceReference ()
void OnFindReference (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags)
void OnFocusNode ()
void OnFocusNodeInNewTab ()
TSharedRef< SWidget > OnGetFunctionListMenu ()
EVisibility OnGetSectionTextVisibility (TWeakPtr< SWidget > RowWidget, int32 InSectionID) const
FText OnGetSectionTitle (int32 InSectionID)
TSharedRef< SWidget > OnGetSectionWidget (TSharedRef< SWidget > RowWidget, int32 InSectionID)
void OnGlobalActionSelected (const TArray< TSharedPtr< FEdGraphSchemaAction > > &InActions, ESelectInfo::Type InSelectionType)
void OnImplementFunction ()
void OnMoveToParent ()
void OnObjectPropertyChanged (UObject *InObject, FPropertyChangedEvent &InPropertyChangedEvent)
Delegate to hook us into non-structural Blueprint object post-change events.
void OnOpenExternalGraph ()
void OnOpenGraph ()
Callbacks for commands.
void OnOpenGraphInNewTab ()
void OnPasteFunction ()
void OnPasteLocalVariable ()
void OnPasteMacro ()
void OnPasteVariable ()
void OnToggleAlwaysShowInterfacesInOverrides ()
Support functions for view options for bAlwaysShowInterfacesInOverrides blueprint editor setting.
void OnToggleShowAccessSpecifier ()
Support functions for view options for bShowAccessSpecifier blueprint editor setting.
void OnToggleShowEmptySections ()
Support functions for view options for Show Empty Sections.
void OnToggleShowInheritedVariables ()
void OnToggleShowParentClassInOverrides ()
Support functions for view options for bShowParentClassInOverrides blueprint editor setting.
void OnToggleShowReplicatedVariablesOnly ()
Support functions for view options for Show Replicated Variables only.
void OpenGraph (FDocumentTracker::EOpenDocumentCause InCause, bool bOpenExternalGraphInNewEditor=false)
Helper function to open the selected graph.
bool SelectionHasContextMenu () const
Checks if the selected action has context menu.
void UpdateNodeCreation ()
Update Node Create Analytic.
Static Private Member Functions
static bool IsAnInterfaceEvent (FEdGraphSchemaAction_K2Graph *InAction)
Determine whether an FEdGraphSchemaAction is associated with an event.
Private Attributes
UBlueprint * Blueprint
The blueprint being displayed:
TWeakPtr< FBlueprintEditor > BlueprintEditorPtr
Pointer back to the blueprint editor that owns us.
bool bNeedsRefresh
Flag to indicate whether or not we need to refresh the panel.
bool bShowReplicatedVariablesOnly
If set we'll show only replicated variables (local to a particular blueprint view).
TSharedPtr< FUICommandList > CommandList
List of UI Commands for this scope.
UEdGraph * EdGraph
The Ed Graph being displayed:
TArray< TWeakObjectPtr< UUserDefinedEnum > > EnumsAddedToBlueprint
Enums created from 'blueprint' level.
TSharedPtr< SSearchBox > FilterBox
The filter box that handles filtering for both graph action menus.
TSharedPtr< SComboButton > FunctionSectionButton
The +Function button in the function section.
TSharedPtr< class SGraphActionMenu > GraphActionMenu
Graph Action Menu for displaying all our variables and functions.
TSet< FName > ImplementedFunctionCache
When we refresh the list of functions we cache off the implemented ones to ask questions for overridable functions.
TWeakPtr< SKismetInspector > Inspector
The Kismet Inspector used to display properties:
FEdGraphPinType LastFunctionPinType
FEdGraphPinType LastPinType
The last pin type used (including the function editor last pin type)
TArray< TSharedPtr< FEdGraphSchemaAction_K2Graph > > OverridableFunctionActions
When we rebuild the view of members, we cache (but don't display) any overridable functions for user in popup menus.
TArray< TWeakObjectPtr< UUserDefinedStruct > > StructsAddedToBlueprint
Enums created from 'blueprint' level.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 85 of file SMyBlueprint.h.
Constructor & Destructor Documentation
~SMyBlueprint()
SMyBlueprint::~SMyBlueprint ()
Member Function Documentation
AddEventForFunctionGraph()
void SMyBlueprint::AddEventForFunctionGraph (UEdGraph * EdGraph, int32 const SectionId, FGraphActionSort & SortList, const FText & ParentCategory = FText::GetEmpty(), bool bAddChildGraphs = true) const private
References EdGraph, and FText::GetEmpty().
BuildAddNewMenu()
void SMyBlueprint::BuildAddNewMenu (FMenuBuilder & MenuBuilder) private
BuildOverridableFunctionsMenu()
void SMyBlueprint::BuildOverridableFunctionsMenu (FMenuBuilder & MenuBuilder) private
CanAddNewElementToSection()
bool SMyBlueprint::CanAddNewElementToSection (int32 InSectionID) const private
CanCopy()
bool SMyBlueprint::CanCopy () const private
CanCut()
bool SMyBlueprint::CanCut () const private
CanDeleteEntry()
bool SMyBlueprint::CanDeleteEntry () const private
CanDuplicateAction()
bool SMyBlueprint::CanDuplicateAction () const private
CanFindAndReplaceReference()
bool SMyBlueprint::CanFindAndReplaceReference () const private
CanFindReference()
bool SMyBlueprint::CanFindReference () const private
CanFocusOnNode()
bool SMyBlueprint::CanFocusOnNode () const private
CanImplementFunction()
bool SMyBlueprint::CanImplementFunction () const private
CanMoveFunctionToParent()
bool SMyBlueprint::CanMoveFunctionToParent () const private
CanMoveVariableToParent()
bool SMyBlueprint::CanMoveVariableToParent () const private
CanOpenExternalGraph()
bool SMyBlueprint::CanOpenExternalGraph () const private
CanOpenGraph()
bool SMyBlueprint::CanOpenGraph () const private
CanPasteFunction()
bool SMyBlueprint::CanPasteFunction () const private
CanPasteGeneric()
bool SMyBlueprint::CanPasteGeneric ()
CanPasteLocalVariable()
bool SMyBlueprint::CanPasteLocalVariable () const private
CanPasteMacro()
bool SMyBlueprint::CanPasteMacro () const private
CanPasteVariable()
bool SMyBlueprint::CanPasteVariable () const private
CanRequestRenameOnActionNode() [1/2]
bool SMyBlueprint::CanRequestRenameOnActionNode () const private
CanRequestRenameOnActionNode() [2/2]
bool SMyBlueprint::CanRequestRenameOnActionNode (TWeakPtr< struct FGraphActionNode > InSelectedNode) const private
ClearGraphActionMenuSelection()
void SMyBlueprint::ClearGraphActionMenuSelection ()
Clears the selection in the graph action menus.
CollectAllActions()
void SMyBlueprint::CollectAllActions (FGraphActionListBuilderBase & OutAllActions) private
Callback used to populate all actions list in SGraphActionMenu.
CollectStaticSections()
void SMyBlueprint::CollectStaticSections (TArray< int32 > & StaticSectionIDs) private
CreateAddNewMenuWidget()
TSharedRef< SWidget > SMyBlueprint::CreateAddNewMenuWidget () private
CreateAddToSectionButton()
TSharedRef< SWidget > SMyBlueprint::CreateAddToSectionButton (int32 InSectionID, TWeakPtr< SWidget > WeakRowWidget, FText AddNewText, FName MetaDataTag) private
EnsureLastPinTypeValid()
void SMyBlueprint::EnsureLastPinTypeValid ()
Referenced by GetLastFunctionPinTypeUsed(), and GetLastPinTypeUsed().
ExecuteAction()
void SMyBlueprint::ExecuteAction (TSharedPtr< FEdGraphSchemaAction > InAction) private
ExpandCategory()
void SMyBlueprint::ExpandCategory (const FText & CategoryName)
Expands any category with the associated name.
GetAlwaysShowInterfacesInOverrides()
bool SMyBlueprint::GetAlwaysShowInterfacesInOverrides () const private
GetBlueprintEditor()
TWeakPtr< FBlueprintEditor > SMyBlueprint::GetBlueprintEditor () inline
Gets our parent blueprint editor.
Definition at line 150 of file SMyBlueprint.h.
References BlueprintEditorPtr.
GetBlueprintObj()
UBlueprint * SMyBlueprint::GetBlueprintObj () const inline
Accessor the blueprint object from the main editor.
Definition at line 144 of file SMyBlueprint.h.
References Blueprint.
GetChildEvents()
void SMyBlueprint::GetChildEvents (UEdGraph const * EdGraph, int32 const SectionId, FGraphActionSort & SortList, const FText & ParentCategory = FText::GetEmpty(), bool bInAddChildGraphs = true) const private
References EdGraph, and FText::GetEmpty().
GetChildGraphs()
void SMyBlueprint::GetChildGraphs (UEdGraph * EdGraph, int32 const SectionId, FGraphActionSort & SortList, const FText & ParentCategory = FText::GetEmpty()) const private
References EdGraph, and FText::GetEmpty().
GetFilterText()
FText SMyBlueprint::GetFilterText () const private
Callback for the action trees to get the filter text.
GetFocusedGraph()
UEdGraph * SMyBlueprint::GetFocusedGraph () const private
GetGraphCategory()
FText SMyBlueprint::GetGraphCategory (UEdGraph * InGraph) const private
Returns the displayed category, if any, of a graph.
GetLastFunctionPinTypeUsed()
FEdGraphPinType & SMyBlueprint::GetLastFunctionPinTypeUsed () inline
Definition at line 141 of file SMyBlueprint.h.
References EnsureLastPinTypeValid(), and LastFunctionPinType.
GetLastPinTypeUsed()
FEdGraphPinType & SMyBlueprint::GetLastPinTypeUsed () inline
Gets the last pin type selected by this widget, or by the function editor.
Definition at line 140 of file SMyBlueprint.h.
References EnsureLastPinTypeValid(), and LastPinType.
GetLocalActionsListVisibility()
EVisibility SMyBlueprint::GetLocalActionsListVisibility () const private
Handles the visibility of the local action list.
GetLocalVariables()
void SMyBlueprint::GetLocalVariables (FGraphActionSort & SortList) const private
GetPasteCategory()
FText SMyBlueprint::GetPasteCategory () const private
Gets the currently selected Category or returns default category name.
GetSelectedItemsForContextMenu()
void SMyBlueprint::GetSelectedItemsForContextMenu (TArray< FComponentEventConstructionData > & OutSelectedItems) const
Fills the supplied array with the currently selected objects.
Parameters
OutSelectedItems The array to fill.
GetShowAccessSpecifier()
bool SMyBlueprint::GetShowAccessSpecifier () const private
GetShowParentClassInOverrides()
bool SMyBlueprint::GetShowParentClassInOverrides () const private
GotoNativeCodeVarDefinition()
void SMyBlueprint::GotoNativeCodeVarDefinition () private
HandleActionMatchesName()
bool SMyBlueprint::HandleActionMatchesName (FEdGraphSchemaAction * InAction, const FName & InName) const private
References InName.
ImplementFunction() [1/2]
void SMyBlueprint::ImplementFunction (FEdGraphSchemaAction_K2Graph * GraphAction) private
ImplementFunction() [2/2]
void SMyBlueprint::ImplementFunction (TSharedPtr< FEdGraphSchemaAction_K2Graph > GraphAction) private
IsAnInterfaceEvent()
bool SMyBlueprint::IsAnInterfaceEvent (FEdGraphSchemaAction_K2Graph * InAction) static private
Determine whether an FEdGraphSchemaAction is associated with an event.
IsDuplicateActionVisible()
bool SMyBlueprint::IsDuplicateActionVisible () const private
IsEditingMode()
bool SMyBlueprint::IsEditingMode () const private
Helper function indicating whehter we're in editing mode, and can modify the target blueprint.
IsImplementationDesiredAsFunction()
bool SMyBlueprint::IsImplementationDesiredAsFunction (const UFunction * OverrideFunc) const private
Check if the override of a given function is most likely desired as a blueprint function or as an event.
Parameters
OverrideFunc Desired function to override
Returns
True if the function is desired as a function, false if desired as an event
IsNativeVariable()
bool SMyBlueprint::IsNativeVariable () const private
IsShowingEmptySections()
bool SMyBlueprint::IsShowingEmptySections () const private
IsShowingInheritedVariables()
bool SMyBlueprint::IsShowingInheritedVariables () const private
Support functions for checkbox to manage displaying user variables only.
Referenced by ShowUserVarsOnly().
IsShowingReplicatedVariablesOnly()
bool SMyBlueprint::IsShowingReplicatedVariablesOnly () const private
MoveCategoryBeforeCategory()
bool SMyBlueprint::MoveCategoryBeforeCategory (const FText & CategoryToMove, const FText & TargetCategory)
Move the category before the target category.
OnActionDoubleClicked()
void SMyBlueprint::OnActionDoubleClicked (const TArray< TSharedPtr< FEdGraphSchemaAction > > & InActions) private
OnActionDragged()
FReply SMyBlueprint::OnActionDragged (const TArray< TSharedPtr< FEdGraphSchemaAction > > & InActions, const FPointerEvent & MouseEvent) private
Callbacks for the graph action menu.
References MouseEvent.
OnActionSelected()
void SMyBlueprint::OnActionSelected (const TArray< TSharedPtr< FEdGraphSchemaAction > > & InActions) private
OnActionSelectedHelper()
void SMyBlueprint::OnActionSelectedHelper (TSharedPtr< FEdGraphSchemaAction > InAction, TWeakPtr< FBlueprintEditor > InBlueprintEditor, UBlueprint * Blueprint, TSharedRef< SKismetInspector > Inspector) private
References Blueprint, InBlueprintEditor, and Inspector.
OnAddButtonClickedOnSection()
FReply SMyBlueprint::OnAddButtonClickedOnSection (int32 InSectionID) private
OnAddNewLocalVariable()
FReply SMyBlueprint::OnAddNewLocalVariable () private
OnCategoryDragged()
FReply SMyBlueprint::OnCategoryDragged (const FText & InCategory, const FPointerEvent & MouseEvent) private
References MouseEvent.
OnCategoryNameCommitted()
void SMyBlueprint::OnCategoryNameCommitted (const FText & InNewText, ETextCommit::Type InTextCommit, TWeakPtr< struct FGraphActionNode > InAction) private
OnContextMenuOpening()
TSharedPtr< SWidget > SMyBlueprint::OnContextMenuOpening () private
OnCopy()
void SMyBlueprint::OnCopy () private
OnCreateWidgetForAction()
TSharedRef< SWidget > SMyBlueprint::OnCreateWidgetForAction (struct FCreateWidgetForActionData *const InCreateData) private
Creates widgets for the graph schema actions.
OnCut()
void SMyBlueprint::OnCut () private
OnDeleteDelegate()
void SMyBlueprint::OnDeleteDelegate (FEdGraphSchemaAction_K2Delegate * InDelegateAction) private
Helper function to delete a delegate in the MyBlueprint window.
OnDeleteEntry()
void SMyBlueprint::OnDeleteEntry () private
OnDeleteGraph()
void SMyBlueprint::OnDeleteGraph (UEdGraph * InGraph, EEdGraphSchemaAction_K2Graph::Type) private
Helper function to delete a graph in the MyBlueprint window.
OnDuplicateAction()
void SMyBlueprint::OnDuplicateAction () private
OnFilterTextChanged()
void SMyBlueprint::OnFilterTextChanged (const FText & InFilterText) private
Callback when the filter is changed, forces the action tree(s) to filter.
OnFindAndReplaceReference()
void SMyBlueprint::OnFindAndReplaceReference () private
OnFindReference()
void SMyBlueprint::OnFindReference (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags) private
References Flags.
OnFocusNode()
void SMyBlueprint::OnFocusNode () private
OnFocusNodeInNewTab()
void SMyBlueprint::OnFocusNodeInNewTab () private
OnGetFunctionListMenu()
TSharedRef< SWidget > SMyBlueprint::OnGetFunctionListMenu () private
OnGetSectionTextVisibility()
EVisibility SMyBlueprint::OnGetSectionTextVisibility (TWeakPtr< SWidget > RowWidget, int32 InSectionID) const private
OnGetSectionTitle()
FText SMyBlueprint::OnGetSectionTitle (int32 InSectionID) private
OnGetSectionWidget()
TSharedRef< SWidget > SMyBlueprint::OnGetSectionWidget (TSharedRef< SWidget > RowWidget, int32 InSectionID) private
OnGlobalActionSelected()
void SMyBlueprint::OnGlobalActionSelected (const TArray< TSharedPtr< FEdGraphSchemaAction > > & InActions, ESelectInfo::Type InSelectionType) private
OnImplementFunction()
void SMyBlueprint::OnImplementFunction () private
OnKeyDown()
virtual FReply SMyBlueprint::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMoveToParent()
void SMyBlueprint::OnMoveToParent () private
OnObjectPropertyChanged()
void SMyBlueprint::OnObjectPropertyChanged (UObject * InObject, FPropertyChangedEvent & InPropertyChangedEvent) private
Delegate to hook us into non-structural Blueprint object post-change events.
OnOpenExternalGraph()
void SMyBlueprint::OnOpenExternalGraph () private
OnOpenGraph()
void SMyBlueprint::OnOpenGraph () private
Callbacks for commands.
OnOpenGraphInNewTab()
void SMyBlueprint::OnOpenGraphInNewTab () private
OnPasteFunction()
void SMyBlueprint::OnPasteFunction () private
OnPasteGeneric()
void SMyBlueprint::OnPasteGeneric ()
Callbacks for Paste Commands.
OnPasteLocalVariable()
void SMyBlueprint::OnPasteLocalVariable () private
OnPasteMacro()
void SMyBlueprint::OnPasteMacro () private
OnPasteVariable()
void SMyBlueprint::OnPasteVariable () private
OnRequestRenameOnActionNode()
void SMyBlueprint::OnRequestRenameOnActionNode ()
Initiates a rename on the selected action node, if possible.
OnResetItemFilter()
void SMyBlueprint::OnResetItemFilter ()
Called to reset the search filter.
OnToggleAlwaysShowInterfacesInOverrides()
void SMyBlueprint::OnToggleAlwaysShowInterfacesInOverrides () private
Support functions for view options for bAlwaysShowInterfacesInOverrides blueprint editor setting.
OnToggleShowAccessSpecifier()
void SMyBlueprint::OnToggleShowAccessSpecifier () private
Support functions for view options for bShowAccessSpecifier blueprint editor setting.
OnToggleShowEmptySections()
void SMyBlueprint::OnToggleShowEmptySections () private
Support functions for view options for Show Empty Sections.
OnToggleShowInheritedVariables()
void SMyBlueprint::OnToggleShowInheritedVariables () private
OnToggleShowParentClassInOverrides()
void SMyBlueprint::OnToggleShowParentClassInOverrides () private
Support functions for view options for bShowParentClassInOverrides blueprint editor setting.
OnToggleShowReplicatedVariablesOnly()
void SMyBlueprint::OnToggleShowReplicatedVariablesOnly () private
Support functions for view options for Show Replicated Variables only.
OpenGraph()
void SMyBlueprint::OpenGraph (FDocumentTracker::EOpenDocumentCause InCause, bool bOpenExternalGraphInNewEditor = false) private
Helper function to open the selected graph.
Refresh()
void SMyBlueprint::Refresh ()
Refreshes the graph action menu.
ResetLastPinType()
void SMyBlueprint::ResetLastPinType ()
SelectionAsBlueprintVariable()
FEdGraphSchemaAction_BlueprintVariableBase * SMyBlueprint::SelectionAsBlueprintVariable () const
Accessor for getting the current selection as a K2 blueprint base variable.
SelectionAsDelegate()
FEdGraphSchemaAction_K2Delegate * SMyBlueprint::SelectionAsDelegate () const
Accessor for getting the current selection as a K2 delegate.
SelectionAsEnum()
FEdGraphSchemaAction_K2Enum * SMyBlueprint::SelectionAsEnum () const
Accessor for getting the current selection as a K2 enum.
SelectionAsEvent()
FEdGraphSchemaAction_K2Event * SMyBlueprint::SelectionAsEvent () const
Accessor for getting the current selection as a K2 event.
SelectionAsGraph()
FEdGraphSchemaAction_K2Graph * SMyBlueprint::SelectionAsGraph () const
Accessor for getting the current selection as a K2 graph.
SelectionAsInputAction()
FEdGraphSchemaAction_K2InputAction * SMyBlueprint::SelectionAsInputAction () const
Accessor for getting the current selection as a K2 Input Action.
SelectionAsLocalVar()
FEdGraphSchemaAction_K2LocalVar * SMyBlueprint::SelectionAsLocalVar () const
Accessor for getting the current selection as a K2 local var.
SelectionAsStruct()
FEdGraphSchemaAction_K2Struct * SMyBlueprint::SelectionAsStruct () const
Accessor for getting the current selection as a K2 enum.
SelectionAsVar()
FEdGraphSchemaAction_K2Var * SMyBlueprint::SelectionAsVar () const
Accessor for getting the current selection as a K2 var.
SelectionHasContextMenu()
bool SMyBlueprint::SelectionHasContextMenu () const private
Checks if the selected action has context menu.
SelectionIsCategory()
bool SMyBlueprint::SelectionIsCategory () const
Accessor for determining if the current selection is a category.
SelectItemByName()
void SMyBlueprint::SelectItemByName (const FName & ItemName, ESelectInfo::Type SelectInfo = ESelectInfo::Direct, int32 SectionId = INDEX_NONE, bool bIsCategory = false)
Selects an item by name in either the main graph action menu or the local one.
References INDEX_NONE.
SetFocusedGraph()
void SMyBlueprint::SetFocusedGraph (UEdGraph * InEdGraph) inline
Definition at line 105 of file SMyBlueprint.h.
References EdGraph.
SetInspector()
void SMyBlueprint::SetInspector (TSharedPtr< SKismetInspector > InInspector) inline
Definition at line 94 of file SMyBlueprint.h.
References Inspector, and SetInspector().
Referenced by SetInspector().
ShowUserVarsOnly()
bool SMyBlueprint::ShowUserVarsOnly () const inline
Gets whether we are showing user variables only or not.
Definition at line 147 of file SMyBlueprint.h.
References IsShowingInheritedVariables().
SLATE_BEGIN_ARGS()
SMyBlueprint::SLATE_BEGIN_ARGS (SMyBlueprint) inline
Definition at line 88 of file SMyBlueprint.h.
SLATE_END_ARGS()
SMyBlueprint::SLATE_END_ARGS () const &
Tick()
virtual void SMyBlueprint::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
UpdateNodeCreation()
void SMyBlueprint::UpdateNodeCreation () private
Update Node Create Analytic.
Field Documentation
Blueprint
UBlueprint* SMyBlueprint::Blueprint private
The blueprint being displayed:
Definition at line 367 of file SMyBlueprint.h.
Referenced by GetBlueprintObj(), and OnActionSelectedHelper().
BlueprintEditorPtr
TWeakPtr<FBlueprintEditor> SMyBlueprint::BlueprintEditorPtr private
Pointer back to the blueprint editor that owns us.
Definition at line 339 of file SMyBlueprint.h.
Referenced by GetBlueprintEditor().
bNeedsRefresh
bool SMyBlueprint::bNeedsRefresh private
Flag to indicate whether or not we need to refresh the panel.
Definition at line 376 of file SMyBlueprint.h.
bShowReplicatedVariablesOnly
bool SMyBlueprint::bShowReplicatedVariablesOnly private
If set we'll show only replicated variables (local to a particular blueprint view).
Definition at line 379 of file SMyBlueprint.h.
CommandList
TSharedPtr<FUICommandList> SMyBlueprint::CommandList private
List of UI Commands for this scope.
Definition at line 336 of file SMyBlueprint.h.
EdGraph
UEdGraph* SMyBlueprint::EdGraph private
The Ed Graph being displayed:
Definition at line 370 of file SMyBlueprint.h.
Referenced by AddEventForFunctionGraph(), GetChildEvents(), GetChildGraphs(), and SetFocusedGraph().
EnumsAddedToBlueprint
TArray<TWeakObjectPtr<UUserDefinedEnum> > SMyBlueprint::EnumsAddedToBlueprint private
Enums created from 'blueprint' level.
Definition at line 358 of file SMyBlueprint.h.
FilterBox
TSharedPtr< SSearchBox > SMyBlueprint::FilterBox private
The filter box that handles filtering for both graph action menus.
Definition at line 361 of file SMyBlueprint.h.
FunctionSectionButton
TSharedPtr<SComboButton> SMyBlueprint::FunctionSectionButton private
The +Function button in the function section.
Definition at line 345 of file SMyBlueprint.h.
GraphActionMenu
TSharedPtr<class SGraphActionMenu> SMyBlueprint::GraphActionMenu private
Graph Action Menu for displaying all our variables and functions.
Definition at line 342 of file SMyBlueprint.h.
ImplementedFunctionCache
TSet<FName> SMyBlueprint::ImplementedFunctionCache private
When we refresh the list of functions we cache off the implemented ones to ask questions for overridable functions.
Definition at line 351 of file SMyBlueprint.h.
InBlueprint
TWeakPtr<FBlueprintEditor> const UBlueprint* SMyBlueprint::InBlueprint = nullptr)
Definition at line 91 of file SMyBlueprint.h.
InBlueprintEditor
TWeakPtr<FBlueprintEditor> SMyBlueprint::InBlueprintEditor
Definition at line 91 of file SMyBlueprint.h.
Referenced by OnActionSelectedHelper().
Inspector
TWeakPtr<SKismetInspector> SMyBlueprint::Inspector private
The Kismet Inspector used to display properties:
Definition at line 373 of file SMyBlueprint.h.
Referenced by OnActionSelectedHelper(), and SetInspector().
LastFunctionPinType
FEdGraphPinType SMyBlueprint::LastFunctionPinType private
Definition at line 355 of file SMyBlueprint.h.
Referenced by GetLastFunctionPinTypeUsed().
LastPinType
FEdGraphPinType SMyBlueprint::LastPinType private
The last pin type used (including the function editor last pin type)
Definition at line 354 of file SMyBlueprint.h.
Referenced by GetLastPinTypeUsed().
OverridableFunctionActions
TArray< TSharedPtr<FEdGraphSchemaAction_K2Graph> > SMyBlueprint::OverridableFunctionActions private
When we rebuild the view of members, we cache (but don't display) any overridable functions for user in popup menus.
Definition at line 348 of file SMyBlueprint.h.
StructsAddedToBlueprint
TArray<TWeakObjectPtr<UUserDefinedStruct> > SMyBlueprint::StructsAddedToBlueprint private
Enums created from 'blueprint' level.
Definition at line 364 of file SMyBlueprint.h.
The documentation for this class was generated from the following file:
SMyBlueprint.h