Unreal Engine 5.6 C++ API: UParticleModuleLocationDirect Class Reference
UParticleModuleLocationDirect Class Reference
#include "ParticleModuleLocationDirect.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() struct FRawDistributionVector Location
The location of the particle at a give time.
void InitializeDefaults ()
Initializes the default values for this property.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual uint32 RequiredBytes (UParticleModuleTypeDataBase *TypeData) override
virtual void Spawn (const FSpawnContext &Context) override
virtual void Update (const FUpdateContext &Context) override
UPROPERTY () struct FRawDistributionVector Direction
Currently unused.
UPROPERTY () struct FRawDistributionVector LocationOffset
An offset to apply to the position retrieved from the Location calculation.
UPROPERTY () struct FRawDistributionVector ScaleFactor
Scales the velocity of the object at a given point in the time-line.
Detailed Description
Definition at line 22 of file ParticleModuleLocationDirect.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UParticleModuleLocationDirect::GENERATED_UCLASS_BODY () private
The location of the particle at a give time.
Retrieved using the particle RelativeTime. IMPORTANT: the particle location is set to this value, thereby over-writing any previous module impacts.
References Category, Location, and UPROPERTY().
InitializeDefaults()
void UParticleModuleLocationDirect::InitializeDefaults () private
Initializes the default values for this property.
References InitializeDefaults().
Referenced by InitializeDefaults().
PostEditChangeProperty()
virtual void UParticleModuleLocationDirect::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UParticleModuleLocationDirect::PostInitProperties () override private virtual
RequiredBytes()
virtual uint32 UParticleModuleLocationDirect::RequiredBytes (UParticleModuleTypeDataBase * TypeData) override private virtual
Spawn()
virtual void UParticleModuleLocationDirect::Spawn (const FSpawnContext & Context) override private virtual
Update()
virtual void UParticleModuleLocationDirect::Update (const FUpdateContext & Context) override private virtual
UPROPERTY() [1/3]
UParticleModuleLocationDirect::UPROPERTY () private
Currently unused.
References Category, Location, and UPROPERTY().
UPROPERTY() [2/3]
UParticleModuleLocationDirect::UPROPERTY () private
An offset to apply to the position retrieved from the Location calculation.
The offset is retrieved using the EmitterTime. The offset will remain constant over the life of the particle.
References Category, Location, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/3]
UParticleModuleLocationDirect::UPROPERTY () private
Scales the velocity of the object at a given point in the time-line.
References Category, Location, and UPROPERTY().
The documentation for this class was generated from the following file:
ParticleModuleLocationDirect.h