Unreal Engine 5.6 C++ API: UE::Geometry::FSphereGenerator Class Reference
UE::Geometry::FSphereGenerator Class Reference
Generate a sphere mesh, with UVs wrapped cylindrically.
#include "SphereGenerator.h"
Public Member Functions
FMeshShapeGenerator & Generate () override
Generate the mesh.
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Data Fields
bool bPolygroupPerQuad = false
If true, each quad of box gets a separate polygroup.
int NumPhi = 3
int NumTheta = 3
double Radius = 1
Radius.
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Private Types
using CornerIndices = FVector3i
Private Member Functions
void GenerateUVVertices ()
void GenerateVertices ()
void OutputEquatorialTriangles ()
void OutputPolarTriangles ()
void OutputTriangle (int TriIdx, int PolyIdx, CornerIndices Corners, CornerIndices UVCorners)
Static Private Member Functions
static FVector3d SphericalToCartesian (double r, double theta, double phi)
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Detailed Description
Generate a sphere mesh, with UVs wrapped cylindrically.
Definition at line 17 of file SphereGenerator.h.
Member Typedef Documentation
CornerIndices
using UE::Geometry::FSphereGenerator::CornerIndices = FVector3i private
Definition at line 107 of file SphereGenerator.h.
Member Function Documentation
Generate()
FMeshShapeGenerator & UE::Geometry::FSphereGenerator::Generate () inline override virtual
Generate the mesh.
Implements UE::Geometry::FMeshShapeGenerator.
Definition at line 197 of file SphereGenerator.h.
References GenerateUVVertices(), GenerateVertices(), FMath::Max, NumPhi, NumTheta, OutputEquatorialTriangles(), OutputPolarTriangles(), and UE::Geometry::FMeshShapeGenerator::SetBufferSizes().
GenerateUVVertices()
void UE::Geometry::FSphereGenerator::GenerateUVVertices () inline private
Definition at line 73 of file SphereGenerator.h.
References float, NumPhi, NumTheta, UE::Geometry::FMeshShapeGenerator::UVParentVertex, and UE::Geometry::FMeshShapeGenerator::UVs.
Referenced by Generate().
GenerateVertices()
void UE::Geometry::FSphereGenerator::GenerateVertices () inline private
Definition at line 40 of file SphereGenerator.h.
References UE::Geometry::Normal, UE::Geometry::FMeshShapeGenerator::NormalParentVertex, UE::Geometry::FMeshShapeGenerator::Normals, NumPhi, NumTheta, TMathUtilConstants< double >::Pi, Radius, UE::Geometry::FMeshShapeGenerator::SetVertex(), SphericalToCartesian(), TMathUtilConstants< double >::TwoPi, UE::Math::TVector< double >::UnitZ(), UE::Math::TVector< float >::UnitZ(), and UE::Geometry::FMeshShapeGenerator::Vertices.
Referenced by Generate().
OutputEquatorialTriangles()
void UE::Geometry::FSphereGenerator::OutputEquatorialTriangles () inline private
Definition at line 116 of file SphereGenerator.h.
References bPolygroupPerQuad, NumPhi, NumTheta, and OutputTriangle().
Referenced by Generate().
OutputPolarTriangles()
void UE::Geometry::FSphereGenerator::OutputPolarTriangles () inline private
Definition at line 156 of file SphereGenerator.h.
References bPolygroupPerQuad, NumPhi, NumTheta, and OutputTriangle().
Referenced by Generate().
OutputTriangle()
void UE::Geometry::FSphereGenerator::OutputTriangle (int TriIdx, int PolyIdx, CornerIndices Corners, CornerIndices UVCorners) inline private
Definition at line 108 of file SphereGenerator.h.
References UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTrianglePolygon(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by OutputEquatorialTriangles(), and OutputPolarTriangles().
SphericalToCartesian()
FVector3d UE::Geometry::FSphereGenerator::SphericalToCartesian (double r, double theta, double phi) inline static private
Definition at line 30 of file SphereGenerator.h.
Referenced by GenerateVertices().
Field Documentation
bPolygroupPerQuad
bool UE::Geometry::FSphereGenerator::bPolygroupPerQuad = false
If true, each quad of box gets a separate polygroup.
Definition at line 27 of file SphereGenerator.h.
Referenced by OutputEquatorialTriangles(), and OutputPolarTriangles().
NumPhi
int UE::Geometry::FSphereGenerator::NumPhi = 3
Definition at line 23 of file SphereGenerator.h.
Referenced by Generate(), GenerateUVVertices(), GenerateVertices(), OutputEquatorialTriangles(), and OutputPolarTriangles().
NumTheta
int UE::Geometry::FSphereGenerator::NumTheta = 3
Definition at line 24 of file SphereGenerator.h.
Referenced by Generate(), GenerateUVVertices(), GenerateVertices(), OutputEquatorialTriangles(), and OutputPolarTriangles().
Radius
double UE::Geometry::FSphereGenerator::Radius = 1
Radius.
Definition at line 21 of file SphereGenerator.h.
Referenced by GenerateVertices().
The documentation for this class was generated from the following file:
SphereGenerator.h