Unreal Engine 5.6 C++ API: UE_NETWORK_PHYSICS Namespace Reference
UE_NETWORK_PHYSICS Namespace Reference
Functions
int32 bFutureInputs ()
static FConditionalAutoConsoleRegister bFutureInputsAuto (TEXT("np2.FutureInputs"),(int32) 0, TEXT("Enable FutureInputs feature"))
int32 bInputDecay ()
static FConditionalAutoConsoleRegister bInputDecayAuto (TEXT("np2.InputDecay"),(int32) 0, TEXT("Enable Input Decay Feature"))
float DampYawVelocityK ()
static FConditionalAutoConsoleRegister DampYawVelocityKAuto (TEXT("np2.Mock.DampYawVelocityK"),(float) 2.f, TEXT("Coefficient for damping angular velocity in yaw direction only. This is only enabled when auto target yaw is disabled."))
float DragK ()
static FConditionalAutoConsoleRegister DragKAuto (TEXT("np2.Mock.DragK"),(float) 1.12f, TEXT("Drag Coefficient (higher=more drag)"))
float InputDecayRate ()
static FConditionalAutoConsoleRegister InputDecayRateAuto (TEXT("np2.InputDecayRate"),(float) 0.99f, TEXT("Rate of input decay"))
float JumpForce ()
static FConditionalAutoConsoleRegister JumpForceAuto (TEXT("np2.Mock.JumpForce"),(float) 70, TEXT("Per-Frame force to apply while jumping."))
int32 JumpFrameDuration ()
static FConditionalAutoConsoleRegister JumpFrameDurationAuto (TEXT("np2.Mock.JumpFrameDuration"),(int32) 4, TEXT("How many frames to apply jump force for"))
int32 JumpFudgeFrames ()
static FConditionalAutoConsoleRegister JumpFudgeFramesAuto (TEXT("np2.Mock.JumpFudgeFrames"),(int32) 10, TEXT("How many frames after being in air do we still allow a jump to begin"))
int32 JumpHack ()
static FConditionalAutoConsoleRegister JumpHackAuto (TEXT("np2.Mock.JumpHack"),(int32) 0, TEXT("Make jump not rely on trace which currently causes non determinism"))
int32 JumpMisPredict ()
static FConditionalAutoConsoleRegister JumpMisPredictAuto (TEXT("np2.Mock.JumpMisPredict"),(int32) 0, TEXT("Make jump do random impulse which will cause a misprediction"))
float MaxAngularVelocity ()
static FConditionalAutoConsoleRegister MaxAngularVelocityAuto (TEXT("np2.Mock.MaxAngularVelocity"),(float) 30.f, TEXT("Limits how fast character can possibly rotate."))
int32 MockDebug ()
static FConditionalAutoConsoleRegister MockDebugAuto (TEXT("np2.Mock.MockDebug"),(int32) 0, TEXT("Enabled spammy log debugging of mock physics object state"))
int32 MockImpulse ()
static FConditionalAutoConsoleRegister MockImpulseAuto (TEXT("np2.Mock.BallImpulse"),(int32) 1, TEXT("Make jump not rely on trace which currently causes non determinism"))
float MockImpulseX ()
static FConditionalAutoConsoleRegister MockImpulseXAuto (TEXT("np2.Mock.BallImpulse.X"),(float) 500.0f, TEXT("X magnitude"))
float MockImpulseZ ()
static FConditionalAutoConsoleRegister MockImpulseZAuto (TEXT("np2.Mock.BallImpulse.Z"),(float) 300.0f, TEXT("Z magnitude"))
float MovementK ()
static FConditionalAutoConsoleRegister MovementKAuto (TEXT("np2.Mock.MovementK"),(float) 1.25, TEXT("Movement Coefficient (higher=faster movement)"))
float RotationK ()
static FConditionalAutoConsoleRegister RotationKAuto (TEXT("np2.Mock.RotationK"),(float) 1.25, TEXT("Rotation Coefficient (higher=faster movement)"))
void SetbFutureInputs (int32 _V)
void SetbInputDecay (int32 _V)
void SetDampYawVelocityK (float _V)
void SetDragK (float _V)
void SetInputDecayRate (float _V)
void SetJumpForce (float _V)
void SetJumpFrameDuration (int32 _V)
void SetJumpFudgeFrames (int32 _V)
void SetJumpHack (int32 _V)
void SetJumpMisPredict (int32 _V)
void SetMaxAngularVelocity (float _V)
void SetMockDebug (int32 _V)
void SetMockImpulse (int32 _V)
void SetMockImpulseX (float _V)
void SetMockImpulseZ (float _V)
void SetMovementK (float _V)
void SetRotationK (float _V)
void SetTurnDampK (float _V)
void SetTurnK (float _V)
float TurnDampK ()
static FConditionalAutoConsoleRegister TurnDampKAuto (TEXT("np2.Mock.TurnDampK"),(float) 100.f, TEXT("Coefficient for damping portion of turn. Higher=more damping but too higher will lead to instability."))
float TurnK ()
static FConditionalAutoConsoleRegister TurnKAuto (TEXT("np2.Mock.TurnK"),(float) 100000000.f, TEXT("Coefficient for automatic turning (higher=quicker turning)"))
Function Documentation
bFutureInputs()
int32 UE_NETWORK_PHYSICS::bFutureInputs () inline
Definition at line 108 of file NetworkPredictionCVars.h.
References bFutureInputs().
Referenced by bFutureInputs().
bFutureInputsAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::bFutureInputsAuto (TEXT("np2.FutureInputs") , (int32) 0, TEXT("Enable FutureInputs feature")) static
bInputDecay()
int32 UE_NETWORK_PHYSICS::bInputDecay () inline
Definition at line 110 of file NetworkPredictionCVars.h.
References bInputDecay().
Referenced by bInputDecay().
bInputDecayAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::bInputDecayAuto (TEXT("np2.InputDecay") , (int32) 0, TEXT("Enable Input Decay Feature")) static
DampYawVelocityK()
float UE_NETWORK_PHYSICS::DampYawVelocityK () inline
Definition at line 119 of file NetworkPredictionCVars.h.
References DampYawVelocityK(), and NETSIM_DEVCVAR_SHIPCONST_FLOAT.
Referenced by DampYawVelocityK().
DampYawVelocityKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::DampYawVelocityKAuto (TEXT("np2.Mock.DampYawVelocityK") , (float) 2. f, TEXT("Coefficient for damping angular velocity in yaw direction only. This is only enabled when auto target yaw is disabled.")) static
DragK()
float UE_NETWORK_PHYSICS::DragK () inline
Definition at line 113 of file NetworkPredictionCVars.h.
References DragK().
Referenced by DragK().
DragKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::DragKAuto (TEXT("np2.Mock.DragK") , (float) 1. 12f, TEXT("Drag Coefficient (higher=more drag)")) static
InputDecayRate()
float UE_NETWORK_PHYSICS::InputDecayRate () inline
Definition at line 111 of file NetworkPredictionCVars.h.
References InputDecayRate().
Referenced by InputDecayRate().
InputDecayRateAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::InputDecayRateAuto (TEXT("np2.InputDecayRate") , (float) 0. 99f, TEXT("Rate of input decay")) static
JumpForce()
float UE_NETWORK_PHYSICS::JumpForce () inline
Definition at line 121 of file NetworkPredictionCVars.h.
References JumpForce(), and NETSIM_DEVCVAR_SHIPCONST_FLOAT.
Referenced by JumpForce().
JumpForceAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::JumpForceAuto (TEXT("np2.Mock.JumpForce") , (float) 70, TEXT("Per-Frame force to apply while jumping.")) static
JumpFrameDuration()
int32 UE_NETWORK_PHYSICS::JumpFrameDuration () inline
Definition at line 122 of file NetworkPredictionCVars.h.
References JumpFrameDuration(), and NETSIM_DEVCVAR_SHIPCONST_INT.
Referenced by JumpFrameDuration().
JumpFrameDurationAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::JumpFrameDurationAuto (TEXT("np2.Mock.JumpFrameDuration") , (int32) 4, TEXT("How many frames to apply jump force for")) static
JumpFudgeFrames()
int32 UE_NETWORK_PHYSICS::JumpFudgeFrames () inline
Definition at line 123 of file NetworkPredictionCVars.h.
References JumpFudgeFrames(), and NETSIM_DEVCVAR_SHIPCONST_INT.
Referenced by JumpFudgeFrames().
JumpFudgeFramesAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::JumpFudgeFramesAuto (TEXT("np2.Mock.JumpFudgeFrames") , (int32) 10, TEXT("How many frames after being in air do we still allow a jump to begin")) static
JumpHack()
int32 UE_NETWORK_PHYSICS::JumpHack () inline
Definition at line 124 of file NetworkPredictionCVars.h.
References JumpHack(), and NETSIM_DEVCVAR_SHIPCONST_INT.
Referenced by JumpHack().
JumpHackAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::JumpHackAuto (TEXT("np2.Mock.JumpHack") , (int32) 0, TEXT("Make jump not rely on trace which currently causes non determinism")) static
JumpMisPredict()
int32 UE_NETWORK_PHYSICS::JumpMisPredict () inline
Definition at line 125 of file NetworkPredictionCVars.h.
References JumpMisPredict(), and NETSIM_DEVCVAR_SHIPCONST_INT.
Referenced by JumpMisPredict().
JumpMisPredictAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::JumpMisPredictAuto (TEXT("np2.Mock.JumpMisPredict") , (int32) 0, TEXT("Make jump do random impulse which will cause a misprediction")) static
MaxAngularVelocity()
float UE_NETWORK_PHYSICS::MaxAngularVelocity () inline
Definition at line 114 of file NetworkPredictionCVars.h.
References MaxAngularVelocity().
Referenced by MaxAngularVelocity().
MaxAngularVelocityAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MaxAngularVelocityAuto (TEXT("np2.Mock.MaxAngularVelocity") , (float) 30. f, TEXT("Limits how fast character can possibly rotate.")) static
MockDebug()
int32 UE_NETWORK_PHYSICS::MockDebug () inline
Definition at line 106 of file NetworkPredictionCVars.h.
References MockDebug().
Referenced by MockDebug().
MockDebugAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MockDebugAuto (TEXT("np2.Mock.MockDebug") , (int32) 0, TEXT("Enabled spammy log debugging of mock physics object state")) static
MockImpulse()
int32 UE_NETWORK_PHYSICS::MockImpulse () inline
Definition at line 127 of file NetworkPredictionCVars.h.
References MockImpulse(), and NETSIM_DEVCVAR_SHIPCONST_INT.
Referenced by MockImpulse().
MockImpulseAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MockImpulseAuto (TEXT("np2.Mock.BallImpulse") , (int32) 1, TEXT("Make jump not rely on trace which currently causes non determinism")) static
MockImpulseX()
float UE_NETWORK_PHYSICS::MockImpulseX () inline
Definition at line 128 of file NetworkPredictionCVars.h.
References MockImpulseX(), and NETSIM_DEVCVAR_SHIPCONST_FLOAT.
Referenced by MockImpulseX().
MockImpulseXAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MockImpulseXAuto (TEXT("np2.Mock.BallImpulse.X") , (float) 500. 0f, TEXT("X magnitude")) static
MockImpulseZ()
float UE_NETWORK_PHYSICS::MockImpulseZ () inline
Definition at line 129 of file NetworkPredictionCVars.h.
References MockImpulseZ(), and NETSIM_DEVCVAR_SHIPCONST_FLOAT.
Referenced by MockImpulseZ().
MockImpulseZAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MockImpulseZAuto (TEXT("np2.Mock.BallImpulse.Z") , (float) 300. 0f, TEXT("Z magnitude")) static
MovementK()
float UE_NETWORK_PHYSICS::MovementK () inline
Definition at line 115 of file NetworkPredictionCVars.h.
References MovementK(), and NETSIM_DEVCVAR_SHIPCONST_FLOAT.
Referenced by MovementK().
MovementKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::MovementKAuto (TEXT("np2.Mock.MovementK") , (float) 1. 25, TEXT("Movement Coefficient (higher=faster movement)")) static
RotationK()
float UE_NETWORK_PHYSICS::RotationK () inline
Definition at line 116 of file NetworkPredictionCVars.h.
References NETSIM_DEVCVAR_SHIPCONST_FLOAT, and RotationK().
Referenced by RotationK().
RotationKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::RotationKAuto (TEXT("np2.Mock.RotationK") , (float) 1. 25, TEXT("Rotation Coefficient (higher=faster movement)")) static
SetbFutureInputs()
void UE_NETWORK_PHYSICS::SetbFutureInputs (int32 _V) inline
Definition at line 108 of file NetworkPredictionCVars.h.
SetbInputDecay()
void UE_NETWORK_PHYSICS::SetbInputDecay (int32 _V) inline
Definition at line 110 of file NetworkPredictionCVars.h.
SetDampYawVelocityK()
void UE_NETWORK_PHYSICS::SetDampYawVelocityK (float _V) inline
Definition at line 119 of file NetworkPredictionCVars.h.
SetDragK()
void UE_NETWORK_PHYSICS::SetDragK (float _V) inline
Definition at line 113 of file NetworkPredictionCVars.h.
SetInputDecayRate()
void UE_NETWORK_PHYSICS::SetInputDecayRate (float _V) inline
Definition at line 111 of file NetworkPredictionCVars.h.
SetJumpForce()
void UE_NETWORK_PHYSICS::SetJumpForce (float _V) inline
Definition at line 121 of file NetworkPredictionCVars.h.
SetJumpFrameDuration()
void UE_NETWORK_PHYSICS::SetJumpFrameDuration (int32 _V) inline
Definition at line 122 of file NetworkPredictionCVars.h.
SetJumpFudgeFrames()
void UE_NETWORK_PHYSICS::SetJumpFudgeFrames (int32 _V) inline
Definition at line 123 of file NetworkPredictionCVars.h.
SetJumpHack()
void UE_NETWORK_PHYSICS::SetJumpHack (int32 _V) inline
Definition at line 124 of file NetworkPredictionCVars.h.
SetJumpMisPredict()
void UE_NETWORK_PHYSICS::SetJumpMisPredict (int32 _V) inline
Definition at line 125 of file NetworkPredictionCVars.h.
SetMaxAngularVelocity()
void UE_NETWORK_PHYSICS::SetMaxAngularVelocity (float _V) inline
Definition at line 114 of file NetworkPredictionCVars.h.
SetMockDebug()
void UE_NETWORK_PHYSICS::SetMockDebug (int32 _V) inline
Definition at line 106 of file NetworkPredictionCVars.h.
SetMockImpulse()
void UE_NETWORK_PHYSICS::SetMockImpulse (int32 _V) inline
Definition at line 127 of file NetworkPredictionCVars.h.
SetMockImpulseX()
void UE_NETWORK_PHYSICS::SetMockImpulseX (float _V) inline
Definition at line 128 of file NetworkPredictionCVars.h.
SetMockImpulseZ()
void UE_NETWORK_PHYSICS::SetMockImpulseZ (float _V) inline
Definition at line 129 of file NetworkPredictionCVars.h.
SetMovementK()
void UE_NETWORK_PHYSICS::SetMovementK (float _V) inline
Definition at line 115 of file NetworkPredictionCVars.h.
SetRotationK()
void UE_NETWORK_PHYSICS::SetRotationK (float _V) inline
Definition at line 116 of file NetworkPredictionCVars.h.
SetTurnDampK()
void UE_NETWORK_PHYSICS::SetTurnDampK (float _V) inline
Definition at line 118 of file NetworkPredictionCVars.h.
References NETSIM_DEVCVAR_SHIPCONST_FLOAT, and TurnDampK().
SetTurnK()
void UE_NETWORK_PHYSICS::SetTurnK (float _V) inline
Definition at line 117 of file NetworkPredictionCVars.h.
References NETSIM_DEVCVAR_SHIPCONST_FLOAT, and TurnK().
TurnDampK()
float UE_NETWORK_PHYSICS::TurnDampK () inline
Definition at line 118 of file NetworkPredictionCVars.h.
Referenced by SetTurnDampK().
TurnDampKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::TurnDampKAuto (TEXT("np2.Mock.TurnDampK") , (float) 100. f, TEXT("Coefficient for damping portion of turn. Higher=more damping but too higher will lead to instability.")) static
TurnK()
float UE_NETWORK_PHYSICS::TurnK () inline
Definition at line 117 of file NetworkPredictionCVars.h.
Referenced by SetTurnK().
TurnKAuto()
FConditionalAutoConsoleRegister UE_NETWORK_PHYSICS::TurnKAuto (TEXT("np2.Mock.TurnK") , (float) 100000000. f, TEXT("Coefficient for automatic turning (higher=quicker turning)")) static