Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitPtr Struct Reference
UE::AnimNext::FTraitPtr Struct Reference
Trait Pointer A trait pointer represents a shared pointer to allocated instance data.
#include "TraitPtr.h"
Public Member Functions
constexpr FTraitPtr () noexcept=default
ANIMNEXTANIMGRAPH_API FTraitPtr (const FTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API FTraitPtr (const FWeakTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API FTraitPtr (FNodeInstance *InNodeInstance, uint32 InTraitIndex)
ANIMNEXTANIMGRAPH_API FTraitPtr (FTraitPtr &&TraitPtr) noexcept
ANIMNEXTANIMGRAPH_API ~FTraitPtr ()
ANIMNEXTANIMGRAPH_API FNodeInstance * GetNodeInstance () const noexcept
ANIMNEXTANIMGRAPH_API constexpr uint32 GetTraitIndex () const noexcept
ANIMNEXTANIMGRAPH_API constexpr bool IsValid () const noexcept
ANIMNEXTANIMGRAPH_API constexpr bool IsWeak () const noexcept
bool operator!= (const FTraitPtr &RHS) const
bool operator!= (const FWeakTraitPtr &RHS) const
ANIMNEXTANIMGRAPH_API FTraitPtr & operator= (const FTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API FTraitPtr & operator= (const FWeakTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API FTraitPtr & operator= (FTraitPtr &&TraitPtr) noexcept
bool operator== (const FTraitPtr &RHS) const
bool operator== (const FWeakTraitPtr &RHS) const
ANIMNEXTANIMGRAPH_API void Reset ()
Private Types
enum EFlags : uintptr_t { IS_WEAK_BIT = 0x01 , FLAGS_MASK = 0x03 }
Private Member Functions
ANIMNEXTANIMGRAPH_API FTraitPtr (FNodeInstance *InNodeInstance, EFlags InFlags, uint32 InTraitIndex)
Private Attributes
uintptr_t PackedPointerAndFlags = 0
uint32 TraitIndex = 0
Friends
struct FExecutionContext
struct FWeakTraitPtr
Detailed Description
Trait Pointer A trait pointer represents a shared pointer to allocated instance data.
It manages reference counting. It points to a FTraitInstanceData or FNodeInstance when resolved.
A node pointer can also be weak, meaning that it does not update reference counting. Note that weak pointers will point to garbage if the trait instance is destroyed.
Weak trait pointers should be used carefully!
See also
FNodeInstance, FTraitInstanceData
Definition at line 27 of file TraitPtr.h.
Member Enumeration Documentation
EFlags
enum UE::AnimNext::FTraitPtr::EFlags : uintptr_t private
Enumerator
IS_WEAK_BIT
FLAGS_MASK
Definition at line 67 of file TraitPtr.h.
Constructor & Destructor Documentation
FTraitPtr() [1/6]
UE::AnimNext::FTraitPtr::FTraitPtr () constexpr default noexcept
Referenced by FTraitPtr(), FTraitPtr(), FTraitPtr(), FTraitPtr(), ~FTraitPtr(), operator!=(), operator=(), operator=(), operator=(), and operator==().
FTraitPtr() [2/6]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::FTraitPtr (FNodeInstance * InNodeInstance, uint32 InTraitIndex)
References FTraitPtr(), and UE_API.
FTraitPtr() [3/6]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::FTraitPtr (const FTraitPtr & TraitPtr)
References FTraitPtr(), and UE_API.
FTraitPtr() [4/6]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::FTraitPtr (const FWeakTraitPtr & TraitPtr) explicit
References FTraitPtr(), FWeakTraitPtr, and UE_API.
FTraitPtr() [5/6]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::FTraitPtr (FTraitPtr && TraitPtr) noexcept
References FTraitPtr(), and UE_API.
~FTraitPtr()
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::~FTraitPtr ()
References FTraitPtr(), and UE_API.
FTraitPtr() [6/6]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitPtr::FTraitPtr (FNodeInstance * InNodeInstance, EFlags InFlags, uint32 InTraitIndex) private
References UE_API.
Member Function Documentation
GetNodeInstance()
ANIMNEXTANIMGRAPH_API FNodeInstance * UE::AnimNext::FTraitPtr::GetNodeInstance () const inline noexcept
Definition at line 45 of file TraitPtr.h.
References FLAGS_MASK, GetNodeInstance(), PackedPointerAndFlags, and UE_API.
Referenced by GetNodeInstance(), operator!=(), operator!=(), UE::AnimNext::FWeakTraitPtr::operator!=(), operator==(), operator==(), and UE::AnimNext::FWeakTraitPtr::operator==().
GetTraitIndex()
ANIMNEXTANIMGRAPH_API constexpr uint32 UE::AnimNext::FTraitPtr::GetTraitIndex () const inline constexpr noexcept
Definition at line 48 of file TraitPtr.h.
References TraitIndex, and UE_API.
Referenced by UE::AnimNext::FWeakTraitPtr::operator!=(), and UE::AnimNext::FWeakTraitPtr::operator==().
IsValid()
ANIMNEXTANIMGRAPH_API constexpr bool UE::AnimNext::FTraitPtr::IsValid () const inline constexpr noexcept
Definition at line 51 of file TraitPtr.h.
References PackedPointerAndFlags, and UE_API.
IsWeak()
ANIMNEXTANIMGRAPH_API constexpr bool UE::AnimNext::FTraitPtr::IsWeak () const inline constexpr noexcept
Definition at line 54 of file TraitPtr.h.
References IS_WEAK_BIT, PackedPointerAndFlags, and UE_API.
operator!=() [1/2]
bool UE::AnimNext::FTraitPtr::operator!= (const FTraitPtr & RHS) const inline
Definition at line 61 of file TraitPtr.h.
References FTraitPtr(), GetNodeInstance(), and TraitIndex.
operator!=() [2/2]
bool UE::AnimNext::FTraitPtr::operator!= (const FWeakTraitPtr & RHS) const inline
Definition at line 136 of file TraitPtr.h.
References FWeakTraitPtr, GetNodeInstance(), UE::AnimNext::FWeakTraitPtr::GetNodeInstance(), UE::AnimNext::FWeakTraitPtr::GetTraitIndex(), and TraitIndex.
operator=() [1/3]
ANIMNEXTANIMGRAPH_API FTraitPtr & UE::AnimNext::FTraitPtr::operator= (const FTraitPtr & TraitPtr)
References FTraitPtr(), and UE_API.
operator=() [2/3]
ANIMNEXTANIMGRAPH_API FTraitPtr & UE::AnimNext::FTraitPtr::operator= (const FWeakTraitPtr & TraitPtr)
References FTraitPtr(), FWeakTraitPtr, and UE_API.
operator=() [3/3]
ANIMNEXTANIMGRAPH_API FTraitPtr & UE::AnimNext::FTraitPtr::operator= (FTraitPtr && TraitPtr) noexcept
References FTraitPtr(), and UE_API.
operator==() [1/2]
bool UE::AnimNext::FTraitPtr::operator== (const FTraitPtr & RHS) const inline
Definition at line 60 of file TraitPtr.h.
References FTraitPtr(), GetNodeInstance(), and TraitIndex.
operator==() [2/2]
bool UE::AnimNext::FTraitPtr::operator== (const FWeakTraitPtr & RHS) const inline
Definition at line 135 of file TraitPtr.h.
References FWeakTraitPtr, GetNodeInstance(), UE::AnimNext::FWeakTraitPtr::GetNodeInstance(), UE::AnimNext::FWeakTraitPtr::GetTraitIndex(), and TraitIndex.
Reset()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitPtr::Reset ()
References UE_API.
Friends And Related Symbol Documentation
FExecutionContext
friend struct FExecutionContext friend
Definition at line 85 of file TraitPtr.h.
References FExecutionContext.
Referenced by FExecutionContext.
FWeakTraitPtr
friend struct FWeakTraitPtr friend
Definition at line 84 of file TraitPtr.h.
References FWeakTraitPtr.
Referenced by FTraitPtr(), FWeakTraitPtr, operator!=(), operator=(), and operator==().
Field Documentation
PackedPointerAndFlags
uintptr_t UE::AnimNext::FTraitPtr::PackedPointerAndFlags = 0 private
Definition at line 81 of file TraitPtr.h.
Referenced by GetNodeInstance(), IsValid(), and IsWeak().
TraitIndex
uint32 UE::AnimNext::FTraitPtr::TraitIndex = 0 private
Definition at line 82 of file TraitPtr.h.
Referenced by GetTraitIndex(), operator!=(), operator!=(), operator==(), and operator==().
The documentation for this struct was generated from the following file:
TraitPtr.h