Unreal Engine 5.6 C++ API: IStreamingGenerationContext::FActorSetContainerInstance Struct Reference
IStreamingGenerationContext::FActorSetContainerInstance Struct Reference
An actor set container represents the list of actor sets in an actor container, e.g.
#include "WorldPartitionStreamingGenerationContext.h"
Public Member Functions
FActorSetContainerInstance ()
FActorSetContainerInstance (const FActorSetContainerInstance &)=delete
FActorSetContainerInstance & operator= (const FActorSetContainerInstance &)=delete
Data Fields
const FStreamingGenerationActorDescViewMap * ActorDescViewMap
TArray< TUniquePtr< FActorSet > > ActorSets
const FStreamingGenerationContainerInstanceCollection * ContainerInstanceCollection
const TArray< const FWorldDataLayersActorDesc * > * DataLayerResolvers
Detailed Description
An actor set container represents the list of actor sets in an actor container, e.g.
a level instance.
Definition at line 56 of file WorldPartitionStreamingGenerationContext.h.
Constructor & Destructor Documentation
FActorSetContainerInstance() [1/2]
IStreamingGenerationContext::FActorSetContainerInstance::FActorSetContainerInstance () inline
Definition at line 58 of file WorldPartitionStreamingGenerationContext.h.
References ActorDescViewMap, ContainerInstanceCollection, and DataLayerResolvers.
Referenced by FActorSetContainerInstance(), and operator=().
FActorSetContainerInstance() [2/2]
IStreamingGenerationContext::FActorSetContainerInstance::FActorSetContainerInstance (const FActorSetContainerInstance &) delete
References FActorSetContainerInstance().
Member Function Documentation
operator=()
FActorSetContainerInstance & IStreamingGenerationContext::FActorSetContainerInstance::operator= (const FActorSetContainerInstance &) delete
References FActorSetContainerInstance().
Field Documentation
ActorDescViewMap
const FStreamingGenerationActorDescViewMap* IStreamingGenerationContext::FActorSetContainerInstance::ActorDescViewMap
Definition at line 68 of file WorldPartitionStreamingGenerationContext.h.
Referenced by FActorSetContainerInstance().
ActorSets
TArray<TUniquePtr<FActorSet> > IStreamingGenerationContext::FActorSetContainerInstance::ActorSets
Definition at line 71 of file WorldPartitionStreamingGenerationContext.h.
ContainerInstanceCollection
const FStreamingGenerationContainerInstanceCollection* IStreamingGenerationContext::FActorSetContainerInstance::ContainerInstanceCollection
Definition at line 70 of file WorldPartitionStreamingGenerationContext.h.
Referenced by FActorSetContainerInstance().
DataLayerResolvers
const TArray<const FWorldDataLayersActorDesc*>* IStreamingGenerationContext::FActorSetContainerInstance::DataLayerResolvers
Definition at line 69 of file WorldPartitionStreamingGenerationContext.h.
Referenced by FActorSetContainerInstance().
The documentation for this struct was generated from the following file:
WorldPartitionStreamingGenerationContext.h