Unreal Engine 5.6 C++ API: IWorldPartitionCookPackageGenerator Class Reference
IWorldPartitionCookPackageGenerator Class Reference abstract
#include "WorldPartitionCookPackageGenerator.h"
Public Member Functions
virtual ~IWorldPartitionCookPackageGenerator ()=default
virtual bool GatherPackagesToCook (IWorldPartitionCookPackageContext &CookContext)=0
virtual UWorldPartitionRuntimeCell * GetCellForPackage (const FWorldPartitionCookPackage &PackageToCook) const =0
virtual bool PopulateGeneratedPackageForCook (IWorldPartitionCookPackageContext &CookContext, const FWorldPartitionCookPackage &InPackageToCook, TArray< UPackage * > &OutModifiedPackages)=0
virtual bool PopulateGeneratorPackageForCook (IWorldPartitionCookPackageContext &CookContext, const TArray< FWorldPartitionCookPackage * > &InPackagesToCook, TArray< UPackage * > &OutModifiedPackages)=0
virtual bool PrepareGeneratorPackageForCook (IWorldPartitionCookPackageContext &CookContext, TArray< UPackage * > &OutModifiedPackages)
Detailed Description
Definition at line 12 of file WorldPartitionCookPackageGenerator.h.
Constructor & Destructor Documentation
~IWorldPartitionCookPackageGenerator()
virtual IWorldPartitionCookPackageGenerator::~IWorldPartitionCookPackageGenerator () virtual default
Member Function Documentation
GatherPackagesToCook()
virtual bool IWorldPartitionCookPackageGenerator::GatherPackagesToCook (IWorldPartitionCookPackageContext & CookContext) pure virtual
Implemented in FContentBundleEditor.
Referenced by UCLASS().
GetCellForPackage()
virtual UWorldPartitionRuntimeCell * IWorldPartitionCookPackageGenerator::GetCellForPackage (const FWorldPartitionCookPackage & PackageToCook) const pure virtual
Implemented in FContentBundleEditor.
Referenced by UCLASS().
PopulateGeneratedPackageForCook()
virtual bool IWorldPartitionCookPackageGenerator::PopulateGeneratedPackageForCook (IWorldPartitionCookPackageContext & CookContext, const FWorldPartitionCookPackage & InPackageToCook, TArray< UPackage * > & OutModifiedPackages) pure virtual
Implemented in FContentBundleEditor.
Referenced by UCLASS().
PopulateGeneratorPackageForCook()
virtual bool IWorldPartitionCookPackageGenerator::PopulateGeneratorPackageForCook (IWorldPartitionCookPackageContext & CookContext, const TArray< FWorldPartitionCookPackage * > & InPackagesToCook, TArray< UPackage * > & OutModifiedPackages) pure virtual
Implemented in FContentBundleEditor.
Referenced by UCLASS().
PrepareGeneratorPackageForCook()
virtual bool IWorldPartitionCookPackageGenerator::PrepareGeneratorPackageForCook (IWorldPartitionCookPackageContext & CookContext, TArray< UPackage * > & OutModifiedPackages) inline virtual
Definition at line 19 of file WorldPartitionCookPackageGenerator.h.
Referenced by UCLASS().
The documentation for this class was generated from the following file:
WorldPartitionCookPackageGenerator.h