Unreal Engine 5.6 C++ API: UE::Geometry::TInterval1< RealType > Struct Template Reference
UE::Geometry::TInterval1< RealType > Struct Template Reference
#include "BoxTypes.h"
Public Member Functions
TInterval1 ()
TInterval1 (const RealType &Min, const RealType &Max)
RealType Center () const
RealType Clamp (RealType f) const
clamp Value f to interval [Min,Max]
void Contain (const RealType &V)
void Contain (const TInterval1< RealType > &O)
bool Contains (const TInterval1< RealType > &O) const
bool Contains (RealType D) const
RealType Dist (const TInterval1< RealType > &O) const
void Expand (RealType Radius)
RealType Extent () const
RealType GetT (RealType Value) const
Convert Value into (clamped) T Value in range [0,1].
RealType Interpolate (RealType T) const
interpolate between Min and Max using Value T in range [0,1]
TInterval1< RealType > IntersectionWith (const TInterval1< RealType > &O) const
bool IsEmpty () const
RealType Length () const
RealType MaxAbsExtrema () const
TInterval1 operator* (RealType f) const
TInterval1 operator+ (RealType f) const
TInterval1 operator- (RealType f) const
TInterval1 operator- (TInterval1 V) const
bool Overlaps (const TInterval1< RealType > &O) const
void Set (RealType A, RealType B)
void Set (TInterval1 O)
RealType SquaredDist (const TInterval1< RealType > &O) const
Static Public Member Functions
static TInterval1< RealType > Empty ()
static TInterval1< RealType > MakeFromUnordered (const RealType &A, const RealType &B)
Data Fields
RealType Max
RealType Min
Detailed Description
template<typename RealType>
struct UE::Geometry::TInterval1< RealType >
Definition at line 18 of file BoxTypes.h.
Constructor & Destructor Documentation
TInterval1() [1/2]
template<typename RealType> UE::Geometry::TInterval1< RealType >::TInterval1 () inline
Definition at line 23 of file BoxTypes.h.
Referenced by UE::Geometry::TInterval1< float >::Empty(), UE::Geometry::TInterval1< float >::IntersectionWith(), UE::Geometry::TInterval1< float >::operator*(), UE::Geometry::TInterval1< float >::operator+(), UE::Geometry::TInterval1< float >::operator-(), and UE::Geometry::TInterval1< float >::operator-().
TInterval1() [2/2]
template<typename RealType> UE::Geometry::TInterval1< RealType >::TInterval1 (const RealType & Min, const RealType & Max) inline
Definition at line 28 of file BoxTypes.h.
Member Function Documentation
Center()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Center () const inline
Definition at line 49 of file BoxTypes.h.
Referenced by UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
Clamp()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Clamp (RealType f) const inline
clamp Value f to interval [Min,Max]
Definition at line 150 of file BoxTypes.h.
Contain() [1/2]
template<typename RealType> void UE::Geometry::TInterval1< RealType >::Contain (const RealType & V) inline
Definition at line 68 of file BoxTypes.h.
Referenced by UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
Contain() [2/2]
template<typename RealType> void UE::Geometry::TInterval1< RealType >::Contain (const TInterval1< RealType > & O) inline
Definition at line 80 of file BoxTypes.h.
Contains() [1/2]
template<typename RealType> bool UE::Geometry::TInterval1< RealType >::Contains (const TInterval1< RealType > & O) const inline
Definition at line 97 of file BoxTypes.h.
Contains() [2/2]
template<typename RealType> bool UE::Geometry::TInterval1< RealType >::Contains (RealType D) const inline
Definition at line 92 of file BoxTypes.h.
Referenced by UE::Geometry::TInterval1< float >::Contains().
Dist()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Dist (const TInterval1< RealType > & O) const inline
Definition at line 122 of file BoxTypes.h.
Empty()
template<typename RealType> TInterval1< RealType > UE::Geometry::TInterval1< RealType >::Empty () inline static
Definition at line 34 of file BoxTypes.h.
Referenced by UE::Geometry::TSampleSetStatistics< float >::Begin_FixedCount(), and UE::Geometry::TInterval1< float >::IntersectionWith().
Expand()
template<typename RealType> void UE::Geometry::TInterval1< RealType >::Expand (RealType Radius) inline
Definition at line 223 of file BoxTypes.h.
Extent()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Extent () const inline
Definition at line 54 of file BoxTypes.h.
GetT()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::GetT (RealType Value) const inline
Convert Value into (clamped) T Value in range [0,1].
Definition at line 166 of file BoxTypes.h.
Interpolate()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Interpolate (RealType T) const inline
interpolate between Min and Max using Value T in range [0,1]
Definition at line 158 of file BoxTypes.h.
IntersectionWith()
template<typename RealType> TInterval1< RealType > UE::Geometry::TInterval1< RealType >::IntersectionWith (const TInterval1< RealType > & O) const inline
Definition at line 138 of file BoxTypes.h.
IsEmpty()
template<typename RealType> bool UE::Geometry::TInterval1< RealType >::IsEmpty () const inline
Definition at line 218 of file BoxTypes.h.
Length()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Length () const inline
Definition at line 58 of file BoxTypes.h.
Referenced by UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
MakeFromUnordered()
template<typename RealType> TInterval1< RealType > UE::Geometry::TInterval1< RealType >::MakeFromUnordered (const RealType & A, const RealType & B) inline static
Definition at line 39 of file BoxTypes.h.
MaxAbsExtrema()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::MaxAbsExtrema () const inline
Definition at line 63 of file BoxTypes.h.
operator*()
template<typename RealType> TInterval1 UE::Geometry::TInterval1< RealType >::operator* (RealType f) const inline
Definition at line 213 of file BoxTypes.h.
operator+()
template<typename RealType> TInterval1 UE::Geometry::TInterval1< RealType >::operator+ (RealType f) const inline
Definition at line 203 of file BoxTypes.h.
operator-() [1/2]
template<typename RealType> TInterval1 UE::Geometry::TInterval1< RealType >::operator- (RealType f) const inline
Definition at line 208 of file BoxTypes.h.
operator-() [2/2]
template<typename RealType> TInterval1 UE::Geometry::TInterval1< RealType >::operator- (TInterval1< RealType > V) const inline
Definition at line 198 of file BoxTypes.h.
Overlaps()
template<typename RealType> bool UE::Geometry::TInterval1< RealType >::Overlaps (const TInterval1< RealType > & O) const inline
Definition at line 102 of file BoxTypes.h.
Set() [1/2]
template<typename RealType> void UE::Geometry::TInterval1< RealType >::Set (RealType A, RealType B) inline
Definition at line 192 of file BoxTypes.h.
Set() [2/2]
template<typename RealType> void UE::Geometry::TInterval1< RealType >::Set (TInterval1< RealType > O) inline
Definition at line 186 of file BoxTypes.h.
SquaredDist()
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::SquaredDist (const TInterval1< RealType > & O) const inline
Definition at line 107 of file BoxTypes.h.
Field Documentation
Max
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Max
Definition at line 21 of file BoxTypes.h.
Referenced by UE::Geometry::TInterval1< float >::Contain(), UE::Geometry::TInterval1< float >::Contains(), UE::Geometry::TInterval1< float >::Dist(), UE::Geometry::TInterval1< float >::IntersectionWith(), IntersectionUtil::LineSphereIntersection(), UE::Geometry::TInterval1< float >::operator-(), UE::Geometry::TInterval1< float >::Overlaps(), UE::Geometry::TInterval1< float >::Set(), and UE::Geometry::TInterval1< float >::SquaredDist().
Min
template<typename RealType> RealType UE::Geometry::TInterval1< RealType >::Min
Definition at line 20 of file BoxTypes.h.
Referenced by UE::Geometry::TInterval1< float >::Contain(), UE::Geometry::TInterval1< float >::Contains(), UE::Geometry::TInterval1< float >::Dist(), UE::Geometry::TDynamicVerticesOctree3< SourceType >::FindNearestHitVertex(), UE::Geometry::TInterval1< float >::IntersectionWith(), IntersectionUtil::LineSphereIntersection(), UE::Geometry::TInterval1< float >::operator-(), UE::Geometry::TInterval1< float >::Overlaps(), UE::Geometry::TInterval1< float >::Set(), and UE::Geometry::TInterval1< float >::SquaredDist().
The documentation for this struct was generated from the following file:
BoxTypes.h