Unreal Engine 5.6 C++ API: UBlueprintPlatformLibrary Class Reference
UBlueprintPlatformLibrary Class Reference
#include "BlueprintPlatformLibrary.h"
Public Member Functions
UFUNCTION () static 1 int32 ScheduleLocalNotificationAtTime(const FDateTime &FireDateTime
Schedule a local notification at a specific time, inLocalTime specifies the current local time or if UTC time should be used.
UFUNCTION () static 1 int32 ScheduleLocalNotificationBadgeAtTime(const FDateTime &FireDateTime
Schedule a local notification badge at a specific time, inLocalTime specifies the current local time or if UTC time should be used.
UFUNCTION () static 1 int32 ScheduleLocalNotificationFromNow(int32 inSecondsFromNow
Schedule a local notification to fire inSecondsFromNow from now.
UFUNCTION () static 1 void CancelLocalNotification(const FString &ActivationEvent)
Cancel a local notification given the ActivationEvent.
UFUNCTION () static 1 void CancelLocalNotificationById(int32 NotificationId)
Cancel a local notification given the ActivationEvent.
UFUNCTION () static 1 void ClearAllLocalNotifications()
Clear all pending local notifications.
UFUNCTION () static 1 void GetLaunchNotification(bool &NotificationLaunchedApp
Get the local notification that was used to launch the app.
UFUNCTION () static 1 void ScheduleLocalNotificationBadgeFromNow(int32 inSecondsFromNow
Schedule a local notification badge to fire inSecondsFromNow from now.
Data Fields
bool const FText const FText const FText & Action
const FText const FText const FText & Action
bool const FText const FText const FText const FString & ActivationEvent
const FText const FText const FText const FString & ActivationEvent
bool const FString & ActivationEvent
const FString & ActivationEvent
FString & ActivationEvent
bool const FText const FText & Body
const FText const FText & Body
FString int32 & FireDate
bool LocalTime
bool const FText & Title
const FText & Title
Private Member Functions
GENERATED_UCLASS_BODY () static 1 ILocalNotificationService *platformService
Static Private Member Functions
static EDeviceScreenOrientation ConvertToDeviceScreenOrientation (EScreenOrientation::Type ScreenOrientation)
static EScreenOrientation::Type ConvertToScreenOrientation (EDeviceScreenOrientation DeviceScreenOrientation)
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
Detailed Description
Definition at line 178 of file BlueprintPlatformLibrary.h.
Member Function Documentation
ConvertToDeviceScreenOrientation()
EDeviceScreenOrientation UBlueprintPlatformLibrary::ConvertToDeviceScreenOrientation (EScreenOrientation::Type ScreenOrientation) static private
References ConvertToDeviceScreenOrientation().
Referenced by ConvertToDeviceScreenOrientation().
ConvertToScreenOrientation()
EScreenOrientation::Type UBlueprintPlatformLibrary::ConvertToScreenOrientation (EDeviceScreenOrientation DeviceScreenOrientation) static private
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
Returns
An EDeviceScreenOrientation value. Returns the allowed orientation of the device. This is NOT the same as GetDeviceOrientation, which only returns Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight. The allowed orientation limits what orientation your device can have. So if you set the allowed orientation to LandscapeLeft, GetDeviceOrientation will only ever return LandscapeLeft. But if you set the allowed orientation to LandscapeSensor, you are actually restricting the allowed orientations to LandscapeLeft OR LandscapeRight (depending on the sensor), so GetDeviceOrientation might return LandscapeLeft OR LandscapeRight.
An EDeviceScreenOrientation value. Set the allowed orientation of the device.
References ConvertToScreenOrientation().
Referenced by ConvertToScreenOrientation().
GENERATED_UCLASS_BODY()
UBlueprintPlatformLibrary::GENERATED_UCLASS_BODY () private
UFUNCTION() [1/8]
UBlueprintPlatformLibrary::UFUNCTION () const &
Schedule a local notification at a specific time, inLocalTime specifies the current local time or if UTC time should be used.
Parameters
FireDateTime The time at which to fire the local notification
LocalTime If true the provided time is in the local timezone, if false it is in UTC
Title The title of the notification
Body The more detailed description of the notification
Action The text to be displayed on the slider controller
ActivationEvent A string that is passed in the delegate callback when the app is brought into the foreground from the user activating the notification
References Category, and UFUNCTION().
UFUNCTION() [2/8]
UBlueprintPlatformLibrary::UFUNCTION () const &
Schedule a local notification badge at a specific time, inLocalTime specifies the current local time or if UTC time should be used.
Parameters
FireDateTime The time at which to fire the local notification
LocalTime If true the provided time is in the local timezone, if false it is in UTC
ActivationEvent A string that is passed in the delegate callback when the app is brought into the foreground from the user activating the notification
References Category, and UFUNCTION().
UFUNCTION() [3/8]
UBlueprintPlatformLibrary::UFUNCTION ()
Schedule a local notification to fire inSecondsFromNow from now.
Parameters
inSecondsFromNow The seconds until the notification should fire
LocalTime If true the provided time is in the local timezone, if false it is in UTC
Title The title of the notification
Body The more detailed description of the notification
Action The text to be displayed on the slider controller
ActivationEvent A string that is passed in the delegate callback when the app is brought into the foreground from the user activating the notification
References Category, and UFUNCTION().
UFUNCTION() [4/8]
UBlueprintPlatformLibrary::UFUNCTION () const &
Cancel a local notification given the ActivationEvent.
Parameters
ActivationEvent The string passed into the Schedule call for the notification to be cancelled
References ActivationEvent, Category, and UFUNCTION().
UFUNCTION() [5/8]
UBlueprintPlatformLibrary::UFUNCTION ()
Cancel a local notification given the ActivationEvent.
Parameters
NotificationId The Id returned from one of the ScheduleLocalNotification* functions
References Category, and UFUNCTION().
UFUNCTION() [6/8]
UBlueprintPlatformLibrary::UFUNCTION ()
Clear all pending local notifications.
Typically this will be done before scheduling new notifications when going into the background
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [7/8]
UBlueprintPlatformLibrary::UFUNCTION () &
Get the local notification that was used to launch the app.
Parameters
NotificationLaunchedApp Return true if a notification was used to launch the app
ActivationEvent Returns the name of the ActivationEvent if a notification was used to launch the app
FireDate Returns the time the notification was activated
References Category, and UFUNCTION().
UFUNCTION() [8/8]
UBlueprintPlatformLibrary::UFUNCTION ()
Schedule a local notification badge to fire inSecondsFromNow from now.
Parameters
inSecondsFromNow The seconds until the notification should fire
ActivationEvent A string that is passed in the delegate callback when the app is brought into the foreground from the user activating the notification
References Category, and UFUNCTION().
Field Documentation
Action [1/2]
bool const FText const FText const FText& UBlueprintPlatformLibrary::Action
Definition at line 199 of file BlueprintPlatformLibrary.h.
Action [2/2]
const FText const FText const FText& UBlueprintPlatformLibrary::Action
Definition at line 210 of file BlueprintPlatformLibrary.h.
ActivationEvent [1/5]
bool const FText const FText const FText const FString& UBlueprintPlatformLibrary::ActivationEvent
Definition at line 199 of file BlueprintPlatformLibrary.h.
Referenced by UFUNCTION().
ActivationEvent [2/5]
const FText const FText const FText const FString& UBlueprintPlatformLibrary::ActivationEvent
Definition at line 210 of file BlueprintPlatformLibrary.h.
ActivationEvent [3/5]
bool const FString& UBlueprintPlatformLibrary::ActivationEvent
Definition at line 218 of file BlueprintPlatformLibrary.h.
ActivationEvent [4/5]
const FString& UBlueprintPlatformLibrary::ActivationEvent
Definition at line 225 of file BlueprintPlatformLibrary.h.
ActivationEvent [5/5]
FString& UBlueprintPlatformLibrary::ActivationEvent
Definition at line 245 of file BlueprintPlatformLibrary.h.
Body [1/2]
bool const FText const FText& UBlueprintPlatformLibrary::Body
Definition at line 199 of file BlueprintPlatformLibrary.h.
Body [2/2]
const FText const FText& UBlueprintPlatformLibrary::Body
Definition at line 210 of file BlueprintPlatformLibrary.h.
FireDate
FString int32& UBlueprintPlatformLibrary::FireDate
Definition at line 245 of file BlueprintPlatformLibrary.h.
LocalTime
bool UBlueprintPlatformLibrary::LocalTime
Definition at line 199 of file BlueprintPlatformLibrary.h.
Title [1/2]
bool const FText& UBlueprintPlatformLibrary::Title
Definition at line 199 of file BlueprintPlatformLibrary.h.
Title [2/2]
const FText& UBlueprintPlatformLibrary::Title
Definition at line 210 of file BlueprintPlatformLibrary.h.
The documentation for this class was generated from the following file:
BlueprintPlatformLibrary.h