Unreal Engine 5.6 C++ API: FRDGBufferSRVDesc Struct Reference
FRDGBufferSRVDesc Struct Reference final
#include "RenderGraphResources.h"
Public Member Functions
FRDGBufferSRVDesc ()=default
FRDGBufferSRVDesc (FRDGBufferRef InBuffer)
FRDGBufferSRVDesc (FRDGBufferRef InBuffer, EPixelFormat InFormat)
FRDGBufferSRVDesc (FRDGBufferRef InBuffer, FRHIRayTracingScene *InRayTracingScene, uint32 InStartOffsetBytes)
FRDGBufferSRVDesc (FRDGBufferRef InBuffer, uint32 InStartOffsetBytes, uint32 InNumElements)
bool operator!= (const FRDGBufferSRVDesc &Other) const
bool operator== (const FRDGBufferSRVDesc &Other) const
Data Fields
FRDGBufferRef Buffer = nullptr
Friends
uint32 GetTypeHash (const FRDGBufferSRVDesc &Desc)
Detailed Description
Definition at line 1120 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGBufferSRVDesc() [1/5]
FRDGBufferSRVDesc::FRDGBufferSRVDesc () default
Referenced by GetTypeHash, operator!=(), and operator==().
FRDGBufferSRVDesc() [2/5]
FRDGBufferSRVDesc::FRDGBufferSRVDesc (FRDGBufferRef InBuffer)
FRDGBufferSRVDesc() [3/5]
FRDGBufferSRVDesc::FRDGBufferSRVDesc (FRDGBufferRef InBuffer, EPixelFormat InFormat) inline
Definition at line 1127 of file RenderGraphResources.h.
References Buffer.
FRDGBufferSRVDesc() [4/5]
FRDGBufferSRVDesc::FRDGBufferSRVDesc (FRDGBufferRef InBuffer, uint32 InStartOffsetBytes, uint32 InNumElements) inline
Definition at line 1133 of file RenderGraphResources.h.
References Buffer.
FRDGBufferSRVDesc() [5/5]
FRDGBufferSRVDesc::FRDGBufferSRVDesc (FRDGBufferRef InBuffer, FRHIRayTracingScene * InRayTracingScene, uint32 InStartOffsetBytes) inline
Definition at line 1138 of file RenderGraphResources.h.
References Buffer.
Member Function Documentation
operator!=()
bool FRDGBufferSRVDesc::operator!= (const FRDGBufferSRVDesc & Other) const inline
Definition at line 1148 of file RenderGraphResources.h.
References FRDGBufferSRVDesc(), and Other.
operator==()
bool FRDGBufferSRVDesc::operator== (const FRDGBufferSRVDesc & Other) const inline
Definition at line 1143 of file RenderGraphResources.h.
References FRDGBufferSRVDesc(), Buffer, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRDGBufferSRVDesc & Desc) friend
Definition at line 1153 of file RenderGraphResources.h.
References FRDGBufferSRVDesc(), Buffer, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
Field Documentation
Buffer
FRDGBufferRef FRDGBufferSRVDesc::Buffer = nullptr
Definition at line 1158 of file RenderGraphResources.h.
Referenced by FRDGBufferSRVDesc(), FRDGBufferSRVDesc(), FRDGBufferSRVDesc(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
RenderGraphResources.h