Unreal Engine 5.6 C++ API: FQuartLatencyTracker Class Reference
FQuartLatencyTracker Class Reference
#include "QuartzQuantizationUtilities.h"
Public Member Functions
FQuartLatencyTracker ()
float GetLifetimeAverageLatency ()
float GetMaxLatency ()
float GetMinLatency ()
void PushLatencyTrackerResult (const double &InResult)
Private Member Functions
void DigestQueue ()
void PushSingleResult (const double &InResult)
Private Attributes
float LifetimeAverage { 0.f }
float Max { 0.0f }
float Min { 0.0f }
int64 NumEntries { 0 }
TQueue< float, EQueueMode::Mpsc > ResultQueue
Detailed Description
Definition at line 244 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
FQuartLatencyTracker()
FQuartLatencyTracker::FQuartLatencyTracker ()
Definition at line 82 of file QuartzQuantizationUtilities.cpp.
References float, Max, and Min.
Member Function Documentation
DigestQueue()
void FQuartLatencyTracker::DigestQueue () private
Definition at line 145 of file QuartzQuantizationUtilities.cpp.
References check, IsInGameThread(), PushSingleResult(), and ResultQueue.
Referenced by GetLifetimeAverageLatency(), GetMaxLatency(), GetMinLatency(), and PushLatencyTrackerResult().
GetLifetimeAverageLatency()
float FQuartLatencyTracker::GetLifetimeAverageLatency ()
Definition at line 100 of file QuartzQuantizationUtilities.cpp.
References DigestQueue(), IsInGameThread(), and LifetimeAverage.
GetMaxLatency()
float FQuartLatencyTracker::GetMaxLatency ()
Definition at line 120 of file QuartzQuantizationUtilities.cpp.
References DigestQueue(), IsInGameThread(), and Max.
GetMinLatency()
float FQuartLatencyTracker::GetMinLatency ()
Definition at line 110 of file QuartzQuantizationUtilities.cpp.
References DigestQueue(), IsInGameThread(), and Min.
PushLatencyTrackerResult()
void FQuartLatencyTracker::PushLatencyTrackerResult (const double & InResult)
Definition at line 88 of file QuartzQuantizationUtilities.cpp.
References DigestQueue(), IsInGameThread(), and ResultQueue.
PushSingleResult()
void FQuartLatencyTracker::PushSingleResult (const double & InResult) private
Definition at line 130 of file QuartzQuantizationUtilities.cpp.
References float, LifetimeAverage, FMath::Max, Max, FMath::Min, Min, and NumEntries.
Referenced by DigestQueue().
Field Documentation
LifetimeAverage
float FQuartLatencyTracker::LifetimeAverage { 0.f } private
Definition at line 266 of file QuartzQuantizationUtilities.h.
Referenced by GetLifetimeAverageLatency(), and PushSingleResult().
Max
float FQuartLatencyTracker::Max { 0.0f } private
Definition at line 270 of file QuartzQuantizationUtilities.h.
Referenced by FQuartLatencyTracker(), GetMaxLatency(), and PushSingleResult().
Min
float FQuartLatencyTracker::Min { 0.0f } private
Definition at line 268 of file QuartzQuantizationUtilities.h.
Referenced by FQuartLatencyTracker(), GetMinLatency(), and PushSingleResult().
NumEntries
int64 FQuartLatencyTracker::NumEntries { 0 } private
Definition at line 264 of file QuartzQuantizationUtilities.h.
Referenced by PushSingleResult().
ResultQueue
TQueue<float, EQueueMode::Mpsc> FQuartLatencyTracker::ResultQueue private
Definition at line 262 of file QuartzQuantizationUtilities.h.
Referenced by DigestQueue(), and PushLatencyTrackerResult().
The documentation for this class was generated from the following files:
QuartzQuantizationUtilities.h
QuartzQuantizationUtilities.cpp