Unreal Engine 5.6 C++ API: UE::UnifiedError::TErrorDetails< T > Class Template Reference
UE::UnifiedError::TErrorDetails< T > Class Template Reference
#include "UnifiedError.h"
Public Member Functions
TErrorDetails ()
TErrorDetails (T &&InErrorDetail)
TErrorDetails (T &&InErrorDetail, TRefCountPtr< const IErrorDetails > InInnerErrorDetails)
const T & GetErrorContext () const
virtual uint32 GetErrorDetailsTypeId () const
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
virtual void GetErrorProperties (const FError &Error, IErrorPropertyExtractor &OutProperties) const override
GetErrorProperties; by default pass through to the InnerErrorDetails.
const T & GetValue () const
virtual void SerializeForLog (FCbWriter &Writer) const override
Public Member Functions inherited from UE::UnifiedError::FDynamicErrorDetails
FDynamicErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails=nullptr)
virtual ~FDynamicErrorDetails ()
virtual const FAnsiStringView GetErrorDetailsTypeName () const override
virtual const FText GetErrorFormatString (const FError &Error) const override
GetErrorFormatString; Pass through to the InnerErrorDetails.
virtual TRefCountPtr< const IErrorDetails > GetInnerErrorDetails () const
GetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
virtual void SetInnerErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails)
SetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
virtual ~FRefCountedErrorDetails ()
virtual FReturnedRefCountValue AddRef () const final
virtual uint32 GetRefCount () const final
virtual uint32 Release () const final
Public Member Functions inherited from UE::UnifiedError::IErrorDetails
virtual ~IErrorDetails ()=default
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Static Public Member Functions
static IErrorDetails * Create ()
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Member Functions inherited from UE::UnifiedError::FDynamicErrorDetails
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Attributes
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(TErrorStructFeatures<T>::GetNameAsString(), TFunction<IErrorDetails * ()>([]() -> IErrorDetails* { return Create(); }))
Static Public Attributes inherited from UE::UnifiedError::FDynamicErrorDetails
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FDynamicErrorDetails"), nullptr)
Static Public Attributes inherited from UE::UnifiedError::FRefCountedErrorDetails
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FRefCountedErrorDetails"), nullptr)
Private Member Functions
FAnsiStringView GetTypeNameAsString () const
Private Attributes
T ErrorDetail
Friends
IErrorDetails * Create ()
Detailed Description
template<typename T>
class UE::UnifiedError::TErrorDetails< T >
Definition at line 310 of file UnifiedError.h.
Constructor & Destructor Documentation
TErrorDetails() [1/3]
template<typename T> UE::UnifiedError::TErrorDetails< T >::TErrorDetails () inline
Definition at line 313 of file UnifiedError.h.
Referenced by Create().
TErrorDetails() [2/3]
template<typename T> UE::UnifiedError::TErrorDetails< T >::TErrorDetails (T && InErrorDetail) inline
Definition at line 314 of file UnifiedError.h.
References ErrorDetail, and MoveTemp().
TErrorDetails() [3/3]
template<typename T> UE::UnifiedError::TErrorDetails< T >::TErrorDetails (T && InErrorDetail, TRefCountPtr< const IErrorDetails > InInnerErrorDetails) inline
Definition at line 318 of file UnifiedError.h.
References UE::UnifiedError::FDynamicErrorDetails::FDynamicErrorDetails(), ErrorDetail, and MoveTemp().
Member Function Documentation
Create()
template<typename T> IErrorDetails * UE::UnifiedError::TErrorDetails< T >::Create () inline static
Definition at line 324 of file UnifiedError.h.
References TErrorDetails().
GetErrorContext()
template<typename T> const T & UE::UnifiedError::TErrorDetails< T >::GetErrorContext () const inline
Definition at line 345 of file UnifiedError.h.
References ErrorDetail.
Referenced by UE::UnifiedError::FError::GetErrorContext().
GetErrorDetailsTypeId()
template<typename T> virtual uint32 UE::UnifiedError::TErrorDetails< T >::GetErrorDetailsTypeId () const inline virtual
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
Returns
Reimplemented from UE::UnifiedError::FDynamicErrorDetails.
Definition at line 333 of file UnifiedError.h.
References StaticGetErrorDetailsTypeId().
GetErrorProperties()
template<typename T> virtual void UE::UnifiedError::TErrorDetails< T >::GetErrorProperties (const FError & Error, IErrorPropertyExtractor & OutProperties) const inline override virtual
GetErrorProperties; by default pass through to the InnerErrorDetails.
It's expected FDynamicErrorDetails will be derived from and implement GetErrorProperties.
Parameters
Error
OutProperties
Reimplemented from UE::UnifiedError::FDynamicErrorDetails.
Definition at line 350 of file UnifiedError.h.
References UE::Error, ErrorDetail, GatherPropertiesForError(), and UE::UnifiedError::FDynamicErrorDetails::GetErrorProperties().
GetTypeNameAsString()
template<typename T> FAnsiStringView UE::UnifiedError::TErrorDetails< T >::GetTypeNameAsString () const inline private
Definition at line 340 of file UnifiedError.h.
References TErrorStructFeatures< T >::GetErrorDetailsTypeNameAsString().
GetValue()
template<typename T> const T & UE::UnifiedError::TErrorDetails< T >::GetValue () const inline
Definition at line 361 of file UnifiedError.h.
References ErrorDetail.
SerializeForLog()
template<typename T> virtual void UE::UnifiedError::TErrorDetails< T >::SerializeForLog (FCbWriter & Writer) const inline override virtual
Reimplemented from UE::UnifiedError::IErrorDetails.
Definition at line 356 of file UnifiedError.h.
References ErrorDetail, and SerializeForLog().
Referenced by SerializeForLog().
StaticGetErrorDetailsTypeId()
template<typename T> uint32 UE::UnifiedError::TErrorDetails< T >::StaticGetErrorDetailsTypeId () inline static
Definition at line 329 of file UnifiedError.h.
References StaticDetailsTypeId.
Referenced by GetErrorDetailsTypeId().
Friends And Related Symbol Documentation
Create
template<typename T> IErrorDetails * Create () friend
Field Documentation
ErrorDetail
template<typename T> T UE::UnifiedError::TErrorDetails< T >::ErrorDetail private
Definition at line 338 of file UnifiedError.h.
Referenced by TErrorDetails(), TErrorDetails(), GetErrorContext(), GetErrorProperties(), GetValue(), and SerializeForLog().
StaticDetailsTypeId
template<typename T> const uint32 UE::UnifiedError::TErrorDetails< T >::StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(TErrorStructFeatures<T>::GetNameAsString(), TFunction<IErrorDetails * ()>([]() -> IErrorDetails* { return Create(); })) inline static
Definition at line 328 of file UnifiedError.h.
Referenced by StaticGetErrorDetailsTypeId().
The documentation for this class was generated from the following file:
UnifiedError.h