Unreal Engine 5.6 C++ API: Set.h File Reference
Set.h File Reference
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/ContainerElementTypeCompatibility.h"
#include "Containers/SetUtilities.h"
#include "Containers/SparseArray.h"
#include "ContainersFwd.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/AssertionMacros.h"
#include "Misc/StructBuilder.h"
#include "Serialization/MemoryImageWriter.h"
#include "Serialization/StructuredArchive.h"
#include "Templates/Function.h"
#include "Templates/RetainedRef.h"
#include "Templates/Sorting.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include <initializer_list>
#include <type_traits>
Data Structures
class FScriptSet
struct FScriptSetLayout
struct TIsTSet< T >
Traits class which determines whether or not a type is a TSet.
struct TIsTSet< const TSet< ElementType, KeyFuncs, Allocator > >
struct TIsTSet< const volatile TSet< ElementType, KeyFuncs, Allocator > >
struct TIsTSet< TSet< ElementType, KeyFuncs, Allocator > >
struct TIsTSet< volatile TSet< ElementType, KeyFuncs, Allocator > >
struct TIsZeroConstructType< TScriptSet< AllocatorType, InDerivedType > >
class TScriptSet< Allocator, InDerivedType >
class TSet< InElementType, KeyFuncs, Allocator >
A set with an optional KeyFuncs parameters for customizing how the elements are compared and searched.
class TSet< InElementType, KeyFuncs, Allocator >::FElementCompareClass< PREDICATE_CLASS >
Extracts the element value from the set's element structure and passes it to the user provided comparison class.
class TSet< InElementType, KeyFuncs, Allocator >::TBaseIterator< bConst, bRangedFor >
The base type of whole set iterators.
class TSet< InElementType, KeyFuncs, Allocator >::TBaseKeyIterator< bConst >
The base type of whole set iterators.
class TSet< InElementType, KeyFuncs, Allocator >::TConstIterator
Used to iterate over the elements of a const TSet.
class TSet< InElementType, KeyFuncs, Allocator >::TConstKeyIterator
Used to iterate over the elements of a const TSet.
class TSet< InElementType, KeyFuncs, Allocator >::TIterator
Used to iterate over the elements of a TSet.
class TSet< InElementType, KeyFuncs, Allocator >::TKeyIterator
Used to iterate over the elements of a TSet.
class TSetElement< InElementType >
An element in the set.
class TSetElementBase< InElementType, bTypeLayout >
class TSetElementBase< InElementType, true >
struct TSetPrivateFriend
Namespaces
namespace Freeze
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Functions
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename ElementType, typename KeyFuncs, typename Allocator >),(TSet< ElementType, KeyFuncs, Allocator >))
template<typename ElementType, typename KeyFuncs, typename Allocator>
uint32 Freeze::IntrinsicAppendHash (const TSet< ElementType, KeyFuncs, Allocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename ElementType, typename KeyFuncs, typename Allocator>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TSet< ElementType, KeyFuncs, Allocator > &Object, void *OutDst)
template<typename ElementType, typename KeyFuncs, typename Allocator>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSet< ElementType, KeyFuncs, Allocator > &Object, const FTypeLayoutDesc &)
template<typename ElementType, typename KeyFuncs, typename Allocator>
bool LegacyCompareEqual (const TSet< ElementType, KeyFuncs, Allocator > &A, const TSet< ElementType, KeyFuncs, Allocator > &B)
template<typename ElementType, typename KeyFuncs, typename Allocator>
bool LegacyCompareNotEqual (const TSet< ElementType, KeyFuncs, Allocator > &A, const TSet< ElementType, KeyFuncs, Allocator > &B)
void UE::Core::Private::OnInvalidSetNum (unsigned long long NewNum)
template<typename ElementType, typename KeyFuncs, typename Allocator>
FArchive & operator<< (FArchive &Ar, TSet< ElementType, KeyFuncs, Allocator > &Set)
Serializer.
template<typename ElementType>
FORCEINLINE FArchive & operator<< (FArchive &Ar, TSetElement< ElementType > &Element)
Serializer.
template<typename ElementType, typename KeyFuncs, typename Allocator>
void operator<< (FStructuredArchive::FSlot &Ar, TSet< ElementType, KeyFuncs, Allocator > &Set)
Structured archive serializer.
template<typename ElementType>
FORCEINLINE void operator<< (FStructuredArchive::FSlot &Ar, TSetElement< ElementType > &Element)
Structured archive serializer.
template<typename RangeType>
TSet (RangeType &&) -> TSet< TElementType_T< RangeType > >
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename ElementType, typename KeyFuncs, typename Allocator >) , (TSet< ElementType, KeyFuncs, Allocator >))
LegacyCompareEqual()
template<typename ElementType, typename KeyFuncs, typename Allocator> bool LegacyCompareEqual (const TSet< ElementType, KeyFuncs, Allocator > & A, const TSet< ElementType, KeyFuncs, Allocator > & B) nodiscard
Definition at line 2208 of file Set.h.
References A, B, and TSetPrivateFriend::LegacyCompareEqual().
LegacyCompareNotEqual()
template<typename ElementType, typename KeyFuncs, typename Allocator> bool LegacyCompareNotEqual (const TSet< ElementType, KeyFuncs, Allocator > & A, const TSet< ElementType, KeyFuncs, Allocator > & B) nodiscard
Definition at line 2213 of file Set.h.
References A, B, and TSetPrivateFriend::LegacyCompareEqual().
operator<<() [1/4]
template<typename ElementType, typename KeyFuncs, typename Allocator> FArchive & operator<< (FArchive & Ar, TSet< ElementType, KeyFuncs, Allocator > & Set)
Serializer.
Definition at line 2194 of file Set.h.
References Ar, and TSetPrivateFriend::Serialize().
operator<<() [2/4]
template<typename ElementType> FORCEINLINE FArchive & operator<< (FArchive & Ar, TSetElement< ElementType > & Element)
Serializer.
Definition at line 2180 of file Set.h.
References Ar, FORCEINLINE, and TSetElementBase< InElementType, bTypeLayout >::Value.
operator<<() [3/4]
template<typename ElementType, typename KeyFuncs, typename Allocator> void operator<< (FStructuredArchive::FSlot & Ar, TSet< ElementType, KeyFuncs, Allocator > & Set)
Structured archive serializer.
Definition at line 2201 of file Set.h.
References Ar, and TSetPrivateFriend::SerializeStructured().
operator<<() [4/4]
template<typename ElementType> FORCEINLINE void operator<< (FStructuredArchive::FSlot & Ar, TSetElement< ElementType > & Element)
Structured archive serializer.
Definition at line 2187 of file Set.h.
References Ar, FORCEINLINE, and TSetElementBase< InElementType, bTypeLayout >::Value.
TSet()
template<typename RangeType> TSet (RangeType &&) -> TSet< TElementType_T< RangeType > >