Unreal Engine 5.6 C++ API: FCoreRedirectsContext Struct Reference
FCoreRedirectsContext Struct Reference
Stores state required for FCoreRedirects API.
#include "CoreRedirectsContext.h"
Data Structures
struct FRWLockWithExclusiveRecursion
This lock allows exclusive locking (WriteLock) and shared locking (ReadLock) Additionally, it permits limited types of recursion.
Public Types
enum class EFlags : uint32 {
None = 0 , DebugMode = 1 << 0 , ValidateAddedRedirects = 1 << 1 , UseRedirectionSummary = 1 << 2 ,
Default = ValidateAddedRedirects | UseRedirectionSummary
}
Public Member Functions
FCoreRedirectsContext ()
Creates a context with a debug context name.
FCoreRedirectsContext (const FCoreRedirectsContext &OtherContext)
Creates a context with a debug context name, and inherits the state from OtherContext.
TMap< FName, ECoreRedirectFlags > & GetConfigKeyMap ()
Map from config name to flag.
EFlags GetFlags () const
Gets the flags for the context.
FRedirectionSummary & GetRedirectionSummary ()
FCoreRedirects::FRedirectTypeMap & GetRedirectTypeMap ()
Map from name of thing being mapped to full list.
const bool HasValidated () const
True if we have done our initial validation.
void InitializeContext ()
Run initialization steps that are needed before any data can be stored from FCoreRedirects calls.
const bool IsInDebugMode () const
True if we are in debug mode that does extra validation.
const bool IsInitialized () const
Get whether this has been initialized.
FCoreRedirectsContext & operator= (const FCoreRedirectsContext &Other)
void SetFlags (EFlags Flags)
Sets the flags for the context.
Static Public Member Functions
static FCoreRedirectsContext & GetGlobalContext ()
static FCoreRedirectsContext & GetThreadContext ()
static void SetThreadContext (FCoreRedirectsContext &NewContext)
Private Member Functions
void SetHasValidated ()
Sets that we have done our initial validation.
Private Attributes
std::atomic< bool > bInitialized
bool bValidatedOnce
TMap< FName, ECoreRedirectFlags > ConfigKeyMap
std::atomic< EFlags > Flags
FRedirectionSummary RedirectionSummary
FCoreRedirects::FRedirectTypeMap RedirectTypeMap
FRWLockWithExclusiveRecursion RWLock
Lock to protect multithreaded access to the CoreRedirect system.
Friends
void FCoreRedirects::ValidateAllRedirects ()
struct FScopeCoreRedirectsReadLockedContext
struct FScopeCoreRedirectsWriteLockedContext
Detailed Description
Stores state required for FCoreRedirects API.
The context encapsulates the necessary state for the FCoreRedirects API to function. Changine the context can be used to change the set of CoreRedirects for the current thread without affecting other threads. It is up to the user to ensure contexts are shared or not between threads. By default a single global context is shared amoung all threads until a thread local context is set.
Definition at line 20 of file CoreRedirectsContext.h.
Member Enumeration Documentation
EFlags
enum class FCoreRedirectsContext::EFlags : uint32 strong
Enumerator
None
DebugMode
ValidateAddedRedirects
UseRedirectionSummary
Default
Definition at line 22 of file CoreRedirectsContext.h.
Constructor & Destructor Documentation
FCoreRedirectsContext() [1/2]
FCoreRedirectsContext::FCoreRedirectsContext ()
Creates a context with a debug context name.
References UE_API.
Referenced by FCoreRedirectsContext(), GetGlobalContext(), GetThreadContext(), operator=(), and SetThreadContext().
FCoreRedirectsContext() [2/2]
FCoreRedirectsContext::FCoreRedirectsContext (const FCoreRedirectsContext & OtherContext)
Creates a context with a debug context name, and inherits the state from OtherContext.
The state from OtherContext is copied into the new context
References FCoreRedirectsContext(), Flags, and UE_API.
Member Function Documentation
GetConfigKeyMap()
TMap< FName, ECoreRedirectFlags > & FCoreRedirectsContext::GetConfigKeyMap () inline
Map from config name to flag.
Definition at line 251 of file CoreRedirectsContext.h.
References ConfigKeyMap.
GetFlags()
FCoreRedirectsContext::EFlags FCoreRedirectsContext::GetFlags () const inline
Gets the flags for the context.
Definition at line 226 of file CoreRedirectsContext.h.
References Flags.
GetGlobalContext()
FCoreRedirectsContext & FCoreRedirectsContext::GetGlobalContext () static
References FCoreRedirectsContext(), and UE_API.
GetRedirectionSummary()
FRedirectionSummary & FCoreRedirectsContext::GetRedirectionSummary () inline
Definition at line 263 of file CoreRedirectsContext.h.
References RedirectionSummary.
GetRedirectTypeMap()
FCoreRedirects::FRedirectTypeMap & FCoreRedirectsContext::GetRedirectTypeMap () inline
Map from name of thing being mapped to full list.
List must be filtered further
Definition at line 257 of file CoreRedirectsContext.h.
References RedirectTypeMap.
GetThreadContext()
FCoreRedirectsContext & FCoreRedirectsContext::GetThreadContext () static
References FCoreRedirectsContext(), and UE_API.
HasValidated()
const bool FCoreRedirectsContext::HasValidated () const inline
True if we have done our initial validation.
After initial validation, each change to redirects will validate independently
Definition at line 239 of file CoreRedirectsContext.h.
References bValidatedOnce.
InitializeContext()
void FCoreRedirectsContext::InitializeContext ()
Run initialization steps that are needed before any data can be stored from FCoreRedirects calls.
References UE_API.
IsInDebugMode()
const bool FCoreRedirectsContext::IsInDebugMode () const inline
True if we are in debug mode that does extra validation.
Definition at line 220 of file CoreRedirectsContext.h.
References DebugMode, and Flags.
IsInitialized()
const bool FCoreRedirectsContext::IsInitialized () const inline
Get whether this has been initialized.
Definition at line 213 of file CoreRedirectsContext.h.
References bInitialized.
operator=()
FCoreRedirectsContext & FCoreRedirectsContext::operator= (const FCoreRedirectsContext & Other)
References FCoreRedirectsContext(), Other, and UE_API.
SetFlags()
void FCoreRedirectsContext::SetFlags (FCoreRedirectsContext::EFlags NewFlags) inline
Sets the flags for the context.
Definition at line 233 of file CoreRedirectsContext.h.
References Flags.
SetHasValidated()
void FCoreRedirectsContext::SetHasValidated () inline private
Sets that we have done our initial validation.
After initial validation, each change to redirects will validate independently
Definition at line 245 of file CoreRedirectsContext.h.
References bValidatedOnce.
SetThreadContext()
void FCoreRedirectsContext::SetThreadContext (FCoreRedirectsContext & NewContext) static
References FCoreRedirectsContext(), and UE_API.
Friends And Related Symbol Documentation
FCoreRedirects::ValidateAllRedirects
void FCoreRedirects::ValidateAllRedirects () friend
FScopeCoreRedirectsReadLockedContext
friend struct FScopeCoreRedirectsReadLockedContext friend
Definition at line 119 of file CoreRedirectsContext.h.
References FScopeCoreRedirectsReadLockedContext.
Referenced by FScopeCoreRedirectsReadLockedContext.
FScopeCoreRedirectsWriteLockedContext
friend struct FScopeCoreRedirectsWriteLockedContext friend
Definition at line 120 of file CoreRedirectsContext.h.
References FScopeCoreRedirectsWriteLockedContext.
Referenced by FScopeCoreRedirectsWriteLockedContext.
Field Documentation
bInitialized
std::atomic<bool> FCoreRedirectsContext::bInitialized private
Definition at line 123 of file CoreRedirectsContext.h.
Referenced by IsInitialized().
bValidatedOnce
bool FCoreRedirectsContext::bValidatedOnce private
Definition at line 125 of file CoreRedirectsContext.h.
Referenced by HasValidated(), and SetHasValidated().
ConfigKeyMap
TMap<FName, ECoreRedirectFlags> FCoreRedirectsContext::ConfigKeyMap private
Definition at line 126 of file CoreRedirectsContext.h.
Referenced by GetConfigKeyMap().
Flags
std::atomic<EFlags> FCoreRedirectsContext::Flags private
Definition at line 124 of file CoreRedirectsContext.h.
Referenced by FCoreRedirectsContext(), GetFlags(), IsInDebugMode(), and SetFlags().
RedirectionSummary
FRedirectionSummary FCoreRedirectsContext::RedirectionSummary private
Definition at line 132 of file CoreRedirectsContext.h.
Referenced by GetRedirectionSummary().
RedirectTypeMap
FCoreRedirects::FRedirectTypeMap FCoreRedirectsContext::RedirectTypeMap private
Definition at line 127 of file CoreRedirectsContext.h.
Referenced by GetRedirectTypeMap().
RWLock
FRWLockWithExclusiveRecursion FCoreRedirectsContext::RWLock private
Lock to protect multithreaded access to the CoreRedirect system.
Definition at line 129 of file CoreRedirectsContext.h.
The documentation for this struct was generated from the following file:
CoreRedirectsContext.h