Unreal Engine 5.6 C++ API: ToolSelectionUtil Namespace Reference
ToolSelectionUtil Namespace Reference
Utility functions for Tool implementations to use when doing selection.
Functions
UE_DEPRECATED(5.5, "AccumulateSelectionElements which takes a bMapFacesToEdges boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") MODELINGCOMPONENTS_API bool AccumulateSelectionElements(UE MODELINGCOMPONENTS_API bool AccumulateSelectionElements (UE::Geometry::FGeometrySelectionElements &Elements, const UE::Geometry::FGeometrySelection &Selection, const UE::Geometry::FDynamicMesh3 &SourceMesh, const UE::Geometry::FGroupTopology *Topology=nullptr, const FTransform *ApplyTransform=nullptr, const UE::Geometry::EEnumerateSelectionMapping Flags=UE::Geometry::EEnumerateSelectionMapping::Default)
Prefer AccumulateSelectionElements with Flags parameter.
void DebugRender (IToolsContextRenderAPI *RenderAPI, const UE::Geometry::FGeometrySelectionElements &Elements, float LineThickness, FLinearColor LineColor, float PointSize, FLinearColor PointColor, float DepthBias=0.f, FLinearColor FillColor=FLinearColor(1.0f, 0.0f, 0.0f))
MODELINGCOMPONENTS_API void DebugRenderGeometrySelectionElements (IToolsContextRenderAPI *RenderAPI, const UE::Geometry::FGeometrySelectionElements &Elements, bool bIsPreview=false)
Render the given Elements using FPrimitiveDrawInterface.
MODELINGCOMPONENTS_API void SetNewActorSelection (UInteractiveToolManager *ToolManager, AActor *Actor)
Change the active selection to the given Actor, via given ToolManager.
MODELINGCOMPONENTS_API void SetNewActorSelection (UInteractiveToolManager *ToolManager, const TArray< AActor * > &Actors)
Change the active selection to the given Actors, via given ToolManager.
Detailed Description
Utility functions for Tool implementations to use when doing selection.
Function Documentation
AccumulateSelectionElements()
UE_DEPRECATED(5.5, "AccumulateSelectionElements which takes a bMapFacesToEdges boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") MODELINGCOMPONENTS_API bool AccumulateSelectionElements(UE MODELINGCOMPONENTS_API bool ToolSelectionUtil::AccumulateSelectionElements (UE::Geometry::FGeometrySelectionElements & Elements, const UE::Geometry::FGeometrySelection & Selection, const UE::Geometry::FDynamicMesh3 & SourceMesh, const UE::Geometry::FGroupTopology * Topology = nullptr, const FTransform * ApplyTransform = nullptr, const UE::Geometry::EEnumerateSelectionMapping Flags = UE::Geometry::EEnumerateSelectionMapping::Default)
Prefer AccumulateSelectionElements with Flags parameter.
Add the geometry selection elements corresponding to the given Selection to Elements. This function does not reset Elements before adding elements. If the Selection has Polygroup topology then use the given Topology to accumulate elements if it isn't null, otherwise compute a FGroupTopology from SourceMesh.TriangleGroups and use that to accumulate elements. If the Selection has Triangle topology then the Topology argument is ignored. Return false if there was an error and true otherwise
References AccumulateSelectionElements(), Default, Flags, and Geometry.
Referenced by AccumulateSelectionElements(), and SetNewActorSelection().
DebugRender()
void ToolSelectionUtil::DebugRender (IToolsContextRenderAPI * RenderAPI, const UE::Geometry::FGeometrySelectionElements & Elements, float LineThickness, FLinearColor LineColor, float PointSize, FLinearColor PointColor, float DepthBias = 0.f, FLinearColor FillColor = FLinearColor(1.0f, 0.0f, 0.0f))
References DebugRender(), and Geometry.
Referenced by DebugRender().
DebugRenderGeometrySelectionElements()
MODELINGCOMPONENTS_API void ToolSelectionUtil::DebugRenderGeometrySelectionElements (IToolsContextRenderAPI * RenderAPI, const UE::Geometry::FGeometrySelectionElements & Elements, bool bIsPreview = false)
Render the given Elements using FPrimitiveDrawInterface.
References DebugRenderGeometrySelectionElements(), and Geometry.
Referenced by DebugRenderGeometrySelectionElements().
SetNewActorSelection() [1/2]
MODELINGCOMPONENTS_API void ToolSelectionUtil::SetNewActorSelection (UInteractiveToolManager * ToolManager, AActor * Actor)
Change the active selection to the given Actor, via given ToolManager.
Replaces existing selection.
References Actor.
SetNewActorSelection() [2/2]
MODELINGCOMPONENTS_API void ToolSelectionUtil::SetNewActorSelection (UInteractiveToolManager * ToolManager, const TArray< AActor * > & Actors)
Change the active selection to the given Actors, via given ToolManager.
Replaces existing selection.
References AccumulateSelectionElements(), Actors, and Geometry.