Unreal Engine 5.6 C++ API: FActiveGameplayEffectIterator< ElementType, ContainerType > Class Template Reference
FActiveGameplayEffectIterator< ElementType, ContainerType > Class Template Reference
#include "ActiveGameplayEffectIterator.h"
Public Member Functions
FActiveGameplayEffectIterator (const ContainerType &InContainer, int32 StartIdx=0)
~FActiveGameplayEffectIterator ()
operator bool () const
ElementType & operator* () const
void operator++ ()
ElementType * operator-> () const
Private Member Functions
FORCEINLINE ElementType * AdvancePending (ElementType **Next)
void Next ()
void UpdateCurrent ()
Private Attributes
ContainerType & Container
ElementType * Current
int32 index
ElementType * Pending
Friends
bool operator!= (const FActiveGameplayEffectIterator &Lhs, const FActiveGameplayEffectIterator &Rhs)
bool operator== (const FActiveGameplayEffectIterator &Lhs, const FActiveGameplayEffectIterator &Rhs)
Detailed Description
template<typename ElementType, typename ContainerType>
class FActiveGameplayEffectIterator< ElementType, ContainerType >
Definition at line 22 of file ActiveGameplayEffectIterator.h.
Constructor & Destructor Documentation
FActiveGameplayEffectIterator()
template<typename ElementType, typename ContainerType> FActiveGameplayEffectIterator< ElementType, ContainerType >::FActiveGameplayEffectIterator (const ContainerType & InContainer, int32 StartIdx = 0) inline
Definition at line 26 of file ActiveGameplayEffectIterator.h.
References Container, Current, InContainer, index, Pending, and UpdateCurrent().
Referenced by operator!=, and operator==.
~FActiveGameplayEffectIterator()
template<typename ElementType, typename ContainerType> FActiveGameplayEffectIterator< ElementType, ContainerType >::~FActiveGameplayEffectIterator () inline
Definition at line 40 of file ActiveGameplayEffectIterator.h.
References Container.
Member Function Documentation
AdvancePending()
template<typename ElementType, typename ContainerType> FORCEINLINE ElementType * FActiveGameplayEffectIterator< ElementType, ContainerType >::AdvancePending (ElementType ** Next) inline private
Definition at line 80 of file ActiveGameplayEffectIterator.h.
References Container, FORCEINLINE, and Next().
Referenced by Next(), and UpdateCurrent().
Next()
template<typename ElementType, typename ContainerType> void FActiveGameplayEffectIterator< ElementType, ContainerType >::Next () inline private
Definition at line 86 of file ActiveGameplayEffectIterator.h.
References AdvancePending(), index, Pending, and UpdateCurrent().
Referenced by AdvancePending(), operator++(), and UpdateCurrent().
operator bool()
template<typename ElementType, typename ContainerType> FActiveGameplayEffectIterator< ElementType, ContainerType >::operator bool () const inline explicit
Definition at line 63 of file ActiveGameplayEffectIterator.h.
References Current.
operator*()
template<typename ElementType, typename ContainerType> ElementType & FActiveGameplayEffectIterator< ElementType, ContainerType >::operator* () const inline
Definition at line 51 of file ActiveGameplayEffectIterator.h.
References check, and Current.
operator++()
template<typename ElementType, typename ContainerType> void FActiveGameplayEffectIterator< ElementType, ContainerType >::operator++ () inline
Definition at line 46 of file ActiveGameplayEffectIterator.h.
References Next().
operator->()
template<typename ElementType, typename ContainerType> ElementType * FActiveGameplayEffectIterator< ElementType, ContainerType >::operator-> () const inline
Definition at line 57 of file ActiveGameplayEffectIterator.h.
References check, and Current.
UpdateCurrent()
template<typename ElementType, typename ContainerType> void FActiveGameplayEffectIterator< ElementType, ContainerType >::UpdateCurrent () inline private
Definition at line 103 of file ActiveGameplayEffectIterator.h.
References AdvancePending(), Container, Current, index, INDEX_NONE, Next(), and Pending.
Referenced by FActiveGameplayEffectIterator(), and Next().
Friends And Related Symbol Documentation
operator!=
template<typename ElementType, typename ContainerType> bool operator!= (const FActiveGameplayEffectIterator< ElementType, ContainerType > & Lhs, const FActiveGameplayEffectIterator< ElementType, ContainerType > & Rhs) friend
Definition at line 73 of file ActiveGameplayEffectIterator.h.
References FActiveGameplayEffectIterator(), and Current.
operator==
template<typename ElementType, typename ContainerType> bool operator== (const FActiveGameplayEffectIterator< ElementType, ContainerType > & Lhs, const FActiveGameplayEffectIterator< ElementType, ContainerType > & Rhs) friend
Definition at line 68 of file ActiveGameplayEffectIterator.h.
References FActiveGameplayEffectIterator(), and Current.
Field Documentation
Container
template<typename ElementType, typename ContainerType> ContainerType& FActiveGameplayEffectIterator< ElementType, ContainerType >::Container private
Definition at line 135 of file ActiveGameplayEffectIterator.h.
Referenced by FActiveGameplayEffectIterator(), ~FActiveGameplayEffectIterator(), AdvancePending(), and UpdateCurrent().
Current
template<typename ElementType, typename ContainerType> ElementType* FActiveGameplayEffectIterator< ElementType, ContainerType >::Current private
Definition at line 133 of file ActiveGameplayEffectIterator.h.
Referenced by FActiveGameplayEffectIterator(), operator bool(), operator!=, operator*(), operator->(), operator==, and UpdateCurrent().
index
template<typename ElementType, typename ContainerType> int32 FActiveGameplayEffectIterator< ElementType, ContainerType >::index private
Definition at line 132 of file ActiveGameplayEffectIterator.h.
Referenced by FActiveGameplayEffectIterator(), Next(), and UpdateCurrent().
Pending
template<typename ElementType, typename ContainerType> ElementType* FActiveGameplayEffectIterator< ElementType, ContainerType >::Pending private
Definition at line 134 of file ActiveGameplayEffectIterator.h.
Referenced by FActiveGameplayEffectIterator(), Next(), and UpdateCurrent().
The documentation for this class was generated from the following file:
ActiveGameplayEffectIterator.h