Unreal Engine 5.6 C++ API: FAssetEditorToolkit Class Reference
FAssetEditorToolkit Class Reference abstract
Base class for toolkits that are used for asset editing (abstract)
#include "AssetEditorToolkit.h"
Data Structures
class FGCEditingObjects
Report the references of the EditingObjects to the GC.
Public Member Functions
UNREALED_API FAssetEditorToolkit ()
Default constructor.
FAssetEditorToolkit (const FAssetEditorToolkit &)=delete
virtual UNREALED_API ~FAssetEditorToolkit ()
Virtual destructor, so that we can clean up our app when destroyed.
virtual void AddGraphEditorPinActionsToContextMenu (FToolMenuSection &InSection) const
UNREALED_API void AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
UNREALED_API void AddToolbarExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
virtual void AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder=INDEX_NONE)
virtual UNREALED_API bool CloseWindow (EAssetEditorCloseReason InCloseReason) override
virtual UNREALED_API TSharedPtr< SWidget > CreateMenuBar (const TSharedPtr< FTabManager > &InTabManager, const FName InMenuName, FToolMenuContext &InToolMenuContext)
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
UNREALED_API void FillDefaultAssetMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
UNREALED_API void FillDefaultFileMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultFileMenuOpenCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultHelpMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for the help menu.
virtual UNREALED_API void FocusWindow (UObject *ObjectToFocusOn=nullptr) override
UNREALED_API void GenerateToolbar ()
Makes a default asset editing toolbar.
virtual UNREALED_API TSharedPtr< FTabManager > GetAssociatedTabManager () override
virtual FText GetBaseToolkitName () const override=0
virtual UNREALED_API FName GetEditingAssetTypeName () const override
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API FName GetEditorName () const override
IAssetEditorInstance interface.
virtual UNREALED_API double GetLastActivationTime () override
virtual UNREALED_API const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual UNREALED_API EAssetOpenMethod GetOpenMethod () const override
UNREALED_API TSharedPtr< IToolkitHost > GetPreviousWorldCentricToolkitHost ()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions GetStatusBarCreationOptions () const
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
TSharedPtr< FTabManager > GetTabManager ()
virtual UNREALED_API FText GetTabSuffix () const override
virtual FName GetToolkitFName () const override=0
virtual UNREALED_API FText GetToolkitName () const override
virtual UNREALED_API FText GetToolkitToolTipText () const override
UNREALED_API FName GetToolMenuAppName () const
UNREALED_API FName GetToolMenuName () const
UNREALED_API FName GetToolMenuToolbarName () const
virtual UNREALED_API FName GetToolMenuToolbarName (FName &OutParentName) const
Get name used by tool menu.
virtual FString GetWorldCentricTabPrefix () const override=0
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
Initializes this asset editor.
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject *ObjectToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
virtual UNREALED_API void InitToolMenuContext (FToolMenuContext &MenuContext)
virtual UNREALED_API void InvokeTab (const FTabId &TabId) override
UNREALED_API bool IsActuallyAnAsset () const
True if this actually is editing an asset.
virtual UNREALED_API bool IsAssetEditor () const override
virtual bool IsPrimaryEditor () const override
virtual void OnToolkitHostingFinished (const TSharedRef< IToolkit > &Toolkit)
virtual void OnToolkitHostingStarted (const TSharedRef< IToolkit > &Toolkit)
virtual void OnViewportDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
React to a Drag&Drop events from the viewport.
virtual void OnViewportDragLeave (const FDragDropEvent &DragDropEvent)
virtual FReply OnViewportDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
FAssetEditorToolkit & operator= (const FAssetEditorToolkit &)=delete
virtual void PostRegenerateMenusAndToolbars ()
Called at the end of RegenerateMenusAndToolbars()
UNREALED_API void RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
UNREALED_API void RegisterDrawer (struct FWidgetDrawerConfig &&Drawer, int32 SlotIndex=INDEX_NONE)
Registers a drawer for the asset editor status bar.
virtual UNREALED_API void RegisterTabSpawners (const TSharedRef< FTabManager > &TabManager) override
IToolkit interface.
UNREALED_API void RemoveAllToolbarWidgets ()
virtual UNREALED_API void RemoveEditingAsset (UObject *Asset) override
UNREALED_API void RemoveMenuExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
virtual void RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget)
Called when a toolkit requests the overlay widget to be removed.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
UNREALED_API void SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
UE_DEPRECATED (4.26, "Override CreateEditorModeManager on the toolkit class instead.") UNREALED_API void SetAssetEditorModeManager(class FAssetEditorModeManager *InModeManager)
Set the asset editor mode manager we are using.
UE_DEPRECATED (4.26, "Use GetEditorModeManager instead.") UNREALED_API class FAssetEditorModeManager *GetAssetEditorModeManager() const
Get the asset editor mode manager we are using.
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") UNREALED_API virtual bool CloseWindow() override
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< FTabManager > &TabManager) override
Public Member Functions inherited from IAssetEditorInstance
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API FName GetToolkitContextFName () const override
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsBlueprintEditor () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedRef< FAssetEditorToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static UNREALED_API FText GetLabelForObject (const UObject *InObject)
Gets the text to display in a toolkit titlebar for an object.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedMenuExtensibilityManager ()
Returns the default extensibility managers, these are applied for all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedToolBarExtensibilityManager ()
static UNREALED_API FText GetToolTipTextForObject (const UObject *InObject)
Gets the text to display in a toolkit tooltip for an object.
static UNREALED_API void RegisterDefaultToolBar ()
Registers default tool bar.
static UNREALED_API void SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost)
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Protected Member Functions
virtual UNREALED_API void AddEditingObject (UObject *Object)
Adds an item to the Editing Objects list.
virtual UNREALED_API void BrowseDocumentation_Execute () const
Called when "Browse Documentation" is clicked for this asset.
virtual bool CanFindInContentBrowser () const
Called to test if "Find in Content Browser" should be enabled for this asset.
virtual UNREALED_API bool CanReimport () const
Called to check to see if there's an asset capable of being reimported.
virtual UNREALED_API bool CanReimport (UObject *EditingObject) const
bool CanReimport_Internal () const
Internal function to check if the asset can be reimported that calls CanReimport.
virtual bool CanSaveAsset () const
Called to test if "Save" should be enabled for this asset.
bool CanSaveAsset_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAsset.
virtual bool CanSaveAssetAs () const
Called to test if "Save As" should be enabled for this asset.
bool CanSaveAssetAs_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
virtual UNREALED_API void CreateEditorModeManager () override
virtual UNREALED_API void FindInContentBrowser_Execute ()
Called when "Find in Content Browser" is clicked for this asset.
virtual UNREALED_API UToolMenu * GenerateCommonActionsToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for common asset actions like Save.
UToolMenu * GenerateReadOnlyToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for read only mode specific content.
virtual UNREALED_API FLinearColor GetDefaultTabColor () const
virtual UNREALED_API const FSlateBrush * GetDefaultTabIcon () const
virtual UNREALED_API FString GetDocumentationLink () const
UNREALED_API UObject * GetEditingObject () const
Returns the single object currently being edited.
UNREALED_API TArray< TObjectPtr< UObject > > & GetEditingObjectPtrs ()
UNREALED_API const TArray< UObject * > & GetEditingObjects () const
Returns an array of all the objects currently being edited.
virtual UNREALED_API FName GetReadOnlyMenuProfileName ()
Get the name of the profile registered with UToolMenus for read only menu customizations.
virtual UNREALED_API void GetSaveableObjects (TArray< UObject * > &OutObjects) const
Get the collection of edited objects that can be saved.
virtual UNREALED_API EVisibility GetVisibilityWhileAssetCompiling () const
Called to get the desired visibility when the asset is compiling.
bool HasEditingObject () const
Returns true if this toolkit has any objects being edited.
virtual bool IsFindInContentBrowserButtonVisible () const
Called to test if "Find in Content Browser" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetAsVisible () const
Called to test if "Save As" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetVisible () const
Called to test if "Save" should be visible for this asset.
virtual UNREALED_API void MapToolkitCommands ()
Can be overriden to prevent registering the default commands.
virtual void OnAssetsSaved (const TArray< UObject * > &SavedObjects)
Called from SaveAsset_Execute when assets have been saved.
virtual void OnAssetsSavedAs (const TArray< UObject * > &SavedObjects)
Called from SaveAssetAs_Execute when assets have been saved.
virtual void OnClose ()
Called when this toolkit is being closed.
virtual UNREALED_API bool OnRequestClose (EAssetEditorCloseReason InCloseReason)
Called when this toolkit is requested to close.
virtual void PostInitAssetEditor ()
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
virtual UNREALED_API void Reimport_Execute ()
Called when "Reimport" is clicked for this asset.
virtual UNREALED_API void Reimport_Execute (UObject *EditingObject)
virtual UNREALED_API void RemoveEditingObject (UObject *Object)
Removes an item from the Editing Objects list.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout, bool bLoadUserLayout)
Applies the passed in layout.
virtual UNREALED_API void SaveAsset_Execute ()
Called when "Save" is clicked for this asset.
virtual UNREALED_API void SaveAssetAs_Execute ()
Called when "Save As" is clicked for this asset.
virtual UNREALED_API void SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization &OutReadOnlyCustomization)
Specify the permission lists to use in read only mode.
virtual UNREALED_API bool ShouldPromptForNewFilesOnReload (const UObject &object) const
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
virtual bool ShouldReopenEditorForSavedAsset (const UObject *Asset) const
Whether to open a new asset editor for the newly-saved Asset.
UE_DEPRECATED (4.26, "Use EditorModeManager instead.") FAssetEditorModeManager *AssetEditorModeManager
UE_DEPRECATED (5.3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") virtual bool OnRequestClose()
Called when this toolkit is requested to close.
Protected Member Functions inherited from FBaseToolkit
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static UNREALED_API void SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
static UNREALED_API void SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
TSharedPtr< FWorkspaceItem > AssetEditorTabsCategory
The base category that tabs are registered to, allows for child classes to register to the same point.
bool bCheckDirtyOnAssetSave
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
TSharedPtr< FEditorModeTools > EditorModeManager
The editor mode manager.
TArray< TSharedPtr< FLayoutExtender > > LayoutExtenders
Array of layout extenders.
FString LayoutIni = GEditorLayoutIni
What ini file should be used to persist and restore the user's layout.
TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHost
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
TSharedPtr< FTabManager > TabManager
Controls our internal layout.
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Private Member Functions
void HandleTabManagerPersistLayout (const TSharedRef< FTabManager::FLayout > &LayoutToSave)
void InitializeReadOnlyMenuProfiles ()
Initialize the base level customizations for read only mode and register the profile.
Private Attributes
bool bIsToolbarFocusable
Whether the buttons on the default toolbar can receive keyboard focus.
bool bIsToolbarUsingSmallIcons
Whether the buttons on the default toolbar use small icons.
TArray< TObjectPtr< UObject > > EditingObjects
The object we're currently editing.
FAssetEditorToolkit::FGCEditingObjects GCEditingObjects
EAssetOpenMethod OpenMethod
Whether the asset editor was opened in edit mode or read only mode.
FReadOnlyAssetEditorCustomization ReadOnlyCustomization
Determines menu/toolbar customization in read only mode.
TWeakPtr< SStandaloneAssetEditorToolkitHost > StandaloneHost
The toolkit standalone host; may be nullptr.
TSharedPtr< SWidget > Toolbar
Asset Editor Default Toolbar.
TArray< TSharedPtr< FExtender > > ToolbarExtenders
The menu extenders to populate the main toolbar with.
TSharedPtr< SBorder > ToolbarWidgetContent
The widget that will house the default Toolbar widget.
TArray< TSharedRef< SWidget > > ToolbarWidgets
Additional widgets to be added to the toolbar.
Static Private Attributes
static UNREALED_API const FName DefaultAssetEditorToolBarName
static UNREALED_API TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHostForNewAssetEditor
Static: World centric toolkit host to use for the next created asset editing toolkit.
static UNREALED_API const FName ReadOnlyMenuProfileName
The name of the profile registered with UToolMenus for read only menu customizations.
static UNREALED_API TSharedPtr< FExtensibilityManager > SharedMenuExtensibilityManager
The extensibility managers shared by all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > SharedToolBarExtensibilityManager
Friends
class UAssetEditorToolkitMenuContext
Detailed Description
Base class for toolkits that are used for asset editing (abstract)
Definition at line 114 of file AssetEditorToolkit.h.
Constructor & Destructor Documentation
FAssetEditorToolkit() [1/2]
UNREALED_API FAssetEditorToolkit::FAssetEditorToolkit ()
Default constructor.
Referenced by FAssetEditorToolkit(), FAssetEditorToolkit::FGCEditingObjects::FGCEditingObjects(), and operator=().
FAssetEditorToolkit() [2/2]
FAssetEditorToolkit::FAssetEditorToolkit (const FAssetEditorToolkit &) delete
References FAssetEditorToolkit().
~FAssetEditorToolkit()
virtual UNREALED_API FAssetEditorToolkit::~FAssetEditorToolkit () virtual
Virtual destructor, so that we can clean up our app when destroyed.
Member Function Documentation
AddEditingObject()
virtual UNREALED_API void FAssetEditorToolkit::AddEditingObject (UObject * Object) protected virtual
Adds an item to the Editing Objects list.
References Object.
AddGraphEditorPinActionsToContextMenu()
virtual void FAssetEditorToolkit::AddGraphEditorPinActionsToContextMenu (FToolMenuSection & InSection) const inline virtual
Definition at line 313 of file AssetEditorToolkit.h.
References AddGraphEditorPinActionsToContextMenu().
Referenced by AddGraphEditorPinActionsToContextMenu().
AddMenuExtender()
UNREALED_API void FAssetEditorToolkit::AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
Referenced by FRigVMNewEditor::AddMenuExtender().
AddToolbarExtender()
UNREALED_API void FAssetEditorToolkit::AddToolbarExtender (TSharedPtr< FExtender > Extender)
Referenced by FRigVMNewEditor::AddToolbarExtender().
AddToolbarWidget()
UNREALED_API void FAssetEditorToolkit::AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
AddViewportOverlayWidget()
virtual void FAssetEditorToolkit::AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder = INDEX_NONE) inline virtual
Definition at line 259 of file AssetEditorToolkit.h.
References INDEX_NONE.
BrowseDocumentation_Execute()
virtual UNREALED_API void FAssetEditorToolkit::BrowseDocumentation_Execute () const protected virtual
Called when "Browse Documentation" is clicked for this asset.
CanFindInContentBrowser()
virtual bool FAssetEditorToolkit::CanFindInContentBrowser () const inline protected virtual
Called to test if "Find in Content Browser" should be enabled for this asset.
Definition at line 388 of file AssetEditorToolkit.h.
CanReimport() [1/2]
virtual UNREALED_API bool FAssetEditorToolkit::CanReimport () const protected virtual
Called to check to see if there's an asset capable of being reimported.
CanReimport() [2/2]
virtual UNREALED_API bool FAssetEditorToolkit::CanReimport (UObject * EditingObject) const protected virtual
CanReimport_Internal()
bool FAssetEditorToolkit::CanReimport_Internal () const protected
Internal function to check if the asset can be reimported that calls CanReimport.
CanSaveAsset()
virtual bool FAssetEditorToolkit::CanSaveAsset () const inline protected virtual
Called to test if "Save" should be enabled for this asset.
Definition at line 355 of file AssetEditorToolkit.h.
CanSaveAsset_Internal()
bool FAssetEditorToolkit::CanSaveAsset_Internal () const protected
Internal function to check if the asset can be saved that calls CanSaveAsset.
CanSaveAssetAs()
virtual bool FAssetEditorToolkit::CanSaveAssetAs () const inline protected virtual
Called to test if "Save As" should be enabled for this asset.
Definition at line 370 of file AssetEditorToolkit.h.
CanSaveAssetAs_Internal()
bool FAssetEditorToolkit::CanSaveAssetAs_Internal () const protected
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
CloseWindow()
virtual UNREALED_API bool FAssetEditorToolkit::CloseWindow (EAssetEditorCloseReason InCloseReason) override virtual
Reimplemented from IAssetEditorInstance.
References CloseWindow().
Referenced by CloseWindow(), and UE_DEPRECATED().
CreateEditorModeManager()
virtual UNREALED_API void FAssetEditorToolkit::CreateEditorModeManager () override protected virtual
Reimplemented from FBaseToolkit.
Reimplemented in FBaseAssetToolkit, FPersonaAssetEditorToolkit, and FWidgetBlueprintEditor.
CreateMenuBar()
virtual UNREALED_API TSharedPtr< SWidget > FAssetEditorToolkit::CreateMenuBar (const TSharedPtr< FTabManager > & InTabManager, const FName InMenuName, FToolMenuContext & InToolMenuContext) inline virtual
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
Definition at line 242 of file AssetEditorToolkit.h.
FillDefaultAssetMenuCommands()
UNREALED_API void FAssetEditorToolkit::FillDefaultAssetMenuCommands (FToolMenuSection & InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
Parameters
MenuBuilder The menu to add commands to
FillDefaultFileMenuCommands()
UNREALED_API void FAssetEditorToolkit::FillDefaultFileMenuCommands (FToolMenuSection & InSection)
Fills in the supplied menu with commands for working with this asset file.
Parameters
MenuBuilder The menu to add commands to
FillDefaultFileMenuOpenCommands()
UNREALED_API void FAssetEditorToolkit::FillDefaultFileMenuOpenCommands (FToolMenuSection & InSection)
Fills in the supplied menu with commands for working with this asset file.
Parameters
MenuBuilder The menu to add commands to
FillDefaultHelpMenuCommands()
UNREALED_API void FAssetEditorToolkit::FillDefaultHelpMenuCommands (FToolMenuSection & InSection)
Fills in the supplied menu with commands for the help menu.
Parameters
MenuBuilder The menu to add commands to
FindInContentBrowser_Execute()
virtual UNREALED_API void FAssetEditorToolkit::FindInContentBrowser_Execute () protected virtual
Called when "Find in Content Browser" is clicked for this asset.
FocusWindow()
virtual UNREALED_API void FAssetEditorToolkit::FocusWindow (UObject * ObjectToFocusOn = nullptr) override virtual
Implements IAssetEditorInstance.
References FocusWindow().
Referenced by FocusWindow().
GenerateCommonActionsToolbar()
virtual UNREALED_API UToolMenu * FAssetEditorToolkit::GenerateCommonActionsToolbar (FToolMenuContext & MenuContext) protected virtual
Generate the toolbar for common asset actions like Save.
GenerateReadOnlyToolbar()
UToolMenu * FAssetEditorToolkit::GenerateReadOnlyToolbar (FToolMenuContext & MenuContext) protected
Generate the toolbar for read only mode specific content.
GenerateToolbar()
UNREALED_API void FAssetEditorToolkit::GenerateToolbar ()
Makes a default asset editing toolbar.
GetAssociatedTabManager()
virtual UNREALED_API TSharedPtr< FTabManager > FAssetEditorToolkit::GetAssociatedTabManager () override virtual
Implements IAssetEditorInstance.
GetBaseToolkitName()
virtual FText FAssetEditorToolkit::GetBaseToolkitName () const override pure virtual
Implemented in FBaseAssetToolkit, FBlueprintEditor, FSimpleAssetEditor, and FWidgetBlueprintEditor.
GetDefaultTabColor()
virtual UNREALED_API FLinearColor FAssetEditorToolkit::GetDefaultTabColor () const protected virtual
Returns
the color to use for the tab color
GetDefaultTabIcon()
virtual UNREALED_API const FSlateBrush * FAssetEditorToolkit::GetDefaultTabIcon () const protected virtual
Returns
a pointer to the brush to use for the tab icon
GetDocumentationLink()
virtual UNREALED_API FString FAssetEditorToolkit::GetDocumentationLink () const protected virtual
Returns
the documentation location for this editor
Reimplemented in FBlueprintEditor.
GetEditingAssetTypeName()
virtual UNREALED_API FName FAssetEditorToolkit::GetEditingAssetTypeName () const override virtual
Reimplemented from IAssetEditorInstance.
Reimplemented in FSimpleAssetEditor.
GetEditingObject()
UNREALED_API UObject * FAssetEditorToolkit::GetEditingObject () const protected
Returns the single object currently being edited.
Asserts if currently editing no object or multiple objects
GetEditingObjectPtrs()
UNREALED_API TArray< TObjectPtr< UObject > > & FAssetEditorToolkit::GetEditingObjectPtrs () protected
GetEditingObjects()
UNREALED_API const TArray< UObject * > & FAssetEditorToolkit::GetEditingObjects () const protected
Returns an array of all the objects currently being edited.
Asserts if editing no objects
Referenced by FRigVMNewEditor::GetEditingBlueprints().
GetEditorModeManager()
virtual UNREALED_API FEditorModeTools & FAssetEditorToolkit::GetEditorModeManager () const final virtual
Implements FBaseToolkit.
Referenced by FRigVMNewEditor::GetToolkitEditorModeManager().
GetEditorName()
virtual UNREALED_API FName FAssetEditorToolkit::GetEditorName () const override virtual
IAssetEditorInstance interface.
Implements IAssetEditorInstance.
References GetEditorName().
Referenced by GetEditorName().
GetLabelForObject()
UNREALED_API FText FAssetEditorToolkit::GetLabelForObject (const UObject * InObject) static
Gets the text to display in a toolkit titlebar for an object.
Parameters
InObject The object we want a description of
Returns
a formatted description of the object state (e.g. "MyObject*")
GetLastActivationTime()
virtual UNREALED_API double FAssetEditorToolkit::GetLastActivationTime () override virtual
Implements IAssetEditorInstance.
GetObjectsCurrentlyBeingEdited()
virtual UNREALED_API const TArray< UObject * > * FAssetEditorToolkit::GetObjectsCurrentlyBeingEdited () const override virtual
Reimplemented in FRigVMNewEditor.
Referenced by FRigVMNewEditor::GetObjectsCurrentlyBeingEdited().
GetOpenMethod()
virtual UNREALED_API EAssetOpenMethod FAssetEditorToolkit::GetOpenMethod () const inline override virtual
Reimplemented from IAssetEditorInstance.
Definition at line 175 of file AssetEditorToolkit.h.
References OpenMethod.
GetPreviousWorldCentricToolkitHost()
UNREALED_API TSharedPtr< IToolkitHost > FAssetEditorToolkit::GetPreviousWorldCentricToolkitHost ()
Returns
For standalone asset editing tool-kits, returns the toolkit host that was last hosting this asset editor before it was switched to standalone mode (if it's still valid.) Returns null if these conditions aren't met.
GetReadOnlyMenuProfileName()
virtual UNREALED_API FName FAssetEditorToolkit::GetReadOnlyMenuProfileName () inline protected virtual
Get the name of the profile registered with UToolMenus for read only menu customizations.
Definition at line 453 of file AssetEditorToolkit.h.
References ReadOnlyMenuProfileName.
GetSaveableObjects()
virtual UNREALED_API void FAssetEditorToolkit::GetSaveableObjects (TArray< UObject * > & OutObjects) const protected virtual
Get the collection of edited objects that can be saved.
GetSharedMenuExtensibilityManager()
UNREALED_API TSharedPtr< FExtensibilityManager > FAssetEditorToolkit::GetSharedMenuExtensibilityManager () static
Returns the default extensibility managers, these are applied for all asset types.
GetSharedToolBarExtensibilityManager()
UNREALED_API TSharedPtr< FExtensibilityManager > FAssetEditorToolkit::GetSharedToolBarExtensibilityManager () static
GetStatusBarCreationOptions()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions FAssetEditorToolkit::GetStatusBarCreationOptions () const virtual
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
GetTabManager()
TSharedPtr< FTabManager > FAssetEditorToolkit::GetTabManager () inline
Returns
Returns this asset editor's tab manager object. May be nullptr for non-standalone toolkits
Definition at line 224 of file AssetEditorToolkit.h.
References TabManager.
Referenced by FRigVMNewEditor::GetTabManager().
GetTabSuffix()
virtual UNREALED_API FText FAssetEditorToolkit::GetTabSuffix () const override virtual
Reimplemented from FBaseToolkit.
GetToolkitFName()
virtual FName FAssetEditorToolkit::GetToolkitFName () const override pure virtual
Implemented in FBaseAssetToolkit, FBlueprintEditor, FSimpleAssetEditor, and FWidgetBlueprintEditor.
GetToolkitName()
virtual UNREALED_API FText FAssetEditorToolkit::GetToolkitName () const override virtual
Reimplemented in FBlueprintEditor, and FSimpleAssetEditor.
GetToolkitToolTipText()
virtual UNREALED_API FText FAssetEditorToolkit::GetToolkitToolTipText () const override virtual
Reimplemented in FBlueprintEditor, and FSimpleAssetEditor.
GetToolMenuAppName()
UNREALED_API FName FAssetEditorToolkit::GetToolMenuAppName () const
GetToolMenuName()
UNREALED_API FName FAssetEditorToolkit::GetToolMenuName () const
GetToolMenuToolbarName() [1/2]
UNREALED_API FName FAssetEditorToolkit::GetToolMenuToolbarName () const
GetToolMenuToolbarName() [2/2]
virtual UNREALED_API FName FAssetEditorToolkit::GetToolMenuToolbarName (FName & OutParentName) const virtual
Get name used by tool menu.
Reimplemented in FWorkflowCentricApplication.
GetToolTipTextForObject()
UNREALED_API FText FAssetEditorToolkit::GetToolTipTextForObject (const UObject * InObject) static
Gets the text to display in a toolkit tooltip for an object.
Parameters
InObject The object we want a description of
Returns
a formatted description of the object
GetVisibilityWhileAssetCompiling()
virtual UNREALED_API EVisibility FAssetEditorToolkit::GetVisibilityWhileAssetCompiling () const protected virtual
Called to get the desired visibility when the asset is compiling.
GetWorldCentricTabPrefix()
virtual FString FAssetEditorToolkit::GetWorldCentricTabPrefix () const override pure virtual
Implemented in FBaseAssetToolkit, FBlueprintEditor, FSimpleAssetEditor, and FWidgetBlueprintEditor.
HandleTabManagerPersistLayout()
void FAssetEditorToolkit::HandleTabManagerPersistLayout (const TSharedRef< FTabManager::FLayout > & LayoutToSave) inline private
Definition at line 468 of file AssetEditorToolkit.h.
References GEditorLayoutIni, and FLayoutSaveRestore::SaveToConfig().
HasEditingObject()
bool FAssetEditorToolkit::HasEditingObject () const inline protected
Returns true if this toolkit has any objects being edited.
Definition at line 330 of file AssetEditorToolkit.h.
References EditingObjects.
InitAssetEditor() [1/2]
UNREALED_API void FAssetEditorToolkit::InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > & StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > & ObjectsToEdit, const bool bInIsToolbarFocusable = false, const bool bInUseSmallToolbarIcons = false, const TOptional< EAssetOpenMethod > & InOpenMethod = TOptional< EAssetOpenMethod >())
Initializes this asset editor.
Called immediately after construction. Override PostInitAssetEditor if you need to do additional initialization
Parameters
Mode Asset editing mode for this editor (standalone or world-centric)
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
AppIdentifier When Mode is Standalone, this is the app identifier of the app that should host this toolkit
StandaloneDefaultLayout The default layout for a standalone asset editor
bCreateDefaultToolbar The default toolbar, which can be extended
bCreateDefaultStandaloneMenu True if in standalone mode, the asset editor should automatically generate a default "asset" menu, or false if you're going to do this yourself in your derived asset editor's implementation
ObjectToEdit The object to edit
bInIsToolbarFocusable Whether the buttons on the default toolbar can receive keyboard focus
bUseSmallToolbarIcons Whether the buttons on the default toolbar use the small icons
InOpenMethod Override whether the Asset Editor is being opened in read only or edit mode (otherwise automatically set by the asset editor subsytem for any asset editors opened through it)
InitAssetEditor() [2/2]
UNREALED_API void FAssetEditorToolkit::InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > & StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject * ObjectToEdit, const bool bInIsToolbarFocusable = false, const bool bInUseSmallToolbarIcons = false, const TOptional< EAssetOpenMethod > & InOpenMethod = TOptional< EAssetOpenMethod >())
InitializeReadOnlyMenuProfiles()
void FAssetEditorToolkit::InitializeReadOnlyMenuProfiles () private
Initialize the base level customizations for read only mode and register the profile.
InitToolMenuContext()
virtual UNREALED_API void FAssetEditorToolkit::InitToolMenuContext (FToolMenuContext & MenuContext) virtual
Reimplemented in FBlueprintEditor, FRigVMNewEditor, and FWidgetBlueprintEditor.
InvokeTab()
virtual UNREALED_API void FAssetEditorToolkit::InvokeTab (const FTabId & TabId) override virtual
IsActuallyAnAsset()
UNREALED_API bool FAssetEditorToolkit::IsActuallyAnAsset () const
True if this actually is editing an asset.
IsAssetEditor()
virtual UNREALED_API bool FAssetEditorToolkit::IsAssetEditor () const override virtual
IsFindInContentBrowserButtonVisible()
virtual bool FAssetEditorToolkit::IsFindInContentBrowserButtonVisible () const inline protected virtual
Called to test if "Find in Content Browser" should be visible for this asset.
Definition at line 394 of file AssetEditorToolkit.h.
IsPrimaryEditor()
virtual bool FAssetEditorToolkit::IsPrimaryEditor () const inline override virtual
Implements IAssetEditorInstance.
Reimplemented in FSimpleAssetEditor.
Definition at line 169 of file AssetEditorToolkit.h.
References IsPrimaryEditor().
Referenced by IsPrimaryEditor().
IsSaveAssetAsVisible()
virtual UNREALED_API bool FAssetEditorToolkit::IsSaveAssetAsVisible () const protected virtual
Called to test if "Save As" should be visible for this asset.
IsSaveAssetVisible()
virtual UNREALED_API bool FAssetEditorToolkit::IsSaveAssetVisible () const protected virtual
Called to test if "Save" should be visible for this asset.
MapToolkitCommands()
virtual UNREALED_API void FAssetEditorToolkit::MapToolkitCommands () protected virtual
Can be overriden to prevent registering the default commands.
OnAssetsSaved()
virtual void FAssetEditorToolkit::OnAssetsSaved (const TArray< UObject * > & SavedObjects) inline protected virtual
Called from SaveAsset_Execute when assets have been saved.
Definition at line 367 of file AssetEditorToolkit.h.
OnAssetsSavedAs()
virtual void FAssetEditorToolkit::OnAssetsSavedAs (const TArray< UObject * > & SavedObjects) inline protected virtual
Called from SaveAssetAs_Execute when assets have been saved.
Definition at line 385 of file AssetEditorToolkit.h.
OnClose()
virtual void FAssetEditorToolkit::OnClose () inline protected virtual
Called when this toolkit is being closed.
Reimplemented in FBlueprintEditor, FRigVMNewEditor, and FWorkflowCentricApplication.
Definition at line 426 of file AssetEditorToolkit.h.
OnRequestClose()
virtual UNREALED_API bool FAssetEditorToolkit::OnRequestClose (EAssetEditorCloseReason InCloseReason) protected virtual
Called when this toolkit is requested to close.
Returns false if closing should be prevented.
Reimplemented in FBlueprintEditor, FWidgetBlueprintEditor, and FWorkflowCentricApplication.
Referenced by UE_DEPRECATED().
OnToolkitHostingFinished()
virtual void FAssetEditorToolkit::OnToolkitHostingFinished (const TSharedRef< IToolkit > & Toolkit) inline virtual
Reimplemented in FPersonaAssetEditorToolkit, and FWidgetBlueprintEditor.
Definition at line 254 of file AssetEditorToolkit.h.
OnToolkitHostingStarted()
virtual void FAssetEditorToolkit::OnToolkitHostingStarted (const TSharedRef< IToolkit > & Toolkit) inline virtual
Reimplemented in FPersonaAssetEditorToolkit, and FWidgetBlueprintEditor.
Definition at line 251 of file AssetEditorToolkit.h.
OnViewportDragEnter()
virtual void FAssetEditorToolkit::OnViewportDragEnter (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) inline virtual
React to a Drag&Drop events from the viewport.
Definition at line 316 of file AssetEditorToolkit.h.
OnViewportDragLeave()
virtual void FAssetEditorToolkit::OnViewportDragLeave (const FDragDropEvent & DragDropEvent) inline virtual
Definition at line 317 of file AssetEditorToolkit.h.
OnViewportDrop()
virtual FReply FAssetEditorToolkit::OnViewportDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) inline virtual
Definition at line 318 of file AssetEditorToolkit.h.
References FReply::Unhandled().
operator=()
FAssetEditorToolkit & FAssetEditorToolkit::operator= (const FAssetEditorToolkit &) delete
References FAssetEditorToolkit().
PostInitAssetEditor()
virtual void FAssetEditorToolkit::PostInitAssetEditor () inline protected virtual
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
For example, if you would like to activate a mode that is not the default from a mode manager, do that here.
Definition at line 327 of file AssetEditorToolkit.h.
PostRegenerateMenusAndToolbars()
virtual void FAssetEditorToolkit::PostRegenerateMenusAndToolbars () inline virtual
Called at the end of RegenerateMenusAndToolbars()
Reimplemented in FBlueprintEditor, and FSimpleAssetEditor.
Definition at line 248 of file AssetEditorToolkit.h.
RegenerateMenusAndToolbars()
UNREALED_API void FAssetEditorToolkit::RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
Referenced by FRigVMNewEditor::RegenerateMenusAndToolbars().
RegisterDefaultToolBar()
UNREALED_API void FAssetEditorToolkit::RegisterDefaultToolBar () static
Registers default tool bar.
RegisterDrawer()
UNREALED_API void FAssetEditorToolkit::RegisterDrawer (struct FWidgetDrawerConfig && Drawer, int32 SlotIndex = INDEX_NONE)
Registers a drawer for the asset editor status bar.
References INDEX_NONE.
RegisterTabSpawners()
virtual UNREALED_API void FAssetEditorToolkit::RegisterTabSpawners (const TSharedRef< FTabManager > & TabManager) override virtual
IToolkit interface.
Reimplemented in FBaseAssetToolkit, FBlueprintEditor, FRigVMNewEditor, FSimpleAssetEditor, and FWorkflowCentricApplication.
References TabManager.
Referenced by FRigVMNewEditor::RegisterToolbarTab().
Reimport_Execute() [1/2]
virtual UNREALED_API void FAssetEditorToolkit::Reimport_Execute () protected virtual
Called when "Reimport" is clicked for this asset.
Reimport_Execute() [2/2]
virtual UNREALED_API void FAssetEditorToolkit::Reimport_Execute (UObject * EditingObject) protected virtual
RemoveAllToolbarWidgets()
UNREALED_API void FAssetEditorToolkit::RemoveAllToolbarWidgets ()
RemoveEditingAsset()
virtual UNREALED_API void FAssetEditorToolkit::RemoveEditingAsset (UObject * Asset) override virtual
Implements IAssetEditorInstance.
References Asset.
RemoveEditingObject()
virtual UNREALED_API void FAssetEditorToolkit::RemoveEditingObject (UObject * Object) protected virtual
Removes an item from the Editing Objects list.
References Object.
RemoveMenuExtender()
UNREALED_API void FAssetEditorToolkit::RemoveMenuExtender (TSharedPtr< FExtender > Extender)
Referenced by FRigVMNewEditor::RemoveMenuExtender().
RemoveToolbarExtender()
UNREALED_API void FAssetEditorToolkit::RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
Referenced by FRigVMNewEditor::RemoveToolbarExtender().
RemoveViewportOverlayWidget()
virtual void FAssetEditorToolkit::RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget) inline virtual
Called when a toolkit requests the overlay widget to be removed.
Definition at line 262 of file AssetEditorToolkit.h.
RestoreFromLayout() [1/2]
UNREALED_API void FAssetEditorToolkit::RestoreFromLayout (const TSharedRef< FTabManager::FLayout > & NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
Must be called after InitAssetEditor.
RestoreFromLayout() [2/2]
UNREALED_API void FAssetEditorToolkit::RestoreFromLayout (const TSharedRef< FTabManager::FLayout > & NewLayout, bool bLoadUserLayout) protected
Applies the passed in layout.
Parameters
NewLayout The layout to restore.
bLoadUserLayout Whether to attempt loading the saved user-modified version.
Note
Must be called after InitAssetEditor.
SaveAsset_Execute()
virtual UNREALED_API void FAssetEditorToolkit::SaveAsset_Execute () protected virtual
Called when "Save" is clicked for this asset.
Referenced by FRigVMNewEditor::SaveAsset_Execute_Impl().
SaveAssetAs_Execute()
virtual UNREALED_API void FAssetEditorToolkit::SaveAssetAs_Execute () protected virtual
Called when "Save As" is clicked for this asset.
Referenced by FRigVMNewEditor::SaveAssetAs_Execute_Impl().
SetMenuOverlay()
UNREALED_API void FAssetEditorToolkit::SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
Parameters
Widget The widget to use as the overlay
SetPreviousWorldCentricToolkitHostForNewAssetEditor()
UNREALED_API void FAssetEditorToolkit::SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost) static
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Parameters
ToolkitHost The tool-kit to use if/when this toolkit is switched back to world-centric mode
References FBaseToolkit::ToolkitHost.
SetupReadOnlyMenuProfiles()
virtual UNREALED_API void FAssetEditorToolkit::SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization & OutReadOnlyCustomization) inline protected virtual
Specify the permission lists to use in read only mode.
Definition at line 450 of file AssetEditorToolkit.h.
ShouldPromptForNewFilesOnReload()
virtual UNREALED_API bool FAssetEditorToolkit::ShouldPromptForNewFilesOnReload (const UObject & object) const protected virtual
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
ShouldReopenEditorForSavedAsset()
virtual bool FAssetEditorToolkit::ShouldReopenEditorForSavedAsset (const UObject * Asset) const inline protected virtual
Whether to open a new asset editor for the newly-saved Asset.
Called from SaveAssetAs_Execute for all newly-saved Assets sequentially.
Definition at line 382 of file AssetEditorToolkit.h.
References Asset.
SwitchToStandaloneEditor_Execute()
UNREALED_API void FAssetEditorToolkit::SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef) static protected
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
Parameters
ThisToolkitWeakRef The toolkit that we want to restart in standalone mode
SwitchToWorldCentricEditor_Execute()
UNREALED_API void FAssetEditorToolkit::SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef) static protected
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Parameters
ThisToolkitWeakRef The toolkit that we want to restart in world-centric mode
UE_DEPRECATED() [1/5]
FAssetEditorToolkit::UE_DEPRECATED (4. 26, "Override CreateEditorModeManager on the toolkit class instead.")
Set the asset editor mode manager we are using.
References UE_DEPRECATED().
UE_DEPRECATED() [2/5]
FAssetEditorToolkit::UE_DEPRECATED (4. 26, "Use EditorModeManager instead.") protected
UE_DEPRECATED() [3/5]
FAssetEditorToolkit::UE_DEPRECATED (4. 26, "Use GetEditorModeManager instead.") const
Get the asset editor mode manager we are using.
UE_DEPRECATED() [4/5]
FAssetEditorToolkit::UE_DEPRECATED (5. 3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") override
References CloseWindow(), and UE_DEPRECATED().
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/5]
FAssetEditorToolkit::UE_DEPRECATED (5. 3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") inline protected
Called when this toolkit is requested to close.
Returns false if closing should be prevented.
Definition at line 419 of file AssetEditorToolkit.h.
References OnRequestClose().
UnregisterTabSpawners()
virtual UNREALED_API void FAssetEditorToolkit::UnregisterTabSpawners (const TSharedRef< FTabManager > & TabManager) override virtual
Reimplemented in FBaseAssetToolkit, FSimpleAssetEditor, and FWorkflowCentricApplication.
References TabManager.
Friends And Related Symbol Documentation
UAssetEditorToolkitMenuContext
friend class UAssetEditorToolkitMenuContext friend
Definition at line 321 of file AssetEditorToolkit.h.
References UAssetEditorToolkitMenuContext.
Referenced by UAssetEditorToolkitMenuContext.
Field Documentation
AssetEditorTabsCategory
TSharedPtr<FWorkspaceItem> FAssetEditorToolkit::AssetEditorTabsCategory protected
The base category that tabs are registered to, allows for child classes to register to the same point.
Definition at line 517 of file AssetEditorToolkit.h.
bCheckDirtyOnAssetSave
bool FAssetEditorToolkit::bCheckDirtyOnAssetSave protected
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
Definition at line 506 of file AssetEditorToolkit.h.
bIsToolbarFocusable
bool FAssetEditorToolkit::bIsToolbarFocusable private
Whether the buttons on the default toolbar can receive keyboard focus.
Definition at line 554 of file AssetEditorToolkit.h.
bIsToolbarUsingSmallIcons
bool FAssetEditorToolkit::bIsToolbarUsingSmallIcons private
Whether the buttons on the default toolbar use small icons.
Definition at line 557 of file AssetEditorToolkit.h.
DefaultAssetEditorToolBarName
UNREALED_API const FName FAssetEditorToolkit::DefaultAssetEditorToolBarName static private
Definition at line 523 of file AssetEditorToolkit.h.
EditingObjects
TArray<TObjectPtr<UObject> > FAssetEditorToolkit::EditingObjects private
The object we're currently editing.
Definition at line 539 of file AssetEditorToolkit.h.
Referenced by HasEditingObject().
EditorModeManager
TSharedPtr<FEditorModeTools> FAssetEditorToolkit::EditorModeManager protected
The editor mode manager.
Definition at line 509 of file AssetEditorToolkit.h.
GCEditingObjects
FAssetEditorToolkit::FGCEditingObjects FAssetEditorToolkit::GCEditingObjects private
LayoutExtenders
TArray<TSharedPtr<FLayoutExtender> > FAssetEditorToolkit::LayoutExtenders protected
Array of layout extenders.
Definition at line 514 of file AssetEditorToolkit.h.
LayoutIni
FString FAssetEditorToolkit::LayoutIni = GEditorLayoutIni protected
What ini file should be used to persist and restore the user's layout.
Defaults to GEditorLayoutIni.
Definition at line 520 of file AssetEditorToolkit.h.
OpenMethod
EAssetOpenMethod FAssetEditorToolkit::OpenMethod private
Whether the asset editor was opened in edit mode or read only mode.
Definition at line 560 of file AssetEditorToolkit.h.
Referenced by GetOpenMethod().
PreviousWorldCentricToolkitHost
TWeakPtr< IToolkitHost > FAssetEditorToolkit::PreviousWorldCentricToolkitHost protected
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
This is used to allow the user to switch the toolkit back to world-centric mode.
Definition at line 500 of file AssetEditorToolkit.h.
PreviousWorldCentricToolkitHostForNewAssetEditor
UNREALED_API TWeakPtr< IToolkitHost > FAssetEditorToolkit::PreviousWorldCentricToolkitHostForNewAssetEditor static private
Static: World centric toolkit host to use for the next created asset editing toolkit.
Definition at line 528 of file AssetEditorToolkit.h.
ReadOnlyCustomization
FReadOnlyAssetEditorCustomization FAssetEditorToolkit::ReadOnlyCustomization private
Determines menu/toolbar customization in read only mode.
Definition at line 563 of file AssetEditorToolkit.h.
ReadOnlyMenuProfileName
UNREALED_API const FName FAssetEditorToolkit::ReadOnlyMenuProfileName static private
The name of the profile registered with UToolMenus for read only menu customizations.
Definition at line 535 of file AssetEditorToolkit.h.
Referenced by GetReadOnlyMenuProfileName().
SharedMenuExtensibilityManager
UNREALED_API TSharedPtr<FExtensibilityManager> FAssetEditorToolkit::SharedMenuExtensibilityManager static private
The extensibility managers shared by all asset types.
Definition at line 531 of file AssetEditorToolkit.h.
SharedToolBarExtensibilityManager
UNREALED_API TSharedPtr<FExtensibilityManager> FAssetEditorToolkit::SharedToolBarExtensibilityManager static private
Definition at line 532 of file AssetEditorToolkit.h.
StandaloneHost
TWeakPtr<SStandaloneAssetEditorToolkitHost> FAssetEditorToolkit::StandaloneHost private
The toolkit standalone host; may be nullptr.
Definition at line 525 of file AssetEditorToolkit.h.
TabManager
TSharedPtr<FTabManager> FAssetEditorToolkit::TabManager protected
Controls our internal layout.
Definition at line 503 of file AssetEditorToolkit.h.
Referenced by GetTabManager(), RegisterTabSpawners(), FBlueprintEditor::RegisterTabSpawners(), FSimpleAssetEditor::RegisterTabSpawners(), FWorkflowCentricApplication::RegisterTabSpawners(), FBlueprintEditor::RegisterToolbarTab(), UnregisterTabSpawners(), FSimpleAssetEditor::UnregisterTabSpawners(), and FWorkflowCentricApplication::UnregisterTabSpawners().
Toolbar
TSharedPtr<SWidget> FAssetEditorToolkit::Toolbar private
Asset Editor Default Toolbar.
Definition at line 542 of file AssetEditorToolkit.h.
ToolbarExtenders
TArray<TSharedPtr<FExtender> > FAssetEditorToolkit::ToolbarExtenders private
The menu extenders to populate the main toolbar with.
Definition at line 548 of file AssetEditorToolkit.h.
ToolbarWidgetContent
TSharedPtr<SBorder> FAssetEditorToolkit::ToolbarWidgetContent private
The widget that will house the default Toolbar widget.
Definition at line 545 of file AssetEditorToolkit.h.
ToolbarWidgets
TArray<TSharedRef<SWidget> > FAssetEditorToolkit::ToolbarWidgets private
Additional widgets to be added to the toolbar.
Definition at line 551 of file AssetEditorToolkit.h.
The documentation for this class was generated from the following file:
AssetEditorToolkit.h