Unreal Engine 5.6 C++ API: UE::Geometry::TPolyline< T, D >::SegmentIterator Class Reference
UE::Geometry::TPolyline< T, D >::SegmentIterator Class Reference
SegmentIterator is used to iterate over the segments of the polyline.
#include "Polyline.h"
Public Member Functions
bool operator! ()
bool operator!= (const SegmentIterator &i3)
SegmentType operator* () const
SegmentIterator & operator++ ()
SegmentIterator operator++ (int)
bool operator== (const SegmentIterator &i3)
Protected Member Functions
SegmentIterator (const TPolyline< T, D > *p, int iCur)
Protected Attributes
int i
const TPolyline< T, D > * Polyline
Friends
class TPolyline
Detailed Description
template<typename T, int D>
class UE::Geometry::TPolyline< T, D >::SegmentIterator
SegmentIterator is used to iterate over the segments of the polyline.
Definition at line 308 of file Polyline.h.
Constructor & Destructor Documentation
SegmentIterator()
template<typename T, int D> UE::Geometry::TPolyline< T, D >::SegmentIterator::SegmentIterator (const TPolyline< T, D > * p, int iCur) inline protected
Definition at line 336 of file Polyline.h.
References i, Polyline, and TPolyline.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!()
template<typename T, int D> bool UE::Geometry::TPolyline< T, D >::SegmentIterator::operator! () inline
Definition at line 311 of file Polyline.h.
References i, and Polyline.
operator!=()
template<typename T, int D> bool UE::Geometry::TPolyline< T, D >::SegmentIterator::operator!= (const SegmentIterator & i3) inline
Definition at line 332 of file Polyline.h.
References SegmentIterator(), i, and Polyline.
operator*()
template<typename T, int D> SegmentType UE::Geometry::TPolyline< T, D >::SegmentIterator::operator* () const inline
Definition at line 315 of file Polyline.h.
References check, i, Polyline, and UE::Geometry::TPolyline< T, D >::SegmentCount().
operator++() [1/2]
template<typename T, int D> SegmentIterator & UE::Geometry::TPolyline< T, D >::SegmentIterator::operator++ () inline
Definition at line 320 of file Polyline.h.
References SegmentIterator(), and i.
operator++() [2/2]
template<typename T, int D> SegmentIterator UE::Geometry::TPolyline< T, D >::SegmentIterator::operator++ (int) inline
Definition at line 325 of file Polyline.h.
References SegmentIterator(), and i.
operator==()
template<typename T, int D> bool UE::Geometry::TPolyline< T, D >::SegmentIterator::operator== (const SegmentIterator & i3) inline
Definition at line 331 of file Polyline.h.
References SegmentIterator(), i, and Polyline.
Friends And Related Symbol Documentation
TPolyline
template<typename T, int D> friend class TPolyline friend
Definition at line 337 of file Polyline.h.
References TPolyline.
Referenced by SegmentIterator(), and TPolyline.
Field Documentation
i
template<typename T, int D> int UE::Geometry::TPolyline< T, D >::SegmentIterator::i protected
Definition at line 335 of file Polyline.h.
Referenced by SegmentIterator(), operator!(), operator!=(), operator*(), operator++(), operator++(), and operator==().
Polyline
template<typename T, int D> const TPolyline<T, D>* UE::Geometry::TPolyline< T, D >::SegmentIterator::Polyline protected
Definition at line 334 of file Polyline.h.
Referenced by SegmentIterator(), operator!(), operator!=(), operator*(), and operator==().
The documentation for this class was generated from the following file:
Polyline.h