Unreal Engine 5.6 C++ API: FSdfGlyphEntryKey Struct Reference
FSdfGlyphEntryKey Struct Reference
Minimal FSdfGlyphEntryKey key information used for map lookups.
#include "FontCache.h"
Public Member Functions
FSdfGlyphEntryKey (const TWeakPtr< FFreeTypeFace > InFontFace, uint32 InGlyphIndex, ESlateFontAtlasContentType InAtlasContentType, int32 InPpem, float InEmOuterSpread, float InEmInnerSpread)
FORCEINLINE bool operator!= (const FSdfGlyphEntryKey &Other) const
FORCEINLINE bool operator== (const FSdfGlyphEntryKey &Other) const
Data Fields
const ESlateFontAtlasContentType AtlasContentType
Type of glyph pixel content.
const TWeakPtr< FFreeTypeFace > FontFace
Weak pointer to the FreeType face to render with.
const uint32 GlyphIndex
The index of this glyph in the FreeType face.
const int32 Ppem
The pixel size at which the sdf glyph is generated.
const int32 SpreadCategory
The spread category.
Static Private Member Functions
static int32 GetSpreadCategory (float InEmOuterSpread, float InEmInnerSpread)
Computes the discrete spread category from real spread values specified in em.
Private Attributes
uint32 KeyHash
Cached hash value used for map lookups.
Friends
uint32 GetTypeHash (const FSdfGlyphEntryKey &Key)
Detailed Description
Minimal FSdfGlyphEntryKey key information used for map lookups.
Definition at line 254 of file FontCache.h.
Constructor & Destructor Documentation
FSdfGlyphEntryKey()
FSdfGlyphEntryKey::FSdfGlyphEntryKey (const TWeakPtr< FFreeTypeFace > InFontFace, uint32 InGlyphIndex, ESlateFontAtlasContentType InAtlasContentType, int32 InPpem, float InEmOuterSpread, float InEmInnerSpread)
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
GetSpreadCategory()
int32 FSdfGlyphEntryKey::GetSpreadCategory (float InEmOuterSpread, float InEmInnerSpread) static private
Computes the discrete spread category from real spread values specified in em.
operator!=()
FORCEINLINE bool FSdfGlyphEntryKey::operator!= (const FSdfGlyphEntryKey & Other) const inline
Definition at line 268 of file FontCache.h.
References FSdfGlyphEntryKey(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FSdfGlyphEntryKey::operator== (const FSdfGlyphEntryKey & Other) const inline
Definition at line 259 of file FontCache.h.
References FSdfGlyphEntryKey(), AtlasContentType, FontFace, FORCEINLINE, GlyphIndex, Other, Ppem, and SpreadCategory.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSdfGlyphEntryKey & Key) friend
Definition at line 273 of file FontCache.h.
References FSdfGlyphEntryKey(), and Key.
Field Documentation
AtlasContentType
const ESlateFontAtlasContentType FSdfGlyphEntryKey::AtlasContentType
Type of glyph pixel content.
Definition at line 283 of file FontCache.h.
Referenced by operator==().
FontFace
const TWeakPtr<FFreeTypeFace> FSdfGlyphEntryKey::FontFace
Weak pointer to the FreeType face to render with.
Definition at line 279 of file FontCache.h.
Referenced by operator==().
GlyphIndex
const uint32 FSdfGlyphEntryKey::GlyphIndex
The index of this glyph in the FreeType face.
Definition at line 281 of file FontCache.h.
Referenced by operator==().
KeyHash
uint32 FSdfGlyphEntryKey::KeyHash private
Cached hash value used for map lookups.
Definition at line 291 of file FontCache.h.
Ppem
const int32 FSdfGlyphEntryKey::Ppem
The pixel size at which the sdf glyph is generated.
Definition at line 285 of file FontCache.h.
Referenced by operator==().
SpreadCategory
const int32 FSdfGlyphEntryKey::SpreadCategory
The spread category.
The spreads of a glyph entry can be arbitrary but similar values will share the same category and therefore glyph entry
Definition at line 287 of file FontCache.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
FontCache.h