Unreal Engine 5.6 C++ API: FSkinWeightDataVertexBuffer Class Reference
FSkinWeightDataVertexBuffer Class Reference
A vertex buffer storing bone index/weight data.
#include "SkinWeightVertexBuffer.h"
Public Member Functions
FSkinWeightDataVertexBuffer ()
Default constructor.
FSkinWeightDataVertexBuffer (const FSkinWeightDataVertexBuffer &Other)
Constructor (copy)
~FSkinWeightDataVertexBuffer ()
Destructor.
void CleanUp ()
Delete existing resources.
void CopyDataFromBuffer (const uint8 *InSkinWeightData, uint32 InNumVertices)
void CopyMetaData (const FSkinWeightDataVertexBuffer &Other)
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
uint32 GetBoneIndex (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex) const
FORCEINLINE uint32 GetBoneIndexAndWeightByteSize () const
FORCEINLINE uint32 GetBoneIndexByteSize () const
GPUSkinBoneInfluenceType GetBoneInfluenceType () const
uint16 GetBoneWeight (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex) const
FORCEINLINE uint32 GetBoneWeightByteSize () const
FORCEINLINE uint32 GetConstantInfluencesBoneWeightsOffset () const
FORCEINLINE uint32 GetConstantInfluencesVertexStride () const
virtual FString GetFriendlyName () const override
FORCEINLINE uint32 GetMaxBoneInfluences () const
FORCEINLINE bool GetNeedsCPUAccess () const
FORCEINLINE uint32 GetNumBoneWeights () const
FORCEINLINE uint32 GetNumVertices () const
bool GetRigidWeightBone (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, int32 &OutBoneIndex) const
FRHIShaderResourceView * GetSRV () const
FORCEINLINE bool GetVariableBonesPerVertex () const
FORCEINLINE uint32 GetVertexDataSize () const
uint8 * GetWeightData ()
const uint8 * GetWeightData () const
void Init (uint32 InNumWeights, uint32 InNumVertices)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
bool IsWeightDataValid () const
FSkinWeightDataVertexBuffer & operator= (const FSkinWeightDataVertexBuffer &Other)
Assignment.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void ResetVertexBoneWeights (uint32 VertexWeightOffset, uint32 VertexInfluenceCount)
void SerializeMetaData (FArchive &Ar)
void SetBoneIndex (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex, uint32 BoneIndex)
void SetBoneWeight (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex, uint16 BoneWeight)
void SetMaxBoneInfluences (uint32 InMaxBoneInfluences)
Set if this will have extra streams for bone indices & weights.
void SetMetaData (uint32 InNumVertices, uint32 InMaxBoneInfluences, bool bInUse16BitBoneIndex, bool bInUse16BitBoneWeight)
FORCEINLINE void SetNeedsCPUAccess (bool bInNeedsCPUAccess)
Set if the CPU needs access to this vertex buffer.
FORCEINLINE void SetUse16BitBoneIndex (bool bInUse16BitBoneIndex)
void SetUse16BitBoneWeight (bool bInUse16BitBoneWeight)
FORCEINLINE bool Use16BitBoneIndex () const
bool Use16BitBoneWeight () const
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Protected Attributes
FShaderResourceViewRHIRef SRVValue
Private Member Functions
void AllocateData ()
Allocates the vertex data storage type.
EPixelFormat GetPixelFormat () const
uint32 GetPixelFormatStride () const
void ResizeBuffer (uint32 InNumWeights, uint32 InNumVertices)
Private Attributes
bool bNeedsCPUAccess
true if this vertex buffer will be used with CPU skinning.
bool bUse16BitBoneIndex
Use 16 bit bone index instead of 8 bit.
bool bUse16BitBoneWeight
Use 16 bit bone weight instead of 8 bit.
bool bVariableBonesPerVertex
uint8 * Data
The cached vertex data pointer.
uint32 MaxBoneInfluences
Has extra bone influences per Vertex, which means using a different TGPUSkinVertexBase.
uint32 NumBoneWeights
Total number of bone weights across all vertices.
uint32 NumVertices
The cached number of vertices.
FStaticMeshVertexDataInterface * WeightData
The vertex data storage type.
Friends
FArchive & operator<< (FArchive &Ar, FSkinWeightDataVertexBuffer &VertexBuffer)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex buffer storing bone index/weight data.
Definition at line 189 of file SkinWeightVertexBuffer.h.
Constructor & Destructor Documentation
FSkinWeightDataVertexBuffer() [1/2]
FSkinWeightDataVertexBuffer::FSkinWeightDataVertexBuffer ()
Default constructor.
Referenced by FSkinWeightDataVertexBuffer(), CopyMetaData(), operator<<, and operator=().
FSkinWeightDataVertexBuffer() [2/2]
FSkinWeightDataVertexBuffer::FSkinWeightDataVertexBuffer (const FSkinWeightDataVertexBuffer & Other)
Constructor (copy)
References FSkinWeightDataVertexBuffer(), and Other.
~FSkinWeightDataVertexBuffer()
FSkinWeightDataVertexBuffer::~FSkinWeightDataVertexBuffer ()
Destructor.
Member Function Documentation
AllocateData()
void FSkinWeightDataVertexBuffer::AllocateData () private
Allocates the vertex data storage type.
CleanUp()
void FSkinWeightDataVertexBuffer::CleanUp ()
Delete existing resources.
CopyDataFromBuffer()
void FSkinWeightDataVertexBuffer::CopyDataFromBuffer (const uint8 * InSkinWeightData, uint32 InNumVertices)
CopyMetaData()
void FSkinWeightDataVertexBuffer::CopyMetaData (const FSkinWeightDataVertexBuffer & Other)
References FSkinWeightDataVertexBuffer(), and Other.
CreateRHIBuffer()
FBufferRHIRef FSkinWeightDataVertexBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
GetBoneIndex()
uint32 FSkinWeightDataVertexBuffer::GetBoneIndex (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex) const
GetBoneIndexAndWeightByteSize()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetBoneIndexAndWeightByteSize () const inline
Definition at line 239 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, GetBoneIndexByteSize(), and GetBoneWeightByteSize().
Referenced by GetConstantInfluencesVertexStride(), and GetVertexDataSize().
GetBoneIndexByteSize()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetBoneIndexByteSize () const inline
Returns
byte size of each bone index
Definition at line 231 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and Use16BitBoneIndex().
Referenced by GetBoneIndexAndWeightByteSize(), and GetConstantInfluencesBoneWeightsOffset().
GetBoneInfluenceType()
GPUSkinBoneInfluenceType FSkinWeightDataVertexBuffer::GetBoneInfluenceType () const
GetBoneWeight()
uint16 FSkinWeightDataVertexBuffer::GetBoneWeight (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex) const
GetBoneWeightByteSize()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetBoneWeightByteSize () const inline
Definition at line 234 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and Use16BitBoneWeight().
Referenced by GetBoneIndexAndWeightByteSize().
GetConstantInfluencesBoneWeightsOffset()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetConstantInfluencesBoneWeightsOffset () const inline
Returns
offset position for bone weights data for each vertex
Definition at line 249 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, GetBoneIndexByteSize(), and MaxBoneInfluences.
GetConstantInfluencesVertexStride()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetConstantInfluencesVertexStride () const inline
Returns
vertex stride for when using constant number of bones per vertex buffer
Definition at line 245 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, GetBoneIndexAndWeightByteSize(), and MaxBoneInfluences.
GetFriendlyName()
virtual FString FSkinWeightDataVertexBuffer::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FVertexBuffer.
Definition at line 219 of file SkinWeightVertexBuffer.h.
References TEXT.
GetMaxBoneInfluences()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetMaxBoneInfluences () const inline
Definition at line 273 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and MaxBoneInfluences.
GetNeedsCPUAccess()
FORCEINLINE bool FSkinWeightDataVertexBuffer::GetNeedsCPUAccess () const inline
Definition at line 264 of file SkinWeightVertexBuffer.h.
References bNeedsCPUAccess, and FORCEINLINE.
GetNumBoneWeights()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetNumBoneWeights () const inline
Returns
number of bone weights in this vertex buffer
Definition at line 227 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and NumBoneWeights.
GetNumVertices()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetNumVertices () const inline
Returns
number of vertices in this vertex buffer
Definition at line 223 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and NumVertices.
GetPixelFormat()
EPixelFormat FSkinWeightDataVertexBuffer::GetPixelFormat () const inline private
Definition at line 326 of file SkinWeightVertexBuffer.h.
References bVariableBonesPerVertex, PF_R32_UINT, and PF_R8_UINT.
GetPixelFormatStride()
uint32 FSkinWeightDataVertexBuffer::GetPixelFormatStride () const inline private
Definition at line 329 of file SkinWeightVertexBuffer.h.
References bVariableBonesPerVertex.
GetRigidWeightBone()
bool FSkinWeightDataVertexBuffer::GetRigidWeightBone (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, int32 & OutBoneIndex) const
GetSRV()
FRHIShaderResourceView * FSkinWeightDataVertexBuffer::GetSRV () const inline
Definition at line 257 of file SkinWeightVertexBuffer.h.
References SRVValue.
GetVariableBonesPerVertex()
FORCEINLINE bool FSkinWeightDataVertexBuffer::GetVariableBonesPerVertex () const inline
Definition at line 267 of file SkinWeightVertexBuffer.h.
References bVariableBonesPerVertex, and FORCEINLINE.
GetVertexDataSize()
FORCEINLINE uint32 FSkinWeightDataVertexBuffer::GetVertexDataSize () const inline
Returns
total size of data in resource array
Definition at line 253 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, GetBoneIndexAndWeightByteSize(), and NumBoneWeights.
GetWeightData() [1/2]
uint8 * FSkinWeightDataVertexBuffer::GetWeightData () inline
Definition at line 314 of file SkinWeightVertexBuffer.h.
References Data.
GetWeightData() [2/2]
const uint8 * FSkinWeightDataVertexBuffer::GetWeightData () const inline
Definition at line 309 of file SkinWeightVertexBuffer.h.
References Data.
Init()
void FSkinWeightDataVertexBuffer::Init (uint32 InNumWeights, uint32 InNumVertices)
InitRHI()
virtual void FSkinWeightDataVertexBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FSkinWeightDataVertexBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
IsWeightDataValid()
bool FSkinWeightDataVertexBuffer::IsWeightDataValid () const
operator=()
FSkinWeightDataVertexBuffer & FSkinWeightDataVertexBuffer::operator= (const FSkinWeightDataVertexBuffer & Other)
Assignment.
Assumes that vertex buffer will be rebuilt
References FSkinWeightDataVertexBuffer(), and Other.
ReleaseRHI()
virtual void FSkinWeightDataVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexBuffer.
ReleaseRHIForStreaming()
void FSkinWeightDataVertexBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
ResetVertexBoneWeights()
void FSkinWeightDataVertexBuffer::ResetVertexBoneWeights (uint32 VertexWeightOffset, uint32 VertexInfluenceCount)
ResizeBuffer()
void FSkinWeightDataVertexBuffer::ResizeBuffer (uint32 InNumWeights, uint32 InNumVertices) private
SerializeMetaData()
void FSkinWeightDataVertexBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetBoneIndex()
void FSkinWeightDataVertexBuffer::SetBoneIndex (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex, uint32 BoneIndex)
SetBoneWeight()
void FSkinWeightDataVertexBuffer::SetBoneWeight (uint32 VertexWeightOffset, uint32 VertexInfluenceCount, uint32 InfluenceIndex, uint16 BoneWeight)
SetMaxBoneInfluences()
void FSkinWeightDataVertexBuffer::SetMaxBoneInfluences (uint32 InMaxBoneInfluences)
Set if this will have extra streams for bone indices & weights.
SetMetaData()
void FSkinWeightDataVertexBuffer::SetMetaData (uint32 InNumVertices, uint32 InMaxBoneInfluences, bool bInUse16BitBoneIndex, bool bInUse16BitBoneWeight)
SetNeedsCPUAccess()
FORCEINLINE void FSkinWeightDataVertexBuffer::SetNeedsCPUAccess (bool bInNeedsCPUAccess) inline
Set if the CPU needs access to this vertex buffer.
Definition at line 261 of file SkinWeightVertexBuffer.h.
References bNeedsCPUAccess, and FORCEINLINE.
SetUse16BitBoneIndex()
FORCEINLINE void FSkinWeightDataVertexBuffer::SetUse16BitBoneIndex (bool bInUse16BitBoneIndex) inline
Definition at line 276 of file SkinWeightVertexBuffer.h.
References bUse16BitBoneIndex, and FORCEINLINE.
SetUse16BitBoneWeight()
void FSkinWeightDataVertexBuffer::SetUse16BitBoneWeight (bool bInUse16BitBoneWeight) inline
Definition at line 282 of file SkinWeightVertexBuffer.h.
References bUse16BitBoneWeight.
Use16BitBoneIndex()
FORCEINLINE bool FSkinWeightDataVertexBuffer::Use16BitBoneIndex () const inline
Definition at line 279 of file SkinWeightVertexBuffer.h.
References bUse16BitBoneIndex, and FORCEINLINE.
Referenced by GetBoneIndexByteSize().
Use16BitBoneWeight()
bool FSkinWeightDataVertexBuffer::Use16BitBoneWeight () const inline
Definition at line 285 of file SkinWeightVertexBuffer.h.
References bUse16BitBoneWeight.
Referenced by GetBoneWeightByteSize().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FSkinWeightDataVertexBuffer & VertexBuffer) friend
References FSkinWeightDataVertexBuffer(), Ar, and VertexBuffer.
Field Documentation
bNeedsCPUAccess
bool FSkinWeightDataVertexBuffer::bNeedsCPUAccess private
true if this vertex buffer will be used with CPU skinning.
Resource arrays are set to cpu accessible if this is true
Definition at line 333 of file SkinWeightVertexBuffer.h.
Referenced by GetNeedsCPUAccess(), and SetNeedsCPUAccess().
bUse16BitBoneIndex
bool FSkinWeightDataVertexBuffer::bUse16BitBoneIndex private
Use 16 bit bone index instead of 8 bit.
Definition at line 341 of file SkinWeightVertexBuffer.h.
Referenced by SetUse16BitBoneIndex(), and Use16BitBoneIndex().
bUse16BitBoneWeight
bool FSkinWeightDataVertexBuffer::bUse16BitBoneWeight private
Use 16 bit bone weight instead of 8 bit.
Definition at line 344 of file SkinWeightVertexBuffer.h.
Referenced by SetUse16BitBoneWeight(), and Use16BitBoneWeight().
bVariableBonesPerVertex
bool FSkinWeightDataVertexBuffer::bVariableBonesPerVertex private
Definition at line 335 of file SkinWeightVertexBuffer.h.
Referenced by GetPixelFormat(), GetPixelFormatStride(), and GetVariableBonesPerVertex().
Data
uint8* FSkinWeightDataVertexBuffer::Data private
The cached vertex data pointer.
Definition at line 350 of file SkinWeightVertexBuffer.h.
Referenced by GetWeightData(), and GetWeightData().
MaxBoneInfluences
uint32 FSkinWeightDataVertexBuffer::MaxBoneInfluences private
Has extra bone influences per Vertex, which means using a different TGPUSkinVertexBase.
Definition at line 338 of file SkinWeightVertexBuffer.h.
Referenced by GetConstantInfluencesBoneWeightsOffset(), GetConstantInfluencesVertexStride(), and GetMaxBoneInfluences().
NumBoneWeights
uint32 FSkinWeightDataVertexBuffer::NumBoneWeights private
Total number of bone weights across all vertices.
Definition at line 356 of file SkinWeightVertexBuffer.h.
Referenced by GetNumBoneWeights(), and GetVertexDataSize().
NumVertices
uint32 FSkinWeightDataVertexBuffer::NumVertices private
The cached number of vertices.
Definition at line 353 of file SkinWeightVertexBuffer.h.
Referenced by GetNumVertices().
SRVValue
FShaderResourceViewRHIRef FSkinWeightDataVertexBuffer::SRVValue protected
Definition at line 321 of file SkinWeightVertexBuffer.h.
Referenced by GetSRV().
WeightData
FStaticMeshVertexDataInterface* FSkinWeightDataVertexBuffer::WeightData private
The vertex data storage type.
Definition at line 347 of file SkinWeightVertexBuffer.h.
The documentation for this class was generated from the following file:
SkinWeightVertexBuffer.h