Unreal Engine 5.6 C++ API: UE::Geometry::FCubeGrid Class Reference
UE::Geometry::FCubeGrid Class Reference
Class representing an adjustable and resizable power-of-two grid in which faces can be selected.
#include "CubeGrid.h"
Data Structures
class FCubeFace
A face always refers to coordinates in the grid space.
Public Types
enum class EFaceDirection : int8 {
NegativeX = -1 , PositiveX = 1 , NegativeY = -2 , PositiveY = 2 ,
NegativeZ = -3 , PositiveZ = 3
}
Direction that a face is facing.
enum class EPowerMode : int8 { PowerOfTwo , FiveAndTen }
Public Member Functions
FCubeGrid ()
virtual ~FCubeGrid ()=default
double GetBaseGridCellSize () const
MODELINGCOMPONENTS_API double GetCellSize (uint8 GridPower) const
double GetCurrentGridCellSize () const
const FFrame3d & GetFrame () const
FTransform GetFTransform () const
uint8 GetGridPower () const
EPowerMode GetGridPowerMode () const
virtual MODELINGCOMPONENTS_API bool GetHitGridFaceBasedOnRay (const FVector3d &WorldHitPoint, const FVector3d &NormalOrTowardCameraRay, FCubeGrid::FCubeFace &FaceOut, bool bPierceToBack, double PlaneTolerance) const
uint8 GetMaxGridPower () const
void SetBaseGridCellSize (double SizeIn)
MODELINGCOMPONENTS_API void SetCurrentGridCellSize (double SizeIn)
void SetGridFrame (const FFrame3d &FrameIn)
void SetGridPower (uint8 PowerIn)
void SetGridPowerMode (EPowerMode PowerModeIn)
FVector3d ToGridPoint (FVector3d WorldPoint) const
FVector3d ToWorldPoint (FVector3d GridPoint) const
FVector3d ToWorldPoint (FVector3d GridPoint, uint8 GridPower) const
Static Public Member Functions
static int8 DirToFlatDim (EFaceDirection DirectionIn)
Convert face direction to the index of the nonzero normal dimension, or equivalently, the dimension in which that face is flat.
static FVector3d DirToNormal (EFaceDirection DirectionIn)
Convert face direction to its normal.
static EFaceDirection FlipDir (EFaceDirection DirectionIn)
Get flipped version of a face direction.
Protected Member Functions
void UpdateCellSize ()
Protected Attributes
double BaseGridCellSize
double CurrentCellSize
uint8 CurrentGridPower
FFrame3d GridFrame
EPowerMode GridPowerMode = EPowerMode::PowerOfTwo
Detailed Description
Class representing an adjustable and resizable power-of-two grid in which faces can be selected.
Definition at line 20 of file CubeGrid.h.
Member Enumeration Documentation
EFaceDirection
enum class UE::Geometry::FCubeGrid::EFaceDirection : int8 strong
Direction that a face is facing.
Values are set up like in IndexUtil, such that abs(value)-1 is the nonzero normal direction, and sign(value) is the sign of the normal.
Enumerator
NegativeX
PositiveX
NegativeY
PositiveY
NegativeZ
PositiveZ
Definition at line 30 of file CubeGrid.h.
EPowerMode
enum class UE::Geometry::FCubeGrid::EPowerMode : int8 strong
Enumerator
PowerOfTwo
FiveAndTen
Definition at line 40 of file CubeGrid.h.
Constructor & Destructor Documentation
~FCubeGrid()
virtual UE::Geometry::FCubeGrid::~FCubeGrid () virtual default
FCubeGrid()
UE::Geometry::FCubeGrid::FCubeGrid () inline
Definition at line 112 of file CubeGrid.h.
References BaseGridCellSize, CurrentGridPower, and UpdateCellSize().
Member Function Documentation
DirToFlatDim()
int8 UE::Geometry::FCubeGrid::DirToFlatDim (EFaceDirection DirectionIn) inline static
Convert face direction to the index of the nonzero normal dimension, or equivalently, the dimension in which that face is flat.
Definition at line 50 of file CubeGrid.h.
Referenced by DirToNormal().
DirToNormal()
FVector3d UE::Geometry::FCubeGrid::DirToNormal (EFaceDirection DirectionIn) inline static
Convert face direction to its normal.
Definition at line 56 of file CubeGrid.h.
References DirToFlatDim(), UE::Geometry::Normal, and UE::Math::TVector< double >::Zero().
Referenced by UE::Geometry::FCubeGrid::FCubeFace::GetNormal().
FlipDir()
EFaceDirection UE::Geometry::FCubeGrid::FlipDir (EFaceDirection DirectionIn) inline static
Get flipped version of a face direction.
Definition at line 64 of file CubeGrid.h.
GetBaseGridCellSize()
double UE::Geometry::FCubeGrid::GetBaseGridCellSize () const inline
Definition at line 142 of file CubeGrid.h.
References BaseGridCellSize.
GetCellSize()
MODELINGCOMPONENTS_API double UE::Geometry::FCubeGrid::GetCellSize (uint8 GridPower) const
References UE_API.
Referenced by ToWorldPoint(), and UpdateCellSize().
GetCurrentGridCellSize()
double UE::Geometry::FCubeGrid::GetCurrentGridCellSize () const inline
Definition at line 153 of file CubeGrid.h.
References CurrentCellSize.
Referenced by GetFTransform().
GetFrame()
const FFrame3d & UE::Geometry::FCubeGrid::GetFrame () const inline
Definition at line 180 of file CubeGrid.h.
References GridFrame.
GetFTransform()
FTransform UE::Geometry::FCubeGrid::GetFTransform () const inline
Definition at line 173 of file CubeGrid.h.
References FVector, GetCurrentGridCellSize(), GridFrame, and UE::Math::TTransform< T >::SetScale3D().
GetGridPower()
uint8 UE::Geometry::FCubeGrid::GetGridPower () const inline
Definition at line 123 of file CubeGrid.h.
References CurrentGridPower.
GetGridPowerMode()
EPowerMode UE::Geometry::FCubeGrid::GetGridPowerMode () const inline
Definition at line 140 of file CubeGrid.h.
References GridPowerMode.
GetHitGridFaceBasedOnRay()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FCubeGrid::GetHitGridFaceBasedOnRay (const FVector3d & WorldHitPoint, const FVector3d & NormalOrTowardCameraRay, FCubeGrid::FCubeFace & FaceOut, bool bPierceToBack, double PlaneTolerance) const virtual
References UE_API.
GetMaxGridPower()
uint8 UE::Geometry::FCubeGrid::GetMaxGridPower () const inline
Definition at line 131 of file CubeGrid.h.
Referenced by SetGridPower().
SetBaseGridCellSize()
void UE::Geometry::FCubeGrid::SetBaseGridCellSize (double SizeIn) inline
Definition at line 143 of file CubeGrid.h.
References BaseGridCellSize, ensure, KINDA_SMALL_NUMBER, and UpdateCellSize().
SetCurrentGridCellSize()
MODELINGCOMPONENTS_API void UE::Geometry::FCubeGrid::SetCurrentGridCellSize (double SizeIn)
References UE_API.
SetGridFrame()
void UE::Geometry::FCubeGrid::SetGridFrame (const FFrame3d & FrameIn) inline
Definition at line 181 of file CubeGrid.h.
References GridFrame.
SetGridPower()
void UE::Geometry::FCubeGrid::SetGridPower (uint8 PowerIn) inline
Definition at line 125 of file CubeGrid.h.
References CurrentGridPower, ensureMsgf, GetMaxGridPower(), TEXT, and UpdateCellSize().
SetGridPowerMode()
void UE::Geometry::FCubeGrid::SetGridPowerMode (EPowerMode PowerModeIn) inline
Definition at line 135 of file CubeGrid.h.
References GridPowerMode, and UpdateCellSize().
ToGridPoint()
FVector3d UE::Geometry::FCubeGrid::ToGridPoint (FVector3d WorldPoint) const inline
Definition at line 168 of file CubeGrid.h.
References CurrentCellSize, and GridFrame.
ToWorldPoint() [1/2]
FVector3d UE::Geometry::FCubeGrid::ToWorldPoint (FVector3d GridPoint) const inline
Definition at line 158 of file CubeGrid.h.
References CurrentCellSize, and GridFrame.
ToWorldPoint() [2/2]
FVector3d UE::Geometry::FCubeGrid::ToWorldPoint (FVector3d GridPoint, uint8 GridPower) const inline
Definition at line 163 of file CubeGrid.h.
References GetCellSize(), and GridFrame.
UpdateCellSize()
void UE::Geometry::FCubeGrid::UpdateCellSize () inline protected
Definition at line 184 of file CubeGrid.h.
References CurrentCellSize, CurrentGridPower, and GetCellSize().
Referenced by FCubeGrid(), SetBaseGridCellSize(), SetGridPower(), and SetGridPowerMode().
Field Documentation
BaseGridCellSize
double UE::Geometry::FCubeGrid::BaseGridCellSize protected
Definition at line 187 of file CubeGrid.h.
Referenced by FCubeGrid(), GetBaseGridCellSize(), and SetBaseGridCellSize().
CurrentCellSize
double UE::Geometry::FCubeGrid::CurrentCellSize protected
Definition at line 191 of file CubeGrid.h.
Referenced by GetCurrentGridCellSize(), ToGridPoint(), ToWorldPoint(), and UpdateCellSize().
CurrentGridPower
uint8 UE::Geometry::FCubeGrid::CurrentGridPower protected
Definition at line 188 of file CubeGrid.h.
Referenced by FCubeGrid(), GetGridPower(), SetGridPower(), and UpdateCellSize().
GridFrame
FFrame3d UE::Geometry::FCubeGrid::GridFrame protected
Definition at line 186 of file CubeGrid.h.
Referenced by GetFrame(), GetFTransform(), SetGridFrame(), ToGridPoint(), ToWorldPoint(), and ToWorldPoint().
GridPowerMode
EPowerMode UE::Geometry::FCubeGrid::GridPowerMode = EPowerMode::PowerOfTwo protected
Definition at line 189 of file CubeGrid.h.
Referenced by GetGridPowerMode(), and SetGridPowerMode().
The documentation for this class was generated from the following file:
CubeGrid.h