Unreal Engine 5.6 C++ API: FindInBlueprintsHelpers Namespace Reference
FindInBlueprintsHelpers Namespace Reference
Some utility functions to help with Find-in-Blueprint functionality.
Data Structures
struct FSimpleFTextKeyStorage
Functions
FText AsFText (int32 InValue, const TMap< int32, FText > &InLookupTable)
Looks up a JsonValue's FText from the passed lookup table.
FText AsFText (TSharedPtr< FJsonValue > InJsonValue, const TMap< int32, FText > &InLookupTable)
Looks up a JsonValue's FText from the passed lookup table.
KISMET_API bool ConstructSearchTermFromFunction (const UFunction *Function, FString &SearchTerm)
Constructs a search term for a function using Find-in-Blueprints search syntax.
void ExpandAllChildren (FSearchResult InTreeNode, TSharedPtr< STreeView< TSharedPtr< FFindInBlueprintsResult > > > InTreeView)
Iterates through all the given tree node's children and tells the tree view to expand them.
KISMET_API UClass * GetFunctionOriginClass (const UFunction *Function)
Utility function to find the ancestor class or interface from which a function is inherited.
FString GetPinTypeAsString (const FEdGraphPinType &InPinType)
Retrieves the pin type as a string value.
static uint32 GetTypeHash (const FindInBlueprintsHelpers::FSimpleFTextKeyStorage &InObject)
bool IsTextEqualToString (const FText &InText, const FString &InString)
bool ParsePinType (FText InKey, FText InValue, FEdGraphPinType &InOutPinType)
Parses a pin type from passed in key names and values.
Detailed Description
Some utility functions to help with Find-in-Blueprint functionality.
Function Documentation
AsFText() [1/2]
FText FindInBlueprintsHelpers::AsFText (int32 InValue, const TMap< int32, FText > & InLookupTable)
Looks up a JsonValue's FText from the passed lookup table.
AsFText() [2/2]
FText FindInBlueprintsHelpers::AsFText (TSharedPtr< FJsonValue > InJsonValue, const TMap< int32, FText > & InLookupTable)
Looks up a JsonValue's FText from the passed lookup table.
ConstructSearchTermFromFunction()
KISMET_API bool FindInBlueprintsHelpers::ConstructSearchTermFromFunction (const UFunction * Function, FString & SearchTerm)
Constructs a search term for a function using Find-in-Blueprints search syntax.
References Function.
ExpandAllChildren()
void FindInBlueprintsHelpers::ExpandAllChildren (FSearchResult InTreeNode, TSharedPtr< STreeView< TSharedPtr< FFindInBlueprintsResult > > > InTreeView)
Iterates through all the given tree node's children and tells the tree view to expand them.
GetFunctionOriginClass()
KISMET_API UClass * FindInBlueprintsHelpers::GetFunctionOriginClass (const UFunction * Function)
Utility function to find the ancestor class or interface from which a function is inherited.
References Function.
GetPinTypeAsString()
FString FindInBlueprintsHelpers::GetPinTypeAsString (const FEdGraphPinType & InPinType)
Retrieves the pin type as a string value.
Parameters
InPinType The pin type to look at
Returns
The pin type as a string in format [category]'[sub-category object]'
GetTypeHash()
uint32 FindInBlueprintsHelpers::GetTypeHash (const FindInBlueprintsHelpers::FSimpleFTextKeyStorage & InObject) static
Definition at line 85 of file FindInBlueprints.h.
References FText::BuildSourceString(), GetTypeHash(), and FindInBlueprintsHelpers::FSimpleFTextKeyStorage::Text.
Referenced by GetTypeHash().
IsTextEqualToString()
bool FindInBlueprintsHelpers::IsTextEqualToString (const FText & InText, const FString & InString)
ParsePinType()
bool FindInBlueprintsHelpers::ParsePinType (FText InKey, FText InValue, FEdGraphPinType & InOutPinType)
Parses a pin type from passed in key names and values.
Parameters
InKey The key name for what the data should be translated as
InValue Value to be be translated
InOutPinType Modifies the PinType based on the passed parameters, building it up over multiple calls
Returns
TRUE when the parsing is successful