Unreal Engine 5.6 C++ API: UE::Geometry::FCompactMaps Class Reference
UE::Geometry::FCompactMaps Class Reference
Stores index remapping for vertices and triangles.
#include "CompactMaps.h"
Public Member Functions
int32 GetTriangleMapping (int32 FromID) const
Get mapping for a triangle.
FIndex3i GetVertexMapping (FIndex3i FromIDs) const
Get mapping for three vertices, e.g.
int32 GetVertexMapping (int32 FromID) const
Get mapping for a vertex.
int32 NumTriangleMappings () const
Get number of triangle mappings.
int32 NumVertexMappings () const
Get number of vertex mappings.
void Reset ()
Reset all maps, leaving them empty.
void Reset (int32 NumVertMappings, int32 NumTriMappings, bool bInitializeWithInvalidID)
Resize vertex and triangle maps, and initialize with InvalidID.
void ResetTriangleMap (int32 NumTriMappings, bool bInitializeWithInvalidID)
Resize triangle map, and optionally initialize with InvalidID.
void ResetVertexMap (int32 NumVertMappings, bool bInitializeWithInvalidID)
Resize vertex map, and optionally initialize with InvalidID.
void SetIdentity (int32 NumVertMappings, int32 NumTriMappings)
Set up maps as identity maps.
void SetIdentityTriangleMap (int32 NumTriMappings)
Set up triangle map as identity map.
void SetIdentityVertexMap (int32 NumVertMappings)
Set up vertex map as identity map.
void SetTriangleMapping (int32 FromID, int32 ToID)
Set mapping for a triangle.
void SetVertexMapping (int32 FromID, int32 ToID)
Set mapping for a vertex.
bool TriangleMapIsSet () const
Returns true if there are triangle mappings.
bool Validate () const
Check data for validity; for testing.
bool VertexMapIsSet () const
Returns true if there are vertex mappings.
Static Public Attributes
static constexpr int32 InvalidID = IndexConstants::InvalidID
Private Attributes
TArray< int32 > TriMap
TArray< int32 > VertMap
Detailed Description
Stores index remapping for vertices and triangles.
Should only be used for compacting, and should maintain invariant that *Map[Idx] <= Idx for all maps
Definition at line 19 of file CompactMaps.h.
Member Function Documentation
GetTriangleMapping()
int32 UE::Geometry::FCompactMaps::GetTriangleMapping (int32 FromID) const inline
Get mapping for a triangle.
Definition at line 171 of file CompactMaps.h.
References TriMap.
Referenced by UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactCopy(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactInPlace(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Serialize().
GetVertexMapping() [1/2]
FIndex3i UE::Geometry::FCompactMaps::GetVertexMapping (FIndex3i FromIDs) const inline
Get mapping for three vertices, e.g.
a triangle
Definition at line 165 of file CompactMaps.h.
References VertMap.
GetVertexMapping() [2/2]
int32 UE::Geometry::FCompactMaps::GetVertexMapping (int32 FromID) const inline
Get mapping for a vertex.
Definition at line 159 of file CompactMaps.h.
References VertMap.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactInPlace(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactInPlace(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize().
NumTriangleMappings()
int32 UE::Geometry::FCompactMaps::NumTriangleMappings () const inline
Get number of triangle mappings.
Definition at line 139 of file CompactMaps.h.
References TriMap.
Referenced by UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactCopy(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactInPlace().
NumVertexMappings()
int32 UE::Geometry::FCompactMaps::NumVertexMappings () const inline
Get number of vertex mappings.
Definition at line 133 of file CompactMaps.h.
References VertMap.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactInPlace(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactInPlace().
Reset() [1/2]
void UE::Geometry::FCompactMaps::Reset () inline
Reset all maps, leaving them empty.
Definition at line 114 of file CompactMaps.h.
References TriMap, and VertMap.
Reset() [2/2]
void UE::Geometry::FCompactMaps::Reset (int32 NumVertMappings, int32 NumTriMappings, bool bInitializeWithInvalidID) inline
Resize vertex and triangle maps, and initialize with InvalidID.
Parameters
NumVertMappings Size of post-reset vertex map
NumTriMappings Size of post-reset triangle map
bInitializeWithInvalidID If true, initializes maps with InvalidID
Definition at line 73 of file CompactMaps.h.
References ResetTriangleMap(), and ResetVertexMap().
ResetTriangleMap()
void UE::Geometry::FCompactMaps::ResetTriangleMap (int32 NumTriMappings, bool bInitializeWithInvalidID) inline
Resize triangle map, and optionally initialize with InvalidID.
Parameters
NumTriMappings Size of post-reset triangle map
bInitializeWithInvalidID If true, initializes map with InvalidID
Definition at line 101 of file CompactMaps.h.
References InvalidID, and TriMap.
Referenced by Reset().
ResetVertexMap()
void UE::Geometry::FCompactMaps::ResetVertexMap (int32 NumVertMappings, bool bInitializeWithInvalidID) inline
Resize vertex map, and optionally initialize with InvalidID.
Parameters
NumVertMappings Size of post-reset vertex map
bInitializeWithInvalidID If true, initializes map with InvalidID
Definition at line 84 of file CompactMaps.h.
References InvalidID, and VertMap.
Referenced by Reset().
SetIdentity()
void UE::Geometry::FCompactMaps::SetIdentity (int32 NumVertMappings, int32 NumTriMappings) inline
Set up maps as identity maps.
Parameters
NumVertMappings Vertex map will be created from 0 to NumVertMappings - 1
NumTriMappings Triangle map will be created from 0 to NumTriMappings - 1
Definition at line 33 of file CompactMaps.h.
References SetIdentityTriangleMap(), and SetIdentityVertexMap().
SetIdentityTriangleMap()
void UE::Geometry::FCompactMaps::SetIdentityTriangleMap (int32 NumTriMappings) inline
Set up triangle map as identity map.
Parameters
NumTriMappings Vertex map will be created from 0 to NumTriMappings - 1
Definition at line 58 of file CompactMaps.h.
References TriMap.
Referenced by SetIdentity().
SetIdentityVertexMap()
void UE::Geometry::FCompactMaps::SetIdentityVertexMap (int32 NumVertMappings) inline
Set up vertex map as identity map.
Parameters
NumVertMappings Vertex map will be created from 0 to NumVertMappings - 1
Definition at line 44 of file CompactMaps.h.
References VertMap.
Referenced by SetIdentity().
SetTriangleMapping()
void UE::Geometry::FCompactMaps::SetTriangleMapping (int32 FromID, int32 ToID) inline
Set mapping for a triangle.
Definition at line 152 of file CompactMaps.h.
References checkSlow, and TriMap.
SetVertexMapping()
void UE::Geometry::FCompactMaps::SetVertexMapping (int32 FromID, int32 ToID) inline
Set mapping for a vertex.
Definition at line 145 of file CompactMaps.h.
References checkSlow, and VertMap.
TriangleMapIsSet()
bool UE::Geometry::FCompactMaps::TriangleMapIsSet () const inline
Returns true if there are triangle mappings.
Definition at line 127 of file CompactMaps.h.
References TriMap.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Serialize().
Validate()
bool UE::Geometry::FCompactMaps::Validate () const inline
Check data for validity; for testing.
Definition at line 177 of file CompactMaps.h.
References TriMap, and VertMap.
VertexMapIsSet()
bool UE::Geometry::FCompactMaps::VertexMapIsSet () const inline
Returns true if there are vertex mappings.
Definition at line 121 of file CompactMaps.h.
References VertMap.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize().
Field Documentation
InvalidID
int32 UE::Geometry::FCompactMaps::InvalidID = IndexConstants::InvalidID static constexpr
Definition at line 25 of file CompactMaps.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactInPlace(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactInPlace(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CompactInPlace(), ResetTriangleMap(), ResetVertexMap(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Serialize(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize(), and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize().
TriMap
TArray<int32> UE::Geometry::FCompactMaps::TriMap private
Definition at line 22 of file CompactMaps.h.
Referenced by GetTriangleMapping(), NumTriangleMappings(), Reset(), ResetTriangleMap(), SetIdentityTriangleMap(), SetTriangleMapping(), TriangleMapIsSet(), and Validate().
VertMap
TArray<int32> UE::Geometry::FCompactMaps::VertMap private
Definition at line 21 of file CompactMaps.h.
Referenced by GetVertexMapping(), GetVertexMapping(), NumVertexMappings(), Reset(), ResetVertexMap(), SetIdentityVertexMap(), SetVertexMapping(), Validate(), and VertexMapIsSet().
The documentation for this class was generated from the following file:
CompactMaps.h