Unreal Engine 5.6 C++ API: FPathFollowingResult Struct Reference
FPathFollowingResult Struct Reference
#include "PathFollowingComponent.h"
Public Member Functions
FPathFollowingResult ()
AIMODULE_API FPathFollowingResult (EPathFollowingResult::Type ResultCode, FPathFollowingResultFlags::Type ExtraFlags)
AIMODULE_API FPathFollowingResult (FPathFollowingResultFlags::Type InFlags)
bool HasFlag (FPathFollowingResultFlags::Type Flag) const
bool IsFailure () const
bool IsInterrupted () const
bool IsSuccess () const
AIMODULE_API FString ToString () const
Data Fields
TEnumAsByte< EPathFollowingResult::Type > Code
FPathFollowingResultFlags::Type Flags
Detailed Description
Definition at line 121 of file PathFollowingComponent.h.
Constructor & Destructor Documentation
FPathFollowingResult() [1/3]
FPathFollowingResult::FPathFollowingResult () inline
Definition at line 126 of file PathFollowingComponent.h.
References Code, Flags, and Invalid.
FPathFollowingResult() [2/3]
AIMODULE_API FPathFollowingResult::FPathFollowingResult (FPathFollowingResultFlags::Type InFlags)
FPathFollowingResult() [3/3]
AIMODULE_API FPathFollowingResult::FPathFollowingResult (EPathFollowingResult::Type ResultCode, FPathFollowingResultFlags::Type ExtraFlags)
Member Function Documentation
HasFlag()
bool FPathFollowingResult::HasFlag (FPathFollowingResultFlags::Type Flag) const inline
Definition at line 130 of file PathFollowingComponent.h.
References Flags.
Referenced by IsFailure(), IsInterrupted(), and IsSuccess().
IsFailure()
bool FPathFollowingResult::IsFailure () const inline
Definition at line 133 of file PathFollowingComponent.h.
References HasFlag(), and FPathFollowingResultFlags::Success.
IsInterrupted()
bool FPathFollowingResult::IsInterrupted () const inline
Definition at line 134 of file PathFollowingComponent.h.
References HasFlag(), FPathFollowingResultFlags::NewRequest, and FPathFollowingResultFlags::UserAbort.
IsSuccess()
bool FPathFollowingResult::IsSuccess () const inline
Definition at line 132 of file PathFollowingComponent.h.
References HasFlag(), and FPathFollowingResultFlags::Success.
ToString()
AIMODULE_API FString FPathFollowingResult::ToString () const
Field Documentation
Code
TEnumAsByte<EPathFollowingResult::Type> FPathFollowingResult::Code
Definition at line 124 of file PathFollowingComponent.h.
Referenced by FPathFollowingResult().
Flags
FPathFollowingResultFlags::Type FPathFollowingResult::Flags
Definition at line 123 of file PathFollowingComponent.h.
Referenced by FPathFollowingResult(), and HasFlag().
The documentation for this struct was generated from the following file:
PathFollowingComponent.h