Unreal Engine 5.6 C++ API: FLoggedPlatformFile Class Reference
FLoggedPlatformFile Class Reference
#include "IPlatformFileLogWrapper.h"
Data Structures
class FLogStatVisitor
class FLogVisitor
Public Member Functions
FLoggedPlatformFile ()
virtual bool CopyFile (const TCHAR *To, const TCHAR *From, EPlatformFileRead ReadFlags=EPlatformFileRead::None, EPlatformFileWrite WriteFlags=EPlatformFileWrite::None) override
Copy a file.
virtual bool CreateDirectory (const TCHAR *Directory) override
Create a directory and return true if the directory was created or already existed.
virtual bool DeleteDirectory (const TCHAR *Directory) override
Delete a directory and return true if the directory was deleted or otherwise does not exist.
virtual bool DeleteDirectoryRecursively (const TCHAR *Directory) override
Delete all files and subdirectories in a directory, then delete the directory itself.
virtual bool DeleteFile (const TCHAR *Filename) override
Delete a file and return true if the file exists.
virtual bool DirectoryExists (const TCHAR *Directory) override
Return true if the directory exists.
virtual bool FileExists (const TCHAR *Filename) override
Return true if the file exists.
virtual int64 FileSize (const TCHAR *Filename) override
Return the size of the file, or -1 if it doesn't exist.
virtual FDateTime GetAccessTimeStamp (const TCHAR *Filename) override
Return the last access time of a file.
virtual FString GetFilenameOnDisk (const TCHAR *Filename) override
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
IPlatformFile * GetLowerLevel () override
Gets the platform file wrapped by this file.
virtual const TCHAR * GetName () const override
Gets this platform file type name.
virtual FFileStatData GetStatData (const TCHAR *FilenameOrDirectory) override
Return the stat data for the given file or directory.
virtual FDateTime GetTimeStamp (const TCHAR *Filename) override
Return the modification time of a file.
void HandleDumpCommand (const TCHAR *Cmd, FOutputDevice &Ar)
virtual bool Initialize (IPlatformFile *Inner, const TCHAR *CommandLineParam) override
Initializes platform file.
virtual bool IsReadOnly (const TCHAR *Filename) override
Return true if the file is read only.
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
virtual bool IterateDirectory (const TCHAR *Directory, IPlatformFile::FDirectoryVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStat (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, IPlatformFile::FDirectoryStatVisitor &Visitor) override
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool MoveFile (const TCHAR *To, const TCHAR *From) override
Attempt to move a file.
void OnHandleClosed (const FString &Filename)
void OnHandleOpen (const FString &Filename)
virtual IAsyncReadFileHandle * OpenAsyncRead (const TCHAR *Filename, bool bAllowWrite=false) override
Open a file for async reading.
virtual FOpenMappedResult OpenMappedEx (const TCHAR *Filename, EOpenReadFlags OpenOptions=EOpenReadFlags::None, int64 MaximumSize=0) override
Open a file for async reading.
virtual IFileHandle * OpenRead (const TCHAR *Filename, bool bAllowWrite) override
Attempt to open a file for reading.
virtual IFileHandle * OpenWrite (const TCHAR *Filename, bool bAppend=false, bool bAllowRead=false) override
Attempt to open a file for writing.
virtual void SetAsyncMinimumPriority (EAsyncIOPriorityAndFlags Priority) override
Controls if the pak precacher should process precache requests.
virtual void SetLowerLevel (IPlatformFile *NewLowerLevel) override
Sets the platform file wrapped by this file.
virtual bool SetReadOnly (const TCHAR *Filename, bool bNewReadOnlyValue) override
Attempt to change the read only status of a file.
virtual void SetTimeStamp (const TCHAR *Filename, FDateTime DateTime) override
Sets the modification time of a file.
virtual bool ShouldBeUsed (IPlatformFile *Inner, const TCHAR *CmdLine) const override
Checks if this platform file should be used even though it was not asked to be.
Public Member Functions inherited from IPlatformFile
IPlatformFile ()
Constructor/Destructor.
virtual ~IPlatformFile ()
virtual void AddLocalDirectories (TArray< FString > &LocalDirectories)
Identifies any platform specific paths that are guaranteed to be local (i.e.
virtual void BypassSecurity (bool bInBypass)
virtual FString ConvertToAbsolutePathForExternalAppForRead (const TCHAR *Filename)
Converts passed in filename to use an absolute path (for reading).
virtual FString ConvertToAbsolutePathForExternalAppForWrite (const TCHAR *Filename)
Converts passed in filename to use an absolute path (for writing)
virtual bool CopyDirectoryTree (const TCHAR *DestinationDirectory, const TCHAR *Source, bool bOverwriteAllExisting)
Copy a file or a hierarchy of files (directory).
virtual bool CreateDirectoryTree (const TCHAR *Directory)
Create a directory, including any parent directories and return true if the directory was created or already existed.
virtual bool DeleteFiles (const TArrayView< const TCHAR * > &Filenames)
Delete an array of files and return true if ALL deletes are succeeded.
virtual bool DoesCreatePublicFiles ()
Checks to see if this file system creates publicly accessible files.
virtual FFileJournalData FileJournalGetFileData (const TCHAR *FilenameOrDirectory, FString *OutError=nullptr)
Return the data for the given path as with GetStatData, but report a FFileJournalData instead, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalGetLatestEntry (const TCHAR *VolumeName, FFileJournalId &OutJournalId, FFileJournalEntryHandle &OutEntryHandle, FString *OutError=nullptr)
Report the current end of the journal for the given volume, to be used as the StartingJournalEntry in FileJournalGetModifiedDirectories.
virtual uint64 FileJournalGetMaximumSize (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr) const
Return the maximum size of the FileJournal for the specified VolumeName, if available, zero otherwise.
virtual FString FileJournalGetVolumeName (FStringView InPath)
Return the VolumeSpecifier present in the given path.
virtual bool FileJournalIsAvailable (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr)
Return whether FileJournal functionality is available on the current platform if VolumeName is nullptr or for the given Volume if VolumeName is non-null.
virtual bool FileJournalIterateDirectory (const TCHAR *Directory, FDirectoryJournalVisitorFunc Visitor, FString *OutError=nullptr)
Iterate the given directory as with IterateDirectoryStat, but report a FFileJournalData for each file and directory, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalReadModified (const TCHAR *VolumeName, const FFileJournalId &JournalIdOfStartingEntry, const FFileJournalEntryHandle &StartingJournalEntry, TMap< FFileJournalFileHandle, FString > &KnownDirectories, TSet< FString > &OutModifiedDirectories, FFileJournalEntryHandle &OutNextJournalEntry, FString *OutError=nullptr)
Query the FileJournal to find a list of all directories on the given volume with files that have been added, deleted, or modified in the specified time range.
virtual void FindFiles (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the given directory, with optional file extension filter.
virtual void FindFilesRecursively (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the directory tree, with optional file extension filter.
virtual int64 GetAllowedBytesToWriteThrottledStorage (const TCHAR *DestinationPath=nullptr)
Returns the number of bytes that are currently allowed to be written to throttled write storage (if the platform has such restrictions)
virtual FDateTime GetTimeStampLocal (const TCHAR *Filename)
Return the modification time of a file in the local time of the calling code (GetTimeStamp returns UTC).
virtual void GetTimeStampPair (const TCHAR *PathA, const TCHAR *PathB, FDateTime &OutTimeStampA, FDateTime &OutTimeStampB)
virtual bool HasMarkOfTheWeb (FStringView Filename, FString *OutSourceURL=nullptr)
Determine if the file has been downloaded from a web browser, based on platform-specific metadata.
virtual void InitializeAfterProjectFilePath ()
Performs initialization of the platform file after the project path has been set.
virtual void InitializeAfterSetActive ()
Performs initialization of the platform file after it has become the active (FPlatformFileManager.GetPlatformFile() will return this.
virtual void InitializeNewAsyncIO ()
Performs initialization of the platform file after the new async IO has been enabled.
virtual bool IsSandboxEnabled () const
Returns whether the sandbox is enabled or not.
virtual ESymlinkResult IsSymlink (const TCHAR *Filename)
Return true if the file is a symbolic link.
virtual void MakeUniquePakFilesForTheseFiles (const TArray< TArray< FString > > &InFiles)
Build an in memory unique pak file from a subset of files in this pak file.
virtual FFileOpenAsyncResult OpenAsyncRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file for async reading.
virtual FFileOpenResult OpenRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file handle for reading.
virtual IFileHandle * OpenReadNoBuffering (const TCHAR *Filename, bool bAllowWrite=false)
virtual bool SendMessageToServer (const TCHAR *Message, IFileServerMessageHandler *Handler)
Sends a message to the file server, and will block until it's complete.
virtual void SetCreatePublicFiles (bool bCreatePublicFiles)
Sets file system to create publicly accessible files or not.
virtual bool SetMarkOfTheWeb (FStringView Filename, bool bNewStatus, const FString *InSourceURL=nullptr)
Attempt to change the platform-specific metadata that indicates if the file has been downloaded from a web browser.
virtual void SetSandboxEnabled (bool bInEnabled)
Set whether the sandbox is enabled or not.
virtual void Tick ()
Platform file can override this to get a regular tick from the engine.
UE_DEPRECATED (5.6, "Please use OpenMappedEx instead") 1 virtual IMappedFileHandle *OpenMapped(const TCHAR *Filename)
Open a file for async reading.
Static Public Member Functions
static const TCHAR * GetTypeName ()
Static Public Member Functions inherited from IPlatformFile
static const TCHAR * GetPhysicalTypeName ()
Returns the name of the physical platform file type.
static IPlatformFile & GetPlatformPhysical ()
Physical file system of the platform, never wrapped.
Private Attributes
FCriticalSection LogFileCritical
IPlatformFile * LowerLevel
TMap< FString, int32 > OpenHandles
Additional Inherited Members
Public Types inherited from IPlatformFile
enum class EOpenReadFlags : uint8 { None = 0 , AllowWrite = 1 << 0 , AllowDelete = 1 << 1 }
Flags to be used when opening a file for reading via IPlatformFile::OpenRead.
typedef TFunctionRef< bool(const TCHAR *, const FFileJournalData &)> FDirectoryJournalVisitorFunc
File and directory visitor function that takes FileJournal data.
typedef TFunctionRef< bool(const TCHAR *, const FFileStatData &)> FDirectoryStatVisitorFunc
File and directory visitor function that takes all the stat data.
typedef TFunctionRef< bool(const TCHAR *, bool)> FDirectoryVisitorFunc
File and directory visitor function that takes only the name.
Detailed Description
Definition at line 145 of file IPlatformFileLogWrapper.h.
Constructor & Destructor Documentation
FLoggedPlatformFile()
FLoggedPlatformFile::FLoggedPlatformFile () inline
Definition at line 160 of file IPlatformFileLogWrapper.h.
References LowerLevel.
Member Function Documentation
CopyFile()
virtual bool FLoggedPlatformFile::CopyFile (const TCHAR * To, const TCHAR * From, EPlatformFileRead ReadFlags = EPlatformFileRead::None, EPlatformFileWrite WriteFlags = EPlatformFileWrite::None) inline override virtual
Copy a file.
This will fail if the destination file already exists.
Parameters
To File to copy to.
From File to copy from.
ReadFlags Source file read options.
WriteFlags Destination file write options.
Returns
true if the file was copied successfully.
Reimplemented from IPlatformFile.
Definition at line 464 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, None, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
CreateDirectory()
virtual bool FLoggedPlatformFile::CreateDirectory (const TCHAR * Directory) inline override virtual
Create a directory and return true if the directory was created or already existed.
Implements IPlatformFile.
Definition at line 331 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
DeleteDirectory()
virtual bool FLoggedPlatformFile::DeleteDirectory (const TCHAR * Directory) inline override virtual
Delete a directory and return true if the directory was deleted or otherwise does not exist.
Implements IPlatformFile.
Definition at line 342 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
DeleteDirectoryRecursively()
virtual bool FLoggedPlatformFile::DeleteDirectoryRecursively (const TCHAR * Directory) inline override virtual
Delete all files and subdirectories in a directory, then delete the directory itself.
Parameters
Directory The directory to delete.
Returns
true if the directory was deleted or did not exist.
Reimplemented from IPlatformFile.
Definition at line 453 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
DeleteFile()
virtual bool FLoggedPlatformFile::DeleteFile (const TCHAR * Filename) inline override virtual
Delete a file and return true if the file exists.
Will not delete read only files.
Implements IPlatformFile.
Definition at line 210 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
DirectoryExists()
virtual bool FLoggedPlatformFile::DirectoryExists (const TCHAR * Directory) inline override virtual
Return true if the directory exists.
Implements IPlatformFile.
Definition at line 320 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
FileExists()
virtual bool FLoggedPlatformFile::FileExists (const TCHAR * Filename) inline override virtual
Return true if the file exists.
Implements IPlatformFile.
Definition at line 188 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
FileSize()
virtual int64 FLoggedPlatformFile::FileSize (const TCHAR * Filename) inline override virtual
Return the size of the file, or -1 if it doesn't exist.
Implements IPlatformFile.
Definition at line 199 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
GetAccessTimeStamp()
virtual FDateTime FLoggedPlatformFile::GetAccessTimeStamp (const TCHAR * Filename) inline override virtual
Return the last access time of a file.
Returns FDateTime::MinValue() on failure
Implements IPlatformFile.
Definition at line 275 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
GetFilenameOnDisk()
virtual FString FLoggedPlatformFile::GetFilenameOnDisk (const TCHAR * Filename) inline override virtual
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
Implements IPlatformFile.
Definition at line 286 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
GetLowerLevel()
IPlatformFile * FLoggedPlatformFile::GetLowerLevel () inline override virtual
Gets the platform file wrapped by this file.
Implements IPlatformFile.
Definition at line 175 of file IPlatformFileLogWrapper.h.
References IPlatformFile::IPlatformFile(), and LowerLevel.
GetName()
virtual const TCHAR * FLoggedPlatformFile::GetName () const inline override virtual
Gets this platform file type name.
Implements IPlatformFile.
Definition at line 183 of file IPlatformFileLogWrapper.h.
References GetTypeName().
GetStatData()
virtual FFileStatData FLoggedPlatformFile::GetStatData (const TCHAR * FilenameOrDirectory) inline override virtual
Return the stat data for the given file or directory.
Check the FFileStatData::bIsValid member before using the returned data
Implements IPlatformFile.
Definition at line 353 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
GetTimeStamp()
virtual FDateTime FLoggedPlatformFile::GetTimeStamp (const TCHAR * Filename) inline override virtual
Return the modification time of a file.
Returns FDateTime::MinValue() on failure
Implements IPlatformFile.
Definition at line 254 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
GetTypeName()
const TCHAR * FLoggedPlatformFile::GetTypeName () inline static
Definition at line 155 of file IPlatformFileLogWrapper.h.
References TEXT.
Referenced by GetName().
HandleDumpCommand()
void FLoggedPlatformFile::HandleDumpCommand (const TCHAR * Cmd, FOutputDevice & Ar)
References Ar, and Cmd.
Initialize()
virtual bool FLoggedPlatformFile::Initialize (IPlatformFile * Inner, const TCHAR * CmdLine) override virtual
Initializes platform file.
Parameters
Inner Platform file to wrap by this file.
CmdLine Command line to parse.
Returns
true if the initialization was successful, false otherise.
Implements IPlatformFile.
References IPlatformFile::IPlatformFile().
IsReadOnly()
virtual bool FLoggedPlatformFile::IsReadOnly (const TCHAR * Filename) inline override virtual
Return true if the file is read only.
Implements IPlatformFile.
Definition at line 221 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
IterateDirectory() [1/2]
virtual bool IPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
IterateDirectory() [2/2]
virtual bool FLoggedPlatformFile::IterateDirectory (const TCHAR * Directory, IPlatformFile::FDirectoryVisitor & Visitor) inline override virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IPlatformFile.
Definition at line 384 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
IterateDirectoryRecursively() [1/2]
virtual bool IPlatformFile::IterateDirectoryRecursively (const TCHAR * Directory, FDirectoryVisitorFunc Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
IterateDirectoryRecursively() [2/2]
virtual bool FLoggedPlatformFile::IterateDirectoryRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryVisitor & Visitor) inline override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
Definition at line 396 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
IterateDirectoryStat() [1/2]
virtual bool IPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryStatVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
IterateDirectoryStat() [2/2]
virtual bool FLoggedPlatformFile::IterateDirectoryStat (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitor & Visitor) inline override virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implements IPlatformFile.
Definition at line 428 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
IterateDirectoryStatRecursively() [1/2]
virtual bool IPlatformFile::IterateDirectoryStatRecursively (const TCHAR * Directory, FDirectoryStatVisitorFunc Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryStatVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
IterateDirectoryStatRecursively() [2/2]
virtual bool FLoggedPlatformFile::IterateDirectoryStatRecursively (const TCHAR * Directory, IPlatformFile::FDirectoryStatVisitor & Visitor) inline override virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented from IPlatformFile.
Definition at line 440 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
MoveFile()
virtual bool FLoggedPlatformFile::MoveFile (const TCHAR * To, const TCHAR * From) inline override virtual
Attempt to move a file.
Return true if successful. Will not overwrite existing files.
Implements IPlatformFile.
Definition at line 232 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
OnHandleClosed()
void FLoggedPlatformFile::OnHandleClosed (const FString & Filename) inline
Definition at line 483 of file IPlatformFileLogWrapper.h.
References Filename, LogFileCritical, and OpenHandles.
OnHandleOpen()
void FLoggedPlatformFile::OnHandleOpen (const FString & Filename) inline
Definition at line 477 of file IPlatformFileLogWrapper.h.
References Filename, LogFileCritical, and OpenHandles.
OpenAsyncRead()
virtual IAsyncReadFileHandle * FLoggedPlatformFile::OpenAsyncRead (const TCHAR * Filename, bool bAllowWrite = false) inline override virtual
Open a file for async reading.
This call does not hit the disk or block.
Parameters
Filename file to be opened
bAllowWrite (applies to certain platforms only) whether this file is allowed to be written to by other processes. This flag is needed to open files that are currently being written to as well.
Returns
Close the file by delete'ing the handle. A non-null return value does not mean the file exists, since that may not be determined yet.
Reimplemented from IPlatformFile.
Definition at line 494 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
OpenMappedEx()
virtual FOpenMappedResult FLoggedPlatformFile::OpenMappedEx (const TCHAR * Filename, EOpenReadFlags OpenOptions = EOpenReadFlags::None, int64 MaximumSize = 0) override virtual
Open a file for async reading.
This call does hit the disk; it is synchronous open.
Parameters
Filename File to be mapped. This doesn't actually map anything, just opens the file.
OpenOptions Allows specifying map to be writable via AllowWrite or be ReadOnly by deafault.
Returns
Close the file by deleting the handle. A non-null return value does mean the file exists. Null can be returned for many reasons even if the file exists. Perhaps this platform does not support mapped files, or this file is compressed in a pak file. Generally you attempt to open mapped, and if that fails, then use other file operations instead.
Reimplemented from IPlatformFile.
References Filename, and IPlatformFile::None.
OpenRead()
virtual IFileHandle * FLoggedPlatformFile::OpenRead (const TCHAR * Filename, bool bAllowWrite) inline override virtual
Attempt to open a file for reading.
Please consider using the new overload that takes EReadFlags instead of bools as parameters.
Parameters
Filename file to be opened
bAllowWrite (applies to certain platforms only) whether this file is allowed to be written to by other processes. This flag is needed to open files that are currently being written to as well.
Returns
If successful will return a non-nullptr pointer. Close the file by deleting the handle.
Implements IPlatformFile.
Definition at line 297 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
OpenWrite()
virtual IFileHandle * FLoggedPlatformFile::OpenWrite (const TCHAR * Filename, bool bAppend = false, bool bAllowRead = false) inline override virtual
Attempt to open a file for writing.
If successful will return a non-nullptr pointer. Close the file by deleting the handle.
Implements IPlatformFile.
Definition at line 308 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
SetAsyncMinimumPriority()
virtual void FLoggedPlatformFile::SetAsyncMinimumPriority (EAsyncIOPriorityAndFlags MinPriority) inline override virtual
Controls if the pak precacher should process precache requests.
Requests below this threshold will not get precached. Without this throttle, quite a lot of memory can be consumed if the disk races ahead of the CPU.
Parameters
MinPriority the minimum priority at which requests will get precached
Reimplemented from IPlatformFile.
Definition at line 508 of file IPlatformFileLogWrapper.h.
References LowerLevel.
SetLowerLevel()
virtual void FLoggedPlatformFile::SetLowerLevel (IPlatformFile * NewLowerLevel) inline override virtual
Sets the platform file wrapped by this file.
Implements IPlatformFile.
Definition at line 179 of file IPlatformFileLogWrapper.h.
References IPlatformFile::IPlatformFile(), and LowerLevel.
SetReadOnly()
virtual bool FLoggedPlatformFile::SetReadOnly (const TCHAR * Filename, bool bNewReadOnlyValue) inline override virtual
Attempt to change the read only status of a file.
Return true if successful.
Implements IPlatformFile.
Definition at line 243 of file IPlatformFileLogWrapper.h.
References FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
SetTimeStamp()
virtual void FLoggedPlatformFile::SetTimeStamp (const TCHAR * Filename, FDateTime DateTime) inline override virtual
Sets the modification time of a file.
Implements IPlatformFile.
Definition at line 265 of file IPlatformFileLogWrapper.h.
References DateTime, FColor::Emerald, FILE_LOG, Filename, Log, LowerLevel, SCOPED_NAMED_EVENT_FSTRING, FAndroidTime::Seconds(), and TEXT.
ShouldBeUsed()
virtual bool FLoggedPlatformFile::ShouldBeUsed (IPlatformFile * Inner, const TCHAR * CmdLine) const override virtual
Checks if this platform file should be used even though it was not asked to be.
i.e. pak files exist on disk so we should use a pak file
Reimplemented from IPlatformFile.
References IPlatformFile::IPlatformFile().
Field Documentation
LogFileCritical
FCriticalSection FLoggedPlatformFile::LogFileCritical private
Definition at line 150 of file IPlatformFileLogWrapper.h.
Referenced by OnHandleClosed(), and OnHandleOpen().
LowerLevel
IPlatformFile* FLoggedPlatformFile::LowerLevel private
Definition at line 147 of file IPlatformFileLogWrapper.h.
Referenced by FLoggedPlatformFile(), CopyFile(), CreateDirectory(), DeleteDirectory(), DeleteDirectoryRecursively(), DeleteFile(), DirectoryExists(), FileExists(), FileSize(), GetAccessTimeStamp(), GetFilenameOnDisk(), GetLowerLevel(), GetStatData(), GetTimeStamp(), IsReadOnly(), IterateDirectory(), IterateDirectoryRecursively(), IterateDirectoryStat(), IterateDirectoryStatRecursively(), MoveFile(), OpenAsyncRead(), OpenRead(), OpenWrite(), SetAsyncMinimumPriority(), SetLowerLevel(), SetReadOnly(), and SetTimeStamp().
OpenHandles
TMap<FString, int32> FLoggedPlatformFile::OpenHandles private
Definition at line 151 of file IPlatformFileLogWrapper.h.
Referenced by OnHandleClosed(), and OnHandleOpen().
The documentation for this class was generated from the following file:
IPlatformFileLogWrapper.h