Unreal Engine 5.6 C++ API: FIoBuffer Class Reference
FIoBuffer Class Reference
Reference to buffer data used by I/O dispatcher APIs.
#include "IoBuffer.h"
Data Structures
struct BufCore
Core buffer object.
Public Types
enum EAssumeOwnershipTag { AssumeOwnership }
enum ECloneTag { Clone }
enum EWrapTag { Wrap }
Public Member Functions
FIoBuffer ()
FIoBuffer (const void *Data, uint64 InSize, const FIoBuffer &OuterBuffer)
FIoBuffer (EAssumeOwnershipTag, const void *Data, uint64 InSize)
FIoBuffer (EAssumeOwnershipTag, FMemoryView Memory)
FIoBuffer (ECloneTag, const void *Data, uint64 InSize)
FIoBuffer (ECloneTag, FMemoryView Memory)
FIoBuffer (EWrapTag, const void *Data, uint64 InSize)
FIoBuffer (EWrapTag, FMemoryView Memory)
FIoBuffer (FMemoryView Memory, const FIoBuffer &OuterBuffer)
FIoBuffer (uint64 InSize)
uint8 * Data ()
const uint8 * Data () const
uint64 DataSize () const
void EnsureOwned () const
uint8 * GetData ()
const uint8 * GetData () const
FMutableMemoryView GetMutableView ()
uint64 GetSize () const
FMemoryView GetView () const
bool IsMemoryOwned () const
void MakeOwned () const
bool operator!= (const FIoBuffer &Rhs) const
TIoStatusOr< uint8 * > Release ()
Relinquishes control of the internal buffer to the caller and removes it from the FIoBuffer.
void SetSize (uint64 InSize)
Private Attributes
TRefCountPtr< BufCore > CorePtr
Friends
class FIoBufferManager
Detailed Description
Reference to buffer data used by I/O dispatcher APIs.
Definition at line 14 of file IoBuffer.h.
Member Enumeration Documentation
EAssumeOwnershipTag
enum FIoBuffer::EAssumeOwnershipTag
Enumerator
AssumeOwnership
Definition at line 17 of file IoBuffer.h.
ECloneTag
enum FIoBuffer::ECloneTag
Enumerator
Clone
Definition at line 18 of file IoBuffer.h.
EWrapTag
enum FIoBuffer::EWrapTag
Enumerator
Wrap
Definition at line 19 of file IoBuffer.h.
Constructor & Destructor Documentation
FIoBuffer() [1/10]
FIoBuffer::FIoBuffer ()
Referenced by FIoBuffer(), FIoBuffer(), and operator!=().
FIoBuffer() [2/10]
FIoBuffer::FIoBuffer (uint64 InSize) explicit
FIoBuffer() [3/10]
FIoBuffer::FIoBuffer (const void * Data, uint64 InSize, const FIoBuffer & OuterBuffer)
References FIoBuffer(), and Data().
FIoBuffer() [4/10]
FIoBuffer::FIoBuffer (FMemoryView Memory, const FIoBuffer & OuterBuffer)
References FIoBuffer(), and Memory.
FIoBuffer() [5/10]
FIoBuffer::FIoBuffer (EAssumeOwnershipTag , const void * Data, uint64 InSize)
References Data().
FIoBuffer() [6/10]
FIoBuffer::FIoBuffer (EAssumeOwnershipTag , FMemoryView Memory)
References Memory.
FIoBuffer() [7/10]
FIoBuffer::FIoBuffer (ECloneTag , const void * Data, uint64 InSize)
References Data().
FIoBuffer() [8/10]
FIoBuffer::FIoBuffer (ECloneTag , FMemoryView Memory)
References Memory.
FIoBuffer() [9/10]
FIoBuffer::FIoBuffer (EWrapTag , const void * Data, uint64 InSize)
References Data().
FIoBuffer() [10/10]
FIoBuffer::FIoBuffer (EWrapTag , FMemoryView Memory)
References Memory.
Member Function Documentation
Data() [1/2]
uint8 * FIoBuffer::Data () inline
Definition at line 37 of file IoBuffer.h.
References CorePtr.
Data() [2/2]
const uint8 * FIoBuffer::Data () const inline
Definition at line 36 of file IoBuffer.h.
References CorePtr.
Referenced by FIoBuffer(), FIoBuffer(), FIoBuffer(), and FIoBuffer().
DataSize()
uint64 FIoBuffer::DataSize () const inline
Definition at line 40 of file IoBuffer.h.
References CorePtr.
Referenced by operator!=().
EnsureOwned()
void FIoBuffer::EnsureOwned () const inline
Definition at line 50 of file IoBuffer.h.
References CorePtr, and MakeOwned().
GetData() [1/2]
uint8 * FIoBuffer::GetData () inline
Definition at line 39 of file IoBuffer.h.
References CorePtr.
GetData() [2/2]
const uint8 * FIoBuffer::GetData () const inline
Definition at line 38 of file IoBuffer.h.
References CorePtr.
Referenced by operator!=().
GetMutableView()
FMutableMemoryView FIoBuffer::GetMutableView () inline
Definition at line 44 of file IoBuffer.h.
References CorePtr, and MakeMemoryView().
Referenced by UE::FPlatformIoDispatcherBase::ScatterDecodedBlock().
GetSize()
uint64 FIoBuffer::GetSize () const inline
Definition at line 41 of file IoBuffer.h.
References CorePtr.
Referenced by UE::FPlatformIoDispatcherBase::ScatterDecodedBlock().
GetView()
FMemoryView FIoBuffer::GetView () const inline
Definition at line 43 of file IoBuffer.h.
References CorePtr, and MakeMemoryView().
IsMemoryOwned()
bool FIoBuffer::IsMemoryOwned () const inline
Definition at line 48 of file IoBuffer.h.
References CorePtr.
MakeOwned()
void FIoBuffer::MakeOwned () const
Referenced by EnsureOwned().
operator!=()
bool FIoBuffer::operator!= (const FIoBuffer & Rhs) const inline
Definition at line 52 of file IoBuffer.h.
References FIoBuffer(), DataSize(), GetData(), and FMemory::Memcmp().
Release()
TIoStatusOr< uint8 * > FIoBuffer::Release () nodiscard
Relinquishes control of the internal buffer to the caller and removes it from the FIoBuffer.
This allows the caller to assume ownership of the internal data and prevent it from being deleted along with the FIoBuffer.
NOTE: It is only valid to call this if the FIoBuffer currently owns the internal memory allocation, as the point of the call is to take ownership of it. If the FIoBuffer is only wrapping the allocation then it will return a failed FIoStatus instead.
Returns
A status wrapper around the memory pointer. Even if the status is valid the pointer might still be null.
SetSize()
void FIoBuffer::SetSize (uint64 InSize) inline
Definition at line 46 of file IoBuffer.h.
References CorePtr.
Friends And Related Symbol Documentation
FIoBufferManager
friend class FIoBufferManager friend
Definition at line 177 of file IoBuffer.h.
References FIoBufferManager.
Referenced by FIoBufferManager.
Field Documentation
CorePtr
TRefCountPtr<BufCore> FIoBuffer::CorePtr private
Definition at line 175 of file IoBuffer.h.
Referenced by Data(), Data(), DataSize(), EnsureOwned(), GetData(), GetData(), GetMutableView(), GetSize(), GetView(), IsMemoryOwned(), and SetSize().
The documentation for this class was generated from the following file:
IoBuffer.h