Unreal Engine 5.6 C++ API: SFindInBlueprints Class Reference
SFindInBlueprints Class Reference
#include "FindInBlueprints.h"
Public Member Functions
~SFindInBlueprints ()
void CacheAllBlueprints (const FFindInBlueprintCachingOptions &InOptions)
Asynchronously caches all Blueprints below a specified version.
void ClearResults ()
Clears the currently visible results.
void CloseHostTab ()
If this is a global find results widget, ask the host tab to close.
void FocusForUse (bool bSetFindWithinBlueprint, FString NewSearchTerms=FString(), bool bSelectFirstResult=false)
Focuses this widget's search box, and changes the mode as well, and optionally the search terms.
FName GetHostTabId () const
If this is a global find results widget, returns the host tab's unique ID.
bool IsLocked () const
Determines if this context does not accept syncing from an external source.
bool IsSearchInProgress () const
Determines whether a search query is actively in progress.
void MakeSearchQuery (FString InSearchString, bool bInIsFindWithinBlueprint, const FStreamSearchOptions &InSearchOptions=FStreamSearchOptions(), FOnSearchComplete InOnSearchComplete=FOnSearchComplete())
Submits a search query.
void OnCacheComplete (EFiBCacheOpType InOpType, EFiBCacheOpFlags InOpFlags)
Called when caching Blueprints is complete.
void OnCacheStarted (EFiBCacheOpType InOpType, EFiBCacheOpFlags InOpFlags)
Called when caching Blueprints is started.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
SWidget overrides.
bHideSearchBar SLATE_ARGUMENT (bool, bHideFindGlobalButton) SLATE_ARGUMENT(TSharedPtr< SDockTab >
SLATE_ARGUMENT (bool, bIsSearchWindow) SLATE_ARGUMENT(bool
SLATE_BEGIN_ARGS (SFindInBlueprints)
bHideSearchBar ContainingTab SLATE_END_ARGS () void Construct(const FArguments &InArgs
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
bHideSearchBar ContainingTab TSharedPtr< class FBlueprintEditor > InBlueprintEditor = nullptr)
Private Member Functions
bool CanCacheAllUnindexedBlueprints () const
Whether user is allowed to initiate loading and indexing all blueprints with out-of-date metadata.
void ConditionallyAddCacheBar ()
Adds the "cache" bar at the bottom of the Find-in-Blueprints widget, to notify the user that the search is incomplete.
FText GetCacheBarCurrentAssetName () const
Callback to return the current asset name during a cache operation.
const FSlateBrush * GetCacheBarImage () const
Returns the BG image used for the cache bar.
FText GetCacheBarStatusText () const
Callback to return the cache bar's display text, informing the user of the situation.
EVisibility GetCacheBarVisibility () const
Returns the caching bar's visibility, it goes invisible when there is nothing to be cached.
EVisibility GetCacheBarWidgetVisibility (EFiBCacheBarWidget InCacheBarWidget) const
Returns the cache bar visibility for the given widget.
int32 GetCurrentCacheIndex () const
Retrieves the current index of the Blueprint caching process.
TOptional< float > GetPercentCompleteCache () const
Gets the percent complete of the caching process.
TOptional< float > GetPercentCompleteSearch () const
Returns the percent complete on the search for the progress bar.
EVisibility GetSearchBarWidgetVisiblity (EFiBSearchBarWidget InSearchBarWidget) const
Returns the search bar visiblity for the given widget.
bool IsCacheInProgress () const
Returns TRUE if Blueprint caching is in progress.
void LaunchStreamThread (const FString &InSearchValue, const FStreamSearchOptions &InSearchOptions=FStreamSearchOptions(), FOnSearchComplete InOnSearchComplete=FOnSearchComplete())
Launches a thread for streaming more content into the results widget.
FReply OnCacheAllBlueprints (const FFindInBlueprintCachingOptions &InOptions)
Callback to cache all Blueprints according to the given options.
FReply OnCacheAllUnindexedBlueprints ()
Callback to cache all unindexed Blueprints.
FReply OnCancelCacheAll ()
Callback to cancel the caching process.
TSharedPtr< SWidget > OnContextMenuOpening ()
Callback to build the context menu when right clicking in the tree.
void OnCopyAction ()
Callback when user attempts to copy their selection in the Find-in-Blueprints.
FReply OnExportUnindexedAssetList ()
Callback to export a list of all blueprints that need reindexing.
TSharedRef< ITableRow > OnGenerateRow (FSearchResult InItem, const TSharedRef< STableViewBase > &OwnerTable)
void OnGetChildren (FSearchResult InItem, TArray< FSearchResult > &OutChildren)
const FSlateBrush * OnGetLockButtonImage () const
Returns the image used for the lock button in a global find results tab.
void OnHostTabClosed (TSharedRef< SDockTab > DockTab)
Called when the host tab is closed (if valid)
FReply OnLockButtonClicked ()
Called when the lock button is clicked in a global find results tab.
FReply OnOpenGlobalFindResults ()
Called when the user clicks the global find results button.
FReply OnRemoveCacheBar ()
Callback to remove the "cache" bar when a button is pressed.
void OnSearchTextChanged (const FText &Text)
void OnSearchTextCommitted (const FText &Text, ETextCommit::Type CommitType)
void OnSelectAllAction ()
Callback when user attempts to select all items in the search results.
void OnTreeSelectionDoubleClicked (FSearchResult Item)
void RegisterCommands ()
Register any Find-in-Blueprint commands.
void SelectAllItemsHelper (FSearchResult InItemToSelect)
Helper function to select all items.
EActiveTimerReturnType UpdateSearchResults (double InCurrentTime, float InDeltaTime)
Processes results of the ongoing async stream search.
Private Attributes
bool bHideProgressBars
True if progress bar widgets should be hidden.
bool bIsInFindWithinBlueprintMode
Should we search within the current blueprint only (rather than all blueprints)
bool bIsLocked
True if current search should not be changed by an external source.
bool bKeepCacheBarProgressVisible
True if cache bar should remain visible after a caching operation has ended.
TWeakPtr< class FBlueprintEditor > BlueprintEditorPtr
Pointer back to the blueprint editor that owns us.
bool bShowCacheBarCancelButton
True if users should be allowed to cancel the active caching operation.
bool bShowCacheBarCloseButton
True if users should be allowed to close the cache bar while caching.
bool bShowCacheBarUnresponsiveEditorWarningText
True if the unresponsive warning text should be visible in the cache bar.
TWeakPtr< SWidget > CacheBarSlot
Weak pointer to the cache bar slot, so it can be removed.
TSharedPtr< FUICommandList > CommandList
Commands handled by this widget.
FText HighlightText
TWeakPtr< SDockTab > HostTab
Tab hosting this widget.
TArray< FSearchResult > ItemsFound
FSoftObjectPath LastCachedAssetPath
Last cached asset path (used during continuous cache operations).
EFiBVersion LastSearchedFiBVersion
Cached version that was last searched.
TWeakPtr< SVerticalBox > MainVerticalBox
Vertical box, used to add and remove widgets dynamically.
FOnSearchComplete OnSearchComplete
Callback when search is complete.
int32 OutOfDateWithLastSearchBPCount
Cached count of out of date Blueprints from last search.
FSearchResult RootSearchResult
In Find Within Blueprint mode, we need to keep a handle on the root result, because it won't show up in the tree.
TSharedPtr< class SSearchBox > SearchTextField
The search text box.
FString SearchValue
TSharedPtr< class FStreamSearch > StreamSearch
Thread object that searches through Blueprint data on a separate thread.
TSharedPtr< STreeViewType > TreeView
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 278 of file FindInBlueprints.h.
Constructor & Destructor Documentation
~SFindInBlueprints()
SFindInBlueprints::~SFindInBlueprints ()
Member Function Documentation
CacheAllBlueprints()
void SFindInBlueprints::CacheAllBlueprints (const FFindInBlueprintCachingOptions & InOptions)
Asynchronously caches all Blueprints below a specified version.
Parameters
InOptions Options to configure the caching task
References CacheAllBlueprints(), and InOptions.
Referenced by CacheAllBlueprints().
CanCacheAllUnindexedBlueprints()
bool SFindInBlueprints::CanCacheAllUnindexedBlueprints () const private
Whether user is allowed to initiate loading and indexing all blueprints with out-of-date metadata.
ClearResults()
void SFindInBlueprints::ClearResults ()
Clears the currently visible results.
CloseHostTab()
void SFindInBlueprints::CloseHostTab ()
If this is a global find results widget, ask the host tab to close.
References CloseHostTab().
Referenced by CloseHostTab().
ConditionallyAddCacheBar()
void SFindInBlueprints::ConditionallyAddCacheBar () private
Adds the "cache" bar at the bottom of the Find-in-Blueprints widget, to notify the user that the search is incomplete.
FocusForUse()
void SFindInBlueprints::FocusForUse (bool bSetFindWithinBlueprint, FString NewSearchTerms = FString(), bool bSelectFirstResult = false)
Focuses this widget's search box, and changes the mode as well, and optionally the search terms.
References FocusForUse().
Referenced by FocusForUse().
GetCacheBarCurrentAssetName()
FText SFindInBlueprints::GetCacheBarCurrentAssetName () const private
Callback to return the current asset name during a cache operation.
GetCacheBarImage()
const FSlateBrush * SFindInBlueprints::GetCacheBarImage () const private
Returns the BG image used for the cache bar.
GetCacheBarStatusText()
FText SFindInBlueprints::GetCacheBarStatusText () const private
Callback to return the cache bar's display text, informing the user of the situation.
GetCacheBarVisibility()
EVisibility SFindInBlueprints::GetCacheBarVisibility () const private
Returns the caching bar's visibility, it goes invisible when there is nothing to be cached.
The next search will remove this bar or make it visible again
GetCacheBarWidgetVisibility()
EVisibility SFindInBlueprints::GetCacheBarWidgetVisibility (EFiBCacheBarWidget InCacheBarWidget) const private
Returns the cache bar visibility for the given widget.
GetCurrentCacheIndex()
int32 SFindInBlueprints::GetCurrentCacheIndex () const private
Retrieves the current index of the Blueprint caching process.
GetHostTabId()
FName SFindInBlueprints::GetHostTabId () const
If this is a global find results widget, returns the host tab's unique ID.
Otherwise, returns NAME_None.
References GetHostTabId().
Referenced by GetHostTabId().
GetPercentCompleteCache()
TOptional< float > SFindInBlueprints::GetPercentCompleteCache () const private
Gets the percent complete of the caching process.
GetPercentCompleteSearch()
TOptional< float > SFindInBlueprints::GetPercentCompleteSearch () const private
Returns the percent complete on the search for the progress bar.
GetSearchBarWidgetVisiblity()
EVisibility SFindInBlueprints::GetSearchBarWidgetVisiblity (EFiBSearchBarWidget InSearchBarWidget) const private
Returns the search bar visiblity for the given widget.
IsCacheInProgress()
bool SFindInBlueprints::IsCacheInProgress () const private
Returns TRUE if Blueprint caching is in progress.
IsLocked()
bool SFindInBlueprints::IsLocked () const inline
Determines if this context does not accept syncing from an external source.
Definition at line 329 of file FindInBlueprints.h.
References bIsLocked, and IsLocked().
Referenced by IsLocked().
IsSearchInProgress()
bool SFindInBlueprints::IsSearchInProgress () const
Determines whether a search query is actively in progress.
LaunchStreamThread()
void SFindInBlueprints::LaunchStreamThread (const FString & InSearchValue, const FStreamSearchOptions & InSearchOptions = FStreamSearchOptions(), FOnSearchComplete InOnSearchComplete = FOnSearchComplete()) private
Launches a thread for streaming more content into the results widget.
MakeSearchQuery()
void SFindInBlueprints::MakeSearchQuery (FString InSearchString, bool bInIsFindWithinBlueprint, const FStreamSearchOptions & InSearchOptions = FStreamSearchOptions(), FOnSearchComplete InOnSearchComplete = FOnSearchComplete())
Submits a search query.
Parameters
InSearchString String to search using
bInIsFindWithinBlueprint TRUE if searching within the current Blueprint only
InSearchOptions Optional search parameters.
InOnSearchComplete Callback when the search is complete, passing the filtered imaginary data (if any).
References MakeSearchQuery().
Referenced by MakeSearchQuery().
OnCacheAllBlueprints()
FReply SFindInBlueprints::OnCacheAllBlueprints (const FFindInBlueprintCachingOptions & InOptions) private
Callback to cache all Blueprints according to the given options.
References InOptions.
OnCacheAllUnindexedBlueprints()
FReply SFindInBlueprints::OnCacheAllUnindexedBlueprints () private
Callback to cache all unindexed Blueprints.
OnCacheComplete()
void SFindInBlueprints::OnCacheComplete (EFiBCacheOpType InOpType, EFiBCacheOpFlags InOpFlags)
Called when caching Blueprints is complete.
References OnCacheComplete().
Referenced by OnCacheComplete().
OnCacheStarted()
void SFindInBlueprints::OnCacheStarted (EFiBCacheOpType InOpType, EFiBCacheOpFlags InOpFlags)
Called when caching Blueprints is started.
References OnCacheStarted().
Referenced by OnCacheStarted().
OnCancelCacheAll()
FReply SFindInBlueprints::OnCancelCacheAll () private
Callback to cancel the caching process.
OnContextMenuOpening()
TSharedPtr< SWidget > SFindInBlueprints::OnContextMenuOpening () private
Callback to build the context menu when right clicking in the tree.
OnCopyAction()
void SFindInBlueprints::OnCopyAction () private
Callback when user attempts to copy their selection in the Find-in-Blueprints.
OnExportUnindexedAssetList()
FReply SFindInBlueprints::OnExportUnindexedAssetList () private
Callback to export a list of all blueprints that need reindexing.
OnGenerateRow()
TSharedRef< ITableRow > SFindInBlueprints::OnGenerateRow (FSearchResult InItem, const TSharedRef< STableViewBase > & OwnerTable) private
OnGetChildren()
void SFindInBlueprints::OnGetChildren (FSearchResult InItem, TArray< FSearchResult > & OutChildren) private
OnGetLockButtonImage()
const FSlateBrush * SFindInBlueprints::OnGetLockButtonImage () const private
Returns the image used for the lock button in a global find results tab.
OnHostTabClosed()
void SFindInBlueprints::OnHostTabClosed (TSharedRef< SDockTab > DockTab) private
Called when the host tab is closed (if valid)
OnKeyDown()
virtual FReply SFindInBlueprints::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
SWidget overrides.
Reimplemented from SWidget.
OnLockButtonClicked()
FReply SFindInBlueprints::OnLockButtonClicked () private
Called when the lock button is clicked in a global find results tab.
OnOpenGlobalFindResults()
FReply SFindInBlueprints::OnOpenGlobalFindResults () private
Called when the user clicks the global find results button.
OnRemoveCacheBar()
FReply SFindInBlueprints::OnRemoveCacheBar () private
Callback to remove the "cache" bar when a button is pressed.
OnSearchTextChanged()
void SFindInBlueprints::OnSearchTextChanged (const FText & Text) private
References Text.
OnSearchTextCommitted()
void SFindInBlueprints::OnSearchTextCommitted (const FText & Text, ETextCommit::Type CommitType) private
References Text.
OnSelectAllAction()
void SFindInBlueprints::OnSelectAllAction () private
Callback when user attempts to select all items in the search results.
OnTreeSelectionDoubleClicked()
void SFindInBlueprints::OnTreeSelectionDoubleClicked (FSearchResult Item) private
References Item.
RegisterCommands()
void SFindInBlueprints::RegisterCommands () private
Register any Find-in-Blueprint commands.
SelectAllItemsHelper()
void SFindInBlueprints::SelectAllItemsHelper (FSearchResult InItemToSelect) private
Helper function to select all items.
SLATE_ARGUMENT() [1/2]
bHideSearchBar SFindInBlueprints::SLATE_ARGUMENT (bool , bHideFindGlobalButton)
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [2/2]
SFindInBlueprints::SLATE_ARGUMENT (bool , bIsSearchWindow)
Referenced by SLATE_ARGUMENT().
SLATE_BEGIN_ARGS()
SFindInBlueprints::SLATE_BEGIN_ARGS (SFindInBlueprints) inline
Definition at line 281 of file FindInBlueprints.h.
SLATE_END_ARGS()
bHideSearchBar ContainingTab SFindInBlueprints::SLATE_END_ARGS () const &
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
UpdateSearchResults()
EActiveTimerReturnType SFindInBlueprints::UpdateSearchResults (double InCurrentTime, float InDeltaTime) private
Processes results of the ongoing async stream search.
Field Documentation
bHideProgressBars
bool SFindInBlueprints::bHideProgressBars private
True if progress bar widgets should be hidden.
Definition at line 499 of file FindInBlueprints.h.
bIsInFindWithinBlueprintMode
bool SFindInBlueprints::bIsInFindWithinBlueprintMode private
Should we search within the current blueprint only (rather than all blueprints)
Definition at line 493 of file FindInBlueprints.h.
bIsLocked
bool SFindInBlueprints::bIsLocked private
True if current search should not be changed by an external source.
Definition at line 496 of file FindInBlueprints.h.
Referenced by IsLocked().
bKeepCacheBarProgressVisible
bool SFindInBlueprints::bKeepCacheBarProgressVisible private
True if cache bar should remain visible after a caching operation has ended.
Definition at line 511 of file FindInBlueprints.h.
BlueprintEditorPtr
TWeakPtr<class FBlueprintEditor> SFindInBlueprints::BlueprintEditorPtr private
Pointer back to the blueprint editor that owns us.
Definition at line 445 of file FindInBlueprints.h.
bShowCacheBarCancelButton
bool SFindInBlueprints::bShowCacheBarCancelButton private
True if users should be allowed to cancel the active caching operation.
Definition at line 505 of file FindInBlueprints.h.
bShowCacheBarCloseButton
bool SFindInBlueprints::bShowCacheBarCloseButton private
True if users should be allowed to close the cache bar while caching.
Definition at line 502 of file FindInBlueprints.h.
bShowCacheBarUnresponsiveEditorWarningText
bool SFindInBlueprints::bShowCacheBarUnresponsiveEditorWarningText private
True if the unresponsive warning text should be visible in the cache bar.
Definition at line 508 of file FindInBlueprints.h.
CacheBarSlot
TWeakPtr< SWidget > SFindInBlueprints::CacheBarSlot private
Weak pointer to the cache bar slot, so it can be removed.
Definition at line 472 of file FindInBlueprints.h.
CommandList
TSharedPtr< FUICommandList > SFindInBlueprints::CommandList private
Commands handled by this widget.
Definition at line 484 of file FindInBlueprints.h.
HighlightText
FText SFindInBlueprints::HighlightText private
Definition at line 460 of file FindInBlueprints.h.
HostTab
TWeakPtr<SDockTab> SFindInBlueprints::HostTab private
Tab hosting this widget.
May be invalid.
Definition at line 487 of file FindInBlueprints.h.
InBlueprintEditor
bHideSearchBar ContainingTab TSharedPtr<class FBlueprintEditor> SFindInBlueprints::InBlueprintEditor = nullptr)
Definition at line 293 of file FindInBlueprints.h.
ItemsFound
TArray<FSearchResult> SFindInBlueprints::ItemsFound private
Definition at line 454 of file FindInBlueprints.h.
LastCachedAssetPath
FSoftObjectPath SFindInBlueprints::LastCachedAssetPath mutable private
Last cached asset path (used during continuous cache operations).
Definition at line 490 of file FindInBlueprints.h.
LastSearchedFiBVersion
EFiBVersion SFindInBlueprints::LastSearchedFiBVersion private
Cached version that was last searched.
Definition at line 481 of file FindInBlueprints.h.
MainVerticalBox
TWeakPtr< SVerticalBox > SFindInBlueprints::MainVerticalBox private
Vertical box, used to add and remove widgets dynamically.
Definition at line 469 of file FindInBlueprints.h.
OnSearchComplete
FOnSearchComplete SFindInBlueprints::OnSearchComplete private
Callback when search is complete.
Definition at line 475 of file FindInBlueprints.h.
OutOfDateWithLastSearchBPCount
int32 SFindInBlueprints::OutOfDateWithLastSearchBPCount private
Cached count of out of date Blueprints from last search.
Definition at line 478 of file FindInBlueprints.h.
RootSearchResult
FSearchResult SFindInBlueprints::RootSearchResult private
In Find Within Blueprint mode, we need to keep a handle on the root result, because it won't show up in the tree.
Definition at line 457 of file FindInBlueprints.h.
SearchTextField
TSharedPtr<class SSearchBox> SFindInBlueprints::SearchTextField private
The search text box.
Definition at line 451 of file FindInBlueprints.h.
SearchValue
FString SFindInBlueprints::SearchValue private
Definition at line 463 of file FindInBlueprints.h.
StreamSearch
TSharedPtr< class FStreamSearch> SFindInBlueprints::StreamSearch private
Thread object that searches through Blueprint data on a separate thread.
Definition at line 466 of file FindInBlueprints.h.
TreeView
TSharedPtr<STreeViewType> SFindInBlueprints::TreeView private
Definition at line 448 of file FindInBlueprints.h.
The documentation for this class was generated from the following file:
FindInBlueprints.h