Unreal Engine 5.6 C++ API: FConstStructArrayView Struct Reference
FConstStructArrayView Struct Reference
A generic, transient view of a homogeneously-typed array of instances of a specific UScriptStruct FConstStructArrayView supplies immutable access to the elements of the Array.
#include "StructArrayView.h"
Data Structures
struct FIterator
Public Member Functions
FConstStructArrayView ()=default
FConstStructArrayView (const FStructArrayView Src)
FConstStructArrayView (const UScriptStruct &InScriptStruct, const void *InData, const int32 InCount)
FConstStructArrayView (const UScriptStruct *InScriptStruct, const void *InData, const uint32 InElementSize, const int32 InCount)
template<typename T>
FConstStructArrayView (TArray< T > &InArray)
template<typename T>
FConstStructArrayView (TArrayView< T > InArrayView)
FORCEINLINE FIterator begin () const
Ranged iteration support.
void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero.
FORCEINLINE FIterator end () const
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T & >::Type GetAt (const int32 Index) const
Returns reference to element at given index.
const void * GetData () const
Helper function for returning a pointer to the first array entry.
const void * GetDataAt (const int32 Index) const
Helper function for returning a pointer to an element in the array.
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T * >::Type GetPtrAt (const int32 Index) const
Returns pointer to element at given index.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
FORCEINLINE_DEBUGGABLE uint32 GetTypeSize ()
Helper function returning the size of the inner type.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
bool IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T & >::Type Last (int32 IndexFromTheEnd=0) const
Returns n-th last element from the array.
FConstStructArrayView Left (const int32 Count) const
Returns the left-most part of the view by taking the given number of elements from the left.
FConstStructArrayView LeftChop (const int32 Count) const
Returns the left-most part of the view by chopping the given number of elements from the right.
void LeftChopInline (const int32 Count)
Modifies the view by chopping the given number of elements from the right.
void LeftInline (const int32 Count)
Modifies the view to be the given number of elements from the left.
FConstStructArrayView Mid (int32 Index, int32 Count=TNumericLimits< int32 >::Max()) const
Returns the middle part of the view by taking up to the given number of elements from the given position.
void MidInline (const int32 Position, const int32 Count=TNumericLimits< int32 >::Max())
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
int32 Num () const
Returns number of elements in array.
FConstStructArrayView & operator= (const FStructArrayView StructArrayView)
FConstStructView operator[] (int32 Index) const
Array bracket operator.
void RangeCheck (int32 Index) const
Checks if index is in array range.
FConstStructArrayView Right (const int32 Count) const
Returns the right-most part of the view by taking the given number of elements from the right.
FConstStructArrayView RightChop (const int32 Count) const
Returns the right-most part of the view by chopping the given number of elements from the left.
void RightChopInline (const int32 Count)
Modifies the view by chopping the given number of elements from the left.
void RightInline (const int32 Count)
Modifies the view to be the given number of elements from the right.
FConstStructArrayView Slice (const int32 Index, const int32 InNum) const
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
FORCEINLINE void SliceRangeCheck (int32 Index, int32 InNum) const
Checks if a slice range [Index, Index+InNum) is in array range.
Private Attributes
int32 ArrayNum = 0
const void * DataPtr = nullptr
uint32 ElementSize = 0
const UScriptStruct * ScriptStruct = nullptr
Detailed Description
A generic, transient view of a homogeneously-typed array of instances of a specific UScriptStruct FConstStructArrayView supplies immutable access to the elements of the Array.
For a more indepth overview of the constness of views see FConstStructView
Definition at line 396 of file StructArrayView.h.
Constructor & Destructor Documentation
FConstStructArrayView() [1/6]
FConstStructArrayView::FConstStructArrayView () default
Referenced by FConstStructArrayView::FIterator::FIterator(), Left(), LeftChop(), Mid(), operator=(), Right(), RightChop(), and Slice().
FConstStructArrayView() [2/6]
template<typename T> FConstStructArrayView::FConstStructArrayView (TArray< T > & InArray) inline explicit
Definition at line 401 of file StructArrayView.h.
References ArrayNum, DataPtr, ElementSize, GetData(), Num(), ScriptStruct, and StaticStruct().
FConstStructArrayView() [3/6]
template<typename T> FConstStructArrayView::FConstStructArrayView (TArrayView< T > InArrayView) inline explicit
Definition at line 409 of file StructArrayView.h.
References ArrayNum, DataPtr, ElementSize, GetData(), Num(), ScriptStruct, and StaticStruct().
FConstStructArrayView() [4/6]
FConstStructArrayView::FConstStructArrayView (const FStructArrayView Src) inline
Definition at line 416 of file StructArrayView.h.
References ArrayNum, DataPtr, ElementSize, GetData(), GetScriptStruct(), GetTypeSize(), Num(), and ScriptStruct.
FConstStructArrayView() [5/6]
FConstStructArrayView::FConstStructArrayView (const UScriptStruct * InScriptStruct, const void * InData, const uint32 InElementSize, const int32 InCount) inline
Definition at line 423 of file StructArrayView.h.
References ArrayNum, check, DataPtr, ElementSize, and ScriptStruct.
FConstStructArrayView() [6/6]
FConstStructArrayView::FConstStructArrayView (const UScriptStruct & InScriptStruct, const void * InData, const int32 InCount) inline
Definition at line 433 of file StructArrayView.h.
References ArrayNum, check, DataPtr, ElementSize, and ScriptStruct.
Member Function Documentation
begin()
FORCEINLINE FIterator FConstStructArrayView::begin () const inline
Ranged iteration support.
DO NOT USE DIRECTLY.
Definition at line 711 of file StructArrayView.h.
References FORCEINLINE.
CheckInvariants()
void FConstStructArrayView::CheckInvariants () const inline
Checks array invariants: if array size is greater than or equal to zero.
Definition at line 452 of file StructArrayView.h.
References ArrayNum, and checkSlow.
end()
FORCEINLINE FIterator FConstStructArrayView::end () const inline
Definition at line 712 of file StructArrayView.h.
References FORCEINLINE, and Num().
GetAt()
template<typename T> TEnableIf< TIsConst< T >::Value, T & >::Type FConstStructArrayView::GetAt (const int32 Index) const inline constexpr
Returns reference to element at given index.
Index and template param T MUST be must be valid.
Parameters
Index Index of element
T Type of stuct, this must either be the type or a parent type of the struct type in the array.
Returns
const reference to indexed element.
Definition at line 568 of file StructArrayView.h.
References GetDataAt(), UE::StructUtils::GetStructRef(), and ScriptStruct.
Referenced by Last().
GetData()
const void * FConstStructArrayView::GetData () const inline
Helper function for returning a pointer to the first array entry.
Returns
const Pointer to first array entry.
Definition at line 509 of file StructArrayView.h.
References DataPtr.
Referenced by FConstStructArrayView(), FConstStructArrayView(), and FConstStructArrayView().
GetDataAt()
const void * FConstStructArrayView::GetDataAt (const int32 Index) const inline
Helper function for returning a pointer to an element in the array.
Parameters
Index Index of element, this MUST be a valid element.
Returns
const Pointer to entry.
Definition at line 520 of file StructArrayView.h.
References DataPtr, ElementSize, and RangeCheck().
Referenced by GetAt(), GetPtrAt(), Mid(), operator[](), Right(), RightChop(), and Slice().
GetPtrAt()
template<typename T> TEnableIf< TIsConst< T >::Value, T * >::Type FConstStructArrayView::GetPtrAt (const int32 Index) const inline constexpr
Returns pointer to element at given index.
The index MUST be valid. If parametre T is invalid then nullptr will be returned.
Parameters
Index Index of element
T Type of stuct, this must either be the type or a parent type of the struct type in the array.
Returns
const pointer to indexed element.
Definition at line 555 of file StructArrayView.h.
References GetDataAt(), UE::StructUtils::GetStructPtr(), and ScriptStruct.
GetScriptStruct()
const UScriptStruct * FConstStructArrayView::GetScriptStruct () const inline
Returns struct type.
Definition at line 544 of file StructArrayView.h.
References ScriptStruct.
Referenced by FConstStructArrayView().
GetTypeSize()
FORCEINLINE_DEBUGGABLE uint32 FConstStructArrayView::GetTypeSize () inline
Helper function returning the size of the inner type.
Returns
Size in bytes of array type.
Definition at line 531 of file StructArrayView.h.
References ElementSize, and FORCEINLINE_DEBUGGABLE.
Referenced by FConstStructArrayView().
IsEmpty()
bool FConstStructArrayView::IsEmpty () const inline
Returns true if the array is empty and contains no elements.
Returns
True if array is empty.
See also
Num
Definition at line 499 of file StructArrayView.h.
References ArrayNum.
IsValidIndex()
bool FConstStructArrayView::IsValidIndex (int32 Index) const inline
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of elements in the array.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 488 of file StructArrayView.h.
References ArrayNum.
Last()
template<typename T> TEnableIf< TIsConst< T >::Value, T & >::Type FConstStructArrayView::Last (int32 IndexFromTheEnd = 0) const inline constexpr
Returns n-th last element from the array.
Parameters
IndexFromTheEnd (Optional) Index from the end of array. This MUST index a valid element. Default is 0.
Returns
const reference to n-th last element from the array.
Definition at line 592 of file StructArrayView.h.
References ArrayNum, and GetAt().
Left()
FConstStructArrayView FConstStructArrayView::Left (const int32 Count) const inline nodiscard
Returns the left-most part of the view by taking the given number of elements from the left.
Definition at line 614 of file StructArrayView.h.
References FConstStructArrayView(), ArrayNum, FMath::Clamp(), Count, DataPtr, ElementSize, and ScriptStruct.
LeftChop()
FConstStructArrayView FConstStructArrayView::LeftChop (const int32 Count) const inline nodiscard
Returns the left-most part of the view by chopping the given number of elements from the right.
Definition at line 620 of file StructArrayView.h.
References FConstStructArrayView(), ArrayNum, FMath::Clamp(), Count, DataPtr, ElementSize, and ScriptStruct.
LeftChopInline()
void FConstStructArrayView::LeftChopInline (const int32 Count) inline
Modifies the view by chopping the given number of elements from the right.
Definition at line 653 of file StructArrayView.h.
References Count, and LeftChop.
LeftInline()
void FConstStructArrayView::LeftInline (const int32 Count) inline
Modifies the view to be the given number of elements from the left.
Definition at line 647 of file StructArrayView.h.
References Count, and Left.
Mid()
FConstStructArrayView FConstStructArrayView::Mid (int32 Index, int32 Count = TNumericLimits<int32>::Max()) const inline nodiscard
Returns the middle part of the view by taking up to the given number of elements from the given position.
Definition at line 640 of file StructArrayView.h.
References FConstStructArrayView(), ArrayNum, UE::StructUtils::CalcMidIndexAndCount(), Count, ElementSize, GetDataAt(), and ScriptStruct.
Referenced by MidInline().
MidInline()
void FConstStructArrayView::MidInline (const int32 Position, const int32 Count = TNumericLimits<int32>::Max()) inline
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
Definition at line 671 of file StructArrayView.h.
References Count, Mid(), and Position.
Num()
int32 FConstStructArrayView::Num () const inline
Returns number of elements in array.
Returns
Number of elements in array.
Definition at line 541 of file StructArrayView.h.
References ArrayNum.
Referenced by FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), and end().
operator=()
FConstStructArrayView & FConstStructArrayView::operator= (const FStructArrayView StructArrayView) inline
Definition at line 443 of file StructArrayView.h.
References FConstStructArrayView().
operator[]()
FConstStructView FConstStructArrayView::operator[] (int32 Index) const inline
Array bracket operator.
Returns FConstStructView to element at given index. Index must be valid.
Returns
FConstStructView to indexed element.
Definition at line 578 of file StructArrayView.h.
References GetDataAt(), and ScriptStruct.
RangeCheck()
void FConstStructArrayView::RangeCheck (int32 Index) const inline
Checks if index is in array range.
Parameters
Index Index to check.
Definition at line 462 of file StructArrayView.h.
References ArrayNum, checkf, and TEXT.
Referenced by GetDataAt().
Right()
FConstStructArrayView FConstStructArrayView::Right (const int32 Count) const inline nodiscard
Returns the right-most part of the view by taking the given number of elements from the right.
Definition at line 626 of file StructArrayView.h.
References FConstStructArrayView(), ArrayNum, FMath::Clamp(), Count, ElementSize, GetDataAt(), and ScriptStruct.
RightChop()
FConstStructArrayView FConstStructArrayView::RightChop (const int32 Count) const inline nodiscard
Returns the right-most part of the view by chopping the given number of elements from the left.
Definition at line 633 of file StructArrayView.h.
References FConstStructArrayView(), ArrayNum, FMath::Clamp(), Count, ElementSize, GetDataAt(), and ScriptStruct.
RightChopInline()
void FConstStructArrayView::RightChopInline (const int32 Count) inline
Modifies the view by chopping the given number of elements from the left.
Definition at line 665 of file StructArrayView.h.
References Count, and RightChop.
RightInline()
void FConstStructArrayView::RightInline (const int32 Count) inline
Modifies the view to be the given number of elements from the right.
Definition at line 659 of file StructArrayView.h.
References Count, and Right.
Slice()
FConstStructArrayView FConstStructArrayView::Slice (const int32 Index, const int32 InNum) const inline nodiscard
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
slicing outside of the range of the view is illegal.
Parameters
Index starting index of the new view
InNum number of elements in the new view
Returns
Sliced view
See also
Mid
Definition at line 607 of file StructArrayView.h.
References FConstStructArrayView(), ElementSize, GetDataAt(), ScriptStruct, and SliceRangeCheck().
SliceRangeCheck()
FORCEINLINE void FConstStructArrayView::SliceRangeCheck (int32 Index, int32 InNum) const inline
Checks if a slice range [Index, Index+InNum) is in array range.
Length is 0 is allowed on empty arrays; Index must be 0 in that case.
Parameters
Index Starting index of the slice.
InNum Length of the slice.
Definition at line 474 of file StructArrayView.h.
References ArrayNum, checkf, FORCEINLINE, and TEXT.
Referenced by Slice().
Field Documentation
ArrayNum
int32 FConstStructArrayView::ArrayNum = 0 private
Definition at line 718 of file StructArrayView.h.
Referenced by FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), CheckInvariants(), IsEmpty(), IsValidIndex(), Last(), Left(), LeftChop(), Mid(), Num(), RangeCheck(), Right(), RightChop(), and SliceRangeCheck().
DataPtr
const void* FConstStructArrayView::DataPtr = nullptr private
Definition at line 715 of file StructArrayView.h.
Referenced by FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), GetData(), GetDataAt(), Left(), and LeftChop().
ElementSize
uint32 FConstStructArrayView::ElementSize = 0 private
Definition at line 717 of file StructArrayView.h.
Referenced by FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), GetDataAt(), GetTypeSize(), Left(), LeftChop(), Mid(), Right(), RightChop(), and Slice().
ScriptStruct
const UScriptStruct* FConstStructArrayView::ScriptStruct = nullptr private
Definition at line 716 of file StructArrayView.h.
Referenced by FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), FConstStructArrayView(), GetAt(), GetPtrAt(), GetScriptStruct(), Left(), LeftChop(), Mid(), operator[](), Right(), RightChop(), and Slice().
The documentation for this struct was generated from the following file:
StructArrayView.h