Unreal Engine 5.6 C++ API: FCookTagList Struct Reference
FCookTagList Struct Reference
Used for passing key-value pairs to the asset registry during serialization during cook, and is accessed off of FArchive::CookContext()
#include "CookTagList.h"
Public Types
using FTagNameValuePair = TPair<FName, FString>
Public Member Functions
FCookTagList (UPackage *InPackage)
void Add (UObject *InObject, FName InTagName, FString &&InTagValue)
Adds a tag to the list to be added to the development asset registry for this object.
void Reset ()
Data Fields
TMap< UObject *, TArray< FTagNameValuePair > > ObjectToTags
UPackage * Package
Detailed Description
Used for passing key-value pairs to the asset registry during serialization during cook, and is accessed off of FArchive::CookContext()
This duplicates functionality in GetAssetRegistryTags, but it exists because some tags are expensive to calculate and the calculation overlaps with other calculations done during serialize.
All tags added to this list have "Cook_" prepended to their names prior to being added to the asset registry.
Cook tags are only added to the development asset registry, and will not show up in the shipped runtime registry.
Cook tags are only generated during Cook By The Book.
Example:
// Cook context is present for all cooks, but the tag list is only for CBTB. if (Ar.CookContext() && Ar.CookContext()->CookTagList()) { FCookTagList* CookTags = Ar.CookContext()->CookTagList(); CookTags->Add(Object, "TagName", FString(TEXT("TagValue"))); }
Definition at line 31 of file CookTagList.h.
Member Typedef Documentation
FTagNameValuePair
using FCookTagList::FTagNameValuePair = TPair<FName, FString>
Definition at line 34 of file CookTagList.h.
Constructor & Destructor Documentation
FCookTagList()
FCookTagList::FCookTagList (UPackage * InPackage) inline
Definition at line 37 of file CookTagList.h.
References Package.
Member Function Documentation
Add()
void FCookTagList::Add (UObject * InObject, FName InTagName, FString && InTagValue) inline
Adds a tag to the list to be added to the development asset registry for this object.
Note that we only carry over the name/value, not any of the other metadata available when adding tags via GetAssetRegistryTags.
Tags that start with "Diff_" are used for bulk data diff blaming - see DiffAssetBulkDataCommandlet.cpp. When adding diff tags, be sure to add explanatory prose in that commandlet to GBuiltinDiffTagHelp.
Definition at line 47 of file CookTagList.h.
References TArray< InElementType, InAllocatorType >::Add(), ensure, UObjectBaseUtility::GetOutermost(), UObject::IsAsset(), ObjectToTags, and Package.
Reset()
void FCookTagList::Reset () inline
Definition at line 61 of file CookTagList.h.
References ObjectToTags.
Field Documentation
ObjectToTags
TMap<UObject*, TArray<FTagNameValuePair> > FCookTagList::ObjectToTags
Definition at line 35 of file CookTagList.h.
Referenced by Add(), and Reset().
Package
UPackage* FCookTagList::Package
Definition at line 33 of file CookTagList.h.
Referenced by FCookTagList(), and Add().
The documentation for this struct was generated from the following file:
CookTagList.h