Unreal Engine 5.6 C++ API: FMetasoundParameterStorageWrapper Class Reference
FMetasoundParameterStorageWrapper Class Reference
#include "MetasoundParameterPack.h"
Public Member Functions
FMetasoundParameterStorageWrapper ()=default
FMetasoundParameterStorageWrapper (const FMetasoundParameterStorageWrapper &)=default
FMetasoundParameterStorageWrapper (const TSharedPtr< Audio::IProxyData > &InInitData)
FSharedMetasoundParameterStoragePtr Get () const
const FSharedMetasoundParameterStoragePtr & GetPackProxy () const
bool IsPackValid () const
FMetasoundParameterPackStorage * operator-> ()
const FMetasoundParameterPackStorage * operator-> () const
FMetasoundParameterStorageWrapper & operator= (const FMetasoundParameterStorageWrapper &Other)=default
Private Attributes
FSharedMetasoundParameterStoragePtr ParameterStoragePtr
Friends
FORCEINLINE uint32 GetTypeHash (const FMetasoundParameterStorageWrapper &InParameterStorageWrapper)
Detailed Description
Definition at line 465 of file MetasoundParameterPack.h.
Constructor & Destructor Documentation
FMetasoundParameterStorageWrapper() [1/3]
FMetasoundParameterStorageWrapper::FMetasoundParameterStorageWrapper () default
Referenced by FMetasoundParameterStorageWrapper(), GetTypeHash, and operator=().
FMetasoundParameterStorageWrapper() [2/3]
FMetasoundParameterStorageWrapper::FMetasoundParameterStorageWrapper (const FMetasoundParameterStorageWrapper &) default
References FMetasoundParameterStorageWrapper().
FMetasoundParameterStorageWrapper() [3/3]
FMetasoundParameterStorageWrapper::FMetasoundParameterStorageWrapper (const TSharedPtr< Audio::IProxyData > & InInitData) inline
Definition at line 474 of file MetasoundParameterPack.h.
References FMetasoundParameterPackProxy::GetParamStorage(), TSharedPtr< ObjectType, InMode >::IsValid(), and ParameterStoragePtr.
Member Function Documentation
Get()
FSharedMetasoundParameterStoragePtr FMetasoundParameterStorageWrapper::Get () const inline
Definition at line 487 of file MetasoundParameterPack.h.
References ParameterStoragePtr.
GetPackProxy()
const FSharedMetasoundParameterStoragePtr & FMetasoundParameterStorageWrapper::GetPackProxy () const inline
Definition at line 497 of file MetasoundParameterPack.h.
References ParameterStoragePtr.
IsPackValid()
bool FMetasoundParameterStorageWrapper::IsPackValid () const inline
Definition at line 492 of file MetasoundParameterPack.h.
References ParameterStoragePtr.
Referenced by GetTypeHash.
operator->() [1/2]
FMetasoundParameterPackStorage * FMetasoundParameterStorageWrapper::operator-> () inline
Definition at line 507 of file MetasoundParameterPack.h.
References ParameterStoragePtr.
operator->() [2/2]
const FMetasoundParameterPackStorage * FMetasoundParameterStorageWrapper::operator-> () const inline
Definition at line 502 of file MetasoundParameterPack.h.
References ParameterStoragePtr.
operator=()
FMetasoundParameterStorageWrapper & FMetasoundParameterStorageWrapper::operator= (const FMetasoundParameterStorageWrapper & Other) default
References FMetasoundParameterStorageWrapper(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FMetasoundParameterStorageWrapper & InParameterStorageWrapper) friend
Definition at line 512 of file MetasoundParameterPack.h.
References FMetasoundParameterStorageWrapper(), FORCEINLINE, GetTypeHash, INDEX_NONE, IsPackValid(), and FMetasoundParameterPackStorage::Storage.
Referenced by GetTypeHash.
Field Documentation
ParameterStoragePtr
FSharedMetasoundParameterStoragePtr FMetasoundParameterStorageWrapper::ParameterStoragePtr private
Definition at line 467 of file MetasoundParameterPack.h.
Referenced by FMetasoundParameterStorageWrapper(), Get(), GetPackProxy(), IsPackValid(), operator->(), and operator->().
The documentation for this class was generated from the following file:
MetasoundParameterPack.h