Unreal Engine 5.6 C++ API: Metasound::Frontend::FAccessPoint Class Reference
Metasound::Frontend::FAccessPoint Class Reference
FAccessPoint acts as a lifecycle tracker for the TAccessPtrs it creates.
#include "MetasoundAccessPtr.h"
Public Types
using FTokenType = FAccessToken
Public Member Functions
FAccessPoint ()
FAccessPoint (const FAccessPoint &)
FAccessPoint & operator= (const FAccessPoint &)
Private Member Functions
FAccessPoint (FAccessPoint &&)=delete
FAccessPoint & operator= (FAccessPoint &&)=delete
Private Attributes
TSharedPtr< FTokenType > Token
Friends
template<typename AccessPtrType, typename Type>
AccessPtrType MakeAccessPtr (const FAccessPoint &InAccessPoint, Type &InRef)
Detailed Description
FAccessPoint acts as a lifecycle tracker for the TAccessPtrs it creates.
When this object is destructed, all associated TAccessPtrs will become invalid.
Definition at line 194 of file MetasoundAccessPtr.h.
Member Typedef Documentation
FTokenType
using Metasound::Frontend::FAccessPoint::FTokenType = FAccessToken
Definition at line 197 of file MetasoundAccessPtr.h.
Constructor & Destructor Documentation
FAccessPoint() [1/3]
Metasound::Frontend::FAccessPoint::FAccessPoint () inline
Definition at line 199 of file MetasoundAccessPtr.h.
References MakeShared(), and Token.
Referenced by FAccessPoint(), FAccessPoint(), MakeAccessPtr, operator=(), and operator=().
FAccessPoint() [2/3]
Metasound::Frontend::FAccessPoint::FAccessPoint (const FAccessPoint &) inline
Definition at line 204 of file MetasoundAccessPtr.h.
References FAccessPoint(), MakeShared(), and Token.
FAccessPoint() [3/3]
Metasound::Frontend::FAccessPoint::FAccessPoint (FAccessPoint &&) private delete
References FAccessPoint().
Member Function Documentation
operator=() [1/2]
FAccessPoint & Metasound::Frontend::FAccessPoint::operator= (const FAccessPoint &) inline
Definition at line 211 of file MetasoundAccessPtr.h.
References FAccessPoint().
operator=() [2/2]
FAccessPoint & Metasound::Frontend::FAccessPoint::operator= (FAccessPoint &&) private delete
References FAccessPoint().
Friends And Related Symbol Documentation
MakeAccessPtr
template<typename AccessPtrType, typename Type> AccessPtrType MakeAccessPtr (const FAccessPoint & InAccessPoint, Type & InRef) friend
Definition at line 227 of file MetasoundAccessPtr.h.
References FAccessPoint(), and Token.
Field Documentation
Token
TSharedPtr<FTokenType> Metasound::Frontend::FAccessPoint::Token private
Definition at line 223 of file MetasoundAccessPtr.h.
Referenced by FAccessPoint(), FAccessPoint(), and MakeAccessPtr.
The documentation for this class was generated from the following file:
MetasoundAccessPtr.h