Unreal Engine 5.6 C++ API: FBlueprintNamespaceUtilities Struct Reference
FBlueprintNamespaceUtilities Struct Reference
A wrapper struct around various Blueprint namespace utility and support methods.
#include "BlueprintNamespaceUtilities.h"
Public Member Functions
DECLARE_MULTICAST_DELEGATE (FOnDefaultBlueprintNamespaceTypeChanged)
Delegate invoked whenever the default Blueprint namespace type changes.
UE_DEPRECATED (5.1, "Please use GetDefaultImportsForObject instead") static void GetDefaultImportsForBlueprint(const UBlueprint *InBlueprint
Gathers the set of default namespaces that are implicitly imported by a given Blueprint asset.
UE_DEPRECATED (5.1, "Please use the updated version that removes the InStruct parameter (no longer needed).") static void GetPropertyValueNamespaces(const UStruct *InStruct
Static Public Member Functions
static void ConvertPackagePathToNamespacePath (const FString &InPackagePath, FString &OutNamespacePath)
Helper method to convert a package path to a Blueprint namespace identifier string.
static FString GetAssetNamespace (const FAssetData &InAssetData)
Analyzes the given asset to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
static EDefaultBlueprintNamespaceType GetDefaultBlueprintNamespaceType ()
static void GetDefaultImportsForObject (const UObject *InObject, TSet< FString > &OutNamespaces)
Gathers the set of default namespaces that are implicitly imported by a given object's type.
static FString GetObjectNamespace (const FSoftObjectPath &InObjectPath)
Analyzes the given object path to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
static FString GetObjectNamespace (const UObject *InObject)
Analyzes the given object to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
static void GetPropertyValueNamespaces (const FProperty *InProperty, const void *InContainer, TSet< FString > &OutNamespaces)
Analyzes a property value to determine explicitly-assigned namespace identifiers from any object references, or otherwise returns the default namespace for each occurrence (default).
static void GetSharedGlobalImports (TSet< FString > &OutNamespaces)
Gathers the set of global namespaces that are implicitly imported by all Blueprint assets.
static FOnDefaultBlueprintNamespaceTypeChanged & OnDefaultBlueprintNamespaceTypeChanged ()
static void RefreshBlueprintEditorFeatures ()
Refresh the Blueprint editor environment to align with current namespace editor feature settings.
static void SetDefaultBlueprintNamespaceType (EDefaultBlueprintNamespaceType InType)
Sets the default Blueprint namespace type that objects/assets should use when not explicitly assigned.
Data Fields
const FProperty const void * InContainer
const FProperty * InProperty
const FProperty const void TSet< FString > & OutNamespaces
TSet< FString > & OutNamespaces
Detailed Description
A wrapper struct around various Blueprint namespace utility and support methods.
Definition at line 29 of file BlueprintNamespaceUtilities.h.
Member Function Documentation
ConvertPackagePathToNamespacePath()
void FBlueprintNamespaceUtilities::ConvertPackagePathToNamespacePath (const FString & InPackagePath, FString & OutNamespacePath) static
Helper method to convert a package path to a Blueprint namespace identifier string.
Parameters
InPackagePath Package path input string.
OutNamespacePath The input string converted to namespace identifier format.
References ConvertPackagePathToNamespacePath().
Referenced by ConvertPackagePathToNamespacePath().
DECLARE_MULTICAST_DELEGATE()
FBlueprintNamespaceUtilities::DECLARE_MULTICAST_DELEGATE (FOnDefaultBlueprintNamespaceTypeChanged)
Delegate invoked whenever the default Blueprint namespace type changes.
References DECLARE_MULTICAST_DELEGATE().
Referenced by DECLARE_MULTICAST_DELEGATE().
GetAssetNamespace()
FString FBlueprintNamespaceUtilities::GetAssetNamespace (const FAssetData & InAssetData) static
Analyzes the given asset to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
Parameters
InAssetData Input asset data.
Returns
The unique Blueprint namespace identifier associated with the given asset, or an empty string if the asset belongs to the global namespace (default).
GetDefaultBlueprintNamespaceType()
EDefaultBlueprintNamespaceType FBlueprintNamespaceUtilities::GetDefaultBlueprintNamespaceType () static
Returns
The default Blueprint namespace type objects/assets should use. Currently used for debugging/testing.
References GetDefaultBlueprintNamespaceType().
Referenced by GetDefaultBlueprintNamespaceType().
GetDefaultImportsForObject()
void FBlueprintNamespaceUtilities::GetDefaultImportsForObject (const UObject * InObject, TSet< FString > & OutNamespaces) static
Gathers the set of default namespaces that are implicitly imported by a given object's type.
Parameters
InObject A reference to a loaded object or type.
OutNamespaces Zero or more unique namespace identifier(s) representing the type's default namespace set.
References GetDefaultImportsForObject(), and OutNamespaces.
Referenced by GetDefaultImportsForObject().
GetObjectNamespace() [1/2]
FString FBlueprintNamespaceUtilities::GetObjectNamespace (const FSoftObjectPath & InObjectPath) static
Analyzes the given object path to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
Parameters
InObjectPath Path to the given object (may not be loaded yet).
Returns
The unique Blueprint namespace identifier associated with the given object (even if unloaded), or an empty string if the object belongs to the global namespace (default).
GetObjectNamespace() [2/2]
FString FBlueprintNamespaceUtilities::GetObjectNamespace (const UObject * InObject) static
Analyzes the given object to determine its explicitly-assigned namespace identifier, or otherwise returns its default namespace.
Parameters
InObject A reference to the input object.
Returns
The unique Blueprint namespace identifier associated with the given object, or an empty string if the object belongs to the global namespace (default).
GetPropertyValueNamespaces()
void FBlueprintNamespaceUtilities::GetPropertyValueNamespaces (const FProperty * InProperty, const void * InContainer, TSet< FString > & OutNamespaces) static
Analyzes a property value to determine explicitly-assigned namespace identifiers from any object references, or otherwise returns the default namespace for each occurrence (default).
Parameters
InProperty The property for which we will analyze the value.
InContainer The source address of the struct/object containing the property's value.
OutNamespaces Zero or more unique namespace identifier(s) referenced by the property value. An entry with an empty string equates to the default global namespace.
References InContainer, InProperty, and OutNamespaces.
GetSharedGlobalImports()
void FBlueprintNamespaceUtilities::GetSharedGlobalImports (TSet< FString > & OutNamespaces) static
Gathers the set of global namespaces that are implicitly imported by all Blueprint assets.
Parameters
OutNamespaces Zero or more unique namespace identifier(s) representing the shared global namespace set.
References OutNamespaces.
OnDefaultBlueprintNamespaceTypeChanged()
FOnDefaultBlueprintNamespaceTypeChanged & FBlueprintNamespaceUtilities::OnDefaultBlueprintNamespaceTypeChanged () static
References OnDefaultBlueprintNamespaceTypeChanged().
Referenced by OnDefaultBlueprintNamespaceTypeChanged().
RefreshBlueprintEditorFeatures()
void FBlueprintNamespaceUtilities::RefreshBlueprintEditorFeatures () static
Refresh the Blueprint editor environment to align with current namespace editor feature settings.
References RefreshBlueprintEditorFeatures().
Referenced by RefreshBlueprintEditorFeatures().
SetDefaultBlueprintNamespaceType()
void FBlueprintNamespaceUtilities::SetDefaultBlueprintNamespaceType (EDefaultBlueprintNamespaceType InType) static
Sets the default Blueprint namespace type that objects/assets should use when not explicitly assigned.
Parameters
InType Default namespace type to use.
References SetDefaultBlueprintNamespaceType().
Referenced by SetDefaultBlueprintNamespaceType().
UE_DEPRECATED() [1/2]
FBlueprintNamespaceUtilities::UE_DEPRECATED (5. 1, "Please use GetDefaultImportsForObject instead") const
Gathers the set of default namespaces that are implicitly imported by a given Blueprint asset.
Parameters
InBlueprint A reference to a loaded Blueprint asset.
OutNamespaces Zero or more unique namespace identifier(s) representing the Blueprint asset's default namespace set.
UE_DEPRECATED() [2/2]
FBlueprintNamespaceUtilities::UE_DEPRECATED (5. 1, "Please use the updated version that removes the InStruct parameter (no longer needed).") const
Field Documentation
InContainer
const FProperty const void* FBlueprintNamespaceUtilities::InContainer
Definition at line 66 of file BlueprintNamespaceUtilities.h.
Referenced by GetPropertyValueNamespaces().
InProperty
const FProperty* FBlueprintNamespaceUtilities::InProperty
Definition at line 66 of file BlueprintNamespaceUtilities.h.
Referenced by GetPropertyValueNamespaces().
OutNamespaces [1/2]
const FProperty const void TSet<FString>& FBlueprintNamespaceUtilities::OutNamespaces
Initial value:
{
        GetPropertyValueNamespaces(InProperty, InContainer, OutNamespaces)
Definition at line 66 of file BlueprintNamespaceUtilities.h.
Referenced by GetDefaultImportsForObject(), GetPropertyValueNamespaces(), and GetSharedGlobalImports().
OutNamespaces [2/2]
TSet<FString>& FBlueprintNamespaceUtilities::OutNamespaces
Definition at line 85 of file BlueprintNamespaceUtilities.h.
The documentation for this struct was generated from the following file:
BlueprintNamespaceUtilities.h