Unreal Engine 5.6 C++ API: TPropertyActuator< PropertyType > Struct Template Reference
TPropertyActuator< PropertyType > Struct Template Reference
Blending actuator type that knows how to apply values of type PropertyType.
#include "MovieScenePropertyTemplate.h"
Public Member Functions
TPropertyActuator (const PropertyTemplate::FSectionData &InPropertyData)
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< FEulerTransform >::ParamType InValue, const TBlendableTokenStack< FEulerTransform > &OriginalStack, const FMovieSceneContext &Context) const
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< FTransform >::ParamType InValue, const TBlendableTokenStack< FTransform > &OriginalStack, const FMovieSceneContext &Context) const
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< FVector >::ParamType InValue, const TBlendableTokenStack< FVector > &OriginalStack, const FMovieSceneContext &Context) const
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< FVector2D >::ParamType InValue, const TBlendableTokenStack< FVector2D > &OriginalStack, const FMovieSceneContext &Context) const
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< FVector4 >::ParamType InValue, const TBlendableTokenStack< FVector4 > &OriginalStack, const FMovieSceneContext &Context) const
void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< int32 >::ParamType InValue, const TBlendableTokenStack< int32 > &OriginalStack, const FMovieSceneContext &Context) const
virtual void Actuate (FMovieSceneInterrogationData &InterrogationData, typename TCallTraits< PropertyType >::ParamType InValue, const TBlendableTokenStack< PropertyType > &OriginalStack, const FMovieSceneContext &Context) const override
virtual void Actuate (UObject *InObject, typename TCallTraits< PropertyType >::ParamType InFinalValue, const TBlendableTokenStack< PropertyType > &OriginalStack, const FMovieSceneContext &Context, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player) override
virtual PropertyType RetrieveCurrentValue (UObject *InObject, IMovieScenePlayer *Player) const
Retrieve the current value of the specified object.
Public Member Functions inherited from TMovieSceneBlendingActuator< PropertyType >
virtual void Actuate (UObject *InObject, typename TCallTraits< PropertyType >::ParamType InValue, const TBlendableTokenStack< PropertyType > &OriginalStack, const FMovieSceneContext &Context, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player)=0
Apply the the specified value to an object.
FMovieSceneBlendingActuatorID GetActuatorID () const
Access this actuator's unique identifier.
bool HasInitialValue (FObjectKey InObject) const
Check whether this actuator has an initial value for the specified animated object.
virtual void RemoveInitialValueForObject (FObjectKey ObjectToRemove) override
Remove the initial value for the specified object from this actuator causing it to be re-computed next time it is required.
Public Member Functions inherited from IMovieSceneBlendingActuator
virtual ~IMovieSceneBlendingActuator ()
Public Member Functions inherited from TSharedFromThis< IMovieSceneBlendingActuator >
TSharedRef< IMovieSceneBlendingActuator, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IMovieSceneBlendingActuator, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
PropertyTemplate::FSectionData PropertyData
Additional Inherited Members
Protected Member Functions inherited from TMovieSceneBlendingActuator< PropertyType >
TMovieSceneBlendingActuator (FMovieSceneBlendingActuatorID InActuatorID)
Constructor.
Protected Member Functions inherited from TSharedFromThis< IMovieSceneBlendingActuator >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IMovieSceneBlendingActuator >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename PropertyType>
struct TPropertyActuator< PropertyType >
Blending actuator type that knows how to apply values of type PropertyType.
Definition at line 168 of file MovieScenePropertyTemplate.h.
Constructor & Destructor Documentation
TPropertyActuator()
template<typename PropertyType> TPropertyActuator< PropertyType >::TPropertyActuator (const PropertyTemplate::FSectionData & InPropertyData) inline
Definition at line 171 of file MovieScenePropertyTemplate.h.
References TMovieSceneBlendingActuator< PropertyType >::TMovieSceneBlendingActuator(), and PropertyData.
Member Function Documentation
Actuate() [1/8]
void TPropertyActuator< FEulerTransform >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< FEulerTransform >::ParamType InValue, const TBlendableTokenStack< FEulerTransform > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 299 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), FMovieSceneInterrogationKey::GetTransformInterrogationKey(), and Value.
Actuate() [2/8]
void TPropertyActuator< FTransform >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< FTransform >::ParamType InValue, const TBlendableTokenStack< FTransform > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 309 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), FMovieSceneInterrogationKey::GetTransformInterrogationKey(), and Value.
Actuate() [3/8]
void TPropertyActuator< FVector >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< FVector >::ParamType InValue, const TBlendableTokenStack< FVector > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 326 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), FVector, and Value.
Actuate() [4/8]
void TPropertyActuator< FVector2D >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< FVector2D >::ParamType InValue, const TBlendableTokenStack< FVector2D > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 292 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), and Value.
Actuate() [5/8]
void TPropertyActuator< FVector4 >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< FVector4 >::ParamType InValue, const TBlendableTokenStack< FVector4 > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 319 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), and Value.
Actuate() [6/8]
void TPropertyActuator< int32 >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< int32 >::ParamType InValue, const TBlendableTokenStack< int32 > & OriginalStack, const FMovieSceneContext & Context) const inline
Definition at line 285 of file MovieScenePropertyTemplate.h.
References FMovieSceneInterrogationData::Add(), and Value.
Actuate() [7/8]
template<typename PropertyType> virtual void TPropertyActuator< PropertyType >::Actuate (FMovieSceneInterrogationData & InterrogationData, typename TCallTraits< PropertyType >::ParamType InValue, const TBlendableTokenStack< PropertyType > & OriginalStack, const FMovieSceneContext & Context) const inline override virtual
Definition at line 192 of file MovieScenePropertyTemplate.h.
Actuate() [8/8]
template<typename PropertyType> virtual void TPropertyActuator< PropertyType >::Actuate (UObject * InObject, typename TCallTraits< PropertyType >::ParamType InFinalValue, const TBlendableTokenStack< PropertyType > & OriginalStack, const FMovieSceneContext & Context, FPersistentEvaluationData & PersistentData, IMovieScenePlayer & Player) inline override virtual
Definition at line 181 of file MovieScenePropertyTemplate.h.
References ensureMsgf, PropertyData, TBlendableTokenStack< DataType >::SavePreAnimatedState(), and TEXT.
RetrieveCurrentValue()
template<typename PropertyType> virtual PropertyType TPropertyActuator< PropertyType >::RetrieveCurrentValue (UObject * InObject, IMovieScenePlayer * Player) const inline virtual
Retrieve the current value of the specified object.
Parameters
InObject The object to retrieve the value from. nullptr where this actuator is being used for a root track.
Player The movie scene player currently running the sequence. Null when this actuator is used in an interrogation context.
Returns
The current value of the object
Implements TMovieSceneBlendingActuator< PropertyType >.
Definition at line 176 of file MovieScenePropertyTemplate.h.
References PropertyData.
Field Documentation
PropertyData
template<typename PropertyType> PropertyTemplate::FSectionData TPropertyActuator< PropertyType >::PropertyData
Definition at line 170 of file MovieScenePropertyTemplate.h.
Referenced by TPropertyActuator(), Actuate(), and RetrieveCurrentValue().
The documentation for this struct was generated from the following file:
MovieScenePropertyTemplate.h