Unreal Engine 5.6 C++ API: FSkeletalMeshAttributes Class Reference
FSkeletalMeshAttributes Class Reference
#include "SkeletalMeshAttributes.h"
Public Member Functions
SKELETALMESHDESCRIPTION_API FSkeletalMeshAttributes (FMeshDescription &InMeshDescription)
SKELETALMESHDESCRIPTION_API TAttributesSet< FBoneID > & BoneAttributes ()
SKELETALMESHDESCRIPTION_API FBoneArray & Bones ()
SKELETALMESHDESCRIPTION_API FBoneID CreateBone ()
Adds a new bone and returns its ID.
SKELETALMESHDESCRIPTION_API void CreateBone (const FBoneID BoneID)
Adds a new bone with the given ID.
SKELETALMESHDESCRIPTION_API FSourceGeometryPartID CreateSourceGeometryPart ()
SKELETALMESHDESCRIPTION_API void DeleteBone (const FBoneID BoneID)
Deletes a bone with the given ID.
SKELETALMESHDESCRIPTION_API void DeleteSourceGeometryPart (FSourceGeometryPartID InSourceGeometryPartID)
SKELETALMESHDESCRIPTION_API FBoneColorAttributesRef GetBoneColors ()
SKELETALMESHDESCRIPTION_API FBoneNameAttributesRef GetBoneNames ()
SKELETALMESHDESCRIPTION_API FBoneParentIndexAttributesRef GetBoneParentIndices ()
SKELETALMESHDESCRIPTION_API FBonePoseAttributesRef GetBonePoses ()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartNameRef GetSourceGeometryPartNames ()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartVertexOffsetAndCountRef GetSourceGeometryPartVertexOffsetAndCounts ()
SKELETALMESHDESCRIPTION_API TVertexInstanceAttributesRef< FVector3f > GetVertexInstanceMorphNormalDelta (const FName InMorphTargetName)
Returns a writable vertex instance normal delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API TVertexAttributesRef< FVector3f > GetVertexMorphPositionDelta (const FName InMorphTargetName)
Returns a writable vertex position delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesRef GetVertexSkinWeights (const FName InProfileName=NAME_None)
Returns the skin weight profile given by its name. NAME_None corresponds to the default profile.
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesRef GetVertexSkinWeightsFromAttributeName (const FName InAttributeName=NAME_None)
virtual SKELETALMESHDESCRIPTION_API void Register (bool bKeepExistingAttribute=false) override
SKELETALMESHDESCRIPTION_API void RegisterColorAttribute ()
Register an optional color attribute for bones.
SKELETALMESHDESCRIPTION_API bool RegisterImportPointIndexAttribute ()
Register an attribute that can be used to maintain a relationship between a given vertex and the point it originated from on the original imported mesh.
SKELETALMESHDESCRIPTION_API bool RegisterMorphTargetAttribute (const FName InMorphTargetName, const bool bIncludeNormals)
Register a new morph target with the given name.
SKELETALMESHDESCRIPTION_API bool RegisterSkinWeightAttribute (const FName InProfileName)
Register a new skin weight profile with the given name.
SKELETALMESHDESCRIPTION_API void RegisterSourceGeometryPartsAttributes ()
This will register the source geometry attributes and their element container on the mesh description so that source geometry part information can be stored.
SKELETALMESHDESCRIPTION_API void ReserveNewBones (const int InNumBones)
Reserves space for this number of new bones.
SKELETALMESHDESCRIPTION_API TAttributesSet< FSourceGeometryPartID > & SourceGeometryPartAttributes ()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartArray & SourceGeometryParts ()
SKELETALMESHDESCRIPTION_API void UnregisterImportPointIndexAttribute ()
Convenience function to unregister the attribute that maintains the relationship between a given vertex and the originating point on the import mesh.
SKELETALMESHDESCRIPTION_API bool UnregisterMorphTargetAttribute (const FName InMorphTargetName)
Unregister an existing morph target with the given name (as returned by GetMorphTargetNames()).
SKELETALMESHDESCRIPTION_API bool UnregisterSkinWeightAttribute (const FName InProfileName)
Unregister an existing skin weight profile with the given name Returns true if theprofile was successfully unregistered.
Public Member Functions inherited from FStaticMeshAttributes
FStaticMeshAttributes (FMeshDescription &InMeshDescription)
TEdgeAttributesRef< bool > GetEdgeHardnesses ()
TEdgeAttributesConstRef< bool > GetEdgeHardnesses () const
TPolygonGroupAttributesRef< FName > GetPolygonGroupMaterialSlotNames ()
TPolygonGroupAttributesConstRef< FName > GetPolygonGroupMaterialSlotNames () const
TTriangleAttributesRef< FVector3f > GetTriangleBinormals ()
TTriangleAttributesConstRef< FVector3f > GetTriangleBinormals () const
TTriangleAttributesRef< FVector3f > GetTriangleNormals ()
TTriangleAttributesConstRef< FVector3f > GetTriangleNormals () const
TTriangleAttributesRef< FVector3f > GetTriangleTangents ()
TTriangleAttributesConstRef< FVector3f > GetTriangleTangents () const
TVertexInstanceAttributesRef< float > GetVertexInstanceBinormalSigns ()
TVertexInstanceAttributesConstRef< float > GetVertexInstanceBinormalSigns () const
TVertexInstanceAttributesRef< FVector4f > GetVertexInstanceColors ()
TVertexInstanceAttributesConstRef< FVector4f > GetVertexInstanceColors () const
TVertexInstanceAttributesRef< FVector3f > GetVertexInstanceNormals ()
TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceNormals () const
TVertexInstanceAttributesRef< FVector3f > GetVertexInstanceTangents ()
TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceTangents () const
TVertexInstanceAttributesRef< FVector2f > GetVertexInstanceUVs ()
TVertexInstanceAttributesConstRef< FVector2f > GetVertexInstanceUVs () const
STATICMESHDESCRIPTION_API void RegisterTriangleNormalAndTangentAttributes ()
UE_DEPRECATED (4.26, "Please use RegisterTriangleNormalAndTangentAttributes() instead.") STATICMESHDESCRIPTION_API void RegisterPolygonNormalAndTangentAttributes()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TEdgeAttributesConstRef< float > GetEdgeCreaseSharpnesses() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TEdgeAttributesRef< float > GetEdgeCreaseSharpnesses()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonBinormals() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonCenters() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonNormals() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonTangents() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonBinormals()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonCenters()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonNormals()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonTangents()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TVertexAttributesConstRef< float > GetVertexCornerSharpnesses() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TVertexAttributesRef< float > GetVertexCornerSharpnesses()
Public Member Functions inherited from FMeshAttributes
FMeshAttributes (FMeshDescription &InMeshDescription)
virtual ~FMeshAttributes ()=default
TEdgeAttributesRef< TArrayView< FVertexID > > GetEdgeVertexIndices ()
Accessors for array of vertex IDs for edges.
TEdgeAttributesConstRef< TArrayView< FVertexID > > GetEdgeVertexIndices () const
TPolygonAttributesRef< FPolygonGroupID > GetPolygonPolygonGroupIndices ()
Accessors for array of polygon group IDs for polygons.
TPolygonAttributesConstRef< FPolygonGroupID > GetPolygonPolygonGroupIndices () const
TTriangleAttributesRef< TArrayView< FEdgeID > > GetTriangleEdgeIndices ()
Accessors for array of edge IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FEdgeID > > GetTriangleEdgeIndices () const
TTriangleAttributesRef< FPolygonGroupID > GetTrianglePolygonGroupIndices ()
Accessors for array of polygon group IDs for triangles.
TTriangleAttributesConstRef< FPolygonGroupID > GetTrianglePolygonGroupIndices () const
TTriangleAttributesRef< TArrayView< FUVID > > GetTriangleUVIndices ()
Accessors for array of UV IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FUVID > > GetTriangleUVIndices () const
TTriangleAttributesRef< TArrayView< FVertexID > > GetTriangleVertexIndices ()
Accessors for array of vertex IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FVertexID > > GetTriangleVertexIndices () const
TTriangleAttributesRef< TArrayView< FVertexInstanceID > > GetTriangleVertexInstanceIndices ()
Accessors for array of vertex instance IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FVertexInstanceID > > GetTriangleVertexInstanceIndices () const
TUVAttributesRef< FVector2f > GetUVCoordinates (int32 UVChannel)
Accessors for UV coordinates.
TUVAttributesConstRef< FVector2f > GetUVCoordinates (int32 UVChannel) const
TVertexInstanceAttributesRef< FVertexID > GetVertexInstanceVertexIndices ()
Accessors for array of vertex IDs for vertex instances.
TVertexInstanceAttributesConstRef< FVertexID > GetVertexInstanceVertexIndices () const
TVertexAttributesRef< FVector3f > GetVertexPositions ()
Accessors for cached vertex position array.
TVertexAttributesConstRef< FVector3f > GetVertexPositions () const
Public Member Functions inherited from FSkeletalMeshAttributesShared
SKELETALMESHDESCRIPTION_API FSkeletalMeshAttributesShared (const FMeshDescription &InMeshDescription)
SKELETALMESHDESCRIPTION_API const TAttributesSet< FBoneID > & BoneAttributes () const
SKELETALMESHDESCRIPTION_API const FBoneArray & Bones () const
SKELETALMESHDESCRIPTION_API FBoneColorAttributesConstRef GetBoneColors () const
SKELETALMESHDESCRIPTION_API FBoneNameAttributesConstRef GetBoneNames () const
SKELETALMESHDESCRIPTION_API FBoneParentIndexAttributesConstRef GetBoneParentIndices () const
SKELETALMESHDESCRIPTION_API FBonePoseAttributesConstRef GetBonePoses () const
SKELETALMESHDESCRIPTION_API TArray< FName > GetMorphTargetNames () const
Returns the list of all registered morph targets on this mesh.
SKELETALMESHDESCRIPTION_API int32 GetNumBones () const
SKELETALMESHDESCRIPTION_API int32 GetNumSourceGeometryParts () const
SKELETALMESHDESCRIPTION_API TArray< FName > GetSkinWeightProfileNames (const bool bInUserDefinedOnly=false) const
Returns the list of all registered skin weight profile names on this mesh.
SKELETALMESHDESCRIPTION_API FSourceGeometryPartNameConstRef GetSourceGeometryPartNames () const
SKELETALMESHDESCRIPTION_API FSourceGeometryPartVertexOffsetAndCountConstRef GetSourceGeometryPartVertexOffsetAndCounts () const
SKELETALMESHDESCRIPTION_API TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceMorphNormalDelta (const FName InMorphTargetName) const
Returns a read-only vertex instance normal delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API TVertexAttributesConstRef< FVector3f > GetVertexMorphPositionDelta (const FName InMorphTargetName) const
Returns a read-only vertex position delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef GetVertexSkinWeights (const FName InProfileName=NAME_None) const
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef GetVertexSkinWeightsFromAttributeName (const FName InAttributeName=NAME_None) const
SKELETALMESHDESCRIPTION_API bool HasBoneColorAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBoneNameAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBoneParentIndexAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBonePoseAttribute () const
bool HasBones () const
SKELETALMESHDESCRIPTION_API bool HasMorphTargetNormalsAttribute (const FName InMorphTargetName) const
SKELETALMESHDESCRIPTION_API bool HasMorphTargetPositionsAttribute (const FName InMorphTargetName) const
bool HasSourceGeometryParts () const
SKELETALMESHDESCRIPTION_API bool IsBoneValid (const FBoneID BoneID) const
SKELETALMESHDESCRIPTION_API bool IsSourceGeometryPartValid (const FSourceGeometryPartID InSourceGeometryPartID) const
SKELETALMESHDESCRIPTION_API const TAttributesSet< FSourceGeometryPartID > & SourceGeometryPartAttributes () const
SKELETALMESHDESCRIPTION_API const FSourceGeometryPartArray & SourceGeometryParts () const
Static Public Member Functions
static bool IsReservedAttributeName (const FName InAttributeName)
Returns true if a given attribute name is a name for a reserved attribute or not.
Static Public Member Functions inherited from FStaticMeshAttributes
static bool IsReservedAttributeName (const FName InAttributeName)
Static Public Member Functions inherited from FMeshAttributes
static bool IsReservedAttributeName (const FName InAttributeName)
Static Public Member Functions inherited from FSkeletalMeshAttributesShared
static SKELETALMESHDESCRIPTION_API FName GetMorphTargetNameFromAttribute (const FName InAttributeName)
Returns the name of a morph target given the attribute name. If the given attribute name is invalid, NAME_None is returned.
static SKELETALMESHDESCRIPTION_API FName GetProfileNameFromAttribute (const FName InAttributeName)
Returns a skin profile name from the attribute name, if the attribute name is a valid skin weights attribute.
static SKELETALMESHDESCRIPTION_API bool IsMorphTargetAttribute (const FName InAttributeName)
Returns true if the given attribute name refers to a morph target attribute.
static SKELETALMESHDESCRIPTION_API bool IsSkinWeightAttribute (const FName InAttributeName)
Helper function that indicates whether an attribute name represents a skin weight attribute.
static SKELETALMESHDESCRIPTION_API bool IsValidSkinWeightProfileName (const FName InProfileName)
Returns true if the given identifier is a valid profile name.
Private Attributes
FMeshElementChannels * BoneElements = nullptr
FMeshElementChannels * SourceGeometryPartElements = nullptr
Additional Inherited Members
Public Types inherited from FSkeletalMeshAttributesShared
using FBoneArray = TMeshElementContainer<FBoneID>
using FBoneColorAttributesConstRef = TMeshAttributesConstRef<FBoneID, FVector4f>
using FBoneColorAttributesRef = TMeshAttributesRef<FBoneID, FVector4f>
using FBoneNameAttributesConstRef = TMeshAttributesConstRef<FBoneID, FName>
using FBoneNameAttributesRef = TMeshAttributesRef<FBoneID, FName>
using FBoneParentIndexAttributesConstRef = TMeshAttributesConstRef<FBoneID, int32>
using FBoneParentIndexAttributesRef = TMeshAttributesRef<FBoneID, int32>
using FBonePoseAttributesConstRef = TMeshAttributesConstRef<FBoneID, FTransform>
using FBonePoseAttributesRef = TMeshAttributesRef<FBoneID, FTransform>
using FSourceGeometryPartArray = TMeshElementContainer<FSourceGeometryPartID>
using FSourceGeometryPartNameConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, FName>
using FSourceGeometryPartNameRef = TMeshAttributesRef<FSourceGeometryPartID, FName>
using FSourceGeometryPartVertexOffsetAndCountConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, TArrayView<int32>>
using FSourceGeometryPartVertexOffsetAndCountRef = TMeshAttributesRef<FSourceGeometryPartID, TArrayView<int32>>
Static Public Attributes inherited from FSkeletalMeshAttributesShared
static SKELETALMESHDESCRIPTION_API FName BonesElementName
Name of the mesh element type representing bones.
static SKELETALMESHDESCRIPTION_API FName DefaultSkinWeightProfileName
static SKELETALMESHDESCRIPTION_API FName SourceGeometryPartElementName
Name of the mesh element representing import data for meshes that were imported from separate geometries into a single skeletal mesh piece.
Static Protected Member Functions inherited from FSkeletalMeshAttributesShared
static SKELETALMESHDESCRIPTION_API FName CreateMorphTargetAttributeName (const FName InMorphTargetName)
Construct a name for a morph target attribute with the given a user-visible morph target name.
static SKELETALMESHDESCRIPTION_API FName CreateSkinWeightAttributeName (const FName InProfileName)
Construct a name for a skin weight attribute with the given skin weight profile name.
Protected Attributes inherited from FMeshAttributes
FMeshDescription & MeshDescription
Protected Attributes inherited from FSkeletalMeshAttributesShared
const FMeshElementChannels * BoneElementsShared = nullptr
const FMeshElementChannels * SourceGeometryPartElementsShared = nullptr
Detailed Description
Definition at line 218 of file SkeletalMeshAttributes.h.
Constructor & Destructor Documentation
FSkeletalMeshAttributes()
SKELETALMESHDESCRIPTION_API FSkeletalMeshAttributes::FSkeletalMeshAttributes (FMeshDescription & InMeshDescription) explicit
Member Function Documentation
BoneAttributes()
SKELETALMESHDESCRIPTION_API TAttributesSet< FBoneID > & FSkeletalMeshAttributes::BoneAttributes ()
Bones()
SKELETALMESHDESCRIPTION_API FBoneArray & FSkeletalMeshAttributes::Bones ()
CreateBone() [1/2]
SKELETALMESHDESCRIPTION_API FBoneID FSkeletalMeshAttributes::CreateBone ()
Adds a new bone and returns its ID.
CreateBone() [2/2]
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::CreateBone (const FBoneID BoneID)
Adds a new bone with the given ID.
CreateSourceGeometryPart()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartID FSkeletalMeshAttributes::CreateSourceGeometryPart ()
DeleteBone()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::DeleteBone (const FBoneID BoneID)
Deletes a bone with the given ID.
DeleteSourceGeometryPart()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::DeleteSourceGeometryPart (FSourceGeometryPartID InSourceGeometryPartID)
GetBoneColors()
SKELETALMESHDESCRIPTION_API FBoneColorAttributesRef FSkeletalMeshAttributes::GetBoneColors ()
GetBoneNames()
SKELETALMESHDESCRIPTION_API FBoneNameAttributesRef FSkeletalMeshAttributes::GetBoneNames ()
GetBoneParentIndices()
SKELETALMESHDESCRIPTION_API FBoneParentIndexAttributesRef FSkeletalMeshAttributes::GetBoneParentIndices ()
GetBonePoses()
SKELETALMESHDESCRIPTION_API FBonePoseAttributesRef FSkeletalMeshAttributes::GetBonePoses ()
GetSourceGeometryPartNames()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartNameRef FSkeletalMeshAttributes::GetSourceGeometryPartNames ()
GetSourceGeometryPartVertexOffsetAndCounts()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartVertexOffsetAndCountRef FSkeletalMeshAttributes::GetSourceGeometryPartVertexOffsetAndCounts ()
GetVertexInstanceMorphNormalDelta()
SKELETALMESHDESCRIPTION_API TVertexInstanceAttributesRef< FVector3f > FSkeletalMeshAttributes::GetVertexInstanceMorphNormalDelta (const FName InMorphTargetName)
Returns a writable vertex instance normal delta attribute for the given morph target.
The delta is the difference between the normal vector of the mesh and the normal vector of the desired morphed mesh. Adding this value to the normal vector of the mesh will return the morph's normal vector for this vertex instance. If the morph was not registered to include normals, this will return an invalid attribute.
GetVertexMorphPositionDelta()
SKELETALMESHDESCRIPTION_API TVertexAttributesRef< FVector3f > FSkeletalMeshAttributes::GetVertexMorphPositionDelta (const FName InMorphTargetName)
Returns a writable vertex position delta attribute for the given morph target.
The delta is the difference between the point position of the mesh and the point position of the morphed mesh. Adding this value to the point position of the mesh will return the morph point position.
GetVertexSkinWeights()
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesRef FSkeletalMeshAttributes::GetVertexSkinWeights (const FName InProfileName = NAME_None)
Returns the skin weight profile given by its name. NAME_None corresponds to the default profile.
GetVertexSkinWeightsFromAttributeName()
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesRef FSkeletalMeshAttributes::GetVertexSkinWeightsFromAttributeName (const FName InAttributeName = NAME_None)
IsReservedAttributeName()
bool FSkeletalMeshAttributes::IsReservedAttributeName (const FName InAttributeName) inline static
Returns true if a given attribute name is a name for a reserved attribute or not.
If not a reserved attribute, it's one that has been user-defined and is not required by any system.
Definition at line 231 of file SkeletalMeshAttributes.h.
References MeshAttribute::Bone::Color, FSkeletalMeshAttributesShared::IsMorphTargetAttribute(), FStaticMeshAttributes::IsReservedAttributeName(), FSkeletalMeshAttributesShared::IsSkinWeightAttribute(), MeshAttribute::Bone::Name, MeshAttribute::Bone::ParentIndex, and MeshAttribute::Bone::Pose.
Register()
virtual SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::Register (bool bKeepExistingAttribute = false) override virtual
Reimplemented from FStaticMeshAttributes.
RegisterColorAttribute()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::RegisterColorAttribute ()
Register an optional color attribute for bones.
RegisterImportPointIndexAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributes::RegisterImportPointIndexAttribute ()
Register an attribute that can be used to maintain a relationship between a given vertex and the point it originated from on the original imported mesh.
This can be useful when trying to match the stored mesh to the import mesh as stored in the import file (e.g. FBX, Alembic, glTF, etc).
RegisterMorphTargetAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributes::RegisterMorphTargetAttribute (const FName InMorphTargetName, const bool bIncludeNormals)
Register a new morph target with the given name.
The attribute name will encode the user-defined morph target name and it will be listed in GetMorphTargetNames(). Returns true if the morph target was successfully registered. Returns false if the attribute was already registered or if InMorphTargetName is empty. The position delta is stored as a vertex attributes, and the optional normal is stored as a vertex instance attribute to allow for hard edges on morph targets.
Parameters
InMorphTargetName The name of the morph target to add. Cannot be empty.
bIncludeNormals Set to true if per-vertex instance normals (Z-tangent) should be included. Otherwise the normals will be automatically computed and only the position delta vertex attribute registered.
RegisterSkinWeightAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributes::RegisterSkinWeightAttribute (const FName InProfileName)
Register a new skin weight profile with the given name.
The attribute name will encode the profile name and it will be listed in GetSkinWeightProfileNames(). Returns true if the profile was successfully registered. Returns false if the attribute was already registered or if IsValidSkinWeightProfileName() returned false.
RegisterSourceGeometryPartsAttributes()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::RegisterSourceGeometryPartsAttributes ()
This will register the source geometry attributes and their element container on the mesh description so that source geometry part information can be stored.
ReserveNewBones()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::ReserveNewBones (const int InNumBones)
Reserves space for this number of new bones.
SourceGeometryPartAttributes()
SKELETALMESHDESCRIPTION_API TAttributesSet< FSourceGeometryPartID > & FSkeletalMeshAttributes::SourceGeometryPartAttributes ()
SourceGeometryParts()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartArray & FSkeletalMeshAttributes::SourceGeometryParts ()
UnregisterImportPointIndexAttribute()
SKELETALMESHDESCRIPTION_API void FSkeletalMeshAttributes::UnregisterImportPointIndexAttribute ()
Convenience function to unregister the attribute that maintains the relationship between a given vertex and the originating point on the import mesh.
Use if updating the mesh description but no longer maintaining this relationship (e.g. the topology changed and so this map cannot possibly be accurate).
UnregisterMorphTargetAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributes::UnregisterMorphTargetAttribute (const FName InMorphTargetName)
Unregister an existing morph target with the given name (as returned by GetMorphTargetNames()).
Returns true if the morph target was successfully unregistered. Returns false if the attribute wasn't registered or if InMorphTargetName is empty.
UnregisterSkinWeightAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributes::UnregisterSkinWeightAttribute (const FName InProfileName)
Unregister an existing skin weight profile with the given name Returns true if theprofile was successfully unregistered.
Returns false if the attribute wasn't registered or if InProfileName is empty.
Field Documentation
BoneElements
FMeshElementChannels* FSkeletalMeshAttributes::BoneElements = nullptr private
Definition at line 357 of file SkeletalMeshAttributes.h.
SourceGeometryPartElements
FMeshElementChannels* FSkeletalMeshAttributes::SourceGeometryPartElements = nullptr private
Definition at line 358 of file SkeletalMeshAttributes.h.
The documentation for this class was generated from the following file:
SkeletalMeshAttributes.h