Unreal Engine 5.6 C++ API: UE::MovieScene::FSubSequencePath Struct Reference
UE::MovieScene::FSubSequencePath Struct Reference
A path of unaccumulated sequence IDs ordered from child->parent->grandparent that is used to generate unique sequenceIDs for inner sequences Optimized for Remap rather than Push/Pop by keeping sequence IDs child-parent order (the order they are required for remapping)
#include "MovieSceneRootOverridePath.h"
Data Structures
struct FSequenceIDPair
Public Member Functions
MOVIESCENE_API FSubSequencePath ()
Default construction to a root path.
MOVIESCENE_API FSubSequencePath (FMovieSceneSequenceID LeafID, const FMovieSceneSequenceHierarchy *RootHierarchy)
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
MOVIESCENE_API FSubSequencePath (FMovieSceneSequenceID LeafID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
MOVIESCENE_API bool Contains (FMovieSceneSequenceID SequenceID) const
Check whether this path contains the specified sequence ID.
MOVIESCENE_API FMovieSceneSequenceID MakeLocalSequenceID (FMovieSceneSequenceID ParentSequenceID) const
MOVIESCENE_API FMovieSceneSequenceID MakeLocalSequenceID (FMovieSceneSequenceID ParentSequenceID, FMovieSceneSequenceID TargetSequenceID) const
MOVIESCENE_API int32 NumGenerationsFromLeaf (FMovieSceneSequenceID SequenceID) const
Return the number of generations between this path's leaf node, and the specified sequence ID.
MOVIESCENE_API int32 NumGenerationsFromRoot (FMovieSceneSequenceID SequenceID) const
Return the number of generations between the root and the specified sequence ID.
MOVIESCENE_API void PopGenerations (int32 NumGenerations)
MOVIESCENE_API void PopTo (FMovieSceneSequenceID ParentSequenceID)
MOVIESCENE_API void PushGeneration (FMovieSceneSequenceID AccumulatedSequenceID, FMovieSceneSequenceID UnaccumulatedSequenceID)
MOVIESCENE_API void Reset ()
Reset this path to its default state (pointing to the root sequence)
MOVIESCENE_API void Reset (FMovieSceneSequenceID LeafID, const FMovieSceneSequenceHierarchy *RootHierarchy)
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
FMovieSceneSequenceID ResolveChildSequenceID (FMovieSceneSequenceID SequenceID) const
Remap the specified sequence ID based on the currently evaluating sequence path, to the Root.
UE_DEPRECATED (5.5, "Please use the version that takes an FSharedPlaybackState") MOVIESCENE_API explicit FSubSequencePath(FMovieSceneSequenceID LeafID
Static Public Member Functions
static MOVIESCENE_API FMovieSceneSequenceID FindCommonParent (const FSubSequencePath &A, const FSubSequencePath &B)
Find the first parent sequence ID that is common to both A and B.
Data Fields
IMovieScenePlayer & Player
Private Attributes
TArray< FSequenceIDPair, TInlineAllocator< 8 > > PathToRoot
A reverse path of deterministic sequence IDs required to accumulate from local -> root.
Detailed Description
A path of unaccumulated sequence IDs ordered from child->parent->grandparent that is used to generate unique sequenceIDs for inner sequences Optimized for Remap rather than Push/Pop by keeping sequence IDs child-parent order (the order they are required for remapping)
Definition at line 24 of file MovieSceneRootOverridePath.h.
Constructor & Destructor Documentation
FSubSequencePath() [1/3]
MOVIESCENE_API UE::MovieScene::FSubSequencePath::FSubSequencePath ()
Default construction to a root path.
Referenced by FSubSequencePath(), and FindCommonParent().
FSubSequencePath() [2/3]
MOVIESCENE_API UE::MovieScene::FSubSequencePath::FSubSequencePath (FMovieSceneSequenceID LeafID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) explicit
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
Parameters
LeafID ID of the child-most sequence to include in this path
Player Player from which to retrieve the hierarchy
FSubSequencePath() [3/3]
MOVIESCENE_API UE::MovieScene::FSubSequencePath::FSubSequencePath (FMovieSceneSequenceID LeafID, const FMovieSceneSequenceHierarchy * RootHierarchy) explicit
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
Parameters
LeafID ID of the child-most sequence to include in this path
RootHierarchy Hierarchy to get sequence IDs from
References FSubSequencePath().
Member Function Documentation
Contains()
MOVIESCENE_API bool UE::MovieScene::FSubSequencePath::Contains (FMovieSceneSequenceID SequenceID) const
Check whether this path contains the specified sequence ID.
Parameters
SequenceID ID of the sequence to check for
Returns
true if this path contains the sequence ID (or SequenceID == MovieSceneSequenceID::Root), false otherwise
FindCommonParent()
MOVIESCENE_API FMovieSceneSequenceID UE::MovieScene::FSubSequencePath::FindCommonParent (const FSubSequencePath & A, const FSubSequencePath & B) static
Find the first parent sequence ID that is common to both A and B.
Parameters
A The first sequence path
B The second sequence path
Returns
The leaf-most parent common to both paths, or MovieSceneSequenceID::Root
References FSubSequencePath(), A, B, and FindCommonParent().
Referenced by FindCommonParent().
MakeLocalSequenceID() [1/2]
MOVIESCENE_API FMovieSceneSequenceID UE::MovieScene::FSubSequencePath::MakeLocalSequenceID (FMovieSceneSequenceID ParentSequenceID) const
Parameters
return
MakeLocalSequenceID() [2/2]
MOVIESCENE_API FMovieSceneSequenceID UE::MovieScene::FSubSequencePath::MakeLocalSequenceID (FMovieSceneSequenceID ParentSequenceID, FMovieSceneSequenceID TargetSequenceID) const
NumGenerationsFromLeaf()
MOVIESCENE_API int32 UE::MovieScene::FSubSequencePath::NumGenerationsFromLeaf (FMovieSceneSequenceID SequenceID) const
Return the number of generations between this path's leaf node, and the specified sequence ID.
Parameters
SequenceID ID of the parent sequence to count generations to
Returns
The number of generations between the two nodes. (ie, 0 where SequenceID == Leaf, 1 for Immediate parents, 2 for grandparents etc)
NumGenerationsFromRoot()
MOVIESCENE_API int32 UE::MovieScene::FSubSequencePath::NumGenerationsFromRoot (FMovieSceneSequenceID SequenceID) const
Return the number of generations between the root and the specified sequence ID.
Parameters
SequenceID ID of the child sequence to count generations to
Returns
The number of generations between the two nodes. (ie, 0 where SequenceID == Root, 1 for Immediate children, 2 for grandchildren)
PopGenerations()
MOVIESCENE_API void UE::MovieScene::FSubSequencePath::PopGenerations (int32 NumGenerations)
PopTo()
MOVIESCENE_API void UE::MovieScene::FSubSequencePath::PopTo (FMovieSceneSequenceID ParentSequenceID)
PushGeneration()
MOVIESCENE_API void UE::MovieScene::FSubSequencePath::PushGeneration (FMovieSceneSequenceID AccumulatedSequenceID, FMovieSceneSequenceID UnaccumulatedSequenceID)
Reset() [1/2]
MOVIESCENE_API void UE::MovieScene::FSubSequencePath::Reset ()
Reset this path to its default state (pointing to the root sequence)
Reset() [2/2]
MOVIESCENE_API void UE::MovieScene::FSubSequencePath::Reset (FMovieSceneSequenceID LeafID, const FMovieSceneSequenceHierarchy * RootHierarchy)
Set up this path from a specific sequence ID that points to a particular sequence in the specified hierarchy.
Parameters
LeafID ID of the child-most sequence to include in this path
RootHierarchy Hierarchy to get sequence IDs from
ResolveChildSequenceID()
FMovieSceneSequenceID UE::MovieScene::FSubSequencePath::ResolveChildSequenceID (FMovieSceneSequenceID SequenceID) const inline
Remap the specified sequence ID based on the currently evaluating sequence path, to the Root.
Parameters
SequenceID The sequence ID to find a template for
Returns
Pointer to a template instance, or nullptr if the ID was not found
Definition at line 67 of file MovieSceneRootOverridePath.h.
References LIKELY, Parent, PathToRoot, and ResolveChildSequenceID().
Referenced by ResolveChildSequenceID().
UE_DEPRECATED()
UE::MovieScene::FSubSequencePath::UE_DEPRECATED (5. 5, "Please use the version that takes an FSharedPlaybackState")
Field Documentation
PathToRoot
TArray<FSequenceIDPair, TInlineAllocator<8> > UE::MovieScene::FSubSequencePath::PathToRoot private
A reverse path of deterministic sequence IDs required to accumulate from local -> root.
Definition at line 147 of file MovieSceneRootOverridePath.h.
Referenced by ResolveChildSequenceID().
Player
IMovieScenePlayer& UE::MovieScene::FSubSequencePath::Player
Definition at line 40 of file MovieSceneRootOverridePath.h.
The documentation for this struct was generated from the following file:
MovieSceneRootOverridePath.h