Unreal Engine 5.6 C++ API: ISoundWaveLoadingBehaviorUtil::FClassData Struct Reference
ISoundWaveLoadingBehaviorUtil::FClassData Struct Reference
#include "SoundWaveLoadingBehavior.h"
Public Member Functions
FClassData ()=default
FClassData (const USoundClass *InClass)
bool CompareGreater (const FClassData &, const ITargetPlatform *) const
Data Fields
FPerPlatformFloat LengthOfFirstChunkInSeconds
ESoundWaveLoadingBehavior LoadingBehavior = ESoundWaveLoadingBehavior::Uninitialized
Detailed Description
Definition at line 53 of file SoundWaveLoadingBehavior.h.
Constructor & Destructor Documentation
FClassData() [1/2]
ISoundWaveLoadingBehaviorUtil::FClassData::FClassData () default
References FClassData().
Referenced by FClassData(), and CompareGreater().
FClassData() [2/2]
ISoundWaveLoadingBehaviorUtil::FClassData::FClassData (const USoundClass * InClass)
Definition at line 397 of file SoundWaveLoadingBehavior.cpp.
References LengthOfFirstChunkInSeconds, and LoadingBehavior.
Member Function Documentation
CompareGreater()
bool ISoundWaveLoadingBehaviorUtil::FClassData::CompareGreater (const FClassData & InOther, const ITargetPlatform * InPlatform) const
Definition at line 403 of file SoundWaveLoadingBehavior.cpp.
References FClassData(), LengthOfFirstChunkInSeconds, and LoadingBehavior.
Referenced by FSoundWaveLoadingBehaviorUtil::FindOwningLoadingBehavior().
Field Documentation
LengthOfFirstChunkInSeconds
FPerPlatformFloat ISoundWaveLoadingBehaviorUtil::FClassData::LengthOfFirstChunkInSeconds
Definition at line 61 of file SoundWaveLoadingBehavior.h.
Referenced by FClassData(), CompareGreater(), and FSoundWaveLoadingBehaviorUtil::WalkClassHierarchy().
LoadingBehavior
ESoundWaveLoadingBehavior ISoundWaveLoadingBehaviorUtil::FClassData::LoadingBehavior = ESoundWaveLoadingBehavior::Uninitialized
Definition at line 60 of file SoundWaveLoadingBehavior.h.
Referenced by FClassData(), CompareGreater(), and FSoundWaveLoadingBehaviorUtil::WalkClassHierarchy().
The documentation for this struct was generated from the following files:
SoundWaveLoadingBehavior.h
SoundWaveLoadingBehavior.cpp