Unreal Engine 5.6 C++ API: TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy > Class Template Reference
TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy > Class Template Reference
The base class of striped maps which is a wrapper that adds thread-safety and contention reduction over regular maps.
#include "StripedMap.h"
Data Structures
struct FBucket
struct FDebuggableExclusiveLock
struct FDebuggableMutex
struct FDebuggableSharedLock
Public Types
typedef BaseMapType::KeyConstPointerType KeyConstPointerType
typedef KeyFuncs KeyFuncsType
typedef BaseMapType MapType
Public Member Functions
void Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
void Add (const KeyType &InKey, ValueType &&InValue)
Set the value associated with a key.
void Add (KeyType &&InKey, const ValueType &InValue)
Set the value associated with a key.
void Add (KeyType &&InKey, ValueType &&InValue)
Set the value associated with a key.
void Compact ()
Compacts the pair set to remove holes.
bool Contains (KeyConstPointerType InKey) const
Check if map contains the specified key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
void Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
void Empty ()
Removes all elements from the map.
template<typename FunctionType>
bool FindAndApply (KeyConstPointerType InKey, FunctionType &&InFunction) const
Calls a function when the value is found while holding a lock on the map.
template<typename UpdateFunctionType>
bool FindAndApply (KeyConstPointerType InKey, UpdateFunctionType &&InUpdateFunction)
Calls a function to update a value if it has been found.
ValueType FindAndRemoveChecked (KeyConstPointerType InKey)
Find a pair with the specified key, removes it from the map, and returns the value part of the pair.
template<typename ProduceFunctionType>
ValueType FindOrProduce (const KeyType &InKey, ProduceFunctionType &&InProduceFunction)
Finds or produce a value associated with the key.
template<typename ProduceFunctionType, typename ApplyFunctionType>
void FindOrProduceAndApply (const KeyType &InKey, ProduceFunctionType &&InProduceFunction, ApplyFunctionType &&InApplyFunction)
Calls ProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value.
template<typename ProduceFunctionType, typename ApplyFunctionType>
void FindOrProduceAndApplyForWrite (const KeyType &InKey, ProduceFunctionType &&InProduceFunction, ApplyFunctionType &&InApplyFunction)
Calls ProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value.
template<typename TryProduceFunctionType, typename ApplyFunctionType>
bool FindOrTryProduceAndApply (const KeyType &InKey, TryProduceFunctionType &&InTryProduceFunction, ApplyFunctionType &&InApplyFunction)
Calls TryProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value if one exists.
template<typename TryProduceFunctionType, typename ApplyFunctionType>
bool FindOrTryProduceAndApplyForWrite (const KeyType &InKey, TryProduceFunctionType &&InTryProduceFunction, ApplyFunctionType &&InApplyFunction)
Calls TryProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value if one exists.
ValueType FindRef (KeyConstPointerType InKey) const
Gets you a copy of the value.
template<typename FunctionType>
void ForEach (FunctionType &&InFunction)
Calls a function on all elements of the map with exclusive access (elements can be modified).
template<typename FunctionType>
void ForEach (FunctionType &&InFunction) const
Calls a function on all elements of the map with shared access (elements can only be read).
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
int32 Num () const
int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
bool RemoveAndCopyValue (KeyConstPointerType InKey, ValueType &OutRemovedValue)
Remove the pair with the specified key and copies the value that was removed to the ref parameter.
int32 RemoveByHash (uint32 InKeyHash, KeyConstPointerType InKey)
See Remove() and class documentation section on ByHash() functions.
template<typename PredicateType>
int32 RemoveIf (KeyConstPointerType InKey, PredicateType &&InPredicate)
Removes only the element associated by the key if the predicate returns true.
template<typename PredicateType>
int32 RemoveIf (PredicateType &&InPredicate)
Removes all elements where the predicate returns true.
void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
void Shrink ()
Shrinks the pair set to avoid slack.
Protected Types
typedef LockingPolicy::ExclusiveLockType ExclusiveLockType
typedef LockingPolicy::MutexType MutexType
typedef LockingPolicy::SharedLockType SharedLockType
Protected Member Functions
template<typename LockType, typename FunctionType>
decltype(auto) Apply (KeyConstPointerType InKey, FunctionType &&InFunction)
template<typename LockType, typename FunctionType>
decltype(auto) Apply (KeyConstPointerType InKey, FunctionType &&InFunction) const
template<typename LockType, typename FunctionType>
decltype(auto) ApplyByHash (uint32 InHash, FunctionType &&InFunction)
template<typename LockType, typename FunctionType>
decltype(auto) ApplyByHash (uint32 InHash, FunctionType &&InFunction) const
template<typename FunctionType>
decltype(auto) ApplyUnlocked (KeyConstPointerType InKey, FunctionType &&InFunction)
template<typename FunctionType>
decltype(auto) ApplyUnlockedByHash (uint32 InHash, FunctionType &&InFunction)
template<typename FunctionType>
void ForEachMap (FunctionType &&InFunction)
template<typename FunctionType>
void ForEachMap (FunctionType &&InFunction) const
uint32 GetBucketIndex (uint32 Hash) const
template<typename FunctionType>
decltype(auto) Read (KeyConstPointerType InKey, FunctionType &&InFunction)
template<typename FunctionType>
decltype(auto) Read (KeyConstPointerType InKey, FunctionType &&InFunction) const
template<typename FunctionType>
decltype(auto) ReadByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType &&InFunction)
template<typename FunctionType>
decltype(auto) ReadByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType &&InFunction) const
template<typename FunctionType>
decltype(auto) Write (KeyConstPointerType InKey, FunctionType &&InFunction)
template<typename FunctionType>
decltype(auto) WriteByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType &&InFunction)
Protected Attributes
struct TStripedMapBase::FBucket Buckets [BucketCount]
Detailed Description
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy>
class TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >
The base class of striped maps which is a wrapper that adds thread-safety and contention reduction over regular maps.
The interface is slightly modified compared to regular maps to avoid some thread-safety issues that would arise if we returned pointers or reference to memory inside the map after the lock on a bucket had been released.
The ByHash() functions are somewhat dangerous but particularly useful in two scenarios: – Heterogeneous lookup to avoid creating expensive keys like FString when looking up by const TCHAR*. You must ensure the hash is calculated in the same way as ElementType is hashed. If possible put both ComparableKey and ElementType hash functions next to each other in the same header to avoid bugs when the ElementType hash function is changed. – Reducing contention around hash tables protected by a lock. This class manage this automatically so you don't have to work with ByHash function in this case.
Definition at line 54 of file StripedMap.h.
Member Typedef Documentation
ExclusiveLockType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef LockingPolicy::ExclusiveLockType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ExclusiveLockType protected
Definition at line 113 of file StripedMap.h.
KeyConstPointerType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef BaseMapType::KeyConstPointerType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::KeyConstPointerType
Definition at line 59 of file StripedMap.h.
KeyFuncsType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef KeyFuncs TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::KeyFuncsType
Definition at line 60 of file StripedMap.h.
MapType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef BaseMapType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::MapType
Definition at line 58 of file StripedMap.h.
MutexType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef LockingPolicy::MutexType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::MutexType protected
Definition at line 112 of file StripedMap.h.
SharedLockType
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> typedef LockingPolicy::SharedLockType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::SharedLockType protected
Definition at line 114 of file StripedMap.h.
Member Function Documentation
Add() [1/4]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add (const KeyType & InKey, const ValueType & InValue) inline
Set the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Definition at line 342 of file StripedMap.h.
Add() [2/4]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add (const KeyType & InKey, ValueType && InValue) inline
Set the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Definition at line 353 of file StripedMap.h.
Add() [3/4]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add (KeyType && InKey, const ValueType & InValue) inline
Set the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Definition at line 364 of file StripedMap.h.
Add() [4/4]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add (KeyType && InKey, ValueType && InValue) inline
Set the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Definition at line 375 of file StripedMap.h.
Apply() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename LockType, typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply (KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 173 of file StripedMap.h.
Apply() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename LockType, typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply (KeyConstPointerType InKey, FunctionType && InFunction) const inline protected
Definition at line 158 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Write().
ApplyByHash() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename LockType, typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyByHash (uint32 InHash, FunctionType && InFunction) inline protected
Definition at line 164 of file StripedMap.h.
ApplyByHash() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename LockType, typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyByHash (uint32 InHash, FunctionType && InFunction) const inline protected
Definition at line 149 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Apply(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::WriteByHash().
ApplyUnlocked()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyUnlocked (KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 143 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduce(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduceAndApply(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApply().
ApplyUnlockedByHash()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyUnlockedByHash (uint32 InHash, FunctionType && InFunction) inline protected
Definition at line 137 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyUnlocked().
Compact()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Compact () inline
Compacts the pair set to remove holes.
Definition at line 680 of file StripedMap.h.
Contains()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Contains (KeyConstPointerType InKey) const inline nodiscard
Check if map contains the specified key.
Parameters
InKey The key to check for.
Returns
true if the map contains the key.
Definition at line 315 of file StripedMap.h.
Emplace()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename InitKeyType = KeyType, typename InitValueType = ValueType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Emplace (InitKeyType && InKey, InitValueType && InValue) inline
Sets the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Definition at line 327 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Add().
Empty()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Empty () inline
Removes all elements from the map.
Definition at line 647 of file StripedMap.h.
FindAndApply() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindAndApply (KeyConstPointerType InKey, FunctionType && InFunction) const inline
Calls a function when the value is found while holding a lock on the map.
Best for more complex types that you don't want to wrap under TSharedPtr and where returning a copy would be wasteful.
Parameters
InKey The key to look for.
InFunction The function to call on the value (if found).
Returns
true if the map contains the key and a value was found.
Definition at line 269 of file StripedMap.h.
FindAndApply() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename UpdateFunctionType> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindAndApply (KeyConstPointerType InKey, UpdateFunctionType && InUpdateFunction) inline
Calls a function to update a value if it has been found.
Parameters
InKey The key to check for.
InUpdateFunction The function to call on the value (if found).
Returns
true if the map contains the key and a value was found.
Definition at line 293 of file StripedMap.h.
FindAndRemoveChecked()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> ValueType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindAndRemoveChecked (KeyConstPointerType InKey) inline
Find a pair with the specified key, removes it from the map, and returns the value part of the pair.
If no pair was found, an exception is thrown.
Parameters
InKey The key to search for
Returns
The value that was removed
Definition at line 637 of file StripedMap.h.
FindOrProduce()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename ProduceFunctionType> ValueType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduce (const KeyType & InKey, ProduceFunctionType && InProduceFunction) inline
Finds or produce a value associated with the key.
Parameters
InKey The key to look for.
InProduceFunction The function to call to produce a new value if the key is missing.
Returns
a copy the value associated with the key.
Definition at line 388 of file StripedMap.h.
FindOrProduceAndApply()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename ProduceFunctionType, typename ApplyFunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduceAndApply (const KeyType & InKey, ProduceFunctionType && InProduceFunction, ApplyFunctionType && InApplyFunction) inline
Calls ProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value.
Parameters
InKey The key to look for.
InProduceFunction The function to call to produce a new value associated with the key.
InApplyFunction The function to call with the const value reference when the key is found or has been produced.
Definition at line 421 of file StripedMap.h.
FindOrProduceAndApplyForWrite()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename ProduceFunctionType, typename ApplyFunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduceAndApplyForWrite (const KeyType & InKey, ProduceFunctionType && InProduceFunction, ApplyFunctionType && InApplyFunction) inline
Calls ProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value.
Parameters
InKey The key to look for.
InProduceFunction The function to call to produce a new value associated with the key.
InApplyFunction The function to call with the value reference when the key is found or has been produced.
Definition at line 499 of file StripedMap.h.
FindOrTryProduceAndApply()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename TryProduceFunctionType, typename ApplyFunctionType> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApply (const KeyType & InKey, TryProduceFunctionType && InTryProduceFunction, ApplyFunctionType && InApplyFunction) inline
Calls TryProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value if one exists.
Parameters
InKey The key to look for.
InTryProduceFunction The function to call to produce a new value associated with the key.
InApplyFunction The function to call with the const value reference when the key is found or has been produced.
Returns
true if a value was found or produced, false if TryProduceFunction failed.
Definition at line 457 of file StripedMap.h.
FindOrTryProduceAndApplyForWrite()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename TryProduceFunctionType, typename ApplyFunctionType> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApplyForWrite (const KeyType & InKey, TryProduceFunctionType && InTryProduceFunction, ApplyFunctionType && InApplyFunction) inline
Calls TryProduceFunction to produce a value if the key is missing, then calls ApplyFunction on the value if one exists.
Parameters
InKey The key to look for.
InTryProduceFunction The function to call to produce a new value associated with the key.
InApplyFunction The function to call with the value reference when the key is found or has been produced.
Returns
true if a value was found or produced, false if TryProduceFunction failed.
Definition at line 524 of file StripedMap.h.
FindRef()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> ValueType TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindRef (KeyConstPointerType InKey) const inline
Gets you a copy of the value.
Best for simple value types like PODs or TSharedPtr.
Parameters
InKey The key to look for.
Returns
a copy of the value for this key.
Definition at line 243 of file StripedMap.h.
ForEach() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEach (FunctionType && InFunction) inline
Calls a function on all elements of the map with exclusive access (elements can be modified).
Parameters
InFunction The callback to run on each Pair of the map.
Definition at line 710 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys().
ForEach() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEach (FunctionType && InFunction) const inline
Calls a function on all elements of the map with shared access (elements can only be read).
Parameters
InFunction The callback to run on each Pair of the map.
Definition at line 729 of file StripedMap.h.
ForEachMap() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEachMap (FunctionType && InFunction) inline protected
Definition at line 215 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Compact(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Empty(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEach(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEach(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Num(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveIf(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Reset(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Shrink().
ForEachMap() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ForEachMap (FunctionType && InFunction) const inline protected
Definition at line 225 of file StripedMap.h.
GetBucketIndex()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> uint32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetBucketIndex (uint32 Hash) const inline protected
Definition at line 124 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyByHash(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyByHash(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ApplyUnlockedByHash().
GetKeys()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename Allocator> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys (TArray< KeyType, Allocator > & OutKeys) const inline
Get the unique keys contained within this map.
Parameters
OutKeys Upon return, contains the set of unique keys in this map.
Returns
The number of unique keys in the map.
Definition at line 749 of file StripedMap.h.
Num()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Num () const inline nodiscard
Returns
The number of elements in the map.
Definition at line 691 of file StripedMap.h.
Read() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read (KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 191 of file StripedMap.h.
Read() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Read (KeyConstPointerType InKey, FunctionType && InFunction) const inline protected
Definition at line 203 of file StripedMap.h.
ReadByHash() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 197 of file StripedMap.h.
ReadByHash() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::ReadByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType && InFunction) const inline protected
Definition at line 209 of file StripedMap.h.
Remove()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Remove (KeyConstPointerType InKey) inline
Remove all value associations for a key.
Parameters
InKey The key to remove associated values for.
Returns
The number of values that were associated with the key.
Definition at line 552 of file StripedMap.h.
RemoveAndCopyValue()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> bool TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveAndCopyValue (KeyConstPointerType InKey, ValueType & OutRemovedValue) inline
Remove the pair with the specified key and copies the value that was removed to the ref parameter.
Parameters
InKey The key to search for
OutRemovedValue If found, the value that was removed (not modified if the key was not found)
Returns
whether or not the key was found
Definition at line 621 of file StripedMap.h.
RemoveByHash()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveByHash (uint32 InKeyHash, KeyConstPointerType InKey) inline
See Remove() and class documentation section on ByHash() functions.
Definition at line 558 of file StripedMap.h.
RemoveIf() [1/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename PredicateType> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveIf (KeyConstPointerType InKey, PredicateType && InPredicate) inline
Removes only the element associated by the key if the predicate returns true.
Parameters
InKey The key to remove associated values for.
InPredicate The predicate to call to determine if a value should be removed.
Returns
The number of values that were removed.
Definition at line 571 of file StripedMap.h.
RemoveIf() [2/2]
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename PredicateType> int32 TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveIf (PredicateType && InPredicate) inline
Removes all elements where the predicate returns true.
Parameters
InPredicate The predicate to call to determine if a pair should be removed.
Returns
The number of pairs that were removed.
Definition at line 594 of file StripedMap.h.
Reset()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Reset () inline
Efficiently empties out the map but preserves all allocations and capacities.
Definition at line 658 of file StripedMap.h.
Shrink()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> void TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Shrink () inline
Shrinks the pair set to avoid slack.
Definition at line 669 of file StripedMap.h.
Write()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Write (KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 179 of file StripedMap.h.
WriteByHash()
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> template<typename FunctionType> decltype(auto) TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::WriteByHash (uint32 InHash, KeyConstPointerType InKey, FunctionType && InFunction) inline protected
Definition at line 185 of file StripedMap.h.
Referenced by TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveByHash().
Field Documentation
Buckets
template<int32 BucketCount, typename BaseMapType, typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs, typename LockingPolicy> struct TStripedMapBase::FBucket TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::Buckets[BucketCount] protected
The documentation for this class was generated from the following file:
StripedMap.h