Unreal Engine 5.6 C++ API: FAssetPackageData Class Reference
FAssetPackageData Class Reference
A class to hold data about a package on disk, this data is updated on save/load and is not updated when an asset changes in memory.
#include "AssetData.h"
Public Member Functions
FAssetPackageData ()
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
TConstArrayView< UE::AssetRegistry::FPackageCustomVersion > GetCustomVersions () const
Custom versions used by the package, used to check whether we need to update the package for the current binary.
FPackageName::EPackageLocationFilter GetPackageLocation () const
bool HasVirtualizedPayloads () const
Whether the package contains virtualized payloads or not.
bool IsLicenseeVersion () const
Whether the package was saved from a licensee executable, used to tell whether non-matching FileVersionLicenseeUE requires a resave.
void NetworkWrite (FCbWriter &Writer) const
void SerializeForCache (FArchive &Ar)
Serialize as part of the registry cache.
void SerializeForCacheOldVersion (FArchive &Ar, FAssetRegistryVersion::Type Version)
void SetCustomVersions (TArray< UE::AssetRegistry::FPackageCustomVersion > &&InCustomVersions)
void SetCustomVersions (TConstArrayView< FCustomVersion > InCustomVersions)
void SetCustomVersions (TConstArrayView< UE::AssetRegistry::FPackageCustomVersion > InCustomVersions)
void SetHasVirtualizedPayloads (bool bValue)
void SetIsLicenseeVersion (bool bValue)
void SetPackageLocation (FPackageName::EPackageLocationFilter PackageLocation)
bool TryNetworkRead (FCbFieldView Field)
UE_DEPRECATED (5.6, "No longer supported in non-editor configurations, to save memory.") 1 FIoHash GetPackageSavedHash() const
Hash of the package's .uasset/.umap file when it was last saved by the editor.
UE_DEPRECATED (5.6, "No longer supported in non-editor configurations, to save memory.") 1 void SetPackageSavedHash(const FIoHash &InHash)
Data Fields
TMap< FIoChunkId, FIoHash > ChunkHashes
The hash of all the chunks written by the package writer for this package.
FMD5Hash CookedHash
MD5 of the cooked package on disk, for tracking nondeterministic changes.
int64 DiskSize
Total size of this asset on disk.
EPackageExtension Extension
int32 FileVersionLicenseeUE
Licensee file version that the package was saved with.
FPackageFileVersion FileVersionUE
UE file version that the package was saved with.
TArray< FName > ImportedClasses
List of classes used by exports in the package.
Private Types
enum : uint32 {
FLAG_LICENSEE_VERSION = 1u << 0 , FLAG_HAS_VIRTUALIZED_PAYLOADS = 1u << 1 , FLAG_PACKAGE_LOCATION_IODISPATCHER = 1u << 30 , FLAG_PACKAGE_LOCATION_FILESYSTEM = 1u << 31 ,
FLAG_PACKAGE_LOCATION_TO_ENUM_SHIFT_SIZE = 30u , FLAG_PACKAGE_LOCATION_MASK = uint32(FPackageName::EPackageLocationFilter::ValidMask) << FLAG_PACKAGE_LOCATION_TO_ENUM_SHIFT_SIZE
}
Private Member Functions
FORCEINLINE void SerializeForCacheInternal (FArchive &Ar, FAssetPackageData &PackageData, FAssetRegistryVersion::Type Version)
Private Attributes
UE::AssetRegistry::FPackageCustomVersionsHandle CustomVersions
uint32 Flags
Bit storage for flags.
Detailed Description
A class to hold data about a package on disk, this data is updated on save/load and is not updated when an asset changes in memory.
Definition at line 934 of file AssetData.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32 private
Enumerator
FLAG_LICENSEE_VERSION
FLAG_HAS_VIRTUALIZED_PAYLOADS
FLAG_PACKAGE_LOCATION_IODISPATCHER
FLAG_PACKAGE_LOCATION_FILESYSTEM
FLAG_PACKAGE_LOCATION_TO_ENUM_SHIFT_SIZE
FLAG_PACKAGE_LOCATION_MASK
Definition at line 1056 of file AssetData.h.
Constructor & Destructor Documentation
FAssetPackageData()
FAssetPackageData::FAssetPackageData () inline
Definition at line 972 of file AssetData.h.
References DiskSize, Extension, FileVersionLicenseeUE, Flags, and Unspecified.
Referenced by SerializeForCacheInternal().
Member Function Documentation
GetAllocatedSize()
SIZE_T FAssetPackageData::GetAllocatedSize () const inline
Returns the amount of memory allocated by this container, not including sizeof(*this).
Definition at line 1017 of file AssetData.h.
References ImportedClasses.
GetCustomVersions()
TConstArrayView< UE::AssetRegistry::FPackageCustomVersion > FAssetPackageData::GetCustomVersions () const inline
Custom versions used by the package, used to check whether we need to update the package for the current binary.
The array is sorted by FPackageCustomVersion::operator<.
Definition at line 984 of file AssetData.h.
References CustomVersions.
GetPackageLocation()
FPackageName::EPackageLocationFilter FAssetPackageData::GetPackageLocation () const inline
Definition at line 1048 of file AssetData.h.
References FLAG_PACKAGE_LOCATION_MASK, FLAG_PACKAGE_LOCATION_TO_ENUM_SHIFT_SIZE, and Flags.
HasVirtualizedPayloads()
bool FAssetPackageData::HasVirtualizedPayloads () const inline
Whether the package contains virtualized payloads or not.
Definition at line 1006 of file AssetData.h.
References FLAG_HAS_VIRTUALIZED_PAYLOADS, and Flags.
IsLicenseeVersion()
bool FAssetPackageData::IsLicenseeVersion () const inline
Whether the package was saved from a licensee executable, used to tell whether non-matching FileVersionLicenseeUE requires a resave.
Definition at line 1002 of file AssetData.h.
References FLAG_LICENSEE_VERSION, and Flags.
NetworkWrite()
void FAssetPackageData::NetworkWrite (FCbWriter & Writer) const
SerializeForCache()
void FAssetPackageData::SerializeForCache (FArchive & Ar)
Serialize as part of the registry cache.
This is not meant to be serialized as part of a package so it does not handle versions normally To version this data change FAssetRegistryVersion
References Ar.
SerializeForCacheInternal()
FORCEINLINE void FAssetPackageData::SerializeForCacheInternal (FArchive & Ar, FAssetPackageData & PackageData, FAssetRegistryVersion::Type Version) private
References FAssetPackageData(), Ar, and FORCEINLINE.
SerializeForCacheOldVersion()
void FAssetPackageData::SerializeForCacheOldVersion (FArchive & Ar, FAssetRegistryVersion::Type Version)
References Ar.
SetCustomVersions() [1/3]
void FAssetPackageData::SetCustomVersions (TArray< UE::AssetRegistry::FPackageCustomVersion > && InCustomVersions) inline
Definition at line 996 of file AssetData.h.
References CustomVersions, UE::AssetRegistry::FPackageCustomVersionsHandle::FindOrAdd(), and MoveTemp().
SetCustomVersions() [2/3]
void FAssetPackageData::SetCustomVersions (TConstArrayView< FCustomVersion > InCustomVersions) inline
Definition at line 988 of file AssetData.h.
References CustomVersions, and UE::AssetRegistry::FPackageCustomVersionsHandle::FindOrAdd().
SetCustomVersions() [3/3]
void FAssetPackageData::SetCustomVersions (TConstArrayView< UE::AssetRegistry::FPackageCustomVersion > InCustomVersions) inline
Definition at line 992 of file AssetData.h.
References CustomVersions, and UE::AssetRegistry::FPackageCustomVersionsHandle::FindOrAdd().
SetHasVirtualizedPayloads()
void FAssetPackageData::SetHasVirtualizedPayloads (bool bValue) inline
Definition at line 1007 of file AssetData.h.
References FLAG_HAS_VIRTUALIZED_PAYLOADS, and Flags.
SetIsLicenseeVersion()
void FAssetPackageData::SetIsLicenseeVersion (bool bValue) inline
Definition at line 1003 of file AssetData.h.
References FLAG_LICENSEE_VERSION, and Flags.
SetPackageLocation()
void FAssetPackageData::SetPackageLocation (FPackageName::EPackageLocationFilter PackageLocation) inline
Definition at line 1038 of file AssetData.h.
References check, FLAG_PACKAGE_LOCATION_MASK, FLAG_PACKAGE_LOCATION_TO_ENUM_SHIFT_SIZE, Flags, FPackageName::MaxBit, and FPackageName::ValidMask.
TryNetworkRead()
bool FAssetPackageData::TryNetworkRead (FCbFieldView Field)
UE_DEPRECATED() [1/2]
FAssetPackageData::UE_DEPRECATED (5. 6, "No longer supported in non-editor configurations, to save memory.") const
Hash of the package's .uasset/.umap file when it was last saved by the editor.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FAssetPackageData::UE_DEPRECATED (5. 6, "No longer supported in non-editor configurations, to save memory.") const &
References UE_DEPRECATED().
Field Documentation
ChunkHashes
TMap<FIoChunkId, FIoHash> FAssetPackageData::ChunkHashes
The hash of all the chunks written by the package writer for this package.
This is only available after cooking. (Note, this only includes the ExportBundleData chunk if using ZenStoreWriter, as that chunk contains both the uasset and uexp data, which is managed separately in LooseCookedPackageWriter.)
Definition at line 945 of file AssetData.h.
CookedHash
FMD5Hash FAssetPackageData::CookedHash
MD5 of the cooked package on disk, for tracking nondeterministic changes.
Definition at line 938 of file AssetData.h.
CustomVersions
UE::AssetRegistry::FPackageCustomVersionsHandle FAssetPackageData::CustomVersions private
Definition at line 963 of file AssetData.h.
Referenced by GetCustomVersions(), SetCustomVersions(), SetCustomVersions(), and SetCustomVersions().
DiskSize
int64 FAssetPackageData::DiskSize
Total size of this asset on disk.
Definition at line 951 of file AssetData.h.
Referenced by FAssetPackageData().
Extension
EPackageExtension FAssetPackageData::Extension
Definition at line 968 of file AssetData.h.
Referenced by FAssetPackageData().
FileVersionLicenseeUE
int32 FAssetPackageData::FileVersionLicenseeUE
Licensee file version that the package was saved with.
Definition at line 957 of file AssetData.h.
Referenced by FAssetPackageData().
FileVersionUE
FPackageFileVersion FAssetPackageData::FileVersionUE
UE file version that the package was saved with.
Definition at line 954 of file AssetData.h.
Flags
uint32 FAssetPackageData::Flags private
Bit storage for flags.
Definition at line 965 of file AssetData.h.
Referenced by FAssetPackageData(), GetPackageLocation(), HasVirtualizedPayloads(), IsLicenseeVersion(), SetHasVirtualizedPayloads(), SetIsLicenseeVersion(), and SetPackageLocation().
ImportedClasses
TArray<FName> FAssetPackageData::ImportedClasses
List of classes used by exports in the package.
Does not include classes in the same package.
Definition at line 948 of file AssetData.h.
Referenced by GetAllocatedSize().
The documentation for this class was generated from the following file:
AssetData.h