Unreal Engine 5.6 C++ API: TRDGParameterStruct< ParameterStructType > Class Template Reference
TRDGParameterStruct< ParameterStructType > Class Template Reference
#include "RenderGraphParameter.h"
Public Member Functions
TRDGParameterStruct (ParameterStructType *Parameters)
const ParameterStructType * GetContents () const
Returns the contents of the struct.
const ParameterStructType * operator-> () const
Public Member Functions inherited from FRDGParameterStruct
template<typename ParameterStructType>
FRDGParameterStruct (const ParameterStructType *Parameters, const FShaderParametersMetadata *InParameterMetadata)
FRDGParameterStruct (const void *InContents, const FRHIUniformBufferLayout *InLayout)
template<typename FunctionType>
void Enumerate (FunctionType Function) const
Enumerates all graph parameters on the layout.
template<typename FunctionType>
void EnumerateBuffers (FunctionType Function) const
Same as Enumerate, but only buffer parameters are included.
template<typename FunctionType>
void EnumerateTextures (FunctionType Function) const
Same as Enumerate, but only texture parameters are included.
template<typename FunctionType>
void EnumerateUniformBuffers (FunctionType Function) const
Enumerates all non-null uniform buffers.
uint32 GetBufferParameterCount () const
Returns the number of buffer parameters present on the layout.
const uint8 * GetContents () const
Returns the contents of the struct.
const FRHIUniformBufferLayout & GetLayout () const
Returns the layout associated with this struct.
const FRHIUniformBufferLayout * GetLayoutPtr () const
const FShaderParametersMetadata * GetMetadata () const
RENDERCORE_API FRHIRenderPassInfo GetRenderPassInfo () const
Returns the render pass info generated from the render target binding slots.
const FRenderTargetBindingSlots & GetRenderTargets () const
Returns the render target binding slots.
RENDERCORE_API FUniformBufferStaticBindings GetStaticUniformBuffers () const
Returns a set of static uniform buffer bindings for the parameter struct.
uint32 GetTextureParameterCount () const
Returns the number of texture parameters present on the layout.
uint32 GetUniformBufferParameterCount () const
Returns the number of RDG uniform buffers present in the layout.
FORCEINLINE bool HasExternalOutputs () const
FORCEINLINE bool HasRenderTargets () const
Helpful forwards from the layout.
FORCEINLINE bool HasStaticSlot () const
Additional Inherited Members
Static Public Member Functions inherited from FRDGParameterStruct
static void ClearUniformBuffers (void *Contents, const FRHIUniformBufferLayout *Layout)
Clears out all uniform buffer references in the parameter struct.
Detailed Description
template<typename ParameterStructType>
class TRDGParameterStruct< ParameterStructType >
Definition at line 304 of file RenderGraphParameter.h.
Constructor & Destructor Documentation
TRDGParameterStruct()
template<typename ParameterStructType> TRDGParameterStruct< ParameterStructType >::TRDGParameterStruct (ParameterStructType * Parameters) inline explicit
Definition at line 308 of file RenderGraphParameter.h.
References FRDGParameterStruct::FRDGParameterStruct(), and FRDGParameterStruct::GetLayout().
Member Function Documentation
GetContents()
template<typename ParameterStructType> const ParameterStructType * TRDGParameterStruct< ParameterStructType >::GetContents () const inline
Returns the contents of the struct.
Definition at line 313 of file RenderGraphParameter.h.
References FRDGParameterStruct::GetContents().
Referenced by operator->().
operator->()
template<typename ParameterStructType> const ParameterStructType * TRDGParameterStruct< ParameterStructType >::operator-> () const inline
Definition at line 318 of file RenderGraphParameter.h.
References GetContents().
The documentation for this class was generated from the following file:
RenderGraphParameter.h