Unreal Engine 5.6 C++ API: TGuardedInt< IntType > Class Template Reference
TGuardedInt< IntType > Class Template Reference
Overflow- and error-checked integer.
#include "GuardedInt.h"
Public Member Functions
TGuardedInt ()=default
Construct a TGuardedInt with an invalid value.
TGuardedInt (const TGuardedInt &Other)=default
Copy-construct a TGuardedInt from another of matching type.
template<typename ValueType UE_REQUIRES>
TGuardedInt (ValueType InValue)
Construct a TGuardedInt from a regular signed integer value.
TGuardedInt Abs () const
bool ComparisonValid (const TGuardedInt Other) const
IntType Get (const IntType DefaultValue) const
IntType GetChecked (const IntType DefaultValue=0) const
template<typename ValueType>
bool InvalidOrGreaterOrEqual (const ValueType Other) const
template<typename ValueType>
bool InvalidOrGreaterThan (const ValueType Other) const
template<typename ValueType>
bool InvalidOrLessOrEqual (const ValueType Other) const
template<typename ValueType>
bool InvalidOrLessThan (const ValueType Other) const
bool IsValid () const
bool operator!= (const TGuardedInt Other) const
TGuardedInt operator% (const TGuardedInt Other) const
TGuardedInt operator% (IntType InB) const
TGuardedInt & operator%= (IntType InB)
TGuardedInt & operator%= (TGuardedInt InB)
TGuardedInt operator* (const TGuardedInt Other) const
TGuardedInt operator* (IntType InB) const
TGuardedInt & operator*= (IntType InB)
TGuardedInt & operator*= (TGuardedInt InB)
TGuardedInt operator+ (const TGuardedInt Other) const
TGuardedInt operator+ (IntType InB) const
TGuardedInt & operator+= (IntType InB)
TGuardedInt & operator+= (TGuardedInt InB)
TGuardedInt operator- () const
TGuardedInt operator- (const TGuardedInt Other) const
TGuardedInt operator- (IntType InB) const
TGuardedInt & operator-= (IntType InB)
TGuardedInt & operator-= (TGuardedInt InB)
TGuardedInt operator/ (const TGuardedInt Other) const
TGuardedInt operator/ (IntType InB) const
TGuardedInt & operator/= (IntType InB)
TGuardedInt & operator/= (TGuardedInt InB)
TGuardedInt operator<< (const TGuardedInt Other) const
TGuardedInt operator<< (IntType InB) const
TGuardedInt & operator<<= (IntType InB)
TGuardedInt & operator<<= (TGuardedInt InB)
TGuardedInt & operator= (const TGuardedInt &Other)=default
Assign a TGuardedInt to another.
bool operator== (const TGuardedInt Other) const
TGuardedInt operator>> (const TGuardedInt Other) const
TGuardedInt operator>> (IntType InB) const
TGuardedInt & operator>>= (IntType InB)
TGuardedInt & operator>>= (TGuardedInt InB)
template<typename ValueType>
bool ValidAndGreaterOrEqual (const ValueType Other) const
template<typename ValueType>
bool ValidAndGreaterThan (const ValueType Other) const
template<typename ValueType>
bool ValidAndLessOrEqual (const ValueType Other) const
template<typename ValueType>
bool ValidAndLessThan (const ValueType Other) const
Private Types
typedef std::make_unsigned_t< IntType > UnsignedType
Private Attributes
bool bIsValid = false
IntType Value = 0
Static Private Attributes
static constexpr IntType MaxValue = std::numeric_limits<IntType>::max()
static constexpr IntType MinValue = std::numeric_limits<IntType>::min()
static constexpr IntType NumBits = IntType((sizeof(IntType) / sizeof(char)) * 8)
Friends
TGuardedInt operator% (IntType InA, TGuardedInt InB)
TGuardedInt operator* (IntType InA, TGuardedInt InB)
TGuardedInt operator+ (IntType InA, TGuardedInt InB)
TGuardedInt operator- (IntType InA, TGuardedInt InB)
TGuardedInt operator/ (IntType InA, TGuardedInt InB)
TGuardedInt operator<< (IntType InA, TGuardedInt InB)
TGuardedInt operator>> (IntType InA, TGuardedInt InB)
Detailed Description
template<typename IntType>
class TGuardedInt< IntType >
Overflow- and error-checked integer.
For integer arithmetic on data from untrusted sources (like imported files), especially when doing size computations. Also checks for division by zero and invalid shift amounts.
You're not meant to use this directly. Use FGuardedInt32 or FGuardedInt64 (defined below). A typical use case would be:
FGuardedInt64 NumBytes = FGuardedInt32(Width) * Height * BytesPerPixel; if (NumBytes.InvalidOrGreaterThan(SizeLimit)) { // Report error. } int64 NumBytesValidated = NumBytes.GetValue();
This is a template meant to be instantiated on top of regular basic integer types. The code is written so the logic is integer-size agnostic and uses just regular C++ arithmetic operations. It is assumed to run on a two's complement integer platform (which is all we support, and as of C++20 is contractual). You should generally use the specializations FGuardedInt32 and FGuardedInt64 below.
Checked integers keep both the integer value and a "valid" flag. Default-constructed guarded ints are invalid, and guarded integers constructed from an integer value are valid and hold that value. Guarded integers are somewhat analogous to a TOptional<IntType> in semantics, and borrow some of the function names.
The main feature of guarded integers is that all arithmetic on them is overflow-checked. Any arithmetic involving guarded integers results in a guarded integer, and any arithmetic involving invalid values, or arithmetic resulting in overflows or other errors (such as division by zero) likewise results in an invalid value. The idea is that integer arithmetic using guarded integers should be possible to write very straightforwardly and without having to consider any of these special cases; if any error occurred along the way, the result will be invalid. These invalid values can then be checked for and handled right when the result is converted back to a regular integer.
Some compilers provide built-ins for overflow-checked integer arithmetic for some types. We could eventually use this (it's especially interesting for multiplications, since our current overflow-checking algorithm is fairly expensive), but a big benefit of the current approach is that it uses nothing but regular arithmetic and is type-agnostic. In particular, this makes it possible to check this implementation exhaustively against a known-good reference for small integer types such as int8. It is much trickier and more subtle to do good testing for larger integer types where that brute-force approach is not practical. As-is, the current approach is not the fastest, but it's not presently intended to be used in contexts where speed of arithmetic operations is a major concern.
Definition at line 54 of file GuardedInt.h.
Member Typedef Documentation
UnsignedType
template<typename IntType> typedef std::make_unsigned_t<IntType> TGuardedInt< IntType >::UnsignedType private
Definition at line 58 of file GuardedInt.h.
Constructor & Destructor Documentation
TGuardedInt() [1/3]
template<typename IntType> TGuardedInt< IntType >::TGuardedInt () nodiscard default
Construct a TGuardedInt with an invalid value.
Referenced by TGuardedInt< SignedType >::Abs(), TGuardedInt< SignedType >::operator%(), TGuardedInt< SignedType >::operator*(), TGuardedInt< SignedType >::operator+(), TGuardedInt< SignedType >::operator-(), TGuardedInt< SignedType >::operator-(), TGuardedInt< SignedType >::operator/(), TGuardedInt< SignedType >::operator<<(), and TGuardedInt< SignedType >::operator>>().
TGuardedInt() [2/3]
template<typename IntType> template<typename ValueType UE_REQUIRES> TGuardedInt< IntType >::TGuardedInt (ValueType InValue) inline explicit nodiscard
Construct a TGuardedInt from a regular signed integer value.
If it's out of range, it results in an invalid value.
Definition at line 76 of file GuardedInt.h.
TGuardedInt() [3/3]
template<typename IntType> TGuardedInt< IntType >::TGuardedInt (const TGuardedInt< IntType > & Other) nodiscard default
Copy-construct a TGuardedInt from another of matching type.
Member Function Documentation
Abs()
template<typename IntType> TGuardedInt TGuardedInt< IntType >::Abs () const inline nodiscard
Returns
The absolute value of *this.
Definition at line 373 of file GuardedInt.h.
ComparisonValid()
template<typename IntType> bool TGuardedInt< IntType >::ComparisonValid (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
true if *this and Other are both valid so they can be compared.
Definition at line 142 of file GuardedInt.h.
Referenced by TGuardedInt< SignedType >::InvalidOrGreaterOrEqual(), TGuardedInt< SignedType >::InvalidOrGreaterThan(), TGuardedInt< SignedType >::InvalidOrLessOrEqual(), TGuardedInt< SignedType >::InvalidOrLessThan(), TGuardedInt< SignedType >::ValidAndGreaterOrEqual(), TGuardedInt< SignedType >::ValidAndGreaterThan(), TGuardedInt< SignedType >::ValidAndLessOrEqual(), and TGuardedInt< SignedType >::ValidAndLessThan().
Get()
template<typename IntType> IntType TGuardedInt< IntType >::Get (const IntType DefaultValue) const inline nodiscard
Returns
The value if valid, DefaultValue otherwise.
Definition at line 102 of file GuardedInt.h.
Referenced by TGuardedInt< SignedType >::GetChecked().
GetChecked()
template<typename IntType> IntType TGuardedInt< IntType >::GetChecked (const IntType DefaultValue = 0) const inline nodiscard
Returns
Returns the value if valid, DefaultValue otherwise, but also check()s that the value is valid. Intended for cases where the value is not expected to be invalid.
Definition at line 110 of file GuardedInt.h.
InvalidOrGreaterOrEqual()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::InvalidOrGreaterOrEqual (const ValueType Other) const inline nodiscard
Returns
true if either of *this or Other are invalid or *this is greater than or equal to Other.
Definition at line 205 of file GuardedInt.h.
InvalidOrGreaterThan()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::InvalidOrGreaterThan (const ValueType Other) const inline nodiscard
Returns
true if either of *this or Other are invalid or *this is greater than Other.
Definition at line 197 of file GuardedInt.h.
InvalidOrLessOrEqual()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::InvalidOrLessOrEqual (const ValueType Other) const inline nodiscard
Returns
true if either of *this or Other are invalid or *this is less than or equal to Other.
Definition at line 189 of file GuardedInt.h.
InvalidOrLessThan()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::InvalidOrLessThan (const ValueType Other) const inline nodiscard
Returns
true if either of *this or Other are invalid or *this is less than Other.
Definition at line 181 of file GuardedInt.h.
IsValid()
template<typename IntType> bool TGuardedInt< IntType >::IsValid () const inline nodiscard
Returns
true if current value is valid (assigned and no overflows or other errors occurred), false otherwise.
Definition at line 96 of file GuardedInt.h.
Referenced by TGuardedInt< SignedType >::Get(), and TGuardedInt< SignedType >::GetChecked().
operator!=()
template<typename IntType> bool TGuardedInt< IntType >::operator!= (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
true if *this and Other either have different "valid" states or are both valid and have different values, false otherwise (logical negation of ==).
Definition at line 128 of file GuardedInt.h.
operator%() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator% (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
The remainder when dividing *this by Other.
Definition at line 294 of file GuardedInt.h.
operator%() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator% (IntType InB) const inline
Definition at line 407 of file GuardedInt.h.
operator%=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator%= (IntType InB) inline
Definition at line 407 of file GuardedInt.h.
operator%=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator%= (TGuardedInt< IntType > InB) inline
Definition at line 407 of file GuardedInt.h.
operator*() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator* (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
The product of the two operands.
Definition at line 259 of file GuardedInt.h.
operator*() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator* (IntType InB) const inline
Definition at line 405 of file GuardedInt.h.
operator*=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator*= (IntType InB) inline
Definition at line 405 of file GuardedInt.h.
operator*=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator*= (TGuardedInt< IntType > InB) inline
Definition at line 405 of file GuardedInt.h.
operator+() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator+ (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
The sum of the two operands.
Definition at line 229 of file GuardedInt.h.
operator+() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator+ (IntType InB) const inline
Definition at line 403 of file GuardedInt.h.
operator+=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator+= (IntType InB) inline
Definition at line 403 of file GuardedInt.h.
operator+=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator+= (TGuardedInt< IntType > InB) inline
Definition at line 403 of file GuardedInt.h.
operator-() [1/3]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator- () const inline nodiscard
Returns
The negated value.
Definition at line 214 of file GuardedInt.h.
operator-() [2/3]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator- (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
The difference between the two operands.
Definition at line 244 of file GuardedInt.h.
operator-() [3/3]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator- (IntType InB) const inline
Definition at line 404 of file GuardedInt.h.
operator-=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator-= (IntType InB) inline
Definition at line 404 of file GuardedInt.h.
operator-=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator-= (TGuardedInt< IntType > InB) inline
Definition at line 404 of file GuardedInt.h.
operator/() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator/ (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
The quotient when dividing *this by Other.
Definition at line 274 of file GuardedInt.h.
operator/() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator/ (IntType InB) const inline
Definition at line 406 of file GuardedInt.h.
operator/=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator/= (IntType InB) inline
Definition at line 406 of file GuardedInt.h.
operator/=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator/= (TGuardedInt< IntType > InB) inline
Definition at line 406 of file GuardedInt.h.
operator<<() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator<< (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
This value bitwise left-shifted by the operand.
Definition at line 312 of file GuardedInt.h.
operator<<() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator<< (IntType InB) const inline
Definition at line 408 of file GuardedInt.h.
operator<<=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator<<= (IntType InB) inline
Definition at line 408 of file GuardedInt.h.
operator<<=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator<<= (TGuardedInt< IntType > InB) inline
Definition at line 408 of file GuardedInt.h.
operator=()
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator= (const TGuardedInt< IntType > & Other) default
Assign a TGuardedInt to another.
operator==()
template<typename IntType> bool TGuardedInt< IntType >::operator== (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
true if *this and Other are either both invalid or both valid and have the same value, false otherwise.
Definition at line 117 of file GuardedInt.h.
operator>>() [1/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator>> (const TGuardedInt< IntType > Other) const inline nodiscard
Returns
This value bitwise right-shifted by the operand.
Definition at line 354 of file GuardedInt.h.
operator>>() [2/2]
template<typename IntType> TGuardedInt TGuardedInt< IntType >::operator>> (IntType InB) const inline
Definition at line 409 of file GuardedInt.h.
operator>>=() [1/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator>>= (IntType InB) inline
Definition at line 409 of file GuardedInt.h.
operator>>=() [2/2]
template<typename IntType> TGuardedInt & TGuardedInt< IntType >::operator>>= (TGuardedInt< IntType > InB) inline
Definition at line 409 of file GuardedInt.h.
ValidAndGreaterOrEqual()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::ValidAndGreaterOrEqual (const ValueType Other) const inline nodiscard
Returns
true if *this and Other are both valid and *this is greater than or equal to Other.
Definition at line 173 of file GuardedInt.h.
ValidAndGreaterThan()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::ValidAndGreaterThan (const ValueType Other) const inline nodiscard
Returns
true if *this and Other are both valid and *this is greater than Other.
Definition at line 165 of file GuardedInt.h.
ValidAndLessOrEqual()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::ValidAndLessOrEqual (const ValueType Other) const inline nodiscard
Returns
true if *this and Other are both valid and *this is less than or equal to Other.
Definition at line 157 of file GuardedInt.h.
ValidAndLessThan()
template<typename IntType> template<typename ValueType> bool TGuardedInt< IntType >::ValidAndLessThan (const ValueType Other) const inline nodiscard
Returns
true if *this and Other are both valid and *this is less than Other.
Definition at line 149 of file GuardedInt.h.
Friends And Related Symbol Documentation
operator%
template<typename IntType> TGuardedInt operator% (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 407 of file GuardedInt.h.
operator*
template<typename IntType> TGuardedInt operator* (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 405 of file GuardedInt.h.
operator+
template<typename IntType> TGuardedInt operator+ (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 403 of file GuardedInt.h.
operator-
template<typename IntType> TGuardedInt operator- (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 404 of file GuardedInt.h.
operator/
template<typename IntType> TGuardedInt operator/ (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 406 of file GuardedInt.h.
operator<<
template<typename IntType> TGuardedInt operator<< (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 408 of file GuardedInt.h.
operator>>
template<typename IntType> TGuardedInt operator>> (IntType InA, TGuardedInt< IntType > InB) friend
Definition at line 409 of file GuardedInt.h.
Field Documentation
bIsValid
template<typename IntType> bool TGuardedInt< IntType >::bIsValid = false private
Definition at line 65 of file GuardedInt.h.
MaxValue
template<typename IntType> IntType TGuardedInt< IntType >::MaxValue = std::numeric_limits<IntType>::max() static constexpr private
Definition at line 61 of file GuardedInt.h.
MinValue
template<typename IntType> IntType TGuardedInt< IntType >::MinValue = std::numeric_limits<IntType>::min() static constexpr private
Definition at line 60 of file GuardedInt.h.
NumBits
template<typename IntType> IntType TGuardedInt< IntType >::NumBits = IntType((sizeof(IntType) / sizeof(char)) * 8) static constexpr private
Definition at line 62 of file GuardedInt.h.
Value
template<typename IntType> IntType TGuardedInt< IntType >::Value = 0 private
Definition at line 64 of file GuardedInt.h.
Referenced by TGuardedInt< SignedType >::InvalidOrGreaterOrEqual(), TGuardedInt< SignedType >::InvalidOrGreaterThan(), TGuardedInt< SignedType >::InvalidOrLessOrEqual(), TGuardedInt< SignedType >::InvalidOrLessThan(), TGuardedInt< SignedType >::ValidAndGreaterOrEqual(), TGuardedInt< SignedType >::ValidAndGreaterThan(), TGuardedInt< SignedType >::ValidAndLessOrEqual(), and TGuardedInt< SignedType >::ValidAndLessThan().
The documentation for this class was generated from the following file:
GuardedInt.h