Unreal Engine 5.6 C++ API: UE::Geometry::FMeshRegionOperator Class Reference
UE::Geometry::FMeshRegionOperator Class Reference
This class automatically extracts a submesh from a mesh, and can re-insert it after you have edited it, as long as you have not messed up the boundary.
#include "MeshRegionOperator.h"
Public Member Functions
FMeshRegionOperator (FDynamicMesh3 *Base, const TArrayView< const int > &RegionTris)
FMeshRegionOperator (FDynamicMesh3 *Base, const TArrayView< const int > &RegionTris, TFunctionRef< void(FDynamicSubmesh3 &)> ConfigSubmeshFunc)
bool BackPropropagate (bool bAllowSubmeshRepairs=true)
Remove the original submesh region and merge in the remeshed version.
bool BackPropropagateVertices (bool bRecomputeBoundaryNormals=false)
Transfer vertex positions in submesh back to base mesh; for use when the vertices in submesh still directly correspond back.
TSet< int > CurrentBaseInteriorVertices () const
const TArray< int > & CurrentBaseTriangles () const
void RepairPossibleNonManifoldEdges ()
After remeshing we may create an internal edge between two boundary vertices [a,b].
void SetSubmeshGroupID (int GID)
Data Fields
FDynamicMesh3 * BaseMesh
TArray< int > CurrentBaseTris
FDynamicSubmesh3 Region
FDynamicMeshEditor::EDuplicateTriBehavior ReinsertDuplicateTriBehavior = FDynamicMeshEditor::EDuplicateTriBehavior::EnsureContinue
FOptionallySparseIndexMap ReinsertSubToBaseMapT
FOptionallySparseIndexMap ReinsertSubToBaseMapV
Detailed Description
This class automatically extracts a submesh from a mesh, and can re-insert it after you have edited it, as long as you have not messed up the boundary.
[TODO] Should this share any code w/ RegionRemesher? [TODO] ReinsertSubToBaseMapT is not returned by the FDynamicMeshEditor.ReinsertSubmesh, instead we are trying to guess it here, by making some assumptions about what happens. It works for now, but it would better if FDynamicMeshEditor returned this information.
Definition at line 31 of file MeshRegionOperator.h.
Constructor & Destructor Documentation
FMeshRegionOperator() [1/2]
UE::Geometry::FMeshRegionOperator::FMeshRegionOperator (FDynamicMesh3 * Base, const TArrayView< const int > & RegionTris, TFunctionRef< void(FDynamicSubmesh3 &)> ConfigSubmeshFunc) inline
Definition at line 49 of file MeshRegionOperator.h.
References BaseMesh, check, CurrentBaseTris, TArrayView< InElementType, InSizeType >::GetData(), TArrayView< InElementType, InSizeType >::Num(), and Region.
FMeshRegionOperator() [2/2]
UE::Geometry::FMeshRegionOperator::FMeshRegionOperator (FDynamicMesh3 * Base, const TArrayView< const int > & RegionTris) inline
Definition at line 58 of file MeshRegionOperator.h.
References BaseMesh, check, CurrentBaseTris, TArrayView< InElementType, InSizeType >::GetData(), TArrayView< InElementType, InSizeType >::Num(), and Region.
Member Function Documentation
BackPropropagate()
bool UE::Geometry::FMeshRegionOperator::BackPropropagate (bool bAllowSubmeshRepairs = true) inline
Remove the original submesh region and merge in the remeshed version.
You can call this multiple times as the base-triangle-set is updated.
Parameters
bAllowSubmeshRepairs if true, we allow the submesh to be modified to prevent creation of non-manifold edges. You can disable this, however then some of the submesh triangles may be discarded.
Returns
false if there were errors in insertion, ie if some triangles failed to insert. Does not revert changes that were successful.
Definition at line 178 of file MeshRegionOperator.h.
References IndexUtil::ArrayCheck(), BaseMesh, checkSlow, CurrentBaseTris, ensure, Region, ReinsertDuplicateTriBehavior, ReinsertSubToBaseMapT, ReinsertSubToBaseMapV, Algo::RemoveIf(), RepairPossibleNonManifoldEdges(), TArray< InElementType, InAllocatorType >::Reserve(), and TArray< InElementType, InAllocatorType >::SetNum().
BackPropropagateVertices()
bool UE::Geometry::FMeshRegionOperator::BackPropropagateVertices (bool bRecomputeBoundaryNormals = false) inline
Transfer vertex positions in submesh back to base mesh; for use when the vertices in submesh still directly correspond back.
Returns
true on success
Definition at line 232 of file MeshRegionOperator.h.
References BaseMesh, UE::Geometry::FMeshNormals::ComputeVertexNormal(), and Region.
CurrentBaseInteriorVertices()
TSet< int > UE::Geometry::FMeshRegionOperator::CurrentBaseInteriorVertices () const inline
Returns
base mesh interior vertices of region (does not include region boundary vertices)
Definition at line 77 of file MeshRegionOperator.h.
References UE::Geometry::FIndex3i::A, TSet< InElementType, KeyFuncs, Allocator >::Add(), UE::Geometry::FIndex3i::B, BaseMesh, UE::Geometry::FIndex3i::C, TSet< InElementType, KeyFuncs, Allocator >::Contains(), CurrentBaseTris, and Region.
CurrentBaseTriangles()
const TArray< int > & UE::Geometry::FMeshRegionOperator::CurrentBaseTriangles () const inline
Returns
the array of sub-region triangles. This is either the input regionTris or the submesh triangles after they are re-inserted.
Definition at line 69 of file MeshRegionOperator.h.
References CurrentBaseTris.
RepairPossibleNonManifoldEdges()
void UE::Geometry::FMeshRegionOperator::RepairPossibleNonManifoldEdges () inline
After remeshing we may create an internal edge between two boundary vertices [a,b].
Those vertices will be merged with vertices c and d in the base mesh. If the edge [c,d] already exists in the base mesh, then after the merge we would have at least 3 triangles at this edge. Dang.
A common example is a 'fin' triangle that would duplicate a 'fin' on the border of the base mesh after removing the submesh, but this situation can arise anywhere (eg think about one-triangle-wide strips).
This is very hard to remove, but we can at least avoid creating non-manifold edges (which with the current DMesh3 will be prevented, hence leaving a hole) by splitting the internal edge in the submesh (which presumably we were remeshing anyway, so changes are ok).
Definition at line 114 of file MeshRegionOperator.h.
References UE::Geometry::FIndex2i::A, TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FIndex2i::B, BaseMesh, ensure, UE::Geometry::FDynamicMesh3::InvalidID, TArray< InElementType, InAllocatorType >::Num(), and Region.
Referenced by BackPropropagate().
SetSubmeshGroupID()
void UE::Geometry::FMeshRegionOperator::SetSubmeshGroupID (int GID) inline
Parameters
gid New group ID to set for entire submesh
Definition at line 163 of file MeshRegionOperator.h.
References Region, and FaceGroupUtil::SetGroupID().
Field Documentation
BaseMesh
FDynamicMesh3* UE::Geometry::FMeshRegionOperator::BaseMesh
Definition at line 34 of file MeshRegionOperator.h.
Referenced by FMeshRegionOperator(), FMeshRegionOperator(), BackPropropagate(), BackPropropagateVertices(), CurrentBaseInteriorVertices(), and RepairPossibleNonManifoldEdges().
CurrentBaseTris
TArray<int> UE::Geometry::FMeshRegionOperator::CurrentBaseTris
Definition at line 47 of file MeshRegionOperator.h.
Referenced by FMeshRegionOperator(), FMeshRegionOperator(), BackPropropagate(), CurrentBaseInteriorVertices(), and CurrentBaseTriangles().
Region
FDynamicSubmesh3 UE::Geometry::FMeshRegionOperator::Region
Definition at line 35 of file MeshRegionOperator.h.
Referenced by FMeshRegionOperator(), FMeshRegionOperator(), BackPropropagate(), BackPropropagateVertices(), CurrentBaseInteriorVertices(), RepairPossibleNonManifoldEdges(), and SetSubmeshGroupID().
ReinsertDuplicateTriBehavior
FDynamicMeshEditor::EDuplicateTriBehavior UE::Geometry::FMeshRegionOperator::ReinsertDuplicateTriBehavior = FDynamicMeshEditor::EDuplicateTriBehavior::EnsureContinue
Definition at line 44 of file MeshRegionOperator.h.
Referenced by BackPropropagate().
ReinsertSubToBaseMapT
FOptionallySparseIndexMap UE::Geometry::FMeshRegionOperator::ReinsertSubToBaseMapT
Definition at line 41 of file MeshRegionOperator.h.
Referenced by BackPropropagate().
ReinsertSubToBaseMapV
FOptionallySparseIndexMap UE::Geometry::FMeshRegionOperator::ReinsertSubToBaseMapV
Definition at line 38 of file MeshRegionOperator.h.
Referenced by BackPropropagate().
The documentation for this class was generated from the following file:
MeshRegionOperator.h