Unreal Engine 5.6 C++ API: FNavigationRelevantData Struct Reference
FNavigationRelevantData Struct Reference
#include "NavigationRelevantData.h"
Data Structures
struct FCollisionDataHeader
CollisionData should always start with this struct for validation purposes.
Public Member Functions
FNavigationRelevantData ()=delete
FNavigationRelevantData (const FNavigationRelevantData &Other)
FNavigationRelevantData (const TSharedRef< const FNavigationElement > &Source)
FNavigationRelevantData (FNavigationRelevantData &&Other)
DECLARE_DELEGATE_RetVal_OneParam (bool, FFilterNavDataDelegate, const struct FNavDataConfig *)
FORCEINLINE SIZE_T GetAllocatedSize () const
FORCEINLINE ENavigationDirtyFlag GetDirtyFlag () const
FORCEINLINE SIZE_T GetGeometryAllocatedSize () const
FCompositeNavModifier GetModifierForAgent (const FNavAgentProperties *NavAgent=nullptr) const
FORCEINLINE bool HasDynamicModifiers () const
FORCEINLINE bool HasGeometry () const
FORCEINLINE bool HasModifiers () const
bool HasPerInstanceTransforms () const
bool IsCollisionDataValid () const
FORCEINLINE bool IsEmpty () const
bool IsMatchingFilter (const FNavigationRelevantDataFilter &Filter) const
FORCEINLINE bool IsPendingChildLazyModifiersGathering () const
FORCEINLINE bool IsPendingLazyGeometryGathering () const
FORCEINLINE bool IsPendingLazyModifiersGathering () const
FORCEINLINE bool NeedAnyPendingLazyModifiersGathering () const
FNavigationRelevantData & operator= (const FNavigationRelevantData &Other)
FNavigationRelevantData & operator= (FNavigationRelevantData &&Other)
FORCEINLINE bool ShouldSkipDirtyAreaOnAddOrRemove () const
Indicates that this object will not dirty the navmesh when added or removed from the octree.
void Shrink ()
FORCEINLINE bool SupportsGatheringGeometrySlices () const
UE_DEPRECATED (5.5, "Use SourceElement instead.") 1 const UObject *GetOwner() const
UE_DEPRECATED (5.5, "Use SourceElement instead.") 1 TWeakObjectPtr< UObject > GetOwnerPtr() const
UE_DEPRECATED (5.5, "Use the constructor using FNavigationElement instead.") 1 FNavigationRelevantData(UObject &Source)
void ValidateAndShrink ()
Public Member Functions inherited from TSharedFromThis< FNavigationRelevantData, ESPMode::ThreadSafe >
TSharedRef< FNavigationRelevantData, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FNavigationRelevantData, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
uint32 bLoadedData: 1
From level loading (only valid in WP dynamic mode)
FBox Bounds
bounds of geometry (unreal coords)
uint32 bPendingChildLazyModifiersGathering: 1
uint32 bPendingLazyGeometryGathering: 1
get set to true when lazy navigation exporting is enabled and this navigation data has "potential" of containing geometry data.
uint32 bPendingLazyModifiersGathering: 1
uint32 bShouldSkipDirtyAreaOnAddOrRemove: 1
Indicates that this data will not dirty the navmesh when added or removed from the octree.
uint32 bSupportsGatheringGeometrySlices: 1
TNavStatArray< uint8 > CollisionData
exported geometry (used by recast navmesh as FRecastGeometryCache)
FCompositeNavModifier Modifiers
additional modifiers: areas and external links
FNavDataPerInstanceTransformDelegate NavDataPerInstanceTransformDelegate
Gathers per instance data for navigation geometry in a specified area box.
FFilterNavDataDelegate ShouldUseGeometryDelegate
called to check if hosted geometry should be used for given FNavDataConfig.
TSharedRef< const FNavigationElement > SourceElement
Navigation element this data represents.
TNavStatArray< uint8 > VoxelData
cached voxels (used by recast navmesh as FRecastVoxelCache)
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FNavigationRelevantData, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FNavigationRelevantData, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 39 of file NavigationRelevantData.h.
Constructor & Destructor Documentation
FNavigationRelevantData() [1/4]
FNavigationRelevantData::FNavigationRelevantData () delete
Referenced by FNavigationRelevantData(), FNavigationRelevantData(), FNavigationRelevantData(), operator=(), operator=(), and UE_DEPRECATED().
FNavigationRelevantData() [2/4]
FNavigationRelevantData::FNavigationRelevantData (const TSharedRef< const FNavigationElement > & Source) inline explicit
Definition at line 101 of file NavigationRelevantData.h.
References FNavigationRelevantData(), bLoadedData, bPendingChildLazyModifiersGathering, bPendingLazyGeometryGathering, bPendingLazyModifiersGathering, bShouldSkipDirtyAreaOnAddOrRemove, bSupportsGatheringGeometrySlices, Source, and SourceElement.
FNavigationRelevantData() [3/4]
FNavigationRelevantData::FNavigationRelevantData (const FNavigationRelevantData & Other)
References FNavigationRelevantData(), and Other.
FNavigationRelevantData() [4/4]
FNavigationRelevantData::FNavigationRelevantData (FNavigationRelevantData && Other)
References FNavigationRelevantData(), and Other.
Member Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
FNavigationRelevantData::DECLARE_DELEGATE_RetVal_OneParam (bool , FFilterNavDataDelegate , const struct FNavDataConfig *)
GetAllocatedSize()
FORCEINLINE SIZE_T FNavigationRelevantData::GetAllocatedSize () const inline
Definition at line 133 of file NavigationRelevantData.h.
References CollisionData, FORCEINLINE, Modifiers, and VoxelData.
GetDirtyFlag()
FORCEINLINE ENavigationDirtyFlag FNavigationRelevantData::GetDirtyFlag () const inline
Definition at line 135 of file NavigationRelevantData.h.
References DynamicModifier, FORCEINLINE, Geometry, HasDynamicModifiers(), HasGeometry(), IsPendingLazyGeometryGathering(), Modifiers, NeedAnyPendingLazyModifiersGathering(), None, and UseAgentHeight.
GetGeometryAllocatedSize()
FORCEINLINE SIZE_T FNavigationRelevantData::GetGeometryAllocatedSize () const inline
Definition at line 134 of file NavigationRelevantData.h.
References CollisionData, FORCEINLINE, and VoxelData.
GetModifierForAgent()
FCompositeNavModifier FNavigationRelevantData::GetModifierForAgent (const FNavAgentProperties * NavAgent = nullptr) const
HasDynamicModifiers()
FORCEINLINE bool FNavigationRelevantData::HasDynamicModifiers () const inline
Definition at line 119 of file NavigationRelevantData.h.
References FORCEINLINE, and Modifiers.
Referenced by GetDirtyFlag().
HasGeometry()
FORCEINLINE bool FNavigationRelevantData::HasGeometry () const inline
Definition at line 117 of file NavigationRelevantData.h.
References CollisionData, FORCEINLINE, and VoxelData.
Referenced by GetDirtyFlag(), and IsEmpty().
HasModifiers()
FORCEINLINE bool FNavigationRelevantData::HasModifiers () const inline
Definition at line 118 of file NavigationRelevantData.h.
References FORCEINLINE, and Modifiers.
Referenced by IsEmpty().
HasPerInstanceTransforms()
bool FNavigationRelevantData::HasPerInstanceTransforms () const
IsCollisionDataValid()
bool FNavigationRelevantData::IsCollisionDataValid () const
Referenced by ValidateAndShrink().
IsEmpty()
FORCEINLINE bool FNavigationRelevantData::IsEmpty () const inline
Definition at line 132 of file NavigationRelevantData.h.
References FORCEINLINE, HasGeometry(), and HasModifiers().
IsMatchingFilter()
bool FNavigationRelevantData::IsMatchingFilter (const FNavigationRelevantDataFilter & Filter) const
References Filter.
IsPendingChildLazyModifiersGathering()
FORCEINLINE bool FNavigationRelevantData::IsPendingChildLazyModifiersGathering () const inline
Definition at line 122 of file NavigationRelevantData.h.
References bPendingChildLazyModifiersGathering, and FORCEINLINE.
IsPendingLazyGeometryGathering()
FORCEINLINE bool FNavigationRelevantData::IsPendingLazyGeometryGathering () const inline
Definition at line 120 of file NavigationRelevantData.h.
References bPendingLazyGeometryGathering, and FORCEINLINE.
Referenced by GetDirtyFlag().
IsPendingLazyModifiersGathering()
FORCEINLINE bool FNavigationRelevantData::IsPendingLazyModifiersGathering () const inline
Definition at line 121 of file NavigationRelevantData.h.
References bPendingLazyModifiersGathering, and FORCEINLINE.
NeedAnyPendingLazyModifiersGathering()
FORCEINLINE bool FNavigationRelevantData::NeedAnyPendingLazyModifiersGathering () const inline
Definition at line 123 of file NavigationRelevantData.h.
References bPendingChildLazyModifiersGathering, bPendingLazyModifiersGathering, and FORCEINLINE.
Referenced by GetDirtyFlag().
operator=() [1/2]
FNavigationRelevantData & FNavigationRelevantData::operator= (const FNavigationRelevantData & Other)
References FNavigationRelevantData(), and Other.
operator=() [2/2]
FNavigationRelevantData & FNavigationRelevantData::operator= (FNavigationRelevantData && Other)
References FNavigationRelevantData(), and Other.
ShouldSkipDirtyAreaOnAddOrRemove()
FORCEINLINE bool FNavigationRelevantData::ShouldSkipDirtyAreaOnAddOrRemove () const inline
Indicates that this object will not dirty the navmesh when added or removed from the octree.
In this case we expect it to manually dirty areas (e.g. using OnObjectBoundsChanged).
Definition at line 130 of file NavigationRelevantData.h.
References bShouldSkipDirtyAreaOnAddOrRemove, and FORCEINLINE.
Shrink()
void FNavigationRelevantData::Shrink ()
Referenced by ValidateAndShrink().
SupportsGatheringGeometrySlices()
FORCEINLINE bool FNavigationRelevantData::SupportsGatheringGeometrySlices () const inline
Definition at line 124 of file NavigationRelevantData.h.
References bSupportsGatheringGeometrySlices, and FORCEINLINE.
UE_DEPRECATED() [1/3]
FNavigationRelevantData::UE_DEPRECATED (5. 5, "Use SourceElement instead.") const
UE_DEPRECATED() [2/3]
FNavigationRelevantData::UE_DEPRECATED (5. 5, "Use SourceElement instead.") const
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FNavigationRelevantData::UE_DEPRECATED (5. 5, "Use the constructor using FNavigationElement instead.") &
References FNavigationRelevantData(), and Source.
Referenced by UE_DEPRECATED().
ValidateAndShrink()
void FNavigationRelevantData::ValidateAndShrink () inline
Definition at line 159 of file NavigationRelevantData.h.
References CollisionData, IsCollisionDataValid(), and Shrink().
Field Documentation
bLoadedData
uint32 FNavigationRelevantData::bLoadedData
From level loading (only valid in WP dynamic mode)
Definition at line 94 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData().
Bounds
FBox FNavigationRelevantData::Bounds
bounds of geometry (unreal coords)
Definition at line 58 of file NavigationRelevantData.h.
bPendingChildLazyModifiersGathering
uint32 FNavigationRelevantData::bPendingChildLazyModifiersGathering
Definition at line 86 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData(), IsPendingChildLazyModifiersGathering(), and NeedAnyPendingLazyModifiersGathering().
bPendingLazyGeometryGathering
uint32 FNavigationRelevantData::bPendingLazyGeometryGathering
get set to true when lazy navigation exporting is enabled and this navigation data has "potential" of containing geometry data.
First access will result in gathering the data and setting this flag back to false. Mind that this flag can go back to 'true' if related data gets cleared out.
Definition at line 84 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData(), and IsPendingLazyGeometryGathering().
bPendingLazyModifiersGathering
uint32 FNavigationRelevantData::bPendingLazyModifiersGathering
Definition at line 85 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData(), IsPendingLazyModifiersGathering(), and NeedAnyPendingLazyModifiersGathering().
bShouldSkipDirtyAreaOnAddOrRemove
uint32 FNavigationRelevantData::bShouldSkipDirtyAreaOnAddOrRemove
Indicates that this data will not dirty the navmesh when added or removed from the octree.
Definition at line 91 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData(), and ShouldSkipDirtyAreaOnAddOrRemove().
bSupportsGatheringGeometrySlices
uint32 FNavigationRelevantData::bSupportsGatheringGeometrySlices
Definition at line 88 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData(), and SupportsGatheringGeometrySlices().
CollisionData
TNavStatArray<uint8> FNavigationRelevantData::CollisionData
exported geometry (used by recast navmesh as FRecastGeometryCache)
Definition at line 52 of file NavigationRelevantData.h.
Referenced by GetAllocatedSize(), GetGeometryAllocatedSize(), HasGeometry(), and ValidateAndShrink().
Modifiers
FCompositeNavModifier FNavigationRelevantData::Modifiers
additional modifiers: areas and external links
Definition at line 70 of file NavigationRelevantData.h.
Referenced by FPrimitiveComponentHelper::AddNavigationModifier(), GetAllocatedSize(), GetDirtyFlag(), FInstancedStaticMeshComponentHelper::GetNavigationData(), FStaticMeshComponentHelper::GetNavigationData(), HasDynamicModifiers(), and HasModifiers().
NavDataPerInstanceTransformDelegate
FNavDataPerInstanceTransformDelegate FNavigationRelevantData::NavDataPerInstanceTransformDelegate
Gathers per instance data for navigation geometry in a specified area box.
Definition at line 61 of file NavigationRelevantData.h.
Referenced by FInstancedStaticMeshComponentHelper::GetNavigationData().
ShouldUseGeometryDelegate
FFilterNavDataDelegate FNavigationRelevantData::ShouldUseGeometryDelegate
called to check if hosted geometry should be used for given FNavDataConfig.
If not set then "true" is assumed. Might want to set bUseVirtualGeometryFilteringAndDirtying to true in the Navmesh class you are excluding geometry from. This will improve cpu performance by stopping the navmesh from dirtying tiles requested by actors being excluded by this delegate.
Definition at line 67 of file NavigationRelevantData.h.
SourceElement
TSharedRef<const FNavigationElement> FNavigationRelevantData::SourceElement
Navigation element this data represents.
Definition at line 79 of file NavigationRelevantData.h.
Referenced by FNavigationRelevantData().
VoxelData
TNavStatArray<uint8> FNavigationRelevantData::VoxelData
cached voxels (used by recast navmesh as FRecastVoxelCache)
Definition at line 55 of file NavigationRelevantData.h.
Referenced by GetAllocatedSize(), GetGeometryAllocatedSize(), and HasGeometry().
The documentation for this struct was generated from the following file:
NavigationRelevantData.h