Unreal Engine 5.6 C++ API: FAllocOpBase Struct Reference
FAllocOpBase Struct Reference
#include "AllocLogRecordingPlayback.h"
Public Member Functions
int32 ParseValueStrings (const TArray< FString > &ValueStrings)
int32 WriteValueStrings (ANSICHAR *Dest) const
Static Public Member Functions
static int32 WriteHeader (ANSICHAR *Dest)
Data Fields
int64 AllocIndex
bool bIsFree
int32 FrameNumber
Detailed Description
Definition at line 18 of file AllocLogRecordingPlayback.h.
Member Function Documentation
ParseValueStrings()
int32 FAllocOpBase::ParseValueStrings (const TArray< FString > & ValueStrings) inline
Definition at line 34 of file AllocLogRecordingPlayback.h.
References AllocIndex, TCString< TCHAR >::Atoi(), TCString< TCHAR >::Atoi64(), bIsFree, FrameNumber, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
WriteHeader()
int32 FAllocOpBase::WriteHeader (ANSICHAR * Dest) inline static
Definition at line 24 of file AllocLogRecordingPlayback.h.
References TCString< ANSICHAR >::Sprintf().
WriteValueStrings()
int32 FAllocOpBase::WriteValueStrings (ANSICHAR * Dest) const inline
Definition at line 29 of file AllocLogRecordingPlayback.h.
References AllocIndex, bIsFree, FrameNumber, and TCString< ANSICHAR >::Sprintf().
Field Documentation
AllocIndex
int64 FAllocOpBase::AllocIndex
Definition at line 20 of file AllocLogRecordingPlayback.h.
Referenced by ParseValueStrings(), and WriteValueStrings().
bIsFree
bool FAllocOpBase::bIsFree
Definition at line 22 of file AllocLogRecordingPlayback.h.
Referenced by ParseValueStrings(), and WriteValueStrings().
FrameNumber
int32 FAllocOpBase::FrameNumber
Definition at line 21 of file AllocLogRecordingPlayback.h.
Referenced by ParseValueStrings(), and WriteValueStrings().
The documentation for this struct was generated from the following file:
AllocLogRecordingPlayback.h