Unreal Engine 5.6 C++ API: SBoxPanel::FScopedWidgetSlotArguments< SlotType > Struct Template Reference
SBoxPanel::FScopedWidgetSlotArguments< SlotType > Struct Template Reference
#include "SBoxPanel.h"
Public Member Functions
FScopedWidgetSlotArguments ()=delete
FScopedWidgetSlotArguments (const FScopedWidgetSlotArguments &)=delete
FScopedWidgetSlotArguments (FScopedWidgetSlotArguments &&)=default
FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< FSlot > &InChildren, int32 InIndex)
virtual ~FScopedWidgetSlotArguments ()
FScopedWidgetSlotArguments & operator= (const FScopedWidgetSlotArguments &)=delete
FScopedWidgetSlotArguments & operator= (FScopedWidgetSlotArguments &&)=default
Private Attributes
TPanelChildren< FSlot > & Children
int32 Index
Detailed Description
template<typename SlotType>
struct SBoxPanel::FScopedWidgetSlotArguments< SlotType >
Definition at line 71 of file SBoxPanel.h.
Constructor & Destructor Documentation
FScopedWidgetSlotArguments() [1/4]
template<typename SlotType> SBoxPanel::FScopedWidgetSlotArguments< SlotType >::FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< FSlot > & InChildren, int32 InIndex) inline
Definition at line 74 of file SBoxPanel.h.
References Children, Index, and MoveTemp().
Referenced by FScopedWidgetSlotArguments(), FScopedWidgetSlotArguments(), operator=(), and operator=().
FScopedWidgetSlotArguments() [2/4]
template<typename SlotType> SBoxPanel::FScopedWidgetSlotArguments< SlotType >::FScopedWidgetSlotArguments () delete
FScopedWidgetSlotArguments() [3/4]
template<typename SlotType> SBoxPanel::FScopedWidgetSlotArguments< SlotType >::FScopedWidgetSlotArguments (const FScopedWidgetSlotArguments< SlotType > &) delete
References FScopedWidgetSlotArguments().
FScopedWidgetSlotArguments() [4/4]
template<typename SlotType> SBoxPanel::FScopedWidgetSlotArguments< SlotType >::FScopedWidgetSlotArguments (FScopedWidgetSlotArguments< SlotType > &&) default
References FScopedWidgetSlotArguments().
~FScopedWidgetSlotArguments()
template<typename SlotType> virtual SBoxPanel::FScopedWidgetSlotArguments< SlotType >::~FScopedWidgetSlotArguments () inline virtual
Definition at line 87 of file SBoxPanel.h.
References Children, Index, INDEX_NONE, and MoveTemp().
Member Function Documentation
operator=() [1/2]
template<typename SlotType> FScopedWidgetSlotArguments & SBoxPanel::FScopedWidgetSlotArguments< SlotType >::operator= (const FScopedWidgetSlotArguments< SlotType > &) delete
References FScopedWidgetSlotArguments().
operator=() [2/2]
template<typename SlotType> FScopedWidgetSlotArguments & SBoxPanel::FScopedWidgetSlotArguments< SlotType >::operator= (FScopedWidgetSlotArguments< SlotType > &&) default
References FScopedWidgetSlotArguments().
Field Documentation
Children
template<typename SlotType> TPanelChildren<FSlot>& SBoxPanel::FScopedWidgetSlotArguments< SlotType >::Children private
Definition at line 104 of file SBoxPanel.h.
Referenced by FScopedWidgetSlotArguments(), and ~FScopedWidgetSlotArguments().
Index
template<typename SlotType> int32 SBoxPanel::FScopedWidgetSlotArguments< SlotType >::Index private
Definition at line 105 of file SBoxPanel.h.
Referenced by FScopedWidgetSlotArguments(), and ~FScopedWidgetSlotArguments().
The documentation for this struct was generated from the following file:
SBoxPanel.h