Unreal Engine 5.6 C++ API: UE::Geometry::FImageDimensions Class Reference
UE::Geometry::FImageDimensions Class Reference
FImageDimensions provides various functions for working with size/indices/coordinates of a 2D image, as well as standard UV spaces.
#include "ImageDimensions.h"
Public Member Functions
FImageDimensions (int32 WidthIn=0, int32 HeightIn=0)
void Clamp (FVector2i &Coords) const
Clamp input coordinates to valid range of image coordinates.
void Clamp (int32 &X, int32 &Y) const
Clamp input coordinates to valid range of image coordinates.
FVector2i GetCoords (int64 LinearIndex) const
int32 GetHeight () const
int64 GetIndex (const FVector2i &Coords) const
int64 GetIndex (int32 X, int32 Y) const
int64 GetIndexMirrored (const FVector2i &Coords, bool bFlipX, bool bFlipY) const
FVector2d GetTexelDistance (const FVector2d &P, const FVector2d Q) const
FVector2d GetTexelSize () const
FVector2d GetTexelUV (const FVector2i &Coords) const
FVector2d GetTexelUV (int64 LinearIndex) const
int32 GetWidth () const
bool IsSquare () const
bool IsValidCoords (const FVector2i &Coords) const
int64 Num () const
bool operator!= (const FImageDimensions &Other) const
bool operator== (const FImageDimensions &Other) const
FVector2i PixelToCoords (const FVector2d &PixelPosition) const
void SetDimensions (int32 WidthIn, int32 HeightIn)
Set the dimensions of this image.
FVector2i UVToCoords (const FVector2d &UVPosition) const
Protected Attributes
int32 Height = 0
int32 Width = 0
Detailed Description
FImageDimensions provides various functions for working with size/indices/coordinates of a 2D image, as well as standard UV spaces.
Definition at line 17 of file ImageDimensions.h.
Constructor & Destructor Documentation
FImageDimensions()
UE::Geometry::FImageDimensions::FImageDimensions (int32 WidthIn = 0, int32 HeightIn = 0) inline
Definition at line 24 of file ImageDimensions.h.
References SetDimensions().
Referenced by operator!=(), and operator==().
Member Function Documentation
Clamp() [1/2]
void UE::Geometry::FImageDimensions::Clamp (FVector2i & Coords) const inline
Clamp input coordinates to valid range of image coordinates.
Definition at line 61 of file ImageDimensions.h.
References FMath::Clamp(), Height, Width, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Clamp() [2/2]
void UE::Geometry::FImageDimensions::Clamp (int32 & X, int32 & Y) const inline
Clamp input coordinates to valid range of image coordinates.
Definition at line 54 of file ImageDimensions.h.
References FMath::Clamp(), Height, Width, X, and Y.
GetCoords()
FVector2i UE::Geometry::FImageDimensions::GetCoords (int64 LinearIndex) const inline
Returns
2D image coordinates from linear index
Definition at line 90 of file ImageDimensions.h.
References checkSlow, Num(), and Width.
Referenced by GetTexelUV().
GetHeight()
int32 UE::Geometry::FImageDimensions::GetHeight () const inline
Returns
height of image
Definition at line 40 of file ImageDimensions.h.
References Height.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation().
GetIndex() [1/2]
int64 UE::Geometry::FImageDimensions::GetIndex (const FVector2i & Coords) const inline
Returns
linear index into image from 2D coordinates
Definition at line 74 of file ImageDimensions.h.
References checkSlow, IsValidCoords(), Width, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
GetIndex() [2/2]
int64 UE::Geometry::FImageDimensions::GetIndex (int32 X, int32 Y) const inline
Returns
linear index into image from 2D coordinates
Definition at line 68 of file ImageDimensions.h.
References Width, X, and Y.
GetIndexMirrored()
int64 UE::Geometry::FImageDimensions::GetIndexMirrored (const FVector2i & Coords, bool bFlipX, bool bFlipY) const inline
Returns
linear index into image from 2D coordinates, optionally flipped around X and Y axes
Definition at line 81 of file ImageDimensions.h.
References checkSlow, Height, IsValidCoords(), Width, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
GetTexelDistance()
FVector2d UE::Geometry::FImageDimensions::GetTexelDistance (const FVector2d & P, const FVector2d Q) const inline
Returns
The distance, measured in texels, between points P and Q which should be given in the default UV-space [0..1]^2
Definition at line 117 of file ImageDimensions.h.
References Height, Width, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
GetTexelSize()
FVector2d UE::Geometry::FImageDimensions::GetTexelSize () const inline
Returns
Real-valued dimensions of a pixel/texel in the image, relative to default UV space [0..1]^2
Definition at line 97 of file ImageDimensions.h.
References Height, and Width.
GetTexelUV() [1/2]
FVector2d UE::Geometry::FImageDimensions::GetTexelUV (const FVector2i & Coords) const inline
Returns
Real-valued position of given texel center in default UV-space [0..1]^2
Definition at line 103 of file ImageDimensions.h.
References Height, Width, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Referenced by GetTexelUV().
GetTexelUV() [2/2]
FVector2d UE::Geometry::FImageDimensions::GetTexelUV (int64 LinearIndex) const inline
Returns
Real-valued position of given texel center in default UV-space [0..1]^2
Definition at line 111 of file ImageDimensions.h.
References GetCoords(), and GetTexelUV().
GetWidth()
int32 UE::Geometry::FImageDimensions::GetWidth () const inline
Returns
width of image
Definition at line 38 of file ImageDimensions.h.
References Width.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation().
IsSquare()
bool UE::Geometry::FImageDimensions::IsSquare () const inline
Returns
true if image is square
Definition at line 45 of file ImageDimensions.h.
References Height, and Width.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::FImageOccupancyMap::Initialize(), and UE::Geometry::FImageOccupancyMap::Initialize().
IsValidCoords()
bool UE::Geometry::FImageDimensions::IsValidCoords (const FVector2i & Coords) const inline
Returns
true if coordinates are valid, ie in-bounds of image dimensions
Definition at line 48 of file ImageDimensions.h.
References Height, Width, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Referenced by GetIndex(), and GetIndexMirrored().
Num()
int64 UE::Geometry::FImageDimensions::Num () const inline
Returns
number of elements in image
Definition at line 42 of file ImageDimensions.h.
References Height, and Width.
Referenced by GetCoords().
operator!=()
bool UE::Geometry::FImageDimensions::operator!= (const FImageDimensions & Other) const inline
Definition at line 146 of file ImageDimensions.h.
References FImageDimensions(), and Other.
operator==()
bool UE::Geometry::FImageDimensions::operator== (const FImageDimensions & Other) const inline
Definition at line 141 of file ImageDimensions.h.
References FImageDimensions(), Height, Other, and Width.
PixelToCoords()
FVector2i UE::Geometry::FImageDimensions::PixelToCoords (const FVector2d & PixelPosition) const inline
Returns
integer XY coordinates for real-valued XY coordinates (ie texel that contains value, if texel origin is in bottom-left
Definition at line 126 of file ImageDimensions.h.
References FMath::Clamp(), Height, Width, UE::Math::TVector2< T >::X, X, Y, and UE::Math::TVector2< T >::Y.
Referenced by UVToCoords().
SetDimensions()
void UE::Geometry::FImageDimensions::SetDimensions (int32 WidthIn, int32 HeightIn) inline
Set the dimensions of this image.
Definition at line 30 of file ImageDimensions.h.
References check, Height, and Width.
Referenced by FImageDimensions().
UVToCoords()
FVector2i UE::Geometry::FImageDimensions::UVToCoords (const FVector2d & UVPosition) const inline
Returns
integer XY coordinates for UV coordinates, assuming default UV space [0..1]^2
Definition at line 134 of file ImageDimensions.h.
References Height, PixelToCoords(), UE::Geometry::UVPosition, and Width.
Field Documentation
Height
int32 UE::Geometry::FImageDimensions::Height = 0 protected
Definition at line 21 of file ImageDimensions.h.
Referenced by Clamp(), Clamp(), GetHeight(), GetIndexMirrored(), GetTexelDistance(), GetTexelSize(), GetTexelUV(), IsSquare(), IsValidCoords(), Num(), operator==(), PixelToCoords(), SetDimensions(), and UVToCoords().
Width
int32 UE::Geometry::FImageDimensions::Width = 0 protected
Definition at line 20 of file ImageDimensions.h.
Referenced by Clamp(), Clamp(), GetCoords(), GetIndex(), GetIndex(), GetIndexMirrored(), GetTexelDistance(), GetTexelSize(), GetTexelUV(), GetWidth(), IsSquare(), IsValidCoords(), Num(), operator==(), PixelToCoords(), SetDimensions(), and UVToCoords().
The documentation for this class was generated from the following file:
ImageDimensions.h