Unreal Engine 5.6 C++ API: UBlueprintSetLibrary Class Reference
UBlueprintSetLibrary Class Reference
#include "BlueprintSetLibrary.h"
Private Member Functions
DECLARE_FUNCTION (execSet_Add)
DECLARE_FUNCTION (execSet_AddItems)
DECLARE_FUNCTION (execSet_Clear)
DECLARE_FUNCTION (execSet_Contains)
DECLARE_FUNCTION (execSet_Difference)
DECLARE_FUNCTION (execSet_GetItemByIndex)
DECLARE_FUNCTION (execSet_GetLastIndex)
DECLARE_FUNCTION (execSet_Intersection)
DECLARE_FUNCTION (execSet_IsEmpty)
DECLARE_FUNCTION (execSet_IsNotEmpty)
DECLARE_FUNCTION (execSet_Length)
DECLARE_FUNCTION (execSet_Remove)
DECLARE_FUNCTION (execSet_RemoveItems)
DECLARE_FUNCTION (execSet_ToArray)
DECLARE_FUNCTION (execSet_Union)
DECLARE_FUNCTION (execSetSetPropertyByName)
GENERATED_BODY() public UFUNCTION ()
Adds item to set.
UFUNCTION ()
Remove item from set.
UFUNCTION ()
Check if the set is empty.
UFUNCTION ()
Check if the set has any elements.
UFUNCTION ()
Removes all elements in an Array from a set.
UFUNCTION ()
Outputs an Array containing copies of the entries of a Set.
UFUNCTION ()
Clear a set, removes all content.
UFUNCTION ()
Get the number of items in a set.
UFUNCTION ()
Returns true if the set contains the given item.
UFUNCTION ()
Assigns Result to the intersection of Set A and Set B.
UFUNCTION ()
Assigns Result to the union of two sets, A and B.
UFUNCTION ()
Assigns Result to the relative difference of two sets, A and B.
UFUNCTION ()
Given a set and an index, returns a copy of the item found at that index.
UFUNCTION ()
Retrieves the last valid index for a set.
UFUNCTION ()) static 1 void SetSetPropertyByName(UObject *Object
Not exposed to users.
Static Private Member Functions
static void GenericSet_Add (const void *TargetSet, const FSetProperty *SetProperty, const void *ItemPtr)
static void GenericSet_AddItems (const void *TargetSet, const FSetProperty *SetProperty, const void *TargetArray, const FArrayProperty *ArrayProperty)
static void GenericSet_Clear (const void *TargetSet, const FSetProperty *SetProperty)
static bool GenericSet_Contains (const void *TargetSet, const FSetProperty *SetProperty, const void *ItemToFind)
static void GenericSet_Difference (const void *SetA, const FSetProperty *SetPropertyA, const void *SetB, const FSetProperty *SetPropertyB, const void *SetResult, const FSetProperty *SetPropertyResult)
static void GenericSet_GetItemByIndex (void *TargetSet, const FSetProperty *SetProperty, int32 Index, void *Item)
static int32 GenericSet_GetLastIndex (const void *TargetSet, const FSetProperty *SetProperty)
static void GenericSet_Intersect (const void *SetA, const FSetProperty *SetPropertyA, const void *SetB, const FSetProperty *SetPropertyB, const void *SetResult, const FSetProperty *SetPropertyResult)
static bool GenericSet_IsEmpty (const void *TargetSet, const FSetProperty *SetProperty)
static bool GenericSet_IsNotEmpty (const void *TargetSet, const FSetProperty *SetProperty)
static int32 GenericSet_Length (const void *TargetSet, const FSetProperty *SetProperty)
static bool GenericSet_Remove (const void *TargetSet, const FSetProperty *SetProperty, const void *ItemPtr)
static void GenericSet_RemoveItems (const void *TargetSet, const FSetProperty *SetProperty, const void *TargetArray, const FArrayProperty *ArrayProperty)
static void GenericSet_SetSetPropertyByName (UObject *OwnerObject, FName SetPropertyName, const void *SrcSetAddr)
static void GenericSet_ToArray (const void *TargetSet, const FSetProperty *SetProperty, void *TargetArray, const FArrayProperty *ArrayProperty)
static void GenericSet_Union (const void *SetA, const FSetProperty *SetPropertyA, const void *SetB, const FSetProperty *SetPropertyB, const void *SetResult, const FSetProperty *SetPropertyResult)
Private Attributes
GENERATED_BODY() public Category
Category
FName PropertyName
FName const TSet< int32 > & Value
Static Private Attributes
static constexpr int32 MaxSupportedSetSize = TNumericLimits<int32>::Max()
Detailed Description
Definition at line 14 of file BlueprintSetLibrary.h.
Member Function Documentation
DECLARE_FUNCTION() [1/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Add) inline private
Definition at line 175 of file BlueprintSetLibrary.h.
References CastField(), DECLARE_FUNCTION(), FProperty::DestroyValue(), FMemory_Alloca, GenericSet_Add(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
Referenced by DECLARE_FUNCTION().
DECLARE_FUNCTION() [2/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_AddItems) inline private
Definition at line 207 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_AddItems(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
DECLARE_FUNCTION() [3/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Clear) inline private
Definition at line 325 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_Clear(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
DECLARE_FUNCTION() [4/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Contains) inline private
Definition at line 366 of file BlueprintSetLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericSet_Contains(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [5/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Difference) inline private
Definition at line 515 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_Difference(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [6/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_GetItemByIndex) inline private
Definition at line 569 of file BlueprintSetLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericSet_GetItemByIndex(), FField::GetClass(), FProperty::GetElementSize(), FProperty::InitializeValue(), FFieldClass::IsChildOf(), P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
DECLARE_FUNCTION() [7/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_GetLastIndex) inline private
Definition at line 613 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_GetLastIndex(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [8/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Intersection) inline private
Definition at line 437 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_Intersect(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [9/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_IsEmpty) inline private
Definition at line 399 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_IsEmpty(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [10/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_IsNotEmpty) inline private
Definition at line 418 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_IsNotEmpty(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [11/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Length) inline private
Definition at line 346 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_Length(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [12/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Remove) inline private
Definition at line 236 of file BlueprintSetLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericSet_Remove(), FProperty::GetElementSize(), FProperty::InitializeValue(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, RESULT_PARAM, and SetProperty.
DECLARE_FUNCTION() [13/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_RemoveItems) inline private
Definition at line 267 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_RemoveItems(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
DECLARE_FUNCTION() [14/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_ToArray) inline private
Definition at line 296 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_ToArray(), P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and SetProperty.
DECLARE_FUNCTION() [15/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSet_Union) inline private
Definition at line 476 of file BlueprintSetLibrary.h.
References CastField(), GenericSet_Union(), P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [16/16]
UBlueprintSetLibrary::DECLARE_FUNCTION (execSetSetPropertyByName) inline private
Definition at line 554 of file BlueprintSetLibrary.h.
References GenericSet_SetSetPropertyByName(), P_FINISH, P_GET_OBJECT, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
GenericSet_Add()
void UBlueprintSetLibrary::GenericSet_Add (const void * TargetSet, const FSetProperty * SetProperty, const void * ItemPtr) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_AddItems()
void UBlueprintSetLibrary::GenericSet_AddItems (const void * TargetSet, const FSetProperty * SetProperty, const void * TargetArray, const FArrayProperty * ArrayProperty) static private
References ArrayProperty, and SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Clear()
void UBlueprintSetLibrary::GenericSet_Clear (const void * TargetSet, const FSetProperty * SetProperty) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Contains()
bool UBlueprintSetLibrary::GenericSet_Contains (const void * TargetSet, const FSetProperty * SetProperty, const void * ItemToFind) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Difference()
void UBlueprintSetLibrary::GenericSet_Difference (const void * SetA, const FSetProperty * SetPropertyA, const void * SetB, const FSetProperty * SetPropertyB, const void * SetResult, const FSetProperty * SetPropertyResult) static private
Referenced by DECLARE_FUNCTION().
GenericSet_GetItemByIndex()
void UBlueprintSetLibrary::GenericSet_GetItemByIndex (void * TargetSet, const FSetProperty * SetProperty, int32 Index, void * Item) static private
References Item, and SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_GetLastIndex()
int32 UBlueprintSetLibrary::GenericSet_GetLastIndex (const void * TargetSet, const FSetProperty * SetProperty) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Intersect()
void UBlueprintSetLibrary::GenericSet_Intersect (const void * SetA, const FSetProperty * SetPropertyA, const void * SetB, const FSetProperty * SetPropertyB, const void * SetResult, const FSetProperty * SetPropertyResult) static private
Referenced by DECLARE_FUNCTION().
GenericSet_IsEmpty()
bool UBlueprintSetLibrary::GenericSet_IsEmpty (const void * TargetSet, const FSetProperty * SetProperty) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_IsNotEmpty()
bool UBlueprintSetLibrary::GenericSet_IsNotEmpty (const void * TargetSet, const FSetProperty * SetProperty) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Length()
int32 UBlueprintSetLibrary::GenericSet_Length (const void * TargetSet, const FSetProperty * SetProperty) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Remove()
bool UBlueprintSetLibrary::GenericSet_Remove (const void * TargetSet, const FSetProperty * SetProperty, const void * ItemPtr) static private
References SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_RemoveItems()
void UBlueprintSetLibrary::GenericSet_RemoveItems (const void * TargetSet, const FSetProperty * SetProperty, const void * TargetArray, const FArrayProperty * ArrayProperty) static private
References ArrayProperty, and SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_SetSetPropertyByName()
void UBlueprintSetLibrary::GenericSet_SetSetPropertyByName (UObject * OwnerObject, FName SetPropertyName, const void * SrcSetAddr) static private
Referenced by DECLARE_FUNCTION().
GenericSet_ToArray()
void UBlueprintSetLibrary::GenericSet_ToArray (const void * TargetSet, const FSetProperty * SetProperty, void * TargetArray, const FArrayProperty * ArrayProperty) static private
References ArrayProperty, and SetProperty.
Referenced by DECLARE_FUNCTION().
GenericSet_Union()
void UBlueprintSetLibrary::GenericSet_Union (const void * SetA, const FSetProperty * SetPropertyA, const void * SetB, const FSetProperty * SetPropertyB, const void * SetResult, const FSetProperty * SetPropertyResult) static private
Referenced by DECLARE_FUNCTION().
UFUNCTION() [1/15]
GENERATED_BODY() public UBlueprintSetLibrary::UFUNCTION () private
Adds item to set.
Parameters
TargetSet The set to add item to
NewItem The item to add to the set Adds all elements from an Array to a Set
TargetSet The set to search for the item
NewItems The items to add to the set
Referenced by UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/15]
UBlueprintSetLibrary::UFUNCTION () private
Remove item from set.
Output value indicates if something was actually removed. False indicates no equivalent item was found.
Parameters
TargetSet The set to remove from
Item The item to remove from the set
Returns
True if an item was removed (False indicates no equivalent item was present)
UFUNCTION() [3/15]
UBlueprintSetLibrary::UFUNCTION () private
Check if the set is empty.
Parameters
TargetSet The set to check
Returns
A boolean indicating if the array is empty
References Category, meta, and UFUNCTION().
UFUNCTION() [4/15]
UBlueprintSetLibrary::UFUNCTION () private
Check if the set has any elements.
Parameters
TargetSet The set to check
Returns
A boolean indicating if the array has any elements
References Category, meta, and UFUNCTION().
UFUNCTION() [5/15]
UBlueprintSetLibrary::UFUNCTION () private
Removes all elements in an Array from a set.
Parameters
TargetSet The set to remove from
Items The items to remove from the set
References Category, meta, and UFUNCTION().
UFUNCTION() [6/15]
UBlueprintSetLibrary::UFUNCTION () private
Outputs an Array containing copies of the entries of a Set.
Parameters
A Set
Result Array
References A, Category, meta, and UFUNCTION().
UFUNCTION() [7/15]
UBlueprintSetLibrary::UFUNCTION () private
Clear a set, removes all content.
Parameters
TargetSet The set to clear
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [8/15]
UBlueprintSetLibrary::UFUNCTION () private
Get the number of items in a set.
Parameters
TargetSet The set to get the length of
Returns
The length of the set
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [9/15]
UBlueprintSetLibrary::UFUNCTION () private
Returns true if the set contains the given item.
Parameters
TargetSet The set to search for the item
ItemToFind The item to look for
Returns
True if the item was found within the set
References Category, meta, and UFUNCTION().
UFUNCTION() [10/15]
UBlueprintSetLibrary::UFUNCTION () private
Assigns Result to the intersection of Set A and Set B.
That is, Result will contain all elements that are in both Set A and Set B. To intersect with the empty set use Clear.
Parameters
A One set to intersect
B Another set to intersect
Result Set to store results in
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [11/15]
UBlueprintSetLibrary::UFUNCTION () private
Assigns Result to the union of two sets, A and B.
That is, Result will contain all elements that are in Set A and in addition all elements in Set B. Note that a Set is a collection of unique elements, so duplicates will be eliminated.
Parameters
A One set to union
B Another set to union
Result Set to store results in
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [12/15]
UBlueprintSetLibrary::UFUNCTION () private
Assigns Result to the relative difference of two sets, A and B.
That is, Result will contain all elements that are in Set A but are not found in Set B. Note that the difference between two sets is not commutative. The Set whose elements you wish to preserve should be the first (top) parameter. Also called the relative complement.
Parameters
A Starting set
B Set of elements to remove from set A
Result Set containing all elements in A that are not found in B
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [13/15]
UBlueprintSetLibrary::UFUNCTION () private
Given a set and an index, returns a copy of the item found at that index.
Index may differ from the order in which they were added. This function is implemented for the purpose of iterating sets by index.
Parameters
TargetSet The set to get an item from
Index The index in the set to get an item from
Returns
A copy of the item stored at the index
References Category, Item, meta, and UFUNCTION().
UFUNCTION() [14/15]
UBlueprintSetLibrary::UFUNCTION () private
Retrieves the last valid index for a set.
Parameters
TargetSet The set in question
Returns
The number of entries in the set
References Category, meta, and UFUNCTION().
UFUNCTION() [15/15]
UBlueprintSetLibrary::UFUNCTION () private
Not exposed to users.
Supports setting a set property on an object by name.
References meta, and UFUNCTION().
Field Documentation
Category [1/2]
GENERATED_BODY() public UBlueprintSetLibrary::Category private
Initial value:
="Utilities|Set")
    static 1 void Set_AddItems(const TSet<int32>& TargetSet, const TArray<int32>& NewItems)
Definition at line 34 of file BlueprintSetLibrary.h.
Referenced by UFUNCTION().
Category [2/2]
UBlueprintSetLibrary::Category private
Initial value:
="Utilities|Set")
    static 1 bool Set_Remove(const TSet<int32>& TargetSet, const int32& Item)
Definition at line 45 of file BlueprintSetLibrary.h.
MaxSupportedSetSize
int32 UBlueprintSetLibrary::MaxSupportedSetSize = TNumericLimits<int32>::Max() static constexpr private
Definition at line 649 of file BlueprintSetLibrary.h.
PropertyName
FName UBlueprintSetLibrary::PropertyName private
Definition at line 152 of file BlueprintSetLibrary.h.
Value
FName const TSet<int32>& UBlueprintSetLibrary::Value private
Definition at line 152 of file BlueprintSetLibrary.h.
The documentation for this class was generated from the following file:
BlueprintSetLibrary.h