Unreal Engine 5.6 C++ API: FVector4Distribution Class Reference
FVector4Distribution Class Reference
Raw distribution from which four floats can be looked up per entry.
#include "Distributions.h"
Public Member Functions
FVector4Distribution ()
Default constructor.
FORCEINLINE void GetRandomValue (float Time, float *RESTRICT OutValue, FRandomStream &RandomStream) const
Samples a value randomly distributed between two values.
void GetRange (FVector4d *OutMin, FVector4d *OutMax)
void GetRange (FVector4f *OutMin, FVector4f *OutMax)
Computes the range of the distribution.
FORCEINLINE void GetValue (float Time, float *RESTRICT OutValue) const
Samples a value from the distribution.
Private Attributes
FDistributionLookupTable LookupTable
The lookup table.
Friends
class FComposableDistribution
This distribution is built from composable distributions.
Detailed Description
Raw distribution from which four floats can be looked up per entry.
Definition at line 412 of file Distributions.h.
Constructor & Destructor Documentation
FVector4Distribution()
FVector4Distribution::FVector4Distribution ()
Default constructor.
Member Function Documentation
GetRandomValue()
FORCEINLINE void FVector4Distribution::GetRandomValue (float Time, float *RESTRICT OutValue, FRandomStream & RandomStream) const inline
Samples a value randomly distributed between two values.
Parameters
Time - Time at which to sample the distribution.
OutValue - Upon return contains the sampled value.
RandomStream - Random stream from which to retrieve random fractions.
Definition at line 444 of file Distributions.h.
References Alpha, checkDistribution, FORCEINLINE, FMath::Lerp(), LookupTable, RandomStream, RESTRICT, and Time.
GetRange() [1/2]
void FVector4Distribution::GetRange (FVector4d * OutMin, FVector4d * OutMax) inline
Definition at line 489 of file Distributions.h.
References GetRange().
GetRange() [2/2]
void FVector4Distribution::GetRange (FVector4f * OutMin, FVector4f * OutMax) inline
Computes the range of the distribution.
Parameters
OutMin - The minimum value in the distribution.
OutMax - The maximum value in the distribution.
Definition at line 483 of file Distributions.h.
References LookupTable.
Referenced by GetRange().
GetValue()
FORCEINLINE void FVector4Distribution::GetValue (float Time, float *RESTRICT OutValue) const inline
Samples a value from the distribution.
Parameters
Time - Time at which to sample the distribution.
OutValue - Upon return contains the sampled value.
Definition at line 423 of file Distributions.h.
References Alpha, checkDistribution, FORCEINLINE, FMath::Lerp(), LookupTable, RESTRICT, and Time.
Friends And Related Symbol Documentation
FComposableDistribution
friend class FComposableDistribution friend
This distribution is built from composable distributions.
Definition at line 502 of file Distributions.h.
References FComposableDistribution.
Referenced by FComposableDistribution.
Field Documentation
LookupTable
FDistributionLookupTable FVector4Distribution::LookupTable private
The lookup table.
Definition at line 499 of file Distributions.h.
Referenced by GetRandomValue(), GetRange(), and GetValue().
The documentation for this class was generated from the following file:
Distributions.h