Unreal Engine 5.6 C++ API: Metasound::FNodeFacade Class Reference
Metasound::FNodeFacade Class Reference
FNodeFacade implements a significant amount of boilerplate code required to build a Metasound INode.
#include "MetasoundFacade.h"
Data Structures
class FFactory
Public Member Functions
FNodeFacade ()=delete
template<typename OperatorType>
FNodeFacade (const FVertexName &InInstanceName, const FGuid &InInstanceID, TFacadeOperatorClass< OperatorType > OperatorClass)
FNodeFacade constructor using the OperatorType template parameter to get the node info, operator factory method and vertex interface.
template<typename OperatorType>
FNodeFacade (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata, TFacadeOperatorClass< OperatorType > OperatorClass)
template<typename OperatorType>
FNodeFacade (FNodeInitData InInitData, TFacadeOperatorClass< OperatorType > OperatorClass)
virtual ~FNodeFacade ()=default
virtual METASOUNDGRAPHCORE_API FOperatorFactorySharedRef GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Private Attributes
TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > Factory
Detailed Description
FNodeFacade implements a significant amount of boilerplate code required to build a Metasound INode.
FNodeFacade is particularly useful for an INode which has a static FVertexInterface, and always creates the same IOperator type.
The type of the concrete IOperator class to instantiate is defined in the FNodeFacade constructors TFacadeOperatorClass<>.
Definition at line 91 of file MetasoundFacade.h.
Constructor & Destructor Documentation
FNodeFacade() [1/4]
Metasound::FNodeFacade::FNodeFacade () delete
Referenced by FNodeFacade(), FNodeFacade(), Metasound::TNodeFacade< TArrayNumOperator< ArrayType > >::TNodeFacade(), and Metasound::TNodeFacade< TArrayNumOperator< ArrayType > >::TNodeFacade().
FNodeFacade() [2/4]
template<typename OperatorType> Metasound::FNodeFacade::FNodeFacade (const FVertexName & InInstanceName, const FGuid & InInstanceID, TFacadeOperatorClass< OperatorType > OperatorClass) inline
FNodeFacade constructor using the OperatorType template parameter to get the node info, operator factory method and vertex interface.
Parameters
InInstanceName - Instance name for the node.
InInstanceID - Instance ID for the node.
OperatorClass - Template class wrapper for the underlying IOperator which is created by this node.
Definition at line 122 of file MetasoundFacade.h.
References FNodeFacade(), and MakeShared().
FNodeFacade() [3/4]
template<typename OperatorType> Metasound::FNodeFacade::FNodeFacade (FNodeInitData InInitData, TFacadeOperatorClass< OperatorType > OperatorClass) inline
Definition at line 128 of file MetasoundFacade.h.
References FNodeFacade(), and MakeShared().
FNodeFacade() [4/4]
template<typename OperatorType> Metasound::FNodeFacade::FNodeFacade (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata, TFacadeOperatorClass< OperatorType > OperatorClass) inline
Definition at line 134 of file MetasoundFacade.h.
References Metasound::FBasicNode::FBasicNode(), Factory, MakeShared(), MoveTemp(), and ThreadSafe.
~FNodeFacade()
virtual Metasound::FNodeFacade::~FNodeFacade () virtual default
Member Function Documentation
GetDefaultOperatorFactory()
virtual METASOUNDGRAPHCORE_API FOperatorFactorySharedRef Metasound::FNodeFacade::GetDefaultOperatorFactory () const override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
References UE_API.
Field Documentation
Factory
TSharedRef<IOperatorFactory, ESPMode::ThreadSafe> Metasound::FNodeFacade::Factory private
Definition at line 147 of file MetasoundFacade.h.
Referenced by FNodeFacade().
The documentation for this class was generated from the following file:
MetasoundFacade.h