Unreal Engine 5.6 C++ API: FMyBlueprintItemDragDropAction Class Reference
FMyBlueprintItemDragDropAction Class Reference
DragDropAction class for drag and dropping an item from the My Blueprints tree (e.g., variable or function)
#include "MyBlueprintItemDragDropAction.h"
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FMyBlueprintItemDragDropAction, FGraphSchemaActionDragDropAction) virtual FReply DroppedOnAction(TSharedRef< FEdGraphSchemaAction > Action) override
virtual FReply DroppedOnCategory (FText Category) override
virtual void HoverTargetChanged () override
void SetAltDrag (bool InIsAltDrag)
Set if operation is modified by alt.
void SetCtrlDrag (bool InIsCtrlDrag)
Set if operation is modified by the ctrl key.
Public Member Functions inherited from FGraphSchemaActionDragDropAction
DRAG_DROP_OPERATOR_TYPE (FGraphSchemaActionDragDropAction, FGraphEditorDragDropAction) virtual void HoverTargetChanged() override
virtual FReply DroppedOnPanel (const TSharedRef< SWidget > &Panel, const FVector2f &ScreenPosition, const FVector2f &GraphPosition, UEdGraph &Graph) override
virtual FReply DroppedOnPin (const FVector2f &ScreenPosition, const FVector2f &GraphPosition) override
Public Member Functions inherited from FGraphEditorDragDropAction
DRAG_DROP_OPERATOR_TYPE (FGraphEditorDragDropAction, FDragDropOperation) FGraphEditorDragDropAction()
virtual FReply DroppedOnAction (TSharedRef< struct FEdGraphSchemaAction > Action)
virtual FReply DroppedOnNode (const FVector2f &ScreenPosition, const FVector2f &GraphPosition)
bool HasFeedbackMessage ()
virtual bool IsSupportedBySchema (const UEdGraphSchema *Schema) const
void SetDropTargetValid (bool bValid)
void SetFeedbackMessage (const TSharedPtr< SWidget > &Message)
void SetHoveredAction (TSharedPtr< struct FEdGraphSchemaAction > Action)
void SetHoveredCategoryName (const FText &InHoverCategoryName)
void SetHoveredGraph (const TSharedPtr< SGraphPanel > &InGraph)
void SetHoveredNode (const TSharedPtr< SGraphNode > &InNode)
void SetHoveredNode (UEdGraphNode *InNode)
void SetHoveredPin (UEdGraphPin *InPin)
void SetSimpleFeedbackMessage (const FSlateBrush *Icon, const FSlateColor &IconColor, const FText &Message, const FSlateBrush *SecondaryIcon=nullptr, const FSlateColor SecondaryColor=FSlateColor())
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnNode(FVector2D ScreenPosition
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPanel(const TSharedRef< SWidget > &Panel
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPin(FVector2D ScreenPosition
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
FMyBlueprintItemDragDropAction ()
Constructor.
virtual UBlueprint * GetSourceBlueprint () const
bool IsFromBlueprint (UBlueprint *InBlueprint) const
Helper method to see if we're dragging in the same blueprint.
void SetFeedbackMessageError (const FText &Message)
void SetFeedbackMessageOK (const FText &Message)
Protected Member Functions inherited from FGraphSchemaActionDragDropAction
virtual void GetDefaultStatusSymbol (const FSlateBrush *&PrimaryBrushOut, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut) const
Protected Member Functions inherited from FGraphEditorDragDropAction
virtual void Construct () override
Constructs the window and widget if applicable.
virtual EVisibility GetErrorIconVisible () const
UEdGraph * GetHoveredGraph () const
UEdGraphNode * GetHoveredNode () const
UEdGraphPin * GetHoveredPin () const
virtual EVisibility GetIconVisible () const
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FNodeCreationAnalytic AnalyticCallback
Analytic delegate to track node creation.
bool bAltDrag
Was alt held down at the start of drag.
bool bControlDrag
Was ctrl held down at start of drag.
Protected Attributes inherited from FGraphSchemaActionDragDropAction
TSharedPtr< FEdGraphSchemaAction > SourceAction
Protected Attributes inherited from FGraphEditorDragDropAction
bool bDropTargetValid
TWeakPtr< struct FEdGraphSchemaAction > HoveredAction
FText HoveredCategoryName
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Static Public Member Functions inherited from FGraphSchemaActionDragDropAction
static TSharedRef< FGraphSchemaActionDragDropAction > New (TSharedPtr< FEdGraphSchemaAction > InActionNode)
Data Fields inherited from FGraphEditorDragDropAction
FVector2D FVector2D GraphPosition
FVector2D ScreenPosition
FVector2D GraphPosition UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
FVector2D FVector2D UEdGraph &Graph UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
DragDropAction class for drag and dropping an item from the My Blueprints tree (e.g., variable or function)
Definition at line 22 of file MyBlueprintItemDragDropAction.h.
Constructor & Destructor Documentation
FMyBlueprintItemDragDropAction()
FMyBlueprintItemDragDropAction::FMyBlueprintItemDragDropAction () protected
Constructor.
Referenced by FKismetVariableDragDropAction::DRAG_DROP_OPERATOR_TYPE(), and DRAG_DROP_OPERATOR_TYPE().
Member Function Documentation
DRAG_DROP_OPERATOR_TYPE()
FMyBlueprintItemDragDropAction::DRAG_DROP_OPERATOR_TYPE (FMyBlueprintItemDragDropAction , FGraphSchemaActionDragDropAction) override
References FMyBlueprintItemDragDropAction().
DroppedOnCategory()
virtual FReply FMyBlueprintItemDragDropAction::DroppedOnCategory (FText Category) override virtual
Reimplemented from FGraphEditorDragDropAction.
References Category.
GetSourceBlueprint()
virtual UBlueprint * FMyBlueprintItemDragDropAction::GetSourceBlueprint () const inline protected virtual
Reimplemented in FKismetVariableDragDropAction.
Definition at line 43 of file MyBlueprintItemDragDropAction.h.
Referenced by IsFromBlueprint().
HoverTargetChanged()
virtual void FMyBlueprintItemDragDropAction::HoverTargetChanged () override virtual
Reimplemented from FGraphEditorDragDropAction.
IsFromBlueprint()
bool FMyBlueprintItemDragDropAction::IsFromBlueprint (UBlueprint * InBlueprint) const inline protected
Helper method to see if we're dragging in the same blueprint.
Definition at line 49 of file MyBlueprintItemDragDropAction.h.
References GetSourceBlueprint().
SetAltDrag()
void FMyBlueprintItemDragDropAction::SetAltDrag (bool InIsAltDrag) inline
Set if operation is modified by alt.
Definition at line 34 of file MyBlueprintItemDragDropAction.h.
References bAltDrag.
SetCtrlDrag()
void FMyBlueprintItemDragDropAction::SetCtrlDrag (bool InIsCtrlDrag) inline
Set if operation is modified by the ctrl key.
Definition at line 37 of file MyBlueprintItemDragDropAction.h.
References bControlDrag.
SetFeedbackMessageError()
void FMyBlueprintItemDragDropAction::SetFeedbackMessageError (const FText & Message) protected
SetFeedbackMessageOK()
void FMyBlueprintItemDragDropAction::SetFeedbackMessageOK (const FText & Message) protected
Field Documentation
AnalyticCallback
FNodeCreationAnalytic FMyBlueprintItemDragDropAction::AnalyticCallback protected
Analytic delegate to track node creation.
Definition at line 63 of file MyBlueprintItemDragDropAction.h.
Referenced by FKismetVariableDragDropAction::New().
bAltDrag
bool FMyBlueprintItemDragDropAction::bAltDrag protected
Was alt held down at the start of drag.
Definition at line 61 of file MyBlueprintItemDragDropAction.h.
Referenced by SetAltDrag().
bControlDrag
bool FMyBlueprintItemDragDropAction::bControlDrag protected
Was ctrl held down at start of drag.
Definition at line 59 of file MyBlueprintItemDragDropAction.h.
Referenced by SetCtrlDrag().
The documentation for this class was generated from the following file:
MyBlueprintItemDragDropAction.h