Unreal Engine 5.6 C++ API: FLocItem Struct Reference
FLocItem Struct Reference
#include "InternationalizationManifest.h"
Public Member Functions
FLocItem ()
FLocItem (const FLocItem &Other)
Copy ctor.
FLocItem (FString InSourceText)
FLocItem (FString InSourceText, TSharedPtr< FLocMetadataObject > InMetadataObj)
bool IsExactMatch (const FLocItem &Other) const
Similar functionality to == operator but ensures everything matches(ex.
bool operator!= (const FLocItem &Other) const
bool operator< (const FLocItem &Other) const
FLocItem & operator= (const FLocItem &Other)
bool operator== (const FLocItem &Other) const
Data Fields
TSharedPtr< FLocMetadataObject > MetadataObj
FString Text
Detailed Description
Definition at line 56 of file InternationalizationManifest.h.
Constructor & Destructor Documentation
FLocItem() [1/4]
FLocItem::FLocItem () inline
Definition at line 59 of file InternationalizationManifest.h.
References MetadataObj, and Text.
Referenced by FLocItem(), IsExactMatch(), operator!=(), operator<(), operator=(), and operator==().
FLocItem() [2/4]
FLocItem::FLocItem (FString InSourceText) inline explicit
Definition at line 65 of file InternationalizationManifest.h.
References MetadataObj, MoveTemp(), and Text.
FLocItem() [3/4]
FLocItem::FLocItem (FString InSourceText, TSharedPtr< FLocMetadataObject > InMetadataObj) inline
Definition at line 71 of file InternationalizationManifest.h.
References MetadataObj, MoveTemp(), and Text.
FLocItem() [4/4]
FLocItem::FLocItem (const FLocItem & Other)
Copy ctor.
References FLocItem(), and Other.
Member Function Documentation
IsExactMatch()
bool FLocItem::IsExactMatch (const FLocItem & Other) const
Similar functionality to == operator but ensures everything matches(ex.
ignores COMPARISON_MODIFIER_PREFIX on metadata).
References FLocItem(), and Other.
operator!=()
bool FLocItem::operator!= (const FLocItem & Other) const inline
Definition at line 82 of file InternationalizationManifest.h.
References FLocItem(), and Other.
operator<()
bool FLocItem::operator< (const FLocItem & Other) const
References FLocItem(), and Other.
operator=()
FLocItem & FLocItem::operator= (const FLocItem & Other)
References FLocItem(), and Other.
operator==()
bool FLocItem::operator== (const FLocItem & Other) const
References FLocItem(), and Other.
Field Documentation
MetadataObj
TSharedPtr<FLocMetadataObject> FLocItem::MetadataObj
Definition at line 90 of file InternationalizationManifest.h.
Referenced by FLocItem(), FLocItem(), and FLocItem().
Text
FString FLocItem::Text
Definition at line 89 of file InternationalizationManifest.h.
Referenced by FLocItem(), FLocItem(), and FLocItem().
The documentation for this struct was generated from the following file:
InternationalizationManifest.h