Unreal Engine 5.6 C++ Documentation: FRootMotionSourceGroup Struct Reference
FRootMotionSourceGroup Struct Reference
Group of Root Motion Sources that are applied.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h>
Public Member Functions
FRootMotionSourceGroup ()
virtual ~FRootMotionSourceGroup ()
void CleanUpInvalidRootMotion (float DeltaTime, const ACharacter &Character, UCharacterMovementComponent &MoveComponent)
void PrepareRootMotion (float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &InMoveComponent, bool bForcePrepareAll=false)
Generates root motion by accumulating transforms through current root motion sources.
void AccumulateOverrideRootMotionVelocity (float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent, FVector &InOutVelocity) const
Helper function for accumulating override velocity into InOutVelocity.
void AccumulateAdditiveRootMotionVelocity (float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent, FVector &InOutVelocity) const
Helper function for accumulating additive velocity into InOutVelocity.
bool GetOverrideRootMotionRotation (float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent, FQuat &OutRotation) const
Get rotation output of current override root motion source, returns true if OutRotation was filled.
bool NeedsSimulatedSmoothing () const
Gets whether any active root motion source has been marked to need NetworkSmoothing as a SimulatedProxy.
void SetPendingRootMotionSourceMinStartTimes (float NewStartTime)
Sets the StartTime of all pending root motion sources to be at least this time, can be used on servers to match client-side start times.
void ApplyTimeStampReset (float DeltaTime)
Applies a reset to the start time for each root motion when the time stamp is reset.
bool HasOverrideVelocity () const
bool HasOverrideVelocityWithIgnoreZAccumulate () const
bool HasAdditiveVelocity () const
bool HasVelocity () const
bool HasActiveRootMotionSources () const
bool HasRootMotionToApply () const
uint16 ApplyRootMotionSource (TSharedPtr< FRootMotionSource > SourcePtr)
Apply a RootMotionSource to this Group.
TSharedPtr< FRootMotionSource > GetRootMotionSource (FName InstanceName)
Get a RootMotionSource from this Group by name.
TSharedPtr< FRootMotionSource > GetRootMotionSourceByID (uint16 RootMotionSourceID)
Get a RootMotionSource from this Group by ID.
void RemoveRootMotionSource (FName InstanceName)
Remove a RootMotionSource from this Group by name.
void RemoveRootMotionSourceByID (uint16 RootMotionSourceID)
Remove a RootMotionSource from this Group by ID.
void UpdateStateFrom (const FRootMotionSourceGroup &GroupToTakeStateFrom, bool bMarkForSimulatedCatchup=false)
Update contained Sources to state in matching sources from other group.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess, uint8 MaxNumRootMotionSourcesToSerialize=MAX_uint8)
Serialize the root motion sources and their states for this group.
void Clear ()
Clear the contents to return it to "empty".
void CullInvalidSources ()
Removes any Sources without a valid ID.
FRootMotionSourceGroup & operator= (const FRootMotionSourceGroup &Other)
Copy operator - deep copy so it can be used for archiving/saving off moves.
bool operator== (const FRootMotionSourceGroup &Other) const
Comparison operator - needs matching Sources along with identical states in those sources.
bool operator!= (const FRootMotionSourceGroup &Other) const
Comparison operator.
void AddStructReferencedObjects (FReferenceCollector &Collector) const
Exposes references to GC system.
Public Attributes
TArray< TSharedPtr< FRootMotionSource > > RootMotionSources
Root Motion Sources currently applied in this Group.
TArray< TSharedPtr< FRootMotionSource > > PendingAddRootMotionSources
Root Motion Sources to be added next frame.
uint8 bHasAdditiveSources:1
Whether this group has additive root motion sources.
uint8 bHasOverrideSources:1
Whether this group has override root motion sources.
uint8 bHasOverrideSourcesWithIgnoreZAccumulate:1
Whether this group has override root motion sources that have IgnoreZAccumulate flag.
uint8 bIsAdditiveVelocityApplied:1
True when we had additive velocity applied last tick, checked to know if we should restore LastPreAdditiveVelocity before a Velocity computation.
FRootMotionSourceSettings LastAccumulatedSettings
Aggregate Settings of the last group of accumulated sources.
FVector_NetQuantize10 LastPreAdditiveVelocity
Saved off pre-additive-applied Velocity, used for being able to reliably add/remove additive velocity from currently computed Velocity (otherwise we would be removing additive velocity that no longer exists, like if you run into a wall and your Velocity becomes 0 - subtracting the velocity that we added heading into the wall last tick would make you go backwards.
Protected Member Functions
void AccumulateRootMotionVelocity (ERootMotionAccumulateMode RootMotionType, float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent, FVector &InOutVelocity) const
Accumulates contributions for velocity into InOutVelocity for a given type of root motion from this group.
void AccumulateRootMotionVelocityFromSource (const FRootMotionSource &RootMotionSource, float DeltaTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent, FVector &InOutVelocity) const
Accumulates contributions for velocity into InOutVelocity for a given type of root motion from this group.
Static Protected Member Functions
static void NetSerializeRMSArray (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess, TArray< TSharedPtr< FRootMotionSource > > &RootMotionSourceArray, uint8 MaxNumRootMotionSourcesToSerialize=MAX_uint8)
Helper function for serializing array of root motion sources.
Detailed Description
Group of Root Motion Sources that are applied.
Definition at line 751 of file RootMotionSource.h.
Constructor & Destructor Documentation
FRootMotionSourceGroup()
FRootMotionSourceGroup::FRootMotionSourceGroup ()
References FRootMotionSourceGroup().
~FRootMotionSourceGroup()
virtual FRootMotionSourceGroup::~FRootMotionSourceGroup () inline virtual
Definition at line 758 of file RootMotionSource.h.
References FRootMotionSourceGroup().
Member Function Documentation
AccumulateAdditiveRootMotionVelocity()
void FRootMotionSourceGroup::AccumulateAdditiveRootMotionVelocity (float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent, FVector & InOutVelocity) const
Helper function for accumulating additive velocity into InOutVelocity.
References AccumulateAdditiveRootMotionVelocity().
AccumulateOverrideRootMotionVelocity()
void FRootMotionSourceGroup::AccumulateOverrideRootMotionVelocity (float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent, FVector & InOutVelocity) const
Helper function for accumulating override velocity into InOutVelocity.
References AccumulateOverrideRootMotionVelocity().
AccumulateRootMotionVelocity()
void FRootMotionSourceGroup::AccumulateRootMotionVelocity (ERootMotionAccumulateMode RootMotionType, float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent, FVector & InOutVelocity) const protected
Accumulates contributions for velocity into InOutVelocity for a given type of root motion from this group.
References AccumulateRootMotionVelocity(), and ERootMotionAccumulateMode.
AccumulateRootMotionVelocityFromSource()
void FRootMotionSourceGroup::AccumulateRootMotionVelocityFromSource (const FRootMotionSource & RootMotionSource, float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent, FVector & InOutVelocity) const protected
Accumulates contributions for velocity into InOutVelocity for a given type of root motion from this group.
References AccumulateRootMotionVelocityFromSource().
AddStructReferencedObjects()
void FRootMotionSourceGroup::AddStructReferencedObjects (FReferenceCollector & Collector) const
Exposes references to GC system.
References AddStructReferencedObjects().
ApplyRootMotionSource()
uint16 FRootMotionSourceGroup::ApplyRootMotionSource (TSharedPtr< FRootMotionSource > SourcePtr)
Apply a RootMotionSource to this Group.
Returns
LocalID for this RMS
References ApplyRootMotionSource().
ApplyTimeStampReset()
void FRootMotionSourceGroup::ApplyTimeStampReset (float DeltaTime)
Applies a reset to the start time for each root motion when the time stamp is reset.
References ApplyTimeStampReset().
CleanUpInvalidRootMotion()
void FRootMotionSourceGroup::CleanUpInvalidRootMotion (float DeltaTime, const ACharacter & Character, UCharacterMovementComponent & MoveComponent)
References CleanUpInvalidRootMotion().
Clear()
void FRootMotionSourceGroup::Clear ()
Clear the contents to return it to "empty".
References Clear().
CullInvalidSources()
void FRootMotionSourceGroup::CullInvalidSources ()
Removes any Sources without a valid ID.
References CullInvalidSources().
GetOverrideRootMotionRotation()
bool FRootMotionSourceGroup::GetOverrideRootMotionRotation (float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent, FQuat & OutRotation) const
Get rotation output of current override root motion source, returns true if OutRotation was filled.
References GetOverrideRootMotionRotation().
GetRootMotionSource()
TSharedPtr< FRootMotionSource > FRootMotionSourceGroup::GetRootMotionSource (FName InstanceName)
Get a RootMotionSource from this Group by name.
References GetRootMotionSource().
GetRootMotionSourceByID()
TSharedPtr< FRootMotionSource > FRootMotionSourceGroup::GetRootMotionSourceByID (uint16 RootMotionSourceID)
Get a RootMotionSource from this Group by ID.
References GetRootMotionSourceByID().
HasActiveRootMotionSources()
bool FRootMotionSourceGroup::HasActiveRootMotionSources () const
Returns
true if we have Root Motion from any source to use in PerformMovement() physics.
References HasActiveRootMotionSources().
HasAdditiveVelocity()
bool FRootMotionSourceGroup::HasAdditiveVelocity () const
Returns
true if any axis of velocity has additive velocity applied by root motion sources
References HasAdditiveVelocity().
HasOverrideVelocity()
bool FRootMotionSourceGroup::HasOverrideVelocity () const
Returns
true if Velocity will be overridden by root motion sources, meaning we can skip all normal movement-based velocity calculations
References HasOverrideVelocity().
HasOverrideVelocityWithIgnoreZAccumulate()
bool FRootMotionSourceGroup::HasOverrideVelocityWithIgnoreZAccumulate () const
Returns
true if Velocity will be overridden by root motion sources that do not affect Z velocity (matching animation root motion behavior)
References HasOverrideVelocityWithIgnoreZAccumulate().
HasRootMotionToApply()
bool FRootMotionSourceGroup::HasRootMotionToApply () const
Returns
true if we have Root Motion accumulated from sources to use in PerformMovement() physics. Not valid outside of the scope of that function. Since RootMotion is extracted and used in it.
References HasRootMotionToApply().
HasVelocity()
bool FRootMotionSourceGroup::HasVelocity () const
Returns
true if any axis of velocity is modified by root motion sources
References HasVelocity().
NeedsSimulatedSmoothing()
bool FRootMotionSourceGroup::NeedsSimulatedSmoothing () const
Gets whether any active root motion source has been marked to need NetworkSmoothing as a SimulatedProxy.
References NeedsSimulatedSmoothing().
NetSerialize()
bool FRootMotionSourceGroup::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess, uint8 MaxNumRootMotionSourcesToSerialize = MAX_uint8)
Serialize the root motion sources and their states for this group.
References NetSerialize().
NetSerializeRMSArray()
void FRootMotionSourceGroup::NetSerializeRMSArray (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess, TArray< TSharedPtr< FRootMotionSource > > & RootMotionSourceArray, uint8 MaxNumRootMotionSourcesToSerialize = MAX_uint8) static protected
Helper function for serializing array of root motion sources.
References NetSerializeRMSArray().
operator!=()
bool FRootMotionSourceGroup::operator!= (const FRootMotionSourceGroup & Other) const
Comparison operator.
References FRootMotionSourceGroup().
operator=()
FRootMotionSourceGroup & FRootMotionSourceGroup::operator= (const FRootMotionSourceGroup & Other)
Copy operator - deep copy so it can be used for archiving/saving off moves.
References FRootMotionSourceGroup().
operator==()
bool FRootMotionSourceGroup::operator== (const FRootMotionSourceGroup & Other) const
Comparison operator - needs matching Sources along with identical states in those sources.
References FRootMotionSourceGroup().
PrepareRootMotion()
void FRootMotionSourceGroup::PrepareRootMotion (float DeltaTime, const ACharacter & Character, const UCharacterMovementComponent & InMoveComponent, bool bForcePrepareAll = false)
Generates root motion by accumulating transforms through current root motion sources.
Parameters
bForcePrepareAll - Used during "live" PerformMovements() to ensure all sources get prepared Needed due to SavedMove playback/server correction only applying corrections to Sources that need updating, so in that case we only Prepare those that need it.
References PrepareRootMotion().
RemoveRootMotionSource()
void FRootMotionSourceGroup::RemoveRootMotionSource (FName InstanceName)
Remove a RootMotionSource from this Group by name.
References RemoveRootMotionSource().
RemoveRootMotionSourceByID()
void FRootMotionSourceGroup::RemoveRootMotionSourceByID (uint16 RootMotionSourceID)
Remove a RootMotionSource from this Group by ID.
References RemoveRootMotionSourceByID().
SetPendingRootMotionSourceMinStartTimes()
void FRootMotionSourceGroup::SetPendingRootMotionSourceMinStartTimes (float NewStartTime)
Sets the StartTime of all pending root motion sources to be at least this time, can be used on servers to match client-side start times.
References SetPendingRootMotionSourceMinStartTimes().
UpdateStateFrom()
void FRootMotionSourceGroup::UpdateStateFrom (const FRootMotionSourceGroup & GroupToTakeStateFrom, bool bMarkForSimulatedCatchup = false)
Update contained Sources to state in matching sources from other group.
Used for correcting root motion state when receiving authoritative state from server.
Parameters
GroupToTakeStateFrom the Authoritative Group to take state from
bMarkForSimulatedCatchup marks Sources as needing to return to their current Time on next Prepare
Returns
whether it successfully updated state
References FRootMotionSourceGroup(), and UpdateStateFrom().
Member Data Documentation
bHasAdditiveSources
uint8 FRootMotionSourceGroup::bHasAdditiveSources
Whether this group has additive root motion sources.
Definition at line 770 of file RootMotionSource.h.
bHasOverrideSources
uint8 FRootMotionSourceGroup::bHasOverrideSources
Whether this group has override root motion sources.
Definition at line 776 of file RootMotionSource.h.
bHasOverrideSourcesWithIgnoreZAccumulate
uint8 FRootMotionSourceGroup::bHasOverrideSourcesWithIgnoreZAccumulate
Whether this group has override root motion sources that have IgnoreZAccumulate flag.
Definition at line 782 of file RootMotionSource.h.
bIsAdditiveVelocityApplied
uint8 FRootMotionSourceGroup::bIsAdditiveVelocityApplied
True when we had additive velocity applied last tick, checked to know if we should restore LastPreAdditiveVelocity before a Velocity computation.
Definition at line 787 of file RootMotionSource.h.
LastAccumulatedSettings
FRootMotionSourceSettings FRootMotionSourceGroup::LastAccumulatedSettings
Aggregate Settings of the last group of accumulated sources.
Definition at line 791 of file RootMotionSource.h.
LastPreAdditiveVelocity
FVector_NetQuantize10 FRootMotionSourceGroup::LastPreAdditiveVelocity
Saved off pre-additive-applied Velocity, used for being able to reliably add/remove additive velocity from currently computed Velocity (otherwise we would be removing additive velocity that no longer exists, like if you run into a wall and your Velocity becomes 0 - subtracting the velocity that we added heading into the wall last tick would make you go backwards.
With this method we override that resulting Velocity due to obstructions
Definition at line 799 of file RootMotionSource.h.
PendingAddRootMotionSources
TArray< TSharedPtr<FRootMotionSource> > FRootMotionSourceGroup::PendingAddRootMotionSources
Root Motion Sources to be added next frame.
Definition at line 764 of file RootMotionSource.h.
RootMotionSources
TArray< TSharedPtr<FRootMotionSource> > FRootMotionSourceGroup::RootMotionSources
Root Motion Sources currently applied in this Group.
Definition at line 761 of file RootMotionSource.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h