Unreal Engine 5.6 C++ API: MemoryLayout.h File Reference
MemoryLayout.h File Reference
#include "Concepts/StaticClassProvider.h"
#include "Concepts/StaticStructProvider.h"
#include "Containers/EnumAsByte.h"
#include "Containers/StringFwd.h"
#include "HAL/UnrealMemory.h"
#include "Misc/DelayedAutoRegister.h"
#include "Templates/EnableIf.h"
#include "Templates/IsAbstract.h"
#include "Templates/IsPolymorphic.h"
#include "Templates/Models.h"
#include "Templates/UnrealTemplate.h"
Data Structures
struct CProvidesDefaultUObject
Access to a global default object is required in order to patch vtables Normally this can be provided by a default-constructed object.
struct CTypeLayout
struct FFieldLayoutDesc
struct FMemoryToStringContext
struct FPlatformTypeLayoutParameters
struct FPlatformTypeLayoutParameters::InternalLinkType< Counter >
struct FPlatformTypeLayoutParameters::InternalLinkType< __COUNTER__ - CounterBase >
struct FRegisterTypeLayoutDesc
struct FTypeLayoutDesc
struct TGetBaseTypeHelper< T >
struct TGetDefaultObjectHelper< T, InterfaceType >
struct TGetDefaultObjectHelper< T, ETypeLayoutInterface::Virtual >
struct TGetFreezeImageFieldHelper< T, bProvidesStaticStruct >
struct TGetFreezeImageHelper< T, bUsePropertyFreezing >
struct TGetTypeLayoutHelper< T >
struct THasCustomDefaultObject< T >
struct THasTypeLayout< T >
struct TInitializeBaseHelper< T, BaseType >
struct TInitializeBaseHelper< T, void >
struct TStaticGetTypeLayoutHelper< T >
struct TUsePropertyFreezing< T >
struct TValidateInterfaceHelper< T, ETypeLayoutInterface::Abstract >
struct TValidateInterfaceHelper< T, ETypeLayoutInterface::NonVirtual >
struct TValidateInterfaceHelper< T, ETypeLayoutInterface::Virtual >
Namespaces
namespace EFieldLayoutFlags
namespace ETypeLayoutInterface
namespace Freeze
Macros
#define ALIAS_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, T, Alias)
#define ALIAS_TYPE_LAYOUT(Type, Alias)
#define DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT(TemplatePrefix, T, RequiredAPI)
#define DECLARE_EXPORTED_TYPE_LAYOUT(T, RequiredAPI, Interface)
#define DECLARE_EXPORTED_TYPE_LAYOUT_EXPLICIT_BASES(T, RequiredAPI, Interface, ...)
#define DECLARE_INLINE_TYPE_LAYOUT(T, Interface)
#define DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES(T, Interface, ...)
#define DECLARE_INTRINSIC_TYPE_LAYOUT(T)
#define DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT(TemplatePrefix, T)
#define DECLARE_TYPE_LAYOUT(T, Interface)
#define DECLARE_TYPE_LAYOUT_EXPLICIT_BASES(T, Interface, ...)
#define IMPLEMENT_ABSTRACT_TYPE_LAYOUT(T)
#define IMPLEMENT_EXPORTED_INTRINSIC_TYPE_LAYOUT(T)
#define IMPLEMENT_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, T)
#define IMPLEMENT_TYPE_LAYOUT(T)
#define IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, T)
#define INTERNAL_DECLARE_INLINE_TYPE_LAYOUT(T, InInterface)
#define INTERNAL_DECLARE_LAYOUT_BASE(T)
#define INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES(T, ...)
#define INTERNAL_DECLARE_TYPE_LAYOUT(T, InInterface, RequiredAPI)
#define INTERNAL_DECLARE_TYPE_LAYOUT_COMMON(T, InInterface)
#define INTERNAL_IMPLEMENT_TYPE_LAYOUT_COMMON(TemplatePrefix, T)
#define INTERNAL_LAYOUT_FIELD(T, InName, InOffset, InFlags, InNumArray, InBitFieldSize, Counter)
#define INTERNAL_LAYOUT_FIELD_WITH_WRITER(T, InName, InFunc, Counter)
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL(Type)
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Abstract { return FTypeLayoutDesc::GetInvalidTypeLayout(); }
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_NonVirtual { return StaticGetTypeLayout(); }
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Virtual { return StaticGetTypeLayout(); }
#define INTERNAL_LAYOUT_INTERFACE_PREFIX(Type)
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_Abstract(...)
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_NonVirtual(...)
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_Virtual(...)
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX(Type)
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_Abstract { return FTypeLayoutDesc::GetInvalidTypeLayout(); }
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_NonVirtual ;
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_Virtual ;
#define INTERNAL_LAYOUT_TOSTRING(Func, Counter)
#define INTERNAL_LAYOUT_WRITE_MEMORY_IMAGE(Func, Counter)
#define INTERNAL_REGISTER_TYPE_LAYOUT(T)
#define LAYOUT_ARRAY(T, Name, NumArray, ...)
#define LAYOUT_ARRAY_EDITORONLY(T, Name, NumArray, ...)
#define LAYOUT_BITFIELD(T, Name, BitFieldSize, ...)
#define LAYOUT_BITFIELD_EDITORONLY(T, Name, BitFieldSize, ...)
#define LAYOUT_FIELD(T, Name, ...)
#define LAYOUT_FIELD_EDITORONLY(T, Name, ...)
#define LAYOUT_FIELD_INITIALIZED(T, Name, Value, ...)
#define LAYOUT_FIELD_WITH_WRITER(T, Name, Func)
#define LAYOUT_MUTABLE_BITFIELD(T, Name, BitFieldSize, ...)
#define LAYOUT_MUTABLE_FIELD(T, Name, ...)
#define LAYOUT_MUTABLE_FIELD_INITIALIZED(T, Name, Value, ...)
#define LAYOUT_MUTABLE_FIELD_WITH_WRITER(T, Name, Func)
#define LAYOUT_TOSTRING(Func)
#define LAYOUT_WRITE_MEMORY_IMAGE(Func)
#define REGISTER_INLINE_TYPE_LAYOUT(T)
#define UE_DECLARE_INTERNAL_LINK_BASE(T)
Certain compilers don't accept full explicit template specializations inside class declarations.
#define UE_DECLARE_INTERNAL_LINK_SPECIALIZATION(T, Counter)
#define UE_STATIC_ONLY(T)
Enumerations
enum EFieldLayoutFlags::Type : uint8 {
EFieldLayoutFlags::None = 0u , EFieldLayoutFlags::WithEditorOnly = (1u << 0) , EFieldLayoutFlags::WithRayTracing = (1u << 1) , EFieldLayoutFlags::Transient = (1u << 2) ,
EFieldLayoutFlags::UseInstanceWithNoProperty = (1u << 3)
}
enum ETypeLayoutInterface::Type : uint8 { ETypeLayoutInterface::NonVirtual , ETypeLayoutInterface::Virtual , ETypeLayoutInterface::Abstract }
Functions
uint32 Freeze::AppendHash (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 Freeze::AppendHashForNameAndSize (const TCHAR *Name, uint32 Size, FSHA1 &Hasher)
uint32 Freeze::AppendHashPair (const FTypeLayoutDesc &KeyTypeDesc, const FTypeLayoutDesc &ValueTypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 Freeze::DefaultAppendHash (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 Freeze::DefaultGetTargetAlignment (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
void Freeze::DefaultToString (const void *Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
uint32 Freeze::DefaultUnfrozenCopy (const FMemoryUnfreezeContent &Context, const void *Object, const FTypeLayoutDesc &TypeDesc, void *OutDst)
void Freeze::DefaultWriteMemoryImage (FMemoryImageWriter &Writer, const void *Object, const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
void Freeze::DefaultWriteMemoryImageField (FMemoryImageWriter &Writer, const void *Object, const void *FieldObject, const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
template<typename T>
void DeleteObjectFromLayout (T *Object, const FPointerTableBase *PtrTable=nullptr, bool bIsFrozen=false)
template<typename T>
FORCEINLINE void Freeze::DestroyObject (T *Object, const FPointerTableBase *PtrTable, bool bIsFrozen)
void Freeze::ExtractBitFieldValue (const void *Value, uint32 SrcBitOffset, uint32 DestBitOffset, uint32 NumBits, uint64 &InOutValue)
uint8 Freeze::FindFieldNameLength (const TCHAR *Name)
template<typename T, typename Base>
uint32 GetBaseOffset ()
template<typename T>
const T * GetDefault ()
uint32 Freeze::GetTargetAlignment (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T>
const FTypeLayoutDesc & GetTypeLayoutDesc (const FPointerTableBase *, const T &Object)
FSHAHash Freeze::HashLayout (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 Freeze::HashLayout (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHAHash &OutHash)
uint32 Freeze::HashLayouts (const TArray< const FTypeLayoutDesc * > &TypeLayouts, const FPlatformTypeLayoutParameters &LayoutParams, FSHAHash &OutHash)
bool ETypeLayoutInterface::HasVTable (Type InType)
bool Freeze::IncludeField (const FFieldLayoutDesc *FieldDesc, const FPlatformTypeLayoutParameters &LayoutParams)
void InternalDeleteObjectFromLayout (void *Object, const FTypeLayoutDesc &TypeDesc, const FPointerTableBase *PtrTable, bool bIsFrozen)
template<typename T>
const T * InternalGetDefaultObject ()
template<typename T, typename BaseType>
static void InternalInitializeBaseHelper (FTypeLayoutDesc &TypeDesc)
template<typename T>
static FORCEINLINE void InternalInitializeBasesHelper (FTypeLayoutDesc &TypeDesc)
template<typename T, typename BaseType, typename ... RemainingBaseTypes>
static void InternalInitializeBasesHelper (FTypeLayoutDesc &TypeDesc)
template<typename T>
FORCEINLINE uint32 Freeze::IntrinsicAppendHash (const T *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 Freeze::IntrinsicAppendHash (void *const *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T>
FORCEINLINE uint32 Freeze::IntrinsicGetTargetAlignment (const T *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 Freeze::IntrinsicGetTargetAlignment (void *const *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
void Freeze::IntrinsicToString (char Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (char16_t Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T>
void Freeze::IntrinsicToString (const T &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (double Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (float Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (int Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (int8 Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (long long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (short Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (unsigned char Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (unsigned int Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (unsigned long long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (unsigned long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (unsigned short Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (void *Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void Freeze::IntrinsicToString (wchar_t Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T>
FORCEINLINE uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const T &Object, void *OutDst)
template<typename T>
FORCEINLINE void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const T &Object, const FTypeLayoutDesc &TypeDesc)
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const void *Object, uint32 Size)
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, void *, const FTypeLayoutDesc &)
FORCEINLINE Type EFieldLayoutFlags::MakeFlags (uint32 Flags=None)
FORCEINLINE Type EFieldLayoutFlags::MakeFlagsEditorOnly (uint32 Flags=None)
FORCEINLINE Type EFieldLayoutFlags::MakeFlagsRayTracing (uint32 Flags=None)
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (template< typename T >) struct THasTypeLayout< PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TEnumAsByte< T >)>
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (template<>) struct THasTypeLayout< PREPROCESSOR_REMOVE_OPTIONAL_PARENS(char)>
template<typename T>
const FTypeLayoutDesc & StaticGetTypeLayoutDesc ()
Macro Definition Documentation
ALIAS_TEMPLATE_TYPE_LAYOUT
#define ALIAS_TEMPLATE_TYPE_LAYOUT (TemplatePrefix, T, Alias)
Value:
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) struct TStaticGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)> : public TStaticGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(Alias)> { UE_STATIC_ONLY(TStaticGetTypeLayoutHelper); }; \
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) struct TGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)> : public TGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(Alias)> { UE_STATIC_ONLY(TGetTypeLayoutHelper); }
Definition at line 762 of file MemoryLayout.h.
ALIAS_TYPE_LAYOUT
#define ALIAS_TYPE_LAYOUT (Type, Alias)
Value:
    static_assert(sizeof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(Type)) == sizeof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(Alias)), "Using a type alias but the sizes don't match!"); \
    ALIAS_TEMPLATE_TYPE_LAYOUT(template<>, Type, Alias)
Definition at line 766 of file MemoryLayout.h.
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT
#define DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT (TemplatePrefix, T, RequiredAPI)
Value:
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) struct THasTypeLayout<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)> { UE_STATIC_ONLY(THasTypeLayout); static const bool Value = true; }; \
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) struct TStaticGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)> { \
        UE_STATIC_ONLY(TStaticGetTypeLayoutHelper); \
        static void CallWriteMemoryImage(FMemoryImageWriter& Writer, const void* Object, const FTypeLayoutDesc& TypeDesc, const FTypeLayoutDesc& DerivedTypeDesc); \
        static uint32 CallUnfrozenCopy(const FMemoryUnfreezeContent& Context, const void* Object, const FTypeLayoutDesc& TypeDesc, void* OutDst); \
        static uint32 CallAppendHash(const FTypeLayoutDesc& TypeDesc, const FPlatformTypeLayoutParameters& LayoutParams, FSHA1& Hasher); \
        static uint32 CallGetTargetAlignment(const FTypeLayoutDesc& TypeDesc, const FPlatformTypeLayoutParameters& LayoutParams); \
        static void CallToString(const void* Object, const FTypeLayoutDesc& TypeDesc, const FPlatformTypeLayoutParameters& LayoutParams, FMemoryToStringContext& OutContext); \
        static void CallDestroy(void* Object, const FTypeLayoutDesc&, const FPointerTableBase* PtrTable, bool bIsFrozen); \
        RequiredAPI static const FTypeLayoutDesc& Do(); }; \
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) struct TGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)> { \
        UE_STATIC_ONLY(TGetTypeLayoutHelper); \
        static const FTypeLayoutDesc& Do(const PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)&) { return TStaticGetTypeLayoutHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>::Do(); }}
Definition at line 706 of file MemoryLayout.h.
DECLARE_EXPORTED_TYPE_LAYOUT
#define DECLARE_EXPORTED_TYPE_LAYOUT (T, RequiredAPI, Interface)
Value:
INTERNAL_DECLARE_LAYOUT_BASE(T); INTERNAL_DECLARE_TYPE_LAYOUT(T, Interface, RequiredAPI)
Definition at line 559 of file MemoryLayout.h.
DECLARE_EXPORTED_TYPE_LAYOUT_EXPLICIT_BASES
#define DECLARE_EXPORTED_TYPE_LAYOUT_EXPLICIT_BASES (T, RequiredAPI, Interface, ...)
Value:
INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES(T, __VA_ARGS__); INTERNAL_DECLARE_TYPE_LAYOUT(T, Interface, RequiredAPI)
Definition at line 563 of file MemoryLayout.h.
DECLARE_INLINE_TYPE_LAYOUT
#define DECLARE_INLINE_TYPE_LAYOUT (T, Interface)
Value:
INTERNAL_DECLARE_LAYOUT_BASE(T); INTERNAL_DECLARE_INLINE_TYPE_LAYOUT(T, Interface)
Definition at line 558 of file MemoryLayout.h.
DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES
#define DECLARE_INLINE_TYPE_LAYOUT_EXPLICIT_BASES (T, Interface, ...)
Value:
INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES(T, __VA_ARGS__); INTERNAL_DECLARE_INLINE_TYPE_LAYOUT(T, Interface)
Definition at line 562 of file MemoryLayout.h.
DECLARE_INTRINSIC_TYPE_LAYOUT
#define DECLARE_INTRINSIC_TYPE_LAYOUT (T)
Value:
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT(template<>, T)
Definition at line 760 of file MemoryLayout.h.
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT
#define DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (TemplatePrefix, T)
Definition at line 661 of file MemoryLayout.h.
DECLARE_TYPE_LAYOUT
#define DECLARE_TYPE_LAYOUT (T, Interface)
Value:
INTERNAL_DECLARE_LAYOUT_BASE(T); INTERNAL_DECLARE_TYPE_LAYOUT(T, Interface, PREPROCESSOR_NOTHING)
Definition at line 557 of file MemoryLayout.h.
DECLARE_TYPE_LAYOUT_EXPLICIT_BASES
#define DECLARE_TYPE_LAYOUT_EXPLICIT_BASES (T, Interface, ...)
Value:
INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES(T, __VA_ARGS__); INTERNAL_DECLARE_TYPE_LAYOUT(T, Interface, PREPROCESSOR_NOTHING)
Definition at line 561 of file MemoryLayout.h.
IMPLEMENT_ABSTRACT_TYPE_LAYOUT
#define IMPLEMENT_ABSTRACT_TYPE_LAYOUT (T)
Value:
    INTERNAL_IMPLEMENT_TYPE_LAYOUT_COMMON(, T); \
    INTERNAL_REGISTER_TYPE_LAYOUT(T)
Definition at line 606 of file MemoryLayout.h.
IMPLEMENT_EXPORTED_INTRINSIC_TYPE_LAYOUT
#define IMPLEMENT_EXPORTED_INTRINSIC_TYPE_LAYOUT (T)
Definition at line 721 of file MemoryLayout.h.
IMPLEMENT_TEMPLATE_TYPE_LAYOUT
#define IMPLEMENT_TEMPLATE_TYPE_LAYOUT (TemplatePrefix, T)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, T); \
    INTERNAL_REGISTER_TYPE_LAYOUT(T)
Definition at line 600 of file MemoryLayout.h.
IMPLEMENT_TYPE_LAYOUT
#define IMPLEMENT_TYPE_LAYOUT (T)
Value:
IMPLEMENT_TEMPLATE_TYPE_LAYOUT(, T)
Definition at line 604 of file MemoryLayout.h.
IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT
#define IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT (TemplatePrefix, T)
Value:
    INTERNAL_IMPLEMENT_TYPE_LAYOUT_COMMON(TemplatePrefix, T); \
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) const FTypeLayoutDesc& PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)::GetTypeLayout() const { return StaticGetTypeLayout(); }
Definition at line 596 of file MemoryLayout.h.
INTERNAL_DECLARE_INLINE_TYPE_LAYOUT
#define INTERNAL_DECLARE_INLINE_TYPE_LAYOUT (T, InInterface)
Value:
    private: static void InternalDestroy(void* Object, const FTypeLayoutDesc&, const FPointerTableBase* PtrTable, bool bIsFrozen) { \
        Freeze::DestroyObject(static_cast<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)*>(Object), PtrTable, bIsFrozen); \
    } \
    public: static FTypeLayoutDesc& StaticGetTypeLayout() { \
        static_assert(TValidateInterfaceHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T), ETypeLayoutInterface::InInterface>::Value, #InInterface " is invalid interface for " #T); \
        alignas(FTypeLayoutDesc) static uint8 TypeBuffer[sizeof(FTypeLayoutDesc)] = { 0 }; \
        FTypeLayoutDesc& TypeDesc = *(FTypeLayoutDesc*)TypeBuffer; \
        if (!TypeDesc.IsInitialized) { \
            TypeDesc.IsInitialized = true; \
            TypeDesc.Name = TEXT(#T); \
            TypeDesc.WriteFrozenMemoryImageFunc = TGetFreezeImageHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>::Do(); \
            TypeDesc.UnfrozenCopyFunc = &Freeze::DefaultUnfrozenCopy; \
            TypeDesc.AppendHashFunc = &Freeze::DefaultAppendHash; \
            TypeDesc.GetTargetAlignmentFunc = &Freeze::DefaultGetTargetAlignment; \
            TypeDesc.ToStringFunc = &Freeze::DefaultToString; \
            TypeDesc.DestroyFunc = &InternalDestroy; \
            TypeDesc.Size = sizeof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)); \
            TypeDesc.Alignment = alignof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)); \
            TypeDesc.Interface = ETypeLayoutInterface::InInterface; \
            TypeDesc.SizeFromFields = ~0u; \
            TypeDesc.GetDefaultObjectFunc = &TGetDefaultObjectHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T), ETypeLayoutInterface::InInterface>::Do; \
            InternalLinkType<1>::Initialize(TypeDesc); \
            InternalInitializeBases<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>(TypeDesc); \
            FTypeLayoutDesc::Initialize(TypeDesc); \
        } \
        return TypeDesc; } \
    public: INTERNAL_LAYOUT_INTERFACE_PREFIX(InInterface)(PREPROCESSOR_NOTHING) const FTypeLayoutDesc& GetTypeLayout() const INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL(InInterface) \
    INTERNAL_DECLARE_TYPE_LAYOUT_COMMON(T, InInterface)
Definition at line 514 of file MemoryLayout.h.
INTERNAL_DECLARE_LAYOUT_BASE
#define INTERNAL_DECLARE_LAYOUT_BASE (T)
Value:
    private: using InternalBaseType = typename TGetBaseTypeHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>::Type; \
    template<typename InternalType> static void InternalInitializeBases(FTypeLayoutDesc& TypeDesc) { TInitializeBaseHelper<InternalType, InternalBaseType>::Initialize(TypeDesc); }
Definition at line 550 of file MemoryLayout.h.
INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES
#define INTERNAL_DECLARE_LAYOUT_EXPLICIT_BASES (T, ...)
Value:
    template<typename InternalType> static void InternalInitializeBases(FTypeLayoutDesc& TypeDesc) { InternalInitializeBasesHelper<InternalType, __VA_ARGS__>(TypeDesc); }
Definition at line 554 of file MemoryLayout.h.
INTERNAL_DECLARE_TYPE_LAYOUT
#define INTERNAL_DECLARE_TYPE_LAYOUT (T, InInterface, RequiredAPI)
Value:
    private: static void InternalDestroy(void* Object, const FTypeLayoutDesc&, const FPointerTableBase* PtrTable, bool bIsFrozen); \
    public: RequiredAPI static FTypeLayoutDesc& StaticGetTypeLayout(); \
    public: INTERNAL_LAYOUT_INTERFACE_PREFIX(InInterface)(RequiredAPI) const FTypeLayoutDesc& GetTypeLayout() const INTERNAL_LAYOUT_INTERFACE_SUFFIX(InInterface) \
    INTERNAL_DECLARE_TYPE_LAYOUT_COMMON(T, InInterface)
Definition at line 544 of file MemoryLayout.h.
INTERNAL_DECLARE_TYPE_LAYOUT_COMMON
#define INTERNAL_DECLARE_TYPE_LAYOUT_COMMON (T, InInterface)
Value:
    static constexpr int CounterBase = __COUNTER__; \
    public: using DerivedType = PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T); \
    static constexpr ETypeLayoutInterface::Type InterfaceType = ETypeLayoutInterface::InInterface; \
    UE_DECLARE_INTERNAL_LINK_BASE(InternalLinkType) { UE_STATIC_ONLY(InternalLinkType); static FORCEINLINE void Initialize(FTypeLayoutDesc& TypeDesc) {} }
Definition at line 508 of file MemoryLayout.h.
INTERNAL_IMPLEMENT_TYPE_LAYOUT_COMMON
#define INTERNAL_IMPLEMENT_TYPE_LAYOUT_COMMON (TemplatePrefix, T)
Value:
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) void PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)::InternalDestroy(void* Object, const FTypeLayoutDesc&, const FPointerTableBase* PtrTable, bool bIsFrozen) { \
        Freeze::DestroyObject(static_cast<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)*>(Object), PtrTable, bIsFrozen); \
    } \
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) FTypeLayoutDesc& PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)::StaticGetTypeLayout() { \
        static_assert(TValidateInterfaceHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T), InterfaceType>::Value, "Invalid interface for " #T); \
        alignas(FTypeLayoutDesc) static uint8 TypeBuffer[sizeof(FTypeLayoutDesc)] = { 0 }; \
        FTypeLayoutDesc& TypeDesc = *(FTypeLayoutDesc*)TypeBuffer; \
        if (!TypeDesc.IsInitialized) { \
            TypeDesc.IsInitialized = true; \
            TypeDesc.Name = TEXT(#T); \
            TypeDesc.WriteFrozenMemoryImageFunc = TGetFreezeImageHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>::Do(); \
            TypeDesc.UnfrozenCopyFunc = &Freeze::DefaultUnfrozenCopy; \
            TypeDesc.AppendHashFunc = &Freeze::DefaultAppendHash; \
            TypeDesc.GetTargetAlignmentFunc = &Freeze::DefaultGetTargetAlignment; \
            TypeDesc.ToStringFunc = &Freeze::DefaultToString; \
            TypeDesc.DestroyFunc = &InternalDestroy; \
            TypeDesc.Size = sizeof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)); \
            TypeDesc.Alignment = alignof(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)); \
            TypeDesc.Interface = InterfaceType; \
            TypeDesc.SizeFromFields = ~0u; \
            TypeDesc.GetDefaultObjectFunc = &TGetDefaultObjectHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T), InterfaceType>::Do; \
            InternalLinkType<1>::Initialize(TypeDesc); \
            InternalInitializeBases<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>(TypeDesc); \
            FTypeLayoutDesc::Initialize(TypeDesc); \
        } \
        return TypeDesc; }
Definition at line 565 of file MemoryLayout.h.
INTERNAL_LAYOUT_FIELD
#define INTERNAL_LAYOUT_FIELD (T, InName, InOffset, InFlags, InNumArray, InBitFieldSize, Counter)
Value:
    PRAGMA_DISABLE_DEPRECATION_WARNINGS \
    UE_DECLARE_INTERNAL_LINK_SPECIALIZATION(InternalLinkType, Counter - CounterBase) { \
        UE_STATIC_ONLY(InternalLinkType); \
        static void Initialize(FTypeLayoutDesc& TypeDesc) { \
            InternalLinkType<Counter - CounterBase + 1>::Initialize(TypeDesc); \
            alignas(FFieldLayoutDesc) static uint8 FieldBuffer[sizeof(FFieldLayoutDesc)] = { 0 }; \
            FFieldLayoutDesc& FieldDesc = *(FFieldLayoutDesc*)FieldBuffer; \
            FieldDesc.Name = TEXT(#InName); \
            FieldDesc.UFieldNameLength = Freeze::FindFieldNameLength(FieldDesc.Name); \
            FieldDesc.Type = &StaticGetTypeLayoutDesc<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>(); \
            FieldDesc.WriteFrozenMemoryImageFunc = TGetFreezeImageFieldHelper<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>::Do(); \
            FieldDesc.Offset = InOffset; \
            FieldDesc.NumArray = InNumArray; \
            FieldDesc.Flags = InFlags; \
            FieldDesc.BitFieldSize = InBitFieldSize; \
            FieldDesc.Next = TypeDesc.Fields; \
            TypeDesc.Fields = &FieldDesc; \
        } \
    }; \
    PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 401 of file MemoryLayout.h.
INTERNAL_LAYOUT_FIELD_WITH_WRITER
#define INTERNAL_LAYOUT_FIELD_WITH_WRITER (T, InName, InFunc, Counter)
Value:
    PRAGMA_DISABLE_DEPRECATION_WARNINGS \
    UE_DECLARE_INTERNAL_LINK_SPECIALIZATION(InternalLinkType, Counter - CounterBase) { \
        UE_STATIC_ONLY(InternalLinkType); \
        static void CallWriteFrozenField(FMemoryImageWriter& Writer, const void* Object, const void* FieldObject, const FTypeLayoutDesc& TypeDesc, const FTypeLayoutDesc& DerivedTypeDesc) { \
            static_cast<const DerivedType*>(Object)->InFunc(Writer, *(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)*)FieldObject); \
        } \
        static void Initialize(FTypeLayoutDesc& TypeDesc) { \
            InternalLinkType<Counter - CounterBase + 1>::Initialize(TypeDesc); \
            alignas(FFieldLayoutDesc) static uint8 FieldBuffer[sizeof(FFieldLayoutDesc)] = { 0 }; \
            FFieldLayoutDesc& FieldDesc = *(FFieldLayoutDesc*)FieldBuffer; \
            FieldDesc.Name = TEXT(#InName); \
            FieldDesc.UFieldNameLength = Freeze::FindFieldNameLength(FieldDesc.Name); \
            FieldDesc.Type = &StaticGetTypeLayoutDesc<PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)>(); \
            FieldDesc.WriteFrozenMemoryImageFunc = &CallWriteFrozenField; \
            FieldDesc.Offset = STRUCT_OFFSET(DerivedType, InName); \
            FieldDesc.NumArray = 1u; \
            FieldDesc.Flags = EFieldLayoutFlags::None; \
            FieldDesc.Next = TypeDesc.Fields; \
            TypeDesc.Fields = &FieldDesc; \
        } \
    }; \
PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 423 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL (Type)
Value:
PREPROCESSOR_JOIN(INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_, Type)
Definition at line 506 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Abstract
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Abstract { return FTypeLayoutDesc::GetInvalidTypeLayout(); }
Definition at line 505 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_NonVirtual
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_NonVirtual { return StaticGetTypeLayout(); }
Definition at line 503 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Virtual
#define INTERNAL_LAYOUT_INTERFACE_INLINE_IMPL_Virtual { return StaticGetTypeLayout(); }
Definition at line 504 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_PREFIX
#define INTERNAL_LAYOUT_INTERFACE_PREFIX (Type)
Value:
PREPROCESSOR_JOIN(INTERNAL_LAYOUT_INTERFACE_PREFIX_, Type)
Definition at line 496 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_PREFIX_Abstract
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_Abstract (...)
Value:
virtual
Definition at line 495 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_PREFIX_NonVirtual
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_NonVirtual (...)
Value:
__VA_ARGS__
Definition at line 493 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_PREFIX_Virtual
#define INTERNAL_LAYOUT_INTERFACE_PREFIX_Virtual (...)
Value:
__VA_ARGS__ virtual
Definition at line 494 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_SUFFIX
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX (Type)
Value:
PREPROCESSOR_JOIN(INTERNAL_LAYOUT_INTERFACE_SUFFIX_, Type)
Definition at line 501 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_SUFFIX_Abstract
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_Abstract { return FTypeLayoutDesc::GetInvalidTypeLayout(); }
Definition at line 500 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_SUFFIX_NonVirtual
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_NonVirtual ;
Definition at line 498 of file MemoryLayout.h.
INTERNAL_LAYOUT_INTERFACE_SUFFIX_Virtual
#define INTERNAL_LAYOUT_INTERFACE_SUFFIX_Virtual ;
Definition at line 499 of file MemoryLayout.h.
INTERNAL_LAYOUT_TOSTRING
#define INTERNAL_LAYOUT_TOSTRING (Func, Counter)
Value:
    UE_DECLARE_INTERNAL_LINK_SPECIALIZATION(InternalLinkType, Counter - CounterBase) { \
        UE_STATIC_ONLY(InternalLinkType); \
        static void CallToString(const void* Object, const FTypeLayoutDesc& TypeDesc, const FPlatformTypeLayoutParameters& LayoutParams, FMemoryToStringContext& OutContext) { \
            static_cast<const DerivedType*>(Object)->Func(OutContext); \
        } \
        static void Initialize(FTypeLayoutDesc& TypeDesc) { \
            InternalLinkType<Counter - CounterBase + 1>::Initialize(TypeDesc); \
            TypeDesc.ToStringFunc = &CallToString; \
        } \
    };
Definition at line 459 of file MemoryLayout.h.
INTERNAL_LAYOUT_WRITE_MEMORY_IMAGE
#define INTERNAL_LAYOUT_WRITE_MEMORY_IMAGE (Func, Counter)
Value:
    UE_DECLARE_INTERNAL_LINK_SPECIALIZATION(InternalLinkType, Counter - CounterBase) { \
        UE_STATIC_ONLY(InternalLinkType); \
        static void CallWriteMemoryImage(FMemoryImageWriter& Writer, const void* Object, const FTypeLayoutDesc& TypeDesc, const FTypeLayoutDesc& DerivedTypeDesc) { \
            static_cast<const DerivedType*>(Object)->Func(Writer, TypeDesc); \
        } \
        static void Initialize(FTypeLayoutDesc& TypeDesc) { \
            InternalLinkType<Counter - CounterBase + 1>::Initialize(TypeDesc); \
            TypeDesc.WriteFrozenMemoryImageFunc = &CallWriteMemoryImage; \
        } \
    };
Definition at line 447 of file MemoryLayout.h.
INTERNAL_REGISTER_TYPE_LAYOUT
#define INTERNAL_REGISTER_TYPE_LAYOUT (T)
Value:
static const FDelayedAutoRegisterHelper ANONYMOUS_VARIABLE(DelayedAutoRegisterHelper)(EDelayedRegisterRunPhase::ShaderTypesReady, []{ FTypeLayoutDesc::Register(T::StaticGetTypeLayout()); });
Definition at line 594 of file MemoryLayout.h.
LAYOUT_ARRAY
#define LAYOUT_ARRAY (T, Name, NumArray, ...)
Value:
PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name[NumArray]; INTERNAL_LAYOUT_FIELD(T, Name, STRUCT_OFFSET(DerivedType, Name), EFieldLayoutFlags::MakeFlags(__VA_ARGS__), NumArray, 0u, __COUNTER__)
Definition at line 475 of file MemoryLayout.h.
LAYOUT_ARRAY_EDITORONLY
#define LAYOUT_ARRAY_EDITORONLY (T, Name, NumArray, ...)
Definition at line 489 of file MemoryLayout.h.
LAYOUT_BITFIELD
#define LAYOUT_BITFIELD (T, Name, BitFieldSize, ...)
Value:
PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name : BitFieldSize; INTERNAL_LAYOUT_FIELD(T, Name, ~0u, EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, BitFieldSize, __COUNTER__)
Definition at line 477 of file MemoryLayout.h.
LAYOUT_BITFIELD_EDITORONLY
#define LAYOUT_BITFIELD_EDITORONLY (T, Name, BitFieldSize, ...)
Definition at line 490 of file MemoryLayout.h.
LAYOUT_FIELD
#define LAYOUT_FIELD (T, Name, ...)
Value:
PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name; INTERNAL_LAYOUT_FIELD(T, Name, STRUCT_OFFSET(DerivedType, Name), EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, 0u, __COUNTER__)
Definition at line 471 of file MemoryLayout.h.
LAYOUT_FIELD_EDITORONLY
#define LAYOUT_FIELD_EDITORONLY (T, Name, ...)
Definition at line 488 of file MemoryLayout.h.
LAYOUT_FIELD_INITIALIZED
#define LAYOUT_FIELD_INITIALIZED (T, Name, Value, ...)
Value:
PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name = Value; INTERNAL_LAYOUT_FIELD(T, Name, STRUCT_OFFSET(DerivedType, Name), EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, 0u, __COUNTER__)
Definition at line 473 of file MemoryLayout.h.
LAYOUT_FIELD_WITH_WRITER
#define LAYOUT_FIELD_WITH_WRITER (T, Name, Func)
Value:
PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name; INTERNAL_LAYOUT_FIELD_WITH_WRITER(T, Name, Func, __COUNTER__)
Definition at line 478 of file MemoryLayout.h.
LAYOUT_MUTABLE_BITFIELD
#define LAYOUT_MUTABLE_BITFIELD (T, Name, BitFieldSize, ...)
Value:
mutable PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name : BitFieldSize; INTERNAL_LAYOUT_FIELD(T, Name, ~0u, EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, BitFieldSize, __COUNTER__)
Definition at line 476 of file MemoryLayout.h.
LAYOUT_MUTABLE_FIELD
#define LAYOUT_MUTABLE_FIELD (T, Name, ...)
Value:
mutable PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name; INTERNAL_LAYOUT_FIELD(T, Name, STRUCT_OFFSET(DerivedType, Name), EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, 0u, __COUNTER__)
Definition at line 472 of file MemoryLayout.h.
LAYOUT_MUTABLE_FIELD_INITIALIZED
#define LAYOUT_MUTABLE_FIELD_INITIALIZED (T, Name, Value, ...)
Value:
mutable PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name = Value; INTERNAL_LAYOUT_FIELD(T, Name, STRUCT_OFFSET(DerivedType, Name), EFieldLayoutFlags::MakeFlags(__VA_ARGS__), 1u, 0u, __COUNTER__)
Definition at line 474 of file MemoryLayout.h.
LAYOUT_MUTABLE_FIELD_WITH_WRITER
#define LAYOUT_MUTABLE_FIELD_WITH_WRITER (T, Name, Func)
Value:
mutable PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T) Name; INTERNAL_LAYOUT_FIELD_WITH_WRITER(T, Name, Func, __COUNTER__)
Definition at line 479 of file MemoryLayout.h.
LAYOUT_TOSTRING
#define LAYOUT_TOSTRING (Func)
Value:
INTERNAL_LAYOUT_TOSTRING(Func, __COUNTER__)
Definition at line 481 of file MemoryLayout.h.
LAYOUT_WRITE_MEMORY_IMAGE
#define LAYOUT_WRITE_MEMORY_IMAGE (Func)
Value:
INTERNAL_LAYOUT_WRITE_MEMORY_IMAGE(Func, __COUNTER__)
Definition at line 480 of file MemoryLayout.h.
REGISTER_INLINE_TYPE_LAYOUT
#define REGISTER_INLINE_TYPE_LAYOUT (T)
Value:
    static const FDelayedAutoRegisterHelper ANONYMOUS_VARIABLE(DelayedAutoRegisterHelper)(EDelayedRegisterRunPhase::ShaderTypesReady, [] \
        { \
            PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)::StaticGetTypeLayout().Name = TEXT(#T); \
            FTypeLayoutDesc::Register(PREPROCESSOR_REMOVE_OPTIONAL_PARENS(T)::StaticGetTypeLayout()); \
        } \
    );
Definition at line 610 of file MemoryLayout.h.
UE_DECLARE_INTERNAL_LINK_BASE
#define UE_DECLARE_INTERNAL_LINK_BASE (T)
Value:
template<int Counter> struct T
Certain compilers don't accept full explicit template specializations inside class declarations.
Partial specializations are accepted however. So for these platforms, we force partial specialization via an extra dummy parameter that's otherwise ignored. This actually breaks MSVC, as MSVC doesn't allow complex statements as template values during partial specialization, so need use full specialization there.
Definition at line 44 of file MemoryLayout.h.
UE_DECLARE_INTERNAL_LINK_SPECIALIZATION
#define UE_DECLARE_INTERNAL_LINK_SPECIALIZATION (T, Counter)
Value:
template<> struct T<Counter>
Definition at line 45 of file MemoryLayout.h.
UE_STATIC_ONLY
#define UE_STATIC_ONLY (T)
Definition at line 33 of file MemoryLayout.h.
Function Documentation
DeleteObjectFromLayout()
template<typename T> void DeleteObjectFromLayout (T * Object, const FPointerTableBase * PtrTable = nullptr, bool bIsFrozen = false) inline
Definition at line 654 of file MemoryLayout.h.
References check, GetTypeLayoutDesc(), InternalDeleteObjectFromLayout(), and Object.
Referenced by TMemoryImagePtr< T >::SafeDelete().
GetBaseOffset()
template<typename T, typename Base> uint32 GetBaseOffset () inline
Definition at line 158 of file MemoryLayout.h.
Referenced by InternalInitializeBaseHelper().
GetDefault()
template<typename T> const T * GetDefault ()
Referenced by FPositioningData::FPositioningData(), FEnvQueryInstance::AddItemData(), FEnvQueryInstance::AddItemData(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), SRigVMActionMenu::GetSearchContextDesc(), InternalGetDefaultObject(), TypePromoDebug::IsTypePromoEnabled(), and SRigVMActionMenu::OnGetActionList().
GetTypeLayoutDesc()
template<typename T> const FTypeLayoutDesc & GetTypeLayoutDesc (const FPointerTableBase * , const T & Object) inline
Definition at line 649 of file MemoryLayout.h.
References TGetTypeLayoutHelper< T >::Do(), and Object.
Referenced by TMemoryImageObject< void >::TMemoryImageObject(), DeleteObjectFromLayout(), Freeze::IntrinsicToString(), Freeze::IntrinsicUnfrozenCopy(), Freeze::IntrinsicWriteMemoryImage(), FMemoryUnfreezeContent::UnfreezeObject(), FMemoryImageWriter::WriteObject(), and FMemoryImageWriter::WriteRootObject().
InternalDeleteObjectFromLayout()
void InternalDeleteObjectFromLayout (void * Object, const FTypeLayoutDesc & TypeDesc, const FPointerTableBase * PtrTable, bool bIsFrozen) extern
References Object.
Referenced by DeleteObjectFromLayout(), and TMemoryImageObject< T >::Destroy().
InternalGetDefaultObject()
template<typename T> const T * InternalGetDefaultObject ()
Definition at line 186 of file MemoryLayout.h.
References Default, GetDefault(), and THasCustomDefaultObject< T >::Value.
Referenced by TGetDefaultObjectHelper< T, ETypeLayoutInterface::Virtual >::Do().
InternalInitializeBaseHelper()
template<typename T, typename BaseType> void InternalInitializeBaseHelper (FTypeLayoutDesc & TypeDesc) static
Definition at line 345 of file MemoryLayout.h.
References FTypeLayoutDesc::Fields, GetBaseOffset(), ETypeLayoutInterface::HasVTable(), FTypeLayoutDesc::Interface, FFieldLayoutDesc::Name, FFieldLayoutDesc::Next, FFieldLayoutDesc::NumArray, FTypeLayoutDesc::NumBases, FTypeLayoutDesc::NumVirtualBases, FFieldLayoutDesc::Offset, PREPROCESSOR_REMOVE_OPTIONAL_PARENS, StaticGetTypeLayoutDesc(), TEXT, FFieldLayoutDesc::Type, FFieldLayoutDesc::UFieldNameLength, and FFieldLayoutDesc::WriteFrozenMemoryImageFunc.
Referenced by TInitializeBaseHelper< T, BaseType >::Initialize(), and InternalInitializeBasesHelper().
InternalInitializeBasesHelper() [1/2]
template<typename T> FORCEINLINE void InternalInitializeBasesHelper (FTypeLayoutDesc & TypeDesc) static
Definition at line 362 of file MemoryLayout.h.
References FORCEINLINE.
Referenced by InternalInitializeBasesHelper().
InternalInitializeBasesHelper() [2/2]
template<typename T, typename BaseType, typename ... RemainingBaseTypes> void InternalInitializeBasesHelper (FTypeLayoutDesc & TypeDesc) static
Definition at line 365 of file MemoryLayout.h.
References InternalInitializeBaseHelper(), and InternalInitializeBasesHelper().
PREPROCESSOR_REMOVE_OPTIONAL_PARENS() [1/2]
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (template< typename T >)
Definition at line 790 of file MemoryLayout.h.
PREPROCESSOR_REMOVE_OPTIONAL_PARENS() [2/2]
PREPROCESSOR_REMOVE_OPTIONAL_PARENS (template<>)
Definition at line 770 of file MemoryLayout.h.
StaticGetTypeLayoutDesc()
template<typename T> const FTypeLayoutDesc & StaticGetTypeLayoutDesc () inline
Definition at line 646 of file MemoryLayout.h.
References TStaticGetTypeLayoutHelper< T >::Do().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AppendHash(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::AppendHash(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyUnfrozen(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), TIndexedPtrBase< T, T * >::Get(), TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContentTypeDesc(), InternalInitializeBaseHelper(), Freeze::IntrinsicAppendHash(), Freeze::IntrinsicGetTargetAlignment(), Freeze::IntrinsicToString(), Freeze::IntrinsicUnfrozenCopy(), Freeze::IntrinsicWriteMemoryImage(), TPtrTableBase< T, PtrType >::StaticGetPtrTypeLayoutDesc(), RangedForIteratorType< FAnimNextTraitEventPtr >::ToString(), RangedForIteratorType< FAnimNextTraitEventPtr >::WriteMemoryImage(), TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >::WriteMemoryImage(), THashTable< FMemoryImageAllocator >::WriteMemoryImage(), TSet< class UObject * >::WriteMemoryImage(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage(), and TMemoryImagePtr< T >::WriteMemoryImageWithDerivedType().