Unreal Engine 5.6 C++ API: FNavigationLockContext Class Reference
FNavigationLockContext Class Reference
#include "NavigationSystemBase.h"
Public Member Functions
FNavigationLockContext (ENavigationLockReason::Type Reason=ENavigationLockReason::Unknown, bool bApplyLock=true)
FNavigationLockContext (UWorld *InWorld, ENavigationLockReason::Type Reason=ENavigationLockReason::Unknown, bool bApplyLock=true)
~FNavigationLockContext ()
Private Member Functions
void LockUpdates ()
void UnlockUpdates ()
Private Attributes
uint8 bIsLocked: 1
uint8 bSingleWorld: 1
uint8 LockReason
UWorld * MyWorld
Detailed Description
Definition at line 58 of file NavigationSystemBase.h.
Constructor & Destructor Documentation
FNavigationLockContext() [1/2]
FNavigationLockContext::FNavigationLockContext (ENavigationLockReason::Type Reason = ENavigationLockReason::Unknown, bool bApplyLock = true) inline
Definition at line 61 of file NavigationSystemBase.h.
References bIsLocked, bSingleWorld, LockReason, LockUpdates(), MyWorld, and ENavigationLockReason::Unknown.
FNavigationLockContext() [2/2]
FNavigationLockContext::FNavigationLockContext (UWorld * InWorld, ENavigationLockReason::Type Reason = ENavigationLockReason::Unknown, bool bApplyLock = true) inline
Definition at line 70 of file NavigationSystemBase.h.
References bIsLocked, bSingleWorld, LockReason, LockUpdates(), MyWorld, and ENavigationLockReason::Unknown.
~FNavigationLockContext()
FNavigationLockContext::~FNavigationLockContext () inline
Definition at line 79 of file NavigationSystemBase.h.
References UnlockUpdates().
Member Function Documentation
LockUpdates()
void FNavigationLockContext::LockUpdates () private
Referenced by FNavigationLockContext(), and FNavigationLockContext().
UnlockUpdates()
void FNavigationLockContext::UnlockUpdates () private
Referenced by ~FNavigationLockContext().
Field Documentation
bIsLocked
uint8 FNavigationLockContext::bIsLocked private
Definition at line 88 of file NavigationSystemBase.h.
Referenced by FNavigationLockContext(), and FNavigationLockContext().
bSingleWorld
uint8 FNavigationLockContext::bSingleWorld private
Definition at line 87 of file NavigationSystemBase.h.
Referenced by FNavigationLockContext(), and FNavigationLockContext().
LockReason
uint8 FNavigationLockContext::LockReason private
Definition at line 86 of file NavigationSystemBase.h.
Referenced by FNavigationLockContext(), and FNavigationLockContext().
MyWorld
UWorld* FNavigationLockContext::MyWorld private
Definition at line 85 of file NavigationSystemBase.h.
Referenced by FNavigationLockContext(), and FNavigationLockContext().
The documentation for this class was generated from the following file:
NavigationSystemBase.h