Unreal Engine 5.6 C++ API: FCanvasTextItemBase Class Reference
FCanvasTextItemBase Class Reference abstract
#include "CanvasItem.h"
Data Structures
struct FTextEffect
Public Member Functions
FCanvasTextItemBase (const FVector2D &InPosition, const FLinearColor &InColor)
virtual ~FCanvasTextItemBase ()
void DisableShadow ()
Disable the shadow.
virtual void Draw (FCanvas *InCanvas) override
Draw the item at the given coordinates.
virtual void Draw (FCanvas *InCanvas, const FVector2D &InPosition)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
virtual void Draw (FCanvas *InCanvas, float X, float Y)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
void EnableShadow (const FLinearColor &InColor, const FVector2D &InOffset=FVector2D(1.0f, 1.0f))
Set the shadow offset and color.
virtual void SetColor (const FLinearColor &InColor) override final
Public Member Functions inherited from FCanvasItem
FCanvasItem (const FVector2D &InPosition)
Basic render item.
virtual ~FCanvasItem ()
Data Fields
bool bCentreX
bool bCentreY
bool bDontCorrectStereoscopic
bool bOutlined
float Depth
FVector2D DrawnSize
FFontRenderInfo FontRenderInfo
float HorizSpacingAdjust
FLinearColor OutlineColor
FVector2D Scale
FLinearColor ShadowColor
FVector2D ShadowOffset
Data Fields inherited from FCanvasItem
FBatchedElementParameters * BatchedElementParameters
bool bFreezeTime
ESimpleElementBlendMode BlendMode
FVector2D Position
uint32 StereoDepth
Protected Member Functions
virtual void DrawStringInternal (FCanvas *InCanvas, const FVector2D &DrawPos, const FLinearColor &DrawColor, TArrayView< FTextEffect > Offsets)=0
Internal string draw.
virtual ESimpleElementBlendMode GetTextBlendMode (const bool bHasShadow) const =0
Get the blend mode we should use to draw this text.
virtual FVector2D GetTextSize (float DPIScale) const =0
Get the measured size of the text to draw.
virtual bool HasValidText () const =0
Does this text item have valid text to draw?
Protected Attributes
FBatchedElements * BatchedElements
These are used by the DrawStringInternal function.
FCanvasTileItem TileItem
Protected Attributes inherited from FCanvasItem
FLinearColor Color
Detailed Description
Definition at line 305 of file CanvasItem.h.
Constructor & Destructor Documentation
FCanvasTextItemBase()
FCanvasTextItemBase::FCanvasTextItemBase (const FVector2D & InPosition, const FLinearColor & InColor)
Referenced by FCanvasShapedTextItem::FCanvasShapedTextItem(), FCanvasSimpleTextItem::FCanvasSimpleTextItem(), and FCanvasSimpleTextItem::FCanvasSimpleTextItem().
~FCanvasTextItemBase()
virtual FCanvasTextItemBase::~FCanvasTextItemBase () virtual
Member Function Documentation
DisableShadow()
void FCanvasTextItemBase::DisableShadow () inline
Disable the shadow.
Definition at line 327 of file CanvasItem.h.
References FontRenderInfo, ShadowOffset, and UE::Math::TVector2< double >::ZeroVector.
Draw() [1/3]
virtual void FCanvasTextItemBase::Draw (FCanvas * InCanvas) override virtual
Draw the item at the given coordinates.
Parameters
InCanvas Canvas on which to draw
Implements FCanvasItem.
Draw() [2/3]
virtual void FCanvasItem::Draw (FCanvas * InCanvas, const FVector2D & InPosition) inline virtual
Draw this item (this will affect the items position for future draw calls that do no specify a position)
Parameters
InCanvas Canvas on which to draw
InPosition Draw position - this will not preserve the items position
Reimplemented from FCanvasItem.
Definition at line 52 of file CanvasItem.h.
Draw() [3/3]
virtual void FCanvasItem::Draw (FCanvas * InCanvas, float X, float Y) inline virtual
Draw this item (this will affect the items position for future draw calls that do no specify a position)
Parameters
InCanvas Canvas on which to draw
X X Draw position
Y Y Draw position
Reimplemented from FCanvasItem.
Definition at line 65 of file CanvasItem.h.
DrawStringInternal()
virtual void FCanvasTextItemBase::DrawStringInternal (FCanvas * InCanvas, const FVector2D & DrawPos, const FLinearColor & DrawColor, TArrayView< FTextEffect > Offsets) protected pure virtual
Internal string draw.
In a method to make it simpler to do effects like shadow, outline
Implemented in FCanvasShapedTextItem, FCanvasSimpleTextItem, FCanvasTextItem, and FCanvasTextStringViewItem.
EnableShadow()
void FCanvasTextItemBase::EnableShadow (const FLinearColor & InColor, const FVector2D & InOffset = FVector2D(1.0f, 1.0f)) inline
Set the shadow offset and color.
Parameters
InColor Shadow color
InOffset Shadow offset. Defaults to 1,1. (Passing zero vector will disable the shadow)
Definition at line 317 of file CanvasItem.h.
References FontRenderInfo, ShadowColor, and ShadowOffset.
GetTextBlendMode()
virtual ESimpleElementBlendMode FCanvasTextItemBase::GetTextBlendMode (const bool bHasShadow) const protected pure virtual
Get the blend mode we should use to draw this text.
Implemented in FCanvasShapedTextItem, and FCanvasSimpleTextItem.
GetTextSize()
virtual FVector2D FCanvasTextItemBase::GetTextSize (float DPIScale) const protected pure virtual
Get the measured size of the text to draw.
Implemented in FCanvasShapedTextItem, FCanvasSimpleTextItem, FCanvasTextItem, and FCanvasTextStringViewItem.
HasValidText()
virtual bool FCanvasTextItemBase::HasValidText () const protected pure virtual
Does this text item have valid text to draw?
Implemented in FCanvasShapedTextItem, FCanvasSimpleTextItem, FCanvasTextItem, and FCanvasTextStringViewItem.
SetColor()
virtual void FCanvasTextItemBase::SetColor (const FLinearColor & InColor) inline final override virtual
Reimplemented from FCanvasItem.
Definition at line 340 of file CanvasItem.h.
References FCanvasItem::SetColor().
Field Documentation
BatchedElements
FBatchedElements* FCanvasTextItemBase::BatchedElements protected
These are used by the DrawStringInternal function.
Definition at line 417 of file CanvasItem.h.
bCentreX
bool FCanvasTextItemBase::bCentreX
Definition at line 364 of file CanvasItem.h.
bCentreY
bool FCanvasTextItemBase::bCentreY
Definition at line 367 of file CanvasItem.h.
bDontCorrectStereoscopic
bool FCanvasTextItemBase::bDontCorrectStereoscopic
Definition at line 376 of file CanvasItem.h.
bOutlined
bool FCanvasTextItemBase::bOutlined
Definition at line 370 of file CanvasItem.h.
Depth
float FCanvasTextItemBase::Depth
Definition at line 349 of file CanvasItem.h.
DrawnSize
FVector2D FCanvasTextItemBase::DrawnSize
Definition at line 361 of file CanvasItem.h.
FontRenderInfo
FFontRenderInfo FCanvasTextItemBase::FontRenderInfo
Definition at line 352 of file CanvasItem.h.
Referenced by DisableShadow(), and EnableShadow().
HorizSpacingAdjust
float FCanvasTextItemBase::HorizSpacingAdjust
Definition at line 346 of file CanvasItem.h.
OutlineColor
FLinearColor FCanvasTextItemBase::OutlineColor
Definition at line 373 of file CanvasItem.h.
Scale
FVector2D FCanvasTextItemBase::Scale
Definition at line 379 of file CanvasItem.h.
ShadowColor
FLinearColor FCanvasTextItemBase::ShadowColor
Definition at line 355 of file CanvasItem.h.
Referenced by EnableShadow().
ShadowOffset
FVector2D FCanvasTextItemBase::ShadowOffset
Definition at line 358 of file CanvasItem.h.
Referenced by DisableShadow(), and EnableShadow().
TileItem
FCanvasTileItem FCanvasTextItemBase::TileItem protected
Definition at line 383 of file CanvasItem.h.
The documentation for this class was generated from the following file:
CanvasItem.h