Unreal Engine 5.6 C++ API: TMemoryImageAllocator< Alignment >::ForAnyElementType Class Reference
TMemoryImageAllocator< Alignment >::ForAnyElementType Class Reference
#include "MemoryImage.h"
Public Member Functions
ForAnyElementType ()=default
Default constructor.
FORCEINLINE int32 CalculateSlackGrow (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement) const
FORCEINLINE int32 CalculateSlackGrow (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const
FORCEINLINE int32 CalculateSlackReserve (int32 NewMax, int32 NumBytesPerElement) const
FORCEINLINE int32 CalculateSlackReserve (int32 NewMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const
FORCEINLINE int32 CalculateSlackShrink (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement) const
FORCEINLINE int32 CalculateSlackShrink (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const
FORCEINLINE SizeType GetInitialCapacity () const
FORCEINLINE void ResizeAllocation (int32 CurrentNum, int32 NewMax, SIZE_T NumBytesPerElement)
FORCEINLINE void ResizeAllocation (int32 CurrentNum, int32 NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement)
FORCEINLINE void WriteMemoryImage (FMemoryImageWriter &Writer, const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements) const
Public Member Functions inherited from FMemoryImageAllocatorBase
FMemoryImageAllocatorBase ()=default
~FMemoryImageAllocatorBase ()
Destructor.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, void *Dst) const
FORCEINLINE SIZE_T GetAllocatedSize (int32 CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE FScriptContainerElement * GetAllocation () const
FORCEINLINE int64 GetFrozenOffsetFromThis () const
FORCEINLINE bool HasAllocation ()
void MoveToEmpty (FMemoryImageAllocatorBase &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (int32 PreviousNumElements, int32 NumElements, SIZE_T NumBytesPerElement, uint32 Alignment)
void ToString (const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, int32 MaxAllocatedElements, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext) const
void WriteMemoryImage (FMemoryImageWriter &Writer, const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, uint32 Alignment) const
Detailed Description
template<uint32 Alignment = DEFAULT_ALIGNMENT>
class TMemoryImageAllocator< Alignment >::ForAnyElementType
Definition at line 650 of file MemoryImage.h.
Constructor & Destructor Documentation
ForAnyElementType()
template<uint32 Alignment = DEFAULT_ALIGNMENT> TMemoryImageAllocator< Alignment >::ForAnyElementType::ForAnyElementType () default
Default constructor.
Member Function Documentation
CalculateSlackGrow() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement) const inline
Definition at line 676 of file MemoryImage.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackGrow() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 680 of file MemoryImage.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackReserve() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve (int32 NewMax, int32 NumBytesPerElement) const inline
Definition at line 660 of file MemoryImage.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackReserve() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve (int32 NewMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 664 of file MemoryImage.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackShrink() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement) const inline
Definition at line 668 of file MemoryImage.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
CalculateSlackShrink() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE int32 TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink (int32 NewMax, int32 CurrentMax, int32 NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 672 of file MemoryImage.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
GetInitialCapacity()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE SizeType TMemoryImageAllocator< Alignment >::ForAnyElementType::GetInitialCapacity () const inline
Definition at line 656 of file MemoryImage.h.
References FORCEINLINE.
ResizeAllocation() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE void TMemoryImageAllocator< Alignment >::ForAnyElementType::ResizeAllocation (int32 CurrentNum, int32 NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 684 of file MemoryImage.h.
References FORCEINLINE, and FMemoryImageAllocatorBase::ResizeAllocation().
ResizeAllocation() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE void TMemoryImageAllocator< Alignment >::ForAnyElementType::ResizeAllocation (int32 CurrentNum, int32 NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 688 of file MemoryImage.h.
References FORCEINLINE, and FMemoryImageAllocatorBase::ResizeAllocation().
WriteMemoryImage()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE void TMemoryImageAllocator< Alignment >::ForAnyElementType::WriteMemoryImage (FMemoryImageWriter & Writer, const FTypeLayoutDesc & TypeDesc, int32 NumAllocatedElements) const inline
Definition at line 693 of file MemoryImage.h.
References FORCEINLINE, and FMemoryImageAllocatorBase::WriteMemoryImage().
The documentation for this class was generated from the following file:
MemoryImage.h