Unreal Engine 5.6 C++ API: FSoftObjectPtr Struct Reference
FSoftObjectPtr Struct Reference
FSoftObjectPtr is a type of weak pointer to a UObject, that also keeps track of the path to the object on disk.
#include "SoftObjectPtr.h"
Public Member Functions
FORCEINLINE FSoftObjectPtr ()=default
FORCEINLINE FSoftObjectPtr (const FSoftObjectPath &ObjectPath)
FORCEINLINE FSoftObjectPtr (const FSoftObjectPtr &Other)=default
FORCEINLINE FSoftObjectPtr (const UObject *Object)
FORCEINLINE FSoftObjectPtr (FObjectPtr Object)
FORCEINLINE FSoftObjectPtr (FSoftObjectPtr &&Other)=default
template<typename T>
FORCEINLINE FSoftObjectPtr (TObjectPtr< T > Object)
FORCEINLINE ~FSoftObjectPtr ()=default
FORCEINLINE UObject * Get () const
Overridden to deal with PIE lookups.
FORCEINLINE FString GetAssetName () const
Returns assetname string, leaving off the /package/path.
FORCEINLINE FName GetLongPackageFName () const
Returns /package/path name, leaving off the asset name.
FORCEINLINE FString GetLongPackageName () const
Returns /package/path string, leaving off the asset name.
UObject * LoadSynchronous () const
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
FORCEINLINE FSoftObjectPtr & operator= (const FSoftObjectPtr &Other)=default
FORCEINLINE FSoftObjectPtr & operator= (const UObject *Ptr)
FSoftObjectPtr & operator= (FObjectPtr Ptr)
FORCEINLINE FSoftObjectPtr & operator= (FSoftObjectPtr &&Other)=default
template<typename T>
FORCEINLINE FSoftObjectPtr & operator= (TObjectPtr< T > Ptr)
FORCEINLINE const FSoftObjectPath & ToSoftObjectPath () const
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
FORCEINLINE FString ToString () const
Returns string representation of reference, in form /package/path.assetname.
Public Member Functions inherited from TPersistentObjectPtr< FSoftObjectPath >
FORCEINLINE TPersistentObjectPtr ()
Default constructor, will be null.
FORCEINLINE TPersistentObjectPtr (const FSoftObjectPath &InObjectID)
Construct from a unique object identifier.
FORCEINLINE UObject * Get () const
Dereference the pointer, which may cause it to become valid again.
FORCEINLINE UObject * Get (bool bEvenIfPendingKill) const
Dereference the lazy pointer, which may cause it to become valid again.
FORCEINLINE FSoftObjectPath & GetUniqueID ()
Non-const version of the above.
FORCEINLINE const FSoftObjectPath & GetUniqueID () const
Gets the unique object identifier associated with this lazy pointer.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE bool operator!= (const TPersistentObjectPtr &Rhs) const
Compare pointers for inequality.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE UObject & operator* () const
Dereference the pointer.
FORCEINLINE UObject * operator-> () const
Dereference the pointer.
FORCEINLINE void operator= (const FSoftObjectPath &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const FWeakObjectPtr &Other)
Copy from an existing weak pointer, reserve IDs if required.
FORCEINLINE void operator= (const UObject *Object)
void operator= (FObjectPtr Object)
Copy from an object pointer.
FORCEINLINE void operator= (TObjectPtr< T > Object)
FORCEINLINE bool operator== (const TPersistentObjectPtr &Rhs) const
Compare pointers for equality.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE void Reset ()
Reset the lazy pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
Private Types
using Super = TPersistentObjectPtr<FSoftObjectPath>
Additional Inherited Members
Public Types inherited from TPersistentObjectPtr< FSoftObjectPath >
using ElementType
Detailed Description
FSoftObjectPtr is a type of weak pointer to a UObject, that also keeps track of the path to the object on disk.
It will change back and forth between being Valid and Pending as the referenced object loads or unloads. It has no impact on if the object is garbage collected or not.
This is useful to specify assets that you may want to asynchronously load on demand.
Definition at line 44 of file SoftObjectPtr.h.
Member Typedef Documentation
Super
using FSoftObjectPtr::Super = TPersistentObjectPtr<FSoftObjectPath> private
Definition at line 47 of file SoftObjectPtr.h.
Constructor & Destructor Documentation
FSoftObjectPtr() [1/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr () nodiscard default
References FORCEINLINE.
Referenced by FSoftObjectPtr(), FSoftObjectPtr(), FSoftObjectPtr(), FSoftObjectPtr(), operator=(), operator=(), operator=(), operator=(), and operator=().
FSoftObjectPtr() [2/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (const FSoftObjectPtr & Other) nodiscard default
References FSoftObjectPtr(), FORCEINLINE, and Other.
FSoftObjectPtr() [3/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (FSoftObjectPtr && Other) nodiscard default
References FSoftObjectPtr(), FORCEINLINE, and Other.
~FSoftObjectPtr()
FORCEINLINE FSoftObjectPtr::~FSoftObjectPtr () default
References FORCEINLINE.
FSoftObjectPtr() [4/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (const FSoftObjectPath & ObjectPath) inline explicit nodiscard
Definition at line 57 of file SoftObjectPtr.h.
References FORCEINLINE.
FSoftObjectPtr() [5/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (FObjectPtr Object) inline explicit nodiscard
Definition at line 62 of file SoftObjectPtr.h.
References FORCEINLINE, and Object.
FSoftObjectPtr() [6/7]
FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (const UObject * Object) inline explicit nodiscard
Definition at line 66 of file SoftObjectPtr.h.
References FSoftObjectPtr(), FORCEINLINE, and Object.
FSoftObjectPtr() [7/7]
template<typename T> FORCEINLINE FSoftObjectPtr::FSoftObjectPtr (TObjectPtr< T > Object) inline explicit nodiscard
Definition at line 71 of file SoftObjectPtr.h.
References FSoftObjectPtr(), FORCEINLINE, and Object.
Member Function Documentation
Get()
FORCEINLINE UObject * FSoftObjectPtr::Get () const inline nodiscard
Overridden to deal with PIE lookups.
Definition at line 127 of file SoftObjectPtr.h.
References FORCEINLINE, TPersistentObjectPtr< FSoftObjectPath >::Get(), UE::GetPlayInEditorID(), TPersistentObjectPtr< FSoftObjectPath >::GetUniqueID(), INDEX_NONE, and FSoftObjectPath::ResolveObject().
Referenced by LoadSynchronous().
GetAssetName()
FORCEINLINE FString FSoftObjectPtr::GetAssetName () const inline nodiscard
Returns assetname string, leaving off the /package/path.
part
Definition at line 120 of file SoftObjectPtr.h.
References FORCEINLINE, FSoftObjectPath::GetAssetName(), and ToSoftObjectPath().
GetLongPackageFName()
FORCEINLINE FName FSoftObjectPtr::GetLongPackageFName () const inline nodiscard
Returns /package/path name, leaving off the asset name.
Definition at line 114 of file SoftObjectPtr.h.
References FORCEINLINE, FSoftObjectPath::GetLongPackageFName(), and ToSoftObjectPath().
GetLongPackageName()
FORCEINLINE FString FSoftObjectPtr::GetLongPackageName () const inline nodiscard
Returns /package/path string, leaving off the asset name.
Definition at line 108 of file SoftObjectPtr.h.
References FORCEINLINE, FSoftObjectPath::GetLongPackageName(), and ToSoftObjectPath().
LoadSynchronous()
UObject * FSoftObjectPtr::LoadSynchronous () const inline
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
Definition at line 82 of file SoftObjectPtr.h.
References Asset, Get(), TPersistentObjectPtr< FSoftObjectPath >::IsNull(), ToSoftObjectPath(), and FSoftObjectPath::TryLoad().
operator=() [1/5]
FORCEINLINE FSoftObjectPtr & FSoftObjectPtr::operator= (const FSoftObjectPtr & Other) default
References FSoftObjectPtr(), FORCEINLINE, and Other.
operator=() [2/5]
FORCEINLINE FSoftObjectPtr & FSoftObjectPtr::operator= (const UObject * Ptr) inline
Definition at line 148 of file SoftObjectPtr.h.
References FSoftObjectPtr(), and FORCEINLINE.
operator=() [3/5]
FSoftObjectPtr & FSoftObjectPtr::operator= (FObjectPtr Ptr) inline
Definition at line 142 of file SoftObjectPtr.h.
References FSoftObjectPtr().
operator=() [4/5]
FORCEINLINE FSoftObjectPtr & FSoftObjectPtr::operator= (FSoftObjectPtr && Other) default
References FSoftObjectPtr(), FORCEINLINE, and Other.
operator=() [5/5]
template<typename T> FORCEINLINE FSoftObjectPtr & FSoftObjectPtr::operator= (TObjectPtr< T > Ptr) inline
Definition at line 153 of file SoftObjectPtr.h.
References FSoftObjectPtr(), and FORCEINLINE.
ToSoftObjectPath()
FORCEINLINE const FSoftObjectPath & FSoftObjectPtr::ToSoftObjectPath () const inline nodiscard
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
Definition at line 96 of file SoftObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FSoftObjectPath >::GetUniqueID().
Referenced by GetAssetName(), GetLongPackageFName(), GetLongPackageName(), LoadSynchronous(), and ToString().
ToString()
FORCEINLINE FString FSoftObjectPtr::ToString () const inline nodiscard
Returns string representation of reference, in form /package/path.assetname.
Definition at line 102 of file SoftObjectPtr.h.
References FORCEINLINE, ToSoftObjectPath(), and FSoftObjectPath::ToString().
The documentation for this struct was generated from the following file:
SoftObjectPtr.h