Unreal Engine 5.6 C++ API: UE::Geometry::TPlane3< RealType > Struct Template Reference
UE::Geometry::TPlane3< RealType > Struct Template Reference
#include "PlaneTypes.h"
Public Types
enum EClipSegmentType { FullyClipped , FirstClipped , SecondClipped , NotClipped }
Public Member Functions
TPlane3 ()
TPlane3 (const FPlane &Plane)
TPlane3 (const UE::Math::TVector< RealType > &Normal, const UE::Math::TVector< RealType > &Point)
N is specified, c = Dot(N,P) where P is a point on the plane.
TPlane3 (const UE::Math::TVector< RealType > &Normal, double Constant)
TPlane3 (const UE::Math::TVector< RealType > &P0, const UE::Math::TVector< RealType > &P1, const UE::Math::TVector< RealType > &P2)
N = Cross(P1-P0,P2-P0)/Length(Cross(P1-P0,P2-P0)), c = Dot(N,P0) where P0, P1, P2 are points on the plane.
EClipSegmentType ClipSegment (UE::Math::TVector< RealType > &Point0, UE::Math::TVector< RealType > &Point1) const
Clip line segment defined by two points against plane.
double DistanceTo (const UE::Math::TVector< RealType > &P) const
Compute d = Dot(N,P)-c where N is the plane normal and c is the plane constant.
bool FindLineIntersection (const UE::Math::TVector< RealType > &LineOrigin, const UE::Math::TVector< RealType > &LineDirection, UE::Math::TVector< RealType > &IntersectionPointOut) const
Compute intersection of Line with Plane.
void InverseTransform (const TTransform< RealType > &Tr)
Transform the plane by the inverse of the given transform.
operator FPlane () const
void Transform (const TTransform< RealType > &Tr)
Transform the plane by the given transform.
int WhichSide (const UE::Math::TVector< RealType > &P) const
The "positive side" of the plane is the half space to which the plane normal points.
Data Fields
RealType Constant
TVector< RealType > Normal
Detailed Description
template<typename RealType>
struct UE::Geometry::TPlane3< RealType >
Definition at line 20 of file PlaneTypes.h.
Member Enumeration Documentation
EClipSegmentType
template<typename RealType> enum UE::Geometry::TPlane3::EClipSegmentType
Enumerator
FullyClipped
FirstClipped
SecondClipped
NotClipped
Definition at line 143 of file PlaneTypes.h.
Constructor & Destructor Documentation
TPlane3() [1/5]
template<typename RealType> UE::Geometry::TPlane3< RealType >::TPlane3 () inline
Definition at line 25 of file PlaneTypes.h.
TPlane3() [2/5]
template<typename RealType> UE::Geometry::TPlane3< RealType >::TPlane3 (const UE::Math::TVector< RealType > & Normal, double Constant) inline
Definition at line 27 of file PlaneTypes.h.
TPlane3() [3/5]
template<typename RealType> UE::Geometry::TPlane3< RealType >::TPlane3 (const UE::Math::TVector< RealType > & Normal, const UE::Math::TVector< RealType > & Point) inline
N is specified, c = Dot(N,P) where P is a point on the plane.
Definition at line 34 of file PlaneTypes.h.
TPlane3() [4/5]
template<typename RealType> UE::Geometry::TPlane3< RealType >::TPlane3 (const UE::Math::TVector< RealType > & P0, const UE::Math::TVector< RealType > & P1, const UE::Math::TVector< RealType > & P2) inline
N = Cross(P1-P0,P2-P0)/Length(Cross(P1-P0,P2-P0)), c = Dot(N,P0) where P0, P1, P2 are points on the plane.
Definition at line 42 of file PlaneTypes.h.
TPlane3() [5/5]
template<typename RealType> UE::Geometry::TPlane3< RealType >::TPlane3 (const FPlane & Plane) inline explicit
Definition at line 48 of file PlaneTypes.h.
Member Function Documentation
ClipSegment()
template<typename RealType> EClipSegmentType UE::Geometry::TPlane3< RealType >::ClipSegment (UE::Math::TVector< RealType > & Point0, UE::Math::TVector< RealType > & Point1) const inline
Clip line segment defined by two points against plane.
Region of Segment on positive side of Plane is kept.
Parameters
Point0 first point of segment
Point1 second point of segment
Returns
FullyClipped if the segment lies fully behind or exactly in the plane FirstClipped if Point0 became the intersection point on the plane SecondClipped if Point1 became the intersection point on the plane NotClipped if the segment lies fully in front of the plane
Definition at line 161 of file PlaneTypes.h.
DistanceTo()
template<typename RealType> double UE::Geometry::TPlane3< RealType >::DistanceTo (const UE::Math::TVector< RealType > & P) const inline
Compute d = Dot(N,P)-c where N is the plane normal and c is the plane constant.
This is a signed distance. The sign of the return value is positive if the point is on the positive side of the plane, negative if the point is on the negative side, and zero if the point is on the plane.
Definition at line 88 of file PlaneTypes.h.
Referenced by UE::Geometry::TPlane3< FVector::FReal >::ClipSegment(), UE::Geometry::TIntrTriangle3Triangle3< float >::TrianglePlaneRelations(), and UE::Geometry::TPlane3< FVector::FReal >::WhichSide().
FindLineIntersection()
template<typename RealType> bool UE::Geometry::TPlane3< RealType >::FindLineIntersection (const UE::Math::TVector< RealType > & LineOrigin, const UE::Math::TVector< RealType > & LineDirection, UE::Math::TVector< RealType > & IntersectionPointOut) const inline
Compute intersection of Line with Plane.
Parameters
LineOrigin origin of line
LineDirection direction of line
HitPointOut intersection point, or invalid point if line is parallel to plane
Returns
true if Line intersects Plane and IntersectionPointOut is valid
Definition at line 126 of file PlaneTypes.h.
InverseTransform()
template<typename RealType> void UE::Geometry::TPlane3< RealType >::InverseTransform (const TTransform< RealType > & Tr) inline
Transform the plane by the inverse of the given transform.
Definition at line 72 of file PlaneTypes.h.
operator FPlane()
template<typename RealType> UE::Geometry::TPlane3< RealType >::operator FPlane () const inline explicit
Definition at line 52 of file PlaneTypes.h.
Transform()
template<typename RealType> void UE::Geometry::TPlane3< RealType >::Transform (const TTransform< RealType > & Tr) inline
Transform the plane by the given transform.
Definition at line 60 of file PlaneTypes.h.
WhichSide()
template<typename RealType> int UE::Geometry::TPlane3< RealType >::WhichSide (const UE::Math::TVector< RealType > & P) const inline
The "positive side" of the plane is the half space to which the plane normal points.
The "negative side" is the other half space. The function returns +1 when P is on the positive side, -1 when P is on the the negative side, or 0 when P is on the plane.
Definition at line 99 of file PlaneTypes.h.
Field Documentation
Constant
template<typename RealType> RealType UE::Geometry::TPlane3< RealType >::Constant
Definition at line 23 of file PlaneTypes.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), and UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment().
Normal
template<typename RealType> TVector<RealType> UE::Geometry::TPlane3< RealType >::Normal
Definition at line 22 of file PlaneTypes.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::ContainsPoint(), UE::Geometry::TIntrTriangle3Triangle3< float >::Find(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), and UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment().
The documentation for this struct was generated from the following file:
PlaneTypes.h