Unreal Engine 5.6 C++ API: TSetElement< InElementType > Class Template Reference
TSetElement< InElementType > Class Template Reference
An element in the set.
#include "Set.h"
Public Member Functions
TSetElement ()=default
Default constructor.
TSetElement (const TSetElement &)=default
template<typename InitType UE_REQUIRES>
FORCEINLINE TSetElement (InitType &&InValue)
Initialization constructor.
TSetElement (TSetElement &&)=default
FORCEINLINE bool operator!= (const TSetElement &Other) const
TSetElement & operator= (const TSetElement &)=default
TSetElement & operator= (TSetElement &&)=default
FORCEINLINE bool operator== (const TSetElement &Other) const
Public Member Functions inherited from TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >
TSetElementBase ()=default
TSetElementBase (const TSetElementBase &)=default
FORCEINLINE TSetElementBase (InitType &&InValue)
Initialization constructor.
TSetElementBase (TSetElementBase &&)=default
TSetElementBase & operator= (const TSetElementBase &)=default
TSetElementBase & operator= (TSetElementBase &&)=default
Private Types
using Super = TSetElementBase<InElementType, THasTypeLayout<InElementType>::Value>
Additional Inherited Members
Public Types inherited from TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >
typedef InElementType ElementType
Data Fields inherited from TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >
int32 HashIndex
The hash bucket that the element is currently linked to.
FSetElementId HashNextId
The id of the next element in the same hash bucket.
ElementType Value
The element's value.
Detailed Description
template<typename InElementType>
class TSetElement< InElementType >
An element in the set.
Definition at line 95 of file Set.h.
Member Typedef Documentation
Super
template<typename InElementType> using TSetElement< InElementType >::Super = TSetElementBase<InElementType, THasTypeLayout<InElementType>::Value> private
Definition at line 97 of file Set.h.
Constructor & Destructor Documentation
TSetElement() [1/4]
template<typename InElementType> TSetElement< InElementType >::TSetElement () nodiscard default
Default constructor.
References TSetElement().
Referenced by TSetElement(), TSetElement(), TSetElement(), operator!=(), operator=(), operator=(), and operator==().
TSetElement() [2/4]
template<typename InElementType> template<typename InitType UE_REQUIRES> FORCEINLINE TSetElement< InElementType >::TSetElement (InitType && InValue) inline explicit nodiscard
Initialization constructor.
Definition at line 107 of file Set.h.
References FORCEINLINE, and Forward().
TSetElement() [3/4]
template<typename InElementType> TSetElement< InElementType >::TSetElement (TSetElement< InElementType > &&) nodiscard default
References TSetElement().
TSetElement() [4/4]
template<typename InElementType> TSetElement< InElementType >::TSetElement (const TSetElement< InElementType > &) nodiscard default
References TSetElement().
Member Function Documentation
operator!=()
template<typename InElementType> FORCEINLINE bool TSetElement< InElementType >::operator!= (const TSetElement< InElementType > & Other) const inline nodiscard
Definition at line 122 of file Set.h.
References TSetElement(), FORCEINLINE, Other, and TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >::Value.
operator=() [1/2]
template<typename InElementType> TSetElement & TSetElement< InElementType >::operator= (const TSetElement< InElementType > &) default
References TSetElement().
operator=() [2/2]
template<typename InElementType> TSetElement & TSetElement< InElementType >::operator= (TSetElement< InElementType > &&) default
References TSetElement().
operator==()
template<typename InElementType> FORCEINLINE bool TSetElement< InElementType >::operator== (const TSetElement< InElementType > & Other) const inline nodiscard
Definition at line 118 of file Set.h.
References TSetElement(), FORCEINLINE, Other, and TSetElementBase< InElementType, THasTypeLayout< InElementType >::Value >::Value.
The documentation for this class was generated from the following file:
Set.h