Unreal Engine 5.6 C++ API: FShaderMapResourceCode Class Reference
FShaderMapResourceCode Class Reference
#include "Shader.h"
Data Structures
struct FShaderEntry
Public Member Functions
FShaderMapResourceCode ()
RENDERCORE_API FShaderMapResourceCode (const FShaderMapResourceCode &Other)
RENDERCORE_API ~FShaderMapResourceCode ()
RENDERCORE_API void AddShaderCompilerOutput (const FShaderCompilerOutput &Output, const FShaderCompileJobKey &Key, FString DebugInfo=FString())
void AddShaderCompilerOutput (const FShaderCompilerOutput &Output, const FString &DebugName=FString(), FString DebugInfo=FString())
RENDERCORE_API void Finalize ()
int32 FindShaderIndex (const FSHAHash &InHash) const
RENDERCORE_API uint32 GetSizeBytes () const
RENDERCORE_API void Serialize (FArchive &Ar, bool bLoadingCooked)
RENDERCORE_API void Serialize (FShaderSerializeContext &Ctx)
RENDERCORE_API void ToString (FStringBuilderBase &OutString) const
Public Member Functions inherited from FThreadSafeRefCountedObject
FThreadSafeRefCountedObject ()=default
FThreadSafeRefCountedObject (const FThreadSafeRefCountedObject &Rhs)=delete
virtual ~FThreadSafeRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FThreadSafeRefCountedObject & operator= (const FThreadSafeRefCountedObject &Rhs)=delete
uint32 Release () const
Data Fields
FSHAHash ResourceHash
A hash describing the total contents of *this.
TArray< FShaderCodeResource > ShaderCodeResources
TArray< FShaderEntry > ShaderEntries
TArray< FSHAHash > ShaderHashes
Detailed Description
Definition at line 514 of file Shader.h.
Constructor & Destructor Documentation
FShaderMapResourceCode() [1/2]
FShaderMapResourceCode::FShaderMapResourceCode () inline
Definition at line 580 of file Shader.h.
Referenced by FShaderMapResourceCode().
FShaderMapResourceCode() [2/2]
RENDERCORE_API FShaderMapResourceCode::FShaderMapResourceCode (const FShaderMapResourceCode & Other)
References FShaderMapResourceCode(), and Other.
~FShaderMapResourceCode()
RENDERCORE_API FShaderMapResourceCode::~FShaderMapResourceCode ()
Member Function Documentation
AddShaderCompilerOutput() [1/2]
RENDERCORE_API void FShaderMapResourceCode::AddShaderCompilerOutput (const FShaderCompilerOutput & Output, const FShaderCompileJobKey & Key, FString DebugInfo = FString())
References Key.
AddShaderCompilerOutput() [2/2]
void FShaderMapResourceCode::AddShaderCompilerOutput (const FShaderCompilerOutput & Output, const FString & DebugName = FString(), FString DebugInfo = FString()) inline
Definition at line 597 of file Shader.h.
References AddShaderCompilerOutput().
Referenced by AddShaderCompilerOutput().
Finalize()
RENDERCORE_API void FShaderMapResourceCode::Finalize ()
FindShaderIndex()
int32 FShaderMapResourceCode::FindShaderIndex (const FSHAHash & InHash) const
GetSizeBytes()
RENDERCORE_API uint32 FShaderMapResourceCode::GetSizeBytes () const
Serialize() [1/2]
RENDERCORE_API void FShaderMapResourceCode::Serialize (FArchive & Ar, bool bLoadingCooked)
References Ar, and Serialize().
Referenced by Serialize(), and Serialize().
Serialize() [2/2]
RENDERCORE_API void FShaderMapResourceCode::Serialize (FShaderSerializeContext & Ctx)
References Serialize().
ToString()
RENDERCORE_API void FShaderMapResourceCode::ToString (FStringBuilderBase & OutString) const
Field Documentation
ResourceHash
FSHAHash FShaderMapResourceCode::ResourceHash
A hash describing the total contents of *this.
Constructed from the contents of ShaderHashes during Finalize.
Definition at line 613 of file Shader.h.
ShaderCodeResources
TArray<FShaderCodeResource> FShaderMapResourceCode::ShaderCodeResources
Definition at line 621 of file Shader.h.
ShaderEntries
TArray<FShaderEntry> FShaderMapResourceCode::ShaderEntries
Definition at line 618 of file Shader.h.
ShaderHashes
TArray<FSHAHash> FShaderMapResourceCode::ShaderHashes
Definition at line 614 of file Shader.h.
The documentation for this class was generated from the following file:
Shader.h