Unreal Engine 5.6 C++ API: FBehaviorTreeInstance Struct Reference
FBehaviorTreeInstance Struct Reference
data required for instance of single subtree
#include "BehaviorTreeTypes.h"
Public Member Functions
AIMODULE_API FBehaviorTreeInstance ()
AIMODULE_API FBehaviorTreeInstance (FBehaviorTreeInstance &&Other)
AIMODULE_API FBehaviorTreeInstance (int32 MemorySize)
AIMODULE_API ~FBehaviorTreeInstance ()
void AddToActiveAuxNodes (UBehaviorTreeComponent &OwnerComp, UBTAuxiliaryNode *AuxNode)
add specified node to the active nodes list
void AddToParallelTasks (FBehaviorTreeParallelTask &&ParallelTask)
add new parallel task
void Cleanup (UBehaviorTreeComponent &OwnerComp, EBTMemoryClear::Type CleanupType)
cleanup node instances
void DeactivateNodes (FBehaviorTreeSearchData &SearchData, uint16 InstanceIndex)
deactivate all active aux nodes and remove their requests from SearchData
FORCEINLINE void DecMemoryStats () const
void ExecuteOnEachAuxNode (TFunctionRef< void(const UBTAuxiliaryNode &)> ExecFunc)
iterate on auxiliary nodes and call ExecFunc on each of them.
void ExecuteOnEachParallelTask (TFunctionRef< void(const FBehaviorTreeParallelTask &, const int32)> ExecFunc)
iterate on parallel tasks and call ExecFunc on each of them.
TArrayView< UBTAuxiliaryNode *const > GetActiveAuxNodes () const
get list of all active auxiliary nodes
FORCEINLINE uint32 GetAllocatedSize () const
TArrayView< const uint8 > GetInstanceMemory () const
get instance memory
TArrayView< const FBehaviorTreeParallelTask > GetParallelTasks () const
get list of all active parallel tasks
bool HasActiveNode (uint16 TestExecutionIndex) const
check if instance has active node with given execution index
FORCEINLINE void IncMemoryStats () const
void Initialize (UBehaviorTreeComponent &OwnerComp, UBTCompositeNode &Node, int32 &InstancedIndex, EBTMemoryInit::Type InitType)
initialize memory and create node instances
bool IsValidParallelTaskIndex (const int32 Index) const
indicates if the provided index is a valid parallel task index
void MarkParallelTaskAsAbortingAt (int32 TaskIndex)
mark parallel task at given index as pending abort
AIMODULE_API FBehaviorTreeInstance & operator= (FBehaviorTreeInstance &&Other)
void RemoveFromActiveAuxNodes (UBehaviorTreeComponent &OwnerComp, UBTAuxiliaryNode *AuxNode)
remove specified node from the active nodes list
void RemoveParallelTaskAt (int32 TaskIndex)
remove parallel task at given index
void ResetActiveAuxNodes ()
remove all auxiliary nodes from active nodes list
void SetInstanceMemory (const TArray< uint8 > &Memory)
set instance memory
UE_DEPRECATED (5.2, "Copying FBehaviorTreeInstance assignement operator has been deprecated in favor of move assignement operator") FBehaviorTreeInstance &operator
UE_DEPRECATED (5.2, "Copying FBehaviorTreeInstance constructor has been deprecated in favor of move-constructor") AIMODULE_API FBehaviorTreeInstance(const FBehaviorTreeInstance &Other)
UE_DEPRECATED (5.4, "This function is deprecated. Please use version that takes UBehaviorTreeComponent.") void AddToActiveAuxNodes(UBTAuxiliaryNode *AuxNode)
UE_DEPRECATED (5.4, "This function is deprecated. Please use version that takes UBehaviorTreeComponent.") void RemoveFromActiveAuxNodes(UBTAuxiliaryNode *AuxNode)
Data Fields
TArray< UBTAuxiliaryNode * > ActiveAuxNodes
active auxiliary nodes
UBTNode * ActiveNode
active node in template
TEnumAsByte< EBTActiveNode::Type > ActiveNodeType
active node type
FBTInstanceDeactivation DeactivationNotify
delegate sending a notify when tree instance is removed from active stack
uint8 InstanceIdIndex
index of identifier (BehaviorTreeComponent.KnownInstances)
TArray< uint8 > InstanceMemory
memory: instance
TArray< FBehaviorTreeParallelTask > ParallelTasks
active parallel tasks
UBTCompositeNode * RootNode
root node in template
Protected Member Functions
void CleanupNodes (UBehaviorTreeComponent &OwnerComp, UBTCompositeNode &Node, EBTMemoryClear::Type CleanupType)
worker for updating all nodes
Private Member Functions
void AddToActiveAuxNodesImpl (UBTAuxiliaryNode *AuxNode)
void RemoveFromActiveAuxNodesImpl (UBTAuxiliaryNode *AuxNode)
Detailed Description
data required for instance of single subtree
Definition at line 319 of file BehaviorTreeTypes.h.
Constructor & Destructor Documentation
FBehaviorTreeInstance() [1/3]
AIMODULE_API FBehaviorTreeInstance::FBehaviorTreeInstance ()
Referenced by FBehaviorTreeInstance(), FBehaviorTreeInstance(), ~FBehaviorTreeInstance(), operator=(), UE_DEPRECATED(), and UE_DEPRECATED().
FBehaviorTreeInstance() [2/3]
AIMODULE_API FBehaviorTreeInstance::FBehaviorTreeInstance (FBehaviorTreeInstance && Other)
References FBehaviorTreeInstance(), and Other.
FBehaviorTreeInstance() [3/3]
AIMODULE_API FBehaviorTreeInstance::FBehaviorTreeInstance (int32 MemorySize)
References FBehaviorTreeInstance().
~FBehaviorTreeInstance()
AIMODULE_API FBehaviorTreeInstance::~FBehaviorTreeInstance ()
References FBehaviorTreeInstance().
Member Function Documentation
AddToActiveAuxNodes()
void FBehaviorTreeInstance::AddToActiveAuxNodes (UBehaviorTreeComponent & OwnerComp, UBTAuxiliaryNode * AuxNode)
add specified node to the active nodes list
References AddToActiveAuxNodes().
Referenced by AddToActiveAuxNodes(), and UE_DEPRECATED().
AddToActiveAuxNodesImpl()
void FBehaviorTreeInstance::AddToActiveAuxNodesImpl (UBTAuxiliaryNode * AuxNode) private
AddToParallelTasks()
void FBehaviorTreeInstance::AddToParallelTasks (FBehaviorTreeParallelTask && ParallelTask)
add new parallel task
Cleanup()
void FBehaviorTreeInstance::Cleanup (UBehaviorTreeComponent & OwnerComp, EBTMemoryClear::Type CleanupType)
cleanup node instances
CleanupNodes()
void FBehaviorTreeInstance::CleanupNodes (UBehaviorTreeComponent & OwnerComp, UBTCompositeNode & Node, EBTMemoryClear::Type CleanupType) protected
worker for updating all nodes
DeactivateNodes()
void FBehaviorTreeInstance::DeactivateNodes (FBehaviorTreeSearchData & SearchData, uint16 InstanceIndex)
deactivate all active aux nodes and remove their requests from SearchData
DecMemoryStats()
FORCEINLINE void FBehaviorTreeInstance::DecMemoryStats () const inline
Definition at line 366 of file BehaviorTreeTypes.h.
References FORCEINLINE.
ExecuteOnEachAuxNode()
void FBehaviorTreeInstance::ExecuteOnEachAuxNode (TFunctionRef< void(const UBTAuxiliaryNode &)> ExecFunc)
iterate on auxiliary nodes and call ExecFunc on each of them.
Nodes can not be added or removed during the iteration
References ExecuteOnEachAuxNode().
Referenced by ExecuteOnEachAuxNode().
ExecuteOnEachParallelTask()
void FBehaviorTreeInstance::ExecuteOnEachParallelTask (TFunctionRef< void(const FBehaviorTreeParallelTask &, const int32)> ExecFunc)
iterate on parallel tasks and call ExecFunc on each of them.
Supports removing the iterated task while processed
GetActiveAuxNodes()
TArrayView< UBTAuxiliaryNode *const > FBehaviorTreeInstance::GetActiveAuxNodes () const inline
get list of all active auxiliary nodes
Definition at line 382 of file BehaviorTreeTypes.h.
References ActiveAuxNodes.
GetAllocatedSize()
FORCEINLINE uint32 FBehaviorTreeInstance::GetAllocatedSize () const inline
Definition at line 364 of file BehaviorTreeTypes.h.
References FORCEINLINE.
GetInstanceMemory()
TArrayView< const uint8 > FBehaviorTreeInstance::GetInstanceMemory () const inline
get instance memory
Definition at line 424 of file BehaviorTreeTypes.h.
References InstanceMemory.
GetParallelTasks()
TArrayView< const FBehaviorTreeParallelTask > FBehaviorTreeInstance::GetParallelTasks () const inline
get list of all active parallel tasks
Definition at line 403 of file BehaviorTreeTypes.h.
References GetParallelTasks(), and ParallelTasks.
Referenced by GetParallelTasks().
HasActiveNode()
bool FBehaviorTreeInstance::HasActiveNode (uint16 TestExecutionIndex) const
check if instance has active node with given execution index
IncMemoryStats()
FORCEINLINE void FBehaviorTreeInstance::IncMemoryStats () const inline
Definition at line 365 of file BehaviorTreeTypes.h.
References FORCEINLINE.
Initialize()
void FBehaviorTreeInstance::Initialize (UBehaviorTreeComponent & OwnerComp, UBTCompositeNode & Node, int32 & InstancedIndex, EBTMemoryInit::Type InitType)
initialize memory and create node instances
IsValidParallelTaskIndex()
bool FBehaviorTreeInstance::IsValidParallelTaskIndex (const int32 Index) const inline
indicates if the provided index is a valid parallel task index
Definition at line 415 of file BehaviorTreeTypes.h.
References ParallelTasks.
MarkParallelTaskAsAbortingAt()
void FBehaviorTreeInstance::MarkParallelTaskAsAbortingAt (int32 TaskIndex)
mark parallel task at given index as pending abort
operator=()
AIMODULE_API FBehaviorTreeInstance & FBehaviorTreeInstance::operator= (FBehaviorTreeInstance && Other)
References FBehaviorTreeInstance(), and Other.
RemoveFromActiveAuxNodes()
void FBehaviorTreeInstance::RemoveFromActiveAuxNodes (UBehaviorTreeComponent & OwnerComp, UBTAuxiliaryNode * AuxNode)
remove specified node from the active nodes list
References RemoveFromActiveAuxNodes().
Referenced by RemoveFromActiveAuxNodes(), and UE_DEPRECATED().
RemoveFromActiveAuxNodesImpl()
void FBehaviorTreeInstance::RemoveFromActiveAuxNodesImpl (UBTAuxiliaryNode * AuxNode) private
References INDEX_NONE.
RemoveParallelTaskAt()
void FBehaviorTreeInstance::RemoveParallelTaskAt (int32 TaskIndex)
remove parallel task at given index
ResetActiveAuxNodes()
void FBehaviorTreeInstance::ResetActiveAuxNodes ()
remove all auxiliary nodes from active nodes list
References ResetActiveAuxNodes().
Referenced by ResetActiveAuxNodes().
SetInstanceMemory()
void FBehaviorTreeInstance::SetInstanceMemory (const TArray< uint8 > & Memory)
set instance memory
References Memory.
UE_DEPRECATED() [1/4]
FBehaviorTreeInstance::UE_DEPRECATED (5. 2, "Copying FBehaviorTreeInstance assignement operator has been deprecated in favor of move assignement operator") &
References FBehaviorTreeInstance(), Other, and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FBehaviorTreeInstance::UE_DEPRECATED (5. 2, "Copying FBehaviorTreeInstance constructor has been deprecated in favor of move-constructor") const &
References FBehaviorTreeInstance(), and Other.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FBehaviorTreeInstance::UE_DEPRECATED (5. 4, "This function is deprecated. Please use version that takes UBehaviorTreeComponent.")
References AddToActiveAuxNodes().
UE_DEPRECATED() [4/4]
FBehaviorTreeInstance::UE_DEPRECATED (5. 4, "This function is deprecated. Please use version that takes UBehaviorTreeComponent.")
References RemoveFromActiveAuxNodes(), and UE_DEPRECATED().
Field Documentation
ActiveAuxNodes
TArray<UBTAuxiliaryNode*> FBehaviorTreeInstance::ActiveAuxNodes
active auxiliary nodes
Definition at line 328 of file BehaviorTreeTypes.h.
Referenced by GetActiveAuxNodes().
ActiveNode
UBTNode* FBehaviorTreeInstance::ActiveNode
active node in template
Definition at line 325 of file BehaviorTreeTypes.h.
ActiveNodeType
TEnumAsByte<EBTActiveNode::Type> FBehaviorTreeInstance::ActiveNodeType
active node type
Definition at line 340 of file BehaviorTreeTypes.h.
DeactivationNotify
FBTInstanceDeactivation FBehaviorTreeInstance::DeactivationNotify
delegate sending a notify when tree instance is removed from active stack
Definition at line 343 of file BehaviorTreeTypes.h.
InstanceIdIndex
uint8 FBehaviorTreeInstance::InstanceIdIndex
index of identifier (BehaviorTreeComponent.KnownInstances)
Definition at line 337 of file BehaviorTreeTypes.h.
InstanceMemory
TArray<uint8> FBehaviorTreeInstance::InstanceMemory
memory: instance
Definition at line 334 of file BehaviorTreeTypes.h.
Referenced by GetInstanceMemory().
ParallelTasks
TArray<FBehaviorTreeParallelTask> FBehaviorTreeInstance::ParallelTasks
active parallel tasks
Definition at line 331 of file BehaviorTreeTypes.h.
Referenced by GetParallelTasks(), and IsValidParallelTaskIndex().
RootNode
UBTCompositeNode* FBehaviorTreeInstance::RootNode
root node in template
Definition at line 322 of file BehaviorTreeTypes.h.
The documentation for this struct was generated from the following file:
BehaviorTreeTypes.h