Unreal Engine 5.6 C++ API: UE::MovieScene::FSharedPlaybackState Struct Reference
UE::MovieScene::FSharedPlaybackState Struct Reference
A structure that stores playback state for an entire sequence hierarchy.
#include "MovieSceneSharedPlaybackState.h"
Public Member Functions
MOVIESCENE_API FSharedPlaybackState (UMovieSceneEntitySystemLinker *InLinker=nullptr)
MOVIESCENE_API FSharedPlaybackState (UMovieSceneSequence &InRootSequence, const FSharedPlaybackStateCreateParams &CreateParams)
MOVIESCENE_API ~FSharedPlaybackState ()
template<typename T, typename ... ArgTypes>
T & AddCapability (ArgTypes &&... InArgs)
Builds the specified capability for the root sequence.
template<typename T>
T & AddCapabilityRaw (T *InPointer)
Adds the specified capability on the root sequence as a raw pointer.
template<typename T>
T & AddCapabilityShared (TSharedRef< T > InSharedRef)
Adds the specified capability on the root sequence as a shared pointer.
MOVIESCENE_API void ClearObjectCaches ()
Clears object caches for the entire sequence hierarchy.
MOVIESCENE_API TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FGuid &ObjectBindingID, FMovieSceneSequenceIDRef SequenceID) const
Finds the bound objects for the given object binding in the given (sub)sequence.
template<typename T>
T * FindCapability () const
Finds the specified capability on the root sequence.
FPlaybackCapabilities & GetCapabilities ()
Gets the capabilities container.
const FPlaybackCapabilities & GetCapabilities () const
Gets the capabilities container.
TObjectPtr< UMovieSceneCompiledDataManager > GetCompiledDataManager () const
Gets the compiled data manager that contains the data for the root sequence.
MOVIESCENE_API const FMovieSceneSequenceHierarchy * GetHierarchy () const
Gets the hierarchy (if any) for this root sequence.
UMovieSceneEntitySystemLinker * GetLinker () const
Gets the linker evaluating this root sequence.
UObject * GetPlaybackContext () const
Gets the playback context.
FMovieSceneInstancePreAnimatedState & GetPreAnimatedState ()
Gets the pre-animated state utility for the sequence hierarchy.
const FMovieSceneInstancePreAnimatedState & GetPreAnimatedState () const
Gets the pre-animated state utility for the sequence hierarchy.
const FMovieSceneCompiledDataID & GetRootCompiledDataID () const
Gets the compiled data ID for the root sequence.
const FRootInstanceHandle & GetRootInstanceHandle () const
Gets the handle of the root sequence.
UMovieSceneSequence * GetRootSequence () const
Gets the root sequence.
MOVIESCENE_API TSharedPtr< FMovieSceneEntitySystemRunner > GetRunner () const
Gets the runner evaluating this root sequence.
MOVIESCENE_API UMovieSceneSequence * GetSequence (FMovieSceneSequenceIDRef SequenceID) const
Gets a sub-sequence given an ID.
template<typename T>
bool HasCapability () const
Returns whether the root sequence has the specified capability.
MOVIESCENE_API void InvalidateCachedData ()
void SetDebugBreakOnDestroy ()
template<typename T, typename ... ArgTypes>
T & SetOrAddCapability (ArgTypes &&... InArgs)
Adds the specified capability on the root sequence.
template<typename T, typename ... ArgTypes>
T & SetOrAddCapabilityRaw (T *InPointer)
Adds the specified capability on the root sequence as a raw pointer.
template<typename T, typename ... ArgTypes>
T & SetOrAddCapabilityShared (TSharedRef< T > InSharedRef)
Adds the specified capability on the root sequence as a shared pointer.
Public Member Functions inherited from TSharedFromThis< FSharedPlaybackState >
TSharedRef< FSharedPlaybackState, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSharedPlaybackState, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
template<typename T>
void MaybeInitialize (T &Cap)
Private Attributes
bool bDebugBreakOnDestroy = false
FPlaybackCapabilities Capabilities
Playback capabilities for the root sequence.
TObjectPtr< UMovieSceneCompiledDataManager > CompiledDataManager
The compiled data manager that contains the data for the root sequence.
FMovieSceneInstancePreAnimatedState PreAnimatedState
Pre-animated state utility for the sequence hierarchy.
FMovieSceneCompiledDataID RootCompiledDataID
The compiled data ID for the root sequence.
FRootInstanceHandle RootInstanceHandle
The handle of the root sequence.
TWeakObjectPtr< UMovieSceneEntitySystemLinker > WeakLinker
The linker evaluating this root sequence.
TWeakObjectPtr< UObject > WeakPlaybackContext
The playback context.
TWeakObjectPtr< UMovieSceneSequence > WeakRootSequence
The root sequence.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FSharedPlaybackState >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FSharedPlaybackState >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A structure that stores playback state for an entire sequence hierarchy.
Definition at line 58 of file MovieSceneSharedPlaybackState.h.
Constructor & Destructor Documentation
FSharedPlaybackState() [1/2]
MOVIESCENE_API UE::MovieScene::FSharedPlaybackState::FSharedPlaybackState (UMovieSceneEntitySystemLinker * InLinker = nullptr)
References UE_API.
FSharedPlaybackState() [2/2]
MOVIESCENE_API UE::MovieScene::FSharedPlaybackState::FSharedPlaybackState (UMovieSceneSequence & InRootSequence, const FSharedPlaybackStateCreateParams & CreateParams)
References UE_API.
~FSharedPlaybackState()
MOVIESCENE_API UE::MovieScene::FSharedPlaybackState::~FSharedPlaybackState ()
References UE_API.
Member Function Documentation
AddCapability()
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FSharedPlaybackState::AddCapability (ArgTypes &&... InArgs) inline
Builds the specified capability for the root sequence.
Definition at line 169 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, Forward(), IsInGameThread(), MaybeInitialize(), and TEXT.
AddCapabilityRaw()
template<typename T> T & UE::MovieScene::FSharedPlaybackState::AddCapabilityRaw (T * InPointer) inline
Adds the specified capability on the root sequence as a raw pointer.
Definition at line 184 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), MaybeInitialize(), and TEXT.
AddCapabilityShared()
template<typename T> T & UE::MovieScene::FSharedPlaybackState::AddCapabilityShared (TSharedRef< T > InSharedRef) inline
Adds the specified capability on the root sequence as a shared pointer.
Definition at line 199 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), MaybeInitialize(), and TEXT.
ClearObjectCaches()
MOVIESCENE_API void UE::MovieScene::FSharedPlaybackState::ClearObjectCaches ()
Clears object caches for the entire sequence hierarchy.
References UE_API.
FindBoundObjects()
MOVIESCENE_API TArrayView< TWeakObjectPtr<> > UE::MovieScene::FSharedPlaybackState::FindBoundObjects (const FGuid & ObjectBindingID, FMovieSceneSequenceIDRef SequenceID) const
Finds the bound objects for the given object binding in the given (sub)sequence.
References UE_API.
FindCapability()
template<typename T> T * UE::MovieScene::FSharedPlaybackState::FindCapability () const inline
Finds the specified capability on the root sequence.
Definition at line 156 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), and TEXT.
GetCapabilities() [1/2]
FPlaybackCapabilities & UE::MovieScene::FSharedPlaybackState::GetCapabilities () inline
Gets the capabilities container.
Definition at line 118 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), and TEXT.
GetCapabilities() [2/2]
const FPlaybackCapabilities & UE::MovieScene::FSharedPlaybackState::GetCapabilities () const inline
Gets the capabilities container.
Definition at line 130 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), and TEXT.
GetCompiledDataManager()
TObjectPtr< UMovieSceneCompiledDataManager > UE::MovieScene::FSharedPlaybackState::GetCompiledDataManager () const inline
Gets the compiled data manager that contains the data for the root sequence.
Definition at line 81 of file MovieSceneSharedPlaybackState.h.
References CompiledDataManager.
GetHierarchy()
MOVIESCENE_API const FMovieSceneSequenceHierarchy * UE::MovieScene::FSharedPlaybackState::GetHierarchy () const
Gets the hierarchy (if any) for this root sequence.
References UE_API.
GetLinker()
UMovieSceneEntitySystemLinker * UE::MovieScene::FSharedPlaybackState::GetLinker () const inline
Gets the linker evaluating this root sequence.
Definition at line 78 of file MovieSceneSharedPlaybackState.h.
References WeakLinker.
GetPlaybackContext()
UObject * UE::MovieScene::FSharedPlaybackState::GetPlaybackContext () const inline
Gets the playback context.
Definition at line 72 of file MovieSceneSharedPlaybackState.h.
References WeakPlaybackContext.
GetPreAnimatedState() [1/2]
FMovieSceneInstancePreAnimatedState & UE::MovieScene::FSharedPlaybackState::GetPreAnimatedState () inline
Gets the pre-animated state utility for the sequence hierarchy.
Definition at line 93 of file MovieSceneSharedPlaybackState.h.
References PreAnimatedState.
GetPreAnimatedState() [2/2]
const FMovieSceneInstancePreAnimatedState & UE::MovieScene::FSharedPlaybackState::GetPreAnimatedState () const inline
Gets the pre-animated state utility for the sequence hierarchy.
Definition at line 90 of file MovieSceneSharedPlaybackState.h.
References PreAnimatedState.
GetRootCompiledDataID()
const FMovieSceneCompiledDataID & UE::MovieScene::FSharedPlaybackState::GetRootCompiledDataID () const inline
Gets the compiled data ID for the root sequence.
Definition at line 87 of file MovieSceneSharedPlaybackState.h.
References RootCompiledDataID.
GetRootInstanceHandle()
const FRootInstanceHandle & UE::MovieScene::FSharedPlaybackState::GetRootInstanceHandle () const inline
Gets the handle of the root sequence.
Definition at line 84 of file MovieSceneSharedPlaybackState.h.
References RootInstanceHandle.
GetRootSequence()
UMovieSceneSequence * UE::MovieScene::FSharedPlaybackState::GetRootSequence () const inline
Gets the root sequence.
Definition at line 75 of file MovieSceneSharedPlaybackState.h.
References WeakRootSequence.
GetRunner()
MOVIESCENE_API TSharedPtr< FMovieSceneEntitySystemRunner > UE::MovieScene::FSharedPlaybackState::GetRunner () const
Gets the runner evaluating this root sequence.
References UE_API.
GetSequence()
MOVIESCENE_API UMovieSceneSequence * UE::MovieScene::FSharedPlaybackState::GetSequence (FMovieSceneSequenceIDRef SequenceID) const
Gets a sub-sequence given an ID.
References UE_API.
HasCapability()
template<typename T> bool UE::MovieScene::FSharedPlaybackState::HasCapability () const inline
Returns whether the root sequence has the specified capability.
Definition at line 143 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, IsInGameThread(), and TEXT.
Referenced by SetOrAddCapability(), SetOrAddCapabilityRaw(), and SetOrAddCapabilityShared().
InvalidateCachedData()
MOVIESCENE_API void UE::MovieScene::FSharedPlaybackState::InvalidateCachedData ()
References UE_API.
MaybeInitialize()
template<typename T> void UE::MovieScene::FSharedPlaybackState::MaybeInitialize (T & Cap) inline private
Definition at line 302 of file MovieSceneSharedPlaybackState.h.
References UE::MovieScene::IPlaybackCapability::Initialize(), TSharedFromThis< FSharedPlaybackState >::SharedThis(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
Referenced by AddCapability(), AddCapabilityRaw(), AddCapabilityShared(), SetOrAddCapability(), SetOrAddCapabilityRaw(), and SetOrAddCapabilityShared().
SetDebugBreakOnDestroy()
void UE::MovieScene::FSharedPlaybackState::SetDebugBreakOnDestroy () inline
Definition at line 296 of file MovieSceneSharedPlaybackState.h.
References bDebugBreakOnDestroy.
SetOrAddCapability()
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FSharedPlaybackState::SetOrAddCapability (ArgTypes &&... InArgs) inline
Adds the specified capability on the root sequence.
If the capability already exists, it must be stored inline, and its value will be replaced by the new object. If the template parameter is a sub-class of the playback capability, the previously stored playback capability must not only have been stored inline, but must have been of the same sub-class (or a sub-class with the exact same size and alignment).
Definition at line 219 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, Forward(), HasCapability(), IsInGameThread(), MaybeInitialize(), and TEXT.
SetOrAddCapabilityRaw()
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FSharedPlaybackState::SetOrAddCapabilityRaw (T * InPointer) inline
Adds the specified capability on the root sequence as a raw pointer.
If the capability already exists, it must be stored as a raw pointer and its value will be replaced by the new pointer.
Definition at line 245 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, HasCapability(), IsInGameThread(), MaybeInitialize(), and TEXT.
SetOrAddCapabilityShared()
template<typename T, typename ... ArgTypes> T & UE::MovieScene::FSharedPlaybackState::SetOrAddCapabilityShared (TSharedRef< T > InSharedRef) inline
Adds the specified capability on the root sequence as a shared pointer.
If the capability already exists, it must be stored as a shared pointer and its value will be replaced by the new pointer.
Definition at line 271 of file MovieSceneSharedPlaybackState.h.
References Capabilities, ensureMsgf, HasCapability(), IsInGameThread(), MaybeInitialize(), and TEXT.
Field Documentation
bDebugBreakOnDestroy
bool UE::MovieScene::FSharedPlaybackState::bDebugBreakOnDestroy = false private
Definition at line 338 of file MovieSceneSharedPlaybackState.h.
Referenced by SetDebugBreakOnDestroy().
Capabilities
FPlaybackCapabilities UE::MovieScene::FSharedPlaybackState::Capabilities private
Playback capabilities for the root sequence.
Definition at line 332 of file MovieSceneSharedPlaybackState.h.
Referenced by AddCapability(), AddCapabilityRaw(), AddCapabilityShared(), FindCapability(), GetCapabilities(), GetCapabilities(), HasCapability(), SetOrAddCapability(), SetOrAddCapabilityRaw(), and SetOrAddCapabilityShared().
CompiledDataManager
TObjectPtr<UMovieSceneCompiledDataManager> UE::MovieScene::FSharedPlaybackState::CompiledDataManager private
The compiled data manager that contains the data for the root sequence.
Definition at line 323 of file MovieSceneSharedPlaybackState.h.
Referenced by GetCompiledDataManager().
PreAnimatedState
FMovieSceneInstancePreAnimatedState UE::MovieScene::FSharedPlaybackState::PreAnimatedState private
Pre-animated state utility for the sequence hierarchy.
Definition at line 335 of file MovieSceneSharedPlaybackState.h.
Referenced by GetPreAnimatedState(), and GetPreAnimatedState().
RootCompiledDataID
FMovieSceneCompiledDataID UE::MovieScene::FSharedPlaybackState::RootCompiledDataID private
The compiled data ID for the root sequence.
Definition at line 329 of file MovieSceneSharedPlaybackState.h.
Referenced by GetRootCompiledDataID().
RootInstanceHandle
FRootInstanceHandle UE::MovieScene::FSharedPlaybackState::RootInstanceHandle private
The handle of the root sequence.
Definition at line 326 of file MovieSceneSharedPlaybackState.h.
Referenced by GetRootInstanceHandle().
WeakLinker
TWeakObjectPtr<UMovieSceneEntitySystemLinker> UE::MovieScene::FSharedPlaybackState::WeakLinker private
The linker evaluating this root sequence.
Definition at line 320 of file MovieSceneSharedPlaybackState.h.
Referenced by GetLinker().
WeakPlaybackContext
TWeakObjectPtr<UObject> UE::MovieScene::FSharedPlaybackState::WeakPlaybackContext private
The playback context.
Definition at line 317 of file MovieSceneSharedPlaybackState.h.
Referenced by GetPlaybackContext().
WeakRootSequence
TWeakObjectPtr<UMovieSceneSequence> UE::MovieScene::FSharedPlaybackState::WeakRootSequence private
The root sequence.
Definition at line 314 of file MovieSceneSharedPlaybackState.h.
Referenced by GetRootSequence().
The documentation for this struct was generated from the following file:
MovieSceneSharedPlaybackState.h