Unreal Engine 5.6 C++ API: APawn Class Reference
APawn Class Reference
#include "Pawn.h"
Public Member Functions
virtual void BecomeViewTarget (APlayerController *PC) override
virtual void BeginPlay () override
virtual bool CanBeBaseForCharacter (APawn *APawn) const override
Overridden to defer to the RootComponent's CanCharacterStepUpOn setting if it is explicitly Yes or No.
virtual void Destroyed () override
virtual void DisableInput (APlayerController *PlayerController) override
void DispatchRestart (bool bCallClientRestart)
Wrapper function to call correct restart functions, enable bCallClientRestart if this is a locally owned player pawn or equivalent.
virtual void DisplayDebug (UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos) override
virtual void EditorApplyRotation (const FRotator &DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
virtual void EnableInput (APlayerController *PlayerController) override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual void EndViewTarget (APlayerController *PC) override
virtual void FaceRotation (FRotator NewControlRotation, float DeltaTime=0.f)
Updates Pawn's rotation to the given rotation, assumed to be the Controller's ControlRotation.
virtual void GetActorEyesViewPoint (FVector &Location, FRotator &Rotation) const override
template<class T>
T * GetController () const
Returns controller for this actor cast to the template type.
virtual float GetDefaultHalfHeight () const
Returns The half-height of the default Pawn, scaled by the component scale.
virtual FVector GetGravityDirection () const
Returns vector direction of gravity.
virtual FQuat GetGravityTransform () const
Returns a quaternion transforming from world space into gravity relative space.
virtual FString GetHumanReadableName () const override
virtual void GetMoveGoalReachTest (const AActor *MovingActor, const FVector &MoveOffset, FVector &GoalOffset, float &GoalRadius, float &GoalHalfHeight) const override
Get cylinder for testing if actor has been reached.
virtual const FNavAgentProperties & GetNavAgentPropertiesRef () const override
virtual class UNetConnection * GetNetConnection () const override
virtual const AActor * GetNetOwner () const override
virtual UPlayer * GetNetOwningPlayer () override
virtual UPlayer * GetNetOwningPlayerAnyRole () override
virtual UPawnNoiseEmitterComponent * GetPawnNoiseEmitterComponent () const
Return our PawnNoiseEmitterComponent, if any.
virtual FVector GetPawnViewLocation () const
Returns Pawn's eye location.
virtual APhysicsVolume * GetPhysicsVolume () const override
Return Physics Volume for this Pawn.
APlayerState * GetPlayerState () const
If Pawn is possessed by a player, returns its Player State.
template<class T>
T * GetPlayerState () const
Templated convenience version of GetPlayerState.
template<class T>
T * GetPlayerStateChecked () const
Templated convenience version of GetPlayerState which checks the type is as presumed.
FORCEINLINE uint16 GetRemoteViewPitch () const
Replicated pitch value so we can see where remote clients are looking.
virtual FVector GetVelocity () const override
virtual FRotator GetViewRotation () const
Get the view rotation of the Pawn (direction they are looking, normally Controller->ControlRotation).
virtual bool InFreeCam () const
Returns true if player is viewing this Pawn in FreeCam.
bool InputEnabled () const
Whether this Pawn's input handling is enabled.
void Internal_AddMovementInput (FVector WorldAccel, bool bForce=false)
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_ConsumeMovementInputVector ()
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetLastMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetPendingMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
virtual bool IsBasedOnActor (const AActor *Other) const override
bool IsLocalPlayerControllerViewingAPawn () const
virtual bool IsNetRelevantFor (const AActor *RealViewer, const AActor *ViewTarget, const FVector &SrcLocation) const override
void MoveIgnoreActorAdd (AActor *ActorToIgnore)
Add an Actor to ignore by Pawn's movement collision.
void MoveIgnoreActorRemove (AActor *ActorToIgnore)
Remove an Actor to ignore by Pawn's movement collision.
virtual void NotifyControllerChanged ()
Call to notify about a change in controller, on both the server and owning client.
virtual void NotifyRestarted ()
Notifies other systems that a pawn has been restarted.
virtual void OutsideWorldBounds () override
virtual void PawnClientRestart ()
Called on the owning client of a player-controlled Pawn when it is restarted, this calls Restart()
virtual void PawnStartFire (uint8 FireModeNum=0)
Handle StartFire() passed from PlayerController.
virtual void PossessedBy (AController *NewController)
Called when this Pawn is possessed.
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitializeComponents () override
virtual void PostLoad () override
virtual void PostNetReceiveLocationAndRotation () override
virtual void PostNetReceiveVelocity (const FVector &NewVelocity) override
virtual void PostRegisterAllComponents () override
virtual void PreInitializeComponents () override
virtual bool ReachedDesiredRotation ()
Return true if yaw is within AllowedYawError of desired yaw.
virtual void RecalculateBaseEyeHeight ()
Set BaseEyeHeight based on current state.
virtual void Reset () override
virtual void Restart ()
Called when the Pawn is being restarted (usually by being possessed by a Controller).
void SetController (AController *InController)
Sets controller for this actor.
virtual void SetPlayerDefaults ()
Make sure pawn properties are back to default.
void SetPlayerState (APlayerState *NewPlayerState)
Set the Pawn's Player State.
void SetRemoteViewPitch (double NewRemoteViewPitch)
Set Pawn ViewPitch, so we can see where remote clients are looking.
virtual bool ShouldTakeDamage (float Damage, FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) const
Return true if we are in a state to take damage (checked at the start of TakeDamage.
virtual bool ShouldTickIfViewportsOnly () const override
virtual float TakeDamage (float Damage, struct FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) override
virtual void TeleportSucceeded (bool bIsATest) override
virtual void TurnOff ()
Freeze pawn - stop sounds, animations, physics, weapon firing.
UE_DEPRECATED (4.24, "IsControlled is deprecated. To check if this pawn is controlled by anything, then call IsPawnControlled. To check if this pawn is controlled only by the player then call IsPlayerControlled") UFUNCTION() 1 bool IsControlled() const
See if this actor is currently being controlled.
UE_DEPRECATED (5.0, "GetPawnPhysicsVolume is deprecated. Please use GetPhysicsVolume instead.") 1 virtual APhysicsVolume *GetPawnPhysicsVolume() const
Return Physics Volume for this Pawn.
UE_DEPRECATED (5.6, "This property is deprecated, use GetRemoteViewPitch()/RemoteViewPitch16 instead.") UPROPERTY() uint8 RemoteViewPitch
DEPRECTED, use RemoteViewPitch16 instead.
UFUNCTION () 1 APlayerController *GetLocalViewingPlayerController() const
Returns local Player Controller viewing this pawn, whether it is controlling or spectating.
UFUNCTION () 1 bool IsLocallyViewed() const
UFUNCTION () 1 FPlatformUserId GetPlatformUserId() const
Returns the Platform User ID of the PlayerController that is controlling this character.
UFUNCTION () 1 FRotator GetControlRotation() const
Get the rotation of the Controller, often the 'view' rotation of this Pawn.
UFUNCTION () 1 TSubclassOf< UInputComponent > GetOverrideInputComponentClass() const
UFUNCTION () 1 virtual bool IsBotControlled() const
Returns true if controlled by a bot.
UFUNCTION () 1 virtual bool IsLocallyControlled() const
Returns true if controlled by a local (not network) Controller.
UFUNCTION () 1 virtual bool IsMoveInputIgnored() const
Helper to see if move input is ignored.
UFUNCTION () 1 virtual bool IsPawnControlled() const
Check if this actor is currently being controlled at all (the actor has a valid Controller, which will be false for remote clients)
UFUNCTION () 1 virtual bool IsPlayerControlled() const
Returns true if controlled by a human player (possessed by a PlayerController).
UFUNCTION () 1 virtual FRotator GetBaseAimRotation() const
Return the aim rotation for the Pawn.
UFUNCTION () 1 virtual void OnRep_Controller()
Called when Controller is replicated.
UFUNCTION () 1 virtual void OnRep_PlayerState()
PlayerState Replication Notification Callback.
UFUNCTION () 1 virtual void SpawnDefaultController()
Spawn default controller for this Pawn, and get possessed by it.
UFUNCTION () 1 void PawnMakeNoise(float Loudness
Inform AIControllers that you've made a noise they might hear (they are sent a HearNoise message if they have bHearNoises==true) The instigator of this sound is the pawn which is used to call MakeNoise.
UFUNCTION () 1 void ReceiveControllerChanged(AController *OldController
Event called after a pawn's controller has changed, on the server and owning client.
UFUNCTION () 1 void ReceiveRestarted()
Event called after a pawn has been restarted, usually by a possession change.
UFUNCTION () AController *GetController() const
Returns controller for this actor.
UFUNCTION () static 1 AActor *GetMovementBaseActor(const APawn *Pawn)
Gets the owning actor of the Movement Base Component on which the pawn is standing.
UFUNCTION () virtual FVector GetNavAgentLocation() const override
Basically retrieved pawn's location on navmesh.
UFUNCTION ()) 1 FVector GetLastMovementInputVector() const
Return the last input vector in world space that was processed by ConsumeMovementInputVector(), which is usually done by the Pawn or PawnMovementComponent.
UFUNCTION ()) 1 FVector GetPendingMovementInputVector() const
Return the pending input vector in world space.
UFUNCTION ()) 1 virtual FVector ConsumeMovementInputVector()
Returns the pending input vector and resets it to zero.
UFUNCTION ()) 1 virtual void AddControllerPitchInput(float Val)
Add input (affecting Pitch) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerRollInput(float Val)
Add input (affecting Roll) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerYawInput(float Val)
Add input (affecting Yaw) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddMovementInput(FVector WorldDirection
Add movement input along the given world direction vector (usually normalized) scaled by 'ScaleValue'.
UFUNCTION ()) 1 virtual void DetachFromControllerPendingDestroy()
Call this function to detach safely pawn from its controller, knowing that we will be destroyed soon.
UFUNCTION ()) 1 void ReceivePossessed(AController *NewController)
Event called when the Pawn is possessed by a Controller.
UFUNCTION ()) 1 void ReceiveUnpossessed(AController *OldController)
Event called when the Pawn is no longer possessed by a Controller.
UFUNCTION ()) 1 void SetCanAffectNavigationGeneration(bool bNewValue
Use SetCanAffectNavigationGeneration to change this value at runtime.
virtual void UnPossessed ()
Called when our Controller no longer possesses us.
void UpdateNavAgent ()
Updates MovementComponent's parameters used by navigation system.
virtual void UpdateNavigationRelevance ()
Update all components relevant for navigation generators to match bCanAffectNavigationGeneration flag.
UPROPERTY ()
Default class to use when pawn is controlled by AI.
UPROPERTY() TEnumAsByte< EAutoReceiveInput UPROPERTY () EAutoPossessAI AutoPossessAI
Determines which PlayerController, if any, should automatically possess the pawn when the level starts or when the pawn is spawned.
UPROPERTY () float BaseEyeHeight
Base eye height above collision center.
UPROPERTY () FPawnControllerChangedSignature ReceiveControllerChangedDelegate
Event called after a pawn's controller has changed, on the server and owning client.
UPROPERTY () FPawnRestartedSignature ReceiveRestartedDelegate
Event called after a pawn has been restarted, usually by a possession change.
UPROPERTY () TObjectPtr< AController > Controller
Controller currently possessing this Actor.
UPROPERTY () TObjectPtr< AController > LastHitBy
Controller of the last Actor that caused us damage.
UPROPERTY () TObjectPtr< AController > PreviousController
Previous controller that was controlling this pawn since the last controller change notification.
Data Fields
float AllowedYawError
Max difference between pawn's Rotation.Yaw and GetDesiredRotation().Yaw for pawn to be considered as having reached its desired rotation.
float bool bForce = false)
bool bForceUpdate = false)
FVector bool bUseNoiseMakerLocation = true
AController * NewController
FVector NoiseLocation
FVector bool AActor * NoiseMaker = nullptr)
float ScaleValue = 1.0f
Static Public Attributes
static FOnPawnBeginPlay OnPawnBeginPlay
a delegate that broadcasts a notification whenever BeginPlay() is called
Protected Member Functions
virtual UInputComponent * CreatePlayerInputComponent ()
Creates an InputComponent that can be used for custom input bindings.
virtual void DestroyPlayerInputComponent ()
Destroys the player input component and removes any references to it.
virtual AController * GetDamageInstigator (AController *InstigatedBy, const UDamageType &DamageType) const
Get the controller instigating the damage.
virtual void OnPlayerStateChanged (APlayerState *NewPlayerState, APlayerState *OldPlayerState)
Called on both the clientand server when ever SetPlayerState is called on this pawn.
virtual void SetupPlayerInputComponent (UInputComponent *PlayerInputComponent)
Allows a Pawn to set up custom input bindings.
UPROPERTY () FVector ControlInputVector
Accumulated control input vector, stored in world space.
UPROPERTY () FVector LastControlInputVector
The last control input vector that was processed by ConsumeMovementInputVector().
UPROPERTY () TSubclassOf< UInputComponent > OverrideInputComponentClass
If set, then this InputComponent class will be used instead of the Input Settings' DefaultInputComponentClass.
UPROPERTY () uint16 RemoteViewPitch16
Replicated so we can see where remote clients are looking.
Private Member Functions
virtual GENERATED_BODY() public void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Default UObject constructor.
virtual UPrimitiveComponent * GetMovementBase () const
Return PrimitiveComponent we are based on (standing on, attached to, and moving on).
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker) override
UFUNCTION ()
Return our PawnMovementComponent, if we have one.
UPROPERTY ()) TObjectPtr< APlayerState > PlayerState
If Pawn is possessed by a player, points to its Player State.
Private Attributes
uint32 bInputEnabled:1
If true, this Pawn's pitch will be updated to match the Controller's ControlRotation pitch, if controlled by a PlayerController.
uint32 bProcessingOutsideWorldBounds: 1
Used to prevent re-entry of OutsideWorldBounds event.
Category
Detailed Description
Definition at line 42 of file Pawn.h.
Member Function Documentation
BecomeViewTarget()
virtual void APawn::BecomeViewTarget (APlayerController * PC) override virtual
References BecomeViewTarget().
Referenced by BecomeViewTarget().
BeginPlay()
virtual void APawn::BeginPlay () override virtual
Reimplemented in ACharacter.
References BeginPlay().
Referenced by BeginPlay().
CanBeBaseForCharacter()
virtual bool APawn::CanBeBaseForCharacter (APawn * APawn) const override virtual
Overridden to defer to the RootComponent's CanCharacterStepUpOn setting if it is explicitly Yes or No.
If set to Owner, will return Super::CanBeBaseForCharacter().
References CanBeBaseForCharacter(), and INavAgentInterface::const.
Referenced by CanBeBaseForCharacter().
CreatePlayerInputComponent()
virtual UInputComponent * APawn::CreatePlayerInputComponent () protected virtual
Creates an InputComponent that can be used for custom input bindings.
Called upon possession by a PlayerController. Return null if you don't want one.
References CreatePlayerInputComponent().
Referenced by CreatePlayerInputComponent().
Destroyed()
virtual void APawn::Destroyed () override virtual
References Destroyed().
Referenced by Destroyed().
DestroyPlayerInputComponent()
virtual void APawn::DestroyPlayerInputComponent () protected virtual
Destroys the player input component and removes any references to it.
References DestroyPlayerInputComponent().
Referenced by DestroyPlayerInputComponent().
DisableInput()
virtual void APawn::DisableInput (APlayerController * PlayerController) override virtual
References DisableInput().
Referenced by DisableInput().
DispatchRestart()
void APawn::DispatchRestart (bool bCallClientRestart)
Wrapper function to call correct restart functions, enable bCallClientRestart if this is a locally owned player pawn or equivalent.
References DispatchRestart().
Referenced by DispatchRestart().
DisplayDebug()
virtual void APawn::DisplayDebug (UCanvas * Canvas, const FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) override virtual
Reimplemented in ACharacter.
References INavAgentInterface::const, and DisplayDebug().
Referenced by DisplayDebug().
EditorApplyRotation()
virtual void APawn::EditorApplyRotation (const FRotator & DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override virtual
EnableInput()
virtual void APawn::EnableInput (APlayerController * PlayerController) override virtual
References EnableInput().
Referenced by EnableInput().
EndPlay()
virtual void APawn::EndPlay (const EEndPlayReason::Type EndPlayReason) override virtual
References INavAgentInterface::const, and EndPlay().
Referenced by EndPlay().
EndViewTarget()
virtual void APawn::EndViewTarget (APlayerController * PC) override virtual
References EndViewTarget().
Referenced by EndViewTarget().
FaceRotation()
virtual void APawn::FaceRotation (FRotator NewControlRotation, float DeltaTime = 0.f) virtual
Updates Pawn's rotation to the given rotation, assumed to be the Controller's ControlRotation.
Respects the bUseControllerRotation* settings.
References DeltaTime, and FaceRotation().
Referenced by FaceRotation().
GetActorEyesViewPoint()
virtual void APawn::GetActorEyesViewPoint (FVector & Location, FRotator & Rotation) const override virtual
References INavAgentInterface::const, FVector, GetActorEyesViewPoint(), Location, and Rotation.
Referenced by GetActorEyesViewPoint().
GetController()
template<class T> FORCEINLINE AController * APawn::GetController () const inline
Returns controller for this actor cast to the template type.
May return NULL is the cast fails.
Definition at line 255 of file Pawn.h.
References Cast(), and GetController().
Referenced by GetController(), and UFUNCTION().
GetDamageInstigator()
virtual AController * APawn::GetDamageInstigator (AController * InstigatedBy, const UDamageType & DamageType) const protected virtual
Get the controller instigating the damage.
If the damage is caused by the world and the supplied controller is nullptr or is this pawn's controller, uses LastHitBy as the instigator.
References INavAgentInterface::const, DamageType, and GetDamageInstigator().
Referenced by GetDamageInstigator().
GetDefaultHalfHeight()
virtual float APawn::GetDefaultHalfHeight () const virtual
Returns The half-height of the default Pawn, scaled by the component scale.
By default returns the half-height of the RootComponent, regardless of whether it is registered or collidable.
Reimplemented in ACharacter.
References INavAgentInterface::const, and GetDefaultHalfHeight().
Referenced by GetDefaultHalfHeight().
GetGravityDirection()
virtual FVector APawn::GetGravityDirection () const virtual
Returns vector direction of gravity.
Reimplemented in ACharacter.
References FVector.
GetGravityTransform()
virtual FQuat APawn::GetGravityTransform () const virtual
Returns a quaternion transforming from world space into gravity relative space.
Reimplemented in ACharacter.
GetHumanReadableName()
virtual FString APawn::GetHumanReadableName () const override virtual
References INavAgentInterface::const, and GetHumanReadableName().
Referenced by GetHumanReadableName().
GetLifetimeReplicatedProps()
virtual GENERATED_BODY() public void APawn::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override private virtual
Default UObject constructor.
Reimplemented in ACharacter.
GetMoveGoalReachTest()
virtual void APawn::GetMoveGoalReachTest (const AActor * MovingActor, const FVector & MoveOffset, FVector & GoalOffset, float & GoalRadius, float & GoalHalfHeight) const override virtual
Get cylinder for testing if actor has been reached.
Parameters
MoveOffset - destination (relative to actor's nav location)
GoalOffset - cylinder center (relative to actor's nav location)
GoalRadius - cylinder radius
GoalHalfHeight - cylinder half height
Reimplemented from INavAgentInterface.
References FVector, INavAgentInterface::GoalOffset, INavAgentInterface::GoalRadius, and INavAgentInterface::MoveOffset.
GetMovementBase()
virtual UPrimitiveComponent * APawn::GetMovementBase () const inline private virtual
Return PrimitiveComponent we are based on (standing on, attached to, and moving on).
Reimplemented in ACharacter.
Definition at line 58 of file Pawn.h.
GetNavAgentPropertiesRef()
virtual const FNavAgentProperties & APawn::GetNavAgentPropertiesRef () const override virtual
Reimplemented in AEQSTestingPawn.
GetNetConnection()
virtual class UNetConnection * APawn::GetNetConnection () const override virtual
References INavAgentInterface::const, and GetNetConnection().
Referenced by GetNetConnection().
GetNetOwner()
virtual const AActor * APawn::GetNetOwner () const override virtual
References INavAgentInterface::const, and GetNetOwner().
Referenced by GetNetOwner().
GetNetOwningPlayer()
virtual UPlayer * APawn::GetNetOwningPlayer () override virtual
References GetNetOwningPlayer().
Referenced by GetNetOwningPlayer().
GetNetOwningPlayerAnyRole()
virtual UPlayer * APawn::GetNetOwningPlayerAnyRole () override virtual
References GetNetOwningPlayerAnyRole().
Referenced by GetNetOwningPlayerAnyRole().
GetPawnNoiseEmitterComponent()
virtual UPawnNoiseEmitterComponent * APawn::GetPawnNoiseEmitterComponent () const virtual
Return our PawnNoiseEmitterComponent, if any.
Default implementation returns the first PawnNoiseEmitterComponent found in the components array. If one isn't found, then it tries to find one on the Pawn's current Controller.
References INavAgentInterface::const, and GetPawnNoiseEmitterComponent().
Referenced by GetPawnNoiseEmitterComponent().
GetPawnViewLocation()
virtual FVector APawn::GetPawnViewLocation () const virtual
Returns Pawn's eye location.
References INavAgentInterface::const, FVector, and GetPawnViewLocation().
Referenced by GetPawnViewLocation().
GetPhysicsVolume()
virtual APhysicsVolume * APawn::GetPhysicsVolume () const override virtual
Return Physics Volume for this Pawn.
References INavAgentInterface::const, and GetPhysicsVolume().
Referenced by GetPhysicsVolume().
GetPlayerState() [1/2]
APlayerState * APawn::GetPlayerState () const inline
If Pawn is possessed by a player, returns its Player State.
Needed for network play as controllers are not replicated to clients.
Definition at line 176 of file Pawn.h.
References GetPlayerState().
Referenced by GetPlayerState().
GetPlayerState() [2/2]
template<class T> T * APawn::GetPlayerState () const inline
Templated convenience version of GetPlayerState.
Definition at line 180 of file Pawn.h.
References Cast().
GetPlayerStateChecked()
template<class T> T * APawn::GetPlayerStateChecked () const inline
Templated convenience version of GetPlayerState which checks the type is as presumed.
Definition at line 184 of file Pawn.h.
References CastChecked().
GetRemoteViewPitch()
FORCEINLINE uint16 APawn::GetRemoteViewPitch () const inline
Replicated pitch value so we can see where remote clients are looking.
Definition at line 214 of file Pawn.h.
References FORCEINLINE, and GetRemoteViewPitch().
Referenced by GetRemoteViewPitch().
GetVelocity()
virtual FVector APawn::GetVelocity () const override virtual
References INavAgentInterface::const, FVector, and GetVelocity().
Referenced by GetVelocity().
GetViewRotation()
virtual FRotator APawn::GetViewRotation () const virtual
Get the view rotation of the Pawn (direction they are looking, normally Controller->ControlRotation).
Returns
The view rotation of the Pawn.
References INavAgentInterface::const, and GetViewRotation().
Referenced by GetViewRotation().
InFreeCam()
virtual bool APawn::InFreeCam () const virtual
Returns true if player is viewing this Pawn in FreeCam.
References INavAgentInterface::const, and InFreeCam().
Referenced by InFreeCam().
InputEnabled()
bool APawn::InputEnabled () const inline
Whether this Pawn's input handling is enabled.
Pawn must still be possessed to get input even if this is true
Definition at line 354 of file Pawn.h.
References bInputEnabled.
Internal_AddMovementInput()
void APawn::Internal_AddMovementInput (FVector WorldAccel, bool bForce = false)
Internal function meant for use only within Pawn or by a PawnMovementComponent.
Adds movement input if not ignored, or if forced.
References bForce, FVector, and Internal_AddMovementInput().
Referenced by Internal_AddMovementInput().
Internal_ConsumeMovementInputVector()
FVector APawn::Internal_ConsumeMovementInputVector ()
Internal function meant for use only within Pawn or by a PawnMovementComponent.
LastControlInputVector is updated with initial value of ControlInputVector. Returns ControlInputVector and resets it to zero.
References FVector.
Internal_GetLastMovementInputVector()
FVector APawn::Internal_GetLastMovementInputVector () const inline
Internal function meant for use only within Pawn or by a PawnMovementComponent.
Returns the value of LastControlInputVector.
Definition at line 580 of file Pawn.h.
References FVector.
Internal_GetPendingMovementInputVector()
FVector APawn::Internal_GetPendingMovementInputVector () const inline
Internal function meant for use only within Pawn or by a PawnMovementComponent.
Returns the value of ControlInputVector.
Definition at line 577 of file Pawn.h.
References FVector, and Internal_GetPendingMovementInputVector().
Referenced by Internal_GetPendingMovementInputVector().
IsBasedOnActor()
virtual bool APawn::IsBasedOnActor (const AActor * Other) const override virtual
References INavAgentInterface::const, IsBasedOnActor(), and Other.
Referenced by IsBasedOnActor().
IsLocalPlayerControllerViewingAPawn()
bool APawn::IsLocalPlayerControllerViewingAPawn () const
References INavAgentInterface::const, and IsLocalPlayerControllerViewingAPawn().
Referenced by IsLocalPlayerControllerViewingAPawn().
IsNetRelevantFor()
virtual bool APawn::IsNetRelevantFor (const AActor * RealViewer, const AActor * ViewTarget, const FVector & SrcLocation) const override virtual
References INavAgentInterface::const, FVector, and IsNetRelevantFor().
Referenced by IsNetRelevantFor().
MoveIgnoreActorAdd()
void APawn::MoveIgnoreActorAdd (AActor * ActorToIgnore)
Add an Actor to ignore by Pawn's movement collision.
MoveIgnoreActorRemove()
void APawn::MoveIgnoreActorRemove (AActor * ActorToIgnore)
Remove an Actor to ignore by Pawn's movement collision.
NotifyControllerChanged()
virtual void APawn::NotifyControllerChanged () virtual
Call to notify about a change in controller, on both the server and owning client.
This calls the above event and delegate
References NotifyControllerChanged().
Referenced by NotifyControllerChanged().
NotifyRestarted()
virtual void APawn::NotifyRestarted () virtual
Notifies other systems that a pawn has been restarted.
By default this is called on the server for all pawns and the owning client for player pawns. This can be overridden by subclasses to delay the notification of restart until data has loaded/replicated
References NotifyRestarted().
Referenced by NotifyRestarted().
OnPlayerStateChanged()
virtual void APawn::OnPlayerStateChanged (APlayerState * NewPlayerState, APlayerState * OldPlayerState) inline protected virtual
Called on both the clientand server when ever SetPlayerState is called on this pawn.
Definition at line 188 of file Pawn.h.
OutsideWorldBounds()
virtual void APawn::OutsideWorldBounds () override virtual
References OutsideWorldBounds().
Referenced by OutsideWorldBounds().
PawnClientRestart()
virtual void APawn::PawnClientRestart () virtual
Called on the owning client of a player-controlled Pawn when it is restarted, this calls Restart()
Reimplemented in ACharacter.
References PawnClientRestart().
Referenced by PawnClientRestart().
PawnStartFire()
virtual void APawn::PawnStartFire (uint8 FireModeNum = 0) virtual
Handle StartFire() passed from PlayerController.
References PawnStartFire().
Referenced by PawnStartFire().
PossessedBy()
virtual void APawn::PossessedBy (AController * NewController) virtual
Called when this Pawn is possessed.
Only called on the server (or in standalone).
Parameters
NewController The controller possessing this pawn
Reimplemented in ACharacter.
References NewController.
PostEditChangeProperty()
virtual void APawn::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented in AEQSTestingPawn.
PostInitializeComponents()
virtual void APawn::PostInitializeComponents () override virtual
Reimplemented in ACharacter.
References PostInitializeComponents().
Referenced by PostInitializeComponents().
PostLoad()
virtual void APawn::PostLoad () override virtual
Reimplemented in ACharacter, and AEQSTestingPawn.
References PostLoad().
Referenced by PostLoad().
PostNetReceiveLocationAndRotation()
virtual void APawn::PostNetReceiveLocationAndRotation () override virtual
Reimplemented in ACharacter.
References PostNetReceiveLocationAndRotation().
Referenced by PostNetReceiveLocationAndRotation().
PostNetReceiveVelocity()
virtual void APawn::PostNetReceiveVelocity (const FVector & NewVelocity) override virtual
References INavAgentInterface::const, FVector, and PostNetReceiveVelocity().
Referenced by PostNetReceiveVelocity().
PostRegisterAllComponents()
virtual void APawn::PostRegisterAllComponents () override virtual
References PostRegisterAllComponents().
Referenced by PostRegisterAllComponents().
PreInitializeComponents()
virtual void APawn::PreInitializeComponents () override virtual
References PreInitializeComponents().
Referenced by PreInitializeComponents().
PreReplication()
virtual void APawn::PreReplication (IRepChangedPropertyTracker & ChangedPropertyTracker) override private virtual
Reimplemented in ACharacter.
ReachedDesiredRotation()
virtual bool APawn::ReachedDesiredRotation () virtual
Return true if yaw is within AllowedYawError of desired yaw.
References ReachedDesiredRotation().
Referenced by ReachedDesiredRotation().
RecalculateBaseEyeHeight()
virtual void APawn::RecalculateBaseEyeHeight () virtual
Set BaseEyeHeight based on current state.
Reimplemented in ACharacter.
Reset()
virtual void APawn::Reset () override virtual
Reimplemented in AEQSTestingPawn.
References Reset().
Referenced by Reset().
Restart()
virtual void APawn::Restart () virtual
Called when the Pawn is being restarted (usually by being possessed by a Controller).
This is called on the server for all pawns and the owning client for player pawns
Reimplemented in ACharacter.
References Restart().
Referenced by Restart().
SetController()
void APawn::SetController (AController * InController)
Sets controller for this actor.
SetPlayerDefaults()
virtual void APawn::SetPlayerDefaults () virtual
Make sure pawn properties are back to default.
SetPlayerState()
void APawn::SetPlayerState (APlayerState * NewPlayerState)
Set the Pawn's Player State.
Keeps bi-directional reference of Pawn to Player State and back in sync.
References SetPlayerState().
Referenced by SetPlayerState().
SetRemoteViewPitch()
void APawn::SetRemoteViewPitch (double NewRemoteViewPitch)
Set Pawn ViewPitch, so we can see where remote clients are looking.
Maps 360.0 degrees into 16 bits
Parameters
NewRemoteViewPitch Pitch component to replicate to remote (non owned) clients.
SetupPlayerInputComponent()
virtual void APawn::SetupPlayerInputComponent (UInputComponent * PlayerInputComponent) inline protected virtual
Allows a Pawn to set up custom input bindings.
Called upon possession by a PlayerController, using the InputComponent created by CreatePlayerInputComponent().
Reimplemented in ACharacter.
Definition at line 473 of file Pawn.h.
References SetupPlayerInputComponent().
Referenced by SetupPlayerInputComponent().
ShouldTakeDamage()
virtual bool APawn::ShouldTakeDamage (float Damage, FDamageEvent const & DamageEvent, AController * EventInstigator, AActor * DamageCauser) const virtual
Return true if we are in a state to take damage (checked at the start of TakeDamage.
Subclasses may check this as well if they override TakeDamage and don't want to potentially trigger TakeDamage actions by checking if it returns zero in the super class.
References Damage, and DamageCauser.
ShouldTickIfViewportsOnly()
virtual bool APawn::ShouldTickIfViewportsOnly () const override virtual
References INavAgentInterface::const, and ShouldTickIfViewportsOnly().
Referenced by ShouldTickIfViewportsOnly().
TakeDamage()
virtual float APawn::TakeDamage (float Damage, struct FDamageEvent const & DamageEvent, AController * EventInstigator, AActor * DamageCauser) override virtual
References INavAgentInterface::const, Damage, DamageCauser, and TakeDamage().
Referenced by TakeDamage().
TeleportSucceeded()
virtual void APawn::TeleportSucceeded (bool bIsATest) override virtual
References TeleportSucceeded().
Referenced by TeleportSucceeded().
TurnOff()
virtual void APawn::TurnOff () virtual
Freeze pawn - stop sounds, animations, physics, weapon firing.
Reimplemented in ACharacter.
References TurnOff().
Referenced by TurnOff().
UE_DEPRECATED() [1/3]
APawn::UE_DEPRECATED (4. 24, "IsControlled is deprecated. To check if this pawn is controlled by anything, then call IsPawnControlled. To check if this pawn is controlled only by the player then call IsPlayerControlled") const
See if this actor is currently being controlled.
References Category, INavAgentInterface::const, Pawn, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [2/3]
APawn::UE_DEPRECATED (5. 0, "GetPawnPhysicsVolume is deprecated. Please use GetPhysicsVolume instead.") const
Return Physics Volume for this Pawn.
References INavAgentInterface::const.
UE_DEPRECATED() [3/3]
APawn::UE_DEPRECATED (5. 6, "This property is deprecated, use GetRemoteViewPitch()/RemoteViewPitch16 instead.")
DEPRECTED, use RemoteViewPitch16 instead.
References UPROPERTY().
Referenced by UE_DEPRECATED().
UFUNCTION() [1/32]
APawn::UFUNCTION () private
Return our PawnMovementComponent, if we have one.
By default, returns the first PawnMovementComponent found. Native classes that create their own movement component should override this method for more efficiency.
Referenced by UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/32]
APawn::UFUNCTION () const
Returns local Player Controller viewing this pawn, whether it is controlling or spectating.
References Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [3/32]
APawn::UFUNCTION () const
References Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [4/32]
APawn::UFUNCTION () const
Returns the Platform User ID of the PlayerController that is controlling this character.
Returns an invalid Platform User ID if this character is not controlled by a local player.
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [5/32]
APawn::UFUNCTION () const
Get the rotation of the Controller, often the 'view' rotation of this Pawn.
References Category, and Pawn.
UFUNCTION() [6/32]
APawn::UFUNCTION () const
References Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [7/32]
APawn::UFUNCTION () const
Returns true if controlled by a bot.
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [8/32]
APawn::UFUNCTION () const
Returns true if controlled by a local (not network) Controller.
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [9/32]
APawn::UFUNCTION () const
Helper to see if move input is ignored.
If our controller is a PlayerController, checks Controller->IsMoveInputIgnored().
References Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [10/32]
APawn::UFUNCTION () const
Check if this actor is currently being controlled at all (the actor has a valid Controller, which will be false for remote clients)
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [11/32]
APawn::UFUNCTION () const
Returns true if controlled by a human player (possessed by a PlayerController).
This returns true for players controlled by remote clients
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [12/32]
APawn::UFUNCTION () const
Return the aim rotation for the Pawn.
If we have a controller, by default we aim at the player's 'eyes' direction that is by default the Pawn rotation for AI, and camera (crosshair) rotation for human players.
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [13/32]
APawn::UFUNCTION ()
Called when Controller is replicated.
UFUNCTION() [14/32]
APawn::UFUNCTION ()
PlayerState Replication Notification Callback.
References UFUNCTION().
UFUNCTION() [15/32]
APawn::UFUNCTION ()
Spawn default controller for this Pawn, and get possessed by it.
References Category, Pawn, and UFUNCTION().
UFUNCTION() [16/32]
APawn::UFUNCTION ()
Inform AIControllers that you've made a noise they might hear (they are sent a HearNoise message if they have bHearNoises==true) The instigator of this sound is the pawn which is used to call MakeNoise.
Parameters
Loudness - is the relative loudness of this noise (range 0.0 to 1.0). Directly affects the hearing range specified by the AI's HearingThreshold.
NoiseLocation - Position of noise source. If zero vector, use the actor's location.
bUseNoiseMakerLocation - If true, use the location of the NoiseMaker rather than NoiseLocation. If false, use NoiseLocation.
NoiseMaker - Which actor is the source of the noise. Not to be confused with the Noise Instigator, which is responsible for the noise (and is the pawn on which this function is called). If not specified, the pawn instigating the noise will be used as the NoiseMaker
References AI, Category, and UFUNCTION().
UFUNCTION() [17/32]
APawn::UFUNCTION ()
Event called after a pawn's controller has changed, on the server and owning client.
This will happen at the same time as the delegate on GameInstance
References UFUNCTION().
UFUNCTION() [18/32]
APawn::UFUNCTION ()
Event called after a pawn has been restarted, usually by a possession change.
This is called on the server for all pawns and the owning client for player pawns
References UFUNCTION().
UFUNCTION() [19/32]
APawn::UFUNCTION () const
Returns controller for this actor.
References Category, INavAgentInterface::const, GetController(), Pawn, and UFUNCTION().
UFUNCTION() [20/32]
APawn::UFUNCTION () const
Gets the owning actor of the Movement Base Component on which the pawn is standing.
References Category, INavAgentInterface::const, Pawn, and UFUNCTION().
UFUNCTION() [21/32]
APawn::UFUNCTION () const inline override
Basically retrieved pawn's location on navmesh.
Definition at line 322 of file Pawn.h.
References Category, FVector, INavAgentInterface::GetNavAgentLocation, and Pawn.
UFUNCTION() [22/32]
APawn::UFUNCTION () const
Return the last input vector in world space that was processed by ConsumeMovementInputVector(), which is usually done by the Pawn or PawnMovementComponent.
Any user that needs to know about the input that last affected movement should use this function. For example an animation update would want to use this, since by default the order of updates in a frame is: PlayerController (device input) -> MovementComponent -> Pawn -> Mesh (animations)
Returns
The last input vector in world space that was processed by ConsumeMovementInputVector().
See also
AddMovementInput(), GetPendingMovementInputVector(), ConsumeMovementInputVector()
References Category, INavAgentInterface::const, FVector, Keywords, meta, and UFUNCTION().
UFUNCTION() [23/32]
APawn::UFUNCTION () const
Return the pending input vector in world space.
This is the most up-to-date value of the input vector, pending ConsumeMovementInputVector() which clears it, Usually only a PawnMovementComponent will want to read this value, or the Pawn itself if it is responsible for movement.
Returns
The pending input vector in world space.
See also
AddMovementInput(), GetLastMovementInputVector(), ConsumeMovementInputVector()
References Category, INavAgentInterface::const, FVector, Keywords, meta, and UFUNCTION().
UFUNCTION() [24/32]
APawn::UFUNCTION ()
Returns the pending input vector and resets it to zero.
This should be used during a movement update (by the Pawn or PawnMovementComponent) to prevent accumulation of control input between frames. Copies the pending input vector to the saved input vector (GetLastMovementInputVector()).
Returns
The pending input vector.
References Category, FVector, Keywords, meta, and UFUNCTION().
UFUNCTION() [25/32]
APawn::UFUNCTION ()
Add input (affecting Pitch) to the Controller's ControlRotation, if it is a local PlayerController.
This value is multiplied by the PlayerController's InputPitchScale value.
Parameters
Val Amount to add to Pitch. This value is multiplied by the PlayerController's InputPitchScale value.
See also
PlayerController::InputPitchScale
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [26/32]
APawn::UFUNCTION ()
Add input (affecting Roll) to the Controller's ControlRotation, if it is a local PlayerController.
This value is multiplied by the PlayerController's InputRollScale value.
Parameters
Val Amount to add to Roll. This value is multiplied by the PlayerController's InputRollScale value.
See also
PlayerController::InputRollScale
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [27/32]
APawn::UFUNCTION ()
Add input (affecting Yaw) to the Controller's ControlRotation, if it is a local PlayerController.
This value is multiplied by the PlayerController's InputYawScale value.
Parameters
Val Amount to add to Yaw. This value is multiplied by the PlayerController's InputYawScale value.
See also
PlayerController::InputYawScale
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [28/32]
APawn::UFUNCTION ()
Add movement input along the given world direction vector (usually normalized) scaled by 'ScaleValue'.
If ScaleValue < 0, movement will be in the opposite direction. Base Pawn classes won't automatically apply movement, it's up to the user to do so in a Tick event. Subclasses such as Character and DefaultPawn automatically handle this input and move.
Parameters
WorldDirection Direction in world space to apply input
ScaleValue Scale to apply to input. This can be used for analog input, ie a value of 0.5 applies half the normal value, while -1.0 would reverse the direction.
bForce If true always add the input, ignoring the result of IsMoveInputIgnored().
See also
GetPendingMovementInputVector(), GetLastMovementInputVector(), ConsumeMovementInputVector()
References Category, Keywords, and meta.
UFUNCTION() [29/32]
APawn::UFUNCTION ()
Call this function to detach safely pawn from its controller, knowing that we will be destroyed soon.
References Category, Keywords, meta, Pawn, and UFUNCTION().
UFUNCTION() [30/32]
APawn::UFUNCTION ()
Event called when the Pawn is possessed by a Controller.
Only called on the server (or in standalone)
References meta, and NewController.
UFUNCTION() [31/32]
APawn::UFUNCTION ()
Event called when the Pawn is no longer possessed by a Controller.
Only called on the server (or in standalone)
References meta, and UFUNCTION().
UFUNCTION() [32/32]
APawn::UFUNCTION ()
Use SetCanAffectNavigationGeneration to change this value at runtime.
Note that calling this function at runtime will result in any navigation change only if runtime navigation generation is enabled.
References Category, meta, and UFUNCTION().
UnPossessed()
virtual void APawn::UnPossessed () virtual
Called when our Controller no longer possesses us.
Only called on the server (or in standalone).
Reimplemented in ACharacter.
References UnPossessed().
Referenced by UnPossessed().
UpdateNavAgent()
void APawn::UpdateNavAgent ()
Updates MovementComponent's parameters used by navigation system.
UpdateNavigationRelevance()
virtual void APawn::UpdateNavigationRelevance () inline virtual
Update all components relevant for navigation generators to match bCanAffectNavigationGeneration flag.
Reimplemented in ACharacter.
Definition at line 317 of file Pawn.h.
References UpdateNavigationRelevance().
Referenced by UpdateNavigationRelevance().
UPROPERTY() [1/13]
APawn::UPROPERTY ()
Default class to use when pawn is controlled by AI.
References Category, meta, Pawn, and UPROPERTY().
UPROPERTY() [2/13]
UPROPERTY() TEnumAsByte< EAutoReceiveInput APawn::UPROPERTY ()
Determines which PlayerController, if any, should automatically possess the pawn when the level starts or when the pawn is spawned.
See also
AutoPossessAI Determines when the Pawn creates and is possessed by an AI Controller (on level start, when spawned, etc). Only possible if AIControllerClassRef is set, and ignored if AutoPossessPlayer is enabled.
AutoPossessPlayer
References Category, and Pawn.
UPROPERTY() [3/13]
APawn::UPROPERTY ()
Base eye height above collision center.
References Camera, Category, and Pawn.
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/13]
APawn::UPROPERTY ()
Event called after a pawn's controller has changed, on the server and owning client.
This will happen at the same time as the delegate on GameInstance
References Category, Pawn, and UPROPERTY().
UPROPERTY() [5/13]
APawn::UPROPERTY ()
Event called after a pawn has been restarted, usually by a possession change.
This is called on the server for all pawns and the owning client for player pawns
References Category, Pawn, and UPROPERTY().
UPROPERTY() [6/13]
APawn::UPROPERTY () protected
Accumulated control input vector, stored in world space.
This is the pending input, which is cleared (zeroed) once consumed.
See also
GetPendingMovementInputVector(), AddMovementInput()
References FVector, Transient, and UPROPERTY().
UPROPERTY() [7/13]
APawn::UPROPERTY () protected
The last control input vector that was processed by ConsumeMovementInputVector().
See also
GetLastMovementInputVector()
References FVector, Transient, and UPROPERTY().
UPROPERTY() [8/13]
APawn::UPROPERTY ()
Controller currently possessing this Actor.
References UPROPERTY().
UPROPERTY() [9/13]
APawn::UPROPERTY ()
Controller of the last Actor that caused us damage.
References Category, and transient.
UPROPERTY() [10/13]
APawn::UPROPERTY ()
Previous controller that was controlling this pawn since the last controller change notification.
References transient, and UPROPERTY().
UPROPERTY() [11/13]
APawn::UPROPERTY () protected
If set, then this InputComponent class will be used instead of the Input Settings' DefaultInputComponentClass.
References Category, and UPROPERTY().
UPROPERTY() [12/13]
APawn::UPROPERTY () protected
Replicated so we can see where remote clients are looking.
UPROPERTY() [13/13]
APawn::UPROPERTY () private
If Pawn is possessed by a player, points to its Player State.
Needed for network play as controllers are not replicated to clients.
References Category, meta, Pawn, and UPROPERTY().
Field Documentation
AllowedYawError
float APawn::AllowedYawError
Max difference between pawn's Rotation.Yaw and GetDesiredRotation().Yaw for pawn to be considered as having reached its desired rotation.
Definition at line 205 of file Pawn.h.
bForce
float bool APawn::bForce = false)
Definition at line 486 of file Pawn.h.
Referenced by Internal_AddMovementInput().
bForceUpdate
bool APawn::bForceUpdate = false)
Definition at line 314 of file Pawn.h.
bInputEnabled
uint32 APawn::bInputEnabled private
If true, this Pawn's pitch will be updated to match the Controller's ControlRotation pitch, if controlled by a PlayerController.
If true, this Pawn's yaw will be updated to match the Controller's ControlRotation yaw, if controlled by a PlayerController. If true, this Pawn's roll will be updated to match the Controller's ControlRotation roll, if controlled by a PlayerController. If set to false (default) given pawn instance will never affect navigation generation (but components could). Setting it to true will result in using regular AActor's navigation relevancy calculation to check if this pawn instance should affect navigation generation.
Note
Use SetCanAffectNavigationGeneration() to change this value at runtime.
Modifying this value at runtime will result in any navigation change only if runtime navigation generation is enabled.
Override UpdateNavigationRelevance() to propagate the flag to the desired components.
See also
SetCanAffectNavigationGeneration(), UpdateNavigationRelevance() Whether this Pawn's input handling is enabled. Pawn must still be possessed to get input even if this is true
Definition at line 86 of file Pawn.h.
Referenced by InputEnabled().
bProcessingOutsideWorldBounds
uint32 APawn::bProcessingOutsideWorldBounds private
Used to prevent re-entry of OutsideWorldBounds event.
Definition at line 89 of file Pawn.h.
bUseNoiseMakerLocation
FVector bool APawn::bUseNoiseMakerLocation = true
Definition at line 147 of file Pawn.h.
Category
APawn::Category private
Initial value:
=Pawn)
    1 virtual UPawnMovementComponent* GetMovementComponent() const
Definition at line 54 of file Pawn.h.
Referenced by AEQSTestingPawn::GENERATED_UCLASS_BODY(), UE_DEPRECATED(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), AEQSTestingPawn::UPROPERTY(), AEQSTestingPawn::UPROPERTY(), AEQSTestingPawn::UPROPERTY(), AEQSTestingPawn::UPROPERTY(), AEQSTestingPawn::UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
NewController
AController* APawn::NewController
Definition at line 377 of file Pawn.h.
Referenced by ACharacter::PossessedBy(), PossessedBy(), and UFUNCTION().
NoiseLocation
FVector APawn::NoiseLocation
Definition at line 147 of file Pawn.h.
NoiseMaker
FVector bool AActor* APawn::NoiseMaker = nullptr)
Definition at line 147 of file Pawn.h.
OnPawnBeginPlay
FOnPawnBeginPlay APawn::OnPawnBeginPlay static
a delegate that broadcasts a notification whenever BeginPlay() is called
Definition at line 163 of file Pawn.h.
ScaleValue
float APawn::ScaleValue = 1.0f
Definition at line 486 of file Pawn.h.
The documentation for this class was generated from the following file:
Pawn.h