Unreal Engine 5.6 C++ API: FCoreTexts Struct Reference
FCoreTexts Struct Reference
#include "CoreGlobals.h"
Public Member Functions
FCoreTexts (const FCoreTexts &)=delete
FCoreTexts (const FText &InTrue, const FText &InFalse, const FText &InYes, const FText &InNo, const FText &InNone)
FCoreTexts & operator= (const FCoreTexts &)=delete
Static Public Member Functions
static const FCoreTexts & Get ()
static void TearDown ()
Invalidates existing references.
Data Fields
const FText & False
const FText & No
const FText & None
const FText & True
const FText & Yes
Detailed Description
Definition at line 108 of file CoreGlobals.h.
Constructor & Destructor Documentation
FCoreTexts() [1/2]
FCoreTexts::FCoreTexts (const FCoreTexts &) delete
References FCoreTexts().
Referenced by FCoreTexts(), Get(), and operator=().
FCoreTexts() [2/2]
FCoreTexts::FCoreTexts (const FText & InTrue, const FText & InFalse, const FText & InYes, const FText & InNo, const FText & InNone) inline
Definition at line 125 of file CoreGlobals.h.
References False, No, None, True, and Yes.
Member Function Documentation
Get()
const FCoreTexts & FCoreTexts::Get () static
References FCoreTexts().
operator=()
FCoreTexts & FCoreTexts::operator= (const FCoreTexts &) delete
References FCoreTexts().
TearDown()
void FCoreTexts::TearDown () static
Invalidates existing references.
Do not use FCoreTexts after calling.
Field Documentation
False
const FText& FCoreTexts::False
Definition at line 111 of file CoreGlobals.h.
Referenced by FCoreTexts().
No
const FText& FCoreTexts::No
Definition at line 113 of file CoreGlobals.h.
Referenced by FCoreTexts().
None
const FText& FCoreTexts::None
Definition at line 114 of file CoreGlobals.h.
Referenced by FCoreTexts().
True
const FText& FCoreTexts::True
Definition at line 110 of file CoreGlobals.h.
Referenced by FCoreTexts().
Yes
const FText& FCoreTexts::Yes
Definition at line 112 of file CoreGlobals.h.
Referenced by FCoreTexts().
The documentation for this struct was generated from the following file:
CoreGlobals.h