Unreal Engine 5.6 C++ API: UE::ConfigAccessTracking::FConfigAccessData Struct Reference
UE::ConfigAccessTracking::FConfigAccessData Struct Reference
Full path of a read of an FConfigValue; used to persistently track which config values were read during an invocation of the editor.
#include "ConfigAccessData.h"
Public Member Functions
FConfigAccessData ()=default
FConfigAccessData (ELoadType InLoadType, FName InConfigPlatform, FName InFileName, FName InSectionName, FName InValueName, const ITargetPlatform *InRequestingPlatform)
FConfigAccessData (ELoadType InLoadType, FNameEntryId InConfigPlatform, FNameEntryId InFileName)
FConfigAccessData (ELoadType InLoadType, FNameEntryId InConfigPlatform, FNameEntryId InFileName, FNameEntryId InSectionName, FMinimalName InValueName, const ITargetPlatform *InRequestingPlatform)
void AppendFullPath (FStringBuilderBase &Out) const
FString FullPathToString () const
FName GetConfigPlatform () const
FName GetFileName () const
FConfigAccessData GetFileOnlyData () const
FConfigAccessData GetPathOnlyData () const
FName GetSectionName () const
FName GetValueName () const
bool IsSameConfigFile (const FConfigAccessData &Other) const
bool operator!= (const FConfigAccessData &Other) const
bool operator< (const FConfigAccessData &Other) const
bool operator== (const FConfigAccessData &Other) const
Static Public Member Functions
static FConfigAccessData Parse (FStringView Text)
"ConfigSystem.<Editor>.../../../Engine/Config/ConsoleVariables.ini:[Section]:Value" -> "ConfigSystem", "<Editor>", "../../../Engine/Config/ConsoleVariables.ini", "Section", "Value"
Data Fields
FNameEntryId ConfigPlatform
FNameEntryId FileName
ELoadType LoadType = ELoadType::Uninitialized
const ITargetPlatform * RequestingPlatform = nullptr
FNameEntryId SectionName
FMinimalName ValueName
Friends
uint32 GetTypeHash (const FConfigAccessData &Data)
Detailed Description
Full path of a read of an FConfigValue; used to persistently track which config values were read during an invocation of the editor.
Definition at line 22 of file ConfigAccessData.h.
Constructor & Destructor Documentation
FConfigAccessData() [1/4]
UE::ConfigAccessTracking::FConfigAccessData::FConfigAccessData () default
Referenced by FConfigAccessData(), GetFileOnlyData(), GetPathOnlyData(), IsSameConfigFile(), operator!=(), operator<(), operator==(), and Parse().
FConfigAccessData() [2/4]
UE::ConfigAccessTracking::FConfigAccessData::FConfigAccessData (ELoadType InLoadType, FName InConfigPlatform, FName InFileName, FName InSectionName, FName InValueName, const ITargetPlatform * InRequestingPlatform) inline
Definition at line 82 of file ConfigAccessData.h.
References FConfigAccessData().
FConfigAccessData() [3/4]
UE::ConfigAccessTracking::FConfigAccessData::FConfigAccessData (ELoadType InLoadType, FNameEntryId InConfigPlatform, FNameEntryId InFileName, FNameEntryId InSectionName, FMinimalName InValueName, const ITargetPlatform * InRequestingPlatform)
FConfigAccessData() [4/4]
UE::ConfigAccessTracking::FConfigAccessData::FConfigAccessData (ELoadType InLoadType, FNameEntryId InConfigPlatform, FNameEntryId InFileName)
Member Function Documentation
AppendFullPath()
void UE::ConfigAccessTracking::FConfigAccessData::AppendFullPath (FStringBuilderBase & Out) const
FullPathToString()
FString UE::ConfigAccessTracking::FConfigAccessData::FullPathToString () const
GetConfigPlatform()
FName UE::ConfigAccessTracking::FConfigAccessData::GetConfigPlatform () const inline
Definition at line 89 of file ConfigAccessData.h.
References ConfigPlatform, FName, and NAME_NO_NUMBER_INTERNAL.
GetFileName()
FName UE::ConfigAccessTracking::FConfigAccessData::GetFileName () const inline
Definition at line 94 of file ConfigAccessData.h.
References FileName, FName, and NAME_NO_NUMBER_INTERNAL.
GetFileOnlyData()
FConfigAccessData UE::ConfigAccessTracking::FConfigAccessData::GetFileOnlyData () const
References FConfigAccessData().
GetPathOnlyData()
FConfigAccessData UE::ConfigAccessTracking::FConfigAccessData::GetPathOnlyData () const
References FConfigAccessData().
GetSectionName()
FName UE::ConfigAccessTracking::FConfigAccessData::GetSectionName () const inline
Definition at line 99 of file ConfigAccessData.h.
References FName, NAME_NO_NUMBER_INTERNAL, and SectionName.
GetValueName()
FName UE::ConfigAccessTracking::FConfigAccessData::GetValueName () const inline
Definition at line 104 of file ConfigAccessData.h.
References FName, and ValueName.
IsSameConfigFile()
bool UE::ConfigAccessTracking::FConfigAccessData::IsSameConfigFile (const FConfigAccessData & Other) const inline
Definition at line 120 of file ConfigAccessData.h.
References FConfigAccessData(), ConfigPlatform, FileName, LoadType, and Other.
operator!=()
bool UE::ConfigAccessTracking::FConfigAccessData::operator!= (const FConfigAccessData & Other) const inline
Definition at line 132 of file ConfigAccessData.h.
References FConfigAccessData(), and Other.
operator<()
bool UE::ConfigAccessTracking::FConfigAccessData::operator< (const FConfigAccessData & Other) const inline
Definition at line 137 of file ConfigAccessData.h.
References FConfigAccessData(), ConfigPlatform, FileName, FName, LoadType, Other, RequestingPlatform, SectionName, and ValueName.
operator==()
bool UE::ConfigAccessTracking::FConfigAccessData::operator== (const FConfigAccessData & Other) const inline
Definition at line 125 of file ConfigAccessData.h.
References FConfigAccessData(), ConfigPlatform, FileName, LoadType, Other, RequestingPlatform, SectionName, and ValueName.
Parse()
FConfigAccessData UE::ConfigAccessTracking::FConfigAccessData::Parse (FStringView Text) static
"ConfigSystem.<Editor>.../../../Engine/Config/ConsoleVariables.ini:[Section]:Value" -> "ConfigSystem", "<Editor>", "../../../Engine/Config/ConsoleVariables.ini", "Section", "Value"
References FConfigAccessData(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FConfigAccessData & Data) friend
Definition at line 109 of file ConfigAccessData.h.
References ConfigPlatform, FileName, UE::ConfigAccessTracking::GetTypeHash(), Hash, HashCombineFast(), LoadType, RequestingPlatform, SectionName, FNameEntryId::ToUnstableInt(), and ValueName.
Field Documentation
ConfigPlatform
FNameEntryId UE::ConfigAccessTracking::FConfigAccessData::ConfigPlatform
Definition at line 24 of file ConfigAccessData.h.
Referenced by GetConfigPlatform(), GetTypeHash, IsSameConfigFile(), operator<(), and operator==().
FileName
FNameEntryId UE::ConfigAccessTracking::FConfigAccessData::FileName
Definition at line 25 of file ConfigAccessData.h.
Referenced by GetFileName(), GetTypeHash, IsSameConfigFile(), operator<(), and operator==().
LoadType
ELoadType UE::ConfigAccessTracking::FConfigAccessData::LoadType = ELoadType::Uninitialized
Definition at line 29 of file ConfigAccessData.h.
Referenced by GetTypeHash, IsSameConfigFile(), operator<(), and operator==().
RequestingPlatform
const ITargetPlatform* UE::ConfigAccessTracking::FConfigAccessData::RequestingPlatform = nullptr
Definition at line 28 of file ConfigAccessData.h.
Referenced by GetTypeHash, operator<(), and operator==().
SectionName
FNameEntryId UE::ConfigAccessTracking::FConfigAccessData::SectionName
Definition at line 26 of file ConfigAccessData.h.
Referenced by GetSectionName(), GetTypeHash, operator<(), and operator==().
ValueName
FMinimalName UE::ConfigAccessTracking::FConfigAccessData::ValueName
Definition at line 27 of file ConfigAccessData.h.
Referenced by GetTypeHash, GetValueName(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
ConfigAccessData.h