Unreal Engine 5.6 C++ API: Metasound::VertexDataPrivate Namespace Reference
Metasound::VertexDataPrivate Namespace Reference
Data Structures
class FInputBinding
class FOutputBinding
struct TCreateInputBinding
struct TCreateOutputBinding
struct TFactoryFacade
TFactoryFacace is a factory for data types which uses the class template type to determine which flavor of DataReference to create.
struct TFactoryFacade< TDataReadReference< DataType > >
struct TFactoryFacade< TDataValueReference< DataType > >
struct TFactoryFacade< TDataWriteReference< DataType > >
struct TGetReferenceDataTypeT
TGetReferencDataTypeT is a template trait which determines the underlying type stored in a data reference.
struct TGetReferenceDataTypeT< TDataReadReference< DataType > >
struct TGetReferenceDataTypeT< TDataValueReference< DataType > >
struct TGetReferenceDataTypeT< TDataWriteReference< DataType > >
struct TGetVertexAccess
struct TGetVertexAccess< TDataReadReference< DataType > >
struct TGetVertexAccess< TDataValueReference< DataType > >
struct TGetVertexAccess< TDataWriteReference< DataType > >
struct TTriggerDeprecatedBindAPIWarning
struct TTriggerDeprecatedBindAPIWarning< const T >
Typedefs
template<typename T>
using TGetReferenceDataType = typename TGetReferenceDataTypeT<T>::Type
TGetReferencDataType is the underlying type stored in a data reference.
Functions
FORCEINLINE void CheckAccessTypeCompatibility (const FDataVertex &InDataVertex, const FAnyDataReference &InDataReference)
METASOUNDGRAPHCORE_API EVertexAccessType DataReferenceAccessTypeToVertexAccessType (EDataReferenceAccessType InReferenceAccessType)
Typedef Documentation
TGetReferenceDataType
template<typename T> using Metasound::VertexDataPrivate::TGetReferenceDataType = typename TGetReferenceDataTypeT<T>::Type
TGetReferencDataType is the underlying type stored in a data reference.
Definition at line 91 of file MetasoundVertexData.h.
Function Documentation
CheckAccessTypeCompatibility()
FORCEINLINE void Metasound::VertexDataPrivate::CheckAccessTypeCompatibility (const FDataVertex & InDataVertex, const FAnyDataReference & InDataReference)
Definition at line 33 of file MetasoundVertexData.h.
References FORCEINLINE.
Referenced by Metasound::VertexDataPrivate::FInputBinding::Set(), Metasound::VertexDataPrivate::FOutputBinding::Set(), Metasound::VertexDataPrivate::FInputBinding::SetValue(), and Metasound::VertexDataPrivate::FOutputBinding::SetValue().
DataReferenceAccessTypeToVertexAccessType()
METASOUNDGRAPHCORE_API EVertexAccessType Metasound::VertexDataPrivate::DataReferenceAccessTypeToVertexAccessType (EDataReferenceAccessType InReferenceAccessType)