Unreal Engine 5.6 C++ API: TRDGLambdaPass< ParameterStructType, ExecuteLambdaType > Class Template Reference
TRDGLambdaPass< ParameterStructType, ExecuteLambdaType > Class Template Reference
Render graph pass with lambda execute function.
#include "RenderGraphPass.h"
Data Structures
class ExecuteLambdaTraits
Public Member Functions
TRDGLambdaPass (FRDGEventName &&InName, const FShaderParametersMetadata *InParameterMetadata, const ParameterStructType *InParameterStruct, ERDGPassFlags InPassFlags, ExecuteLambdaType &&InExecuteLambda)
Public Member Functions inherited from FRDGPass
FRDGPass (const FRDGPass &)=delete
RENDERCORE_API FRDGPass (FRDGEventName &&InName, FRDGParameterStruct InParameterStruct, ERDGPassFlags InFlags, ERDGPassTaskMode InTaskMode)
virtual ~FRDGPass ()=default
const FRDGEventName & GetEventName () const
ERDGPassFlags GetFlags () const
FRHIGPUMask GetGPUMask () const
FRDGPassHandle GetGraphicsForkPass () const
Returns the graphics pass responsible for forking the async interval this pass is in.
FRDGPassHandle GetGraphicsJoinPass () const
Returns the graphics pass responsible for joining the async interval this pass is in.
FRDGPassHandle GetHandle () const
RENDERCORE_API const TCHAR * GetName () const
FRDGParameterStruct GetParameters () const
ERHIPipeline GetPipeline () const
FRDGScope const * GetScope () const
ERDGPassTaskMode GetTaskMode () const
uint32 GetWorkload () const
bool IsAsyncCompute () const
bool IsAsyncComputeBegin () const
bool IsAsyncComputeEnd () const
bool IsCulled () const
bool IsGraphicsFork () const
bool IsGraphicsJoin () const
bool IsMergedRenderPassBegin () const
bool IsMergedRenderPassEnd () const
bool IsParallelExecuteAllowed () const
bool IsSentinel () const
bool SkipRenderPassBegin () const
bool SkipRenderPassEnd () const
Private Member Functions
void Execute (FRHIComputeCommandList &RHICmdList) override
void ExecuteLambdaFunc (FRHIComputeCommandList &RHICmdList)
Private Attributes
const ParameterStructType * DebugParameterStruct
ExecuteLambdaType ExecuteLambda
Additional Inherited Members
Protected Member Functions inherited from FRDGPass
FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginFor (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue, ERHIPipeline PipelineForEnd)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForAll (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForAsyncCompute (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForGraphics (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchEnd & GetEpilogueBarriersToEnd (FRDGAllocator &Allocator)
RENDERCORE_API FRDGBarrierBatchBegin & GetPrologueBarriersToBegin (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchEnd & GetPrologueBarriersToEnd (FRDGAllocator &Allocator)
virtual void LaunchDispatchPassTasks (FRDGDispatchPassBuilder &DispatchPassBuilder)
Protected Attributes inherited from FRDGPass
union {
struct {
uint8 bCulled: 1
Whether this pass has been culled.
uint8 bEmptyParameters: 1
Whether this pass does not contain parameters.
uint8 bExternalAccessPass: 1
Whether this pass is used for external access transitions.
uint8 bHasExternalOutputs: 1
Whether this pass has external UAVs that are not tracked by RDG.
}
uint8 PacketBits_AsyncSetupQueue = 0
};
union {
struct {
uint16 bAsyncComputeBegin: 1
(AsyncCompute only) Whether this is the first / last async compute pass in an async interval.
uint16 bAsyncComputeEnd: 1
uint16 bDispatchAfterExecute: 1
If set, dispatches to the RHI thread after executing this pass.
uint16 bDispatchPass: 1
If set, this is a dispatch pass.
uint16 bGraphicsFork: 1
(Graphics only) Whether this is a graphics fork / join pass.
uint16 bGraphicsJoin: 1
uint16 bRenderPassOnlyWrites: 1
Whether the pass only writes to resources in its render pass.
uint16 bSentinel: 1
Whether this pass is a sentinel (prologue / epilogue) pass.
uint16 bSkipRenderPassBegin: 1
Whether the render pass begin / end should be skipped.
uint16 bSkipRenderPassEnd: 1
}
uint16 PackedBits = 0
};
union {
struct {
uint8 bParallelExecute: 1
If set, marks that a pass is executing in parallel.
uint8 bParallelExecuteBegin: 1
If set, marks the begin / end of a span of passes executed in parallel in a task.
uint8 bParallelExecuteEnd: 1
}
uint8 PacketBits_ParallelExecute = 0
};
TArray< FBufferState, FRDGArrayAllocator > BufferStates
TArray< FRDGPassHandle, FRDGArrayAllocator > CrossPipelineConsumers
Lists of producer passes and the full list of cross-pipeline consumer passes.
FRDGPassHandle CrossPipelineProducer
Handle of the latest cross-pipeline producer.
FRDGPassHandle EpilogueBarrierPass
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForAll = nullptr
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForAsyncCompute = nullptr
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForGraphics = nullptr
FRDGBarrierBatchEnd * EpilogueBarriersToEnd = nullptr
TArray< FExternalAccessOp, FRDGArrayAllocator > ExternalAccessOps
const ERDGPassFlags Flags
friend FRDGBuilder
friend FRDGDispatchPassBuilder
friend FRDGPassRegistry
friend FRDGTrace
friend FRDGUserValidation
FString FullPathIfDebug
FRDGPassHandle GraphicsForkPass
(AsyncCompute only) Graphics passes which are the fork / join for async compute interval this pass is in.
FRDGPassHandle GraphicsJoinPass
FRDGPassHandle Handle
const FRDGEventName Name
uint32 NumTransitionsToReserve = 0
Number of transitions to reserve.
uint32 ParallelPassSetIndex = 0
const FRDGParameterStruct ParameterStruct
const ERHIPipeline Pipeline
TArray< FRDGPass *, FRDGArrayAllocator > Producers
FRDGPassHandle PrologueBarrierPass
The passes which are handling the epilogue / prologue barriers meant for this pass.
FRDGBarrierBatchBegin * PrologueBarriersToBegin = nullptr
Split-barrier batches at various points of execution of the pass.
FRDGBarrierBatchEnd * PrologueBarriersToEnd = nullptr
TArray< FRDGPass *, TInlineAllocator< 1, FRDGArrayAllocator > > ResourcesToBegin
Lists of pass parameters scheduled for begin during execution of this pass.
TArray< FRDGPass *, TInlineAllocator< 1, FRDGArrayAllocator > > ResourcesToEnd
FRDGScope * Scope = nullptr
TArray< FRDGBarrierBatchBegin *, FRDGArrayAllocator > SharedEpilogueBarriersToBegin
const ERDGPassTaskMode TaskMode
TArray< FTextureState, FRDGArrayAllocator > TextureStates
Maps textures / buffers to information on how they are used in the pass.
TArray< FRDGUniformBufferHandle, FRDGArrayAllocator > UniformBuffers
TArray< FRDGViewHandle, FRDGArrayAllocator > Views
uint32 Workload = 1
Detailed Description
template<typename ParameterStructType, typename ExecuteLambdaType>
class TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >
Render graph pass with lambda execute function.
Definition at line 567 of file RenderGraphPass.h.
Constructor & Destructor Documentation
TRDGLambdaPass()
template<typename ParameterStructType, typename ExecuteLambdaType> TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::TRDGLambdaPass (FRDGEventName && InName, const FShaderParametersMetadata * InParameterMetadata, const ParameterStructType * InParameterStruct, ERDGPassFlags InPassFlags, ExecuteLambdaType && InExecuteLambda) inline
Definition at line 654 of file RenderGraphPass.h.
References FRDGPass::FRDGPass(), DebugParameterStruct, ExecuteLambda, InName, MoveTemp(), RDG_ENABLE_DEBUG, and FRDGPass::TaskMode.
Member Function Documentation
Execute()
template<typename ParameterStructType, typename ExecuteLambdaType> void TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::Execute (FRHIComputeCommandList & RHICmdList) inline override private virtual
Reimplemented from FRDGPass.
Definition at line 694 of file RenderGraphPass.h.
References checkNoEntry, DECLARE_CYCLE_STAT_WITH_FLAGS, ExecuteLambdaFunc(), FRDGPass::ParameterStruct, SCOPE_CYCLE_COUNTER, TEXT, and Verbose.
ExecuteLambdaFunc()
template<typename ParameterStructType, typename ExecuteLambdaType> void TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::ExecuteLambdaFunc (FRHIComputeCommandList & RHICmdList) inline private
Definition at line 668 of file RenderGraphPass.h.
References Async, TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::ExecuteLambdaTraits::bIsPassArgValid, ExecuteLambda, and TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::ExecuteLambdaTraits::TaskMode.
Referenced by Execute().
Field Documentation
DebugParameterStruct
template<typename ParameterStructType, typename ExecuteLambdaType> const ParameterStructType* TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::DebugParameterStruct private
Definition at line 709 of file RenderGraphPass.h.
Referenced by TRDGLambdaPass().
ExecuteLambda
template<typename ParameterStructType, typename ExecuteLambdaType> ExecuteLambdaType TRDGLambdaPass< ParameterStructType, ExecuteLambdaType >::ExecuteLambda private
Definition at line 707 of file RenderGraphPass.h.
Referenced by TRDGLambdaPass(), and ExecuteLambdaFunc().
The documentation for this class was generated from the following file:
RenderGraphPass.h