Unreal Engine 5.6 C++ API: FWaterSplineDataPhysics Struct Reference
FWaterSplineDataPhysics Struct Reference
#include "WaterBodyTypes.h"
Public Member Functions
FWaterSplineDataPhysics ()
FWaterSplineDataPhysics (UWaterSplineComponent *WaterSplineComponent)
WATER_API float FindInputKeyClosestToWorldLocation (const FVector &WorldLocation) const
WATER_API FVector GetDirectionAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace=ESplineCoordinateSpace::World) const
WATER_API FVector GetLocationAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace=ESplineCoordinateSpace::World) const
FQuat GetQuaternionAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace=ESplineCoordinateSpace::World) const
FVector GetUpVectorAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace=ESplineCoordinateSpace::World) const
FWaterSplineDataPhysics & operator= (const UWaterSplineComponent *WaterSplineComponent)
Data Fields
FTransform ComponentTransform
FVector DefaultUpVector
FSplineCurves SplineCurves
Detailed Description
Definition at line 149 of file WaterBodyTypes.h.
Constructor & Destructor Documentation
FWaterSplineDataPhysics() [1/2]
FWaterSplineDataPhysics::FWaterSplineDataPhysics () inline
Definition at line 155 of file WaterBodyTypes.h.
Referenced by operator=().
FWaterSplineDataPhysics() [2/2]
FWaterSplineDataPhysics::FWaterSplineDataPhysics (UWaterSplineComponent * WaterSplineComponent)
Member Function Documentation
FindInputKeyClosestToWorldLocation()
WATER_API float FWaterSplineDataPhysics::FindInputKeyClosestToWorldLocation (const FVector & WorldLocation) const
References FVector.
GetDirectionAtSplineInputKey()
WATER_API FVector FWaterSplineDataPhysics::GetDirectionAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace = ESplineCoordinateSpace::World) const
References FVector.
GetLocationAtSplineInputKey()
WATER_API FVector FWaterSplineDataPhysics::GetLocationAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace = ESplineCoordinateSpace::World) const
References FVector.
Referenced by FBuoyancyComponentSim::ComputeWaterForce().
GetQuaternionAtSplineInputKey()
FQuat FWaterSplineDataPhysics::GetQuaternionAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace = ESplineCoordinateSpace::World) const
GetUpVectorAtSplineInputKey()
FVector FWaterSplineDataPhysics::GetUpVectorAtSplineInputKey (float InKey, ESplineCoordinateSpace::Type CoordinateSpace = ESplineCoordinateSpace::World) const
References FVector.
operator=()
FWaterSplineDataPhysics & FWaterSplineDataPhysics::operator= (const UWaterSplineComponent * WaterSplineComponent)
References FWaterSplineDataPhysics().
Field Documentation
ComponentTransform
FTransform FWaterSplineDataPhysics::ComponentTransform
Definition at line 151 of file WaterBodyTypes.h.
DefaultUpVector
FVector FWaterSplineDataPhysics::DefaultUpVector
Definition at line 153 of file WaterBodyTypes.h.
SplineCurves
FSplineCurves FWaterSplineDataPhysics::SplineCurves
Definition at line 152 of file WaterBodyTypes.h.
The documentation for this struct was generated from the following file:
WaterBodyTypes.h