Unreal Engine 5.6 C++ API: FConvexVolume Struct Reference
FConvexVolume Struct Reference
#include "ConvexVolume.h"
Public Types
typedef TArray< FPlane, TInlineAllocator< 8 > > FPermutedPlaneArray
typedef TArray< FPlane, TInlineAllocator< 6 > > FPlaneArray
Public Member Functions
FConvexVolume ()
FConvexVolume (const TArray< FPlane, TInlineAllocator< 6 > > &InPlanes)
Builds the set of planes used to clip against.
bool ClipPolygon (class FPoly &Polygon) const
Clips a polygon to the volume.
float DistanceTo (const FVector &Point) const
Calculates the maximum perpendicular distance of a point to the plains of the convex volume.
FOutcode GetBoxIntersectionOutcode (const FVector &Origin, const FVector &Extent) const
void Init (void)
Builds the permuted planes for SSE/Altivec fast clipping.
bool IntersectBox (const FVector &Origin, const FVector &Extent) const
Intersection test with a translated axis-aligned box.
bool IntersectBox (const FVector &Origin, const FVector &Extent, bool &bOutFullyContained) const
Intersection test with a translated axis-aligned box.
bool IntersectBox (const FVector &Origin, const FVector &Translation, const FVector &Extent) const
Intersection test with a translated axis-aligned box.
bool IntersectLineSegment (const FVector &Start, const FVector &End) const
Intersection test with line segment.
bool IntersectPoint (const FVector &Point) const
Determines whether the given point lies inside the convex volume.
bool IntersectSphere (const FVector &Origin, const float &Radius) const
Intersection test with a sphere.
bool IntersectSphere (const FVector &Origin, const float &Radius, bool &bOutFullyContained) const
Intersection test with a sphere.
bool IntersectTriangle (const FVector &PointA, const FVector &PointB, const FVector &PointC, bool &bOutFullyContained) const
Intersection test with a triangle param bOutFullyContained to know if the triangle was fully contained.
Data Fields
FPermutedPlaneArray PermutedPlanes
This is the set of planes pre-permuted to SSE/Altivec form.
FPlaneArray Planes
Friends
FArchive & operator<< (FArchive &Ar, FConvexVolume &ConvexVolume)
Serializer.
Detailed Description
Definition at line 43 of file ConvexVolume.h.
Member Typedef Documentation
FPermutedPlaneArray
typedef TArray<FPlane,TInlineAllocator<8> > FConvexVolume::FPermutedPlaneArray
Definition at line 48 of file ConvexVolume.h.
FPlaneArray
typedef TArray<FPlane,TInlineAllocator<6> > FConvexVolume::FPlaneArray
Definition at line 47 of file ConvexVolume.h.
Constructor & Destructor Documentation
FConvexVolume() [1/2]
FConvexVolume::FConvexVolume () inline
Definition at line 54 of file ConvexVolume.h.
Referenced by operator<<.
FConvexVolume() [2/2]
FConvexVolume::FConvexVolume (const TArray< FPlane, TInlineAllocator< 6 > > & InPlanes) inline
Builds the set of planes used to clip against.
Also, puts the planes into a form more readily used by SSE/Altivec so 4 planes can be clipped against at once.
Definition at line 64 of file ConvexVolume.h.
References Init(), and Planes.
Member Function Documentation
ClipPolygon()
bool FConvexVolume::ClipPolygon (class FPoly & Polygon) const
Clips a polygon to the volume.
Parameters
Polygon - The polygon to be clipped. If the true is returned, contains the clipped polygon.
Returns
Returns false if the polygon is entirely outside the volume and true otherwise.
References Polygon.
DistanceTo()
float FConvexVolume::DistanceTo (const FVector & Point) const
Calculates the maximum perpendicular distance of a point to the plains of the convex volume.
The distance can be used to see if the sphere is touching the volume
Parameters
Point to calculate the distance to.
Returns
Returns the maximum perpendicular distance to then plains (the distance is conservative at the corners)
References FVector, and Point.
GetBoxIntersectionOutcode()
FOutcode FConvexVolume::GetBoxIntersectionOutcode (const FVector & Origin, const FVector & Extent) const
References FVector, and Origin.
Init()
void FConvexVolume::Init (void)
Builds the permuted planes for SSE/Altivec fast clipping.
Referenced by FConvexVolume().
IntersectBox() [1/3]
bool FConvexVolume::IntersectBox (const FVector & Origin, const FVector & Extent) const
Intersection test with a translated axis-aligned box.
Parameters
Origin of the box.
Translation -to apply to the box.
Extent of the box along each axis.
Returns
true if this convex volume intersects the given translated box.
References FVector, and Origin.
Referenced by FDebugRenderSceneProxy::BoxInFrustum().
IntersectBox() [2/3]
bool FConvexVolume::IntersectBox (const FVector & Origin, const FVector & Extent, bool & bOutFullyContained) const
Intersection test with a translated axis-aligned box.
Parameters
Origin of the box.
Translation -to apply to the box.
Extent of the box along each axis. param bOutFullyContained to know if the box was fully contained
Returns
true if this convex volume intersects the given translated box.
References FVector, and Origin.
IntersectBox() [3/3]
bool FConvexVolume::IntersectBox (const FVector & Origin, const FVector & Translation, const FVector & Extent) const
Intersection test with a translated axis-aligned box.
Parameters
Origin - Origin of the box.
Translation - Translation to apply to the box.
Extent - Extent of the box along each axis.
Returns
true if this convex volume intersects the given translated box.
References FVector, Origin, and Translation.
IntersectLineSegment()
bool FConvexVolume::IntersectLineSegment (const FVector & Start, const FVector & End) const
Intersection test with line segment.
Parameters
Start of the segment.
End of the segment. param bOutFullyContained to know if the sphere was fully contained
Returns
true if this convex volume intersects the given line segment
References End, and FVector.
Referenced by FDebugRenderSceneProxy::SegmentInFrustum().
IntersectPoint()
bool FConvexVolume::IntersectPoint (const FVector & Point) const inline
Determines whether the given point lies inside the convex volume.
Parameters
Point to test against.
Returns
true if the point is inside the convex volume.
Definition at line 163 of file ConvexVolume.h.
References FVector, IntersectSphere(), and Point.
Referenced by FDebugRenderSceneProxy::PointInFrustum().
IntersectSphere() [1/2]
bool FConvexVolume::IntersectSphere (const FVector & Origin, const float & Radius) const
Intersection test with a sphere.
Parameters
Origin of the sphere.
Radius of the sphere.
Returns
true if this convex volume intersects the given sphere (the result is conservative at the corners)
References FVector, and Origin.
Referenced by IntersectPoint(), and FDebugRenderSceneProxy::SphereInFrustum().
IntersectSphere() [2/2]
bool FConvexVolume::IntersectSphere (const FVector & Origin, const float & Radius, bool & bOutFullyContained) const
Intersection test with a sphere.
Parameters
Origin of the sphere.
Radius of the sphere. param bOutFullyContained to know if the sphere was fully contained
Returns
true if this convex volume intersects the given sphere (the result is conservative at the corners)
References FVector, and Origin.
IntersectTriangle()
bool FConvexVolume::IntersectTriangle (const FVector & PointA, const FVector & PointB, const FVector & PointC, bool & bOutFullyContained) const
Intersection test with a triangle param bOutFullyContained to know if the triangle was fully contained.
Returns
true if this convex volume intersects the given triangle.
References FVector.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FConvexVolume & ConvexVolume) friend
Serializer.
Parameters
Ar Archive to serialize data to
ConvexVolume Convex volumes to serialize to archive
Returns
passed in archive
References FConvexVolume(), and Ar.
Field Documentation
PermutedPlanes
FPermutedPlaneArray FConvexVolume::PermutedPlanes
This is the set of planes pre-permuted to SSE/Altivec form.
Definition at line 52 of file ConvexVolume.h.
Planes
FPlaneArray FConvexVolume::Planes
Definition at line 50 of file ConvexVolume.h.
Referenced by FConvexVolume().
The documentation for this struct was generated from the following file:
ConvexVolume.h