Unreal Engine 5.6 C++ API: ActorsReferencesUtils::FGetActorReferencesParams Struct Reference
ActorsReferencesUtils::FGetActorReferencesParams Struct Reference
#include "ActorReferencesUtils.h"
Public Member Functions
FGetActorReferencesParams (UObject *InRoot)
FGetActorReferencesParams & SetRecursive (bool bInRecursive)
FGetActorReferencesParams & SetRequiredFlags (EObjectFlags InRequiredFlags)
Data Fields
bool bRecursive = false
EObjectFlags RequiredFlags = RF_NoFlags
UObject * Root = nullptr
Detailed Description
Definition at line 24 of file ActorReferencesUtils.h.
Constructor & Destructor Documentation
FGetActorReferencesParams()
ActorsReferencesUtils::FGetActorReferencesParams::FGetActorReferencesParams (UObject * InRoot) inline
Definition at line 26 of file ActorReferencesUtils.h.
References Root.
Referenced by SetRecursive(), and SetRequiredFlags().
Member Function Documentation
SetRecursive()
FGetActorReferencesParams & ActorsReferencesUtils::FGetActorReferencesParams::SetRecursive (bool bInRecursive) inline
Definition at line 35 of file ActorReferencesUtils.h.
References FGetActorReferencesParams(), and bRecursive.
SetRequiredFlags()
FGetActorReferencesParams & ActorsReferencesUtils::FGetActorReferencesParams::SetRequiredFlags (EObjectFlags InRequiredFlags) inline
Definition at line 34 of file ActorReferencesUtils.h.
References FGetActorReferencesParams(), and RequiredFlags.
Field Documentation
bRecursive
bool ActorsReferencesUtils::FGetActorReferencesParams::bRecursive = false
Definition at line 32 of file ActorReferencesUtils.h.
Referenced by SetRecursive().
RequiredFlags
EObjectFlags ActorsReferencesUtils::FGetActorReferencesParams::RequiredFlags = RF_NoFlags
Definition at line 31 of file ActorReferencesUtils.h.
Referenced by SetRequiredFlags().
Root
UObject* ActorsReferencesUtils::FGetActorReferencesParams::Root = nullptr
Definition at line 30 of file ActorReferencesUtils.h.
Referenced by FGetActorReferencesParams().
The documentation for this struct was generated from the following file:
ActorReferencesUtils.h