Unreal Engine 5.6 C++ API: UE::FLogTime Class Reference
UE::FLogTime Class Reference
Time that a log event occurred.
#include "StructuredLog.h"
Public Member Functions
constexpr FLogTime ()=default
FDateTime GetUtcTime () const
Returns the UTC time.
Static Public Member Functions
static FLogTime FromUtcTime (const FDateTime &UtcTime)
static FLogTime Now ()
Private Attributes
int64 UtcTicks = 0
Ticks from FDateTime::UtcNow()
Detailed Description
Time that a log event occurred.
Definition at line 162 of file StructuredLog.h.
Constructor & Destructor Documentation
FLogTime()
UE::FLogTime::FLogTime () constexpr default
Referenced by FromUtcTime(), and Now().
Member Function Documentation
FromUtcTime()
FLogTime UE::FLogTime::FromUtcTime (const FDateTime & UtcTime) static
References FLogTime(), and UE_API.
GetUtcTime()
FDateTime UE::FLogTime::GetUtcTime () const
Returns the UTC time.
0 ticks when the time was not set.
References UE_API.
Now()
FLogTime UE::FLogTime::Now () static
References FLogTime(), and UE_API.
Field Documentation
UtcTicks
int64 UE::FLogTime::UtcTicks = 0 private
Ticks from FDateTime::UtcNow()
Definition at line 175 of file StructuredLog.h.
The documentation for this class was generated from the following file:
StructuredLog.h