Unreal Engine 5.6 C++ API: TDoubleLinkedList< ElementType > Class Template Reference
TDoubleLinkedList< ElementType > Class Template Reference
Double linked list.
#include "List.h"
Data Structures
class TDoubleLinkedListNode
Public Types
typedef TDoubleLinkedListIterator< TDoubleLinkedListNode, const ElementType > TConstIterator
typedef TDoubleLinkedListIterator< TDoubleLinkedListNode, ElementType > TIterator
Used to iterate over the elements of a linked list.
Public Member Functions
TDoubleLinkedList ()
Constructors.
virtual ~TDoubleLinkedList ()
Destructor.
bool AddHead (const ElementType &InElement)
Add the specified value to the beginning of the list, making that value the new head of the list.
bool AddHead (TDoubleLinkedListNode *NewNode)
bool AddTail (const ElementType &InElement)
Append the specified value to the end of the list.
bool AddTail (TDoubleLinkedListNode *NewNode)
bool Contains (const ElementType &InElement)
void Empty ()
Removes all nodes from the list.
TDoubleLinkedListNode * FindNode (const ElementType &InElement)
Finds the node corresponding to the value specified.
TDoubleLinkedListNode * GetHead () const
Returns the node at the head of the list.
TDoubleLinkedListNode * GetTail () const
Returns the node at the end of the list.
bool InsertNode (const ElementType &InElement, TDoubleLinkedListNode *NodeToInsertBefore=nullptr)
Insert the specified value into the list at an arbitrary point.
bool InsertNode (TDoubleLinkedListNode *NewNode, TDoubleLinkedListNode *NodeToInsertBefore=nullptr)
bool IsEmpty () const
Returns true if the list is empty and contains no elements.
int32 Num () const
Returns the number of items in the list.
void RemoveNode (const ElementType &InElement)
Remove the node corresponding to InElement.
void RemoveNode (TDoubleLinkedListNode *NodeToRemove, bool bDeleteNode=true)
Removes the node specified.
Protected Member Functions
virtual void SetListSize (int32 NewListSize)
Updates the size reported by Num().
Private Member Functions
TDoubleLinkedList (const TDoubleLinkedList &)
TDoubleLinkedList & operator= (const TDoubleLinkedList &)
Private Attributes
TDoubleLinkedListNode * HeadNode
int32 ListSize
TDoubleLinkedListNode * TailNode
Friends
TConstIterator begin (const TDoubleLinkedList &List)
TIterator begin (TDoubleLinkedList &List)
TConstIterator end (const TDoubleLinkedList &List)
TIterator end (TDoubleLinkedList &List)
Detailed Description
template<class ElementType>
class TDoubleLinkedList< ElementType >
Double linked list.
See also
TIntrusiveDoubleLinkedList
Definition at line 437 of file List.h.
Member Typedef Documentation
TConstIterator
template<class ElementType> typedef TDoubleLinkedListIterator<TDoubleLinkedListNode, const ElementType> TDoubleLinkedList< ElementType >::TConstIterator
Definition at line 491 of file List.h.
TIterator
template<class ElementType> typedef TDoubleLinkedListIterator<TDoubleLinkedListNode, ElementType> TDoubleLinkedList< ElementType >::TIterator
Used to iterate over the elements of a linked list.
Definition at line 490 of file List.h.
Constructor & Destructor Documentation
TDoubleLinkedList() [1/2]
template<class ElementType> TDoubleLinkedList< ElementType >::TDoubleLinkedList () inline nodiscard
Constructors.
Definition at line 494 of file List.h.
~TDoubleLinkedList()
template<class ElementType> virtual TDoubleLinkedList< ElementType >::~TDoubleLinkedList () inline virtual
Destructor.
Definition at line 502 of file List.h.
TDoubleLinkedList() [2/2]
template<class ElementType> TDoubleLinkedList< ElementType >::TDoubleLinkedList (const TDoubleLinkedList< ElementType > &) private
Member Function Documentation
AddHead() [1/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::AddHead (const ElementType & InElement) inline
Add the specified value to the beginning of the list, making that value the new head of the list.
Parameters
InElement the value to add to the list.
Returns
whether the node was successfully added into the list.
See also
GetHead, InsertNode, RemoveNode
Definition at line 516 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::AddHead(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), FRigVMGraphMathTypeDetailCustomization::GetPropertyChain(), TDoubleLinkedListNode< FSegmentAndSID >::InsertNode(), and FObjectEditorUtils::SetPropertyValue().
AddHead() [2/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::AddHead (TDoubleLinkedListNode * NewNode) inline
Definition at line 521 of file List.h.
AddTail() [1/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::AddTail (const ElementType & InElement) inline
Append the specified value to the end of the list.
Parameters
InElement the value to add to the list.
Returns
whether the node was successfully added into the list
See also
GetTail, InsertNode, RemoveNode
Definition at line 551 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::AddTail().
AddTail() [2/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::AddTail (TDoubleLinkedListNode * NewNode) inline
Definition at line 556 of file List.h.
Contains()
template<class ElementType> bool TDoubleLinkedList< ElementType >::Contains (const ElementType & InElement) inline nodiscard
Definition at line 743 of file List.h.
Empty()
template<class ElementType> void TDoubleLinkedList< ElementType >::Empty () inline
Removes all nodes from the list.
Definition at line 683 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::~TDoubleLinkedList(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), FRigVMGraphMathTypeDetailCustomization::GetPropertyChain(), and TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
FindNode()
template<class ElementType> TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::FindNode (const ElementType & InElement) inline nodiscard
Finds the node corresponding to the value specified.
Parameters
InElement the value to find
Returns
a pointer to the node that contains the value specified, or nullptr of the value couldn't be found
Definition at line 727 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::Contains(), and TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
GetHead()
template<class ElementType> TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::GetHead () const inline nodiscard
Returns the node at the head of the list.
Returns
Pointer to the first node.
See also
GetTail
Definition at line 705 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::begin, TDoubleLinkedListNode< FSegmentAndSID >::begin, FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr(), FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), and FRigVMGraphMathTypeDetailCustomization::GetPropertyChain().
GetTail()
template<class ElementType> TDoubleLinkedListNode * TDoubleLinkedList< ElementType >::GetTail () const inline nodiscard
Returns the node at the end of the list.
Returns
Pointer to the last node.
See also
GetHead
Definition at line 716 of file List.h.
Referenced by FRigVMGraphEnumDetailCustomization::GetPropertyChain(), and FRigVMGraphMathTypeDetailCustomization::GetPropertyChain().
InsertNode() [1/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::InsertNode (const ElementType & InElement, TDoubleLinkedListNode * NodeToInsertBefore = nullptr) inline
Insert the specified value into the list at an arbitrary point.
Parameters
InElement the value to insert into the list
NodeToInsertBefore the new node will be inserted into the list at the current location of this node if nullptr, the new node will become the new head of the list
Returns
whether the node was successfully added into the list
See also
Empty, RemoveNode
Definition at line 587 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::InsertNode().
InsertNode() [2/2]
template<class ElementType> bool TDoubleLinkedList< ElementType >::InsertNode (TDoubleLinkedListNode * NewNode, TDoubleLinkedListNode * NodeToInsertBefore = nullptr) inline
Definition at line 592 of file List.h.
IsEmpty()
template<class ElementType> bool TDoubleLinkedList< ElementType >::IsEmpty () const inline nodiscard
Returns true if the list is empty and contains no elements.
Returns
True if the list is empty.
See also
Num
Definition at line 754 of file List.h.
Num()
template<class ElementType> int32 TDoubleLinkedList< ElementType >::Num () const inline nodiscard
Returns the number of items in the list.
Returns
Item count.
Definition at line 764 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
operator=()
template<class ElementType> TDoubleLinkedList & TDoubleLinkedList< ElementType >::operator= (const TDoubleLinkedList< ElementType > &) private
RemoveNode() [1/2]
template<class ElementType> void TDoubleLinkedList< ElementType >::RemoveNode (const ElementType & InElement) inline
Remove the node corresponding to InElement.
Parameters
InElement The value to remove from the list.
See also
Empty, InsertNode
Definition at line 620 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
RemoveNode() [2/2]
template<class ElementType> void TDoubleLinkedList< ElementType >::RemoveNode (TDoubleLinkedListNode * NodeToRemove, bool bDeleteNode = true) inline
Removes the node specified.
Parameters
NodeToRemove The node to remove.
See also
Empty, InsertNode
Definition at line 632 of file List.h.
SetListSize()
template<class ElementType> virtual void TDoubleLinkedList< ElementType >::SetListSize (int32 NewListSize) inline protected virtual
Updates the size reported by Num().
Child classes can use this function to conveniently hook into list additions/removals.
Parameters
NewListSize the new size for this list
Reimplemented in FEditPropertyChain.
Definition at line 777 of file List.h.
Referenced by TDoubleLinkedListNode< FSegmentAndSID >::AddHead(), TDoubleLinkedListNode< FSegmentAndSID >::AddTail(), TDoubleLinkedListNode< FSegmentAndSID >::Empty(), TDoubleLinkedListNode< FSegmentAndSID >::InsertNode(), and TDoubleLinkedListNode< FSegmentAndSID >::RemoveNode().
Friends And Related Symbol Documentation
begin [1/2]
template<class ElementType> TConstIterator begin (const TDoubleLinkedList< ElementType > & List) friend
Definition at line 791 of file List.h.
begin [2/2]
template<class ElementType> TIterator begin (TDoubleLinkedList< ElementType > & List) friend
Definition at line 790 of file List.h.
end [1/2]
template<class ElementType> TConstIterator end (const TDoubleLinkedList< ElementType > & List) friend
Definition at line 793 of file List.h.
end [2/2]
template<class ElementType> TIterator end (TDoubleLinkedList< ElementType > & List) friend
Definition at line 792 of file List.h.
Field Documentation
HeadNode
template<class ElementType> TDoubleLinkedListNode* TDoubleLinkedList< ElementType >::HeadNode private
Definition at line 783 of file List.h.
ListSize
template<class ElementType> int32 TDoubleLinkedList< ElementType >::ListSize private
Definition at line 785 of file List.h.
TailNode
template<class ElementType> TDoubleLinkedListNode* TDoubleLinkedList< ElementType >::TailNode private
Definition at line 784 of file List.h.
The documentation for this class was generated from the following file:
List.h