Unreal Engine 5.6 C++ API: TDisplayClusterDataCache< InDataType > Class Template Reference
TDisplayClusterDataCache< InDataType > Class Template Reference
Cache template for named data with automatic deletion of unused items after timeout.
#include "DisplayClusterDataCache.h"
Data Structures
struct FCachedObject
Public Types
typedef InDataType DataType
Data type of stored objects.
Public Member Functions
virtual ~TDisplayClusterDataCache ()
void Add (const TSharedPtr< DataType, ESPMode::ThreadSafe > &InDataRef)
Register a new object.
TSharedPtr< DataType, ESPMode::ThreadSafe > Find (const FString &InUniqueDataName)
Retrieve an existing object by a unique name.
Static Public Member Functions
static FString HashString (const FString &InString)
Helper to perform the very common case of hashing an FString into a hex representation.
Protected Member Functions
void Release ()
Release the cache.
void Tick (float DeltaTime)
When the number of DataRef references drops to 1, these items will be removed after a timeout.
void UpdateTickableGameObject ()
Create or remove tickable game object.
Private Attributes
TArray< FCachedObject > CachedObjects
TUniquePtr< FDisplayClusterTickableGameObject > TickableGameObject
FDelegateHandle TickHandle
Detailed Description
template<typename InDataType>
class TDisplayClusterDataCache< InDataType >
Cache template for named data with automatic deletion of unused items after timeout.
Definition at line 13 of file DisplayClusterDataCache.h.
Member Typedef Documentation
DataType
template<typename InDataType> typedef InDataType TDisplayClusterDataCache< InDataType >::DataType
Data type of stored objects.
The following methods must be implemented in DataType:
// Return DataCache timeout in frames. A negative value disables the timeout. static int32 GetDataCacheTimeOutInFrames();
// Return true if DataCache is enabled. static bool IsDataCacheEnabled();
// Method for releasing a cached data item, called before its destructor void ReleaseDataCacheItem();
// Returns the unique name of this texture for DataCache. inline const FString& GetDataCacheName() const;
Definition at line 32 of file DisplayClusterDataCache.h.
Constructor & Destructor Documentation
~TDisplayClusterDataCache()
template<typename InDataType> virtual TDisplayClusterDataCache< InDataType >::~TDisplayClusterDataCache () inline virtual
Definition at line 34 of file DisplayClusterDataCache.h.
References Release().
Member Function Documentation
Add()
template<typename InDataType> void TDisplayClusterDataCache< InDataType >::Add (const TSharedPtr< DataType, ESPMode::ThreadSafe > & InDataRef) inline
Register a new object.
Definition at line 63 of file DisplayClusterDataCache.h.
References CachedObjects, and UpdateTickableGameObject().
Find()
template<typename InDataType> TSharedPtr< DataType, ESPMode::ThreadSafe > TDisplayClusterDataCache< InDataType >::Find (const FString & InUniqueDataName) inline
Retrieve an existing object by a unique name.
Definition at line 46 of file DisplayClusterDataCache.h.
References CachedObjects.
HashString()
template<typename InDataType> FString TDisplayClusterDataCache< InDataType >::HashString (const FString & InString) inline static
Helper to perform the very common case of hashing an FString into a hex representation.
Definition at line 40 of file DisplayClusterDataCache.h.
References FMD5::HashAnsiString().
Release()
template<typename InDataType> void TDisplayClusterDataCache< InDataType >::Release () inline protected
Release the cache.
Definition at line 77 of file DisplayClusterDataCache.h.
References CachedObjects, and UpdateTickableGameObject().
Referenced by ~TDisplayClusterDataCache(), and Tick().
Tick()
template<typename InDataType> void TDisplayClusterDataCache< InDataType >::Tick (float DeltaTime) inline protected
When the number of DataRef references drops to 1, these items will be removed after a timeout.
Definition at line 86 of file DisplayClusterDataCache.h.
References CachedObjects, DeltaTime, Release(), and UpdateTickableGameObject().
Referenced by UpdateTickableGameObject().
UpdateTickableGameObject()
template<typename InDataType> void TDisplayClusterDataCache< InDataType >::UpdateTickableGameObject () inline protected
Create or remove tickable game object.
Definition at line 125 of file DisplayClusterDataCache.h.
References CachedObjects, MakeUnique(), Tick(), TickableGameObject, and TickHandle.
Referenced by Add(), Release(), and Tick().
Field Documentation
CachedObjects
template<typename InDataType> TArray<FCachedObject> TDisplayClusterDataCache< InDataType >::CachedObjects private
Definition at line 185 of file DisplayClusterDataCache.h.
Referenced by Add(), Find(), Release(), Tick(), and UpdateTickableGameObject().
TickableGameObject
template<typename InDataType> TUniquePtr<FDisplayClusterTickableGameObject> TDisplayClusterDataCache< InDataType >::TickableGameObject private
Definition at line 189 of file DisplayClusterDataCache.h.
Referenced by UpdateTickableGameObject().
TickHandle
template<typename InDataType> FDelegateHandle TDisplayClusterDataCache< InDataType >::TickHandle private
Definition at line 192 of file DisplayClusterDataCache.h.
Referenced by UpdateTickableGameObject().
The documentation for this class was generated from the following file:
DisplayClusterDataCache.h