Unreal Engine 5.6 C++ API: FAssetDataTagMapSharedView Class Reference
FAssetDataTagMapSharedView Class Reference
Reference-counted handle to a loose FAssetDataTagMap or a fixed / immutable cooked tag map.
#include "AssetDataTagMap.h"
Data Structures
class FMemoryCounter
Helps count deduplicated memory usage.
Public Types
using FFindTagResult = FAssetTagValueRef
Public Member Functions
FAssetDataTagMapSharedView ()=default
FAssetDataTagMapSharedView (const FAssetDataTagMapSharedView &O)
FAssetDataTagMapSharedView (FAssetDataTagMap &&InLoose)
FAssetDataTagMapSharedView (FAssetDataTagMapSharedView &&O)
FAssetDataTagMapSharedView (FixedTagPrivate::FMapHandle InFixed)
~FAssetDataTagMapSharedView ()
TConstIterator begin () const
Shrinks the contained map *‍/ 1 void Shrink();.
bool Contains (FName Key) const
Determine whether a key is present in the map.
bool ContainsKeyValue (FName Tag, const FString &Value) const
Return true if this map contains a specific key value pair.
FAssetDataTagMap CopyMap () const
Copy map contents to a loose FAssetDataTagMap.
TConstIterator end () const
Range for iterator access - DO NOT USE DIRECTLY.
FAssetTagValueRef FindTag (FName Tag) const
Find a value by key and return an option indicating if it was found, and if so, what the value is.
template<typename Func>
void ForEach (Func Fn) const
int32 Num () const
Retrieve size of map.
FAssetDataTagMapSharedView & operator= (const FAssetDataTagMapSharedView &)
FAssetDataTagMapSharedView & operator= (FAssetDataTagMapSharedView &&)
Private Member Functions
FAssetTagValueRef FindFixedValue (FName Key) const
bool IsFixed () const
bool IsLoose () const
Static Private Member Functions
static TPair< FName, FAssetTagValueRef > MakePair (const FAssetDataTagMap::ElementType &LoosePair)
static TPair< FName, FAssetTagValueRef > MakePair (FixedTagPrivate::FNumberedPair FixedPair, uint32 StoreIndex)
Private Attributes
union {
uint64 Bits = 0
FixedTagPrivate::FMapHandle Fixed
FAssetDataTagMap * Loose
};
Friends
bool operator!= (const FAssetDataTagMap &A, const FAssetDataTagMapSharedView &B)
bool operator!= (const FAssetDataTagMapSharedView &A, const FAssetDataTagMap &B)
bool operator!= (const FAssetDataTagMapSharedView &A, const FAssetDataTagMapSharedView &B)
bool operator== (const FAssetDataTagMap &A, const FAssetDataTagMapSharedView &B)
bool operator== (const FAssetDataTagMapSharedView &A, const FAssetDataTagMap &B)
bool operator== (const FAssetDataTagMapSharedView &A, const FAssetDataTagMapSharedView &B)
Detailed Description
Reference-counted handle to a loose FAssetDataTagMap or a fixed / immutable cooked tag map.
Definition at line 302 of file AssetDataTagMap.h.
Member Typedef Documentation
FFindTagResult
using FAssetDataTagMapSharedView::FFindTagResult = FAssetTagValueRef
Definition at line 350 of file AssetDataTagMap.h.
Constructor & Destructor Documentation
FAssetDataTagMapSharedView() [1/5]
FAssetDataTagMapSharedView::FAssetDataTagMapSharedView () default
Referenced by FAssetDataTagMapSharedView(), FAssetDataTagMapSharedView(), FAssetDataTagMapSharedView::FMemoryCounter::Include(), operator!=, operator!=, operator!=, operator=(), operator=(), operator==, operator==, and operator==.
FAssetDataTagMapSharedView() [2/5]
FAssetDataTagMapSharedView::FAssetDataTagMapSharedView (const FAssetDataTagMapSharedView & O)
References FAssetDataTagMapSharedView().
FAssetDataTagMapSharedView() [3/5]
FAssetDataTagMapSharedView::FAssetDataTagMapSharedView (FAssetDataTagMapSharedView && O)
References FAssetDataTagMapSharedView().
FAssetDataTagMapSharedView() [4/5]
FAssetDataTagMapSharedView::FAssetDataTagMapSharedView (FixedTagPrivate::FMapHandle InFixed) explicit
FAssetDataTagMapSharedView() [5/5]
FAssetDataTagMapSharedView::FAssetDataTagMapSharedView (FAssetDataTagMap && InLoose) explicit
~FAssetDataTagMapSharedView()
FAssetDataTagMapSharedView::~FAssetDataTagMapSharedView ()
Member Function Documentation
begin()
TConstIterator FAssetDataTagMapSharedView::begin () const inline
Shrinks the contained map *‍/ 1 void Shrink();.
class TConstIterator { public: TConstIterator(const FAssetDataTagMapSharedView& InView, uint32 InIndex) : View(InView) , Index(InIndex) {}
TPair<FName, FAssetTagValueRef> operator*() const { check(View.Bits != 0); return View.IsFixed() ? MakePair(View.Fixed.At(Index), View.Fixed.StoreIndex) : MakePair((&*View.Loose->begin())[Index]); }
TConstIterator& operator++() { ++Index; return *this; }
bool operator!=(TConstIterator Rhs) const { return Index != Rhs.Index; }
protected: const FAssetDataTagMapSharedView& View; uint32 Index; };
class TConstIteratorWithEnd : public TConstIterator { public: TConstIteratorWithEnd(const FAssetDataTagMapSharedView& InView, uint32 InBeginIndex, uint32 InEndIndex) : TConstIterator(InView, InBeginIndex) , EndIndex(InEndIndex) {}
explicit operator bool() const { return Index != EndIndex; } FName Key() const { return operator*().Key; } FAssetTagValueRef Value() const { return operator*().Value; }
private: const uint32 EndIndex; };
TConstIteratorWithEnd CreateConstIterator() const { return TConstIteratorWithEnd(*this, 0, Num()); }
/** Range for iterator access - DO NOT USE DIRECTLY
Definition at line 462 of file AssetDataTagMap.h.
Contains()
bool FAssetDataTagMapSharedView::Contains (FName Key) const inline
Determine whether a key is present in the map.
Definition at line 370 of file AssetDataTagMap.h.
References FindTag(), FAssetTagValueRef::IsSet(), and Key.
ContainsKeyValue()
bool FAssetDataTagMapSharedView::ContainsKeyValue (FName Tag, const FString & Value) const inline
Return true if this map contains a specific key value pair.
Value comparisons are NOT cases sensitive.
Definition at line 364 of file AssetDataTagMap.h.
References FAssetTagValueRef::Equals(), FindTag(), and Value.
CopyMap()
FAssetDataTagMap FAssetDataTagMapSharedView::CopyMap () const
Copy map contents to a loose FAssetDataTagMap.
end()
TConstIterator FAssetDataTagMapSharedView::end () const inline
Range for iterator access - DO NOT USE DIRECTLY.
Definition at line 468 of file AssetDataTagMap.h.
References Num().
FindFixedValue()
FAssetTagValueRef FAssetDataTagMapSharedView::FindFixedValue (FName Key) const inline private
Definition at line 321 of file AssetDataTagMap.h.
References checkSlow, Fixed, IsFixed(), Key, and Value.
Referenced by FindTag().
FindTag()
FAssetTagValueRef FAssetDataTagMapSharedView::FindTag (FName Tag) const inline
Find a value by key and return an option indicating if it was found, and if so, what the value is.
Definition at line 353 of file AssetDataTagMap.h.
References FindFixedValue(), IsFixed(), and Loose.
Referenced by Contains(), and ContainsKeyValue().
ForEach()
template<typename Func> void FAssetDataTagMapSharedView::ForEach (Func Fn) const inline
Definition at line 390 of file AssetDataTagMap.h.
References Fixed, IsFixed(), Loose, and MakePair().
IsFixed()
bool FAssetDataTagMapSharedView::IsFixed () const inline private
Definition at line 311 of file AssetDataTagMap.h.
References Fixed.
Referenced by FindFixedValue(), FindTag(), ForEach(), and Num().
IsLoose()
bool FAssetDataTagMapSharedView::IsLoose () const inline private
Definition at line 316 of file AssetDataTagMap.h.
References Fixed, and Loose.
MakePair() [1/2]
TPair< FName, FAssetTagValueRef > FAssetDataTagMapSharedView::MakePair (const FAssetDataTagMap::ElementType & LoosePair) inline static private
Definition at line 333 of file AssetDataTagMap.h.
References MakeTuple().
MakePair() [2/2]
TPair< FName, FAssetTagValueRef > FAssetDataTagMapSharedView::MakePair (FixedTagPrivate::FNumberedPair FixedPair, uint32 StoreIndex) inline static private
Definition at line 328 of file AssetDataTagMap.h.
References FixedTagPrivate::FNumberedPair::Key, MakeTuple(), and FixedTagPrivate::FNumberedPair::Value.
Referenced by ForEach().
Num()
int32 FAssetDataTagMapSharedView::Num () const inline
Retrieve size of map.
Definition at line 376 of file AssetDataTagMap.h.
References Fixed, IsFixed(), and Loose.
Referenced by end().
operator=() [1/2]
FAssetDataTagMapSharedView & FAssetDataTagMapSharedView::operator= (const FAssetDataTagMapSharedView &)
References FAssetDataTagMapSharedView().
operator=() [2/2]
FAssetDataTagMapSharedView & FAssetDataTagMapSharedView::operator= (FAssetDataTagMapSharedView &&)
References FAssetDataTagMapSharedView().
Friends And Related Symbol Documentation
operator!= [1/3]
bool operator!= (const FAssetDataTagMap & A, const FAssetDataTagMapSharedView & B) friend
Definition at line 486 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView(), A, and B.
operator!= [2/3]
bool operator!= (const FAssetDataTagMapSharedView & A, const FAssetDataTagMap & B) friend
Definition at line 487 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView(), A, and B.
operator!= [3/3]
bool operator!= (const FAssetDataTagMapSharedView & A, const FAssetDataTagMapSharedView & B) friend
Definition at line 488 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView(), A, and B.
operator== [1/3]
bool operator== (const FAssetDataTagMap & A, const FAssetDataTagMapSharedView & B) friend
Definition at line 485 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView(), A, and B.
operator== [2/3]
bool operator== (const FAssetDataTagMapSharedView & A, const FAssetDataTagMap & B) friend
References FAssetDataTagMapSharedView(), A, and B.
operator== [3/3]
bool operator== (const FAssetDataTagMapSharedView & A, const FAssetDataTagMapSharedView & B) friend
References FAssetDataTagMapSharedView(), A, and B.
Field Documentation
[union]
union { ... } FAssetDataTagMapSharedView
Bits
uint64 FAssetDataTagMapSharedView::Bits = 0
Definition at line 308 of file AssetDataTagMap.h.
Fixed
FixedTagPrivate::FMapHandle FAssetDataTagMapSharedView::Fixed
Definition at line 306 of file AssetDataTagMap.h.
Referenced by FindFixedValue(), ForEach(), IsFixed(), IsLoose(), and Num().
Loose
FAssetDataTagMap* FAssetDataTagMapSharedView::Loose
Definition at line 307 of file AssetDataTagMap.h.
Referenced by FindTag(), ForEach(), IsLoose(), and Num().
The documentation for this class was generated from the following file:
AssetDataTagMap.h