Unreal Engine 5.6 C++ API: FRDGBlackboard Class Reference
FRDGBlackboard Class Reference
The blackboard is a map of struct instances with a lifetime tied to a render graph allocator.
#include "RenderGraphBlackboard.h"
Data Structures
struct FStruct
struct TStruct
Public Member Functions
template<typename StructType, typename... ArgsType>
StructType & Create (ArgsType &&... Args)
Creates a new instance of a struct.
template<typename StructType>
const StructType * Get () const
Gets an immutable instance of the struct.
template<typename StructType>
const StructType & GetChecked () const
Gets an immutable instance of the struct.
template<typename StructType>
StructType * GetMutable () const
Gets a mutable instance of the struct.
template<typename StructType>
StructType & GetMutableChecked () const
Gets a mutable instance of the struct.
template<typename StructType, typename... ArgsType>
StructType & GetOrCreate (ArgsType &&... Args)
Private Member Functions
FRDGBlackboard (FRDGAllocator &InAllocator)
void Clear ()
Static Private Member Functions
static RENDERCORE_API uint32 AllocateIndex (FString &&TypeName)
template<typename StructType>
static uint32 GetStructIndex ()
template<typename StructType>
static FString GetTypeName ()
static RENDERCORE_API FString GetTypeName (const TCHAR *ClassName, const TCHAR *FileName, uint32 LineNumber)
Private Attributes
FRDGAllocator & Allocator
TArray< FStruct *, FRDGArrayAllocator > Blackboard
Friends
class FRDGBuilder
Detailed Description
The blackboard is a map of struct instances with a lifetime tied to a render graph allocator.
It is designed to solve cases where explicit marshaling of immutable data is undesirable. Structures are created once and the mutable reference is returned.
Good candidates for the blackboard would be data that is created once and immutably fetched across the entire renderer pipeline, where marshaling would create more maintenance burden than benefit. More constrained data structures should be marshaled through function calls instead.
Example of Usage:
class FMyStruct { public: FRDGTextureRef TextureA = nullptr; FRDGTextureRef TextureB = nullptr; FRDGTextureRef TextureC = nullptr; };
RDG_REGISTER_BLACKBOARD_STRUCT(FMyStruct);
static void InitStruct(FRDGBlackboard& GraphBlackboard) { auto& MyStruct = GraphBlackboard.Create<FMyStruct>();
//... }
static void UseStruct(const FRDGBlackboard& GraphBlackboard) { const auto& MyStruct = GraphBlackboard.GetChecked<FMyStruct>();
//... }
Definition at line 56 of file RenderGraphBlackboard.h.
Constructor & Destructor Documentation
FRDGBlackboard()
FRDGBlackboard::FRDGBlackboard (FRDGAllocator & InAllocator) inline private
Definition at line 129 of file RenderGraphBlackboard.h.
References Allocator.
Member Function Documentation
AllocateIndex()
RENDERCORE_API uint32 FRDGBlackboard::AllocateIndex (FString && TypeName) static private
Referenced by GetStructIndex().
Clear()
void FRDGBlackboard::Clear () inline private
Definition at line 133 of file RenderGraphBlackboard.h.
References Blackboard.
Create()
template<typename StructType, typename... ArgsType> StructType & FRDGBlackboard::Create (ArgsType &&... Args) inline
Creates a new instance of a struct.
Asserts if one already existed.
Definition at line 61 of file RenderGraphBlackboard.h.
References Allocator, Blackboard, check, checkf, Forward(), GetGeneratedTypeName(), GetStructIndex(), Struct, and TEXT.
Get()
template<typename StructType> const StructType * FRDGBlackboard::Get () const inline
Gets an immutable instance of the struct.
Returns null if not present in the blackboard.
Definition at line 97 of file RenderGraphBlackboard.h.
References GetMutable().
GetChecked()
template<typename StructType> const StructType & FRDGBlackboard::GetChecked () const inline
Gets an immutable instance of the struct.
Asserts if not present in the blackboard.
Definition at line 123 of file RenderGraphBlackboard.h.
References GetMutableChecked().
GetMutable()
template<typename StructType> StructType * FRDGBlackboard::GetMutable () const inline
Gets a mutable instance of the struct.
Returns null if not present in the blackboard.
Definition at line 80 of file RenderGraphBlackboard.h.
References Blackboard, and GetStructIndex().
Referenced by Get(), GetMutableChecked(), and GetOrCreate().
GetMutableChecked()
template<typename StructType> StructType & FRDGBlackboard::GetMutableChecked () const inline
Gets a mutable instance of the struct.
Asserts if not present in the blackboard.
Definition at line 114 of file RenderGraphBlackboard.h.
References checkf, GetGeneratedTypeName(), GetMutable(), Struct, and TEXT.
Referenced by GetChecked().
GetOrCreate()
template<typename StructType, typename... ArgsType> StructType & FRDGBlackboard::GetOrCreate (ArgsType &&... Args) inline
Definition at line 103 of file RenderGraphBlackboard.h.
References Create, Forward(), GetMutable(), and Struct.
GetStructIndex()
template<typename StructType> uint32 FRDGBlackboard::GetStructIndex () inline static private
Definition at line 166 of file RenderGraphBlackboard.h.
References AllocateIndex(), and GetTypeName().
Referenced by Create(), and GetMutable().
GetTypeName() [1/2]
template<typename StructType> FString FRDGBlackboard::GetTypeName () inline static private
Definition at line 155 of file RenderGraphBlackboard.h.
Referenced by GetStructIndex().
GetTypeName() [2/2]
RENDERCORE_API FString FRDGBlackboard::GetTypeName (const TCHAR * ClassName, const TCHAR * FileName, uint32 LineNumber) static private
Friends And Related Symbol Documentation
FRDGBuilder
friend class FRDGBuilder friend
Definition at line 179 of file RenderGraphBlackboard.h.
References FRDGBuilder.
Referenced by FRDGBuilder.
Field Documentation
Allocator
FRDGAllocator& FRDGBlackboard::Allocator private
Definition at line 176 of file RenderGraphBlackboard.h.
Referenced by FRDGBlackboard(), and Create().
Blackboard
TArray<FStruct*, FRDGArrayAllocator> FRDGBlackboard::Blackboard private
Definition at line 177 of file RenderGraphBlackboard.h.
Referenced by Clear(), Create(), and GetMutable().
The documentation for this class was generated from the following file:
RenderGraphBlackboard.h