Unreal Engine 5.6 C++ API: UE::Geometry::FGeneralizedCylinderGenerator Class Reference
UE::Geometry::FGeneralizedCylinderGenerator Class Reference
Sweep a 2D Profile Polygon along a 3D Path.
#include "SweepGenerator.h"
Public Member Functions
void EnableMitering (double InMiterLimit=10)
virtual FMeshShapeGenerator & Generate () override
Generate the mesh.
void SetMiterLimitByAngle (double MiterAngleLimitInDeg)
Public Member Functions inherited from UE::Geometry::FSweepGeneratorBase
virtual ~FSweepGeneratorBase ()
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Data Fields
bool bAlignFramesToSampledTangents = false
bool bCapped = false
bool bLoop = false
bool bUVScaleRelativeWorld = false
ECapType CapType = ECapType::FlatTriangulation
FPolygon2d CrossSection
TArray< float > CrossSectionTexCoord
double EndScale = 1.0
FFrame3d InitialFrame
double MiterLimit = 1.0
TArray< FVector3d > Path
TArray< FFrame3d > PathFrames
TArray< FVector2d > PathScales
TArray< float > PathTexCoord
double StartScale = 1.0
float UnitUVInWorldCoordinates = 100
Data Fields inherited from UE::Geometry::FSweepGeneratorBase
bool bPolygroupPerQuad = false
If true, each quad gets a separate polygroup.
bool bProfileCurveIsClosed = true
If true, the last point of the profile curve is considered to be connected to the first.
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Protected Member Functions inherited from UE::Geometry::FSweepGeneratorBase
void ConstructMeshTopology (const FPolygon2d &CrossSection, const TArrayView< const int32 > &UVSections, const TArrayView< const int32 > &NormalSections, const TArrayView< const int32 > &SharpNormalsAlongLength, bool bEvenlySpaceUVs, const TArrayView< const FVector3d > &Path, int32 NumCrossSections, bool bLoop, const ECapType Caps[2], FVector2f SectionsUVScale, FVector2f CapUVScale, FVector2f CapUVOffset, const TArrayView< const float > &CustomCrossSectionTexCoord={}, const TArrayView< const float > &CustomPathTexCoord={})
Shared logic for creating vertex buffers and triangulations across all sweep primitives Note: Does not set vertex positions or normals; a separate call must do that.
Protected Attributes inherited from UE::Geometry::FSweepGeneratorBase
int32 CapNormalStart [2]
int32 CapPolygonStart [2]
int32 CapTriangleStart [2]
int32 CapUVStart [2]
int32 CapVertStart [2]
Detailed Description
Sweep a 2D Profile Polygon along a 3D Path.
TODO:
a custom variant for toruses specifically (would be faster)
Definition at line 721 of file SweepGenerator.h.
Member Function Documentation
EnableMitering()
void UE::Geometry::FGeneralizedCylinderGenerator::EnableMitering (double InMiterLimit = 10) inline
Definition at line 750 of file SweepGenerator.h.
References bAlignFramesToSampledTangents, and MiterLimit.
Generate()
virtual FMeshShapeGenerator & UE::Geometry::FGeneralizedCylinderGenerator::Generate () inline override virtual
Generate the mesh.
Implements UE::Geometry::FMeshShapeGenerator.
Definition at line 801 of file SweepGenerator.h.
References UE::Geometry::TFrame3< RealType >::AlignAxis(), UE::Geometry::CurveUtil::ArcLength(), UE::Geometry::TMatrix2< double >::AxisScale(), bAlignFramesToSampledTangents, bCapped, bLoop, bUVScaleRelativeWorld, UE::Geometry::FSweepGeneratorBase::CapNormalStart, CapType, UE::Geometry::FSweepGeneratorBase::CapVertStart, UE::Geometry::TAxisAlignedBox2< RealType >::Center(), TMathUtil< double >::Clamp(), UE::Geometry::FSweepGeneratorBase::ConstructMeshTopology(), CrossSection, CrossSectionTexCoord, Distance, UE::Math::TVector< T >::Dot(), EndScale, UE::Geometry::FlatMidpointFan, float, UE::Geometry::CurveUtil::GetVectorsToPrevNext(), UE::Geometry::TMatrix2< double >::Identity(), InitialFrame, UE::Math::TVector< T >::IsZero(), TMathUtil< double >::Lerp(), TMathUtil< double >::Max(), UE::Geometry::TAxisAlignedBox2< RealType >::MaxDim(), MiterLimit, UE::Geometry::None, UE::Geometry::Normal, UE::Geometry::Normalize, UE::Math::TVector2< T >::Normalize(), Normalized, UE::Geometry::FMeshShapeGenerator::Normals, UE::Math::TVector2< double >::One(), Path, PathFrames, PathScales, PathTexCoord, UE::Geometry::Perimeter, TArray< InElementType, InAllocatorType >::SetNum(), StartScale, Tangent, UE::Geometry::CurveUtil::Tangent(), UE::Geometry::TFrame3< RealType >::ToFrameVector(), UnitUVInWorldCoordinates, UE::Geometry::FMeshShapeGenerator::Vertices, UE::Geometry::TFrame3< RealType >::X(), UE::Math::TVector2< T >::X, X, Y, UE::Geometry::TFrame3< RealType >::Y(), and UE::Math::TVector2< T >::Y.
SetMiterLimitByAngle()
void UE::Geometry::FGeneralizedCylinderGenerator::SetMiterLimitByAngle (double MiterAngleLimitInDeg) inline
Definition at line 758 of file SweepGenerator.h.
References FMath::Clamp(), TMathUtilConstants< double >::DegToRad, MiterLimit, and TMathUtilConstants< double >::ZeroTolerance.
Field Documentation
bAlignFramesToSampledTangents
bool UE::Geometry::FGeneralizedCylinderGenerator::bAlignFramesToSampledTangents = false
Definition at line 747 of file SweepGenerator.h.
Referenced by EnableMitering(), and Generate().
bCapped
bool UE::Geometry::FGeneralizedCylinderGenerator::bCapped = false
Definition at line 733 of file SweepGenerator.h.
Referenced by Generate().
bLoop
bool UE::Geometry::FGeneralizedCylinderGenerator::bLoop = false
Definition at line 734 of file SweepGenerator.h.
Referenced by Generate().
bUVScaleRelativeWorld
bool UE::Geometry::FGeneralizedCylinderGenerator::bUVScaleRelativeWorld = false
Definition at line 768 of file SweepGenerator.h.
Referenced by Generate().
CapType
ECapType UE::Geometry::FGeneralizedCylinderGenerator::CapType = ECapType::FlatTriangulation
Definition at line 735 of file SweepGenerator.h.
Referenced by Generate().
CrossSection
FPolygon2d UE::Geometry::FGeneralizedCylinderGenerator::CrossSection
Definition at line 724 of file SweepGenerator.h.
Referenced by Generate().
CrossSectionTexCoord
TArray<float> UE::Geometry::FGeneralizedCylinderGenerator::CrossSectionTexCoord
Definition at line 785 of file SweepGenerator.h.
Referenced by Generate().
EndScale
double UE::Geometry::FGeneralizedCylinderGenerator::EndScale = 1.0
Definition at line 739 of file SweepGenerator.h.
Referenced by Generate().
InitialFrame
FFrame3d UE::Geometry::FGeneralizedCylinderGenerator::InitialFrame
Definition at line 727 of file SweepGenerator.h.
Referenced by Generate().
MiterLimit
double UE::Geometry::FGeneralizedCylinderGenerator::MiterLimit = 1.0
Definition at line 744 of file SweepGenerator.h.
Referenced by EnableMitering(), Generate(), and SetMiterLimitByAngle().
Path
TArray<FVector3d> UE::Geometry::FGeneralizedCylinderGenerator::Path
Definition at line 725 of file SweepGenerator.h.
Referenced by Generate().
PathFrames
TArray<FFrame3d> UE::Geometry::FGeneralizedCylinderGenerator::PathFrames
Definition at line 729 of file SweepGenerator.h.
Referenced by Generate().
PathScales
TArray<FVector2d> UE::Geometry::FGeneralizedCylinderGenerator::PathScales
Definition at line 731 of file SweepGenerator.h.
Referenced by Generate().
PathTexCoord
TArray<float> UE::Geometry::FGeneralizedCylinderGenerator::PathTexCoord
Definition at line 797 of file SweepGenerator.h.
Referenced by Generate().
StartScale
double UE::Geometry::FGeneralizedCylinderGenerator::StartScale = 1.0
Definition at line 738 of file SweepGenerator.h.
Referenced by Generate().
UnitUVInWorldCoordinates
float UE::Geometry::FGeneralizedCylinderGenerator::UnitUVInWorldCoordinates = 100
Definition at line 771 of file SweepGenerator.h.
Referenced by Generate().
The documentation for this class was generated from the following file:
SweepGenerator.h