Unreal Engine 5.6 C++ API: TraceServices::TCachedStringStore< CharType > Class Template Reference
TraceServices::TCachedStringStore< CharType > Class Template Reference
A deduplicating persistent string store.
#include "CachedStringStore.h"
Data Structures
struct FPersistentState
Public Types
typedef TStringView< CharType > StringViewType
Public Member Functions
TCachedStringStore (const TCHAR *InCacheIdentifier, IAnalysisCache &InCache)
Create a persistent string store.
~TCachedStringStore ()
uint64 AllocatedSize ()
Get the total number of bytes used.
uint64 GetOffsetOfString (const TCHAR *String) const
Gets the offset of a string previously stored string.
const CharType * GetStringAtOffset (uint64 OffsetBytes) const
Resolve an offset to a c string.
uint32 Num () const
Get the number of unique stored string.
uint64 Store_GetOffset (const CharType *String)
Store a string, get offset back.
uint64 Store_GetOffset (const StringViewType String)
Store a string, get offset back.
const CharType * Store_GetString (const CharType *String)
Store a string, get string back.
const CharType * Store_GetString (const StringViewType String)
Store a string, get string back.
Private Member Functions
const TTuple< uint64, const CharType * > & StoreInternal (const StringViewType &String)
Private Attributes
TArray< FSharedBuffer > Blocks
CharType * BufferCursor
IAnalysisCache & Cache
uint32 CacheIndex
FPersistentState * State
TMap< uint32, TTuple< uint64, const CharType * > > StoredStrings
Static Private Attributes
static constexpr uint32 BlockSize = IAnalysisCache::BlockSizeBytes
Detailed Description
template<typename CharType>
class TraceServices::TCachedStringStore< CharType >
A deduplicating persistent string store.
Allows users to store a string in a session and retrieve it at a given offset in consecutive sessions. The store uses analysis cache to store the strings. The store is not thread safe.
Definition at line 19 of file CachedStringStore.h.
Member Typedef Documentation
StringViewType
template<typename CharType> typedef TStringView<CharType> TraceServices::TCachedStringStore< CharType >::StringViewType
Definition at line 22 of file CachedStringStore.h.
Constructor & Destructor Documentation
TCachedStringStore()
template<typename CharType> TraceServices::TCachedStringStore< CharType >::TCachedStringStore (const TCHAR * InCacheIdentifier, IAnalysisCache & InCache) inline
Create a persistent string store.
Parameters
InCacheIdentifier A unique string identifying this store.
InCache Cache to use
Definition at line 29 of file CachedStringStore.h.
~TCachedStringStore()
template<typename CharType> TraceServices::TCachedStringStore< CharType >::~TCachedStringStore () inline
Definition at line 76 of file CachedStringStore.h.
Member Function Documentation
AllocatedSize()
template<typename CharType> uint64 TraceServices::TCachedStringStore< CharType >::AllocatedSize () inline
Get the total number of bytes used.
Note that this does ot account for unused block space.
Returns
Number of bytes used to store the strings.
Definition at line 172 of file CachedStringStore.h.
GetOffsetOfString()
template<typename CharType> uint64 TraceServices::TCachedStringStore< CharType >::GetOffsetOfString (const TCHAR * String) const inline
Gets the offset of a string previously stored string.
Parameters
String A string that was stored
Returns
Offset in bytes to the string, or ~0 if the string was not found in the store.
Definition at line 103 of file CachedStringStore.h.
GetStringAtOffset()
template<typename CharType> const CharType * TraceServices::TCachedStringStore< CharType >::GetStringAtOffset (uint64 OffsetBytes) const inline
Resolve an offset to a c string.
Parameters
OffsetBytes Offset in bytes
Returns
The string at the offset or null if the offset was invalid.
Definition at line 86 of file CachedStringStore.h.
Referenced by TraceServices::TCachedStringStore< WIDECHAR >::StoreInternal().
Num()
template<typename CharType> uint32 TraceServices::TCachedStringStore< CharType >::Num () const inline
Get the number of unique stored string.
Returns
Number of strings
Definition at line 163 of file CachedStringStore.h.
Store_GetOffset() [1/2]
template<typename CharType> uint64 TraceServices::TCachedStringStore< CharType >::Store_GetOffset (const CharType * String) inline
Store a string, get offset back.
Parameters
String String to store
Returns
Offset in bytes
Definition at line 124 of file CachedStringStore.h.
Store_GetOffset() [2/2]
template<typename CharType> uint64 TraceServices::TCachedStringStore< CharType >::Store_GetOffset (const StringViewType String) inline
Store a string, get offset back.
Parameters
String String to store
Returns
Offset in bytes
Definition at line 134 of file CachedStringStore.h.
Store_GetString() [1/2]
template<typename CharType> const CharType * TraceServices::TCachedStringStore< CharType >::Store_GetString (const CharType * String) inline
Store a string, get string back.
Parameters
String String to store
Returns
Stored string
Definition at line 144 of file CachedStringStore.h.
Store_GetString() [2/2]
template<typename CharType> const CharType * TraceServices::TCachedStringStore< CharType >::Store_GetString (const StringViewType String) inline
Store a string, get string back.
Parameters
String String to store
Returns
Stored string
Definition at line 154 of file CachedStringStore.h.
StoreInternal()
template<typename CharType> const TTuple< uint64, const CharType * > & TraceServices::TCachedStringStore< CharType >::StoreInternal (const StringViewType & String) inline private
Definition at line 179 of file CachedStringStore.h.
Referenced by TraceServices::TCachedStringStore< WIDECHAR >::Store_GetOffset(), TraceServices::TCachedStringStore< WIDECHAR >::Store_GetOffset(), TraceServices::TCachedStringStore< WIDECHAR >::Store_GetString(), and TraceServices::TCachedStringStore< WIDECHAR >::Store_GetString().
Field Documentation
Blocks
template<typename CharType> TArray<FSharedBuffer> TraceServices::TCachedStringStore< CharType >::Blocks private
Definition at line 225 of file CachedStringStore.h.
BlockSize
template<typename CharType> uint32 TraceServices::TCachedStringStore< CharType >::BlockSize = IAnalysisCache::BlockSizeBytes static constexpr private
Definition at line 220 of file CachedStringStore.h.
BufferCursor
template<typename CharType> CharType* TraceServices::TCachedStringStore< CharType >::BufferCursor private
Definition at line 226 of file CachedStringStore.h.
Cache
template<typename CharType> IAnalysisCache& TraceServices::TCachedStringStore< CharType >::Cache private
Definition at line 222 of file CachedStringStore.h.
CacheIndex
template<typename CharType> uint32 TraceServices::TCachedStringStore< CharType >::CacheIndex private
Definition at line 223 of file CachedStringStore.h.
State
template<typename CharType> FPersistentState* TraceServices::TCachedStringStore< CharType >::State private
Definition at line 227 of file CachedStringStore.h.
StoredStrings
template<typename CharType> TMap<uint32, TTuple<uint64,const CharType*> > TraceServices::TCachedStringStore< CharType >::StoredStrings private
Definition at line 224 of file CachedStringStore.h.
The documentation for this class was generated from the following file:
CachedStringStore.h