Unreal Engine 5.6 C++ API: FEdGraphPinHandle Struct Reference
FEdGraphPinHandle Struct Reference
#include "EdGraphHandleTypes.h"
Public Member Functions
FORCEINLINE FEdGraphPinHandle (const UEdGraphPin *InPin)
FORCEINLINE UEdGraphPin * GetPin () const
FORCEINLINE bool operator== (const FEdGraphPinHandle &InOther) const
Public Member Functions inherited from FEdGraphNodeHandle
FORCEINLINE FEdGraphNodeHandle (const UEdGraphNode *InNode)
FORCEINLINE const UEdGraph * GetGraph () const
FORCEINLINE UEdGraphNode * GetNode () const
FORCEINLINE bool operator== (const FEdGraphNodeHandle &InOther) const
Private Attributes
FGuid PersistentPinGuid
EEdGraphPinDirection PinDirection
int32 PinIndex
FName PinName
Friends
FORCEINLINE uint32 GetTypeHash (const FEdGraphPinHandle &InHandle)
Detailed Description
Definition at line 54 of file EdGraphHandleTypes.h.
Constructor & Destructor Documentation
FEdGraphPinHandle()
FORCEINLINE FEdGraphPinHandle::FEdGraphPinHandle (const UEdGraphPin * InPin) inline
Definition at line 58 of file EdGraphHandleTypes.h.
References FEdGraphNodeHandle::FEdGraphNodeHandle(), UEdGraphPin::Direction, FORCEINLINE, UEdGraphPin::GetFName(), UEdGraphPin::GetOwningNode(), TEnumAsByte< InEnumType >::GetValue(), INDEX_NONE, PersistentPinGuid, PinDirection, PinIndex, and PinName.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
GetPin()
FORCEINLINE UEdGraphPin * FEdGraphPinHandle::GetPin () const inline
Definition at line 101 of file EdGraphHandleTypes.h.
References UEdGraphPin::Direction, FORCEINLINE, UEdGraphPin::GetFName(), FEdGraphNodeHandle::GetNode(), PersistentPinGuid, PinDirection, PinIndex, and PinName.
operator==()
FORCEINLINE bool FEdGraphPinHandle::operator== (const FEdGraphPinHandle & InOther) const inline
Definition at line 94 of file EdGraphHandleTypes.h.
References FEdGraphPinHandle(), CaseSensitive, FORCEINLINE, FEdGraphNodeHandle::operator==(), PersistentPinGuid, PinDirection, and PinName.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FEdGraphPinHandle & InHandle) friend
Definition at line 79 of file EdGraphHandleTypes.h.
References FEdGraphNodeHandle::FEdGraphNodeHandle(), FEdGraphPinHandle(), FORCEINLINE, GetTypeHash, GetTypeHash(), HashCombine(), FGuid::IsValid(), PersistentPinGuid, PinDirection, and PinName.
Referenced by GetTypeHash.
Field Documentation
PersistentPinGuid
FGuid FEdGraphPinHandle::PersistentPinGuid private
Definition at line 141 of file EdGraphHandleTypes.h.
Referenced by FEdGraphPinHandle(), GetPin(), GetTypeHash, and operator==().
PinDirection
EEdGraphPinDirection FEdGraphPinHandle::PinDirection private
Definition at line 140 of file EdGraphHandleTypes.h.
Referenced by FEdGraphPinHandle(), GetPin(), GetTypeHash, and operator==().
PinIndex
int32 FEdGraphPinHandle::PinIndex private
Definition at line 142 of file EdGraphHandleTypes.h.
Referenced by FEdGraphPinHandle(), and GetPin().
PinName
FName FEdGraphPinHandle::PinName private
Definition at line 139 of file EdGraphHandleTypes.h.
Referenced by FEdGraphPinHandle(), GetPin(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
EdGraphHandleTypes.h