Unreal Engine 5.6 C++ API: UE::RemoteObject::Handle Namespace Reference
UE::RemoteObject::Handle Namespace Reference
Data Structures
struct FRemoteObjectStub
Enumerations
enum class ERemoteReferenceType { Strong = 0 , Weak = 1 }
Functions
bool CanResolveObject (FRemoteObjectId ObjectId)
Resolves a remote object.
void ChangeOwnerServerId (const UObject *Object, FRemoteServerId NewOwnerServerId)
Sets the owner server id for a locally resident object.
void ChangePhysicsServerId (const UObject *Object, FRemoteServerId NewPhysicsServerId)
Sets the physics id where the object should go to.
void ClearAllPhysicsServerId ()
FRemoteServerId GetOwnerServerId (const UObject *Object)
Get the owner server id for a locally resident object.
FRemoteServerId GetPhysicsServerId (const UObject *Object)
Get the physics server id where the object should be simulated on.
bool IsOwned (const UObject *Object)
Checks if a locally resident object is owned by this server.
bool IsOwned (FRemoteObjectId ObjectId)
Checks if an object id is owned by this server We are only able to check if we own the object.
bool IsRemote (const UObject *Object)
Checks if an object (memory that has not yet been GC'd) is remote.
bool IsRemote (FRemoteObjectId ObjectId)
Checks if an object associated with the specified unique id is remote.
UObject * ResolveObject (const FRemoteObjectStub *Stub, ERemoteReferenceType RefType=ERemoteReferenceType::Strong)
Resolves a remote object given its stub, aborting the active transaction if the object is unavailable.
UObject * ResolveObject (UObject *Object, ERemoteReferenceType RefType=ERemoteReferenceType::Strong)
Resolves a remote object, aborting the active transaction if the object is unavailable.
void TouchResidentObject (UObject *Object)
void UpdateAllPhysicsServerId (const TMap< uint32, uint32 > &PhysicsServerMergingMap)
Enumeration Type Documentation
ERemoteReferenceType
enum class UE::RemoteObject::Handle::ERemoteReferenceType strong
Enumerator
Strong
Weak
Definition at line 56 of file RemoteObject.h.
Function Documentation
CanResolveObject()
bool UE::RemoteObject::Handle::CanResolveObject (FRemoteObjectId ObjectId)
Resolves a remote object.
Parameters
Object Object id to resolve
RefType Reference type that wants to resolve an object
Returns
True if a remote object can be resolved
References ObjectId.
ChangeOwnerServerId()
void UE::RemoteObject::Handle::ChangeOwnerServerId (const UObject * Object, FRemoteServerId NewOwnerServerId)
Sets the owner server id for a locally resident object.
ChangePhysicsServerId()
void UE::RemoteObject::Handle::ChangePhysicsServerId (const UObject * Object, FRemoteServerId NewPhysicsServerId)
Sets the physics id where the object should go to.
ClearAllPhysicsServerId()
void UE::RemoteObject::Handle::ClearAllPhysicsServerId ()
GetOwnerServerId()
FRemoteServerId UE::RemoteObject::Handle::GetOwnerServerId (const UObject * Object)
Get the owner server id for a locally resident object.
GetPhysicsServerId()
FRemoteServerId UE::RemoteObject::Handle::GetPhysicsServerId (const UObject * Object)
Get the physics server id where the object should be simulated on.
IsOwned() [1/2]
bool UE::RemoteObject::Handle::IsOwned (const UObject * Object)
Checks if a locally resident object is owned by this server.
IsOwned() [2/2]
bool UE::RemoteObject::Handle::IsOwned (FRemoteObjectId ObjectId)
Checks if an object id is owned by this server We are only able to check if we own the object.
If we don't own the object then we don't have a reliable way of knowing who the owner is, which is why the below GetOwnerServerId function requires the object be locally resident
References ObjectId.
IsRemote() [1/2]
bool UE::RemoteObject::Handle::IsRemote (const UObject * Object)
Checks if an object (memory that has not yet been GC'd) is remote.
Returns
True if the object is remote
IsRemote() [2/2]
bool UE::RemoteObject::Handle::IsRemote (FRemoteObjectId ObjectId)
Checks if an object associated with the specified unique id is remote.
Returns
True if an object associated with the specified unique id is remote
References ObjectId.
Referenced by IsObjectHandleResolved(), FRemoteObjectReference::IsRemote(), and UE::CoreUObject::Private::ResolveObjectHandleNoRead().
ResolveObject() [1/2]
UObject * UE::RemoteObject::Handle::ResolveObject (const FRemoteObjectStub * Stub, ERemoteReferenceType RefType = ERemoteReferenceType::Strong)
Resolves a remote object given its stub, aborting the active transaction if the object is unavailable.
Parameters
Stub Basic data required to migrate a remote object
RefType Reference type that wants to resolve an object
Returns
Resolved object
References Strong.
Referenced by UE::CoreUObject::Private::ResolveObjectHandleNoRead(), and UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck().
ResolveObject() [2/2]
UObject * UE::RemoteObject::Handle::ResolveObject (UObject * Object, ERemoteReferenceType RefType = ERemoteReferenceType::Strong)
Resolves a remote object, aborting the active transaction if the object is unavailable.
Parameters
Object Object to resolve (remote object memory that has not yet been GC'd)
RefType Reference type that wants to resolve an object
Returns
Resolved object
References Strong.
TouchResidentObject()
void UE::RemoteObject::Handle::TouchResidentObject (UObject * Object)
Referenced by UE::CoreUObject::Private::ResolveObjectHandleNoRead().
UpdateAllPhysicsServerId()
void UE::RemoteObject::Handle::UpdateAllPhysicsServerId (const TMap< uint32, uint32 > & PhysicsServerMergingMap)