Unreal Engine 5.6 C++ API: FInBunch Class Reference
FInBunch Class Reference
#include "DataBunch.h"
Public Member Functions
FInBunch (const FInBunch &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FInBunch (FInBunch &&)=default
FInBunch (FInBunch &InBunch, bool CopyBuffer)
FInBunch (UNetConnection *InConnection, uint8 *Src=NULL, int64 CountBits=0)
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void CountMemory (FArchive &Ar) const override
Counts the in-memory bytes used by this object.
virtual uint32 EngineNetVer () const override
Returns the engine-global network protocol version for this archive.
virtual uint32 GameNetVer () const override
Returns the game-specific network protocol version for this archive.
FInBunch & operator= (const FInBunch &)=default
FInBunch & operator= (FInBunch &&)=default
virtual void SetEngineNetVer (const uint32 InEngineNetVer) override
Sets the archive engine network version.
virtual void SetGameNetVer (const uint32 InGameNetVer) override
Sets the archive game network version.
FString ToString ()
Public Member Functions inherited from FNetBitReader
FNetBitReader (const FNetBitReader &)
FNetBitReader (FNetBitReader &&)
FNetBitReader (UPackageMap *InPackageMap=nullptr, const uint8 *Src=nullptr, int64 CountBits=0)
virtual ~FNetBitReader ()
virtual FArchive & operator<< (FName &Name) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FObjectPtr &Value) override
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (FSoftObjectPath &Value) override
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (FSoftObjectPtr &Value) override
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (struct FWeakObjectPtr &Value) override
Serializes FWeakObjectPtr value from or into this archive.
virtual FArchive & operator<< (UObject *&Object) override
Serializes an UObject value from or into this archive.
FNetBitReader & operator= (const FNetBitReader &)
FNetBitReader & operator= (FNetBitReader &&)
Public Member Functions inherited from FBitReader
FBitReader (const FBitReader &)
FBitReader (const uint8 *Src=nullptr, int64 CountBits=0)
FBitReader (FBitReader &&)
~FBitReader ()
void AppendDataFromChecked (FBitReader &Src)
void AppendDataFromChecked (uint8 *Src, uint32 NumBits)
void AppendTo (TArray< uint8 > &Buffer)
FORCEINLINE_DEBUGGABLE bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
FORCEINLINE_DEBUGGABLE void EatByteAlign ()
FORCEINLINE_DEBUGGABLE int64 GetBitsLeft () const
FORCEINLINE_DEBUGGABLE const TArray< uint8 > & GetBuffer () const
FORCEINLINE_DEBUGGABLE int64 GetBytesLeft () const
FORCEINLINE_DEBUGGABLE uint8 * GetData ()
FORCEINLINE_DEBUGGABLE const uint8 * GetData () const
FORCEINLINE_DEBUGGABLE uint8 * GetDataPosChecked ()
FORCEINLINE_DEBUGGABLE int64 GetNumBits () const
FORCEINLINE_DEBUGGABLE int64 GetNumBytes () const
FORCEINLINE_DEBUGGABLE int64 GetPosBits () const
FBitReader & operator= (const FBitReader &)
FBitReader & operator= (FBitReader &&)
FORCEINLINE_DEBUGGABLE uint8 ReadBit ()
FORCEINLINE_DEBUGGABLE uint32 ReadInt (uint32 Max)
void ResetData (FBitReader &Src, int64 CountBits, int64 CountBitsWithSlack=0)
Equivalent to SetData (reset position, copy from Src into internal buffer), but uses Reset not Empty to avoid a realloc if possible.
FORCEINLINE_DEBUGGABLE void Serialize (void *Dest, int64 LengthBytes)
PRAGMA_DISABLE_BUFFER_OVERRUN_WARNING FORCEINLINE_DEBUGGABLE void SerializeBits (void *Dest, int64 LengthBits)
virtual PRAGMA_ENABLE_BUFFER_OVERRUN_WARNING void SerializeBitsWithOffset (void *Dest, int32 DestBit, int64 LengthBits) override
FORCEINLINE_DEBUGGABLE void SerializeInt (uint32 &OutValue, uint32 ValueMax)
virtual void SerializeIntPacked (uint32 &Value) override
Packs int value into bytes of 7 bits with 8th bit for 'more'.
void SetAtEnd ()
Set the stream at the end.
void SetData (FBitReader &Src, int64 CountBits)
void SetData (TArray< uint8 > &&Src, int64 CountBits)
void SetData (uint8 *Src, int64 CountBits)
void SetOverflowed (int64 LengthBits)
Marks this bit reader as overflowed.
FORCEINLINE_DEBUGGABLE void Skip (int32 BitCount)
Public Member Functions inherited from FBitArchive
FBitArchive ()
Default Constructor.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData)
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback)
Adds external read dependency.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache ()
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization ()
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const
Returns the name of the Archive.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkScriptSerializationEnd (const UObject *Obj)
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj)
Called when an object begins serializing property data using script serialization.
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (struct FLazyObjectPtr &Value)
Serializes a lazy object pointer value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopDebugDataString ()
virtual void PopFileRegionType ()
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pop a property that was previously being serialized off the property stack.
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize)
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object)
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushDebugDataString (const FName &DebugData)
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Push a property that is currently being serialized onto the property stack.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void Seek (int64 InPos)
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params)
Serialize bulk data.
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags)
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
virtual void SetSerializedProperty (FProperty *InProperty)
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr)
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
virtual int64 Tell ()
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
virtual int64 TotalSize ()
Returns total size of the backing data storage.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Data Fields
uint8 bClose:1
uint8 bHasMustBeMappedGUIDs:1
uint8 bHasPackageMapExports:1
uint8 bIgnoreRPCs:1
uint8 bOpen:1
uint8 bPartial:1
uint8 bPartialCustomExportsFinal:1
uint8 bPartialFinal:1
uint8 bPartialInitial:1
UE_DEPRECATED(5.3, "Replication pausing is deprecated") uint8 bIsReplicationPaused uint8 bReliable:1
int32 ChIndex
FName ChName
int32 ChSequence
EChannelCloseReason CloseReason
UNetConnection * Connection
FInBunch * Next
int32 PacketId
Data Fields inherited from FNetBitReader
TPimplPtr< UE::Net::FNetResult, EPimplPtrMode::DeepCopy > ExtendedError
Stores additional error information.
UPackageMap * PackageMap = nullptr
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Additional Inherited Members
Protected Member Functions inherited from FBitReader
void SetNetVersionsFromArchive (FArchive &Source)
Copies version information used for network compatibility from Source to this archive.
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Protected Attributes inherited from FBitReader
TArray< uint8 > Buffer
int64 Num
int64 Pos
Detailed Description
Definition at line 126 of file DataBunch.h.
Constructor & Destructor Documentation
FInBunch() [1/4]
FInBunch::FInBunch (UNetConnection * InConnection, uint8 * Src = NULL, int64 CountBits = 0)
Referenced by FInBunch(), FInBunch(), FInBunch(), operator=(), and operator=().
FInBunch() [2/4]
FInBunch::FInBunch (FInBunch & InBunch, bool CopyBuffer)
References FInBunch(), and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
FInBunch() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FInBunch::FInBunch (FInBunch &&) default
References FInBunch().
FInBunch() [4/4]
FInBunch::FInBunch (const FInBunch &) default
References FInBunch().
Member Function Documentation
CountMemory()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void FInBunch::CountMemory (FArchive & Ar) const override virtual
Counts the in-memory bytes used by this object.
Reimplemented from FNetBitReader.
References Ar.
EngineNetVer()
virtual uint32 FInBunch::EngineNetVer () const override virtual
Returns the engine-global network protocol version for this archive.
Reimplemented from FArchive.
GameNetVer()
virtual uint32 FInBunch::GameNetVer () const override virtual
Returns the game-specific network protocol version for this archive.
Reimplemented from FArchive.
operator=() [1/2]
FInBunch & FInBunch::operator= (const FInBunch &) default
References FInBunch(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FInBunch & FInBunch::operator= (FInBunch &&) default
References FInBunch().
SetEngineNetVer()
virtual void FInBunch::SetEngineNetVer (const uint32 InEngineNetVer) override virtual
Sets the archive engine network version.
Reimplemented from FArchive.
SetGameNetVer()
virtual void FInBunch::SetGameNetVer (const uint32 InGameNetVer) override virtual
Sets the archive game network version.
Reimplemented from FArchive.
ToString()
FString FInBunch::ToString () inline
Definition at line 151 of file DataBunch.h.
References bClose, bHasMustBeMappedGUIDs, bHasPackageMapExports, bIgnoreRPCs, bOpen, bPartial, bPartialCustomExportsFinal, bPartialFinal, bPartialInitial, bReliable, ChIndex, ChSequence, CloseReason, FBitReader::GetNumBits(), LexToString(), PacketId, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, TEXT, and ToString().
Referenced by ToString().
Field Documentation
bClose
uint8 FInBunch::bClose
Definition at line 137 of file DataBunch.h.
Referenced by ToString().
bHasMustBeMappedGUIDs
uint8 FInBunch::bHasMustBeMappedGUIDs
Definition at line 145 of file DataBunch.h.
Referenced by ToString().
bHasPackageMapExports
uint8 FInBunch::bHasPackageMapExports
Definition at line 144 of file DataBunch.h.
Referenced by ToString().
bIgnoreRPCs
uint8 FInBunch::bIgnoreRPCs
Definition at line 147 of file DataBunch.h.
Referenced by ToString().
bOpen
uint8 FInBunch::bOpen
Definition at line 136 of file DataBunch.h.
Referenced by ToString().
bPartial
uint8 FInBunch::bPartial
Definition at line 141 of file DataBunch.h.
Referenced by ToString().
bPartialCustomExportsFinal
uint8 FInBunch::bPartialCustomExportsFinal
Definition at line 146 of file DataBunch.h.
Referenced by ToString().
bPartialFinal
uint8 FInBunch::bPartialFinal
Definition at line 143 of file DataBunch.h.
Referenced by ToString().
bPartialInitial
uint8 FInBunch::bPartialInitial
Definition at line 142 of file DataBunch.h.
Referenced by ToString().
bReliable
UE_DEPRECATED (5.3, "Replication pausing is deprecated") uint8 bIsReplicationPaused uint8 FInBunch::bReliable
Definition at line 140 of file DataBunch.h.
Referenced by ToString().
ChIndex
int32 FInBunch::ChIndex
Definition at line 133 of file DataBunch.h.
Referenced by ToString().
ChName
FName FInBunch::ChName
Definition at line 134 of file DataBunch.h.
ChSequence
int32 FInBunch::ChSequence
Definition at line 135 of file DataBunch.h.
Referenced by ToString().
CloseReason
EChannelCloseReason FInBunch::CloseReason
Definition at line 149 of file DataBunch.h.
Referenced by ToString().
Connection
UNetConnection* FInBunch::Connection
Definition at line 132 of file DataBunch.h.
Next
FInBunch* FInBunch::Next
Definition at line 131 of file DataBunch.h.
PacketId
int32 FInBunch::PacketId
Definition at line 130 of file DataBunch.h.
Referenced by ToString().
The documentation for this class was generated from the following file:
DataBunch.h