Unreal Engine 5.6 C++ Documentation: ULocalPlayerSaveGame Class Reference
ULocalPlayerSaveGame Class Reference
Abstract subclass of USaveGame that provides utility functions that let you associate a Save Game object with a specific local player.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/SaveGame.h>
Public Member Functions
virtual bool SaveGameToSlotForLocalPlayer ()
Synchronously save using the slot and user index, stalling the main thread until it completes.
virtual bool AsyncSaveGameToSlotForLocalPlayer ()
Asynchronously save to the slot and user index.
virtual APlayerController * GetLocalPlayerController () const
Returns the local player controller this is associated with, this will be valid if it is ready to save.
virtual const ULocalPlayer * GetLocalPlayer () const
Returns the local player this is associated with, this will be valid if it is ready to save.
virtual void SetLocalPlayer (const ULocalPlayer *LocalPlayer)
Associates this save game with a local player, this is called automatically during load/create.
virtual FPlatformUserId GetPlatformUserId () const
Returns the platform user to save to, based on Local Player by default.
virtual int32 GetPlatformUserIndex () const
Returns the user index to save to, based on Local Player by default.
virtual FString GetSaveSlotName () const
Returns the save slot name to use.
virtual void SetSaveSlotName (const FString &SlotName)
Sets the save slot name for any future saves.
virtual int32 GetSavedDataVersion () const
Returns the game-specific version number this was last saved/loaded as.
virtual int32 GetInvalidDataVersion () const
Returns the invalid save data version, which means it has never been saved/loaded.
virtual int32 GetLatestDataVersion () const
Returns the latest save data version, this is used when the new data is saved.
virtual bool WasLoaded () const
Returns true if this was loaded from an existing save.
virtual bool IsSaveInProgress () const
Returns true if a save is in progress.
virtual bool WasLastSaveSuccessful () const
Returns true if it has been saved at least once and the last save was successful.
virtual bool WasSaveRequested () const
Returns true if a save was ever requested, may still be in progress.
virtual void InitializeSaveGame (const ULocalPlayer *LocalPlayer, FString InSlotName, bool bWasLoaded)
Initializes this save after either loading or initial creation, automatically called by load/create functions above.
virtual void ResetToDefault ()
Resets all saved data to default values, called when the load fails or manually.
void OnResetToDefault ()
Blueprint event called to reset all saved data to default, called when the load fails or manually.
virtual void HandlePostLoad ()
Called after loading, this is not called for newly created saves.
void OnPostLoad ()
Blueprint event called after loading, is not called for newly created saves.
virtual void HandlePreSave ()
Called before saving, do any game-specific fixup here.
void OnPreSave ()
Blueprint event called before saving, do any game-specific fixup here.
virtual void HandlePostSave (bool bSuccess)
Called after saving finishes with success/failure result.
void OnPostSave (bool bSuccess)
Blueprint event called after saving finishes with success/failure result.
Static Public Member Functions
static ULocalPlayerSaveGame * LoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, APlayerController *LocalPlayerController, const FString &SlotName)
Synchronously loads a save game object in the specified slot for the local player, stalling the main thread until it completes.
static ULocalPlayerSaveGame * LoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer *LocalPlayer, const FString &SlotName)
Native version of above function, this takes a ULocalPlayer because you can have a local player before a player controller.
static bool AsyncLoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, APlayerController *LocalPlayerController, const FString &SlotName, FOnLocalPlayerSaveGameLoaded Delegate)
Asynchronously loads a save game object in the specified slot for the local player, if this returns true the delegate will get called later.
static bool AsyncLoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer *LocalPlayer, const FString &SlotName, FOnLocalPlayerSaveGameLoadedNative Delegate)
Native version of above function, this takes a ULocalPlayer and calls a native delegate.
static ULocalPlayerSaveGame * CreateNewSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer *LocalPlayer, const FString &SlotName)
Create a brand new save game, possibly ready for saving but without trying to load from disk.
Protected Member Functions
virtual void ProcessSaveComplete (const FString &SlotName, const int32 UserIndex, bool bSuccess, int32 SaveRequest)
Internal callback that will call HandlePostSave.
Static Protected Member Functions
static ULocalPlayerSaveGame * ProcessLoadedSave (USaveGame *BaseSave, const FString &SlotName, const int32 UserIndex, TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer *LocalPlayer)
Internal helper function used by both the sync and async save.
Protected Attributes
TObjectPtr< const ULocalPlayer > OwningPlayer
The local player this is connected to, can be null if subclasses override Get/Set Local Player or it hasn't been initialized.
FString SaveSlotName
The slot name this was loaded from and that will be used to save to in the future.
int32 SavedDataVersion = 0
The value of GetLatestDataVersion when this was last saved.
int32 LoadedDataVersion = -1
The value of SavedDataVersion when a save was last loaded, this will be -1 for newly created saves.
int32 CurrentSaveRequest = 0
Integer that is incremented every time a save has been requested in the current session, can be used to know if one is in progress.
int32 LastSuccessfulSaveRequest = 0
Integer that is set when a save completes successfully, if this equals RequestedSaveCount then the last save was successful.
int32 LastErrorSaveRequest = 0
Integer that is set when a save fails.
Detailed Description
Abstract subclass of USaveGame that provides utility functions that let you associate a Save Game object with a specific local player.
These objects can also be loaded using the functions on GameplayStatics, but you would need to call functions like InitializeSaveGame manually. For simple games, it is fine to blueprint this class directly and add parameters and override functions in blueprint, but for complicated games you will want to subclass this in native code and set up proper versioning.
Definition at line 46 of file SaveGame.h.
Member Function Documentation
AsyncLoadOrCreateSaveGameForLocalPlayer() [1/2]
bool ULocalPlayerSaveGame::AsyncLoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, APlayerController * LocalPlayerController, const FString & SlotName, FOnLocalPlayerSaveGameLoaded Delegate) static
Asynchronously loads a save game object in the specified slot for the local player, if this returns true the delegate will get called later.
False means the load was never scheduled, otherwise it will create and initialize a new instance before calling the delegate if loading failed.
References AsyncLoadOrCreateSaveGameForLocalPlayer().
AsyncLoadOrCreateSaveGameForLocalPlayer() [2/2]
bool ULocalPlayerSaveGame::AsyncLoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer * LocalPlayer, const FString & SlotName, FOnLocalPlayerSaveGameLoadedNative Delegate) static
Native version of above function, this takes a ULocalPlayer and calls a native delegate.
False means the load was never scheduled, otherwise it will create and initialize a new instance before calling the delegate if loading failed.
References AsyncLoadOrCreateSaveGameForLocalPlayer().
AsyncSaveGameToSlotForLocalPlayer()
virtual bool ULocalPlayerSaveGame::AsyncSaveGameToSlotForLocalPlayer () virtual
Asynchronously save to the slot and user index.
This will return true if the save was requested, and errors should be handled by the HandlePostSave function after the save succeeds or fails
References AsyncSaveGameToSlotForLocalPlayer().
CreateNewSaveGameForLocalPlayer()
ULocalPlayerSaveGame * ULocalPlayerSaveGame::CreateNewSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer * LocalPlayer, const FString & SlotName) static
Create a brand new save game, possibly ready for saving but without trying to load from disk.
This will always succeed.
References CreateNewSaveGameForLocalPlayer().
GetInvalidDataVersion()
virtual int32 ULocalPlayerSaveGame::GetInvalidDataVersion () const virtual
Returns the invalid save data version, which means it has never been saved/loaded.
References GetInvalidDataVersion().
GetLatestDataVersion()
virtual int32 ULocalPlayerSaveGame::GetLatestDataVersion () const virtual
Returns the latest save data version, this is used when the new data is saved.
References GetLatestDataVersion().
GetLocalPlayer()
virtual const ULocalPlayer * ULocalPlayerSaveGame::GetLocalPlayer () const virtual
Returns the local player this is associated with, this will be valid if it is ready to save.
References GetLocalPlayer().
GetLocalPlayerController()
virtual APlayerController * ULocalPlayerSaveGame::GetLocalPlayerController () const virtual
Returns the local player controller this is associated with, this will be valid if it is ready to save.
References GetLocalPlayerController().
GetPlatformUserId()
virtual FPlatformUserId ULocalPlayerSaveGame::GetPlatformUserId () const virtual
Returns the platform user to save to, based on Local Player by default.
References GetPlatformUserId().
GetPlatformUserIndex()
virtual int32 ULocalPlayerSaveGame::GetPlatformUserIndex () const virtual
Returns the user index to save to, based on Local Player by default.
References GetPlatformUserIndex().
GetSavedDataVersion()
virtual int32 ULocalPlayerSaveGame::GetSavedDataVersion () const virtual
Returns the game-specific version number this was last saved/loaded as.
References GetSavedDataVersion().
GetSaveSlotName()
virtual FString ULocalPlayerSaveGame::GetSaveSlotName () const virtual
Returns the save slot name to use.
References GetSaveSlotName().
HandlePostLoad()
virtual void ULocalPlayerSaveGame::HandlePostLoad () virtual
Called after loading, this is not called for newly created saves.
References HandlePostLoad().
HandlePostSave()
virtual void ULocalPlayerSaveGame::HandlePostSave (bool bSuccess) virtual
Called after saving finishes with success/failure result.
References HandlePostSave().
HandlePreSave()
virtual void ULocalPlayerSaveGame::HandlePreSave () virtual
Called before saving, do any game-specific fixup here.
References HandlePreSave().
InitializeSaveGame()
virtual void ULocalPlayerSaveGame::InitializeSaveGame (const ULocalPlayer * LocalPlayer, FString InSlotName, bool bWasLoaded) virtual
Initializes this save after either loading or initial creation, automatically called by load/create functions above.
References InitializeSaveGame().
IsSaveInProgress()
virtual bool ULocalPlayerSaveGame::IsSaveInProgress () const virtual
Returns true if a save is in progress.
References IsSaveInProgress().
LoadOrCreateSaveGameForLocalPlayer() [1/2]
ULocalPlayerSaveGame * ULocalPlayerSaveGame::LoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, APlayerController * LocalPlayerController, const FString & SlotName) static
Synchronously loads a save game object in the specified slot for the local player, stalling the main thread until it completes.
This will return null for invalid parameters, but will create a new instance if the parameters are valid but loading fails.
References LoadOrCreateSaveGameForLocalPlayer().
LoadOrCreateSaveGameForLocalPlayer() [2/2]
ULocalPlayerSaveGame * ULocalPlayerSaveGame::LoadOrCreateSaveGameForLocalPlayer (TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer * LocalPlayer, const FString & SlotName) static
Native version of above function, this takes a ULocalPlayer because you can have a local player before a player controller.
This will return null for invalid parameters, but will create a new instance if the parameters are valid but loading fails.
References LoadOrCreateSaveGameForLocalPlayer().
OnPostLoad()
void ULocalPlayerSaveGame::OnPostLoad ()
Blueprint event called after loading, is not called for newly created saves.
References OnPostLoad().
OnPostSave()
void ULocalPlayerSaveGame::OnPostSave (bool bSuccess)
Blueprint event called after saving finishes with success/failure result.
References OnPostSave().
OnPreSave()
void ULocalPlayerSaveGame::OnPreSave ()
Blueprint event called before saving, do any game-specific fixup here.
References OnPreSave().
OnResetToDefault()
void ULocalPlayerSaveGame::OnResetToDefault ()
Blueprint event called to reset all saved data to default, called when the load fails or manually.
References OnResetToDefault().
ProcessLoadedSave()
ULocalPlayerSaveGame * ULocalPlayerSaveGame::ProcessLoadedSave (USaveGame * BaseSave, const FString & SlotName, const int32 UserIndex, TSubclassOf< ULocalPlayerSaveGame > SaveGameClass, const ULocalPlayer * LocalPlayer) static protected
Internal helper function used by both the sync and async save.
References ProcessLoadedSave().
ProcessSaveComplete()
virtual void ULocalPlayerSaveGame::ProcessSaveComplete (const FString & SlotName, const int32 UserIndex, bool bSuccess, int32 SaveRequest) protected virtual
Internal callback that will call HandlePostSave.
References ProcessSaveComplete().
ResetToDefault()
virtual void ULocalPlayerSaveGame::ResetToDefault () virtual
Resets all saved data to default values, called when the load fails or manually.
References ResetToDefault().
SaveGameToSlotForLocalPlayer()
virtual bool ULocalPlayerSaveGame::SaveGameToSlotForLocalPlayer () virtual
Synchronously save using the slot and user index, stalling the main thread until it completes.
This will return true if the save was requested, and errors should be handled by the HandlePostSave function that will be called immediately.
References SaveGameToSlotForLocalPlayer().
SetLocalPlayer()
virtual void ULocalPlayerSaveGame::SetLocalPlayer (const ULocalPlayer * LocalPlayer) virtual
Associates this save game with a local player, this is called automatically during load/create.
References SetLocalPlayer().
SetSaveSlotName()
virtual void ULocalPlayerSaveGame::SetSaveSlotName (const FString & SlotName) virtual
Sets the save slot name for any future saves.
References SetSaveSlotName().
WasLastSaveSuccessful()
virtual bool ULocalPlayerSaveGame::WasLastSaveSuccessful () const virtual
Returns true if it has been saved at least once and the last save was successful.
References WasLastSaveSuccessful().
WasLoaded()
virtual bool ULocalPlayerSaveGame::WasLoaded () const virtual
Returns true if this was loaded from an existing save.
References WasLoaded().
WasSaveRequested()
virtual bool ULocalPlayerSaveGame::WasSaveRequested () const virtual
Returns true if a save was ever requested, may still be in progress.
References WasSaveRequested().
Member Data Documentation
CurrentSaveRequest
int32 ULocalPlayerSaveGame::CurrentSaveRequest = 0 protected
Integer that is incremented every time a save has been requested in the current session, can be used to know if one is in progress.
Definition at line 216 of file SaveGame.h.
LastErrorSaveRequest
int32 ULocalPlayerSaveGame::LastErrorSaveRequest = 0 protected
Integer that is set when a save fails.
Definition at line 224 of file SaveGame.h.
LastSuccessfulSaveRequest
int32 ULocalPlayerSaveGame::LastSuccessfulSaveRequest = 0 protected
Integer that is set when a save completes successfully, if this equals RequestedSaveCount then the last save was successful.
Definition at line 220 of file SaveGame.h.
LoadedDataVersion
int32 ULocalPlayerSaveGame::LoadedDataVersion = -1 protected
The value of SavedDataVersion when a save was last loaded, this will be -1 for newly created saves.
Definition at line 211 of file SaveGame.h.
OwningPlayer
TObjectPtr<const ULocalPlayer> ULocalPlayerSaveGame::OwningPlayer protected
The local player this is connected to, can be null if subclasses override Get/Set Local Player or it hasn't been initialized.
Definition at line 193 of file SaveGame.h.
SavedDataVersion
int32 ULocalPlayerSaveGame::SavedDataVersion = 0 protected
The value of GetLatestDataVersion when this was last saved.
Subclasses can override GetLatestDataVersion and then handle fixups in HandlePostLoad. This defaults to 0 so old save games that didn't previously subclass ULocalPlayerSaveGame will have 0 instead of the invalid version.
Definition at line 205 of file SaveGame.h.
SaveSlotName
FString ULocalPlayerSaveGame::SaveSlotName protected
The slot name this was loaded from and that will be used to save to in the future.
Definition at line 197 of file SaveGame.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/SaveGame.h