Unreal Engine 5.6 C++ API: FNetSimCueDispatcher Struct Reference
FNetSimCueDispatcher Struct Reference abstract
#include "NetworkPredictionCues.h"
Data Structures
struct FContext
Public Member Functions
virtual ~FNetSimCueDispatcher ()=default
const FContext & GetContext () const
virtual FString GetDebugName () const =0
template<typename T, typename... ArgsType>
void Invoke (ArgsType &&... Args)
void PopContext ()
void PushContext (const FContext &InContext)
Protected Member Functions
bool EnsureValidContext ()
TArray< FSavedCue > & GetBuffer (const bool &bTransient)
Protected Attributes
FContext Context
int32 RollbackFrame = INDEX_NONE
TArray< FSavedCue > SavedCues
TArray< FSavedCue > TransientCues
Detailed Description
Definition at line 448 of file NetworkPredictionCues.h.
Constructor & Destructor Documentation
~FNetSimCueDispatcher()
virtual FNetSimCueDispatcher::~FNetSimCueDispatcher () virtual default
Member Function Documentation
EnsureValidContext()
bool FNetSimCueDispatcher::EnsureValidContext () inline protected
Definition at line 538 of file NetworkPredictionCues.h.
References Context, None, and npEnsure.
Referenced by Invoke().
GetBuffer()
TArray< FSavedCue > & FNetSimCueDispatcher::GetBuffer (const bool & bTransient) inline protected
Definition at line 553 of file NetworkPredictionCues.h.
References SavedCues, and TransientCues.
Referenced by Invoke().
GetContext()
const FContext & FNetSimCueDispatcher::GetContext () const inline
Definition at line 563 of file NetworkPredictionCues.h.
References Context.
GetDebugName()
virtual FString FNetSimCueDispatcher::GetDebugName () const pure virtual
Implemented in TNetSimCueDispatcher< ModelDef >.
Referenced by Invoke().
Invoke()
template<typename T, typename... ArgsType> void FNetSimCueDispatcher::Invoke (ArgsType &&... Args) inline
Definition at line 462 of file NetworkPredictionCues.h.
References All, Authority, Context, TArray< InElementType, InAllocatorType >::Emplace_GetRef(), EnsureValidContext(), EnumHasAnyFlags(), Forward(), FGlobalCueTypeTable::Get(), GetBuffer(), GetDebugName(), GetTypeName(), INDEX_NONE, FGlobalCueTypeTable::IsRegisterationTypeInfoDirty(), Log, MoveTempIfPossible(), None, npCheckSlow, npEnsure, npEnsureSlow, TNetSimCueTraits< TCue >::ReplicationTarget, Resimulate, TNetSimCueTraits< TCue >::Resimulate, RollbackFrame, SavedCues, TNetSimCueTraits< TCue >::SimTickMask(), TEXT, and UE_LOG.
PopContext()
void FNetSimCueDispatcher::PopContext () inline
Definition at line 562 of file NetworkPredictionCues.h.
References Context.
PushContext()
void FNetSimCueDispatcher::PushContext (const FContext & InContext) inline
Definition at line 561 of file NetworkPredictionCues.h.
References Context.
Field Documentation
Context
FContext FNetSimCueDispatcher::Context protected
Definition at line 555 of file NetworkPredictionCues.h.
Referenced by EnsureValidContext(), GetContext(), Invoke(), PopContext(), and PushContext().
RollbackFrame
int32 FNetSimCueDispatcher::RollbackFrame = INDEX_NONE protected
Definition at line 556 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), Invoke(), and TNetSimCueDispatcher< ModelDef >::NotifyRollback().
SavedCues
TArray<FSavedCue> FNetSimCueDispatcher::SavedCues protected
Definition at line 551 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), GetBuffer(), Invoke(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), TNetSimCueDispatcher< ModelDef >::NetSendSavedCues(), and TNetSimCueDispatcher< ModelDef >::NotifyRollback().
TransientCues
TArray<FSavedCue> FNetSimCueDispatcher::TransientCues protected
Definition at line 552 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), and GetBuffer().
The documentation for this struct was generated from the following file:
NetworkPredictionCues.h