Unreal Engine 5.6 C++ API: FAnimationCacheBonesContext Struct Reference
FAnimationCacheBonesContext Struct Reference
Context passed around when RequiredBones array changed and cached bones indices have to be refreshed.
#include "AnimNodeBase.h"
Public Member Functions
FAnimationCacheBonesContext (FAnimInstanceProxy *InAnimInstanceProxy)
FAnimationCacheBonesContext WithNodeId (int32 InNodeId) const
Public Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext ()
FAnimationBaseContext (const FAnimationBaseContext &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAnimationBaseContext (FAnimationBaseContext &&)=default
template<typename TGraphMessageType>
TGraphMessageType * FindMessage (TFunctionRef< bool(TGraphMessageType &)> InFunction) const
IAnimClassInterface * GetAnimClass () const
UObject * GetAnimInstanceObject () const
int32 GetCurrentNodeId () const
template<typename TGraphMessageType>
TGraphMessageType * GetMessage () const
template<typename TGraphMessageType>
TGraphMessageType & GetMessageChecked () const
int32 GetPreviousNodeId () const
bool IsActive () const
FAnimationBaseContext & operator= (const FAnimationBaseContext &)=default
FAnimationBaseContext & operator= (FAnimationBaseContext &&)=default
void SetNodeId (int32 InNodeId)
void SetNodeIds (const FAnimationBaseContext &InContext)
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") FScopedAnimNodeTracker TrackAncestor(NodeType *Node) const
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") NodeType *GetAncestor() const
Additional Inherited Members
Data Fields inherited from FAnimationBaseContext
FAnimInstanceProxy * AnimInstanceProxy
FAnimationUpdateSharedContext * SharedContext
Protected Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext (FAnimInstanceProxy *InAnimInstanceProxy, FAnimationUpdateSharedContext *InSharedContext=nullptr)
FAnimationBaseContext (UAnimInstance *InAnimInstance)
void LogMessageInternal (FName InLogType, const TSharedRef< FTokenizedMessage > &InMessage) const
Interface for node contexts to register log messages with the proxy.
Protected Attributes inherited from FAnimationBaseContext
bool bIsActive = true
int32 CurrentNodeId
int32 PreviousNodeId
Detailed Description
Context passed around when RequiredBones array changed and cached bones indices have to be refreshed.
(RequiredBones array changed because of an LOD switch for example)
Definition at line 336 of file AnimNodeBase.h.
Constructor & Destructor Documentation
FAnimationCacheBonesContext()
FAnimationCacheBonesContext::FAnimationCacheBonesContext (FAnimInstanceProxy * InAnimInstanceProxy) inline
Definition at line 339 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext().
Referenced by WithNodeId().
Member Function Documentation
WithNodeId()
FAnimationCacheBonesContext FAnimationCacheBonesContext::WithNodeId (int32 InNodeId) const inline
Definition at line 344 of file AnimNodeBase.h.
References FAnimationCacheBonesContext().
The documentation for this struct was generated from the following file:
AnimNodeBase.h