Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModel Class Reference
UE::Sequencer::FViewModel Class Reference
Base class for a sequencer data model.
#include "ViewModel.h"
Public Member Functions
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Protected Member Functions
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Private Types
enum class ESetParentResult { AlreadySameParent , ChangedParent , ClearedParent }
Private Member Functions
virtual void OnConstruct ()
Called once for this model when it is added to a parent that has valid shared data.
virtual void OnDestruct ()
ESetParentResult SetParentOnly (const TSharedPtr< FViewModel > &NewParent, bool bReportChanges=true)
Private Attributes
int32 ActiveIterationCount
Counter that is non-zero when this model is actively being iterated that enables detection of invalid move operations during iteration.
uint8 bNeedsConstruction: 1
Flag to track whether this view model needs to be constructed.
FViewModelListHead * FirstChildListHead
List of children data models.
friend FParentFirstChildIterator
friend FScopedViewModelListHead
friend FViewModelChildren
friend FViewModelHierarchyOperation
friend FViewModelIterationState
friend FViewModelListHead
friend FViewModelListIterator
friend FViewModelListLink
FViewModelListLink Link
Link to siblings of this data model.
uint32 ModelID
Non-deterministic, non-persistent, serially increasing model ID unique to this instance.
TSharedPtr< FSharedViewModelData > SharedData
Data that is shared between all view-models in this hierarchy.
TWeakPtr< FViewModel > WeakParent
Parent of this data model.
Additional Inherited Members
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Detailed Description
Base class for a sequencer data model.
This might wrap an underlying UObject, or be a purely logical construct for the sequencer UI.
WARNING: most of the casting and hierarchy related methods are not safe to call from a sub-class' constructor because they rely on shared-pointers to be available for this.
Definition at line 35 of file ViewModel.h.
Member Enumeration Documentation
ESetParentResult
enum class UE::Sequencer::FViewModel::ESetParentResult strong private
Enumerator
AlreadySameParent
ChangedParent
ClearedParent
Definition at line 255 of file ViewModel.h.
Constructor & Destructor Documentation
FViewModel() [1/2]
UE::Sequencer::FViewModel::FViewModel ()
Builds a new data model.
Referenced by FViewModel(), GetAncestorsOfType(), GetDescendantsOfType(), operator=(), UE::Sequencer::FBindingLifetimeOverlayModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FCategoryModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FChannelGroupModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FChannelModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FEditorViewModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FLayerBarModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FOutlinerSpacer::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FOutlinerViewModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FSectionModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FSequenceModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FSharedViewModelData::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FTrackAreaViewModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FTrackAreaViewSpace::UE_SEQUENCER_DECLARE_CASTABLE(), and UE_SEQUENCER_DECLARE_CASTABLE().
FViewModel() [2/2]
UE::Sequencer::FViewModel::FViewModel (const FViewModel &) delete
References FViewModel().
~FViewModel()
virtual UE::Sequencer::FViewModel::~FViewModel () virtual
Member Function Documentation
AddDynamicExtension() [1/2]
template<typename T, typename... InArgTypes> T & UE::Sequencer::FViewModel::AddDynamicExtension (const TViewModelTypeID< T > & TypeID, InArgTypes &&... Args) inline
Adds a dynamic extension to this data model.
Definition at line 71 of file ViewModel.h.
References AddDynamicExtension(), and Forward().
AddDynamicExtension() [2/2]
template<typename T, typename... InArgTypes> T & UE::Sequencer::FViewModel::AddDynamicExtension (InArgTypes &&... Args) inline
Adds a dynamic extension to this data model.
Definition at line 56 of file ViewModel.h.
References UE::Sequencer::FDynamicExtensionContainer::AddDynamicExtension(), TSharedFromThis< FViewModel >::AsShared(), UE::Sequencer::ICastable::CastThis(), UE::Sequencer::ICastable::DynamicTypes, Forward(), and TTypedTagStaticImpl< TagT >::StaticImpl.
Referenced by AddDynamicExtension().
CastParent()
template<typename T> TViewModelPtr< T > UE::Sequencer::FViewModel::CastParent () const inline
Gets the parent data model.
Definition at line 129 of file ViewModel.h.
References Parent, and WeakParent.
CastThisShared() [1/2]
template<typename T> TViewModelPtr< T > UE::Sequencer::FViewModel::CastThisShared () inline
Casts this data model to an extension, or to a child class implementation.
Definition at line 78 of file ViewModel.h.
References TSharedFromThis< FViewModel >::AsShared(), UE::Sequencer::FDynamicExtensionContainer::CastDynamic(), and UE::Sequencer::ICastable::CastThis().
CastThisShared() [2/2]
template<typename T> TViewModelPtr< const T > UE::Sequencer::FViewModel::CastThisShared () const inline
Casts this data model to an extension, or to a child class implementation.
Definition at line 86 of file ViewModel.h.
References TSharedFromThis< FViewModel >::AsShared(), UE::Sequencer::FDynamicExtensionContainer::CastDynamic(), and UE::Sequencer::ICastable::CastThis().
CastThisSharedChecked() [1/2]
template<typename T> TSharedPtr< T > UE::Sequencer::FViewModel::CastThisSharedChecked () inline
Casts this data model to an extension, or to a child class implementation.
Definition at line 94 of file ViewModel.h.
References TSharedFromThis< FViewModel >::AsShared(), UE::Sequencer::FDynamicExtensionContainer::CastDynamicChecked(), and UE::Sequencer::ICastable::CastThisChecked().
CastThisSharedChecked() [2/2]
template<typename T> TSharedPtr< const T > UE::Sequencer::FViewModel::CastThisSharedChecked () const inline
Casts this data model to an extension, or to a child class implementation.
Definition at line 102 of file ViewModel.h.
References TSharedFromThis< FViewModel >::AsShared(), UE::Sequencer::FDynamicExtensionContainer::CastDynamic(), and UE::Sequencer::ICastable::CastThisChecked().
DiscardAllChildren()
void UE::Sequencer::FViewModel::DiscardAllChildren ()
Unlinks the head of the children list.
FindAncestorOfType() [1/2]
template<typename T> TViewModelPtr< T > UE::Sequencer::FViewModel::FindAncestorOfType (bool bIncludeThis = false) const inline
Finds the first ancestor view model that implements the given type.
Definition at line 209 of file ViewModel.h.
References GetAncestorsOfType().
Referenced by FSequencerTrackFilter_ModelType< InModelType >::PassesFilter().
FindAncestorOfType() [2/2]
FViewModelPtr UE::Sequencer::FViewModel::FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis = false) const
Finds a parent data model of a given type among the ancestry of this data model.
FindAncestorOfTypes()
FViewModelPtr UE::Sequencer::FViewModel::FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis = false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
FindChildList()
TOptional< FViewModelChildren > UE::Sequencer::FViewModel::FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
GetAncestors()
FParentModelIterator UE::Sequencer::FViewModel::GetAncestors (bool bIncludeThis = false) const
Iterates over the ancestry of this data model.
GetAncestorsOfType()
template<typename T> TParentModelIterator< T > UE::Sequencer::FViewModel::GetAncestorsOfType (bool bIncludeThis = false) const inline
Iterates over all ancestors of a given time along the ancestry of this data model.
Definition at line 238 of file ViewModel.h.
References FViewModel(), and TSharedFromThis< FViewModel >::SharedThis().
Referenced by FindAncestorOfType().
GetChildList()
FViewModelChildren UE::Sequencer::FViewModel::GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
Asserts on failure.
References FViewModelChildren.
GetChildren()
FViewModelListIterator UE::Sequencer::FViewModel::GetChildren (EViewModelListType InFilter = EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
References UE::Sequencer::Everything, and FViewModelListIterator.
GetChildrenForList()
FViewModelChildren UE::Sequencer::FViewModel::GetChildrenForList (FViewModelListHead * ListHead) protected
Retrieve the children for the specified child list head.
References FViewModelChildren, and FViewModelListHead.
GetChildrenOfType()
template<typename T> TViewModelListIterator< T > UE::Sequencer::FViewModel::GetChildrenOfType (EViewModelListType InFilter = EViewModelListType::Everything) const inline
Gets children of a given type from the view-model's children lists, or the specified list.
Definition at line 181 of file ViewModel.h.
References UE::Sequencer::Everything, and FirstChildListHead.
GetDescendants()
FParentFirstChildIterator UE::Sequencer::FViewModel::GetDescendants (bool bIncludeThis = false, EViewModelListType InFilter = EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
References UE::Sequencer::Everything, and FParentFirstChildIterator.
GetDescendantsOfType() [1/2]
template<typename T> TParentFirstChildIterator< T > UE::Sequencer::FViewModel::GetDescendantsOfType (bool bIncludeThis = false, EViewModelListType InFilter = EViewModelListType::Everything) const inline
Gets all children and descendants of a given type in the hierarchy below this data model.
Definition at line 200 of file ViewModel.h.
References FViewModel(), TSharedFromThis< FViewModel >::AsShared(), and UE::Sequencer::Everything.
GetDescendantsOfType() [2/2]
void UE::Sequencer::FViewModel::GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > & OutChildren, EViewModelListType InFilter = EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
References UE::Sequencer::Everything.
GetHierarchicalDepth()
int32 UE::Sequencer::FViewModel::GetHierarchicalDepth () const inline
Gets the hierarchical depth of this data model, i.e.
the number of levels to the top-most parent.
Definition at line 112 of file ViewModel.h.
References Depth, Parent, and WeakParent.
GetModelID()
uint32 UE::Sequencer::FViewModel::GetModelID () const inline
Get this model's unique, non-persistent and non-deterministic ID.
Definition at line 140 of file ViewModel.h.
References ModelID.
Referenced by UE::Sequencer::TFlagStateCacheExtension< FlagsType >::GetCachedFlags(), and UE::Sequencer::TFlagStateCacheExtension< FlagsType >::PostVisitChildren().
GetNextSibling()
TSharedPtr< FViewModel > UE::Sequencer::FViewModel::GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
GetParent()
FViewModelPtr UE::Sequencer::FViewModel::GetParent () const
Gets the parent data model.
GetPreviousSibling()
TSharedPtr< FViewModel > UE::Sequencer::FViewModel::GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
GetRoot()
FViewModelPtr UE::Sequencer::FViewModel::GetRoot () const
Returns the root model of the hierarchy, i.e.
the parent model that has no parent
GetSharedData()
TSharedPtr< FSharedViewModelData > UE::Sequencer::FViewModel::GetSharedData () const
HasChildren()
bool UE::Sequencer::FViewModel::HasChildren () const
Returns whether this model has any children in any of its child lists.
IsConstructed()
bool UE::Sequencer::FViewModel::IsConstructed () const
OnConstruct()
virtual void UE::Sequencer::FViewModel::OnConstruct () inline private virtual
Called once for this model when it is added to a parent that has valid shared data.
Reimplemented in UE::Sequencer::FBindingLifetimeTrackModel, UE::Sequencer::FFolderModel, UE::Sequencer::FLayerBarModel, UE::Sequencer::FObjectBindingModel, UE::Sequencer::FPossessableModel, UE::Sequencer::FSpawnableModel, UE::Sequencer::FTimeWarpTrackModel, UE::Sequencer::FTrackAreaViewModel, and UE::Sequencer::FTrackModel.
Definition at line 264 of file ViewModel.h.
OnDestruct()
virtual void UE::Sequencer::FViewModel::OnDestruct () inline private virtual
Reimplemented in UE::Sequencer::FLayerBarModel.
Definition at line 265 of file ViewModel.h.
operator=()
FViewModel & UE::Sequencer::FViewModel::operator= (const FViewModel &) delete
References FViewModel().
RegisterChildList()
void UE::Sequencer::FViewModel::RegisterChildList (FViewModelListHead * InChildren) protected
Chain a new children list to the existing children lists.
References FViewModelListHead.
RemoveFromParent()
void UE::Sequencer::FViewModel::RemoveFromParent ()
Remove this model from its parent.
SetParentOnly()
ESetParentResult UE::Sequencer::FViewModel::SetParentOnly (const TSharedPtr< FViewModel > & NewParent, bool bReportChanges = true) private
SetSharedData()
void UE::Sequencer::FViewModel::SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
SetSharedDataFromConstructor()
void UE::Sequencer::FViewModel::SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData) protected
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FViewModel::UE_SEQUENCER_DECLARE_CASTABLE (FViewModel , FDynamicExtensionContainer)
References UE::Sequencer::FDynamicExtensionContainer::FDynamicExtensionContainer(), and FViewModel().
Field Documentation
ActiveIterationCount
int32 UE::Sequencer::FViewModel::ActiveIterationCount private
Counter that is non-zero when this model is actively being iterated that enables detection of invalid move operations during iteration.
Note: this is not set when the model is only a prospective candidate for iteration (ie a sibling of an item that an iterator is currently looking at). Such models are safe to move due to children being linked lists
Definition at line 293 of file ViewModel.h.
bNeedsConstruction
uint8 UE::Sequencer::FViewModel::bNeedsConstruction private
Flag to track whether this view model needs to be constructed.
Definition at line 301 of file ViewModel.h.
FirstChildListHead
FViewModelListHead* UE::Sequencer::FViewModel::FirstChildListHead private
List of children data models.
Definition at line 283 of file ViewModel.h.
Referenced by GetChildrenOfType().
FParentFirstChildIterator
friend UE::Sequencer::FViewModel::FParentFirstChildIterator private
Definition at line 272 of file ViewModel.h.
Referenced by GetDescendants().
FScopedViewModelListHead
friend UE::Sequencer::FViewModel::FScopedViewModelListHead private
Definition at line 269 of file ViewModel.h.
FViewModelChildren
friend UE::Sequencer::FViewModel::FViewModelChildren private
Definition at line 267 of file ViewModel.h.
Referenced by GetChildList(), GetChildrenForList(), and UE::Sequencer::FEditorViewModel::GetEditorPanels().
FViewModelHierarchyOperation
friend UE::Sequencer::FViewModel::FViewModelHierarchyOperation private
Definition at line 273 of file ViewModel.h.
FViewModelIterationState
friend UE::Sequencer::FViewModel::FViewModelIterationState private
Definition at line 274 of file ViewModel.h.
FViewModelListHead
friend UE::Sequencer::FViewModel::FViewModelListHead private
Definition at line 268 of file ViewModel.h.
Referenced by GetChildrenForList(), and RegisterChildList().
FViewModelListIterator
friend UE::Sequencer::FViewModel::FViewModelListIterator private
Definition at line 271 of file ViewModel.h.
Referenced by GetChildren().
FViewModelListLink
friend UE::Sequencer::FViewModel::FViewModelListLink private
Definition at line 270 of file ViewModel.h.
Link
FViewModelListLink UE::Sequencer::FViewModel::Link private
Link to siblings of this data model.
Definition at line 281 of file ViewModel.h.
ModelID
uint32 UE::Sequencer::FViewModel::ModelID private
Non-deterministic, non-persistent, serially increasing model ID unique to this instance.
Definition at line 296 of file ViewModel.h.
Referenced by GetModelID().
SharedData
TSharedPtr<FSharedViewModelData> UE::Sequencer::FViewModel::SharedData private
Data that is shared between all view-models in this hierarchy.
Definition at line 279 of file ViewModel.h.
WeakParent
TWeakPtr<FViewModel> UE::Sequencer::FViewModel::WeakParent private
Parent of this data model.
Definition at line 277 of file ViewModel.h.
Referenced by CastParent(), and GetHierarchicalDepth().
The documentation for this class was generated from the following file:
ViewModel.h