Unreal Engine 5.6 C++ API: IStereoLayers::FShapeWrapper Struct Reference
IStereoLayers::FShapeWrapper Struct Reference
Public Member Functions
FShapeWrapper (const FShapeWrapper &In)
FShapeWrapper (FShapeWrapper &&In)
FShapeWrapper (IStereoLayerShape *InWrapped)
bool IsValid () const
FShapeWrapper & operator= (const FShapeWrapper &In)
FShapeWrapper & operator= (FShapeWrapper &&In)
FShapeWrapper & operator= (IStereoLayerShape *InWrapped)
Data Fields
TUniquePtr< IStereoLayerShape > Wrapped
Detailed Description
Definition at line 22 of file IStereoLayers.h.
Constructor & Destructor Documentation
FShapeWrapper() [1/3]
IStereoLayers::FShapeWrapper::FShapeWrapper (IStereoLayerShape * InWrapped) inline
Definition at line 25 of file IStereoLayers.h.
References Wrapped.
Referenced by FShapeWrapper(), FShapeWrapper(), operator=(), operator=(), and operator=().
FShapeWrapper() [2/3]
IStereoLayers::FShapeWrapper::FShapeWrapper (const FShapeWrapper & In) inline
Definition at line 29 of file IStereoLayers.h.
References FShapeWrapper(), IsValid(), and Wrapped.
FShapeWrapper() [3/3]
IStereoLayers::FShapeWrapper::FShapeWrapper (FShapeWrapper && In) inline
Definition at line 33 of file IStereoLayers.h.
References FShapeWrapper(), MoveTemp(), and Wrapped.
Member Function Documentation
IsValid()
bool IStereoLayers::FShapeWrapper::IsValid () const inline
Definition at line 55 of file IStereoLayers.h.
References Wrapped.
Referenced by FShapeWrapper(), and operator=().
operator=() [1/3]
FShapeWrapper & IStereoLayers::FShapeWrapper::operator= (const FShapeWrapper & In) inline
Definition at line 44 of file IStereoLayers.h.
References FShapeWrapper(), IStereoLayerShape::Clone(), IsValid(), operator=(), and Wrapped.
operator=() [2/3]
FShapeWrapper & IStereoLayers::FShapeWrapper::operator= (FShapeWrapper && In) inline
Definition at line 49 of file IStereoLayers.h.
References FShapeWrapper(), MoveTemp(), and Wrapped.
operator=() [3/3]
FShapeWrapper & IStereoLayers::FShapeWrapper::operator= (IStereoLayerShape * InWrapped) inline
Definition at line 38 of file IStereoLayers.h.
References FShapeWrapper(), and Wrapped.
Referenced by operator=().
Field Documentation
Wrapped
TUniquePtr<IStereoLayerShape> IStereoLayers::FShapeWrapper::Wrapped
Definition at line 24 of file IStereoLayers.h.
Referenced by FShapeWrapper(), FShapeWrapper(), FShapeWrapper(), IsValid(), operator=(), operator=(), and operator=().
The documentation for this struct was generated from the following file:
IStereoLayers.h