Unreal Engine 5.6 C++ API: FStreamingSourceShapeHelper Class Reference
FStreamingSourceShapeHelper Class Reference
Helper class used to iterate over streaming source shapes.
#include "WorldPartitionStreamingSource.h"
Static Public Member Functions
static FORCEINLINE void ForEachShape (float InGridLoadingRange, float InDefaultRadius, bool bInProjectIn2D, const FVector &InLocation, const FRotator &InRotation, const TArray< FStreamingSourceShape > &InShapes, TFunctionRef< void(const FSphericalSector &)> InOperation, float InExtraRadius=0.f, float InExtraAngle=0.f)
static FORCEINLINE bool IsSourceAffectingGrid (const TSet< FName > &InSourceTargetGrids, EStreamingSourceTargetBehavior InSourceTargetBehavior, FName InGridName)
Detailed Description
Helper class used to iterate over streaming source shapes.
Definition at line 163 of file WorldPartitionStreamingSource.h.
Member Function Documentation
ForEachShape()
FORCEINLINE void FStreamingSourceShapeHelper::ForEachShape (float InGridLoadingRange, float InDefaultRadius, bool bInProjectIn2D, const FVector & InLocation, const FRotator & InRotation, const TArray< FStreamingSourceShape > & InShapes, TFunctionRef< void(const FSphericalSector &)> InOperation, float InExtraRadius = 0.f, float InExtraAngle = 0.f) inline static
Definition at line 181 of file WorldPartitionStreamingSource.h.
References check, FORCEINLINE, UE::Math::TVector< double >::ForwardVector, FVector, TArray< InElementType, InAllocatorType >::IsEmpty(), UE::Math::TRotator< T >::IsNearlyZero(), FSphericalSector::IsValid(), FMath::Min, Transform, FSphericalSector::TransformBy(), UE::Math::TRotator< T >::Vector(), UE::Math::TRotator< T >::Yaw, and UE::Math::TVector< double >::ZeroVector.
Referenced by FWorldPartitionStreamingSource::ForEachShape(), and FWorldPartitionStreamingSource::ForEachShape().
IsSourceAffectingGrid()
FORCEINLINE bool FStreamingSourceShapeHelper::IsSourceAffectingGrid (const TSet< FName > & InSourceTargetGrids, EStreamingSourceTargetBehavior InSourceTargetBehavior, FName InGridName) inline static
Definition at line 166 of file WorldPartitionStreamingSource.h.
References checkNoEntry, TSet< InElementType, KeyFuncs, Allocator >::Contains(), FORCEINLINE, and TSet< InElementType, KeyFuncs, Allocator >::IsEmpty().
Referenced by FWorldPartitionStreamingSource::ForEachShape().
The documentation for this class was generated from the following file:
WorldPartitionStreamingSource.h