Unreal Engine 5.6 C++ API: DynamicRenderScaling::FBudget Class Reference
DynamicRenderScaling::FBudget Class Reference final
#include "DynamicRenderScaling.h"
Public Member Functions
RENDERCORE_API FBudget (const TCHAR *Name, FHeuristicSettings(*HeuristicSettingsGetter)(void))
RENDERCORE_API ~FBudget ()
const char * GetAnsiName () const
int32 GetBudgetId () const
const TCHAR * GetName () const
const FHeuristicSettings & GetSettings () const
bool operator== (const FBudget &Other) const
Static Public Member Functions
static RENDERCORE_API TLinkedList< FBudget * > *& GetGlobalList ()
static RENDERCORE_API int32 GetGlobalListSize ()
Private Member Functions
UE_NONCOPYABLE (FBudget)
Private Attributes
TArray< char > AnsiName
int32 BudgetId = 0
FHeuristicSettings CachedSettings
TLinkedList< FBudget * > GlobalListLink
FHeuristicSettings(* HeuristicSettingsGetter)(void)
const TCHAR * Name
Friends
template<typename Type>
class TMap
RENDERCORE_API void UpdateHeuristicsSettings ()
Updates all FBudget::GetSettings() with their new FHeuristicSettings.
Detailed Description
Definition at line 82 of file DynamicRenderScaling.h.
Constructor & Destructor Documentation
FBudget()
RENDERCORE_API DynamicRenderScaling::FBudget::FBudget (const TCHAR * Name, FHeuristicSettings(* HeuristicSettingsGetter)(void))
References HeuristicSettingsGetter, and Name.
Referenced by operator==(), and UE_NONCOPYABLE().
~FBudget()
RENDERCORE_API DynamicRenderScaling::FBudget::~FBudget ()
Member Function Documentation
GetAnsiName()
const char * DynamicRenderScaling::FBudget::GetAnsiName () const inline
Definition at line 97 of file DynamicRenderScaling.h.
References AnsiName.
GetBudgetId()
int32 DynamicRenderScaling::FBudget::GetBudgetId () const inline
Definition at line 108 of file DynamicRenderScaling.h.
References BudgetId.
GetGlobalList()
RENDERCORE_API TLinkedList< FBudget * > *& DynamicRenderScaling::FBudget::GetGlobalList () static
Referenced by FStatUnitData::FStatUnitData(), and DynamicRenderScaling::TMap< Type >::TMap().
GetGlobalListSize()
RENDERCORE_API int32 DynamicRenderScaling::FBudget::GetGlobalListSize () static
Referenced by DynamicRenderScaling::TMap< Type >::TMap(), DynamicRenderScaling::TMap< Type >::operator[](), DynamicRenderScaling::TMap< Type >::operator[](), DynamicRenderScaling::TMap< Type >::operator[](), DynamicRenderScaling::TMap< Type >::operator[](), and DynamicRenderScaling::TMap< Type >::SetAll().
GetName()
const TCHAR * DynamicRenderScaling::FBudget::GetName () const inline
Definition at line 92 of file DynamicRenderScaling.h.
References Name.
GetSettings()
const FHeuristicSettings & DynamicRenderScaling::FBudget::GetSettings () const inline
Definition at line 103 of file DynamicRenderScaling.h.
References CachedSettings.
operator==()
bool DynamicRenderScaling::FBudget::operator== (const FBudget & Other) const inline
Definition at line 113 of file DynamicRenderScaling.h.
References FBudget(), BudgetId, and Other.
UE_NONCOPYABLE()
DynamicRenderScaling::FBudget::UE_NONCOPYABLE (FBudget) private
References FBudget().
Friends And Related Symbol Documentation
TMap
template<typename Type> friend class TMap friend
Definition at line 164 of file DynamicRenderScaling.h.
References TMap.
Referenced by TMap.
UpdateHeuristicsSettings
RENDERCORE_API void UpdateHeuristicsSettings () friend
Updates all FBudget::GetSettings() with their new FHeuristicSettings.
Field Documentation
AnsiName
TArray<char> DynamicRenderScaling::FBudget::AnsiName private
Definition at line 147 of file DynamicRenderScaling.h.
Referenced by GetAnsiName().
BudgetId
int32 DynamicRenderScaling::FBudget::BudgetId = 0 private
Definition at line 151 of file DynamicRenderScaling.h.
Referenced by GetBudgetId(), operator==(), DynamicRenderScaling::TMap< Type >::operator[](), and DynamicRenderScaling::TMap< Type >::operator[]().
CachedSettings
FHeuristicSettings DynamicRenderScaling::FBudget::CachedSettings private
Definition at line 150 of file DynamicRenderScaling.h.
Referenced by GetSettings().
GlobalListLink
TLinkedList<FBudget*> DynamicRenderScaling::FBudget::GlobalListLink private
Definition at line 149 of file DynamicRenderScaling.h.
HeuristicSettingsGetter
FHeuristicSettings(* DynamicRenderScaling::FBudget::HeuristicSettingsGetter) (void) private
Definition at line 148 of file DynamicRenderScaling.h.
Referenced by FBudget().
Name
const TCHAR* DynamicRenderScaling::FBudget::Name private
Definition at line 146 of file DynamicRenderScaling.h.
Referenced by FBudget(), and GetName().
The documentation for this class was generated from the following file:
DynamicRenderScaling.h