Unreal Engine 5.6 C++ API: FXxHash64Builder Class Reference
FXxHash64Builder Class Reference
Calculates a 64-bit hash with XXH3.
#include "xxhash.h"
Public Member Functions
FXxHash64Builder ()
FXxHash64Builder (const FXxHash64Builder &)=delete
FXxHash64 Finalize () const
FXxHash64Builder & operator= (const FXxHash64Builder &)=delete
void Reset ()
void Update (const FCompositeBuffer &Buffer)
void Update (const void *Data, uint64 Size)
void Update (FMemoryView View)
Private Attributes
char StateBytes [576]
Detailed Description
Calculates a 64-bit hash with XXH3.
Definition at line 180 of file xxhash.h.
Constructor & Destructor Documentation
FXxHash64Builder() [1/2]
FXxHash64Builder::FXxHash64Builder () inline
Definition at line 183 of file xxhash.h.
References Reset().
Referenced by FXxHash64Builder(), and operator=().
FXxHash64Builder() [2/2]
FXxHash64Builder::FXxHash64Builder (const FXxHash64Builder &) delete
References FXxHash64Builder().
Member Function Documentation
Finalize()
FXxHash64 FXxHash64Builder::Finalize () const nodiscard
operator=()
FXxHash64Builder & FXxHash64Builder::operator= (const FXxHash64Builder &) delete
References FXxHash64Builder().
Reset()
void FXxHash64Builder::Reset ()
Referenced by FXxHash64Builder().
Update() [1/3]
void FXxHash64Builder::Update (const FCompositeBuffer & Buffer)
References Buffer.
Update() [2/3]
void FXxHash64Builder::Update (const void * Data, uint64 Size)
References TSequenceHistory< HistorySize >::Size.
Update() [3/3]
void FXxHash64Builder::Update (FMemoryView View)
Field Documentation
StateBytes
char FXxHash64Builder::StateBytes[576] private
Definition at line 197 of file xxhash.h.
The documentation for this class was generated from the following file:
xxhash.h