Unreal Engine 5.6 C++ API: UUVEditorTexelDensityTool Class Reference
UUVEditorTexelDensityTool Class Reference
UUVEditorRecomputeUVsTool Recomputes UVs based on existing segmentations of the mesh.
#include "UVEditorTexelDensityTool.h"
Public Member Functions
ETexelDensityToolAction ActiveAction () const
virtual bool CanAccept () const override
virtual bool HasAccept () const override
virtual bool HasCancel () const override
virtual void OnPropertyModified (UObject *PropertySet, FProperty *Property) override
virtual void OnTick (float DeltaTime) override
virtual void Render (IToolsContextRenderAPI *RenderAPI) override
void RequestAction (ETexelDensityToolAction ActionType)
virtual void SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn)
The tool will operate on the meshes given here.
virtual void Setup () override
virtual void Shutdown (EToolShutdownType ShutdownType) override
Private Member Functions
void ApplyClick ()
void ClearHover (bool bClearHoverInfo=true)
int32 Get2DHitTriangle (const FRay &WorldRayIn, int32 *IndexOf2DSpatialOut=nullptr)
int32 Get3DHitTriangle (const FRay &WorldRayIn, int32 *IndexOf2DSpatialOut=nullptr)
void OnMeshTriangleClicked (int32 Tid, int32 IndexOfMesh, bool bTidIsFromUnwrap)
void OnMeshTriangleHovered (int32 Tid, int32 IndexOfMesh, bool bTidIsFromUnwrap)
void OnSelectedGroupLayerChanged ()
void PerformBackgroundScalingTask ()
void RecordAnalytics ()
void UpdateActiveGroupLayer (bool bUpdateFactories=true)
void UpdateHover ()
void UpdateToolMessage ()
Private Attributes
TObjectPtr< UUVEditorTexelDensityActionSettings > ActionSettings = nullptr
TSharedPtr< UE::Geometry::FPolygroupSet, ESPMode::ThreadSafe > ActiveGroupSet
bool bClickWasInUnwrap = false
bool bHoverTidIsFromUnwrap = false
bool bLastHoverTidWasFromUnwrap = false
int32 ClickedMeshIndex = -1
int32 ClickedTid = IndexConstants::InvalidID
CURRENT_FILE_ID___LINE___GENERATED_BODY
TObjectPtr< UUVToolEmitChangeAPI > EmitChangeAPI = nullptr
TArray< TObjectPtr< UUVTexelDensityOperatorFactory > > Factories
int32 HoverMeshIndex = IndexConstants::InvalidID
int32 HoverTid = IndexConstants::InvalidID
UE::Geometry::UVEditorAnalytics::FTargetAnalytics InputTargetAnalytics
int32 LastHoverMeshIndex = IndexConstants::InvalidID
int32 LastHoverTid = IndexConstants::InvalidID
TObjectPtr< UUVToolLivePreviewAPI > LivePreviewAPI = nullptr
TObjectPtr< UInputBehaviorSet > LivePreviewBehaviorSet = nullptr
TObjectPtr< ULocalInputBehaviorSource > LivePreviewBehaviorSource = nullptr
FViewCameraState LivePreviewCameraState
TObjectPtr< UPreviewGeometry > LivePreviewGeometry = nullptr
TWeakObjectPtr< UInputRouter > LivePreviewInputRouter = nullptr
ETexelDensityToolAction PendingAction = ETexelDensityToolAction::NoAction
int32 RemainingTargetsToProcess
TObjectPtr< UUVEditorTexelDensitySettings > Settings = nullptr
TArray< TSharedPtr< UE::Geometry::FDynamicMeshAABBTree3 > > Spatials2D
TArray< TSharedPtr< UE::Geometry::FDynamicMeshAABBTree3 > > Spatials3D
TArray< TObjectPtr< UUVEditorToolMeshInput > > Targets
FDateTime ToolStartTimeAnalytics
TObjectPtr< UMaterialInstanceDynamic > TriangleSetMaterial = nullptr
TObjectPtr< UPreviewGeometry > UnwrapGeometry = nullptr
TObjectPtr< UUVTool2DViewportAPI > UVTool2DViewportAPI = nullptr
TObjectPtr< UUVToolSelectionAPI > UVToolSelectionAPI = nullptr
Detailed Description
UUVEditorRecomputeUVsTool Recomputes UVs based on existing segmentations of the mesh.
Definition at line 90 of file UVEditorTexelDensityTool.h.
Member Function Documentation
ActiveAction()
ETexelDensityToolAction UUVEditorTexelDensityTool::ActiveAction () const
ApplyClick()
void UUVEditorTexelDensityTool::ApplyClick () private
References ApplyClick().
Referenced by ApplyClick().
CanAccept()
virtual bool UUVEditorTexelDensityTool::CanAccept () const override virtual
ClearHover()
void UUVEditorTexelDensityTool::ClearHover (bool bClearHoverInfo = true) private
Parameters
bClearHoverInfo If true, also clears HoverVid, etc in addition to just clearing display.
References ClearHover().
Referenced by ClearHover().
Get2DHitTriangle()
int32 UUVEditorTexelDensityTool::Get2DHitTriangle (const FRay & WorldRayIn, int32 * IndexOf2DSpatialOut = nullptr) private
References Get2DHitTriangle().
Referenced by Get2DHitTriangle().
Get3DHitTriangle()
int32 UUVEditorTexelDensityTool::Get3DHitTriangle (const FRay & WorldRayIn, int32 * IndexOf2DSpatialOut = nullptr) private
References Get3DHitTriangle().
Referenced by Get3DHitTriangle().
HasAccept()
virtual bool UUVEditorTexelDensityTool::HasAccept () const inline override virtual
Definition at line 103 of file UVEditorTexelDensityTool.h.
HasCancel()
virtual bool UUVEditorTexelDensityTool::HasCancel () const inline override virtual
Definition at line 102 of file UVEditorTexelDensityTool.h.
References HasCancel().
Referenced by HasCancel().
OnMeshTriangleClicked()
void UUVEditorTexelDensityTool::OnMeshTriangleClicked (int32 Tid, int32 IndexOfMesh, bool bTidIsFromUnwrap) private
References OnMeshTriangleClicked().
Referenced by OnMeshTriangleClicked().
OnMeshTriangleHovered()
void UUVEditorTexelDensityTool::OnMeshTriangleHovered (int32 Tid, int32 IndexOfMesh, bool bTidIsFromUnwrap) private
References OnMeshTriangleHovered().
Referenced by OnMeshTriangleHovered().
OnPropertyModified()
virtual void UUVEditorTexelDensityTool::OnPropertyModified (UObject * PropertySet, FProperty * Property) override virtual
References Property.
OnSelectedGroupLayerChanged()
void UUVEditorTexelDensityTool::OnSelectedGroupLayerChanged () private
References OnSelectedGroupLayerChanged().
Referenced by OnSelectedGroupLayerChanged().
OnTick()
virtual void UUVEditorTexelDensityTool::OnTick (float DeltaTime) override virtual
References DeltaTime, and OnTick().
Referenced by OnTick().
PerformBackgroundScalingTask()
void UUVEditorTexelDensityTool::PerformBackgroundScalingTask () private
References PerformBackgroundScalingTask(), and UPROPERTY.
Referenced by PerformBackgroundScalingTask().
RecordAnalytics()
void UUVEditorTexelDensityTool::RecordAnalytics () private
References RecordAnalytics().
Referenced by RecordAnalytics().
Render()
virtual void UUVEditorTexelDensityTool::Render (IToolsContextRenderAPI * RenderAPI) override virtual
References Render().
Referenced by Render().
RequestAction()
void UUVEditorTexelDensityTool::RequestAction (ETexelDensityToolAction ActionType)
SetTargets()
virtual void UUVEditorTexelDensityTool::SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn) inline virtual
The tool will operate on the meshes given here.
Definition at line 112 of file UVEditorTexelDensityTool.h.
References Targets.
Setup()
virtual void UUVEditorTexelDensityTool::Setup () override virtual
References Setup().
Referenced by Setup().
Shutdown()
virtual void UUVEditorTexelDensityTool::Shutdown (EToolShutdownType ShutdownType) override virtual
References Shutdown().
Referenced by Shutdown().
UpdateActiveGroupLayer()
void UUVEditorTexelDensityTool::UpdateActiveGroupLayer (bool bUpdateFactories = true) private
References UpdateActiveGroupLayer().
Referenced by UpdateActiveGroupLayer().
UpdateHover()
void UUVEditorTexelDensityTool::UpdateHover () private
References UpdateHover().
Referenced by UpdateHover().
UpdateToolMessage()
void UUVEditorTexelDensityTool::UpdateToolMessage () private
References UpdateToolMessage().
Referenced by UpdateToolMessage().
Field Documentation
ActionSettings
TObjectPtr<UUVEditorTexelDensityActionSettings> UUVEditorTexelDensityTool::ActionSettings = nullptr private
Definition at line 129 of file UVEditorTexelDensityTool.h.
ActiveGroupSet
TSharedPtr<UE::Geometry::FPolygroupSet, ESPMode::ThreadSafe> UUVEditorTexelDensityTool::ActiveGroupSet private
Definition at line 174 of file UVEditorTexelDensityTool.h.
bClickWasInUnwrap
bool UUVEditorTexelDensityTool::bClickWasInUnwrap = false private
Definition at line 193 of file UVEditorTexelDensityTool.h.
bHoverTidIsFromUnwrap
bool UUVEditorTexelDensityTool::bHoverTidIsFromUnwrap = false private
Definition at line 198 of file UVEditorTexelDensityTool.h.
bLastHoverTidWasFromUnwrap
bool UUVEditorTexelDensityTool::bLastHoverTidWasFromUnwrap = false private
Definition at line 201 of file UVEditorTexelDensityTool.h.
ClickedMeshIndex
int32 UUVEditorTexelDensityTool::ClickedMeshIndex = -1 private
Definition at line 192 of file UVEditorTexelDensityTool.h.
ClickedTid
int32 UUVEditorTexelDensityTool::ClickedTid = IndexConstants::InvalidID private
Definition at line 191 of file UVEditorTexelDensityTool.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorTexelDensityTool::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 92 of file UVEditorTexelDensityTool.h.
EmitChangeAPI
TObjectPtr<UUVToolEmitChangeAPI> UUVEditorTexelDensityTool::EmitChangeAPI = nullptr private
Definition at line 144 of file UVEditorTexelDensityTool.h.
Factories
TArray<TObjectPtr<UUVTexelDensityOperatorFactory> > UUVEditorTexelDensityTool::Factories private
Definition at line 147 of file UVEditorTexelDensityTool.h.
HoverMeshIndex
int32 UUVEditorTexelDensityTool::HoverMeshIndex = IndexConstants::InvalidID private
Definition at line 197 of file UVEditorTexelDensityTool.h.
HoverTid
int32 UUVEditorTexelDensityTool::HoverTid = IndexConstants::InvalidID private
Definition at line 196 of file UVEditorTexelDensityTool.h.
InputTargetAnalytics
UE::Geometry::UVEditorAnalytics::FTargetAnalytics UUVEditorTexelDensityTool::InputTargetAnalytics private
Definition at line 207 of file UVEditorTexelDensityTool.h.
LastHoverMeshIndex
int32 UUVEditorTexelDensityTool::LastHoverMeshIndex = IndexConstants::InvalidID private
Definition at line 200 of file UVEditorTexelDensityTool.h.
LastHoverTid
int32 UUVEditorTexelDensityTool::LastHoverTid = IndexConstants::InvalidID private
Definition at line 199 of file UVEditorTexelDensityTool.h.
LivePreviewAPI
TObjectPtr<UUVToolLivePreviewAPI> UUVEditorTexelDensityTool::LivePreviewAPI = nullptr private
Definition at line 137 of file UVEditorTexelDensityTool.h.
LivePreviewBehaviorSet
TObjectPtr<UInputBehaviorSet> UUVEditorTexelDensityTool::LivePreviewBehaviorSet = nullptr private
Definition at line 153 of file UVEditorTexelDensityTool.h.
LivePreviewBehaviorSource
TObjectPtr<ULocalInputBehaviorSource> UUVEditorTexelDensityTool::LivePreviewBehaviorSource = nullptr private
Definition at line 156 of file UVEditorTexelDensityTool.h.
LivePreviewCameraState
FViewCameraState UUVEditorTexelDensityTool::LivePreviewCameraState private
Definition at line 169 of file UVEditorTexelDensityTool.h.
LivePreviewGeometry
TObjectPtr<UPreviewGeometry> UUVEditorTexelDensityTool::LivePreviewGeometry = nullptr private
Definition at line 162 of file UVEditorTexelDensityTool.h.
LivePreviewInputRouter
TWeakObjectPtr<UInputRouter> UUVEditorTexelDensityTool::LivePreviewInputRouter = nullptr private
Definition at line 164 of file UVEditorTexelDensityTool.h.
PendingAction
ETexelDensityToolAction UUVEditorTexelDensityTool::PendingAction = ETexelDensityToolAction::NoAction private
Definition at line 131 of file UVEditorTexelDensityTool.h.
RemainingTargetsToProcess
int32 UUVEditorTexelDensityTool::RemainingTargetsToProcess private
Definition at line 149 of file UVEditorTexelDensityTool.h.
Settings
TObjectPtr<UUVEditorTexelDensitySettings> UUVEditorTexelDensityTool::Settings = nullptr private
Definition at line 126 of file UVEditorTexelDensityTool.h.
Spatials2D
TArray<TSharedPtr<UE::Geometry::FDynamicMeshAABBTree3> > UUVEditorTexelDensityTool::Spatials2D private
Definition at line 166 of file UVEditorTexelDensityTool.h.
Spatials3D
TArray<TSharedPtr<UE::Geometry::FDynamicMeshAABBTree3> > UUVEditorTexelDensityTool::Spatials3D private
Definition at line 167 of file UVEditorTexelDensityTool.h.
Targets
TArray<TObjectPtr<UUVEditorToolMeshInput> > UUVEditorTexelDensityTool::Targets private
Definition at line 123 of file UVEditorTexelDensityTool.h.
Referenced by SetTargets().
ToolStartTimeAnalytics
FDateTime UUVEditorTexelDensityTool::ToolStartTimeAnalytics private
Definition at line 208 of file UVEditorTexelDensityTool.h.
TriangleSetMaterial
TObjectPtr<UMaterialInstanceDynamic> UUVEditorTexelDensityTool::TriangleSetMaterial = nullptr private
Definition at line 172 of file UVEditorTexelDensityTool.h.
UnwrapGeometry
TObjectPtr<UPreviewGeometry> UUVEditorTexelDensityTool::UnwrapGeometry = nullptr private
Definition at line 159 of file UVEditorTexelDensityTool.h.
UVTool2DViewportAPI
TObjectPtr< UUVTool2DViewportAPI> UUVEditorTexelDensityTool::UVTool2DViewportAPI = nullptr private
Definition at line 141 of file UVEditorTexelDensityTool.h.
UVToolSelectionAPI
TObjectPtr<UUVToolSelectionAPI> UUVEditorTexelDensityTool::UVToolSelectionAPI = nullptr private
Definition at line 134 of file UVEditorTexelDensityTool.h.
The documentation for this class was generated from the following file:
UVEditorTexelDensityTool.h