Unreal Engine 5.6 C++ API: FHistogram Struct Reference
FHistogram Struct Reference
Fairly generic histogram for values that have natural lower bound and possibly no upper bound, e.g., frame time.
#include "Histogram.h"
Data Structures
struct FBin
Bin.
Public Member Functions
void AddMeasurement (double Value)
Adds an observed measurement.
void AddMeasurement (double ValueForBinning, double MeasurementValue)
Adds an observed measurement (with a different thresholding key than the measurement, e.g., when accumulating time spent in a chart keyed on framerate).
FString DumpToJsonString () const
Same as DumpToJsonString but uses a DefaultConvertBinToLabel.
FString DumpToJsonString (TFunctionRef< FString(double, double)> ConvertBinToLabel) const
Returns a string in a Json format: [{"Bin":"BinName","Count":Count,"Sum":Sum},...].
FString DumpToJsonString2 () const
Same as DumpToJsonString2 but uses a DefaultConvertBinToLabel.
FString DumpToJsonString2 (TFunctionRef< FString(double, double)> ConvertBinToLabel) const
Returns a string in a Json format: [{"BinName":{"Count":Count,"Sum":Sum}},...].
void DumpToLog (const FString &HistogramName)
Prints histogram contents to the log.
double GetAverageOfAllMeasures () const
Returns the average of all measurements (essentially a shortcut for Sum/Count).
double GetBinLowerBound (int IdxBin) const
Gets lower bound of the bin, i.e.
int32 GetBinObservationsCount (int IdxBin) const
Gets number of observations in the bin.
double GetBinObservationsSum (int IdxBin) const
Gets sum of observations in the bin.
double GetBinUpperBound (int IdxBin) const
Gets upper bound of the bin, i.e.
double GetMaxOfAllMeasures () const
Returns the maximum of all measurements.
double GetMinOfAllMeasures () const
Returns the minimum of all measurements.
int32 GetNumBins () const
Gets number of bins.
int64 GetNumMeasurements () const
Returns the sum of all counts (the number of recorded measurements)
double GetSumOfAllMeasures () const
Returns the sum of all measurements.
FORCEINLINE void InitFromArray (std::initializer_list< double > Thresholds)
Inits histogram with the specified bin boundaries, with the final bucket extending to infinity (e.g., passing in 0,5 creates a [0..5) bucket and a [5..infinity) bucket)
void InitFromArray (TArrayView< const double > Thresholds)
Inits histogram with the specified bin boundaries, with the final bucket extending to infinity (e.g., passing in 0,5 creates a [0..5) bucket and a [5..infinity) bucket)
void InitHitchTracking ()
Inits histogram to mimic our existing hitch buckets.
void InitLinear (double MinTime, double MaxTime, double BinSize)
Inits histogram with linear, equally sized bins.
FORCEINLINE FHistogram operator+ (const FHistogram &Other) const
FORCEINLINE FHistogram & operator+= (const FHistogram &Other)
FORCEINLINE FHistogram operator- (const FHistogram &Other) const
void Reset ()
Resets measurements, without resetting the configured bins.
Static Public Member Functions
static FString DefaultConvertBinToLabel (double MinValue, double UpperBound)
Default stringifier for bins for use with DumpToJsonString.
Protected Attributes
TArray< FBin > Bins
Bins themselves, should be continous in terms of [MinValue; UpperBound) and sorted ascending by MinValue.
int64 CountOfAllMeasures
friend FHistogramBuilder
This is exposed as a clean way to build bins while enforcing the condition mentioned above.
double MaximalMeasurement
double MinimalMeasurement
double SumOfAllMeasures
Quick stats for all bins.
Detailed Description
Fairly generic histogram for values that have natural lower bound and possibly no upper bound, e.g., frame time.
Definition at line 33 of file Histogram.h.
Member Function Documentation
AddMeasurement() [1/2]
void FHistogram::AddMeasurement (double Value) inline
Adds an observed measurement.
Definition at line 54 of file Histogram.h.
References AddMeasurement(), and Value.
Referenced by AddMeasurement().
AddMeasurement() [2/2]
void FHistogram::AddMeasurement (double ValueForBinning, double MeasurementValue)
Adds an observed measurement (with a different thresholding key than the measurement, e.g., when accumulating time spent in a chart keyed on framerate).
DefaultConvertBinToLabel()
FString FHistogram::DefaultConvertBinToLabel (double MinValue, double UpperBound) static
Default stringifier for bins for use with DumpToJsonString.
Truncates to int and uses Plus as the suffix for the last bin. ie. [0.0, 3.75, 9.8] -> 0_3, 3_9, 9_Plus
DumpToJsonString() [1/2]
FString FHistogram::DumpToJsonString () const
Same as DumpToJsonString but uses a DefaultConvertBinToLabel.
DumpToJsonString() [2/2]
FString FHistogram::DumpToJsonString (TFunctionRef< FString(double, double)> ConvertBinToLabel) const
Returns a string in a Json format: [{"Bin":"BinName","Count":Count,"Sum":Sum},...].
Bucket name is constructed by calling ConvertBinToLabel on the MinValue and UpperBound for each bin. Convert function is used to allow the bin range, which is stored as a double, to be printed prettily.
DumpToJsonString2() [1/2]
FString FHistogram::DumpToJsonString2 () const
Same as DumpToJsonString2 but uses a DefaultConvertBinToLabel.
DumpToJsonString2() [2/2]
FString FHistogram::DumpToJsonString2 (TFunctionRef< FString(double, double)> ConvertBinToLabel) const
Returns a string in a Json format: [{"BinName":{"Count":Count,"Sum":Sum}},...].
Bucket name is constructed by calling ConvertBinToLabel on the MinValue and UpperBound for each bin. Convert function is used to allow the bin range, which is stored as a double, to be printed prettily.
DumpToLog()
void FHistogram::DumpToLog (const FString & HistogramName)
Prints histogram contents to the log.
GetAverageOfAllMeasures()
double FHistogram::GetAverageOfAllMeasures () const inline
Returns the average of all measurements (essentially a shortcut for Sum/Count).
Definition at line 131 of file Histogram.h.
References CountOfAllMeasures, and SumOfAllMeasures.
GetBinLowerBound()
double FHistogram::GetBinLowerBound (int IdxBin) const inline
Gets lower bound of the bin, i.e.
minimum value that goes into it.
Definition at line 95 of file Histogram.h.
References Bins.
GetBinObservationsCount()
int32 FHistogram::GetBinObservationsCount (int IdxBin) const inline
Gets number of observations in the bin.
Definition at line 107 of file Histogram.h.
References Bins.
GetBinObservationsSum()
double FHistogram::GetBinObservationsSum (int IdxBin) const inline
Gets sum of observations in the bin.
Definition at line 113 of file Histogram.h.
References Bins.
GetBinUpperBound()
double FHistogram::GetBinUpperBound (int IdxBin) const inline
Gets upper bound of the bin, i.e.
first value that does not go into it.
Definition at line 101 of file Histogram.h.
References Bins.
GetMaxOfAllMeasures()
double FHistogram::GetMaxOfAllMeasures () const inline
Returns the maximum of all measurements.
Definition at line 143 of file Histogram.h.
References MaximalMeasurement.
GetMinOfAllMeasures()
double FHistogram::GetMinOfAllMeasures () const inline
Returns the minimum of all measurements.
Definition at line 137 of file Histogram.h.
References MinimalMeasurement.
GetNumBins()
int32 FHistogram::GetNumBins () const inline
Gets number of bins.
Definition at line 89 of file Histogram.h.
References Bins.
Referenced by operator+(), operator+=(), and operator-().
GetNumMeasurements()
int64 FHistogram::GetNumMeasurements () const inline
Returns the sum of all counts (the number of recorded measurements)
Definition at line 119 of file Histogram.h.
References CountOfAllMeasures.
GetSumOfAllMeasures()
double FHistogram::GetSumOfAllMeasures () const inline
Returns the sum of all measurements.
Definition at line 125 of file Histogram.h.
References SumOfAllMeasures.
InitFromArray() [1/2]
FORCEINLINE void FHistogram::InitFromArray (std::initializer_list< double > Thresholds) inline
Inits histogram with the specified bin boundaries, with the final bucket extending to infinity (e.g., passing in 0,5 creates a [0..5) bucket and a [5..infinity) bucket)
Definition at line 45 of file Histogram.h.
References FORCEINLINE, InitFromArray(), and MakeArrayView().
InitFromArray() [2/2]
void FHistogram::InitFromArray (TArrayView< const double > Thresholds)
Inits histogram with the specified bin boundaries, with the final bucket extending to infinity (e.g., passing in 0,5 creates a [0..5) bucket and a [5..infinity) bucket)
Referenced by InitFromArray().
InitHitchTracking()
void FHistogram::InitHitchTracking ()
Inits histogram to mimic our existing hitch buckets.
InitLinear()
void FHistogram::InitLinear (double MinTime, double MaxTime, double BinSize)
Inits histogram with linear, equally sized bins.
operator+()
FORCEINLINE FHistogram FHistogram::operator+ (const FHistogram & Other) const inline
Definition at line 161 of file Histogram.h.
References Bins, check, FORCEINLINE, GetNumBins(), and Other.
operator+=()
FORCEINLINE FHistogram & FHistogram::operator+= (const FHistogram & Other) inline
Definition at line 174 of file Histogram.h.
References Bins, check, CountOfAllMeasures, FORCEINLINE, GetNumBins(), FMath::Max, MaximalMeasurement, FMath::Min, MinimalMeasurement, Other, and SumOfAllMeasures.
operator-()
FORCEINLINE FHistogram FHistogram::operator- (const FHistogram & Other) const inline
Definition at line 148 of file Histogram.h.
References Bins, check, FORCEINLINE, GetNumBins(), and Other.
Reset()
void FHistogram::Reset ()
Resets measurements, without resetting the configured bins.
Field Documentation
Bins
TArray<FBin> FHistogram::Bins protected
Bins themselves, should be continous in terms of [MinValue; UpperBound) and sorted ascending by MinValue.
Last bin's UpperBound doesn't matter
Definition at line 257 of file Histogram.h.
Referenced by GetBinLowerBound(), GetBinObservationsCount(), GetBinObservationsSum(), GetBinUpperBound(), GetNumBins(), operator+(), operator+=(), and operator-().
CountOfAllMeasures
int64 FHistogram::CountOfAllMeasures protected
Definition at line 261 of file Histogram.h.
Referenced by GetAverageOfAllMeasures(), GetNumMeasurements(), and operator+=().
FHistogramBuilder
friend FHistogram::FHistogramBuilder protected
This is exposed as a clean way to build bins while enforcing the condition mentioned above.
Definition at line 266 of file Histogram.h.
MaximalMeasurement
double FHistogram::MaximalMeasurement protected
Definition at line 263 of file Histogram.h.
Referenced by GetMaxOfAllMeasures(), and operator+=().
MinimalMeasurement
double FHistogram::MinimalMeasurement protected
Definition at line 262 of file Histogram.h.
Referenced by GetMinOfAllMeasures(), and operator+=().
SumOfAllMeasures
double FHistogram::SumOfAllMeasures protected
Quick stats for all bins.
Definition at line 260 of file Histogram.h.
Referenced by GetAverageOfAllMeasures(), GetSumOfAllMeasures(), and operator+=().
The documentation for this struct was generated from the following file:
Histogram.h