Unreal Engine 5.6 C++ API: FObjectSavePackageSerializeContext Class Reference
FObjectSavePackageSerializeContext Class Reference
Interface used by FArchiveSavePackageData during Serialize(FArchive& Ar) to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectSavePackageSerializeContext (const FObjectSavePackageSerializeContext &Other)
FObjectSavePackageSerializeContext (FObjectSaveContextData &InData)
UE_DEPRECATED(5.6, "Use AddCookLoadDependency.") 1 void AddCookBuildDependency(UE void AddCookLoadDependency (UE::Cook::FCookDependency BuildDependency)
Add the given FCookDependency to the build dependencies for the package being cook-saved.
void AddCookRuntimeDependency (FSoftObjectPath Dependency)
Add the given UObject's package as a runtime dependency for the package being cook-saved.
void AddCookSaveDependency (UE::Cook::FCookDependency BuildDependency)
Add the given FCookDependency to the build dependencies for the package being cook-saved.
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
EObjectSaveContextPhase GetPhase () const
Return which phase of SavePackage callbacks are active.
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const TCHAR * GetTargetFilename () const
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
void HarvestCookRuntimeDependencies (UObject *HarvestReferencesFrom)
Serialize an object to find all packages that it references, and AddCookRuntimeDependency for each one.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsDeterminismDebug () const
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
bool IsFirstConcurrentSave () const
Always true normally.
bool IsHarvestingCookDependencies () const
Return true if the archive is listening to AddCookBuildDependency and AddCookRuntimeDependency calls.
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
bool IsUpdatingLoadedPath () const
Return whether LoadedPath of the package being saved is being updated.
void RegisterDeterminismHelper (const TRefCountPtr< UE::Cook::IDeterminismHelper > &DeterminismHelper)
Ignored unless IsDeterminismDebug()=true.
void RequestPostSaveSerialization ()
Called during the Harvest phase when the current object need to call Serialize again during the PostSave phase.
Protected Attributes
FObjectSaveContextData & Data
Detailed Description
Interface used by FArchiveSavePackageData during Serialize(FArchive& Ar) to access the save parameters.
Definition at line 337 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectSavePackageSerializeContext() [1/2]
FObjectSavePackageSerializeContext::FObjectSavePackageSerializeContext (FObjectSaveContextData & InData) inline explicit
Definition at line 340 of file ObjectSaveContext.h.
References Data.
Referenced by FObjectSavePackageSerializeContext().
FObjectSavePackageSerializeContext() [2/2]
FObjectSavePackageSerializeContext::FObjectSavePackageSerializeContext (const FObjectSavePackageSerializeContext & Other) inline
Definition at line 345 of file ObjectSaveContext.h.
References FObjectSavePackageSerializeContext(), Data, and Other.
Member Function Documentation
AddCookLoadDependency()
UE_DEPRECATED(5.6, "Use AddCookLoadDependency.") 1 void AddCookBuildDependency(UE void FObjectSavePackageSerializeContext::AddCookLoadDependency (UE::Cook::FCookDependency BuildDependency)
Add the given FCookDependency to the build dependencies for the package being cook-saved.
Incremental cooks will invalidate the package and recook it if the CookDependency changes. Other packages that incorporate the loaded data of the package into their own cooked results will also be recooked if this build dependency changes. Calling this function during editor save (rather than cook save) has another meaning. It is ignored for FCookDependency of type other than FCookDependency::Package, but for FCookDependency::Package it identifies a reference that propagates chunk management in the AssetRegistry, but does not cause its target to be cooked.
References AddCookLoadDependency().
Referenced by AddCookLoadDependency().
AddCookRuntimeDependency()
void FObjectSavePackageSerializeContext::AddCookRuntimeDependency (FSoftObjectPath Dependency)
Add the given UObject's package as a runtime dependency for the package being cook-saved.
It will be cooked for the current platform even if it is not otherwise referenced, and even if the object being PreSaved does not end up saving into the package's exports for the current platform.
References AddCookRuntimeDependency().
Referenced by AddCookRuntimeDependency().
AddCookSaveDependency()
void FObjectSavePackageSerializeContext::AddCookSaveDependency (UE::Cook::FCookDependency BuildDependency)
Add the given FCookDependency to the build dependencies for the package being cook-saved.
Incremental cooks will invalidate the package and recook it if the CookDependency changes.
References AddCookSaveDependency().
Referenced by AddCookSaveDependency().
GetCookingDLC()
UE::Cook::ECookingDLC FObjectSavePackageSerializeContext::GetCookingDLC () const inline
Definition at line 367 of file ObjectSaveContext.h.
References Data.
GetCookType()
UE::Cook::ECookType FObjectSavePackageSerializeContext::GetCookType () const inline
Definition at line 366 of file ObjectSaveContext.h.
References Data.
Referenced by IsCookByTheBook(), IsCookOnTheFly(), and IsCookTypeUnknown().
GetPhase()
EObjectSaveContextPhase FObjectSavePackageSerializeContext::GetPhase () const inline
Return which phase of SavePackage callbacks are active.
See also
EObjectSaveContextPhase.
Definition at line 370 of file ObjectSaveContext.h.
References Data.
GetSaveFlags()
uint32 FObjectSavePackageSerializeContext::GetSaveFlags () const inline
Return the save flags (ESaveFlags) of the save.
Definition at line 435 of file ObjectSaveContext.h.
References Data.
GetTargetFilename()
const TCHAR * FObjectSavePackageSerializeContext::GetTargetFilename () const inline
The target Filename being saved into (not the temporary file for saving).
The path is in the standard UnrealEngine form - it is as a relative path from the process binary directory. Empty string if the saved bytes are not being saved to a file. Never null.
Definition at line 355 of file ObjectSaveContext.h.
References Data.
GetTargetPlatform()
const ITargetPlatform * FObjectSavePackageSerializeContext::GetTargetPlatform () const inline
Return the targetplatform of the save, if cooking.
Null if not cooking.
Definition at line 361 of file ObjectSaveContext.h.
References Data.
HarvestCookRuntimeDependencies()
void FObjectSavePackageSerializeContext::HarvestCookRuntimeDependencies (UObject * HarvestReferencesFrom)
Serialize an object to find all packages that it references, and AddCookRuntimeDependency for each one.
References HarvestCookRuntimeDependencies().
Referenced by HarvestCookRuntimeDependencies().
IsCookByTheBook()
bool FObjectSavePackageSerializeContext::IsCookByTheBook () const inline
Definition at line 363 of file ObjectSaveContext.h.
References UE::Cook::ByTheBook, and GetCookType().
IsCooking()
bool FObjectSavePackageSerializeContext::IsCooking () const inline
Report whether this is a save into a target-specific cooked format.
Definition at line 358 of file ObjectSaveContext.h.
References Data.
IsCookOnTheFly()
bool FObjectSavePackageSerializeContext::IsCookOnTheFly () const inline
Definition at line 364 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::OnTheFly.
IsCookTypeUnknown()
bool FObjectSavePackageSerializeContext::IsCookTypeUnknown () const inline
Definition at line 365 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::Unknown.
IsDeterminismDebug()
bool FObjectSavePackageSerializeContext::IsDeterminismDebug () const
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
References IsDeterminismDebug().
Referenced by IsDeterminismDebug().
IsFirstConcurrentSave()
bool FObjectSavePackageSerializeContext::IsFirstConcurrentSave () const inline
Always true normally.
When a system is executing multiple PreSaves concurrently before a single save, will return false for all but the first PreSave.
Definition at line 441 of file ObjectSaveContext.h.
References Data.
IsHarvestingCookDependencies()
bool FObjectSavePackageSerializeContext::IsHarvestingCookDependencies () const
Return true if the archive is listening to AddCookBuildDependency and AddCookRuntimeDependency calls.
If it returns true, objects must add their dependencies, failing to do so will cause false positive incremental skips.
IsProceduralSave()
bool FObjectSavePackageSerializeContext::IsProceduralSave () const inline
Return whether the package is being saved due to a procedural save.
Any save without the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 426 of file ObjectSaveContext.h.
References Data.
IsUpdatingLoadedPath()
bool FObjectSavePackageSerializeContext::IsUpdatingLoadedPath () const inline
Return whether LoadedPath of the package being saved is being updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file.
Definition at line 432 of file ObjectSaveContext.h.
References Data.
RegisterDeterminismHelper()
void FObjectSavePackageSerializeContext::RegisterDeterminismHelper (const TRefCountPtr< UE::Cook::IDeterminismHelper > & DeterminismHelper)
Ignored unless IsDeterminismDebug()=true.
An object should call this function to register their callback class for adding determinism diagnostics the package save.
References RegisterDeterminismHelper().
Referenced by RegisterDeterminismHelper().
RequestPostSaveSerialization()
void FObjectSavePackageSerializeContext::RequestPostSaveSerialization ()
Called during the Harvest phase when the current object need to call Serialize again during the PostSave phase.
References RequestPostSaveSerialization().
Referenced by RequestPostSaveSerialization().
Field Documentation
Data
FObjectSaveContextData& FObjectSavePackageSerializeContext::Data protected
Definition at line 444 of file ObjectSaveContext.h.
Referenced by FObjectSavePackageSerializeContext(), FObjectSavePackageSerializeContext(), GetCookingDLC(), GetCookType(), GetPhase(), GetSaveFlags(), GetTargetFilename(), GetTargetPlatform(), IsCooking(), IsFirstConcurrentSave(), IsProceduralSave(), and IsUpdatingLoadedPath().
The documentation for this class was generated from the following file:
ObjectSaveContext.h