Unreal Engine 5.6 C++ API: FDisplayClusterRender_ProceduralMeshComponentRef Class Reference
FDisplayClusterRender_ProceduralMeshComponentRef Class Reference
#include "DisplayClusterRender_ProceduralMeshComponentRef.h"
Public Member Functions
FDisplayClusterRender_ProceduralMeshComponentRef ()
FDisplayClusterRender_ProceduralMeshComponentRef (const FDisplayClusterRender_ProceduralMeshComponentRef &In)
UProceduralMeshComponent * GetOrFindProceduralMeshComponent () const
bool IsProceduralMeshGeometryDirty () const
void MarkProceduralMeshGeometryDirty () const
void ResetProceduralMeshComponentRef ()
void ResetProceduralMeshGeometryDirty () const
bool SetProceduralMeshComponentRef (UProceduralMeshComponent *InProceduralMeshComponent)
Public Member Functions inherited from FDisplayClusterSceneComponentRef
FDisplayClusterSceneComponentRef ()
FDisplayClusterSceneComponentRef (const FDisplayClusterSceneComponentRef &InComponentRef)
FDisplayClusterSceneComponentRef (USceneComponent *InComponent)
USceneComponent * GetOrFindSceneComponent () const
bool IsDefinedSceneComponent () const
bool IsEqualsComponentName (const FName &InComponentName) const
bool IsSceneComponentValid () const
void ResetSceneComponent ()
bool SetSceneComponent (USceneComponent *const InComponent)
Public Member Functions inherited from FDisplayClusterActorRef
FDisplayClusterActorRef ()
FDisplayClusterActorRef (const FDisplayClusterActorRef &InActorRef)
virtual ~FDisplayClusterActorRef ()
AActor * GetOrFindSceneActor () const
const TWeakObjectPtr< AActor > GetSceneActorWeakPtr () const
Returns the current weak ptr of the scene actor object.
bool IsDefinedSceneActor () const
void ResetSceneActor ()
bool SetSceneActor (const AActor *InActor)
Private Attributes
bool bIsProceduralMeshGeometryDirty = false
Additional Inherited Members
Protected Attributes inherited from FDisplayClusterActorRef
FCriticalSection DataGuard
Detailed Description
Definition at line 11 of file DisplayClusterRender_ProceduralMeshComponentRef.h.
Constructor & Destructor Documentation
FDisplayClusterRender_ProceduralMeshComponentRef() [1/2]
FDisplayClusterRender_ProceduralMeshComponentRef::FDisplayClusterRender_ProceduralMeshComponentRef () inline
Definition at line 15 of file DisplayClusterRender_ProceduralMeshComponentRef.h.
References FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef().
Referenced by FDisplayClusterRender_ProceduralMeshComponentRef().
FDisplayClusterRender_ProceduralMeshComponentRef() [2/2]
FDisplayClusterRender_ProceduralMeshComponentRef::FDisplayClusterRender_ProceduralMeshComponentRef (const FDisplayClusterRender_ProceduralMeshComponentRef & In) inline
Definition at line 19 of file DisplayClusterRender_ProceduralMeshComponentRef.h.
References FDisplayClusterRender_ProceduralMeshComponentRef(), FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef(), and bIsProceduralMeshGeometryDirty.
Member Function Documentation
GetOrFindProceduralMeshComponent()
UProceduralMeshComponent * FDisplayClusterRender_ProceduralMeshComponentRef::GetOrFindProceduralMeshComponent () const
IsProceduralMeshGeometryDirty()
bool FDisplayClusterRender_ProceduralMeshComponentRef::IsProceduralMeshGeometryDirty () const
MarkProceduralMeshGeometryDirty()
void FDisplayClusterRender_ProceduralMeshComponentRef::MarkProceduralMeshGeometryDirty () const
ResetProceduralMeshComponentRef()
void FDisplayClusterRender_ProceduralMeshComponentRef::ResetProceduralMeshComponentRef ()
ResetProceduralMeshGeometryDirty()
void FDisplayClusterRender_ProceduralMeshComponentRef::ResetProceduralMeshGeometryDirty () const
SetProceduralMeshComponentRef()
bool FDisplayClusterRender_ProceduralMeshComponentRef::SetProceduralMeshComponentRef (UProceduralMeshComponent * InProceduralMeshComponent)
Field Documentation
bIsProceduralMeshGeometryDirty
bool FDisplayClusterRender_ProceduralMeshComponentRef::bIsProceduralMeshGeometryDirty = false mutable private
Definition at line 35 of file DisplayClusterRender_ProceduralMeshComponentRef.h.
Referenced by FDisplayClusterRender_ProceduralMeshComponentRef().
The documentation for this class was generated from the following file:
DisplayClusterRender_ProceduralMeshComponentRef.h