Unreal Engine 5.6 C++ API: Components.h File Reference
Components.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Containers/StridedView.h"
#include "MeshUVChannelInfo.h"
#include "VertexStreamComponent.h"
Data Structures
struct FConstMeshBuildVertexView
The information used to build a mesh.
struct FMeshBuildVertexData
struct FMeshBuildVertexView
struct FStaticMeshBuildVertex
The information used to build a static-mesh vertex.
struct FStaticMeshDataType
Enumerations
enum { MAX_STATIC_TEXCOORDS = 8 }
Functions
FConstMeshBuildVertexView MakeConstMeshBuildVertexView (const FMeshBuildVertexData &InVertexData)
FConstMeshBuildVertexView MakeConstMeshBuildVertexView (const TConstArrayView< FStaticMeshBuildVertex > &InVertices)
FMeshBuildVertexView MakeMeshBuildVertexView (FMeshBuildVertexData &InVertexData)
Make a strided mesh build vertex view from FMeshBuildVertexData.
FMeshBuildVertexView MakeMeshBuildVertexView (TArray< FStaticMeshBuildVertex > &InVertices)
Make a strided mesh build vertex view from FStaticMeshBuildVertex.
FStaticMeshBuildVertex MakeStaticMeshVertex (const FMeshBuildVertexData &InVertexData, int32 Index)
FStaticMeshBuildVertex MakeStaticMeshVertex (const FMeshBuildVertexView &View, int32 Index)
void RemoveInvalidVertexColor (FConstMeshBuildVertexView &VertexView)
void RemoveInvalidVertexColor (FMeshBuildVertexView &VertexView)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_STATIC_TEXCOORDS
Definition at line 22 of file Components.h.
Function Documentation
MakeConstMeshBuildVertexView() [1/2]
FConstMeshBuildVertexView MakeConstMeshBuildVertexView (const FMeshBuildVertexData & InVertexData) inline
Definition at line 280 of file Components.h.
References TArray< InElementType, InAllocatorType >::Add(), FConstMeshBuildVertexView::BoneIndices, FMeshBuildVertexData::BoneIndices, FConstMeshBuildVertexView::BoneWeights, FMeshBuildVertexData::BoneWeights, FConstMeshBuildVertexView::Color, FMeshBuildVertexData::Color, MakeStridedView(), TArray< InElementType, InAllocatorType >::Num(), FConstMeshBuildVertexView::Position, FMeshBuildVertexData::Position, RemoveInvalidVertexColor(), TArray< InElementType, InAllocatorType >::Reserve(), FConstMeshBuildVertexView::TangentX, FMeshBuildVertexData::TangentX, FConstMeshBuildVertexView::TangentY, FMeshBuildVertexData::TangentY, FConstMeshBuildVertexView::TangentZ, FMeshBuildVertexData::TangentZ, FConstMeshBuildVertexView::UVs, and FMeshBuildVertexData::UVs.
MakeConstMeshBuildVertexView() [2/2]
FConstMeshBuildVertexView MakeConstMeshBuildVertexView (const TConstArrayView< FStaticMeshBuildVertex > & InVertices) inline
Definition at line 205 of file Components.h.
References FConstMeshBuildVertexView::Color, FStaticMeshBuildVertex::Color, MakeConstStridedView(), MAX_STATIC_TEXCOORDS, FConstMeshBuildVertexView::Position, FStaticMeshBuildVertex::Position, RemoveInvalidVertexColor(), FConstMeshBuildVertexView::TangentX, FStaticMeshBuildVertex::TangentX, FConstMeshBuildVertexView::TangentY, FStaticMeshBuildVertex::TangentY, FConstMeshBuildVertexView::TangentZ, FStaticMeshBuildVertex::TangentZ, and FConstMeshBuildVertexView::UVs.
Referenced by FStaticMeshVertexBuffer::Init().
MakeMeshBuildVertexView() [1/2]
FMeshBuildVertexView MakeMeshBuildVertexView (FMeshBuildVertexData & InVertexData) inline
Make a strided mesh build vertex view from FMeshBuildVertexData.
Definition at line 226 of file Components.h.
References TArray< InElementType, InAllocatorType >::Add(), FMeshBuildVertexData::BoneIndices, FMeshBuildVertexView::BoneIndices, FMeshBuildVertexData::BoneWeights, FMeshBuildVertexView::BoneWeights, FMeshBuildVertexData::Color, FMeshBuildVertexView::Color, MakeStridedView(), TArray< InElementType, InAllocatorType >::Num(), FMeshBuildVertexData::Position, FMeshBuildVertexView::Position, RemoveInvalidVertexColor(), TArray< InElementType, InAllocatorType >::Reserve(), FMeshBuildVertexData::TangentX, FMeshBuildVertexView::TangentX, FMeshBuildVertexData::TangentY, FMeshBuildVertexView::TangentY, FMeshBuildVertexData::TangentZ, FMeshBuildVertexView::TangentZ, FMeshBuildVertexData::UVs, and FMeshBuildVertexView::UVs.
MakeMeshBuildVertexView() [2/2]
FMeshBuildVertexView MakeMeshBuildVertexView (TArray< FStaticMeshBuildVertex > & InVertices) inline
Make a strided mesh build vertex view from FStaticMeshBuildVertex.
Definition at line 185 of file Components.h.
References FMeshBuildVertexView::Color, FStaticMeshBuildVertex::Color, MakeStridedView(), MAX_STATIC_TEXCOORDS, TArray< InElementType, InAllocatorType >::Num(), FMeshBuildVertexView::Position, FStaticMeshBuildVertex::Position, RemoveInvalidVertexColor(), FMeshBuildVertexView::TangentX, FStaticMeshBuildVertex::TangentX, FMeshBuildVertexView::TangentY, FStaticMeshBuildVertex::TangentY, FMeshBuildVertexView::TangentZ, FStaticMeshBuildVertex::TangentZ, and FMeshBuildVertexView::UVs.
MakeStaticMeshVertex() [1/2]
FStaticMeshBuildVertex MakeStaticMeshVertex (const FMeshBuildVertexData & InVertexData, int32 Index) inline
Definition at line 366 of file Components.h.
References FMeshBuildVertexData::Color, FStaticMeshBuildVertex::Color, MAX_STATIC_TEXCOORDS, TArray< InElementType, InAllocatorType >::Num(), FMeshBuildVertexData::Position, FStaticMeshBuildVertex::Position, FMeshBuildVertexData::TangentX, FStaticMeshBuildVertex::TangentX, FMeshBuildVertexData::TangentY, FStaticMeshBuildVertex::TangentY, FMeshBuildVertexData::TangentZ, FStaticMeshBuildVertex::TangentZ, FMeshBuildVertexData::UVs, FStaticMeshBuildVertex::UVs, FColor::White, and UE::Math::TVector2< float >::ZeroVector.
MakeStaticMeshVertex() [2/2]
FStaticMeshBuildVertex MakeStaticMeshVertex (const FMeshBuildVertexView & View, int32 Index) inline
Definition at line 335 of file Components.h.
References FMeshBuildVertexView::Color, MAX_STATIC_TEXCOORDS, TStridedView< InElementType, InSizeType >::Num(), FMeshBuildVertexView::Position, FMeshBuildVertexView::TangentX, FMeshBuildVertexView::TangentY, FMeshBuildVertexView::TangentZ, FMeshBuildVertexView::UVs, Vertex, FColor::White, and UE::Math::TVector2< float >::ZeroVector.
RemoveInvalidVertexColor() [1/2]
void RemoveInvalidVertexColor (FConstMeshBuildVertexView & VertexView) inline
Definition at line 157 of file Components.h.
References Color, FConstMeshBuildVertexView::Color, and TStridedView< InElementType, InSizeType >::Num().
RemoveInvalidVertexColor() [2/2]
void RemoveInvalidVertexColor (FMeshBuildVertexView & VertexView) inline
Definition at line 130 of file Components.h.
References Color, FMeshBuildVertexView::Color, and TStridedView< InElementType, InSizeType >::Num().
Referenced by MakeConstMeshBuildVertexView(), MakeConstMeshBuildVertexView(), MakeMeshBuildVertexView(), and MakeMeshBuildVertexView().