Unreal Engine 5.6 C++ API: FInputDeviceAnalogStickDeadZoneProperty Struct Reference
FInputDeviceAnalogStickDeadZoneProperty Struct Reference
A generic input device property that sets Deadzone for Analog Sticks.
#include "IInputInterface.h"
Public Member Functions
FInputDeviceAnalogStickDeadZoneProperty ()
FInputDeviceAnalogStickDeadZoneProperty (EInputDeviceAnalogStickMask InAffectedStick, float InDeadZone)
Public Member Functions inherited from FInputDeviceAnalogStickProperty
FInputDeviceAnalogStickProperty (FName InName)
FInputDeviceAnalogStickProperty (FName InName, EInputDeviceAnalogStickMask InAffectedStick)
Static Public Member Functions
static FName PropertyName ()
Data Fields
float DeadZone = 0
Data Fields inherited from FInputDeviceAnalogStickProperty
EInputDeviceAnalogStickMask AffectedStick = EInputDeviceAnalogStickMask::None
Which stick this property should effect.
Detailed Description
A generic input device property that sets Deadzone for Analog Sticks.
NOTE: Not all input device libraries do their own deadzone filtering, so the game must still do it. This is just to tell those device libraries that do some filtering not to ignore inputs of this size (circular) or larger.
Definition at line 265 of file IInputInterface.h.
Constructor & Destructor Documentation
FInputDeviceAnalogStickDeadZoneProperty() [1/2]
FInputDeviceAnalogStickDeadZoneProperty::FInputDeviceAnalogStickDeadZoneProperty () inline
Definition at line 267 of file IInputInterface.h.
References FInputDeviceAnalogStickProperty::FInputDeviceAnalogStickProperty(), and PropertyName().
FInputDeviceAnalogStickDeadZoneProperty() [2/2]
FInputDeviceAnalogStickDeadZoneProperty::FInputDeviceAnalogStickDeadZoneProperty (EInputDeviceAnalogStickMask InAffectedStick, float InDeadZone) inline
Definition at line 271 of file IInputInterface.h.
References FInputDeviceAnalogStickProperty::FInputDeviceAnalogStickProperty(), DeadZone, and PropertyName().
Member Function Documentation
PropertyName()
FName FInputDeviceAnalogStickDeadZoneProperty::PropertyName () inline static
Definition at line 276 of file IInputInterface.h.
References FName.
Referenced by FInputDeviceAnalogStickDeadZoneProperty(), and FInputDeviceAnalogStickDeadZoneProperty().
Field Documentation
DeadZone
float FInputDeviceAnalogStickDeadZoneProperty::DeadZone = 0
Definition at line 278 of file IInputInterface.h.
Referenced by FInputDeviceAnalogStickDeadZoneProperty().
The documentation for this struct was generated from the following file:
IInputInterface.h