Unreal Engine 5.6 C++ API: FCoreDelegates Class Reference
FCoreDelegates Class Reference
#include "CoreDelegates.h"
Data Structures
struct FExtraBinaryConfigData
Public Types
enum class EOnScreenMessageSeverity : uint8 { Info , Warning , Error }
enum class ETemperatureSeverity : uint8 {
Unknown , Good , Bad , Serious ,
Critical , NumSeverities
}
using FAttachShaderReadRequestFunc = TFunctionRef<class FIoRequest(const class FIoChunkId&, FGraphEventRef)>
typedef TSharedPtr< class IMovieStreamer, ESPMode::ThreadSafe > FMovieStreamerPtr
typedef TMultiMap< EOnScreenMessageSeverity, FText > FSeverityMessageMap
Public Member Functions
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDisallowedExecCommandCalled, const TCHAR *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNamedCommandParsed, const TCHAR *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNetworkConnectionChanged, ENetworkConnectionType)
UE_DEPRECATED (5.1, "OnControllerConnectionChange, use IPlatformInputDeviceMapper::GetOnInputDeviceConnectionChange() instead") static 1 TMulticastDelegate< void(bool
UE_DEPRECATED (5.1, "OnControllerPairingChange, use IPlatformInputDeviceMapper::GetOnInputDevicePairingChange() instead") static 1 TMulticastDelegate< void(int32 ControllerIndex
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "Use FPackageStore::Mount() instead") static 1 TDelegate< TSharedPtr< class IPackageStore >()> CreatePackageStore
UE_DEPRECATED (5.3, "This delegate is not thread safe while it can be used concurrently. Please use to GetApplicationWillTerminateDelegate() instead.") static 1 TMulticastDelegate< void()> ApplicationWillTerminateDelegate
UE_DEPRECATED (5.3, "This delegate is not thread-safe, please use GetOnAsyncLoadPackage().") static 1 TMulticastDelegate< void(const FString &)> OnAsyncLoadPackage
UE_DEPRECATED (5.3, "This delegate is not thread-safe, please use GetOnPakFileMounted2().") static 1 TMulticastDelegate< void(const IPakFile &)> OnPakFileMounted2
UE_DEPRECATED (5.3, "This delegate is not thread-safe, please use Use FCoreDelegates::GetOnFileOpenedForReadFromPakFile()") static 1 TMulticastDelegate< void(const TCHAR *PakFile
Static Public Member Functions
static TTSMulticastDelegate< void()> & GetApplicationWillTerminateDelegate ()
static TMulticastDelegate< void(const uint64, const uint64)> & GetGPUOutOfMemoryDelegate ()
static TDelegate< void(void *, int32)> & GetHotfixDelegate (EHotfixDelegates::Type HotFix)
static FSimpleMulticastDelegate & GetLowLevelAllocatorMemoryTrimDelegate ()
static FSimpleMulticastDelegate & GetMemoryTrimDelegate ()
static TTSMulticastDelegate< void(FStringView)> & GetOnAsyncLoadPackage ()
static TTSMulticastDelegate< void(const TCHAR *PakFile, const TCHAR *FileName)> & GetOnFileOpenedForReadFromPakFile ()
static TTSMulticastDelegate< void(const IPakFile &)> & GetOnPakFileMounted2 ()
static FSimpleMulticastDelegate & GetOutOfMemoryDelegate ()
static TDelegate< void(uint8[32])> & GetPakEncryptionKeyDelegate ()
static TDelegate< void(TArray< uint8 > &, TArray< uint8 > &)> & GetPakSigningKeysDelegate ()
static TMulticastDelegate< void()> & GetPreMainInitDelegate ()
static FSimpleMulticastDelegate & GetRefreshLowLevelAllocatorDelegate ()
static TMulticastDelegate< void(const FGuid &, const FAES::FAESKey &)> & GetRegisterEncryptionKeyMulticastDelegate ()
static TTSMulticastDelegate< void(FExtraBinaryConfigData &)> & TSAccessExtraBinaryConfigData ()
static TTSMulticastDelegate< void()> & TSConfigReadyForUse ()
Sent when GConfig is finished initializing.
static TTSMulticastDelegate< void(const TCHAR *IniFilename, int32 &ResponderCount)> & TSCountPreLoadConfigFileRespondersDelegate ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName)> & TSOnConfigSectionNameRead ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName)> & TSOnConfigSectionRead ()
static TTSMulticastDelegate< void(const FString &IniFilename, const TSet< FString > &SectionNames)> & TSOnConfigSectionsChanged ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName, const TCHAR *Key)> & TSOnConfigValueRead ()
static TTSMulticastDelegate< void(const FConfigFile *)> & TSOnFConfigCreated ()
static TTSMulticastDelegate< void(const FConfigFile *)> & TSOnFConfigDeleted ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, bool &bOutDeleted)> & TSPreDeleteConfigFileDelegate ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, FString &LoadedContents)> & TSPreLoadConfigFileDelegate ()
static TTSMulticastDelegate< void(const TCHAR *IniFilename, const FString &ContentsToSave, int32 &SavedCount)> & TSPreSaveConfigFileDelegate ()
Data Fields
const TCHAR * FileName
FPlatformUserId
FPlatformUserId NewUserPlatformId
int32 OnControllerConnectionChange
FPlatformUserId FPlatformUserId OldUserPlatformId OnControllerPairingChange
const TCHAR FNotThreadSafeNotCheckedDelegateUserPolicy OnFileOpenedForReadFromPakFile
Static Public Attributes
static TMulticastDelegate< void(FString)> ApplicationBackgroundSessionEventDelegate
static TMulticastDelegate< void(FString)> ApplicationFailedToRegisterForRemoteNotificationsDelegate
static TMulticastDelegate< void()> ApplicationHasEnteredForegroundDelegate
static TMulticastDelegate< void()> ApplicationHasReactivatedDelegate
static TMulticastDelegate< void()> ApplicationLicenseChange
static TMulticastDelegate< void(bool bIsNetworkInitialized)> ApplicationNetworkInitializationChanged
Called when the application's network initializes or shutdowns on platforms where the network stack is not always available.
static TMulticastDelegate< void()> ApplicationPerformFetchDelegate
static TMulticastDelegate< void(FString, int, int)> ApplicationReceivedLocalNotificationDelegate
static TMulticastDelegate< void(FString, int)> ApplicationReceivedRemoteNotificationDelegate
static TMulticastDelegate< void(int32)> ApplicationReceivedScreenOrientationChangedNotificationDelegate
Sent when a device screen orientation changes.
static TMulticastDelegate< void(const TArray< FString > &)> ApplicationReceivedStartupArgumentsDelegate
static TMulticastDelegate< void(TArray< uint8 >)> ApplicationRegisteredForRemoteNotificationsDelegate
IOS-style push notification delegates.
static TMulticastDelegate< void(int)> ApplicationRegisteredForUserNotificationsDelegate
static TMulticastDelegate< void()> ApplicationRequestAudioState
static TMulticastDelegate< void()> ApplicationShouldUnloadResourcesDelegate
static TMulticastDelegate< void(bool)> ApplicationSystemUIOverlayStateChangedDelegate
static TMulticastDelegate< void()> ApplicationWillDeactivateDelegate
IOS-style application lifecycle delegates.
static TMulticastDelegate< void()> ApplicationWillEnterBackgroundDelegate
static TMulticastDelegate< void(bool)> AudioInterruptionDelegate
static TMulticastDelegate< void(bool, int)> AudioMuteDelegate
static TMulticastDelegate< void(bool)> AudioRouteChangedDelegate
static FSimpleMulticastDelegate ColorPickerChanged
Color picker color has changed, please refresh as needed.
static TMulticastDelegate< void(const FCrashOverrideParameters &)> CrashOverrideParamsChanged
Sent by application code to set params that customize crash reporting behavior.
static TMulticastDelegate< void(const FString &)> GameSessionIDChanged
Sent when application code changes the currently active game session.
static TMulticastDelegate< void(const FString &)> GameStateClassChanged
Sent when application code changes game state.
static TMulticastDelegate< void(TArray< FString > &)> GatherAdditionalLocResPathsCallback
Delegate for gathering up additional localization paths that are unknown to the engine core (such as plugins)
static TDelegate< bool()> IsLoadingMovieCurrentlyPlaying
static TMulticastDelegate< void(bool)> IsVanillaProductChanged
Sent by engine code when the "vanilla" status of the engine changes.
static TDelegate< void(const FString &URL, FString *Error)> LaunchCustomHandlerForURL
static TMulticastDelegate< void(float DeltaTime)> MobileBackgroundTickDelegate
static TDelegate< EAppReturnType::Type(EAppMsgCategory, EAppMsgType::Type, const FText &, const FText &)> ModalMessageDialog
requests to open a message box
static TDelegate< IPakFile *(const FString &, int32)> MountPak
static TDelegate< bool(TArrayView< UE::FMountPaksExArgs >)> MountPaksEx
static TMulticastDelegate< void(const FString &)> NewFileAddedDelegate
static TMulticastDelegate< void()> NoPakFilesMountedDelegate
static TMulticastDelegate< void(const FString &Parameter, FPlatformUserId UserId)> OnActivatedByProtocol
static TMulticastDelegate< void(AActor *)> OnActorLabelChanged
static FSimpleMulticastDelegate OnAllModuleLoadingPhasesComplete
static TMulticastDelegate< void(const TCHAR *SectionName, const TCHAR *IniFilename, uint32 SetBy, bool bAllowCheating)> OnApplyCVarFromIni
static TMulticastDelegate< void()> OnAsyncLoadingFlush
static TMulticastDelegate< void()> OnAsyncLoadingFlushUpdate
static FSimpleMulticastDelegate OnBeginFrame
static FSimpleMulticastDelegate OnBeginFrameRT
static FSimpleMulticastDelegate OnChildEndFramePostFork
static FSimpleMulticastDelegate OnCommandletPostMain
static FSimpleMulticastDelegate OnCommandletPreMain
static FOnDisallowedExecCommandCalled OnDisallowedExecCommandCalled
static FSimpleMulticastDelegate OnEndFrame
static FSimpleMulticastDelegate OnEndFrameRT
static FSimpleMulticastDelegate OnEnginePreExit
static FSimpleMulticastDelegate OnExit
static TMulticastDelegate< void(int, const FName &)> OnFeatureLevelDisabled
static FSimpleMulticastDelegate OnFEngineLoopInitComplete
static TMulticastDelegate< void(const FString &)> OnGCFinishDestroyTimeExtended
Sent when GC finish destroy takes more time than expected.
static TDelegate< const TCHAR *()> OnGetBuildURL
static TDelegate< const TCHAR *()> OnGetExecutingJobURL
static TMulticastDelegate< void(FSeverityMessageMap &)> OnGetOnScreenMessages
static TMulticastDelegate< void()> OnHandleSystemEnsure
static TMulticastDelegate< void()> OnHandleSystemError
static FSimpleMulticastDelegate OnInit
static TMulticastDelegate< void(const FString &, const FString &)> OnInviteAccepted
Called when the user accepts an invitation to the current game.
static TMulticastDelegate< void(const FLogCategoryName &CategoryName, ELogVerbosity::Type OldVerbosity, ELogVerbosity::Type NewVerbosity)> OnLogVerbosityChanged
Called when the verbosity of a log category is changed.
static TMulticastDelegate< void(bool)> OnLowPowerMode
Called when the OS goes into low power mode.
static TDelegate< int32(const TArray< FString > &)> OnMountAllPakFiles
static TMulticastDelegate< void(const UE::FMultiprocessCreatedContext &)> OnMultiprocessWorkerCreated
static TMulticastDelegate< void(const UE::FMultiprocessDetachedContext &)> OnMultiprocessWorkerDetached
static FOnNamedCommandParsed OnNamedCommandParsed
static FOnNetworkConnectionChanged OnNetworkConnectionChanged
static TMulticastDelegate< void(ENetworkConnectionStatus LastConnectionState, ENetworkConnectionStatus ConnectionState)> OnNetworkConnectionStatusChanged
Called when the connection state as reported by the platform changes.
static TDelegate< void()> OnOptimizeMemoryUsageForMountedPaks
static FSimpleMulticastDelegate OnOutputDevicesInit
static PRAGMA_ENABLE_DEPRECATION_WARNINGS FSimpleMulticastDelegate OnParentBeginFork
static FSimpleMulticastDelegate OnParentPreFork
static FSimpleMulticastDelegate OnPostEngineInit
static TMulticastDelegate< void(EForkProcessRole ProcessRole)> OnPostFork
static FSimpleMulticastDelegate OnPreExit
static TMulticastDelegate< void()> OnSafeFrameChangedEvent
static FSimpleMulticastDelegate OnSamplingInput
static FSimpleMulticastDelegate OnShutdownAfterError
static TMulticastDelegate< void(const FString &)> OnSyncLoadPackage
static TMulticastDelegate< void(uint32 ResX, uint32 ResY)> OnSystemResolutionChanged
static TMulticastDelegate< void(const ITargetPlatform *)> OnTargetPlatformChangedSupportedFormats
static TMulticastDelegate< void(ETemperatureSeverity)> OnTemperatureChange
static TDelegate< bool(const FString &)> OnUnmountPak
static TMulticastDelegate< void(bool, int32, int32)> OnUserLoginChangedEvent
static TArray< TDelegate< bool(const FString &, FString &)> > PackageNameResolvers
static TDelegate< int32(const FString &)> PakChunkIdOverrideDelegate
static TMulticastDelegate< void(EConvertibleLaptopMode)> PlatformChangedLaptopMode
Sent when the platform changed its laptop mode (for convertible laptops).
static FSimpleMulticastDelegate PostModal
static TMulticastDelegate< void()> PostRenderingThreadCreated
Callback for notifications regarding changes of the rendering thread.
static FSimpleMulticastDelegate PostSlateModal
static TMulticastDelegate< void(class UWorld *, FIntVector, FIntVector)> PostWorldOriginOffset
called after world origin shifting
static TDelegate< void(TArrayView< const FSHAHash >, FAttachShaderReadRequestFunc)> PreloadPackageShaderMaps
static FSimpleMulticastDelegate PreModal
static TMulticastDelegate< void()> PreRenderingThreadDestroyed
static FSimpleMulticastDelegate PreSlateModal
static TMulticastDelegate< void(class UWorld *, FIntVector, FIntVector)> PreWorldOriginOffset
called before world origin shifting
static TMulticastDelegate< void(FMovieStreamerPtr)> RegisterMovieStreamerDelegate
static TDelegate< void(TArrayView< const FSHAHash >)> ReleasePreloadedPackageShaderMaps
static TDelegate< bool(const TCHAR *URL)> ShouldLaunchUrl
static TDelegate< void()> StarvedGameLoop
called when the main loop would otherwise starve.
static TMulticastDelegate< void(const TCHAR *, bool &, bool &)> StatCheckEnabled
Checks to see if the stat is already enabled.
static TMulticastDelegate< void(const bool)> StatDisableAll
Sent when all stats need to be disabled.
static TMulticastDelegate< void(const TCHAR *)> StatDisabled
Sent after each stat is disabled.
static TMulticastDelegate< void(const TCHAR *)> StatEnabled
Sent after each stat is enabled.
static TMulticastDelegate< void(FMovieStreamerPtr)> UnRegisterMovieStreamerDelegate
static TMulticastDelegate< void(const FString &)> UserActivityStringChanged
Sent when application code changes the user activity hint string for analytics, crash reports, etc.
static TMulticastDelegate< void(bool)> UserMusicInterruptDelegate
static TMulticastDelegate< void()> VRControllerRecentered
Sent when a 3DOF VR controller is recentered.
static TMulticastDelegate< void()> VRHeadsetConnectCanceled
Sent when connection to VR HMD connection is refused by the player.
static TMulticastDelegate< void()> VRHeadsetLost
Sent when connection to VR HMD is lost.
static TMulticastDelegate< void()> VRHeadsetPutOnHead
Sent when the VR HMD detects that it has been put on by the player.
static TMulticastDelegate< void()> VRHeadsetRecenter
Sent when the platform requests a low-level VR recentering.
static TMulticastDelegate< void()> VRHeadsetReconnected
Sent when connection to VR HMD is restored.
static TMulticastDelegate< void()> VRHeadsetRemovedFromHead
Sent when the VR HMD detects that it has been taken off by the player.
static TMulticastDelegate< void()> VRHeadsetTrackingInitializedDelegate
Sent when the platform finds that needed headset tracking on startup has completed (Most platforms do not need this.)
static TMulticastDelegate< void()> VRHeadsetTrackingInitializingAndNeedsHMDToBeTrackedDelegate
Sent when the platform needs the user to fix headset tracking on startup (Most platforms do not need this.)
Private Member Functions
FCoreDelegates ()=default
Static Private Attributes
static TArray< TDelegate< void(void *, int32)> > HotFixDelegates
Detailed Description
Definition at line 101 of file CoreDelegates.h.
Member Typedef Documentation
FAttachShaderReadRequestFunc
using FCoreDelegates::FAttachShaderReadRequestFunc = TFunctionRef<class FIoRequest(const class FIoChunkId&, FGraphEventRef)>
Definition at line 581 of file CoreDelegates.h.
FMovieStreamerPtr
typedef TSharedPtr<class IMovieStreamer, ESPMode::ThreadSafe> FCoreDelegates::FMovieStreamerPtr
Definition at line 171 of file CoreDelegates.h.
FSeverityMessageMap
typedef TMultiMap<EOnScreenMessageSeverity, FText> FCoreDelegates::FSeverityMessageMap
Definition at line 521 of file CoreDelegates.h.
Member Enumeration Documentation
EOnScreenMessageSeverity
enum class FCoreDelegates::EOnScreenMessageSeverity : uint8 strong
Enumerator
Info
Warning
Error
Definition at line 515 of file CoreDelegates.h.
ETemperatureSeverity
enum class FCoreDelegates::ETemperatureSeverity : uint8 strong
Enumerator
Unknown
Good
Bad
Serious
Critical
NumSeverities
Definition at line 287 of file CoreDelegates.h.
Constructor & Destructor Documentation
FCoreDelegates()
FCoreDelegates::FCoreDelegates () private default
References bAllowCheating, DeltaTime, FileName, FPlatformUserId, Key, NewUserPlatformId, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and SetBy.
Member Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam() [1/3]
FCoreDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDisallowedExecCommandCalled , const TCHAR *)
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [2/3]
FCoreDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNamedCommandParsed , const TCHAR *)
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [3/3]
FCoreDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNetworkConnectionChanged , ENetworkConnectionType)
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), and DECLARE_MULTICAST_DELEGATE_OneParam().
GetApplicationWillTerminateDelegate()
TTSMulticastDelegate< void()> & FCoreDelegates::GetApplicationWillTerminateDelegate () static
References GetApplicationWillTerminateDelegate().
Referenced by GetApplicationWillTerminateDelegate().
GetGPUOutOfMemoryDelegate()
TMulticastDelegate< void(const uint64, const uint64)> & FCoreDelegates::GetGPUOutOfMemoryDelegate () static
References GetGPUOutOfMemoryDelegate().
Referenced by GetGPUOutOfMemoryDelegate().
GetHotfixDelegate()
TDelegate< void(void *, int32)> & FCoreDelegates::GetHotfixDelegate (EHotfixDelegates::Type HotFix) static
References GetHotfixDelegate().
Referenced by GetHotfixDelegate().
GetLowLevelAllocatorMemoryTrimDelegate()
FSimpleMulticastDelegate & FCoreDelegates::GetLowLevelAllocatorMemoryTrimDelegate () static
References GetLowLevelAllocatorMemoryTrimDelegate().
Referenced by GetLowLevelAllocatorMemoryTrimDelegate().
GetMemoryTrimDelegate()
FSimpleMulticastDelegate & FCoreDelegates::GetMemoryTrimDelegate () static
References GetMemoryTrimDelegate().
Referenced by GetMemoryTrimDelegate().
GetOnAsyncLoadPackage()
TTSMulticastDelegate< void(FStringView)> & FCoreDelegates::GetOnAsyncLoadPackage () static
References GetOnAsyncLoadPackage().
Referenced by GetOnAsyncLoadPackage().
GetOnFileOpenedForReadFromPakFile()
TTSMulticastDelegate< void(const TCHAR *PakFile, const TCHAR *FileName)> & FCoreDelegates::GetOnFileOpenedForReadFromPakFile () static
References FileName, and GetOnFileOpenedForReadFromPakFile().
Referenced by GetOnFileOpenedForReadFromPakFile().
GetOnPakFileMounted2()
TTSMulticastDelegate< void(const IPakFile &)> & FCoreDelegates::GetOnPakFileMounted2 () static
References GetOnPakFileMounted2().
Referenced by GetOnPakFileMounted2().
GetOutOfMemoryDelegate()
FSimpleMulticastDelegate & FCoreDelegates::GetOutOfMemoryDelegate () static
References GetOutOfMemoryDelegate().
Referenced by GetOutOfMemoryDelegate().
GetPakEncryptionKeyDelegate()
TDelegate< void(uint8[32])> & FCoreDelegates::GetPakEncryptionKeyDelegate () static
References GetPakEncryptionKeyDelegate().
Referenced by KeyChainUtilities::ApplyEncryptionKeys(), and GetPakEncryptionKeyDelegate().
GetPakSigningKeysDelegate()
TDelegate< void(TArray< uint8 > &, TArray< uint8 > &)> & FCoreDelegates::GetPakSigningKeysDelegate () static
References GetPakSigningKeysDelegate().
Referenced by GetPakSigningKeysDelegate().
GetPreMainInitDelegate()
TMulticastDelegate< void()> & FCoreDelegates::GetPreMainInitDelegate () static
References GetPreMainInitDelegate().
Referenced by GetPreMainInitDelegate().
GetRefreshLowLevelAllocatorDelegate()
FSimpleMulticastDelegate & FCoreDelegates::GetRefreshLowLevelAllocatorDelegate () static
References GetRefreshLowLevelAllocatorDelegate().
Referenced by GetRefreshLowLevelAllocatorDelegate().
GetRegisterEncryptionKeyMulticastDelegate()
TMulticastDelegate< void(const FGuid &, const FAES::FAESKey &)> & FCoreDelegates::GetRegisterEncryptionKeyMulticastDelegate () static
References GetRegisterEncryptionKeyMulticastDelegate().
Referenced by KeyChainUtilities::ApplyEncryptionKeys(), and GetRegisterEncryptionKeyMulticastDelegate().
TSAccessExtraBinaryConfigData()
TTSMulticastDelegate< void(FExtraBinaryConfigData &)> & FCoreDelegates::TSAccessExtraBinaryConfigData () static
TSConfigReadyForUse()
TTSMulticastDelegate< void()> & FCoreDelegates::TSConfigReadyForUse () static
Sent when GConfig is finished initializing.
References TSConfigReadyForUse().
Referenced by TSConfigReadyForUse().
TSCountPreLoadConfigFileRespondersDelegate()
TTSMulticastDelegate< void(const TCHAR *IniFilename, int32 &ResponderCount)> & FCoreDelegates::TSCountPreLoadConfigFileRespondersDelegate () static
TSOnConfigSectionNameRead()
TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName)> & FCoreDelegates::TSOnConfigSectionNameRead () static
TSOnConfigSectionRead()
TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName)> & FCoreDelegates::TSOnConfigSectionRead () static
TSOnConfigSectionsChanged()
TTSMulticastDelegate< void(const FString &IniFilename, const TSet< FString > &SectionNames)> & FCoreDelegates::TSOnConfigSectionsChanged () static
TSOnConfigValueRead()
TTSMulticastDelegate< void(const TCHAR *IniFilename, const TCHAR *SectionName, const TCHAR *Key)> & FCoreDelegates::TSOnConfigValueRead () static
References Key.
TSOnFConfigCreated()
TTSMulticastDelegate< void(const FConfigFile *)> & FCoreDelegates::TSOnFConfigCreated () static
TSOnFConfigDeleted()
TTSMulticastDelegate< void(const FConfigFile *)> & FCoreDelegates::TSOnFConfigDeleted () static
TSPreDeleteConfigFileDelegate()
TTSMulticastDelegate< void(const TCHAR *IniFilename, bool &bOutDeleted)> & FCoreDelegates::TSPreDeleteConfigFileDelegate () static
TSPreLoadConfigFileDelegate()
TTSMulticastDelegate< void(const TCHAR *IniFilename, FString &LoadedContents)> & FCoreDelegates::TSPreLoadConfigFileDelegate () static
TSPreSaveConfigFileDelegate()
TTSMulticastDelegate< void(const TCHAR *IniFilename, const FString &ContentsToSave, int32 &SavedCount)> & FCoreDelegates::TSPreSaveConfigFileDelegate () static
UE_DEPRECATED() [1/7]
FCoreDelegates::UE_DEPRECATED (5. 1, " OnControllerConnectionChange, use IPlatformInputDeviceMapper::GetOnInputDeviceConnectionChange() instead")
References UE_DEPRECATED().
UE_DEPRECATED() [2/7]
FCoreDelegates::UE_DEPRECATED (5. 1, " OnControllerPairingChange, use IPlatformInputDeviceMapper::GetOnInputDevicePairingChange() instead")
References UE_DEPRECATED().
UE_DEPRECATED() [3/7]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FCoreDelegates::UE_DEPRECATED (5. 1, "Use FPackageStore::Mount() instead")
References PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED() [4/7]
FCoreDelegates::UE_DEPRECATED (5. 3, "This delegate is not thread safe while it can be used concurrently. Please use to GetApplicationWillTerminateDelegate() instead.")
UE_DEPRECATED() [5/7]
FCoreDelegates::UE_DEPRECATED (5. 3, "This delegate is not thread- safe, please use GetOnAsyncLoadPackage().") const &
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/7]
FCoreDelegates::UE_DEPRECATED (5. 3, "This delegate is not thread- safe, please use GetOnPakFileMounted2().") const &
References UE_DEPRECATED().
UE_DEPRECATED() [7/7]
FCoreDelegates::UE_DEPRECATED (5. 3, "This delegate is not thread- safe, please use Use FCoreDelegates::GetOnFileOpenedForReadFromPakFile()") const
References UE_DEPRECATED().
Field Documentation
ApplicationBackgroundSessionEventDelegate
TMulticastDelegate<void(FString)> FCoreDelegates::ApplicationBackgroundSessionEventDelegate static
Definition at line 416 of file CoreDelegates.h.
ApplicationFailedToRegisterForRemoteNotificationsDelegate
TMulticastDelegate<void(FString)> FCoreDelegates::ApplicationFailedToRegisterForRemoteNotificationsDelegate static
Definition at line 404 of file CoreDelegates.h.
ApplicationHasEnteredForegroundDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationHasEnteredForegroundDelegate static
Definition at line 344 of file CoreDelegates.h.
ApplicationHasReactivatedDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationHasReactivatedDelegate static
Definition at line 335 of file CoreDelegates.h.
ApplicationLicenseChange
TMulticastDelegate<void()> FCoreDelegates::ApplicationLicenseChange static
Definition at line 435 of file CoreDelegates.h.
ApplicationNetworkInitializationChanged
TMulticastDelegate<void(bool bIsNetworkInitialized)> FCoreDelegates::ApplicationNetworkInitializationChanged static
Called when the application's network initializes or shutdowns on platforms where the network stack is not always available.
Definition at line 547 of file CoreDelegates.h.
ApplicationPerformFetchDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationPerformFetchDelegate static
Definition at line 413 of file CoreDelegates.h.
ApplicationReceivedLocalNotificationDelegate
TMulticastDelegate<void(FString, int, int)> FCoreDelegates::ApplicationReceivedLocalNotificationDelegate static
Definition at line 410 of file CoreDelegates.h.
ApplicationReceivedRemoteNotificationDelegate
TMulticastDelegate<void(FString, int)> FCoreDelegates::ApplicationReceivedRemoteNotificationDelegate static
Definition at line 407 of file CoreDelegates.h.
ApplicationReceivedScreenOrientationChangedNotificationDelegate
TMulticastDelegate<void(int32)> FCoreDelegates::ApplicationReceivedScreenOrientationChangedNotificationDelegate static
Sent when a device screen orientation changes.
Definition at line 419 of file CoreDelegates.h.
ApplicationReceivedStartupArgumentsDelegate
TMulticastDelegate<void(const TArray<FString>&)> FCoreDelegates::ApplicationReceivedStartupArgumentsDelegate static
Definition at line 393 of file CoreDelegates.h.
ApplicationRegisteredForRemoteNotificationsDelegate
TMulticastDelegate<void(TArray<uint8>)> FCoreDelegates::ApplicationRegisteredForRemoteNotificationsDelegate static
IOS-style push notification delegates.
Definition at line 398 of file CoreDelegates.h.
ApplicationRegisteredForUserNotificationsDelegate
TMulticastDelegate<void(int)> FCoreDelegates::ApplicationRegisteredForUserNotificationsDelegate static
Definition at line 401 of file CoreDelegates.h.
ApplicationRequestAudioState
TMulticastDelegate<void()> FCoreDelegates::ApplicationRequestAudioState static
Definition at line 387 of file CoreDelegates.h.
ApplicationShouldUnloadResourcesDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationShouldUnloadResourcesDelegate static
Definition at line 390 of file CoreDelegates.h.
ApplicationSystemUIOverlayStateChangedDelegate
TMulticastDelegate<void(bool)> FCoreDelegates::ApplicationSystemUIOverlayStateChangedDelegate static
Definition at line 357 of file CoreDelegates.h.
ApplicationWillDeactivateDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationWillDeactivateDelegate static
IOS-style application lifecycle delegates.
Definition at line 332 of file CoreDelegates.h.
ApplicationWillEnterBackgroundDelegate
TMulticastDelegate<void()> FCoreDelegates::ApplicationWillEnterBackgroundDelegate static
Definition at line 341 of file CoreDelegates.h.
AudioInterruptionDelegate
TMulticastDelegate<void(bool)> FCoreDelegates::AudioInterruptionDelegate static
Definition at line 380 of file CoreDelegates.h.
AudioMuteDelegate
TMulticastDelegate<void(bool, int)> FCoreDelegates::AudioMuteDelegate static
Definition at line 373 of file CoreDelegates.h.
AudioRouteChangedDelegate
TMulticastDelegate<void(bool)> FCoreDelegates::AudioRouteChangedDelegate static
Definition at line 377 of file CoreDelegates.h.
ColorPickerChanged
FSimpleMulticastDelegate FCoreDelegates::ColorPickerChanged static
Color picker color has changed, please refresh as needed.
Definition at line 253 of file CoreDelegates.h.
CrashOverrideParamsChanged
TMulticastDelegate<void(const FCrashOverrideParameters&)> FCoreDelegates::CrashOverrideParamsChanged static
Sent by application code to set params that customize crash reporting behavior.
Definition at line 477 of file CoreDelegates.h.
FileName
const TCHAR* FCoreDelegates::FileName
Definition at line 168 of file CoreDelegates.h.
Referenced by FCoreDelegates(), and GetOnFileOpenedForReadFromPakFile().
FPlatformUserId
FCoreDelegates::FPlatformUserId
Definition at line 127 of file CoreDelegates.h.
Referenced by FCoreDelegates().
GameSessionIDChanged
TMulticastDelegate<void(const FString&)> FCoreDelegates::GameSessionIDChanged static
Sent when application code changes the currently active game session.
The exact semantics of this will vary between games but it is useful for analytics, crash reports, etc
Definition at line 471 of file CoreDelegates.h.
GameStateClassChanged
TMulticastDelegate<void(const FString&)> FCoreDelegates::GameStateClassChanged static
Sent when application code changes game state.
The exact semantics of this will vary between games but it is useful for analytics, crash reports, etc
Definition at line 474 of file CoreDelegates.h.
GatherAdditionalLocResPathsCallback
TMulticastDelegate<void(TArray<FString>&)> FCoreDelegates::GatherAdditionalLocResPathsCallback static
Delegate for gathering up additional localization paths that are unknown to the engine core (such as plugins)
Definition at line 250 of file CoreDelegates.h.
HotFixDelegates
TArray<TDelegate<void(void*, int32)> > FCoreDelegates::HotFixDelegates static private
Definition at line 626 of file CoreDelegates.h.
IsLoadingMovieCurrentlyPlaying
TDelegate<bool()> FCoreDelegates::IsLoadingMovieCurrentlyPlaying static
Definition at line 531 of file CoreDelegates.h.
IsVanillaProductChanged
TMulticastDelegate<void(bool)> FCoreDelegates::IsVanillaProductChanged static
Sent by engine code when the "vanilla" status of the engine changes.
Definition at line 480 of file CoreDelegates.h.
LaunchCustomHandlerForURL
TDelegate<void(const FString& URL, FString* Error)> FCoreDelegates::LaunchCustomHandlerForURL static
Definition at line 538 of file CoreDelegates.h.
MobileBackgroundTickDelegate
TMulticastDelegate<void(float DeltaTime)> FCoreDelegates::MobileBackgroundTickDelegate static
Definition at line 362 of file CoreDelegates.h.
ModalMessageDialog
TDelegate<EAppReturnType::Type(EAppMsgCategory, EAppMsgType::Type, const FText&, const FText&)> FCoreDelegates::ModalMessageDialog static
requests to open a message box
Definition at line 256 of file CoreDelegates.h.
MountPak
TDelegate<IPakFile*(const FString&, int32)> FCoreDelegates::MountPak static
Definition at line 140 of file CoreDelegates.h.
MountPaksEx
TDelegate<bool(TArrayView<UE::FMountPaksExArgs>)> FCoreDelegates::MountPaksEx static
Definition at line 144 of file CoreDelegates.h.
NewFileAddedDelegate
TMulticastDelegate<void(const FString&)> FCoreDelegates::NewFileAddedDelegate static
Definition at line 161 of file CoreDelegates.h.
NewUserPlatformId
FPlatformUserId FCoreDelegates::NewUserPlatformId
Definition at line 131 of file CoreDelegates.h.
Referenced by FCoreDelegates().
NoPakFilesMountedDelegate
TMulticastDelegate<void()> FCoreDelegates::NoPakFilesMountedDelegate static
Definition at line 164 of file CoreDelegates.h.
OnActivatedByProtocol
TMulticastDelegate<void(const FString& Parameter, FPlatformUserId UserId)> FCoreDelegates::OnActivatedByProtocol static
Definition at line 541 of file CoreDelegates.h.
OnActorLabelChanged
TMulticastDelegate<void(AActor*)> FCoreDelegates::OnActorLabelChanged static
Definition at line 187 of file CoreDelegates.h.
OnAllModuleLoadingPhasesComplete
FSimpleMulticastDelegate FCoreDelegates::OnAllModuleLoadingPhasesComplete static
Definition at line 229 of file CoreDelegates.h.
OnApplyCVarFromIni
TMulticastDelegate<void(const TCHAR* SectionName, const TCHAR* IniFilename, uint32 SetBy, bool bAllowCheating)> FCoreDelegates::OnApplyCVarFromIni static
Definition at line 316 of file CoreDelegates.h.
OnAsyncLoadingFlush
TMulticastDelegate<void()> FCoreDelegates::OnAsyncLoadingFlush static
Definition at line 105 of file CoreDelegates.h.
OnAsyncLoadingFlushUpdate
TMulticastDelegate<void()> FCoreDelegates::OnAsyncLoadingFlushUpdate static
Definition at line 108 of file CoreDelegates.h.
OnBeginFrame
FSimpleMulticastDelegate FCoreDelegates::OnBeginFrame static
Definition at line 262 of file CoreDelegates.h.
OnBeginFrameRT
FSimpleMulticastDelegate FCoreDelegates::OnBeginFrameRT static
Definition at line 271 of file CoreDelegates.h.
OnChildEndFramePostFork
FSimpleMulticastDelegate FCoreDelegates::OnChildEndFramePostFork static
Definition at line 600 of file CoreDelegates.h.
OnCommandletPostMain
FSimpleMulticastDelegate FCoreDelegates::OnCommandletPostMain static
Definition at line 238 of file CoreDelegates.h.
OnCommandletPreMain
FSimpleMulticastDelegate FCoreDelegates::OnCommandletPreMain static
Definition at line 235 of file CoreDelegates.h.
OnControllerConnectionChange
int32 FCoreDelegates::OnControllerConnectionChange
Definition at line 127 of file CoreDelegates.h.
OnControllerPairingChange
FPlatformUserId FPlatformUserId OldUserPlatformId FCoreDelegates::OnControllerPairingChange
Definition at line 131 of file CoreDelegates.h.
OnDisallowedExecCommandCalled
FOnDisallowedExecCommandCalled FCoreDelegates::OnDisallowedExecCommandCalled static
Definition at line 608 of file CoreDelegates.h.
OnEndFrame
FSimpleMulticastDelegate FCoreDelegates::OnEndFrame static
Definition at line 268 of file CoreDelegates.h.
OnEndFrameRT
FSimpleMulticastDelegate FCoreDelegates::OnEndFrameRT static
Definition at line 274 of file CoreDelegates.h.
OnEnginePreExit
FSimpleMulticastDelegate FCoreDelegates::OnEnginePreExit static
Definition at line 247 of file CoreDelegates.h.
OnExit
FSimpleMulticastDelegate FCoreDelegates::OnExit static
Definition at line 241 of file CoreDelegates.h.
OnFeatureLevelDisabled
TMulticastDelegate<void(int, const FName&)> FCoreDelegates::OnFeatureLevelDisabled static
Definition at line 325 of file CoreDelegates.h.
OnFEngineLoopInitComplete
FSimpleMulticastDelegate FCoreDelegates::OnFEngineLoopInitComplete static
Definition at line 232 of file CoreDelegates.h.
OnFileOpenedForReadFromPakFile
const TCHAR FNotThreadSafeNotCheckedDelegateUserPolicy FCoreDelegates::OnFileOpenedForReadFromPakFile
Definition at line 168 of file CoreDelegates.h.
OnGCFinishDestroyTimeExtended
TMulticastDelegate<void(const FString&)> FCoreDelegates::OnGCFinishDestroyTimeExtended static
Sent when GC finish destroy takes more time than expected.
Definition at line 544 of file CoreDelegates.h.
OnGetBuildURL
TDelegate<const TCHAR*()> FCoreDelegates::OnGetBuildURL static
Definition at line 611 of file CoreDelegates.h.
OnGetExecutingJobURL
TDelegate<const TCHAR*()> FCoreDelegates::OnGetExecutingJobURL static
Definition at line 614 of file CoreDelegates.h.
OnGetOnScreenMessages
TMulticastDelegate<void(FSeverityMessageMap&)> FCoreDelegates::OnGetOnScreenMessages static
Definition at line 529 of file CoreDelegates.h.
OnHandleSystemEnsure
TMulticastDelegate<void()> FCoreDelegates::OnHandleSystemEnsure static
Definition at line 181 of file CoreDelegates.h.
OnHandleSystemError
TMulticastDelegate<void()> FCoreDelegates::OnHandleSystemError static
Definition at line 184 of file CoreDelegates.h.
OnInit
FSimpleMulticastDelegate FCoreDelegates::OnInit static
Definition at line 220 of file CoreDelegates.h.
OnInviteAccepted
TMulticastDelegate<void(const FString&, const FString&)> FCoreDelegates::OnInviteAccepted static
Called when the user accepts an invitation to the current game.
Definition at line 259 of file CoreDelegates.h.
OnLogVerbosityChanged
TMulticastDelegate<void(const FLogCategoryName& CategoryName, ELogVerbosity::Type OldVerbosity, ELogVerbosity::Type NewVerbosity)> FCoreDelegates::OnLogVerbosityChanged static
Called when the verbosity of a log category is changed.
Definition at line 585 of file CoreDelegates.h.
OnLowPowerMode
TMulticastDelegate<void(bool)> FCoreDelegates::OnLowPowerMode static
Called when the OS goes into low power mode.
Definition at line 300 of file CoreDelegates.h.
OnMountAllPakFiles
TDelegate<int32(const TArray<FString>&)> FCoreDelegates::OnMountAllPakFiles static
Definition at line 137 of file CoreDelegates.h.
OnMultiprocessWorkerCreated
TMulticastDelegate<void(const UE::FMultiprocessCreatedContext&)> FCoreDelegates::OnMultiprocessWorkerCreated static
Definition at line 618 of file CoreDelegates.h.
OnMultiprocessWorkerDetached
TMulticastDelegate<void(const UE::FMultiprocessDetachedContext&)> FCoreDelegates::OnMultiprocessWorkerDetached static
Definition at line 621 of file CoreDelegates.h.
OnNamedCommandParsed
FOnNamedCommandParsed FCoreDelegates::OnNamedCommandParsed static
Definition at line 604 of file CoreDelegates.h.
OnNetworkConnectionChanged
FOnNetworkConnectionChanged FCoreDelegates::OnNetworkConnectionChanged static
Definition at line 303 of file CoreDelegates.h.
OnNetworkConnectionStatusChanged
TMulticastDelegate<void(ENetworkConnectionStatus LastConnectionState, ENetworkConnectionStatus ConnectionState)> FCoreDelegates::OnNetworkConnectionStatusChanged static
Called when the connection state as reported by the platform changes.
Parameters
LastConnectionState last state of the connection
ConnectionState current state of the connection
Definition at line 555 of file CoreDelegates.h.
OnOptimizeMemoryUsageForMountedPaks
TDelegate<void()> FCoreDelegates::OnOptimizeMemoryUsageForMountedPaks static
Definition at line 153 of file CoreDelegates.h.
OnOutputDevicesInit
FSimpleMulticastDelegate FCoreDelegates::OnOutputDevicesInit static
Definition at line 223 of file CoreDelegates.h.
OnParentBeginFork
PRAGMA_ENABLE_DEPRECATION_WARNINGS FSimpleMulticastDelegate FCoreDelegates::OnParentBeginFork static
Definition at line 593 of file CoreDelegates.h.
OnParentPreFork
FSimpleMulticastDelegate FCoreDelegates::OnParentPreFork static
Definition at line 595 of file CoreDelegates.h.
OnPostEngineInit
FSimpleMulticastDelegate FCoreDelegates::OnPostEngineInit static
Definition at line 226 of file CoreDelegates.h.
OnPostFork
TMulticastDelegate<void(EForkProcessRole ProcessRole)> FCoreDelegates::OnPostFork static
Definition at line 598 of file CoreDelegates.h.
OnPreExit
FSimpleMulticastDelegate FCoreDelegates::OnPreExit static
Definition at line 244 of file CoreDelegates.h.
OnSafeFrameChangedEvent
TMulticastDelegate<void()> FCoreDelegates::OnSafeFrameChangedEvent static
Definition at line 134 of file CoreDelegates.h.
OnSamplingInput
FSimpleMulticastDelegate FCoreDelegates::OnSamplingInput static
Definition at line 265 of file CoreDelegates.h.
OnShutdownAfterError
FSimpleMulticastDelegate FCoreDelegates::OnShutdownAfterError static
Definition at line 217 of file CoreDelegates.h.
OnSyncLoadPackage
TMulticastDelegate<void(const FString&)> FCoreDelegates::OnSyncLoadPackage static
Definition at line 117 of file CoreDelegates.h.
OnSystemResolutionChanged
TMulticastDelegate<void(uint32 ResX, uint32 ResY)> FCoreDelegates::OnSystemResolutionChanged static
Definition at line 318 of file CoreDelegates.h.
OnTargetPlatformChangedSupportedFormats
TMulticastDelegate<void(const ITargetPlatform*)> FCoreDelegates::OnTargetPlatformChangedSupportedFormats static
Definition at line 322 of file CoreDelegates.h.
OnTemperatureChange
TMulticastDelegate<void(ETemperatureSeverity)> FCoreDelegates::OnTemperatureChange static
Definition at line 297 of file CoreDelegates.h.
OnUnmountPak
TDelegate<bool(const FString&)> FCoreDelegates::OnUnmountPak static
Definition at line 147 of file CoreDelegates.h.
OnUserLoginChangedEvent
TMulticastDelegate<void(bool, int32, int32)> FCoreDelegates::OnUserLoginChangedEvent static
Definition at line 123 of file CoreDelegates.h.
PackageNameResolvers
TArray<TDelegate<bool(const FString&, FString&)> > FCoreDelegates::PackageNameResolvers static
Definition at line 497 of file CoreDelegates.h.
PakChunkIdOverrideDelegate
TDelegate<int32(const FString&)> FCoreDelegates::PakChunkIdOverrideDelegate static
Definition at line 150 of file CoreDelegates.h.
PlatformChangedLaptopMode
TMulticastDelegate<void(EConvertibleLaptopMode)> FCoreDelegates::PlatformChangedLaptopMode static
Sent when the platform changed its laptop mode (for convertible laptops).
Definition at line 438 of file CoreDelegates.h.
PostModal
FSimpleMulticastDelegate FCoreDelegates::PostModal static
Definition at line 200 of file CoreDelegates.h.
PostRenderingThreadCreated
TMulticastDelegate<void()> FCoreDelegates::PostRenderingThreadCreated static
Callback for notifications regarding changes of the rendering thread.
Sent just after the rendering thread has been created.
Definition at line 491 of file CoreDelegates.h.
PostSlateModal
FSimpleMulticastDelegate FCoreDelegates::PostSlateModal static
Definition at line 206 of file CoreDelegates.h.
PostWorldOriginOffset
TMulticastDelegate<void(class UWorld*, FIntVector, FIntVector)> FCoreDelegates::PostWorldOriginOffset static
called after world origin shifting
Definition at line 280 of file CoreDelegates.h.
PreloadPackageShaderMaps
TDelegate<void(TArrayView<const FSHAHash>, FAttachShaderReadRequestFunc)> FCoreDelegates::PreloadPackageShaderMaps static
Definition at line 582 of file CoreDelegates.h.
PreModal
FSimpleMulticastDelegate FCoreDelegates::PreModal static
Definition at line 197 of file CoreDelegates.h.
PreRenderingThreadDestroyed
TMulticastDelegate<void()> FCoreDelegates::PreRenderingThreadDestroyed static
Definition at line 493 of file CoreDelegates.h.
PreSlateModal
FSimpleMulticastDelegate FCoreDelegates::PreSlateModal static
Definition at line 203 of file CoreDelegates.h.
PreWorldOriginOffset
TMulticastDelegate<void(class UWorld*, FIntVector, FIntVector)> FCoreDelegates::PreWorldOriginOffset static
called before world origin shifting
Definition at line 278 of file CoreDelegates.h.
RegisterMovieStreamerDelegate
TMulticastDelegate<void(FMovieStreamerPtr)> FCoreDelegates::RegisterMovieStreamerDelegate static
Definition at line 175 of file CoreDelegates.h.
ReleasePreloadedPackageShaderMaps
TDelegate<void(TArrayView<const FSHAHash>)> FCoreDelegates::ReleasePreloadedPackageShaderMaps static
Definition at line 583 of file CoreDelegates.h.
ShouldLaunchUrl
TDelegate<bool(const TCHAR* URL)> FCoreDelegates::ShouldLaunchUrl static
Definition at line 535 of file CoreDelegates.h.
StarvedGameLoop
TDelegate<void()> FCoreDelegates::StarvedGameLoop static
called when the main loop would otherwise starve.
Definition at line 283 of file CoreDelegates.h.
StatCheckEnabled
TMulticastDelegate<void(const TCHAR*, bool&, bool&)> FCoreDelegates::StatCheckEnabled static
Checks to see if the stat is already enabled.
Definition at line 422 of file CoreDelegates.h.
StatDisableAll
TMulticastDelegate<void(const bool)> FCoreDelegates::StatDisableAll static
Sent when all stats need to be disabled.
Definition at line 431 of file CoreDelegates.h.
StatDisabled
TMulticastDelegate<void(const TCHAR*)> FCoreDelegates::StatDisabled static
Sent after each stat is disabled.
Definition at line 428 of file CoreDelegates.h.
StatEnabled
TMulticastDelegate<void(const TCHAR*)> FCoreDelegates::StatEnabled static
Sent after each stat is enabled.
Definition at line 425 of file CoreDelegates.h.
UnRegisterMovieStreamerDelegate
TMulticastDelegate<void(FMovieStreamerPtr)> FCoreDelegates::UnRegisterMovieStreamerDelegate static
Definition at line 178 of file CoreDelegates.h.
UserActivityStringChanged
TMulticastDelegate<void(const FString&)> FCoreDelegates::UserActivityStringChanged static
Sent when application code changes the user activity hint string for analytics, crash reports, etc.
Definition at line 468 of file CoreDelegates.h.
UserMusicInterruptDelegate
TMulticastDelegate<void(bool)> FCoreDelegates::UserMusicInterruptDelegate static
Definition at line 368 of file CoreDelegates.h.
VRControllerRecentered
TMulticastDelegate<void()> FCoreDelegates::VRControllerRecentered static
Sent when a 3DOF VR controller is recentered.
Definition at line 465 of file CoreDelegates.h.
VRHeadsetConnectCanceled
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetConnectCanceled static
Sent when connection to VR HMD connection is refused by the player.
Definition at line 456 of file CoreDelegates.h.
VRHeadsetLost
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetLost static
Sent when connection to VR HMD is lost.
Definition at line 450 of file CoreDelegates.h.
VRHeadsetPutOnHead
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetPutOnHead static
Sent when the VR HMD detects that it has been put on by the player.
Definition at line 459 of file CoreDelegates.h.
VRHeadsetRecenter
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetRecenter static
Sent when the platform requests a low-level VR recentering.
Definition at line 447 of file CoreDelegates.h.
VRHeadsetReconnected
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetReconnected static
Sent when connection to VR HMD is restored.
Definition at line 453 of file CoreDelegates.h.
VRHeadsetRemovedFromHead
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetRemovedFromHead static
Sent when the VR HMD detects that it has been taken off by the player.
Definition at line 462 of file CoreDelegates.h.
VRHeadsetTrackingInitializedDelegate
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetTrackingInitializedDelegate static
Sent when the platform finds that needed headset tracking on startup has completed (Most platforms do not need this.)
Definition at line 444 of file CoreDelegates.h.
VRHeadsetTrackingInitializingAndNeedsHMDToBeTrackedDelegate
TMulticastDelegate<void()> FCoreDelegates::VRHeadsetTrackingInitializingAndNeedsHMDToBeTrackedDelegate static
Sent when the platform needs the user to fix headset tracking on startup (Most platforms do not need this.)
Definition at line 441 of file CoreDelegates.h.
The documentation for this class was generated from the following file:
CoreDelegates.h