Unreal Engine 5.6 C++ API: FComponentEditorUtils Class Reference
FComponentEditorUtils Class Reference
#include "ComponentEditorUtils.h"
Static Public Member Functions
static UNREALED_API void AdjustComponentDelta (const USceneComponent *Component, FVector &Drag, FRotator &Rotation)
Potentially transforms the delta to be applied to a component into the appropriate space.
static bool ApplyDefaultValueChange (class USceneComponent *InSceneComponent, const class FProperty *InProperty, const bool &OldDefaultValue, const bool &NewDefaultValue, int32 PropertyOffset)
template<typename T>
static bool ApplyDefaultValueChange (class USceneComponent *InSceneComponent, const class FProperty *InProperty, const T &OldDefaultValue, const T &NewDefaultValue, int32 PropertyOffset)
template<typename T>
static bool ApplyDefaultValueChange (class USceneComponent *InSceneComponent, T &CurrentValue, const T &OldDefaultValue, const T &NewDefaultValue, bool bReregisterComponent=true)
static UNREALED_API bool AttemptApplyMaterialToComponent (USceneComponent *SceneComponent, UMaterialInterface *MaterialToApply, int32 OptionalMaterialSlot=-1)
Attempts to apply a material to a component at the specified slot.
static UNREALED_API void BindComponentSelectionOverride (USceneComponent *SceneComponent, bool bBind)
Ensures that the selection override delegate is properly bound for the supplied component This includes any attached editor-only primitive components (such as billboard visualizers)
static UNREALED_API bool CanCopyComponent (const UActorComponent *ComponentToCopy)
Checks whether it is valid to copy the given component.
static UNREALED_API bool CanCopyComponents (const TArray< UActorComponent * > &ComponentsToCopy)
Checks whether it is valid to copy the indicated components.
static UNREALED_API bool CanDeleteComponent (const UActorComponent *ComponentToDelete)
Determines whether the indicated component can be deleted.
static UNREALED_API bool CanDeleteComponents (const TArray< UActorComponent * > &ComponentsToDelete)
Determines whether the indicated components can be deleted.
static UNREALED_API bool CanEditComponentInstance (const UActorComponent *ActorComp, const UActorComponent *ParentSceneComp, bool bAllowUserContructionScript)
Is the instance component is editable.
static UNREALED_API bool CanPasteComponents (const USceneComponent *RootComponent, bool bOverrideCanAttach=false, bool bPasteAsArchetypes=false, const FString *SourceData=nullptr)
Determines whether the current contents of the clipboard contain paste-able component information.
static UNREALED_API void CopyComponents (const TArray< UActorComponent * > &ComponentsToCopy, FString *DestinationData=nullptr)
Copies the selected components to the clipboard.
static UNREALED_API int32 DeleteComponents (const TArray< UActorComponent * > &ComponentsToDelete, UActorComponent *&OutComponentToSelect)
Deletes the indicated components and identifies the component that should be selected following the operation.
static UNREALED_API UActorComponent * DuplicateComponent (UActorComponent *TemplateComponent)
Duplicates a component instance and takes care of attachment and registration.
static UNREALED_API void FillComponentContextMenuOptions (UToolMenu *Menu, const TArray< UActorComponent * > &SelectedComponents)
Populates the given menu with basic options for operations on components in the world.
static UNREALED_API UActorComponent * FindMatchingComponent (const UActorComponent *ComponentInstance, const TInlineComponentArray< UActorComponent * > &ComponentList)
Tries to find a match for ComponentInstance in the ComponentList.
static UNREALED_API FName FindVariableNameGivenComponentInstance (const UActorComponent *ComponentInstance)
static UNREALED_API FString GenerateValidVariableName (TSubclassOf< UActorComponent > InComponentClass, AActor *ComponentOwner)
Generate a valid variable name string for the given component instance.
static UNREALED_API FString GenerateValidVariableNameFromAsset (UObject *Asset, AActor *ComponentOwner)
Generate a valid variable name string for the given component instance based on the name of the asset referenced by the component.
static UNREALED_API void GetComponentsFromClipboard (TMap< FName, FName > &OutParentMap, TMap< FName, UActorComponent * > &OutNewObjectMap, bool bGetComponentsAsArchetypes)
Gets the copied components from the clipboard without attempting to paste/apply them in any way.
static UNREALED_API FProperty * GetPropertyForEditableNativeComponent (const UActorComponent *NativeComponent)
Test if the native component is editable.
static UNREALED_API bool IsComponentNameAvailable (const FString &InString, UObject *ComponentOwner, const UActorComponent *ComponentToIgnore=nullptr)
Test whether or not the given string is already the name string of a component on the the owner Optionally excludes an existing component from the check (ex.
static UNREALED_API bool IsValidVariableNameString (const UActorComponent *InComponent, const FString &InString)
Test whether or not the given string is a valid variable name string for the given component instance.
static UNREALED_API FComponentReference MakeComponentReference (const AActor *ExpectedComponentOwner, const UActorComponent *Component)
Make a FComponentReference from a component pointer.
static UNREALED_API void PasteComponents (TArray< UActorComponent * > &OutPastedComponents, AActor *TargetActor, USceneComponent *TargetComponent=nullptr, const FString *SourceData=nullptr)
Attempts to paste components from the clipboard as siblings of the target component.
template<typename T>
static void PropagateDefaultValueChange (class USceneComponent *InSceneComponentTemplate, const class FProperty *InProperty, const T &OldDefaultValue, const T &NewDefaultValue, TSet< class USceneComponent * > &UpdatedInstances, int32 PropertyOffset=INDEX_NONE)
Static Private Member Functions
static UNREALED_API USceneComponent * FindClosestParentInList (UActorComponent *ChildComponent, const TArray< UActorComponent * > &ComponentList)
static UNREALED_API void OnEditBlueprintComponent (UObject *Blueprint)
static UNREALED_API void OnGoToComponentAssetInBrowser (UObject *Asset)
static UNREALED_API void OnOpenComponentCodeFile (const FString CodeFileName)
Detailed Description
Definition at line 15 of file ComponentEditorUtils.h.
Member Function Documentation
AdjustComponentDelta()
UNREALED_API void FComponentEditorUtils::AdjustComponentDelta (const USceneComponent * Component, FVector & Drag, FRotator & Rotation) static
Potentially transforms the delta to be applied to a component into the appropriate space.
References Component, FVector, and Rotation.
ApplyDefaultValueChange() [1/3]
bool FComponentEditorUtils::ApplyDefaultValueChange (class USceneComponent * InSceneComponent, const class FProperty * InProperty, const bool & OldDefaultValue, const bool & NewDefaultValue, int32 PropertyOffset) inline static
Definition at line 191 of file ComponentEditorUtils.h.
References ApplyDefaultValueChange(), BoolProperty, CastField(), check, FProperty::ContainerPtrToValuePtr(), INDEX_NONE, and UActorComponent::ReregisterComponent().
ApplyDefaultValueChange() [2/3]
template<typename T> bool FComponentEditorUtils::ApplyDefaultValueChange (class USceneComponent * InSceneComponent, const class FProperty * InProperty, const T & OldDefaultValue, const T & NewDefaultValue, int32 PropertyOffset) inline static
Definition at line 177 of file ComponentEditorUtils.h.
References ApplyDefaultValueChange(), CastField(), check, FProperty::ContainerPtrToValuePtr(), ensureMsgf, INDEX_NONE, and TEXT.
Referenced by ApplyDefaultValueChange(), ApplyDefaultValueChange(), and PropagateDefaultValueChange().
ApplyDefaultValueChange() [3/3]
template<typename T> bool FComponentEditorUtils::ApplyDefaultValueChange (class USceneComponent * InSceneComponent, T & CurrentValue, const T & OldDefaultValue, const T & NewDefaultValue, bool bReregisterComponent = true) inline static
Definition at line 218 of file ComponentEditorUtils.h.
References UActorComponent::AllowReregistration(), check, UActorComponent::GetOwner(), UActorComponent::IsCreatedByConstructionScript(), UActorComponent::IsRegistered(), UActorComponent::Modify(), Owner, UActorComponent::ReregisterComponent(), RF_Transactional, UObjectBaseUtility::SetFlags(), and USceneComponent::UpdateComponentToWorld().
AttemptApplyMaterialToComponent()
UNREALED_API bool FComponentEditorUtils::AttemptApplyMaterialToComponent (USceneComponent * SceneComponent, UMaterialInterface * MaterialToApply, int32 OptionalMaterialSlot = -1) static
Attempts to apply a material to a component at the specified slot.
Parameters
SceneComponent The component to which we should attempt to apply the material
MaterialToApply The material to apply to the component
OptionalMaterialSlot The material slot on the component to which the material should be applied. -1 to apply to all slots on the component.
Returns
True if the material was successfully applied to the component.
BindComponentSelectionOverride()
UNREALED_API void FComponentEditorUtils::BindComponentSelectionOverride (USceneComponent * SceneComponent, bool bBind) static
Ensures that the selection override delegate is properly bound for the supplied component This includes any attached editor-only primitive components (such as billboard visualizers)
Parameters
SceneComponent The component to set the selection override for
bBind Whether the override should be bound
CanCopyComponent()
UNREALED_API bool FComponentEditorUtils::CanCopyComponent (const UActorComponent * ComponentToCopy) static
Checks whether it is valid to copy the given component.
Parameters
ComponentToCopy The component to check
Returns
Whether the given component can be copied
CanCopyComponents()
UNREALED_API bool FComponentEditorUtils::CanCopyComponents (const TArray< UActorComponent * > & ComponentsToCopy) static
Checks whether it is valid to copy the indicated components.
Parameters
ComponentsToCopy The list of components to check
Returns
Whether the indicated components can be copied
CanDeleteComponent()
UNREALED_API bool FComponentEditorUtils::CanDeleteComponent (const UActorComponent * ComponentToDelete) static
Determines whether the indicated component can be deleted.
Parameters
ComponentToDelete The component to determine can be deleted
Returns
Whether the indicated component can be deleted
CanDeleteComponents()
UNREALED_API bool FComponentEditorUtils::CanDeleteComponents (const TArray< UActorComponent * > & ComponentsToDelete) static
Determines whether the indicated components can be deleted.
Parameters
ComponentsToDelete The list of components to determine can be deleted
Returns
Whether the indicated components can be deleted
CanEditComponentInstance()
UNREALED_API bool FComponentEditorUtils::CanEditComponentInstance (const UActorComponent * ActorComp, const UActorComponent * ParentSceneComp, bool bAllowUserContructionScript) static
Is the instance component is editable.
CanPasteComponents()
UNREALED_API bool FComponentEditorUtils::CanPasteComponents (const USceneComponent * RootComponent, bool bOverrideCanAttach = false, bool bPasteAsArchetypes = false, const FString * SourceData = nullptr) static
Determines whether the current contents of the clipboard contain paste-able component information.
Parameters
RootComponent The root component of the actor being pasted on
bOverrideCanAttach Optional override declaring that components can be attached and a check is not needed
SourceData Component data to paste, or null to use the clipboard
Returns
Whether components can be pasted
CopyComponents()
UNREALED_API void FComponentEditorUtils::CopyComponents (const TArray< UActorComponent * > & ComponentsToCopy, FString * DestinationData = nullptr) static
Copies the selected components to the clipboard.
Parameters
ComponentsToCopy The list of components to copy
DestinationData Buffer to fill with the copied data, or null to use the clipboard
DeleteComponents()
UNREALED_API int32 FComponentEditorUtils::DeleteComponents (const TArray< UActorComponent * > & ComponentsToDelete, UActorComponent *& OutComponentToSelect) static
Deletes the indicated components and identifies the component that should be selected following the operation.
Note: Does not take care of the actual selection of a new component. It only identifies which component should be selected.
Parameters
ComponentsToDelete The list of components to delete
OutComponentToSelect The component that should be selected after the deletion
Returns
The number of components that were actually deleted
DuplicateComponent()
UNREALED_API UActorComponent * FComponentEditorUtils::DuplicateComponent (UActorComponent * TemplateComponent) static
Duplicates a component instance and takes care of attachment and registration.
Parameters
TemplateComponent The component to duplicate
Returns
The created clone of the provided TemplateComponent. nullptr if the duplication failed.
FillComponentContextMenuOptions()
UNREALED_API void FComponentEditorUtils::FillComponentContextMenuOptions (UToolMenu * Menu, const TArray< UActorComponent * > & SelectedComponents) static
Populates the given menu with basic options for operations on components in the world.
Parameters
Menu Used to register the menu options
SelectedComponents The selected components to create menu options for
References Menu.
FindClosestParentInList()
UNREALED_API USceneComponent * FComponentEditorUtils::FindClosestParentInList (UActorComponent * ChildComponent, const TArray< UActorComponent * > & ComponentList) static private
FindMatchingComponent()
UNREALED_API UActorComponent * FComponentEditorUtils::FindMatchingComponent (const UActorComponent * ComponentInstance, const TInlineComponentArray< UActorComponent * > & ComponentList) static
Tries to find a match for ComponentInstance in the ComponentList.
First by name and then if multiple Components have a matching name try to match the SceneComponent hierarchy to find the best match.
Parameters
ComponentInstance Component we are trying to match in the ComponentList
ComponentList List containing possible matches
Returns
Valid Component pointer if match was found. nullptr otherwise.
FindVariableNameGivenComponentInstance()
UNREALED_API FName FComponentEditorUtils::FindVariableNameGivenComponentInstance (const UActorComponent * ComponentInstance) static
GenerateValidVariableName()
UNREALED_API FString FComponentEditorUtils::GenerateValidVariableName (TSubclassOf< UActorComponent > InComponentClass, AActor * ComponentOwner) static
Generate a valid variable name string for the given component instance.
GenerateValidVariableNameFromAsset()
UNREALED_API FString FComponentEditorUtils::GenerateValidVariableNameFromAsset (UObject * Asset, AActor * ComponentOwner) static
Generate a valid variable name string for the given component instance based on the name of the asset referenced by the component.
References Asset.
GetComponentsFromClipboard()
UNREALED_API void FComponentEditorUtils::GetComponentsFromClipboard (TMap< FName, FName > & OutParentMap, TMap< FName, UActorComponent * > & OutNewObjectMap, bool bGetComponentsAsArchetypes) static
Gets the copied components from the clipboard without attempting to paste/apply them in any way.
Parameters
OutParentMap Contains the child->parent name relationships of the copied components
OutNewObjectMap Contains the name->instance object mapping of the copied components
GetPropertyForEditableNativeComponent()
UNREALED_API FProperty * FComponentEditorUtils::GetPropertyForEditableNativeComponent (const UActorComponent * NativeComponent) static
Test if the native component is editable.
If it is, return a valid pointer to it's FProperty Otherwise, return nullptr. A native component is editable if it is marked as EditAnywhere via meta data tags or is within an editable property container
IsComponentNameAvailable()
UNREALED_API bool FComponentEditorUtils::IsComponentNameAvailable (const FString & InString, UObject * ComponentOwner, const UActorComponent * ComponentToIgnore = nullptr) static
Test whether or not the given string is already the name string of a component on the the owner Optionally excludes an existing component from the check (ex.
a component currently being renamed)
Returns
True if the InString is an available name for a component of ComponentOwner
IsValidVariableNameString()
UNREALED_API bool FComponentEditorUtils::IsValidVariableNameString (const UActorComponent * InComponent, const FString & InString) static
Test whether or not the given string is a valid variable name string for the given component instance.
MakeComponentReference()
UNREALED_API FComponentReference FComponentEditorUtils::MakeComponentReference (const AActor * ExpectedComponentOwner, const UActorComponent * Component) static
Make a FComponentReference from a component pointer.
Parameters
ExpectedComponentOwner The expected component owner. Should be the same as OwningActor from FComponentReference::GetComponent().
Component The component we would like to initialize the FComponentReference with.
References Component.
OnEditBlueprintComponent()
UNREALED_API void FComponentEditorUtils::OnEditBlueprintComponent (UObject * Blueprint) static private
OnGoToComponentAssetInBrowser()
UNREALED_API void FComponentEditorUtils::OnGoToComponentAssetInBrowser (UObject * Asset) static private
References Asset.
OnOpenComponentCodeFile()
UNREALED_API void FComponentEditorUtils::OnOpenComponentCodeFile (const FString CodeFileName) static private
PasteComponents()
UNREALED_API void FComponentEditorUtils::PasteComponents (TArray< UActorComponent * > & OutPastedComponents, AActor * TargetActor, USceneComponent * TargetComponent = nullptr, const FString * SourceData = nullptr) static
Attempts to paste components from the clipboard as siblings of the target component.
Parameters
OutPastedComponents List of all the components that were pasted
TargetActor The actor to attach the pasted components to
TargetComponent The component the paste is targeting (will attempt to paste components as siblings). If null, will attach pasted components to the root.
SourceData Component data to paste, or null to use the clipboard
PropagateDefaultValueChange()
template<typename T> void FComponentEditorUtils::PropagateDefaultValueChange (class USceneComponent * InSceneComponentTemplate, const class FProperty * InProperty, const T & OldDefaultValue, const T & NewDefaultValue, TSet< class USceneComponent * > & UpdatedInstances, int32 PropertyOffset = INDEX_NONE) inline static
Definition at line 146 of file ComponentEditorUtils.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), ApplyDefaultValueChange(), TSet< InElementType, KeyFuncs, Allocator >::Contains(), FindObjectWithOuter(), UObject::GetArchetypeInstances(), UObjectBase::GetClass(), UObjectBase::GetFName(), UObjectBase::GetOuter(), UObjectBaseUtility::HasAnyFlags(), INDEX_NONE, TArray< InElementType, InAllocatorType >::Num(), Outer, and RF_ArchetypeObject.
The documentation for this class was generated from the following file:
ComponentEditorUtils.h