Unreal Engine 5.6 C++ Documentation: INavMovementInterface Class Reference
INavMovementInterface Class Reference abstract
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/NavMovementInterface.h>
Public Member Functions
virtual bool CanStartPathFollowing () const =0
Returns true if path following can start.
virtual bool CanStopPathFollowing () const =0
check if current move target can be reached right now if positions are matching (e.g.
virtual FNavMovementProperties * GetNavMovementProperties ()=0
Returns the Nav movement properties struct used by NavMovementInterface and PathFollowing.
virtual const FNavMovementProperties & GetNavMovementProperties () const =0
Returns the Nav movement properties struct (const) used by NavMovementInterface and PathFollowing.
virtual FNavAgentProperties & GetNavAgentPropertiesRef ()=0
Returns the NavAgentProperties used by NavMovementInterface and PathFollowing.
virtual const FNavAgentProperties & GetNavAgentPropertiesRef () const =0
Returns the NavAgentProperties(const) used by NavMovementInterface and PathFollowing.
virtual void SetPathFollowingAgent (IPathFollowingAgentInterface *InPathFollowingAgent)=0
Set the path following agent this interface uses.
virtual IPathFollowingAgentInterface * GetPathFollowingAgent ()=0
Get path following agent this interface uses.
virtual const IPathFollowingAgentInterface * GetPathFollowingAgent () const =0
Get path following agent this interface uses(const)
virtual void RequestDirectMove (const FVector &MoveVelocity, bool bForceMaxSpeed)=0
path following: request movement through a velocity directly
virtual void RequestPathMove (const FVector &MoveInput)=0
path following: request movement through a new move input (normal vector = full strength)
virtual void StopMovementImmediately ()=0
Stops movement by setting velocity to zero - Note: depending on the movement system this may take effect next tick.
virtual void ResetMoveState ()=0
Resets runtime movement state to default movement capabilities.
virtual FVector GetLocation () const =0
Returns location of controlled agent - meaning center of collision shape.
virtual FVector GetFeetLocation () const =0
Returns location of controlled agent's "feet" meaning center of bottom of collision shape.
virtual FBasedPosition GetFeetLocationBased () const =0
Returns based location of controlled agent.
virtual UObject * GetOwnerAsObject () const =0
Get the owner of the object consuming nav movement.
virtual TObjectPtr< UObject > GetUpdatedObject () const =0
Get the Object this movement interface is updating.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const =0
Get axis-aligned cylinder around this agent, used for simple collision checks in nav movement.
virtual FVector GetSimpleCollisionCylinderExtent () const =0
Returns collision extents vector for this object.
virtual FVector GetForwardVector () const =0
Get forward vector of the object being driven by nav movement.
virtual void UpdateNavAgent (const UObject &ObjectToUpdateFrom)=0
Set nav agent properties from an object.
virtual FVector GetVelocityForNavMovement () const =0
Get the current velocity of the agent for nav movement.
virtual float GetMaxSpeedForNavMovement () const =0
Get maximum movement speed of the agent.
virtual bool IsCrouching () const =0
Returns true if currently crouching.
virtual bool IsFalling () const =0
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
virtual bool IsMovingOnGround () const =0
Returns true if currently moving on the ground (e.g.
virtual bool IsSwimming () const =0
Returns true if currently swimming (moving through a fluid volume)
virtual bool IsFlying () const =0
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
virtual UE_API void StopActiveMovement ()
Stops applying further movement (usually zeros acceleration).
virtual UE_API void StopMovementKeepPathing ()
Stops movement immediately (reset velocity) but keeps following current path.
UE_API FVector GetNavLocation () const
Returns navigation location of controlled agent.
virtual UE_API float GetPathFollowingBrakingDistance (float MaxSpeed) const
Returns braking distance for acceleration driven path following.
UE_API void SetFixedBrakingDistance (float DistanceToEndOfPath)
Set fixed braking distance.
UE_API bool UseAccelerationForPathFollowing () const
Returns true if acceleration should be used for path following.
virtual bool CanEverCrouch () const
Returns true if agent can crouch.
virtual bool CanEverJump () const
Returns true if agent can jump.
virtual bool CanEverMoveOnGround () const
Returns true if agent can move along the ground (walk, drive, etc)
virtual bool CanEverSwim () const
Returns true if agent can swim.
virtual bool CanEverFly () const
Returns true if agent can fly.
Detailed Description
Definition at line 25 of file NavMovementInterface.h.
Member Function Documentation
CanEverCrouch()
virtual bool INavMovementInterface::CanEverCrouch () const inline virtual
Returns true if agent can crouch.
Definition at line 149 of file NavMovementInterface.h.
References CanEverCrouch(), and GetNavAgentPropertiesRef().
CanEverFly()
virtual bool INavMovementInterface::CanEverFly () const inline virtual
Returns true if agent can fly.
Definition at line 161 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverJump()
virtual bool INavMovementInterface::CanEverJump () const inline virtual
Returns true if agent can jump.
Definition at line 152 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverMoveOnGround()
virtual bool INavMovementInterface::CanEverMoveOnGround () const inline virtual
Returns true if agent can move along the ground (walk, drive, etc)
Definition at line 155 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverSwim()
virtual bool INavMovementInterface::CanEverSwim () const inline virtual
Returns true if agent can swim.
Definition at line 158 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanStartPathFollowing()
virtual bool INavMovementInterface::CanStartPathFollowing () const pure virtual
Returns true if path following can start.
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
CanStopPathFollowing()
virtual bool INavMovementInterface::CanStopPathFollowing () const pure virtual
check if current move target can be reached right now if positions are matching (e.g.
performing scripted move and can't stop)
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
GetFeetLocation()
virtual FVector INavMovementInterface::GetFeetLocation () const pure virtual
Returns location of controlled agent's "feet" meaning center of bottom of collision shape.
Implemented in UNavMovementComponent.
References GetFeetLocation().
GetFeetLocationBased()
virtual FBasedPosition INavMovementInterface::GetFeetLocationBased () const pure virtual
Returns based location of controlled agent.
Implemented in UNavMovementComponent.
References GetFeetLocationBased().
GetForwardVector()
virtual FVector INavMovementInterface::GetForwardVector () const pure virtual
Get forward vector of the object being driven by nav movement.
Implemented in UNavMovementComponent.
References GetForwardVector().
GetLocation()
virtual FVector INavMovementInterface::GetLocation () const pure virtual
Returns location of controlled agent - meaning center of collision shape.
Implemented in UNavMovementComponent.
References GetLocation().
GetMaxSpeedForNavMovement()
virtual float INavMovementInterface::GetMaxSpeedForNavMovement () const pure virtual
Get maximum movement speed of the agent.
Implemented in UNavMovementComponent.
References GetMaxSpeedForNavMovement().
GetNavAgentPropertiesRef() [1/2]
virtual const FNavAgentProperties & INavMovementInterface::GetNavAgentPropertiesRef () const pure virtual
Returns the NavAgentProperties(const) used by NavMovementInterface and PathFollowing.
Implemented in UNavMovementComponent.
GetNavAgentPropertiesRef() [2/2]
virtual FNavAgentProperties & INavMovementInterface::GetNavAgentPropertiesRef () pure virtual
Returns the NavAgentProperties used by NavMovementInterface and PathFollowing.
Implemented in UNavMovementComponent.
GetNavLocation()
UE_API FVector INavMovementInterface::GetNavLocation () const
Returns navigation location of controlled agent.
References GetNavLocation(), and UE_API.
GetNavMovementProperties() [1/2]
virtual const FNavMovementProperties & INavMovementInterface::GetNavMovementProperties () const pure virtual
Returns the Nav movement properties struct (const) used by NavMovementInterface and PathFollowing.
Implemented in UNavMovementComponent.
GetNavMovementProperties() [2/2]
virtual FNavMovementProperties * INavMovementInterface::GetNavMovementProperties () pure virtual
Returns the Nav movement properties struct used by NavMovementInterface and PathFollowing.
Implemented in UNavMovementComponent.
GetOwnerAsObject()
virtual UObject * INavMovementInterface::GetOwnerAsObject () const pure virtual
Get the owner of the object consuming nav movement.
Implemented in UNavMovementComponent.
References GetOwnerAsObject().
GetPathFollowingAgent() [1/2]
virtual const IPathFollowingAgentInterface * INavMovementInterface::GetPathFollowingAgent () const pure virtual
Get path following agent this interface uses(const)
Implemented in UNavMovementComponent.
GetPathFollowingAgent() [2/2]
virtual IPathFollowingAgentInterface * INavMovementInterface::GetPathFollowingAgent () pure virtual
Get path following agent this interface uses.
Implemented in UNavMovementComponent.
GetPathFollowingBrakingDistance()
virtual UE_API float INavMovementInterface::GetPathFollowingBrakingDistance (float MaxSpeed) const virtual
Returns braking distance for acceleration driven path following.
Reimplemented in UCharacterMovementComponent.
References GetPathFollowingBrakingDistance(), and UE_API.
GetSimpleCollisionCylinder()
virtual void INavMovementInterface::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const pure virtual
Get axis-aligned cylinder around this agent, used for simple collision checks in nav movement.
Implemented in UNavMovementComponent.
References GetSimpleCollisionCylinder().
GetSimpleCollisionCylinderExtent()
virtual FVector INavMovementInterface::GetSimpleCollisionCylinderExtent () const pure virtual
Returns collision extents vector for this object.
Implemented in UNavMovementComponent.
References GetSimpleCollisionCylinderExtent().
GetUpdatedObject()
virtual TObjectPtr< UObject > INavMovementInterface::GetUpdatedObject () const pure virtual
Get the Object this movement interface is updating.
Implemented in UNavMovementComponent.
References GetUpdatedObject().
GetVelocityForNavMovement()
virtual FVector INavMovementInterface::GetVelocityForNavMovement () const pure virtual
Get the current velocity of the agent for nav movement.
Implemented in UNavMovementComponent.
References GetVelocityForNavMovement().
IsCrouching()
virtual bool INavMovementInterface::IsCrouching () const pure virtual
Returns true if currently crouching.
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References IsCrouching().
IsFalling()
virtual bool INavMovementInterface::IsFalling () const pure virtual
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References IsFalling().
IsFlying()
virtual bool INavMovementInterface::IsFlying () const pure virtual
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References IsFlying().
IsMovingOnGround()
virtual bool INavMovementInterface::IsMovingOnGround () const pure virtual
Returns true if currently moving on the ground (e.g.
walking or driving)
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References IsMovingOnGround().
IsSwimming()
virtual bool INavMovementInterface::IsSwimming () const pure virtual
Returns true if currently swimming (moving through a fluid volume)
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References IsSwimming().
RequestDirectMove()
virtual void INavMovementInterface::RequestDirectMove (const FVector & MoveVelocity, bool bForceMaxSpeed) pure virtual
path following: request movement through a velocity directly
Implemented in UCharacterMovementComponent, and UNavMovementComponent.
References RequestDirectMove().
RequestPathMove()
virtual void INavMovementInterface::RequestPathMove (const FVector & MoveInput) pure virtual
path following: request movement through a new move input (normal vector = full strength)
Implemented in UCharacterMovementComponent, UNavMovementComponent, and UPawnMovementComponent.
References RequestPathMove().
ResetMoveState()
virtual void INavMovementInterface::ResetMoveState () pure virtual
Resets runtime movement state to default movement capabilities.
Implemented in UNavMovementComponent.
References ResetMoveState().
SetFixedBrakingDistance()
UE_API void INavMovementInterface::SetFixedBrakingDistance (float DistanceToEndOfPath)
Set fixed braking distance.
References SetFixedBrakingDistance(), and UE_API.
SetPathFollowingAgent()
virtual void INavMovementInterface::SetPathFollowingAgent (IPathFollowingAgentInterface * InPathFollowingAgent) pure virtual
Set the path following agent this interface uses.
Must implement IPathFollowingAgentInterface.
Implemented in UNavMovementComponent.
StopActiveMovement()
virtual UE_API void INavMovementInterface::StopActiveMovement () virtual
Stops applying further movement (usually zeros acceleration).
Reimplemented in UCharacterMovementComponent.
References StopActiveMovement(), and UE_API.
StopMovementImmediately()
virtual void INavMovementInterface::StopMovementImmediately () pure virtual
Stops movement by setting velocity to zero - Note: depending on the movement system this may take effect next tick.
Implemented in UNavMovementComponent.
References StopMovementImmediately().
StopMovementKeepPathing()
virtual UE_API void INavMovementInterface::StopMovementKeepPathing () virtual
Stops movement immediately (reset velocity) but keeps following current path.
References StopMovementKeepPathing(), and UE_API.
UpdateNavAgent()
virtual void INavMovementInterface::UpdateNavAgent (const UObject & ObjectToUpdateFrom) pure virtual
Set nav agent properties from an object.
Implemented in UNavMovementComponent.
References UpdateNavAgent().
UseAccelerationForPathFollowing()
UE_API bool INavMovementInterface::UseAccelerationForPathFollowing () const
Returns true if acceleration should be used for path following.
References UE_API, and UseAccelerationForPathFollowing().
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/NavMovementInterface.h