Unreal Engine 5.6 C++ API: FSkeletalMeshRestoreState Struct Reference
FSkeletalMeshRestoreState Struct Reference
#include "SkeletalMeshRestoreState.h"
Public Member Functions
void RestoreLOD ()
void RestoreState ()
void SaveState (USkeletalMeshComponent *InComponent)
UE_DEPRECATED (5.6, "InComponent is not required") void RestoreLOD(USkeletalMeshComponent *InComponent)
UE_DEPRECATED (5.6, "InComponent is not required") void RestoreState(USkeletalMeshComponent *InComponent)
Data Fields
TArray< FSkeletalMeshEditorParams > SkeletalMeshCompEditorParams
Detailed Description
Definition at line 58 of file SkeletalMeshRestoreState.h.
Member Function Documentation
RestoreLOD()
void FSkeletalMeshRestoreState::RestoreLOD () inline
Definition at line 98 of file SkeletalMeshRestoreState.h.
References SkeletalMeshCompEditorParams.
Referenced by UE_DEPRECATED().
RestoreState()
void FSkeletalMeshRestoreState::RestoreState () inline
Definition at line 91 of file SkeletalMeshRestoreState.h.
References SkeletalMeshCompEditorParams.
Referenced by UE_DEPRECATED().
SaveState()
void FSkeletalMeshRestoreState::SaveState (USkeletalMeshComponent * InComponent) inline
Definition at line 60 of file SkeletalMeshRestoreState.h.
References Cast(), Params, Parent, and SkeletalMeshCompEditorParams.
UE_DEPRECATED() [1/2]
FSkeletalMeshRestoreState::UE_DEPRECATED (5. 6, "InComponent is not required") inline
Definition at line 85 of file SkeletalMeshRestoreState.h.
References RestoreLOD().
UE_DEPRECATED() [2/2]
FSkeletalMeshRestoreState::UE_DEPRECATED (5. 6, "InComponent is not required") inline
Definition at line 80 of file SkeletalMeshRestoreState.h.
References RestoreState().
Field Documentation
SkeletalMeshCompEditorParams
TArray<FSkeletalMeshEditorParams> FSkeletalMeshRestoreState::SkeletalMeshCompEditorParams
Definition at line 105 of file SkeletalMeshRestoreState.h.
Referenced by RestoreLOD(), RestoreState(), and SaveState().
The documentation for this struct was generated from the following file:
SkeletalMeshRestoreState.h