Unreal Engine 5.6 C++ API: FFormatContainer Class Reference
FFormatContainer Class Reference
#include "BulkData.h"
Public Member Functions
~FFormatContainer ()
bool Contains (FName Format) const
void DeepCopy (const FFormatContainer &Other)
void FlushData ()
void GetContainedFormats (TArray< FName > &OutFormats) const
FByteBulkData & GetFormat (FName Format)
void Serialize (FArchive &Ar, UObject *Owner, const TArray< FName > *FormatsToSave=nullptr, bool bSingleUse=true, uint16 InAlignment=DEFAULT_ALIGNMENT, bool bInline=true, bool bMapped=false)
void SerializeAttemptMappedLoad (FArchive &Ar, UObject *Owner)
Private Attributes
TSortedMap< FName, FByteBulkData *, FDefaultAllocator, FNameFastLess > Formats
Friends
class UBodySetup
Detailed Description
Definition at line 1137 of file BulkData.h.
Constructor & Destructor Documentation
~FFormatContainer()
FFormatContainer::~FFormatContainer () inline
Definition at line 1143 of file BulkData.h.
References FlushData().
Member Function Documentation
Contains()
bool FFormatContainer::Contains (FName Format) const inline
Definition at line 1147 of file BulkData.h.
References Format, and Formats.
DeepCopy()
void FFormatContainer::DeepCopy (const FFormatContainer & Other) inline
Definition at line 1175 of file BulkData.h.
References Copy, FlushData(), Format, Formats, and Other.
FlushData()
void FFormatContainer::FlushData () inline
Definition at line 1165 of file BulkData.h.
References BulkData, Format, and Formats.
Referenced by ~FFormatContainer(), and DeepCopy().
GetContainedFormats()
void FFormatContainer::GetContainedFormats (TArray< FName > & OutFormats) const inline
Definition at line 1151 of file BulkData.h.
References Formats.
GetFormat()
FByteBulkData & FFormatContainer::GetFormat (FName Format) inline
Definition at line 1155 of file BulkData.h.
References Format, and Formats.
Serialize()
void FFormatContainer::Serialize (FArchive & Ar, UObject * Owner, const TArray< FName > * FormatsToSave = nullptr, bool bSingleUse = true, uint16 InAlignment = DEFAULT_ALIGNMENT, bool bInline = true, bool bMapped = false)
References Ar, DEFAULT_ALIGNMENT, and Owner.
SerializeAttemptMappedLoad()
void FFormatContainer::SerializeAttemptMappedLoad (FArchive & Ar, UObject * Owner)
References Ar, and Owner.
Friends And Related Symbol Documentation
UBodySetup
friend class UBodySetup friend
Definition at line 1139 of file BulkData.h.
References UBodySetup.
Referenced by UBodySetup.
Field Documentation
Formats
TSortedMap<FName, FByteBulkData*, FDefaultAllocator, FNameFastLess> FFormatContainer::Formats private
Definition at line 1141 of file BulkData.h.
Referenced by Contains(), DeepCopy(), FlushData(), GetContainedFormats(), and GetFormat().
The documentation for this class was generated from the following file:
BulkData.h