Unreal Engine 5.6 C++ Documentation: FNetLevelVisibilityTransactionId Struct Reference
FNetLevelVisibilityTransactionId Struct Reference
This structure is used to to identify NetLevelVisibility transactions between server and client.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/UpdateLevelVisibilityLevelInfo.h>
Public Types
enum : uint32 { InvalidTransactionIndex = 0U , InvalidTransactionId = 0U , IsClientTransactionMask = 0x80000000U , ValueMask = ~IsClientTransactionMask }
Public Member Functions
FNetLevelVisibilityTransactionId ()
bool IsClientTransaction () const
bool IsValid () const
void SetIsClientInstigator (bool bValue)
uint32 GetTransactionIndex () const
void SetTransactionIndex (uint32 TransactionIndex)
uint32 IncrementTransactionIndex ()
bool operator== (const FNetLevelVisibilityTransactionId &Other) const
bool NetSerialize (FArchive &Ar, UPackageMap *PackageMap, bool &bOutSuccess)
Detailed Description
This structure is used to to identify NetLevelVisibility transactions between server and client.
Definition at line 8 of file UpdateLevelVisibilityLevelInfo.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32
Enumerator
InvalidTransactionIndex
InvalidTransactionId
IsClientTransactionMask
ValueMask
Definition at line 13 of file UpdateLevelVisibilityLevelInfo.h.
Constructor & Destructor Documentation
FNetLevelVisibilityTransactionId()
FNetLevelVisibilityTransactionId::FNetLevelVisibilityTransactionId () inline
Definition at line 107 of file UpdateLevelVisibilityLevelInfo.h.
References InvalidTransactionId.
Member Function Documentation
GetTransactionIndex()
uint32 FNetLevelVisibilityTransactionId::GetTransactionIndex () const inline
Definition at line 26 of file UpdateLevelVisibilityLevelInfo.h.
References ValueMask.
IncrementTransactionIndex()
uint32 FNetLevelVisibilityTransactionId::IncrementTransactionIndex () inline
Definition at line 117 of file UpdateLevelVisibilityLevelInfo.h.
References GetTransactionIndex(), InvalidTransactionIndex, SetTransactionIndex(), and ValueMask.
IsClientTransaction()
bool FNetLevelVisibilityTransactionId::IsClientTransaction () const inline
Definition at line 23 of file UpdateLevelVisibilityLevelInfo.h.
References IsClientTransactionMask.
IsValid()
bool FNetLevelVisibilityTransactionId::IsValid () const inline
Definition at line 24 of file UpdateLevelVisibilityLevelInfo.h.
References InvalidTransactionId.
NetSerialize()
bool FNetLevelVisibilityTransactionId::NetSerialize (FArchive & Ar, UPackageMap * PackageMap, bool & bOutSuccess)
References FNetLevelVisibilityTransactionId().
operator==()
bool FNetLevelVisibilityTransactionId::operator== (const FNetLevelVisibilityTransactionId & Other) const inline
Definition at line 30 of file UpdateLevelVisibilityLevelInfo.h.
References FNetLevelVisibilityTransactionId().
SetIsClientInstigator()
void FNetLevelVisibilityTransactionId::SetIsClientInstigator (bool bValue) inline
Definition at line 25 of file UpdateLevelVisibilityLevelInfo.h.
References IsClientTransactionMask.
SetTransactionIndex()
void FNetLevelVisibilityTransactionId::SetTransactionIndex (uint32 TransactionIndex) inline
Definition at line 27 of file UpdateLevelVisibilityLevelInfo.h.
References IsClientTransactionMask, and ValueMask.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/UpdateLevelVisibilityLevelInfo.h