Unreal Engine 5.6 C++ API: ICameraPhotographyModule Class Reference
ICameraPhotographyModule Class Reference abstract
The public interface of the CameraPhotographyModule.
#include "CameraPhotographyModule.h"
Public Member Functions
virtual TSharedPtr< class ICameraPhotography > CreateCameraPhotography ()=0
Attempts to create a new photography interface.
virtual void StartupModule () override
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static ICameraPhotographyModule & Get ()
Singleton-like access to ICameraPhotographyModule.
static FName GetModularFeatureName ()
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Detailed Description
The public interface of the CameraPhotographyModule.
Definition at line 19 of file CameraPhotographyModule.h.
Member Function Documentation
CreateCameraPhotography()
virtual TSharedPtr< class ICameraPhotography > ICameraPhotographyModule::CreateCameraPhotography () pure virtual
Attempts to create a new photography interface.
Returns
Interface to the photography implementation, if we were able to successfully create one
Get()
ICameraPhotographyModule & ICameraPhotographyModule::Get () inline static
Singleton-like access to ICameraPhotographyModule.
Returns
Returns ICameraPhotographyModule singleton instance, loading the module on demand if needed
Definition at line 38 of file CameraPhotographyModule.h.
References GetModularFeatureName(), and FModuleManager::LoadModuleChecked().
GetModularFeatureName()
FName ICameraPhotographyModule::GetModularFeatureName () inline static
Definition at line 22 of file CameraPhotographyModule.h.
References FName, and TEXT.
Referenced by Get(), IsAvailable(), and StartupModule().
IsAvailable()
bool ICameraPhotographyModule::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 48 of file CameraPhotographyModule.h.
References FModuleManager::Get(), GetModularFeatureName(), and FModuleManager::IsModuleLoaded().
StartupModule()
virtual void ICameraPhotographyModule::StartupModule () inline override virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
Definition at line 28 of file CameraPhotographyModule.h.
References IModularFeatures::Get(), GetModularFeatureName(), and IModularFeatures::RegisterModularFeature().
The documentation for this class was generated from the following file:
CameraPhotographyModule.h