Unreal Engine 5.6 C++ API: SplineMeshComponent.h File Reference
SplineMeshComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "Interfaces/Interface_CollisionDataProvider.h"
#include "Components/StaticMeshComponent.h"
#include "SplineMeshShaderParams.h"
#include "SplineMeshComponent.generated.h"
Data Structures
class USplineMeshComponent
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::SplineMesh
Functions
void PackSplineMeshParams (const FSplineMeshShaderParams &Params, const TArrayView< FVector4f > &Output)
float UE::SplineMesh::RealToFloatChecked (const double Value)
UCLASS ()
A Spline Mesh Component is a derivation of a Static Mesh Component which can be deformed using a spline.
UENUM () namespace ESplineMeshAxis
USTRUCT () struct FSplineMeshParams
Structure that holds info about spline, passed to renderer to deform UStaticMesh.
Variables
meta =(BlueprintSpawnableComponent)
Function Documentation
PackSplineMeshParams()
void PackSplineMeshParams (const FSplineMeshShaderParams & Params, const TArrayView< FVector4f > & Output)
References Params.
UCLASS()
UCLASS ()
A Spline Mesh Component is a derivation of a Static Mesh Component which can be deformed using a spline.
Only a start and end position (and tangent) can be specified.
See also
https://docs.unrealengine.com/latest/INT/Resources/ContentExamples/Blueprint_Splines
UENUM()
UENUM ()
Definition at line 22 of file SplineMeshComponent.h.
References BlueprintType, X, Y, and Z.
USTRUCT()
USTRUCT ()
Structure that holds info about spline, passed to renderer to deform UStaticMesh.
Also used by Lightmass, so be sure to update Lightmass::FSplineMeshParams and the static lighting code if this changes!
Start location of spline, in component space.
Start tangent of spline, in component space.
X and Y scale applied to mesh at start of spline.
Roll around spline applied at start, in radians.
Roll around spline applied at end, in radians.
Starting offset of the mesh from the spline, in component space.
End location of spline, in component space.
X and Y scale applied to mesh at end of spline.
End tangent of spline, in component space.
Ending offset of the mesh from the spline, in component space.
How much to scale the calculated culling bounds of Nanite clusters after deformation. NOTE: This should only be set greater than 1.0 if it fixes visible issues with clusters being incorrectly culled.
Definition at line 42 of file SplineMeshComponent.h.
References Category, ForceInit, FVector, GENERATED_USTRUCT_BODY, meta, and UPROPERTY.
Variable Documentation
meta
meta =(BlueprintSpawnableComponent)
Definition at line 117 of file SplineMeshComponent.h.
Referenced by USplineMeshComponent::GENERATED_UCLASS_BODY(), USplineMeshComponent::UFUNCTION(), and USplineMeshComponent::UFUNCTION().