Unreal Engine 5.6 C++ API: FStyleDefaults Class Reference
FStyleDefaults Class Reference
#include "StyleDefaults.h"
Static Public Member Functions
static const FLinearColor & GetColor ()
Get default FLinearColor.
static float GetFloat ()
Return the static default float value.
static const FSlateFontInfo GetFontInfo (uint16 Size=10)
Get default font.
static const FMargin & GetMargin ()
Get default FMargin.
static const FSlateBrush * GetNoBrush ()
static const FSlateColor & GetSlateColor ()
Get default Slate Color.
static const FSlateSound & GetSound ()
Return the static default sound value.
static const UE::Slate::FDeprecateVector2DResult GetVector2D ()
Get default FVector2D value.
Static Private Attributes
static FLinearColor DefaultColor
static float DefaultFloat
static FVector2f DefaultFVector2D
static FMargin DefaultMargin
static FSlateColor DefaultSlateColor
static FSlateSound DefaultSound
Detailed Description
Definition at line 11 of file StyleDefaults.h.
Member Function Documentation
GetColor()
const FLinearColor & FStyleDefaults::GetColor () inline static
Get default FLinearColor.
Returns
- The default FLinearColor.
Definition at line 37 of file StyleDefaults.h.
References DefaultColor.
Referenced by FSlateStyleSet::GetColor(), and ISlateStyle::GetColor().
GetFloat()
float FStyleDefaults::GetFloat () inline static
Return the static default float value.
Returns
- The static default float value.
Definition at line 19 of file StyleDefaults.h.
References DefaultFloat.
Referenced by FSlateStyleSet::GetFloat(), and ISlateStyle::GetFloat().
GetFontInfo()
const FSlateFontInfo FStyleDefaults::GetFontInfo (uint16 Size = 10) static
Get default font.
Returns
- The default font.
References TSequenceHistory< HistorySize >::Size.
GetMargin()
const FMargin & FStyleDefaults::GetMargin () inline static
Get default FMargin.
Returns
- The default FMargin value.
Definition at line 55 of file StyleDefaults.h.
References DefaultMargin.
Referenced by FSlateStyleSet::GetMargin(), and ISlateStyle::GetMargin().
GetNoBrush()
const FSlateBrush * FStyleDefaults::GetNoBrush () static
Returns
- Returns no brush.
Referenced by FAppStyle::GetNoBrush(), FAppStyle::GetOptionalBrush(), FSlateGameResources::GetOptionalBrush(), FSlateStyleSet::GetOptionalBrush(), ISlateStyle::GetOptionalBrush(), SListView< TSharedPtr< FString > >::SetStyle(), STreeView< FRigVMSearchResult >::SetStyle(), and SComboBox< OptionType >::SLATE_ARGUMENT().
GetSlateColor()
const FSlateColor & FStyleDefaults::GetSlateColor () inline static
Get default Slate Color.
Returns
- The default Slate color.
Definition at line 46 of file StyleDefaults.h.
References DefaultSlateColor.
Referenced by FSlateStyleSet::GetSlateColor(), and ISlateStyle::GetSlateColor().
GetSound()
const FSlateSound & FStyleDefaults::GetSound () inline static
Return the static default sound value.
Returns
- The static default sound value.
Definition at line 75 of file StyleDefaults.h.
References DefaultSound.
GetVector2D()
const UE::Slate::FDeprecateVector2DResult FStyleDefaults::GetVector2D () inline static
Get default FVector2D value.
Returns
- The default FVector2D.
Definition at line 28 of file StyleDefaults.h.
References DefaultFVector2D.
Referenced by FSlateStyleSet::GetVector(), and ISlateStyle::GetVector().
Field Documentation
DefaultColor
FLinearColor FStyleDefaults::DefaultColor static private
Definition at line 84 of file StyleDefaults.h.
Referenced by GetColor().
DefaultFloat
float FStyleDefaults::DefaultFloat static private
Definition at line 82 of file StyleDefaults.h.
Referenced by GetFloat().
DefaultFVector2D
FVector2f FStyleDefaults::DefaultFVector2D static private
Definition at line 83 of file StyleDefaults.h.
Referenced by GetVector2D().
DefaultMargin
FMargin FStyleDefaults::DefaultMargin static private
Definition at line 85 of file StyleDefaults.h.
Referenced by GetMargin().
DefaultSlateColor
FSlateColor FStyleDefaults::DefaultSlateColor static private
Definition at line 87 of file StyleDefaults.h.
Referenced by GetSlateColor().
DefaultSound
FSlateSound FStyleDefaults::DefaultSound static private
Definition at line 86 of file StyleDefaults.h.
Referenced by GetSound().
The documentation for this class was generated from the following file:
StyleDefaults.h