Unreal Engine 5.6 C++ API: UE::Tick::FWorldContextId Struct Reference
UE::Tick::FWorldContextId Struct Reference final
Identifies a specific WorldContext that has objects which are allowed to tick and run tasks.
#include "TaskSyncManager.h"
Public Types
typedef int32 FInternalId
Public Member Functions
FWorldContextId ()
Construct an invalid world context id.
FWorldContextId (const UWorld *InWorld)
Construct from a world pointer, if it is null or not part of a tickable world context it will return an invalid id.
FWorldContextId (FInternalId InWorldId)
Construct from an internal id TODO: May make private.
bool IsValid () const
Returns true if this points to a valid tickable world context.
bool operator!= (const FWorldContextId &Other) const
bool operator== (const FWorldContextId &Other) const
Static Public Member Functions
static FWorldContextId GetContextIdForWorld (const UWorld *World)
Construct from a world pointer, if it is null or not part of a tickable world context it will return an invalid id.
Data Fields
FInternalId WorldId
Static Public Attributes
static constexpr FInternalId DefaultWorldContextId = 0
Default id which is used for the default game world outside the editor.
static constexpr FInternalId InvalidWorldContextId = -1
Friends
uint32 GetTypeHash (const FWorldContextId &Context)
Detailed Description
Identifies a specific WorldContext that has objects which are allowed to tick and run tasks.
Definition at line 241 of file TaskSyncManager.h.
Member Typedef Documentation
FInternalId
typedef int32 UE::Tick::FWorldContextId::FInternalId
Definition at line 244 of file TaskSyncManager.h.
Constructor & Destructor Documentation
FWorldContextId() [1/3]
UE::Tick::FWorldContextId::FWorldContextId () inline
Construct an invalid world context id.
Definition at line 255 of file TaskSyncManager.h.
References InvalidWorldContextId, and WorldId.
Referenced by GetContextIdForWorld(), GetTypeHash, operator!=(), and operator==().
FWorldContextId() [2/3]
UE::Tick::FWorldContextId::FWorldContextId (FInternalId InWorldId) inline explicit
Construct from an internal id TODO: May make private.
Definition at line 260 of file TaskSyncManager.h.
References WorldId.
FWorldContextId() [3/3]
UE::Tick::FWorldContextId::FWorldContextId (const UWorld * InWorld) inline
Construct from a world pointer, if it is null or not part of a tickable world context it will return an invalid id.
Definition at line 265 of file TaskSyncManager.h.
References GetContextIdForWorld(), and WorldId.
Member Function Documentation
GetContextIdForWorld()
FWorldContextId UE::Tick::FWorldContextId::GetContextIdForWorld (const UWorld * World) static
Construct from a world pointer, if it is null or not part of a tickable world context it will return an invalid id.
References FWorldContextId().
Referenced by FWorldContextId().
IsValid()
bool UE::Tick::FWorldContextId::IsValid () const inline
Returns true if this points to a valid tickable world context.
Definition at line 271 of file TaskSyncManager.h.
References InvalidWorldContextId, and WorldId.
operator!=()
bool UE::Tick::FWorldContextId::operator!= (const FWorldContextId & Other) const inline
Definition at line 281 of file TaskSyncManager.h.
References FWorldContextId(), and Other.
operator==()
bool UE::Tick::FWorldContextId::operator== (const FWorldContextId & Other) const inline
Definition at line 276 of file TaskSyncManager.h.
References FWorldContextId(), Other, and WorldId.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FWorldContextId & Context) friend
Definition at line 286 of file TaskSyncManager.h.
References FWorldContextId().
Field Documentation
DefaultWorldContextId
FInternalId UE::Tick::FWorldContextId::DefaultWorldContextId = 0 static constexpr
Default id which is used for the default game world outside the editor.
Definition at line 249 of file TaskSyncManager.h.
InvalidWorldContextId
FInternalId UE::Tick::FWorldContextId::InvalidWorldContextId = -1 static constexpr
Definition at line 246 of file TaskSyncManager.h.
Referenced by FWorldContextId(), and IsValid().
WorldId
FInternalId UE::Tick::FWorldContextId::WorldId
Definition at line 291 of file TaskSyncManager.h.
Referenced by FWorldContextId(), FWorldContextId(), FWorldContextId(), IsValid(), and operator==().
The documentation for this struct was generated from the following file:
TaskSyncManager.h