Unreal Engine 5.6 C++ API: MovieSceneToolHelpers Class Reference
MovieSceneToolHelpers Class Reference
#include "MovieSceneToolHelpers.h"
Public Member Functions
UE_DEPRECATED (5.3, "GenerateNewShotName has been deprecated in favor of GenerateNewSubsequenceName that takes a given prefix") static FString GenerateNewShotName(const TArray< UMovieSceneSection * > &AllSections
UE_DEPRECATED (5.3, "GenerateNewShotPath has been deprecated in favor of GenerateNewSubsequencePath that takes a given directory") static FString GenerateNewShotPath(UMovieScene *SequenceMovieScene
UE_DEPRECATED (5.5, "BakeToSkelMeshToCallbacks taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences") static bool BakeToSkelMeshToCallbacks(UMovieScene *MovieScene
UE_DEPRECATED (5.5, "ExportFBX taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences") static bool ExportFBX(UWorld *World
UE_DEPRECATED (5.5, "ExportToAnimSequence taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences") static bool ExportToAnimSequence(UAnimSequence *AnimSequence
Static Public Member Functions
static USkeletalMeshComponent * AcquireSkeletalMeshFromObject (UObject *BoundObject)
static bool AddTransformKeys (const UMovieScene3DTransformSection *InTransformSection, const TArray< FFrameNumber > &Frames, const TArray< FTransform > &InLocalTransforms, const EMovieSceneTransformChannel &InChannels)
Adds transform keys to the section based on the channels filters.
static bool BakeToSkelMeshToCallbacks (const FAnimExportSequenceParameters &AnimExportSequenceParameters, USkeletalMeshComponent *SkelMesh, UAnimSeqExportOption *ExportOptions, FInitAnimationCB InitCallback, FStartAnimationCB StartCallback, FTickAnimationCB TickCallback, FEndAnimationCB EndCallback)
static void CalculateFramesBetween (const UMovieScene *MovieScene, FFrameNumber StartFrame, FFrameNumber EndFrame, int FrameIncrement, TArray< FFrameNumber > &OutFrames)
Returns the frame numbers between start and end.
static bool CanSplitSection (const TSet< UMovieSceneSection * > &Sections, FQualifiedFrameTime Time)
static bool CanTrimSectionLeft (const TSet< UMovieSceneSection * > &Sections, FQualifiedFrameTime Time)
static bool CanTrimSectionRight (const TSet< UMovieSceneSection * > &Sections, FQualifiedFrameTime Time)
static bool CollapseSection (TSharedPtr< ISequencer > &InSequencer, UMovieSceneTrack *InOwnerTrack, TArray< UMovieSceneSection * > InSections, const FBakingAnimationKeySettings &InSettings)
static FString ComposeShotName (const FString &ShotPrefix, uint32 ShotNumber, uint32 TakeNumber, uint32 ShotNumberDigits, uint32 TakeNumberDigits)
Compose a shot name given its components.
static void CopyCameraProperties (fbxsdk::FbxCamera *CameraNode, AActor *InCameraActor)
Import FBX Camera to existing camera's.
static void CreateCameraCutSectionForCamera (UMovieScene *MovieScene, FGuid CameraGuid, FFrameNumber FrameNumber)
Create a new camera cut section for the given camera.
static UMovieSceneSequence * CreateSequence (FString &NewSequenceName, FString &NewSequencePath, UMovieSceneSubSection *SectionToDuplicate=nullptr)
static bool ExportFBX (UWorld *World, const FAnimExportSequenceParameters &AnimExportSequenceParameters, const TArray< FGuid > &Bindings, const TArray< UMovieSceneTrack * > &Tracks, INodeNameAdapter &NodeNameAdapter, FMovieSceneSequenceIDRef &Template, const FString &InFBXFileName)
Export FBX.
static bool ExportFBXFromControlRigChannels (const UMovieSceneSection *Section, const UMovieSceneUserExportFBXControlRigSettings *ExportFBXControlRigSettings, const TArray< FName > &SelectedControlNames, const FMovieSceneSequenceTransform &RootToLocalTransform)
static bool ExportFBXFromControlRigChannelsWithDialog (const TSharedRef< ISequencer > &InSequencer, UMovieSceneTrack *Track)
static bool ExportToAnimSequence (UAnimSequence *AnimSequence, UAnimSeqExportOption *ExportOptions, const FAnimExportSequenceParameters &AnimExportSequenceParameters, USkeletalMeshComponent *SkelMesh)
static int32 FindAvailableRowIndex (UMovieSceneTrack *InTrack, UMovieSceneSection *InSection, const TArray< UMovieSceneSection * > &SectionsToDisregard=TArray< UMovieSceneSection * >())
Get the next available row index for the section so that it doesn't overlap any other sections in time.
static void GatherTakes (const UMovieSceneSection *Section, TArray< FAssetData > &AssetData, uint32 &OutCurrentTakeNumber)
Gather takes - level sequence assets that have the same shot prefix and shot number in the same asset path (directory)
static FString GenerateNewSubsequenceName (const TArray< UMovieSceneSection * > &AllSections, const FString &SubsequencePrefix, FFrameNumber Time)
Generate a new shot name.
static FString GenerateNewSubsequencePath (UMovieScene *SequenceMovieScene, const FString &SubsequenceDirectory, FString &NewShotName)
Generate a new subsequence package.
static void GetActorParents (const FActorForWorldTransforms &Actor, TArray< FActorForWorldTransforms > &OutParentActors)
static void GetActorParentsWithAttachments (ISequencer *Sequencer, const FActorForWorldTransforms &Actor, TArray< FActorForWorldTransforms > &OutParentActors)
static void GetActorsAndParentsKeyFrames (ISequencer *Sequencer, const FActorForWorldTransforms &Actor, const FFrameNumber &StartFrame, const FFrameNumber &EndFrame, TSortedMap< FFrameNumber, FFrameNumber > &OutFrameMap)
static void GetActorWorldTransforms (IMovieScenePlayer *Player, UMovieSceneSequence *InSequence, FMovieSceneSequenceIDRef Template, const FActorForWorldTransforms &Actors, const TArray< FFrameNumber > &Frames, TArray< FTransform > &OutWorldTransforms)
static void GetActorWorldTransforms (ISequencer *Sequencer, const FActorForWorldTransforms &Actors, const TArray< FFrameNumber > &Frames, TArray< FTransform > &OutWorldTransforms)
static FString GetCameraName (fbxsdk::FbxCamera *InCamera)
static void GetCameras (fbxsdk::FbxNode *Parent, TArray< fbxsdk::FbxCamera * > &Cameras)
template<typename ChannelType, typename CurveValueType>
static TArray< CurveValueType > GetChannelValues (const int32 StartIndex, const int32 EndIndex, const TArray< UMovieSceneSection * > &Sections, const TArray< UMovieSceneSection * > &AbsoluteSections, const FFrameNumber &FrameTime)
static const FMovieSceneEvaluationTrack * GetEvaluationTrack (ISequencer *Sequencer, const FGuid &TrackSignature)
static void GetLocationAtTime (const FMovieSceneEvaluationTrack *Track, UObject *Object, FFrameTime KeyTime, FVector &KeyPos, FRotator &KeyRot, const TSharedPtr< ISequencer > &Sequencer)
static void GetParents (TArray< const UObject * > &Parents, const UObject *InObject)
static bool GetParentTM (FTransform &CurrentRefTM, const TSharedPtr< ISequencer > &Sequencer, UObject *ParentObject, FFrameTime KeyTime)
static FTransform GetRefFrameFromParents (const TSharedPtr< ISequencer > &Sequencer, const TArray< const UObject * > &Parents, FFrameTime KeyTime)
static bool GetTakeNumber (const UMovieSceneSection *Section, FAssetData AssetData, uint32 &OutTakeNumber)
Get the take number for the given asset.
static FTransform GetTransformOriginForFocusedSequence (TSharedPtr< ISequencer > InSequencer)
static UMovieScene3DTransformSection * GetTransformSection (const ISequencer *InSequencer, const FGuid &InGuid, const FTransform &InDefaultTransform=FTransform::Identity)
Returns the transform section for that guid.
static bool HasHiddenMobility (const UClass *ObjectClass)
static void ImportAnimSequenceTransforms (const TSharedRef< ISequencer > &Sequencer, const FAssetData &Asset, UMovieScene3DTransformTrack *TransformTrack)
Import an animation sequence's root transforms into a transform section.
static void ImportAnimSequenceTransformsEnterPressed (const TSharedRef< ISequencer > &Sequencer, const TArray< FAssetData > &Asset, UMovieScene3DTransformTrack *TransformTrack)
Import an animation sequence's root transforms into a transform section.
static void ImportFBXCameraToExisting (UnFbx::FFbxImporter *FbxImporter, UMovieSceneSequence *InSequence, IMovieScenePlayer *Player, FMovieSceneSequenceIDRef TemplateID, TMap< FGuid, FString > &InObjectBindingMap, bool bMatchByNameOnly, bool bNotifySlate)
Import FBX Camera to existing camera's.
static bool ImportFBXIfReady (UWorld *World, UMovieSceneSequence *InSequence, IMovieScenePlayer *Player, FMovieSceneSequenceIDRef TemplateID, TMap< FGuid, FString > &ObjectBindingMap, UMovieSceneUserImportFBXSettings *ImportFBXSettings, const FFBXInOutParameters &InFBXParams, ISequencer *Sequencer=nullptr)
Import into an FBX scene that has been readied already, via the ReadyFBXForImport call.
static bool ImportFBXIntoControlRigChannels (UMovieScene *MovieScene, const FString &ImportFilename, UMovieSceneUserImportFBXControlRigSettings *ControlRigSettings, TArray< FRigControlFBXNodeAndChannels > *NodeAndChannels, const TArray< FName > &SelectedControlNames, FFrameRate FrameRate)
static bool ImportFBXIntoControlRigChannelsWithDialog (const TSharedRef< ISequencer > &InSequencer, TArray< FRigControlFBXNodeAndChannels > *NodeAndChannels)
static bool ImportFBXNode (FString NodeName, UnFbx::FFbxCurvesAPI &CurveAPI, UMovieSceneSequence *InSequence, IMovieScenePlayer *Player, FMovieSceneSequenceIDRef TemplateID, FGuid ObjectBinding, ISequencer *Sequencer=nullptr)
Import FBX Node to existing actor/node.
static bool ImportFBXWithDialog (UMovieSceneSequence *InSequence, ISequencer &InSequencer, const TMap< FGuid, FString > &InObjectBindingNameMap, TOptional< bool > bCreateCameras)
Import FBX with dialog.
static bool IsValidAsset (UMovieSceneSequence *Sequence, const FAssetData &InAssetData)
static void LockCameraActorToViewport (const TSharedPtr< ISequencer > &Sequencer, ACameraActor *CameraActor)
Lock the given camera actor to the viewport.
static TSharedRef< SWidget > MakeEnumComboBox (const UEnum *Enum, TAttribute< int32 > CurrentValue, SEnumComboBox::FOnEnumSelectionChanged OnSelectionChanged)
Generate a combobox for editing enum values.
template<typename ChannelType>
static bool MergeChannels (int32 SectionChannelIndex, TArray< ChannelType * > &Channels, const TArray< UMovieSceneSection * > &Sections, const TRange< FFrameNumber > &Range, FChannelMergeAlgorithm MergeAlgorithm, const TArray< UMovieSceneSection * > &TrackSections, const int32 *Increment=nullptr)
template<typename ChannelType>
static bool MergeSections (UMovieSceneSection *BaseSection, TArray< UMovieSceneSection * > &AbsoluteSections, TArray< UMovieSceneSection * > &AdditiveSections, int32 StartIndex, int32 EndIndex, const TRange< FFrameNumber > &Range, const int32 *Increment=nullptr)
template<typename ChannelType>
static bool MergeSections (UMovieSceneSection *BaseSection, UMovieSceneSection *TopSection, int32 StartIndex, int32 EndIndex, const TRange< FFrameNumber > &Range, const TArray< UMovieSceneSection * > &TrackSections, const int32 *Increment=nullptr)
template<typename ChannelType, typename CurveValueType>
static bool MergeValue (CurveValueType &InOutValue, TArray< ChannelType * > &Channels, const FFrameNumber &Frame, int32 SectionChannelIndex, const TArray< UMovieSceneSection * > &Sections, const TArray< UMovieSceneSection * > &AbsoluteSections, const TArray< UMovieSceneSection * > &OtherSections, int32 OverrideChannelIndex, FChannelMergeAlgorithm MergeAlgorithm)
static bool MovieSceneTranslatorExport (FMovieSceneExporter *InExporter, const UMovieScene *InMovieScene, const FMovieSceneCaptureSettings &Settings)
Export movie scene formats.
static bool MovieSceneTranslatorImport (FMovieSceneImporter *InImporter, UMovieScene *InMovieScene, FFrameRate InFrameRate, FString InOpenDirectory=TEXT(""))
Import movie scene formats.
static void MovieSceneTranslatorLogMessages (FMovieSceneTranslator *InTranslator, TSharedRef< FMovieSceneTranslatorContext > InContext, bool bDisplayMessages)
Log messages and display error message window for MovieScene translators.
static void MovieSceneTranslatorLogOutput (FMovieSceneTranslator *InTranslator, TSharedRef< FMovieSceneTranslatorContext > InContext)
Log error output for MovieScene translators.
static bool OptimizeSection (const FKeyDataOptimizationParams &InParams, UMovieSceneSection *InSection)
static bool OverlapsSection (UMovieSceneTrack *InTrack, UMovieSceneSection *InSection, const TArray< UMovieSceneSection * > &SectionsToDisregard=TArray< UMovieSceneSection * >())
Does this section overlap any other track section?
static bool ParseShotName (const FString &ShotName, FString &ShotPrefix, uint32 &ShotNumber, uint32 &TakeNumber, uint32 &ShotNumberDigits, uint32 &TakeNumberDigits)
Parse a shot name into its components.
static bool ReadyFBXForImport (const FString &ImportFilename, UMovieSceneUserImportFBXSettings *ImportFBXSettings, FFBXInOutParameters &OutFBXParams)
Get FBX Ready for Import.
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > &ChannelData, FFrameNumber Time, double Value, const EMovieSceneKeyInterpolation Interpolation=EMovieSceneKeyInterpolation::Auto)
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > &ChannelData, FFrameNumber Time, FMovieSceneDoubleValue Value)
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > &Curve, FFrameNumber Time, double Value, float ArriveTangent, float LeaveTangent, ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode, FFrameRate FrameRate, ERichCurveTangentWeightMode WeightedMode=RCTWM_WeightedNone, float ArriveTangentWeight=0.0f, float LeaveTangentWeight=0.0f)
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > &ChannelData, FFrameNumber Time, float Value, const EMovieSceneKeyInterpolation Interpolation=EMovieSceneKeyInterpolation::Auto)
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > &Curve, FFrameNumber Time, const FMovieSceneFloatValue &Value)
static void SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > &Curve, FFrameNumber Time, float Value, float ArriveTangent, float LeaveTangent, ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode, FFrameRate FrameRate, ERichCurveTangentWeightMode WeightedMode=RCTWM_WeightedNone, float ArriveTangentWeight=0.0f, float LeaveTangentWeight=0.0f)
static bool SetTakeNumber (const UMovieSceneSection *Section, uint32 InTakeNumber)
Set the take number for the given asset.
static bool ShowExportEDLDialog (const UMovieScene *InMovieScene, FFrameRate InFrameRate, FString InSaveDirectory=TEXT(""), int32 InHandleFrames=8, FString InMovieExtension=TEXT(".avi"))
Show Export EDL Dialog.
static bool ShowImportEDLDialog (UMovieScene *InMovieScene, FFrameRate InFrameRate, FString InOpenDirectory=TEXT(""))
Show Import EDL Dialog.
static void SplitSection (const TSet< UMovieSceneSection * > &Sections, FQualifiedFrameTime Time, bool bDeleteKeys)
Splits sections at the given time.
static void SplitSectionsByBlendType (EMovieSceneBlendType BlendType, const TArray< UMovieSceneSection * > &InSections, TArray< UMovieSceneSection * > &OutSections, TArray< UMovieSceneSection * > &OutBlendTypeSections)
static void TrimOrExtendSection (UMovieSceneTrack *Track, TOptional< int32 > RowIndex, FQualifiedFrameTime Time, bool bTrimOrExtendLeft, bool bDeleteKeys)
Trim or extend section at the given time.
static void TrimSection (const TSet< UMovieSceneSection * > &Sections, FQualifiedFrameTime Time, bool bTrimLeft, bool bDeleteKeys)
Trim section at the given time.
Data Fields
UMovieScene IMovieScenePlayer const TArray< FGuid > & Bindings
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB FTickAnimationCB FEndAnimationCB EndCallback
UAnimSeqExportOption * ExportOptions
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption * ExportOptions
UMovieScene IMovieScenePlayer const TArray< FGuid > const TArray< UMovieSceneTrack * > INodeNameAdapter FMovieSceneSequenceIDRef const FString & InFBXFileName
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB InitCallback
UMovieScene * MovieScene
UAnimSeqExportOption UMovieScene * MovieScene
FString & NewShotName
UMovieScene IMovieScenePlayer const TArray< FGuid > const TArray< UMovieSceneTrack * > INodeNameAdapter & NodeNameAdapter
UMovieScene IMovieScenePlayer * Player
UAnimSeqExportOption UMovieScene IMovieScenePlayer * Player
IMovieScenePlayer * Player
UMovieScene IMovieScenePlayer const TArray< FGuid > const TArray< UMovieSceneTrack * > INodeNameAdapter FMovieSceneSequenceIDRef const FString FMovieSceneSequenceTransform & RootToLocalTransform
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform & RootToLocalTransform
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform & RootToLocalTransform
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent * SkelMesh
IMovieScenePlayer USkeletalMeshComponent * SkelMesh
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB StartCallback
UMovieScene IMovieScenePlayer const TArray< FGuid > const TArray< UMovieSceneTrack * > INodeNameAdapter FMovieSceneSequenceIDRef & Template
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef & Template
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef & Template
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB FTickAnimationCB TickCallback
FFrameNumber Time
UMovieScene IMovieScenePlayer const TArray< FGuid > const TArray< UMovieSceneTrack * > & Tracks
Detailed Description
Definition at line 120 of file MovieSceneToolHelpers.h.
Member Function Documentation
AcquireSkeletalMeshFromObject()
USkeletalMeshComponent * MovieSceneToolHelpers::AcquireSkeletalMeshFromObject (UObject * BoundObject) static
References AcquireSkeletalMeshFromObject().
Referenced by AcquireSkeletalMeshFromObject().
AddTransformKeys()
bool MovieSceneToolHelpers::AddTransformKeys (const UMovieScene3DTransformSection * InTransformSection, const TArray< FFrameNumber > & Frames, const TArray< FTransform > & InLocalTransforms, const EMovieSceneTransformChannel & InChannels) static
Adds transform keys to the section based on the channels filters.
BakeToSkelMeshToCallbacks()
bool MovieSceneToolHelpers::BakeToSkelMeshToCallbacks (const FAnimExportSequenceParameters & AnimExportSequenceParameters, USkeletalMeshComponent * SkelMesh, UAnimSeqExportOption * ExportOptions, FInitAnimationCB InitCallback, FStartAnimationCB StartCallback, FTickAnimationCB TickCallback, FEndAnimationCB EndCallback) static
References BakeToSkelMeshToCallbacks(), EndCallback, ExportOptions, InitCallback, SkelMesh, StartCallback, and TickCallback.
Referenced by BakeToSkelMeshToCallbacks().
CalculateFramesBetween()
void MovieSceneToolHelpers::CalculateFramesBetween (const UMovieScene * MovieScene, FFrameNumber StartFrame, FFrameNumber EndFrame, int FrameIncrement, TArray< FFrameNumber > & OutFrames) static
Returns the frame numbers between start and end.
References EndFrame, and MovieScene.
Referenced by MergeChannels().
CanSplitSection()
bool MovieSceneToolHelpers::CanSplitSection (const TSet< UMovieSceneSection * > & Sections, FQualifiedFrameTime Time) static
References Sections, and Time.
CanTrimSectionLeft()
bool MovieSceneToolHelpers::CanTrimSectionLeft (const TSet< UMovieSceneSection * > & Sections, FQualifiedFrameTime Time) static
References Sections, and Time.
CanTrimSectionRight()
bool MovieSceneToolHelpers::CanTrimSectionRight (const TSet< UMovieSceneSection * > & Sections, FQualifiedFrameTime Time) static
References Sections, and Time.
CollapseSection()
bool MovieSceneToolHelpers::CollapseSection (TSharedPtr< ISequencer > & InSequencer, UMovieSceneTrack * InOwnerTrack, TArray< UMovieSceneSection * > InSections, const FBakingAnimationKeySettings & InSettings) static
References CollapseSection().
Referenced by CollapseSection().
ComposeShotName()
FString MovieSceneToolHelpers::ComposeShotName (const FString & ShotPrefix, uint32 ShotNumber, uint32 TakeNumber, uint32 ShotNumberDigits, uint32 TakeNumberDigits) static
Compose a shot name given its components.
Parameters
ShotPrefix The shot prefix to use
ShotNumber The shot number to use
TakeNumber The take number to use
ShotNumberDigits The number of digits to pad for the shot number
TakeNumberDigits The number of digits to pad for the take number
Returns
The composed shot name
CopyCameraProperties()
void MovieSceneToolHelpers::CopyCameraProperties (fbxsdk::FbxCamera * CameraNode, AActor * InCameraActor) static
Import FBX Camera to existing camera's.
Parameters
CameraNode The Fbx camera
InCameraActor UE actor
References CopyCameraProperties().
Referenced by CopyCameraProperties().
CreateCameraCutSectionForCamera()
void MovieSceneToolHelpers::CreateCameraCutSectionForCamera (UMovieScene * MovieScene, FGuid CameraGuid, FFrameNumber FrameNumber) static
Create a new camera cut section for the given camera.
Parameters
MovieScene MovieScene to add Camera.
CameraGuid CameraGuid Guid of the camera that was added.
FrameNumber FrameNumber it's added at.
References CreateCameraCutSectionForCamera(), and MovieScene.
Referenced by CreateCameraCutSectionForCamera().
CreateSequence()
UMovieSceneSequence * MovieSceneToolHelpers::CreateSequence (FString & NewSequenceName, FString & NewSequencePath, UMovieSceneSubSection * SectionToDuplicate = nullptr) static
References CreateSequence().
Referenced by CreateSequence().
ExportFBX()
bool MovieSceneToolHelpers::ExportFBX (UWorld * World, const FAnimExportSequenceParameters & AnimExportSequenceParameters, const TArray< FGuid > & Bindings, const TArray< UMovieSceneTrack * > & Tracks, INodeNameAdapter & NodeNameAdapter, FMovieSceneSequenceIDRef & Template, const FString & InFBXFileName) static
Export FBX.
Parameters
World The world to export from
AnimExportSequenceParameters The sequence parameters used for evaluation
Bindings The sequencer binding map
Tracks The tracks to export
NodeNameAdaptor Adaptor to look up actor names.
Template Movie scene sequence id.
InFBXFileName the fbx file name.
Returns
Whether the export was successful
References Bindings, ExportFBX(), InFBXFileName, NodeNameAdapter, Template, and Tracks.
Referenced by ExportFBX().
ExportFBXFromControlRigChannels()
bool MovieSceneToolHelpers::ExportFBXFromControlRigChannels (const UMovieSceneSection * Section, const UMovieSceneUserExportFBXControlRigSettings * ExportFBXControlRigSettings, const TArray< FName > & SelectedControlNames, const FMovieSceneSequenceTransform & RootToLocalTransform) static
References ExportFBXFromControlRigChannels(), and RootToLocalTransform.
Referenced by ExportFBXFromControlRigChannels().
ExportFBXFromControlRigChannelsWithDialog()
bool MovieSceneToolHelpers::ExportFBXFromControlRigChannelsWithDialog (const TSharedRef< ISequencer > & InSequencer, UMovieSceneTrack * Track) static
References ExportFBXFromControlRigChannelsWithDialog().
Referenced by ExportFBXFromControlRigChannelsWithDialog().
ExportToAnimSequence()
bool MovieSceneToolHelpers::ExportToAnimSequence (UAnimSequence * AnimSequence, UAnimSeqExportOption * ExportOptions, const FAnimExportSequenceParameters & AnimExportSequenceParameters, USkeletalMeshComponent * SkelMesh) static
References ExportOptions, ExportToAnimSequence(), and SkelMesh.
Referenced by ExportToAnimSequence().
FindAvailableRowIndex()
int32 MovieSceneToolHelpers::FindAvailableRowIndex (UMovieSceneTrack * InTrack, UMovieSceneSection * InSection, const TArray< UMovieSceneSection * > & SectionsToDisregard = TArray< UMovieSceneSection * >()) static
Get the next available row index for the section so that it doesn't overlap any other sections in time.
Parameters
InTrack The track to find the next available row on
InSection The section
SectionsToDisregard Disregard checking these sections
Returns
The next available row index
References FindAvailableRowIndex().
Referenced by FindAvailableRowIndex().
GatherTakes()
void MovieSceneToolHelpers::GatherTakes (const UMovieSceneSection * Section, TArray< FAssetData > & AssetData, uint32 & OutCurrentTakeNumber) static
Gather takes - level sequence assets that have the same shot prefix and shot number in the same asset path (directory)
Parameters
Section The section to gather takes from
AssetData The gathered asset take data
OutCurrentTakeNumber The current take number of the section
References GatherTakes().
Referenced by GatherTakes().
GenerateNewSubsequenceName()
FString MovieSceneToolHelpers::GenerateNewSubsequenceName (const TArray< UMovieSceneSection * > & AllSections, const FString & SubsequencePrefix, FFrameNumber Time) static
Generate a new shot name.
Parameters
AllSections All the sections in the given shot track
Time The time to generate the new shot name at
Returns
The new shot name
References GenerateNewSubsequenceName(), and Time.
Referenced by GenerateNewSubsequenceName().
GenerateNewSubsequencePath()
FString MovieSceneToolHelpers::GenerateNewSubsequencePath (UMovieScene * SequenceMovieScene, const FString & SubsequenceDirectory, FString & NewShotName) static
Generate a new subsequence package.
Parameters
SequenceMovieScene The sequence movie scene for the new subsequence
SubsequenceDirectory The directory for the new subsequence
NewShotName The new shot name
Returns
The new subsequence path
References NewShotName.
GetActorParents()
void MovieSceneToolHelpers::GetActorParents (const FActorForWorldTransforms & Actor, TArray< FActorForWorldTransforms > & OutParentActors) static
References Actor, and GetActorParents().
Referenced by GetActorParents().
GetActorParentsWithAttachments()
void MovieSceneToolHelpers::GetActorParentsWithAttachments (ISequencer * Sequencer, const FActorForWorldTransforms & Actor, TArray< FActorForWorldTransforms > & OutParentActors) static
References Actor, and GetActorParentsWithAttachments().
Referenced by GetActorParentsWithAttachments().
GetActorsAndParentsKeyFrames()
void MovieSceneToolHelpers::GetActorsAndParentsKeyFrames (ISequencer * Sequencer, const FActorForWorldTransforms & Actor, const FFrameNumber & StartFrame, const FFrameNumber & EndFrame, TSortedMap< FFrameNumber, FFrameNumber > & OutFrameMap) static
References Actor, EndFrame, and GetActorsAndParentsKeyFrames().
Referenced by GetActorsAndParentsKeyFrames().
GetActorWorldTransforms() [1/2]
void MovieSceneToolHelpers::GetActorWorldTransforms (IMovieScenePlayer * Player, UMovieSceneSequence * InSequence, FMovieSceneSequenceIDRef Template, const FActorForWorldTransforms & Actors, const TArray< FFrameNumber > & Frames, TArray< FTransform > & OutWorldTransforms) static
References Actors, GetActorWorldTransforms(), Player, and Template.
GetActorWorldTransforms() [2/2]
void MovieSceneToolHelpers::GetActorWorldTransforms (ISequencer * Sequencer, const FActorForWorldTransforms & Actors, const TArray< FFrameNumber > & Frames, TArray< FTransform > & OutWorldTransforms) static
References Actors, and GetActorWorldTransforms().
Referenced by GetActorWorldTransforms(), and GetActorWorldTransforms().
GetCameraName()
FString MovieSceneToolHelpers::GetCameraName (fbxsdk::FbxCamera * InCamera) static
References GetCameraName(), and InCamera.
Referenced by GetCameraName().
GetCameras()
void MovieSceneToolHelpers::GetCameras (fbxsdk::FbxNode * Parent, TArray< fbxsdk::FbxCamera * > & Cameras) static
References GetCameras(), and Parent.
Referenced by GetCameras().
GetChannelValues()
template<typename ChannelType, typename CurveValueType> TArray< CurveValueType > MovieSceneToolHelpers::GetChannelValues (const int32 StartIndex, const int32 EndIndex, const TArray< UMovieSceneSection * > & Sections, const TArray< UMovieSceneSection * > & AbsoluteSections, const FFrameNumber & FrameTime) inline static
Definition at line 706 of file MovieSceneToolHelpers.h.
References GetChannelValues(), Sections, TEXT, UE_LOG, Value, Warning, and Weight.
Referenced by GetChannelValues(), and MergeValue().
GetEvaluationTrack()
const FMovieSceneEvaluationTrack * MovieSceneToolHelpers::GetEvaluationTrack (ISequencer * Sequencer, const FGuid & TrackSignature) static
References GetEvaluationTrack().
Referenced by GetEvaluationTrack().
GetLocationAtTime()
void MovieSceneToolHelpers::GetLocationAtTime (const FMovieSceneEvaluationTrack * Track, UObject * Object, FFrameTime KeyTime, FVector & KeyPos, FRotator & KeyRot, const TSharedPtr< ISequencer > & Sequencer) static
References FVector, GetLocationAtTime(), and Object.
Referenced by GetLocationAtTime().
GetParents()
void MovieSceneToolHelpers::GetParents (TArray< const UObject * > & Parents, const UObject * InObject) static
References GetParents().
Referenced by GetParents().
GetParentTM()
bool MovieSceneToolHelpers::GetParentTM (FTransform & CurrentRefTM, const TSharedPtr< ISequencer > & Sequencer, UObject * ParentObject, FFrameTime KeyTime) static
References GetParentTM().
Referenced by GetParentTM().
GetRefFrameFromParents()
FTransform MovieSceneToolHelpers::GetRefFrameFromParents (const TSharedPtr< ISequencer > & Sequencer, const TArray< const UObject * > & Parents, FFrameTime KeyTime) static
References GetRefFrameFromParents().
Referenced by GetRefFrameFromParents().
GetTakeNumber()
bool MovieSceneToolHelpers::GetTakeNumber (const UMovieSceneSection * Section, FAssetData AssetData, uint32 & OutTakeNumber) static
Get the take number for the given asset.
Parameters
Section The section to gather the take number from
AssetData The take asset to search for
OutTakeNumber The take number for the given asset
Returns
Whether the take number was found
References GetTakeNumber().
Referenced by GetTakeNumber().
GetTransformOriginForFocusedSequence()
FTransform MovieSceneToolHelpers::GetTransformOriginForFocusedSequence (TSharedPtr< ISequencer > InSequencer) static
GetTransformSection()
UMovieScene3DTransformSection * MovieSceneToolHelpers::GetTransformSection (const ISequencer * InSequencer, const FGuid & InGuid, const FTransform & InDefaultTransform = FTransform::Identity) static
Returns the transform section for that guid.
References UE::Math::TTransform< double >::Identity.
HasHiddenMobility()
bool MovieSceneToolHelpers::HasHiddenMobility (const UClass * ObjectClass) static
References HasHiddenMobility().
Referenced by HasHiddenMobility().
ImportAnimSequenceTransforms()
void MovieSceneToolHelpers::ImportAnimSequenceTransforms (const TSharedRef< ISequencer > & Sequencer, const FAssetData & Asset, UMovieScene3DTransformTrack * TransformTrack) static
Import an animation sequence's root transforms into a transform section.
References Asset.
ImportAnimSequenceTransformsEnterPressed()
void MovieSceneToolHelpers::ImportAnimSequenceTransformsEnterPressed (const TSharedRef< ISequencer > & Sequencer, const TArray< FAssetData > & Asset, UMovieScene3DTransformTrack * TransformTrack) static
Import an animation sequence's root transforms into a transform section.
References Asset.
ImportFBXCameraToExisting()
void MovieSceneToolHelpers::ImportFBXCameraToExisting (UnFbx::FFbxImporter * FbxImporter, UMovieSceneSequence * InSequence, IMovieScenePlayer * Player, FMovieSceneSequenceIDRef TemplateID, TMap< FGuid, FString > & InObjectBindingMap, bool bMatchByNameOnly, bool bNotifySlate) static
Import FBX Camera to existing camera's.
Parameters
FbxImporter The Fbx importer
InMovieScene The movie scene to import the fbx into
Player The player we are getting objects from.
TemplateID Id of the sequence that contains the objects being imported onto
InObjectBindingNameMap The object binding to name map to map import fbx animation onto
bCreateCameras Whether to allow creation of cameras if found in the fbx file.
bNotifySlate If an issue show's up, whether or not to notify the UI.
Returns
Whether the import was successful
References ImportFBXCameraToExisting(), and Player.
Referenced by ImportFBXCameraToExisting().
ImportFBXIfReady()
bool MovieSceneToolHelpers::ImportFBXIfReady (UWorld * World, UMovieSceneSequence * InSequence, IMovieScenePlayer * Player, FMovieSceneSequenceIDRef TemplateID, TMap< FGuid, FString > & ObjectBindingMap, UMovieSceneUserImportFBXSettings * ImportFBXSettings, const FFBXInOutParameters & InFBXParams, ISequencer * Sequencer = nullptr) static
Import into an FBX scene that has been readied already, via the ReadyFBXForImport call.
We do this as two pass in case the client want's to do something, like create camera's, before actually loading the data.
Parameters
World The world to import the fbx into
InMovieScene The movie scene to import the fbx into
ObjectBindingMap Map relating binding id's to track names.
TemplateID Id of the sequence that contains the objects being imported onto
ImportFBXSettings FBX Import Settings to enforce.
InFBXParams Paremter from ImportReadiedFbx used to reset some internal fbx settings that we override.
Returns
Whether the fbx file was ready and is ready to be import.
References ImportFBXIfReady(), and Player.
Referenced by ImportFBXIfReady().
ImportFBXIntoControlRigChannels()
bool MovieSceneToolHelpers::ImportFBXIntoControlRigChannels (UMovieScene * MovieScene, const FString & ImportFilename, UMovieSceneUserImportFBXControlRigSettings * ControlRigSettings, TArray< FRigControlFBXNodeAndChannels > * NodeAndChannels, const TArray< FName > & SelectedControlNames, FFrameRate FrameRate) static
References FrameRate, ImportFBXIntoControlRigChannels(), and MovieScene.
Referenced by ImportFBXIntoControlRigChannels().
ImportFBXIntoControlRigChannelsWithDialog()
bool MovieSceneToolHelpers::ImportFBXIntoControlRigChannelsWithDialog (const TSharedRef< ISequencer > & InSequencer, TArray< FRigControlFBXNodeAndChannels > * NodeAndChannels) static
References ImportFBXIntoControlRigChannelsWithDialog().
Referenced by ImportFBXIntoControlRigChannelsWithDialog().
ImportFBXNode()
bool MovieSceneToolHelpers::ImportFBXNode (FString NodeName, UnFbx::FFbxCurvesAPI & CurveAPI, UMovieSceneSequence * InSequence, IMovieScenePlayer * Player, FMovieSceneSequenceIDRef TemplateID, FGuid ObjectBinding, ISequencer * Sequencer = nullptr) static
Import FBX Node to existing actor/node.
Parameters
NodeName Name of fbx node/actor
CurvesApi Existing FBX curves coming in
InMovieScene The movie scene to import the fbx into
Player The player we are getting objects from.
TemplateID Id of the sequence template ID.
ObjectBinding Guid of the object we are importing onto.
Returns
Whether the import was successful
References ImportFBXNode(), and Player.
Referenced by ImportFBXNode().
ImportFBXWithDialog()
bool MovieSceneToolHelpers::ImportFBXWithDialog (UMovieSceneSequence * InSequence, ISequencer & InSequencer, const TMap< FGuid, FString > & InObjectBindingNameMap, TOptional< bool > bCreateCameras) static
Import FBX with dialog.
Parameters
InMovieScene The movie scene to import the fbx into
InObjectBindingNameMap The object binding to name map to map import fbx animation onto
bCreateCameras Whether to allow creation of cameras if found in the fbx file.
Returns
Whether the import was successful
References ImportFBXWithDialog().
Referenced by ImportFBXWithDialog().
IsValidAsset()
bool MovieSceneToolHelpers::IsValidAsset (UMovieSceneSequence * Sequence, const FAssetData & InAssetData) static
References IsValidAsset().
Referenced by IsValidAsset().
LockCameraActorToViewport()
void MovieSceneToolHelpers::LockCameraActorToViewport (const TSharedPtr< ISequencer > & Sequencer, ACameraActor * CameraActor) static
Lock the given camera actor to the viewport.
Parameters
Sequencer The Sequencer to set the camera cut enabled for
CameraActor The camera actor to lock
References LockCameraActorToViewport().
Referenced by LockCameraActorToViewport().
MakeEnumComboBox()
TSharedRef< SWidget > MovieSceneToolHelpers::MakeEnumComboBox (const UEnum * Enum, TAttribute< int32 > CurrentValue, SEnumComboBox::FOnEnumSelectionChanged OnSelectionChanged) static
Generate a combobox for editing enum values.
Parameters
Enum The enum to make the combobox from
CurrentValue The current value to display
OnSelectionChanged Delegate fired when selection is changed
Returns
The new widget
References Enum, and MakeEnumComboBox().
Referenced by MakeEnumComboBox().
MergeChannels()
template<typename ChannelType> bool MovieSceneToolHelpers::MergeChannels (int32 SectionChannelIndex, TArray< ChannelType * > & Channels, const TArray< UMovieSceneSection * > & Sections, const TRange< FFrameNumber > & Range, FChannelMergeAlgorithm MergeAlgorithm, const TArray< UMovieSceneSection * > & TrackSections, const int32 * Increment = nullptr) inline static
Definition at line 867 of file MovieSceneToolHelpers.h.
References TArray< InElementType, InAllocatorType >::Add(), CalculateFramesBetween(), TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBoundValue(), INDEX_NONE, MergeValue(), MovieScene, TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), Override, TArray< InElementType, InAllocatorType >::Reset(), Sections, SetOrAddKey(), SplitSectionsByBlendType(), TEXT, UE_LOG, Value, and Warning.
Referenced by MergeSections(), and MergeSections().
MergeSections() [1/2]
template<typename ChannelType> bool MovieSceneToolHelpers::MergeSections (UMovieSceneSection * BaseSection, TArray< UMovieSceneSection * > & AbsoluteSections, TArray< UMovieSceneSection * > & AdditiveSections, int32 StartIndex, int32 EndIndex, const TRange< FFrameNumber > & Range, const int32 * Increment = nullptr) inline static
Definition at line 1059 of file MovieSceneToolHelpers.h.
References Add, Average, MergeChannels(), TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), TEXT, UE_LOG, and Warning.
MergeSections() [2/2]
template<typename ChannelType> bool MovieSceneToolHelpers::MergeSections (UMovieSceneSection * BaseSection, UMovieSceneSection * TopSection, int32 StartIndex, int32 EndIndex, const TRange< FFrameNumber > & Range, const TArray< UMovieSceneSection * > & TrackSections, const int32 * Increment = nullptr) inline static
Definition at line 990 of file MovieSceneToolHelpers.h.
References Add, Average, MergeChannels(), TArrayView< InElementType, InSizeType >::Num(), Override, Sections, TEXT, UE_LOG, and Warning.
MergeValue()
template<typename ChannelType, typename CurveValueType> bool MovieSceneToolHelpers::MergeValue (CurveValueType & InOutValue, TArray< ChannelType * > & Channels, const FFrameNumber & Frame, int32 SectionChannelIndex, const TArray< UMovieSceneSection * > & Sections, const TArray< UMovieSceneSection * > & AbsoluteSections, const TArray< UMovieSceneSection * > & OtherSections, int32 OverrideChannelIndex, FChannelMergeAlgorithm MergeAlgorithm) inline static
Definition at line 789 of file MovieSceneToolHelpers.h.
References Add, Average, GetChannelValues(), IsValid(), TArray< InElementType, InAllocatorType >::Num(), Override, Sections, and Weight.
Referenced by MergeChannels().
MovieSceneTranslatorExport()
bool MovieSceneToolHelpers::MovieSceneTranslatorExport (FMovieSceneExporter * InExporter, const UMovieScene * InMovieScene, const FMovieSceneCaptureSettings & Settings) static
Export movie scene formats.
Parameters
InExporter The movie scene exporter.
InMovieScene The movie scene with the cinematic shot track and audio tracks to export
InFrameRate The frame rate to export the AAF at
InSaveDirectory Optional directory path to save to. If none given, a dialog will pop up to prompt the user
InHandleFrames The number of handle frames to include for each shot.
Returns
Whether the export was successful
References MovieSceneTranslatorExport().
Referenced by MovieSceneTranslatorExport().
MovieSceneTranslatorImport()
bool MovieSceneToolHelpers::MovieSceneTranslatorImport (FMovieSceneImporter * InImporter, UMovieScene * InMovieScene, FFrameRate InFrameRate, FString InOpenDirectory = TEXT("")) static
Import movie scene formats.
Parameters
InImporter The movie scene importer.
InMovieScene The movie scene to import the format into
InFrameRate The frame rate to import the format at
InOpenDirectory Optional directory path to open from. If none given, a dialog will pop up to prompt the user
Returns
Whether the import was successful
References MovieSceneTranslatorImport(), and TEXT.
Referenced by MovieSceneTranslatorImport().
MovieSceneTranslatorLogMessages()
void MovieSceneToolHelpers::MovieSceneTranslatorLogMessages (FMovieSceneTranslator * InTranslator, TSharedRef< FMovieSceneTranslatorContext > InContext, bool bDisplayMessages) static
Log messages and display error message window for MovieScene translators.
Parameters
InTranslator The movie scene importer or exporter.
InContext The context used to gather error, warning or info messages during import or export.
bDisplayMessages Whether to open the message log window after adding the message.
References MovieSceneTranslatorLogMessages().
Referenced by MovieSceneTranslatorLogMessages().
MovieSceneTranslatorLogOutput()
void MovieSceneToolHelpers::MovieSceneTranslatorLogOutput (FMovieSceneTranslator * InTranslator, TSharedRef< FMovieSceneTranslatorContext > InContext) static
Log error output for MovieScene translators.
Parameters
InTranslator The movie scene importer or exporter.
InContext The context used to gather error, warning or info messages during import or export.
References MovieSceneTranslatorLogOutput().
Referenced by MovieSceneTranslatorLogOutput().
OptimizeSection()
bool MovieSceneToolHelpers::OptimizeSection (const FKeyDataOptimizationParams & InParams, UMovieSceneSection * InSection) static
OverlapsSection()
bool MovieSceneToolHelpers::OverlapsSection (UMovieSceneTrack * InTrack, UMovieSceneSection * InSection, const TArray< UMovieSceneSection * > & SectionsToDisregard = TArray< UMovieSceneSection * >()) static
Does this section overlap any other track section?
Parameters
InTrack The track to find sections on
InSection The section
SectionsToDisregard Disregard checking these sections
Returns
Whether this section overlaps any other track section
References OverlapsSection().
Referenced by OverlapsSection().
ParseShotName()
bool MovieSceneToolHelpers::ParseShotName (const FString & ShotName, FString & ShotPrefix, uint32 & ShotNumber, uint32 & TakeNumber, uint32 & ShotNumberDigits, uint32 & TakeNumberDigits) static
Parse a shot name into its components.
Parameters
ShotName The shot name to parse
ShotPrefix The parsed shot prefix
ShotNumber The parsed shot number
TakeNumber The parsed take number
ShotNumberDigits The number of digits to pad for the shot number
TakeNumberDigits The number of digits to pad for the take number
Returns
Whether the shot name was parsed successfully
ReadyFBXForImport()
bool MovieSceneToolHelpers::ReadyFBXForImport (const FString & ImportFilename, UMovieSceneUserImportFBXSettings * ImportFBXSettings, FFBXInOutParameters & OutFBXParams) static
Get FBX Ready for Import.
This make sure the passed in file make be imported. After calling this call ImportReadiedFbx. It returns out some parameters that we forcably change so we reset them later.
Parameters
ImportFileName The filename to import into
ImportFBXSettings FBX Import Settings to enforce.
OutFBXParams Paremter to pass back to ImportReadiedFbx
Returns
Whether the fbx file was ready and is ready to be import.
References ReadyFBXForImport().
Referenced by ReadyFBXForImport().
SetOrAddKey() [1/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > & ChannelData, FFrameNumber Time, double Value, const EMovieSceneKeyInterpolation Interpolation = EMovieSceneKeyInterpolation::Auto) static
References Auto, Interpolation, SetOrAddKey(), Time, and Value.
SetOrAddKey() [2/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > & ChannelData, FFrameNumber Time, FMovieSceneDoubleValue Value) static
References SetOrAddKey(), Time, and Value.
SetOrAddKey() [3/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneDoubleValue > & Curve, FFrameNumber Time, double Value, float ArriveTangent, float LeaveTangent, ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode, FFrameRate FrameRate, ERichCurveTangentWeightMode WeightedMode = RCTWM_WeightedNone, float ArriveTangentWeight = 0.0f, float LeaveTangentWeight = 0.0f) static
References ArriveTangent, FrameRate, LeaveTangent, SetOrAddKey(), Time, and Value.
SetOrAddKey() [4/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > & ChannelData, FFrameNumber Time, float Value, const EMovieSceneKeyInterpolation Interpolation = EMovieSceneKeyInterpolation::Auto) static
References Auto, Interpolation, SetOrAddKey(), Time, and Value.
Referenced by MergeChannels(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), and SetOrAddKey().
SetOrAddKey() [5/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > & Curve, FFrameNumber Time, const FMovieSceneFloatValue & Value) static
References SetOrAddKey(), Time, and Value.
SetOrAddKey() [6/6]
void MovieSceneToolHelpers::SetOrAddKey (TMovieSceneChannelData< FMovieSceneFloatValue > & Curve, FFrameNumber Time, float Value, float ArriveTangent, float LeaveTangent, ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode, FFrameRate FrameRate, ERichCurveTangentWeightMode WeightedMode = RCTWM_WeightedNone, float ArriveTangentWeight = 0.0f, float LeaveTangentWeight = 0.0f) static
References ArriveTangent, FrameRate, LeaveTangent, SetOrAddKey(), Time, and Value.
SetTakeNumber()
bool MovieSceneToolHelpers::SetTakeNumber (const UMovieSceneSection * Section, uint32 InTakeNumber) static
Set the take number for the given asset.
Parameters
Section The section to set the take number on
InTakeNumber The take number for the given asset
Returns
Whether the take number could be set
References SetTakeNumber().
Referenced by SetTakeNumber().
ShowExportEDLDialog()
bool MovieSceneToolHelpers::ShowExportEDLDialog (const UMovieScene * InMovieScene, FFrameRate InFrameRate, FString InSaveDirectory = TEXT(""), int32 InHandleFrames = 8, FString InMovieExtension = TEXT(".avi")) static
Show Export EDL Dialog.
Parameters
InMovieScene The movie scene with the cinematic shot track and audio tracks to export
InFrameRate The frame rate to export the EDL at
InSaveDirectory Optional directory path to save to. If none given, a dialog will pop up to prompt the user
InHandleFrames The number of handle frames to include for each shot.
MovieExtension The movie extension for the shot filenames (ie. .avi, .mov, .mp4)
Returns
Whether the export was successful
References ShowExportEDLDialog(), and TEXT.
Referenced by ShowExportEDLDialog().
ShowImportEDLDialog()
bool MovieSceneToolHelpers::ShowImportEDLDialog (UMovieScene * InMovieScene, FFrameRate InFrameRate, FString InOpenDirectory = TEXT("")) static
Show Import EDL Dialog.
Parameters
InMovieScene The movie scene to import the edl into
InFrameRate The frame rate to import the EDL at
InOpenDirectory Optional directory path to open from. If none given, a dialog will pop up to prompt the user
Returns
Whether the import was successful
References ShowImportEDLDialog(), and TEXT.
Referenced by ShowImportEDLDialog().
SplitSection()
void MovieSceneToolHelpers::SplitSection (const TSet< UMovieSceneSection * > & Sections, FQualifiedFrameTime Time, bool bDeleteKeys) static
Splits sections at the given time.
Parameters
Sections The sections to split
Time The time at which to split
bDeleteKeys Delete keys outside the split ranges
References Sections, and Time.
SplitSectionsByBlendType()
void MovieSceneToolHelpers::SplitSectionsByBlendType (EMovieSceneBlendType BlendType, const TArray< UMovieSceneSection * > & InSections, TArray< UMovieSceneSection * > & OutSections, TArray< UMovieSceneSection * > & OutBlendTypeSections) static
References SplitSectionsByBlendType().
Referenced by MergeChannels(), and SplitSectionsByBlendType().
TrimOrExtendSection()
void MovieSceneToolHelpers::TrimOrExtendSection (UMovieSceneTrack * Track, TOptional< int32 > RowIndex, FQualifiedFrameTime Time, bool bTrimOrExtendLeft, bool bDeleteKeys) static
Trim or extend section at the given time.
Parameters
Track The track that contains the sections to trim
RowIndex Optional row index to trim, otherwise trims sections with all row indices
Time The time at which to trim
bTrimOrExtendleft Trim or extend left or right
bDeleteKeys Delete keys outside the split ranges
References Time.
TrimSection()
void MovieSceneToolHelpers::TrimSection (const TSet< UMovieSceneSection * > & Sections, FQualifiedFrameTime Time, bool bTrimLeft, bool bDeleteKeys) static
Trim section at the given time.
Parameters
Sections The sections to trim
Time The time at which to trim
bTrimLeft Trim left or trim right
bDeleteKeys Delete keys outside the split ranges
References Sections, and Time.
UE_DEPRECATED() [1/5]
MovieSceneToolHelpers::UE_DEPRECATED (5. 3, "GenerateNewShotName has been deprecated in favor of GenerateNewSubsequenceName that takes a given prefix") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/5]
MovieSceneToolHelpers::UE_DEPRECATED (5. 3, "GenerateNewShotPath has been deprecated in favor of GenerateNewSubsequencePath that takes a given directory")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/5]
MovieSceneToolHelpers::UE_DEPRECATED (5. 5, "BakeToSkelMeshToCallbacks taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences")
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
MovieSceneToolHelpers::UE_DEPRECATED (5. 5, "ExportFBX taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences")
References UE_DEPRECATED().
UE_DEPRECATED() [5/5]
MovieSceneToolHelpers::UE_DEPRECATED (5. 5, "ExportToAnimSequence taking movie scene has been deprecated in favor of a new function that takes current and root movie scene sequences")
References UE_DEPRECATED().
Field Documentation
Bindings
UMovieScene IMovieScenePlayer const TArray<FGuid>& MovieSceneToolHelpers::Bindings
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBX().
EndCallback
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB FTickAnimationCB FEndAnimationCB MovieSceneToolHelpers::EndCallback
Definition at line 488 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks().
ExportOptions [1/2]
UAnimSeqExportOption* MovieSceneToolHelpers::ExportOptions
Definition at line 461 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks(), and ExportToAnimSequence().
ExportOptions [2/2]
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption* MovieSceneToolHelpers::ExportOptions
Definition at line 487 of file MovieSceneToolHelpers.h.
InFBXFileName
UMovieScene IMovieScenePlayer const TArray<FGuid> const TArray<UMovieSceneTrack*> INodeNameAdapter FMovieSceneSequenceIDRef const FString& MovieSceneToolHelpers::InFBXFileName
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBX().
InitCallback
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB MovieSceneToolHelpers::InitCallback
Definition at line 488 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks().
MovieScene [1/2]
UMovieScene* MovieSceneToolHelpers::MovieScene
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by CalculateFramesBetween(), CreateCameraCutSectionForCamera(), ImportFBXIntoControlRigChannels(), and MergeChannels().
MovieScene [2/2]
UAnimSeqExportOption UMovieScene* MovieSceneToolHelpers::MovieScene
Definition at line 461 of file MovieSceneToolHelpers.h.
NewShotName
FString& MovieSceneToolHelpers::NewShotName
Definition at line 194 of file MovieSceneToolHelpers.h.
Referenced by GenerateNewSubsequencePath().
NodeNameAdapter
UMovieScene IMovieScenePlayer const TArray<FGuid> const TArray<UMovieSceneTrack*> INodeNameAdapter& MovieSceneToolHelpers::NodeNameAdapter
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBX().
Player [1/3]
UMovieScene IMovieScenePlayer* MovieSceneToolHelpers::Player
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by GetActorWorldTransforms(), ImportFBXCameraToExisting(), ImportFBXIfReady(), and ImportFBXNode().
Player [2/3]
UAnimSeqExportOption UMovieScene IMovieScenePlayer* MovieSceneToolHelpers::Player
Definition at line 461 of file MovieSceneToolHelpers.h.
Player [3/3]
IMovieScenePlayer* MovieSceneToolHelpers::Player
Definition at line 486 of file MovieSceneToolHelpers.h.
RootToLocalTransform [1/3]
UMovieScene IMovieScenePlayer const TArray<FGuid> const TArray<UMovieSceneTrack*> INodeNameAdapter FMovieSceneSequenceIDRef const FString FMovieSceneSequenceTransform& MovieSceneToolHelpers::RootToLocalTransform
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBXFromControlRigChannels().
RootToLocalTransform [2/3]
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform& MovieSceneToolHelpers::RootToLocalTransform
Definition at line 462 of file MovieSceneToolHelpers.h.
RootToLocalTransform [3/3]
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform& MovieSceneToolHelpers::RootToLocalTransform
Definition at line 487 of file MovieSceneToolHelpers.h.
SkelMesh [1/2]
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent* MovieSceneToolHelpers::SkelMesh
Definition at line 462 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks(), and ExportToAnimSequence().
SkelMesh [2/2]
IMovieScenePlayer USkeletalMeshComponent* MovieSceneToolHelpers::SkelMesh
Definition at line 487 of file MovieSceneToolHelpers.h.
StartCallback
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB MovieSceneToolHelpers::StartCallback
Definition at line 488 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks().
Template [1/3]
UMovieScene IMovieScenePlayer const TArray<FGuid> const TArray<UMovieSceneTrack*> INodeNameAdapter FMovieSceneSequenceIDRef& MovieSceneToolHelpers::Template
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBX(), and GetActorWorldTransforms().
Template [2/3]
UAnimSeqExportOption UMovieScene IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef& MovieSceneToolHelpers::Template
Definition at line 462 of file MovieSceneToolHelpers.h.
Template [3/3]
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef& MovieSceneToolHelpers::Template
Definition at line 487 of file MovieSceneToolHelpers.h.
TickCallback
IMovieScenePlayer USkeletalMeshComponent FMovieSceneSequenceIDRef FMovieSceneSequenceTransform UAnimSeqExportOption FInitAnimationCB FStartAnimationCB FTickAnimationCB MovieSceneToolHelpers::TickCallback
Definition at line 488 of file MovieSceneToolHelpers.h.
Referenced by BakeToSkelMeshToCallbacks().
Time
FFrameNumber MovieSceneToolHelpers::Time
Definition at line 207 of file MovieSceneToolHelpers.h.
Referenced by CanSplitSection(), CanTrimSectionLeft(), CanTrimSectionRight(), GenerateNewSubsequenceName(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SetOrAddKey(), SplitSection(), TrimOrExtendSection(), and TrimSection().
Tracks
UMovieScene IMovieScenePlayer const TArray<FGuid> const TArray<UMovieSceneTrack*>& MovieSceneToolHelpers::Tracks
Definition at line 355 of file MovieSceneToolHelpers.h.
Referenced by ExportFBX().
The documentation for this class was generated from the following file:
MovieSceneToolHelpers.h