Unreal Engine 5.6 C++ API: FRandomStream Struct Reference
FRandomStream Struct Reference
Implements a thread-safe SRand based RNG.
#include "RandomStream.h"
Public Member Functions
FRandomStream ()
Default constructor.
FRandomStream (FName InName)
Creates and initializes a new random stream from the specified name.
FRandomStream (int32 InSeed)
Creates and initializes a new random stream from the specified seed value.
FORCEINLINE float FRand () const
Mirrors the random number API in FMath.
FORCEINLINE FVector::FReal FRandRange (FVector::FReal InMin, FVector::FReal InMax) const
Helper function for rand implementations.
void GenerateNewSeed ()
Generates a new random seed.
int32 GetCurrentSeed () const
Gets the current seed.
float GetFraction () const
Returns a random float number in the range [0, 1).
int32 GetInitialSeed () const
FVector GetUnitVector () const
Returns a random vector of unit size.
uint32 GetUnsignedInt () const
Returns a random number between 0 and MAXUINT.
void Initialize (FName InName)
Initializes this random stream using the specified name.
void Initialize (int32 InSeed)
Initializes this random stream with the specified seed value.
FORCEINLINE int32 RandHelper (int32 A) const
Helper function for rand implementations.
FORCEINLINE FVector RandPointInBox (const FBox &Box) const
FORCEINLINE int32 RandRange (int32 Min, int32 Max) const
Helper function for rand implementations.
void Reset () const
Resets this random stream to the initial seed value.
FString ToString () const
Get a textual representation of the RandomStream.
FORCEINLINE FVector VRand () const
Returns a random vector of unit size.
FORCEINLINE FVector VRandCone (FVector const &Dir, float ConeHalfAngleRad) const
Returns a random unit vector, uniformly distributed, within the specified cone.
FORCEINLINE FVector VRandCone (FVector const &Dir, float HorizontalConeHalfAngleRad, float VerticalConeHalfAngleRad) const
Returns a random unit vector, uniformly distributed, within the specified cone.
Protected Member Functions
void MutateSeed () const
Mutates the current seed into the next seed.
Private Attributes
int32 InitialSeed
uint32 Seed
Friends
struct Z_Construct_UScriptStruct_FRandomStream_Statics
Detailed Description
Implements a thread-safe SRand based RNG.
Very bad quality in the lower bits. Don't use the modulus (%) operator.
Definition at line 19 of file RandomStream.h.
Constructor & Destructor Documentation
FRandomStream() [1/3]
FRandomStream::FRandomStream () inline
Default constructor.
The seed should be set prior to use.
Definition at line 30 of file RandomStream.h.
References InitialSeed, and Seed.
FRandomStream() [2/3]
FRandomStream::FRandomStream (int32 InSeed) inline
Creates and initializes a new random stream from the specified seed value.
Parameters
InSeed The seed value.
Definition at line 40 of file RandomStream.h.
References Initialize.
FRandomStream() [3/3]
FRandomStream::FRandomStream (FName InName) inline
Creates and initializes a new random stream from the specified name.
Note
If NAME_None is provided, the stream will be seeded using the current time.
Parameters
InName The name value from which the stream will be initialized.
Definition at line 51 of file RandomStream.h.
References Initialize, and InName.
Member Function Documentation
FRand()
FORCEINLINE float FRandomStream::FRand () const inline
Mirrors the random number API in FMath.
Returns
Random number.
Definition at line 176 of file RandomStream.h.
References FORCEINLINE, and GetFraction().
Referenced by AdjustParticleBaseSizeForUVFlipping(), FRandRange(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), VRandCone(), and VRandCone().
FRandRange()
FORCEINLINE FVector::FReal FRandomStream::FRandRange (FVector::FReal InMin, FVector::FReal InMax) const inline
Helper function for rand implementations.
Returns
A random number >= Min and <= Max
Definition at line 209 of file RandomStream.h.
References FORCEINLINE, and FRand().
Referenced by RandPointInBox().
GenerateNewSeed()
void FRandomStream::GenerateNewSeed () inline
Generates a new random seed.
Definition at line 105 of file RandomStream.h.
References Initialize.
GetCurrentSeed()
int32 FRandomStream::GetCurrentSeed () const inline
Gets the current seed.
Returns
Current seed.
Definition at line 166 of file RandomStream.h.
References Seed.
GetFraction()
float FRandomStream::GetFraction () const inline
Returns a random float number in the range [0, 1).
Returns
Random number.
Definition at line 115 of file RandomStream.h.
References MutateSeed(), and Seed.
Referenced by FRand(), GetUnitVector(), and RandHelper().
GetInitialSeed()
int32 FRandomStream::GetInitialSeed () const inline
Definition at line 97 of file RandomStream.h.
References InitialSeed.
GetUnitVector()
FVector FRandomStream::GetUnitVector () const inline
Returns a random vector of unit size.
Returns
Random unit vector.
Definition at line 143 of file RandomStream.h.
References FVector, GetFraction(), and UE_KINDA_SMALL_NUMBER.
Referenced by VRand().
GetUnsignedInt()
uint32 FRandomStream::GetUnsignedInt () const inline
Returns a random number between 0 and MAXUINT.
Returns
Random number.
Definition at line 131 of file RandomStream.h.
References MutateSeed(), and Seed.
Initialize() [1/2]
void FRandomStream::Initialize (FName InName) inline
Initializes this random stream using the specified name.
Note
If NAME_None is provided, the stream will be seeded using the current time.
Parameters
InName The name value from which the stream will be initialized.
Definition at line 75 of file RandomStream.h.
References FAndroidTime::Cycles(), GetTypeHash(), InitialSeed, InName, and Seed.
Initialize() [2/2]
void FRandomStream::Initialize (int32 InSeed) inline
Initializes this random stream with the specified seed value.
Parameters
InSeed The seed value.
Definition at line 63 of file RandomStream.h.
References InitialSeed, and Seed.
MutateSeed()
void FRandomStream::MutateSeed () const inline protected
Mutates the current seed into the next seed.
Definition at line 340 of file RandomStream.h.
References Seed.
Referenced by GetFraction(), and GetUnsignedInt().
RandHelper()
FORCEINLINE int32 FRandomStream::RandHelper (int32 A) const inline
Helper function for rand implementations.
Returns
A random number in [0..A)
Definition at line 186 of file RandomStream.h.
References A, FORCEINLINE, and GetFraction().
Referenced by RandRange().
RandPointInBox()
FORCEINLINE FVector FRandomStream::RandPointInBox (const FBox & Box) const inline
Definition at line 224 of file RandomStream.h.
References Box, FORCEINLINE, FRandRange(), and FVector.
RandRange()
FORCEINLINE int32 FRandomStream::RandRange (int32 Min, int32 Max) const inline
Helper function for rand implementations.
Returns
A random number >= Min and <= Max
Definition at line 197 of file RandomStream.h.
References FORCEINLINE, Max, and RandHelper().
Reset()
void FRandomStream::Reset () const inline
Resets this random stream to the initial seed value.
Definition at line 92 of file RandomStream.h.
References InitialSeed, and Seed.
ToString()
FString FRandomStream::ToString () const inline
Get a textual representation of the RandomStream.
Returns
Text describing the RandomStream.
Definition at line 330 of file RandomStream.h.
References InitialSeed, Seed, and TEXT.
VRand()
FORCEINLINE FVector FRandomStream::VRand () const inline
Returns a random vector of unit size.
Returns
Random unit vector.
Definition at line 219 of file RandomStream.h.
References FORCEINLINE, FVector, and GetUnitVector().
Referenced by UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select().
VRandCone() [1/2]
FORCEINLINE FVector FRandomStream::VRandCone (FVector const & Dir, float ConeHalfAngleRad) const inline
Returns a random unit vector, uniformly distributed, within the specified cone.
Parameters
Dir The center direction of the cone
ConeHalfAngleRad Half-angle of cone, in radians.
Returns
Normalized vector within the specified cone.
Definition at line 238 of file RandomStream.h.
References FORCEINLINE, FRand(), FVector, UE::Math::TVector< T >::GetSafeNormal(), UE::Math::TMatrix< T >::GetUnitAxis(), UE::Math::TVector< T >::RotateAngleAxis(), UE::Math::TVector< T >::Rotation(), UE_PI, EAxis::X, and EAxis::Y.
VRandCone() [2/2]
FORCEINLINE FVector FRandomStream::VRandCone (FVector const & Dir, float HorizontalConeHalfAngleRad, float VerticalConeHalfAngleRad) const inline
Returns a random unit vector, uniformly distributed, within the specified cone.
Parameters
Dir The center direction of the cone
HorizontalConeHalfAngleRad Horizontal half-angle of cone, in radians.
VerticalConeHalfAngleRad Vertical half-angle of cone, in radians.
Returns
Normalized vector within the specified cone.
Definition at line 283 of file RandomStream.h.
References FORCEINLINE, FRand(), FVector, UE::Math::TVector< T >::GetSafeNormal(), UE::Math::TMatrix< T >::GetUnitAxis(), UE::Math::TVector< T >::RotateAngleAxis(), UE::Math::TVector< T >::Rotation(), FMath::Square(), UE_PI, EAxis::X, and EAxis::Y.
Friends And Related Symbol Documentation
Z_Construct_UScriptStruct_FRandomStream_Statics
friend struct Z_Construct_UScriptStruct_FRandomStream_Statics friend
Definition at line 21 of file RandomStream.h.
References Z_Construct_UScriptStruct_FRandomStream_Statics.
Referenced by Z_Construct_UScriptStruct_FRandomStream_Statics.
Field Documentation
InitialSeed
int32 FRandomStream::InitialSeed private
Definition at line 348 of file RandomStream.h.
Referenced by FRandomStream(), GetInitialSeed(), Initialize(), Initialize(), Reset(), and ToString().
Seed
uint32 FRandomStream::Seed mutable private
Definition at line 352 of file RandomStream.h.
Referenced by FRandomStream(), GetCurrentSeed(), GetFraction(), GetUnsignedInt(), Initialize(), Initialize(), MutateSeed(), Reset(), and ToString().
The documentation for this struct was generated from the following file:
RandomStream.h