Unreal Engine 5.6 C++ API: FSequencerFilterBase< InFilterType > Class Template Reference
FSequencerFilterBase< InFilterType > Class Template Reference
Sequencer base filter for all Sequencer filters (Sequencer, Navigation Tool, etc.)
#include "SequencerFilterBase.h"
Public Member Functions
FSequencerFilterBase (ISequencerFilterBar &InOutFilterInterface, TSharedPtr< FFilterCategory > &&InCategory=nullptr)
virtual void ActiveStateChanged (const bool bInActive) override
virtual void BindCommands ()
bool CanToggleFilter () const
virtual FLinearColor GetColor () const override
virtual FText GetDefaultToolTipText () const
virtual FText GetDisplayName () const override
virtual ISequencerFilterBar & GetFilterInterface () const
virtual FSlateIcon GetIcon () const
ISequencer & GetSequencer () const
virtual TSharedPtr< FUICommandInfo > GetToggleCommand () const
virtual FText GetToolTipText () const override
virtual bool IsCustomTextFilter () const
virtual bool IsInverseFilter () const override
virtual void LoadSettings (const FString &InIniFilename, const FString &InIniSection, const FString &InSettingsString) override
virtual void ModifyContextMenu (FMenuBuilder &MenuBuilder) override
virtual bool PassesFilter (InFilterType InItem) const override
virtual void SaveSettings (const FString &InIniFilename, const FString &InIniSection, const FString &InSettingsString) const override
virtual bool SupportsSequence (UMovieSceneSequence *const InSequence) const
void ToggleFilter ()
Public Member Functions inherited from TSharedFromThis< FSequencerFilterBase< InFilterType > >
TSharedRef< FSequencerFilterBase< InFilterType >, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSequencerFilterBase< InFilterType >, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FText BuildTooltipTextForCommand (const FText &InBaseText, const TSharedPtr< FUICommandInfo > &InCommand)
static bool SupportsDaySequence (UMovieSceneSequence *const InSequence)
static bool SupportsLevelSequence (UMovieSceneSequence *const InSequence)
static bool SupportsUMGSequence (UMovieSceneSequence *const InSequence)
Protected Member Functions
void MapToggleAction (const TSharedPtr< FUICommandInfo > &InCommand)
Protected Member Functions inherited from TSharedFromThis< FSequencerFilterBase< InFilterType > >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
ISequencerFilterBar & FilterInterface
Private Member Functions
virtual FName GetIconName () const override
Hide behind private to force use of GetIcon() instead.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FSequencerFilterBase< InFilterType > >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename InFilterType>
class FSequencerFilterBase< InFilterType >
Sequencer base filter for all Sequencer filters (Sequencer, Navigation Tool, etc.)
Definition at line 12 of file SequencerFilterBase.h.
Constructor & Destructor Documentation
FSequencerFilterBase()
template<typename InFilterType> FSequencerFilterBase< InFilterType >::FSequencerFilterBase (ISequencerFilterBar & InOutFilterInterface, TSharedPtr< FFilterCategory > && InCategory = nullptr) inline
Definition at line 52 of file SequencerFilterBase.h.
References FilterInterface.
Member Function Documentation
ActiveStateChanged()
template<typename InFilterType> virtual void FSequencerFilterBase< InFilterType >::ActiveStateChanged (const bool bInActive) inline override virtual
Reimplemented in FSequencerTrackFilter_Selected, and UE::SequenceNavigator::FNavigationToolFilter_Playhead.
Definition at line 83 of file SequencerFilterBase.h.
BindCommands()
template<typename InFilterType> virtual void FSequencerFilterBase< InFilterType >::BindCommands () inline virtual
Reimplemented in FSequencerTrackFilter_HideIsolate.
Definition at line 95 of file SequencerFilterBase.h.
References GetToggleCommand(), and MapToggleAction().
BuildTooltipTextForCommand()
template<typename InFilterType> FText FSequencerFilterBase< InFilterType >::BuildTooltipTextForCommand (const FText & InBaseText, const TSharedPtr< FUICommandInfo > & InCommand) inline static
Definition at line 41 of file SequencerFilterBase.h.
References FText::Format(), and NSLOCTEXT.
Referenced by GetToolTipText().
CanToggleFilter()
template<typename InFilterType> bool FSequencerFilterBase< InFilterType >::CanToggleFilter () const inline
Definition at line 105 of file SequencerFilterBase.h.
References FilterInterface, and GetDisplayName().
Referenced by MapToggleAction().
GetColor()
template<typename InFilterType> virtual FLinearColor FSequencerFilterBase< InFilterType >::GetColor () const inline override virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolFilter_CustomText.
Definition at line 74 of file SequencerFilterBase.h.
References FLinearColor::White.
GetDefaultToolTipText()
template<typename InFilterType> virtual FText FSequencerFilterBase< InFilterType >::GetDefaultToolTipText () const inline virtual
Reimplemented in FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_Condition, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_Group, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Level, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Particle, FSequencerTrackFilter_Selected, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeDilation, FSequencerTrackFilter_TimeWarp, FSequencerTrackFilter_Unbound, UE::SequenceNavigator::FNavigationToolFilter_CustomText, UE::SequenceNavigator::FNavigationToolFilter_Dirty, UE::SequenceNavigator::FNavigationToolFilter_Marks, UE::SequenceNavigator::FNavigationToolFilter_Playhead, UE::SequenceNavigator::FNavigationToolFilter_Sequence, UE::SequenceNavigator::FNavigationToolFilter_Track, and UE::SequenceNavigator::FNavigationToolFilter_Unbound.
Definition at line 91 of file SequencerFilterBase.h.
Referenced by GetToolTipText().
GetDisplayName()
template<typename InFilterType> virtual FText FSequencerFilterBase< InFilterType >::GetDisplayName () const inline override virtual
Reimplemented in FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_Condition, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_Group, FSequencerTrackFilter_HideIsolate, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Level, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Particle, FSequencerTrackFilter_Selected, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeDilation, FSequencerTrackFilter_TimeWarp, FSequencerTrackFilter_Unbound, UE::SequenceNavigator::FNavigationToolFilter_CustomText, UE::SequenceNavigator::FNavigationToolFilter_Dirty, UE::SequenceNavigator::FNavigationToolFilter_Marks, UE::SequenceNavigator::FNavigationToolFilter_Playhead, UE::SequenceNavigator::FNavigationToolFilter_Sequence, UE::SequenceNavigator::FNavigationToolFilter_Text, UE::SequenceNavigator::FNavigationToolFilter_Track, and UE::SequenceNavigator::FNavigationToolFilter_Unbound.
Definition at line 63 of file SequencerFilterBase.h.
References FText::GetEmpty().
Referenced by CanToggleFilter(), and ToggleFilter().
GetFilterInterface()
template<typename InFilterType> virtual ISequencerFilterBar & FSequencerFilterBase< InFilterType >::GetFilterInterface () const inline virtual
Reimplemented in FSequencerTrackFilter, and UE::SequenceNavigator::FNavigationToolFilter.
Definition at line 89 of file SequencerFilterBase.h.
References FilterInterface.
GetIcon()
template<typename InFilterType> virtual FSlateIcon FSequencerFilterBase< InFilterType >::GetIcon () const inline virtual
Reimplemented in FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_Condition, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_Group, FSequencerTrackFilter_HideIsolate, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Level, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Particle, FSequencerTrackFilter_Selected, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeDilation, FSequencerTrackFilter_TimeWarp, FSequencerTrackFilter_Unbound, UE::SequenceNavigator::FNavigationToolFilter_Dirty, UE::SequenceNavigator::FNavigationToolFilter_Marks, UE::SequenceNavigator::FNavigationToolFilter_Playhead, UE::SequenceNavigator::FNavigationToolFilter_Sequence, UE::SequenceNavigator::FNavigationToolFilter_Track, and UE::SequenceNavigator::FNavigationToolFilter_Unbound.
Definition at line 92 of file SequencerFilterBase.h.
GetIconName()
template<typename InFilterType> virtual FName FSequencerFilterBase< InFilterType >::GetIconName () const inline override private virtual
Hide behind private to force use of GetIcon() instead.
Definition at line 135 of file SequencerFilterBase.h.
References FName.
GetSequencer()
template<typename InFilterType> ISequencer & FSequencerFilterBase< InFilterType >::GetSequencer () const inline
Definition at line 87 of file SequencerFilterBase.h.
References FilterInterface.
GetToggleCommand()
template<typename InFilterType> virtual TSharedPtr< FUICommandInfo > FSequencerFilterBase< InFilterType >::GetToggleCommand () const inline virtual
Reimplemented in FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_Condition, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_Group, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Level, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Particle, FSequencerTrackFilter_Selected, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeDilation, FSequencerTrackFilter_TimeWarp, FSequencerTrackFilter_Unbound, UE::SequenceNavigator::FNavigationToolFilter_CustomText, UE::SequenceNavigator::FNavigationToolFilter_Dirty, UE::SequenceNavigator::FNavigationToolFilter_Marks, UE::SequenceNavigator::FNavigationToolFilter_Playhead, UE::SequenceNavigator::FNavigationToolFilter_Sequence, UE::SequenceNavigator::FNavigationToolFilter_Track, and UE::SequenceNavigator::FNavigationToolFilter_Unbound.
Definition at line 103 of file SequencerFilterBase.h.
Referenced by BindCommands(), and GetToolTipText().
GetToolTipText()
template<typename InFilterType> virtual FText FSequencerFilterBase< InFilterType >::GetToolTipText () const inline override virtual
Reimplemented in FSequencerTrackFilter_HideIsolate, FSequencerTrackFilter_Level, UE::SequenceNavigator::FNavigationToolFilter_CustomText, and UE::SequenceNavigator::FNavigationToolFilter_Text.
Definition at line 65 of file SequencerFilterBase.h.
References BuildTooltipTextForCommand(), GetDefaultToolTipText(), and GetToggleCommand().
IsCustomTextFilter()
template<typename InFilterType> virtual bool FSequencerFilterBase< InFilterType >::IsCustomTextFilter () const inline virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolFilter_CustomText.
Definition at line 93 of file SequencerFilterBase.h.
IsInverseFilter()
template<typename InFilterType> virtual bool FSequencerFilterBase< InFilterType >::IsInverseFilter () const inline override virtual
Definition at line 81 of file SequencerFilterBase.h.
LoadSettings()
template<typename InFilterType> virtual void FSequencerFilterBase< InFilterType >::LoadSettings (const FString & InIniFilename, const FString & InIniSection, const FString & InSettingsString) inline override virtual
Definition at line 79 of file SequencerFilterBase.h.
MapToggleAction()
template<typename InFilterType> void FSequencerFilterBase< InFilterType >::MapToggleAction (const TSharedPtr< FUICommandInfo > & InCommand) inline protected
Definition at line 121 of file SequencerFilterBase.h.
References CanToggleFilter(), FilterInterface, and ToggleFilter().
Referenced by BindCommands().
ModifyContextMenu()
template<typename InFilterType> virtual void FSequencerFilterBase< InFilterType >::ModifyContextMenu (FMenuBuilder & MenuBuilder) inline override virtual
Definition at line 76 of file SequencerFilterBase.h.
PassesFilter()
template<typename InFilterType> virtual bool FSequencerFilterBase< InFilterType >::PassesFilter (InFilterType InItem) const inline override virtual
Reimplemented in FSequencerTrackFilter_ClassType< InClassType >, FSequencerTrackFilter_ClassType< UMovieSceneAudioTrack >, FSequencerTrackFilter_ClassType< UMovieSceneCameraCutTrack >, FSequencerTrackFilter_ClassType< UMovieSceneCinematicShotTrack >, FSequencerTrackFilter_ClassType< UMovieSceneDataLayerTrack >, FSequencerTrackFilter_ClassType< UMovieSceneEventTrack >, FSequencerTrackFilter_ClassType< UMovieSceneFadeTrack >, FSequencerTrackFilter_ClassType< UMovieSceneLevelVisibilityTrack >, FSequencerTrackFilter_ClassType< UMovieSceneParticleTrack >, FSequencerTrackFilter_ClassType< UMovieSceneSlomoTrack >, FSequencerTrackFilter_ClassType< UMovieSceneSubTrack >, FSequencerTrackFilter_ComponentType< InComponentType >, FSequencerTrackFilter_ComponentType< UCameraComponent >, FSequencerTrackFilter_ComponentType< ULightComponentBase >, FSequencerTrackFilter_ComponentType< USkeletalMeshComponent >, FSequencerTrackFilter_Condition, FSequencerTrackFilter_Group, FSequencerTrackFilter_HideIsolate, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Level, FSequencerTrackFilter_ModelType< InModelType >, FSequencerTrackFilter_ModelType< UE::Sequencer::FFolderModel >, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Selected, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeWarp, and FSequencerTrackFilter_Unbound.
Definition at line 58 of file SequencerFilterBase.h.
SaveSettings()
template<typename InFilterType> virtual void FSequencerFilterBase< InFilterType >::SaveSettings (const FString & InIniFilename, const FString & InIniSection, const FString & InSettingsString) const inline override virtual
Definition at line 78 of file SequencerFilterBase.h.
SupportsDaySequence()
template<typename InFilterType> bool FSequencerFilterBase< InFilterType >::SupportsDaySequence (UMovieSceneSequence *const InSequence) inline static
Definition at line 33 of file SequencerFilterBase.h.
References UObjectBase::GetClass(), UStruct::IsChildOf(), and TEXT.
SupportsLevelSequence()
template<typename InFilterType> bool FSequencerFilterBase< InFilterType >::SupportsLevelSequence (UMovieSceneSequence *const InSequence) inline static
Definition at line 17 of file SequencerFilterBase.h.
References UObjectBase::GetClass(), UStruct::IsChildOf(), and TEXT.
SupportsSequence()
template<typename InFilterType> virtual bool FSequencerFilterBase< InFilterType >::SupportsSequence (UMovieSceneSequence *const InSequence) const inline virtual
Reimplemented in FSequencerTrackFilter, FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Particle, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, FSequencerTrackFilter_TimeDilation, UE::SequenceNavigator::FNavigationToolFilter_Sequence, and UE::SequenceNavigator::FNavigationToolFilter_Track.
Definition at line 118 of file SequencerFilterBase.h.
SupportsUMGSequence()
template<typename InFilterType> bool FSequencerFilterBase< InFilterType >::SupportsUMGSequence (UMovieSceneSequence *const InSequence) inline static
Definition at line 25 of file SequencerFilterBase.h.
References UObjectBase::GetClass(), UStruct::IsChildOf(), and TEXT.
ToggleFilter()
template<typename InFilterType> void FSequencerFilterBase< InFilterType >::ToggleFilter () inline
Definition at line 111 of file SequencerFilterBase.h.
References FilterInterface, and GetDisplayName().
Referenced by MapToggleAction().
Field Documentation
FilterInterface
template<typename InFilterType> ISequencerFilterBar& FSequencerFilterBase< InFilterType >::FilterInterface protected
Definition at line 130 of file SequencerFilterBase.h.
Referenced by FSequencerFilterBase(), CanToggleFilter(), GetFilterInterface(), GetSequencer(), MapToggleAction(), and ToggleFilter().
The documentation for this class was generated from the following file:
SequencerFilterBase.h