Unreal Engine 5.6 C++ API: IDisplayClusterCallbacks Class Reference
IDisplayClusterCallbacks Class Reference abstract
DisplayCluster callbacks API.
#include "IDisplayClusterCallbacks.h"
Public Member Functions
virtual ~IDisplayClusterCallbacks ()=default
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterCustomPresentSetEvent)
Callback triggered when custom present handler was created.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterEndSceneEvent)
Called on end scene.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterEndSessionEvent)
Called on session end.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterPostTickEvent)
Called on DisplayCluster PostTick.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterPresentationPostSynchronization_RHIThread)
Called after presentation synchronization is completed.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterPresentationPreSynchronization_RHIThread)
Called before presentation synchronization is initiated.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterPreTickEvent)
Called on DisplayCluster PreTick.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterStartSceneEvent)
Called on start scene.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterStartSessionEvent)
Called on session start.
DECLARE_EVENT (IDisplayClusterCallbacks, FDisplayClusterTickEvent)
Called on DisplayCluster Tick.
DECLARE_EVENT_FiveParams (IDisplayClusterCallbacks, FDisplayClusterPostTonemapPass_RenderThread, FRDGBuilder &, const IDisplayClusterViewportProxy *, const FSceneView &, const FPostProcessMaterialInputs &, const uint32)
Called after tonemap pass (before applying OCIO transformation)
DECLARE_EVENT_FourParams (IDisplayClusterCallbacks, FDisplayClusterPreProcessIcvfx_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportProxy *, FDisplayClusterShaderParameters_WarpBlend &, FDisplayClusterShaderParameters_ICVFX &)
Called before applying ICVFX shaders.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterEndFrameEvent, uint64)
Called on DisplayCluster EndFrame.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterFailoverNodeDown, const FString &)
Notifies about cluster node failure.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterFailoverPrimaryNodeChanged, const FString &)
Notifies about new primary node.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterFramePresentated_RHIThread, bool bNativePresent)
Called after frame presentation.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterPreSubmitViewFamilies, TArray< FSceneViewFamilyContext * > &)
Callback triggered before submitting view families to render.
DECLARE_EVENT_OneParam (IDisplayClusterCallbacks, FDisplayClusterStartFrameEvent, uint64)
Called on DisplayCluster StartFrame.
DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks, FDisplayClusterPostBackbufferUpdate_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *, FViewport *)
(deprecated) Called after backbuffer update
DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks, FDisplayClusterPostCrossGpuTransfer_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *, FViewport *)
Called after inter-GPU synchronization.
DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks, FDisplayClusterPostFrameRender_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *, FViewport *)
Called in the end of the nD rendering chain, right before updating the backbuffer.
DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks, FDisplayClusterPostRenderViewFamily_RenderThread, FRDGBuilder &, const FSceneViewFamily &, const IDisplayClusterViewportProxy *)
Called once the ViewFamily of this viewport is rendered.
DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks, FDisplayClusterProcessLatency_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *, FViewport *)
Called to let the artificial latency subsystem do its job.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPassthroughMediaCapture_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *)
Called to process passthrough media capture.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPassthroughMediaInput_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *)
Called to process passthrough media input.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPostBackbufferUpdated_RenderThread, FRHICommandListImmediate &, FViewport *)
Called after backbuffer update.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPostWarp_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *)
Called once after warping all the viewports.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPostWarpViewport_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportProxy *)
Called after warping a specific viewport.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPreWarp_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportManagerProxy *)
Called once before warping all available viewports.
DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks, FDisplayClusterPreWarpViewport_RenderThread, FRHICommandListImmediate &, const IDisplayClusterViewportProxy *)
Called before warping a specific viewport.
DECLARE_MULTICAST_DELEGATE_TwoParams (FDisplayClusterUpdateViewportMediaState, IDisplayClusterViewport *, EDisplayClusterViewportMediaState &)
The viewport can be used by external media, which affects the internal logic of the viewport.
virtual FDisplayClusterCustomPresentSetEvent & OnDisplayClusterCustomPresentSet ()=0
virtual FDisplayClusterEndFrameEvent & OnDisplayClusterEndFrame ()=0
virtual FDisplayClusterEndSceneEvent & OnDisplayClusterEndScene ()=0
virtual FDisplayClusterEndSessionEvent & OnDisplayClusterEndSession ()=0
virtual FDisplayClusterFailoverNodeDown & OnDisplayClusterFailoverNodeDown ()=0
virtual FDisplayClusterFailoverPrimaryNodeChanged & OnDisplayClusterFailoverPrimaryNodeChanged ()=0
virtual FDisplayClusterFramePresentated_RHIThread & OnDisplayClusterFramePresented_RHIThread ()=0
virtual FDisplayClusterPassthroughMediaCapture_RenderThread & OnDisplayClusterPassthroughMediaCapture_RenderThread ()=0
virtual FDisplayClusterPassthroughMediaInput_RenderThread & OnDisplayClusterPassthroughMediaInput_RenderThread ()=0
virtual FDisplayClusterPostBackbufferUpdated_RenderThread & OnDisplayClusterPostBackbufferUpdated_RenderThread ()=0
virtual FDisplayClusterPostCrossGpuTransfer_RenderThread & OnDisplayClusterPostCrossGpuTransfer_RenderThread ()=0
virtual FDisplayClusterPostFrameRender_RenderThread & OnDisplayClusterPostFrameRender_RenderThread ()=0
virtual FDisplayClusterPostRenderViewFamily_RenderThread & OnDisplayClusterPostRenderViewFamily_RenderThread ()=0
virtual FDisplayClusterPostTickEvent & OnDisplayClusterPostTick ()=0
virtual FDisplayClusterPostTonemapPass_RenderThread & OnDisplayClusterPostTonemapPass_RenderThread ()=0
virtual FDisplayClusterPostWarp_RenderThread & OnDisplayClusterPostWarp_RenderThread ()=0
virtual FDisplayClusterPostWarpViewport_RenderThread & OnDisplayClusterPostWarpViewport_RenderThread ()=0
virtual FDisplayClusterPreProcessIcvfx_RenderThread & OnDisplayClusterPreProcessIcvfx_RenderThread ()=0
virtual FDisplayClusterPresentationPostSynchronization_RHIThread & OnDisplayClusterPresentationPostSynchronization_RHIThread ()=0
virtual FDisplayClusterPresentationPreSynchronization_RHIThread & OnDisplayClusterPresentationPreSynchronization_RHIThread ()=0
virtual FDisplayClusterPreSubmitViewFamilies & OnDisplayClusterPreSubmitViewFamilies ()=0
virtual FDisplayClusterPreTickEvent & OnDisplayClusterPreTick ()=0
virtual FDisplayClusterPreWarp_RenderThread & OnDisplayClusterPreWarp_RenderThread ()=0
virtual FDisplayClusterPreWarpViewport_RenderThread & OnDisplayClusterPreWarpViewport_RenderThread ()=0
virtual FDisplayClusterProcessLatency_RenderThread & OnDisplayClusterProcessLatency_RenderThread ()=0
virtual FDisplayClusterStartFrameEvent & OnDisplayClusterStartFrame ()=0
virtual FDisplayClusterStartSceneEvent & OnDisplayClusterStartScene ()=0
virtual FDisplayClusterStartSessionEvent & OnDisplayClusterStartSession ()=0
virtual FDisplayClusterTickEvent & OnDisplayClusterTick ()=0
virtual FDisplayClusterUpdateViewportMediaState & OnDisplayClusterUpdateViewportMediaState ()=0
UE_DEPRECATED (5.2, "This event getter has been deprecated. Please use OnDisplayClusterPostBackbufferUpdated_RenderThread()") virtual FDisplayClusterPostBackbufferUpdate_RenderThread &OnDisplayClusterPostBackbufferUpdate_RenderThread()=0
Detailed Description
DisplayCluster callbacks API.
Definition at line 28 of file IDisplayClusterCallbacks.h.
Constructor & Destructor Documentation
~IDisplayClusterCallbacks()
virtual IDisplayClusterCallbacks::~IDisplayClusterCallbacks () virtual default
Member Function Documentation
DECLARE_EVENT() [1/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterCustomPresentSetEvent)
Callback triggered when custom present handler was created.
DECLARE_EVENT() [2/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterEndSceneEvent)
Called on end scene.
DECLARE_EVENT() [3/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterEndSessionEvent)
Called on session end.
DECLARE_EVENT() [4/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterPostTickEvent)
Called on DisplayCluster PostTick.
DECLARE_EVENT() [5/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterPresentationPostSynchronization_RHIThread)
Called after presentation synchronization is completed.
DECLARE_EVENT() [6/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterPresentationPreSynchronization_RHIThread)
Called before presentation synchronization is initiated.
DECLARE_EVENT() [7/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterPreTickEvent)
Called on DisplayCluster PreTick.
DECLARE_EVENT() [8/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterStartSceneEvent)
Called on start scene.
DECLARE_EVENT() [9/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterStartSessionEvent)
Called on session start.
DECLARE_EVENT() [10/10]
IDisplayClusterCallbacks::DECLARE_EVENT (IDisplayClusterCallbacks , FDisplayClusterTickEvent)
Called on DisplayCluster Tick.
DECLARE_EVENT_FiveParams()
IDisplayClusterCallbacks::DECLARE_EVENT_FiveParams (IDisplayClusterCallbacks , FDisplayClusterPostTonemapPass_RenderThread , FRDGBuilder & , const IDisplayClusterViewportProxy * , const FSceneView & , const FPostProcessMaterialInputs & , const uint32)
Called after tonemap pass (before applying OCIO transformation)
DECLARE_EVENT_FourParams()
IDisplayClusterCallbacks::DECLARE_EVENT_FourParams (IDisplayClusterCallbacks , FDisplayClusterPreProcessIcvfx_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportProxy * , FDisplayClusterShaderParameters_WarpBlend & , FDisplayClusterShaderParameters_ICVFX &)
Called before applying ICVFX shaders.
References DECLARE_EVENT_FourParams().
Referenced by DECLARE_EVENT_FourParams().
DECLARE_EVENT_OneParam() [1/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterEndFrameEvent , uint64)
Called on DisplayCluster EndFrame.
DECLARE_EVENT_OneParam() [2/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterFailoverNodeDown , const FString &)
Notifies about cluster node failure.
Called from AnyThread.
DECLARE_EVENT_OneParam() [3/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterFailoverPrimaryNodeChanged , const FString &)
Notifies about new primary node.
Called from AnyThread.
DECLARE_EVENT_OneParam() [4/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterFramePresentated_RHIThread , bool bNativePresent)
Called after frame presentation.
DECLARE_EVENT_OneParam() [5/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterPreSubmitViewFamilies , TArray< FSceneViewFamilyContext * > &)
Callback triggered before submitting view families to render.
DECLARE_EVENT_OneParam() [6/6]
IDisplayClusterCallbacks::DECLARE_EVENT_OneParam (IDisplayClusterCallbacks , FDisplayClusterStartFrameEvent , uint64)
Called on DisplayCluster StartFrame.
DECLARE_EVENT_ThreeParams() [1/5]
IDisplayClusterCallbacks::DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks , FDisplayClusterPostBackbufferUpdate_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy * , FViewport *)
(deprecated) Called after backbuffer update
DECLARE_EVENT_ThreeParams() [2/5]
IDisplayClusterCallbacks::DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks , FDisplayClusterPostCrossGpuTransfer_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy * , FViewport *)
Called after inter-GPU synchronization.
DECLARE_EVENT_ThreeParams() [3/5]
IDisplayClusterCallbacks::DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks , FDisplayClusterPostFrameRender_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy * , FViewport *)
Called in the end of the nD rendering chain, right before updating the backbuffer.
DECLARE_EVENT_ThreeParams() [4/5]
IDisplayClusterCallbacks::DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks , FDisplayClusterPostRenderViewFamily_RenderThread , FRDGBuilder & , const FSceneViewFamily & , const IDisplayClusterViewportProxy *)
Called once the ViewFamily of this viewport is rendered.
DECLARE_EVENT_ThreeParams() [5/5]
IDisplayClusterCallbacks::DECLARE_EVENT_ThreeParams (IDisplayClusterCallbacks , FDisplayClusterProcessLatency_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy * , FViewport *)
Called to let the artificial latency subsystem do its job.
DECLARE_EVENT_TwoParams() [1/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPassthroughMediaCapture_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy *)
Called to process passthrough media capture.
DECLARE_EVENT_TwoParams() [2/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPassthroughMediaInput_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy *)
Called to process passthrough media input.
DECLARE_EVENT_TwoParams() [3/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPostBackbufferUpdated_RenderThread , FRHICommandListImmediate & , FViewport *)
Called after backbuffer update.
References DECLARE_EVENT_TwoParams().
DECLARE_EVENT_TwoParams() [4/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPostWarp_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy *)
Called once after warping all the viewports.
DECLARE_EVENT_TwoParams() [5/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPostWarpViewport_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportProxy *)
Called after warping a specific viewport.
DECLARE_EVENT_TwoParams() [6/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPreWarp_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportManagerProxy *)
Called once before warping all available viewports.
Referenced by DECLARE_EVENT_TwoParams().
DECLARE_EVENT_TwoParams() [7/7]
IDisplayClusterCallbacks::DECLARE_EVENT_TwoParams (IDisplayClusterCallbacks , FDisplayClusterPreWarpViewport_RenderThread , FRHICommandListImmediate & , const IDisplayClusterViewportProxy *)
Called before warping a specific viewport.
DECLARE_MULTICAST_DELEGATE_TwoParams()
IDisplayClusterCallbacks::DECLARE_MULTICAST_DELEGATE_TwoParams (FDisplayClusterUpdateViewportMediaState , IDisplayClusterViewport * , EDisplayClusterViewportMediaState &)
The viewport can be used by external media, which affects the internal logic of the viewport.
Media must use this callback and return their own media states for this viewport.
Parameters
InViewport - this viewport wants to know its media state.
InOutMediaState - the delegate function should raise the desired media state flags to this variable.
References DECLARE_MULTICAST_DELEGATE_TwoParams().
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams().
OnDisplayClusterCustomPresentSet()
virtual FDisplayClusterCustomPresentSetEvent & IDisplayClusterCallbacks::OnDisplayClusterCustomPresentSet () pure virtual
OnDisplayClusterEndFrame()
virtual FDisplayClusterEndFrameEvent & IDisplayClusterCallbacks::OnDisplayClusterEndFrame () pure virtual
OnDisplayClusterEndScene()
virtual FDisplayClusterEndSceneEvent & IDisplayClusterCallbacks::OnDisplayClusterEndScene () pure virtual
OnDisplayClusterEndSession()
virtual FDisplayClusterEndSessionEvent & IDisplayClusterCallbacks::OnDisplayClusterEndSession () pure virtual
OnDisplayClusterFailoverNodeDown()
virtual FDisplayClusterFailoverNodeDown & IDisplayClusterCallbacks::OnDisplayClusterFailoverNodeDown () pure virtual
OnDisplayClusterFailoverPrimaryNodeChanged()
virtual FDisplayClusterFailoverPrimaryNodeChanged & IDisplayClusterCallbacks::OnDisplayClusterFailoverPrimaryNodeChanged () pure virtual
OnDisplayClusterFramePresented_RHIThread()
virtual FDisplayClusterFramePresentated_RHIThread & IDisplayClusterCallbacks::OnDisplayClusterFramePresented_RHIThread () pure virtual
OnDisplayClusterPassthroughMediaCapture_RenderThread()
virtual FDisplayClusterPassthroughMediaCapture_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPassthroughMediaCapture_RenderThread () pure virtual
OnDisplayClusterPassthroughMediaInput_RenderThread()
virtual FDisplayClusterPassthroughMediaInput_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPassthroughMediaInput_RenderThread () pure virtual
OnDisplayClusterPostBackbufferUpdated_RenderThread()
virtual FDisplayClusterPostBackbufferUpdated_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostBackbufferUpdated_RenderThread () pure virtual
References OnDisplayClusterPostBackbufferUpdated_RenderThread().
Referenced by OnDisplayClusterPostBackbufferUpdated_RenderThread().
OnDisplayClusterPostCrossGpuTransfer_RenderThread()
virtual FDisplayClusterPostCrossGpuTransfer_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostCrossGpuTransfer_RenderThread () pure virtual
OnDisplayClusterPostFrameRender_RenderThread()
virtual FDisplayClusterPostFrameRender_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostFrameRender_RenderThread () pure virtual
OnDisplayClusterPostRenderViewFamily_RenderThread()
virtual FDisplayClusterPostRenderViewFamily_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostRenderViewFamily_RenderThread () pure virtual
OnDisplayClusterPostTick()
virtual FDisplayClusterPostTickEvent & IDisplayClusterCallbacks::OnDisplayClusterPostTick () pure virtual
OnDisplayClusterPostTonemapPass_RenderThread()
virtual FDisplayClusterPostTonemapPass_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostTonemapPass_RenderThread () pure virtual
OnDisplayClusterPostWarp_RenderThread()
virtual FDisplayClusterPostWarp_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostWarp_RenderThread () pure virtual
OnDisplayClusterPostWarpViewport_RenderThread()
virtual FDisplayClusterPostWarpViewport_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPostWarpViewport_RenderThread () pure virtual
OnDisplayClusterPreProcessIcvfx_RenderThread()
virtual FDisplayClusterPreProcessIcvfx_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPreProcessIcvfx_RenderThread () pure virtual
References OnDisplayClusterPreProcessIcvfx_RenderThread().
Referenced by OnDisplayClusterPreProcessIcvfx_RenderThread().
OnDisplayClusterPresentationPostSynchronization_RHIThread()
virtual FDisplayClusterPresentationPostSynchronization_RHIThread & IDisplayClusterCallbacks::OnDisplayClusterPresentationPostSynchronization_RHIThread () pure virtual
OnDisplayClusterPresentationPreSynchronization_RHIThread()
virtual FDisplayClusterPresentationPreSynchronization_RHIThread & IDisplayClusterCallbacks::OnDisplayClusterPresentationPreSynchronization_RHIThread () pure virtual
OnDisplayClusterPreSubmitViewFamilies()
virtual FDisplayClusterPreSubmitViewFamilies & IDisplayClusterCallbacks::OnDisplayClusterPreSubmitViewFamilies () pure virtual
OnDisplayClusterPreTick()
virtual FDisplayClusterPreTickEvent & IDisplayClusterCallbacks::OnDisplayClusterPreTick () pure virtual
OnDisplayClusterPreWarp_RenderThread()
virtual FDisplayClusterPreWarp_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPreWarp_RenderThread () pure virtual
OnDisplayClusterPreWarpViewport_RenderThread()
virtual FDisplayClusterPreWarpViewport_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterPreWarpViewport_RenderThread () pure virtual
OnDisplayClusterProcessLatency_RenderThread()
virtual FDisplayClusterProcessLatency_RenderThread & IDisplayClusterCallbacks::OnDisplayClusterProcessLatency_RenderThread () pure virtual
OnDisplayClusterStartFrame()
virtual FDisplayClusterStartFrameEvent & IDisplayClusterCallbacks::OnDisplayClusterStartFrame () pure virtual
OnDisplayClusterStartScene()
virtual FDisplayClusterStartSceneEvent & IDisplayClusterCallbacks::OnDisplayClusterStartScene () pure virtual
OnDisplayClusterStartSession()
virtual FDisplayClusterStartSessionEvent & IDisplayClusterCallbacks::OnDisplayClusterStartSession () pure virtual
OnDisplayClusterTick()
virtual FDisplayClusterTickEvent & IDisplayClusterCallbacks::OnDisplayClusterTick () pure virtual
OnDisplayClusterUpdateViewportMediaState()
virtual FDisplayClusterUpdateViewportMediaState & IDisplayClusterCallbacks::OnDisplayClusterUpdateViewportMediaState () pure virtual
References OnDisplayClusterUpdateViewportMediaState().
Referenced by OnDisplayClusterUpdateViewportMediaState().
UE_DEPRECATED()
IDisplayClusterCallbacks::UE_DEPRECATED (5. 2, "This event getter has been deprecated. Please use OnDisplayClusterPostBackbufferUpdated_RenderThread()") & pure virtual
The documentation for this class was generated from the following file:
IDisplayClusterCallbacks.h