Unreal Engine 5.6 C++ API: SharedPointer.h File Reference
SharedPointer.h File Reference
#include "CoreTypes.h"
#include "Misc/IntrusiveUnsetOptionalState.h"
#include "Templates/PointerIsConvertibleFromTo.h"
#include "Misc/AssertionMacros.h"
#include "HAL/UnrealMemory.h"
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "CoreGlobals.h"
#include "Templates/SharedPointerInternals.h"
#include "Templates/SharedPointerTesting.inl"
Data Structures
struct TCallTraits< TSharedPtr< ObjectType, Mode > >
struct TCallTraits< TSharedRef< ObjectType, Mode > >
struct TCallTraits< TWeakPtr< ObjectType, Mode > >
struct TIsWeakPointerType< TWeakPtr< T, Mode > >
struct TIsZeroConstructType< TSharedPtr< ObjectType, Mode > >
struct TIsZeroConstructType< TWeakPtr< T, Mode > >
class TSharedFromThis< ObjectType, Mode >
Derive your class from TSharedFromThis to enable access to a TSharedRef directly from an object instance that's already been allocated.
class TSharedPtr< ObjectType, InMode >
TSharedPtr is a non-intrusive reference-counted authoritative object pointer.
class TSharedRef< ObjectType, InMode >
TSharedRef is a non-nullable, non-intrusive reference-counted authoritative object reference.
class TWeakPtr< ObjectType, InMode >
TWeakPtr is a non-intrusive reference-counted weak object pointer.
Namespaces
namespace Freeze
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Functions
template<class Type>
FORCEINLINE void CleanupPointerArray (TArray< TWeakPtr< Type > > &PointerArray)
Given a TArray of TWeakPtr's, will remove any invalid pointers.
template<class KeyType, class ValueType>
FORCEINLINE void CleanupPointerMap (TMap< TWeakPtr< KeyType >, ValueType > &PointerMap)
Given a TMap of TWeakPtr's, will remove any invalid pointers.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TSharedPtr< CastToType, Mode > ConstCastSharedPtr (TSharedPtr< CastFromType, Mode > const &InSharedPtr)
Casts a 'const' shared pointer to 'mutable' shared pointer.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TSharedRef< CastToType, Mode > ConstCastSharedRef (TSharedRef< CastFromType, Mode > const &InSharedRef)
Casts a 'const' shared reference to 'mutable' shared reference.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TWeakPtr< CastToType, Mode > ConstCastWeakPtr (TWeakPtr< CastFromType, Mode > const &InWeakPtr)
Casts a 'const' weak pointer to 'mutable' weak pointer.
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< class ObjectType, ESPMode Mode >),(TSharedPtr< ObjectType, Mode >))
template<typename ObjectType, ESPMode Mode>
uint32 GetTypeHash (const TSharedPtr< ObjectType, Mode > &InSharedPtr)
Computes a hash code for this object.
template<typename ObjectType, ESPMode Mode>
uint32 GetTypeHash (const TSharedRef< ObjectType, Mode > &InSharedRef)
Computes a hash code for this object.
template<typename ObjectType, ESPMode Mode>
uint32 GetTypeHash (const TWeakPtr< ObjectType, Mode > &InWeakPtr)
Computes a hash code for this object.
template<class ObjectType, ESPMode Mode>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSharedPtr< ObjectType, Mode > &Object, const FTypeLayoutDesc &)
template<class ObjectType>
FORCEINLINE SharedPointerInternals::TRawPtrProxy< ObjectType > MakeShareable (ObjectType *InObject)
MakeShareable utility function.
template<class ObjectType, class DeleterType>
FORCEINLINE SharedPointerInternals::TRawPtrProxyWithDeleter< ObjectType, DeleterType > MakeShareable (ObjectType *InObject, DeleterType &&InDeleter)
MakeShareable utility function.
template<typename InObjectType, ESPMode InMode = ESPMode::ThreadSafe, typename... InArgTypes>
FORCEINLINE TSharedRef< InObjectType, InMode > MakeShared (InArgTypes &&... Args)
MakeShared utility function.
template<typename ObjectType, ESPMode Mode>
FORCEINLINE TSharedRef< ObjectType, Mode > UE::Core::Private::MakeSharedRef (ObjectType *InObject, SharedPointerInternals::TReferenceControllerBase< Mode > *InSharedReferenceCount)
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global inequality operator for TSharedPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TYPE_OF_NULLPTR)
Global inequality operator for TSharedPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeB, Mode > const &InSharedPtr, TSharedRef< ObjectTypeA, Mode > const &InSharedRef)
Tests to see if a TSharedRef is not "equal" to a TSharedPtr (shared pointer is invalid, or both refer to different objects) (reverse)
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const &InSharedRef, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtr)
Tests to see if a TSharedRef is not "equal" to a TSharedPtr (shared pointer is invalid, or both refer to different objects)
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const &InSharedRefA, TSharedRef< ObjectTypeB, Mode > const &InSharedRefB)
Global inequality operator for TSharedRef.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const &InSharedRefA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TSharedRef< ObjectTypeB, Mode > const &InSharedRefB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global inequality operator for TWeakPtr.
template<class ObjectTypeA, ESPMode Mode>
FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TYPE_OF_NULLPTR)
Global inequality operator for TWeakPtr.
template<class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global inequality operator for TSharedPtr.
template<class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global inequality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global equality operator for TSharedPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, ESPMode Mode>
FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const &InSharedPtrA, TYPE_OF_NULLPTR)
Global equality operator for TSharedPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedPtr< ObjectTypeB, Mode > const &InSharedPtr, TSharedRef< ObjectTypeA, Mode > const &InSharedRef)
Tests to see if a TSharedRef is "equal" to a TSharedPtr (both are valid and refer to the same object) (reverse)
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const &InSharedRef, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtr)
Tests to see if a TSharedRef is "equal" to a TSharedPtr (both are valid and refer to the same object)
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const &InSharedRefA, TSharedRef< ObjectTypeB, Mode > const &InSharedRefB)
Global equality operator for TSharedRef.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const &InSharedRefA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TSharedRef< ObjectTypeB, Mode > const &InSharedRefB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class ObjectTypeA, ESPMode Mode>
FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const &InWeakPtrA, TYPE_OF_NULLPTR)
Global equality operator for TWeakPtr.
template<class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, TSharedPtr< ObjectTypeB, Mode > const &InSharedPtrB)
Global equality operator for TSharedPtr.
template<class ObjectTypeB, ESPMode Mode>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, TWeakPtr< ObjectTypeB, Mode > const &InWeakPtrB)
Global equality operator for TWeakPtr.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TSharedPtr< CastToType, Mode > StaticCastSharedPtr (TSharedPtr< CastFromType, Mode > const &InSharedPtr)
Casts a shared pointer of one type to another type.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TSharedRef< CastToType, Mode > StaticCastSharedRef (TSharedRef< CastFromType, Mode > const &InSharedRef)
SharedPointer - Unreal smart pointer library.
template<class CastToType, class CastFromType, ESPMode Mode>
FORCEINLINE TWeakPtr< CastToType, Mode > StaticCastWeakPtr (TWeakPtr< CastFromType, Mode > const &InWeakPtr)
Casts a weak pointer of one type to another type.
Variables
template<typename T>
constexpr bool TIsTSharedPtr_V = false
Trait which determines whether or not a type is a TSharedPtr.
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedPtr_V< const TSharedPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedPtr_V< const volatile TSharedPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedPtr_V< TSharedPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedPtr_V< volatile TSharedPtr< ObjectType, InMode > > = true
template<typename T>
constexpr bool TIsTSharedRef_V = false
Trait which determines whether or not a type is a TSharedRef.
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedRef_V< const TSharedRef< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedRef_V< const volatile TSharedRef< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedRef_V< TSharedRef< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTSharedRef_V< volatile TSharedRef< ObjectType, InMode > > = true
template<typename T>
constexpr bool TIsTWeakPtr_V = false
Trait which determines whether or not a type is a TWeakPtr.
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTWeakPtr_V< const TWeakPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTWeakPtr_V< const volatile TWeakPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTWeakPtr_V< TWeakPtr< ObjectType, InMode > > = true
template<class ObjectType, ESPMode InMode>
constexpr bool TIsTWeakPtr_V< volatile TWeakPtr< ObjectType, InMode > > = true
Function Documentation
CleanupPointerArray()
template<class Type> FORCEINLINE void CleanupPointerArray (TArray< TWeakPtr< Type > > & PointerArray)
Given a TArray of TWeakPtr's, will remove any invalid pointers.
Parameters
PointerArray The pointer array to prune invalid pointers out of
Definition at line 2264 of file SharedPointer.h.
References TArray< InElementType, InAllocatorType >::Add(), FORCEINLINE, and IsValid().
CleanupPointerMap()
template<class KeyType, class ValueType> FORCEINLINE void CleanupPointerMap (TMap< TWeakPtr< KeyType >, ValueType > & PointerMap)
Given a TMap of TWeakPtr's, will remove any invalid pointers.
Not the most efficient.
Parameters
PointerMap The pointer map to prune invalid pointers out of
Definition at line 2283 of file SharedPointer.h.
References FORCEINLINE, TWeakPtr< ObjectType, InMode >::IsValid(), and NewMap.
ConstCastSharedPtr()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TSharedPtr< CastToType, Mode > ConstCastSharedPtr (TSharedPtr< CastFromType, Mode > const & InSharedPtr) nodiscard
Casts a 'const' shared pointer to 'mutable' shared pointer.
(const_cast)
Parameters
InSharedPtr The shared pointer to cast
Definition at line 2165 of file SharedPointer.h.
References FORCEINLINE.
ConstCastSharedRef()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TSharedRef< CastToType, Mode > ConstCastSharedRef (TSharedRef< CastFromType, Mode > const & InSharedRef) nodiscard
Casts a 'const' shared reference to 'mutable' shared reference.
(const_cast)
Parameters
InSharedRef The shared reference to cast
Definition at line 2153 of file SharedPointer.h.
References FORCEINLINE.
Referenced by UE::Sequencer::ITrackLaneWidget::AsWidget(), and FRigVMNewEditor::GetHostingApp().
ConstCastWeakPtr()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TWeakPtr< CastToType, Mode > ConstCastWeakPtr (TWeakPtr< CastFromType, Mode > const & InWeakPtr) nodiscard
Casts a 'const' weak pointer to 'mutable' weak pointer.
(const_cast)
Parameters
InWeakPtr The weak pointer to cast
Definition at line 2177 of file SharedPointer.h.
References FORCEINLINE.
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< class ObjectType, ESPMode Mode >) , (TSharedPtr< ObjectType, Mode >))
GetTypeHash() [1/3]
template<typename ObjectType, ESPMode Mode> uint32 GetTypeHash (const TSharedPtr< ObjectType, Mode > & InSharedPtr) nodiscard
Computes a hash code for this object.
Parameters
InSharedPtr Shared pointer to compute hash code for
Returns
Hash code value
Definition at line 2318 of file SharedPointer.h.
References TSharedPtr< ObjectType, InMode >::Get().
GetTypeHash() [2/3]
template<typename ObjectType, ESPMode Mode> uint32 GetTypeHash (const TSharedRef< ObjectType, Mode > & InSharedRef) nodiscard
Computes a hash code for this object.
Parameters
InSharedRef Shared pointer to compute hash code for
Returns
Hash code value
Definition at line 2305 of file SharedPointer.h.
References TSharedRef< ObjectType, InMode >::Get().
GetTypeHash() [3/3]
template<typename ObjectType, ESPMode Mode> uint32 GetTypeHash (const TWeakPtr< ObjectType, Mode > & InWeakPtr) nodiscard
Computes a hash code for this object.
Parameters
InWeakPtr Weak pointer to compute hash code for
Returns
Hash code value
Definition at line 2331 of file SharedPointer.h.
References TWeakPtr< ObjectType, InMode >::GetWeakPtrTypeHash().
MakeShareable() [1/2]
template<class ObjectType> FORCEINLINE SharedPointerInternals::TRawPtrProxy< ObjectType > MakeShareable (ObjectType * InObject) nodiscard
MakeShareable utility function.
Wrap object pointers with MakeShareable to allow them to be implicitly converted to shared pointers! This is useful in assignment operations, or when returning a shared pointer from a function.
Definition at line 2190 of file SharedPointer.h.
References checkf, FORCEINLINE, IsDerivedFromSharedFromThis(), and TEXT.
Referenced by FGlobalTabmanager::FGlobalTabmanager(), FProxyTabmanager::FProxyTabmanager(), FRigVMFunctionArgument::FRigVMFunctionArgument(), TAllocRecordingLog< FModifier, FAllocOp >::TAllocRecordingLog(), SNumericEntryBox< NumericType >::Construct(), FBlueprintCompileReinstancer::Create(), FDefaultLayoutBlock::Create(), FDefaultLayoutBlock::Create(), FFbxErrorToken::Create(), FPropertyPath::Create(), FStructSharedMemory::Create(), FWidgetLayoutBlock::Create(), FWidgetLayoutBlock::Create(), FCommonAnalogCursor::CreateAnalogCursor(), FStructSharedMemory::CreateArgs(), FPropertyPath::CreateEmpty(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), FPropertyPath::ExtendPath(), FPropertyPath::ExtendPath(), FEditorViewportTypeDefinition::FromType(), FLightWeightInstanceSubsystem::Get(), FFeedbackContext::GetScopeStackSharedPtr(), FDisplayedBoneMappingInfo::Make(), FRigVMVariableMappingInfo::Make(), FTabPayload_UObject::Make(), Metasound::MakeDataChannel(), FBlueprintMemberReferenceDetails::MakeInstance(), FBlueprintMemberReferenceDetails::MakeInstance(), FClothCreateSettingsCustomization::MakeInstance(), FRigVMCommentNodeDetailCustomization::MakeInstance(), FRigVMGraphEnumDetailCustomization::MakeInstance(), FRigVMGraphMathTypeDetailCustomization::MakeInstance(), FRigVMLocalVariableDetailCustomization::MakeInstance(), FRigVMVariantDetailCustomization::MakeInstance(), FSkinWeightImportOptionsCustomization::MakeInstance(), GenericApplication::MakeWindow(), FActorDragDropGraphEdOp::New(), FBoneDragDropOp::New(), FClassDragDropOp::New(), FExportTextDragDropOp::New(), FGlobalTabmanager::New(), FGraphSchemaActionDragDropAction::New(), FKismetVariableDragDropAction::New(), FLevelDragDropOp::New(), FLevelDragDropOp::New(), FSocketDragDropOp::New(), FTabManager::New(), FTabManager::NewArea(), FTabManager::NewArea(), FSceneViewExtensions::NewExtension(), FTabManager::NewLayout(), FTabManager::NewPrimaryArea(), FTabManager::NewSplitter(), FTabManager::NewStack(), operator<<(), TCommands< CommandContextType >::Register(), TTypeContainer< Mode >::RegisterClass(), TTypeContainer< Mode >::RegisterDelegate(), TTypeContainer< Mode >::RegisterFactory(), TTypeContainer< Mode >::RegisterFactory(), TTypeContainer< Mode >::RegisterInstance(), FEditorModeRegistry::RegisterMode(), FNavigationQueryFilter::SetFilterImplementation(), FNavigationQueryFilter::SetFilterType(), FPropertyPath::TrimPath(), and FPropertyPath::TrimRoot().
MakeShareable() [2/2]
template<class ObjectType, class DeleterType> FORCEINLINE SharedPointerInternals::TRawPtrProxyWithDeleter< ObjectType, DeleterType > MakeShareable (ObjectType * InObject, DeleterType && InDeleter) nodiscard
MakeShareable utility function.
Wrap object pointers with MakeShareable to allow them to be implicitly converted to shared pointers! This is useful in assignment operations, or when returning a shared pointer from a function.
Definition at line 2214 of file SharedPointer.h.
References checkf, FORCEINLINE, Forward(), IsDerivedFromSharedFromThis(), and TEXT.
MakeShared()
template<typename InObjectType, ESPMode InMode = ESPMode::ThreadSafe, typename... InArgTypes> FORCEINLINE TSharedRef< InObjectType, InMode > MakeShared (InArgTypes &&... Args) nodiscard
MakeShared utility function.
Allocates a new ObjectType and reference controller in a single memory block. Equivalent to std::make_shared.
NOTE: If the constructor is private/protected you will need to utilize a private token. Do not make SharedPointerInternals::TIntrusiveReferenceController a friend.
class FMyType
{
private:
    struct FPrivateToken { explicit FPrivateToken() = default; };
public:
    // This has an equivalent access level to a private constructor,
    // as only friends of FMyType will have access to FPrivateToken,
    // but MakeShared can legally call it since it's public.
    explicit FMyType(FPrivateToken, int32 Int, float Real, const TCHAR* String);
};
// Won't compile if the caller doesn't have access to FMyType::FPrivateToken
TSharedPtr<FMyType> Val = MakeShared<FMyType>(FMyType::FPrivateToken{}, 5, 3.14f, TEXT("Banana"));
Definition at line 2252 of file SharedPointer.h.
References FORCEINLINE, Forward(), SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::GetObjectPtr(), UE::Core::Private::MakeSharedRef(), and SharedPointerInternals::NewIntrusiveReferenceController().
Referenced by Metasound::Frontend::FAccessPoint::FAccessPoint(), Metasound::Frontend::FAccessPoint::FAccessPoint(), FCanvasTileRendererItem::FCanvasTileRendererItem(), FCanvasTriangleRendererItem::FCanvasTriangleRendererItem(), FDetailsViewObjectFilter::FDetailsViewObjectFilter(), FInstancedStaticMeshComponentHelper::FDummyStaticMeshInstanceBuffer::FDummyStaticMeshInstanceBuffer(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), FInputActionUnifiedDelegate::FInputActionUnifiedDelegate(), HarmonixMetasound::Analysis::FMidiClockSongPositionHistory::FMidiClockSongPositionHistory(), Metasound::FNodeFacade::FNodeFacade(), Metasound::FNodeFacade::FNodeFacade(), Metasound::FNodeFacade::FNodeFacade(), UE::Tasks::FPipe::FPipe(), FShaderCommonCompileJob::FShaderCommonCompileJob(), FSlateCachedClipState::FSlateCachedClipState(), UE::Insights::FTableCellValue::FTableCellValue(), UE::Tasks::FTaskConcurrencyLimiter::FTaskConcurrencyLimiter(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode(), UE::Geometry::TBackgroundModelingComputeSource< UE::Geometry::FDynamicMeshOperator, UE::Geometry::IDynamicMeshOperatorFactory >::TBackgroundModelingComputeSource(), Metasound::TDataReference< DataType >::TDataReference(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::TInputUnifiedDelegate(), Metasound::TNodeFacade< TArrayNumOperator< ArrayType > >::TNodeFacade(), UE::Anim::TOptionalScopedGraphMessage< TGraphMessageType >::TOptionalScopedGraphMessage(), Metasound::TOutputNode< DataType, VertexAccess >::TOutputNode(), TPromise< ResultType >::TPromise(), TPromise< ResultType >::TPromise(), UE::Anim::TScopedGraphMessage< TGraphMessageType >::TScopedGraphMessage(), TSlateDecl< WidgetType, RequiredArgsPayloadType >::TSlateDecl(), Metasound::TVariableNode< DataType >::TVariableNode(), Metasound::TVariableNode< DataType >::TVariableNode(), UE::Geometry::TSpatialPhotoSet< FVector4f, float >::Add(), UE::SequenceNavigator::FNavigationToolColumnExtender::AddColumn(), UE::SequenceNavigator::FNavigationToolItemDragDropOp::AddDropHandler(), UE::Sequencer::FDynamicExtensionContainer::AddDynamicExtension(), UE::MovieScene::IEntitySystemScheduler::AddMemberFunctionTask(), TSlateBaseNamedArgs< InWidgetType >::AddMetaData(), TSlateBaseNamedArgs< InWidgetType >::AddMetaData(), UE::MovieScene::IEntitySystemScheduler::AddTask(), TLocalWorkQueue< TaskType >::AddWorkers(), FToolCommandChangeSequence::AppendChange(), UE::AnimNext::FEvaluationProgram::AppendTask(), FInputActionUnifiedDelegate::BindDelegate(), FInputActionUnifiedDelegate::BindDelegate(), FInputActionUnifiedDelegate::BindDelegate(), FInputActionUnifiedDelegate::BindDelegate(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::BindDelegate(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::BindDelegate(), UE::Insights::FFilter::BuildFilterState(), UE::Insights::FFilter::BuildFilterState(), FShapedTextCache::Create(), TAnimatedAttribute< NumericType >::Create(), ILiveLinkProvider::CreateLiveLinkProvider(), Metasound::Frontend::TBoundAnalyzerOutput< DataType >::CreateOutputData(), FText::CreateTextGenerator(), FMediaTrackEditor::CreateTrackEditor(), FTimeWarpTrackEditor::CreateTrackEditor(), TAnimatedAttribute< NumericType >::CreateWithGetter(), TAnimatedAttribute< NumericType >::CreateWithGetter(), UE::SequenceNavigator::TNavigationToolItemProxyDefaultFactoryBase< InItemProxyType, InItemProxyPriority, typename >::DefaultCreateItemProxy(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), TPerlinNoiseChannelInterface< ChannelContainerType >::ExtendSectionMenu_Raw(), TPerlinNoiseChannelInterface< ChannelContainerType >::ExtendSidebarMenu_Raw(), UE::SequenceNavigator::INavigationTool::FindOrAdd(), FStreamableHandle::FindOrAddContextData(), FRPCDoSDetection::FindOrAddRPCTracking(), FSuspensionFactory::GenerateNetData(), FSuspensionSimModule::GenerateNetData(), UE::AnimNext::FExecutionContext::GetComponent(), FInputActionUnifiedDelegate::GetDelegateForManualSet(), TInputUnifiedDelegate< DelegateType, DynamicDelegateType >::GetDelegateForManualSet(), FInputActionUnifiedDelegate::GetDelegateWithKeyForManualSet(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::GetEnumDataTypeInterface(), FSceneViewFamily::GetOrCreateExtentionData(), UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateGroupManager(), UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateStorage(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::GetPreAnimatedStateStorage(), FQuartzTickableObject::GetQuartzSubscriber(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes(), FQuartzTickableObject::Init(), UE::PixelStreaming::IsDecoderSupported(), UE::PixelStreaming::IsEncoderSupported(), UE::PixelStreaming2::IsHardwareDecoderSupported(), UE::PixelStreaming2::IsHardwareEncoderSupported(), UE::PixelStreaming2::IsSoftwareDecoderSupported(), UE::PixelStreaming2::IsSoftwareEncoderSupported(), UE::MovieScene::MakeChannelProxy(), FFontFaceData::MakeFontFaceData(), FFontFaceData::MakeFontFaceData(), FNavigationElement::MakeFromUObject_DEPRECATED(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::MakeInitialValueProcessor(), UE::AnimNext::MakeInjectionRequest(), FFrameNumberDetailsCustomization::MakeInstance(), FFrameNumberDetailsCustomization::MakeInstance(), FMediaIOVideoTimecodeConfigurationCustomization::MakeInstance(), FMovieSceneSectionDetailsCustomization::MakeInstance(), Metasound::MakeOperatorFactoryRef(), MakeTraitEvent(), FWorkspaceItem::NewGroup(), FWorkspaceItem::NewGroup(), FWorkspaceItem::NewGroup(), FWorkspaceItem::NewGroup(), UE::SequenceNavigator::INavigationTool::NewItemAction(), FStringTable::NewStringTable(), FStringTableEntry::NewStringTableEntry(), SRigVMActionMenu::OnGetActionList(), UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Push(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), UE::SequenceNavigator::FNavigationToolItemProxyRegistry::RegisterItemProxyFactory(), UE::Sequencer::ISequencerCoreModule::RegisterModelType(), UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl(), FSlateStyleSet::Set(), UE::Net::TStructNetTokenDataStoreHelper< T >::SetupReplayExportGroup(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), UE::Insights::STableTreeView::StartTableDataTask(), HarmonixMetasound::Analysis::FMidiClockSongPositionHistory::UpdateMaps(), USTRUCT(), and UE::Tasks::WaitAny().
operator!=() [1/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global inequality operator for TSharedPtr.
Returns
True if the two shared pointers are not equal
Definition at line 1877 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::Get().
operator!=() [2/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ptr are not equal
Definition at line 2093 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator!=() [3/13]
template<class ObjectTypeA, ESPMode Mode> FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TYPE_OF_NULLPTR) nodiscard
Global inequality operator for TSharedPtr.
Returns
True if the shared pointer is not null
Definition at line 1889 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::IsValid().
operator!=() [4/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedPtr< ObjectTypeB, Mode > const & InSharedPtr, TSharedRef< ObjectTypeA, Mode > const & InSharedRef) nodiscard
Tests to see if a TSharedRef is not "equal" to a TSharedPtr (shared pointer is invalid, or both refer to different objects) (reverse)
Returns
True if the shared reference and shared pointer are not "equal"
Definition at line 1949 of file SharedPointer.h.
References FORCEINLINE.
operator!=() [5/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const & InSharedRef, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtr) nodiscard
Tests to see if a TSharedRef is not "equal" to a TSharedPtr (shared pointer is invalid, or both refer to different objects)
Returns
True if the shared reference and shared pointer are not "equal"
Definition at line 1925 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), TSharedRef< ObjectType, InMode >::Get(), and TSharedPtr< ObjectType, InMode >::IsValid().
operator!=() [6/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const & InSharedRefA, TSharedRef< ObjectTypeB, Mode > const & InSharedRefB) nodiscard
Global inequality operator for TSharedRef.
Returns
True if the two shared references are not equal
Definition at line 1829 of file SharedPointer.h.
References FORCEINLINE, and TSharedRef< ObjectType, InMode >::Get().
operator!=() [7/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TSharedRef< ObjectTypeA, Mode > const & InSharedRefA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ref are not equal
Definition at line 2081 of file SharedPointer.h.
References FORCEINLINE, TSharedRef< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator!=() [8/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ptr are not equal
Definition at line 2069 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator!=() [9/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TSharedRef< ObjectTypeB, Mode > const & InSharedRefB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ref are not equal
Definition at line 2057 of file SharedPointer.h.
References FORCEINLINE, TSharedRef< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator!=() [10/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global inequality operator for TWeakPtr.
Returns
True if the two weak pointers are not equal
Definition at line 2045 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::Pin().
operator!=() [11/13]
template<class ObjectTypeA, ESPMode Mode> FORCEINLINE bool operator!= (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TYPE_OF_NULLPTR) nodiscard
Global inequality operator for TWeakPtr.
Returns
True if the weak pointer is not null
Definition at line 2105 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::IsValid().
operator!=() [12/13]
template<class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global inequality operator for TSharedPtr.
Returns
True if the shared pointer is not null
Definition at line 1901 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::IsValid().
operator!=() [13/13]
template<class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global inequality operator for TWeakPtr.
Returns
True if the weak pointer is not null
Definition at line 2117 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::IsValid().
operator==() [1/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global equality operator for TSharedPtr.
Returns
True if the two shared pointers are equal
Definition at line 1841 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::Get().
operator==() [2/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ptr are equal
Definition at line 2009 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator==() [3/13]
template<class ObjectTypeA, ESPMode Mode> FORCEINLINE bool operator== (TSharedPtr< ObjectTypeA, Mode > const & InSharedPtrA, TYPE_OF_NULLPTR) nodiscard
Global equality operator for TSharedPtr.
Returns
True if the shared pointer is null
Definition at line 1853 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::IsValid().
operator==() [4/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedPtr< ObjectTypeB, Mode > const & InSharedPtr, TSharedRef< ObjectTypeA, Mode > const & InSharedRef) nodiscard
Tests to see if a TSharedRef is "equal" to a TSharedPtr (both are valid and refer to the same object) (reverse)
Returns
True if the shared reference and shared pointer are "equal"
Definition at line 1937 of file SharedPointer.h.
References FORCEINLINE.
operator==() [5/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const & InSharedRef, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtr) nodiscard
Tests to see if a TSharedRef is "equal" to a TSharedPtr (both are valid and refer to the same object)
Returns
True if the shared reference and shared pointer are "equal"
Definition at line 1913 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), TSharedRef< ObjectType, InMode >::Get(), and TSharedPtr< ObjectType, InMode >::IsValid().
operator==() [6/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const & InSharedRefA, TSharedRef< ObjectTypeB, Mode > const & InSharedRefB) nodiscard
Global equality operator for TSharedRef.
Returns
True if the two shared references are equal
Definition at line 1817 of file SharedPointer.h.
References FORCEINLINE, and TSharedRef< ObjectType, InMode >::Get().
operator==() [7/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TSharedRef< ObjectTypeA, Mode > const & InSharedRefA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ref are equal
Definition at line 1997 of file SharedPointer.h.
References FORCEINLINE, TSharedRef< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator==() [8/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ptr are equal
Definition at line 1985 of file SharedPointer.h.
References FORCEINLINE, TSharedPtr< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator==() [9/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TSharedRef< ObjectTypeB, Mode > const & InSharedRefB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer and the shared ref are equal
Definition at line 1973 of file SharedPointer.h.
References FORCEINLINE, TSharedRef< ObjectType, InMode >::Get(), and TWeakPtr< ObjectType, InMode >::Pin().
operator==() [10/13]
template<class ObjectTypeA, class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the two weak pointers are equal
Definition at line 1961 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::Pin().
operator==() [11/13]
template<class ObjectTypeA, ESPMode Mode> FORCEINLINE bool operator== (TWeakPtr< ObjectTypeA, Mode > const & InWeakPtrA, TYPE_OF_NULLPTR) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer is null
Definition at line 2021 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::IsValid().
operator==() [12/13]
template<class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , TSharedPtr< ObjectTypeB, Mode > const & InSharedPtrB) nodiscard
Global equality operator for TSharedPtr.
Returns
True if the shared pointer is null
Definition at line 1865 of file SharedPointer.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::IsValid().
operator==() [13/13]
template<class ObjectTypeB, ESPMode Mode> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , TWeakPtr< ObjectTypeB, Mode > const & InWeakPtrB) nodiscard
Global equality operator for TWeakPtr.
Returns
True if the weak pointer is null
Definition at line 2033 of file SharedPointer.h.
References FORCEINLINE, and TWeakPtr< ObjectType, InMode >::IsValid().
StaticCastSharedPtr()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TSharedPtr< CastToType, Mode > StaticCastSharedPtr (TSharedPtr< CastFromType, Mode > const & InSharedPtr) nodiscard
Casts a shared pointer of one type to another type.
(static_cast) Useful for down-casting.
Parameters
InSharedPtr The shared pointer to cast
Definition at line 2129 of file SharedPointer.h.
References FORCEINLINE.
Referenced by FTabPayload_UObject::CastChecked(), FStreamableHandle::FindFirstContextDataOfType(), UE::MovieScene::FPreAnimatedStateExtension::FindGroupManager(), UE::SequenceNavigator::INavigationTool::FindOrAdd(), UE::MovieScene::FPreAnimatedStateExtension::FindStorage(), FStreamableHandle::GetContextDataOfType(), TTypeContainer< Mode >::GetInstance(), TTypeContainer< Mode >::TThreadInstanceProvider< T >::GetInstance(), UE::MovieScene::FPreAnimatedStateExtension::GetOrCreateGroupManager(), UE::SequenceNavigator::INavigationTool::GetOrCreateItemProxy(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetShared(), FCompositeDragDropOp::GetSubOp(), FCompositeDragDropOp::GetSubOp(), UE::Insights::FTableCellValue::GetText(), UE::Insights::SUntypedTableTreeView::GetUntypedTable(), TCommands< CommandContextType >::Register(), FCompositeDragDropOp::ResetToDefaultToolTip(), FArguments< ItemType >::SetOwnerTableView(), SNumericEntryBox< NumericType >::SupportsKeyboardFocus(), and UE::Anim::FMessageStack::TopMessageWeakPtr().
StaticCastSharedRef()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TSharedRef< CastToType, Mode > StaticCastSharedRef (TSharedRef< CastFromType, Mode > const & InSharedRef) nodiscard
SharedPointer - Unreal smart pointer library.
This is a smart pointer library consisting of shared references (TSharedRef), shared pointers (TSharedPtr), weak pointers (TWeakPtr) as well as related helper functions and classes. This implementation is modeled after the C++0x standard library's shared_ptr as well as Boost smart pointers.
Benefits of using shared references and pointers:
Clean syntax.  You can copy, dereference and compare shared pointers just like regular C++ pointers.
Prevents memory leaks.  Resources are destroyed automatically when there are no more shared references.
Weak referencing.  Weak pointers allow you to safely check when an object has been destroyed.
Thread safety.  Includes "thread safe" version that can be safely accessed from multiple threads.
Ubiquitous.  You can create shared pointers to virtually *any* type of object.
Runtime safety.  Shared references are never null and can always be dereferenced.
No reference cycles.  Use weak pointers to break reference cycles.
Confers intent.  You can easily tell an object *owner* from an *observer*.
Performance.  Shared pointers have minimal overhead.  All operations are constant-time.
Robust features.  Supports 'const', forward declarations to incomplete types, type-casting, etc.
Memory.  Only twice the size of a C++ pointer in 64-bit (plus a shared 16-byte reference controller.)
This library contains the following smart pointers:
TSharedRef - Non-nullable, reference counted non-intrusive authoritative smart pointer
TSharedPtr - Reference counted non-intrusive authoritative smart pointer
TWeakPtr - Reference counted non-intrusive weak pointer reference
Additionally, the following helper classes and functions are defined:
MakeShareable() - Used to initialize shared pointers from C++ pointers (enables implicit conversion)
MakeShared<T>(...) - Used to construct a T alongside its controller, saving an allocation.
TSharedFromThis - You can derive your own class from this to acquire a TSharedRef from "this"
StaticCastSharedRef() - Static cast utility function, typically used to downcast to a derived type.
ConstCastSharedRef() - Converts a 'const' reference to 'mutable' smart reference
StaticCastSharedPtr() - Dynamic cast utility function, typically used to downcast to a derived type.
ConstCastSharedPtr() - Converts a 'const' smart pointer to 'mutable' smart pointer
StaticCastWeakPtr() - Dynamic cast utility function, typically used to downcast to a derived type.
ConstCastWeakPtr() - Converts a 'const' smart pointer to 'mutable' smart pointer
Examples:
Please see 'SharedPointerTesting.inl' for various examples of shared pointers and references!
Tips:
Use TSharedRef instead of TSharedPtr whenever possible – it can never be nullptr!
You can call TSharedPtr::Reset() to release a reference to your object (and potentially deallocate)
Use the MakeShareable() helper function to implicitly convert to TSharedRefs or TSharedPtrs
Prefer MakeShared<T>(...) to MakeShareable(new T(...))
You can never reset a TSharedRef or assign it to nullptr, but you can assign it a new object
Shared pointers assume ownership of objects – no need to call delete yourself!
Usually you should "operator new" when passing a C++ pointer to a new shared pointer
Use TSharedRef or TSharedPtr when passing smart pointers as function parameters, not TWeakPtr
The "thread-safe" versions of smart pointers are a bit slower – only use them when needed
You can forward declare shared pointers to incomplete types, just how you'd expect to!
Shared pointers of compatible types will be converted implicitly (e.g. upcasting)
You can create a typedef to TSharedRef< MyClass > to make it easier to type
For best performance, minimize calls to TWeakPtr::Pin (or conversions to TSharedRef/TSharedPtr)
Your class can return itself as a shared reference if you derive from TSharedFromThis
To downcast a pointer to a derived object class, use the StaticCastSharedRef, StaticCastSharedRef or StaticCastWeakPtr functions
'const' objects are fully supported with shared pointers!
You can make a 'const' pointer mutable using the ConstCastSharedRef, ConstCastSharedPtr or ConstCastWeakPtr functions
Limitations:
- Shared pointers are not compatible with Unreal objects (UObject classes)!
- Currently only types with that have regular destructors (no custom deleters)
- Dynamically-allocated arrays are not supported yet (e.g. MakeShareable(new int32[20]))
Differences from other implementations (e.g. boost:shared_ptr, std::shared_ptr):
- Type names and method names are more consistent with Unreal's codebase
- You must use Pin() to convert weak pointers to shared pointers (no explicit constructor)
- Thread-safety features are optional instead of forced
- TSharedFromThis returns a shared *reference*, not a shared *pointer*
- Some features were omitted (e.g. use_count(), unique(), etc.)
- No exceptions are allowed (all related features have been omitted)
- Custom allocators and custom delete functions are not supported yet
- Our implementation supports non-nullable smart pointers (TSharedRef)
- Several other new features added, such as MakeShareable and nullptr assignment
Why did we write our own Unreal shared pointer instead of using available alternatives?
- std::shared_ptr (and even tr1::shared_ptr) is not yet available on all platforms
- Allows for a more consistent implementation on all compilers and platforms
- Can work seamlessly with other Unreal containers and types
- Better control over platform specifics, including threading and optimizations
- We want thread-safety features to be optional (for performance)
- We've added our own improvements (MakeShareable, assign to nullptr, etc.)
- Exceptions were not needed nor desired in our implementation
- We wanted more control over performance (inlining, memory, use of virtuals, etc.)
- Potentially easier to debug (liberal code comments, etc.)
- Prefer not to introduce new third party dependencies when not needed
Casts a shared reference of one type to another type. (static_cast) Useful for down-casting.
Parameters
InSharedRef The shared reference to cast
Definition at line 126 of file SharedPointer.h.
References FORCEINLINE.
Referenced by UE::Core::Private::TPtrVariantBase< BaseType, true >::TPtrVariantBase(), UE::MovieScene::FPlaybackCapabilities::AddCapabilityShared(), FCommonNativeListItem::AsTypedItem(), STreeView< FRigVMSearchResult >::GenerateNewWidget(), SWidget::GetAllMetaData(), SWidget::GetMetaData(), AudioWidgets::FAudioMeter::GetWidget(), FTabPayload_UObject::IsEqual(), FArguments< ItemType >::OnMouseButtonUp(), UE::MovieScene::FPlaybackCapabilities::OverwriteCapabilityShared(), FRigVMNewEditor::SharedRef(), FRigVMNewEditor::SharedRef(), TSharedFromThis< ObjectType, Mode >::SharedThis(), TSharedFromThis< ObjectType, Mode >::SharedThis(), TWidgetFactory< UUserWidget >::TakeAndCacheRow(), and TWidgetFactory< UUserWidget >::TakeAndCacheWidget().
StaticCastWeakPtr()
template<class CastToType, class CastFromType, ESPMode Mode> FORCEINLINE TWeakPtr< CastToType, Mode > StaticCastWeakPtr (TWeakPtr< CastFromType, Mode > const & InWeakPtr) nodiscard
Casts a weak pointer of one type to another type.
(static_cast) Useful for down-casting.
Parameters
InWeakPtr The weak pointer to cast
Definition at line 2141 of file SharedPointer.h.
References FORCEINLINE.
Variable Documentation
TIsTSharedPtr_V
template<typename T> bool TIsTSharedPtr_V = false constexpr
Trait which determines whether or not a type is a TSharedPtr.
Definition at line 1209 of file SharedPointer.h.
Referenced by TStrongPtrVariant< BaseType >::Get(), and TStrongPtrVariant< BaseType >::ToWeakVariant().
TIsTSharedPtr_V< const TSharedPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedPtr_V< const TSharedPtr< ObjectType, InMode > > = true constexpr
Definition at line 1211 of file SharedPointer.h.
TIsTSharedPtr_V< const volatile TSharedPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedPtr_V< const volatile TSharedPtr< ObjectType, InMode > > = true constexpr
Definition at line 1213 of file SharedPointer.h.
TIsTSharedPtr_V< TSharedPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedPtr_V< TSharedPtr< ObjectType, InMode > > = true constexpr
Definition at line 1210 of file SharedPointer.h.
TIsTSharedPtr_V< volatile TSharedPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedPtr_V< volatile TSharedPtr< ObjectType, InMode > > = true constexpr
Definition at line 1212 of file SharedPointer.h.
TIsTSharedRef_V
template<typename T> bool TIsTSharedRef_V = false constexpr
Trait which determines whether or not a type is a TSharedRef.
Definition at line 646 of file SharedPointer.h.
TIsTSharedRef_V< const TSharedRef< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedRef_V< const TSharedRef< ObjectType, InMode > > = true constexpr
Definition at line 648 of file SharedPointer.h.
TIsTSharedRef_V< const volatile TSharedRef< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedRef_V< const volatile TSharedRef< ObjectType, InMode > > = true constexpr
Definition at line 650 of file SharedPointer.h.
TIsTSharedRef_V< TSharedRef< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedRef_V< TSharedRef< ObjectType, InMode > > = true constexpr
Definition at line 647 of file SharedPointer.h.
TIsTSharedRef_V< volatile TSharedRef< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTSharedRef_V< volatile TSharedRef< ObjectType, InMode > > = true constexpr
Definition at line 649 of file SharedPointer.h.
TIsTWeakPtr_V
template<typename T> bool TIsTWeakPtr_V = false constexpr
Trait which determines whether or not a type is a TWeakPtr.
Definition at line 1548 of file SharedPointer.h.
Referenced by TWeakPtrVariant< BaseType >::Pin().
TIsTWeakPtr_V< const TWeakPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTWeakPtr_V< const TWeakPtr< ObjectType, InMode > > = true constexpr
Definition at line 1550 of file SharedPointer.h.
TIsTWeakPtr_V< const volatile TWeakPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTWeakPtr_V< const volatile TWeakPtr< ObjectType, InMode > > = true constexpr
Definition at line 1552 of file SharedPointer.h.
TIsTWeakPtr_V< TWeakPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTWeakPtr_V< TWeakPtr< ObjectType, InMode > > = true constexpr
Definition at line 1549 of file SharedPointer.h.
TIsTWeakPtr_V< volatile TWeakPtr< ObjectType, InMode > >
template<class ObjectType, ESPMode InMode> bool TIsTWeakPtr_V< volatile TWeakPtr< ObjectType, InMode > > = true constexpr
Definition at line 1551 of file SharedPointer.h.