Unreal Engine 5.6 C++ API: FShaderCompilingManager Class Reference
FShaderCompilingManager Class Reference
Manager of asynchronous and parallel shader compilation.
#include "ShaderCompiler.h"
Public Types
enum class EDumpShaderDebugInfo : int32 { Never = 0 , Always = 1 , OnError = 2 , OnErrorOrWarning = 3 }
Public Member Functions
FShaderCompilingManager ()
~FShaderCompilingManager ()
bool AllowAsynchronousShaderCompiling () const
bool AreWarningsSuppressed (const EShaderPlatform Platform) const
void CancelCompilation (const TCHAR *MaterialName, const TArray< int32 > &ShaderMapIdsToCancel)
Removes all outstanding compile jobs for the passed shader maps.
FString CreateShaderDebugInfoPath (const FShaderCompilerInput &ShaderCompilerInput) const
void FinishAllCompilation () override
Blocks until completion of all async shader compiling, and assigns shader maps to relevant materials.
void FinishCompilation (const TCHAR *MaterialName, const TArray< int32 > &ShaderMapIdsToFinishCompiling)
Blocks until completion of the requested shader maps.
const FString & GetAbsoluteShaderDebugInfoDirectory () const
EDumpShaderDebugInfo GetDumpShaderDebugInfo () const
EShaderDebugInfoFlags GetDumpShaderDebugInfoFlags () const
FShaderCompileMemoryUsage GetExternalMemoryUsage ()
Returns the current memory usage of external local compilation processes in bytes.
void GetLocalStats (FShaderCompilerStats &OutStats) const
Retrieve compiler statistics for all compilation done in this process.
int32 GetNumLocalWorkers () const
Returns the (current) number of local workers.
int32 GetNumOutstandingJobs () const
int32 GetNumPendingJobs () const
int32 GetNumRemainingJobs () const
Returns the number of outstanding compile jobs.
bool HasShaderJobs () const
return true if we have shader jobs in any state shader jobs are removed when they are applied to the gamethreadshadermap accessable from gamethread
bool IgnoreAllThrottling () const
Returns whether normal throttling settings should be ignored because shader compilation is at the moment the only action blocking the critical path.
void IncrementNumDumpedShaderSources ()
bool IsCompiling () const
Returns whether async compiling is happening.
bool IsCompilingShaderMap (uint32 Id)
bool IsExclusiveDistributedCompilingEnabled () const
Returns whether shaders are exclusively compiled through distributed controller, i.e.
bool IsRemoteCompilingEnabled () const
Returns whether remote compiling is enabled.
bool IsShaderCompilationSkipped () const
void OnDistributedShaderCompilingChanged ()
Called when CVars are changed at runtime that determine whether or not the distributed shader compiler supports local workers (e.g.
void OnMachineResourcesChanged (int32 NumberOfCores, int32 NumberOfCoresIncludingHyperthreads)
Called by external systems that have updated the number of worker threads available.
FShaderPipelineCompileJob * PreparePipelineCompileJob (uint32 Id, const FShaderPipelineCompileJobKey &Key, EShaderCompileJobPriority Priority)
FShaderCompileJob * PrepareShaderCompileJob (uint32 Id, const FShaderCompileJobKey &Key, EShaderCompileJobPriority Priority)
Prepares a job of the given type for compilation.
void PrintStats ()
Prints stats related to shader compilation to the log.
void ProcessAsyncResults (bool bLimitExecutionTime, bool bBlockOnGlobalShaderCompletion)
Version of ProcessAsyncResults that specifies use of ProcessGameThreadTargetTime for the timeslice.
void ProcessAsyncResults (float TimeSlice, bool bBlockOnGlobalShaderCompletion)
Processes completed asynchronous shader maps, and assigns them to relevant materials.
void ProcessFinishedJob (FShaderCommonCompileJob *FinishedJob, EShaderCompileJobStatus Status)
This is an entry point for all jobs that have finished the compilation.
void SetAllowForIncompleteShaderMaps (bool toggle)
void SetExternalJobs (int32 NumJobs)
bool ShouldDisplayCompilingNotification () const
Returns whether to display a notification that shader compiling is happening in the background.
bool ShouldRecompileToDumpShaderDebugInfo (const FShaderCompileJob &Job) const
bool ShouldRecompileToDumpShaderDebugInfo (const FShaderCompilerInput &Input, const FShaderCompilerOutput &Output, bool bSucceeded) const
void Shutdown () override
Shutdown the shader compiler manager, this will shutdown immediately and not process any more shader compile requests.
void SkipShaderCompilation (bool toggle)
void SubmitJobs (TArray< FShaderCommonCompileJobPtr > &NewJobs, const FString MaterialBasePath, FString PermutationString=FString(""))
Adds shader jobs to be asynchronously compiled.
void SuppressWarnings (const EShaderPlatform Platform)
UE_DEPRECATED (5.6, "ProcessFinishedJob must now be passed an EShaderCompileJobStatus") void ProcessFinishedJob(FShaderCommonCompileJob *FinishedJob)
Static Public Member Functions
static FName GetStaticAssetTypeName ()
Get the name of the asset type this compiler handles.
static bool IsShaderCompilerWorkerRunning (FProcHandle &WorkerHandle)
Returns true if the given shader compile worker is still running.
Private Member Functions
void AddCompiledResults (TMap< int32, FShaderMapFinalizeResults > &CompiledShaderMaps, int32 ShaderMapIdx, const FShaderMapFinalizeResults &Results)
Adds compiled results to the CompiledShaderMaps, merging with the existing ones as necessary.
bool AllTargetPlatformSupportsRemoteShaderCompiling ()
Checks if any target platform down't support remote shader compiling.
void BlockOnAllShaderMapCompletion (TMap< int32, FShaderMapFinalizeResults > &CompiledShaderMaps)
Blocks on completion of all shader maps.
void BlockOnShaderMapCompletion (const TArray< int32 > &ShaderMapIdsToFinishCompiling, TMap< int32, FShaderMapFinalizeResults > &CompiledShaderMaps)
Blocks on completion of the given shader maps.
void CalculateNumberOfCompilingThreads (int32 NumberOfCores, int32 NumberOfCoresIncludingHyperthreads)
Calculate NumShaderCompilingThreads, during construction or OnMachineResourcesChanged.
IDistributedBuildController * FindRemoteCompilerController () const
Returns the first remote compiler controller found.
FShaderCompileThreadRunnableBase * FindShaderCompilingThread (EShaderCompilerWorkerType InWorkerType)
Returns the shader compiling thread of the specified kind or null if there is none.
FTextFormat GetAssetNameFormat () const override
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
FName GetAssetTypeName () const override
A unique name among all asset compiling manager to identify the type of asset this manager handles.
TArrayView< FName > GetDependentTypeNames () const override
Return other asset types that should preferably be handled before this one.
int32 GetNumRemainingAssets () const override
Returns the number of remaining compilations.
bool HandlePotentialRetry (TMap< int32, FShaderMapFinalizeResults > &CompletedShaderMaps)
Recompiles shader jobs if requested (either interactively for failed jobs via msgbox in editor, or for jobs with errors/warnings due to r.DumpShaderDebugInfo=2/3), and returns true if a retry was needed.
FShaderCompileThreadRunnableBase * LaunchLocalShaderCompilingThread (bool bDelayThreadExecution=false)
Launches the thread for local shader compilation.
FShaderCompileThreadRunnableBase * LaunchRemoteShaderCompilingThread (bool bDelayThreadExecution=false)
Launches the thread for remote shader compilation.
FShaderCompileThreadRunnableBase * LaunchShaderCompilingThread (TUniquePtr< FShaderCompileThreadRunnableBase > &&NewShaderCompilingThread, bool bDelayThreadExecution=false)
Takes the ownership of the new shader compiling thread and returns its non-owning pointer.
FProcHandle LaunchWorker (const FString &WorkingDirectory, uint32 InParentProcessId, uint32 ThreadId, const FString &WorkerInputFile, const FString &WorkerOutputFile, uint32 *OutWorkerProcessId=nullptr)
Launches the worker, returns the launched process handle.
void ProcessAsyncTasks (bool bLimitExecutionTime=false) override
Called once per frame, fetches completed tasks and applies them to the scene.
void ProcessAsyncTasks (const AssetCompilation::FProcessAsyncTaskParams &Params) override
Called once per frame, fetches completed tasks and applies them to the scene.
void ProcessCompiledNiagaraShaderMaps (TMap< int32, FShaderMapFinalizeResults > &CompiledShaderMaps, float TimeBudget)
Finalizes the given Niagara shader map results and assigns the affected shader maps to Niagara scripts, while attempting to stay within an execution time budget.
void ProcessCompiledShaderMaps (TMap< int32, FShaderMapFinalizeResults > &CompiledShaderMaps, float TimeBudget)
Finalizes the given shader map results and optionally assigns the affected shader maps to materials, while attempting to stay within an execution time budget.
void PropagateMaterialChangesToPrimitives (TMap< TRefCountPtr< FMaterial >, TRefCountPtr< FMaterialShaderMap > > &MaterialsToUpdate)
Propagate the completed compile to primitives that might be using the materials compiled.
void ReleaseJob (FShaderCommonCompileJob *Job)
void ReleaseJob (FShaderCommonCompileJobPtr &Job)
void ReportMemoryUsage ()
Prints out the memory usage for shader compile worker processes, if they exist.
void UpdateNumRemainingAssets ()
Take some action whenever the number of remaining asset changes.
Private Member Functions inherited from IAssetCompilingManager
virtual void FinishCompilationForObjects (TArrayView< UObject *const > InObjects)
Blocks until completion of the requested objects.
virtual void MarkCompilationAsCanceled (TArrayView< UObject *const > InObjects)
Mark compilation of the provided objects as canceled.
virtual ~IAssetCompilingManager ()
Private Attributes
FString AbsoluteShaderBaseWorkingDirectory
Absolute version of ShaderBaseWorkingDirectory.
FString AbsoluteShaderDebugInfoDirectory
Absolute path to the directory to dump shader debug info to.
FShaderCompileJobCollection AllJobs
Collection of all outstanding jobs.
bool bAllowAsynchronousShaderCompiling
Whether to allow shaders to compile in the background or to block after each material.
bool bAllowCompilingThroughWorkers
Whether to allow compiling shaders through the worker application, which allows multiple cores to be used.
bool bAllowForIncompleteShaderMaps
If we are using ODSC (On Demand Shader Compilation) we should allow for incomplete maps to still be processed.
bool bCompilingDuringGame
Tracks whether we are compiling while the game is running.
bool bDebugBreakOnPromptToRetryShaderCompile = false
If enabled when we enter the prompt to retry we will break in the debugger if one is attached rather than prompting.
bool bIsEngineLoopInitialized
Cached Engine loop initialization state.
bool bLogJobCompletionTimes
Whether to log out shader job completion times on the worker thread.
bool bNoShaderCompilation
Opt out of material shader compilation and instead place an empty shader map.
bool bPromptToRetryFailedShaderCompiles
Whether to ask to retry a failed shader compile error.
IDistributedBuildController * BuildDistributionController = nullptr
Interface to the build distribution controller (XGE/SN-DBS)
bool bUseOnlyDistributedCompilationThread = false
Whether shaders are compiled exclusively through the distributed shader controller and no local shader compiling thread is allocated.
FCriticalSection CompileQueueSection
Critical section used to gain access to the variables above that are shared by both the main thread and the FShaderCompileThreadRunnable.
TMap< FString, FDelegateHandle > DirectoryWatcherHandles
int32 LastNumRemainingAssets = 0
Last value of GetNumRemainingAssets.
int32 MaxShaderJobBatchSize
Largest number of jobs that can be put in the same batch.
TUniquePtr< FAsyncCompilationNotification > Notification
Used to show a notification accompanying progress.
std::atomic< int32 > NumDumpedShaderSources = 0
Number of preprocessed shader sources that are dumped due to a crash of the shader compiler.
int32 NumExternalJobs
Number of jobs currently being compiled.
uint32 NumShaderCompilingThreads
Number of busy threads to use for shader compiling while loading.
uint32 NumShaderCompilingThreadsDuringGame
Number of busy threads to use for shader compiling while in game.
int32 NumSingleThreadedRunsBeforeRetry
Number of runs through single-threaded compiling before we can retry to compile through workers.
FDelegateHandle OutOfMemoryDelegateHandle
Delegate handle for delegate used to report memory usage during out-of-memory conditions.
TMap< int32, FShaderMapFinalizeResults > PendingFinalizeShaderMaps
Map from shader map id to results being finalized.
float ProcessGameThreadTargetTime
Target execution time for ProcessAsyncResults.
uint32 ProcessId
Process Id of UE.
FString ShaderBaseWorkingDirectory
Base directory where temporary files are written out during multi core shader compiling.
FString ShaderCompileWorkerName
Name of the shader worker application.
TMap< int32, FPendingShaderMapCompileResultsPtr > ShaderMapJobs
Map from shader map Id to the compile results for that map, used to gather compiled results.
uint64 SuppressedShaderPlatforms
Tracks which opt-in shader platforms have their warnings suppressed.
TArray< TUniquePtr< FShaderCompileThreadRunnableBase > > Threads
The threads spawned for shader compiling.
FString WorkerCrashLogBaseDirectory
If dumping crash logs for workers is enabled and an absolute path is used (i.e.
double WorkersBusyTime
Tracks the total time that shader compile workers have been busy since startup.
Friends
class FShaderCompileDistributedThreadRunnable_Interface
class FShaderCompileFASTBuildThreadRunnable
class FShaderCompileThreadRunnable
class FShaderCompileThreadRunnableBase
class FShaderCompileXGEThreadRunnable_XmlInterface
Detailed Description
Manager of asynchronous and parallel shader compilation.
This class contains an interface to enqueue and retreive asynchronous shader jobs, and manages a FShaderCompileThreadRunnable.
Definition at line 875 of file ShaderCompiler.h.
Member Enumeration Documentation
EDumpShaderDebugInfo
enum class FShaderCompilingManager::EDumpShaderDebugInfo : int32 strong
Enumerator
Never
Always
OnError
OnErrorOrWarning
Definition at line 1153 of file ShaderCompiler.h.
Constructor & Destructor Documentation
FShaderCompilingManager()
FShaderCompilingManager::FShaderCompilingManager ()
~FShaderCompilingManager()
FShaderCompilingManager::~FShaderCompilingManager ()
Member Function Documentation
AddCompiledResults()
void FShaderCompilingManager::AddCompiledResults (TMap< int32, FShaderMapFinalizeResults > & CompiledShaderMaps, int32 ShaderMapIdx, const FShaderMapFinalizeResults & Results) private
Adds compiled results to the CompiledShaderMaps, merging with the existing ones as necessary.
AllowAsynchronousShaderCompiling()
bool FShaderCompilingManager::AllowAsynchronousShaderCompiling () const inline
Definition at line 1079 of file ShaderCompiler.h.
References bAllowAsynchronousShaderCompiling.
AllTargetPlatformSupportsRemoteShaderCompiling()
bool FShaderCompilingManager::AllTargetPlatformSupportsRemoteShaderCompiling () private
Checks if any target platform down't support remote shader compiling.
AreWarningsSuppressed()
bool FShaderCompilingManager::AreWarningsSuppressed (const EShaderPlatform Platform) const inline
Definition at line 1178 of file ShaderCompiler.h.
References Platform, and SuppressedShaderPlatforms.
BlockOnAllShaderMapCompletion()
void FShaderCompilingManager::BlockOnAllShaderMapCompletion (TMap< int32, FShaderMapFinalizeResults > & CompiledShaderMaps) private
Blocks on completion of all shader maps.
BlockOnShaderMapCompletion()
void FShaderCompilingManager::BlockOnShaderMapCompletion (const TArray< int32 > & ShaderMapIdsToFinishCompiling, TMap< int32, FShaderMapFinalizeResults > & CompiledShaderMaps) private
Blocks on completion of the given shader maps.
CalculateNumberOfCompilingThreads()
void FShaderCompilingManager::CalculateNumberOfCompilingThreads (int32 NumberOfCores, int32 NumberOfCoresIncludingHyperthreads) private
Calculate NumShaderCompilingThreads, during construction or OnMachineResourcesChanged.
CancelCompilation()
void FShaderCompilingManager::CancelCompilation (const TCHAR * MaterialName, const TArray< int32 > & ShaderMapIdsToCancel)
Removes all outstanding compile jobs for the passed shader maps.
CreateShaderDebugInfoPath()
FString FShaderCompilingManager::CreateShaderDebugInfoPath (const FShaderCompilerInput & ShaderCompilerInput) const
FindRemoteCompilerController()
IDistributedBuildController * FShaderCompilingManager::FindRemoteCompilerController () const private
Returns the first remote compiler controller found.
FindShaderCompilingThread()
FShaderCompileThreadRunnableBase * FShaderCompilingManager::FindShaderCompilingThread (EShaderCompilerWorkerType InWorkerType) private
Returns the shader compiling thread of the specified kind or null if there is none.
References FShaderCompileThreadRunnableBase.
FinishAllCompilation()
void FShaderCompilingManager::FinishAllCompilation () override virtual
Blocks until completion of all async shader compiling, and assigns shader maps to relevant materials.
This should be called before exit if the DDC needs to be made up to date.
Implements IAssetCompilingManager.
FinishCompilation()
void FShaderCompilingManager::FinishCompilation (const TCHAR * MaterialName, const TArray< int32 > & ShaderMapIdsToFinishCompiling)
Blocks until completion of the requested shader maps.
This will not assign the shader map to any materials, the caller is responsible for that.
GetAbsoluteShaderDebugInfoDirectory()
const FString & FShaderCompilingManager::GetAbsoluteShaderDebugInfoDirectory () const inline
Definition at line 1173 of file ShaderCompiler.h.
References GetShaderDebugInfoPath().
GetAssetNameFormat()
FTextFormat FShaderCompilingManager::GetAssetNameFormat () const override private virtual
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
Note: Should be in a similar form as "{0}|plural(one=Singular Name,other=Plural Name)"
Implements IAssetCompilingManager.
GetAssetTypeName()
FName FShaderCompilingManager::GetAssetTypeName () const override private virtual
A unique name among all asset compiling manager to identify the type of asset this manager handles.
Implements IAssetCompilingManager.
GetDependentTypeNames()
TArrayView< FName > FShaderCompilingManager::GetDependentTypeNames () const override private virtual
Return other asset types that should preferably be handled before this one.
Implements IAssetCompilingManager.
GetDumpShaderDebugInfo()
EDumpShaderDebugInfo FShaderCompilingManager::GetDumpShaderDebugInfo () const
GetDumpShaderDebugInfoFlags()
EShaderDebugInfoFlags FShaderCompilingManager::GetDumpShaderDebugInfoFlags () const
GetExternalMemoryUsage()
FShaderCompileMemoryUsage FShaderCompilingManager::GetExternalMemoryUsage ()
Returns the current memory usage of external local compilation processes in bytes.
GetLocalStats()
void FShaderCompilingManager::GetLocalStats (FShaderCompilerStats & OutStats) const
Retrieve compiler statistics for all compilation done in this process.
Note that this will not include stats for any compilation that occurs in worker processes in a multiprocess cook.
GetNumLocalWorkers()
int32 FShaderCompilingManager::GetNumLocalWorkers () const inline
Returns the (current) number of local workers.
Definition at line 1143 of file ShaderCompiler.h.
References bCompilingDuringGame, NumShaderCompilingThreads, and NumShaderCompilingThreadsDuringGame.
GetNumOutstandingJobs()
int32 FShaderCompilingManager::GetNumOutstandingJobs () const
Referenced by GetNumRemainingJobs(), IsCompiling(), and ShouldDisplayCompilingNotification().
GetNumPendingJobs()
int32 FShaderCompilingManager::GetNumPendingJobs () const
Referenced by IsCompiling(), and ShouldDisplayCompilingNotification().
GetNumRemainingAssets()
int32 FShaderCompilingManager::GetNumRemainingAssets () const override private virtual
Returns the number of remaining compilations.
Implements IAssetCompilingManager.
GetNumRemainingJobs()
int32 FShaderCompilingManager::GetNumRemainingJobs () const inline
Returns the number of outstanding compile jobs.
Note: This is dependent on NumOutstandingJobs which is updated from another thread, so the results are non-deterministic.
Definition at line 1135 of file ShaderCompiler.h.
References GetNumOutstandingJobs(), and NumExternalJobs.
GetStaticAssetTypeName()
FName FShaderCompilingManager::GetStaticAssetTypeName () static
Get the name of the asset type this compiler handles.
HandlePotentialRetry()
bool FShaderCompilingManager::HandlePotentialRetry (TMap< int32, FShaderMapFinalizeResults > & CompletedShaderMaps) private
Recompiles shader jobs if requested (either interactively for failed jobs via msgbox in editor, or for jobs with errors/warnings due to r.DumpShaderDebugInfo=2/3), and returns true if a retry was needed.
HasShaderJobs()
bool FShaderCompilingManager::HasShaderJobs () const inline
return true if we have shader jobs in any state shader jobs are removed when they are applied to the gamethreadshadermap accessable from gamethread
Definition at line 1126 of file ShaderCompiler.h.
References PendingFinalizeShaderMaps, and ShaderMapJobs.
Referenced by IsCompiling().
IgnoreAllThrottling()
bool FShaderCompilingManager::IgnoreAllThrottling () const inline
Returns whether normal throttling settings should be ignored because shader compilation is at the moment the only action blocking the critical path.
An example of such situation is startup compilation of global shaders and default materials, but there may be more cases like that.
Definition at line 1116 of file ShaderCompiler.h.
References bIsEngineLoopInitialized.
IncrementNumDumpedShaderSources()
void FShaderCompilingManager::IncrementNumDumpedShaderSources () inline
Definition at line 1168 of file ShaderCompiler.h.
References NumDumpedShaderSources.
IsCompiling()
bool FShaderCompilingManager::IsCompiling () const inline
Returns whether async compiling is happening.
Note: This is dependent on NumOutstandingJobs which is updated from another thread, so the results are non-deterministic.
Definition at line 1088 of file ShaderCompiler.h.
References GetNumOutstandingJobs(), GetNumPendingJobs(), HasShaderJobs(), and NumExternalJobs.
IsCompilingShaderMap()
bool FShaderCompilingManager::IsCompilingShaderMap (uint32 Id)
IsExclusiveDistributedCompilingEnabled()
bool FShaderCompilingManager::IsExclusiveDistributedCompilingEnabled () const inline
Returns whether shaders are exclusively compiled through distributed controller, i.e.
no local shader compiling thread is allocated. If this is true, the distributed controller must not refuse job batches below a minimum threshold, otherwise those jobs will never get picked up.
Definition at line 1107 of file ShaderCompiler.h.
References bUseOnlyDistributedCompilationThread.
IsRemoteCompilingEnabled()
bool FShaderCompilingManager::IsRemoteCompilingEnabled () const inline
Returns whether remote compiling is enabled.
Otherwise, only the local machine is used for shader compilation. This depends on command line argument '-NoRemoteShaderCompile', CVar 'r.ShaderCompiler.AllowDistributedCompilation', and whether the target platform supports remote compilin; see ITargetPlatform::CanSupportRemoteShaderCompile().
Definition at line 1098 of file ShaderCompiler.h.
References BuildDistributionController.
IsShaderCompilationSkipped()
bool FShaderCompilingManager::IsShaderCompilationSkipped () const inline
Definition at line 1188 of file ShaderCompiler.h.
References bNoShaderCompilation.
IsShaderCompilerWorkerRunning()
bool FShaderCompilingManager::IsShaderCompilerWorkerRunning (FProcHandle & WorkerHandle) static
Returns true if the given shader compile worker is still running.
LaunchLocalShaderCompilingThread()
FShaderCompileThreadRunnableBase * FShaderCompilingManager::LaunchLocalShaderCompilingThread (bool bDelayThreadExecution = false) private
Launches the thread for local shader compilation.
If the distributed shader controller supports local workers, this might not be invoked until this condition changes.
References FShaderCompileThreadRunnableBase.
LaunchRemoteShaderCompilingThread()
FShaderCompileThreadRunnableBase * FShaderCompilingManager::LaunchRemoteShaderCompilingThread (bool bDelayThreadExecution = false) private
Launches the thread for remote shader compilation.
References FShaderCompileThreadRunnableBase.
LaunchShaderCompilingThread()
FShaderCompileThreadRunnableBase * FShaderCompilingManager::LaunchShaderCompilingThread (TUniquePtr< FShaderCompileThreadRunnableBase > && NewShaderCompilingThread, bool bDelayThreadExecution = false) private
Takes the ownership of the new shader compiling thread and returns its non-owning pointer.
If 'bDelayThreadExecution' is false, the thread is started immediately.
References FShaderCompileThreadRunnableBase.
LaunchWorker()
FProcHandle FShaderCompilingManager::LaunchWorker (const FString & WorkingDirectory, uint32 InParentProcessId, uint32 ThreadId, const FString & WorkerInputFile, const FString & WorkerOutputFile, uint32 * OutWorkerProcessId = nullptr) private
Launches the worker, returns the launched process handle.
OnDistributedShaderCompilingChanged()
void FShaderCompilingManager::OnDistributedShaderCompilingChanged ()
Called when CVars are changed at runtime that determine whether or not the distributed shader compiler supports local workers (e.g.
'r.XGEController.AvoidUsingLocalMachine' can be changed at runtime).
OnMachineResourcesChanged()
void FShaderCompilingManager::OnMachineResourcesChanged (int32 NumberOfCores, int32 NumberOfCoresIncludingHyperthreads)
Called by external systems that have updated the number of worker threads available.
PreparePipelineCompileJob()
FShaderPipelineCompileJob * FShaderCompilingManager::PreparePipelineCompileJob (uint32 Id, const FShaderPipelineCompileJobKey & Key, EShaderCompileJobPriority Priority)
References Key.
PrepareShaderCompileJob()
FShaderCompileJob * FShaderCompilingManager::PrepareShaderCompileJob (uint32 Id, const FShaderCompileJobKey & Key, EShaderCompileJobPriority Priority)
Prepares a job of the given type for compilation.
If a job with the given Id/Key already exists, it will attempt to adjust to the higher priority if possible, and nullptr will be returned. If a non-nullptr is returned, the given job should be filled out with relevant information, then passed to SubmitJobs() when ready
References Key.
PrintStats()
void FShaderCompilingManager::PrintStats ()
Prints stats related to shader compilation to the log.
ProcessAsyncResults() [1/2]
void FShaderCompilingManager::ProcessAsyncResults (bool bLimitExecutionTime, bool bBlockOnGlobalShaderCompletion)
Version of ProcessAsyncResults that specifies use of ProcessGameThreadTargetTime for the timeslice.
ProcessAsyncResults() [2/2]
void FShaderCompilingManager::ProcessAsyncResults (float TimeSlice, bool bBlockOnGlobalShaderCompletion)
Processes completed asynchronous shader maps, and assigns them to relevant materials.
Parameters
TimeSlice - When more than 0, ProcessAsyncResults will be bandwidth throttled by the given timeslice, to limit hitching. ProcessAsyncResults will then have to be called often to finish all shader maps (eg from Tick). Otherwise, all compiled shader maps will be processed.
bBlockOnGlobalShaderCompletion - When enabled, ProcessAsyncResults will block until global shader maps are complete. This must be done before using global shaders for rendering.
ProcessAsyncTasks() [1/2]
void FShaderCompilingManager::ProcessAsyncTasks (bool bLimitExecutionTime = false) override private virtual
Called once per frame, fetches completed tasks and applies them to the scene.
Implements IAssetCompilingManager.
ProcessAsyncTasks() [2/2]
void FShaderCompilingManager::ProcessAsyncTasks (const AssetCompilation::FProcessAsyncTaskParams & Params) override private virtual
Called once per frame, fetches completed tasks and applies them to the scene.
Reimplemented from IAssetCompilingManager.
References Params.
ProcessCompiledNiagaraShaderMaps()
void FShaderCompilingManager::ProcessCompiledNiagaraShaderMaps (TMap< int32, FShaderMapFinalizeResults > & CompiledShaderMaps, float TimeBudget) private
Finalizes the given Niagara shader map results and assigns the affected shader maps to Niagara scripts, while attempting to stay within an execution time budget.
ProcessCompiledShaderMaps()
void FShaderCompilingManager::ProcessCompiledShaderMaps (TMap< int32, FShaderMapFinalizeResults > & CompiledShaderMaps, float TimeBudget) private
Finalizes the given shader map results and optionally assigns the affected shader maps to materials, while attempting to stay within an execution time budget.
ProcessFinishedJob()
void FShaderCompilingManager::ProcessFinishedJob (FShaderCommonCompileJob * FinishedJob, EShaderCompileJobStatus Status)
This is an entry point for all jobs that have finished the compilation.
Can be called from multiple threads.
Referenced by UE_DEPRECATED().
PropagateMaterialChangesToPrimitives()
void FShaderCompilingManager::PropagateMaterialChangesToPrimitives (TMap< TRefCountPtr< FMaterial >, TRefCountPtr< FMaterialShaderMap > > & MaterialsToUpdate) private
Propagate the completed compile to primitives that might be using the materials compiled.
ReleaseJob() [1/2]
void FShaderCompilingManager::ReleaseJob (FShaderCommonCompileJob * Job) private
ReleaseJob() [2/2]
void FShaderCompilingManager::ReleaseJob (FShaderCommonCompileJobPtr & Job) private
ReportMemoryUsage()
void FShaderCompilingManager::ReportMemoryUsage () private
Prints out the memory usage for shader compile worker processes, if they exist.
SetAllowForIncompleteShaderMaps()
void FShaderCompilingManager::SetAllowForIncompleteShaderMaps (bool toggle) inline
Definition at line 1201 of file ShaderCompiler.h.
References bAllowForIncompleteShaderMaps.
SetExternalJobs()
void FShaderCompilingManager::SetExternalJobs (int32 NumJobs) inline
Definition at line 1148 of file ShaderCompiler.h.
References NumExternalJobs.
ShouldDisplayCompilingNotification()
bool FShaderCompilingManager::ShouldDisplayCompilingNotification () const inline
Returns whether to display a notification that shader compiling is happening in the background.
Note: This is dependent on NumOutstandingJobs which is updated from another thread, so the results are non-deterministic.
Definition at line 1073 of file ShaderCompiler.h.
References GetNumOutstandingJobs(), GetNumPendingJobs(), and NumExternalJobs.
ShouldRecompileToDumpShaderDebugInfo() [1/2]
bool FShaderCompilingManager::ShouldRecompileToDumpShaderDebugInfo (const FShaderCompileJob & Job) const
ShouldRecompileToDumpShaderDebugInfo() [2/2]
bool FShaderCompilingManager::ShouldRecompileToDumpShaderDebugInfo (const FShaderCompilerInput & Input, const FShaderCompilerOutput & Output, bool bSucceeded) const
References Input.
Shutdown()
void FShaderCompilingManager::Shutdown () override virtual
Shutdown the shader compiler manager, this will shutdown immediately and not process any more shader compile requests.
Implements IAssetCompilingManager.
SkipShaderCompilation()
void FShaderCompilingManager::SkipShaderCompilation (bool toggle) inline
Definition at line 1193 of file ShaderCompiler.h.
References AllowShaderCompiling(), and bNoShaderCompilation.
SubmitJobs()
void FShaderCompilingManager::SubmitJobs (TArray< FShaderCommonCompileJobPtr > & NewJobs, const FString MaterialBasePath, FString PermutationString = FString(""))
Adds shader jobs to be asynchronously compiled.
FinishCompilation or ProcessAsyncResults must be used to get the results.
SuppressWarnings()
void FShaderCompilingManager::SuppressWarnings (const EShaderPlatform Platform) inline
Definition at line 1183 of file ShaderCompiler.h.
References Platform, and SuppressedShaderPlatforms.
UE_DEPRECATED()
FShaderCompilingManager::UE_DEPRECATED (5. 6, "ProcessFinishedJob must now be passed an EShaderCompileJobStatus") inline
Definition at line 1215 of file ShaderCompiler.h.
References ProcessFinishedJob().
UpdateNumRemainingAssets()
void FShaderCompilingManager::UpdateNumRemainingAssets () private
Take some action whenever the number of remaining asset changes.
Friends And Related Symbol Documentation
FShaderCompileDistributedThreadRunnable_Interface
friend class FShaderCompileDistributedThreadRunnable_Interface friend
Definition at line 883 of file ShaderCompiler.h.
References FShaderCompileDistributedThreadRunnable_Interface.
Referenced by FShaderCompileDistributedThreadRunnable_Interface.
FShaderCompileFASTBuildThreadRunnable
friend class FShaderCompileFASTBuildThreadRunnable friend
Definition at line 884 of file ShaderCompiler.h.
References FShaderCompileFASTBuildThreadRunnable.
Referenced by FShaderCompileFASTBuildThreadRunnable.
FShaderCompileThreadRunnable
friend class FShaderCompileThreadRunnable friend
Definition at line 878 of file ShaderCompiler.h.
References FShaderCompileThreadRunnable.
Referenced by FShaderCompileThreadRunnable.
FShaderCompileThreadRunnableBase
friend class FShaderCompileThreadRunnableBase friend
Definition at line 877 of file ShaderCompiler.h.
References FShaderCompileThreadRunnableBase.
Referenced by FindShaderCompilingThread(), FShaderCompileThreadRunnableBase, LaunchLocalShaderCompilingThread(), LaunchRemoteShaderCompilingThread(), and LaunchShaderCompilingThread().
FShaderCompileXGEThreadRunnable_XmlInterface
friend class FShaderCompileXGEThreadRunnable_XmlInterface friend
Definition at line 881 of file ShaderCompiler.h.
References FShaderCompileXGEThreadRunnable_XmlInterface.
Referenced by FShaderCompileXGEThreadRunnable_XmlInterface.
Field Documentation
AbsoluteShaderBaseWorkingDirectory
FString FShaderCompilingManager::AbsoluteShaderBaseWorkingDirectory private
Absolute version of ShaderBaseWorkingDirectory.
Definition at line 961 of file ShaderCompiler.h.
AbsoluteShaderDebugInfoDirectory
FString FShaderCompilingManager::AbsoluteShaderDebugInfoDirectory private
Absolute path to the directory to dump shader debug info to.
Definition at line 963 of file ShaderCompiler.h.
AllJobs
FShaderCompileJobCollection FShaderCompilingManager::AllJobs private
Collection of all outstanding jobs.
Definition at line 917 of file ShaderCompiler.h.
bAllowAsynchronousShaderCompiling
bool FShaderCompilingManager::bAllowAsynchronousShaderCompiling private
Whether to allow shaders to compile in the background or to block after each material.
Definition at line 947 of file ShaderCompiler.h.
Referenced by AllowAsynchronousShaderCompiling().
bAllowCompilingThroughWorkers
bool FShaderCompilingManager::bAllowCompilingThroughWorkers private
Whether to allow compiling shaders through the worker application, which allows multiple cores to be used.
Definition at line 945 of file ShaderCompiler.h.
bAllowForIncompleteShaderMaps
bool FShaderCompilingManager::bAllowForIncompleteShaderMaps private
If we are using ODSC (On Demand Shader Compilation) we should allow for incomplete maps to still be processed.
Definition at line 992 of file ShaderCompiler.h.
Referenced by SetAllowForIncompleteShaderMaps().
bCompilingDuringGame
bool FShaderCompilingManager::bCompilingDuringGame private
Tracks whether we are compiling while the game is running.
If true, we need to throttle down shader compiling CPU usage to avoid starving the runtime threads.
Definition at line 902 of file ShaderCompiler.h.
Referenced by GetNumLocalWorkers().
bDebugBreakOnPromptToRetryShaderCompile
bool FShaderCompilingManager::bDebugBreakOnPromptToRetryShaderCompile = false private
If enabled when we enter the prompt to retry we will break in the debugger if one is attached rather than prompting.
Definition at line 953 of file ShaderCompiler.h.
bIsEngineLoopInitialized
bool FShaderCompilingManager::bIsEngineLoopInitialized private
Cached Engine loop initialization state.
Definition at line 983 of file ShaderCompiler.h.
Referenced by IgnoreAllThrottling().
bLogJobCompletionTimes
bool FShaderCompilingManager::bLogJobCompletionTimes private
Whether to log out shader job completion times on the worker thread.
Useful for tracking down which global shader is taking a long time.
Definition at line 955 of file ShaderCompiler.h.
bNoShaderCompilation
bool FShaderCompilingManager::bNoShaderCompilation private
Opt out of material shader compilation and instead place an empty shader map.
Definition at line 989 of file ShaderCompiler.h.
Referenced by IsShaderCompilationSkipped(), and SkipShaderCompilation().
bPromptToRetryFailedShaderCompiles
bool FShaderCompilingManager::bPromptToRetryFailedShaderCompiles private
Whether to ask to retry a failed shader compile error.
Definition at line 951 of file ShaderCompiler.h.
BuildDistributionController
IDistributedBuildController* FShaderCompilingManager::BuildDistributionController = nullptr private
Interface to the build distribution controller (XGE/SN-DBS)
Definition at line 986 of file ShaderCompiler.h.
Referenced by IsRemoteCompilingEnabled().
bUseOnlyDistributedCompilationThread
bool FShaderCompilingManager::bUseOnlyDistributedCompilationThread = false private
Whether shaders are compiled exclusively through the distributed shader controller and no local shader compiling thread is allocated.
Ignored if 'bAllowCompilingThroughWorkers' is false.
Definition at line 949 of file ShaderCompiler.h.
Referenced by IsExclusiveDistributedCompilingEnabled().
CompileQueueSection
FCriticalSection FShaderCompilingManager::CompileQueueSection private
Critical section used to gain access to the variables above that are shared by both the main thread and the FShaderCompileThreadRunnable.
Definition at line 914 of file ShaderCompiler.h.
DirectoryWatcherHandles
TMap<FString, FDelegateHandle> FShaderCompilingManager::DirectoryWatcherHandles private
Definition at line 1001 of file ShaderCompiler.h.
LastNumRemainingAssets
int32 FShaderCompilingManager::LastNumRemainingAssets = 0 private
Last value of GetNumRemainingAssets.
Definition at line 967 of file ShaderCompiler.h.
MaxShaderJobBatchSize
int32 FShaderCompilingManager::MaxShaderJobBatchSize private
Largest number of jobs that can be put in the same batch.
Definition at line 936 of file ShaderCompiler.h.
Notification
TUniquePtr<FAsyncCompilationNotification> FShaderCompilingManager::Notification private
Used to show a notification accompanying progress.
Definition at line 995 of file ShaderCompiler.h.
NumDumpedShaderSources
std::atomic<int32> FShaderCompilingManager::NumDumpedShaderSources = 0 private
Number of preprocessed shader sources that are dumped due to a crash of the shader compiler.
This state is updated when a job is completed, which happens on a worker thread. The state is read on the Game Thread to see if we should dump the source to begin with.
Definition at line 941 of file ShaderCompiler.h.
Referenced by IncrementNumDumpedShaderSources().
NumExternalJobs
int32 FShaderCompilingManager::NumExternalJobs private
Number of jobs currently being compiled.
This includes CompileQueue and any jobs that have been assigned to workers but aren't complete yet.
Definition at line 908 of file ShaderCompiler.h.
Referenced by GetNumRemainingJobs(), IsCompiling(), SetExternalJobs(), and ShouldDisplayCompilingNotification().
NumShaderCompilingThreads
uint32 FShaderCompilingManager::NumShaderCompilingThreads private
Number of busy threads to use for shader compiling while loading.
Definition at line 932 of file ShaderCompiler.h.
Referenced by GetNumLocalWorkers().
NumShaderCompilingThreadsDuringGame
uint32 FShaderCompilingManager::NumShaderCompilingThreadsDuringGame private
Number of busy threads to use for shader compiling while in game.
Definition at line 934 of file ShaderCompiler.h.
Referenced by GetNumLocalWorkers().
NumSingleThreadedRunsBeforeRetry
int32 FShaderCompilingManager::NumSingleThreadedRunsBeforeRetry private
Number of runs through single-threaded compiling before we can retry to compile through workers.
-1 if not used.
Definition at line 938 of file ShaderCompiler.h.
OutOfMemoryDelegateHandle
FDelegateHandle FShaderCompilingManager::OutOfMemoryDelegateHandle private
Delegate handle for delegate used to report memory usage during out-of-memory conditions.
Definition at line 998 of file ShaderCompiler.h.
PendingFinalizeShaderMaps
TMap<int32, FShaderMapFinalizeResults> FShaderCompilingManager::PendingFinalizeShaderMaps private
Map from shader map id to results being finalized.
Used to track shader finalizations over multiple frames.
Definition at line 923 of file ShaderCompiler.h.
Referenced by HasShaderJobs().
ProcessGameThreadTargetTime
float FShaderCompilingManager::ProcessGameThreadTargetTime private
Target execution time for ProcessAsyncResults.
Larger values speed up async shader map processing but cause more hitchiness while async compiling is happening.
Definition at line 957 of file ShaderCompiler.h.
ProcessId
uint32 FShaderCompilingManager::ProcessId private
Process Id of UE.
Definition at line 943 of file ShaderCompiler.h.
ShaderBaseWorkingDirectory
FString FShaderCompilingManager::ShaderBaseWorkingDirectory private
Base directory where temporary files are written out during multi core shader compiling.
Definition at line 959 of file ShaderCompiler.h.
ShaderCompileWorkerName
FString FShaderCompilingManager::ShaderCompileWorkerName private
Name of the shader worker application.
Definition at line 965 of file ShaderCompiler.h.
ShaderMapJobs
TMap<int32, FPendingShaderMapCompileResultsPtr> FShaderCompilingManager::ShaderMapJobs private
Map from shader map Id to the compile results for that map, used to gather compiled results.
Definition at line 905 of file ShaderCompiler.h.
Referenced by HasShaderJobs().
SuppressedShaderPlatforms
uint64 FShaderCompilingManager::SuppressedShaderPlatforms private
Tracks which opt-in shader platforms have their warnings suppressed.
Definition at line 980 of file ShaderCompiler.h.
Referenced by AreWarningsSuppressed(), and SuppressWarnings().
Threads
TArray<TUniquePtr<FShaderCompileThreadRunnableBase> > FShaderCompilingManager::Threads private
The threads spawned for shader compiling.
Definition at line 926 of file ShaderCompiler.h.
WorkerCrashLogBaseDirectory
FString FShaderCompilingManager::WorkerCrashLogBaseDirectory private
If dumping crash logs for workers is enabled and an absolute path is used (i.e.
-AbsLog), this contains the base directory path.
Definition at line 969 of file ShaderCompiler.h.
WorkersBusyTime
double FShaderCompilingManager::WorkersBusyTime private
Tracks the total time that shader compile workers have been busy since startup.
Useful for profiling the shader compile worker thread time.
Definition at line 975 of file ShaderCompiler.h.
The documentation for this class was generated from the following file:
ShaderCompiler.h