Unreal Engine 5.6 C++ API: ALevelBounds Class Reference
ALevelBounds Class Reference
#include "LevelBounds.h"
Protected Member Functions
void BroadcastLevelBoundsUpdated ()
Broadcasts LevelBoundsActorUpdatedEvent in case this actor acts as a level bounds.
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual UWorld * GetTickableGameObjectWorld () const override
Used to determine the specific world this object is associated with.
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const override
Virtual that can be overloaded by the inheriting class.
virtual bool IsTickableInEditor () const override
Used to determine whether the object should be ticked in the editor when there is no gameplay world.
void OnLevelActorAddedRemoved (AActor *InActor)
Called whenever any actor added or removed.
void OnLevelActorMoved (AActor *InActor)
Called whenever any actor moved.
void SubscribeToUpdateEvents ()
Subscribes for actors transformation events.
virtual void Tick (float DeltaTime) override
FTickableGameObject interface.
void UnsubscribeFromUpdateEvents ()
Unsubscribes from actors transformation events.
void UpdateLevelBounds ()
Updates this actor bounding box by summing all level actors bounding boxes.
Protected Attributes
bool bLevelBoundsDirty
Whether currently level bounds is dirty and needs to be updated.
bool bUsingDefaultBounds
True when there are no actors contributing to the bounds and we are currently using the default bounds instead.
FDelegateHandle OnLevelActorAddedDelegateHandle
FDelegateHandle OnLevelActorDeletedDelegateHandle
FDelegateHandle OnLevelActorMovedDelegateHandle
Handles to various registered delegates.
Private Member Functions
virtual bool ActorTypeIsMainWorldOnly () const override
virtual bool CanChangeIsSpatiallyLoadedFlag () const override
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UBoxComponent > BoxComponent
Bounding box for the level bounds.
virtual FBox GetComponentsBoundingBox (bool bNonColliding=false, bool bIncludeFromChildActors=false) const override
virtual bool IsLevelBoundsRelevant () const override
bool IsUsingDefaultBounds () const
void MarkLevelBoundsDirty ()
Marks level bounds as dirty so they will be recalculated on next tick.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditMove (bool bFinished) override
virtual void PostEditUndo () override
virtual void PostLoad () override
virtual void PostRegisterAllComponents () override
virtual void PostUnregisterAllComponents () override
void UpdateLevelBoundsImmediately ()
Update level bounds immediately so the bounds are accurate when returning.
UPROPERTY () bool bAutoUpdateBounds
Whether to automatically update actor bounds based on all relevant actors bounds belonging to the same level.
Static Private Member Functions
static FBox CalculateLevelBounds (const ULevel *InLevel)
Additional Inherited Members
Public Member Functions inherited from FTickableGameObject
FTickableGameObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableGameObject ()
Removes this instance from the static array of tickable objects.
virtual bool IsTickableWhenPaused () const
Used to determine if an object should be ticked when the game is paused.
void SetTickableTickType (ETickableTickType NewTickType)
Call to modify the tickable type of this instance.
UE_NONCOPYABLE (FTickableGameObject)
Tickable objects cannot be copied safely due to the auto registration.
Public Member Functions inherited from FTickableObjectBase
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Member Functions inherited from FTickableGameObject
static void TickObjects (UWorld *World, ELevelTick LevelTickType, bool bIsPaused, float DeltaSeconds)
Tick all FTickableGameObject instances that match the parameters.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Definition at line 28 of file LevelBounds.h.
Member Function Documentation
ActorTypeIsMainWorldOnly()
virtual bool ALevelBounds::ActorTypeIsMainWorldOnly () const inline override private virtual
Definition at line 111 of file LevelBounds.h.
BroadcastLevelBoundsUpdated()
void ALevelBounds::BroadcastLevelBoundsUpdated () protected
Broadcasts LevelBoundsActorUpdatedEvent in case this actor acts as a level bounds.
CalculateLevelBounds()
FBox ALevelBounds::CalculateLevelBounds (const ULevel * InLevel) static private
Returns
Bounding box which includes all relevant actors bounding boxes belonging to specified level
CanChangeIsSpatiallyLoadedFlag()
virtual bool ALevelBounds::CanChangeIsSpatiallyLoadedFlag () const inline override private virtual
Definition at line 70 of file LevelBounds.h.
GENERATED_UCLASS_BODY()
ALevelBounds::GENERATED_UCLASS_BODY () private
Bounding box for the level bounds.
References Category, and UPROPERTY().
GetComponentsBoundingBox()
virtual FBox ALevelBounds::GetComponentsBoundingBox (bool bNonColliding = false, bool bIncludeFromChildActors = false) const override private virtual
References GetComponentsBoundingBox().
Referenced by GetComponentsBoundingBox().
GetStatId()
virtual TStatId ALevelBounds::GetStatId () const override protected virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
GetTickableGameObjectWorld()
virtual UWorld * ALevelBounds::GetTickableGameObjectWorld () const inline override protected virtual
Used to determine the specific world this object is associated with.
If this returns a valid world it will tick during that world's level tick. If this returns null, it will tick during the general engine tick after all world ticks.
Returns
the world this object is associated with, or nullptr
Reimplemented from FTickableGameObject.
Definition at line 75 of file LevelBounds.h.
GetTickableTickType()
virtual ETickableTickType ALevelBounds::GetTickableTickType () const override protected virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented from FTickableObjectBase.
IsLevelBoundsRelevant()
virtual bool ALevelBounds::IsLevelBoundsRelevant () const inline override private virtual
Definition at line 48 of file LevelBounds.h.
References IsLevelBoundsRelevant().
Referenced by IsLevelBoundsRelevant().
IsTickable()
virtual bool ALevelBounds::IsTickable () const override protected virtual
Virtual that can be overloaded by the inheriting class.
It is used to determine whether an object should be conditionally ticked.
Returns
true if object is ready to be ticked, false otherwise.
Reimplemented from FTickableObjectBase.
IsTickableInEditor()
virtual bool ALevelBounds::IsTickableInEditor () const override protected virtual
Used to determine whether the object should be ticked in the editor when there is no gameplay world.
Objects will still be ticked in Play in Editor if they are associated with a PIE world.
Returns
true if this tickable object should always be ticked in the editor, even if there is no gameplay world
Reimplemented from FTickableGameObject.
IsUsingDefaultBounds()
bool ALevelBounds::IsUsingDefaultBounds () const private
Returns
True if there were no actors contributing to bounds and we are currently using the default bounds
MarkLevelBoundsDirty()
void ALevelBounds::MarkLevelBoundsDirty () private
Marks level bounds as dirty so they will be recalculated on next tick.
OnLevelActorAddedRemoved()
void ALevelBounds::OnLevelActorAddedRemoved (AActor * InActor) protected
Called whenever any actor added or removed.
OnLevelActorMoved()
void ALevelBounds::OnLevelActorMoved (AActor * InActor) protected
Called whenever any actor moved.
PostEditChangeProperty()
virtual void ALevelBounds::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostEditMove()
virtual void ALevelBounds::PostEditMove (bool bFinished) override private virtual
PostEditUndo()
virtual void ALevelBounds::PostEditUndo () override private virtual
PostLoad()
virtual void ALevelBounds::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
PostRegisterAllComponents()
virtual void ALevelBounds::PostRegisterAllComponents () override private virtual
PostUnregisterAllComponents()
virtual void ALevelBounds::PostUnregisterAllComponents () override private virtual
SubscribeToUpdateEvents()
void ALevelBounds::SubscribeToUpdateEvents () protected
Subscribes for actors transformation events.
Tick()
virtual void ALevelBounds::Tick (float DeltaTime) override protected virtual
FTickableGameObject interface.
Implements FTickableObjectBase.
References DeltaTime.
UnsubscribeFromUpdateEvents()
void ALevelBounds::UnsubscribeFromUpdateEvents () protected
Unsubscribes from actors transformation events.
UpdateLevelBounds()
void ALevelBounds::UpdateLevelBounds () protected
Updates this actor bounding box by summing all level actors bounding boxes.
UpdateLevelBoundsImmediately()
void ALevelBounds::UpdateLevelBoundsImmediately () private
Update level bounds immediately so the bounds are accurate when returning.
Use only when needed because updating the bounds is slow
UPROPERTY()
ALevelBounds::UPROPERTY () private
Whether to automatically update actor bounds based on all relevant actors bounds belonging to the same level.
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
Field Documentation
bLevelBoundsDirty
bool ALevelBounds::bLevelBoundsDirty protected
Whether currently level bounds is dirty and needs to be updated.
Definition at line 100 of file LevelBounds.h.
bUsingDefaultBounds
bool ALevelBounds::bUsingDefaultBounds protected
True when there are no actors contributing to the bounds and we are currently using the default bounds instead.
Definition at line 103 of file LevelBounds.h.
OnLevelActorAddedDelegateHandle
FDelegateHandle ALevelBounds::OnLevelActorAddedDelegateHandle protected
Definition at line 108 of file LevelBounds.h.
OnLevelActorDeletedDelegateHandle
FDelegateHandle ALevelBounds::OnLevelActorDeletedDelegateHandle protected
Definition at line 107 of file LevelBounds.h.
OnLevelActorMovedDelegateHandle
FDelegateHandle ALevelBounds::OnLevelActorMovedDelegateHandle protected
Handles to various registered delegates.
Definition at line 106 of file LevelBounds.h.
The documentation for this class was generated from the following file:
LevelBounds.h