Unreal Engine 5.6 C++ API: SoftObjectPtr.h File Reference
SoftObjectPtr.h File Reference
#include "UObject/Object.h"
#include "Templates/Casts.h"
#include "UObject/PersistentObjectPtr.h"
#include "UObject/SoftObjectPath.h"
#include "Templates/Models.h"
#include "Concepts/EqualityComparable.h"
#include <type_traits>
Data Structures
struct FSoftObjectPtr
FSoftObjectPtr is a type of weak pointer to a UObject, that also keeps track of the path to the object on disk.
struct FSoftObjectPtrFastLess
Fast non-alphabetical order that is only stable during this process' lifetime.
struct FSoftObjectPtrLexicalLess
Slow alphabetical order that is stable / deterministic over process runs.
struct TCallTraits< TSoftClassPtr< T > >
struct TCallTraits< TSoftObjectPtr< T > >
struct TIsPODType< FSoftObjectPtr >
struct TIsPODType< TSoftClassPtr< T > >
struct TIsSoftObjectPointerType< T >
TIsSoftObjectPointerType Trait for recognizing 'soft' (path-based) object pointer types.
struct TIsSoftObjectPointerType< FSoftObjectPtr >
struct TIsSoftObjectPointerType< TSoftObjectPtr< T > >
struct TIsWeakPointerType< FSoftObjectPtr >
struct TIsWeakPointerType< TSoftClassPtr< T > >
struct TIsWeakPointerType< TSoftObjectPtr< T > >
class TSoftClassPtr< TClass >
TSoftClassPtr is a templatized wrapper around FSoftObjectPtr that works like a TSubclassOf, it can be used in UProperties for blueprint subclasses.
struct TSoftObjectPtr< T >
TSoftObjectPtr is templatized wrapper of the generic FSoftObjectPtr, it can be used in UProperties.
Macros
#define UE_DEPRECATE_SOFTOBJECTPTR_CONVERSIONS 1
#define UE_SOFTOBJECTPTR_CONVERSION_DEPRECATED(Version, Message)
Functions
template<class TClass>
FORCEINLINE uint32 GetTypeHash (const TSoftClassPtr< TClass > &Ptr)
Hash function.
template<class T>
TSoftClassPtr< std::remove_cv_t< T > > MakeSoftClassPtr (T *Object)
Utility to create a TSoftObjectPtr without specifying the type.
template<class T>
TSoftClassPtr< std::remove_cv_t< T > > MakeSoftClassPtr (TObjectPtr< T > Object)
template<class T>
TSoftObjectPtr< T > MakeSoftObjectPtr (T *Object)
Utility to create a TSoftObjectPtr without specifying the type.
template<class T>
TSoftObjectPtr< T > MakeSoftObjectPtr (TObjectPtr< T > Object)
template<class TClass>
FORCEINLINE bool operator!= (const UClass *Lhs, const TSoftClassPtr< TClass > &Rhs)
template<class TClass>
FArchive & operator<< (FArchive &Ar, TSoftClassPtr< TClass > &Ptr)
template<class TClass>
FORCEINLINE bool operator== (const UClass *Lhs, const TSoftClassPtr< TClass > &Rhs)
template<typename LhsType, typename RhsType UE_REQUIRES>
FORCEINLINE bool operator== (LhsType *Lhs, const TSoftObjectPtr< RhsType > &Rhs)
template<typename T>
TSoftObjectPtr (T *) -> TSoftObjectPtr< T >
template<typename LhsType, typename RhsType UE_REQUIRES>
UE_DEPRECATED (5.5, "Comparing TSoftObjectPtrs of incompatible pointer types has been deprecated.") FORCEINLINE bool operator
Macro Definition Documentation
UE_DEPRECATE_SOFTOBJECTPTR_CONVERSIONS
#define UE_DEPRECATE_SOFTOBJECTPTR_CONVERSIONS 1
Definition at line 19 of file SoftObjectPtr.h.
UE_SOFTOBJECTPTR_CONVERSION_DEPRECATED
#define UE_SOFTOBJECTPTR_CONVERSION_DEPRECATED (Version, Message)
Value:
UE_DEPRECATED(Version, Message)
Definition at line 22 of file SoftObjectPtr.h.
Function Documentation
GetTypeHash()
template<class TClass> FORCEINLINE uint32 GetTypeHash (const TSoftClassPtr< TClass > & Ptr) nodiscard
Hash function.
Definition at line 1075 of file SoftObjectPtr.h.
References FORCEINLINE, and TSoftClassPtr< TClass >::GetPtrTypeHash().
Referenced by TSoftClassPtr< const T >::GetPtrTypeHash(), and TSoftObjectPtr< const T >::GetPtrTypeHash().
MakeSoftClassPtr() [1/2]
template<class T> TSoftClassPtr< std::remove_cv_t< T > > MakeSoftClassPtr (T * Object) nodiscard
Utility to create a TSoftObjectPtr without specifying the type.
Definition at line 1019 of file SoftObjectPtr.h.
References Object.
MakeSoftClassPtr() [2/2]
template<class T> TSoftClassPtr< std::remove_cv_t< T > > MakeSoftClassPtr (TObjectPtr< T > Object) nodiscard
Definition at line 1026 of file SoftObjectPtr.h.
References Object, and ToRawPtr().
MakeSoftObjectPtr() [1/2]
template<class T> TSoftObjectPtr< T > MakeSoftObjectPtr (T * Object) nodiscard
Utility to create a TSoftObjectPtr without specifying the type.
Definition at line 745 of file SoftObjectPtr.h.
References Object.
MakeSoftObjectPtr() [2/2]
template<class T> TSoftObjectPtr< T > MakeSoftObjectPtr (TObjectPtr< T > Object) nodiscard
Definition at line 752 of file SoftObjectPtr.h.
References Object, and ToRawPtr().
operator!=()
template<class TClass> FORCEINLINE bool operator!= (const UClass * Lhs, const TSoftClassPtr< TClass > & Rhs) nodiscard
Definition at line 1067 of file SoftObjectPtr.h.
References FORCEINLINE.
operator<<()
template<class TClass> FArchive & operator<< (FArchive & Ar, TSoftClassPtr< TClass > & Ptr)
Definition at line 1081 of file SoftObjectPtr.h.
References Ar, and TSoftClassPtr< TClass >::Serialize().
operator==() [1/2]
template<class TClass> FORCEINLINE bool operator== (const UClass * Lhs, const TSoftClassPtr< TClass > & Rhs) nodiscard
Definition at line 1061 of file SoftObjectPtr.h.
References FORCEINLINE.
operator==() [2/2]
template<typename LhsType, typename RhsType UE_REQUIRES> FORCEINLINE bool operator== (LhsType * Lhs, const TSoftObjectPtr< RhsType > & Rhs) nodiscard
Definition at line 630 of file SoftObjectPtr.h.
References FORCEINLINE.
TSoftObjectPtr()
template<typename T> TSoftObjectPtr (T *) -> TSoftObjectPtr< T >
References TModels_V.
UE_DEPRECATED()
template<typename LhsType, typename RhsType UE_REQUIRES> UE_DEPRECATED (5. 5, "Comparing TSoftObjectPtrs of incompatible pointer types has been deprecated.") nodiscard
References FORCEINLINE.