Unreal Engine 5.6 C++ API: FAtlasedTextureSlot Struct Reference
FAtlasedTextureSlot Struct Reference
Structure holding information about where a texture is located in the atlas.
#include "TextureAtlas.h"
Public Member Functions
FAtlasedTextureSlot (uint32 InX, uint32 InY, uint32 InWidth, uint32 InHeight, uint8 InPadding)
Public Member Functions inherited from TIntrusiveLinkedList< FAtlasedTextureSlot >
TIntrusiveLinkedList ()
Default constructor (empty list).
Public Member Functions inherited from TLinkedListBase< FAtlasedTextureSlot, FAtlasedTextureSlot, TIntrusiveLinkedListIterator >
TLinkedListBase ()
Default constructor (empty list)
FORCEINLINE FAtlasedTextureSlot * GetNextLink () const
FORCEINLINE FAtlasedTextureSlot ** GetPrevLink () const
FORCEINLINE bool IsLinked ()
Returns whether element is currently linked.
FORCEINLINE void LinkAfter (FAtlasedTextureSlot *After)
Adds this element to the linked list, after the specified element.
FORCEINLINE void LinkBefore (FAtlasedTextureSlot *Before)
Adds this element to a list, before the given element.
FORCEINLINE void LinkHead (FAtlasedTextureSlot *&Head)
Adds this element as the head of the linked list, linking the input Head pointer to this element, so that when the element is linked/unlinked, the Head linked list pointer will be correctly updated.
FORCEINLINE void LinkReplace (FAtlasedTextureSlot *Replace)
Adds this element to the linked list, replacing the specified element.
FORCEINLINE FAtlasedTextureSlot * Next ()
FORCEINLINE void Unlink ()
Removes this element from the list in constant time.
Data Fields
uint32 Height
The height of the character.
uint8 Padding
Uniform Padding.
uint32 Width
The width of the character.
uint32 X
The X position of the character in the texture.
uint32 Y
The Y position of the character in the texture.
Additional Inherited Members
Public Types inherited from TLinkedListBase< FAtlasedTextureSlot, FAtlasedTextureSlot, TIntrusiveLinkedListIterator >
typedef TIntrusiveLinkedListIterator< FAtlasedTextureSlot, const FAtlasedTextureSlot > TConstIterator
typedef TIntrusiveLinkedListIterator< FAtlasedTextureSlot, FAtlasedTextureSlot > TIterator
Used to iterate over the elements of a linked list.
Detailed Description
Structure holding information about where a texture is located in the atlas.
Inherits a linked-list interface.
When a slot is occupied by texture data, the remaining space in the slot (if big enough) is split off into two new (smaller) slots, building a tree of texture rectangles which, instead of being stored as a tree, are flattened into two linked-lists:
AtlasEmptySlots: A linked-list of empty slots ready for texture data - iterates in same order as a depth-first-search on a tree
AtlasUsedSlots: An unordered linked-list of slots containing texture data
Definition at line 71 of file TextureAtlas.h.
Constructor & Destructor Documentation
FAtlasedTextureSlot()
FAtlasedTextureSlot::FAtlasedTextureSlot (uint32 InX, uint32 InY, uint32 InWidth, uint32 InHeight, uint8 InPadding) inline
Definition at line 84 of file TextureAtlas.h.
References FAtlasedTextureSlot(), TIntrusiveLinkedList< FAtlasedTextureSlot >::TIntrusiveLinkedList(), Height, Padding, Width, X, and Y.
Referenced by FAtlasedTextureSlot().
Field Documentation
Height
uint32 FAtlasedTextureSlot::Height
The height of the character.
Definition at line 80 of file TextureAtlas.h.
Referenced by FAtlasedTextureSlot().
Padding
uint8 FAtlasedTextureSlot::Padding
Uniform Padding.
can only be zero or one. See ESlateTextureAtlasPaddingStyle.
Definition at line 82 of file TextureAtlas.h.
Referenced by FAtlasedTextureSlot().
Width
uint32 FAtlasedTextureSlot::Width
The width of the character.
Definition at line 78 of file TextureAtlas.h.
Referenced by FAtlasedTextureSlot().
X
uint32 FAtlasedTextureSlot::X
The X position of the character in the texture.
Definition at line 74 of file TextureAtlas.h.
Referenced by FAtlasedTextureSlot().
Y
uint32 FAtlasedTextureSlot::Y
The Y position of the character in the texture.
Definition at line 76 of file TextureAtlas.h.
Referenced by FAtlasedTextureSlot().
The documentation for this struct was generated from the following file:
TextureAtlas.h