Unreal Engine 5.6 C++ API: FRDGUniformBuffer Class Reference
FRDGUniformBuffer Class Reference
#include "RenderGraphResources.h"
Public Member Functions
virtual RENDERCORE_API ~FRDGUniformBuffer ()
FORCEINLINE const TCHAR * GetLayoutName () const
FORCEINLINE const FRDGParameterStruct & GetParameters () const
FRHIUniformBuffer * GetRHI () const
The following methods may only be called during pass execution.
RENDERCORE_API void MarkResourceAsUsed () override
The following methods may only be called during pass execution.
Public Member Functions inherited from FRDGResource
FRDGResource (const FRDGResource &)=delete
virtual ~FRDGResource ()=default
FRHIResource * GetRHI () const
Protected Member Functions
template<typename TParameterStruct>
FRDGUniformBuffer (const TParameterStruct *InParameters, const TCHAR *InName)
Protected Member Functions inherited from FRDGResource
FRDGResource (const TCHAR *InName)
FRHIResource * GetRHIUnchecked () const
bool HasRHI () const
RENDERCORE_API void ValidateRHIAccess () const
Private Member Functions
FRHIUniformBuffer * GetRHIUnchecked () const
RENDERCORE_API void InitRHI ()
Private Attributes
bool bExternal = false
friend FRDGAllocator
friend FRDGBuilder
friend FRDGUniformBufferRegistry
FRDGUniformBufferHandle Handle
const FRDGParameterStruct ParameterStruct
TRefCountPtr< FRHIUniformBuffer > UniformBufferRHI
Additional Inherited Members
Data Fields inherited from FRDGResource
const TCHAR *const Name = nullptr
Protected Attributes inherited from FRDGResource
FRHIResource * ResourceRHI = nullptr
Detailed Description
Definition at line 191 of file RenderGraphResources.h.
Constructor & Destructor Documentation
~FRDGUniformBuffer()
virtual RENDERCORE_API FRDGUniformBuffer::~FRDGUniformBuffer () virtual
FRDGUniformBuffer()
template<typename TParameterStruct> FRDGUniformBuffer::FRDGUniformBuffer (const TParameterStruct * InParameters, const TCHAR * InName) inline explicit protected
Definition at line 226 of file RenderGraphResources.h.
References FRDGResource::FRDGResource(), InName, and ParameterStruct.
Referenced by TRDGUniformBuffer< TUniformStruct > *::TRDGUniformBuffer().
Member Function Documentation
GetLayoutName()
FORCEINLINE const TCHAR * FRDGUniformBuffer::GetLayoutName () const inline
Definition at line 203 of file RenderGraphResources.h.
References FORCEINLINE, and ParameterStruct.
GetParameters()
FORCEINLINE const FRDGParameterStruct & FRDGUniformBuffer::GetParameters () const inline
Definition at line 198 of file RenderGraphResources.h.
References FORCEINLINE, and ParameterStruct.
Referenced by TRDGUniformBuffer< TUniformStruct > *::GetParameters().
GetRHI()
FRHIUniformBuffer * FRDGUniformBuffer::GetRHI () const inline
The following methods may only be called during pass execution.
Definition at line 217 of file RenderGraphResources.h.
References FRDGResource::GetRHI().
Referenced by TRDGUniformBuffer< TUniformStruct > *::GetRHIRef().
GetRHIUnchecked()
FRHIUniformBuffer * FRDGUniformBuffer::GetRHIUnchecked () const inline private
Definition at line 232 of file RenderGraphResources.h.
References FRDGResource::GetRHIUnchecked().
InitRHI()
RENDERCORE_API void FRDGUniformBuffer::InitRHI () private
MarkResourceAsUsed()
RENDERCORE_API void FRDGUniformBuffer::MarkResourceAsUsed () override virtual
The following methods may only be called during pass execution.
Marks this resource as actually used by a resource. This is to track what dependencies on pass was actually unnecessary.
Reimplemented from FRDGResource.
Field Documentation
bExternal
bool FRDGUniformBuffer::bExternal = false private
Definition at line 242 of file RenderGraphResources.h.
FRDGAllocator
friend FRDGUniformBuffer::FRDGAllocator private
Definition at line 246 of file RenderGraphResources.h.
FRDGBuilder
friend FRDGUniformBuffer::FRDGBuilder private
Definition at line 244 of file RenderGraphResources.h.
FRDGUniformBufferRegistry
friend FRDGUniformBuffer::FRDGUniformBufferRegistry private
Definition at line 245 of file RenderGraphResources.h.
Handle
FRDGUniformBufferHandle FRDGUniformBuffer::Handle private
Definition at line 241 of file RenderGraphResources.h.
ParameterStruct
const FRDGParameterStruct FRDGUniformBuffer::ParameterStruct private
Definition at line 239 of file RenderGraphResources.h.
Referenced by FRDGUniformBuffer(), GetLayoutName(), and GetParameters().
UniformBufferRHI
TRefCountPtr<FRHIUniformBuffer> FRDGUniformBuffer::UniformBufferRHI private
Definition at line 240 of file RenderGraphResources.h.
The documentation for this class was generated from the following file:
RenderGraphResources.h