Unreal Engine 5.6 C++ API: FShaderLooseParameterInfo Class Reference
FShaderLooseParameterInfo Class Reference
#include "Shader.h"
Public Member Functions
FShaderLooseParameterInfo ()=default
FShaderLooseParameterInfo (uint16 InBaseIndex, uint16 InSize)
LAYOUT_FIELD (uint16, BaseIndex)
LAYOUT_FIELD (uint16, Size)
bool operator< (const FShaderLooseParameterInfo &Rhs) const
bool operator== (const FShaderLooseParameterInfo &Rhs) const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderLooseParameterInfo, RENDERCORE_API, NonVirtual)
Friends
FArchive & operator<< (FArchive &Ar, FShaderLooseParameterInfo &Info)
Detailed Description
Definition at line 215 of file Shader.h.
Constructor & Destructor Documentation
FShaderLooseParameterInfo() [1/2]
FShaderLooseParameterInfo::FShaderLooseParameterInfo () default
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), operator<(), operator<<, and operator==().
FShaderLooseParameterInfo() [2/2]
FShaderLooseParameterInfo::FShaderLooseParameterInfo (uint16 InBaseIndex, uint16 InSize) inline
Definition at line 224 of file Shader.h.
References checkf, TEXT, and TSequenceHistory< HistorySize >::Size.
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderLooseParameterInfo::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderLooseParameterInfo , RENDERCORE_API , NonVirtual) private
References FShaderLooseParameterInfo().
LAYOUT_FIELD() [1/2]
FShaderLooseParameterInfo::LAYOUT_FIELD (uint16 , BaseIndex)
LAYOUT_FIELD() [2/2]
FShaderLooseParameterInfo::LAYOUT_FIELD (uint16 , Size)
References TSequenceHistory< HistorySize >::Size.
operator<()
bool FShaderLooseParameterInfo::operator< (const FShaderLooseParameterInfo & Rhs) const inline
Definition at line 244 of file Shader.h.
References FShaderLooseParameterInfo().
operator==()
bool FShaderLooseParameterInfo::operator== (const FShaderLooseParameterInfo & Rhs) const inline
Definition at line 238 of file Shader.h.
References FShaderLooseParameterInfo(), and TSequenceHistory< HistorySize >::Size.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderLooseParameterInfo & Info) friend
Definition at line 231 of file Shader.h.
References FShaderLooseParameterInfo(), Ar, and Info.
The documentation for this class was generated from the following file:
Shader.h