Unreal Engine 5.6 C++ API: Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType Class Reference
Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType Class Reference
#include "RobinHoodHashTable.h"
Public Member Functions
FHashElementId GetElementId () const
bool operator!= (const FConstIteratorType &Rhs) const
const ElementType & operator* () const
FConstIteratorType & operator++ ()
bool operator== (const FConstIteratorType &Rhs) const
Private Member Functions
FConstIteratorType (const FData &InData, bool bIsStartIterator)
Private Attributes
const FData & Data
FData::FIteratorState State
Friends
template<typename, typename, typename, typename>
class TRobinHoodHashTable
Detailed Description
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator>
class Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType
Definition at line 784 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
FConstIteratorType()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::FConstIteratorType (const FData & InData, bool bIsStartIterator) inline private
Definition at line 792 of file RobinHoodHashTable.h.
References Data, and State.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
GetElementId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::GetElementId () const inline
Definition at line 826 of file RobinHoodHashTable.h.
References State.
operator!=()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::operator!= (const FConstIteratorType & Rhs) const inline
Definition at line 810 of file RobinHoodHashTable.h.
References FConstIteratorType(), Data, and State.
operator*()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const ElementType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::operator* () const inline
Definition at line 815 of file RobinHoodHashTable.h.
References Data, and State.
operator++()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FConstIteratorType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::operator++ () inline
Definition at line 820 of file RobinHoodHashTable.h.
References FConstIteratorType(), Data, and State.
operator==()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::operator== (const FConstIteratorType & Rhs) const inline
Definition at line 805 of file RobinHoodHashTable.h.
References FConstIteratorType(), Data, and State.
Friends And Related Symbol Documentation
TRobinHoodHashTable
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename, typename, typename, typename> friend class TRobinHoodHashTable friend
Definition at line 790 of file RobinHoodHashTable.h.
References TRobinHoodHashTable.
Referenced by TRobinHoodHashTable.
Field Documentation
Data
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const FData& Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::Data private
Definition at line 787 of file RobinHoodHashTable.h.
Referenced by FConstIteratorType(), operator!=(), operator*(), operator++(), and operator==().
State
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FData::FIteratorState Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FConstIteratorType::State private
Definition at line 786 of file RobinHoodHashTable.h.
Referenced by FConstIteratorType(), GetElementId(), operator!=(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
RobinHoodHashTable.h