Unreal Engine 5.6 C++ API: FTimespan Struct Reference
FTimespan Struct Reference
Implements a time span.
#include "Timespan.h"
Public Member Functions
FTimespan ()
Default constructor (zero initialization).
FTimespan (int32 Days, int32 Hours, int32 Minutes, int32 Seconds)
Create and initialize a new time interval with the specified number of days, hours, minutes and seconds.
FTimespan (int32 Days, int32 Hours, int32 Minutes, int32 Seconds, int32 FractionNano)
Create and initialize a new time interval with the specified number of days, hours, minutes and seconds.
FTimespan (int32 Hours, int32 Minutes, int32 Seconds)
Create and initialize a new time interval with the specified number of hours, minutes and seconds.
FTimespan (int64 InTicks)
Create and initialize a new time interval with the specified number of ticks.
bool ExportTextItem (FString &ValueStr, FTimespan const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
Export this time span value to a string.
int32 GetDays () const
Get the days component of this time span.
FTimespan GetDuration ()
Get a time span with the absolute value of this time span.
int32 GetFractionMicro () const
Gets the fractional seconds (in microsecond resolution).
int32 GetFractionMilli () const
Gets the fractional seconds (in millisecond resolution).
int32 GetFractionNano () const
Gets the fractional seconds (in nanosecond resolution).
int32 GetFractionTicks () const
Gets the fractional ticks (in 100 nanosecond resolution).
int32 GetHours () const
Gets the hours component of this time span.
int32 GetMinutes () const
Get the minutes component of this time span.
int32 GetSeconds () const
Get the seconds component of this time span.
int64 GetTicks () const
Get the number of ticks represented by this time span.
double GetTotalDays () const
Get the total number of days represented by this time span.
double GetTotalHours () const
Get the total number of hours represented by this time span.
double GetTotalMicroseconds () const
Get the total number of microseconds represented by this time span.
double GetTotalMilliseconds () const
Get the total number of milliseconds represented by this time span.
double GetTotalMinutes () const
Get the total number of minutes represented by this time span.
double GetTotalSeconds () const
Get the total number of seconds represented by this time span.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
Import a time span value from a text buffer.
bool IsZero () const
Check whether this time span is zero.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
Serializes this date and time for network transmission.
bool operator!= (const FTimespan &Other) const
Compare this time span with the given time span for inequality.
FTimespan operator% (const FTimespan &Other) const
Return the result of calculating the modulus of this time span with another time span.
FTimespan & operator%= (const FTimespan &Other)
Calculate this time span modulo another.
FTimespan operator* (double Scalar) const
Return the result of multiplying the this time span with the given scalar.
FTimespan & operator*= (double Scalar)
Multiply this time span with the given scalar.
FTimespan operator+ (const FTimespan &Other) const
Return the result of adding the given time span to this time span.
FTimespan & operator+= (const FTimespan &Other)
Adds the given time span to this time span.
FTimespan operator- () const
Return the inverse of this time span.
FTimespan operator- (const FTimespan &Other) const
Return the result of subtracting the given time span from this time span.
FTimespan & operator-= (const FTimespan &Other)
Subtract the given time span from this time span.
FTimespan operator/ (double Scalar) const
Return the result of dividing the this time span by the given scalar.
FTimespan & operator/= (double Scalar)
Divide this time span by the given scalar.
bool operator< (const FTimespan &Other) const
Check whether this time span is less than the given time span.
bool operator<= (const FTimespan &Other) const
Check whether this time span is less than or equal to the given time span.
bool operator== (const FTimespan &Other) const
Compare this time span with the given time span for equality.
bool operator> (const FTimespan &Other) const
Check whether this time span is greater than the given time span.
bool operator>= (const FTimespan &Other) const
Check whether this time span is greater than or equal to the given time span.
bool Serialize (FArchive &Ar)
Serialize this time span from or into the specified archive.
FString ToString () const
Return the string representation of this time span using a default format.
FString ToString (const TCHAR *Format) const
Convert this time span to its string representation.
Static Public Member Functions
static FTimespan FromDays (double Days)
Create a time span that represents the specified number of days.
static FTimespan FromHours (double Hours)
Create a time span that represents the specified number of hours.
static FTimespan FromMicroseconds (double Microseconds)
Create a time span that represents the specified number of microseconds.
static FTimespan FromMilliseconds (double Milliseconds)
Create a time span that represents the specified number of milliseconds.
static FTimespan FromMinutes (double Minutes)
Create a time span that represents the specified number of minutes.
static FTimespan FromSeconds (double Seconds)
Create a time span that represents the specified number of seconds.
static FTimespan MaxValue ()
Return the maximum time span value.
static FTimespan MinValue ()
Return the minimum time span value.
static bool Parse (const FString &TimespanString, FTimespan &OutTimespan)
Convert a string to a time span.
static double Ratio (FTimespan Dividend, FTimespan Divisor)
Ratio between two time spans (handles zero values).
static FTimespan Zero ()
Return the zero time span value.
Protected Member Functions
void Assign (int32 Days, int32 Hours, int32 Minutes, int32 Seconds, int32 FractionNano)
Assign the specified components to this time span.
Private Attributes
int64 Ticks
The time span value in 100 nanoseconds resolution.
Friends
uint32 GetTypeHash (const FTimespan &Timespan)
Get the hash for the specified time span.
FArchive & operator<< (FArchive &Ar, FTimespan &Timespan)
Serialize the given time span from or into the specified archive.
class UObject
struct Z_Construct_UScriptStruct_FTimespan_Statics
Detailed Description
Implements a time span.
A time span is the difference between two dates and times. For example, the time span between 12:00:00 January 1, 2000 and 18:00:00 January 2, 2000 is 30.0 hours. Time spans are measured in positive or negative ticks depending on whether the difference is measured forward or backward. Each tick has a resolution of 0.1 microseconds (= 100 nanoseconds).
In conjunction with the companion class FDateTime, time spans can be used to perform date and time based arithmetic, such as calculating the difference between two dates or adding a certain amount of time to a given date.
When initializing time span values from single components, consider using the FromHours, FromMinutes, FromSeconds, Zero, MinValue and related methods instead of calling the overloaded constructors as they will make your code easier to read and understand.
See also
FDateTime
Definition at line 75 of file Timespan.h.
Constructor & Destructor Documentation
FTimespan() [1/5]
FTimespan::FTimespan () inline
Default constructor (zero initialization).
Definition at line 80 of file Timespan.h.
References Ticks.
Referenced by ExportTextItem(), FromDays(), FromHours(), FromMicroseconds(), FromMilliseconds(), FromMinutes(), FromSeconds(), GetDuration(), GetTypeHash, MaxValue(), MinValue(), operator!=(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<<, operator<=(), operator==(), operator>(), operator>=(), Parse(), Ratio(), and Zero().
FTimespan() [2/5]
FTimespan::FTimespan (int64 InTicks) inline
Create and initialize a new time interval with the specified number of ticks.
For better readability, consider using MinValue, MaxValue and Zero.
Parameters
Ticks The number of ticks.
See also
MaxValue, MinValue, Zero
Definition at line 92 of file Timespan.h.
References check, ETimespan::MaxTicks, ETimespan::MinTicks, and Ticks.
FTimespan() [3/5]
FTimespan::FTimespan (int32 Hours, int32 Minutes, int32 Seconds) inline
Create and initialize a new time interval with the specified number of hours, minutes and seconds.
For better readability, consider using FromHours, FromMinutes and FromSeconds.
Parameters
Hours The hours component.
Minutes The minutes component.
Seconds The seconds component.
See also
FromHours, FromMinutes, FromSeconds
Definition at line 108 of file Timespan.h.
References Assign(), Hours, Minutes, and Seconds.
FTimespan() [4/5]
FTimespan::FTimespan (int32 Days, int32 Hours, int32 Minutes, int32 Seconds) inline
Create and initialize a new time interval with the specified number of days, hours, minutes and seconds.
For better readability, consider using FromDays, FromHours, FromMinutes and FromSeconds.
Parameters
Days The days component.
Hours The hours component.
Minutes The minutes component.
Seconds The seconds component.
See also
FromDays, FromHours, FromMinutes, FromSeconds
Definition at line 124 of file Timespan.h.
References Assign(), Days, Hours, Minutes, and Seconds.
FTimespan() [5/5]
FTimespan::FTimespan (int32 Days, int32 Hours, int32 Minutes, int32 Seconds, int32 FractionNano) inline
Create and initialize a new time interval with the specified number of days, hours, minutes and seconds.
Parameters
Days The days component.
Hours The hours component.
Minutes The minutes component.
Seconds The seconds component.
FractionNano The fractional seconds (in nanosecond resolution).
Definition at line 138 of file Timespan.h.
References Assign(), Days, Hours, Minutes, and Seconds.
Member Function Documentation
Assign()
void FTimespan::Assign (int32 Days, int32 Hours, int32 Minutes, int32 Seconds, int32 FractionNano) protected
Assign the specified components to this time span.
Parameters
Days The days component.
Hours The hours component.
Minutes The minutes component.
Seconds The seconds component.
FractionNano The fractional seconds (in nanosecond resolution).
References Days, Hours, Minutes, and Seconds.
Referenced by FTimespan(), FTimespan(), and FTimespan().
ExportTextItem()
bool FTimespan::ExportTextItem (FString & ValueStr, FTimespan const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
Export this time span value to a string.
Parameters
ValueStr Will hold the string value.
DefaultValue The default value.
Parent Not used.
PortFlags Not used.
ExportRootScope Not used.
Returns
true on success, false otherwise.
See also
ImportTextItem
References FTimespan(), Parent, and UObject.
FromDays()
FTimespan FTimespan::FromDays (double Days) inline static
Create a time span that represents the specified number of days.
Parameters
Days The number of days.
Returns
Time span.
See also
FromHours, FromMicroseconds, FromMilliseconds, FromMinutes, FromSeconds
Definition at line 613 of file Timespan.h.
References FTimespan(), Days, and ETimespan::TicksPerDay.
FromHours()
FTimespan FTimespan::FromHours (double Hours) inline static
Create a time span that represents the specified number of hours.
Parameters
Hours The number of hours.
Returns
Time span.
See also
FromDays, FromMicroseconds, FromMilliseconds, FromMinutes, FromSeconds
Definition at line 625 of file Timespan.h.
References FTimespan(), Hours, and ETimespan::TicksPerHour.
FromMicroseconds()
FTimespan FTimespan::FromMicroseconds (double Microseconds) inline static
Create a time span that represents the specified number of microseconds.
Parameters
Microseconds The number of microseconds.
Returns
Time span.
See also
FromDays, FromHours, FromMinutes, FromSeconds, FromMilliseconds
Definition at line 637 of file Timespan.h.
References FTimespan(), Microseconds, and ETimespan::TicksPerMicrosecond.
FromMilliseconds()
FTimespan FTimespan::FromMilliseconds (double Milliseconds) inline static
Create a time span that represents the specified number of milliseconds.
Parameters
Milliseconds The number of milliseconds.
Returns
Time span.
See also
FromDays, FromHours, FromMicroseconds, FromMinutes, FromSeconds
Definition at line 649 of file Timespan.h.
References FTimespan(), Milliseconds, and ETimespan::TicksPerMillisecond.
Referenced by ENUM_CLASS_FLAGS().
FromMinutes()
FTimespan FTimespan::FromMinutes (double Minutes) inline static
Create a time span that represents the specified number of minutes.
Parameters
Minutes The number of minutes.
Returns
Time span.
See also
FromDays, FromHours, FromMicroseconds, FromMilliseconds, FromSeconds
Definition at line 661 of file Timespan.h.
References FTimespan(), Minutes, and ETimespan::TicksPerMinute.
FromSeconds()
FTimespan FTimespan::FromSeconds (double Seconds) inline static
Create a time span that represents the specified number of seconds.
Parameters
Seconds The number of seconds.
Returns
Time span.
See also
FromDays, FromHours, FromMicroseconds, FromMilliseconds, FromMinutes
Definition at line 673 of file Timespan.h.
References FTimespan(), Seconds, and ETimespan::TicksPerSecond.
Referenced by ENUM_CLASS_FLAGS(), UE::FTimeout::GetElapsedTime(), UE::FTimeout::GetRemainingTime(), UE::FTimeout::GetTimeoutValue(), and FTimecode::ToTimespan().
GetDays()
int32 FTimespan::GetDays () const inline
Get the days component of this time span.
Returns
Days component.
Definition at line 356 of file Timespan.h.
References Ticks, and ETimespan::TicksPerDay.
GetDuration()
FTimespan FTimespan::GetDuration () inline
Get a time span with the absolute value of this time span.
This method may overflow the timespan if its value is equal to MinValue.
Returns
Duration of this time span.
See also
MinValue
Definition at line 369 of file Timespan.h.
References FTimespan(), and Ticks.
GetFractionMicro()
int32 FTimespan::GetFractionMicro () const inline
Gets the fractional seconds (in microsecond resolution).
Returns
Number of microseconds in fractional part.
See also
GetTotalMicroseconds
Definition at line 380 of file Timespan.h.
References Ticks, ETimespan::TicksPerMicrosecond, and ETimespan::TicksPerSecond.
GetFractionMilli()
int32 FTimespan::GetFractionMilli () const inline
Gets the fractional seconds (in millisecond resolution).
Returns
Number of milliseconds in fractional part.
See also
GetTotalMilliseconds
Definition at line 391 of file Timespan.h.
References Ticks, ETimespan::TicksPerMillisecond, and ETimespan::TicksPerSecond.
GetFractionNano()
int32 FTimespan::GetFractionNano () const inline
Gets the fractional seconds (in nanosecond resolution).
Returns
Number of nanoseconds in fractional part.
Definition at line 401 of file Timespan.h.
References ETimespan::NanosecondsPerTick, Ticks, and ETimespan::TicksPerSecond.
GetFractionTicks()
int32 FTimespan::GetFractionTicks () const inline
Gets the fractional ticks (in 100 nanosecond resolution).
Returns
Number of ticks in fractional part.
Definition at line 411 of file Timespan.h.
References Ticks, and ETimespan::TicksPerSecond.
GetHours()
int32 FTimespan::GetHours () const inline
Gets the hours component of this time span.
Returns
Hours component.
See also
GetTotalHours
Definition at line 422 of file Timespan.h.
References Ticks, and ETimespan::TicksPerHour.
GetMinutes()
int32 FTimespan::GetMinutes () const inline
Get the minutes component of this time span.
Returns
Minutes component.
See also
GetTotalMinutes
Definition at line 433 of file Timespan.h.
References Ticks, and ETimespan::TicksPerMinute.
GetSeconds()
int32 FTimespan::GetSeconds () const inline
Get the seconds component of this time span.
Returns
Seconds component.
See also
GetTotalSeconds
Definition at line 444 of file Timespan.h.
References Ticks, and ETimespan::TicksPerSecond.
GetTicks()
int64 FTimespan::GetTicks () const inline
Get the number of ticks represented by this time span.
Returns
Number of ticks.
Definition at line 454 of file Timespan.h.
References Ticks.
Referenced by UE::FTimeout::GetRemainingRoundedUpMilliseconds(), Ratio(), and FEvent::Wait().
GetTotalDays()
double FTimespan::GetTotalDays () const inline
Get the total number of days represented by this time span.
Returns
Number of days.
See also
GetDays
Definition at line 465 of file Timespan.h.
References Ticks, and ETimespan::TicksPerDay.
Referenced by FDateTime::GetJulianDay().
GetTotalHours()
double FTimespan::GetTotalHours () const inline
Get the total number of hours represented by this time span.
Returns
Number of hours.
See also
GetHours
Definition at line 476 of file Timespan.h.
References Ticks, and ETimespan::TicksPerHour.
GetTotalMicroseconds()
double FTimespan::GetTotalMicroseconds () const inline
Get the total number of microseconds represented by this time span.
Returns
Number of microseconds.
See also
GetFractionMicro
Definition at line 487 of file Timespan.h.
References Ticks, and ETimespan::TicksPerMicrosecond.
GetTotalMilliseconds()
double FTimespan::GetTotalMilliseconds () const inline
Get the total number of milliseconds represented by this time span.
Returns
Number of milliseconds.
See also
GetFractionMilli
Definition at line 498 of file Timespan.h.
References Ticks, and ETimespan::TicksPerMillisecond.
GetTotalMinutes()
double FTimespan::GetTotalMinutes () const inline
Get the total number of minutes represented by this time span.
Returns
Number of minutes.
See also
GetMinutes
Definition at line 509 of file Timespan.h.
References Ticks, and ETimespan::TicksPerMinute.
GetTotalSeconds()
double FTimespan::GetTotalSeconds () const inline
Get the total number of seconds represented by this time span.
Returns
Number of seconds.
See also
GetSeconds
Definition at line 520 of file Timespan.h.
References Ticks, and ETimespan::TicksPerSecond.
Referenced by UE::FTimeout::FTimeout(), FMediaIOCoreSampleContainer< SampleType >::CacheState(), FTimecode::FromTimespan(), FTimecode::FromTimespan(), and UE::MediaIO::LogThrottle().
ImportTextItem()
bool FTimespan::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
Import a time span value from a text buffer.
Parameters
Buffer The text buffer to import from.
PortFlags Not used.
Parent Not used.
ErrorText The output device for error logging.
Returns
true on success, false otherwise.
See also
ExportTextItem
References Buffer, Parent, and UObject.
IsZero()
bool FTimespan::IsZero () const inline
Check whether this time span is zero.
Returns
true if the time span is zero, false otherwise.
See also
Zero
Definition at line 543 of file Timespan.h.
References Ticks.
MaxValue()
FTimespan FTimespan::MaxValue () inline static
Return the maximum time span value.
The maximum time span value is slightly more than 10,675,199 days.
Returns
Maximum time span.
See also
MinValue,Zero
Definition at line 686 of file Timespan.h.
References FTimespan(), and ETimespan::MaxTicks.
Referenced by UE::FTimeout::FTimeout(), UE::FTimeout::GetRemainingTime(), TFutureState< ResultType >::GetResult(), UE::FTimeout::GetTimeoutValue(), TIntervalTraits< FTimespan >::Max(), TFutureBase< ResultType >::Wait(), UE::Tasks::FTaskConcurrencyLimiter::Wait(), UE::Tasks::WaitAny(), WaitForAnyTaskCompleted(), and UE::Tasks::FPipe::WaitUntilEmpty().
MinValue()
FTimespan FTimespan::MinValue () inline static
Return the minimum time span value.
The minimum time span value is slightly less than -10,675,199 days.
Returns
Minimum time span.
See also
MaxValue, ZeroValue
Definition at line 699 of file Timespan.h.
References FTimespan(), and ETimespan::MinTicks.
Referenced by ENUM_CLASS_FLAGS(), and TIntervalTraits< FTimespan >::Lowest().
NetSerialize()
bool FTimespan::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess)
Serializes this date and time for network transmission.
References Ar, and Map.
operator!=()
bool FTimespan::operator!= (const FTimespan & Other) const inline
Compare this time span with the given time span for inequality.
Parameters
Other The time span to compare with.
Returns
true if the time spans are not equal, false otherwise.
Definition at line 287 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator%()
FTimespan FTimespan::operator% (const FTimespan & Other) const inline
Return the result of calculating the modulus of this time span with another time span.
Parameters
Other The time span to divide by.
Returns
A time span representing the remainder of the modulus operation.
Definition at line 253 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator%=()
FTimespan & FTimespan::operator%= (const FTimespan & Other) inline
Calculate this time span modulo another.
Parameters
Other The time span to divide by.
Returns
This time span.
Definition at line 264 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator*()
FTimespan FTimespan::operator* (double Scalar) const inline
Return the result of multiplying the this time span with the given scalar.
Parameters
Scalar The scalar to multiply with.
Returns
A time span whose value is the product of this time span and the given scalar.
Definition at line 207 of file Timespan.h.
References FTimespan(), and Ticks.
operator*=()
FTimespan & FTimespan::operator*= (double Scalar) inline
Multiply this time span with the given scalar.
Parameters
Scalar The scalar to multiply with.
Returns
This time span.
Definition at line 218 of file Timespan.h.
References FTimespan(), and Ticks.
operator+()
FTimespan FTimespan::operator+ (const FTimespan & Other) const inline
Return the result of adding the given time span to this time span.
Returns
A time span whose value is the sum of this time span and the given time span.
Definition at line 150 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator+=()
FTimespan & FTimespan::operator+= (const FTimespan & Other) inline
Adds the given time span to this time span.
Returns
This time span.
Definition at line 160 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator-() [1/2]
FTimespan FTimespan::operator- () const inline
Return the inverse of this time span.
The value of this time span must be greater than FTimespan::MinValue(), or else an overflow will occur.
Returns
Inverse of this time span.
Definition at line 173 of file Timespan.h.
References FTimespan(), and Ticks.
operator-() [2/2]
FTimespan FTimespan::operator- (const FTimespan & Other) const inline
Return the result of subtracting the given time span from this time span.
Parameters
Other The time span to compare with.
Returns
A time span whose value is the difference of this time span and the given time span.
Definition at line 184 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator-=()
FTimespan & FTimespan::operator-= (const FTimespan & Other) inline
Subtract the given time span from this time span.
Parameters
Other The time span to subtract.
Returns
This time span.
Definition at line 195 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator/()
FTimespan FTimespan::operator/ (double Scalar) const inline
Return the result of dividing the this time span by the given scalar.
Parameters
Scalar The scalar to divide by.
Returns
A time span whose value is the quotient of this time span and the given scalar.
Definition at line 230 of file Timespan.h.
References FTimespan(), and Ticks.
operator/=()
FTimespan & FTimespan::operator/= (double Scalar) inline
Divide this time span by the given scalar.
Parameters
Scalar The scalar to divide by.
Returns
This time span.
Definition at line 241 of file Timespan.h.
References FTimespan(), and Ticks.
operator<()
bool FTimespan::operator< (const FTimespan & Other) const inline
Check whether this time span is less than the given time span.
Parameters
Other The time span to compare with.
Returns
true if this time span is less, false otherwise.
Definition at line 320 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator<=()
bool FTimespan::operator<= (const FTimespan & Other) const inline
Check whether this time span is less than or equal to the given time span.
Parameters
Other The time span to compare with.
Returns
true if this time span is less or equal, false otherwise.
Definition at line 331 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator==()
bool FTimespan::operator== (const FTimespan & Other) const inline
Compare this time span with the given time span for equality.
Parameters
Other The time span to compare with.
Returns
true if the time spans are equal, false otherwise.
Definition at line 276 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator>()
bool FTimespan::operator> (const FTimespan & Other) const inline
Check whether this time span is greater than the given time span.
Parameters
Other The time span to compare with.
Returns
true if this time span is greater, false otherwise.
Definition at line 298 of file Timespan.h.
References FTimespan(), Other, and Ticks.
operator>=()
bool FTimespan::operator>= (const FTimespan & Other) const inline
Check whether this time span is greater than or equal to the given time span.
Parameters
Other The time span to compare with.
Returns
true if this time span is greater or equal, false otherwise.
Definition at line 309 of file Timespan.h.
References FTimespan(), Other, and Ticks.
Parse()
bool FTimespan::Parse (const FString & TimespanString, FTimespan & OutTimespan) static
Convert a string to a time span.
The string must be in one of the following formats: p[d.]hh::mm::ss.fff p[d.]hh::mm::ss.uuuuuu p[d.]hh::mm::ss.nnnnnnnnn
Note that 'p' is the plus or minus sign, and the date component may be omitted for time spans that are shorter than one day.
Parameters
TimespanString The string to convert.
OutTimespan Will contain the parsed time span.
Returns
true if the string was converted successfully, false otherwise.
See also
ToString
References FTimespan().
Ratio()
double FTimespan::Ratio (FTimespan Dividend, FTimespan Divisor) inline static
Ratio between two time spans (handles zero values).
Parameters
Dividend The dividend.
Divisor The divisor.
Returns
The quotient, i.e. Dividend / Divisor.
Definition at line 729 of file Timespan.h.
References FTimespan(), GetTicks(), and Zero().
Serialize()
bool FTimespan::Serialize (FArchive & Ar)
Serialize this time span from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Returns
true on success, false otherwise.
References Ar.
ToString() [1/2]
FString FTimespan::ToString () const
Return the string representation of this time span using a default format.
The returned string has the following format: p[d.]hh:mm:ss.fff
Note that 'p' is the plus or minus sign, and the date component is omitted for time spans that are shorter than one day.
Examples: -42.15:11:36.457 (45 days, 15 hours, 11 minutes, 36.457 seconds in the past) +42.15:11:36.457 (45 days, 15 hours, 11 minutes, 36.457 seconds in the future) +15:11:36.457 (15 hours, 11 minutes, 36.457 seconds in the future) +00:11:36.457 (11 minutes, 36.457 seconds in the future) +00:00:36.457 (36.457 seconds in the future)
Returns
String representation.
See also
Parse
ToString() [2/2]
FString FTimespan::ToString (const TCHAR * Format) const
Convert this time span to its string representation.
The following formatting codes are available: d - prints the days component D - prints the zero-padded days component (00000000..10675199) h - prints the zero-padded hours component (00..23) m - prints the zero-padded minutes component (00..59) s - prints the zero-padded seconds component (00..59) f - prints the zero-padded fractional seconds (000..999) u - prints the zero-padded fractional seconds (000000..999999) n - prints the zero-padded fractional seconds (000000000..999999999)
Depending on whether the time span is positive or negative, a plus or minus sign character will always be added in front of the generated string.
Parameters
Format The format of the returned string.
Returns
String representation.
See also
Parse
References Format.
Zero()
FTimespan FTimespan::Zero () inline static
Return the zero time span value.
The zero time span value can be used in comparison operations with other time spans.
Returns
Zero time span.
See also
IsZero, MaxValue, MinValue
Definition at line 747 of file Timespan.h.
References FTimespan().
Referenced by UE::FMacSystemWideMutex::FMacSystemWideMutex(), UE::FPlatformSystemWideMutexNotImplemented::FPlatformSystemWideMutexNotImplemented(), UE::FUnixSystemWideMutex::FUnixSystemWideMutex(), UE::FWindowsSystemWideMutex::FWindowsSystemWideMutex(), Ratio(), FLiveLinkProvider::SendMessage(), FLiveLinkProvider::SendMessage(), FLiveLinkProvider::SendMessage(), FMacSemaphore::TryAcquire(), FPThreadSemaphore::TryAcquire(), FWindowsSemaphore::TryAcquire(), and FEngineAnalyticsSessionSummary::UpdateSessionProgress().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FTimespan & Timespan) friend
Get the hash for the specified time span.
Parameters
Timespan The timespan to get the hash for.
Returns
Hash value.
References FTimespan(), and Timespan.
operator<<
FArchive & operator<< (FArchive & Ar, FTimespan & Timespan) friend
Serialize the given time span from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Timespan The time span value to serialize.
Returns
The archive.
References FTimespan(), Ar, and Timespan.
UObject
friend class UObject friend
Definition at line 754 of file Timespan.h.
References UObject.
Referenced by ExportTextItem(), ImportTextItem(), and UObject.
Z_Construct_UScriptStruct_FTimespan_Statics
friend struct Z_Construct_UScriptStruct_FTimespan_Statics friend
Definition at line 787 of file Timespan.h.
References Z_Construct_UScriptStruct_FTimespan_Statics.
Referenced by Z_Construct_UScriptStruct_FTimespan_Statics.
Field Documentation
Ticks
int64 FTimespan::Ticks private
The time span value in 100 nanoseconds resolution.
Definition at line 792 of file Timespan.h.
Referenced by FTimespan(), FTimespan(), GetDays(), GetDuration(), GetFractionMicro(), GetFractionMilli(), GetFractionNano(), GetFractionTicks(), GetHours(), GetMinutes(), GetSeconds(), GetTicks(), GetTotalDays(), GetTotalHours(), GetTotalMicroseconds(), GetTotalMilliseconds(), GetTotalMinutes(), GetTotalSeconds(), IsZero(), operator!=(), operator%(), operator%=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this struct was generated from the following file:
Timespan.h