Unreal Engine 5.6 C++ API: UE::Geometry::FSparsePointOctreeCell Struct Reference
UE::Geometry::FSparsePointOctreeCell Struct Reference
FSparsePointOctreeCell is a Node in a SparseDynamicOctree3.
#include "SparseDynamicPointOctree3.h"
Public Member Functions
FSparsePointOctreeCell ()
FSparsePointOctreeCell (uint8 LevelIn, const FVector3i &IndexIn)
uint32 GetChildCellID (int ChildIndex) const
bool HasChild (int ChildIndex) const
bool IsExistingCell () const
FSparsePointOctreeCell MakeChildCell (int ChildIndex) const
void SetChild (uint32 ChildIndex, const FSparsePointOctreeCell &ChildCell)
Data Fields
uint32 CellID
ID of cell (index into cell list)
TStaticArray< uint32, 8 > Children
CellID of each child, or InvalidID if that child does not exist.
FVector3i Index
i,j,k index of cell in level, relative to origin
uint8 Level
Level of cell in octree.
Static Public Attributes
static constexpr uint32 InvalidID = TNumericLimits<uint32>::Max()
static constexpr uint8 InvalidLevel = TNumericLimits<uint8>::Max()
Detailed Description
FSparsePointOctreeCell is a Node in a SparseDynamicOctree3.
Definition at line 26 of file SparseDynamicPointOctree3.h.
Constructor & Destructor Documentation
FSparsePointOctreeCell() [1/2]
UE::Geometry::FSparsePointOctreeCell::FSparsePointOctreeCell () inline
Definition at line 43 of file SparseDynamicPointOctree3.h.
References CellID, Children, Index, InvalidID, Level, and Zero.
Referenced by MakeChildCell(), and SetChild().
FSparsePointOctreeCell() [2/2]
UE::Geometry::FSparsePointOctreeCell::FSparsePointOctreeCell (uint8 LevelIn, const FVector3i & IndexIn) inline
Definition at line 50 of file SparseDynamicPointOctree3.h.
References CellID, Children, Index, InvalidID, and Level.
Member Function Documentation
GetChildCellID()
uint32 UE::Geometry::FSparsePointOctreeCell::GetChildCellID (int ChildIndex) const inline
Definition at line 67 of file SparseDynamicPointOctree3.h.
References Children.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::FindCurrentContainingCell(), and UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand().
HasChild()
bool UE::Geometry::FSparsePointOctreeCell::HasChild (int ChildIndex) const inline
Definition at line 62 of file SparseDynamicPointOctree3.h.
References Children, and InvalidID.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::FindCurrentContainingCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), and UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand().
IsExistingCell()
bool UE::Geometry::FSparsePointOctreeCell::IsExistingCell () const inline
Definition at line 57 of file SparseDynamicPointOctree3.h.
References CellID, and InvalidID.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), and UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand().
MakeChildCell()
FSparsePointOctreeCell UE::Geometry::FSparsePointOctreeCell::MakeChildCell (int ChildIndex) const inline
Definition at line 72 of file SparseDynamicPointOctree3.h.
References FSparsePointOctreeCell(), Index, and Level.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand(), and UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet().
SetChild()
void UE::Geometry::FSparsePointOctreeCell::SetChild (uint32 ChildIndex, const FSparsePointOctreeCell & ChildCell) inline
Definition at line 81 of file SparseDynamicPointOctree3.h.
References FSparsePointOctreeCell(), CellID, and Children.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell().
Field Documentation
CellID
uint32 UE::Geometry::FSparsePointOctreeCell::CellID
ID of cell (index into cell list)
Definition at line 32 of file SparseDynamicPointOctree3.h.
Referenced by FSparsePointOctreeCell(), FSparsePointOctreeCell(), UE::Geometry::FSparseDynamicPointOctree3::CreateNewRootCell(), UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_ToCell(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand(), IsExistingCell(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), and SetChild().
Children
TStaticArray<uint32, 8> UE::Geometry::FSparsePointOctreeCell::Children
CellID of each child, or InvalidID if that child does not exist.
Definition at line 41 of file SparseDynamicPointOctree3.h.
Referenced by FSparsePointOctreeCell(), FSparsePointOctreeCell(), GetChildCellID(), HasChild(), and SetChild().
Index
FVector3i UE::Geometry::FSparsePointOctreeCell::Index
i,j,k index of cell in level, relative to origin
Definition at line 38 of file SparseDynamicPointOctree3.h.
Referenced by FSparsePointOctreeCell(), FSparsePointOctreeCell(), UE::Geometry::FSparseDynamicPointOctree3::CreateNewRootCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_ToCell(), MakeChildCell(), and UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet().
InvalidID
uint32 UE::Geometry::FSparsePointOctreeCell::InvalidID = TNumericLimits<uint32>::Max() static constexpr
Definition at line 28 of file SparseDynamicPointOctree3.h.
Referenced by FSparsePointOctreeCell(), FSparsePointOctreeCell(), HasChild(), and IsExistingCell().
InvalidLevel
uint8 UE::Geometry::FSparsePointOctreeCell::InvalidLevel = TNumericLimits<uint8>::Max() static constexpr
Definition at line 29 of file SparseDynamicPointOctree3.h.
Referenced by UE::Geometry::FSparseDynamicPointOctree3::FindCurrentContainingCell(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), and UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand().
Level
uint8 UE::Geometry::FSparsePointOctreeCell::Level
Level of cell in octree.
Definition at line 35 of file SparseDynamicPointOctree3.h.
Referenced by FSparsePointOctreeCell(), FSparsePointOctreeCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell(), UE::Geometry::FSparseDynamicPointOctree3::Insert_ToCell(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand(), and MakeChildCell().
The documentation for this struct was generated from the following file:
SparseDynamicPointOctree3.h