Unreal Engine 5.6 C++ API: FAdditionalCrashContextStack Struct Reference
FAdditionalCrashContextStack Struct Reference
A thread local stack of callbacks that can be issued at time of the crash.
#include "GenericPlatformCrashContext.h"
Static Public Member Functions
static void ExecuteProviders (FCrashContextExtendedWriter &Writer)
static FAdditionalCrashContextStack & GetThreadContextProvider ()
static void PopProvider ()
static void PushProvider (struct FScopedAdditionalCrashContextProvider *Provider)
Private Types
enum { MaxStackDepth = 16 }
Private Member Functions
FAdditionalCrashContextStack ()
~FAdditionalCrashContextStack ()
void PopProviderInternal ()
void PushProviderInternal (const FScopedAdditionalCrashContextProvider *Provider)
Private Attributes
FAdditionalCrashContextStack * Next
const FScopedAdditionalCrashContextProvider * Stack [MaxStackDepth]
uint32 StackIndex = 0
Detailed Description
A thread local stack of callbacks that can be issued at time of the crash.
Definition at line 914 of file GenericPlatformCrashContext.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
MaxStackDepth
Definition at line 923 of file GenericPlatformCrashContext.h.
Constructor & Destructor Documentation
FAdditionalCrashContextStack()
FAdditionalCrashContextStack::FAdditionalCrashContextStack () private
Referenced by GetThreadContextProvider().
~FAdditionalCrashContextStack()
FAdditionalCrashContextStack::~FAdditionalCrashContextStack () private
Member Function Documentation
ExecuteProviders()
void FAdditionalCrashContextStack::ExecuteProviders (FCrashContextExtendedWriter & Writer) static
GetThreadContextProvider()
FAdditionalCrashContextStack & FAdditionalCrashContextStack::GetThreadContextProvider () static
References FAdditionalCrashContextStack().
PopProvider()
void FAdditionalCrashContextStack::PopProvider () static
Referenced by FScopedAdditionalCrashContextProvider::~FScopedAdditionalCrashContextProvider().
PopProviderInternal()
void FAdditionalCrashContextStack::PopProviderInternal () inline private
Definition at line 937 of file GenericPlatformCrashContext.h.
References check, Stack, and StackIndex.
PushProvider()
void FAdditionalCrashContextStack::PushProvider (struct FScopedAdditionalCrashContextProvider * Provider) static
Referenced by FScopedAdditionalCrashContextProvider::FScopedAdditionalCrashContextProvider().
PushProviderInternal()
void FAdditionalCrashContextStack::PushProviderInternal (const FScopedAdditionalCrashContextProvider * Provider) inline private
Definition at line 931 of file GenericPlatformCrashContext.h.
References check, MaxStackDepth, Stack, and StackIndex.
Field Documentation
Next
FAdditionalCrashContextStack* FAdditionalCrashContextStack::Next private
Definition at line 924 of file GenericPlatformCrashContext.h.
Stack
const FScopedAdditionalCrashContextProvider* FAdditionalCrashContextStack::Stack[MaxStackDepth] private
Definition at line 925 of file GenericPlatformCrashContext.h.
Referenced by PopProviderInternal(), and PushProviderInternal().
StackIndex
uint32 FAdditionalCrashContextStack::StackIndex = 0 private
Definition at line 926 of file GenericPlatformCrashContext.h.
Referenced by PopProviderInternal(), and PushProviderInternal().
The documentation for this struct was generated from the following file:
GenericPlatformCrashContext.h