Unreal Engine 5.6 C++ API: UE::Shader::FType Struct Reference
UE::Shader::FType Struct Reference
#include "ShaderTypes.h"
Public Member Functions
FType ()
FType (const FStructType *InStruct)
FType (EValueType InValueType)
FType (FName InObjectType)
EValueComponentType GetComponentType (int32 Index) const
FType GetConcreteType () const
FType GetDerivativeType () const
EValueType GetFlatFieldType (int32 Index) const
const TCHAR * GetName () const
FType GetNonLWCType () const
int32 GetNumComponents () const
int32 GetNumFlatFields () const
bool IsAny () const
bool IsGeneric () const
bool IsNumeric () const
bool IsNumericLWC () const
bool IsNumericMatrix () const
bool IsNumericScalar () const
bool IsNumericVector () const
bool IsObject () const
bool IsStruct () const
bool IsVoid () const
operator bool () const
operator EValueType () const
bool operator! () const
Data Fields
FName ObjectType
const FStructType * StructType = nullptr
EValueType ValueType
Detailed Description
Definition at line 180 of file ShaderTypes.h.
Constructor & Destructor Documentation
FType() [1/4]
UE::Shader::FType::FType () inline
Definition at line 182 of file ShaderTypes.h.
References ValueType, and UE::Shader::Void.
Referenced by GetConcreteType(), GetDerivativeType(), and GetNonLWCType().
FType() [2/4]
UE::Shader::FType::FType (EValueType InValueType) inline
Definition at line 183 of file ShaderTypes.h.
References check, UE::Shader::Object, UE::Shader::Struct, and ValueType.
FType() [3/4]
UE::Shader::FType::FType (const FStructType * InStruct) inline
Definition at line 184 of file ShaderTypes.h.
References UE::Shader::Struct, StructType, ValueType, and UE::Shader::Void.
FType() [4/4]
UE::Shader::FType::FType (FName InObjectType) inline
Definition at line 185 of file ShaderTypes.h.
References UE::Shader::Object, ObjectType, ValueType, and UE::Shader::Void.
Member Function Documentation
GetComponentType()
EValueComponentType UE::Shader::FType::GetComponentType (int32 Index) const
GetConcreteType()
FType UE::Shader::FType::GetConcreteType () const inline
Definition at line 190 of file ShaderTypes.h.
References FType(), IsNumeric(), UE::Shader::MakeConcreteType(), and ValueType.
GetDerivativeType()
FType UE::Shader::FType::GetDerivativeType () const
References FType().
GetFlatFieldType()
EValueType UE::Shader::FType::GetFlatFieldType (int32 Index) const
GetName()
const TCHAR * UE::Shader::FType::GetName () const
GetNonLWCType()
FType UE::Shader::FType::GetNonLWCType () const inline
Definition at line 189 of file ShaderTypes.h.
References FType(), IsNumericLWC(), UE::Shader::MakeNonLWCType(), and ValueType.
GetNumComponents()
int32 UE::Shader::FType::GetNumComponents () const
Referenced by UE::Shader::FValue::FValue().
GetNumFlatFields()
int32 UE::Shader::FType::GetNumFlatFields () const
IsAny()
bool UE::Shader::FType::IsAny () const inline
Definition at line 194 of file ShaderTypes.h.
References UE::Shader::Any, and ValueType.
IsGeneric()
bool UE::Shader::FType::IsGeneric () const inline
Definition at line 195 of file ShaderTypes.h.
References UE::Shader::IsGenericType(), IsObject(), IsStruct(), and ValueType.
IsNumeric()
bool UE::Shader::FType::IsNumeric () const inline
Definition at line 196 of file ShaderTypes.h.
References UE::Shader::IsNumericType(), IsObject(), IsStruct(), and ValueType.
Referenced by GetConcreteType(), and IsNumericLWC().
IsNumericLWC()
bool UE::Shader::FType::IsNumericLWC () const inline
Definition at line 200 of file ShaderTypes.h.
References UE::Shader::IsLWCType(), IsNumeric(), and ValueType.
Referenced by GetNonLWCType().
IsNumericMatrix()
bool UE::Shader::FType::IsNumericMatrix () const inline
Definition at line 199 of file ShaderTypes.h.
References UE::Shader::IsNumericMatrixType(), IsObject(), IsStruct(), and ValueType.
IsNumericScalar()
bool UE::Shader::FType::IsNumericScalar () const inline
Definition at line 197 of file ShaderTypes.h.
References UE::Shader::IsNumericScalarType(), IsObject(), IsStruct(), and ValueType.
IsNumericVector()
bool UE::Shader::FType::IsNumericVector () const inline
Definition at line 198 of file ShaderTypes.h.
References UE::Shader::IsNumericVectorType(), IsObject(), IsStruct(), and ValueType.
IsObject()
bool UE::Shader::FType::IsObject () const inline
Definition at line 193 of file ShaderTypes.h.
References UE::Shader::Object, and ValueType.
Referenced by IsGeneric(), IsNumeric(), IsNumericMatrix(), IsNumericScalar(), and IsNumericVector().
IsStruct()
bool UE::Shader::FType::IsStruct () const inline
Definition at line 192 of file ShaderTypes.h.
References UE::Shader::Struct, and ValueType.
Referenced by IsGeneric(), IsNumeric(), IsNumericMatrix(), IsNumericScalar(), IsNumericVector(), UE::Shader::operator==(), and UE::Shader::operator==().
IsVoid()
bool UE::Shader::FType::IsVoid () const inline
Definition at line 191 of file ShaderTypes.h.
References ValueType, and UE::Shader::Void.
Referenced by operator bool(), and operator!().
operator bool()
UE::Shader::FType::operator bool () const inline
Definition at line 207 of file ShaderTypes.h.
References IsVoid().
operator EValueType()
UE::Shader::FType::operator EValueType () const inline
Definition at line 206 of file ShaderTypes.h.
References ValueType.
operator!()
bool UE::Shader::FType::operator! () const inline
Definition at line 208 of file ShaderTypes.h.
References IsVoid().
Field Documentation
ObjectType
FName UE::Shader::FType::ObjectType
Definition at line 211 of file ShaderTypes.h.
Referenced by FType(), and UE::Shader::operator==().
StructType
const FStructType* UE::Shader::FType::StructType = nullptr
Definition at line 210 of file ShaderTypes.h.
Referenced by FType(), and UE::Shader::operator==().
ValueType
EValueType UE::Shader::FType::ValueType
Definition at line 212 of file ShaderTypes.h.
Referenced by FType(), FType(), FType(), FType(), GetConcreteType(), GetNonLWCType(), IsAny(), IsGeneric(), IsNumeric(), IsNumericLWC(), IsNumericMatrix(), IsNumericScalar(), IsNumericVector(), IsObject(), IsStruct(), IsVoid(), operator EValueType(), UE::Shader::operator==(), UE::Shader::operator==(), and UE::Shader::operator==().
The documentation for this struct was generated from the following file:
ShaderTypes.h