Unreal Engine 5.6 C++ API: FBlueprintActionDatabase Class Reference
FBlueprintActionDatabase Class Reference
Serves as a container for all available blueprint actions (no matter the type of blueprint/graph they belong in).
#include "BlueprintActionDatabase.h"
Public Types
enum class EPermissionsContext { Property , Asset , Node , Pin }
Field visibility is different depending on context, this enum differentiates between the different contexts that fields can be present in.
typedef TArray< TObjectPtr< UBlueprintNodeSpawner > > FActionList
typedef TMap< FObjectKey, FActionList > FActionRegistry
typedef TMap< FObjectKey, int32 > FPrimingQueue
typedef TMap< FSoftObjectPath, FActionList > FUnloadedActionRegistry
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
virtual ~FBlueprintActionDatabase ()
Destructor.
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
bool ClearAssetActions (const FObjectKey &AssetObjectKey)
Finds the database entry for the specified object and wipes it.
bool ClearAssetActions (UObject *const AssetObject)
Finds the database entry for the specified object and wipes it.
void ClearUnloadedAssetActions (const FSoftObjectPath &ObjectPath)
Finds the database entry for the specified unloaded asset and wipes it.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDatabaseEntryUpdated, UObject *)
void DeferredRemoveEntry (FObjectKey const &InKey)
Removes the entry with the given key on the next tick.
FActionRegistry const & GetAllActions ()
Will populate the database first if it hasn't been created yet, and then returns it in its entirety.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
void MoveUnloadedAssetActions (const FSoftObjectPath &SourceObjectPath, const FSoftObjectPath &TargetObjectPath)
Moves the unloaded asset actions from one location to another.
FOnDatabaseEntryUpdated & OnEntryRemoved ()
FOnDatabaseEntryUpdated & OnEntryUpdated ()
void RefreshAll ()
Populates the action database from scratch.
void RefreshAssetActions (UObject *const AssetObject)
Finds the database entry for the specified asset and wipes it, repopulating it with a fresh set of associated node-spawners.
void RefreshClassActions (UClass *const Class)
Finds the database entry for the specified class and wipes it, repopulating it with a fresh set of associated node-spawners.
void RefreshComponentActions ()
Updates all component related actions.
void RefreshWorlds ()
Populates the action database with all level script actions from all active editor worlds.
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Member Functions
static FBlueprintActionDatabase & Get ()
Getter to access the database singleton.
static bool HasClassFiltering ()
Check whether we have any class filtering applied.
static bool IsClassAllowed (const FTopLevelAssetPath &InClassPath, EPermissionsContext InContext)
static bool IsClassAllowed (UClass const *InClass, EPermissionsContext InContext)
Check whether the global filter applies to this class.
static bool IsEnumAllowed (const FTopLevelAssetPath &InEnumPath, EPermissionsContext InContext)
static bool IsEnumAllowed (UEnum const *InEnum, EPermissionsContext InContext)
Check whether permissions allow this enum.
static bool IsFieldAllowed (UField const *InField, EPermissionsContext InContext)
Check whether permissions allow this field.
static bool IsFunctionAllowed (UFunction const *InFunction, EPermissionsContext InContext)
Check whether permissions allow this function.
static bool IsPinTypeAllowed (const FEdGraphPinType &InPinType, const FTopLevelAssetPath &InUnloadedAssetPath=FTopLevelAssetPath())
Check whether permissions allow this pin type.
static bool IsStructAllowed (const FTopLevelAssetPath &InStructPath, EPermissionsContext InContext)
static bool IsStructAllowed (UScriptStruct const *InStruct, EPermissionsContext InContext)
Check whether permissions allow this struct.
static FBlueprintActionDatabase * TryGet ()
Getter to access the datbase singleton, will return null if the database has not been initialized.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Private Member Functions
FBlueprintActionDatabase ()
Private constructor for singleton purposes.
void Init ()
void OnBlueprintChanged (UBlueprint *)
This exists only because we need a pointer to associate our delegates with.
void PreRefresh (bool bRefreshAll)
Refresh other systems before a full or partial refresh.
void RegisterAllNodeActions (FBlueprintActionDatabaseRegistrar &Registrar)
Private Attributes
FPrimingQueue ActionPrimingQueue
References newly allocated actions that need to be "primed".
FActionRegistry ActionRegistry
A map of associated node-spawners for each class/asset.
TArray< FObjectKey > ActionRemoveQueue
List of action keys to be removed on the next tick.
const TArray< struct FComponentTypeEntry > * ComponentTypes
Pointer to the shared list of currently existing component types.
FOnDatabaseEntryUpdated EntryRefreshDelegate
FOnDatabaseEntryUpdated EntryRemovedDelegate
FDelegateHandle OnAssetAddedDelegateHandle
FDelegateHandle OnAssetLoadedDelegateHandle
Handles to registered delegates.
FDelegateHandle OnAssetRemovedDelegateHandle
FDelegateHandle OnAssetRenamedDelegateHandle
FDelegateHandle OnAssetsPreDeleteDelegateHandle
FDelegateHandle OnBlueprintUnloadedDelegateHandle
FDelegateHandle OnModulesChangedDelegateHandle
FDelegateHandle OnReloadCompleteDelegateHandle
FDelegateHandle OnWorldAddedDelegateHandle
FDelegateHandle OnWorldDestroyedDelegateHandle
FDelegateHandle RefreshLevelScriptActionsDelegateHandle
FUnloadedActionRegistry UnloadedActionRegistry
A map of associated object paths for each node-class that is associated with it.
Additional Inherited Members
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Serves as a container for all available blueprint actions (no matter the type of blueprint/graph they belong in).
The actions stored here are not tied to a specific ui menu; each action is a UBlueprintNodeSpawner which is charged with spawning a specific node type. Should be set up in a way where class specific actions are refreshed when the associated class is regenerated.
@TODO: Hook up to handle class recompile events, along with enum/struct asset creation events.
Definition at line 44 of file BlueprintActionDatabase.h.
Member Typedef Documentation
FActionList
typedef TArray<TObjectPtr<UBlueprintNodeSpawner> > FBlueprintActionDatabase::FActionList
Definition at line 50 of file BlueprintActionDatabase.h.
FActionRegistry
typedef TMap<FObjectKey, FActionList> FBlueprintActionDatabase::FActionRegistry
Definition at line 51 of file BlueprintActionDatabase.h.
FPrimingQueue
typedef TMap<FObjectKey, int32> FBlueprintActionDatabase::FPrimingQueue
Definition at line 49 of file BlueprintActionDatabase.h.
FUnloadedActionRegistry
typedef TMap<FSoftObjectPath, FActionList> FBlueprintActionDatabase::FUnloadedActionRegistry
Definition at line 52 of file BlueprintActionDatabase.h.
Member Enumeration Documentation
EPermissionsContext
enum class FBlueprintActionDatabase::EPermissionsContext strong
Field visibility is different depending on context, this enum differentiates between the different contexts that fields can be present in.
Enumerator
Property
A property on a class - from a user perspective a variable in the My Blueprint tab.
Asset
An asset - e.g.
an anim blueprint asset player or skeleton notify
Node
A K2 node in a graph - e.g.
a function call
Pin
An exposed pin on a K2 node.
Definition at line 174 of file BlueprintActionDatabase.h.
Constructor & Destructor Documentation
~FBlueprintActionDatabase()
virtual FBlueprintActionDatabase::~FBlueprintActionDatabase () virtual
Destructor.
FBlueprintActionDatabase()
FBlueprintActionDatabase::FBlueprintActionDatabase () private
Private constructor for singleton purposes.
Referenced by Get(), and TryGet().
Member Function Documentation
AddReferencedObjects()
virtual void FBlueprintActionDatabase::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
ClearAssetActions() [1/2]
bool FBlueprintActionDatabase::ClearAssetActions (const FObjectKey & AssetObjectKey)
Finds the database entry for the specified object and wipes it.
The entry won't be rebuilt, unless RefreshAssetActions() is explicitly called after.
Parameters
AssetObjectKey
Returns
True if an entry was found and removed.
ClearAssetActions() [2/2]
bool FBlueprintActionDatabase::ClearAssetActions (UObject *const AssetObject)
Finds the database entry for the specified object and wipes it.
The entry won't be rebuilt, unless RefreshAssetActions() is explicitly called after.
Parameters
AssetObject
Returns
True if an entry was found and removed.
ClearUnloadedAssetActions()
void FBlueprintActionDatabase::ClearUnloadedAssetActions (const FSoftObjectPath & ObjectPath)
Finds the database entry for the specified unloaded asset and wipes it.
The entry won't be rebuilt, unless RefreshAssetActions() is explicitly called after.
Parameters
ObjectPath Object's path to lookup into the database
DECLARE_MULTICAST_DELEGATE_OneParam()
FBlueprintActionDatabase::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDatabaseEntryUpdated , UObject *)
DeferredRemoveEntry()
void FBlueprintActionDatabase::DeferredRemoveEntry (FObjectKey const & InKey)
Removes the entry with the given key on the next tick.
Get()
FBlueprintActionDatabase & FBlueprintActionDatabase::Get () static
Getter to access the database singleton.
Will populate the database first if this is the first time accessing it.
Returns
The singleton instance of FBlueprintActionDatabase.
References FBlueprintActionDatabase().
GetAllActions()
FActionRegistry const & FBlueprintActionDatabase::GetAllActions ()
Will populate the database first if it hasn't been created yet, and then returns it in its entirety.
Each node spawner is categorized by a class orasset. A spawner that corresponds to a specific class field (like a function, property, enum, etc.) will be listed under that field's class owner. Remaining spawners that can't be categorized this way will be registered by asset or node type.
Returns
The entire action database, which maps specific objects to arrays of associated node-spawners.
GetReferencerName()
virtual FString FBlueprintActionDatabase::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
GetStatId()
virtual TStatId FBlueprintActionDatabase::GetStatId () const override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
GetTickableTickType()
virtual ETickableTickType FBlueprintActionDatabase::GetTickableTickType () const inline override virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented from FTickableObjectBase.
Definition at line 71 of file BlueprintActionDatabase.h.
References Always.
HasClassFiltering()
bool FBlueprintActionDatabase::HasClassFiltering () static
Check whether we have any class filtering applied.
Init()
void FBlueprintActionDatabase::Init () private
IsClassAllowed() [1/2]
bool FBlueprintActionDatabase::IsClassAllowed (const FTopLevelAssetPath & InClassPath, EPermissionsContext InContext) static
IsClassAllowed() [2/2]
bool FBlueprintActionDatabase::IsClassAllowed (UClass const * InClass, EPermissionsContext InContext) static
Check whether the global filter applies to this class.
IsEnumAllowed() [1/2]
bool FBlueprintActionDatabase::IsEnumAllowed (const FTopLevelAssetPath & InEnumPath, EPermissionsContext InContext) static
IsEnumAllowed() [2/2]
bool FBlueprintActionDatabase::IsEnumAllowed (UEnum const * InEnum, EPermissionsContext InContext) static
Check whether permissions allow this enum.
IsFieldAllowed()
bool FBlueprintActionDatabase::IsFieldAllowed (UField const * InField, EPermissionsContext InContext) static
Check whether permissions allow this field.
IsFunctionAllowed()
bool FBlueprintActionDatabase::IsFunctionAllowed (UFunction const * InFunction, EPermissionsContext InContext) static
Check whether permissions allow this function.
IsPinTypeAllowed()
bool FBlueprintActionDatabase::IsPinTypeAllowed (const FEdGraphPinType & InPinType, const FTopLevelAssetPath & InUnloadedAssetPath = FTopLevelAssetPath()) static
Check whether permissions allow this pin type.
InUnloadedAssetPath will be used in the case where a InPinType.PinSubCategoryObject is unable to be resolved.
IsStructAllowed() [1/2]
bool FBlueprintActionDatabase::IsStructAllowed (const FTopLevelAssetPath & InStructPath, EPermissionsContext InContext) static
IsStructAllowed() [2/2]
bool FBlueprintActionDatabase::IsStructAllowed (UScriptStruct const * InStruct, EPermissionsContext InContext) static
Check whether permissions allow this struct.
MoveUnloadedAssetActions()
void FBlueprintActionDatabase::MoveUnloadedAssetActions (const FSoftObjectPath & SourceObjectPath, const FSoftObjectPath & TargetObjectPath)
Moves the unloaded asset actions from one location to another.
Parameters
SourceObjectPath The object path that the data can currently be found under
TargetObjectPath The object path that the data should be moved to
OnBlueprintChanged()
void FBlueprintActionDatabase::OnBlueprintChanged (UBlueprint *) private
This exists only because we need a pointer to associate our delegates with.
OnEntryRemoved()
FOnDatabaseEntryUpdated & FBlueprintActionDatabase::OnEntryRemoved () inline
Definition at line 168 of file BlueprintActionDatabase.h.
References EntryRemovedDelegate.
OnEntryUpdated()
FOnDatabaseEntryUpdated & FBlueprintActionDatabase::OnEntryUpdated () inline
Definition at line 166 of file BlueprintActionDatabase.h.
References EntryRefreshDelegate.
PreRefresh()
void FBlueprintActionDatabase::PreRefresh (bool bRefreshAll) private
Refresh other systems before a full or partial refresh.
RefreshAll()
void FBlueprintActionDatabase::RefreshAll ()
Populates the action database from scratch.
Loops over every known class and records a set of node-spawners associated with each.
RefreshAssetActions()
void FBlueprintActionDatabase::RefreshAssetActions (UObject *const AssetObject)
Finds the database entry for the specified asset and wipes it, repopulating it with a fresh set of associated node-spawners.
Parameters
AssetObject The asset entry you want rebuilt.
RefreshClassActions()
void FBlueprintActionDatabase::RefreshClassActions (UClass *const Class)
Finds the database entry for the specified class and wipes it, repopulating it with a fresh set of associated node-spawners.
Parameters
Class The class entry you want rebuilt.
References Class.
RefreshComponentActions()
void FBlueprintActionDatabase::RefreshComponentActions ()
Updates all component related actions.
RefreshWorlds()
void FBlueprintActionDatabase::RefreshWorlds ()
Populates the action database with all level script actions from all active editor worlds.
RegisterAllNodeActions()
void FBlueprintActionDatabase::RegisterAllNodeActions (FBlueprintActionDatabaseRegistrar & Registrar) private
Parameters
Registrar
Tick()
virtual void FBlueprintActionDatabase::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
References DeltaTime.
TryGet()
FBlueprintActionDatabase * FBlueprintActionDatabase::TryGet () static
Getter to access the datbase singleton, will return null if the database has not been initialized.
References FBlueprintActionDatabase().
Field Documentation
ActionPrimingQueue
FPrimingQueue FBlueprintActionDatabase::ActionPrimingQueue private
References newly allocated actions that need to be "primed".
Priming is something we do on Tick() aimed at speeding up performance (like pre- caching each spawner's template-node, etc.).
Definition at line 254 of file BlueprintActionDatabase.h.
ActionRegistry
FActionRegistry FBlueprintActionDatabase::ActionRegistry private
A map of associated node-spawners for each class/asset.
A spawner that corresponds to a specific class field (like a function, property, enum, etc.) will be mapped under that field's class outer. Other spawners (that can't be associated with a class outer), will be filed under the desired node's type, or an associated asset.
Definition at line 240 of file BlueprintActionDatabase.h.
ActionRemoveQueue
TArray<FObjectKey> FBlueprintActionDatabase::ActionRemoveQueue private
List of action keys to be removed on the next tick.
Definition at line 257 of file BlueprintActionDatabase.h.
ComponentTypes
const TArray<struct FComponentTypeEntry>* FBlueprintActionDatabase::ComponentTypes private
Pointer to the shared list of currently existing component types.
Definition at line 277 of file BlueprintActionDatabase.h.
EntryRefreshDelegate
FOnDatabaseEntryUpdated FBlueprintActionDatabase::EntryRefreshDelegate private
Definition at line 260 of file BlueprintActionDatabase.h.
Referenced by OnEntryUpdated().
EntryRemovedDelegate
FOnDatabaseEntryUpdated FBlueprintActionDatabase::EntryRemovedDelegate private
Definition at line 261 of file BlueprintActionDatabase.h.
Referenced by OnEntryRemoved().
OnAssetAddedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnAssetAddedDelegateHandle private
Definition at line 265 of file BlueprintActionDatabase.h.
OnAssetLoadedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnAssetLoadedDelegateHandle private
Handles to registered delegates.
Definition at line 264 of file BlueprintActionDatabase.h.
OnAssetRemovedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnAssetRemovedDelegateHandle private
Definition at line 266 of file BlueprintActionDatabase.h.
OnAssetRenamedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnAssetRenamedDelegateHandle private
Definition at line 267 of file BlueprintActionDatabase.h.
OnAssetsPreDeleteDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnAssetsPreDeleteDelegateHandle private
Definition at line 268 of file BlueprintActionDatabase.h.
OnBlueprintUnloadedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnBlueprintUnloadedDelegateHandle private
Definition at line 269 of file BlueprintActionDatabase.h.
OnModulesChangedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnModulesChangedDelegateHandle private
Definition at line 273 of file BlueprintActionDatabase.h.
OnReloadCompleteDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnReloadCompleteDelegateHandle private
Definition at line 274 of file BlueprintActionDatabase.h.
OnWorldAddedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnWorldAddedDelegateHandle private
Definition at line 270 of file BlueprintActionDatabase.h.
OnWorldDestroyedDelegateHandle
FDelegateHandle FBlueprintActionDatabase::OnWorldDestroyedDelegateHandle private
Definition at line 271 of file BlueprintActionDatabase.h.
RefreshLevelScriptActionsDelegateHandle
FDelegateHandle FBlueprintActionDatabase::RefreshLevelScriptActionsDelegateHandle private
Definition at line 272 of file BlueprintActionDatabase.h.
UnloadedActionRegistry
FUnloadedActionRegistry FBlueprintActionDatabase::UnloadedActionRegistry private
A map of associated object paths for each node-class that is associated with it.
This is used for unloaded assets that will need to be replaced after the asset is loaded with the final (and more complete) nodespawner.
Definition at line 247 of file BlueprintActionDatabase.h.
The documentation for this class was generated from the following file:
BlueprintActionDatabase.h