Unreal Engine 5.6 C++ API: TActorDescContainerCollection< ActorDescContPtrType > Class Template Reference
TActorDescContainerCollection< ActorDescContPtrType > Class Template Reference
#include "ActorDescContainerCollection.h"
Data Structures
class TBaseIterator
class TConstIterator
class TIterator
Public Member Functions
TActorDescContainerCollection ()=default
template<class U>
TActorDescContainerCollection (const TArray< U > &ActorDescContainers)
template<class U>
TActorDescContainerCollection (std::initializer_list< U > ActorDescContainerArray)
virtual ~TActorDescContainerCollection ()
void AddContainer (ActorDescContPtrType Container)
template<class U>
void Append (const TActorDescContainerCollection< U > &OtherCollection)
bool Contains (const FName &ContainerPackageName) const
DECLARE_EVENT_OneParam (UWorldPartition, FActorDescAddedEvent, FWorldPartitionActorDesc *)
DECLARE_EVENT_OneParam (UWorldPartition, FActorDescRemovedEvent, FWorldPartitionActorDesc *)
void Empty ()
ActorDescContPtrType FindContainer (const FName &ContainerPackageName) const
ActorDescContPtrType FindHandlingContainer (const AActor *Actor) const
void ForEachActorDescContainer (TFunctionRef< void(ActorDescContPtrType)> Func)
void ForEachActorDescContainer (TFunctionRef< void(ActorDescContPtrType)> Func) const
void ForEachActorDescContainerBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func)
void ForEachActorDescContainerBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func) const
FWorldPartitionActorDesc * GetActorDesc (const FGuid &Guid)
const FWorldPartitionActorDesc * GetActorDesc (const FGuid &Guid) const
const FWorldPartitionActorDesc * GetActorDescByName (FName ActorName) const
const FWorldPartitionActorDesc * GetActorDescByPath (const FSoftObjectPath &ActorPath) const
const FWorldPartitionActorDesc * GetActorDescByPath (const FString &ActorPath) const
FWorldPartitionActorDesc & GetActorDescChecked (const FGuid &Guid)
const FWorldPartitionActorDesc & GetActorDescChecked (const FGuid &Guid) const
ActorDescContPtrType GetActorDescContainer (const FGuid &ActorGuid) const
uint32 GetActorDescContainerCount () const
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
bool IsActorDescHandled (const AActor *Actor) const
bool IsEmpty () const
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
void LoadAllActors (TArray< FWorldPartitionReference > &OutReferences)
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
void OnPackageDeleted (UPackage *Package)
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
bool RemoveActor (const FGuid &ActorGuid)
bool RemoveContainer (ActorDescContPtrType Container)
Data Fields
FActorDescAddedEvent OnActorDescAddedEvent
FActorDescRemovedEvent OnActorDescRemovedEvent
Protected Member Functions
virtual void OnCollectionChanged ()
Protected Attributes
TArray< ActorDescContPtrType > ActorDescContainerCollection
Private Member Functions
void OnActorDescAdded (FWorldPartitionActorDesc *ActorDesc)
void OnActorDescRemoved (FWorldPartitionActorDesc *ActorDesc)
void RegisterDelegates (ActorDescContPtrType Container)
void UnregisterDelegates (ActorDescContPtrType Container)
Friends
template<class>
class TActorDescContainerCollection
Detailed Description
template<class ActorDescContPtrType>
class TActorDescContainerCollection< ActorDescContPtrType >
Definition at line 12 of file ActorDescContainerCollection.h.
Constructor & Destructor Documentation
TActorDescContainerCollection() [1/3]
template<class ActorDescContPtrType> TActorDescContainerCollection< ActorDescContPtrType >::TActorDescContainerCollection () default
TActorDescContainerCollection() [2/3]
template<class ActorDescContPtrType> template<class U> TActorDescContainerCollection< ActorDescContPtrType >::TActorDescContainerCollection (std::initializer_list< U > ActorDescContainerArray)
Definition at line 206 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection, ForEachActorDescContainer(), and RegisterDelegates().
TActorDescContainerCollection() [3/3]
template<class ActorDescContPtrType> template<class U> TActorDescContainerCollection< ActorDescContPtrType >::TActorDescContainerCollection (const TArray< U > & ActorDescContainers)
Definition at line 217 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection, ForEachActorDescContainer(), and RegisterDelegates().
~TActorDescContainerCollection()
template<class ActorDescContPtrType> TActorDescContainerCollection< ActorDescContPtrType >::~TActorDescContainerCollection () virtual
Definition at line 227 of file ActorDescContainerCollection.h.
References Empty.
Member Function Documentation
AddContainer()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::AddContainer (ActorDescContPtrType Container)
Definition at line 233 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection, Container, OnCollectionChanged(), and RegisterDelegates().
Append()
template<class ActorDescContPtrType> template<class U> void TActorDescContainerCollection< ActorDescContPtrType >::Append (const TActorDescContainerCollection< U > & OtherCollection)
Definition at line 254 of file ActorDescContainerCollection.h.
References TActorDescContainerCollection, ActorDescContainerCollection, IsEmpty(), TArray< InElementType, InAllocatorType >::Num(), OnCollectionChanged(), and RegisterDelegates().
Contains()
template<class ActorDescContPtrType> bool TActorDescContainerCollection< ActorDescContPtrType >::Contains (const FName & ContainerPackageName) const
Definition at line 272 of file ActorDescContainerCollection.h.
References FindContainer().
DECLARE_EVENT_OneParam() [1/2]
template<class ActorDescContPtrType> TActorDescContainerCollection< ActorDescContPtrType >::DECLARE_EVENT_OneParam (UWorldPartition , FActorDescAddedEvent , FWorldPartitionActorDesc *)
DECLARE_EVENT_OneParam() [2/2]
template<class ActorDescContPtrType> TActorDescContainerCollection< ActorDescContPtrType >::DECLARE_EVENT_OneParam (UWorldPartition , FActorDescRemovedEvent , FWorldPartitionActorDesc *)
Empty()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::Empty ()
Definition at line 285 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection, ForEachActorDescContainer(), OnCollectionChanged(), and UnregisterDelegates().
FindContainer()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerCollection< ActorDescContPtrType >::FindContainer (const FName & ContainerPackageName) const
Definition at line 278 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection.
Referenced by Contains().
FindHandlingContainer()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerCollection< ActorDescContPtrType >::FindHandlingContainer (const AActor * Actor) const
Definition at line 449 of file ActorDescContainerCollection.h.
References Actor, ForEachActorDescContainerBreakable(), and GetActorDescContainer().
ForEachActorDescContainer() [1/2]
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::ForEachActorDescContainer (TFunctionRef< void(ActorDescContPtrType)> Func)
Definition at line 499 of file ActorDescContainerCollection.h.
References TActorDescContainerCollection, and ForEachActorDescContainer().
Referenced by TActorDescContainerCollection(), TActorDescContainerCollection(), Empty(), ForEachActorDescContainer(), LoadAllActors(), and OnPackageDeleted().
ForEachActorDescContainer() [2/2]
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::ForEachActorDescContainer (TFunctionRef< void(ActorDescContPtrType)> Func) const
Definition at line 490 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection.
ForEachActorDescContainerBreakable() [1/2]
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::ForEachActorDescContainerBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func)
Definition at line 484 of file ActorDescContainerCollection.h.
References TActorDescContainerCollection, and ForEachActorDescContainerBreakable().
Referenced by FindHandlingContainer(), ForEachActorDescContainerBreakable(), GetActorDesc(), GetActorDescByName(), GetActorDescByPath(), GetActorDescByPath(), GetActorDescContainer(), IsActorDescHandled(), and RemoveActor().
ForEachActorDescContainerBreakable() [2/2]
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::ForEachActorDescContainerBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func) const
Definition at line 472 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection.
GetActorDesc() [1/2]
template<class ActorDescContPtrType> FWorldPartitionActorDesc * TActorDescContainerCollection< ActorDescContPtrType >::GetActorDesc (const FGuid & Guid)
Definition at line 324 of file ActorDescContainerCollection.h.
References TActorDescContainerCollection, and Guid.
Referenced by GetActorDescChecked().
GetActorDesc() [2/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDesc * TActorDescContainerCollection< ActorDescContPtrType >::GetActorDesc (const FGuid & Guid) const
Definition at line 311 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable(), and Guid.
GetActorDescByName()
template<class ActorDescContPtrType> const FWorldPartitionActorDesc * TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescByName (FName ActorName) const
Definition at line 372 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable().
GetActorDescByPath() [1/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDesc * TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescByPath (const FSoftObjectPath & ActorPath) const
Definition at line 359 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable().
GetActorDescByPath() [2/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDesc * TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescByPath (const FString & ActorPath) const
Definition at line 346 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable().
GetActorDescChecked() [1/2]
template<class ActorDescContPtrType> FWorldPartitionActorDesc & TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescChecked (const FGuid & Guid)
Definition at line 340 of file ActorDescContainerCollection.h.
References TActorDescContainerCollection, and Guid.
GetActorDescChecked() [2/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDesc & TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescChecked (const FGuid & Guid) const
Definition at line 330 of file ActorDescContainerCollection.h.
References check, GetActorDesc(), and Guid.
GetActorDescContainer()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescContainer (const FGuid & ActorGuid) const
Definition at line 433 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable().
Referenced by FindHandlingContainer().
GetActorDescContainerCount()
template<class ActorDescContPtrType> uint32 TActorDescContainerCollection< ActorDescContPtrType >::GetActorDescContainerCount () const inline
Definition at line 38 of file ActorDescContainerCollection.h.
IsActorDescHandled()
template<class ActorDescContPtrType> template<typename, typename> bool TActorDescContainerCollection< ActorDescContPtrType >::IsActorDescHandled (const AActor * Actor) const
Definition at line 410 of file ActorDescContainerCollection.h.
References Actor, and ForEachActorDescContainerBreakable().
IsEmpty()
template<class ActorDescContPtrType> bool TActorDescContainerCollection< ActorDescContPtrType >::IsEmpty () const inline
Definition at line 37 of file ActorDescContainerCollection.h.
Referenced by Append().
LoadAllActors()
template<class ActorDescContPtrType> template<typename, typename> void TActorDescContainerCollection< ActorDescContPtrType >::LoadAllActors (TArray< FWorldPartitionReference > & OutReferences)
Definition at line 424 of file ActorDescContainerCollection.h.
References ForEachActorDescContainer().
OnActorDescAdded()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::OnActorDescAdded (FWorldPartitionActorDesc * ActorDesc) private
Definition at line 505 of file ActorDescContainerCollection.h.
References OnActorDescAddedEvent.
Referenced by RegisterDelegates().
OnActorDescRemoved()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::OnActorDescRemoved (FWorldPartitionActorDesc * ActorDesc) private
Definition at line 511 of file ActorDescContainerCollection.h.
References OnActorDescRemovedEvent.
Referenced by RegisterDelegates().
OnCollectionChanged()
template<class ActorDescContPtrType> virtual void TActorDescContainerCollection< ActorDescContPtrType >::OnCollectionChanged () inline protected virtual
Definition at line 79 of file ActorDescContainerCollection.h.
Referenced by AddContainer(), Append(), Empty(), and RemoveContainer().
OnPackageDeleted()
template<class ActorDescContPtrType> template<typename, typename> void TActorDescContainerCollection< ActorDescContPtrType >::OnPackageDeleted (UPackage * Package)
Definition at line 400 of file ActorDescContainerCollection.h.
References ForEachActorDescContainer(), and Package.
RegisterDelegates()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::RegisterDelegates (ActorDescContPtrType Container) private
Definition at line 297 of file ActorDescContainerCollection.h.
References ConstCast(), Container, OnActorDescAdded(), and OnActorDescRemoved().
Referenced by TActorDescContainerCollection(), TActorDescContainerCollection(), AddContainer(), and Append().
RemoveActor()
template<class ActorDescContPtrType> template<typename, typename> bool TActorDescContainerCollection< ActorDescContPtrType >::RemoveActor (const FGuid & ActorGuid)
Definition at line 386 of file ActorDescContainerCollection.h.
References ForEachActorDescContainerBreakable().
RemoveContainer()
template<class ActorDescContPtrType> bool TActorDescContainerCollection< ActorDescContPtrType >::RemoveContainer (ActorDescContPtrType Container)
Definition at line 241 of file ActorDescContainerCollection.h.
References ActorDescContainerCollection, Container, OnCollectionChanged(), and UnregisterDelegates().
UnregisterDelegates()
template<class ActorDescContPtrType> void TActorDescContainerCollection< ActorDescContPtrType >::UnregisterDelegates (ActorDescContPtrType Container) private
Definition at line 304 of file ActorDescContainerCollection.h.
References ConstCast(), and Container.
Referenced by Empty(), and RemoveContainer().
Friends And Related Symbol Documentation
TActorDescContainerCollection
template<class ActorDescContPtrType> template<class> friend class TActorDescContainerCollection friend
Definition at line 16 of file ActorDescContainerCollection.h.
Referenced by Append(), ForEachActorDescContainer(), ForEachActorDescContainerBreakable(), GetActorDesc(), and GetActorDescChecked().
Field Documentation
ActorDescContainerCollection
template<class ActorDescContPtrType> TArray<ActorDescContPtrType> TActorDescContainerCollection< ActorDescContPtrType >::ActorDescContainerCollection protected
Definition at line 81 of file ActorDescContainerCollection.h.
Referenced by TActorDescContainerCollection(), TActorDescContainerCollection(), TActorDescContainerCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), AddContainer(), Append(), Empty(), FindContainer(), ForEachActorDescContainer(), ForEachActorDescContainerBreakable(), and RemoveContainer().
OnActorDescAddedEvent
template<class ActorDescContPtrType> FActorDescAddedEvent TActorDescContainerCollection< ActorDescContPtrType >::OnActorDescAddedEvent
Definition at line 63 of file ActorDescContainerCollection.h.
Referenced by OnActorDescAdded().
OnActorDescRemovedEvent
template<class ActorDescContPtrType> FActorDescRemovedEvent TActorDescContainerCollection< ActorDescContPtrType >::OnActorDescRemovedEvent
Definition at line 66 of file ActorDescContainerCollection.h.
Referenced by OnActorDescRemoved().
The documentation for this class was generated from the following file:
ActorDescContainerCollection.h