Unreal Engine 5.6 C++ API: FScopedSlowTask Struct Reference
FScopedSlowTask Struct Reference
A scope block representing an amount of work divided up into sections.
#include "ScopedSlowTask.h"
Public Member Functions
FORCEINLINE FScopedSlowTask (float InAmountOfWork, const FText &InDefaultMessage=FText(), bool bInEnabled=true, FFeedbackContext &InContext= *GWarn)
Construct this scope from an amount of work to do, and a message to display.
FORCEINLINE ~FScopedSlowTask ()
Public Member Functions inherited from FSlowTask
FSlowTask (float InAmountOfWork, const FText &InDefaultMessage=FText(), bool bInEnabled=true, FFeedbackContext &InContext= *GWarn)
Construct this scope from an amount of work to do, and a message to display.
void Destroy ()
Function that finishes any remaining work and removes itself from the global scope stack.
void EnterProgressFrame (float ExpectedWorkThisFrame=1.f, const FText &Text=FText())
Indicate that we are to enter a frame that will take up the specified amount of work.
void ForceRefresh ()
Whenever we encounter edge condition requiring to force a UI refresh (Like if another popup would show when the slow task finishes and you want it to show 100%)
const FText & GetCurrentMessage () const
Get the frame message or default message if empty.
void Initialize ()
Function that initializes the scope by adding it to its context's stack.
void MakeDialog (bool bShowCancelButton=false, bool bAllowInPIE=false)
Creates a new dialog for this slow task, if there is currently not one open.
void MakeDialogDelayed (float Threshold, bool bShowCancelButton=false, bool bAllowInPIE=false)
Creates a new dialog for this slow task after the given time threshold.
bool ShouldCancel () const
True if the user has requested that the slow task be canceled.
void TickProgress ()
Let the UI refresh but doesn't advance progress.
Additional Inherited Members
Static Public Member Functions inherited from FSlowTask
static bool ShouldCreateThrottledSlowTask ()
True if a slow task should be created.
Data Fields inherited from FSlowTask
float CompletedWork
The amount of work we have already completed in this scope.
float CurrentFrameScope
The amount of work the current frame is responsible for.
FText DefaultMessage
Default message to display to the user when not overridden by a frame.
FText FrameMessage
Message pertaining to the current frame's work.
TOptional< float > OpenDialogThreshold
Threshold before dialog is opened.
double StartTime
The time that this scope was created.
float TotalAmountOfWork
The amount of work to do in this scope.
ESlowTaskVisibility Visibility
The visibility of this slow task.
Detailed Description
A scope block representing an amount of work divided up into sections.
Use one scope at the top of each function to give accurate feedback to the user of a slow operation's progress.
Example Usage: void DoSlowWork() { FScopedSlowTask Progress(2.f, LOCTEXT("DoingSlowWork", "Doing Slow Work...")); // Optionally make this show a dialog if not already shown Progress.MakeDialog();
// Indicate that we are entering a frame representing 1 unit of work Progress.EnterProgressFrame(1.f);
// DoFirstThing() can follow a similar pattern of creating a scope divided into frames. These contribute to their parent's progress frame proportionately. DoFirstThing();
Progress.EnterProgressFrame(1.f); DoSecondThing(); }
Definition at line 31 of file ScopedSlowTask.h.
Constructor & Destructor Documentation
FScopedSlowTask()
FORCEINLINE FScopedSlowTask::FScopedSlowTask (float InAmountOfWork, const FText & InDefaultMessage = FText(), bool bInEnabled = true, FFeedbackContext & InContext = *GWarn) inline
Construct this scope from an amount of work to do, and a message to display.
Parameters
InAmountOfWork Arbitrary number of work units to perform (can be a percentage or number of steps). 0 indicates that no progress frames are to be entered in this scope (automatically enters a frame encompassing the entire scope)
InDefaultMessage A message to display to the user to describe the purpose of the scope
bInEnabled When false, this scope will have no effect. Allows for proper scoped objects that are conditionally disabled.
Definition at line 41 of file ScopedSlowTask.h.
References FSlowTask::FSlowTask(), FORCEINLINE, GWarn, and FSlowTask::Initialize().
~FScopedSlowTask()
FORCEINLINE FScopedSlowTask::~FScopedSlowTask () inline
Definition at line 47 of file ScopedSlowTask.h.
References FSlowTask::Destroy(), and FORCEINLINE.
The documentation for this struct was generated from the following file:
ScopedSlowTask.h