Unreal Engine 5.6 C++ API: UE::Insights::TTreeNodeGroupingByUniqueValue< Type > Class Template Reference
UE::Insights::TTreeNodeGroupingByUniqueValue< Type > Class Template Reference
Creates a group for each unique value (assumes data type of cell values is a simple type).
#include "TreeNodeGrouping.h"
Public Member Functions
TTreeNodeGroupingByUniqueValue (TSharedRef< FTableColumn > InColumnRef)
virtual ~TTreeNodeGroupingByUniqueValue ()
virtual void GroupNodes (const TArray< FTableTreeNodePtr > &Nodes, FTableTreeNode &ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress &InAsyncOperationProgress) const override
Public Member Functions inherited from UE::Insights::FTreeNodeGroupingByUniqueValue
FTreeNodeGroupingByUniqueValue (TSharedRef< FTableColumn > InColumnRef)
virtual ~FTreeNodeGroupingByUniqueValue ()
TSharedRef< FTableColumn > GetColumn () const
virtual FName GetColumnId () const override
virtual FTreeNodeGroupInfo GetGroupForNode (const FBaseTreeNodePtr InNode) const override
Static Private Member Functions
static FName GetGroupName (const FTableColumn &Column, const FTableTreeNode &Node)
static Type GetValue (const FTableCellValue &CellValue)
Additional Inherited Members
Protected Member Functions inherited from UE::Insights::FTreeNodeGrouping
UE_DEPRECATED (5.6, "BrushName is not used") FName BrushName
Protected Attributes inherited from UE::Insights::FTreeNodeGrouping
FText Description
const FSlateBrush * Icon
FText ShortName
FText TitleName
Detailed Description
template<typename Type>
class UE::Insights::TTreeNodeGroupingByUniqueValue< Type >
Creates a group for each unique value (assumes data type of cell values is a simple type).
Definition at line 136 of file TreeNodeGrouping.h.
Constructor & Destructor Documentation
TTreeNodeGroupingByUniqueValue()
template<typename Type> UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::TTreeNodeGroupingByUniqueValue (TSharedRef< FTableColumn > InColumnRef) inline
Definition at line 139 of file TreeNodeGrouping.h.
~TTreeNodeGroupingByUniqueValue()
template<typename Type> virtual UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::~TTreeNodeGroupingByUniqueValue () inline virtual
Definition at line 140 of file TreeNodeGrouping.h.
Member Function Documentation
GetGroupName()
template<typename Type> FName UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GetGroupName (const FTableColumn & Column, const FTableTreeNode & Node) static private
Definition at line 150 of file TreeNodeGrouping.h.
References FName, TStringView< CharType >::GetData(), GetGroupName(), UE::Insights::FTableColumn::GetValueAsGroupingText(), FText::IsEmpty(), TStringView< CharType >::Len(), NAME_SIZE, and TEXT.
Referenced by GetGroupName(), and GroupNodes().
GetValue()
template<typename Type> Type UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GetValue (const FTableCellValue & CellValue) static private
Referenced by GroupNodes().
GroupNodes()
template<typename Type> void UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes (const TArray< FTableTreeNodePtr > & Nodes, FTableTreeNode & ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress & InAsyncOperationProgress) const override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
Definition at line 169 of file TreeNodeGrouping.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), UE::Insights::FBaseTreeNode::AddChildAndSetParent(), UE::Insights::FBaseTreeNode::ClearChildren(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), FName, UE::Insights::FTreeNodeGroupingByUniqueValue::GetColumn(), GetGroupName(), TOptional< OptionalType >::GetValue(), UE::Insights::FTableColumn::GetValue(), GetValue(), GroupNodes(), TOptional< OptionalType >::IsSet(), MakeShared(), UE::Insights::IAsyncOperationProgress::ShouldCancelAsyncOp(), TEXT, and Value.
Referenced by GroupNodes().
The documentation for this class was generated from the following file:
TreeNodeGrouping.h