Unreal Engine 5.6 C++ API: GenericApplication Class Reference
GenericApplication Class Reference
Generic platform application interface.
#include "GenericApplication.h"
Public Types
typedef FOnConsoleCommandAdded::FDelegate FOnConsoleCommandListener
Public Member Functions
APPLICATIONCORE_API GenericApplication (const TSharedPtr< ICursor > &InCursor)
virtual APPLICATIONCORE_API ~GenericApplication ()
virtual void AddPendingConsoleCommand (const FString &InCommand)
virtual bool ApplicationLicenseValid (FPlatformUserId PlatformUser=PLATFORMUSERID_NONE)
DECLARE_EVENT (FSlateApplication, FOnClipboardContentChanged)
DECLARE_EVENT (FSlateApplication, FVirtualKeyboardHiddenEvent)
DECLARE_EVENT_OneParam (FSlateApplication, FVirtualKeyboardShownEvent, FPlatformRect)
Delegate for virtual keyboard being shown/hidden in case UI wants to slide out of the way.
DECLARE_EVENT_OneParam (GenericApplication, FOnDisplayMetricsChanged, const FDisplayMetrics &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnConsoleCommandAdded, const FString &)
virtual void DestroyApplication ()
virtual void FinishedInputThisFrame ()
virtual void * GetCapture (void) const
virtual void GetInitialDisplayMetrics (FDisplayMetrics &OutDisplayMetrics) const
virtual IInputInterface * GetInputInterface ()
TSharedRef< FGenericApplicationMessageHandler > GetMessageHandler ()
virtual FModifierKeysState GetModifierKeys () const
virtual ITextInputMethodSystem * GetTextInputMethodSystem ()
Function to return the current implementation of the Text Input Method System.
virtual EWindowTitleAlignment::Type GetWindowTitleAlignment () const
Gets the horizontal alignment of the window title bar's title text.
virtual EWindowTransparency GetWindowTransparencySupport () const
virtual TSharedPtr< FGenericWindow > GetWindowUnderCursor ()
virtual FPlatformRect GetWorkArea (const FPlatformRect &CurrentWindow) const
virtual void InitializeWindow (const TSharedRef< FGenericWindow > &Window, const TSharedRef< FGenericWindowDefinition > &InDefinition, const TSharedPtr< FGenericWindow > &InParent, const bool bShowImmediately)
virtual bool IsAllowedToRender () const
virtual bool IsCursorDirectlyOverSlateWindow () const
virtual bool IsGamepadAttached () const
virtual bool IsMinimized () const
virtual bool IsMouseAttached () const
virtual bool IsUsingHighPrecisionMouseMode () const
virtual bool IsUsingTrackpad () const
virtual TSharedRef< FGenericWindow > MakeWindow ()
FOnClipboardContentChanged & OnClipboardContentChanged ()
FOnDisplayMetricsChanged & OnDisplayMetricsChanged ()
Notifies subscribers when any of the display metrics change: e.g.
FVirtualKeyboardHiddenEvent & OnVirtualKeyboardHidden ()
FVirtualKeyboardShownEvent & OnVirtualKeyboardShown ()
virtual void PollGameDeviceState (const float TimeDelta)
virtual void ProcessDeferredEvents (const float TimeDelta)
virtual void PumpMessages (const float TimeDelta)
virtual void RegisterConsoleCommandListener (const FOnConsoleCommandListener &InListener)
virtual void SendAnalytics (IAnalyticsProvider *Provider)
Send any analytics captured by the application.
virtual void SetCapture (const TSharedPtr< FGenericWindow > &InWindow)
virtual void SetHighPrecisionMouseMode (const bool Enable, const TSharedPtr< FGenericWindow > &InWindow)
virtual void SetMessageHandler (const TSharedRef< FGenericApplicationMessageHandler > &InMessageHandler)
virtual void ShowSystemHelp ()
virtual bool SupportsSystemHelp () const
virtual void Tick (const float TimeDelta)
virtual bool TryCalculatePopupWindowPosition (const FPlatformRect &InAnchor, const FVector2D &InSize, const FVector2D &ProposedPlacement, const EPopUpOrientation::Type Orientation, FVector2D *const CalculatedPopUpPosition) const
Data Fields
const TSharedPtr< ICursor > Cursor
Protected Member Functions
void BroadcastDisplayMetricsChanged (const FDisplayMetrics &InMetrics)
Trigger the OnDisplayMetricsChanged event with the argument 'InMetrics'.
Protected Attributes
TSharedRef< class FGenericApplicationMessageHandler > MessageHandler
FOnClipboardContentChanged OnClipboardContentChangedEvent
Delegate for clipboard contents change.
FOnDisplayMetricsChanged OnDisplayMetricsChangedEvent
FVirtualKeyboardHiddenEvent VirtualKeyboardHiddenEvent
Delegate for virtual keyboard being shown.
FVirtualKeyboardShownEvent VirtualKeyboardShownEvent
Delegate for virtual keyboard being shown.
Detailed Description
Generic platform application interface.
Definition at line 436 of file GenericApplication.h.
Member Typedef Documentation
FOnConsoleCommandListener
typedef FOnConsoleCommandAdded::FDelegate GenericApplication::FOnConsoleCommandListener
Definition at line 441 of file GenericApplication.h.
Constructor & Destructor Documentation
GenericApplication()
APPLICATIONCORE_API GenericApplication::GenericApplication (const TSharedPtr< ICursor > & InCursor)
Referenced by DECLARE_EVENT_OneParam().
~GenericApplication()
virtual APPLICATIONCORE_API GenericApplication::~GenericApplication () virtual
Member Function Documentation
AddPendingConsoleCommand()
virtual void GenericApplication::AddPendingConsoleCommand (const FString & InCommand) inline virtual
Definition at line 493 of file GenericApplication.h.
ApplicationLicenseValid()
virtual bool GenericApplication::ApplicationLicenseValid (FPlatformUserId PlatformUser = PLATFORMUSERID_NONE) inline virtual
Definition at line 551 of file GenericApplication.h.
References PLATFORMUSERID_NONE.
BroadcastDisplayMetricsChanged()
void GenericApplication::BroadcastDisplayMetricsChanged (const FDisplayMetrics & InMetrics) inline protected
Trigger the OnDisplayMetricsChanged event with the argument 'InMetrics'.
Definition at line 570 of file GenericApplication.h.
References OnDisplayMetricsChangedEvent.
DECLARE_EVENT() [1/2]
GenericApplication::DECLARE_EVENT (FSlateApplication , FOnClipboardContentChanged)
DECLARE_EVENT() [2/2]
GenericApplication::DECLARE_EVENT (FSlateApplication , FVirtualKeyboardHiddenEvent)
DECLARE_EVENT_OneParam() [1/2]
GenericApplication::DECLARE_EVENT_OneParam (FSlateApplication , FVirtualKeyboardShownEvent , FPlatformRect)
Delegate for virtual keyboard being shown/hidden in case UI wants to slide out of the way.
DECLARE_EVENT_OneParam() [2/2]
GenericApplication::DECLARE_EVENT_OneParam (GenericApplication , FOnDisplayMetricsChanged , const FDisplayMetrics &)
References GenericApplication().
DECLARE_MULTICAST_DELEGATE_OneParam()
GenericApplication::DECLARE_MULTICAST_DELEGATE_OneParam (FOnConsoleCommandAdded , const FString &)
DestroyApplication()
virtual void GenericApplication::DestroyApplication () inline virtual
Reimplemented in FLinuxApplication, FNullApplication, and FWindowsApplication.
Definition at line 537 of file GenericApplication.h.
FinishedInputThisFrame()
virtual void GenericApplication::FinishedInputThisFrame () inline virtual
Reimplemented in FWindowsApplication.
Definition at line 555 of file GenericApplication.h.
GetCapture()
virtual void * GenericApplication::GetCapture (void) const inline virtual
Reimplemented in FLinuxApplication, FNullApplication, and FWindowsApplication.
Definition at line 469 of file GenericApplication.h.
GetInitialDisplayMetrics()
virtual void GenericApplication::GetInitialDisplayMetrics (FDisplayMetrics & OutDisplayMetrics) const inline virtual
Reimplemented in FWindowsApplication.
Definition at line 513 of file GenericApplication.h.
References FDisplayMetrics::RebuildDisplayMetrics().
GetInputInterface()
virtual IInputInterface * GenericApplication::GetInputInterface () inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 539 of file GenericApplication.h.
GetMessageHandler()
TSharedRef< FGenericApplicationMessageHandler > GenericApplication::GetMessageHandler () inline
Definition at line 448 of file GenericApplication.h.
References MessageHandler.
GetModifierKeys()
virtual FModifierKeysState GenericApplication::GetModifierKeys () const inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 471 of file GenericApplication.h.
GetTextInputMethodSystem()
virtual ITextInputMethodSystem * GenericApplication::GetTextInputMethodSystem () inline virtual
Function to return the current implementation of the Text Input Method System.
Reimplemented in FMacApplication, and FWindowsApplication.
Definition at line 542 of file GenericApplication.h.
GetWindowTitleAlignment()
virtual EWindowTitleAlignment::Type GenericApplication::GetWindowTitleAlignment () const inline virtual
Gets the horizontal alignment of the window title bar's title text.
Reimplemented in FMacApplication, and FWindowsApplication.
Definition at line 527 of file GenericApplication.h.
References EWindowTitleAlignment::Left.
GetWindowTransparencySupport()
virtual EWindowTransparency GenericApplication::GetWindowTransparencySupport () const inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 532 of file GenericApplication.h.
References None.
GetWindowUnderCursor()
virtual TSharedPtr< FGenericWindow > GenericApplication::GetWindowUnderCursor () inline virtual
Returns
Native window under the mouse cursor.
Reimplemented in FLinuxApplication, FMacApplication, and FNullApplication.
Definition at line 477 of file GenericApplication.h.
GetWorkArea()
virtual FPlatformRect GenericApplication::GetWorkArea (const FPlatformRect & CurrentWindow) const inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 495 of file GenericApplication.h.
References FPlatformRect::Bottom, FPlatformRect::Left, FPlatformRect::Right, and FPlatformRect::Top.
InitializeWindow()
virtual void GenericApplication::InitializeWindow (const TSharedRef< FGenericWindow > & Window, const TSharedRef< FGenericWindowDefinition > & InDefinition, const TSharedPtr< FGenericWindow > & InParent, const bool bShowImmediately) inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 465 of file GenericApplication.h.
IsAllowedToRender()
virtual bool GenericApplication::IsAllowedToRender () const inline virtual
Definition at line 553 of file GenericApplication.h.
IsCursorDirectlyOverSlateWindow()
virtual bool GenericApplication::IsCursorDirectlyOverSlateWindow () const inline virtual
Returns
true if the system cursor is currently directly over a slate window.
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 474 of file GenericApplication.h.
IsGamepadAttached()
virtual bool GenericApplication::IsGamepadAttached () const inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 489 of file GenericApplication.h.
IsMinimized()
virtual bool GenericApplication::IsMinimized () const inline virtual
Reimplemented in FWindowsApplication.
Definition at line 479 of file GenericApplication.h.
IsMouseAttached()
virtual bool GenericApplication::IsMouseAttached () const inline virtual
Reimplemented in FLinuxApplication, FNullApplication, and FWindowsApplication.
Definition at line 487 of file GenericApplication.h.
IsUsingHighPrecisionMouseMode()
virtual bool GenericApplication::IsUsingHighPrecisionMouseMode () const inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 483 of file GenericApplication.h.
IsUsingTrackpad()
virtual bool GenericApplication::IsUsingTrackpad () const inline virtual
Reimplemented in FMacApplication.
Definition at line 485 of file GenericApplication.h.
MakeWindow()
virtual TSharedRef< FGenericWindow > GenericApplication::MakeWindow () inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 463 of file GenericApplication.h.
References MakeShareable().
OnClipboardContentChanged()
FOnClipboardContentChanged & GenericApplication::OnClipboardContentChanged () inline
Definition at line 524 of file GenericApplication.h.
References OnClipboardContentChangedEvent.
OnDisplayMetricsChanged()
FOnDisplayMetricsChanged & GenericApplication::OnDisplayMetricsChanged () inline
Notifies subscribers when any of the display metrics change: e.g.
resolution changes or monitor sare re-arranged.
Definition at line 511 of file GenericApplication.h.
References OnDisplayMetricsChangedEvent.
OnVirtualKeyboardHidden()
FVirtualKeyboardHiddenEvent & GenericApplication::OnVirtualKeyboardHidden () inline
Definition at line 521 of file GenericApplication.h.
References VirtualKeyboardHiddenEvent.
OnVirtualKeyboardShown()
FVirtualKeyboardShownEvent & GenericApplication::OnVirtualKeyboardShown () inline
Definition at line 518 of file GenericApplication.h.
References VirtualKeyboardShownEvent.
PollGameDeviceState()
virtual void GenericApplication::PollGameDeviceState (const float TimeDelta) inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 455 of file GenericApplication.h.
ProcessDeferredEvents()
virtual void GenericApplication::ProcessDeferredEvents (const float TimeDelta) inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 459 of file GenericApplication.h.
PumpMessages()
virtual void GenericApplication::PumpMessages (const float TimeDelta) inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 457 of file GenericApplication.h.
RegisterConsoleCommandListener()
virtual void GenericApplication::RegisterConsoleCommandListener (const FOnConsoleCommandListener & InListener) inline virtual
Definition at line 491 of file GenericApplication.h.
SendAnalytics()
virtual void GenericApplication::SendAnalytics (IAnalyticsProvider * Provider) inline virtual
Send any analytics captured by the application.
Reimplemented in FMacApplication.
Definition at line 545 of file GenericApplication.h.
SetCapture()
virtual void GenericApplication::SetCapture (const TSharedPtr< FGenericWindow > & InWindow) inline virtual
Reimplemented in FLinuxApplication, FNullApplication, and FWindowsApplication.
Definition at line 467 of file GenericApplication.h.
SetHighPrecisionMouseMode()
virtual void GenericApplication::SetHighPrecisionMouseMode (const bool Enable, const TSharedPtr< FGenericWindow > & InWindow) inline virtual
Reimplemented in FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 481 of file GenericApplication.h.
References Enable.
SetMessageHandler()
virtual void GenericApplication::SetMessageHandler (const TSharedRef< FGenericApplicationMessageHandler > & InMessageHandler) inline virtual
Reimplemented in FAndroidApplication, FIOSApplication, FLinuxApplication, FMacApplication, FNullApplication, and FWindowsApplication.
Definition at line 446 of file GenericApplication.h.
References MessageHandler.
ShowSystemHelp()
virtual void GenericApplication::ShowSystemHelp () inline virtual
Definition at line 549 of file GenericApplication.h.
SupportsSystemHelp()
virtual bool GenericApplication::SupportsSystemHelp () const inline virtual
Definition at line 547 of file GenericApplication.h.
Tick()
virtual void GenericApplication::Tick (const float TimeDelta) inline virtual
Reimplemented in FAndroidApplication.
Definition at line 461 of file GenericApplication.h.
TryCalculatePopupWindowPosition()
virtual bool GenericApplication::TryCalculatePopupWindowPosition (const FPlatformRect & InAnchor, const FVector2D & InSize, const FVector2D & ProposedPlacement, const EPopUpOrientation::Type Orientation, FVector2D *const CalculatedPopUpPosition) const inline virtual
Definition at line 506 of file GenericApplication.h.
Field Documentation
Cursor
const TSharedPtr< ICursor > GenericApplication::Cursor
Definition at line 558 of file GenericApplication.h.
MessageHandler
TSharedRef< class FGenericApplicationMessageHandler > GenericApplication::MessageHandler protected
Definition at line 562 of file GenericApplication.h.
Referenced by GetMessageHandler(), and SetMessageHandler().
OnClipboardContentChangedEvent
FOnClipboardContentChanged GenericApplication::OnClipboardContentChangedEvent protected
Delegate for clipboard contents change.
Definition at line 582 of file GenericApplication.h.
Referenced by OnClipboardContentChanged().
OnDisplayMetricsChangedEvent
FOnDisplayMetricsChanged GenericApplication::OnDisplayMetricsChangedEvent protected
Definition at line 573 of file GenericApplication.h.
Referenced by BroadcastDisplayMetricsChanged(), and OnDisplayMetricsChanged().
VirtualKeyboardHiddenEvent
FVirtualKeyboardHiddenEvent GenericApplication::VirtualKeyboardHiddenEvent protected
Delegate for virtual keyboard being shown.
Definition at line 579 of file GenericApplication.h.
Referenced by OnVirtualKeyboardHidden().
VirtualKeyboardShownEvent
FVirtualKeyboardShownEvent GenericApplication::VirtualKeyboardShownEvent protected
Delegate for virtual keyboard being shown.
Definition at line 576 of file GenericApplication.h.
Referenced by OnVirtualKeyboardShown().
The documentation for this class was generated from the following file:
GenericApplication.h