Unreal Engine 5.6 C++ API: AnimInstanceProxy.h File Reference
AnimInstanceProxy.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Animation/AnimTypes.h"
#include "Animation/AnimationAsset.h"
#include "Animation/AnimBlueprint.h"
#include "Animation/AnimClassInterface.h"
#include "Animation/AnimSync.h"
#include "Animation/AnimInertializationRequest.h"
#include "AnimInstanceProxy.generated.h"
Data Structures
struct FQueuedDrawDebugItem
struct FQueuedDrawDebugItem::FVectorEntry
Namespaces
namespace EMessageSeverity
The severity of the message type.
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Anim
Macros
#define ENABLE_ANIM_DRAW_DEBUG (1 && !(UE_BUILD_SHIPPING || UE_BUILD_TEST))
#define ENABLE_ANIM_LOGGING (1 && !NO_LOGGING && !(UE_BUILD_SHIPPING || UE_BUILD_TEST))
Functions
DECLARE_DELEGATE_RetVal (bool, FCanTakeTransition)
DECLARE_DELEGATE_ThreeParams (FOnGraphStateChanged, const struct FAnimNode_StateMachine &, int32, int32)
UENUM () namespace EDrawDebugItemType
USTRUCT ()) struct FAnimInstanceProxy
Proxy object passed around during animation tree update in lieu of a UAnimInstance.
Variables
const FName NAME_AnimBlueprintLog
const FName NAME_AnimGraph
const FName NAME_Evaluate
const FName NAME_Update
Macro Definition Documentation
ENABLE_ANIM_DRAW_DEBUG
#define ENABLE_ANIM_DRAW_DEBUG (1 && !(UE_BUILD_SHIPPING || UE_BUILD_TEST))
Definition at line 62 of file AnimInstanceProxy.h.
ENABLE_ANIM_LOGGING
#define ENABLE_ANIM_LOGGING (1 && !NO_LOGGING && !(UE_BUILD_SHIPPING || UE_BUILD_TEST))
Definition at line 65 of file AnimInstanceProxy.h.
Function Documentation
DECLARE_DELEGATE_RetVal()
DECLARE_DELEGATE_RetVal (bool , FCanTakeTransition)
DECLARE_DELEGATE_ThreeParams()
DECLARE_DELEGATE_ThreeParams (FOnGraphStateChanged , const struct FAnimNode_StateMachine & , int32 , int32)
UENUM()
UENUM ()
Definition at line 75 of file AnimInstanceProxy.h.
References Capsule, Circle, Cone, CoordinateSystem, Line, Point, and Sphere.
USTRUCT()
USTRUCT ()
Proxy object passed around during animation tree update in lieu of a UAnimInstance.
Get the last DeltaSeconds passed into PreUpdate()
Get the last time dilation, gleaned from world settings
Get the sync group we are currently reading from
Get the ungrouped active player we are currently reading from
Queues an Anim Notify from the shared list on our generated class
Trigger any anim notifies
Check whether we should extract root motion
Save a pose snapshot to the internal snapshot cache
Add an empty pose snapshot to the internal snapshot cache (or recycle an existing pose snapshot if the name is already in use)
Remove a previously saved pose snapshot from the internal snapshot cache
Get a cached pose snapshot by name
Access various counters
Access root motion params
Access UObject base of UAnimInstance
Gets an unchecked (can return nullptr) node given an index into the node property array
Gets an unchecked (can return nullptr) node given an index into the node property array
Gets a checked node given an index into the node property array
Gets a checked node given an index into the node property array
Gets a checked node given an index into the node property array
Gets a checked node given an index into the node property array
Gets an unchecked (can return nullptr) node given an index into the node property array
Gets an unchecked (can return nullptr) node given an index into the node property array
const access to required bones array
access to required bones array
Access to LODLevel
Get the current skeleton we are using. Note that this will return nullptr outside of pre/post update
Get the current skeletal mesh component we are running on. Note that this will return nullptr outside of pre/post update
Get the current main instance proxy. Note that this will return nullptr outside of pre/post update, and may return nullptr anyway if we dont have a main instance
Get Slot Node Weight : this returns new Slot Node Weight, Source Weight, Original TotalNodeWeight this 3 values can't be derived from each other
Parameters
SlotNodeName : the name of the slot node you're querying
out_SlotNodeWeight : The node weight for this slot node in the range of [0, 1]
out_SourceWeight : The Source weight for this node.
out_TotalNodeWeight : Total weight of this node
Evaluate a pose for a named montage slot
Register a named slot
Check whether we have a valid root node
Todo
: remove after deprecation
Gather debug data from this instance proxy and the blend tree for display
Gather debug data from this instance proxy and the specified blend tree root for display
Gets the runtime instance of the specified state machine by Name
Gets the runtime instance of the specified state machine
Get the machine description for the specified instance. Does not rely on PRIVATE_MachineDescription being initialized
Get the index of the specified instance asset player. Useful to pass to GetInstanceAssetPlayerLength (etc.). Passing NAME_None to InstanceName will return the first (assumed only) player instance index found.
Reset any dynamics running simulation-style updates (e.g. on teleport, time skip etc.)
Returns all Animation Nodes of FAnimNode_AssetPlayerBase class within the specified (named) Animation Graph
Returns all Animation Nodes of FAnimNode_AssetPlayerBase class within the specified (named) Animation Graph
Returns all Animation Nodes of FAnimNode_AssetPlayerRelevancyBase class within the specified (named) Animation Graph
Returns all Animation Nodes of FAnimNode_AssetPlayerRelevancyBase class within the specified (named) Animation Graph
Returns true if SyncGroupName is valid (exists, and if is based on markers, has valid markers)
Get the relative transform of the component we are running on
Get the component to world transform of the component we are running on
Get the transform of the actor we are running on
Get the debug data for this instance's anim bp
Add anim notifies to the proxies notify queue
Parameters
NewNotifies The notifies to add
InstanceWeight The effective weight of the notifies (used for trigger filtering)
Set the optional animation interpolation type override. When not set, it will use the interpolation type set inside the animation asset.
Get the interpolation type override. If not set, it will use the iterpolation type set inside the animation asset.
Only restricted classes can access the protected interface
Called when our anim instance is being initialized
Called when our anim instance is being uninitialized
Let us copy the full notify queue from the last frame
Called before update so we can copy any data we need
Called during PreUpdate, if SkelMesh LOD has changed since last update
Update override point
Updates the anim graph
Updates the anim graph using a specified root node
Called on the game thread pre-evaluate.
Called when the anim instance is being initialized. If we are not using a blueprint instance, this root node can be provided
Called when the anim instance is being initialized. If we are not using a blueprint instance, these nodes can be provided
Cache bones override point. You should call CacheBones on any nodes that need it here. bBoneCachesInvalidated is used to only perform this when needed (e.g. when a LOD changes), as it is usually an expensive operation.
Cache bones override point. You should call CacheBones on any nodes that need it here. bBoneCachesInvalidated is used to only perform this when needed (e.g. when a LOD changes), as it is usually an expensive operation.
Evaluate override point
Returns
true if this function is implemented, false otherwise. Note: the node graph will not be evaluated if this function returns true
Evaluate override point with root node override.
Returns
true if this function is implemented, false otherwise. Note: the node graph will not be evaluated if this function returns true
Called after update so we can copy any data we need
Called after evaluate so we can do any game thread work we need to
Copy any UObjects we might be using. Called Pre-update and pre-evaluate.
Clear any UObjects we might be using. Called at the end of the post-evaluate phase. This is to ensure that objects are not used by anything apart from animation nodes. Please make sure to call the base implementation if this is overridden.
Calls Update(), updates the anim graph, ticks asset players
Calls Update(), updates the anim graph from the specified root, ticks asset players
Evaluates the anim graph if Evaluate() returns false
Evaluates the anim graph given the specified root if Evaluate() returns false
Evaluates the anim graph
Evaluates the anim graph given the specified root
Returns the baked sync group index from the compile step
Get global weight in AnimGraph for this slot node. Note: this is the weight of the node, not the weight of any potential montage it is playing.
Get Global weight of any montages this slot node is playing. If this slot is not currently playing a montage, it will return 0.
Get local weight of any montages this slot node is playing. If this slot is not currently playing a montage, it will return 0. This is double buffered, will return last frame data if called from Update or Evaluate.
Get local weight of any montages this slot is playing. If this slot is not current playing a montage, it will return 0. This will return up to date data if called during Update or Evaluate.
Recalculate Required Bones [RequiredBones] Is called when bRequiredBonesUpToDate = false The provided asset must be a SkeletalMesh or a Skeleton.
Recalculate required curve list for animation - if you call RecalcRequiredBones, this should already happen
Get Currently active montage evaluation state. Note that there might be multiple Active at the same time. This will only return the first active one it finds.
Access montage array data
Access montage array data
Check whether we have active morph target curves
Gets the most relevant asset player in a specified state
Gets the most relevant asset player in a specified state
Gets an unchecked (can return nullptr) node given a property of the anim instance
Gets the length in seconds of the asset referenced in an asset player node
Get the current accumulated time in seconds for an asset player node
Get the current accumulated time as a fraction for an asset player node
Get the time in seconds from the end of an animation in an asset player node
Get the time as a fraction of the asset length of an animation in an asset player node
Get the blend weight of a specified state
Get the blend weight of a specified state
Get the current elapsed time of a state within the specified state machine
Get the crossfade duration of a specified transition
Get the elapsed time in seconds of a specified transition
Get the elapsed time as a fraction of the crossfade duration of a specified transition
Get the time remaining in seconds for the most relevant animation in the source state
Get the time remaining as a fraction of the duration for the most relevant animation in the source state
Get the length in seconds of the most relevant animation in the source state
Get the current accumulated time in seconds for the most relevant animation in the source state
Get the current accumulated time as a fraction of the length of the most relevant animation in the source state
Get whether a particular notify state was active in any state machine last tick.
Get whether a particular notify state is active in a specific state machine last tick.
Get whether the most relevant animation was in a particular notify state last tick.
Get whether the most relevant animation triggered the given notify last tick.
Get whether the most relevant animation triggered the given notify last tick.
Get whether a particular notify type was active in a specific state machine last tick.
Get whether an animation notify of a given type was triggered last tick.
Get whether the animation notify with the specified name triggered last tick.
Get whether the given state machine triggered the animation notify with the specified name last tick.
Attempts to queue a transition request, returns true if successful
Removes all queued transition requests with the given event name
Removes all queued transition requests
Returns whether or not the given event transition request has been queued
Behaves like QueryTransitionEvent but additionally marks the event for consumption
Bind any native delegates that we have set up
Gets the runtime instance desc of the state machine specified by name
Gets the index of the state machine matching MachineName
Gets the index of the state machine
Initialize the root node - split into a separate function for backwards compatibility (initialization order) reasons
Initialize the specified root node
Manually add object references to GC
Allow nodes to register log messages to be processed on the game thread
Get the current value of all animation curves
Reset Animation Curves
Pushes blended heap curve to output curves in the proxy using required bones cached data
Update curves once evaluation has taken place. Mostly pushes curves to materials/morphs
Check whether we have any active curves
Add a curve value
Custom proxy Init/Cache/Update/Evaluate functions
Reset the sync system to its starting state
Send any queued DrawDebug commands and reset the queue
Executes the provided functor on each valid state machine on this anim instance
Evaluate the slot when there are blend spaces involved in any of the active anim montages.
Initialize cached class data - state machines, pre-update nodes etc.
The component to world transform of the component we are running on
The relative transform of the component we are running on
The transform of the actor we are running on
Object ptr to our UAnimInstance
Our anim blueprint generated class
Skeleton we are using, only used for comparison purposes. Note that this will be nullptr outside of pre/post update
Skeletal mesh component we are attached to. Note that this will be nullptr outside of pre/post update
Cached ptr to the main instance proxy, which may be "this"
The last time passed into PreUpdate()
The last dime dilation (gleaned from world settings)
Actor name for debug logging purposes
Anim instance name for debug purposes
Anim graph
Default linked instance input node if available
Map of layer name to saved pose nodes to process after the graph has been updated
Synchronizes animations according to sync groups/markers
Buffers containing read/write buffers for all current machine weights
Buffers containing read/write buffers for all current state weights
Map that transforms state class indices to base offsets into the weight array
Animation Notifies that has been triggered in the latest tick
Curves in an easily looked-up form
Material parameters that we had been changing and now need to clear
Optional override of the animation interpolation type. If not set, it is ignored.
Temporary array of bone indices required this frame. Should be subset of Skeleton and Mesh's RequiredBones. Shared between all anim instances on a skeletal mesh component if it has a skeletal mesh and a skeleton present.
LODLevel used by RequiredBones
Counter used to control CacheBones recursion behavior - makes sure we cache bones correctly when recursing into different subgraphs
During animation update and eval, records the number of frames we will skip due to URO
Copy of UAnimInstance::MontageInstances data used for update & evaluation
Delegate fired on the game thread before update occurs
When GameThreadPreUpdateNodes are disabled due to LOD, they are stored here. To be potentially restored later.
All nodes that need to be reset on DynamicReset()
Native transition rules
Native state entry bindings
Native state exit bindings
Array of snapshots. Each entry contains a name for finding specific pose snapshots
Logged message queues. Allows nodes to report messages to MessageLog even though they may be running on a worked thread
Cache of guids generated from previously sent messages so we can stop spam
Scope guard to prevent duplicate work on re-entracy
When RequiredBones mapping has changed, AnimNodes need to update their bones caches.
We can defer initialization until first update
Definition at line 142 of file AnimInstanceProxy.h.
References Asset, Cast(), Color, Component, ensureAlways, Evaluate, FVector, GENERATED_USTRUCT_BODY, IAnimClassInterface::GetActualAnimClass(), Initialize, Instance, meta, NotifyName, operator=(), Property, FGraphTraversalCounter::Reset(), Rotation, Scale, Skeleton, Sync, Transient, TSequenceHistory< HistorySize >::Size, UE_DEPRECATED, UE::Math::TVector2< double >::UnitVector, UPROPERTY, UE::Math::TVector< double >::UpVector, and Value.
Variable Documentation
NAME_AnimBlueprintLog
const FName NAME_AnimBlueprintLog extern
NAME_AnimGraph
const FName NAME_AnimGraph extern
NAME_Evaluate
const FName NAME_Evaluate extern
NAME_Update
const FName NAME_Update extern