Unreal Engine 5.6 C++ API: SkyAtmosphereComponent.h File Reference
SkyAtmosphereComponent.h File Reference
#include "CoreMinimal.h"
#include "Components/SceneComponent.h"
#include "EngineDefines.h"
#include "GameFramework/Info.h"
#include "Misc/Guid.h"
#include "RenderResource.h"
#include "StateStream/SkyAtmosphereStateStreamHandle.h"
#include "SkyAtmosphereComponent.generated.h"
Data Structures
class ASkyAtmosphere
class USkyAtmosphereComponent
Functions
UENUM() enum class ESkyAtmosphereTransformMode UCLASS ()
A component that represents a planet atmosphere material and simulates sky and light scattering within it.
USTRUCT () struct FTentDistribution
Variables
ClassGroup = Fog
UENUM() enum class ESkyAtmosphereTransformMode editinlinenew
hidecategories = (Info, Object, Input)
UENUM() enum class ESkyAtmosphereTransformMode meta = (BlueprintSpawnableComponent)
Function Documentation
UCLASS()
UENUM() enum class ESkyAtmosphereTransformMode UCLASS ()
A component that represents a planet atmosphere material and simulates sky and light scattering within it.
A placeable actor that represents a planet atmosphere material and simulates sky and light scattering within it.
See also
https://docs.unrealengine.com/en-US/Engine/Actors/FogEffects/SkyAtmosphere/index.html
USTRUCT()
USTRUCT ()
Definition at line 19 of file SkyAtmosphereComponent.h.
References BlueprintType, Category, GENERATED_USTRUCT_BODY, meta, UPROPERTY, and Width.
Variable Documentation
ClassGroup
ClassGroup = Fog
Definition at line 323 of file SkyAtmosphereComponent.h.
editinlinenew
UENUM() enum class ESkyAtmosphereTransformMode editinlinenew
Definition at line 46 of file SkyAtmosphereComponent.h.
hidecategories
hidecategories = (Info, Object, Input)
Definition at line 323 of file SkyAtmosphereComponent.h.
meta
UENUM() enum class ESkyAtmosphereTransformMode meta = (BlueprintSpawnableComponent)
Definition at line 46 of file SkyAtmosphereComponent.h.
Referenced by USkyAtmosphereComponent::UFUNCTION(), USkyAtmosphereComponent::UFUNCTION(), USkyAtmosphereComponent::UFUNCTION(), USkyAtmosphereComponent::UFUNCTION(), USkyAtmosphereComponent::UFUNCTION(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), USkyAtmosphereComponent::UPROPERTY(), and USkyAtmosphereComponent::UPROPERTY().