Unreal Engine 5.6 C++ API: FUnixTime Struct Reference
FUnixTime Struct Reference
Unix implementation of the Time OS functions.
#include "UnixPlatformTime.h"
Static Public Member Functions
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
static FORCEINLINE uint32 Cycles ()
static FORCEINLINE uint64 Cycles64 ()
static FCPUTime GetCPUTime ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
static FCPUTime GetThreadCPUTime ()
static double InitTiming ()
static void PrintCalibrationLog ()
Calibration log to be printed at later time.
static FORCEINLINE double Seconds ()
static bool UpdateCPUTime (float DeltaSeconds)
static bool UpdateThreadCPUTime (float=0.0)
Static Public Member Functions inherited from FGenericPlatformTime
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
Registers automatic updates of Game Thread CPU utilization.
static FCPUTime GetCPUTime ()
static double GetLastIntervalCPUTimeInSeconds ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
Gets the per-thread CPU processing time (kernel + user) from the last update.
static double GetSecondsPerCycle ()
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
static double GetSecondsPerCycle64 ()
Returns seconds per cycle, to pair with Cycles64().
static FCPUTime GetThreadCPUTime ()
Gets current threads CPU Utilization.
static FString PrettyTime (double Seconds)
Returns a pretty-string for a time given in seconds.
static uint64 SecondsToCycles64 (double Seconds)
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
static TCHAR * StrDate (TCHAR *Dest, SIZE_T DestSize)
Get the system date.
static TCHAR * StrTime (TCHAR *Dest, SIZE_T DestSize)
Get the system time.
static const TCHAR * StrTimestamp ()
Returns a timestamp string built from the current date and time.
static float ToMilliseconds (const uint32 Cycles)
Converts cycles to milliseconds.
static double ToMilliseconds64 (const uint64 Cycles)
Converts 64 bit cycles to milliseconds.
static float ToSeconds (const uint32 Cycles)
Converts cycles to seconds.
static double ToSeconds64 (const uint64 Cycles)
Converts 64 bit cycles to seconds.
static bool UpdateCPUTime (float DeltaTime)
Updates CPU utilization, called through a delegate from the Core ticker.
static bool UpdateThreadCPUTime (float=0.0)
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Static Private Member Functions
static int CalibrateAndSelectClock ()
Benchmarks clock_gettime(), possibly switches to something else is too slow.
static uint64 CallsPerSecondBenchmark (clockid_t BenchClockId, const char *BenchClockIdName)
Returns number of time we can call the clock per second.
Static Private Attributes
static char CalibrationLog [4096]
Log information about calibrating the clock.
static int ClockSource
Clock source to use.
Additional Inherited Members
Static Protected Attributes inherited from FGenericPlatformTime
static double LastIntervalCPUTimeInSeconds
static double SecondsPerCycle
static double SecondsPerCycle64
Detailed Description
Unix implementation of the Time OS functions.
Definition at line 17 of file UnixPlatformTime.h.
Member Function Documentation
AutoUpdateGameThreadCPUTime()
void FUnixTime::AutoUpdateGameThreadCPUTime (double UpdateInterval) static
CalibrateAndSelectClock()
int FUnixTime::CalibrateAndSelectClock () static private
Benchmarks clock_gettime(), possibly switches to something else is too slow.
Unix-specific.
Referenced by Cycles(), and Seconds().
CallsPerSecondBenchmark()
uint64 FUnixTime::CallsPerSecondBenchmark (clockid_t BenchClockId, const char * BenchClockIdName) static private
Returns number of time we can call the clock per second.
Cycles()
FORCEINLINE uint32 FUnixTime::Cycles () inline static
Definition at line 33 of file UnixPlatformTime.h.
References CalibrateAndSelectClock(), ClockSource, FORCEINLINE, and UNLIKELY.
Cycles64()
FORCEINLINE uint64 FUnixTime::Cycles64 () inline static
Definition at line 45 of file UnixPlatformTime.h.
References FORCEINLINE.
GetCPUTime()
FCPUTime FUnixTime::GetCPUTime () static
GetLastIntervalThreadCPUTimeInSeconds()
double FUnixTime::GetLastIntervalThreadCPUTimeInSeconds () static
GetThreadCPUTime()
FCPUTime FUnixTime::GetThreadCPUTime () static
InitTiming()
double FUnixTime::InitTiming () static
PrintCalibrationLog()
void FUnixTime::PrintCalibrationLog () static
Calibration log to be printed at later time.
Seconds()
FORCEINLINE double FUnixTime::Seconds () inline static
Definition at line 21 of file UnixPlatformTime.h.
References CalibrateAndSelectClock(), ClockSource, FORCEINLINE, and UNLIKELY.
UpdateCPUTime()
bool FUnixTime::UpdateCPUTime (float DeltaSeconds) static
UpdateThreadCPUTime()
bool FUnixTime::UpdateThreadCPUTime (float = 0.0) static
Field Documentation
CalibrationLog
char FUnixTime::CalibrationLog[4096] static private
Log information about calibrating the clock.
Definition at line 71 of file UnixPlatformTime.h.
ClockSource
int FUnixTime::ClockSource static private
Clock source to use.
Definition at line 68 of file UnixPlatformTime.h.
Referenced by Cycles(), and Seconds().
The documentation for this struct was generated from the following file:
UnixPlatformTime.h