Unreal Engine 5.6 C++ API: FOctreeNodeContext Class Reference
FOctreeNodeContext Class Reference
The context of an octree node, derived from the traversal of the tree.
#include "GenericOctree.h"
Public Types
enum { LoosenessDenominator = 16 }
The node bounds are expanded by their extent divided by LoosenessDenominator.
using FReal = FVector4::FReal
Public Member Functions
FOctreeNodeContext ()
Default constructor.
FOctreeNodeContext (const FBoxCenterAndExtent &InBounds)
Initialization constructor.
FOctreeNodeContext (const FBoxCenterAndExtent &InBounds, uint32 InInCullBits, uint32 InOutCullBits)
Initialization constructor.
FOctreeNodeContext (uint32 InInCullBits, uint32 InOutCullBits)
Initialization constructor, this one is used when we done care about the box anymore.
FOctreeNodeContext GetChildContext (FOctreeChildNodeRef ChildRef) const
Child node initialization constructor.
void GetChildContext (FOctreeChildNodeRef ChildRef, FOctreeNodeContext *ChildContext) const
Construct a child context given the child ref.
FOctreeNodeContext GetChildContext (FOctreeChildNodeRef ChildRef, uint32 InInCullBits, uint32 InOutCullBits) const
Child node initialization constructor.
VectorRegister GetChildOffsetVec (int i) const
FOctreeChildNodeRef GetContainingChild (const FBoxCenterAndExtent &BoundingBox) const
Determines which of the octree node's children contain the whole bounding box, if any.
FOctreeChildNodeSubset GetIntersectingChildren (const FBoxCenterAndExtent &BoundingBox) const
Determines which of the octree node's children intersect with a bounding box.
Data Fields
FBoxCenterAndExtent Bounds
The bounds of the node.
FReal ChildCenterOffset
The offset of the childrens' centers from the center of this node.
FReal ChildExtent
The extent of the node's children.
uint32 InCullBits
Bits used for culling, semantics left up to the caller (except that it is always set to zero at the root).
uint32 OutCullBits
Bits used for culling, semantics left up to the caller (except that it is always set to zero at the root).
Detailed Description
The context of an octree node, derived from the traversal of the tree.
Definition at line 251 of file GenericOctree.h.
Member Typedef Documentation
FReal
using FOctreeNodeContext::FReal = FVector4::FReal
Definition at line 255 of file GenericOctree.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The node bounds are expanded by their extent divided by LoosenessDenominator.
Enumerator
LoosenessDenominator
Definition at line 258 of file GenericOctree.h.
Constructor & Destructor Documentation
FOctreeNodeContext() [1/4]
FOctreeNodeContext::FOctreeNodeContext () inline
Default constructor.
Definition at line 276 of file GenericOctree.h.
Referenced by GetChildContext(), GetChildContext(), and GetChildContext().
FOctreeNodeContext() [2/4]
FOctreeNodeContext::FOctreeNodeContext (uint32 InInCullBits, uint32 InOutCullBits) inline
Initialization constructor, this one is used when we done care about the box anymore.
Definition at line 280 of file GenericOctree.h.
References InCullBits, and OutCullBits.
FOctreeNodeContext() [3/4]
FOctreeNodeContext::FOctreeNodeContext (const FBoxCenterAndExtent & InBounds) inline
Initialization constructor.
Definition at line 287 of file GenericOctree.h.
References Bounds, ChildCenterOffset, ChildExtent, and LoosenessDenominator.
FOctreeNodeContext() [4/4]
FOctreeNodeContext::FOctreeNodeContext (const FBoxCenterAndExtent & InBounds, uint32 InInCullBits, uint32 InOutCullBits) inline
Initialization constructor.
Definition at line 299 of file GenericOctree.h.
References Bounds, ChildCenterOffset, ChildExtent, InCullBits, LoosenessDenominator, and OutCullBits.
Member Function Documentation
GetChildContext() [1/3]
FOctreeNodeContext FOctreeNodeContext::GetChildContext (FOctreeChildNodeRef ChildRef) const inline nodiscard
Child node initialization constructor.
Definition at line 326 of file GenericOctree.h.
References FOctreeNodeContext(), Bounds, ChildExtent, GetChildOffsetVec(), FOctreeChildNodeRef::Index, LocalBounds, MakeVectorRegister(), VectorAdd(), VectorLoadAligned(), VectorMultiply(), VectorSetFloat1(), and VectorStoreAligned().
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithBoundsTestInternal(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindFirstElementWithBoundsTestInternal(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNearbyElementsInternal(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNodesWithPredicateInternal().
GetChildContext() [2/3]
void FOctreeNodeContext::GetChildContext (FOctreeChildNodeRef ChildRef, FOctreeNodeContext * ChildContext) const inline
Construct a child context given the child ref.
Optimized to remove all LHS.
Definition at line 336 of file GenericOctree.h.
References FOctreeNodeContext(), Bounds, FBoxCenterAndExtent::Center, ChildCenterOffset, ChildExtent, FBoxCenterAndExtent::Extent, GetChildOffsetVec(), FOctreeChildNodeRef::Index, LoosenessDenominator, MakeVectorRegister(), VectorAdd(), VectorLoadAligned(), VectorMultiply(), VectorSetFloat1(), VectorStoreAligned(), and UE::Math::TVector4< T >::X.
GetChildContext() [3/3]
FOctreeNodeContext FOctreeNodeContext::GetChildContext (FOctreeChildNodeRef ChildRef, uint32 InInCullBits, uint32 InOutCullBits) const inline nodiscard
Child node initialization constructor.
Definition at line 349 of file GenericOctree.h.
References FOctreeNodeContext(), Bounds, ChildExtent, GetChildOffsetVec(), FOctreeChildNodeRef::Index, LocalBounds, MakeVectorRegister(), VectorAdd(), VectorLoadAligned(), VectorMultiply(), VectorSetFloat1(), and VectorStoreAligned().
GetChildOffsetVec()
VectorRegister FOctreeNodeContext::GetChildOffsetVec (int i) const inline nodiscard
Definition at line 312 of file GenericOctree.h.
References A, ChildCenterOffset, MakeVectorRegister(), Mask, VectorIntAnd(), VectorIntCompareEQ(), VectorIntLoad1(), VectorSelect(), VectorSetFloat1(), and X.
Referenced by GetChildContext(), GetChildContext(), and GetChildContext().
GetContainingChild()
FOctreeChildNodeRef FOctreeNodeContext::GetContainingChild (const FBoxCenterAndExtent & BoundingBox) const nodiscard
Determines which of the octree node's children contain the whole bounding box, if any.
Parameters
BoundingBox - The bounding box to check for intersection with.
Returns
The octree's node that the bounding box is farthest from the outside edge of, or an invalid node ref if it's not contained by any of the children.
References BoundingBox.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNearbyElementsInternal().
GetIntersectingChildren()
FOctreeChildNodeSubset FOctreeNodeContext::GetIntersectingChildren (const FBoxCenterAndExtent & BoundingBox) const nodiscard
Determines which of the octree node's children intersect with a bounding box.
Parameters
BoundingBox - The bounding box to check for intersection with.
Returns
A subset of the children's nodes that intersect the bounding box.
References BoundingBox.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithBoundsTestInternal(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindFirstElementWithBoundsTestInternal().
Field Documentation
Bounds
FBoxCenterAndExtent FOctreeNodeContext::Bounds
The bounds of the node.
Definition at line 261 of file GenericOctree.h.
Referenced by FOctreeNodeContext(), FOctreeNodeContext(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNodesWithPredicateInternal(), GetChildContext(), GetChildContext(), and GetChildContext().
ChildCenterOffset
FReal FOctreeNodeContext::ChildCenterOffset
The offset of the childrens' centers from the center of this node.
Definition at line 267 of file GenericOctree.h.
Referenced by FOctreeNodeContext(), FOctreeNodeContext(), GetChildContext(), and GetChildOffsetVec().
ChildExtent
FReal FOctreeNodeContext::ChildExtent
The extent of the node's children.
Definition at line 264 of file GenericOctree.h.
Referenced by FOctreeNodeContext(), FOctreeNodeContext(), GetChildContext(), GetChildContext(), and GetChildContext().
InCullBits
uint32 FOctreeNodeContext::InCullBits
Bits used for culling, semantics left up to the caller (except that it is always set to zero at the root).
This does not consume storage because it is leftover in the padding.
Definition at line 270 of file GenericOctree.h.
Referenced by FOctreeNodeContext(), FOctreeNodeContext(), and TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::PushChild().
OutCullBits
uint32 FOctreeNodeContext::OutCullBits
Bits used for culling, semantics left up to the caller (except that it is always set to zero at the root).
This does not consume storage because it is leftover in the padding.
Definition at line 273 of file GenericOctree.h.
Referenced by FOctreeNodeContext(), FOctreeNodeContext(), and TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::PushChild().
The documentation for this class was generated from the following file:
GenericOctree.h