Unreal Engine 5.6 C++ API: FBlake3Hash Struct Reference
FBlake3Hash Struct Reference
Stores a BLAKE3 hash.
#include "Blake3.h"
Public Types
using ByteArray = uint8[32]
Public Member Functions
FBlake3Hash ()=default
Construct a zero hash.
FBlake3Hash (const ByteArray &Hash)
Construct a hash from an array of 32 bytes.
FBlake3Hash (FAnsiStringView HexHash)
Construct a hash from a 64-character hex string.
FBlake3Hash (FUtf8StringView HexHash)
FBlake3Hash (FWideStringView HexHash)
ByteArray & GetBytes ()
Returns a reference to the raw byte array for the hash.
const ByteArray & GetBytes () const
bool IsZero () const
Returns whether this is a zero hash.
bool operator!= (const FBlake3Hash &B) const
bool operator< (const FBlake3Hash &B) const
bool operator== (const FBlake3Hash &B) const
void Reset ()
Reset this to a zero hash.
Static Public Member Functions
static FBlake3Hash FromView (FMemoryView Hash)
Construct a hash from a view of 32 bytes.
Static Public Attributes
static const FBlake3Hash Zero
A zero hash.
Private Attributes
ByteArray Hash {}
Friends
uint32 GetTypeHash (const FBlake3Hash &Value)
FArchive & operator<< (FArchive &Ar, FBlake3Hash &Value)
Detailed Description
Stores a BLAKE3 hash.
Definition at line 26 of file Blake3.h.
Member Typedef Documentation
ByteArray
using FBlake3Hash::ByteArray = uint8[32]
Definition at line 29 of file Blake3.h.
Constructor & Destructor Documentation
FBlake3Hash() [1/5]
FBlake3Hash::FBlake3Hash () default
Construct a zero hash.
References FBlake3Hash(), and Hash.
Referenced by FBlake3Hash(), FromView(), GetTypeHash, operator!=(), operator<(), operator<<, operator==(), and Reset().
FBlake3Hash() [2/5]
FBlake3Hash::FBlake3Hash (const ByteArray & Hash) inline explicit
Construct a hash from an array of 32 bytes.
Definition at line 127 of file Blake3.h.
References Hash, and FMemory::Memcpy().
FBlake3Hash() [3/5]
FBlake3Hash::FBlake3Hash (FAnsiStringView HexHash) inline explicit
Construct a hash from a 64-character hex string.
Definition at line 132 of file Blake3.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
FBlake3Hash() [4/5]
FBlake3Hash::FBlake3Hash (FWideStringView HexHash) inline explicit
Definition at line 138 of file Blake3.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
FBlake3Hash() [5/5]
FBlake3Hash::FBlake3Hash (FUtf8StringView HexHash) inline explicit
Definition at line 144 of file Blake3.h.
References check, Hash, UE::String::HexToBytes(), and TStringView< CharType >::Len().
Member Function Documentation
FromView()
FBlake3Hash FBlake3Hash::FromView (FMemoryView Hash) inline static
Construct a hash from a view of 32 bytes.
Definition at line 150 of file Blake3.h.
References FBlake3Hash(), checkf, TMemoryView< DataType >::GetData(), TMemoryView< DataType >::GetSize(), Hash, FMemory::Memcpy(), TEXT, and UINT64_FMT.
GetBytes() [1/2]
ByteArray & FBlake3Hash::GetBytes () inline
Returns a reference to the raw byte array for the hash.
Definition at line 52 of file Blake3.h.
References Hash.
Referenced by FIoHash::FIoHash(), operator!=(), operator<(), and operator==().
GetBytes() [2/2]
const ByteArray & FBlake3Hash::GetBytes () const inline
Definition at line 53 of file Blake3.h.
References Hash.
IsZero()
bool FBlake3Hash::IsZero () const inline
Returns whether this is a zero hash.
Definition at line 159 of file Blake3.h.
References Hash, and Value.
operator!=()
bool FBlake3Hash::operator!= (const FBlake3Hash & B) const inline
Definition at line 63 of file Blake3.h.
References FBlake3Hash(), B, GetBytes(), and FMemory::Memcmp().
operator<()
bool FBlake3Hash::operator< (const FBlake3Hash & B) const inline
Definition at line 68 of file Blake3.h.
References FBlake3Hash(), B, GetBytes(), and FMemory::Memcmp().
operator==()
bool FBlake3Hash::operator== (const FBlake3Hash & B) const inline
Definition at line 58 of file Blake3.h.
References FBlake3Hash(), B, GetBytes(), and FMemory::Memcmp().
Reset()
void FBlake3Hash::Reset () inline
Reset this to a zero hash.
Definition at line 46 of file Blake3.h.
References FBlake3Hash().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FBlake3Hash & Value) friend
Definition at line 79 of file Blake3.h.
References FBlake3Hash(), and Value.
operator<<
FArchive & operator<< (FArchive & Ar, FBlake3Hash & Value) friend
Definition at line 73 of file Blake3.h.
References FBlake3Hash(), Ar, and Value.
Field Documentation
Hash
ByteArray FBlake3Hash::Hash {} private
Definition at line 85 of file Blake3.h.
Referenced by FBlake3Hash(), FBlake3Hash(), FBlake3Hash(), FBlake3Hash(), FBlake3Hash(), FromView(), GetBytes(), GetBytes(), and IsZero().
Zero
const FBlake3Hash FBlake3Hash::Zero inline static
A zero hash.
Definition at line 56 of file Blake3.h.
Referenced by FShaderCompileJobStatus::GetInputHash().
The documentation for this struct was generated from the following file:
Blake3.h