Unreal Engine 5.6 C++ API: UE::Geometry::FTexture2DBuilder Class Reference
UE::Geometry::FTexture2DBuilder Class Reference
Texture2DBuilder is a utility class for creating/modifying various types of UTexture2D.
#include "Texture2DBuilder.h"
Public Types
enum class ETextureType {
Color , ColorLinear , Roughness , Metallic ,
Specular , NormalMap , AmbientOcclusion , EmissiveHDR
}
Supported texture types.
Public Member Functions
virtual ~FTexture2DBuilder ()
MODELINGCOMPONENTS_API void Cancel ()
Cancel active editing and unlock the texture data.
MODELINGCOMPONENTS_API void Clear ()
Clear all texels in the current Mip to the clear/default color for the texture build type.
MODELINGCOMPONENTS_API void Clear (const FColor &ClearColor)
Clear all texels in the current Mip to the given ClearColor.
MODELINGCOMPONENTS_API void Clear (const FFloat16Color &ClearColor)
Clear all texels in the current Mip to the given ClearColor.
MODELINGCOMPONENTS_API void Commit (bool bUpdateSourceData=true)
Unlock the Mip 0 buffer and update the texture rendering data.
MODELINGCOMPONENTS_API bool Copy (const TImageBuilder< FVector3f > &SourceImage, const bool bConvertToSRGB=false)
populate texel values from floating-point SourceImage
MODELINGCOMPONENTS_API bool Copy (const TImageBuilder< FVector4f > &SourceImage, const bool bConvertToSRGB=false)
Populate texel values from floating-point SourceImage.
MODELINGCOMPONENTS_API bool CopyImageToSourceData (const TImageBuilder< FVector4f > &SourceImage, const ETextureSourceFormat SourceDataFormat, const bool bConvertToSRGB=false)
Populate Source Data texel values from a floating point SourceImage.
void CopyTexel (int64 FromLinearIndex, int64 ToLinearIndex)
Copy texel value from one linear index to another.
MODELINGCOMPONENTS_API bool CopyTo (TImageBuilder< FVector4f > &DestImage) const
copy existing texel values to floating-point DestImage.
MODELINGCOMPONENTS_API const FColor & GetClearColor () const
MODELINGCOMPONENTS_API FFloat16Color GetClearColorFloat16 () const
const FImageDimensions & GetDimensions () const
void * GetRawTexelBufferUnsafe ()
const void * GetRawTexelBufferUnsafe () const
const FColor & GetTexel (const FVector2i &ImageCoords) const
Get the FColor texel at the given X/Y coordinates.
const FColor & GetTexel (int64 LinearIndex) const
Get the FColor texel at the given linear index.
const FFloat16Color & GetTexelFloat16 (const FVector2i &ImageCoords) const
Get the FFloat16Color texel at the given X/Y coordinates.
const FFloat16Color & GetTexelFloat16 (int64 LinearIndex) const
Get the FFloat16Color texel at the given linear index.
UTexture2D * GetTexture2D () const
const EPixelFormat GetTexturePixelFormat () const
const ETextureType GetTextureType () const
MODELINGCOMPONENTS_API bool Initialize (ETextureType BuildTypeIn, FImageDimensions DimensionsIn)
Create a new UTexture2D configured with the given BuildType and Dimensions.
MODELINGCOMPONENTS_API bool Initialize (UTexture2D *ExistingTexture, ETextureType BuildTypeIn, bool bLockForEditing=true)
Initialize the builder with an existing UTexture2D.
MODELINGCOMPONENTS_API bool InitializeAndReplaceExistingTexture (UTexture2D *ExistingTexture, ETextureType BuildTypeIn, FImageDimensions DimensionsIn)
Create a new UTexture2D 'over' an existing UTexture2D, with the given BuildType and Dimensions.
MODELINGCOMPONENTS_API bool InitializeAndReplaceExistingTexture (UTexture2D *ExistingTexture, UTexture2D *SourceTexture)
Create a new UTexture2D 'over' an existing UTexture2D using the same texture settings as a given source UTexture2D.
const bool IsByteTexture () const
bool IsEditable () const
const bool IsFloat16Texture () const
MODELINGCOMPONENTS_API bool LockForEditing ()
Lock the Mip 0 buffer for editing.
void SetTexel (const FVector2i &ImageCoords, const FColor &NewValue)
Set the texel at the given X/Y coordinates to the given FColor.
void SetTexel (const FVector2i &ImageCoords, const FFloat16Color &NewValue)
Set the texel at the given X/Y coordinates to the given FFloat16Color.
void SetTexel (int64 LinearIndex, const FColor &NewValue)
Set the texel at the given linear index to the given FColor.
void SetTexel (int64 LinearIndex, const FFloat16Color &NewValue)
Set the texel at the given linear index to the given FFloat16Color.
MODELINGCOMPONENTS_API void UpdateSourceData ()
Copy the current PlatformData to the UTexture2D Source Data.
Static Public Member Functions
template<typename PixelType>
static UTexture2D * BuildTextureFromImage (const TImageBuilder< PixelType > &SourceImage, FTexture2DBuilder::ETextureType TextureType, const bool bConvertToSRGB, bool bPopulateSourceData=true)
Create a new UTexture2D of the given TextureType from the given SourceImage.
static MODELINGCOMPONENTS_API bool CopyPlatformDataToSourceData (UTexture2D *Texture, ETextureType TextureType)
Use a FTexture2DBuilder to copy the PlatformData to the UTexture2D Source data, so it can be saved as an Asset.
Protected Attributes
ETextureType BuildType = ETextureType::Color
FColor * CurrentMipData = nullptr
FFloat16Color * CurrentMipDataFloat16 = nullptr
EPixelFormat CurrentPixelFormat = PF_B8G8R8A8
FImageDimensions Dimensions
UTexture2D * RawTexture2D = nullptr
Private Member Functions
MODELINGCOMPONENTS_API bool InitializeInternal (ETextureType BuildTypeIn, FImageDimensions DimensionsIn, UTexture2D *CreatedTextureIn)
Detailed Description
Texture2DBuilder is a utility class for creating/modifying various types of UTexture2D.
Use Initialize() functions to configure, can either generate a new UTexture2D (in the Transient package) or modify an existing UTexture2D.
Currently the generated UTexture2D will only have Mip 0, and only Mip 0 can be edited. The generated UTexture2D has format PF_B8G8R8A8 or PF_FloatRGBA.
Use Commit() to lock and update the texture after editing is complete. LockForEditing() can be used to re-open. By default textures are locked for editing on Initialize()
If you have generated a UTexture2D by other means, you can use the static function CopyPlatformDataToSourceData() to populate the Source data from the PlatformData, which is required to save it as a UAsset.
Definition at line 30 of file Texture2DBuilder.h.
Member Enumeration Documentation
ETextureType
enum class UE::Geometry::FTexture2DBuilder::ETextureType strong
Supported texture types.
Enumerator
Color
ColorLinear
Roughness
Metallic
Specular
NormalMap
AmbientOcclusion
EmissiveHDR
Definition at line 37 of file Texture2DBuilder.h.
Constructor & Destructor Documentation
~FTexture2DBuilder()
virtual UE::Geometry::FTexture2DBuilder::~FTexture2DBuilder () inline virtual
Definition at line 60 of file Texture2DBuilder.h.
References check, and IsEditable().
Member Function Documentation
BuildTextureFromImage()
template<typename PixelType> UTexture2D * UE::Geometry::FTexture2DBuilder::BuildTextureFromImage (const TImageBuilder< PixelType > & SourceImage, FTexture2DBuilder::ETextureType TextureType, const bool bConvertToSRGB, bool bPopulateSourceData = true) inline static
Create a new UTexture2D of the given TextureType from the given SourceImage.
Parameters
bConvertToSRGB if true, assumption is SourceImage is Linear and we want output UTexture2D to be SRGB. Only valid for 8-bit textures.
bPopulateSourceData if true, first the PlatformData is initialized, then it is copied to the SourceData. This is necessary if the UTexture2D is going to be stored as an Asset (but can also be done explicitly using Commit())
Definition at line 347 of file Texture2DBuilder.h.
References Commit(), Copy(), UE::Geometry::TImageBuilder< PixelType >::GetDimensions(), GetTexture2D(), and Initialize().
Cancel()
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::Cancel ()
Cancel active editing and unlock the texture data.
References UE_API.
Clear() [1/3]
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::Clear ()
Clear all texels in the current Mip to the clear/default color for the texture build type.
References UE_API.
Clear() [2/3]
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::Clear (const FColor & ClearColor)
Clear all texels in the current Mip to the given ClearColor.
References UE_API.
Clear() [3/3]
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::Clear (const FFloat16Color & ClearColor)
Clear all texels in the current Mip to the given ClearColor.
References UE_API.
Commit()
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::Commit (bool bUpdateSourceData = true)
Unlock the Mip 0 buffer and update the texture rendering data.
This does not PostEditChange() so any materials using this texture may not be updated, the caller must do that.
Parameters
bUpdateSourceData if true, UpdateSourceData() is called to copy the current PlatformData to the SourceData
References UE_API.
Referenced by BuildTextureFromImage().
Copy() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::Copy (const TImageBuilder< FVector3f > & SourceImage, const bool bConvertToSRGB = false)
populate texel values from floating-point SourceImage
Parameters
bConvertToSRGB if true, SourceImage is assumed to be Linear, and converted to SRGB for the Texture
References UE_API.
Referenced by BuildTextureFromImage().
Copy() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::Copy (const TImageBuilder< FVector4f > & SourceImage, const bool bConvertToSRGB = false)
Populate texel values from floating-point SourceImage.
Parameters
bConvertToSRGB if true, SourceImage is assumed to be Linear, and converted to SRGB for the Texture
References UE_API.
CopyImageToSourceData()
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::CopyImageToSourceData (const TImageBuilder< FVector4f > & SourceImage, const ETextureSourceFormat SourceDataFormat, const bool bConvertToSRGB = false)
Populate Source Data texel values from a floating point SourceImage.
Parameters
SourceImage the image to copy to source data
SourceDataFormat the texture format for the Source Data
bConvertToSRGB if true, SourceImage is assumed to be Linear, and converted to SRGB for the Texture
References UE_API.
CopyPlatformDataToSourceData()
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::CopyPlatformDataToSourceData (UTexture2D * Texture, ETextureType TextureType) static
Use a FTexture2DBuilder to copy the PlatformData to the UTexture2D Source data, so it can be saved as an Asset.
References Texture, and UE_API.
CopyTexel()
void UE::Geometry::FTexture2DBuilder::CopyTexel (int64 FromLinearIndex, int64 ToLinearIndex) inline
Copy texel value from one linear index to another.
Definition at line 264 of file Texture2DBuilder.h.
References checkSlow, CurrentMipData, CurrentMipDataFloat16, IsByteTexture(), and IsEditable().
CopyTo()
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::CopyTo (TImageBuilder< FVector4f > & DestImage) const
copy existing texel values to floating-point DestImage.
Assumed to be same color space (eg values are copied without any linear/SRGB conversion)
References UE_API.
GetClearColor()
MODELINGCOMPONENTS_API const FColor & UE::Geometry::FTexture2DBuilder::GetClearColor () const
Returns
the default FColor for the current texture build type
References UE_API.
GetClearColorFloat16()
MODELINGCOMPONENTS_API FFloat16Color UE::Geometry::FTexture2DBuilder::GetClearColorFloat16 () const
Returns
the default FFloat16Color for the current texture build type
References UE_API.
GetDimensions()
const FImageDimensions & UE::Geometry::FTexture2DBuilder::GetDimensions () const inline
Definition at line 65 of file Texture2DBuilder.h.
References Dimensions.
GetRawTexelBufferUnsafe() [1/2]
void * UE::Geometry::FTexture2DBuilder::GetRawTexelBufferUnsafe () inline
Returns
current locked Mip data. Nullptr if IsEditable() == false. Use IsByteTexture() / IsFloat16Texture() to determine type.
Warning
this point is invalid after the texture is Committed!
Definition at line 317 of file Texture2DBuilder.h.
References CurrentMipData.
GetRawTexelBufferUnsafe() [2/2]
const void * UE::Geometry::FTexture2DBuilder::GetRawTexelBufferUnsafe () const inline
Returns
current locked Mip data. Nullptr if IsEditable() == false. Use IsByteTexture() / IsFloat16Texture() to determine type.
Warning
this point is invalid after the texture is Committed!
Definition at line 308 of file Texture2DBuilder.h.
References CurrentMipData.
GetTexel() [1/2]
const FColor & UE::Geometry::FTexture2DBuilder::GetTexel (const FVector2i & ImageCoords) const inline
Get the FColor texel at the given X/Y coordinates.
Definition at line 179 of file Texture2DBuilder.h.
References checkSlow, CurrentMipData, Dimensions, IsByteTexture(), and IsEditable().
GetTexel() [2/2]
const FColor & UE::Geometry::FTexture2DBuilder::GetTexel (int64 LinearIndex) const inline
Get the FColor texel at the given linear index.
Definition at line 190 of file Texture2DBuilder.h.
References checkSlow, CurrentMipData, IsByteTexture(), and IsEditable().
GetTexelFloat16() [1/2]
const FFloat16Color & UE::Geometry::FTexture2DBuilder::GetTexelFloat16 (const FVector2i & ImageCoords) const inline
Get the FFloat16Color texel at the given X/Y coordinates.
Definition at line 200 of file Texture2DBuilder.h.
References checkSlow, CurrentMipDataFloat16, Dimensions, IsEditable(), and IsFloat16Texture().
GetTexelFloat16() [2/2]
const FFloat16Color & UE::Geometry::FTexture2DBuilder::GetTexelFloat16 (int64 LinearIndex) const inline
Get the FFloat16Color texel at the given linear index.
Definition at line 211 of file Texture2DBuilder.h.
References checkSlow, CurrentMipDataFloat16, IsEditable(), and IsFloat16Texture().
GetTexture2D()
UTexture2D * UE::Geometry::FTexture2DBuilder::GetTexture2D () const inline
Returns
the internal texture
Definition at line 93 of file Texture2DBuilder.h.
References RawTexture2D.
Referenced by BuildTextureFromImage().
GetTexturePixelFormat()
const EPixelFormat UE::Geometry::FTexture2DBuilder::GetTexturePixelFormat () const inline
Definition at line 75 of file Texture2DBuilder.h.
References CurrentPixelFormat.
GetTextureType()
const ETextureType UE::Geometry::FTexture2DBuilder::GetTextureType () const inline
Definition at line 70 of file Texture2DBuilder.h.
References BuildType.
Initialize() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::Initialize (ETextureType BuildTypeIn, FImageDimensions DimensionsIn)
Create a new UTexture2D configured with the given BuildType and Dimensions.
References UE_API.
Referenced by BuildTextureFromImage().
Initialize() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::Initialize (UTexture2D * ExistingTexture, ETextureType BuildTypeIn, bool bLockForEditing = true)
Initialize the builder with an existing UTexture2D.
References UE_API.
InitializeAndReplaceExistingTexture() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::InitializeAndReplaceExistingTexture (UTexture2D * ExistingTexture, ETextureType BuildTypeIn, FImageDimensions DimensionsIn)
Create a new UTexture2D 'over' an existing UTexture2D, with the given BuildType and Dimensions.
References UE_API.
InitializeAndReplaceExistingTexture() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::InitializeAndReplaceExistingTexture (UTexture2D * ExistingTexture, UTexture2D * SourceTexture)
Create a new UTexture2D 'over' an existing UTexture2D using the same texture settings as a given source UTexture2D.
This method only initializes the texture settings of ExistingTexture to match those of SourceTexture. To populate texture data, use Copy(..).
References UE_API.
InitializeInternal()
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::InitializeInternal (ETextureType BuildTypeIn, FImageDimensions DimensionsIn, UTexture2D * CreatedTextureIn) private
References UE_API.
IsByteTexture()
const bool UE::Geometry::FTexture2DBuilder::IsByteTexture () const inline
Returns
true if texture buffer is FColor/8-bit BGRA
Definition at line 81 of file Texture2DBuilder.h.
References CurrentPixelFormat, and PF_B8G8R8A8.
Referenced by CopyTexel(), GetTexel(), GetTexel(), SetTexel(), and SetTexel().
IsEditable()
bool UE::Geometry::FTexture2DBuilder::IsEditable () const inline
Returns
true if the texture data is currently locked and editable
Definition at line 132 of file Texture2DBuilder.h.
References CurrentMipData, and CurrentMipDataFloat16.
Referenced by ~FTexture2DBuilder(), CopyTexel(), GetTexel(), GetTexel(), GetTexelFloat16(), GetTexelFloat16(), SetTexel(), SetTexel(), SetTexel(), and SetTexel().
IsFloat16Texture()
const bool UE::Geometry::FTexture2DBuilder::IsFloat16Texture () const inline
Returns
true if texture buffer is FFloat16Color/16-bit RGBA
Definition at line 87 of file Texture2DBuilder.h.
References CurrentPixelFormat, and PF_FloatRGBA.
Referenced by GetTexelFloat16(), GetTexelFloat16(), SetTexel(), and SetTexel().
LockForEditing()
MODELINGCOMPONENTS_API bool UE::Geometry::FTexture2DBuilder::LockForEditing ()
Lock the Mip 0 buffer for editing.
Returns
true if lock was successfull. Will return false if already locked.
References UE_API.
SetTexel() [1/4]
void UE::Geometry::FTexture2DBuilder::SetTexel (const FVector2i & ImageCoords, const FColor & NewValue) inline
Set the texel at the given X/Y coordinates to the given FColor.
Definition at line 222 of file Texture2DBuilder.h.
References checkSlow, CurrentMipData, Dimensions, IsByteTexture(), and IsEditable().
Referenced by SetTexel(), and SetTexel().
SetTexel() [2/4]
void UE::Geometry::FTexture2DBuilder::SetTexel (const FVector2i & ImageCoords, const FFloat16Color & NewValue) inline
Set the texel at the given X/Y coordinates to the given FFloat16Color.
Definition at line 243 of file Texture2DBuilder.h.
References checkSlow, CurrentMipDataFloat16, Dimensions, IsEditable(), and IsFloat16Texture().
SetTexel() [3/4]
void UE::Geometry::FTexture2DBuilder::SetTexel (int64 LinearIndex, const FColor & NewValue) inline
Set the texel at the given linear index to the given FColor.
Definition at line 233 of file Texture2DBuilder.h.
References checkSlow, Dimensions, IsByteTexture(), IsEditable(), and SetTexel().
SetTexel() [4/4]
void UE::Geometry::FTexture2DBuilder::SetTexel (int64 LinearIndex, const FFloat16Color & NewValue) inline
Set the texel at the given linear index to the given FFloat16Color.
Definition at line 254 of file Texture2DBuilder.h.
References checkSlow, Dimensions, IsEditable(), IsFloat16Texture(), and SetTexel().
UpdateSourceData()
MODELINGCOMPONENTS_API void UE::Geometry::FTexture2DBuilder::UpdateSourceData ()
Copy the current PlatformData to the UTexture2D Source Data.
This does not require the texture to be locked for editing, if it is not locked, a read-only lock will be acquired as needed
Warning
currently assumes both buffers are the same format
References UE_API.
Field Documentation
BuildType
ETextureType UE::Geometry::FTexture2DBuilder::BuildType = ETextureType::Color protected
Definition at line 51 of file Texture2DBuilder.h.
Referenced by GetTextureType().
CurrentMipData
FColor* UE::Geometry::FTexture2DBuilder::CurrentMipData = nullptr protected
Definition at line 54 of file Texture2DBuilder.h.
Referenced by CopyTexel(), GetRawTexelBufferUnsafe(), GetRawTexelBufferUnsafe(), GetTexel(), GetTexel(), IsEditable(), and SetTexel().
CurrentMipDataFloat16
FFloat16Color* UE::Geometry::FTexture2DBuilder::CurrentMipDataFloat16 = nullptr protected
Definition at line 55 of file Texture2DBuilder.h.
Referenced by CopyTexel(), GetTexelFloat16(), GetTexelFloat16(), IsEditable(), and SetTexel().
CurrentPixelFormat
EPixelFormat UE::Geometry::FTexture2DBuilder::CurrentPixelFormat = PF_B8G8R8A8 protected
Definition at line 56 of file Texture2DBuilder.h.
Referenced by GetTexturePixelFormat(), IsByteTexture(), and IsFloat16Texture().
Dimensions
FImageDimensions UE::Geometry::FTexture2DBuilder::Dimensions protected
Definition at line 50 of file Texture2DBuilder.h.
Referenced by GetDimensions(), GetTexel(), GetTexelFloat16(), SetTexel(), SetTexel(), SetTexel(), and SetTexel().
RawTexture2D
UTexture2D* UE::Geometry::FTexture2DBuilder::RawTexture2D = nullptr protected
Definition at line 53 of file Texture2DBuilder.h.
Referenced by GetTexture2D().
The documentation for this class was generated from the following file:
Texture2DBuilder.h