Unreal Engine 5.6 C++ API: AudioWidgets::FAudioMeter Class Reference
AudioWidgets::FAudioMeter Class Reference
#include "AudioMeter.h"
Public Member Functions
AUDIOWIDGETS_API FAudioMeter (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, const FAudioMaterialMeterStyle &AudioMaterialMeterStyle, TObjectPtr< UAudioBus > InExternalAudioBus=nullptr)
AUDIOWIDGETS_API FAudioMeter (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, TObjectPtr< UAudioBus > InExternalAudioBus=nullptr, const FAudioMeterDefaultColorStyle *AudioMeterColorStyle=nullptr)
AUDIOWIDGETS_API ~FAudioMeter ()
AUDIOWIDGETS_API UAudioBus * GetAudioBus () const
AUDIOWIDGETS_API TSharedRef< SAudioMeter > GetWidget () const
template<class T>
TSharedRef< T > GetWidget () const
AUDIOWIDGETS_API void Init (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, TObjectPtr< UAudioBus > InExternalAudioBus)
virtual void SetAudioBusInfo (const FAudioBusInfo &AudioBusInfo) override
If the Audio Bus to analyze changes (due to channel count change), handle this here.
virtual AUDIOWIDGETS_API TSharedRef< SDockTab > SpawnTab (const FSpawnTabArgs &Args) const override
Spawn the actual analyzer Widget in a DockTab.
UE_DEPRECATED (5.4, "Use the FAudioMeter constructor that uses Audio::FDeviceId.") AUDIOWIDGETS_API FAudioMeter(int32 InNumChannels
UE_DEPRECATED (5.4, "Use the Init method that uses Audio::FDeviceId.") AUDIOWIDGETS_API void Init(int32 InNumChannels
Public Member Functions inherited from AudioWidgets::IAudioAnalyzerRackUnit
virtual ~IAudioAnalyzerRackUnit ()
virtual void StartProcessing ()
Be notified of request to start processing.
virtual void StopProcessing ()
Be notified of request to stop processing.
Public Member Functions inherited from TSharedFromThis< IAudioAnalyzerRackUnit >
TSharedRef< IAudioAnalyzerRackUnit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IAudioAnalyzerRackUnit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
UWorld TObjectPtr< UAudioBus > InExternalAudioBus = nullptr)
UWorld & InWorld
Static Public Attributes
static AUDIOWIDGETS_API const FAudioAnalyzerRackUnitTypeInfo RackUnitTypeInfo
Protected Member Functions
AUDIOWIDGETS_API void OnMeterOutput (UMeterAnalyzer *InMeterAnalyzer, int32 ChannelIndex, const FMeterResults &InMeterResults)
Protected Member Functions inherited from TSharedFromThis< IAudioAnalyzerRackUnit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
AUDIOWIDGETS_API void Teardown ()
Static Private Member Functions
static AUDIOWIDGETS_API TSharedRef< IAudioAnalyzerRackUnit > MakeRackUnit (const FAudioAnalyzerRackUnitConstructParams &Params)
Private Attributes
TStrongObjectPtr< UMeterAnalyzer > Analyzer
Metasound analyzer object.
TStrongObjectPtr< UAudioBus > AudioBus
The audio bus used for analysis.
bool bUseExternalAudioBus = false
TArray< FMeterChannelInfo > ChannelInfo
Cached channel info for the meter.
FDelegateHandle ResultsDelegateHandle
Handle for results delegate for MetaSound meter analyzer.
TStrongObjectPtr< UMeterSettings > Settings
Meter settings.
TSharedPtr< SAudioMeterBase > Widget
MetaSound Output Meter widget.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IAudioAnalyzerRackUnit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 193 of file AudioMeter.h.
Constructor & Destructor Documentation
FAudioMeter() [1/2]
AUDIOWIDGETS_API AudioWidgets::FAudioMeter::FAudioMeter (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, TObjectPtr< UAudioBus > InExternalAudioBus = nullptr, const FAudioMeterDefaultColorStyle * AudioMeterColorStyle = nullptr)
References FAudioMeter(), InExternalAudioBus, and UE_API.
Referenced by FAudioMeter(), FAudioMeter(), and ~FAudioMeter().
FAudioMeter() [2/2]
AUDIOWIDGETS_API AudioWidgets::FAudioMeter::FAudioMeter (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, const FAudioMaterialMeterStyle & AudioMaterialMeterStyle, TObjectPtr< UAudioBus > InExternalAudioBus = nullptr)
References FAudioMeter(), InExternalAudioBus, and UE_API.
~FAudioMeter()
AUDIOWIDGETS_API AudioWidgets::FAudioMeter::~FAudioMeter ()
References FAudioMeter(), and UE_API.
Member Function Documentation
GetAudioBus()
AUDIOWIDGETS_API UAudioBus * AudioWidgets::FAudioMeter::GetAudioBus () const
References GetAudioBus(), and UE_API.
Referenced by GetAudioBus().
GetWidget() [1/2]
AUDIOWIDGETS_API TSharedRef< SAudioMeter > AudioWidgets::FAudioMeter::GetWidget () const
References GetWidget(), and UE_API.
Referenced by GetWidget().
GetWidget() [2/2]
template<class T> TSharedRef< T > AudioWidgets::FAudioMeter::GetWidget () const inline
Definition at line 214 of file AudioMeter.h.
References GetWidget(), StaticCastSharedRef(), and Widget.
Init()
AUDIOWIDGETS_API void AudioWidgets::FAudioMeter::Init (const int32 InNumChannels, const Audio::FDeviceId InAudioDeviceId, TObjectPtr< UAudioBus > InExternalAudioBus)
References InExternalAudioBus, Init(), and UE_API.
Referenced by Init(), and UE_DEPRECATED().
MakeRackUnit()
AUDIOWIDGETS_API TSharedRef< IAudioAnalyzerRackUnit > AudioWidgets::FAudioMeter::MakeRackUnit (const FAudioAnalyzerRackUnitConstructParams & Params) static private
References Params, and UE_API.
OnMeterOutput()
AUDIOWIDGETS_API void AudioWidgets::FAudioMeter::OnMeterOutput (UMeterAnalyzer * InMeterAnalyzer, int32 ChannelIndex, const FMeterResults & InMeterResults) protected
References UE_API.
SetAudioBusInfo()
virtual void AudioWidgets::FAudioMeter::SetAudioBusInfo (const FAudioBusInfo & AudioBusInfo) inline override virtual
If the Audio Bus to analyze changes (due to channel count change), handle this here.
Implements AudioWidgets::IAudioAnalyzerRackUnit.
Definition at line 225 of file AudioMeter.h.
References Init, and SetAudioBusInfo().
Referenced by SetAudioBusInfo().
SpawnTab()
virtual AUDIOWIDGETS_API TSharedRef< SDockTab > AudioWidgets::FAudioMeter::SpawnTab (const FSpawnTabArgs & Args) const override virtual
Spawn the actual analyzer Widget in a DockTab.
Implements AudioWidgets::IAudioAnalyzerRackUnit.
References UE_API.
Teardown()
AUDIOWIDGETS_API void AudioWidgets::FAudioMeter::Teardown () private
References UE_API.
UE_DEPRECATED() [1/2]
AudioWidgets::FAudioMeter::UE_DEPRECATED (5. 4, "Use the FAudioMeter constructor that uses Audio::FDeviceId.")
UE_DEPRECATED() [2/2]
AudioWidgets::FAudioMeter::UE_DEPRECATED (5. 4, "Use the Init method that uses Audio::FDeviceId.")
References InExternalAudioBus, Init(), InWorld, and UE_API.
Field Documentation
Analyzer
TStrongObjectPtr<UMeterAnalyzer> AudioWidgets::FAudioMeter::Analyzer private
Metasound analyzer object.
Definition at line 242 of file AudioMeter.h.
AudioBus
TStrongObjectPtr<UAudioBus> AudioWidgets::FAudioMeter::AudioBus private
The audio bus used for analysis.
Definition at line 245 of file AudioMeter.h.
bUseExternalAudioBus
bool AudioWidgets::FAudioMeter::bUseExternalAudioBus = false private
Definition at line 259 of file AudioMeter.h.
ChannelInfo
TArray<FMeterChannelInfo> AudioWidgets::FAudioMeter::ChannelInfo private
Cached channel info for the meter.
Definition at line 248 of file AudioMeter.h.
InExternalAudioBus
UWorld TObjectPtr< UAudioBus > AudioWidgets::FAudioMeter::InExternalAudioBus = nullptr)
Definition at line 199 of file AudioMeter.h.
Referenced by FAudioMeter(), FAudioMeter(), Init(), and UE_DEPRECATED().
InWorld
UWorld & AudioWidgets::FAudioMeter::InWorld
Definition at line 199 of file AudioMeter.h.
Referenced by UE_DEPRECATED().
RackUnitTypeInfo
AUDIOWIDGETS_API const FAudioAnalyzerRackUnitTypeInfo AudioWidgets::FAudioMeter::RackUnitTypeInfo static
Definition at line 196 of file AudioMeter.h.
ResultsDelegateHandle
FDelegateHandle AudioWidgets::FAudioMeter::ResultsDelegateHandle private
Handle for results delegate for MetaSound meter analyzer.
Definition at line 251 of file AudioMeter.h.
Settings
TStrongObjectPtr<UMeterSettings> AudioWidgets::FAudioMeter::Settings private
Meter settings.
Definition at line 254 of file AudioMeter.h.
Widget
TSharedPtr<SAudioMeterBase> AudioWidgets::FAudioMeter::Widget private
MetaSound Output Meter widget.
Definition at line 257 of file AudioMeter.h.
Referenced by GetWidget().
The documentation for this class was generated from the following file:
AudioMeter.h