Unreal Engine 5.6 C++ API: UStereoLayerShapeEquirect Class Reference
UStereoLayerShapeEquirect Class Reference
#include "StereoLayerComponent.h"
Private Member Functions
virtual void ApplyShape (IStereoLayers::FLayerDesc &LayerDesc) override
virtual void DrawShapeVisualization (const class FSceneView *View, class FPrimitiveDrawInterface *PDI) override
GENERATED_BODY () public
UFUNCTION () 1 void SetEquirectProps(FEquirectProps InScaleBiases)
Set Equirect layer properties: UVRect, Scale, and Bias.
UPROPERTY () FBox2D LeftUVRect
Left source texture UVRect, specifying portion of input texture corresponding to left eye.
UPROPERTY () FBox2D RightUVRect
Right source texture UVRect, specifying portion of input texture corresponding to right eye.
UPROPERTY () float Radius
Sphere radius.
UPROPERTY () FVector2D LeftBias
Left eye's texture coordinate bias after mapping to 2D.
UPROPERTY () FVector2D LeftScale
Left eye's texture coordinate scale after mapping to 2D.
UPROPERTY () FVector2D RightBias
Right eye's texture coordinate bias after mapping to 2D.
UPROPERTY () FVector2D RightScale
Right eye's texture coordinate scale after mapping to 2D.
Detailed Description
Definition at line 204 of file StereoLayerComponent.h.
Member Function Documentation
ApplyShape()
virtual void UStereoLayerShapeEquirect::ApplyShape (IStereoLayers::FLayerDesc & LayerDesc) override private virtual
References ApplyShape().
Referenced by ApplyShape().
DrawShapeVisualization()
virtual void UStereoLayerShapeEquirect::DrawShapeVisualization (const class FSceneView * View, class FPrimitiveDrawInterface * PDI) override private virtual
GENERATED_BODY()
UStereoLayerShapeEquirect::GENERATED_BODY () inline private
Definition at line 206 of file StereoLayerComponent.h.
UFUNCTION()
UStereoLayerShapeEquirect::UFUNCTION () private
Set Equirect layer properties: UVRect, Scale, and Bias.
Parameters
LeftScale Scale for left eye
LeftBias Bias for left eye
RightScale Scale for right eye
RightBias Bias for right eye
Radius Sphere radius
References Category, and UFUNCTION().
Referenced by UFUNCTION().
UPROPERTY() [1/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Left source texture UVRect, specifying portion of input texture corresponding to left eye.
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Right source texture UVRect, specifying portion of input texture corresponding to right eye.
References Category, and UPROPERTY().
UPROPERTY() [3/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Sphere radius.
As of UE 5.3, equirect layers are supported only by the Oculus OpenXR runtime and only with a radius of 0 (infinite sphere).
References Category, and UPROPERTY().
UPROPERTY() [4/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Left eye's texture coordinate bias after mapping to 2D.
References Category, and UPROPERTY().
UPROPERTY() [5/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Left eye's texture coordinate scale after mapping to 2D.
References Category, and UPROPERTY().
UPROPERTY() [6/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Right eye's texture coordinate bias after mapping to 2D.
References Category, and UPROPERTY().
UPROPERTY() [7/7]
UStereoLayerShapeEquirect::UPROPERTY () private
Right eye's texture coordinate scale after mapping to 2D.
References Category, and UPROPERTY().
The documentation for this class was generated from the following file:
StereoLayerComponent.h