Unreal Engine 5.6 C++ API: UHeterogeneousVolumeComponent Class Reference
UHeterogeneousVolumeComponent Class Reference
#include "HeterogeneousVolumeComponent.h"
Public Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual int32 GetNumMaterials () const override
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PostReinitProperties () override
virtual void SetMaterial (int32 ElementIndex, class UMaterialInterface *Material) override
virtual bool ShouldRenderSelected () const override
virtual void TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Private Member Functions
~UHeterogeneousVolumeComponent ()
GENERATED_UCLASS_BODY () UPROPERTY() FIntVector VolumeResolution
UMaterialInterface * GetHeterogeneousVolumeMaterial () const
void OnSparseVolumeTextureChanged (const USparseVolumeTexture *SparseVolumeTexture)
UFUNCTION () 1 void Play()
UFUNCTION () 1 void SetEndFrame(float NewValue)
UFUNCTION () 1 void SetFrame(float NewValue)
UFUNCTION () 1 void SetFrameRate(float NewValue)
UFUNCTION () 1 void SetLooping(bool NewValue)
UFUNCTION () 1 void SetPlaying(bool NewValue)
UFUNCTION () 1 void SetStartFrame(float NewValue)
UFUNCTION () 1 void SetStreamingMipBias(int32 NewValue)
UFUNCTION () 1 void SetVolumeResolution(FIntVector NewValue)
UPROPERTY () float EndFrame
UPROPERTY () float FrameRate
UPROPERTY () float LightingDownsampleFactor
UPROPERTY () float ShadowBiasFactor
UPROPERTY () float ShadowStepFactor
UPROPERTY () float StartFrame
UPROPERTY() uint32 bIssueBlockingRequests UPROPERTY() uint32 bPivotAtCentroid UPROPERTY () float StepFactor
UPROPERTY() uint32 bPlaying UPROPERTY() uint32 bLooping UPROPERTY () float StreamingMipBias
UPROPERTY () FTransform FrameTransform
UPROPERTY () TObjectPtr< UMaterialInstanceDynamic > MaterialInstanceDynamic
UPROPERTY ()) float Frame
Static Private Member Functions
static UMaterialInstanceDynamic * CreateOrCastToMID (UMaterialInterface *MaterialInterface)
static USparseVolumeTexture * GetSparseVolumeTexture (UMaterialInterface *MaterialInterface, int32 ParameterIndex, FName *OutParamName=nullptr)
Private Attributes
const USparseVolumeTexture * PreviousSVT
Additional Inherited Members
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Detailed Description
Definition at line 20 of file HeterogeneousVolumeComponent.h.
Constructor & Destructor Documentation
~UHeterogeneousVolumeComponent()
UHeterogeneousVolumeComponent::~UHeterogeneousVolumeComponent () inline private
Definition at line 101 of file HeterogeneousVolumeComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UHeterogeneousVolumeComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
CreateOrCastToMID()
UMaterialInstanceDynamic * UHeterogeneousVolumeComponent::CreateOrCastToMID (UMaterialInterface * MaterialInterface) static private
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UHeterogeneousVolumeComponent::CreateSceneProxy () override virtual
GENERATED_UCLASS_BODY()
UHeterogeneousVolumeComponent::GENERATED_UCLASS_BODY () private
References Category, UPROPERTY(), and Volume.
GetHeterogeneousVolumeMaterial()
UMaterialInterface * UHeterogeneousVolumeComponent::GetHeterogeneousVolumeMaterial () const private
GetMaterialIndex()
virtual int32 UHeterogeneousVolumeComponent::GetMaterialIndex (FName MaterialSlotName) const override virtual
GetNumMaterials()
virtual int32 UHeterogeneousVolumeComponent::GetNumMaterials () const inline override virtual
Reimplemented from UMeshComponent.
Definition at line 123 of file HeterogeneousVolumeComponent.h.
GetSparseVolumeTexture()
USparseVolumeTexture * UHeterogeneousVolumeComponent::GetSparseVolumeTexture (UMaterialInterface * MaterialInterface, int32 ParameterIndex, FName * OutParamName = nullptr) static private
GetUsedMaterials()
virtual void UHeterogeneousVolumeComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override virtual
Reimplemented from UMeshComponent.
IsMaterialSlotNameValid()
virtual bool UHeterogeneousVolumeComponent::IsMaterialSlotNameValid (FName MaterialSlotName) const override virtual
OnSparseVolumeTextureChanged()
void UHeterogeneousVolumeComponent::OnSparseVolumeTextureChanged (const USparseVolumeTexture * SparseVolumeTexture) private
PostEditChangeProperty()
virtual void UHeterogeneousVolumeComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UHeterogeneousVolumeComponent::PostInitProperties () override virtual
PostLoad()
virtual void UHeterogeneousVolumeComponent::PostLoad () override virtual
PostReinitProperties()
virtual void UHeterogeneousVolumeComponent::PostReinitProperties () override virtual
SetMaterial()
virtual void UHeterogeneousVolumeComponent::SetMaterial (int32 ElementIndex, class UMaterialInterface * Material) override virtual
Reimplemented from UMeshComponent.
References Material.
ShouldRenderSelected()
virtual bool UHeterogeneousVolumeComponent::ShouldRenderSelected () const inline override virtual
Definition at line 118 of file HeterogeneousVolumeComponent.h.
TickComponent()
virtual void UHeterogeneousVolumeComponent::TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
References DeltaTime.
UFUNCTION() [1/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [2/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [4/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [6/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [7/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [8/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [9/9]
UHeterogeneousVolumeComponent::UFUNCTION () private
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UPROPERTY() [1/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Animation, Category, EndFrame, and UPROPERTY().
UPROPERTY() [2/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Animation, Category, FrameRate, and UPROPERTY().
UPROPERTY() [3/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [4/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [5/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [6/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Animation, Category, and UPROPERTY().
UPROPERTY() [7/11]
UPROPERTY() uint32 bIssueBlockingRequests UPROPERTY() uint32 bPivotAtCentroid UHeterogeneousVolumeComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [8/11]
UPROPERTY() uint32 bPlaying UPROPERTY() uint32 bLooping UHeterogeneousVolumeComponent::UPROPERTY () private
References Category, UPROPERTY(), and Volume.
UPROPERTY() [9/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Animation, Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [10/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Transient, and UPROPERTY().
UPROPERTY() [11/11]
UHeterogeneousVolumeComponent::UPROPERTY () private
References Animation, Category, meta, and UPROPERTY().
Field Documentation
PreviousSVT
const USparseVolumeTexture* UHeterogeneousVolumeComponent::PreviousSVT private
Definition at line 130 of file HeterogeneousVolumeComponent.h.
The documentation for this class was generated from the following file:
HeterogeneousVolumeComponent.h