Unreal Engine 5.6 C++ API: TraceServices::FCallstack Struct Reference
TraceServices::FCallstack Struct Reference
#include "Callstack.h"
Public Member Functions
FCallstack ()
Creates the default empty callstack (id 0).
FCallstack (const FStackFrame *FirstEntry, uint8 FrameCount)
Creates an callstack initialized with a certain number of stack frames.
FCallstack (uint64 Id)
Creates an empty callstack but with a non-zero id.
uint64 Addr (uint8 Depth) const
Gets the address at a given stack depth.
const FStackFrame * Frame (uint8 Depth) const
Gets the entire frame at given depth.
uint64 GetEmptyId () const
Gets the callstack id of an empty callstack.
void Init (const FStackFrame *FirstEntry, uint8 FrameCount)
Initializes the callstack with a certain number of stack frames.
void InitEmpty (uint64 Id)
Initializes an empty callstack but with a non-zero id.
bool IsEmpty () const
Return true if the number of stack frames is zero.
const TCHAR * Name (uint8 Depth) const
Gets the cached symbol name at a given stack depth.
uint32 Num () const
Gets the number of stack frames in callstack.
Private Types
enum : uint64 { EntryLenShift = 56 , EntryLenMask = uint64(0xff) << EntryLenShift }
Private Attributes
uint64 CallstackLenIndex
Detailed Description
Definition at line 22 of file Callstack.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint64 private
Enumerator
EntryLenShift
EntryLenMask
Definition at line 58 of file Callstack.h.
Constructor & Destructor Documentation
FCallstack() [1/3]
TraceServices::FCallstack::FCallstack () inline
Creates the default empty callstack (id 0).
Definition at line 104 of file Callstack.h.
References CallstackLenIndex.
FCallstack() [2/3]
TraceServices::FCallstack::FCallstack (uint64 Id) inline
Creates an empty callstack but with a non-zero id.
Definition at line 110 of file Callstack.h.
References InitEmpty().
FCallstack() [3/3]
TraceServices::FCallstack::FCallstack (const FStackFrame * FirstEntry, uint8 FrameCount) inline
Creates an callstack initialized with a certain number of stack frames.
Definition at line 116 of file Callstack.h.
References Init.
Member Function Documentation
Addr()
uint64 TraceServices::FCallstack::Addr (uint8 Depth) const inline
Gets the address at a given stack depth.
Definition at line 154 of file Callstack.h.
References Addr(), CallstackLenIndex, Depth, EntryLenMask, and Num().
Referenced by Addr().
Frame()
const FStackFrame * TraceServices::FCallstack::Frame (uint8 Depth) const inline
Gets the entire frame at given depth.
Definition at line 170 of file Callstack.h.
References CallstackLenIndex, Depth, EntryLenMask, and Num().
GetEmptyId()
uint64 TraceServices::FCallstack::GetEmptyId () const inline
Gets the callstack id of an empty callstack.
Definition at line 136 of file Callstack.h.
References CallstackLenIndex, and EntryLenMask.
Init()
void TraceServices::FCallstack::Init (const FStackFrame * FirstEntry, uint8 FrameCount) inline
Initializes the callstack with a certain number of stack frames.
Definition at line 122 of file Callstack.h.
References CallstackLenIndex, check, EntryLenMask, and EntryLenShift.
InitEmpty()
void TraceServices::FCallstack::InitEmpty (uint64 Id) inline
Initializes an empty callstack but with a non-zero id.
Definition at line 129 of file Callstack.h.
References CallstackLenIndex, check, and EntryLenMask.
Referenced by FCallstack().
IsEmpty()
bool TraceServices::FCallstack::IsEmpty () const inline
Return true if the number of stack frames is zero.
Definition at line 142 of file Callstack.h.
References CallstackLenIndex, and EntryLenShift.
Name()
const TCHAR * TraceServices::FCallstack::Name (uint8 Depth) const inline
Gets the cached symbol name at a given stack depth.
Definition at line 162 of file Callstack.h.
References CallstackLenIndex, Depth, EntryLenMask, and Num().
Num()
uint32 TraceServices::FCallstack::Num () const inline
Gets the number of stack frames in callstack.
Definition at line 148 of file Callstack.h.
References CallstackLenIndex, and EntryLenShift.
Referenced by Addr(), Frame(), and Name().
Field Documentation
CallstackLenIndex
uint64 TraceServices::FCallstack::CallstackLenIndex private
Definition at line 64 of file Callstack.h.
Referenced by FCallstack(), Addr(), Frame(), GetEmptyId(), Init(), InitEmpty(), IsEmpty(), Name(), and Num().
The documentation for this struct was generated from the following file:
Callstack.h