Unreal Engine 5.6 C++ API: UE::Color Namespace Reference
UE::Color Namespace Reference
Data Structures
class FColorSpace
Color space definition as 4 chromaticity coordinates, in double precision internally.
struct FColorSpaceTransform
Enumerations
enum class EChromaticAdaptationMethod : uint8 { None = 0 , Bradford = 1 , CAT02 = 2 , Max }
List of available chromatic adaptation methods.
enum class EColorSpace : uint8 {
None = 0 , sRGB = 1 , Rec2020 = 2 , ACESAP0 = 3 ,
ACESAP1 = 4 , P3DCI = 5 , P3D65 = 6 , REDWideGamut = 7 ,
SonySGamut3 = 8 , SonySGamut3Cine = 9 , AlexaWideGamut = 10 , CanonCinemaGamut = 11 ,
GoProProtuneNative = 12 , PanasonicVGamut = 13 , PLASA_E1_54 = 14 , ACESCAM16 = 15 ,
Max
}
List of available color spaces.
enum class EEncoding : uint8 {
None = 0 , Linear = 1 , sRGB , ST2084 ,
Gamma22 , BT1886 , Gamma26 , Cineon ,
REDLog , REDLog3G10 , SLog1 , SLog2 ,
SLog3 , AlexaV3LogC , CanonLog , ProTune ,
VLog , Max
}
List of available encodings/transfer functions.
enum class EWhitePoint : uint8 { CIE1931_D65 = 0 , ACES_D60 = 1 , DCI_CalibrationWhite , Max }
List of standard white points.
Functions
FLinearColor Decode (EEncoding Encoding, const FLinearColor &Color)
Decode a color based on the specified encoding type.
float Decode (EEncoding Encoding, float Value)
Decode a value based on the specified encoding type.
float DecodeArriAlexaV3LogC (float Value)
Decode value with an ARRI Alexa LogC encoding.
float DecodeBT1886 (float Value)
Decode value with an ITU-R BT.1886 encoding.
float DecodeCanonLog (float Value)
Decode value with a Canon Log encoding.
float DecodeCineon (float Value)
Decode value with a Cineon encoding.
float DecodeGamma22 (float Value)
Decode value with a Gamma 2.2 encoding.
float DecodeGamma26 (float Value)
Decode value with a Gamma 2.6 encoding.
float DecodeGoProProTune (float Value)
Decode value with a GoPro ProTune encoding.
float DecodePanasonicVLog (float Value)
Decode value with a Panasonic V-Log encoding.
float DecodeREDLog (float Value)
Decode value with a RED Log encoding.
float DecodeREDLog3G10 (float Value)
Decode value with a RED Log3G10 encoding.
float DecodeSLog1 (float Value)
Decode value with a Sony S-Log1 encoding.
float DecodeSLog2 (float Value)
Decode value with a Sony S-Log2 encoding.
float DecodeSLog3 (float Value)
Decode value with a Sony S-Log3 encoding.
float DecodeSRGB (float Value)
Decode value with an sRGB encoding.
float DecodeST2084 (float Value)
Decode value with a SMPTE ST 2084:2014 encoding.
FLinearColor Encode (EEncoding Encoding, const FLinearColor &Color)
Encode a color based on the specified encoding type.
float Encode (EEncoding Encoding, float Value)
Encode a value based on the specified encoding type.
float EncodeArriAlexaV3LogC (float Value)
Encode value to ARRI Alexa LogC.
float EncodeBT1886 (float Value)
Encode value to ITU-R BT.1886.
float EncodeCanonLog (float Value)
Encode value to Canon Log.
float EncodeCineon (float Value)
Encode value to Cineon.
float EncodeGamma22 (float Value)
Encode value to Gamma 2.2.
float EncodeGamma26 (float Value)
Encode value to Gamma 2.6.
float EncodeGoProProTune (float Value)
Encode value to GoPro ProTune.
float EncodePanasonicVLog (float Value)
Encode value to Panasonic V-Log.
float EncodeREDLog (float Value)
Encode value to RED Log.
float EncodeREDLog3G10 (float Value)
Encode value to RED Log3G10.
float EncodeSLog1 (float Value)
Encode value to Sony S-Log1.
float EncodeSLog2 (float Value)
Encode value to Sony S-Log2.
float EncodeSLog3 (float Value)
Encode value to Sony S-Log3.
float EncodeSRGB (float Value)
Encode value to sRGB.
float EncodeST2084 (float Value)
Encode value to SMPTE ST 2084:2014.
TFunction< FLinearColor(const FLinearColor &)> GetColorDecodeFunction (EEncoding Encoding)
Get the decode function that matches the encoding type.
TFunction< FLinearColor(const FLinearColor &)> GetColorEncodeFunction (EEncoding Encoding)
Get the encode function that matches the encoding type.
TFunction< float(float)> GetDecodeFunction (EEncoding Encoding)
Get the decode function that matches the encoding type.
TFunction< float(float)> GetEncodeFunction (EEncoding Encoding)
Get the encode function that matches the encoding type.
FVector2d GetWhitePoint (EWhitePoint InWhitePoint)
Get standard white point coordinates.
float Linear (float Value)
template<typename T>
UE::Math::TMatrix< T > Transpose (const FMatrix44d &Transform)
Convenience function to get the transposed matrix, i.e.
FVector3d xyYToXYZ (const FVector3d &xyY)
Convert chromaticity coordinate and luminance to CIE XYZ tristimulus values.
FVector3d XYZToxyY (const FVector3d &XYZ)
Convert CIE XYZ tristimulus values to chromaticitiy coordinates and luminance.
Variables
constexpr uint32 COLORSPACE_VER = 2
Increment upon breaking changes to the EColorSpace and EChromaticAdaptationMethod enums.
constexpr EChromaticAdaptationMethod DEFAULT_CHROMATIC_ADAPTATION_METHOD = EChromaticAdaptationMethod::Bradford
Default method used across the engine for chromatic adaptation.
constexpr uint32 ENCODING_TYPES_VER = 4
Increment upon breaking changes to the EEncoding enum.
Enumeration Type Documentation
EChromaticAdaptationMethod
enum class UE::Color::EChromaticAdaptationMethod : uint8 strong
List of available chromatic adaptation methods.
NOTE: This list is replicated as a UENUM in TextureDefines.h, and both should always match.
Enumerator
None
Bradford
CAT02
Max
Definition at line 71 of file ColorManagementDefines.h.
EColorSpace
enum class UE::Color::EColorSpace : uint8 strong
List of available color spaces.
(Increment COLORSPACE_VER upon breaking changes to the list.)
NOTE: This list is partially replicated as a UENUM in TextureDefines.h: any type exposed to textures should match the enum value below.
Enumerator
None
sRGB
Rec2020
ACESAP0
ACESAP1
P3DCI
P3D65
REDWideGamut
SonySGamut3
SonySGamut3Cine
AlexaWideGamut
CanonCinemaGamut
GoProProtuneNative
PanasonicVGamut
PLASA_E1_54
ACESCAM16
Max
Definition at line 45 of file ColorManagementDefines.h.
EEncoding
enum class UE::Color::EEncoding : uint8 strong
List of available encodings/transfer functions.
NOTE: This list is replicated as a UENUM in TextureDefines.h, and both should always match.
Enumerator
None
Linear
sRGB
ST2084
Gamma22
BT1886
Gamma26
Cineon
REDLog
REDLog3G10
SLog1
SLog2
SLog3
AlexaV3LogC
CanonLog
ProTune
VLog
Max
Definition at line 19 of file ColorManagementDefines.h.
EWhitePoint
enum class UE::Color::EWhitePoint : uint8 strong
List of standard white points.
Enumerator
CIE1931_D65
ACES_D60
DCI_CalibrationWhite
Max
Definition at line 83 of file ColorManagementDefines.h.
Function Documentation
Decode() [1/2]
FLinearColor UE::Color::Decode (EEncoding Encoding, const FLinearColor & Color)
Decode a color based on the specified encoding type.
Note: Less optimal due to function pointer call.
Decode() [2/2]
float UE::Color::Decode (EEncoding Encoding, float Value)
Decode a value based on the specified encoding type.
Note: Less optimal due to function pointer call.
References Value.
DecodeArriAlexaV3LogC()
float UE::Color::DecodeArriAlexaV3LogC (float Value) inline
Decode value with an ARRI Alexa LogC encoding.
Returns
float decoded value.
Definition at line 380 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeBT1886()
float UE::Color::DecodeBT1886 (float Value) inline
Decode value with an ITU-R BT.1886 encoding.
Returns
float decoded value.
Definition at line 154 of file TransferFunctions.h.
References A, B, Gamma, FGenericPlatformMath::Max(), FGenericPlatformMath::Pow(), and Value.
DecodeCanonLog()
float UE::Color::DecodeCanonLog (float Value) inline
Decode value with a Canon Log encoding.
Returns
float decoded value.
Definition at line 423 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeCineon()
float UE::Color::DecodeCineon (float Value) inline
Decode value with a Cineon encoding.
Returns
float decoded value.
Definition at line 182 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeGamma22()
float UE::Color::DecodeGamma22 (float Value) inline
Decode value with a Gamma 2.2 encoding.
Returns
float decoded value.
Definition at line 106 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeGamma26()
float UE::Color::DecodeGamma26 (float Value) inline
Decode value with a Gamma 2.6 encoding.
Returns
float decoded value.
Definition at line 144 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeGoProProTune()
float UE::Color::DecodeGoProProTune (float Value) inline
Decode value with a GoPro ProTune encoding.
Returns
float decoded value.
Definition at line 450 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodePanasonicVLog()
float UE::Color::DecodePanasonicVLog (float Value) inline
Decode value with a Panasonic V-Log encoding.
Returns
float decoded value.
Definition at line 481 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeREDLog()
float UE::Color::DecodeREDLog (float Value) inline
Decode value with a RED Log encoding.
Returns
float decoded value.
Definition at line 204 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeREDLog3G10()
float UE::Color::DecodeREDLog3G10 (float Value) inline
Decode value with a RED Log3G10 encoding.
Returns
float decoded value.
Definition at line 239 of file TransferFunctions.h.
References A, FGenericPlatformMath::Abs(), B, G, FGenericPlatformMath::Pow(), FGenericPlatformMath::Sign(), and Value.
DecodeSLog1()
float UE::Color::DecodeSLog1 (float Value) inline
Decode value with a Sony S-Log1 encoding.
Returns
float decoded value.
Definition at line 275 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeSLog2()
float UE::Color::DecodeSLog2 (float Value) inline
Decode value with a Sony S-Log2 encoding.
Returns
float decoded value.
Definition at line 304 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeSLog3()
float UE::Color::DecodeSLog3 (float Value) inline
Decode value with a Sony S-Log3 encoding.
Returns
float decoded value.
Definition at line 338 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeSRGB()
float UE::Color::DecodeSRGB (float Value) inline
Decode value with an sRGB encoding.
Returns
float decoded value.
Definition at line 41 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
DecodeST2084()
float UE::Color::DecodeST2084 (float Value) inline
Decode value with a SMPTE ST 2084:2014 encoding.
Returns
float decoded value.
Definition at line 76 of file TransferFunctions.h.
References FGenericPlatformMath::Max(), FGenericPlatformMath::Pow(), and Value.
Encode() [1/2]
FLinearColor UE::Color::Encode (EEncoding Encoding, const FLinearColor & Color)
Encode a color based on the specified encoding type.
Note: Less optimal due to function pointer call.
Encode() [2/2]
float UE::Color::Encode (EEncoding Encoding, float Value)
Encode a value based on the specified encoding type.
Note: Less optimal due to function pointer call.
References Value.
EncodeArriAlexaV3LogC()
float UE::Color::EncodeArriAlexaV3LogC (float Value) inline
Encode value to ARRI Alexa LogC.
Returns
float encoded value.
Definition at line 355 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeBT1886()
float UE::Color::EncodeBT1886 (float Value) inline
Encode value to ITU-R BT.1886.
Returns
float encoded value.
Definition at line 116 of file TransferFunctions.h.
References A, B, Gamma, FGenericPlatformMath::Pow(), and Value.
EncodeCanonLog()
float UE::Color::EncodeCanonLog (float Value) inline
Encode value to Canon Log.
Returns
float encoded value.
Definition at line 405 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeCineon()
float UE::Color::EncodeCineon (float Value) inline
Encode value to Cineon.
Returns
float encoded value.
Definition at line 171 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), FGenericPlatformMath::Pow(), and Value.
EncodeGamma22()
float UE::Color::EncodeGamma22 (float Value) inline
Encode value to Gamma 2.2.
Returns
float encoded value.
Definition at line 95 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
EncodeGamma26()
float UE::Color::EncodeGamma26 (float Value) inline
Encode value to Gamma 2.6.
Returns
float encoded value.
Definition at line 133 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
EncodeGoProProTune()
float UE::Color::EncodeGoProProTune (float Value) inline
Encode value to GoPro ProTune.
Returns
float encoded value.
Definition at line 440 of file TransferFunctions.h.
References FGenericPlatformMath::Loge(), and Value.
EncodePanasonicVLog()
float UE::Color::EncodePanasonicVLog (float Value) inline
Encode value to Panasonic V-Log.
Returns
float encoded value.
Definition at line 460 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeREDLog()
float UE::Color::EncodeREDLog (float Value) inline
Encode value to RED Log.
Returns
float encoded value.
Definition at line 193 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), FGenericPlatformMath::Pow(), and Value.
EncodeREDLog3G10()
float UE::Color::EncodeREDLog3G10 (float Value) inline
Encode value to RED Log3G10.
Returns
float encoded value.
Definition at line 215 of file TransferFunctions.h.
References A, FGenericPlatformMath::Abs(), B, G, FGenericPlatformMath::LogX(), FGenericPlatformMath::Sign(), and Value.
EncodeSLog1()
float UE::Color::EncodeSLog1 (float Value) inline
Encode value to Sony S-Log1.
Returns
float encoded value.
Definition at line 263 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeSLog2()
float UE::Color::EncodeSLog2 (float Value) inline
Encode value to Sony S-Log2.
Returns
float encoded value.
Definition at line 287 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeSLog3()
float UE::Color::EncodeSLog3 (float Value) inline
Encode value to Sony S-Log3.
Returns
float encoded value.
Definition at line 321 of file TransferFunctions.h.
References FGenericPlatformMath::LogX(), and Value.
EncodeSRGB()
float UE::Color::EncodeSRGB (float Value) inline
Encode value to sRGB.
Returns
float encoded value.
Definition at line 24 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
EncodeST2084()
float UE::Color::EncodeST2084 (float Value) inline
Encode value to SMPTE ST 2084:2014.
Returns
float encoded value.
Definition at line 58 of file TransferFunctions.h.
References FGenericPlatformMath::Pow(), and Value.
GetColorDecodeFunction()
TFunction< FLinearColor(const FLinearColor &)> UE::Color::GetColorDecodeFunction (EEncoding Encoding)
Get the decode function that matches the encoding type.
GetColorEncodeFunction()
TFunction< FLinearColor(const FLinearColor &)> UE::Color::GetColorEncodeFunction (EEncoding Encoding)
Get the encode function that matches the encoding type.
GetDecodeFunction()
TFunction< float(float)> UE::Color::GetDecodeFunction (EEncoding Encoding)
Get the decode function that matches the encoding type.
GetEncodeFunction()
TFunction< float(float)> UE::Color::GetEncodeFunction (EEncoding Encoding)
Get the encode function that matches the encoding type.
GetWhitePoint()
FVector2d UE::Color::GetWhitePoint (EWhitePoint InWhitePoint) inline
Get standard white point coordinates.
Parameters
InWhitePoint White point type.
Returns
FVector2d Chromaticity coordinates.
Definition at line 78 of file ColorSpace.h.
References ACES_D60, checkNoEntry, CIE1931_D65, and DCI_CalibrationWhite.
Linear()
float UE::Color::Linear (float Value) inline
Definition at line 14 of file TransferFunctions.h.
References Value.
Transpose()
template<typename T> UE::Math::TMatrix< T > UE::Color::Transpose (const FMatrix44d & Transform) inline
Convenience function to get the transposed matrix, i.e.
for pre-multiplied shader matrices.
Returns
TMatrix<T>
Definition at line 60 of file ColorSpace.h.
References UE::Math::TMatrix< T >::GetTransposed(), and Transform.
xyYToXYZ()
FVector3d UE::Color::xyYToXYZ (const FVector3d & xyY) inline
Convert chromaticity coordinate and luminance to CIE XYZ tristimulus values.
Returns
FVector3d
Definition at line 23 of file ColorSpace.h.
References FMath::Max.
XYZToxyY()
FVector3d UE::Color::XYZToxyY (const FVector3d & XYZ) inline
Convert CIE XYZ tristimulus values to chromaticitiy coordinates and luminance.
Returns
FVector3d
Definition at line 39 of file ColorSpace.h.
Variable Documentation
COLORSPACE_VER
uint32 UE::Color::COLORSPACE_VER = 2 inline constexpr
Increment upon breaking changes to the EColorSpace and EChromaticAdaptationMethod enums.
Note that changing this forces a rebuild of textures that rely on it.
Definition at line 13 of file ColorManagementDefines.h.
DEFAULT_CHROMATIC_ADAPTATION_METHOD
EChromaticAdaptationMethod UE::Color::DEFAULT_CHROMATIC_ADAPTATION_METHOD = EChromaticAdaptationMethod::Bradford constexpr
Default method used across the engine for chromatic adaptation.
Definition at line 80 of file ColorManagementDefines.h.
Referenced by UE::Color::FColorSpaceTransform::FColorSpaceTransform(), and UE::Color::FColorSpaceTransform::CalcChromaticAdaptionMatrix().
ENCODING_TYPES_VER
uint32 UE::Color::ENCODING_TYPES_VER = 4 inline constexpr
Increment upon breaking changes to the EEncoding enum.
Note that changing this forces a rebuild of textures that rely on it.
Definition at line 10 of file ColorManagementDefines.h.