Unreal Engine 5.6 C++ API: FCSPose< PoseType > Struct Template Reference
FCSPose< PoseType > Struct Template Reference
#include "BonePose.h"
Public Types
typedef PoseType::Allocator AllocatorType
typedef PoseType::BoneIndexType BoneIndexType
Public Member Functions
void CalculateComponentSpaceTransform (BoneIndexType BoneIndex)
void ConvertBoneToLocalSpace (BoneIndexType BoneIndex)
Convert Bone to Local Space.
void CopyAndAssignBoneContainer (FBoneContainer &NewBoneContainer)
template<typename OtherPoseType>
void CopyPose (const OtherPoseType &SrcPose)
void Empty ()
const TCustomBoneIndexArray< uint8, BoneIndexType, AllocatorType > & GetComponentSpaceFlags () const
const FTransform & GetComponentSpaceTransform (BoneIndexType BoneIndex)
FTransform GetLocalSpaceTransform (BoneIndexType BoneIndex)
const PoseType & GetPose () const
void InitPose (const FBoneContainer *InBoneContainer)
void InitPose (const PoseType &SrcPose)
void InitPose (PoseType &&SrcPose)
FORCEINLINE_DEBUGGABLE void LocalBlendCSBoneTransforms (TConstArrayView< FBoneTransform > BoneTransforms, float Alpha)
Blends Component Space transforms to MeshPose in Local Space.
void SafeSetCSBoneTransforms (TConstArrayView< FBoneTransform > BoneTransforms)
Set a bunch of Component Space Bone Transforms.
void SetComponentSpaceTransform (BoneIndexType BoneIndex, const FTransform &NewTransform)
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE void ConvertComponentPosesToLocalPoses (const FCSPose< PoseType > &InPose, PoseType &OutPose)
This function convert component space to local space to OutPose.
static FORCEINLINE_DEBUGGABLE void ConvertComponentPosesToLocalPoses (FCSPose< PoseType > &&InPose, PoseType &OutPose)
This function convert component space to local space to OutPose.
static FORCEINLINE_DEBUGGABLE void ConvertComponentPosesToLocalPosesSafe (FCSPose< PoseType > &InPose, PoseType &OutPose)
This function convert component space to local space to OutPose.
Protected Attributes
TCustomBoneIndexArray< uint8, BoneIndexType, AllocatorType > BoneMask
TArray< FCompactPoseBoneIndex, AllocatorType > BonesToConvert
TCustomBoneIndexArray< uint8, BoneIndexType, AllocatorType > ComponentSpaceFlags
PoseType Pose
Detailed Description
template<class PoseType>
struct FCSPose< PoseType >
Definition at line 407 of file BonePose.h.
Member Typedef Documentation
AllocatorType
template<class PoseType> typedef PoseType::Allocator FCSPose< PoseType >::AllocatorType
Definition at line 411 of file BonePose.h.
BoneIndexType
template<class PoseType> typedef PoseType::BoneIndexType FCSPose< PoseType >::BoneIndexType
Definition at line 410 of file BonePose.h.
Member Function Documentation
CalculateComponentSpaceTransform()
template<class PoseType> void FCSPose< PoseType >::CalculateComponentSpaceTransform (BoneIndexType BoneIndex)
Definition at line 594 of file BonePose.h.
References TArray< InElementType, InAllocatorType >::Add(), check, checkf, checkSlow, ComponentSpaceFlags, UE::Math::TTransform< T >::ContainsNaN(), FBase64::Encode(), No, UE::Math::TTransform< T >::NormalizeRotation(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Pop(), Pose, TArray< InElementType, InAllocatorType >::Reserve(), TEXT, and UE::Math::TTransform< T >::ToString().
Referenced by ConvertComponentPosesToLocalPosesSafe(), GetComponentSpaceTransform(), and SafeSetCSBoneTransforms().
ConvertBoneToLocalSpace()
template<class PoseType> void FCSPose< PoseType >::ConvertBoneToLocalSpace (BoneIndexType BoneIndex)
Convert Bone to Local Space.
Definition at line 652 of file BonePose.h.
References check, checkSlow, ComponentSpaceFlags, and Pose.
Referenced by LocalBlendCSBoneTransforms(), and SafeSetCSBoneTransforms().
ConvertComponentPosesToLocalPoses() [1/2]
template<class PoseType> void FCSPose< PoseType >::ConvertComponentPosesToLocalPoses (const FCSPose< PoseType > & InPose, PoseType & OutPose) static
This function convert component space to local space to OutPose.
This has been optimized with an assumption of all parents are calculated in component space for those who have been converted to component space
If a part of chain hasn't been converted, it will trigger ensure.
Definition at line 830 of file BonePose.h.
References checkSlow, ComponentSpaceFlags, ensureMsgf, Pose, and TEXT.
ConvertComponentPosesToLocalPoses() [2/2]
template<class PoseType> void FCSPose< PoseType >::ConvertComponentPosesToLocalPoses (FCSPose< PoseType > && InPose, PoseType & OutPose) static
This function convert component space to local space to OutPose.
This has been optimized with an assumption of all parents are calculated in component space for those who have been converted to component space After this function, accessing InPose.Pose won't be valid anymore because of Move semantics
If a part of chain hasn't been converted, it will trigger ensure.
Definition at line 865 of file BonePose.h.
References checkSlow, ensureMsgf, FBaseCompactPose< InAllocator >::GetParentBoneIndex(), MoveTemp(), and TEXT.
ConvertComponentPosesToLocalPosesSafe()
template<class PoseType> void FCSPose< PoseType >::ConvertComponentPosesToLocalPosesSafe (FCSPose< PoseType > & InPose, PoseType & OutPose) static
This function convert component space to local space to OutPose.
Contrast to ConvertComponentPosesToLocalPoses, this allows some parts of chain to stay in local space before conversion And it will calculate back to component space correctly before converting back to new local space This is issue when child is in component space, but the parent is not. Then we have to convert parents to be in the component space before converting back to local
However it is more expensive as a result.
Definition at line 904 of file BonePose.h.
References CalculateComponentSpaceTransform(), checkSlow, ComponentSpaceFlags, FBaseCompactPose< InAllocator >::GetParentBoneIndex(), and Pose.
CopyAndAssignBoneContainer()
template<class PoseType> void FCSPose< PoseType >::CopyAndAssignBoneContainer (FBoneContainer & NewBoneContainer) inline
Definition at line 448 of file BonePose.h.
References Pose.
CopyPose()
template<class PoseType> template<typename OtherPoseType> void FCSPose< PoseType >::CopyPose (const OtherPoseType & SrcPose) inline
Definition at line 442 of file BonePose.h.
References ComponentSpaceFlags, and Pose.
Empty()
template<class PoseType> void FCSPose< PoseType >::Empty () inline
Definition at line 453 of file BonePose.h.
References BoneMask, BonesToConvert, ComponentSpaceFlags, and Pose.
GetComponentSpaceFlags()
template<class PoseType> const TCustomBoneIndexArray< uint8, BoneIndexType, AllocatorType > & FCSPose< PoseType >::GetComponentSpaceFlags () const inline
Definition at line 462 of file BonePose.h.
References ComponentSpaceFlags.
GetComponentSpaceTransform()
template<class PoseType> const FTransform & FCSPose< PoseType >::GetComponentSpaceTransform (BoneIndexType BoneIndex)
Definition at line 566 of file BonePose.h.
References CalculateComponentSpaceTransform(), check, checkSlow, ComponentSpaceFlags, and Pose.
Referenced by GetLocalSpaceTransform(), and USTRUCT().
GetLocalSpaceTransform()
template<class PoseType> FTransform FCSPose< PoseType >::GetLocalSpaceTransform (BoneIndexType BoneIndex)
Definition at line 543 of file BonePose.h.
References check, checkSlow, ComponentSpaceFlags, GetComponentSpaceTransform(), UE::Math::TTransform< T >::GetRelativeTransform(), INDEX_NONE, and Pose.
Referenced by LocalBlendCSBoneTransforms().
GetPose()
template<class PoseType> const PoseType & FCSPose< PoseType >::GetPose () const inline
Definition at line 461 of file BonePose.h.
References Pose.
InitPose() [1/3]
template<class PoseType> void FCSPose< PoseType >::InitPose (const FBoneContainer * InBoneContainer) inline
Definition at line 414 of file BonePose.h.
References ComponentSpaceFlags, and Pose.
InitPose() [2/3]
template<class PoseType> void FCSPose< PoseType >::InitPose (const PoseType & SrcPose) inline
Definition at line 424 of file BonePose.h.
References ComponentSpaceFlags, and Pose.
InitPose() [3/3]
template<class PoseType> void FCSPose< PoseType >::InitPose (PoseType && SrcPose) inline
Definition at line 432 of file BonePose.h.
References ComponentSpaceFlags, MoveTemp(), and Pose.
LocalBlendCSBoneTransforms()
template<class PoseType> void FCSPose< PoseType >::LocalBlendCSBoneTransforms (TConstArrayView< FBoneTransform > BoneTransforms, float Alpha)
Blends Component Space transforms to MeshPose in Local Space.
Used by SkelControls to apply their transforms.
The tricky bit is that SkelControls deliver their transforms in Component Space, But the blending is done in Local Space. Also we need to refresh any Children they have that has been previously converted to Component Space.
Definition at line 737 of file BonePose.h.
References Alpha, BoneMask, BoneTransforms, check, ComponentSpaceFlags, ConvertBoneToLocalSpace(), GetLocalSpaceTransform(), INDEX_NONE, TArray< InElementType, InAllocatorType >::Num(), Pose, SafeSetCSBoneTransforms(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), Transform, and ZERO_ANIMWEIGHT_THRESH.
SafeSetCSBoneTransforms()
template<class PoseType> void FCSPose< PoseType >::SafeSetCSBoneTransforms (TConstArrayView< FBoneTransform > BoneTransforms)
Set a bunch of Component Space Bone Transforms.
Do this safely by insuring that Parents are already in Component Space, and any Component Space children are converted back to Local Space before hand.
Definition at line 672 of file BonePose.h.
References BonesToConvert, BoneTransforms, CalculateComponentSpaceTransform(), checkSlow, ComponentSpaceFlags, ConvertBoneToLocalSpace(), INDEX_NONE, Pose, SetComponentSpaceTransform(), and Transform.
Referenced by LocalBlendCSBoneTransforms().
SetComponentSpaceTransform()
template<class PoseType> void FCSPose< PoseType >::SetComponentSpaceTransform (BoneIndexType BoneIndex, const FTransform & NewTransform)
Definition at line 583 of file BonePose.h.
References check, checkSlow, ComponentSpaceFlags, and Pose.
Referenced by SafeSetCSBoneTransforms().
Field Documentation
BoneMask
template<class PoseType> TCustomBoneIndexArray<uint8, BoneIndexType, AllocatorType> FCSPose< PoseType >::BoneMask protected
Definition at line 536 of file BonePose.h.
Referenced by Empty(), and LocalBlendCSBoneTransforms().
BonesToConvert
template<class PoseType> TArray<FCompactPoseBoneIndex, AllocatorType> FCSPose< PoseType >::BonesToConvert protected
Definition at line 539 of file BonePose.h.
Referenced by Empty(), and SafeSetCSBoneTransforms().
ComponentSpaceFlags
template<class PoseType> TCustomBoneIndexArray<uint8, BoneIndexType, AllocatorType> FCSPose< PoseType >::ComponentSpaceFlags protected
Definition at line 533 of file BonePose.h.
Referenced by CalculateComponentSpaceTransform(), ConvertBoneToLocalSpace(), ConvertComponentPosesToLocalPoses(), ConvertComponentPosesToLocalPosesSafe(), CopyPose(), Empty(), GetComponentSpaceFlags(), GetComponentSpaceTransform(), GetLocalSpaceTransform(), InitPose(), InitPose(), InitPose(), LocalBlendCSBoneTransforms(), SafeSetCSBoneTransforms(), and SetComponentSpaceTransform().
Pose
template<class PoseType> PoseType FCSPose< PoseType >::Pose protected
Definition at line 530 of file BonePose.h.
Referenced by CalculateComponentSpaceTransform(), ConvertBoneToLocalSpace(), ConvertComponentPosesToLocalPoses(), ConvertComponentPosesToLocalPosesSafe(), CopyAndAssignBoneContainer(), CopyPose(), Empty(), GetComponentSpaceTransform(), GetLocalSpaceTransform(), GetPose(), InitPose(), InitPose(), InitPose(), LocalBlendCSBoneTransforms(), SafeSetCSBoneTransforms(), and SetComponentSpaceTransform().
The documentation for this struct was generated from the following files:
AnimNodeEditMode.h
BonePose.h