Unreal Engine 5.6 C++ API: FStaticMeshAttributes Class Reference
FStaticMeshAttributes Class Reference
#include "StaticMeshAttributes.h"
Public Member Functions
FStaticMeshAttributes (FMeshDescription &InMeshDescription)
TEdgeAttributesRef< bool > GetEdgeHardnesses ()
TEdgeAttributesConstRef< bool > GetEdgeHardnesses () const
TPolygonGroupAttributesRef< FName > GetPolygonGroupMaterialSlotNames ()
TPolygonGroupAttributesConstRef< FName > GetPolygonGroupMaterialSlotNames () const
TTriangleAttributesRef< FVector3f > GetTriangleBinormals ()
TTriangleAttributesConstRef< FVector3f > GetTriangleBinormals () const
TTriangleAttributesRef< FVector3f > GetTriangleNormals ()
TTriangleAttributesConstRef< FVector3f > GetTriangleNormals () const
TTriangleAttributesRef< FVector3f > GetTriangleTangents ()
TTriangleAttributesConstRef< FVector3f > GetTriangleTangents () const
TVertexInstanceAttributesRef< float > GetVertexInstanceBinormalSigns ()
TVertexInstanceAttributesConstRef< float > GetVertexInstanceBinormalSigns () const
TVertexInstanceAttributesRef< FVector4f > GetVertexInstanceColors ()
TVertexInstanceAttributesConstRef< FVector4f > GetVertexInstanceColors () const
TVertexInstanceAttributesRef< FVector3f > GetVertexInstanceNormals ()
TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceNormals () const
TVertexInstanceAttributesRef< FVector3f > GetVertexInstanceTangents ()
TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceTangents () const
TVertexInstanceAttributesRef< FVector2f > GetVertexInstanceUVs ()
TVertexInstanceAttributesConstRef< FVector2f > GetVertexInstanceUVs () const
virtual STATICMESHDESCRIPTION_API void Register (bool bKeepExistingAttribute=false) override
STATICMESHDESCRIPTION_API void RegisterTriangleNormalAndTangentAttributes ()
UE_DEPRECATED (4.26, "Please use RegisterTriangleNormalAndTangentAttributes() instead.") STATICMESHDESCRIPTION_API void RegisterPolygonNormalAndTangentAttributes()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TEdgeAttributesConstRef< float > GetEdgeCreaseSharpnesses() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TEdgeAttributesRef< float > GetEdgeCreaseSharpnesses()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonBinormals() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonCenters() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonNormals() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesConstRef< FVector3f > GetPolygonTangents() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonBinormals()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonCenters()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonNormals()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TPolygonAttributesRef< FVector3f > GetPolygonTangents()
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TVertexAttributesConstRef< float > GetVertexCornerSharpnesses() const
UE_DEPRECATED (4.26, "This attribute is no longer supported, please remove code pertaining to it.") TVertexAttributesRef< float > GetVertexCornerSharpnesses()
Public Member Functions inherited from FMeshAttributes
FMeshAttributes (FMeshDescription &InMeshDescription)
virtual ~FMeshAttributes ()=default
TEdgeAttributesRef< TArrayView< FVertexID > > GetEdgeVertexIndices ()
Accessors for array of vertex IDs for edges.
TEdgeAttributesConstRef< TArrayView< FVertexID > > GetEdgeVertexIndices () const
TPolygonAttributesRef< FPolygonGroupID > GetPolygonPolygonGroupIndices ()
Accessors for array of polygon group IDs for polygons.
TPolygonAttributesConstRef< FPolygonGroupID > GetPolygonPolygonGroupIndices () const
TTriangleAttributesRef< TArrayView< FEdgeID > > GetTriangleEdgeIndices ()
Accessors for array of edge IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FEdgeID > > GetTriangleEdgeIndices () const
TTriangleAttributesRef< FPolygonGroupID > GetTrianglePolygonGroupIndices ()
Accessors for array of polygon group IDs for triangles.
TTriangleAttributesConstRef< FPolygonGroupID > GetTrianglePolygonGroupIndices () const
TTriangleAttributesRef< TArrayView< FUVID > > GetTriangleUVIndices ()
Accessors for array of UV IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FUVID > > GetTriangleUVIndices () const
TTriangleAttributesRef< TArrayView< FVertexID > > GetTriangleVertexIndices ()
Accessors for array of vertex IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FVertexID > > GetTriangleVertexIndices () const
TTriangleAttributesRef< TArrayView< FVertexInstanceID > > GetTriangleVertexInstanceIndices ()
Accessors for array of vertex instance IDs for triangles.
TTriangleAttributesConstRef< TArrayView< FVertexInstanceID > > GetTriangleVertexInstanceIndices () const
TUVAttributesRef< FVector2f > GetUVCoordinates (int32 UVChannel)
Accessors for UV coordinates.
TUVAttributesConstRef< FVector2f > GetUVCoordinates (int32 UVChannel) const
TVertexInstanceAttributesRef< FVertexID > GetVertexInstanceVertexIndices ()
Accessors for array of vertex IDs for vertex instances.
TVertexInstanceAttributesConstRef< FVertexID > GetVertexInstanceVertexIndices () const
TVertexAttributesRef< FVector3f > GetVertexPositions ()
Accessors for cached vertex position array.
TVertexAttributesConstRef< FVector3f > GetVertexPositions () const
Static Public Member Functions
static bool IsReservedAttributeName (const FName InAttributeName)
Static Public Member Functions inherited from FMeshAttributes
static bool IsReservedAttributeName (const FName InAttributeName)
Additional Inherited Members
Protected Attributes inherited from FMeshAttributes
FMeshDescription & MeshDescription
Detailed Description
Definition at line 72 of file StaticMeshAttributes.h.
Constructor & Destructor Documentation
FStaticMeshAttributes()
FStaticMeshAttributes::FStaticMeshAttributes (FMeshDescription & InMeshDescription) inline explicit
Definition at line 76 of file StaticMeshAttributes.h.
References FMeshAttributes::FMeshAttributes().
Member Function Documentation
GetEdgeHardnesses() [1/2]
TEdgeAttributesRef< bool > FStaticMeshAttributes::GetEdgeHardnesses () inline
Definition at line 123 of file StaticMeshAttributes.h.
References MeshAttribute::Edge::IsHard, and FMeshAttributes::MeshDescription.
GetEdgeHardnesses() [2/2]
TEdgeAttributesConstRef< bool > FStaticMeshAttributes::GetEdgeHardnesses () const inline
Definition at line 124 of file StaticMeshAttributes.h.
References MeshAttribute::Edge::IsHard, and FMeshAttributes::MeshDescription.
GetPolygonGroupMaterialSlotNames() [1/2]
TPolygonGroupAttributesRef< FName > FStaticMeshAttributes::GetPolygonGroupMaterialSlotNames () inline
Definition at line 160 of file StaticMeshAttributes.h.
References MeshAttribute::PolygonGroup::ImportedMaterialSlotName, and FMeshAttributes::MeshDescription.
GetPolygonGroupMaterialSlotNames() [2/2]
TPolygonGroupAttributesConstRef< FName > FStaticMeshAttributes::GetPolygonGroupMaterialSlotNames () const inline
Definition at line 161 of file StaticMeshAttributes.h.
References MeshAttribute::PolygonGroup::ImportedMaterialSlotName, and FMeshAttributes::MeshDescription.
GetTriangleBinormals() [1/2]
TTriangleAttributesRef< FVector3f > FStaticMeshAttributes::GetTriangleBinormals () inline
Definition at line 137 of file StaticMeshAttributes.h.
References MeshAttribute::Triangle::Binormal, and FMeshAttributes::MeshDescription.
GetTriangleBinormals() [2/2]
TTriangleAttributesConstRef< FVector3f > FStaticMeshAttributes::GetTriangleBinormals () const inline
Definition at line 138 of file StaticMeshAttributes.h.
References MeshAttribute::Triangle::Binormal, and FMeshAttributes::MeshDescription.
GetTriangleNormals() [1/2]
TTriangleAttributesRef< FVector3f > FStaticMeshAttributes::GetTriangleNormals () inline
Definition at line 131 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::Triangle::Normal.
GetTriangleNormals() [2/2]
TTriangleAttributesConstRef< FVector3f > FStaticMeshAttributes::GetTriangleNormals () const inline
Definition at line 132 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::Triangle::Normal.
GetTriangleTangents() [1/2]
TTriangleAttributesRef< FVector3f > FStaticMeshAttributes::GetTriangleTangents () inline
Definition at line 134 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::Triangle::Tangent.
GetTriangleTangents() [2/2]
TTriangleAttributesConstRef< FVector3f > FStaticMeshAttributes::GetTriangleTangents () const inline
Definition at line 135 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::Triangle::Tangent.
GetVertexInstanceBinormalSigns() [1/2]
TVertexInstanceAttributesRef< float > FStaticMeshAttributes::GetVertexInstanceBinormalSigns () inline
Definition at line 117 of file StaticMeshAttributes.h.
References MeshAttribute::VertexInstance::BinormalSign, and FMeshAttributes::MeshDescription.
GetVertexInstanceBinormalSigns() [2/2]
TVertexInstanceAttributesConstRef< float > FStaticMeshAttributes::GetVertexInstanceBinormalSigns () const inline
Definition at line 118 of file StaticMeshAttributes.h.
References MeshAttribute::VertexInstance::BinormalSign, and FMeshAttributes::MeshDescription.
GetVertexInstanceColors() [1/2]
TVertexInstanceAttributesRef< FVector4f > FStaticMeshAttributes::GetVertexInstanceColors () inline
Definition at line 120 of file StaticMeshAttributes.h.
References MeshAttribute::VertexInstance::Color, and FMeshAttributes::MeshDescription.
GetVertexInstanceColors() [2/2]
TVertexInstanceAttributesConstRef< FVector4f > FStaticMeshAttributes::GetVertexInstanceColors () const inline
Definition at line 121 of file StaticMeshAttributes.h.
References MeshAttribute::VertexInstance::Color, and FMeshAttributes::MeshDescription.
GetVertexInstanceNormals() [1/2]
TVertexInstanceAttributesRef< FVector3f > FStaticMeshAttributes::GetVertexInstanceNormals () inline
Definition at line 111 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::Normal.
GetVertexInstanceNormals() [2/2]
TVertexInstanceAttributesConstRef< FVector3f > FStaticMeshAttributes::GetVertexInstanceNormals () const inline
Definition at line 112 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::Normal.
GetVertexInstanceTangents() [1/2]
TVertexInstanceAttributesRef< FVector3f > FStaticMeshAttributes::GetVertexInstanceTangents () inline
Definition at line 114 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::Tangent.
GetVertexInstanceTangents() [2/2]
TVertexInstanceAttributesConstRef< FVector3f > FStaticMeshAttributes::GetVertexInstanceTangents () const inline
Definition at line 115 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::Tangent.
GetVertexInstanceUVs() [1/2]
TVertexInstanceAttributesRef< FVector2f > FStaticMeshAttributes::GetVertexInstanceUVs () inline
Definition at line 108 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::TextureCoordinate.
GetVertexInstanceUVs() [2/2]
TVertexInstanceAttributesConstRef< FVector2f > FStaticMeshAttributes::GetVertexInstanceUVs () const inline
Definition at line 109 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and MeshAttribute::VertexInstance::TextureCoordinate.
IsReservedAttributeName()
bool FStaticMeshAttributes::IsReservedAttributeName (const FName InAttributeName) inline static
Definition at line 82 of file StaticMeshAttributes.h.
References MeshAttribute::Triangle::Binormal, MeshAttribute::VertexInstance::BinormalSign, MeshAttribute::VertexInstance::Color, MeshAttribute::PolygonGroup::ImportedMaterialSlotName, MeshAttribute::Edge::IsHard, FMeshAttributes::IsReservedAttributeName(), MeshAttribute::Triangle::Normal, MeshAttribute::VertexInstance::Normal, MeshAttribute::Triangle::Tangent, MeshAttribute::VertexInstance::Tangent, and MeshAttribute::VertexInstance::TextureCoordinate.
Referenced by FSkeletalMeshAttributes::IsReservedAttributeName().
Register()
virtual STATICMESHDESCRIPTION_API void FStaticMeshAttributes::Register (bool bKeepExistingAttribute = false) override virtual
Reimplemented from FMeshAttributes.
Reimplemented in FSkeletalMeshAttributes.
RegisterTriangleNormalAndTangentAttributes()
STATICMESHDESCRIPTION_API void FStaticMeshAttributes::RegisterTriangleNormalAndTangentAttributes ()
References RegisterTriangleNormalAndTangentAttributes().
Referenced by RegisterTriangleNormalAndTangentAttributes().
UE_DEPRECATED() [1/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "Please use RegisterTriangleNormalAndTangentAttributes() instead.")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 128 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [3/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 126 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [4/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 152 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [5/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 157 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [6/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 142 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [7/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 147 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [8/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 150 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [9/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 155 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [10/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 140 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [11/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 145 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [12/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") const inline
Definition at line 105 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription.
UE_DEPRECATED() [13/13]
FStaticMeshAttributes::UE_DEPRECATED (4. 26, "This attribute is no longer supported, please remove code pertaining to it.") inline
Definition at line 103 of file StaticMeshAttributes.h.
References FMeshAttributes::MeshDescription, and UE_DEPRECATED().
The documentation for this class was generated from the following file:
StaticMeshAttributes.h