Unreal Engine 5.6 C++ API: TIndirectArray< T, Allocator > Class Template Reference
TIndirectArray< T, Allocator > Class Template Reference
#include "IndirectArray.h"
Public Types
typedef T ElementType
typedef TArray< void *, Allocator > InternalArrayType
typedef TIndexedContainerIterator< const TIndirectArray, const ElementType, int32 > TConstIterator
typedef TIndexedContainerIterator< TIndirectArray, ElementType, int32 > TIterator
Public Member Functions
TIndirectArray ()=default
Default constructors.
TIndirectArray (const TIndirectArray &Other)
Copy constructor.
TIndirectArray (TIndirectArray &&)=default
~TIndirectArray ()
Destructor.
FORCEINLINE int32 Add (T *Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE TDereferencingIterator< ElementType, typename InternalArrayType::RangedForIteratorType > begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TDereferencingIterator< const ElementType, typename InternalArrayType::RangedForConstIteratorType > begin () const
void CountBytes (FArchive &Ar) const
Count bytes needed to serialize this array.
TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this array.
TIterator CreateIterator ()
Creates an iterator for the contents of this array.
void Empty (int32 Slack=0)
Empties the array.
FORCEINLINE TDereferencingIterator< ElementType, typename InternalArrayType::RangedForIteratorType > end ()
FORCEINLINE TDereferencingIterator< const ElementType, typename InternalArrayType::RangedForConstIteratorType > end () const
SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
FORCEINLINE T ** GetData ()
Helper function for returning a typed pointer to the first array entry.
FORCEINLINE const T ** GetData () const
Helper function for returning a typed pointer to the first array entry.
FORCEINLINE void Insert (T *Item, int32 Index)
Inserts a given element into the array at given location.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
FORCEINLINE bool IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
FORCEINLINE ElementType & Last (int32 IndexFromTheEnd=0)
Returns n-th last element from the array.
FORCEINLINE const ElementType & Last (int32 IndexFromTheEnd=0) const
Returns n-th last element from the array.
FORCEINLINE int32 Num () const
Gets number of elements in array.
TIndirectArray & operator= (const TIndirectArray &Other)
Assignment operators.
TIndirectArray & operator= (TIndirectArray &&Other)
FORCEINLINE T & operator[] (int32 Index)
Bracket array access operator.
FORCEINLINE const T & operator[] (int32 Index) const
Bracket array access operator.
void RemoveAt (int32 Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element at given location optionally shrinking the array.
void RemoveAt (int32 Index, int32 Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes elements at given location optionally shrinking the array.
void RemoveAtSwap (int32 Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element at given location optionally shrinking the array.
void RemoveAtSwap (int32 Index, int32 Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes elements at given location optionally shrinking the array.
FORCEINLINE void Reserve (int32 Number)
Reserves memory such that the array can contain at least Number elements.
void Reset (int32 NewSize=0)
Resets the array to the new given size.
void Serialize (FArchive &Ar, UObject *Owner)
Special serialize function passing the owning UObject along as required by FUnytpedBulkData serialization.
void Shrink ()
Shrinks the array's used memory to smallest possible to store elements currently in it.
void Swap (int32 FirstIndexToSwap, int32 SecondIndexToSwap)
Element-wise array element swap.
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt") FORCEINLINE void RemoveAt(int32 Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") FORCEINLINE void RemoveAtSwap(int32 Index
Static Public Member Functions
static constexpr uint32 GetTypeSize ()
Helper function returning the size of the inner type.
Data Fields
int32 bool bAllowShrinking
int32 Count
Private Member Functions
void DestructAndFreeItems ()
Calls destructor and frees memory on every element in the array.
Private Attributes
InternalArrayType Array
Detailed Description
template<typename T, typename Allocator = FDefaultAllocator>
class TIndirectArray< T, Allocator >
Definition at line 19 of file IndirectArray.h.
Member Typedef Documentation
ElementType
template<typename T, typename Allocator = FDefaultAllocator> typedef T TIndirectArray< T, Allocator >::ElementType
Definition at line 22 of file IndirectArray.h.
InternalArrayType
template<typename T, typename Allocator = FDefaultAllocator> typedef TArray<void*, Allocator> TIndirectArray< T, Allocator >::InternalArrayType
Definition at line 23 of file IndirectArray.h.
TConstIterator
template<typename T, typename Allocator = FDefaultAllocator> typedef TIndexedContainerIterator<const TIndirectArray, const ElementType, int32> TIndirectArray< T, Allocator >::TConstIterator
Definition at line 425 of file IndirectArray.h.
TIterator
template<typename T, typename Allocator = FDefaultAllocator> typedef TIndexedContainerIterator< TIndirectArray, ElementType, int32> TIndirectArray< T, Allocator >::TIterator
Definition at line 424 of file IndirectArray.h.
Constructor & Destructor Documentation
TIndirectArray() [1/3]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::TIndirectArray () nodiscard default
Default constructors.
TIndirectArray() [2/3]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::TIndirectArray (TIndirectArray< T, Allocator > &&) nodiscard default
TIndirectArray() [3/3]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::TIndirectArray (const TIndirectArray< T, Allocator > & Other) inline nodiscard
Copy constructor.
Parameters
Other Other array to copy from.
Definition at line 34 of file IndirectArray.h.
~TIndirectArray()
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::~TIndirectArray () inline
Destructor.
Definition at line 73 of file IndirectArray.h.
Member Function Documentation
Add()
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE int32 TIndirectArray< T, Allocator >::Add (T * Item) inline
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
Parameters
Item The item to add.
Returns
Index to the new item.
Definition at line 374 of file IndirectArray.h.
begin() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE TDereferencingIterator< ElementType, typename InternalArrayType::RangedForIteratorType > TIndirectArray< T, Allocator >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 467 of file IndirectArray.h.
begin() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE TDereferencingIterator< const ElementType, typename InternalArrayType::RangedForConstIteratorType > TIndirectArray< T, Allocator >::begin () const inline nodiscard
Definition at line 468 of file IndirectArray.h.
CountBytes()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::CountBytes (FArchive & Ar) const inline
Count bytes needed to serialize this array.
Parameters
Ar Archive to count for.
Definition at line 241 of file IndirectArray.h.
Referenced by TIndirectArray< FChunk, AllocatorType >::Serialize().
CreateConstIterator()
template<typename T, typename Allocator = FDefaultAllocator> TConstIterator TIndirectArray< T, Allocator >::CreateConstIterator () const inline nodiscard
Creates a const iterator for the contents of this array.
Returns
The const iterator.
Definition at line 442 of file IndirectArray.h.
CreateIterator()
template<typename T, typename Allocator = FDefaultAllocator> TIterator TIndirectArray< T, Allocator >::CreateIterator () inline nodiscard
Creates an iterator for the contents of this array.
Returns
The iterator.
Definition at line 432 of file IndirectArray.h.
DestructAndFreeItems()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::DestructAndFreeItems () inline private
Calls destructor and frees memory on every element in the array.
Definition at line 452 of file IndirectArray.h.
Referenced by TIndirectArray< FChunk, AllocatorType >::Empty(), and TIndirectArray< FChunk, AllocatorType >::Reset().
Empty()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::Empty (int32 Slack = 0) inline
Empties the array.
It calls the destructors on held items.
Parameters
Slack (Optional) The expected usage size after empty operation. Default is 0.
Definition at line 361 of file IndirectArray.h.
end() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE TDereferencingIterator< ElementType, typename InternalArrayType::RangedForIteratorType > TIndirectArray< T, Allocator >::end () inline nodiscard
Definition at line 469 of file IndirectArray.h.
end() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE TDereferencingIterator< const ElementType, typename InternalArrayType::RangedForConstIteratorType > TIndirectArray< T, Allocator >::end () const inline nodiscard
Definition at line 470 of file IndirectArray.h.
GetAllocatedSize()
template<typename T, typename Allocator = FDefaultAllocator> SIZE_T TIndirectArray< T, Allocator >::GetAllocatedSize () const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Returns
Number of bytes allocated by this container.
Definition at line 418 of file IndirectArray.h.
GetData() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE T ** TIndirectArray< T, Allocator >::GetData () inline nodiscard
Helper function for returning a typed pointer to the first array entry.
Returns
Pointer to first array entry or nullptr if this->ArrayMax == 0.
Definition at line 104 of file IndirectArray.h.
Referenced by TIndirectArray< FChunk, AllocatorType >::DestructAndFreeItems(), TIndirectArray< FChunk, AllocatorType >::RemoveAt(), TIndirectArray< FChunk, AllocatorType >::RemoveAt(), TIndirectArray< FChunk, AllocatorType >::RemoveAtSwap(), and TIndirectArray< FChunk, AllocatorType >::RemoveAtSwap().
GetData() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE const T ** TIndirectArray< T, Allocator >::GetData () const inline nodiscard
Helper function for returning a typed pointer to the first array entry.
Returns
Pointer to first array entry or nullptr if this->ArrayMax == 0.
Definition at line 114 of file IndirectArray.h.
GetTypeSize()
template<typename T, typename Allocator = FDefaultAllocator> constexpr uint32 TIndirectArray< T, Allocator >::GetTypeSize () inline static nodiscard constexpr
Helper function returning the size of the inner type.
Returns
Size in bytes of array type.
Definition at line 124 of file IndirectArray.h.
Insert()
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE void TIndirectArray< T, Allocator >::Insert (T * Item, int32 Index) inline
Inserts a given element into the array at given location.
Parameters
Item The element to insert.
Index Tells where to insert the new elements.
Definition at line 385 of file IndirectArray.h.
IsEmpty()
template<typename T, typename Allocator = FDefaultAllocator> bool TIndirectArray< T, Allocator >::IsEmpty () const inline nodiscard
Returns true if the array is empty and contains no elements.
Returns
True if the array is empty.
See also
Num
Definition at line 84 of file IndirectArray.h.
IsValidIndex()
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE bool TIndirectArray< T, Allocator >::IsValidIndex (int32 Index) const inline nodiscard
Tests if index is valid, i.e.
greater than zero and less than number of elements in array.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 408 of file IndirectArray.h.
Referenced by UE::Geometry::FConvexDecomposition3::FProximity::GetMergeCost().
Last() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE ElementType & TIndirectArray< T, Allocator >::Last (int32 IndexFromTheEnd = 0) inline nodiscard
Returns n-th last element from the array.
Parameters
IndexFromTheEnd (Optional) Index from the end of array (default = 0).
Returns
Reference to n-th last element from the array.
Definition at line 159 of file IndirectArray.h.
Last() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE const ElementType & TIndirectArray< T, Allocator >::Last (int32 IndexFromTheEnd = 0) const inline nodiscard
Returns n-th last element from the array.
Const version.
Parameters
IndexFromTheEnd (Optional) Index from the end of array (default = 0).
Returns
Reference to n-th last element from the array.
Definition at line 172 of file IndirectArray.h.
Num()
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE int32 TIndirectArray< T, Allocator >::Num () const inline nodiscard
Gets number of elements in array.
Returns
Number of elements in array.
Definition at line 94 of file IndirectArray.h.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), FStaticMeshComponentHelper::CreateSceneProxy(), and SMultiColumnTableRow< ItemType >::GenerateColumns().
operator=() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray & TIndirectArray< T, Allocator >::operator= (const TIndirectArray< T, Allocator > & Other) inline
Assignment operators.
Parameters
Other Other array to assign with.
Definition at line 47 of file IndirectArray.h.
operator=() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray & TIndirectArray< T, Allocator >::operator= (TIndirectArray< T, Allocator > && Other) inline
Definition at line 60 of file IndirectArray.h.
operator[]() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE T & TIndirectArray< T, Allocator >::operator[] (int32 Index) inline nodiscard
Bracket array access operator.
Parameters
Index Position of element to return.
Returns
Reference to element in array at given position.
Definition at line 135 of file IndirectArray.h.
operator[]() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE const T & TIndirectArray< T, Allocator >::operator[] (int32 Index) const inline nodiscard
Bracket array access operator.
Const version.
Parameters
Index Position of element to return.
Returns
Reference to element in array at given position.
Definition at line 148 of file IndirectArray.h.
RemoveAt() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::RemoveAt (int32 Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element at given location optionally shrinking the array.
Parameters
Index Location in array of the element to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 254 of file IndirectArray.h.
RemoveAt() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::RemoveAt (int32 Index, int32 Count, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes elements at given location optionally shrinking the array.
Parameters
Index Location in array of the first element to remove.
Count Number of elements to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 272 of file IndirectArray.h.
RemoveAtSwap() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::RemoveAtSwap (int32 Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element at given location optionally shrinking the array.
This version is much more efficient than RemoveAt (O(Count) instead of O(ArrayNum)), but does not preserve the order.
Parameters
Index Location in array of the element to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 302 of file IndirectArray.h.
Referenced by TIndirectArray< FChunk, AllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
RemoveAtSwap() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::RemoveAtSwap (int32 Index, int32 Count, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes elements at given location optionally shrinking the array.
This version is much more efficient than RemoveAt (O(Count) instead of O(ArrayNum)), but does not preserve the order.
Parameters
Index Location in array of the rirst element to remove.
Count Number of elements to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 323 of file IndirectArray.h.
Reserve()
template<typename T, typename Allocator = FDefaultAllocator> FORCEINLINE void TIndirectArray< T, Allocator >::Reserve (int32 Number) inline
Reserves memory such that the array can contain at least Number elements.
Parameters
Number The number of elements that the array should be able to contain after allocation.
Definition at line 396 of file IndirectArray.h.
Reset()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::Reset (int32 NewSize = 0) inline
Resets the array to the new given size.
It calls the destructors on held items.
Parameters
NewSize (Optional) The expected usage size after calling this function. Default is 0.
Definition at line 193 of file IndirectArray.h.
Serialize()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::Serialize (FArchive & Ar, UObject * Owner) inline
Special serialize function passing the owning UObject along as required by FUnytpedBulkData serialization.
Parameters
Ar Archive to serialize with.
Owner UObject this structure is serialized within.
Definition at line 206 of file IndirectArray.h.
Shrink()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::Shrink () inline
Shrinks the array's used memory to smallest possible to store elements currently in it.
Definition at line 181 of file IndirectArray.h.
Swap()
template<typename T, typename Allocator = FDefaultAllocator> void TIndirectArray< T, Allocator >::Swap (int32 FirstIndexToSwap, int32 SecondIndexToSwap) inline
Element-wise array element swap.
This version is doing more sanity checks than SwapMemory.
Parameters
FirstIndexToSwap Position of the first element to swap.
SecondIndexToSwap Position of the second element to swap.
Definition at line 350 of file IndirectArray.h.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/2]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/2]
template<typename T, typename Allocator = FDefaultAllocator> TIndirectArray< T, Allocator >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap")
Field Documentation
Array
template<typename T, typename Allocator = FDefaultAllocator> InternalArrayType TIndirectArray< T, Allocator >::Array private
Definition at line 474 of file IndirectArray.h.
bAllowShrinking
template<typename T, typename Allocator = FDefaultAllocator> int32 bool TIndirectArray< T, Allocator >::bAllowShrinking
Initial value:
{
        RemoveAt(Index, Count, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 286 of file IndirectArray.h.
Count
template<typename T, typename Allocator = FDefaultAllocator> int32 TIndirectArray< T, Allocator >::Count
Definition at line 286 of file IndirectArray.h.
The documentation for this class was generated from the following file:
IndirectArray.h