Unreal Engine 5.6 C++ API: UE::Geometry::TOrientedBox3< RealType > Struct Template Reference
UE::Geometry::TOrientedBox3< RealType > Struct Template Reference
TOrientedBox3 is a non-axis-aligned 3D box defined by a 3D frame and extents along the axes of that frame The frame is at the center of the box.
#include "OrientedBoxTypes.h"
Public Member Functions
TOrientedBox3 ()
TOrientedBox3 (const TAxisAlignedBox3< RealType > &AxisBox)
Create oriented box from axis-aligned box.
TOrientedBox3 (const TFrame3< RealType > &FrameIn, const TVector< RealType > &ExtentsIn)
Create oriented box with given Frame and Extents.
TOrientedBox3 (const TVector< RealType > &Origin, const TVector< RealType > &ExtentsIn)
Create axis-aligned box with given Origin and Extents.
TVector< RealType > AxisX () const
TVector< RealType > AxisY () const
TVector< RealType > AxisZ () const
TVector< RealType > Center () const
TVector< RealType > ClosestPoint (const TVector< RealType > &Point) const
Find closest point on box.
bool Contains (const TVector< RealType > &Point) const
TVector< RealType > Diagonal () const
RealType DistanceSquared (TVector< RealType > Point) const
Find squared distance to box.
template<typename PointFuncType>
void EnumerateCorners (PointFuncType CornerPointFunc) const
Call CornerPointFunc(FVector3) for each of the 8 box corners.
TVector< RealType > GetAxis (int AxisIndex) const
TVector< RealType > GetCorner (int Index) const
TOrientedBox3< RealType > Merge (const TOrientedBox3< RealType > &Other, bool bOnlyConsiderExistingAxes=false) const
RealType SignedDistance (TVector< RealType > Point) const
Find signed distance to box surface.
RealType SurfaceArea () const
template<typename PointPredicateType>
bool TestCorners (PointPredicateType CornerPointPredicate) const
Call CornerPointPredicate(FVector3) for each of the 8 box corners, with early-out if any call returns false.
RealType Volume () const
Static Public Member Functions
static FIndex3i GetCornerSide (int Index)
Get whether the corner at Index (see diagram in GetCorner documentation comment) is in the negative or positive direction for each axis.
static TOrientedBox3< RealType > UnitPositive ()
static TOrientedBox3< RealType > UnitZeroCentered ()
Data Fields
TVector< RealType > Extents
Half-dimensions of box measured along the three axes.
TFrame3< RealType > Frame
3D position (center) and orientation (axes) of the box
Detailed Description
template<typename RealType>
struct UE::Geometry::TOrientedBox3< RealType >
TOrientedBox3 is a non-axis-aligned 3D box defined by a 3D frame and extents along the axes of that frame The frame is at the center of the box.
Definition at line 23 of file OrientedBoxTypes.h.
Constructor & Destructor Documentation
TOrientedBox3() [1/4]
template<typename RealType> UE::Geometry::TOrientedBox3< RealType >::TOrientedBox3 () inline
Definition at line 33 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::TOrientedBox3< float >::UnitPositive(), and UE::Geometry::TOrientedBox3< float >::UnitZeroCentered().
TOrientedBox3() [2/4]
template<typename RealType> UE::Geometry::TOrientedBox3< RealType >::TOrientedBox3 (const TVector< RealType > & Origin, const TVector< RealType > & ExtentsIn) inline
Create axis-aligned box with given Origin and Extents.
Definition at line 38 of file OrientedBoxTypes.h.
TOrientedBox3() [3/4]
template<typename RealType> UE::Geometry::TOrientedBox3< RealType >::TOrientedBox3 (const TFrame3< RealType > & FrameIn, const TVector< RealType > & ExtentsIn) inline
Create oriented box with given Frame and Extents.
Definition at line 46 of file OrientedBoxTypes.h.
TOrientedBox3() [4/4]
template<typename RealType> UE::Geometry::TOrientedBox3< RealType >::TOrientedBox3 (const TAxisAlignedBox3< RealType > & AxisBox) inline
Create oriented box from axis-aligned box.
Definition at line 54 of file OrientedBoxTypes.h.
Member Function Documentation
AxisX()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::AxisX () const inline
Returns
X axis of the box
Definition at line 71 of file OrientedBoxTypes.h.
AxisY()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::AxisY () const inline
Returns
Y axis of the box
Definition at line 74 of file OrientedBoxTypes.h.
AxisZ()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::AxisZ () const inline
Returns
Z axis of the box
Definition at line 77 of file OrientedBoxTypes.h.
Center()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::Center () const inline
Returns
center of the box
Definition at line 68 of file OrientedBoxTypes.h.
ClosestPoint()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::ClosestPoint (const TVector< RealType > & Point) const inline
Find closest point on box.
Parameters
Point input point
Returns
Closest point on box. Input point is returned if it is inside box.
Definition at line 242 of file OrientedBoxTypes.h.
Contains()
template<typename RealType> bool UE::Geometry::TOrientedBox3< RealType >::Contains (const TVector< RealType > & Point) const inline
Returns
true if box contains point
Definition at line 102 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::IsInside().
Diagonal()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::Diagonal () const inline
Returns
vector from minimum-corner to maximum-corner of box
Definition at line 83 of file OrientedBoxTypes.h.
DistanceSquared()
template<typename RealType> RealType UE::Geometry::TOrientedBox3< RealType >::DistanceSquared (TVector< RealType > Point) const inline
Find squared distance to box.
Parameters
Point input point
Returns
Squared distance from point to box, or 0 if point is inside box
Definition at line 199 of file OrientedBoxTypes.h.
EnumerateCorners()
template<typename RealType> template<typename PointFuncType> void UE::Geometry::TOrientedBox3< RealType >::EnumerateCorners (PointFuncType CornerPointFunc) const inline
Call CornerPointFunc(FVector3) for each of the 8 box corners.
Order is the same as GetCorner(X). This is more efficient than calling GetCorner(X) because the Rotation matrix is only computed once.
Definition at line 141 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::IsInside().
GetAxis()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::GetAxis (int AxisIndex) const inline
Returns
an axis of the box
Definition at line 80 of file OrientedBoxTypes.h.
GetCorner()
template<typename RealType> TVector< RealType > UE::Geometry::TOrientedBox3< RealType >::GetCorner (int Index) const inline
Parameters
Index corner index in range 0-7
Returns
Corner point on the box identified by the given index. See diagram in OrientedBoxTypes.h for index/corner mapping.
Definition at line 127 of file OrientedBoxTypes.h.
GetCornerSide()
template<typename RealType> FIndex3i UE::Geometry::TOrientedBox3< RealType >::GetCornerSide (int Index) inline static
Get whether the corner at Index (see diagram in GetCorner documentation comment) is in the negative or positive direction for each axis.
Parameters
Index corner index in range 0-7
Returns
Index3i with 0 or 1 for each axis, 0 if corner is in the negative direction for that axis, 1 if in the positive direction
Definition at line 182 of file OrientedBoxTypes.h.
Merge()
template<typename RealType> TOrientedBox3< RealType > UE::Geometry::TOrientedBox3< RealType >::Merge (const TOrientedBox3< RealType > & Other, bool bOnlyConsiderExistingAxes = false) const inline
Definition at line 261 of file OrientedBoxTypes.h.
SignedDistance()
template<typename RealType> RealType UE::Geometry::TOrientedBox3< RealType >::SignedDistance (TVector< RealType > Point) const inline
Find signed distance to box surface.
Parameters
Point input point
Returns
Signed distance from point to box surface; negative if point is inside box
Definition at line 215 of file OrientedBoxTypes.h.
SurfaceArea()
template<typename RealType> RealType UE::Geometry::TOrientedBox3< RealType >::SurfaceArea () const inline
Returns
surface area of box
Definition at line 95 of file OrientedBoxTypes.h.
TestCorners()
template<typename RealType> template<typename PointPredicateType> bool UE::Geometry::TOrientedBox3< RealType >::TestCorners (PointPredicateType CornerPointPredicate) const inline
Call CornerPointPredicate(FVector3) for each of the 8 box corners, with early-out if any call returns false.
Returns
true if all tests pass
Definition at line 161 of file OrientedBoxTypes.h.
UnitPositive()
template<typename RealType> TOrientedBox3< RealType > UE::Geometry::TOrientedBox3< RealType >::UnitPositive () inline static
Returns
box with unit dimensions where minimum corner is at origin
Definition at line 64 of file OrientedBoxTypes.h.
UnitZeroCentered()
template<typename RealType> TOrientedBox3< RealType > UE::Geometry::TOrientedBox3< RealType >::UnitZeroCentered () inline static
Returns
box with unit dimensions centered at origin
Definition at line 61 of file OrientedBoxTypes.h.
Volume()
template<typename RealType> RealType UE::Geometry::TOrientedBox3< RealType >::Volume () const inline
Returns
volume of box
Definition at line 89 of file OrientedBoxTypes.h.
Field Documentation
Extents
template<typename RealType> TVector<RealType> UE::Geometry::TOrientedBox3< RealType >::Extents
Half-dimensions of box measured along the three axes.
Definition at line 31 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::GetShape().
Frame
template<typename RealType> TFrame3<RealType> UE::Geometry::TOrientedBox3< RealType >::Frame
3D position (center) and orientation (axes) of the box
Definition at line 29 of file OrientedBoxTypes.h.
Referenced by UE::Geometry::GetShape().
The documentation for this struct was generated from the following files:
IntersectionQueries3.h
OrientedBoxTypes.h