Unreal Engine 5.6 C++ API: Verse::TNativeTuple< Type, RestTypes... > Struct Template Reference
Verse::TNativeTuple< Type, RestTypes... > Struct Template Reference
#include "VVMNativeTuple.h"
Public Member Functions
TNativeTuple ()=default
template<typename OtherType, typename... OtherRestTypes, typename = typename TEnableIf<sizeof...(RestTypes) == sizeof...(OtherRestTypes)>::Type>
TNativeTuple (const TNativeTuple< OtherType, OtherRestTypes... > &Other)
TNativeTuple (const Type &Arg, const RestTypes &... Args)
template<typename TArg, typename... TArgs, typename = typename TEnableIf<sizeof...(RestTypes) == sizeof...(TArgs)>::Type>
TNativeTuple (TArg &&Arg, TArgs &&... Args)
template<size_t Idx>
constexpr auto & Get ()
template<size_t Idx>
constexpr const auto & Get () const
Data Fields
Type First
TNativeTuple< RestTypes... > Rest
Friends
bool operator!= (const TNativeTuple< Type, RestTypes... > &Lhs, const TNativeTuple< Type, RestTypes... > &Rhs)
bool operator== (const TNativeTuple< Type, RestTypes... > &Lhs, const TNativeTuple< Type, RestTypes... > &Rhs)
Detailed Description
template<typename Type, typename... RestTypes>
struct Verse::TNativeTuple< Type, RestTypes... >
Definition at line 101 of file VVMNativeTuple.h.
Constructor & Destructor Documentation
TNativeTuple() [1/4]
template<typename Type, typename... RestTypes> Verse::TNativeTuple< Type, RestTypes... >::TNativeTuple () default
Referenced by TNativeTuple(), Get(), Get(), operator!=, and operator==.
TNativeTuple() [2/4]
template<typename Type, typename... RestTypes> Verse::TNativeTuple< Type, RestTypes... >::TNativeTuple (const Type & Arg, const RestTypes &... Args) inline
Definition at line 111 of file VVMNativeTuple.h.
References First, Rest, and Verse::Type.
TNativeTuple() [3/4]
template<typename Type, typename... RestTypes> template<typename TArg, typename... TArgs, typename = typename TEnableIf<sizeof...(RestTypes) == sizeof...(TArgs)>::Type> Verse::TNativeTuple< Type, RestTypes... >::TNativeTuple (TArg && Arg, TArgs &&... Args) inline
Definition at line 118 of file VVMNativeTuple.h.
References First, Forward(), and Rest.
TNativeTuple() [4/4]
template<typename Type, typename... RestTypes> template<typename OtherType, typename... OtherRestTypes, typename = typename TEnableIf<sizeof...(RestTypes) == sizeof...(OtherRestTypes)>::Type> Verse::TNativeTuple< Type, RestTypes... >::TNativeTuple (const TNativeTuple< OtherType, OtherRestTypes... > & Other) inline
Definition at line 125 of file VVMNativeTuple.h.
References TNativeTuple(), First, Other, and Rest.
Member Function Documentation
Get() [1/2]
template<typename Type, typename... RestTypes> template<size_t Idx> auto & Verse::TNativeTuple< Type, RestTypes... >::Get () inline constexpr
Definition at line 134 of file VVMNativeTuple.h.
References TNativeTuple(), Get(), and Verse::Type.
Referenced by Get(), and Get().
Get() [2/2]
template<typename Type, typename... RestTypes> template<size_t Idx> const auto & Verse::TNativeTuple< Type, RestTypes... >::Get () const inline constexpr
Definition at line 142 of file VVMNativeTuple.h.
References TNativeTuple(), Get(), and Verse::Type.
Friends And Related Symbol Documentation
operator!=
template<typename Type, typename... RestTypes> bool operator!= (const TNativeTuple< Type, RestTypes... > & Lhs, const TNativeTuple< Type, RestTypes... > & Rhs) friend
Definition at line 151 of file VVMNativeTuple.h.
References TNativeTuple().
operator==
template<typename Type, typename... RestTypes> bool operator== (const TNativeTuple< Type, RestTypes... > & Lhs, const TNativeTuple< Type, RestTypes... > & Rhs) friend
Definition at line 147 of file VVMNativeTuple.h.
References TNativeTuple().
Field Documentation
First
template<typename Type, typename... RestTypes> Type Verse::TNativeTuple< Type, RestTypes... >::First
Definition at line 106 of file VVMNativeTuple.h.
Referenced by TNativeTuple(), TNativeTuple(), and TNativeTuple().
Rest
template<typename Type, typename... RestTypes> TNativeTuple<RestTypes...> Verse::TNativeTuple< Type, RestTypes... >::Rest
Definition at line 107 of file VVMNativeTuple.h.
Referenced by TNativeTuple(), TNativeTuple(), and TNativeTuple().
The documentation for this struct was generated from the following file:
VVMNativeTuple.h