Unreal Engine 5.6 C++ API: UE::Net::TNetControlMessageImpl< Index, ParamTypes > Class Template Reference
UE::Net::TNetControlMessageImpl< Index, ParamTypes > Class Template Reference
#include "DataChannel.h"
Static Public Member Functions
static void Discard (FInBunch &Bunch)
throws away a message of this type from the passed in bunch
static uint8 Initialize (const TCHAR *InName)
static bool Receive (FInBunch &Bunch, ParamTypes &... Params)
receives a message of this type from the passed in bunch
static void Send (UNetConnection *Conn, ParamTypes &... Params)
sends a message of this type on the specified connection's control channel
Detailed Description
template<int32 Index, typename... ParamTypes>
class UE::Net::TNetControlMessageImpl< Index, ParamTypes >
Definition at line 106 of file DataChannel.h.
Member Function Documentation
Discard()
template<int32 Index, typename... ParamTypes> void UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Discard (FInBunch & Bunch) inline static
throws away a message of this type from the passed in bunch
Definition at line 141 of file DataChannel.h.
References Params, and VisitTupleElements().
Initialize()
template<int32 Index, typename... ParamTypes> uint8 UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Initialize (const TCHAR * InName) inline static
Definition at line 109 of file DataChannel.h.
References InName, and FNetControlMessageInfo::SetName().
Receive()
template<int32 Index, typename... ParamTypes> bool UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Receive (FInBunch & Bunch, ParamTypes &... Params) inline static nodiscard
receives a message of this type from the passed in bunch
Definition at line 134 of file DataChannel.h.
References FArchive::IsError(), Params, and FNetControlMessageInfo::ReceiveParams().
Send()
template<int32 Index, typename... ParamTypes> void UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Send (UNetConnection * Conn, ParamTypes &... Params) inline static
sends a message of this type on the specified connection's control channel
Note
: const not used only because of the FArchive interface; the parameters are not modified
control channel messages can only be sent on the parent connection
Definition at line 119 of file DataChannel.h.
References checkSlow, FNetControlMessageInfo::MaxNames, Params, and FNetControlMessageInfo::SendParams().
The documentation for this class was generated from the following file:
DataChannel.h