Unreal Engine 5.6 C++ API: CompositeFont.h File Reference
CompositeFont.h File Reference
#include "CoreMinimal.h"
#include "Fonts/FontRasterizationMode.h"
#include "UObject/ObjectMacros.h"
#include "UObject/GCObject.h"
#include "UObject/Class.h"
#include "CompositeFont.generated.h"
Data Structures
struct FFontFaceData
Raw font data for a Font Face asset.
struct FFontRasterizationSettings
Font face rasterization settings.
struct FStandaloneCompositeFont
A version of FCompositeFont that should be used when it's not being embedded within another UObject This derives from FGCObject to ensure that the bulk data objects are referenced correctly.
struct TStructOpsTypeTraits< FFontData >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Slate
Typedefs
typedef TSharedPtr< const FFontFaceData, ESPMode::ThreadSafe > FFontFaceDataConstPtr
typedef TSharedRef< const FFontFaceData, ESPMode::ThreadSafe > FFontFaceDataConstRef
typedef TSharedRef< FFontFaceData, ESPMode::ThreadSafe > FFontFaceDataRef
Functions
USTRUCT () struct FFontData
Payload data describing an individual font in a typeface.
Variables
UENUM() enum class EFontHinting UENUM() enum class EFontLoadingPolicy UENUM() enum class EFontLayoutMethod typedef TSharedPtr< FFontFaceData, ESPMode::ThreadSafe > FFontFaceDataPtr
Typedef Documentation
FFontFaceDataConstPtr
typedef TSharedPtr<const FFontFaceData, ESPMode::ThreadSafe> FFontFaceDataConstPtr
Definition at line 60 of file CompositeFont.h.
FFontFaceDataConstRef
typedef TSharedRef<const FFontFaceData, ESPMode::ThreadSafe> FFontFaceDataConstRef
Definition at line 61 of file CompositeFont.h.
FFontFaceDataRef
typedef TSharedRef<FFontFaceData, ESPMode::ThreadSafe> FFontFaceDataRef
Definition at line 59 of file CompositeFont.h.
Function Documentation
USTRUCT()
USTRUCT ()
Payload data describing an individual font in a typeface.
Definition for a typeface (a family of fonts)
A single entry in a typeface.
Keep this lean as it's also used as a key!
Default constructor
Construct the raw data from a font face asset
Construct the raw data from a filename and the font data attributes
Is this font data set to a font? (either by filename or by inline data)
Get the filename of the font to use. This may not actually exist on disk in editor builds and we should load the face buffer instead.
Get the hinting algorithm to use with the font.
Get the enum controlling how this font should be loaded at runtime.
Get the index of the sub-face that should be used.
Set the index of the sub-face that should be used.
Get the method to use when laying out the font?
Returns true if the ascend is overridden.
Returns the overridden value of the ascend. This value will be used only if IsAscendOverridden returns true.
Returns true if the descend is overridden.
Returns the overridden value of the descend. This value will be used only if IsDescendOverridden returns true.
Gets the percentage of the font height that's used as the height of the strike brush.
Get the data buffer containing the data for the current font face.
Get the font face asset used by this data (if any).
Get the font face rasterization settings.
Check to see whether this font data is equal to the other font data
Check to see whether this font data is not equal to the other font data
Get the type hash for this font data
Handle serialization for this struct.
Called by FStandaloneCompositeFont to prevent our objects from being GCd
The filename of the font to use. This variable is ignored if we have a font face asset, and is set to the .ufont file in a cooked build.
Cached hash value of FontFilename. Must be updated everytime FontFilename changes.
The hinting algorithm to use with the font. This variable is ignored if we have a font face asset, and is synchronized with the font face asset on load in a cooked build.
Enum controlling how this font should be loaded at runtime. See the enum for more explanations of the options. This variable is ignored if we have a font face asset, and is synchronized with the font face asset on load in a cooked build.
The index of the sub-face that should be used. This is typically zero unless using a TTC/OTC font.
Font data v3. This points to a font face asset.
Default constructor
Construct the entry from a name
Construct the entry from a filename and the font data attributes
Name used to identify this font within its typeface
Raw font data for this font
Default constructor
Convenience constructor for when your font family only contains a single font
Append a new font into this family
The fonts contained within this family
Default constructor
Typeface data for this sub-font
Amount to scale this sub-font so that it better matches the size of the default font
Default constructor
Convenience constructor for when your composite font only contains a single font
The default typeface that will be used when not overridden by a sub-typeface
The fallback typeface that will be used as a last resort when no other typeface provides a match
Sub-typefaces to use for a specific set of characters
If set to false, the ascent and descent override specified in a Font face will be ignored, and the value from the font source file will be used instead.
Returns the enabled state of ascent and descent override.
Definition at line 143 of file CompositeFont.h.
References Ar, GENERATED_USTRUCT_BODY, GetTypeHash(), HashCombine(), InOuter, Key, operator!=(), operator<<(), operator==(), Other, FArchive::Serialize(), and UPROPERTY.
Variable Documentation
FFontFaceDataPtr
UENUM () enum class EFontHinting UENUM () enum class EFontLoadingPolicy UENUM () enum class EFontLayoutMethod typedef TSharedPtr<FFontFaceData, ESPMode::ThreadSafe> FFontFaceDataPtr ()
Definition at line 58 of file CompositeFont.h.