Unreal Engine 5.6 C++ API: FRotationConversionCache Struct Reference
FRotationConversionCache Struct Reference
Struct for caching Quat<->Rotator conversions.
#include "EngineTypes.h"
Data Structures
struct FPayload
Public Member Functions
FRotationConversionCache ()
FORCEINLINE_DEBUGGABLE FQuat GetCachedQuat () const
Return the cached Quat.
FORCEINLINE_DEBUGGABLE FRotator GetCachedRotator () const
Return the cached Rotator.
FORCEINLINE_DEBUGGABLE FRotator NormalizedQuatToRotator (const FQuat &InNormalizedQuat) const
Version of QuatToRotator when the Quat is known to already be normalized.
FORCEINLINE_DEBUGGABLE FRotator NormalizedQuatToRotator_ReadOnly (const FQuat &InNormalizedQuat) const
Version of QuatToRotator when the Quat is known to already be normalized.
FRotationConversionCache & operator= (const FRotationConversionCache &Other)
FORCEINLINE_DEBUGGABLE FRotator QuatToRotator (const FQuat &InQuat) const
Convert a FQuat to FRotator.
FORCEINLINE_DEBUGGABLE FRotator QuatToRotator_ReadOnly (const FQuat &InQuat) const
Convert a FQuat to FRotator.
FORCEINLINE_DEBUGGABLE FQuat RotatorToQuat (const FRotator &InRotator) const
Convert a FRotator to FQuat.
FORCEINLINE_DEBUGGABLE FQuat RotatorToQuat_ReadOnly (const FRotator &InRotator) const
Convert a FRotator to FQuat.
Private Member Functions
FPayload & GetOrCreatePayload () const
Private Attributes
TUniquePtr< FPayload > PayloadPtr
Detailed Description
Struct for caching Quat<->Rotator conversions.
Definition at line 1915 of file EngineTypes.h.
Constructor & Destructor Documentation
FRotationConversionCache()
FRotationConversionCache::FRotationConversionCache () inline
Definition at line 1917 of file EngineTypes.h.
Referenced by operator=().
Member Function Documentation
GetCachedQuat()
FORCEINLINE_DEBUGGABLE FQuat FRotationConversionCache::GetCachedQuat () const inline
Return the cached Quat.
Definition at line 2000 of file EngineTypes.h.
References FORCEINLINE_DEBUGGABLE, UE::Math::TQuat< double >::Identity, PayloadPtr, and UNLIKELY.
GetCachedRotator()
FORCEINLINE_DEBUGGABLE FRotator FRotationConversionCache::GetCachedRotator () const inline
Return the cached Rotator.
Definition at line 2010 of file EngineTypes.h.
References FORCEINLINE_DEBUGGABLE, PayloadPtr, UNLIKELY, and UE::Math::TRotator< double >::ZeroRotator.
GetOrCreatePayload()
FPayload & FRotationConversionCache::GetOrCreatePayload () const inline private
Definition at line 2043 of file EngineTypes.h.
References MakeUnique(), PayloadPtr, and UNLIKELY.
Referenced by NormalizedQuatToRotator(), operator=(), QuatToRotator(), and RotatorToQuat().
NormalizedQuatToRotator()
FORCEINLINE_DEBUGGABLE FRotator FRotationConversionCache::NormalizedQuatToRotator (const FQuat & InNormalizedQuat) const inline
Version of QuatToRotator when the Quat is known to already be normalized.
Definition at line 1974 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, GetOrCreatePayload(), LIKELY, and UE::Math::TQuat< T >::Rotator().
NormalizedQuatToRotator_ReadOnly()
FORCEINLINE_DEBUGGABLE FRotator FRotationConversionCache::NormalizedQuatToRotator_ReadOnly (const FQuat & InNormalizedQuat) const inline
Version of QuatToRotator when the Quat is known to already be normalized.
Does NOT update the cache if there was no match.
Definition at line 1986 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, LIKELY, PayloadPtr, and UE::Math::TQuat< T >::Rotator().
operator=()
FRotationConversionCache & FRotationConversionCache::operator= (const FRotationConversionCache & Other) inline
Definition at line 2019 of file EngineTypes.h.
References FRotationConversionCache(), FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, GetOrCreatePayload(), LIKELY, Other, and PayloadPtr.
QuatToRotator()
FORCEINLINE_DEBUGGABLE FRotator FRotationConversionCache::QuatToRotator (const FQuat & InQuat) const inline
Convert a FQuat to FRotator.
Uses the cached conversion if possible, and updates it if there was no match.
Definition at line 1948 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, UE::Math::TQuat< T >::GetNormalized(), GetOrCreatePayload(), LIKELY, and UE::Math::TQuat< T >::Rotator().
QuatToRotator_ReadOnly()
FORCEINLINE_DEBUGGABLE FRotator FRotationConversionCache::QuatToRotator_ReadOnly (const FQuat & InQuat) const inline
Convert a FQuat to FRotator.
Uses the cached conversion if possible, but does NOT update the cache if there was no match.
Definition at line 1960 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, UE::Math::TQuat< T >::GetNormalized(), LIKELY, PayloadPtr, and UE::Math::TQuat< T >::Rotator().
RotatorToQuat()
FORCEINLINE_DEBUGGABLE FQuat FRotationConversionCache::RotatorToQuat (const FRotator & InRotator) const inline
Convert a FRotator to FQuat.
Uses the cached conversion if possible, and updates it if there was no match.
Definition at line 1922 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, UE::Math::TRotator< T >::GetNormalized(), GetOrCreatePayload(), LIKELY, and UE::Math::TRotator< T >::Quaternion().
RotatorToQuat_ReadOnly()
FORCEINLINE_DEBUGGABLE FQuat FRotationConversionCache::RotatorToQuat_ReadOnly (const FRotator & InRotator) const inline
Convert a FRotator to FQuat.
Uses the cached conversion if possible, but does NOT update the cache if there was no match.
Definition at line 1934 of file EngineTypes.h.
References FRotationConversionCache::FPayload::CachedQuat, FRotationConversionCache::FPayload::CachedRotator, FORCEINLINE_DEBUGGABLE, LIKELY, PayloadPtr, and UE::Math::TRotator< T >::Quaternion().
Field Documentation
PayloadPtr
TUniquePtr<FPayload> FRotationConversionCache::PayloadPtr mutable private
Definition at line 2052 of file EngineTypes.h.
Referenced by GetCachedQuat(), GetCachedRotator(), GetOrCreatePayload(), NormalizedQuatToRotator_ReadOnly(), operator=(), QuatToRotator_ReadOnly(), and RotatorToQuat_ReadOnly().
The documentation for this struct was generated from the following file:
EngineTypes.h