Unreal Engine 5.6 C++ API: UE::Dataflow::FDataflowToolRegistry Class Reference
UE::Dataflow::FDataflowToolRegistry Class Reference
#include "DataflowToolRegistry.h"
Data Structures
struct FToolInfo
class IDataflowToolActionCommands
Public Member Functions
void AddNodeToToolMapping (const FName &NodeName, TObjectPtr< UInteractiveToolBuilder > ToolBuilder, const TSharedRef< const IDataflowToolActionCommands > &ToolActionCommands, const FSlateIcon &AddNodeButtonIcon, const FText &AddNodeButtonText, const FName &ToolCategory=FName("General"))
void BindCommandsForCurrentTool (const TSharedPtr< FUICommandList > &UICommandList, UInteractiveTool *Tool) const
const FSlateIcon & GetAddNodeButtonIcon (const FName &NodeType) const
const FText & GetAddNodeButtonText (const FName &NodeType) const
TSharedPtr< FUICommandInfo > & GetAddNodeCommandForNode (const FName &NodeType)
TArray< FName > GetNodeNames () const
UInteractiveToolBuilder * GetToolBuilderForNode (const FName &NodeName)
const UInteractiveToolBuilder * GetToolBuilderForNode (const FName &NodeName) const
const FName & GetToolCategoryForNode (const FName &NodeName)
Return the category the tool has been registered in.
TSharedPtr< FUICommandInfo > & GetToolCommandForNode (const FName &NodeName)
void RemoveNodeToToolMapping (const FName &NodeName)
UE_DEPRECATED (5.6, "Please use the version of AddNodeToToolMapping taking AddNodeButtonIcon and AddNodeButtonText") void AddNodeToToolMapping(const FName &NodeName
void UnbindActiveCommands (const TSharedPtr< FUICommandList > &UICommandList) const
Static Public Member Functions
static FDataflowToolRegistry & Get ()
static void TearDown ()
Data Fields
TObjectPtr< UInteractiveToolBuilder > const TSharedRef< const IDataflowToolActionCommands > & ToolActionCommands
TObjectPtr< UInteractiveToolBuilder > ToolBuilder
Private Attributes
TMap< FName, FToolInfo > NodeTypeToToolMap
Detailed Description
Definition at line 17 of file DataflowToolRegistry.h.
Member Function Documentation
AddNodeToToolMapping()
void UE::Dataflow::FDataflowToolRegistry::AddNodeToToolMapping (const FName & NodeName, TObjectPtr< UInteractiveToolBuilder > ToolBuilder, const TSharedRef< const IDataflowToolActionCommands > & ToolActionCommands, const FSlateIcon & AddNodeButtonIcon, const FText & AddNodeButtonText, const FName & ToolCategory = FName("General"))
References ToolActionCommands, and ToolBuilder.
Referenced by UE_DEPRECATED().
BindCommandsForCurrentTool()
void UE::Dataflow::FDataflowToolRegistry::BindCommandsForCurrentTool (const TSharedPtr< FUICommandList > & UICommandList, UInteractiveTool * Tool) const
References BindCommandsForCurrentTool().
Referenced by BindCommandsForCurrentTool().
Get()
FDataflowToolRegistry & UE::Dataflow::FDataflowToolRegistry::Get () static
GetAddNodeButtonIcon()
const FSlateIcon & UE::Dataflow::FDataflowToolRegistry::GetAddNodeButtonIcon (const FName & NodeType) const
References GetAddNodeButtonIcon().
Referenced by GetAddNodeButtonIcon().
GetAddNodeButtonText()
const FText & UE::Dataflow::FDataflowToolRegistry::GetAddNodeButtonText (const FName & NodeType) const
References GetAddNodeButtonText().
Referenced by GetAddNodeButtonText().
GetAddNodeCommandForNode()
TSharedPtr< FUICommandInfo > & UE::Dataflow::FDataflowToolRegistry::GetAddNodeCommandForNode (const FName & NodeType)
References GetAddNodeCommandForNode().
Referenced by GetAddNodeCommandForNode().
GetNodeNames()
TArray< FName > UE::Dataflow::FDataflowToolRegistry::GetNodeNames () const
References GetNodeNames().
Referenced by GetNodeNames().
GetToolBuilderForNode() [1/2]
UInteractiveToolBuilder * UE::Dataflow::FDataflowToolRegistry::GetToolBuilderForNode (const FName & NodeName)
References GetToolBuilderForNode().
Referenced by GetToolBuilderForNode(), and GetToolBuilderForNode().
GetToolBuilderForNode() [2/2]
const UInteractiveToolBuilder * UE::Dataflow::FDataflowToolRegistry::GetToolBuilderForNode (const FName & NodeName) const
References GetToolBuilderForNode().
GetToolCategoryForNode()
const FName & UE::Dataflow::FDataflowToolRegistry::GetToolCategoryForNode (const FName & NodeName)
Return the category the tool has been registered in.
References GetToolCategoryForNode().
Referenced by GetToolCategoryForNode().
GetToolCommandForNode()
TSharedPtr< FUICommandInfo > & UE::Dataflow::FDataflowToolRegistry::GetToolCommandForNode (const FName & NodeName)
References GetToolCommandForNode().
Referenced by GetToolCommandForNode().
RemoveNodeToToolMapping()
void UE::Dataflow::FDataflowToolRegistry::RemoveNodeToToolMapping (const FName & NodeName)
References RemoveNodeToToolMapping().
Referenced by RemoveNodeToToolMapping().
TearDown()
void UE::Dataflow::FDataflowToolRegistry::TearDown () static
UE_DEPRECATED()
UE::Dataflow::FDataflowToolRegistry::UE_DEPRECATED (5. 6, "Please use the version of AddNodeToToolMapping taking AddNodeButtonIcon and AddNodeButtonText") const &
References AddNodeToToolMapping().
UnbindActiveCommands()
void UE::Dataflow::FDataflowToolRegistry::UnbindActiveCommands (const TSharedPtr< FUICommandList > & UICommandList) const
References UnbindActiveCommands().
Referenced by UnbindActiveCommands().
Field Documentation
NodeTypeToToolMap
TMap<FName, FToolInfo> UE::Dataflow::FDataflowToolRegistry::NodeTypeToToolMap private
Definition at line 83 of file DataflowToolRegistry.h.
ToolActionCommands
TObjectPtr<UInteractiveToolBuilder> const TSharedRef<const IDataflowToolActionCommands>& UE::Dataflow::FDataflowToolRegistry::ToolActionCommands
Definition at line 44 of file DataflowToolRegistry.h.
Referenced by AddNodeToToolMapping().
ToolBuilder
TObjectPtr<UInteractiveToolBuilder> UE::Dataflow::FDataflowToolRegistry::ToolBuilder
Definition at line 43 of file DataflowToolRegistry.h.
Referenced by AddNodeToToolMapping().
The documentation for this class was generated from the following file:
DataflowToolRegistry.h