Unreal Engine 5.6 C++ API: UE::Tick::FBatchContextId Struct Reference
UE::Tick::FBatchContextId Struct Reference final
Identifies a specific batch of tasks, which will be associated with a set of objects in a world context.
#include "TaskSyncManager.h"
Public Types
typedef int32 FInternalId
Public Member Functions
FBatchContextId ()
Construct an invalid batch.
FBatchContextId (FInternalId InBatchId)
Construct from an internal id TODO: May make private.
bool IsValid () const
Returns true if this has been initialized to a valid batch.
bool operator!= (const FBatchContextId &Other) const
bool operator== (const FBatchContextId &Other) const
Data Fields
FInternalId BatchId
Static Public Attributes
static constexpr FInternalId InvalidBatch = -1
Friends
uint32 GetTypeHash (const FBatchContextId &Context)
Detailed Description
Identifies a specific batch of tasks, which will be associated with a set of objects in a world context.
Definition at line 295 of file TaskSyncManager.h.
Member Typedef Documentation
FInternalId
typedef int32 UE::Tick::FBatchContextId::FInternalId
Definition at line 298 of file TaskSyncManager.h.
Constructor & Destructor Documentation
FBatchContextId() [1/2]
UE::Tick::FBatchContextId::FBatchContextId () inline
Construct an invalid batch.
Definition at line 303 of file TaskSyncManager.h.
References BatchId, and InvalidBatch.
Referenced by GetTypeHash, operator!=(), and operator==().
FBatchContextId() [2/2]
UE::Tick::FBatchContextId::FBatchContextId (FInternalId InBatchId) inline explicit
Construct from an internal id TODO: May make private.
Definition at line 308 of file TaskSyncManager.h.
References BatchId.
Member Function Documentation
IsValid()
bool UE::Tick::FBatchContextId::IsValid () const inline
Returns true if this has been initialized to a valid batch.
Definition at line 313 of file TaskSyncManager.h.
References BatchId, and InvalidBatch.
operator!=()
bool UE::Tick::FBatchContextId::operator!= (const FBatchContextId & Other) const inline
Definition at line 323 of file TaskSyncManager.h.
References FBatchContextId(), and Other.
operator==()
bool UE::Tick::FBatchContextId::operator== (const FBatchContextId & Other) const inline
Definition at line 318 of file TaskSyncManager.h.
References FBatchContextId(), BatchId, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FBatchContextId & Context) friend
Definition at line 328 of file TaskSyncManager.h.
References FBatchContextId().
Field Documentation
BatchId
FInternalId UE::Tick::FBatchContextId::BatchId
Definition at line 333 of file TaskSyncManager.h.
Referenced by FBatchContextId(), FBatchContextId(), IsValid(), and operator==().
InvalidBatch
FInternalId UE::Tick::FBatchContextId::InvalidBatch = -1 static constexpr
Definition at line 300 of file TaskSyncManager.h.
Referenced by FBatchContextId(), and IsValid().
The documentation for this struct was generated from the following file:
TaskSyncManager.h