Unreal Engine 5.6 C++ API: UE::FIoBufferHandle Struct Reference
UE::FIoBufferHandle Struct Reference
#include "PlatformIoDispatcherBase.h"
Public Member Functions
FIoBufferHandle ()=default
FIoBufferHandle (int32 InHandle)
bool IsValid () const
int32 Value () const
Private Attributes
int32 Handle = INDEX_NONE
Detailed Description
Definition at line 31 of file PlatformIoDispatcherBase.h.
Constructor & Destructor Documentation
FIoBufferHandle() [1/2]
UE::FIoBufferHandle::FIoBufferHandle () default
FIoBufferHandle() [2/2]
UE::FIoBufferHandle::FIoBufferHandle (int32 InHandle) inline explicit
Definition at line 35 of file PlatformIoDispatcherBase.h.
References check, Handle, and INDEX_NONE.
Member Function Documentation
IsValid()
bool UE::FIoBufferHandle::IsValid () const inline
Definition at line 42 of file PlatformIoDispatcherBase.h.
References Handle, and INDEX_NONE.
Referenced by UE::FPlatformIoDispatcherBase::EnqueueBlockToDecode(), UE::FIoFileBlockCache::Get(), and UE::FIoFileBlockCache::Put().
Value()
int32 UE::FIoBufferHandle::Value () const inline
Definition at line 41 of file PlatformIoDispatcherBase.h.
References Handle.
Field Documentation
Handle
int32 UE::FIoBufferHandle::Handle = INDEX_NONE private
Definition at line 45 of file PlatformIoDispatcherBase.h.
Referenced by FIoBufferHandle(), IsValid(), and Value().
The documentation for this struct was generated from the following file:
PlatformIoDispatcherBase.h