Unreal Engine 5.6 C++ API: IMappedFileRegion Class Reference
IMappedFileRegion Class Reference
#include "MappedFileHandle.h"
Public Member Functions
IMappedFileRegion (const IMappedFileRegion &)=delete
FORCEINLINE IMappedFileRegion (const uint8 *InMappedPtr, size_t InMappedSize, const FString &InDebugFilename, size_t InDebugOffsetRelativeToFile)
virtual ~IMappedFileRegion ()
virtual void Flush (int64 FlushOffset=0, int64 BytesToFlush=MAX_int64)
Synchronously flush part or all of the mapped region.
FORCEINLINE const uint8 * GetMappedPtr ()
Return the pointer to the mapped region.
FORCEINLINE int64 GetMappedSize ()
Return the size of the mapped region.
IMappedFileRegion & operator= (const IMappedFileRegion &)=delete
virtual void PreloadHint (int64 PreloadOffset=0, int64 BytesToPreload=MAX_int64)
Synchronously preload part or all of the mapped region.
Private Member Functions
FORCEINLINE void CheckInvariants ()
Private Attributes
FString DebugFilename
size_t DebugOffsetRelativeToFile
const uint8 * MappedPtr
size_t MappedSize
Detailed Description
Definition at line 16 of file MappedFileHandle.h.
Constructor & Destructor Documentation
IMappedFileRegion() [1/2]
FORCEINLINE IMappedFileRegion::IMappedFileRegion (const uint8 * InMappedPtr, size_t InMappedSize, const FString & InDebugFilename, size_t InDebugOffsetRelativeToFile) inline
Definition at line 30 of file MappedFileHandle.h.
References CheckInvariants(), DebugFilename, DebugOffsetRelativeToFile, FORCEINLINE, INC_DWORD_STAT, INC_MEMORY_STAT_BY, MappedPtr, and MappedSize.
Referenced by IMappedFileRegion(), and operator=().
~IMappedFileRegion()
virtual IMappedFileRegion::~IMappedFileRegion () inline virtual
Definition at line 41 of file MappedFileHandle.h.
References check, DEC_DWORD_STAT, DEC_MEMORY_STAT_BY, and MappedSize.
IMappedFileRegion() [2/2]
IMappedFileRegion::IMappedFileRegion (const IMappedFileRegion &) delete
References IMappedFileRegion().
Member Function Documentation
CheckInvariants()
FORCEINLINE void IMappedFileRegion::CheckInvariants () inline private
Definition at line 23 of file MappedFileHandle.h.
References check, FORCEINLINE, MappedPtr, and MappedSize.
Referenced by IMappedFileRegion(), GetMappedPtr(), and GetMappedSize().
Flush()
virtual void IMappedFileRegion::Flush (int64 FlushOffset = 0, int64 BytesToFlush = MAX_int64) inline virtual
Synchronously flush part or all of the mapped region.
This is only a hint, some platforms might ignore it. There are not guarantees how long this data will stay in paged out.
Parameters
FlushOffset Offset into this region to flush
BytesToFlush number of bytes to flush. This is clamped to the size of the mapped region
Definition at line 86 of file MappedFileHandle.h.
References MAX_int64.
GetMappedPtr()
FORCEINLINE const uint8 * IMappedFileRegion::GetMappedPtr () inline
Return the pointer to the mapped region.
Returns
Returned size of the file or -1 if the file was not found, the request was canceled or other error.
Definition at line 53 of file MappedFileHandle.h.
References CheckInvariants(), FORCEINLINE, and MappedPtr.
GetMappedSize()
FORCEINLINE int64 IMappedFileRegion::GetMappedSize () inline
Return the size of the mapped region.
Definition at line 62 of file MappedFileHandle.h.
References CheckInvariants(), FORCEINLINE, and MappedSize.
operator=()
IMappedFileRegion & IMappedFileRegion::operator= (const IMappedFileRegion &) delete
References IMappedFileRegion().
PreloadHint()
virtual void IMappedFileRegion::PreloadHint (int64 PreloadOffset = 0, int64 BytesToPreload = MAX_int64) inline virtual
Synchronously preload part or all of the mapped region.
Typically this is done by reading a byte from each CPU page. This is only a hint, some platforms might ignore it. There are not guarantees how long this data will stay in memory.
Parameters
PreloadOffset Offset into this region to preload
BytesToPreload number of bytes to preload. This is clamped to the size of the mapped region
Definition at line 75 of file MappedFileHandle.h.
References MAX_int64.
Field Documentation
DebugFilename
FString IMappedFileRegion::DebugFilename private
Definition at line 20 of file MappedFileHandle.h.
Referenced by IMappedFileRegion().
DebugOffsetRelativeToFile
size_t IMappedFileRegion::DebugOffsetRelativeToFile private
Definition at line 21 of file MappedFileHandle.h.
Referenced by IMappedFileRegion().
MappedPtr
const uint8* IMappedFileRegion::MappedPtr private
Definition at line 18 of file MappedFileHandle.h.
Referenced by IMappedFileRegion(), CheckInvariants(), and GetMappedPtr().
MappedSize
size_t IMappedFileRegion::MappedSize private
Definition at line 19 of file MappedFileHandle.h.
Referenced by IMappedFileRegion(), ~IMappedFileRegion(), CheckInvariants(), and GetMappedSize().
The documentation for this class was generated from the following file:
MappedFileHandle.h