Unreal Engine 5.6 C++ API: FObjectFullNameAndThumbnail Struct Reference
FObjectFullNameAndThumbnail Struct Reference
Wraps an object's full name and thumbnail.
#include "ObjectThumbnail.h"
Public Member Functions
FObjectFullNameAndThumbnail ()
Constructor.
FObjectFullNameAndThumbnail (const FName InFullName, const FObjectThumbnail *InThumbnail)
Constructor.
void CountBytes (FArchive &Ar) const
Calculates the memory usage of this FObjectFullNameAndThumbnail.
Data Fields
int32 FileOffset
Offset in the file where the data is stored.
FName ObjectFullName
Full name of the object.
const FObjectThumbnail * ObjectThumbnail
Thumbnail data.
Friends
FArchive & operator<< (FArchive &Ar, const FObjectFullNameAndThumbnail &NameThumbPair)
FArchive & operator<< (FArchive &Ar, FObjectFullNameAndThumbnail &NameThumbPair)
I/O operator.
Detailed Description
Wraps an object's full name and thumbnail.
Definition at line 333 of file ObjectThumbnail.h.
Constructor & Destructor Documentation
FObjectFullNameAndThumbnail() [1/2]
FObjectFullNameAndThumbnail::FObjectFullNameAndThumbnail () inline
Constructor.
Definition at line 345 of file ObjectThumbnail.h.
References FileOffset, ObjectFullName, and ObjectThumbnail.
Referenced by operator<<, and operator<<.
FObjectFullNameAndThumbnail() [2/2]
FObjectFullNameAndThumbnail::FObjectFullNameAndThumbnail (const FName InFullName, const FObjectThumbnail * InThumbnail) inline
Constructor.
Definition at line 352 of file ObjectThumbnail.h.
References FileOffset, ObjectFullName, and ObjectThumbnail.
Member Function Documentation
CountBytes()
void FObjectFullNameAndThumbnail::CountBytes (FArchive & Ar) const
Calculates the memory usage of this FObjectFullNameAndThumbnail.
Parameters
Ar the FArchiveCountMem (or similar) archive that will store the results of the memory usage calculation.
References Ar.
Referenced by operator<<, and operator<<.
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, const FObjectFullNameAndThumbnail & NameThumbPair) friend
Definition at line 379 of file ObjectThumbnail.h.
References FObjectFullNameAndThumbnail(), Ar, and CountBytes().
operator<< [2/2]
FArchive & operator<< (FArchive & Ar, FObjectFullNameAndThumbnail & NameThumbPair) friend
I/O operator.
Definition at line 366 of file ObjectThumbnail.h.
References FObjectFullNameAndThumbnail(), Ar, CountBytes(), FileOffset, and ObjectFullName.
Field Documentation
FileOffset
int32 FObjectFullNameAndThumbnail::FileOffset
Offset in the file where the data is stored.
Definition at line 342 of file ObjectThumbnail.h.
Referenced by FObjectFullNameAndThumbnail(), FObjectFullNameAndThumbnail(), and operator<<.
ObjectFullName
FName FObjectFullNameAndThumbnail::ObjectFullName
Full name of the object.
Definition at line 336 of file ObjectThumbnail.h.
Referenced by FObjectFullNameAndThumbnail(), FObjectFullNameAndThumbnail(), and operator<<.
ObjectThumbnail
const FObjectThumbnail* FObjectFullNameAndThumbnail::ObjectThumbnail
Thumbnail data.
Definition at line 339 of file ObjectThumbnail.h.
Referenced by FObjectFullNameAndThumbnail(), and FObjectFullNameAndThumbnail().
The documentation for this struct was generated from the following file:
ObjectThumbnail.h