Unreal Engine 5.6 C++ API: FAssetThumbnailPool::FThumbId Struct Reference
FAssetThumbnailPool::FThumbId Struct Reference
Key for looking up thumbnails in a map.
Public Member Functions
FThumbId (FSoftObjectPath InObjectPath, uint32 InWidth, uint32 InHeight)
bool operator== (const FThumbId &Other) const
Data Fields
uint32 Height
FSoftObjectPath ObjectPath
uint32 Width
Friends
uint32 GetTypeHash (const FThumbId &Id)
Detailed Description
Key for looking up thumbnails in a map.
Definition at line 370 of file AssetThumbnail.h.
Constructor & Destructor Documentation
FThumbId()
FAssetThumbnailPool::FThumbId::FThumbId (FSoftObjectPath InObjectPath, uint32 InWidth, uint32 InHeight) inline
Definition at line 376 of file AssetThumbnail.h.
References Height, MoveTemp(), ObjectPath, and Width.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FAssetThumbnailPool::FThumbId::operator== (const FThumbId & Other) const inline
Definition at line 382 of file AssetThumbnail.h.
References FThumbId(), Height, ObjectPath, Other, and Width.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FThumbId & Id) friend
Definition at line 387 of file AssetThumbnail.h.
References FThumbId(), GetTypeHash(), Height, ObjectPath, and Width.
Field Documentation
Height
uint32 FAssetThumbnailPool::FThumbId::Height
Definition at line 374 of file AssetThumbnail.h.
Referenced by FThumbId(), GetTypeHash, and operator==().
ObjectPath
FSoftObjectPath FAssetThumbnailPool::FThumbId::ObjectPath
Definition at line 372 of file AssetThumbnail.h.
Referenced by FThumbId(), GetTypeHash, and operator==().
Width
uint32 FAssetThumbnailPool::FThumbId::Width
Definition at line 373 of file AssetThumbnail.h.
Referenced by FThumbId(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
AssetThumbnail.h