Unreal Engine 5.6 C++ API: TAwaitableTask< ReturnType > Class Template Reference
TAwaitableTask< ReturnType > Class Template Reference
#include "AwaitableTask.h"
Public Member Functions
TAwaitableTask ()
TAwaitableTask (const ThisClass &Other)
TAwaitableTask (ThisClass &&Other)
~TAwaitableTask ()
ReturnType Await ()
template<typename CallableT>
void Init (const TCHAR *DebugName, CallableT &&Callable)
template<typename CallableT>
void Init (const TCHAR *DebugName, LowLevelTasks::ETaskPriority Priority, CallableT &&Callable)
template<typename CallableT>
bool InitAndLaunch (const TCHAR *DebugName, CallableT &&Callable)
template<typename CallableT>
bool InitAndLaunch (const TCHAR *DebugName, LowLevelTasks::ETaskPriority Priority, CallableT &&Callable)
bool IsCompleted () const
bool IsLaunched () const
bool IsValid () const
ThisClass & operator= (const ThisClass &Other)
ThisClass & operator= (ThisClass &&Other)
void Reset ()
bool TryLaunch ()
Private Types
using ThisClass = TAwaitableTask<ReturnType>
template<typename R, typename C>
using TPromise = AwaitableTask_Detail::TPromise<R, C>
template<typename P>
using TPromiseVTable = AwaitableTask_Detail::TPromiseVTable<P>
template<typename R>
using TPromiseVTableBase = AwaitableTask_Detail::TPromiseVTableBase<R>
template<typename R>
using TPromiseVTableDummy = AwaitableTask_Detail::TPromiseVTableDummy<R>
Private Member Functions
template<typename PromiseType = TPromiseVTableBase<ReturnType>>
PromiseType * GetVtable ()
template<typename PromiseType = TPromiseVTableBase<ReturnType>>
const PromiseType * GetVtable () const
Private Attributes
TPromiseVTableBase< ReturnType > PromiseVTable
Detailed Description
template<typename ReturnType>
class TAwaitableTask< ReturnType >
Definition at line 370 of file AwaitableTask.h.
Member Typedef Documentation
ThisClass
template<typename ReturnType> using TAwaitableTask< ReturnType >::ThisClass = TAwaitableTask<ReturnType> private
Definition at line 384 of file AwaitableTask.h.
TPromise
template<typename ReturnType> template<typename R, typename C> using TAwaitableTask< ReturnType >::TPromise = AwaitableTask_Detail::TPromise<R, C> private
Definition at line 379 of file AwaitableTask.h.
TPromiseVTable
template<typename ReturnType> template<typename P> using TAwaitableTask< ReturnType >::TPromiseVTable = AwaitableTask_Detail::TPromiseVTable<P> private
Definition at line 382 of file AwaitableTask.h.
TPromiseVTableBase
template<typename ReturnType> template<typename R> using TAwaitableTask< ReturnType >::TPromiseVTableBase = AwaitableTask_Detail::TPromiseVTableBase<R> private
Definition at line 373 of file AwaitableTask.h.
TPromiseVTableDummy
template<typename ReturnType> template<typename R> using TAwaitableTask< ReturnType >::TPromiseVTableDummy = AwaitableTask_Detail::TPromiseVTableDummy<R> private
Definition at line 376 of file AwaitableTask.h.
Constructor & Destructor Documentation
TAwaitableTask() [1/3]
template<typename ReturnType> TAwaitableTask< ReturnType >::TAwaitableTask () inline
Definition at line 389 of file AwaitableTask.h.
References PromiseVTable.
~TAwaitableTask()
template<typename ReturnType> TAwaitableTask< ReturnType >::~TAwaitableTask () inline
Definition at line 395 of file AwaitableTask.h.
References Reset().
TAwaitableTask() [2/3]
template<typename ReturnType> TAwaitableTask< ReturnType >::TAwaitableTask (const ThisClass & Other) inline
Definition at line 400 of file AwaitableTask.h.
References GetVtable(), Other, and PromiseVTable.
TAwaitableTask() [3/3]
template<typename ReturnType> TAwaitableTask< ReturnType >::TAwaitableTask (ThisClass && Other) inline
Definition at line 406 of file AwaitableTask.h.
References MoveTemp(), Other, and PromiseVTable.
Member Function Documentation
Await()
template<typename ReturnType> ReturnType TAwaitableTask< ReturnType >::Await () inline
Definition at line 504 of file AwaitableTask.h.
References checkSlow, GetVtable(), and IsValid().
GetVtable() [1/2]
template<typename ReturnType> template<typename PromiseType = TPromiseVTableBase<ReturnType>> PromiseType * TAwaitableTask< ReturnType >::GetVtable () inline private
Definition at line 512 of file AwaitableTask.h.
References PromiseVTable, and UE_LAUNDER.
Referenced by TAwaitableTask(), Await(), InitAndLaunch(), IsCompleted(), IsLaunched(), IsValid(), operator=(), Reset(), and TryLaunch().
GetVtable() [2/2]
template<typename ReturnType> template<typename PromiseType = TPromiseVTableBase<ReturnType>> const PromiseType * TAwaitableTask< ReturnType >::GetVtable () const inline private
Definition at line 518 of file AwaitableTask.h.
References PromiseVTable, and UE_LAUNDER.
Init() [1/2]
template<typename ReturnType> template<typename CallableT> void TAwaitableTask< ReturnType >::Init (const TCHAR * DebugName, CallableT && Callable) inline
Definition at line 449 of file AwaitableTask.h.
References LowLevelTasks::Default, Forward(), and Init.
Init() [2/2]
template<typename ReturnType> template<typename CallableT> void TAwaitableTask< ReturnType >::Init (const TCHAR * DebugName, LowLevelTasks::ETaskPriority Priority, CallableT && Callable) inline
Definition at line 436 of file AwaitableTask.h.
References Forward(), PromiseVTable, Reset(), and UE::Core::Private::IsInvocable::TIsInvocableImpl< void, CallableType, ArgTypes... >::Value.
InitAndLaunch() [1/2]
template<typename ReturnType> template<typename CallableT> bool TAwaitableTask< ReturnType >::InitAndLaunch (const TCHAR * DebugName, CallableT && Callable) inline
Definition at line 472 of file AwaitableTask.h.
References LowLevelTasks::Default, Forward(), and InitAndLaunch().
InitAndLaunch() [2/2]
template<typename ReturnType> template<typename CallableT> bool TAwaitableTask< ReturnType >::InitAndLaunch (const TCHAR * DebugName, LowLevelTasks::ETaskPriority Priority, CallableT && Callable) inline
Definition at line 462 of file AwaitableTask.h.
References Forward(), GetVtable(), and Init.
Referenced by InitAndLaunch().
IsCompleted()
template<typename ReturnType> bool TAwaitableTask< ReturnType >::IsCompleted () const inline
Definition at line 496 of file AwaitableTask.h.
References GetVtable().
IsLaunched()
template<typename ReturnType> bool TAwaitableTask< ReturnType >::IsLaunched () const inline
Definition at line 484 of file AwaitableTask.h.
References GetVtable().
IsValid()
template<typename ReturnType> bool TAwaitableTask< ReturnType >::IsValid () const inline
Definition at line 490 of file AwaitableTask.h.
References GetVtable().
Referenced by Await().
operator=() [1/2]
template<typename ReturnType> ThisClass & TAwaitableTask< ReturnType >::operator= (const ThisClass & Other) inline
Definition at line 411 of file AwaitableTask.h.
References GetVtable(), Other, PromiseVTable, and Reset().
operator=() [2/2]
template<typename ReturnType> ThisClass & TAwaitableTask< ReturnType >::operator= (ThisClass && Other) inline
Definition at line 422 of file AwaitableTask.h.
References MoveTemp(), Other, PromiseVTable, and Reset().
Reset()
template<typename ReturnType> void TAwaitableTask< ReturnType >::Reset () inline
Definition at line 478 of file AwaitableTask.h.
References GetVtable().
Referenced by ~TAwaitableTask(), Init(), operator=(), and operator=().
TryLaunch()
template<typename ReturnType> bool TAwaitableTask< ReturnType >::TryLaunch () inline
Definition at line 455 of file AwaitableTask.h.
References GetVtable().
Field Documentation
PromiseVTable
template<typename ReturnType> TPromiseVTableBase<ReturnType> TAwaitableTask< ReturnType >::PromiseVTable private
Definition at line 386 of file AwaitableTask.h.
Referenced by TAwaitableTask(), TAwaitableTask(), TAwaitableTask(), GetVtable(), GetVtable(), Init(), operator=(), and operator=().
The documentation for this class was generated from the following file:
AwaitableTask.h