Unreal Engine 5.6 C++ API: UE::Geometry::TIntrTriangle3Triangle3< Real > Class Template Reference
UE::Geometry::TIntrTriangle3Triangle3< Real > Class Template Reference
Compute intersection between 3D triangles use Test() for fast boolean query, does not compute intersection info use Find() to compute full information By default fully-contained co-planar triangles are not reported as intersecting.
#include "IntrTriangle3Triangle3.h"
Public Member Functions
TIntrTriangle3Triangle3 ()
TIntrTriangle3Triangle3 (const TTriangle3< Real > &T0, const TTriangle3< Real > &T1)
TIntrTriangle3Triangle3 * Compute ()
bool Find ()
bool GetReportCoplanarIntersection () const
Real GetTolerance () const
TTriangle3< Real > GetTriangle0 () const
TTriangle3< Real > GetTriangle1 () const
void SetReportCoplanarIntersection (bool bReportCoplanarIntersectionIn)
void SetResult (bool IsIntersecting)
Store an externally-computed binary yes/no result.
void SetResult (const TVector< Real > &A, const TVector< Real > &B)
Store an externally-computed segment intersection result.
void SetResultNone ()
Store an externally-computed no-intersection result.
void SetTolerance (Real ToleranceIn)
void SetTriangle0 (const TTriangle3< Real > &Triangle0In)
void SetTriangle1 (const TTriangle3< Real > &Triangle1In)
bool Test ()
Static Public Member Functions
static bool Intersects (const TTriangle3< Real > &Triangle0, const TTriangle3< Real > &Triangle1, Real Tolerance=TMathUtil< Real >::ZeroTolerance)
static int IntersectTriangleWithCoplanarSegment (const TPlane3< Real > &plane, const TTriangle3< Real > &triangle, const TVector< Real > &end0, const TVector< Real > &end1, TVector< Real > &OutA, TVector< Real > &OutB, Real Tolerance)
Solve a common sub-problem for triangle-triangle intersection – find the sub-segment (or point) where a triangle intersects a coplanar segment.
static void ProjectOntoAxis (const TTriangle3< Real > &triangle, const TVector< Real > &axis, Real &fmin, Real &fmax)
static void TrianglePlaneRelations (const TTriangle3< Real > &triangle, const TPlane3< Real > &plane, TVector< Real > &distance, FIndex3i &sign, int &positive, int &negative, int &zero, Real Tolerance)
Data Fields
TVector< Real > Points [6]
int Quantity = 0
EIntersectionResult Result = EIntersectionResult::NotComputed
EIntersectionType Type = EIntersectionType::Empty
Protected Member Functions
bool ContainsPoint (const TTriangle3< Real > &triangle, const TPlane3< Real > &plane, const TVector< Real > &point)
bool GetCoplanarIntersection (const TPlane3< Real > &plane, const TTriangle3< Real > &tri0, const TTriangle3< Real > &tri1)
bool IntersectsSegment (const TPlane3< Real > &plane, const TTriangle3< Real > &triangle, const TVector< Real > &end0, const TVector< Real > &end1)
Protected Attributes
bool bReportCoplanarIntersection = false
Real Tolerance = TMathUtil<Real>::ZeroTolerance
TTriangle3< Real > Triangle0
TTriangle3< Real > Triangle1
Detailed Description
template<typename Real>
class UE::Geometry::TIntrTriangle3Triangle3< Real >
Compute intersection between 3D triangles use Test() for fast boolean query, does not compute intersection info use Find() to compute full information By default fully-contained co-planar triangles are not reported as intersecting.
Call SetReportCoplanarIntersection(true) to handle this case (more expensive)
Definition at line 32 of file IntrTriangle3Triangle3.h.
Constructor & Destructor Documentation
TIntrTriangle3Triangle3() [1/2]
template<typename Real> UE::Geometry::TIntrTriangle3Triangle3< Real >::TIntrTriangle3Triangle3 () inline
Definition at line 56 of file IntrTriangle3Triangle3.h.
TIntrTriangle3Triangle3() [2/2]
template<typename Real> UE::Geometry::TIntrTriangle3Triangle3< Real >::TIntrTriangle3Triangle3 (const TTriangle3< Real > & T0, const TTriangle3< Real > & T1) inline
Definition at line 58 of file IntrTriangle3Triangle3.h.
Member Function Documentation
Compute()
template<typename Real> TIntrTriangle3Triangle3 * UE::Geometry::TIntrTriangle3Triangle3< Real >::Compute () inline
Definition at line 133 of file IntrTriangle3Triangle3.h.
ContainsPoint()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::ContainsPoint (const TTriangle3< Real > & triangle, const TPlane3< Real > & plane, const TVector< Real > & point) inline protected
Definition at line 677 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Find()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::Find () inline
Definition at line 140 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Compute(), UE::Geometry::TIntrTriangle3Triangle3< float >::Find(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TriangleIntersection().
GetCoplanarIntersection()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::GetCoplanarIntersection (const TPlane3< Real > & plane, const TTriangle3< Real > & tri0, const TTriangle3< Real > & tri1) inline protected
Definition at line 736 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
GetReportCoplanarIntersection()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::GetReportCoplanarIntersection () const inline
Definition at line 104 of file IntrTriangle3Triangle3.h.
GetTolerance()
template<typename Real> Real UE::Geometry::TIntrTriangle3Triangle3< Real >::GetTolerance () const inline
Definition at line 108 of file IntrTriangle3Triangle3.h.
GetTriangle0()
template<typename Real> TTriangle3< Real > UE::Geometry::TIntrTriangle3Triangle3< Real >::GetTriangle0 () const inline
Definition at line 96 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection().
GetTriangle1()
template<typename Real> TTriangle3< Real > UE::Geometry::TIntrTriangle3Triangle3< Real >::GetTriangle1 () const inline
Definition at line 100 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection().
Intersects()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::Intersects (const TTriangle3< Real > & Triangle0, const TTriangle3< Real > & Triangle1, Real Tolerance = TMathUtil<Real>::ZeroTolerance) inline static
Definition at line 386 of file IntrTriangle3Triangle3.h.
IntersectsSegment()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::IntersectsSegment (const TPlane3< Real > & plane, const TTriangle3< Real > & triangle, const TVector< Real > & end0, const TVector< Real > & end1) inline protected
Definition at line 716 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
IntersectTriangleWithCoplanarSegment()
template<typename Real> int UE::Geometry::TIntrTriangle3Triangle3< Real >::IntersectTriangleWithCoplanarSegment (const TPlane3< Real > & plane, const TTriangle3< Real > & triangle, const TVector< Real > & end0, const TVector< Real > & end1, TVector< Real > & OutA, TVector< Real > & OutB, Real Tolerance) inline static
Solve a common sub-problem for triangle-triangle intersection – find the sub-segment (or point) where a triangle intersects a coplanar segment.
Parameters
plane The plane the triangle is on
triangle The triangle to intersect
end0 First point of line segment
end1 Second point of line segment
OutA First point of intersection between line segment and triangle (if any)
OutB Second point of intersection between line segment and triangle (if any)
Tolerance Tolerance to use for segment-triangle intersection
Returns
Number of points representing the intersection result (0 for none, 1 for point, 2 for segment)
Definition at line 545 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectsSegment().
ProjectOntoAxis()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::ProjectOntoAxis (const TTriangle3< Real > & triangle, const TVector< Real > & axis, Real & fmin, Real & fmax) inline static
Definition at line 471 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Intersects(), and UE::Geometry::TIntrTriangle3Triangle3< float >::Test().
SetReportCoplanarIntersection()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetReportCoplanarIntersection (bool bReportCoplanarIntersectionIn) inline
Definition at line 122 of file IntrTriangle3Triangle3.h.
SetResult() [1/2]
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetResult (bool IsIntersecting) inline
Store an externally-computed binary yes/no result.
Definition at line 89 of file IntrTriangle3Triangle3.h.
SetResult() [2/2]
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetResult (const TVector< Real > & A, const TVector< Real > & B) inline
Store an externally-computed segment intersection result.
Definition at line 67 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection().
SetResultNone()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetResultNone () inline
Store an externally-computed no-intersection result.
Definition at line 79 of file IntrTriangle3Triangle3.h.
SetTolerance()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetTolerance (Real ToleranceIn) inline
Definition at line 127 of file IntrTriangle3Triangle3.h.
SetTriangle0()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetTriangle0 (const TTriangle3< Real > & Triangle0In) inline
Definition at line 112 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_tri_tri_intersections().
SetTriangle1()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::SetTriangle1 (const TTriangle3< Real > & Triangle1In) inline
Definition at line 117 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_tri_tri_intersections().
Test()
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::Test () inline
Definition at line 281 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TriangleIntersection().
TrianglePlaneRelations()
template<typename Real> void UE::Geometry::TIntrTriangle3Triangle3< Real >::TrianglePlaneRelations (const TTriangle3< Real > & triangle, const TPlane3< Real > & plane, TVector< Real > & distance, FIndex3i & sign, int & positive, int & negative, int & zero, Real Tolerance) inline static
Definition at line 501 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Field Documentation
bReportCoplanarIntersection
template<typename Real> bool UE::Geometry::TIntrTriangle3Triangle3< Real >::bReportCoplanarIntersection = false protected
Definition at line 42 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Points
template<typename Real> TVector<Real> UE::Geometry::TIntrTriangle3Triangle3< Real >::Points[6]
Definition at line 54 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::AddTriTriIntersectionResult(), and UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Quantity
template<typename Real> int UE::Geometry::TIntrTriangle3Triangle3< Real >::Quantity = 0
Definition at line 53 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::AddTriTriIntersectionResult(), and UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Result
template<typename Real> EIntersectionResult UE::Geometry::TIntrTriangle3Triangle3< Real >::Result = EIntersectionResult::NotComputed
Definition at line 48 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TriangleIntersection().
Tolerance
template<typename Real> Real UE::Geometry::TIntrTriangle3Triangle3< Real >::Tolerance = TMathUtil<Real>::ZeroTolerance protected
Definition at line 37 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
Triangle0
template<typename Real> TTriangle3<Real> UE::Geometry::TIntrTriangle3Triangle3< Real >::Triangle0 protected
Definition at line 36 of file IntrTriangle3Triangle3.h.
Triangle1
template<typename Real> TTriangle3<Real> UE::Geometry::TIntrTriangle3Triangle3< Real >::Triangle1 protected
Definition at line 36 of file IntrTriangle3Triangle3.h.
Type
template<typename Real> EIntersectionType UE::Geometry::TIntrTriangle3Triangle3< Real >::Type = EIntersectionType::Empty
Definition at line 49 of file IntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::AddTriTriIntersectionResult(), and UE::Geometry::TIntrTriangle3Triangle3< float >::Find().
The documentation for this class was generated from the following file:
IntrTriangle3Triangle3.h