Unreal Engine 5.6 C++ API: FNetPacketNotify Class Reference
FNetPacketNotify Class Reference
FNetPacketNotify - Drives delivery of sequence numbers, acknowledgments and notifications of delivery sequence numbers.
#include "NetPacketNotify.h"
Data Structures
struct FNotificationHeader
struct FSentAckData
Public Types
enum { MaxSequenceHistoryLength = 256 }
enum { SequenceNumberBits = 14 }
typedef TSequenceHistory< MaxSequenceHistoryLength > SequenceHistoryT
typedef TSequenceNumber< SequenceNumberBits, uint16 > SequenceNumberT
Public Member Functions
FNetPacketNotify ()
Constructor.
void AckSeq (SequenceNumberT Seq)
Mark Seq as received and update current InSeq, missing sequence numbers will be marked as lost.
bool CanSend () const
If we do have more unacknowledged sequence numbers in-flight than our maximum sendwindow we should not send more as the receiving end will not be able to detect if the sequence number has wrapped around.
SequenceNumberT CommitAndIncrementOutSeq ()
Increment outgoing seq number and commit data.
SequenceNumberT::DifferenceT GetCurrentSequenceHistoryLength () const
Get the current sequenceHistory length in bits, clamped to the maximum history length.
SequenceNumberT GetInAckSeq () const
Get the last received sequence number that we have accepted, InAckSeq cannot be larger than InSeq.
SequenceNumberT GetInSeq () const
Get the last received in sequence number.
const SequenceHistoryT & GetInSeqHistory () const
Get the current SequenceHistory.
SequenceNumberT GetOutAckSeq () const
Get the last outgoing sequence number acknowledged by remote.
SequenceNumberT GetOutSeq () const
Get the current outgoing sequence number.
SequenceNumberT::DifferenceT GetSequenceDelta (const FNotificationHeader &NotificationData)
Gets the delta between the present sequence, and the sequence inside the specified header - if the delta is positive.
void Init (SequenceNumberT InitialInSeq, SequenceNumberT InitialOutSeq)
Init notification with expected initial sequence numbers.
bool IsSequenceWindowFull (uint32 SafetyMargin=0U) const
Return whether we can send packets without exhausting the packet sequence history window, as it could cause packets to be NAKed even when they've been received by the remote peer.
bool IsWaitingForSequenceHistoryFlush () const
Returns true if we are currently waiting for a flush of the sequence window.
void NakSeq (SequenceNumberT Seq)
Explicitly mark Seq as not received and update current InSeq, additional missing sequence numbers will be marked as lost.
bool ReadHeader (FNotificationHeader &Data, FBitReader &Reader) const
Read header from stream.
template<class Functor>
SequenceNumberT::DifferenceT Update (const FNotificationHeader &NotificationData, Functor &&InFunc)
Update state of PacketNotification based on received header and invoke packet notifications for received acks.
bool WriteHeader (FBitWriter &Writer, bool bRefresh=false)
Write NotificationHeader, and update outgoing ack record if bRefresh is true we will attempt to refresh a previously written header if the resulting size will be the same as the already written header.
Private Types
typedef TResizableCircularQueue< FSentAckData, TInlineAllocator< 128 > > AckRecordT
Private Member Functions
void AckSeq (SequenceNumberT AckedSeq, bool IsAck)
bool GetHasUnacknowledgedAcks () const
SequenceNumberT::DifferenceT InternalUpdate (const FNotificationHeader &NotificationData, SequenceNumberT::DifferenceT InSeqDelta)
template<class Functor>
void ProcessReceivedAcks (const FNotificationHeader &NotificationData, Functor &&InFunc)
void SetWaitForSequenceHistoryFlush ()
SequenceNumberT UpdateInAckSeqAck (SequenceNumberT::DifferenceT AckCount, SequenceNumberT AckedSeq)
bool WillSequenceFitInSequenceHistory (SequenceNumberT Seq) const
Private Attributes
AckRecordT AckRecord
SequenceNumberT InAckSeq
SequenceNumberT InAckSeqAck
SequenceNumberT InSeq
SequenceHistoryT InSeqHistory
SequenceNumberT OutAckSeq
SequenceNumberT OutSeq
SequenceNumberT WaitingForFlushSeqAck
SIZE_T WrittenHistoryWordCount
SequenceNumberT WrittenInAckSeq
Detailed Description
FNetPacketNotify - Drives delivery of sequence numbers, acknowledgments and notifications of delivery sequence numbers.
Definition at line 38 of file NetPacketNotify.h.
Member Typedef Documentation
AckRecordT
typedef TResizableCircularQueue<FSentAckData, TInlineAllocator<128> > FNetPacketNotify::AckRecordT private
Definition at line 140 of file NetPacketNotify.h.
SequenceHistoryT
typedef TSequenceHistory<MaxSequenceHistoryLength> FNetPacketNotify::SequenceHistoryT
Definition at line 45 of file NetPacketNotify.h.
SequenceNumberT
typedef TSequenceNumber<SequenceNumberBits, uint16> FNetPacketNotify::SequenceNumberT
Definition at line 44 of file NetPacketNotify.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MaxSequenceHistoryLength
Definition at line 42 of file NetPacketNotify.h.
anonymous enum
anonymous enum
Enumerator
SequenceNumberBits
Definition at line 41 of file NetPacketNotify.h.
Constructor & Destructor Documentation
FNetPacketNotify()
FNetPacketNotify::FNetPacketNotify ()
Constructor.
Member Function Documentation
AckSeq() [1/2]
void FNetPacketNotify::AckSeq (SequenceNumberT AckedSeq, bool IsAck) private
AckSeq() [2/2]
void FNetPacketNotify::AckSeq (SequenceNumberT Seq) inline
Mark Seq as received and update current InSeq, missing sequence numbers will be marked as lost.
Definition at line 62 of file NetPacketNotify.h.
References AckSeq().
Referenced by AckSeq(), and NakSeq().
CanSend()
bool FNetPacketNotify::CanSend () const inline
If we do have more unacknowledged sequence numbers in-flight than our maximum sendwindow we should not send more as the receiving end will not be able to detect if the sequence number has wrapped around.
Definition at line 120 of file NetPacketNotify.h.
References OutAckSeq, and OutSeq.
CommitAndIncrementOutSeq()
SequenceNumberT FNetPacketNotify::CommitAndIncrementOutSeq ()
Increment outgoing seq number and commit data.
GetCurrentSequenceHistoryLength()
SequenceNumberT::DifferenceT FNetPacketNotify::GetCurrentSequenceHistoryLength () const
Get the current sequenceHistory length in bits, clamped to the maximum history length.
GetHasUnacknowledgedAcks()
bool FNetPacketNotify::GetHasUnacknowledgedAcks () const private
GetInAckSeq()
SequenceNumberT FNetPacketNotify::GetInAckSeq () const inline
Get the last received sequence number that we have accepted, InAckSeq cannot be larger than InSeq.
Definition at line 111 of file NetPacketNotify.h.
References InAckSeq.
GetInSeq()
SequenceNumberT FNetPacketNotify::GetInSeq () const inline
Get the last received in sequence number.
Definition at line 108 of file NetPacketNotify.h.
References InSeq.
GetInSeqHistory()
const SequenceHistoryT & FNetPacketNotify::GetInSeqHistory () const inline
Get the current SequenceHistory.
Definition at line 105 of file NetPacketNotify.h.
References InSeqHistory.
GetOutAckSeq()
SequenceNumberT FNetPacketNotify::GetOutAckSeq () const inline
Get the last outgoing sequence number acknowledged by remote.
Definition at line 117 of file NetPacketNotify.h.
References OutAckSeq.
GetOutSeq()
SequenceNumberT FNetPacketNotify::GetOutSeq () const inline
Get the current outgoing sequence number.
Definition at line 114 of file NetPacketNotify.h.
References OutSeq.
GetSequenceDelta()
SequenceNumberT::DifferenceT FNetPacketNotify::GetSequenceDelta (const FNotificationHeader & NotificationData) inline
Gets the delta between the present sequence, and the sequence inside the specified header - if the delta is positive.
Definition at line 82 of file NetPacketNotify.h.
References FNetPacketNotify::FNotificationHeader::AckedSeq, TSequenceNumber< SequenceNumberBits, uint16 >::Diff(), InSeq, OutAckSeq, OutSeq, and FNetPacketNotify::FNotificationHeader::Seq.
Referenced by Update().
Init()
void FNetPacketNotify::Init (SequenceNumberT InitialInSeq, SequenceNumberT InitialOutSeq)
Init notification with expected initial sequence numbers.
InternalUpdate()
SequenceNumberT::DifferenceT FNetPacketNotify::InternalUpdate (const FNotificationHeader & NotificationData, SequenceNumberT::DifferenceT InSeqDelta) private
Referenced by Update().
IsSequenceWindowFull()
bool FNetPacketNotify::IsSequenceWindowFull (uint32 SafetyMargin = 0U) const inline
Return whether we can send packets without exhausting the packet sequence history window, as it could cause packets to be NAKed even when they've been received by the remote peer.
Parameters
SafetyMargin A small number representing how many packets you would like to keep as a safety margin for heart beats or other important packets.
Definition at line 180 of file NetPacketNotify.h.
References MaxSequenceHistoryLength, OutAckSeq, OutSeq, and SequenceLength.
IsWaitingForSequenceHistoryFlush()
bool FNetPacketNotify::IsWaitingForSequenceHistoryFlush () const inline
Returns true if we are currently waiting for a flush of the sequence window.
Definition at line 132 of file NetPacketNotify.h.
References OutAckSeq, and WaitingForFlushSeqAck.
NakSeq()
void FNetPacketNotify::NakSeq (SequenceNumberT Seq) inline
Explicitly mark Seq as not received and update current InSeq, additional missing sequence numbers will be marked as lost.
Definition at line 65 of file NetPacketNotify.h.
References AckSeq().
ProcessReceivedAcks()
template<class Functor> void FNetPacketNotify::ProcessReceivedAcks (const FNotificationHeader & NotificationData, Functor && InFunc) inline private
Definition at line 206 of file NetPacketNotify.h.
References FNetPacketNotify::FNotificationHeader::AckedSeq, TSequenceHistory< MaxSequenceHistoryLength >::BitsPerWord, TSequenceNumber< SequenceNumberBits, uint16 >::Diff(), TSequenceNumber< NumBits, SequenceType >::Get(), FNetPacketNotify::FNotificationHeader::History, FNetPacketNotify::FNotificationHeader::HistoryWordCount, InAckSeqAck, TSequenceHistory< HistorySize >::IsDelivered(), OutAckSeq, TSequenceHistory< MaxSequenceHistoryLength >::Size, TEXT, UE_LOG_PACKET_NOTIFY, UE_LOG_PACKET_NOTIFY_WARNING, UpdateInAckSeqAck(), and WaitingForFlushSeqAck.
Referenced by Update().
ReadHeader()
bool FNetPacketNotify::ReadHeader (FNotificationHeader & Data, FBitReader & Reader) const
Read header from stream.
SetWaitForSequenceHistoryFlush()
void FNetPacketNotify::SetWaitForSequenceHistoryFlush () private
Update()
template<class Functor> FNetPacketNotify::SequenceNumberT::DifferenceT FNetPacketNotify::Update (const FNotificationHeader & NotificationData, Functor && InFunc)
Update state of PacketNotification based on received header and invoke packet notifications for received acks.
Parameters
NotificationData The header to update from
InFunc A function in the format (void)(FNetPacketNotify::SequenceNumberT AckedSequence, bool bDelivered) to handle packet notifications.
Returns
The > 0 delta of the incoming seq if within half the seq number space. 0 if the received seq is outside current window ,or the ack seq received is invalid.
Definition at line 187 of file NetPacketNotify.h.
References TSequenceNumber< NumBits, SequenceType >::Get(), GetSequenceDelta(), InSeq, InternalUpdate(), ProcessReceivedAcks(), FNetPacketNotify::FNotificationHeader::Seq, TEXT, and UE_LOG_PACKET_NOTIFY.
UpdateInAckSeqAck()
SequenceNumberT FNetPacketNotify::UpdateInAckSeqAck (SequenceNumberT::DifferenceT AckCount, SequenceNumberT AckedSeq) private
Referenced by ProcessReceivedAcks().
WillSequenceFitInSequenceHistory()
bool FNetPacketNotify::WillSequenceFitInSequenceHistory (SequenceNumberT Seq) const private
WriteHeader()
bool FNetPacketNotify::WriteHeader (FBitWriter & Writer, bool bRefresh = false)
Write NotificationHeader, and update outgoing ack record if bRefresh is true we will attempt to refresh a previously written header if the resulting size will be the same as the already written header.
returns true if data was written, and false if no data was written which might be the case if we try to rewrite an existing header but the required size differs.
Field Documentation
AckRecord
AckRecordT FNetPacketNotify::AckRecord private
Definition at line 142 of file NetPacketNotify.h.
InAckSeq
SequenceNumberT FNetPacketNotify::InAckSeq private
Definition at line 149 of file NetPacketNotify.h.
Referenced by GetInAckSeq().
InAckSeqAck
SequenceNumberT FNetPacketNotify::InAckSeqAck private
Definition at line 150 of file NetPacketNotify.h.
Referenced by ProcessReceivedAcks().
InSeq
SequenceNumberT FNetPacketNotify::InSeq private
Definition at line 148 of file NetPacketNotify.h.
Referenced by GetInSeq(), GetSequenceDelta(), and Update().
InSeqHistory
SequenceHistoryT FNetPacketNotify::InSeqHistory private
Definition at line 147 of file NetPacketNotify.h.
Referenced by GetInSeqHistory().
OutAckSeq
SequenceNumberT FNetPacketNotify::OutAckSeq private
Definition at line 155 of file NetPacketNotify.h.
Referenced by CanSend(), GetOutAckSeq(), GetSequenceDelta(), IsSequenceWindowFull(), IsWaitingForSequenceHistoryFlush(), and ProcessReceivedAcks().
OutSeq
SequenceNumberT FNetPacketNotify::OutSeq private
Definition at line 154 of file NetPacketNotify.h.
Referenced by CanSend(), GetOutSeq(), GetSequenceDelta(), and IsSequenceWindowFull().
WaitingForFlushSeqAck
SequenceNumberT FNetPacketNotify::WaitingForFlushSeqAck private
Definition at line 151 of file NetPacketNotify.h.
Referenced by IsWaitingForSequenceHistoryFlush(), and ProcessReceivedAcks().
WrittenHistoryWordCount
SIZE_T FNetPacketNotify::WrittenHistoryWordCount private
Definition at line 143 of file NetPacketNotify.h.
WrittenInAckSeq
SequenceNumberT FNetPacketNotify::WrittenInAckSeq private
Definition at line 144 of file NetPacketNotify.h.
The documentation for this class was generated from the following file:
NetPacketNotify.h