Unreal Engine 5.6 C++ API: TIoPriorityQueue< T > Class Template Reference
TIoPriorityQueue< T > Class Template Reference
#include "IoPriorityQueue.h"
Data Structures
struct TInternalQueue
class TIterator
Public Member Functions
TIterator CreateIterator (int32 Priority)
int32 GetMaxPriority () const
bool IsEmpty () const
void MergeInto (TIoPriorityQueue< T > &Other, int32 Priority)
T * Pop ()
void Push (T *Item, int32 Priority)
void Remove (T *Item)
void Reprioritize (T *Item, int32 NewPriority)
Private Member Functions
TInternalQueue * AllocInternalQueue (int32 Priority)
TInternalQueue & FindOrAddQueueByPriority (int32 Priority)
TInternalQueue * FindQueueByPriority (int32 Priority) const
TInternalQueue * FindQueueByPriority (int32 Priority, int32 &OutIndex) const
void FreeInternalQueue (TInternalQueue *InternalQueue)
void RemoveQueueAtIndex (int32 Index)
void RemoveQueueByPriority (int32 Priority)
Private Attributes
TInternalQueue * FirstFreeQueue = nullptr
TArray< TInternalQueue * > InternalQueues
Detailed Description
template<typename T>
class TIoPriorityQueue< T >
Definition at line 10 of file IoPriorityQueue.h.
Member Function Documentation
AllocInternalQueue()
template<typename T> TInternalQueue * TIoPriorityQueue< T >::AllocInternalQueue (int32 Priority) inline private
Definition at line 308 of file IoPriorityQueue.h.
References FirstFreeQueue.
Referenced by FindOrAddQueueByPriority().
CreateIterator()
template<typename T> TIterator TIoPriorityQueue< T >::CreateIterator (int32 Priority) inline
Definition at line 204 of file IoPriorityQueue.h.
FindOrAddQueueByPriority()
template<typename T> TInternalQueue & TIoPriorityQueue< T >::FindOrAddQueueByPriority (int32 Priority) inline private
Definition at line 283 of file IoPriorityQueue.h.
References AllocInternalQueue(), InternalQueues, Algo::LowerBoundBy(), and TIoPriorityQueue< T >::TInternalQueue::Priority.
Referenced by Push().
FindQueueByPriority() [1/2]
template<typename T> TInternalQueue * TIoPriorityQueue< T >::FindQueueByPriority (int32 Priority) const inline private
Definition at line 262 of file IoPriorityQueue.h.
References InternalQueues, Algo::LowerBoundBy(), and TIoPriorityQueue< T >::TInternalQueue::Priority.
Referenced by MergeInto(), Remove(), and RemoveQueueByPriority().
FindQueueByPriority() [2/2]
template<typename T> TInternalQueue * TIoPriorityQueue< T >::FindQueueByPriority (int32 Priority, int32 & OutIndex) const inline private
Definition at line 272 of file IoPriorityQueue.h.
References InternalQueues, Algo::LowerBoundBy(), and TIoPriorityQueue< T >::TInternalQueue::Priority.
FreeInternalQueue()
template<typename T> void TIoPriorityQueue< T >::FreeInternalQueue (TInternalQueue * InternalQueue) inline private
Definition at line 320 of file IoPriorityQueue.h.
References check, FirstFreeQueue, TIoPriorityQueue< T >::TInternalQueue::Head, TIoPriorityQueue< T >::TInternalQueue::NextFree, and TIoPriorityQueue< T >::TInternalQueue::Tail.
Referenced by RemoveQueueAtIndex().
GetMaxPriority()
template<typename T> int32 TIoPriorityQueue< T >::GetMaxPriority () const inline
Definition at line 144 of file IoPriorityQueue.h.
References InternalQueues, and MIN_int32.
IsEmpty()
template<typename T> bool TIoPriorityQueue< T >::IsEmpty () const inline
Definition at line 139 of file IoPriorityQueue.h.
References InternalQueues.
MergeInto()
template<typename T> void TIoPriorityQueue< T >::MergeInto (TIoPriorityQueue< T > & Other, int32 Priority) inline
Definition at line 236 of file IoPriorityQueue.h.
References check, FindQueueByPriority(), TIoPriorityQueue< T >::TInternalQueue::Head, Other, RemoveQueueAtIndex(), and TIoPriorityQueue< T >::TInternalQueue::Tail.
Pop()
template<typename T> T * TIoPriorityQueue< T >::Pop () inline
Definition at line 172 of file IoPriorityQueue.h.
References check, TIoPriorityQueue< T >::TInternalQueue::Head, InternalQueues, Item, TIoPriorityQueue< T >::TInternalQueue::Priority, RemoveQueueAtIndex(), and TIoPriorityQueue< T >::TInternalQueue::Tail.
Push()
template<typename T> void TIoPriorityQueue< T >::Push (T * Item, int32 Priority) inline
Definition at line 153 of file IoPriorityQueue.h.
References check, FindOrAddQueueByPriority(), TIoPriorityQueue< T >::TInternalQueue::Head, Item, and TIoPriorityQueue< T >::TInternalQueue::Tail.
Referenced by Reprioritize().
Remove()
template<typename T> void TIoPriorityQueue< T >::Remove (T * Item) inline
Definition at line 209 of file IoPriorityQueue.h.
References check, FindQueueByPriority(), Item, TIoPriorityQueue< T >::TInternalQueue::Remove(), and RemoveQueueAtIndex().
RemoveQueueAtIndex()
template<typename T> void TIoPriorityQueue< T >::RemoveQueueAtIndex (int32 Index) inline private
Definition at line 302 of file IoPriorityQueue.h.
References FreeInternalQueue(), InternalQueues, and No.
Referenced by MergeInto(), Pop(), Remove(), and RemoveQueueByPriority().
RemoveQueueByPriority()
template<typename T> void TIoPriorityQueue< T >::RemoveQueueByPriority (int32 Priority) inline private
Definition at line 293 of file IoPriorityQueue.h.
References FindQueueByPriority(), and RemoveQueueAtIndex().
Reprioritize()
template<typename T> void TIoPriorityQueue< T >::Reprioritize (T * Item, int32 NewPriority) inline
Definition at line 230 of file IoPriorityQueue.h.
References Item, Push(), and Remove.
Field Documentation
FirstFreeQueue
template<typename T> TInternalQueue* TIoPriorityQueue< T >::FirstFreeQueue = nullptr private
Definition at line 329 of file IoPriorityQueue.h.
Referenced by AllocInternalQueue(), and FreeInternalQueue().
InternalQueues
template<typename T> TArray<TInternalQueue*> TIoPriorityQueue< T >::InternalQueues private
Definition at line 328 of file IoPriorityQueue.h.
Referenced by FindOrAddQueueByPriority(), FindQueueByPriority(), FindQueueByPriority(), GetMaxPriority(), IsEmpty(), Pop(), and RemoveQueueAtIndex().
The documentation for this class was generated from the following file:
IoPriorityQueue.h