Unreal Engine 5.6 C++ API: IPixelStreamingModule Class Reference
IPixelStreamingModule Class Reference abstract
The public interface of the Pixel Streaming module.
#include "IPixelStreamingModule.h"
Public Member Functions
virtual void AddInputComponent (UPixelStreamingInput *InInputComponent)=0
Tell the input device about a new pixel streaming input component.
virtual rtc::scoped_refptr< webrtc::VideoTrackSourceInterface > CreateExternalVideoSource ()=0
Allows the creation of Video Tracks that are fed the backbuffer.
virtual TSharedPtr< IPixelStreamingStreamer > CreateStreamer (const FString &StreamerId)=0
Creates a new streamer.
virtual TUniquePtr< webrtc::VideoEncoderFactory > CreateVideoEncoderFactory ()=0
Create a webrtc::VideoEncoderFactory pointer.
DECLARE_EVENT_OneParam (IPixelStreamingModule, FReadyEvent, IPixelStreamingModule &)
virtual TSharedPtr< IPixelStreamingStreamer > DeleteStreamer (const FString &StreamerId)=0
Remove a streamer by an ID.
virtual void DeleteStreamer (TSharedPtr< IPixelStreamingStreamer > ToBeDeleted)=0
Remove a streamer by its pointer.
virtual TSharedPtr< IPixelStreamingStreamer > FindStreamer (const FString &StreamerId)=0
Find a streamer by an ID.
virtual void ForEachStreamer (const TFunction< void(TSharedPtr< IPixelStreamingStreamer >)> &Func)=0
A method for iterating through all of the streamers on the module.
virtual EPixelStreamingCodec GetCodec () const =0
Gets the currently selected encoder codec for all of Pixel Streaming.
virtual FString GetDefaultSignallingURL ()=0
Get the Default Signaling URL ("ws://127.0.0.1:8888")
virtual FString GetDefaultStreamerID ()=0
Get the Default Streamer ID.
virtual const TArray< UPixelStreamingInput * > GetInputComponents ()=0
Get the input components currently attached to Pixel Streaming.
virtual TArray< FString > GetStreamerIds ()=0
Returns a TArray containing the keys to the currently held streamers.
virtual bool IsReady ()=0
Is the PixelStreaming module actually ready to use?
virtual FReadyEvent & OnReady ()=0
A getter for the OnReady event.
virtual void ReleaseExternalVideoSource (const webrtc::VideoTrackSourceInterface *InVideoSource)=0
Used to clean up sources no longer needed.
virtual void RemoveInputComponent (UPixelStreamingInput *InInputComponent)=0
Tell the input device that a pixel streaming input component is no longer relevant.
virtual void SetCodec (EPixelStreamingCodec Codec)=0
Sets the encoder codec for the whole Pixel Streaming module.
virtual void SetExternalVideoSourceCoupleFramerate (bool bShouldCoupleFPS)=0
Control coupling the external video source framerate to the video input framerate.
virtual void SetExternalVideoSourceFPS (uint32 InFPS)=0
Sets the target FPS for Externally Consumed video Tracks.
virtual void SetExternalVideoSourceInput (TSharedPtr< FPixelStreamingVideoInput > InVideoInput)=0
Hook to set the input to the external video source.
virtual bool StartStreaming ()=0
Starts streaming on all streamers.
virtual void StopStreaming ()=0
Stops all streamers from streaming.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IPixelStreamingModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
The public interface of the Pixel Streaming module.
Definition at line 22 of file IPixelStreamingModule.h.
Member Function Documentation
AddInputComponent()
virtual void IPixelStreamingModule::AddInputComponent (UPixelStreamingInput * InInputComponent) pure virtual
Tell the input device about a new pixel streaming input component.
Parameters
InInputComponent - The new pixel streaming input component.
CreateExternalVideoSource()
virtual rtc::scoped_refptr< webrtc::VideoTrackSourceInterface > IPixelStreamingModule::CreateExternalVideoSource () pure virtual
Allows the creation of Video Tracks that are fed the backbuffer.
CreateStreamer()
virtual TSharedPtr< IPixelStreamingStreamer > IPixelStreamingModule::CreateStreamer (const FString & StreamerId) pure virtual
Creates a new streamer.
Parameters
StreamerId - The ID of the Streamer to be created.
CreateVideoEncoderFactory()
virtual TUniquePtr< webrtc::VideoEncoderFactory > IPixelStreamingModule::CreateVideoEncoderFactory () pure virtual
Create a webrtc::VideoEncoderFactory pointer.
Returns
A WebRTC video encoder factory with its encoders populated by Pixel Streaming.
DECLARE_EVENT_OneParam()
IPixelStreamingModule::DECLARE_EVENT_OneParam (IPixelStreamingModule , FReadyEvent , IPixelStreamingModule &)
DeleteStreamer() [1/2]
virtual TSharedPtr< IPixelStreamingStreamer > IPixelStreamingModule::DeleteStreamer (const FString & StreamerId) pure virtual
Remove a streamer by an ID.
Parameters
StreamerId - The ID of the streamer to be removed.
Returns
The removed streamer. nullptr if the streamer wasn't found.
DeleteStreamer() [2/2]
virtual void IPixelStreamingModule::DeleteStreamer (TSharedPtr< IPixelStreamingStreamer > ToBeDeleted) pure virtual
Remove a streamer by its pointer.
Parameters
ToBeDeleted The streamer to remove from the internal management.
FindStreamer()
virtual TSharedPtr< IPixelStreamingStreamer > IPixelStreamingModule::FindStreamer (const FString & StreamerId) pure virtual
Find a streamer by an ID.
Returns
A pointer to the interface for a streamer. nullptr if the streamer isn't found
ForEachStreamer()
virtual void IPixelStreamingModule::ForEachStreamer (const TFunction< void(TSharedPtr< IPixelStreamingStreamer >)> & Func) pure virtual
A method for iterating through all of the streamers on the module.
Parameters
Func The lambda to execute with each streamer
Get()
IPixelStreamingModule & IPixelStreamingModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 31 of file IPixelStreamingModule.h.
References FModuleManager::LoadModuleChecked().
GetCodec()
virtual EPixelStreamingCodec IPixelStreamingModule::GetCodec () const pure virtual
Gets the currently selected encoder codec for all of Pixel Streaming.
Returns
A valid EPixelStreamingCodec value.
GetDefaultSignallingURL()
virtual FString IPixelStreamingModule::GetDefaultSignallingURL () pure virtual
Get the Default Signaling URL ("ws://127.0.0.1:8888")
Returns
FString The default signaling url ("ws://127.0.0.1:8888")
GetDefaultStreamerID()
virtual FString IPixelStreamingModule::GetDefaultStreamerID () pure virtual
Get the Default Streamer ID.
Returns
FString The default streamer ID
GetInputComponents()
virtual const TArray< UPixelStreamingInput * > IPixelStreamingModule::GetInputComponents () pure virtual
Get the input components currently attached to Pixel Streaming.
Returns
An array of input components.
GetStreamerIds()
virtual TArray< FString > IPixelStreamingModule::GetStreamerIds () pure virtual
Returns a TArray containing the keys to the currently held streamers.
Returns
TArray containing the keys to the currently held streamers.
IsAvailable()
bool IPixelStreamingModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 41 of file IPixelStreamingModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
IsReady()
virtual bool IPixelStreamingModule::IsReady () pure virtual
Is the PixelStreaming module actually ready to use?
Is the streamer created.
Returns
True if Pixel Streaming module methods are ready for use.
OnReady()
virtual FReadyEvent & IPixelStreamingModule::OnReady () pure virtual
A getter for the OnReady event.
Intent is for users to call IPixelStreamingModule::Get().OnReady().AddXXX.
Returns
The bindable OnReady event.
ReleaseExternalVideoSource()
virtual void IPixelStreamingModule::ReleaseExternalVideoSource (const webrtc::VideoTrackSourceInterface * InVideoSource) pure virtual
Used to clean up sources no longer needed.
RemoveInputComponent()
virtual void IPixelStreamingModule::RemoveInputComponent (UPixelStreamingInput * InInputComponent) pure virtual
Tell the input device that a pixel streaming input component is no longer relevant.
Parameters
InInputComponent - The pixel streaming input component which is no longer relevant.
SetCodec()
virtual void IPixelStreamingModule::SetCodec (EPixelStreamingCodec Codec) pure virtual
Sets the encoder codec for the whole Pixel Streaming module.
Should be called before any streaming starts.
Parameters
Codec A valid EPixelStreamingCodec value.
SetExternalVideoSourceCoupleFramerate()
virtual void IPixelStreamingModule::SetExternalVideoSourceCoupleFramerate (bool bShouldCoupleFPS) pure virtual
Control coupling the external video source framerate to the video input framerate.
Parameters
bShouldCoupleFPS Flag for coupling the video source and video input framerates
SetExternalVideoSourceFPS()
virtual void IPixelStreamingModule::SetExternalVideoSourceFPS (uint32 InFPS) pure virtual
Sets the target FPS for Externally Consumed video Tracks.
Parameters
InFPS new FPS for the ExternalVideoSource to output at.
SetExternalVideoSourceInput()
virtual void IPixelStreamingModule::SetExternalVideoSourceInput (TSharedPtr< FPixelStreamingVideoInput > InVideoInput) pure virtual
Hook to set the input to the external video source.
Will also call Start() on the external video source
StartStreaming()
virtual bool IPixelStreamingModule::StartStreaming () pure virtual
Starts streaming on all streamers.
StopStreaming()
virtual void IPixelStreamingModule::StopStreaming () pure virtual
Stops all streamers from streaming.
The documentation for this class was generated from the following file:
IPixelStreamingModule.h