Unreal Engine 5.6 C++ API: VertexFactory.h File Reference
VertexFactory.h File Reference
#include "Containers/Array.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/EnumAsByte.h"
#include "Containers/List.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "HAL/PlatformCrt.h"
#include "Math/NumericLimits.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/SecureHash.h"
#include "RHI.h"
#include "RHIDefinitions.h"
#include "RenderResource.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryImage.h"
#include "Serialization/MemoryLayout.h"
#include "Shader.h"
#include "ShaderCore.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/NameTypes.h"
#include "VertexStreamComponent.h"
#include <atomic>
Data Structures
class FCompareVertexFactoryTypes
Used to compare two Vertex Factory types by name.
class FPrimitiveIdDummyBuffer
Default PrimitiveId vertex buffer.
class FVertexFactory
Encapsulates a vertex data source which can be linked into a vertex shader.
struct FVertexFactory::FVertexStream
Information needed to set a vertex stream.
class FVertexFactoryShaderParameters
An interface to the parameter bindings for the vertex factory used by a shader.
class FVertexFactoryType
An object used to represent the type of a vertex factory.
class FVertexFactoryTypeDependency
Encapsulates a dependency on a vertex factory type and saved state from that vertex factory type.
struct FVertexInputStream
struct TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >
Macros
#define DECLARE_VERTEX_FACTORY_TYPE(FactoryClass)
A macro for declaring a new vertex factory type, for use in the vertex factory class's definition body.
#define DECLARE_VERTEX_FACTORY_TYPE_API(FactoryClass, ModuleApi)
#define IMPLEMENT_TEMPLATE_VERTEX_FACTORY_TYPE(TemplatePrefix, FactoryClass, ShaderFilename, Flags)
Templated macro to define a FVertexFactoryType.
#define IMPLEMENT_VERTEX_FACTORY_EDITOR_VTABLE(FactoryClass)
#define IMPLEMENT_VERTEX_FACTORY_PARAMETER_TYPE(FactoryClass, ShaderFrequency, ParameterClass)
#define IMPLEMENT_VERTEX_FACTORY_TYPE(FactoryClass, ShaderFilename, Flags)
A macro for implementing the static vertex factory type object, and specifying parameters used by the type.
#define IMPLEMENT_VERTEX_FACTORY_VTABLE(FactoryClass)
#define STRUCTMEMBER_VERTEXSTREAMCOMPONENT(VertexBuffer, VertexType, Member, MemberType)
A macro which initializes a FVertexStreamComponent to read a member from a struct.
Typedefs
typedef TArray< FVertexInputStream, TInlineAllocator< 7 > > FVertexInputStreamArray
Number of vertex input bindings to allocate inline within a FMeshDrawCommand.
Enumerations
enum class EVertexFactoryFlags : uint32 {
None = 0u , UsedWithMaterials = 1u << 1 , SupportsStaticLighting = 1u << 2 , SupportsDynamicLighting = 1u << 3 ,
SupportsPrecisePrevWorldPos = 1u << 4 , SupportsPositionOnly = 1u << 5 , SupportsCachingMeshDrawCommands = 1u << 6 , SupportsPrimitiveIdStream = 1u << 7 ,
SupportsNaniteRendering = 1u << 8 , SupportsRayTracing = 1u << 9 , SupportsRayTracingDynamicGeometry = 1u << 10 , SupportsRayTracingProceduralPrimitive = 1u << 11 ,
SupportsLightmapBaking = 1u << 12 , SupportsPSOPrecaching = 1u << 13 , SupportsManualVertexFetch = 1u << 14 , DoesNotSupportNullPixelShader = 1u << 15 ,
SupportsGPUSkinPassThrough = 1u << 16 , SupportsComputeShading = 1u << 17 , SupportsLumenMeshCards = 1u << 18 , SupportsLandscape = 1u << 19 ,
IncludesFwdShader = 1u << 20 , SupportsTriangleSorting = 1u << 21
}
enum class EVertexInputStreamType : uint8 { Default = 0 , PositionOnly , PositionAndNormalOnly , Count }
Functions
template<typename VertexFactoryType>
static FVertexFactoryShaderParameters * ConstructVertexFactoryParameters (EShaderFrequency ShaderFrequency, const class FShaderParameterMap &ParameterMap)
RENDERCORE_API FVertexFactoryType * FindVertexFactoryType (const FHashedName &TypeName)
Find the vertex factory type with the given name.
template<typename VertexFactoryType>
static void GetVertexFactoryParametersElementShaderBindings (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters *Parameters, const class FSceneInterface *Scene, const class FSceneView *View, const class FMeshMaterialShader *Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory *VertexFactory, const struct FMeshBatchElement &BatchElement, class FMeshDrawSingleShaderBindings &ShaderBindings, FVertexInputStreamArray &VertexStreams)
template<typename VertexFactoryType>
static const FTypeLayoutDesc * GetVertexFactoryParametersLayout (EShaderFrequency ShaderFrequency)
constexpr bool operator! (EVertexFactoryFlags E)
constexpr bool operator! (EVertexStreamUsage E)
constexpr EVertexFactoryFlags operator& (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs)
constexpr EVertexStreamUsage operator& (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs)
EVertexFactoryFlags & operator&= (EVertexFactoryFlags &Lhs, EVertexFactoryFlags Rhs)
EVertexStreamUsage & operator&= (EVertexStreamUsage &Lhs, EVertexStreamUsage Rhs)
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FVertexFactoryType *&TypeRef)
Serializes a reference to a vertex factory type.
constexpr EVertexFactoryFlags operator^ (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs)
constexpr EVertexStreamUsage operator^ (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs)
EVertexFactoryFlags & operator^= (EVertexFactoryFlags &Lhs, EVertexFactoryFlags Rhs)
EVertexStreamUsage & operator^= (EVertexStreamUsage &Lhs, EVertexStreamUsage Rhs)
constexpr EVertexFactoryFlags operator| (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs)
constexpr EVertexStreamUsage operator| (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs)
EVertexFactoryFlags & operator|= (EVertexFactoryFlags &Lhs, EVertexFactoryFlags Rhs)
EVertexStreamUsage & operator|= (EVertexStreamUsage &Lhs, EVertexStreamUsage Rhs)
constexpr EVertexFactoryFlags operator~ (EVertexFactoryFlags E)
constexpr EVertexStreamUsage operator~ (EVertexStreamUsage E)
Variables
RENDERCORE_API TGlobalResource< FPrimitiveIdDummyBuffer > GPrimitiveIdDummy
Macro Definition Documentation
DECLARE_VERTEX_FACTORY_TYPE
#define DECLARE_VERTEX_FACTORY_TYPE (FactoryClass)
Value:
    public: \
    static FVertexFactoryType StaticType; \
    virtual FVertexFactoryType* GetType() const override;
A macro for declaring a new vertex factory type, for use in the vertex factory class's definition body.
Definition at line 548 of file VertexFactory.h.
DECLARE_VERTEX_FACTORY_TYPE_API
#define DECLARE_VERTEX_FACTORY_TYPE_API (FactoryClass, ModuleApi)
Value:
    public: \
    ModuleApi static FVertexFactoryType StaticType; \
    ModuleApi virtual FVertexFactoryType* GetType() const override;
Definition at line 553 of file VertexFactory.h.
IMPLEMENT_TEMPLATE_VERTEX_FACTORY_TYPE
#define IMPLEMENT_TEMPLATE_VERTEX_FACTORY_TYPE (TemplatePrefix, FactoryClass, ShaderFilename, Flags)
Value:
    PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) FVertexFactoryType FactoryClass::StaticType( \
        TEXT(#FactoryClass), \
        TEXT(ShaderFilename), \
        Flags, \
        IMPLEMENT_VERTEX_FACTORY_VTABLE(FactoryClass) \
        ); \
        PREPROCESSOR_REMOVE_OPTIONAL_PARENS(TemplatePrefix) FVertexFactoryType* FactoryClass::GetType() const { return &StaticType; }
Templated macro to define a FVertexFactoryType.
Can be used for templated Vertex Factories.
Definition at line 588 of file VertexFactory.h.
IMPLEMENT_VERTEX_FACTORY_EDITOR_VTABLE
#define IMPLEMENT_VERTEX_FACTORY_EDITOR_VTABLE (FactoryClass)
Value:
        , FactoryClass::ModifyCompilationEnvironment \
        , FactoryClass::ValidateCompiledResult
Definition at line 559 of file VertexFactory.h.
IMPLEMENT_VERTEX_FACTORY_PARAMETER_TYPE
#define IMPLEMENT_VERTEX_FACTORY_PARAMETER_TYPE (FactoryClass, ShaderFrequency, ParameterClass)
Value:
    template<> struct TVertexFactoryParameterTraits<ShaderFrequency, FactoryClass> \
    { \
        static const FTypeLayoutDesc* GetLayout() { return &StaticGetTypeLayoutDesc<ParameterClass>(); } \
        static FVertexFactoryShaderParameters* Create(const class FShaderParameterMap& ParameterMap) { ParameterClass* Result = new ParameterClass(); Result->Bind(ParameterMap); return Result; } \
        static void GetElementShaderBindings( \
            const FVertexFactoryShaderParameters* Parameters, \
            const class FSceneInterface* Scene, \
            const class FSceneView* View, \
            const class FMeshMaterialShader* Shader, \
            const EVertexInputStreamType InputStreamType, \
            ERHIFeatureLevel::Type FeatureLevel, \
            const class FVertexFactory* VertexFactory, \
            const struct FMeshBatchElement& BatchElement, \
            class FMeshDrawSingleShaderBindings& ShaderBindings, \
            FVertexInputStreamArray& VertexStreams) \
        { \
            static_cast<const ParameterClass*>(Parameters)->GetElementShaderBindings(Scene, View, Shader, InputStreamType, FeatureLevel, VertexFactory, BatchElement, ShaderBindings, VertexStreams); \
        } \
    }
Definition at line 216 of file VertexFactory.h.
IMPLEMENT_VERTEX_FACTORY_TYPE
#define IMPLEMENT_VERTEX_FACTORY_TYPE (FactoryClass, ShaderFilename, Flags)
Value:
    FVertexFactoryType FactoryClass::StaticType( \
        TEXT(#FactoryClass), \
        TEXT(ShaderFilename), \
        Flags, \
        IMPLEMENT_VERTEX_FACTORY_VTABLE(FactoryClass) \
        ); \
        FVertexFactoryType* FactoryClass::GetType() const { return &StaticType; }
A macro for implementing the static vertex factory type object, and specifying parameters used by the type.
Definition at line 577 of file VertexFactory.h.
IMPLEMENT_VERTEX_FACTORY_VTABLE
#define IMPLEMENT_VERTEX_FACTORY_VTABLE (FactoryClass)
Value:
    &ConstructVertexFactoryParameters<FactoryClass>, \
    &GetVertexFactoryParametersLayout<FactoryClass>, \
    &GetVertexFactoryParametersElementShaderBindings<FactoryClass>, \
    FactoryClass::GetPSOPrecacheVertexFetchElements, \
    FactoryClass::ShouldCompilePermutation \
    IMPLEMENT_VERTEX_FACTORY_EDITOR_VTABLE(FactoryClass)
Definition at line 566 of file VertexFactory.h.
STRUCTMEMBER_VERTEXSTREAMCOMPONENT
#define STRUCTMEMBER_VERTEXSTREAMCOMPONENT (VertexBuffer, VertexType, Member, MemberType)
Value:
    FVertexStreamComponent(VertexBuffer,STRUCT_OFFSET(VertexType,Member),sizeof(VertexType),MemberType)
A macro which initializes a FVertexStreamComponent to read a member from a struct.
Definition at line 165 of file VertexFactory.h.
Typedef Documentation
FVertexInputStreamArray
typedef TArray<FVertexInputStream, TInlineAllocator<7> > FVertexInputStreamArray
Number of vertex input bindings to allocate inline within a FMeshDrawCommand.
This is tweaked so that the bindings for commonly cached factories (FLocalVertexFactory, FGPUBaseSkinVertexFactory) fit into the inline storage. Overflow of the inline storage will cause a heap allocation per draw (and corresponding cache miss on traversal)
Definition at line 123 of file VertexFactory.h.
Enumeration Type Documentation
EVertexFactoryFlags
enum class EVertexFactoryFlags : uint32 strong
Enumerator
None
UsedWithMaterials
SupportsStaticLighting
SupportsDynamicLighting
SupportsPrecisePrevWorldPos
SupportsPositionOnly
SupportsCachingMeshDrawCommands
SupportsPrimitiveIdStream
SupportsNaniteRendering
SupportsRayTracing
SupportsRayTracingDynamicGeometry
SupportsRayTracingProceduralPrimitive
SupportsLightmapBaking
SupportsPSOPrecaching
SupportsManualVertexFetch
DoesNotSupportNullPixelShader
SupportsGPUSkinPassThrough
SupportsComputeShading
SupportsLumenMeshCards
SupportsLandscape
IncludesFwdShader
SupportsTriangleSorting
Definition at line 135 of file VertexFactory.h.
EVertexInputStreamType
enum class EVertexInputStreamType : uint8 strong
Enumerator
Default
PositionOnly
PositionAndNormalOnly
Count
Definition at line 127 of file VertexFactory.h.
Function Documentation
ConstructVertexFactoryParameters()
template<typename VertexFactoryType> FVertexFactoryShaderParameters * ConstructVertexFactoryParameters (EShaderFrequency ShaderFrequency, const class FShaderParameterMap & ParameterMap) static
Definition at line 259 of file VertexFactory.h.
References checkNoEntry, and TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::Create().
FindVertexFactoryType()
RENDERCORE_API FVertexFactoryType * FindVertexFactoryType (const FHashedName & TypeName) extern
Find the vertex factory type with the given name.
Returns
NULL if no vertex factory type matched, otherwise a vertex factory type with a matching name.
GetVertexFactoryParametersElementShaderBindings()
template<typename VertexFactoryType> void GetVertexFactoryParametersElementShaderBindings (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters * Parameters, const class FSceneInterface * Scene, const class FSceneView * View, const class FMeshMaterialShader * Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory * VertexFactory, const struct FMeshBatchElement & BatchElement, class FMeshDrawSingleShaderBindings & ShaderBindings, FVertexInputStreamArray & VertexStreams) static
Definition at line 281 of file VertexFactory.h.
References checkNoEntry, TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::GetElementShaderBindings(), Scene, and VertexFactory.
GetVertexFactoryParametersLayout()
template<typename VertexFactoryType> const FTypeLayoutDesc * GetVertexFactoryParametersLayout (EShaderFrequency ShaderFrequency) static
Definition at line 238 of file VertexFactory.h.
References checkNoEntry, and TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::GetLayout().
operator!() [1/2]
bool operator! (EVertexFactoryFlags E) inline constexpr
Definition at line 160 of file VertexFactory.h.
operator!() [2/2]
bool operator! (EVertexStreamUsage E) inline constexpr
Definition at line 125 of file VertexFactory.h.
operator&() [1/2]
EVertexFactoryFlags operator& (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs) inline constexpr
Definition at line 160 of file VertexFactory.h.
operator&() [2/2]
EVertexStreamUsage operator& (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs) inline constexpr
Definition at line 125 of file VertexFactory.h.
operator&=() [1/2]
EVertexFactoryFlags & operator&= (EVertexFactoryFlags & Lhs, EVertexFactoryFlags Rhs) inline
Definition at line 160 of file VertexFactory.h.
operator&=() [2/2]
EVertexStreamUsage & operator&= (EVertexStreamUsage & Lhs, EVertexStreamUsage Rhs) inline
Definition at line 125 of file VertexFactory.h.
operator<<()
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FVertexFactoryType *& TypeRef) extern
Serializes a reference to a vertex factory type.
References Ar.
operator^() [1/2]
EVertexFactoryFlags operator^ (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs) inline constexpr
Definition at line 160 of file VertexFactory.h.
operator^() [2/2]
EVertexStreamUsage operator^ (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs) inline constexpr
Definition at line 125 of file VertexFactory.h.
operator^=() [1/2]
EVertexFactoryFlags & operator^= (EVertexFactoryFlags & Lhs, EVertexFactoryFlags Rhs) inline
Definition at line 160 of file VertexFactory.h.
operator^=() [2/2]
EVertexStreamUsage & operator^= (EVertexStreamUsage & Lhs, EVertexStreamUsage Rhs) inline
Definition at line 125 of file VertexFactory.h.
operator|() [1/2]
EVertexFactoryFlags operator| (EVertexFactoryFlags Lhs, EVertexFactoryFlags Rhs) inline constexpr
Definition at line 160 of file VertexFactory.h.
operator|() [2/2]
EVertexStreamUsage operator| (EVertexStreamUsage Lhs, EVertexStreamUsage Rhs) inline constexpr
Definition at line 125 of file VertexFactory.h.
operator|=() [1/2]
EVertexFactoryFlags & operator|= (EVertexFactoryFlags & Lhs, EVertexFactoryFlags Rhs) inline
Definition at line 160 of file VertexFactory.h.
operator|=() [2/2]
EVertexStreamUsage & operator|= (EVertexStreamUsage & Lhs, EVertexStreamUsage Rhs) inline
Definition at line 125 of file VertexFactory.h.
operator~() [1/2]
EVertexFactoryFlags operator~ (EVertexFactoryFlags E) inline constexpr
Definition at line 160 of file VertexFactory.h.
operator~() [2/2]
EVertexStreamUsage operator~ (EVertexStreamUsage E) inline constexpr
Definition at line 125 of file VertexFactory.h.
Variable Documentation
GPrimitiveIdDummy
RENDERCORE_API TGlobalResource<FPrimitiveIdDummyBuffer> GPrimitiveIdDummy extern