Unreal Engine 5.6 C++ API: ThumbnailTools Namespace Reference
ThumbnailTools Namespace Reference
Namespaces
namespace EThumbnailTextureFlushMode
Thumbnail texture flush mode.
Functions
UNREALED_API FDelegateHandle AddLoadThumbnailsFromPackageDelegate (FLoadThumbnailsFromPackage InDelegate)
Add delegate to handle loading of thumbnail from package.
UNREALED_API bool AssetHasCustomCreatedThumbnail (const FString &InAssetDataFullName)
Returns true if the given asset has a custom thumbnail cached or on the disk and if the thumbnail was captured from a viewport.
UNREALED_API bool AssetHasCustomThumbnail (const FString &InAssetDataFullName)
Returns true if the given asset has a custom thumbnail cached or on the disk.
UNREALED_API bool AssetHasCustomThumbnail (const FString &InAssetDataFullName, FObjectThumbnail &OutThumbnail)
UNREALED_API void CacheEmptyThumbnail (const FString &ObjectFullName, UPackage *DestPackage)
Caches an empty thumbnail entry.
UNREALED_API FObjectThumbnail * CacheThumbnail (const FString &ObjectFullName, FObjectThumbnail *Thumbnail, UPackage *DestPackage)
Caches a thumbnail into a package's thumbnail map.
UNREALED_API bool ConditionallyLoadThumbnailsForObjects (const TArray< FName > &InObjectFullNames, FThumbnailMap &InOutThumbnails)
Loads thumbnails for the specified objects (or copies them from a cache, if they're already loaded.)
UNREALED_API bool ConditionallyLoadThumbnailsFromPackage (const FString &InPackageFileName, const TSet< FName > &InObjectFullNames, FThumbnailMap &InOutThumbnails)
Loads thumbnails from a package unless they're already cached in that package's thumbnail map.
UNREALED_API const FObjectThumbnail * FindCachedThumbnail (const FString &InFullName)
Searches for an object's thumbnail in memory and returns it if found.
UNREALED_API FObjectThumbnail * GenerateThumbnailForObjectToSaveToDisk (UObject *InObject)
Generates a thumbnail for the specified object and caches it.
UNREALED_API FObjectThumbnail * GetThumbnailForObject (UObject *InObject)
Returns the thumbnail for the specified object or NULL if one doesn't exist yet.
UNREALED_API bool LoadThumbnailFromPackage (const FAssetData &AssetData, FObjectThumbnail &OutThumbnail)
Loads the thumbnail of an asset from the specified package file name (or from the external thumbnail cache file if it exists)
UNREALED_API bool LoadThumbnailsFromPackage (const FString &InPackageFileName, const TSet< FName > &InObjectFullNames, FThumbnailMap &InOutThumbnails)
Loads thumbnails from the specified package file name (or from the external thumbnail cache file if it exists)
UNREALED_API bool LoadThumbnailsFromPackageDirectly (const FString &InPackageFileName, const TSet< FName > &InObjectFullNames, FThumbnailMap &InOutThumbnails, const FString &InPackageFileNameToOpen)
Loads thumbnails from the specified package file name (without using external thumbnail cache or delegates, only attempts to read from InPackageFileNameToOpen provided)
UNREALED_API bool LoadThumbnailsFromPackageUsingExternalFolders (const FString &InPackageFileName, const TSet< FName > &InObjectFullNames, FThumbnailMap &InOutThumbnails, TConstArrayView< FString > ExternalFolders)
Loads thumbnails from the specified package file name.
UNREALED_API bool QueryPackageFileNameForObject (const FString &InFullName, FString &OutPackageFileName)
Finds the file path/name of an existing package for the specified object full name, or false if the package is not valid.
UNREALED_API void RemoveLoadThumbnailsFromPackageDelegate (const FDelegateHandle InHandle)
Remove delegate to handle loading of thumbnail from package.
UNREALED_API void RenderThumbnail (UObject *InObject, const uint32 InImageWidth, const uint32 InImageHeight, EThumbnailTextureFlushMode::Type InFlushMode, FTextureRenderTargetResource *InRenderTargetResource=NULL, FObjectThumbnail *OutThumbnail=NULL)
Renders a thumbnail for the specified object.
Variables
const int32 DefaultThumbnailSize =256
Standard thumbnail height setting used by generation.
Function Documentation
AddLoadThumbnailsFromPackageDelegate()
UNREALED_API FDelegateHandle ThumbnailTools::AddLoadThumbnailsFromPackageDelegate (FLoadThumbnailsFromPackage InDelegate)
Add delegate to handle loading of thumbnail from package.
References AddLoadThumbnailsFromPackageDelegate().
Referenced by AddLoadThumbnailsFromPackageDelegate().
AssetHasCustomCreatedThumbnail()
UNREALED_API bool ThumbnailTools::AssetHasCustomCreatedThumbnail (const FString & InAssetDataFullName)
Returns true if the given asset has a custom thumbnail cached or on the disk and if the thumbnail was captured from a viewport.
References AssetHasCustomCreatedThumbnail().
Referenced by AssetHasCustomCreatedThumbnail().
AssetHasCustomThumbnail() [1/2]
UNREALED_API bool ThumbnailTools::AssetHasCustomThumbnail (const FString & InAssetDataFullName)
Returns true if the given asset has a custom thumbnail cached or on the disk.
References AssetHasCustomThumbnail().
Referenced by AssetHasCustomThumbnail(), and AssetHasCustomThumbnail().
AssetHasCustomThumbnail() [2/2]
UNREALED_API bool ThumbnailTools::AssetHasCustomThumbnail (const FString & InAssetDataFullName, FObjectThumbnail & OutThumbnail)
References AssetHasCustomThumbnail().
CacheEmptyThumbnail()
UNREALED_API void ThumbnailTools::CacheEmptyThumbnail (const FString & ObjectFullName, UPackage * DestPackage)
Caches an empty thumbnail entry.
Parameters
ObjectFullName the full name for the object to associate with the thumbnail
DestPackage the package that will hold the cached thumbnail
References CacheEmptyThumbnail().
Referenced by CacheEmptyThumbnail().
CacheThumbnail()
UNREALED_API FObjectThumbnail * ThumbnailTools::CacheThumbnail (const FString & ObjectFullName, FObjectThumbnail * Thumbnail, UPackage * DestPackage)
Caches a thumbnail into a package's thumbnail map.
Parameters
ObjectFullName the full name for the object to associate with the thumbnail
Thumbnail the thumbnail to cache; specify NULL to remove the current cached thumbnail
DestPackage the package that will hold the cached thumbnail
Returns
pointer to the thumbnail data that was cached into the package
References CacheThumbnail().
Referenced by CacheThumbnail().
ConditionallyLoadThumbnailsForObjects()
UNREALED_API bool ThumbnailTools::ConditionallyLoadThumbnailsForObjects (const TArray< FName > & InObjectFullNames, FThumbnailMap & InOutThumbnails)
Loads thumbnails for the specified objects (or copies them from a cache, if they're already loaded.)
References ConditionallyLoadThumbnailsForObjects().
Referenced by ConditionallyLoadThumbnailsForObjects().
ConditionallyLoadThumbnailsFromPackage()
UNREALED_API bool ThumbnailTools::ConditionallyLoadThumbnailsFromPackage (const FString & InPackageFileName, const TSet< FName > & InObjectFullNames, FThumbnailMap & InOutThumbnails)
Loads thumbnails from a package unless they're already cached in that package's thumbnail map.
References ConditionallyLoadThumbnailsFromPackage().
Referenced by ConditionallyLoadThumbnailsFromPackage().
FindCachedThumbnail()
UNREALED_API const FObjectThumbnail * ThumbnailTools::FindCachedThumbnail (const FString & InFullName)
Searches for an object's thumbnail in memory and returns it if found.
References FindCachedThumbnail().
Referenced by FindCachedThumbnail().
GenerateThumbnailForObjectToSaveToDisk()
UNREALED_API FObjectThumbnail * ThumbnailTools::GenerateThumbnailForObjectToSaveToDisk (UObject * InObject)
Generates a thumbnail for the specified object and caches it.
Used to generate the thumbnail that gets saved in a package.
References GenerateThumbnailForObjectToSaveToDisk().
Referenced by GenerateThumbnailForObjectToSaveToDisk().
GetThumbnailForObject()
UNREALED_API FObjectThumbnail * ThumbnailTools::GetThumbnailForObject (UObject * InObject)
Returns the thumbnail for the specified object or NULL if one doesn't exist yet.
References GetThumbnailForObject().
Referenced by GetThumbnailForObject().
LoadThumbnailFromPackage()
UNREALED_API bool ThumbnailTools::LoadThumbnailFromPackage (const FAssetData & AssetData, FObjectThumbnail & OutThumbnail)
Loads the thumbnail of an asset from the specified package file name (or from the external thumbnail cache file if it exists)
References LoadThumbnailFromPackage().
Referenced by LoadThumbnailFromPackage().
LoadThumbnailsFromPackage()
UNREALED_API bool ThumbnailTools::LoadThumbnailsFromPackage (const FString & InPackageFileName, const TSet< FName > & InObjectFullNames, FThumbnailMap & InOutThumbnails)
Loads thumbnails from the specified package file name (or from the external thumbnail cache file if it exists)
References LoadThumbnailsFromPackage().
Referenced by LoadThumbnailsFromPackage().
LoadThumbnailsFromPackageDirectly()
UNREALED_API bool ThumbnailTools::LoadThumbnailsFromPackageDirectly (const FString & InPackageFileName, const TSet< FName > & InObjectFullNames, FThumbnailMap & InOutThumbnails, const FString & InPackageFileNameToOpen)
Loads thumbnails from the specified package file name (without using external thumbnail cache or delegates, only attempts to read from InPackageFileNameToOpen provided)
References LoadThumbnailsFromPackageDirectly().
Referenced by LoadThumbnailsFromPackageDirectly().
LoadThumbnailsFromPackageUsingExternalFolders()
UNREALED_API bool ThumbnailTools::LoadThumbnailsFromPackageUsingExternalFolders (const FString & InPackageFileName, const TSet< FName > & InObjectFullNames, FThumbnailMap & InOutThumbnails, TConstArrayView< FString > ExternalFolders)
Loads thumbnails from the specified package file name.
References LoadThumbnailsFromPackageUsingExternalFolders().
Referenced by LoadThumbnailsFromPackageUsingExternalFolders().
QueryPackageFileNameForObject()
UNREALED_API bool ThumbnailTools::QueryPackageFileNameForObject (const FString & InFullName, FString & OutPackageFileName)
Finds the file path/name of an existing package for the specified object full name, or false if the package is not valid.
References QueryPackageFileNameForObject().
Referenced by QueryPackageFileNameForObject().
RemoveLoadThumbnailsFromPackageDelegate()
UNREALED_API void ThumbnailTools::RemoveLoadThumbnailsFromPackageDelegate (const FDelegateHandle InHandle)
Remove delegate to handle loading of thumbnail from package.
References RemoveLoadThumbnailsFromPackageDelegate().
Referenced by RemoveLoadThumbnailsFromPackageDelegate().
RenderThumbnail()
UNREALED_API void ThumbnailTools::RenderThumbnail (UObject * InObject, const uint32 InImageWidth, const uint32 InImageHeight, EThumbnailTextureFlushMode::Type InFlushMode, FTextureRenderTargetResource * InRenderTargetResource = NULL, FObjectThumbnail * OutThumbnail = NULL)
Renders a thumbnail for the specified object.
Parameters
InObject the rendered thumbnail will represent this object
InImageWidth the maximum width of the thumbnail. It may be smaller when supplying a OutThumbnail.
InImageHeight the maximum height of the thumbnail. It may be smaller when supplying a OutThumbnail.
InRenderTargetResource if non-NULL, the render target that will receive the thumbnail.
OutThumbnail if non-NULL, the FObjectThumbnail that will receive the thumbnail data.
References RenderThumbnail().
Referenced by RenderThumbnail().
Variable Documentation
DefaultThumbnailSize
const int32 ThumbnailTools::DefaultThumbnailSize =256 inline
Standard thumbnail height setting used by generation.
Definition at line 801 of file ObjectTools.h.