Unreal Engine 5.6 C++ API: FStaticMeshSceneProxy Class Reference
FStaticMeshSceneProxy Class Reference
A static mesh component scene proxy.
#include "StaticMeshSceneProxy.h"
Data Structures
class FLODInfo
Information used by the proxy about a single LOD of the mesh.
class FRayTracingLODInfo
Information used by the proxy about a single ray tracing proxy LOD of the mesh.
Public Member Functions
FStaticMeshSceneProxy (const FStaticMeshSceneProxyDesc &InDesc, bool bForceLODsShareStaticLighting)
Initialization constructor.
FStaticMeshSceneProxy (UStaticMeshComponent *Component, bool bForceLODsShareStaticLighting)
Initialization constructor.
virtual ~FStaticMeshSceneProxy ()
virtual bool AllowInstanceCullingOcclusionQueries () const override
virtual bool CanBeOccluded () const override
virtual HHitProxy * CreateHitProxies (IPrimitiveComponent *ComponentInterface, TArray< TRefCountPtr< HHitProxy > > &OutHitProxies) override
Creates the hit proxies are used when DrawDynamicElements is called.
virtual HHitProxy * CreateHitProxies (UPrimitiveComponent *Component, TArray< TRefCountPtr< HHitProxy > > &OutHitProxies) override
All FPrimitiveSceneProxy derived classes can decide to fully override the HHitProxy creation, or add their own and call any of their base classes to add theirs.
virtual void CreateRenderThreadResources (FRHICommandListBase &RHICmdList) override
Called when the rendering thread adds the proxy to the scene.
virtual void DestroyRenderThreadResources () override
Called when the rendering thread removes the proxy from the scene.
virtual void DrawStaticElements (FStaticPrimitiveDrawInterface *PDI) override
Draws the primitive's static elements.
SIZE_T GetAllocatedSize (void) const
virtual bool GetCollisionMeshElement (int32 LODIndex, int32 BatchIndex, int32 ElementIndex, uint8 InDepthPriorityGroup, const FMaterialRenderProxy *RenderProxy, FMeshBatch &OutMeshBatch) const
Sets up a collision FMeshBatch for a specific LOD and element.
virtual uint8 GetCurrentFirstLODIdx_RenderThread () const final override
virtual FDesiredLODLevel GetDesiredLODLevel_RenderThread (const FSceneView *View) const final override
virtual void GetDistanceFieldAtlasData (const FDistanceFieldVolumeData *&OutDistanceFieldData, float &SelfShadowBias) const override
virtual void GetDynamicMeshElements (const TArray< const FSceneView * > &Views, const FSceneViewFamily &ViewFamily, uint32 VisibilityMap, FMeshElementCollector &Collector) const override
Gathers the primitive's dynamic mesh elements.
virtual bool GetInstanceWorldPositionOffsetDisableDistance (float &OutWPODisableDistance) const override
Retrieves the per-instance world position offset disable distance.
virtual void GetLCIs (FLCIArray &LCIs) override
virtual int32 GetLightMapCoordinateIndex () const override
Get the lightmap UV coordinate index for this primitive.
virtual void GetLightRelevance (const FLightSceneProxy *LightSceneProxy, bool &bDynamic, bool &bRelevant, bool &bLightMapped, bool &bShadowMapped) const override
Determines the relevance of this primitive's elements to the given light.
virtual int32 GetLOD (const FSceneView *View) const override
Returns the LOD that the primitive will render at for this view.
FLODMask GetLODMask (const FSceneView *View) const
Returns the LOD mask for a view, this is like the ordinary LOD but can return two values for dither fading.
virtual FUintVector2 GetMaterialCacheTextureDescriptor () const override
virtual uint32 GetMemoryFootprint (void) const override
Every derived class should override these functions.
virtual const FCardRepresentationData * GetMeshCardRepresentation () const override
virtual void GetMeshDescription (int32 LODIndex, TArray< FMeshBatch > &OutMeshElements) const override
Gathers a description of the mesh elements to be rendered for the given LOD index, without consideration for views.
virtual bool GetMeshElement (int32 LODIndex, int32 BatchIndex, int32 SectionIndex, uint8 InDepthPriorityGroup, bool bUseSelectionOutline, bool bAllowPreCulledIndices, FMeshBatch &OutMeshBatch) const
Sets up a FMeshBatch for a specific LOD and element.
virtual FUintVector2 GetMeshPaintTextureDescriptor () const override
virtual int32 GetNumMeshBatches () const
Gets the number of mesh batches required to represent the proxy, aside from section needs.
virtual bool GetRayTracingMeshElement (int32 LODIndex, int32 BatchIndex, int32 SectionIndex, uint8 InDepthPriorityGroup, FMeshBatch &OutMeshBatch) const
Sets up a ray tracing FMeshBatch for a specific LOD.
float GetScreenSize (int32 LODIndex) const
Returns the display factor for the given LOD level.
virtual bool GetShadowMeshElement (int32 LODIndex, int32 BatchIndex, uint8 InDepthPriorityGroup, FMeshBatch &OutMeshBatch, bool bDitheredLODTransition) const
Sets up a shadow FMeshBatch for a specific LOD.
virtual void GetStreamableRenderAssetInfo (const FBoxSphereBounds &InPrimitiveBounds, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamableRenderAssets) const override
SIZE_T GetTypeHash () const override
Return a type (or subtype) specific hash for sorting purposes.
virtual FPrimitiveViewRelevance GetViewRelevance (const FSceneView *View) const override
Determines the relevance of this primitive's elements to the given view.
virtual bool GetWireframeMeshElement (int32 LODIndex, int32 BatchIndex, const FMaterialRenderProxy *WireframeRenderProxy, uint8 InDepthPriorityGroup, bool bAllowPreCulledIndices, FMeshBatch &OutMeshBatch) const
Sets up a wireframe FMeshBatch for a specific LOD.
virtual bool HasDistanceFieldRepresentation () const override
virtual bool HasDynamicIndirectShadowCasterRepresentation () const override
virtual bool IsCullingReversedByComponent () const override
virtual bool IsUsingDistanceCullFade () const override
virtual void SetEvaluateWorldPositionOffsetInRayTracing (FRHICommandListBase &RHICmdList, bool bEvaluate)
virtual bool StaticMeshHasPendingStreaming () const override
Public Member Functions inherited from FPrimitiveSceneProxy
FPrimitiveSceneProxy (const FPrimitiveSceneProxyDesc &InDesc, FName ResourceName=NAME_None)
FPrimitiveSceneProxy (const UPrimitiveComponent *InComponent, FName ResourceName=NAME_None)
Initialization constructor.
FPrimitiveSceneProxy (FPrimitiveSceneProxy const &)
Copy constructor.
virtual ~FPrimitiveSceneProxy ()
Virtual destructor.
virtual void AcceptOcclusionResults (const FSceneView *View, TArray< bool > *Results, int32 ResultsStart, int32 NumResults)
Gives the primitive the results of sub-occlusion-queries.
bool AffectsDistanceFieldLighting () const
bool AffectsDynamicIndirectLighting () const
bool AffectsIndirectLightingWhileHidden () const
bool AllowApproximateOcclusion () const
bool AlwaysHasVelocity () const
Returns true if this proxy should write velocity even when the transform isn't changing.
bool AnyMaterialAlwaysEvaluatesWorldPositionOffset () const
bool AnyMaterialHasPixelAnimation () const
bool AnyMaterialHasWorldPositionOffset () const
virtual void ApplyLateUpdateTransform (FRHICommandListBase &RHICmdList, const FMatrix &LateUpdateTransform)
Applies a "late in the frame" adjustment to the proxy's existing transform.
virtual void ApplyViewDependentMeshArguments (const FSceneView &View, FMeshBatch &ViewDependentMeshBatch) const
Gives the primitive an opportunity to override MeshBatch arguments for a specific View Only called for a MeshBatch with a bViewDependentArguments property set.
virtual void ApplyWorldOffset (FRHICommandListBase &RHICmdList, FVector InOffset)
Shifts primitive position and all relevant data by an arbitrary delta.
void BuildUniformShaderParameters (FPrimitiveUniformShaderParametersBuilder &Builder) const
Apply the unform shader parameter settings for the proxy to the builder.
bool CanSkipRedundantTransformUpdates () const
bool CastsCapsuleDirectShadow () const
bool CastsCinematicShadow () const
bool CastsContactShadow () const
bool CastsDeepShadow () const
bool CastsDynamicIndirectShadow () const
bool CastsDynamicShadow () const
bool CastsFarShadow () const
bool CastsHiddenShadow () const
bool CastsInsetShadow () const
bool CastsSelfShadowOnly () const
bool CastsShadowAsTwoSided () const
bool CastsStaticShadow () const
bool CastsVolumetricTranslucentShadow () const
bool DoesMeshBatchesUseSceneInstanceCount () const
Returns true to inform scene update that the mesh batches produced makes use of the (GPU)Scene instance count, and thus don't require recaching if the instance count changed.
bool DoesVFRequirePrimitiveUniformBuffer () const
bool DrawsVelocity () const
Returns true if this proxy can write velocity.
bool EvaluateWorldPositionOffset () const
virtual void GatherSimpleLights (const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const
Callback from the renderer to gather simple lights that this proxy wants renderered.
float GetAbsMaxDisplacement () const
const FVector & GetActorPosition () const
SIZE_T GetAllocatedSize (void) const
const FBoxSphereBounds & GetBounds () const
uint8 GetCustomDepthStencilValue () const
virtual const FColorVertexBuffer * GetCustomHitProxyIdBuffer () const
Allows a scene proxy to override hit proxy ids and generate more than one hit proxy id per draw call Useful for sub-section selection (faces, vertices, bones, etc)
virtual FBoxSphereBounds GetCustomOcclusionBounds () const
Return the custom occlusion bounds for this scene proxy.
const FCustomPrimitiveData * GetCustomPrimitiveData () const
Get the custom primitive data for this scene proxy.
ESceneDepthPriorityGroup GetDepthPriorityGroup (const FSceneView *View) const
Determines the DPG to render the primitive in for the given view.
virtual void GetDistanceFieldAtlasData (const class FDistanceFieldVolumeData *&OutDistanceFieldData, float &SelfShadowBias) const
float GetDynamicIndirectShadowMinVisibility () const
virtual float GetGpuLodInstanceRadius () const
Returns the instance radius to use for per instance GPU LOD calculation.
virtual void GetHeightfieldRepresentation (UTexture2D *&OutHeightmapTexture, UTexture2D *&OutVisibilityTexture, FHeightfieldComponentDescription &OutDescription) const
EIndirectLightingCacheQuality GetIndirectLightingCacheQuality () const
FInstanceDataBufferHeader GetInstanceDataHeader () const
virtual FInstanceDataUpdateTaskInfo * GetInstanceDataUpdateTaskInfo () const
Return a pointer to a class that can be used to guard access to instance data that is being updated by a task.
virtual bool GetInstanceDrawDistanceMinMax (FVector2f &OutDistanceMinMax) const
Retrieves the instance draw distance range (mostly only used by objects whose instances are culled on the GPU)
const FInstanceSceneDataBuffers * GetInstanceSceneDataBuffers (EInstanceBufferAccessFlags AccessFlags=EInstanceBufferAccessFlags::SynchronizeUpdateTask) const
Get the instance data view, which may be null for uninstanced primitives.
FName GetLevelName () const
uint8 GetLightingChannelMask () const
uint8 GetLightingChannelStencilValue () const
virtual int32 GetLightMapResolution () const
Get the lightmap resolution for this primitive.
ELightmapType GetLightmapType () const
const FBoxSphereBounds & GetLocalBounds () const
const FMatrix & GetLocalToWorld () const
virtual float GetLodScreenSizeScale () const
Returns a scale to apply to ScreenSize used in LOD calculation.
float GetMaxDrawDistance () const
float GetMaxWorldPositionOffsetExtent () const
FName GetMeshDrawCommandStatsCategory () const
float GetMinDrawDistance () const
const FVector2f & GetMinMaxMaterialDisplacement () const
virtual void GetNaniteResourceInfo (uint32 &ResourceID, uint32 &HierarchyOffset, uint32 &AssemblyTransformOffset, uint32 &ImposterIndex) const
int32 GetNumUncachedStaticLightingInteractions ()
virtual const TArray< FBoxSphereBounds > * GetOcclusionQueries (const FSceneView *View) const
Gets the boxes for sub occlusion queries.
FColor GetOverlayColor () const
FName GetOwnerName () const
virtual void GetPreSkinnedLocalBounds (FBoxSphereBounds &OutBounds) const
FLinearColor GetPrimitiveColor () const
FPrimitiveComponentId GetPrimitiveComponentId () const
FPrimitiveSceneInfo * GetPrimitiveSceneInfo () const
uint8 GetRayTracingGroupCullingPriority () const
int32 GetRayTracingGroupId () const
virtual FRenderCurveResourceData * GetRenderCurveResourceData ()
FName GetResourceName () const
const TArray< int32 > & GetRuntimeVirtualTextureIds () const
FSceneInterface & GetScene () const
uint8 GetSelectionOutlineColorIndex () const
EShadowCacheInvalidationBehavior GetShadowCacheInvalidationBehavior () const
virtual void GetShadowShapes (FVector PreViewTranslation, TArray< FCapsuleShape3f > &OutCapsuleShapes) const
Gathers shadow shapes from this proxy.
virtual TConstArrayView< FPrimitiveComponentId > GetSourceLandscapeComponentIds () const
virtual ESceneDepthPriorityGroup GetStaticDepthPriorityGroup () const
Determines the DPG to render the primitive in regardless of view.
FORCEINLINE TStatId GetStatId () const
EStencilMask GetStencilWriteMask () const
float GetTranslucencySortDistanceOffset () const
int16 GetTranslucencySortPriority () const
FRHIUniformBuffer * GetUniformBuffer () const
int32 GetVirtualTextureCullMips () const
int32 GetVirtualTextureLodBias () const
int32 GetVirtualTextureMinCoverage () const
int32 GetVisibilityId () const
FLinearColor GetWireframeColor () const
virtual bool HasCustomOcclusionBounds () const
Returns whether the proxy utilizes custom occlusion bounds or not.
bool HasDeformableMesh () const
Returns true if this proxy has any deformable mesh, meaning the mesh is animated e.g., by deforming the vertices through skinning, morphing or some procedural update.
bool HasDynamicTransform () const
Returns true if this proxy can change transform so that we should cache previous transform for calculating velocity.
bool HasInstanceDataBuffers () const
bool HasPerInstanceHitProxies () const
bool HasStaticLighting () const
virtual bool HasSubprimitiveOcclusionQueries () const
bool HasValidSettingsForStaticLighting () const
bool HasViewDependentDPG () const
virtual bool HeightfieldHasPendingStreaming () const
bool Holdout () const
bool IsAlwaysVisible () const
Returns whether this proxy is always visible.
bool IsCollisionEnabled () const
bool IsCompatibleWithLumenCardSharing () const
virtual bool IsDetailMesh () const
Returns whether this proxy should be considered a "detail mesh".
FORCEINLINE bool IsDrawnInEditor () const
Tell us if this proxy is drawn in editor.
FORCEINLINE bool IsDrawnInGame () const
Tell us if this proxy is drawn in game.
bool IsEditingLevelInstanceChild () const
bool IsEmissiveLightSource () const
bool IsFirstPerson () const
bool IsFirstPersonWorldSpaceRepresentation () const
bool IsForceHidden () const
bool IsForceMipStreaming () const
bool IsHeterogeneousVolume () const
Returns whether this proxy is a heterogeneous volume.
bool IsHiddenInSceneCapture () const
bool IsHovered () const
bool IsIndividuallySelected () const
bool IsInstanceDataGPUOnly () const
Whether instance data only exists in the GPU Scene (instance data not present in CPU memory).
bool IsLandscapeNaniteProxy () const
bool IsLocalToWorldDeterminantNegative () const
bool IsMeshShapeOftenMoving () const
bool IsMovable () const
bool IsNaniteMesh () const
Returns whether this proxy is a Nanite mesh.
bool IsOftenMoving () const
bool IsOpaqueOrMasked () const
bool IsOwnedBy (const FSceneViewOwner &Owner) const
bool IsParentSelected () const
bool IsRayTracingFarField () const
bool IsSelectable () const
bool IsSelected () const
bool IsShadowCast (const FSceneView *View) const
bool IsShown (const FSceneView *View) const
bool IsSkinnedMesh () const
bool IsSplineMesh () const
bool IsStatic () const
bool IsSupportingStreamableRenderAssetsGathering () const
bool IsVisibleInLumenScene () const
bool IsVisibleInRayTracing () const
bool IsVisibleInRealTimeSkyCaptures () const
bool IsVisibleInReflectionCaptures () const
bool IsVisibleInSceneCaptureOnly () const
bool LightAttachmentsAsGroup () const
bool NeedsUnbuiltPreviewLighting () const
virtual void OnDetachLight (const FLightSceneInfo *Light)
Called by the rendering thread to notify the proxy when a light is no longer associated with the proxy, so that it can clean up any cached resources.
virtual void OnTransformChanged (FRHICommandListBase &RHICmdList)
Called to notify the proxy when its transform has been updated.
const bool ReceivesDecals () const
void RenderBounds (FPrimitiveDrawInterface *PDI, const FEngineShowFlags &EngineShowFlags, const FBoxSphereBounds &Bounds, bool bRenderInEditor) const
Helper for components that want to render bounds.
void ResetSceneVelocity_GameThread ()
Enqueue and update for the render thread to remove the velocity data for this component from the scene.
void SetCanSkipRedundantTransformUpdates (bool bCanSkip)
Set whether the proxy can skip redundant transform updates where applicable.
void SetCollisionEnabled_GameThread (const bool bNewEnabled)
Set the collision flag on the scene proxy to enable/disable collision drawing.
void SetCollisionEnabled_RenderThread (const bool bNewEnabled)
Set the collision flag on the scene proxy to enable/disable collision drawing (RENDER THREAD)
void SetCustomDepthEnabled_GameThread (const bool bInRenderCustomDepth)
Set the custom depth enabled flag.
void SetCustomDepthEnabled_RenderThread (const bool bInRenderCustomDepth)
Set the custom depth enabled flag (RENDER THREAD)
void SetCustomDepthStencilValue_GameThread (const int32 InCustomDepthStencilValue)
Set the custom depth stencil value.
void SetCustomDepthStencilValue_RenderThread (const int32 InCustomDepthStencilValue)
Set the custom depth stencil value (RENDER THREAD)
virtual void SetDebugMassData (const TArray< FDebugMassData > &InDebugMassData)
Sets the primitive proxy's mass space to component space.
void SetDistanceFieldSelfShadowBias_RenderThread (float NewBias)
void SetDrawDistance_RenderThread (float MinDrawDistance, float MaxDrawDistance, float VirtualTextureMaxDrawDistance)
void SetDrawnInGame_RenderThread (bool bInDrawInGame)
Set the drawn in game flag, from the render thread.
void SetEvaluateWorldPositionOffset_GameThread (bool bEvaluate)
Enqueue updated setting for evaluation of World Position Offset.
void SetHiddenEdViews_GameThread (uint64 InHiddenEditorViews)
Updates the hidden editor view visibility map on the game thread which just enqueues a command on the render thread.
void SetHovered_GameThread (const bool bInHovered)
Updates hover state for the primitive proxy.
virtual void SetInstanceCullDistance_RenderThread (float StartCullDistance, float EndCullDistance)
void SetIsBeingMovedByEditor_GameThread (bool bIsBeingMoved)
Enqueue and update for the render thread to notify it that the editor is currently moving the owning component with gizmos.
void SetLevelInstanceEditingState_GameThread (const bool bInEditingState)
Updates the LevelInstance editing state for the primitive proxy.
void SetLightingChannels_GameThread (FLightingChannels LightingChannels)
Updates the lighting channels for the primitive proxy.
void SetOverlayColor_GameThread (FColor OverlayColor)
Enqueue updated overlay color for the render thread to use.
void SetPrimitiveColor (const FLinearColor &InPrimitiveColor)
void SetPrimitiveColor_GameThread (const FLinearColor &InPrimitiveColor)
Enqueue and update for the render thread to notify it that the primitive color changed.
void SetSelection_GameThread (const bool bInParentSelected, const bool bInIndividuallySelected=false)
Updates selection for the primitive proxy.
void SetSelectionOutlineColorIndex_GameThread (uint8 ColorIndex)
Enqueue updated selection outline color for the render thread to use.
void SetSelectionOverride_GameThread (bool bForceSelection)
Force the proxy to render as though it is selected.
void SetUsedMaterialForVerification (const TArray< UMaterialInterface * > &InUsedMaterialsForVerification)
This function exist only to perform an update of the UsedMaterialsForVerification on the render thread.
void SetWireframeColor (const FLinearColor &InWireframeColor)
virtual void SetWorldPositionOffsetDisableDistance_GameThread (int32 NewValue)
bool ShouldNotifyOnWorldAddRemove () const
bool ShouldReceiveMobileCSMShadows () const
bool ShouldRenderCustomDepth () const
bool ShouldRenderInDepthPass () const
bool ShouldRenderInMainPass () const
bool ShouldUseAsOccluder () const
virtual bool ShowInBSPSplitViewmode () const
bool SinglePassGDME () const
bool StaticElementsAlwaysUseProxyPrimitiveUniformBuffer () const
bool SupportsDistanceFieldRepresentation () const
bool SupportsGPUScene () const
Returns true if all meshes drawn by this proxy support GPU scene.
bool SupportsHeightfieldRepresentation () const
bool SupportsInstanceDataBuffer () const
bool SupportsMaterialCache () const
bool SupportsParallelGDME () const
bool SupportsParallelGDRTI () const
bool SupportsSortedTriangles () const
bool TreatAsBackgroundForOcclusion () const
UE_DEPRECATED (5.4, "Use generic instance data through GetInstanceSceneDataBuffers().") virtual void GetDistanceFieldInstanceData(TArray< FRenderTransform > &InstanceLocalToPrimitiveTransforms) const final
UE_DEPRECATED (5.6, "Use GetRuntimeVirtualTextureIds() instead.") inline bool WritesVirtualTexture(URuntimeVirtualTexture *VirtualTexture) const
void UpdateUniformBuffer (FRHICommandList &RHICmdList)
Updates the primitive proxy's uniform buffer.
bool UseEditorCompositing (const FSceneView *View) const
bool UseSingleSampleShadowFromStationaryLights () const
bool VerifyUsedMaterial (const class FMaterialRenderProxy *MaterialRenderProxy) const
Verifies that a material used for rendering was present in the component's GetUsedMaterials list.
bool WantsEditorEffects () const
bool WantsSelectionOutline () const
bool WillEverBeLit () const
bool WritesVirtualTexture () const
Static Public Member Functions
static void GetRayTracingWPOConfig (bool &bOutHasRayTracingRepresentation, bool &bOutDynamicRayTracingGeometry)
static bool ShouldEvaluateWPOInRayTracing (FVector ViewCenter, const FBoxSphereBounds &Bounds)
Static Public Member Functions inherited from FPrimitiveSceneProxy
static void DrawArc (FPrimitiveDrawInterface *PDI, const FVector &Start, const FVector &End, const float Height, const uint32 Segments, const FLinearColor &Color, uint8 DepthPriorityGroup, const float Thickness=0.0f, const bool bScreenSpace=false)
Drawing helper.
static void DrawArrowHead (FPrimitiveDrawInterface *PDI, const FVector &Tip, const FVector &Origin, const float Size, const FLinearColor &Color, uint8 DepthPriorityGroup, const float Thickness=0.0f, const bool bScreenSpace=false)
Protected Member Functions
uint8 GetCurrentFirstLODIdx_Internal () const
Only call on render thread timeline.
bool IsCollisionView (const FEngineShowFlags &EngineShowFlags, bool &bDrawSimpleCollision, bool &bDrawComplexCollision) const
bool IsReversedCullingNeeded (bool bUseReversedIndices) const
Returns whether this mesh needs reverse culling when using reversed indices.
virtual void OnEvaluateWorldPositionOffsetChanged_RenderThread () override
Allows child implementations to do render-thread work when bEvaluateWorldPositionOffset changes.
uint32 SetMeshElementGeometrySource (const FStaticMeshSection &Section, const FRawStaticIndexBuffer &IndexBuffer, const FAdditionalStaticMeshIndexBuffers *AdditionalIndexBuffers, const FVertexFactory *VertexFactory, bool bWireframe, bool bUseInversedIndices, FMeshBatch &OutMeshElement) const
Configures mesh batch vertex / index state.
void SetMeshElementScreenSize (int32 LODIndex, bool bDitheredLODTransition, FMeshBatch &OutMeshBatch) const
Sets the screen size on a mesh element.
bool ShouldRenderBackFaces () const
Returns whether this mesh should render back-faces instead of front-faces - either with reversed indices or reversed cull mode.
UE_DEPRECATED (5.6, "Provide FStaticMeshSection, IndexBuffer and AdditionalIndexBuffers instead of LODIndex, etc.") 1 uint32 SetMeshElementGeometrySource(int32 LODIndex
Protected Member Functions inherited from FPrimitiveSceneProxy
bool DrawInRuntimeVirtualTextureOnly (bool bEditor) const
Returns true if a primitive should currently be hidden because it is drawn only to the runtime virtual texture.
void EnableGPUSceneSupportFlags ()
Call during setup to set flags to indicate GPU-Scene support for the proxy if GPU-Scene is enabled & supported for the current feature level.
bool IsRuntimeVirtualTextureOnly () const
Returns true if a primitive can never be rendered outside of a runtime virtual texture.
virtual void OnForceHiddenChanged ()
void OnLevelAddedToWorld_RenderThread ()
Called to notify the proxy that the level has been fully added to the world and the primitive will now be rendered.
void OnLevelRemovedFromWorld_RenderThread ()
Called to notify the proxy that the level has been fully removed from the world and the primitive will not be rendered.
void OverrideOwnerName (FName InOwnerName)
Allow subclasses to override the primitive name.
FRenderBounds PadInstanceLocalBounds (const FRenderBounds &InBounds)
void SetForceHidden (bool bForceHiddenIn)
void SetHovered_RenderThread (const bool bInHovered)
Updates hover state for the primitive proxy.
void SetLevelInstanceEditingState_RenderThread (const bool bInLevelInstanceEditingState)
Updates LevelInstance editing state for the primitive proxy.
void SetSelection_RenderThread (const bool bInParentSelected, const bool bInIndividuallySelected)
Updates selection for the primitive proxy.
void SetupInstanceSceneDataBuffers (const FInstanceSceneDataBuffers *InInstanceSceneDataBuffers)
UE_DEPRECATED (5.6, "StaticMeshBounds is no longer a parameter of this interface, please update the implementation.") 1 virtual void UpdateInstances_RenderThread(FRHICommandListBase &RHICmdList
Called on the render thread for a proxy that has an instance data update, the buffers are updated asynchronously so it is unclear what this should do, except update legacy data if needed.
virtual void UpdateInstances_RenderThread (FRHICommandListBase &RHICmdList, const FBoxSphereBounds &InBounds, const FBoxSphereBounds &InLocalBounds)
void UpdateVisibleInLumenScene ()
Updates bVisibleInLumen, which indicated whether a primitive should be tracked by Lumen scene.
Protected Attributes
int32 bool bool bool bAllowPreCulledIndices
uint32 bCastShadow: 1
uint32 bReverseCulling: 1
This primitive has culling reversed.
int32 bool bool bUseInversedIndices
int32 bool bWireframe
const FCardRepresentationData * CardRepresentationData
int32 ClampedMinLOD
Minimum LOD index to use.
int32 bool bool bool const FVertexFactory FMeshBatch &OutMeshElement const
const FDistanceFieldVolumeData * DistanceFieldData
int32 ElementIndex
int32 ForcedLodModel
The forcedLOD set in the static mesh editor, copied from the mesh component.
TArray< FLODInfo > LODs
FMaterialRelevance MaterialRelevance
The view relevance for all the static mesh's materials.
TArray< TObjectPtr< UMaterialInterface > > MaterialSlotsOverlayMaterial
uint32 MeshPaintTextureCoordinateIndex: 2
The coordinate index to use for texture color painting.
UMaterialInterface * OverlayMaterial
float OverlayMaterialMaxDrawDistance
TArray< FRayTracingLODInfo > RayTracingLODInfos
FStaticMeshRenderData * RenderData
int32 bool bool bool const FVertexFactory * VertexFactory
float WPODisableDistance
The distance at which to disable World Position Offset (0 = no max).
Protected Attributes inherited from FPrimitiveSceneProxy
uint8 bAffectDistanceFieldLighting: 1
uint8 bAffectDynamicIndirectLighting: 1
True if the primitive influences dynamic indirect lighting.
uint8 bAffectIndirectLightingWhileHidden: 1
True if the primitive should affect indirect lighting even when hidden.
uint8 bAllowApproximateOcclusion: 1
If this is True, this primitive doesn't need exact occlusion info.
uint8 bAlwaysHasVelocity: 1
Whether the primitive should always be considered to have velocities, even if it hasn't moved.
uint8 bAnyMaterialAlwaysEvaluatesWorldPositionOffset: 1
Whether the primitive has any materials that must ALWAYS evaluate World Position Offset.
uint8 bAnyMaterialHasPixelAnimation: 1
Whether the primitive has any materials that must ALWAYS evaluate World Position Offset.
uint8 bAnyMaterialHasWorldPositionOffset: 1
Whether the primitive has any materials with World Position Offset.
uint8 bCanSkipRedundantTransformUpdates: 1
Whether this component can skip redundant transform updates where applicable.
uint8 bCastCapsuleDirectShadow: 1
Whether the primitive should use capsules for direct shadowing, if present.
uint8 bCastCinematicShadow: 1
Whether this component should create a per-object shadow that gives higher effective shadow resolution.
uint8 bCastContactShadow: 1
Whether the object should cast a contact shadow.
uint8 bCastDeepShadow: 1
Whether the object should cast a deep shadow.
uint8 bCastDynamicShadow: 1
True if the primitive casts dynamic shadows.
uint8 bCastFarShadow: 1
uint8 bCastHiddenShadow: 1
True if the primitive casts shadows even when hidden.
uint8 bCastInsetShadow: 1
Whether this component should create a per-object shadow that gives higher effective shadow resolution.
uint8 bCastsDynamicIndirectShadow: 1
Whether the primitive should use an inset indirect shadow from capsules or mesh distance fields.
uint8 bCastShadowAsTwoSided: 1
Whether this primitive should cast dynamic shadows as if it were a two sided material.
uint8 bCastStaticShadow: 1
True if the primitive casts static shadows.
uint8 bCastVolumetricTranslucentShadow: 1
Whether the object should cast a volumetric translucent shadow.
uint8 bCompatibleWithLumenCardSharing: 1
Whether Lumen cards of this primitive can be shared.
uint8 bDoesMeshBatchesUseSceneInstanceCount: 1
Set to true to inform scene update that the MDCs produced may use the (GPU)Scene instance count, and thus don't require recaching if the instance count changed.
uint8 bEmissiveLightSource: 1
Whether the primitive will be used as an emissive light source.
uint8 bEvaluateWorldPositionOffset: 1
Whether the primitive should evaluate any World Position Offset.
uint8 bGoodCandidateForCachedShadowmap: 1
Whether this proxy's mesh is unlikely to be constantly changing.
uint8 bHasDeformableMesh: 1
True if the mesh representation is deformable (see HasDeformableMesh() above for more details).
uint8 bHasValidSettingsForStaticLighting: 1
True if the primitive wants to use static lighting, but has invalid content settings to do so.
uint8 bHasWorldPositionOffsetVelocity: 1
Whether the primitive has any materials with World Position Offset, and some conditions around velocity are met.
uint8 bHoldout: 1
If this is True, this primitive should render black with an alpha of 0, but all secondary effects (shadows, refletions, indirect lighting) should behave as usual.
uint8 bImplementsStreamableAssetGathering: 1
This is only set to true by constructors of proxy types witch support gathering of UStreamableAssets.
uint8 bIsAlwaysVisible: 1
Whether this proxy is always visible.
uint8 bIsFirstPerson: 1
If this is True, this primitive is to be rendered as a first person view object.
uint8 bIsFirstPersonWorldSpaceRepresentation: 1
If this is True, this primitive represents another first person primitive in world space.
uint8 bIsHeterogeneousVolume: 1
Whether this proxy is a heterogeneous volume.
uint8 bIsHierarchicalInstancedStaticMesh: 1
Whether the primitive is a HierarchicalInstancedStaticMesh.
uint8 bIsLandscapeGrass: 1
Whether the primitive is landscape grass.
uint8 bIsLandscapeNaniteProxy: 1
Whether this is FLandscapeNaniteSceneProxy and implements GetSourceLandscapeComponentIds().
uint8 bIsNaniteMesh: 1
Whether this proxy is a Nanite mesh.
uint8 bIsStaticMesh: 1
Whether this proxy is a static mesh.
uint8 bLightAttachmentsAsGroup: 1
Whether to light this component and any attachments as a group.
uint8 bNeedsUnbuiltPreviewLighting: 1
Whether the primitive should be statically lit but has unbuilt lighting, and a preview should be used.
uint8 bOpaqueOrMasked: 1
Whether this component contains opaque materials (cached once from assigned material).
uint8 bSelfShadowOnly: 1
When enabled, the component will only cast a shadow on itself and not other components in the world.
uint8 bShouldNotifyOnWorldAddRemove: 1
Whether this primitive requires notification when its level is added to the world and made visible for the first time.
uint8 bSinglePassGDME: 1
Whether to call GetDynamicMeshElements a single time, instead of once per unique FSceneViewFamily.
uint8 bSingleSampleShadowFromStationaryLights: 1
Whether the whole component should be shadowed as one from stationary lights, which makes shadow receiving much cheaper.
uint8 bSkinnedMesh: 1
If this is True, this primitive is a skinned mesh.
uint8 bSplineMesh: 1
If this is True, this primitive is a spline mesh.
uint8 bStaticElementsAlwaysUseProxyPrimitiveUniformBuffer: 1
Whether this proxy always uses UniformBuffer and no other uniform buffers.
uint8 bSupportsDistanceFieldRepresentation: 1
Whether the primitive type supports a distance field representation.
uint8 bSupportsGPUScene: 1
True if all meshes (AKA all vertex factories) drawn by this proxy support GPU scene (default is false).
uint8 bSupportsHeightfieldRepresentation: 1
Whether the primitive implements GetHeightfieldRepresentation()
uint8 bSupportsMaterialCache: 1
uint8 bSupportsParallelGDME: 1
Whether the proxy supports asynchronously calling GetDynamicMeshElements.
uint8 bSupportsParallelGDRTI: 1
Whether the proxy supports asynchronously calling GetDynamicRayTracingInstances.
uint8 bSupportsRuntimeVirtualTexture: 1
This is only set true by the constructors of proxy types which support writing to runtime virtual texture.
uint8 bSupportsSortedTriangles: 1
Whether the object support triangles when rendered with translucent material.
uint8 bVerifyUsedMaterials: 1
uint8 bVFRequiresPrimitiveUniformBuffer: 1
Whether this proxy ever draws with vertex factories that require a primitive uniform buffer.
uint8 bVisibleInLumenScene: 1
Whether this component should be tracked by Lumen Scene.
uint8 bWantsEditorEffects: 1
False by default, if true the proxy wants editor-only effects like outlines and overlays.
uint8 bWantsSelectionOutline: 1
true by default, if set to false will make given proxy never drawn with selection outline
uint8 bWillEverBeLit: 1
Can be set to false to skip some work only needed on lit primitives.
FMaterialRelevance CombinedMaterialRelevance
Cached material relevance available for GetMaterialRelevance call.
float DistanceFieldSelfShadowBias
float DynamicIndirectShadowMinVisibility
Min visibility for capsule shadows.
const FBoxSphereBounds const FBoxSphereBounds const FBoxSphereBounds &InStaticMeshBounds final
const FBoxSphereBounds & InBounds
TEnumAsByte< EIndirectLightingCacheQuality > IndirectLightingCacheQuality
Quality of interpolated indirect lighting for Movable components.
const FBoxSphereBounds const FBoxSphereBounds & InLocalBounds
float MaxDrawDistance
The primitive's cull distance.
float MaxWPOExtent
Maximum distance of World Position Offset used by materials.
float MinDrawDistance
The primitive's minimum cull distance.
FVector2f MinMaxMaterialDisplacement
TArray< ERuntimeVirtualTextureMaterialType > RuntimeVirtualTextureMaterialTypes
Set of unique runtime virtual texture material types referenced by RuntimeVirtualTextures.
TArray< int32 > RuntimeVirtualTextures
Array of runtime virtual textures unique ids that this proxy should render to.
EShadowCacheInvalidationBehavior ShadowCacheInvalidationBehavior
int8 VirtualTextureCullMips
Number of low mips to skip when rendering to runtime virtual texture.
int8 VirtualTextureLodBias
Geometry Lod bias when rendering to runtime virtual texture.
int8 VirtualTextureMinCoverage
Log2 of minimum estimated pixel coverage before culling from runtime virtual texture.
Private Member Functions
void AddSpeedTreeWind ()
void RemoveSpeedTreeWind ()
Private Attributes
FUintVector2 MaterialCacheTextureDescriptor = FUintVector2(0, 0)
FTextureResource * MaterialCacheTextureResource = nullptr
FUintVector2 MeshPaintTextureDescriptor = FUintVector2(0, 0)
FTextureResource * MeshPaintTextureResource = nullptr
const UStaticMesh * StaticMesh
Additional Inherited Members
Public Types inherited from FPrimitiveSceneProxy
enum class EInstanceBufferAccessFlags { SynchronizeUpdateTask , UnsynchronizedAndUnsafe }
typedef TArray< class FLightCacheInterface *, TInlineAllocator< 8 > > FLCIArray
Get the list of LCIs.
Data Fields inherited from FPrimitiveSceneProxy
TArray< FDebugMassData > DebugMassData
TSharedPtr< int32, ESPMode::ThreadSafe > SimpleStreamableAssetManagerIndex = MakeShared<int32, ESPMode::ThreadSafe>(INDEX_NONE)
Static Public Attributes inherited from FPrimitiveSceneProxy
static constexpr int32 InvalidRayTracingGroupId = -1
Detailed Description
A static mesh component scene proxy.
Definition at line 30 of file StaticMeshSceneProxy.h.
Constructor & Destructor Documentation
FStaticMeshSceneProxy() [1/2]
FStaticMeshSceneProxy::FStaticMeshSceneProxy (UStaticMeshComponent * Component, bool bForceLODsShareStaticLighting)
Initialization constructor.
References Component.
FStaticMeshSceneProxy() [2/2]
FStaticMeshSceneProxy::FStaticMeshSceneProxy (const FStaticMeshSceneProxyDesc & InDesc, bool bForceLODsShareStaticLighting)
Initialization constructor.
~FStaticMeshSceneProxy()
virtual FStaticMeshSceneProxy::~FStaticMeshSceneProxy () virtual
Member Function Documentation
AddSpeedTreeWind()
void FStaticMeshSceneProxy::AddSpeedTreeWind () private
AllowInstanceCullingOcclusionQueries()
virtual bool FStaticMeshSceneProxy::AllowInstanceCullingOcclusionQueries () const inline override virtual
Returns
true if per-pixel visibility tests are allowed for instances of this primitive during GPU instance culling. This may yield significant performance benefit for some cases, such as relatively high-poly instanced static meshes.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FHierarchicalStaticMeshSceneProxy.
Definition at line 146 of file StaticMeshSceneProxy.h.
CanBeOccluded()
virtual bool FStaticMeshSceneProxy::CanBeOccluded () const override virtual
Returns
true if the proxy can be culled when occluded by other primitives
Reimplemented from FPrimitiveSceneProxy.
CreateHitProxies() [1/2]
virtual HHitProxy * FStaticMeshSceneProxy::CreateHitProxies (IPrimitiveComponent * ComponentInterface, TArray< TRefCountPtr< HHitProxy > > & OutHitProxies) override virtual
Creates the hit proxies are used when DrawDynamicElements is called.
Called in the game thread.
Parameters
OutHitProxies - Hit proxes which are created should be added to this array.
Returns
The hit proxy to use by default for elements drawn by DrawDynamicElements.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FInstancedStaticMeshSceneProxy.
CreateHitProxies() [2/2]
virtual HHitProxy * FStaticMeshSceneProxy::CreateHitProxies (UPrimitiveComponent * Component, TArray< TRefCountPtr< HHitProxy > > & OutHitProxies) override virtual
All FPrimitiveSceneProxy derived classes can decide to fully override the HHitProxy creation, or add their own and call any of their base classes to add theirs.
Classes deriving from FPrimitiveSceneProxy which are meant to be used with IPrimitiveComponent should override both CreateHitProxies(UPrimitiveComponent*, ...) and CreateHitProxies(IPrimitiveComponent*, ...) and make the UPrimitiveComponent version call into the IPrimitiveComponent one. This allows their derived classes that are exclusive to UPrimitiveComponent to call into them and to reroute the proxy creation to the IPrimitiveComponent path. Creates the hit proxies are used when DrawDynamicElements is called. Called in the game thread.
Parameters
OutHitProxies - Hit proxes which are created should be added to this array.
Returns
The hit proxy to use by default for elements drawn by DrawDynamicElements.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FInstancedStaticMeshSceneProxy.
References Component.
CreateRenderThreadResources()
virtual void FStaticMeshSceneProxy::CreateRenderThreadResources (FRHICommandListBase & RHICmdList) override virtual
Called when the rendering thread adds the proxy to the scene.
This function allows for generating renderer-side resources. Called in the rendering thread.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FHierarchicalStaticMeshSceneProxy, FInstancedStaticMeshSceneProxy, and FLandscapeMeshProxySceneProxy.
DestroyRenderThreadResources()
virtual void FStaticMeshSceneProxy::DestroyRenderThreadResources () override virtual
Called when the rendering thread removes the proxy from the scene.
This function allows for removing renderer-side resources. Called in the rendering thread.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FInstancedStaticMeshSceneProxy, and FLandscapeMeshProxySceneProxy.
DrawStaticElements()
virtual void FStaticMeshSceneProxy::DrawStaticElements (FStaticPrimitiveDrawInterface * PDI) override virtual
Draws the primitive's static elements.
This is called from the rendering thread once when the scene proxy is created. The static elements will only be rendered if GetViewRelevance declares static relevance.
Parameters
PDI - The interface which receives the primitive elements.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FHierarchicalStaticMeshSceneProxy.
GetAllocatedSize()
SIZE_T FStaticMeshSceneProxy::GetAllocatedSize (void) const inline
Definition at line 154 of file StaticMeshSceneProxy.h.
References FPrimitiveSceneProxy::GetAllocatedSize(), and LODs.
Referenced by GetMemoryFootprint().
GetCollisionMeshElement()
virtual bool FStaticMeshSceneProxy::GetCollisionMeshElement (int32 LODIndex, int32 BatchIndex, int32 ElementIndex, uint8 InDepthPriorityGroup, const FMaterialRenderProxy * RenderProxy, FMeshBatch & OutMeshBatch) const virtual
Sets up a collision FMeshBatch for a specific LOD and element.
Reimplemented in FSplineMeshSceneProxy.
References ElementIndex.
GetCurrentFirstLODIdx_Internal()
uint8 FStaticMeshSceneProxy::GetCurrentFirstLODIdx_Internal () const protected
Only call on render thread timeline.
References const, and GetCurrentFirstLODIdx_Internal().
Referenced by GetCurrentFirstLODIdx_Internal(), GetCurrentFirstLODIdx_RenderThread(), and GetDesiredLODLevel_RenderThread().
GetCurrentFirstLODIdx_RenderThread()
virtual uint8 FStaticMeshSceneProxy::GetCurrentFirstLODIdx_RenderThread () const inline final override virtual
Reimplemented from FPrimitiveSceneProxy.
Definition at line 83 of file StaticMeshSceneProxy.h.
References const, FPrimitiveSceneProxy::final, and GetCurrentFirstLODIdx_Internal().
GetDesiredLODLevel_RenderThread()
virtual FDesiredLODLevel FStaticMeshSceneProxy::GetDesiredLODLevel_RenderThread (const FSceneView * View) const inline final override virtual
Reimplemented from FPrimitiveSceneProxy.
Definition at line 88 of file StaticMeshSceneProxy.h.
References FDesiredLODLevel::CreateFirst(), and GetCurrentFirstLODIdx_Internal().
GetDistanceFieldAtlasData()
virtual void FStaticMeshSceneProxy::GetDistanceFieldAtlasData (const FDistanceFieldVolumeData *& OutDistanceFieldData, float & SelfShadowBias) const override virtual
Reimplemented in FInstancedStaticMeshSceneProxy.
GetDynamicMeshElements()
virtual void FStaticMeshSceneProxy::GetDynamicMeshElements (const TArray< const FSceneView * > & Views, const FSceneViewFamily & ViewFamily, uint32 VisibilityMap, FMeshElementCollector & Collector) const override virtual
Gathers the primitive's dynamic mesh elements.
This will only be called if GetViewRelevance declares dynamic relevance. This is called from the rendering thread for each set of views that might be rendered.
Game thread state like UObjects must have their properties mirrored on the proxy to avoid race conditions. The rendering thread must not dereference UObjects. The gathered mesh elements will be used multiple times, any memory referenced must last as long as the Collector (eg no stack memory should be referenced). This function should not modify the proxy but simply collect a description of things to render. Updates to the proxy need to be pushed from game thread or external events.
Parameters
Views - the array of views to consider. These may not exist in the ViewFamily.
ViewFamily - the view family, for convenience
VisibilityMap - a bit representing this proxy's visibility in the Views array
Collector - gathers the mesh elements to be rendered and provides mechanisms for temporary allocations
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FHierarchicalStaticMeshSceneProxy, and FInstancedStaticMeshSceneProxy.
GetInstanceWorldPositionOffsetDisableDistance()
virtual bool FStaticMeshSceneProxy::GetInstanceWorldPositionOffsetDisableDistance (float & OutWPODisableDistance) const override virtual
Retrieves the per-instance world position offset disable distance.
Parameters
OutWPODisableDistance contains the distance from the camera at which the primitive's instances disable WPO
Returns
bool true if WPO disable distance is enabled for this primitive's instances
Reimplemented from FPrimitiveSceneProxy.
GetLCIs()
virtual void FStaticMeshSceneProxy::GetLCIs (FLCIArray & LCIs) override virtual
Reimplemented from FPrimitiveSceneProxy.
References FVector, and LightMapResolution.
GetLightMapCoordinateIndex()
virtual int32 FStaticMeshSceneProxy::GetLightMapCoordinateIndex () const override virtual
Get the lightmap UV coordinate index for this primitive.
Used by systems that explicitly fetch lightmap UVs.
Reimplemented from FPrimitiveSceneProxy.
GetLightRelevance()
virtual void FStaticMeshSceneProxy::GetLightRelevance (const FLightSceneProxy * LightSceneProxy, bool & bDynamic, bool & bRelevant, bool & bLightMapped, bool & bShadowMapped) const override virtual
Determines the relevance of this primitive's elements to the given light.
Parameters
LightSceneProxy The light to determine relevance for
bDynamic (output) The light is dynamic for this primitive
bRelevant (output) The light is relevant for this primitive
bLightMapped (output) The light is light mapped for this primitive
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FInstancedStaticMeshSceneProxy.
GetLOD()
virtual int32 FStaticMeshSceneProxy::GetLOD (const FSceneView * View) const override virtual
Returns the LOD that the primitive will render at for this view.
Reimplemented from FPrimitiveSceneProxy.
GetLODMask()
FLODMask FStaticMeshSceneProxy::GetLODMask (const FSceneView * View) const
Returns the LOD mask for a view, this is like the ordinary LOD but can return two values for dither fading.
GetMaterialCacheTextureDescriptor()
virtual FUintVector2 FStaticMeshSceneProxy::GetMaterialCacheTextureDescriptor () const inline override virtual
Reimplemented from FPrimitiveSceneProxy.
Definition at line 166 of file StaticMeshSceneProxy.h.
References MaterialCacheTextureDescriptor.
GetMemoryFootprint()
virtual uint32 FStaticMeshSceneProxy::GetMemoryFootprint (void) const inline override virtual
Every derived class should override these functions.
Implements FPrimitiveSceneProxy.
Definition at line 153 of file StaticMeshSceneProxy.h.
References GetAllocatedSize().
GetMeshCardRepresentation()
virtual const FCardRepresentationData * FStaticMeshSceneProxy::GetMeshCardRepresentation () const override virtual
Reimplemented from FPrimitiveSceneProxy.
GetMeshDescription()
virtual void FStaticMeshSceneProxy::GetMeshDescription (int32 LODIndex, TArray< FMeshBatch > & OutMeshElements) const override virtual
Gathers a description of the mesh elements to be rendered for the given LOD index, without consideration for views.
Reimplemented from FPrimitiveSceneProxy.
GetMeshElement()
virtual bool FStaticMeshSceneProxy::GetMeshElement (int32 LODIndex, int32 BatchIndex, int32 SectionIndex, uint8 InDepthPriorityGroup, bool bUseSelectionOutline, bool bAllowPreCulledIndices, FMeshBatch & OutMeshBatch) const virtual
Sets up a FMeshBatch for a specific LOD and element.
Reimplemented in FInstancedStaticMeshSceneProxy, and FSplineMeshSceneProxy.
References bAllowPreCulledIndices.
GetMeshPaintTextureDescriptor()
virtual FUintVector2 FStaticMeshSceneProxy::GetMeshPaintTextureDescriptor () const inline override virtual
Reimplemented from FPrimitiveSceneProxy.
Definition at line 164 of file StaticMeshSceneProxy.h.
References MeshPaintTextureDescriptor.
GetNumMeshBatches()
virtual int32 FStaticMeshSceneProxy::GetNumMeshBatches () const inline virtual
Gets the number of mesh batches required to represent the proxy, aside from section needs.
Reimplemented in FInstancedStaticMeshSceneProxy.
Definition at line 44 of file StaticMeshSceneProxy.h.
GetRayTracingMeshElement()
virtual bool FStaticMeshSceneProxy::GetRayTracingMeshElement (int32 LODIndex, int32 BatchIndex, int32 SectionIndex, uint8 InDepthPriorityGroup, FMeshBatch & OutMeshBatch) const virtual
Sets up a ray tracing FMeshBatch for a specific LOD.
GetRayTracingWPOConfig()
void FStaticMeshSceneProxy::GetRayTracingWPOConfig (bool & bOutHasRayTracingRepresentation, bool & bOutDynamicRayTracingGeometry) static
GetScreenSize()
float FStaticMeshSceneProxy::GetScreenSize (int32 LODIndex) const
Returns the display factor for the given LOD level.
@Param LODIndex - The LOD to get the display factor for
GetShadowMeshElement()
virtual bool FStaticMeshSceneProxy::GetShadowMeshElement (int32 LODIndex, int32 BatchIndex, uint8 InDepthPriorityGroup, FMeshBatch & OutMeshBatch, bool bDitheredLODTransition) const virtual
Sets up a shadow FMeshBatch for a specific LOD.
Reimplemented in FInstancedStaticMeshSceneProxy, and FSplineMeshSceneProxy.
GetStreamableRenderAssetInfo()
virtual void FStaticMeshSceneProxy::GetStreamableRenderAssetInfo (const FBoxSphereBounds & InPrimitiveBounds, TArray< FStreamingRenderAssetPrimitiveInfo > & OutStreamableRenderAssets) const override virtual
Reimplemented from FPrimitiveSceneProxy.
GetTypeHash()
SIZE_T FStaticMeshSceneProxy::GetTypeHash () const override virtual
Return a type (or subtype) specific hash for sorting purposes.
Implements FPrimitiveSceneProxy.
GetViewRelevance()
virtual FPrimitiveViewRelevance FStaticMeshSceneProxy::GetViewRelevance (const FSceneView * View) const override virtual
Determines the relevance of this primitive's elements to the given view.
Called in the rendering thread.
Parameters
View - The view to determine relevance for.
Returns
The relevance of the primitive's elements to the view.
Reimplemented from FPrimitiveSceneProxy.
Reimplemented in FHierarchicalStaticMeshSceneProxy, and FInstancedStaticMeshSceneProxy.
Referenced by FInstancedStaticMeshSceneProxy::GetViewRelevance().
GetWireframeMeshElement()
virtual bool FStaticMeshSceneProxy::GetWireframeMeshElement (int32 LODIndex, int32 BatchIndex, const FMaterialRenderProxy * WireframeRenderProxy, uint8 InDepthPriorityGroup, bool bAllowPreCulledIndices, FMeshBatch & OutMeshBatch) const virtual
Sets up a wireframe FMeshBatch for a specific LOD.
Reimplemented in FInstancedStaticMeshSceneProxy, and FSplineMeshSceneProxy.
References bAllowPreCulledIndices.
HasDistanceFieldRepresentation()
virtual bool FStaticMeshSceneProxy::HasDistanceFieldRepresentation () const override virtual
Reimplemented from FPrimitiveSceneProxy.
HasDynamicIndirectShadowCasterRepresentation()
virtual bool FStaticMeshSceneProxy::HasDynamicIndirectShadowCasterRepresentation () const override virtual
Reimplemented from FPrimitiveSceneProxy.
IsCollisionView()
bool FStaticMeshSceneProxy::IsCollisionView (const FEngineShowFlags & EngineShowFlags, bool & bDrawSimpleCollision, bool & bDrawComplexCollision) const protected
References const, and IsCollisionView().
Referenced by IsCollisionView().
IsCullingReversedByComponent()
virtual bool FStaticMeshSceneProxy::IsCullingReversedByComponent () const inline override virtual
Reimplemented from FPrimitiveSceneProxy.
Definition at line 162 of file StaticMeshSceneProxy.h.
References bReverseCulling.
IsReversedCullingNeeded()
bool FStaticMeshSceneProxy::IsReversedCullingNeeded (bool bUseReversedIndices) const protected
Returns whether this mesh needs reverse culling when using reversed indices.
References const, and IsReversedCullingNeeded().
Referenced by IsReversedCullingNeeded().
IsUsingDistanceCullFade()
virtual bool FStaticMeshSceneProxy::IsUsingDistanceCullFade () const override virtual
Returns
true if the proxy uses distance cull fade.
Reimplemented from FPrimitiveSceneProxy.
OnEvaluateWorldPositionOffsetChanged_RenderThread()
virtual void FStaticMeshSceneProxy::OnEvaluateWorldPositionOffsetChanged_RenderThread () override protected virtual
Allows child implementations to do render-thread work when bEvaluateWorldPositionOffset changes.
Reimplemented from FPrimitiveSceneProxy.
References OnEvaluateWorldPositionOffsetChanged_RenderThread().
Referenced by OnEvaluateWorldPositionOffsetChanged_RenderThread().
RemoveSpeedTreeWind()
void FStaticMeshSceneProxy::RemoveSpeedTreeWind () private
SetEvaluateWorldPositionOffsetInRayTracing()
virtual void FStaticMeshSceneProxy::SetEvaluateWorldPositionOffsetInRayTracing (FRHICommandListBase & RHICmdList, bool bEvaluate) virtual
SetMeshElementGeometrySource()
uint32 FStaticMeshSceneProxy::SetMeshElementGeometrySource (const FStaticMeshSection & Section, const FRawStaticIndexBuffer & IndexBuffer, const FAdditionalStaticMeshIndexBuffers * AdditionalIndexBuffers, const FVertexFactory * VertexFactory, bool bWireframe, bool bUseInversedIndices, FMeshBatch & OutMeshElement) const protected
Configures mesh batch vertex / index state.
Returns the number of primitives used in the element.
References bUseInversedIndices, bWireframe, const, IndexBuffer, SetMeshElementGeometrySource(), and VertexFactory.
Referenced by SetMeshElementGeometrySource(), and UE_DEPRECATED().
SetMeshElementScreenSize()
void FStaticMeshSceneProxy::SetMeshElementScreenSize (int32 LODIndex, bool bDitheredLODTransition, FMeshBatch & OutMeshBatch) const protected
Sets the screen size on a mesh element.
References const, and SetMeshElementScreenSize().
Referenced by SetMeshElementScreenSize().
ShouldEvaluateWPOInRayTracing()
bool FStaticMeshSceneProxy::ShouldEvaluateWPOInRayTracing (FVector ViewCenter, const FBoxSphereBounds & Bounds) static
References FPrimitiveSceneProxy::Bounds, and FVector.
ShouldRenderBackFaces()
bool FStaticMeshSceneProxy::ShouldRenderBackFaces () const protected
Returns whether this mesh should render back-faces instead of front-faces - either with reversed indices or reversed cull mode.
References const, and ShouldRenderBackFaces().
Referenced by ShouldRenderBackFaces().
StaticMeshHasPendingStreaming()
virtual bool FStaticMeshSceneProxy::StaticMeshHasPendingStreaming () const override virtual
Reimplemented from FPrimitiveSceneProxy.
UE_DEPRECATED()
FStaticMeshSceneProxy::UE_DEPRECATED (5. 6, "Provide FStaticMeshSection, IndexBuffer and AdditionalIndexBuffers instead of LODIndex, etc.") protected
References SetMeshElementGeometrySource().
Field Documentation
bAllowPreCulledIndices
int32 bool bool bool FStaticMeshSceneProxy::bAllowPreCulledIndices protected
Definition at line 106 of file StaticMeshSceneProxy.h.
Referenced by FInstancedStaticMeshSceneProxy::GetMeshElement(), FSplineMeshSceneProxy::GetMeshElement(), GetMeshElement(), FInstancedStaticMeshSceneProxy::GetWireframeMeshElement(), FSplineMeshSceneProxy::GetWireframeMeshElement(), and GetWireframeMeshElement().
bCastShadow
uint32 FStaticMeshSceneProxy::bCastShadow protected
Definition at line 299 of file StaticMeshSceneProxy.h.
bReverseCulling
uint32 FStaticMeshSceneProxy::bReverseCulling protected
This primitive has culling reversed.
Definition at line 302 of file StaticMeshSceneProxy.h.
Referenced by IsCullingReversedByComponent().
bUseInversedIndices
int32 bool bool FStaticMeshSceneProxy::bUseInversedIndices protected
Definition at line 105 of file StaticMeshSceneProxy.h.
Referenced by SetMeshElementGeometrySource().
bWireframe
int32 bool FStaticMeshSceneProxy::bWireframe protected
Definition at line 104 of file StaticMeshSceneProxy.h.
Referenced by SetMeshElementGeometrySource().
CardRepresentationData
const FCardRepresentationData* FStaticMeshSceneProxy::CardRepresentationData protected
Definition at line 271 of file StaticMeshSceneProxy.h.
ClampedMinLOD
int32 FStaticMeshSceneProxy::ClampedMinLOD protected
Minimum LOD index to use.
Clamped to valid range [0, NumLODs - 1].
Definition at line 297 of file StaticMeshSceneProxy.h.
const
int32 bool bool bool const FVertexFactory FMeshBatch& OutMeshElement FStaticMeshSceneProxy::const protected
Definition at line 108 of file StaticMeshSceneProxy.h.
Referenced by GetCurrentFirstLODIdx_Internal(), GetCurrentFirstLODIdx_RenderThread(), IsCollisionView(), IsReversedCullingNeeded(), SetMeshElementGeometrySource(), SetMeshElementScreenSize(), and ShouldRenderBackFaces().
DistanceFieldData
const FDistanceFieldVolumeData* FStaticMeshSceneProxy::DistanceFieldData protected
Definition at line 270 of file StaticMeshSceneProxy.h.
ElementIndex
int32 FStaticMeshSceneProxy::ElementIndex protected
Definition at line 103 of file StaticMeshSceneProxy.h.
Referenced by FSplineMeshSceneProxy::GetCollisionMeshElement(), GetCollisionMeshElement(), FInstancedStaticMeshSceneProxy::GetMeshElement(), and FSplineMeshSceneProxy::GetMeshElement().
ForcedLodModel
int32 FStaticMeshSceneProxy::ForcedLodModel protected
The forcedLOD set in the static mesh editor, copied from the mesh component.
Definition at line 294 of file StaticMeshSceneProxy.h.
LODs
TArray<FLODInfo> FStaticMeshSceneProxy::LODs protected
Definition at line 267 of file StaticMeshSceneProxy.h.
Referenced by GetAllocatedSize().
MaterialCacheTextureDescriptor
FUintVector2 FStaticMeshSceneProxy::MaterialCacheTextureDescriptor = FUintVector2(0, 0) private
Definition at line 338 of file StaticMeshSceneProxy.h.
Referenced by GetMaterialCacheTextureDescriptor().
MaterialCacheTextureResource
FTextureResource* FStaticMeshSceneProxy::MaterialCacheTextureResource = nullptr private
Definition at line 337 of file StaticMeshSceneProxy.h.
MaterialRelevance
FMaterialRelevance FStaticMeshSceneProxy::MaterialRelevance protected
The view relevance for all the static mesh's materials.
Definition at line 308 of file StaticMeshSceneProxy.h.
MaterialSlotsOverlayMaterial
TArray<TObjectPtr<UMaterialInterface> > FStaticMeshSceneProxy::MaterialSlotsOverlayMaterial protected
Definition at line 275 of file StaticMeshSceneProxy.h.
MeshPaintTextureCoordinateIndex
uint32 FStaticMeshSceneProxy::MeshPaintTextureCoordinateIndex protected
The coordinate index to use for texture color painting.
Definition at line 305 of file StaticMeshSceneProxy.h.
MeshPaintTextureDescriptor
FUintVector2 FStaticMeshSceneProxy::MeshPaintTextureDescriptor = FUintVector2(0, 0) private
Definition at line 335 of file StaticMeshSceneProxy.h.
Referenced by GetMeshPaintTextureDescriptor().
MeshPaintTextureResource
FTextureResource* FStaticMeshSceneProxy::MeshPaintTextureResource = nullptr private
Definition at line 334 of file StaticMeshSceneProxy.h.
OverlayMaterial
UMaterialInterface* FStaticMeshSceneProxy::OverlayMaterial protected
Definition at line 273 of file StaticMeshSceneProxy.h.
OverlayMaterialMaxDrawDistance
float FStaticMeshSceneProxy::OverlayMaterialMaxDrawDistance protected
Definition at line 274 of file StaticMeshSceneProxy.h.
RayTracingLODInfos
TArray<FRayTracingLODInfo> FStaticMeshSceneProxy::RayTracingLODInfos protected
Definition at line 268 of file StaticMeshSceneProxy.h.
RenderData
FStaticMeshRenderData* FStaticMeshSceneProxy::RenderData protected
Definition at line 265 of file StaticMeshSceneProxy.h.
StaticMesh
const UStaticMesh* FStaticMeshSceneProxy::StaticMesh private
Definition at line 332 of file StaticMeshSceneProxy.h.
VertexFactory
int32 bool bool bool const FVertexFactory* FStaticMeshSceneProxy::VertexFactory protected
Definition at line 107 of file StaticMeshSceneProxy.h.
Referenced by SetMeshElementGeometrySource().
WPODisableDistance
float FStaticMeshSceneProxy::WPODisableDistance protected
The distance at which to disable World Position Offset (0 = no max).
Definition at line 311 of file StaticMeshSceneProxy.h.
The documentation for this class was generated from the following file:
StaticMeshSceneProxy.h