Unreal Engine 5.6 C++ API: UE::Geometry::FMeshNormals Class Reference
UE::Geometry::FMeshNormals Class Reference
FMeshNormals is a utility class that can calculate and store various types of normal vectors for a FDynamicMesh.
#include "MeshNormals.h"
Public Member Functions
FMeshNormals ()
FMeshNormals (const FDynamicMesh3 *Mesh)
void ComputeTriangleNormals ()
Compute per-triangle normals.
void ComputeVertexNormals (bool bWeightByArea=true, bool bWeightByAngle=true)
Compute standard per-vertex normals by averaging one-ring face normals.
GEOMETRYCORE_API void CopyToOverlay (FDynamicMeshNormalOverlay *NormalOverlay, bool bInvert=false) const
Copy the current set of normals to the NormalOverlay attribute layer.
GEOMETRYCORE_API void CopyToVertexNormals (FDynamicMesh3 *SetMesh, bool bInvert=false) const
Copy the current set of normals to the vertex normals of SetMesh.
const TArray< FVector3d > & GetNormals () const
FVector3d & operator[] (int i)
const FVector3d & operator[] (int i) const
void RecomputeOverlayNormals (const FDynamicMeshNormalOverlay *NormalOverlay, bool bWeightByArea=true, bool bWeightByAngle=true)
Recompute the per-element normals of the given overlay by averaging one-ring face normals.
GEOMETRYCORE_API void SetCount (int Count, bool bClearToZero)
Set the size of the Normals array to Count, and optionally clear all values to (0,0,0)
GEOMETRYCORE_API void SetDegenerateTriangleNormalsToNeighborNormal ()
Assumes that ComputeTriangleNormals() has already been run.
void SetMesh (const FDynamicMesh3 *MeshIn)
Static Public Member Functions
static GEOMETRYCORE_API FVector3d ComputeOverlayNormal (const FDynamicMesh3 &Mesh, const FDynamicMeshNormalOverlay *NormalOverlay, int ElemIdx, bool bWeightByArea=true, bool bWeightByAngle=true)
static GEOMETRYCORE_API FVector3d ComputeVertexNormal (const FDynamicMesh3 &Mesh, int VertIdx, bool bWeightByArea=true, bool bWeightByAngle=true)
Compute normal at mesh vertex by weighted sum of one-ring triangle normals.
static GEOMETRYCORE_API FVector3d ComputeVertexNormal (const FDynamicMesh3 &Mesh, int32 VertIdx, TFunctionRef< bool(int32)> TriangleFilterFunc, bool bWeightByArea=true, bool bWeightByAngle=true)
Compute normal at mesh vertex by weighted sum of subset of one-ring triangle normals.
static GEOMETRYCORE_API FVector3d GetVertexWeightsOnTriangle (const FDynamicMesh3 *Mesh, int TriID, double TriArea, bool bWeightByArea, bool bWeightByAngle)
Retrieve the area and/or angle weights for each vertex of a triangle.
static GEOMETRYCORE_API void InitializeMeshToPerTriangleNormals (FDynamicMesh3 *Mesh)
Initialize the given Mesh with per-face normals, ie separate overlay element for each vertex of each triangle.
static GEOMETRYCORE_API void InitializeOverlayRegionToPerVertexNormals (FDynamicMeshNormalOverlay *NormalOverlay, const TArray< int32 > &Triangles)
Initialize the given triangles of NormalOverlay with per-vertex normals, ie single overlay element for each mesh vertex.
static GEOMETRYCORE_API void InitializeOverlayToPerTriangleNormals (FDynamicMeshNormalOverlay *NormalOverlay)
Initialize the given NormalOverlay with per-face normals, ie separate overlay element for each vertex of each triangle.
static GEOMETRYCORE_API void InitializeOverlayToPerVertexNormals (FDynamicMeshNormalOverlay *NormalOverlay, bool bUseMeshVertexNormalsIfAvailable=true)
Initialize the given NormalOverlay with per-vertex normals, ie single overlay element for each mesh vertex.
static GEOMETRYCORE_API void InitializeOverlayTopologyFromFaceGroups (const FDynamicMesh3 *Mesh, FDynamicMeshNormalOverlay *NormalOverlay)
static GEOMETRYCORE_API void InitializeOverlayTopologyFromOpeningAngle (const FDynamicMesh3 *Mesh, FDynamicMeshNormalOverlay *NormalOverlay, double AngleThresholdDeg)
static GEOMETRYCORE_API void QuickComputeVertexNormals (FDynamicMesh3 &Mesh, bool bInvert=false)
Compute per-vertex normals for the given Mesh.
static GEOMETRYCORE_API void QuickComputeVertexNormalsForTriangles (FDynamicMesh3 &Mesh, const TArray< int32 > &Triangles, bool bWeightByArea=true, bool bWeightByAngle=true, bool bInvert=false)
Compute per-vertex normals for the vertices of a set of triangles of a Mesh.
static GEOMETRYCORE_API bool QuickRecomputeOverlayNormals (FDynamicMesh3 &Mesh, bool bInvert=false, bool bWeightByArea=true, bool bWeightByAngle=true, bool bParallelCompute=true)
Compute overlay normals for the given mesh.
static GEOMETRYCORE_API bool RecomputeOverlayElementNormals (FDynamicMesh3 &Mesh, const TArray< int32 > &ElementIDs, bool bWeightByArea=true, bool bWeightByAngle=true)
Compute overlay normals for the given mesh, for the given set of element IDs.
static GEOMETRYCORE_API bool RecomputeOverlayTriNormals (FDynamicMesh3 &Mesh, const TArray< int32 > &Triangles, bool bWeightByArea=true, bool bWeightByAngle=true)
Compute overlay normals for the given mesh, for the given set of triangles.
static GEOMETRYCORE_API void SmoothVertexNormals (FDynamicMesh3 &Mesh, int32 SmoothingRounds, double SmoothingAlpha)
Apply rounds of explicit uniform-weighted normal smoothing to the VertexNormals attribute of the given Mesh.
Protected Member Functions
GEOMETRYCORE_API void Compute_FaceAvg (bool bWeightByArea, bool bWeightByAngle)
Compute per-vertex normals using a custom combination of area-weighted and angle-weighted averaging of one-ring triangle normals.
GEOMETRYCORE_API void Compute_FaceAvg_AreaWeighted ()
Compute per-vertex normals using area-weighted averaging of one-ring triangle normals.
GEOMETRYCORE_API void Compute_Overlay_FaceAvg (const FDynamicMeshNormalOverlay *NormalOverlay, bool bWeightByArea, bool bWeightByAngle)
Recompute the element Normals of the given attribute overlay using a custom combination of area-weighted and angle-weighted averaging of one-ring triangle normals.
GEOMETRYCORE_API void Compute_Overlay_FaceAvg_AreaWeighted (const FDynamicMeshNormalOverlay *NormalOverlay)
Recompute the element Normals of the given attribute overlay using area-weighted averaging of one-ring triangle normals.
GEOMETRYCORE_API void Compute_Triangle ()
Compute per-triangle normals.
Protected Attributes
const FDynamicMesh3 * Mesh
Target Mesh.
TArray< FVector3d > Normals
Set of computed normals.
Detailed Description
FMeshNormals is a utility class that can calculate and store various types of normal vectors for a FDynamicMesh.
Definition at line 25 of file MeshNormals.h.
Constructor & Destructor Documentation
FMeshNormals() [1/2]
UE::Geometry::FMeshNormals::FMeshNormals () inline
Definition at line 34 of file MeshNormals.h.
References Mesh.
FMeshNormals() [2/2]
UE::Geometry::FMeshNormals::FMeshNormals (const FDynamicMesh3 * Mesh) inline
Definition at line 39 of file MeshNormals.h.
References Mesh, and SetMesh().
Member Function Documentation
Compute_FaceAvg()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::Compute_FaceAvg (bool bWeightByArea, bool bWeightByAngle) protected
Compute per-vertex normals using a custom combination of area-weighted and angle-weighted averaging of one-ring triangle normals.
Referenced by ComputeVertexNormals().
Compute_FaceAvg_AreaWeighted()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::Compute_FaceAvg_AreaWeighted () protected
Compute per-vertex normals using area-weighted averaging of one-ring triangle normals.
Compute_Overlay_FaceAvg()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::Compute_Overlay_FaceAvg (const FDynamicMeshNormalOverlay * NormalOverlay, bool bWeightByArea, bool bWeightByAngle) protected
Recompute the element Normals of the given attribute overlay using a custom combination of area-weighted and angle-weighted averaging of one-ring triangle normals.
Referenced by RecomputeOverlayNormals().
Compute_Overlay_FaceAvg_AreaWeighted()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::Compute_Overlay_FaceAvg_AreaWeighted (const FDynamicMeshNormalOverlay * NormalOverlay) protected
Recompute the element Normals of the given attribute overlay using area-weighted averaging of one-ring triangle normals.
Compute_Triangle()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::Compute_Triangle () protected
Compute per-triangle normals.
Referenced by ComputeTriangleNormals().
ComputeOverlayNormal()
GEOMETRYCORE_API FVector3d UE::Geometry::FMeshNormals::ComputeOverlayNormal (const FDynamicMesh3 & Mesh, const FDynamicMeshNormalOverlay * NormalOverlay, int ElemIdx, bool bWeightByArea = true, bool bWeightByAngle = true) static
Returns
the computed overlay normal at an element of the overlay (ie based on normals of triangles connected to this element)
Parameters
bWeightByArea weight neighbor triangles by area
bWeightByAngle weight neighbor triangles by angle
References Mesh.
ComputeTriangleNormals()
void UE::Geometry::FMeshNormals::ComputeTriangleNormals () inline
Compute per-triangle normals.
Definition at line 72 of file MeshNormals.h.
References Compute_Triangle().
ComputeVertexNormal() [1/2]
GEOMETRYCORE_API FVector3d UE::Geometry::FMeshNormals::ComputeVertexNormal (const FDynamicMesh3 & Mesh, int VertIdx, bool bWeightByArea = true, bool bWeightByAngle = true) static
Compute normal at mesh vertex by weighted sum of one-ring triangle normals.
Can optionally weight by area, angle, or both (averaged)
Parameters
bWeightByArea weight neighbor triangles by area
bWeightByAngle weight neighbor triangles by angle
Returns
the vertex normal at vertex VertIdx of Mesh.
References Mesh.
Referenced by UE::Geometry::FMeshRegionOperator::BackPropropagateVertices(), and UE::Geometry::TMeshLocalParam< PointSetType >::GetNormal().
ComputeVertexNormal() [2/2]
GEOMETRYCORE_API FVector3d UE::Geometry::FMeshNormals::ComputeVertexNormal (const FDynamicMesh3 & Mesh, int32 VertIdx, TFunctionRef< bool(int32)> TriangleFilterFunc, bool bWeightByArea = true, bool bWeightByAngle = true) static
Compute normal at mesh vertex by weighted sum of subset of one-ring triangle normals.
Can optionally weight by area, angle, or both (averaged)
Parameters
TriangleFilterFunc Only one-ring triangles for which this function returns true will be included
bWeightByArea weight neighbor triangles by area
bWeightByAngle weight neighbor triangles by angle
Returns
the vertex normal at vertex VertIdx of Mesh.
References Mesh.
ComputeVertexNormals()
void UE::Geometry::FMeshNormals::ComputeVertexNormals (bool bWeightByArea = true, bool bWeightByAngle = true) inline
Compute standard per-vertex normals by averaging one-ring face normals.
Definition at line 64 of file MeshNormals.h.
References Compute_FaceAvg().
Referenced by UE::Geometry::FIterativeOffsetMeshOp::Offset(), and UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
CopyToOverlay()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::CopyToOverlay (FDynamicMeshNormalOverlay * NormalOverlay, bool bInvert = false) const
Copy the current set of normals to the NormalOverlay attribute layer.
Warning
assumes that the computed normals are attribute normals
Parameters
bInvert if true, normals are flipped
CopyToVertexNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::CopyToVertexNormals (FDynamicMesh3 * SetMesh, bool bInvert = false) const
Copy the current set of normals to the vertex normals of SetMesh.
Warning
assumes that the computed normals are vertex normals
Parameters
bInvert if true, normals are flipped
References SetMesh().
GetNormals()
const TArray< FVector3d > & UE::Geometry::FMeshNormals::GetNormals () const inline
Definition at line 50 of file MeshNormals.h.
References Normals.
Referenced by UE::Geometry::FIterativeOffsetMeshOp::Offset(), and UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
GetVertexWeightsOnTriangle()
GEOMETRYCORE_API FVector3d UE::Geometry::FMeshNormals::GetVertexWeightsOnTriangle (const FDynamicMesh3 * Mesh, int TriID, double TriArea, bool bWeightByArea, bool bWeightByAngle) static
Retrieve the area and/or angle weights for each vertex of a triangle.
Parameters
Mesh the mesh to query
TriID the triangle index of the mesh to query
TriArea the area of the triangle
bWeightByArea if true, include weighting by the area of the triangle
bWeightByAngle if true, include weighting by the interior angles of the triangle
References Mesh.
InitializeMeshToPerTriangleNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeMeshToPerTriangleNormals (FDynamicMesh3 * Mesh) static
Initialize the given Mesh with per-face normals, ie separate overlay element for each vertex of each triangle.
References Mesh.
InitializeOverlayRegionToPerVertexNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeOverlayRegionToPerVertexNormals (FDynamicMeshNormalOverlay * NormalOverlay, const TArray< int32 > & Triangles) static
Initialize the given triangles of NormalOverlay with per-vertex normals, ie single overlay element for each mesh vertex.
Only the triangles included in the region are considered when calculating per-vertex normals.
InitializeOverlayToPerTriangleNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeOverlayToPerTriangleNormals (FDynamicMeshNormalOverlay * NormalOverlay) static
Initialize the given NormalOverlay with per-face normals, ie separate overlay element for each vertex of each triangle.
InitializeOverlayToPerVertexNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeOverlayToPerVertexNormals (FDynamicMeshNormalOverlay * NormalOverlay, bool bUseMeshVertexNormalsIfAvailable = true) static
Initialize the given NormalOverlay with per-vertex normals, ie single overlay element for each mesh vertex.
Parameters
bUseMeshVertexNormalsIfAvailable if true and the parent mesh has per-vertex normals, use them instead of calculating new ones
InitializeOverlayTopologyFromFaceGroups()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeOverlayTopologyFromFaceGroups (const FDynamicMesh3 * Mesh, FDynamicMeshNormalOverlay * NormalOverlay) static
References Mesh.
InitializeOverlayTopologyFromOpeningAngle()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::InitializeOverlayTopologyFromOpeningAngle (const FDynamicMesh3 * Mesh, FDynamicMeshNormalOverlay * NormalOverlay, double AngleThresholdDeg) static
References Mesh.
operator[]() [1/2]
FVector3d & UE::Geometry::FMeshNormals::operator[] (int i) inline
Definition at line 52 of file MeshNormals.h.
References Normals.
operator[]() [2/2]
const FVector3d & UE::Geometry::FMeshNormals::operator[] (int i) const inline
Definition at line 53 of file MeshNormals.h.
References Normals.
QuickComputeVertexNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::QuickComputeVertexNormals (FDynamicMesh3 & Mesh, bool bInvert = false) static
Compute per-vertex normals for the given Mesh.
Parameters
bInvert if true, normals are flipped
References Mesh.
QuickComputeVertexNormalsForTriangles()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::QuickComputeVertexNormalsForTriangles (FDynamicMesh3 & Mesh, const TArray< int32 > & Triangles, bool bWeightByArea = true, bool bWeightByAngle = true, bool bInvert = false) static
Compute per-vertex normals for the vertices of a set of triangles of a Mesh.
Parameters
bWeightByArea weight neighbor triangles by area
bWeightByAngle weight neighbor triangles by angle
bInvert if true, normals are flipped
References Mesh.
QuickRecomputeOverlayNormals()
GEOMETRYCORE_API bool UE::Geometry::FMeshNormals::QuickRecomputeOverlayNormals (FDynamicMesh3 & Mesh, bool bInvert = false, bool bWeightByArea = true, bool bWeightByAngle = true, bool bParallelCompute = true) static
Compute overlay normals for the given mesh.
Parameters
bInvert if true, normals are flipped
References Mesh.
RecomputeOverlayElementNormals()
GEOMETRYCORE_API bool UE::Geometry::FMeshNormals::RecomputeOverlayElementNormals (FDynamicMesh3 & Mesh, const TArray< int32 > & ElementIDs, bool bWeightByArea = true, bool bWeightByAngle = true) static
Compute overlay normals for the given mesh, for the given set of element IDs.
References Mesh.
RecomputeOverlayNormals()
void UE::Geometry::FMeshNormals::RecomputeOverlayNormals (const FDynamicMeshNormalOverlay * NormalOverlay, bool bWeightByArea = true, bool bWeightByAngle = true) inline
Recompute the per-element normals of the given overlay by averaging one-ring face normals.
Warning
NormalOverlay must be attached to ParentMesh or an exact copy
Definition at line 93 of file MeshNormals.h.
References Compute_Overlay_FaceAvg().
RecomputeOverlayTriNormals()
GEOMETRYCORE_API bool UE::Geometry::FMeshNormals::RecomputeOverlayTriNormals (FDynamicMesh3 & Mesh, const TArray< int32 > & Triangles, bool bWeightByArea = true, bool bWeightByAngle = true) static
Compute overlay normals for the given mesh, for the given set of triangles.
References Mesh.
SetCount()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::SetCount (int Count, bool bClearToZero)
Set the size of the Normals array to Count, and optionally clear all values to (0,0,0)
References UE::Count.
SetDegenerateTriangleNormalsToNeighborNormal()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::SetDegenerateTriangleNormalsToNeighborNormal ()
Assumes that ComputeTriangleNormals() has already been run.
Looks through the normals for any that are zero, and tries to set them to the normal of some neighboring triangle, preferring the triangle on its longer side if possible. This is useful for finding connected components based on normals, as it prevents degenerate triangles with 0 normals from connecting otherwise disconnected components. This won't help if a whole mesh componenent is entirely made of such degenerate triangles (which is usually ok).
SetMesh()
void UE::Geometry::FMeshNormals::SetMesh (const FDynamicMesh3 * MeshIn) inline
Definition at line 45 of file MeshNormals.h.
Referenced by FMeshNormals(), and CopyToVertexNormals().
SmoothVertexNormals()
GEOMETRYCORE_API void UE::Geometry::FMeshNormals::SmoothVertexNormals (FDynamicMesh3 & Mesh, int32 SmoothingRounds, double SmoothingAlpha) static
Apply rounds of explicit uniform-weighted normal smoothing to the VertexNormals attribute of the given Mesh.
References Mesh.
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FMeshNormals::Mesh protected
Target Mesh.
Definition at line 29 of file MeshNormals.h.
Referenced by FMeshNormals(), FMeshNormals(), ComputeOverlayNormal(), ComputeVertexNormal(), ComputeVertexNormal(), GetVertexWeightsOnTriangle(), InitializeMeshToPerTriangleNormals(), InitializeOverlayTopologyFromFaceGroups(), InitializeOverlayTopologyFromOpeningAngle(), QuickComputeVertexNormals(), QuickComputeVertexNormalsForTriangles(), QuickRecomputeOverlayNormals(), RecomputeOverlayElementNormals(), RecomputeOverlayTriNormals(), and SmoothVertexNormals().
Normals
TArray<FVector3d> UE::Geometry::FMeshNormals::Normals protected
Set of computed normals.
Definition at line 31 of file MeshNormals.h.
Referenced by GetNormals(), operator[](), and operator[]().
The documentation for this class was generated from the following file:
MeshNormals.h