Unreal Engine 5.6 C++ API: UE::Geometry::FSparseOctreeCell Struct Reference
UE::Geometry::FSparseOctreeCell Struct Reference
FSparseOctreeCell is a Node in a SparseDynamicOctree3.
#include "SparseDynamicOctree3.h"
Public Member Functions
FSparseOctreeCell ()
FSparseOctreeCell (uint8 LevelIn, const FVector3i &IndexIn)
uint32 GetChildCellID (int ChildIndex) const
bool HasChild (int ChildIndex) const
bool IsExistingCell () const
FSparseOctreeCell MakeChildCell (int ChildIndex)
void SetChild (uint32 ChildIndex, const FSparseOctreeCell &ChildCell)
Data Fields
uint32 CellID
ID of cell (index into cell list)
TStaticArray< uint32, 8 > Children
CellID of each child, or InvalidID if that child does not exist.
FVector3i Index
i,j,k index of cell in level, relative to origin
uint8 Level
Level of cell in octree.
Static Public Attributes
static constexpr uint32 InvalidID = TNumericLimits<uint32>::Max()
static constexpr uint8 InvalidLevel = TNumericLimits<uint8>::Max()
Detailed Description
FSparseOctreeCell is a Node in a SparseDynamicOctree3.
Definition at line 82 of file SparseDynamicOctree3.h.
Constructor & Destructor Documentation
FSparseOctreeCell() [1/2]
UE::Geometry::FSparseOctreeCell::FSparseOctreeCell () inline
Definition at line 99 of file SparseDynamicOctree3.h.
References CellID, Children, Index, InvalidID, Level, and Zero.
Referenced by MakeChildCell(), and SetChild().
FSparseOctreeCell() [2/2]
UE::Geometry::FSparseOctreeCell::FSparseOctreeCell (uint8 LevelIn, const FVector3i & IndexIn) inline
Definition at line 106 of file SparseDynamicOctree3.h.
References CellID, Children, Index, InvalidID, and Level.
Member Function Documentation
GetChildCellID()
uint32 UE::Geometry::FSparseOctreeCell::GetChildCellID (int ChildIndex) const inline
Definition at line 123 of file SparseDynamicOctree3.h.
References Children.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), and UE::Geometry::FDynamicMeshOctree3::CollectTriangles().
HasChild()
bool UE::Geometry::FSparseOctreeCell::HasChild (int ChildIndex) const inline
Definition at line 118 of file SparseDynamicOctree3.h.
References Children, and InvalidID.
Referenced by UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), and UE::Geometry::FDynamicMeshOctree3::CollectTriangles().
IsExistingCell()
bool UE::Geometry::FSparseOctreeCell::IsExistingCell () const inline
Definition at line 113 of file SparseDynamicOctree3.h.
References CellID, and InvalidID.
MakeChildCell()
FSparseOctreeCell UE::Geometry::FSparseOctreeCell::MakeChildCell (int ChildIndex) inline
Definition at line 128 of file SparseDynamicOctree3.h.
References FSparseOctreeCell(), Index, and Level.
SetChild()
void UE::Geometry::FSparseOctreeCell::SetChild (uint32 ChildIndex, const FSparseOctreeCell & ChildCell) inline
Definition at line 137 of file SparseDynamicOctree3.h.
References FSparseOctreeCell(), CellID, and Children.
Field Documentation
CellID
uint32 UE::Geometry::FSparseOctreeCell::CellID
ID of cell (index into cell list)
Definition at line 88 of file SparseDynamicOctree3.h.
Referenced by FSparseOctreeCell(), FSparseOctreeCell(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), IsExistingCell(), and SetChild().
Children
TStaticArray<uint32, 8> UE::Geometry::FSparseOctreeCell::Children
CellID of each child, or InvalidID if that child does not exist.
Definition at line 97 of file SparseDynamicOctree3.h.
Referenced by FSparseOctreeCell(), FSparseOctreeCell(), GetChildCellID(), HasChild(), and SetChild().
Index
FVector3i UE::Geometry::FSparseOctreeCell::Index
i,j,k index of cell in level, relative to origin
Definition at line 94 of file SparseDynamicOctree3.h.
Referenced by FSparseOctreeCell(), FSparseOctreeCell(), and MakeChildCell().
InvalidID
uint32 UE::Geometry::FSparseOctreeCell::InvalidID = TNumericLimits<uint32>::Max() static constexpr
Definition at line 84 of file SparseDynamicOctree3.h.
Referenced by FSparseOctreeCell(), FSparseOctreeCell(), HasChild(), and IsExistingCell().
InvalidLevel
uint8 UE::Geometry::FSparseOctreeCell::InvalidLevel = TNumericLimits<uint8>::Max() static constexpr
Definition at line 85 of file SparseDynamicOctree3.h.
Level
uint8 UE::Geometry::FSparseOctreeCell::Level
Level of cell in octree.
Definition at line 91 of file SparseDynamicOctree3.h.
Referenced by FSparseOctreeCell(), FSparseOctreeCell(), and MakeChildCell().
The documentation for this struct was generated from the following file:
SparseDynamicOctree3.h