Unreal Engine 5.6 C++ API: FShaderTypeRegistration Class Reference
FShaderTypeRegistration Class Reference
Registers a shader type in various systems.
#include "Shader.h"
Public Member Functions
FShaderTypeRegistration (TFunctionRef< FShaderType &()> LazyShaderTypeAccessor)
Static Public Member Functions
static RENDERCORE_API void CommitAll ()
static RENDERCORE_API TArray< const FShaderTypeRegistration * > & GetInstances ()
Private Attributes
TFunctionRef< FShaderType &()> LazyShaderTypeAccessor
Detailed Description
Registers a shader type in various systems.
Should be created as a static field/global.
Each shader type is collected here, not as an instance but as an accessor, so the actual construction can be deferred. The collection happens during static init, the actual construction happens later during launch. The purpose of collecting the types is the CommitAll function, called in LaunchEngineLoop, to ensure all type instances are constructed and registered before other systems start iterating them.
Definition at line 1621 of file Shader.h.
Constructor & Destructor Documentation
FShaderTypeRegistration()
FShaderTypeRegistration::FShaderTypeRegistration (TFunctionRef< FShaderType &()> LazyShaderTypeAccessor) inline
Definition at line 1624 of file Shader.h.
References GetInstances(), and LazyShaderTypeAccessor.
Member Function Documentation
CommitAll()
RENDERCORE_API void FShaderTypeRegistration::CommitAll () static
GetInstances()
RENDERCORE_API TArray< const FShaderTypeRegistration * > & FShaderTypeRegistration::GetInstances () static
Referenced by FShaderTypeRegistration().
Field Documentation
LazyShaderTypeAccessor
TFunctionRef<FShaderType& ()> FShaderTypeRegistration::LazyShaderTypeAccessor private
Definition at line 1636 of file Shader.h.
Referenced by FShaderTypeRegistration().
The documentation for this class was generated from the following file:
Shader.h