Unreal Engine 5.6 C++ API: FNavigationMetaData Class Reference
FNavigationMetaData Class Reference
Metadata to override the navigation behavior or regular SWidget.
#include "NavigationMetaData.h"
Data Structures
struct SNavData
Public Member Functions
EUINavigationRule GetBoundaryRule (EUINavigation InNavigation) const
Get the boundary rule for the provided navigation type.
const FNavigationDelegate & GetFocusDelegate (EUINavigation InNavigation) const
Get the focus recipient delegate for the provided navigation type.
const TWeakPtr< SWidget > & GetFocusRecipient (EUINavigation InNavigation) const
Get the focus recipient for the provided navigation type.
void SetNavigationCustom (EUINavigation InNavigation, EUINavigationRule InCustomBoundaryRule, FNavigationDelegate InFocusDelegate)
Set the navigation behavior for the provided navigation type to be a custom delegate.
void SetNavigationEscape (EUINavigation InNavigation)
An event should return a FNavigationReply::Escape() to let the system know that a navigation can escape the bounds of this widget.
void SetNavigationExplicit (EUINavigation InNavigation, TSharedPtr< SWidget > InFocusRecipient)
Set the navigation behavior for the provided navigation type to be explicit, using a constant widget.
void SetNavigationStop (EUINavigation InNavigation)
An event should return a FNavigationReply::Explicit() to let the system know to stop at the bounds of this widget.
void SetNavigationWrap (EUINavigation InNavigation)
Set the navigation behavior for the provided navigation type to be wrap.
SLATE_METADATA_TYPE (FNavigationMetaData, ISlateMetaData) FNavigationMetaData()
Public Member Functions inherited from ISlateMetaData
virtual ~ISlateMetaData ()
Virtual destructor.
template<class TType>
bool IsOfType () const
Check if this metadata operation can cast safely to the specified template type.
Private Attributes
SNavData Rules [(uint8) EUINavigation::Num]
Additional Inherited Members
Protected Member Functions inherited from ISlateMetaData
virtual bool IsOfTypeImpl (const FName &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
Detailed Description
Metadata to override the navigation behavior or regular SWidget.
Definition at line 15 of file NavigationMetaData.h.
Member Function Documentation
GetBoundaryRule()
EUINavigationRule FNavigationMetaData::GetBoundaryRule (EUINavigation InNavigation) const inline
Get the boundary rule for the provided navigation type.
Parameters
InNavigation the type of navigation to get the boundary rule for
Returns
the boundary rule for the provided navigation type
Definition at line 36 of file NavigationMetaData.h.
References Rules.
Referenced by FSimulatedNavigationMetaData::FSimulatedNavigationMetaData().
GetFocusDelegate()
const FNavigationDelegate & FNavigationMetaData::GetFocusDelegate (EUINavigation InNavigation) const inline
Get the focus recipient delegate for the provided navigation type.
Parameters
InNavigation the type of navigation to get the focus recipient delegate for
Returns
the focus recipient delegate for the provided navigation type
Definition at line 58 of file NavigationMetaData.h.
References Rules.
GetFocusRecipient()
const TWeakPtr< SWidget > & FNavigationMetaData::GetFocusRecipient (EUINavigation InNavigation) const inline
Get the focus recipient for the provided navigation type.
Parameters
InNavigation the type of navigation to get the focus recipient for
Returns
the focus recipient for the provided navigation type
Definition at line 47 of file NavigationMetaData.h.
References Rules.
Referenced by FSimulatedNavigationMetaData::FSimulatedNavigationMetaData().
SetNavigationCustom()
void FNavigationMetaData::SetNavigationCustom (EUINavigation InNavigation, EUINavigationRule InCustomBoundaryRule, FNavigationDelegate InFocusDelegate) inline
Set the navigation behavior for the provided navigation type to be a custom delegate.
Parameters
InNavigation the type of navigation to set custom
InCustomBoundaryRule
InFocusRecipient the delegate used when the system requests the destination for the custom navigation
Definition at line 83 of file NavigationMetaData.h.
References ensure, and Rules.
SetNavigationEscape()
void FNavigationMetaData::SetNavigationEscape (EUINavigation InNavigation) inline
An event should return a FNavigationReply::Escape() to let the system know that a navigation can escape the bounds of this widget.
Definition at line 116 of file NavigationMetaData.h.
References Rules.
SetNavigationExplicit()
void FNavigationMetaData::SetNavigationExplicit (EUINavigation InNavigation, TSharedPtr< SWidget > InFocusRecipient) inline
Set the navigation behavior for the provided navigation type to be explicit, using a constant widget.
Parameters
InNavigation the type of navigation to set explicit
InFocusRecipient the widget used when the system requests the destination for the explicit navigation
Definition at line 69 of file NavigationMetaData.h.
References Rules.
SetNavigationStop()
void FNavigationMetaData::SetNavigationStop (EUINavigation InNavigation) inline
An event should return a FNavigationReply::Explicit() to let the system know to stop at the bounds of this widget.
Definition at line 106 of file NavigationMetaData.h.
References Rules.
SetNavigationWrap()
void FNavigationMetaData::SetNavigationWrap (EUINavigation InNavigation) inline
Set the navigation behavior for the provided navigation type to be wrap.
Parameters
InNavigation the type of navigation to set wrapping
Definition at line 96 of file NavigationMetaData.h.
References Rules.
SLATE_METADATA_TYPE()
FNavigationMetaData::SLATE_METADATA_TYPE (FNavigationMetaData , ISlateMetaData) inline
Definition at line 18 of file NavigationMetaData.h.
References Rules.
Field Documentation
Rules
SNavData FNavigationMetaData::Rules[(uint8) EUINavigation::Num] private
Definition at line 130 of file NavigationMetaData.h.
Referenced by GetBoundaryRule(), GetFocusDelegate(), GetFocusRecipient(), SetNavigationCustom(), SetNavigationEscape(), SetNavigationExplicit(), SetNavigationStop(), SetNavigationWrap(), and SLATE_METADATA_TYPE().
The documentation for this class was generated from the following file:
NavigationMetaData.h