Unreal Engine 5.6 C++ API: CreateTypeImpl Namespace Reference
CreateTypeImpl Namespace Reference
This is a similar approach to ForEach, above.
Typedefs
using JumpTableType = TJumpTable<TUniquePtr<FMeshAttributeArraySetBase>(uint32), TTupleArity<AttributeTypes>::Value>
Functions
template<uint32 I>
static TUniquePtr< FMeshAttributeArraySetBase > Dispatch (uint32 Extent)
template<uint32... Is>
static constexpr JumpTableType MakeJumpTable (TIntegerSequence< uint32, Is... >)
Detailed Description
This is a similar approach to ForEach, above.
Given a type index, at runtime, we wish to create an attribute array of the corresponding type; essentially a factory.
We generate a jump table at compile time, containing generated functions to register attributes of each type.
Typedef Documentation
JumpTableType
using CreateTypeImpl::JumpTableType = TJumpTable<TUniquePtr<FMeshAttributeArraySetBase>(uint32), TTupleArity<AttributeTypes>::Value>
Definition at line 2377 of file MeshAttributeArray.h.
Function Documentation
Dispatch()
template<uint32 I> TUniquePtr< FMeshAttributeArraySetBase > CreateTypeImpl::Dispatch (uint32 Extent) static
Definition at line 2381 of file MeshAttributeArray.h.
References MakeUnique().
Referenced by MakeJumpTable().
MakeJumpTable()
template<uint32... Is> constexpr JumpTableType CreateTypeImpl::MakeJumpTable (TIntegerSequence< uint32, Is... >) static constexpr
Definition at line 2396 of file MeshAttributeArray.h.
References Dispatch().
Referenced by FAttributesSetEntry::CreateArrayOfType().