Unreal Engine 5.6 C++ API: FLocMetadataValue Class Reference
FLocMetadataValue Class Reference abstract
A Metadata Value is a structure that can be a number of types.
#include "InternationalizationMetadata.h"
Public Member Functions
virtual ~FLocMetadataValue ()=0
virtual TArray< TSharedPtr< FLocMetadataValue > > AsArray ()
Returns this value as an array, throwing an error if this is not an Metadata Array.
virtual bool AsBool ()
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
virtual TSharedPtr< FLocMetadataObject > AsObject ()
Returns this value as an object, throwing an error if this is not an Metadata Object.
virtual FString AsString ()
Returns this value as a string, throwing an error if this is not a Metadata String.
virtual TSharedRef< FLocMetadataValue > Clone () const =0
virtual ELocMetadataType GetType () const =0
bool operator< (const FLocMetadataValue &Other) const
bool operator== (const FLocMetadataValue &Other) const
virtual FString ToString () const =0
Protected Member Functions
FLocMetadataValue ()
virtual bool EqualTo (const FLocMetadataValue &Other) const =0
void ErrorMessage (const FString &InType)
virtual FString GetTypeString () const =0
virtual bool LessThan (const FLocMetadataValue &Other) const =0
Private Member Functions
FLocMetadataValue (const FLocMetadataValue &)
FLocMetadataValue & operator= (const FLocMetadataValue &)
Detailed Description
A Metadata Value is a structure that can be a number of types.
Definition at line 32 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
~FLocMetadataValue()
virtual FLocMetadataValue::~FLocMetadataValue () pure virtual
FLocMetadataValue() [1/2]
FLocMetadataValue::FLocMetadataValue () inline protected
Definition at line 59 of file InternationalizationMetadata.h.
Referenced by FLocMetadataValue(), EqualTo(), FLocMetadataValueArray::EqualTo(), FLocMetadataValueBoolean::EqualTo(), FLocMetadataValueObject::EqualTo(), FLocMetadataValueString::EqualTo(), LessThan(), FLocMetadataValueArray::LessThan(), FLocMetadataValueBoolean::LessThan(), FLocMetadataValueObject::LessThan(), FLocMetadataValueString::LessThan(), operator<(), operator=(), and operator==().
FLocMetadataValue() [2/2]
FLocMetadataValue::FLocMetadataValue (const FLocMetadataValue &) private
References FLocMetadataValue().
Member Function Documentation
AsArray()
virtual TArray< TSharedPtr< FLocMetadataValue > > FLocMetadataValue::AsArray () inline virtual
Returns this value as an array, throwing an error if this is not an Metadata Array.
Reimplemented in FLocMetadataValueArray.
Definition at line 46 of file InternationalizationMetadata.h.
References ErrorMessage(), and TEXT.
AsBool()
virtual bool FLocMetadataValue::AsBool () inline virtual
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
Reimplemented in FLocMetadataValueBoolean.
Definition at line 43 of file InternationalizationMetadata.h.
References ErrorMessage(), and TEXT.
AsObject()
virtual TSharedPtr< FLocMetadataObject > FLocMetadataValue::AsObject () inline virtual
Returns this value as an object, throwing an error if this is not an Metadata Object.
Reimplemented in FLocMetadataValueObject.
Definition at line 49 of file InternationalizationMetadata.h.
References ErrorMessage(), and TEXT.
AsString()
virtual FString FLocMetadataValue::AsString () inline virtual
Returns this value as a string, throwing an error if this is not a Metadata String.
Reimplemented in FLocMetadataValueString.
Definition at line 40 of file InternationalizationMetadata.h.
References ErrorMessage(), and TEXT.
Clone()
virtual TSharedRef< FLocMetadataValue > FLocMetadataValue::Clone () const pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
EqualTo()
virtual bool FLocMetadataValue::EqualTo (const FLocMetadataValue & Other) const protected pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
References FLocMetadataValue(), and Other.
Referenced by operator==().
ErrorMessage()
void FLocMetadataValue::ErrorMessage (const FString & InType) protected
Referenced by AsArray(), AsBool(), AsObject(), and AsString().
GetType()
virtual ELocMetadataType FLocMetadataValue::GetType () const pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
Referenced by operator<(), and operator==().
GetTypeString()
virtual FString FLocMetadataValue::GetTypeString () const protected pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
LessThan()
virtual bool FLocMetadataValue::LessThan (const FLocMetadataValue & Other) const protected pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
References FLocMetadataValue(), and Other.
Referenced by operator<().
operator<()
bool FLocMetadataValue::operator< (const FLocMetadataValue & Other) const inline
Definition at line 56 of file InternationalizationMetadata.h.
References FLocMetadataValue(), GetType(), LessThan(), and Other.
operator=()
FLocMetadataValue & FLocMetadataValue::operator= (const FLocMetadataValue &) private
References FLocMetadataValue().
operator==()
bool FLocMetadataValue::operator== (const FLocMetadataValue & Other) const inline
Definition at line 55 of file InternationalizationMetadata.h.
References FLocMetadataValue(), EqualTo(), GetType(), and Other.
ToString()
virtual FString FLocMetadataValue::ToString () const pure virtual
Implemented in FLocMetadataValueArray, FLocMetadataValueBoolean, FLocMetadataValueObject, and FLocMetadataValueString.
The documentation for this class was generated from the following file:
InternationalizationMetadata.h