Unreal Engine 5.6 C++ API: UBTDecorator_KeepInCone Class Reference
UBTDecorator_KeepInCone Class Reference
#include "BTDecorator_KeepInCone.h"
Protected Member Functions
AIMODULE_API bool CalculateCurrentDirection (const UBehaviorTreeComponent &OwnerComp, FVector &Direction) const
virtual AIMODULE_API void OnBecomeRelevant (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) override
virtual AIMODULE_API void TickNode (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, float DeltaSeconds) override
Private Member Functions
virtual AIMODULE_API void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () typedef FBTKeepInConeDecoratorMemory TNodeInstanceMemory
UPROPERTY() uint32 bUseSelfAsOrigin UPROPERTY() uint32 bUseSelfAsObserved float GetConeHalfAngleDot (const UBehaviorTreeComponent &OwnerComp) const
virtual AIMODULE_API FString GetErrorMessage () const override
virtual AIMODULE_API uint16 GetInstanceMemorySize () const override
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
virtual AIMODULE_API void InitializeFromAsset (UBehaviorTree &Asset) override
virtual AIMODULE_API void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
UPROPERTY () FBlackboardKeySelector ConeOrigin
blackboard key selector
UPROPERTY () FBlackboardKeySelector Observed
blackboard key selector
UPROPERTY () FValueOrBBKey_Float ConeHalfAngle
max allowed time for execution of underlying node
Detailed Description
Definition at line 24 of file BTDecorator_KeepInCone.h.
Member Function Documentation
CalculateCurrentDirection()
AIMODULE_API bool UBTDecorator_KeepInCone::CalculateCurrentDirection (const UBehaviorTreeComponent & OwnerComp, FVector & Direction) const protected
References FVector.
CleanupMemory()
virtual AIMODULE_API void UBTDecorator_KeepInCone::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override private virtual
References CleanupMemory().
Referenced by CleanupMemory().
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_KeepInCone::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues().
Referenced by DescribeRuntimeValues().
GENERATED_UCLASS_BODY()
UBTDecorator_KeepInCone::GENERATED_UCLASS_BODY () private
GetConeHalfAngleDot()
UPROPERTY() uint32 bUseSelfAsOrigin UPROPERTY() uint32 bUseSelfAsObserved float UBTDecorator_KeepInCone::GetConeHalfAngleDot (const UBehaviorTreeComponent & OwnerComp) const private
References GetConeHalfAngleDot().
Referenced by GetConeHalfAngleDot().
GetErrorMessage()
virtual AIMODULE_API FString UBTDecorator_KeepInCone::GetErrorMessage () const override private virtual
GetInstanceMemorySize()
virtual AIMODULE_API uint16 UBTDecorator_KeepInCone::GetInstanceMemorySize () const override private virtual
References GetInstanceMemorySize().
Referenced by GetInstanceMemorySize().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_KeepInCone::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_KeepInCone::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
InitializeFromAsset()
virtual AIMODULE_API void UBTDecorator_KeepInCone::InitializeFromAsset (UBehaviorTree & Asset) override private virtual
References Asset, and InitializeFromAsset().
Referenced by InitializeFromAsset().
InitializeMemory()
virtual AIMODULE_API void UBTDecorator_KeepInCone::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override private virtual
References InitializeMemory().
Referenced by InitializeMemory().
OnBecomeRelevant()
virtual AIMODULE_API void UBTDecorator_KeepInCone::OnBecomeRelevant (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) override protected virtual
TickNode()
virtual AIMODULE_API void UBTDecorator_KeepInCone::TickNode (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, float DeltaSeconds) override protected virtual
UPROPERTY() [1/3]
UBTDecorator_KeepInCone::UPROPERTY () private
blackboard key selector
References Category, and UPROPERTY().
UPROPERTY() [2/3]
UBTDecorator_KeepInCone::UPROPERTY () private
blackboard key selector
References Category, and UPROPERTY().
UPROPERTY() [3/3]
UBTDecorator_KeepInCone::UPROPERTY () private
max allowed time for execution of underlying node
References Category, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
BTDecorator_KeepInCone.h