Unreal Engine 5.6 C++ API: FAssetSourceFilenameCache Class Reference
FAssetSourceFilenameCache Class Reference
Class responsible for maintaing a cache of clean source file names (bla.txt) to asset data.
#include "AssetSourceFilenameCache.h"
Public Member Functions
UNREALED_API FAssetSourceFilenameCache ()
DECLARE_EVENT_TwoParams (FAssetSourceFilenameCache, FAssetRenamedEvent, const FAssetData &, const FString &)
Event for when an asset has been renamed, and has been updated in our source file cache.
UNREALED_API TArray< FAssetData > GetAssetsPertainingToFile (const IAssetRegistry &Registry, const FString &AbsoluteFilename) const
Retrieve a list of assets that were imported from the specified filename.
FAssetRenamedEvent & OnAssetRenamed ()
UNREALED_API void Shutdown ()
Shutdown this instance of the cache.
Static Public Member Functions
static UNREALED_API TOptional< FAssetImportInfo > ExtractAssetImportInfo (const FAssetData &AssetData)
Helper functions to extract asset import information from asset registry tags.
static UNREALED_API FAssetSourceFilenameCache & Get ()
Singleton access.
Private Member Functions
UNREALED_API void HandleOnAssetRenamed (const FAssetData &AssetData, const FString &OldPath)
UNREALED_API void HandleOnAssetsAdded (TConstArrayView< FAssetData > Assets)
Delegate bindings that keep the cache up-to-date.
UNREALED_API void HandleOnAssetsRemoved (TConstArrayView< FAssetData > AssetData)
UNREALED_API void HandleOnAssetUpdated (const FAssetImportInfo &OldData, const UAssetImportData *ImportData)
Private Attributes
FAssetRenamedEvent AssetRenamedEvent
Event that is triggered when an asset has been renamed, and we've updated our cache.
UE::Tasks::FPipe CachePipe
TMap< FString, TSet< FSoftObjectPath > > SourceFileToObjectPathCache
Map of clean filenames (no leading path information) to object paths that were imported with that file.
Detailed Description
Class responsible for maintaing a cache of clean source file names (bla.txt) to asset data.
Definition at line 25 of file AssetSourceFilenameCache.h.
Constructor & Destructor Documentation
FAssetSourceFilenameCache()
UNREALED_API FAssetSourceFilenameCache::FAssetSourceFilenameCache ()
Referenced by DECLARE_EVENT_TwoParams(), and Get().
Member Function Documentation
DECLARE_EVENT_TwoParams()
FAssetSourceFilenameCache::DECLARE_EVENT_TwoParams (FAssetSourceFilenameCache , FAssetRenamedEvent , const FAssetData & , const FString &)
Event for when an asset has been renamed, and has been updated in our source file cache.
References FAssetSourceFilenameCache().
ExtractAssetImportInfo()
UNREALED_API TOptional< FAssetImportInfo > FAssetSourceFilenameCache::ExtractAssetImportInfo (const FAssetData & AssetData) static
Helper functions to extract asset import information from asset registry tags.
Get()
UNREALED_API FAssetSourceFilenameCache & FAssetSourceFilenameCache::Get () static
Singleton access.
References FAssetSourceFilenameCache().
GetAssetsPertainingToFile()
UNREALED_API TArray< FAssetData > FAssetSourceFilenameCache::GetAssetsPertainingToFile (const IAssetRegistry & Registry, const FString & AbsoluteFilename) const
Retrieve a list of assets that were imported from the specified filename.
References Registry.
HandleOnAssetRenamed()
UNREALED_API void FAssetSourceFilenameCache::HandleOnAssetRenamed (const FAssetData & AssetData, const FString & OldPath) private
HandleOnAssetsAdded()
UNREALED_API void FAssetSourceFilenameCache::HandleOnAssetsAdded (TConstArrayView< FAssetData > Assets) private
Delegate bindings that keep the cache up-to-date.
HandleOnAssetsRemoved()
UNREALED_API void FAssetSourceFilenameCache::HandleOnAssetsRemoved (TConstArrayView< FAssetData > AssetData) private
HandleOnAssetUpdated()
UNREALED_API void FAssetSourceFilenameCache::HandleOnAssetUpdated (const FAssetImportInfo & OldData, const UAssetImportData * ImportData) private
OnAssetRenamed()
FAssetRenamedEvent & FAssetSourceFilenameCache::OnAssetRenamed () inline
Definition at line 44 of file AssetSourceFilenameCache.h.
References AssetRenamedEvent.
Shutdown()
UNREALED_API void FAssetSourceFilenameCache::Shutdown ()
Shutdown this instance of the cache.
Field Documentation
AssetRenamedEvent
FAssetRenamedEvent FAssetSourceFilenameCache::AssetRenamedEvent private
Event that is triggered when an asset has been renamed, and we've updated our cache.
Definition at line 54 of file AssetSourceFilenameCache.h.
Referenced by OnAssetRenamed().
CachePipe
UE::Tasks::FPipe FAssetSourceFilenameCache::CachePipe mutable private
Definition at line 57 of file AssetSourceFilenameCache.h.
SourceFileToObjectPathCache
TMap<FString, TSet<FSoftObjectPath> > FAssetSourceFilenameCache::SourceFileToObjectPathCache private
Map of clean filenames (no leading path information) to object paths that were imported with that file.
Definition at line 60 of file AssetSourceFilenameCache.h.
The documentation for this class was generated from the following file:
AssetSourceFilenameCache.h