Unreal Engine 5.6 C++ API: FEditorViewportClient Class Reference
FEditorViewportClient Class Reference
Viewport client for editor viewports.
#include "EditorViewportClient.h"
Data Structures
struct FDropObjectOptions
struct FRealtimeOverride
Temporary realtime overrides and user messages that are not saved between editor sessions.
struct FRequiredCursorState
Used to store the required cursor visibility states and override cursor appearance.
class ICustomTemporalUpscalerData
Public Member Functions
FEditorViewportClient (const FEditorViewportClient &)=delete
Non-copyable.
UNREALED_API FEditorViewportClient (FEditorModeTools *InModeTools, FPreviewScene *InPreviewScene=nullptr, const TWeakPtr< SEditorViewport > &InEditorViewportWidget=nullptr)
virtual UNREALED_API ~FEditorViewportClient ()
UNREALED_API void AddRealtimeOverride (bool bShouldBeRealtime, FText SystemDisplayName)
Overrides the realtime state of this viewport until RemoveViewportsRealtimeOverride is called.
virtual UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector) override
FGCObject interface.
UNREALED_API void AdjustTransformWidgetSize (const int32 SizeDelta)
Adjusts the current transform widget size by the provided delta value.
virtual UNREALED_API bool BeginTransform (const FGizmoState &InState)
virtual UNREALED_API FSceneView * CalcSceneView (FSceneViewFamily *ViewFamily, const int32 StereoViewIndex=INDEX_NONE)
Configures the specified FSceneView object with the view and projection matrices for this viewport.
virtual UNREALED_API FMatrix CalcViewRotationMatrix (const FRotator &InViewRotation) const
Computes a matrix to use for viewport location and rotation.
virtual UNREALED_API FMatrix CalcViewRotationMatrixForControllingActorView (const FRotator &InViewRotation) const
virtual bool CanCycleWidgetMode () const
Whether or not the widget mode can be cycled.
virtual FDropQuery CanDropObjectsAtCoordinates (int32 MouseX, int32 MouseY, const FAssetData &AssetInfo)
Checks the viewport to see if the given object can be dropped using the given mouse coordinates local to this viewport.
virtual UNREALED_API bool CanSetWidgetMode (UE::Widget::EWidgetMode NewMode) const
Whether or not the new widget mode can be set in this viewport.
virtual UNREALED_API bool CanUseDragTool () const
virtual UNREALED_API void CapturedMouseMove (FViewport *InViewport, int32 InMouseX, int32 InMouseY) override
Called when the mouse is moved while a window input capture is in effect.
UNREALED_API void CenterViewportAtPoint (const FVector &NewLookAt, bool bInstant=false)
Translates the viewport so that the given LookAt point is at the center of viewport, while maintaining current Location/LookAt distance.
UNREALED_API void ChangeActorColorationVisualizationMode (FName InName)
Changes the actor coloration visualization mode for this viewport.
UNREALED_API void ChangeBufferVisualizationMode (FName InName)
Changes the buffer visualization mode for this viewport.
UNREALED_API void ChangeGPUSkinCacheVisualizationMode (FName InName)
Changes the GPU Skin Cache visualization mode for this viewport.
UNREALED_API void ChangeGroomVisualizationMode (FName InName)
Changes the Groom visualization mode for this viewport.
UNREALED_API void ChangeLumenVisualizationMode (FName InName)
Changes the Lumen visualization mode for this viewport.
UNREALED_API void ChangeNaniteVisualizationMode (FName InName)
Changes the Nanite visualization mode for this viewport.
UNREALED_API void ChangeRayTracingDebugVisualizationMode (FName InName)
Changes the ray tracing debug visualization mode for this viewport.
UNREALED_API void ChangeSubstrateVisualizationMode (FName InName)
Changes the Substrate visualization mode for this viewport.
UNREALED_API void ChangeVirtualShadowMapVisualizationMode (FName InName)
Changes the virtual shadow map visualization mode for this viewport.
UNREALED_API void ChangeVirtualTextureVisualizationMode (FName InName)
Changes the virtual texture visualization mode for this viewport.
virtual UNREALED_API void CheckHoveredHitProxy (HHitProxy *HoveredHitProxy)
Called when the mouse cursor is hovered over a hit proxy.
void ClearAudioFocus ()
UNREALED_API void ConvertMovementToDragRot (const FVector &InDelta, FVector &InDragDelta, FRotator &InRotDelta) const
Converts a generic movement delta into drag/rotation deltas based on the viewport and keys held down.
UNREALED_API void ConvertMovementToOrbitDragRot (const FVector &InDelta, FVector &InDragDelta, FRotator &InRotDelta) const
virtual void DestroyDropPreviewActors ()
If dragging an actor for placement, this function destroys the actor.
virtual void DestroyDropPreviewElements ()
If dragging items for placement, this function destroys the items.
UNREALED_API void DisableOverrideEngineShowFlags ()
Disable EngineShowFlags override if enabled.
UNREALED_API bool DoRealtimeAndOverridesMatch (bool bInValue) const
virtual UNREALED_API void Draw (const FSceneView *View, FPrimitiveDrawInterface *PDI) override
FViewElementDrawer interface.
virtual UNREALED_API void Draw (FViewport *Viewport, FCanvas *Canvas) override
UNREALED_API void DrawActorScreenSpaceBoundingBox (FCanvas *InCanvas, const FSceneView *InView, FViewport *InViewport, AActor *InActor, const FLinearColor &InColor, const bool bInDrawBracket, const FString &InLabelText=TEXT(""))
Draws a screen space bounding box around the specified actor.
UNREALED_API void DrawBoundingBox (FBox &Box, FCanvas *InCanvas, const FSceneView *InView, const FViewport *InViewport, const FLinearColor &InColor, const bool bInDrawBracket, const FString &InLabelText)
virtual UNREALED_API void DrawCanvas (FViewport &InViewport, FSceneView &View, FCanvas &Canvas)
Called to draw onto the viewports 2D canvas.
virtual UNREALED_API void DrawPreviewLightVisualization (const FSceneView *View, FPrimitiveDrawInterface *PDI)
virtual UNREALED_API bool DropObjectsAtCoordinates (int32 MouseX, int32 MouseY, const TArray< UObject * > &DroppedObjects, TArray< FTypedElementHandle > &OutNewObjects, const FDropObjectOptions &Options=FDropObjectOptions())
Attempts to intelligently drop the given objects in the viewport, using the given mouse coordinates local to this viewport.
UNREALED_API void EnableOverrideEngineShowFlags (TUniqueFunction< void(FEngineShowFlags &)> OverrideFunc)
Enable customization of the EngineShowFlags for rendering.
virtual UNREALED_API bool EndTransform (const FGizmoState &InState)
UNREALED_API void FocusViewportOnBox (const FBox &BoundingBox, bool bInstant=false)
Focuses the viewport to the center of the bounding box ensuring that the entire box is in view.
virtual UNREALED_API FLinearColor GetBackgroundColor () const
virtual uint32 GetCachedMouseX () const
virtual uint32 GetCachedMouseY () const
FEditorCameraController * GetCameraController (void)
UNREALED_API float GetCameraSpeed () const
Get the camera speed for this viewport.
UNREALED_API float GetCameraSpeed (int32 SpeedSetting) const
Get the camera speed for this viewport based on the specified speed setting.
virtual UNREALED_API float GetCameraSpeedScalar () const
Get the camera speed scalar for this viewport.
virtual UNREALED_API int32 GetCameraSpeedSetting () const
Get the camera speed setting for this viewport.
UNREALED_API FText GetCurrentActorColorationVisualizationModeDisplayName () const
Returns the FText display name associated with current actor coloration visualization mode.
UNREALED_API FText GetCurrentBufferVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentBufferVisualizationMode.
UNREALED_API FText GetCurrentGPUSkinCacheVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentGPUSkinCacheVisualizationMode.
UNREALED_API FText GetCurrentGroomVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentGroomVisualizationMode.
UNREALED_API FText GetCurrentLumenVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentLumenVisualizationMode.
UNREALED_API FText GetCurrentNaniteVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentNaniteVisualizationMode.
UNREALED_API FText GetCurrentSubstrateVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentSubstrateVisualizationMode.
UNREALED_API FText GetCurrentVirtualShadowMapVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentVirtualShadowMapVisualizationMode.
UNREALED_API FText GetCurrentVirtualTextureVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentVirtualTextureVisualizationMode.
UNREALED_API EAxisList::Type GetCurrentWidgetAxis () const
virtual UNREALED_API EMouseCursor::Type GetCursor (FViewport *Viewport, int32 X, int32 Y) override
Retrieves the cursor that should be displayed by the OS.
UNREALED_API FViewportCursorLocation GetCursorWorldLocationFromMousePos ()
Gets the world space cursor info from the current mouse position.
TSharedPtr< ICustomTemporalUpscalerData > GetCustomTemporalUpscalerData () const
UNREALED_API float GetDefaultPrimaryResolutionFractionTarget () const
TSharedPtr< SEditorViewport > GetEditorViewportWidget () const
Get the editor viewport widget.
virtual UNREALED_API const TArray< FString > * GetEnabledStats () const override
Get a ptr to the enabled stats list.
UNREALED_API float GetFarClipPlaneOverride () const
Get the far clipping plane override for this viewport.
UNREALED_API FVector GetHitProxyObjectLocation (int32 X, int32 Y)
Returns the location of the object at the given viewport X,Y.
bool GetIsCurrentLevelEditingFocus () const
virtual UNREALED_API FMatrix GetLocalCoordinateSystem () const
const FVector & GetLookAtLocation () const
FEditorModeTools * GetModeTools () const
Editor mode tool manager being used for this viewport client.
FMouseDeltaTracker * GetMouseDeltaTracker () const
Mouse info is usually transformed to gizmo space before FEdMode handles it, this allows raw delta X and Y access.
UNREALED_API float GetNearClipPlane () const
Get the near clipping plane for this viewport.
UNREALED_API float GetOrthoUnitsPerPixel (const FViewport *Viewport) const
EViewModeIndex GetOrthoViewMode () const
float GetOrthoZoom () const
EViewModeIndex GetPerspViewMode () const
virtual UNREALED_API bool GetPivotForOrbit (FVector &OutPivot) const
Get the custom pivot point around which the camera should orbit for this viewport.
FPreviewScene * GetPreviewScene ()
Retrieves the FPreviewScene used by this instance of FEditorViewportClient.
UNREALED_API int32 GetPreviewScreenPercentage () const
UNREALED_API FText GetRealtimeOverrideMessage () const
virtual UNREALED_API FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual UNREALED_API FSceneInterface * GetScene () const
UNREALED_API float GetSceneDepthAtLocation (int32 X, int32 Y)
Returns the scene depth at the given viewport X,Y.
UNREALED_API bool GetShowWidget () const
virtual UNREALED_API FStatHitchesData * GetStatHitchesData () const override
Get a ptr to the stat unit data for this viewport.
virtual UNREALED_API FStatUnitData * GetStatUnitData () const override
Get a ptr to the stat unit data for this viewport.
const FVector & GetViewLocation () const
UNREALED_API EViewModeIndex GetViewMode () const
TMap< int32, FName > & GetViewModeParamNameMap ()
Returns the map allowing to convert from the viewmode param to a name.
UNREALED_API void GetViewportDimensions (FIntPoint &OutOrigin, FIntPoint &OutSize)
Gets the dimensions of the viewport.
virtual UNREALED_API ELevelViewportType GetViewportType () const
Returns the effective viewport type (taking into account any actor locking or camera possession)
const FRotator & GetViewRotation () const
UNREALED_API EViewStatusForScreenPercentage GetViewStatusForScreenPercentage () const
FViewportCameraTransform & GetViewTransform ()
Gets ViewportCameraTransform object for the current viewport type.
const FViewportCameraTransform & GetViewTransform () const
virtual UNREALED_API FMatrix GetWidgetCoordSystem () const
virtual UNREALED_API ECoordSystem GetWidgetCoordSystemSpace () const
virtual UNREALED_API FVector GetWidgetLocation () const
virtual UNREALED_API UE::Widget::EWidgetMode GetWidgetMode () const
virtual UNREALED_API UWorld * GetWorld () const override
Use the viewports Scene to get a world.
virtual UNREALED_API bool HandleIsShowFlagEnabled (FEngineShowFlags::EShowFlag EngineShowFlagIndex) const
Delegate handler fired to determine the state of a show flag.
virtual UNREALED_API void HandleToggleShowFlag (FEngineShowFlags::EShowFlag EngineShowFlagIndex)
Delegate handler fired when a show flag is toggled.
virtual bool HasDropPreviewActors () const
Returns true if a placement dragging actor exists.
virtual bool HasDropPreviewElements () const
Returns true if a placement drag preview elements exists.
UNREALED_API bool HasRealtimeOverride (FText SystemDisplayName) const
Returns whether there's a realtime override registered with the given system name.
virtual UNREALED_API bool InputAxis (const FInputKeyEventArgs &Args) override
Check an axis movement received by the viewport.
UNREALED_API void InputAxisForOrbit (FViewport *Viewport, const FVector &DragDelta, FVector &Drag, FRotator &Rot)
virtual UNREALED_API bool InputGesture (FViewport *Viewport, const FInputDeviceId DeviceId, EGestureEvent GestureType, const FVector2D &GestureDelta, bool bIsDirectionInvertedFromDevice, const uint64 Timestamp) override
Check a gesture event received by the viewport.
virtual UNREALED_API bool InputKey (const FInputKeyEventArgs &EventArgs) override
Check a key event received by the viewport.
UNREALED_API bool InputTakeScreenshot (FViewport *Viewport, FKey Key, EInputEvent Event)
Implements screenshot capture for editor viewports.
virtual UNREALED_API bool InputWidgetDelta (FViewport *InViewport, EAxisList::Type CurrentAxis, FVector &Drag, FRotator &Rot, FVector &Scale)
Called to give the viewport client a chance to handle widgets being moved.
UNREALED_API void Invalidate (bool bInvalidateChildViews=true, bool bInvalidateHitProxies=true)
Invalidates this viewport and optionally child views.
UNREALED_API bool IsActiveViewportType (ELevelViewportType InViewportType) const
UNREALED_API bool IsActiveViewportTypeInRotation () const
UNREALED_API bool IsActorColorationVisualizationModeSelected (FName InName) const
Checks if an actor coloration visualization mode is selected.
UNREALED_API bool IsAltPressed () const
virtual UNREALED_API bool IsAspectRatioConstrained () const
Is the aspect ratio currently constrained?
UNREALED_API bool IsBufferVisualizationModeSelected (FName InName) const
Checks if a buffer visualization mode is selected.
UNREALED_API bool IsCameraLocked () const
Callback for checking the camera lock flag.
UNREALED_API bool IsCmdPressed () const
UNREALED_API bool IsCommandChordPressed (const TSharedPtr< FUICommandInfo > InCommand, FKey InOptionalKey=FKey()) const
Utility function to return whether the command accepts the key states.
UNREALED_API bool IsCtrlPressed () const
bool IsEngineShowFlagsOverrideEnabled () const
UNREALED_API bool IsFlightCameraActive () const
Returns whether or not the flight camera is active.
bool IsForcedRealtimeAudio () const
UNREALED_API bool IsGPUSkinCacheVisualizationModeSelected (FName InName) const
Checks if a GPU Skin Cache visualization mode is selected.
UNREALED_API bool IsGroomVisualizationModeSelected (FName InName) const
Checks if a Groom visualization mode is selected.
virtual bool IsInGameView () const override
Returns true if this viewport is excluding non-game elements from its display.
UNREALED_API bool IsInImmersiveViewport () const
virtual bool IsLevelEditorClient () const
If true, this is a level editor viewport.
UNREALED_API bool IsLowDPIPreview () const
UNREALED_API bool IsLumenVisualizationModeSelected (FName InName) const
Checks if a Lumen visualization mode is selected.
UNREALED_API bool IsMovingCamera () const
UNREALED_API bool IsNaniteVisualizationModeSelected (FName InName) const
Checks if a Nanite visualization mode is selected.
virtual UNREALED_API bool IsOrtho () const override
Returns true if this viewport is orthogonal.
UNREALED_API bool IsPerspective () const
Returns true if this viewport is perspective.
UNREALED_API bool IsPreviewingScreenPercentage () const
UNREALED_API bool IsPrioritizedInputChordPressed (const FName InInputCordName) const
UNREALED_API bool IsRayTracingDebugVisualizationModeSelected (FName InName) const
Checks if a ray tracing debug visualization mode is selected.
bool IsRealtime () const
bool IsRealtimeOverrideSet () const
UNREALED_API bool IsSetShowBoundsChecked () const
Callback for checking the bounds show flag.
UNREALED_API bool IsSetShowCollisionChecked () const
Callback for checking the collision geometry show flag.
UNREALED_API bool IsSetShowGridChecked () const
Callback for checking the grid show flag.
UNREALED_API bool IsShiftPressed () const
bool IsShowingAspectRatioBarDisplay () const
bool IsShowingSafeFrameBoxDisplay () const
bool IsSimulateInEditorViewport () const
virtual UNREALED_API bool IsStatEnabled (const FString &InName) const override
Check whether a specific stat is enabled for this viewport.
UNREALED_API bool IsSubstrateVisualizationModeSelected (FName InName) const
Checks if a Substrate visualization mode is selected.
bool IsTracking () const
UNREALED_API bool IsUsingAbsoluteTranslation (bool bAlsoCheckAbsoluteRotation=false) const
Determines whether this viewport is currently allowed to use Absolute Movement.
bool IsViewModeEnabled (EViewModeIndex InViewModeIndex) const
UNREALED_API bool IsViewModeParam (int32 InViewModeParam) const
UNREALED_API bool IsVirtualShadowMapVisualizationModeSelected (FName InName) const
Checks if a virtual shadow map visualization mode is selected.
UNREALED_API bool IsVirtualTextureVisualizationModeSelected (FName InName) const
Checks if a virtual texture visualization mode is selected.
UNREALED_API bool IsVisualizeCalibrationMaterialEnabled () const
Returns whether visualize debug material is enabled.
virtual UNREALED_API void LostFocus (FViewport *Viewport) override
virtual UNREALED_API TSharedPtr< FDragTool > MakeDragTool (EDragTool::Type DragToolType)
Called to make a drag tool when the user starts dragging in the viewport.
UNREALED_API void MarkMouseMovedSinceClick ()
virtual UNREALED_API void MouseEnter (FViewport *Viewport, int32 x, int32 y) override
virtual UNREALED_API void MouseLeave (FViewport *Viewport) override
virtual UNREALED_API void MouseMove (FViewport *Viewport, int32 x, int32 y) override
UNREALED_API void MoveViewportCamera (const FVector &InDrag, const FRotator &InRot, bool bDollyCamera=false)
Moves the viewport Scamera according to the specified drag and rotation.
UNREALED_API void OnEditorModeIDChanged (const FEditorModeID &EditorModeID, bool bIsEntering)
Called when an editor mode has been (de)activated.
UNREALED_API void OpenScreenshot (FString SourceFilePath)
Opens the screenshot in the uses default bitmap viewer (determined by OS)
FEditorViewportClient & operator= (const FEditorViewportClient &)=delete
UNREALED_API void OverrideFarClipPlane (const float InFarPlane)
Override the far clipping plane.
UNREALED_API void OverrideNearClipPlane (float InNearPlane)
Override the near clipping plane.
virtual void OverridePostProcessSettings (FSceneView &View)
Called to override any post process settings for the view.
UNREALED_API void PeformDefaultCameraMovement (FVector &Drag, FRotator &Rot, FVector &Scale)
Perform default camera movement that would normally happen* This can be used by systems to override how the camera is triggered.
UNREALED_API bool PopRealtimeOverride ()
Removes the last added realtime override.
virtual UNREALED_API void ProcessAccumulatedPointerInput (FViewport *InViewport) override
Called from slate when input is finished for this frame, and we should process any queued mouse moves.
virtual UNREALED_API void ProcessClick (FSceneView &View, HHitProxy *HitProxy, FKey Key, EInputEvent Event, uint32 HitX, uint32 HitY)
Called when the user clicks in the viewport.
virtual UNREALED_API bool ProcessScreenShots (FViewport *Viewport) override
FViewportClient interface.
virtual UNREALED_API void ReceivedFocus (FViewport *Viewport) override
virtual UNREALED_API void RedrawRequested (FViewport *Viewport) override
UNREALED_API void RegisterPrioritizedInputChord (const FPrioritizedInputChord &InInputCord)
void RemoveCameraRoll ()
UNREALED_API bool RemoveRealtimeOverride (FText SystemDisplayName, bool bCheckMissingOverride=true)
Removes the most recent realtime override registered with the given system name.
UNREALED_API void RenderDragTool (const FSceneView *View, FCanvas *Canvas)
Render the drag tool in the viewport.
virtual UNREALED_API void RequestInvalidateHitProxy (FViewport *Viewport) override
virtual void RequestRealTimeFrames (uint64 NumRealTimeFrames=1)
Get the number of real-time frames to draw (overrides bRealtime)
virtual UNREALED_API void RotateViewportType ()
Rotate through viewport view options.
UNREALED_API void SaveRealtimeStateToConfig (bool &ConfigVar) const
Saves the realtime state to a config location.
void SetAudioFocus ()
virtual UNREALED_API void SetCameraLock ()
Callback for toggling the camera lock flag.
UNREALED_API void SetCameraSetup (const FVector &LocationForOrbiting, const FRotator &InOrbitRotation, const FVector &InOrbitZoom, const FVector &InOrbitLookAt, const FVector &InViewLocation, const FRotator &InViewRotation)
virtual UNREALED_API void SetCameraSpeedScalar (float SpeedScalar)
Set the camera speed scalar for this viewport.
virtual UNREALED_API void SetCameraSpeedSetting (int32 SpeedSetting)
Set the speed setting for the camera in this viewport.
virtual UNREALED_API void SetCurrentWidgetAxis (EAxisList::Type InAxis)
Sets the current axis being manipulated by the transform widget.
void SetCustomTemporalUpscalerData (TSharedPtr< ICustomTemporalUpscalerData > InCustomTemporalUpscalerData)
virtual UNREALED_API void SetEnabledStats (const TArray< FString > &InEnabledStats) override
Sets all the stats that should be enabled for the viewport.
void SetForcedAudioRealtime (bool bShouldForceAudioRealtime)
true to force realtime audio to be true, false to stop forcing it
UNREALED_API void SetGameView (bool bGameViewEnable)
UNREALED_API void SetInitialViewTransform (ELevelViewportType ViewportType, const FVector &ViewLocation, const FRotator &ViewRotation, float InOrthoZoom)
void SetIsCurrentLevelEditingFocus (bool bInIsCurrentLevelEditingFocus)
void SetLookAtLocation (const FVector &LookAt, bool bRecalculateView=false)
Sets the look at location of the viewports camera for orbit *.
UNREALED_API void SetLowDPIPreview (bool LowDPIPreview)
Set whether previewing for low DPI.
void SetOrthoZoom (float InOrthoZoom)
Sets ortho zoom amount.
UNREALED_API void SetPreviewingScreenPercentage (bool bIsPreviewing)
Sets whether preview screen percentage for UI.
UNREALED_API void SetPreviewScreenPercentage (int32 PreviewScreenPercentage)
Set preview screen percentage on UI behalf.
UNREALED_API void SetRealtime (bool bInRealtime)
Sets whether or not the viewport updates in realtime.
UNREALED_API void SetRequiredCursorOverride (bool WantOverride, EMouseCursor::Type RequiredCursor=EMouseCursor::Default)
Overrides current cursor.
void SetShowAspectRatioBarDisplay (bool bEnable)
Aspect ratio bar display settings.
UNREALED_API void SetShowBounds (bool bShow)
Sets the show bounds flag.
UNREALED_API void SetShowCollision ()
Callback for toggling the collision geometry show flag.
UNREALED_API void SetShowGrid ()
Callback for toggling the grid show flag.
void SetShowSafeFrameBoxDisplay (bool bEnable)
virtual UNREALED_API void SetShowStats (bool bWantStats) override
Sets whether or not stats info is displayed over the viewport.
virtual UNREALED_API void SetupViewForRendering (FSceneViewFamily &ViewFamily, FSceneView &View)
Called to do any additional set up of the view for rendering.
void SetViewLocation (const FVector &NewLocation)
Sets the location of the viewport's camera.
UNREALED_API void SetViewLocationForOrbiting (const FVector &LookAtPoint, float DistanceToCamera=256.f)
Sets the camera view location such that the LookAtPoint point is at the specified location.
virtual UNREALED_API void SetViewMode (EViewModeIndex InViewModeIndex)
Sets how the viewport is displayed (lit, wireframe, etc) for the current viewport type.
UNREALED_API void SetViewModeParam (int32 InViewModeParam)
Set the viewmode param.
UNREALED_API void SetViewModes (const EViewModeIndex InPerspViewModeIndex, const EViewModeIndex InOrthoViewModeIndex)
Sets how the viewport is displayed (lit, wireframe, etc)
virtual UNREALED_API void SetViewportType (ELevelViewportType InViewportType)
Set the viewport type of the client.
void SetViewRotation (const FRotator &NewRotation)
Sets the location of the viewport's camera.
virtual UNREALED_API void SetVREditView (bool bGameViewEnable)
virtual UNREALED_API void SetWidgetCoordSystemSpace (ECoordSystem NewCoordSystem)
Sets the coordinate system space to use.
virtual UNREALED_API void SetWidgetMode (UE::Widget::EWidgetMode NewMode)
Sets the current widget mode.
UNREALED_API void SetWidgetModeOverride (UE::Widget::EWidgetMode InWidgetMode)
Overrides current widget mode.
virtual UNREALED_API bool ShouldLockPitch () const
virtual UNREALED_API bool ShouldOrbitCamera () const
virtual UNREALED_API bool ShouldScaleCameraSpeedByDistance () const
bool ShouldShowStats () const
Returns true if status information should be displayed over the viewport.
UNREALED_API void ShowWidget (const bool bShow)
Show or hide the widget.
UNREALED_API bool SupportsLowDPIPreview () const
UNREALED_API bool SupportsPreviewResolutionFraction () const
UNREALED_API void TakeHighResScreenShot ()
UNREALED_API void TakeScreenshot (FViewport *Viewport, bool bInvalidateViewport)
Takes the screenshot capture, this is called by keybinded events as well InputTakeScreenshot.
virtual UNREALED_API void Tick (float DeltaSeconds)
Ticks this viewport client.
UNREALED_API void ToggleOrbitCamera (bool bEnableOrbitCamera)
Toggle between orbit camera and fly camera.
UNREALED_API bool ToggleRealtime ()
Toggles whether or not the viewport updates in realtime and returns the updated state.
UNREALED_API void ToggleShowBounds ()
Callback for toggling the bounds show flag.
virtual void TrackingStarted (const struct FInputEventState &InInputState, bool bIsDraggingWidget, bool bNudge)
Called when mouse movement tracking begins.
virtual void TrackingStopped ()
Called when mouse movement tracking stops.
UNREALED_API FVector TranslateDelta (FKey InKey, float InDelta, bool InNudge)
Determines which axis InKey and InDelta most refer to and returns a corresponding FVector.
UE_DEPRECATED (4.25, "SetRealtime no longer takes in bStoreCurrentValue parameter. For temporary overrides use AddRealtimeOverride") UNREALED_API void SetRealtime(bool bInRealtime
UE_DEPRECATED (4.25, "To save and restore realtime state non-permanently use AddRealtimeOverride and RemoveRealtimeOverride") UNREALED_API void RestoreRealtime(const bool bAllowDisable
Restores realtime setting to stored value.
UE_DEPRECATED (5.0, "This function is meant for legacy edge cases (pre-UAssetEditor), where the toolkit may not be the original owner of the mode manager.") UNREALED_API void TakeOwnershipOfModeManager(TSharedPtr< FEditorModeTools > &ModeManagerPtr)
Legacy adapter for a toolkit to take ownership of a mode manager that may have been created by this viewport client.
UE_DEPRECATED (5.4, "Use the overload that takes FDropObjectOptions instead.") UNREALED_API virtual bool DropObjectsAtCoordinates(int32 MouseX
UNREALED_API void UnregisterPrioritizedInputChord (const FName InInputCordName)
virtual bool UpdateDropPreviewActors (int32 MouseX, int32 MouseY, const TArray< UObject * > &DroppedObjects, bool &out_bDroppedObjectsVisible, UActorFactory *FactoryToUse=nullptr)
If dragging an actor for placement, this function updates its position.
virtual bool UpdateDropPreviewElements (int32 MouseX, int32 MouseY, const TArray< UObject * > &DroppedObjects, bool &out_bDroppedObjectsVisible, TScriptInterface< IAssetFactoryInterface > Factory=nullptr)
If dragging items for placement, this function updates their position.
virtual UNREALED_API void UpdateGestureDelta ()
Called each frame to update the viewport based on delta trackpad gestures.
UNREALED_API void UpdateHiddenCollisionDrawing ()
When collision draw mode changes, this function allows hidden objects to be drawn, so hidden colliding objects can be seen.
virtual void UpdateLinkedOrthoViewports (bool bInvalidate=false)
virtual UNREALED_API void UpdateMouseDelta ()
Called each frame to update the viewport based on delta mouse movements.
Public Member Functions inherited from FCommonViewportClient
FCommonViewportClient ()
virtual ~FCommonViewportClient () override
void DrawHighResScreenshotCaptureRegion (FCanvas &Canvas)
float GetDPIDerivedResolutionFraction () const
virtual float GetDPIScale () const override
void RequestUpdateDPIScale ()
Tells this viewport to update editor dpi scale when needed.
Public Member Functions inherited from FViewportClient
virtual ~FViewportClient ()
virtual void Activated (FViewport *Viewport, const FWindowActivateEvent &InActivateEvent)
virtual bool CaptureMouseOnLaunch ()
Gets whether or not the viewport captures the Mouse on launch of the application Technically this controls capture on the first window activate, so in situations where the application is launched but isn't activated the effect is delayed until activation.
virtual void CloseRequested (FViewport *Viewport)
virtual void ConditionalRestoreWorld (class UWorld *InWorld)
Restores GWorld to InWorld.
virtual class UWorld * ConditionalSetWorld ()
Sets GWorld to the appropriate world for this client.
virtual void Deactivated (FViewport *Viewport, const FWindowActivateEvent &InActivateEvent)
virtual EMouseCaptureMode GetMouseCaptureMode () const
Gets the mouse capture behavior when the viewport is clicked.
virtual bool HandleNavigation (const uint32 InUserIndex, TSharedPtr< SWidget > InDestination)
Optionally do custom handling of a navigation.
virtual bool HideCursorDuringCapture () const
Gets whether or not the cursor is hidden when the viewport captures the mouse.
virtual bool IgnoreInput ()
Check whether we should ignore input.
virtual bool InputChar (FViewport *Viewport, int32 ControllerId, TCHAR Character)
Check a character input received by the viewport.
virtual bool InputMotion (FViewport *Viewport, const FInputDeviceId DeviceId, const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, const uint64 Timestamp)
Each frame, the input system will update the motion data.
virtual bool InputTouch (FViewport *Viewport, const FInputDeviceId DeviceId, uint32 Handle, ETouchType::Type Type, const FVector2D &TouchLocation, float Force, uint32 TouchpadIndex, const uint64 Timestamp)
Check a key event received by the viewport.
virtual bool IsFocused (FViewport *Viewport)
virtual bool IsInPermanentCapture ()
virtual bool LockDuringCapture ()
Gets whether or not the cursor is locked to the viewport when the viewport captures the mouse.
virtual TOptional< TSharedRef< SWidget > > MapCursor (FViewport *Viewport, const FCursorReply &CursorReply)
Called to map a cursor reply to an actual widget to render.
virtual FPopupMethodReply OnQueryPopupMethod () const
Should we make new windows for popups or create an overlay in the current window.
virtual bool OverrideHighResScreenshotCaptureRegion (FIntRect &OutCaptureRegion)
Allow viewport client to override the current capture region.
virtual void Precache ()
virtual TOptional< bool > QueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual bool RequiresHitProxyStorage ()
virtual bool RequiresKeyboardInput () const
Determine if the viewport client is going to need any keyboard input.
virtual bool RequiresUncapturedAxisInput () const
Determines whether this viewport client should receive calls to InputAxis() if the game's window is not currently capturing the mouse.
virtual void SetIsSimulateInEditorViewport (bool bInIsSimulateInEditorViewport)
virtual bool ShouldAlwaysLockMouse ()
Gets whether or not the cursor should always be locked to the viewport.
virtual bool ShouldDPIScaleSceneCanvas () const
UE_DEPRECATED (5.6, "This function will be removed in a future release.") virtual bool WantsPollingMouseMovement(void) const
UE_DEPRECATED (5.6, "Use the version of InputAxis which takes in a FInputKeyEventArgs instead.") 1 virtual bool InputAxis(FViewport *Viewport
Check an axis movement received by the viewport.
UE_DEPRECATED (5.6, "Use the version which takes a uint64 timestamp instead") 1 virtual bool InputTouch(FViewport *Viewport
Check a key event received by the viewport.
UE_DEPRECATED (5.6, "Use the version which takes in a FInputDeviceId and a timestamp instead") 1 virtual bool InputMotion(FViewport *Viewport
Each frame, the input system will update the motion data.
UE_DEPRECATED (5.6, "Use the version which takes in a FInputDeviceId and uint64 Timestamp instead.") 1 virtual bool InputGesture(FViewport *Viewport
Check a gesture event received by the viewport.
virtual bool WindowCloseRequested ()
Called when the top level window associated with the viewport has been requested to close.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static UNREALED_API FString UnrealUnitsToSiUnits (float UnrealUnits)
Get a prettified string representation of the specified unreal units.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Data Fields
float AspectRatio
int32 const TArray< UObject * > TArray< AActor * > bool bool bCreateDropPreview = false
bool bDisableInput
true if all input is rejected from this viewport
bool bDrawAxes
If true, draw the axis indicators when the viewport is perspective.
bool bDrawAxesGame
If true, draw the axis indicators when EngineShowFlags.Game is set.
bool bDrawVertices
If true, draw vertices for selected BSP brushes and static meshes if the large vertices show flag is set.
bool bForcingUnlitForNewMap
true if we've forced the SHOW_Lighting show flag off because there are no lights in the scene
bool bLockFlightCamera
Flag to lock the viewport fly camera.
bool bNeedsInvalidateHitProxy
If, following the next redraw, we should invalidate hit proxies on the viewport.
bool bNeedsLinkedRedraw
bool bNeedsRedraw
The number of pending viewport redraws.
int32 const TArray< UObject * > TArray< AActor * > bool bOnlyDropOnTarget = false
int32 const TArray< UObject * > TArray< AActor * > bool bool bool bSelectActors = true
bool bSetListenerPosition
If true, the listener position will be set.
bool bShouldApplyViewModifiers
Whether view modifiers should be called and applied.
bool bStoreCurrentValue
bool bUseNumpadCameraControl
If true, numpad keys will be used to move camera in perspective viewport.
bool bUsingOrbitCamera
True if the orbit camera is currently being used.
bool bWidgetAxisControlledByDrag
true if the widget's axis is being controlled by an active mouse drag.
FName CurrentBufferVisualizationMode
FName CurrentGPUSkinCacheVisualizationMode
FName CurrentGroomVisualizationMode
FName CurrentLumenVisualizationMode
FName CurrentNaniteVisualizationMode
FName CurrentRayTracingDebugVisualizationMode
FName CurrentSubstrateVisualizationMode
FName CurrentVirtualShadowMapVisualizationMode
FName CurrentVirtualTextureVisualizationMode
int32 const TArray< UObject * > & DroppedObjects
FEngineShowFlags EngineShowFlags
A set of flags that determines visibility for various scene elements.
FExposureSettings ExposureSettings
Editor setting to allow designers to override the automatic expose.
int32 const TArray< UObject * > TArray< AActor * > bool bool bool UActorFactory * FactoryToUse
float FOVAngle
Viewport's stored horizontal field of view (saved in ini files).
int32 FramesSinceLastDraw
The number of frames since this viewport was last drawn.
FViewportStateGetter ImmersiveDelegate
Delegate used to get whether or not this client is in an immersive viewport.
int8 LandscapeLODOverride
FEngineShowFlags LastEngineShowFlags
Previous value for engine show flags, used for toggling.
int32 MouseY
int32 const TArray< UObject * > TArray< AActor * > & OutNewActors
TArray< FSceneViewStateReference > StereoViewStates
Viewport view state when stereo rendering is enabled.
float ViewFOV
Viewport's current horizontal field of view (can be modified by locked cameras etc.)
int32 ViewIndex
Index of this view in the editor's list of views.
FEditorViewportViewModifierDelegate ViewModifiers
List of view modifiers to apply on view parameters.
FViewport * Viewport
ELevelViewportType ViewportType
The viewport type.
FSceneViewStateReference ViewState
The viewport's scene view state.
FViewportCameraTransform ViewTransformOrthographic
Viewport camera transform data for orthographic viewports.
FViewportCameraTransform ViewTransformPerspective
Viewport camera transform data for perspective viewports.
FViewportStateGetter VisibilityDelegate
Delegate used to get the visibility of this client from a slate viewport layout and tab configuration.
float WireframeOpacity = 0.2f
Editor setting to adjust wireframe opacity.
Data Fields inherited from FViewportClient
FInputDeviceId FKey float float int32 bool bGamepad = false) final
int32 ControllerId
FInputDeviceId FKey float Delta
FInputDeviceId FKey float float DeltaTime
int32 uint32 ETouchType::Type const FVector2D float FDateTime DeviceTimestamp
int32 uint32 ETouchType::Type const FVector2D float FDateTime uint32 TouchpadIndex final
EGestureEvent const FVector2D bool bIsDirectionInvertedFromDevice final
int32 const FVector const FVector const FVector const FVector &Acceleration final
int32 uint32 ETouchType::Type const FVector2D float Force
EGestureEvent const FVector2D & GestureDelta
EGestureEvent GestureType
int32 const FVector const FVector const FVector & Gravity
int32 uint32 Handle
FInputDeviceId InputDevice
FInputDeviceId FKey Key
FInputDeviceId FKey float float int32 NumSamples = 1
int32 const FVector const FVector & RotationRate
int32 const FVector & Tilt
int32 uint32 ETouchType::Type const FVector2D & TouchLocation
int32 uint32 ETouchType::Type Type
Static Public Attributes
static UNREALED_API const EViewModeIndex DefaultOrthoViewMode
static UNREALED_API const EViewModeIndex DefaultPerspectiveViewMode
static UNREALED_API const uint32 MaxCameraSpeeds
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions
virtual UNREALED_API void AbortTracking ()
Aborts mouse tracking (stop and cancel)
UNREALED_API void ApplyDeltaToRotateWidget (const FRotator &InRot)
Updates the rotate widget with the passed in delta rotation.
UNREALED_API void ApplyRequiredCursorVisibility (bool bUpdateSoftwareCursorPostion=false)
Apply the required cursor visibility states from the RequiredCursorVisibiltyAndAppearance struct.
UNREALED_API bool CalculateEditorConstrainedViewRect (FSlateRect &OutSafeFrameRect, FViewport *InViewport, const float DPIScale)
Helper function to calculate the safe frame rectangle on the current viewport.
UNREALED_API void DrawAxes (FViewport *Viewport, FCanvas *Canvas, const FRotator *InRotation=nullptr, EAxisList::Type InAxis=EAxisList::XYZ)
Draws viewport axes.
UNREALED_API void DrawScaleUnits (FViewport *Viewport, FCanvas *Canvas, const FSceneView &InView)
Draws viewport scale units.
UNREALED_API void EnableCameraLock (bool bEnable)
Enables or disables camera lock.
virtual bool GetActiveSafeFrame (float &OutAspectRatio) const
Helper used by DrawSafeFrames to get the current safe frame aspect ratio.
UNREALED_API FCachedJoystickState * GetJoystickState (const uint32 InControllerID)
Gets a joystick state cache for the specified controller ID.
virtual UNREALED_API bool Internal_InputAxis (FViewport *Viewport, FInputDeviceId DeviceID, FKey Key, float Delta, float DeltaTime, int32 NumSamples=1, bool bGamepad=false)
virtual UNREALED_API bool Internal_InputKey (const FInputKeyEventArgs &EventArgs)
UNREALED_API void InvalidateViewportWidget ()
Invalidates the viewport widget (if valid) to register its active timer.
virtual void NudgeSelectedObjects (const struct FInputEventState &InputState)
UNREALED_API void OnChangeCameraSpeed (const struct FInputEventState &InputState)
Called when a user changes the camera speed.
UNREALED_API void OnDollyPerspectiveCamera (const struct FInputEventState &InputState)
Called when a user dollys the perspective camera.
UNREALED_API void OnOrthoZoom (const struct FInputEventState &InputState, float Scale=1.0f)
Called when a user zooms the ortho viewport.
virtual void PerspectiveCameraMoved ()
Called when the perspective viewport camera moves.
UNREALED_API void ProcessClickInViewport (const FInputEventState &InputState, FSceneView &View)
Handles clicking in the viewport.
UNREALED_API void ProcessDoubleClickInViewport (const struct FInputEventState &InputState, FSceneView &View)
Handles double clicking in the viewport.
virtual UNREALED_API void RedrawAllViewportsIntoThisScene ()
Invalidates this and other linked viewports (anything viewing the same scene)
UNREALED_API void SetRequiredCursor (const bool bHardwareCursorVisible, const bool bSoftwareCursorVisible)
Sets the required hardware and software cursor.
UNREALED_API bool ShouldUseMoveCanvasMovement () const
UNREALED_API void StartTrackingDueToInput (const struct FInputEventState &InputState, FSceneView &View)
Starts tracking the mouse due to mouse input.
UNREALED_API void StopTracking ()
Stops any mouse tracking.
UNREALED_API void UpdateAndApplyCursorVisibility ()
Updates the visibility of the hardware and software cursors according to the viewport's state.
UNREALED_API void UpdateRequiredCursorVisibility ()
Setup the cursor visibility state we require and store in RequiredCursorVisibiltyAndAppearance struct.
virtual UNREALED_API float UpdateViewportClientWindowDPIScale () const override
FCommonViewportClient interface.
Protected Attributes
bool bAllowCinematicControl
true if this window is allowed to be possessed by cinematic tools for previewing sequences in real-time
bool bCameraLock
Camera Lock or not.
bool bDraggingByHandle
true if the user is dragging by a widget handle.
bool bForceAudioRealtime
If true, force this viewport to use real time audio regardless of other settings.
bool bHasAudioFocus
If true, this viewport gets to set audio parameters (e.g.
bool bHasMouseMovedSinceClick
If true, the canvas has been been moved using bMoveCanvas Mode.
bool bIsCameraMoving
Is the camera moving?
bool bIsCameraMovingOnTick
Is the camera moving at the beginning of the tick?
bool bIsRealtime
if the viewport is currently realtime
bool bIsSimulateInEditorViewport
True if this level viewport can be used to view Simulate in Editor sessions.
bool bIsTracking
true when within a FMouseDeltaTracker::StartTracking/EndTracking block.
bool bShouldCheckHitProxy
true when we are in a state where we can check the hit proxy for hovering.
bool bShowStats
True if we should draw stats over the viewport.
bool bShowWidget
Whether the widget should be drawn.
bool bUseControllingActorViewInfo
bool bUserIsControllingAtmosphericLight0 = false
True is the use is controling the light via a shorcut.
bool bUserIsControllingAtmosphericLight1 = false
bool bUsesDrawHelper
True if this viewport uses a draw helper.
int32 CachedLastMouseX = 0
Represents the last mouse position.
int32 CachedLastMouseY = 0
uint32 CachedMouseX
Represents the last known mouse position.
uint32 CachedMouseY
FEditorCameraController * CameraController
Camera controller object that's used for piloting the camera around.
float CameraSpeedScalar
Camera speed scalar.
int32 CameraSpeedSetting
Camera speed setting.
FCameraControllerUserImpulseData * CameraUserImpulseData
Current cached impulse state.
TOptional< EAspectRatioAxisConstraint > ControllingActorAspectRatioAxisConstraint
TArray< FPostProcessSettings > ControllingActorExtraPostProcessBlends
TArray< float > ControllingActorExtraPostProcessBlendWeights
FMinimalViewInfo ControllingActorViewInfo
FVector CurrentGestureDragDelta
Cumulative camera drag and rotation deltas from trackpad gesture in current Tick.
FRotator CurrentGestureRotDelta
FIntPoint CurrentMousePos
FVector DefaultOrbitLocation = FVector::ZeroVector
FVector DefaultOrbitLookAt = FVector::ZeroVector
FRotator DefaultOrbitRotation = FRotator::ZeroRotator
default set up for toggling back
FVector DefaultOrbitZoom = FVector::ZeroVector
FEditorCommonDrawHelper DrawHelper
Draw helper for rendering common editor functionality like the grid.
TWeakPtr< SEditorViewport > EditorViewportWidget
The editor viewport widget this client is attached to.
TArray< FString > EnabledStats
A list of all the stat names which are enabled for this viewport.
float FlightCameraSpeedScale
Extra camera speed scale for flight camera.
float GestureMoveForwardBackwardImpulse
TMap< int32, FCachedJoystickState * > JoystickStateMap
Cached state of joystick axes and buttons.
uint32 LastMouseX
uint32 LastMouseY
FVector::FReal MinimumFocusRadius = 10.0
When focusing viewport on a box, treat boxes smaller than this size as being this size.
TSharedPtr< FEditorModeTools > ModeTools
Editor mode tools provided to this instance.
FMouseDeltaTracker * MouseDeltaTracker
FVector2D MovingPreviewLightSavedScreenPos
float MovingPreviewLightTimer
TUniqueFunction< void(FEngineShowFlags &)> OverrideShowFlagsFunc
Custom override function that will be called every Draw() until override is disabled.
FPreviewScene * PreviewScene
The scene used for the viewport.
TArray< FRealtimeOverride > RealtimeOverrides
uint64 RealTimeUntilFrameNumber
Overrides bIsRealtime until GFrameCounter is >= this number.
FRequiredCursorState RequiredCursorVisibiltyAndAppearance
Cursor visibility and appearance information.
FStatHitchesData StatHitchesData
Data needed to display per-frame stat tracking when STAT HITCHES is enabled.
FStatUnitData StatUnitData
Data needed to display per-frame stat tracking when STAT UNIT is enabled.
double TimeForForceRedraw
When we have LOD locking, it's slow to force redraw of other viewports, so we delay invalidates to reduce the number of redraws.
FTransform UserControlledAtmosphericLightMatrix
float UserIsControllingAtmosphericLightTimer = 0.0f
TObjectPtr< UTypedElementViewportInteraction > ViewportInteraction
The viewport interaction instance for this viewport.
FWidget * Widget
Static Protected Attributes
static UNREALED_API float const SafePadding
Constant for how much the camera safe zone rectangle is inset when being displayed in the editor.
Private Types
enum class ESceneDPIMode { EditorDefault , EmulateLowDPI , HighDPI }
Private Member Functions
UNREALED_API void ApplyEditorViewModeAdjustments (FEngineShowFlags &InOut) const
InOut might get adjusted depending on viewmode or viewport type.
virtual void BeginCameraMovement (bool bHasMovement)
Handle the camera about to be moved or stopped.
UNREALED_API void ConditionalCheckHoveredHitProxy ()
UNREALED_API void DrawSafeFrameQuad (FCanvas &Canvas, FVector2D V1, FVector2D V2)
UNREALED_API void DrawSafeFrames (FViewport &Viewport, FSceneView &View, FCanvas &Canvas)
Renders the safe frame lines.
virtual void EndCameraMovement ()
virtual FEngineShowFlags * GetEngineShowFlags () override
virtual UNREALED_API float GetMinimumOrthoZoom () const
UNREALED_API void HandleViewportStatCheckEnabled (const TCHAR *InName, bool &bOutCurrentEnabled, bool &bOutOthersEnabled)
Delegate handler to see if a stat is enabled on this viewport.
UNREALED_API void HandleViewportStatDisableAll (const bool bInAnyViewport)
Delegate handler for when all stats are disabled in a viewport.
UNREALED_API void HandleViewportStatDisabled (const TCHAR *InName)
Delegate handler for when stats are disabled in a viewport.
UNREALED_API void HandleViewportStatEnabled (const TCHAR *InName)
Delegate handler for when stats are enabled in a viewport.
UNREALED_API void HandleWindowDPIScaleChanged (TSharedRef< SWindow > InWindow)
Delegate handler for when a window DPI changes and we might need to adjust the scenes resolution.
UNREALED_API bool IsFlightCameraInputModeActive () const
Returns true if perspective flight camera input mode is currently active in this viewport.
UNREALED_API void MoveViewportPerspectiveCamera (const FVector &InDrag, const FRotator &InRot, bool bDollyCamera=false)
Moves a perspective camera.
UNREALED_API int32 SetStatEnabled (const TCHAR *InName, const bool bEnable, const bool bAll=false)
Set a specific stat to either enabled or disabled (returns true if there are any stats enabled)
UNREALED_API bool ShouldPanOrDollyCamera () const
UNREALED_API void UpdateCameraMovement (float DeltaTime)
Updates real-time camera movement.
UNREALED_API void UpdateCameraMovementFromJoystick (const bool bRelativeMovement, FCameraControllerConfig &InConfig)
Applies Joystick axis control to camera movement.
UNREALED_API void UpdateLightingShowFlags (FEngineShowFlags &InOutShowFlags)
Forcibly disables lighting show flags if there are no lights in the scene, or restores lighting show flags if lights are added to the scene.
Private Attributes
bool bInGameViewMode
If true, we are in Game View mode.
bool bInVREditViewMode
If true, we are in VR Edit View mode.
bool bIsCurrentLevelEditingFocus = false
True if this is the current viewport client in editing.
bool bIsPreviewingResolutionFraction = false
Controles resolution fraction for previewing in editor viewport at different screen percentage.
bool bIsTrackingBeingStopped
true during FEditorViewportClient::StopTracking.
bool bShouldInvalidateViewportWidget
If true, the viewport widget should be invalidated on the next tick (needed to ensure thread safety)
TArray< FIntPoint > CapturedMouseMoves
TSharedPtr< ICustomTemporalUpscalerData > CustomTemporalUpscalerData
FSceneView * DragStartView
FSceneViewFamily * DragStartViewFamily
float FarPlane
If > 0, overrides the view's far clipping plane with a plane at the specified distance.
float NearPlane
near plane adjustable for each editor view, if < 0 GNearClippingPlane should be used.
EViewModeIndex OrthoViewModeIndex
EViewModeIndex PerspViewModeIndex
TOptional< float > PreviewResolutionFraction
TArray< FPrioritizedInputChord > PrioritizedInputChords
A list of input key combinations, sorted by priority.
ESceneDPIMode SceneDPIMode
int32 ViewModeParam
FName ViewModeParamName
TMap< int32, FName > ViewModeParamNameMap
Friends
class FMouseDeltaTracker
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Detailed Description
Viewport client for editor viewports.
Contains common functionality for camera movement, rendering debug information, etc.
Definition at line 335 of file EditorViewportClient.h.
Member Enumeration Documentation
ESceneDPIMode
enum class FEditorViewportClient::ESceneDPIMode strong private
Enumerator
EditorDefault
EmulateLowDPI
HighDPI
Definition at line 2114 of file EditorViewportClient.h.
Constructor & Destructor Documentation
FEditorViewportClient() [1/2]
UNREALED_API FEditorViewportClient::FEditorViewportClient (FEditorModeTools * InModeTools, FPreviewScene * InPreviewScene = nullptr, const TWeakPtr< SEditorViewport > & InEditorViewportWidget = nullptr)
Referenced by FEditorViewportClient(), and operator=().
~FEditorViewportClient()
virtual UNREALED_API FEditorViewportClient::~FEditorViewportClient () virtual
FEditorViewportClient() [2/2]
FEditorViewportClient::FEditorViewportClient (const FEditorViewportClient &) delete
Non-copyable.
References FEditorViewportClient().
Member Function Documentation
AbortTracking()
virtual UNREALED_API void FEditorViewportClient::AbortTracking () protected virtual
Aborts mouse tracking (stop and cancel)
Reimplemented in FLevelEditorViewportClient.
AddRealtimeOverride()
UNREALED_API void FEditorViewportClient::AddRealtimeOverride (bool bShouldBeRealtime, FText SystemDisplayName)
Overrides the realtime state of this viewport until RemoveViewportsRealtimeOverride is called.
The state of this override is not preserved between editor sessions.
Parameters
bShouldBeRealtime If true, this viewport will be realtime, if false this viewport will not be realtime
SystemDisplayName This display name of whatever system is overriding realtime. This name is displayed to users in the viewport options menu
AddReferencedObjects()
virtual UNREALED_API void FEditorViewportClient::AddReferencedObjects (FReferenceCollector & Collector) override virtual
FGCObject interface.
Implements FGCObject.
Reimplemented in FDataflowConstructionViewportClient, FDataflowEditorViewportClientBase, and FLevelEditorViewportClient.
AdjustTransformWidgetSize()
UNREALED_API void FEditorViewportClient::AdjustTransformWidgetSize (const int32 SizeDelta)
Adjusts the current transform widget size by the provided delta value.
ApplyDeltaToRotateWidget()
UNREALED_API void FEditorViewportClient::ApplyDeltaToRotateWidget (const FRotator & InRot) protected
Updates the rotate widget with the passed in delta rotation.
ApplyEditorViewModeAdjustments()
UNREALED_API void FEditorViewportClient::ApplyEditorViewModeAdjustments (FEngineShowFlags & InOut) const private
InOut might get adjusted depending on viewmode or viewport type.
ApplyRequiredCursorVisibility()
UNREALED_API void FEditorViewportClient::ApplyRequiredCursorVisibility (bool bUpdateSoftwareCursorPostion = false) protected
Apply the required cursor visibility states from the RequiredCursorVisibiltyAndAppearance struct.
Parameters
View True - Set the position of the software cursor if being made visible. This defaults to FALSE.
BeginCameraMovement()
virtual void FEditorViewportClient::BeginCameraMovement (bool bHasMovement) inline private virtual
Handle the camera about to be moved or stopped.
Reimplemented in FLevelEditorViewportClient.
Definition at line 1799 of file EditorViewportClient.h.
BeginTransform()
virtual UNREALED_API bool FEditorViewportClient::BeginTransform (const FGizmoState & InState) inline virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 620 of file EditorViewportClient.h.
CalcSceneView()
virtual UNREALED_API FSceneView * FEditorViewportClient::CalcSceneView (FSceneViewFamily * ViewFamily, const int32 StereoViewIndex = INDEX_NONE) virtual
Configures the specified FSceneView object with the view and projection matrices for this viewport.
Parameters
View The view to be configured. Must be valid.
StereoPass Which eye we're drawing this view for when in stereo mode
Returns
A pointer to the view within the view family which represents the viewport's primary view.
Reimplemented in FLevelEditorViewportClient.
References INDEX_NONE.
CalculateEditorConstrainedViewRect()
UNREALED_API bool FEditorViewportClient::CalculateEditorConstrainedViewRect (FSlateRect & OutSafeFrameRect, FViewport * InViewport, const float DPIScale) protected
Helper function to calculate the safe frame rectangle on the current viewport.
CalcViewRotationMatrix()
virtual UNREALED_API FMatrix FEditorViewportClient::CalcViewRotationMatrix (const FRotator & InViewRotation) const virtual
Computes a matrix to use for viewport location and rotation.
CalcViewRotationMatrixForControllingActorView()
virtual UNREALED_API FMatrix FEditorViewportClient::CalcViewRotationMatrixForControllingActorView (const FRotator & InViewRotation) const virtual
CanCycleWidgetMode()
virtual bool FEditorViewportClient::CanCycleWidgetMode () const inline virtual
Whether or not the widget mode can be cycled.
Definition at line 684 of file EditorViewportClient.h.
CanDropObjectsAtCoordinates()
virtual FDropQuery FEditorViewportClient::CanDropObjectsAtCoordinates (int32 MouseX, int32 MouseY, const FAssetData & AssetInfo) inline virtual
Checks the viewport to see if the given object can be dropped using the given mouse coordinates local to this viewport.
Parameters
MouseX The position of the mouse's X coordinate
MouseY The position of the mouse's Y coordinate
AssetInfo Asset in question to be dropped
Reimplemented in FLevelEditorViewportClient.
Definition at line 886 of file EditorViewportClient.h.
References MouseY.
CanSetWidgetMode()
virtual UNREALED_API bool FEditorViewportClient::CanSetWidgetMode (UE::Widget::EWidgetMode NewMode) const virtual
Whether or not the new widget mode can be set in this viewport.
CanUseDragTool()
virtual UNREALED_API bool FEditorViewportClient::CanUseDragTool () const virtual
Returns
true if a drag tool can be used
CapturedMouseMove()
virtual UNREALED_API void FEditorViewportClient::CapturedMouseMove (FViewport * InViewport, int32 InMouseX, int32 InMouseY) override virtual
Called when the mouse is moved while a window input capture is in effect.
Parameters
InViewport Viewport that captured the mouse input
InMouseX New mouse cursor X coordinate
InMouseY New mouse cursor Y coordinate
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
CenterViewportAtPoint()
UNREALED_API void FEditorViewportClient::CenterViewportAtPoint (const FVector & NewLookAt, bool bInstant = false)
Translates the viewport so that the given LookAt point is at the center of viewport, while maintaining current Location/LookAt distance.
Parameters
NewLookAt The new NewLookAt point to focus on
bInstant Whether or not to focus the viewport instantly or over time
References FVector.
ChangeActorColorationVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeActorColorationVisualizationMode (FName InName)
Changes the actor coloration visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeBufferVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeBufferVisualizationMode (FName InName)
Changes the buffer visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeGPUSkinCacheVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeGPUSkinCacheVisualizationMode (FName InName)
Changes the GPU Skin Cache visualization mode for this viewport.
Parameters
InName The ID of the required GPU Skin Cache visualization mode
References InName.
ChangeGroomVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeGroomVisualizationMode (FName InName)
Changes the Groom visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeLumenVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeLumenVisualizationMode (FName InName)
Changes the Lumen visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeNaniteVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeNaniteVisualizationMode (FName InName)
Changes the Nanite visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeRayTracingDebugVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeRayTracingDebugVisualizationMode (FName InName)
Changes the ray tracing debug visualization mode for this viewport.
Parameters
InName The ID of the required ray tracing debug visualization mode
References InName.
ChangeSubstrateVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeSubstrateVisualizationMode (FName InName)
Changes the Substrate visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeVirtualShadowMapVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeVirtualShadowMapVisualizationMode (FName InName)
Changes the virtual shadow map visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
ChangeVirtualTextureVisualizationMode()
UNREALED_API void FEditorViewportClient::ChangeVirtualTextureVisualizationMode (FName InName)
Changes the virtual texture visualization mode for this viewport.
Parameters
InName The ID of the required visualization mode
References InName.
CheckHoveredHitProxy()
virtual UNREALED_API void FEditorViewportClient::CheckHoveredHitProxy (HHitProxy * HoveredHitProxy) virtual
Called when the mouse cursor is hovered over a hit proxy.
Parameters
HoveredHitProxy The hit proxy currently hovered over
Reimplemented in FLevelEditorViewportClient.
ClearAudioFocus()
void FEditorViewportClient::ClearAudioFocus () inline
Definition at line 1159 of file EditorViewportClient.h.
References bHasAudioFocus.
ConditionalCheckHoveredHitProxy()
UNREALED_API void FEditorViewportClient::ConditionalCheckHoveredHitProxy () private
ConvertMovementToDragRot()
UNREALED_API void FEditorViewportClient::ConvertMovementToDragRot (const FVector & InDelta, FVector & InDragDelta, FRotator & InRotDelta) const
Converts a generic movement delta into drag/rotation deltas based on the viewport and keys held down.
References FVector.
ConvertMovementToOrbitDragRot()
UNREALED_API void FEditorViewportClient::ConvertMovementToOrbitDragRot (const FVector & InDelta, FVector & InDragDelta, FRotator & InRotDelta) const
References FVector.
DestroyDropPreviewActors()
virtual void FEditorViewportClient::DestroyDropPreviewActors () inline virtual
If dragging an actor for placement, this function destroys the actor.
Reimplemented in FLevelEditorViewportClient.
Definition at line 855 of file EditorViewportClient.h.
DestroyDropPreviewElements()
virtual void FEditorViewportClient::DestroyDropPreviewElements () inline virtual
If dragging items for placement, this function destroys the items.
Reimplemented in FLevelEditorViewportClient.
Definition at line 877 of file EditorViewportClient.h.
DisableOverrideEngineShowFlags()
UNREALED_API void FEditorViewportClient::DisableOverrideEngineShowFlags ()
Disable EngineShowFlags override if enabled.
DoRealtimeAndOverridesMatch()
UNREALED_API bool FEditorViewportClient::DoRealtimeAndOverridesMatch (bool bInValue) const
Returns
true if the underlying realtime mode and the last override (if any) match the given value.
Draw() [1/2]
virtual UNREALED_API void FEditorViewportClient::Draw (const FSceneView * View, FPrimitiveDrawInterface * PDI) override virtual
FViewElementDrawer interface.
Reimplemented from FViewElementDrawer.
Reimplemented in FDataflowConstructionViewportClient, FDataflowEditorViewportClientBase, FDataflowSimulationViewportClient, and FLevelEditorViewportClient.
Draw() [2/2]
virtual UNREALED_API void FEditorViewportClient::Draw (FViewport * Viewport, FCanvas * Canvas) override virtual
Reimplemented from FViewportClient.
References Viewport.
DrawActorScreenSpaceBoundingBox()
UNREALED_API void FEditorViewportClient::DrawActorScreenSpaceBoundingBox (FCanvas * InCanvas, const FSceneView * InView, FViewport * InViewport, AActor * InActor, const FLinearColor & InColor, const bool bInDrawBracket, const FString & InLabelText = TEXT(""))
Draws a screen space bounding box around the specified actor.
Parameters
InCanvas Canvas to draw on
InView View to render
InViewport Viewport we're rendering into
InActor Actor to draw a bounding box for
InColor Color of bounding box
bInDrawBracket True to draw a bracket, otherwise a box will be rendered
bInLabelText Optional label text to draw
DrawAxes()
UNREALED_API void FEditorViewportClient::DrawAxes (FViewport * Viewport, FCanvas * Canvas, const FRotator * InRotation = nullptr, EAxisList::Type InAxis = EAxisList::XYZ) protected
Draws viewport axes.
Parameters
InViewport Viewport we're rendering into
InCanvas Canvas to draw on
InRotation Specifies the rotation to apply to the axes
InAxis Specifies which axes to draw
References Viewport, and EAxisList::XYZ.
DrawBoundingBox()
UNREALED_API void FEditorViewportClient::DrawBoundingBox (FBox & Box, FCanvas * InCanvas, const FSceneView * InView, const FViewport * InViewport, const FLinearColor & InColor, const bool bInDrawBracket, const FString & InLabelText)
References Box.
DrawCanvas()
virtual UNREALED_API void FEditorViewportClient::DrawCanvas (FViewport & InViewport, FSceneView & View, FCanvas & Canvas) virtual
Called to draw onto the viewports 2D canvas.
Parameters
InViewport The viewport being rendered
View The view of the scene to be rendered
Canvas The canvas to draw on
Reimplemented in FDataflowConstructionViewportClient, FDataflowSimulationViewportClient, and FLevelEditorViewportClient.
DrawPreviewLightVisualization()
virtual UNREALED_API void FEditorViewportClient::DrawPreviewLightVisualization (const FSceneView * View, FPrimitiveDrawInterface * PDI) virtual
DrawSafeFrameQuad()
UNREALED_API void FEditorViewportClient::DrawSafeFrameQuad (FCanvas & Canvas, FVector2D V1, FVector2D V2) private
DrawSafeFrames()
UNREALED_API void FEditorViewportClient::DrawSafeFrames (FViewport & Viewport, FSceneView & View, FCanvas & Canvas) private
Renders the safe frame lines.
References Viewport.
DrawScaleUnits()
UNREALED_API void FEditorViewportClient::DrawScaleUnits (FViewport * Viewport, FCanvas * Canvas, const FSceneView & InView) protected
Draws viewport scale units.
Parameters
InViewport Viewport we're rendering into
InCanvas Canvas to draw on
InView Scene view used for rendering
References Viewport.
DropObjectsAtCoordinates()
virtual UNREALED_API bool FEditorViewportClient::DropObjectsAtCoordinates (int32 MouseX, int32 MouseY, const TArray< UObject * > & DroppedObjects, TArray< FTypedElementHandle > & OutNewObjects, const FDropObjectOptions & Options = FDropObjectOptions()) virtual
Attempts to intelligently drop the given objects in the viewport, using the given mouse coordinates local to this viewport.
Parameters
MouseX The position of the mouse's X coordinate
MouseY The position of the mouse's Y coordinate
DroppedObjects The Objects to be placed into the editor via this viewport
OutNewObjects The new actor objects that were created
Options Additional options
Reimplemented in FLevelEditorViewportClient.
References DroppedObjects, and MouseY.
EnableCameraLock()
UNREALED_API void FEditorViewportClient::EnableCameraLock (bool bEnable) protected
Enables or disables camera lock.
EnableOverrideEngineShowFlags()
UNREALED_API void FEditorViewportClient::EnableOverrideEngineShowFlags (TUniqueFunction< void(FEngineShowFlags &)> OverrideFunc)
Enable customization of the EngineShowFlags for rendering.
After calling this function, the provided OverrideFunc will be passed a copy of .EngineShowFlags in Draw() just before rendering setup. Changes made to the ShowFlags will be used for that frame but .EngineShowFlags will not be modified.
Parameters
OverrideFunc custom override function that will be called every frame until override is disabled.
EndCameraMovement()
virtual void FEditorViewportClient::EndCameraMovement () inline private virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 1800 of file EditorViewportClient.h.
EndTransform()
virtual UNREALED_API bool FEditorViewportClient::EndTransform (const FGizmoState & InState) inline virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 621 of file EditorViewportClient.h.
FocusViewportOnBox()
UNREALED_API void FEditorViewportClient::FocusViewportOnBox (const FBox & BoundingBox, bool bInstant = false)
Focuses the viewport to the center of the bounding box ensuring that the entire box is in view.
Parameters
BoundingBox The box to focus
bInstant Whether or not to focus the viewport instantly or over time
References BoundingBox.
GetActiveSafeFrame()
virtual bool FEditorViewportClient::GetActiveSafeFrame (float & OutAspectRatio) const inline protected virtual
Helper used by DrawSafeFrames to get the current safe frame aspect ratio.
Reimplemented in FLevelEditorViewportClient.
Definition at line 1728 of file EditorViewportClient.h.
GetBackgroundColor()
virtual UNREALED_API FLinearColor FEditorViewportClient::GetBackgroundColor () const virtual
Returns
The background color of the viewport
Reimplemented in FLevelEditorViewportClient.
GetCachedMouseX()
virtual uint32 FEditorViewportClient::GetCachedMouseX () const inline virtual
Definition at line 1560 of file EditorViewportClient.h.
References CachedMouseX.
GetCachedMouseY()
virtual uint32 FEditorViewportClient::GetCachedMouseY () const inline virtual
Definition at line 1561 of file EditorViewportClient.h.
References CachedMouseY.
GetCameraController()
FEditorCameraController * FEditorViewportClient::GetCameraController (void) inline
Definition at line 1085 of file EditorViewportClient.h.
References CameraController.
GetCameraSpeed() [1/2]
UNREALED_API float FEditorViewportClient::GetCameraSpeed () const
Get the camera speed for this viewport.
GetCameraSpeed() [2/2]
UNREALED_API float FEditorViewportClient::GetCameraSpeed (int32 SpeedSetting) const
Get the camera speed for this viewport based on the specified speed setting.
GetCameraSpeedScalar()
virtual UNREALED_API float FEditorViewportClient::GetCameraSpeedScalar () const virtual
Get the camera speed scalar for this viewport.
Reimplemented in FLevelEditorViewportClient.
GetCameraSpeedSetting()
virtual UNREALED_API int32 FEditorViewportClient::GetCameraSpeedSetting () const virtual
Get the camera speed setting for this viewport.
Reimplemented in FLevelEditorViewportClient.
GetCurrentActorColorationVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentActorColorationVisualizationModeDisplayName () const
Returns the FText display name associated with current actor coloration visualization mode.
GetCurrentBufferVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentBufferVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentBufferVisualizationMode.
GetCurrentGPUSkinCacheVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentGPUSkinCacheVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentGPUSkinCacheVisualizationMode.
GetCurrentGroomVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentGroomVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentGroomVisualizationMode.
GetCurrentLumenVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentLumenVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentLumenVisualizationMode.
GetCurrentNaniteVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentNaniteVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentNaniteVisualizationMode.
GetCurrentSubstrateVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentSubstrateVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentSubstrateVisualizationMode.
GetCurrentVirtualShadowMapVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentVirtualShadowMapVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentVirtualShadowMapVisualizationMode.
GetCurrentVirtualTextureVisualizationModeDisplayName()
UNREALED_API FText FEditorViewportClient::GetCurrentVirtualTextureVisualizationModeDisplayName () const
Returns the FText display name associated with CurrentVirtualTextureVisualizationMode.
GetCurrentWidgetAxis()
UNREALED_API EAxisList::Type FEditorViewportClient::GetCurrentWidgetAxis () const
GetCursor()
virtual UNREALED_API EMouseCursor::Type FEditorViewportClient::GetCursor (FViewport * Viewport, int32 X, int32 Y) override virtual
Retrieves the cursor that should be displayed by the OS.
Parameters
Viewport the viewport that contains the cursor
X the x position of the cursor
Y the Y position of the cursor
Returns
the cursor that the OS should display
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
References Viewport, X, and Y.
GetCursorWorldLocationFromMousePos()
UNREALED_API FViewportCursorLocation FEditorViewportClient::GetCursorWorldLocationFromMousePos ()
Gets the world space cursor info from the current mouse position.
Returns
An FViewportCursorLocation containing information about the mouse position in world space.
GetCustomTemporalUpscalerData()
TSharedPtr< ICustomTemporalUpscalerData > FEditorViewportClient::GetCustomTemporalUpscalerData () const inline
Definition at line 2094 of file EditorViewportClient.h.
References CustomTemporalUpscalerData.
GetDefaultPrimaryResolutionFractionTarget()
UNREALED_API float FEditorViewportClient::GetDefaultPrimaryResolutionFractionTarget () const
Returns
default resolution fraction for UI based on display resolution and user settings.
GetEditorViewportWidget()
TSharedPtr< SEditorViewport > FEditorViewportClient::GetEditorViewportWidget () const inline
Get the editor viewport widget.
Definition at line 1216 of file EditorViewportClient.h.
References EditorViewportWidget, and GetEditorViewportWidget().
Referenced by GetEditorViewportWidget().
GetEnabledStats()
virtual UNREALED_API const TArray< FString > * FEditorViewportClient::GetEnabledStats () const override virtual
Get a ptr to the enabled stats list.
Reimplemented from FViewportClient.
GetEngineShowFlags()
virtual FEngineShowFlags * FEditorViewportClient::GetEngineShowFlags () inline override private virtual
Reimplemented from FViewportClient.
Definition at line 1773 of file EditorViewportClient.h.
References EngineShowFlags.
GetFarClipPlaneOverride()
UNREALED_API float FEditorViewportClient::GetFarClipPlaneOverride () const
Get the far clipping plane override for this viewport.
GetHitProxyObjectLocation()
UNREALED_API FVector FEditorViewportClient::GetHitProxyObjectLocation (int32 X, int32 Y)
Returns the location of the object at the given viewport X,Y.
References FVector, X, and Y.
GetIsCurrentLevelEditingFocus()
bool FEditorViewportClient::GetIsCurrentLevelEditingFocus () const inline
Definition at line 1580 of file EditorViewportClient.h.
References bIsCurrentLevelEditingFocus.
GetJoystickState()
UNREALED_API FCachedJoystickState * FEditorViewportClient::GetJoystickState (const uint32 InControllerID) protected
Gets a joystick state cache for the specified controller ID.
GetLocalCoordinateSystem()
virtual UNREALED_API FMatrix FEditorViewportClient::GetLocalCoordinateSystem () const virtual
Returns
The local coordinate system for the transform widget. For world coordiante system return the identity matrix
GetLookAtLocation()
const FVector & FEditorViewportClient::GetLookAtLocation () const inline
Returns
the current look at location
Definition at line 554 of file EditorViewportClient.h.
References FVector, FViewportCameraTransform::GetLookAt(), and GetViewTransform().
GetMinimumOrthoZoom()
virtual UNREALED_API float FEditorViewportClient::GetMinimumOrthoZoom () const private virtual
Reimplemented in FDataflowConstructionViewportClient.
GetModeTools()
FEditorModeTools * FEditorViewportClient::GetModeTools () const inline
Editor mode tool manager being used for this viewport client.
Definition at line 1206 of file EditorViewportClient.h.
References ModeTools.
GetMouseDeltaTracker()
FMouseDeltaTracker * FEditorViewportClient::GetMouseDeltaTracker () const inline
Mouse info is usually transformed to gizmo space before FEdMode handles it, this allows raw delta X and Y access.
Definition at line 1558 of file EditorViewportClient.h.
References FMouseDeltaTracker, and MouseDeltaTracker.
GetNearClipPlane()
UNREALED_API float FEditorViewportClient::GetNearClipPlane () const
Get the near clipping plane for this viewport.
GetOrthoUnitsPerPixel()
UNREALED_API float FEditorViewportClient::GetOrthoUnitsPerPixel (const FViewport * Viewport) const
Returns
The number of units per pixel displayed in this viewport
References Viewport.
GetOrthoViewMode()
EViewModeIndex FEditorViewportClient::GetOrthoViewMode () const inline
Returns
The view mode to use when this viewport is not of type LVT_Perspective
Definition at line 1001 of file EditorViewportClient.h.
References OrthoViewModeIndex.
GetOrthoZoom()
float FEditorViewportClient::GetOrthoZoom () const inline
Returns
the current ortho zoom amount
Definition at line 561 of file EditorViewportClient.h.
References FViewportCameraTransform::GetOrthoZoom(), and GetViewTransform().
GetPerspViewMode()
EViewModeIndex FEditorViewportClient::GetPerspViewMode () const inline
Returns
The view mode to use when this viewport is of type LVT_Perspective
Definition at line 993 of file EditorViewportClient.h.
References PerspViewModeIndex.
GetPivotForOrbit()
virtual UNREALED_API bool FEditorViewportClient::GetPivotForOrbit (FVector & OutPivot) const virtual
Get the custom pivot point around which the camera should orbit for this viewport.
Parameters
OutPivot The custom pivot point specified by the viewport
Returns
true if a custom pivot point was specified, false otherwise.
Reimplemented in FLevelEditorViewportClient.
References FVector.
GetPreviewScene()
FPreviewScene * FEditorViewportClient::GetPreviewScene () inline
Retrieves the FPreviewScene used by this instance of FEditorViewportClient.
Returns
The internal FPreviewScene pointer.
Definition at line 353 of file EditorViewportClient.h.
References PreviewScene.
GetPreviewScreenPercentage()
UNREALED_API int32 FEditorViewportClient::GetPreviewScreenPercentage () const
Returns
preview screen percentage for UI.
GetRealtimeOverrideMessage()
UNREALED_API FText FEditorViewportClient::GetRealtimeOverrideMessage () const
Returns
If an override is set this returns the message indicating what set it
GetReferencerName()
virtual UNREALED_API FString FEditorViewportClient::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Reimplemented in FDataflowConstructionViewportClient, and FDataflowSimulationViewportClient.
GetScene()
virtual UNREALED_API FSceneInterface * FEditorViewportClient::GetScene () const virtual
Returns
The scene being rendered in this viewport
GetSceneDepthAtLocation()
UNREALED_API float FEditorViewportClient::GetSceneDepthAtLocation (int32 X, int32 Y)
Returns the scene depth at the given viewport X,Y.
References X, and Y.
GetShowWidget()
UNREALED_API bool FEditorViewportClient::GetShowWidget () const inline
Definition at line 1312 of file EditorViewportClient.h.
References bShowWidget.
GetStatHitchesData()
virtual UNREALED_API FStatHitchesData * FEditorViewportClient::GetStatHitchesData () const override virtual
Get a ptr to the stat unit data for this viewport.
Reimplemented from FViewportClient.
GetStatUnitData()
virtual UNREALED_API FStatUnitData * FEditorViewportClient::GetStatUnitData () const override virtual
Get a ptr to the stat unit data for this viewport.
Reimplemented from FViewportClient.
GetViewLocation()
const FVector & FEditorViewportClient::GetViewLocation () const inline
Returns
the current viewport camera location
Definition at line 540 of file EditorViewportClient.h.
References FVector, FViewportCameraTransform::GetLocation(), and GetViewTransform().
Referenced by FBookMarkTypeActions::InitFromViewport().
GetViewMode()
UNREALED_API EViewModeIndex FEditorViewportClient::GetViewMode () const
Returns
The current view mode in this viewport, for the current viewport type
Referenced by IsViewModeEnabled().
GetViewModeParamNameMap()
TMap< int32, FName > & FEditorViewportClient::GetViewModeParamNameMap () inline
Returns the map allowing to convert from the viewmode param to a name.
Definition at line 1308 of file EditorViewportClient.h.
References ViewModeParamNameMap.
GetViewportDimensions()
UNREALED_API void FEditorViewportClient::GetViewportDimensions (FIntPoint & OutOrigin, FIntPoint & OutSize)
Gets the dimensions of the viewport.
GetViewportType()
virtual UNREALED_API ELevelViewportType FEditorViewportClient::GetViewportType () const virtual
Returns the effective viewport type (taking into account any actor locking or camera possession)
Reimplemented in FLevelEditorViewportClient.
GetViewRotation()
const FRotator & FEditorViewportClient::GetViewRotation () const inline
Returns
the current viewport camera rotation
Definition at line 547 of file EditorViewportClient.h.
References FViewportCameraTransform::GetRotation(), and GetViewTransform().
Referenced by FBookMarkTypeActions::InitFromViewport(), and RemoveCameraRoll().
GetViewStatusForScreenPercentage()
UNREALED_API EViewStatusForScreenPercentage FEditorViewportClient::GetViewStatusForScreenPercentage () const
Returns
the view status to select the corresponding default screen percentage behavior
GetViewTransform() [1/2]
FViewportCameraTransform & FEditorViewportClient::GetViewTransform () inline
Gets ViewportCameraTransform object for the current viewport type.
Definition at line 481 of file EditorViewportClient.h.
References GetViewTransform(), IsPerspective(), ViewTransformOrthographic, and ViewTransformPerspective.
Referenced by GetLookAtLocation(), GetOrthoZoom(), GetViewLocation(), GetViewRotation(), GetViewTransform(), SetLookAtLocation(), SetOrthoZoom(), SetViewLocation(), and SetViewRotation().
GetViewTransform() [2/2]
const FViewportCameraTransform & FEditorViewportClient::GetViewTransform () const inline
Definition at line 486 of file EditorViewportClient.h.
References IsPerspective(), ViewTransformOrthographic, and ViewTransformPerspective.
GetWidgetCoordSystem()
virtual UNREALED_API FMatrix FEditorViewportClient::GetWidgetCoordSystem () const virtual
Returns
The current coordinate system for drawing and input of the transform widget.
For world coordiante system return the identity matrix
Reimplemented in FLevelEditorViewportClient.
GetWidgetCoordSystemSpace()
virtual UNREALED_API ECoordSystem FEditorViewportClient::GetWidgetCoordSystemSpace () const virtual
Returns
The coordinate system space (world or local) to display the widget in
GetWidgetLocation()
virtual UNREALED_API FVector FEditorViewportClient::GetWidgetLocation () const virtual
Returns
The world space location of the transform widget
Reimplemented in FLevelEditorViewportClient.
References FVector.
GetWidgetMode()
virtual UNREALED_API UE::Widget::EWidgetMode FEditorViewportClient::GetWidgetMode () const virtual
Returns
The current display mode for transform widget
Reimplemented in FLevelEditorViewportClient.
GetWorld()
virtual UNREALED_API UWorld * FEditorViewportClient::GetWorld () const override virtual
Use the viewports Scene to get a world.
Will use Global world instance of the scene or its world is invalid.
Returns
A valid pointer to the viewports world scene.
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
Referenced by FBookMarkTypeActions::InitFromViewport().
HandleIsShowFlagEnabled()
virtual UNREALED_API bool FEditorViewportClient::HandleIsShowFlagEnabled (FEngineShowFlags::EShowFlag EngineShowFlagIndex) const virtual
Delegate handler fired to determine the state of a show flag.
HandleToggleShowFlag()
virtual UNREALED_API void FEditorViewportClient::HandleToggleShowFlag (FEngineShowFlags::EShowFlag EngineShowFlagIndex) virtual
Delegate handler fired when a show flag is toggled.
HandleViewportStatCheckEnabled()
UNREALED_API void FEditorViewportClient::HandleViewportStatCheckEnabled (const TCHAR * InName, bool & bOutCurrentEnabled, bool & bOutOthersEnabled) private
Delegate handler to see if a stat is enabled on this viewport.
References InName.
HandleViewportStatDisableAll()
UNREALED_API void FEditorViewportClient::HandleViewportStatDisableAll (const bool bInAnyViewport) private
Delegate handler for when all stats are disabled in a viewport.
HandleViewportStatDisabled()
UNREALED_API void FEditorViewportClient::HandleViewportStatDisabled (const TCHAR * InName) private
Delegate handler for when stats are disabled in a viewport.
References InName.
HandleViewportStatEnabled()
UNREALED_API void FEditorViewportClient::HandleViewportStatEnabled (const TCHAR * InName) private
Delegate handler for when stats are enabled in a viewport.
References InName.
HandleWindowDPIScaleChanged()
UNREALED_API void FEditorViewportClient::HandleWindowDPIScaleChanged (TSharedRef< SWindow > InWindow) private
Delegate handler for when a window DPI changes and we might need to adjust the scenes resolution.
HasDropPreviewActors()
virtual bool FEditorViewportClient::HasDropPreviewActors () const inline virtual
Returns true if a placement dragging actor exists.
Reimplemented in FLevelEditorViewportClient.
Definition at line 836 of file EditorViewportClient.h.
HasDropPreviewElements()
virtual bool FEditorViewportClient::HasDropPreviewElements () const inline virtual
Returns true if a placement drag preview elements exists.
Reimplemented in FLevelEditorViewportClient.
Definition at line 858 of file EditorViewportClient.h.
HasRealtimeOverride()
UNREALED_API bool FEditorViewportClient::HasRealtimeOverride (FText SystemDisplayName) const
Returns whether there's a realtime override registered with the given system name.
InputAxis()
virtual UNREALED_API bool FEditorViewportClient::InputAxis (const FInputKeyEventArgs & Args) override virtual
Check an axis movement received by the viewport.
If this viewport client uses this input and wants to consume it (stop it from being passed along to further viewports) then it should return true.
Parameters
Args The input event arguments for this axis movement.
Returns
True to consume the axis movement, false to pass it on.
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
InputAxisForOrbit()
UNREALED_API void FEditorViewportClient::InputAxisForOrbit (FViewport * Viewport, const FVector & DragDelta, FVector & Drag, FRotator & Rot)
References FVector, and Viewport.
InputGesture()
virtual UNREALED_API bool FEditorViewportClient::InputGesture (FViewport * Viewport, const FInputDeviceId DeviceId, EGestureEvent GestureType, const FVector2D & GestureDelta, bool bIsDirectionInvertedFromDevice, const uint64 Timestamp) override virtual
Check a gesture event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
Viewport - The viewport which the event is from.
DeviceId - The input device id from which this gesture came from
GestureType - The type of gesture being input
GestureDelta - Delta values of this gesture from the previous instance of it
Timestamp - The timestamp of when this input event was originally polled in the form of CPU cycles.
Returns
True to consume the gesture event, false to pass it on.
Reimplemented from FViewportClient.
References FViewportClient::GestureDelta, FViewportClient::GestureType, and Viewport.
InputKey()
virtual UNREALED_API bool FEditorViewportClient::InputKey (const FInputKeyEventArgs & EventArgs) override virtual
Check a key event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
EventArgs - The Input event args.
Returns
True to consume the key event, false to pass it on.
Reimplemented from FViewportClient.
Reimplemented in FDataflowConstructionViewportClient, and FLevelEditorViewportClient.
InputTakeScreenshot()
UNREALED_API bool FEditorViewportClient::InputTakeScreenshot (FViewport * Viewport, FKey Key, EInputEvent Event)
Implements screenshot capture for editor viewports.
Should be called by derived class' InputKey.
References Event, FViewportClient::Key, and Viewport.
InputWidgetDelta()
virtual UNREALED_API bool FEditorViewportClient::InputWidgetDelta (FViewport * InViewport, EAxisList::Type CurrentAxis, FVector & Drag, FRotator & Rot, FVector & Scale) virtual
Called to give the viewport client a chance to handle widgets being moved.
Parameters
InViewport The viewport being rendered
CurrentAxis The current widget axis being moved
Drag The amount the widget was translated (the value depends on the coordinate system of the widget. See GetWidgetCoordSystem)
Rot The amount the widget was rotated (the value depends on the coordinate system of the widget. See GetWidgetCoordSystem)
Scale The amount the widget was scaled (the value depends on the coordinate system of the widget. See GetWidgetCoordSystem)
Reimplemented in FLevelEditorViewportClient.
References FVector, and Scale.
Internal_InputAxis()
virtual UNREALED_API bool FEditorViewportClient::Internal_InputAxis (FViewport * Viewport, FInputDeviceId DeviceID, FKey Key, float Delta, float DeltaTime, int32 NumSamples = 1, bool bGamepad = false) protected virtual
References FViewportClient::bGamepad, FViewportClient::Delta, FViewportClient::DeltaTime, DeviceID, FViewportClient::Key, FViewportClient::NumSamples, and Viewport.
Internal_InputKey()
virtual UNREALED_API bool FEditorViewportClient::Internal_InputKey (const FInputKeyEventArgs & EventArgs) protected virtual
Invalidate()
UNREALED_API void FEditorViewportClient::Invalidate (bool bInvalidateChildViews = true, bool bInvalidateHitProxies = true)
Invalidates this viewport and optionally child views.
Parameters
bInvalidateChildViews [opt] If true (the default), invalidate views that see this viewport as their parent.
bInvalidateHitProxies [opt] If true (the default), invalidates cached hit proxies too.
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient(), SetShowAspectRatioBarDisplay(), and SetShowSafeFrameBoxDisplay().
InvalidateViewportWidget()
UNREALED_API void FEditorViewportClient::InvalidateViewportWidget () protected
Invalidates the viewport widget (if valid) to register its active timer.
IsActiveViewportType()
UNREALED_API bool FEditorViewportClient::IsActiveViewportType (ELevelViewportType InViewportType) const
Returns
If InViewportType is the active viewport type
IsActiveViewportTypeInRotation()
UNREALED_API bool FEditorViewportClient::IsActiveViewportTypeInRotation () const
Returns
If the viewport option in the array is the active viewport type
IsActorColorationVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsActorColorationVisualizationModeSelected (FName InName) const
Checks if an actor coloration visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied actor coloration visualization mode is checked
References InName.
IsAltPressed()
UNREALED_API bool FEditorViewportClient::IsAltPressed () const
IsAspectRatioConstrained()
virtual UNREALED_API bool FEditorViewportClient::IsAspectRatioConstrained () const virtual
Is the aspect ratio currently constrained?
IsBufferVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsBufferVisualizationModeSelected (FName InName) const
Checks if a buffer visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied buffer visualization mode is checked
References InName.
IsCameraLocked()
UNREALED_API bool FEditorViewportClient::IsCameraLocked () const
Callback for checking the camera lock flag.
References IsCameraLocked().
Referenced by IsCameraLocked().
IsCmdPressed()
UNREALED_API bool FEditorViewportClient::IsCmdPressed () const
IsCommandChordPressed()
UNREALED_API bool FEditorViewportClient::IsCommandChordPressed (const TSharedPtr< FUICommandInfo > InCommand, FKey InOptionalKey = FKey()) const
Utility function to return whether the command accepts the key states.
Parameters
InCommand The command being checked
InOptionalKey (Optional) input key being tested against. If not specified, the current viewport's key state's key will be used
Returns
True if one of the command's chords accepts the input :
IsCtrlPressed()
UNREALED_API bool FEditorViewportClient::IsCtrlPressed () const
IsEngineShowFlagsOverrideEnabled()
bool FEditorViewportClient::IsEngineShowFlagsOverrideEnabled () const inline
Returns
true if Override EngineShowFlags are currently enabled
Definition at line 1578 of file EditorViewportClient.h.
References OverrideShowFlagsFunc.
IsFlightCameraActive()
UNREALED_API bool FEditorViewportClient::IsFlightCameraActive () const
Returns whether or not the flight camera is active.
Returns
true if the flight camera is active
IsFlightCameraInputModeActive()
UNREALED_API bool FEditorViewportClient::IsFlightCameraInputModeActive () const private
Returns true if perspective flight camera input mode is currently active in this viewport.
IsForcedRealtimeAudio()
bool FEditorViewportClient::IsForcedRealtimeAudio () const inline
Definition at line 1168 of file EditorViewportClient.h.
References bForceAudioRealtime.
IsGPUSkinCacheVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsGPUSkinCacheVisualizationModeSelected (FName InName) const
Checks if a GPU Skin Cache visualization mode is selected.
Parameters
InName The ID of the required GPU Skin Cache visualization mode
Returns
true if the supplied GPU Skin Cache visualization mode is checked
References InName.
IsGroomVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsGroomVisualizationModeSelected (FName InName) const
Checks if a Groom visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied Groom visualization mode is checked
References InName.
IsInGameView()
virtual bool FEditorViewportClient::IsInGameView () const inline override virtual
Returns true if this viewport is excluding non-game elements from its display.
Reimplemented from FViewportClient.
Definition at line 1260 of file EditorViewportClient.h.
References bInGameViewMode.
IsInImmersiveViewport()
UNREALED_API bool FEditorViewportClient::IsInImmersiveViewport () const
Returns
True if the window is in an immersive viewport
IsLevelEditorClient()
virtual bool FEditorViewportClient::IsLevelEditorClient () const inline virtual
If true, this is a level editor viewport.
Reimplemented in FLevelEditorViewportClient.
Definition at line 802 of file EditorViewportClient.h.
IsLowDPIPreview()
UNREALED_API bool FEditorViewportClient::IsLowDPIPreview () const
Returns
whether previewing for low DPI.
IsLumenVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsLumenVisualizationModeSelected (FName InName) const
Checks if a Lumen visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied Lumen visualization mode is checked
References InName.
IsMovingCamera()
UNREALED_API bool FEditorViewportClient::IsMovingCamera () const
IsNaniteVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsNaniteVisualizationModeSelected (FName InName) const
Checks if a Nanite visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied Nanite visualization mode is checked
References InName.
IsOrtho()
virtual UNREALED_API bool FEditorViewportClient::IsOrtho () const override virtual
Returns true if this viewport is orthogonal.
If hit proxies are ever used in-game, this will need to be overridden correctly in GameViewportClient.
Reimplemented from FViewportClient.
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient(), and FBookMarkTypeActions::InitFromViewport().
IsPerspective()
UNREALED_API bool FEditorViewportClient::IsPerspective () const
Returns true if this viewport is perspective.
Referenced by GetViewTransform(), and GetViewTransform().
IsPreviewingScreenPercentage()
UNREALED_API bool FEditorViewportClient::IsPreviewingScreenPercentage () const
Returns
whether preview screen percentage for UI.
IsPrioritizedInputChordPressed()
UNREALED_API bool FEditorViewportClient::IsPrioritizedInputChordPressed (const FName InInputCordName) const
IsRayTracingDebugVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsRayTracingDebugVisualizationModeSelected (FName InName) const
Checks if a ray tracing debug visualization mode is selected.
Parameters
InName The ID of the required ray tracing debug visualization mode
Returns
true if the supplied ray tracing debug visualization mode is checked
References InName.
IsRealtime()
bool FEditorViewportClient::IsRealtime () const inline
Returns
True if viewport is in realtime mode, false otherwise.
Definition at line 404 of file EditorViewportClient.h.
References bIsRealtime, GFrameCounter, RealtimeOverrides, and RealTimeUntilFrameNumber.
IsRealtimeOverrideSet()
bool FEditorViewportClient::IsRealtimeOverrideSet () const inline
Returns
true if there are any temp realtime overrides set
Definition at line 428 of file EditorViewportClient.h.
References RealtimeOverrides.
IsSetShowBoundsChecked()
UNREALED_API bool FEditorViewportClient::IsSetShowBoundsChecked () const
Callback for checking the bounds show flag.
References IsSetShowBoundsChecked().
Referenced by IsSetShowBoundsChecked().
IsSetShowCollisionChecked()
UNREALED_API bool FEditorViewportClient::IsSetShowCollisionChecked () const
Callback for checking the collision geometry show flag.
References IsSetShowCollisionChecked().
Referenced by IsSetShowCollisionChecked().
IsSetShowGridChecked()
UNREALED_API bool FEditorViewportClient::IsSetShowGridChecked () const
Callback for checking the grid show flag.
References IsSetShowGridChecked().
Referenced by IsSetShowGridChecked().
IsShiftPressed()
UNREALED_API bool FEditorViewportClient::IsShiftPressed () const
IsShowingAspectRatioBarDisplay()
bool FEditorViewportClient::IsShowingAspectRatioBarDisplay () const inline
Definition at line 1277 of file EditorViewportClient.h.
References EngineShowFlags.
IsShowingSafeFrameBoxDisplay()
bool FEditorViewportClient::IsShowingSafeFrameBoxDisplay () const inline
Definition at line 1282 of file EditorViewportClient.h.
References EngineShowFlags.
IsSimulateInEditorViewport()
bool FEditorViewportClient::IsSimulateInEditorViewport () const inline
Definition at line 945 of file EditorViewportClient.h.
References bIsSimulateInEditorViewport.
IsStatEnabled()
virtual UNREALED_API bool FEditorViewportClient::IsStatEnabled (const FString & InName) const override virtual
Check whether a specific stat is enabled for this viewport.
Reimplemented from FViewportClient.
References InName.
IsSubstrateVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsSubstrateVisualizationModeSelected (FName InName) const
Checks if a Substrate visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied Substrate visualization mode is checked
References InName.
IsTracking()
bool FEditorViewportClient::IsTracking () const inline
Returns
true if a mouse button is down and it's movement being tracked for operations inside the viewport
Definition at line 1177 of file EditorViewportClient.h.
References bIsTracking.
IsUsingAbsoluteTranslation()
UNREALED_API bool FEditorViewportClient::IsUsingAbsoluteTranslation (bool bAlsoCheckAbsoluteRotation = false) const
Determines whether this viewport is currently allowed to use Absolute Movement.
IsViewModeEnabled()
bool FEditorViewportClient::IsViewModeEnabled (EViewModeIndex InViewModeIndex) const inline
Returns
True if InViewModeIndex is the current view mode index
Definition at line 1007 of file EditorViewportClient.h.
References GetViewMode().
IsViewModeParam()
UNREALED_API bool FEditorViewportClient::IsViewModeParam (int32 InViewModeParam) const
Returns
True if InViewModeIndex is the current view mode param
IsVirtualShadowMapVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsVirtualShadowMapVisualizationModeSelected (FName InName) const
Checks if a virtual shadow map visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied virtual shadow map visualization mode is checked
References InName.
IsVirtualTextureVisualizationModeSelected()
UNREALED_API bool FEditorViewportClient::IsVirtualTextureVisualizationModeSelected (FName InName) const
Checks if a virtual texture visualization mode is selected.
Parameters
InName The ID of the required visualization mode
Returns
true if the supplied virtual texture visualization mode is checked
References InName.
IsVisualizeCalibrationMaterialEnabled()
UNREALED_API bool FEditorViewportClient::IsVisualizeCalibrationMaterialEnabled () const
Returns whether visualize debug material is enabled.
LostFocus()
virtual UNREALED_API void FEditorViewportClient::LostFocus (FViewport * Viewport) override virtual
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
References Viewport.
MakeDragTool()
virtual UNREALED_API TSharedPtr< FDragTool > FEditorViewportClient::MakeDragTool (EDragTool::Type DragToolType) virtual
Called to make a drag tool when the user starts dragging in the viewport.
Parameters
DragToolType The type of drag tool to make
Returns
The new drag tool
Reimplemented in FLevelEditorViewportClient.
MarkMouseMovedSinceClick()
UNREALED_API void FEditorViewportClient::MarkMouseMovedSinceClick ()
MouseEnter()
virtual UNREALED_API void FEditorViewportClient::MouseEnter (FViewport * Viewport, int32 x, int32 y) override virtual
Reimplemented from FViewportClient.
References Viewport.
MouseLeave()
virtual UNREALED_API void FEditorViewportClient::MouseLeave (FViewport * Viewport) override virtual
Reimplemented from FViewportClient.
References Viewport.
MouseMove()
virtual UNREALED_API void FEditorViewportClient::MouseMove (FViewport * Viewport, int32 x, int32 y) override virtual
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
References Viewport.
MoveViewportCamera()
UNREALED_API void FEditorViewportClient::MoveViewportCamera (const FVector & InDrag, const FRotator & InRot, bool bDollyCamera = false)
Moves the viewport Scamera according to the specified drag and rotation.
References FVector.
MoveViewportPerspectiveCamera()
UNREALED_API void FEditorViewportClient::MoveViewportPerspectiveCamera (const FVector & InDrag, const FRotator & InRot, bool bDollyCamera = false) private
Moves a perspective camera.
References FVector.
NudgeSelectedObjects()
virtual void FEditorViewportClient::NudgeSelectedObjects (const struct FInputEventState & InputState) inline protected virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 1733 of file EditorViewportClient.h.
OnChangeCameraSpeed()
UNREALED_API void FEditorViewportClient::OnChangeCameraSpeed (const struct FInputEventState & InputState) protected
Called when a user changes the camera speed.
Parameters
InputState The current state of mouse and keyboard buttons
OnDollyPerspectiveCamera()
UNREALED_API void FEditorViewportClient::OnDollyPerspectiveCamera (const struct FInputEventState & InputState) protected
Called when a user dollys the perspective camera.
Parameters
InputState The current state of mouse and keyboard buttons
OnEditorModeIDChanged()
UNREALED_API void FEditorViewportClient::OnEditorModeIDChanged (const FEditorModeID & EditorModeID, bool bIsEntering)
Called when an editor mode has been (de)activated.
OnOrthoZoom()
UNREALED_API void FEditorViewportClient::OnOrthoZoom (const struct FInputEventState & InputState, float Scale = 1.0f) protected
Called when a user zooms the ortho viewport.
Parameters
InputState The current state of mouse and keyboard buttons
Scale Allows modifying the default amount of zoom
References Scale.
OpenScreenshot()
UNREALED_API void FEditorViewportClient::OpenScreenshot (FString SourceFilePath)
Opens the screenshot in the uses default bitmap viewer (determined by OS)
operator=()
FEditorViewportClient & FEditorViewportClient::operator= (const FEditorViewportClient &) delete
References FEditorViewportClient().
OverrideFarClipPlane()
UNREALED_API void FEditorViewportClient::OverrideFarClipPlane (const float InFarPlane)
Override the far clipping plane.
Set to a negative value to disable the override.
OverrideNearClipPlane()
UNREALED_API void FEditorViewportClient::OverrideNearClipPlane (float InNearPlane)
Override the near clipping plane.
Set to a negative value to disable the override.
OverridePostProcessSettings()
virtual void FEditorViewportClient::OverridePostProcessSettings (FSceneView & View) inline virtual
Called to override any post process settings for the view.
Parameters
View The view to override post process settings on
Reimplemented in FLevelEditorViewportClient.
Definition at line 775 of file EditorViewportClient.h.
PeformDefaultCameraMovement()
UNREALED_API void FEditorViewportClient::PeformDefaultCameraMovement (FVector & Drag, FRotator & Rot, FVector & Scale)
Perform default camera movement that would normally happen* This can be used by systems to override how the camera is triggered.
References FVector, and Scale.
PerspectiveCameraMoved()
virtual void FEditorViewportClient::PerspectiveCameraMoved () inline protected virtual
Called when the perspective viewport camera moves.
Reimplemented in FLevelEditorViewportClient.
Definition at line 1592 of file EditorViewportClient.h.
PopRealtimeOverride()
UNREALED_API bool FEditorViewportClient::PopRealtimeOverride ()
Removes the last added realtime override.
WARNING: it's recommended to use RemoveRealtimeOverride to prevent removing an override that belongs to another systems than yours.
Returns
Whether there was any realtime override to be popped.
ProcessAccumulatedPointerInput()
virtual UNREALED_API void FEditorViewportClient::ProcessAccumulatedPointerInput (FViewport * InViewport) override virtual
Called from slate when input is finished for this frame, and we should process any queued mouse moves.
Reimplemented from FViewportClient.
ProcessClick()
virtual UNREALED_API void FEditorViewportClient::ProcessClick (FSceneView & View, HHitProxy * HitProxy, FKey Key, EInputEvent Event, uint32 HitX, uint32 HitY) virtual
Called when the user clicks in the viewport.
Parameters
View The view of the scene in the viewport
HitProxy Any hit proxy that was clicked
Key The key that caused the click event
Event State of the pressed key
HitX The X location of the mouse
HitY The Y location of the mouse
Reimplemented in FDataflowConstructionViewportClient, FDataflowSimulationViewportClient, and FLevelEditorViewportClient.
References Event, and FViewportClient::Key.
ProcessClickInViewport()
UNREALED_API void FEditorViewportClient::ProcessClickInViewport (const FInputEventState & InputState, FSceneView & View) protected
Handles clicking in the viewport.
Parameters
InputState The mouse and keyboard input state at the time the click happened
View The view of the scene in this viewport
ProcessDoubleClickInViewport()
UNREALED_API void FEditorViewportClient::ProcessDoubleClickInViewport (const struct FInputEventState & InputState, FSceneView & View) protected
Handles double clicking in the viewport.
Parameters
InputState The mouse and keyboard input state at the time the click happened
View The view of the scene in this viewport
ProcessScreenShots()
virtual UNREALED_API bool FEditorViewportClient::ProcessScreenShots (FViewport * Viewport) override virtual
FViewportClient interface.
Reimplemented from FViewportClient.
References Viewport.
ReceivedFocus()
virtual UNREALED_API void FEditorViewportClient::ReceivedFocus (FViewport * Viewport) override virtual
Reimplemented from FViewportClient.
Reimplemented in FLevelEditorViewportClient.
References Viewport.
RedrawAllViewportsIntoThisScene()
virtual UNREALED_API void FEditorViewportClient::RedrawAllViewportsIntoThisScene () protected virtual
Invalidates this and other linked viewports (anything viewing the same scene)
Reimplemented in FLevelEditorViewportClient.
RedrawRequested()
virtual UNREALED_API void FEditorViewportClient::RedrawRequested (FViewport * Viewport) override virtual
Reimplemented from FViewportClient.
References Viewport.
RegisterPrioritizedInputChord()
UNREALED_API void FEditorViewportClient::RegisterPrioritizedInputChord (const FPrioritizedInputChord & InInputCord)
RemoveCameraRoll()
void FEditorViewportClient::RemoveCameraRoll () inline
Definition at line 573 of file EditorViewportClient.h.
References GetViewRotation(), Rotation, and SetViewRotation().
RemoveRealtimeOverride()
UNREALED_API bool FEditorViewportClient::RemoveRealtimeOverride (FText SystemDisplayName, bool bCheckMissingOverride = true)
Removes the most recent realtime override registered with the given system name.
Parameters
SystemDisplayName The display name of the override to be removed.
bCheckMissingOverride Whether to assert if no matching realtime override was found. Should be false if users can operate within the viewport between enable/disable calls as they can remove overrides.
Returns
Whether any matching realtime override was found.
RenderDragTool()
UNREALED_API void FEditorViewportClient::RenderDragTool (const FSceneView * View, FCanvas * Canvas)
Render the drag tool in the viewport.
RequestInvalidateHitProxy()
virtual UNREALED_API void FEditorViewportClient::RequestInvalidateHitProxy (FViewport * Viewport) override virtual
Reimplemented from FViewportClient.
References Viewport.
RequestRealTimeFrames()
virtual void FEditorViewportClient::RequestRealTimeFrames (uint64 NumRealTimeFrames = 1) inline virtual
Get the number of real-time frames to draw (overrides bRealtime)
Note
When non-zero, the viewport will render RealTimeFrameCount frames in real-time mode, then revert back to bIsRealtime this can be used to ensure that not only the viewport renders a frame, but also that the world ticks
Parameters
NumExtraFrames The number of extra real time frames to draw
Definition at line 415 of file EditorViewportClient.h.
References GFrameCounter, FMath::Max, and RealTimeUntilFrameNumber.
RotateViewportType()
virtual UNREALED_API void FEditorViewportClient::RotateViewportType () virtual
Rotate through viewport view options.
Reimplemented in FLevelEditorViewportClient.
SaveRealtimeStateToConfig()
UNREALED_API void FEditorViewportClient::SaveRealtimeStateToConfig (bool & ConfigVar) const
Saves the realtime state to a config location.
Does not save any temp overrides
SetAudioFocus()
void FEditorViewportClient::SetAudioFocus () inline
Definition at line 1161 of file EditorViewportClient.h.
References bHasAudioFocus.
SetCameraLock()
virtual UNREALED_API void FEditorViewportClient::SetCameraLock () virtual
Callback for toggling the camera lock flag.
References SetCameraLock().
Referenced by SetCameraLock().
SetCameraSetup()
UNREALED_API void FEditorViewportClient::SetCameraSetup (const FVector & LocationForOrbiting, const FRotator & InOrbitRotation, const FVector & InOrbitZoom, const FVector & InOrbitLookAt, const FVector & InViewLocation, const FRotator & InViewRotation)
References FVector, and SetCameraSetup().
Referenced by SetCameraSetup().
SetCameraSpeedScalar()
virtual UNREALED_API void FEditorViewportClient::SetCameraSpeedScalar (float SpeedScalar) virtual
Set the camera speed scalar for this viewport.
Reimplemented in FLevelEditorViewportClient.
SetCameraSpeedSetting()
virtual UNREALED_API void FEditorViewportClient::SetCameraSpeedSetting (int32 SpeedSetting) virtual
Set the speed setting for the camera in this viewport.
Reimplemented in FLevelEditorViewportClient.
SetCurrentWidgetAxis()
virtual UNREALED_API void FEditorViewportClient::SetCurrentWidgetAxis (EAxisList::Type InAxis) virtual
Sets the current axis being manipulated by the transform widget.
SetCustomTemporalUpscalerData()
void FEditorViewportClient::SetCustomTemporalUpscalerData (TSharedPtr< ICustomTemporalUpscalerData > InCustomTemporalUpscalerData) inline
Definition at line 2099 of file EditorViewportClient.h.
References CustomTemporalUpscalerData.
SetEnabledStats()
virtual UNREALED_API void FEditorViewportClient::SetEnabledStats (const TArray< FString > & InEnabledStats) override virtual
Sets all the stats that should be enabled for the viewport.
Reimplemented from FViewportClient.
SetForcedAudioRealtime()
void FEditorViewportClient::SetForcedAudioRealtime (bool bShouldForceAudioRealtime) inline
true to force realtime audio to be true, false to stop forcing it
Definition at line 1171 of file EditorViewportClient.h.
References bForceAudioRealtime.
SetGameView()
UNREALED_API void FEditorViewportClient::SetGameView (bool bGameViewEnable)
SetInitialViewTransform()
UNREALED_API void FEditorViewportClient::SetInitialViewTransform (ELevelViewportType ViewportType, const FVector & ViewLocation, const FRotator & ViewRotation, float InOrthoZoom)
References FVector, and ViewportType.
SetIsCurrentLevelEditingFocus()
void FEditorViewportClient::SetIsCurrentLevelEditingFocus (bool bInIsCurrentLevelEditingFocus) inline
Definition at line 1581 of file EditorViewportClient.h.
References bIsCurrentLevelEditingFocus.
SetLookAtLocation()
void FEditorViewportClient::SetLookAtLocation (const FVector & LookAt, bool bRecalculateView = false) inline
Sets the look at location of the viewports camera for orbit *.
Parameters
LookAt The new look at location
bRecalulateView If true, will recalculate view location and rotation to look at the new point immediatley
Definition at line 511 of file EditorViewportClient.h.
References FViewportCameraTransform::ComputeOrbitMatrix(), FVector, UE::Math::TMatrix< T >::GetOrigin(), GetViewTransform(), UE::Math::TMatrix< T >::InverseFast(), UE::Math::TMatrix< T >::Rotator(), FViewportCameraTransform::SetLocation(), FViewportCameraTransform::SetLookAt(), and FViewportCameraTransform::SetRotation().
SetLowDPIPreview()
UNREALED_API void FEditorViewportClient::SetLowDPIPreview (bool LowDPIPreview)
Set whether previewing for low DPI.
SetOrthoZoom()
void FEditorViewportClient::SetOrthoZoom (float InOrthoZoom) inline
Sets ortho zoom amount.
Definition at line 530 of file EditorViewportClient.h.
References check, GetViewTransform(), and FViewportCameraTransform::SetOrthoZoom().
SetPreviewingScreenPercentage()
UNREALED_API void FEditorViewportClient::SetPreviewingScreenPercentage (bool bIsPreviewing)
Sets whether preview screen percentage for UI.
SetPreviewScreenPercentage()
UNREALED_API void FEditorViewportClient::SetPreviewScreenPercentage (int32 PreviewScreenPercentage)
Set preview screen percentage on UI behalf.
SetRealtime()
UNREALED_API void FEditorViewportClient::SetRealtime (bool bInRealtime)
Sets whether or not the viewport updates in realtime.
Note: This value is saved between editor sessions so it should not be used for temporary states. For that see SetRealtimeOverride
SetRequiredCursor()
UNREALED_API void FEditorViewportClient::SetRequiredCursor (const bool bHardwareCursorVisible, const bool bSoftwareCursorVisible) protected
Sets the required hardware and software cursor.
SetRequiredCursorOverride()
UNREALED_API void FEditorViewportClient::SetRequiredCursorOverride (bool WantOverride, EMouseCursor::Type RequiredCursor = EMouseCursor::Default)
Overrides current cursor.
References EMouseCursor::Default.
SetShowAspectRatioBarDisplay()
void FEditorViewportClient::SetShowAspectRatioBarDisplay (bool bEnable) inline
Aspect ratio bar display settings.
Definition at line 1265 of file EditorViewportClient.h.
References EngineShowFlags, and Invalidate().
SetShowBounds()
UNREALED_API void FEditorViewportClient::SetShowBounds (bool bShow)
Sets the show bounds flag.
References SetShowBounds().
Referenced by SetShowBounds().
SetShowCollision()
UNREALED_API void FEditorViewportClient::SetShowCollision ()
Callback for toggling the collision geometry show flag.
References SetShowCollision().
Referenced by SetShowCollision().
SetShowGrid()
UNREALED_API void FEditorViewportClient::SetShowGrid ()
Callback for toggling the grid show flag.
References SetShowGrid().
Referenced by SetShowGrid().
SetShowSafeFrameBoxDisplay()
void FEditorViewportClient::SetShowSafeFrameBoxDisplay (bool bEnable) inline
Definition at line 1271 of file EditorViewportClient.h.
References EngineShowFlags, and Invalidate().
SetShowStats()
virtual UNREALED_API void FEditorViewportClient::SetShowStats (bool bWantStats) override virtual
Sets whether or not stats info is displayed over the viewport.
Parameters
bWantStats true if stats should be displayed
Reimplemented from FViewportClient.
SetStatEnabled()
UNREALED_API int32 FEditorViewportClient::SetStatEnabled (const TCHAR * InName, const bool bEnable, const bool bAll = false) private
Set a specific stat to either enabled or disabled (returns true if there are any stats enabled)
References InName.
SetupViewForRendering()
virtual UNREALED_API void FEditorViewportClient::SetupViewForRendering (FSceneViewFamily & ViewFamily, FSceneView & View) virtual
Called to do any additional set up of the view for rendering.
Parameters
ViewFamily The view family being rendered
View The view being rendered
Reimplemented in FLevelEditorViewportClient.
SetViewLocation()
void FEditorViewportClient::SetViewLocation (const FVector & NewLocation) inline
Sets the location of the viewport's camera.
Definition at line 492 of file EditorViewportClient.h.
References FVector, GetViewTransform(), and FViewportCameraTransform::SetLocation().
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient().
SetViewLocationForOrbiting()
UNREALED_API void FEditorViewportClient::SetViewLocationForOrbiting (const FVector & LookAtPoint, float DistanceToCamera = 256.f)
Sets the camera view location such that the LookAtPoint point is at the specified location.
References FVector.
SetViewMode()
virtual UNREALED_API void FEditorViewportClient::SetViewMode (EViewModeIndex InViewModeIndex) virtual
Sets how the viewport is displayed (lit, wireframe, etc) for the current viewport type.
Parameters
InViewModeIndex View mode to set for the current viewport type
SetViewModeParam()
UNREALED_API void FEditorViewportClient::SetViewModeParam (int32 InViewModeParam)
Set the viewmode param.
SetViewModes()
UNREALED_API void FEditorViewportClient::SetViewModes (const EViewModeIndex InPerspViewModeIndex, const EViewModeIndex InOrthoViewModeIndex)
Sets how the viewport is displayed (lit, wireframe, etc)
Parameters
InPerspViewModeIndex View mode to set when this viewport is of type LVT_Perspective
InOrthoViewModeIndex View mode to set when this viewport is not of type LVT_Perspective
SetViewportType()
virtual UNREALED_API void FEditorViewportClient::SetViewportType (ELevelViewportType InViewportType) virtual
Set the viewport type of the client.
Parameters
InViewportType The viewport type to set the client to
Reimplemented in FLevelEditorViewportClient.
SetViewRotation()
void FEditorViewportClient::SetViewRotation (const FRotator & NewRotation) inline
Sets the location of the viewport's camera.
Definition at line 499 of file EditorViewportClient.h.
References GetViewTransform(), and FViewportCameraTransform::SetRotation().
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient(), and RemoveCameraRoll().
SetVREditView()
virtual UNREALED_API void FEditorViewportClient::SetVREditView (bool bGameViewEnable) virtual
Reimplemented in FLevelEditorViewportClient.
SetWidgetCoordSystemSpace()
virtual UNREALED_API void FEditorViewportClient::SetWidgetCoordSystemSpace (ECoordSystem NewCoordSystem) virtual
Sets the coordinate system space to use.
SetWidgetMode()
virtual UNREALED_API void FEditorViewportClient::SetWidgetMode (UE::Widget::EWidgetMode NewMode) virtual
Sets the current widget mode.
SetWidgetModeOverride()
UNREALED_API void FEditorViewportClient::SetWidgetModeOverride (UE::Widget::EWidgetMode InWidgetMode)
Overrides current widget mode.
ShouldLockPitch()
virtual UNREALED_API bool FEditorViewportClient::ShouldLockPitch () const virtual
Returns
true to lock the pitch of the viewport camera
Reimplemented in FLevelEditorViewportClient.
ShouldOrbitCamera()
virtual UNREALED_API bool FEditorViewportClient::ShouldOrbitCamera () const virtual
Returns
Whether or not to orbit the camera
ShouldPanOrDollyCamera()
UNREALED_API bool FEditorViewportClient::ShouldPanOrDollyCamera () const private
Returns
Whether or not the camera should be panned or dollied
ShouldScaleCameraSpeedByDistance()
virtual UNREALED_API bool FEditorViewportClient::ShouldScaleCameraSpeedByDistance () const virtual
Returns
True if the camera speed should be scaled by its view distance.
Reimplemented in FLevelEditorViewportClient.
ShouldShowStats()
bool FEditorViewportClient::ShouldShowStats () const inline
Returns true if status information should be displayed over the viewport.
Returns
true if stats should be displayed
Definition at line 955 of file EditorViewportClient.h.
References bShowStats.
ShouldUseMoveCanvasMovement()
UNREALED_API bool FEditorViewportClient::ShouldUseMoveCanvasMovement () const protected
ShowWidget()
UNREALED_API void FEditorViewportClient::ShowWidget (const bool bShow)
Show or hide the widget.
StartTrackingDueToInput()
UNREALED_API void FEditorViewportClient::StartTrackingDueToInput (const struct FInputEventState & InputState, FSceneView & View) protected
Starts tracking the mouse due to mouse input.
Parameters
InputState The mouse and keyboard input state at the time the mouse input happened
View The view of the scene in this viewport
StopTracking()
UNREALED_API void FEditorViewportClient::StopTracking () protected
Stops any mouse tracking.
SupportsLowDPIPreview()
UNREALED_API bool FEditorViewportClient::SupportsLowDPIPreview () const
Returns
True if DPI preview is supported.
SupportsPreviewResolutionFraction()
UNREALED_API bool FEditorViewportClient::SupportsPreviewResolutionFraction () const
Returns
True if PreviewResolutionFraction is supported.
TakeHighResScreenShot()
UNREALED_API void FEditorViewportClient::TakeHighResScreenShot ()
TakeScreenshot()
UNREALED_API void FEditorViewportClient::TakeScreenshot (FViewport * Viewport, bool bInvalidateViewport)
Takes the screenshot capture, this is called by keybinded events as well InputTakeScreenshot.
Parameters
Viewport The viewport to take a screenshot of.
bInvalidateViewport Some methods already invalidate the viewport before calling this method.
References Viewport.
Tick()
virtual UNREALED_API void FEditorViewportClient::Tick (float DeltaSeconds) virtual
Ticks this viewport client.
Reimplemented in FDataflowConstructionViewportClient, FDataflowSimulationViewportClient, and FLevelEditorViewportClient.
ToggleOrbitCamera()
UNREALED_API void FEditorViewportClient::ToggleOrbitCamera (bool bEnableOrbitCamera)
Toggle between orbit camera and fly camera.
ToggleRealtime()
UNREALED_API bool FEditorViewportClient::ToggleRealtime ()
Toggles whether or not the viewport updates in realtime and returns the updated state.
Note: This value is saved between editor sessions so it should not be used for temporary states. For that see SetRealtimeOverride
Returns
The current state of the realtime flag.
ToggleShowBounds()
UNREALED_API void FEditorViewportClient::ToggleShowBounds ()
Callback for toggling the bounds show flag.
References ToggleShowBounds().
Referenced by ToggleShowBounds().
TrackingStarted()
virtual void FEditorViewportClient::TrackingStarted (const struct FInputEventState & InInputState, bool bIsDraggingWidget, bool bNudge) inline virtual
Called when mouse movement tracking begins.
Parameters
InInputState The current mouse and keyboard input state
bIsDraggingWidget True if a widget is being dragged
bNudge True if we are tracking due to a nudge movement with the arrow keys
Reimplemented in FLevelEditorViewportClient.
Definition at line 653 of file EditorViewportClient.h.
TrackingStopped()
virtual void FEditorViewportClient::TrackingStopped () inline virtual
Called when mouse movement tracking stops.
Reimplemented in FLevelEditorViewportClient.
Definition at line 658 of file EditorViewportClient.h.
TranslateDelta()
UNREALED_API FVector FEditorViewportClient::TranslateDelta (FKey InKey, float InDelta, bool InNudge)
Determines which axis InKey and InDelta most refer to and returns a corresponding FVector.
This vector represents the mouse movement translated into the viewports/widgets axis space.
Parameters
InNudge If 1, this delta is coming from a keyboard nudge and not the mouse
References FVector.
UE_DEPRECATED() [1/4]
FEditorViewportClient::UE_DEPRECATED (4. 25, "SetRealtime no longer takes in bStoreCurrentValue parameter. For temporary overrides use AddRealtimeOverride")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FEditorViewportClient::UE_DEPRECATED (4. 25, "To save and restore realtime state non-permanently use AddRealtimeOverride and RemoveRealtimeOverride") const
Restores realtime setting to stored value.
This will only enable realtime and never disable it (unless bAllowDisable is true)
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FEditorViewportClient::UE_DEPRECATED (5. 0, "This function is meant for legacy edge cases pre-UAssetEditor, where the toolkit may not be the original owner of the mode manager.") &
Legacy adapter for a toolkit to take ownership of a mode manager that may have been created by this viewport client.
UE_DEPRECATED() [4/4]
FEditorViewportClient::UE_DEPRECATED (5. 4, "Use the overload that takes FDropObjectOptions instead.")
UnrealUnitsToSiUnits()
UNREALED_API FString FEditorViewportClient::UnrealUnitsToSiUnits (float UnrealUnits) static
Get a prettified string representation of the specified unreal units.
UnregisterPrioritizedInputChord()
UNREALED_API void FEditorViewportClient::UnregisterPrioritizedInputChord (const FName InInputCordName)
UpdateAndApplyCursorVisibility()
UNREALED_API void FEditorViewportClient::UpdateAndApplyCursorVisibility () protected
Updates the visibility of the hardware and software cursors according to the viewport's state.
UpdateCameraMovement()
UNREALED_API void FEditorViewportClient::UpdateCameraMovement (float DeltaTime) private
Updates real-time camera movement.
Should be called every viewport tick!
Parameters
DeltaTime Time interval in seconds since last update
References FViewportClient::DeltaTime.
UpdateCameraMovementFromJoystick()
UNREALED_API void FEditorViewportClient::UpdateCameraMovementFromJoystick (const bool bRelativeMovement, FCameraControllerConfig & InConfig) private
Applies Joystick axis control to camera movement.
UpdateDropPreviewActors()
virtual bool FEditorViewportClient::UpdateDropPreviewActors (int32 MouseX, int32 MouseY, const TArray< UObject * > & DroppedObjects, bool & out_bDroppedObjectsVisible, UActorFactory * FactoryToUse = nullptr) inline virtual
If dragging an actor for placement, this function updates its position.
Parameters
MouseX The position of the mouse's X coordinate
MouseY The position of the mouse's Y coordinate
DroppedObjects The Objects that were used to create preview objects
out_bDroppedObjectsVisible Output, returns if preview objects are visible or not
Returns true if preview actors were updated
Reimplemented in FLevelEditorViewportClient.
Definition at line 849 of file EditorViewportClient.h.
References DroppedObjects, FactoryToUse, and MouseY.
UpdateDropPreviewElements()
virtual bool FEditorViewportClient::UpdateDropPreviewElements (int32 MouseX, int32 MouseY, const TArray< UObject * > & DroppedObjects, bool & out_bDroppedObjectsVisible, TScriptInterface< IAssetFactoryInterface > Factory = nullptr) inline virtual
If dragging items for placement, this function updates their position.
Parameters
MouseX The position of the mouse's X coordinate
MouseY The position of the mouse's Y coordinate
DroppedObjects The Objects that were used to create preview objects
out_bDroppedObjectsVisible Output, returns if preview objects are visible or not
Returns true if preview elements were updated
Reimplemented in FLevelEditorViewportClient.
Definition at line 870 of file EditorViewportClient.h.
References DroppedObjects, and MouseY.
UpdateGestureDelta()
virtual UNREALED_API void FEditorViewportClient::UpdateGestureDelta () virtual
Called each frame to update the viewport based on delta trackpad gestures.
UpdateHiddenCollisionDrawing()
UNREALED_API void FEditorViewportClient::UpdateHiddenCollisionDrawing ()
When collision draw mode changes, this function allows hidden objects to be drawn, so hidden colliding objects can be seen.
UpdateLightingShowFlags()
UNREALED_API void FEditorViewportClient::UpdateLightingShowFlags (FEngineShowFlags & InOutShowFlags) private
Forcibly disables lighting show flags if there are no lights in the scene, or restores lighting show flags if lights are added to the scene.
UpdateLinkedOrthoViewports()
virtual void FEditorViewportClient::UpdateLinkedOrthoViewports (bool bInvalidate = false) inline virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 820 of file EditorViewportClient.h.
UpdateMouseDelta()
virtual UNREALED_API void FEditorViewportClient::UpdateMouseDelta () virtual
Called each frame to update the viewport based on delta mouse movements.
UpdateRequiredCursorVisibility()
UNREALED_API void FEditorViewportClient::UpdateRequiredCursorVisibility () protected
Setup the cursor visibility state we require and store in RequiredCursorVisibiltyAndAppearance struct.
UpdateViewportClientWindowDPIScale()
virtual UNREALED_API float FEditorViewportClient::UpdateViewportClientWindowDPIScale () const override protected virtual
FCommonViewportClient interface.
Reimplemented from FCommonViewportClient.
Friends And Related Symbol Documentation
FMouseDeltaTracker
friend class FMouseDeltaTracker friend
Definition at line 338 of file EditorViewportClient.h.
References FMouseDeltaTracker.
Referenced by FMouseDeltaTracker, and GetMouseDeltaTracker().
Field Documentation
AspectRatio
float FEditorViewportClient::AspectRatio
Definition at line 1864 of file EditorViewportClient.h.
bAllowCinematicControl
bool FEditorViewportClient::bAllowCinematicControl protected
true if this window is allowed to be possessed by cinematic tools for previewing sequences in real-time
Definition at line 1229 of file EditorViewportClient.h.
bCameraLock
bool FEditorViewportClient::bCameraLock protected
Camera Lock or not.
Definition at line 2013 of file EditorViewportClient.h.
bCreateDropPreview
int32 const TArray<UObject*> TArray<AActor*> bool bool FEditorViewportClient::bCreateDropPreview = false
Definition at line 923 of file EditorViewportClient.h.
Referenced by FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnBackground(), FLevelEditorViewportClient::DropObjectsOnBSPSurface(), and FLevelEditorViewportClient::DropObjectsOnWidget().
bDisableInput
bool FEditorViewportClient::bDisableInput
true if all input is rejected from this viewport
Definition at line 1889 of file EditorViewportClient.h.
bDraggingByHandle
bool FEditorViewportClient::bDraggingByHandle protected
true if the user is dragging by a widget handle.
Definition at line 1980 of file EditorViewportClient.h.
bDrawAxes
bool FEditorViewportClient::bDrawAxes
If true, draw the axis indicators when the viewport is perspective.
Definition at line 1892 of file EditorViewportClient.h.
bDrawAxesGame
bool FEditorViewportClient::bDrawAxesGame
If true, draw the axis indicators when EngineShowFlags.Game is set.
Definition at line 1895 of file EditorViewportClient.h.
bDrawVertices
bool FEditorViewportClient::bDrawVertices
If true, draw vertices for selected BSP brushes and static meshes if the large vertices show flag is set.
Definition at line 1904 of file EditorViewportClient.h.
bForceAudioRealtime
bool FEditorViewportClient::bForceAudioRealtime protected
If true, force this viewport to use real time audio regardless of other settings.
Definition at line 1989 of file EditorViewportClient.h.
Referenced by IsForcedRealtimeAudio(), and SetForcedAudioRealtime().
bForcingUnlitForNewMap
bool FEditorViewportClient::bForcingUnlitForNewMap
true if we've forced the SHOW_Lighting show flag off because there are no lights in the scene
Definition at line 1867 of file EditorViewportClient.h.
bHasAudioFocus
bool FEditorViewportClient::bHasAudioFocus protected
If true, this viewport gets to set audio parameters (e.g.
set the listener)
Definition at line 2001 of file EditorViewportClient.h.
Referenced by ClearAudioFocus(), and SetAudioFocus().
bHasMouseMovedSinceClick
bool FEditorViewportClient::bHasMouseMovedSinceClick protected
If true, the canvas has been been moved using bMoveCanvas Mode.
Definition at line 1924 of file EditorViewportClient.h.
bInGameViewMode
bool FEditorViewportClient::bInGameViewMode private
If true, we are in Game View mode.
Definition at line 2147 of file EditorViewportClient.h.
Referenced by IsInGameView().
bInVREditViewMode
bool FEditorViewportClient::bInVREditViewMode private
If true, we are in VR Edit View mode.
Definition at line 2150 of file EditorViewportClient.h.
bIsCameraMoving
bool FEditorViewportClient::bIsCameraMoving protected
Is the camera moving?
Definition at line 2016 of file EditorViewportClient.h.
bIsCameraMovingOnTick
bool FEditorViewportClient::bIsCameraMovingOnTick protected
Is the camera moving at the beginning of the tick?
Definition at line 2019 of file EditorViewportClient.h.
bIsCurrentLevelEditingFocus
bool FEditorViewportClient::bIsCurrentLevelEditingFocus = false private
True if this is the current viewport client in editing.
Definition at line 2169 of file EditorViewportClient.h.
Referenced by GetIsCurrentLevelEditingFocus(), and SetIsCurrentLevelEditingFocus().
bIsPreviewingResolutionFraction
bool FEditorViewportClient::bIsPreviewingResolutionFraction = false private
Controles resolution fraction for previewing in editor viewport at different screen percentage.
Definition at line 2110 of file EditorViewportClient.h.
bIsRealtime
bool FEditorViewportClient::bIsRealtime protected
if the viewport is currently realtime
Definition at line 1995 of file EditorViewportClient.h.
Referenced by IsRealtime().
bIsSimulateInEditorViewport
bool FEditorViewportClient::bIsSimulateInEditorViewport protected
True if this level viewport can be used to view Simulate in Editor sessions.
Definition at line 2010 of file EditorViewportClient.h.
Referenced by IsSimulateInEditorViewport().
bIsTracking
bool FEditorViewportClient::bIsTracking protected
true when within a FMouseDeltaTracker::StartTracking/EndTracking block.
Definition at line 1975 of file EditorViewportClient.h.
Referenced by IsTracking().
bIsTrackingBeingStopped
bool FEditorViewportClient::bIsTrackingBeingStopped private
true during FEditorViewportClient::StopTracking.
Used to guard against reentry.
Definition at line 2174 of file EditorViewportClient.h.
bLockFlightCamera
bool FEditorViewportClient::bLockFlightCamera
Flag to lock the viewport fly camera.
Definition at line 2072 of file EditorViewportClient.h.
bNeedsInvalidateHitProxy
bool FEditorViewportClient::bNeedsInvalidateHitProxy
If, following the next redraw, we should invalidate hit proxies on the viewport.
Definition at line 1878 of file EditorViewportClient.h.
bNeedsLinkedRedraw
bool FEditorViewportClient::bNeedsLinkedRedraw
Definition at line 1875 of file EditorViewportClient.h.
bNeedsRedraw
bool FEditorViewportClient::bNeedsRedraw
The number of pending viewport redraws.
Definition at line 1873 of file EditorViewportClient.h.
bOnlyDropOnTarget
int32 const TArray<UObject*> TArray<AActor*> bool FEditorViewportClient::bOnlyDropOnTarget = false
Definition at line 923 of file EditorViewportClient.h.
Referenced by FLevelEditorViewportClient::DropObjectsAtCoordinates().
bSelectActors
int32 const TArray<UObject*> TArray<AActor*> bool bool bool FEditorViewportClient::bSelectActors = true
Definition at line 923 of file EditorViewportClient.h.
Referenced by FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnBackground(), FLevelEditorViewportClient::DropObjectsOnBSPSurface(), and FLevelEditorViewportClient::TryPlacingActorFromObject().
bSetListenerPosition
bool FEditorViewportClient::bSetListenerPosition
If true, the listener position will be set.
Definition at line 1898 of file EditorViewportClient.h.
bShouldApplyViewModifiers
bool FEditorViewportClient::bShouldApplyViewModifiers
Whether view modifiers should be called and applied.
Definition at line 1910 of file EditorViewportClient.h.
bShouldCheckHitProxy
bool FEditorViewportClient::bShouldCheckHitProxy protected
true when we are in a state where we can check the hit proxy for hovering.
Definition at line 2004 of file EditorViewportClient.h.
bShouldInvalidateViewportWidget
bool FEditorViewportClient::bShouldInvalidateViewportWidget private
If true, the viewport widget should be invalidated on the next tick (needed to ensure thread safety)
Definition at line 2153 of file EditorViewportClient.h.
bShowStats
bool FEditorViewportClient::bShowStats protected
True if we should draw stats over the viewport.
Definition at line 1998 of file EditorViewportClient.h.
Referenced by ShouldShowStats().
bShowWidget
bool FEditorViewportClient::bShowWidget protected
Whether the widget should be drawn.
Definition at line 1919 of file EditorViewportClient.h.
Referenced by GetShowWidget().
bStoreCurrentValue
bool FEditorViewportClient::bStoreCurrentValue
Definition at line 441 of file EditorViewportClient.h.
bUseControllingActorViewInfo
bool FEditorViewportClient::bUseControllingActorViewInfo protected
Definition at line 1944 of file EditorViewportClient.h.
bUseNumpadCameraControl
bool FEditorViewportClient::bUseNumpadCameraControl
If true, numpad keys will be used to move camera in perspective viewport.
Definition at line 1884 of file EditorViewportClient.h.
bUserIsControllingAtmosphericLight0
bool FEditorViewportClient::bUserIsControllingAtmosphericLight0 = false protected
True is the use is controling the light via a shorcut.
Definition at line 1963 of file EditorViewportClient.h.
bUserIsControllingAtmosphericLight1
bool FEditorViewportClient::bUserIsControllingAtmosphericLight1 = false protected
Definition at line 1964 of file EditorViewportClient.h.
bUsesDrawHelper
bool FEditorViewportClient::bUsesDrawHelper protected
True if this viewport uses a draw helper.
Definition at line 2007 of file EditorViewportClient.h.
bUsingOrbitCamera
bool FEditorViewportClient::bUsingOrbitCamera
True if the orbit camera is currently being used.
Definition at line 1881 of file EditorViewportClient.h.
bWidgetAxisControlledByDrag
bool FEditorViewportClient::bWidgetAxisControlledByDrag
true if the widget's axis is being controlled by an active mouse drag.
Definition at line 1870 of file EditorViewportClient.h.
CachedLastMouseX
int32 FEditorViewportClient::CachedLastMouseX = 0 protected
Represents the last mouse position.
It is constantly updated on tick so it can also be the current position.
Definition at line 1959 of file EditorViewportClient.h.
CachedLastMouseY
int32 FEditorViewportClient::CachedLastMouseY = 0 protected
Definition at line 1960 of file EditorViewportClient.h.
CachedMouseX
uint32 FEditorViewportClient::CachedMouseX protected
Represents the last known mouse position.
If the mouse stops moving it's not the current but the last position before the current location.
Definition at line 1955 of file EditorViewportClient.h.
Referenced by GetCachedMouseX().
CachedMouseY
uint32 FEditorViewportClient::CachedMouseY protected
Definition at line 1956 of file EditorViewportClient.h.
Referenced by GetCachedMouseY().
CameraController
FEditorCameraController* FEditorViewportClient::CameraController protected
Camera controller object that's used for piloting the camera around.
Definition at line 1933 of file EditorViewportClient.h.
Referenced by GetCameraController().
CameraSpeedScalar
float FEditorViewportClient::CameraSpeedScalar protected
Camera speed scalar.
Definition at line 1235 of file EditorViewportClient.h.
CameraSpeedSetting
int32 FEditorViewportClient::CameraSpeedSetting protected
Camera speed setting.
Definition at line 1232 of file EditorViewportClient.h.
CameraUserImpulseData
FCameraControllerUserImpulseData* FEditorViewportClient::CameraUserImpulseData protected
Current cached impulse state.
Definition at line 1936 of file EditorViewportClient.h.
CapturedMouseMoves
TArray<FIntPoint> FEditorViewportClient::CapturedMouseMoves private
Definition at line 2163 of file EditorViewportClient.h.
ControllingActorAspectRatioAxisConstraint
TOptional<EAspectRatioAxisConstraint> FEditorViewportClient::ControllingActorAspectRatioAxisConstraint protected
Definition at line 1946 of file EditorViewportClient.h.
ControllingActorExtraPostProcessBlends
TArray<FPostProcessSettings> FEditorViewportClient::ControllingActorExtraPostProcessBlends protected
Definition at line 1947 of file EditorViewportClient.h.
ControllingActorExtraPostProcessBlendWeights
TArray<float> FEditorViewportClient::ControllingActorExtraPostProcessBlendWeights protected
Definition at line 1948 of file EditorViewportClient.h.
ControllingActorViewInfo
FMinimalViewInfo FEditorViewportClient::ControllingActorViewInfo protected
Definition at line 1945 of file EditorViewportClient.h.
CurrentBufferVisualizationMode
FName FEditorViewportClient::CurrentBufferVisualizationMode
Definition at line 1842 of file EditorViewportClient.h.
CurrentGestureDragDelta
FVector FEditorViewportClient::CurrentGestureDragDelta protected
Cumulative camera drag and rotation deltas from trackpad gesture in current Tick.
Definition at line 1983 of file EditorViewportClient.h.
CurrentGestureRotDelta
FRotator FEditorViewportClient::CurrentGestureRotDelta protected
Definition at line 1984 of file EditorViewportClient.h.
CurrentGPUSkinCacheVisualizationMode
FName FEditorViewportClient::CurrentGPUSkinCacheVisualizationMode
Definition at line 1851 of file EditorViewportClient.h.
CurrentGroomVisualizationMode
FName FEditorViewportClient::CurrentGroomVisualizationMode
Definition at line 1846 of file EditorViewportClient.h.
CurrentLumenVisualizationMode
FName FEditorViewportClient::CurrentLumenVisualizationMode
Definition at line 1844 of file EditorViewportClient.h.
CurrentMousePos
FIntPoint FEditorViewportClient::CurrentMousePos protected
Definition at line 1970 of file EditorViewportClient.h.
CurrentNaniteVisualizationMode
FName FEditorViewportClient::CurrentNaniteVisualizationMode
Definition at line 1843 of file EditorViewportClient.h.
CurrentRayTracingDebugVisualizationMode
FName FEditorViewportClient::CurrentRayTracingDebugVisualizationMode
Definition at line 1850 of file EditorViewportClient.h.
CurrentSubstrateVisualizationMode
FName FEditorViewportClient::CurrentSubstrateVisualizationMode
Definition at line 1845 of file EditorViewportClient.h.
CurrentVirtualShadowMapVisualizationMode
FName FEditorViewportClient::CurrentVirtualShadowMapVisualizationMode
Definition at line 1847 of file EditorViewportClient.h.
CurrentVirtualTextureVisualizationMode
FName FEditorViewportClient::CurrentVirtualTextureVisualizationMode
Definition at line 1848 of file EditorViewportClient.h.
CustomTemporalUpscalerData
TSharedPtr<ICustomTemporalUpscalerData> FEditorViewportClient::CustomTemporalUpscalerData private
Definition at line 2106 of file EditorViewportClient.h.
Referenced by GetCustomTemporalUpscalerData(), and SetCustomTemporalUpscalerData().
DefaultOrbitLocation
FVector FEditorViewportClient::DefaultOrbitLocation = FVector::ZeroVector protected
Definition at line 2035 of file EditorViewportClient.h.
DefaultOrbitLookAt
FVector FEditorViewportClient::DefaultOrbitLookAt = FVector::ZeroVector protected
Definition at line 2037 of file EditorViewportClient.h.
DefaultOrbitRotation
FRotator FEditorViewportClient::DefaultOrbitRotation = FRotator::ZeroRotator protected
default set up for toggling back
Definition at line 2034 of file EditorViewportClient.h.
DefaultOrbitZoom
FVector FEditorViewportClient::DefaultOrbitZoom = FVector::ZeroVector protected
Definition at line 2036 of file EditorViewportClient.h.
DefaultOrthoViewMode
UNREALED_API const EViewModeIndex FEditorViewportClient::DefaultOrthoViewMode static
Definition at line 2069 of file EditorViewportClient.h.
DefaultPerspectiveViewMode
UNREALED_API const EViewModeIndex FEditorViewportClient::DefaultPerspectiveViewMode static
Definition at line 2066 of file EditorViewportClient.h.
DragStartView
FSceneView* FEditorViewportClient::DragStartView private
Definition at line 2160 of file EditorViewportClient.h.
DragStartViewFamily
FSceneViewFamily* FEditorViewportClient::DragStartViewFamily private
Definition at line 2161 of file EditorViewportClient.h.
DrawHelper
FEditorCommonDrawHelper FEditorViewportClient::DrawHelper protected
Draw helper for rendering common editor functionality like the grid.
Definition at line 2022 of file EditorViewportClient.h.
DroppedObjects
int32 const TArray<UObject*>& FEditorViewportClient::DroppedObjects
Definition at line 922 of file EditorViewportClient.h.
Referenced by DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnBackground(), FLevelEditorViewportClient::DropObjectsOnBackground(), FLevelEditorViewportClient::DropObjectsOnBSPSurface(), FLevelEditorViewportClient::DropObjectsOnBSPSurface(), FLevelEditorViewportClient::DropObjectsOnWidget(), UpdateDropPreviewActors(), FLevelEditorViewportClient::UpdateDropPreviewActors(), UpdateDropPreviewElements(), and FLevelEditorViewportClient::UpdateDropPreviewElements().
EditorViewportWidget
TWeakPtr<SEditorViewport> FEditorViewportClient::EditorViewportWidget protected
The editor viewport widget this client is attached to.
Definition at line 2025 of file EditorViewportClient.h.
Referenced by GetEditorViewportWidget().
EnabledStats
TArray<FString> FEditorViewportClient::EnabledStats protected
A list of all the stat names which are enabled for this viewport.
Definition at line 2081 of file EditorViewportClient.h.
EngineShowFlags
FEngineShowFlags FEditorViewportClient::EngineShowFlags
A set of flags that determines visibility for various scene elements.
Definition at line 1831 of file EditorViewportClient.h.
Referenced by GetEngineShowFlags(), IsShowingAspectRatioBarDisplay(), IsShowingSafeFrameBoxDisplay(), SetShowAspectRatioBarDisplay(), and SetShowSafeFrameBoxDisplay().
ExposureSettings
FExposureSettings FEditorViewportClient::ExposureSettings
Editor setting to allow designers to override the automatic expose.
Definition at line 1837 of file EditorViewportClient.h.
FactoryToUse
int32 const TArray<UObject*> TArray<AActor*> bool bool bool UActorFactory* FEditorViewportClient::FactoryToUse
Initial value:
= nullptr) { return false; }
    bool AllowsCinematicControl() const { return bAllowCinematicControl; }
    void SetAllowCinematicControl( bool bInAllowCinematicControl) { bAllowCinematicControl = bInAllowCinematicControl; }
    virtual bool WantsDrawWhenAppIsHidden() const { return false; }
    virtual bool UseAppTime() const { return IsRealtime() && !IsSimulateInEditorViewport(); }
public:
    UNREALED_API bool IsVisible() const
Definition at line 924 of file EditorViewportClient.h.
Referenced by FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnBackground(), FLevelEditorViewportClient::DropObjectsOnBSPSurface(), FLevelEditorViewportClient::TryPlacingActorFromObject(), UpdateDropPreviewActors(), and FLevelEditorViewportClient::UpdateDropPreviewActors().
FarPlane
float FEditorViewportClient::FarPlane private
If > 0, overrides the view's far clipping plane with a plane at the specified distance.
Definition at line 2144 of file EditorViewportClient.h.
FlightCameraSpeedScale
float FEditorViewportClient::FlightCameraSpeedScale protected
Extra camera speed scale for flight camera.
Definition at line 1942 of file EditorViewportClient.h.
FOVAngle
float FEditorViewportClient::FOVAngle
Viewport's stored horizontal field of view (saved in ini files).
Definition at line 1862 of file EditorViewportClient.h.
FramesSinceLastDraw
int32 FEditorViewportClient::FramesSinceLastDraw
The number of frames since this viewport was last drawn.
Only applies to linked orthographic movement.
Definition at line 1854 of file EditorViewportClient.h.
GestureMoveForwardBackwardImpulse
float FEditorViewportClient::GestureMoveForwardBackwardImpulse protected
Definition at line 1986 of file EditorViewportClient.h.
ImmersiveDelegate
FViewportStateGetter FEditorViewportClient::ImmersiveDelegate
Delegate used to get whether or not this client is in an immersive viewport.
Definition at line 1808 of file EditorViewportClient.h.
JoystickStateMap
TMap<int32, FCachedJoystickState*> FEditorViewportClient::JoystickStateMap protected
Cached state of joystick axes and buttons.
Definition at line 1930 of file EditorViewportClient.h.
LandscapeLODOverride
int8 FEditorViewportClient::LandscapeLODOverride
Definition at line 1901 of file EditorViewportClient.h.
LastEngineShowFlags
FEngineShowFlags FEditorViewportClient::LastEngineShowFlags
Previous value for engine show flags, used for toggling.
Definition at line 1834 of file EditorViewportClient.h.
LastMouseX
uint32 FEditorViewportClient::LastMouseX protected
Definition at line 1951 of file EditorViewportClient.h.
LastMouseY
uint32 FEditorViewportClient::LastMouseY protected
Definition at line 1952 of file EditorViewportClient.h.
MaxCameraSpeeds
UNREALED_API const uint32 FEditorViewportClient::MaxCameraSpeeds static
Definition at line 1805 of file EditorViewportClient.h.
MinimumFocusRadius
FVector::FReal FEditorViewportClient::MinimumFocusRadius = 10.0 protected
When focusing viewport on a box, treat boxes smaller than this size as being this size.
Definition at line 2057 of file EditorViewportClient.h.
ModeTools
TSharedPtr<FEditorModeTools> FEditorViewportClient::ModeTools protected
Editor mode tools provided to this instance.
Definition at line 1914 of file EditorViewportClient.h.
Referenced by GetModeTools().
MouseDeltaTracker
FMouseDeltaTracker* FEditorViewportClient::MouseDeltaTracker protected
Definition at line 1921 of file EditorViewportClient.h.
Referenced by GetMouseDeltaTracker().
MouseY
int32 FEditorViewportClient::MouseY
Definition at line 922 of file EditorViewportClient.h.
Referenced by CanDropObjectsAtCoordinates(), FLevelEditorViewportClient::CanDropObjectsAtCoordinates(), DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsAtCoordinates(), UpdateDropPreviewActors(), FLevelEditorViewportClient::UpdateDropPreviewActors(), UpdateDropPreviewElements(), and FLevelEditorViewportClient::UpdateDropPreviewElements().
MovingPreviewLightSavedScreenPos
FVector2D FEditorViewportClient::MovingPreviewLightSavedScreenPos protected
Definition at line 2061 of file EditorViewportClient.h.
MovingPreviewLightTimer
float FEditorViewportClient::MovingPreviewLightTimer protected
Definition at line 2062 of file EditorViewportClient.h.
NearPlane
float FEditorViewportClient::NearPlane private
near plane adjustable for each editor view, if < 0 GNearClippingPlane should be used.
Definition at line 2141 of file EditorViewportClient.h.
OrthoViewModeIndex
EViewModeIndex FEditorViewportClient::OrthoViewModeIndex private
Definition at line 2131 of file EditorViewportClient.h.
Referenced by GetOrthoViewMode().
OutNewActors
int32 const TArray<UObject*> TArray<AActor*>& FEditorViewportClient::OutNewActors
Definition at line 922 of file EditorViewportClient.h.
Referenced by FLevelEditorViewportClient::DropObjectsAtCoordinates(), FLevelEditorViewportClient::DropObjectsOnActor(), FLevelEditorViewportClient::DropObjectsOnBackground(), and FLevelEditorViewportClient::DropObjectsOnBSPSurface().
OverrideShowFlagsFunc
TUniqueFunction<void(FEngineShowFlags&)> FEditorViewportClient::OverrideShowFlagsFunc protected
Custom override function that will be called every Draw() until override is disabled.
Definition at line 2054 of file EditorViewportClient.h.
Referenced by IsEngineShowFlagsOverrideEnabled().
PerspViewModeIndex
EViewModeIndex FEditorViewportClient::PerspViewModeIndex private
Definition at line 2128 of file EditorViewportClient.h.
Referenced by GetPerspViewMode().
PreviewResolutionFraction
TOptional<float> FEditorViewportClient::PreviewResolutionFraction private
Definition at line 2111 of file EditorViewportClient.h.
PreviewScene
FPreviewScene* FEditorViewportClient::PreviewScene protected
The scene used for the viewport.
Owned externally
Definition at line 2031 of file EditorViewportClient.h.
Referenced by GetPreviewScene().
PrioritizedInputChords
TArray<FPrioritizedInputChord> FEditorViewportClient::PrioritizedInputChords private
A list of input key combinations, sorted by priority.
See FPrioritizedInputChord.
Definition at line 2166 of file EditorViewportClient.h.
RealtimeOverrides
TArray<FRealtimeOverride> FEditorViewportClient::RealtimeOverrides protected
Definition at line 2051 of file EditorViewportClient.h.
Referenced by IsRealtime(), and IsRealtimeOverrideSet().
RealTimeUntilFrameNumber
uint64 FEditorViewportClient::RealTimeUntilFrameNumber protected
Overrides bIsRealtime until GFrameCounter is >= this number.
Used to force viewports to draw a number of frames even if they are otherwise non-realtime viewports.
Definition at line 1992 of file EditorViewportClient.h.
Referenced by IsRealtime(), and RequestRealTimeFrames().
RequiredCursorVisibiltyAndAppearance
FRequiredCursorState FEditorViewportClient::RequiredCursorVisibiltyAndAppearance protected
Cursor visibility and appearance information.
Definition at line 1927 of file EditorViewportClient.h.
SafePadding
UNREALED_API float const FEditorViewportClient::SafePadding static protected
Constant for how much the camera safe zone rectangle is inset when being displayed in the editor.
Definition at line 1588 of file EditorViewportClient.h.
SceneDPIMode
ESceneDPIMode FEditorViewportClient::SceneDPIMode private
Definition at line 2125 of file EditorViewportClient.h.
StatHitchesData
FStatHitchesData FEditorViewportClient::StatHitchesData mutable protected
Data needed to display per-frame stat tracking when STAT HITCHES is enabled.
Definition at line 2078 of file EditorViewportClient.h.
StatUnitData
FStatUnitData FEditorViewportClient::StatUnitData mutable protected
Data needed to display per-frame stat tracking when STAT UNIT is enabled.
Definition at line 2075 of file EditorViewportClient.h.
StereoViewStates
TArray<FSceneViewStateReference> FEditorViewportClient::StereoViewStates
Viewport view state when stereo rendering is enabled.
Definition at line 1828 of file EditorViewportClient.h.
TimeForForceRedraw
double FEditorViewportClient::TimeForForceRedraw protected
When we have LOD locking, it's slow to force redraw of other viewports, so we delay invalidates to reduce the number of redraws.
Definition at line 1939 of file EditorViewportClient.h.
UserControlledAtmosphericLightMatrix
FTransform FEditorViewportClient::UserControlledAtmosphericLightMatrix protected
Definition at line 1966 of file EditorViewportClient.h.
UserIsControllingAtmosphericLightTimer
float FEditorViewportClient::UserIsControllingAtmosphericLightTimer = 0.0f protected
Definition at line 1965 of file EditorViewportClient.h.
ViewFOV
float FEditorViewportClient::ViewFOV
Viewport's current horizontal field of view (can be modified by locked cameras etc.)
Definition at line 1860 of file EditorViewportClient.h.
ViewIndex
int32 FEditorViewportClient::ViewIndex
Index of this view in the editor's list of views.
Definition at line 1857 of file EditorViewportClient.h.
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient().
ViewModeParam
int32 FEditorViewportClient::ViewModeParam private
Definition at line 2134 of file EditorViewportClient.h.
ViewModeParamName
FName FEditorViewportClient::ViewModeParamName private
Definition at line 2135 of file EditorViewportClient.h.
ViewModeParamNameMap
TMap<int32, FName> FEditorViewportClient::ViewModeParamNameMap private
Definition at line 2138 of file EditorViewportClient.h.
Referenced by GetViewModeParamNameMap().
ViewModifiers
FEditorViewportViewModifierDelegate FEditorViewportClient::ViewModifiers
List of view modifiers to apply on view parameters.
Definition at line 1907 of file EditorViewportClient.h.
Viewport
FViewport* FEditorViewportClient::Viewport
Definition at line 1813 of file EditorViewportClient.h.
Referenced by Draw(), DrawAxes(), DrawSafeFrames(), DrawScaleUnits(), GetCursor(), FLevelEditorViewportClient::GetCursor(), GetOrthoUnitsPerPixel(), InputAxisForOrbit(), InputGesture(), InputTakeScreenshot(), FLevelEditorViewportClient::InputWidgetDelta(), Internal_InputAxis(), LostFocus(), MouseEnter(), MouseLeave(), MouseMove(), ProcessScreenShots(), FLevelEditorViewportClient::ProjectActorsIntoWorld(), ReceivedFocus(), RedrawRequested(), RequestInvalidateHitProxy(), and TakeScreenshot().
ViewportInteraction
TObjectPtr<UTypedElementViewportInteraction> FEditorViewportClient::ViewportInteraction protected
The viewport interaction instance for this viewport.
Definition at line 2028 of file EditorViewportClient.h.
ViewportType
ELevelViewportType FEditorViewportClient::ViewportType
The viewport type.
Definition at line 1822 of file EditorViewportClient.h.
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient(), and SetInitialViewTransform().
ViewState
FSceneViewStateReference FEditorViewportClient::ViewState
The viewport's scene view state.
Definition at line 1825 of file EditorViewportClient.h.
ViewTransformOrthographic
FViewportCameraTransform FEditorViewportClient::ViewTransformOrthographic
Viewport camera transform data for orthographic viewports.
Definition at line 1819 of file EditorViewportClient.h.
Referenced by GetViewTransform(), and GetViewTransform().
ViewTransformPerspective
FViewportCameraTransform FEditorViewportClient::ViewTransformPerspective
Viewport camera transform data for perspective viewports.
Definition at line 1816 of file EditorViewportClient.h.
Referenced by GetViewTransform(), and GetViewTransform().
VisibilityDelegate
FViewportStateGetter FEditorViewportClient::VisibilityDelegate
Delegate used to get the visibility of this client from a slate viewport layout and tab configuration.
Definition at line 1811 of file EditorViewportClient.h.
Widget
FWidget* FEditorViewportClient::Widget protected
Definition at line 1916 of file EditorViewportClient.h.
WireframeOpacity
float FEditorViewportClient::WireframeOpacity = 0.2f
Editor setting to adjust wireframe opacity.
Definition at line 1840 of file EditorViewportClient.h.
The documentation for this class was generated from the following file:
EditorViewportClient.h