Unreal Engine 5.6 C++ API: FCompressibleAnimData Struct Reference
FCompressibleAnimData Struct Reference
#include "AnimCompressionTypes.h"
Public Member Functions
FCompressibleAnimData ()
FCompressibleAnimData (class UAnimSequence *InSeq, const bool bPerformStripping, const ITargetPlatform *InTargetPlatform)
FCompressibleAnimData (const FCompressibleAnimData &)
FCompressibleAnimData (UAnimBoneCompressionSettings *InBoneCompressionSettings, UAnimCurveCompressionSettings *InCurveCompressionSettings, USkeleton *InSkeleton, EAnimInterpolationType InInterpolation, float InSequenceLength, int32 InNumberOfKeys, const ITargetPlatform *InTargetPlatform)
void AddReferencedObjects (FReferenceCollector &Collector)
void FetchData (const ITargetPlatform *InPlatform)
uint64 GetApproxMemoryUsage () const
int64 GetApproxRawBoneSize () const
int64 GetApproxRawCurveSize () const
int64 GetApproxRawSize () const
int32 GetNumberOfFrames () const
bool IsCancelled () const
FCompressibleAnimData & operator= (const FCompressibleAnimData &)
UE_DEPRECATED (5.0, "NumberOfFrames has been replaced with NumberOfKeys and GetNumberOfFrames") int32 NumberOfFrames
Number of keys within the (non-uniform) RawAnimationData tracks.
void Update (struct FCompressedAnimSequence &CompressedData) const
Static Public Member Functions
static int64 GetApproxRawDataArraySize (const TArray< FRawAnimSequenceTrack > &AnimData)
Data Fields
TArray< FRawAnimSequenceTrack > AdditiveBaseAnimationData
EAdditiveAnimationType AdditiveType = AAT_None
FName AnimFName
bool bDataFetched = false
bool bIsValidAdditive
TObjectPtr< UAnimBoneCompressionSettings > BoneCompressionSettings
TArray< FBoneData > BoneData
bool bShouldPerformStripping = false
TObjectPtr< UAnimCurveCompressionSettings > CurveCompressionSettings
float ErrorThresholdScale
FString FullName
EAnimInterpolationType Interpolation
FCancelCompressionSignal IsCancelledSignal
FString Name
int32 NumberOfKeys
TArray< FRawAnimSequenceTrack > RawAnimationData
TArray< FFloatCurve > RawFloatCurves
TArray< FTransform > RefLocalPoses
FReferenceSkeleton RefSkeleton
FFrameRate SampledFrameRate
double SequenceLength
const ITargetPlatform * TargetPlatform = nullptr
TArray< FTrackToSkeletonMap > TrackToSkeletonMapTable
TWeakObjectPtr< UAnimSequence > WeakSequence
Protected Member Functions
void BakeOutAdditiveIntoRawData (const FFrameRate &SampleRate, TArray< FBoneAnimationTrack > &ResampledTrackData, TArray< FFloatCurve > &FloatCurves)
void ResampleAnimationTrackData (const FFrameRate &SampleRate, TArray< FBoneAnimationTrack > &ResampledTrackData) const
Private Member Functions
void WriteCompressionDataToJSON (TArrayView< FName > OriginalTrackNames, TArrayView< FRawAnimSequenceTrack > FinalRawAnimationData, TArrayView< FName > FinalTrackNames) const
Detailed Description
Definition at line 201 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
FCompressibleAnimData() [1/4]
FCompressibleAnimData::FCompressibleAnimData ()
Referenced by FCompressibleAnimData(), and operator=().
FCompressibleAnimData() [2/4]
FCompressibleAnimData::FCompressibleAnimData (UAnimBoneCompressionSettings * InBoneCompressionSettings, UAnimCurveCompressionSettings * InCurveCompressionSettings, USkeleton * InSkeleton, EAnimInterpolationType InInterpolation, float InSequenceLength, int32 InNumberOfKeys, const ITargetPlatform * InTargetPlatform)
FCompressibleAnimData() [3/4]
FCompressibleAnimData::FCompressibleAnimData (class UAnimSequence * InSeq, const bool bPerformStripping, const ITargetPlatform * InTargetPlatform)
FCompressibleAnimData() [4/4]
FCompressibleAnimData::FCompressibleAnimData (const FCompressibleAnimData &)
References FCompressibleAnimData().
Member Function Documentation
AddReferencedObjects()
void FCompressibleAnimData::AddReferencedObjects (FReferenceCollector & Collector) inline
Definition at line 312 of file AnimCompressionTypes.h.
References BoneCompressionSettings, and CurveCompressionSettings.
BakeOutAdditiveIntoRawData()
void FCompressibleAnimData::BakeOutAdditiveIntoRawData (const FFrameRate & SampleRate, TArray< FBoneAnimationTrack > & ResampledTrackData, TArray< FFloatCurve > & FloatCurves) protected
FetchData()
void FCompressibleAnimData::FetchData (const ITargetPlatform * InPlatform)
GetApproxMemoryUsage()
uint64 FCompressibleAnimData::GetApproxMemoryUsage () const inline
Definition at line 299 of file AnimCompressionTypes.h.
References AdditiveBaseAnimationData, BoneData, GetApproxRawDataArraySize(), GetApproxRawSize(), and TrackToSkeletonMapTable.
GetApproxRawBoneSize()
int64 FCompressibleAnimData::GetApproxRawBoneSize () const inline
Definition at line 278 of file AnimCompressionTypes.h.
References GetApproxRawDataArraySize(), and RawAnimationData.
Referenced by GetApproxRawSize().
GetApproxRawCurveSize()
int64 FCompressibleAnimData::GetApproxRawCurveSize () const inline
Definition at line 283 of file AnimCompressionTypes.h.
References RawFloatCurves.
Referenced by GetApproxRawSize().
GetApproxRawDataArraySize()
int64 FCompressibleAnimData::GetApproxRawDataArraySize (const TArray< FRawAnimSequenceTrack > & AnimData) inline static
Definition at line 263 of file AnimCompressionTypes.h.
References FVector, and TArray< InElementType, InAllocatorType >::Num().
Referenced by GetApproxMemoryUsage(), and GetApproxRawBoneSize().
GetApproxRawSize()
int64 FCompressibleAnimData::GetApproxRawSize () const inline
Definition at line 294 of file AnimCompressionTypes.h.
References GetApproxRawBoneSize(), and GetApproxRawCurveSize().
Referenced by GetApproxMemoryUsage().
GetNumberOfFrames()
int32 FCompressibleAnimData::GetNumberOfFrames () const inline
Definition at line 241 of file AnimCompressionTypes.h.
References GetNumberOfFrames(), FMath::Max, and NumberOfKeys.
Referenced by GetNumberOfFrames().
IsCancelled()
bool FCompressibleAnimData::IsCancelled () const inline
Definition at line 318 of file AnimCompressionTypes.h.
References IsCancelledSignal.
operator=()
FCompressibleAnimData & FCompressibleAnimData::operator= (const FCompressibleAnimData &)
References FCompressibleAnimData().
ResampleAnimationTrackData()
void FCompressibleAnimData::ResampleAnimationTrackData (const FFrameRate & SampleRate, TArray< FBoneAnimationTrack > & ResampledTrackData) const protected
UE_DEPRECATED()
FCompressibleAnimData::UE_DEPRECATED (5. 0, "NumberOfFrames has been replaced with NumberOfKeys and GetNumberOfFrames")
Number of keys within the (non-uniform) RawAnimationData tracks.
Update()
void FCompressibleAnimData::Update (struct FCompressedAnimSequence & CompressedData) const
References CompressedData.
WriteCompressionDataToJSON()
void FCompressibleAnimData::WriteCompressionDataToJSON (TArrayView< FName > OriginalTrackNames, TArrayView< FRawAnimSequenceTrack > FinalRawAnimationData, TArrayView< FName > FinalTrackNames) const private
Field Documentation
AdditiveBaseAnimationData
TArray<FRawAnimSequenceTrack> FCompressibleAnimData::AdditiveBaseAnimationData
Definition at line 225 of file AnimCompressionTypes.h.
Referenced by GetApproxMemoryUsage().
AdditiveType
EAdditiveAnimationType FCompressibleAnimData::AdditiveType = AAT_None
Definition at line 243 of file AnimCompressionTypes.h.
AnimFName
FName FCompressibleAnimData::AnimFName
Definition at line 251 of file AnimCompressionTypes.h.
bDataFetched
bool FCompressibleAnimData::bDataFetched = false
Definition at line 259 of file AnimCompressionTypes.h.
bIsValidAdditive
bool FCompressibleAnimData::bIsValidAdditive
Definition at line 244 of file AnimCompressionTypes.h.
BoneCompressionSettings
TObjectPtr<UAnimBoneCompressionSettings> FCompressibleAnimData::BoneCompressionSettings
Definition at line 215 of file AnimCompressionTypes.h.
Referenced by AddReferencedObjects().
BoneData
TArray<FBoneData> FCompressibleAnimData::BoneData
Definition at line 229 of file AnimCompressionTypes.h.
Referenced by GetApproxMemoryUsage().
bShouldPerformStripping
bool FCompressibleAnimData::bShouldPerformStripping = false
Definition at line 257 of file AnimCompressionTypes.h.
CurveCompressionSettings
TObjectPtr<UAnimCurveCompressionSettings> FCompressibleAnimData::CurveCompressionSettings
Definition at line 213 of file AnimCompressionTypes.h.
Referenced by AddReferencedObjects().
ErrorThresholdScale
float FCompressibleAnimData::ErrorThresholdScale
Definition at line 246 of file AnimCompressionTypes.h.
FullName
FString FCompressibleAnimData::FullName
Definition at line 250 of file AnimCompressionTypes.h.
Interpolation
EAnimInterpolationType FCompressibleAnimData::Interpolation
Definition at line 227 of file AnimCompressionTypes.h.
IsCancelledSignal
FCancelCompressionSignal FCompressibleAnimData::IsCancelledSignal
Definition at line 255 of file AnimCompressionTypes.h.
Referenced by IsCancelled().
Name
FString FCompressibleAnimData::Name
Definition at line 249 of file AnimCompressionTypes.h.
NumberOfKeys
int32 FCompressibleAnimData::NumberOfKeys
Definition at line 239 of file AnimCompressionTypes.h.
Referenced by GetNumberOfFrames().
RawAnimationData
TArray<FRawAnimSequenceTrack> FCompressibleAnimData::RawAnimationData
Definition at line 223 of file AnimCompressionTypes.h.
Referenced by GetApproxRawBoneSize().
RawFloatCurves
TArray<FFloatCurve> FCompressibleAnimData::RawFloatCurves
Definition at line 231 of file AnimCompressionTypes.h.
Referenced by GetApproxRawCurveSize().
RefLocalPoses
TArray<FTransform> FCompressibleAnimData::RefLocalPoses
Definition at line 218 of file AnimCompressionTypes.h.
RefSkeleton
FReferenceSkeleton FCompressibleAnimData::RefSkeleton
Definition at line 219 of file AnimCompressionTypes.h.
SampledFrameRate
FFrameRate FCompressibleAnimData::SampledFrameRate
Definition at line 253 of file AnimCompressionTypes.h.
SequenceLength
double FCompressibleAnimData::SequenceLength
Definition at line 233 of file AnimCompressionTypes.h.
TargetPlatform
const ITargetPlatform* FCompressibleAnimData::TargetPlatform = nullptr
Definition at line 261 of file AnimCompressionTypes.h.
TrackToSkeletonMapTable
TArray<FTrackToSkeletonMap> FCompressibleAnimData::TrackToSkeletonMapTable
Definition at line 221 of file AnimCompressionTypes.h.
Referenced by GetApproxMemoryUsage().
WeakSequence
TWeakObjectPtr<UAnimSequence> FCompressibleAnimData::WeakSequence
Definition at line 258 of file AnimCompressionTypes.h.
The documentation for this struct was generated from the following file:
AnimCompressionTypes.h