Unreal Engine 5.6 C++ API: MovieSceneTimeWarpChannel.h File Reference
MovieSceneTimeWarpChannel.h File Reference
#include "Channels/MovieSceneChannelTraits.h"
#include "Channels/MovieSceneDoubleChannel.h"
#include "MovieSceneTimeWarpChannel.generated.h"
Data Structures
struct TMovieSceneChannelTraits< FMovieSceneTimeWarpChannel >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Enumerations
enum class UE::MovieScene::ETimeWarpChannelDomain : uint8 { UE::MovieScene::Time , UE::MovieScene::PlayRate }
Functions
FKeyHandle AddKeyToChannel (FMovieSceneTimeWarpChannel *Channel, FFrameNumber InFrameNumber, double InValue, EMovieSceneKeyInterpolation Interpolation)
void AssignValue (FMovieSceneTimeWarpChannel *InChannel, FKeyHandle InKeyHandle, double InValue)
void AssignValue (FMovieSceneTimeWarpChannel *InChannel, FKeyHandle InKeyHandle, float InValue)
USTRUCT() struct FMovieSceneTimeWarpChannel MOVIESCENE_API void Dilate (FMovieSceneTimeWarpChannel *InChannel, FFrameNumber Origin, double DilationFactor)
EMovieSceneKeyInterpolation GetTimeWarpMode (FMovieSceneDoubleChannel *InChannel, const FFrameNumber &InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel *InChannel, FFrameNumber InFrameNumber, const FMovieSceneDoubleValue &InValue)
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel *InChannel, FFrameNumber InFrameNumber, double Value)
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel *InChannel, FFrameNumber InFrameNumber, float Value)
Function Documentation
AddKeyToChannel()
FKeyHandle AddKeyToChannel (FMovieSceneTimeWarpChannel * Channel, FFrameNumber InFrameNumber, double InValue, EMovieSceneKeyInterpolation Interpolation) inline
Definition at line 39 of file MovieSceneTimeWarpChannel.h.
References AddKeyToChannel(), and Interpolation.
Referenced by AddKeyToChannel().
AssignValue() [1/2]
void AssignValue (FMovieSceneTimeWarpChannel * InChannel, FKeyHandle InKeyHandle, double InValue) inline
Definition at line 55 of file MovieSceneTimeWarpChannel.h.
References AssignValue().
Referenced by AssignValue(), and AssignValue().
AssignValue() [2/2]
void AssignValue (FMovieSceneTimeWarpChannel * InChannel, FKeyHandle InKeyHandle, float InValue) inline
Definition at line 59 of file MovieSceneTimeWarpChannel.h.
References AssignValue().
Dilate()
USTRUCT() struct FMovieSceneTimeWarpChannel MOVIESCENE_API void Dilate (FMovieSceneTimeWarpChannel * InChannel, FFrameNumber Origin, double DilationFactor)
References Origin.
GetTimeWarpMode()
EMovieSceneKeyInterpolation GetTimeWarpMode (FMovieSceneDoubleChannel * InChannel, const FFrameNumber & InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode) inline
Definition at line 35 of file MovieSceneTimeWarpChannel.h.
References GetInterpolationMode(), and InTime.
ValueExistsAtTime() [1/3]
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel * InChannel, FFrameNumber InFrameNumber, const FMovieSceneDoubleValue & InValue) inline
Definition at line 43 of file MovieSceneTimeWarpChannel.h.
References ValueExistsAtTime().
Referenced by ValueExistsAtTime(), ValueExistsAtTime(), and ValueExistsAtTime().
ValueExistsAtTime() [2/3]
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel * InChannel, FFrameNumber InFrameNumber, double Value) inline
Definition at line 47 of file MovieSceneTimeWarpChannel.h.
References Value, and ValueExistsAtTime().
ValueExistsAtTime() [3/3]
bool ValueExistsAtTime (const FMovieSceneTimeWarpChannel * InChannel, FFrameNumber InFrameNumber, float Value) inline
Definition at line 51 of file MovieSceneTimeWarpChannel.h.
References Value, and ValueExistsAtTime().