Unreal Engine 5.6 C++ API: IAbilitySystemReplicationProxyInterface Class Reference
IAbilitySystemReplicationProxyInterface Class Reference abstract
Interface for actors that act like an ability system component for replication.
#include "AbilitySystemReplicationProxyInterface.h"
Private Member Functions
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueAdded (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueAdded_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters Parameters)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueAddedAndWhileActive_FromSpec (const FGameplayEffectSpecForRPC &Spec, FPredictionKey PredictionKey)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueAddedAndWhileActive_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueExecuted (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueExecuted_FromSpec (const FGameplayEffectSpecForRPC Spec, FPredictionKey PredictionKey)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCueExecuted_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCuesAddedAndWhileActive_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCuesExecuted (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)
virtual GAMEPLAYABILITIES_API void Call_InvokeGameplayCuesExecuted_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)
GENERATED_IINTERFACE_BODY () virtual void ForceReplication()=0
virtual void NetMulticast_InvokeGameplayCueAdded (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)=0
virtual void NetMulticast_InvokeGameplayCueAdded_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters Parameters)=0
virtual void NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec (const FGameplayEffectSpecForRPC &Spec, FPredictionKey PredictionKey)=0
virtual void NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)=0
virtual void NetMulticast_InvokeGameplayCueExecuted (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)=0
virtual void NetMulticast_InvokeGameplayCueExecuted_FromSpec (const FGameplayEffectSpecForRPC Spec, FPredictionKey PredictionKey)=0
virtual void NetMulticast_InvokeGameplayCueExecuted_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)=0
virtual void NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)=0
virtual void NetMulticast_InvokeGameplayCuesExecuted (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext)=0
virtual void NetMulticast_InvokeGameplayCuesExecuted_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters)=0
Detailed Description
Interface for actors that act like an ability system component for replication.
This can be used to group together different components for replication
Definition at line 28 of file AbilitySystemReplicationProxyInterface.h.
Member Function Documentation
Call_InvokeGameplayCueAdded()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueAdded (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private virtual
References Call_InvokeGameplayCueAdded(), and UE_API.
Referenced by Call_InvokeGameplayCueAdded().
Call_InvokeGameplayCueAdded_WithParams()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueAdded_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters Parameters) private virtual
References Call_InvokeGameplayCueAdded_WithParams(), and UE_API.
Referenced by Call_InvokeGameplayCueAdded_WithParams().
Call_InvokeGameplayCueAddedAndWhileActive_FromSpec()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueAddedAndWhileActive_FromSpec (const FGameplayEffectSpecForRPC & Spec, FPredictionKey PredictionKey) private virtual
References Call_InvokeGameplayCueAddedAndWhileActive_FromSpec(), and UE_API.
Referenced by Call_InvokeGameplayCueAddedAndWhileActive_FromSpec().
Call_InvokeGameplayCueAddedAndWhileActive_WithParams()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueAddedAndWhileActive_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private virtual
References Call_InvokeGameplayCueAddedAndWhileActive_WithParams(), and UE_API.
Referenced by Call_InvokeGameplayCueAddedAndWhileActive_WithParams().
Call_InvokeGameplayCueExecuted()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueExecuted (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private virtual
References Call_InvokeGameplayCueExecuted(), and UE_API.
Referenced by Call_InvokeGameplayCueExecuted().
Call_InvokeGameplayCueExecuted_FromSpec()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueExecuted_FromSpec (const FGameplayEffectSpecForRPC Spec, FPredictionKey PredictionKey) private virtual
References Call_InvokeGameplayCueExecuted_FromSpec(), and UE_API.
Referenced by Call_InvokeGameplayCueExecuted_FromSpec().
Call_InvokeGameplayCueExecuted_WithParams()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCueExecuted_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private virtual
References Call_InvokeGameplayCueExecuted_WithParams(), and UE_API.
Referenced by Call_InvokeGameplayCueExecuted_WithParams().
Call_InvokeGameplayCuesAddedAndWhileActive_WithParams()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCuesAddedAndWhileActive_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private virtual
References Call_InvokeGameplayCuesAddedAndWhileActive_WithParams(), and UE_API.
Referenced by Call_InvokeGameplayCuesAddedAndWhileActive_WithParams().
Call_InvokeGameplayCuesExecuted()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCuesExecuted (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private virtual
References Call_InvokeGameplayCuesExecuted(), and UE_API.
Referenced by Call_InvokeGameplayCuesExecuted().
Call_InvokeGameplayCuesExecuted_WithParams()
virtual GAMEPLAYABILITIES_API void IAbilitySystemReplicationProxyInterface::Call_InvokeGameplayCuesExecuted_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private virtual
References Call_InvokeGameplayCuesExecuted_WithParams(), and UE_API.
Referenced by Call_InvokeGameplayCuesExecuted_WithParams().
GENERATED_IINTERFACE_BODY()
IAbilitySystemReplicationProxyInterface::GENERATED_IINTERFACE_BODY () private pure virtual
NetMulticast_InvokeGameplayCueAdded()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAdded (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private pure virtual
References NetMulticast_InvokeGameplayCueAdded().
Referenced by NetMulticast_InvokeGameplayCueAdded(), and UAbilitySystemComponent::UFUNCTION().
NetMulticast_InvokeGameplayCueAdded_WithParams()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAdded_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters Parameters) private pure virtual
References NetMulticast_InvokeGameplayCueAdded_WithParams().
Referenced by NetMulticast_InvokeGameplayCueAdded_WithParams().
NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec (const FGameplayEffectSpecForRPC & Spec, FPredictionKey PredictionKey) private pure virtual
References NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec().
Referenced by NetMulticast_InvokeGameplayCueAddedAndWhileActive_FromSpec(), and UAbilitySystemComponent::UFUNCTION().
NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private pure virtual
References NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams().
Referenced by NetMulticast_InvokeGameplayCueAddedAndWhileActive_WithParams(), and UAbilitySystemComponent::UFUNCTION().
NetMulticast_InvokeGameplayCueExecuted()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueExecuted (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private pure virtual
References NetMulticast_InvokeGameplayCueExecuted().
Referenced by NetMulticast_InvokeGameplayCueExecuted().
NetMulticast_InvokeGameplayCueExecuted_FromSpec()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueExecuted_FromSpec (const FGameplayEffectSpecForRPC Spec, FPredictionKey PredictionKey) private pure virtual
References NetMulticast_InvokeGameplayCueExecuted_FromSpec().
Referenced by NetMulticast_InvokeGameplayCueExecuted_FromSpec().
NetMulticast_InvokeGameplayCueExecuted_WithParams()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCueExecuted_WithParams (const FGameplayTag GameplayCueTag, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private pure virtual
References NetMulticast_InvokeGameplayCueExecuted_WithParams().
Referenced by NetMulticast_InvokeGameplayCueExecuted_WithParams().
NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private pure virtual
References NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams().
Referenced by NetMulticast_InvokeGameplayCuesAddedAndWhileActive_WithParams(), and UAbilitySystemComponent::UFUNCTION().
NetMulticast_InvokeGameplayCuesExecuted()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesExecuted (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayEffectContextHandle EffectContext) private pure virtual
References NetMulticast_InvokeGameplayCuesExecuted().
Referenced by NetMulticast_InvokeGameplayCuesExecuted(), and UAbilitySystemComponent::UFUNCTION().
NetMulticast_InvokeGameplayCuesExecuted_WithParams()
virtual void IAbilitySystemReplicationProxyInterface::NetMulticast_InvokeGameplayCuesExecuted_WithParams (const FGameplayTagContainer GameplayCueTags, FPredictionKey PredictionKey, FGameplayCueParameters GameplayCueParameters) private pure virtual
References NetMulticast_InvokeGameplayCuesExecuted_WithParams().
Referenced by NetMulticast_InvokeGameplayCuesExecuted_WithParams(), and UAbilitySystemComponent::UFUNCTION().
The documentation for this class was generated from the following file:
AbilitySystemReplicationProxyInterface.h