Unreal Engine 5.6 C++ API: TFunctionGraphTaskImpl< Signature, SubsequentsMode > Class Template Reference
TFunctionGraphTaskImpl< Signature, SubsequentsMode > Class Template Reference
Task class for lambda based tasks.
#include "TaskGraphInterfaces.h"
Public Member Functions
TFunctionGraphTaskImpl (TUniqueFunction< Signature > &&InFunction, TStatId StatId, ENamedThreads::Type InDesiredThread)
Task constructor.
FORCEINLINE void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
ENamedThreads::Type GetDesiredThread () const
Public Member Functions inherited from FCustomStatIDGraphTaskBase
FCustomStatIDGraphTaskBase (const TStatId &StatId)
Constructor.
FORCEINLINE TStatId GetStatId () const
Gets stat id for this task.
Static Public Member Functions
static ESubsequentsMode::Type GetSubsequentsMode ()
Static Private Member Functions
static FORCEINLINE void DoTaskImpl (TUniqueFunction< void()> &Function, ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
static FORCEINLINE void DoTaskImpl (TUniqueFunction< void(const FGraphEventRef &)> &Function, ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
static FORCEINLINE void DoTaskImpl (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> &Function, ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
Private Attributes
const ENamedThreads::Type DesiredThread
Thread to run the function on.
TUniqueFunction< Signature > Function
Function to run.
Detailed Description
template<typename Signature, ESubsequentsMode::Type SubsequentsMode>
class TFunctionGraphTaskImpl< Signature, SubsequentsMode >
Task class for lambda based tasks.
Definition at line 1071 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
TFunctionGraphTaskImpl()
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> TFunctionGraphTaskImpl< Signature, SubsequentsMode >::TFunctionGraphTaskImpl (TUniqueFunction< Signature > && InFunction, TStatId StatId, ENamedThreads::Type InDesiredThread) inline
Task constructor.
Parameters
InFunction - function to execute when the prerequisites are complete
StatId The stat id for this task.
InDesiredThread - Thread to run on
Definition at line 1086 of file TaskGraphInterfaces.h.
References FCustomStatIDGraphTaskBase::FCustomStatIDGraphTaskBase(), DesiredThread, Function, and MoveTemp().
Member Function Documentation
DoTask()
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> FORCEINLINE void TFunctionGraphTaskImpl< Signature, SubsequentsMode >::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Definition at line 1102 of file TaskGraphInterfaces.h.
References DoTaskImpl(), FORCEINLINE, and Function.
DoTaskImpl() [1/3]
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> FORCEINLINE void TFunctionGraphTaskImpl< Signature, SubsequentsMode >::DoTaskImpl (TUniqueFunction< void()> & Function, ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline static private
Definition at line 1108 of file TaskGraphInterfaces.h.
References FORCEINLINE, and Function.
Referenced by DoTask().
DoTaskImpl() [2/3]
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> FORCEINLINE void TFunctionGraphTaskImpl< Signature, SubsequentsMode >::DoTaskImpl (TUniqueFunction< void(const FGraphEventRef &)> & Function, ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline static private
Definition at line 1114 of file TaskGraphInterfaces.h.
References FORCEINLINE, and Function.
DoTaskImpl() [3/3]
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> FORCEINLINE void TFunctionGraphTaskImpl< Signature, SubsequentsMode >::DoTaskImpl (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> & Function, ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline static private
Definition at line 1120 of file TaskGraphInterfaces.h.
References FORCEINLINE, and Function.
GetDesiredThread()
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> ENamedThreads::Type TFunctionGraphTaskImpl< Signature, SubsequentsMode >::GetDesiredThread () const inline
Definition at line 1092 of file TaskGraphInterfaces.h.
References DesiredThread.
GetSubsequentsMode()
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> ESubsequentsMode::Type TFunctionGraphTaskImpl< Signature, SubsequentsMode >::GetSubsequentsMode () inline static
Definition at line 1097 of file TaskGraphInterfaces.h.
Field Documentation
DesiredThread
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> const ENamedThreads::Type TFunctionGraphTaskImpl< Signature, SubsequentsMode >::DesiredThread private
Thread to run the function on.
Definition at line 1077 of file TaskGraphInterfaces.h.
Referenced by TFunctionGraphTaskImpl(), and GetDesiredThread().
Function
template<typename Signature, ESubsequentsMode::Type SubsequentsMode> TUniqueFunction<Signature> TFunctionGraphTaskImpl< Signature, SubsequentsMode >::Function private
Function to run.
Definition at line 1075 of file TaskGraphInterfaces.h.
Referenced by TFunctionGraphTaskImpl(), DoTask(), DoTaskImpl(), DoTaskImpl(), and DoTaskImpl().
The documentation for this class was generated from the following file:
TaskGraphInterfaces.h