Unreal Engine 5.6 C++ API: UObjectBase Class Reference
UObjectBase Class Reference
Low level implementation of UObject, should not be used directly in game code.
#include "UObjectBase.h"
Public Member Functions
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Static Public Member Functions
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Protected Member Functions
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Attributes
const TCHAR * Name
Private Member Functions
void AddObject (FName Name, EInternalObjectFlags InSetInternalFlags, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Add a newly created object to the name hash tables and the object array.
FORCEINLINE int32 GetFlagsInternal () const
bool IsValidLowLevelForDestruction () const
Checks to see if the object appears to be valid when being destroyed.
void SetClass (UClass *NewClass)
This is used by the reinstancer to re-class and re-archetype the current instances of a class before recompiling.
Private Attributes
ObjectPtr_Private::TNonAccessTrackedObjectPtr< UClass > ClassPrivate
Class the object belongs to.
int32 InternalIndex
Index into GObjectArray...very private.
FName NamePrivate
Name of this object.
EObjectFlags ObjectFlags
Flags used to track and report various object states.
ObjectPtr_Private::TNonAccessTrackedObjectPtr< UObject > OuterPrivate
Object this object resides in.
Friends
void AddToClassMap (class FUObjectHashTables &ThreadHash, UObjectBase *Object)
class FBlueprintCompileReinstancer
class FContextObjectManager
struct FInternalUObjectBaseUtilityIsValidFlagsChecker
class FUObjectAllocator
class FUObjectArray
class FVerseObjectClassReplacer
void InitializePrivateStaticClass (class UClass *(*TClass_StaticClassFn)(), class UClass *TClass_Super_StaticClass, class UClass *TClass_PrivateStaticClass, class UClass *TClass_WithinClass_StaticClass, const TCHAR *PackageName, const TCHAR *Name)
void RemoveFromClassMap (class FUObjectHashTables &ThreadHash, UObjectBase *Object)
UObject * StaticAllocateObject (const UClass *Class, UObject *InOuter, FName Name, EObjectFlags SetFlags, EInternalObjectFlags InternalSetFlags=EInternalObjectFlags::None, bool bCanReuseSubobjects=false, bool *bOutReusedSubobject=nullptr, UPackage *ExternalPackage=nullptr, int32 SerialNumber=0, FRemoteObjectId RemoteId=FRemoteObjectId(), class FGCReconstructionGuard *GCGuard=nullptr)
Create a new instance of an object or replace an existing object.
struct UE::CoreUObject::Private::FObjectHandleUtils
class UObjectBaseUtility
void UObjectForceRegistration (UObjectBase *Object, bool bCheckForModuleRelease=true)
Force a pending registrant to register now instead of in the natural order.
struct Z_Construct_UClass_UObject_Statics
Detailed Description
Low level implementation of UObject, should not be used directly in game code.
Definition at line 46 of file UObjectBase.h.
Constructor & Destructor Documentation
UObjectBase() [1/3]
UObjectBase::UObjectBase () inline protected
Definition at line 77 of file UObjectBase.h.
References ClassPrivate, NamePrivate, NoInit, and OuterPrivate.
Referenced by UObjectBaseUtility::UObjectBaseUtility(), AddToClassMap, PrefetchClass(), PrefetchOuter(), RemoveFromClassMap, and UObjectForceRegistration.
UObjectBase() [2/3]
UObjectBase::UObjectBase (EObjectFlags InFlags) protected
Constructor used for bootstrapping.
Parameters
InFlags RF_Flags to assign
UObjectBase() [3/3]
UObjectBase::UObjectBase (UClass * InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject * InOuter, FName InName, int32 InInternalIndex = -1, int32 InSerialNumber = 0, FRemoteObjectId InRemoteId = FRemoteObjectId())
Constructor used by StaticAllocateObject.
Parameters
InClass non NULL, this gives the class of the new object, if known at this time
InFlags RF_Flags to assign
InInternalFlags EInternalObjectFlags to assign
InOuter outer for this object
InName name of the new object
InInternalIndex internal index to use (if already allocated), negative value means allocate a new index
InSerialNumber serial number to re-use (if already allocated)
References InName, and InOuter.
~UObjectBase()
virtual UObjectBase::~UObjectBase () virtual
Final destructor, removes the object from the object array, and indirectly, from any annotations.
Member Function Documentation
AddObject()
void UObjectBase::AddObject (FName Name, EInternalObjectFlags InSetInternalFlags, int32 InInternalIndex = -1, int32 InSerialNumber = 0, FRemoteObjectId InRemoteId = FRemoteObjectId()) private
Add a newly created object to the name hash tables and the object array.
Parameters
Name name to assign to this uobject
InSetInternalFlags Internal object flags to be set on the object once it's been added to the array
InInternalIndex already allocated internal index to use, negative value means allocate a new index
InSerialNumber already allocated serial number to re-use
References Name.
AddRef()
void UObjectBase::AddRef () const
Increments ref-count on the object.
Should always be paired with RAII (i.e. TStrongObjectPtr).
AtomicallyClearFlags()
FORCENOINLINE void UObjectBase::AtomicallyClearFlags (EObjectFlags FlagsToClear) inline
Atomically clears the specified flags.
Definition at line 298 of file UObjectBase.h.
References FORCENOINLINE, GetFlagsInternal(), and ObjectFlags.
Referenced by UObjectBaseUtility::ClearFlags(), and UObjectBaseUtility::ClearGarbage().
AtomicallySetFlags()
FORCENOINLINE void UObjectBase::AtomicallySetFlags (EObjectFlags FlagsToAdd) inline
Atomically adds the specified flags.
Definition at line 265 of file UObjectBase.h.
References FORCENOINLINE, GetFlagsInternal(), and ObjectFlags.
Referenced by UObjectBaseUtility::MarkAsGarbage(), and UObjectBaseUtility::SetFlags().
DeferredRegister()
virtual void UObjectBase::DeferredRegister (UClass * UClassStaticClass, const TCHAR * PackageName, const TCHAR * Name) protected virtual
Convert a boot-strap registered class into a real one, add to uobject array, etc.
Parameters
UClassStaticClass Now that it is known, fill in UClass::StaticClass() as the class
Reimplemented in UClass.
References DeferredRegister(), Name, and PackageName.
Referenced by DeferredRegister().
GetClass()
FORCEINLINE UClass * UObjectBase::GetClass () const inline
Returns the UClass that defines the fields of this object.
Definition at line 190 of file UObjectBase.h.
References ClassPrivate, and FORCEINLINE.
Referenced by UClass::AddDefaultSubobject(), UE::MovieScene::FObjectPropertyTraits::CanAssignValue(), IAnimationDataController::CheckOuterClass(), UProperty::ContainerUObjectPtrToValuePtrInternal(), ExactCast(), BlueprintNodeHelpers::GetNodeName(), UObject::Implements(), UObjectBaseUtility::IsA(), UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects(), FComponentEditorUtils::PropagateDefaultValueChange(), FSequencerFilterBase< InFilterType >::SupportsDaySequence(), FSequencerFilterBase< InFilterType >::SupportsLevelSequence(), and FSequencerFilterBase< InFilterType >::SupportsUMGSequence().
GetExternalPackage()
UPackage * UObjectBase::GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
GetExternalPackageInternal()
UPackage * UObjectBase::GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects().
GetFlags()
FORCEINLINE EObjectFlags UObjectBase::GetFlags () const inline
Retrieve the object flags directly.
Returns
Flags for this object
Definition at line 255 of file UObjectBase.h.
References checkfSlow, Flags, FORCEINLINE, GetFlagsInternal(), GetFName(), RF_AllFlags, TEXT, and ToString().
Referenced by UObjectBaseUtility::ClearFlags(), UObjectBaseUtility::GetMaskedFlags(), UObjectBaseUtility::HasAllFlags(), UObjectBaseUtility::HasAnyFlags(), UObjectBaseUtility::SetFlags(), FTransaction::FObjectRecord::FSerializedObject::SetObject(), and UE::Transaction::FDiffableObject::SetObject().
GetFlagsInternal()
FORCEINLINE int32 UObjectBase::GetFlagsInternal () const inline private
Definition at line 330 of file UObjectBase.h.
References FORCEINLINE, and ObjectFlags.
Referenced by AtomicallyClearFlags(), AtomicallySetFlags(), and GetFlags().
GetFName()
FORCEINLINE FName UObjectBase::GetFName () const inline
Returns the logical name of this object.
Definition at line 206 of file UObjectBase.h.
References FORCEINLINE, and NamePrivate.
Referenced by UObjectBaseUtility::AppendName(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TActorDescViewMap< Type >::FindByExactNativeClass(), FSoundWaveLoadingBehaviorUtil::FindOwningLoadingBehavior(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::FindThumbnailScene(), GetFlags(), UObjectBaseUtility::GetName(), UObjectBaseUtility::GetName(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FComponentEditorUtils::PropagateDefaultValueChange(), FExclusiveLoadPackageTimeTracker::PushPostLoad(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::RemoveThumbnailScene(), FDisplayClusterSceneComponentRef::SetSceneComponent(), UE_DEPRECATED(), UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateAnimatedBoneAttributes(), and USTRUCT().
GetFNameForStatID()
virtual FName UObjectBase::GetFNameForStatID () const virtual
Overridable method to return a logical name for identification in stats.
Reimplemented in UAudioComponent.
GetOuter()
FORCEINLINE UObject * UObjectBase::GetOuter () const inline
Returns the UObject this object resides in.
Definition at line 196 of file UObjectBase.h.
References FORCEINLINE, ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve(), and OuterPrivate.
Referenced by UClass::AddDefaultSubobject(), UProperty::ContainerUObjectPtrToValuePtrInternal(), UProperty::ContainerVoidPtrToValuePtrInternal(), FindFieldChecked(), IMovieSceneBindingOwnerInterface::FindFromObject(), FReferenceGraphNode::GetObjectToDisplay(), UFunction::GetOuterUClassUnchecked(), UProperty::GetOwnerProperty(), UProperty::GetOwnerProperty(), UPhysicsCollisionHandler::GetWorld(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects(), and FComponentEditorUtils::PropagateDefaultValueChange().
GetUniqueID()
FORCEINLINE uint32 UObjectBase::GetUniqueID () const inline
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
Useful as a tag.
Definition at line 184 of file UObjectBase.h.
References FORCEINLINE, and InternalIndex.
IsValidLowLevel()
bool UObjectBase::IsValidLowLevel () const
Checks to see if the object appears to be valid.
Returns
true if this appears to be a valid object
Referenced by UProperty::ContainerUObjectPtrToValuePtrInternal(), and Verse::FNativeConverter::ToVValue().
IsValidLowLevelFast()
bool UObjectBase::IsValidLowLevelFast (bool bRecursive = true) const
Faster version of IsValidLowLevel.
Checks to see if the object appears to be valid by checking pointers and their alignment. Name and InternalIndex checks are less accurate than IsValidLowLevel.
Parameters
bRecursive true if the Class pointer should be checked with IsValidLowLevelFast
Returns
true if this appears to be a valid object
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetDelegateOwner().
IsValidLowLevelForDestruction()
bool UObjectBase::IsValidLowLevelForDestruction () const private
Checks to see if the object appears to be valid when being destroyed.
Returns
true if this appears to be a valid object
LowLevelRename()
void UObjectBase::LowLevelRename (FName NewName, UObject * NewOuter = NULL) protected
Just change the FName and Outer and rehash into name hash tables.
For use by higher level rename functions.
Parameters
NewName new name for this object
NewOuter new outer for this object, if NULL, outer will be unchanged
MarkAsReachable()
void UObjectBase::MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
PrefetchClass()
void UObjectBase::PrefetchClass (UObject * Object) inline static
Definition at line 326 of file UObjectBase.h.
References UObjectBase(), ClassPrivate, Object, and FGenericPlatformMisc::Prefetch().
Referenced by UE::GC::FPrefetchingObjectIterator::Advance().
PrefetchOuter()
void UObjectBase::PrefetchOuter (UObject * Object) inline static
Definition at line 327 of file UObjectBase.h.
References UObjectBase(), Object, OuterPrivate, and FGenericPlatformMisc::Prefetch().
Referenced by UE::GC::FPrefetchingObjectIterator::Advance().
Register()
void UObjectBase::Register (class UClass *(* StaticClassFn)(), const TCHAR * PackageName, const TCHAR * Name) protected
Enqueue the registration for this object.
References Name, and PackageName.
RegisterDependencies()
virtual void UObjectBase::RegisterDependencies () inline protected virtual
Force any base classes to be registered first.
Reimplemented in UStruct.
Definition at line 125 of file UObjectBase.h.
ReleaseRef()
void UObjectBase::ReleaseRef () const
Release ref-count on the object.
RemoveClassPrefix()
FString UObjectBase::RemoveClassPrefix (const TCHAR * ClassName) static
Removes the class prefix from the given string.
SetClass()
void UObjectBase::SetClass (UClass * NewClass) private
This is used by the reinstancer to re-class and re-archetype the current instances of a class before recompiling.
SetExternalPackage()
void UObjectBase::SetExternalPackage (UPackage * InPackage)
Associate an external package directly to this object.
UE_DEPRECATED() [1/2]
UObjectBase::UE_DEPRECATED (5. 3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") inline protected
Set the object flags directly.
Definition at line 242 of file UObjectBase.h.
References checkfSlow, FORCEINLINE, GetFName(), ObjectFlags, RF_AllFlags, TEXT, and ToString().
UE_DEPRECATED() [2/2]
UObjectBase::UE_DEPRECATED (5. 6, "Use the new method above and specify UClass::StaticClass as the first argument") const protected
Friends And Related Symbol Documentation
AddToClassMap
void AddToClassMap (class FUObjectHashTables & ThreadHash, UObjectBase * Object) friend
References UObjectBase(), and Object.
FBlueprintCompileReinstancer
friend class FBlueprintCompileReinstancer friend
Definition at line 368 of file UObjectBase.h.
References FBlueprintCompileReinstancer.
Referenced by FBlueprintCompileReinstancer.
FContextObjectManager
friend class FContextObjectManager friend
Definition at line 370 of file UObjectBase.h.
References FContextObjectManager.
Referenced by FContextObjectManager.
FInternalUObjectBaseUtilityIsValidFlagsChecker
friend struct FInternalUObjectBaseUtilityIsValidFlagsChecker friend
Definition at line 52 of file UObjectBase.h.
References FInternalUObjectBaseUtilityIsValidFlagsChecker.
Referenced by FInternalUObjectBaseUtilityIsValidFlagsChecker.
FUObjectAllocator
friend class FUObjectAllocator friend
Definition at line 51 of file UObjectBase.h.
References FUObjectAllocator.
Referenced by FUObjectAllocator.
FUObjectArray
friend class FUObjectArray friend
Definition at line 50 of file UObjectBase.h.
References FUObjectArray.
Referenced by FUObjectArray.
FVerseObjectClassReplacer
friend class FVerseObjectClassReplacer friend
Definition at line 369 of file UObjectBase.h.
References FVerseObjectClassReplacer.
Referenced by FVerseObjectClassReplacer.
InitializePrivateStaticClass
void InitializePrivateStaticClass (class UClass *(* TClass_StaticClassFn)(), class UClass * TClass_Super_StaticClass, class UClass * TClass_PrivateStaticClass, class UClass * TClass_WithinClass_StaticClass, const TCHAR * PackageName, const TCHAR * Name) friend
References Name, PackageName, TClass_PrivateStaticClass, and TClass_WithinClass_StaticClass.
RemoveFromClassMap
void RemoveFromClassMap (class FUObjectHashTables & ThreadHash, UObjectBase * Object) friend
References UObjectBase(), and Object.
StaticAllocateObject
UObject * StaticAllocateObject (const UClass * Class, UObject * InOuter, FName Name, EObjectFlags SetFlags, EInternalObjectFlags InternalSetFlags = EInternalObjectFlags::None, bool bCanReuseSubobjects = false, bool * bOutReusedSubobject = nullptr, UPackage * ExternalPackage = nullptr, int32 SerialNumber = 0, FRemoteObjectId RemoteId = FRemoteObjectId(), class FGCReconstructionGuard * GCGuard = nullptr) friend
Create a new instance of an object or replace an existing object.
If both an Outer and Name are specified, and there is an object already in memory with the same Class, Outer, and Name, the existing object will be destructed, and the new object will be created in its place.
Parameters
Class the class of the object to create
InOuter the object to create this object within (the Outer property for the new object will be set to the value specified here).
Name the name to give the new object. If no value (NAME_None) is specified, the object will be given a unique name in the form of ClassName_#.
SetFlags the ObjectFlags to assign to the new object. some flags can affect the behavior of constructing the object.
InternalSetFlags the InternalObjectFlags to assign to the new object. some flags can affect the behavior of constructing the object.
bCanReuseSubobjects if set to true, SAO will not attempt to destroy a subobject if it already exists in memory.
bOutReusedSubobject flag indicating if the object is a subobject that has already been created (in which case further initialization is not necessary).
ExternalPackage External Package assigned to the allocated object, if any
RemoteId Globally unique id for this object
GCGuard Special synchronization object that prevents GC from running when reconstructing an object on top of existing one
Returns
a pointer to a fully initialized object of the specified class.
UE::CoreUObject::Private::FObjectHandleUtils
friend struct UE::CoreUObject::Private::FObjectHandleUtils friend
Definition at line 53 of file UObjectBase.h.
References UE::CoreUObject::Private::FObjectHandleUtils.
Referenced by UE::CoreUObject::Private::FObjectHandleUtils.
UObjectBaseUtility
friend class UObjectBaseUtility friend
Definition at line 48 of file UObjectBase.h.
References UObjectBaseUtility.
Referenced by UObjectBaseUtility.
UObjectForceRegistration
void UObjectForceRegistration (UObjectBase * Object, bool bCheckForModuleRelease = true) friend
Force a pending registrant to register now instead of in the natural order.
References UObjectBase(), and Object.
Z_Construct_UClass_UObject_Statics
friend struct Z_Construct_UClass_UObject_Statics friend
Definition at line 49 of file UObjectBase.h.
References Z_Construct_UClass_UObject_Statics.
Referenced by Z_Construct_UClass_UObject_Statics.
Field Documentation
ClassPrivate
ObjectPtr_Private::TNonAccessTrackedObjectPtr<UClass> UObjectBase::ClassPrivate private
Class the object belongs to.
Definition at line 352 of file UObjectBase.h.
Referenced by UObjectBase(), GetClass(), and PrefetchClass().
InternalIndex
int32 UObjectBase::InternalIndex private
Index into GObjectArray...very private.
Definition at line 349 of file UObjectBase.h.
Referenced by UObjectBaseUtility::AddToRoot(), UObjectBaseUtility::AtomicallyClearInternalFlags(), UObjectBaseUtility::ClearGarbage(), UObjectBaseUtility::ClearInternalFlags(), UObjectBaseUtility::GetInternalFlags(), UObjectBaseUtility::GetStatID(), GetUniqueID(), UObjectBaseUtility::HasAnyInternalFlags(), UObjectBaseUtility::IsNative(), UObjectBaseUtility::IsRooted(), UObjectBaseUtility::IsUnreachable(), UObjectBaseUtility::MarkAsGarbage(), UObjectBaseUtility::RemoveFromRoot(), and UObjectBaseUtility::SetInternalFlags().
Name
const TCHAR* UObjectBase::Name protected
Definition at line 130 of file UObjectBase.h.
Referenced by AddObject(), UWorldPartitionRuntimeHash::ContainsRuntimeHash(), DeferredRegister(), UAnimDataModel::FindBoneTrackByName(), UAnimDataModel::FindMutableBoneTrackByName(), UObject::GetArchetypeFromRequiredInfo(), UAnimDataModel::GetMutableBoneTrackByName(), InitializePrivateStaticClass, and Register().
NamePrivate
FName UObjectBase::NamePrivate private
Name of this object.
Definition at line 355 of file UObjectBase.h.
Referenced by UObjectBase(), and GetFName().
ObjectFlags
EObjectFlags UObjectBase::ObjectFlags private
Flags used to track and report various object states.
This needs to be 8 byte aligned on 32-bit platforms to reduce memory waste
Definition at line 346 of file UObjectBase.h.
Referenced by AtomicallyClearFlags(), AtomicallySetFlags(), UObject::GetArchetypeFromRequiredInfo(), GetFlagsInternal(), and UE_DEPRECATED().
OuterPrivate
ObjectPtr_Private::TNonAccessTrackedObjectPtr<UObject> UObjectBase::OuterPrivate private
Object this object resides in.
Definition at line 366 of file UObjectBase.h.
Referenced by UObjectBase(), GetOuter(), and PrefetchOuter().
The documentation for this class was generated from the following file:
UObjectBase.h