Unreal Engine 5.6 C++ API: TRangeBound< ElementType > Class Template Reference
TRangeBound< ElementType > Class Template Reference
Template for range bounds.
#include "RangeBound.h"
Public Types
typedef TCallTraits< ElementType >::ParamType ElementValueOrConstRef
Public Member Functions
TRangeBound ()
Default constructor.
TRangeBound (ElementValueOrConstRef InValue)
Creates a closed bound that includes the specified value.
FORCEINLINE_DEBUGGABLE ElementValueOrConstRef GetValue () const
Gets the bound's value.
FORCEINLINE_DEBUGGABLE bool IsClosed () const
Checks whether the bound is closed.
FORCEINLINE_DEBUGGABLE bool IsExclusive () const
Checks whether the bound is exclusive.
FORCEINLINE_DEBUGGABLE bool IsInclusive () const
Checks whether the bound is inclusive.
FORCEINLINE_DEBUGGABLE bool IsOpen () const
Checks whether the bound is open.
bool operator!= (const TRangeBound &Other) const
Compares this range with the specified bound for inequality.
bool operator== (const TRangeBound &Other) const
Compares this bound with the specified bound for equality.
FORCEINLINE_DEBUGGABLE void SetValue (ElementValueOrConstRef NewValue)
Sets the bound's value, maintining the inclusivity of the bound.
Static Public Member Functions
static FORCEINLINE TRangeBound Exclusive (ElementValueOrConstRef Value)
Returns a closed bound that excludes the specified value.
static FORCEINLINE TRangeBound FlipInclusion (const TRangeBound &Bound)
Returns the given bound with its inclusion flipped between inclusive and exclusive.
static FORCEINLINE TRangeBound Inclusive (ElementValueOrConstRef Value)
Returns a closed bound that includes the specified value.
static FORCEINLINE const TRangeBound & MaxLower (const TRangeBound &A, const TRangeBound &B)
Returns the greater of two lower bounds.
static FORCEINLINE const TRangeBound & MaxUpper (const TRangeBound &A, const TRangeBound &B)
Returns the greater of two upper bounds.
static FORCEINLINE const TRangeBound & MinLower (const TRangeBound &A, const TRangeBound &B)
Returns the lesser of two lower bounds.
static FORCEINLINE const TRangeBound & MinUpper (const TRangeBound &A, const TRangeBound &B)
Returns the lesser of two upper bounds.
static FORCEINLINE TRangeBound Open ()
Returns an open bound.
Private Attributes
TEnumAsByte< ERangeBoundTypes::Type > Type
Holds the type of the bound.
ElementType Value
Holds the bound's value.
Friends
uint32 GetTypeHash (const TRangeBound &Bound)
Gets the hash for the specified bound.
class FArchive & operator<< (class FArchive &Ar, TRangeBound &Bound)
Serializes the given bound from or into the specified archive.
Detailed Description
template<typename ElementType>
class TRangeBound< ElementType >
Template for range bounds.
Definition at line 35 of file RangeBound.h.
Member Typedef Documentation
ElementValueOrConstRef
template<typename ElementType> typedef TCallTraits<ElementType>::ParamType TRangeBound< ElementType >::ElementValueOrConstRef
Definition at line 40 of file RangeBound.h.
Constructor & Destructor Documentation
TRangeBound() [1/2]
template<typename ElementType> TRangeBound< ElementType >::TRangeBound () inline nodiscard
Default constructor.
See also
Exclusive, Inclusive, Open
Definition at line 47 of file RangeBound.h.
TRangeBound() [2/2]
template<typename ElementType> TRangeBound< ElementType >::TRangeBound (ElementValueOrConstRef InValue) inline nodiscard
Creates a closed bound that includes the specified value.
Parameters
InValue The bound's value.
See also
Exclusive, Inclusive, Open
Definition at line 58 of file RangeBound.h.
Member Function Documentation
Exclusive()
template<typename ElementType> FORCEINLINE TRangeBound TRangeBound< ElementType >::Exclusive (ElementValueOrConstRef Value) inline static nodiscard
Returns a closed bound that excludes the specified value.
Parameters
Value The bound value.
Returns
An exclusive closed bound.
Definition at line 193 of file RangeBound.h.
Referenced by UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DilateRange(), TRangeBound< FDateTime >::FlipInclusion(), UE::MovieScene::MakeDiscreteRange(), UE::MovieScene::MakeDiscreteRangeFromLower(), FFrameRate::operator/, and USTRUCT().
FlipInclusion()
template<typename ElementType> FORCEINLINE TRangeBound TRangeBound< ElementType >::FlipInclusion (const TRangeBound< ElementType > & Bound) inline static nodiscard
Returns the given bound with its inclusion flipped between inclusive and exclusive.
If the bound is open it is returned unchanged.
Returns
A new bound.
Definition at line 242 of file RangeBound.h.
GetValue()
template<typename ElementType> FORCEINLINE_DEBUGGABLE ElementValueOrConstRef TRangeBound< ElementType >::GetValue () const inline nodiscard
Gets the bound's value.
Use IsClosed() to verify that this bound is closed before calling this method.
Returns
Bound value.
See also
IsOpen
Definition at line 97 of file RangeBound.h.
Referenced by UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::DiscreteExclusiveUpper(), UE::MovieScene::DiscreteInclusiveLower(), TRangeSet< ElementType >::GetMaxBoundValue(), TRangeSet< ElementType >::GetMinBoundValue(), LexToString(), UE::MovieScene::MakeDiscreteRangeFromLower(), and UE::MovieScene::MakeDiscreteRangeFromUpper().
Inclusive()
template<typename ElementType> FORCEINLINE TRangeBound TRangeBound< ElementType >::Inclusive (ElementValueOrConstRef Value) inline static nodiscard
Returns a closed bound that includes the specified value.
Parameters
Value The bound value.
Returns
An inclusive closed bound.
Definition at line 209 of file RangeBound.h.
Referenced by UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DilateRange(), TRangeBound< FDateTime >::FlipInclusion(), TMovieSceneChannelData< const ValueType >::GetTotalRange(), UE::MovieScene::MakeDiscreteRange(), UE::MovieScene::MakeDiscreteRangeFromUpper(), UE::MovieScene::MakeHullRange(), UE::MovieScene::MakeHullRange(), FFrameRate::operator/, and USTRUCT().
IsClosed()
template<typename ElementType> FORCEINLINE_DEBUGGABLE bool TRangeBound< ElementType >::IsClosed () const inline nodiscard
Checks whether the bound is closed.
Returns
true if the bound is closed, false otherwise.
Definition at line 125 of file RangeBound.h.
Referenced by UE::MovieScene::ClampToDiscreteRange(), TRangeSet< ElementType >::HasMaxBound(), and TRangeSet< ElementType >::HasMinBound().
IsExclusive()
template<typename ElementType> FORCEINLINE_DEBUGGABLE bool TRangeBound< ElementType >::IsExclusive () const inline nodiscard
Checks whether the bound is exclusive.
Returns
true if the bound is exclusive, false otherwise.
Definition at line 135 of file RangeBound.h.
Referenced by UE::MovieScene::DiscreteInclusiveLower(), TRangeBound< FDateTime >::FlipInclusion(), and UE::MovieScene::MakeDiscreteRangeFromLower().
IsInclusive()
template<typename ElementType> FORCEINLINE_DEBUGGABLE bool TRangeBound< ElementType >::IsInclusive () const inline nodiscard
Checks whether the bound is inclusive.
Returns
true if the bound is inclusive, false otherwise.
Definition at line 145 of file RangeBound.h.
Referenced by UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertToDiscreteRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::ConvertToFrameTimeRange(), UE::MovieScene::DiscreteExclusiveUpper(), UE::MovieScene::DiscreteRangeIsEmpty(), TRangeBound< FDateTime >::FlipInclusion(), LexToString(), and UE::MovieScene::MakeDiscreteRangeFromUpper().
IsOpen()
template<typename ElementType> FORCEINLINE_DEBUGGABLE bool TRangeBound< ElementType >::IsOpen () const inline nodiscard
Checks whether the bound is open.
Returns
true if the bound is open, false otherwise.
Definition at line 155 of file RangeBound.h.
Referenced by UE::MovieScene::ConvertRange(), UE::MovieScene::ConvertRange(), UE::MovieScene::DiscreteExclusiveUpper(), UE::MovieScene::DiscreteInclusiveLower(), UE::MovieScene::DiscreteRangeIsEmpty(), LexToString(), UE::MovieScene::MakeDiscreteRangeFromLower(), and UE::MovieScene::MakeDiscreteRangeFromUpper().
MaxLower()
template<typename ElementType> FORCEINLINE const TRangeBound & TRangeBound< ElementType >::MaxLower (const TRangeBound< ElementType > & A, const TRangeBound< ElementType > & B) inline static nodiscard
Returns the greater of two lower bounds.
Parameters
A The first lower bound.
B The second lower bound.
Returns
The greater lower bound.
Definition at line 264 of file RangeBound.h.
MaxUpper()
template<typename ElementType> FORCEINLINE const TRangeBound & TRangeBound< ElementType >::MaxUpper (const TRangeBound< ElementType > & A, const TRangeBound< ElementType > & B) inline static nodiscard
Returns the greater of two upper bounds.
Parameters
A The first upper bound.
B The second upper bound.
Returns
The greater upper bound.
Definition at line 282 of file RangeBound.h.
Referenced by TRangeSet< ElementType >::Add(), and TRangeSet< ElementType >::GetMaxBound().
MinLower()
template<typename ElementType> FORCEINLINE const TRangeBound & TRangeBound< ElementType >::MinLower (const TRangeBound< ElementType > & A, const TRangeBound< ElementType > & B) inline static nodiscard
Returns the lesser of two lower bounds.
Parameters
A The first lower bound.
B The second lower bound.
Returns
The lesser lower bound.
Definition at line 300 of file RangeBound.h.
Referenced by TRangeSet< ElementType >::Add(), TRangeSet< ElementType >::GetMinBound(), and MovieSceneHelpers::SortLowerBounds().
MinUpper()
template<typename ElementType> FORCEINLINE const TRangeBound & TRangeBound< ElementType >::MinUpper (const TRangeBound< ElementType > & A, const TRangeBound< ElementType > & B) inline static nodiscard
Returns the lesser of two upper bounds.
Parameters
A The first upper bound.
B The second upper bound.
Returns
The lesser upper bound.
Definition at line 318 of file RangeBound.h.
Referenced by MovieSceneHelpers::SortUpperBounds().
Open()
template<typename ElementType> FORCEINLINE TRangeBound TRangeBound< ElementType >::Open () inline static nodiscard
Returns an open bound.
Returns
An open bound.
Definition at line 224 of file RangeBound.h.
Referenced by UE::MovieScene::DilateRange(), UE::MovieScene::MakeHullRange(), and FFrameRate::operator/.
operator!=()
template<typename ElementType> bool TRangeBound< ElementType >::operator!= (const TRangeBound< ElementType > & Other) const inline nodiscard
Compares this range with the specified bound for inequality.
Parameters
Other The bound to compare with.
Returns
true if the bounds are not equal, false otherwise.
Definition at line 82 of file RangeBound.h.
operator==()
template<typename ElementType> bool TRangeBound< ElementType >::operator== (const TRangeBound< ElementType > & Other) const inline nodiscard
Compares this bound with the specified bound for equality.
Parameters
Other The bound to compare with.
Returns
true if the bounds are equal, false otherwise.
Definition at line 71 of file RangeBound.h.
SetValue()
template<typename ElementType> FORCEINLINE_DEBUGGABLE void TRangeBound< ElementType >::SetValue (ElementValueOrConstRef NewValue) inline
Sets the bound's value, maintining the inclusivity of the bound.
Use IsClosed() to verify that this bound is closed before calling this method.
Parameters
NewValue New bound value.
See also
IsClosed
Definition at line 113 of file RangeBound.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename ElementType> uint32 GetTypeHash (const TRangeBound< ElementType > & Bound) friend
Gets the hash for the specified bound.
Parameters
Bound The bound to get the hash for.
Returns
Hash value.
Definition at line 180 of file RangeBound.h.
Referenced by TRangeBound< FDateTime >::GetTypeHash.
operator<<
template<typename ElementType> class FArchive & operator<< (class FArchive & Ar, TRangeBound< ElementType > & Bound) friend
Serializes the given bound from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Bound The bound to serialize.
Returns
The archive.
Definition at line 169 of file RangeBound.h.
Field Documentation
Type
template<typename ElementType> TEnumAsByte<ERangeBoundTypes::Type> TRangeBound< ElementType >::Type private
Holds the type of the bound.
Definition at line 332 of file RangeBound.h.
Referenced by TRangeBound< FDateTime >::GetTypeHash, and TRangeBound< FDateTime >::operator<<.
Value
template<typename ElementType> ElementType TRangeBound< ElementType >::Value private
Holds the bound's value.
Definition at line 335 of file RangeBound.h.
Referenced by TRangeBound< FDateTime >::FlipInclusion(), TRangeBound< FDateTime >::GetTypeHash, and TRangeBound< FDateTime >::operator<<.
The documentation for this class was generated from the following file:
RangeBound.h