Unreal Engine 5.6 C++ API: FMovieSceneEvaluationTreeNodeHandle Struct Reference
FMovieSceneEvaluationTreeNodeHandle Struct Reference
A handle to a node in an FMovieSceneEvaluationTree, defined in terms of an entry handle (corrsponding to FMovieSceneEvaluationTree::ChildNodes), and its child index.
#include "MovieSceneEvaluationTree.h"
Public Member Functions
FMovieSceneEvaluationTreeNodeHandle (FEvaluationTreeEntryHandle InChildrenHandle, int32 InIndex)
Construction from the node's parent's children entry handle, and this node's index within its parent's children.
int32 GetChildIndex () const
Access the index of this node amongst its siblings.
FEvaluationTreeEntryHandle GetHandle () const
Access the children handle that this node is contained within.
bool IsRoot () const
Check whether this node is the root node or not.
bool IsValid () const
Check whether this node should correspond to a node.
Static Public Member Functions
static FMovieSceneEvaluationTreeNodeHandle Invalid ()
Special handle that represents an invalid node.
static FMovieSceneEvaluationTreeNodeHandle Root ()
Special handle that represents the root node.
Private Attributes
FEvaluationTreeEntryHandle ChildrenHandle
Entry handle for the parent's children in FMovieSceneEvaluationTree::ChildNodes.
int32 Index
The index of this child within its parent's children.
Friends
bool operator!= (const FMovieSceneEvaluationTreeNodeHandle &A, const FMovieSceneEvaluationTreeNodeHandle &B)
Test two node handles for inequality.
FArchive & operator<< (FArchive &Ar, FMovieSceneEvaluationTreeNodeHandle &In)
Serialization operator.
bool operator== (const FMovieSceneEvaluationTreeNodeHandle &A, const FMovieSceneEvaluationTreeNodeHandle &B)
Test two node handles for equality.
Detailed Description
A handle to a node in an FMovieSceneEvaluationTree, defined in terms of an entry handle (corrsponding to FMovieSceneEvaluationTree::ChildNodes), and its child index.
Definition at line 211 of file MovieSceneEvaluationTree.h.
Constructor & Destructor Documentation
FMovieSceneEvaluationTreeNodeHandle()
FMovieSceneEvaluationTreeNodeHandle::FMovieSceneEvaluationTreeNodeHandle (FEvaluationTreeEntryHandle InChildrenHandle, int32 InIndex) inline
Construction from the node's parent's children entry handle, and this node's index within its parent's children.
Definition at line 214 of file MovieSceneEvaluationTree.h.
References ChildrenHandle, and Index.
Referenced by Invalid(), operator!=, operator<<, operator==, and Root().
Member Function Documentation
GetChildIndex()
int32 FMovieSceneEvaluationTreeNodeHandle::GetChildIndex () const inline
Access the index of this node amongst its siblings.
Definition at line 249 of file MovieSceneEvaluationTree.h.
References Index.
GetHandle()
FEvaluationTreeEntryHandle FMovieSceneEvaluationTreeNodeHandle::GetHandle () const inline
Access the children handle that this node is contained within.
Definition at line 243 of file MovieSceneEvaluationTree.h.
References ChildrenHandle.
Invalid()
FMovieSceneEvaluationTreeNodeHandle FMovieSceneEvaluationTreeNodeHandle::Invalid () inline static
Special handle that represents an invalid node.
Definition at line 225 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeNodeHandle(), and INDEX_NONE.
Referenced by FMovieSceneEvaluationTree::FMovieSceneEvaluationTree(), TMovieSceneEvaluationTreeDataIterator< DataType >::end, and FMovieSceneEvaluationTree::operator=().
IsRoot()
bool FMovieSceneEvaluationTreeNodeHandle::IsRoot () const inline
Check whether this node is the root node or not.
Definition at line 231 of file MovieSceneEvaluationTree.h.
References Root().
IsValid()
bool FMovieSceneEvaluationTreeNodeHandle::IsValid () const inline
Check whether this node should correspond to a node.
Does not check whether this handle is actually valid for any given tree
Definition at line 237 of file MovieSceneEvaluationTree.h.
References ChildrenHandle, and Index.
Root()
FMovieSceneEvaluationTreeNodeHandle FMovieSceneEvaluationTreeNodeHandle::Root () inline static
Special handle that represents the root node.
Definition at line 219 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeNodeHandle().
Referenced by TMovieSceneEvaluationTree< DataType >::Add(), TMovieSceneEvaluationTree< DataType >::Add(), TMovieSceneEvaluationTree< DataType >::AddSelective(), TMovieSceneEvaluationTree< DataType >::AddUnique(), and IsRoot().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FMovieSceneEvaluationTreeNodeHandle & A, const FMovieSceneEvaluationTreeNodeHandle & B) friend
Test two node handles for inequality.
Definition at line 259 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeNodeHandle(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FMovieSceneEvaluationTreeNodeHandle & In) friend
Serialization operator.
Definition at line 261 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeNodeHandle(), Ar, ChildrenHandle, and Index.
operator==
bool operator== (const FMovieSceneEvaluationTreeNodeHandle & A, const FMovieSceneEvaluationTreeNodeHandle & B) friend
Test two node handles for equality.
Definition at line 257 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeNodeHandle(), A, and B.
Field Documentation
ChildrenHandle
FEvaluationTreeEntryHandle FMovieSceneEvaluationTreeNodeHandle::ChildrenHandle private
Entry handle for the parent's children in FMovieSceneEvaluationTree::ChildNodes.
Definition at line 264 of file MovieSceneEvaluationTree.h.
Referenced by FMovieSceneEvaluationTreeNodeHandle(), GetHandle(), IsValid(), and operator<<.
Index
int32 FMovieSceneEvaluationTreeNodeHandle::Index private
The index of this child within its parent's children.
Definition at line 266 of file MovieSceneEvaluationTree.h.
Referenced by FMovieSceneEvaluationTreeNodeHandle(), GetChildIndex(), IsValid(), and operator<<.
The documentation for this struct was generated from the following file:
MovieSceneEvaluationTree.h