Unreal Engine 5.6 C++ API: FIOSPlatformMisc Struct Reference
FIOSPlatformMisc Struct Reference
iOS implementation of the misc OS functions
#include "IOSPlatformMisc.h"
Public Types
enum EIOSAuthNotificationStatus {
NotDetermined , Denied , Authorized , Provisional ,
Ephemeral , Unknown
}
enum EIOSDevice {
IOS_IPhone4 , IOS_IPhone4S , IOS_IPhone5 , IOS_IPhone5S ,
IOS_IPodTouch5 , IOS_IPodTouch6 , IOS_IPad2 , IOS_IPad3 ,
IOS_IPad4 , IOS_IPadMini , IOS_IPadMini2 , IOS_IPadMini4 ,
IOS_IPadAir , IOS_IPadAir2 , IOS_IPhone6 , IOS_IPhone6Plus ,
IOS_IPhone6S , IOS_IPhone6SPlus , IOS_IPhone7 , IOS_IPhone7Plus ,
IOS_IPhone8 , IOS_IPhone8Plus , IOS_IPhoneX , IOS_IPadPro ,
IOS_AppleTV , IOS_AppleTV4K , IOS_IPhoneSE , IOS_IPadPro_129 ,
IOS_IPadPro_97 , IOS_IPadPro_105 , IOS_IPadPro2_129 , IOS_IPad5 ,
IOS_IPhoneXS , IOS_IPhoneXSMax , IOS_IPhoneXR , IOS_IPhone11 ,
IOS_IPhone11Pro , IOS_IPhone11ProMax , IOS_IPad6 , IOS_IPadPro_11 ,
IOS_IPadPro3_129 , IOS_IPadAir3 , IOS_IPadMini5 , IOS_IPodTouch7 ,
IOS_IPad7 , IOS_IPhoneSE2 , IOS_IPadPro2_11 , IOS_IPadPro4_129 ,
IOS_NewDevice1 , IOS_NewDevice2 , IOS_NewDevice3 , IOS_NewDevice4 ,
IOS_NewDevice5 , IOS_NewDevice6 , IOS_NewDevice7 , IOS_NewDevice8 ,
IOS_RealityPro , IOS_Unknown
}
Public Member Functions
UE_DEPRECATED (4.21, "IsAllowedRemoteNotifications is deprecated. Use FIOSLocalNotificationService::CheckAllowedNotifications instead.") static bool IsAllowedRemoteNotifications()
UE_DEPRECATED (4.21, "Use GetDeviceVolume, it is now callable on all platforms.") static int GetAudioVolume()
UE_DEPRECATED (4.26, "Use GetDefaultDeviceProfileName() which uses the [IOSDeviceMappings] entries in BaseDeviceProfiles.ini and can be updated to support newly released devices.") static EIOSDevice GetIOSDeviceType()
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrientation)
Public Member Functions inherited from FApplePlatformMisc
UE_DEPRECATED (4.21, "void FPlatformMisc::GetEnvironmentVariable(Name, Result, Length) is deprecated. Use FString FPlatformMisc::GetEnvironmentVariable(Name) instead.") static void GetEnvironmentVariable(const TCHAR *VariableName
Public Member Functions inherited from FGenericPlatformMisc
UE_DEPRECATED (4.14, "GetHasedMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetHashedMacAddressString()
Retrieve the Mac address of the current adapter as a hashed string (privacy).
UE_DEPRECATED (4.14, "GetMacAddress is deprecated. It is not reliable on all platforms") static 1 TArray< uint8 > GetMacAddress()
Retrieve the Mac address of the current adapter.
UE_DEPRECATED (4.14, "GetMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetMacAddressString()
Retrieve the Mac address of the current adapter as a string.
UE_DEPRECATED (4.14, "GetMachineId is deprecated. Use GetLoginId instead.") static 1 FGuid GetMachineId()
Get (or create) the unique ID used to identify this computer.
UE_DEPRECATED (4.18, "FPaths::SetOverrideGameDir() has been superseded by FPaths::SetOverrideProjectDir().") static FORCEINLINE void SetOverrideGameDir(const FString &InOverrideDir)
UE_DEPRECATED (4.19, "FPlatformMisc::DebugBreak is deprecated. Use the UE_DEBUG_BREAK() macro instead.") FORCEINLINE static void DebugBreak()
Break into the debugger, if IsDebuggerPresent returns true, otherwise do nothing.
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static 1 void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrientation)
Change the orientation of the device.
UE_DEPRECATED (5.2, "Must supply size when prefetching a block of data") FORCEINLINE static void PrefetchBlock(const void *Ptr)
Static Public Member Functions
static bool AllowThreadHeartBeat ()
static bool AreHeadphonesPluggedIn ()
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static bool CPUHasHwAesSupport ()
static bool CPUHasHwCrcSupport ()
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
static void EnableVoiceChat (bool bEnable)
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static const TCHAR * GamePersistentDownloadDir ()
static int GetBatteryLevel ()
static float GetBrightness ()
static FString GetBuildNumber ()
static const class TMap< FString, FString > & GetConfigRuleVars ()
static FString GetCPUBrand ()
static FString GetCPUVendor ()
static const TCHAR * GetDefaultDeviceProfileName ()
static int GetDefaultStackSize ()
static FString GetDeviceId ()
Implemented using UIDevice::identifierForVendor, so all the caveats that apply to that API call apply here.
static EDeviceScreenOrientation GetDeviceOrientation ()
static float GetDeviceTemperatureLevel ()
static int32 GetDeviceVolume ()
static FString GetDiscardableCacheDir ()
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
static FORCEINLINE constexpr int32 GetMaxPathLength ()
static int32 GetMaxRefreshRate ()
static ENetworkConnectionType GetNetworkConnectionType ()
static EIOSAuthNotificationStatus GetNotificationAuthorizationStatus ()
static FString GetOSVersion ()
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
static FString GetPendingActivationProtocol ()
static class IPlatformChunkInstall * GetPlatformChunkInstall ()
static const TCHAR * GetPlatformFeaturesModuleName ()
static FString GetProjectVersion ()
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
static FString GetUniqueAdvertisingId ()
static void GetValidTargetPlatforms (class TArray< class FString > &TargetPlatformNames)
static FORCENOINLINE CA_NO_RETURN void GPUAssert ()
static void HandleLowMemoryWarning ()
static bool HasActiveWiFiConnection ()
static bool HasMemoryWarningHandler ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
static bool HasRecordPermission ()
static bool HasSeparateChannelForDebugOutput ()
static int32 IOSVersionCompare (uint8 Major, uint8 Minor, uint8 Revision)
static bool IsBackgroundAppRefreshAvailable ()
static bool IsConsoleOpen ()
static bool IsEntitlementEnabled (const char *EntitlementToCheck)
static bool IsInLowPowerMode ()
static bool IsPackagedForDistribution ()
static bool IsRegisteredForRemoteNotifications ()
static bool IsRunningOnBattery ()
static bool IsUpdateAvailable ()
static bool IsVoiceChatEnabled ()
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
static FORCENOINLINE CA_NO_RETURN void MetalAssert ()
static void OpenAppCustomSettings ()
Open the app's custom settings in the Settings App.
static void OpenAppNotificationSettings ()
Open the Settings app at the Notification page for this app.
static void PlatformHandleSplashScreen (bool ShowSplashScreen=false)
static void PlatformInit ()
static void PlatformPreInit ()
static void PrepareMobileHaptics (EMobileHapticsType Type)
static void RegisterForRemoteNotifications ()
static void ReleaseMobileHaptics ()
static bool RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
static void RequestStoreReview ()
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
static void SetBrightness (float Brightness)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
static void SetGracefulTerminationHandler ()
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
static bool SupportsBrightness ()
static bool SupportsDeviceCheckToken ()
static bool SupportsForceTouchInput ()
static void TriggerMobileHaptics ()
static void UnregisterForRemoteNotifications ()
Static Public Member Functions inherited from FApplePlatformMisc
static void BeginNamedEvent (const struct FColor &Color, const ANSICHAR *Text)
static void BeginNamedEvent (const struct FColor &Color, const TCHAR *Text)
Override to add Apple features when AppleProfiling is on, otherwise use version on FGenericPlatformMisc.
static void * CreateAutoreleasePool ()
static void CreateGuid (struct FGuid &Result)
static void EndNamedEvent ()
static FString GetDefaultLanguage ()
static FString GetDefaultLocale ()
static FString GetEnvironmentVariable (const TCHAR *VariableName)
static FString GetLocalCurrencyCode ()
static FString GetLocalCurrencySymbol ()
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
static TArray< uint8 > GetSystemFontBytes ()
static bool IsDebuggerPresent ()
static bool IsOSAtLeastVersion (const uint32 MacOSVersion[3], const uint32 IOSVersion[3], const uint32 TVOSVersion[3])
static void LocalPrint (const TCHAR *Message)
static FORCEINLINE void MemoryBarrier ()
static int32 NumberOfCores ()
static void PlatformInit ()
static void ReleaseAutoreleasePool (void *Pool)
static bool SupportsMultithreadedFileHandles ()
Static Public Member Functions inherited from FGenericPlatformMisc
static void AddAdditionalRootDirectory (const FString &RootDir)
add an additional root directory
static FDelegateHandle AddNetworkListener (FOnNetworkConnectionChangedDelegate &&InNewDelegate)
static bool AllowAudioThread ()
Checks if platform wants to allow an audio thread on current device (note: does not imply it will, only if okay given other criteria met)
static bool AllowLocalCaching ()
static bool AllowThreadHeartBeat ()
Checks if platform wants to allow the thread heartbeat hang detection.
static void BeginEnterBackgroundEvent (const TCHAR *Text)
Profiler enter background events.
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const ANSICHAR *Text)
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const TCHAR *Text)
static FORCEINLINE void BeginNamedEventFrame ()
static void CacheLaunchDir ()
Function to store the current working directory for use with LaunchDir()
static bool CheckPersistentDownloadStorageSpaceAvailable (uint64 BytesRequired, bool bAttemptToUseUI)
Ensure that there enough space in the persistent download dir.
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static FString CloudDir ()
Return the CloudDir.
static bool CommandLineCommands ()
Handles Game Explorer, Firewall and FirstInstall commands, typically from the installer.
static void CreateGuid (struct FGuid &Result)
Create a new globally unique identifier.
static FORCEINLINE void CustomNamedStat (const ANSICHAR *Text, float Value, const ANSICHAR *Graph, const ANSICHAR *Unit)
static FORCEINLINE void CustomNamedStat (const TCHAR *Text, float Value, const TCHAR *Graph, const TCHAR *Unit)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
Deletes the given section and its contained values in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
Deletes value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DesktopTouchScreen ()
static void DisableScreenTimeout ()
static void EnableScreenTimeout ()
static void EndEnterBackgroundEvent ()
static FORCEINLINE void EndNamedEvent ()
static const TCHAR * EngineDir ()
Get the engine directory.
static void EnsureNetworkIfNecessary ()
static bool Exec (class UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Out)
Platform-specific Exec function.
static FORCEINLINE bool Expand16BitIndicesTo32BitOnLoad ()
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static bool FullscreenSameAsWindowedFullscreen ()
static const TCHAR * GamePersistentDownloadDir ()
Return the GamePersistentDownloadDir.
static const TCHAR * GameTemporaryDownloadDir ()
Return the temporary directory.
static const TCHAR * GeneratedConfigDir ()
static TArray< FString > GetAdditionalRootDirectories ()
get additional directories which can be considered as root directories
static EDeviceScreenOrientation GetAllowedDeviceOrientation ()
Returns the allowed orientation of the device.
static FORCEINLINE int GetBatteryLevel ()
Gets the current battery level.
static bool GetBlockingIOStats (FProcessIOStats &OutStats, EInputOutputFlags Flags=EInputOutputFlags::All)
Gets Blocking Input/Output stats covering the lifetime of the process.
static FORCEINLINE float GetBrightness ()
static FORCEINLINE int32 GetChunkIDFromPakchunkIndex (int32 PakchunkIndex)
static const FString * GetConfigRulesVariable (const FString &Key)
static const class TMap< FString, FString > & GetConfigRuleVars ()
static bool GetContextSwitchStats (FContextSwitchStats &OutStats, EContextSwitchFlags Flags=EContextSwitchFlags::All)
Gets Context Switch stats covering the lifetime of the process.
static EConvertibleLaptopMode GetConvertibleLaptopMode ()
Gets the current mode of convertible laptops, i.e.
static FString GetCPUBrand ()
Uses cpuid instruction to get the CPU brand string.
static FString GetCPUChipset ()
Returns the CPU chipset if known.
static uint32 GetCPUInfo ()
On x86(-64) platforms, uses cpuid instruction to get the CPU signature.
static FString GetCPUVendor ()
Uses cpuid instruction to get the vendor string.
static ECrashHandlingType GetCrashHandlingType ()
Gets the current crash handling type.
static const TCHAR * GetDefaultDeviceProfileName ()
Gets the default profile name.
static FString GetDefaultLanguage ()
Get the default language (for localization) used by this platform.
static FString GetDefaultLocale ()
Get the default locale (for internationalization) used by this platform.
static const TCHAR * GetDefaultPathSeparator ()
static FString GetDeviceId ()
Returns a unique string for device identification.
static FString GetDeviceMakeAndModel ()
static EDeviceScreenOrientation GetDeviceOrientation ()
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
static FString GetDeviceTag ()
Get Device Tag of the device running the session.
static float GetDeviceTemperatureLevel ()
Returns the current device temperature level.
static int32 GetDeviceVolume ()
Returns the device volume if the device is capable of returning that information.
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
Retrieves information about the total number of bytes and number of free bytes for the specified disk path.
static bool GetEngineAndProjectAbsoluteDirsFromExecutable (FString &OutProjectDir, FString &OutEngineDir)
Return the engine and project directory based from the executable.
static const TCHAR * GetEngineMode ()
Get a string description of the mode the engine was running in.
static FString GetEnvironmentVariable (const TCHAR *VariableName)
Retrieve a environment variable from the system.
static FString GetEpicAccountId ()
Get the Epic account ID for the user who last used the Launcher.
static FText GetFileManagerName ()
static struct FGPUDriverInfo GetGPUDriverInfo (const FString &DeviceDescription)
static FString GetHostArchitecture ()
static FORCEINLINE uint32 GetLastError ()
static FString GetLocalCurrencyCode ()
Returns the currency code associated with the device's locale.
static FString GetLocalCurrencySymbol ()
Returns the currency symbol associated with the device's locale.
static FString GetLoginId ()
Returns a unique string associated with the login account of the current machine.
static FORCEINLINE int32 GetMaxPathLength ()
Returns the maximum length of a path.
static int32 GetMaxRefreshRate ()
retrieves the current maximum refresh rate supported by the platform
static int32 GetMaxSupportedRefreshRate ()
retrieves the maximum refresh rate supported by the platform
static int32 GetMaxSyncInterval ()
Returns the platform's maximum allowed value for rhi.SyncInterval.
static int GetMobilePropagateAlphaSetting ()
static ENetworkConnectionStatus GetNetworkConnectionStatus ()
Returns the current status for the network connection.
static ENetworkConnectionType GetNetworkConnectionType ()
Returns whether WiFi connection is currently active.
static FORCEINLINE void GetNetworkFileCustomData (TMap< FString, FString > &OutCustomPlatformData)
Returns any platform-specific key-value data that needs to be sent to the network file server.
static const TCHAR * GetNullRHIShaderFormat ()
Determines the shader format for the platform.
static FString GetOperatingSystemId ()
Gets a globally unique ID the represents a particular operating system install.
static FString GetOSVersion ()
Gets a string representing the numeric OS version (as opposed to a translated OS version that GetOSVersions returns).
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
Gets the OS Version and OS Subversion.
static bool GetPageFaultStats (FPageFaultStats &OutStats, EPageFaultFlags Flags=EPageFaultFlags::All)
Gets Page Fault stats covering the lifetime of the process.
static int32 GetPakchunkIndexFromPakFile (FStringView InFilename)
static FStringView GetPakFilenamePrefix ()
static const TCHAR * GetPathVarDelimiter ()
return the delimiter between paths in the PATH environment variable.
static FString GetPendingActivationProtocol ()
Returns activation protocol that's waiting to be broadcast.
static IPlatformChunkInstall * GetPlatformChunkInstall ()
Returns the platform specific chunk based install interface.
static IPlatformCompression * GetPlatformCompression ()
Returns the platform specific compression interface.
static const TCHAR * GetPlatformFeaturesModuleName ()
Return the name of the platform features module.
static IPlatformHostCommunication & GetPlatformHostCommunication ()
Returns the platform specific interface for communication with processes running on the host pc.
static bool GetPlatformScreenWarnings (TArray< FText > &PlatformScreenWarnings)
Returns any platform specific warning messages we want printed on screen.
static struct FAsyncIOSystemBase * GetPlatformSpecificAsyncIOSystem ()
Return the platform specific async IO system, or nullptr if the standard one should be used.
static FPlatformUserId GetPlatformUserForUserIndex (int32 LocalUserIndex)
static TArray< FString > GetPreferredLanguages ()
Returns an array of the user's preferred languages in order of preference.
static FString GetPrimaryGPUBrand ()
static EProcessDiagnosticFlags GetProcessDiagnostics ()
Returns non-zero if a performance-sensitive diagnostic, like a memory sanitizer, is detected for this process.
static const FProcessorGroupDesc & GetProcessorGroupDesc ()
static bool GetSHA256Signature (const void *Data, uint32 ByteSize, FSHA256Signature &OutSignature)
Generates the SHA256 signature of the given data.
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
Get the value for the given section and key from the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
Returns the last system error code in string form.
static TArray< uint8 > GetSystemFontBytes ()
static FString GetTimeZoneId ()
Get the timezone identifier for this platform, or an empty string if the default timezone calculation will work.
static const TCHAR * GetUBTPlatform ()
static const TCHAR * GetUBTTarget ()
static const TCHAR * GetUBTTargetName ()
static FString GetUniqueAdvertisingId ()
Returns a unique string for advertising identification.
static int32 GetUserIndexForPlatformUser (FPlatformUserId PlatformUser)
static bool GetUseVirtualJoysticks ()
Returns whether the platform wants to use a touch screen for virtual joysticks.
static void GetValidTargetPlatforms (TArray< FString > &TargetPlatformNames)
Return an ordered list of target platforms this runtime can support (ie Android_DXT, Android would mean that it prefers Android_DXT, but can use Android as well)
static const float GetVirtualKeyboardInputHeight ()
static bool GetVolumeButtonsHandledBySystem ()
static bool HasActiveWiFiConnection ()
Returns whether WiFi connection is currently active.
static bool HasMemoryWarningHandler ()
Determines if a warning handler has been set.
static bool HasNonoptionalCPUFeatures ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
Returns whether the given platform feature is currently available (for instance, Metal is only available in IOS8 and with A7 devices)
static bool HasProjectPersistentDownloadDir ()
Return true if the PersistentDownloadDir is available.
static bool HasSeparateChannelForDebugOutput ()
Whether the platform has a separate debug channel to stdout (eg.
static bool HasVariableHardware ()
Returns whether the platform has variable hardware (configurable/upgradeable system).
static void HidePlatformStartupScreen ()
static FORCEINLINE void InitTaggedStorage (uint32 NumTags)
Platform specific function for initializing storage of tagged memory buffers.
static FORCEINLINE bool Is64bitOperatingSystem ()
Detects whether we're running in a 64-bit operating system.
static bool IsCacheStorageAvailable ()
For platforms that support cache storage functionality, setting a directory for it when it's not available can result in errors.
static FORCEINLINE bool IsDebuggerPresent ()
Return true if a debugger is present.
static bool IsEnsureAllowed ()
Allows disabling ensure()s without rebuilding the binary, by either a commandline switch or a hotfix.
static FORCEINLINE bool IsInLowPowerMode ()
static bool IsLocalPrintThreadSafe ()
Whether LocalPrint can be called from any thread without overlapping.
static bool IsLowLevelOutputDebugStringStructured ()
Whether LowLevelOutputDebugString[f] can receive structured output as lines of JSON.
static bool IsPackagedForDistribution ()
static bool IsPGIActive ()
Returns true if PGI (profile-guided instrumentation, needed for PGO) is currently ongoing.
static bool IsPGICapableBinary ()
Returns true if this binary has been instrumented for collection of data needed for profile-guided optimization (PGO) This value is not expected to change during the run-time.
static bool IsPGOEnabled ()
Returns true if PGO is currently enabled.
static bool IsRegisteredForRemoteNotifications ()
Returns whether or not the device has been registered to receive remote notifications.
static bool IsRemoteSession ()
Check to see if the platform is being viewed remotely.
static bool IsRunningInCloud ()
Return if the game is running on cloud server.
static bool IsRunningOnBattery ()
Returns whether the platform is running on battery power or not.
static bool IsValidAbsolutePathFormat (const FString &Path)
Checks structure of the path against platform formatting requirements.
static const TCHAR * LaunchDir ()
Get the directory the application was launched from (useful for commandline utilities)
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
Loads a text file relative to the package root on platforms that distribute apps in package formats.
static void LocalPrint (const TCHAR *Str)
Prints string to the default output.
static void LogNameEventStatsInit ()
static void LowLevelOutputDebugString (const TCHAR *Message)
Sends a message to a remote tool, and debugger consoles.
static void VARARGS LowLevelOutputDebugStringf (const TCHAR *Format,...)
static FORCENOINLINE void MemoryBarrier ()
Enforces strict memory load/store ordering across the memory barrier call.
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
Show a message box if possible, otherwise print a message and return the default.
static bool NeedsNonoptionalCPUFeaturesCheck ()
static void NormalizePath (FString &InPath)
Platform-specific normalization of path E.g.
static void NormalizePath (FStringBuilderBase &InPath)
Platform-specific normalization of path E.g.
static int32 NumberOfCores ()
return the number of hardware CPU cores
static int32 NumberOfCoresIncludingHyperthreads ()
return the number of logical CPU cores
static int32 NumberOfIOWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn to service IO, NOT based on number of cores.
static int32 NumberOfWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn, based on number of cores.
static bool OsExecute (const TCHAR *CommandType, const TCHAR *Command, const TCHAR *CommandLine=NULL)
Has the OS execute a command and path pair (such as launch a browser)
static void ParseChunkIdPakchunkIndexMapping (TArray< FString > ChunkIndexRedirects, TMap< int32, int32 > &OutMapping)
static void PlatformHandleSplashScreen (bool ShowSplashScreen=false)
Called to dismiss splash screen.
static void PlatformInit ()
static void PlatformPreInit ()
Called during appInit() after cmd line setup.
static void PlatformTearDown ()
Called during AppExit().
static FORCEINLINE void Prefetch (const void *Ptr)
static FORCEINLINE void Prefetch (const void *Ptr, int32 Offset)
static FORCEINLINE void PrefetchBlock (const void *Ptr, int32 NumBytes)
static void PrepareMobileHaptics (EMobileHapticsType Type)
For mobile devices, this will crank up a haptic engine for the specified type to be played later with TriggerMobileHaptics If this is called again before Release, it will switch to this type.
static const TCHAR * ProjectDir ()
Return the project directory.
static void PromptForRemoteDebugging (bool bIsEnsure)
static void PumpEssentialAppMessages ()
Pumps app messages only if there are essential keep-alive messages pending.
static void PumpMessagesForSlowTask ()
static void PumpMessagesOutsideMainLoop ()
static void RaiseException (uint32 ExceptionCode)
static void RegisterForRemoteNotifications ()
Requests permission to send remote notifications to the user's device.
static void ReleaseMobileHaptics ()
For mobile devices, this will shutdown the haptics, allowing system to put it to reset as needed.
static bool RemoveNetworkListener (FDelegateHandle Handle)
static bool RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
Requests application exit.
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
Requests application exit with a specified return code.
static bool RestartApplication ()
Requests application to restart.
static bool RestartApplicationWithCmdLine (const char *CmdLine)
Requests application to restart appending the passed in CmdLine to the restart.
static const TCHAR * RootDir ()
Get the application root directory.
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
Change the allowed orientation of the device.
static FORCEINLINE void SetBrightness (float bBright)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
Installs handler for the unexpected (due to error) termination of the program, including, but not limited to, crashes.
static ECrashHandlingType SetCrashHandlingType (ECrashHandlingType Type)
Sets the type of crash handling done by the engine.
static void SetEnvironmentVar (const TCHAR *VariableName, const TCHAR *Value)
Sets an environment variable to the local process's environment.
static void SetGracefulTerminationHandler ()
Set/restore the Console Interrupt (Control-C, Control-Break, Close) handler.
static void SetLastError (uint32 ErrorCode)
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
Set a handler to be called when there is a memory warning from the OS.
static void SetNetworkConnectionStatus (ENetworkConnectionStatus NewNetworkConnectionStatus)
Updates the current status for the network connection.
static void SetOverrideProjectDir (const FString &InOverrideDir)
Allows a game/program/etc to control the game directory in a special place (for instance, monolithic programs that don't have .uprojects)
static void SetShouldPromptForRemoteDebugging (bool bInShouldPrompt)
static void SetShouldPromptForRemoteDebugOnEnsure (bool bInShouldPrompt)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool SetStoredValues (const FString &InStoreId, const FString &InSectionName, const TMap< FString, FString > &InKeyValues)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static void SetUBTTargetName (const TCHAR *InTargetName)
static bool SetupSyscallFilters ()
static void SetUTF8Output ()
Sets the default output to UTF8.
static void SetVolumeButtonsHandledBySystem (bool enabled)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
Perform a mobile-style sharing of a URL.
static bool ShouldDisablePluginAtRuntime (const FString &PluginName)
Allows platform at runtime to disable unsupported plugins.
static bool ShouldDisplayTouchInterfaceOnFakingTouchEvents ()
static void ShowConsoleWindow ()
static FORCEINLINE void ShutdownTaggedStorage ()
Platform specific function for freeing storage of tagged memory buffers.
static bool StartNewPGOCollection (const FString &AbsoluteFileName)
On platforms that support run-time PGI on/off, starts a new collection with a given file name.
template<typename CharType>
static void StatNamedEvent (const CharType *Text)
Stats logging for named event.
static bool StopPGOCollectionAndCloseFile ()
On platforms that support run-time PGI on/off, stops the current collection and writes out the file (or completes its write).
static void SubmitErrorReport (const TCHAR *InErrorHist, EErrorReportMode::Type InMode)
Submits a crash report to a central server (release builds only)
static FORCEINLINE bool SupportsBackbufferSampling ()
static FORCEINLINE bool SupportsBrightness ()
static bool SupportsDeviceCheckToken ()
static bool SupportsForceTouchInput ()
static bool SupportsFullCrashDumps ()
Platform can generate a full-memory crashdump during crash handling.
static bool SupportsLocalCaching ()
static bool SupportsMessaging ()
static bool SupportsMultithreadedFileHandles ()
static bool SupportsTouchInput ()
static FORCEINLINE void TagBuffer (const char *Label, uint32 Category, const void *Buffer, size_t BufferSize)
Platform specific function for tagging a memory buffer with a label.
static void TearDown ()
Frees any memory retained by FGenericPlatformMisc.
static void TickHotfixables ()
Ticks values that can be hotfixable in the config.
static void TickStatNamedEvents ()
static void TriggerMobileHaptics ()
For mobile devices, this will kick the haptic type that was set in PrepareMobileHaptics.
static void UnregisterForRemoteNotifications ()
Requests unregistering from receiving remote notifications on the user's device.
static void UpdateHotfixableEnsureSettings ()
Updates hotfixable ensure settings from config and commandline (config takes priority).
static FORCEINLINE bool UseHDRByDefault ()
static bool UseRenderThread ()
Checks if platform wants to use a rendering thread on current device.
static const FString VersionCheckPlatformName ()
static bool WasLaunchedStreaming ()
Return true if the game is being streamed to a separate client device.
Additional Inherited Members
Data Fields inherited from FApplePlatformMisc
TCHAR * Result
TCHAR int32 ResultLength
Static Protected Member Functions inherited from FGenericPlatformMisc
static void GetConfiguredCoreLimits (int32 PlatformNumPhysicalCores, int32 PlatformNumLogicalCores, bool &bOutFullyInitialized, int32 &OutPhysicalCoreLimit, int32 &OutLogicalCoreLimit, bool &bOutSetPhysicalCountToLogicalCount)
Parse CoreLimit from CommandLine or from the SetCoreLimit value.
Static Protected Attributes inherited from FGenericPlatformMisc
static EDeviceScreenOrientation AllowedDeviceOrientation
static bool bPromptForRemoteDebugOnEnsure
Whether the user should be prompted to allow for a remote debugger to be attached on an ensure.
static bool bShouldPromptForRemoteDebugging
Whether the user should be prompted to allow for a remote debugger to be attached.
static ENetworkConnectionStatus CurrentNetworkConnectionStatus
Detailed Description
iOS implementation of the misc OS functions
Definition at line 18 of file IOSPlatformMisc.h.
Member Enumeration Documentation
EIOSAuthNotificationStatus
enum FIOSPlatformMisc::EIOSAuthNotificationStatus
Enumerator
NotDetermined
Denied
Authorized
Provisional
Ephemeral
Unknown
Definition at line 77 of file IOSPlatformMisc.h.
EIOSDevice
enum FIOSPlatformMisc::EIOSDevice
Enumerator
IOS_IPhone4
IOS_IPhone4S
IOS_IPhone5
IOS_IPhone5S
IOS_IPodTouch5
IOS_IPodTouch6
IOS_IPad2
IOS_IPad3
IOS_IPad4
IOS_IPadMini
IOS_IPadMini2
IOS_IPadMini4
IOS_IPadAir
IOS_IPadAir2
IOS_IPhone6
IOS_IPhone6Plus
IOS_IPhone6S
IOS_IPhone6SPlus
IOS_IPhone7
IOS_IPhone7Plus
IOS_IPhone8
IOS_IPhone8Plus
IOS_IPhoneX
IOS_IPadPro
IOS_AppleTV
IOS_AppleTV4K
IOS_IPhoneSE
IOS_IPadPro_129
IOS_IPadPro_97
IOS_IPadPro_105
IOS_IPadPro2_129
IOS_IPad5
IOS_IPhoneXS
IOS_IPhoneXSMax
IOS_IPhoneXR
IOS_IPhone11
IOS_IPhone11Pro
IOS_IPhone11ProMax
IOS_IPad6
IOS_IPadPro_11
IOS_IPadPro3_129
IOS_IPadAir3
IOS_IPadMini5
IOS_IPodTouch7
IOS_IPad7
IOS_IPhoneSE2
IOS_IPadPro2_11
IOS_IPadPro4_129
IOS_NewDevice1
IOS_NewDevice2
IOS_NewDevice3
IOS_NewDevice4
IOS_NewDevice5
IOS_NewDevice6
IOS_NewDevice7
IOS_NewDevice8
IOS_RealityPro
IOS_Unknown
Definition at line 127 of file IOSPlatformMisc.h.
Member Function Documentation
AllowThreadHeartBeat()
bool FIOSPlatformMisc::AllowThreadHeartBeat () inline static
Definition at line 30 of file IOSPlatformMisc.h.
AreHeadphonesPluggedIn()
bool FIOSPlatformMisc::AreHeadphonesPluggedIn () static
References AreHeadphonesPluggedIn().
Referenced by AreHeadphonesPluggedIn().
ChooseHDRDeviceAndColorGamut()
FORCEINLINE void FIOSPlatformMisc::ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat & OutputDevice, EDisplayColorGamut & ColorGamut) inline static
Definition at line 232 of file IOSPlatformMisc.h.
References FORCEINLINE, HDR_LinearEXR, and sRGB_D65.
CPUHasHwAesSupport()
bool FIOSPlatformMisc::CPUHasHwAesSupport () static
CPUHasHwCrcSupport()
bool FIOSPlatformMisc::CPUHasHwCrcSupport () static
DeleteStoredSection()
bool FIOSPlatformMisc::DeleteStoredSection (const FString & InStoreId, const FString & InSectionName) static
DeleteStoredValue()
bool FIOSPlatformMisc::DeleteStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName) static
EnableVoiceChat()
void FIOSPlatformMisc::EnableVoiceChat (bool bEnable) static
FileExistsInPlatformPackage()
bool FIOSPlatformMisc::FileExistsInPlatformPackage (const FString & RelativePath) static
GamePersistentDownloadDir()
const TCHAR * FIOSPlatformMisc::GamePersistentDownloadDir () static
GetBatteryLevel()
int FIOSPlatformMisc::GetBatteryLevel () static
References GetBatteryLevel().
Referenced by GetBatteryLevel().
GetBrightness()
float FIOSPlatformMisc::GetBrightness () static
References GetBrightness().
Referenced by GetBrightness().
GetBuildNumber()
FString FIOSPlatformMisc::GetBuildNumber () static
References GetBuildNumber().
Referenced by GetBuildNumber().
GetConfigRuleVars()
const class TMap< FString, FString > & FIOSPlatformMisc::GetConfigRuleVars () static
GetCPUBrand()
FString FIOSPlatformMisc::GetCPUBrand () static
References GetCPUBrand().
Referenced by GetCPUBrand().
GetCPUVendor()
FString FIOSPlatformMisc::GetCPUVendor () static
References GetCPUVendor().
Referenced by GetCPUVendor().
GetDefaultDeviceProfileName()
const TCHAR * FIOSPlatformMisc::GetDefaultDeviceProfileName () static
References GetDefaultDeviceProfileName().
Referenced by GetDefaultDeviceProfileName().
GetDefaultStackSize()
int FIOSPlatformMisc::GetDefaultStackSize () static
GetDeviceId()
FString FIOSPlatformMisc::GetDeviceId () static
Implemented using UIDevice::identifierForVendor, so all the caveats that apply to that API call apply here.
GetDeviceOrientation()
EDeviceScreenOrientation FIOSPlatformMisc::GetDeviceOrientation () static
References GetDeviceOrientation().
Referenced by GetDeviceOrientation().
GetDeviceTemperatureLevel()
float FIOSPlatformMisc::GetDeviceTemperatureLevel () static
References GetDeviceTemperatureLevel().
Referenced by GetDeviceTemperatureLevel().
GetDeviceVolume()
int32 FIOSPlatformMisc::GetDeviceVolume () static
References GetDeviceVolume().
Referenced by GetDeviceVolume().
GetDiscardableCacheDir()
FString FIOSPlatformMisc::GetDiscardableCacheDir () static
GetDiskTotalAndFreeSpace()
bool FIOSPlatformMisc::GetDiskTotalAndFreeSpace (const FString & InPath, uint64 & TotalNumberOfBytes, uint64 & NumberOfFreeBytes) static
GetMaxPathLength()
FORCEINLINE constexpr int32 FIOSPlatformMisc::GetMaxPathLength () inline static constexpr
Definition at line 25 of file IOSPlatformMisc.h.
References FORCEINLINE, and IOS_MAX_PATH.
GetMaxRefreshRate()
int32 FIOSPlatformMisc::GetMaxRefreshRate () static
GetNetworkConnectionType()
ENetworkConnectionType FIOSPlatformMisc::GetNetworkConnectionType () static
GetNotificationAuthorizationStatus()
EIOSAuthNotificationStatus FIOSPlatformMisc::GetNotificationAuthorizationStatus () static
GetOSVersion()
FString FIOSPlatformMisc::GetOSVersion () static
GetOSVersions()
void FIOSPlatformMisc::GetOSVersions (FString & out_OSVersionLabel, FString & out_OSSubVersionLabel) static
References GetOSVersions().
Referenced by GetOSVersions().
GetPendingActivationProtocol()
FString FIOSPlatformMisc::GetPendingActivationProtocol () static
GetPlatformChunkInstall()
class IPlatformChunkInstall * FIOSPlatformMisc::GetPlatformChunkInstall () static
GetPlatformFeaturesModuleName()
const TCHAR * FIOSPlatformMisc::GetPlatformFeaturesModuleName () static
GetProjectVersion()
FString FIOSPlatformMisc::GetProjectVersion () static
References GetProjectVersion().
Referenced by GetProjectVersion().
GetStoredValue()
bool FIOSPlatformMisc::GetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, FString & OutValue) static
GetUniqueAdvertisingId()
FString FIOSPlatformMisc::GetUniqueAdvertisingId () static
GetValidTargetPlatforms()
void FIOSPlatformMisc::GetValidTargetPlatforms (class TArray< class FString > & TargetPlatformNames) static
GPUAssert()
FORCENOINLINE CA_NO_RETURN void FIOSPlatformMisc::GPUAssert () static
References CA_NO_RETURN, and FORCENOINLINE.
HandleLowMemoryWarning()
void FIOSPlatformMisc::HandleLowMemoryWarning () static
HasActiveWiFiConnection()
bool FIOSPlatformMisc::HasActiveWiFiConnection () static
HasMemoryWarningHandler()
bool FIOSPlatformMisc::HasMemoryWarningHandler () static
HasPlatformFeature()
bool FIOSPlatformMisc::HasPlatformFeature (const TCHAR * FeatureName) static
HasRecordPermission()
bool FIOSPlatformMisc::HasRecordPermission () static
HasSeparateChannelForDebugOutput()
bool FIOSPlatformMisc::HasSeparateChannelForDebugOutput () static
IOSVersionCompare()
int32 FIOSPlatformMisc::IOSVersionCompare (uint8 Major, uint8 Minor, uint8 Revision) static
References IOSVersionCompare(), Major, and Minor.
Referenced by IOSVersionCompare().
IsBackgroundAppRefreshAvailable()
bool FIOSPlatformMisc::IsBackgroundAppRefreshAvailable () static
Returns
true if the app is able to refresh in the background
References IsBackgroundAppRefreshAvailable().
Referenced by IsBackgroundAppRefreshAvailable().
IsConsoleOpen()
bool FIOSPlatformMisc::IsConsoleOpen () static
IsEntitlementEnabled()
bool FIOSPlatformMisc::IsEntitlementEnabled (const char * EntitlementToCheck) static
IsInLowPowerMode()
bool FIOSPlatformMisc::IsInLowPowerMode () static
IsPackagedForDistribution()
bool FIOSPlatformMisc::IsPackagedForDistribution () static
IsRegisteredForRemoteNotifications()
bool FIOSPlatformMisc::IsRegisteredForRemoteNotifications () static
IsRunningOnBattery()
bool FIOSPlatformMisc::IsRunningOnBattery () static
References IsRunningOnBattery().
Referenced by IsRunningOnBattery().
IsUpdateAvailable()
bool FIOSPlatformMisc::IsUpdateAvailable () static
IsVoiceChatEnabled()
bool FIOSPlatformMisc::IsVoiceChatEnabled () static
LoadTextFileFromPlatformPackage()
FString FIOSPlatformMisc::LoadTextFileFromPlatformPackage (const FString & RelativePath) static
MessageBoxExt()
EAppReturnType::Type FIOSPlatformMisc::MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR * Text, const TCHAR * Caption) static
References Caption, and Text.
MetalAssert()
FORCENOINLINE CA_NO_RETURN void FIOSPlatformMisc::MetalAssert () static
References CA_NO_RETURN, and FORCENOINLINE.
OpenAppCustomSettings()
void FIOSPlatformMisc::OpenAppCustomSettings () static
Open the app's custom settings in the Settings App.
References OpenAppCustomSettings().
Referenced by OpenAppCustomSettings().
OpenAppNotificationSettings()
void FIOSPlatformMisc::OpenAppNotificationSettings () static
Open the Settings app at the Notification page for this app.
References OpenAppNotificationSettings().
Referenced by OpenAppNotificationSettings().
PlatformHandleSplashScreen()
void FIOSPlatformMisc::PlatformHandleSplashScreen (bool ShowSplashScreen = false) static
PlatformInit()
void FIOSPlatformMisc::PlatformInit () static
PlatformPreInit()
void FIOSPlatformMisc::PlatformPreInit () static
PrepareMobileHaptics()
void FIOSPlatformMisc::PrepareMobileHaptics (EMobileHapticsType Type) static
RegisterForRemoteNotifications()
void FIOSPlatformMisc::RegisterForRemoteNotifications () static
ReleaseMobileHaptics()
void FIOSPlatformMisc::ReleaseMobileHaptics () static
RequestDeviceCheckToken()
bool FIOSPlatformMisc::RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc) static
RequestExit()
void FIOSPlatformMisc::RequestExit (bool Force, const TCHAR * CallSite = nullptr) static
References Force.
RequestExitWithStatus()
void FIOSPlatformMisc::RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR * CallSite = nullptr) static
References Force.
RequestStoreReview()
void FIOSPlatformMisc::RequestStoreReview () static
SetAllowedDeviceOrientation()
void FIOSPlatformMisc::SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation) static
References SetAllowedDeviceOrientation().
Referenced by SetAllowedDeviceOrientation().
SetBrightness()
void FIOSPlatformMisc::SetBrightness (float Brightness) static
References SetBrightness().
Referenced by SetBrightness().
SetCrashHandler()
void FIOSPlatformMisc::SetCrashHandler (void(* CrashHandler)(const FGenericCrashContext &Context)) static
References SetCrashHandler().
Referenced by SetCrashHandler().
SetGracefulTerminationHandler()
void FIOSPlatformMisc::SetGracefulTerminationHandler () static
References SetGracefulTerminationHandler().
Referenced by SetGracefulTerminationHandler().
SetMemoryWarningHandler()
void FIOSPlatformMisc::SetMemoryWarningHandler (void(* Handler)(const FGenericMemoryWarningContext &Context)) static
SetStoredValue()
bool FIOSPlatformMisc::SetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, const FString & InValue) static
ShareURL()
void FIOSPlatformMisc::ShareURL (const FString & URL, const FText & Description, int32 LocationHintX, int32 LocationHintY) static
SupportsBrightness()
bool FIOSPlatformMisc::SupportsBrightness () inline static
Definition at line 66 of file IOSPlatformMisc.h.
References SupportsBrightness().
Referenced by SupportsBrightness().
SupportsDeviceCheckToken()
bool FIOSPlatformMisc::SupportsDeviceCheckToken () inline static
Definition at line 225 of file IOSPlatformMisc.h.
References SupportsDeviceCheckToken().
Referenced by SupportsDeviceCheckToken().
SupportsForceTouchInput()
bool FIOSPlatformMisc::SupportsForceTouchInput () static
TriggerMobileHaptics()
void FIOSPlatformMisc::TriggerMobileHaptics () static
UE_DEPRECATED() [1/4]
FIOSPlatformMisc::UE_DEPRECATED (4. 21, "IsAllowedRemoteNotifications is deprecated. Use FIOSLocalNotificationService::CheckAllowedNotifications instead.")
UE_DEPRECATED() [2/4]
FIOSPlatformMisc::UE_DEPRECATED (4. 21, "Use GetDeviceVolume, it is now callable on all platforms.")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FIOSPlatformMisc::UE_DEPRECATED (4. 26, "Use GetDefaultDeviceProfileName() which uses the entries in BaseDeviceProfiles.ini and can be updated to support newly released devices." [IOSDeviceMappings])
UE_DEPRECATED() [4/4]
FIOSPlatformMisc::UE_DEPRECATED (5. 1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.")
References UE_DEPRECATED().
UnregisterForRemoteNotifications()
void FIOSPlatformMisc::UnregisterForRemoteNotifications () static
The documentation for this struct was generated from the following file:
IOSPlatformMisc.h