Unreal Engine 5.6 C++ API: Metasound::ArrayNodeRandomGetVertexNames Namespace Reference
Metasound::ArrayNodeRandomGetVertexNames Namespace Reference
Functions
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array Enable Shared Set to enabled to share state with other Random Get (Array) nodes. Does not apply when previewing in the MetaSound editor
Trigger to reset the seed for the randomized array METASOUND_PARAM (InputRandomArray, "In Array", "Input array to randomize.") METASOUND_PARAM(InputWeights
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from METASOUND_PARAM (InputSeed, "Seed", "Seed to use for the random stream. Set to -1 to use a random seed.") METASOUND_PARAM(InputNoRepeatOrder
use PIE or game METASOUND_PARAM (InputSharedStateBehavior, "Shared State Behavior", "The behavior for how state is shared with other Random Get (Array) nodes. Only applied when Enable Shared State is true.") METASOUND_PARAM(OutputTriggerOnNext
METASOUND_PARAM (InputTriggerNextValue, "Next", "Trigger to get the next value in the randomized array.") METASOUND_PARAM(InputTriggerResetSeed
use PIE or game On Triggers when the Next input is triggered METASOUND_PARAM (OutputTriggerOnReset, "On Reset", "Triggers when the \"Reset\" input is triggered.") METASOUND_PARAM(ShuffleOutputValue
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array size (which is the maximum no-repeats behavior)") METASOUND_PARAM(InputEnableSharedState
Variables
use PIE or game On Next
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No Repeats
Reset
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array Enable Shared State
use PIE or game On Triggers when the Next input is triggered Value
Trigger to reset the seed for the randomized array Weights
Function Documentation
Get()
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array Enable Shared Set to enabled to share state with other Random Metasound::ArrayNodeRandomGetVertexNames::Get (Array)
References METASOUND_PARAM().
METASOUND_PARAM() [1/5]
Trigger to reset the seed for the randomized array Metasound::ArrayNodeRandomGetVertexNames::METASOUND_PARAM (InputRandomArray , "In Array" , "Input array to randomize.")
References METASOUND_PARAM().
METASOUND_PARAM() [2/5]
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from Metasound::ArrayNodeRandomGetVertexNames::METASOUND_PARAM (InputSeed , "Seed" , "Seed to use for the random stream. Set to -1 to use a random seed.")
References METASOUND_PARAM().
METASOUND_PARAM() [3/5]
use PIE or game Metasound::ArrayNodeRandomGetVertexNames::METASOUND_PARAM (InputSharedStateBehavior , "Shared State Behavior" , "The behavior for how state is shared with other Random Get (Array) nodes. Only applied when Enable Shared State is true.")
References METASOUND_PARAM().
METASOUND_PARAM() [4/5]
Metasound::ArrayNodeRandomGetVertexNames::METASOUND_PARAM (InputTriggerNextValue , "Next" , "Trigger to get the next value in the randomized array.")
Referenced by Get(), METASOUND_PARAM(), METASOUND_PARAM(), METASOUND_PARAM(), and METASOUND_PARAM().
METASOUND_PARAM() [5/5]
use PIE or game On Triggers when the Next input is triggered Metasound::ArrayNodeRandomGetVertexNames::METASOUND_PARAM (OutputTriggerOnReset , "On Reset" , "Triggers when the \"Reset\" input is triggered.")
References METASOUND_PARAM().
size()
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array Metasound::ArrayNodeRandomGetVertexNames::size (which is the maximum no-repeats behavior)
Variable Documentation
Next
use PIE or game On Metasound::ArrayNodeRandomGetVertexNames::Next
Definition at line 71 of file MetasoundArrayRandomNode.h.
Repeats
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No Metasound::ArrayNodeRandomGetVertexNames::Repeats
Definition at line 68 of file MetasoundArrayRandomNode.h.
Reset
Metasound::ArrayNodeRandomGetVertexNames::Reset
Definition at line 64 of file MetasoundArrayRandomNode.h.
State
Trigger to reset the seed for the randomized array Input array of weights to use for random selection Will repeat if this array is shorter than the input array to select from No The number of elements to track to avoid repeating in a row This is clamped to be within half the array size The output will end up repeating a clear pattern if set close to the array size Set to to automatically set to half the array Enable Shared Metasound::ArrayNodeRandomGetVertexNames::State
Definition at line 69 of file MetasoundArrayRandomNode.h.
Value
use PIE or game On Triggers when the Next input is triggered Metasound::ArrayNodeRandomGetVertexNames::Value
Definition at line 73 of file MetasoundArrayRandomNode.h.
Weights
Trigger to reset the seed for the randomized array Metasound::ArrayNodeRandomGetVertexNames::Weights
Definition at line 66 of file MetasoundArrayRandomNode.h.