Unreal Engine 5.6 C++ API: UE::Geometry::FVertexConnectedComponents Class Reference
UE::Geometry::FVertexConnectedComponents Class Reference
Vertex-based connected components class – can work with any mesh that has vertex IDs Also supports linking spatially-close vertices in the same component.
#include "VertexConnectedComponents.h"
Public Member Functions
FVertexConnectedComponents ()
FVertexConnectedComponents (int32 MaxVertexID)
template<typename TriangleMeshType>
void ConnectCloseVertices (const TriangleMeshType &Mesh, double CloseVertexThreshold, int32 KeepSizeThreshold=0)
template<typename TriangleMeshType>
void ConnectOverlappingComponents (const TriangleMeshType &Mesh, int32 KeepSizeThreshold=0)
template<typename TriangleMeshType>
void ConnectTriangles (const TriangleMeshType &Mesh)
template<typename TriangleType>
void ConnectTriangles (TArrayView< const TriangleType > Triangles)
void ConnectVertices (int32 VertexID0, int32 VertexID1)
bool EnumerateContiguousComponentsFromArray (const TArray< int32 > &ContiguousComponentsArray, TFunctionRef< bool(int32, TArrayView< const int32 >)> ProcessComponentFn)
Apply ProcessComponentFn() to each connected component, or until the function returns false.
template<typename TriangleType>
int32 GetComponent (const TriangleType &Triangle)
int32 GetComponent (int32 VertexID)
int32 GetComponentSize (int32 VertexID)
template<typename TriangleMeshType>
bool HasMultipleComponents (const TriangleMeshType &Mesh, int32 KeepSizeThreshold=0)
bool HasMultipleComponents (int32 MaxVID, int32 KeepSizeThreshold=0)
template<typename TriangleMeshType>
void Init (const TriangleMeshType &Mesh)
void Init (int32 MaxVertexID)
template<typename TriangleMeshType>
TMap< int32, int32 > MakeComponentMap (const TriangleMeshType &Mesh, int32 KeepSizeThreshold=0)
TMap< int32, int32 > MakeComponentMap (int32 MaxVID, int32 KeepSizeThreshold=0)
TArray< int32 > MakeContiguousComponentsArray (int32 MaxVID)
Protected Attributes
FSizedDisjointSet DisjointSet
Detailed Description
Vertex-based connected components class – can work with any mesh that has vertex IDs Also supports linking spatially-close vertices in the same component.
Functions templated on TemplateMeshType are designed to work with any mesh that implements the standard MeshAdapter functions (see MeshAdapter.h) Functions templated on TriangleType are designed to work with triangles with vertex IDs that can be array-accessed (i.e.: Tri[0], Tri[1], Tri[2])
Definition at line 156 of file VertexConnectedComponents.h.
Constructor & Destructor Documentation
FVertexConnectedComponents() [1/2]
UE::Geometry::FVertexConnectedComponents::FVertexConnectedComponents () inline
Definition at line 159 of file VertexConnectedComponents.h.
References Init.
FVertexConnectedComponents() [2/2]
UE::Geometry::FVertexConnectedComponents::FVertexConnectedComponents (int32 MaxVertexID) inline
Definition at line 164 of file VertexConnectedComponents.h.
References Init.
Member Function Documentation
ConnectCloseVertices()
template<typename TriangleMeshType> void UE::Geometry::FVertexConnectedComponents::ConnectCloseVertices (const TriangleMeshType & Mesh, double CloseVertexThreshold, int32 KeepSizeThreshold = 0) inline
Definition at line 206 of file VertexConnectedComponents.h.
References DisjointSet, UE::Geometry::DistanceSquared(), UE::Geometry::TPointHashGrid3< PointDataType, RealType >::EnumeratePointsInBall(), UE::Geometry::TPointHashGrid3< PointDataType, RealType >::InsertPointUnsafe(), and UE::Geometry::Mesh.
ConnectOverlappingComponents()
template<typename TriangleMeshType> void UE::Geometry::FVertexConnectedComponents::ConnectOverlappingComponents (const TriangleMeshType & Mesh, int32 KeepSizeThreshold = 0) inline
Definition at line 238 of file VertexConnectedComponents.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateConstIterator(), DisjointSet, UE::Geometry::TAxisAlignedBox3< double >::Empty(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), and UE::Geometry::Mesh.
ConnectTriangles() [1/2]
template<typename TriangleMeshType> void UE::Geometry::FVertexConnectedComponents::ConnectTriangles (const TriangleMeshType & Mesh) inline
Definition at line 181 of file VertexConnectedComponents.h.
References DisjointSet, UE::Geometry::Mesh, and UE::Geometry::Triangle.
ConnectTriangles() [2/2]
template<typename TriangleType> void UE::Geometry::FVertexConnectedComponents::ConnectTriangles (TArrayView< const TriangleType > Triangles) inline
Definition at line 195 of file VertexConnectedComponents.h.
References DisjointSet, and UE::Geometry::Triangle.
ConnectVertices()
void UE::Geometry::FVertexConnectedComponents::ConnectVertices (int32 VertexID0, int32 VertexID1) inline
Definition at line 440 of file VertexConnectedComponents.h.
References DisjointSet.
EnumerateContiguousComponentsFromArray()
bool UE::Geometry::FVertexConnectedComponents::EnumerateContiguousComponentsFromArray (const TArray< int32 > & ContiguousComponentsArray, TFunctionRef< bool(int32, TArrayView< const int32 >)> ProcessComponentFn) inline
Apply ProcessComponentFn() to each connected component, or until the function returns false.
Parameters
ContiguousComponentsArray Must be the array returned by MakeContiguousComponentsArray()
ProcessComponentFn Function of (ComponentID, Component Members). If the function returns false, enumeration will stop.
Returns
True if every component was processed, false if ProcessComponentFn returned false and the enumeration returned early.
Definition at line 403 of file VertexConnectedComponents.h.
References ensure, GetComponent(), GetComponentSize(), TArray< InElementType, InAllocatorType >::GetData(), and TArray< InElementType, InAllocatorType >::Num().
GetComponent() [1/2]
template<typename TriangleType> int32 UE::Geometry::FVertexConnectedComponents::GetComponent (const TriangleType & Triangle) inline
Definition at line 435 of file VertexConnectedComponents.h.
References GetComponent(), and UE::Geometry::Triangle.
GetComponent() [2/2]
int32 UE::Geometry::FVertexConnectedComponents::GetComponent (int32 VertexID) inline
Definition at line 424 of file VertexConnectedComponents.h.
References DisjointSet.
Referenced by EnumerateContiguousComponentsFromArray(), and GetComponent().
GetComponentSize()
int32 UE::Geometry::FVertexConnectedComponents::GetComponentSize (int32 VertexID) inline
Definition at line 429 of file VertexConnectedComponents.h.
References DisjointSet.
Referenced by EnumerateContiguousComponentsFromArray().
HasMultipleComponents() [1/2]
template<typename TriangleMeshType> bool UE::Geometry::FVertexConnectedComponents::HasMultipleComponents (const TriangleMeshType & Mesh, int32 KeepSizeThreshold = 0) inline
Definition at line 274 of file VertexConnectedComponents.h.
References DisjointSet, and UE::Geometry::Mesh.
HasMultipleComponents() [2/2]
bool UE::Geometry::FVertexConnectedComponents::HasMultipleComponents (int32 MaxVID, int32 KeepSizeThreshold = 0) inline
Definition at line 300 of file VertexConnectedComponents.h.
References DisjointSet.
Init() [1/2]
template<typename TriangleMeshType> void UE::Geometry::FVertexConnectedComponents::Init (const TriangleMeshType & Mesh) inline
Definition at line 175 of file VertexConnectedComponents.h.
References DisjointSet, and UE::Geometry::Mesh.
Init() [2/2]
void UE::Geometry::FVertexConnectedComponents::Init (int32 MaxVertexID) inline
Definition at line 169 of file VertexConnectedComponents.h.
References DisjointSet.
MakeComponentMap() [1/2]
template<typename TriangleMeshType> TMap< int32, int32 > UE::Geometry::FVertexConnectedComponents::MakeComponentMap (const TriangleMeshType & Mesh, int32 KeepSizeThreshold = 0) inline
Definition at line 324 of file VertexConnectedComponents.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains(), DisjointSet, and UE::Geometry::Mesh.
MakeComponentMap() [2/2]
TMap< int32, int32 > UE::Geometry::FVertexConnectedComponents::MakeComponentMap (int32 MaxVID, int32 KeepSizeThreshold = 0) inline
Definition at line 347 of file VertexConnectedComponents.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains(), and DisjointSet.
MakeContiguousComponentsArray()
TArray< int32 > UE::Geometry::FVertexConnectedComponents::MakeContiguousComponentsArray (int32 MaxVID) inline
Definition at line 367 of file VertexConnectedComponents.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), DisjointSet, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and TArray< InElementType, InAllocatorType >::SetNum().
Field Documentation
DisjointSet
FSizedDisjointSet UE::Geometry::FVertexConnectedComponents::DisjointSet protected
Definition at line 448 of file VertexConnectedComponents.h.
Referenced by ConnectCloseVertices(), ConnectOverlappingComponents(), ConnectTriangles(), ConnectTriangles(), ConnectVertices(), GetComponent(), GetComponentSize(), HasMultipleComponents(), HasMultipleComponents(), Init(), Init(), MakeComponentMap(), MakeComponentMap(), and MakeContiguousComponentsArray().
The documentation for this class was generated from the following file:
VertexConnectedComponents.h