Unreal Engine 5.6 C++ API: TAdderReserverRef< T, SizeType > Struct Template Reference
TAdderReserverRef< T, SizeType > Struct Template Reference
#include "AdderRef.h"
Public Member Functions
template<typename ContainerType UE_REQUIRES>
UE_NODEBUG TAdderReserverRef (ContainerType &InContainer UE_LIFETIMEBOUND)
UE_NODEBUG SizeType Num () const
UE_NODEBUG void Reserve (SizeType Size) const
Public Member Functions inherited from TAdderRef< T >
template<typename ContainerType UE_REQUIRES>
UE_NODEBUG TAdderRef (ContainerType &InContainer UE_LIFETIMEBOUND)
UE_NODEBUG void Add (const T &Val) const
UE_NODEBUG void Add (T &&Val) const
Additional Inherited Members
Protected Member Functions inherited from TAdderRef< T >
UE_NODEBUG TAdderRef (const UE::Core::Private::TAdderVTable< T > *InVPtr, void *InContainerPtr)
Protected Attributes inherited from TAdderRef< T >
void * ContainerPtr
const UE::Core::Private::TAdderVTable< T > * VPtr
Detailed Description
template<typename T, typename SizeType = int32>
struct TAdderReserverRef< T, SizeType >
Definition at line 146 of file AdderRef.h.
Constructor & Destructor Documentation
TAdderReserverRef()
template<typename T, typename SizeType = int32> template<typename ContainerType UE_REQUIRES> UE_NODEBUG TAdderReserverRef< T, SizeType >::TAdderReserverRef (ContainerType &InContainer UE_LIFETIMEBOUND) inline nodiscard
Definition at line 152 of file AdderRef.h.
References TAdderRef< T >::TAdderRef(), Core, InContainer, Private, UE_LIFETIMEBOUND, and UE_NODEBUG.
Member Function Documentation
Num()
template<typename T, typename SizeType = int32> UE_NODEBUG SizeType TAdderReserverRef< T, SizeType >::Num () const inline nodiscard
Definition at line 158 of file AdderRef.h.
References Num(), UE_NODEBUG, and TAdderRef< T >::VPtr.
Referenced by Num().
Reserve()
template<typename T, typename SizeType = int32> UE_NODEBUG void TAdderReserverRef< T, SizeType >::Reserve (SizeType Size) const inline
Definition at line 163 of file AdderRef.h.
References Reserve(), TSequenceHistory< HistorySize >::Size, UE_NODEBUG, and TAdderRef< T >::VPtr.
Referenced by Reserve().
The documentation for this struct was generated from the following file:
AdderRef.h