Unreal Engine 5.6 C++ API: RectLightComponent.h File Reference
RectLightComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Engine/Scene.h"
#include "Components/LocalLightComponent.h"
#include "RectLightComponent.generated.h"
Data Structures
class URectLightComponent
Functions
void CalculateRectLightBarnCorners (float SourceWidth, float SourceHeight, float BarnExtent, float BarnDepth, TStaticArray< FVector, 8 > &OutCorners)
void CalculateRectLightCullingBarnExtentAndDepth (float Size, float Length, float AngleRad, float Radius, float &OutExtent, float &OutDepth)
float GetRectLightBarnDoorMaxAngle ()
UCLASS ()
A light component which emits light from a rectangle.
Variables
editinlinenew
hidecategories =(Object, LightShafts)
meta =(BlueprintSpawnableComponent)
Function Documentation
CalculateRectLightBarnCorners()
void CalculateRectLightBarnCorners (float SourceWidth, float SourceHeight, float BarnExtent, float BarnDepth, TStaticArray< FVector, 8 > & OutCorners)
CalculateRectLightCullingBarnExtentAndDepth()
void CalculateRectLightCullingBarnExtentAndDepth (float Size, float Length, float AngleRad, float Radius, float & OutExtent, float & OutDepth)
References TSequenceHistory< HistorySize >::Size.
GetRectLightBarnDoorMaxAngle()
float GetRectLightBarnDoorMaxAngle ()
UCLASS()
UCLASS ()
A light component which emits light from a rectangle.
Variable Documentation
editinlinenew
editinlinenew
Definition at line 22 of file RectLightComponent.h.
hidecategories
hidecategories =(Object, LightShafts)
Definition at line 22 of file RectLightComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 22 of file RectLightComponent.h.
Referenced by URectLightComponent::GENERATED_UCLASS_BODY(), URectLightComponent::UPROPERTY(), URectLightComponent::UPROPERTY(), URectLightComponent::UPROPERTY(), URectLightComponent::UPROPERTY(), URectLightComponent::UPROPERTY(), and URectLightComponent::UPROPERTY().