Unreal Engine 5.6 C++ API: Metasound::FDataTransmissionCenter Class Reference
Metasound::FDataTransmissionCenter Class Reference
#include "MetasoundRouter.h"
Public Member Functions
METASOUNDFRONTEND_API TUniquePtr< IReceiver > RegisterNewReceiver (const FTransmissionAddress &InAddress, const FReceiverInitParams &InitParams)
template<typename TDataType>
TReceiverPtr< TDataType > RegisterNewReceiver (const FTransmissionAddress &InAddress, const FReceiverInitParams &InitParams)
METASOUNDFRONTEND_API TUniquePtr< ISender > RegisterNewSender (const FTransmissionAddress &InAddress, const FSenderInitParams &InitParams)
template<typename TDataType>
TSenderPtr< TDataType > RegisterNewSender (const FTransmissionAddress &InAddress, const FSenderInitParams &InitParams)
UE_DEPRECATED (5.1, "Pushing literals from the Metasound::FDataTransmissionCenter will no longer be supported in future released.") METASOUNDFRONTEND_API bool PushLiteral(FName DataTypeName
METASOUNDFRONTEND_API bool UnregisterDataChannel (const FTransmissionAddress &InAddress)
METASOUNDFRONTEND_API bool UnregisterDataChannelIfUnconnected (const FTransmissionAddress &InAddress)
Static Public Member Functions
static METASOUNDFRONTEND_API FDataTransmissionCenter & Get ()
Data Fields
FName GlobalChannelName
FName const FLiteral & InParam
Private Member Functions
FDataTransmissionCenter ()=default
Private Attributes
FAddressRouter GlobalRouter
Detailed Description
Definition at line 1087 of file MetasoundRouter.h.
Constructor & Destructor Documentation
FDataTransmissionCenter()
Metasound::FDataTransmissionCenter::FDataTransmissionCenter () private default
References FDataTransmissionCenter(), and Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES().
Referenced by FDataTransmissionCenter(), and Get().
Member Function Documentation
Get()
METASOUNDFRONTEND_API FDataTransmissionCenter & Metasound::FDataTransmissionCenter::Get () static
References FDataTransmissionCenter(), and UE_API.
Referenced by Metasound::Frontend::TBoundAnalyzerOutput< DataType >::TBoundAnalyzerOutput(), Metasound::Frontend::TBoundAnalyzerOutput< DataType >::~TBoundAnalyzerOutput(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateNewReceiver(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateNewSender(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::ResetReceiverAndCleanupChannel(), and Metasound::SendNodePrivate::TSendOperator< TDataType >::ResetSenderAndCleanupChannel().
RegisterNewReceiver() [1/2]
METASOUNDFRONTEND_API TUniquePtr< IReceiver > Metasound::FDataTransmissionCenter::RegisterNewReceiver (const FTransmissionAddress & InAddress, const FReceiverInitParams & InitParams)
References UE_API.
Referenced by RegisterNewReceiver().
RegisterNewReceiver() [2/2]
template<typename TDataType> TReceiverPtr< TDataType > Metasound::FDataTransmissionCenter::RegisterNewReceiver (const FTransmissionAddress & InAddress, const FReceiverInitParams & InitParams) inline
Definition at line 1122 of file MetasoundRouter.h.
References Metasound::Downcast(), TUniquePtr< T, Deleter >::IsValid(), MoveTemp(), and RegisterNewReceiver().
RegisterNewSender() [1/2]
METASOUNDFRONTEND_API TUniquePtr< ISender > Metasound::FDataTransmissionCenter::RegisterNewSender (const FTransmissionAddress & InAddress, const FSenderInitParams & InitParams)
References UE_API.
Referenced by Metasound::Frontend::TBoundAnalyzerOutput< DataType >::TBoundAnalyzerOutput(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateNewSender(), and RegisterNewSender().
RegisterNewSender() [2/2]
template<typename TDataType> TSenderPtr< TDataType > Metasound::FDataTransmissionCenter::RegisterNewSender (const FTransmissionAddress & InAddress, const FSenderInitParams & InitParams) inline
Definition at line 1102 of file MetasoundRouter.h.
References Metasound::Downcast(), TUniquePtr< T, Deleter >::IsValid(), MoveTemp(), and RegisterNewSender().
UE_DEPRECATED()
Metasound::FDataTransmissionCenter::UE_DEPRECATED (5. 1, "Pushing literals from the Metasound::FDataTransmissionCenter will no longer be supported in future released.")
UnregisterDataChannel()
METASOUNDFRONTEND_API bool Metasound::FDataTransmissionCenter::UnregisterDataChannel (const FTransmissionAddress & InAddress)
References UE_API.
Referenced by Metasound::Frontend::TBoundAnalyzerOutput< DataType >::~TBoundAnalyzerOutput().
UnregisterDataChannelIfUnconnected()
METASOUNDFRONTEND_API bool Metasound::FDataTransmissionCenter::UnregisterDataChannelIfUnconnected (const FTransmissionAddress & InAddress)
References UE_API.
Referenced by Metasound::SendNodePrivate::TSendOperator< TDataType >::ResetSenderAndCleanupChannel().
Field Documentation
GlobalChannelName
FName Metasound::FDataTransmissionCenter::GlobalChannelName
Definition at line 1144 of file MetasoundRouter.h.
GlobalRouter
FAddressRouter Metasound::FDataTransmissionCenter::GlobalRouter private
Definition at line 1148 of file MetasoundRouter.h.
InParam
FName const FLiteral& Metasound::FDataTransmissionCenter::InParam
Definition at line 1144 of file MetasoundRouter.h.
The documentation for this class was generated from the following file:
MetasoundRouter.h