Unreal Engine 5.6 C++ API: UE::Sequencer Namespace Reference
UE::Sequencer Namespace Reference
Namespaces
namespace ExtensionHooks
Data Structures
struct FAddKeyOperation
Temporary structure used for consistent add-key behavior for a set of display nodes Ultimately the operation will call ISequencerTrackEditor::ProcessKeyOperation for each track editor that needs to add keys.
struct FAddKeyResult
class FAddOutlinerColumn
struct FArrangedVirtualEntity
class FBindingLifetimeOverlayModel
class FBindingLifetimeTrackModel
struct FCachedKeys
struct FCastableTypeTable
class FCategoryGroupModel
Model for the outliner entry associated with all sections' channel categories of a given common name.
class FCategoryModel
Model for a single channel category inside a section.
class FChannelGroupModel
Model for the outliner entry associated with all sections' channels of a given common name.
class FChannelGroupOutlinerModel
Model for the outliner entry associated with all sections' channels of a given common name.
class FChannelGroupOverrideHelper
Utility class for building menus that add, edit, and remove channel overrides.
class FChannelModel
Model for a single channel inside a section.
struct FChannelViewKeyCachedState
Cache structure that stores all the sequencer-specific things that contribute to the cached screen-space renderered key states.
class FColorPickerOutlinerColumn
class FCommonAnimationSection
Class for animation sections.
class FCommonAnimationTrackEditor
Tools for animation tracks.
struct FCommonOutlinerNames
struct FCreateBindingParams
struct FCreateCurveEditorModelParams
struct FCreateKeyEditorParams
struct FCreateOutlinerColumnParams
Parameters for creating an outliner column widget.
struct FCreateOutlinerContextMenuWidgetParams
Parameters for building a context menu widget.
struct FCreateOutlinerViewParams
Parameters for creating an outliner item widget.
struct FCreateSectionViewWidgetParams
struct FCreateTrackLaneViewParams
Parameters for creating a track lane widget.
class FCurveEditorExtension
class FCurveEditorIntegrationExtension
Extension for managing integration between outliner items and the curve editor.
class FCurveEditorTreeItemExtensionShim
Default partial implementation of ICurveEditorTreeItemExtension.
class FDeactivateOutlinerColumn
A column for local (not serialized to the asset) muting/unmuting tracks.
class FDeactiveStateCacheExtension
class FDynamicExtensionContainer
Base class for supporting dynamic extensions that participate in dynamic casting.
struct FDynamicExtensionContainerIterator
class FEditorSharedViewModelData
class FEditorViewModel
This represents to root view-model for a sequencer-like editor.
class FEditOutlinerColumn
class FEvaluableOutlinerItemModel
class FFolderModel
class FFolderModelStorageExtension
class FGeometryExtensionShim
Basic utility implementation of the IGeometryExtension interface.
class FHierarchicalCacheExtension
class FHoveredExtensionShim
struct FIndirectOutlinerSelectionIterator
Iterator class for iterating the outliner nodes that have keys or sections selected on them, including the filtering mechanisms that exist on the actual selection sets.
class FInputHandlerStack
Class responsible for handling input to multiple objects that reside at the same level in the widget hierarchy.
struct FKeyBatchParameters
class FKeyFrameOutlinerColumn
struct FKeyOperation
Structure defining an opeartion that should add keys to a track.
struct FKeyRenderer
Utility class for efficiently drawing large numbers of keys on a track lane.
struct FKeyRendererPaintArgs
Paint arguments required for painting keys on a sequencer track.
struct FKeySectionOperation
Structure defining a section that needs to be keyed by specific channels.
struct FKeySelection
Main key selection class that stores selected key handles, and the channel they originated from.
class FLabelOutlinerColumn
Label Column.
class FLayerBarModel
class FLinkedOutlinerComputedSizingShim
Simple mixin class for having computed sizing information on a linked outliner item.
class FLinkedOutlinerExtension
Extension for a model that is linked somehow to an outliner model.
class FLockOutlinerColumn
A column for locking/unlocking tracks.
struct FMarkedFrameSelection
Main track-area marked frame selection class.
class FMuteOutlinerColumn
A column for muting/unmuting tracks.
class FMuteStateCacheExtension
class FNavOutlinerColumn
class FObjectBindingModel
class FObjectBindingModelStorageExtension
struct FObjectSchemaRelevancy
class FOutlinerCacheExtension
class FOutlinerColumnBase
struct FOutlinerColumnLayout
struct FOutlinerColumnPosition
class FOutlinerExtensionShim
Default implementation for some of the outliner extension API.
class FOutlinerIndicatorBuilderBase
class FOutlinerItemModel
class FOutlinerItemModelMixin
class FOutlinerSelection
struct FOutlinerSizing
class FOutlinerSpacer
class FOutlinerViewModel
class FOutlinerViewModelDragDropOp
A decorated drag drop operation object for dragging sequencer outliner items.
struct FOverlappingSections
struct FParentFirstChildIterator
A depth-first iterator into a hierarchy of data models.
struct FParentModelIterator
Iterator going up the parent relationships towards the root.
class FPinnableExtensionShim
Default implementation for IPinnableExtension, with helper method to cache pinned states for children of a pinned branch.
class FPossessableModel
struct FScopedViewModelListHead
Scoped object that adds a temporary child list to the specified model of the specified type.
class FSectionModel
Model for a sequencer section.
class FSectionModelStorageExtension
class FSelectionBase
Base class for all selection sets that can be added to an FSequencerCoreSelection owner.
struct FSelectionEventSuppressor
Scoped object type that temporarily suppresses broadcast of selection events.
class FSequenceModel
class FSequencerBakingSetupRestore
class FSequencerCoreSelection
Core selection class that manages multiple different selection sets through FSelectionBase.
class FSequencerEditorViewModel
Main view-model for the Sequencer editor.
struct FSequencerNumericTypeInterface
class FSequencerObjectBindingDragDropOp
class FSequencerOutlinerViewModel
class FSequencerSelection
Selection class for an ISequence instance that manages all the different types of selection and event marshaling.
class FSequencerTrackAreaViewModel
class FSharedViewModelData
struct FSnapPoint
Structure defining a point to snap to in the sequencer.
class FSoloOutlinerColumn
A column for soloing/unsoloing tracks.
struct FSortingKey
Structure for sorting models of various types together.
class FSpawnableModel
struct FStretchParameters
struct FStretchScreenParameters
struct FTimeDomainOverride
RAII struct that temporarily overrides time operations within Sequencer to operate in warped or unwarped space.
struct FTimeToPixelSpace
Utility for converting time units to slate pixel units and vice versa.
class FTimeWarpTrackExtension
struct FTimeWarpTrackModel
struct FTrackAreaParameters
struct FTrackAreaSelection
Main track-area selection class storing the selection of sections, layer-bars and other trac-area elements.
class FTrackAreaSlot
Structure representing a slot in the track area.
struct FTrackAreaViewLayers
class FTrackAreaViewModel
class FTrackAreaViewSpace
struct FTrackLaneScreenAlignment
struct FTrackLaneVerticalAlignment
struct FTrackLaneVerticalArrangement
struct FTrackLaneVirtualAlignment
class FTrackModel
class FTrackModelStorageExtension
class FTrackRowModel
class FTrackRowModelStorageExtension
struct FViewDensityInfo
class FViewModel
Base class for a sequencer data model.
struct FViewModelChildren
struct FViewModelExtensionCollection
Utility class for maintaining a list of view-models that implement a given extension in a given hierarchy.
class FViewModelHierarchyOperation
Scoped utility class for batching change notifications on a view model hierarchy This class works by keeping track of models that have been changed in some way, along with their previous sibling and parent pointers before any change was made.
struct FViewModelIterationState
Iterator state that wraps a view model and handles incrementing/decrementing its ActiveIterationCount while active.
struct FViewModelListHead
Defines the head of a linked list of view models.
struct FViewModelListIterator
Iterates all models contained in the specified list chain.
struct FViewModelListLink
Intrusive linked-list of data models.
struct FViewModelSubListIterator
Iterates all models that exist in a single list from the start model.
struct FViewModelTypeID
struct FViewModelVariantIterator
An iterator that can accomodate different types of data model lists, arrays, etc.
class FViewSpaceClientExtensionShim
An extension that is used for view models that represent UObject data.
struct FVirtualGeometry
Virtual bounding box information for track area elements.
class FVirtualTrackArea
Structure used for handling the virtual space of the track area.
class IBindingLifetimeExtension
class ICastable
class IClockExtension
Extension class that can be added to the sequence model in order to define a custom clock implementation.
class ICompoundOutlinerExtension
Extension for outliner models that want to compute their and their children's sizing.
class IConditionableExtension
An extension for models that can have conditions.
class ICurveEditorTreeItemExtension
Extension interface for view-models that want to show up in the curve editor.
class IDeactivatableExtension
An extension for outliner nodes that can be deactivated.
class IDeletableExtension
class IDimmableExtension
class IDraggableOutlinerExtension
Extension for models that can be dragged.
class IDraggableTrackAreaExtension
Extension for models that can be dragged.
class IDragOperation
Interface for drag operations.
class IDroppableExtension
Extension for models that can be dragged.
class IDynamicExtension
Base class for dynamic extensions that can be added to sequence data models and participate in dynamic casting.
class IGeometryExtension
Interface for data models who can store virtual geometry information.
class IGroupableExtension
class IHierarchicalCache
class IHotspotExtension
class IHoveredExtension
class IKeyExtension
class IKeyRendererInterface
Interface for defining selection states for keys.
class ILayerBarExtension
class ILockableExtension
An extension for models that can be locked.
class IMutableExtension
An extension for outliner nodes that can be muted.
struct INonLinearTimeTransform
class IObjectBindingExtension
class IObjectModelExtension
An extension that is used for view models that represent UObject data.
class IObjectSchema
class IOutlinerColumn
Interface for sequencer outliner columns.
class IOutlinerDropTargetOutlinerExtension
Extension for outliner items that accept drag and drop.
class IOutlinerExtension
Extension interface for models that can be displayed in the outliner view.
class IOutlinerIndicatorBuilder
Interface for building sequencer indicator outliner items.
class IPinnableExtension
An extension for outliner nodes that can be pinned at the top.
class IRecyclableExtension
class IRenameableExtension
class IResizableExtension
struct ISectionView
class ISelectableExtension
class ISequencerCoreModule
Interface for the Sequencer module.
class ISequencerEditTool
Interface for edit tools in Sequencer.
class ISequencerEditToolDragOperation
Interface for drag and drop operations that are handled by edit tools in Sequencer.
class ISequencerTreeView
class ISequencerTreeViewRow
Facade class to allow SOutlinerViewRow to be passed around publicly.
struct ISnapCandidate
Interface that defines how to construct an FSequencerSnapField.
class ISnapField
class ISnappableExtension
class ISoloableExtension
An extension for outliner nodes that can be made 'solo'.
class ISortableExtension
Extension for models that can sort their children, and be sorted themselves among their siblings.
class IStretchableExtension
class IStretchOperation
class ITimeDomainExtension
Extension class that can be added to sections and tracks in order to define which time domain their data is defined in.
class ITrackAreaExtension
This extension can be added to any model in order to provide a list of models that are relevent to the track area.
struct ITrackAreaHotspot
A sequencer hotspot is used to identify specific areas on the sequencer track area.
class ITrackAreaViewSpaceProviderExtension
An extension that supplies view spaces to a track area.
class ITrackExtension
class ITrackLaneExtension
Extension for view-models that can create track lanes in the track area.
class ITrackLaneWidget
Base interface for track-area lanes.
class ITrackLaneWidgetSpace
Interface used for laying out track lane widgets in screen space.
class IViewSpaceClientExtension
An extension that is used for view models that represent UObject data.
class SChannelView
Widget for displaying a channel within a section.
class SColumnToggleWidget
Outliner Column Widget for toggling active state with click and drag functionality.
class SCompoundTrackLaneView
class SOutlinerColumnButton
class SOutlinerItemViewBase
A widget for displaying a sequencer tree node in the animation outliner.
class SOutlinerObjectBindingView
A widget for displaying an object binding in the sequencer outliner.
class SOutlinerTrackColorPicker
class SOutlinerTrackView
A widget for displaying a track in the sequencer outliner.
class SOutlinerView
The tree view used in the sequencer.
class SOutlinerViewRow
Widget that represents a row in the sequencer's tree control.
class STrackAreaLaneView
class STrackAreaView
The area where tracks(rows of sections) are displayed.
class STrackLane
A wrapper widget responsible for positioning a track lane within the section area.
struct TAutoRegisterViewModelTypeID
struct TDynamicExtensionContainerIterator
struct TDynamicExtensionContainerIteratorProxy
struct TFilteredSelectionSetIteratorImpl
struct TFilteredViewModelSelectionIterator
class TFlagStateCacheExtension
struct TImplements
struct TImplicitViewModelCastImpl
Proxy type that enables implicit dynamic casting of a view-model to any other view-model or extension type.
struct TImplicitWeakViewModelPin
Proxy type that combines a Pin() and Cast() of a weak view model ptr, gracefully handling null.
class TOutlinerModelMixin
class TSelectionSetBase
Typed selection set for keeping track of an externally provided key type KeyType is what is stored within the selection set (ie, an FObjectKey, TWeakPtr or int32) MixinType is the type of the derived class.
struct TSelectionSetIteratorImpl
Minimal traits class for iterator implementations.
struct TSelectionSetIteratorImpl< TWeakPtr< T > >
Specialization for TWeakPtr types that skips invalid pointers and exposes iterators as TSharedPtr.
struct TSelectionSetIteratorImpl< TWeakViewModelPtr< T > >
Specialization for TWeakViewModelPtr types that skips invalid pointers and exposes iterators as TViewModelPtr.
struct TSelectionSetIteratorState
Selection iterator class that iterates a given selection set using specialized behavior for weak pointers.
class TSharedListItem
struct TTypedIterator
struct TTypedIterator< T, FParentFirstChildIterator >
struct TTypedIteratorBase
Utility class to wrap an untyped iterator (one that only returns FViewModel pointers) so that it can be used as a typed iterator.
class TUniqueFragmentSelectionSet
Selection set that defines a fragment selection of a view model where each fragment is globally unique.
struct TUniqueFragmentSelectionSetIterator
Iterator for iterating unique fragment selection sets.
struct TViewModelConversions
struct TViewModelConversions< const FViewModel >
struct TViewModelConversions< FViewModel >
struct TViewModelExtensionCollection
Strongly typed version of FViewModelExtensionCollection.
struct TViewModelPtr
Pointer type that wraps a shared view model pointer to provide implicit dynamic_cast style casting to any other view-model or extension.
struct TViewModelPtrStorage
Storage selector implemented as a type alias to defer instantiation and allow use with fwd declared types.
struct TViewModelTypeID
class TWeakListItem
struct TWeakViewModelConversions
Weak pointer utility for view models that also provides the same explicit conversion utility as F/TViewModelPtr Using this pointer type allows for expressive null handling and casting in a simple function call for any extension type which is useful for many widgets:
struct TWeakViewModelPtr
Templated version of FWeakViewModelPtr that provides an additional self-documenting extension that should exist on the view model.
Typedefs
using FConstViewModelPtr = TViewModelPtr<const FViewModel>
using FViewModelPtr = TViewModelPtr<FViewModel>
using FWeakViewModelPtr = TWeakViewModelPtr<FViewModel>
template<typename StorageKeyType, typename FilterType>
using TFilteredViewModelSelectionIteratorState = TSelectionSetIteratorState<StorageKeyType, TFilteredSelectionSetIteratorImpl<StorageKeyType, FilterType>>
Filtered iterator for a TSelectionSet<TWeakViewModelPtr<T>> that iterates only the items of a specific filtered type.
template<typename ViewModelType>
using TImplicitViewModelCast = TImplicitViewModelCastImpl<ViewModelType, false>
template<typename ViewModelType>
using TImplicitViewModelCastChecked = TImplicitViewModelCastImpl<ViewModelType, true>
template<typename T>
using TParentFirstChildIterator = TTypedIterator<T, FParentFirstChildIterator>
template<typename T>
using TParentModelIterator = TTypedIterator<T, FParentModelIterator>
template<typename T>
using TViewModelListIterator = TTypedIterator<T, FViewModelListIterator>
template<typename T>
using TViewModelSubListIterator = TTypedIterator<T, FViewModelSubListIterator>
Enumerations
enum class ECachedConditionState {
None = 0 , HasCondition = 1 << 0 , ConditionEvaluatingTrue = 1 << 1 , EditorForceTrue = 1 << 2 ,
ChildHasCondition = 1 << 3 , SectionHasCondition = 1 << 4 , ParentHasCondition = 1 << 5 , ParentHasConditionEvaluatingTrue = 1 << 6 ,
InheritedFromChildren = ChildHasCondition
}
enum class ECachedDeactiveState {
None = 0 , Deactivatable = 1 << 0 , DeactivatableChildren = 1 << 1 , Deactivated = 1 << 2 ,
PartiallyDeactivatedChildren = 1 << 3 , ImplicitlyDeactivatedByParent = 1 << 4 , Inheritable = 1 << 5 , InheritedFromChildren = DeactivatableChildren | PartiallyDeactivatedChildren
}
enum class ECachedLockState {
None = 0 , Lockable = 1 << 0 , LockableChildren = 1 << 1 , Locked = 1 << 2 ,
PartiallyLockedChildren = 1 << 3 , ImplicitlyLockedByParent = 1 << 4 , InheritedFromChildren = LockableChildren | PartiallyLockedChildren
}
enum class ECachedMuteState {
None = 0 , Mutable = 1 << 0 , MutableChildren = 1 << 1 , Muted = 1 << 2 ,
PartiallyMutedChildren = 1 << 3 , ImplicitlyMutedByParent = 1 << 4 , Inheritable = 1 << 5 , InheritedFromChildren = MutableChildren | PartiallyMutedChildren
}
enum class ECachedSoloState {
None = 0 , Soloable = 1 << 0 , SoloableChildren = 1 << 1 , Soloed = 1 << 2 ,
PartiallySoloedChildren = 1 << 3 , ImplicitlySoloedByParent = 1 << 4 , InheritedFromChildren = SoloableChildren | PartiallySoloedChildren
}
enum class EConditionableConditionState { None , HasConditionEvaluatingFalse , HasConditionEvaluatingTrue , HasConditionEditorForceTrue }
enum class EDeactivatableState { None , Deactivated , PartiallyDeactivated }
enum class EKeyNavigationButtons : uint8 {
PreviousKey = 1 << 0 , AddKey = 1 << 1 , NextKey = 1 << 2 , NavOnly = PreviousKey | NextKey ,
All = NavOnly | AddKey
}
enum class EKeySelectionPreviewState : uint8 { Undefined , Selected , NotSelected }
Key selection preview state - mirrored from FSequencer while selection concepts are ported to SequencerCore.
enum class ELockableLockState { None , Locked , PartiallyLocked }
enum class ENumericIntent { Position , Duration }
enum class EObjectBindingType { Possessable , Spawnable , Unknown }
Enumeration specifying what kind of object binding this is.
enum class EOutlinerColumnFlags : uint8 { None = 0 , OverflowSubsequentEmptyCells = 1 << 0 , OverflowOnHover = 1 << 1 , Hidden = 1 << 2 }
enum class EOutlinerColumnSizeMode : uint8 { Fixed , Stretch }
enum class EOutlinerItemViewBaseStyle { Default , ContainerHeader , InsideContainer }
enum class EOutlinerSelectionState {
None = 0 , SelectedDirectly = 1 << 0 , HasSelectedKeys = 1 << 1 , HasSelectedTrackAreaItems = 1 << 2 ,
DescendentHasSelectedKeys = 1 << 3 , DescendentHasSelectedTrackAreaItems = 1 << 4
}
enum class EOutlinerSizingFlags { None = 0 , DynamicSizing = 1 << 0 , IncludeSeparator = 1 << 1 , CustomHeight = 1 << 2 }
enum class ESelectionIntent { Never = 0x0 , PersistentSelection = 0x1 , ContextMenu = 0x2 , Any = PersistentSelection | ContextMenu }
Enumeration specifying the type of interaction that instigated the selection This allows models to opt-into selection in some contexts while refusing selection in others.
enum class ESortingMode { PriorityFirst , CustomOrderFirst , Default = CustomOrderFirst }
enum class EStretchConstraint { AnchorToStart , AnchorToEnd }
enum class EStretchResult { Success , Failure }
enum class ETimeDomain : uint8 { Warped , Unwarped }
enum class ETrackAreaLaneType : uint8 { Inline , Nested , None }
enum class ETreeRecursion { Recursive , NonRecursive }
enum class EViewDensity { Variable , Compact , Relaxed }
enum class EViewDependentCacheFlags : uint8 {
None = 0 , DataChanged = 1 << 0 , KeyStateChanged = 1 << 1 , ViewChanged = 1 << 2 ,
ViewZoomed = 1 << 3 , Empty = 1 << 4 , All = DataChanged | KeyStateChanged | ViewChanged | ViewZoomed
}
Flag enum signifying how the cache has changed since it was last generated.
enum class EViewModelListType : uint32 {
Generic = 1u << 0 , Outliner = 1u << 1 , TrackArea = 1u << 2 , Custom = 1u << 4 ,
Recycled = 1u << 30 , Last = 1u << 31 , Invalid = Last , Everything = (~0u) & ~(Recycled|Invalid) ,
Any = Everything
}
Model list for defining logical groupings of children within a view model Custom list types can be registered using RegisterCustomModelListType.
Functions
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModel (const TSharedPtr< InModelType > &InViewModel)
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModel (const TSharedRef< InModelType > &InViewModel)
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModel (const TViewModelPtr< InModelType > &InViewModel)
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModelChecked (const TSharedPtr< InModelType > &InViewModel)
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModelChecked (const TSharedRef< InModelType > &InViewModel)
template<typename OutModelType, typename InModelType>
TViewModelPtr< OutModelType > CastViewModelChecked (const TViewModelPtr< InModelType > &InViewModel)
template<typename EnumType>
EnumType CombinePropagatedChildFlags (EnumType ParentFlags, EnumType CombinedChildFlags)
DECLARE_DELEGATE_OneParam (FDynamicExtensionCallback, TSharedRef< FViewModel >)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnTrackAreaHotspotChanged, TSharedPtr< ITrackAreaHotspot >)
DECLARE_MULTICAST_DELEGATE_OneParam (FPreUpdateCachesEvent, FViewModelPtr)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnInitializeSequenceModel, TSharedPtr< FEditorViewModel >, TSharedPtr< FSequenceModel >)
ENUM_CLASS_FLAGS (ECachedDeactiveState) SEQUENCERCORE_API ECachedDeactiveState CombinePropagatedChildFlags(const ECachedDeactiveState ParentFlags
ENUM_CLASS_FLAGS (ECachedMuteState) SEQUENCERCORE_API ECachedMuteState CombinePropagatedChildFlags(ECachedMuteState ParentFlags
ENUM_CLASS_FLAGS (EOutlinerSelectionState)
ENUM_CLASS_FLAGS (EOutlinerSizingFlags)
ENUM_CLASS_FLAGS (ESelectionIntent)
ENUM_CLASS_FLAGS (EViewDependentCacheFlags)
ENUM_CLASS_FLAGS (EViewModelListType) SEQUENCERCORE_API EViewModelListType RegisterCustomModelListType()
Register a new custom view model list type.
ENUM_CLASS_FLAGS (FKeyRenderer::EKeyRenderingFlags)
ENUM_CLASS_FLAGS (ISnapCandidate::ESnapCapabilities)
SEQUENCER_API FFrameNumber GetFrameByRule (const ISequencer &Sequencer, ESequencerThumbnailCaptureTimeLocation Rule)
template<typename T>
FORCEINLINE TSharedPtr< T > HotspotCast (const TSharedPtr< ITrackAreaHotspot > &InHotspot)
SEQUENCERCORE_API TSharedRef< SWidget > MakeAddButton (FText HoverText, const FOnClicked &HandleClicked, const FViewModelPtr &ViewModel)
SEQUENCERCORE_API TSharedRef< SWidget > MakeAddButton (FText HoverText, const FOnClicked &OnClicked, const TAttribute< bool > &HoverState, const TAttribute< bool > &IsEnabled)
SEQUENCERCORE_API TSharedRef< SWidget > MakeAddButton (FText HoverText, const FOnGetContent &HandleGetMenuContent, const FViewModelPtr &ViewModel)
SEQUENCERCORE_API TSharedRef< SWidget > MakeAddButton (FText HoverText, const FOnGetContent &HandleGetMenuContent, const TAttribute< bool > &HoverState, const TAttribute< bool > &IsEnabled)
SEQUENCERCORE_API TSharedRef< SWidget > MakeButton (FText HoverText, const FSlateBrush *Image, const FOnClicked &HandleClicked, const FViewModelPtr &ViewModel)
SEQUENCERCORE_API TSharedRef< SWidget > MakeButton (FText HoverText, const FSlateBrush *Image, const FOnGetContent &HandleGetMenuContent, const FViewModelPtr &ViewModel)
Variables
ECachedDeactiveState CombinedChildFlags
Typedef Documentation
FConstViewModelPtr
using UE::Sequencer::FConstViewModelPtr = TViewModelPtr<const FViewModel>
Definition at line 64 of file SequencerCoreFwd.h.
FViewModelPtr
using UE::Sequencer::FViewModelPtr = TViewModelPtr<FViewModel>
Definition at line 63 of file SequencerCoreFwd.h.
FWeakViewModelPtr
using UE::Sequencer::FWeakViewModelPtr = TWeakViewModelPtr<FViewModel>
Definition at line 65 of file SequencerCoreFwd.h.
TFilteredViewModelSelectionIteratorState
template<typename StorageKeyType, typename FilterType> using UE::Sequencer::TFilteredViewModelSelectionIteratorState = TSelectionSetIteratorState<StorageKeyType, TFilteredSelectionSetIteratorImpl<StorageKeyType, FilterType>>
Filtered iterator for a TSelectionSet<TWeakViewModelPtr<T>> that iterates only the items of a specific filtered type.
Definition at line 122 of file SequencerCoreSelectionIterators.h.
TImplicitViewModelCast
template<typename ViewModelType> using UE::Sequencer::TImplicitViewModelCast = TImplicitViewModelCastImpl<ViewModelType, false>
Definition at line 52 of file SequencerCoreFwd.h.
TImplicitViewModelCastChecked
template<typename ViewModelType> using UE::Sequencer::TImplicitViewModelCastChecked = TImplicitViewModelCastImpl<ViewModelType, true>
Definition at line 55 of file SequencerCoreFwd.h.
TParentFirstChildIterator
template<typename T> using UE::Sequencer::TParentFirstChildIterator = TTypedIterator<T, FParentFirstChildIterator>
Definition at line 592 of file ViewModelIterators.h.
TParentModelIterator
template<typename T> using UE::Sequencer::TParentModelIterator = TTypedIterator<T, FParentModelIterator>
Definition at line 590 of file ViewModelIterators.h.
TViewModelListIterator
template<typename T> using UE::Sequencer::TViewModelListIterator = TTypedIterator<T, FViewModelListIterator>
Definition at line 594 of file ViewModelIterators.h.
TViewModelSubListIterator
template<typename T> using UE::Sequencer::TViewModelSubListIterator = TTypedIterator<T, FViewModelSubListIterator>
Definition at line 596 of file ViewModelIterators.h.
Enumeration Type Documentation
ECachedConditionState
enum class UE::Sequencer::ECachedConditionState strong
Enumerator
None
HasCondition
ConditionEvaluatingTrue
EditorForceTrue
ChildHasCondition
SectionHasCondition
ParentHasCondition
ParentHasConditionEvaluatingTrue
InheritedFromChildren
Definition at line 44 of file IConditionableExtension.h.
ECachedDeactiveState
enum class UE::Sequencer::ECachedDeactiveState strong
Enumerator
None
Deactivatable
DeactivatableChildren
Deactivated
PartiallyDeactivatedChildren
ImplicitlyDeactivatedByParent
Inheritable
InheritedFromChildren
Definition at line 41 of file IDeactivatableExtension.h.
ECachedLockState
enum class UE::Sequencer::ECachedLockState strong
Enumerator
None
Lockable
LockableChildren
Locked
PartiallyLockedChildren
ImplicitlyLockedByParent
InheritedFromChildren
Definition at line 39 of file ILockableExtension.h.
ECachedMuteState
enum class UE::Sequencer::ECachedMuteState strong
Enumerator
None
Mutable
MutableChildren
Muted
PartiallyMutedChildren
ImplicitlyMutedByParent
Inheritable
InheritedFromChildren
Definition at line 38 of file IMutableExtension.h.
ECachedSoloState
enum class UE::Sequencer::ECachedSoloState strong
Enumerator
None
Soloable
SoloableChildren
Soloed
PartiallySoloedChildren
ImplicitlySoloedByParent
InheritedFromChildren
Definition at line 32 of file ISoloableExtension.h.
EConditionableConditionState
enum class UE::Sequencer::EConditionableConditionState strong
Enumerator
None
HasConditionEvaluatingFalse
HasConditionEvaluatingTrue
HasConditionEditorForceTrue
Definition at line 15 of file IConditionableExtension.h.
EDeactivatableState
enum class UE::Sequencer::EDeactivatableState strong
Enumerator
None
Deactivated
PartiallyDeactivated
Definition at line 11 of file IDeactivatableExtension.h.
EKeyNavigationButtons
enum class UE::Sequencer::EKeyNavigationButtons : uint8 strong
Enumerator
PreviousKey
AddKey
NextKey
NavOnly
All
Definition at line 28 of file SKeyNavigationButtons.h.
EKeySelectionPreviewState
enum class UE::Sequencer::EKeySelectionPreviewState : uint8 strong
Key selection preview state - mirrored from FSequencer while selection concepts are ported to SequencerCore.
Enumerator
Undefined
Selected
NotSelected
Definition at line 26 of file KeyRenderer.h.
ELockableLockState
enum class UE::Sequencer::ELockableLockState strong
Enumerator
None
Locked
PartiallyLocked
Definition at line 14 of file ILockableExtension.h.
ENumericIntent
enum class UE::Sequencer::ENumericIntent strong
Enumerator
Position
Duration
Definition at line 13 of file ISequencerNumericTypeInterface.h.
EObjectBindingType
enum class UE::Sequencer::EObjectBindingType strong
Enumeration specifying what kind of object binding this is.
Enumerator
Possessable
Spawnable
Unknown
Definition at line 38 of file ObjectBindingModel.h.
EOutlinerColumnFlags
enum class UE::Sequencer::EOutlinerColumnFlags : uint8 strong
Enumerator
None
OverflowSubsequentEmptyCells
OverflowOnHover
Hidden
Definition at line 12 of file OutlinerColumnTypes.h.
EOutlinerColumnSizeMode
enum class UE::Sequencer::EOutlinerColumnSizeMode : uint8 strong
Enumerator
Fixed
Stretch
Definition at line 42 of file OutlinerColumnTypes.h.
EOutlinerItemViewBaseStyle
enum class UE::Sequencer::EOutlinerItemViewBaseStyle strong
Enumerator
Default
ContainerHeader
InsideContainer
Definition at line 35 of file SOutlinerItemViewBase.h.
EOutlinerSelectionState
enum class UE::Sequencer::EOutlinerSelectionState strong
Enumerator
None
SelectedDirectly
HasSelectedKeys
HasSelectedTrackAreaItems
DescendentHasSelectedKeys
DescendentHasSelectedTrackAreaItems
Definition at line 38 of file IOutlinerExtension.h.
EOutlinerSizingFlags
enum class UE::Sequencer::EOutlinerSizingFlags strong
Enumerator
None
DynamicSizing
IncludeSeparator
CustomHeight
Definition at line 50 of file IOutlinerExtension.h.
ESelectionIntent
enum class UE::Sequencer::ESelectionIntent strong
Enumeration specifying the type of interaction that instigated the selection This allows models to opt-into selection in some contexts while refusing selection in others.
Enumerator
Never
Symbolic value signifying that a model is never selectable.
PersistentSelection
Used when the selection will be persistent and visible on the UI.
ContextMenu
Used exclisively for a transient context-menu selection.
Any
Combination that defines any intent is supported.
Definition at line 24 of file ISelectableExtension.h.
ESortingMode
enum class UE::Sequencer::ESortingMode strong
Enumerator
PriorityFirst
CustomOrderFirst
Default
Definition at line 63 of file ISortableExtension.h.
EStretchConstraint
enum class UE::Sequencer::EStretchConstraint strong
Enumerator
AnchorToStart
AnchorToEnd
Definition at line 23 of file IStretchableExtension.h.
EStretchResult
enum class UE::Sequencer::EStretchResult strong
Enumerator
Success
Failure
Definition at line 28 of file IStretchableExtension.h.
ETimeDomain
enum class UE::Sequencer::ETimeDomain : uint8 strong
Enumerator
Warped
Unwarped
Definition at line 11 of file SequencerTimeDomainOverride.h.
ETrackAreaLaneType
enum class UE::Sequencer::ETrackAreaLaneType : uint8 strong
Enumerator
Inline
Nested
None
Definition at line 16 of file ITrackAreaExtension.h.
ETreeRecursion
enum class UE::Sequencer::ETreeRecursion strong
Enumerator
Recursive
NonRecursive
Definition at line 61 of file SOutlinerView.h.
EViewDensity
enum class UE::Sequencer::EViewDensity strong
Enumerator
Variable
Variable density where inner items are more condensed than top level or outer items.
Compact
A compact view type with uniform heights.
Relaxed
A relaxed view type with larger, uniform heights and additional information.
Definition at line 11 of file ViewDensity.h.
EViewDependentCacheFlags
enum class UE::Sequencer::EViewDependentCacheFlags : uint8 strong
Flag enum signifying how the cache has changed since it was last generated.
Enumerator
None
DataChanged
KeyStateChanged
ViewChanged
ViewZoomed
Empty
All
Definition at line 64 of file KeyRenderer.h.
EViewModelListType
enum class UE::Sequencer::EViewModelListType : uint32 strong
Model list for defining logical groupings of children within a view model Custom list types can be registered using RegisterCustomModelListType.
Enumerator
Generic
Outliner
TrackArea
Custom
Recycled
Last
Invalid
Everything
Any
Definition at line 33 of file ViewModelHierarchy.h.
Function Documentation
CastViewModel() [1/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModel (const TSharedPtr< InModelType > & InViewModel)
Definition at line 345 of file ViewModelPtr.h.
CastViewModel() [2/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModel (const TSharedRef< InModelType > & InViewModel)
Definition at line 340 of file ViewModelPtr.h.
Referenced by UE::Sequencer::TWeakViewModelPtr< ExtensionType >::Pin(), and UE::Sequencer::TFilteredSelectionSetIteratorImpl< KeyType, FilterType >::SkipInvalid().
CastViewModel() [3/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModel (const TViewModelPtr< InModelType > & InViewModel)
Definition at line 354 of file ViewModelPtr.h.
References UE::Sequencer::TViewModelPtr< T >::ImplicitCast().
CastViewModelChecked() [1/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModelChecked (const TSharedPtr< InModelType > & InViewModel)
Definition at line 367 of file ViewModelPtr.h.
References check.
CastViewModelChecked() [2/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModelChecked (const TSharedRef< InModelType > & InViewModel)
Definition at line 360 of file ViewModelPtr.h.
References check.
CastViewModelChecked() [3/3]
template<typename OutModelType, typename InModelType> TViewModelPtr< OutModelType > UE::Sequencer::CastViewModelChecked (const TViewModelPtr< InModelType > & InViewModel)
Definition at line 374 of file ViewModelPtr.h.
References check, and UE::Sequencer::TViewModelPtr< T >::ImplicitCast().
CombinePropagatedChildFlags()
template<typename EnumType> EnumType UE::Sequencer::CombinePropagatedChildFlags (EnumType ParentFlags, EnumType CombinedChildFlags)
Definition at line 19 of file HierarchicalCacheExtension.h.
References CombinedChildFlags.
Referenced by UE::Sequencer::TFlagStateCacheExtension< FlagsType >::PostVisitChildren().
DECLARE_DELEGATE_OneParam()
UE::Sequencer::DECLARE_DELEGATE_OneParam (FDynamicExtensionCallback , TSharedRef< FViewModel >)
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
UE::Sequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnTrackAreaHotspotChanged , TSharedPtr< ITrackAreaHotspot >)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
UE::Sequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FPreUpdateCachesEvent , FViewModelPtr)
DECLARE_MULTICAST_DELEGATE_TwoParams()
UE::Sequencer::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnInitializeSequenceModel , TSharedPtr< FEditorViewModel > , TSharedPtr< FSequenceModel >)
ENUM_CLASS_FLAGS() [1/9]
UE::Sequencer::ENUM_CLASS_FLAGS (ECachedDeactiveState) const
ENUM_CLASS_FLAGS() [2/9]
UE::Sequencer::ENUM_CLASS_FLAGS (ECachedMuteState)
References CombinedChildFlags.
ENUM_CLASS_FLAGS() [3/9]
UE::Sequencer::ENUM_CLASS_FLAGS (EOutlinerSelectionState)
ENUM_CLASS_FLAGS() [4/9]
UE::Sequencer::ENUM_CLASS_FLAGS (EOutlinerSizingFlags)
ENUM_CLASS_FLAGS() [5/9]
UE::Sequencer::ENUM_CLASS_FLAGS (ESelectionIntent)
ENUM_CLASS_FLAGS() [6/9]
UE::Sequencer::ENUM_CLASS_FLAGS (EViewDependentCacheFlags)
ENUM_CLASS_FLAGS() [7/9]
UE::Sequencer::ENUM_CLASS_FLAGS (EViewModelListType)
Register a new custom view model list type.
ENUM_CLASS_FLAGS() [8/9]
UE::Sequencer::ENUM_CLASS_FLAGS (FKeyRenderer::EKeyRenderingFlags)
ENUM_CLASS_FLAGS() [9/9]
UE::Sequencer::ENUM_CLASS_FLAGS (ISnapCandidate::ESnapCapabilities)
GetFrameByRule()
SEQUENCER_API FFrameNumber UE::Sequencer::GetFrameByRule (const ISequencer & Sequencer, ESequencerThumbnailCaptureTimeLocation Rule)
Returns
The frame that Rule wants to get from Sequencer
HotspotCast()
template<typename T> FORCEINLINE TSharedPtr< T > UE::Sequencer::HotspotCast (const TSharedPtr< ITrackAreaHotspot > & InHotspot)
Definition at line 45 of file ITrackAreaHotspot.h.
References FORCEINLINE, and TSharedPtr< ObjectType, InMode >::Get().
MakeAddButton() [1/4]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeAddButton (FText HoverText, const FOnClicked & HandleClicked, const FViewModelPtr & ViewModel)
MakeAddButton() [2/4]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeAddButton (FText HoverText, const FOnClicked & OnClicked, const TAttribute< bool > & HoverState, const TAttribute< bool > & IsEnabled)
MakeAddButton() [3/4]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeAddButton (FText HoverText, const FOnGetContent & HandleGetMenuContent, const FViewModelPtr & ViewModel)
MakeAddButton() [4/4]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeAddButton (FText HoverText, const FOnGetContent & HandleGetMenuContent, const TAttribute< bool > & HoverState, const TAttribute< bool > & IsEnabled)
MakeButton() [1/2]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeButton (FText HoverText, const FSlateBrush * Image, const FOnClicked & HandleClicked, const FViewModelPtr & ViewModel)
MakeButton() [2/2]
SEQUENCERCORE_API TSharedRef< SWidget > UE::Sequencer::MakeButton (FText HoverText, const FSlateBrush * Image, const FOnGetContent & HandleGetMenuContent, const FViewModelPtr & ViewModel)
Variable Documentation
CombinedChildFlags
ECachedMuteState UE::Sequencer::CombinedChildFlags
Definition at line 56 of file IDeactivatableExtension.h.
Referenced by CombinePropagatedChildFlags(), and ENUM_CLASS_FLAGS().