Unreal Engine 5.6 C++ API: SharedPointerInternals::FWeakReferencer< Mode > Class Template Reference
SharedPointerInternals::FWeakReferencer< Mode > Class Template Reference
FWeakReferencer is a wrapper around a pointer to a reference controller that is used by a TWeakPtr to keep track of a referenced object's lifetime.
#include "SharedPointerInternals.h"
Public Member Functions
FORCEINLINE FWeakReferencer ()
Default constructor with empty counter.
FORCEINLINE FWeakReferencer (FSharedReferencer< Mode > const &InSharedRefCountPointer)
Construct a weak referencer object from a shared referencer object.
FORCEINLINE FWeakReferencer (FWeakReferencer &&InWeakRefCountPointer)
Construct a weak referencer object from an rvalue weak referencer.
FORCEINLINE FWeakReferencer (FWeakReferencer const &InWeakRefCountPointer)
Construct a weak referencer object from another weak referencer.
FORCEINLINE ~FWeakReferencer ()
Destructor.
FORCEINLINE const bool IsValid () const
Tests to see whether or not this weak counter contains a valid reference.
FORCEINLINE FWeakReferencer & operator= (FSharedReferencer< Mode > const &InSharedReference)
Assignment operator from a shared reference counter.
FORCEINLINE FWeakReferencer & operator= (FWeakReferencer &&InWeakReference)
Assignment operator from an rvalue weak referencer object.
FORCEINLINE FWeakReferencer & operator= (FWeakReferencer const &InWeakReference)
Assignment operator from a weak referencer object.
Private Member Functions
void AssignReferenceController (TReferenceControllerBase< Mode > *NewReferenceController)
Assigns a new reference controller to this counter object, first adding a reference to it, then releasing the previous object.
Private Attributes
TReferenceControllerBase< Mode > * ReferenceController
Pointer to the reference controller for the object a TWeakPtr is referencing.
Friends
template<ESPMode OtherMode>
class FSharedReferencer
Expose access to ReferenceController to FSharedReferencer.
Detailed Description
template<ESPMode Mode>
class SharedPointerInternals::FWeakReferencer< Mode >
FWeakReferencer is a wrapper around a pointer to a reference controller that is used by a TWeakPtr to keep track of a referenced object's lifetime.
Definition at line 708 of file SharedPointerInternals.h.
Constructor & Destructor Documentation
FWeakReferencer() [1/4]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FWeakReferencer< Mode >::FWeakReferencer () inline
Default constructor with empty counter.
Definition at line 713 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
Referenced by FWeakReferencer(), FWeakReferencer(), operator=(), operator=(), and operator=().
FWeakReferencer() [2/4]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FWeakReferencer< Mode >::FWeakReferencer (FWeakReferencer< Mode > const & InWeakRefCountPointer) inline
Construct a weak referencer object from another weak referencer.
Definition at line 718 of file SharedPointerInternals.h.
References FWeakReferencer(), FORCEINLINE, and ReferenceController.
FWeakReferencer() [3/4]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FWeakReferencer< Mode >::FWeakReferencer (FWeakReferencer< Mode > && InWeakRefCountPointer) inline
Construct a weak referencer object from an rvalue weak referencer.
Definition at line 729 of file SharedPointerInternals.h.
References FWeakReferencer(), FORCEINLINE, and ReferenceController.
FWeakReferencer() [4/4]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FWeakReferencer< Mode >::FWeakReferencer (FSharedReferencer< Mode > const & InSharedRefCountPointer) inline
Construct a weak referencer object from a shared referencer object.
Definition at line 736 of file SharedPointerInternals.h.
References FORCEINLINE, FSharedReferencer, and ReferenceController.
~FWeakReferencer()
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FWeakReferencer< Mode >::~FWeakReferencer () inline
Destructor.
Definition at line 747 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
Member Function Documentation
AssignReferenceController()
template<ESPMode Mode> void SharedPointerInternals::FWeakReferencer< Mode >::AssignReferenceController (TReferenceControllerBase< Mode > * NewReferenceController) inline private
Assigns a new reference controller to this counter object, first adding a reference to it, then releasing the previous object.
Definition at line 804 of file SharedPointerInternals.h.
References SharedPointerInternals::TReferenceControllerBase< Mode >::AddWeakReference(), and ReferenceController.
Referenced by operator=(), and operator=().
IsValid()
template<ESPMode Mode> FORCEINLINE const bool SharedPointerInternals::FWeakReferencer< Mode >::IsValid () const inline
Tests to see whether or not this weak counter contains a valid reference.
Returns
True if reference is valid
Definition at line 795 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
operator=() [1/3]
template<ESPMode Mode> FORCEINLINE FWeakReferencer & SharedPointerInternals::FWeakReferencer< Mode >::operator= (FSharedReferencer< Mode > const & InSharedReference) inline
Assignment operator from a shared reference counter.
If this counter was previously referencing an object, that reference will be released.
Definition at line 783 of file SharedPointerInternals.h.
References FWeakReferencer(), AssignReferenceController(), FORCEINLINE, FSharedReferencer, and SharedPointerInternals::FSharedReferencer< Mode >::ReferenceController.
operator=() [2/3]
template<ESPMode Mode> FORCEINLINE FWeakReferencer & SharedPointerInternals::FWeakReferencer< Mode >::operator= (FWeakReferencer< Mode > && InWeakReference) inline
Assignment operator from an rvalue weak referencer object.
If this counter was previously referencing an object, that reference will be released.
Definition at line 768 of file SharedPointerInternals.h.
References FWeakReferencer(), FORCEINLINE, and ReferenceController.
operator=() [3/3]
template<ESPMode Mode> FORCEINLINE FWeakReferencer & SharedPointerInternals::FWeakReferencer< Mode >::operator= (FWeakReferencer< Mode > const & InWeakReference) inline
Assignment operator from a weak referencer object.
If this counter was previously referencing an object, that reference will be released.
Definition at line 759 of file SharedPointerInternals.h.
References FWeakReferencer(), AssignReferenceController(), FORCEINLINE, and ReferenceController.
Friends And Related Symbol Documentation
FSharedReferencer
template<ESPMode Mode> template<ESPMode OtherMode> friend class FSharedReferencer friend
Expose access to ReferenceController to FSharedReferencer.
Definition at line 829 of file SharedPointerInternals.h.
References FSharedReferencer.
Referenced by FWeakReferencer(), FSharedReferencer, and operator=().
Field Documentation
ReferenceController
template<ESPMode Mode> TReferenceControllerBase<Mode>* SharedPointerInternals::FWeakReferencer< Mode >::ReferenceController private
Pointer to the reference controller for the object a TWeakPtr is referencing.
Definition at line 834 of file SharedPointerInternals.h.
Referenced by FWeakReferencer(), FWeakReferencer(), FWeakReferencer(), FWeakReferencer(), ~FWeakReferencer(), AssignReferenceController(), IsValid(), operator=(), and operator=().
The documentation for this class was generated from the following file:
SharedPointerInternals.h