Unreal Engine 5.6 C++ API: FRigVMRegistry_RWLock Struct Reference
FRigVMRegistry_RWLock Struct Reference final
The FRigVMRegistry is used to manage all known function pointers for use in the RigVM.
#include "RigVMRegistry.h"
Data Structures
class FConditionalReadScopeLock
class FConditionalScopeLock
class FConditionalWriteScopeLock
Public Types
typedef FRigVMRegistry_NoLock Super
Public Types inherited from FRigVMRegistry_NoLock
enum ELockType : uint8 { LockType_Read , LockType_Write , LockType_Invalid }
enum class ERegisterObjectOperation { Class , ClassAndParents , ClassAndChildren }
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
const FRigVMTemplate * AddTemplateFromArguments (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates, bool bLockRegistry=true)
bool CanMatchTypes (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts, bool bLockRegistry=true) const
bool ConvertExecuteContextToBaseType (TRigVMTypeIndex &InOutTypeIndex, bool bLockRegistry=true) const
FRigVMDispatchFactory * FindDispatchFactory (const FName &InFactoryName, bool bLockRegistry=true) const
const FRigVMFunction * FindFunction (const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InTypeResolver=FRigVMUserDefinedTypeResolver(), bool bLockRegistry=true) const
const FRigVMFunction * FindFunction (UScriptStruct *InStruct, const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InResolvalInfo=FRigVMUserDefinedTypeResolver(), bool bLockRegistry=true) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FRigVMDispatchFactory * FindOrAddDispatchFactory (bool bLockRegistry=true)
FRigVMDispatchFactory * FindOrAddDispatchFactory (UScriptStruct *InFactoryStruct, bool bLockRegistry=true)
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FString FindOrAddSingletonDispatchFunction (bool bLockRegistry=true)
FString FindOrAddSingletonDispatchFunction (UScriptStruct *InFactoryStruct, bool bLockRegistry=true)
TRigVMTypeIndex FindOrAddType (const FRigVMTemplateArgumentType &InType, bool bForce=false, bool bLockRegistry=true)
const FRigVMTemplate * FindTemplate (const FName &InNotation, bool bIncludeDeprecated=false, bool bLockRegistry=true) const
const FRigVMTemplateArgumentType & FindTypeFromCPPType (const FString &InCPPType, bool bLockRegistry=true) const
int32 GetArrayDimensionsForType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
TRigVMTypeIndex GetArrayTypeFromBaseTypeIndex (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
TRigVMTypeIndex GetBaseTypeFromArrayTypeIndex (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
const TArray< TRigVMTypeIndex > & GetCompatibleTypes (TRigVMTypeIndex InTypeIndex) const
const TArray< FRigVMDispatchFactory * > & GetFactories (bool bLockRegistry=true) const
const TChunkedArray< FRigVMFunction > & GetFunctions (bool bLockRegistry=true) const
uint32 GetHashForEnum (const UEnum *InEnum, bool bCheckTypeIndex=true, bool bLockRegistry=true) const
uint32 GetHashForProperty (const FProperty *InProperty, bool bLockRegistry=true) const
uint32 GetHashForScriptStruct (const UScriptStruct *InScriptStruct, bool bCheckTypeIndex=true, bool bLockRegistry=true) const
uint32 GetHashForStruct (const UStruct *InStruct, bool bLockRegistry=true) const
uint32 GetHashForType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
const FRigVMTemplate * GetOrAddTemplateFromArguments (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates, bool bLockRegistry=true)
const TArray< FRigVMFunction > * GetPredicatesForStruct (const FName &InStructName, bool bLockRegistry=true) const
const TChunkedArray< FRigVMTemplate > & GetTemplates (bool bLockRegistry=true) const
const FRigVMTemplateArgumentType & GetType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
template<typename T>
TRigVMTypeIndex GetTypeIndex (bool bAsArray=false, bool bLockRegistry=true) const
TRigVMTypeIndex GetTypeIndex (const FName &InCPPType, UObject *InCPPTypeObject, bool bLockRegistry=true) const
TRigVMTypeIndex GetTypeIndex (const FRigVMTemplateArgumentType &InType, bool bLockRegistry=true) const
TRigVMTypeIndex GetTypeIndexFromCPPType (const FString &InCPPType, bool bLockRegistry=true) const
const TArray< TRigVMTypeIndex > & GetTypesForCategory (FRigVMTemplateArgument::ETypeCategory InCategory, bool bLockRegistry=true) const
bool IsArrayType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
bool IsExecuteType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry=true) const
bool IsWildCardType (TRigVMTypeIndex InTypeIndex) const
int32 NumTypes (bool bLockRegistry=true) const
RIGVM_API void OnAnimationAttributeTypesChanged (const UScriptStruct *InStruct, bool bIsAdded)
RIGVM_API void OnAssetRemoved (const FAssetData &InAssetData)
void OnAssetRenamed (const FAssetData &InAssetData, const FString &InOldObjectPath)
RIGVM_API void OnPluginLoaded (IPlugin &InPlugin)
RIGVM_API void OnPluginUnloaded (IPlugin &InPlugin)
FOnRigVMRegistryChanged & OnRigVMRegistryChanged ()
void RebuildRegistry (bool bLockRegistry=true)
void RefreshEngineTypes ()
void RefreshEngineTypesIfRequired (bool bLockRegistry=true)
bool RefreshFunctionsAndDispatches ()
void Register (const TCHAR *InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct *InStruct=nullptr, const TArray< FRigVMFunctionArgument > &InArguments=TArray< FRigVMFunctionArgument >(), bool bLockRegistry=true)
const FRigVMDispatchFactory * RegisterFactory (UScriptStruct *InFactoryStruct, bool bLockRegistry=true)
void RegisterObjectTypes (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses, bool bLockRegistry=true)
void RegisterPredicate (UScriptStruct *InStruct, const TCHAR *InName, const TArray< FRigVMFunctionArgument > &InArguments, bool bLockRegistry=true)
void RegisterStructTypes (TConstArrayView< UScriptStruct * > InStructs, bool bLockRegistry=true)
bool RemoveType (const FSoftObjectPath &InObjectPath, const UClass *InObjectClass, bool bLockRegistry=true)
void Reset (bool bLockRegistry=true)
Public Member Functions inherited from FRigVMRegistry_NoLock
virtual RIGVM_API ~FRigVMRegistry_NoLock () override
virtual RIGVM_API void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
DECLARE_MULTICAST_DELEGATE (FOnRigVMRegistryChanged)
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FRigVMDispatchFactory * FindOrAddDispatchFactory_NoLock ()
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FString FindOrAddSingletonDispatchFunction_NoLock ()
virtual RIGVM_API FString GetReferencerName () const override
Overload this method to report a name for your referencer.
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value, T >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
TRigVMTypeIndex GetTypeIndex_NoLock (bool bAsArray=false) const
virtual RIGVM_API void RegisterStructTypes_NoLock (TConstArrayView< UScriptStruct * > InStructs)
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static RIGVM_API FRigVMRegistry_RWLock & Get ()
static FRigVMRegistry_NoLock & Get (ELockType InLockType)=delete
static const FRigVMRegistry_NoLock & GetForRead ()=delete
static FRigVMRegistry_NoLock & GetForWrite ()=delete
Static Public Member Functions inherited from FRigVMRegistry_NoLock
static RIGVM_API FRigVMRegistry_NoLock & Get (ELockType InLockType)
static const FRigVMRegistry_NoLock & GetForRead ()
static FRigVMRegistry_NoLock & GetForWrite ()
static RIGVM_API const TArray< UScriptStruct * > & GetMathTypes ()
static RIGVM_API void OnEngineInit ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Protected Member Functions
virtual const FRigVMTemplate * AddTemplateFromArguments_NoLock (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates) override
virtual bool CanMatchTypes_NoLock (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts) const override
virtual bool ConvertExecuteContextToBaseType_NoLock (TRigVMTypeIndex &InOutTypeIndex) const override
virtual FRigVMDispatchFactory * FindDispatchFactory_NoLock (const FName &InFactoryName) const override
virtual const FRigVMFunction * FindFunction_NoLock (const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InTypeResolver=FRigVMUserDefinedTypeResolver()) const override
virtual const FRigVMFunction * FindFunction_NoLock (UScriptStruct *InStruct, const TCHAR *InName, const FRigVMUserDefinedTypeResolver &InResolvalInfo=FRigVMUserDefinedTypeResolver()) const override
virtual FRigVMDispatchFactory * FindOrAddDispatchFactory_NoLock (UScriptStruct *InFactoryStruct) override
virtual FString FindOrAddSingletonDispatchFunction_NoLock (UScriptStruct *InFactoryStruct) override
virtual TRigVMTypeIndex FindOrAddType_NoLock (const FRigVMTemplateArgumentType &InType, bool bForce=false) override
virtual const FRigVMTemplate * FindTemplate_NoLock (const FName &InNotation, bool bIncludeDeprecated=false) const override
virtual const FRigVMTemplateArgumentType & FindTypeFromCPPType_NoLock (const FString &InCPPType) const override
virtual int32 GetArrayDimensionsForType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual TRigVMTypeIndex GetArrayTypeFromBaseTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual TRigVMTypeIndex GetBaseTypeFromArrayTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual const TArray< TRigVMTypeIndex > & GetCompatibleTypes_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual const TArray< FRigVMDispatchFactory * > & GetFactories_NoLock () const override
virtual const TChunkedArray< FRigVMFunction > & GetFunctions_NoLock () const override
virtual uint32 GetHashForEnum_NoLock (const UEnum *InEnum, bool bCheckTypeIndex=true) const override
virtual uint32 GetHashForProperty_NoLock (const FProperty *InProperty) const override
virtual uint32 GetHashForScriptStruct_NoLock (const UScriptStruct *InScriptStruct, bool bCheckTypeIndex=true) const override
virtual uint32 GetHashForStruct_NoLock (const UStruct *InStruct) const override
virtual uint32 GetHashForType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual const FRigVMTemplate * GetOrAddTemplateFromArguments_NoLock (const FName &InName, const TArray< FRigVMTemplateArgumentInfo > &InInfos, const FRigVMTemplateDelegates &InDelegates) override
virtual const TArray< FRigVMFunction > * GetPredicatesForStruct_NoLock (const FName &InStructName) const override
virtual const TChunkedArray< FRigVMTemplate > & GetTemplates_NoLock () const override
virtual const FRigVMTemplateArgumentType & GetType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual TRigVMTypeIndex GetTypeIndex_NoLock (const FName &InCPPType, UObject *InCPPTypeObject) const override
virtual TRigVMTypeIndex GetTypeIndex_NoLock (const FRigVMTemplateArgumentType &InType) const override
virtual TRigVMTypeIndex GetTypeIndexFromCPPType_NoLock (const FString &InCPPType) const override
virtual const TArray< TRigVMTypeIndex > & GetTypesForCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory) const override
virtual bool IsArrayType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual bool IsExecuteType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual bool IsWildCardType_NoLock (TRigVMTypeIndex InTypeIndex) const override
virtual int32 NumTypes_NoLock () const override
virtual void OnAnimationAttributeTypesChanged_NoLock (const UScriptStruct *InStruct, bool bIsAdded) override
virtual bool OnAssetRemoved_NoLock (const FAssetData &InAssetData) override
virtual void OnAssetRenamed_NoLock (const FAssetData &InAssetData, const FString &InOldObjectPath) override
virtual bool OnPluginLoaded_NoLock (IPlugin &InPlugin) override
virtual bool OnPluginUnloaded_NoLock (IPlugin &InPlugin) override
virtual void RebuildRegistry_NoLock () override
virtual void RefreshEngineTypes_NoLock () override
virtual void RefreshEngineTypesIfRequired_NoLock () override
virtual bool RefreshFunctionsAndDispatches_NoLock () override
virtual void Register_NoLock (const TCHAR *InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct *InStruct=nullptr, const TArray< FRigVMFunctionArgument > &InArguments=TArray< FRigVMFunctionArgument >()) override
virtual const FRigVMDispatchFactory * RegisterFactory_NoLock (UScriptStruct *InFactoryStruct) override
virtual void RegisterObjectTypes_NoLock (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses) override
virtual void RegisterPredicate_NoLock (UScriptStruct *InStruct, const TCHAR *InName, const TArray< FRigVMFunctionArgument > &InArguments) override
virtual bool RemoveType_NoLock (const FSoftObjectPath &InObjectPath, const UClass *InObjectClass) override
virtual void Reset_NoLock () override
Protected Member Functions inherited from FRigVMRegistry_NoLock
RIGVM_API FRigVMRegistry_NoLock ()
FRigVMRegistry_NoLock (const FRigVMRegistry_NoLock &)=delete
RIGVM_API void Initialize_NoLock ()
RIGVM_API bool IsAllowedType_NoLock (const FProperty *InProperty) const
RIGVM_API bool IsAllowedType_NoLock (const UClass *InClass) const
RIGVM_API bool IsAllowedType_NoLock (const UEnum *InEnum) const
RIGVM_API bool IsAllowedType_NoLock (const UStruct *InStruct) const
FRigVMRegistry_NoLock & operator= (const FRigVMRegistry_NoLock &InOther)=delete
RIGVM_API void PropagateTypeAddedToCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex)
RIGVM_API void RegisterTypeInCategory_NoLock (const FRigVMTemplateArgument::ETypeCategory InCategory, const TRigVMTypeIndex InTypeIndex)
RIGVM_API void RemoveTypeInCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory, TRigVMTypeIndex InTypeIndex)
Private Member Functions
FRigVMRegistry_RWLock ()
virtual void Initialize (bool bLockRegistry) override
Static Private Member Functions
static void EnsureLocked (ELockType InLockType)
Private Attributes
FRWLock Lock
std::atomic< int32 > LockCount
std::atomic< ELockType > LockType
FOnRigVMRegistryChanged OnRigVMRegistryChangedDelegate
Friends
struct FRigVMDispatchFactory
struct FRigVMFunction
struct FRigVMRegistry_NoLock
struct FRigVMStruct
struct FRigVMTemplate
struct FRigVMTemplateArgument
Additional Inherited Members
Static Public Attributes inherited from FRigVMRegistry_NoLock
static const FLazyName TemplateNameMetaName = FLazyName(TEXT("TemplateName"))
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from FRigVMRegistry_NoLock
static EObjectFlags DisallowedFlags ()
static RIGVM_API bool IsTypeOfByName (const UObject *InObject, const FName &InName)
static EObjectFlags NeededFlags ()
Protected Attributes inherited from FRigVMRegistry_NoLock
TSet< TObjectPtr< const UClass > > AllowedClasses
TSet< TObjectPtr< const UScriptStruct > > AllowedStructs
bool bAvoidTypePropagation
bool bEverRefreshedDispatchFactoriesAfterEngineInit
bool bEverRefreshedEngineTypes
TMap< FName, int32 > DeprecatedTemplateNotationToIndex
TChunkedArray< FRigVMTemplate > DeprecatedTemplates
TArray< FRigVMDispatchFactory * > Factories
TMap< FName, int32 > FunctionNameToIndex
TChunkedArray< FRigVMFunction > Functions
TMap< FName, TArray< FRigVMFunction > > StructNameToPredicates
TMap< FName, int32 > TemplateNotationToIndex
TChunkedArray< FRigVMTemplate > Templates
TMap< FRigVMTemplateArgument::ETypeCategory, TArray< int32 > > TemplatesPerCategory
TArray< FTypeInfo > Types
TMap< FRigVMTemplateArgument::ETypeCategory, TArray< TRigVMTypeIndex > > TypesPerCategory
TMap< FRigVMTemplateArgumentType, TRigVMTypeIndex > TypeToIndex
TMap< FSoftObjectPath, TRigVMTypeIndex > UserDefinedTypeToIndex
Detailed Description
The FRigVMRegistry is used to manage all known function pointers for use in the RigVM.
The Register method is called automatically when the static struct is initially constructed for each USTRUCT hosting a RIGVM_METHOD enabled virtual function.
Inheriting from FGCObject to ensure that all type objects cannot be GCed
Definition at line 442 of file RigVMRegistry.h.
Member Typedef Documentation
Super
typedef FRigVMRegistry_NoLock FRigVMRegistry_RWLock::Super
Definition at line 444 of file RigVMRegistry.h.
Constructor & Destructor Documentation
FRigVMRegistry_RWLock()
FRigVMRegistry_RWLock::FRigVMRegistry_RWLock () private
Referenced by FRigVMRegistry_RWLock::FConditionalReadScopeLock::FConditionalReadScopeLock(), FRigVMRegistry_RWLock::FConditionalReadScopeLock::FConditionalReadScopeLock(), FRigVMRegistry_RWLock::FConditionalScopeLock::FConditionalScopeLock(), FRigVMRegistry_RWLock::FConditionalWriteScopeLock::FConditionalWriteScopeLock(), FRigVMRegistry_RWLock::FConditionalWriteScopeLock::FConditionalWriteScopeLock(), and Get().
Member Function Documentation
AddTemplateFromArguments()
const FRigVMTemplate * FRigVMRegistry_RWLock::AddTemplateFromArguments (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates, bool bLockRegistry = true) inline
Definition at line 840 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::AddTemplateFromArguments_NoLock(), FRigVMTemplate, and InName.
AddTemplateFromArguments_NoLock()
virtual const FRigVMTemplate * FRigVMRegistry_RWLock::AddTemplateFromArguments_NoLock (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1216 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::AddTemplateFromArguments_NoLock(), FRigVMTemplate, and InName.
CanMatchTypes()
bool FRigVMRegistry_RWLock::CanMatchTypes (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts, bool bLockRegistry = true) const inline
Definition at line 759 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::CanMatchTypes_NoLock().
CanMatchTypes_NoLock()
virtual bool FRigVMRegistry_RWLock::CanMatchTypes_NoLock (TRigVMTypeIndex InTypeIndexA, TRigVMTypeIndex InTypeIndexB, bool bAllowFloatingPointCasts) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1136 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::CanMatchTypes_NoLock().
ConvertExecuteContextToBaseType()
bool FRigVMRegistry_RWLock::ConvertExecuteContextToBaseType (TRigVMTypeIndex & InOutTypeIndex, bool bLockRegistry = true) const inline
Definition at line 738 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::ConvertExecuteContextToBaseType_NoLock().
ConvertExecuteContextToBaseType_NoLock()
virtual bool FRigVMRegistry_RWLock::ConvertExecuteContextToBaseType_NoLock (TRigVMTypeIndex & InOutTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1115 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::ConvertExecuteContextToBaseType_NoLock().
EnsureLocked()
void FRigVMRegistry_RWLock::EnsureLocked (ELockType InLockType) static private
FindDispatchFactory()
FRigVMDispatchFactory * FRigVMRegistry_RWLock::FindDispatchFactory (const FName & InFactoryName, bool bLockRegistry = true) const inline
Definition at line 851 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindDispatchFactory_NoLock(), and FRigVMDispatchFactory.
FindDispatchFactory_NoLock()
virtual FRigVMDispatchFactory * FRigVMRegistry_RWLock::FindDispatchFactory_NoLock (const FName & InFactoryName) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1226 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindDispatchFactory_NoLock(), and FRigVMDispatchFactory.
FindFunction() [1/2]
const FRigVMFunction * FRigVMRegistry_RWLock::FindFunction (const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InTypeResolver = FRigVMUserDefinedTypeResolver(), bool bLockRegistry = true) const inline
Definition at line 794 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindFunction_NoLock(), FRigVMFunction, and InName.
FindFunction() [2/2]
const FRigVMFunction * FRigVMRegistry_RWLock::FindFunction (UScriptStruct * InStruct, const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InResolvalInfo = FRigVMUserDefinedTypeResolver(), bool bLockRegistry = true) const inline
Definition at line 801 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindFunction_NoLock(), FRigVMFunction, and InName.
FindFunction_NoLock() [1/2]
virtual const FRigVMFunction * FRigVMRegistry_RWLock::FindFunction_NoLock (const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InTypeResolver = FRigVMUserDefinedTypeResolver()) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1171 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindFunction_NoLock(), FRigVMFunction, and InName.
FindFunction_NoLock() [2/2]
virtual const FRigVMFunction * FRigVMRegistry_RWLock::FindFunction_NoLock (UScriptStruct * InStruct, const TCHAR * InName, const FRigVMUserDefinedTypeResolver & InResolvalInfo = FRigVMUserDefinedTypeResolver()) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1178 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindFunction_NoLock(), FRigVMFunction, and InName.
FindOrAddDispatchFactory() [1/2]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> FRigVMDispatchFactory * FRigVMRegistry_RWLock::FindOrAddDispatchFactory (bool bLockRegistry = true) inline
Definition at line 869 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddDispatchFactory_NoLock(), and FRigVMDispatchFactory.
FindOrAddDispatchFactory() [2/2]
FRigVMDispatchFactory * FRigVMRegistry_RWLock::FindOrAddDispatchFactory (UScriptStruct * InFactoryStruct, bool bLockRegistry = true) inline
Definition at line 858 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddDispatchFactory_NoLock(), and FRigVMDispatchFactory.
FindOrAddDispatchFactory_NoLock()
virtual FRigVMDispatchFactory * FRigVMRegistry_RWLock::FindOrAddDispatchFactory_NoLock (UScriptStruct * InFactoryStruct) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1233 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddDispatchFactory_NoLock(), and FRigVMDispatchFactory.
FindOrAddSingletonDispatchFunction() [1/2]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> FString FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction (bool bLockRegistry = true) inline
Definition at line 887 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddSingletonDispatchFunction_NoLock().
FindOrAddSingletonDispatchFunction() [2/2]
FString FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction (UScriptStruct * InFactoryStruct, bool bLockRegistry = true) inline
Definition at line 876 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddSingletonDispatchFunction_NoLock().
FindOrAddSingletonDispatchFunction_NoLock()
virtual FString FRigVMRegistry_RWLock::FindOrAddSingletonDispatchFunction_NoLock (UScriptStruct * InFactoryStruct) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1240 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddSingletonDispatchFunction_NoLock().
FindOrAddType()
TRigVMTypeIndex FRigVMRegistry_RWLock::FindOrAddType (const FRigVMTemplateArgumentType & InType, bool bForce = false, bool bLockRegistry = true) inline
Definition at line 659 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddType_NoLock().
FindOrAddType_NoLock()
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::FindOrAddType_NoLock (const FRigVMTemplateArgumentType & InType, bool bForce = false) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1044 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindOrAddType_NoLock().
FindTemplate()
const FRigVMTemplate * FRigVMRegistry_RWLock::FindTemplate (const FName & InNotation, bool bIncludeDeprecated = false, bool bLockRegistry = true) const inline
Definition at line 815 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindTemplate_NoLock(), and FRigVMTemplate.
FindTemplate_NoLock()
virtual const FRigVMTemplate * FRigVMRegistry_RWLock::FindTemplate_NoLock (const FName & InNotation, bool bIncludeDeprecated = false) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1192 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindTemplate_NoLock(), and FRigVMTemplate.
FindTypeFromCPPType()
const FRigVMTemplateArgumentType & FRigVMRegistry_RWLock::FindTypeFromCPPType (const FString & InCPPType, bool bLockRegistry = true) const inline
Definition at line 710 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindTypeFromCPPType_NoLock().
FindTypeFromCPPType_NoLock()
virtual const FRigVMTemplateArgumentType & FRigVMRegistry_RWLock::FindTypeFromCPPType_NoLock (const FString & InCPPType) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1087 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::FindTypeFromCPPType_NoLock().
Get() [1/2]
RIGVM_API FRigVMRegistry_RWLock & FRigVMRegistry_RWLock::Get () static
References FRigVMRegistry_RWLock().
Referenced by FRigVMRegistry_RWLock::FConditionalReadScopeLock::FConditionalReadScopeLock(), FRigVMRegistry_RWLock::FConditionalWriteScopeLock::FConditionalWriteScopeLock(), and USTRUCT().
Get() [2/2]
FRigVMRegistry_NoLock & FRigVMRegistry_RWLock::Get (ELockType InLockType) static delete
References FRigVMRegistry_NoLock.
GetArrayDimensionsForType()
int32 FRigVMRegistry_RWLock::GetArrayDimensionsForType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 745 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetArrayDimensionsForType_NoLock().
GetArrayDimensionsForType_NoLock()
virtual int32 FRigVMRegistry_RWLock::GetArrayDimensionsForType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1122 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetArrayDimensionsForType_NoLock().
GetArrayTypeFromBaseTypeIndex()
TRigVMTypeIndex FRigVMRegistry_RWLock::GetArrayTypeFromBaseTypeIndex (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 780 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetArrayTypeFromBaseTypeIndex_NoLock().
GetArrayTypeFromBaseTypeIndex_NoLock()
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::GetArrayTypeFromBaseTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1157 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetArrayTypeFromBaseTypeIndex_NoLock().
GetBaseTypeFromArrayTypeIndex()
TRigVMTypeIndex FRigVMRegistry_RWLock::GetBaseTypeFromArrayTypeIndex (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 787 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetBaseTypeFromArrayTypeIndex_NoLock().
GetBaseTypeFromArrayTypeIndex_NoLock()
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::GetBaseTypeFromArrayTypeIndex_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1164 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetBaseTypeFromArrayTypeIndex_NoLock().
GetCompatibleTypes()
const TArray< TRigVMTypeIndex > & FRigVMRegistry_RWLock::GetCompatibleTypes (TRigVMTypeIndex InTypeIndex) const inline
Definition at line 766 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetCompatibleTypes_NoLock().
GetCompatibleTypes_NoLock()
virtual const TArray< TRigVMTypeIndex > & FRigVMRegistry_RWLock::GetCompatibleTypes_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1143 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetCompatibleTypes_NoLock().
GetFactories()
const TArray< FRigVMDispatchFactory * > & FRigVMRegistry_RWLock::GetFactories (bool bLockRegistry = true) const inline
Definition at line 894 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetFactories_NoLock().
GetFactories_NoLock()
virtual const TArray< FRigVMDispatchFactory * > & FRigVMRegistry_RWLock::GetFactories_NoLock () const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1247 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetFactories_NoLock().
GetForRead()
const FRigVMRegistry_NoLock & FRigVMRegistry_RWLock::GetForRead () static delete
References FRigVMRegistry_NoLock.
GetForWrite()
FRigVMRegistry_NoLock & FRigVMRegistry_RWLock::GetForWrite () static delete
References FRigVMRegistry_NoLock.
GetFunctions()
const TChunkedArray< FRigVMFunction > & FRigVMRegistry_RWLock::GetFunctions (bool bLockRegistry = true) const inline
Definition at line 808 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetFunctions_NoLock().
GetFunctions_NoLock()
virtual const TChunkedArray< FRigVMFunction > & FRigVMRegistry_RWLock::GetFunctions_NoLock () const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1185 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetFunctions_NoLock().
GetHashForEnum()
uint32 FRigVMRegistry_RWLock::GetHashForEnum (const UEnum * InEnum, bool bCheckTypeIndex = true, bool bLockRegistry = true) const inline
Definition at line 926 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForEnum_NoLock().
GetHashForEnum_NoLock()
virtual uint32 FRigVMRegistry_RWLock::GetHashForEnum_NoLock (const UEnum * InEnum, bool bCheckTypeIndex = true) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1279 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForEnum_NoLock().
GetHashForProperty()
uint32 FRigVMRegistry_RWLock::GetHashForProperty (const FProperty * InProperty, bool bLockRegistry = true) const inline
Definition at line 932 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForProperty_NoLock().
GetHashForProperty_NoLock()
virtual uint32 FRigVMRegistry_RWLock::GetHashForProperty_NoLock (const FProperty * InProperty) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1285 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForProperty_NoLock().
GetHashForScriptStruct()
uint32 FRigVMRegistry_RWLock::GetHashForScriptStruct (const UScriptStruct * InScriptStruct, bool bCheckTypeIndex = true, bool bLockRegistry = true) const inline
Definition at line 914 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForScriptStruct_NoLock().
GetHashForScriptStruct_NoLock()
virtual uint32 FRigVMRegistry_RWLock::GetHashForScriptStruct_NoLock (const UScriptStruct * InScriptStruct, bool bCheckTypeIndex = true) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1267 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForScriptStruct_NoLock().
GetHashForStruct()
uint32 FRigVMRegistry_RWLock::GetHashForStruct (const UStruct * InStruct, bool bLockRegistry = true) const inline
Definition at line 920 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForStruct_NoLock().
GetHashForStruct_NoLock()
virtual uint32 FRigVMRegistry_RWLock::GetHashForStruct_NoLock (const UStruct * InStruct) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1273 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForStruct_NoLock().
GetHashForType()
uint32 FRigVMRegistry_RWLock::GetHashForType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 908 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForType_NoLock().
GetHashForType_NoLock()
virtual uint32 FRigVMRegistry_RWLock::GetHashForType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1261 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetHashForType_NoLock().
GetOrAddTemplateFromArguments()
const FRigVMTemplate * FRigVMRegistry_RWLock::GetOrAddTemplateFromArguments (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates, bool bLockRegistry = true) inline
Definition at line 829 of file RigVMRegistry.h.
References FRigVMTemplate, FRigVMRegistry_NoLock::GetOrAddTemplateFromArguments_NoLock(), and InName.
GetOrAddTemplateFromArguments_NoLock()
virtual const FRigVMTemplate * FRigVMRegistry_RWLock::GetOrAddTemplateFromArguments_NoLock (const FName & InName, const TArray< FRigVMTemplateArgumentInfo > & InInfos, const FRigVMTemplateDelegates & InDelegates) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1206 of file RigVMRegistry.h.
References FRigVMTemplate, FRigVMRegistry_NoLock::GetOrAddTemplateFromArguments_NoLock(), and InName.
GetPredicatesForStruct()
const TArray< FRigVMFunction > * FRigVMRegistry_RWLock::GetPredicatesForStruct (const FName & InStructName, bool bLockRegistry = true) const inline
Definition at line 901 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetPredicatesForStruct_NoLock().
GetPredicatesForStruct_NoLock()
virtual const TArray< FRigVMFunction > * FRigVMRegistry_RWLock::GetPredicatesForStruct_NoLock (const FName & InStructName) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1254 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetPredicatesForStruct_NoLock().
GetTemplates()
const TChunkedArray< FRigVMTemplate > & FRigVMRegistry_RWLock::GetTemplates (bool bLockRegistry = true) const inline
Definition at line 822 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTemplates_NoLock().
GetTemplates_NoLock()
virtual const TChunkedArray< FRigVMTemplate > & FRigVMRegistry_RWLock::GetTemplates_NoLock () const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1199 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTemplates_NoLock().
GetType()
const FRigVMTemplateArgumentType & FRigVMRegistry_RWLock::GetType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 696 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetType_NoLock().
Referenced by USTRUCT().
GetType_NoLock()
virtual const FRigVMTemplateArgumentType & FRigVMRegistry_RWLock::GetType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1073 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetType_NoLock().
GetTypeIndex() [1/3]
template<typename T> TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndex (bool bAsArray = false, bool bLockRegistry = true) const inline
Definition at line 689 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndex_NoLock().
GetTypeIndex() [2/3]
TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndex (const FName & InCPPType, UObject * InCPPTypeObject, bool bLockRegistry = true) const inline
Definition at line 681 of file RigVMRegistry.h.
References GetTypeIndex().
GetTypeIndex() [3/3]
TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndex (const FRigVMTemplateArgumentType & InType, bool bLockRegistry = true) const inline
Definition at line 674 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndex_NoLock().
Referenced by GetTypeIndex(), and USTRUCT().
GetTypeIndex_NoLock() [1/2]
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndex_NoLock (const FName & InCPPType, UObject * InCPPTypeObject) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1066 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndex_NoLock().
GetTypeIndex_NoLock() [2/2]
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndex_NoLock (const FRigVMTemplateArgumentType & InType) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1059 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndex_NoLock().
GetTypeIndexFromCPPType()
TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndexFromCPPType (const FString & InCPPType, bool bLockRegistry = true) const inline
Definition at line 717 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndexFromCPPType_NoLock().
GetTypeIndexFromCPPType_NoLock()
virtual TRigVMTypeIndex FRigVMRegistry_RWLock::GetTypeIndexFromCPPType_NoLock (const FString & InCPPType) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1094 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypeIndexFromCPPType_NoLock().
GetTypesForCategory()
const TArray< TRigVMTypeIndex > & FRigVMRegistry_RWLock::GetTypesForCategory (FRigVMTemplateArgument::ETypeCategory InCategory, bool bLockRegistry = true) const inline
Definition at line 773 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypesForCategory_NoLock().
GetTypesForCategory_NoLock()
virtual const TArray< TRigVMTypeIndex > & FRigVMRegistry_RWLock::GetTypesForCategory_NoLock (FRigVMTemplateArgument::ETypeCategory InCategory) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1150 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::GetTypesForCategory_NoLock().
Initialize()
virtual void FRigVMRegistry_RWLock::Initialize (bool bLockRegistry) override private virtual
Implements FRigVMRegistry_NoLock.
IsArrayType()
bool FRigVMRegistry_RWLock::IsArrayType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 724 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsArrayType_NoLock().
IsArrayType_NoLock()
virtual bool FRigVMRegistry_RWLock::IsArrayType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1101 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsArrayType_NoLock().
IsExecuteType()
bool FRigVMRegistry_RWLock::IsExecuteType (TRigVMTypeIndex InTypeIndex, bool bLockRegistry = true) const inline
Definition at line 731 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsExecuteType_NoLock().
IsExecuteType_NoLock()
virtual bool FRigVMRegistry_RWLock::IsExecuteType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1108 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsExecuteType_NoLock().
IsWildCardType()
bool FRigVMRegistry_RWLock::IsWildCardType (TRigVMTypeIndex InTypeIndex) const inline
Definition at line 752 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsWildCardType_NoLock().
IsWildCardType_NoLock()
virtual bool FRigVMRegistry_RWLock::IsWildCardType_NoLock (TRigVMTypeIndex InTypeIndex) const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1129 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::IsWildCardType_NoLock().
NumTypes()
int32 FRigVMRegistry_RWLock::NumTypes (bool bLockRegistry = true) const inline
Definition at line 703 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::NumTypes_NoLock().
NumTypes_NoLock()
virtual int32 FRigVMRegistry_RWLock::NumTypes_NoLock () const inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1080 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::NumTypes_NoLock().
OnAnimationAttributeTypesChanged()
RIGVM_API void FRigVMRegistry_RWLock::OnAnimationAttributeTypesChanged (const UScriptStruct * InStruct, bool bIsAdded)
OnAnimationAttributeTypesChanged_NoLock()
virtual void FRigVMRegistry_RWLock::OnAnimationAttributeTypesChanged_NoLock (const UScriptStruct * InStruct, bool bIsAdded) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1029 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnAnimationAttributeTypesChanged_NoLock().
OnAssetRemoved()
RIGVM_API void FRigVMRegistry_RWLock::OnAssetRemoved (const FAssetData & InAssetData)
OnAssetRemoved_NoLock()
virtual bool FRigVMRegistry_RWLock::OnAssetRemoved_NoLock (const FAssetData & InAssetData) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1007 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnAssetRemoved_NoLock().
OnAssetRenamed()
void FRigVMRegistry_RWLock::OnAssetRenamed (const FAssetData & InAssetData, const FString & InOldObjectPath) inline
Definition at line 628 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnAssetRenamed_NoLock().
OnAssetRenamed_NoLock()
virtual void FRigVMRegistry_RWLock::OnAssetRenamed_NoLock (const FAssetData & InAssetData, const FString & InOldObjectPath) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1000 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnAssetRenamed_NoLock().
OnPluginLoaded()
RIGVM_API void FRigVMRegistry_RWLock::OnPluginLoaded (IPlugin & InPlugin)
OnPluginLoaded_NoLock()
virtual bool FRigVMRegistry_RWLock::OnPluginLoaded_NoLock (IPlugin & InPlugin) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1014 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnPluginLoaded_NoLock().
OnPluginUnloaded()
RIGVM_API void FRigVMRegistry_RWLock::OnPluginUnloaded (IPlugin & InPlugin)
OnPluginUnloaded_NoLock()
virtual bool FRigVMRegistry_RWLock::OnPluginUnloaded_NoLock (IPlugin & InPlugin) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1021 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::OnPluginUnloaded_NoLock().
OnRigVMRegistryChanged()
FOnRigVMRegistryChanged & FRigVMRegistry_RWLock::OnRigVMRegistryChanged () inline
Definition at line 648 of file RigVMRegistry.h.
References OnRigVMRegistryChangedDelegate.
RebuildRegistry()
void FRigVMRegistry_RWLock::RebuildRegistry (bool bLockRegistry = true) inline
Definition at line 938 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RebuildRegistry_NoLock().
RebuildRegistry_NoLock()
virtual void FRigVMRegistry_RWLock::RebuildRegistry_NoLock () inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1291 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RebuildRegistry_NoLock().
RefreshEngineTypes()
void FRigVMRegistry_RWLock::RefreshEngineTypes () inline
Definition at line 606 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshEngineTypes_NoLock().
RefreshEngineTypes_NoLock()
virtual void FRigVMRegistry_RWLock::RefreshEngineTypes_NoLock () inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 979 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshEngineTypes_NoLock().
RefreshEngineTypesIfRequired()
void FRigVMRegistry_RWLock::RefreshEngineTypesIfRequired (bool bLockRegistry = true) inline
Definition at line 614 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshEngineTypesIfRequired_NoLock().
RefreshEngineTypesIfRequired_NoLock()
virtual void FRigVMRegistry_RWLock::RefreshEngineTypesIfRequired_NoLock () inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 993 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshEngineTypesIfRequired_NoLock().
RefreshFunctionsAndDispatches()
bool FRigVMRegistry_RWLock::RefreshFunctionsAndDispatches () inline
Definition at line 621 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshFunctionsAndDispatches_NoLock().
RefreshFunctionsAndDispatches_NoLock()
virtual bool FRigVMRegistry_RWLock::RefreshFunctionsAndDispatches_NoLock () inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 985 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RefreshFunctionsAndDispatches_NoLock().
Register()
void FRigVMRegistry_RWLock::Register (const TCHAR * InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct * InStruct = nullptr, const TArray< FRigVMFunctionArgument > & InArguments = TArray<FRigVMFunctionArgument>(), bool bLockRegistry = true) inline
Definition at line 570 of file RigVMRegistry.h.
References InName, and FRigVMRegistry_NoLock::Register_NoLock().
Register_NoLock()
virtual void FRigVMRegistry_RWLock::Register_NoLock (const TCHAR * InName, FRigVMFunctionPtr InFunctionPtr, UScriptStruct * InStruct = nullptr, const TArray< FRigVMFunctionArgument > & InArguments = TArray<FRigVMFunctionArgument>()) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 950 of file RigVMRegistry.h.
References InName, and FRigVMRegistry_NoLock::Register_NoLock().
RegisterFactory()
const FRigVMDispatchFactory * FRigVMRegistry_RWLock::RegisterFactory (UScriptStruct * InFactoryStruct, bool bLockRegistry = true) inline
Definition at line 577 of file RigVMRegistry.h.
References FRigVMDispatchFactory, and FRigVMRegistry_NoLock::RegisterFactory_NoLock().
RegisterFactory_NoLock()
virtual const FRigVMDispatchFactory * FRigVMRegistry_RWLock::RegisterFactory_NoLock (UScriptStruct * InFactoryStruct) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 957 of file RigVMRegistry.h.
References FRigVMDispatchFactory, and FRigVMRegistry_NoLock::RegisterFactory_NoLock().
RegisterObjectTypes()
void FRigVMRegistry_RWLock::RegisterObjectTypes (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses, bool bLockRegistry = true) inline
Definition at line 591 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RegisterObjectTypes_NoLock().
RegisterObjectTypes_NoLock()
virtual void FRigVMRegistry_RWLock::RegisterObjectTypes_NoLock (TConstArrayView< TPair< UClass *, ERegisterObjectOperation > > InClasses) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 971 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RegisterObjectTypes_NoLock().
RegisterPredicate()
void FRigVMRegistry_RWLock::RegisterPredicate (UScriptStruct * InStruct, const TCHAR * InName, const TArray< FRigVMFunctionArgument > & InArguments, bool bLockRegistry = true) inline
Definition at line 584 of file RigVMRegistry.h.
References InName, and FRigVMRegistry_NoLock::RegisterPredicate_NoLock().
RegisterPredicate_NoLock()
virtual void FRigVMRegistry_RWLock::RegisterPredicate_NoLock (UScriptStruct * InStruct, const TCHAR * InName, const TArray< FRigVMFunctionArgument > & InArguments) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 964 of file RigVMRegistry.h.
References InName, and FRigVMRegistry_NoLock::RegisterPredicate_NoLock().
RegisterStructTypes()
void FRigVMRegistry_RWLock::RegisterStructTypes (TConstArrayView< UScriptStruct * > InStructs, bool bLockRegistry = true) inline
Definition at line 598 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RegisterStructTypes_NoLock().
RemoveType()
bool FRigVMRegistry_RWLock::RemoveType (const FSoftObjectPath & InObjectPath, const UClass * InObjectClass, bool bLockRegistry = true) inline
Definition at line 667 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RemoveType_NoLock().
RemoveType_NoLock()
virtual bool FRigVMRegistry_RWLock::RemoveType_NoLock (const FSoftObjectPath & InObjectPath, const UClass * InObjectClass) inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1052 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::RemoveType_NoLock().
Reset()
void FRigVMRegistry_RWLock::Reset (bool bLockRegistry = true) inline
Definition at line 651 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::Reset_NoLock().
Reset_NoLock()
virtual void FRigVMRegistry_RWLock::Reset_NoLock () inline override protected virtual
Reimplemented from FRigVMRegistry_NoLock.
Definition at line 1036 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock::Reset_NoLock().
Friends And Related Symbol Documentation
FRigVMDispatchFactory
friend struct FRigVMDispatchFactory friend
Definition at line 1316 of file RigVMRegistry.h.
References FRigVMDispatchFactory.
Referenced by FindDispatchFactory(), FindDispatchFactory_NoLock(), FindOrAddDispatchFactory(), FindOrAddDispatchFactory(), FindOrAddDispatchFactory_NoLock(), FRigVMDispatchFactory, RegisterFactory(), and RegisterFactory_NoLock().
FRigVMFunction
friend struct FRigVMFunction friend
Definition at line 1314 of file RigVMRegistry.h.
References FRigVMFunction.
Referenced by FindFunction(), FindFunction(), FindFunction_NoLock(), FindFunction_NoLock(), and FRigVMFunction.
FRigVMRegistry_NoLock
friend struct FRigVMRegistry_NoLock friend
Definition at line 1317 of file RigVMRegistry.h.
References FRigVMRegistry_NoLock.
Referenced by FRigVMRegistry_NoLock, Get(), GetForRead(), GetForWrite(), FRigVMRegistry_RWLock::FConditionalScopeLock::GetRegistry(), and FRigVMRegistry_RWLock::FConditionalScopeLock::GetRegistry().
FRigVMStruct
friend struct FRigVMStruct friend
Definition at line 1312 of file RigVMRegistry.h.
References FRigVMStruct.
Referenced by FRigVMStruct.
FRigVMTemplate
friend struct FRigVMTemplate friend
Definition at line 1313 of file RigVMRegistry.h.
References FRigVMTemplate.
Referenced by AddTemplateFromArguments(), AddTemplateFromArguments_NoLock(), FindTemplate(), FindTemplate_NoLock(), FRigVMTemplate, GetOrAddTemplateFromArguments(), and GetOrAddTemplateFromArguments_NoLock().
FRigVMTemplateArgument
friend struct FRigVMTemplateArgument friend
Definition at line 1315 of file RigVMRegistry.h.
References FRigVMTemplateArgument.
Referenced by FRigVMTemplateArgument.
Field Documentation
Lock
FRWLock FRigVMRegistry_RWLock::Lock mutable private
Definition at line 1305 of file RigVMRegistry.h.
LockCount
std::atomic<int32> FRigVMRegistry_RWLock::LockCount mutable private
Definition at line 1307 of file RigVMRegistry.h.
LockType
std::atomic<ELockType> FRigVMRegistry_RWLock::LockType mutable private
Definition at line 1306 of file RigVMRegistry.h.
OnRigVMRegistryChangedDelegate
FOnRigVMRegistryChanged FRigVMRegistry_RWLock::OnRigVMRegistryChangedDelegate private
Definition at line 1310 of file RigVMRegistry.h.
Referenced by OnRigVMRegistryChanged().
The documentation for this struct was generated from the following file:
RigVMRegistry.h