Unreal Engine 5.6 C++ API: UE::Geometry::FUVPacker Class Reference
UE::Geometry::FUVPacker Class Reference
FUVPacker implements various strategies for packing UV islands in a generic mesh class.
#include "UVPacking.h"
Data Structures
struct IUVMeshView
Public Member Functions
bool StackPack (IUVMeshView *Mesh, const TArray< TArray< int > > &UVIslands)
Version of StackPack that takes an array of arrays instead of a TFunctionRef, for convenience.
GEOMETRYCORE_API bool StackPack (IUVMeshView *Mesh, int NumIslands, TFunctionRef< void(int, TArray< int32 > &)> CopyIsland)
Uniformly scale all UV islands so that the largest fits in positive-unit-square, and translate each islands separately so that it's bbox-min is at the origin.
bool StandardPack (IUVMeshView *Mesh, const TArray< TArray< int > > &UVIslands)
Version of StandardPack that takes an array of arrays instead of a TFunctionRef, for convenience.
GEOMETRYCORE_API bool StandardPack (IUVMeshView *Mesh, int NumIslands, TFunctionRef< void(int, TArray< int32 > &)> CopyIsland)
Standard UE UV layout, similar to that used for Lightmap UVs.
Data Fields
bool bAllowFlips = false
If true, islands can be flipped in addition to rotate/translate/scale.
bool bPreserveRotation = false
If true, original island rotation is maintained during any packing process.
bool bPreserveScale = false
If true, original island scale is maintained during any packing process.
bool bScaleIslandsByWorldSpaceTexelRatio = false
Attempt to rescale islands to match texel-to-world-space ratio across islands, based on ratio of World- and UV-space edge lengths.
float GutterSize = 1.0
Thickness of gutter/border in pixel dimensions.
int32 TextureResolution = 512
Resolution of the target texture.
Protected Member Functions
GEOMETRYCORE_API void GetIslandStats (IUVMeshView *Mesh, const TArray< int32 > &Island, FAxisAlignedBox2d &IslandBoundsOut, double &IslandScaleFactorOut, double &UVAreaOut)
Compute common stats used by the packing algorithms to transform UV islands.
Detailed Description
FUVPacker implements various strategies for packing UV islands in a generic mesh class.
The UV islands must already be identified, this class simply scales/rotates/translates the islands to fit.
Definition at line 24 of file UVPacking.h.
Member Function Documentation
GetIslandStats()
GEOMETRYCORE_API void UE::Geometry::FUVPacker::GetIslandStats (IUVMeshView * Mesh, const TArray< int32 > & Island, FAxisAlignedBox2d & IslandBoundsOut, double & IslandScaleFactorOut, double & UVAreaOut) protected
Compute common stats used by the packing algorithms to transform UV islands.
References UE::Geometry::Mesh.
StackPack() [1/2]
bool UE::Geometry::FUVPacker::StackPack (IUVMeshView * Mesh, const TArray< TArray< int > > & UVIslands) inline
Version of StackPack that takes an array of arrays instead of a TFunctionRef, for convenience.
Definition at line 82 of file UVPacking.h.
References UE::Geometry::Mesh, StackPack(), and UE::Geometry::UVIslands.
StackPack() [2/2]
GEOMETRYCORE_API bool UE::Geometry::FUVPacker::StackPack (IUVMeshView * Mesh, int NumIslands, TFunctionRef< void(int, TArray< int32 > &)> CopyIsland)
Uniformly scale all UV islands so that the largest fits in positive-unit-square, and translate each islands separately so that it's bbox-min is at the origin.
So the islands are "stacked" and all fit in the unit box.
References UE::Geometry::Mesh.
Referenced by StackPack().
StandardPack() [1/2]
bool UE::Geometry::FUVPacker::StandardPack (IUVMeshView * Mesh, const TArray< TArray< int > > & UVIslands) inline
Version of StandardPack that takes an array of arrays instead of a TFunctionRef, for convenience.
Definition at line 66 of file UVPacking.h.
References UE::Geometry::Mesh, StandardPack(), and UE::Geometry::UVIslands.
StandardPack() [2/2]
GEOMETRYCORE_API bool UE::Geometry::FUVPacker::StandardPack (IUVMeshView * Mesh, int NumIslands, TFunctionRef< void(int, TArray< int32 > &)> CopyIsland)
Standard UE UV layout, similar to that used for Lightmap UVs.
All UV islands are packed into standard positive-unit-square. Only supports single-pixel border size.
References UE::Geometry::Mesh.
Referenced by StandardPack().
Field Documentation
bAllowFlips
bool UE::Geometry::FUVPacker::bAllowFlips = false
If true, islands can be flipped in addition to rotate/translate/scale.
Definition at line 53 of file UVPacking.h.
bPreserveRotation
bool UE::Geometry::FUVPacker::bPreserveRotation = false
If true, original island rotation is maintained during any packing process.
Automatically prevents bAllowFlips from applying, if set.
Definition at line 50 of file UVPacking.h.
bPreserveScale
bool UE::Geometry::FUVPacker::bPreserveScale = false
If true, original island scale is maintained during any packing process.
Definition at line 47 of file UVPacking.h.
bScaleIslandsByWorldSpaceTexelRatio
bool UE::Geometry::FUVPacker::bScaleIslandsByWorldSpaceTexelRatio = false
Attempt to rescale islands to match texel-to-world-space ratio across islands, based on ratio of World- and UV-space edge lengths.
Definition at line 56 of file UVPacking.h.
GutterSize
float UE::Geometry::FUVPacker::GutterSize = 1.0
Thickness of gutter/border in pixel dimensions.
Not supported by all packing methods
Definition at line 44 of file UVPacking.h.
TextureResolution
int32 UE::Geometry::FUVPacker::TextureResolution = 512
Resolution of the target texture.
This is used to convert pixel gutter/border thickness to UV space
Definition at line 41 of file UVPacking.h.
The documentation for this class was generated from the following file:
UVPacking.h