Unreal Engine 5.6 C++ API: FSkeletalMeshImportData Class Reference
FSkeletalMeshImportData Class Reference
Container and importer for skeletal mesh (FBX file) data.
#include "SkeletalMeshLODImporterData.h"
Public Member Functions
FSkeletalMeshImportData ()
void AddMorphTarget (FName InMorphTargetName, const FMorphTargetLODModel &InMorphTargetModel, const TArray< uint32 > &InVertexMap)
void AddSkinWeightProfile (FName InProfileName, const FImportedSkinWeightProfileData &InProfileData, const TArray< int32 > &InVertexMap, const TArray< FBoneIndexType > &InBoneIndexMap)
bool ApplyRigToGeo (FSkeletalMeshImportData &Other)
void ComputeSmoothGroupFromNormals ()
void CopyDataNeedByMorphTargetImport (FSkeletalMeshImportData &Other) const
void CopyLODImportData (TArray< FVector3f > &LODPoints, TArray< SkeletalMeshImportData::FMeshWedge > &LODWedges, TArray< SkeletalMeshImportData::FMeshFace > &LODFaces, TArray< SkeletalMeshImportData::FVertInfluence > &LODInfluences, TArray< int32 > &LODPointToRawMap) const
Copy mesh data for importing a single LOD.
void Empty ()
Removes all import data.
bool GetMeshDescription (const USkeletalMesh *InSkeletalMesh, const FSkeletalMeshBuildSettings *InBuildSettings, FMeshDescription &OutMeshDescription) const
Returns a mesh description from the import data.
void KeepAlternateSkinningBuildDataOnly ()
Static Public Member Functions
static FSkeletalMeshImportData CreateFromMeshDescription (const FMeshDescription &InMeshDescription)
static FString FixupBoneName (FString InBoneName)
static bool ReplaceSkeletalMeshGeometryImportData (const USkeletalMesh *SkeletalMesh, FSkeletalMeshImportData *ImportData, int32 LodIndex)
static bool ReplaceSkeletalMeshRigImportData (const USkeletalMesh *SkeletalMesh, FSkeletalMeshImportData *ImportData, int32 LodIndex)
Data Fields
TArray< FString > AlternateInfluenceProfileNames
TArray< FSkeletalMeshImportData > AlternateInfluences
bool bHasNormals
bool bHasTangents
bool bHasVertexColors
TArray< SkeletalMeshImportData::FTriangle > Faces
TArray< SkeletalMeshImportData::FRawBoneInfluence > Influences
TArray< SkeletalMeshImportData::FMaterial > Materials
uint32 MaxMaterialIndex
TArray< SkeletalMeshImportData::FMeshInfo > MeshInfos
TArray< TSet< uint32 > > MorphTargetModifiedPoints
TArray< FString > MorphTargetNames
TArray< FSkeletalMeshImportData > MorphTargets
uint32 NumTexCoords
TArray< FVector3f > Points
TArray< int32 > PointToRawMap
TArray< SkeletalMeshImportData::FBone > RefBonesBinary
TArray< FString > VertexAttributeNames
TArray< SkeletalMeshImportData::FVertexAttribute > VertexAttributes
TArray< SkeletalMeshImportData::FVertex > Wedges
Private Member Functions
void CleanUpUnusedMaterials ()
void CopySkinWeightsToMeshDescription (const USkeletalMesh *InSkeletalMesh, const FName InSkinWeightName, const FSkeletalMeshImportData &InSkinWeightMesh, const TArray< FVertexID > &InVertexIDMap, FMeshDescription &OutMeshDescription) const
void SplitVerticesBySmoothingGroups ()
Friends
FArchive & operator<< (FArchive &Ar, FSkeletalMeshImportData &RawMesh)
Detailed Description
Container and importer for skeletal mesh (FBX file) data.
Definition at line 327 of file SkeletalMeshLODImporterData.h.
Constructor & Destructor Documentation
FSkeletalMeshImportData()
FSkeletalMeshImportData::FSkeletalMeshImportData () inline
Definition at line 358 of file SkeletalMeshLODImporterData.h.
References bHasNormals, bHasTangents, bHasVertexColors, MaxMaterialIndex, and NumTexCoords.
Referenced by ApplyRigToGeo(), CopyDataNeedByMorphTargetImport(), CopySkinWeightsToMeshDescription(), CreateFromMeshDescription(), operator<<, ReplaceSkeletalMeshGeometryImportData(), and ReplaceSkeletalMeshRigImportData().
Member Function Documentation
AddMorphTarget()
void FSkeletalMeshImportData::AddMorphTarget (FName InMorphTargetName, const FMorphTargetLODModel & InMorphTargetModel, const TArray< uint32 > & InVertexMap)
AddSkinWeightProfile()
void FSkeletalMeshImportData::AddSkinWeightProfile (FName InProfileName, const FImportedSkinWeightProfileData & InProfileData, const TArray< int32 > & InVertexMap, const TArray< FBoneIndexType > & InBoneIndexMap)
ApplyRigToGeo()
bool FSkeletalMeshImportData::ApplyRigToGeo (FSkeletalMeshImportData & Other)
References FSkeletalMeshImportData(), and Other.
CleanUpUnusedMaterials()
void FSkeletalMeshImportData::CleanUpUnusedMaterials () private
ComputeSmoothGroupFromNormals()
void FSkeletalMeshImportData::ComputeSmoothGroupFromNormals ()
CopyDataNeedByMorphTargetImport()
void FSkeletalMeshImportData::CopyDataNeedByMorphTargetImport (FSkeletalMeshImportData & Other) const
References FSkeletalMeshImportData(), and Other.
CopyLODImportData()
void FSkeletalMeshImportData::CopyLODImportData (TArray< FVector3f > & LODPoints, TArray< SkeletalMeshImportData::FMeshWedge > & LODWedges, TArray< SkeletalMeshImportData::FMeshFace > & LODFaces, TArray< SkeletalMeshImportData::FVertInfluence > & LODInfluences, TArray< int32 > & LODPointToRawMap) const
Copy mesh data for importing a single LOD.
Parameters
LODPoints - vertex data.
LODWedges - wedge information to static LOD level.
LODFaces - triangle/ face data to static LOD level.
LODInfluences - weights/ influences to static LOD level.
CopySkinWeightsToMeshDescription()
void FSkeletalMeshImportData::CopySkinWeightsToMeshDescription (const USkeletalMesh * InSkeletalMesh, const FName InSkinWeightName, const FSkeletalMeshImportData & InSkinWeightMesh, const TArray< FVertexID > & InVertexIDMap, FMeshDescription & OutMeshDescription) const private
References FSkeletalMeshImportData().
CreateFromMeshDescription()
FSkeletalMeshImportData FSkeletalMeshImportData::CreateFromMeshDescription (const FMeshDescription & InMeshDescription) static
Note
MeshDescription always contains color, normal and tangent data by default. Therefore, while iterating over the vertices, we check if at least one normal/tangent vector is not a zero vector and the vertex color is not pure white, then we set the corresponding bHasNormals/bHasTangent/bHasVertexColors flags to true.
References FSkeletalMeshImportData().
Empty()
void FSkeletalMeshImportData::Empty () inline
Removes all import data.
Definition at line 399 of file SkeletalMeshLODImporterData.h.
References Faces, Influences, Materials, MeshInfos, Points, PointToRawMap, RefBonesBinary, and Wedges.
FixupBoneName()
FString FSkeletalMeshImportData::FixupBoneName (FString InBoneName) static
GetMeshDescription()
bool FSkeletalMeshImportData::GetMeshDescription (const USkeletalMesh * InSkeletalMesh, const FSkeletalMeshBuildSettings * InBuildSettings, FMeshDescription & OutMeshDescription) const
Returns a mesh description from the import data.
If logging on failures is required, pass in a pointer to the owning skeletal mesh. Otherwise, leave as a nullptr.
KeepAlternateSkinningBuildDataOnly()
void FSkeletalMeshImportData::KeepAlternateSkinningBuildDataOnly ()
ReplaceSkeletalMeshGeometryImportData()
bool FSkeletalMeshImportData::ReplaceSkeletalMeshGeometryImportData (const USkeletalMesh * SkeletalMesh, FSkeletalMeshImportData * ImportData, int32 LodIndex) static
References FSkeletalMeshImportData(), and SkeletalMesh.
ReplaceSkeletalMeshRigImportData()
bool FSkeletalMeshImportData::ReplaceSkeletalMeshRigImportData (const USkeletalMesh * SkeletalMesh, FSkeletalMeshImportData * ImportData, int32 LodIndex) static
References FSkeletalMeshImportData(), and SkeletalMesh.
SplitVerticesBySmoothingGroups()
void FSkeletalMeshImportData::SplitVerticesBySmoothingGroups () private
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FSkeletalMeshImportData & RawMesh) friend
References FSkeletalMeshImportData(), and Ar.
Field Documentation
AlternateInfluenceProfileNames
TArray<FString> FSkeletalMeshImportData::AlternateInfluenceProfileNames
Definition at line 351 of file SkeletalMeshLODImporterData.h.
AlternateInfluences
TArray<FSkeletalMeshImportData> FSkeletalMeshImportData::AlternateInfluences
Definition at line 350 of file SkeletalMeshLODImporterData.h.
bHasNormals
bool FSkeletalMeshImportData::bHasNormals
Definition at line 341 of file SkeletalMeshLODImporterData.h.
Referenced by FSkeletalMeshImportData().
bHasTangents
bool FSkeletalMeshImportData::bHasTangents
Definition at line 342 of file SkeletalMeshLODImporterData.h.
Referenced by FSkeletalMeshImportData().
bHasVertexColors
bool FSkeletalMeshImportData::bHasVertexColors
Definition at line 340 of file SkeletalMeshLODImporterData.h.
Referenced by FSkeletalMeshImportData().
Faces
TArray<SkeletalMeshImportData::FTriangle> FSkeletalMeshImportData::Faces
Definition at line 333 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
Influences
TArray<SkeletalMeshImportData::FRawBoneInfluence> FSkeletalMeshImportData::Influences
Definition at line 335 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
Materials
TArray<SkeletalMeshImportData::FMaterial> FSkeletalMeshImportData::Materials
Definition at line 330 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
MaxMaterialIndex
uint32 FSkeletalMeshImportData::MaxMaterialIndex
Definition at line 339 of file SkeletalMeshLODImporterData.h.
Referenced by FSkeletalMeshImportData().
MeshInfos
TArray<SkeletalMeshImportData::FMeshInfo> FSkeletalMeshImportData::MeshInfos
Definition at line 336 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
MorphTargetModifiedPoints
TArray<TSet<uint32> > FSkeletalMeshImportData::MorphTargetModifiedPoints
Definition at line 346 of file SkeletalMeshLODImporterData.h.
MorphTargetNames
TArray<FString> FSkeletalMeshImportData::MorphTargetNames
Definition at line 347 of file SkeletalMeshLODImporterData.h.
MorphTargets
TArray<FSkeletalMeshImportData> FSkeletalMeshImportData::MorphTargets
Definition at line 345 of file SkeletalMeshLODImporterData.h.
NumTexCoords
uint32 FSkeletalMeshImportData::NumTexCoords
Definition at line 338 of file SkeletalMeshLODImporterData.h.
Referenced by FSkeletalMeshImportData().
Points
TArray<FVector3f> FSkeletalMeshImportData::Points
Definition at line 331 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
PointToRawMap
TArray<int32> FSkeletalMeshImportData::PointToRawMap
Definition at line 337 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
RefBonesBinary
TArray<SkeletalMeshImportData::FBone> FSkeletalMeshImportData::RefBonesBinary
Definition at line 334 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
VertexAttributeNames
TArray<FString> FSkeletalMeshImportData::VertexAttributeNames
Definition at line 354 of file SkeletalMeshLODImporterData.h.
VertexAttributes
TArray<SkeletalMeshImportData::FVertexAttribute> FSkeletalMeshImportData::VertexAttributes
Definition at line 353 of file SkeletalMeshLODImporterData.h.
Wedges
TArray<SkeletalMeshImportData::FVertex> FSkeletalMeshImportData::Wedges
Definition at line 332 of file SkeletalMeshLODImporterData.h.
Referenced by Empty().
The documentation for this class was generated from the following file:
SkeletalMeshLODImporterData.h