Unreal Engine 5.6 C++ API: Metasound::IOperator Class Reference
Metasound::IOperator Class Reference abstract
IOperator.
#include "MetasoundOperatorInterface.h"
Data Structures
struct FResetParams
FResetOperatorParams holds the parameters provided to an IOperator's reset function.
Public Types
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
virtual ~IOperator ()
virtual void METASOUNDGRAPHCORE_API BindInputs (FInputVertexInterfaceData &InVertexData)
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void METASOUNDGRAPHCORE_API BindOutputs (FOutputVertexInterfaceData &InVertexData)
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual FExecuteFunction GetExecuteFunction ()=0
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction ()=0
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction ()=0
Return the reset function to call during graph execution.
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Detailed Description
IOperator.
IOperator defines the interface for render time operations. IOperators are created using an INodeOperatorFactory.
Definition at line 15 of file MetasoundOperatorInterface.h.
Member Typedef Documentation
FExecuteFunction
using Metasound::IOperator::FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
Parameters
IOperator* - The operator associated with the function pointer.
Definition at line 159 of file MetasoundOperatorInterface.h.
FPostExecuteFunction
using Metasound::IOperator::FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
Parameters
IOperator* - The operator associated with the function pointer.
Definition at line 175 of file MetasoundOperatorInterface.h.
FResetFunction
using Metasound::IOperator::FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Parameters
IOperator* - The operator associated with the function pointer.
Definition at line 143 of file MetasoundOperatorInterface.h.
Constructor & Destructor Documentation
~IOperator()
virtual Metasound::IOperator::~IOperator () inline virtual
Definition at line 33 of file MetasoundOperatorInterface.h.
Member Function Documentation
BindInputs()
virtual void METASOUNDGRAPHCORE_API Metasound::IOperator::BindInputs (FInputVertexInterfaceData & InVertexData) virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented in HarmonixMetasound::Nodes::MetronomeNode::FMetronomeOperatorBase, Metasound::FExecuter, Metasound::FGraphOperator, Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase, Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableOperator< DataType >, Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >, Metasound::SendNodePrivate::TSendOperator< TDataType >, Metasound::TArrayConcatOperator< ArrayType >, Metasound::TArrayGetOperator< ArrayType >, Metasound::TArrayLastIndexOperator< ArrayType >, Metasound::TArrayNumOperator< ArrayType >, Metasound::TArrayRandomGetOperator< ArrayType >, Metasound::TArraySetOperator< ArrayType >, Metasound::TArrayShuffleOperator< ArrayType >, Metasound::TArraySubsetOperator< ArrayType >, and Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator.
References BindInputs().
Referenced by BindInputs().
BindOutputs()
virtual void METASOUNDGRAPHCORE_API Metasound::IOperator::BindOutputs (FOutputVertexInterfaceData & InVertexData) virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented in HarmonixMetasound::Nodes::MetronomeNode::FMetronomeOperatorBase, Metasound::FExecuter, Metasound::FGraphOperator, Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase, Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableOperator< DataType >, Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >, Metasound::SendNodePrivate::TSendOperator< TDataType >, Metasound::TArrayConcatOperator< ArrayType >, Metasound::TArrayGetOperator< ArrayType >, Metasound::TArrayLastIndexOperator< ArrayType >, Metasound::TArrayNumOperator< ArrayType >, Metasound::TArrayRandomGetOperator< ArrayType >, Metasound::TArraySetOperator< ArrayType >, Metasound::TArrayShuffleOperator< ArrayType >, Metasound::TArraySubsetOperator< ArrayType >, and Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator.
References BindOutputs().
Referenced by BindOutputs().
GetExecuteFunction()
virtual FExecuteFunction Metasound::IOperator::GetExecuteFunction () pure virtual
Return the execution function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be executed.
Implemented in Metasound::FExecuter, Metasound::FNoOpOperator, Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase, Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >, Metasound::TExecutableOperator< DerivedOperatorType >, Metasound::TExecutableOperator< FConverterOperator >, Metasound::TExecutableOperator< FGraphOperator >, Metasound::TExecutableOperator< FMetronomeOperatorBase >, Metasound::TExecutableOperator< TArrayConcatOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayLastIndexOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayNumOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayRandomGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayShuffleOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySubsetOperator< ArrayType > >, Metasound::TExecutableOperator< TReceiverOperator< TDataType > >, and Metasound::TExecutableOperator< TSendOperator< TDataType > >.
References GetExecuteFunction().
Referenced by GetExecuteFunction().
GetPostExecuteFunction()
virtual FPostExecuteFunction Metasound::IOperator::GetPostExecuteFunction () pure virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Implemented in Metasound::FExecuter, Metasound::FGraphOperator, Metasound::FNoOpOperator, Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase, Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >, Metasound::TExecutableOperator< DerivedOperatorType >, Metasound::TExecutableOperator< FConverterOperator >, Metasound::TExecutableOperator< FGraphOperator >, Metasound::TExecutableOperator< FMetronomeOperatorBase >, Metasound::TExecutableOperator< TArrayConcatOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayLastIndexOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayNumOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayRandomGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayShuffleOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySubsetOperator< ArrayType > >, Metasound::TExecutableOperator< TReceiverOperator< TDataType > >, and Metasound::TExecutableOperator< TSendOperator< TDataType > >.
References GetPostExecuteFunction().
Referenced by GetPostExecuteFunction().
GetResetFunction()
virtual FResetFunction Metasound::IOperator::GetResetFunction () pure virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Implemented in Metasound::FExecuter, Metasound::FNoOpOperator, Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase, Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >, Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >, Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >, Metasound::TExecutableOperator< DerivedOperatorType >, Metasound::TExecutableOperator< FConverterOperator >, Metasound::TExecutableOperator< FGraphOperator >, Metasound::TExecutableOperator< FMetronomeOperatorBase >, Metasound::TExecutableOperator< TArrayConcatOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayLastIndexOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayNumOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayRandomGetOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySetOperator< ArrayType > >, Metasound::TExecutableOperator< TArrayShuffleOperator< ArrayType > >, Metasound::TExecutableOperator< TArraySubsetOperator< ArrayType > >, Metasound::TExecutableOperator< TReceiverOperator< TDataType > >, and Metasound::TExecutableOperator< TSendOperator< TDataType > >.
References GetResetFunction().
Referenced by GetResetFunction().
UE_DEPRECATED() [1/3]
Metasound::IOperator::UE_DEPRECATED (5. 3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") const &
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
Please update your code by removing the implementation to Bind(...) and implementing BindOutputs(...). In future releases, the Bind(...) virtual method will be removed.
Note: IOperators which do not correctly implement BindInputs(...) and BindOutputs(...) will not function correctly with MetaSound operator caching and live auditioning in the MetaSound Builder BP API.
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
Metasound::IOperator::UE_DEPRECATED (5. 3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") const
GetInputs() has been deprecated in favor of BindInputs(...).
Please update your code by removing the implementation to GetInputs() and implementing BindInputs(...). In future releases, the GetInputs() virtual method will be removed.
Note: IOperators which do not correctly implement BindInputs(...) and BindOutputs(...) will not function correctly with MetaSound operator caching and live auditioning in the MetaSound Builder BP API.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
Metasound::IOperator::UE_DEPRECATED (5. 3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Please update your code by removing the implementation to GetOutputs() and implementing BindOutputs(...). In future releases, the GetOutputs() virtual method will be removed.
Note: IOperators which do not correctly implement BindInputs(...) and BindOutputs(...) will not function correctly with MetaSound operator caching and live auditioning in the MetaSound Builder BP API.
References UE_DEPRECATED().
The documentation for this class was generated from the following file:
MetasoundOperatorInterface.h