Unreal Engine 5.6 C++ API: FMovieSceneClipboardKey Class Reference
FMovieSceneClipboardKey Class Reference
A key in the clipboard representing a time and a value of a specific type Client code must define MovieSceneClipboard::GetKeyTypeName<> in order to use a type with this class.
#include "MovieSceneClipboard.h"
Data Structures
struct IKey
Abstract base class for all key types.
struct TKey
Implementation of any key-value type.
Public Member Functions
MOVIESCENE_API FMovieSceneClipboardKey (const FMovieSceneClipboardKey &In)
Copy construction/assignment.
template<typename T>
FMovieSceneClipboardKey (FFrameNumber InTime, T InValue)
Templated constructor accepting a specific value type.
MOVIESCENE_API FFrameNumber GetTime () const
Get the time at which this key is defined.
template<typename T>
T GetValue () const
Get the value of this key as the specified type.
MOVIESCENE_API FMovieSceneClipboardKey & operator= (const FMovieSceneClipboardKey &In)
MOVIESCENE_API void SetTime (FFrameNumber InTime)
Set the time at which this key is defined.
template<typename T>
bool TryGetValue (T &Value) const
Attempt to get the value of this key as the specified type.
Static Public Member Functions
template<typename FromType, typename ToType>
static void DefineConversion (TFunction< ToType(const FromType &)> InFunction)
Define a conversion from one type to another type.
Private Types
typedef TFunction< FMovieSceneClipboardKey(const FMovieSceneClipboardKey &)> FConversionFunction
Private Attributes
TInlineValue< IKey, 64 > Data
Type-erased bytes containing the key's value.
FFrameNumber Time
The time that this key is defined at.
Static Private Attributes
static MOVIESCENE_API TMap< FName, TMap< FName, FConversionFunction > > ConversionMap
Static map of conversions between types.
Detailed Description
A key in the clipboard representing a time and a value of a specific type Client code must define MovieSceneClipboard::GetKeyTypeName<> in order to use a type with this class.
In general, keys are stored relaative to the minumum key-time in the clipboard, or some arbitrary time. This cardinal time is stored with the clipboard environment.
Definition at line 47 of file MovieSceneClipboard.h.
Member Typedef Documentation
FConversionFunction
typedef TFunction<FMovieSceneClipboardKey(const FMovieSceneClipboardKey&)> FMovieSceneClipboardKey::FConversionFunction private
Definition at line 116 of file MovieSceneClipboard.h.
Constructor & Destructor Documentation
FMovieSceneClipboardKey() [1/2]
template<typename T> FMovieSceneClipboardKey::FMovieSceneClipboardKey (FFrameNumber InTime, T InValue) inline
Templated constructor accepting a specific value type.
Definition at line 52 of file MovieSceneClipboard.h.
References Data, InTime, MoveTemp(), and Time.
Referenced by FMovieSceneClipboardKey(), DefineConversion(), operator=(), and TryGetValue().
FMovieSceneClipboardKey() [2/2]
MOVIESCENE_API FMovieSceneClipboardKey::FMovieSceneClipboardKey (const FMovieSceneClipboardKey & In)
Copy construction/assignment.
References FMovieSceneClipboardKey().
Member Function Documentation
DefineConversion()
template<typename FromType, typename ToType> void FMovieSceneClipboardKey::DefineConversion (TFunction< ToType(const FromType &)> InFunction) inline static
Define a conversion from one type to another type.
Definition at line 170 of file MovieSceneClipboard.h.
References FMovieSceneClipboardKey(), ConversionMap, MovieSceneClipboard::GetKeyTypeName(), and FMovieSceneClipboardKey::TKey< T >::Value.
Referenced by MovieSceneClipboard::DefineExplicitConversion().
GetTime()
MOVIESCENE_API FFrameNumber FMovieSceneClipboardKey::GetTime () const
Get the time at which this key is defined.
GetValue()
template<typename T> T FMovieSceneClipboardKey::GetValue () const inline
Get the value of this key as the specified type.
Returns
the key as the templated type, or a default-constructed T where no conversion is possible
Definition at line 74 of file MovieSceneClipboard.h.
References Default, and TryGetValue().
operator=()
MOVIESCENE_API FMovieSceneClipboardKey & FMovieSceneClipboardKey::operator= (const FMovieSceneClipboardKey & In)
References FMovieSceneClipboardKey().
SetTime()
MOVIESCENE_API void FMovieSceneClipboardKey::SetTime (FFrameNumber InTime)
Set the time at which this key is defined.
References InTime.
TryGetValue()
template<typename T> bool FMovieSceneClipboardKey::TryGetValue (T & Value) const inline
Attempt to get the value of this key as the specified type.
Parameters
InValue Reference to receive the value
Returns
true if the value was set, or false if no conversion between the source and T was possible
Definition at line 88 of file MovieSceneClipboard.h.
References FMovieSceneClipboardKey(), Data, MovieSceneClipboard::GetKeyTypeName(), Key, FMovieSceneClipboardKey::TKey< T >::Value, and Value.
Referenced by GetValue().
Field Documentation
ConversionMap
MOVIESCENE_API TMap<FName, TMap<FName, FConversionFunction> > FMovieSceneClipboardKey::ConversionMap static private
Static map of conversions between types.
Definition at line 185 of file MovieSceneClipboard.h.
Referenced by DefineConversion(), and FMovieSceneClipboardKey::TKey< T >::FindConversionTo().
Data
TInlineValue<IKey, 64> FMovieSceneClipboardKey::Data private
Type-erased bytes containing the key's value.
Definition at line 164 of file MovieSceneClipboard.h.
Referenced by FMovieSceneClipboardKey(), and TryGetValue().
Time
FFrameNumber FMovieSceneClipboardKey::Time private
The time that this key is defined at.
Definition at line 161 of file MovieSceneClipboard.h.
Referenced by FMovieSceneClipboardKey().
The documentation for this class was generated from the following file:
MovieSceneClipboard.h