Unreal Engine 5.6 C++ API: FStructBuilder Class Reference
FStructBuilder Class Reference
Lays out up a struct at runtime, in hopefully the same way as a compiler, and returns the offset of each member as it's added.
#include "StructBuilder.h"
Public Member Functions
FStructBuilder ()
int32 AddMember (int32 MemberSize, int32 MemberAlignment)
Adds a new member to the end of the struct.
int32 GetAlignment () const
Returns the current alignment of the struct.
int32 GetSize () const
Returns the current size of the struct.
Private Attributes
int32 Alignment
int32 EndOfLastMember
Detailed Description
Lays out up a struct at runtime, in hopefully the same way as a compiler, and returns the offset of each member as it's added.
Definition at line 13 of file StructBuilder.h.
Constructor & Destructor Documentation
FStructBuilder()
FStructBuilder::FStructBuilder () inline
Definition at line 16 of file StructBuilder.h.
References Alignment, and EndOfLastMember.
Member Function Documentation
AddMember()
int32 FStructBuilder::AddMember (int32 MemberSize, int32 MemberAlignment) inline
Adds a new member to the end of the struct.
Parameters
MemberSize The size of the member.
MemberAlignment The alignment of the member.
Returns
The offset of the member from the start of the struct.
Definition at line 30 of file StructBuilder.h.
References Align, Alignment, EndOfLastMember, and FMath::Max.
Referenced by TScriptMap< FDefaultSetAllocator, FScriptMap >::GetScriptLayout(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::GetScriptLayout().
GetAlignment()
int32 FStructBuilder::GetAlignment () const inline
Returns the current alignment of the struct.
Returns
The alignment of the struct.
Definition at line 53 of file StructBuilder.h.
References Alignment.
Referenced by TScriptMap< FDefaultSetAllocator, FScriptMap >::GetScriptLayout(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::GetScriptLayout().
GetSize()
int32 FStructBuilder::GetSize () const inline
Returns the current size of the struct.
Returns
The size of the struct.
Definition at line 43 of file StructBuilder.h.
References Align, Alignment, and EndOfLastMember.
Referenced by TScriptMap< FDefaultSetAllocator, FScriptMap >::GetScriptLayout(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::GetScriptLayout().
Field Documentation
Alignment
int32 FStructBuilder::Alignment private
Definition at line 63 of file StructBuilder.h.
Referenced by FStructBuilder(), AddMember(), GetAlignment(), and GetSize().
EndOfLastMember
int32 FStructBuilder::EndOfLastMember private
Definition at line 60 of file StructBuilder.h.
Referenced by FStructBuilder(), AddMember(), and GetSize().
The documentation for this class was generated from the following file:
StructBuilder.h