Unreal Engine 5.6 C++ API: FGenericPlatformProperties Struct Reference
FGenericPlatformProperties Struct Reference
Base class for platform properties.
#include "GenericPlatformProperties.h"
Static Public Member Functions
static constexpr FORCEINLINE bool AllowsCallStackDumpDuringAssert ()
static constexpr FORCEINLINE bool AllowsFramerateSmoothing ()
Whether this platform wants to allow framerate smoothing or not.
static constexpr FORCEINLINE int GetMaxSupportedVirtualMemoryAlignment ()
static constexpr FORCEINLINE int64 GetMemoryMappingAlignment ()
static constexpr FORCEINLINE const char * GetPhysicsFormat ()
Gets the platform's physics format.
static constexpr FORCEINLINE const char * GetZlibReplacementFormat ()
static constexpr FORCEINLINE bool HasEditorOnlyData ()
Gets whether this platform has Editor-only data.
static constexpr FORCEINLINE bool HasFixedResolution ()
Gets whether user settings should override the resolution or not.
static constexpr FORCEINLINE bool HasSecurePackageFormat ()
Checks whether shipped data on this platform is secure, and doesn't require extra encryption/signing to protect it.
static const char * IniPlatformName ()
Gets the name of this platform when loading INI files.
static constexpr FORCEINLINE bool IsClientOnly ()
Gets whether this is a client only (no capability to run the game without connecting to a server) platform.
static constexpr FORCEINLINE bool IsGameOnly ()
Gets whether this is a game only platform.
static constexpr FORCEINLINE bool IsLittleEndian ()
Gets whether this is a Little Endian platform.
static constexpr FORCEINLINE bool IsMonolithicBuild ()
Gets whether this was a monolithic build or not.
static constexpr FORCEINLINE bool IsProgram ()
Gets whether this was a program or not.
static constexpr FORCEINLINE bool IsServerOnly ()
Gets whether this is a server only platform.
static FORCEINLINE const char * PlatformName ()
Gets the name of this platform.
static FORCEINLINE const char * PlatformVariantName ()
Get the name of the hardware variant of the current platform.
static constexpr FORCEINLINE bool RequiresCookedData ()
Checks whether this platform requires cooked data.
static constexpr FORCEINLINE bool RequiresOriginalReleaseVersionForPatch ()
static constexpr FORCEINLINE bool RequiresUserCredentials ()
Checks whether this platform requires user credentials (typically server platforms).
static constexpr FORCEINLINE bool SupportsAudioStreaming ()
Whether this platform supports streaming audio.
static constexpr FORCEINLINE bool SupportsAutoSDK ()
Returns true if platform supports the AutoSDK system.
static FORCEINLINE bool SupportsBuildTarget (EBuildTargetType TargetType)
Checks whether the specified build target is supported.
static constexpr FORCEINLINE bool SupportsDistanceFieldAO ()
static constexpr FORCEINLINE bool SupportsDistanceFieldShadows ()
static constexpr FORCEINLINE bool SupportsGrayscaleSRGB ()
Gets whether this platform supports gray scale sRGB texture formats.
static constexpr FORCEINLINE bool SupportsHardwareLZDecompression ()
static constexpr FORCEINLINE bool SupportsHighQualityLightmaps ()
static constexpr FORCEINLINE bool SupportsLowQualityLightmaps ()
static constexpr FORCEINLINE bool SupportsLumenGI ()
static constexpr FORCEINLINE bool SupportsMemoryMappedAnimation ()
static constexpr FORCEINLINE bool SupportsMemoryMappedAudio ()
static constexpr FORCEINLINE bool SupportsMemoryMappedFiles ()
static constexpr FORCEINLINE bool SupportsMeshLODStreaming ()
static constexpr FORCEINLINE bool SupportsMinimize ()
static constexpr FORCEINLINE bool SupportsMultipleGameInstances ()
Checks whether this platforms supports running multiple game instances on a single device.
static constexpr FORCEINLINE bool SupportsQuit ()
static constexpr FORCEINLINE bool SupportsRayTracing ()
static constexpr FORCEINLINE bool SupportsTextureStreaming ()
static constexpr FORCEINLINE bool SupportsWindowedMode ()
Gets whether this platform supports windowed mode rendering.
Detailed Description
Base class for platform properties.
These are shared between: the runtime platform - via FPlatformProperties the target platforms - via ITargetPlatform
Definition at line 16 of file GenericPlatformProperties.h.
Member Function Documentation
AllowsCallStackDumpDuringAssert()
constexpr FORCEINLINE bool FGenericPlatformProperties::AllowsCallStackDumpDuringAssert () inline static constexpr
Definition at line 311 of file GenericPlatformProperties.h.
References FORCEINLINE, and IsProgram().
AllowsFramerateSmoothing()
constexpr FORCEINLINE bool FGenericPlatformProperties::AllowsFramerateSmoothing () inline static constexpr
Whether this platform wants to allow framerate smoothing or not.
Definition at line 207 of file GenericPlatformProperties.h.
References FORCEINLINE.
GetMaxSupportedVirtualMemoryAlignment()
constexpr FORCEINLINE int FGenericPlatformProperties::GetMaxSupportedVirtualMemoryAlignment () inline static constexpr
Definition at line 271 of file GenericPlatformProperties.h.
References FORCEINLINE.
GetMemoryMappingAlignment()
constexpr FORCEINLINE int64 FGenericPlatformProperties::GetMemoryMappingAlignment () inline static constexpr
Definition at line 265 of file GenericPlatformProperties.h.
References FORCEINLINE.
GetPhysicsFormat()
constexpr FORCEINLINE const char * FGenericPlatformProperties::GetPhysicsFormat () inline static constexpr
Gets the platform's physics format.
Returns
The physics format name.
Definition at line 23 of file GenericPlatformProperties.h.
References FORCEINLINE.
GetZlibReplacementFormat()
constexpr FORCEINLINE const char * FGenericPlatformProperties::GetZlibReplacementFormat () inline static constexpr
Definition at line 318 of file GenericPlatformProperties.h.
References FORCEINLINE.
HasEditorOnlyData()
constexpr FORCEINLINE bool FGenericPlatformProperties::HasEditorOnlyData () inline static constexpr
Gets whether this platform has Editor-only data.
Returns
true if the platform has Editor-only data, false otherwise.
Definition at line 33 of file GenericPlatformProperties.h.
References FORCEINLINE, and WITH_EDITORONLY_DATA.
Referenced by RequiresCookedData().
HasFixedResolution()
constexpr FORCEINLINE bool FGenericPlatformProperties::HasFixedResolution () inline static constexpr
Gets whether user settings should override the resolution or not.
Definition at line 294 of file GenericPlatformProperties.h.
References FORCEINLINE.
HasSecurePackageFormat()
constexpr FORCEINLINE bool FGenericPlatformProperties::HasSecurePackageFormat () inline static constexpr
Checks whether shipped data on this platform is secure, and doesn't require extra encryption/signing to protect it.
Returns
true if packaged data is considered secure, false otherwise.
Definition at line 140 of file GenericPlatformProperties.h.
References FORCEINLINE.
IniPlatformName()
const char * FGenericPlatformProperties::IniPlatformName () static
Gets the name of this platform when loading INI files.
Defaults to PlatformName.
Note: MUST be implemented per platform.
Returns
Platform name.
IsClientOnly()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsClientOnly () inline static constexpr
Gets whether this is a client only (no capability to run the game without connecting to a server) platform.
Returns
true if this is a client only platform, false otherwise.
Definition at line 72 of file GenericPlatformProperties.h.
References FORCEINLINE.
IsGameOnly()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsGameOnly () inline static constexpr
Gets whether this is a game only platform.
Returns
true if this is a game only platform, false otherwise.
Definition at line 52 of file GenericPlatformProperties.h.
References FORCEINLINE, and UE_GAME.
IsLittleEndian()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsLittleEndian () inline static constexpr
Gets whether this is a Little Endian platform.
Returns
true if the platform is Little Endian, false otherwise.
Definition at line 98 of file GenericPlatformProperties.h.
References FORCEINLINE.
IsMonolithicBuild()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsMonolithicBuild () inline static constexpr
Gets whether this was a monolithic build or not.
Definition at line 80 of file GenericPlatformProperties.h.
References FORCEINLINE, and IS_MONOLITHIC.
IsProgram()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsProgram () inline static constexpr
Gets whether this was a program or not.
Definition at line 88 of file GenericPlatformProperties.h.
References FORCEINLINE, and IS_PROGRAM.
Referenced by AllowsCallStackDumpDuringAssert().
IsServerOnly()
constexpr FORCEINLINE bool FGenericPlatformProperties::IsServerOnly () inline static constexpr
Gets whether this is a server only platform.
Returns
true if this is a server only platform, false otherwise.
Definition at line 62 of file GenericPlatformProperties.h.
References FORCEINLINE, and UE_SERVER.
PlatformName()
FORCEINLINE const char * FGenericPlatformProperties::PlatformName () static
Gets the name of this platform.
Note: MUST be implemented per platform.
Returns
Platform Name.
References FORCEINLINE.
PlatformVariantName()
FORCEINLINE const char * FGenericPlatformProperties::PlatformVariantName () inline static
Get the name of the hardware variant of the current platform.
Most platforms don't need to provide overrides for this member. This member is intended to be used by the few which come in different hardware flavours or which may operate in different runtime modes.
Returns
Name of the platform variant.
Definition at line 120 of file GenericPlatformProperties.h.
References FORCEINLINE.
RequiresCookedData()
constexpr FORCEINLINE bool FGenericPlatformProperties::RequiresCookedData () inline static constexpr
Checks whether this platform requires cooked data.
Returns
true if cooked data is required, false otherwise.
Definition at line 130 of file GenericPlatformProperties.h.
References FORCEINLINE, and HasEditorOnlyData().
RequiresOriginalReleaseVersionForPatch()
constexpr FORCEINLINE bool FGenericPlatformProperties::RequiresOriginalReleaseVersionForPatch () inline static constexpr
Definition at line 324 of file GenericPlatformProperties.h.
References FORCEINLINE.
RequiresUserCredentials()
constexpr FORCEINLINE bool FGenericPlatformProperties::RequiresUserCredentials () inline static constexpr
Checks whether this platform requires user credentials (typically server platforms).
Returns
true if this platform requires user credentials, false otherwise.
Definition at line 150 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsAudioStreaming()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsAudioStreaming () inline static constexpr
Whether this platform supports streaming audio.
Definition at line 215 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsAutoSDK()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsAutoSDK () inline static constexpr
Returns true if platform supports the AutoSDK system.
Definition at line 169 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsBuildTarget()
FORCEINLINE bool FGenericPlatformProperties::SupportsBuildTarget (EBuildTargetType TargetType) inline static
Checks whether the specified build target is supported.
Parameters
TargetType The build target to check.
Returns
true if the build target is supported, false otherwise.
Definition at line 161 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsDistanceFieldAO()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsDistanceFieldAO () inline static constexpr
Definition at line 235 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsDistanceFieldShadows()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsDistanceFieldShadows () inline static constexpr
Definition at line 230 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsGrayscaleSRGB()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsGrayscaleSRGB () inline static constexpr
Gets whether this platform supports gray scale sRGB texture formats.
Returns
true if gray scale sRGB texture formats are supported.
Definition at line 179 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsHardwareLZDecompression()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsHardwareLZDecompression () inline static constexpr
Definition at line 286 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsHighQualityLightmaps()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsHighQualityLightmaps () inline static constexpr
Definition at line 220 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsLowQualityLightmaps()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsLowQualityLightmaps () inline static constexpr
Definition at line 225 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsLumenGI()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsLumenGI () inline static constexpr
Definition at line 281 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMemoryMappedAnimation()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMemoryMappedAnimation () inline static constexpr
Definition at line 260 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMemoryMappedAudio()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMemoryMappedAudio () inline static constexpr
Definition at line 255 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMemoryMappedFiles()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMemoryMappedFiles () inline static constexpr
Definition at line 250 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMeshLODStreaming()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMeshLODStreaming () inline static constexpr
Definition at line 245 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMinimize()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMinimize () inline static constexpr
Definition at line 299 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsMultipleGameInstances()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsMultipleGameInstances () inline static constexpr
Checks whether this platforms supports running multiple game instances on a single device.
Returns
true if multiple instances are supported, false otherwise.
Definition at line 189 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsQuit()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsQuit () inline static constexpr
Definition at line 305 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsRayTracing()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsRayTracing () inline static constexpr
Definition at line 276 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsTextureStreaming()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsTextureStreaming () inline static constexpr
Definition at line 240 of file GenericPlatformProperties.h.
References FORCEINLINE.
SupportsWindowedMode()
constexpr FORCEINLINE bool FGenericPlatformProperties::SupportsWindowedMode () inline static constexpr
Gets whether this platform supports windowed mode rendering.
Returns
true if windowed mode is supported.
Definition at line 199 of file GenericPlatformProperties.h.
References FORCEINLINE.
The documentation for this struct was generated from the following file:
GenericPlatformProperties.h