Unreal Engine 5.6 C++ API: TRefCountingMixin< T, ERefCountingMode::ThreadSafe > Class Template Reference
TRefCountingMixin< T, ERefCountingMode::ThreadSafe > Class Template Reference
Thread-safe specialization.
#include "RefCounting.h"
Public Member Functions
TRefCountingMixin ()=default
TRefCountingMixin (const TRefCountingMixin &)=delete
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
TRefCountingMixin & operator= (const TRefCountingMixin &)=delete
uint32 Release () const
Static Public Member Functions
static void StaticDestroyObject (const T *Obj)
Private Types
using Super = UE::Private::TTransactionalAtomicRefCount<uint32>
Static Private Member Functions
static void StaticDestroyMixin (const Super *This)
Additional Inherited Members
Private Member Functions inherited from UE::Private::TTransactionalAtomicRefCount< uint32 >
uint32 AddRef () const
uint32 GetRefCount () const
uint32 Release () const
Detailed Description
template<typename T>
class TRefCountingMixin< T, ERefCountingMode::ThreadSafe >
Thread-safe specialization.
Definition at line 361 of file RefCounting.h.
Member Typedef Documentation
Super
template<typename T> using TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::Super = UE::Private::TTransactionalAtomicRefCount<uint32> private
Definition at line 390 of file RefCounting.h.
Constructor & Destructor Documentation
TRefCountingMixin() [1/2]
template<typename T> TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::TRefCountingMixin () default
Referenced by TRefCountingMixin(), and operator=().
TRefCountingMixin() [2/2]
template<typename T> TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::TRefCountingMixin (const TRefCountingMixin< T, ERefCountingMode::ThreadSafe > &) delete
References TRefCountingMixin().
Member Function Documentation
AddRef()
template<typename T> FReturnedRefCountValue TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::AddRef () const inline
Definition at line 369 of file RefCounting.h.
References AddRef().
Referenced by AddRef().
GetRefCount()
template<typename T> uint32 TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::GetRefCount () const inline
Definition at line 379 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::GetRefCount().
operator=()
template<typename T> TRefCountingMixin & TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::operator= (const TRefCountingMixin< T, ERefCountingMode::ThreadSafe > &) delete
References TRefCountingMixin().
Release()
template<typename T> uint32 TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::Release () const inline
Definition at line 374 of file RefCounting.h.
References Release().
Referenced by Release().
StaticDestroyMixin()
template<typename T> void TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::StaticDestroyMixin (const Super * This) inline static private
Definition at line 392 of file RefCounting.h.
StaticDestroyObject()
template<typename T> void TRefCountingMixin< T, ERefCountingMode::ThreadSafe >::StaticDestroyObject (const T * Obj) inline static
Definition at line 384 of file RefCounting.h.
The documentation for this class was generated from the following file:
RefCounting.h