Unreal Engine 5.6 C++ API: FPrecomputedVolumetricLightmapData Class Reference
FPrecomputedVolumetricLightmapData Class Reference
Data for a Volumetric Lightmap, built during import from Lightmass.
#include "PrecomputedVolumetricLightmap.h"
Public Member Functions
FPrecomputedVolumetricLightmapData ()
virtual ~FPrecomputedVolumetricLightmapData ()
void AddToSceneData (FPrecomputedVolumetricLightmapData *SceneData)
void FinalizeImport ()
SIZE_T GetAllocatedBytes () const
const FBox & GetBounds () const
void HandleDataMovementInAtlas (int32 OldOffset, int32 NewOffset)
void InitializeOnImport (const FBox &NewBounds, int32 InBrickSize)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForSubLevelResources ()
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForSubLevelResources ()
void RemoveFromSceneData (FPrecomputedVolumetricLightmapData *SceneData, int32 PersistentLevelBrickDataBaseOffset)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
FBox Bounds
FVolumetricLightmapBrickData BrickData
int32 BrickDataBaseOffsetInAtlas
FIntVector BrickDataDimensions
int32 BrickSize
bool bTransient
TArray< FPrecomputedVolumetricLightmapData * > CPUSubLevelBrickDataList
TArray< uint8 > CPUSubLevelIndirectionTable
FVolumetricLightmapDataLayer IndirectionTexture
FIntVector IndirectionTextureDimensions
TResourceArray< FColor > IndirectionTextureOriginalValues
FBufferRHIRef IndirectionTextureOriginalValuesBuffer
FShaderResourceViewRHIRef IndirectionTextureOriginalValuesSRV
TArray< FPrecomputedVolumetricLightmapData * > SceneDataAdded
TResourceArray< FIntVector > SubLevelBrickPositions
Position data for sub level streaming.
FBufferRHIRef SubLevelBrickPositionsBuffer
Runtime data for sub level streaming.
FShaderResourceViewRHIRef SubLevelBrickPositionsSRV
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Friends
class FPrecomputedVolumetricLightmap
FArchive & operator<< (FArchive &Ar, FPrecomputedVolumetricLightmapData &Volume)
FArchive & operator<< (FArchive &Ar, FPrecomputedVolumetricLightmapData *&Volume)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Data for a Volumetric Lightmap, built during import from Lightmass.
Its lifetime is managed by UMapBuildDataRegistry.
Definition at line 145 of file PrecomputedVolumetricLightmap.h.
Constructor & Destructor Documentation
FPrecomputedVolumetricLightmapData()
FPrecomputedVolumetricLightmapData::FPrecomputedVolumetricLightmapData ()
Referenced by AddToSceneData(), operator<<, operator<<, and RemoveFromSceneData().
~FPrecomputedVolumetricLightmapData()
virtual FPrecomputedVolumetricLightmapData::~FPrecomputedVolumetricLightmapData () virtual
Member Function Documentation
AddToSceneData()
void FPrecomputedVolumetricLightmapData::AddToSceneData (FPrecomputedVolumetricLightmapData * SceneData)
References FPrecomputedVolumetricLightmapData().
FinalizeImport()
void FPrecomputedVolumetricLightmapData::FinalizeImport ()
GetAllocatedBytes()
SIZE_T FPrecomputedVolumetricLightmapData::GetAllocatedBytes () const
GetBounds()
const FBox & FPrecomputedVolumetricLightmapData::GetBounds () const inline
Definition at line 170 of file PrecomputedVolumetricLightmap.h.
References Bounds.
HandleDataMovementInAtlas()
void FPrecomputedVolumetricLightmapData::HandleDataMovementInAtlas (int32 OldOffset, int32 NewOffset)
InitializeOnImport()
void FPrecomputedVolumetricLightmapData::InitializeOnImport (const FBox & NewBounds, int32 InBrickSize)
InitRHI()
virtual void FPrecomputedVolumetricLightmapData::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForSubLevelResources()
void FPrecomputedVolumetricLightmapData::InitRHIForSubLevelResources ()
ReleaseRHI()
virtual void FPrecomputedVolumetricLightmapData::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHIForSubLevelResources()
void FPrecomputedVolumetricLightmapData::ReleaseRHIForSubLevelResources ()
RemoveFromSceneData()
void FPrecomputedVolumetricLightmapData::RemoveFromSceneData (FPrecomputedVolumetricLightmapData * SceneData, int32 PersistentLevelBrickDataBaseOffset)
References FPrecomputedVolumetricLightmapData().
Friends And Related Symbol Documentation
FPrecomputedVolumetricLightmap
friend class FPrecomputedVolumetricLightmap friend
Definition at line 211 of file PrecomputedVolumetricLightmap.h.
References FPrecomputedVolumetricLightmap.
Referenced by FPrecomputedVolumetricLightmap.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPrecomputedVolumetricLightmapData & Volume) friend
References FPrecomputedVolumetricLightmapData(), Ar, and Volume.
operator<< [2/2]
FArchive & operator<< (FArchive & Ar, FPrecomputedVolumetricLightmapData *& Volume) friend
References FPrecomputedVolumetricLightmapData(), Ar, and Volume.
Field Documentation
Bounds
FBox FPrecomputedVolumetricLightmapData::Bounds
Definition at line 175 of file PrecomputedVolumetricLightmap.h.
Referenced by GetBounds().
BrickData
FVolumetricLightmapBrickData FPrecomputedVolumetricLightmapData::BrickData
Definition at line 184 of file PrecomputedVolumetricLightmap.h.
BrickDataBaseOffsetInAtlas
int32 FPrecomputedVolumetricLightmapData::BrickDataBaseOffsetInAtlas
Definition at line 202 of file PrecomputedVolumetricLightmap.h.
BrickDataDimensions
FIntVector FPrecomputedVolumetricLightmapData::BrickDataDimensions
Definition at line 183 of file PrecomputedVolumetricLightmap.h.
BrickSize
int32 FPrecomputedVolumetricLightmapData::BrickSize
Definition at line 182 of file PrecomputedVolumetricLightmap.h.
bTransient
bool FPrecomputedVolumetricLightmapData::bTransient
Definition at line 177 of file PrecomputedVolumetricLightmap.h.
CPUSubLevelBrickDataList
TArray<FPrecomputedVolumetricLightmapData*> FPrecomputedVolumetricLightmapData::CPUSubLevelBrickDataList
Definition at line 207 of file PrecomputedVolumetricLightmap.h.
CPUSubLevelIndirectionTable
TArray<uint8> FPrecomputedVolumetricLightmapData::CPUSubLevelIndirectionTable
Definition at line 206 of file PrecomputedVolumetricLightmap.h.
IndirectionTexture
FVolumetricLightmapDataLayer FPrecomputedVolumetricLightmapData::IndirectionTexture
Definition at line 180 of file PrecomputedVolumetricLightmap.h.
IndirectionTextureDimensions
FIntVector FPrecomputedVolumetricLightmapData::IndirectionTextureDimensions
Definition at line 179 of file PrecomputedVolumetricLightmap.h.
IndirectionTextureOriginalValues
TResourceArray<FColor> FPrecomputedVolumetricLightmapData::IndirectionTextureOriginalValues
Definition at line 191 of file PrecomputedVolumetricLightmap.h.
IndirectionTextureOriginalValuesBuffer
FBufferRHIRef FPrecomputedVolumetricLightmapData::IndirectionTextureOriginalValuesBuffer
Definition at line 199 of file PrecomputedVolumetricLightmap.h.
IndirectionTextureOriginalValuesSRV
FShaderResourceViewRHIRef FPrecomputedVolumetricLightmapData::IndirectionTextureOriginalValuesSRV
Definition at line 200 of file PrecomputedVolumetricLightmap.h.
SceneDataAdded
TArray<FPrecomputedVolumetricLightmapData*> FPrecomputedVolumetricLightmapData::SceneDataAdded
Definition at line 203 of file PrecomputedVolumetricLightmap.h.
SubLevelBrickPositions
TResourceArray<FIntVector> FPrecomputedVolumetricLightmapData::SubLevelBrickPositions
Position data for sub level streaming.
Definition at line 190 of file PrecomputedVolumetricLightmap.h.
SubLevelBrickPositionsBuffer
FBufferRHIRef FPrecomputedVolumetricLightmapData::SubLevelBrickPositionsBuffer
Runtime data for sub level streaming.
Definition at line 196 of file PrecomputedVolumetricLightmap.h.
SubLevelBrickPositionsSRV
FShaderResourceViewRHIRef FPrecomputedVolumetricLightmapData::SubLevelBrickPositionsSRV
Definition at line 197 of file PrecomputedVolumetricLightmap.h.
The documentation for this class was generated from the following file:
PrecomputedVolumetricLightmap.h