Unreal Engine 5.6 C++ API: IChaosCachingPlugin Class Reference
IChaosCachingPlugin Class Reference
#include "ChaosCachingPlugin.h"
Public Member Functions
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IChaosCachingPlugin & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Private Attributes
TUniquePtr< Chaos::FGeometryCollectionCacheAdapter > GeometryCollectionAdapter
FDelegateHandle OnCreateMovieSceneObjectSpawnerHandle
TUniquePtr< Chaos::FStaticMeshCacheAdapter > StaticMeshAdapter
Detailed Description
Definition at line 15 of file ChaosCachingPlugin.h.
Member Function Documentation
Get()
IChaosCachingPlugin & IChaosCachingPlugin::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 27 of file ChaosCachingPlugin.h.
References FModuleManager::LoadModuleChecked().
IsAvailable()
bool IChaosCachingPlugin::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 37 of file ChaosCachingPlugin.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
ShutdownModule()
virtual void IChaosCachingPlugin::ShutdownModule () virtual
Called before the module is unloaded, right before the module object is destroyed.
During normal shutdown, this is called in reverse order that modules finish StartupModule(). This means that, as long as a module references dependent modules in it's StartupModule(), it can safely reference those dependencies in ShutdownModule() as well.
Reimplemented from IModuleInterface.
StartupModule()
virtual void IChaosCachingPlugin::StartupModule () virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
Field Documentation
GeometryCollectionAdapter
TUniquePtr<Chaos::FGeometryCollectionCacheAdapter> IChaosCachingPlugin::GeometryCollectionAdapter private
Definition at line 43 of file ChaosCachingPlugin.h.
OnCreateMovieSceneObjectSpawnerHandle
FDelegateHandle IChaosCachingPlugin::OnCreateMovieSceneObjectSpawnerHandle private
Definition at line 46 of file ChaosCachingPlugin.h.
StaticMeshAdapter
TUniquePtr<Chaos::FStaticMeshCacheAdapter> IChaosCachingPlugin::StaticMeshAdapter private
Definition at line 44 of file ChaosCachingPlugin.h.
The documentation for this class was generated from the following file:
ChaosCachingPlugin.h