Unreal Engine 5.6 C++ API: FQuatFixed48NoW Class Reference
FQuatFixed48NoW Class Reference
#include "AnimationCompression.h"
Public Member Functions
FQuatFixed48NoW ()
FQuatFixed48NoW (const FQuat4f &Quat)
void FromQuat (const FQuat4f &Quat)
void ToQuat (FQuat4f &Out) const
Data Fields
uint16 X
uint16 Y
uint16 Z
Friends
FArchive & operator<< (FArchive &Ar, FQuatFixed48NoW &Quat)
Detailed Description
Definition at line 96 of file AnimationCompression.h.
Constructor & Destructor Documentation
FQuatFixed48NoW() [1/2]
FQuatFixed48NoW::FQuatFixed48NoW () inline
Definition at line 103 of file AnimationCompression.h.
Referenced by operator<<.
FQuatFixed48NoW() [2/2]
FQuatFixed48NoW::FQuatFixed48NoW (const FQuat4f & Quat) inline explicit
Definition at line 106 of file AnimationCompression.h.
References FromQuat(), and Quat.
Member Function Documentation
FromQuat()
void FQuatFixed48NoW::FromQuat (const FQuat4f & Quat) inline
Definition at line 111 of file AnimationCompression.h.
References UE::Math::TQuat< T >::Normalize(), Quant16BitFactor, Quant16BitOffs, Quat, UE::Math::TQuat< T >::W, X, UE::Math::TQuat< T >::X, Y, UE::Math::TQuat< T >::Y, Z, and UE::Math::TQuat< T >::Z.
Referenced by FQuatFixed48NoW().
ToQuat()
void FQuatFixed48NoW::ToQuat (FQuat4f & Out) const inline
Definition at line 128 of file AnimationCompression.h.
References Quant16BitDiv, Quant16BitOffs, UE::Math::TQuat< T >::W, X, UE::Math::TQuat< T >::X, Y, UE::Math::TQuat< T >::Y, Z, and UE::Math::TQuat< T >::Z.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FQuatFixed48NoW & Quat) friend
Definition at line 141 of file AnimationCompression.h.
References FQuatFixed48NoW(), Ar, and Quat.
Field Documentation
X
uint16 FQuatFixed48NoW::X
Definition at line 99 of file AnimationCompression.h.
Referenced by FromQuat(), and ToQuat().
Y
uint16 FQuatFixed48NoW::Y
Definition at line 100 of file AnimationCompression.h.
Referenced by FromQuat(), and ToQuat().
Z
uint16 FQuatFixed48NoW::Z
Definition at line 101 of file AnimationCompression.h.
Referenced by FromQuat(), and ToQuat().
The documentation for this class was generated from the following file:
AnimationCompression.h