Unreal Engine 5.6 C++ API: FDepthStencilBinding Struct Reference
FDepthStencilBinding Struct Reference
Render graph information about how to bind a depth-stencil render target.
#include "ShaderParameterMacros.h"
Public Member Functions
FDepthStencilBinding ()=default
FORCEINLINE FDepthStencilBinding (FRDGTexture *InTexture, ERenderTargetLoadAction InDepthLoadAction, ERenderTargetLoadAction InStencilLoadAction, FExclusiveDepthStencil InDepthStencilAccess)
Creates a render target binding informations for a depth/stencil texture.
FORCEINLINE FDepthStencilBinding (FRDGTexture *InTexture, ERenderTargetLoadAction InDepthLoadAction, FExclusiveDepthStencil InDepthStencilAccess)
FORCEINLINE FDepthStencilBinding (FRDGTexture *InTexture, FRDGTexture *InResolveTexture, ERenderTargetLoadAction InDepthLoadAction, ERenderTargetLoadAction InStencilLoadAction, FExclusiveDepthStencil InDepthStencilAccess)
FORCEINLINE FDepthStencilBinding (FRDGTexture *InTexture, FRDGTexture *InResolveTexture, ERenderTargetLoadAction InDepthLoadAction, FExclusiveDepthStencil InDepthStencilAccess)
bool CanMergeBefore (const FDepthStencilBinding &Other) const
FORCEINLINE ERenderTargetLoadAction GetDepthLoadAction () const
FORCEINLINE FExclusiveDepthStencil GetDepthStencilAccess () const
FORCEINLINE FRDGTexture * GetResolveTexture () const
FORCEINLINE ERenderTargetLoadAction GetStencilLoadAction () const
FORCEINLINE FRDGTexture * GetTexture () const
void SetDepthLoadAction (ERenderTargetLoadAction InAction)
void SetDepthStencilAccess (FExclusiveDepthStencil InAccess)
void SetResolveTexture (FRDGTexture *InTexture)
void SetStencilLoadAction (ERenderTargetLoadAction InAction)
void SetTexture (FRDGTexture *InTexture)
Private Member Functions
RENDERCORE_API bool Validate () const
Private Attributes
ERenderTargetLoadAction DepthLoadAction = ERenderTargetLoadAction::ENoAction
FExclusiveDepthStencil DepthStencilAccess = FExclusiveDepthStencil::DepthNop_StencilNop
TAlignedShaderParameterPtr< FRDGTexture * > ResolveTexture = nullptr
ERenderTargetLoadAction StencilLoadAction = ERenderTargetLoadAction::ENoAction
TAlignedShaderParameterPtr< FRDGTexture * > Texture = nullptr
All parameters required to bind a depth render target deferred.
Detailed Description
Render graph information about how to bind a depth-stencil render target.
Definition at line 628 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FDepthStencilBinding() [1/5]
FDepthStencilBinding::FDepthStencilBinding () default
Referenced by CanMergeBefore().
FDepthStencilBinding() [2/5]
FORCEINLINE FDepthStencilBinding::FDepthStencilBinding (FRDGTexture * InTexture, ERenderTargetLoadAction InDepthLoadAction, ERenderTargetLoadAction InStencilLoadAction, FExclusiveDepthStencil InDepthStencilAccess) inline
Creates a render target binding informations for a depth/stencil texture.
Notes: Load and store action are on explicit without default values, to force the user to not forget one of these.
Definition at line 637 of file ShaderParameterMacros.h.
References check, DepthLoadAction, DepthStencilAccess, FORCEINLINE, ResolveTexture, StencilLoadAction, Texture, and Validate().
FDepthStencilBinding() [3/5]
FORCEINLINE FDepthStencilBinding::FDepthStencilBinding (FRDGTexture * InTexture, FRDGTexture * InResolveTexture, ERenderTargetLoadAction InDepthLoadAction, ERenderTargetLoadAction InStencilLoadAction, FExclusiveDepthStencil InDepthStencilAccess) inline
Definition at line 651 of file ShaderParameterMacros.h.
References check, DepthLoadAction, DepthStencilAccess, FORCEINLINE, ResolveTexture, StencilLoadAction, Texture, and Validate().
FDepthStencilBinding() [4/5]
FORCEINLINE FDepthStencilBinding::FDepthStencilBinding (FRDGTexture * InTexture, ERenderTargetLoadAction InDepthLoadAction, FExclusiveDepthStencil InDepthStencilAccess) inline
Definition at line 666 of file ShaderParameterMacros.h.
References check, DepthLoadAction, DepthStencilAccess, FORCEINLINE, ResolveTexture, Texture, and Validate().
FDepthStencilBinding() [5/5]
FORCEINLINE FDepthStencilBinding::FDepthStencilBinding (FRDGTexture * InTexture, FRDGTexture * InResolveTexture, ERenderTargetLoadAction InDepthLoadAction, FExclusiveDepthStencil InDepthStencilAccess) inline
Definition at line 678 of file ShaderParameterMacros.h.
References check, DepthLoadAction, DepthStencilAccess, FORCEINLINE, ResolveTexture, Texture, and Validate().
Member Function Documentation
CanMergeBefore()
bool FDepthStencilBinding::CanMergeBefore (const FDepthStencilBinding & Other) const inline
Definition at line 713 of file ShaderParameterMacros.h.
References FDepthStencilBinding(), DepthStencilAccess, Other, ResolveTexture, and Texture.
GetDepthLoadAction()
FORCEINLINE ERenderTargetLoadAction FDepthStencilBinding::GetDepthLoadAction () const inline
Definition at line 699 of file ShaderParameterMacros.h.
References DepthLoadAction, and FORCEINLINE.
GetDepthStencilAccess()
FORCEINLINE FExclusiveDepthStencil FDepthStencilBinding::GetDepthStencilAccess () const inline
Definition at line 707 of file ShaderParameterMacros.h.
References DepthStencilAccess, and FORCEINLINE.
GetResolveTexture()
FORCEINLINE FRDGTexture * FDepthStencilBinding::GetResolveTexture () const inline
Definition at line 695 of file ShaderParameterMacros.h.
References FORCEINLINE, and ResolveTexture.
GetStencilLoadAction()
FORCEINLINE ERenderTargetLoadAction FDepthStencilBinding::GetStencilLoadAction () const inline
Definition at line 703 of file ShaderParameterMacros.h.
References FORCEINLINE, and StencilLoadAction.
GetTexture()
FORCEINLINE FRDGTexture * FDepthStencilBinding::GetTexture () const inline
Definition at line 691 of file ShaderParameterMacros.h.
References FORCEINLINE, and Texture.
SetDepthLoadAction()
void FDepthStencilBinding::SetDepthLoadAction (ERenderTargetLoadAction InAction) inline
Definition at line 741 of file ShaderParameterMacros.h.
References check, DepthLoadAction, and Validate().
SetDepthStencilAccess()
void FDepthStencilBinding::SetDepthStencilAccess (FExclusiveDepthStencil InAccess) inline
Definition at line 735 of file ShaderParameterMacros.h.
References check, DepthStencilAccess, and Validate().
SetResolveTexture()
void FDepthStencilBinding::SetResolveTexture (FRDGTexture * InTexture) inline
Definition at line 729 of file ShaderParameterMacros.h.
References check, ResolveTexture, and Validate().
SetStencilLoadAction()
void FDepthStencilBinding::SetStencilLoadAction (ERenderTargetLoadAction InAction) inline
Definition at line 747 of file ShaderParameterMacros.h.
References check, StencilLoadAction, and Validate().
SetTexture()
void FDepthStencilBinding::SetTexture (FRDGTexture * InTexture) inline
Definition at line 723 of file ShaderParameterMacros.h.
References check, Texture, and Validate().
Validate()
RENDERCORE_API bool FDepthStencilBinding::Validate () const private
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), SetDepthLoadAction(), SetDepthStencilAccess(), SetResolveTexture(), SetStencilLoadAction(), and SetTexture().
Field Documentation
DepthLoadAction
ERenderTargetLoadAction FDepthStencilBinding::DepthLoadAction = ERenderTargetLoadAction::ENoAction private
Definition at line 760 of file ShaderParameterMacros.h.
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), GetDepthLoadAction(), and SetDepthLoadAction().
DepthStencilAccess
FExclusiveDepthStencil FDepthStencilBinding::DepthStencilAccess = FExclusiveDepthStencil::DepthNop_StencilNop private
Definition at line 762 of file ShaderParameterMacros.h.
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), CanMergeBefore(), GetDepthStencilAccess(), and SetDepthStencilAccess().
ResolveTexture
TAlignedShaderParameterPtr<FRDGTexture*> FDepthStencilBinding::ResolveTexture = nullptr private
Definition at line 759 of file ShaderParameterMacros.h.
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), CanMergeBefore(), GetResolveTexture(), and SetResolveTexture().
StencilLoadAction
ERenderTargetLoadAction FDepthStencilBinding::StencilLoadAction = ERenderTargetLoadAction::ENoAction private
Definition at line 761 of file ShaderParameterMacros.h.
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), GetStencilLoadAction(), and SetStencilLoadAction().
Texture
TAlignedShaderParameterPtr<FRDGTexture*> FDepthStencilBinding::Texture = nullptr private
All parameters required to bind a depth render target deferred.
This are purposefully private to force the user to call FDepthStencilBinding() constructors. No defaults allowed.
Definition at line 758 of file ShaderParameterMacros.h.
Referenced by FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), FDepthStencilBinding(), CanMergeBefore(), GetTexture(), and SetTexture().
The documentation for this struct was generated from the following file:
ShaderParameterMacros.h