Unreal Engine 5.6 C++ API: ObjectPtr_Private::TNonAccessTrackedObjectPtr< T > Class Template Reference
ObjectPtr_Private::TNonAccessTrackedObjectPtr< T > Class Template Reference
#include "ObjectPtr.h"
Public Member Functions
TNonAccessTrackedObjectPtr ()=default
TNonAccessTrackedObjectPtr (ENoInit)
TNonAccessTrackedObjectPtr (T *Ptr)
T * Get () const
TObjectPtr< T > & GetAccessTrackedObjectPtr ()
const TObjectPtr< T > & GetAccessTrackedObjectPtr () const
UE_INTERNAL T * GetNoResolve () const
operator T* () const
operator UPTRINT () const
T * operator-> () const
TNonAccessTrackedObjectPtr & operator= (T *Value)
Private Attributes
TObjectPtr< T > ObjectPtr
Detailed Description
template<typename T>
class ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >
Definition at line 887 of file ObjectPtr.h.
Constructor & Destructor Documentation
TNonAccessTrackedObjectPtr() [1/3]
template<typename T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::TNonAccessTrackedObjectPtr () default
Referenced by operator=().
TNonAccessTrackedObjectPtr() [2/3]
template<typename T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::TNonAccessTrackedObjectPtr (ENoInit) inline explicit
Definition at line 892 of file ObjectPtr.h.
References NoInit, and ObjectPtr.
TNonAccessTrackedObjectPtr() [3/3]
template<typename T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::TNonAccessTrackedObjectPtr (T * Ptr) inline explicit
Definition at line 897 of file ObjectPtr.h.
References ObjectPtr.
Member Function Documentation
Get()
template<typename T> T * ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::Get () const inline
Definition at line 908 of file ObjectPtr.h.
References ObjectPtr_Private::Friend::NoAccessTrackingGet(), and ObjectPtr.
Referenced by operator T*(), operator UPTRINT(), and operator->().
GetAccessTrackedObjectPtr() [1/2]
template<typename T> TObjectPtr< T > & ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::GetAccessTrackedObjectPtr () inline
Definition at line 923 of file ObjectPtr.h.
References ObjectPtr.
GetAccessTrackedObjectPtr() [2/2]
template<typename T> const TObjectPtr< T > & ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::GetAccessTrackedObjectPtr () const inline
Definition at line 928 of file ObjectPtr.h.
References ObjectPtr.
GetNoResolve()
template<typename T> UE_INTERNAL T * ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::GetNoResolve () const inline
Definition at line 913 of file ObjectPtr.h.
References ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve(), ObjectPtr, and UE_INTERNAL.
operator T*()
template<typename T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::operator T* () const inline
Definition at line 933 of file ObjectPtr.h.
References Get().
operator UPTRINT()
template<typename T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::operator UPTRINT () const inline explicit
Definition at line 918 of file ObjectPtr.h.
References BitCast(), and Get().
operator->()
template<typename T> T * ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::operator-> () const inline
Definition at line 938 of file ObjectPtr.h.
References Get().
operator=()
template<typename T> TNonAccessTrackedObjectPtr & ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::operator= (T * Value) inline
Definition at line 902 of file ObjectPtr.h.
References TNonAccessTrackedObjectPtr(), ObjectPtr, and Value.
Field Documentation
ObjectPtr
template<typename T> TObjectPtr<T> ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >::ObjectPtr private
Definition at line 944 of file ObjectPtr.h.
Referenced by TNonAccessTrackedObjectPtr(), TNonAccessTrackedObjectPtr(), Get(), GetAccessTrackedObjectPtr(), GetAccessTrackedObjectPtr(), GetNoResolve(), and operator=().
The documentation for this class was generated from the following file:
ObjectPtr.h