Unreal Engine 5.6 C++ API: FBrushBuilderDragDropOp Class Reference
FBrushBuilderDragDropOp Class Reference
#include "BrushBuilderDragDropOp.h"
Public Member Functions
~FBrushBuilderDragDropOp ()
Operation Construct ()
Constructs the window and widget if applicable.
DRAG_DROP_OPERATOR_TYPE (FBrushBuilderDragDropOp, FDragDropOperation) static TSharedRef< FBrushBuilderDragDropOp > New(TWeakObjectPtr< UBrushBuilder > InBrushBuilder
TWeakObjectPtr< UBrushBuilder > GetBrushBuilder () const
virtual TSharedPtr< class SWidget > GetDefaultDecorator () const override
Gets the widget that will serve as the decorator unless overridden.
virtual void OnDragged (const FDragDropEvent &DragDropEvent) override
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent) override
Invoked when the drag and drop operation has ended.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
const FSlateBrush bool bInIsAddtive
const FSlateBrush * InIconBrush
Operation MouseCursor = EMouseCursor::GrabHandClosed
return Operation
Private Member Functions
FBrushBuilderDragDropOp (TWeakObjectPtr< UBrushBuilder > InBrushBuilder, const FSlateBrush *InIconBrush, bool bInIsAdditive)
Private Attributes
bool bIsAdditive
Additive or subtractive mode.
TWeakObjectPtr< UBrushBuilder > BrushBuilder
The brush builder.
const FSlateBrush * IconBrush
The icon to display when dragging.
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Detailed Description
Definition at line 17 of file BrushBuilderDragDropOp.h.
Constructor & Destructor Documentation
~FBrushBuilderDragDropOp()
FBrushBuilderDragDropOp::~FBrushBuilderDragDropOp () inline
Definition at line 32 of file BrushBuilderDragDropOp.h.
References GEditor.
FBrushBuilderDragDropOp()
FBrushBuilderDragDropOp::FBrushBuilderDragDropOp (TWeakObjectPtr< UBrushBuilder > InBrushBuilder, const FSlateBrush * InIconBrush, bool bInIsAdditive) inline private
Definition at line 104 of file BrushBuilderDragDropOp.h.
References bIsAdditive, BrushBuilder, GEditor, IconBrush, and InIconBrush.
Referenced by DRAG_DROP_OPERATOR_TYPE().
Member Function Documentation
Construct()
Operation FBrushBuilderDragDropOp::Construct () virtual
Constructs the window and widget if applicable.
Reimplemented from FDragDropOperation.
References Operation.
DRAG_DROP_OPERATOR_TYPE()
FBrushBuilderDragDropOp::DRAG_DROP_OPERATOR_TYPE (FBrushBuilderDragDropOp , FDragDropOperation)
References FBrushBuilderDragDropOp(), and FDragDropOperation::FDragDropOperation().
GetBrushBuilder()
TWeakObjectPtr< UBrushBuilder > FBrushBuilderDragDropOp::GetBrushBuilder () const inline
Definition at line 98 of file BrushBuilderDragDropOp.h.
References BrushBuilder.
GetDefaultDecorator()
virtual TSharedPtr< class SWidget > FBrushBuilderDragDropOp::GetDefaultDecorator () const inline override virtual
Gets the widget that will serve as the decorator unless overridden.
If you do not override, you will have no decorator
Reimplemented from FDragDropOperation.
Definition at line 81 of file BrushBuilderDragDropOp.h.
References FAppStyle::GetBrush(), IconBrush, and SNew.
OnDragged()
virtual void FBrushBuilderDragDropOp::OnDragged (const FDragDropEvent & DragDropEvent) inline override virtual
Definition at line 66 of file BrushBuilderDragDropOp.h.
References FDragDropOperation::CursorDecoratorWindow, GEditor, and FDragDropOperation::OnDragged().
OnDrop()
virtual void FBrushBuilderDragDropOp::OnDrop (bool bDropWasHandled, const FPointerEvent & MouseEvent) inline override virtual
Invoked when the drag and drop operation has ended.
Parameters
bDropWasHandled true when the drop was handled by some widget; false otherwise
MouseEvent The mouse event which caused the on drop to be called.
Reimplemented from FDragDropOperation.
Definition at line 42 of file BrushBuilderDragDropOp.h.
References bIsAdditive, BrushBuilder, DuplicateObject(), GEditor, FLevelUtils::IsLevelLocked(), MouseEvent, FDragDropOperation::OnDrop(), and TEXT.
Field Documentation
bInIsAddtive
const FSlateBrush bool FBrushBuilderDragDropOp::bInIsAddtive
Initial value:
{
        TSharedRef<FBrushBuilderDragDropOp> Operation = MakeShareable(new FBrushBuilderDragDropOp(InBrushBuilder, InIconBrush, bInIsAddtive))
Definition at line 22 of file BrushBuilderDragDropOp.h.
bIsAdditive
bool FBrushBuilderDragDropOp::bIsAdditive private
Additive or subtractive mode.
Definition at line 126 of file BrushBuilderDragDropOp.h.
Referenced by FBrushBuilderDragDropOp(), and OnDrop().
BrushBuilder
TWeakObjectPtr<UBrushBuilder> FBrushBuilderDragDropOp::BrushBuilder private
The brush builder.
Definition at line 120 of file BrushBuilderDragDropOp.h.
Referenced by FBrushBuilderDragDropOp(), GetBrushBuilder(), and OnDrop().
IconBrush
const FSlateBrush* FBrushBuilderDragDropOp::IconBrush private
The icon to display when dragging.
Definition at line 123 of file BrushBuilderDragDropOp.h.
Referenced by FBrushBuilderDragDropOp(), and GetDefaultDecorator().
InIconBrush
const FSlateBrush* FBrushBuilderDragDropOp::InIconBrush
Definition at line 22 of file BrushBuilderDragDropOp.h.
Referenced by FBrushBuilderDragDropOp().
MouseCursor
Operation FBrushBuilderDragDropOp::MouseCursor = EMouseCursor::GrabHandClosed
Definition at line 26 of file BrushBuilderDragDropOp.h.
Operation
return FBrushBuilderDragDropOp::Operation
Definition at line 29 of file BrushBuilderDragDropOp.h.
Referenced by Construct().
The documentation for this class was generated from the following file:
BrushBuilderDragDropOp.h