Unreal Engine 5.6 C++ API: IIoDispatcherBackend Struct Reference
IIoDispatcherBackend Struct Reference abstract
I/O dispatcher backend interface.
#include "IoDispatcherBackend.h"
Public Member Functions
virtual void CancelIoRequest (FIoRequestImpl *Request)=0
Cancel the I/O request.
virtual bool DoesChunkExist (const FIoChunkId &ChunkId) const =0
Returns whether the chunk exists.
virtual bool DoesChunkExist (const FIoChunkId &ChunkId, const FIoOffsetAndLength &ChunkRange) const
Returns whether specified range of the chunk exists.
virtual FIoRequestImpl * GetCompletedIoRequests ()=0
Returns all completed request(s) to the I/O dispatcher.
virtual const TCHAR * GetName () const =0
Returns the name of this backend, for logging purposes.
virtual TIoStatusOr< uint64 > GetSizeForChunk (const FIoChunkId &ChunkId) const =0
Returns the size of the chunk.
virtual TIoStatusOr< uint64 > GetSizeForChunk (const FIoChunkId &ChunkId, const FIoOffsetAndLength &ChunkRange, uint64 &OutAvailable) const
Returns the size of the chunk and the size of the requested range.
virtual void Initialize (TSharedRef< const FIoDispatcherBackendContext > Context)=0
Called by the I/O dispatcher once initialized.
virtual TIoStatusOr< FIoMappedRegion > OpenMapped (const FIoChunkId &ChunkId, const FIoReadOptions &Options)=0
Read the chunk as a memory mapped file.
virtual void ResolveIoRequests (FIoRequestList Requests, FIoRequestList &OutUnresolved)=0
Create asynchronous read requests for the list of I/O request(s).
virtual void Shutdown ()
Called by the I/O dispatcher when shutting down.
virtual void UpdatePriorityForIoRequest (FIoRequestImpl *Request)=0
Update the priority of the I/O request.
Detailed Description
I/O dispatcher backend interface.
The following methods are called from the I/O dispatcher thread:
ResolveIoRequests
CancelIoRequest
UpdatePriorityForIoRequest
GetCompletedRequests
All other methods can be called from any thread.
Definition at line 185 of file IoDispatcherBackend.h.
Member Function Documentation
CancelIoRequest()
virtual void IIoDispatcherBackend::CancelIoRequest (FIoRequestImpl * Request) pure virtual
Cancel the I/O request.
DoesChunkExist() [1/2]
virtual bool IIoDispatcherBackend::DoesChunkExist (const FIoChunkId & ChunkId) const pure virtual
Returns whether the chunk exists.
DoesChunkExist() [2/2]
virtual bool IIoDispatcherBackend::DoesChunkExist (const FIoChunkId & ChunkId, const FIoOffsetAndLength & ChunkRange) const inline virtual
Returns whether specified range of the chunk exists.
Definition at line 221 of file IoDispatcherBackend.h.
References DoesChunkExist().
Referenced by DoesChunkExist().
GetCompletedIoRequests()
virtual FIoRequestImpl * IIoDispatcherBackend::GetCompletedIoRequests () pure virtual
Returns all completed request(s) to the I/O dispatcher.
Triggered by invoking the wake-up callback on the backend context object.
GetName()
virtual const TCHAR * IIoDispatcherBackend::GetName () const pure virtual
Returns the name of this backend, for logging purposes.
GetSizeForChunk() [1/2]
virtual TIoStatusOr< uint64 > IIoDispatcherBackend::GetSizeForChunk (const FIoChunkId & ChunkId) const pure virtual
Returns the size of the chunk.
Referenced by GetSizeForChunk().
GetSizeForChunk() [2/2]
virtual TIoStatusOr< uint64 > IIoDispatcherBackend::GetSizeForChunk (const FIoChunkId & ChunkId, const FIoOffsetAndLength & ChunkRange, uint64 & OutAvailable) const inline virtual
Returns the size of the chunk and the size of the requested range.
Definition at line 227 of file IoDispatcherBackend.h.
References GetSizeForChunk(), TIoStatusOr< T >::IsOk(), and TIoStatusOr< T >::ValueOrDie().
Initialize()
virtual void IIoDispatcherBackend::Initialize (TSharedRef< const FIoDispatcherBackendContext > Context) pure virtual
Called by the I/O dispatcher once initialized.
Parameters
Context Context object used for signalling the I/O dispatcher.
OpenMapped()
virtual TIoStatusOr< FIoMappedRegion > IIoDispatcherBackend::OpenMapped (const FIoChunkId & ChunkId, const FIoReadOptions & Options) pure virtual
Read the chunk as a memory mapped file.
ResolveIoRequests()
virtual void IIoDispatcherBackend::ResolveIoRequests (FIoRequestList Requests, FIoRequestList & OutUnresolved) pure virtual
Create asynchronous read requests for the list of I/O request(s).
The request(s) can span multiple chunks.
Parameters
Requests Request(s) to resolve.
OutUnresolved Unresolved request(s) returned to the I/O dispatcher.
Shutdown()
virtual void IIoDispatcherBackend::Shutdown () inline virtual
Called by the I/O dispatcher when shutting down.
Definition at line 194 of file IoDispatcherBackend.h.
UpdatePriorityForIoRequest()
virtual void IIoDispatcherBackend::UpdatePriorityForIoRequest (FIoRequestImpl * Request) pure virtual
Update the priority of the I/O request.
The documentation for this struct was generated from the following file:
IoDispatcherBackend.h