Unreal Engine 5.6 C++ API: FMacPlatformProcess::FProcEnumerator Class Reference
FMacPlatformProcess::FProcEnumerator Class Reference
Process enumerator.
#include "MacPlatformProcess.h"
Public Member Functions
FProcEnumerator ()
FProcEnumerator (const FProcEnumerator &)=delete
~FProcEnumerator ()
FProcEnumInfo GetCurrent () const
bool MoveNext ()
Moves current to the next process.
FProcEnumerator & operator= (const FProcEnumerator &)=delete
Private Attributes
uint32 CurrentProcIndex
uint32 ProcCount
struct kinfo_proc * Processes
Detailed Description
Process enumerator.
Definition at line 163 of file MacPlatformProcess.h.
Constructor & Destructor Documentation
FProcEnumerator() [1/2]
FMacPlatformProcess::FProcEnumerator::FProcEnumerator ()
Referenced by FProcEnumerator(), and operator=().
FProcEnumerator() [2/2]
FMacPlatformProcess::FProcEnumerator::FProcEnumerator (const FProcEnumerator &) delete
References FProcEnumerator().
~FProcEnumerator()
FMacPlatformProcess::FProcEnumerator::~FProcEnumerator ()
Member Function Documentation
GetCurrent()
FProcEnumInfo FMacPlatformProcess::FProcEnumerator::GetCurrent () const
MoveNext()
bool FMacPlatformProcess::FProcEnumerator::MoveNext ()
Moves current to the next process.
Returns
True if succeeded. False otherwise.
operator=()
FProcEnumerator & FMacPlatformProcess::FProcEnumerator::operator= (const FProcEnumerator &) delete
References FProcEnumerator().
Field Documentation
CurrentProcIndex
uint32 FMacPlatformProcess::FProcEnumerator::CurrentProcIndex private
Definition at line 192 of file MacPlatformProcess.h.
ProcCount
uint32 FMacPlatformProcess::FProcEnumerator::ProcCount private
Definition at line 189 of file MacPlatformProcess.h.
Processes
struct kinfo_proc* FMacPlatformProcess::FProcEnumerator::Processes private
Definition at line 186 of file MacPlatformProcess.h.
The documentation for this class was generated from the following file:
MacPlatformProcess.h