Unreal Engine 5.6 C++ API: UE::Sequencer::SOutlinerView Class Reference
UE::Sequencer::SOutlinerView Class Reference
The tree view used in the sequencer.
#include "SOutlinerView.h"
Data Structures
struct FCachedGeometry
Structure used to cache physical geometry for a particular node.
Public Member Functions
SOutlinerView ()
~SOutlinerView ()
void AddPinnedTreeView (TSharedPtr< SOutlinerView > PinnedTreeView)
Add a SOutlinerView object that should be modified or updated when this Treeview is updated.
void Construct (const FArguments &InArgs, TWeakPtr< FOutlinerViewModel > InWeakOutliner, const TSharedRef< STrackAreaView > &InTrackArea)
Construct this widget.
void ExpandCollapseNode (TViewModelPtr< IOutlinerExtension > InDataModel, bool bExpansionState, ETreeRecursion Recursion)
Set the item's expansion state, including all of its children.
void ForceSetSelectedItems (const TSet< TWeakViewModelPtr< IOutlinerExtension > > &InItems)
const TArray< FCachedGeometry > & GetAllVisibleNodes () const
Access all the physical nodes currently visible on the sequencer.
int32 GetNumRootNodes () const
TSharedPtr< FOutlinerViewModel > GetOutlinerModel () const
float GetVirtualTop () const
void GetVisibleItems (TArray< TViewModelPtr< IOutlinerExtension > > &OutItems) const
TViewModelPtr< IOutlinerExtension > HitTestNode (float InPhysical) const
Get the tree item model at the specified physical vertical position.
bool IsColumnVisible (const FName &InName) const
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
float PhysicalToVirtual (float InPhysical) const
Convert the specified physical vertical position into an absolute virtual position, ignoring expanded states.
void Refresh ()
Refresh this tree as a result of the underlying tree data changing.
void ReportChildRowGeometry (const TViewModelPtr< IOutlinerExtension > &InNode, const FGeometry &InGeometry)
void ScrollByDelta (float DeltaInSlateUnits)
Scroll this tree view by the specified number of slate units.
void SetOutlinerColumns (const TArray< TSharedPtr< IOutlinerColumn > > &InOutlinerColumns)
Updates the list of visible outliner columns and regenerates columns in the outliner view.
void SetPrimaryTreeView (TSharedPtr< SOutlinerView > InPrimaryTreeView)
Set a SOutlinerView object this Treeview is pinned to, for operations that should happen on the primary.
void SetShowPinned (bool bShowPinned)
Set whether this TreeView should show only pinned nodes or only non-pinned nodes.
SLATE_ARGUMENT (TSharedPtr< FSequencerCoreSelection >, Selection) SLATE_ARGUMENT(TSharedPtr< SScrollBar >
Externally supplied scroll bar.
SLATE_BEGIN_ARGS (SOutlinerView)
ExternalScrollbar SLATE_END_ARGS () static const FName TrackNameColumn
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
See SWidget::Tick()
void ToggleExpandCollapseNodes (ETreeRecursion Recursion=ETreeRecursion::Recursive, bool bExpandAll=false, bool bCollapseAll=false)
Expand or collapse nodes.
float VirtualToPhysical (float InVirtual) const
Convert the specified absolute virtual position into a physical position in the tree.
Public Member Functions inherited from STreeView< TWeakViewModelPtr< IOutlinerExtension > >
STreeView ()
Default constructor.
void ClearExpandedItems ()
Clears the entire set of expanded items.
void ClearRootItemsSource ()
virtual TSharedRef< ITableRow > GenerateNewWidget (TWeakViewModelPtr< IOutlinerExtension > InItem) override
Given a TreeItem, create a Widget to represent it in the tree view.
void GetExpandedItems (TItemSet &ExpandedItems) const
Generates a set of items that are currently expanded.
TArrayView< const TWeakViewModelPtr< IOutlinerExtension > > GetRootItems () const
bool HasValidRootItemsSource () const
bool IsItemExpanded (const TWeakViewModelPtr< IOutlinerExtension > &InItem) const
bool PopulateLinearizedItems (TArrayView< const TWeakViewModelPtr< IOutlinerExtension > > InItemsSource, TArray< TWeakViewModelPtr< IOutlinerExtension > > &InLinearizedItems, TArray< FItemInfo > &NewDenseItemInfos, TBitArray<> NeedsParentWire, TItemSet &OutNewSelectedItems, TSparseItemMap &NewSparseItemInfo, bool bAddingItems, int32 ParentIndex)
Given: an array of items (ItemsSource) each of which potentially has a child.
int32 PopulatePinnedItems (const TArray< TWeakViewModelPtr< IOutlinerExtension > > &InItemsSource, TArray< TWeakViewModelPtr< IOutlinerExtension > > &InPinnedItems, const STableViewBase::FReGenerateResults &Results)
virtual void RebuildList () override
Completely wipe existing widgets and fully regenerate them on next tick.
virtual STableViewBase::FReGenerateResults ReGenerateItems (const FGeometry &MyGeometry) override
Update generate Widgets for Items as needed and clean up any Widgets that are no longer needed.
virtual void RequestListRefresh () override
Queue up a regeneration of the linearized items on the next tick.
void RequestTreeRefresh ()
void SetItemExpansion (const TWeakViewModelPtr< IOutlinerExtension > &InItem, bool InShouldExpandItem)
Set whether some data item is expanded or not.
void SetRootItemsSource (const TArray< TWeakViewModelPtr< IOutlinerExtension > > *InItemsSource)
Set the Root items.
void SetSingleExpandedItem (const TWeakViewModelPtr< IOutlinerExtension > &InItem)
Collapse all the items in the tree and expand InItem.
void SetStyle (const FTableViewStyle *InStyle)
void SetTreeItemsSource (const TArray< TWeakViewModelPtr< IOutlinerExtension > > *InItemsSource)
Set the TreeItemsSource.
OnItemsRebuilt OnMouseButtonDoubleClick OnExpansionChanged SLATE_EVENT(FIsSelectableOrNavigable, OnIsSelectableOrNavigable) SLATE_ATTRIBUTE(ESelectionMode SLATE_ARGUMENT (EAllowOverscroll, AllowOverscroll)
OnGenerateRow OnRefreshRow OnTreeViewScrolled OnItemScrolledIntoView OnSetExpansionRecursive The ItemHeight is only used for Tile See ShouldArrangeAsTiles SLATE_ATTRIBUTE (int32, MaxPinnedItems)
SLATE_BEGIN_ARGS (STreeView< TWeakViewModelPtr< IOutlinerExtension > >)
OnGenerateRow SLATE_EVENT (FOnGenerateRow, OnGeneratePinnedRow) SLATE_EVENT(FOnRefreshRow
OnGenerateRow OnRefreshRow OnTreeViewScrolled OnItemScrolledIntoView OnSetExpansionRecursive SLATE_ITEMS_SOURCE_ARGUMENT (TWeakViewModelPtr< IOutlinerExtension >, TreeItemsSource) SLATE_ATTRIBUTE_DEPRECATED(float
SLATE_STYLE_ARGUMENT (FTableViewStyle, TreeViewStyle) SLATE_EVENT(FOnGenerateRow
UE_DEPRECATED (5.3, "SetItemsSource is deprecated. You probably want to use SetTreeItemsSource.") void SetItemsSource(const TArray< TWeakViewModelPtr< IOutlinerExtension > > *InListItemsSource)
Public Member Functions inherited from SListView< TWeakViewModelPtr< IOutlinerExtension > >
PRAGMA_DISABLE_DEPRECATION_WARNINGS SListView (ETableViewMode::Type InListMode=ETableViewMode::List)
virtual TSharedRef< SWidget > AsWidget () override
void BindToRefreshRow (const FOnRefreshRow &Binding)
void ClearHighlightedItems ()
Empty the highlighted item set.
void ClearItemsSource ()
void ClearSelection ()
Empty the selection set.
DECLARE_DELEGATE_OneParam (FOnWidgetToBeRemoved, const TSharedRef< ITableRow > &)
DECLARE_DELEGATE_TwoParams (FOnEntryInitialized, TWeakViewModelPtr< IOutlinerExtension >, const TSharedRef< ITableRow > &)
virtual TSharedRef< ITableRow > GenerateNewPinnedWidget (TWeakViewModelPtr< IOutlinerExtension > InItem, const int32 ItemIndex, const int32 NumPinnedItems)
void GeneratePinnedWidgetForItem (const TWeakViewModelPtr< IOutlinerExtension > &CurItem, int32 ItemIndex, int32 NumPinnedItems, float LayoutScaleMultiplier)
float GenerateWidgetForItem (const TWeakViewModelPtr< IOutlinerExtension > &CurItem, int32 ItemIndex, int32 StartIndex, float LayoutScaleMultiplier)
TArrayView< const TWeakViewModelPtr< IOutlinerExtension > > GetItems () const
virtual int32 GetNumItemsBeingObserved () const override
int32 GetNumItemsSelected () const
Gets the number of selected items.
virtual TArray< TWeakViewModelPtr< IOutlinerExtension > > GetSelectedItems () const override
Returns a list of selected item indices, or an empty array if nothing is selected.
virtual ETableViewMode::Type GetTableViewMode () const override
bool HasValidItemsSource () const
bool IsItemSelected (const TWeakViewModelPtr< IOutlinerExtension > &InItem) const
Test if the current item is selected.
bool IsItemVisible (TWeakViewModelPtr< IOutlinerExtension > Item) const
Checks whether the specified item is currently visible in the list view.
const TObjectPtrWrapTypeOf< TWeakViewModelPtr< IOutlinerExtension > > * ItemFromWidget (const ITableRow *WidgetToFind) const
Given a Widget, find the corresponding data item.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent) override
Called when navigation is requested e.g.
virtual void Private_ClearHighlightedItems () override
Empty the set of highlighted items.
virtual int32 Private_GetNumSelectedItems () const override
virtual EOrientation Private_GetOrientation () const override
virtual ESelectionMode::Type Private_GetSelectionMode () const override
virtual bool Private_HasSelectorFocus (const TWeakViewModelPtr< IOutlinerExtension > &TheItem) const override
Test if the item passed in has selector focus.
virtual bool Private_IsItemHighlighted (const TWeakViewModelPtr< IOutlinerExtension > &TheItem) const override
Test if the current item should be highlighted.
virtual bool Private_IsItemSelectableOrNavigable (const TWeakViewModelPtr< IOutlinerExtension > &TheItem) const override
Test if the current item can be selected or navigated to.
virtual bool Private_IsItemSelected (const TWeakViewModelPtr< IOutlinerExtension > &TheItem) const override
Test if the current item is selected.
virtual bool Private_IsPendingRefresh () const override
Is the list pending a refresh?
virtual const TObjectPtrWrapTypeOf< TWeakViewModelPtr< IOutlinerExtension > > * Private_ItemFromWidget (const ITableRow *TheWidget) const override
Given a Widget, find the corresponding data item.
void Private_OnEntryInitialized (TWeakViewModelPtr< IOutlinerExtension > TheItem, const TSharedRef< ITableRow > &TableRow)
virtual bool Private_OnItemClicked (TWeakViewModelPtr< IOutlinerExtension > TheItem) override
Called when the item is clicked, and returns whether or not the event was handled.
virtual bool Private_OnItemDoubleClicked (TWeakViewModelPtr< IOutlinerExtension > TheItem) override
Called when the item is double-clicked, and returns whether or not the event was handled.
virtual void Private_OnItemRightClicked (TWeakViewModelPtr< IOutlinerExtension > TheItem, const FPointerEvent &MouseEvent) override
Called when the item is right-clicked when not right mouse scrolling.
virtual void Private_SelectRangeFromCurrentTo (TWeakViewModelPtr< IOutlinerExtension > InRangeSelectionEnd) override
Select a range of items from the current RangeSelectionStart to the SelectorItem Does not cause an OnSelectionChanged()!
virtual void Private_SetItemHighlighted (TWeakViewModelPtr< IOutlinerExtension > TheItem, bool bShouldBeHighlighted) override
Enable a soft highlight on the element.
virtual void Private_SetItemSelection (TWeakViewModelPtr< IOutlinerExtension > TheItem, bool bShouldBeSelected, bool bWasUserDirected=false) override
Set the selection state of an item.
virtual bool Private_UsesSelectorFocus () const override
Returns whether the table view uses selector focus.
void ReGeneratePinnedItems (const TArray< TWeakViewModelPtr< IOutlinerExtension > > &InItems, const FGeometry &MyGeometry, int32 MaxPinnedItemsOverride=-1)
void RequestScrollIntoView (TWeakViewModelPtr< IOutlinerExtension > ItemToView, const uint32 UserIndex=0)
Scroll an item into view.
void SetItemHighlighted (const TWeakViewModelPtr< IOutlinerExtension > &TheItem, bool bHighlighted)
Set the highlighted state of an item.
void SetItemSelection (const TWeakViewModelPtr< IOutlinerExtension > &InItem, bool bSelected, ESelectInfo::Type SelectInfo=ESelectInfo::Direct)
Set the selection state of an item.
void SetItemsSource (const TArray< TWeakViewModelPtr< IOutlinerExtension > > *InListItemsSource)
Establishes a wholly new list of items being observed by the list.
void SetOnEntryInitialized (const FOnEntryInitialized &Delegate)
Sets the OnEntryInitializer delegate.
void SetStyle (const FTableViewStyle *InStyle)
OnGenerateRow OnRefreshRow OnRowReleased OnItemScrolledIntoView ListItemsSource MaxPinnedItems OnItemsRebuilt OnMouseButtonDoubleClick OnIsSelectableOrNavigable HeaderRow SLATE_ARGUMENT (bool, ClearSelectionOnClick) SLATE_ARGUMENT(TSharedPtr< SScrollBar >
OnGenerateRow OnRefreshRow OnRowReleased OnItemScrolledIntoView ListItemsSource MaxPinnedItems OnItemsRebuilt OnMouseButtonDoubleClick OnIsSelectableOrNavigable SLATE_ATTRIBUTE (ESelectionMode::Type, SelectionMode) SLATE_ARGUMENT(TSharedPtr< SHeaderRow >
OnGenerateRow OnRefreshRow OnRowReleased OnItemScrolledIntoView ListItemsSource SLATE_ATTRIBUTE_DEPRECATED (float, ItemHeight, 5.5, "The ItemHeight is only used for Tile. See ShouldArrangeAsTiles") SLATE_ATTRIBUTE(int32
SLATE_BEGIN_ARGS (SListView< TWeakViewModelPtr< IOutlinerExtension > >)
OnGenerateRow SLATE_EVENT (FOnGenerateRow, OnGeneratePinnedRow) SLATE_EVENT(FOnRefreshRow
SLATE_STYLE_ARGUMENT (FTableViewStyle, ListViewStyle) SLATE_EVENT(FOnGenerateRow
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
UE_DEPRECATED (5.2, "SetListItemsSource is deprecated. Please use the correct SetItemsSource implementation.") void SetListItemsSource(const TArray< TWeakViewModelPtr< IOutlinerExtension > > &InListItemsSource)
virtual void UpdateSelectionSet () override
Remove any items that are no longer in the list from the selection set.
Public Member Functions inherited from STableViewBase
void AddScrollOffset (const float InScrollOffsetDelta, bool RefreshList=false)
Add the scroll offset of this view (in items)
virtual bool ComputeVolatility () const override
Recomputes the volatility of the widget.
void ConstructChildren (const TAttribute< float > &InItemWidth, const TAttribute< float > &InItemHeight, const TAttribute< EListItemAlignment > &InItemAlignment, const TSharedPtr< SHeaderRow > &InHeaderRow, const TSharedPtr< SScrollBar > &InScrollBar, EOrientation InScrollOrientation, const FOnTableViewScrolled &InOnTableViewScrolled, const FScrollBarStyle *InScrollBarStyle=nullptr, const bool bInPreventThrottling=false)
Create the child widgets that comprise the list.
void EndInertialScrolling (const bool bInShouldStopScrollNow=false)
Reset the inertial scroll velocity accumulated in the InertialScrollManager.
TSharedPtr< SWidget > GetGeneratedChildAt (int32 Index) const
TSharedPtr< SHeaderRow > GetHeaderRow () const
int32 GetNumGeneratedChildren () const
EVisibility GetScrollbarVisibility () const
virtual FVector2D GetScrollDistance () override
Gets the distance that user has scrolled into the control in normalized coordinates (0 - 1)
virtual FVector2D GetScrollDistanceRemaining () override
Gets the distance that user has left to scroll in the control before reaching the end in normalized coordinates (0 - 1)
float GetScrollOffset () const
Gets the scroll offset of this view (in items)
virtual TSharedRef< class SWidget > GetScrollWidget () override
Returns the typed SWidget that implements this interface.
bool IsPendingRefresh () const
Return true if there is currently a refresh pending, false otherwise.
bool IsRightClickScrolling () const
bool IsScrollbarNeeded () const
Returns true if scrolling is possible; false if the view is big enough to fit all the content.
bool IsScrolling () const
Returns whether the attached scrollbar is scrolling.
bool IsUserScrolling () const
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when the mouse wheel is spun.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is started (finger down)
void ScrollBar_OnUserScrolled (float InScrollOffsetFraction)
Invoked by the scrollbar when the user scrolls.
void ScrollToBottom ()
Scrolls the view to the bottom.
void ScrollToTop ()
Scrolls the view to the top.
void SetAllowOverscroll (EAllowOverscroll InAllowOverscroll)
Sets whether to permit overscroll on this list view.
void SetBackgroundBrush (const TAttribute< const FSlateBrush * > &InBackgroundBrush)
Sets the Background Brush.
void SetEnableTouchAnimatedScrolling (bool bInEnableTouchAnimatedScrolling)
Sets whether the list should lerp between scroll offsets or jump instantly between them with touch.
void SetFixedLineScrollOffset (TOptional< double > InFixedLineScrollOffset)
Sets the fixed offset in items to always apply to the top/left (depending on orientation) of the list.
void SetIsGamepadScrollingEnabled (bool bInIsGamepadScrollingEnabled)
Enables/disables being able to scroll via gamepad.
void SetIsPointerScrollingEnabled (bool bInIsPointerScrollingEnabled)
Enables/disables being able to scroll via pointer.
void SetIsRightClickScrollingEnabled (const bool bInEnableRightClickScrolling)
Enables/disables being able to scroll with the right mouse button.
void SetIsScrollAnimationEnabled (bool bInEnableScrollAnimation)
Sets whether the list should lerp between scroll offsets or jump instantly between them.
void SetIsTouchScrollingEnabled (const bool bInEnableTouchScrolling)
Enables/disables being able to scroll using touch input.
void SetItemHeight (TAttribute< float > Height)
Sets the item height.
void SetItemWidth (TAttribute< float > Width)
Sets the item width.
void SetScrollbarPadding (const FMargin &InScrollbarPadding)
void SetScrollbarVisibility (const EVisibility InVisibility)
void SetScrollingAnimationInterpolationSpeed (float InScrollingAnimationInterpolationSpeed)
Sets the speed of lerp between scroll offsets.
void SetScrollOffset (const float InScrollOffset)
Set the scroll offset of this view (in items)
void SetSelectItemOnNavigation (const bool bInSelectItemOnNavigation)
Sets whether items will be selected and focused or only focused when navigating to them.
void SetWheelScrollMultiplier (float NewWheelScrollMultiplier)
Sets the multiplier applied when wheel scrolling.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from IScrollableWidget
virtual ~IScrollableWidget ()
Public Member Functions inherited from ITypedTableView< TWeakViewModelPtr< IOutlinerExtension > >
virtual TSharedPtr< ITableRow > WidgetFromItem (const TWeakViewModelPtr< IOutlinerExtension > &InItem) const=0
Find a widget for this item if it has already been constructed.
Protected Types
using FColumnGenerator = TFunction<TSharedPtr<SWidget>(const FCreateOutlinerColumnParams& Params, const TSharedRef<SOutlinerViewRow>&)>
Protected Types inherited from STableViewBase
enum class EScrollIntoViewResult { Success , Deferred , Failure }
Protected Member Functions
void ClearSelection ()
int32 CreateOutlinerColumnsForGroup (int32 ColumnIndex, EOutlinerColumnGroup Group)
void CreateTrackLanesForRow (TSharedRef< SOutlinerViewRow > InRow, TViewModelPtr< IOutlinerExtension > InDataModel)
TSharedPtr< STrackLane > FindOrCreateParentLane (TViewModelPtr< IOutlinerExtension > InDataModel)
TSharedRef< SWidget > GenerateWidgetForColumn (TViewModelPtr< IOutlinerExtension > InDataModel, const FName &ColumnId, const TSharedRef< SOutlinerViewRow > &Row) const
Generate a widget for the specified Node and Column.
void HandleTableViewScrolled (double InScrollOffset)
void InsertSeparatorColumn (int32 InsertIndex, int32 SeparatorID)
Insert a separator column at the specified column index, with a unique identifier.
TSharedPtr< SWidget > OnContextMenuOpening ()
Handles the context menu opening when right clicking on the tree view.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
FReply OnDragRow (const FGeometry &InGeometry, const FPointerEvent &InPointerEvent, TSharedRef< SOutlinerViewRow > InRow)
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
void OnExpansionChanged (TWeakViewModelPtr< IOutlinerExtension > InItem, bool bIsExpanded)
Called when a node has been expanded or collapsed.
virtual TSharedRef< ITableRow > OnGenerateRow (TWeakViewModelPtr< IOutlinerExtension > InDisplayNode, const TSharedRef< STableViewBase > &OwnerTable)
Generate a row for a particular node.
void OnGetChildren (TWeakViewModelPtr< IOutlinerExtension > InParent, TArray< TWeakViewModelPtr< IOutlinerExtension > > &OutChildren) const
Gather the children from the specified node.
FString OnItemToString_Debug (TWeakViewModelPtr< IOutlinerExtension > InWeakModel)
virtual void OnRightMouseButtonDown (const FPointerEvent &MouseEvent) override
virtual void OnRightMouseButtonUp (const FPointerEvent &MouseEvent) override
Opens a context menu as the result of a right click if OnContextMenuOpening is bound and we are not right click scrolling.
virtual void Private_ClearSelection () override
Empty the selection set.
virtual void Private_SelectRangeFromCurrentTo (TWeakViewModelPtr< IOutlinerExtension > InRangeSelectionEnd) override
virtual void Private_SetItemSelection (TWeakViewModelPtr< IOutlinerExtension > TheItem, bool bShouldBeSelected, bool bWasUserDirected=false) override
virtual void Private_SignalSelectionChanged (ESelectInfo::Type SelectInfo) override
Notify the ItemsWidget that we changed its selection.
virtual void Private_UpdateParentHighlights () override
This clears the highlight state from all nodes and then traverses the parents of each selected node to add it to the highlighted set.
void SetItemExpansionRecursive (TWeakViewModelPtr< IOutlinerExtension > InItem, bool bIsExpanded)
void SetItemSelection ()
void UpdateModelSelectionFromView ()
void UpdateOutlinerColumns ()
Populate the map of column definitions, and add relevant columns to the header row.
void UpdatePhysicalGeometry (bool bIsRefresh)
void UpdateViewSelectionFromModel ()
Protected Member Functions inherited from SListView< TWeakViewModelPtr< IOutlinerExtension > >
FReply OnKeyDown_Internal (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Protected Member Functions inherited from STableViewBase
STableViewBase (ETableViewMode::Type InTableViewMode)
virtual ~STableViewBase ()
void AppendPinnedWidget (const TSharedRef< SWidget > &WidgetToAppend)
Add a WidgetToAppend to the bottom of the pinned view.
void AppendWidget (const TSharedRef< ITableRow > &WidgetToAppend)
Add a WidgetToAppend to the bottom of the view.
bool CanUseInertialScroll (float ScrollAmount) const
Check whether the current state of the table warrants inertial scroll by the specified amount.
void ClearPinnedWidgets ()
Remove all the pinned widgets from the view.
void ClearWidgets ()
Remove all the widgets from the view.
EActiveTimerReturnType EnsureTickToRefresh (double InCurrentTime, float InDeltaTime)
One-off active timer to refresh the contents of the table as needed.
int32 FindChildUnderPosition (FArrangedChildren &ArrangedChildren, const FVector2D &ArrangedSpacePosition) const
Util function to find the child index under the given position.
const FChildren * GetConstructedTableItems () const
virtual float GetFirstLineScrollOffset () const
Get the offset of the first list item.
float GetItemHeight () const
Get the uniform item height that is enforced by ListViews.
UE::Slate::FDeprecateVector2DResult GetItemSize () const
Get the uniform item.
float GetItemWidth () const
Get the uniform item width.
virtual int32 GetNumItemsPerLine () const
Get the number of items that can fit in the view along the line axis (orthogonal to the scroll axis) before creating a new line.
virtual float GetNumLiveWidgets () const
int32 GetNumPinnedItems () const
float GetScrollRateInItems () const
Get the scroll rate in items that best approximates a constant physical scroll rate.
double GetTargetScrollOffset () const
Returns the "true" scroll offset where the list will ultimately settle (and may already be).
void InsertPinnedWidget (const TSharedRef< SWidget > &WidgetToInset)
Insert WidgetToInsert at the top of the pinned view.
void InsertWidget (const TSharedRef< ITableRow > &WidgetToInset)
Insert WidgetToInsert at the top of the view.
void NavigateToWidget (const uint32 UserIndex, const TSharedPtr< SWidget > &NavigationDestination, ENavigationSource NavigationSource=ENavigationSource::FocusedWidget) const
Util Function so templates classes don't need to include SlateApplication.
virtual void NotifyFinishedScrolling ()=0
Called at the end of a Tick when.
virtual void NotifyItemScrolledIntoView ()=0
Called when an item has entered the visible geometry to check to see if the ItemScrolledIntoView delegate should be fired.
virtual void OnClippingChanged () override
Passing over the clipping to SListPanel.
void RequestLayoutRefresh ()
Internal request for a layout update on the next tick (i.e.
virtual float ScrollBy (const FGeometry &MyGeometry, float ScrollByAmount, EAllowOverscroll InAllowOverscroll)
Scroll the list view by some number of screen units.
virtual EScrollIntoViewResult ScrollIntoView (const FGeometry &ListViewGeometry)=0
If there is a pending request to scroll an item into view, do so.
virtual float ScrollTo (float InScrollOffset)
Scroll the view to an offset and resets the inertial scroll velocity.
UE_DEPRECATED (5.5, "The Pinned items visibility is no more an attribute.") 1 EVisibility GetPinnedItemsVisiblity() const
EActiveTimerReturnType UpdateInertialScroll (double InCurrentTime, float InDeltaTime)
Active timer to update the inertial scroll.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bRefreshPhysicalGeometry
Whether physical geometry information should be recomputed.
bool bRightMouseButtonDown
Right mouse button is down, don't update sequencer selection.
bool bSelectionChangesPending
Whether we have pending selection changes to broadcast.
bool bShowPinnedNodes
Whether this tree is for pinned nodes or non-pinned nodes.
bool bUpdatingTreeSelection
When true, the tree selection is being updated from a change in the sequencer selection.
TMap< FName, FColumnGenerator > ColumnGenerators
Column definitions for each of the columns in the tree view.
TSharedPtr< FOutlinerHeaderRowWidgetMetaData > ColumnMetaData
MetaData pertaining to each column within HeaderRow.
TUniquePtr< FSelectionEventSuppressor > DelayedEventSuppressor
TSharedPtr< SHeaderRow > HeaderRow
The tree view's header row (hidden)
TArray< TSharedPtr< IOutlinerColumn > > OutlinerColumns
Visible Outliner columns to display in the outliner view.
TArray< FCachedGeometry > PhysicalNodes
Linear, sorted array of nodes that we currently have generated widgets for.
TArray< TSharedPtr< SOutlinerView > > PinnedTreeViews
SOutlinerView objects that should be modified or updated when this Treeview is updated.
TWeakPtr< SOutlinerView > PrimaryTreeView
The SOutlinerView object this SOutlinerView is pinned to, or nullptr if not pinned.
TArray< TWeakViewModelPtr< IOutlinerExtension > > RootNodes
Cached copy of the root nodes from the tree data.
TSharedPtr< FSequencerCoreSelection > Selection
TSharedPtr< STrackAreaView > TrackArea
Strong pointer to the track area so we can generate track lanes as we need them.
float VirtualTop
TWeakPtr< FOutlinerViewModel > WeakOutliner
The outliner view model.
Protected Attributes inherited from STreeView< TWeakViewModelPtr< IOutlinerExtension > >
TArray< FItemInfo > DenseItemInfos
Info needed by every item in the linearized version of the tree.
TArray< TWeakViewModelPtr< IOutlinerExtension > > LinearizedItems
A linearized version of the items being observed by the tree view.
FOnExpansionChanged OnExpansionChanged
The delegate that is invoked whenever an item in the tree is expanded or collapsed.
FOnGetChildren OnGetChildren
The delegate that is invoked whenever we need to gather an item's children.
FOnSetExpansionRecursive OnSetExpansionRecursive
The delegate that is invoked to recursively expand/collapse a tree items children.
TSparseItemMap SparseItemInfos
Info needed by a small fraction of tree items; some of these are not visible to the user.
const FTableViewStyle * Style
Style resource for the tree.
Protected Attributes inherited from STableViewBase
EAllowOverscroll AllowOverscroll
Whether to permit overscroll on this list view.
float AmountScrolledWhileRightMouseDown
How much we scrolled while the rmb has been held.
FInvalidatableBrushAttribute BackgroundBrush
Brush resource representing the background area of the view.
bool bEnableAnimatedScrolling = false
True to lerp smoothly between offsets when the desired scroll offset changes.
bool bEnableRightClickScrolling = true
True to allow right click drag scrolling.
bool bEnableTouchAnimatedScrolling = false
True to lerp smoothly between offsets when the desired scroll offset changes with touch.
bool bEnableTouchScrolling = true
True to allow scrolling by using touch input.
bool bIsGamepadScrollingEnabled = true
Whether the list is allowed to scroll via gamepad.
bool bIsPointerScrollingEnabled = true
Whether the list is allowed to scroll via cursor.
bool bIsScrollingActiveTimerRegistered
Whether the active timer to update the inertial scrolling is currently registered.
bool bSelectItemOnNavigation = true
If true, items will be "selected" (in addition to focused) when navigating to them.
bool bShowSoftwareCursor
Whether the software cursor should be drawn in the viewport.
bool bStartedTouchInteraction
Did the user start an interaction in this list?
bool bWasAtEndOfList
Last time we scrolled, did we end up at the end of the list.
EConsumeMouseWheel ConsumeMouseWheel
How we should handle scrolling with the mouse wheel.
double CurrentScrollOffset = 0.
The currently displayed scroll offset from the beginning of the list in items.
double DesiredScrollOffset = 0.
The raw desired scroll offset from the beginning of the list in items.
TOptional< double > FixedLineScrollOffset
The fixed offset in lines to always apply to the top/left (depending on orientation) of the list.
TSharedPtr< SHeaderRow > HeaderRow
Column headers that describe which columns this list shows.
FInertialScrollManager InertialScrollManager
Helper object to manage inertial scrolling.
TSharedPtr< SListPanel > ItemsPanel
The panel which holds the visible widgets in this list.
FReGenerateResults LastGenerateResults
Information about the widgets we generated during the last regenerate pass.
FOnContextMenuOpening OnContextMenuOpening
Delegate to invoke when the context menu should be opening.
FSimpleDelegate OnItemsRebuilt
Delegate to invoke after the children have been regenerated.
FOnTableViewScrolled OnTableViewScrolled
Delegate to call when the table view is scrolled.
EOrientation Orientation = Orient_Vertical
The layout and scroll orientation of the list.
FOverscroll Overscroll
FGeometry PanelGeometryLastTick
What the list's geometry was the last time a refresh occurred.
TSharedPtr< SListPanel > PinnedItemsPanel
The panel which holds the pinned widgets in this list.
FVector2f PressedScreenSpacePosition
The location in screenspace the view was pressed.
TSharedPtr< SScrollBar > ScrollBar
The scroll bar widget.
FMargin ScrollBarSlotPadding
Padding to the scrollbox.
float ScrollingAnimationInterpolationSpeed = 12.f
The speed of interpolation for the scrolling animation.
TAttribute< ESelectionMode::Type > SelectionMode
The selection mode that this tree/list is in.
FVector2f SoftwareCursorPosition
The current position of the software cursor.
float TickScrollDelta
The amount we have scrolled this tick cycle.
float WheelScrollMultiplier
How much to scroll when using mouse wheel.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Public Types inherited from STreeView< TWeakViewModelPtr< IOutlinerExtension > >
using FIsSelectableOrNavigable
using FOnExpansionChanged
using FOnGenerateRow
using FOnGetChildren
using FOnItemScrolledIntoView
using FOnItemToString_Debug
using FOnMouseButtonClick
using FOnMouseButtonDoubleClick
using FOnRefreshRow
using FOnSelectionChanged
using FOnSetExpansionRecursive
using FOnWidgetToBeRemoved
using MapKeyFuncs
using MapKeyFuncsSparse
using NullableItemType
using TItemSet
using TSparseItemMap
Public Types inherited from SListView< TWeakViewModelPtr< IOutlinerExtension > >
using FIsSelectableOrNavigable
using FOnGenerateRow
using FOnItemScrolledIntoView
typedef TSlateDelegates< TWeakViewModelPtr< IOutlinerExtension > >::FOnItemToString_Debug FOnItemToString_Debug
using FOnMouseButtonClick
using FOnMouseButtonDoubleClick
using FOnRefreshRow
using FOnSelectionChanged
using MapKeyFuncs
using MapKeyFuncsSparse
using NullableItemType
using TItemSet
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields inherited from STreeView< TWeakViewModelPtr< IOutlinerExtension > >
OnGenerateRow OnRefreshRow OnTreeViewScrolled OnItemScrolledIntoView OnSetExpansionRecursive ItemHeight
OnEnteredBadState
WheelScrollMultiplier
Data Fields inherited from SListView< TWeakViewModelPtr< IOutlinerExtension > >
bool bClearScrollVelocityOnSelection
True to force the scroll velocity to reset to 0 when an item of the list is selected.
bool bClearSelectionOnClick
If true, the selection will be cleared if the user clicks in empty space (not on an item)
bool bHandleDirectionalNavigation
Should directional nav be supported.
bool bHandleGamepadEvents
Should gamepad nav be supported.
bool bHandleSpacebarSelection
Should space bar based selection be supported.
bool bIsHierarchyCollapsed
If true, number of pinned items > MaxPinnedItems so some items are collapsed in the hierarchy.
bool bNavigateOnScrollIntoView
If true, the item currently slated to be scrolled into view will also be navigated to after being scrolled in.
bool bReturnFocusToSelection
If true, the focus will be returned to the last selected object in a list when navigated to.
TAttribute< int32 > DefaultMaxPinnedItems
The initial value of MaxPinnedItems (used to restore it back if overriden)
TItemSet HighlightedItems
A set of which items should be highlighted.
TAttribute< bool > IsFocusable
True when the list view supports keyboard focus.
NullableItemType ItemToNotifyWhenInView
When set, the list will notify this item when it has been scrolled into view.
NullableItemType ItemToScrollIntoView
When not null, the list will try to scroll to this item on tick.
TAttribute< int32 > MaxPinnedItems
The maximum number of pinned items allowed.
const uint32 const bool NavigateOnScrollIntoView
float NavigationScrollOffset
The additional scroll offset (in items) to show when navigating to rows at the edge of the visible area (i.e.
FOnMouseButtonClick OnClick
Called when the user clicks on an element in the list view with the left mouse button.
FOnMouseButtonDoubleClick OnDoubleClick
Called when the user double-clicks on an element in the list view with the left mouse button.
FOnTableViewBadState OnEnteredBadState
Invoked when the tree enters a bad state.
FOnEntryInitialized OnEntryInitialized
Invoked after initializing an entry being generated, before it may be added to the actual widget hierarchy.
FOnFinishedScrolling OnFinishedScrolling
Delegate to be invoked when TargetScrollOffset is reached at the end of a Tick.
FOnGenerateRow OnGeneratePinnedRow
Delegate to be invoked when the list needs to generate a new pinned widget from a data item.
FOnGenerateRow OnGenerateRow
Delegate to be invoked when the list needs to generate a new widget from a data item.
FIsSelectableOrNavigable OnIsSelectableOrNavigable
Delegate to invoke to see if we can navigate or select item.
FOnItemScrolledIntoView OnItemScrolledIntoView
Delegate to be invoked when an item has come into view after it was requested to come into view.
FOnItemToString_Debug OnItemToString_Debug
Assign this to get more diagnostics from the list view.
FOnKeyDown OnKeyDownHandler
Called when the user presses a keyboard key.
FOnRefreshRow OnRefreshRow
Delegate to be invoked when the list needs to update an existing widget for an item.
FOnWidgetToBeRemoved OnRowReleased
FOnSelectionChanged OnSelectionChanged
Delegate to invoke when selection changes.
FWidgetGenerator PinnedWidgetGenerator
A widget generator component used for pinned items in the list.
NullableItemType RangeSelectionStart
The item which was last manipulated; used as a start for shift-click selection.
EScrollIntoViewAlignment ScrollIntoViewAlignment
How to scroll an item into view.
TItemSet SelectedItems
A set of selected data items.
NullableItemType SelectorItem
The item to manipulate selection for.
const FTableViewStyle * Style
Style resource for the list.
const uint32 UserIndex
uint32 UserRequestingScrollIntoView
The user index requesting the item to be scrolled into view.
Data Fields inherited from STableViewBase
const ETableViewMode::Type TableViewMode
Is this list backing a tree or just a standalone list.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The tree view used in the sequencer.
Definition at line 68 of file SOutlinerView.h.
Member Typedef Documentation
FColumnGenerator
using UE::Sequencer::SOutlinerView::FColumnGenerator = TFunction<TSharedPtr<SWidget>(const FCreateOutlinerColumnParams& Params, const TSharedRef<SOutlinerViewRow>&)> protected
Definition at line 238 of file SOutlinerView.h.
Constructor & Destructor Documentation
SOutlinerView()
UE::Sequencer::SOutlinerView::SOutlinerView ()
References SOutlinerView().
Referenced by SOutlinerView(), ~SOutlinerView(), and SLATE_BEGIN_ARGS().
~SOutlinerView()
UE::Sequencer::SOutlinerView::~SOutlinerView ()
References SOutlinerView().
Member Function Documentation
AddPinnedTreeView()
void UE::Sequencer::SOutlinerView::AddPinnedTreeView (TSharedPtr< SOutlinerView > PinnedTreeView)
Add a SOutlinerView object that should be modified or updated when this Treeview is updated.
ClearSelection()
void UE::Sequencer::SOutlinerView::ClearSelection () protected
Construct()
void UE::Sequencer::SOutlinerView::Construct (const FArguments & InArgs, TWeakPtr< FOutlinerViewModel > InWeakOutliner, const TSharedRef< STrackAreaView > & InTrackArea)
Construct this widget.
References Construct().
Referenced by Construct().
CreateOutlinerColumnsForGroup()
int32 UE::Sequencer::SOutlinerView::CreateOutlinerColumnsForGroup (int32 ColumnIndex, EOutlinerColumnGroup Group) protected
References Group.
CreateTrackLanesForRow()
void UE::Sequencer::SOutlinerView::CreateTrackLanesForRow (TSharedRef< SOutlinerViewRow > InRow, TViewModelPtr< IOutlinerExtension > InDataModel) protected
ExpandCollapseNode()
void UE::Sequencer::SOutlinerView::ExpandCollapseNode (TViewModelPtr< IOutlinerExtension > InDataModel, bool bExpansionState, ETreeRecursion Recursion)
Set the item's expansion state, including all of its children.
FindOrCreateParentLane()
TSharedPtr< STrackLane > UE::Sequencer::SOutlinerView::FindOrCreateParentLane (TViewModelPtr< IOutlinerExtension > InDataModel) protected
ForceSetSelectedItems()
void UE::Sequencer::SOutlinerView::ForceSetSelectedItems (const TSet< TWeakViewModelPtr< IOutlinerExtension > > & InItems)
GenerateWidgetForColumn()
TSharedRef< SWidget > UE::Sequencer::SOutlinerView::GenerateWidgetForColumn (TViewModelPtr< IOutlinerExtension > InDataModel, const FName & ColumnId, const TSharedRef< SOutlinerViewRow > & Row) const protected
Generate a widget for the specified Node and Column.
GetAllVisibleNodes()
const TArray< FCachedGeometry > & UE::Sequencer::SOutlinerView::GetAllVisibleNodes () const inline
Access all the physical nodes currently visible on the sequencer.
Definition at line 205 of file SOutlinerView.h.
References PhysicalNodes.
GetNumRootNodes()
int32 UE::Sequencer::SOutlinerView::GetNumRootNodes () const inline
Returns
the number of root nodes this tree contains
Definition at line 94 of file SOutlinerView.h.
References GetNumRootNodes(), and RootNodes.
Referenced by GetNumRootNodes().
GetOutlinerModel()
TSharedPtr< FOutlinerViewModel > UE::Sequencer::SOutlinerView::GetOutlinerModel () const
References GetOutlinerModel().
Referenced by GetOutlinerModel().
GetVirtualTop()
float UE::Sequencer::SOutlinerView::GetVirtualTop () const
GetVisibleItems()
void UE::Sequencer::SOutlinerView::GetVisibleItems (TArray< TViewModelPtr< IOutlinerExtension > > & OutItems) const
HandleTableViewScrolled()
void UE::Sequencer::SOutlinerView::HandleTableViewScrolled (double InScrollOffset) protected
HitTestNode()
TViewModelPtr< IOutlinerExtension > UE::Sequencer::SOutlinerView::HitTestNode (float InPhysical) const
Get the tree item model at the specified physical vertical position.
InsertSeparatorColumn()
void UE::Sequencer::SOutlinerView::InsertSeparatorColumn (int32 InsertIndex, int32 SeparatorID) protected
Insert a separator column at the specified column index, with a unique identifier.
IsColumnVisible()
bool UE::Sequencer::SOutlinerView::IsColumnVisible (const FName & InName) const
References InName.
OnContextMenuOpening()
TSharedPtr< SWidget > UE::Sequencer::SOutlinerView::OnContextMenuOpening () protected
Handles the context menu opening when right clicking on the tree view.
OnDragOver()
virtual FReply UE::Sequencer::SOutlinerView::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override protected virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
OnDragRow()
FReply UE::Sequencer::SOutlinerView::OnDragRow (const FGeometry & InGeometry, const FPointerEvent & InPointerEvent, TSharedRef< SOutlinerViewRow > InRow) protected
OnDrop()
virtual FReply UE::Sequencer::SOutlinerView::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override protected virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
OnExpansionChanged()
void UE::Sequencer::SOutlinerView::OnExpansionChanged (TWeakViewModelPtr< IOutlinerExtension > InItem, bool bIsExpanded) protected
Called when a node has been expanded or collapsed.
OnGenerateRow()
virtual TSharedRef< ITableRow > UE::Sequencer::SOutlinerView::OnGenerateRow (TWeakViewModelPtr< IOutlinerExtension > InDisplayNode, const TSharedRef< STableViewBase > & OwnerTable) protected virtual
Generate a row for a particular node.
OnGetChildren()
void UE::Sequencer::SOutlinerView::OnGetChildren (TWeakViewModelPtr< IOutlinerExtension > InParent, TArray< TWeakViewModelPtr< IOutlinerExtension > > & OutChildren) const protected
Gather the children from the specified node.
OnItemToString_Debug()
FString UE::Sequencer::SOutlinerView::OnItemToString_Debug (TWeakViewModelPtr< IOutlinerExtension > InWeakModel) protected
OnKeyDown()
virtual FReply UE::Sequencer::SOutlinerView::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
OnPaint()
virtual int32 UE::Sequencer::SOutlinerView::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from STableViewBase.
References SWidget::FSlateWindowElementList, and OnPaint().
Referenced by OnPaint().
OnRightMouseButtonDown()
virtual void UE::Sequencer::SOutlinerView::OnRightMouseButtonDown (const FPointerEvent & MouseEvent) override protected virtual
Reimplemented from STableViewBase.
References MouseEvent.
OnRightMouseButtonUp()
virtual void UE::Sequencer::SOutlinerView::OnRightMouseButtonUp (const FPointerEvent & MouseEvent) override protected virtual
Opens a context menu as the result of a right click if OnContextMenuOpening is bound and we are not right click scrolling.
Reimplemented from STableViewBase.
References MouseEvent.
PhysicalToVirtual()
float UE::Sequencer::SOutlinerView::PhysicalToVirtual (float InPhysical) const
Convert the specified physical vertical position into an absolute virtual position, ignoring expanded states.
Private_ClearSelection()
virtual void UE::Sequencer::SOutlinerView::Private_ClearSelection () override protected virtual
Empty the selection set.
Reimplemented from SListView< TWeakViewModelPtr< IOutlinerExtension > >.
Private_SelectRangeFromCurrentTo()
virtual void UE::Sequencer::SOutlinerView::Private_SelectRangeFromCurrentTo (TWeakViewModelPtr< IOutlinerExtension > InRangeSelectionEnd) override protected virtual
Private_SetItemSelection()
virtual void UE::Sequencer::SOutlinerView::Private_SetItemSelection (TWeakViewModelPtr< IOutlinerExtension > TheItem, bool bShouldBeSelected, bool bWasUserDirected = false) override protected virtual
Private_SignalSelectionChanged()
virtual void UE::Sequencer::SOutlinerView::Private_SignalSelectionChanged (ESelectInfo::Type SelectInfo) override protected virtual
Notify the ItemsWidget that we changed its selection.
Triggers as OnSelectionChanged().
Parameters
SelectInfo Provides context on how the selection changed
Reimplemented from STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
Private_UpdateParentHighlights()
virtual void UE::Sequencer::SOutlinerView::Private_UpdateParentHighlights () override protected virtual
This clears the highlight state from all nodes and then traverses the parents of each selected node to add it to the highlighted set.
Reimplemented from STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
Refresh()
void UE::Sequencer::SOutlinerView::Refresh ()
Refresh this tree as a result of the underlying tree data changing.
ReportChildRowGeometry()
void UE::Sequencer::SOutlinerView::ReportChildRowGeometry (const TViewModelPtr< IOutlinerExtension > & InNode, const FGeometry & InGeometry)
ScrollByDelta()
void UE::Sequencer::SOutlinerView::ScrollByDelta (float DeltaInSlateUnits)
Scroll this tree view by the specified number of slate units.
SetItemExpansionRecursive()
void UE::Sequencer::SOutlinerView::SetItemExpansionRecursive (TWeakViewModelPtr< IOutlinerExtension > InItem, bool bIsExpanded) protected
SetItemSelection()
void UE::Sequencer::SOutlinerView::SetItemSelection () protected
SetOutlinerColumns()
void UE::Sequencer::SOutlinerView::SetOutlinerColumns (const TArray< TSharedPtr< IOutlinerColumn > > & InOutlinerColumns)
Updates the list of visible outliner columns and regenerates columns in the outliner view.
SetPrimaryTreeView()
void UE::Sequencer::SOutlinerView::SetPrimaryTreeView (TSharedPtr< SOutlinerView > InPrimaryTreeView) inline
Set a SOutlinerView object this Treeview is pinned to, for operations that should happen on the primary.
Definition at line 211 of file SOutlinerView.h.
References PrimaryTreeView.
SetShowPinned()
void UE::Sequencer::SOutlinerView::SetShowPinned (bool bShowPinned) inline
Set whether this TreeView should show only pinned nodes or only non-pinned nodes.
Definition at line 214 of file SOutlinerView.h.
References bShowPinnedNodes.
SLATE_ARGUMENT()
UE::Sequencer::SOutlinerView::SLATE_ARGUMENT (TSharedPtr< FSequencerCoreSelection > , Selection)
Externally supplied scroll bar.
References Selection.
SLATE_BEGIN_ARGS()
UE::Sequencer::SOutlinerView::SLATE_BEGIN_ARGS (SOutlinerView) inline
Definition at line 73 of file SOutlinerView.h.
References SOutlinerView().
SLATE_END_ARGS()
ExternalScrollbar UE::Sequencer::SOutlinerView::SLATE_END_ARGS () const
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Tick()
virtual void UE::Sequencer::SOutlinerView::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) virtual
See SWidget::Tick()
Parameters
AllottedGeometry The space allotted for this widget.
InCurrentTime Current absolute real time.
InDeltaTime Real time passed since last tick.
Reimplemented from STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
References Tick().
Referenced by Tick().
ToggleExpandCollapseNodes()
void UE::Sequencer::SOutlinerView::ToggleExpandCollapseNodes (ETreeRecursion Recursion = ETreeRecursion::Recursive, bool bExpandAll = false, bool bCollapseAll = false)
Expand or collapse nodes.
References UE::Sequencer::Recursive.
UpdateModelSelectionFromView()
void UE::Sequencer::SOutlinerView::UpdateModelSelectionFromView () protected
UpdateOutlinerColumns()
void UE::Sequencer::SOutlinerView::UpdateOutlinerColumns () protected
Populate the map of column definitions, and add relevant columns to the header row.
Must be called when outliner columns change
UpdatePhysicalGeometry()
void UE::Sequencer::SOutlinerView::UpdatePhysicalGeometry (bool bIsRefresh) protected
UpdateViewSelectionFromModel()
void UE::Sequencer::SOutlinerView::UpdateViewSelectionFromModel () protected
VirtualToPhysical()
float UE::Sequencer::SOutlinerView::VirtualToPhysical (float InVirtual) const
Convert the specified absolute virtual position into a physical position in the tree.
Note
: Will not work reliably for virtual positions that are outside of the physical space
Field Documentation
bRefreshPhysicalGeometry
bool UE::Sequencer::SOutlinerView::bRefreshPhysicalGeometry protected
Whether physical geometry information should be recomputed.
Definition at line 285 of file SOutlinerView.h.
bRightMouseButtonDown
bool UE::Sequencer::SOutlinerView::bRightMouseButtonDown protected
Right mouse button is down, don't update sequencer selection.
Definition at line 276 of file SOutlinerView.h.
bSelectionChangesPending
bool UE::Sequencer::SOutlinerView::bSelectionChangesPending protected
Whether we have pending selection changes to broadcast.
Definition at line 282 of file SOutlinerView.h.
bShowPinnedNodes
bool UE::Sequencer::SOutlinerView::bShowPinnedNodes protected
Whether this tree is for pinned nodes or non-pinned nodes.
Definition at line 279 of file SOutlinerView.h.
Referenced by SetShowPinned().
bUpdatingTreeSelection
bool UE::Sequencer::SOutlinerView::bUpdatingTreeSelection protected
When true, the tree selection is being updated from a change in the sequencer selection.
Definition at line 273 of file SOutlinerView.h.
ColumnGenerators
TMap<FName, FColumnGenerator> UE::Sequencer::SOutlinerView::ColumnGenerators protected
Column definitions for each of the columns in the tree view.
Definition at line 253 of file SOutlinerView.h.
ColumnMetaData
TSharedPtr<FOutlinerHeaderRowWidgetMetaData> UE::Sequencer::SOutlinerView::ColumnMetaData protected
MetaData pertaining to each column within HeaderRow.
Definition at line 244 of file SOutlinerView.h.
DelayedEventSuppressor
TUniquePtr<FSelectionEventSuppressor> UE::Sequencer::SOutlinerView::DelayedEventSuppressor protected
Definition at line 256 of file SOutlinerView.h.
HeaderRow
TSharedPtr<SHeaderRow> UE::Sequencer::SOutlinerView::HeaderRow protected
The tree view's header row (hidden)
Definition at line 241 of file SOutlinerView.h.
OutlinerColumns
TArray<TSharedPtr<IOutlinerColumn> > UE::Sequencer::SOutlinerView::OutlinerColumns protected
Visible Outliner columns to display in the outliner view.
Definition at line 268 of file SOutlinerView.h.
PhysicalNodes
TArray<FCachedGeometry> UE::Sequencer::SOutlinerView::PhysicalNodes protected
Linear, sorted array of nodes that we currently have generated widgets for.
Definition at line 222 of file SOutlinerView.h.
Referenced by GetAllVisibleNodes().
PinnedTreeViews
TArray<TSharedPtr<SOutlinerView> > UE::Sequencer::SOutlinerView::PinnedTreeViews protected
SOutlinerView objects that should be modified or updated when this Treeview is updated.
Definition at line 262 of file SOutlinerView.h.
PrimaryTreeView
TWeakPtr<SOutlinerView> UE::Sequencer::SOutlinerView::PrimaryTreeView protected
The SOutlinerView object this SOutlinerView is pinned to, or nullptr if not pinned.
Definition at line 265 of file SOutlinerView.h.
Referenced by SetPrimaryTreeView().
RootNodes
TArray<TWeakViewModelPtr<IOutlinerExtension> > UE::Sequencer::SOutlinerView::RootNodes protected
Cached copy of the root nodes from the tree data.
Definition at line 250 of file SOutlinerView.h.
Referenced by GetNumRootNodes().
Selection
TSharedPtr<FSequencerCoreSelection> UE::Sequencer::SOutlinerView::Selection protected
Definition at line 255 of file SOutlinerView.h.
Referenced by SLATE_ARGUMENT().
TrackArea
TSharedPtr<STrackAreaView> UE::Sequencer::SOutlinerView::TrackArea protected
Strong pointer to the track area so we can generate track lanes as we need them.
Definition at line 259 of file SOutlinerView.h.
VirtualTop
float UE::Sequencer::SOutlinerView::VirtualTop protected
Definition at line 270 of file SOutlinerView.h.
WeakOutliner
TWeakPtr<FOutlinerViewModel> UE::Sequencer::SOutlinerView::WeakOutliner protected
The outliner view model.
Definition at line 247 of file SOutlinerView.h.
The documentation for this class was generated from the following file:
SOutlinerView.h