Unreal Engine 5.6 C++ API: UE::Core::PagedArray::Private Namespace Reference
UE::Core::PagedArray::Private Namespace Reference
Data Structures
class TIteratorBase
TPagedArray iterator base class for TIteratorAdapter.
struct TPageTraits
Page traits struct for TPagedArray.
Typedefs
template<typename InElementType, typename InPageType, typename InPageTraits>
using TIterator = TIteratorAdapter<TIteratorBase<InElementType, InPageType, InPageTraits>>
Functions
template<typename ElementType, int32 PageSizeInBytes, typename AllocatorType>
FArchive & Serialize (FArchive &Ar, TPagedArray< ElementType, PageSizeInBytes, AllocatorType > &InOutPagedArray)
Serializer.
template<typename ElementType, int32 PageSizeInBytes, typename AllocatorType>
void SerializeStructured (FStructuredArchive::FSlot Slot, TPagedArray< ElementType, PageSizeInBytes, AllocatorType > &InOutPagedArray)
Structured archive serializer.
Typedef Documentation
TIterator
template<typename InElementType, typename InPageType, typename InPageTraits> using UE::Core::PagedArray::Private::TIterator = TIteratorAdapter<TIteratorBase<InElementType, InPageType, InPageTraits>>
Definition at line 87 of file Runtime/Core/Public/Containers/PagedArray.h.
Function Documentation
Serialize()
template<typename ElementType, int32 PageSizeInBytes, typename AllocatorType> FArchive & UE::Core::PagedArray::Private::Serialize (FArchive & Ar, TPagedArray< ElementType, PageSizeInBytes, AllocatorType > & InOutPagedArray)
Serializer.
Definition at line 91 of file Runtime/Core/Public/Containers/PagedArray.h.
References Ar, TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CountBytes(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace_GetRef(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Empty(), and TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Num().
Referenced by operator<<().
SerializeStructured()
template<typename ElementType, int32 PageSizeInBytes, typename AllocatorType> void UE::Core::PagedArray::Private::SerializeStructured (FStructuredArchive::FSlot Slot, TPagedArray< ElementType, PageSizeInBytes, AllocatorType > & InOutPagedArray)
Structured archive serializer.
Definition at line 121 of file Runtime/Core/Public/Containers/PagedArray.h.
References Array, TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace_GetRef(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Empty(), FStructuredArchiveSlot::EnterArray(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), and TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Num().
Referenced by operator<<().