Unreal Engine 5.6 C++ API: ITextFormatArgumentModifier.h File Reference
ITextFormatArgumentModifier.h File Reference
#include "CoreTypes.h"
#include "Misc/Crc.h"
#include "Containers/UnrealString.h"
#include "Internationalization/CulturePointer.h"
Data Structures
class FTextFormatString
Type used as a string literal by the text formatter.
class ITextFormatArgumentModifier
Interface for a format argument modifier.
Functions
bool operator!= (const FTextFormatString &LHS, const FTextFormatString &RHS)
bool operator< (const FTextFormatString &LHS, const FTextFormatString &RHS)
bool operator== (const FTextFormatString &LHS, const FTextFormatString &RHS)
Function Documentation
operator!=()
bool operator!= (const FTextFormatString & LHS, const FTextFormatString & RHS) inline
Definition at line 143 of file ITextFormatArgumentModifier.h.
References FTextFormatString::StringLen, FTextFormatString::StringPtr, and TCString< TCHAR >::Strncmp().
operator<()
bool operator< (const FTextFormatString & LHS, const FTextFormatString & RHS) inline
Definition at line 149 of file ITextFormatArgumentModifier.h.
References FTextFormatString::StringLen, FTextFormatString::StringPtr, and TCString< TCHAR >::Strncmp().
operator==()
bool operator== (const FTextFormatString & LHS, const FTextFormatString & RHS) inline
Definition at line 137 of file ITextFormatArgumentModifier.h.
References FTextFormatString::StringLen, FTextFormatString::StringPtr, and TCString< TCHAR >::Strncmp().