Unreal Engine 5.6 C++ API: TStringFormatter< CharType > Class Template Reference
TStringFormatter< CharType > Class Template Reference
A string formatter is responsible for formatting string patterns using a set of named, or ordered arguments.
#include "StringFormatter.h"
Public Member Functions
TStringFormatter ()
TString< CharType > Format (const CharType *InExpression, const TArray< FStringFormatArg > &InArgs) const
Format the specified string using the specified arguments.
TString< CharType > Format (const CharType *InExpression, const TMap< TString< CharType >, FStringFormatArg > &InArgs) const
Format the specified string using the specified arguments.
TValueOrError< TString< CharType >, FExpressionError > FormatStrict (const CharType *InExpression, const TArray< FStringFormatArg > &InArgs) const
Format the specified string using the specified arguments.
TValueOrError< TString< CharType >, FExpressionError > FormatStrict (const CharType *InExpression, const TMap< TString< CharType >, FStringFormatArg > &InArgs) const
Format the specified string using the specified arguments.
Private Member Functions
TValueOrError< TString< CharType >, FExpressionError > FormatInternal (const CharType *InExpression, const TArray< FStringFormatArg > &InArgs, bool bStrict) const
TValueOrError< TString< CharType >, FExpressionError > FormatInternal (const CharType *InExpression, const TMap< TString< CharType >, FStringFormatArg > &InArgs, bool bStrict) const
Internal formatting logic.
Private Attributes
TTokenDefinitions< CharType > NamedDefinitions
Token definitions for lenient lexers.
TTokenDefinitions< CharType > OrderedDefinitions
TTokenDefinitions< CharType > StrictNamedDefinitions
Token definitions for strict lexers.
TTokenDefinitions< CharType > StrictOrderedDefinitions
Detailed Description
template<typename CharType>
class TStringFormatter< CharType >
A string formatter is responsible for formatting string patterns using a set of named, or ordered arguments.
Definition at line 13 of file StringFormatter.h.
Constructor & Destructor Documentation
TStringFormatter()
template<typename CharType> TStringFormatter< CharType >::TStringFormatter ()
Member Function Documentation
Format() [1/2]
template<typename CharType> TString< CharType > TStringFormatter< CharType >::Format (const CharType * InExpression, const TArray< FStringFormatArg > & InArgs) const inline
Format the specified string using the specified arguments.
Replaces instances of {0} with indices from the given array matching the index specified in the token
Parameters
InExpression A string representing the format expression
InArgs An array of ordered arguments that match the tokens specified in InExpression
Returns
A string containing the formatted text
Definition at line 42 of file StringFormatter.h.
References ensure, FormatInternal(), and MoveTemp().
Format() [2/2]
template<typename CharType> TString< CharType > TStringFormatter< CharType >::Format (const CharType * InExpression, const TMap< TString< CharType >, FStringFormatArg > & InArgs) const inline
Format the specified string using the specified arguments.
Replaces instances of { Argument } with keys in the map matching 'Argument'
Parameters
InExpression A string representing the format expression
InArgs A map of named arguments that match the tokens specified in InExpression
Returns
A string containing the formatted text
Definition at line 25 of file StringFormatter.h.
References ensure, FormatInternal(), and MoveTemp().
FormatInternal() [1/2]
template<typename CharType> TValueOrError< TString< CharType >, FExpressionError > TStringFormatter< CharType >::FormatInternal (const CharType * InExpression, const TArray< FStringFormatArg > & InArgs, bool bStrict) const private
FormatInternal() [2/2]
template<typename CharType> TValueOrError< TString< CharType >, FExpressionError > TStringFormatter< CharType >::FormatInternal (const CharType * InExpression, const TMap< TString< CharType >, FStringFormatArg > & InArgs, bool bStrict) const private
Internal formatting logic.
Referenced by Format(), Format(), FormatStrict(), and FormatStrict().
FormatStrict() [1/2]
template<typename CharType> TValueOrError< TString< CharType >, FExpressionError > TStringFormatter< CharType >::FormatStrict (const CharType * InExpression, const TArray< FStringFormatArg > & InArgs) const inline
Format the specified string using the specified arguments.
Replaces instances of {0} with indices from the given array matching the index specified in the token
Parameters
InExpression A string representing the format expression
InArgs An array of ordered arguments that match the tokens specified in InExpression
Returns
A string containing the formatted text, or an error where InExpression is ill-formed, or contains undefined arguments
Definition at line 70 of file StringFormatter.h.
References FormatInternal().
FormatStrict() [2/2]
template<typename CharType> TValueOrError< TString< CharType >, FExpressionError > TStringFormatter< CharType >::FormatStrict (const CharType * InExpression, const TMap< TString< CharType >, FStringFormatArg > & InArgs) const inline
Format the specified string using the specified arguments.
Replaces instances of { Argument } with keys in the map matching 'Argument'
Parameters
InExpression A string representing the format expression
InArgs A map of named arguments that match the tokens specified in InExpression
Returns
A string containing the formatted text, or an error where InExpression is ill-formed, or contains undefined arguments
Definition at line 59 of file StringFormatter.h.
References FormatInternal().
Field Documentation
NamedDefinitions
template<typename CharType> TTokenDefinitions<CharType> TStringFormatter< CharType >::NamedDefinitions private
Token definitions for lenient lexers.
Definition at line 82 of file StringFormatter.h.
OrderedDefinitions
template<typename CharType> TTokenDefinitions<CharType> TStringFormatter< CharType >::OrderedDefinitions private
Definition at line 83 of file StringFormatter.h.
StrictNamedDefinitions
template<typename CharType> TTokenDefinitions<CharType> TStringFormatter< CharType >::StrictNamedDefinitions private
Token definitions for strict lexers.
Definition at line 86 of file StringFormatter.h.
StrictOrderedDefinitions
template<typename CharType> TTokenDefinitions<CharType> TStringFormatter< CharType >::StrictOrderedDefinitions private
Definition at line 87 of file StringFormatter.h.
The documentation for this class was generated from the following file:
StringFormatter.h