Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes > Struct Template Reference
UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
template<typename... ArgTypes>
TEntityAllocationTask (FEntityManager *InEntityManager, const TEntityTaskComponents< ComponentTypes... > &InComponents, ArgTypes &&... InArgs)
template<typename... ArgTypes>
TEntityAllocationTask (FEntityManager *InEntityManager, const TFilteredEntityTask< ComponentTypes... > &InComponentFilter, ArgTypes &&... InArgs)
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &CompletionGraphEvent)
Public Member Functions inherited from UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >
TEntityAllocationTaskBase (FEntityManager *InEntityManager, const TEntityTaskComponents< ComponentTypes... > &InComponents)
ENamedThreads::Type GetDesiredThread () const
TStatId GetStatId () const
void Run (TaskImpl &TaskImplInstance)
Static Public Member Functions
static ESubsequentsMode::Type GetSubsequentsMode ()
Private Attributes
TaskImpl TaskImplInstance
Additional Inherited Members
Protected Types inherited from UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >
using Caller
Protected Attributes inherited from UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >
TFilteredEntityTask< ComponentTypes... > ComponentFilter
FEntityManager * EntityManager
FEntityAllocationWriteContext WriteContext
Detailed Description
template<typename TaskImpl, typename... ComponentTypes>
struct UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >
Definition at line 1761 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TEntityAllocationTask() [1/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename... ArgTypes> UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::TEntityAllocationTask (FEntityManager * InEntityManager, const TEntityTaskComponents< ComponentTypes... > & InComponents, ArgTypes &&... InArgs) inline explicit
Definition at line 1764 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >::TEntityAllocationTaskBase(), Forward(), and TaskImplInstance.
TEntityAllocationTask() [2/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename... ArgTypes> UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::TEntityAllocationTask (FEntityManager * InEntityManager, const TFilteredEntityTask< ComponentTypes... > & InComponentFilter, ArgTypes &&... InArgs) inline explicit
Definition at line 1770 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >::TEntityAllocationTaskBase(), Forward(), and TaskImplInstance.
Member Function Documentation
DoTask()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & CompletionGraphEvent) inline
Definition at line 1780 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkf, UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >::ComponentFilter, UE::MovieScene::TEntityAllocationTaskBase< TaskImpl, ComponentTypes... >::Run(), TaskImplInstance, TEXT, and UE_DEBUG_BREAK.
GetSubsequentsMode()
template<typename TaskImpl, typename... ComponentTypes> ESubsequentsMode::Type UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::GetSubsequentsMode () inline static
Definition at line 1775 of file MovieSceneEntitySystemTask.h.
References ESubsequentsMode::TrackSubsequents.
Field Documentation
TaskImplInstance
template<typename TaskImpl, typename... ComponentTypes> TaskImpl UE::MovieScene::TEntityAllocationTask< TaskImpl, ComponentTypes >::TaskImplInstance private
Definition at line 1797 of file MovieSceneEntitySystemTask.h.
Referenced by TEntityAllocationTask(), TEntityAllocationTask(), and DoTask().
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h