Unreal Engine 5.6 C++ API: FGroomBindingBuildContext Struct Reference
FGroomBindingBuildContext Struct Reference
#include "GroomBindingAsset.h"
Public Member Functions
FGroomBindingBuildContext ()=default
FGroomBindingBuildContext (const FGroomBindingBuildContext &)=delete
FGroomBindingBuildContext (FGroomBindingBuildContext &&)=default
FGroomBindingBuildContext & operator= (const FGroomBindingBuildContext &)=delete
FGroomBindingBuildContext & operator= (FGroomBindingBuildContext &&)=default
Data Fields
bool bReloadResource = false
FOnGroomBindingAssetBuildComplete DynamicCompletionDelegate
TArray< TRefCountPtr< FSkeletalMeshLODRenderData > > MeshLODReferences
FOnGroomBindingAssetBuildCompleteNative NativeCompletionDelegate
int32 SourceMeshLOD = INDEX_NONE
int32 TargetMeshMinLOD = INDEX_NONE
Detailed Description
Definition at line 116 of file GroomBindingAsset.h.
Constructor & Destructor Documentation
FGroomBindingBuildContext() [1/3]
FGroomBindingBuildContext::FGroomBindingBuildContext () default
Referenced by FGroomBindingBuildContext(), FGroomBindingBuildContext(), operator=(), and operator=().
FGroomBindingBuildContext() [2/3]
FGroomBindingBuildContext::FGroomBindingBuildContext (const FGroomBindingBuildContext &) delete
References FGroomBindingBuildContext().
FGroomBindingBuildContext() [3/3]
FGroomBindingBuildContext::FGroomBindingBuildContext (FGroomBindingBuildContext &&) default
References FGroomBindingBuildContext().
Member Function Documentation
operator=() [1/2]
FGroomBindingBuildContext & FGroomBindingBuildContext::operator= (const FGroomBindingBuildContext &) delete
References FGroomBindingBuildContext().
operator=() [2/2]
FGroomBindingBuildContext & FGroomBindingBuildContext::operator= (FGroomBindingBuildContext &&) default
References FGroomBindingBuildContext().
Field Documentation
bReloadResource
bool FGroomBindingBuildContext::bReloadResource = false
Definition at line 135 of file GroomBindingAsset.h.
DynamicCompletionDelegate
FOnGroomBindingAssetBuildComplete FGroomBindingBuildContext::DynamicCompletionDelegate
Definition at line 130 of file GroomBindingAsset.h.
MeshLODReferences
TArray<TRefCountPtr<FSkeletalMeshLODRenderData> > FGroomBindingBuildContext::MeshLODReferences
Definition at line 128 of file GroomBindingAsset.h.
NativeCompletionDelegate
FOnGroomBindingAssetBuildCompleteNative FGroomBindingBuildContext::NativeCompletionDelegate
Definition at line 131 of file GroomBindingAsset.h.
SourceMeshLOD
int32 FGroomBindingBuildContext::SourceMeshLOD = INDEX_NONE
Definition at line 133 of file GroomBindingAsset.h.
TargetMeshMinLOD
int32 FGroomBindingBuildContext::TargetMeshMinLOD = INDEX_NONE
Definition at line 134 of file GroomBindingAsset.h.
The documentation for this struct was generated from the following file:
GroomBindingAsset.h