Unreal Engine 5.6 C++ API: UE::Geometry::TDistSegment3Triangle3< Real > Class Template Reference
UE::Geometry::TDistSegment3Triangle3< Real > Class Template Reference
Compute unsigned distance between 3D segment and 3D triangle.
#include "DistSegment3Triangle3.h"
Public Member Functions
TDistSegment3Triangle3 (const TSegment3< Real > &SegmentIn, const TTriangle3< Real > &TriangleIn)
Real ComputeResult ()
Real Get ()
Real GetSquared ()
Data Fields
Real DistanceSquared = -1.0
TSegment3< Real > Segment
TVector< Real > SegmentClosest
Real SegmentParameter
TTriangle3< Real > Triangle
TVector< Real > TriangleBaryCoords
TVector< Real > TriangleClosest
Detailed Description
template<typename Real>
class UE::Geometry::TDistSegment3Triangle3< Real >
Compute unsigned distance between 3D segment and 3D triangle.
Definition at line 25 of file DistSegment3Triangle3.h.
Constructor & Destructor Documentation
TDistSegment3Triangle3()
template<typename Real> UE::Geometry::TDistSegment3Triangle3< Real >::TDistSegment3Triangle3 (const TSegment3< Real > & SegmentIn, const TTriangle3< Real > & TriangleIn) inline
Definition at line 37 of file DistSegment3Triangle3.h.
Member Function Documentation
ComputeResult()
template<typename Real> Real UE::Geometry::TDistSegment3Triangle3< Real >::ComputeResult () inline
Definition at line 50 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::Get(), and UE::Geometry::TDistSegment3Triangle3< float >::GetSquared().
Get()
template<typename Real> Real UE::Geometry::TDistSegment3Triangle3< Real >::Get () inline
Definition at line 41 of file DistSegment3Triangle3.h.
GetSquared()
template<typename Real> Real UE::Geometry::TDistSegment3Triangle3< Real >::GetSquared () inline
Definition at line 45 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult().
Field Documentation
DistanceSquared
template<typename Real> Real UE::Geometry::TDistSegment3Triangle3< Real >::DistanceSquared = -1.0
Definition at line 33 of file DistSegment3Triangle3.h.
Segment
template<typename Real> TSegment3<Real> UE::Geometry::TDistSegment3Triangle3< Real >::Segment
Definition at line 29 of file DistSegment3Triangle3.h.
SegmentClosest
template<typename Real> TVector<Real> UE::Geometry::TDistSegment3Triangle3< Real >::SegmentClosest
Definition at line 35 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult().
SegmentParameter
template<typename Real> Real UE::Geometry::TDistSegment3Triangle3< Real >::SegmentParameter
Definition at line 34 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult().
Triangle
template<typename Real> TTriangle3<Real> UE::Geometry::TDistSegment3Triangle3< Real >::Triangle
Definition at line 30 of file DistSegment3Triangle3.h.
TriangleBaryCoords
template<typename Real> TVector<Real> UE::Geometry::TDistSegment3Triangle3< Real >::TriangleBaryCoords
Definition at line 35 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult().
TriangleClosest
template<typename Real> TVector<Real> UE::Geometry::TDistSegment3Triangle3< Real >::TriangleClosest
Definition at line 35 of file DistSegment3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::ComputeResult().
The documentation for this class was generated from the following file:
DistSegment3Triangle3.h