Unreal Engine 5.6 C++ API: FPackedRGB10A2N Struct Reference
FPackedRGB10A2N Struct Reference
A vector, quantized and packed into 32-bits.
#include "PackedNormal.h"
Public Member Functions
FPackedRGB10A2N ()
FPackedRGB10A2N (const FVector3d &InVector)
FPackedRGB10A2N (const FVector3f &InVector)
FPackedRGB10A2N (const FVector4f &InVector)
VectorRegister4Float GetVectorRegister () const
bool operator!= (const FPackedRGB10A2N &B) const
void operator= (const FVector3d &InVector)
void operator= (const FVector3f &InVector)
void operator= (const FVector4f &InVector)
bool operator== (const FPackedRGB10A2N &B) const
void Set (const FVector3d &InVector)
void Set (const FVector3f &InVector)
void Set (const FVector4f &InVector)
FString ToString () const
Data Fields
union {
struct {
uint32 W: 2
uint32 X: 10
uint32 Y: 10
uint32 Z: 10
}
struct {
uint32 Packed
}
} Vector
Static Public Attributes
static RENDERCORE_API FPackedRGB10A2N ZeroVector
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FPackedRGB10A2N &N)
Detailed Description
A vector, quantized and packed into 32-bits.
Definition at line 202 of file PackedNormal.h.
Constructor & Destructor Documentation
FPackedRGB10A2N() [1/4]
FPackedRGB10A2N::FPackedRGB10A2N () inline
Definition at line 229 of file PackedNormal.h.
References Vector.
Referenced by operator!=(), operator<<, and operator==().
FPackedRGB10A2N() [2/4]
FPackedRGB10A2N::FPackedRGB10A2N (const FVector3f & InVector) inline
Definition at line 230 of file PackedNormal.h.
FPackedRGB10A2N() [3/4]
FPackedRGB10A2N::FPackedRGB10A2N (const FVector3d & InVector) inline
Definition at line 231 of file PackedNormal.h.
FPackedRGB10A2N() [4/4]
FPackedRGB10A2N::FPackedRGB10A2N (const FVector4f & InVector) inline
Definition at line 232 of file PackedNormal.h.
Member Function Documentation
GetVectorRegister()
FORCEINLINE VectorRegister4Float FPackedRGB10A2N::GetVectorRegister () const
Definition at line 298 of file PackedNormal.h.
References FORCEINLINE, MakeVectorRegister(), VectorLoadURGB10A2N(), VectorMultiplyAdd(), and VectorResetFloatRegisters.
operator!=()
FORCEINLINE bool FPackedRGB10A2N::operator!= (const FPackedRGB10A2N & B) const
Definition at line 293 of file PackedNormal.h.
References FPackedRGB10A2N(), B, and FORCEINLINE.
operator=() [1/3]
FORCEINLINE void FPackedRGB10A2N::operator= (const FVector3d & InVector)
Definition at line 272 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, Vector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator=() [2/3]
FORCEINLINE void FPackedRGB10A2N::operator= (const FVector3f & InVector)
Definition at line 264 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, Vector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator=() [3/3]
FORCEINLINE void FPackedRGB10A2N::operator= (const FVector4f & InVector)
Definition at line 280 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, Vector, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
operator==()
FORCEINLINE bool FPackedRGB10A2N::operator== (const FPackedRGB10A2N & B) const
Definition at line 288 of file PackedNormal.h.
References FPackedRGB10A2N(), B, FORCEINLINE, and Vector.
Set() [1/3]
void FPackedRGB10A2N::Set (const FVector3d & InVector) inline
Definition at line 244 of file PackedNormal.h.
Set() [2/3]
void FPackedRGB10A2N::Set (const FVector3f & InVector) inline
Definition at line 243 of file PackedNormal.h.
Set() [3/3]
void FPackedRGB10A2N::Set (const FVector4f & InVector) inline
Definition at line 245 of file PackedNormal.h.
ToString()
FString FPackedRGB10A2N::ToString () const inline
Definition at line 256 of file PackedNormal.h.
References TEXT, and Vector.
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FPackedRGB10A2N & N) friend
References FPackedRGB10A2N(), and Ar.
Field Documentation
Packed
uint32 FPackedRGB10A2N::Packed
Definition at line 223 of file PackedNormal.h.
[union]
union { ... } FPackedRGB10A2N::Vector
Referenced by FPackedRGB10A2N(), operator=(), operator=(), operator=(), operator==(), and ToString().
W
uint32 FPackedRGB10A2N::W
Definition at line 214 of file PackedNormal.h.
X
uint32 FPackedRGB10A2N::X
Definition at line 217 of file PackedNormal.h.
Y
uint32 FPackedRGB10A2N::Y
Definition at line 216 of file PackedNormal.h.
Z
uint32 FPackedRGB10A2N::Z
Definition at line 215 of file PackedNormal.h.
ZeroVector
RENDERCORE_API FPackedRGB10A2N FPackedRGB10A2N::ZeroVector static
Definition at line 261 of file PackedNormal.h.
The documentation for this struct was generated from the following file:
PackedNormal.h