Unreal Engine 5.6 C++ API: IMappedFileHandle Class Reference
IMappedFileHandle Class Reference abstract
#include "MappedFileHandle.h"
Public Member Functions
IMappedFileHandle (const IMappedFileHandle &)=delete
IMappedFileHandle (size_t InFileSize)
virtual ~IMappedFileHandle ()
Destructor, also the only way to close the file handle.
virtual void Flush (void)
FORCEINLINE int64 GetFileSize () const
Return the size of the mapped file.
virtual IMappedFileRegion * MapRegion (int64 Offset=0, int64 BytesToMap=MAX_int64, FFileMappingFlags Flags=EMappedFileFlags::ENone)=0
Map a region of the file.
IMappedFileHandle & operator= (const IMappedFileHandle &)=delete
Private Attributes
size_t MappedFileSize
Detailed Description
Definition at line 114 of file MappedFileHandle.h.
Constructor & Destructor Documentation
IMappedFileHandle() [1/2]
IMappedFileHandle::IMappedFileHandle (size_t InFileSize) inline
Definition at line 119 of file MappedFileHandle.h.
References INC_DWORD_STAT, and MappedFileSize.
Referenced by IMappedFileHandle(), and operator=().
~IMappedFileHandle()
virtual IMappedFileHandle::~IMappedFileHandle () inline virtual
Destructor, also the only way to close the file handle.
It is not legal to delete an async file with outstanding requests. You must always call WaitCompletion before deleting a request.
Definition at line 125 of file MappedFileHandle.h.
References DEC_DWORD_STAT.
IMappedFileHandle() [2/2]
IMappedFileHandle::IMappedFileHandle (const IMappedFileHandle &) delete
References IMappedFileHandle().
Member Function Documentation
Flush()
virtual void IMappedFileHandle::Flush (void) inline virtual
Definition at line 147 of file MappedFileHandle.h.
GetFileSize()
FORCEINLINE int64 IMappedFileHandle::GetFileSize () const inline
Return the size of the mapped file.
Definition at line 133 of file MappedFileHandle.h.
References FORCEINLINE, and MappedFileSize.
MapRegion()
virtual IMappedFileRegion * IMappedFileHandle::MapRegion (int64 Offset = 0, int64 BytesToMap = MAX_int64, FFileMappingFlags Flags = EMappedFileFlags::ENone) pure virtual
Map a region of the file.
Parameters
Offset Offset into the file to start mapping.
BytesToMap Number of bytes to map. Clamped to the size of the file.
Flags A combination of EMappingFlags values
Returns
the mapped region interface. Returns nullptr on failure.
References ENone, Flags, and MAX_int64.
operator=()
IMappedFileHandle & IMappedFileHandle::operator= (const IMappedFileHandle &) delete
References IMappedFileHandle().
Field Documentation
MappedFileSize
size_t IMappedFileHandle::MappedFileSize private
Definition at line 116 of file MappedFileHandle.h.
Referenced by IMappedFileHandle(), and GetFileSize().
The documentation for this class was generated from the following file:
MappedFileHandle.h