Unreal Engine 5.6 C++ API: FTrackInstancePropertyBindings::FResolvedProperty Struct Reference
FTrackInstancePropertyBindings::FResolvedProperty Struct Reference
Public Member Functions
FResolvedProperty ()
template<typename ValueType>
ValueType * GetPropertyAddress () const
FProperty * GetValidProperty () const
Data Fields
int32 ArrayIndex = INDEX_NONE
void * ContainerAddress
TWeakFieldPtr< FProperty > Property
Detailed Description
Definition at line 490 of file MovieSceneCommonHelpers.h.
Constructor & Destructor Documentation
FResolvedProperty()
FTrackInstancePropertyBindings::FResolvedProperty::FResolvedProperty () inline
Definition at line 527 of file MovieSceneCommonHelpers.h.
References ContainerAddress, and Property.
Member Function Documentation
GetPropertyAddress()
template<typename ValueType> ValueType * FTrackInstancePropertyBindings::FResolvedProperty::GetPropertyAddress () const inline
Definition at line 509 of file MovieSceneCommonHelpers.h.
References ArrayIndex, CastFieldChecked(), check, ContainerAddress, FScriptArrayHelper::GetRawPtr(), GetValidProperty(), INDEX_NONE, and FScriptArrayHelper::IsValidIndex().
Referenced by FTrackInstancePropertyBindings::TryGetPropertyValue().
GetValidProperty()
FProperty * FTrackInstancePropertyBindings::FResolvedProperty::GetValidProperty () const inline
Definition at line 498 of file MovieSceneCommonHelpers.h.
References ContainerAddress, FField::HasAnyFlags(), Property, RF_BeginDestroyed, and RF_FinishDestroyed.
Referenced by FTrackInstancePropertyBindings::CallFunction(), and GetPropertyAddress().
Field Documentation
ArrayIndex
int32 FTrackInstancePropertyBindings::FResolvedProperty::ArrayIndex = INDEX_NONE
Definition at line 496 of file MovieSceneCommonHelpers.h.
Referenced by GetPropertyAddress().
ContainerAddress
void* FTrackInstancePropertyBindings::FResolvedProperty::ContainerAddress
Definition at line 494 of file MovieSceneCommonHelpers.h.
Referenced by FResolvedProperty(), GetPropertyAddress(), and GetValidProperty().
Property
TWeakFieldPtr<FProperty> FTrackInstancePropertyBindings::FResolvedProperty::Property
Definition at line 492 of file MovieSceneCommonHelpers.h.
Referenced by FResolvedProperty(), and GetValidProperty().
The documentation for this struct was generated from the following file:
MovieSceneCommonHelpers.h