Unreal Engine 5.6 C++ API: FOverridableManager Class Reference
FOverridableManager Class Reference
#include "OverridableManager.h"
Public Member Functions
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void ClearInstancedSubObjectOverrides (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Clear all overrides of the specified instanced subobject if it is really owned by the referencer.
bool ClearOverriddenProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
Clears an overridden properties specified by the property chain.
bool ClearOverriddenProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath)
Clears an overridden properties specified by the property chain.
void ClearOverrides (TNotNull< UObject * > Object)
Clears all the overrides on the specified object.
void Disable (TNotNull< UObject * > Object, bool bPropagateToSubObjects=false)
Sets on the specified object to not use overridable serialization.
void DisableInstancedSubObject (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Sets on the specified object to not use overridable serialization Sets the specified instanced subobject to not use overridable serialization if it is really owned by the referencer.
void Enable (TNotNull< UObject * > Object)
Sets on the specified object to use overridable serialization.
template<typename InputType UE_REQUIRES>
auto GetOverriddenProperties (InputType &&Object)
Retrieve the overridden properties for the specified object.
FORCEINLINE EOverriddenPropertyOperation GetOverriddenPropertyOperation (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain, bool *bOutInheritedOperation=nullptr)
Retrieve the overridable operation from the specified the edit property chain.
EOverriddenPropertyOperation GetOverriddenPropertyOperation (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath, bool *bOutInheritedOperation=nullptr)
Retrieve the overridable operation from the specified property path.
EOverriddenState GetOverriddenState (TNotNull< UObject * > Object)
Retrieve the overridden state for the specified object.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
void HandleDeadObjectReferences (const TSet< UClass * > &DeadClasses, const TSet< UObject * > &ActiveInstances, const TSet< UObject * > &TemplateInstances)
void HandleObjectsReInstantiated (const TMap< UObject *, UObject * > &OldToNewInstanceMap)
void InheritEnabledFrom (TNotNull< UObject * > Object, const UObject *DefaultData)
Inherit if the specified object should enable overridable serialization.
bool IsEnabled (TNotNull< const UObject * > Object)
Lookup if the for the specified object has overridable serialization enabled.
bool NeedSubObjectTemplateInstantiation (TNotNull< const UObject * > Object)
Return true if this object needs subobject template instantiation.
void OverrideInstancedSubObject (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Override all the properties of the specified instanced subobject if it is really owned by the referencer.
void OverrideObject (TNotNull< UObject * > Object)
Override the entire object properties and all its instanced subobjects.
void OverrideProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
Override a specific property of an object (Helper methods to call Pre/PostOverride) Note: Supports object that does not have overridable serialization enabled.
void OverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath)
Override a specific property of an object (Helper methods to call Pre/PostOverride) Note: Supports object that does not have overridable serialization enabled.
void PostOverrideProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
To be called after the property was overridden of the specified object Note: Supports object that does not have overridable serialization enabled.
void PostOverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath, const EPropertyChangeType::Type ChangeType)
To be called after the property of the specified object was overridden Note: Supports object that does not have overridable serialization enabled.
void PreOverrideProperty (TNotNull< UObject * > Object, const FEditPropertyChain &PropertyChain)
To be called prior to override a property of the specified object Note: Supports object that does not have overridable serialization enabled.
void PreOverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath)
To be called prior to override a property of the specified object Note: Supports object that does not have overridable serialization enabled.
void PropagateClearOverridesToInstancedSubObjects (TNotNull< UObject * > Object)
Propagate the clear overrides to all instanced suboject of the specified object.
void PropagateOverrideToInstancedSubObjects (TNotNull< UObject * > Object)
Propagate override to all instanced sub object of the specified object.
FOverriddenPropertySet * RestoreOverrideOperation (TNotNull< UObject * > Object, EOverriddenPropertyOperation Operation, const bool bNeedsSubobjectTemplateInstantiation)
Restore the override operation from a saved state on this object, and it will enable it if it wasn't already enabled.
void RestoreOverrideState (TNotNull< const UObject * > OldObject, TNotNull< UObject * > NewObject)
Restore some of the overridden state that is not necessarily restored by the CPFUO (ex: bWasAdded come from the owner of the object and reinstantiating the object does not preserve it)
void SerializeOverriddenProperties (TNotNull< UObject * > Object, FStructuredArchive::FRecord ObjectRecord)
Serializes the overridden properties of the specified object into the record.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static void Create ()
static FOverridableManager & Get ()
static FOverridableManager * TryGet ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Protected Member Functions
FOverridableManager ()
bool ClearOverriddenProperty (TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator)
const FOverriddenPropertySet * GetOverriddenPropertiesInternal (TNotNull< const UObject * > Object)
FOverriddenPropertySet * GetOverriddenPropertiesInternal (TNotNull< UObject * > Object)
EOverriddenPropertyOperation GetOverriddenPropertyOperation (TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator, bool *bOutInheritedOperation=nullptr)
void NotifyPropertyChange (const EPropertyNotificationType Notification, TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator, const EPropertyChangeType::Type ChangeType)
Protected Attributes
friend FOverriddenPropertySet
FUObjectAnnotationSparseBool NeedsSubobjectTemplateInstantiation
Static Protected Attributes
static FOverridableManager * OverridableManager
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
Definition at line 54 of file OverridableManager.h.
Constructor & Destructor Documentation
FOverridableManager()
FOverridableManager::FOverridableManager () protected
Referenced by Get(), and TryGet().
Member Function Documentation
AddReferencedObjects()
virtual void FOverridableManager::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
ClearInstancedSubObjectOverrides()
void FOverridableManager::ClearInstancedSubObjectOverrides (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Clear all overrides of the specified instanced subobject if it is really owned by the referencer.
Parameters
Object referencing the subobject
InstancedSubObject to clear overrides on
References Object.
ClearOverriddenProperty() [1/3]
bool FOverridableManager::ClearOverriddenProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain) inline
Clears an overridden properties specified by the property chain.
Parameters
Object owning the property to clear
PropertyEvent only needed to know about the container item index in any
PropertyChain to the property to clear from the root of the specified object
Returns
true if the property was successfully cleared.
Definition at line 256 of file OverridableManager.h.
References ClearOverriddenProperty(), and Object.
ClearOverriddenProperty() [2/3]
bool FOverridableManager::ClearOverriddenProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath) inline
Clears an overridden properties specified by the property chain.
Parameters
Object owning the property to clear
PropertyPath to the property to clear from the root of the specified object
Returns
true if the property was successfully cleared.
Definition at line 202 of file OverridableManager.h.
References ClearOverriddenProperty(), FPropertyVisitorPath::GetRootIterator(), and Object.
Referenced by ClearOverriddenProperty(), and ClearOverriddenProperty().
ClearOverriddenProperty() [3/3]
bool FOverridableManager::ClearOverriddenProperty (TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator) protected
References Object.
ClearOverrides()
void FOverridableManager::ClearOverrides (TNotNull< UObject * > Object)
Clears all the overrides on the specified object.
Parameters
Object to clear them on
References Object.
Create()
void FOverridableManager::Create () static
Returns
the static instance managing the overridability
Disable()
void FOverridableManager::Disable (TNotNull< UObject * > Object, bool bPropagateToSubObjects = false)
Sets on the specified object to not use overridable serialization.
Parameters
Object to disable
bPropagateToSubObjects true if wants to propagate the disable to all subobjects
References Object.
DisableInstancedSubObject()
void FOverridableManager::DisableInstancedSubObject (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Sets on the specified object to not use overridable serialization Sets the specified instanced subobject to not use overridable serialization if it is really owned by the referencer.
Parameters
Object referencing this subobject
InstancedSubObject the sub object to override all its properties
References Object.
Enable()
void FOverridableManager::Enable (TNotNull< UObject * > Object)
Sets on the specified object to use overridable serialization.
Parameters
Object to enable
References Object.
Get()
FOverridableManager & FOverridableManager::Get () inline static
Returns
the instance managing the overridability
Definition at line 62 of file OverridableManager.h.
References FOverridableManager(), checkf, OverridableManager, and TEXT.
GetOverriddenProperties()
template<typename InputType UE_REQUIRES> auto FOverridableManager::GetOverriddenProperties (InputType && Object) inline
Retrieve the overridden properties for the specified object.
Parameters
Object to fetch the overridden properties
Returns
the overridden properties if the object have overridable serialization enabled
Definition at line 123 of file OverridableManager.h.
References GetOverriddenPropertiesInternal(), and Object.
GetOverriddenPropertiesInternal() [1/2]
const FOverriddenPropertySet * FOverridableManager::GetOverriddenPropertiesInternal (TNotNull< const UObject * > Object) protected
References FOverriddenPropertySet, and Object.
GetOverriddenPropertiesInternal() [2/2]
FOverriddenPropertySet * FOverridableManager::GetOverriddenPropertiesInternal (TNotNull< UObject * > Object) protected
References FOverriddenPropertySet, and Object.
Referenced by GetOverriddenProperties().
GetOverriddenPropertyOperation() [1/3]
FORCEINLINE EOverriddenPropertyOperation FOverridableManager::GetOverriddenPropertyOperation (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain, bool * bOutInheritedOperation = nullptr) inline
Retrieve the overridable operation from the specified the edit property chain.
Parameters
Object owning the property
PropertyEvent only needed to know about the container item index in any
PropertyChain leading to the property the caller is interested in
bOutInheritedOperation optional parameter to know if the operation returned was inherited from a parent property
Returns
the current type of override operation on the property
Definition at line 289 of file OverridableManager.h.
References FORCEINLINE, GetOverriddenPropertyOperation(), and Object.
GetOverriddenPropertyOperation() [2/3]
EOverriddenPropertyOperation FOverridableManager::GetOverriddenPropertyOperation (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath, bool * bOutInheritedOperation = nullptr) inline
Retrieve the overridable operation from the specified property path.
Parameters
Object owning the property
PropertyPath leading to the property the caller is interested in
bOutInheritedOperation optional parameter to know if the operation returned was inherited from a parent property
Returns
the current type of override operation on the property
Definition at line 228 of file OverridableManager.h.
References GetOverriddenPropertyOperation(), FPropertyVisitorPath::GetRootIterator(), and Object.
Referenced by GetOverriddenPropertyOperation(), and GetOverriddenPropertyOperation().
GetOverriddenPropertyOperation() [3/3]
EOverriddenPropertyOperation FOverridableManager::GetOverriddenPropertyOperation (TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator, bool * bOutInheritedOperation = nullptr) protected
References Object.
GetOverriddenState()
EOverriddenState FOverridableManager::GetOverriddenState (TNotNull< UObject * > Object)
Retrieve the overridden state for the specified object.
Parameters
Object to fetch the overridden properties
Returns
the overridden state if the object has overridable serialization enabled
References Object.
GetReferencerName()
virtual FString FOverridableManager::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 300 of file OverridableManager.h.
References TEXT.
HandleDeadObjectReferences()
void FOverridableManager::HandleDeadObjectReferences (const TSet< UClass * > & DeadClasses, const TSet< UObject * > & ActiveInstances, const TSet< UObject * > & TemplateInstances)
HandleObjectsReInstantiated()
void FOverridableManager::HandleObjectsReInstantiated (const TMap< UObject *, UObject * > & OldToNewInstanceMap)
InheritEnabledFrom()
void FOverridableManager::InheritEnabledFrom (TNotNull< UObject * > Object, const UObject * DefaultData)
Inherit if the specified object should enable overridable serialization.
It inherits it from either its default object or its outer.
Parameters
Object to be inherited on
DefaultData its default object
References Object.
IsEnabled()
bool FOverridableManager::IsEnabled (TNotNull< const UObject * > Object)
Lookup if the for the specified object has overridable serialization enabled.
Parameters
Object to check against
Returns
true if it uses the overridable serialization
References Object.
NeedSubObjectTemplateInstantiation()
bool FOverridableManager::NeedSubObjectTemplateInstantiation (TNotNull< const UObject * > Object)
Return true if this object needs subobject template instantiation.
Parameters
Object to be querying about
References Object.
NotifyPropertyChange()
void FOverridableManager::NotifyPropertyChange (const EPropertyNotificationType Notification, TNotNull< UObject * > Object, FPropertyVisitorPath::Iterator PropertyIterator, const EPropertyChangeType::Type ChangeType) protected
References Notification, and Object.
OverrideInstancedSubObject()
void FOverridableManager::OverrideInstancedSubObject (TNotNull< const UObject * > Object, TNotNull< UObject * > InstancedSubObject)
Override all the properties of the specified instanced subobject if it is really owned by the referencer.
Parameters
Object referencing this subobject
InstancedSubObject the sub object to override all its properties
References Object.
OverrideObject()
void FOverridableManager::OverrideObject (TNotNull< UObject * > Object)
Override the entire object properties and all its instanced subobjects.
Parameters
Object to override all it properties
References Object.
OverrideProperty() [1/2]
void FOverridableManager::OverrideProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain) inline
Override a specific property of an object (Helper methods to call Pre/PostOverride) Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyEvent information about the type of change including any container item index
PropertyChain leading to the property that is about to be overridden
Definition at line 245 of file OverridableManager.h.
References Object, and OverrideProperty().
OverrideProperty() [2/2]
void FOverridableManager::OverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath)
Override a specific property of an object (Helper methods to call Pre/PostOverride) Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyPath leading to the property that is about to be overridden
References Object.
Referenced by OverrideProperty().
PostOverrideProperty() [1/2]
void FOverridableManager::PostOverrideProperty (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain) inline
To be called after the property was overridden of the specified object Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyEvent information about the type of change including any container item index
PropertyChain leading to the property that was overridden
Definition at line 277 of file OverridableManager.h.
References FPropertyChangedEvent::ChangeType, Object, and PostOverrideProperty().
PostOverrideProperty() [2/2]
void FOverridableManager::PostOverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath, const EPropertyChangeType::Type ChangeType)
To be called after the property of the specified object was overridden Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyPath leading to the property that was overridden
ChangeType of the current operation
References Object.
Referenced by PostOverrideProperty().
PreOverrideProperty() [1/2]
void FOverridableManager::PreOverrideProperty (TNotNull< UObject * > Object, const FEditPropertyChain & PropertyChain) inline
To be called prior to override a property of the specified object Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyChain leading to the property about to be overridden
Definition at line 266 of file OverridableManager.h.
References Object, and PreOverrideProperty().
PreOverrideProperty() [2/2]
void FOverridableManager::PreOverrideProperty (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath)
To be called prior to override a property of the specified object Note: Supports object that does not have overridable serialization enabled.
Parameters
Object owning the property
PropertyPath leading to the property about to be overridden
References Object.
Referenced by PreOverrideProperty().
PropagateClearOverridesToInstancedSubObjects()
void FOverridableManager::PropagateClearOverridesToInstancedSubObjects (TNotNull< UObject * > Object)
Propagate the clear overrides to all instanced suboject of the specified object.
Parameters
Object
References Object.
PropagateOverrideToInstancedSubObjects()
void FOverridableManager::PropagateOverrideToInstancedSubObjects (TNotNull< UObject * > Object)
Propagate override to all instanced sub object of the specified object.
Parameters
Object to propagate from
References Object.
RestoreOverrideOperation()
FOverriddenPropertySet * FOverridableManager::RestoreOverrideOperation (TNotNull< UObject * > Object, EOverriddenPropertyOperation Operation, const bool bNeedsSubobjectTemplateInstantiation)
Restore the override operation from a saved state on this object, and it will enable it if it wasn't already enabled.
Note
: It will not restore a Modified state has this will be done automatically when sub properties overrides are restored
Parameters
Object to set the override operation on
Operation the override operation to set on the object
bNeedsSubobjectTemplateInstantiation set to true if it will need a sub object template instantiation during postload, false will not do it.
Returns
the overridden properties of the object
References FOverriddenPropertySet, and Object.
RestoreOverrideState()
void FOverridableManager::RestoreOverrideState (TNotNull< const UObject * > OldObject, TNotNull< UObject * > NewObject)
Restore some of the overridden state that is not necessarily restored by the CPFUO (ex: bWasAdded come from the owner of the object and reinstantiating the object does not preserve it)
Parameters
OldObject to old object to restore from the overridden state
NewObject the new object to restore to the overridden state
References NewObject().
SerializeOverriddenProperties()
void FOverridableManager::SerializeOverriddenProperties (TNotNull< UObject * > Object, FStructuredArchive::FRecord ObjectRecord)
Serializes the overridden properties of the specified object into the record.
Parameters
Object to serialize the overridden property
ObjectRecord the record to use for serialization
References Object.
TryGet()
FOverridableManager * FOverridableManager::TryGet () inline static
Returns
the instance managing the overridability if available
Note
it is not available only during initialization time
Definition at line 71 of file OverridableManager.h.
References FOverridableManager(), and OverridableManager.
Field Documentation
FOverriddenPropertySet
friend FOverridableManager::FOverriddenPropertySet protected
Definition at line 320 of file OverridableManager.h.
Referenced by GetOverriddenPropertiesInternal(), GetOverriddenPropertiesInternal(), and RestoreOverrideOperation().
NeedsSubobjectTemplateInstantiation
FUObjectAnnotationSparseBool FOverridableManager::NeedsSubobjectTemplateInstantiation protected
Definition at line 317 of file OverridableManager.h.
OverridableManager
FOverridableManager* FOverridableManager::OverridableManager static protected
Definition at line 310 of file OverridableManager.h.
Referenced by Get(), and TryGet().
The documentation for this class was generated from the following file:
OverridableManager.h