Unreal Engine 5.6 C++ API: TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > > Struct Template Reference
TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > > Struct Template Reference
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>, FSparseItemInfo, false>
typedef TSharedPtr< T, ESPMode::ThreadSafe > NullableType
using SetKeyFuncs = DefaultKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>>
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< TSharedRef< T, ESPMode::ThreadSafe > > &, TSet< TSharedRef< T, ESPMode::ThreadSafe > > &, TMap< const U *, TSharedRef< T, ESPMode::ThreadSafe > > &)
static FString DebugDump (TSharedRef< T, ESPMode::ThreadSafe > InPtr)
static bool IsPtrValid (const TSharedPtr< T, ESPMode::ThreadSafe > &InPtr)
static TSharedPtr< T, ESPMode::ThreadSafe > MakeNullPtr ()
static TSharedRef< T, ESPMode::ThreadSafe > NullableItemTypeConvertToItemType (const TSharedPtr< T, ESPMode::ThreadSafe > &InPtr)
static void ResetPtr (TSharedPtr< T, ESPMode::ThreadSafe > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >
Definition at line 267 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>, TSharedRef<ITableRow>, false>
Definition at line 272 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>, FSparseItemInfo, false>
Definition at line 273 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TSharedPtr<T, ESPMode::ThreadSafe> TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::NullableType
Definition at line 270 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::SetKeyFuncs = DefaultKeyFuncs<TSharedRef<T, ESPMode::ThreadSafe>>
Definition at line 274 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::AddReferencedObjects (FReferenceCollector & , TArray< TSharedRef< T, ESPMode::ThreadSafe > > & , TSet< TSharedRef< T, ESPMode::ThreadSafe > > & , TMap< const U *, TSharedRef< T, ESPMode::ThreadSafe > > &) inline static
Definition at line 277 of file TableViewTypeTraits.h.
DebugDump()
template<typename T> FString TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::DebugDump (TSharedRef< T, ESPMode::ThreadSafe > InPtr) inline static
Definition at line 304 of file TableViewTypeTraits.h.
References TSharedRef< ObjectType, InMode >::Get(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::IsPtrValid (const TSharedPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 284 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::IsValid().
MakeNullPtr()
template<typename T> TSharedPtr< T, ESPMode::ThreadSafe > TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::MakeNullPtr () inline static
Definition at line 294 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TSharedRef< T, ESPMode::ThreadSafe > TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::NullableItemTypeConvertToItemType (const TSharedPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 299 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::ToSharedRef().
ResetPtr()
template<typename T> void TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::ResetPtr (TSharedPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 289 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::Reset().
The documentation for this struct was generated from the following file:
TableViewTypeTraits.h