Unreal Engine 5.6 C++ API: ANavLinkProxy Class Reference
ANavLinkProxy Class Reference
#include "NavLinkProxy.h"
Public Member Functions
virtual AIMODULE_API void BeginDestroy () override
virtual AIMODULE_API FBox GetComponentsBoundingBox (bool bNonColliding=false, bool bIncludeFromChildActors=false) const override
virtual AIMODULE_API FBox GetNavigationBounds () const override
Get bounds for navigation octree.
virtual AIMODULE_API void GetNavigationData (FNavigationRelevantData &Data) const override
virtual AIMODULE_API bool GetNavigationLinksArray (TArray< FNavigationLink > &OutLink, TArray< FNavigationSegmentLink > &OutSegments) const override
virtual AIMODULE_API bool GetNavigationLinksClasses (TArray< TSubclassOf< UNavLinkDefinition > > &OutClasses) const override
UNavLinkCustomComponent * GetSmartLinkComp () const
Returns SmartLinkComp subobject.
virtual AIMODULE_API bool IsNavigationRelevant () const override
Are modifiers active?
virtual AIMODULE_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual AIMODULE_API void PostEditImport () override
virtual AIMODULE_API void PostEditUndo () override
virtual AIMODULE_API void PostInitProperties () override
virtual AIMODULE_API void PostLoad () override
virtual AIMODULE_API void PostRegisterAllComponents () override
UFUNCTION () AIMODULE_API bool HasMovingAgents() const
check if any agent is moving through smart link right now
UFUNCTION () AIMODULE_API bool IsSmartLinkEnabled() const
check if smart link is enabled
UFUNCTION () AIMODULE_API void ReceiveSmartLinkReached(AActor *Agent
called when agent reaches smart link during path following, use ResumePathFollowing() to give control back
UFUNCTION () AIMODULE_API void ResumePathFollowing(AActor *Agent)
resume normal path following
UFUNCTION () AIMODULE_API void SetSmartLinkEnabled(bool bEnabled)
change state of smart link
UFUNCTION ()) AIMODULE_API void CopyEndPointsFromSimpleLinkToSmartLink()
Copies navlink end points from the first entry in PointLinks array.
UPROPERTY () bool bSmartLinkIsRelevant
Smart link: toggle relevancy.
Data Fields
const FVector & Destination
Protected Member Functions
AIMODULE_API void NotifySmartLinkReached (UNavLinkCustomComponent *LinkComp, UObject *PathingAgent, const FVector &DestPoint)
AIMODULE_API void OnNavAreaRegistered (const UWorld &World, const UClass *NavAreaClass)
AIMODULE_API void OnNavAreaUnregistered (const UWorld &World, const UClass *NavAreaClass)
UPROPERTY () FSmartLinkReachedSignature OnSmartLinkReached
Protected Attributes
FDelegateHandle OnNavAreaRegisteredDelegateHandle
FDelegateHandle OnNavAreaUnregisteredDelegateHandle
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TArray< FNavigationLink > PointLinks
Navigation links (point to point) added to navigation data.
UPROPERTY () TArray< FNavigationSegmentLink > SegmentLinks
Navigation links (segment to segment) added to navigation data.
UPROPERTY () TObjectPtr< UNavLinkCustomComponent > SmartLinkComp
Smart link: can affect path following.
Detailed Description
Definition at line 34 of file NavLinkProxy.h.
Member Function Documentation
BeginDestroy()
virtual AIMODULE_API void ANavLinkProxy::BeginDestroy () override virtual
GENERATED_UCLASS_BODY()
ANavLinkProxy::GENERATED_UCLASS_BODY () private
Navigation links (point to point) added to navigation data.
References Category, and UPROPERTY().
GetComponentsBoundingBox()
virtual AIMODULE_API FBox ANavLinkProxy::GetComponentsBoundingBox (bool bNonColliding = false, bool bIncludeFromChildActors = false) const override virtual
GetNavigationBounds()
virtual AIMODULE_API FBox ANavLinkProxy::GetNavigationBounds () const override virtual
Get bounds for navigation octree.
Reimplemented from INavRelevantInterface.
GetNavigationData()
virtual AIMODULE_API void ANavLinkProxy::GetNavigationData (FNavigationRelevantData & Data) const override virtual
GetNavigationLinksArray()
virtual AIMODULE_API bool ANavLinkProxy::GetNavigationLinksArray (TArray< FNavigationLink > & OutLink, TArray< FNavigationSegmentLink > & OutSegments) const override virtual
GetNavigationLinksClasses()
virtual AIMODULE_API bool ANavLinkProxy::GetNavigationLinksClasses (TArray< TSubclassOf< UNavLinkDefinition > > & OutClasses) const override virtual
GetSmartLinkComp()
UNavLinkCustomComponent * ANavLinkProxy::GetSmartLinkComp () const inline
Returns SmartLinkComp subobject.
Definition at line 143 of file NavLinkProxy.h.
IsNavigationRelevant()
virtual AIMODULE_API bool ANavLinkProxy::IsNavigationRelevant () const override virtual
Are modifiers active?
Reimplemented from INavRelevantInterface.
NotifySmartLinkReached()
AIMODULE_API void ANavLinkProxy::NotifySmartLinkReached (UNavLinkCustomComponent * LinkComp, UObject * PathingAgent, const FVector & DestPoint) protected
References FVector.
OnNavAreaRegistered()
AIMODULE_API void ANavLinkProxy::OnNavAreaRegistered (const UWorld & World, const UClass * NavAreaClass) protected
OnNavAreaUnregistered()
AIMODULE_API void ANavLinkProxy::OnNavAreaUnregistered (const UWorld & World, const UClass * NavAreaClass) protected
PostEditChangeProperty()
virtual AIMODULE_API void ANavLinkProxy::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostEditImport()
virtual AIMODULE_API void ANavLinkProxy::PostEditImport () override virtual
PostEditUndo()
virtual AIMODULE_API void ANavLinkProxy::PostEditUndo () override virtual
PostInitProperties()
virtual AIMODULE_API void ANavLinkProxy::PostInitProperties () override virtual
PostLoad()
virtual AIMODULE_API void ANavLinkProxy::PostLoad () override virtual
PostRegisterAllComponents()
virtual AIMODULE_API void ANavLinkProxy::PostRegisterAllComponents () override virtual
UFUNCTION() [1/6]
ANavLinkProxy::UFUNCTION () const
check if any agent is moving through smart link right now
References Category, and UFUNCTION().
UFUNCTION() [2/6]
ANavLinkProxy::UFUNCTION () const
check if smart link is enabled
References Category, and UFUNCTION().
UFUNCTION() [3/6]
ANavLinkProxy::UFUNCTION ()
called when agent reaches smart link during path following, use ResumePathFollowing() to give control back
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/6]
ANavLinkProxy::UFUNCTION ()
resume normal path following
References Category, and UFUNCTION().
UFUNCTION() [5/6]
ANavLinkProxy::UFUNCTION ()
change state of smart link
References Category, and UFUNCTION().
UFUNCTION() [6/6]
ANavLinkProxy::UFUNCTION ()
Copies navlink end points from the first entry in PointLinks array.
This function is a helper function making up for smart links not drawing the FVector widgets in the editor.
References Category, and meta.
UPROPERTY() [1/4]
ANavLinkProxy::UPROPERTY ()
Smart link: toggle relevancy.
References Category, and UPROPERTY().
UPROPERTY() [2/4]
ANavLinkProxy::UPROPERTY () protected
UPROPERTY() [3/4]
ANavLinkProxy::UPROPERTY () private
Navigation links (segment to segment) added to navigation data.
Todo
hidden from use until we fix segment links. Not really working now
References UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/4]
ANavLinkProxy::UPROPERTY () private
Smart link: can affect path following.
References Category, and UPROPERTY().
Field Documentation
Destination
const FVector& ANavLinkProxy::Destination
Definition at line 103 of file NavLinkProxy.h.
OnNavAreaRegisteredDelegateHandle
FDelegateHandle ANavLinkProxy::OnNavAreaRegisteredDelegateHandle protected
Definition at line 153 of file NavLinkProxy.h.
OnNavAreaUnregisteredDelegateHandle
FDelegateHandle ANavLinkProxy::OnNavAreaUnregisteredDelegateHandle protected
Definition at line 154 of file NavLinkProxy.h.
The documentation for this class was generated from the following file:
NavLinkProxy.h