Unreal Engine 5.6 C++ API: RefCounting.h File Reference
RefCounting.h File Reference
#include "CoreTypes.h"
#include "AutoRTFM.h"
#include "HAL/PlatformAtomics.h"
#include "HAL/PreprocessorHelpers.h"
#include "HAL/ThreadSafeCounter.h"
#include "Misc/AssertionMacros.h"
#include "Misc/Build.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryLayout.h"
#include "Templates/Requires.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include <atomic>
#include <type_traits>
Data Structures
class FRefCountBase
Base class implementing thread-safe reference counting.
class FRefCountedObject
The base class of reference counted objects.
struct FReturnedRefCountValue
Simple wrapper class which holds a refcount; emits a deprecation warning when accessed.
class FThreadSafeRefCountedObject
Like FRefCountedObject, but the reference count is thread-safe.
class IRefCountedObject
A virtual interface for ref counted objects to implement.
class TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >
Not-thread-safe specialization.
class TRefCountingMixin< T, ERefCountingMode::ThreadSafe >
Thread-safe specialization.
class TRefCountPtr< ReferencedType >
A smart pointer to an object which implements AddRef/Release.
class UE::Private::TTransactionalAtomicRefCount< AtomicType >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Private
The global memory allocator.
Enumerations
enum class ERefCountingMode : uint8 { NotThreadSafe = 0 , ThreadSafe = 1 }
ERefCountingMode is used select between either 'fast' or 'thread safe' ref-counting types.
Functions
ALIAS_TEMPLATE_TYPE_LAYOUT (template< typename T >, TRefCountPtr< T >, void *)
void UE::Private::CheckRefCountIsNonZero ()
template<typename ReferencedType>
FORCEINLINE uint32 GetTypeHash (const TRefCountPtr< ReferencedType > &InPtr)
template<typename T, typename... TArgs UE_REQUIRES>
FORCEINLINE TRefCountPtr< T > MakeRefCount (TArgs &&... Args)
template<typename ReferencedType>
FArchive & operator<< (FArchive &Ar, TRefCountPtr< ReferencedType > &Ptr)
template<typename ReferencedType>
FORCEINLINE bool operator== (ReferencedType *A, const TRefCountPtr< ReferencedType > &B)
Enumeration Type Documentation
ERefCountingMode
enum class ERefCountingMode : uint8 strong
ERefCountingMode is used select between either 'fast' or 'thread safe' ref-counting types.
This is only used at compile time to select between template specializations.
Enumerator
NotThreadSafe
Forced to be not thread-safe.
ThreadSafe
Thread-safe: never spin locks, but slower.
Definition at line 323 of file RefCounting.h.
Function Documentation
ALIAS_TEMPLATE_TYPE_LAYOUT()
ALIAS_TEMPLATE_TYPE_LAYOUT (template< typename T > , TRefCountPtr< T > , void *)
GetTypeHash()
template<typename ReferencedType> FORCEINLINE uint32 GetTypeHash (const TRefCountPtr< ReferencedType > & InPtr)
Definition at line 661 of file RefCounting.h.
References FORCEINLINE, TRefCountPtr< ReferencedType >::GetReference(), and GetTypeHash().
Referenced by GetTypeHash().
MakeRefCount()
template<typename T, typename... TArgs UE_REQUIRES> FORCEINLINE TRefCountPtr< T > MakeRefCount (TArgs &&... Args) nodiscard
Definition at line 679 of file RefCounting.h.
References FORCEINLINE, Forward(), and NewObject().
Referenced by UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::FEpicRtcFrameDependencyStructure(), UE::PixelStreaming2::FEpicRtcGenericFrameInfo::FEpicRtcGenericFrameInfo(), and MakeTextDisplayString().
operator<<()
template<typename ReferencedType> FArchive & operator<< (FArchive & Ar, TRefCountPtr< ReferencedType > & Ptr)
Definition at line 668 of file RefCounting.h.
References Ar, and TRefCountPtr< ReferencedType >::Serialize().
operator==()
template<typename ReferencedType> FORCEINLINE bool operator== (ReferencedType * A, const TRefCountPtr< ReferencedType > & B)
Definition at line 654 of file RefCounting.h.
References A, B, and FORCEINLINE.