Unreal Engine 5.6 C++ API: Verse::FNativeConverter Struct Reference
Verse::FNativeConverter Struct Reference
#include "VVMNativeConverter.h"
Static Public Member Functions
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< bool > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< double > &OutNative)
template<class EnumType>
static TEnableIf< TIsEnumClass< EnumType >::Value, FOpResult >::Type FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< EnumType > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< EVerseTrue > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< FNativeString > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< FVerseValue > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< int64 > &OutNative)
template<class NativeType UE_REQUIRES>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< NativeType > &OutNative)
template<class StructType>
static TEnableIf< TIsNativeStruct< StructType >::Value, FOpResult >::Type FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< StructType > &OutNative)
template<class ElementType>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TArray< ElementType > > &OutNative)
template<class InterfaceProxyType>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TInterfaceInstance< InterfaceProxyType > > &OutNative)
template<class KeyType, class ValueType>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TMap< KeyType, ValueType > > &OutNative)
template<typename... ElementTypes>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNativeTuple< ElementTypes... > > &OutNative)
template<typename... ElementTypes, size_t... Indices>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNativeTuple< ElementTypes... > > &OutNative, std::index_sequence< Indices... >)
template<class ObjectType>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNonNullPtr< ObjectType > > &OutNative)
template<typename ValueType>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TOptional< ValueType > > &OutNative)
template<typename ReturnType, typename... ParamTypes>
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TVerseFunction< ReturnType(ParamTypes...)> > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< UTF32CHAR > &OutNative)
static FOpResult FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< UTF8CHAR > &OutNative)
template<class ObjectType>
static VValue ToVValue (FAllocationContext Context, ::TObjectPtr< ObjectType > Object)
static VValue ToVValue (FAllocationContext Context, bool Logic)
static VValue ToVValue (FAllocationContext Context, const ::FNullOpt &Optional)
template<typename ValueType>
static VValue ToVValue (FAllocationContext Context, const ::TOptional< ValueType > &Optional)
static VValue ToVValue (FAllocationContext Context, const FNativeString &String)
static VValue ToVValue (FAllocationContext Context, const FVerseFunction &Function)
static VValue ToVValue (FAllocationContext Context, const FVerseValue &Value)
template<class NativeType UE_REQUIRES>
static VValue ToVValue (FAllocationContext Context, const NativeType &Type)
template<class ElementType>
static VValue ToVValue (FAllocationContext Context, const TArray< ElementType > &Array)
template<class KeyType, class ValueType>
static VValue ToVValue (FAllocationContext Context, const TMap< KeyType, ValueType > &Map)
template<typename... ElementTypes>
static VValue ToVValue (FAllocationContext Context, const TNativeTuple< ElementTypes... > &Tuple)
template<typename... ElementTypes, size_t... Indices>
static VValue ToVValue (FAllocationContext Context, const TNativeTuple< ElementTypes... > &Tuple, std::index_sequence< Indices... >)
static VValue ToVValue (FAllocationContext Context, double Number)
template<typename EnumType, typename = typename TEnableIf<TIsEnumClass<EnumType>::Value>::Type>
static VValue ToVValue (FAllocationContext Context, EnumType Enumerator)
static VValue ToVValue (FAllocationContext Context, EVerseFalse)
static VValue ToVValue (FAllocationContext Context, EVerseTrue)
static VValue ToVValue (FAllocationContext Context, int64 Number)
template<class ObjectType>
static VValue ToVValue (FAllocationContext Context, ObjectType *Object)
template<class StructType, typename = typename TEnableIf<TIsNativeStruct<typename TDecay<StructType>::Type>::Value>::Type>
static VValue ToVValue (FAllocationContext Context, StructType &&Struct)
template<class InterfaceProxyType>
static VValue ToVValue (FAllocationContext Context, TInterfaceInstance< InterfaceProxyType > Object)
template<class ObjectType>
static VValue ToVValue (FAllocationContext Context, TNonNullPtr< ObjectType > Object)
static VValue ToVValue (FAllocationContext Context, TSubclassOf< UObject > Class)
static VValue ToVValue (FAllocationContext Context, UTF32CHAR Char32)
static VValue ToVValue (FAllocationContext Context, UTF8CHAR Char)
Detailed Description
Definition at line 178 of file VVMNativeConverter.h.
Member Function Documentation
FromVValue() [1/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< bool > & OutNative) inline static
Definition at line 346 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [2/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< double > & OutNative) inline static
Definition at line 368 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [3/19]
template<class EnumType> TEnableIf< TIsEnumClass< EnumType >::Value, FOpResult >::Type Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< EnumType > & OutNative) inline static
Definition at line 403 of file VVMNativeConverter.h.
References Verse::ErrRuntime_GeneratedNativeInternal, FText::FromString(), Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [4/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< EVerseTrue > & OutNative) inline static
Definition at line 340 of file VVMNativeConverter.h.
References Value.
Referenced by FromVValue(), FromVValue(), FromVValue(), FromVValue(), and FromVValue().
FromVValue() [5/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< FNativeString > & OutNative) inline static
Definition at line 376 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [6/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< FVerseValue > & OutNative) static
References Value.
FromVValue() [7/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< int64 > & OutNative) inline static
Definition at line 354 of file VVMNativeConverter.h.
References Verse::ErrRuntime_GeneratedNativeInternal, FText::FromString(), Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [8/19]
template<class NativeType UE_REQUIRES> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< NativeType > & OutNative) inline static
Definition at line 468 of file VVMNativeConverter.h.
References Verse::Class, Verse::ErrRuntime_GeneratedNativeInternal, FText::FromString(), Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [9/19]
template<class StructType> TEnableIf< TIsNativeStruct< StructType >::Value, FOpResult >::Type Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< StructType > & OutNative) inline static
Definition at line 432 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [10/19]
template<class ElementType> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TArray< ElementType > > & OutNative) inline static
Definition at line 482 of file VVMNativeConverter.h.
References Verse::Array, ensure, FromVValue(), Verse::TFromVValue< NativeType, typename >::GetValue(), and Value.
FromVValue() [11/19]
template<class InterfaceProxyType> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TInterfaceInstance< InterfaceProxyType > > & OutNative) static
References Verse::Type, and Value.
FromVValue() [12/19]
template<class KeyType, class ValueType> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TMap< KeyType, ValueType > > & OutNative) inline static
Definition at line 503 of file VVMNativeConverter.h.
References ensure, FromVValue(), Verse::TFromVValue< NativeType, typename >::GetValue(), Map, and Value.
FromVValue() [13/19]
template<typename... ElementTypes> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNativeTuple< ElementTypes... > > & OutNative) inline static
Definition at line 440 of file VVMNativeConverter.h.
References FromVValue(), and Value.
FromVValue() [14/19]
template<typename... ElementTypes, size_t... Indices> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNativeTuple< ElementTypes... > > & OutNative, std::index_sequence< Indices... >) inline static
Definition at line 446 of file VVMNativeConverter.h.
References Verse::Array, FromVValue(), Verse::Type, and Value.
FromVValue() [15/19]
template<class ObjectType> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TNonNullPtr< ObjectType > > & OutNative) inline static
Definition at line 418 of file VVMNativeConverter.h.
References Value.
FromVValue() [16/19]
template<typename ValueType> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TOptional< ValueType > > & OutNative) inline static
Definition at line 530 of file VVMNativeConverter.h.
References ensure, FromVValue(), Verse::TFromVValue< NativeType, typename >::GetValue(), and Value.
FromVValue() [17/19]
template<typename ReturnType, typename... ParamTypes> FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< TVerseFunction< ReturnType(ParamTypes...)> > & OutNative) static
References Value.
FromVValue() [18/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< UTF32CHAR > & OutNative) inline static
Definition at line 393 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
FromVValue() [19/19]
FOpResult Verse::FNativeConverter::FromVValue (FAllocationContext Context, const VValue Value, TFromVValue< UTF8CHAR > & OutNative) inline static
Definition at line 385 of file VVMNativeConverter.h.
References Value, and Verse::TFromVValue< NativeType, typename >::Value.
ToVValue() [1/24]
template<class ObjectType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, ::TObjectPtr< ObjectType > Object) inline static
Definition at line 245 of file VVMNativeConverter.h.
References Object, and ToVValue().
ToVValue() [2/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, bool Logic) inline static
Definition at line 193 of file VVMNativeConverter.h.
References Verse::Logic.
ToVValue() [3/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const ::FNullOpt & Optional) inline static
Definition at line 330 of file VVMNativeConverter.h.
References Optional.
ToVValue() [4/24]
template<typename ValueType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const ::TOptional< ValueType > & Optional) inline static
Definition at line 318 of file VVMNativeConverter.h.
References Optional, and ToVValue().
ToVValue() [5/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const FNativeString & String) inline static
Definition at line 208 of file VVMNativeConverter.h.
References Verse::String.
ToVValue() [6/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const FVerseFunction & Function) static
References Function.
ToVValue() [7/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const FVerseValue & Value) static
References Value.
ToVValue() [8/24]
template<class NativeType UE_REQUIRES> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const NativeType & Type) inline static
Definition at line 290 of file VVMNativeConverter.h.
References ToVValue(), and Verse::Type.
ToVValue() [9/24]
template<class ElementType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const TArray< ElementType > & Array) inline static
Definition at line 296 of file VVMNativeConverter.h.
References Verse::Array.
ToVValue() [10/24]
template<class KeyType, class ValueType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const TMap< KeyType, ValueType > & Map) inline static
Definition at line 305 of file VVMNativeConverter.h.
References Map, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Push(), TArray< InElementType, InAllocatorType >::Reserve(), and ToVValue().
ToVValue() [11/24]
template<typename... ElementTypes> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const TNativeTuple< ElementTypes... > & Tuple) inline static
Definition at line 260 of file VVMNativeConverter.h.
References ToVValue().
ToVValue() [12/24]
template<typename... ElementTypes, size_t... Indices> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, const TNativeTuple< ElementTypes... > & Tuple, std::index_sequence< Indices... >) inline static
Definition at line 266 of file VVMNativeConverter.h.
References ToVValue().
ToVValue() [13/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, double Number) inline static
Definition at line 203 of file VVMNativeConverter.h.
ToVValue() [14/24]
template<typename EnumType, typename = typename TEnableIf<TIsEnumClass<EnumType>::Value>::Type> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, EnumType Enumerator) inline static
Definition at line 224 of file VVMNativeConverter.h.
ToVValue() [15/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, EVerseFalse) inline static
Definition at line 182 of file VVMNativeConverter.h.
References VERSE_UNREACHABLE.
Referenced by ToVValue(), ToVValue(), ToVValue(), ToVValue(), ToVValue(), ToVValue(), and ToVValue().
ToVValue() [16/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, EVerseTrue) inline static
Definition at line 188 of file VVMNativeConverter.h.
ToVValue() [17/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, int64 Number) inline static
Definition at line 198 of file VVMNativeConverter.h.
ToVValue() [18/24]
template<class ObjectType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, ObjectType * Object) inline static
Definition at line 232 of file VVMNativeConverter.h.
References check, UObjectBase::IsValidLowLevel(), and Object.
ToVValue() [19/24]
template<class StructType, typename = typename TEnableIf<TIsNativeStruct<typename TDecay<StructType>::Type>::Value>::Type> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, StructType && Struct) inline static
Definition at line 254 of file VVMNativeConverter.h.
References Forward(), and Struct.
ToVValue() [20/24]
template<class InterfaceProxyType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, TInterfaceInstance< InterfaceProxyType > Object) static
References Object, Verse::Type, and Value.
ToVValue() [21/24]
template<class ObjectType> VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, TNonNullPtr< ObjectType > Object) inline static
Definition at line 240 of file VVMNativeConverter.h.
References Object, and ToVValue().
ToVValue() [22/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, TSubclassOf< UObject > Class) inline static
Definition at line 271 of file VVMNativeConverter.h.
References Cast(), Verse::Class, and VerseClass.
ToVValue() [23/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, UTF32CHAR Char32) inline static
Definition at line 218 of file VVMNativeConverter.h.
ToVValue() [24/24]
VValue Verse::FNativeConverter::ToVValue (FAllocationContext Context, UTF8CHAR Char) inline static
Definition at line 213 of file VVMNativeConverter.h.
The documentation for this struct was generated from the following file:
VVMNativeConverter.h