Unreal Engine 5.6 C++ API: Metasound::TEnum< EnumType, DefaultValue > Class Template Reference
Metasound::TEnum< EnumType, DefaultValue > Class Template Reference final
Metasound Enum Wrapper.
#include "MetasoundEnum.h"
Public Types
using InnerType = EnumType
using SerializedType = int32
using UnderlyingType = std::underlying_type_t<EnumType>
Public Member Functions
TEnum (const FString &InString)
TEnum (EnumType InValue=DefaultValue)
TEnum (FName InValueName)
TEnum (int32 InIntValue)
EnumType Get () const
operator EnumType () const
int32 ToInt () const
TOptional< FName > ToName () const
Static Public Member Functions
static constexpr bool EnumTypeIsSupported ()
static TArray< FName > GetAllNames ()
static TOptional< EnumType > NameToEnum (FName InValue)
static TOptional< FName > ToName (EnumType InValue)
Private Attributes
EnumType EnumValue = DefaultValue
Static Private Attributes
static bool bHasWarnedNameToEnumConversionFailure
Detailed Description
template<typename EnumType, EnumType DefaultValue>
class Metasound::TEnum< EnumType, DefaultValue >
Metasound Enum Wrapper.
Definition at line 108 of file MetasoundEnum.h.
Member Typedef Documentation
InnerType
template<typename EnumType, EnumType DefaultValue> using Metasound::TEnum< EnumType, DefaultValue >::InnerType = EnumType
Definition at line 111 of file MetasoundEnum.h.
SerializedType
template<typename EnumType, EnumType DefaultValue> using Metasound::TEnum< EnumType, DefaultValue >::SerializedType = int32
Definition at line 112 of file MetasoundEnum.h.
UnderlyingType
template<typename EnumType, EnumType DefaultValue> using Metasound::TEnum< EnumType, DefaultValue >::UnderlyingType = std::underlying_type_t<EnumType>
Definition at line 113 of file MetasoundEnum.h.
Constructor & Destructor Documentation
TEnum() [1/4]
template<typename EnumType, EnumType DefaultValue> Metasound::TEnum< EnumType, DefaultValue >::TEnum (EnumType InValue = DefaultValue) inline explicit
Definition at line 157 of file MetasoundEnum.h.
TEnum() [2/4]
template<typename EnumType, EnumType DefaultValue> Metasound::TEnum< EnumType, DefaultValue >::TEnum (int32 InIntValue) inline explicit
Definition at line 181 of file MetasoundEnum.h.
TEnum() [3/4]
template<typename EnumType, EnumType DefaultValue> Metasound::TEnum< EnumType, DefaultValue >::TEnum (FName InValueName) inline explicit
Definition at line 187 of file MetasoundEnum.h.
TEnum() [4/4]
template<typename EnumType, EnumType DefaultValue> Metasound::TEnum< EnumType, DefaultValue >::TEnum (const FString & InString) inline explicit
Definition at line 212 of file MetasoundEnum.h.
Member Function Documentation
EnumTypeIsSupported()
template<typename EnumType, EnumType DefaultValue> constexpr bool Metasound::TEnum< EnumType, DefaultValue >::EnumTypeIsSupported () inline static constexpr
Definition at line 115 of file MetasoundEnum.h.
Get()
template<typename EnumType, EnumType DefaultValue> EnumType Metasound::TEnum< EnumType, DefaultValue >::Get () const inline
Definition at line 217 of file MetasoundEnum.h.
GetAllNames()
template<typename EnumType, EnumType DefaultValue> TArray< FName > Metasound::TEnum< EnumType, DefaultValue >::GetAllNames () inline static
Definition at line 252 of file MetasoundEnum.h.
Referenced by Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum(), and Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum().
NameToEnum()
template<typename EnumType, EnumType DefaultValue> TOptional< EnumType > Metasound::TEnum< EnumType, DefaultValue >::NameToEnum (FName InValue) inline static
Definition at line 246 of file MetasoundEnum.h.
Referenced by Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum().
operator EnumType()
template<typename EnumType, EnumType DefaultValue> Metasound::TEnum< EnumType, DefaultValue >::operator EnumType () const inline
Definition at line 234 of file MetasoundEnum.h.
ToInt()
template<typename EnumType, EnumType DefaultValue> int32 Metasound::TEnum< EnumType, DefaultValue >::ToInt () const inline
Definition at line 222 of file MetasoundEnum.h.
ToName() [1/2]
template<typename EnumType, EnumType DefaultValue> TOptional< FName > Metasound::TEnum< EnumType, DefaultValue >::ToName () const inline
Definition at line 228 of file MetasoundEnum.h.
Referenced by Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum(), and Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::ToName().
ToName() [2/2]
template<typename EnumType, EnumType DefaultValue> TOptional< FName > Metasound::TEnum< EnumType, DefaultValue >::ToName (EnumType InValue) inline static
Definition at line 240 of file MetasoundEnum.h.
Field Documentation
bHasWarnedNameToEnumConversionFailure
template<typename EnumType, EnumType DefaultValue> bool Metasound::TEnum< EnumType, DefaultValue >::bHasWarnedNameToEnumConversionFailure static private
Definition at line 261 of file MetasoundEnum.h.
EnumValue
template<typename EnumType, EnumType DefaultValue> EnumType Metasound::TEnum< EnumType, DefaultValue >::EnumValue = DefaultValue private
Definition at line 259 of file MetasoundEnum.h.
The documentation for this class was generated from the following file:
MetasoundEnum.h