Unreal Engine 5.6 C++ API: UBTDecorator_Cooldown Class Reference
UBTDecorator_Cooldown Class Reference
#include "BTDecorator_Cooldown.h"
Protected Member Functions
virtual AIMODULE_API void OnNodeDeactivation (FBehaviorTreeSearchData &SearchData, EBTNodeResult::Type NodeResult) override
virtual AIMODULE_API void TickNode (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, float DeltaSeconds) override
Private Member Functions
virtual AIMODULE_API bool CalculateRawConditionValue (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) const override
virtual AIMODULE_API void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () UPROPERTY() FValueOrBBKey_Float CoolDownTime
max allowed time for execution of underlying node
virtual AIMODULE_API uint16 GetInstanceMemorySize () const override
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
virtual AIMODULE_API void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
virtual AIMODULE_API void PostLoad () override
Detailed Description
Definition at line 22 of file BTDecorator_Cooldown.h.
Member Function Documentation
CalculateRawConditionValue()
virtual AIMODULE_API bool UBTDecorator_Cooldown::CalculateRawConditionValue (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) const override private virtual
References CalculateRawConditionValue().
Referenced by CalculateRawConditionValue().
CleanupMemory()
virtual AIMODULE_API void UBTDecorator_Cooldown::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override private virtual
References CleanupMemory().
Referenced by CleanupMemory().
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_Cooldown::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues().
Referenced by DescribeRuntimeValues().
GENERATED_UCLASS_BODY()
UBTDecorator_Cooldown::GENERATED_UCLASS_BODY () private
max allowed time for execution of underlying node
References Category, and UPROPERTY.
GetInstanceMemorySize()
virtual AIMODULE_API uint16 UBTDecorator_Cooldown::GetInstanceMemorySize () const override private virtual
References GetInstanceMemorySize().
Referenced by GetInstanceMemorySize().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_Cooldown::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_Cooldown::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
InitializeMemory()
virtual AIMODULE_API void UBTDecorator_Cooldown::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override private virtual
References InitializeMemory().
Referenced by InitializeMemory().
OnNodeDeactivation()
virtual AIMODULE_API void UBTDecorator_Cooldown::OnNodeDeactivation (FBehaviorTreeSearchData & SearchData, EBTNodeResult::Type NodeResult) override protected virtual
PostLoad()
virtual AIMODULE_API void UBTDecorator_Cooldown::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
TickNode()
virtual AIMODULE_API void UBTDecorator_Cooldown::TickNode (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, float DeltaSeconds) override protected virtual
The documentation for this class was generated from the following file:
BTDecorator_Cooldown.h