Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... > Struct Template Reference
UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
template<int Index>
FORCEINLINE auto GetAccessor () const
Get the accessor for a specific index within this task.
bool HasAnyWork (const FEntityManager *EntityManager) const
Check whether all required accessors correspond to component types that are present in the given entity manager.
bool HasBeenWrittenToSince (uint32 InSystemVersion)
bool IsValid () const
Check whether this task data is well-formed in the sense that it can perform meaningful work.
template<typename Callback>
void Iterate_PerAllocation (FEntityManager *EntityManager, Callback &&InCallback) const
Perform a thread-safe iteration of all matching allocations within the specified entity manager using this task, inline on the current thread.
template<typename Callback>
void Iterate_PerAllocationImpl (FEntityManager *EntityManager, const FEntityComponentFilter &Filter, Callback &&InCallback) const
Implementation function for Iterate_PerAllocation.
template<typename Callback>
void Iterate_PerEntity (FEntityManager *EntityManager, Callback &&InCallback) const
Perform a thread-safe iteration of all matching entities specified entity manager using this task, inline on the current thread.
template<typename Callback>
void Iterate_PerEntityImpl (FEntityManager *EntityManager, const FEntityComponentFilter &Filter, Callback &&InCallback) const
Implementation function for Iterate_PerEntity.
TEntityTaskComponents< T..., FFilterMatchPassthrough > PassthroughFilter (const FEntityComponentFilter &InFilter) const
void PopulateFilter (FEntityComponentFilter *OutFilter) const
Utility function called when the task is dispatched to populate the filter based on our component typs.
void PopulatePrerequisites (const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs) const
Utility function called when the task is dispatched to populate the filter based on our component typs.
void PopulateReadWriteDependencies (FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies) const
void PopulateSubsequents (const FGraphEventRef &InEvent, FSystemSubsequentTasks &OutSubsequents) const
Utility function called when the task is dispatched to populate the filter based on our component typs.
void PreLockComponentHeaders (FEntityAllocationIteratorItem Item, TArray< FPreLockedDataPtr > &OutComponentHeaders) const
template<typename U>
TEntityTaskComponents< T..., TReadAccess< U > > Read (TComponentTypeID< U > ComponentType) const
Read the value of a component.
template<typename... U>
TEntityTaskComponents< T..., TReadAccess< U >... > ReadAllOf (TComponentTypeID< U >... ComponentTypes) const
Read all of the specified components and pass them through to the task as individual parameters.
template<typename... U>
TEntityTaskComponents< T..., TOptionalReadAccess< U >... > ReadAnyOf (TComponentTypeID< U >... ComponentTypes) const
Read any of the specified components and pass them through to the task as individual optional parameters.
TEntityTaskComponents< T..., FEntityIDAccess > ReadEntityIDs () const
Read the entity ID along with this task.
TEntityTaskComponents< T..., FErasedReadAccess > ReadErased (FComponentTypeID ComponentType) const
Read the type-erased value of a component.
TEntityTaskComponents< T..., FErasedOptionalReadAccess > ReadErasedOptional (FComponentTypeID ComponentType, FComponentTypeIDFilter InConditionType=FComponentTypeIDFilter()) const
Optionally read the type-erased value of a component.
template<typename... U>
TEntityTaskComponents< T..., TReadOneOfAccessor< U... > > ReadOneOf (TComponentTypeID< U >... ComponentTypes) const
Read the value of only one of the specified components.
template<typename... U>
TEntityTaskComponents< T..., TReadOneOrMoreOfAccessor< U... > > ReadOneOrMoreOf (TComponentTypeID< U >... ComponentTypes) const
Read the value of one or more of the specified components.
template<typename U>
TEntityTaskComponents< T..., TOptionalReadAccess< U > > ReadOptional (TComponentTypeID< U > ComponentType, FComponentTypeIDFilter InConditionType=FComponentTypeIDFilter()) const
Optionally read the value of a component.
FString ToString (FEntityManager *EntityManager) const
template<typename U>
TEntityTaskComponents< T..., TWriteAccess< U > > Write (TComponentTypeID< U > ComponentType) const
Write the value of a component in a thread safe manner.
template<typename... U>
TEntityTaskComponents< T..., TWriteAccess< U >... > WriteAllOf (TComponentTypeID< U >... ComponentTypes) const
Write all of the specified components and pass them through to the task as individual parameters.
TEntityTaskComponents< T..., FErasedWriteAccess > WriteErased (FComponentTypeID ComponentType) const
Write the type-erased value of a component.
template<typename U>
TEntityTaskComponents< T..., TOptionalWriteAccess< U > > WriteOptional (TComponentTypeID< U > ComponentType, FComponentTypeIDFilter InConditionType=FComponentTypeIDFilter()) const
Optionally write the value of a component in a thread safe manner if it exists.
Data Fields
FCommonEntityTaskParams CommonParams
Protected Member Functions
TEntityTaskComponentsImpl ()
template<typename... ConstructionTypes>
TEntityTaskComponentsImpl (const FCommonEntityTaskParams &InCommonParams, ConstructionTypes &&... InTypes)
Protected Attributes
TTuple< T... > Accessors
Friends
template<typename...>
struct TEntityTaskComponentsImpl
Detailed Description
template<int... Indices, typename... T>
struct UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >
Definition at line 631 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TEntityTaskComponentsImpl() [1/2]
template<int... Indices, typename... T> UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::TEntityTaskComponentsImpl () inline protected
Definition at line 986 of file MovieSceneEntitySystemTask.h.
TEntityTaskComponentsImpl() [2/2]
template<int... Indices, typename... T> template<typename... ConstructionTypes> UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::TEntityTaskComponentsImpl (const FCommonEntityTaskParams & InCommonParams, ConstructionTypes &&... InTypes) inline explicit protected
Definition at line 990 of file MovieSceneEntitySystemTask.h.
References Accessors, CommonParams, and Forward().
Member Function Documentation
GetAccessor()
template<int... Indices, typename... T> template<int Index> FORCEINLINE auto UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::GetAccessor () const inline
Get the accessor for a specific index within this task.
Definition at line 964 of file MovieSceneEntitySystemTask.h.
References Accessors, and FORCEINLINE.
HasAnyWork()
template<int... Indices, typename... T> bool UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::HasAnyWork (const FEntityManager * EntityManager) const inline
Check whether all required accessors correspond to component types that are present in the given entity manager.
Definition at line 806 of file MovieSceneEntitySystemTask.h.
References Accessors, and UE::MovieScene::HasAccessorWork().
HasBeenWrittenToSince()
template<int... Indices, typename... T> bool UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::HasBeenWrittenToSince (uint32 InSystemVersion) inline
Definition at line 780 of file MovieSceneEntitySystemTask.h.
References Accessors, and UE::MovieScene::HasBeenWrittenToSince().
IsValid()
template<int... Indices, typename... T> bool UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::IsValid () const inline
Check whether this task data is well-formed in the sense that it can perform meaningful work.
Definition at line 793 of file MovieSceneEntitySystemTask.h.
References Accessors, and UE::MovieScene::IsAccessorValid().
Iterate_PerAllocation()
template<int... Indices, typename... T> template<typename Callback> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerAllocation (FEntityManager * EntityManager, Callback && InCallback) const inline
Perform a thread-safe iteration of all matching allocations within the specified entity manager using this task, inline on the current thread.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
InCallback A callable type that matches the signature defined by ForEachAllocation ie void(FEntityAllocation*, const TFilteredEntityTask<T...>&)
Definition at line 863 of file MovieSceneEntitySystemTask.h.
References Filter, Iterate_PerAllocationImpl(), and PopulateFilter().
Iterate_PerAllocationImpl()
template<int... Indices, typename... T> template<typename Callback> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerAllocationImpl (FEntityManager * EntityManager, const FEntityComponentFilter & Filter, Callback && InCallback) const inline
Implementation function for Iterate_PerAllocation.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
Filter Filter that at least must match the types specified by this task
InCallback A callable type that matches the signature defined by ForEachAllocation ie void(FEntityAllocation*, const TFilteredEntityTask<T...>&)
Definition at line 931 of file MovieSceneEntitySystemTask.h.
References Accessors, Filter, IsValid(), Item, MakeTuple(), and UE::MovieScene::NoThreading.
Referenced by Iterate_PerAllocation().
Iterate_PerEntity()
template<int... Indices, typename... T> template<typename Callback> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerEntity (FEntityManager * EntityManager, Callback && InCallback) const inline
Perform a thread-safe iteration of all matching entities specified entity manager using this task, inline on the current thread.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
InCallback A callable type that matches the signature defined by ForEachEntity ie void(typename T::AccessType...)
Definition at line 877 of file MovieSceneEntitySystemTask.h.
References Filter, Iterate_PerEntityImpl(), and PopulateFilter().
Iterate_PerEntityImpl()
template<int... Indices, typename... T> template<typename Callback> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerEntityImpl (FEntityManager * EntityManager, const FEntityComponentFilter & Filter, Callback && InCallback) const inline
Implementation function for Iterate_PerEntity.
Parameters
EntityManager The entity manager to iterate allocations for. All component type IDs in this class must relate to this entity manager
Filter Filter that at least must match the types specified by this task
InCallback A callable type that matches the signature defined by ForEachEntity ie void(typename T::AccessType...)
Definition at line 892 of file MovieSceneEntitySystemTask.h.
References Accessors, DeclVal(), Filter, UE::MovieScene::GetComponentAtIndex(), IsValid(), Item, UE::MovieScene::NoThreading, and Num.
Referenced by Iterate_PerEntity().
PassthroughFilter()
template<int... Indices, typename... T> TEntityTaskComponents< T..., FFilterMatchPassthrough > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PassthroughFilter (const FEntityComponentFilter & InFilter) const inline
Definition at line 775 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
PopulateFilter()
template<int... Indices, typename... T> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateFilter (FEntityComponentFilter * OutFilter) const inline
Utility function called when the task is dispatched to populate the filter based on our component typs.
Definition at line 817 of file MovieSceneEntitySystemTask.h.
References Accessors, and UE::MovieScene::AddAccessorToFilter().
Referenced by Iterate_PerAllocation(), and Iterate_PerEntity().
PopulatePrerequisites()
template<int... Indices, typename... T> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulatePrerequisites (const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs) const inline
Utility function called when the task is dispatched to populate the filter based on our component typs.
Definition at line 824 of file MovieSceneEntitySystemTask.h.
References Accessors, UE::MovieScene::FSystemTaskPrerequisites::FilterByComponent(), UE::MovieScene::FComponentTypeID::Invalid(), and UE::MovieScene::PopulatePrerequisites().
PopulateReadWriteDependencies()
template<int... Indices, typename... T> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateReadWriteDependencies (FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) const inline
Definition at line 850 of file MovieSceneEntitySystemTask.h.
References Accessors, and UE::MovieScene::PopulateReadWriteDependencies().
PopulateSubsequents()
template<int... Indices, typename... T> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateSubsequents (const FGraphEventRef & InEvent, FSystemSubsequentTasks & OutSubsequents) const inline
Utility function called when the task is dispatched to populate the filter based on our component typs.
Definition at line 834 of file MovieSceneEntitySystemTask.h.
References Accessors, UE::MovieScene::FSystemSubsequentTasks::AddRootTask(), and UE::MovieScene::PopulateSubsequents().
PreLockComponentHeaders()
template<int... Indices, typename... T> void UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PreLockComponentHeaders (FEntityAllocationIteratorItem Item, TArray< FPreLockedDataPtr > & OutComponentHeaders) const inline
Definition at line 842 of file MovieSceneEntitySystemTask.h.
References Accessors, TArray< InElementType, InAllocatorType >::AddDefaulted(), Item, and TArray< InElementType, InAllocatorType >::Num().
Read()
template<int... Indices, typename... T> template<typename U> TEntityTaskComponents< T..., TReadAccess< U > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Read (TComponentTypeID< U > ComponentType) const inline
Read the value of a component.
Passed to the task as either a const T& or T depending on the type specified in the task function.
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentType A valid component type to read.
Definition at line 648 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadAllOf()
template<int... Indices, typename... T> template<typename... U> TEntityTaskComponents< T..., TReadAccess< U >... > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadAllOf (TComponentTypeID< U >... ComponentTypes) const inline
Read all of the specified components and pass them through to the task as individual parameters.
Parameters
ComponentTypes The component types to visit
Definition at line 682 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadAnyOf()
template<int... Indices, typename... T> template<typename... U> TEntityTaskComponents< T..., TOptionalReadAccess< U >... > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadAnyOf (TComponentTypeID< U >... ComponentTypes) const inline
Read any of the specified components and pass them through to the task as individual optional parameters.
Parameters
ComponentTypes The component types to visit
Definition at line 693 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadEntityIDs()
template<int... Indices, typename... T> TEntityTaskComponents< T..., FEntityIDAccess > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadEntityIDs () const inline
Read the entity ID along with this task.
Passed to the task as an FMovieSceneEntityID
Definition at line 636 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadErased()
template<int... Indices, typename... T> TEntityTaskComponents< T..., FErasedReadAccess > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadErased (FComponentTypeID ComponentType) const inline
Read the type-erased value of a component.
Passed to the task as a const void*
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentType A valid component type to read.
Definition at line 704 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadErasedOptional()
template<int... Indices, typename... T> TEntityTaskComponents< T..., FErasedOptionalReadAccess > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadErasedOptional (FComponentTypeID ComponentType, FComponentTypeIDFilter InConditionType = FComponentTypeIDFilter()) const inline
Optionally read the type-erased value of a component.
Passed to the task as a const void*
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentType A valid component type to read.
Definition at line 715 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadOneOf()
template<int... Indices, typename... T> template<typename... U> TEntityTaskComponents< T..., TReadOneOfAccessor< U... > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadOneOf (TComponentTypeID< U >... ComponentTypes) const inline
Read the value of only one of the specified components.
Only entities with exactly one of these components will be read. Per-entity iteration not supported with this accessor.
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentTypes The component types to visit
Definition at line 660 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadOneOrMoreOf()
template<int... Indices, typename... T> template<typename... U> TEntityTaskComponents< T..., TReadOneOrMoreOfAccessor< U... > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadOneOrMoreOf (TComponentTypeID< U >... ComponentTypes) const inline
Read the value of one or more of the specified components.
Entities with at least one of these components will be read. Per-entity iteration not supported with this accessor.
Parameters
ComponentTypes The component types to visit
Definition at line 671 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ReadOptional()
template<int... Indices, typename... T> template<typename U> TEntityTaskComponents< T..., TOptionalReadAccess< U > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ReadOptional (TComponentTypeID< U > ComponentType, FComponentTypeIDFilter InConditionType = FComponentTypeIDFilter()) const inline
Optionally read the value of a component.
ComponentType may be invalid, and the component may or may not exist for some/all of the entities in the resulting task
Note
Always passed to the task as a const T* pointer which must be checked for null
Definition at line 725 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
ToString()
template<int... Indices, typename... T> FString UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::ToString (FEntityManager * EntityManager) const inline
Definition at line 970 of file MovieSceneEntitySystemTask.h.
References Accessors, TEXT, and Unused.
Write()
template<int... Indices, typename... T> template<typename U> TEntityTaskComponents< T..., TWriteAccess< U > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Write (TComponentTypeID< U > ComponentType) const inline
Write the value of a component in a thread safe manner.
Passed to the task as a T& so the value can be modified or overwritten.
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentType A valid component type to read.
Definition at line 737 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
WriteAllOf()
template<int... Indices, typename... T> template<typename... U> TEntityTaskComponents< T..., TWriteAccess< U >... > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::WriteAllOf (TComponentTypeID< U >... ComponentTypes) const inline
Write all of the specified components and pass them through to the task as individual parameters.
Parameters
ComponentTypes The component types to visit
Definition at line 748 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
WriteErased()
template<int... Indices, typename... T> TEntityTaskComponents< T..., FErasedWriteAccess > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::WriteErased (FComponentTypeID ComponentType) const inline
Write the type-erased value of a component.
Passed to the task as a void*
Note
Supplying an invalid ComponentType will be handled gracefully, but will result in no task being dispatched.
Parameters
ComponentType A valid component type to read.
Definition at line 759 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
WriteOptional()
template<int... Indices, typename... T> template<typename U> TEntityTaskComponents< T..., TOptionalWriteAccess< U > > UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::WriteOptional (TComponentTypeID< U > ComponentType, FComponentTypeIDFilter InConditionType = FComponentTypeIDFilter()) const inline
Optionally write the value of a component in a thread safe manner if it exists.
Passed to the task as a T* which must be checked for nullptr.
Note
Always passed to the task as a T* pointer which must be checked for null
Definition at line 770 of file MovieSceneEntitySystemTask.h.
References Accessors, and CommonParams.
Friends And Related Symbol Documentation
TEntityTaskComponentsImpl
template<int... Indices, typename... T> template<typename...> friend struct TEntityTaskComponentsImpl friend
Definition at line 997 of file MovieSceneEntitySystemTask.h.
References TEntityTaskComponentsImpl.
Referenced by TEntityTaskComponentsImpl.
Field Documentation
Accessors
template<int... Indices, typename... T> TTuple<T...> UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Accessors protected
Definition at line 999 of file MovieSceneEntitySystemTask.h.
Referenced by TEntityTaskComponentsImpl(), GetAccessor(), HasAnyWork(), HasBeenWrittenToSince(), IsValid(), Iterate_PerAllocationImpl(), Iterate_PerEntityImpl(), PassthroughFilter(), PopulateFilter(), PopulatePrerequisites(), PopulateReadWriteDependencies(), PopulateSubsequents(), PreLockComponentHeaders(), Read(), ReadAllOf(), ReadAnyOf(), ReadEntityIDs(), ReadErased(), ReadErasedOptional(), ReadOneOf(), ReadOneOrMoreOf(), ReadOptional(), ToString(), Write(), WriteAllOf(), WriteErased(), and WriteOptional().
CommonParams
template<int... Indices, typename... T> FCommonEntityTaskParams UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::CommonParams
Definition at line 1003 of file MovieSceneEntitySystemTask.h.
Referenced by TEntityTaskComponentsImpl(), PassthroughFilter(), Read(), ReadAllOf(), ReadAnyOf(), ReadEntityIDs(), ReadErased(), ReadErasedOptional(), ReadOneOf(), ReadOneOrMoreOf(), ReadOptional(), Write(), WriteAllOf(), WriteErased(), and WriteOptional().
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h