Unreal Engine 5.6 C++ API: FQueuedThreadPoolDynamicWrapper Class Reference
FQueuedThreadPoolDynamicWrapper Class Reference
ThreadPool wrapper implementation allowing to schedule up to MaxConcurrency tasks at a time making sub-partitioning another thread-pool a breeze and allowing more fine-grained control over scheduling by giving full control of task reordering.
#include "QueuedThreadPoolWrapper.h"
Public Member Functions
FQueuedThreadPoolDynamicWrapper (FQueuedThreadPool *InWrappedQueuedThreadPool, int32 InMaxConcurrency=-1, TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper=DefaultQueuedWorkPriorityWrapper)
InWrappedQueuedThreadPool Underlying thread pool to schedule task to.
void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal) override
Checks to see if there is a thread available to perform the task.
void Sort (TFunctionRef< bool(const IQueuedWork *Lhs, const IQueuedWork *Rhs)> Predicate)
Apply sort predicate to reorder the queued tasks.
Public Member Functions inherited from FQueuedThreadPoolWrapper
FQueuedThreadPoolWrapper (FQueuedThreadPool *InWrappedQueuedThreadPool, int32 InMaxConcurrency=-1, TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper=DefaultQueuedWorkPriorityWrapper)
InWrappedQueuedThreadPool Underlying thread pool to schedule task to.
~FQueuedThreadPoolWrapper ()
void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal) override
Checks to see if there is a thread available to perform the task.
int32 GetCurrentConcurrency () const
int32 GetNumThreads () const override
Get the number of queued threads.
void Pause ()
Queued task are not scheduled against the wrapped thread-pool until resumed.
void Resume (int32 InNumQueuedWork=-1)
Resume a specified amount of queued work, or -1 to unpause.
bool RetractQueuedWork (IQueuedWork *InQueuedWork) override
Attempts to retract a previously queued task.
void SetMaxConcurrency (int32 MaxConcurrency=-1)
Dynamically adjust the maximum number of concurrent tasks, -1 for unlimited.
Public Member Functions inherited from FQueuedThreadPool
FQueuedThreadPool ()
virtual ~FQueuedThreadPool ()
virtual bool CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
Additional Inherited Members
Static Public Member Functions inherited from FQueuedThreadPool
static FQueuedThreadPool * Allocate ()
Allocates a thread pool.
Static Public Attributes inherited from FQueuedThreadPool
static uint32 OverrideStackSize
Stack size for threads created for the thread pool.
Protected Member Functions inherited from FQueuedThreadPoolWrapper
virtual FScheduledWork * AllocateScheduledWork ()
virtual int32 GetMaxConcurrency () const
virtual void OnScheduled (const IQueuedWork *)
virtual void OnUnscheduled (const IQueuedWork *)
Protected Attributes inherited from FQueuedThreadPoolWrapper
FCriticalSection Lock
FThreadPoolPriorityQueue QueuedWork
Detailed Description
ThreadPool wrapper implementation allowing to schedule up to MaxConcurrency tasks at a time making sub-partitioning another thread-pool a breeze and allowing more fine-grained control over scheduling by giving full control of task reordering.
Definition at line 230 of file QueuedThreadPoolWrapper.h.
Constructor & Destructor Documentation
FQueuedThreadPoolDynamicWrapper()
FQueuedThreadPoolDynamicWrapper::FQueuedThreadPoolDynamicWrapper (FQueuedThreadPool * InWrappedQueuedThreadPool, int32 InMaxConcurrency = -1, TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper = DefaultQueuedWorkPriorityWrapper) inline
InWrappedQueuedThreadPool Underlying thread pool to schedule task to.
InMaxConcurrency Maximum number of concurrent tasks allowed, -1 will limit concurrency to number of threads available in the underlying thread pool. InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the underlying thread pool.
Definition at line 238 of file QueuedThreadPoolWrapper.h.
References FQueuedThreadPool::FQueuedThreadPool(), FQueuedThreadPoolWrapper::FQueuedThreadPoolWrapper(), and DefaultQueuedWorkPriorityWrapper.
Member Function Documentation
AddQueuedWork()
void FQueuedThreadPoolDynamicWrapper::AddQueuedWork (IQueuedWork * InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) inline override virtual
Checks to see if there is a thread available to perform the task.
If not, it queues the work for later. Otherwise it is immediately dispatched.
Parameters
InQueuedWork The work that needs to be done asynchronously
InQueuedWorkPriority The priority at which to process this task
See also
RetractQueuedWork
Implements FQueuedThreadPool.
Definition at line 243 of file QueuedThreadPoolWrapper.h.
References FQueuedThreadPoolWrapper::AddQueuedWork(), and Normal.
Sort()
void FQueuedThreadPoolDynamicWrapper::Sort (TFunctionRef< bool(const IQueuedWork *Lhs, const IQueuedWork *Rhs)> Predicate) inline
Apply sort predicate to reorder the queued tasks.
Definition at line 252 of file QueuedThreadPoolWrapper.h.
References FQueuedThreadPoolWrapper::Lock, Normal, Predicate, and FQueuedThreadPoolWrapper::QueuedWork.
The documentation for this class was generated from the following file:
QueuedThreadPoolWrapper.h