Unreal Engine 5.6 C++ API: MemberReference.h File Reference
MemberReference.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "UObject/Class.h"
#include "Templates/SubclassOf.h"
#include "UObject/UnrealType.h"
#include "UObject/Package.h"
#include "UObject/UObjectIterator.h"
#include "Engine/Blueprint.h"
#include "EngineLogs.h"
#include "MemberReference.generated.h"
Data Structures
struct FFieldRemapInfo
Helper struct to allow us to redirect properties and functions through renames and additionally between classes if necessary.
struct FParamRemapInfo
Helper struct to allow us to redirect pin name for node class.
Functions
USTRUCT () struct FMemberReference
Function Documentation
USTRUCT()
USTRUCT ()
Most often the Class that this member is defined in. Could be a UPackage if it is a native delegate signature function (declared globally). Should be NULL if bSelfContext is true.
Name of variable
The Guid of the variable
Whether or not this should be a "self" context
Whether or not this property has been deprecated
Set up this reference from a supplied field
Update given a new self
Set to a non-'self' member, so must include reference to class owning the member.
Set to reference a global field (intended for things like natively defined delegate signatures)
Set to a non-'self' delegate member, this is not self-context but is not given a parent class
Set up this reference to a 'self' member name
Set up this reference to a 'self' member name, scoped to a struct
Set up this reference to a 'self' member name, scoped to a struct name
Only intended for backwards compat!
Invalidate the current MemberParent, if this is a self scope, or the MemberScope if it is not (and set). Intended for PostDuplication fixups
Get the name of this member
Reset the member name only. Intended for use primarily as a helper method for rename operations.
Returns if this is a 'self' context.
Returns if this is a local scope.
Returns true if this is in the sparse data struct for OwningClass
Returns a search string to submit to Find-in-Blueprints to find references to this reference
Parameters
InFieldOwner The owner of the field, cannot be resolved internally
Returns
Search string to find this reference in other Blueprints
Refreshes a local variable reference name if it has changed
Parameters
InSelfScope Scope to lookup the variable in, to see if it has changed
Only intended for backwards compat!
Get the class that owns this member
Get the scope of this member
Get the name of the scope of this member
Compares with another MemberReference to see if they are identical
Returns whether or not the variable has been deprecated
Returns the scope for the current member. This will vary based on whether or not this member uses the self context or not.
Returns the member FProperty/UFunction this reference is pointing to, or NULL if it no longer exists Derives 'self' scope from supplied Blueprint node if required Will check for redirects and fix itself up if one is found (when WITH_EDITOR, or when bAlwaysFollowRedirects is true).
ResolveMember overload for UBlueprint, uses the skeleton class so it can be more up to date
Searches the field redirect map for the specified named field in the scope, and returns the remapped field if found
Parameters
FieldClass UClass of field type we are looking for
InitialScope The scope the field was initially defined in. The function will search up into parent scopes to attempt to find remappings
InitialName The name of the field to attempt to find a redirector for
bInitialScopeMustBeOwnerOfFieldForParentScopeRedirect If true, and a redirect is found in a parent scope, and the targetscope of the redirect is a child scope of the parent scope that is not the initial scope or a parent of the initial scope, then the redirect will be ignored.
Returns
The remapped field, if one exists
Templated version of above, extracts FieldClass and Casts result
Init the field redirect map (if not already done) from .ini file entries
Has the field map been initialized this run
Returns
the 'real' generated class for blueprint classes, but only if we're already passed through CompileClassLayout
Definition at line 63 of file MemberReference.h.
References Cast(), FindUField(), GENERATED_USTRUCT_BODY, FFieldVariant::Get(), UObjectBase::GetFName(), UField::GetOwnerClass(), HEADER_GENERATED_DELEGATE_SIGNATURE_SUFFIX, FGuid::Invalidate(), Name, and UPROPERTY.