Unreal Engine 5.6 C++ API: FMaterialListItem Struct Reference
FMaterialListItem Struct Reference
A Material item in a material list slot.
#include "MaterialList.h"
Public Member Functions
FMaterialListItem (UMaterialInterface *InMaterial=NULL, uint32 InSlotIndex=0, bool bInCanBeReplaced=false, UActorComponent *InCurrentComponent=nullptr, FName InSlotName=FName())
bool operator!= (const FMaterialListItem &Other) const
bool operator== (const FMaterialListItem &Other) const
Data Fields
bool bCanBeReplaced
Whether or not this material can be replaced by a new material.
TWeakObjectPtr< UActorComponent > CurrentComponent
The current component using the current material.
TWeakObjectPtr< UMaterialInterface > Material
Material being used.
int32 SlotIndex
Slot on a component where this material is at (mesh element)
FName SlotName
User-specified name for the slot on a component where this material is at (mesh element).
Friends
uint32 GetTypeHash (const FMaterialListItem &InItem)
Detailed Description
A Material item in a material list slot.
Definition at line 108 of file MaterialList.h.
Constructor & Destructor Documentation
FMaterialListItem()
FMaterialListItem::FMaterialListItem (UMaterialInterface * InMaterial = NULL, uint32 InSlotIndex = 0, bool bInCanBeReplaced = false, UActorComponent * InCurrentComponent = nullptr, FName InSlotName = FName()) inline
Definition at line 125 of file MaterialList.h.
References bCanBeReplaced, CurrentComponent, Material, SlotIndex, and SlotName.
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
bool FMaterialListItem::operator!= (const FMaterialListItem & Other) const inline
Definition at line 143 of file MaterialList.h.
References FMaterialListItem(), and Other.
operator==()
bool FMaterialListItem::operator== (const FMaterialListItem & Other) const inline
Definition at line 138 of file MaterialList.h.
References FMaterialListItem(), Material, Other, SlotIndex, and SlotName.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FMaterialListItem & InItem) friend
Definition at line 133 of file MaterialList.h.
References FMaterialListItem(), GetTypeHash, HashCombine(), Material, SlotIndex, and SlotName.
Referenced by GetTypeHash.
Field Documentation
bCanBeReplaced
bool FMaterialListItem::bCanBeReplaced
Whether or not this material can be replaced by a new material.
Definition at line 117 of file MaterialList.h.
Referenced by FMaterialListItem().
CurrentComponent
TWeakObjectPtr<UActorComponent> FMaterialListItem::CurrentComponent
The current component using the current material.
Definition at line 120 of file MaterialList.h.
Referenced by FMaterialListItem().
Material
TWeakObjectPtr<UMaterialInterface> FMaterialListItem::Material
Material being used.
Definition at line 111 of file MaterialList.h.
Referenced by FMaterialListItem(), GetTypeHash, and operator==().
SlotIndex
int32 FMaterialListItem::SlotIndex
Slot on a component where this material is at (mesh element)
Definition at line 114 of file MaterialList.h.
Referenced by FMaterialListItem(), GetTypeHash, and operator==().
SlotName
FName FMaterialListItem::SlotName
User-specified name for the slot on a component where this material is at (mesh element).
May be empty.
Definition at line 123 of file MaterialList.h.
Referenced by FMaterialListItem(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
MaterialList.h