Unreal Engine 5.6 C++ API: NetworkPredictionPhysicsCvars Namespace Reference
NetworkPredictionPhysicsCvars Namespace Reference
Functions
int32 DebugPositionCorrections ()
static FConditionalAutoConsoleRegister DebugPositionCorrectionsAuto (TEXT("np.Physics.DebugPositionCorrections"),(int32) 0, TEXT("Prints position history when correcting physics X"))
int32 FullPrecision ()
static FConditionalAutoConsoleRegister FullPrecisionAuto (TEXT("np.Physics.FullPrecision"),(int32) 1, TEXT("Replicatre physics state with full precision. Not to be toggled during gameplay."))
void SetDebugPositionCorrections (int32 _V)
void SetFullPrecision (int32 _V)
void SetToleranceR (float _V)
void SetToleranceV (float _V)
void SetToleranceW (float _V)
void SetToleranceX (float _V)
float ToleranceR ()
static FConditionalAutoConsoleRegister ToleranceRAuto (TEXT("np.Physics.Tolerance.R"),(float) 0.1, TEXT("Normalized error tolerance between rotation (0..1)"))
float ToleranceV ()
static FConditionalAutoConsoleRegister ToleranceVAuto (TEXT("np.Physics.Tolerance.V"),(float) 1.0, TEXT("Absolute error tolerance for velocity "))
float ToleranceW ()
static FConditionalAutoConsoleRegister ToleranceWAuto (TEXT("np.Physics.Tolerance.W"),(float) 1.0, TEXT("Absolute error tolerance for rotational velocity "))
float ToleranceX ()
static FConditionalAutoConsoleRegister ToleranceXAuto (TEXT("np.Physics.Tolerance.X"),(float) 1.0, TEXT("Absolute tolerance for position"))
Function Documentation
DebugPositionCorrections()
int32 NetworkPredictionPhysicsCvars::DebugPositionCorrections () inline
Definition at line 19 of file NetworkPredictionPhysics.h.
References DebugPositionCorrections().
Referenced by DebugPositionCorrections().
DebugPositionCorrectionsAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::DebugPositionCorrectionsAuto (TEXT("np.Physics.DebugPositionCorrections") , (int32) 0, TEXT("Prints position history when correcting physics X")) static
FullPrecision()
int32 NetworkPredictionPhysicsCvars::FullPrecision () inline
Definition at line 18 of file NetworkPredictionPhysics.h.
References FullPrecision().
Referenced by FullPrecision(), and FNetworkPredictionPhysicsState::NetRecv().
FullPrecisionAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::FullPrecisionAuto (TEXT("np.Physics.FullPrecision") , (int32) 1, TEXT("Replicatre physics state with full precision. Not to be toggled during gameplay.")) static
SetDebugPositionCorrections()
void NetworkPredictionPhysicsCvars::SetDebugPositionCorrections (int32 _V) inline
Definition at line 19 of file NetworkPredictionPhysics.h.
SetFullPrecision()
void NetworkPredictionPhysicsCvars::SetFullPrecision (int32 _V) inline
Definition at line 18 of file NetworkPredictionPhysics.h.
SetToleranceR()
void NetworkPredictionPhysicsCvars::SetToleranceR (float _V) inline
Definition at line 22 of file NetworkPredictionPhysics.h.
References ToleranceR().
SetToleranceV()
void NetworkPredictionPhysicsCvars::SetToleranceV (float _V) inline
Definition at line 23 of file NetworkPredictionPhysics.h.
References ToleranceV().
SetToleranceW()
void NetworkPredictionPhysicsCvars::SetToleranceW (float _V) inline
Definition at line 24 of file NetworkPredictionPhysics.h.
References ToleranceW().
SetToleranceX()
void NetworkPredictionPhysicsCvars::SetToleranceX (float _V) inline
Definition at line 21 of file NetworkPredictionPhysics.h.
References ToleranceX().
ToleranceR()
float NetworkPredictionPhysicsCvars::ToleranceR () inline
Definition at line 22 of file NetworkPredictionPhysics.h.
Referenced by SetToleranceR().
ToleranceRAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::ToleranceRAuto (TEXT("np.Physics.Tolerance.R") , (float) 0. 1, TEXT("Normalized error tolerance between rotation (0..1)")) static
ToleranceV()
float NetworkPredictionPhysicsCvars::ToleranceV () inline
Definition at line 23 of file NetworkPredictionPhysics.h.
Referenced by SetToleranceV().
ToleranceVAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::ToleranceVAuto (TEXT("np.Physics.Tolerance.V") , (float) 1. 0, TEXT("Absolute error tolerance for velocity ")) static
ToleranceW()
float NetworkPredictionPhysicsCvars::ToleranceW () inline
Definition at line 24 of file NetworkPredictionPhysics.h.
Referenced by SetToleranceW().
ToleranceWAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::ToleranceWAuto (TEXT("np.Physics.Tolerance.W") , (float) 1. 0, TEXT("Absolute error tolerance for rotational velocity ")) static
ToleranceX()
float NetworkPredictionPhysicsCvars::ToleranceX () inline
Definition at line 21 of file NetworkPredictionPhysics.h.
Referenced by SetToleranceX().
ToleranceXAuto()
FConditionalAutoConsoleRegister NetworkPredictionPhysicsCvars::ToleranceXAuto (TEXT("np.Physics.Tolerance.X") , (float) 1. 0, TEXT("Absolute tolerance for position")) static