Unreal Engine 5.6 C++ API: ISequencerModule Class Reference
ISequencerModule Class Reference abstract
Interface for the Sequencer module.
#include "ISequencerModule.h"
Data Structures
struct FSequenceEditorEntry
Public Member Functions
virtual ~ISequencerModule ()
virtual bool CanAnimateProperty (FProperty *Property)=0
Check whether the specified property type can be animated by sequeuncer.
virtual TSharedRef< ISequencer > CreateSequencer (const FSequencerInitParams &InitParams)=0
Create a new instance of a standalone sequencer that can be added to other UIs.
ISequencerChannelInterface * FindChannelEditorInterface (FName ChannelTypeName) const
Find a sequencer channel for the specified channel type name.
virtual TSharedPtr< UE::Sequencer::IObjectSchema > FindObjectSchema (const UObject *Object) const =0
Find an object schema for the specified object.
FMovieSceneSequenceEditor * FindSequenceEditor (UClass *SequenceClass) const
Find a sequence editor for the specified sequence class.
virtual TSharedPtr< FExtensibilityManager > GetActionsMenuExtensibilityManager () const =0
Get the extensibility manager for the actions menu.
virtual TSharedPtr< FExtensibilityManager > GetAddTrackMenuExtensibilityManager () const =0
Get the extensibility manager for add track menus.
virtual IMovieRendererInterface * GetMovieRenderer (const FString &InMovieRendererName)=0
Get the movie renderer with the requested name.
virtual TArray< FString > GetMovieRendererNames ()=0
Get a list of registered movie renderers.
virtual TSharedPtr< FExtensibilityManager > GetObjectBindingContextMenuExtensibilityManager () const =0
Get the extensibility manager for object binding menus.
virtual TArrayView< const TSharedPtr< UE::Sequencer::IObjectSchema > > GetObjectSchemas () const =0
Retrieve all the currently registered object schemas.
virtual TSharedPtr< FSequencerCustomizationManager > GetSequencerCustomizationManager () const =0
Get the sequencer customization manager, which handles editor customizations applied based on the currently focused sequence type and other dynamic criteria.
virtual TSharedPtr< FExtensibilityManager > GetSidebarExtensibilityManager () const =0
Get the extensibility manager for the sidebar.
virtual TSharedPtr< FExtensibilityManager > GetToolBarExtensibilityManager () const =0
Get the extensibility manager for toolbars.
virtual TSharedPtr< FExtensibilityManager > GetViewMenuExtensibilityManager () const =0
Get the extensibility manager for the view options menu.
template<typename ChannelType>
void RegisterChannelInterface ()
Register a sequencer channel type using a default channel interface.
template<typename ChannelType>
void RegisterChannelInterface (TUniquePtr< ISequencerChannelInterface > &&InInterface)
Register a sequencer channel type using the specified interface.
virtual FDelegateHandle RegisterEditorObjectBinding (FOnCreateEditorObjectBinding InOnCreateEditorObjectBinding)=0
Registers a delegate that will create editor UI for an object binding in sequencer.
virtual FDelegateHandle RegisterMovieRenderer (TUniquePtr< IMovieRendererInterface > &&InMovieRenderer)=0
Register a movie renderer for this sequencer.
virtual void RegisterObjectSchema (TSharedPtr< UE::Sequencer::IObjectSchema > InObjectSchema)=0
Register a new object schema defining how an object is able to be animated through Sequencer.
virtual FDelegateHandle RegisterOnPreSequencerInit (FOnPreSequencerInit::FDelegate InOnPreSequencerInit)=0
Registers a delegate that will be called just before a sequencer is initialized.
virtual FDelegateHandle RegisterOnSequencerCreated (FOnSequencerCreated::FDelegate InOnSequencerCreated)=0
Registers a delegate that will be called when a sequencer is created.
virtual FDelegateHandle RegisterOutlinerColumn (FOnCreateOutlinerColumn InCreator)=0
Registers a delegate that will create a gutter column view model for a given Outliner column.
virtual FDelegateHandle RegisterOutlinerIndicator (FOnCreateOutlinerIndicator InCreator)=0
Registers a delegate that will create an outliner indicator item.
virtual void RegisterPropertyAnimator (FAnimatedPropertyKey Key)=0
Register that the specified property type can be animated in sequencer.
template<typename PropertyTrackEditorType>
FDelegateHandle RegisterPropertyTrackEditor ()
Helper template for registering property track editors.
FDelegateHandle RegisterSequenceEditor (UClass *SequenceClass, TUniquePtr< FMovieSceneSequenceEditor > &&InSequenceEditor)
Register a sequence editor for the specified type of sequence.
virtual FDelegateHandle RegisterTrackEditor (FOnCreateTrackEditor InOnCreateTrackEditor, TArrayView< FAnimatedPropertyKey > AnimatedPropertyTypes=TArrayView< FAnimatedPropertyKey >())=0
Registers a delegate that will create an editor for a track in each sequencer.
virtual FDelegateHandle RegisterTrackModel (FOnCreateTrackModel InCreator)=0
Registers a delegate that will create a track view model for a given track.
virtual void UnRegisterEditorObjectBinding (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate for creating editor UI for an object binding in sequencer.
virtual void UnregisterMovieRenderer (FDelegateHandle InDelegateHandle)=0
Unregister a movie renderer for this sequencer.
virtual void UnregisterObjectSchema (TSharedPtr< UE::Sequencer::IObjectSchema > InSchema)=0
Unregister a new object schema defining how an object is able to be animated through Sequencer.
virtual void UnregisterOnPreSequencerInit (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate called just before a sequencer is initialized.
virtual void UnregisterOnSequencerCreated (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate called when a sequencer is created.
virtual void UnregisterOutlinerColumn (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate for creating Outliner columns.
virtual void UnregisterOutlinerIndicator (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate for creating an outliner indicator item.
virtual void UnRegisterPropertyAnimator (FAnimatedPropertyKey Key)=0
Unregister that the specified property type can be animated in sequencer.
void UnregisterSequenceEditor (FDelegateHandle Handle)
Unregister a sequence editor for the specified type of sequence.
virtual void UnRegisterTrackEditor (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate for creating a track editor.
virtual void UnregisterTrackModel (FDelegateHandle InHandle)=0
Unregisters a previously registered delegate for creating track view models.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static ECurveEditorTreeFilterType GetSequencerSelectionFilterType ()
Retrieve the unique identifer for the sequencer selection curve editor filter (of type FSequencerSelectionCurveFilter)
Private Attributes
TMap< FName, TUniquePtr< ISequencerChannelInterface > > ChannelToEditorInterfaceMap
Map of sequencer interfaces for movie scene channel types, keyed on channel UStruct name.
TArray< FSequenceEditorEntry > SequenceEditors
Array of sequence editor entries.
Detailed Description
Interface for the Sequencer module.
Definition at line 217 of file ISequencerModule.h.
Constructor & Destructor Documentation
~ISequencerModule()
virtual ISequencerModule::~ISequencerModule () virtual
Member Function Documentation
CanAnimateProperty()
virtual bool ISequencerModule::CanAnimateProperty (FProperty * Property) pure virtual
Check whether the specified property type can be animated by sequeuncer.
References Property.
CreateSequencer()
virtual TSharedRef< ISequencer > ISequencerModule::CreateSequencer (const FSequencerInitParams & InitParams) pure virtual
Create a new instance of a standalone sequencer that can be added to other UIs.
Parameters
InitParams Initialization parameters.
Returns
The new sequencer object.
FindChannelEditorInterface()
ISequencerChannelInterface * ISequencerModule::FindChannelEditorInterface (FName ChannelTypeName) const inline
Find a sequencer channel for the specified channel type name.
Definition at line 569 of file ISequencerModule.h.
References ChannelToEditorInterfaceMap, ensureMsgf, Found, and TEXT.
FindObjectSchema()
virtual TSharedPtr< UE::Sequencer::IObjectSchema > ISequencerModule::FindObjectSchema (const UObject * Object) const pure virtual
Find an object schema for the specified object.
References Object.
FindSequenceEditor()
FMovieSceneSequenceEditor * ISequencerModule::FindSequenceEditor (UClass * SequenceClass) const inline
Find a sequence editor for the specified sequence class.
Definition at line 470 of file ISequencerModule.h.
References check, UStruct::IsChildOf(), and SequenceEditors.
GetActionsMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetActionsMenuExtensibilityManager () const pure virtual
Get the extensibility manager for the actions menu.
Returns
Toolbar extensibility manager.
GetAddTrackMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetAddTrackMenuExtensibilityManager () const pure virtual
Get the extensibility manager for add track menus.
Returns
Add Track Menu extensibility manager.
GetMovieRenderer()
virtual IMovieRendererInterface * ISequencerModule::GetMovieRenderer (const FString & InMovieRendererName) pure virtual
Get the movie renderer with the requested name.
GetMovieRendererNames()
virtual TArray< FString > ISequencerModule::GetMovieRendererNames () pure virtual
Get a list of registered movie renderers.
GetObjectBindingContextMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetObjectBindingContextMenuExtensibilityManager () const pure virtual
Get the extensibility manager for object binding menus.
Returns
ObjectBinding Context Menu extensibility manager.
GetObjectSchemas()
virtual TArrayView< const TSharedPtr< UE::Sequencer::IObjectSchema > > ISequencerModule::GetObjectSchemas () const pure virtual
Retrieve all the currently registered object schemas.
GetSequencerCustomizationManager()
virtual TSharedPtr< FSequencerCustomizationManager > ISequencerModule::GetSequencerCustomizationManager () const pure virtual
Get the sequencer customization manager, which handles editor customizations applied based on the currently focused sequence type and other dynamic criteria.
GetSequencerSelectionFilterType()
ECurveEditorTreeFilterType ISequencerModule::GetSequencerSelectionFilterType () static
Retrieve the unique identifer for the sequencer selection curve editor filter (of type FSequencerSelectionCurveFilter)
GetSidebarExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetSidebarExtensibilityManager () const pure virtual
Get the extensibility manager for the sidebar.
Returns
Sidebar extensibility manager.
GetToolBarExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetToolBarExtensibilityManager () const pure virtual
Get the extensibility manager for toolbars.
Returns
Toolbar extensibility manager.
GetViewMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > ISequencerModule::GetViewMenuExtensibilityManager () const pure virtual
Get the extensibility manager for the view options menu.
Returns
Toolbar extensibility manager.
RegisterChannelInterface() [1/2]
template<typename ChannelType> void ISequencerModule::RegisterChannelInterface ()
Register a sequencer channel type using a default channel interface.
Definition at line 550 of file ISequencerModule.h.
References RegisterChannelInterface().
Referenced by RegisterChannelInterface().
RegisterChannelInterface() [2/2]
template<typename ChannelType> void ISequencerModule::RegisterChannelInterface (TUniquePtr< ISequencerChannelInterface > && InInterface)
Register a sequencer channel type using the specified interface.
Definition at line 559 of file ISequencerModule.h.
References ChannelToEditorInterfaceMap, check, and MoveTemp().
RegisterEditorObjectBinding()
virtual FDelegateHandle ISequencerModule::RegisterEditorObjectBinding (FOnCreateEditorObjectBinding InOnCreateEditorObjectBinding) pure virtual
Registers a delegate that will create editor UI for an object binding in sequencer.
Parameters
InOnCreateEditorObjectBinding Delegate to register.
Returns
A handle to the newly-added delegate.
RegisterMovieRenderer()
virtual FDelegateHandle ISequencerModule::RegisterMovieRenderer (TUniquePtr< IMovieRendererInterface > && InMovieRenderer) pure virtual
Register a movie renderer for this sequencer.
RegisterObjectSchema()
virtual void ISequencerModule::RegisterObjectSchema (TSharedPtr< UE::Sequencer::IObjectSchema > InObjectSchema) pure virtual
Register a new object schema defining how an object is able to be animated through Sequencer.
RegisterOnPreSequencerInit()
virtual FDelegateHandle ISequencerModule::RegisterOnPreSequencerInit (FOnPreSequencerInit::FDelegate InOnPreSequencerInit) pure virtual
Registers a delegate that will be called just before a sequencer is initialized.
Parameters
InOnPreSequencerInit Delegate to register.
Returns
A handle to the newly-added delegate.
RegisterOnSequencerCreated()
virtual FDelegateHandle ISequencerModule::RegisterOnSequencerCreated (FOnSequencerCreated::FDelegate InOnSequencerCreated) pure virtual
Registers a delegate that will be called when a sequencer is created.
Parameters
InOnSequencerCreated Delegate to register.
Returns
A handle to the newly-added delegate.
RegisterOutlinerColumn()
virtual FDelegateHandle ISequencerModule::RegisterOutlinerColumn (FOnCreateOutlinerColumn InCreator) pure virtual
Registers a delegate that will create a gutter column view model for a given Outliner column.
Parameters
InCreator Delegate to register
Returns
A handle to the newly added delegate
RegisterOutlinerIndicator()
virtual FDelegateHandle ISequencerModule::RegisterOutlinerIndicator (FOnCreateOutlinerIndicator InCreator) pure virtual
Registers a delegate that will create an outliner indicator item.
Parameters
InCreator Delegate to register
Returns
A handle to the newly added delegate
RegisterPropertyAnimator()
virtual void ISequencerModule::RegisterPropertyAnimator (FAnimatedPropertyKey Key) pure virtual
Register that the specified property type can be animated in sequencer.
References Key.
RegisterPropertyTrackEditor()
template<typename PropertyTrackEditorType> FDelegateHandle ISequencerModule::RegisterPropertyTrackEditor () inline
Helper template for registering property track editors.
Parameters
InOnCreateTrackEditor Delegate to register.
Returns
A handle to the newly-added delegate.
Definition at line 501 of file ISequencerModule.h.
References RegisterTrackEditor().
RegisterSequenceEditor()
FDelegateHandle ISequencerModule::RegisterSequenceEditor (UClass * SequenceClass, TUniquePtr< FMovieSceneSequenceEditor > && InSequenceEditor) inline
Register a sequence editor for the specified type of sequence.
Sequence editors provide editor-only functionality for particular sequence types.
Definition at line 448 of file ISequencerModule.h.
References check, FDelegateHandle::GenerateNewHandle, MoveTemp(), and SequenceEditors.
RegisterTrackEditor()
virtual FDelegateHandle ISequencerModule::RegisterTrackEditor (FOnCreateTrackEditor InOnCreateTrackEditor, TArrayView< FAnimatedPropertyKey > AnimatedPropertyTypes = TArrayView< FAnimatedPropertyKey >()) pure virtual
Registers a delegate that will create an editor for a track in each sequencer.
Parameters
InOnCreateTrackEditor Delegate to register.
Returns
A handle to the newly-added delegate.
Referenced by RegisterPropertyTrackEditor().
RegisterTrackModel()
virtual FDelegateHandle ISequencerModule::RegisterTrackModel (FOnCreateTrackModel InCreator) pure virtual
Registers a delegate that will create a track view model for a given track.
Parameters
InCreator Delegate to register
Returns
A handle to the newly-added delegate
UnRegisterEditorObjectBinding()
virtual void ISequencerModule::UnRegisterEditorObjectBinding (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate for creating editor UI for an object binding in sequencer.
Parameters
InHandle Handle to the delegate to unregister
UnregisterMovieRenderer()
virtual void ISequencerModule::UnregisterMovieRenderer (FDelegateHandle InDelegateHandle) pure virtual
Unregister a movie renderer for this sequencer.
UnregisterObjectSchema()
virtual void ISequencerModule::UnregisterObjectSchema (TSharedPtr< UE::Sequencer::IObjectSchema > InSchema) pure virtual
Unregister a new object schema defining how an object is able to be animated through Sequencer.
UnregisterOnPreSequencerInit()
virtual void ISequencerModule::UnregisterOnPreSequencerInit (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate called just before a sequencer is initialized.
Parameters
InHandle Handle to the delegate to unregister
UnregisterOnSequencerCreated()
virtual void ISequencerModule::UnregisterOnSequencerCreated (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate called when a sequencer is created.
Parameters
InHandle Handle to the delegate to unregister
UnregisterOutlinerColumn()
virtual void ISequencerModule::UnregisterOutlinerColumn (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate for creating Outliner columns.
Parameters
InHandle Handle to the delegate to unregister
UnregisterOutlinerIndicator()
virtual void ISequencerModule::UnregisterOutlinerIndicator (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate for creating an outliner indicator item.
Parameters
InHandle Handle to the delegate to unregister
UnRegisterPropertyAnimator()
virtual void ISequencerModule::UnRegisterPropertyAnimator (FAnimatedPropertyKey Key) pure virtual
Unregister that the specified property type can be animated in sequencer.
References Key.
UnregisterSequenceEditor()
void ISequencerModule::UnregisterSequenceEditor (FDelegateHandle Handle) inline
Unregister a sequence editor for the specified type of sequence.
Definition at line 462 of file ISequencerModule.h.
References Handle, ISequencerModule::FSequenceEditorEntry::Handle, and SequenceEditors.
UnRegisterTrackEditor()
virtual void ISequencerModule::UnRegisterTrackEditor (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate for creating a track editor.
Parameters
InHandle Handle to the delegate to unregister
UnregisterTrackModel()
virtual void ISequencerModule::UnregisterTrackModel (FDelegateHandle InHandle) pure virtual
Unregisters a previously registered delegate for creating track view models.
Parameters
InHandle Handle to the delegate to unregister
Field Documentation
ChannelToEditorInterfaceMap
TMap<FName, TUniquePtr<ISequencerChannelInterface> > ISequencerModule::ChannelToEditorInterfaceMap private
Map of sequencer interfaces for movie scene channel types, keyed on channel UStruct name.
Definition at line 532 of file ISequencerModule.h.
Referenced by FindChannelEditorInterface(), and RegisterChannelInterface().
SequenceEditors
TArray<FSequenceEditorEntry> ISequencerModule::SequenceEditors private
Array of sequence editor entries.
Definition at line 542 of file ISequencerModule.h.
Referenced by FindSequenceEditor(), RegisterSequenceEditor(), and UnregisterSequenceEditor().
The documentation for this class was generated from the following file:
ISequencerModule.h