Unreal Engine 5.6 C++ API: TSequenceNumber< NumBits, SequenceType > Class Template Reference
TSequenceNumber< NumBits, SequenceType > Class Template Reference
Helper class to work with sequence numbers.
#include "SequenceNumber.h"
Public Types
enum { SeqNumberMax = SeqNumberCount - 1u }
enum { SeqNumberHalf = SequenceT(1) << (NumBits - 1) }
enum { SeqNumberCount = SequenceT(1) << NumBits }
enum { SeqNumberMask = SeqNumberMax }
enum { SeqNumberBits = NumBits }
using DifferenceT = int32
using SequenceT = SequenceType
Public Member Functions
TSequenceNumber ()
Default constructor.
TSequenceNumber (SequenceT ValueIn)
Constructor with given value.
SequenceT Get () const
Get Current Value.
TSequenceNumber & operator++ ()
Pre-increment and wrap around.
TSequenceNumber operator++ (int)
Post-increment and wrap around.
bool operator> (const TSequenceNumber &Other) const
return true if this is > Other, this is only considered to be the case if (A - B) < SeqNumberHalf since we have to be able to detect wraparounds
bool operator>= (const TSequenceNumber &Other) const
Check if this is >= Other, See above.
Static Public Member Functions
static DifferenceT Diff (TSequenceNumber A, TSequenceNumber B)
Diff between sequence numbers (A - B) only valid if (A - B) < SeqNumberHalf.
Private Member Functions
void Increment (SequenceT InValue)
Private Attributes
SequenceT Value
Friends
bool operator!= (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
const TSequenceNumber operator+ (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
const TSequenceNumber operator+ (const TSequenceNumber &Lhs, SequenceType Rhs)
const TSequenceNumber operator- (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
const TSequenceNumber operator- (const TSequenceNumber &Lhs, SequenceType Rhs)
bool operator< (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
bool operator<= (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
bool operator== (const TSequenceNumber &Lhs, const TSequenceNumber &Rhs)
Equals, NOTE that sequence numbers wrap around so 0 == 0 + SequenceNumberCount.
Detailed Description
template<SIZE_T NumBits, typename SequenceType>
class TSequenceNumber< NumBits, SequenceType >
Helper class to work with sequence numbers.
Definition at line 12 of file SequenceNumber.h.
Member Typedef Documentation
DifferenceT
template<SIZE_T NumBits, typename SequenceType> using TSequenceNumber< NumBits, SequenceType >::DifferenceT = int32
Definition at line 18 of file SequenceNumber.h.
SequenceT
template<SIZE_T NumBits, typename SequenceType> using TSequenceNumber< NumBits, SequenceType >::SequenceT = SequenceType
Definition at line 17 of file SequenceNumber.h.
Member Enumeration Documentation
anonymous enum
template<SIZE_T NumBits, typename SequenceType> anonymous enum
Enumerator
SeqNumberMax
Definition at line 24 of file SequenceNumber.h.
anonymous enum
template<SIZE_T NumBits, typename SequenceType> anonymous enum
Enumerator
SeqNumberHalf
Definition at line 23 of file SequenceNumber.h.
anonymous enum
template<SIZE_T NumBits, typename SequenceType> anonymous enum
Enumerator
SeqNumberCount
Definition at line 22 of file SequenceNumber.h.
anonymous enum
template<SIZE_T NumBits, typename SequenceType> anonymous enum
Enumerator
SeqNumberMask
Definition at line 25 of file SequenceNumber.h.
anonymous enum
template<SIZE_T NumBits, typename SequenceType> anonymous enum
Enumerator
SeqNumberBits
Definition at line 21 of file SequenceNumber.h.
Constructor & Destructor Documentation
TSequenceNumber() [1/2]
template<SIZE_T NumBits, typename SequenceType> TSequenceNumber< NumBits, SequenceType >::TSequenceNumber () inline
Default constructor.
Definition at line 28 of file SequenceNumber.h.
Referenced by Diff(), TSequenceNumber< SequenceNumberBits, uint16 >::Increment(), TSequenceNumber< SequenceNumberBits, uint16 >::operator+, TSequenceNumber< SequenceNumberBits, uint16 >::operator+, TSequenceNumber< SequenceNumberBits, uint16 >::operator-, and TSequenceNumber< SequenceNumberBits, uint16 >::operator-.
TSequenceNumber() [2/2]
template<SIZE_T NumBits, typename SequenceType> TSequenceNumber< NumBits, SequenceType >::TSequenceNumber (SequenceT ValueIn) inline
Constructor with given value.
Definition at line 31 of file SequenceNumber.h.
Member Function Documentation
Diff()
template<SIZE_T NumBits, typename SequenceType> TSequenceNumber< NumBits, SequenceType >::DifferenceT TSequenceNumber< NumBits, SequenceType >::Diff (TSequenceNumber< NumBits, SequenceType > A, TSequenceNumber< NumBits, SequenceType > B) static
Diff between sequence numbers (A - B) only valid if (A - B) < SeqNumberHalf.
Definition at line 98 of file SequenceNumber.h.
References TSequenceNumber(), A, and B.
Get()
template<SIZE_T NumBits, typename SequenceType> SequenceT TSequenceNumber< NumBits, SequenceType >::Get () const inline
Get Current Value.
Definition at line 34 of file SequenceNumber.h.
Referenced by TSequenceNumber< SequenceNumberBits, uint16 >::operator!=, TSequenceNumber< SequenceNumberBits, uint16 >::operator+, TSequenceNumber< SequenceNumberBits, uint16 >::operator+, TSequenceNumber< SequenceNumberBits, uint16 >::operator-, TSequenceNumber< SequenceNumberBits, uint16 >::operator-, TSequenceNumber< SequenceNumberBits, uint16 >::operator==, FNetPacketNotify::ProcessReceivedAcks(), and FNetPacketNotify::Update().
Increment()
template<SIZE_T NumBits, typename SequenceType> void TSequenceNumber< NumBits, SequenceType >::Increment (SequenceT InValue) inline private
Definition at line 52 of file SequenceNumber.h.
Referenced by TSequenceNumber< SequenceNumberBits, uint16 >::operator++(), and TSequenceNumber< SequenceNumberBits, uint16 >::operator++().
operator++() [1/2]
template<SIZE_T NumBits, typename SequenceType> TSequenceNumber & TSequenceNumber< NumBits, SequenceType >::operator++ () inline
Pre-increment and wrap around.
Definition at line 46 of file SequenceNumber.h.
operator++() [2/2]
template<SIZE_T NumBits, typename SequenceType> TSequenceNumber TSequenceNumber< NumBits, SequenceType >::operator++ (int) inline
Post-increment and wrap around.
Definition at line 49 of file SequenceNumber.h.
operator>()
template<SIZE_T NumBits, typename SequenceType> bool TSequenceNumber< NumBits, SequenceType >::operator> (const TSequenceNumber< NumBits, SequenceType > & Other) const inline
return true if this is > Other, this is only considered to be the case if (A - B) < SeqNumberHalf since we have to be able to detect wraparounds
Definition at line 40 of file SequenceNumber.h.
operator>=()
template<SIZE_T NumBits, typename SequenceType> bool TSequenceNumber< NumBits, SequenceType >::operator>= (const TSequenceNumber< NumBits, SequenceType > & Other) const inline
Check if this is >= Other, See above.
Definition at line 43 of file SequenceNumber.h.
Friends And Related Symbol Documentation
operator!=
template<SIZE_T NumBits, typename SequenceType> bool operator!= (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Definition at line 71 of file SequenceNumber.h.
operator+ [1/2]
template<SIZE_T NumBits, typename SequenceType> const TSequenceNumber operator+ (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Definition at line 76 of file SequenceNumber.h.
operator+ [2/2]
template<SIZE_T NumBits, typename SequenceType> const TSequenceNumber operator+ (const TSequenceNumber< NumBits, SequenceType > & Lhs, SequenceType Rhs) friend
Definition at line 86 of file SequenceNumber.h.
operator- [1/2]
template<SIZE_T NumBits, typename SequenceType> const TSequenceNumber operator- (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Definition at line 81 of file SequenceNumber.h.
operator- [2/2]
template<SIZE_T NumBits, typename SequenceType> const TSequenceNumber operator- (const TSequenceNumber< NumBits, SequenceType > & Lhs, SequenceType Rhs) friend
Definition at line 91 of file SequenceNumber.h.
operator<
template<SIZE_T NumBits, typename SequenceType> bool operator< (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Definition at line 55 of file SequenceNumber.h.
operator<=
template<SIZE_T NumBits, typename SequenceType> bool operator<= (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Definition at line 60 of file SequenceNumber.h.
operator==
template<SIZE_T NumBits, typename SequenceType> bool operator== (const TSequenceNumber< NumBits, SequenceType > & Lhs, const TSequenceNumber< NumBits, SequenceType > & Rhs) friend
Equals, NOTE that sequence numbers wrap around so 0 == 0 + SequenceNumberCount.
Definition at line 66 of file SequenceNumber.h.
Field Documentation
Value
template<SIZE_T NumBits, typename SequenceType> SequenceT TSequenceNumber< NumBits, SequenceType >::Value private
Definition at line 53 of file SequenceNumber.h.
The documentation for this class was generated from the following file:
SequenceNumber.h