Unreal Engine 5.6 C++ API: UE::MemStack Namespace Reference
UE::MemStack Namespace Reference
Functions
template<typename T>
TArrayView< T > AllocateArrayView (FMemStackBase &Allocator, TArrayView< T > View)
const TCHAR * AllocateString (FMemStackBase &Allocator, const FStringBuilderBase &StringBuilder)
const TCHAR * AllocateString (FMemStackBase &Allocator, const TCHAR *String, int32 Length)
const TCHAR * AllocateString (FMemStackBase &Allocator, FStringView String)
template<typename FormatType, typename... ArgTypes>
const TCHAR * AllocateStringf (FMemStackBase &Allocator, const FormatType &Format, ArgTypes... Args)
FStringView AllocateStringView (FMemStackBase &Allocator, FStringView String)
template<typename FormatType, typename... ArgTypes>
FStringView AllocateStringViewf (FMemStackBase &Allocator, const FormatType &Format, ArgTypes... Args)
Function Documentation
AllocateArrayView()
template<typename T> TArrayView< T > UE::MemStack::AllocateArrayView (FMemStackBase & Allocator, TArrayView< T > View) inline
Definition at line 55 of file MemStackUtility.h.
References Allocator, MakeArrayView(), and TArrayView< InElementType, InSizeType >::Num().
AllocateString() [1/3]
const TCHAR * UE::MemStack::AllocateString (FMemStackBase & Allocator, const FStringBuilderBase & StringBuilder) inline
Definition at line 33 of file MemStackUtility.h.
References AllocateString(), Allocator, TStringBuilderBase< CharType >::GetData(), and TStringBuilderBase< CharType >::Len().
AllocateString() [2/3]
const TCHAR * UE::MemStack::AllocateString (FMemStackBase & Allocator, const TCHAR * String, int32 Length) inline
Definition at line 15 of file MemStackUtility.h.
References Allocator, FMemory::Memcpy(), and New().
Referenced by AllocateString(), AllocateString(), AllocateStringf(), and AllocateStringView().
AllocateString() [3/3]
const TCHAR * UE::MemStack::AllocateString (FMemStackBase & Allocator, FStringView String) inline
Definition at line 23 of file MemStackUtility.h.
References AllocateString(), and Allocator.
AllocateStringf()
template<typename FormatType, typename... ArgTypes> const TCHAR * UE::MemStack::AllocateStringf (FMemStackBase & Allocator, const FormatType & Format, ArgTypes... Args) inline
Definition at line 39 of file MemStackUtility.h.
References AllocateString(), Allocator, Format, and Forward().
AllocateStringView()
FStringView UE::MemStack::AllocateStringView (FMemStackBase & Allocator, FStringView String) inline
Definition at line 28 of file MemStackUtility.h.
References AllocateString(), and Allocator.
Referenced by AllocateStringViewf().
AllocateStringViewf()
template<typename FormatType, typename... ArgTypes> FStringView UE::MemStack::AllocateStringViewf (FMemStackBase & Allocator, const FormatType & Format, ArgTypes... Args) inline
Definition at line 47 of file MemStackUtility.h.
References AllocateStringView(), Allocator, Format, and Forward().