Unreal Engine 5.6 C++ API: FRegisterComponentContext Class Reference
FRegisterComponentContext Class Reference
#include "ActorComponent.h"
Public Types
using FPrimitiveBatch = TArray<UPrimitiveComponent*, FConcurrentLinearArrayAllocator>
Public Member Functions
FRegisterComponentContext (UWorld *InWorld)
~FRegisterComponentContext ()
void AddPrimitive (UPrimitiveComponent *PrimitiveComponent)
void AddSendRenderDynamicData (UPrimitiveComponent *PrimitiveComponent)
int32 GetIncrementalUpdateAddPrimitiveBatchSize () const
int32 GetIncrementalUpdateNumComponentsToUpdate () const
const UE::FTimeout & GetIncrementalUpdateTimeout () const
void Process ()
FRegisterComponentContext & SetAsyncRegisterLevelContext (FAsyncRegisterLevelContext *Value)
FRegisterComponentContext & SetIncrementalUpdateAddPrimitiveBatchSize (int32 Value)
FRegisterComponentContext & SetIncrementalUpdateNumComponentsToUpdate (int32 Value)
FRegisterComponentContext & SetIncrementalUpdateTimeout (const UE::FTimeout &InTimeout)
UE_DEPRECATED (5.5, "This function is not used anymore") int32 Count() const
Static Public Member Functions
static void SendRenderDynamicData (FRegisterComponentContext *Context, UPrimitiveComponent *PrimitiveComponent)
Private Member Functions
bool OnIncrementalRegisterComponentsDone ()
Private Attributes
FPrimitiveBatch AddPrimitiveBatches
FAsyncRegisterLevelContext * AsyncRegisterLevelContext
int32 IncrementalUpdateAddPrimitiveBatchSize
int32 IncrementalUpdateNumComponentsToUpdate
FPrimitiveBatch SendRenderDynamicDataPrimitives
UE::FTimeout Timeout
UWorld * World
Friends
class ULevel
Detailed Description
Definition at line 40 of file ActorComponent.h.
Member Typedef Documentation
FPrimitiveBatch
using FRegisterComponentContext::FPrimitiveBatch = TArray<UPrimitiveComponent*, FConcurrentLinearArrayAllocator>
Definition at line 43 of file ActorComponent.h.
Constructor & Destructor Documentation
FRegisterComponentContext()
FRegisterComponentContext::FRegisterComponentContext (UWorld * InWorld)
Referenced by SendRenderDynamicData(), SetAsyncRegisterLevelContext(), SetIncrementalUpdateAddPrimitiveBatchSize(), SetIncrementalUpdateNumComponentsToUpdate(), and SetIncrementalUpdateTimeout().
~FRegisterComponentContext()
FRegisterComponentContext::~FRegisterComponentContext ()
Member Function Documentation
AddPrimitive()
void FRegisterComponentContext::AddPrimitive (UPrimitiveComponent * PrimitiveComponent)
AddSendRenderDynamicData()
void FRegisterComponentContext::AddSendRenderDynamicData (UPrimitiveComponent * PrimitiveComponent)
GetIncrementalUpdateAddPrimitiveBatchSize()
int32 FRegisterComponentContext::GetIncrementalUpdateAddPrimitiveBatchSize () const inline
Definition at line 54 of file ActorComponent.h.
References IncrementalUpdateAddPrimitiveBatchSize.
GetIncrementalUpdateNumComponentsToUpdate()
int32 FRegisterComponentContext::GetIncrementalUpdateNumComponentsToUpdate () const inline
Definition at line 55 of file ActorComponent.h.
References IncrementalUpdateNumComponentsToUpdate.
GetIncrementalUpdateTimeout()
const UE::FTimeout & FRegisterComponentContext::GetIncrementalUpdateTimeout () const inline
Definition at line 53 of file ActorComponent.h.
References Timeout.
OnIncrementalRegisterComponentsDone()
bool FRegisterComponentContext::OnIncrementalRegisterComponentsDone () private
Process()
void FRegisterComponentContext::Process ()
SendRenderDynamicData()
void FRegisterComponentContext::SendRenderDynamicData (FRegisterComponentContext * Context, UPrimitiveComponent * PrimitiveComponent) static
References FRegisterComponentContext().
SetAsyncRegisterLevelContext()
FRegisterComponentContext & FRegisterComponentContext::SetAsyncRegisterLevelContext (FAsyncRegisterLevelContext * Value)
References FRegisterComponentContext(), and Value.
SetIncrementalUpdateAddPrimitiveBatchSize()
FRegisterComponentContext & FRegisterComponentContext::SetIncrementalUpdateAddPrimitiveBatchSize (int32 Value)
References FRegisterComponentContext(), and Value.
SetIncrementalUpdateNumComponentsToUpdate()
FRegisterComponentContext & FRegisterComponentContext::SetIncrementalUpdateNumComponentsToUpdate (int32 Value)
References FRegisterComponentContext(), and Value.
SetIncrementalUpdateTimeout()
FRegisterComponentContext & FRegisterComponentContext::SetIncrementalUpdateTimeout (const UE::FTimeout & InTimeout)
References FRegisterComponentContext().
UE_DEPRECATED()
FRegisterComponentContext::UE_DEPRECATED (5. 5, "This function is not used anymore") const inline
Definition at line 62 of file ActorComponent.h.
References AddPrimitiveBatches, and Count.
Friends And Related Symbol Documentation
ULevel
friend class ULevel friend
Definition at line 79 of file ActorComponent.h.
References ULevel.
Referenced by ULevel.
Field Documentation
AddPrimitiveBatches
FPrimitiveBatch FRegisterComponentContext::AddPrimitiveBatches private
Definition at line 76 of file ActorComponent.h.
Referenced by UE_DEPRECATED().
AsyncRegisterLevelContext
FAsyncRegisterLevelContext* FRegisterComponentContext::AsyncRegisterLevelContext private
Definition at line 74 of file ActorComponent.h.
IncrementalUpdateAddPrimitiveBatchSize
int32 FRegisterComponentContext::IncrementalUpdateAddPrimitiveBatchSize private
Definition at line 72 of file ActorComponent.h.
Referenced by GetIncrementalUpdateAddPrimitiveBatchSize().
IncrementalUpdateNumComponentsToUpdate
int32 FRegisterComponentContext::IncrementalUpdateNumComponentsToUpdate private
Definition at line 73 of file ActorComponent.h.
Referenced by GetIncrementalUpdateNumComponentsToUpdate().
SendRenderDynamicDataPrimitives
FPrimitiveBatch FRegisterComponentContext::SendRenderDynamicDataPrimitives private
Definition at line 77 of file ActorComponent.h.
Timeout
UE::FTimeout FRegisterComponentContext::Timeout private
Definition at line 71 of file ActorComponent.h.
Referenced by GetIncrementalUpdateTimeout().
World
UWorld* FRegisterComponentContext::World private
Definition at line 70 of file ActorComponent.h.
The documentation for this class was generated from the following file:
ActorComponent.h