Unreal Engine 5.6 C++ API: TPtrTableBase< T, PtrType > Class Template Reference
TPtrTableBase< T, PtrType > Class Template Reference
#include "MemoryImage.h"
Public Member Functions
uint32 AddIndexedPointer (T *Ptr)
void AddPatchedPointer (T *Ptr, uint64 Offset)
void ApplyPointerPatches (void *FrozenBase) const
TArray< PtrType >::RangedForIteratorType begin ()
TArray< PtrType >::RangedForConstIteratorType begin () const
void Empty (int32 NewSize=0)
TArray< PtrType >::RangedForIteratorType end ()
TArray< PtrType >::RangedForConstIteratorType end () const
T * GetIndexedPointer (uint32 i) const
void LoadIndexedPointer (T *Ptr)
uint32 Num () const
bool TryAddIndexedPtr (const FTypeLayoutDesc &TypeDesc, void *Ptr, int32 &OutIndex)
bool TryGetIndexedPtr (const FTypeLayoutDesc &TypeDesc, uint32 i, void *&OutPtr) const
Public Member Functions inherited from FPtrTableBase
void SavePatchesToArchive (FArchive &Ar, uint32 PtrIndex) const
Static Public Member Functions
static const FTypeLayoutDesc & StaticGetPtrTypeLayoutDesc ()
Static Public Member Functions inherited from FPtrTableBase
template<typename PtrType>
static void LoadAndApplyPatchesFromArchive (FArchive &Ar, void *FrozenBase, const PtrType &Ptr)
Private Attributes
TArray< PtrType > Pointers
Additional Inherited Members
Protected Member Functions inherited from FPtrTableBase
void AddPatchedPointerBase (uint32 PtrIndex, uint64 Offset)
Protected Attributes inherited from FPtrTableBase
TArray< FPatchOffsetList > PatchLists
TArray< FPatchOffset > PatchOffsets
Detailed Description
template<typename T, typename PtrType>
class TPtrTableBase< T, PtrType >
Definition at line 960 of file MemoryImage.h.
Member Function Documentation
AddIndexedPointer()
template<typename T, typename PtrType> uint32 TPtrTableBase< T, PtrType >::AddIndexedPointer (T * Ptr) inline
Definition at line 971 of file MemoryImage.h.
Referenced by TPtrTableBase< T, TRefCountPtr< T > >::AddPatchedPointer(), and TPtrTableBase< T, TRefCountPtr< T > >::TryAddIndexedPtr().
AddPatchedPointer()
template<typename T, typename PtrType> void TPtrTableBase< T, PtrType >::AddPatchedPointer (T * Ptr, uint64 Offset) inline
Definition at line 998 of file MemoryImage.h.
ApplyPointerPatches()
template<typename T, typename PtrType> void TPtrTableBase< T, PtrType >::ApplyPointerPatches (void * FrozenBase) const inline
Definition at line 1016 of file MemoryImage.h.
begin() [1/2]
template<typename T, typename PtrType> TArray< PtrType >::RangedForIteratorType TPtrTableBase< T, PtrType >::begin () inline
Definition at line 1030 of file MemoryImage.h.
begin() [2/2]
template<typename T, typename PtrType> TArray< PtrType >::RangedForConstIteratorType TPtrTableBase< T, PtrType >::begin () const inline
Definition at line 1032 of file MemoryImage.h.
Empty()
template<typename T, typename PtrType> void TPtrTableBase< T, PtrType >::Empty (int32 NewSize = 0) inline
Definition at line 965 of file MemoryImage.h.
end() [1/2]
template<typename T, typename PtrType> TArray< PtrType >::RangedForIteratorType TPtrTableBase< T, PtrType >::end () inline
Definition at line 1031 of file MemoryImage.h.
end() [2/2]
template<typename T, typename PtrType> TArray< PtrType >::RangedForConstIteratorType TPtrTableBase< T, PtrType >::end () const inline
Definition at line 1033 of file MemoryImage.h.
GetIndexedPointer()
template<typename T, typename PtrType> T * TPtrTableBase< T, PtrType >::GetIndexedPointer (uint32 i) const inline
Definition at line 1004 of file MemoryImage.h.
Referenced by TIndexedPtrBase< T, T * >::Get(), and TPtrTableBase< T, TRefCountPtr< T > >::TryGetIndexedPtr().
LoadIndexedPointer()
template<typename T, typename PtrType> void TPtrTableBase< T, PtrType >::LoadIndexedPointer (T * Ptr) inline
Definition at line 983 of file MemoryImage.h.
Num()
template<typename T, typename PtrType> uint32 TPtrTableBase< T, PtrType >::Num () const inline
Definition at line 970 of file MemoryImage.h.
StaticGetPtrTypeLayoutDesc()
template<typename T, typename PtrType> const FTypeLayoutDesc & TPtrTableBase< T, PtrType >::StaticGetPtrTypeLayoutDesc () inline static
Definition at line 1168 of file MemoryImage.h.
References StaticGetTypeLayoutDesc().
Referenced by TPtrTableBase< T, TRefCountPtr< T > >::TryAddIndexedPtr(), and TPtrTableBase< T, TRefCountPtr< T > >::TryGetIndexedPtr().
TryAddIndexedPtr()
template<typename T, typename PtrType> bool TPtrTableBase< T, PtrType >::TryAddIndexedPtr (const FTypeLayoutDesc & TypeDesc, void * Ptr, int32 & OutIndex) inline
Definition at line 973 of file MemoryImage.h.
TryGetIndexedPtr()
template<typename T, typename PtrType> bool TPtrTableBase< T, PtrType >::TryGetIndexedPtr (const FTypeLayoutDesc & TypeDesc, uint32 i, void *& OutPtr) const inline
Definition at line 1006 of file MemoryImage.h.
Field Documentation
Pointers
template<typename T, typename PtrType> TArray<PtrType> TPtrTableBase< T, PtrType >::Pointers private
Definition at line 1035 of file MemoryImage.h.
The documentation for this class was generated from the following file:
MemoryImage.h