Unreal Engine 5.6 C++ API: IWaterBrushActorInterface Class Reference
IWaterBrushActorInterface Class Reference abstract
Dummy class needed to support Cast<IWaterBrushActorInterface>(Object).
#include "WaterBrushActorInterface.h"
Data Structures
struct FWaterBrushActorChangedEventParams
Struct indicating what type of change occurrend on the water brush actor.
Private Member Functions
virtual bool AffectsWaterMesh () const =0
Returns true if this water actor is currently affecting (i.e.
void BroadcastWaterBrushActorChangedEvent (const FWaterBrushActorChangedEventParams &InParams)
virtual bool CanEverAffectWaterInfo () const =0
Returns true if this water actor could potentially be affecting the water info texture of an AWaterZone actor:
virtual bool CanEverAffectWaterMesh () const =0
Returns true if this water actor could potentially be affecting (i.e.
DECLARE_EVENT_OneParam (IWaterBrushActorInterface, FWaterBrushActorChangedEvent, const FWaterBrushActorChangedEventParams &)
Event sent whenever a data change occurs on a water brush actor.
GENERATED_IINTERFACE_BODY () virtual bool AffectsLandscape() const =0
Returns true if this water actor is currently setup to modify the landscape :
virtual WATER_API TArray< UPrimitiveComponent * > GetBrushRenderableComponents () const
Returns an ordered list of components to render in the actor brush render pass (e.g.
virtual void GetBrushRenderDependencies (TSet< UObject * > &OutDependencies) const =0
Returns the list of objects this actor depends on to render its brush (textures, materials...)
virtual ETextureRenderTargetFormat GetBrushRenderTargetFormat () const =0
Returns the format of the render target used to render this actor in the water brush.
virtual const TMap< FName, FWaterBodyWeightmapSettings > & GetLayerWeightmapSettings () const =0
Returns the landscape weightmap settings, per layer, for this water actor.
virtual const FWaterCurveSettings & GetWaterCurveSettings () const =0
Returns the curve settings for this water actor.
virtual const FWaterBodyHeightmapSettings & GetWaterHeightmapSettings () const =0
Returns the landscape heightmap settings for this water actor.
Static Private Member Functions
static WATER_API FWaterBrushActorChangedEvent & GetOnWaterBrushActorChangedEvent ()
Detailed Description
Dummy class needed to support Cast<IWaterBrushActorInterface>(Object).
Interface implemented by actors which can affect the water brush
Definition at line 26 of file WaterBrushActorInterface.h.
Member Function Documentation
AffectsWaterMesh()
virtual bool IWaterBrushActorInterface::AffectsWaterMesh () const private pure virtual
Returns true if this water actor is currently affecting (i.e.
being rendered by) a AWaterZone actor :
References AffectsWaterMesh().
Referenced by AffectsWaterMesh().
BroadcastWaterBrushActorChangedEvent()
void IWaterBrushActorInterface::BroadcastWaterBrushActorChangedEvent (const FWaterBrushActorChangedEventParams & InParams) inline private
Definition at line 113 of file WaterBrushActorInterface.h.
References Event, GetOnWaterBrushActorChangedEvent(), and GIsEditor.
CanEverAffectWaterInfo()
virtual bool IWaterBrushActorInterface::CanEverAffectWaterInfo () const private pure virtual
Returns true if this water actor could potentially be affecting the water info texture of an AWaterZone actor:
References CanEverAffectWaterInfo().
Referenced by CanEverAffectWaterInfo().
CanEverAffectWaterMesh()
virtual bool IWaterBrushActorInterface::CanEverAffectWaterMesh () const private pure virtual
Returns true if this water actor could potentially be affecting (i.e.
being rendered by) a AWaterZone actor :
References CanEverAffectWaterMesh().
Referenced by CanEverAffectWaterMesh().
DECLARE_EVENT_OneParam()
IWaterBrushActorInterface::DECLARE_EVENT_OneParam (IWaterBrushActorInterface , FWaterBrushActorChangedEvent , const FWaterBrushActorChangedEventParams &) private
Event sent whenever a data change occurs on a water brush actor.
GENERATED_IINTERFACE_BODY()
IWaterBrushActorInterface::GENERATED_IINTERFACE_BODY () const private pure virtual
Returns true if this water actor is currently setup to modify the landscape :
GetBrushRenderableComponents()
virtual WATER_API TArray< UPrimitiveComponent * > IWaterBrushActorInterface::GetBrushRenderableComponents () const private virtual
Returns an ordered list of components to render in the actor brush render pass (e.g.
USplineMeshComponents for rivers)
References UE_API.
GetBrushRenderDependencies()
virtual void IWaterBrushActorInterface::GetBrushRenderDependencies (TSet< UObject * > & OutDependencies) const private pure virtual
Returns the list of objects this actor depends on to render its brush (textures, materials...)
GetBrushRenderTargetFormat()
virtual ETextureRenderTargetFormat IWaterBrushActorInterface::GetBrushRenderTargetFormat () const private pure virtual
Returns the format of the render target used to render this actor in the water brush.
GetLayerWeightmapSettings()
virtual const TMap< FName, FWaterBodyWeightmapSettings > & IWaterBrushActorInterface::GetLayerWeightmapSettings () const private pure virtual
Returns the landscape weightmap settings, per layer, for this water actor.
GetOnWaterBrushActorChangedEvent()
WATER_API FWaterBrushActorChangedEvent & IWaterBrushActorInterface::GetOnWaterBrushActorChangedEvent () static private
References UE_API.
Referenced by BroadcastWaterBrushActorChangedEvent().
GetWaterCurveSettings()
virtual const FWaterCurveSettings & IWaterBrushActorInterface::GetWaterCurveSettings () const private pure virtual
Returns the curve settings for this water actor.
GetWaterHeightmapSettings()
virtual const FWaterBodyHeightmapSettings & IWaterBrushActorInterface::GetWaterHeightmapSettings () const private pure virtual
Returns the landscape heightmap settings for this water actor.
The documentation for this class was generated from the following file:
WaterBrushActorInterface.h