Unreal Engine 5.6 C++ API: FShaderCodeArchive Class Reference
FShaderCodeArchive Class Reference
#include "ShaderCodeArchive.h"
Data Structures
struct FShaderPreloadEntry
Public Member Functions
virtual ~FShaderCodeArchive ()
virtual TRefCountPtr< FRHIShader > CreateShader (int32 Index, bool bRequired=true) override
virtual int32 FindShaderIndex (const FSHAHash &Hash) override
virtual int32 FindShaderMapIndex (const FSHAHash &Hash) override
virtual void GetAllShaderIndices (int32 ShaderMapIndex, TArray< int32 > &ShaderIndices)
virtual int32 GetNumShaderMaps () const override
virtual int32 GetNumShaders () const override
virtual int32 GetNumShadersForShaderMap (int32 ShaderMapIndex) const override
virtual FSHAHash GetShaderHash (int32 ShaderMapIndex, int32 ShaderIndex) override
virtual int32 GetShaderIndex (int32 ShaderMapIndex, int32 i) const override
virtual uint32 GetSizeBytes () const override
virtual bool IsNativeLibrary () const override
void OnShaderPreloadFinished (int32 ShaderIndex, const IMemoryReadStreamRef &PreloadData)
virtual bool PreloadShader (int32 ShaderIndex, FGraphEventArray &OutCompletionEvents) override
virtual bool PreloadShaderMap (int32 ShaderMapIndex, FGraphEventArray &OutCompletionEvents) override
virtual void ReleasePreloadedShader (int32 ShaderIndex) override
virtual void Teardown () override
Static Public Member Functions
static FShaderCodeArchive * Create (EShaderPlatform InPlatform, FArchive &Ar, const FString &InDestFilePath, const FString &InLibraryDir, const FString &InLibraryName)
Protected Member Functions
FShaderCodeArchive (EShaderPlatform InPlatform, const FString &InLibraryDir, const FString &InLibraryName)
void CheckShaderCreation (void *ShaderPtr, int32 Index)
bool WaitForPreload (FShaderPreloadEntry &ShaderPreloadEntry)
Protected Attributes
FShaderUsageVisualizer DebugVisualizer
debug visualizer - in Shipping compiles out to an empty struct with no-op functions
IFileCacheHandle * FileCacheHandle
int64 LibraryCodeOffset
FString LibraryDir
FSerializedShaderArchive SerializedShaders
FRWLock ShaderPreloadLock
TArray< FShaderPreloadEntry > ShaderPreloads
Detailed Description
Definition at line 379 of file ShaderCodeArchive.h.
Constructor & Destructor Documentation
~FShaderCodeArchive()
virtual FShaderCodeArchive::~FShaderCodeArchive () virtual
FShaderCodeArchive()
FShaderCodeArchive::FShaderCodeArchive (EShaderPlatform InPlatform, const FString & InLibraryDir, const FString & InLibraryName) protected
Referenced by Create().
Member Function Documentation
CheckShaderCreation()
void FShaderCodeArchive::CheckShaderCreation (void * ShaderPtr, int32 Index) inline protected
Definition at line 443 of file ShaderCodeArchive.h.
References FORCENOINLINE.
Create()
FShaderCodeArchive * FShaderCodeArchive::Create (EShaderPlatform InPlatform, FArchive & Ar, const FString & InDestFilePath, const FString & InLibraryDir, const FString & InLibraryName) static
References FShaderCodeArchive(), and Ar.
CreateShader()
virtual TRefCountPtr< FRHIShader > FShaderCodeArchive::CreateShader (int32 Index, bool bRequired = true) override virtual
FindShaderIndex()
virtual int32 FShaderCodeArchive::FindShaderIndex (const FSHAHash & Hash) inline override virtual
Definition at line 419 of file ShaderCodeArchive.h.
References Hash, and SerializedShaders.
FindShaderMapIndex()
virtual int32 FShaderCodeArchive::FindShaderMapIndex (const FSHAHash & Hash) inline override virtual
Definition at line 414 of file ShaderCodeArchive.h.
References Hash, and SerializedShaders.
GetAllShaderIndices()
virtual void FShaderCodeArchive::GetAllShaderIndices (int32 ShaderMapIndex, TArray< int32 > & ShaderIndices) inline virtual
Definition at line 405 of file ShaderCodeArchive.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), FShaderMapEntry::NumShaders, SerializedShaders, and FShaderMapEntry::ShaderIndicesOffset.
GetNumShaderMaps()
virtual int32 FShaderCodeArchive::GetNumShaderMaps () const inline override virtual
Definition at line 396 of file ShaderCodeArchive.h.
References SerializedShaders.
GetNumShaders()
virtual int32 FShaderCodeArchive::GetNumShaders () const inline override virtual
Definition at line 395 of file ShaderCodeArchive.h.
References SerializedShaders.
GetNumShadersForShaderMap()
virtual int32 FShaderCodeArchive::GetNumShadersForShaderMap (int32 ShaderMapIndex) const inline override virtual
Definition at line 397 of file ShaderCodeArchive.h.
References SerializedShaders.
GetShaderHash()
virtual FSHAHash FShaderCodeArchive::GetShaderHash (int32 ShaderMapIndex, int32 ShaderIndex) inline override virtual
Definition at line 424 of file ShaderCodeArchive.h.
References GetShaderIndex(), and SerializedShaders.
GetShaderIndex()
virtual int32 FShaderCodeArchive::GetShaderIndex (int32 ShaderMapIndex, int32 i) const inline override virtual
Definition at line 399 of file ShaderCodeArchive.h.
References SerializedShaders, and FShaderMapEntry::ShaderIndicesOffset.
Referenced by GetShaderHash().
GetSizeBytes()
virtual uint32 FShaderCodeArchive::GetSizeBytes () const inline override virtual
Definition at line 388 of file ShaderCodeArchive.h.
References SerializedShaders, and ShaderPreloads.
IsNativeLibrary()
virtual bool FShaderCodeArchive::IsNativeLibrary () const inline override virtual
Definition at line 386 of file ShaderCodeArchive.h.
OnShaderPreloadFinished()
void FShaderCodeArchive::OnShaderPreloadFinished (int32 ShaderIndex, const IMemoryReadStreamRef & PreloadData)
PreloadShader()
virtual bool FShaderCodeArchive::PreloadShader (int32 ShaderIndex, FGraphEventArray & OutCompletionEvents) override virtual
PreloadShaderMap()
virtual bool FShaderCodeArchive::PreloadShaderMap (int32 ShaderMapIndex, FGraphEventArray & OutCompletionEvents) override virtual
ReleasePreloadedShader()
virtual void FShaderCodeArchive::ReleasePreloadedShader (int32 ShaderIndex) override virtual
Teardown()
virtual void FShaderCodeArchive::Teardown () override virtual
WaitForPreload()
bool FShaderCodeArchive::WaitForPreload (FShaderPreloadEntry & ShaderPreloadEntry) protected
Field Documentation
DebugVisualizer
FShaderUsageVisualizer FShaderCodeArchive::DebugVisualizer protected
debug visualizer - in Shipping compiles out to an empty struct with no-op functions
Definition at line 480 of file ShaderCodeArchive.h.
FileCacheHandle
IFileCacheHandle* FShaderCodeArchive::FileCacheHandle protected
Definition at line 471 of file ShaderCodeArchive.h.
LibraryCodeOffset
int64 FShaderCodeArchive::LibraryCodeOffset protected
Definition at line 468 of file ShaderCodeArchive.h.
LibraryDir
FString FShaderCodeArchive::LibraryDir protected
Definition at line 465 of file ShaderCodeArchive.h.
SerializedShaders
FSerializedShaderArchive FShaderCodeArchive::SerializedShaders protected
Definition at line 474 of file ShaderCodeArchive.h.
Referenced by FindShaderIndex(), FindShaderMapIndex(), GetAllShaderIndices(), GetNumShaderMaps(), GetNumShaders(), GetNumShadersForShaderMap(), GetShaderHash(), GetShaderIndex(), and GetSizeBytes().
ShaderPreloadLock
FRWLock FShaderCodeArchive::ShaderPreloadLock protected
Definition at line 477 of file ShaderCodeArchive.h.
ShaderPreloads
TArray<FShaderPreloadEntry> FShaderCodeArchive::ShaderPreloads protected
Definition at line 476 of file ShaderCodeArchive.h.
Referenced by GetSizeBytes().
The documentation for this class was generated from the following file:
ShaderCodeArchive.h