Unreal Engine 5.6 C++ API: UE::FSourceLocation::FSourceLocationImpl Struct Reference
UE::FSourceLocation::FSourceLocationImpl Struct Reference
Public Member Functions
constexpr FSourceLocationImpl () noexcept=default
constexpr uint_least32_t column () const noexcept
constexpr const char * file_name () const noexcept
constexpr const char * function_name () const noexcept
constexpr uint_least32_t line () const noexcept
Static Public Member Functions
static UE_CONSTEVAL FSourceLocationImpl current (const uint_least32_t InLine=__builtin_LINE(), const uint_least32_t InColumn=__builtin_COLUMN(), const char *const InFile=__builtin_FILE(), const char *const InFunction=__builtin_FUNCTION()) noexcept
Private Attributes
uint_least32_t Column = 0
const char * FileName = nullptr
const char * FunctionName = nullptr
uint_least32_t Line = 0
Detailed Description
Definition at line 26 of file SourceLocation.h.
Constructor & Destructor Documentation
FSourceLocationImpl()
UE::FSourceLocation::FSourceLocationImpl::FSourceLocationImpl () constexpr default noexcept
Referenced by current().
Member Function Documentation
column()
uint_least32_t UE::FSourceLocation::FSourceLocationImpl::column () const inline constexpr noexcept
Definition at line 49 of file SourceLocation.h.
References Column.
current()
UE_CONSTEVAL FSourceLocationImpl UE::FSourceLocation::FSourceLocationImpl::current (const uint_least32_t InLine = __builtin_LINE(), const uint_least32_t InColumn = __builtin_COLUMN(), const char *const InFile = __builtin_FILE(), const char *const InFunction = __builtin_FUNCTION()) inline static noexcept
Definition at line 28 of file SourceLocation.h.
References FSourceLocationImpl(), Location, and UE_CONSTEVAL.
Referenced by UE::FSourceLocation::Current().
file_name()
const char * UE::FSourceLocation::FSourceLocationImpl::file_name () const inline constexpr noexcept
Definition at line 53 of file SourceLocation.h.
References FileName.
function_name()
const char * UE::FSourceLocation::FSourceLocationImpl::function_name () const inline constexpr noexcept
Definition at line 57 of file SourceLocation.h.
References FunctionName.
line()
uint_least32_t UE::FSourceLocation::FSourceLocationImpl::line () const inline constexpr noexcept
Definition at line 45 of file SourceLocation.h.
References Line, and line().
Referenced by line().
Field Documentation
Column
uint_least32_t UE::FSourceLocation::FSourceLocationImpl::Column = 0 private
Definition at line 64 of file SourceLocation.h.
Referenced by column().
FileName
const char* UE::FSourceLocation::FSourceLocationImpl::FileName = nullptr private
Definition at line 65 of file SourceLocation.h.
Referenced by file_name().
FunctionName
const char* UE::FSourceLocation::FSourceLocationImpl::FunctionName = nullptr private
Definition at line 66 of file SourceLocation.h.
Referenced by function_name().
Line
uint_least32_t UE::FSourceLocation::FSourceLocationImpl::Line = 0 private
Definition at line 63 of file SourceLocation.h.
Referenced by line().
The documentation for this struct was generated from the following file:
SourceLocation.h