Unreal Engine 5.6 C++ API: FAnimNodeTracker Struct Reference
FAnimNodeTracker Struct Reference
DEPRECATED - This system is now supplanted by UE::Anim::FMessageStack Utility container for tracking a stack of ancestor nodes by node type during graph traversal This is not an exhaustive list of all visited ancestors.
#include "AnimNodeBase.h"
Public Types
using FKey = FObjectKey
using FMap = TMap<FKey, FNodeStack, TInlineSetAllocator<4>>
using FNodeStack = TArray<FAnimNode_Base*, TInlineAllocator<4>>
Public Member Functions
void CopyTopsOnly (const FAnimNodeTracker &Source)
template<typename NodeType>
NodeType * Pop ()
FAnimNode_Base * Pop (FKey Key)
template<typename NodeType>
FKey Push (NodeType *Node)
template<typename NodeType>
NodeType * Top () const
Static Public Member Functions
template<typename NodeType>
static FKey GetKey ()
Data Fields
FMap Map
Detailed Description
DEPRECATED - This system is now supplanted by UE::Anim::FMessageStack Utility container for tracking a stack of ancestor nodes by node type during graph traversal This is not an exhaustive list of all visited ancestors.
During Update nodes must call FAnimationUpdateContext::TrackAncestor() to appear in the tracker.
Definition at line 45 of file AnimNodeBase.h.
Member Typedef Documentation
FKey
using FAnimNodeTracker::FKey = FObjectKey
Definition at line 47 of file AnimNodeBase.h.
FMap
using FAnimNodeTracker::FMap = TMap<FKey, FNodeStack, TInlineSetAllocator<4>>
Definition at line 49 of file AnimNodeBase.h.
FNodeStack
using FAnimNodeTracker::FNodeStack = TArray<FAnimNode_Base*, TInlineAllocator<4>>
Definition at line 48 of file AnimNodeBase.h.
Member Function Documentation
CopyTopsOnly()
void FAnimNodeTracker::CopyTopsOnly (const FAnimNodeTracker & Source) inline
Definition at line 88 of file AnimNodeBase.h.
References Map, TArray< InElementType, InAllocatorType >::Push(), and Source.
Referenced by FAnimationUpdateSharedContext::CopyForCachedUpdate().
GetKey()
template<typename NodeType> FKey FAnimNodeTracker::GetKey () inline static
Definition at line 54 of file AnimNodeBase.h.
Referenced by Pop(), Push(), and Top().
Pop() [1/2]
template<typename NodeType> NodeType * FAnimNodeTracker::Pop () inline
Definition at line 69 of file AnimNodeBase.h.
References GetKey(), Map, and TArray< InElementType, InAllocatorType >::Pop().
Pop() [2/2]
FAnimNode_Base * FAnimNodeTracker::Pop (FKey Key) inline
Definition at line 75 of file AnimNodeBase.h.
References Key, Map, and TArray< InElementType, InAllocatorType >::Pop().
Push()
template<typename NodeType> FKey FAnimNodeTracker::Push (NodeType * Node) inline
Definition at line 60 of file AnimNodeBase.h.
References GetKey(), Key, Map, and TArray< InElementType, InAllocatorType >::Push().
Top()
template<typename NodeType> NodeType * FAnimNodeTracker::Top () const inline
Definition at line 82 of file AnimNodeBase.h.
References GetKey(), Map, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Top().
Field Documentation
Map
FMap FAnimNodeTracker::Map
Definition at line 51 of file AnimNodeBase.h.
Referenced by CopyTopsOnly(), Pop(), Pop(), Push(), and Top().
The documentation for this struct was generated from the following file:
AnimNodeBase.h