Unreal Engine 5.6 C++ API: FCompactPoseBoneIndexIterator Struct Reference
FCompactPoseBoneIndexIterator Struct Reference
Iterator for compact pose indices.
#include "BoneContainer.h"
Public Member Functions
FCompactPoseBoneIndexIterator (int32 InIndex)
bool operator!= (FCompactPoseBoneIndexIterator &Rhs)
FCompactPoseBoneIndex operator* () const
FCompactPoseBoneIndexIterator & operator++ ()
bool operator== (FCompactPoseBoneIndexIterator &Rhs)
Data Fields
int32 Index
Detailed Description
Iterator for compact pose indices.
Definition at line 139 of file BoneContainer.h.
Constructor & Destructor Documentation
FCompactPoseBoneIndexIterator()
FCompactPoseBoneIndexIterator::FCompactPoseBoneIndexIterator (int32 InIndex) inline
Definition at line 143 of file BoneContainer.h.
References Index.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
bool FCompactPoseBoneIndexIterator::operator!= (FCompactPoseBoneIndexIterator & Rhs) inline
Definition at line 147 of file BoneContainer.h.
References FCompactPoseBoneIndexIterator(), and Index.
operator*()
FCompactPoseBoneIndex FCompactPoseBoneIndexIterator::operator* () const inline
Definition at line 148 of file BoneContainer.h.
References Index.
operator++()
FCompactPoseBoneIndexIterator & FCompactPoseBoneIndexIterator::operator++ () inline
Definition at line 145 of file BoneContainer.h.
References FCompactPoseBoneIndexIterator(), and Index.
operator==()
bool FCompactPoseBoneIndexIterator::operator== (FCompactPoseBoneIndexIterator & Rhs) inline
Definition at line 146 of file BoneContainer.h.
References FCompactPoseBoneIndexIterator(), and Index.
Field Documentation
Index
int32 FCompactPoseBoneIndexIterator::Index
Definition at line 141 of file BoneContainer.h.
Referenced by FCompactPoseBoneIndexIterator(), operator!=(), operator*(), operator++(), and operator==().
The documentation for this struct was generated from the following file:
BoneContainer.h