Unreal Engine 5.6 C++ API: Audio::FQuartzLatencyTimer Class Reference
Audio::FQuartzLatencyTimer Class Reference
#include "QuartzQuantizationUtilities.h"
Public Member Functions
FQuartzLatencyTimer ()
double GetCurrentTimePassedMs ()
double GetResultsMilliseconds ()
bool HasTimerRun ()
bool HasTimerStarted ()
bool HasTimerStopped ()
bool IsTimerRunning ()
void ResetTimer ()
void StartTimer ()
void StopTimer ()
Private Attributes
int64 JourneyEndCycles
int64 JourneyStartCycles
Detailed Description
Definition at line 340 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
FQuartzLatencyTimer()
Audio::FQuartzLatencyTimer::FQuartzLatencyTimer ()
Definition at line 669 of file QuartzQuantizationUtilities.cpp.
References JourneyEndCycles, and JourneyStartCycles.
Member Function Documentation
GetCurrentTimePassedMs()
double Audio::FQuartzLatencyTimer::GetCurrentTimePassedMs ()
Definition at line 692 of file QuartzQuantizationUtilities.cpp.
References FAndroidTime::Cycles64(), IsTimerRunning(), JourneyStartCycles, and FGenericPlatformTime::ToMilliseconds64().
GetResultsMilliseconds()
double Audio::FQuartzLatencyTimer::GetResultsMilliseconds ()
Definition at line 702 of file QuartzQuantizationUtilities.cpp.
References HasTimerRun(), JourneyEndCycles, JourneyStartCycles, and FGenericPlatformTime::ToMilliseconds64().
HasTimerRun()
bool Audio::FQuartzLatencyTimer::HasTimerRun ()
Definition at line 727 of file QuartzQuantizationUtilities.cpp.
References HasTimerStarted(), and HasTimerStopped().
Referenced by GetResultsMilliseconds().
HasTimerStarted()
bool Audio::FQuartzLatencyTimer::HasTimerStarted ()
Definition at line 712 of file QuartzQuantizationUtilities.cpp.
References JourneyStartCycles.
Referenced by HasTimerRun(), and IsTimerRunning().
HasTimerStopped()
bool Audio::FQuartzLatencyTimer::HasTimerStopped ()
Definition at line 717 of file QuartzQuantizationUtilities.cpp.
References JourneyEndCycles.
Referenced by HasTimerRun(), and IsTimerRunning().
IsTimerRunning()
bool Audio::FQuartzLatencyTimer::IsTimerRunning ()
Definition at line 722 of file QuartzQuantizationUtilities.cpp.
References HasTimerStarted(), and HasTimerStopped().
Referenced by GetCurrentTimePassedMs().
ResetTimer()
void Audio::FQuartzLatencyTimer::ResetTimer ()
Definition at line 680 of file QuartzQuantizationUtilities.cpp.
References JourneyEndCycles, and JourneyStartCycles.
StartTimer()
void Audio::FQuartzLatencyTimer::StartTimer ()
Definition at line 675 of file QuartzQuantizationUtilities.cpp.
References FAndroidTime::Cycles64(), and JourneyStartCycles.
StopTimer()
void Audio::FQuartzLatencyTimer::StopTimer ()
Definition at line 686 of file QuartzQuantizationUtilities.cpp.
References FAndroidTime::Cycles64(), and JourneyEndCycles.
Field Documentation
JourneyEndCycles
int64 Audio::FQuartzLatencyTimer::JourneyEndCycles private
Definition at line 376 of file QuartzQuantizationUtilities.h.
Referenced by FQuartzLatencyTimer(), GetResultsMilliseconds(), HasTimerStopped(), ResetTimer(), and StopTimer().
JourneyStartCycles
int64 Audio::FQuartzLatencyTimer::JourneyStartCycles private
Definition at line 374 of file QuartzQuantizationUtilities.h.
Referenced by FQuartzLatencyTimer(), GetCurrentTimePassedMs(), GetResultsMilliseconds(), HasTimerStarted(), ResetTimer(), and StartTimer().
The documentation for this class was generated from the following files:
QuartzQuantizationUtilities.h
QuartzQuantizationUtilities.cpp