Unreal Engine 5.6 C++ API: FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc > Class Template Reference
FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
FORCEINLINE FLockFreePointerListLIFORoot ()
FORCEINLINE uint64 GetState () const
FORCEINLINE bool IsEmpty () const
TLinkPtr Pop ()
TLinkPtr PopAll ()
TLinkPtr PopAllAndChangeState (TFunctionRef< uint64(uint64)> StateChange)
void Push (TLinkPtr Item)
bool PushIf (TFunctionRef< TLinkPtr(uint64)> AllocateIfOkToPush)
void Reset ()
Private Types
typedef FLockFreeLinkPolicy::TLinkPtr TLinkPtr
Private Attributes
TDoublePtr Head
UE_NONCOPYABLE(FLockFreePointerListLIFORoot) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink TLink
Detailed Description
template<int TPaddingForCacheContention, uint64 TABAInc = 1>
class FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >
Definition at line 261 of file LockFreeList.h.
Member Typedef Documentation
TLinkPtr
template<int TPaddingForCacheContention, uint64 TABAInc = 1> typedef FLockFreeLinkPolicy::TLinkPtr FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::TLinkPtr private
Definition at line 267 of file LockFreeList.h.
Constructor & Destructor Documentation
FLockFreePointerListLIFORoot()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::FLockFreePointerListLIFORoot () inline nodiscard
Definition at line 270 of file LockFreeList.h.
References FORCEINLINE, MAX_TagBitsValue, and Reset().
Member Function Documentation
GetState()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE uint64 FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::GetState () const inline nodiscard
Definition at line 402 of file LockFreeList.h.
References FORCEINLINE, and Head.
IsEmpty()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE bool FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::IsEmpty () const inline nodiscard
Definition at line 397 of file LockFreeList.h.
References FORCEINLINE, and Head.
Pop()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> TLinkPtr FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Pop () inline
Definition at line 328 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), Head, Item, and TLink.
PopAll()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> TLinkPtr FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::PopAll () inline
Definition at line 353 of file LockFreeList.h.
References Head, and Item.
PopAllAndChangeState()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> TLinkPtr FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::PopAllAndChangeState (TFunctionRef< uint64(uint64)> StateChange) inline
Definition at line 376 of file LockFreeList.h.
References Head, and Item.
Push()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> void FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Push (TLinkPtr Item) inline
Definition at line 284 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), Head, Item, and FIndexedLockFreeLink::SingleNext.
PushIf()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> bool FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::PushIf (TFunctionRef< TLinkPtr(uint64)> AllocateIfOkToPush) inline
Definition at line 301 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), Head, Item, and FIndexedLockFreeLink::SingleNext.
Reset()
template<int TPaddingForCacheContention, uint64 TABAInc = 1> void FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Reset () inline
Definition at line 279 of file LockFreeList.h.
References Head.
Referenced by FLockFreePointerListLIFORoot().
Field Documentation
Head
template<int TPaddingForCacheContention, uint64 TABAInc = 1> TDoublePtr FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Head private
Definition at line 410 of file LockFreeList.h.
Referenced by GetState(), IsEmpty(), Pop(), PopAll(), PopAllAndChangeState(), Push(), PushIf(), and Reset().
TLink
template<int TPaddingForCacheContention, uint64 TABAInc = 1> UE_NONCOPYABLE (FLockFreePointerListLIFORoot) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::TLink private
Definition at line 266 of file LockFreeList.h.
Referenced by Pop().
The documentation for this class was generated from the following file:
LockFreeList.h