Unreal Engine 5.6 C++ API: FRDGDispatchPass Class Reference
FRDGDispatchPass Class Reference
#include "RenderGraphPass.h"
Public Member Functions
FRDGDispatchPass (FRDGEventName &&InName, FRDGParameterStruct InParameterStruct, ERDGPassFlags InFlags)
Public Member Functions inherited from FRDGPass
FRDGPass (const FRDGPass &)=delete
RENDERCORE_API FRDGPass (FRDGEventName &&InName, FRDGParameterStruct InParameterStruct, ERDGPassFlags InFlags, ERDGPassTaskMode InTaskMode)
virtual ~FRDGPass ()=default
const FRDGEventName & GetEventName () const
ERDGPassFlags GetFlags () const
FRHIGPUMask GetGPUMask () const
FRDGPassHandle GetGraphicsForkPass () const
Returns the graphics pass responsible for forking the async interval this pass is in.
FRDGPassHandle GetGraphicsJoinPass () const
Returns the graphics pass responsible for joining the async interval this pass is in.
FRDGPassHandle GetHandle () const
RENDERCORE_API const TCHAR * GetName () const
FRDGParameterStruct GetParameters () const
ERHIPipeline GetPipeline () const
FRDGScope const * GetScope () const
ERDGPassTaskMode GetTaskMode () const
uint32 GetWorkload () const
bool IsAsyncCompute () const
bool IsAsyncComputeBegin () const
bool IsAsyncComputeEnd () const
bool IsCulled () const
bool IsGraphicsFork () const
bool IsGraphicsJoin () const
bool IsMergedRenderPassBegin () const
bool IsMergedRenderPassEnd () const
bool IsParallelExecuteAllowed () const
bool IsSentinel () const
bool SkipRenderPassBegin () const
bool SkipRenderPassEnd () const
Private Member Functions
void Execute (FRHIComputeCommandList &RHICmdList) override
Private Attributes
TArray< FRHICommandListImmediate::FQueuedCommandList, FRDGArrayAllocator > CommandLists
UE::Tasks::FTaskEvent CommandListsEvent { UE_SOURCE_LOCATION }
friend FRDGBuilder
friend FRDGDispatchPassBuilder
Additional Inherited Members
Protected Member Functions inherited from FRDGPass
FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginFor (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue, ERHIPipeline PipelineForEnd)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForAll (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForAsyncCompute (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchBegin & GetEpilogueBarriersToBeginForGraphics (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchEnd & GetEpilogueBarriersToEnd (FRDGAllocator &Allocator)
RENDERCORE_API FRDGBarrierBatchBegin & GetPrologueBarriersToBegin (FRDGAllocator &Allocator, FRDGTransitionCreateQueue &CreateQueue)
RENDERCORE_API FRDGBarrierBatchEnd & GetPrologueBarriersToEnd (FRDGAllocator &Allocator)
virtual void LaunchDispatchPassTasks (FRDGDispatchPassBuilder &DispatchPassBuilder)
Protected Attributes inherited from FRDGPass
union {
struct {
uint8 bCulled: 1
Whether this pass has been culled.
uint8 bEmptyParameters: 1
Whether this pass does not contain parameters.
uint8 bExternalAccessPass: 1
Whether this pass is used for external access transitions.
uint8 bHasExternalOutputs: 1
Whether this pass has external UAVs that are not tracked by RDG.
}
uint8 PacketBits_AsyncSetupQueue = 0
};
union {
struct {
uint16 bAsyncComputeBegin: 1
(AsyncCompute only) Whether this is the first / last async compute pass in an async interval.
uint16 bAsyncComputeEnd: 1
uint16 bDispatchAfterExecute: 1
If set, dispatches to the RHI thread after executing this pass.
uint16 bDispatchPass: 1
If set, this is a dispatch pass.
uint16 bGraphicsFork: 1
(Graphics only) Whether this is a graphics fork / join pass.
uint16 bGraphicsJoin: 1
uint16 bRenderPassOnlyWrites: 1
Whether the pass only writes to resources in its render pass.
uint16 bSentinel: 1
Whether this pass is a sentinel (prologue / epilogue) pass.
uint16 bSkipRenderPassBegin: 1
Whether the render pass begin / end should be skipped.
uint16 bSkipRenderPassEnd: 1
}
uint16 PackedBits = 0
};
union {
struct {
uint8 bParallelExecute: 1
If set, marks that a pass is executing in parallel.
uint8 bParallelExecuteBegin: 1
If set, marks the begin / end of a span of passes executed in parallel in a task.
uint8 bParallelExecuteEnd: 1
}
uint8 PacketBits_ParallelExecute = 0
};
TArray< FBufferState, FRDGArrayAllocator > BufferStates
TArray< FRDGPassHandle, FRDGArrayAllocator > CrossPipelineConsumers
Lists of producer passes and the full list of cross-pipeline consumer passes.
FRDGPassHandle CrossPipelineProducer
Handle of the latest cross-pipeline producer.
FRDGPassHandle EpilogueBarrierPass
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForAll = nullptr
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForAsyncCompute = nullptr
FRDGBarrierBatchBegin * EpilogueBarriersToBeginForGraphics = nullptr
FRDGBarrierBatchEnd * EpilogueBarriersToEnd = nullptr
TArray< FExternalAccessOp, FRDGArrayAllocator > ExternalAccessOps
const ERDGPassFlags Flags
friend FRDGBuilder
friend FRDGDispatchPassBuilder
friend FRDGPassRegistry
friend FRDGTrace
friend FRDGUserValidation
FString FullPathIfDebug
FRDGPassHandle GraphicsForkPass
(AsyncCompute only) Graphics passes which are the fork / join for async compute interval this pass is in.
FRDGPassHandle GraphicsJoinPass
FRDGPassHandle Handle
const FRDGEventName Name
uint32 NumTransitionsToReserve = 0
Number of transitions to reserve.
uint32 ParallelPassSetIndex = 0
const FRDGParameterStruct ParameterStruct
const ERHIPipeline Pipeline
TArray< FRDGPass *, FRDGArrayAllocator > Producers
FRDGPassHandle PrologueBarrierPass
The passes which are handling the epilogue / prologue barriers meant for this pass.
FRDGBarrierBatchBegin * PrologueBarriersToBegin = nullptr
Split-barrier batches at various points of execution of the pass.
FRDGBarrierBatchEnd * PrologueBarriersToEnd = nullptr
TArray< FRDGPass *, TInlineAllocator< 1, FRDGArrayAllocator > > ResourcesToBegin
Lists of pass parameters scheduled for begin during execution of this pass.
TArray< FRDGPass *, TInlineAllocator< 1, FRDGArrayAllocator > > ResourcesToEnd
FRDGScope * Scope = nullptr
TArray< FRDGBarrierBatchBegin *, FRDGArrayAllocator > SharedEpilogueBarriersToBegin
const ERDGPassTaskMode TaskMode
TArray< FTextureState, FRDGArrayAllocator > TextureStates
Maps textures / buffers to information on how they are used in the pass.
TArray< FRDGUniformBufferHandle, FRDGArrayAllocator > UniformBuffers
TArray< FRDGViewHandle, FRDGArrayAllocator > Views
uint32 Workload = 1
Detailed Description
Definition at line 712 of file RenderGraphPass.h.
Constructor & Destructor Documentation
FRDGDispatchPass()
FRDGDispatchPass::FRDGDispatchPass (FRDGEventName && InName, FRDGParameterStruct InParameterStruct, ERDGPassFlags InFlags) inline
Definition at line 716 of file RenderGraphPass.h.
References FRDGPass::FRDGPass(), Async, FRDGPass::bDispatchPass, InName, and MoveTemp().
Referenced by TRDGDispatchPass< ParameterStructType, LaunchLambdaType >::TRDGDispatchPass().
Member Function Documentation
Execute()
void FRDGDispatchPass::Execute (FRHIComputeCommandList & RHICmdList) inline override private virtual
Reimplemented from FRDGPass.
Definition at line 723 of file RenderGraphPass.h.
References CommandLists, and MoveTemp().
Field Documentation
CommandLists
TArray<FRHICommandListImmediate::FQueuedCommandList, FRDGArrayAllocator> FRDGDispatchPass::CommandLists private
Definition at line 728 of file RenderGraphPass.h.
Referenced by Execute().
CommandListsEvent
UE::Tasks::FTaskEvent FRDGDispatchPass::CommandListsEvent { UE_SOURCE_LOCATION } private
Definition at line 729 of file RenderGraphPass.h.
FRDGBuilder
friend FRDGDispatchPass::FRDGBuilder private
Definition at line 731 of file RenderGraphPass.h.
FRDGDispatchPassBuilder
friend FRDGDispatchPass::FRDGDispatchPassBuilder private
Definition at line 732 of file RenderGraphPass.h.
Referenced by TRDGDispatchPass< ParameterStructType, LaunchLambdaType >::LaunchDispatchPassTasks().
The documentation for this class was generated from the following file:
RenderGraphPass.h