Unreal Engine 5.6 C++ API: FEditorModeRegistry Class Reference
FEditorModeRegistry Class Reference
A registry of editor modes and factories.
#include "EditorModeRegistry.h"
Public Member Functions
const FactoryMap & GetFactoryMap () const
Const access to the internal factory map.
template<class T>
void RegisterMode (FEditorModeID ModeID, FText Name=FText(), FSlateIcon IconBrush=FSlateIcon(), bool bVisible=false, int32 PriorityOrder=MAX_int32)
Registers an editor mode type.
UNREALED_API void RegisterMode (FEditorModeID ModeID, TSharedRef< IEditorModeFactory > Factory)
Registers an editor mode.
UE_DEPRECATED (4.26, "Use UAssetEditorSubsystem::FindEditorModeInfo") UNREALED_API FEditorModeInfo GetModeInfo(FEditorModeID ModeID) const
Get a currently registered mode information for specified ID.
UE_DEPRECATED (4.26, "Use UAssetEditorSubsystem::GetEditorModeInfoOrderedByPriority") UNREALED_API TArray< FEditorModeInfo > GetSortedModeInfo() const
Get a list of information for all currently registered modes, sorted by UI priority order.
UE_DEPRECATED (4.26, "Use UAssetEditorSubsystem::OnEditorModeRegistered") FOnModeRegistered &OnModeRegistered()
Event that is triggered whenever a mode is registered.
UE_DEPRECATED (4.26, "Use UAssetEditorSubsystem::OnEditorModesChanged") FRegisteredModesChangedEvent &OnRegisteredModesChanged()
Event that is triggered whenever a mode is registered or unregistered.
UE_DEPRECATED (4.26, "Use UAssetEditorSubsystem::OnEditorModeUnregistered") FOnModeUnregistered &OnModeUnregistered()
Event that is triggered whenever a mode is unregistered.
UNREALED_API void UnregisterMode (FEditorModeID ModeID)
Unregisters an editor mode.
Static Public Member Functions
static UNREALED_API FEditorModeRegistry & Get ()
Singleton access.
Private Types
typedef TMap< FEditorModeID, TSharedRef< IEditorModeFactory > > FactoryMap
Private Member Functions
TSharedPtr< FEdMode > CreateMode (FEditorModeID ModeID, FEditorModeTools &Owner)
Create a new instance of the mode registered under the specified ID.
void Initialize ()
Initialize this registry.
void Shutdown ()
Shutdown this registry.
Private Attributes
bool bInitialized = false
FactoryMap ModeFactories
A map of editor mode IDs to factory callbacks.
Friends
class UAssetEditorSubsystem
class ULegacyEdModeWrapper
Detailed Description
A registry of editor modes and factories.
Definition at line 83 of file EditorModeRegistry.h.
Member Typedef Documentation
FactoryMap
typedef TMap<FEditorModeID, TSharedRef<IEditorModeFactory> > FEditorModeRegistry::FactoryMap private
Definition at line 85 of file EditorModeRegistry.h.
Member Function Documentation
CreateMode()
TSharedPtr< FEdMode > FEditorModeRegistry::CreateMode (FEditorModeID ModeID, FEditorModeTools & Owner) private
Create a new instance of the mode registered under the specified ID.
References Owner.
Get()
UNREALED_API FEditorModeRegistry & FEditorModeRegistry::Get () static
Singleton access.
GetFactoryMap()
const FactoryMap & FEditorModeRegistry::GetFactoryMap () const inline
Const access to the internal factory map.
Definition at line 159 of file EditorModeRegistry.h.
References GetFactoryMap(), and ModeFactories.
Referenced by GetFactoryMap().
Initialize()
void FEditorModeRegistry::Initialize () private
Initialize this registry.
RegisterMode() [1/2]
template<class T> void FEditorModeRegistry::RegisterMode (FEditorModeID ModeID, FText Name = FText(), FSlateIcon IconBrush = FSlateIcon(), bool bVisible = false, int32 PriorityOrder = MAX_int32) inline
Registers an editor mode type.
Typically called from a module's StartupModule() routine.
Parameters
ModeID ID of the mode to register
Definition at line 120 of file EditorModeRegistry.h.
References FEditorModeFactory::FEditorModeFactory(), MakeShareable(), MAX_int32, Name, and RegisterMode().
RegisterMode() [2/2]
UNREALED_API void FEditorModeRegistry::RegisterMode (FEditorModeID ModeID, TSharedRef< IEditorModeFactory > Factory)
Registers an editor mode.
Typically called from a module's StartupModule() routine.
Parameters
ModeID ID of the mode to register
References RegisterMode().
Referenced by RegisterMode(), and RegisterMode().
Shutdown()
void FEditorModeRegistry::Shutdown () private
Shutdown this registry.
UE_DEPRECATED() [1/5]
FEditorModeRegistry::UE_DEPRECATED (4. 26, "Use UAssetEditorSubsystem::FindEditorModeInfo") const
Get a currently registered mode information for specified ID.
References UE_DEPRECATED().
UE_DEPRECATED() [2/5]
FEditorModeRegistry::UE_DEPRECATED (4. 26, "Use UAssetEditorSubsystem::GetEditorModeInfoOrderedByPriority") const
Get a list of information for all currently registered modes, sorted by UI priority order.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/5]
FEditorModeRegistry::UE_DEPRECATED (4. 26, "Use UAssetEditorSubsystem::OnEditorModeRegistered") &
Event that is triggered whenever a mode is registered.
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
FEditorModeRegistry::UE_DEPRECATED (4. 26, "Use UAssetEditorSubsystem::OnEditorModesChanged") &
Event that is triggered whenever a mode is registered or unregistered.
UE_DEPRECATED() [5/5]
FEditorModeRegistry::UE_DEPRECATED (4. 26, "Use UAssetEditorSubsystem::OnEditorModeUnregistered") &
Event that is triggered whenever a mode is unregistered.
References UE_DEPRECATED().
UnregisterMode()
UNREALED_API void FEditorModeRegistry::UnregisterMode (FEditorModeID ModeID)
Unregisters an editor mode.
Typically called from a module's ShutdownModule() routine. Note: will exit the edit mode if it is currently active.
Parameters
ModeID ID of the mode to unregister
Friends And Related Symbol Documentation
UAssetEditorSubsystem
friend class UAssetEditorSubsystem friend
Definition at line 87 of file EditorModeRegistry.h.
References UAssetEditorSubsystem.
Referenced by UAssetEditorSubsystem.
ULegacyEdModeWrapper
friend class ULegacyEdModeWrapper friend
Definition at line 86 of file EditorModeRegistry.h.
References ULegacyEdModeWrapper.
Referenced by ULegacyEdModeWrapper.
Field Documentation
bInitialized
bool FEditorModeRegistry::bInitialized = false private
Definition at line 181 of file EditorModeRegistry.h.
ModeFactories
FactoryMap FEditorModeRegistry::ModeFactories private
A map of editor mode IDs to factory callbacks.
Definition at line 179 of file EditorModeRegistry.h.
Referenced by GetFactoryMap().
The documentation for this class was generated from the following file:
EditorModeRegistry.h