Unreal Engine 5.6 C++ API: CommonUIUtils Namespace Reference
CommonUIUtils Namespace Reference
Enumerations
enum class ECollisionPolicy { Allow , Require , Forbid }
Functions
template<typename UserWidgetT = UUserWidget>
UserWidgetT * GetOwningUserWidget (const UWidget *Widget)
Traverses the UserWidgets that the given widget resides in until we find one matching the given type (or we run out of parents)
FString PrintAllOwningUserWidgets (const UWidget *Widget)
Traverses the UserWidgets the given widget resides in and prints their names.
bool COMMONUI_API ShouldDisplayMobileUISizes ()
template<typename... ChildNameArgs>
void ValidateBoundWidgetHierarchy (const UWidgetTree &WidgetTree, IWidgetCompilerLog &CompileLog, ECollisionPolicy CollisionPolicy, FName ParentWidgetName, ChildNameArgs &&... ChildNames)
COMMONUI_API void ValidateBoundWidgetHierarchy (const UWidgetTree &WidgetTree, IWidgetCompilerLog &CompileLog, ECollisionPolicy CollisionPolicy, FName ParentWidgetName, TArray< FName > &&ChildNames)
Validates that a given widget tree hierarchy satisfies the condition that a given widget contains N other widgets (optionally requiring individual slots for each) Intended to be called from within a widget subclass's ValidateCompiledWidgetTree override If the given hierarchy does not satisfy the requirements, we'll log an error in the compiler log.
Enumeration Type Documentation
ECollisionPolicy
enum class CommonUIUtils::ECollisionPolicy strong
Enumerator
Allow
Require
Forbid
Definition at line 14 of file CommonUIUtils.h.
Function Documentation
GetOwningUserWidget()
template<typename UserWidgetT = UUserWidget> UserWidgetT * CommonUIUtils::GetOwningUserWidget (const UWidget * Widget)
Traverses the UserWidgets that the given widget resides in until we find one matching the given type (or we run out of parents)
Parameters
Widget The widget whose parent we're seeking
Returns
The first parent of the given type, or nullptr if there is none
Definition at line 32 of file CommonUIUtils.h.
References Cast(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
PrintAllOwningUserWidgets()
FString CommonUIUtils::PrintAllOwningUserWidgets (const UWidget * Widget)
Traverses the UserWidgets the given widget resides in and prints their names.
Useful for debug logging.
Parameters
Widget The widget whose parents we'll print
Returns
An FString containing the names of the parents
ShouldDisplayMobileUISizes()
bool COMMONUI_API CommonUIUtils::ShouldDisplayMobileUISizes ()
ValidateBoundWidgetHierarchy() [1/2]
template<typename... ChildNameArgs> void CommonUIUtils::ValidateBoundWidgetHierarchy (const UWidgetTree & WidgetTree, IWidgetCompilerLog & CompileLog, ECollisionPolicy CollisionPolicy, FName ParentWidgetName, ChildNameArgs &&... ChildNames)
Definition at line 87 of file CommonUIUtils.h.
References ValidateBoundWidgetHierarchy().
ValidateBoundWidgetHierarchy() [2/2]
COMMONUI_API void CommonUIUtils::ValidateBoundWidgetHierarchy (const UWidgetTree & WidgetTree, IWidgetCompilerLog & CompileLog, ECollisionPolicy CollisionPolicy, FName ParentWidgetName, TArray< FName > && ChildNames)
Validates that a given widget tree hierarchy satisfies the condition that a given widget contains N other widgets (optionally requiring individual slots for each) Intended to be called from within a widget subclass's ValidateCompiledWidgetTree override If the given hierarchy does not satisfy the requirements, we'll log an error in the compiler log.
void MyWidget::ValidateCompiledWidgetTree(const UWidgetTree& BlueprintWidgetTree, IWidgetCompilerLog& CompileLog) const { Super::ValidateCompiledWidgetTree(BlueprintWidgetTree, CompileLog);
const CommonUIUtils::ECollisionPolicy CollisionPolicy = CommonUIUtils::ECollisionPolicy::Forbid; CommonUIUtils::ValidateBoundWidgetHierarchy(BlueprintWidgetTree, CompileLog, CollisionPolicy, GET_MEMBER_NAME_CHECKED(MyWidget, MySubWidget1Name), GET_MEMBER_NAME_CHECKED(MyWidget, MySubWidget2Name)); }
Referenced by ValidateBoundWidgetHierarchy().