Unreal Engine 5.6 C++ API: UE::MovieScene::TAddConditional< T > Struct Template Reference
UE::MovieScene::TAddConditional< T > Struct Template Reference
Implemtntation of a conditional typed add payload.
#include "MovieSceneEntityBuilder.h"
Public Member Functions
template<typename PayloadType>
TAddConditional (TComponentTypeID< T > ComponentTypeID, PayloadType &&InPayload, bool bInCondition)
void Apply (FEntityAllocation *Allocation, int32 ComponentOffset)
Public Member Functions inherited from UE::MovieScene::FAddConditional
FAddConditional (FComponentTypeID InComponentTypeID, bool bInCondition)
void AccumulateMask (FComponentMask &OutMask) const
void Apply (FEntityAllocation *Allocation, int32 ComponentOffset)
Data Fields
TOptional< T > Payload
Data Fields inherited from UE::MovieScene::FAddConditional
bool bCondition
FComponentTypeID ComponentTypeID
Detailed Description
template<typename T>
struct UE::MovieScene::TAddConditional< T >
Implemtntation of a conditional typed add payload.
Definition at line 516 of file MovieSceneEntityBuilder.h.
Constructor & Destructor Documentation
TAddConditional()
template<typename T> template<typename PayloadType> UE::MovieScene::TAddConditional< T >::TAddConditional (TComponentTypeID< T > ComponentTypeID, PayloadType && InPayload, bool bInCondition) inline
Definition at line 521 of file MovieSceneEntityBuilder.h.
References UE::MovieScene::FAddConditional::FAddConditional(), UE::MovieScene::FAddConditional::ComponentTypeID, Forward(), and Payload.
Member Function Documentation
Apply()
template<typename T> void UE::MovieScene::TAddConditional< T >::Apply (FEntityAllocation * Allocation, int32 ComponentOffset) inline
Definition at line 526 of file MovieSceneEntityBuilder.h.
References UE::MovieScene::FAddConditional::bCondition, check, UE::MovieScene::FAddConditional::ComponentTypeID, Header, MoveTemp(), and Payload.
Field Documentation
Payload
template<typename T> TOptional<T> UE::MovieScene::TAddConditional< T >::Payload
Definition at line 518 of file MovieSceneEntityBuilder.h.
Referenced by TAddConditional(), and Apply().
The documentation for this struct was generated from the following file:
MovieSceneEntityBuilder.h