Unreal Engine 5.6 C++ API: EngineTypes.h File Reference
EngineTypes.h File Reference
#include "Misc/EnumClassFlags.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Templates/SubclassOf.h"
#include "Engine/TimerHandle.h"
#include "Engine/NaniteAssemblyData.h"
#include "EngineTypes.generated.h"
Data Structures
struct FAttachmentTransformRules
Rules for attaching components - needs to be kept synced to EDetachmentRule.
struct FCollisionEnabledMask
struct FComponentSocketDescription
Info about a socket on a scene component.
struct FDetachmentTransformRules
Rules for detaching components - needs to be kept synced to EAttachmentRule.
struct FReplicationFlags
Structure to hold and pass around transient flags used during replication.
struct FRotationConversionCache
Struct for caching Quat<->Rotator conversions.
struct FRotationConversionCache::FPayload
struct FSubstrateMaterialInfo
Gather information from the Substrate material graph to setup material for runtime.
struct TIsPODType< FWalkableSlopeOverride >
struct TIsZeroConstructType< FCanvasUVTri >
struct TStructOpsTypeTraits< FSoftComponentReference >
Struct that allows for different ways to reference a component using TObjectPtr.
struct TStructOpsTypeTraits< FSubstrateMaterialInfo >
Namespaces
namespace EBrowseReturnVal
Enum describing how to constrain perspective view port FOV.
namespace EWorldType
Specifies what types of objects to return from an overlap physics query.
Macros
#define COLLISION_GIZMO ECC_EngineTraceChannel1
#define NUM_LIGHTING_CHANNELS 3
Specifies which component of the scene rendering should be output to the final render target.
#define SUBSTRATE_TREE_MAX_DEPTH 48
Enumerations
enum { NumExtraFilterBits = 6 }
Lighting build quality enumeration.
enum { NumInlinedActorComponents = 24 }
Default number of components to expect in TInlineAllocators used with AActor component arrays.
enum class EFlushLevelStreamingType : uint8 { None , Full , Visibility }
Describes what parts of level streaming should be forcibly handled immediately.
enum class ELevelCollectionType : uint8 { DynamicSourceLevels , DynamicDuplicatedLevels , StaticLevels , MAX }
Which processors will have access to Mesh Vertex Buffers.
enum class EPackageAutoSaveType : uint8 { None = 0 , Transient = 1 << 0 , Persistent = 1 << 1 , Any = Transient | Persistent }
enum class ESleepEvent : uint8 { SET_Wakeup , SET_Sleep }
Describes type of wake/sleep event sent to the physics system.
enum ESubstrateShadingModel : int {
SSM_Unlit , SSM_DefaultLit , SSM_ThinTranslucent , SSM_SubsurfaceMFP ,
SSM_SubsurfaceProfile , SSM_SubsurfaceWrap , SSM_SubsurfaceThinTwoSided , SSM_VolumetricFogCloud ,
SSM_Hair , SSM_Eye , SSM_Cloth , SSM_ClearCoat ,
SSM_SingleLayerWater , SSM_LightFunction , SSM_PostProcess , SSM_Decal ,
SSM_UI , SSM_NUM
}
Specifies the Substrate runtime shading model summarized from the material graph Not exposed in UI, only used in code.
enum class EUserActivityContext : uint8 { Game , Editor , Other }
Defines available strategies for handling the case where an actor is spawned in such a way that it penetrates blocking collision.
enum EBrowseReturnVal::Type { EBrowseReturnVal::Success , EBrowseReturnVal::Failure , EBrowseReturnVal::Pending }
enum EWorldType::Type {
EWorldType::None , EWorldType::Game , EWorldType::Editor , EWorldType::PIE ,
EWorldType::EditorPreview , EWorldType::GamePreview , EWorldType::GameRPC , EWorldType::Inactive
}
Functions
FORCEINLINE ECollisionEnabled::Type CollisionEnabledFromFlags (const bool bQuery, const bool bPhysics, const bool bProbe)
Convert a set of three bools into an ECollisionEnabled.
FORCEINLINE bool CollisionEnabledHasPhysics (ECollisionEnabled::Type CollisionEnabled)
FORCEINLINE bool CollisionEnabledHasProbe (ECollisionEnabled::Type CollisionEnabled)
FORCEINLINE bool CollisionEnabledHasQuery (ECollisionEnabled::Type CollisionEnabled)
FORCEINLINE ECollisionEnabled::Type CollisionEnabledIntersection (ECollisionEnabled::Type CollisionEnabledA, ECollisionEnabled::Type CollisionEnabledB)
FORCEINLINE void CollisionEnabledToFlags (const ECollisionEnabled::Type CollisionEnabled, bool &bQuery, bool &bPhysics, bool &bProbe)
Convert an ECollisionEnabled enum into a set of three bools.
UENUM() enum ECollisionChannel DECLARE_DELEGATE_OneParam (FOnConstraintBroken, int32)
Enum indicating different type of objects for rigid-body collision purposes.
DECLARE_DELEGATE_OneParam (FOnPlasticDeformation, int32)
DECLARE_DELEGATE_ThreeParams (FOnConstraintViolated, int32, float, float)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FConstraintBrokenSignature, int32, ConstraintIndex)
Dynamic delegate to use by components that want to route the broken-event into blueprints.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FPlasticDeformationEventSignature, int32, ConstraintIndex)
Dynamic delegate to use by components that want to route the pasticity deformation event into blueprints.
ENUM_CLASS_FLAGS (EPackageAutoSaveType)
uint8 GetDefaultLightingChannelMask ()
Returns mask for only channel 0.
int32 GetFirstLightingChannelFromMask (uint8 Mask)
Returns the index of the first lighting channel set, or -1 if no channels are set.
uint8 GetLightingChannelMaskForStruct (FLightingChannels Value)
Converts lighting channels into a bitfield.
uint32 GetTypeHash (const FBaseComponentReference &Reference)
UENUM() enum EMaterialSamplerType bool IsVirtualSamplerType (EMaterialSamplerType Value)
Describes how textures are sampled for materials.
const TCHAR * LexToString (const EWorldType::Type Value)
FCollisionEnabledMask operator& (const ECollisionEnabled::Type A, const ECollisionEnabled::Type B)
FCollisionEnabledMask operator& (const ECollisionEnabled::Type A, const FCollisionEnabledMask B)
FCollisionEnabledMask operator| (const ECollisionEnabled::Type A, const ECollisionEnabled::Type B)
FCollisionEnabledMask operator| (const ECollisionEnabled::Type A, const FCollisionEnabledMask B)
void SerializeNaniteSettingsForDDC (FArchive &Ar, FMeshNaniteSettings &NaniteSettings, bool bIsNaniteForceEnabled)
void SerializeRayTracingProxySettingsForDDC (FArchive &Ar, FMeshRayTracingProxySettings &Settings)
FORCEINLINE bool TeleportEnumToFlag (ETeleportType Teleport)
UENUM() enum ELightMapPaddingType UENUM() enum EShadowMapFlags UENUM() enum class ETeleportType FORCEINLINE ETeleportType TeleportFlagToEnum (bool bTeleport)
Method for padding a light map in memory.
USTRUCT () struct FLightingChannels
Specifies which lighting channels are relevant.
Variables
UENUM () enum EMaterialShadingModel
Specifies the overal rendering/shading model for a material.
Macro Definition Documentation
COLLISION_GIZMO
#define COLLISION_GIZMO ECC_EngineTraceChannel1
Definition at line 1101 of file EngineTypes.h.
NUM_LIGHTING_CHANNELS
#define NUM_LIGHTING_CHANNELS 3
Specifies which component of the scene rendering should be output to the final render target.
Specifies how scene captures are composited into render buffers Maximum number of custom lighting channels
Definition at line 550 of file EngineTypes.h.
SUBSTRATE_TREE_MAX_DEPTH
#define SUBSTRATE_TREE_MAX_DEPTH 48
Definition at line 797 of file EngineTypes.h.
Referenced by FSubstrateMaterialInfo::PushSubstrateTreeStack().
Enumeration Type Documentation
anonymous enum
anonymous enum
Lighting build quality enumeration.
Movement modes for Characters. Smoothing approach used by network interpolation for Characters.
Enumerator
NumExtraFilterBits
Definition at line 1013 of file EngineTypes.h.
anonymous enum
anonymous enum
Default number of components to expect in TInlineAllocators used with AActor component arrays.
Used by engine code to try to avoid allocations in AActor::GetComponents(), among others.
Enumerator
NumInlinedActorComponents
Definition at line 32 of file EngineTypes.h.
EFlushLevelStreamingType
enum class EFlushLevelStreamingType : uint8 strong
Describes what parts of level streaming should be forcibly handled immediately.
Enumerator
None
Do not flush state on change.
Full
Allow multiple load requests.
Visibility
Flush visibility only, do not allow load requests, flushes async loading as well.
Definition at line 1255 of file EngineTypes.h.
ELevelCollectionType
enum class ELevelCollectionType : uint8 strong
Which processors will have access to Mesh Vertex Buffers.
Indicates the type of a level collection, used in FLevelCollection.
Enumerator
DynamicSourceLevels
The dynamic levels that are used for normal gameplay and the source for any duplicated collections.
Will contain a world's persistent level and any streaming levels that contain dynamic or replicated gameplay actors. This collection will always exist for gameplay and editor worlds.
DynamicDuplicatedLevels
Gameplay relevant levels that have been duplicated from DynamicSourceLevels if requested by the game.
This collection only exists if levels have actually been duplicated.
StaticLevels
These levels are shared between the source levels and the duplicated levels, and should contain only static geometry and other visuals that are not replicated or affected by gameplay.
These will not be duplicated in order to save memory. If s.World.CreateStaticLevelCollection is 0, this will not be created and static levels will be treated as dynamic.
MAX
Definition at line 4188 of file EngineTypes.h.
EPackageAutoSaveType
enum class EPackageAutoSaveType : uint8 strong
Enumerator
None
No auto-save is happening.
Transient
The auto-save is happening to a transient directory (eg, the Saved/Autosaves directory) and doesn't directly replace the persistent project content.
Persistent
The auto-save is happening directly to the persistent project content, though a backup may still be made in a transient directory.
Any
The auto-save is happening for any reason.
Definition at line 4214 of file EngineTypes.h.
ESleepEvent
enum class ESleepEvent : uint8 strong
Describes type of wake/sleep event sent to the physics system.
Enumerator
SET_Wakeup
SET_Sleep
Definition at line 1671 of file EngineTypes.h.
ESubstrateShadingModel
enum ESubstrateShadingModel : int
Specifies the Substrate runtime shading model summarized from the material graph Not exposed in UI, only used in code.
Those states are deducted from the material graph and map to a specific domain/shading state.
Enumerator
SSM_Unlit
SSM_DefaultLit
SSM_ThinTranslucent
SSM_SubsurfaceMFP
SSM_SubsurfaceProfile
SSM_SubsurfaceWrap
SSM_SubsurfaceThinTwoSided
SSM_VolumetricFogCloud
SSM_Hair
SSM_Eye
SSM_Cloth
SSM_ClearCoat
SSM_SingleLayerWater
SSM_LightFunction
SSM_PostProcess
SSM_Decal
SSM_UI
SSM_NUM
Number of unique shading models.
Definition at line 772 of file EngineTypes.h.
EUserActivityContext
enum class EUserActivityContext : uint8 strong
Defines available strategies for handling the case where an actor is spawned in such a way that it penetrates blocking collision.
Defines the context of a user activity. Activities triggered in Blueprints will by type Game. Those created in code might choose to set another type.
Enumerator
Game
Event triggered from gameplay, such as from blueprints.
Editor
Event triggered from the editor UI.
Other
Event triggered from some other source.
Definition at line 4133 of file EngineTypes.h.
Function Documentation
CollisionEnabledFromFlags()
FORCEINLINE ECollisionEnabled::Type CollisionEnabledFromFlags (const bool bQuery, const bool bPhysics, const bool bProbe)
Convert a set of three bools into an ECollisionEnabled.
Definition at line 1635 of file EngineTypes.h.
References FORCEINLINE.
CollisionEnabledHasPhysics()
FORCEINLINE bool CollisionEnabledHasPhysics (ECollisionEnabled::Type CollisionEnabled)
Definition at line 1574 of file EngineTypes.h.
References FORCEINLINE.
Referenced by USceneComponent::IsPhysicsCollisionEnabled().
CollisionEnabledHasProbe()
FORCEINLINE bool CollisionEnabledHasProbe (ECollisionEnabled::Type CollisionEnabled)
Definition at line 1587 of file EngineTypes.h.
References FORCEINLINE.
CollisionEnabledHasQuery()
FORCEINLINE bool CollisionEnabledHasQuery (ECollisionEnabled::Type CollisionEnabled)
Definition at line 1580 of file EngineTypes.h.
References FORCEINLINE.
Referenced by USceneComponent::IsQueryCollisionEnabled().
CollisionEnabledIntersection()
FORCEINLINE ECollisionEnabled::Type CollisionEnabledIntersection (ECollisionEnabled::Type CollisionEnabledA, ECollisionEnabled::Type CollisionEnabledB)
Definition at line 1593 of file EngineTypes.h.
References FORCEINLINE.
CollisionEnabledToFlags()
FORCEINLINE void CollisionEnabledToFlags (const ECollisionEnabled::Type CollisionEnabled, bool & bQuery, bool & bPhysics, bool & bProbe)
Convert an ECollisionEnabled enum into a set of three bools.
Definition at line 1662 of file EngineTypes.h.
References FORCEINLINE.
DECLARE_DELEGATE_OneParam() [1/2]
UENUM() enum ECollisionChannel DECLARE_DELEGATE_OneParam (FOnConstraintBroken , int32)
Enum indicating different type of objects for rigid-body collision purposes.
DECLARE_DELEGATE_OneParam() [2/2]
DECLARE_DELEGATE_OneParam (FOnPlasticDeformation , int32)
DECLARE_DELEGATE_ThreeParams()
DECLARE_DELEGATE_ThreeParams (FOnConstraintViolated , int32 , float , float)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam() [1/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FConstraintBrokenSignature , int32 , ConstraintIndex)
Dynamic delegate to use by components that want to route the broken-event into blueprints.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam() [2/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FPlasticDeformationEventSignature , int32 , ConstraintIndex)
Dynamic delegate to use by components that want to route the pasticity deformation event into blueprints.
References BlueprintType, Category, UPROPERTY, and USTRUCT.
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EPackageAutoSaveType)
GetDefaultLightingChannelMask()
uint8 GetDefaultLightingChannelMask () inline
Returns mask for only channel 0.
Definition at line 585 of file EngineTypes.h.
Referenced by FPrimitiveUniformShaderParametersBuilder::Defaults().
GetFirstLightingChannelFromMask()
int32 GetFirstLightingChannelFromMask (uint8 Mask) inline
Returns the index of the first lighting channel set, or -1 if no channels are set.
Definition at line 591 of file EngineTypes.h.
References Mask.
GetLightingChannelMaskForStruct()
uint8 GetLightingChannelMaskForStruct (FLightingChannels Value) inline
Converts lighting channels into a bitfield.
Definition at line 578 of file EngineTypes.h.
References Value.
GetTypeHash()
uint32 GetTypeHash (const FBaseComponentReference & Reference) inline
Definition at line 3638 of file EngineTypes.h.
References GetTypeHash(), and HashCombineFast().
IsVirtualSamplerType()
UENUM() enum EMaterialSamplerType bool IsVirtualSamplerType (EMaterialSamplerType Value) inline
Describes how textures are sampled for materials.
Definition at line 922 of file EngineTypes.h.
References Value.
LexToString()
const TCHAR * LexToString (const EWorldType::Type Value)
References Value.
operator&() [1/2]
FCollisionEnabledMask operator& (const ECollisionEnabled::Type A, const ECollisionEnabled::Type B) extern
References A, and B.
operator&() [2/2]
FCollisionEnabledMask operator& (const ECollisionEnabled::Type A, const FCollisionEnabledMask B) extern
References A, and B.
operator|() [1/2]
FCollisionEnabledMask operator| (const ECollisionEnabled::Type A, const ECollisionEnabled::Type B) extern
References A, and B.
operator|() [2/2]
FCollisionEnabledMask operator| (const ECollisionEnabled::Type A, const FCollisionEnabledMask B) extern
References A, and B.
SerializeNaniteSettingsForDDC()
void SerializeNaniteSettingsForDDC (FArchive & Ar, FMeshNaniteSettings & NaniteSettings, bool bIsNaniteForceEnabled)
References Ar.
SerializeRayTracingProxySettingsForDDC()
void SerializeRayTracingProxySettingsForDDC (FArchive & Ar, FMeshRayTracingProxySettings & Settings)
References Ar.
TeleportEnumToFlag()
FORCEINLINE bool TeleportEnumToFlag (ETeleportType Teleport)
Definition at line 2374 of file EngineTypes.h.
References FORCEINLINE.
TeleportFlagToEnum()
UENUM() enum ELightMapPaddingType UENUM() enum EShadowMapFlags UENUM() enum class ETeleportType FORCEINLINE ETeleportType TeleportFlagToEnum (bool bTeleport)
Method for padding a light map in memory.
Bit-field flags that affects storage (e.g. packing, streaming) and other info about a shadowmap. Whether to teleport physics body or not
Definition at line 2373 of file EngineTypes.h.
References FORCEINLINE.
USTRUCT()
USTRUCT ()
Specifies which lighting channels are relevant.
The description of a user activity.
Simple 2d triangle with UVs.
Information used in font rendering.
Info for glow when using depth field rendering.
Structure for recording float values and displaying them as an Histogram through DrawDebugFloatHistory.
This is used for redirecting an old name to new name, such as for collision profiles This is used for better UI in the editor.
Reference to an editor collection of assets.
Base class for the hard/soft component reference structs.
Struct used to specify the property name of the component to constrain.
Controls behavior of WalkableSlopeOverride, determining how to affect walkability of surfaces for Characters.
Settings applied when building Nanite data.
Settings applied when building a mesh.
Point Of View structure used in Camera calculations.
Enum for controlling buckets for update rate optimizations if we need to stagger Multiple actor populations separately.
Used to indicate each slot name and how many channels they have.
Structure containing information about minimum translation direction (MTD)
Debug options for Swarm.
Debug options for Lightmass.
Point/spot settings for Lightmass.
Per-light settings for Lightmass.
A line of subtitle text and the time at which it should be displayed.
Struct for handling positions relative to a base actor, which is potentially moving.
Struct used to hold effects for destructible damage events.
Information about an overall collision, including contacts.
Information about one contact between a pair of rigid bodies.
Rigid body error correction data.
Container for indicating a set of collision channels that this object will collide with.
Describes response for a single collision response channel.
Wrapper for a bitfield of shading models.
View / light masking support.
A material contains one of these to describe what possible shading models can be used by that material.
Directional light settings for Lightmass Per-object settings for Lightmass
Container for Animation Update Rate parameters. They are shared for all components of an Actor, so they can be updated in sync.
See also
FWalkableSlopeOverride
UCharacterMovementComponent::GetWalkableFloorAngle(), UCharacterMovementComponent::SetWalkableFloorAngle() Struct allowing control over "walkable" normals, by allowing a restriction or relaxation of what steepness is normally walkable.
This allows an editor-only picker UI
Default channel for all primitives and lights.
First custom channel
Second custom channel
View specific lighting channel 0 (enabled by default).
View specific lighting channel 1.
View specific lighting channel 2.
View specific lighting channel 3.
View specific lighting channel 4.
Converts view lighting channels into a bitfield for use in FLightSceneProxy
This should match DisplayName of ECollisionChannel Meta data of custom channels can be used as well
Describes how the channel behaves
This constructor will set all channels to ECR_Block
Set the response of a particular channel in the structure.
Set all channels to the specified response
Replace the channels matching the old response with the new response
Returns the response set on the specified channel
Set all channels from ChannelResponse Array
Take two response containers and create a new container where each element is the 'min' of the two inputs (ie Ignore and Block results in Ignore)
Returns the game-wide default collision response
static variable for default data to be used without reconstructing everytime
Value between 0 and 1 which indicates how much velocity and ping based correction to use
For the purpose of extrapolation, ping will be clamped to this value
Error per centimeter
Error per degree
Maximum allowable error for a state to be considered "resolved"
How much to directly lerp to the correct position. Generally this should be very low, if not zero. A higher value will increase precision along with jerkiness.
How much to directly lerp to the correct angle.
This is the coefficient k in the differential equation: dx/dt = k (x_target(t) - x(t)), which is used to update the velocity in a replication step.
This is the angular analog to LinearVelocityCoefficient.
Number of seconds to remain in a heuristically unresolveable state before hard snapping.
If the body has moved less than the square root of this amount towards a resolved state in the previous frame, then error may accumulate towards a hard snap.
If the previous error projected onto the current error is greater than this value (indicating "similarity" between states), then error may accumulate towards a hard snap.
Position of contact, where two shapes intersect
Normal of contact, points from second shape towards first shape
How far the two shapes penetrated into each other
Was this contact generated by a probe constraint
The physical material of the two shapes involved in a contact
Swap the order of info in this info
All the contact points in the collision
The total impulse applied as the two objects push against each other
The total counterimpulse applied of the two objects sliding against each other
Iterate over ContactInfos array and swap order of information
Particle system effect to play at fracture location.
Sound cue to play at fracture location.
Actor that is the base
Position relative to the base actor
Retrieve world location of this position
Updates base/position
Clear base/position
The text to appear in the subtitle.
The time at which the subtitle is to be displayed, in seconds relative to the beginning of the line.
0 will be completely desaturated, 1 will be unchanged
Controls the falloff of shadow penumbras
Whether to use area shadows for stationary light precomputed shadowmaps.
Area shadows get softer the further they are from shadow casters, but require higher lightmap resolution to get the same quality where the shadow is sharp.
If true, this object will be lit as if it receives light from both sides of its polygons.
If true, this object will only shadow indirect lighting.
If true, allow using the emissive for static lighting.
Typically the triangle normal is used for hemisphere gathering which prevents incorrect self-shadowing from artist-tweaked vertex normals. However in the case of foliage whose vertex normal has been setup to match the underlying terrain, gathering in the direction of the vertex normal is desired.
Direct lighting falloff exponent for mesh area lights created from emissive areas on this primitive.
Direct lighting influence radius. The default is 0, which means the influence radius should be automatically generated based on the emissive light brightness. Values greater than 0 override the automatic method.
Scales the emissive contribution of all materials applied to this object.
Scales the diffuse contribution of all materials applied to this object.
Fraction of samples taken that must be occluded in order to reach full occlusion.
If false, UnrealLightmass.exe is launched automatically (default) If true, it must be launched manually (e.g. through a debugger) with the -debug command line parameter.
If true, all participating Lightmass agents will report back detailed stats to the log.
If true, BSP surfaces split across model components are joined into 1 mapping
The tolerance level used when gathering BSP surfaces.
If true, Lightmass will import mappings immediately as they complete. It will not process them, however.
If true, Lightmass will process appropriate mappings as they are imported. NOTE: Requires ImmediateMode be enabled to actually work.
If true, Lightmass will sort mappings by texel cost.
If true, the generate coefficients will be dumped to binary files.
If true, Lightmass will write out BMPs for each generated material property sample to <GAME>\ScreenShots\Materials.
If true, Lightmass will pad the calculated mappings to reduce/eliminate seams.
If true, will fill padding of mappings with a color rather than the sampled edges. Means nothing if bPadMappings is not enabled...
If true, only the mapping containing a debug texel will be calculated, all others will be set to white
If true, color lightmaps a random color
If true, a green border will be placed around the edges of mappings
If true, Lightmass will overwrite lightmap data with a shade of red relating to how long it took to calculate the mapping (Red = Time / ExecutionTimeDivisor)
The amount of time that will be count as full red when bColorByExecutionTime is enabled
If true, Swarm will distribute jobs. If false, only the local machine will execute the jobs.
If true, Swarm will force content to re-export rather than using the cached version. If false, Swarm will attempt to use the cached version.
Normalized direction of the minimum translation required to fix penetration.
Distance required to move along the MTD vector (Direction).
Name of the slot.
Number of channels that are available in this slot.
Cache which Update Rate Optimization mode we are using
The bucket to use when deciding which counter to use to calculate shift values
When skipping a frame, should it be interpolated or frozen?
Whether or not to use the defined LOD/Frameskip map instead of separate distance factor thresholds
If set, LOD/Frameskip map will be queried with mesh's MinLodModel instead of current LOD (PredictedLODLevel)
(This frame) animation update should be skipped.
(This frame) animation evaluation should be skipped.
How often animation will be updated/ticked. 1 = every frame, 2 = every 2 frames, etc.
How often animation will be evaluated. 1 = every frame, 2 = every 2 frames, etc. has to be a multiple of UpdateRate.
Track time we have lost via skipping
Total time of the last series of skipped updates
The delta time of the last tick
Rate of animation evaluation when non rendered (off screen and dedicated servers). a value of 4 means evaluated 1 frame, then 3 frames skipped
Max Evaluation Rate allowed for interpolation to be enabled. Beyond, interpolation will be turned off.
Array of MaxDistanceFactor to use for AnimUpdateRate when mesh is visible (rendered). MaxDistanceFactor is size on screen, as used by LODs Example: BaseVisibleDistanceFactorThesholds.Add(0.4f) BaseVisibleDistanceFactorThesholds.Add(0.2f) means: 0 frame skip, MaxDistanceFactor > 0.4f 1 frame skip, MaxDistanceFactor > 0.2f 2 frame skip, MaxDistanceFactor > 0.0f
Map of LOD levels to frame skip amounts. if bShouldUseLodMap is set these values will be used for the frameskip amounts and the distance factor thresholds will be ignored. The flag and these values should be configured using the customization callback when parameters are created for a component.
Note that this is # of frames to skip, so if you have 20, that means every 21th frame, it will update, and evaluate.
Number of update frames that have been skipped in a row
Number of evaluate frames that have been skipped in a row
Default constructor.
Set parameters and verify inputs for Trail Mode (original behaviour - skip frames, track skipped time and then catch up afterwards).
Parameters
UpdateRateShift. Shift our update frames so that updates across all skinned components are staggered
NewUpdateRate. How often animation will be updated/ticked. 1 = every frame, 2 = every 2 frames, etc.
NewEvaluationRate. How often animation will be evaluated. 1 = every frame, 2 = every 2 frames, etc.
bNewInterpSkippedFrames. When skipping a frame, should it be interpolated or frozen?
Set parameters and verify inputs for Lookahead mode, which handles Root Motion
Parameters
UpdateRateShift. Shift our update frames so that updates across all skinned components are staggered
LookAheadAmount. Amount of time to look ahead and predict movement
Amount to interpolate bone transforms
Amount to interpoilate root motion
Return true if evaluation rate should be optimized at all
Getter for bSkipUpdate
Getter for bSkipEvaluation
Getter for bInterpolateSkippedFrames
Called when we are ticking a pose to make sure we accumulate all needed time
Returns color to use for debug UI
Location
Rotation
FOV angle
If true, degenerate triangles will be removed.
If true, normals in the raw mesh are ignored and recomputed.
If true, tangents in the raw mesh are ignored and recomputed.
If true, we will use the surface area and the corner angle of the triangle as a ratio when computing the normals.
If true, degenerate triangles will be removed.
Required to optimize mesh in mirrored transform. Double index buffer size.
If true, Tangents will be stored at 16 bit vs 8 bit precision.
If true, UVs will be stored at full floating point precision.
If true, UVs will use backwards-compatible F16 conversion with truncation for legacy meshes.
Whether to generate the distance field treating every triangle hit as a front face.
When enabled prevents the distance field from being discarded due to the mesh being open, but also lowers Distance Field AO quality.
The local scale applied when building the mesh
Scale to apply to the mesh when allocating the distance field volume texture. The default scale is 1, which is assuming that the mesh will be placed unscaled in the world.
Max Lumen mesh cards to generate for this mesh. More cards means that surface will have better coverage, but will result in increased runtime overhead. Set to 0 in order to disable mesh card generation for this mesh. Default is 12.
Default settings.
Equality operator.
Inequality.
If true, normals in the raw mesh are ignored and recomputed.
If true, tangents in the raw mesh are ignored and recomputed.
If true, degenerate triangles will be removed.
If true, we will use the surface area and the corner angle of the triangle as a ratio when computing the normals.
If true, degenerate triangles will be removed.
If true, Tangents will be stored at 16 bit vs 8 bit precision.
Use 16-bit precision for rendering skin weights, instead of 8-bit precision.
If true, UVs will be stored at full floating point precision.
If true, UVs will use backwards-compatible F16 conversion with truncation for legacy meshes.
Threshold use to decide if two vertex position are equal.
Threshold use to decide if two normal, tangents or bi-normals are equal.
Threshold use to decide if two UVs are equal.
Threshold to compare vertex position equality when computing morph target deltas.
The maximum number of bone influences to allow each vertex in this mesh to use.
If set higher than the limit determined by the project settings, it has no effect.
If set to 0, the value is taken from the DefaultBoneInfluenceLimit project setting.
Default settings.
Equality operator.
Inequality.
If true, Nanite data will be generated.
Whether to try and maintain the same surface area at all distances. Useful for foliage that thins out otherwise.
Whether to store explicit tangents instead of using the implicitly derived ones.
Whether to interpolate UVs when simplifying. Should be enabled whenever possible. For real UV coordinates this allows calculating the lowest error optimal UVs for new vertices when simplifying, assuming the UVs are used as normal texture coordinates and will interpolate across the face of the triangles.
Disable if data stored in UVs isn't valid to interpolate, for example if indexes are stored in UVs. Lerping an index doesn't make sense and would break the shader trying to use it. Note: If disabled, error from UVs is no longer accounted for when Nanite selects the LOD to render because error due to arbitrary vertex attributes that aren't interpolatable can't be generally reasoned about.
Position Precision. Step size is 2^(-PositionPrecision) cm. MIN_int32 is auto.
Normal Precision in bits. -1 is auto.
Tangent Precision in bits. -1 is auto.
Blend Weight Precision in bits. -1 is auto. 0 is rigid.
How much of the resource should always be resident (In KB). Approximate due to paging. 0: Minimum size (single page). MAX_uint32: Entire mesh.
Percentage of triangles to keep from source mesh. 1.0 = no reduction, 0.0 = no triangles.
Reduce until at least this amount of error is reached relative to size of the mesh
Whether fallback mesh should be generated.
Which heuristic to use when generating the fallback mesh.
Percentage of triangles to keep from source mesh for fallback. 1.0 = no reduction, 0.0 = no triangles.
Reduce until at least this amount of error is reached relative to size of the mesh
Controls the maximum distance allowed between each vertex of the mesh on screen. Can be used to prevent oversimplification of meshes that are intended to be deformed (e.g. animation using World Position Offset, Spline Mesh Component, etc.). Should be left at default of 0 unless explicitly needed to fix oversimplification issues.
Number of rays
UV channel used to sample displacement maps
Nanite Assembly data set up by the import
Equality operator.
Inequality operator.
Equality operator.
Inequality operator.
How large the max displacement should be, in on-screen pixels, when beginning to fade out displacement. NOTE: This should be a LARGER number than End Fade Size.
Equality operator.
Inequality operator.
If true, Ray Tracing Proxy data will be generated.
Which heuristic to use when generating the fallback mesh.
Percentage of triangles to keep from source mesh for fallback. 1.0 = no reduction, 0.0 = no triangles.
Reduce until at least this amount of error is reached relative to size of the mesh
A bias to reduce foliage over occlusion in Lumen GI. 0: no adjustment, 1: full strength.
Equality operator.
Inequality operator.
Behavior of this surface (whether we affect the walkable slope).
See also
GetWalkableSlopeBehavior(), SetWalkableSlopeBehavior()
Override walkable slope angle (in degrees), applying the rules of the Walkable Slope Behavior.
See also
GetWalkableSlopeAngle(), SetWalkableSlopeAngle()
Gets the slope override behavior.
Gets the slope angle used for the override behavior.
Set the slope override behavior.
Set the slope angle used for the override behavior.
Given a walkable floor normal Z value, either relax or restrict the value if we override such behavior.
Name of property
Name of component to use. If this is not specified the reference refers to the root component.
Path to the component from its owner actor
Allows direct setting of first component to constraint.
Extract the actual component pointer from this reference given a search actor
FBaseComponentReference == operator
Name of the collection
Types of objects that this physics objects will collide with.
Samples
Max Samples to record.
Min value to record.
Max value to record.
Auto adjust Min/Max as new values are recorded?
Record a new Sample. if bAutoAdjustMinMax is true, this new value will potentially adjust those bounds. Otherwise value will be clamped before being recorded. If MaxSamples is exceeded, old values will be deleted.
Parameters
FloatValue new sample to record.
Range between Min and Max values
Min value. This could either be the min value recorded or min value allowed depending on 'bAutoAdjustMinMax'.
Max value. This could be either the max value recorded or max value allowed depending on 'bAutoAdjustMinMax'.
Number of Samples currently recorded
Read access to Samples array
Whether to turn on the outline glow (depth field fonts only)
Base color to use for the glow
If bEnableGlow, outline glow outer radius (0 to 1, 0.5 is edge of character silhouette) glow influence will be 0 at GlowOuterRadius.X and 1 at GlowOuterRadius.Y
If bEnableGlow, outline glow inner radius (0 to 1, 0.5 is edge of character silhouette) glow influence will be 1 at GlowInnerRadius.X and 0 at GlowInnerRadius.Y
Whether to clip text
Whether to turn on shadowing
Depth field glow parameters (only usable if font was imported with a depth field)
Position of first vertex
UV of first vertex
Color of first vertex
Position of second vertex
UV of second vertex
Color of second vertex
Position of third vertex
UV of third vertex
Color of third vertex
Describes the user's activity
A game or editor activity?
Default constructor.
Creates and initializes a new instance.
Creates and initializes a new instance with a context other than the default "Game".
Definition at line 553 of file EngineTypes.h.
References BlueprintType, Category, GENERATED_BODY, and UPROPERTY.
Variable Documentation
UENUM
UENUM() enum EMaterialShadingModel ()
Specifies the overal rendering/shading model for a material.
Utility class for engine types.
Describes how often this component is allowed to move.
Types of valid physical material mask colors which may be associated with a physical material.
Specifies if an AI pawn will automatically be possessed by an AI controller.
The network role of an actor on a local/remote network context.
Enum used to indicate what type of timeline signature a function matches.
Enumerates available MobileLocalLightSetting.
Enumerates available GBufferFormats.
MegaLights Shadow type for a light component.
Ray Tracing Shadows type.
The default float precision for material's pixel shaders on mobile devices.
Deprecated rules for setting transform on attachment, new functions should use FAttachmentTransformRules isntead.
Warning
Check UMaterialInstance::Serialize if changed!
Controls where the sampler for different texture lookups comes from defines how MipValue is used Describes how to handle lighting of translucent objets Determines how the refraction offset should be computed for the material. Determines how the refraction account for the coverage with Substrate. It can only be used when Substrate is enabled. Determines how the pixel depth offset is evaluated and applied. Must match PODM_LEGACY in MaterialTemplace.ush. Enumerates available options for the translucency sort policy.
Warning
When this enum is updated please update CVarGBufferFormat comments
When this enum is updated please update CVarMobileForwardEnableLocalLights comments Controls the way that the width scale property affects animation trails. Specifies how particle collision is computed for GPU particles
Enum used to describe what type of collision is enabled on a body.
Describes if an actor can enter a low network bandwidth dormant mode Specifies which player index will pass input to this actor/component
Specifies why an actor is being deleted/removed from a level
Type of a socket on a scene component.
Keeps current relative transform as the relative transform to the new parent.
Automatically calculates the relative transform such that the attached component maintains the same world transform.
Snaps location and rotation to the attach point. Calculates the relative scale so that the final world scale of the component remains the same.
Snaps entire transform to target, including scale.
Sort based on distance from camera centerpoint to bounding sphere centerpoint. (Default, best for 3D games.)
Sort based on the post-projection Z distance to the camera.
Sort based on the projection onto a fixed axis. (Best for 2D games.)
No dynamic Global Illumination method will be used. Global Illumination can still be baked into lightmaps.
Use Lumen Global Illumination for all lights, emissive materials casting light and SkyLight Occlusion. Requires 'Generate Mesh Distance Fields' enabled for Software Ray Tracing and 'Support Hardware Ray Tracing' enabled for Hardware Ray Tracing.
Standalone Screen Space Global Illumination. Low cost, but limited by screen space information.
Use a plugin for Global Illumination
No global reflection method will be used. Reflections can still come from Reflection Captures, Planar Reflections or a Skylight placed in the level.
Use Lumen Reflections, which supports Screen / Software / Hardware Ray Tracing together and integrates with Lumen Global Illumination for rough reflections and Global Illumination seen in reflections.
Standalone Screen Space Reflections. Low cost, but limited by screen space information.
Render geometry into shadow depth maps for shadowing. Requires manual setup of shadowing distances and only culls per-component, causing poor performance with high poly scenes. Required to enable stationary baked shadows (but which is incompatible with Nanite geometry).
Render geometry into virtualized shadow depth maps for shadowing. Provides high-quality shadows for next-gen projects with simplified setup. High efficiency culling when used with Nanite.
Ray traced shadows disabled for this light
Ray traced shadows follow Cast Ray Traced Shadows project setting
Ray traced shadows enabled for this light
Recommended. Uses the default MegaLights shadow method.
Preferred method, which guarantees fixed MegaLights cost and correct area shadows, but is dependent on the BVH representation quality.
Has a significant per light cost, but can cast shadows directly from the Nanite geometry using rasterization.
Forces all GBuffers to 8 bits per channel. Intended as profiling for best performance. (Substrate: Octahedral encoding as 2x11bits for simple and single materials, 2x16bits for complex materials)
See GBuffer allocation function for layout details. (Substrate: Octahedral encoding as 2x11bits for simple and single material, 2x16bits for complex materials)
Same as Default except normals are encoded at 16 bits per channel. (Substrate: Octahedral encoding as 2x16bits for all materials.)
Forces all GBuffers to 16 bits per channel. Intended as profiling for best quality. (Substrate: Octahedral encoding as 2x16bits for all materials.)
Will not create any representation in the physics engine. Cannot be used for spatial queries (raycasts, sweeps, overlaps) or simulation (rigid body, constraints). Best performance possible (especially for moving objects)
Only used for spatial queries (raycasts, sweeps, and overlaps). Cannot be used for simulation (rigid body, constraints). Useful for character movement and things that do not need physical simulation. Performance gains by keeping data out of simulation tree.
Only used only for physics simulation (rigid body, constraints). Cannot be used for spatial queries (raycasts, sweeps, overlaps). Useful for jiggly bits on characters that do not need per bone detection. Performance gains by keeping data out of query tree
Can be used for both spatial queries (raycasts, sweeps, overlaps) and simulation (rigid body, constraints).
Only used for probing the physics simulation (rigid body, constraints). Cannot be used for spatial queries (raycasts, sweeps, overlaps). Useful for when you want to detect potential physics interactions and pass contact data to hit callbacks or contact modification, but don't want to physically react to these contacts.
Can be used for both spatial queries (raycasts, sweeps, overlaps) and probing the physics simulation (rigid body, constraints). Will not allow for actual physics interaction, but will generate contact data, trigger hit callbacks, and contacts will appear in contact modification.
When the Actor or Component is explicitly destroyed.
When the world is being unloaded for a level transition.
When the world is being unloaded because PIE is ending.
When the level it is a member of is streamed out.
When the application is being exited.
Static objects cannot be moved or changed in game.
Allows baked lighting
Fastest rendering
A stationary light will only have its shadowing and bounced lighting from static geometry baked by Lightmass, all other lighting will be dynamic.
It can change color and intensity in game.
Can't move
Allows partial baked lighting
Dynamic shadows
Movable objects can be moved and changed in game.
Totally dynamic
Can cast dynamic shadows
Slowest rendering
Not a valid socket or bone name.
Skeletal bone.
Socket.
Definition at line 720 of file EngineTypes.h.