Unreal Engine 5.6 C++ API: FSlateVertex Struct Reference
FSlateVertex Struct Reference
A struct which defines a basic vertex seen by the Slate vertex buffers and shaders.
#include "RenderingCommon.h"
Public Member Functions
FSlateVertex ()
FORCEINLINE void SetPosition (const FVector2f InPosition)
FORCEINLINE void SetTexCoords (const FVector4f InTexCoords)
Static Public Member Functions
template<ESlateVertexRounding Rounding>
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InLocalSize, float Scale, const FVector4f InTexCoords, const FColor InColor, const FColor SecondaryColor=FColor())
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InLocalSize, float Scale, const FVector4f InTexCoords, const FColor InColor, const FColor SecondaryColor=FColor(), const ESlateVertexRounding InRounding=ESlateVertexRounding::Disabled)
template<ESlateVertexRounding Rounding>
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FColor &InColor, const FColor SecondaryColor=FColor())
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FColor &InColor, const FColor SecondaryColor=FColor(), const ESlateVertexRounding InRounding=ESlateVertexRounding::Disabled)
template<ESlateVertexRounding Rounding>
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FVector2f InTexCoord2, const FColor InColor, const FColor SecondaryColor=FColor())
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FVector2f InTexCoord2, const FColor InColor, const FColor SecondaryColor=FColor(), const ESlateVertexRounding InRounding=ESlateVertexRounding::Disabled)
template<ESlateVertexRounding Rounding>
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector4f InTexCoords, const FVector2f InMaterialTexCoords, const FColor InColor, const FColor SecondaryColor=FColor())
static FORCEINLINE FSlateVertex Make (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FVector4f InTexCoords, const FVector2f InMaterialTexCoords, const FColor InColor, const FColor SecondaryColor=FColor(), const ESlateVertexRounding InRounding=ESlateVertexRounding::Disabled)
Data Fields
FColor Color
Vertex color.
FVector2f MaterialTexCoords
Texture coordinates used as pass through to materials for custom texturing.
uint16 PixelSize [2]
Local size of the element.
FVector2f Position
Position of the vertex in window space.
FColor SecondaryColor
Secondary vertex color.
float TexCoords [4]
Texture coordinates.
Private Member Functions
template<ESlateVertexRounding Rounding>
FORCEINLINE void InitCommon (const FSlateRenderTransform &RenderTransform, const FVector2f InLocalPosition, const FColor InColor, const FColor InSecondaryColor)
Detailed Description
A struct which defines a basic vertex seen by the Slate vertex buffers and shaders.
Definition at line 220 of file RenderingCommon.h.
Constructor & Destructor Documentation
FSlateVertex()
FSlateVertex::FSlateVertex () inline
Definition at line 240 of file RenderingCommon.h.
Referenced by Make(), Make(), Make(), Make(), Make(), Make(), Make(), and Make().
Member Function Documentation
InitCommon()
template<ESlateVertexRounding Rounding> FORCEINLINE void FSlateVertex::InitCommon (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FColor InColor, const FColor InSecondaryColor) inline private
Definition at line 358 of file RenderingCommon.h.
References Color, Enabled, FORCEINLINE, Position, RenderTransform, SecondaryColor, and TransformPoint().
Make() [1/8]
template<ESlateVertexRounding Rounding> FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InLocalSize, float Scale, const FVector4f InTexCoords, const FColor InColor, const FColor SecondaryColor = FColor()) inline static
Definition at line 286 of file RenderingCommon.h.
References FSlateVertex(), ensureMsgf, FORCEINLINE, RenderTransform, Scale, SecondaryColor, TEXT, Vertex, UE::Math::TVector4< T >::W, UE::Math::TVector2< T >::X, UE::Math::TVector4< T >::X, UE::Math::TVector2< T >::Y, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Make() [2/8]
FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InLocalSize, float Scale, const FVector4f InTexCoords, const FColor InColor, const FColor SecondaryColor = FColor(), const ESlateVertexRounding InRounding = ESlateVertexRounding::Disabled) inline static
Definition at line 335 of file RenderingCommon.h.
References FSlateVertex(), Disabled, Enabled, FORCEINLINE, Make(), RenderTransform, Scale, and SecondaryColor.
Make() [3/8]
template<ESlateVertexRounding Rounding> FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FColor & InColor, const FColor SecondaryColor = FColor()) inline static
Definition at line 259 of file RenderingCommon.h.
References FSlateVertex(), FORCEINLINE, RenderTransform, SecondaryColor, Vertex, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Make() [4/8]
FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FColor & InColor, const FColor SecondaryColor = FColor(), const ESlateVertexRounding InRounding = ESlateVertexRounding::Disabled) inline static
Definition at line 319 of file RenderingCommon.h.
References FSlateVertex(), Disabled, Enabled, FORCEINLINE, Make(), RenderTransform, and SecondaryColor.
Make() [5/8]
template<ESlateVertexRounding Rounding> FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FVector2f InTexCoord2, const FColor InColor, const FColor SecondaryColor = FColor()) inline static
Definition at line 246 of file RenderingCommon.h.
References FSlateVertex(), FORCEINLINE, RenderTransform, SecondaryColor, Vertex, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by Make(), Make(), Make(), and Make().
Make() [6/8]
FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector2f InTexCoord, const FVector2f InTexCoord2, const FColor InColor, const FColor SecondaryColor = FColor(), const ESlateVertexRounding InRounding = ESlateVertexRounding::Disabled) inline static
Definition at line 311 of file RenderingCommon.h.
References FSlateVertex(), Disabled, Enabled, FORCEINLINE, Make(), RenderTransform, and SecondaryColor.
Make() [7/8]
template<ESlateVertexRounding Rounding> FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector4f InTexCoords, const FVector2f InMaterialTexCoords, const FColor InColor, const FColor SecondaryColor = FColor()) inline static
Definition at line 272 of file RenderingCommon.h.
References FSlateVertex(), FORCEINLINE, RenderTransform, SecondaryColor, Vertex, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Make() [8/8]
FORCEINLINE FSlateVertex FSlateVertex::Make (const FSlateRenderTransform & RenderTransform, const FVector2f InLocalPosition, const FVector4f InTexCoords, const FVector2f InMaterialTexCoords, const FColor InColor, const FColor SecondaryColor = FColor(), const ESlateVertexRounding InRounding = ESlateVertexRounding::Disabled) inline static
Definition at line 327 of file RenderingCommon.h.
References FSlateVertex(), Disabled, Enabled, FORCEINLINE, Make(), RenderTransform, and SecondaryColor.
SetPosition()
FORCEINLINE void FSlateVertex::SetPosition (const FVector2f InPosition) inline
Definition at line 350 of file RenderingCommon.h.
References FORCEINLINE, and Position.
SetTexCoords()
FORCEINLINE void FSlateVertex::SetTexCoords (const FVector4f InTexCoords) inline
Definition at line 342 of file RenderingCommon.h.
References FORCEINLINE, TexCoords, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Field Documentation
Color
FColor FSlateVertex::Color
Vertex color.
Definition at line 232 of file RenderingCommon.h.
Referenced by InitCommon().
MaterialTexCoords
FVector2f FSlateVertex::MaterialTexCoords
Texture coordinates used as pass through to materials for custom texturing.
Definition at line 226 of file RenderingCommon.h.
PixelSize
uint16 FSlateVertex::PixelSize[2]
Local size of the element.
Definition at line 238 of file RenderingCommon.h.
Position
FVector2f FSlateVertex::Position
Position of the vertex in window space.
Definition at line 229 of file RenderingCommon.h.
Referenced by InitCommon(), and SetPosition().
SecondaryColor
FColor FSlateVertex::SecondaryColor
Secondary vertex color.
Generally used for outlines
Definition at line 235 of file RenderingCommon.h.
Referenced by InitCommon(), Make(), Make(), Make(), Make(), Make(), Make(), Make(), and Make().
TexCoords
float FSlateVertex::TexCoords[4]
Texture coordinates.
The first 2 are in xy and the 2nd are in zw
Definition at line 223 of file RenderingCommon.h.
Referenced by SetTexCoords().
The documentation for this struct was generated from the following file:
RenderingCommon.h