Unreal Engine 5.6 C++ API: TActorDescList< DescType > Class Template Reference
TActorDescList< DescType > Class Template Reference
#include "ActorDescList.h"
Data Structures
struct FActorGuidKeyFuncs
class TBaseIterator
class TConstIterator
class TIterator
Public Member Functions
TActorDescList ()
TActorDescList (const TActorDescList &)=delete
virtual ~TActorDescList ()
void AddActorDescriptor (DescType *ActorDesc)
void Empty ()
virtual FGuidActorDescMap & GetActorsByGuid () const
bool IsEmpty () const
TActorDescList & operator= (const TActorDescList &)=delete
void RemoveActorDescriptor (DescType *ActorDesc)
Protected Types
using FActorDescArray = TChunkedArray<TUniquePtr<DescType>>
using FGuidActorDescMap = TMap<FGuid, TUniquePtr<DescType>*, FDefaultSetAllocator, FActorGuidKeyFuncs>
Protected Member Functions
TUniquePtr< DescType > * GetActorDescriptor (const FGuid &ActorGuid)
const TUniquePtr< DescType > * GetActorDescriptor (const FGuid &ActorGuid) const
TUniquePtr< DescType > * GetActorDescriptorChecked (const FGuid &ActorGuid)
const TUniquePtr< DescType > * GetActorDescriptorChecked (const FGuid &ActorGuid) const
virtual FGuidActorDescMap & GetProxyActorsByGuid () const
void SetIsProxy ()
Protected Attributes
FActorDescArray ActorDescList
FGuidActorDescMap ActorsByGuid
bool bIsProxy
Friends
struct FWorldPartitionImplBase
Detailed Description
template<class DescType>
class TActorDescList< DescType >
Definition at line 20 of file ActorDescList.h.
Member Typedef Documentation
FActorDescArray
template<class DescType> using TActorDescList< DescType >::FActorDescArray = TChunkedArray<TUniquePtr<DescType>> protected
Definition at line 35 of file ActorDescList.h.
FGuidActorDescMap
template<class DescType> using TActorDescList< DescType >::FGuidActorDescMap = TMap<FGuid, TUniquePtr<DescType>*, FDefaultSetAllocator, FActorGuidKeyFuncs> protected
Definition at line 34 of file ActorDescList.h.
Constructor & Destructor Documentation
TActorDescList() [1/2]
template<class DescType> TActorDescList< DescType >::TActorDescList () inline
Definition at line 38 of file ActorDescList.h.
References bIsProxy.
Referenced by TActorDescList(), and operator=().
~TActorDescList()
template<class DescType> virtual TActorDescList< DescType >::~TActorDescList () inline virtual
Definition at line 39 of file ActorDescList.h.
TActorDescList() [2/2]
template<class DescType> TActorDescList< DescType >::TActorDescList (const TActorDescList< DescType > &) delete
References TActorDescList().
Member Function Documentation
AddActorDescriptor()
template<class DescType> void TActorDescList< DescType >::AddActorDescriptor (DescType * ActorDesc)
Definition at line 207 of file ActorDescList.h.
References ActorDescList, ActorsByGuid, bIsProxy, check, Error, FWorldPartitionActorDesc::Full, TEXT, and UE_LOG.
Empty()
template<class DescType> void TActorDescList< DescType >::Empty () inline
Definition at line 46 of file ActorDescList.h.
References ActorDescList, ActorsByGuid, bIsProxy, and check.
GetActorDescriptor() [1/2]
template<class DescType> TUniquePtr< DescType > * TActorDescList< DescType >::GetActorDescriptor (const FGuid & ActorGuid) protected
Definition at line 237 of file ActorDescList.h.
References GetProxyActorsByGuid().
GetActorDescriptor() [2/2]
template<class DescType> const TUniquePtr< DescType > * TActorDescList< DescType >::GetActorDescriptor (const FGuid & ActorGuid) const protected
Definition at line 243 of file ActorDescList.h.
References GetProxyActorsByGuid().
GetActorDescriptorChecked() [1/2]
template<class DescType> TUniquePtr< DescType > * TActorDescList< DescType >::GetActorDescriptorChecked (const FGuid & ActorGuid) protected
Definition at line 249 of file ActorDescList.h.
References GetProxyActorsByGuid().
GetActorDescriptorChecked() [2/2]
template<class DescType> const TUniquePtr< DescType > * TActorDescList< DescType >::GetActorDescriptorChecked (const FGuid & ActorGuid) const protected
Definition at line 255 of file ActorDescList.h.
References GetProxyActorsByGuid().
GetActorsByGuid()
template<class DescType> virtual FGuidActorDescMap & TActorDescList< DescType >::GetActorsByGuid () const inline virtual
Definition at line 183 of file ActorDescList.h.
References GetProxyActorsByGuid().
Referenced by TActorDescList< DescType >::TBaseIterator< false, ActorType >::TBaseIterator(), and IsEmpty().
GetProxyActorsByGuid()
template<class DescType> virtual FGuidActorDescMap & TActorDescList< DescType >::GetProxyActorsByGuid () const inline protected virtual
Definition at line 191 of file ActorDescList.h.
References ActorsByGuid.
Referenced by GetActorDescriptor(), GetActorDescriptor(), GetActorDescriptorChecked(), GetActorDescriptorChecked(), and GetActorsByGuid().
IsEmpty()
template<class DescType> bool TActorDescList< DescType >::IsEmpty () const inline
Definition at line 45 of file ActorDescList.h.
References GetActorsByGuid(), and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num().
operator=()
template<class DescType> TActorDescList & TActorDescList< DescType >::operator= (const TActorDescList< DescType > &) delete
References TActorDescList().
RemoveActorDescriptor()
template<class DescType> void TActorDescList< DescType >::RemoveActorDescriptor (DescType * ActorDesc)
Definition at line 225 of file ActorDescList.h.
References ActorsByGuid, bIsProxy, check, ensure, Error, FWorldPartitionActorDesc::Full, TEXT, and UE_LOG.
SetIsProxy()
template<class DescType> void TActorDescList< DescType >::SetIsProxy () inline protected
Definition at line 185 of file ActorDescList.h.
References ActorsByGuid, bIsProxy, and check.
Friends And Related Symbol Documentation
FWorldPartitionImplBase
template<class DescType> friend struct FWorldPartitionImplBase friend
Definition at line 23 of file ActorDescList.h.
References FWorldPartitionImplBase.
Referenced by FWorldPartitionImplBase.
Field Documentation
ActorDescList
template<class DescType> FActorDescArray TActorDescList< DescType >::ActorDescList protected
Definition at line 199 of file ActorDescList.h.
Referenced by AddActorDescriptor(), and Empty().
ActorsByGuid
template<class DescType> FGuidActorDescMap TActorDescList< DescType >::ActorsByGuid protected
Definition at line 200 of file ActorDescList.h.
Referenced by AddActorDescriptor(), Empty(), GetProxyActorsByGuid(), RemoveActorDescriptor(), and SetIsProxy().
bIsProxy
template<class DescType> bool TActorDescList< DescType >::bIsProxy protected
Definition at line 201 of file ActorDescList.h.
Referenced by TActorDescList(), AddActorDescriptor(), Empty(), RemoveActorDescriptor(), and SetIsProxy().
The documentation for this class was generated from the following file:
ActorDescList.h