Unreal Engine 5.6 C++ API: SMInstanceElementDataUtil Namespace Reference
SMInstanceElementDataUtil Namespace Reference
Functions
FSMInstanceManager GetSMInstanceFromHandle (const FTypedElementHandle &InHandle, const bool bSilent=false)
Attempt to get the static mesh instance ID from the given element handle.
FSMInstanceManager GetSMInstanceFromHandleChecked (const FTypedElementHandle &InHandle)
Attempt to get the static mesh instance ID from the given element handle, asserting if the element handle doesn't contain FSMInstanceElementData.
ISMInstanceManager * GetSMInstanceManager (const FSMInstanceId &InstanceId)
Get the static mesh instance manager for the given instance.
template<typename ElementHandleType>
TArray< FSMInstanceManager > GetSMInstancesFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent=false)
Attempt to get the static mesh instance IDs from the given element handles.
template<typename ElementHandleType>
TArray< FSMInstanceManager > GetSMInstancesFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the static mesh instance IDs from the given element handles, asserting if any element handle doesn't contain FSMInstanceElementData, and skipping any that don't resolve to a valid FSMInstanceManager.
FSimpleMulticastDelegate & OnSMInstanceElementsEnabledChanged ()
bool SMInstanceElementsEnabled ()
Test whether static mesh instance elements are currently enabled?
Function Documentation
GetSMInstanceFromHandle()
FSMInstanceManager SMInstanceElementDataUtil::GetSMInstanceFromHandle (const FTypedElementHandle & InHandle, const bool bSilent = false)
Attempt to get the static mesh instance ID from the given element handle.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The static mesh instance ID if the element handle contains FSMInstanceElementData which resolved to a valid FSMInstanceManager, otherwise an invalid ID.
Referenced by GetSMInstancesFromHandles().
GetSMInstanceFromHandleChecked()
FSMInstanceManager SMInstanceElementDataUtil::GetSMInstanceFromHandleChecked (const FTypedElementHandle & InHandle)
Attempt to get the static mesh instance ID from the given element handle, asserting if the element handle doesn't contain FSMInstanceElementData.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The static mesh instance ID, or an invalid ID if the FSMInstanceElementData didn't resolve to a valid FSMInstanceManager.
Referenced by GetSMInstancesFromHandlesChecked().
GetSMInstanceManager()
ISMInstanceManager * SMInstanceElementDataUtil::GetSMInstanceManager (const FSMInstanceId & InstanceId)
Get the static mesh instance manager for the given instance.
Returns
The static mesh instance manager, or null if this instance cannot be managed.
GetSMInstancesFromHandles()
template<typename ElementHandleType> TArray< FSMInstanceManager > SMInstanceElementDataUtil::GetSMInstancesFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent = false)
Attempt to get the static mesh instance IDs from the given element handles.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The static mesh instance IDs of any element handles that contain FSMInstanceElementData which resolves to a valid FSMInstanceManager, skipping any that don't.
Definition at line 67 of file SMInstanceElementData.h.
References TArray< InElementType, InAllocatorType >::Add(), GetSMInstanceFromHandle(), Handle, MoveTemp(), TArrayView< InElementType, InSizeType >::Num(), and TArray< InElementType, InAllocatorType >::Reserve().
GetSMInstancesFromHandlesChecked()
template<typename ElementHandleType> TArray< FSMInstanceManager > SMInstanceElementDataUtil::GetSMInstancesFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the static mesh instance IDs from the given element handles, asserting if any element handle doesn't contain FSMInstanceElementData, and skipping any that don't resolve to a valid FSMInstanceManager.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The static mesh instance IDs.
Definition at line 89 of file SMInstanceElementData.h.
References TArray< InElementType, InAllocatorType >::Add(), GetSMInstanceFromHandleChecked(), Handle, MoveTemp(), TArrayView< InElementType, InSizeType >::Num(), and TArray< InElementType, InAllocatorType >::Reserve().
OnSMInstanceElementsEnabledChanged()
FSimpleMulticastDelegate & SMInstanceElementDataUtil::OnSMInstanceElementsEnabledChanged ()
SMInstanceElementsEnabled()
bool SMInstanceElementDataUtil::SMInstanceElementsEnabled ()
Test whether static mesh instance elements are currently enabled?
Note
Controlled by the CVar: "TypedElements.EnableSMInstanceElements".