Unreal Engine 5.6 C++ API: RenderResource.h File Reference
RenderResource.h File Reference
#include "RHIFwd.h"
#include "RHIShaderPlatform.h"
#include "RHIFeatureLevel.h"
#include "RenderTimer.h"
#include "CoreGlobals.h"
Data Structures
class FBufferWithRDG
class FIndexBuffer
An index buffer resource.
struct FMipBiasFade
Functionality for fading in/out texture mip-levels.
struct FMipFadeSettings
Mip fade settings, selectable by chosing a different EMipFadeSettings.
class FRenderResource
A rendering resource which is owned by the rendering thread.
class FTexture
A textures resource.
class FTextureReference
A texture reference resource.
class FTextureWithSRV
A textures resource that includes an SRV.
class FVertexBuffer
A vertex buffer resource.
class FVertexBufferWithSRV
class TGlobalResource< ResourceType, InInitPhase >
Used to declare a render resource that is initialized/released by static initialization/destruction.
Enumerations
enum EMipFadeSettings { MipFade_Normal = 0 , MipFade_Slow , MipFade_NumSettings }
enum class ERayTracingMode : uint8 { Disabled , Enabled , Dynamic }
enum class ERenderResourceState : uint8 { Default , BatchReleased , Deleted }
Functions
void BeginInitResource (FName OwnerName, FRenderResource *Resource, FRenderCommandPipe *RenderCommandPipe=nullptr)
RENDERCORE_API void BeginInitResource (FRenderResource *Resource, FRenderCommandPipe *RenderCommandPipe=nullptr)
Sends a message to the rendering thread to initialize a resource.
RENDERCORE_API void BeginReleaseResource (FRenderResource *Resource, FRenderCommandPipe *RenderCommandPipe=nullptr)
Sends a message to the rendering thread to release a resource.
RENDERCORE_API void BeginUpdateResourceRHI (FRenderResource *Resource, FRenderCommandPipe *RenderCommandPipe=nullptr)
Sends a message to the rendering thread to update a resource.
RENDERCORE_API void EndBatchedRelease ()
Disables the batching of calls to BeginReleaseResource This is called in the game thread.
RENDERCORE_API void ReleaseResourceAndFlush (FRenderResource *Resource)
Sends a message to the rendering thread to release a resource, and spins until the rendering thread has processed the message.
RENDERCORE_API void StartBatchedRelease ()
Enables the batching of calls to BeginReleaseResource This is called in the game thread.
Variables
RENDERCORE_API float GEnableMipLevelFading
Whether to enable mip-level fading or not: +1.0f if enabled, -1.0f if disabled.
RENDERCORE_API FMipFadeSettings GMipFadeSettings [MipFade_NumSettings]
Global mip fading settings, indexed by EMipFadeSettings.
Enumeration Type Documentation
EMipFadeSettings
enum EMipFadeSettings
Enumerator
MipFade_Normal
MipFade_Slow
MipFade_NumSettings
Definition at line 256 of file RenderResource.h.
ERayTracingMode
enum class ERayTracingMode : uint8 strong
Enumerator
Disabled
Enabled
Dynamic
Definition at line 26 of file RenderResource.h.
ERenderResourceState
enum class ERenderResourceState : uint8 strong
Enumerator
Default
BatchReleased
Deleted
Definition at line 19 of file RenderResource.h.
Function Documentation
BeginInitResource() [1/2]
void BeginInitResource (FName OwnerName, FRenderResource * Resource, FRenderCommandPipe * RenderCommandPipe = nullptr) inline
Definition at line 217 of file RenderResource.h.
References BeginInitResource(), and FRenderResource::SetOwnerName().
BeginInitResource() [2/2]
RENDERCORE_API void BeginInitResource (FRenderResource * Resource, FRenderCommandPipe * RenderCommandPipe = nullptr) extern
Sends a message to the rendering thread to initialize a resource.
This is called in the game thread.
Referenced by TStaticStateRHI< InitializerType, RHIRefType, RHIParamRefType >::FStaticStateResource::FStaticStateResource(), BeginInitResource(), and TGlobalResource< FGlobalBoundShaderStateResource >::InitGlobalResource().
BeginReleaseResource()
RENDERCORE_API void BeginReleaseResource (FRenderResource * Resource, FRenderCommandPipe * RenderCommandPipe = nullptr) extern
Sends a message to the rendering thread to release a resource.
This is called in the game thread.
BeginUpdateResourceRHI()
RENDERCORE_API void BeginUpdateResourceRHI (FRenderResource * Resource, FRenderCommandPipe * RenderCommandPipe = nullptr) extern
Sends a message to the rendering thread to update a resource.
This is called in the game thread.
Referenced by FGeometryCollectionVertexFactory::Copy(), and FSplineMeshVertexFactory::Copy().
EndBatchedRelease()
RENDERCORE_API void EndBatchedRelease () extern
Disables the batching of calls to BeginReleaseResource This is called in the game thread.
ReleaseResourceAndFlush()
RENDERCORE_API void ReleaseResourceAndFlush (FRenderResource * Resource) extern
Sends a message to the rendering thread to release a resource, and spins until the rendering thread has processed the message.
This is called in the game thread.
StartBatchedRelease()
RENDERCORE_API void StartBatchedRelease () extern
Enables the batching of calls to BeginReleaseResource This is called in the game thread.
Variable Documentation
GEnableMipLevelFading
RENDERCORE_API float GEnableMipLevelFading extern
Whether to enable mip-level fading or not: +1.0f if enabled, -1.0f if disabled.
Referenced by FMipBiasFade::CalcMipBias().
GMipFadeSettings
RENDERCORE_API FMipFadeSettings GMipFadeSettings[MipFade_NumSettings] extern
Global mip fading settings, indexed by EMipFadeSettings.