Unreal Engine 5.6 C++ API: DataReplication.h File Reference
DataReplication.h File Reference
#include "CoreMinimal.h"
#include "Misc/NetworkGuid.h"
#include "UObject/CoreNet.h"
#include "Engine/EngineTypes.h"
#include "UObject/UnrealType.h"
#include "UObject/GCObject.h"
#include "HAL/LowLevelMemTracker.h"
Data Structures
class FObjectReplicator
Represents an object that is currently being replicated or handling RPCs.
struct FObjectReplicator::FRPCCallInfo
struct FObjectReplicator::FRPCPendingLocalCall
struct FReplicatedActorProperty
struct containing property and offset for replicated actor properties
class FScopedActorRoleSwap
Functions
bool FORCEINLINE IsCustomDeltaProperty (const FProperty *Property)
bool FORCEINLINE IsCustomDeltaProperty (const FStructProperty *StructProperty)
LLM_DECLARE_TAG_API (NetObjReplicator, 1)
Function Documentation
IsCustomDeltaProperty() [1/2]
bool FORCEINLINE IsCustomDeltaProperty (const FProperty * Property)
Definition at line 34 of file DataReplication.h.
References CastField(), FORCEINLINE, IsCustomDeltaProperty(), Property, and StructProperty.
IsCustomDeltaProperty() [2/2]
bool FORCEINLINE IsCustomDeltaProperty (const FStructProperty * StructProperty)
Definition at line 29 of file DataReplication.h.
References EnumHasAnyFlags(), FORCEINLINE, STRUCT_NetDeltaSerializeNative, and StructProperty.
Referenced by IsCustomDeltaProperty().
LLM_DECLARE_TAG_API()
LLM_DECLARE_TAG_API (NetObjReplicator , 1)