Unreal Engine 5.6 C++ API: Metasound::MetasoundLiteralIntrinsics Namespace Reference
Metasound::MetasoundLiteralIntrinsics Namespace Reference
Data Structures
struct TLiteralDefaultValueFromDecayed
struct TLiteralDefaultValueFromDecayed< ArgType >
struct TLiteralDefaultValueFromDecayed< FLiteral::FNone >
struct TLiteralDefaultValueFromDecayed< FString >
struct TLiteralDefaultValueFromDecayed< TArray< ElementType > >
struct TLiteralDefaultValueFromDecayed< TArray< TSharedPtr< Audio::IProxyData > > >
struct TLiteralDefaultValueFromDecayed< TSharedPtr< Audio::IProxyData > >
Functions
template<typename... ArgTypes>
ELiteralType GetLiteralArgTypeFromDecayed ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< bool > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< float > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< FString > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< int32 > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< bool > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< FLiteral::FNone > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< float > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< FString > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< int32 > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TArray< TSharedPtr< Audio::IProxyData > > > ()
template<>
FORCEINLINE ELiteralType GetLiteralArgTypeFromDecayed< TSharedPtr< Audio::IProxyData > > ()
Function Documentation
GetLiteralArgTypeFromDecayed() [1/2]
template<typename... ArgTypes> ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed ()
Definition at line 168 of file MetasoundLiteral.h.
References Metasound::Invalid.
Referenced by Metasound::TLiteralTypeInfo< ArgType >::GetLiteralArgTypeEnum(), Metasound::TLiteralTypeInfo<>::GetLiteralArgTypeEnum(), GetLiteralArgTypeFromDecayed< TArray< bool > >(), GetLiteralArgTypeFromDecayed< TArray< FLiteral::FNone > >(), GetLiteralArgTypeFromDecayed< TArray< float > >(), GetLiteralArgTypeFromDecayed< TArray< FString > >(), GetLiteralArgTypeFromDecayed< TArray< int32 > >(), GetLiteralArgTypeFromDecayed< TArray< TSharedPtr< Audio::IProxyData > > >(), and GetLiteralArgTypeFromDecayed< TSharedPtr< Audio::IProxyData > >().
GetLiteralArgTypeFromDecayed() [2/2]
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed ()
Definition at line 174 of file MetasoundLiteral.h.
References checkNoEntry, FORCEINLINE, and Metasound::None.
GetLiteralArgTypeFromDecayed< bool >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< bool > ()
Definition at line 181 of file MetasoundLiteral.h.
References Metasound::Boolean, and FORCEINLINE.
GetLiteralArgTypeFromDecayed< float >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< float > ()
Definition at line 193 of file MetasoundLiteral.h.
References Metasound::Float, and FORCEINLINE.
GetLiteralArgTypeFromDecayed< FString >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< FString > ()
Definition at line 199 of file MetasoundLiteral.h.
References FORCEINLINE, and Metasound::String.
GetLiteralArgTypeFromDecayed< int32 >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< int32 > ()
Definition at line 187 of file MetasoundLiteral.h.
References FORCEINLINE, and Metasound::Integer.
GetLiteralArgTypeFromDecayed< TArray< bool > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< bool > > ()
Definition at line 217 of file MetasoundLiteral.h.
References Metasound::BooleanArray, FORCEINLINE, and GetLiteralArgTypeFromDecayed().
GetLiteralArgTypeFromDecayed< TArray< FLiteral::FNone > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< FLiteral::FNone > > ()
Definition at line 211 of file MetasoundLiteral.h.
References FORCEINLINE, GetLiteralArgTypeFromDecayed(), and Metasound::NoneArray.
GetLiteralArgTypeFromDecayed< TArray< float > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< float > > ()
Definition at line 229 of file MetasoundLiteral.h.
References Metasound::FloatArray, FORCEINLINE, and GetLiteralArgTypeFromDecayed().
GetLiteralArgTypeFromDecayed< TArray< FString > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< FString > > ()
Definition at line 235 of file MetasoundLiteral.h.
References FORCEINLINE, GetLiteralArgTypeFromDecayed(), and Metasound::StringArray.
GetLiteralArgTypeFromDecayed< TArray< int32 > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< int32 > > ()
Definition at line 223 of file MetasoundLiteral.h.
References FORCEINLINE, GetLiteralArgTypeFromDecayed(), and Metasound::IntegerArray.
GetLiteralArgTypeFromDecayed< TArray< TSharedPtr< Audio::IProxyData > > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TArray< TSharedPtr< Audio::IProxyData > > > ()
Definition at line 241 of file MetasoundLiteral.h.
References FORCEINLINE, GetLiteralArgTypeFromDecayed(), and Metasound::UObjectProxyArray.
GetLiteralArgTypeFromDecayed< TSharedPtr< Audio::IProxyData > >()
template<> FORCEINLINE ELiteralType Metasound::MetasoundLiteralIntrinsics::GetLiteralArgTypeFromDecayed< TSharedPtr< Audio::IProxyData > > ()
Definition at line 205 of file MetasoundLiteral.h.
References FORCEINLINE, GetLiteralArgTypeFromDecayed(), and Metasound::UObjectProxy.