Unreal Engine 5.6 C++ API: FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType > Class Template Reference
FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType > Class Template Reference final
#include "SkeletalMeshUpdater.h"
Public Member Functions
TBackend ()
Private Member Functions
TUniquePtr< FSkeletalMeshUpdatePacket > CreatePacket () const override
void Replay (FRHICommandList &RHICmdList, FSkeletalMeshUpdateChannel &Channel, FSkeletalMeshUpdatePacket &Packet) const override
Private Member Functions inherited from FSkeletalMeshUpdateChannel::FBackend
FBackend ()
virtual ~FBackend ()
Private Member Functions inherited from TIntrusiveDoubleLinkedListNode< FBackend >
TIntrusiveDoubleLinkedListNode ()
FORCEINLINE ElementType * GetNext () const
FORCEINLINE ElementType * GetPrev () const
FORCEINLINE void InsertAfter (ElementType *NewPrev)
Insert this node after the specified node.
FORCEINLINE void InsertBefore (ElementType *NewNext)
Insert this node before the specified node.
FORCEINLINE bool IsInList () const
FORCEINLINE void Remove ()
Removes this element from the list in constant time.
FORCEINLINE void Reset ()
FORCEINLINE ElementType * GetThisElement ()
Static Private Member Functions
static int32 GetGlobalListIndex ()
static TBackend * GetInstance ()
Static Private Member Functions inherited from FSkeletalMeshUpdateChannel::FBackend
static FGlobalList & GetGlobalList ()
Private Attributes
friend FSkeletalMeshUpdateChannel
Private Attributes inherited from FSkeletalMeshUpdateChannel::FBackend
int32 GlobalListIndex = INDEX_NONE
Private Attributes inherited from TIntrusiveDoubleLinkedListNode< FBackend >
ElementType * Next
ElementType * Prev
Static Private Attributes
static TBackend * Instance = nullptr
Additional Inherited Members
Private Types inherited from TIntrusiveDoubleLinkedListNode< FBackend >
using ElementType
using NodeType
Detailed Description
template<typename SkeletalMeshUpdatePacketType>
class FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >
Definition at line 428 of file SkeletalMeshUpdater.h.
Constructor & Destructor Documentation
TBackend()
template<typename SkeletalMeshUpdatePacketType> FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::TBackend () inline
Definition at line 431 of file SkeletalMeshUpdater.h.
References checkf, Instance, and TEXT.
Referenced by GetInstance().
Member Function Documentation
CreatePacket()
template<typename SkeletalMeshUpdatePacketType> TUniquePtr< FSkeletalMeshUpdatePacket > FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::CreatePacket () const inline override private virtual
Implements FSkeletalMeshUpdateChannel::FBackend.
Definition at line 451 of file SkeletalMeshUpdater.h.
GetGlobalListIndex()
template<typename SkeletalMeshUpdatePacketType> int32 FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::GetGlobalListIndex () inline static private
Definition at line 440 of file SkeletalMeshUpdater.h.
References checkf, Instance, and TEXT.
GetInstance()
template<typename SkeletalMeshUpdatePacketType> TBackend * FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::GetInstance () inline static private
Definition at line 446 of file SkeletalMeshUpdater.h.
References TBackend(), and Instance.
Replay()
template<typename SkeletalMeshUpdatePacketType> void FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::Replay (FRHICommandList & RHICmdList, FSkeletalMeshUpdateChannel & Channel, FSkeletalMeshUpdatePacket & Packet) const inline override private virtual
Implements FSkeletalMeshUpdateChannel::FBackend.
Definition at line 456 of file SkeletalMeshUpdater.h.
References FSkeletalMeshUpdateChannel, and FSkeletalMeshUpdateChannel::Replay().
Field Documentation
FSkeletalMeshUpdateChannel
template<typename SkeletalMeshUpdatePacketType> friend FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::FSkeletalMeshUpdateChannel private
Definition at line 461 of file SkeletalMeshUpdater.h.
Referenced by Replay().
Instance
template<typename SkeletalMeshUpdatePacketType> FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType > * FSkeletalMeshUpdateChannel::TBackend< SkeletalMeshUpdatePacketType >::Instance = nullptr static private
Definition at line 438 of file SkeletalMeshUpdater.h.
Referenced by TBackend(), GetGlobalListIndex(), and GetInstance().
The documentation for this class was generated from the following file:
SkeletalMeshUpdater.h