Unreal Engine 5.6 C++ API: TFutureBase< ResultType > Class Template Reference
TFutureBase< ResultType > Class Template Reference
Abstract base template for futures and shared futures.
#include "Future.h"
Public Types
using ConstResultType = typename StateType::ConstResultType
using MutableResultType = typename StateType::MutableResultType
using RvalueResultType = typename StateType::RvalueResultType
Public Member Functions
ConstResultType Get () const UE_LIFETIMEBOUND
Gets the future's result.
bool IsReady () const
Checks whether this future object has its value set.
bool IsValid () const
Checks whether this future object has a valid state.
void Wait () const
Blocks the calling thread until the future result is available.
bool WaitFor (const FTimespan &Duration) const
Blocks the calling thread until the future result is available or the specified duration is exceeded.
bool WaitUntil (const FDateTime &Time) const
Blocks the calling thread until the future result is available or the specified time is hit.
Protected Types
using StateType = TFutureState<ResultType>
Protected Member Functions
TFutureBase ()=default
Default constructor.
TFutureBase (const TSharedPtr< StateType > &InState)
TFutureBase (TSharedPtr< StateType > &&InState)
Creates and initializes a new instance.
const TSharedPtr< StateType > & GetState () const
Gets the shared state object.
template<typename Func>
auto Next (Func Continuation)
Convenience wrapper for Then that set a completion callback that will be called once the future completes or immediately if already completed.
void Reset ()
Reset the future.
template<typename Func>
auto Then (Func Continuation)
Set a completion callback that will be called once the future completes or immediately if already completed.
Private Attributes
TSharedPtr< StateType > State
Holds the future's state.
Detailed Description
template<typename ResultType>
class TFutureBase< ResultType >
Abstract base template for futures and shared futures.
Definition at line 224 of file Future.h.
Member Typedef Documentation
ConstResultType
template<typename ResultType> using TFutureBase< ResultType >::ConstResultType = typename StateType::ConstResultType
Definition at line 231 of file Future.h.
MutableResultType
template<typename ResultType> using TFutureBase< ResultType >::MutableResultType = typename StateType::MutableResultType
Definition at line 230 of file Future.h.
RvalueResultType
template<typename ResultType> using TFutureBase< ResultType >::RvalueResultType = typename StateType::RvalueResultType
Definition at line 232 of file Future.h.
StateType
template<typename ResultType> using TFutureBase< ResultType >::StateType = TFutureState<ResultType> protected
Definition at line 227 of file Future.h.
Constructor & Destructor Documentation
TFutureBase() [1/3]
template<typename ResultType> TFutureBase< ResultType >::TFutureBase () protected default
Default constructor.
TFutureBase() [2/3]
template<typename ResultType> TFutureBase< ResultType >::TFutureBase (TSharedPtr< StateType > && InState) inline protected
Creates and initializes a new instance.
Parameters
InState The shared state to initialize with.
Definition at line 330 of file Future.h.
References MoveTemp(), and State.
TFutureBase() [3/3]
template<typename ResultType> TFutureBase< ResultType >::TFutureBase (const TSharedPtr< StateType > & InState) inline protected
Definition at line 334 of file Future.h.
References State.
Member Function Documentation
Get()
template<typename ResultType> ConstResultType TFutureBase< ResultType >::Get () const inline
Gets the future's result.
Returns
The result as a const reference, or the same reference if the future holds a reference, or void if the future holds a void.
Note
Not equivalent to std::future::get(). The future remains valid.
Definition at line 241 of file Future.h.
References GetState(), and UE_LIFETIMEBOUND.
Referenced by TSharedFuture< ResultType >::Get(), and TFuture< ResultType >::GetMutable().
GetState()
template<typename ResultType> const TSharedPtr< StateType > & TFutureBase< ResultType >::GetState () const inline protected
Gets the shared state object.
Returns
The shared state object.
Definition at line 344 of file Future.h.
References check, and State.
Referenced by Get().
IsReady()
template<typename ResultType> bool TFutureBase< ResultType >::IsReady () const inline
Checks whether this future object has its value set.
Returns
true if this future has a shared state and the value has been set, false otherwise.
See also
IsValid
Definition at line 264 of file Future.h.
References State.
IsValid()
template<typename ResultType> bool TFutureBase< ResultType >::IsValid () const inline
Checks whether this future object has a valid state.
Returns
true if the state is valid, false otherwise.
See also
IsReady
Definition at line 275 of file Future.h.
References State.
Referenced by Reset().
Next()
template<typename ResultType> template<typename Func> auto TFutureBase< ResultType >::Next (Func Continuation) protected
Convenience wrapper for Then that set a completion callback that will be called once the future completes or immediately if already completed.
Parameters
Continuation a continuation taking an argument of type ResultType
Returns
nothing at the moment but could return another future to allow future chaining
Definition at line 740 of file Future.h.
References MoveTemp(), Self, Then(), TModels_V, and UE_STATIC_DEPRECATE.
Reset()
template<typename ResultType> void TFutureBase< ResultType >::Reset () inline protected
Reset the future.
Resetting a future removes any continuation from its shared state and invalidates it. Useful for discarding yet to be completed future cleanly.
Definition at line 379 of file Future.h.
References IsValid(), and State.
Then()
template<typename ResultType> template<typename Func> auto TFutureBase< ResultType >::Then (Func Continuation) protected
Set a completion callback that will be called once the future completes or immediately if already completed.
Parameters
Continuation a continuation taking an argument of type TFuture<ResultType>
Returns
nothing at the moment but could return another future to allow future chaining
Definition at line 719 of file Future.h.
References check, TPromise< ResultType >::GetFuture(), IsValid(), MoveTemp(), FutureDetail::SetPromiseValue(), and State.
Referenced by Next().
Wait()
template<typename ResultType> void TFutureBase< ResultType >::Wait () const inline
Blocks the calling thread until the future result is available.
Note that this method may block forever if the result is never set. Use the WaitFor or WaitUntil methods to specify a maximum timeout for the wait.
See also
WaitFor, WaitUntil
Definition at line 288 of file Future.h.
References FTimespan::MaxValue(), State, and WaitFor().
WaitFor()
template<typename ResultType> bool TFutureBase< ResultType >::WaitFor (const FTimespan & Duration) const inline
Blocks the calling thread until the future result is available or the specified duration is exceeded.
Parameters
Duration The maximum time span to wait for the future result.
Returns
true if the result is available, false otherwise.
See also
Wait, WaitUntil
Definition at line 303 of file Future.h.
References Duration, and State.
Referenced by Wait(), and WaitUntil().
WaitUntil()
template<typename ResultType> bool TFutureBase< ResultType >::WaitUntil (const FDateTime & Time) const inline
Blocks the calling thread until the future result is available or the specified time is hit.
Parameters
Time The time until to wait for the future result (in UTC).
Returns
true if the result is available, false otherwise.
See also
Wait, WaitUntil
Definition at line 315 of file Future.h.
References Time, FDateTime::UtcNow(), and WaitFor().
Field Documentation
State
template<typename ResultType> TSharedPtr<StateType> TFutureBase< ResultType >::State private
Holds the future's state.
Definition at line 391 of file Future.h.
Referenced by TFutureBase(), TFutureBase(), GetState(), IsReady(), IsValid(), Reset(), Then(), Wait(), and WaitFor().
The documentation for this class was generated from the following file:
Future.h