Unreal Engine 5.6 C++ API: FQuartzSubscriptionToken Class Reference
FQuartzSubscriptionToken Class Reference
#include "QuartzSubscriptionToken.h"
Public Member Functions
FQuartzSubscriptionToken ()
~FQuartzSubscriptionToken ()
TSharedPtr< FQuartzTickableObjectsManager > GetTickableObjectManager ()
bool IsSubscribed () const
void Subscribe (FQuartzTickableObject *Subscriber, UQuartzSubsystem *QuartzSubsystem)
void Unsubscribe ()
Private Attributes
FQuartzTickableObject * SubscribingObject
TWeakPtr< FQuartzTickableObjectsManager > TickableObjectManagerPtr
Detailed Description
Definition at line 10 of file QuartzSubscriptionToken.h.
Constructor & Destructor Documentation
FQuartzSubscriptionToken()
FQuartzSubscriptionToken::FQuartzSubscriptionToken ()
Definition at line 8 of file QuartzSubscriptionToken.cpp.
References SubscribingObject.
~FQuartzSubscriptionToken()
FQuartzSubscriptionToken::~FQuartzSubscriptionToken ()
Definition at line 12 of file QuartzSubscriptionToken.cpp.
References Unsubscribe().
Member Function Documentation
GetTickableObjectManager()
TSharedPtr< FQuartzTickableObjectsManager > FQuartzSubscriptionToken::GetTickableObjectManager ()
Definition at line 67 of file QuartzSubscriptionToken.cpp.
References TickableObjectManagerPtr.
Referenced by Subscribe(), and Unsubscribe().
IsSubscribed()
bool FQuartzSubscriptionToken::IsSubscribed () const
Definition at line 73 of file QuartzSubscriptionToken.cpp.
References TickableObjectManagerPtr.
Referenced by Subscribe().
Subscribe()
void FQuartzSubscriptionToken::Subscribe (FQuartzTickableObject * Subscriber, UQuartzSubsystem * QuartzSubsystem)
Definition at line 17 of file QuartzSubscriptionToken.cpp.
References ensure, Error, GetTickableObjectManager(), IsSubscribed(), TSharedPtr< ObjectType, InMode >::IsValid(), SubscribingObject, TEXT, TickableObjectManagerPtr, UE_LOG, and Warning.
Unsubscribe()
void FQuartzSubscriptionToken::Unsubscribe ()
Definition at line 55 of file QuartzSubscriptionToken.cpp.
References GetTickableObjectManager(), TSharedPtr< ObjectType, InMode >::IsValid(), SubscribingObject, and TickableObjectManagerPtr.
Referenced by ~FQuartzSubscriptionToken().
Field Documentation
SubscribingObject
FQuartzTickableObject* FQuartzSubscriptionToken::SubscribingObject private
Definition at line 23 of file QuartzSubscriptionToken.h.
Referenced by FQuartzSubscriptionToken(), Subscribe(), and Unsubscribe().
TickableObjectManagerPtr
TWeakPtr<FQuartzTickableObjectsManager> FQuartzSubscriptionToken::TickableObjectManagerPtr private
Definition at line 24 of file QuartzSubscriptionToken.h.
Referenced by GetTickableObjectManager(), IsSubscribed(), Subscribe(), and Unsubscribe().
The documentation for this class was generated from the following files:
QuartzSubscriptionToken.h
QuartzSubscriptionToken.cpp