Unreal Engine 5.6 C++ API: UE::Graph::FMappingManyToOne Struct Reference
UE::Graph::FMappingManyToOne Struct Reference
Represents a mapping between two graphs where each vertex in a source graph maps to exactly one vertex in a target graph.
#include "GraphConvert.h"
Public Member Functions
FMappingManyToOne ()=default
FMappingManyToOne (const FMappingManyToOne &)=default
FMappingManyToOne (FMappingManyToOne &&)=default
SIZE_T GetAllocatedSize () const
FMappingManyToOne & operator= (const FMappingManyToOne &)=default
FMappingManyToOne & operator= (FMappingManyToOne &&)=default
Data Fields
TArray< FVertex > Mapping
Detailed Description
Represents a mapping between two graphs where each vertex in a source graph maps to exactly one vertex in a target graph.
The mapping is not bidirectionally one-to-one. The length of Mapping is the number of vertices in the source graph and each value is a vertex in the target graph. e.g. a mapping from the vertices in a cyclic graph to the vertices in its condensation graph.
Definition at line 84 of file GraphConvert.h.
Constructor & Destructor Documentation
FMappingManyToOne() [1/3]
UE::Graph::FMappingManyToOne::FMappingManyToOne () default
Referenced by FMappingManyToOne(), FMappingManyToOne(), operator=(), and operator=().
FMappingManyToOne() [2/3]
UE::Graph::FMappingManyToOne::FMappingManyToOne (const FMappingManyToOne &) default
References FMappingManyToOne().
FMappingManyToOne() [3/3]
UE::Graph::FMappingManyToOne::FMappingManyToOne (FMappingManyToOne &&) default
References FMappingManyToOne().
Member Function Documentation
GetAllocatedSize()
SIZE_T UE::Graph::FMappingManyToOne::GetAllocatedSize () const inline
Definition at line 94 of file GraphConvert.h.
References Mapping.
operator=() [1/2]
FMappingManyToOne & UE::Graph::FMappingManyToOne::operator= (const FMappingManyToOne &) default
References FMappingManyToOne().
operator=() [2/2]
FMappingManyToOne & UE::Graph::FMappingManyToOne::operator= (FMappingManyToOne &&) default
References FMappingManyToOne().
Field Documentation
Mapping
TArray<FVertex> UE::Graph::FMappingManyToOne::Mapping
Definition at line 86 of file GraphConvert.h.
Referenced by GetAllocatedSize().
The documentation for this struct was generated from the following file:
GraphConvert.h