Unreal Engine 5.6 C++ API: UE::Modeling Namespace Reference
UE::Modeling Namespace Reference
Functions
MODELINGCOMPONENTS_API FCreateMaterialObjectResult CreateMaterialObject (UInteractiveToolManager *ToolManager, FCreateMaterialObjectParams &&CreateMaterialParams)
Create a new material object based on the data in CreateMaterialParams.
MODELINGCOMPONENTS_API FCreateMeshObjectResult CreateMeshObject (UInteractiveToolManager *ToolManager, FCreateMeshObjectParams &&CreateMeshParams)
Create a new mesh object based on the data in CreateMeshParams.
MODELINGCOMPONENTS_API FCreateActorResult CreateNewActor (UInteractiveToolManager *ToolManager, FCreateActorParams &&CreateActorParams)
Create a new actor based on the data in CreateActorParams.
MODELINGCOMPONENTS_API FCreateComponentResult CreateNewComponentOnActor (UInteractiveToolManager *ToolManager, FCreateComponentParams &&CreateComponentParams)
Create a new component on an actor based on the data in CreateComponentParams.
MODELINGCOMPONENTS_API FCreateTextureObjectResult CreateTextureObject (UInteractiveToolManager *ToolManager, FCreateTextureObjectParams &&CreateTexParams)
Create a new texture object based on the data in CreateTexParams.
MODELINGCOMPONENTS_API FString GenerateRandomShortHexString (int32 NumChars=8)
Generate a N-letter GUID string that contains only hex digits, and contains at least one letter and one number.
MODELINGCOMPONENTS_API FString GetComponentAssetBaseName (UActorComponent *Component, bool bRemoveAutoGeneratedSuffixes=true)
Look up the name for the Asset underlying the given Component, if there is one.
MODELINGCOMPONENTS_API FString StripGeneratedAssetSuffixFromName (FString InputName)
Strip the appended auto-generated _UUID suffix on the given string, if we can detect one.
Function Documentation
CreateMaterialObject()
MODELINGCOMPONENTS_API FCreateMaterialObjectResult UE::Modeling::CreateMaterialObject (UInteractiveToolManager * ToolManager, FCreateMaterialObjectParams && CreateMaterialParams)
Create a new material object based on the data in CreateMaterialParams.
This is a convenience function that will try to locate a UModelingObjectsCreationAPI instance in the ToolManager's ContextObjectStore, and then call UModelingObjectsCreationAPI::CreateMaterialObject()
Returns
a results data structure, containing a result code and information about any new objects created
References CreateMaterialObject().
Referenced by CreateMaterialObject().
CreateMeshObject()
MODELINGCOMPONENTS_API FCreateMeshObjectResult UE::Modeling::CreateMeshObject (UInteractiveToolManager * ToolManager, FCreateMeshObjectParams && CreateMeshParams)
Create a new mesh object based on the data in CreateMeshParams.
This is a convenience function that will try to locate a UModelingObjectsCreationAPI instance in the ToolManager's ContextObjectStore, and then call UModelingObjectsCreationAPI::CreateMeshObject()
Returns
a results data structure, containing a result code and information about any new objects created
References CreateMeshObject().
Referenced by CreateMeshObject().
CreateNewActor()
MODELINGCOMPONENTS_API FCreateActorResult UE::Modeling::CreateNewActor (UInteractiveToolManager * ToolManager, FCreateActorParams && CreateActorParams)
Create a new actor based on the data in CreateActorParams.
This is a convenience function that will try to locate a UModelingObjectsCreationAPI instance in the ToolManager's ContextObjectStore, and then call UModelingObjectsCreationAPI::CreateNewActor()
Returns
a results data structure, containing a result code and information about any new objects created
References CreateNewActor().
Referenced by CreateNewActor().
CreateNewComponentOnActor()
MODELINGCOMPONENTS_API FCreateComponentResult UE::Modeling::CreateNewComponentOnActor (UInteractiveToolManager * ToolManager, FCreateComponentParams && CreateComponentParams)
Create a new component on an actor based on the data in CreateComponentParams.
This is a convenience function that will try to locate a UModelingObjectsCreationAPI instance in the ToolManager's ContextObjectStore, and then call UModelingObjectsCreationAPI::CreateNewComponentOnActor()
Returns
a results data structure, containing a result code and information about any new objects created
References CreateNewComponentOnActor().
Referenced by CreateNewComponentOnActor().
CreateTextureObject()
MODELINGCOMPONENTS_API FCreateTextureObjectResult UE::Modeling::CreateTextureObject (UInteractiveToolManager * ToolManager, FCreateTextureObjectParams && CreateTexParams)
Create a new texture object based on the data in CreateTexParams.
This is a convenience function that will try to locate a UModelingObjectsCreationAPI instance in the ToolManager's ContextObjectStore, and then call UModelingObjectsCreationAPI::CreateTextureObject()
Returns
a results data structure, containing a result code and information about any new objects created
References CreateTextureObject().
Referenced by CreateTextureObject().
GenerateRandomShortHexString()
MODELINGCOMPONENTS_API FString UE::Modeling::GenerateRandomShortHexString (int32 NumChars = 8)
Generate a N-letter GUID string that contains only hex digits, and contains at least one letter and one number.
Used to create _UUID suffixes for making asset names unique, etc.
References GenerateRandomShortHexString().
Referenced by GenerateRandomShortHexString().
GetComponentAssetBaseName()
MODELINGCOMPONENTS_API FString UE::Modeling::GetComponentAssetBaseName (UActorComponent * Component, bool bRemoveAutoGeneratedSuffixes = true)
Look up the name for the Asset underlying the given Component, if there is one.
Optionally Strip off the appended auto-generated UUID string if we can detect one. If there is not a known underlying asset, returns the Component's name
Parameters
Component the Component we want the Asset Base Name for
bRemoveAutoGeneratedSuffixes strip off generated UUID suffix if one is detected (default true)
Returns
the Name for the Component
References Component, and GetComponentAssetBaseName().
Referenced by GetComponentAssetBaseName().
StripGeneratedAssetSuffixFromName()
MODELINGCOMPONENTS_API FString UE::Modeling::StripGeneratedAssetSuffixFromName (FString InputName)
Strip the appended auto-generated _UUID suffix on the given string, if we can detect one.
Parameters
InputName input string that may have _UUID suffix
Returns
InputName without _UUID suffix
References StripGeneratedAssetSuffixFromName().
Referenced by StripGeneratedAssetSuffixFromName().