Unreal Engine 5.6 C++ API: FCompositeBuffer Class Reference
FCompositeBuffer Class Reference
FCompositeBuffer is a non-contiguous buffer composed of zero or more immutable shared buffers.
#include "CompositeBuffer.h"
Public Member Functions
template<typename... BufferTypes, std::enable_if_t< std::conjunction_v< CanAppendBufferType< std::decay_t< BufferTypes > >... > > * = nullptr>
FCompositeBuffer (BufferTypes &&... Buffers)
Construct a composite buffer by concatenating the buffers.
void CopyTo (FMutableMemoryView Target, uint64 Offset=0) const
Copies a range of the buffer to a contiguous region of memory.
bool EqualBytes (const FCompositeBuffer &Other) const
Returns true if the bytes of this buffer are equal to the bytes of the other buffer.
TConstArrayView< FSharedBuffer > GetSegments () const
Returns the segments that the buffer is composed from.
uint64 GetSize () const
Returns the total size of the composite buffer in bytes.
bool IsNull () const
Returns true if the composite buffer is null.
bool IsOwned () const
Returns true if every segment in the composite buffer is owned.
void IterateRange (uint64 Offset, uint64 Size, TFunctionRef< void(FMemoryView View)> Visitor) const
Invokes a visitor with a view of each segment that intersects with a range.
void IterateRange (uint64 Offset, uint64 Size, TFunctionRef< void(FMemoryView View, const FSharedBuffer &ViewOuter)> Visitor) const
FCompositeBuffer MakeOwned () &&
FCompositeBuffer MakeOwned () const &
Returns a copy of the buffer where every segment is owned.
FCompositeBuffer Mid (uint64 Offset, uint64 Size=MAX_uint64) const
Returns the middle part of the buffer by taking the size starting at the offset.
operator bool () const
Returns true if the composite buffer is not null.
void Reset ()
Reset this to null.
FSharedBuffer ToShared () &&
FSharedBuffer ToShared () const &
Returns the concatenation of the segments into a contiguous buffer.
FMemoryView ViewOrCopyRange (uint64 Offset, uint64 Size, FUniqueBuffer &CopyBuffer) const
Returns a view of the range if contained by one segment, otherwise a view of a copy of the range.
FMemoryView ViewOrCopyRange (uint64 Offset, uint64 Size, FUniqueBuffer &CopyBuffer, TFunctionRef< FUniqueBuffer(uint64 Size)> Allocator) const
Static Public Attributes
static const FCompositeBuffer Null
A null composite buffer.
Private Types
template<typename BufferType>
using CanAppendBufferType
Private Member Functions
template<typename BufferType, decltype(std::declval< TArray< FSharedBuffer > >().Append(std::declval< BufferType >())) * = nullptr>
void AppendBuffers (BufferType &&Buffer)
void AppendBuffers (const FCompositeBuffer &Buffer)
void AppendBuffers (const FSharedBuffer &Buffer)
void AppendBuffers (FCompositeBuffer &&Buffer)
void AppendBuffers (FSharedBuffer &&Buffer)
Static Private Member Functions
template<typename BufferType, decltype(std::declval< TArray< FSharedBuffer > >().Append(std::declval< BufferType >())) * = nullptr>
static int32 GetBufferCount (BufferType &&Buffer)
static int32 GetBufferCount (const FCompositeBuffer &Buffer)
static int32 GetBufferCount (const FSharedBuffer &Buffer)
Private Attributes
TArray< FSharedBuffer, TInlineAllocator< 1 > > Segments
Detailed Description
FCompositeBuffer is a non-contiguous buffer composed of zero or more immutable shared buffers.
A composite buffer is most efficient when its segments are consumed as they are, but it can be flattened into a contiguous buffer when necessary, by calling ToShared(). Ownership of segment buffers is not changed on construction, but if ownership of segments is required then that can be guaranteed by calling MakeOwned().
Definition at line 26 of file CompositeBuffer.h.
Member Typedef Documentation
CanAppendBufferType
template<typename BufferType> using FCompositeBuffer::CanAppendBufferType private
Initial value:
 std::bool_constant<
        std::is_same_v<FCompositeBuffer, BufferType> ||
        std::is_same_v<FSharedBuffer, BufferType> ||
        TIsTArray_V<BufferType>>
Definition at line 29 of file CompositeBuffer.h.
Constructor & Destructor Documentation
FCompositeBuffer()
template<typename... BufferTypes, std::enable_if_t< std::conjunction_v< CanAppendBufferType< std::decay_t< BufferTypes > >... > > * = nullptr> FCompositeBuffer::FCompositeBuffer (BufferTypes &&... Buffers) inline explicit
Construct a composite buffer by concatenating the buffers.
Does not enforce ownership.
Buffer parameters may be FSharedBuffer, FCompositeBuffer, or TArray<FSharedBuffer>.
Definition at line 42 of file CompositeBuffer.h.
References AppendBuffers(), Forward(), GetBufferCount(), FSharedBuffer::IsNull(), and Segments.
Referenced by AppendBuffers(), AppendBuffers(), EqualBytes(), GetBufferCount(), MakeOwned(), MakeOwned(), and Mid().
Member Function Documentation
AppendBuffers() [1/5]
template<typename BufferType, decltype(std::declval< TArray< FSharedBuffer > >().Append(std::declval< BufferType >())) * = nullptr> void FCompositeBuffer::AppendBuffers (BufferType && Buffer) inline private
Definition at line 139 of file CompositeBuffer.h.
References Buffer, Forward(), and Segments.
AppendBuffers() [2/5]
void FCompositeBuffer::AppendBuffers (const FCompositeBuffer & Buffer) inline private
Definition at line 129 of file CompositeBuffer.h.
References FCompositeBuffer(), Buffer, and Segments.
Referenced by FCompositeBuffer().
AppendBuffers() [3/5]
void FCompositeBuffer::AppendBuffers (const FSharedBuffer & Buffer) inline private
Definition at line 133 of file CompositeBuffer.h.
References Buffer, and Segments.
AppendBuffers() [4/5]
void FCompositeBuffer::AppendBuffers (FCompositeBuffer && Buffer) inline private
Definition at line 130 of file CompositeBuffer.h.
References FCompositeBuffer(), Buffer, MoveTemp(), and Segments.
AppendBuffers() [5/5]
void FCompositeBuffer::AppendBuffers (FSharedBuffer && Buffer) inline private
Definition at line 134 of file CompositeBuffer.h.
References Buffer, MoveTemp(), and Segments.
CopyTo()
void FCompositeBuffer::CopyTo (FMutableMemoryView Target, uint64 Offset = 0) const
Copies a range of the buffer to a contiguous region of memory.
Parameters
Target The view to copy to. Must be no larger than the data available at the offset.
Offset The byte offset in this buffer to start copying from.
References CopyTo(), and Target.
Referenced by CopyTo().
EqualBytes()
bool FCompositeBuffer::EqualBytes (const FCompositeBuffer & Other) const nodiscard
Returns true if the bytes of this buffer are equal to the bytes of the other buffer.
References FCompositeBuffer(), EqualBytes(), and Other.
Referenced by EqualBytes().
GetBufferCount() [1/3]
template<typename BufferType, decltype(std::declval< TArray< FSharedBuffer > >().Append(std::declval< BufferType >())) * = nullptr> int32 FCompositeBuffer::GetBufferCount (BufferType && Buffer) inline static private
Definition at line 137 of file CompositeBuffer.h.
References Buffer, and GetNum().
GetBufferCount() [2/3]
int32 FCompositeBuffer::GetBufferCount (const FCompositeBuffer & Buffer) inline static private
Definition at line 128 of file CompositeBuffer.h.
References FCompositeBuffer(), Buffer, and GetBufferCount().
Referenced by FCompositeBuffer(), and GetBufferCount().
GetBufferCount() [3/3]
int32 FCompositeBuffer::GetBufferCount (const FSharedBuffer & Buffer) inline static private
Definition at line 132 of file CompositeBuffer.h.
References Buffer.
GetSegments()
TConstArrayView< FSharedBuffer > FCompositeBuffer::GetSegments () const inline nodiscard
Returns the segments that the buffer is composed from.
Definition at line 59 of file CompositeBuffer.h.
References Segments.
Referenced by FShaderCodeResource::PopulateFromComposite().
GetSize()
uint64 FCompositeBuffer::GetSize () const nodiscard
Returns the total size of the composite buffer in bytes.
IsNull()
bool FCompositeBuffer::IsNull () const inline nodiscard
Returns true if the composite buffer is null.
Definition at line 65 of file CompositeBuffer.h.
References Segments.
Referenced by FCbAttachment::FCbAttachment(), and operator bool().
IsOwned()
bool FCompositeBuffer::IsOwned () const nodiscard
Returns true if every segment in the composite buffer is owned.
IterateRange() [1/2]
void FCompositeBuffer::IterateRange (uint64 Offset, uint64 Size, TFunctionRef< void(FMemoryView View)> Visitor) const
Invokes a visitor with a view of each segment that intersects with a range.
Parameters
Offset The byte offset in this buffer to start visiting from.
Size The number of bytes in the range to visit.
Visitor The visitor to invoke from zero to GetSegments().Num() times.
References IterateRange(), and TSequenceHistory< HistorySize >::Size.
Referenced by IterateRange(), and IterateRange().
IterateRange() [2/2]
void FCompositeBuffer::IterateRange (uint64 Offset, uint64 Size, TFunctionRef< void(FMemoryView View, const FSharedBuffer &ViewOuter)> Visitor) const
References IterateRange(), and TSequenceHistory< HistorySize >::Size.
MakeOwned() [1/2]
FCompositeBuffer FCompositeBuffer::MakeOwned () && nodiscard
References FCompositeBuffer(), and MakeOwned().
MakeOwned() [2/2]
FCompositeBuffer FCompositeBuffer::MakeOwned () const & nodiscard
Returns a copy of the buffer where every segment is owned.
References FCompositeBuffer().
Referenced by MakeOwned().
Mid()
FCompositeBuffer FCompositeBuffer::Mid (uint64 Offset, uint64 Size = MAX_uint64) const nodiscard
Returns the middle part of the buffer by taking the size starting at the offset.
References FCompositeBuffer(), MAX_uint64, Mid(), and TSequenceHistory< HistorySize >::Size.
Referenced by Mid().
operator bool()
FCompositeBuffer::operator bool () const inline explicit nodiscard
Returns true if the composite buffer is not null.
Definition at line 62 of file CompositeBuffer.h.
References IsNull().
Reset()
void FCompositeBuffer::Reset ()
Reset this to null.
ToShared() [1/2]
FSharedBuffer FCompositeBuffer::ToShared () && nodiscard
References ToShared().
ToShared() [2/2]
FSharedBuffer FCompositeBuffer::ToShared () const & nodiscard
Returns the concatenation of the segments into a contiguous buffer.
References ToShared().
Referenced by ToShared(), and ToShared().
ViewOrCopyRange() [1/2]
FMemoryView FCompositeBuffer::ViewOrCopyRange (uint64 Offset, uint64 Size, FUniqueBuffer & CopyBuffer) const nodiscard
Returns a view of the range if contained by one segment, otherwise a view of a copy of the range.
Note
CopyBuffer is reused if large enough, and otherwise allocated when needed.
Parameters
Offset The byte offset in this buffer that the range starts at.
Size The number of bytes in the range to view or copy.
CopyBuffer The buffer to write the copy into if a copy is required.
Allocator The optional allocator to use when the copy buffer is required.
References TSequenceHistory< HistorySize >::Size, and ViewOrCopyRange().
Referenced by ViewOrCopyRange(), and ViewOrCopyRange().
ViewOrCopyRange() [2/2]
FMemoryView FCompositeBuffer::ViewOrCopyRange (uint64 Offset, uint64 Size, FUniqueBuffer & CopyBuffer, TFunctionRef< FUniqueBuffer(uint64 Size)> Allocator) const nodiscard
References Allocator, TSequenceHistory< HistorySize >::Size, and ViewOrCopyRange().
Field Documentation
Null
const FCompositeBuffer FCompositeBuffer::Null inline static
A null composite buffer.
Definition at line 125 of file CompositeBuffer.h.
Referenced by FCbAttachment::AsCompositeBinary().
Segments
TArray<FSharedBuffer, TInlineAllocator<1> > FCompositeBuffer::Segments private
Definition at line 142 of file CompositeBuffer.h.
Referenced by FCompositeBuffer(), AppendBuffers(), AppendBuffers(), AppendBuffers(), AppendBuffers(), AppendBuffers(), GetSegments(), and IsNull().
The documentation for this class was generated from the following file:
CompositeBuffer.h