Unreal Engine 5.6 C++ API: FLandscapeComponentDataInterfaceBase Struct Reference
FLandscapeComponentDataInterfaceBase Struct Reference
#include "LandscapeDataAccess.h"
Public Member Functions
FLandscapeComponentDataInterfaceBase ()
LANDSCAPE_API FLandscapeComponentDataInterfaceBase (ULandscapeComponent *InComponent, int32 InMipLevel, bool InWorkOnEditingLayer=true)
void ComponentXYToSubsectionXY (int32 CompX, int32 CompY, int32 &SubNumX, int32 &SubNumY, int32 &SubX, int32 &SubY) const
int32 GetComponentSizeVerts () const
uint16 GetHeight (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
const FColor * GetHeightData (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
float GetLocalHeight (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
void GetLocalTangentVectors (int32 LocalX, int32 LocalY, FVector &LocalTangentX, FVector &LocalTangentY, FVector &LocalTangentZ, const TArray< FColor > &HeightAndNormals) const
FVector GetLocalVertex (int32 LocalX, int32 LocalY, const TArray< FColor > &HeightAndNormals) const
float GetScaleFactor () const
void QuadIndexToXY (int32 QuadIndex, int32 &OutX, int32 &OutY) const
int32 TexelXYToIndex (int32 TexelX, int32 TexelY) const
int32 VertexIndexToTexel (int32 VertexIndex) const
void VertexIndexToXY (int32 VertexIndex, int32 &OutX, int32 &OutY) const
int32 VertexXYToIndex (int32 VertX, int32 VertY) const
void VertexXYToTexelXY (int32 VertX, int32 VertY, int32 &OutX, int32 &OutY) const
Data Fields
int32 HeightmapComponentOffsetX = 0
int32 HeightmapComponentOffsetY = 0
int32 HeightmapStride = 0
int32 HeightmapSubsectionOffset = 0
const int32 MipLevel = 0
Protected Attributes
int32 ComponentNumSubsections = 0
int32 ComponentSizeQuads = 0
int32 ComponentSizeVerts = 0
int32 SubsectionSizeVerts = 0
Detailed Description
Definition at line 134 of file LandscapeDataAccess.h.
Constructor & Destructor Documentation
FLandscapeComponentDataInterfaceBase() [1/2]
FLandscapeComponentDataInterfaceBase::FLandscapeComponentDataInterfaceBase () inline
Definition at line 136 of file LandscapeDataAccess.h.
FLandscapeComponentDataInterfaceBase() [2/2]
LANDSCAPE_API FLandscapeComponentDataInterfaceBase::FLandscapeComponentDataInterfaceBase (ULandscapeComponent * InComponent, int32 InMipLevel, bool InWorkOnEditingLayer = true)
Member Function Documentation
ComponentXYToSubsectionXY()
void FLandscapeComponentDataInterfaceBase::ComponentXYToSubsectionXY (int32 CompX, int32 CompY, int32 & SubNumX, int32 & SubNumY, int32 & SubX, int32 & SubY) const inline
Definition at line 164 of file LandscapeDataAccess.h.
References SubsectionSizeVerts.
Referenced by VertexXYToTexelXY().
GetComponentSizeVerts()
int32 FLandscapeComponentDataInterfaceBase::GetComponentSizeVerts () const inline
Definition at line 255 of file LandscapeDataAccess.h.
References ComponentSizeVerts.
GetHeight()
uint16 FLandscapeComponentDataInterfaceBase::GetHeight (int32 LocalX, int32 LocalY, const TArray< FColor > & HeightAndNormals) const inline
Definition at line 211 of file LandscapeDataAccess.h.
References FColor::G, GetHeightData(), and FColor::R.
Referenced by GetLocalHeight(), and GetLocalVertex().
GetHeightData()
const FColor * FLandscapeComponentDataInterfaceBase::GetHeightData (int32 LocalX, int32 LocalY, const TArray< FColor > & HeightAndNormals) const inline
Definition at line 234 of file LandscapeDataAccess.h.
References check, ComponentSizeVerts, HeightmapComponentOffsetX, HeightmapComponentOffsetY, HeightmapStride, and VertexXYToTexelXY().
Referenced by GetHeight(), and GetLocalTangentVectors().
GetLocalHeight()
float FLandscapeComponentDataInterfaceBase::GetLocalHeight (int32 LocalX, int32 LocalY, const TArray< FColor > & HeightAndNormals) const inline
Definition at line 229 of file LandscapeDataAccess.h.
References GetHeight(), and LandscapeDataAccess::GetLocalHeight().
GetLocalTangentVectors()
void FLandscapeComponentDataInterfaceBase::GetLocalTangentVectors (int32 LocalX, int32 LocalY, FVector & LocalTangentX, FVector & LocalTangentY, FVector & LocalTangentZ, const TArray< FColor > & HeightAndNormals) const inline
Definition at line 246 of file LandscapeDataAccess.h.
References FVector, GetHeightData(), LandscapeDataAccess::UnpackNormal(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetLocalVertex()
FVector FLandscapeComponentDataInterfaceBase::GetLocalVertex (int32 LocalX, int32 LocalY, const TArray< FColor > & HeightAndNormals) const inline
Definition at line 222 of file LandscapeDataAccess.h.
References FVector, GetHeight(), LandscapeDataAccess::GetLocalHeight(), and GetScaleFactor().
GetScaleFactor()
float FLandscapeComponentDataInterfaceBase::GetScaleFactor () const inline
Definition at line 217 of file LandscapeDataAccess.h.
References ComponentSizeQuads, ComponentSizeVerts, and float.
Referenced by GetLocalVertex().
QuadIndexToXY()
void FLandscapeComponentDataInterfaceBase::QuadIndexToXY (int32 QuadIndex, int32 & OutX, int32 & OutY) const inline
Definition at line 150 of file LandscapeDataAccess.h.
References ComponentSizeVerts.
TexelXYToIndex()
int32 FLandscapeComponentDataInterfaceBase::TexelXYToIndex (int32 TexelX, int32 TexelY) const inline
Definition at line 206 of file LandscapeDataAccess.h.
References ComponentNumSubsections, and SubsectionSizeVerts.
Referenced by VertexIndexToTexel().
VertexIndexToTexel()
int32 FLandscapeComponentDataInterfaceBase::VertexIndexToTexel (int32 VertexIndex) const inline
Definition at line 197 of file LandscapeDataAccess.h.
References TexelXYToIndex(), VertexIndexToXY(), and VertexXYToTexelXY().
VertexIndexToXY()
void FLandscapeComponentDataInterfaceBase::VertexIndexToXY (int32 VertexIndex, int32 & OutX, int32 & OutY) const inline
Definition at line 140 of file LandscapeDataAccess.h.
References ComponentSizeVerts.
Referenced by FLandscapeComponentDataInterface::GetHeight(), FLandscapeComponentDataInterface::GetLocalTangentVectors(), FLandscapeComponentDataInterface::GetLocalVertex(), FLandscapeComponentDataInterface::GetWorldPositionTangents(), FLandscapeComponentDataInterface::GetWorldTangentVectors(), FLandscapeComponentDataInterface::GetWorldVertex(), FLandscapeComponentDataInterface::GetXYOffset(), and VertexIndexToTexel().
VertexXYToIndex()
int32 FLandscapeComponentDataInterfaceBase::VertexXYToIndex (int32 VertX, int32 VertY) const inline
Definition at line 159 of file LandscapeDataAccess.h.
References ComponentSizeVerts.
VertexXYToTexelXY()
void FLandscapeComponentDataInterfaceBase::VertexXYToTexelXY (int32 VertX, int32 VertY, int32 & OutX, int32 & OutY) const inline
Definition at line 188 of file LandscapeDataAccess.h.
References ComponentXYToSubsectionXY(), and SubsectionSizeVerts.
Referenced by FLandscapeComponentDataInterface::GetHeightData(), GetHeightData(), and VertexIndexToTexel().
Field Documentation
ComponentNumSubsections
int32 FLandscapeComponentDataInterfaceBase::ComponentNumSubsections = 0 protected
Definition at line 269 of file LandscapeDataAccess.h.
Referenced by TexelXYToIndex().
ComponentSizeQuads
int32 FLandscapeComponentDataInterfaceBase::ComponentSizeQuads = 0 protected
Definition at line 266 of file LandscapeDataAccess.h.
Referenced by GetScaleFactor().
ComponentSizeVerts
int32 FLandscapeComponentDataInterfaceBase::ComponentSizeVerts = 0 protected
Definition at line 267 of file LandscapeDataAccess.h.
Referenced by GetComponentSizeVerts(), FLandscapeComponentDataInterface::GetHeightData(), GetHeightData(), GetScaleFactor(), QuadIndexToXY(), VertexIndexToXY(), and VertexXYToIndex().
HeightmapComponentOffsetX
int32 FLandscapeComponentDataInterfaceBase::HeightmapComponentOffsetX = 0
Definition at line 260 of file LandscapeDataAccess.h.
Referenced by FLandscapeComponentDataInterface::GetHeightData(), and GetHeightData().
HeightmapComponentOffsetY
int32 FLandscapeComponentDataInterfaceBase::HeightmapComponentOffsetY = 0
Definition at line 261 of file LandscapeDataAccess.h.
Referenced by FLandscapeComponentDataInterface::GetHeightData(), and GetHeightData().
HeightmapStride
int32 FLandscapeComponentDataInterfaceBase::HeightmapStride = 0
Definition at line 259 of file LandscapeDataAccess.h.
Referenced by FLandscapeComponentDataInterface::GetHeightData(), and GetHeightData().
HeightmapSubsectionOffset
int32 FLandscapeComponentDataInterfaceBase::HeightmapSubsectionOffset = 0
Definition at line 262 of file LandscapeDataAccess.h.
MipLevel
const int32 FLandscapeComponentDataInterfaceBase::MipLevel = 0
Definition at line 263 of file LandscapeDataAccess.h.
SubsectionSizeVerts
int32 FLandscapeComponentDataInterfaceBase::SubsectionSizeVerts = 0 protected
Definition at line 268 of file LandscapeDataAccess.h.
Referenced by ComponentXYToSubsectionXY(), TexelXYToIndex(), and VertexXYToTexelXY().
The documentation for this struct was generated from the following file:
LandscapeDataAccess.h