Unreal Engine 5.6 C++ API: ANavigationObjectBase Class Reference
ANavigationObjectBase Class Reference
#include "NavigationObjectBase.h"
Public Member Functions
virtual void FindBase ()
class UBillboardComponent * GetBadSprite () const
Returns BadSprite subobject.
class UCapsuleComponent * GetCapsuleComponent () const
Returns CapsuleComponent subobject.
class UBillboardComponent * GetGoodSprite () const
Returns GoodSprite subobject.
virtual void GetMoveGoalReachTest (const AActor *MovingActor, const FVector &MoveOffset, FVector &GoalOffset, float &GoalRadius, float &GoalHalfHeight) const override
Get cylinder for testing if actor has been reached.
virtual FVector GetNavAgentLocation () const override
class APhysicsVolume * GetNavPhysicsVolume ()
Return Physics Volume for this Actor.
virtual UPROPERTY() uint32 bIsPIEPlayerStart void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const override
True if this nav point was spawned to be a PIE player start.
virtual void PostEditMove (bool bFinished) override
virtual void PostEditUndo () override
virtual bool ShouldBeBased ()
virtual void Validate ()
Check to make sure the navigation is at a valid point.
Private Member Functions
UPROPERTY () TObjectPtr< class UBillboardComponent > BadSprite
Used to draw bad collision intersection in editor.
GENERATED_UCLASS_BODY() private UPROPERTY () TObjectPtr< class UBillboardComponent > GoodSprite
Normal editor sprite.
Detailed Description
Definition at line 13 of file NavigationObjectBase.h.
Member Function Documentation
FindBase()
virtual void ANavigationObjectBase::FindBase () virtual
Todo
document
GetBadSprite()
class UBillboardComponent * ANavigationObjectBase::GetBadSprite () const inline
Returns BadSprite subobject.
Definition at line 70 of file NavigationObjectBase.h.
GetCapsuleComponent()
class UCapsuleComponent * ANavigationObjectBase::GetCapsuleComponent () const inline
Returns CapsuleComponent subobject.
Definition at line 66 of file NavigationObjectBase.h.
GetGoodSprite()
class UBillboardComponent * ANavigationObjectBase::GetGoodSprite () const inline
Returns GoodSprite subobject.
Definition at line 68 of file NavigationObjectBase.h.
GetMoveGoalReachTest()
virtual void ANavigationObjectBase::GetMoveGoalReachTest (const AActor * MovingActor, const FVector & MoveOffset, FVector & GoalOffset, float & GoalRadius, float & GoalHalfHeight) const override virtual
Get cylinder for testing if actor has been reached.
Parameters
MoveOffset - destination (relative to actor's nav location)
GoalOffset - cylinder center (relative to actor's nav location)
GoalRadius - cylinder radius
GoalHalfHeight - cylinder half height
Reimplemented from INavAgentInterface.
References FVector, INavAgentInterface::GoalOffset, INavAgentInterface::GoalRadius, and INavAgentInterface::MoveOffset.
GetNavAgentLocation()
virtual FVector ANavigationObjectBase::GetNavAgentLocation () const inline override virtual
Definition at line 60 of file NavigationObjectBase.h.
References FVector.
GetNavPhysicsVolume()
class APhysicsVolume * ANavigationObjectBase::GetNavPhysicsVolume ()
Return Physics Volume for this Actor.
GetSimpleCollisionCylinder()
virtual UPROPERTY() uint32 bIsPIEPlayerStart void ANavigationObjectBase::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const override virtual
True if this nav point was spawned to be a PIE player start.
References INavAgentInterface::const, and GetSimpleCollisionCylinder().
Referenced by GetSimpleCollisionCylinder().
PostEditMove()
virtual void ANavigationObjectBase::PostEditMove (bool bFinished) override virtual
PostEditUndo()
virtual void ANavigationObjectBase::PostEditUndo () override virtual
ShouldBeBased()
virtual bool ANavigationObjectBase::ShouldBeBased () virtual
Todo
document
UPROPERTY() [1/2]
ANavigationObjectBase::UPROPERTY () private
Used to draw bad collision intersection in editor.
References UPROPERTY().
UPROPERTY() [2/2]
GENERATED_UCLASS_BODY() private ANavigationObjectBase::UPROPERTY () private
Normal editor sprite.
Referenced by UPROPERTY().
Validate()
virtual void ANavigationObjectBase::Validate () virtual
Check to make sure the navigation is at a valid point.
Detect when path building is going to move a pathnode around This may be undesirable for LDs (ie b/c cover links define slots by offsets)
The documentation for this class was generated from the following file:
NavigationObjectBase.h