Unreal Engine 5.6 C++ API: FRemoteServerId Struct Reference
FRemoteServerId Struct Reference
#include "RemoteObjectTypes.h"
Public Member Functions
FRemoteServerId ()=default
FRemoteServerId (const FString &InText)
FRemoteServerId (ERemoteServerIdConstants InId)
FRemoteServerId (uint32 InId)
uint32 GetIdNumber () const
bool IsAsset () const
bool IsDatabase () const
bool IsValid () const
bool operator!= (FRemoteServerId Other) const
bool operator< (FRemoteServerId Other) const
bool operator<= (FRemoteServerId Other) const
void operator= (FRemoteServerId Other)
bool operator== (FRemoteServerId Other) const
FString ToString () const
Private Member Functions
FRemoteServerId (uint32 InId, ERemoteServerIdConstants)
Constructor used exclusively by FRemoteObjectId::GetServerId() to bypass range changes in the other constructors.
Private Attributes
uint32 Id = (uint32)ERemoteServerIdConstants::Invalid
Friends
struct FRemoteObjectId
FArchive & operator<< (FArchive &Ar, FRemoteServerId &Id)
Detailed Description
Definition at line 30 of file RemoteObjectTypes.h.
Constructor & Destructor Documentation
FRemoteServerId() [1/5]
FRemoteServerId::FRemoteServerId () default
Referenced by operator!=(), operator<(), operator<<, operator<=(), operator=(), and operator==().
FRemoteServerId() [2/5]
FRemoteServerId::FRemoteServerId (ERemoteServerIdConstants InId) inline explicit
Definition at line 35 of file RemoteObjectTypes.h.
References Id.
FRemoteServerId() [3/5]
FRemoteServerId::FRemoteServerId (uint32 InId) inline explicit
Definition at line 39 of file RemoteObjectTypes.h.
References checkf, FirstReserved, Id, and TEXT.
FRemoteServerId() [4/5]
FRemoteServerId::FRemoteServerId (const FString & InText) explicit
FRemoteServerId() [5/5]
FRemoteServerId::FRemoteServerId (uint32 InId, ERemoteServerIdConstants) inline private
Constructor used exclusively by FRemoteObjectId::GetServerId() to bypass range changes in the other constructors.
Definition at line 91 of file RemoteObjectTypes.h.
References Id.
Member Function Documentation
GetIdNumber()
uint32 FRemoteServerId::GetIdNumber () const inline
Definition at line 47 of file RemoteObjectTypes.h.
References Id.
IsAsset()
bool FRemoteServerId::IsAsset () const inline
Definition at line 75 of file RemoteObjectTypes.h.
References Asset, and Id.
Referenced by FRemoteObjectId::IsAsset().
IsDatabase()
bool FRemoteServerId::IsDatabase () const inline
Definition at line 79 of file RemoteObjectTypes.h.
References Database, and Id.
IsValid()
bool FRemoteServerId::IsValid () const inline
Definition at line 51 of file RemoteObjectTypes.h.
References Id.
Referenced by FRemoteWorkPriority::IsValid().
operator!=()
bool FRemoteServerId::operator!= (FRemoteServerId Other) const inline
Definition at line 59 of file RemoteObjectTypes.h.
References FRemoteServerId(), Id, and Other.
operator<()
bool FRemoteServerId::operator< (FRemoteServerId Other) const inline
Definition at line 63 of file RemoteObjectTypes.h.
References FRemoteServerId(), Id, and Other.
operator<=()
bool FRemoteServerId::operator<= (FRemoteServerId Other) const inline
Definition at line 67 of file RemoteObjectTypes.h.
References FRemoteServerId(), Id, and Other.
operator=()
void FRemoteServerId::operator= (FRemoteServerId Other) inline
Definition at line 71 of file RemoteObjectTypes.h.
References FRemoteServerId(), Id, and Other.
operator==()
bool FRemoteServerId::operator== (FRemoteServerId Other) const inline
Definition at line 55 of file RemoteObjectTypes.h.
References FRemoteServerId(), Id, and Other.
ToString()
FString FRemoteServerId::ToString () const
Friends And Related Symbol Documentation
FRemoteObjectId
friend struct FRemoteObjectId friend
Definition at line 32 of file RemoteObjectTypes.h.
References FRemoteObjectId.
Referenced by FRemoteObjectId.
operator<<
FArchive & operator<< (FArchive & Ar, FRemoteServerId & Id) friend
References FRemoteServerId(), Ar, and Id.
Field Documentation
Id
uint32 FRemoteServerId::Id = (uint32)ERemoteServerIdConstants::Invalid private
Definition at line 96 of file RemoteObjectTypes.h.
Referenced by FRemoteServerId(), FRemoteServerId(), FRemoteServerId(), GetIdNumber(), IsAsset(), IsDatabase(), IsValid(), operator!=(), operator<(), operator<<, operator<=(), operator=(), and operator==().
The documentation for this struct was generated from the following file:
RemoteObjectTypes.h