Unreal Engine 5.6 C++ API: FLinkerTables Class Reference
FLinkerTables Class Reference
#include "Linker.h"
Public Member Functions
bool AnyExportIsInImport (int32 ImportIndex) const
Return if any export is in the import.
bool AnyExportShareOuterWithImport (int32 ImportIndex) const
Return if any export share an outer with the import.
bool DoResourcesShareOutermost (FPackageIndex LinkerIndexLHS, FPackageIndex LinkerIndexRHS) const
Return if two resources share the same outermost.
FORCEINLINE FObjectExport & Exp (FPackageIndex Index)
Check that this Index is non-null and an export and return an import.
FORCEINLINE FObjectExport const & Exp (FPackageIndex Index) const
FORCEINLINE FObjectExport * ExpPtr (FPackageIndex Index)
Return an export for this index.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
FName GetClassName (FPackageIndex PackageIndex)
Gets the class name for the specified PackageIndex.
FName GetExportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the export map.
FName GetExportClassName (int32 ExportIdx)
Gets the class name for the specified index in the export map.
FString GetExportFullName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FName GetImportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the import map.
FName GetImportClassName (int32 ImportIdx)
Gets the class name for the specified index in the import map.
FString GetImportFullName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified package index.
FString GetImportFullName (int32 ImportIndex)
Return the full name of the UObject represented by the specified import.
FString GetImportPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FString GetImportPathName (int32 ImportIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE FObjectImport & Imp (FPackageIndex Index)
Check that this Index is non-null and an import and return an import.
FORCEINLINE FObjectImport const & Imp (FPackageIndex Index) const
FORCEINLINE FObjectResource & ImpExp (FPackageIndex Index)
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource const & ImpExp (FPackageIndex Index) const
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource * ImpExpPtr (FPackageIndex Index)
Return an import or export for this index.
bool ImportIsInAnyExport (int32 ImportIndex) const
Return if the import is in any export.
FORCEINLINE FObjectImport * ImpPtr (FPackageIndex Index)
Return an import for this index.
FPackageIndex ResourceGetOutermost (FPackageIndex LinkerIndex) const
Return the outermost resource package index of the resource pointed by LinkerIndex.
bool ResourceIsIn (FPackageIndex LinkerIndex, FPackageIndex OuterIndex) const
Return if a resource has the specified other resource in its outer chain.
void SerializeSearchableNamesMap (FArchive &Ar)
Serializes the searchable name map.
void SerializeSearchableNamesMap (FStructuredArchive::FSlot Slot)
Data Fields
TArray< FCellExport > CellExportMap
The list of FCellExports found in the package.
TArray< FCellImport > CellImportMap
The list of FCellImports found in the package.
TArray< TArray< FPackageIndex > > DependsMap
List of dependency lists for each export.
TArray< FObjectExport > ExportMap
The list of FObjectExports found in the package.
TArray< FObjectImport > ImportMap
The list of FObjectImports found in the package.
TMap< FPackageIndex, TArray< FName > > SearchableNamesMap
List of Searchable Names, by object containing them.
TArray< FName > SoftPackageReferenceList
List of packages that are soft referenced by this package.
Detailed Description
Definition at line 63 of file Linker.h.
Member Function Documentation
AnyExportIsInImport()
bool FLinkerTables::AnyExportIsInImport (int32 ImportIndex) const
Return if any export is in the import.
Parameters
ImportIndex the import to verify
Returns
true if the import is in any export outer chain
AnyExportShareOuterWithImport()
bool FLinkerTables::AnyExportShareOuterWithImport (int32 ImportIndex) const
Return if any export share an outer with the import.
Parameters
ImportIndex the import to verify @reutrn true if any export share the same outer has the import
DoResourcesShareOutermost()
bool FLinkerTables::DoResourcesShareOutermost (FPackageIndex LinkerIndexLHS, FPackageIndex LinkerIndexRHS) const
Return if two resources share the same outermost.
Parameters
LinkerIndexLHS the package index of the first resource
LinkerIndexRHS the package index of the second resource
Returns
true if they share an outer
Exp() [1/2]
FORCEINLINE FObjectExport & FLinkerTables::Exp (FPackageIndex Index) inline
Check that this Index is non-null and an export and return an import.
Parameters
Index Package index to get, must be an export
Returns
the export corresponding to this index
Definition at line 167 of file Linker.h.
References check, ExportMap, and FORCEINLINE.
Exp() [2/2]
FORCEINLINE FObjectExport const & FLinkerTables::Exp (FPackageIndex Index) const inline
Definition at line 172 of file Linker.h.
References check, ExportMap, and FORCEINLINE.
ExpPtr()
FORCEINLINE FObjectExport * FLinkerTables::ExpPtr (FPackageIndex Index) inline
Return an export for this index.
Parameters
Index Package index to get
Returns
the export corresponding to this index, or NULL if the package index is null or an import
Definition at line 182 of file Linker.h.
References check, ExportMap, and FORCEINLINE.
Referenced by ImpExpPtr().
GetAllocatedSize()
SIZE_T FLinkerTables::GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
GetClassName()
FName FLinkerTables::GetClassName (FPackageIndex PackageIndex) inline
Gets the class name for the specified PackageIndex.
Parameters
RootPackagePath Name of the root package these linker tables represent
PackageIndex PackageIndex for the entry in the linker tables (import or export)
Returns
Class name of the export at specified PackageIndex if the PackageIndex is non-null. Otherwise NAME_None
Definition at line 362 of file Linker.h.
References FName, GetExportClassName(), GetImportClassName(), FPackageIndex::IsExport(), and FPackageIndex::IsImport().
GetExportClassName() [1/2]
FName FLinkerTables::GetExportClassName (FPackageIndex PackageIndex) inline
Gets the class name for the specified index in the export map.
Parameters
PackageIndex PackageIndex that represents the export index
Returns
Class name of the export at specified PackageIndex if the PackageIndex represents an export. Otherwise NAME_None
Definition at line 326 of file Linker.h.
References FName, GetExportClassName(), FPackageIndex::IsExport(), and FPackageIndex::ToExport().
GetExportClassName() [2/2]
FName FLinkerTables::GetExportClassName (int32 ExportIdx)
Gets the class name for the specified index in the export map.
Parameters
ExportIdx Export index
Returns
Class name of the export at specified index
Referenced by GetClassName(), and GetExportClassName().
GetExportFullName()
FString FLinkerTables::GetExportFullName (const FString & RootPackagePath, int32 ExportIndex, bool bResolveForcedExports = false)
Return the full name of the UObject represented by the specified export.
Parameters
RootPackagePath Name of the root package for this export
ExportIndex index into the ExportMap for the resource to get the name for
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the full name of the UObject represented by the resource at ExportIndex
GetExportPathName()
FString FLinkerTables::GetExportPathName (const FString & RootPackagePath, int32 ExportIndex, bool bResolveForcedExports = false)
Return the path name of the UObject represented by the specified export.
(can be used with StaticFindObject)
Parameters
RootPackagePath Name of the root package for this export
ExportIndex index into the ExportMap for the resource to get the name for
bResolveForcedExports if true, the package name part of the return value will be the export's original package, not the name of the package it's currently contained within.
Returns
the path name of the UObject represented by the resource at ExportIndex
GetImportClassName() [1/2]
FName FLinkerTables::GetImportClassName (FPackageIndex PackageIndex) inline
Gets the class name for the specified index in the import map.
Parameters
ImportIdx Import PackageIndex
Returns
Class name of the import at specified PackageIndex if the PackageIndex represents an import. Otherwise NAME_None
Definition at line 348 of file Linker.h.
References FName, GetImportClassName(), FPackageIndex::IsImport(), and FPackageIndex::ToImport().
GetImportClassName() [2/2]
FName FLinkerTables::GetImportClassName (int32 ImportIdx) inline
Gets the class name for the specified index in the import map.
Parameters
ImportIdx Import index
Returns
Class name of the import at specified index
Definition at line 339 of file Linker.h.
References ImportMap.
Referenced by GetClassName(), and GetImportClassName().
GetImportFullName() [1/2]
FString FLinkerTables::GetImportFullName (FPackageIndex PackageIndex) inline
Return the full name of the UObject represented by the specified package index.
Parameters
PackageIndex package index for the resource to get the name for
Returns
the full name of the UObject represented by the resource at PackageIndex
Definition at line 250 of file Linker.h.
References GetImportFullName(), FPackageIndex::IsImport(), and FPackageIndex::ToImport().
GetImportFullName() [2/2]
FString FLinkerTables::GetImportFullName (int32 ImportIndex)
Return the full name of the UObject represented by the specified import.
Parameters
ImportIndex index into the ImportMap for the resource to get the name for
Returns
the full name of the UObject represented by the resource at ImportIndex
Referenced by FLinker::GetFullImpExpName(), and GetImportFullName().
GetImportPathName() [1/2]
FString FLinkerTables::GetImportPathName (FPackageIndex PackageIndex) inline
Return the path name of the UObject represented by the specified import.
(can be used with StaticFindObject)
Parameters
PackageIndex package index for the resource to get the name for
Returns
the path name of the UObject represented by the resource at PackageIndex, or the empty string if this isn't an import
Definition at line 213 of file Linker.h.
References GetImportPathName(), FPackageIndex::IsImport(), and FPackageIndex::ToImport().
GetImportPathName() [2/2]
FString FLinkerTables::GetImportPathName (int32 ImportIndex)
Return the path name of the UObject represented by the specified import.
(can be used with StaticFindObject)
Parameters
ImportIndex index into the ImportMap for the resource to get the name for
Returns
the path name of the UObject represented by the resource at ImportIndex
Referenced by GetImportPathName(), and FLinker::GetPathName().
Imp() [1/2]
FORCEINLINE FObjectImport & FLinkerTables::Imp (FPackageIndex Index) inline
Check that this Index is non-null and an import and return an import.
Parameters
Index Package index to get, must be an import
Returns
the import corresponding to this index
Definition at line 137 of file Linker.h.
References check, FORCEINLINE, and ImportMap.
Referenced by ImpExp(), and ImpExp().
Imp() [2/2]
FORCEINLINE FObjectImport const & FLinkerTables::Imp (FPackageIndex Index) const inline
Definition at line 142 of file Linker.h.
References check, FORCEINLINE, and ImportMap.
ImpExp() [1/2]
FORCEINLINE FObjectResource & FLinkerTables::ImpExp (FPackageIndex Index) inline
Check that this Index is non-null and return an import or export.
Parameters
Index Package index to get
Returns
the resource corresponding to this index
Definition at line 86 of file Linker.h.
References check, Exp, FORCEINLINE, and Imp().
ImpExp() [2/2]
FORCEINLINE FObjectResource const & FLinkerTables::ImpExp (FPackageIndex Index) const inline
Check that this Index is non-null and return an import or export.
Parameters
Index Package index to get
Returns
the resource corresponding to this index
Definition at line 103 of file Linker.h.
References check, Exp, FORCEINLINE, and Imp().
ImpExpPtr()
FORCEINLINE FObjectResource * FLinkerTables::ImpExpPtr (FPackageIndex Index) inline
Return an import or export for this index.
Parameters
Index Package index to get
Returns
the resource corresponding to this index, or NULL if the package index is null
Definition at line 120 of file Linker.h.
References ExpPtr(), FORCEINLINE, and ImpPtr().
ImportIsInAnyExport()
bool FLinkerTables::ImportIsInAnyExport (int32 ImportIndex) const
Return if the import is in any export.
Parameters
ImportIndex the import to verify
Returns
true if an export is in the import outer chain
ImpPtr()
FORCEINLINE FObjectImport * FLinkerTables::ImpPtr (FPackageIndex Index) inline
Return an import for this index.
Parameters
Index Package index to get
Returns
the import corresponding to this index, or NULL if the package index is null or an export
Definition at line 152 of file Linker.h.
References check, FORCEINLINE, and ImportMap.
Referenced by ImpExpPtr().
ResourceGetOutermost()
FPackageIndex FLinkerTables::ResourceGetOutermost (FPackageIndex LinkerIndex) const
Return the outermost resource package index of the resource pointed by LinkerIndex.
Parameters
LinkerIndex the resource to find the outermost of
Returns
the package index of the outermost
ResourceIsIn()
bool FLinkerTables::ResourceIsIn (FPackageIndex LinkerIndex, FPackageIndex OuterIndex) const
Return if a resource has the specified other resource in its outer chain.
Parameters
LinkerIndex the package index of the resource to verify
OuterIndex the package index of the possible outer for the resource
Returns
true if the resource pointed by LinkerIndex is in the resource pointed by OuterIndex
SerializeSearchableNamesMap() [1/2]
void FLinkerTables::SerializeSearchableNamesMap (FArchive & Ar)
Serializes the searchable name map.
References Ar.
SerializeSearchableNamesMap() [2/2]
void FLinkerTables::SerializeSearchableNamesMap (FStructuredArchive::FSlot Slot)
Field Documentation
CellExportMap
TArray<FCellExport> FLinkerTables::CellExportMap
The list of FCellExports found in the package.
Definition at line 73 of file Linker.h.
CellImportMap
TArray<FCellImport> FLinkerTables::CellImportMap
The list of FCellImports found in the package.
Definition at line 71 of file Linker.h.
DependsMap
TArray<TArray<FPackageIndex> > FLinkerTables::DependsMap
List of dependency lists for each export.
Definition at line 75 of file Linker.h.
ExportMap
TArray<FObjectExport> FLinkerTables::ExportMap
The list of FObjectExports found in the package.
Definition at line 69 of file Linker.h.
Referenced by Exp(), Exp(), and ExpPtr().
ImportMap
TArray<FObjectImport> FLinkerTables::ImportMap
The list of FObjectImports found in the package.
Definition at line 67 of file Linker.h.
Referenced by GetImportClassName(), Imp(), Imp(), and ImpPtr().
SearchableNamesMap
TMap<FPackageIndex, TArray<FName> > FLinkerTables::SearchableNamesMap
List of Searchable Names, by object containing them.
Not in MultiMap to allow sorting, and sizes are usually small enough where TArray makes sense
Definition at line 79 of file Linker.h.
SoftPackageReferenceList
TArray<FName> FLinkerTables::SoftPackageReferenceList
List of packages that are soft referenced by this package.
Definition at line 77 of file Linker.h.
The documentation for this class was generated from the following file:
Linker.h