Unreal Engine 5.6 C++ API: UE::Tasks::Private Namespace Reference
UE::Tasks::Private Namespace Reference
Data Structures
class FTaskBase
class FTaskEventBase
class FTaskHandle
class TExecutableTask
class TExecutableTaskBase
class TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >
class TTaskWithResult
Typedefs
using FExecutableTaskAllocator = TLockFreeFixedSizeAllocator_TLSCache<SmallTaskSize, PLATFORM_CACHE_LINE_SIZE>
using FTaskEventBaseAllocator = TLockFreeFixedSizeAllocator_TLSCache<sizeof(FTaskEventBase), PLATFORM_CACHE_LINE_SIZE>
Functions
FTaskBase * ExchangeCurrentTask (FTaskBase *Task)
FTaskBase * GetCurrentTask ()
template<typename TaskCollectionType>
TArray< TaskTrace::FId > GetTraceIds (const TaskCollectionType &Tasks)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FTask > > * = nullptr>
bool IsCompleted (const HigherLevelTaskType &Prerequisite)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr>
bool IsCompleted (const HigherLevelTaskType &Prerequisite)
template<int32 Index, typename ArrayType, typename FirstTaskType, typename... OtherTasksTypes>
void PrerequisitesUnpacker (ArrayType &Array, FirstTaskType &FirstTask, OtherTasksTypes &... OtherTasks)
template<int32 Index, typename ArrayType, typename TaskType>
void PrerequisitesUnpacker (ArrayType &Array, TaskType &Task)
void TranslatePriority (ENamedThreads::Type ThreadType, ETaskPriority &OutPriority, EExtendedTaskPriority &OutExtendedPriority)
ENamedThreads::Type TranslatePriority (ETaskPriority Priority, EExtendedTaskPriority ExtendedPriority)
template<typename TaskCollectionType>
bool TryRetractAndExecute (const TaskCollectionType &Tasks, FTimeout Timeout)
bool TryWaitOnNamedThread (FTaskBase &Task)
UE_DEPRECATED (5.1, "You should not use this function as it exists only to patch another system and can be removed any time.") 1 bool IsThreadRetractingTask()
Variables
constexpr int32 LargeTaskAlignment = 16
FExecutableTaskAllocator SmallTaskAllocator
constexpr int32 SmallTaskSize = 256
FTaskEventBaseAllocator TaskEventBaseAllocator
Typedef Documentation
FExecutableTaskAllocator
using UE::Tasks::Private::FExecutableTaskAllocator = TLockFreeFixedSizeAllocator_TLSCache<SmallTaskSize, PLATFORM_CACHE_LINE_SIZE>
Definition at line 926 of file TaskPrivate.h.
FTaskEventBaseAllocator
using UE::Tasks::Private::FTaskEventBaseAllocator = TLockFreeFixedSizeAllocator_TLSCache<sizeof(FTaskEventBase), PLATFORM_CACHE_LINE_SIZE>
Definition at line 995 of file TaskPrivate.h.
Function Documentation
ExchangeCurrentTask()
FTaskBase * UE::Tasks::Private::ExchangeCurrentTask (FTaskBase * Task)
Referenced by UE::Tasks::Private::FTaskBase::TryExecuteTask().
GetCurrentTask()
FTaskBase * UE::Tasks::Private::GetCurrentTask ()
Referenced by UE::Tasks::AddNested(), and FBaseGraphTask::DontCompleteUntil().
GetTraceIds()
template<typename TaskCollectionType> TArray< TaskTrace::FId > UE::Tasks::Private::GetTraceIds (const TaskCollectionType & Tasks)
Definition at line 340 of file Tasks/Task.h.
Referenced by UE::Tasks::Wait().
IsCompleted() [1/2]
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FTask > > * = nullptr> bool UE::Tasks::Private::IsCompleted (const HigherLevelTaskType & Prerequisite)
Definition at line 410 of file Tasks/Task.h.
Referenced by UE::Tasks::Private::FTaskBase::~FTaskBase(), UE::Tasks::Private::FTaskBase::Close(), UE::Tasks::Private::FTaskBase::UE_DEPRECATED(), and UE::Tasks::WaitAny().
IsCompleted() [2/2]
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr> bool UE::Tasks::Private::IsCompleted (const HigherLevelTaskType & Prerequisite)
Definition at line 416 of file Tasks/Task.h.
PrerequisitesUnpacker() [1/2]
template<int32 Index, typename ArrayType, typename FirstTaskType, typename... OtherTasksTypes> void UE::Tasks::Private::PrerequisitesUnpacker (ArrayType & Array, FirstTaskType & FirstTask, OtherTasksTypes &... OtherTasks)
Definition at line 397 of file Tasks/Task.h.
Referenced by UE::Tasks::Prerequisites(), and UE::Tasks::Private::FTaskHandle::PrerequisitesUnpacker.
PrerequisitesUnpacker() [2/2]
template<int32 Index, typename ArrayType, typename TaskType> void UE::Tasks::Private::PrerequisitesUnpacker (ArrayType & Array, TaskType & Task)
Definition at line 404 of file Tasks/Task.h.
TranslatePriority() [1/2]
void UE::Tasks::Private::TranslatePriority (ENamedThreads::Type ThreadType, ETaskPriority & OutPriority, EExtendedTaskPriority & OutExtendedPriority)
Referenced by TGraphTask< TTask >::FConstructor::ConstructAndHoldImpl(), and UE::Tasks::Private::FTaskBase::TryLaunch().
TranslatePriority() [2/2]
ENamedThreads::Type UE::Tasks::Private::TranslatePriority (ETaskPriority Priority, EExtendedTaskPriority ExtendedPriority)
TryRetractAndExecute()
template<typename TaskCollectionType> bool UE::Tasks::Private::TryRetractAndExecute (const TaskCollectionType & Tasks, FTimeout Timeout)
Definition at line 1014 of file TaskPrivate.h.
Referenced by UE::Tasks::Private::FTaskBase::UE_DEPRECATED().
TryWaitOnNamedThread()
bool UE::Tasks::Private::TryWaitOnNamedThread (FTaskBase & Task)
UE_DEPRECATED()
UE::Tasks::Private::UE_DEPRECATED (5. 1, "You should not use this function as it exists only to patch another system and can be removed any time.")
Variable Documentation
LargeTaskAlignment
int32 UE::Tasks::Private::LargeTaskAlignment = 16 inline constexpr
Definition at line 925 of file TaskPrivate.h.
Referenced by UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator new().
SmallTaskAllocator
FExecutableTaskAllocator UE::Tasks::Private::SmallTaskAllocator extern
Referenced by UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator delete(), and UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator new().
SmallTaskSize
int32 UE::Tasks::Private::SmallTaskSize = 256 inline constexpr
Definition at line 924 of file TaskPrivate.h.
Referenced by UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator delete(), and UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator new().
TaskEventBaseAllocator
FTaskEventBaseAllocator UE::Tasks::Private::TaskEventBaseAllocator extern
Referenced by UE::Tasks::Private::FTaskEventBase::operator delete(), and UE::Tasks::Private::FTaskEventBase::operator new().