Unreal Engine 5.6 C++ API: FLazyName::FLiteralOrName Struct Reference
FLazyName::FLiteralOrName Struct Reference
Public Member Functions
FLiteralOrName (const ANSICHAR *Literal)
FLiteralOrName (const WIDECHAR *Literal)
FLiteralOrName (FNameEntryId ComparisionId, FNameEntryId DisplayId)
const ANSICHAR * AsAnsiLiteral () const
const WIDECHAR * AsWideLiteral () const
FNameEntryId GetComparisionId () const
FNameEntryId GetDisplayId () const
bool IsLiteral () const
bool IsName () const
Data Fields
uint64 Int
Static Public Attributes
static constexpr uint32 DisplayNameShift = 32
static constexpr uint64 LiteralFlag = uint64(1) << (sizeof(uint64) * 8 - 1)
Detailed Description
Definition at line 1697 of file NameTypes.h.
Constructor & Destructor Documentation
FLiteralOrName() [1/3]
FLazyName::FLiteralOrName::FLiteralOrName (const ANSICHAR * Literal) inline explicit
Definition at line 1703 of file NameTypes.h.
References Int, and LiteralFlag.
FLiteralOrName() [2/3]
FLazyName::FLiteralOrName::FLiteralOrName (const WIDECHAR * Literal) inline explicit
Definition at line 1707 of file NameTypes.h.
References Int, and LiteralFlag.
FLiteralOrName() [3/3]
FLazyName::FLiteralOrName::FLiteralOrName (FNameEntryId ComparisionId, FNameEntryId DisplayId) inline explicit
Definition at line 1711 of file NameTypes.h.
References checkName, DisplayNameShift, Int, IsName(), and WITH_CASE_PRESERVING_NAME.
Member Function Documentation
AsAnsiLiteral()
const ANSICHAR * FLazyName::FLiteralOrName::AsAnsiLiteral () const inline
Definition at line 1743 of file NameTypes.h.
References Int, and LiteralFlag.
Referenced by FLazyName::operator==.
AsWideLiteral()
const WIDECHAR * FLazyName::FLiteralOrName::AsWideLiteral () const inline
Definition at line 1748 of file NameTypes.h.
References Int, and LiteralFlag.
Referenced by FLazyName::operator==.
GetComparisionId()
FNameEntryId FLazyName::FLiteralOrName::GetComparisionId () const inline
Definition at line 1729 of file NameTypes.h.
References FNameEntryId::FromUnstableInt(), and Int.
Referenced by GetDisplayId().
GetDisplayId()
FNameEntryId FLazyName::FLiteralOrName::GetDisplayId () const inline
Definition at line 1734 of file NameTypes.h.
References DisplayNameShift, FNameEntryId::FromUnstableInt(), GetComparisionId(), and Int.
IsLiteral()
bool FLazyName::FLiteralOrName::IsLiteral () const inline
Definition at line 1724 of file NameTypes.h.
References Int, and LiteralFlag.
IsName()
bool FLazyName::FLiteralOrName::IsName () const inline
Definition at line 1719 of file NameTypes.h.
References Int, and LiteralFlag.
Referenced by FLiteralOrName(), and FLazyName::operator==.
Field Documentation
DisplayNameShift
uint32 FLazyName::FLiteralOrName::DisplayNameShift = 32 static constexpr
Definition at line 1701 of file NameTypes.h.
Referenced by FLiteralOrName(), and GetDisplayId().
Int
uint64 FLazyName::FLiteralOrName::Int
Definition at line 1753 of file NameTypes.h.
Referenced by FLiteralOrName(), FLiteralOrName(), FLiteralOrName(), AsAnsiLiteral(), AsWideLiteral(), GetComparisionId(), GetDisplayId(), IsLiteral(), and IsName().
LiteralFlag
uint64 FLazyName::FLiteralOrName::LiteralFlag = uint64(1) << (sizeof(uint64) * 8 - 1) static constexpr
Definition at line 1700 of file NameTypes.h.
Referenced by FLiteralOrName(), FLiteralOrName(), AsAnsiLiteral(), AsWideLiteral(), IsLiteral(), and IsName().
The documentation for this struct was generated from the following file:
NameTypes.h