Unreal Engine 5.6 C++ API: ISceneRenderBuilder Class Reference
ISceneRenderBuilder Class Reference abstract
#include "SceneRenderBuilderInterface.h"
Public Member Functions
virtual ~ISceneRenderBuilder ()=default
virtual void AddCommand (TUniqueFunction< void()> &&Function)=0
Adds a command that executes on the game thread and is pipelined with scene render commands on the render thread.
void AddRenderCommand (TUniqueFunction< void(FRHICommandListImmediate &)> &&Function)
void AddRenderer (FSceneRenderer *Renderer, FSceneRenderFunction &&Function)
virtual void AddRenderer (FSceneRenderer *Renderer, FString &&Name, FSceneRenderFunction &&Function)=0
virtual TArray< FSceneRenderer *, FConcurrentLinearArrayAllocator > CreateLinkedSceneRenderers (TConstArrayView< FSceneViewFamily * > ViewFamilies, FHitProxyConsumer *HitProxyConsumer)=0
Creates a linked set of scene renderers with related view families based on the current feature level.
virtual FSceneRenderer * CreateSceneRenderer (FSceneViewFamily *ViewFamily)=0
Creates a scene renderer based on the current feature level.
virtual void Execute ()=0
virtual FConcurrentLinearBulkObjectAllocator & GetAllocator ()=0
virtual bool IsCompatible (const FEngineShowFlags &EngineShowFlags) const =0
Whether a renderer with the provided show flags can be added to the builder.
Static Public Member Functions
static TUniquePtr< ISceneRenderBuilder > Create (FSceneInterface *SceneInterface)
Private Member Functions
virtual void BeginGroup (FString &&Name, ESceneRenderGroupFlags Flags)=0
virtual void EndGroup ()=0
Friends
class FSceneRenderGroupScope
Detailed Description
Definition at line 51 of file SceneRenderBuilderInterface.h.
Constructor & Destructor Documentation
~ISceneRenderBuilder()
virtual ISceneRenderBuilder::~ISceneRenderBuilder () virtual default
Member Function Documentation
AddCommand()
virtual void ISceneRenderBuilder::AddCommand (TUniqueFunction< void()> && Function) pure virtual
Adds a command that executes on the game thread and is pipelined with scene render commands on the render thread.
This is useful to process game thread side logic in between scene renders which may insert render commands. Though be mindful of how commands may be deferred until RDG execution in certain configurations.
References Function.
Referenced by AddRenderCommand().
AddRenderCommand()
void ISceneRenderBuilder::AddRenderCommand (TUniqueFunction< void(FRHICommandListImmediate &)> && Function) inline
Definition at line 75 of file SceneRenderBuilderInterface.h.
References AddCommand(), ENQUEUE_RENDER_COMMAND, Function, and MoveTemp().
AddRenderer() [1/2]
void ISceneRenderBuilder::AddRenderer (FSceneRenderer * Renderer, FSceneRenderFunction && Function) inline
Definition at line 86 of file SceneRenderBuilderInterface.h.
References AddRenderer(), Function, and MoveTemp().
AddRenderer() [2/2]
virtual void ISceneRenderBuilder::AddRenderer (FSceneRenderer * Renderer, FString && Name, FSceneRenderFunction && Function) pure virtual
References Function, and Name.
Referenced by AddRenderer().
BeginGroup()
virtual void ISceneRenderBuilder::BeginGroup (FString && Name, ESceneRenderGroupFlags Flags) private pure virtual
References Flags, and Name.
Create()
TUniquePtr< ISceneRenderBuilder > ISceneRenderBuilder::Create (FSceneInterface * SceneInterface) static
CreateLinkedSceneRenderers()
virtual TArray< FSceneRenderer *, FConcurrentLinearArrayAllocator > ISceneRenderBuilder::CreateLinkedSceneRenderers (TConstArrayView< FSceneViewFamily * > ViewFamilies, FHitProxyConsumer * HitProxyConsumer) pure virtual
Creates a linked set of scene renderers with related view families based on the current feature level.
CreateSceneRenderer()
virtual FSceneRenderer * ISceneRenderBuilder::CreateSceneRenderer (FSceneViewFamily * ViewFamily) pure virtual
Creates a scene renderer based on the current feature level.
EndGroup()
virtual void ISceneRenderBuilder::EndGroup () private pure virtual
Execute()
virtual void ISceneRenderBuilder::Execute () pure virtual
GetAllocator()
virtual FConcurrentLinearBulkObjectAllocator & ISceneRenderBuilder::GetAllocator () pure virtual
IsCompatible()
virtual bool ISceneRenderBuilder::IsCompatible (const FEngineShowFlags & EngineShowFlags) const pure virtual
Whether a renderer with the provided show flags can be added to the builder.
If not compatible, you must call Execute() first to flush existing renderers prior to adding.
Friends And Related Symbol Documentation
FSceneRenderGroupScope
friend class FSceneRenderGroupScope friend
Definition at line 105 of file SceneRenderBuilderInterface.h.
References FSceneRenderGroupScope.
Referenced by FSceneRenderGroupScope.
The documentation for this class was generated from the following file:
SceneRenderBuilderInterface.h