Unreal Engine 5.6 C++ API: FRepLayout Class Reference
FRepLayout Class Reference
This class holds all replicated properties for a given type (either a UClass, UStruct, or UFunction).
#include "RepLayout.h"
Public Member Functions
virtual ~FRepLayout ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void BuildSharedSerializationForRPC (const FConstRepObjectDataBuffer Data, UE::Net::FNetTokenStore *NetTokenStore=nullptr)
Builds shared serialization state for a multicast rpc.
void CallRepNotifies (FReceivingRepState *RepState, UObject *Object) const
Fire any RepNotifies that have been queued for an object while receiving properties.
void ClearSharedSerializationForRPC ()
Clears shared serialization state for a multicast rpc.
void CountBytes (FArchive &Ar) const
TSharedPtr< FReplicationChangelistMgr > CreateReplicationChangelistMgr (const UObject *InObject, const ECreateReplicationChangelistMgrFlags CreateFlags) const
Creates and initializes a new FReplicationChangelistMgr.
TUniquePtr< FRepState > CreateRepState (const FConstRepObjectDataBuffer Source, TSharedPtr< FRepChangedPropertyTracker > &InRepChangedPropertyTracker, ECreateRepStateFlags Flags) const
Creates and initializes a new FRepState.
FRepStateStaticBuffer CreateShadowBuffer (const FConstRepObjectDataBuffer Source) const
Creates and initialize a new Shadow Buffer.
template<ERepDataBufferType DstType, ERepDataBufferType SrcType>
bool DiffProperties (TArray< FProperty * > *RepNotifies, TRepDataBuffer< DstType > Destination, TConstRepDataBuffer< SrcType > Source, const EDiffPropertiesFlags Flags) const
Compare all properties between source and destination buffer, and optionally update the destination buffer to match the state of the source buffer if they don't match.
template<ERepDataBufferType DstType, ERepDataBufferType SrcType>
bool DiffStableProperties (TArray< FProperty * > *RepNotifies, TArray< UObject * > *ObjReferences, TRepDataBuffer< DstType > Destination, TConstRepDataBuffer< SrcType > Source) const
void GatherGuidReferences (FReceivingRepState *RESTRICT RepState, struct FNetDeltaSerializeInfo &Params, TSet< FNetworkGUID > &OutReferencedGuids, int32 &OutTrackedGuidMemoryBytes) const
Finds any properties in the Shadow Buffer of the given Rep State that are currently valid (mapped or unmapped) references to other network objects, and retrieves the associated Net GUIDS.
uint32 GenerateChecksum (const FRepState *RepState) const
const uint16 GetCustomDeltaIndexFromPropertyRepIndex (const uint16 PropertyRepIndex) const
const ERepLayoutFlags GetFlags () const
const int32 GetNumParents () const
UObject * GetOwner () const
const int32 GetParentArrayIndex (int32 Index) const
const int32 GetParentCondition (int32 Index) const
const FProperty * GetParentProperty (int32 Index) const
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
template<typename T>
const T * GetShadowStateValue (FConstRepShadowDataBuffer Data, const FName PropertyName) const
template<typename T>
T * GetShadowStateValue (FRepShadowDataBuffer Data, const FName PropertyName)
Gets a pointer to the value of the given property in the Shadow State.
const bool IsCustomDeltaProperty (int32 Index) const
const bool IsEmpty () const
bool MoveMappedObjectToUnmapped (FReceivingRepState *RESTRICT RepState, struct FNetDeltaSerializeInfo &Params, const FNetworkGUID &GUID) const
Called to indicate that the object referenced by the FNetworkGUID is no longer mapped.
bool ReceiveProperties (UActorChannel *OwningChannel, UClass *InObjectClass, FReceivingRepState *RESTRICT RepState, UObject *Object, FNetBitReader &InBunch, bool &bOutHasUnmapped, bool &bOutGuidsChanged, const EReceivePropertiesFlags InFlags) const
Reads all property values from the received buffer, and applies them to the property memory.
bool ReceiveProperties_BackwardsCompatible (UNetConnection *Connection, FReceivingRepState *RESTRICT RepState, FRepObjectDataBuffer Data, FNetBitReader &InBunch, bool &bOutHasUnmapped, const bool bEnableRepNotifies, bool &bOutGuidsChanged, UObject *OwningObject=nullptr) const
Currently only used for Replays / with the UDemoNetDriver.
void ReceivePropertiesForRPC (UObject *Object, UFunction *Function, UActorChannel *Channel, FNetBitReader &Reader, FRepObjectDataBuffer Data, TSet< FNetworkGUID > &UnmappedGuids) const
bool ReplicateProperties (FSendingRepState *RESTRICT RepState, FRepChangelistState *RESTRICT RepChangelistState, const FConstRepObjectDataBuffer Data, UClass *ObjectClass, UActorChannel *OwningChannel, FNetBitWriter &Writer, const FReplicationFlags &RepFlags) const
Writes out any changed properties for an Object into the given data buffer, and does book keeping for the RepState of the object.
void SendProperties_BackwardsCompatible (FSendingRepState *RESTRICT RepState, FRepChangedPropertyTracker *ChangedTracker, const FConstRepObjectDataBuffer Data, UNetConnection *Connection, FNetBitWriter &Writer, TArray< uint16 > &Changed) const
Currently only used for Replays / with the UDemoNetDriver.
void SendPropertiesForRPC (UFunction *Function, UActorChannel *Channel, FNetBitWriter &Writer, const FConstRepObjectDataBuffer Data) const
void SerializeObjectReplicatedProperties (UObject *Object, FBitArchive &Ar) const
Serializes all replicated properties of a UObject in or out of an archive (depending on what type of archive it is).
void SerializePropertiesForStruct (UStruct *Struct, FBitArchive &Ar, UPackageMap *Map, FRepObjectDataBuffer Data, bool &bHasUnmapped, const UObject *OwningObject=nullptr) const
UE_DEPRECATED (5.1, "No longer used, trackers are initialized by the replication subsystem.") void InitChangedTracker(FRepChangedPropertyTracker *ChangedTracker) const
void UpdateUnmappedObjects (FReceivingRepState *RESTRICT RepState, UPackageMap *PackageMap, UObject *Object, struct FNetDeltaSerializeInfo &Params, bool &bCalledPreNetReceive, bool &bOutSomeObjectsWereMapped, bool &bOutHasMoreUnmapped) const
Attempts to update any unmapped network guids referenced by the RepState.
template<ERepDataBufferType DataType>
void ValidateWithChecksum (TConstRepDataBuffer< DataType > Data, FBitArchive &Ar) const
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from TSharedFromThis< FRepLayout >
TSharedRef< FRepLayout, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRepLayout, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< FRepLayout > CreateFromClass (UClass *InObjectClass, const UNetConnection *ServerConnection=nullptr, const ECreateRepLayoutFlags Flags=ECreateRepLayoutFlags::None)
Creates a new FRepLayout for the given class.
static TSharedPtr< FRepLayout > CreateFromFunction (UFunction *InFunction, const UNetConnection *ServerConnection=nullptr, const ECreateRepLayoutFlags Flags=ECreateRepLayoutFlags::None)
Creates a new FRepLayout for the given function.
static TSharedPtr< FRepLayout > CreateFromStruct (UStruct *InStruct, const UNetConnection *ServerConnection=nullptr, const ECreateRepLayoutFlags Flags=ECreateRepLayoutFlags::None)
Creates a new FRepLayout for the given struct.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Private Member Functions
FRepLayout ()
void BuildChangeList_r (const TArray< FHandleToCmdIndex > &HandleToCmdIndex, const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, const int32 HandleOffset, const bool bForceArraySends, TArray< uint16 > &Changed) const
void BuildHandleToCmdIndexTable_r (const int32 CmdStart, const int32 CmdEnd, TArray< FHandleToCmdIndex > &HandleToCmdIndex)
void BuildSharedSerialization (const FConstRepObjectDataBuffer Data, TArray< uint16 > &Changed, const bool bWriteHandle, FRepSerializationSharedInfo &SharedInfo, UE::Net::FNetTokenStore *NetTokenStore=nullptr) const
void BuildSharedSerialization_r (FRepHandleIterator &RepHandleIterator, const FConstRepObjectDataBuffer SourceData, const bool bWriteHandle, const bool bDoChecksum, const int32 ArrayDepth, FRepSerializationSharedInfo &SharedInfo) const
void BuildSharedSerializationForRPC_DynamicArray_r (const int32 CmdIndex, const FConstRepObjectDataBuffer Data, int32 ArrayDepth, FRepSerializationSharedInfo &SharedInfo)
void BuildSharedSerializationForRPC_r (const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, int32 ArrayIndex, int32 ArrayDepth, FRepSerializationSharedInfo &SharedInfo)
ERepLayoutResult CompareProperties (FSendingRepState *RESTRICT RepState, FRepChangelistState *RESTRICT RepChangelistState, const FConstRepObjectDataBuffer Data, const FReplicationFlags &RepFlags, const bool bForceCompare) const
Compare Property Values currently stored in the Changelist State to the Property Values in the passed in data, generating a new changelist if necessary.
void ConstructProperties (FRepStateStaticBuffer &ShadowData) const
void CopyProperties (FRepStateStaticBuffer &ShadowData, const FConstRepObjectDataBuffer Source) const
TSharedPtr< FNetFieldExportGroup > CreateNetfieldExportGroup () const
ERepLayoutResult DeltaSerializeFastArrayProperty (struct FFastArrayDeltaSerializeParams &Params, FReplicationChangelistMgr *ChangelistMgr) const
void DestructProperties (FRepStateStaticBuffer &RepStateStaticBuffer) const
void FilterChangeList (const TArray< uint16 > &Changelist, const TBitArray<> &InactiveParentHandles, TArray< uint16 > &OutInactiveProperties, TArray< uint16 > &OutActiveProperties) const
Splits a given Changelist into an Inactive Change List and an Active Change List.
void FilterChangeListToActive (const TArray< uint16 > &Changelist, const TBitArray<> &InactiveParentHandles, TArray< uint16 > &OutActiveProperties) const
Same as FilterChangeList, but only populates an Active Change List.
int32 FindCompatibleProperty (const int32 CmdStart, const int32 CmdEnd, const uint32 Checksum) const
void GatherGuidReferences_r (const FGuidReferencesMap *GuidReferencesMap, TSet< FNetworkGUID > &OutReferencedGuids, int32 &OutTrackedGuidMemoryBytes) const
void GatherGuidReferencesForFastArray (struct FFastArrayDeltaSerializeParams &Params) const
FProperty * GetLifetimeCustomDeltaProperty (const uint16 CustomDeltaPropertyIndex) const
const ELifetimeCondition GetLifetimeCustomDeltaPropertyCondition (const uint16 RepIndCustomDeltaPropertyIndex) const
const uint16 GetLifetimeCustomDeltaPropertyRepIndex (const uint16 RepIndCustomDeltaPropertyIndex) const
const uint16 GetNumLifetimeCustomDeltaProperties () const
void InitFromClass (UClass *InObjectClass, const UNetConnection *ServerConnection, const ECreateRepLayoutFlags Flags)
void InitFromFunction (UFunction *InFunction, const UNetConnection *ServerConnection, const ECreateRepLayoutFlags Flags)
void InitFromStruct (UStruct *InStruct, const UNetConnection *ServerConnection, const ECreateRepLayoutFlags Flags)
void InitRepStateStaticBuffer (FRepStateStaticBuffer &ShadowData, const FConstRepObjectDataBuffer Source) const
void MergeChangeList (const FConstRepObjectDataBuffer Data, const TArray< uint16 > &Dirty1, const TArray< uint16 > &Dirty2, TArray< uint16 > &MergedDirty) const
void MergeChangeList_r (FRepHandleIterator &RepHandleIterator1, FRepHandleIterator &RepHandleIterator2, const FConstRepObjectDataBuffer SourceData, TArray< uint16 > &OutChanged) const
bool MoveMappedObjectToUnmapped_r (FGuidReferencesMap *GuidReferencesMap, const FNetworkGUID &GUID, const UObject *const OwningObject) const
bool MoveMappedObjectToUnmappedForFastArray (struct FFastArrayDeltaSerializeParams &Params) const
void PostSendCustomDeltaProperties (UObject *Object, UNetConnection *Connection, FReplicationChangelistMgr &ChangelistMgr, TArray< TSharedPtr< INetDeltaBaseState > > &CustomDeltaStates) const
void PreSendCustomDeltaProperties (UObject *Object, UNetConnection *Connection, FReplicationChangelistMgr &ChangelistMgr, uint32 ReplicationFrame, TArray< TSharedPtr< INetDeltaBaseState > > &CustomDeltaStates) const
void PruneChangeList (const FConstRepObjectDataBuffer Data, const TArray< uint16 > &Changed, TArray< uint16 > &PrunedChanged) const
Clamps a changelist so that it conforms to the current size of either an array, or arrays within structs/arrays.
void PruneChangeList_r (FRepHandleIterator &RepHandleIterator, const FConstRepObjectDataBuffer SourceData, TArray< uint16 > &OutChanged) const
void RebuildConditionalProperties (FSendingRepState *RepState, const FReplicationFlags RepFlags) const
bool ReceiveCustomDeltaProperty (FReceivingRepState *RESTRICT ReceivingRepState, FNetDeltaSerializeInfo &Params, FStructProperty *Property) const
Attempts to receive the custom delta property.
bool ReceiveProperties_BackwardsCompatible_r (FReceivingRepState *RESTRICT RepState, FNetFieldExportGroup *NetFieldExportGroup, FNetBitReader &Reader, const int32 CmdStart, const int32 CmdEnd, FRepShadowDataBuffer ShadowData, FRepObjectDataBuffer OldData, FRepObjectDataBuffer Data, FGuidReferencesMap *GuidReferencesMap, bool &bOutHasUnmapped, bool &bOutGuidsChanged, UObject *OwningObject) const
void SanityCheckChangeList (const FConstRepObjectDataBuffer Data, TArray< uint16 > &Changed) const
void SanityCheckChangeList_DynamicArray_r (const int32 CmdIndex, const FConstRepObjectDataBuffer Data, TArray< uint16 > &Changed, int32 &ChangedIndex) const
uint16 SanityCheckChangeList_r (const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, TArray< uint16 > &Changed, int32 &ChangedIndex, uint16 Handle) const
void SendAllProperties_BackwardsCompatible_r (FSendingRepState *RESTRICT RepState, FNetBitWriter &Writer, const bool bDoChecksum, UPackageMapClient *PackageMapClient, FNetFieldExportGroup *NetFieldExportGroup, const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer SourceData) const
bool SendCustomDeltaProperty (FNetDeltaSerializeInfo &Params, const uint16 CustomDeltaIndex) const
void SendProperties (FSendingRepState *RESTRICT RepState, FRepChangedPropertyTracker *ChangedTracker, const FConstRepObjectDataBuffer Data, UClass *ObjectClass, FNetBitWriter &Writer, TArray< uint16 > &Changed, const FRepSerializationSharedInfo &SharedInfo, const ESerializePropertyType SerializePropertyType) const
Writes all changed property values from the input owner data to the given buffer.
void SendProperties_BackwardsCompatible_r (FSendingRepState *RESTRICT RepState, UPackageMapClient *PackageMapClient, FNetFieldExportGroup *NetFieldExportGroup, FRepChangedPropertyTracker *ChangedTracker, FNetBitWriter &Writer, const bool bDoChecksum, FRepHandleIterator &HandleIterator, const FConstRepObjectDataBuffer Source) const
void SendProperties_r (FSendingRepState *RESTRICT RepState, FNetBitWriter &Writer, const bool bDoChecksum, FRepHandleIterator &HandleIterator, const FConstRepObjectDataBuffer SourceData, const int32 ArrayDepth, const FRepSerializationSharedInfo *const RESTRICT SharedInfo, const ESerializePropertyType SerializePropertyType) const
void SerializeProperties_DynamicArray_r (FBitArchive &Ar, UPackageMap *Map, const int32 CmdIndex, FRepObjectDataBuffer Data, bool &bHasUnmapped, const int32 ArrayDepth, const FRepSerializationSharedInfo &SharedInfo, FNetTraceCollector *Collector, const UObject *OwningObject) const
void SerializeProperties_r (FBitArchive &Ar, UPackageMap *Map, const int32 CmdStart, const int32 CmdEnd, FRepObjectDataBuffer Data, bool &bHasUnmapped, const int32 ArrayIndex, const int32 ArrayDepth, const FRepSerializationSharedInfo &SharedInfo, FNetTraceCollector *Collector, const UObject *OwningObject) const
void UpdateChangelistHistory (FSendingRepState *RepState, UClass *ObjectClass, const FConstRepObjectDataBuffer Data, UNetConnection *Connection, TArray< uint16 > *OutMerged) const
ERepLayoutResult UpdateChangelistMgr (FSendingRepState *RESTRICT RepState, FReplicationChangelistMgr &InChangelistMgr, const UObject *InObject, const uint32 ReplicationFrame, const FReplicationFlags &RepFlags, const bool bForceCompare) const
void UpdateUnmappedGuidsForFastArray (struct FFastArrayDeltaSerializeParams &Params) const
void UpdateUnmappedObjects_r (FReceivingRepState *RESTRICT RepState, FGuidReferencesMap *GuidReferencesMap, UObject *OriginalObject, UNetConnection *Connection, FRepShadowDataBuffer ShadowData, FRepObjectDataBuffer Data, const int32 MaxAbsOffset, bool &bCalledPreNetReceive, bool &bOutSomeObjectsWereMapped, bool &bOutHasMoreUnmapped) const
Private Attributes
TArray< FHandleToCmdIndex > BaseHandleToCmdIndex
Converts a relative handle to the appropriate index into the Cmds array.
TArray< FRepLayoutCmd > Cmds
All Layout Commands.
ERepLayoutFlags Flags
TUniquePtr< struct FLifetimeCustomDeltaState > LifetimeCustomPropertyState
Special state tracking for Lifetime Custom Delta Properties.
TMap< FRepLayoutCmd *, TArray< FRepLayoutCmd > > NetSerializeLayouts
UStruct * Owner
UClass, UStruct, or UFunction that this FRepLayout represents.
TArray< FRepParentCmd > Parents
Top level Layout Commands.
int32 ShadowDataBufferSize
Size (in bytes) needed to allocate a single instance of a Shadow buffer for this RepLayout.
FRepSerializationSharedInfo SharedInfoRPC
Shared serialization state for a multicast rpc.
TBitArray SharedInfoRPCParentsChanged
Shared comparison to default state for multicast rpc.
Friends
struct FCustomDeltaPropertyIterator
class FNetSerializeCB
struct FRepStateStaticBuffer
class UPackageMapClient
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions inherited from TSharedFromThis< FRepLayout >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRepLayout >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
This class holds all replicated properties for a given type (either a UClass, UStruct, or UFunction).
Helpers functions exist to read, write, and compare property state.
There is only one FRepLayout for a given type, meaning all instances of the type share the FRepState.
COMMANDS:
All Properties in a RepLayout are represented as Layout Commands. These commands dictate:
What the underlying data type is.
How the data is laid out in memory.
How the data should be serialized.
How the data should be compared (between instances of Objects, Structs, etc.).
Whether or not the data should trigger notifications on change (RepNotifies).
Whether or not the data is conditional (e.g. may be skipped when sending to some or all connections).
Commands are split into 2 main types: Parent Commands (
See also
FRepParentCmd) and Child Commands (
FRepLayoutCmd).
A Parent Command represents a Top Level Property of the type represented by an FRepLayout. A Child Command represents any Property (even nested properties).
E.G., Imagine an Object O, with 4 Properties, CA, DA, I, and S. CA is a fixed size C-Style array. This will generate 1 Parent Command and 1 Child Command for each element in the array. DA is a dynamic array (TArray). This will generate only 1 Parent Command and 1 Child Command, both referencing the array. Additionally, Child Commands will be added recursively for the element type of the array. S is a UStruct. All struct types generate 1 Parent Command for the Struct Property. Additionally: If the struct has a native NetSerialize method then it will generate 1 Child Command referencing the struct. If the struct has a native NetDeltaSerialize method then it will generate no Child Commands. All other structs will recursively generate Child Commands for each nested Net Property in the struct. Note, in this case there is no Child Command associated with the top level struct property. I is an integer (or other supported non-Struct type, or object reference). This will generate 1 Parent Command and 1 Child Command.
CHANGELISTS
Along with Layout Commands that describe the Properties in a type, RepLayout uses changelists to know what Properties have changed between frames.
See also
FRepChangedHistory.
Changelists are arrays of Property Handles that describe what Properties have changed, however they don't track the actual values of the Properties.
Changelists can contain "sub-changelists" for arrays. Formally, they can be described as the following grammar:
Terminator          ::= 0
Handle              ::= Integer between 1 ~ 65535
Number              ::= Integer between 0 ~ 65535
Changelist          ::= <Terminator> | <Handle><Changelist> | <Handle><Array-Changelist><Changelist>
Array-Changelist:   ::= <Number><Changelist>
An important distinction is that Handles do not have a 1:1 mapping with RepLayoutCommands. Handles are 1-based (as opposed to 0-based), and track a relative command index within a single level of a changelist. Each Array Command, regardless of the number of child Commands it has, will only be count as a single handle in its owning changelist. Each time we recurse into an Array-Changelist, our handles restart at 1 for that "depth", and they correspond to the Commands associated with the Array's element type.
In order to generate Changelists, Layout Commands are sequentially applied that compare the values of an object's cached state to a object's current state. Any properties that are found to be different will have their handle written into the changelist. This means handles within a changelists are inherently ordered (with arrays inserted whose Handles are also ordered).
When we want to replicate properties for an object, merge together any outstanding changelists and then iterate over it using Layout Commands that serialize the necessary property data.
Receiving is very similar, except the Handles are baked into the serialized data so no explicit changelist is required. As each Handle is read, a Layout Command is applied that serializes the data from the network bunch and applies it to an object.
RETRIES AND RELIABLES
@FSendingRepState maintains a circular buffer that tracks recently sent Changelists (@FRepChangedHistory). These history items track the Changelist alongside the Packet ID that the bunches were sent in.
Once we receive ACKs for all associated packets, the history will be removed from the buffer. If NAKs are received for any of the packets, we will merge the changelist into the next set of properties we replicate.
If we receive no NAKs or ACKs for an extended period, to prevent overflows in the history buffer, we will merge the entire buffer into a single monolithic changelist which will be sent alongside the next set of properties.
In both cases of NAKs or no response, the merged changelists will be tracked in the latest history item alongside with other sent properties.
When "net.PartialBunchReliableThreshold" is non-zero and property data bunches are split into partial bunches above the threshold, we will not generate a history item. Instead, we will rely on the reliable bunch framework for resends and replication of the Object will be completely paused until the property bunches are acknowledged. However, this will not affect other history items since they are still unreliable.
Definition at line 1173 of file RepLayout.h.
Constructor & Destructor Documentation
FRepLayout()
FRepLayout::FRepLayout () private
~FRepLayout()
virtual FRepLayout::~FRepLayout () virtual
Member Function Documentation
AddReferencedObjects()
virtual void FRepLayout::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
BuildChangeList_r()
void FRepLayout::BuildChangeList_r (const TArray< FHandleToCmdIndex > & HandleToCmdIndex, const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, const int32 HandleOffset, const bool bForceArraySends, TArray< uint16 > & Changed) const private
References Changed.
BuildHandleToCmdIndexTable_r()
void FRepLayout::BuildHandleToCmdIndexTable_r (const int32 CmdStart, const int32 CmdEnd, TArray< FHandleToCmdIndex > & HandleToCmdIndex) private
BuildSharedSerialization()
void FRepLayout::BuildSharedSerialization (const FConstRepObjectDataBuffer Data, TArray< uint16 > & Changed, const bool bWriteHandle, FRepSerializationSharedInfo & SharedInfo, UE::Net::FNetTokenStore * NetTokenStore = nullptr) const private
References Changed.
BuildSharedSerialization_r()
void FRepLayout::BuildSharedSerialization_r (FRepHandleIterator & RepHandleIterator, const FConstRepObjectDataBuffer SourceData, const bool bWriteHandle, const bool bDoChecksum, const int32 ArrayDepth, FRepSerializationSharedInfo & SharedInfo) const private
BuildSharedSerializationForRPC()
void FRepLayout::BuildSharedSerializationForRPC (const FConstRepObjectDataBuffer Data, UE::Net::FNetTokenStore * NetTokenStore = nullptr)
Builds shared serialization state for a multicast rpc.
References BuildSharedSerializationForRPC().
Referenced by BuildSharedSerializationForRPC().
BuildSharedSerializationForRPC_DynamicArray_r()
void FRepLayout::BuildSharedSerializationForRPC_DynamicArray_r (const int32 CmdIndex, const FConstRepObjectDataBuffer Data, int32 ArrayDepth, FRepSerializationSharedInfo & SharedInfo) private
BuildSharedSerializationForRPC_r()
void FRepLayout::BuildSharedSerializationForRPC_r (const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, int32 ArrayIndex, int32 ArrayDepth, FRepSerializationSharedInfo & SharedInfo) private
CallRepNotifies()
void FRepLayout::CallRepNotifies (FReceivingRepState * RepState, UObject * Object) const
Fire any RepNotifies that have been queued for an object while receiving properties.
Parameters
RepState The ReceivingRepState associated with the Object. This is expected to be valid.
Object The Object that received properties.
References CallRepNotifies(), and Object.
Referenced by CallRepNotifies().
ClearSharedSerializationForRPC()
void FRepLayout::ClearSharedSerializationForRPC ()
Clears shared serialization state for a multicast rpc.
References ClearSharedSerializationForRPC().
Referenced by ClearSharedSerializationForRPC().
CompareProperties()
ERepLayoutResult FRepLayout::CompareProperties (FSendingRepState *RESTRICT RepState, FRepChangelistState *RESTRICT RepChangelistState, const FConstRepObjectDataBuffer Data, const FReplicationFlags & RepFlags, const bool bForceCompare) const private
Compare Property Values currently stored in the Changelist State to the Property Values in the passed in data, generating a new changelist if necessary.
Parameters
RepState RepState for the object.
RepChangelistState The FRepChangelistState that contains the last cached values and changelists.
Data The newest Property Data available.
RepFlags Flags that will be used if the object is replicated.
bForceCompare Compare the property even if the dirty flag is not set.
References RESTRICT.
ConstructProperties()
void FRepLayout::ConstructProperties (FRepStateStaticBuffer & ShadowData) const private
References FRepStateStaticBuffer.
CopyProperties()
void FRepLayout::CopyProperties (FRepStateStaticBuffer & ShadowData, const FConstRepObjectDataBuffer Source) const private
References FRepStateStaticBuffer, and Source.
CountBytes()
void FRepLayout::CountBytes (FArchive & Ar) const
References Ar.
CreateFromClass()
TSharedPtr< FRepLayout > FRepLayout::CreateFromClass (UClass * InObjectClass, const UNetConnection * ServerConnection = nullptr, const ECreateRepLayoutFlags Flags = ECreateRepLayoutFlags::None) static
Creates a new FRepLayout for the given class.
References Flags, and None.
CreateFromFunction()
TSharedPtr< FRepLayout > FRepLayout::CreateFromFunction (UFunction * InFunction, const UNetConnection * ServerConnection = nullptr, const ECreateRepLayoutFlags Flags = ECreateRepLayoutFlags::None) static
Creates a new FRepLayout for the given function.
References Flags, and None.
CreateFromStruct()
TSharedPtr< FRepLayout > FRepLayout::CreateFromStruct (UStruct * InStruct, const UNetConnection * ServerConnection = nullptr, const ECreateRepLayoutFlags Flags = ECreateRepLayoutFlags::None) static
Creates a new FRepLayout for the given struct.
References Flags, and None.
CreateNetfieldExportGroup()
TSharedPtr< FNetFieldExportGroup > FRepLayout::CreateNetfieldExportGroup () const private
CreateReplicationChangelistMgr()
TSharedPtr< FReplicationChangelistMgr > FRepLayout::CreateReplicationChangelistMgr (const UObject * InObject, const ECreateReplicationChangelistMgrFlags CreateFlags) const
Creates and initializes a new FReplicationChangelistMgr.
Parameters
InObject The Object that is being managed.
CreateFlags Flags modifying how the manager is created.
CreateRepState()
TUniquePtr< FRepState > FRepLayout::CreateRepState (const FConstRepObjectDataBuffer Source, TSharedPtr< FRepChangedPropertyTracker > & InRepChangedPropertyTracker, ECreateRepStateFlags Flags) const
Creates and initializes a new FRepState.
This includes:
Initializing the ShadowData.
Associating and validating the appropriate ChangedPropertyTracker.
Building initial ConditionMap.
Parameters
RepState The RepState to initialize.
Class The class of the object represented by the input memory.
Src Memory buffer storing object property data.
InRepChangedPropertyTracker The PropertyTracker we want to associate with the RepState.
Returns
A new RepState. Note, maybe a a FRepStateBase or FRepStateSending based on parameters.
References Flags, and Source.
CreateShadowBuffer()
FRepStateStaticBuffer FRepLayout::CreateShadowBuffer (const FConstRepObjectDataBuffer Source) const
Creates and initialize a new Shadow Buffer.
Shadow Data / Shadow States are used to cache property data so that the Object's state can be compared between frames to see if any properties have changed. They are also used on clients to keep track of RepNotify state.
This includes:
Allocating memory for all Properties in the class.
Constructing instances of each Property.
Copying the values of the Properties from given object.
Parameters
Source Memory buffer storing object property data.
References FRepStateStaticBuffer, and Source.
DeltaSerializeFastArrayProperty()
ERepLayoutResult FRepLayout::DeltaSerializeFastArrayProperty (struct FFastArrayDeltaSerializeParams & Params, FReplicationChangelistMgr * ChangelistMgr) const private
References Params.
DestructProperties()
void FRepLayout::DestructProperties (FRepStateStaticBuffer & RepStateStaticBuffer) const private
References FRepStateStaticBuffer.
DiffProperties()
template<ERepDataBufferType DstType, ERepDataBufferType SrcType> bool FRepLayout::DiffProperties (TArray< FProperty * > * RepNotifies, TRepDataBuffer< DstType > Destination, TConstRepDataBuffer< SrcType > Source, const EDiffPropertiesFlags Flags) const
Compare all properties between source and destination buffer, and optionally update the destination buffer to match the state of the source buffer if they don't match.
Parameters
RepNotifies RepNotifies that should be fired if we're changing properties.
Destination Destination buffer that will be changed if we're changing properties.
Source Source buffer containing desired property values.
Flags Controls how DiffProperties behaves.
Returns
True if there were any properties with different values.
References DiffProperties(), Flags, RepNotifies, and Source.
Referenced by DiffProperties().
DiffStableProperties()
template<ERepDataBufferType DstType, ERepDataBufferType SrcType> bool FRepLayout::DiffStableProperties (TArray< FProperty * > * RepNotifies, TArray< UObject * > * ObjReferences, TRepDataBuffer< DstType > Destination, TConstRepDataBuffer< SrcType > Source) const
See also
DiffProperties
The main difference between this method and DiffProperties is that this method will skip any properties that are:
Transient
Point to Actors or ActorComponents
Point to Objects that are non-stably named for networking.
Parameters
RepNotifies RepNotifies that should be fired if we're changing properties.
Destination Destination buffer that will be changed if we're changing properties.
Source Source buffer containing desired property values.
Flags Controls how DiffProperties behaves.
Returns
True if there were any properties with different values.
References DiffStableProperties(), RepNotifies, and Source.
Referenced by DiffStableProperties().
FilterChangeList()
void FRepLayout::FilterChangeList (const TArray< uint16 > & Changelist, const TBitArray<> & InactiveParentHandles, TArray< uint16 > & OutInactiveProperties, TArray< uint16 > & OutActiveProperties) const private
Splits a given Changelist into an Inactive Change List and an Active Change List.
Parameters
Changelist The Changelist to filter.
InactiveParentHandles The set of ParentCmd Indices that are not active.
OutInactiveProperties The properties found to be inactive.
OutActiveProperties The properties found to be active.
References Changelist.
FilterChangeListToActive()
void FRepLayout::FilterChangeListToActive (const TArray< uint16 > & Changelist, const TBitArray<> & InactiveParentHandles, TArray< uint16 > & OutActiveProperties) const private
Same as FilterChangeList, but only populates an Active Change List.
References Changelist.
FindCompatibleProperty()
int32 FRepLayout::FindCompatibleProperty (const int32 CmdStart, const int32 CmdEnd, const uint32 Checksum) const private
GatherGuidReferences()
void FRepLayout::GatherGuidReferences (FReceivingRepState *RESTRICT RepState, struct FNetDeltaSerializeInfo & Params, TSet< FNetworkGUID > & OutReferencedGuids, int32 & OutTrackedGuidMemoryBytes) const
Finds any properties in the Shadow Buffer of the given Rep State that are currently valid (mapped or unmapped) references to other network objects, and retrieves the associated Net GUIDS.
Parameters
RepState The RepState whose shadow buffer we'll inspect. This is expected to be valid.
OutReferencedGuids Set of Net GUIDs being referenced by the RepState.
OutTrackedGuidMemoryBytes Total memory usage of properties containing GUID references.
References GatherGuidReferences(), Params, and RESTRICT.
Referenced by GatherGuidReferences().
GatherGuidReferences_r()
void FRepLayout::GatherGuidReferences_r (const FGuidReferencesMap * GuidReferencesMap, TSet< FNetworkGUID > & OutReferencedGuids, int32 & OutTrackedGuidMemoryBytes) const private
GatherGuidReferencesForFastArray()
void FRepLayout::GatherGuidReferencesForFastArray (struct FFastArrayDeltaSerializeParams & Params) const private
References Params.
GenerateChecksum()
uint32 FRepLayout::GenerateChecksum (const FRepState * RepState) const
References GenerateChecksum().
Referenced by GenerateChecksum().
GetCustomDeltaIndexFromPropertyRepIndex()
const uint16 FRepLayout::GetCustomDeltaIndexFromPropertyRepIndex (const uint16 PropertyRepIndex) const
GetFlags()
const ERepLayoutFlags FRepLayout::GetFlags () const inline
Definition at line 1496 of file RepLayout.h.
References Flags.
GetLifetimeCustomDeltaProperty()
FProperty * FRepLayout::GetLifetimeCustomDeltaProperty (const uint16 CustomDeltaPropertyIndex) const private
GetLifetimeCustomDeltaPropertyCondition()
const ELifetimeCondition FRepLayout::GetLifetimeCustomDeltaPropertyCondition (const uint16 RepIndCustomDeltaPropertyIndex) const private
GetLifetimeCustomDeltaPropertyRepIndex()
const uint16 FRepLayout::GetLifetimeCustomDeltaPropertyRepIndex (const uint16 RepIndCustomDeltaPropertyIndex) const private
GetNumLifetimeCustomDeltaProperties()
const uint16 FRepLayout::GetNumLifetimeCustomDeltaProperties () const private
GetNumParents()
const int32 FRepLayout::GetNumParents () const inline
Definition at line 1506 of file RepLayout.h.
References Parents.
GetOwner()
UObject * FRepLayout::GetOwner () const inline
Definition at line 1436 of file RepLayout.h.
References GetOwner(), and Owner.
Referenced by GetOwner().
GetParentArrayIndex()
const int32 FRepLayout::GetParentArrayIndex (int32 Index) const inline
Definition at line 1516 of file RepLayout.h.
References Parents.
GetParentCondition()
const int32 FRepLayout::GetParentCondition (int32 Index) const inline
Definition at line 1521 of file RepLayout.h.
References Parents.
GetParentProperty()
const FProperty * FRepLayout::GetParentProperty (int32 Index) const inline
Definition at line 1511 of file RepLayout.h.
References Parents.
GetReferencerName()
virtual FString FRepLayout::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
GetShadowStateValue() [1/2]
template<typename T> const T * FRepLayout::GetShadowStateValue (FConstRepShadowDataBuffer Data, const FName PropertyName) const inline
Definition at line 1483 of file RepLayout.h.
References Parent, Parents, and PropertyName.
GetShadowStateValue() [2/2]
template<typename T> T * FRepLayout::GetShadowStateValue (FRepShadowDataBuffer Data, const FName PropertyName) inline
Gets a pointer to the value of the given property in the Shadow State.
Returns
A pointer to the property value in the shadow state, or nullptr if the property wasn't found.
Definition at line 1469 of file RepLayout.h.
References Parent, Parents, and PropertyName.
InitFromClass()
void FRepLayout::InitFromClass (UClass * InObjectClass, const UNetConnection * ServerConnection, const ECreateRepLayoutFlags Flags) private
References Flags.
InitFromFunction()
void FRepLayout::InitFromFunction (UFunction * InFunction, const UNetConnection * ServerConnection, const ECreateRepLayoutFlags Flags) private
References Flags.
InitFromStruct()
void FRepLayout::InitFromStruct (UStruct * InStruct, const UNetConnection * ServerConnection, const ECreateRepLayoutFlags Flags) private
References Flags.
InitRepStateStaticBuffer()
void FRepLayout::InitRepStateStaticBuffer (FRepStateStaticBuffer & ShadowData, const FConstRepObjectDataBuffer Source) const private
References FRepStateStaticBuffer, and Source.
IsCustomDeltaProperty()
const bool FRepLayout::IsCustomDeltaProperty (int32 Index) const inline
Definition at line 1526 of file RepLayout.h.
References EnumHasAnyFlags(), Flags, IsCustomDelta, and Parents.
IsEmpty()
const bool FRepLayout::IsEmpty () const inline
Definition at line 1501 of file RepLayout.h.
References EnumHasAnyFlags(), Flags, NoReplicatedProperties, and Parents.
MergeChangeList()
void FRepLayout::MergeChangeList (const FConstRepObjectDataBuffer Data, const TArray< uint16 > & Dirty1, const TArray< uint16 > & Dirty2, TArray< uint16 > & MergedDirty) const private
MergeChangeList_r()
void FRepLayout::MergeChangeList_r (FRepHandleIterator & RepHandleIterator1, FRepHandleIterator & RepHandleIterator2, const FConstRepObjectDataBuffer SourceData, TArray< uint16 > & OutChanged) const private
MoveMappedObjectToUnmapped()
bool FRepLayout::MoveMappedObjectToUnmapped (FReceivingRepState *RESTRICT RepState, struct FNetDeltaSerializeInfo & Params, const FNetworkGUID & GUID) const
Called to indicate that the object referenced by the FNetworkGUID is no longer mapped.
This can happen if the Object was destroyed, if its level was streamed out, or for any other reason that may cause the Server (or client) to no longer be able to properly reference the object. Note, it's possible the object may become valid again later.
Parameters
RepState The RepState that holds a reference to the object. This is expected to be valid.
GUID The Network GUID of the object to unmap.
Params Delta Serialization Params used for Custom Delta Properties.
References MoveMappedObjectToUnmapped(), Params, and RESTRICT.
Referenced by MoveMappedObjectToUnmapped().
MoveMappedObjectToUnmapped_r()
bool FRepLayout::MoveMappedObjectToUnmapped_r (FGuidReferencesMap * GuidReferencesMap, const FNetworkGUID & GUID, const UObject *const OwningObject) const private
MoveMappedObjectToUnmappedForFastArray()
bool FRepLayout::MoveMappedObjectToUnmappedForFastArray (struct FFastArrayDeltaSerializeParams & Params) const private
References Params.
PostSendCustomDeltaProperties()
void FRepLayout::PostSendCustomDeltaProperties (UObject * Object, UNetConnection * Connection, FReplicationChangelistMgr & ChangelistMgr, TArray< TSharedPtr< INetDeltaBaseState > > & CustomDeltaStates) const private
References Object.
PreSendCustomDeltaProperties()
void FRepLayout::PreSendCustomDeltaProperties (UObject * Object, UNetConnection * Connection, FReplicationChangelistMgr & ChangelistMgr, uint32 ReplicationFrame, TArray< TSharedPtr< INetDeltaBaseState > > & CustomDeltaStates) const private
References Object.
PruneChangeList()
void FRepLayout::PruneChangeList (const FConstRepObjectDataBuffer Data, const TArray< uint16 > & Changed, TArray< uint16 > & PrunedChanged) const private
Clamps a changelist so that it conforms to the current size of either an array, or arrays within structs/arrays.
Parameters
Data Object memory.
Changed The changelist to prune.
PrunedChanged The resulting pruned changelist.
References Changed.
PruneChangeList_r()
void FRepLayout::PruneChangeList_r (FRepHandleIterator & RepHandleIterator, const FConstRepObjectDataBuffer SourceData, TArray< uint16 > & OutChanged) const private
RebuildConditionalProperties()
void FRepLayout::RebuildConditionalProperties (FSendingRepState * RepState, const FReplicationFlags RepFlags) const private
ReceiveCustomDeltaProperty()
bool FRepLayout::ReceiveCustomDeltaProperty (FReceivingRepState *RESTRICT ReceivingRepState, FNetDeltaSerializeInfo & Params, FStructProperty * Property) const private
Attempts to receive the custom delta property.
Parameters
Params Params that we'll use to receive. The PackageMap member must be non null. The Object member must be non null. The Reader member must be non null.
Property The Property that we're trying to received. This is expected to be a valid Replicated property that is a CustomDelta type.
References Params, Property, and RESTRICT.
ReceiveProperties()
bool FRepLayout::ReceiveProperties (UActorChannel * OwningChannel, UClass * InObjectClass, FReceivingRepState *RESTRICT RepState, UObject * Object, FNetBitReader & InBunch, bool & bOutHasUnmapped, bool & bOutGuidsChanged, const EReceivePropertiesFlags InFlags) const
Reads all property values from the received buffer, and applies them to the property memory.
Parameters
OwningChannel The channel of the Actor that owns the object whose properties we're reading.
InObjectClass Class of the object.
RepState RepState for the object. This is expected to be valid.
Data Pointer to memory where read property data should be stored.
InBunch The data that should be read.
bOutHasUnmapped Whether or not unmapped GUIDs were read.
bOutGuidsChanged Whether or not any GUIDs were changed.
Flags Controls how ReceiveProperties behaves.
References Object, ReceiveProperties(), and RESTRICT.
Referenced by ReceiveProperties().
ReceiveProperties_BackwardsCompatible()
bool FRepLayout::ReceiveProperties_BackwardsCompatible (UNetConnection * Connection, FReceivingRepState *RESTRICT RepState, FRepObjectDataBuffer Data, FNetBitReader & InBunch, bool & bOutHasUnmapped, const bool bEnableRepNotifies, bool & bOutGuidsChanged, UObject * OwningObject = nullptr) const
Currently only used for Replays / with the UDemoNetDriver.
References RESTRICT.
ReceiveProperties_BackwardsCompatible_r()
bool FRepLayout::ReceiveProperties_BackwardsCompatible_r (FReceivingRepState *RESTRICT RepState, FNetFieldExportGroup * NetFieldExportGroup, FNetBitReader & Reader, const int32 CmdStart, const int32 CmdEnd, FRepShadowDataBuffer ShadowData, FRepObjectDataBuffer OldData, FRepObjectDataBuffer Data, FGuidReferencesMap * GuidReferencesMap, bool & bOutHasUnmapped, bool & bOutGuidsChanged, UObject * OwningObject) const private
References RESTRICT.
ReceivePropertiesForRPC()
void FRepLayout::ReceivePropertiesForRPC (UObject * Object, UFunction * Function, UActorChannel * Channel, FNetBitReader & Reader, FRepObjectDataBuffer Data, TSet< FNetworkGUID > & UnmappedGuids) const
See also
ReceiveProperties.
References Function, Object, and ReceivePropertiesForRPC().
Referenced by ReceivePropertiesForRPC().
ReplicateProperties()
bool FRepLayout::ReplicateProperties (FSendingRepState *RESTRICT RepState, FRepChangelistState *RESTRICT RepChangelistState, const FConstRepObjectDataBuffer Data, UClass * ObjectClass, UActorChannel * OwningChannel, FNetBitWriter & Writer, const FReplicationFlags & RepFlags) const
Writes out any changed properties for an Object into the given data buffer, and does book keeping for the RepState of the object.
Note, this does not compare properties or send them on the wire, it's only used to serialize properties.
Parameters
RepState RepState for the object. This is expected to be valid.
RepChangelistState RepChangelistState for the object.
Data Pointer to memory where property data is stored.
ObjectClass Class of the object.
Writer Writer used to store / write out the replicated properties.
RepFlags Flags used for replication.
References ReplicateProperties(), and RESTRICT.
Referenced by ReplicateProperties().
SanityCheckChangeList()
void FRepLayout::SanityCheckChangeList (const FConstRepObjectDataBuffer Data, TArray< uint16 > & Changed) const private
References Changed.
SanityCheckChangeList_DynamicArray_r()
void FRepLayout::SanityCheckChangeList_DynamicArray_r (const int32 CmdIndex, const FConstRepObjectDataBuffer Data, TArray< uint16 > & Changed, int32 & ChangedIndex) const private
References Changed.
SanityCheckChangeList_r()
uint16 FRepLayout::SanityCheckChangeList_r (const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer Data, TArray< uint16 > & Changed, int32 & ChangedIndex, uint16 Handle) const private
References Changed, and Handle.
SendAllProperties_BackwardsCompatible_r()
void FRepLayout::SendAllProperties_BackwardsCompatible_r (FSendingRepState *RESTRICT RepState, FNetBitWriter & Writer, const bool bDoChecksum, UPackageMapClient * PackageMapClient, FNetFieldExportGroup * NetFieldExportGroup, const int32 CmdStart, const int32 CmdEnd, const FConstRepObjectDataBuffer SourceData) const private
References RESTRICT, and UPackageMapClient.
SendCustomDeltaProperty()
bool FRepLayout::SendCustomDeltaProperty (FNetDeltaSerializeInfo & Params, const uint16 CustomDeltaIndex) const private
Parameters
CustomDeltaIndex The index of the Custom Delta Property. This is not the same as FProperty::RepIndex!
See also
FLifetimeCustomDeltaState.
References Params.
SendProperties()
void FRepLayout::SendProperties (FSendingRepState *RESTRICT RepState, FRepChangedPropertyTracker * ChangedTracker, const FConstRepObjectDataBuffer Data, UClass * ObjectClass, FNetBitWriter & Writer, TArray< uint16 > & Changed, const FRepSerializationSharedInfo & SharedInfo, const ESerializePropertyType SerializePropertyType) const private
Writes all changed property values from the input owner data to the given buffer.
This is used primarily by ReplicateProperties.
Note, the changelist is expected to have any conditional properties whose conditions aren't met filtered out already. See FRepState::ConditionMap and FRepLayout::FilterChangeList
Parameters
RepState RepState for the object. This is expected to be valid.
ChangedTracker Used to indicate
Data Pointer to the object's memory.
ObjectClass Class of the object.
Writer Writer used to store / write out the replicated properties.
Changed Aggregate list of property handles that need to be written.
SharedInfo Shared Serialization state for properties.
References Changed, and RESTRICT.
SendProperties_BackwardsCompatible()
void FRepLayout::SendProperties_BackwardsCompatible (FSendingRepState *RESTRICT RepState, FRepChangedPropertyTracker * ChangedTracker, const FConstRepObjectDataBuffer Data, UNetConnection * Connection, FNetBitWriter & Writer, TArray< uint16 > & Changed) const
Currently only used for Replays / with the UDemoNetDriver.
References Changed, and RESTRICT.
SendProperties_BackwardsCompatible_r()
void FRepLayout::SendProperties_BackwardsCompatible_r (FSendingRepState *RESTRICT RepState, UPackageMapClient * PackageMapClient, FNetFieldExportGroup * NetFieldExportGroup, FRepChangedPropertyTracker * ChangedTracker, FNetBitWriter & Writer, const bool bDoChecksum, FRepHandleIterator & HandleIterator, const FConstRepObjectDataBuffer Source) const private
References RESTRICT, Source, and UPackageMapClient.
SendProperties_r()
void FRepLayout::SendProperties_r (FSendingRepState *RESTRICT RepState, FNetBitWriter & Writer, const bool bDoChecksum, FRepHandleIterator & HandleIterator, const FConstRepObjectDataBuffer SourceData, const int32 ArrayDepth, const FRepSerializationSharedInfo *const RESTRICT SharedInfo, const ESerializePropertyType SerializePropertyType) const private
References RESTRICT.
SendPropertiesForRPC()
void FRepLayout::SendPropertiesForRPC (UFunction * Function, UActorChannel * Channel, FNetBitWriter & Writer, const FConstRepObjectDataBuffer Data) const
See also
SendProperties.
References Function, and SendPropertiesForRPC().
Referenced by SendPropertiesForRPC().
SerializeObjectReplicatedProperties()
void FRepLayout::SerializeObjectReplicatedProperties (UObject * Object, FBitArchive & Ar) const
Serializes all replicated properties of a UObject in or out of an archive (depending on what type of archive it is).
References Ar, Object, and SerializeObjectReplicatedProperties().
Referenced by SerializeObjectReplicatedProperties().
SerializeProperties_DynamicArray_r()
void FRepLayout::SerializeProperties_DynamicArray_r (FBitArchive & Ar, UPackageMap * Map, const int32 CmdIndex, FRepObjectDataBuffer Data, bool & bHasUnmapped, const int32 ArrayDepth, const FRepSerializationSharedInfo & SharedInfo, FNetTraceCollector * Collector, const UObject * OwningObject) const private
References Ar, and Map.
SerializeProperties_r()
void FRepLayout::SerializeProperties_r (FBitArchive & Ar, UPackageMap * Map, const int32 CmdStart, const int32 CmdEnd, FRepObjectDataBuffer Data, bool & bHasUnmapped, const int32 ArrayIndex, const int32 ArrayDepth, const FRepSerializationSharedInfo & SharedInfo, FNetTraceCollector * Collector, const UObject * OwningObject) const private
References Ar, and Map.
SerializePropertiesForStruct()
void FRepLayout::SerializePropertiesForStruct (UStruct * Struct, FBitArchive & Ar, UPackageMap * Map, FRepObjectDataBuffer Data, bool & bHasUnmapped, const UObject * OwningObject = nullptr) const
References Ar, Map, SerializePropertiesForStruct(), and Struct.
Referenced by SerializePropertiesForStruct().
UE_DEPRECATED()
FRepLayout::UE_DEPRECATED (5. 1, "No longer used, trackers are initialized by the replication subsystem.") const
UpdateChangelistHistory()
void FRepLayout::UpdateChangelistHistory (FSendingRepState * RepState, UClass * ObjectClass, const FConstRepObjectDataBuffer Data, UNetConnection * Connection, TArray< uint16 > * OutMerged) const private
UpdateChangelistMgr()
ERepLayoutResult FRepLayout::UpdateChangelistMgr (FSendingRepState *RESTRICT RepState, FReplicationChangelistMgr & InChangelistMgr, const UObject * InObject, const uint32 ReplicationFrame, const FReplicationFlags & RepFlags, const bool bForceCompare) const private
References RESTRICT.
UpdateUnmappedGuidsForFastArray()
void FRepLayout::UpdateUnmappedGuidsForFastArray (struct FFastArrayDeltaSerializeParams & Params) const private
References Params.
UpdateUnmappedObjects()
void FRepLayout::UpdateUnmappedObjects (FReceivingRepState *RESTRICT RepState, UPackageMap * PackageMap, UObject * Object, struct FNetDeltaSerializeInfo & Params, bool & bCalledPreNetReceive, bool & bOutSomeObjectsWereMapped, bool & bOutHasMoreUnmapped) const
Attempts to update any unmapped network guids referenced by the RepState.
If any guids become mapped, we will update corresponding properties on the given object to point to the referenced object.
Parameters
RepState The RepState associated with the Object. This is expected to be valid.
PackageMap The package map that controls FNetworkGUID associations.
Object The live game object whose properties should be updated if we map any objects.
bOutSomeObjectsWereMapped Whether or not we successfully mapped any references.
bOutHasMoreUnamapped Whether or not there are more unmapped references in the RepState.
References Object, Params, RESTRICT, and UpdateUnmappedObjects().
Referenced by UpdateUnmappedObjects().
UpdateUnmappedObjects_r()
void FRepLayout::UpdateUnmappedObjects_r (FReceivingRepState *RESTRICT RepState, FGuidReferencesMap * GuidReferencesMap, UObject * OriginalObject, UNetConnection * Connection, FRepShadowDataBuffer ShadowData, FRepObjectDataBuffer Data, const int32 MaxAbsOffset, bool & bCalledPreNetReceive, bool & bOutSomeObjectsWereMapped, bool & bOutHasMoreUnmapped) const private
References RESTRICT.
ValidateWithChecksum()
template<ERepDataBufferType DataType> void FRepLayout::ValidateWithChecksum (TConstRepDataBuffer< DataType > Data, FBitArchive & Ar) const
References Ar, and ValidateWithChecksum().
Referenced by ValidateWithChecksum().
Friends And Related Symbol Documentation
FCustomDeltaPropertyIterator
friend struct FCustomDeltaPropertyIterator friend
Definition at line 1180 of file RepLayout.h.
References FCustomDeltaPropertyIterator.
Referenced by FCustomDeltaPropertyIterator.
FNetSerializeCB
friend class FNetSerializeCB friend
Definition at line 1179 of file RepLayout.h.
References FNetSerializeCB.
Referenced by FNetSerializeCB.
FRepStateStaticBuffer
friend struct FRepStateStaticBuffer friend
Definition at line 1177 of file RepLayout.h.
References FRepStateStaticBuffer.
Referenced by ConstructProperties(), CopyProperties(), CreateShadowBuffer(), DestructProperties(), FRepStateStaticBuffer, and InitRepStateStaticBuffer().
UPackageMapClient
friend class UPackageMapClient friend
Definition at line 1178 of file RepLayout.h.
References UPackageMapClient.
Referenced by SendAllProperties_BackwardsCompatible_r(), SendProperties_BackwardsCompatible_r(), and UPackageMapClient.
Field Documentation
BaseHandleToCmdIndex
TArray<FHandleToCmdIndex> FRepLayout::BaseHandleToCmdIndex private
Converts a relative handle to the appropriate index into the Cmds array.
Definition at line 1887 of file RepLayout.h.
Cmds
TArray<FRepLayoutCmd> FRepLayout::Cmds private
All Layout Commands.
Definition at line 1884 of file RepLayout.h.
Flags
ERepLayoutFlags FRepLayout::Flags private
Definition at line 1875 of file RepLayout.h.
Referenced by CreateFromClass(), CreateFromFunction(), CreateFromStruct(), CreateRepState(), DiffProperties(), GetFlags(), InitFromClass(), InitFromFunction(), InitFromStruct(), IsCustomDeltaProperty(), and IsEmpty().
LifetimeCustomPropertyState
TUniquePtr<struct FLifetimeCustomDeltaState> FRepLayout::LifetimeCustomPropertyState private
Special state tracking for Lifetime Custom Delta Properties.
Will only ever be valid if the Layout has Lifetime Custom Delta Properties.
Definition at line 1893 of file RepLayout.h.
NetSerializeLayouts
TMap<FRepLayoutCmd*, TArray<FRepLayoutCmd> > FRepLayout::NetSerializeLayouts private
Definition at line 1909 of file RepLayout.h.
Owner
UStruct* FRepLayout::Owner private
UClass, UStruct, or UFunction that this FRepLayout represents.
Definition at line 1896 of file RepLayout.h.
Referenced by GetOwner().
Parents
TArray<FRepParentCmd> FRepLayout::Parents private
Top level Layout Commands.
Definition at line 1881 of file RepLayout.h.
Referenced by GetNumParents(), GetParentArrayIndex(), GetParentCondition(), GetParentProperty(), GetShadowStateValue(), GetShadowStateValue(), IsCustomDeltaProperty(), and IsEmpty().
ShadowDataBufferSize
int32 FRepLayout::ShadowDataBufferSize private
Size (in bytes) needed to allocate a single instance of a Shadow buffer for this RepLayout.
Definition at line 1878 of file RepLayout.h.
SharedInfoRPC
FRepSerializationSharedInfo FRepLayout::SharedInfoRPC private
Shared serialization state for a multicast rpc.
Definition at line 1899 of file RepLayout.h.
SharedInfoRPCParentsChanged
TBitArray FRepLayout::SharedInfoRPCParentsChanged private
Shared comparison to default state for multicast rpc.
Definition at line 1902 of file RepLayout.h.
The documentation for this class was generated from the following file:
RepLayout.h