Unreal Engine 5.6 C++ API: FRenderTargetBinding Struct Reference
FRenderTargetBinding Struct Reference
Render graph information about how to bind a render target.
#include "ShaderParameterMacros.h"
Public Member Functions
FRenderTargetBinding ()=default
FRenderTargetBinding (FRDGTexture *InTexture, ERenderTargetLoadAction InLoadAction, uint8 InMipIndex=0, int16 InArraySlice=-1)
FRenderTargetBinding (FRDGTexture *InTexture, FRDGTexture *InResolveTexture, ERenderTargetLoadAction InLoadAction, uint8 InMipIndex=0, int16 InArraySlice=-1)
bool CanMergeBefore (const FRenderTargetBinding &Other) const
Whether we can merge a render pass using Other into a render pass using this render target binding.
int16 GetArraySlice () const
ERenderTargetLoadAction GetLoadAction () const
uint8 GetMipIndex () const
FRDGTexture * GetResolveTexture () const
FRDGTexture * GetTexture () const
void SetArraySlice (int16 InArraySlice)
void SetLoadAction (ERenderTargetLoadAction InLoadAction)
void SetMipIndex (uint8 InMipIndex)
void SetResolveTexture (FRDGTexture *InTexture)
void SetTexture (FRDGTexture *InTexture)
UE_DEPRECATED (5.1, "GetMipIndex has been renamed to SetMipIndex.") void GetMipIndex(uint8 InMipIndex)
Private Member Functions
RENDERCORE_API bool Validate () const
Private Attributes
int16 ArraySlice = -1
ERenderTargetLoadAction LoadAction = ERenderTargetLoadAction::ENoAction
uint8 MipIndex = 0
TAlignedShaderParameterPtr< FRDGTexture * > ResolveTexture = nullptr
TAlignedShaderParameterPtr< FRDGTexture * > Texture = nullptr
Intentionally kept private to force setting the load action in the constructor.
Detailed Description
Render graph information about how to bind a render target.
Definition at line 523 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FRenderTargetBinding() [1/3]
FRenderTargetBinding::FRenderTargetBinding () default
Referenced by CanMergeBefore().
FRenderTargetBinding() [2/3]
FRenderTargetBinding::FRenderTargetBinding (FRDGTexture * InTexture, ERenderTargetLoadAction InLoadAction, uint8 InMipIndex = 0, int16 InArraySlice = -1) inline
Definition at line 527 of file ShaderParameterMacros.h.
References ArraySlice, check, LoadAction, MipIndex, Texture, and Validate().
FRenderTargetBinding() [3/3]
FRenderTargetBinding::FRenderTargetBinding (FRDGTexture * InTexture, FRDGTexture * InResolveTexture, ERenderTargetLoadAction InLoadAction, uint8 InMipIndex = 0, int16 InArraySlice = -1) inline
Definition at line 536 of file ShaderParameterMacros.h.
References ArraySlice, check, LoadAction, MipIndex, ResolveTexture, Texture, and Validate().
Member Function Documentation
CanMergeBefore()
bool FRenderTargetBinding::CanMergeBefore (const FRenderTargetBinding & Other) const inline
Whether we can merge a render pass using Other into a render pass using this render target binding.
Definition at line 572 of file ShaderParameterMacros.h.
References FRenderTargetBinding(), ArraySlice, MipIndex, Other, ResolveTexture, and Texture.
GetArraySlice()
int16 FRenderTargetBinding::GetArraySlice () const inline
Definition at line 566 of file ShaderParameterMacros.h.
References ArraySlice.
GetLoadAction()
ERenderTargetLoadAction FRenderTargetBinding::GetLoadAction () const inline
Definition at line 556 of file ShaderParameterMacros.h.
References LoadAction.
GetMipIndex()
uint8 FRenderTargetBinding::GetMipIndex () const inline
Definition at line 561 of file ShaderParameterMacros.h.
References MipIndex.
Referenced by UE_DEPRECATED().
GetResolveTexture()
FRDGTexture * FRenderTargetBinding::GetResolveTexture () const inline
Definition at line 551 of file ShaderParameterMacros.h.
References ResolveTexture.
GetTexture()
FRDGTexture * FRenderTargetBinding::GetTexture () const inline
Definition at line 546 of file ShaderParameterMacros.h.
References Texture.
SetArraySlice()
void FRenderTargetBinding::SetArraySlice (int16 InArraySlice) inline
Definition at line 606 of file ShaderParameterMacros.h.
References ArraySlice, check, and Validate().
SetLoadAction()
void FRenderTargetBinding::SetLoadAction (ERenderTargetLoadAction InLoadAction) inline
Definition at line 594 of file ShaderParameterMacros.h.
References check, LoadAction, and Validate().
SetMipIndex()
void FRenderTargetBinding::SetMipIndex (uint8 InMipIndex) inline
Definition at line 600 of file ShaderParameterMacros.h.
References check, MipIndex, and Validate().
Referenced by UE_DEPRECATED().
SetResolveTexture()
void FRenderTargetBinding::SetResolveTexture (FRDGTexture * InTexture) inline
Definition at line 588 of file ShaderParameterMacros.h.
References check, ResolveTexture, and Validate().
SetTexture()
void FRenderTargetBinding::SetTexture (FRDGTexture * InTexture) inline
Definition at line 582 of file ShaderParameterMacros.h.
References check, Texture, and Validate().
UE_DEPRECATED()
FRenderTargetBinding::UE_DEPRECATED (5. 1, "GetMipIndex has been renamed to SetMipIndex.") inline
Definition at line 612 of file ShaderParameterMacros.h.
References GetMipIndex(), and SetMipIndex().
Validate()
RENDERCORE_API bool FRenderTargetBinding::Validate () const private
Referenced by FRenderTargetBinding(), FRenderTargetBinding(), SetArraySlice(), SetLoadAction(), SetMipIndex(), SetResolveTexture(), and SetTexture().
Field Documentation
ArraySlice
int16 FRenderTargetBinding::ArraySlice = -1 private
Definition at line 621 of file ShaderParameterMacros.h.
Referenced by FRenderTargetBinding(), FRenderTargetBinding(), CanMergeBefore(), GetArraySlice(), and SetArraySlice().
LoadAction
ERenderTargetLoadAction FRenderTargetBinding::LoadAction = ERenderTargetLoadAction::ENoAction private
Definition at line 619 of file ShaderParameterMacros.h.
Referenced by FRenderTargetBinding(), FRenderTargetBinding(), GetLoadAction(), and SetLoadAction().
MipIndex
uint8 FRenderTargetBinding::MipIndex = 0 private
Definition at line 620 of file ShaderParameterMacros.h.
Referenced by FRenderTargetBinding(), FRenderTargetBinding(), CanMergeBefore(), GetMipIndex(), and SetMipIndex().
ResolveTexture
TAlignedShaderParameterPtr<FRDGTexture*> FRenderTargetBinding::ResolveTexture = nullptr private
Definition at line 618 of file ShaderParameterMacros.h.
Referenced by FRenderTargetBinding(), CanMergeBefore(), GetResolveTexture(), and SetResolveTexture().
Texture
TAlignedShaderParameterPtr<FRDGTexture*> FRenderTargetBinding::Texture = nullptr private
Intentionally kept private to force setting the load action in the constructor.
Definition at line 617 of file ShaderParameterMacros.h.
Referenced by FRenderTargetBinding(), FRenderTargetBinding(), CanMergeBefore(), GetTexture(), and SetTexture().
The documentation for this struct was generated from the following file:
ShaderParameterMacros.h