Unreal Engine 5.6 C++ API: UE::Geometry::TTriangle2< RealType > Struct Template Reference
UE::Geometry::TTriangle2< RealType > Struct Template Reference
#include "TriangleTypes.h"
Public Member Functions
TTriangle2 ()
TTriangle2 (const TVector2< RealType > &V0, const TVector2< RealType > &V1, const TVector2< RealType > &V2)
TTriangle2 (const TVector2< RealType > VIn[3])
RealType Area () const
TVector2< RealType > BarycentricPoint (const TVector< RealType > &BaryCoords) const
TVector2< RealType > BarycentricPoint (RealType Bary0, RealType Bary1, RealType Bary2) const
TVector< RealType > GetBarycentricCoords (const TVector2< RealType > &Point) const
bool IsInside (const TVector2< RealType > &QueryPoint) const
bool IsInsideOrOn (const TVector2< RealType > &QueryPoint, RealType Tolerance=0) const
int IsInsideOrOn_Oriented (const TVector2< RealType > &QueryPoint, RealType Tolerance=(RealType) 0) const
More robust (because it doesn't multiply orientation test results) inside-triangle test for oriented triangles only (the code early-outs at the first 'outside' edge, which only works if the triangle is oriented as expected)
RealType SignedArea () const
Static Public Member Functions
static bool IsInside (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C, const TVector2< RealType > &QueryPoint)
static bool IsInsideOrOn (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C, const TVector2< RealType > &QueryPoint, RealType Tolerance=(RealType) 0)
static int IsInsideOrOn_Oriented (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C, const TVector2< RealType > &QueryPoint, RealType Tolerance=(RealType) 0)
More robust (because it doesn't multiply orientation test results) inside-triangle test for oriented triangles only (the code early-outs at the first 'outside' edge, which only works if the triangle is oriented as expected)
static RealType SignedArea (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C)
Data Fields
TVector2< RealType > V [3]
Detailed Description
template<typename RealType>
struct UE::Geometry::TTriangle2< RealType >
Definition at line 38 of file TriangleTypes.h.
Constructor & Destructor Documentation
TTriangle2() [1/3]
template<typename RealType> UE::Geometry::TTriangle2< RealType >::TTriangle2 () inline
Definition at line 42 of file TriangleTypes.h.
TTriangle2() [2/3]
template<typename RealType> UE::Geometry::TTriangle2< RealType >::TTriangle2 (const TVector2< RealType > & V0, const TVector2< RealType > & V1, const TVector2< RealType > & V2) inline
Definition at line 44 of file TriangleTypes.h.
TTriangle2() [3/3]
template<typename RealType> UE::Geometry::TTriangle2< RealType >::TTriangle2 (const TVector2< RealType > VIn[3]) inline
Definition at line 51 of file TriangleTypes.h.
Member Function Documentation
Area()
template<typename RealType> RealType UE::Geometry::TTriangle2< RealType >::Area () const inline
Returns
unsigned area of the triangle
Definition at line 91 of file TriangleTypes.h.
BarycentricPoint() [1/2]
template<typename RealType> TVector2< RealType > UE::Geometry::TTriangle2< RealType >::BarycentricPoint (const TVector< RealType > & BaryCoords) const inline
Definition at line 63 of file TriangleTypes.h.
BarycentricPoint() [2/2]
template<typename RealType> TVector2< RealType > UE::Geometry::TTriangle2< RealType >::BarycentricPoint (RealType Bary0, RealType Bary1, RealType Bary2) const inline
Definition at line 58 of file TriangleTypes.h.
GetBarycentricCoords()
template<typename RealType> TVector< RealType > UE::Geometry::TTriangle2< RealType >::GetBarycentricCoords (const TVector2< RealType > & Point) const inline
Definition at line 68 of file TriangleTypes.h.
Referenced by UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV().
IsInside() [1/2]
template<typename RealType> bool UE::Geometry::TTriangle2< RealType >::IsInside (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C, const TVector2< RealType > & QueryPoint) inline static
Parameters
A first vertex of triangle
B second vertex of triangle
C third vertex of triangle
QueryPoint test point
Returns
true if QueryPoint is inside triangle
Definition at line 104 of file TriangleTypes.h.
Referenced by UE::Geometry::TTriangle2< float >::IsInside().
IsInside() [2/2]
template<typename RealType> bool UE::Geometry::TTriangle2< RealType >::IsInside (const TVector2< RealType > & QueryPoint) const inline
Returns
true if QueryPoint is inside triangle
Definition at line 113 of file TriangleTypes.h.
IsInsideOrOn() [1/2]
template<typename RealType> bool UE::Geometry::TTriangle2< RealType >::IsInsideOrOn (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C, const TVector2< RealType > & QueryPoint, RealType Tolerance = (RealType)0) inline static
Returns
true if QueryPoint is inside triangle or on edge. Note that this is slower than IsInside because of the need to handle degeneracy and tolerance.
Definition at line 123 of file TriangleTypes.h.
Referenced by UE::Geometry::TTriangle2< float >::IsInsideOrOn().
IsInsideOrOn() [2/2]
template<typename RealType> bool UE::Geometry::TTriangle2< RealType >::IsInsideOrOn (const TVector2< RealType > & QueryPoint, RealType Tolerance = 0) const inline
Returns
true if QueryPoint is inside triangle or on edge. Note that this is slower than IsInside because of the need to handle degeneracy and tolerance.
Definition at line 170 of file TriangleTypes.h.
IsInsideOrOn_Oriented() [1/2]
template<typename RealType> int UE::Geometry::TTriangle2< RealType >::IsInsideOrOn_Oriented (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C, const TVector2< RealType > & QueryPoint, RealType Tolerance = (RealType)0) inline static
More robust (because it doesn't multiply orientation test results) inside-triangle test for oriented triangles only (the code early-outs at the first 'outside' edge, which only works if the triangle is oriented as expected)
Returns
1 if outside, -1 if inside, 0 if on boundary
Definition at line 191 of file TriangleTypes.h.
IsInsideOrOn_Oriented() [2/2]
template<typename RealType> int UE::Geometry::TTriangle2< RealType >::IsInsideOrOn_Oriented (const TVector2< RealType > & QueryPoint, RealType Tolerance = (RealType)0) const inline
More robust (because it doesn't multiply orientation test results) inside-triangle test for oriented triangles only (the code early-outs at the first 'outside' edge, which only works if the triangle is oriented as expected)
Returns
1 if outside, -1 if inside, 0 if on boundary
Definition at line 181 of file TriangleTypes.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::ContainsPoint(), and UE::Geometry::TTriangle2< float >::IsInsideOrOn_Oriented().
SignedArea() [1/2]
template<typename RealType> RealType UE::Geometry::TTriangle2< RealType >::SignedArea () const inline
Returns
signed area of triangle
Definition at line 85 of file TriangleTypes.h.
Referenced by UE::Geometry::TTriangle2< float >::Area(), and UE::Geometry::TTriangle2< float >::SignedArea().
SignedArea() [2/2]
template<typename RealType> RealType UE::Geometry::TTriangle2< RealType >::SignedArea (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C) inline static
Parameters
A first vertex of triangle
B second vertex of triangle
C third vertex of triangle
Returns
signed area of triangle
Definition at line 79 of file TriangleTypes.h.
Field Documentation
V
template<typename RealType> TVector2<RealType> UE::Geometry::TTriangle2< RealType >::V[3]
Definition at line 40 of file TriangleTypes.h.
Referenced by UE::Geometry::TIntrRay3Triangle3< float >::FindWatertightIntersectionInternal(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), UE::Geometry::TIntrLine2Triangle2< float >::GetInterval(), UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment(), UE::Geometry::TIntrLine2Triangle2< float >::TriangleLineRelations(), and UE::Geometry::TIntrTriangle2Triangle2< float >::WhichSide().
The documentation for this struct was generated from the following file:
TriangleTypes.h