Unreal Engine 5.6 C++ API: FLocMetadataValueArray Class Reference
FLocMetadataValueArray Class Reference
A LocMetadata Array Value.
#include "InternationalizationMetadata.h"
Public Member Functions
FLocMetadataValueArray (const TArray< TSharedPtr< FLocMetadataValue > > &InArray)
FLocMetadataValueArray (FStructuredArchive::FSlot Slot)
virtual TArray< TSharedPtr< FLocMetadataValue > > AsArray () override
Returns this value as an array, throwing an error if this is not an Metadata Array.
virtual TSharedRef< FLocMetadataValue > Clone () const override
virtual ELocMetadataType GetType () const override
virtual FString ToString () const override
Public Member Functions inherited from FLocMetadataValue
virtual ~FLocMetadataValue ()=0
virtual bool AsBool ()
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
virtual TSharedPtr< FLocMetadataObject > AsObject ()
Returns this value as an object, throwing an error if this is not an Metadata Object.
virtual FString AsString ()
Returns this value as a string, throwing an error if this is not a Metadata String.
bool operator< (const FLocMetadataValue &Other) const
bool operator== (const FLocMetadataValue &Other) const
Static Public Member Functions
static void Serialize (FLocMetadataValueArray &Value, FStructuredArchive::FSlot Slot)
Protected Member Functions
virtual bool EqualTo (const FLocMetadataValue &Other) const override
virtual FString GetTypeString () const override
virtual bool LessThan (const FLocMetadataValue &Other) const override
Protected Member Functions inherited from FLocMetadataValue
FLocMetadataValue ()
void ErrorMessage (const FString &InType)
Protected Attributes
TArray< TSharedPtr< FLocMetadataValue > > Value
Detailed Description
A LocMetadata Array Value.
Definition at line 233 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
FLocMetadataValueArray() [1/2]
FLocMetadataValueArray::FLocMetadataValueArray (const TArray< TSharedPtr< FLocMetadataValue > > & InArray) inline
Definition at line 236 of file InternationalizationMetadata.h.
References Value.
Referenced by Serialize().
FLocMetadataValueArray() [2/2]
FLocMetadataValueArray::FLocMetadataValueArray (FStructuredArchive::FSlot Slot)
Member Function Documentation
AsArray()
virtual TArray< TSharedPtr< FLocMetadataValue > > FLocMetadataValueArray::AsArray () inline override virtual
Returns this value as an array, throwing an error if this is not an Metadata Array.
Reimplemented from FLocMetadataValue.
Definition at line 240 of file InternationalizationMetadata.h.
References Value.
Clone()
virtual TSharedRef< FLocMetadataValue > FLocMetadataValueArray::Clone () const override virtual
Implements FLocMetadataValue.
EqualTo()
virtual bool FLocMetadataValueArray::EqualTo (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
GetType()
virtual ELocMetadataType FLocMetadataValueArray::GetType () const inline override virtual
Implements FLocMetadataValue.
Definition at line 246 of file InternationalizationMetadata.h.
References Array.
GetTypeString()
virtual FString FLocMetadataValueArray::GetTypeString () const inline override protected virtual
Implements FLocMetadataValue.
Definition at line 254 of file InternationalizationMetadata.h.
References TEXT.
LessThan()
virtual bool FLocMetadataValueArray::LessThan (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
Serialize()
void FLocMetadataValueArray::Serialize (FLocMetadataValueArray & Value, FStructuredArchive::FSlot Slot) static
References FLocMetadataValueArray(), and Value.
ToString()
virtual FString FLocMetadataValueArray::ToString () const override virtual
Implements FLocMetadataValue.
Field Documentation
Value
TArray< TSharedPtr<FLocMetadataValue> > FLocMetadataValueArray::Value protected
Definition at line 249 of file InternationalizationMetadata.h.
Referenced by FLocMetadataValueArray(), AsArray(), and Serialize().
The documentation for this class was generated from the following file:
InternationalizationMetadata.h