Unreal Engine 5.6 C++ API: UParticleModuleLocationEmitter Class Reference
UParticleModuleLocationEmitter Class Reference
#include "ParticleModuleLocationEmitter.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FName EmitterName
The name of the emitter to use that the source location for particle.
virtual uint32 RequiredBytesPerInstance () override
virtual void Spawn (const FSpawnContext &Context) override
UPROPERTY() uint32 bInheritSourceRotation UPROPERTY () float InheritSourceRotationScale
If true, the spawned particle should inherit the rotation of the source particle.
UPROPERTY() uint32 InheritSourceVelocity UPROPERTY () float InheritSourceVelocityScale
If true, the spawned particle should inherit the velocity of the source particle.
UPROPERTY () TEnumAsByte< enum ELocationEmitterSelectionMethod > SelectionMethod
The method to use when selecting a spawn target particle from the emitter.
Detailed Description
Definition at line 29 of file ParticleModuleLocationEmitter.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UParticleModuleLocationEmitter::GENERATED_UCLASS_BODY () private
The name of the emitter to use that the source location for particle.
References Category, Location, and UPROPERTY().
RequiredBytesPerInstance()
virtual uint32 UParticleModuleLocationEmitter::RequiredBytesPerInstance () override private virtual
References RequiredBytesPerInstance().
Referenced by RequiredBytesPerInstance().
Spawn()
virtual void UParticleModuleLocationEmitter::Spawn (const FSpawnContext & Context) override private virtual
References Spawn().
Referenced by Spawn().
UPROPERTY() [1/3]
UPROPERTY() uint32 bInheritSourceRotation UParticleModuleLocationEmitter::UPROPERTY () private
If true, the spawned particle should inherit the rotation of the source particle.
Amount to scale the source rotation by when inheriting it.
References Category, Location, and UPROPERTY().
UPROPERTY() [2/3]
UPROPERTY() uint32 InheritSourceVelocity UParticleModuleLocationEmitter::UPROPERTY () private
If true, the spawned particle should inherit the velocity of the source particle.
Amount to scale the source velocity by when inheriting it.
References Category, Location, and UPROPERTY().
UPROPERTY() [3/3]
UParticleModuleLocationEmitter::UPROPERTY () private
The method to use when selecting a spawn target particle from the emitter.
Can be one of the following: ELESM_Random Randomly select a particle from the source emitter. ELESM_Sequential Step through each particle from the source emitter in order.
References Category, Location, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
ParticleModuleLocationEmitter.h