Unreal Engine 5.6 C++ API: FModularSimCollection Class Reference
FModularSimCollection Class Reference
FModularSimCollection (FTransformCollection)
#include "ModularSimCollection.h"
Public Types
typedef FGeometryCollection Super
Public Member Functions
CHAOSMODULARVEHICLE_API FModularSimCollection ()
FModularSimCollection (FModularSimCollection &&)=default
FModularSimCollection (FModularSimCollection &)=delete
CHAOSMODULARVEHICLE_API void GenerateSimTree ()
FModularSimCollection & operator= (const FModularSimCollection &)=delete
FModularSimCollection & operator= (FModularSimCollection &&)=default
Static Public Member Functions
static CHAOSMODULARVEHICLE_API void Init (FModularSimCollection *Collection)
static CHAOSMODULARVEHICLE_API FModularSimCollection * NewModularSimulationCollection ()
static CHAOSMODULARVEHICLE_API FModularSimCollection * NewModularSimulationCollection (const FTransformCollection &Base)
Create a GeometryCollection from Vertex and Indices arrays.
Data Fields
TManagedArray< int32 > SimModuleIndex
Static Public Attributes
static CHAOSMODULARVEHICLE_API const FName SimModuleIndexAttribute
Protected Member Functions
CHAOSMODULARVEHICLE_API void Construct ()
Detailed Description
FModularSimCollection (FTransformCollection)
Definition at line 19 of file ModularSimCollection.h.
Member Typedef Documentation
Super
typedef FGeometryCollection FModularSimCollection::Super
Definition at line 23 of file ModularSimCollection.h.
Constructor & Destructor Documentation
FModularSimCollection() [1/3]
CHAOSMODULARVEHICLE_API FModularSimCollection::FModularSimCollection ()
References UE_API.
Referenced by FModularSimCollection(), FModularSimCollection(), Init(), NewModularSimulationCollection(), NewModularSimulationCollection(), operator=(), and operator=().
FModularSimCollection() [2/3]
FModularSimCollection::FModularSimCollection (FModularSimCollection &) delete
References FModularSimCollection().
FModularSimCollection() [3/3]
FModularSimCollection::FModularSimCollection (FModularSimCollection &&) default
References FModularSimCollection().
Member Function Documentation
Construct()
CHAOSMODULARVEHICLE_API void FModularSimCollection::Construct () protected
References UE_API.
GenerateSimTree()
CHAOSMODULARVEHICLE_API void FModularSimCollection::GenerateSimTree ()
References UE_API.
Init()
CHAOSMODULARVEHICLE_API void FModularSimCollection::Init (FModularSimCollection * Collection) static
References FModularSimCollection(), and UE_API.
NewModularSimulationCollection() [1/2]
CHAOSMODULARVEHICLE_API FModularSimCollection * FModularSimCollection::NewModularSimulationCollection () static
References FModularSimCollection(), and UE_API.
NewModularSimulationCollection() [2/2]
CHAOSMODULARVEHICLE_API FModularSimCollection * FModularSimCollection::NewModularSimulationCollection (const FTransformCollection & Base) static
Create a GeometryCollection from Vertex and Indices arrays.
References FModularSimCollection(), and UE_API.
operator=() [1/2]
FModularSimCollection & FModularSimCollection::operator= (const FModularSimCollection &) delete
References FModularSimCollection().
operator=() [2/2]
FModularSimCollection & FModularSimCollection::operator= (FModularSimCollection &&) default
References FModularSimCollection().
Field Documentation
SimModuleIndex
TManagedArray<int32> FModularSimCollection::SimModuleIndex
Definition at line 43 of file ModularSimCollection.h.
SimModuleIndexAttribute
CHAOSMODULARVEHICLE_API const FName FModularSimCollection::SimModuleIndexAttribute static
Definition at line 42 of file ModularSimCollection.h.
The documentation for this class was generated from the following file:
ModularSimCollection.h