Unreal Engine 5.6 C++ API: FViewport Class Reference
FViewport Class Reference abstract
Encapsulates the I/O of a viewport.
#include "UnrealClient.h"
Data Structures
class FHitProxyMap
A map from 2D coordinates to cached hit proxies.
Public Member Functions
FViewport (FViewportClient *InViewportClient)
virtual ~FViewport ()
virtual void BeginRenderFrame (FRHICommandListImmediate &RHICmdList)
Starts a new rendering frame.
FIntRect CalculateViewExtents (float AspectRatio, const FIntRect &ViewRect)
Calculates the view inside the viewport when the aspect ratio is locked.
virtual void CaptureMouse (bool bCapture)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnViewportResized, FViewport *, uint32)
delegate type for viewport resize events (Params: FViewport* Viewport, uint32)
virtual void DeferInvalidateHitProxy ()
Invalidates the viewport's cached hit proxies at the end of the frame.
virtual void Destroy ()=0
void Draw (bool bShouldPresent=true)
Updates the viewport's displayed pixels with the results of calling ViewportClient->Draw.
virtual int32 DrawStatsHUD (FCanvas *InCanvas, const int32 InX, const int32 InY)
First chance for viewports to render custom stats text.
virtual void EndRenderFrame (FRHICommandListImmediate &RHICmdList, bool bPresent, bool bLockToVsync)
Ends a rendering frame.
virtual void EnqueueBeginRenderFrame (const bool bShouldPresent)
Starts a new rendering frame.
virtual void EnqueueEndRenderFrame (const bool bLockToVsync, const bool bShouldPresent)
Ends a rendering frame.
void EnumerateHitProxiesInRect (FIntRect InRect, TFunctionRef< bool(HHitProxy *)> InCallback)
Enumerate all valid hit proxies found within a specified region.
void GetActorsAndModelsInHitProxy (FIntRect InRect, TSet< AActor * > &OutActors, TSet< UModel * > &OutModels)
Returns all actors and models found in the hit proxy within a specified region.
FViewportClient * GetClient () const
virtual FCanvas * GetDebugCanvas ()
virtual float GetDesiredAspectRatio () const
FTypedElementHandle GetElementHandleAtPoint (int32 X, int32 Y)
Returns the dominant element handle at a given point.
void GetElementHandlesInRect (FIntRect InRect, FTypedElementListRef OutElementHandles)
Returns all element handles found within a specified region.
virtual FRHIGPUMask GetGPUMask (FRHICommandListImmediate &RHICmdList) const override
Returns the GPU nodes on which to render this viewport.
HHitProxy * GetHitProxy (int32 X, int32 Y)
Returns the dominant hit proxy at a given point.
void GetHitProxyMap (FIntRect InRect, TArray< HHitProxy * > &OutMap)
Copies the hit proxies from an area of the screen into a buffer.
FIntPoint GetInitialPositionXY () const
virtual void GetMousePos (FIntPoint &MousePosition, const bool bLocalPosition=true)=0
virtual int32 GetMouseX () const =0
virtual int32 GetMouseY () const =0
const TArray< FColor > & GetRawHitProxyData (FIntRect InRect)
virtual FIntPoint GetRenderTargetTextureSizeXY () const
Returns dimensions of RenderTarget texture.
virtual FIntPoint GetSizeXY () const override
virtual float GetTabletPressure ()
virtual FViewportFrame * GetViewportFrame ()=0
Retrieves the interface to the viewport's frame, if it has one.
const FViewportRHIRef & GetViewportRHI () const
Accessors for RHI resources.
FName GetViewportType () const
virtual void * GetWindow ()=0
virtual EWindowMode::Type GetWindowMode () const
virtual bool HasFocus () const
virtual bool HasMouseCapture () const
virtual bool HasToggleFreezeCommand () override
Returns if there is a command to freeze.
void Invalidate ()
Invalidates cached hit proxies and the display.
virtual void InvalidateDisplay ()=0
Invalidates the viewport's displayed pixels.
void InvalidateHitProxy ()
Invalidates cached hit proxies.
virtual bool IsCursorVisible () const
Returns true if the mouse cursor is currently visible.
virtual bool IsExclusiveFullscreen () const
virtual bool IsForegroundWindow () const
virtual bool IsFullscreen () const
bool IsHDRViewport () const
Returns true if this viewport should be rendered in HDR.
virtual bool IsKeyboardAvailable (int32 ControllerID) const
virtual bool IsMouseAvailable (int32 ControllerID) const
virtual bool IsPenActive ()
bool IsPlayInEditorViewport () const
Returns true if the viewport is for play in editor.
bool IsSlateViewport () const
Returns true if this is an FSlateSceneViewport.
virtual bool IsSoftwareCursorVisible () const
virtual bool IsStereoRenderingAllowed () const
Should return true, if stereo rendering is allowed in this viewport.
virtual bool KeyState (FKey Key) const =0
virtual void LockMouseToViewport (bool bLock)
virtual void MoveWindow (int32 NewPosX, int32 NewPosY, int32 NewSizeX, int32 NewSizeY)=0
virtual void ProcessInput (float DeltaTime)=0
virtual void ProcessToggleFreezeCommand () override
Handles freezing/unfreezing of rendering.
void SetHDRMode (bool bHDR)
Sets HDR Status of Viewport.
void SetInitialSize (FIntPoint InitialSizeXY)
Sets the initial size of this viewport.
virtual void SetMouse (int32 x, int32 y)=0
void SetPlayInEditorViewport (bool bInPlayInEditorViewport)
Sets this viewport as a play in editor viewport.
virtual void SetPreCaptureMousePosFromSlateCursor ()
Sets PreCapture coordinates from the current position of the slate cursor.
virtual void SetRequiresVsync (bool bShouldVsync)
Indicate that the viewport should be block for vsync.
virtual void SetSoftwareCursorPosition (FVector2D Position)
virtual bool SetUserFocus (bool bFocus)=0
virtual void SetViewportClient (FViewportClient *InViewportClient)
Sets a viewport client if one wasn't provided at construction time.
virtual void ShowCursor (bool bVisible)
virtual void ShowSoftwareCursor (bool bVisible)
bool TakeHighResScreenShot ()
Trigger a high res screenshot.
virtual bool UpdateMouseCursor (bool bSetCursor)
void UpdateRenderTargetSurfaceRHIToCurrentBackBuffer ()
Update the render target surface RHI to the current back buffer.
virtual FIntPoint ViewportToVirtualDesktopPixel (FVector2D ViewportCoordinate) const =0
Transforms a coordinate in the local space of this viewport into a virtual desktop pixel.
virtual FVector2D VirtualDesktopPixelToViewport (FIntPoint VirtualDesktopPointPx) const =0
Transforms a virtual desktop pixel (the origin is in the primary screen's top left corner) to the local space of this viewport.
Public Member Functions inherited from FRenderTarget
FRenderTarget ()
Default constructor.
virtual ~FRenderTarget ()
Destructor.
virtual EDisplayColorGamut GetDisplayColorGamut () const
virtual float GetDisplayGamma () const
virtual EDisplayOutputFormat GetDisplayOutputFormat () const
virtual const FTextureRHIRef & GetRenderTargetTexture () const
Accessor for the surface RHI when setting this render target.
virtual FRDGTextureRef GetRenderTargetTexture (FRDGBuilder &GraphBuilder) const
Returns a valid RDG texture for this render target.
virtual FUnorderedAccessViewRHIRef GetRenderTargetUAV () const
virtual bool GetSceneHDREnabled () const
virtual const FTextureRHIRef & GetShaderResourceTexture () const
Accessor for the surface RHI to use when reading the reading target (may differ from GetRenderTargetTexture() for some implementations like cubemaps)
virtual bool ReadFloat16Pixels (TArray< FFloat16Color > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadLinearColorPixels (TArray< FLinearColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
bool ReadLinearColorPixelsPtr (FLinearColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadPixels (TArray< FColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
bool ReadPixelsPtr (FColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
UE_DEPRECATED (5.4, "Use the other ReadFloat16Pixels variant (ECubeFace can be set in FReadSurfaceDataFlags)") 1 bool ReadFloat16Pixels(TArray< FFloat16Color > &OutImageData
Reads the render target's displayed pixels into the given color buffer.
Static Public Member Functions
static FIntRect CalculateViewExtents (float AspectRatio, float DesiredAspectRatio, const FIntRect &ViewRect, const FIntPoint &DestSize)
Calculates the view inside the viewport when the aspect ratio is locked.
static bool IsGameRenderingEnabled ()
Returns whether rendering is globally enabled or disabled.
static void SetGameRenderingEnabled (bool bIsEnabled, int32 PresentAndStopMovieDelay=0)
Globally enables/disables rendering.
Static Public Member Functions inherited from FRenderTarget
static float GetEngineDisplayGamma ()
Data Fields
FString AppVersionString
The current version of the running instance.
Data Fields inherited from FRenderTarget
ECubeFace CubeFace
Static Public Attributes
static FOnViewportResized ViewportResizedEvent
Send when a viewport is resized.
Protected Member Functions
void HighResScreenshot ()
Take a high-resolution screenshot and save to disk.
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
virtual void UpdateViewportRHI (bool bDestroyed, uint32 NewSizeX, uint32 NewSizeY, EWindowMode::Type NewWindowMode, EPixelFormat PreferredPixelFormat)
Updates the viewport RHI with the current viewport state.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Protected Attributes
uint32 bHasRequestedToggleFreeze: 1
If a toggle freeze request has been made.
uint32 bHitProxiesCached: 1
True if the hit proxy buffer buffer has up to date hit proxies for this viewport.
uint32 bIsHDR: 1
If true this viewport is being displayed on a HDR monitor.
uint32 bIsPlayInEditorViewport: 1
if true this viewport is for play in editor
uint32 bIsSlateViewport: 1
If true this viewport is an FSlateSceneViewport.
uint32 bRequiresHitProxyStorage: 1
True if the viewport client requires hit proxy storage.
bool bTakeHighResScreenShot
Triggers the taking of a high res screen shot for this viewport.
TArray< FColor > CachedHitProxyData
Cached hit proxy data.
FHitProxyMap HitProxyMap
The viewport's hit proxy map.
uint32 HitProxySize
The size of the region to check hit proxies.
uint32 InitialPositionX
The initial position of the viewport.
uint32 InitialPositionY
The initial position of the viewport.
uint32 SizeX
The width of the viewport.
uint32 SizeY
The height of the viewport.
FViewportClient * ViewportClient
The viewport's client.
FViewportRHIRef ViewportRHI
The RHI viewport.
FName ViewportType
Used internally for testing runtime instance type before casting.
EWindowMode::Type WindowMode
What is the current window mode.
Protected Attributes inherited from FRenderTarget
FTextureRHIRef RenderTargetTextureRHI
Protected Attributes inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Static Protected Attributes
static bool bIsGameRenderingEnabled
true if we should draw game viewports (has no effect on Editor viewports)
static int32 PresentAndStopMovieDelay
Delay in frames to disable present (but still render scene) and stopping of a movie.
Additional Inherited Members
Protected Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Detailed Description
Encapsulates the I/O of a viewport.
The viewport display is implemented using the platform independent RHI.
Definition at line 399 of file UnrealClient.h.
Constructor & Destructor Documentation
FViewport()
FViewport::FViewport (FViewportClient * InViewportClient)
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams(), and FSceneViewport::GetViewport().
~FViewport()
virtual FViewport::~FViewport () virtual
Member Function Documentation
BeginRenderFrame()
virtual void FViewport::BeginRenderFrame (FRHICommandListImmediate & RHICmdList) virtual
Starts a new rendering frame.
Called from the rendering thread.
Reimplemented in FDummyViewport, and FSceneViewport.
CalculateViewExtents() [1/2]
FIntRect FViewport::CalculateViewExtents (float AspectRatio, const FIntRect & ViewRect)
Calculates the view inside the viewport when the aspect ratio is locked.
Used for creating cinematic bars.
Parameters
Aspect [in] ratio to lock to
ViewRect [in] unconstrained view rectangle
Returns
constrained view rectangle
CalculateViewExtents() [2/2]
FIntRect FViewport::CalculateViewExtents (float AspectRatio, float DesiredAspectRatio, const FIntRect & ViewRect, const FIntPoint & DestSize) static
Calculates the view inside the viewport when the aspect ratio is locked.
Used for creating cinematic bars.
Parameters
AspectRatio [in] ratio to lock to
DesiredAspectRatio [in] the aspect ratio of the viewport
ViewRect [in] unconstrained view rectangle
DestSize [in] the size of the the viewport
Returns
constrained view rectangle
CaptureMouse()
virtual void FViewport::CaptureMouse (bool bCapture) inline virtual
Reimplemented in FSceneViewport.
Definition at line 422 of file UnrealClient.h.
DECLARE_MULTICAST_DELEGATE_TwoParams()
FViewport::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnViewportResized , FViewport * , uint32)
delegate type for viewport resize events (Params: FViewport* Viewport, uint32)
References FViewport().
DeferInvalidateHitProxy()
virtual void FViewport::DeferInvalidateHitProxy () virtual
Invalidates the viewport's cached hit proxies at the end of the frame.
Reimplemented in FDummyViewport, and FSceneViewport.
Destroy()
virtual void FViewport::Destroy () pure virtual
Implemented in FDummyViewport, and FSceneViewport.
Draw()
void FViewport::Draw (bool bShouldPresent = true)
Updates the viewport's displayed pixels with the results of calling ViewportClient->Draw.
Parameters
bShouldPresent Whether we want this frame to be presented
DrawStatsHUD()
virtual int32 FViewport::DrawStatsHUD (FCanvas * InCanvas, const int32 InX, const int32 InY) inline virtual
First chance for viewports to render custom stats text.
Parameters
InCanvas - Canvas for rendering
InX - Starting X for drawing
InY - Starting Y for drawing
Returns
- Y for next stat drawing
Definition at line 680 of file UnrealClient.h.
EndRenderFrame()
virtual void FViewport::EndRenderFrame (FRHICommandListImmediate & RHICmdList, bool bPresent, bool bLockToVsync) virtual
Ends a rendering frame.
Called from the rendering thread.
Parameters
bPresent Whether the frame should be presented to the screen
bLockToVsync Whether the GPU should block until VSYNC before presenting
Reimplemented in FDummyViewport, and FSceneViewport.
EnqueueBeginRenderFrame()
virtual void FViewport::EnqueueBeginRenderFrame (const bool bShouldPresent) virtual
Starts a new rendering frame.
Called from the game thread thread.
Parameters
bShouldPresent Whether the frame will be presented to the screen
Reimplemented in FSceneViewport.
EnqueueEndRenderFrame()
virtual void FViewport::EnqueueEndRenderFrame (const bool bLockToVsync, const bool bShouldPresent) virtual
Ends a rendering frame.
Called from the game thread.
Parameters
bPresent Whether the frame should be presented to the screen
Reimplemented in FSceneViewport.
EnumerateHitProxiesInRect()
void FViewport::EnumerateHitProxiesInRect (FIntRect InRect, TFunctionRef< bool(HHitProxy *)> InCallback)
Enumerate all valid hit proxies found within a specified region.
InRect must be entirely within the viewport's client area. If the hit proxies are not cached, this will call ViewportClient->Draw with a hit-testing canvas.
GetActorsAndModelsInHitProxy()
void FViewport::GetActorsAndModelsInHitProxy (FIntRect InRect, TSet< AActor * > & OutActors, TSet< UModel * > & OutModels)
Returns all actors and models found in the hit proxy within a specified region.
InRect must be entirely within the viewport's client area. If the hit proxies are not cached, this will call ViewportClient->Draw with a hit-testing canvas.
GetClient()
FViewportClient * FViewport::GetClient () const inline
Definition at line 637 of file UnrealClient.h.
References ViewportClient.
GetDebugCanvas()
virtual FCanvas * FViewport::GetDebugCanvas () inline virtual
Returns
A canvas that can be used while this viewport is being drawn to render debug elements on top of everything else
Reimplemented in FDummyViewport, and FSceneViewport.
Definition at line 472 of file UnrealClient.h.
GetDesiredAspectRatio()
virtual float FViewport::GetDesiredAspectRatio () const inline virtual
Returns
aspect ratio that this viewport should be rendered at
Definition at line 527 of file UnrealClient.h.
References float, GetSizeXY(), and TSequenceHistory< HistorySize >::Size.
GetElementHandleAtPoint()
FTypedElementHandle FViewport::GetElementHandleAtPoint (int32 X, int32 Y)
Returns the dominant element handle at a given point.
If X,Y are outside the client area of the viewport, returns an invalid handle.
References X, and Y.
GetElementHandlesInRect()
void FViewport::GetElementHandlesInRect (FIntRect InRect, FTypedElementListRef OutElementHandles)
Returns all element handles found within a specified region.
InRect must be entirely within the viewport's client area. If the hit proxies are not cached, this will call ViewportClient->Draw with a hit-testing canvas.
GetGPUMask()
virtual FRHIGPUMask FViewport::GetGPUMask (FRHICommandListImmediate & RHICmdList) const override virtual
Returns the GPU nodes on which to render this viewport.
Reimplemented from FRenderTarget.
GetHitProxy()
HHitProxy * FViewport::GetHitProxy (int32 X, int32 Y)
Returns the dominant hit proxy at a given point.
If X,Y are outside the client area of the viewport, returns NULL. Caution is required as calling Invalidate after this will free the returned HHitProxy.
References X, and Y.
GetHitProxyMap()
void FViewport::GetHitProxyMap (FIntRect InRect, TArray< HHitProxy * > & OutMap)
Copies the hit proxies from an area of the screen into a buffer.
InRect must be entirely within the viewport's client area. If the hit proxies are not cached, this will call ViewportClient->Draw with a hit-testing canvas.
GetInitialPositionXY()
FIntPoint FViewport::GetInitialPositionXY () const inline
Definition at line 635 of file UnrealClient.h.
References InitialPositionX, and InitialPositionY.
GetMousePos()
virtual void FViewport::GetMousePos (FIntPoint & MousePosition, const bool bLocalPosition = true) pure virtual
Implemented in FDummyViewport, and FSceneViewport.
GetMouseX()
virtual int32 FViewport::GetMouseX () const pure virtual
Implemented in FDummyViewport, and FSceneViewport.
GetMouseY()
virtual int32 FViewport::GetMouseY () const pure virtual
Implemented in FDummyViewport, and FSceneViewport.
GetRawHitProxyData()
const TArray< FColor > & FViewport::GetRawHitProxyData (FIntRect InRect)
GetRenderTargetTextureSizeXY()
virtual FIntPoint FViewport::GetRenderTargetTextureSizeXY () const inline virtual
Returns dimensions of RenderTarget texture.
Can be called on a game thread.
Reimplemented in FSceneViewport.
Definition at line 725 of file UnrealClient.h.
References GetSizeXY().
GetSizeXY()
virtual FIntPoint FViewport::GetSizeXY () const inline override virtual
Implements FRenderTarget.
Definition at line 634 of file UnrealClient.h.
References SizeX, and SizeY.
Referenced by GetDesiredAspectRatio(), FSceneViewport::GetRenderTargetTextureSizeXY(), GetRenderTargetTextureSizeXY(), and FSceneViewport::GetSize().
GetTabletPressure()
virtual float FViewport::GetTabletPressure () inline virtual
Definition at line 443 of file UnrealClient.h.
GetViewportFrame()
virtual FViewportFrame * FViewport::GetViewportFrame () pure virtual
Retrieves the interface to the viewport's frame, if it has one.
Returns
The viewport's frame interface.
Implemented in FDummyViewport, and FSceneViewport.
GetViewportRHI()
const FViewportRHIRef & FViewport::GetViewportRHI () const inline
Accessors for RHI resources.
Definition at line 666 of file UnrealClient.h.
References ViewportRHI.
GetViewportType()
FName FViewport::GetViewportType () const inline
Definition at line 727 of file UnrealClient.h.
References ViewportType.
GetWindow()
virtual void * FViewport::GetWindow () pure virtual
Implemented in FDummyViewport, and FSceneViewport.
GetWindowMode()
virtual EWindowMode::Type FViewport::GetWindowMode () const inline virtual
Definition at line 448 of file UnrealClient.h.
References WindowMode.
HasFocus()
virtual bool FViewport::HasFocus () const inline virtual
Reimplemented in FSceneViewport.
Definition at line 420 of file UnrealClient.h.
HasMouseCapture()
virtual bool FViewport::HasMouseCapture () const inline virtual
Reimplemented in FSceneViewport.
Definition at line 419 of file UnrealClient.h.
HasToggleFreezeCommand()
virtual bool FViewport::HasToggleFreezeCommand () override virtual
Returns if there is a command to freeze.
Reimplemented from FRenderTarget.
HighResScreenshot()
void FViewport::HighResScreenshot () protected
Take a high-resolution screenshot and save to disk.
InitRHI()
virtual void FViewport::InitRHI (FRHICommandListBase & RHICmdList) override protected virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FDummyViewport, and FSceneViewport.
Invalidate()
void FViewport::Invalidate ()
Invalidates cached hit proxies and the display.
InvalidateDisplay()
virtual void FViewport::InvalidateDisplay () pure virtual
Invalidates the viewport's displayed pixels.
Implemented in FDummyViewport, and FSceneViewport.
InvalidateHitProxy()
void FViewport::InvalidateHitProxy ()
Invalidates cached hit proxies.
IsCursorVisible()
virtual bool FViewport::IsCursorVisible () const inline virtual
Returns true if the mouse cursor is currently visible.
Returns
True if the mouse cursor is currently visible, otherwise false.
Reimplemented in FSceneViewport.
Definition at line 436 of file UnrealClient.h.
IsExclusiveFullscreen()
virtual bool FViewport::IsExclusiveFullscreen () const inline virtual
Definition at line 447 of file UnrealClient.h.
References EWindowMode::Fullscreen, and WindowMode.
IsForegroundWindow()
virtual bool FViewport::IsForegroundWindow () const inline virtual
Reimplemented in FSceneViewport.
Definition at line 421 of file UnrealClient.h.
IsFullscreen()
virtual bool FViewport::IsFullscreen () const inline virtual
Definition at line 446 of file UnrealClient.h.
References EWindowMode::Fullscreen, EWindowMode::WindowedFullscreen, and WindowMode.
IsGameRenderingEnabled()
bool FViewport::IsGameRenderingEnabled () inline static
Returns whether rendering is globally enabled or disabled.
Returns
true if rendering is globally enabled, otherwise false.
Definition at line 651 of file UnrealClient.h.
References bIsGameRenderingEnabled.
IsHDRViewport()
bool FViewport::IsHDRViewport () const inline
Returns true if this viewport should be rendered in HDR.
Definition at line 708 of file UnrealClient.h.
References bIsHDR.
IsKeyboardAvailable()
virtual bool FViewport::IsKeyboardAvailable (int32 ControllerID) const inline virtual
Returns
whether or not this Controller has a keyboard available to be used
Definition at line 516 of file UnrealClient.h.
IsMouseAvailable()
virtual bool FViewport::IsMouseAvailable (int32 ControllerID) const inline virtual
Returns
whether or not this Controller has a mouse available to be used
Definition at line 521 of file UnrealClient.h.
IsPenActive()
virtual bool FViewport::IsPenActive () inline virtual
Definition at line 444 of file UnrealClient.h.
IsPlayInEditorViewport()
bool FViewport::IsPlayInEditorViewport () const inline
Returns true if the viewport is for play in editor.
Definition at line 693 of file UnrealClient.h.
References bIsPlayInEditorViewport.
IsSlateViewport()
bool FViewport::IsSlateViewport () const inline
Returns true if this is an FSlateSceneViewport.
Definition at line 705 of file UnrealClient.h.
References bIsSlateViewport.
IsSoftwareCursorVisible()
virtual bool FViewport::IsSoftwareCursorVisible () const inline virtual
Reimplemented in FSceneViewport.
Definition at line 429 of file UnrealClient.h.
IsStereoRenderingAllowed()
virtual bool FViewport::IsStereoRenderingAllowed () const inline virtual
Should return true, if stereo rendering is allowed in this viewport.
Reimplemented in FSceneViewport.
Definition at line 722 of file UnrealClient.h.
KeyState()
virtual bool FViewport::KeyState (FKey Key) const pure virtual
Implemented in FDummyViewport, and FSceneViewport.
References Key.
LockMouseToViewport()
virtual void FViewport::LockMouseToViewport (bool bLock) inline virtual
Reimplemented in FSceneViewport.
Definition at line 423 of file UnrealClient.h.
MoveWindow()
virtual void FViewport::MoveWindow (int32 NewPosX, int32 NewPosY, int32 NewSizeX, int32 NewSizeY) pure virtual
Implemented in FDummyViewport, and FSceneViewport.
ProcessInput()
virtual void FViewport::ProcessInput (float DeltaTime) pure virtual
Implemented in FDummyViewport, and FSceneViewport.
References DeltaTime.
ProcessToggleFreezeCommand()
virtual void FViewport::ProcessToggleFreezeCommand () override virtual
Handles freezing/unfreezing of rendering.
Reimplemented from FRenderTarget.
ReleaseRHI()
virtual void FViewport::ReleaseRHI () override protected virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FSceneViewport.
SetGameRenderingEnabled()
void FViewport::SetGameRenderingEnabled (bool bIsEnabled, int32 PresentAndStopMovieDelay = 0) static
Globally enables/disables rendering.
Parameters
bIsEnabled true if drawing should occur
PresentAndStopMovieDelay Number of frames to delay before enabling bPresent in RHIEndDrawingViewport, and before stopping the movie
References PresentAndStopMovieDelay.
SetHDRMode()
void FViewport::SetHDRMode (bool bHDR) inline
Sets HDR Status of Viewport.
Definition at line 711 of file UnrealClient.h.
References bIsHDR.
SetInitialSize()
void FViewport::SetInitialSize (FIntPoint InitialSizeXY)
Sets the initial size of this viewport.
Will do nothing if the viewport has already been sized
Parameters
InitialSizeXY The initial size of the viewport
SetMouse()
virtual void FViewport::SetMouse (int32 x, int32 y) pure virtual
Implemented in FDummyViewport, and FSceneViewport.
SetPlayInEditorViewport()
void FViewport::SetPlayInEditorViewport (bool bInPlayInEditorViewport) inline
Sets this viewport as a play in editor viewport.
Definition at line 699 of file UnrealClient.h.
References bIsPlayInEditorViewport.
SetPreCaptureMousePosFromSlateCursor()
virtual void FViewport::SetPreCaptureMousePosFromSlateCursor () inline virtual
Sets PreCapture coordinates from the current position of the slate cursor.
Reimplemented in FSceneViewport.
Definition at line 482 of file UnrealClient.h.
SetRequiresVsync()
virtual void FViewport::SetRequiresVsync (bool bShouldVsync) inline virtual
Indicate that the viewport should be block for vsync.
Reimplemented in FSceneViewport.
Definition at line 477 of file UnrealClient.h.
SetSoftwareCursorPosition()
virtual void FViewport::SetSoftwareCursorPosition (FVector2D Position) inline virtual
Reimplemented in FSceneViewport.
Definition at line 428 of file UnrealClient.h.
References Position.
SetUserFocus()
virtual bool FViewport::SetUserFocus (bool bFocus) pure virtual
Implemented in FDummyViewport, and FSceneViewport.
SetViewportClient()
virtual void FViewport::SetViewportClient (FViewportClient * InViewportClient) virtual
Sets a viewport client if one wasn't provided at construction time.
Parameters
InViewportClient - The viewport client to set.
ShowCursor()
virtual void FViewport::ShowCursor (bool bVisible) inline virtual
Reimplemented in FSceneViewport.
Definition at line 424 of file UnrealClient.h.
ShowSoftwareCursor()
virtual void FViewport::ShowSoftwareCursor (bool bVisible) inline virtual
Reimplemented in FSceneViewport.
Definition at line 427 of file UnrealClient.h.
TakeHighResScreenShot()
bool FViewport::TakeHighResScreenShot ()
Trigger a high res screenshot.
Returns true if the screenshot can be taken, and false if it can't. The screenshot can fail if the requested multiplier makes the screen too big for the GPU to cope with
UpdateMouseCursor()
virtual bool FViewport::UpdateMouseCursor (bool bSetCursor) inline virtual
Definition at line 425 of file UnrealClient.h.
UpdateRenderTargetSurfaceRHIToCurrentBackBuffer()
void FViewport::UpdateRenderTargetSurfaceRHIToCurrentBackBuffer ()
Update the render target surface RHI to the current back buffer.
UpdateViewportRHI()
virtual void FViewport::UpdateViewportRHI (bool bDestroyed, uint32 NewSizeX, uint32 NewSizeY, EWindowMode::Type NewWindowMode, EPixelFormat PreferredPixelFormat) protected virtual
Updates the viewport RHI with the current viewport state.
Parameters
bDestroyed - True if the viewport has been destroyed.
Reimplemented in FSceneViewport.
ViewportToVirtualDesktopPixel()
virtual FIntPoint FViewport::ViewportToVirtualDesktopPixel (FVector2D ViewportCoordinate) const pure virtual
Transforms a coordinate in the local space of this viewport into a virtual desktop pixel.
Parameters
ViewportCoordiante Normalized coordniate in the rate [0..1]; (0,0) is upper left and (1,1) is lower right.
Returns
the transformed coordinate. It is in virtual desktop pixels.
Implemented in FDummyViewport, and FSceneViewport.
VirtualDesktopPixelToViewport()
virtual FVector2D FViewport::VirtualDesktopPixelToViewport (FIntPoint VirtualDesktopPointPx) const pure virtual
Transforms a virtual desktop pixel (the origin is in the primary screen's top left corner) to the local space of this viewport.
Parameters
VirtualDesktopPointPx Coordinate on the virtual desktop in pixel units. Desktop is considered virtual because multiple monitors are supported.
Returns
The transformed pixel. It is normalized to the range [0, 1]
Implemented in FDummyViewport, and FSceneViewport.
Field Documentation
AppVersionString
FString FViewport::AppVersionString
The current version of the running instance.
Definition at line 714 of file UnrealClient.h.
bHasRequestedToggleFreeze
uint32 FViewport::bHasRequestedToggleFreeze protected
If a toggle freeze request has been made.
Definition at line 826 of file UnrealClient.h.
bHitProxiesCached
uint32 FViewport::bHitProxiesCached protected
True if the hit proxy buffer buffer has up to date hit proxies for this viewport.
Definition at line 823 of file UnrealClient.h.
bIsGameRenderingEnabled
bool FViewport::bIsGameRenderingEnabled static protected
true if we should draw game viewports (has no effect on Editor viewports)
Definition at line 841 of file UnrealClient.h.
Referenced by IsGameRenderingEnabled().
bIsHDR
uint32 FViewport::bIsHDR protected
If true this viewport is being displayed on a HDR monitor.
Definition at line 835 of file UnrealClient.h.
Referenced by IsHDRViewport(), and SetHDRMode().
bIsPlayInEditorViewport
uint32 FViewport::bIsPlayInEditorViewport protected
if true this viewport is for play in editor
Definition at line 829 of file UnrealClient.h.
Referenced by IsPlayInEditorViewport(), and SetPlayInEditorViewport().
bIsSlateViewport
uint32 FViewport::bIsSlateViewport protected
If true this viewport is an FSlateSceneViewport.
Definition at line 832 of file UnrealClient.h.
Referenced by IsSlateViewport().
bRequiresHitProxyStorage
uint32 FViewport::bRequiresHitProxyStorage protected
True if the viewport client requires hit proxy storage.
Definition at line 820 of file UnrealClient.h.
bTakeHighResScreenShot
bool FViewport::bTakeHighResScreenShot protected
Triggers the taking of a high res screen shot for this viewport.
Definition at line 847 of file UnrealClient.h.
CachedHitProxyData
TArray<FColor> FViewport::CachedHitProxyData protected
Cached hit proxy data.
Definition at line 796 of file UnrealClient.h.
HitProxyMap
FHitProxyMap FViewport::HitProxyMap protected
The viewport's hit proxy map.
Definition at line 793 of file UnrealClient.h.
HitProxySize
uint32 FViewport::HitProxySize protected
The size of the region to check hit proxies.
Definition at line 814 of file UnrealClient.h.
InitialPositionX
uint32 FViewport::InitialPositionX protected
The initial position of the viewport.
Definition at line 802 of file UnrealClient.h.
Referenced by GetInitialPositionXY().
InitialPositionY
uint32 FViewport::InitialPositionY protected
The initial position of the viewport.
Definition at line 805 of file UnrealClient.h.
Referenced by GetInitialPositionXY().
PresentAndStopMovieDelay
int32 FViewport::PresentAndStopMovieDelay static protected
Delay in frames to disable present (but still render scene) and stopping of a movie.
This is useful to keep playing a movie while driver caches things on the first frame, which can be slow.
Definition at line 844 of file UnrealClient.h.
Referenced by SetGameRenderingEnabled().
SizeX
uint32 FViewport::SizeX protected
The width of the viewport.
Definition at line 808 of file UnrealClient.h.
Referenced by GetSizeXY().
SizeY
uint32 FViewport::SizeY protected
The height of the viewport.
Definition at line 811 of file UnrealClient.h.
Referenced by GetSizeXY().
ViewportClient
FViewportClient* FViewport::ViewportClient protected
The viewport's client.
Definition at line 732 of file UnrealClient.h.
Referenced by GetClient().
ViewportResizedEvent
FOnViewportResized FViewport::ViewportResizedEvent static
Send when a viewport is resized.
Definition at line 405 of file UnrealClient.h.
ViewportRHI
FViewportRHIRef FViewport::ViewportRHI protected
The RHI viewport.
Definition at line 799 of file UnrealClient.h.
Referenced by GetViewportRHI().
ViewportType
FName FViewport::ViewportType protected
Used internally for testing runtime instance type before casting.
Definition at line 838 of file UnrealClient.h.
Referenced by GetViewportType().
WindowMode
EWindowMode::Type FViewport::WindowMode protected
What is the current window mode.
Definition at line 817 of file UnrealClient.h.
Referenced by GetWindowMode(), IsExclusiveFullscreen(), and IsFullscreen().
The documentation for this class was generated from the following file:
UnrealClient.h