Unreal Engine 5.6 C++ API: FDragTool Class Reference
FDragTool Class Reference
The base class that all drag tools inherit from.
#include "EditorDragTools.h"
Public Member Functions
UNREALED_API FDragTool (FEditorModeTools *InModeTools)
virtual ~FDragTool ()
virtual UNREALED_API void AddDelta (const FVector &InDelta)
Updates the drag tool's end location with the specified delta.
virtual UNREALED_API void EndDrag ()
Ends a mouse drag behavior (the user has let go of the mouse button).
bool IsDragging () const
virtual void Render (const FSceneView *View, FCanvas *Canvas)
virtual void Render (FCanvas *Canvas)
Rendering stub for 2D viewport drag tools.
virtual void Render3D (const FSceneView *View, FPrimitiveDrawInterface *PDI)
virtual UNREALED_API void StartDrag (FEditorViewportClient *InViewportClient, const FVector &InStartWorld, const FVector2D &InStartScreen)
Starts a mouse drag behavior.
Data Fields
bool bConvertDelta
Does this drag tool need to have the mouse movement converted to the viewport orientation?
Protected Attributes
bool bAltDown
These flags store the state of various buttons that were pressed when the drag was started.
bool bControlDown
bool bIsDragging
True if we are dragging.
bool bLeftMouseButtonDown
bool bMiddleMouseButtonDown
bool bRightMouseButtonDown
bool bShiftDown
bool bUseSnapping
If true, the drag tool wants to be passed grid snapped values.
FVector End
FVector EndWk
FEditorModeTools * ModeTools
FVector Start
The start/end location of the current drag.
Detailed Description
The base class that all drag tools inherit from.
The drag tools implement special behaviors for the user clicking and dragging in a viewport.
Definition at line 18 of file EditorDragTools.h.
Constructor & Destructor Documentation
FDragTool()
UNREALED_API FDragTool::FDragTool (FEditorModeTools * InModeTools)
Referenced by FDragTool_ActorBoxSelect::FDragTool_ActorBoxSelect(), FDragTool_ActorBoxSelect::FDragTool_ActorBoxSelect(), FDragTool_ActorFrustumSelect::FDragTool_ActorFrustumSelect(), and FDragTool_ActorFrustumSelect::FDragTool_ActorFrustumSelect().
~FDragTool()
virtual FDragTool::~FDragTool () inline virtual
Definition at line 22 of file EditorDragTools.h.
Member Function Documentation
AddDelta()
virtual UNREALED_API void FDragTool::AddDelta (const FVector & InDelta) virtual
Updates the drag tool's end location with the specified delta.
The end location is snapped to the editor constraints if bUseSnapping is true.
Parameters
InDelta A delta of mouse movement.
Reimplemented in FDragTool_ActorBoxSelect, FDragTool_ActorFrustumSelect, FDragTool_Measure, and FDragTool_ViewportChange.
References FVector.
EndDrag()
virtual UNREALED_API void FDragTool::EndDrag () virtual
Ends a mouse drag behavior (the user has let go of the mouse button).
Reimplemented in FDragTool_ActorBoxSelect, FDragTool_ActorFrustumSelect, and FDragTool_ViewportChange.
IsDragging()
bool FDragTool::IsDragging () const inline
Returns
true if we are dragging
Definition at line 53 of file EditorDragTools.h.
References bIsDragging.
Render() [1/2]
virtual void FDragTool::Render (const FSceneView * View, FCanvas * Canvas) inline virtual
Reimplemented in FDragTool_ActorBoxSelect, FDragTool_ActorFrustumSelect, FDragTool_Measure, and FDragTool_ViewportChange.
Definition at line 45 of file EditorDragTools.h.
Render() [2/2]
virtual void FDragTool::Render (FCanvas * Canvas) inline virtual
Rendering stub for 2D viewport drag tools.
Definition at line 50 of file EditorDragTools.h.
Render3D()
virtual void FDragTool::Render3D (const FSceneView * View, FPrimitiveDrawInterface * PDI) inline virtual
Definition at line 44 of file EditorDragTools.h.
StartDrag()
virtual UNREALED_API void FDragTool::StartDrag (FEditorViewportClient * InViewportClient, const FVector & InStartWorld, const FVector2D & InStartScreen) virtual
Starts a mouse drag behavior.
The start location is snapped to the editor constraints if bUseSnapping is true.
Parameters
InViewportClient The viewport client in which the drag event occurred.
InStart Where the mouse was when the drag started.
Reimplemented in FDragTool_ActorBoxSelect, FDragTool_ActorFrustumSelect, FDragTool_Measure, and FDragTool_ViewportChange.
References FVector.
Field Documentation
bAltDown
bool FDragTool::bAltDown protected
These flags store the state of various buttons that were pressed when the drag was started.
Definition at line 68 of file EditorDragTools.h.
bControlDown
bool FDragTool::bControlDown protected
Definition at line 70 of file EditorDragTools.h.
bConvertDelta
bool FDragTool::bConvertDelta
Does this drag tool need to have the mouse movement converted to the viewport orientation?
Definition at line 56 of file EditorDragTools.h.
bIsDragging
bool FDragTool::bIsDragging protected
True if we are dragging.
Definition at line 75 of file EditorDragTools.h.
Referenced by IsDragging().
bLeftMouseButtonDown
bool FDragTool::bLeftMouseButtonDown protected
Definition at line 71 of file EditorDragTools.h.
bMiddleMouseButtonDown
bool FDragTool::bMiddleMouseButtonDown protected
Definition at line 73 of file EditorDragTools.h.
bRightMouseButtonDown
bool FDragTool::bRightMouseButtonDown protected
Definition at line 72 of file EditorDragTools.h.
bShiftDown
bool FDragTool::bShiftDown protected
Definition at line 69 of file EditorDragTools.h.
bUseSnapping
bool FDragTool::bUseSnapping protected
If true, the drag tool wants to be passed grid snapped values.
Definition at line 65 of file EditorDragTools.h.
End
FVector FDragTool::End protected
Definition at line 62 of file EditorDragTools.h.
EndWk
FVector FDragTool::EndWk protected
Definition at line 62 of file EditorDragTools.h.
ModeTools
FEditorModeTools* FDragTool::ModeTools protected
Definition at line 59 of file EditorDragTools.h.
Start
FVector FDragTool::Start protected
The start/end location of the current drag.
Definition at line 62 of file EditorDragTools.h.
The documentation for this class was generated from the following file:
EditorDragTools.h