Unreal Engine 5.6 C++ API: StridedView.h File Reference
StridedView.h File Reference
#include "CoreTypes.h"
#include "Containers/ContainersFwd.h"
#include "Templates/UnrealTemplate.h"
#include "Misc/AssertionMacros.h"
#include "Containers/ArrayView.h"
#include "HAL/PlatformString.h"
#include <type_traits>
Data Structures
class TStridedView< InElementType, InSizeType >
Pointer with extent and a stride, similar to TArrayView.
struct TStridedView< InElementType, InSizeType >::FIterator
Functions
template<typename ElementType>
TConstStridedView< ElementType > MakeConstStridedView (int32 BytesBetweenElements, const ElementType *FirstElement, int32 Count)
template<typename StructuredRangeType>
auto MakeConstStridedView (StructuredRangeType &&StructuredRange) -> TConstStridedView< std::remove_reference_t< decltype(*GetData(StructuredRange))> >
template<typename StructuredRangeType, typename ElementType, typename StructureType, decltype(GetData(std::declval< StructuredRangeType >())) * = nullptr, decltype(GetNum(std::declval< StructuredRangeType >())) * = nullptr>
TConstStridedView< ElementType > MakeConstStridedView (StructuredRangeType &&StructuredRange, const ElementType StructureType::*Member)
template<typename StructureType>
TConstStridedView< StructureType > MakeConstStridedView (TConstArrayView< StructureType > StructuredView)
template<typename BaseStructureType, typename DerivedStructureType>
TConstStridedView< BaseStructureType > MakeConstStridedViewOfBase (TConstArrayView< DerivedStructureType > StructuredView)
template<typename ElementType>
TStridedView< ElementType > MakeStridedView (int32 BytesBetweenElements, ElementType *FirstElement, int32 Count)
template<typename StructuredRangeType>
auto MakeStridedView (StructuredRangeType &&StructuredRange) -> TStridedView< std::remove_reference_t< decltype(*GetData(StructuredRange))> >
template<typename StructuredRangeType, typename ElementType, typename StructureType, decltype(GetData(std::declval< StructuredRangeType >())) * = nullptr, decltype(GetNum(std::declval< StructuredRangeType >())) * = nullptr>
TStridedView< ElementType > MakeStridedView (StructuredRangeType &&StructuredRange, ElementType StructureType::*Member)
template<typename StructureType>
TStridedView< StructureType > MakeStridedView (TArrayView< StructureType > StructuredView)
template<typename BaseStructureType, typename DerivedStructureType>
TStridedView< BaseStructureType > MakeStridedViewOfBase (TArrayView< DerivedStructureType > StructuredView)
Function Documentation
MakeConstStridedView() [1/4]
template<typename ElementType> TConstStridedView< ElementType > MakeConstStridedView (int32 BytesBetweenElements, const ElementType * FirstElement, int32 Count) nodiscard
Definition at line 183 of file StridedView.h.
References Count.
Referenced by MakeConstMeshBuildVertexView(), MakeConstStridedView(), MakeConstStridedView(), and MakeConstStridedViewOfBase().
MakeConstStridedView() [2/4]
template<typename StructuredRangeType> auto MakeConstStridedView (StructuredRangeType && StructuredRange) -> TConstStridedView<std::remove_reference_t<decltype(*GetData(StructuredRange))>> nodiscard
Definition at line 246 of file StridedView.h.
References Forward(), GetData(), GetNum(), MakeArrayView(), and MakeConstStridedView().
MakeConstStridedView() [3/4]
template<typename StructuredRangeType, typename ElementType, typename StructureType, decltype(GetData(std::declval< StructuredRangeType >())) * = nullptr, decltype(GetNum(std::declval< StructuredRangeType >())) * = nullptr> TConstStridedView< ElementType > MakeConstStridedView (StructuredRangeType && StructuredRange, const ElementType StructureType::* Member) nodiscard
Definition at line 233 of file StridedView.h.
References GetData(), and GetNum().
MakeConstStridedView() [4/4]
template<typename StructureType> TConstStridedView< StructureType > MakeConstStridedView (TConstArrayView< StructureType > StructuredView) nodiscard
Definition at line 209 of file StridedView.h.
References GetData(), GetNum(), and MakeConstStridedView().
MakeConstStridedViewOfBase()
template<typename BaseStructureType, typename DerivedStructureType> TConstStridedView< BaseStructureType > MakeConstStridedViewOfBase (TConstArrayView< DerivedStructureType > StructuredView) nodiscard
Definition at line 196 of file StridedView.h.
References GetData(), GetNum(), and MakeConstStridedView().
MakeStridedView() [1/4]
template<typename ElementType> TStridedView< ElementType > MakeStridedView (int32 BytesBetweenElements, ElementType * FirstElement, int32 Count) nodiscard
Definition at line 177 of file StridedView.h.
References Count.
Referenced by MakeConstMeshBuildVertexView(), MakeMeshBuildVertexView(), MakeMeshBuildVertexView(), MakeStridedView(), MakeStridedView(), and MakeStridedViewOfBase().
MakeStridedView() [2/4]
template<typename StructuredRangeType> auto MakeStridedView (StructuredRangeType && StructuredRange) -> TStridedView<std::remove_reference_t<decltype(*GetData(StructuredRange))>> nodiscard
Definition at line 239 of file StridedView.h.
References Forward(), GetData(), GetNum(), MakeArrayView(), and MakeStridedView().
MakeStridedView() [3/4]
template<typename StructuredRangeType, typename ElementType, typename StructureType, decltype(GetData(std::declval< StructuredRangeType >())) * = nullptr, decltype(GetNum(std::declval< StructuredRangeType >())) * = nullptr> TStridedView< ElementType > MakeStridedView (StructuredRangeType && StructuredRange, ElementType StructureType::* Member) nodiscard
Definition at line 221 of file StridedView.h.
References GetData(), and GetNum().
MakeStridedView() [4/4]
template<typename StructureType> TStridedView< StructureType > MakeStridedView (TArrayView< StructureType > StructuredView) nodiscard
Definition at line 203 of file StridedView.h.
References GetData(), GetNum(), and MakeStridedView().
MakeStridedViewOfBase()
template<typename BaseStructureType, typename DerivedStructureType> TStridedView< BaseStructureType > MakeStridedViewOfBase (TArrayView< DerivedStructureType > StructuredView) nodiscard
Definition at line 189 of file StridedView.h.
References GetData(), GetNum(), and MakeStridedView().