Unreal Engine 5.6 C++ API: UClass Class Reference
UClass Class Reference
An object class.
#include "Class.h"
Public Member Functions
UClass (const FObjectInitializer &ObjectInitializer, UClass *InSuperClass)
UClass (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
UClass (EStaticConstructor, FName InName, uint32 InSize, uint32 InAlignment, EClassFlags InClassFlags, EClassCastFlags InClassCastFlags, const TCHAR *InClassConfigName, EObjectFlags InFlags, ClassConstructorType InClassConstructor, ClassVTableHelperCtorCallerType InClassVTableHelperCtorCaller, FUObjectCppClassStaticFunctions &&InCppClassStaticFunctions)
~UClass ()
void AddDefaultSubobject (UObject *NewSubobject, const UClass *BaseClass)
Adds a new default instance map item.
void AddFunctionToFunctionMap (UFunction *Function, FName FuncName)
Add a function to the function map.
void AddNativeFunction (const ANSICHAR *InName, FNativeFuncPtr InPointer)
Add a native function to the internal native function table.
void AddNativeFunction (const WIDECHAR *InName, FNativeFuncPtr InPointer)
Add a native function to the internal native function table, but with a unicode name.
void AssembleReferenceTokenStream (bool bForce=false)
Assembles the token stream for realtime garbage collection by combining the per class only token stream for each class in the class hierarchy.
virtual void Bind () override
virtual bool CanCreateAssetOfClass () const
Some classes may not support creating assets of their type.
FORCEINLINE bool CheckDefaultObjectIsValidLowLevelFast (const int32 AlignmentCheck) const
Checks if the class default object is valid (not null and its address is a properly aligned pointer)
void ClearFunctionMapsCaches ()
Clears the function name caches, in case things have changed.
void ClearSparseClassDataStruct (bool bInRecomplingOnLoad)
Clears the sparse class data struct for this and all child classes that directly reference it as a super-struct This will rename the current sparse class data struct aside into the transient package.
void CreateLinkAndAddChildFunctionsToMap (const FClassFunctionLinkInfo *Functions, uint32 NumFunctions)
virtual void CreatePersistentUberGraphFrame (UObject *Obj, bool bCreateOnlyIfEmpty=false, bool bSkipSuperClass=false, UClass *OldClass=nullptr) const
Creates memory to store temporary data.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *InName) override
Convert a boot-strap registered class into a real one, add to uobject array, etc.
virtual void DestroyPersistentUberGraphFrame (UObject *Obj, bool bSkipSuperClass=false) const
Clears memory to store temporary data.
virtual UObject * FindArchetype (const UClass *ArchetypeClass, const FName ArchetypeName) const
Finds the object that is used as the parent object when serializing properties, overridden for blueprints.
UFunction * FindFunctionByName (FName InName, EIncludeSuperFlag::Type IncludeSuper=EIncludeSuperFlag::IncludeSuper) const
Looks for a given function name.
virtual void FinishDestroy () override
Called to finish destroying the object.
void GenerateFunctionList (TArray< FName > &OutArray) const
virtual UObject * GetArchetypeForCDO () const
Returns archetype object for CDO.
const void * GetArchetypeForSparseClassData () const
Returns archetype for sparse class data.
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
virtual UClass * GetAuthoritativeClass ()
If there are potentially multiple versions of this class (e.g.
const UClass * GetAuthoritativeClass () const
FORCEINLINE EClassFlags GetClassFlags () const
Gets the class flags.
FORCEINLINE FTopLevelAssetPath GetClassPathName () const
Returns class path name as a package + class FName pair.
const FString GetConfigName () const
Translates the hardcoded script config names (engine, editor, input and game) to their global pendants and otherwise uses config(myini) name to look for a game specific implementation and creates one based on the default if it doesn't exist yet.
const ICppClassTypeInfo * GetCppTypeInfo () const
Provides access to C++ type info.
template<class T>
T * GetDefaultObject () const
Get the default object from the class and cast to a particular type.
UObject * GetDefaultObject (bool bCreateIfNeeded=true) const
Get the default object from the class.
FName GetDefaultObjectName () const
Get the name of the CDO for the this class.
virtual void GetDefaultObjectPreloadDependencies (TArray< UObject * > &OutDeps)
Returns all objects that should be preloaded before the class default object is serialized at load time.
void GetDefaultObjectSubobjects (TArray< UObject * > &OutDefaultSubobjects)
Gets all default instanced objects (often components).
int32 GetDefaultsCount ()
Returns amount of memory used by default object.
UObject * GetDefaultSubobjectByName (FName ToFind)
Searches for the default instanced object (often a component) by name.
virtual FString GetDesc () override
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDescription () const
void * GetOrCreateSparseClassData ()
Returns a pointer to the sidecar data structure.
virtual uint8 * GetPersistentUberGraphFrame (UObject *Obj, UFunction *FuncToCheck) const
Returns memory used to store temporary data on an instance, used by blueprints.
virtual const TCHAR * GetPrefixCPP () const override
Returns the struct/ class prefix used for the C++ declaration of this struct/ class.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps) override
Called during cooking.
FTopLevelAssetPath GetReinstancedClassPathName () const
If this class was recompiled, returns the path to where we should find the new (i.e.
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite () override
Save information for StaticAllocateObject in the case of overwriting an existing object.
const void * GetSparseClassData (const EGetSparseClassDataMethod GetMethod)
Returns a pointer to the sidecar data structure, based on the EGetSparseClassDataMethod.
UScriptStruct * GetSparseClassDataArchetypeStruct () const
Returns the struct used by the sparse class data archetype.
UScriptStruct * GetSparseClassDataStruct () const
Returns a pointer to the type of the sidecar data structure if one is specified.
UClass * GetSuperClass () const
Returns parent class, the parent of a Class is always another class.
FORCEINLINE bool HasAllCastFlags (EClassCastFlags FlagsToCheck) const
FORCEINLINE bool HasAllClassFlags (EClassFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyCastFlag (EClassCastFlags FlagToCheck) const
Used to safely check whether the passed in flag is set.
FORCEINLINE bool HasAnyClassFlags (EClassFlags FlagsToCheck) const
Used to safely check whether the passed in flag is set.
virtual bool HasProperty (const FProperty *InProperty) const
Checks if the property exists on this class or a parent class.
bool ImplementsInterface (const class UClass *SomeInterface) const
This will return whether or not this class implements the passed in class / interface.
virtual void InitPropertiesFromCustomList (uint8 *DataPtr, const uint8 *DefaultDataPtr)
Helper method to assist with initializing object properties from an explicit list.
virtual bool IsAsset () const override
Returns true if this object is considered an asset.
virtual bool IsFunctionImplementedInScript (FName InFunctionName) const
Determines if the specified function has been implemented in a Blueprint.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsStructTrashed () const override
If true, this class has been cleaned and sanitized (trashed) and should not be used.
virtual void Link (FArchive &Ar, bool bRelinkExistingProperties) override
Creates the field/property links and gets structure ready for use at runtime.
virtual void PostInitInstance (UObject *InObj, FObjectInstancingGraph *InstanceGraph)
Called after PostInitProperties during object construction to allow class specific initialization of an object instance.
virtual void PostInitProperties () override
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
virtual void PostLoadDefaultObject (UObject *Object)
Wraps the PostLoad() call for the class default object.
virtual void PostLoadInstance (UObject *InObj)
Called during PostLoad of an object to allow class specific PostLoad operations of an object instance.
virtual void PurgeClass (bool bRecompilingOnLoad)
Purges out the properties of this class in preparation for it to be regenerated.
void RemoveFunctionFromFunctionMap (UFunction *Function)
Remove a function from the function map.
virtual bool Rename (const TCHAR *NewName=nullptr, UObject *NewOuter=nullptr, ERenameFlags Flags=REN_None) override
Rename this object to a unique name, or change its outer.
virtual void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
virtual void SerializeDefaultObject (UObject *Object, FArchive &Ar) final
serializes the passed in object as this class's default object using the given archive
virtual void SerializeDefaultObject (UObject *Object, FStructuredArchive::FSlot Slot)
serializes the passed in object as this class's default object using the given archive slot
void SerializeSparseClassData (FStructuredArchive::FSlot Slot)
serializes the associated sparse class data for the passed in object using the given archive slot.
void SetCppTypeInfoStatic (const FCppClassTypeInfoStatic *InCppTypeInfoStatic)
Sets C++ type information.
void SetDefaultObject (UObject *InClassDefaultObject)
Get the immutable default object from the class.
void SetSparseClassDataStruct (UScriptStruct *InSparseClassDataStruct)
virtual void SetSuperStruct (UStruct *NewSuperStruct) override
Sets the super struct pointer and updates hash information as necessary.
virtual void SetupObjectInitializer (FObjectInitializer &ObjectInitializer) const
Allows class to provide data to the object initializer that can affect how native class subobjects are created.
void SetUpRuntimeReplicationData ()
Initializes the ClassReps and NetFields arrays used by replication.
bool ShouldUseDynamicSubobjectInstancing () const
Returns true if the object instancing graph should analyze default data at runtime to determine which of its object properties need to be instanced at construction time, rather than exclusively relying on reflected property semantics.
virtual void TagSubobjects (EObjectFlags NewFlags) override
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const override
UE_DEPRECATED (5.5, "Replace with UE::Reflection::DoesSparseClassDataOverrideArchetype(Class, [](const FProperty*){return true;})") 1 bool OverridesSparseClassDataArchetype() const
Returns whether the sparse class data on this instance overrides that of its archetype (in type or value)
Public Member Functions inherited from UStruct
UStruct (const FObjectInitializer &ObjectInitializer, UStruct *InSuperStruct, SIZE_T ParamsSize=0, SIZE_T Alignment=0)
UStruct (EStaticConstructor, int32 InSize, int32 InAlignment, EObjectFlags InFlags)
UStruct (UStruct *InSuperStruct, SIZE_T ParamsSize=0, SIZE_T Alignment=0)
virtual ~UStruct ()
virtual void AddCppProperty (FProperty *Property) override
void CollectBytecodeAndPropertyReferencedObjects ()
Collects UObjects referenced by bytecode and properties for faster GC access.
void CollectBytecodeAndPropertyReferencedObjectsRecursively ()
Collects UObjects referenced by bytecode and properties for this class and its child fields and their children...
void CollectBytecodeReferencedObjects (TArray< UObject * > &OutReferencedObjects)
Collects UObjects referenced by bytecode.
void CollectPropertyReferencedObjects (TArray< UObject * > &OutReferencedObjects)
Collects UObjects referenced by properties.
virtual FProperty * CustomFindProperty (const FName InName) const
Look up a property by an alternate name if it was not found in the first search, this is overridden for user structs.
FORCEINLINE void DeleteUnresolvedScriptProperties ()
Deletes the UnresolvedScriptProperties array.
void DestroyChildPropertiesAndResetPropertyLinks ()
Destroys all properties owned by this struct.
virtual void DestroyStruct (void *Dest, int32 ArrayDim=1) const
Destroy a struct in memory.
FProperty * FindPropertyByName (FName InName) const
Searches property link chain for a property with the specified name.
UE_INTERNAL FProperty * FindPropertyByOffset (int32 Offset) const
Internal API that searches the property link chain for a property with the specified offset.
virtual FString GetAuthoredNameForField (const FField *Field) const
Returns a human readable string for a given field, overridden for user defined structs.
virtual FString GetAuthoredNameForField (const UField *Field) const
Returns a human readable string for a given field, overridden for user defined structs.
virtual UStruct * GetInheritanceSuper () const
Returns the structure used for inheritance, may be changed by child types.
FORCEINLINE int32 GetMinAlignment () const
Alignment of structure in memory, structure will be at least this large.
FORCEINLINE int32 GetPropertiesSize () const
Total size of all UProperties, the allocated structure may be larger due to alignment.
FTopLevelAssetPath GetStructPathName () const
Returns struct path name as a package + struct FName pair.
FORCEINLINE int32 GetStructureSize () const
Returns actual allocated size of structure in memory.
UStruct * GetSuperStruct () const
Struct this inherits from, may be null.
virtual void InitializeStruct (void *Dest, int32 ArrayDim=1) const
Initialize a struct over uninitialized memory.
void InstanceSubobjectTemplates (TNotNull< void * > Data, void const *DefaultData, UStruct *DefaultStruct, TNotNull< UObject * > Owner, FObjectInstancingGraph *InstanceGraph)
Creates new copies of components.
template<class T>
bool IsChildOf () const
Returns true if this struct either is class T, or is a child of class T.
bool IsChildOf (const UStruct *SomeBase) const
Returns true if this struct either is SomeBase, or is a child of SomeBase.
virtual void PreloadChildren (FArchive &Ar)
Preloads all fields that belong to this struct.
virtual void RegisterDependencies () override
Force any base classes to be registered first.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const
Attempt to resolve the given inner path info against this outer struct to get the inner property value.
virtual void Serialize (FStructuredArchive::FRecord Record) override
virtual void SerializeBin (FArchive &Ar, void *Data) const final
Serializes struct properties, does not handle defaults.
virtual void SerializeBin (FStructuredArchive::FSlot Slot, void *Data) const
Serializes struct properties, does not handle defaults.
void SerializeBinEx (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct) const
Serializes the class properties that reside in Data if they differ from the corresponding values in DefaultData.
virtual EExprToken SerializeExpr (int32 &iCode, FArchive &Ar)
Serialize an expression to an archive.
virtual void SerializeTaggedProperties (FArchive &Ar, uint8 *Data, UStruct *DefaultsStruct, uint8 *Defaults, const UObject *BreakRecursionIfFullyLoad=nullptr) const final
Serializes list of properties, using property tags to handle mismatches.
virtual void SerializeTaggedProperties (FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, uint8 *Defaults, const UObject *BreakRecursionIfFullyLoad=nullptr) const
Serializes list of properties, using property tags to handle mismatches.
void SetPropertiesSize (int32 NewSize)
Modifies the property size after it's been recomputed.
void SetUnresolvedScriptProperties (FUnresolvedScriptPropertiesArray &InUnresolvedProperties)
Sets the UnresolvedScriptProperties array.
void StaticLink (bool bRelinkExistingProperties=false)
Static wrapper for Link, using a dummy archive.
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(void *Data
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
EPropertyVisitorControlFlow Visit (void *Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc, FPropertyVisitorContext::EScope InScope=FPropertyVisitorContext::EScope::All) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BeginDestroy ()
Called before destroying the object.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CallRemoteFunction (UFunction *Function, void *Parms, struct FOutParmRec *OutParms, FFrame *Stack)
Call the actor's function remotely.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
virtual bool CanEditChange (const FProperty *InProperty) const
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack)
Return the space this function should be called.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual void GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > &OutLifetimeProps) const
Returns properties that are replicated for the lifetime of the actor channel.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const
IsSupportedForNetworking means an object can be referenced over the network.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual bool Modify (bool bAlwaysMarkDirty=true)
Note that the object will be modified.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForEditorGame () const
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditChangeChainProperty (struct FPropertyChangedChainEvent &PropertyChangedEvent)
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent)
Called when a property on this object has been modified externally.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo ()
Called after applying a transaction to the object.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostNetReceive ()
Called right after receiving a bunch.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRename (UObject *OldOuter, const FName OldName)
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreEditChange (FProperty *PropertyAboutToChange)
This is called when a property is about to be modified externally.
virtual void PreEditUndo ()
Called before applying a transaction to the object.
virtual void PreNetReceive ()
Called right before receiving a bunch.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static void AssembleReferenceTokenStreams ()
Assemble reference token streams for all classes if they haven't had it assembled already.
static FString ConvertFullNameToShortTypeFullName (FStringView InFullName)
Takes a FullName (from e.g.
static FString ConvertPathNameToShortTypeName (FStringView InClassPathOrShortTypeName)
Returns the ObjectName portion of a ClassPath name: "/Path/To.Object" is converted to "Object".
static UClass * FindCommonBase (const TArray< UClass * > &InClasses)
Finds the common base class that parents the array of classes passed in.
static UClass * FindCommonBase (UClass *InClassA, UClass *InClassB)
Finds the common base class that parents the two classes passed in.
static class FFeedbackContext & GetDefaultPropertiesFeedbackContext ()
Feedback context for default property import.
static bool IsSafeToSerializeToStructuredArchives (UClass *InClass)
Helper function for determining if the given class is compatible with structured archive serialization.
static bool IsShortTypeName (FStringView ClassPathOrShortTypeName)
Returns whether the given stringview is in ShortTypeName form: No directory separators "/" or object separators ".", SUBOBJECT_DELIMITER Returns true for empty string.
template<typename T>
static FTopLevelAssetPath TryConvertShortTypeNameToPathName (const FString &InShortTypeName, ELogVerbosity::Type AmbiguousMessageVerbosity=ELogVerbosity::NoLogging, const TCHAR *AmbiguousClassMessage=nullptr)
Tries to convert short class name to class path name.
static FTopLevelAssetPath TryConvertShortTypeNameToPathName (UClass *TypeClass, const FString &InShortTypeName, ELogVerbosity::Type AmbiguousMessageVerbosity=ELogVerbosity::NoLogging, const TCHAR *AmbiguousClassMessage=nullptr)
Tries to convert short class name to class path name.
template<typename T>
static T * TryFindTypeSlow (const FString &InShortNameOrPathName, EFindFirstObjectOptions InOptions=EFindFirstObjectOptions::None)
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
static UField * TryFindTypeSlow (UClass *TypeClass, const FString &InPathNameOrShortName, EFindFirstObjectOptions InOptions=EFindFirstObjectOptions::None)
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
template<typename T>
static T * TryFindTypeSlowSafe (const FString &InShortNameOrPathName, EFindFirstObjectOptions InOptions=EFindFirstObjectOptions::None)
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
static UField * TryFindTypeSlowSafe (UClass *TypeClass, const FString &InPathNameOrShortName, EFindFirstObjectOptions InOptions=EFindFirstObjectOptions::None)
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
static bool TryFixShortClassNameExportPath (FString &InOutExportPathToFix, ELogVerbosity::Type AmbiguousMessageVerbosity=ELogVerbosity::NoLogging, const TCHAR *AmbiguousClassMessage=nullptr, bool bClearOnError=false)
Tries to fix an export path containing short class name.
Static Public Member Functions inherited from UStruct
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Data Fields
TArray< FImplementedInterface > Interfaces
The list of interfaces which this class implements, along with the pointer property that is located at the offset of the interface's vtable.
TArray< FNativeFunctionLookup > NativeFunctionLookupTable
This class's native functions.
UE::GC::FSchemaOwner ReferenceSchema
GC schema, finalized in AssembleReferenceTokenStream.
Data Fields inherited from UStruct
FField * ChildProperties
Pointer to start of linked list of child fields.
TObjectPtr< UField > Children
Pointer to start of linked list of child fields.
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLink
In memory only: Linked list of properties requiring destruction.
int16 MinAlignment
Alignment of structure in memory, structure will be at least this large.
FProperty * PostConstructLink
In memory only: Linked list of properties requiring post constructor initialization.
int32 PropertiesSize
Total size of all UProperties, the allocated structure may be larger due to alignment.
FProperty * PropertyLink
In memory only: Linked list of properties from most-derived to base.
FProperty * RefLink
In memory only: Linked list of object reference properties from most-derived to base.
TArray< uint8 > Script
Script bytecode associated with this object.
TArray< TObjectPtr< UObject > > ScriptAndPropertyObjectReferences
Array of object references embedded in script code and referenced by FProperties.
FUnresolvedScriptPropertiesArray * UnresolvedScriptProperties
Contains a list of script properties that couldn't be resolved at load time.
std::atomic< const struct FUnversionedStructSchema * > UnversionedGameSchema = nullptr
Cached schema for optimized unversioned and filtereditoronly property serialization, owned by this.
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Protected Member Functions
void CleanupSparseClassData ()
virtual UObject * CreateDefaultObject ()
Get the default object from the class, creating it if missing, if requested or under a few other circumstances.
void * CreateSparseClassData ()
virtual FTopLevelAssetPath GetReinstancedClassPathName_Impl () const
Internal helper method for GetReinstancedClassPathName().
virtual bool SupportsDynamicInstancedReference () const
Subtypes can optionally override to return true.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UStruct
virtual bool ArePropertyGuidsAvailable () const
Returns if we have access to property guids.
virtual FGuid FindPropertyGuidFromName (const FName InName) const
Find property guid.
virtual FName FindPropertyNameFromGuid (const FGuid &PropertyGuid) const
Returns the property name from the guid.
void LoadTaggedPropertiesFromText (FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, uint8 *Defaults, const UObject *BreakRecursionIfFullyLoad) const
Serializes list of properties to a te, using property tags to handle mismatches.
void SerializeProperties (FArchive &Ar)
Serializes properties of this struct.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual bool IsSelectedInEditor () const
Test the selection state of a UObject.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Attributes
void * SparseClassData
This is where we store the data that is only changed per class instead of per instance.
TObjectPtr< UScriptStruct > SparseClassDataStruct
The struct used to store sparse class data.
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Private Types
typedef void(* ClassConstructorType) (const FObjectInitializer &)
typedef UObject *(* ClassVTableHelperCtorCallerType) (FVTableHelper &Helper)
typedef UClass *(* StaticClassFunctionType) ()
Private Member Functions
void AssembleReferenceTokenStreamInternal (bool bForce=false)
Tests if all properties tagged with Replicate were registered in GetLifetimeReplicatedProps.
FORCEINLINE void CallAddReferencedObjects (UObject *This, FReferenceCollector &Collector) const
Calls AddReferencedObjects static method on the specified object.
virtual void ConditionalRecompileClass (FUObjectSerializeContext *InLoadContext)
Conditionally recompiles the class after loading, in case any dependencies were also newly loaded.
UFunction * FindFunction (FName InName) const
This signature intentionally hides the method declared in UObject to make it private.
UFunction * FindFunctionChecked (FName InName) const
This signature intentionally hides the method declared in UObject to make it private.
virtual void FlushCompilationQueueForLevel ()
void GetAutoCollapseCategories (TArray< FString > &OutAutoCollapseCategories) const
void GetAutoExpandCategories (TArray< FString > &OutAutoExpandCategories) const
void GetClassGroupNames (TArray< FString > &OutClassGroupNames) const
void GetHideFunctions (TArray< FString > &OutHideFunctions) const
void GetPrioritizeCategories (TArray< FString > &OutPrioritizedCategories) const
template<typename T>
bool Implements () const
This signature intentionally hides the method declared in UObject to make it private.
void InternalCreateDefaultObjectWrapper () const
bool IsA (const UClass *Parent) const
This signature intentionally hides the method declared in UObjectBaseUtility to make it private.
bool IsAutoCollapseCategory (const TCHAR *InCategory) const
bool IsAutoExpandCategory (const TCHAR *InCategory) const
bool IsClassGroupName (const TCHAR *InGroupName) const
bool IsFunctionHidden (const TCHAR *InFunction) const
bool IsPrioritizeCategory (const TCHAR *InCategory) const
UE_DEPRECATED (5.6, "ClassDefaultObject will be made private in the next release. For general purpose access to the CDO consider using the global GetDefault<>() or GetMutableDefault<>() functions.") TObjectPtr< UObject > ClassDefaultObject
The class default object; used for delta serialization and object initialization.
Private Attributes
TMap< FName, UFunction * > AllFunctionsCache
A cache of all functions by name that exist in this class or a parent (superclass or interface) context.
FUClassFuncLock AllFunctionsCacheLock
Scope lock to avoid the SuperFuncMap being read and written to simultaneously on multiple threads.
bool bCooked
Used to check if the class was cooked or not.
bool bLayoutChanging
Used to check if the class layout is currently changing and therefore is not ready for a CDO to be created.
EClassCastFlags ClassCastFlags
Cast flags used to accelerate dynamic_cast<T*> on objects of this type for common T.
FName ClassConfigName
Which Name.ini file to load Config variables out of.
ClassConstructorType ClassConstructor
EClassFlags ClassFlags
Class flags; See EClassFlags for more information.
TArray< FRepRecord > ClassReps
List of replication records.
int32 ClassUnique
Class pseudo-unique counter; used to accelerate unique instance name generation.
ClassVTableHelperCtorCallerType ClassVTableHelperCtorCaller
TObjectPtr< UClass > ClassWithin
The required type for the outer of instances of this class.
FUObjectCppClassStaticFunctions CppClassStaticFunctions
TOptional< FCppClassTypeInfo > CppTypeInfo
Provides access to attributes of the underlying C++ class.
int32 FirstOwnedClassRep = 0
Index of the first ClassRep that belongs to this class.
TMap< FName, TObjectPtr< UFunction > > FuncMap
Map of all functions by name contained in this class.
FUClassFuncLock FuncMapLock
Scope lock to avoid the FuncMap being read and written to simultaneously on multiple threads.
TArray< UField * > NetFields
List of network relevant fields (functions)
Friends
struct FBlueprintCompilationManagerImpl
class FBlueprintCompileReinstancer
class(UClass, UStruct, 0, TEXT("/Script/CoreUObject"), CASTCLASS_UClass, 1) DECLARE_WITHIN_UPACKAGE() public FBlueprintEditorUtils
Additional Inherited Members
Public Types inherited from UStruct
typedef TArray< TPair< TFieldPath< FField >, int32 > > FUnresolvedScriptPropertiesArray
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Detailed Description
An object class.
Definition at line 2981 of file Class.h.
Member Typedef Documentation
ClassConstructorType
typedef void(* UClass::ClassConstructorType) (const FObjectInitializer &) private
Definition at line 2992 of file Class.h.
ClassVTableHelperCtorCallerType
typedef UObject *(* UClass::ClassVTableHelperCtorCallerType) (FVTableHelper &Helper) private
Definition at line 2993 of file Class.h.
StaticClassFunctionType
typedef UClass *(* UClass::StaticClassFunctionType) () private
Definition at line 2994 of file Class.h.
Constructor & Destructor Documentation
UClass() [1/3]
UClass::UClass (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
References FObjectInitializer::Get().
Referenced by UClass(), ~UClass(), AddDefaultSubobject(), CreatePersistentUberGraphFrame(), DeferredRegister(), FindArchetype(), FindCommonBase(), FindCommonBase(), GetAuthoritativeClass(), GetAuthoritativeClass(), GetSuperClass(), ImplementsInterface(), IsA(), IsSafeToSerializeToStructuredArchives(), TryConvertShortTypeNameToPathName(), TryFindTypeSlow(), and TryFindTypeSlowSafe().
UClass() [2/3]
UClass::UClass (const FObjectInitializer & ObjectInitializer, UClass * InSuperClass) explicit
References UClass().
UClass() [3/3]
UClass::UClass (EStaticConstructor , FName InName, uint32 InSize, uint32 InAlignment, EClassFlags InClassFlags, EClassCastFlags InClassCastFlags, const TCHAR * InClassConfigName, EObjectFlags InFlags, ClassConstructorType InClassConstructor, ClassVTableHelperCtorCallerType InClassVTableHelperCtorCaller, FUObjectCppClassStaticFunctions && InCppClassStaticFunctions)
References InName.
~UClass()
UClass::~UClass ()
References UClass(), InName, and TClass_WithinClass_StaticClass.
Member Function Documentation
AddDefaultSubobject()
void UClass::AddDefaultSubobject (UObject * NewSubobject, const UClass * BaseClass) inline
Adds a new default instance map item.
Definition at line 3625 of file Class.h.
References UClass(), UObject::UObject(), check, UObjectBase::GetClass(), UObjectBase::GetOuter(), UObjectBaseUtility::IsA(), and UStruct::IsChildOf().
AddFunctionToFunctionMap()
void UClass::AddFunctionToFunctionMap (UFunction * Function, FName FuncName) inline
Add a function to the function map.
Definition at line 3260 of file Class.h.
References AllFunctionsCache, AllFunctionsCacheLock, FuncMap, FuncMapLock, and Function.
AddNativeFunction() [1/2]
void UClass::AddNativeFunction (const ANSICHAR * InName, FNativeFuncPtr InPointer)
Add a native function to the internal native function table.
Parameters
InName name of the function
InPointer pointer to the function
References InName.
AddNativeFunction() [2/2]
void UClass::AddNativeFunction (const WIDECHAR * InName, FNativeFuncPtr InPointer)
Add a native function to the internal native function table, but with a unicode name.
Used when generating code from blueprints, which can have unicode identifiers for functions and properties.
Parameters
InName name of the function
InPointer pointer to the function
References InName.
AddReferencedObjects()
void UClass::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
References UObject::UObject().
AssembleReferenceTokenStream()
void UClass::AssembleReferenceTokenStream (bool bForce = false)
Assembles the token stream for realtime garbage collection by combining the per class only token stream for each class in the class hierarchy.
This is only done once and duplicate work is avoided by using an object flag.
Parameters
bForce Assemble the stream even if it has been already assembled (deletes the old one)
AssembleReferenceTokenStreamInternal()
void UClass::AssembleReferenceTokenStreamInternal (bool bForce = false) private
Tests if all properties tagged with Replicate were registered in GetLifetimeReplicatedProps.
AssembleReferenceTokenStreams()
void UClass::AssembleReferenceTokenStreams () static
Assemble reference token streams for all classes if they haven't had it assembled already.
Bind()
virtual void UClass::Bind () override virtual
Reimplemented from UField.
CallAddReferencedObjects()
FORCEINLINE void UClass::CallAddReferencedObjects (UObject * This, FReferenceCollector & Collector) const inline private
Calls AddReferencedObjects static method on the specified object.
Parameters
This Object to call ARO on.
Collector Reference collector.
Definition at line 3069 of file Class.h.
References UObject::UObject(), check, CppClassStaticFunctions, and FORCEINLINE.
CanCreateAssetOfClass()
virtual bool UClass::CanCreateAssetOfClass () const inline virtual
Some classes may not support creating assets of their type.
Definition at line 3582 of file Class.h.
CheckDefaultObjectIsValidLowLevelFast()
FORCEINLINE bool UClass::CheckDefaultObjectIsValidLowLevelFast (const int32 AlignmentCheck) const inline
Checks if the class default object is valid (not null and its address is a properly aligned pointer)
Parameters
AlignmentCheck address alignment to check
Returns
true if the CDO is valid
Definition at line 3548 of file Class.h.
References FORCEINLINE, ObjectPtr_Private::Friend::NoAccessTrackingGet(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
CleanupSparseClassData()
void UClass::CleanupSparseClassData () protected
ClearFunctionMapsCaches()
void UClass::ClearFunctionMapsCaches ()
Clears the function name caches, in case things have changed.
ClearSparseClassDataStruct()
void UClass::ClearSparseClassDataStruct (bool bInRecomplingOnLoad)
Clears the sparse class data struct for this and all child classes that directly reference it as a super-struct This will rename the current sparse class data struct aside into the transient package.
ConditionalRecompileClass()
virtual void UClass::ConditionalRecompileClass (FUObjectSerializeContext * InLoadContext) inline private virtual
Conditionally recompiles the class after loading, in case any dependencies were also newly loaded.
Parameters
ObjLoaded If set this is the list of objects that are currently loading, usualy GObjLoaded
Definition at line 3037 of file Class.h.
ConvertFullNameToShortTypeFullName()
FString UClass::ConvertFullNameToShortTypeFullName (FStringView InFullName) static
Takes a FullName (from e.g.
AssetData.GetFullName or UObject.GetFullName) in either ShortTypeFullName or PathFullName form ShortTypeFullName: "ClassObjectName /PackagePath/PackageShortName.ObjectName:SubObjectName" PathFullName: "/ClassPath/ClassPackage.ClassObjectName /PackagePath/PackageShortName.ObjectName:SubObjectName" Converts it to ShortTypeFullName if not already in that format and returns it
ConvertPathNameToShortTypeName()
FString UClass::ConvertPathNameToShortTypeName (FStringView InClassPathOrShortTypeName) static
Returns the ObjectName portion of a ClassPath name: "/Path/To.Object" is converted to "Object".
Returns the full string if it is already a ShortTypeName.
CreateDefaultObject()
virtual UObject * UClass::CreateDefaultObject () protected virtual
Get the default object from the class, creating it if missing, if requested or under a few other circumstances.
Returns
the CDO for this class
References UObject::UObject().
CreateLinkAndAddChildFunctionsToMap()
void UClass::CreateLinkAndAddChildFunctionsToMap (const FClassFunctionLinkInfo * Functions, uint32 NumFunctions)
CreatePersistentUberGraphFrame()
virtual void UClass::CreatePersistentUberGraphFrame (UObject * Obj, bool bCreateOnlyIfEmpty = false, bool bSkipSuperClass = false, UClass * OldClass = nullptr) const inline virtual
Creates memory to store temporary data.
Definition at line 3600 of file Class.h.
References UClass(), and UObject::UObject().
CreateSparseClassData()
void * UClass::CreateSparseClassData () protected
DeferredRegister()
virtual void UClass::DeferredRegister (UClass * UClassStaticClass, const TCHAR * PackageName, const TCHAR * Name) override virtual
Convert a boot-strap registered class into a real one, add to uobject array, etc.
Parameters
UClassStaticClass Now that it is known, fill in UClass::StaticClass() as the class
Reimplemented from UObjectBase.
References UClass(), InName, PackageName, and UE_WITH_REMOTE_OBJECT_HANDLE.
DestroyPersistentUberGraphFrame()
virtual void UClass::DestroyPersistentUberGraphFrame (UObject * Obj, bool bSkipSuperClass = false) const inline virtual
Clears memory to store temporary data.
Definition at line 3605 of file Class.h.
References UObject::UObject().
FindArchetype()
virtual UObject * UClass::FindArchetype (const UClass * ArchetypeClass, const FName ArchetypeName) const inline virtual
Finds the object that is used as the parent object when serializing properties, overridden for blueprints.
Definition at line 3774 of file Class.h.
References UClass(), and UObject::UObject().
FindCommonBase() [1/2]
UClass * UClass::FindCommonBase (const TArray< UClass * > & InClasses) static
Finds the common base class that parents the array of classes passed in.
Parameters
InClasses the array of classes to find the common base for
Returns
the common base class or NULL
References UClass().
FindCommonBase() [2/2]
UClass * UClass::FindCommonBase (UClass * InClassA, UClass * InClassB) static
Finds the common base class that parents the two classes passed in.
Parameters
InClassA the first class to find the common base for
InClassB the second class to find the common base for
Returns
the common base class or NULL
References UClass().
FindFunction()
UFunction * UClass::FindFunction (FName InName) const inline private
This signature intentionally hides the method declared in UObject to make it private.
Call FindFunctionByName instead; This method will search for a function declared in UClass instead of the class it was called on
Definition at line 3854 of file Class.h.
References UObject::FindFunction(), and InName.
FindFunctionByName()
UFunction * UClass::FindFunctionByName (FName InName, EIncludeSuperFlag::Type IncludeSuper = EIncludeSuperFlag::IncludeSuper) const
Looks for a given function name.
References IncludeSuper, EIncludeSuperFlag::IncludeSuper, and InName.
FindFunctionChecked()
UFunction * UClass::FindFunctionChecked (FName InName) const inline private
This signature intentionally hides the method declared in UObject to make it private.
Call FindFunctionByName instead; This method will search for a function declared in UClass instead of the class it was called on
Definition at line 3863 of file Class.h.
References UObject::FindFunctionChecked(), and InName.
FinishDestroy()
virtual void UClass::FinishDestroy () override virtual
Called to finish destroying the object.
After UObject::FinishDestroy is called, the object's memory should no longer be accessed.
Warning
Because properties are destroyed here, Super::FinishDestroy() should always be called at the end of your child class's FinishDestroy() method, rather than at the beginning.
Reimplemented from UStruct.
FlushCompilationQueueForLevel()
virtual void UClass::FlushCompilationQueueForLevel () inline private virtual
Definition at line 3038 of file Class.h.
GenerateFunctionList()
void UClass::GenerateFunctionList (TArray< FName > & OutArray) const inline
Definition at line 3145 of file Class.h.
References FuncMap, and FuncMapLock.
GetArchetypeForCDO()
virtual UObject * UClass::GetArchetypeForCDO () const virtual
Returns archetype object for CDO.
References UObject::UObject().
GetArchetypeForSparseClassData()
const void * UClass::GetArchetypeForSparseClassData () const
Returns archetype for sparse class data.
GetAssetRegistryTags()
virtual void UClass::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override virtual
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
Parameters
OutTags A list of key-value pairs associated with this object and their types
Reimplemented from UObject.
Referenced by UE_DEPRECATED().
GetAuthoritativeClass() [1/2]
virtual UClass * UClass::GetAuthoritativeClass () virtual
If there are potentially multiple versions of this class (e.g.
blueprint generated classes), this function will return the authoritative version, which should be used for references
Returns
The version of this class that references should be stored to
References UClass().
GetAuthoritativeClass() [2/2]
const UClass * UClass::GetAuthoritativeClass () const inline
Definition at line 3242 of file Class.h.
References UClass(), and GetAuthoritativeClass().
Referenced by GetAuthoritativeClass().
GetAutoCollapseCategories()
void UClass::GetAutoCollapseCategories (TArray< FString > & OutAutoCollapseCategories) const private
GetAutoExpandCategories()
void UClass::GetAutoExpandCategories (TArray< FString > & OutAutoExpandCategories) const private
GetClassFlags()
FORCEINLINE EClassFlags UClass::GetClassFlags () const inline
Gets the class flags.
Returns
The class flags.
Definition at line 3669 of file Class.h.
References ClassFlags, and FORCEINLINE.
GetClassGroupNames()
void UClass::GetClassGroupNames (TArray< FString > & OutClassGroupNames) const private
GetClassPathName()
FORCEINLINE FTopLevelAssetPath UClass::GetClassPathName () const inline
Returns class path name as a package + class FName pair.
Definition at line 3348 of file Class.h.
References FORCEINLINE, and UStruct::GetStructPathName().
GetConfigName()
const FString UClass::GetConfigName () const
Translates the hardcoded script config names (engine, editor, input and game) to their global pendants and otherwise uses config(myini) name to look for a game specific implementation and creates one based on the default if it doesn't exist yet.
Returns
name of the class specific ini file
GetCppTypeInfo()
const ICppClassTypeInfo * UClass::GetCppTypeInfo () const inline
Provides access to C++ type info.
Definition at line 3462 of file Class.h.
References CppTypeInfo.
GetDefaultObject() [1/2]
template<class T> T * UClass::GetDefaultObject () const inline
Get the default object from the class and cast to a particular type.
Returns
the CDO for this class
Definition at line 3614 of file Class.h.
References UObject::UObject(), check, GetDefaultObject(), and UObjectBaseUtility::IsA().
Referenced by GetDefaultObject().
GetDefaultObject() [2/2]
UObject * UClass::GetDefaultObject (bool bCreateIfNeeded = true) const inline
Get the default object from the class.
Parameters
bCreateIfNeeded if true (default) then the CDO is created if it is null
Returns
the CDO for this class
Definition at line 3509 of file Class.h.
References UObject::UObject(), InternalCreateDefaultObjectWrapper(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by FGameModeInfoCustomizer::GetCurrentGameModeCDO().
GetDefaultObjectName()
FName UClass::GetDefaultObjectName () const
Get the name of the CDO for the this class.
Returns
The name of the CDO
GetDefaultObjectPreloadDependencies()
virtual void UClass::GetDefaultObjectPreloadDependencies (TArray< UObject * > & OutDeps) inline virtual
Returns all objects that should be preloaded before the class default object is serialized at load time.
Only used by the EDL.
Parameters
OutDeps All objects that should be preloaded before the class default object is serialized at load time.
Definition at line 3794 of file Class.h.
References UObject::UObject(), and GetDefaultObjectPreloadDependencies().
Referenced by GetDefaultObjectPreloadDependencies().
GetDefaultObjectSubobjects()
void UClass::GetDefaultObjectSubobjects (TArray< UObject * > & OutDefaultSubobjects)
Gets all default instanced objects (often components).
Parameters
OutDefaultSubobjects An array to be filled with default subobjects.
GetDefaultPropertiesFeedbackContext()
class FFeedbackContext & UClass::GetDefaultPropertiesFeedbackContext () static
Feedback context for default property import.
GetDefaultsCount()
int32 UClass::GetDefaultsCount () inline
Returns amount of memory used by default object.
Definition at line 3497 of file Class.h.
References UStruct::GetPropertiesSize(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
GetDefaultSubobjectByName()
UObject * UClass::GetDefaultSubobjectByName (FName ToFind)
Searches for the default instanced object (often a component) by name.
References UObject::UObject().
GetDesc()
virtual FString UClass::GetDesc () override virtual
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
Reimplemented from UObject.
GetDescription()
FString UClass::GetDescription () const
GetHideFunctions()
void UClass::GetHideFunctions (TArray< FString > & OutHideFunctions) const private
GetOrCreateSparseClassData()
void * UClass::GetOrCreateSparseClassData () inline
Returns a pointer to the sidecar data structure.
This function will create an instance of the data structure if one has been specified and it has not yet been created.
Definition at line 3126 of file Class.h.
References CreateIfNull, and GetSparseClassData().
GetPersistentUberGraphFrame()
virtual uint8 * UClass::GetPersistentUberGraphFrame (UObject * Obj, UFunction * FuncToCheck) const inline virtual
Returns memory used to store temporary data on an instance, used by blueprints.
Definition at line 3594 of file Class.h.
References UObject::UObject().
GetPrefixCPP()
virtual const TCHAR * UClass::GetPrefixCPP () const override virtual
Returns the struct/ class prefix used for the C++ declaration of this struct/ class.
Returns
Prefix character used for C++ declaration of this struct/ class.
Reimplemented from UStruct.
GetPreloadDependencies()
virtual void UClass::GetPreloadDependencies (TArray< UObject * > & OutDeps) override virtual
Called during cooking.
Must return all objects that will be Preload()ed when this is serialized at load time. Only used by the EDL.
Parameters
OutDeps all objects that will be preloaded when this is serialized at load time
Reimplemented from UStruct.
GetPrioritizeCategories()
void UClass::GetPrioritizeCategories (TArray< FString > & OutPrioritizedCategories) const private
GetReinstancedClassPathName()
FTopLevelAssetPath UClass::GetReinstancedClassPathName () const
If this class was recompiled, returns the path to where we should find the new (i.e.
reinstanced) class. Note: If this is not a recompiled class, this will return a NULL path and should be handled appropriately.
GetReinstancedClassPathName_Impl()
virtual FTopLevelAssetPath UClass::GetReinstancedClassPathName_Impl () const inline protected virtual
Internal helper method for GetReinstancedClassPathName().
Subclasses can choose to override the default implementation to return a valid class path for recompiled class objects based on how reinstancing is handled.
Definition at line 3898 of file Class.h.
GetRestoreForUObjectOverwrite()
virtual FRestoreForUObjectOverwrite * UClass::GetRestoreForUObjectOverwrite () override virtual
Save information for StaticAllocateObject in the case of overwriting an existing object.
StaticAllocateObject will call delete on the result after calling Restore()
Returns
An FRestoreForUObjectOverwrite that can restore the object or NULL if this is not necessary.
Reimplemented from UObject.
GetSparseClassData()
const void * UClass::GetSparseClassData (const EGetSparseClassDataMethod GetMethod)
Returns a pointer to the sidecar data structure, based on the EGetSparseClassDataMethod.
Note
It is only safe to mutate this data when using "CreateIfNull", as others may return archetype/default data; consider GetOrCreateSparseClassData for this use-case.
Referenced by GetOrCreateSparseClassData().
GetSparseClassDataArchetypeStruct()
UScriptStruct * UClass::GetSparseClassDataArchetypeStruct () const
Returns the struct used by the sparse class data archetype.
GetSparseClassDataStruct()
UScriptStruct * UClass::GetSparseClassDataStruct () const
Returns a pointer to the type of the sidecar data structure if one is specified.
GetSuperClass()
UClass * UClass::GetSuperClass () const inline
Returns parent class, the parent of a Class is always another class.
Definition at line 3488 of file Class.h.
References UClass(), and UStruct::GetSuperStruct().
Referenced by FClassTree::ChangeParentClass(), and UE::MovieScene::FCustomAccessorView::FindCustomAccessorIndex().
HasAllCastFlags()
FORCEINLINE bool UClass::HasAllCastFlags (EClassCastFlags FlagsToCheck) const inline
Definition at line 3686 of file Class.h.
References ClassCastFlags, and FORCEINLINE.
HasAllClassFlags()
FORCEINLINE bool UClass::HasAllClassFlags (EClassFlags FlagsToCheck) const inline
Used to safely check whether all of the passed in flags are set.
Parameters
FlagsToCheck Class flags to check for
Returns
true if all of the passed in flags are set (including no flags passed in), false otherwise
Definition at line 3659 of file Class.h.
References ClassFlags, EnumHasAllFlags(), and FORCEINLINE.
HasAnyCastFlag()
FORCEINLINE bool UClass::HasAnyCastFlag (EClassCastFlags FlagToCheck) const inline
Used to safely check whether the passed in flag is set.
Parameters
FlagToCheck the cast flag to check for (value should be one of the EClassCastFlags enums)
Returns
true if the passed in flag is set, false otherwise (including no flag passed in)
Definition at line 3682 of file Class.h.
References ClassCastFlags, and FORCEINLINE.
Referenced by Cast().
HasAnyClassFlags()
FORCEINLINE bool UClass::HasAnyClassFlags (EClassFlags FlagsToCheck) const inline
Used to safely check whether the passed in flag is set.
Parameters
FlagsToCheck Class flag(s) to check for
Returns
true if the passed in flag is set, false otherwise (including no flag passed in, unless the FlagsToCheck is CLASS_AllFlags)
Definition at line 3648 of file Class.h.
References ClassFlags, EnumHasAnyFlags(), and FORCEINLINE.
HasProperty()
virtual bool UClass::HasProperty (const FProperty * InProperty) const virtual
Checks if the property exists on this class or a parent class.
Parameters
InProperty The property to check if it is contained in this or a parent class.
Returns
True if the property exists on this or a parent class.
Implements()
template<typename T> bool UClass::Implements () const inline private
This signature intentionally hides the method declared in UObject to make it private.
Call ImplementsInterface instead; Hidden because calling Implements on a class almost always indicates an error where the caller should use ImplementsInterface
Definition at line 3845 of file Class.h.
References UObject::Implements().
ImplementsInterface()
bool UClass::ImplementsInterface (const class UClass * SomeInterface) const
This will return whether or not this class implements the passed in class / interface.
Parameters
SomeClass - the interface to check and see if this class implements it
References UClass().
Referenced by UObject::Implements().
InitPropertiesFromCustomList()
virtual void UClass::InitPropertiesFromCustomList (uint8 * DataPtr, const uint8 * DefaultDataPtr) inline virtual
Helper method to assist with initializing object properties from an explicit list.
Parameters
InStruct the current scope for which the given property list applies
DataPtr destination address (where to start copying values to)
DefaultDataPtr source address (where to start copying the defaults data from)
Definition at line 3572 of file Class.h.
InternalCreateDefaultObjectWrapper()
void UClass::InternalCreateDefaultObjectWrapper () const private
Referenced by GetDefaultObject().
IsA()
bool UClass::IsA (const UClass * Parent) const inline private
This signature intentionally hides the method declared in UObjectBaseUtility to make it private.
Call IsChildOf instead; Hidden because calling IsA on a class almost always indicates an error where the caller should use IsChildOf
Definition at line 3835 of file Class.h.
References UClass(), UObjectBaseUtility::IsA(), and Parent.
IsAsset()
virtual bool UClass::IsAsset () const inline override virtual
Returns true if this object is considered an asset.
Reimplemented from UObject.
Definition at line 3320 of file Class.h.
IsAutoCollapseCategory()
bool UClass::IsAutoCollapseCategory (const TCHAR * InCategory) const private
IsAutoExpandCategory()
bool UClass::IsAutoExpandCategory (const TCHAR * InCategory) const private
IsClassGroupName()
bool UClass::IsClassGroupName (const TCHAR * InGroupName) const private
IsFunctionHidden()
bool UClass::IsFunctionHidden (const TCHAR * InFunction) const private
IsFunctionImplementedInScript()
virtual bool UClass::IsFunctionImplementedInScript (FName InFunctionName) const virtual
Determines if the specified function has been implemented in a Blueprint.
Parameters
InFunctionName The name of the function to test
Returns
True if the specified function exists and is implemented in a blueprint generated class
IsNameStableForNetworking()
virtual bool UClass::IsNameStableForNetworking () const inline override virtual
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
Reimplemented from UObject.
Definition at line 3321 of file Class.h.
IsPrioritizeCategory()
bool UClass::IsPrioritizeCategory (const TCHAR * InCategory) const private
IsSafeToSerializeToStructuredArchives()
bool UClass::IsSafeToSerializeToStructuredArchives (UClass * InClass) static
Helper function for determining if the given class is compatible with structured archive serialization.
References UClass(), and UE_INTERNAL.
IsShortTypeName()
bool UClass::IsShortTypeName (FStringView ClassPathOrShortTypeName) static
Returns whether the given stringview is in ShortTypeName form: No directory separators "/" or object separators ".", SUBOBJECT_DELIMITER Returns true for empty string.
IsStructTrashed()
virtual bool UClass::IsStructTrashed () const override virtual
If true, this class has been cleaned and sanitized (trashed) and should not be used.
Reimplemented from UStruct.
References Flags, Name, Property, Record, and UE_INTERNAL.
Link()
virtual void UClass::Link (FArchive & Ar, bool bRelinkExistingProperties) override virtual
Creates the field/property links and gets structure ready for use at runtime.
Reimplemented from UStruct.
References Ar.
PostInitInstance()
virtual void UClass::PostInitInstance (UObject * InObj, FObjectInstancingGraph * InstanceGraph) inline virtual
Called after PostInitProperties during object construction to allow class specific initialization of an object instance.
Definition at line 3558 of file Class.h.
References UObject::UObject().
PostInitProperties()
virtual void UClass::PostInitProperties () override virtual
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
This is called before any serialization or other setup has happened.
Reimplemented from UObject.
PostLoad()
virtual void UClass::PostLoad () override virtual
Do any object-specific cleanup required immediately after loading an object.
This is not called for newly-created objects, and by default will always execute on the game thread.
Reimplemented from UStruct.
PostLoadDefaultObject()
virtual void UClass::PostLoadDefaultObject (UObject * Object) virtual
Wraps the PostLoad() call for the class default object.
Parameters
Object the default object to call PostLoad() on
References UObject::UObject(), and Object.
PostLoadInstance()
virtual void UClass::PostLoadInstance (UObject * InObj) inline virtual
Called during PostLoad of an object to allow class specific PostLoad operations of an object instance.
Definition at line 3563 of file Class.h.
References UObject::UObject().
PurgeClass()
virtual void UClass::PurgeClass (bool bRecompilingOnLoad) virtual
Purges out the properties of this class in preparation for it to be regenerated.
Parameters
bRecompilingOnLoad - true if we are recompiling on load
In editor, properties are not freed until DestroyPropertiesPendingDestruction is called.
RemoveFunctionFromFunctionMap()
void UClass::RemoveFunctionFromFunctionMap (UFunction * Function) inline
Remove a function from the function map.
Definition at line 3276 of file Class.h.
References AllFunctionsCache, AllFunctionsCacheLock, FuncMap, FuncMapLock, and Function.
Rename()
virtual bool UClass::Rename (const TCHAR * NewName = nullptr, UObject * NewOuter = nullptr, ERenameFlags Flags = REN_None) override virtual
Rename this object to a unique name, or change its outer.
Remarks
A unique name will be generated if NewName is null and if either is true: NewOuter is null or NewOuter equals the current outer.
Parameters
NewName The new name of the object, if null then NewOuter should be set
NewOuter New Outer this object will be placed within, if null it will use the current outer
Flags Flags to specify what happens during the rename
Reimplemented from UObject.
References UObject::UObject(), Flags, and REN_None.
Serialize()
virtual void UClass::Serialize (FArchive & Ar) override virtual
Handles reading, writing, and reference collecting using FArchive.
This implementation handles all FProperty serialization, but can be overridden for native variables.
Reimplemented from UStruct.
References Ar.
SerializeDefaultObject() [1/2]
virtual void UClass::SerializeDefaultObject (UObject * Object, FArchive & Ar) inline final virtual
serializes the passed in object as this class's default object using the given archive
Parameters
Object the object to serialize as default
Ar the archive to serialize from
Definition at line 3718 of file Class.h.
References UObject::UObject(), Ar, Object, and SerializeDefaultObject().
SerializeDefaultObject() [2/2]
virtual void UClass::SerializeDefaultObject (UObject * Object, FStructuredArchive::FSlot Slot) virtual
serializes the passed in object as this class's default object using the given archive slot
Parameters
Object the object to serialize as default
Slot the structured archive slot to serialize from
References UObject::UObject(), and Object.
Referenced by SerializeDefaultObject().
SerializeSparseClassData()
void UClass::SerializeSparseClassData (FStructuredArchive::FSlot Slot)
serializes the associated sparse class data for the passed in object using the given archive slot.
This should only be called if the class has an associated sparse data structure.
Parameters
Slot the structured archive slot to serialize from
SetCppTypeInfoStatic()
void UClass::SetCppTypeInfoStatic (const FCppClassTypeInfoStatic * InCppTypeInfoStatic) inline
Sets C++ type information.
Should not be NULL.
Definition at line 3469 of file Class.h.
References check, and CppTypeInfo.
SetDefaultObject()
void UClass::SetDefaultObject (UObject * InClassDefaultObject)
Get the immutable default object from the class.
Parameters
bCreateIfNeeded if true (default) then the CDO is created if it is null
Returns
the immutable CDO for this class Sets the default object of the class
Parameters
InClassDefaultObject new class default object or null
References UObject::UObject().
SetSparseClassDataStruct()
void UClass::SetSparseClassDataStruct (UScriptStruct * InSparseClassDataStruct)
SetSuperStruct()
virtual void UClass::SetSuperStruct (UStruct * NewSuperStruct) override virtual
Sets the super struct pointer and updates hash information as necessary.
Note that this is not sufficient to actually reparent a struct, it simply sets a pointer.
Reimplemented from UStruct.
References UStruct::UStruct().
SetupObjectInitializer()
virtual void UClass::SetupObjectInitializer (FObjectInitializer & ObjectInitializer) const inline virtual
Allows class to provide data to the object initializer that can affect how native class subobjects are created.
Definition at line 3577 of file Class.h.
SetUpRuntimeReplicationData()
void UClass::SetUpRuntimeReplicationData ()
Initializes the ClassReps and NetFields arrays used by replication.
This happens lazily based on the CLASS_ReplicationDataIsSetUp flag, and will generally occur in Link or PostLoad. It's possible that replicated UFunctions will load after their owning class, so UFunction::PostLoad will clear the flag on its owning class to force lazy initialization next time the data is needed. Also happens after blueprint compiliation.
ShouldUseDynamicSubobjectInstancing()
bool UClass::ShouldUseDynamicSubobjectInstancing () const
Returns true if the object instancing graph should analyze default data at runtime to determine which of its object properties need to be instanced at construction time, rather than exclusively relying on reflected property semantics.
SupportsDynamicInstancedReference()
virtual bool UClass::SupportsDynamicInstancedReference () const inline protected virtual
Subtypes can optionally override to return true.
This will enable dynamic subobject instancing, which will use default data to determine which properties need instancing at construction/serialization time rather than reflected property 'Instanced' semantics.
Definition at line 3888 of file Class.h.
TagSubobjects()
virtual void UClass::TagSubobjects (EObjectFlags NewFlags) override virtual
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
Parameters
ObjectFlags Object Flags to enable on the related objects
Reimplemented from UStruct.
ThreadedPostLoadAssetRegistryTagsOverride()
virtual void UClass::ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext & Context) const protected virtual
Performs fixup on loaded asset registry data.
DO NOT CALL ASSETREGISTRY FUNCTIONS FROM THIS FUNCTION, IT WILL DEADLOCK because this function is called from inside the AssetRegistry CriticalSection. IT MUST BE SAFE TO CALL IN MULTITHREADED BACKGROUND THREADS because the AssetRegistry can call this function from a background thread.
Note that this function is only called on Class Default Objects where the actual object instance data used to generate the asset data is not available.
Parameters
Context Contains input and receives output from the function.
See also
FPostloadAssetRegistryTagsContext
Reimplemented from UObject.
TryConvertShortTypeNameToPathName() [1/2]
template<typename T> FTopLevelAssetPath UClass::TryConvertShortTypeNameToPathName (const FString & InShortTypeName, ELogVerbosity::Type AmbiguousMessageVerbosity = ELogVerbosity::NoLogging, const TCHAR * AmbiguousClassMessage = nullptr) inline static
Tries to convert short class name to class path name.
This will only work if the class exists in memory
Parameters
InShortClassName Short class name. If this parameter is already a path name then it's going to be returned as FTopLevelAssetPath
AmbiguousMessageVerbosity Verbosity with which to log a message if class name is ambiguous
AmbiguousClassMessage Additional message to log when class name is ambiguous (e.g. current operation)
Returns
Class path name if successful. Empty FTopLevelAssetPath otherwise.
Definition at line 3420 of file Class.h.
References ELogVerbosity::NoLogging, and TryConvertShortTypeNameToPathName().
TryConvertShortTypeNameToPathName() [2/2]
FTopLevelAssetPath UClass::TryConvertShortTypeNameToPathName (UClass * TypeClass, const FString & InShortTypeName, ELogVerbosity::Type AmbiguousMessageVerbosity = ELogVerbosity::NoLogging, const TCHAR * AmbiguousClassMessage = nullptr) static
Tries to convert short class name to class path name.
This will only work if the class exists in memory This function is slow and should not be used in performance critical situations
Parameters
TypeClass Expected Class of the type that needs to be converted (UEnum / UStruct / UClass)
InShortClassName Short class name. If this parameter is already a path name then it's going to be returned as FTopLevelAssetPath
AmbiguousMessageVerbosity Verbosity with which to log a message if class name is ambiguous
AmbiguousClassMessage Additional message to log when class name is ambiguous (e.g. current operation)
Returns
Class path name if successful. Empty FTopLevelAssetPath otherwise.
References UClass(), and ELogVerbosity::NoLogging.
Referenced by TryConvertShortTypeNameToPathName().
TryFindTypeSlow() [1/2]
template<typename T> T * UClass::TryFindTypeSlow (const FString & InShortNameOrPathName, EFindFirstObjectOptions InOptions = EFindFirstObjectOptions::None) inline static
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
Useful for tracking down and fixing remaining places that use short class names. This function is slow and should not be used in performance critical situations
Parameters
InShortNameOrPathName Class name
Returns
Pointer to a type object if successful, false otherwise
Definition at line 3371 of file Class.h.
References InOptions, None, and TryFindTypeSlow().
TryFindTypeSlow() [2/2]
UField * UClass::TryFindTypeSlow (UClass * TypeClass, const FString & InPathNameOrShortName, EFindFirstObjectOptions InOptions = EFindFirstObjectOptions::None) static
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
Useful for tracking down and fixing remaining places that use short class names. This function is slow and should not be used in performance critical situations
Parameters
TypeClass Class of the expected type. Must be a subclass of UField
InShortNameOrPathName Class name
Returns
Pointer to a type object if successful, nullptr otherwise
References UClass(), InOptions, and None.
Referenced by FPropertyTrackEditor< TrackType >::GetCustomizedTrackClass(), TryFindTypeSlow(), and FGameplayAbilityInputBinds::TryFixShortEnumName().
TryFindTypeSlowSafe() [1/2]
template<typename T> T * UClass::TryFindTypeSlowSafe (const FString & InShortNameOrPathName, EFindFirstObjectOptions InOptions = EFindFirstObjectOptions::None) inline static
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
Useful for tracking down and fixing remaining places that use short class names. This function is slow and should not be used in performance critical situations This version of TryFindType will not assert when saving package or when collecting garbage
Parameters
InShortNameOrPathName Class name
Returns
Pointer to a type object if successful, nullptr otherwise
Definition at line 3396 of file Class.h.
References InOptions, None, and TryFindTypeSlowSafe().
TryFindTypeSlowSafe() [2/2]
UField * UClass::TryFindTypeSlowSafe (UClass * TypeClass, const FString & InPathNameOrShortName, EFindFirstObjectOptions InOptions = EFindFirstObjectOptions::None) static
Utility function that tries to find a type (class/struct/enum) given a path name or a short name however it will throw a warning (with a callstack) if it's the latter.
Useful for tracking down and fixing remaining places that use short class names. This function is slow and should not be used in performance critical situations This version of TryFindType will not assert when saving package or when collecting garbage
Parameters
TypeClass Class of the expected type. Must be a subclass of UField
InShortNameOrPathName Class name
Returns
Pointer to a type object if successful, nullptr otherwise
References UClass(), InOptions, and None.
Referenced by TryFindTypeSlowSafe().
TryFixShortClassNameExportPath()
bool UClass::TryFixShortClassNameExportPath (FString & InOutExportPathToFix, ELogVerbosity::Type AmbiguousMessageVerbosity = ELogVerbosity::NoLogging, const TCHAR * AmbiguousClassMessage = nullptr, bool bClearOnError = false) static
Tries to fix an export path containing short class name.
Will not modify the input InOutExportPathToFix if a fixup was not necessary. Optionally modifies it if a fixup is necessary but unsuccessful.
Parameters
InOutExportPathToFix Export path (Class'/Path/To.Object')
AmbiguousMessageVerbosity Verbosity with which to log a message if class name is ambiguous
AmbiguousClassMessage Additional message to log when class name is ambiguous (e.g. current operation)
bClearOnError If the fixup is necessary but unsuccessful, if bClearOnError, clear the value and return true, otherwise leave the value unchanged and return false.
Returns
True if the short path was successfully fixed. False if the provided export path did not contain short class name or the short path could not be fixed.
References ELogVerbosity::NoLogging.
UE_DEPRECATED() [1/3]
UClass::UE_DEPRECATED (5. 4, "Implement the version that takes FAssetRegistryTagsContext instead.") const & override
References UStruct::const, and GetAssetRegistryTags().
UE_DEPRECATED() [2/3]
UClass::UE_DEPRECATED (5. 5, "Replace with UE::Reflection::DoesSparseClassDataOverrideArchetype(Class, [](const FProperty*){return true;})") const
Returns whether the sparse class data on this instance overrides that of its archetype (in type or value)
References UStruct::const.
UE_DEPRECATED() [3/3]
UClass::UE_DEPRECATED (5. 6, "ClassDefaultObject will be made private in the next release. For general purpose access to the CDO consider using the global GetDefault<>() or GetMutableDefault<>() functions.") private
The class default object; used for delta serialization and object initialization.
References UObject::UObject().
Friends And Related Symbol Documentation
FBlueprintCompilationManagerImpl
friend struct FBlueprintCompilationManagerImpl friend
Definition at line 2990 of file Class.h.
References FBlueprintCompilationManagerImpl.
Referenced by FBlueprintCompilationManagerImpl.
FBlueprintCompileReinstancer
friend class FBlueprintCompileReinstancer friend
Definition at line 2989 of file Class.h.
References FBlueprintCompileReinstancer.
Referenced by FBlueprintCompileReinstancer.
FBlueprintEditorUtils
friend class (UClass, UStruct, 0, TEXT("/Script/CoreUObject"), CASTCLASS_UClass, 1) DECLARE_WITHIN_UPACKAGE() public FBlueprintEditorUtils friend
Definition at line 2988 of file Class.h.
References FBlueprintEditorUtils.
Referenced by FBlueprintEditorUtils.
Field Documentation
AllFunctionsCache
TMap<FName, UFunction*> UClass::AllFunctionsCache mutable private
A cache of all functions by name that exist in this class or a parent (superclass or interface) context.
Definition at line 3170 of file Class.h.
Referenced by AddFunctionToFunctionMap(), and RemoveFunctionFromFunctionMap().
AllFunctionsCacheLock
FUClassFuncLock UClass::AllFunctionsCacheLock mutable private
Scope lock to avoid the SuperFuncMap being read and written to simultaneously on multiple threads.
Definition at line 3173 of file Class.h.
Referenced by AddFunctionToFunctionMap(), and RemoveFunctionFromFunctionMap().
bCooked
bool UClass::bCooked private
Used to check if the class was cooked or not.
Definition at line 3007 of file Class.h.
bLayoutChanging
bool UClass::bLayoutChanging private
Used to check if the class layout is currently changing and therefore is not ready for a CDO to be created.
Definition at line 3010 of file Class.h.
ClassCastFlags
EClassCastFlags UClass::ClassCastFlags private
Cast flags used to accelerate dynamic_cast<T*> on objects of this type for common T.
Definition at line 3016 of file Class.h.
Referenced by HasAllCastFlags(), and HasAnyCastFlag().
ClassConfigName
FName UClass::ClassConfigName private
Which Name.ini file to load Config variables out of.
Definition at line 3042 of file Class.h.
ClassConstructor
ClassConstructorType UClass::ClassConstructor private
Definition at line 2996 of file Class.h.
ClassFlags
EClassFlags UClass::ClassFlags private
Class flags; See EClassFlags for more information.
Definition at line 3013 of file Class.h.
Referenced by GetClassFlags(), HasAllClassFlags(), and HasAnyClassFlags().
ClassReps
TArray<FRepRecord> UClass::ClassReps private
List of replication records.
Definition at line 3045 of file Class.h.
ClassUnique
int32 UClass::ClassUnique mutable private
Class pseudo-unique counter; used to accelerate unique instance name generation.
Definition at line 3001 of file Class.h.
ClassVTableHelperCtorCaller
ClassVTableHelperCtorCallerType UClass::ClassVTableHelperCtorCaller private
Definition at line 2997 of file Class.h.
ClassWithin
TObjectPtr<UClass> UClass::ClassWithin private
The required type for the outer of instances of this class.
Definition at line 3019 of file Class.h.
CppClassStaticFunctions
FUObjectCppClassStaticFunctions UClass::CppClassStaticFunctions private
Definition at line 2998 of file Class.h.
Referenced by CallAddReferencedObjects().
CppTypeInfo
TOptional<FCppClassTypeInfo> UClass::CppTypeInfo private
Provides access to attributes of the underlying C++ class.
Should never be unset.
Definition at line 3160 of file Class.h.
Referenced by GetCppTypeInfo(), and SetCppTypeInfoStatic().
FirstOwnedClassRep
int32 UClass::FirstOwnedClassRep = 0 private
Index of the first ClassRep that belongs to this class.
Anything before that was defined by / belongs to parent classes.
Definition at line 3004 of file Class.h.
FuncMap
TMap<FName, TObjectPtr<UFunction> > UClass::FuncMap private
Map of all functions by name contained in this class.
Definition at line 3164 of file Class.h.
Referenced by AddFunctionToFunctionMap(), GenerateFunctionList(), and RemoveFunctionFromFunctionMap().
FuncMapLock
FUClassFuncLock UClass::FuncMapLock mutable private
Scope lock to avoid the FuncMap being read and written to simultaneously on multiple threads.
Definition at line 3167 of file Class.h.
Referenced by AddFunctionToFunctionMap(), GenerateFunctionList(), and RemoveFunctionFromFunctionMap().
Interfaces
TArray<FImplementedInterface> UClass::Interfaces
The list of interfaces which this class implements, along with the pointer property that is located at the offset of the interface's vtable.
If the interface class isn't native, the property will be null.
Definition at line 3180 of file Class.h.
Referenced by TFieldIterator< T >::IterateToNext().
NativeFunctionLookupTable
TArray<FNativeFunctionLookup> UClass::NativeFunctionLookupTable
This class's native functions.
Definition at line 3186 of file Class.h.
NetFields
TArray<UField*> UClass::NetFields private
List of network relevant fields (functions)
Definition at line 3048 of file Class.h.
ReferenceSchema
UE::GC::FSchemaOwner UClass::ReferenceSchema
GC schema, finalized in AssembleReferenceTokenStream.
Definition at line 3183 of file Class.h.
SparseClassData
void* UClass::SparseClassData protected
This is where we store the data that is only changed per class instead of per instance.
Definition at line 3111 of file Class.h.
SparseClassDataStruct
TObjectPtr<UScriptStruct> UClass::SparseClassDataStruct protected
The struct used to store sparse class data.
Definition at line 3114 of file Class.h.
The documentation for this class was generated from the following file:
Class.h