Unreal Engine 5.6 C++ API: SScrollBox::FSlot Class Reference
SScrollBox::FSlot Class Reference
A Slot that provides layout options for the contents of a scrollable box.
#include "SScrollBox.h"
Public Member Functions
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlotArguments & FillContentSize (TAttribute< float > InStretchCoefficient, TAttribute< float > InShrinkStretchCoefficient=TAttribute< float >())
The widget's content size is adjusted proportionally to fit the available space.
FSlotArguments & FillSize (TAttribute< float > InStretchCoefficient)
The available space will be distributed proportionately.
FSlotArguments & MaxSize (TAttribute< float > InMaxHeight)
Set the max size in SlateUnit this slot can be.
FSlotArguments & MinSize (TAttribute< float > InMinHeight)
Set the min size in SlateUnit this slot can be.
SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot, TBasicLayoutWidgetSlot< FSlot >, TResizingWidgetSlotMixin< FSlot >) FSlotArguments &AutoSize()
The widget's DesiredSize will be used as the space required.
SLATE_SLOT_END_ARGS () FSlot()
Default values for a slot.
Public Member Functions inherited from TBasicLayoutWidgetSlot< FSlot >
TBasicLayoutWidgetSlot ()
SLATE_SLOT_BEGIN_ARGS_TwoMixins (TBasicLayoutWidgetSlot, TSlotBase< FSlot >, TPaddingWidgetSlotMixin< FSlot >, TAlignmentWidgetSlotMixin< FSlot >) SLATE_SLOT_END_ARGS() void Construct(const FChildren &SlotOwner
TAlignmentWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
TPaddingWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
Public Member Functions inherited from TWidgetSlotWithAttributeSupport< FSlot >
virtual ~TWidgetSlotWithAttributeSupport ()
void Construct (const FChildren &SlotOwner, typename Super::FSlotArguments &&InArgs)
virtual FName GetContainerName () const override
virtual uint32 GetContainerSortOrder () const override
virtual SWidget & GetContainerWidget () const override
void RequestSortAttribute ()
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
TPaddingWidgetSlotMixin ()
FMargin GetPadding () const
void SetPadding (TAttribute< FMargin > InPadding)
Public Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Public Member Functions inherited from TResizingWidgetSlotMixin< FSlot >
TResizingWidgetSlotMixin ()
float GetMaxSize () const
Get the max size the slot can be.
float GetMinSize () const
Get the min size the slot can be.
float GetShrinkSizeValue () const
Get the size parameter for the space rule, used when the slot size is shrinking below desired size.
FSizeParam::ESizeRule GetSizeRule () const
Get the space rule this slot should occupy along panel's direction.
float GetSizeValue () const
Get the size parameter for the space rule.
void SetMaxSize (TAttribute< float > InMaxSize)
Set the max size in SlateUnit this slot can be.
void SetMinSize (TAttribute< float > InMinSize)
Set the min size in SlateUnit this slot can be.
void SetSizeParam (FSizeParam InSizeParam)
Set the size Param of the slot, It could be a FStretch, FStretchContent, or a FAuto.
void SetSizeToAuto ()
The widget's DesiredSize will be used as the space required.
void SetSizeToStretch (TAttribute< float > InStretchCoefficient)
The available space will be distributed proportionately to each slots stretch coefficient.
void SetSizeToStretchContent (TAttribute< float > InStretchCoefficient, TAttribute< float > InShrinkStretchCoefficient=TAttribute< float >())
The widget's content size is adjusted proportionally to fit the available space.
Static Public Member Functions
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Static Public Member Functions inherited from TBasicLayoutWidgetSlot< FSlot >
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Static Public Member Functions inherited from TWidgetSlotWithAttributeSupport< FSlot >
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Private Attributes
bool bIsShrinkSizeValueSet
How much space this slot should occupy along scrollbox's direction.
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Data Fields inherited from TBasicLayoutWidgetSlot< FSlot >
FSlotArguments && InArgs
Protected Types inherited from TResizingWidgetSlotMixin< FSlot >
using TSlateSlotAttribute
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Protected Member Functions inherited from TResizingWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Static Protected Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Static Protected Member Functions inherited from TResizingWidgetSlotMixin< FSlot >
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Protected Attributes inherited from TResizingWidgetSlotMixin< FSlot >
TSlateSlotAttribute< float > MaxSize
The max size that this slot can be (0 if no max)
TSlateSlotAttribute< float > MinSize
The min size that this slot can be.
TSlateSlotAttribute< float > ShrinkSizeValue
The actual value this size parameter stores, used for shrinking (negative if not defined, use SizeValue).
FSizeParam::ESizeRule SizeRule
The sizing rule to use, see ESizeRule for more info how the different rules work.
TSlateSlotAttribute< float > SizeValue
The actual value this size parameter stores.
Detailed Description
A Slot that provides layout options for the contents of a scrollable box.
Definition at line 79 of file SScrollBox.h.
Member Function Documentation
Construct()
void SScrollBox::FSlot::Construct (const FChildren & SlotOwner, FSlotArguments && InArgs)
References TBasicLayoutWidgetSlot< FSlot >::InArgs.
FillContentSize()
FSlotArguments & SScrollBox::FSlot::FillContentSize (TAttribute< float > InStretchCoefficient, TAttribute< float > InShrinkStretchCoefficient = TAttribute<float>()) inline
The widget's content size is adjusted proportionally to fit the available space.
The slots size starts at DesiredSize, and a slot with coefficient of 2 will get adjusted twice as much as slot with coefficient 1 to fit the available space.
Parameters
InStretchCoefficient Stretch coefficient for this slot.
InShrinkStretchCoefficient If specified, this stretch coefficient is used when the slots is shrinking below desired size. Otherwise InStretchCoefficient is used for both shrink and grow.
Definition at line 103 of file SScrollBox.h.
References MoveTemp().
FillSize()
FSlotArguments & SScrollBox::FSlot::FillSize (TAttribute< float > InStretchCoefficient) inline
The available space will be distributed proportionately.
Definition at line 91 of file SScrollBox.h.
References MoveTemp().
MaxSize()
FSlotArguments & SScrollBox::FSlot::MaxSize (TAttribute< float > InMaxHeight) inline
Set the max size in SlateUnit this slot can be.
Definition at line 117 of file SScrollBox.h.
References MoveTemp().
MinSize()
FSlotArguments & SScrollBox::FSlot::MinSize (TAttribute< float > InMinHeight) inline
Set the min size in SlateUnit this slot can be.
Definition at line 110 of file SScrollBox.h.
References MoveTemp().
RegisterAttributes()
void SScrollBox::FSlot::RegisterAttributes (FSlateWidgetSlotAttributeInitializer & AttributeInitializer) static
SLATE_SLOT_BEGIN_ARGS_OneMixin()
SScrollBox::FSlot::SLATE_SLOT_BEGIN_ARGS_OneMixin (FSlot , TBasicLayoutWidgetSlot< FSlot > , TResizingWidgetSlotMixin< FSlot >) & inline
The widget's DesiredSize will be used as the space required.
Definition at line 82 of file SScrollBox.h.
References TBasicLayoutWidgetSlot< FSlot >::TBasicLayoutWidgetSlot(), and TResizingWidgetSlotMixin< FSlot >::TResizingWidgetSlotMixin().
SLATE_SLOT_END_ARGS()
SScrollBox::FSlot::SLATE_SLOT_END_ARGS () inline
Default values for a slot.
Definition at line 122 of file SScrollBox.h.
References TBasicLayoutWidgetSlot< FSlot >::TBasicLayoutWidgetSlot(), TResizingWidgetSlotMixin< FSlot >::TResizingWidgetSlotMixin(), TResizingWidgetSlotMixin< FSlot >::SizeRule, and FSizeParam::SizeRule_Auto.
Field Documentation
bIsShrinkSizeValueSet
bool SScrollBox::FSlot::bIsShrinkSizeValueSet private
How much space this slot should occupy along scrollbox's direction.
When SizeRule is SizeRule_Auto, the widget's DesiredSize will be used as the space required. When SizeRule is SizeRule_Stretch, the available space will be distributed proportionately between peer Widgets depending on the Value property. Available space is space remaining after all the peers' SizeRule_Auto requirements have been satisfied. Flag indicating if the ShrinkSizeValue value is set.
Definition at line 145 of file SScrollBox.h.
The documentation for this class was generated from the following file:
SScrollBox.h