Unreal Engine 5.6 C++ API: FMeshDescription Struct Reference
FMeshDescription Struct Reference
#include "MeshDescription.h"
Public Member Functions
MESHDESCRIPTION_API FMeshDescription ()
MESHDESCRIPTION_API FMeshDescription (const FMeshDescription &)
FMeshDescription (FMeshDescription &&)=default
~FMeshDescription ()=default
void BuildEdgeIndexers ()
MESHDESCRIPTION_API void BuildIndexers ()
void BuildPolygonGroupIndexers ()
void BuildPolygonIndexers ()
void BuildVertexIndexers ()
void BuildVertexInstanceIndexers ()
MESHDESCRIPTION_API void Compact (FElementIDRemappings &OutRemappings)
Compacts the data held in the mesh description, and returns an object describing how the IDs have been remapped.
MESHDESCRIPTION_API FBox ComputeBoundingBox () const
MESHDESCRIPTION_API void ComputePolygonTriangulation (const FPolygonID PolygonID)
Generates triangles and internal edges for the given polygon.
FEdgeID CreateEdge (const FVertexID VertexID0, const FVertexID VertexID1)
Adds a new edge to the mesh and returns its ID.
void CreateEdgeWithID (const FEdgeID EdgeID, const FVertexID VertexID0, const FVertexID VertexID1)
Adds a new edge to the mesh with the given ID.
FPolygonID CreatePolygon (const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs=nullptr)
Adds a new polygon to the mesh and returns its ID.
FPolygonGroupID CreatePolygonGroup ()
Adds a new polygon group to the mesh and returns its ID.
void CreatePolygonGroupWithID (const FPolygonGroupID PolygonGroupID)
Adds a new polygon group to the mesh with the given ID.
void CreatePolygonWithID (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs=nullptr)
Adds a new polygon to the mesh with the given ID.
FTriangleID CreateTriangle (const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs=nullptr)
Adds a new triangle to the mesh and returns its ID.
void CreateTriangleWithID (const FTriangleID TriangleID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs=nullptr)
Adds a new triangle to the mesh with the given ID.
FUVID CreateUV (const int32 UVChannel=0)
Adds a new UV to the mesh and returns its ID.
void CreateUVWithID (const FUVID UVID, const int32 UVChannel=0)
Adds a new UV to the mesh with the given ID.
FVertexID CreateVertex ()
Adds a new vertex to the mesh and returns its ID.
FVertexInstanceID CreateVertexInstance (const FVertexID VertexID)
Adds a new vertex instance to the mesh and returns its ID.
void CreateVertexInstanceWithID (const FVertexInstanceID VertexInstanceID, const FVertexID VertexID)
Adds a new vertex instance to the mesh with the given ID.
void CreateVertexWithID (const FVertexID VertexID)
Adds a new vertex to the mesh with the given ID.
MESHDESCRIPTION_API void DeleteEdge (const FEdgeID EdgeID, TArray< FVertexID > *InOutOrphanedVerticesPtr=nullptr)
Deletes an edge from the mesh.
MESHDESCRIPTION_API void DeletePolygon (const FPolygonID PolygonID, TArray< FEdgeID > *InOutOrphanedEdgesPtr=nullptr, TArray< FVertexInstanceID > *InOutOrphanedVertexInstancesPtr=nullptr, TArray< FPolygonGroupID > *InOutOrphanedPolygonGroupsPtr=nullptr)
Deletes a polygon from the mesh.
void DeletePolygonGroup (const FPolygonGroupID PolygonGroupID)
Deletes a polygon group from the mesh.
MESHDESCRIPTION_API void DeletePolygons (const TArray< FPolygonID > &Polygons)
Deletes polygons from the mesh and remove all orphaned polygon groups, vertex instances, edges and vertices.
MESHDESCRIPTION_API void DeleteTriangle (const FTriangleID TriangleID, TArray< FEdgeID > *InOutOrphanedEdgesPtr=nullptr, TArray< FVertexInstanceID > *InOutOrphanedVertexInstancesPtr=nullptr, TArray< FPolygonGroupID > *InOutOrphanedPolygonGroupsPtr=nullptr)
Deletes a triangle from the mesh.
MESHDESCRIPTION_API void DeleteTriangles (const TArray< FTriangleID > &Triangles)
Deletes triangles from the mesh and remove all orphaned polygon groups, vertex instances, edges and vertices.
void DeleteUV (const FUVID UVID, const int32 UVChannel=0)
Deletes a UV from the mesh.
void DeleteVertex (const FVertexID VertexID)
Deletes a vertex from the mesh.
MESHDESCRIPTION_API void DeleteVertexInstance (const FVertexInstanceID VertexInstanceID, TArray< FVertexID > *InOutOrphanedVerticesPtr=nullptr)
Deletes a vertex instance from a mesh.
TAttributesSet< FEdgeID > & EdgeAttributes ()
const TAttributesSet< FEdgeID > & EdgeAttributes () const
FEdgeArray & Edges ()
const FEdgeArray & Edges () const
MESHDESCRIPTION_API void Empty ()
MESHDESCRIPTION_API void FindPolygonPerimeter (const FPolygonID PolygonID, TArrayView< FEdgeID > Edges) const
MESHDESCRIPTION_API void FindPolygonPerimeter (TArrayView< const FTriangleID > Triangles, TArrayView< TTuple< int32, int32 > > Result) const
Determines the vertex instances which form the perimeter of a polygon.
for (int32 Index=0;Index< 3;++Index)
for (int32 Index=0;Index< 3;++Index)
MESHDESCRIPTION_API FBoxSphereBounds GetBounds () const
Returns bounds of vertices.
template<typename Alloc>
TArray< FPolygonID, Alloc > GetEdgeConnectedPolygons (const FEdgeID EdgeID) const
Returns the polygons connected to this edge as an array with the specified allocator template type.
TArray< FPolygonID > GetEdgeConnectedPolygons (const FEdgeID EdgeID) const
Returns the polygons connected to this edge.
template<typename Alloc>
void GetEdgeConnectedPolygons (const FEdgeID EdgeID, TArray< FPolygonID, Alloc > &OutPolygonIDs) const
Populates the passed array with polygon IDs connected to this edge.
TArrayView< const FTriangleID > GetEdgeConnectedTriangleIDs (const FEdgeID EdgeID) const
Returns reference to an array of triangle IDs connected to this edge.
FVertexID GetEdgeVertex (const FEdgeID EdgeID, int32 VertexNumber) const
Returns the vertex ID corresponding to one of the edge endpoints.
TArrayView< const FVertexID > GetEdgeVertices (const FEdgeID EdgeID) const
Returns a pair of vertex IDs defining the edge.
TMap< FName, FMeshElementTypeWrapper > & GetElements ()
const TMap< FName, FMeshElementTypeWrapper > & GetElements () const
int32 GetNumEdgeConnectedPolygons (const FEdgeID EdgeID) const
Returns the number of polygons connected to this edge.
int32 GetNumEdgeConnectedTriangles (const FEdgeID EdgeID) const
int32 GetNumPolygonGroupPolygons (const FPolygonGroupID PolygonGroupID) const
Returns the number of polygons in this polygon group.
int32 GetNumPolygonGroupTriangles (const FPolygonGroupID PolygonGroupID) const
Returns the number of triangles in this polygon group.
int32 GetNumPolygonInternalEdges (const FPolygonID PolygonID) const
Return the number of internal edges in this polygon.
int32 GetNumPolygonTriangles (const FPolygonID PolygonID) const
Return the number of triangles which comprise this polygon.
int32 GetNumPolygonVertices (const FPolygonID PolygonID) const
Returns the number of vertices this polygon has.
int32 GetNumUVElementChannels () const
Gets the number of UV element channels.
int32 GetNumVertexConnectedEdges (const FVertexID VertexID) const
Returns number of edges connected to this vertex.
int32 GetNumVertexConnectedPolygons (const FVertexID VertexID) const
Returns the number of polygons connected to this vertex.
int32 GetNumVertexConnectedTriangles (const FVertexID VertexID) const
Returns number of triangles connected to this vertex.
int32 GetNumVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const
Returns the number of polygons connected to this vertex instance.
int32 GetNumVertexInstanceConnectedTriangles (const FVertexInstanceID VertexInstanceID) const
Returns the number of triangles connected to this vertex instance.
int32 GetNumVertexVertexInstances (const FVertexID VertexID) const
Returns number of vertex instances created from this vertex.
template<typename Alloc>
TArray< FPolygonID, Alloc > GetPolygonAdjacentPolygons (const FPolygonID PolygonID) const
Return adjacent polygons into a TArray with the specified allocator.
TArray< FPolygonID > GetPolygonAdjacentPolygons (const FPolygonID PolygonID) const
Return adjacent polygons to this polygon.
template<typename Alloc>
void GetPolygonAdjacentPolygons (const FPolygonID PolygonID, TArray< FPolygonID, Alloc > &OutPolygonIDs) const
Populates the passed array with adjacent polygons.
MESHDESCRIPTION_API float GetPolygonCornerAngleForVertex (const FPolygonID PolygonID, const FVertexID VertexID) const
TArrayView< const FPolygonID > GetPolygonGroupPolygonIDs (const FPolygonGroupID PolygonGroupID) const
Returns the polygons associated with the given polygon group.
TArrayView< const FTriangleID > GetPolygonGroupTriangles (const FPolygonGroupID PolygonGroupID) const
Returns the triangles associated with the given polygon group.
template<typename Alloc>
TArray< FEdgeID, Alloc > GetPolygonInternalEdges (const FPolygonID PolygonID) const
Return the internal edges of this polygon, i.e.
TArray< FEdgeID > GetPolygonInternalEdges (const FPolygonID PolygonID) const
Return the internal edges of this polygon, i.e.
template<typename Alloc>
void GetPolygonInternalEdges (const FPolygonID PolygonID, TArray< FEdgeID, Alloc > &OutEdgeIDs) const
Populate the provided array with a list of edges which are internal to the polygon, i.e.
template<typename Alloc>
TArray< FEdgeID, Alloc > GetPolygonPerimeterEdges (const FPolygonID PolygonID) const
Returns the vertices which form the polygon perimeter as an array templated on the given allocator.
TArray< FEdgeID > GetPolygonPerimeterEdges (const FPolygonID PolygonID) const
Returns the vertices which form the polygon perimeter.
template<typename Alloc>
void GetPolygonPerimeterEdges (const FPolygonID PolygonID, TArray< FEdgeID, Alloc > &OutEdgeIDs) const
Populates the passed array with the edges which form the polygon perimeter.
FPolygonGroupID GetPolygonPolygonGroup (const FPolygonID PolygonID) const
Return the polygon group associated with a polygon.
TArrayView< const FTriangleID > GetPolygonTriangles (const FPolygonID PolygonID) const
Return reference to an array of triangle IDs which comprise this polygon.
template<typename Alloc>
TArray< FVertexInstanceID, Alloc > GetPolygonVertexInstances (const FPolygonID PolygonID) const
TArray< FVertexInstanceID > GetPolygonVertexInstances (const FPolygonID PolygonID) const
template<typename Alloc>
void GetPolygonVertexInstances (const FPolygonID PolygonID, TArray< FVertexInstanceID, Alloc > &OutVertexInstanceIDs) const
Returns reference to an array of VertexInstance IDs forming the perimeter of this polygon.
template<typename Alloc>
TArray< FVertexID, Alloc > GetPolygonVertices (const FPolygonID PolygonID) const
Returns the vertices which form the polygon perimeter as an array templated on the given allocator.
TArray< FVertexID > GetPolygonVertices (const FPolygonID PolygonID) const
Returns the vertices which form the polygon perimeter.
template<typename Alloc>
void GetPolygonVertices (const FPolygonID PolygonID, TArray< FVertexID, Alloc > &OutVertexIDs) const
Populates the passed array of VertexIDs with the vertices which form the polygon perimeter.
template<typename Alloc>
TArray< FTriangleID, Alloc > GetTriangleAdjacentTriangles (const FTriangleID TriangleID) const
Return adjacent triangles into a TArray with the specified allocator.
TArray< FTriangleID > GetTriangleAdjacentTriangles (const FTriangleID TriangleID) const
Return adjacent triangles to this triangle.
template<typename Alloc>
void GetTriangleAdjacentTriangles (const FTriangleID TriangleID, TArray< FTriangleID, Alloc > &OutTriangleIDs) const
Populates the passed array with adjacent triangles.
MESHDESCRIPTION_API float GetTriangleCornerAngleForVertex (const FTriangleID TriangleID, const FVertexID VertexID) const
TArrayView< FEdgeID > GetTriangleEdges (const FTriangleID TriangleID) const
Return the edges which form this triangle.
FPolygonID GetTrianglePolygon (const FTriangleID TriangleID) const
Get the polygon which contains this triangle.
FPolygonGroupID GetTrianglePolygonGroup (const FTriangleID TriangleID) const
Get the polygon group which contains this triangle.
TArrayView< FUVID > GetTriangleUVIndices (const FTriangleID TriangleID, int32 UVChannel=0) const
Return UV indices for this triangle for the given channel.
FVertexInstanceID GetTriangleVertexInstance (const FTriangleID TriangleID, const int32 Index) const
Get the specified vertex instance by index.
TArrayView< const FVertexInstanceID > GetTriangleVertexInstances (const FTriangleID TriangleID) const
Get the vertex instances which define this triangle.
TArrayView< const FVertexID > GetTriangleVertices (const FTriangleID TriangleID) const
Return the vertices which define this triangle.
template<typename Alloc>
TArray< FVertexID, Alloc > GetVertexAdjacentVertices (const FVertexID VertexID) const
Returns the vertices adjacent to this vertex as an array with the specified allocator template type.
TArray< FVertexID > GetVertexAdjacentVertices (const FVertexID VertexID) const
Returns the vertices adjacent to this vertex.
template<typename Alloc>
void GetVertexAdjacentVertices (const FVertexID VertexID, TArray< FVertexID, Alloc > &OutAdjacentVertexIDs) const
Populates the passed array of VertexIDs with the vertices adjacent to this vertex.
TArrayView< const FEdgeID > GetVertexConnectedEdgeIDs (const FVertexID VertexID) const
Returns reference to an array of Edge IDs connected to this vertex.
template<typename Alloc>
TArray< FPolygonID, Alloc > GetVertexConnectedPolygons (const FVertexID VertexID) const
Returns the polygons connected to this vertex as an array with the specified allocator template type.
TArray< FPolygonID > GetVertexConnectedPolygons (const FVertexID VertexID) const
Returns the polygons connected to this vertex.
template<typename Alloc>
void GetVertexConnectedPolygons (const FVertexID VertexID, TArray< FPolygonID, Alloc > &OutConnectedPolygonIDs) const
Populates the passed array of PolygonIDs with the polygons connected to this vertex.
template<typename Alloc>
TArray< FTriangleID, Alloc > GetVertexConnectedTriangles (const FVertexID VertexID) const
Returns the triangles connected to this vertex as an array with the specified allocator template type.
TArray< FTriangleID > GetVertexConnectedTriangles (const FVertexID VertexID) const
Returns the triangles connected to this vertex.
template<typename Alloc>
void GetVertexConnectedTriangles (const FVertexID VertexID, TArray< FTriangleID, Alloc > &OutConnectedTriangleIDs) const
Populates the passed array of TriangleIDs with the triangles connected to this vertex.
template<typename Alloc>
TArray< FPolygonID, Alloc > GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const
Returns the polygons connected to this vertex instance as an array with the specified allocator template type.
TArray< FPolygonID > GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const
Returns the polygons connected to this vertex instance.
template<typename Alloc>
void GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID, TArray< FPolygonID, Alloc > &OutPolygonIDs) const
Populates the passed array with the polygons connected to this vertex instance.
TArrayView< const FTriangleID > GetVertexInstanceConnectedTriangleIDs (const FVertexInstanceID VertexInstanceID) const
Returns reference to an array of Triangle IDs connected to this vertex instance.
FVertexInstanceID GetVertexInstanceForPolygonVertex (const FPolygonID PolygonID, const FVertexID VertexID) const
Return the vertex instance which corresponds to the given vertex on the given polygon, or INDEX_NONE.
FVertexInstanceID GetVertexInstanceForTriangleVertex (const FTriangleID TriangleID, const FVertexID VertexID) const
Return the vertex instance which corresponds to the given vertex on the given triangle, or INDEX_NONE.
MESHDESCRIPTION_API FEdgeID GetVertexInstancePairEdge (const FVertexInstanceID VertexInstanceID0, const FVertexInstanceID VertexInstanceID1) const
Returns the edge ID defined by the two given vertex instance IDs, if there is one; otherwise INDEX_NONE.
FVertexID GetVertexInstanceVertex (const FVertexInstanceID VertexInstanceID) const
Returns the vertex ID associated with the given vertex instance.
MESHDESCRIPTION_API FEdgeID GetVertexPairEdge (const FVertexID VertexID0, const FVertexID VertexID1) const
Returns the edge ID defined by the two given vertex IDs, if there is one; otherwise INDEX_NONE.
FVector3f GetVertexPosition (const FVertexID VertexID) const
Returns the position of this vertex.
TVertexAttributesRef< FVector3f > GetVertexPositions ()
TVertexAttributesRef< const FVector3f > GetVertexPositions () const
TArrayView< const FVertexInstanceID > GetVertexVertexInstanceIDs (const FVertexID VertexID) const
Returns reference to an array of VertexInstance IDs instanced from this vertex.
bool IsEdgeInternal (const FEdgeID EdgeID) const
Determine whether a given edge is an internal edge between triangles of a polygon.
bool IsEdgeInternalToPolygon (const FEdgeID EdgeID, const FPolygonID PolygonID) const
Determine whether a given edge is an internal edge between triangles of a specific polygon.
bool IsEdgeValid (const FEdgeID EdgeID) const
Returns whether the passed edge ID is valid.
MESHDESCRIPTION_API bool IsEmpty () const
bool IsPolygonGroupValid (const FPolygonGroupID PolygonGroupID) const
Returns whether the passed polygon group ID is valid.
bool IsPolygonValid (const FPolygonID PolygonID) const
Returns whether the passed polygon ID is valid.
bool IsTrianglePartOfNgon (const FTriangleID TriangleID) const
Determines if this triangle is part of an n-gon.
bool IsTriangleValid (const FTriangleID TriangleID) const
Returns whether the passed triangle ID is valid.
bool IsUVValid (const FUVID UVID, const int32 UVChannel=0) const
Returns whether the passed UV ID is valid.
bool IsVertexInstanceValid (const FVertexInstanceID VertexInstanceID) const
Returns whether the passed vertex instance ID is valid.
MESHDESCRIPTION_API bool IsVertexOrphaned (const FVertexID VertexID) const
Returns whether a given vertex is orphaned, i.e.
bool IsVertexValid (const FVertexID VertexID) const
Returns whether the passed vertex ID is valid.
MESHDESCRIPTION_API bool NeedsCompact () const
Determines if calling Compact() would perform actual compaction or not.
MESHDESCRIPTION_API FMeshDescription & operator= (const FMeshDescription &)
FMeshDescription & operator= (FMeshDescription &&)=default
TAttributesSet< FPolygonID > & PolygonAttributes ()
const TAttributesSet< FPolygonID > & PolygonAttributes () const
TAttributesSet< FPolygonGroupID > & PolygonGroupAttributes ()
const TAttributesSet< FPolygonGroupID > & PolygonGroupAttributes () const
FPolygonGroupArray & PolygonGroups ()
const FPolygonGroupArray & PolygonGroups () const
FPolygonArray & Polygons ()
const FPolygonArray & Polygons () const
MESHDESCRIPTION_API void RebuildIndexers ()
MESHDESCRIPTION_API void Remap (const FElementIDRemappings &Remappings)
Remaps the element IDs in the mesh description according to the passed in object.
MESHDESCRIPTION_API void RemapPolygonGroups (const TMap< FPolygonGroupID, FPolygonGroupID > &Remap)
Remaps polygon groups according to the supplied map.
void ReserveNewEdges (const int32 NumEdges)
Reserves space for this number of new edges.
void ReserveNewPolygonGroups (const int32 NumPolygonGroups)
Reserves space for this number of new polygon groups.
void ReserveNewPolygons (const int32 NumPolygons)
Reserves space for this number of new polygons.
void ReserveNewTriangles (const int32 NumTriangles)
Reserves space for this number of new triangles.
void ReserveNewUVs (const int32 NumUVs, const int32 UVChannel=0)
Reserves space for this number of new UVs.
void ReserveNewVertexInstances (const int32 NumVertexInstances)
Reserves space for this number of new vertex instances.
void ReserveNewVertices (const int32 NumVertices)
Reserves space for this number of new vertices.
MESHDESCRIPTION_API void ResetIndexers ()
void ResumeEdgeIndexing ()
void ResumePolygonGroupIndexing ()
void ResumePolygonIndexing ()
void ResumeUVIndexing ()
void ResumeVertexIndexing ()
void ResumeVertexInstanceIndexing ()
MESHDESCRIPTION_API void ReverseAllPolygonFacing ()
Reverses the winding order of all polygons in the mesh.
MESHDESCRIPTION_API void ReversePolygonFacing (const FPolygonID PolygonID)
Reverse the winding order of the vertices of this polygon.
MESHDESCRIPTION_API void ReverseTriangleFacing (const FTriangleID TriangleID)
Reverse the winding order of the vertices of this triangle.
MESHDESCRIPTION_API void Serialize (FArchive &Ar)
MESHDESCRIPTION_API void SerializeLegacy (FArchive &Ar)
MESHDESCRIPTION_API void SetNumUVChannels (const int32 NumUVChannels)
Sets the specified number of UV channels.
void SetPolygonPolygonGroup (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID)
Sets the polygon group associated with a polygon.
MESHDESCRIPTION_API void SetPolygonVertexInstance (const FPolygonID PolygonID, const int32 PerimeterIndex, const FVertexInstanceID VertexInstanceID)
Set the vertex instance at the given index around the polygon to the new value.
MESHDESCRIPTION_API void SetPolygonVertexInstances (const FPolygonID PolygonID, TArrayView< const FVertexInstanceID > VertexInstanceIDs)
MESHDESCRIPTION_API void SetTriangleUVIndices (const FTriangleID TriangleID, TArrayView< const FUVID > UVIDs, int32 UVChannel=0)
Set the UV indices for this triangle.
MESHDESCRIPTION_API void SplitPolygon (FPolygonID PolygonID)
void SuspendEdgeIndexing ()
void SuspendPolygonGroupIndexing ()
void SuspendPolygonIndexing ()
void SuspendUVIndexing ()
void SuspendVertexIndexing ()
void SuspendVertexInstanceIndexing ()
MESHDESCRIPTION_API void TransferPolygonGroup (FPolygonGroupID SourceID, FPolygonGroupID DestinationID)
Transfer the source polygon group data to the destination polygon group.
TAttributesSet< FTriangleID > & TriangleAttributes ()
const TAttributesSet< FTriangleID > & TriangleAttributes () const
FTriangleArray & Triangles ()
const FTriangleArray & Triangles () const
MESHDESCRIPTION_API void TriangulateMesh ()
Retriangulates the entire mesh.
UE_DEPRECATED (4.26, "Please use GetEdgeConnectedTriangleIDs() instead.") TArray< FTriangleID > GetEdgeConnectedTriangles(const FEdgeID EdgeID) const
UE_DEPRECATED (4.26, "Please use GetPolygonGroupPolygonIDs() instead.") TArray< FPolygonID > GetPolygonGroupPolygons(const FPolygonGroupID PolygonGroupID) const
UE_DEPRECATED (4.26, "Please use GetPolygonTriangles() instead.") TArray< FTriangleID > GetPolygonTriangleIDs(const FPolygonID PolygonID) const
UE_DEPRECATED (4.26, "Please use GetVertexConnectedEdgeIDs instead.") TArray< FEdgeID > GetVertexConnectedEdges(const FVertexID VertexID) const
UE_DEPRECATED (4.26, "Please use GetVertexInstanceTriangleIDs() instead.") TArray< FTriangleID > GetVertexInstanceConnectedTriangles(const FVertexInstanceID VertexInstanceID) const
UE_DEPRECATED (4.26, "Please use GetVertexVertexInstanceIDs instead.") TArray< FVertexInstanceID > GetVertexVertexInstances(const FVertexID VertexID) const
UE_DEPRECATED (4.26, "Use the other form of GetTriangleEdges") void GetTriangleEdges(const FTriangleID TriangleID
Populates the passed array with the edges which define this triangle.
UE_DEPRECATED (4.26, "Use the other form of GetTriangleVertices") void GetTriangleVertices(const FTriangleID TriangleID
Populates the passed array with the vertices which define this triangle.
TAttributesSet< FUVID > & UVAttributes (int32 Index)
const TAttributesSet< FUVID > & UVAttributes (int32 Index) const
FUVArray & UVs (int32 Index)
const FUVArray & UVs (int32 Index) const
TAttributesSet< FVertexID > & VertexAttributes ()
const TAttributesSet< FVertexID > & VertexAttributes () const
TAttributesSet< FVertexInstanceID > & VertexInstanceAttributes ()
const TAttributesSet< FVertexInstanceID > & VertexInstanceAttributes () const
FVertexInstanceArray & VertexInstances ()
const FVertexInstanceArray & VertexInstances () const
FVertexArray & Vertices ()
const FVertexArray & Vertices () const
Data Fields
TArrayView< FVertexID > OutVertexIDs const
TArrayView< FEdgeID > OutEdgeIDs const
TArrayView< const FEdgeID > TriEdges = TriangleEdges[TriangleID]
TArrayView< const FVertexID > TriVerts = TriangleVertices[TriangleID]
Static Public Attributes
static MESHDESCRIPTION_API FName EdgesName
static MESHDESCRIPTION_API FName PolygonGroupsName
static MESHDESCRIPTION_API FName PolygonsName
static MESHDESCRIPTION_API FName TrianglesName
static MESHDESCRIPTION_API FName UVsName
static MESHDESCRIPTION_API FName VertexInstancesName
static MESHDESCRIPTION_API FName VerticesName
Private Member Functions
template<class T>
void AddUnique (TArray< T > &Container, const T &Item)
template<class T>
void AddUnique (TSet< T > &Container, const T &Item)
MESHDESCRIPTION_API void Cache ()
MESHDESCRIPTION_API FVector ComputePolygonNormal (TArrayView< const FVertexInstanceID > PerimeterVertexInstanceIDs) const
MESHDESCRIPTION_API FPlane ComputePolygonPlane (TArrayView< const FVertexInstanceID > PerimeterVertexInstanceIDs) const
MESHDESCRIPTION_API void CreateEdge_Internal (const FEdgeID EdgeID, const FVertexID VertexID0, const FVertexID VertexID1)
MESHDESCRIPTION_API void CreatePolygon_Internal (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs)
MESHDESCRIPTION_API void CreatePolygonTriangles (const FPolygonID PolygonID, TArrayView< const FVertexInstanceID > VertexInstanceIDs)
MESHDESCRIPTION_API void CreateTriangle_Internal (const FTriangleID TriangleID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > *OutEdgeIDs)
MESHDESCRIPTION_API void CreateVertexInstance_Internal (const FVertexInstanceID VertexInstanceID, const FVertexID VertexID)
template<template< typename... > class TContainer>
void DeleteEdge_Internal (const FEdgeID EdgeID, TContainer< FVertexID > *InOutOrphanedVerticesPtr=nullptr)
template<template< typename... > class TContainer>
void DeletePolygon_Internal (const FPolygonID PolygonID, TContainer< FEdgeID > *InOutOrphanedEdgesPtr=nullptr, TContainer< FVertexInstanceID > *InOutOrphanedVertexInstancesPtr=nullptr, TContainer< FPolygonGroupID > *InOutOrphanedPolygonGroupsPtr=nullptr)
template<template< typename... > class TContainer>
void DeleteTriangle_Internal (const FTriangleID TriangleID, TContainer< FEdgeID > *InOutOrphanedEdgesPtr=nullptr, TContainer< FVertexInstanceID > *InOutOrphanedVertexInstancesPtr=nullptr, TContainer< FPolygonGroupID > *InOutOrphanedPolygonGroupsPtr=nullptr)
template<template< typename... > class TContainer>
void DeleteVertexInstance_Internal (const FVertexInstanceID VertexInstanceID, TContainer< FVertexID > *InOutOrphanedVerticesPtr=nullptr)
MESHDESCRIPTION_API void FixUpElementIDs (const FElementIDRemappings &Remappings)
Given a set of index remappings, fixes up references to element IDs.
MESHDESCRIPTION_API void Initialize ()
MESHDESCRIPTION_API void InitializeIndexers ()
MESHDESCRIPTION_API void RemovePolygonTriangles (const FPolygonID PolygonID)
Private Attributes
FMeshElementChannels * EdgeElements
FMeshElementIndexer EdgeToTriangles
TMeshAttributesArray< TArrayView< FVertexID > > EdgeVertices
TMap< FName, FMeshElementTypeWrapper > Elements
FMeshElementChannels * PolygonElements
FMeshElementChannels * PolygonGroupElements
FMeshElementIndexer PolygonGroupToPolygons
FMeshElementIndexer PolygonGroupToTriangles
TMeshAttributesArray< FPolygonGroupID > PolygonPolygonGroups
FMeshElementIndexer PolygonToTriangles
TMeshAttributesArray< TArrayView< FEdgeID > > TriangleEdges
FMeshElementChannels * TriangleElements
TMeshAttributesArray< FPolygonGroupID > TrianglePolygonGroups
TMeshAttributesArray< FPolygonID > TrianglePolygons
TMeshAttributesArray< TArrayView< FUVID > > TriangleUVs
TMeshAttributesArray< TArrayView< FVertexInstanceID > > TriangleVertexInstances
TMeshAttributesArray< TArrayView< FVertexID > > TriangleVertices
FMeshElementChannels * UVElements
FMeshElementIndexer UVToTriangles
FMeshElementChannels * VertexElements
FMeshElementChannels * VertexInstanceElements
FMeshElementIndexer VertexInstanceToTriangles
TMeshAttributesArray< FVertexID > VertexInstanceVertices
TMeshAttributesArray< FVector3f > VertexPositions
FMeshElementIndexer VertexToEdges
FMeshElementIndexer VertexToVertexInstances
Friends
MESHDESCRIPTION_API FArchive & operator<< (FArchive &Ar, FMeshDescription &MeshDescription)
Detailed Description
Definition at line 93 of file MeshDescription.h.
Constructor & Destructor Documentation
FMeshDescription() [1/3]
MESHDESCRIPTION_API FMeshDescription::FMeshDescription ()
Referenced by FMeshDescription(), FMeshDescription(), operator<<, operator=(), and operator=().
~FMeshDescription()
FMeshDescription::~FMeshDescription () default
FMeshDescription() [2/3]
MESHDESCRIPTION_API FMeshDescription::FMeshDescription (const FMeshDescription &)
References FMeshDescription().
FMeshDescription() [3/3]
FMeshDescription::FMeshDescription (FMeshDescription &&) default
References FMeshDescription().
Member Function Documentation
AddUnique() [1/2]
template<class T> void FMeshDescription::AddUnique (TArray< T > & Container, const T & Item) inline private
Definition at line 1266 of file MeshDescription.h.
References Container, and Item.
AddUnique() [2/2]
template<class T> void FMeshDescription::AddUnique (TSet< T > & Container, const T & Item) inline private
Definition at line 1272 of file MeshDescription.h.
References Container, and Item.
BuildEdgeIndexers()
void FMeshDescription::BuildEdgeIndexers () inline
Definition at line 190 of file MeshDescription.h.
References EdgeToTriangles.
BuildIndexers()
MESHDESCRIPTION_API void FMeshDescription::BuildIndexers ()
BuildPolygonGroupIndexers()
void FMeshDescription::BuildPolygonGroupIndexers () inline
Definition at line 192 of file MeshDescription.h.
References PolygonGroupToPolygons, and PolygonGroupToTriangles.
BuildPolygonIndexers()
void FMeshDescription::BuildPolygonIndexers () inline
Definition at line 191 of file MeshDescription.h.
References PolygonToTriangles.
BuildVertexIndexers()
void FMeshDescription::BuildVertexIndexers () inline
Definition at line 188 of file MeshDescription.h.
References VertexToEdges, and VertexToVertexInstances.
BuildVertexInstanceIndexers()
void FMeshDescription::BuildVertexInstanceIndexers () inline
Definition at line 189 of file MeshDescription.h.
References VertexInstanceToTriangles.
Cache()
MESHDESCRIPTION_API void FMeshDescription::Cache () private
Compact()
MESHDESCRIPTION_API void FMeshDescription::Compact (FElementIDRemappings & OutRemappings)
Compacts the data held in the mesh description, and returns an object describing how the IDs have been remapped.
ComputeBoundingBox()
MESHDESCRIPTION_API FBox FMeshDescription::ComputeBoundingBox () const
ComputePolygonNormal()
MESHDESCRIPTION_API FVector FMeshDescription::ComputePolygonNormal (TArrayView< const FVertexInstanceID > PerimeterVertexInstanceIDs) const private
References FVector.
ComputePolygonPlane()
MESHDESCRIPTION_API FPlane FMeshDescription::ComputePolygonPlane (TArrayView< const FVertexInstanceID > PerimeterVertexInstanceIDs) const private
ComputePolygonTriangulation()
MESHDESCRIPTION_API void FMeshDescription::ComputePolygonTriangulation (const FPolygonID PolygonID)
Generates triangles and internal edges for the given polygon.
CreateEdge()
FEdgeID FMeshDescription::CreateEdge (const FVertexID VertexID0, const FVertexID VertexID1) inline
Adds a new edge to the mesh and returns its ID.
Definition at line 302 of file MeshDescription.h.
References CreateEdge_Internal(), and EdgeElements.
CreateEdge_Internal()
MESHDESCRIPTION_API void FMeshDescription::CreateEdge_Internal (const FEdgeID EdgeID, const FVertexID VertexID0, const FVertexID VertexID1) private
Referenced by CreateEdge(), and CreateEdgeWithID().
CreateEdgeWithID()
void FMeshDescription::CreateEdgeWithID (const FEdgeID EdgeID, const FVertexID VertexID0, const FVertexID VertexID1) inline
Adds a new edge to the mesh with the given ID.
Definition at line 310 of file MeshDescription.h.
References CreateEdge_Internal(), and EdgeElements.
CreatePolygon()
FPolygonID FMeshDescription::CreatePolygon (const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs = nullptr) inline
Adds a new polygon to the mesh and returns its ID.
This will also make any missing edges, and all constituent triangles.
Definition at line 367 of file MeshDescription.h.
References CreatePolygon_Internal(), and PolygonElements.
CreatePolygon_Internal()
MESHDESCRIPTION_API void FMeshDescription::CreatePolygon_Internal (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs) private
Referenced by CreatePolygon(), and CreatePolygonWithID().
CreatePolygonGroup()
FPolygonGroupID FMeshDescription::CreatePolygonGroup () inline
Adds a new polygon group to the mesh and returns its ID.
Definition at line 402 of file MeshDescription.h.
References PolygonGroupElements.
CreatePolygonGroupWithID()
void FMeshDescription::CreatePolygonGroupWithID (const FPolygonGroupID PolygonGroupID) inline
Adds a new polygon group to the mesh with the given ID.
Definition at line 409 of file MeshDescription.h.
References PolygonGroupElements.
CreatePolygonTriangles()
MESHDESCRIPTION_API void FMeshDescription::CreatePolygonTriangles (const FPolygonID PolygonID, TArrayView< const FVertexInstanceID > VertexInstanceIDs) private
CreatePolygonWithID()
void FMeshDescription::CreatePolygonWithID (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs = nullptr) inline
Adds a new polygon to the mesh with the given ID.
This will also make any missing edges, and all constituent triangles.
Definition at line 375 of file MeshDescription.h.
References CreatePolygon_Internal(), and PolygonElements.
CreateTriangle()
FTriangleID FMeshDescription::CreateTriangle (const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs = nullptr) inline
Adds a new triangle to the mesh and returns its ID.
This will also make an encapsulating polygon, and any missing edges.
Definition at line 332 of file MeshDescription.h.
References CreateTriangle_Internal(), and TriangleElements.
CreateTriangle_Internal()
MESHDESCRIPTION_API void FMeshDescription::CreateTriangle_Internal (const FTriangleID TriangleID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs) private
Referenced by CreateTriangle(), and CreateTriangleWithID().
CreateTriangleWithID()
void FMeshDescription::CreateTriangleWithID (const FTriangleID TriangleID, const FPolygonGroupID PolygonGroupID, TArrayView< const FVertexInstanceID > VertexInstanceIDs, TArray< FEdgeID > * OutEdgeIDs = nullptr) inline
Adds a new triangle to the mesh with the given ID.
This will also make an encapsulating polygon, and any missing edges.
Definition at line 340 of file MeshDescription.h.
References CreateTriangle_Internal(), and TriangleElements.
CreateUV()
FUVID FMeshDescription::CreateUV (const int32 UVChannel = 0) inline
Adds a new UV to the mesh and returns its ID.
Definition at line 269 of file MeshDescription.h.
References UVElements.
CreateUVWithID()
void FMeshDescription::CreateUVWithID (const FUVID UVID, const int32 UVChannel = 0) inline
Adds a new UV to the mesh with the given ID.
Definition at line 276 of file MeshDescription.h.
References UVElements.
CreateVertex()
FVertexID FMeshDescription::CreateVertex () inline
Adds a new vertex to the mesh and returns its ID.
Definition at line 204 of file MeshDescription.h.
References VertexElements.
CreateVertexInstance()
FVertexInstanceID FMeshDescription::CreateVertexInstance (const FVertexID VertexID) inline
Adds a new vertex instance to the mesh and returns its ID.
Definition at line 239 of file MeshDescription.h.
References CreateVertexInstance_Internal(), and VertexInstanceElements.
CreateVertexInstance_Internal()
MESHDESCRIPTION_API void FMeshDescription::CreateVertexInstance_Internal (const FVertexInstanceID VertexInstanceID, const FVertexID VertexID) private
Referenced by CreateVertexInstance(), and CreateVertexInstanceWithID().
CreateVertexInstanceWithID()
void FMeshDescription::CreateVertexInstanceWithID (const FVertexInstanceID VertexInstanceID, const FVertexID VertexID) inline
Adds a new vertex instance to the mesh with the given ID.
Definition at line 247 of file MeshDescription.h.
References CreateVertexInstance_Internal(), and VertexInstanceElements.
CreateVertexWithID()
void FMeshDescription::CreateVertexWithID (const FVertexID VertexID) inline
Adds a new vertex to the mesh with the given ID.
Definition at line 211 of file MeshDescription.h.
References VertexElements.
DeleteEdge()
MESHDESCRIPTION_API void FMeshDescription::DeleteEdge (const FEdgeID EdgeID, TArray< FVertexID > * InOutOrphanedVerticesPtr = nullptr)
Deletes an edge from the mesh.
DeleteEdge_Internal()
template<template< typename... > class TContainer> void FMeshDescription::DeleteEdge_Internal (const FEdgeID EdgeID, TContainer< FVertexID > * InOutOrphanedVerticesPtr = nullptr) private
DeletePolygon()
MESHDESCRIPTION_API void FMeshDescription::DeletePolygon (const FPolygonID PolygonID, TArray< FEdgeID > * InOutOrphanedEdgesPtr = nullptr, TArray< FVertexInstanceID > * InOutOrphanedVertexInstancesPtr = nullptr, TArray< FPolygonGroupID > * InOutOrphanedPolygonGroupsPtr = nullptr)
Deletes a polygon from the mesh.
DeletePolygon_Internal()
template<template< typename... > class TContainer> void FMeshDescription::DeletePolygon_Internal (const FPolygonID PolygonID, TContainer< FEdgeID > * InOutOrphanedEdgesPtr = nullptr, TContainer< FVertexInstanceID > * InOutOrphanedVertexInstancesPtr = nullptr, TContainer< FPolygonGroupID > * InOutOrphanedPolygonGroupsPtr = nullptr) private
DeletePolygonGroup()
void FMeshDescription::DeletePolygonGroup (const FPolygonGroupID PolygonGroupID) inline
Deletes a polygon group from the mesh.
Definition at line 415 of file MeshDescription.h.
References check, PolygonGroupElements, PolygonGroupToPolygons, and PolygonGroupToTriangles.
DeletePolygons()
MESHDESCRIPTION_API void FMeshDescription::DeletePolygons (const TArray< FPolygonID > & Polygons)
Deletes polygons from the mesh and remove all orphaned polygon groups, vertex instances, edges and vertices.
Will not compact the internal arrays, you must call Compact() manually.
References Polygons().
DeleteTriangle()
MESHDESCRIPTION_API void FMeshDescription::DeleteTriangle (const FTriangleID TriangleID, TArray< FEdgeID > * InOutOrphanedEdgesPtr = nullptr, TArray< FVertexInstanceID > * InOutOrphanedVertexInstancesPtr = nullptr, TArray< FPolygonGroupID > * InOutOrphanedPolygonGroupsPtr = nullptr)
Deletes a triangle from the mesh.
DeleteTriangle_Internal()
template<template< typename... > class TContainer> void FMeshDescription::DeleteTriangle_Internal (const FTriangleID TriangleID, TContainer< FEdgeID > * InOutOrphanedEdgesPtr = nullptr, TContainer< FVertexInstanceID > * InOutOrphanedVertexInstancesPtr = nullptr, TContainer< FPolygonGroupID > * InOutOrphanedPolygonGroupsPtr = nullptr) private
DeleteTriangles()
MESHDESCRIPTION_API void FMeshDescription::DeleteTriangles (const TArray< FTriangleID > & Triangles)
Deletes triangles from the mesh and remove all orphaned polygon groups, vertex instances, edges and vertices.
Will not compact the internal arrays, you must call Compact() manually.
References Triangles().
DeleteUV()
void FMeshDescription::DeleteUV (const FUVID UVID, const int32 UVChannel = 0) inline
Deletes a UV from the mesh.
Definition at line 282 of file MeshDescription.h.
References check, UVElements, and UVToTriangles.
DeleteVertex()
void FMeshDescription::DeleteVertex (const FVertexID VertexID) inline
Deletes a vertex from the mesh.
Definition at line 217 of file MeshDescription.h.
References check, VertexElements, VertexToEdges, and VertexToVertexInstances.
DeleteVertexInstance()
MESHDESCRIPTION_API void FMeshDescription::DeleteVertexInstance (const FVertexInstanceID VertexInstanceID, TArray< FVertexID > * InOutOrphanedVerticesPtr = nullptr)
Deletes a vertex instance from a mesh.
DeleteVertexInstance_Internal()
template<template< typename... > class TContainer> void FMeshDescription::DeleteVertexInstance_Internal (const FVertexInstanceID VertexInstanceID, TContainer< FVertexID > * InOutOrphanedVerticesPtr = nullptr) private
EdgeAttributes() [1/2]
TAttributesSet< FEdgeID > & FMeshDescription::EdgeAttributes () inline
Definition at line 156 of file MeshDescription.h.
References Edges(), and TMeshElementContainer< ElementIDType >::GetAttributes().
EdgeAttributes() [2/2]
const TAttributesSet< FEdgeID > & FMeshDescription::EdgeAttributes () const inline
Definition at line 157 of file MeshDescription.h.
References Edges(), and TMeshElementContainer< ElementIDType >::GetAttributes().
Edges() [1/2]
FEdgeArray & FMeshDescription::Edges () inline
Definition at line 135 of file MeshDescription.h.
References EdgeElements.
Referenced by EdgeAttributes(), EdgeAttributes(), and FindPolygonPerimeter().
Edges() [2/2]
const FEdgeArray & FMeshDescription::Edges () const inline
Definition at line 136 of file MeshDescription.h.
References EdgeElements.
Empty()
MESHDESCRIPTION_API void FMeshDescription::Empty ()
FindPolygonPerimeter() [1/2]
MESHDESCRIPTION_API void FMeshDescription::FindPolygonPerimeter (const FPolygonID PolygonID, TArrayView< FEdgeID > Edges) const
References Edges().
FindPolygonPerimeter() [2/2]
MESHDESCRIPTION_API void FMeshDescription::FindPolygonPerimeter (TArrayView< const FTriangleID > Triangles, TArrayView< TTuple< int32, int32 > > Result) const
Determines the vertex instances which form the perimeter of a polygon.
References Triangles().
Referenced by GetPolygonPerimeterEdges(), GetPolygonVertexInstances(), and GetPolygonVertices().
FixUpElementIDs()
MESHDESCRIPTION_API void FMeshDescription::FixUpElementIDs (const FElementIDRemappings & Remappings) private
Given a set of index remappings, fixes up references to element IDs.
for() [1/2]
FMeshDescription::for () inline
Definition at line 796 of file MeshDescription.h.
References TriVerts.
for() [2/2]
FMeshDescription::for () inline
Definition at line 814 of file MeshDescription.h.
References TriEdges.
GetBounds()
MESHDESCRIPTION_API FBoxSphereBounds FMeshDescription::GetBounds () const
Returns bounds of vertices.
GetEdgeConnectedPolygons() [1/3]
template<typename Alloc> TArray< FPolygonID, Alloc > FMeshDescription::GetEdgeConnectedPolygons (const FEdgeID EdgeID) const inline
Returns the polygons connected to this edge as an array with the specified allocator template type.
Definition at line 719 of file MeshDescription.h.
References GetEdgeConnectedPolygons().
GetEdgeConnectedPolygons() [2/3]
TArray< FPolygonID > FMeshDescription::GetEdgeConnectedPolygons (const FEdgeID EdgeID) const inline
Returns the polygons connected to this edge.
Definition at line 727 of file MeshDescription.h.
References GetEdgeConnectedPolygons().
GetEdgeConnectedPolygons() [3/3]
template<typename Alloc> void FMeshDescription::GetEdgeConnectedPolygons (const FEdgeID EdgeID, TArray< FPolygonID, Alloc > & OutPolygonIDs) const inline
Populates the passed array with polygon IDs connected to this edge.
Definition at line 708 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), EdgeToTriangles, TArray< InElementType, InAllocatorType >::Reset(), and TrianglePolygons.
Referenced by GetEdgeConnectedPolygons(), GetNumEdgeConnectedPolygons(), and GetPolygonAdjacentPolygons().
GetEdgeConnectedTriangleIDs()
TArrayView< const FTriangleID > FMeshDescription::GetEdgeConnectedTriangleIDs (const FEdgeID EdgeID) const inline
Returns reference to an array of triangle IDs connected to this edge.
Definition at line 690 of file MeshDescription.h.
References EdgeToTriangles.
Referenced by UE_DEPRECATED().
GetEdgeVertex()
FVertexID FMeshDescription::GetEdgeVertex (const FEdgeID EdgeID, int32 VertexNumber) const inline
Returns the vertex ID corresponding to one of the edge endpoints.
Definition at line 741 of file MeshDescription.h.
References check, and EdgeVertices.
GetEdgeVertices()
TArrayView< const FVertexID > FMeshDescription::GetEdgeVertices (const FEdgeID EdgeID) const inline
Returns a pair of vertex IDs defining the edge.
Definition at line 749 of file MeshDescription.h.
References EdgeVertices.
GetElements() [1/2]
TMap< FName, FMeshElementTypeWrapper > & FMeshDescription::GetElements () inline
Definition at line 171 of file MeshDescription.h.
References Elements.
GetElements() [2/2]
const TMap< FName, FMeshElementTypeWrapper > & FMeshDescription::GetElements () const inline
Definition at line 172 of file MeshDescription.h.
References Elements.
GetNumEdgeConnectedPolygons()
int32 FMeshDescription::GetNumEdgeConnectedPolygons (const FEdgeID EdgeID) const inline
Returns the number of polygons connected to this edge.
Definition at line 735 of file MeshDescription.h.
References GetEdgeConnectedPolygons(), and Num.
GetNumEdgeConnectedTriangles()
int32 FMeshDescription::GetNumEdgeConnectedTriangles (const FEdgeID EdgeID) const inline
Definition at line 701 of file MeshDescription.h.
References EdgeToTriangles.
GetNumPolygonGroupPolygons()
int32 FMeshDescription::GetNumPolygonGroupPolygons (const FPolygonGroupID PolygonGroupID) const inline
Returns the number of polygons in this polygon group.
Definition at line 1186 of file MeshDescription.h.
References PolygonGroupToPolygons.
GetNumPolygonGroupTriangles()
int32 FMeshDescription::GetNumPolygonGroupTriangles (const FPolygonGroupID PolygonGroupID) const inline
Returns the number of triangles in this polygon group.
Definition at line 1192 of file MeshDescription.h.
References PolygonGroupToTriangles.
GetNumPolygonInternalEdges()
int32 FMeshDescription::GetNumPolygonInternalEdges (const FPolygonID PolygonID) const inline
Return the number of internal edges in this polygon.
Definition at line 1072 of file MeshDescription.h.
References PolygonToTriangles.
GetNumPolygonTriangles()
int32 FMeshDescription::GetNumPolygonTriangles (const FPolygonID PolygonID) const inline
Return the number of triangles which comprise this polygon.
Definition at line 899 of file MeshDescription.h.
References PolygonToTriangles.
GetNumPolygonVertices()
int32 FMeshDescription::GetNumPolygonVertices (const FPolygonID PolygonID) const inline
Returns the number of vertices this polygon has.
Definition at line 944 of file MeshDescription.h.
References TArrayView< InElementType, InSizeType >::Num(), and PolygonToTriangles.
Referenced by GetPolygonInternalEdges(), GetPolygonPerimeterEdges(), GetPolygonVertexInstances(), and GetPolygonVertices().
GetNumUVElementChannels()
int32 FMeshDescription::GetNumUVElementChannels () const inline
Gets the number of UV element channels.
Definition at line 1216 of file MeshDescription.h.
References UVElements.
GetNumVertexConnectedEdges()
int32 FMeshDescription::GetNumVertexConnectedEdges (const FVertexID VertexID) const inline
Returns number of edges connected to this vertex.
Definition at line 457 of file MeshDescription.h.
References VertexToEdges.
GetNumVertexConnectedPolygons()
int32 FMeshDescription::GetNumVertexConnectedPolygons (const FVertexID VertexID) const inline
Returns the number of polygons connected to this vertex.
Definition at line 550 of file MeshDescription.h.
References GetVertexConnectedPolygons(), and Num.
GetNumVertexConnectedTriangles()
int32 FMeshDescription::GetNumVertexConnectedTriangles (const FVertexID VertexID) const inline
Returns number of triangles connected to this vertex.
Definition at line 510 of file MeshDescription.h.
References ID, Algo::TransformAccumulate(), VertexInstances(), VertexInstanceToTriangles, and VertexToVertexInstances.
Referenced by GetVertexConnectedTriangles().
GetNumVertexInstanceConnectedPolygons()
int32 FMeshDescription::GetNumVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const inline
Returns the number of polygons connected to this vertex instance.
Definition at line 663 of file MeshDescription.h.
References GetVertexInstanceConnectedPolygons(), and Num.
GetNumVertexInstanceConnectedTriangles()
int32 FMeshDescription::GetNumVertexInstanceConnectedTriangles (const FVertexInstanceID VertexInstanceID) const inline
Returns the number of triangles connected to this vertex instance.
Definition at line 629 of file MeshDescription.h.
References VertexInstanceToTriangles.
GetNumVertexVertexInstances()
int32 FMeshDescription::GetNumVertexVertexInstances (const FVertexID VertexID) const inline
Returns number of vertex instances created from this vertex.
Definition at line 475 of file MeshDescription.h.
References VertexToVertexInstances.
GetPolygonAdjacentPolygons() [1/3]
template<typename Alloc> TArray< FPolygonID, Alloc > FMeshDescription::GetPolygonAdjacentPolygons (const FPolygonID PolygonID) const inline
Return adjacent polygons into a TArray with the specified allocator.
Definition at line 1096 of file MeshDescription.h.
References GetPolygonAdjacentPolygons().
GetPolygonAdjacentPolygons() [2/3]
TArray< FPolygonID > FMeshDescription::GetPolygonAdjacentPolygons (const FPolygonID PolygonID) const inline
Return adjacent polygons to this polygon.
Definition at line 1104 of file MeshDescription.h.
References GetPolygonAdjacentPolygons().
GetPolygonAdjacentPolygons() [3/3]
template<typename Alloc> void FMeshDescription::GetPolygonAdjacentPolygons (const FPolygonID PolygonID, TArray< FPolygonID, Alloc > & OutPolygonIDs) const inline
Populates the passed array with adjacent polygons.
Definition at line 1079 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::Add(), GetEdgeConnectedPolygons(), GetPolygonPerimeterEdges(), and TArray< InElementType, InAllocatorType >::Reset().
Referenced by GetPolygonAdjacentPolygons().
GetPolygonCornerAngleForVertex()
MESHDESCRIPTION_API float FMeshDescription::GetPolygonCornerAngleForVertex (const FPolygonID PolygonID, const FVertexID VertexID) const
GetPolygonGroupPolygonIDs()
TArrayView< const FPolygonID > FMeshDescription::GetPolygonGroupPolygonIDs (const FPolygonGroupID PolygonGroupID) const inline
Returns the polygons associated with the given polygon group.
Definition at line 1168 of file MeshDescription.h.
References PolygonGroupToPolygons.
Referenced by UE_DEPRECATED().
GetPolygonGroupTriangles()
TArrayView< const FTriangleID > FMeshDescription::GetPolygonGroupTriangles (const FPolygonGroupID PolygonGroupID) const inline
Returns the triangles associated with the given polygon group.
Definition at line 1180 of file MeshDescription.h.
References PolygonGroupToTriangles.
GetPolygonInternalEdges() [1/3]
template<typename Alloc> TArray< FEdgeID, Alloc > FMeshDescription::GetPolygonInternalEdges (const FPolygonID PolygonID) const inline
Return the internal edges of this polygon, i.e.
those which separate constituent triangles
Definition at line 1056 of file MeshDescription.h.
References GetPolygonInternalEdges().
GetPolygonInternalEdges() [2/3]
TArray< FEdgeID > FMeshDescription::GetPolygonInternalEdges (const FPolygonID PolygonID) const inline
Return the internal edges of this polygon, i.e.
those which separate constituent triangles
Definition at line 1064 of file MeshDescription.h.
References GetPolygonInternalEdges().
GetPolygonInternalEdges() [3/3]
template<typename Alloc> void FMeshDescription::GetPolygonInternalEdges (const FPolygonID PolygonID, TArray< FEdgeID, Alloc > & OutEdgeIDs) const inline
Populate the provided array with a list of edges which are internal to the polygon, i.e.
those which separate constituent triangles.
Definition at line 1035 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Contains(), GetNumPolygonVertices(), GetPolygonVertexInstances(), GetVertexConnectedEdgeIDs(), GetVertexInstanceVertex(), IsEdgeInternalToPolygon(), and TArray< InElementType, InAllocatorType >::Reset().
Referenced by GetPolygonInternalEdges().
GetPolygonPerimeterEdges() [1/3]
template<typename Alloc> TArray< FEdgeID, Alloc > FMeshDescription::GetPolygonPerimeterEdges (const FPolygonID PolygonID) const inline
Returns the vertices which form the polygon perimeter as an array templated on the given allocator.
Definition at line 1017 of file MeshDescription.h.
References GetPolygonPerimeterEdges().
GetPolygonPerimeterEdges() [2/3]
TArray< FEdgeID > FMeshDescription::GetPolygonPerimeterEdges (const FPolygonID PolygonID) const inline
Returns the vertices which form the polygon perimeter.
Definition at line 1025 of file MeshDescription.h.
References GetPolygonPerimeterEdges().
GetPolygonPerimeterEdges() [3/3]
template<typename Alloc> void FMeshDescription::GetPolygonPerimeterEdges (const FPolygonID PolygonID, TArray< FEdgeID, Alloc > & OutEdgeIDs) const inline
Populates the passed array with the edges which form the polygon perimeter.
Definition at line 993 of file MeshDescription.h.
References FindPolygonPerimeter(), GetNumPolygonVertices(), TArrayView< InElementType, InSizeType >::Num(), PolygonToTriangles, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and TriangleEdges.
Referenced by GetPolygonAdjacentPolygons(), and GetPolygonPerimeterEdges().
GetPolygonPolygonGroup()
FPolygonGroupID FMeshDescription::GetPolygonPolygonGroup (const FPolygonID PolygonID) const inline
Return the polygon group associated with a polygon.
Definition at line 1112 of file MeshDescription.h.
References PolygonPolygonGroups.
GetPolygonTriangles()
TArrayView< const FTriangleID > FMeshDescription::GetPolygonTriangles (const FPolygonID PolygonID) const inline
Return reference to an array of triangle IDs which comprise this polygon.
Definition at line 887 of file MeshDescription.h.
References PolygonToTriangles.
Referenced by UE_DEPRECATED().
GetPolygonVertexInstances() [1/3]
template<typename Alloc> TArray< FVertexInstanceID, Alloc > FMeshDescription::GetPolygonVertexInstances (const FPolygonID PolygonID) const inline
Definition at line 929 of file MeshDescription.h.
References GetPolygonVertexInstances().
GetPolygonVertexInstances() [2/3]
TArray< FVertexInstanceID > FMeshDescription::GetPolygonVertexInstances (const FPolygonID PolygonID) const inline
Definition at line 936 of file MeshDescription.h.
References GetPolygonVertexInstances().
GetPolygonVertexInstances() [3/3]
template<typename Alloc> void FMeshDescription::GetPolygonVertexInstances (const FPolygonID PolygonID, TArray< FVertexInstanceID, Alloc > & OutVertexInstanceIDs) const inline
Returns reference to an array of VertexInstance IDs forming the perimeter of this polygon.
Definition at line 906 of file MeshDescription.h.
References FindPolygonPerimeter(), GetNumPolygonVertices(), TArrayView< InElementType, InSizeType >::Num(), PolygonToTriangles, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and TriangleVertexInstances.
Referenced by GetPolygonInternalEdges(), GetPolygonVertexInstances(), and GetVertexInstanceForPolygonVertex().
GetPolygonVertices() [1/3]
template<typename Alloc> TArray< FVertexID, Alloc > FMeshDescription::GetPolygonVertices (const FPolygonID PolygonID) const inline
Returns the vertices which form the polygon perimeter as an array templated on the given allocator.
Definition at line 976 of file MeshDescription.h.
References GetPolygonVertices().
GetPolygonVertices() [2/3]
TArray< FVertexID > FMeshDescription::GetPolygonVertices (const FPolygonID PolygonID) const inline
Returns the vertices which form the polygon perimeter.
Definition at line 984 of file MeshDescription.h.
References GetPolygonVertices().
GetPolygonVertices() [3/3]
template<typename Alloc> void FMeshDescription::GetPolygonVertices (const FPolygonID PolygonID, TArray< FVertexID, Alloc > & OutVertexIDs) const inline
Populates the passed array of VertexIDs with the vertices which form the polygon perimeter.
Definition at line 952 of file MeshDescription.h.
References FindPolygonPerimeter(), GetNumPolygonVertices(), TArrayView< InElementType, InSizeType >::Num(), PolygonToTriangles, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and TriangleVertices.
Referenced by GetPolygonVertices().
GetTriangleAdjacentTriangles() [1/3]
template<typename Alloc> TArray< FTriangleID, Alloc > FMeshDescription::GetTriangleAdjacentTriangles (const FTriangleID TriangleID) const inline
Return adjacent triangles into a TArray with the specified allocator.
Definition at line 846 of file MeshDescription.h.
References GetTriangleAdjacentTriangles().
GetTriangleAdjacentTriangles() [2/3]
TArray< FTriangleID > FMeshDescription::GetTriangleAdjacentTriangles (const FTriangleID TriangleID) const inline
Return adjacent triangles to this triangle.
Definition at line 854 of file MeshDescription.h.
References GetTriangleAdjacentTriangles().
GetTriangleAdjacentTriangles() [3/3]
template<typename Alloc> void FMeshDescription::GetTriangleAdjacentTriangles (const FTriangleID TriangleID, TArray< FTriangleID, Alloc > & OutTriangleIDs) const inline
Populates the passed array with adjacent triangles.
Definition at line 828 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::Add(), EdgeToTriangles, GetTriangleEdges(), and TArray< InElementType, InAllocatorType >::Reset().
Referenced by GetTriangleAdjacentTriangles().
GetTriangleCornerAngleForVertex()
MESHDESCRIPTION_API float FMeshDescription::GetTriangleCornerAngleForVertex (const FTriangleID TriangleID, const FVertexID VertexID) const
GetTriangleEdges()
TArrayView< FEdgeID > FMeshDescription::GetTriangleEdges (const FTriangleID TriangleID) const inline
Return the edges which form this triangle.
Definition at line 821 of file MeshDescription.h.
References TriangleEdges.
Referenced by GetTriangleAdjacentTriangles().
GetTrianglePolygon()
FPolygonID FMeshDescription::GetTrianglePolygon (const FTriangleID TriangleID) const inline
Get the polygon which contains this triangle.
Definition at line 759 of file MeshDescription.h.
References TrianglePolygons.
GetTrianglePolygonGroup()
FPolygonGroupID FMeshDescription::GetTrianglePolygonGroup (const FTriangleID TriangleID) const inline
Get the polygon group which contains this triangle.
Definition at line 765 of file MeshDescription.h.
References TrianglePolygonGroups.
GetTriangleUVIndices()
TArrayView< FUVID > FMeshDescription::GetTriangleUVIndices (const FTriangleID TriangleID, int32 UVChannel = 0) const inline
Return UV indices for this triangle for the given channel.
Definition at line 862 of file MeshDescription.h.
References TriangleUVs.
GetTriangleVertexInstance()
FVertexInstanceID FMeshDescription::GetTriangleVertexInstance (const FTriangleID TriangleID, const int32 Index) const inline
Get the specified vertex instance by index.
Definition at line 783 of file MeshDescription.h.
References check, and TriangleVertexInstances.
GetTriangleVertexInstances()
TArrayView< const FVertexInstanceID > FMeshDescription::GetTriangleVertexInstances (const FTriangleID TriangleID) const inline
Get the vertex instances which define this triangle.
Definition at line 777 of file MeshDescription.h.
References TriangleVertexInstances.
Referenced by GetVertexInstanceForTriangleVertex().
GetTriangleVertices()
TArrayView< const FVertexID > FMeshDescription::GetTriangleVertices (const FTriangleID TriangleID) const inline
Return the vertices which define this triangle.
Definition at line 803 of file MeshDescription.h.
References TriangleVertices.
GetVertexAdjacentVertices() [1/3]
template<typename Alloc> TArray< FVertexID, Alloc > FMeshDescription::GetVertexAdjacentVertices (const FVertexID VertexID) const inline
Returns the vertices adjacent to this vertex as an array with the specified allocator template type.
Definition at line 573 of file MeshDescription.h.
References GetVertexAdjacentVertices().
GetVertexAdjacentVertices() [2/3]
TArray< FVertexID > FMeshDescription::GetVertexAdjacentVertices (const FVertexID VertexID) const inline
Returns the vertices adjacent to this vertex.
Definition at line 581 of file MeshDescription.h.
References GetVertexAdjacentVertices().
GetVertexAdjacentVertices() [3/3]
template<typename Alloc> void FMeshDescription::GetVertexAdjacentVertices (const FVertexID VertexID, TArray< FVertexID, Alloc > & OutAdjacentVertexIDs) const inline
Populates the passed array of VertexIDs with the vertices adjacent to this vertex.
Definition at line 557 of file MeshDescription.h.
References EdgeVertices, TArrayView< InElementType, InSizeType >::Num(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and VertexToEdges.
Referenced by GetVertexAdjacentVertices().
GetVertexConnectedEdgeIDs()
TArrayView< const FEdgeID > FMeshDescription::GetVertexConnectedEdgeIDs (const FVertexID VertexID) const inline
Returns reference to an array of Edge IDs connected to this vertex.
Definition at line 445 of file MeshDescription.h.
References VertexToEdges.
Referenced by GetPolygonInternalEdges(), and UE_DEPRECATED().
GetVertexConnectedPolygons() [1/3]
template<typename Alloc> TArray< FPolygonID, Alloc > FMeshDescription::GetVertexConnectedPolygons (const FVertexID VertexID) const inline
Returns the polygons connected to this vertex as an array with the specified allocator template type.
Definition at line 534 of file MeshDescription.h.
References GetVertexConnectedPolygons().
GetVertexConnectedPolygons() [2/3]
TArray< FPolygonID > FMeshDescription::GetVertexConnectedPolygons (const FVertexID VertexID) const inline
Returns the polygons connected to this vertex.
Definition at line 542 of file MeshDescription.h.
References GetVertexConnectedPolygons().
GetVertexConnectedPolygons() [3/3]
template<typename Alloc> void FMeshDescription::GetVertexConnectedPolygons (const FVertexID VertexID, TArray< FPolygonID, Alloc > & OutConnectedPolygonIDs) const inline
Populates the passed array of PolygonIDs with the polygons connected to this vertex.
Definition at line 520 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), TArray< InElementType, InAllocatorType >::Reset(), TrianglePolygons, VertexInstanceToTriangles, and VertexToVertexInstances.
Referenced by GetNumVertexConnectedPolygons(), and GetVertexConnectedPolygons().
GetVertexConnectedTriangles() [1/3]
template<typename Alloc> TArray< FTriangleID, Alloc > FMeshDescription::GetVertexConnectedTriangles (const FVertexID VertexID) const inline
Returns the triangles connected to this vertex as an array with the specified allocator template type.
Definition at line 494 of file MeshDescription.h.
References GetVertexConnectedTriangles().
GetVertexConnectedTriangles() [2/3]
TArray< FTriangleID > FMeshDescription::GetVertexConnectedTriangles (const FVertexID VertexID) const inline
Returns the triangles connected to this vertex.
Definition at line 502 of file MeshDescription.h.
References GetVertexConnectedTriangles().
GetVertexConnectedTriangles() [3/3]
template<typename Alloc> void FMeshDescription::GetVertexConnectedTriangles (const FVertexID VertexID, TArray< FTriangleID, Alloc > & OutConnectedTriangleIDs) const inline
Populates the passed array of TriangleIDs with the triangles connected to this vertex.
Definition at line 482 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::Append(), TArrayView< InElementType, InSizeType >::GetData(), GetNumVertexConnectedTriangles(), TArrayView< InElementType, InSizeType >::Num(), TArray< InElementType, InAllocatorType >::Reset(), VertexInstanceToTriangles, and VertexToVertexInstances.
Referenced by GetVertexConnectedTriangles().
GetVertexInstanceConnectedPolygons() [1/3]
template<typename Alloc> TArray< FPolygonID, Alloc > FMeshDescription::GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const inline
Returns the polygons connected to this vertex instance as an array with the specified allocator template type.
Definition at line 647 of file MeshDescription.h.
References GetVertexInstanceConnectedPolygons().
GetVertexInstanceConnectedPolygons() [2/3]
TArray< FPolygonID > FMeshDescription::GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID) const inline
Returns the polygons connected to this vertex instance.
Definition at line 655 of file MeshDescription.h.
References GetVertexInstanceConnectedPolygons().
GetVertexInstanceConnectedPolygons() [3/3]
template<typename Alloc> void FMeshDescription::GetVertexInstanceConnectedPolygons (const FVertexInstanceID VertexInstanceID, TArray< FPolygonID, Alloc > & OutPolygonIDs) const inline
Populates the passed array with the polygons connected to this vertex instance.
Definition at line 636 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), TArray< InElementType, InAllocatorType >::Reset(), TrianglePolygons, and VertexInstanceToTriangles.
Referenced by GetNumVertexInstanceConnectedPolygons(), and GetVertexInstanceConnectedPolygons().
GetVertexInstanceConnectedTriangleIDs()
TArrayView< const FTriangleID > FMeshDescription::GetVertexInstanceConnectedTriangleIDs (const FVertexInstanceID VertexInstanceID) const inline
Returns reference to an array of Triangle IDs connected to this vertex instance.
Definition at line 617 of file MeshDescription.h.
References VertexInstanceToTriangles.
Referenced by UE_DEPRECATED().
GetVertexInstanceForPolygonVertex()
FVertexInstanceID FMeshDescription::GetVertexInstanceForPolygonVertex (const FPolygonID PolygonID, const FVertexID VertexID) const inline
Return the vertex instance which corresponds to the given vertex on the given polygon, or INDEX_NONE.
Definition at line 1118 of file MeshDescription.h.
References TArray< InElementType, InAllocatorType >::FindByPredicate(), GetPolygonVertexInstances(), GetVertexInstanceVertex(), and INDEX_NONE.
GetVertexInstanceForTriangleVertex()
FVertexInstanceID FMeshDescription::GetVertexInstanceForTriangleVertex (const FTriangleID TriangleID, const FVertexID VertexID) const inline
Return the vertex instance which corresponds to the given vertex on the given triangle, or INDEX_NONE.
Definition at line 868 of file MeshDescription.h.
References Algo::FindByPredicate(), GetTriangleVertexInstances(), GetVertexInstanceVertex(), and INDEX_NONE.
GetVertexInstancePairEdge()
MESHDESCRIPTION_API FEdgeID FMeshDescription::GetVertexInstancePairEdge (const FVertexInstanceID VertexInstanceID0, const FVertexInstanceID VertexInstanceID1) const
Returns the edge ID defined by the two given vertex instance IDs, if there is one; otherwise INDEX_NONE.
GetVertexInstanceVertex()
FVertexID FMeshDescription::GetVertexInstanceVertex (const FVertexInstanceID VertexInstanceID) const inline
Returns the vertex ID associated with the given vertex instance.
Definition at line 608 of file MeshDescription.h.
References VertexInstanceVertices.
Referenced by GetPolygonInternalEdges(), GetVertexInstanceForPolygonVertex(), and GetVertexInstanceForTriangleVertex().
GetVertexPairEdge()
MESHDESCRIPTION_API FEdgeID FMeshDescription::GetVertexPairEdge (const FVertexID VertexID0, const FVertexID VertexID1) const
Returns the edge ID defined by the two given vertex IDs, if there is one; otherwise INDEX_NONE.
GetVertexPosition()
FVector3f FMeshDescription::GetVertexPosition (const FVertexID VertexID) const inline
Returns the position of this vertex.
Definition at line 589 of file MeshDescription.h.
References VertexPositions.
GetVertexPositions() [1/2]
TVertexAttributesRef< FVector3f > FMeshDescription::GetVertexPositions () inline
Definition at line 594 of file MeshDescription.h.
References VertexPositions.
GetVertexPositions() [2/2]
TVertexAttributesRef< const FVector3f > FMeshDescription::GetVertexPositions () const inline
Definition at line 599 of file MeshDescription.h.
References VertexPositions.
GetVertexVertexInstanceIDs()
TArrayView< const FVertexInstanceID > FMeshDescription::GetVertexVertexInstanceIDs (const FVertexID VertexID) const inline
Returns reference to an array of VertexInstance IDs instanced from this vertex.
Definition at line 463 of file MeshDescription.h.
References VertexToVertexInstances.
Referenced by UE_DEPRECATED().
Initialize()
MESHDESCRIPTION_API void FMeshDescription::Initialize () private
InitializeIndexers()
MESHDESCRIPTION_API void FMeshDescription::InitializeIndexers () private
IsEdgeInternal()
bool FMeshDescription::IsEdgeInternal (const FEdgeID EdgeID) const inline
Determine whether a given edge is an internal edge between triangles of a polygon.
Definition at line 673 of file MeshDescription.h.
References EdgeToTriangles, TArrayView< InElementType, InSizeType >::Num(), and TrianglePolygons.
IsEdgeInternalToPolygon()
bool FMeshDescription::IsEdgeInternalToPolygon (const FEdgeID EdgeID, const FPolygonID PolygonID) const inline
Determine whether a given edge is an internal edge between triangles of a specific polygon.
Definition at line 681 of file MeshDescription.h.
References EdgeToTriangles, TArrayView< InElementType, InSizeType >::Num(), and TrianglePolygons.
Referenced by GetPolygonInternalEdges().
IsEdgeValid()
bool FMeshDescription::IsEdgeValid (const FEdgeID EdgeID) const inline
Returns whether the passed edge ID is valid.
Definition at line 320 of file MeshDescription.h.
References EdgeElements.
IsEmpty()
MESHDESCRIPTION_API bool FMeshDescription::IsEmpty () const
IsPolygonGroupValid()
bool FMeshDescription::IsPolygonGroupValid (const FPolygonGroupID PolygonGroupID) const inline
Returns whether the passed polygon group ID is valid.
Definition at line 424 of file MeshDescription.h.
References PolygonGroupElements.
IsPolygonValid()
bool FMeshDescription::IsPolygonValid (const FPolygonID PolygonID) const inline
Returns whether the passed polygon ID is valid.
Definition at line 390 of file MeshDescription.h.
References PolygonElements.
IsTrianglePartOfNgon()
bool FMeshDescription::IsTrianglePartOfNgon (const FTriangleID TriangleID) const inline
Determines if this triangle is part of an n-gon.
Definition at line 771 of file MeshDescription.h.
References PolygonToTriangles, and TrianglePolygons.
IsTriangleValid()
bool FMeshDescription::IsTriangleValid (const FTriangleID TriangleID) const inline
Returns whether the passed triangle ID is valid.
Definition at line 355 of file MeshDescription.h.
References TriangleElements.
IsUVValid()
bool FMeshDescription::IsUVValid (const FUVID UVID, const int32 UVChannel = 0) const inline
Returns whether the passed UV ID is valid.
Definition at line 290 of file MeshDescription.h.
References UVElements.
IsVertexInstanceValid()
bool FMeshDescription::IsVertexInstanceValid (const FVertexInstanceID VertexInstanceID) const inline
Returns whether the passed vertex instance ID is valid.
Definition at line 257 of file MeshDescription.h.
References VertexInstanceElements.
IsVertexOrphaned()
MESHDESCRIPTION_API bool FMeshDescription::IsVertexOrphaned (const FVertexID VertexID) const
Returns whether a given vertex is orphaned, i.e.
it doesn't form part of any polygon
IsVertexValid()
bool FMeshDescription::IsVertexValid (const FVertexID VertexID) const inline
Returns whether the passed vertex ID is valid.
Definition at line 227 of file MeshDescription.h.
References VertexElements.
NeedsCompact()
MESHDESCRIPTION_API bool FMeshDescription::NeedsCompact () const
Determines if calling Compact() would perform actual compaction or not.
operator=() [1/2]
MESHDESCRIPTION_API FMeshDescription & FMeshDescription::operator= (const FMeshDescription &)
References FMeshDescription().
operator=() [2/2]
FMeshDescription & FMeshDescription::operator= (FMeshDescription &&) default
References FMeshDescription().
PolygonAttributes() [1/2]
TAttributesSet< FPolygonID > & FMeshDescription::PolygonAttributes () inline
Definition at line 165 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Polygons().
PolygonAttributes() [2/2]
const TAttributesSet< FPolygonID > & FMeshDescription::PolygonAttributes () const inline
Definition at line 166 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Polygons().
PolygonGroupAttributes() [1/2]
TAttributesSet< FPolygonGroupID > & FMeshDescription::PolygonGroupAttributes () inline
Definition at line 168 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and PolygonGroups().
PolygonGroupAttributes() [2/2]
const TAttributesSet< FPolygonGroupID > & FMeshDescription::PolygonGroupAttributes () const inline
Definition at line 169 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and PolygonGroups().
PolygonGroups() [1/2]
FPolygonGroupArray & FMeshDescription::PolygonGroups () inline
Definition at line 147 of file MeshDescription.h.
References PolygonGroupElements.
Referenced by PolygonGroupAttributes(), and PolygonGroupAttributes().
PolygonGroups() [2/2]
const FPolygonGroupArray & FMeshDescription::PolygonGroups () const inline
Definition at line 148 of file MeshDescription.h.
References PolygonGroupElements.
Polygons() [1/2]
FPolygonArray & FMeshDescription::Polygons () inline
Definition at line 144 of file MeshDescription.h.
References PolygonElements.
Referenced by DeletePolygons(), PolygonAttributes(), and PolygonAttributes().
Polygons() [2/2]
const FPolygonArray & FMeshDescription::Polygons () const inline
Definition at line 145 of file MeshDescription.h.
References PolygonElements.
RebuildIndexers()
MESHDESCRIPTION_API void FMeshDescription::RebuildIndexers ()
Remap()
MESHDESCRIPTION_API void FMeshDescription::Remap (const FElementIDRemappings & Remappings)
Remaps the element IDs in the mesh description according to the passed in object.
Referenced by RemapPolygonGroups().
RemapPolygonGroups()
MESHDESCRIPTION_API void FMeshDescription::RemapPolygonGroups (const TMap< FPolygonGroupID, FPolygonGroupID > & Remap)
Remaps polygon groups according to the supplied map.
References Remap().
RemovePolygonTriangles()
MESHDESCRIPTION_API void FMeshDescription::RemovePolygonTriangles (const FPolygonID PolygonID) private
ReserveNewEdges()
void FMeshDescription::ReserveNewEdges (const int32 NumEdges) inline
Reserves space for this number of new edges.
Definition at line 296 of file MeshDescription.h.
References EdgeElements.
ReserveNewPolygonGroups()
void FMeshDescription::ReserveNewPolygonGroups (const int32 NumPolygonGroups) inline
Reserves space for this number of new polygon groups.
Definition at line 396 of file MeshDescription.h.
References PolygonGroupElements.
ReserveNewPolygons()
void FMeshDescription::ReserveNewPolygons (const int32 NumPolygons) inline
Reserves space for this number of new polygons.
Definition at line 361 of file MeshDescription.h.
References PolygonElements.
ReserveNewTriangles()
void FMeshDescription::ReserveNewTriangles (const int32 NumTriangles) inline
Reserves space for this number of new triangles.
Definition at line 326 of file MeshDescription.h.
References TriangleElements.
ReserveNewUVs()
void FMeshDescription::ReserveNewUVs (const int32 NumUVs, const int32 UVChannel = 0) inline
Reserves space for this number of new UVs.
Definition at line 263 of file MeshDescription.h.
References UVElements.
ReserveNewVertexInstances()
void FMeshDescription::ReserveNewVertexInstances (const int32 NumVertexInstances) inline
Reserves space for this number of new vertex instances.
Definition at line 233 of file MeshDescription.h.
References VertexInstanceElements.
ReserveNewVertices()
void FMeshDescription::ReserveNewVertices (const int32 NumVertices) inline
Reserves space for this number of new vertices.
Definition at line 198 of file MeshDescription.h.
References VertexElements.
ResetIndexers()
MESHDESCRIPTION_API void FMeshDescription::ResetIndexers ()
ResumeEdgeIndexing()
void FMeshDescription::ResumeEdgeIndexing () inline
Definition at line 183 of file MeshDescription.h.
References EdgeToTriangles.
ResumePolygonGroupIndexing()
void FMeshDescription::ResumePolygonGroupIndexing () inline
Definition at line 185 of file MeshDescription.h.
References PolygonGroupToPolygons, and PolygonGroupToTriangles.
ResumePolygonIndexing()
void FMeshDescription::ResumePolygonIndexing () inline
Definition at line 184 of file MeshDescription.h.
References PolygonToTriangles.
ResumeUVIndexing()
void FMeshDescription::ResumeUVIndexing () inline
Definition at line 186 of file MeshDescription.h.
References UVToTriangles.
ResumeVertexIndexing()
void FMeshDescription::ResumeVertexIndexing () inline
Definition at line 181 of file MeshDescription.h.
References VertexToEdges, and VertexToVertexInstances.
ResumeVertexInstanceIndexing()
void FMeshDescription::ResumeVertexInstanceIndexing () inline
Definition at line 182 of file MeshDescription.h.
References VertexInstanceToTriangles.
ReverseAllPolygonFacing()
MESHDESCRIPTION_API void FMeshDescription::ReverseAllPolygonFacing ()
Reverses the winding order of all polygons in the mesh.
ReversePolygonFacing()
MESHDESCRIPTION_API void FMeshDescription::ReversePolygonFacing (const FPolygonID PolygonID)
Reverse the winding order of the vertices of this polygon.
ReverseTriangleFacing()
MESHDESCRIPTION_API void FMeshDescription::ReverseTriangleFacing (const FTriangleID TriangleID)
Reverse the winding order of the vertices of this triangle.
Serialize()
MESHDESCRIPTION_API void FMeshDescription::Serialize (FArchive & Ar)
References Ar.
Referenced by operator<<.
SerializeLegacy()
MESHDESCRIPTION_API void FMeshDescription::SerializeLegacy (FArchive & Ar)
References Ar.
SetNumUVChannels()
MESHDESCRIPTION_API void FMeshDescription::SetNumUVChannels (const int32 NumUVChannels)
Sets the specified number of UV channels.
SetPolygonPolygonGroup()
void FMeshDescription::SetPolygonPolygonGroup (const FPolygonID PolygonID, const FPolygonGroupID PolygonGroupID) inline
Sets the polygon group associated with a polygon.
Definition at line 1132 of file MeshDescription.h.
References check, PolygonGroupToPolygons, PolygonGroupToTriangles, PolygonPolygonGroups, PolygonToTriangles, and TrianglePolygonGroups.
SetPolygonVertexInstance()
MESHDESCRIPTION_API void FMeshDescription::SetPolygonVertexInstance (const FPolygonID PolygonID, const int32 PerimeterIndex, const FVertexInstanceID VertexInstanceID)
Set the vertex instance at the given index around the polygon to the new value.
SetPolygonVertexInstances()
MESHDESCRIPTION_API void FMeshDescription::SetPolygonVertexInstances (const FPolygonID PolygonID, TArrayView< const FVertexInstanceID > VertexInstanceIDs)
SetTriangleUVIndices()
MESHDESCRIPTION_API void FMeshDescription::SetTriangleUVIndices (const FTriangleID TriangleID, TArrayView< const FUVID > UVIDs, int32 UVChannel = 0)
Set the UV indices for this triangle.
SplitPolygon()
MESHDESCRIPTION_API void FMeshDescription::SplitPolygon (FPolygonID PolygonID)
SuspendEdgeIndexing()
void FMeshDescription::SuspendEdgeIndexing () inline
Definition at line 176 of file MeshDescription.h.
References EdgeToTriangles.
SuspendPolygonGroupIndexing()
void FMeshDescription::SuspendPolygonGroupIndexing () inline
Definition at line 178 of file MeshDescription.h.
References PolygonGroupToPolygons, and PolygonGroupToTriangles.
SuspendPolygonIndexing()
void FMeshDescription::SuspendPolygonIndexing () inline
Definition at line 177 of file MeshDescription.h.
References PolygonToTriangles.
SuspendUVIndexing()
void FMeshDescription::SuspendUVIndexing () inline
Definition at line 179 of file MeshDescription.h.
References UVToTriangles.
SuspendVertexIndexing()
void FMeshDescription::SuspendVertexIndexing () inline
Definition at line 174 of file MeshDescription.h.
References VertexToEdges, and VertexToVertexInstances.
SuspendVertexInstanceIndexing()
void FMeshDescription::SuspendVertexInstanceIndexing () inline
Definition at line 175 of file MeshDescription.h.
References VertexInstanceToTriangles.
TransferPolygonGroup()
MESHDESCRIPTION_API void FMeshDescription::TransferPolygonGroup (FPolygonGroupID SourceID, FPolygonGroupID DestinationID)
Transfer the source polygon group data to the destination polygon group.
The source data is append to the destination
TriangleAttributes() [1/2]
TAttributesSet< FTriangleID > & FMeshDescription::TriangleAttributes () inline
Definition at line 162 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Triangles().
TriangleAttributes() [2/2]
const TAttributesSet< FTriangleID > & FMeshDescription::TriangleAttributes () const inline
Definition at line 163 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Triangles().
Triangles() [1/2]
FTriangleArray & FMeshDescription::Triangles () inline
Definition at line 141 of file MeshDescription.h.
References TriangleElements.
Referenced by DeleteTriangles(), FindPolygonPerimeter(), TriangleAttributes(), and TriangleAttributes().
Triangles() [2/2]
const FTriangleArray & FMeshDescription::Triangles () const inline
Definition at line 142 of file MeshDescription.h.
References TriangleElements.
TriangulateMesh()
MESHDESCRIPTION_API void FMeshDescription::TriangulateMesh ()
Retriangulates the entire mesh.
UE_DEPRECATED() [1/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetEdgeConnectedTriangleIDs() instead.") const inline
Definition at line 695 of file MeshDescription.h.
References const, and GetEdgeConnectedTriangleIDs().
UE_DEPRECATED() [2/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetPolygonGroupPolygonIDs() instead.") const inline
Definition at line 1173 of file MeshDescription.h.
References const, and GetPolygonGroupPolygonIDs().
UE_DEPRECATED() [3/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetPolygonTriangles() instead.") const inline
Definition at line 892 of file MeshDescription.h.
References const, and GetPolygonTriangles().
UE_DEPRECATED() [4/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetVertexConnectedEdgeIDs instead.") const inline
Definition at line 450 of file MeshDescription.h.
References const, and GetVertexConnectedEdgeIDs().
UE_DEPRECATED() [5/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetVertexInstanceTriangleIDs() instead.") const inline
Definition at line 622 of file MeshDescription.h.
References const, and GetVertexInstanceConnectedTriangleIDs().
UE_DEPRECATED() [6/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Please use GetVertexVertexInstanceIDs instead.") const inline
Definition at line 468 of file MeshDescription.h.
References const, and GetVertexVertexInstanceIDs().
UE_DEPRECATED() [7/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Use the other form of GetTriangleEdges") const
Populates the passed array with the edges which define this triangle.
UE_DEPRECATED() [8/8]
FMeshDescription::UE_DEPRECATED (4. 26, "Use the other form of GetTriangleVertices") const
Populates the passed array with the vertices which define this triangle.
UVAttributes() [1/2]
TAttributesSet< FUVID > & FMeshDescription::UVAttributes (int32 Index) inline
Definition at line 159 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and UVs().
UVAttributes() [2/2]
const TAttributesSet< FUVID > & FMeshDescription::UVAttributes (int32 Index) const inline
Definition at line 160 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and UVs().
UVs() [1/2]
FUVArray & FMeshDescription::UVs (int32 Index) inline
Definition at line 138 of file MeshDescription.h.
References UVElements.
Referenced by UVAttributes(), and UVAttributes().
UVs() [2/2]
const FUVArray & FMeshDescription::UVs (int32 Index) const inline
Definition at line 139 of file MeshDescription.h.
References UVElements.
VertexAttributes() [1/2]
TAttributesSet< FVertexID > & FMeshDescription::VertexAttributes () inline
Definition at line 150 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Vertices().
VertexAttributes() [2/2]
const TAttributesSet< FVertexID > & FMeshDescription::VertexAttributes () const inline
Definition at line 151 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and Vertices().
VertexInstanceAttributes() [1/2]
TAttributesSet< FVertexInstanceID > & FMeshDescription::VertexInstanceAttributes () inline
Definition at line 153 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and VertexInstances().
VertexInstanceAttributes() [2/2]
const TAttributesSet< FVertexInstanceID > & FMeshDescription::VertexInstanceAttributes () const inline
Definition at line 154 of file MeshDescription.h.
References TMeshElementContainer< ElementIDType >::GetAttributes(), and VertexInstances().
VertexInstances() [1/2]
FVertexInstanceArray & FMeshDescription::VertexInstances () inline
Definition at line 132 of file MeshDescription.h.
References VertexInstanceElements.
Referenced by GetNumVertexConnectedTriangles(), VertexInstanceAttributes(), and VertexInstanceAttributes().
VertexInstances() [2/2]
const FVertexInstanceArray & FMeshDescription::VertexInstances () const inline
Definition at line 133 of file MeshDescription.h.
References VertexInstanceElements.
Vertices() [1/2]
FVertexArray & FMeshDescription::Vertices () inline
Definition at line 129 of file MeshDescription.h.
References VertexElements.
Referenced by VertexAttributes(), and VertexAttributes().
Vertices() [2/2]
const FVertexArray & FMeshDescription::Vertices () const inline
Definition at line 130 of file MeshDescription.h.
References VertexElements.
Friends And Related Symbol Documentation
operator<<
MESHDESCRIPTION_API FArchive & operator<< (FArchive & Ar, FMeshDescription & MeshDescription) friend
Definition at line 106 of file MeshDescription.h.
References FMeshDescription(), Ar, and Serialize().
Field Documentation
const [1/2]
TArrayView<FVertexID> OutVertexIDs FMeshDescription::const
Initial value:
{
        check(OutVertexIDs.Num() >= 3)
Definition at line 792 of file MeshDescription.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
const [2/2]
TArrayView<FEdgeID> OutEdgeIDs FMeshDescription::const
Initial value:
{
        check(OutEdgeIDs.Num() >= 3)
Definition at line 810 of file MeshDescription.h.
EdgeElements
FMeshElementChannels* FMeshDescription::EdgeElements private
Definition at line 1292 of file MeshDescription.h.
Referenced by CreateEdge(), CreateEdgeWithID(), Edges(), Edges(), IsEdgeValid(), and ReserveNewEdges().
EdgesName
MESHDESCRIPTION_API FName FMeshDescription::EdgesName static
Definition at line 1281 of file MeshDescription.h.
EdgeToTriangles
FMeshElementIndexer FMeshDescription::EdgeToTriangles mutable private
Definition at line 1312 of file MeshDescription.h.
Referenced by BuildEdgeIndexers(), GetEdgeConnectedPolygons(), GetEdgeConnectedTriangleIDs(), GetNumEdgeConnectedTriangles(), GetTriangleAdjacentTriangles(), IsEdgeInternal(), IsEdgeInternalToPolygon(), ResumeEdgeIndexing(), and SuspendEdgeIndexing().
EdgeVertices
TMeshAttributesArray<TArrayView<FVertexID> > FMeshDescription::EdgeVertices private
Definition at line 1298 of file MeshDescription.h.
Referenced by GetEdgeVertex(), GetEdgeVertices(), and GetVertexAdjacentVertices().
Elements
TMap<FName, FMeshElementTypeWrapper> FMeshDescription::Elements private
Definition at line 1287 of file MeshDescription.h.
Referenced by GetElements(), and GetElements().
PolygonElements
FMeshElementChannels* FMeshDescription::PolygonElements private
Definition at line 1294 of file MeshDescription.h.
Referenced by CreatePolygon(), CreatePolygonWithID(), IsPolygonValid(), Polygons(), Polygons(), and ReserveNewPolygons().
PolygonGroupElements
FMeshElementChannels* FMeshDescription::PolygonGroupElements private
Definition at line 1295 of file MeshDescription.h.
Referenced by CreatePolygonGroup(), CreatePolygonGroupWithID(), DeletePolygonGroup(), IsPolygonGroupValid(), PolygonGroups(), PolygonGroups(), and ReserveNewPolygonGroups().
PolygonGroupsName
MESHDESCRIPTION_API FName FMeshDescription::PolygonGroupsName static
Definition at line 1284 of file MeshDescription.h.
PolygonGroupToPolygons
FMeshElementIndexer FMeshDescription::PolygonGroupToPolygons mutable private
Definition at line 1316 of file MeshDescription.h.
Referenced by BuildPolygonGroupIndexers(), DeletePolygonGroup(), GetNumPolygonGroupPolygons(), GetPolygonGroupPolygonIDs(), ResumePolygonGroupIndexing(), SetPolygonPolygonGroup(), and SuspendPolygonGroupIndexing().
PolygonGroupToTriangles
FMeshElementIndexer FMeshDescription::PolygonGroupToTriangles mutable private
Definition at line 1315 of file MeshDescription.h.
Referenced by BuildPolygonGroupIndexers(), DeletePolygonGroup(), GetNumPolygonGroupTriangles(), GetPolygonGroupTriangles(), ResumePolygonGroupIndexing(), SetPolygonPolygonGroup(), and SuspendPolygonGroupIndexing().
PolygonPolygonGroups
TMeshAttributesArray<FPolygonGroupID> FMeshDescription::PolygonPolygonGroups private
Definition at line 1305 of file MeshDescription.h.
Referenced by GetPolygonPolygonGroup(), and SetPolygonPolygonGroup().
PolygonsName
MESHDESCRIPTION_API FName FMeshDescription::PolygonsName static
Definition at line 1283 of file MeshDescription.h.
PolygonToTriangles
FMeshElementIndexer FMeshDescription::PolygonToTriangles mutable private
Definition at line 1314 of file MeshDescription.h.
Referenced by BuildPolygonIndexers(), GetNumPolygonInternalEdges(), GetNumPolygonTriangles(), GetNumPolygonVertices(), GetPolygonPerimeterEdges(), GetPolygonTriangles(), GetPolygonVertexInstances(), GetPolygonVertices(), IsTrianglePartOfNgon(), ResumePolygonIndexing(), SetPolygonPolygonGroup(), and SuspendPolygonIndexing().
TriangleEdges
TMeshAttributesArray<TArrayView<FEdgeID> > FMeshDescription::TriangleEdges private
Definition at line 1301 of file MeshDescription.h.
Referenced by GetPolygonPerimeterEdges(), and GetTriangleEdges().
TriangleElements
FMeshElementChannels* FMeshDescription::TriangleElements private
Definition at line 1293 of file MeshDescription.h.
Referenced by CreateTriangle(), CreateTriangleWithID(), IsTriangleValid(), ReserveNewTriangles(), Triangles(), and Triangles().
TrianglePolygonGroups
TMeshAttributesArray<FPolygonGroupID> FMeshDescription::TrianglePolygonGroups private
Definition at line 1304 of file MeshDescription.h.
Referenced by GetTrianglePolygonGroup(), and SetPolygonPolygonGroup().
TrianglePolygons
TMeshAttributesArray<FPolygonID> FMeshDescription::TrianglePolygons private
Definition at line 1300 of file MeshDescription.h.
Referenced by GetEdgeConnectedPolygons(), GetTrianglePolygon(), GetVertexConnectedPolygons(), GetVertexInstanceConnectedPolygons(), IsEdgeInternal(), IsEdgeInternalToPolygon(), and IsTrianglePartOfNgon().
TrianglesName
MESHDESCRIPTION_API FName FMeshDescription::TrianglesName static
Definition at line 1282 of file MeshDescription.h.
TriangleUVs
TMeshAttributesArray<TArrayView<FUVID> > FMeshDescription::TriangleUVs private
Definition at line 1303 of file MeshDescription.h.
Referenced by GetTriangleUVIndices().
TriangleVertexInstances
TMeshAttributesArray<TArrayView<FVertexInstanceID> > FMeshDescription::TriangleVertexInstances private
Definition at line 1299 of file MeshDescription.h.
Referenced by GetPolygonVertexInstances(), GetTriangleVertexInstance(), and GetTriangleVertexInstances().
TriangleVertices
TMeshAttributesArray<TArrayView<FVertexID> > FMeshDescription::TriangleVertices private
Definition at line 1302 of file MeshDescription.h.
Referenced by GetPolygonVertices(), and GetTriangleVertices().
TriEdges
TArrayView<const FEdgeID> FMeshDescription::TriEdges = TriangleEdges[TriangleID]
Definition at line 813 of file MeshDescription.h.
Referenced by for().
TriVerts
TArrayView<const FVertexID> FMeshDescription::TriVerts = TriangleVertices[TriangleID]
Definition at line 795 of file MeshDescription.h.
Referenced by for().
UVElements
FMeshElementChannels* FMeshDescription::UVElements private
Definition at line 1291 of file MeshDescription.h.
Referenced by CreateUV(), CreateUVWithID(), DeleteUV(), GetNumUVElementChannels(), IsUVValid(), ReserveNewUVs(), UVs(), and UVs().
UVsName
MESHDESCRIPTION_API FName FMeshDescription::UVsName static
Definition at line 1280 of file MeshDescription.h.
UVToTriangles
FMeshElementIndexer FMeshDescription::UVToTriangles mutable private
Definition at line 1313 of file MeshDescription.h.
Referenced by DeleteUV(), ResumeUVIndexing(), and SuspendUVIndexing().
VertexElements
FMeshElementChannels* FMeshDescription::VertexElements private
Definition at line 1289 of file MeshDescription.h.
Referenced by CreateVertex(), CreateVertexWithID(), DeleteVertex(), IsVertexValid(), ReserveNewVertices(), Vertices(), and Vertices().
VertexInstanceElements
FMeshElementChannels* FMeshDescription::VertexInstanceElements private
Definition at line 1290 of file MeshDescription.h.
Referenced by CreateVertexInstance(), CreateVertexInstanceWithID(), IsVertexInstanceValid(), ReserveNewVertexInstances(), VertexInstances(), and VertexInstances().
VertexInstancesName
MESHDESCRIPTION_API FName FMeshDescription::VertexInstancesName static
Definition at line 1279 of file MeshDescription.h.
VertexInstanceToTriangles
FMeshElementIndexer FMeshDescription::VertexInstanceToTriangles mutable private
Definition at line 1311 of file MeshDescription.h.
Referenced by BuildVertexInstanceIndexers(), GetNumVertexConnectedTriangles(), GetNumVertexInstanceConnectedTriangles(), GetVertexConnectedPolygons(), GetVertexConnectedTriangles(), GetVertexInstanceConnectedPolygons(), GetVertexInstanceConnectedTriangleIDs(), ResumeVertexInstanceIndexing(), and SuspendVertexInstanceIndexing().
VertexInstanceVertices
TMeshAttributesArray<FVertexID> FMeshDescription::VertexInstanceVertices private
Definition at line 1297 of file MeshDescription.h.
Referenced by GetVertexInstanceVertex().
VertexPositions
TMeshAttributesArray<FVector3f> FMeshDescription::VertexPositions private
Definition at line 1306 of file MeshDescription.h.
Referenced by GetVertexPosition(), GetVertexPositions(), and GetVertexPositions().
VertexToEdges
FMeshElementIndexer FMeshDescription::VertexToEdges mutable private
Definition at line 1310 of file MeshDescription.h.
Referenced by BuildVertexIndexers(), DeleteVertex(), GetNumVertexConnectedEdges(), GetVertexAdjacentVertices(), GetVertexConnectedEdgeIDs(), ResumeVertexIndexing(), and SuspendVertexIndexing().
VertexToVertexInstances
FMeshElementIndexer FMeshDescription::VertexToVertexInstances mutable private
Definition at line 1309 of file MeshDescription.h.
Referenced by BuildVertexIndexers(), DeleteVertex(), GetNumVertexConnectedTriangles(), GetNumVertexVertexInstances(), GetVertexConnectedPolygons(), GetVertexConnectedTriangles(), GetVertexVertexInstanceIDs(), ResumeVertexIndexing(), and SuspendVertexIndexing().
VerticesName
MESHDESCRIPTION_API FName FMeshDescription::VerticesName static
Definition at line 1278 of file MeshDescription.h.
The documentation for this struct was generated from the following file:
MeshDescription.h