Unreal Engine 5.6 C++ API: UE::FPropertyPathNameTree Class Reference
UE::FPropertyPathNameTree Class Reference
A tree of property path names and their associated types.
#include "PropertyPathNameTree.h"
Data Structures
class FConstIterator
struct FConstNode
struct FKey
Key corresponding to a FPropertyPathNameSegment with no index.
struct FNode
struct FValue
Public Member Functions
FPropertyPathNameTree ()=default
FPropertyPathNameTree (const FPropertyPathNameTree &)=delete
FPropertyPathNameTree (FPropertyPathNameTree &&)=default
FNode Add (const FPropertyPathName &Path, int32 StartIndex=0)
Adds the path to the tree.
FConstIterator CreateConstIterator () const
void Empty ()
Remove every property path name from the tree.
FNode Find (const FPropertyPathName &Path, int32 StartIndex=0)
Finds the path within the tree.
FConstNode Find (const FPropertyPathName &Path, int32 StartIndex=0) const
bool IsEmpty () const
True if the tree contains no property path names.
FPropertyPathNameTree & operator= (const FPropertyPathNameTree &)=delete
FPropertyPathNameTree & operator= (FPropertyPathNameTree &&)=default
Private Attributes
TMap< FKey, FValue > Nodes
Friends
void AppendHash (FBlake3 &Builder, const FPropertyPathNameTree &Tree)
Detailed Description
A tree of property path names and their associated types.
A union of the paths that are added, ignoring any container index.
Definition at line 24 of file PropertyPathNameTree.h.
Constructor & Destructor Documentation
FPropertyPathNameTree() [1/3]
UE::FPropertyPathNameTree::FPropertyPathNameTree () default
Referenced by FPropertyPathNameTree(), FPropertyPathNameTree(), AppendHash, Find(), UE::FPropertyPathNameTree::FConstNode::GetSubTree(), UE::FPropertyPathNameTree::FNode::GetSubTree(), operator=(), and operator=().
FPropertyPathNameTree() [2/3]
UE::FPropertyPathNameTree::FPropertyPathNameTree (FPropertyPathNameTree &&) default
References FPropertyPathNameTree().
FPropertyPathNameTree() [3/3]
UE::FPropertyPathNameTree::FPropertyPathNameTree (const FPropertyPathNameTree &) delete
References FPropertyPathNameTree().
Member Function Documentation
Add()
FNode UE::FPropertyPathNameTree::Add (const FPropertyPathName & Path, int32 StartIndex = 0)
Adds the path to the tree.
Keeps any existing nodes that match both name and type.
References Path, and UE_API.
CreateConstIterator()
FConstIterator UE::FPropertyPathNameTree::CreateConstIterator () const inline nodiscard
Definition at line 134 of file PropertyPathNameTree.h.
References Nodes.
Empty()
void UE::FPropertyPathNameTree::Empty ()
Remove every property path name from the tree.
References UE_API.
Find() [1/2]
FNode UE::FPropertyPathNameTree::Find (const FPropertyPathName & Path, int32 StartIndex = 0) nodiscard
Finds the path within the tree.
Parameters
OutSubTree If non-null, this is set to the maybe-null sub-tree at the path if the path is found.
Path Path to search within the tree.
StartIndex Index of the segment within Path at which to start searching.
Returns
An accessor for the node at the path if it exists.
References Path, and UE_API.
Find() [2/2]
FConstNode UE::FPropertyPathNameTree::Find (const FPropertyPathName & Path, int32 StartIndex = 0) const inline nodiscard
Definition at line 106 of file PropertyPathNameTree.h.
References FPropertyPathNameTree(), Find, and Path.
IsEmpty()
bool UE::FPropertyPathNameTree::IsEmpty () const inline
True if the tree contains no property path names.
Definition at line 89 of file PropertyPathNameTree.h.
References Nodes.
operator=() [1/2]
FPropertyPathNameTree & UE::FPropertyPathNameTree::operator= (const FPropertyPathNameTree &) delete
References FPropertyPathNameTree().
operator=() [2/2]
FPropertyPathNameTree & UE::FPropertyPathNameTree::operator= (FPropertyPathNameTree &&) default
References FPropertyPathNameTree().
Friends And Related Symbol Documentation
AppendHash
void AppendHash (FBlake3 & Builder, const FPropertyPathNameTree & Tree) friend
References FPropertyPathNameTree(), and UE_API.
Field Documentation
Nodes
TMap<FKey, FValue> UE::FPropertyPathNameTree::Nodes private
Definition at line 139 of file PropertyPathNameTree.h.
Referenced by CreateConstIterator(), and IsEmpty().
The documentation for this class was generated from the following file:
PropertyPathNameTree.h