Unreal Engine 5.6 C++ API: TAsyncGraphTask< ResultType > Class Template Reference
TAsyncGraphTask< ResultType > Class Template Reference
Template for asynchronous functions that are executed in the Task Graph system.
#include "Async.h"
Public Member Functions
TAsyncGraphTask (TUniqueFunction< ResultType()> &&InFunction, TPromise< ResultType > &&InPromise, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Creates and initializes a new instance.
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
Performs the actual task.
ENamedThreads::Type GetDesiredThread ()
Returns the name of the thread that this task should run on.
TFuture< ResultType > GetFuture ()
Gets the future that will hold the asynchronous result.
Public Member Functions inherited from FAsyncGraphTaskBase
TStatId GetStatId () const
Gets the task's stats tracking identifier.
Private Attributes
ENamedThreads::Type DesiredThread
The desired execution thread.
TUniqueFunction< ResultType()> Function
The function to execute on the Task Graph.
TPromise< ResultType > Promise
The promise to assign the result to.
Additional Inherited Members
Static Public Member Functions inherited from FAsyncGraphTaskBase
static ESubsequentsMode::Type GetSubsequentsMode ()
Gets the mode for tracking subsequent tasks.
Detailed Description
template<typename ResultType>
class TAsyncGraphTask< ResultType >
Template for asynchronous functions that are executed in the Task Graph system.
Definition at line 106 of file Async.h.
Constructor & Destructor Documentation
TAsyncGraphTask()
template<typename ResultType> TAsyncGraphTask< ResultType >::TAsyncGraphTask (TUniqueFunction< ResultType()> && InFunction, TPromise< ResultType > && InPromise, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline
Creates and initializes a new instance.
Parameters
InFunction The function to execute asynchronously.
InPromise The promise object used to return the function's result.
Definition at line 117 of file Async.h.
References ENamedThreads::AnyThread, DesiredThread, Function, MoveTemp(), and Promise.
Member Function Documentation
DoTask()
template<typename ResultType> void TAsyncGraphTask< ResultType >::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Performs the actual task.
Parameters
CurrentThread The thread that this task is executing on.
MyCompletionGraphEvent The completion event.
Definition at line 131 of file Async.h.
References Function, Promise, and SetPromise().
GetDesiredThread()
template<typename ResultType> ENamedThreads::Type TAsyncGraphTask< ResultType >::GetDesiredThread () inline
Returns the name of the thread that this task should run on.
Returns
Always run on any thread.
Definition at line 141 of file Async.h.
References DesiredThread.
GetFuture()
template<typename ResultType> TFuture< ResultType > TAsyncGraphTask< ResultType >::GetFuture () inline
Gets the future that will hold the asynchronous result.
Returns
A TFuture object.
Definition at line 151 of file Async.h.
References Promise.
Field Documentation
DesiredThread
template<typename ResultType> ENamedThreads::Type TAsyncGraphTask< ResultType >::DesiredThread private
The desired execution thread.
Definition at line 165 of file Async.h.
Referenced by TAsyncGraphTask(), and GetDesiredThread().
Function
template<typename ResultType> TUniqueFunction<ResultType()> TAsyncGraphTask< ResultType >::Function private
The function to execute on the Task Graph.
Definition at line 159 of file Async.h.
Referenced by TAsyncGraphTask(), and DoTask().
Promise
template<typename ResultType> TPromise<ResultType> TAsyncGraphTask< ResultType >::Promise private
The promise to assign the result to.
Definition at line 162 of file Async.h.
Referenced by TAsyncGraphTask(), DoTask(), and GetFuture().
The documentation for this class was generated from the following file:
Async.h