Unreal Engine 5.6 C++ API: FSkinnedAssetAsyncBuildTask Struct Reference
FSkinnedAssetAsyncBuildTask Struct Reference
#include "SkinnedAssetAsyncCompileUtils.h"
Public Member Functions
FSkinnedAssetAsyncBuildTask (USkinnedAsset *InSkinnedAsset, FSkinnedAssetBuildContext &&InBuildContext)
FSkinnedAssetAsyncBuildTask (USkinnedAsset *InSkinnedAsset, FSkinnedAssetPostLoadContext &&InPostLoadContext)
FSkinnedAssetAsyncBuildTask (USkinnedAsset *InSkinnedAsset, FSkinnedAsyncTaskContext &&InAsyncTaskContext)
Public Member Functions inherited from FAsyncTask< FSkinnedAssetAsyncBuildWorker >
FAsyncTask ()
void DoTaskWork () final
Perform task's work.
FSkinnedAssetAsyncBuildWorker & GetTask ()
bool TryAbandonTask () final
Abandon task if possible, returns true on success, false otherwise.
Public Member Functions inherited from FAsyncTaskBase
virtual ~FAsyncTaskBase ()
Destructor, not legal when a task is in process.
bool Cancel ()
Cancel the task, if possible.
void EnsureCompletion (bool bDoWorkOnThisThreadIfNotStarted=true, bool bIsLatencySensitive=false)
Wait until the job is complete.
const TCHAR * GetDebugName () const final
Returns text to identify the Work, for debug/log purposes only.
EQueuedWorkPriority GetPriority () const
int64 GetRequiredMemory () const final
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
bool IsDone ()
Returns true if the work and TASK has completed, false while it's still in progress.
bool IsIdle () const
Returns true if the work has not been started or has been completed.
bool IsWorkDone () const
Returns true if the work has completed, false while it's still in progress.
bool Reschedule (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal)
If not already being processed, will be rescheduled on given thread pool and priority.
bool SetPriority (EQueuedWorkPriority QueuedWorkPriority)
void StartBackgroundTask (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Queue this task for processing by the background thread pool.
void StartSynchronousTask (EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Run this task on this thread.
bool WaitCompletionWithTimeout (float TimeLimitSeconds)
Wait until the job is complete, up to a time limit.
Data Fields
const USkinnedAsset * SkinnedAsset
Additional Inherited Members
Protected Member Functions inherited from FAsyncTaskBase
void CheckIdle () const
Internal call to assert that we are idle.
void Init (TStatId InStatId)
Detailed Description
Definition at line 118 of file SkinnedAssetAsyncCompileUtils.h.
Constructor & Destructor Documentation
FSkinnedAssetAsyncBuildTask() [1/3]
FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask (USkinnedAsset * InSkinnedAsset, FSkinnedAssetPostLoadContext && InPostLoadContext) inline
Definition at line 120 of file SkinnedAssetAsyncCompileUtils.h.
References FAsyncTask< FSkinnedAssetAsyncBuildWorker >::FAsyncTask(), MoveTemp(), and SkinnedAsset.
FSkinnedAssetAsyncBuildTask() [2/3]
FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask (USkinnedAsset * InSkinnedAsset, FSkinnedAssetBuildContext && InBuildContext) inline
Definition at line 128 of file SkinnedAssetAsyncCompileUtils.h.
References FAsyncTask< FSkinnedAssetAsyncBuildWorker >::FAsyncTask(), MoveTemp(), and SkinnedAsset.
FSkinnedAssetAsyncBuildTask() [3/3]
FSkinnedAssetAsyncBuildTask::FSkinnedAssetAsyncBuildTask (USkinnedAsset * InSkinnedAsset, FSkinnedAsyncTaskContext && InAsyncTaskContext) inline
Definition at line 136 of file SkinnedAssetAsyncCompileUtils.h.
References FAsyncTask< FSkinnedAssetAsyncBuildWorker >::FAsyncTask(), MoveTemp(), and SkinnedAsset.
Field Documentation
SkinnedAsset
const USkinnedAsset* FSkinnedAssetAsyncBuildTask::SkinnedAsset
Definition at line 144 of file SkinnedAssetAsyncCompileUtils.h.
Referenced by FSkinnedAssetAsyncBuildTask(), FSkinnedAssetAsyncBuildTask(), and FSkinnedAssetAsyncBuildTask().
The documentation for this struct was generated from the following file:
SkinnedAssetAsyncCompileUtils.h