Unreal Engine 5.6 C++ API: StateTreeIndexTypes.h File Reference
StateTreeIndexTypes.h File Reference
#include "PropertyBindingTypes.h"
#include "StateTreeIndexTypes.generated.h"
Data Structures
struct TStructOpsTypeTraits< FStateTreeIndex16 >
struct TStructOpsTypeTraits< FStateTreeIndex8 >
Macros
#define UE_API STATETREEMODULE_API
Functions
USTRUCT () struct FStateTreeIndex16
uint16 index that can be invalid.
Macro Definition Documentation
UE_API
#define UE_API STATETREEMODULE_API
Definition at line 8 of file StateTreeIndexTypes.h.
Function Documentation
USTRUCT()
USTRUCT ()
uint16 index that can be invalid.
uint8 index that can be invalid.
Returns
true if the given index can be represented by the type.
Construct from a uint16 index where MAX_uint16 is considered an invalid index (i.e FStateTreeIndex16::InvalidValue).
Construct from a int32 index where INDEX_NONE is considered an invalid index and converted to FStateTreeIndex16::InvalidValue (i.e MAX_uint16).
Construct from FPropertyBindingIndex16 to facilitate transition to FPropertyBindingIndex16 in bindings
Conversion to from FPropertyBindingIndex16 to facilitate transition to FPropertyBindingIndex16 in bindings (Intentionally not explicit for the initial refactoring)
Todo
make this explicit and update StateTree code to use FPropertyBindingIndex16
Returns
value of the index or FStateTreeIndex16::InvalidValue (i.e. MAX_uint16) if invalid.
the index value as int32, mapping invalid value to INDEX_NONE.
true if the index is valid.
true if the given index can be represented by the type.
value of the index.
the index value as int32, mapping invalid value to INDEX_NONE.
true if the index is valid.
Definition at line 11 of file StateTreeIndexTypes.h.
References BlueprintType, check, FORCEINLINE, GENERATED_BODY, GetTypeHash(), INDEX_NONE, Invalid, IsValid(), MAX_uint16, operator!=(), operator==(), UE_API, UPROPERTY, and Value.