Unreal Engine 5.6 C++ API: FGeometryIdentifier Struct Reference
FGeometryIdentifier Struct Reference
FGeometryIdentifier is used to represent a specific Geometry-containing object.
#include "GeometrySelector.h"
Public Types
enum class EObjectType {
Unknown = 0 , DynamicMeshComponent = 1 , DynamicMesh = 2 , BrushComponent = 3 ,
StaticMeshComponent = 4 , UserDefinedBase = 64
}
EObjectType is the specific UClass/UObject Type of TargetObject.
enum class ETargetType { Unknown = 0 , PrimitiveComponent = 1 , MeshContainer = 2 , UserDefinedBase = 32 }
ETargetType specifies the category of target object.
Public Member Functions
FGeometryIdentifier ()=default
bool Equals (const FGeometryIdentifier &Other) const
template<typename ComponentTypeT>
ComponentTypeT * GetAsComponentType () const
template<typename ObjectTypeT>
ObjectTypeT * GetAsObjectType () const
bool HasObject () const
bool operator== (const FGeometryIdentifier &Other) const
Static Public Member Functions
static FGeometryIdentifier PrimitiveComponent (UPrimitiveComponent *Component, EObjectType ObjectType)
Data Fields
EObjectType ObjectType = EObjectType::Unknown
Object Type specifies the specific UClass/UObject Type of TargetObject.
TWeakObjectPtr< UObject > TargetObject = nullptr
TargetObject is optional, depending on the identifier and situation it may or may not exist.
ETargetType TargetType = ETargetType::PrimitiveComponent
Target Type specifies the category of TargetObject.
Friends
uint32 GetTypeHash (const FGeometryIdentifier &Object)
Detailed Description
FGeometryIdentifier is used to represent a specific Geometry-containing object.
Definition at line 21 of file GeometrySelector.h.
Member Enumeration Documentation
EObjectType
enum class FGeometryIdentifier::EObjectType strong
EObjectType is the specific UClass/UObject Type of TargetObject.
Enumerator
Unknown
DynamicMeshComponent
DynamicMesh
BrushComponent
StaticMeshComponent
UserDefinedBase
Definition at line 40 of file GeometrySelector.h.
ETargetType
enum class FGeometryIdentifier::ETargetType strong
ETargetType specifies the category of target object.
Enumerator
Unknown
PrimitiveComponent
TargetObject is a UPrimitiveComponent subclass.
MeshContainer
TargetObject is a UObject container for a Mesh, like UStaticMesh or UDynamicMesh.
UserDefinedBase
Definition at line 26 of file GeometrySelector.h.
Constructor & Destructor Documentation
FGeometryIdentifier()
FGeometryIdentifier::FGeometryIdentifier () default
Referenced by Equals(), GetTypeHash, operator==(), and PrimitiveComponent().
Member Function Documentation
Equals()
bool FGeometryIdentifier::Equals (const FGeometryIdentifier & Other) const inline
Definition at line 78 of file GeometrySelector.h.
References FGeometryIdentifier(), ObjectType, Other, TargetObject, and TargetType.
Referenced by operator==().
GetAsComponentType()
template<typename ComponentTypeT> ComponentTypeT * FGeometryIdentifier::GetAsComponentType () const inline
Returns
TargetObject cast to template PrimitiveComponent subclass ComponentTypeT, or nullptr if it is not defined or not this type
Definition at line 103 of file GeometrySelector.h.
References Cast(), ensure, PrimitiveComponent, TargetObject, and TargetType.
GetAsObjectType()
template<typename ObjectTypeT> ObjectTypeT * FGeometryIdentifier::GetAsObjectType () const inline
Returns
TargetObject cast to template ObjectTypeT, or nullptr if it is not defined or not this type
Definition at line 94 of file GeometrySelector.h.
References Cast(), and TargetObject.
HasObject()
bool FGeometryIdentifier::HasObject () const inline
Returns
true if TargetObject is defined and still exists
Definition at line 71 of file GeometrySelector.h.
References TargetObject.
operator==()
bool FGeometryIdentifier::operator== (const FGeometryIdentifier & Other) const inline
Definition at line 74 of file GeometrySelector.h.
References FGeometryIdentifier(), Equals(), and Other.
PrimitiveComponent()
FGeometryIdentifier FGeometryIdentifier::PrimitiveComponent (UPrimitiveComponent * Component, EObjectType ObjectType) inline static
Returns
a FGeometryIdentifier for a given UPrimitiveComponent with the specified ObjectType (may be EObjectType::Unknown)
Definition at line 116 of file GeometrySelector.h.
References FGeometryIdentifier(), Component, ObjectType, PrimitiveComponent, TargetObject, and TargetType.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGeometryIdentifier & Object) friend
Definition at line 83 of file GeometrySelector.h.
References FGeometryIdentifier(), GetTypeHash, HashCombine(), and Object.
Referenced by GetTypeHash.
Field Documentation
ObjectType
EObjectType FGeometryIdentifier::ObjectType = EObjectType::Unknown
Object Type specifies the specific UClass/UObject Type of TargetObject.
Definition at line 59 of file GeometrySelector.h.
Referenced by Equals(), FBaseDynamicMeshSelector::GetIdentifier(), and PrimitiveComponent().
TargetObject
TWeakObjectPtr<UObject> FGeometryIdentifier::TargetObject = nullptr
TargetObject is optional, depending on the identifier and situation it may or may not exist.
Definition at line 64 of file GeometrySelector.h.
Referenced by Equals(), GetAsComponentType(), GetAsObjectType(), FBaseDynamicMeshSelector::GetIdentifier(), HasObject(), and PrimitiveComponent().
TargetType
ETargetType FGeometryIdentifier::TargetType = ETargetType::PrimitiveComponent
Target Type specifies the category of TargetObject.
Definition at line 54 of file GeometrySelector.h.
Referenced by Equals(), GetAsComponentType(), FBaseDynamicMeshSelector::GetIdentifier(), and PrimitiveComponent().
The documentation for this struct was generated from the following file:
GeometrySelector.h