Unreal Engine 5.6 C++ API: FPackageId Class Reference
FPackageId Class Reference
#include "PackageId.h"
Public Member Functions
FPackageId ()=default
FName GetName () const
bool IsValid () const
bool operator!= (FPackageId Other) const
bool operator< (FPackageId Other) const
bool operator== (FPackageId Other) const
UE_DEPRECATED (5.5, "Use LexToString()") inline uint64 ValueForDebugging() const
uint64 Value () const
Static Public Member Functions
static FPackageId FromName (const FName &Name)
static FPackageId FromValue (const uint64 Value)
Private Member Functions
FPackageId (uint64 InId)
Private Attributes
uint64 Id = InvalidId
Static Private Attributes
static constexpr uint64 InvalidId = 0
Friends
uint32 GetTypeHash (const FPackageId &In)
FArchive & operator<< (FArchive &Ar, FPackageId &Value)
void operator<< (FStructuredArchiveSlot Slot, FPackageId &Value)
void SerializeForLog (FCbWriter &Writer, const FPackageId &Value)
Detailed Description
Definition at line 18 of file PackageId.h.
Constructor & Destructor Documentation
FPackageId() [1/2]
FPackageId::FPackageId (uint64 InId) inline explicit private
Definition at line 23 of file PackageId.h.
References Id.
Referenced by FromName(), FromValue(), GetTypeHash, operator!=(), operator<(), operator<<, operator<<, operator==(), and SerializeForLog.
FPackageId() [2/2]
FPackageId::FPackageId () default
Referenced by FromValue().
Member Function Documentation
FromName()
FPackageId FPackageId::FromName (const FName & Name) static
References FPackageId(), and Name.
Referenced by UPackage::GetPackageIdToLoad().
FromValue()
FPackageId FPackageId::FromValue (const uint64 Value) inline static
Definition at line 30 of file PackageId.h.
References FPackageId(), FPackageId(), and Value().
Referenced by FPublicExportKey::GetPackageId().
GetName()
FName FPackageId::GetName () const
IsValid()
bool FPackageId::IsValid () const inline
Definition at line 35 of file PackageId.h.
References Id, and InvalidId.
Referenced by FPublicExportKey::MakeKey().
operator!=()
bool FPackageId::operator!= (FPackageId Other) const inline
Definition at line 61 of file PackageId.h.
References FPackageId(), Id, and Other.
operator<()
bool FPackageId::operator< (FPackageId Other) const inline
Definition at line 51 of file PackageId.h.
References FPackageId(), Id, and Other.
operator==()
bool FPackageId::operator== (FPackageId Other) const inline
Definition at line 56 of file PackageId.h.
References FPackageId(), Id, and Other.
UE_DEPRECATED()
FPackageId::UE_DEPRECATED (5. 5, "Use LexToString()") const inline
Definition at line 45 of file PackageId.h.
References Id.
Value()
uint64 FPackageId::Value () const inline
Definition at line 40 of file PackageId.h.
References Id.
Referenced by FromValue(), FPublicExportKey::MakeKey(), operator<<, operator<<, and SerializeForLog.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPackageId & In) friend
Definition at line 66 of file PackageId.h.
References FPackageId(), and Id.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPackageId & Value) friend
References FPackageId(), Ar, and Value().
operator<< [2/2]
void operator<< (FStructuredArchiveSlot Slot, FPackageId & Value) friend
References FPackageId(), and Value().
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FPackageId & Value) friend
References FPackageId(), and Value().
Field Documentation
Id
uint64 FPackageId::Id = InvalidId private
Definition at line 21 of file PackageId.h.
Referenced by FPackageId(), GetTypeHash, IsValid(), operator!=(), operator<(), operator==(), UE_DEPRECATED(), and Value().
InvalidId
uint64 FPackageId::InvalidId = 0 static constexpr private
Definition at line 20 of file PackageId.h.
Referenced by IsValid().
The documentation for this class was generated from the following file:
PackageId.h