Unreal Engine 5.6 C++ API: ASkeletalMeshActor Class Reference
ASkeletalMeshActor Class Reference
#include "SkeletalMeshActor.h"
Public Member Functions
virtual void CheckForErrors () override
virtual void EditorReplacedActor (AActor *OldActor) override
virtual bool GetReferencedContentObjects (TArray< UObject * > &Objects) const override
class USkeletalMeshComponent * GetSkeletalMeshComponent () const
Returns SkeletalMeshComponent subobject.
virtual void LoadedFromAnotherClass (const FName &OldClassName) override
virtual void PostInitializeComponents () override
UFUNCTION () 1 virtual void OnRep_ReplicatedMaterial0()
UFUNCTION () 1 virtual void OnRep_ReplicatedMaterial1()
UFUNCTION () 1 virtual void OnRep_ReplicatedMesh()
Replication Notification Callbacks.
UFUNCTION () 1 virtual void OnRep_ReplicatedPhysAsset()
UPROPERTY () TObjectPtr< class UMaterialInterface > ReplicatedMaterial0
used to replicate the material in index 0
UPROPERTY () TObjectPtr< class UMaterialInterface > ReplicatedMaterial1
UPROPERTY () TObjectPtr< class UPhysicsAsset > ReplicatedPhysAsset
Used to replicate physics asset to clients.
UPROPERTY () TObjectPtr< class USkeletalMesh > ReplicatedMesh
Used to replicate mesh to clients.
Protected Member Functions
virtual FString GetDetailedInfoInternal () const override
Private Member Functions
GENERATED_UCLASS_BODY () 1 virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > &OutLifetimeProps) const override
UPROPERTY ()) TObjectPtr< class USkeletalMeshComponent > SkeletalMeshComponent
Whether or not this actor should respond to anim notifies - CURRENTLY ONLY AFFECTS PlayParticleEffect NOTIFIES.
Private Attributes
TMap< FName, TWeakObjectPtr< class UAnimMontage > > CurrentlyPlayingMontages
Detailed Description
Definition at line 22 of file SkeletalMeshActor.h.
Member Function Documentation
CheckForErrors()
virtual void ASkeletalMeshActor::CheckForErrors () override virtual
EditorReplacedActor()
virtual void ASkeletalMeshActor::EditorReplacedActor (AActor * OldActor) override virtual
GENERATED_UCLASS_BODY()
ASkeletalMeshActor::GENERATED_UCLASS_BODY () const & override private
References Animation, Category, and UPROPERTY().
GetDetailedInfoInternal()
virtual FString ASkeletalMeshActor::GetDetailedInfoInternal () const override protected virtual
References GetDetailedInfoInternal().
Referenced by GetDetailedInfoInternal().
GetReferencedContentObjects()
virtual bool ASkeletalMeshActor::GetReferencedContentObjects (TArray< UObject * > & Objects) const override virtual
GetSkeletalMeshComponent()
class USkeletalMeshComponent * ASkeletalMeshActor::GetSkeletalMeshComponent () const inline
Returns SkeletalMeshComponent subobject.
Definition at line 93 of file SkeletalMeshActor.h.
LoadedFromAnotherClass()
virtual void ASkeletalMeshActor::LoadedFromAnotherClass (const FName & OldClassName) override virtual
PostInitializeComponents()
virtual void ASkeletalMeshActor::PostInitializeComponents () override virtual
UFUNCTION() [1/4]
ASkeletalMeshActor::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [2/4]
ASkeletalMeshActor::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [3/4]
ASkeletalMeshActor::UFUNCTION ()
Replication Notification Callbacks.
References UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/4]
ASkeletalMeshActor::UFUNCTION ()
References UFUNCTION().
UPROPERTY() [1/5]
ASkeletalMeshActor::UPROPERTY ()
used to replicate the material in index 0
References UPROPERTY().
UPROPERTY() [2/5]
ASkeletalMeshActor::UPROPERTY ()
References UPROPERTY().
UPROPERTY() [3/5]
ASkeletalMeshActor::UPROPERTY ()
Used to replicate physics asset to clients.
References transient, and UPROPERTY().
UPROPERTY() [4/5]
ASkeletalMeshActor::UPROPERTY ()
Used to replicate mesh to clients.
References transient, and UPROPERTY().
UPROPERTY() [5/5]
ASkeletalMeshActor::UPROPERTY () private
Whether or not this actor should respond to anim notifies - CURRENTLY ONLY AFFECTS PlayParticleEffect NOTIFIES.
References Category, and meta.
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
CurrentlyPlayingMontages
TMap<FName, TWeakObjectPtr<class UAnimMontage> > ASkeletalMeshActor::CurrentlyPlayingMontages private
Definition at line 89 of file SkeletalMeshActor.h.
The documentation for this class was generated from the following file:
SkeletalMeshActor.h