Unreal Engine 5.6 C++ API: FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc > Class Template Reference
FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
FORCEINLINE FLockFreePointerFIFOBase ()
~FLockFreePointerFIFOBase ()
FORCEINLINE bool IsEmpty () const
T * Pop ()
template<typename ContainerType>
void PopAll (ContainerType &OutContainer)
void Push (T *InPayload)
Private Types
typedef FLockFreeLinkPolicy::TLinkPtr TLinkPtr
Private Attributes
TDoublePtr Head
TDoublePtr Tail
UE_NONCOPYABLE(FLockFreePointerFIFOBase) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink TLink
Detailed Description
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1>
class FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >
Definition at line 543 of file LockFreeList.h.
Member Typedef Documentation
TLinkPtr
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> typedef FLockFreeLinkPolicy::TLinkPtr FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::TLinkPtr private
Definition at line 549 of file LockFreeList.h.
Constructor & Destructor Documentation
FLockFreePointerFIFOBase()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::FLockFreePointerFIFOBase () inline nodiscard
Definition at line 552 of file LockFreeList.h.
References FLockFreeLinkPolicy::AllocLockFreeLink(), FORCEINLINE, Head, and Tail.
~FLockFreePointerFIFOBase()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::~FLockFreePointerFIFOBase () inline
Definition at line 566 of file LockFreeList.h.
References FLockFreeLinkPolicy::FreeLockFreeLink(), Head, and Pop().
Member Function Documentation
IsEmpty()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE bool FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::IsEmpty () const inline nodiscard
Definition at line 672 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FORCEINLINE, and Head.
Referenced by TLockFreePointerListFIFO< T, TPaddingForCacheContention >::IsEmpty().
Pop()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> T * FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop () inline nodiscard
Definition at line 617 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), Head, Tail, and TestCriticalStall().
Referenced by ~FLockFreePointerFIFOBase(), TLockFreePointerListFIFO< T, TPaddingForCacheContention >::Pop(), and PopAll().
PopAll()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> template<typename ContainerType> void FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll (ContainerType & OutContainer) inline
Definition at line 663 of file LockFreeList.h.
References Item, and Pop().
Referenced by TLockFreePointerListFIFO< T, TPaddingForCacheContention >::PopAll().
Push()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> void FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Push (T * InPayload) inline
Definition at line 572 of file LockFreeList.h.
References FLockFreeLinkPolicy::AllocLockFreeLink(), FLockFreeLinkPolicy::DerefLink(), Item, FIndexedLockFreeLink::Payload, Tail, TestCriticalStall(), and TLink.
Referenced by TLockFreePointerListFIFO< T, TPaddingForCacheContention >::Push().
Field Documentation
Head
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> TDoublePtr FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Head private
Definition at line 682 of file LockFreeList.h.
Referenced by FLockFreePointerFIFOBase(), ~FLockFreePointerFIFOBase(), IsEmpty(), and Pop().
Tail
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> TDoublePtr FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Tail private
Definition at line 683 of file LockFreeList.h.
Referenced by FLockFreePointerFIFOBase(), Pop(), and Push().
TLink
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> UE_NONCOPYABLE (FLockFreePointerFIFOBase) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::TLink private
Definition at line 548 of file LockFreeList.h.
Referenced by Push().
The documentation for this class was generated from the following file:
LockFreeList.h