Unreal Engine 5.6 C++ API: UE::Geometry::FRenderCaptureMapEvaluator< DataType > Class Template Reference
UE::Geometry::FRenderCaptureMapEvaluator< DataType > Class Template Reference
#include "RenderCaptureMapEvaluator.h"
Public Member Functions
virtual ~FRenderCaptureMapEvaluator ()
virtual const TArray< EComponents > & DataLayout () const override
virtual void Setup (const FMeshBaseBaker &Baker, FEvaluationContext &Context) override
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
virtual EMeshMapEvaluatorType Type () const override
Public Member Functions inherited from UE::Geometry::FMeshMapEvaluator
virtual ~FMeshMapEvaluator ()=default
Static Public Member Functions
static void EvaluateColor (const int DataIdx, float *&In, FVector4f &Out, void *EvalData)
static void EvaluateDefault (float *&Out, void *EvalData)
static void EvaluateSample (float *&Out, const FCorrespondenceSample &Sample, void *EvalData)
Data Fields
ERenderCaptureChannel Channel = ERenderCaptureChannel::BaseColor
DataType DefaultResult
TFunction< FVector4f(const int DataIdx, float *&In)> EvaluateColorCallback
TFunction< DataType(const FCorrespondenceSample &Sample)> EvaluateSampleCallback
Additional Inherited Members
Public Types inherited from UE::Geometry::FMeshMapEvaluator
enum class EAccumulateMode { Add , Overwrite , Last }
Accumulate mode informs the baker how samples should be accumulated into the buffer.
enum class EComponents { Float1 = 1 , Float2 = 2 , Float3 = 3 , Float4 = 4 }
The number of float components of an evaluator result/target.
Static Protected Member Functions inherited from UE::Geometry::FMeshMapEvaluator
static void WriteToBuffer (float *&Out, const float Data)
Write float data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector2f &Data)
Write FVector2f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector3f &Data)
Write FVector3f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector4f &Data)
Write FVector4f data to a float buffer and increment.
Detailed Description
template<typename DataType>
class UE::Geometry::FRenderCaptureMapEvaluator< DataType >
Definition at line 28 of file RenderCaptureMapEvaluator.h.
Constructor & Destructor Documentation
~FRenderCaptureMapEvaluator()
template<typename DataType> virtual UE::Geometry::FRenderCaptureMapEvaluator< DataType >::~FRenderCaptureMapEvaluator () inline virtual
Definition at line 42 of file RenderCaptureMapEvaluator.h.
Member Function Documentation
DataLayout()
template<typename DataType> virtual const TArray< EComponents > & UE::Geometry::FRenderCaptureMapEvaluator< DataType >::DataLayout () const inline override virtual
Returns
the data layout of the evaluator
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 55 of file RenderCaptureMapEvaluator.h.
References Channel, UE::Geometry::FMeshMapEvaluator::Float3, UE::Geometry::FMeshMapEvaluator::Float4, Layout, and UE::Geometry::WorldNormal.
Referenced by Setup().
EvaluateColor()
template<typename DataType> void UE::Geometry::FRenderCaptureMapEvaluator< DataType >::EvaluateColor (const int DataIdx, float *& In, FVector4f & Out, void * EvalData) inline static
Definition at line 78 of file RenderCaptureMapEvaluator.h.
Referenced by Setup().
EvaluateDefault()
template<typename DataType> void UE::Geometry::FRenderCaptureMapEvaluator< DataType >::EvaluateDefault (float *& Out, void * EvalData) inline static
Definition at line 72 of file RenderCaptureMapEvaluator.h.
References UE::Geometry::FMeshMapEvaluator::WriteToBuffer().
Referenced by Setup().
EvaluateSample()
template<typename DataType> void UE::Geometry::FRenderCaptureMapEvaluator< DataType >::EvaluateSample (float *& Out, const FCorrespondenceSample & Sample, void * EvalData) inline static
Definition at line 65 of file RenderCaptureMapEvaluator.h.
References UE::Geometry::FMeshMapEvaluator::WriteToBuffer().
Referenced by Setup().
Setup()
template<typename DataType> virtual void UE::Geometry::FRenderCaptureMapEvaluator< DataType >::Setup (const FMeshBaseBaker & Baker, FEvaluationContext & Context) inline override virtual
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
The evaluation context indicates to the baker how the evaluator should be invoked. See FEvaluationContext for more details.
Parameters
Baker the baker that owns this evaluator.
Context [out] the evaluation context.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 45 of file RenderCaptureMapEvaluator.h.
References UE::Geometry::FMeshMapEvaluator::Add, DataLayout(), EvaluateColor(), EvaluateDefault(), and EvaluateSample().
Type()
template<typename DataType> virtual EMeshMapEvaluatorType UE::Geometry::FRenderCaptureMapEvaluator< DataType >::Type () const inline override virtual
Returns
the type of evaluator.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 62 of file RenderCaptureMapEvaluator.h.
References UE::Geometry::RenderCapture.
Field Documentation
Channel
template<typename DataType> ERenderCaptureChannel UE::Geometry::FRenderCaptureMapEvaluator< DataType >::Channel = ERenderCaptureChannel::BaseColor
Definition at line 32 of file RenderCaptureMapEvaluator.h.
Referenced by DataLayout().
DefaultResult
template<typename DataType> DataType UE::Geometry::FRenderCaptureMapEvaluator< DataType >::DefaultResult
Definition at line 37 of file RenderCaptureMapEvaluator.h.
EvaluateColorCallback
template<typename DataType> TFunction<FVector4f(const int DataIdx, float*& In)> UE::Geometry::FRenderCaptureMapEvaluator< DataType >::EvaluateColorCallback
Definition at line 39 of file RenderCaptureMapEvaluator.h.
EvaluateSampleCallback
template<typename DataType> TFunction<DataType(const FCorrespondenceSample& Sample)> UE::Geometry::FRenderCaptureMapEvaluator< DataType >::EvaluateSampleCallback
Definition at line 38 of file RenderCaptureMapEvaluator.h.
The documentation for this class was generated from the following file:
RenderCaptureMapEvaluator.h