Unreal Engine 5.6 C++ API: RenderGraphResources.h File Reference
RenderGraphResources.h File Reference
#include "Containers/Array.h"
#include "Math/NumericLimits.h"
#include "Math/UnrealMathSSE.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "PixelFormat.h"
#include "RHI.h"
#include "RHIDefinitions.h"
#include "RHIResources.h"
#include "RHITransientResourceAllocator.h"
#include "RenderGraphAllocator.h"
#include "RenderGraphDefinitions.h"
#include "RenderGraphParameter.h"
#include "RenderGraphTextureSubresource.h"
#include "RendererInterface.h"
#include "ShaderParameterMacros.h"
#include "Templates/Function.h"
#include "Templates/RefCounting.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include "RenderGraphResources.inl"
Data Structures
class FRDGBuffer
A render graph tracked buffer.
struct FRDGBufferDesc
Descriptor for render graph tracked Buffer.
class FRDGBufferSRV
Render graph tracked buffer SRV.
struct FRDGBufferSRVDesc
class FRDGBufferUAV
Render graph tracked buffer UAV.
struct FRDGBufferUAVDesc
class FRDGPooledBuffer
class FRDGPooledTexture
struct FRDGProducerState
Used for tracking pass producer / consumer edges in the graph for culling and pipe fencing.
class FRDGResource
Generic graph resource.
class FRDGShaderResourceView
Render graph tracked SRV.
struct FRDGSubresourceState
Used for tracking the state of an individual subresource during execution.
class FRDGTexture
Render graph tracked Texture.
class FRDGTextureSRV
Render graph tracked SRV.
class FRDGTextureSRVDesc
Descriptor for render graph tracked SRV.
class FRDGTextureUAV
Render graph tracked texture UAV.
class FRDGTextureUAVDesc
Descriptor for render graph tracked UAV.
class FRDGUniformBuffer
class FRDGUnorderedAccessView
Render graph tracked UAV.
class FRDGView
A render graph resource (e.g.
class FRDGViewableResource
A render graph resource with an allocation lifetime tracked by the graph.
struct FRDGViewableResource::FAccessModeState
class TRDGUniformBuffer< ParameterStructType >
Typedefs
using FRDGProducerStatesByPipeline = TRHIPipelineArray<FRDGProducerState>
using FRDGTextureSubresourceState = TRDGTextureSubresourceArray<FRDGSubresourceState*, FRDGArrayAllocator>
Enumerations
enum class ERDGBarrierLocation : uint8 { Prologue , Epilogue }
Barrier location controls where the barrier is 'Ended' relative to the pass lambda being executed.
Functions
FGraphicsPipelineRenderTargetsInfo ExtractRenderTargetsInfo (const FRDGParameterStruct &ParameterStruct)
FGraphicsPipelineRenderTargetsInfo ExtractRenderTargetsInfo (const FRenderTargetBindingSlots &RenderTargets)
template<typename ViewType>
ViewType * GetAs (FRDGView *View)
template<typename ViewableResourceType>
ViewableResourceType * GetAs (FRDGViewableResource *Resource)
FRDGBuffer * GetAsBuffer (FRDGViewableResource *Resource)
FRDGBufferSRV * GetAsBufferSRV (FRDGView *View)
FRDGBufferUAV * GetAsBufferUAV (FRDGView *View)
FRDGTexture * GetAsTexture (FRDGViewableResource *Resource)
FRDGTextureSRV * GetAsTextureSRV (FRDGView *View)
FRDGTextureUAV * GetAsTextureUAV (FRDGView *View)
FRDGTextureDesc Translate (const FPooledRenderTargetDesc &InDesc)
Translates from a pooled render target descriptor to an RDG texture descriptor.
FRHIBufferCreateInfo Translate (const FRDGBufferDesc &InDesc)
Translates from a RDG buffer descriptor to a RHI buffer creation info.
FPooledRenderTargetDesc Translate (const FRHITextureDesc &InDesc)
Translates from an RHI/RDG texture descriptor to a pooled render target descriptor.
Typedef Documentation
FRDGProducerStatesByPipeline
using FRDGProducerStatesByPipeline = TRHIPipelineArray<FRDGProducerState>
Definition at line 65 of file RenderGraphResources.h.
FRDGTextureSubresourceState
using FRDGTextureSubresourceState = TRDGTextureSubresourceArray<FRDGSubresourceState*, FRDGArrayAllocator>
Definition at line 127 of file RenderGraphResources.h.
Enumeration Type Documentation
ERDGBarrierLocation
enum class ERDGBarrierLocation : uint8 strong
Barrier location controls where the barrier is 'Ended' relative to the pass lambda being executed.
Most barrier locations are done in the prologue prior to the executing lambda. But certain cases like an aliasing discard operation need to be done after the pass being invoked. Therefore, when adding a transition the user can specify where to place the barrier.
Enumerator
Prologue
The barrier occurs in the prologue of the pass (before execution).
Epilogue
The barrier occurs in the epilogue of the pass (after execution).
Definition at line 56 of file RenderGraphResources.h.
Function Documentation
ExtractRenderTargetsInfo() [1/2]
FGraphicsPipelineRenderTargetsInfo ExtractRenderTargetsInfo (const FRDGParameterStruct & ParameterStruct) inline
ExtractRenderTargetsInfo() [2/2]
FGraphicsPipelineRenderTargetsInfo ExtractRenderTargetsInfo (const FRenderTargetBindingSlots & RenderTargets) inline
GetAs() [1/2]
template<typename ViewType> ViewType * GetAs (FRDGView * View) inline
Definition at line 1483 of file RenderGraphResources.h.
References check, and FRDGView::Type.
GetAs() [2/2]
template<typename ViewableResourceType> ViewableResourceType * GetAs (FRDGViewableResource * Resource) inline
Definition at line 1476 of file RenderGraphResources.h.
References check, and FRDGViewableResource::Type.
Referenced by GetAsBuffer(), GetAsBufferSRV(), GetAsBufferUAV(), GetAsTexture(), GetAsTextureSRV(), and GetAsTextureUAV().
GetAsBuffer()
FRDGBuffer * GetAsBuffer (FRDGViewableResource * Resource) inline
Definition at line 1489 of file RenderGraphResources.h.
References GetAs().
GetAsBufferSRV()
FRDGBufferSRV * GetAsBufferSRV (FRDGView * View) inline
Definition at line 1504 of file RenderGraphResources.h.
References GetAs().
GetAsBufferUAV()
FRDGBufferUAV * GetAsBufferUAV (FRDGView * View) inline
Definition at line 1499 of file RenderGraphResources.h.
References GetAs().
GetAsTexture()
FRDGTexture * GetAsTexture (FRDGViewableResource * Resource) inline
Definition at line 1494 of file RenderGraphResources.h.
References GetAs().
GetAsTextureSRV()
FRDGTextureSRV * GetAsTextureSRV (FRDGView * View) inline
Definition at line 1514 of file RenderGraphResources.h.
References GetAs().
GetAsTextureUAV()
FRDGTextureUAV * GetAsTextureUAV (FRDGView * View) inline
Definition at line 1509 of file RenderGraphResources.h.
References GetAs().
Translate() [1/3]
FRDGTextureDesc Translate (const FPooledRenderTargetDesc & InDesc) inline
Translates from a pooled render target descriptor to an RDG texture descriptor.
Referenced by FRenderTargetPool::FindFreeElement(), and UE::Geometry::TMeshLocalParam< PointSetType >::TransformUV().
Translate() [2/3]
FRHIBufferCreateInfo Translate (const FRDGBufferDesc & InDesc) inline
Translates from a RDG buffer descriptor to a RHI buffer creation info.
Translate() [3/3]
FPooledRenderTargetDesc Translate (const FRHITextureDesc & InDesc) inline
Translates from an RHI/RDG texture descriptor to a pooled render target descriptor.