Unreal Engine 5.6 C++ API: UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources Struct Reference
UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources Struct Reference
Structure responsible for tracking contributions to pre-eanimated state entries that originate from track EvaluationHooks (ie, from an IMovieSceneExecutionToken::Execute)
#include "MovieScenePreAnimatedCaptureSources.h"
Public Member Functions
MOVIESCENE_API FPreAnimatedEvaluationHookCaptureSources (FPreAnimatedStateExtension *InOwner)
MOVIESCENE_API EPreAnimatedCaptureSourceState BeginTrackingCaptureSource (const UObject *Hook, FMovieSceneSequenceID SequenceID, const FPreAnimatedStateMetaData &MetaData)
Make an association for the specified evaluation key to the value specified by Entry, along with an indication of whether it should be restored on completion.
MOVIESCENE_API void StopTrackingCaptureSource (const UObject *Hook, FRootInstanceHandle RootInstanceHandle, FMovieSceneSequenceID SequenceID)
Stop tracking the evaluation key in question, restoring the value if it was captured with bWantsRestoreState.
Public Member Functions inherited from UE::MovieScene::TPreAnimatedCaptureSources< FPreAnimatedEvalHookKeyType >
TPreAnimatedCaptureSources (FPreAnimatedStateExtension *InOwner)
MOVIESCENE_API EPreAnimatedCaptureSourceState BeginTrackingCaptureSource (const FPreAnimatedEvalHookKeyType &InKey, const FPreAnimatedStateMetaData &MetaData)
Make an association for the specified evaluation key to the value specified by Entry, along with an indication of whether it should be restored on completion.
MOVIESCENE_API bool ContainsInstanceHandle (FRootInstanceHandle RootInstanceHandle) const override
MOVIESCENE_API void GatherAndRemoveExpiredMetaData (const FRestoreStateParams &Params, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForGroup (FPreAnimatedStorageGroupHandle Group, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForRootInstance (FRootInstanceHandle InstanceHandle, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void GatherAndRemoveMetaDataForStorage (FPreAnimatedStorageID StorageID, FPreAnimatedStorageIndex StorageIndex, TArray< FPreAnimatedStateMetaData > &OutExpiredMetaData) override
MOVIESCENE_API void Reset () override
MOVIESCENE_API void StopTrackingCaptureSource (const FPreAnimatedEvalHookKeyType &InKey, FPreAnimatedStorageID InStorageID)
Stop tracking the evaluation key in question, where associated with the given storage value ID This restores the value if it was captured with bWantsRestoreState.
Public Member Functions inherited from UE::MovieScene::IPreAnimatedCaptureSource
virtual ~IPreAnimatedCaptureSource ()
Detailed Description
Structure responsible for tracking contributions to pre-eanimated state entries that originate from track EvaluationHooks (ie, from an IMovieSceneExecutionToken::Execute)
Definition at line 157 of file MovieScenePreAnimatedCaptureSources.h.
Constructor & Destructor Documentation
FPreAnimatedEvaluationHookCaptureSources()
MOVIESCENE_API UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources::FPreAnimatedEvaluationHookCaptureSources (FPreAnimatedStateExtension * InOwner)
Member Function Documentation
BeginTrackingCaptureSource()
MOVIESCENE_API EPreAnimatedCaptureSourceState UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources::BeginTrackingCaptureSource (const UObject * Hook, FMovieSceneSequenceID SequenceID, const FPreAnimatedStateMetaData & MetaData)
Make an association for the specified evaluation key to the value specified by Entry, along with an indication of whether it should be restored on completion.
References MetaData.
Referenced by StopTrackingCaptureSource().
StopTrackingCaptureSource()
MOVIESCENE_API void UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources::StopTrackingCaptureSource (const UObject * Hook, FRootInstanceHandle RootInstanceHandle, FMovieSceneSequenceID SequenceID)
Stop tracking the evaluation key in question, restoring the value if it was captured with bWantsRestoreState.
References UE::MovieScene::TPreAnimatedCaptureSources< FPreAnimatedEvalHookKeyType >::TPreAnimatedCaptureSources(), BeginTrackingCaptureSource(), and StopTrackingCaptureSource().
Referenced by StopTrackingCaptureSource().
The documentation for this struct was generated from the following file:
MovieScenePreAnimatedCaptureSources.h