Unreal Engine 5.6 C++ API: FMaterialShaderMap Class Reference
FMaterialShaderMap Class Reference
The set of material shaders for a single material.
#include "MaterialShared.h"
Data Structures
struct FAsyncLoadContext
A context returned by BeginLoadFromDerivedDataCache that can be queried to know the state of the async request.
Public Types
using FLWCUsagesArray = TStaticArray<uint16, (int)ELWCFunctionKind::Max>
using Super = TShaderMap<FMaterialShaderMapContent, FShaderMapPointerTable>
Public Member Functions
FMaterialShaderMap ()
virtual ~FMaterialShaderMap ()
uint32 AcquireCompilingId (const TRefCountPtr< FSharedShaderCompilerEnvironment > &InMaterialEnvironment)
FMaterialShaderMap * AcquireFinalizedClone ()
FMeshMaterialShaderMap * AcquireMeshShaderMap (const FHashedName &VertexFactoryTypeName)
FMeshMaterialShaderMap * AcquireMeshShaderMap (const FVertexFactoryType *VertexFactoryType)
void AddCompilingDependency (FMaterial *Material)
void AddRef ()
void AppendCompileStateDebugInfo (FStringBuilderBase &OutDebugInfo) const
FPSOPrecacheDataArray CollectPSOPrecacheData (const FMaterialPSOPrecacheParams &PrecacheParams)
Collect all possible PSO's which can be used with this material shader map for given parameters.
void Compile (FMaterial *Material, const FMaterialShaderMapId &ShaderMapId, const TRefCountPtr< FSharedShaderCompilerEnvironment > &MaterialEnvironment, const FMaterialCompilationOutput &InMaterialCompilationOutput, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode)
Compiles the shaders for a material and caches them in this shader map.
bool CompiledSuccessfully () const
void CountNumShaders (int32 &NumShaders, int32 &NumPipelines) const
void DumpDebugInfo (FOutputDevice &OutputDevice) const
virtual void DumpShaderList (FShaderListReport &Out) const
uint32 GetCompilingId () const
const TCHAR * GetDebugDescription () const
void GetEstimatedLWCFuncUsageComplexity (uint32 &LWCComplexityVS, uint32 &LWCComplexityPS, uint32 &LWCComplexityCS) const
void GetEstimatedLWCFuncUsages (FLWCUsagesArray &UsagesVS, FLWCUsagesArray &UsagesPS, FLWCUsagesArray &UsagesCS) const
void GetEstimatedNumTextureSamples (uint32 &VSSamples, uint32 &PSSamples) const
uint32 GetEstimatedNumVirtualTextureLookups () const
FMaterialShaderMap * GetFinalizedClone () const
const TCHAR * GetFriendlyName () const
const TCHAR * GetMaterialPath () const
uint32 GetMaxNumInstructionsForShader (FShaderType *ShaderType) const
uint32 GetMaxTextureSamplers () const
Returns the maximum number of texture samplers used by any shader in this shader map.
const FMeshMaterialShaderMap * GetMeshShaderMap (const FHashedName &VertexFactoryTypeName) const
const FMeshMaterialShaderMap * GetMeshShaderMap (const FVertexFactoryType *VertexFactoryType) const
uint32 GetNumPreshaders () const
int32 GetNumRefs () const
uint32 GetNumUsedCustomInterpolatorScalars () const
uint32 GetNumUsedUVScalars () const
uint32 GetNumVirtualTextureStacks () const
void GetOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
const TRefCountPtr< FSharedShaderCompilerEnvironment > & GetPendingCompilerEnvironment () const
int32 GetRefCount () const
FScriptName GetResolutionRelativeToInput () const
uint8 GetRuntimeVirtualTextureOutputAttributeMask () const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (const typename ShaderType::FPermutationDomain &PermutationVector) const
TShaderRef< FShader > GetShader (FShaderType *ShaderType, int32 PermutationId=0) const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (int32 PermutationId=0) const
const FSHAHash & GetShaderContentHash () const
virtual void GetShaderList (TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const override
Builds a list of the shaders in a shader map.
void GetShaderList (TMap< FShaderId, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
const FMaterialShaderMapId & GetShaderMapId () const
uint32 GetShaderNum () const
Number of Shaders in Shadermap.
virtual void GetShaderPipelineList (TArray< FShaderPipelineRef > &OutShaderPipelines) const override
Builds a list of the shader pipelines in a shader map.
const FMemoryImageString * GetShaderSource (const FVertexFactoryType *VertexFactoryType, const FShaderType *ShaderType, int32 PermutationId) const
uint8 GetSubstrateClosureCount () const
const FSubstrateMaterialCompilationOutput & GetSubstrateMaterialCompilationOutput () const
uint8 GetSubstrateMaterialType () const
uint8 GetSubstrateUintPerPixel () const
bool GetSubstrateUsesComplexSpecialRenderPath () const
const FRHIUniformBufferLayout * GetUniformBufferLayout () const
const FUniformExpressionSet & GetUniformExpressionSet () const
TConstArrayView< FScriptName > GetUserSceneTextureInputs () const
FScriptName GetUserSceneTextureOutput () const
FIntPoint GetUserTextureDivisor () const
void InitalizeForODSC (EShaderPlatform TargetShaderPlatform, const FMaterialCompilationOutput &NewCompilationOutput)
bool IsCompilationFinalized () const
bool IsComplete (const FMaterial *Material, bool bSilent)
Checks whether the material shader map is missing any shader types necessary for the given material.
bool IsLightFunctionAtlasCompatible () const
bool IsValidForRendering (bool bFailOnInvalid=false) const
void LoadMissingShadersFromMemory (const FMaterial *Material)
Attempts to load missing shaders from memory.
bool ModifiesMeshPosition () const
bool NeedsGBuffer () const
bool NeedsSceneTextures () const
void ProcessCompilationResults (const TArray< TRefCountPtr< FShaderCommonCompileJob > > &ICompilationResults, int32 &InOutJobIndex, float &TimeBudget)
Sorts the incoming compiled jobs into the appropriate mesh shader maps.
void Register (EShaderPlatform InShaderPlatform)
Registers a material shader map in the global map so it can be used by materials.
void RegisterForODSC (EShaderPlatform InShaderPlatform)
Registers a material shader map in the global map so it can be used by materials.
void Release ()
void ReleaseCompilingId ()
void RemoveCompilingDependency (FMaterial *Material)
bool RequiresSceneColorCopy () const
void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SaveToDerivedDataCache (const FMaterialShaderParameters &ShaderParameters)
Saves this shader map to the derived data cache.
bool Serialize (FShaderSerializeContext &Ctx)
Serializes the shader map.
void SetCompiledSuccessfully (bool bSuccess)
int32 SubmitCompileJobs (uint32 CompilingShaderMapId, const FMaterial *Material, const TRefCountPtr< FSharedShaderCompilerEnvironment > &MaterialEnvironment, EShaderCompileJobPriority Priority) const
Submits compile jobs for this shadermap, returns number of jobs submitted.
UE_DEPRECATED (5.5, "Please use overload accepting an FShaderSerializeContext. Note that inlining of shader code into runtime shadermaps is no longer supported. If you rely on this please reach out to the UE rendering team.") bool Serialize(FArchive &Ar
bool UsesAnisotropy () const
bool UsesDisplacement () const
bool UsesDistanceCullFade () const
bool UsesEyeAdaptation () const
bool UsesGlobalDistanceField () const
bool UsesPathTracingBufferTexture (uint32 TexId) const
bool UsesPixelDepthOffset () const
bool UsesSceneDepthLookup () const
bool UsesSceneTexture (uint32 TexId) const
bool UsesVelocitySceneTexture () const
bool UsesWorldPositionOffset () const
Public Member Functions inherited from TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >
void FinalizeContent ()
const FMaterialShaderMapContent * GetContent () const
FMaterialShaderMapContent * GetMutableContent ()
const FShaderMapPointerTable & GetPointerTable () const
Public Member Functions inherited from FShaderMapBase
virtual RENDERCORE_API ~FShaderMapBase ()
RENDERCORE_API void AssignContent (TMemoryImageObject< FShaderMapContent > InContent)
void AssociateWithAsset (const FName &AssetPath)
Associates a shadermap with an asset (note: one shadermap can be used by several assets, e.g.
void AssociateWithAssets (const FShaderMapAssetPaths &AssetPaths)
RENDERCORE_API void FinalizeContent ()
const FShaderMapAssetPaths & GetAssociatedAssets () const
const FShaderMapContent * GetContent () const
uint32 GetFrozenContentSize () const
FShaderMapContent * GetMutableContent ()
void GetOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
EShaderPermutationFlags GetPermutationFlags () const
const FShaderMapPointerTable & GetPointerTable () const
FShaderMapResource * GetResource () const
FShaderMapResource * GetResourceChecked () const
RENDERCORE_API FShaderMapResourceCode * GetResourceCode ()
EShaderPlatform GetShaderPlatform () const
void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API bool Serialize (FArchive &Ar, bool bInlineShaderResources, bool bLoadingCooked, bool bInlineShaderCode=false, const FName &SerializingAsset=NAME_None)
RENDERCORE_API bool Serialize (FShaderSerializeContext &Ctx)
RENDERCORE_API FString ToString () const
RENDERCORE_API void UnfreezeContent ()
Public Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Static Public Member Functions
static TSharedRef< FAsyncLoadContext > BeginLoadFromDerivedDataCache (const FMaterial *Material, const FMaterialShaderMapId &ShaderMapId, EShaderPlatform Platform, const ITargetPlatform *TargetPlatform, TRefCountPtr< FMaterialShaderMap > &InOutShaderMap, FString &OutDDCKeyDesc)
Begin an attempts to load the shader map for the given material from the Derived Data Cache.
static FMaterialShaderMap * FindCompilingShaderMap (uint32 CompilingId)
static TRefCountPtr< FMaterialShaderMap > FindId (const FMaterialShaderMapId &ShaderMapId, EShaderPlatform Platform)
Finds the shader map for a material.
static void GetAllOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes)
Gets outdated types from all loaded material shader maps.
static void LoadForRemoteRecompile (FArchive &Ar, EShaderPlatform ShaderPlatform, TArray< UMaterialInterface * > &OutLoadedMaterials)
static void LoadFromDerivedDataCache (const FMaterial *Material, const FMaterialShaderMapId &ShaderMapId, EShaderPlatform Platform, const ITargetPlatform *TargetPlatform, TRefCountPtr< FMaterialShaderMap > &InOutShaderMap, FString &OutDDCKeyDesc)
Attempts to load the shader map for the given material from the Derived Data Cache.
static void SaveForRemoteRecompile (FArchive &Ar, const TMap< FString, TArray< TRefCountPtr< FMaterialShaderMap > > > &CompiledShaderMaps)
Serializes a shader map to an archive (used with recompiling shaders for a remote console)
Data Fields
bool bool bool bInlineShaderCode = false
bool bInlineShaderResources = true
bool bool bLoadingCooked = false
bool bool bool const FName & SerializingAsset = NAME_None)
Protected Member Functions
void AddCompilingMaterialExternalDependency ()
void CheckReleaseCompilingId ()
void PostFinalizeContent () override
void RemoveCompilingMaterialExternalDependency ()
Protected Member Functions inherited from TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >
virtual FShaderMapPointerTable * CreatePointerTable () const final override
virtual const FTypeLayoutDesc & GetContentTypeDesc () const final override
Protected Member Functions inherited from FShaderMapBase
RENDERCORE_API FShaderMapBase ()
RENDERCORE_API void AssignCopy (const FShaderMapBase &Source)
RENDERCORE_API void DestroyContent ()
RENDERCORE_API void InitResource ()
Private Member Functions
FShader * ProcessCompilationResultsForSingleJob (class FShaderCompileJob *SingleJob, const FShaderPipelineType *ShaderPipeline, const FSHAHash &MaterialShaderMapHash)
Static Private Member Functions
static void ShaderMapResourceExplicitRelease (const FShaderMapResource *ShaderMapResource)
Iterate over global MaterialShaderMap cache and remove MaterialShaderMap which reference FShaderMapResource argument.
Private Attributes
uint32 bCompilationFinalized: 1
Indicates whether this shader map has had ProcessCompilationResults called after Compile.
uint32 bCompiledSuccessfully: 1
bool bDeletedThroughDeferredCleanup
Used to catch errors where the shader map is deleted directly.
uint32 bIsFromODSC: 1
Indicates whether the shader map is from ODSC.
uint32 bIsPersistent: 1
Indicates whether the shader map should be stored in the shader cache.
uint32 bRegistered: 1
Indicates whether this shader map has been registered in GIdToMaterialShaderMap.
float CompileTime
uint32 CompilingId = 0
Tracks material resources and their shader maps that need to be compiled but whose compilation is being deferred.
TArray< TRefCountPtr< FMaterial > > CompilingMaterialDependencies
int32 CompilingMaterialNumExternalDependencies = 0
TRefCountPtr< FMaterialShaderMap > FinalizedClone
TMap< uint32, TPair< FString, TSharedPtr< FShaderCompileJobStatus > > > InFlightJobs
int32 NumRefs
TRefCountPtr< FSharedShaderCompilerEnvironment > PendingCompilerEnvironment
FMaterialShaderMapId ShaderMapId
The static parameter set that this shader map was compiled with and other parameters unique to this shadermap.
FUniformBufferLayoutRHIRef UniformBufferLayout
Static Private Attributes
static TArray< FMaterialShaderMap * > AllMaterialShaderMaps
All material shader maps in memory.
static FCriticalSection AllMaterialShaderMapsGuard
Guards access to AllMaterialShaderMaps, which can be written to from an async loading thread.
static TMap< FMaterialShaderMapId, FMaterialShaderMap * > GIdToMaterialShaderMap [SP_NumPlatforms]
A global map from a material's static parameter set to any shader map cached for that material.
static FCriticalSection GIdToMaterialShaderMapCS
Friends
void DumpMaterialStats (EShaderPlatform Platform)
Dump material stats for a given platform.
class FShaderCompilingManager
class UE::Cook::FODSCClientData
Detailed Description
The set of material shaders for a single material.
Definition at line 1440 of file MaterialShared.h.
Member Typedef Documentation
FLWCUsagesArray
using FMaterialShaderMap::FLWCUsagesArray = TStaticArray<uint16, (int)ELWCFunctionKind::Max>
Definition at line 1670 of file MaterialShared.h.
Super
using FMaterialShaderMap::Super = TShaderMap<FMaterialShaderMapContent, FShaderMapPointerTable>
Definition at line 1443 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialShaderMap()
FMaterialShaderMap::FMaterialShaderMap ()
Referenced by AcquireFinalizedClone(), FindCompilingShaderMap(), and GetFinalizedClone().
~FMaterialShaderMap()
virtual FMaterialShaderMap::~FMaterialShaderMap () virtual
Member Function Documentation
AcquireCompilingId()
uint32 FMaterialShaderMap::AcquireCompilingId (const TRefCountPtr< FSharedShaderCompilerEnvironment > & InMaterialEnvironment)
AcquireFinalizedClone()
FMaterialShaderMap * FMaterialShaderMap::AcquireFinalizedClone ()
References FMaterialShaderMap().
AcquireMeshShaderMap() [1/2]
FMeshMaterialShaderMap * FMaterialShaderMap::AcquireMeshShaderMap (const FHashedName & VertexFactoryTypeName) inline
Definition at line 1611 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetMutableContent().
AcquireMeshShaderMap() [2/2]
FMeshMaterialShaderMap * FMaterialShaderMap::AcquireMeshShaderMap (const FVertexFactoryType * VertexFactoryType) inline
Definition at line 1610 of file MaterialShared.h.
References FVertexFactoryType::GetHashedName(), and TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetMutableContent().
AddCompilingDependency()
void FMaterialShaderMap::AddCompilingDependency (FMaterial * Material)
References Material.
AddCompilingMaterialExternalDependency()
void FMaterialShaderMap::AddCompilingMaterialExternalDependency () inline protected
Definition at line 1735 of file MaterialShared.h.
References check, CompilingMaterialNumExternalDependencies, and IsInGameThread().
AddRef()
void FMaterialShaderMap::AddRef ()
AppendCompileStateDebugInfo()
void FMaterialShaderMap::AppendCompileStateDebugInfo (FStringBuilderBase & OutDebugInfo) const
BeginLoadFromDerivedDataCache()
TSharedRef< FAsyncLoadContext > FMaterialShaderMap::BeginLoadFromDerivedDataCache (const FMaterial * Material, const FMaterialShaderMapId & ShaderMapId, EShaderPlatform Platform, const ITargetPlatform * TargetPlatform, TRefCountPtr< FMaterialShaderMap > & InOutShaderMap, FString & OutDDCKeyDesc) static
Begin an attempts to load the shader map for the given material from the Derived Data Cache.
If InOutShaderMap is valid, attempts to load the individual missing shaders instead. Returns (via OutDDCKeyDesc parameter) a helpful string to debug the DDC key and parameters
References Material, Platform, and ShaderMapId.
CheckReleaseCompilingId()
void FMaterialShaderMap::CheckReleaseCompilingId () protected
Referenced by RemoveCompilingMaterialExternalDependency().
CollectPSOPrecacheData()
FPSOPrecacheDataArray FMaterialShaderMap::CollectPSOPrecacheData (const FMaterialPSOPrecacheParams & PrecacheParams)
Collect all possible PSO's which can be used with this material shader map for given parameters.
Compile()
void FMaterialShaderMap::Compile (FMaterial * Material, const FMaterialShaderMapId & ShaderMapId, const TRefCountPtr< FSharedShaderCompilerEnvironment > & MaterialEnvironment, const FMaterialCompilationOutput & InMaterialCompilationOutput, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode)
Compiles the shaders for a material and caches them in this shader map.
Parameters
Material - The material to compile shaders for.
ShaderMapId - the set of static parameters to compile for
Platform - The platform to compile to
References Material, Platform, and ShaderMapId.
CompiledSuccessfully()
bool FMaterialShaderMap::CompiledSuccessfully () const inline
Definition at line 1623 of file MaterialShared.h.
References bCompiledSuccessfully.
CountNumShaders()
void FMaterialShaderMap::CountNumShaders (int32 & NumShaders, int32 & NumPipelines) const inline
Definition at line 1711 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
DumpDebugInfo()
void FMaterialShaderMap::DumpDebugInfo (FOutputDevice & OutputDevice) const
DumpShaderList()
virtual void FMaterialShaderMap::DumpShaderList (FShaderListReport & Out) const virtual
Reimplemented from FShaderMapBase.
FindCompilingShaderMap()
FMaterialShaderMap * FMaterialShaderMap::FindCompilingShaderMap (uint32 CompilingId) static
References FMaterialShaderMap(), and CompilingId.
FindId()
TRefCountPtr< FMaterialShaderMap > FMaterialShaderMap::FindId (const FMaterialShaderMapId & ShaderMapId, EShaderPlatform Platform) static
Finds the shader map for a material.
Parameters
ShaderMapId - The static parameter set and other properties identifying the shader map
Platform - The platform to lookup for
Returns
NULL if no cached shader map was found.
References Platform, and ShaderMapId.
GetAllOutdatedTypes()
void FMaterialShaderMap::GetAllOutdatedTypes (TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) static
Gets outdated types from all loaded material shader maps.
GetCompilingId()
uint32 FMaterialShaderMap::GetCompilingId () const inline
Definition at line 1618 of file MaterialShared.h.
References CompilingId.
GetDebugDescription()
const TCHAR * FMaterialShaderMap::GetDebugDescription () const inline
Definition at line 1641 of file MaterialShared.h.
References TEXT.
GetEstimatedLWCFuncUsageComplexity()
void FMaterialShaderMap::GetEstimatedLWCFuncUsageComplexity (uint32 & LWCComplexityVS, uint32 & LWCComplexityPS, uint32 & LWCComplexityCS) const
GetEstimatedLWCFuncUsages()
void FMaterialShaderMap::GetEstimatedLWCFuncUsages (FLWCUsagesArray & UsagesVS, FLWCUsagesArray & UsagesPS, FLWCUsagesArray & UsagesCS) const inline
Definition at line 1671 of file MaterialShared.h.
References CopyAssignItems(), TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent(), and TStaticArray< InElementType, NumElements, Alignment >::GetData().
GetEstimatedNumTextureSamples()
void FMaterialShaderMap::GetEstimatedNumTextureSamples (uint32 & VSSamples, uint32 & PSSamples) const inline
Definition at line 1668 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetEstimatedNumVirtualTextureLookups()
uint32 FMaterialShaderMap::GetEstimatedNumVirtualTextureLookups () const inline
Definition at line 1669 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetFinalizedClone()
FMaterialShaderMap * FMaterialShaderMap::GetFinalizedClone () const
References FMaterialShaderMap().
GetFriendlyName()
const TCHAR * FMaterialShaderMap::GetFriendlyName () const inline
Definition at line 1640 of file MaterialShared.h.
References TEXT.
Referenced by IsValidForRendering().
GetMaterialPath()
const TCHAR * FMaterialShaderMap::GetMaterialPath () const inline
Definition at line 1642 of file MaterialShared.h.
References TEXT.
GetMaxNumInstructionsForShader()
uint32 FMaterialShaderMap::GetMaxNumInstructionsForShader (FShaderType * ShaderType) const inline
Definition at line 1505 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetMaxTextureSamplers()
uint32 FMaterialShaderMap::GetMaxTextureSamplers () const
Returns the maximum number of texture samplers used by any shader in this shader map.
GetMeshShaderMap() [1/2]
const FMeshMaterialShaderMap * FMaterialShaderMap::GetMeshShaderMap (const FHashedName & VertexFactoryTypeName) const inline
Definition at line 1609 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetMeshShaderMap() [2/2]
const FMeshMaterialShaderMap * FMaterialShaderMap::GetMeshShaderMap (const FVertexFactoryType * VertexFactoryType) const inline
Definition at line 1608 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent(), and FVertexFactoryType::GetHashedName().
GetNumPreshaders()
uint32 FMaterialShaderMap::GetNumPreshaders () const inline
Definition at line 1678 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetNumRefs()
int32 FMaterialShaderMap::GetNumRefs () const inline
Definition at line 1708 of file MaterialShared.h.
References NumRefs.
GetNumUsedCustomInterpolatorScalars()
uint32 FMaterialShaderMap::GetNumUsedCustomInterpolatorScalars () const inline
Definition at line 1667 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetNumUsedUVScalars()
uint32 FMaterialShaderMap::GetNumUsedUVScalars () const inline
Definition at line 1666 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetNumVirtualTextureStacks()
uint32 FMaterialShaderMap::GetNumVirtualTextureStacks () const inline
Definition at line 1680 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetOutdatedTypes()
void FMaterialShaderMap::GetOutdatedTypes (TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) const
GetPendingCompilerEnvironment()
const TRefCountPtr< FSharedShaderCompilerEnvironment > & FMaterialShaderMap::GetPendingCompilerEnvironment () const inline
Definition at line 1619 of file MaterialShared.h.
References PendingCompilerEnvironment.
GetRefCount()
int32 FMaterialShaderMap::GetRefCount () const inline
Definition at line 1709 of file MaterialShared.h.
References NumRefs.
GetResolutionRelativeToInput()
FScriptName FMaterialShaderMap::GetResolutionRelativeToInput () const inline
Definition at line 1686 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetRuntimeVirtualTextureOutputAttributeMask()
uint8 FMaterialShaderMap::GetRuntimeVirtualTextureOutputAttributeMask () const inline
Definition at line 1681 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetShader() [1/3]
template<typename ShaderType> TShaderRef< ShaderType > FMaterialShaderMap::GetShader (const typename ShaderType::FPermutationDomain & PermutationVector) const inline
Definition at line 1500 of file MaterialShared.h.
References TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), and GetShader().
GetShader() [2/3]
TShaderRef< FShader > FMaterialShaderMap::GetShader (FShaderType * ShaderType, int32 PermutationId = 0) const inline
Definition at line 1491 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
Referenced by GetShader(), and GetShader().
GetShader() [3/3]
template<typename ShaderType> TShaderRef< ShaderType > FMaterialShaderMap::GetShader (int32 PermutationId = 0) const inline
Definition at line 1496 of file MaterialShared.h.
References TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), and GetShader().
GetShaderContentHash()
const FSHAHash & FMaterialShaderMap::GetShaderContentHash () const inline
Definition at line 1613 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetShaderList() [1/2]
virtual void FMaterialShaderMap::GetShaderList (TMap< FHashedName, TShaderRef< FShader > > & OutShaders) const override virtual
Builds a list of the shaders in a shader map.
Key is FShaderType::TypeName
Implements FShaderMapBase.
GetShaderList() [2/2]
void FMaterialShaderMap::GetShaderList (TMap< FShaderId, TShaderRef< FShader > > & OutShaders) const
Builds a list of the shaders in a shader map.
GetShaderMapId()
const FMaterialShaderMapId & FMaterialShaderMap::GetShaderMapId () const inline
Definition at line 1612 of file MaterialShared.h.
References ShaderMapId.
GetShaderNum()
uint32 FMaterialShaderMap::GetShaderNum () const
Number of Shaders in Shadermap.
GetShaderPipelineList()
virtual void FMaterialShaderMap::GetShaderPipelineList (TArray< FShaderPipelineRef > & OutShaderPipelines) const override virtual
Builds a list of the shader pipelines in a shader map.
Implements FShaderMapBase.
GetShaderSource()
const FMemoryImageString * FMaterialShaderMap::GetShaderSource (const FVertexFactoryType * VertexFactoryType, const FShaderType * ShaderType, int32 PermutationId) const
GetSubstrateClosureCount()
uint8 FMaterialShaderMap::GetSubstrateClosureCount () const inline
Definition at line 1661 of file MaterialShared.h.
References GetSubstrateMaterialCompilationOutput().
GetSubstrateMaterialCompilationOutput()
const FSubstrateMaterialCompilationOutput & FMaterialShaderMap::GetSubstrateMaterialCompilationOutput () const inline
Definition at line 1659 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
Referenced by GetSubstrateClosureCount(), GetSubstrateMaterialType(), GetSubstrateUintPerPixel(), and GetSubstrateUsesComplexSpecialRenderPath().
GetSubstrateMaterialType()
uint8 FMaterialShaderMap::GetSubstrateMaterialType () const inline
Definition at line 1660 of file MaterialShared.h.
References GetSubstrateMaterialCompilationOutput().
GetSubstrateUintPerPixel()
uint8 FMaterialShaderMap::GetSubstrateUintPerPixel () const inline
Definition at line 1662 of file MaterialShared.h.
References GetSubstrateMaterialCompilationOutput().
GetSubstrateUsesComplexSpecialRenderPath()
bool FMaterialShaderMap::GetSubstrateUsesComplexSpecialRenderPath () const inline
Definition at line 1663 of file MaterialShared.h.
References GetSubstrateMaterialCompilationOutput().
GetUniformBufferLayout()
const FRHIUniformBufferLayout * FMaterialShaderMap::GetUniformBufferLayout () const inline
Definition at line 1706 of file MaterialShared.h.
References UniformBufferLayout.
GetUniformExpressionSet()
const FUniformExpressionSet & FMaterialShaderMap::GetUniformExpressionSet () const inline
Definition at line 1705 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetUserSceneTextureInputs()
TConstArrayView< FScriptName > FMaterialShaderMap::GetUserSceneTextureInputs () const inline
Definition at line 1683 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetUserSceneTextureOutput()
FScriptName FMaterialShaderMap::GetUserSceneTextureOutput () const inline
Definition at line 1684 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetUserTextureDivisor()
FIntPoint FMaterialShaderMap::GetUserTextureDivisor () const inline
Definition at line 1685 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
InitalizeForODSC()
void FMaterialShaderMap::InitalizeForODSC (EShaderPlatform TargetShaderPlatform, const FMaterialCompilationOutput & NewCompilationOutput)
IsCompilationFinalized()
bool FMaterialShaderMap::IsCompilationFinalized () const inline
Definition at line 1622 of file MaterialShared.h.
References bCompilationFinalized.
IsComplete()
bool FMaterialShaderMap::IsComplete (const FMaterial * Material, bool bSilent)
Checks whether the material shader map is missing any shader types necessary for the given material.
Parameters
Material - The material which is checked.
Returns
True if the shader map has all of the shader types necessary.
References Material.
IsLightFunctionAtlasCompatible()
bool FMaterialShaderMap::IsLightFunctionAtlasCompatible () const inline
Definition at line 1657 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
IsValidForRendering()
bool FMaterialShaderMap::IsValidForRendering (bool bFailOnInvalid = false) const inline
Definition at line 1690 of file MaterialShared.h.
References bCompilationFinalized, bCompiledSuccessfully, bDeletedThroughDeferredCleanup, checkf, GetFriendlyName(), FShaderMapBase::GetFrozenContentSize(), and TEXT.
LoadForRemoteRecompile()
void FMaterialShaderMap::LoadForRemoteRecompile (FArchive & Ar, EShaderPlatform ShaderPlatform, TArray< UMaterialInterface * > & OutLoadedMaterials) static
References Ar, and ShaderPlatform.
LoadFromDerivedDataCache()
void FMaterialShaderMap::LoadFromDerivedDataCache (const FMaterial * Material, const FMaterialShaderMapId & ShaderMapId, EShaderPlatform Platform, const ITargetPlatform * TargetPlatform, TRefCountPtr< FMaterialShaderMap > & InOutShaderMap, FString & OutDDCKeyDesc) static
Attempts to load the shader map for the given material from the Derived Data Cache.
If InOutShaderMap is valid, attempts to load the individual missing shaders instead. Returns (via OutDDCKeyDesc parameter) a helpful string to debug the DDC key and parameters
References Material, Platform, and ShaderMapId.
LoadMissingShadersFromMemory()
void FMaterialShaderMap::LoadMissingShadersFromMemory (const FMaterial * Material)
Attempts to load missing shaders from memory.
References Material.
ModifiesMeshPosition()
bool FMaterialShaderMap::ModifiesMeshPosition () const inline
Definition at line 1651 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
NeedsGBuffer()
bool FMaterialShaderMap::NeedsGBuffer () const inline
Definition at line 1649 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
NeedsSceneTextures()
bool FMaterialShaderMap::NeedsSceneTextures () const inline
Definition at line 1645 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
PostFinalizeContent()
void FMaterialShaderMap::PostFinalizeContent () override protected virtual
Reimplemented from FShaderMapBase.
ProcessCompilationResults()
void FMaterialShaderMap::ProcessCompilationResults (const TArray< TRefCountPtr< FShaderCommonCompileJob > > & ICompilationResults, int32 & InOutJobIndex, float & TimeBudget)
Sorts the incoming compiled jobs into the appropriate mesh shader maps.
ProcessCompilationResultsForSingleJob()
FShader * FMaterialShaderMap::ProcessCompilationResultsForSingleJob (class FShaderCompileJob * SingleJob, const FShaderPipelineType * ShaderPipeline, const FSHAHash & MaterialShaderMapHash) private
Register()
void FMaterialShaderMap::Register (EShaderPlatform InShaderPlatform)
Registers a material shader map in the global map so it can be used by materials.
RegisterForODSC()
void FMaterialShaderMap::RegisterForODSC (EShaderPlatform InShaderPlatform)
Registers a material shader map in the global map so it can be used by materials.
Since the shader maps content can change this will overwrite entries in the global map.
Release()
void FMaterialShaderMap::Release ()
ReleaseCompilingId()
void FMaterialShaderMap::ReleaseCompilingId ()
RemoveCompilingDependency()
void FMaterialShaderMap::RemoveCompilingDependency (FMaterial * Material)
References bIsFromODSC, and Material.
RemoveCompilingMaterialExternalDependency()
void FMaterialShaderMap::RemoveCompilingMaterialExternalDependency () inline protected
Definition at line 1736 of file MaterialShared.h.
References check, CheckReleaseCompilingId(), CompilingMaterialNumExternalDependencies, and IsInGameThread().
RequiresSceneColorCopy()
bool FMaterialShaderMap::RequiresSceneColorCopy () const inline
Definition at line 1644 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
SaveForRemoteRecompile()
void FMaterialShaderMap::SaveForRemoteRecompile (FArchive & Ar, const TMap< FString, TArray< TRefCountPtr< FMaterialShaderMap > > > & CompiledShaderMaps) static
Serializes a shader map to an archive (used with recompiling shaders for a remote console)
References Ar.
SaveShaderStableKeys()
void FMaterialShaderMap::SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue & SaveKeyVal)
SaveToDerivedDataCache()
void FMaterialShaderMap::SaveToDerivedDataCache (const FMaterialShaderParameters & ShaderParameters)
Saves this shader map to the derived data cache.
Serialize()
bool FMaterialShaderMap::Serialize (FShaderSerializeContext & Ctx)
Serializes the shader map.
References Serialize().
Referenced by Serialize().
SetCompiledSuccessfully()
void FMaterialShaderMap::SetCompiledSuccessfully (bool bSuccess) inline
Definition at line 1625 of file MaterialShared.h.
References bCompiledSuccessfully.
ShaderMapResourceExplicitRelease()
void FMaterialShaderMap::ShaderMapResourceExplicitRelease (const FShaderMapResource * ShaderMapResource) static private
Iterate over global MaterialShaderMap cache and remove MaterialShaderMap which reference FShaderMapResource argument.
SubmitCompileJobs()
int32 FMaterialShaderMap::SubmitCompileJobs (uint32 CompilingShaderMapId, const FMaterial * Material, const TRefCountPtr< FSharedShaderCompilerEnvironment > & MaterialEnvironment, EShaderCompileJobPriority Priority) const
Submits compile jobs for this shadermap, returns number of jobs submitted.
References Material.
UE_DEPRECATED()
FMaterialShaderMap::UE_DEPRECATED (5. 5, "Please use overload accepting an FShaderSerializeContext. Note that inlining of shader code into runtime shadermaps is no longer supported. If you rely on this please reach out to the UE rendering team.") &
UsesAnisotropy()
bool FMaterialShaderMap::UsesAnisotropy () const inline
Definition at line 1656 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesDisplacement()
bool FMaterialShaderMap::UsesDisplacement () const inline
Definition at line 1648 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesDistanceCullFade()
bool FMaterialShaderMap::UsesDistanceCullFade () const inline
Definition at line 1655 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesEyeAdaptation()
bool FMaterialShaderMap::UsesEyeAdaptation () const inline
Definition at line 1650 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesGlobalDistanceField()
bool FMaterialShaderMap::UsesGlobalDistanceField () const inline
Definition at line 1646 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesPathTracingBufferTexture()
bool FMaterialShaderMap::UsesPathTracingBufferTexture (uint32 TexId) const inline
Definition at line 1688 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesPixelDepthOffset()
bool FMaterialShaderMap::UsesPixelDepthOffset () const inline
Definition at line 1652 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesSceneDepthLookup()
bool FMaterialShaderMap::UsesSceneDepthLookup () const inline
Definition at line 1653 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesSceneTexture()
bool FMaterialShaderMap::UsesSceneTexture (uint32 TexId) const inline
Definition at line 1682 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesVelocitySceneTexture()
bool FMaterialShaderMap::UsesVelocitySceneTexture () const inline
Definition at line 1654 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
UsesWorldPositionOffset()
bool FMaterialShaderMap::UsesWorldPositionOffset () const inline
Definition at line 1647 of file MaterialShared.h.
References TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
Friends And Related Symbol Documentation
DumpMaterialStats
void DumpMaterialStats (EShaderPlatform Platform) friend
Dump material stats for a given platform.
Parameters
Platform Platform to dump stats for.
References Platform.
FShaderCompilingManager
friend class FShaderCompilingManager friend
Definition at line 1823 of file MaterialShared.h.
References FShaderCompilingManager.
Referenced by FShaderCompilingManager.
UE::Cook::FODSCClientData
friend class UE::Cook::FODSCClientData friend
Definition at line 1824 of file MaterialShared.h.
Field Documentation
AllMaterialShaderMaps
TArray<FMaterialShaderMap*> FMaterialShaderMap::AllMaterialShaderMaps static private
All material shader maps in memory.
No ref counting needed as these are removed on destruction of the shader map.
Definition at line 1756 of file MaterialShared.h.
AllMaterialShaderMapsGuard
FCriticalSection FMaterialShaderMap::AllMaterialShaderMapsGuard static private
Guards access to AllMaterialShaderMaps, which can be written to from an async loading thread.
Definition at line 1759 of file MaterialShared.h.
bCompilationFinalized
uint32 FMaterialShaderMap::bCompilationFinalized private
Indicates whether this shader map has had ProcessCompilationResults called after Compile.
The shader map must not be used on the rendering thread unless bCompilationFinalized is true.
Definition at line 1798 of file MaterialShared.h.
Referenced by IsCompilationFinalized(), and IsValidForRendering().
bCompiledSuccessfully
uint32 FMaterialShaderMap::bCompiledSuccessfully private
Definition at line 1800 of file MaterialShared.h.
Referenced by CompiledSuccessfully(), IsValidForRendering(), and SetCompiledSuccessfully().
bDeletedThroughDeferredCleanup
bool FMaterialShaderMap::bDeletedThroughDeferredCleanup private
Used to catch errors where the shader map is deleted directly.
Definition at line 1789 of file MaterialShared.h.
Referenced by IsValidForRendering().
bInlineShaderCode
bool bool bool FMaterialShaderMap::bInlineShaderCode = false
Definition at line 1585 of file MaterialShared.h.
bInlineShaderResources
bool FMaterialShaderMap::bInlineShaderResources = true
Definition at line 1585 of file MaterialShared.h.
bIsFromODSC
uint32 FMaterialShaderMap::bIsFromODSC private
Indicates whether the shader map is from ODSC.
Definition at line 1806 of file MaterialShared.h.
Referenced by RemoveCompilingDependency().
bIsPersistent
uint32 FMaterialShaderMap::bIsPersistent private
Indicates whether the shader map should be stored in the shader cache.
Definition at line 1803 of file MaterialShared.h.
bLoadingCooked
bool bool FMaterialShaderMap::bLoadingCooked = false
Definition at line 1585 of file MaterialShared.h.
bRegistered
uint32 FMaterialShaderMap::bRegistered private
Indicates whether this shader map has been registered in GIdToMaterialShaderMap.
Definition at line 1792 of file MaterialShared.h.
CompileTime
float FMaterialShaderMap::CompileTime private
Definition at line 1772 of file MaterialShared.h.
CompilingId
uint32 FMaterialShaderMap::CompilingId = 0 private
Tracks material resources and their shader maps that need to be compiled but whose compilation is being deferred.
Uniquely identifies this shader map during compilation, needed for deferred compilation where shaders from multiple shader maps are compiled together.
Definition at line 1783 of file MaterialShared.h.
Referenced by FindCompilingShaderMap(), and GetCompilingId().
CompilingMaterialDependencies
TArray<TRefCountPtr<FMaterial> > FMaterialShaderMap::CompilingMaterialDependencies private
Definition at line 1765 of file MaterialShared.h.
CompilingMaterialNumExternalDependencies
int32 FMaterialShaderMap::CompilingMaterialNumExternalDependencies = 0 private
Definition at line 1766 of file MaterialShared.h.
Referenced by AddCompilingMaterialExternalDependency(), and RemoveCompilingMaterialExternalDependency().
FinalizedClone
TRefCountPtr<FMaterialShaderMap> FMaterialShaderMap::FinalizedClone private
Definition at line 1763 of file MaterialShared.h.
GIdToMaterialShaderMap
TMap<FMaterialShaderMapId,FMaterialShaderMap*> FMaterialShaderMap::GIdToMaterialShaderMap[SP_NumPlatforms] static private
A global map from a material's static parameter set to any shader map cached for that material.
Note: this does not necessarily contain all material shader maps in memory. Shader maps with the same key can evict each other. No ref counting needed as these are removed on destruction of the shader map.
Definition at line 1748 of file MaterialShared.h.
GIdToMaterialShaderMapCS
FCriticalSection FMaterialShaderMap::GIdToMaterialShaderMapCS static private
Definition at line 1749 of file MaterialShared.h.
InFlightJobs
TMap<uint32, TPair<FString, TSharedPtr<FShaderCompileJobStatus> > > FMaterialShaderMap::InFlightJobs mutable private
Definition at line 1816 of file MaterialShared.h.
NumRefs
int32 FMaterialShaderMap::NumRefs mutable private
Definition at line 1786 of file MaterialShared.h.
Referenced by GetNumRefs(), and GetRefCount().
PendingCompilerEnvironment
TRefCountPtr<FSharedShaderCompilerEnvironment> FMaterialShaderMap::PendingCompilerEnvironment private
Definition at line 1764 of file MaterialShared.h.
Referenced by GetPendingCompilerEnvironment().
SerializingAsset
bool bool bool const FName& FMaterialShaderMap::SerializingAsset = NAME_None)
Definition at line 1585 of file MaterialShared.h.
ShaderMapId
FMaterialShaderMapId FMaterialShaderMap::ShaderMapId private
The static parameter set that this shader map was compiled with and other parameters unique to this shadermap.
Definition at line 1776 of file MaterialShared.h.
Referenced by BeginLoadFromDerivedDataCache(), Compile(), FindId(), GetShaderMapId(), and LoadFromDerivedDataCache().
UniformBufferLayout
FUniformBufferLayoutRHIRef FMaterialShaderMap::UniformBufferLayout private
Definition at line 1769 of file MaterialShared.h.
Referenced by GetUniformBufferLayout().
The documentation for this class was generated from the following file:
MaterialShared.h