Unreal Engine 5.6 C++ API: Metasound::Frontend::IEnumDataTypeInterface Struct Reference
Metasound::Frontend::IEnumDataTypeInterface Struct Reference abstract
Interface for metadata of a registered MetaSound enum type.
#include "MetasoundFrontendDataTypeRegistry.h"
Public Types
using FGenericInt32Entry = TEnumEntry<int32>
Public Member Functions
virtual ~IEnumDataTypeInterface ()=default
TOptional< FGenericInt32Entry > FindByName (FName InEnumName) const
TOptional< FGenericInt32Entry > FindByValue (int32 InEnumValue) const
template<typename Predicate>
TOptional< FGenericInt32Entry > FindEntryBy (Predicate Pred) const
virtual const TArray< FGenericInt32Entry > & GetAllEntries () const =0
virtual int32 GetDefaultValue () const =0
virtual FName GetNamespace () const =0
TOptional< FName > ToName (int32 InEnumValue) const
TOptional< int32 > ToValue (FName InName) const
Detailed Description
Interface for metadata of a registered MetaSound enum type.
Definition at line 91 of file MetasoundFrontendDataTypeRegistry.h.
Member Typedef Documentation
FGenericInt32Entry
using Metasound::Frontend::IEnumDataTypeInterface::FGenericInt32Entry = TEnumEntry<int32>
Definition at line 93 of file MetasoundFrontendDataTypeRegistry.h.
Constructor & Destructor Documentation
~IEnumDataTypeInterface()
virtual Metasound::Frontend::IEnumDataTypeInterface::~IEnumDataTypeInterface () virtual default
Member Function Documentation
FindByName()
TOptional< FGenericInt32Entry > Metasound::Frontend::IEnumDataTypeInterface::FindByName (FName InEnumName) const inline
Definition at line 115 of file MetasoundFrontendDataTypeRegistry.h.
References FindEntryBy(), and Metasound::TEnumEntry< T >::Name.
Referenced by ToValue().
FindByValue()
TOptional< FGenericInt32Entry > Metasound::Frontend::IEnumDataTypeInterface::FindByValue (int32 InEnumValue) const inline
Definition at line 111 of file MetasoundFrontendDataTypeRegistry.h.
References FindEntryBy(), and Metasound::TEnumEntry< T >::Value.
Referenced by ToName().
FindEntryBy()
template<typename Predicate> TOptional< FGenericInt32Entry > Metasound::Frontend::IEnumDataTypeInterface::FindEntryBy (Predicate Pred) const inline
Definition at line 102 of file MetasoundFrontendDataTypeRegistry.h.
References TArray< InElementType, InAllocatorType >::FindByPredicate(), Found, GetAllEntries(), and Predicate.
Referenced by FindByName(), and FindByValue().
GetAllEntries()
virtual const TArray< FGenericInt32Entry > & Metasound::Frontend::IEnumDataTypeInterface::GetAllEntries () const pure virtual
Referenced by FindEntryBy().
GetDefaultValue()
virtual int32 Metasound::Frontend::IEnumDataTypeInterface::GetDefaultValue () const pure virtual
GetNamespace()
virtual FName Metasound::Frontend::IEnumDataTypeInterface::GetNamespace () const pure virtual
ToName()
TOptional< FName > Metasound::Frontend::IEnumDataTypeInterface::ToName (int32 InEnumValue) const inline
Definition at line 119 of file MetasoundFrontendDataTypeRegistry.h.
References FindByValue().
ToValue()
TOptional< int32 > Metasound::Frontend::IEnumDataTypeInterface::ToValue (FName InName) const inline
Definition at line 127 of file MetasoundFrontendDataTypeRegistry.h.
References FindByName(), and InName.
The documentation for this struct was generated from the following file:
MetasoundFrontendDataTypeRegistry.h