Unreal Engine 5.6 C++ API: FPropertyBagArrayRef Class Reference
FPropertyBagArrayRef Class Reference
A reference to an array in FInstancedPropertyBag Allows to modify the array via the FScriptArrayHelper API, and contains helper methods to get and set properties.
#include "PropertyBag.h"
Public Member Functions
FORCEINLINE FPropertyBagArrayRef (const FPropertyBagPropertyDesc &InDesc, const void *InArray)
TValueOrError< FPropertyBagArrayRef, EPropertyBagResult > GetMutableNestedArrayRef (const int32 Index=0) const
Returns helper class to modify and access a nested array (mutable version).
TValueOrError< const FPropertyBagArrayRef, EPropertyBagResult > GetNestedArrayRef (const int32 Index=0) const
Returns helper class to access a nested array (const version).
TValueOrError< bool, EPropertyBagResult > GetValueBool (const int32 Index) const
Getters Numeric types (bool, (u)int32, (u)int64, float, double) support type conversion.
TValueOrError< uint8, EPropertyBagResult > GetValueByte (const int32 Index) const
TValueOrError< UClass *, EPropertyBagResult > GetValueClass (const int32 Index) const
TValueOrError< double, EPropertyBagResult > GetValueDouble (const int32 Index) const
template<typename T>
TValueOrError< T, EPropertyBagResult > GetValueEnum (const int32 Index) const
TValueOrError< uint8, EPropertyBagResult > GetValueEnum (const int32 Index, const UEnum *RequestedEnum) const
TValueOrError< float, EPropertyBagResult > GetValueFloat (const int32 Index) const
TValueOrError< int32, EPropertyBagResult > GetValueInt32 (const int32 Index) const
TValueOrError< int64, EPropertyBagResult > GetValueInt64 (const int32 Index) const
TValueOrError< FName, EPropertyBagResult > GetValueName (const int32 Index) const
template<typename T>
TValueOrError< T *, EPropertyBagResult > GetValueObject (const int32 Index) const
TValueOrError< UObject *, EPropertyBagResult > GetValueObject (const int32 Index, const UClass *RequestedClass=nullptr) const
TValueOrError< FSoftObjectPath, EPropertyBagResult > GetValueSoftPath (const int32 Index) const
TValueOrError< FString, EPropertyBagResult > GetValueString (const int32 Index) const
template<typename T>
TValueOrError< T *, EPropertyBagResult > GetValueStruct (const int32 Index) const
TValueOrError< FStructView, EPropertyBagResult > GetValueStruct (const int32 Index, const UScriptStruct *RequestedStruct=nullptr) const
TValueOrError< FText, EPropertyBagResult > GetValueText (const int32 Index) const
TValueOrError< uint32, EPropertyBagResult > GetValueUInt32 (const int32 Index) const
TValueOrError< uint64, EPropertyBagResult > GetValueUInt64 (const int32 Index) const
EPropertyBagResult SetValueBool (const int32 Index, const bool bInValue)
Value Setters.
EPropertyBagResult SetValueByte (const int32 Index, const uint8 InValue)
EPropertyBagResult SetValueClass (const int32 Index, UClass *InValue)
EPropertyBagResult SetValueDouble (const int32 Index, const double InValue)
template<typename T>
EPropertyBagResult SetValueEnum (const int32 Index, const T InValue)
Sets enum value specified type.
EPropertyBagResult SetValueEnum (const int32 Index, const uint8 InValue, const UEnum *Enum)
EPropertyBagResult SetValueFloat (const int32 Index, const float InValue)
EPropertyBagResult SetValueInt32 (const int32 Index, const int32 InValue)
EPropertyBagResult SetValueInt64 (const int32 Index, const int64 InValue)
EPropertyBagResult SetValueName (const int32 Index, const FName InValue)
template<typename T>
EPropertyBagResult SetValueObject (const int32 Index, T *InValue)
Sets object pointer value specified type.
EPropertyBagResult SetValueObject (const int32 Index, UObject *InValue)
EPropertyBagResult SetValueSoftPath (const int32 Index, const FSoftObjectPath &InValue)
EPropertyBagResult SetValueSoftPath (const int32 Index, const UObject *InValue)
EPropertyBagResult SetValueString (const int32 Index, const FString &InValue)
template<typename T>
EPropertyBagResult SetValueStruct (const int32 Index, const T &InValue)
Sets struct value specified type.
EPropertyBagResult SetValueStruct (const int32 Index, FConstStructView InValue)
EPropertyBagResult SetValueText (const int32 Index, const FText &InValue)
EPropertyBagResult SetValueUInt32 (const int32 Index, const uint32 InValue)
EPropertyBagResult SetValueUInt64 (const int32 Index, const uint64 InValue)
Public Member Functions inherited from FScriptArrayHelper
FORCEINLINE FScriptArrayHelper (const FArrayProperty *InProperty, const void *InArray)
Constructor, brings together a property and an instance of the property located in memory.
FORCEINLINE int32 AddUninitializedValue ()
Add an uninitialized value to the end of the array.
int32 AddUninitializedValues (int32 Count)
Add uninitialized values to the end of the array.
FORCEINLINE int32 AddValue ()
Add a blank, constructed values to the end of the array.
int32 AddValues (int32 Count)
Add blank, constructed values to the end of the array.
void ClearValues (int32 Index, int32 Count=1)
Clear values in the array.
void CountBytes (FArchive &Ar) const
Used by memory counting archives to accumulate the size of this array.
void DestroyContainer_Unsafe ()
Destroys the container object - THERE SHOULD BE NO MORE USE OF THIS HELPER AFTER THIS FUNCTION IS CALLED!
void EmptyAndAddUninitializedValues (int32 Count)
Empty the array, then add uninitialized values to a given size.
void EmptyAndAddValues (int32 Count)
Empty the array, then add blank, constructed values to a given size.
void EmptyValues (int32 Slack=0)
Remove all values from the array, calling destructors, etc as appropriate.
bool ExpandForIndex (int32 Index)
Expand the array, if needed, so that the given index is valid.
FORCEINLINE uint8 * GetElementPtr (int32 Index=0)
Returns a uint8 pointer to an element in the array.
FORCEINLINE uint8 * GetRawPtr (int32 Index=0)
Returns a uint8 pointer to an element in the array.
void InsertValues (int32 Index, int32 Count=1)
Insert blank, constructed values into the array.
FORCEINLINE bool IsValidIndex (int32 Index) const
Index range check.
void MoveAssign (void *InOtherArray)
Move the allocation from another array and make it our own.
FORCEINLINE int32 Num () const
Return the number of elements in the array.
FORCEINLINE int32 NumUnchecked () const
Return the number of elements in the array without validating the state of the array.
void RemoveValues (int32 Index, int32 Count=1)
Remove values from the array, calling destructors, etc as appropriate.
void Resize (int32 Count)
Add or remove elements to set the array to a given size.
void SwapValues (int32 A, int32 B)
Swap two elements in the array, does not call constructors and destructors.
Private Member Functions
const void * GetAddress (const int32 Index) const
void * GetMutableAddress (const int32 Index) const
Private Attributes
FPropertyBagPropertyDesc ValueDesc
Additional Inherited Members
Static Public Member Functions inherited from FScriptArrayHelper
static FScriptArrayHelper CreateHelperFormInnerProperty (const FProperty *InInnerProperty, const void *InArray, EArrayPropertyFlags InArrayFlags=EArrayPropertyFlags::None)
Detailed Description
A reference to an array in FInstancedPropertyBag Allows to modify the array via the FScriptArrayHelper API, and contains helper methods to get and set properties.
FInstancedPropertyBag Bag;
Bag.AddProperties({
    { ArrayName, EPropertyBagContainerType::Array, EPropertyBagPropertyType::Float }
});
if (auto FloatArrayRes = Bag.GetArrayRef(ArrayName); FloatArrayRes.IsValid())
{
    FPropertyBagArrayRef& FloatArray = FloatArrayRes.GetValue();
    const int32 NewIndex = FloatArray.AddValue();
    FloatArray.SetValueFloat(NewIndex, 123.0f);
}
Note: The array reference is not valid after the layout of the referenced property bag has changed!
Definition at line 935 of file StructUtils/PropertyBag.h.
Constructor & Destructor Documentation
FPropertyBagArrayRef()
FORCEINLINE FPropertyBagArrayRef::FPropertyBagArrayRef (const FPropertyBagPropertyDesc & InDesc, const void * InArray) inline
Definition at line 962 of file StructUtils/PropertyBag.h.
References FScriptArrayHelper::FScriptArrayHelper(), ArrayProperty, CastField(), check, FORCEINLINE, and ValueDesc.
Referenced by GetAddress(), and GetMutableAddress().
Member Function Documentation
GetAddress()
const void * FPropertyBagArrayRef::GetAddress (const int32 Index) const inline private
Definition at line 939 of file StructUtils/PropertyBag.h.
References FPropertyBagArrayRef(), FScriptArrayHelper::GetRawPtr(), and FScriptArrayHelper::IsValidIndex().
GetMutableAddress()
void * FPropertyBagArrayRef::GetMutableAddress (const int32 Index) const inline private
Definition at line 950 of file StructUtils/PropertyBag.h.
References FPropertyBagArrayRef(), FScriptArrayHelper::GetRawPtr(), and FScriptArrayHelper::IsValidIndex().
GetMutableNestedArrayRef()
TValueOrError< FPropertyBagArrayRef, EPropertyBagResult > FPropertyBagArrayRef::GetMutableNestedArrayRef (const int32 Index = 0) const
Returns helper class to modify and access a nested array (mutable version).
Note: Note: The array reference is not valid after the layout of the referenced property bag has changed!
Returns
helper class to modify and access arrays
References UE_API.
GetNestedArrayRef()
TValueOrError< const FPropertyBagArrayRef, EPropertyBagResult > FPropertyBagArrayRef::GetNestedArrayRef (const int32 Index = 0) const
Returns helper class to access a nested array (const version).
Note: Note: The array reference is not valid after the layout of the referenced property bag has changed!
Returns
helper class to access arrays
References UE_API.
GetValueBool()
TValueOrError< bool, EPropertyBagResult > FPropertyBagArrayRef::GetValueBool (const int32 Index) const
Getters Numeric types (bool, (u)int32, (u)int64, float, double) support type conversion.
References UE_API.
GetValueByte()
TValueOrError< uint8, EPropertyBagResult > FPropertyBagArrayRef::GetValueByte (const int32 Index) const
References UE_API.
GetValueClass()
TValueOrError< UClass *, EPropertyBagResult > FPropertyBagArrayRef::GetValueClass (const int32 Index) const
References UE_API.
GetValueDouble()
TValueOrError< double, EPropertyBagResult > FPropertyBagArrayRef::GetValueDouble (const int32 Index) const
References UE_API.
GetValueEnum() [1/2]
template<typename T> TValueOrError< T, EPropertyBagResult > FPropertyBagArrayRef::GetValueEnum (const int32 Index) const inline
Returns
enum value of specified type.
Definition at line 1000 of file StructUtils/PropertyBag.h.
References GetValueEnum(), MakeError(), MakeValue(), StaticEnum(), and TIsEnum< T >::Value.
GetValueEnum() [2/2]
TValueOrError< uint8, EPropertyBagResult > FPropertyBagArrayRef::GetValueEnum (const int32 Index, const UEnum * RequestedEnum) const
References UE_API.
Referenced by GetValueEnum().
GetValueFloat()
TValueOrError< float, EPropertyBagResult > FPropertyBagArrayRef::GetValueFloat (const int32 Index) const
References UE_API.
GetValueInt32()
TValueOrError< int32, EPropertyBagResult > FPropertyBagArrayRef::GetValueInt32 (const int32 Index) const
References UE_API.
GetValueInt64()
TValueOrError< int64, EPropertyBagResult > FPropertyBagArrayRef::GetValueInt64 (const int32 Index) const
References UE_API.
GetValueName()
TValueOrError< FName, EPropertyBagResult > FPropertyBagArrayRef::GetValueName (const int32 Index) const
References UE_API.
GetValueObject() [1/2]
template<typename T> TValueOrError< T *, EPropertyBagResult > FPropertyBagArrayRef::GetValueObject (const int32 Index) const inline
Returns
object pointer value of specified type.
Definition at line 1030 of file StructUtils/PropertyBag.h.
References Cast(), GetValueObject(), MakeError(), MakeValue(), Object, and TIsDerivedFrom< DerivedType, BaseType >::Value.
GetValueObject() [2/2]
TValueOrError< UObject *, EPropertyBagResult > FPropertyBagArrayRef::GetValueObject (const int32 Index, const UClass * RequestedClass = nullptr) const
References UE_API.
Referenced by GetValueObject().
GetValueSoftPath()
TValueOrError< FSoftObjectPath, EPropertyBagResult > FPropertyBagArrayRef::GetValueSoftPath (const int32 Index) const
References UE_API.
GetValueString()
TValueOrError< FString, EPropertyBagResult > FPropertyBagArrayRef::GetValueString (const int32 Index) const
References UE_API.
GetValueStruct() [1/2]
template<typename T> TValueOrError< T *, EPropertyBagResult > FPropertyBagArrayRef::GetValueStruct (const int32 Index) const inline
Returns
struct reference of specified type.
Definition at line 1014 of file StructUtils/PropertyBag.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), GetValueStruct(), MakeError(), and MakeValue().
GetValueStruct() [2/2]
TValueOrError< FStructView, EPropertyBagResult > FPropertyBagArrayRef::GetValueStruct (const int32 Index, const UScriptStruct * RequestedStruct = nullptr) const
References UE_API.
Referenced by GetValueStruct().
GetValueText()
TValueOrError< FText, EPropertyBagResult > FPropertyBagArrayRef::GetValueText (const int32 Index) const
References UE_API.
GetValueUInt32()
TValueOrError< uint32, EPropertyBagResult > FPropertyBagArrayRef::GetValueUInt32 (const int32 Index) const
References UE_API.
GetValueUInt64()
TValueOrError< uint64, EPropertyBagResult > FPropertyBagArrayRef::GetValueUInt64 (const int32 Index) const
References UE_API.
SetValueBool()
EPropertyBagResult FPropertyBagArrayRef::SetValueBool (const int32 Index, const bool bInValue)
Value Setters.
A property must exist in that bag before it can be set.
Numeric types (bool, (u)int32, (u)int64, float, double) support type conversion.
References UE_API.
SetValueByte()
EPropertyBagResult FPropertyBagArrayRef::SetValueByte (const int32 Index, const uint8 InValue)
References UE_API.
SetValueClass()
EPropertyBagResult FPropertyBagArrayRef::SetValueClass (const int32 Index, UClass * InValue)
References UE_API.
SetValueDouble()
EPropertyBagResult FPropertyBagArrayRef::SetValueDouble (const int32 Index, const double InValue)
References UE_API.
SetValueEnum() [1/2]
template<typename T> EPropertyBagResult FPropertyBagArrayRef::SetValueEnum (const int32 Index, const T InValue) inline
Sets enum value specified type.
Definition at line 1088 of file StructUtils/PropertyBag.h.
References SetValueEnum(), StaticEnum(), and TIsEnum< T >::Value.
SetValueEnum() [2/2]
EPropertyBagResult FPropertyBagArrayRef::SetValueEnum (const int32 Index, const uint8 InValue, const UEnum * Enum)
References Enum, and UE_API.
Referenced by SetValueEnum().
SetValueFloat()
EPropertyBagResult FPropertyBagArrayRef::SetValueFloat (const int32 Index, const float InValue)
References UE_API.
SetValueInt32()
EPropertyBagResult FPropertyBagArrayRef::SetValueInt32 (const int32 Index, const int32 InValue)
References UE_API.
SetValueInt64()
EPropertyBagResult FPropertyBagArrayRef::SetValueInt64 (const int32 Index, const int64 InValue)
References UE_API.
SetValueName()
EPropertyBagResult FPropertyBagArrayRef::SetValueName (const int32 Index, const FName InValue)
References UE_API.
SetValueObject() [1/2]
template<typename T> EPropertyBagResult FPropertyBagArrayRef::SetValueObject (const int32 Index, T * InValue) inline
Sets object pointer value specified type.
Definition at line 1103 of file StructUtils/PropertyBag.h.
References SetValueObject(), and TIsDerivedFrom< DerivedType, BaseType >::Value.
SetValueObject() [2/2]
EPropertyBagResult FPropertyBagArrayRef::SetValueObject (const int32 Index, UObject * InValue)
References UE_API.
Referenced by SetValueObject().
SetValueSoftPath() [1/2]
EPropertyBagResult FPropertyBagArrayRef::SetValueSoftPath (const int32 Index, const FSoftObjectPath & InValue)
References UE_API.
SetValueSoftPath() [2/2]
EPropertyBagResult FPropertyBagArrayRef::SetValueSoftPath (const int32 Index, const UObject * InValue)
References UE_API.
SetValueString()
EPropertyBagResult FPropertyBagArrayRef::SetValueString (const int32 Index, const FString & InValue)
References UE_API.
SetValueStruct() [1/2]
template<typename T> EPropertyBagResult FPropertyBagArrayRef::SetValueStruct (const int32 Index, const T & InValue) inline
Sets struct value specified type.
Definition at line 1096 of file StructUtils/PropertyBag.h.
References FConstStructView::Make(), and SetValueStruct().
SetValueStruct() [2/2]
EPropertyBagResult FPropertyBagArrayRef::SetValueStruct (const int32 Index, FConstStructView InValue)
References UE_API.
Referenced by SetValueStruct().
SetValueText()
EPropertyBagResult FPropertyBagArrayRef::SetValueText (const int32 Index, const FText & InValue)
References UE_API.
SetValueUInt32()
EPropertyBagResult FPropertyBagArrayRef::SetValueUInt32 (const int32 Index, const uint32 InValue)
References UE_API.
SetValueUInt64()
EPropertyBagResult FPropertyBagArrayRef::SetValueUInt64 (const int32 Index, const uint64 InValue)
References UE_API.
Field Documentation
ValueDesc
FPropertyBagPropertyDesc FPropertyBagArrayRef::ValueDesc private
Definition at line 937 of file StructUtils/PropertyBag.h.
Referenced by FPropertyBagArrayRef().
The documentation for this class was generated from the following file:
StructUtils/PropertyBag.h