Unreal Engine 5.6 C++ API: UObjectIterator.h File Reference
UObjectIterator.h File Reference
#include "CoreMinimal.h"
#include "UObject/GarbageCollectionGlobals.h"
#include "UObject/UObjectHash.h"
#include "UObject/UObjectArray.h"
#include "UObject/ObjectVisibility.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
Data Structures
class FRawObjectIterator
Class for iterating through all objects, including class default objects, unreachable objects...all UObjects.
class TObjectIterator< T >
Class for iterating through all objects which inherit from a specified base class.
class TObjectIterator< UObject >
specialization for T == UObject that does not call IsA() unnecessarily
class TObjectIteratorBase< IteratorThreadSafety >
Class for iterating through all objects, including class default objects.
struct TObjectRange< T >
struct TObjectRange< UObject >
Typedefs
typedef TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafeAdvance > FPersistentThreadSafeObjectIterator
Class for iterating through all objects, including class default objects.
typedef TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe > FThreadSafeObjectIterator
Class for iterating through all objects, including class default objects.
typedef TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None > FUnsafeObjectIterator
Class for iterating through all objects, including class default objects.
Enumerations
enum class EObjectIteratorThreadSafetyOptions : uint8 { None = 0 , ThreadSafe = 1 , ThreadSafeAdvance = 2 }
Functions
EInternalObjectFlags GetObjectIteratorDefaultInternalExclusionFlags (EInternalObjectFlags InternalExclusionFlags)
UE_DEPRECATED (4.27, "FObjectIterator is not thread safe, use FThreadSafeObjectIterator or FPresistentThreadSafeObjectIterator instead.") typedef FUnsafeObjectIterator FObjectIterator
Deprecating the old FObjectIterator class which is now synonymous with FUnsafeObjectIterator.
Typedef Documentation
FPersistentThreadSafeObjectIterator
typedef TObjectIteratorBase<EObjectIteratorThreadSafetyOptions::ThreadSafeAdvance> FPersistentThreadSafeObjectIterator
Class for iterating through all objects, including class default objects.
Note that when Playing In Editor, this will find objects in the editor as well as the PIE world, in an indeterminate order. Locks the global FUObjectArray when advancing to the next object. Should only be used with persistent iterator instances that exist for more than a frame.
Definition at line 244 of file UObjectIterator.h.
FThreadSafeObjectIterator
typedef TObjectIteratorBase<EObjectIteratorThreadSafetyOptions::ThreadSafe> FThreadSafeObjectIterator
Class for iterating through all objects, including class default objects.
Note that when Playing In Editor, this will find objects in the editor as well as the PIE world, in an indeterminate order. Locks the global FUObjectArray when iterating over it. Should only be used with function local iterator instances.
Definition at line 235 of file UObjectIterator.h.
FUnsafeObjectIterator
typedef TObjectIteratorBase<EObjectIteratorThreadSafetyOptions::None> FUnsafeObjectIterator
Class for iterating through all objects, including class default objects.
Note that when Playing In Editor, this will find objects in the editor as well as the PIE world, in an indeterminate order. This iterator does not lock the gloabl FUObjectArray when iterating over it which may result in race conditions.
Definition at line 221 of file UObjectIterator.h.
Enumeration Type Documentation
EObjectIteratorThreadSafetyOptions
enum class EObjectIteratorThreadSafetyOptions : uint8 strong
Enumerator
None
ThreadSafe
ThreadSafeAdvance
Definition at line 52 of file UObjectIterator.h.
Function Documentation
GetObjectIteratorDefaultInternalExclusionFlags()
EInternalObjectFlags GetObjectIteratorDefaultInternalExclusionFlags (EInternalObjectFlags InternalExclusionFlags) inline
Definition at line 59 of file UObjectIterator.h.
References AutoRTFMConstructionAborted, UE::GetAsyncLoadingInternalFlagsExclusion(), PendingConstruction, Remote, and Unreachable.
Referenced by TComponentInterfaceIterator< T >::TComponentInterfaceIterator(), TObjectIterator< T >::TObjectIterator(), TObjectIterator< UObject >::TObjectIterator(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase().
UE_DEPRECATED()
UE_DEPRECATED (4. 27, "FObjectIterator is not thread safe, use FThreadSafeObjectIterator or FPresistentThreadSafeObjectIterator instead.")
Deprecating the old FObjectIterator class which is now synonymous with FUnsafeObjectIterator.