Unreal Engine 5.6 C++ API: Metasound::TInputNode< DataType, VertexAccess > Class Template Reference
Metasound::TInputNode< DataType, VertexAccess > Class Template Reference
TInputNode represents an input to a metasound graph.
#include "MetasoundInputNode.h"
Public Member Functions
TInputNode (const FVertexName &InVertexName, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
TInputNode (FInputNodeConstructorParams &&InParams)
UE_DEPRECATED (5.6, "Use CreateNodeClassMetadata(...) instead") static FNodeClassMetadata GetNodeInfo(const FVertexName &InVertexName)
Public Member Functions inherited from Metasound::FInputNode
METASOUNDFRONTEND_API FInputNode (FInputNodeConstructorParams &&InParams, const FName &InDataTypeName, EVertexAccessType InVertexAccess, FOperatorFactorySharedRef InFactory)
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
UE_DEPRECATED (5.6, "Use CreateNodeClassMetadata(...) instead") static METASOUNDFRONTEND_API FNodeClassMetadata GetNodeMetadata(const FVertexName &InVertexName
UE_DEPRECATED (5.6, "You can find the vertex name by inspecting the FVertexInterface.") METASOUNDFRONTEND_API const FVertexName &GetVertexName() const
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static FNodeClassMetadata CreateNodeClassMetadata (const FVertexName &InVertexName)
Static Public Member Functions inherited from Metasound::FInputNode
static METASOUNDFRONTEND_API FNodeClassMetadata CreateNodeClassMetadata (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccess)
static METASOUNDFRONTEND_API FText GetInputDescription ()
Static Public Attributes
static constexpr bool bCanRegister = bIsSupportedInput
Static Private Attributes
static constexpr bool bIsConstructorInput = VertexAccess == EVertexAccessType::Value
static constexpr bool bIsReferenceInput = VertexAccess == EVertexAccessType::Reference
static constexpr bool bIsSupportedConstructorInput = TIsConstructorVertexSupported<DataType>::Value && bIsConstructorInput
static constexpr bool bIsSupportedInput = bIsSupportedConstructorInput || bIsSupportedReferenceInput
static constexpr bool bIsSupportedReferenceInput = TLiteralTraits<DataType>::bIsParsableFromAnyLiteralType && bIsReferenceInput
Additional Inherited Members
Data Fields inherited from Metasound::FInputNode
const FName & InDataTypeName
const FName EVertexAccessType InVertexAccess
Protected Member Functions inherited from Metasound::FInputNode
METASOUNDFRONTEND_API FInputNode (FOperatorFactorySharedRef InFactory, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Static Protected Member Functions inherited from Metasound::FInputNode
static METASOUNDFRONTEND_API FVertexInterface CreateDefaultVertexInterface (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccess, const FLiteral *InDefaultLiteral=nullptr)
Detailed Description
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference>
class Metasound::TInputNode< DataType, VertexAccess >
TInputNode represents an input to a metasound graph.
Definition at line 353 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
TInputNode() [1/2]
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::TInputNode< DataType, VertexAccess >::TInputNode (FInputNodeConstructorParams && InParams) inline explicit
Definition at line 379 of file MetasoundInputNode.h.
References Metasound::FInputNode::FInputNode(), Metasound::GetMetasoundDataTypeName(), MakeShared(), and MoveTemp().
TInputNode() [2/2]
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::TInputNode< DataType, VertexAccess >::TInputNode (const FVertexName & InVertexName, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) inline explicit
Definition at line 384 of file MetasoundInputNode.h.
References Metasound::FInputNode::FInputNode(), MakeShared(), and MoveTemp().
Member Function Documentation
CreateNodeClassMetadata()
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> FNodeClassMetadata Metasound::TInputNode< DataType, VertexAccess >::CreateNodeClassMetadata (const FVertexName & InVertexName) inline static
Definition at line 372 of file MetasoundInputNode.h.
References Metasound::FInputNode::CreateNodeClassMetadata(), and Metasound::GetMetasoundDataTypeName().
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
UE_DEPRECATED()
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::TInputNode< DataType, VertexAccess >::UE_DEPRECATED (5. 6, "Use CreateNodeClassMetadata(...) instead") const & inline
Definition at line 366 of file MetasoundInputNode.h.
References Metasound::FInputNode::CreateNodeClassMetadata(), and Metasound::GetMetasoundDataTypeName().
Field Documentation
bCanRegister
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bCanRegister = bIsSupportedInput static constexpr
Definition at line 364 of file MetasoundInputNode.h.
bIsConstructorInput
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bIsConstructorInput = VertexAccess == EVertexAccessType::Value static constexpr private
Definition at line 355 of file MetasoundInputNode.h.
bIsReferenceInput
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bIsReferenceInput = VertexAccess == EVertexAccessType::Reference static constexpr private
Definition at line 357 of file MetasoundInputNode.h.
bIsSupportedConstructorInput
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bIsSupportedConstructorInput = TIsConstructorVertexSupported<DataType>::Value && bIsConstructorInput static constexpr private
Definition at line 356 of file MetasoundInputNode.h.
bIsSupportedInput
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bIsSupportedInput = bIsSupportedConstructorInput || bIsSupportedReferenceInput static constexpr private
Definition at line 360 of file MetasoundInputNode.h.
bIsSupportedReferenceInput
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::TInputNode< DataType, VertexAccess >::bIsSupportedReferenceInput = TLiteralTraits<DataType>::bIsParsableFromAnyLiteralType && bIsReferenceInput static constexpr private
Definition at line 358 of file MetasoundInputNode.h.
The documentation for this class was generated from the following file:
MetasoundInputNode.h