Unreal Engine 5.6 C++ API: FPThreadEvent Class Reference
FPThreadEvent Class Reference
This is the PThreads version of FEvent.
#include "PThreadEvent.h"
Public Member Functions
FPThreadEvent ()
virtual ~FPThreadEvent ()
virtual bool Create (bool _bIsManualReset=false) override
virtual bool IsManualReset () override
Whether the signaled state of this event needs to be reset manually.
virtual void Reset () override
Resets the event to an untriggered (waitable) state.
virtual void Trigger () override
Triggers the event so any waiting threads are activated.
virtual bool Wait (uint32 WaitTime=(uint32) -1, const bool bIgnoreThreadIdleStats=false) override
Waits the specified amount of time for the event to be triggered.
Public Member Functions inherited from FEvent
FEvent ()
Default constructor.
virtual ~FEvent ()
Virtual destructor.
void AdvanceStats ()
Advances stats associated with this event.
UE_DEPRECATED (5.0, "Direct creation of FEvent is discouraged for performance reasons. Please use FPlatformProcess::GetSynchEventFromPool/ReturnSynchEventToPool.") virtual bool Create(bool bIsManualReset
Creates the event.
bool Wait ()
Waits an infinite amount of time for the event to be triggered.
bool Wait (const FTimespan &WaitTime, const bool bIgnoreThreadIdleStats=false)
Waits the specified amount of time for the event to be triggered.
Private Types
enum TriggerType { TRIGGERED_NONE , TRIGGERED_ONE , TRIGGERED_ALL }
Private Member Functions
void LockEventMutex ()
void UnlockEventMutex ()
Static Private Member Functions
static void SubtractTimevals (const struct timeval *FromThis, struct timeval *SubThis, struct timeval *Difference)
Private Attributes
bool bInitialized
bool bIsManualReset
pthread_cond_t Condition
pthread_mutex_t Mutex
volatile TriggerType Triggered
volatile int32 WaitingThreads
Additional Inherited Members
Protected Member Functions inherited from FEvent
void ResetForStats ()
Resets start cycles to 0.
void TriggerForStats ()
Send to the stats a special message which encodes a trigger for the event.
void WaitForStats ()
Sends to the stats a special messages which encodes a wait for the event.
Protected Attributes inherited from FEvent
uint32 EventId
An unique id of this event.
TAtomic< uint32 > EventStartCycles
Greater than 0, if the event called wait.
Static Protected Attributes inherited from FEvent
static TAtomic< uint32 > EventUniqueId
Counter used to generate an unique id for the events.
Detailed Description
This is the PThreads version of FEvent.
Definition at line 13 of file PThreadEvent.h.
Member Enumeration Documentation
TriggerType
enum FPThreadEvent::TriggerType private
Enumerator
TRIGGERED_NONE
TRIGGERED_ONE
TRIGGERED_ALL
Definition at line 17 of file PThreadEvent.h.
Constructor & Destructor Documentation
FPThreadEvent()
FPThreadEvent::FPThreadEvent () inline
Definition at line 65 of file PThreadEvent.h.
References bInitialized, bIsManualReset, Triggered, TRIGGERED_NONE, and WaitingThreads.
~FPThreadEvent()
virtual FPThreadEvent::~FPThreadEvent () inline virtual
Definition at line 73 of file PThreadEvent.h.
References bInitialized, bIsManualReset, Condition, LockEventMutex(), Mutex, Trigger(), UnlockEventMutex(), and WaitingThreads.
Member Function Documentation
Create()
virtual bool FPThreadEvent::Create (bool _bIsManualReset = false) inline override virtual
Definition at line 102 of file PThreadEvent.h.
References bInitialized, bIsManualReset, check, Condition, Mutex, Triggered, and TRIGGERED_NONE.
IsManualReset()
virtual bool FPThreadEvent::IsManualReset () inline override virtual
Whether the signaled state of this event needs to be reset manually.
Returns
true if the state requires manual resetting, false otherwise.
See also
Reset
Implements FEvent.
Definition at line 124 of file PThreadEvent.h.
References bIsManualReset.
LockEventMutex()
void FPThreadEvent::LockEventMutex () inline private
Definition at line 31 of file PThreadEvent.h.
References check, and Mutex.
Referenced by ~FPThreadEvent(), Reset(), and Trigger().
Reset()
virtual void FPThreadEvent::Reset () inline override virtual
Resets the event to an untriggered (waitable) state.
See also
IsManualReset, Trigger
Implements FEvent.
Definition at line 156 of file PThreadEvent.h.
References bInitialized, check, LockEventMutex(), FEvent::ResetForStats(), Triggered, TRIGGERED_NONE, and UnlockEventMutex().
SubtractTimevals()
void FPThreadEvent::SubtractTimevals (const struct timeval * FromThis, struct timeval * SubThis, struct timeval * Difference) inline static private
Definition at line 43 of file PThreadEvent.h.
Trigger()
virtual void FPThreadEvent::Trigger () inline override virtual
Triggers the event so any waiting threads are activated.
See also
IsManualReset, Reset
Implements FEvent.
Definition at line 129 of file PThreadEvent.h.
References bInitialized, bIsManualReset, check, Condition, LockEventMutex(), Triggered, TRIGGERED_ALL, TRIGGERED_ONE, FEvent::TriggerForStats(), and UnlockEventMutex().
Referenced by ~FPThreadEvent().
UnlockEventMutex()
void FPThreadEvent::UnlockEventMutex () inline private
Definition at line 37 of file PThreadEvent.h.
References check, and Mutex.
Referenced by ~FPThreadEvent(), Reset(), and Trigger().
Wait()
virtual bool FPThreadEvent::Wait (uint32 WaitTime = (uint32) -1, const bool bIgnoreThreadIdleStats = false) override virtual
Waits the specified amount of time for the event to be triggered.
A wait time of MAX_uint32 is treated as infinite wait.
Parameters
WaitTime The time to wait (in milliseconds).
bIgnoreThreadIdleStats If true, ignores ThreadIdleStats
Returns
true if the event was triggered, false if the wait timed out.
Implements FEvent.
Field Documentation
bInitialized
bool FPThreadEvent::bInitialized private
Definition at line 24 of file PThreadEvent.h.
Referenced by FPThreadEvent(), ~FPThreadEvent(), Create(), Reset(), and Trigger().
bIsManualReset
bool FPThreadEvent::bIsManualReset private
Definition at line 25 of file PThreadEvent.h.
Referenced by FPThreadEvent(), ~FPThreadEvent(), Create(), IsManualReset(), and Trigger().
Condition
pthread_cond_t FPThreadEvent::Condition private
Definition at line 29 of file PThreadEvent.h.
Referenced by ~FPThreadEvent(), Create(), and Trigger().
Mutex
pthread_mutex_t FPThreadEvent::Mutex private
Definition at line 28 of file PThreadEvent.h.
Referenced by ~FPThreadEvent(), Create(), LockEventMutex(), and UnlockEventMutex().
Triggered
volatile TriggerType FPThreadEvent::Triggered private
Definition at line 26 of file PThreadEvent.h.
Referenced by FPThreadEvent(), Create(), Reset(), and Trigger().
WaitingThreads
volatile int32 FPThreadEvent::WaitingThreads private
Definition at line 27 of file PThreadEvent.h.
Referenced by FPThreadEvent(), and ~FPThreadEvent().
The documentation for this class was generated from the following file:
PThreadEvent.h