Unreal Engine 5.6 C++ API: FArchiveSavePackageData Struct Reference
FArchiveSavePackageData Struct Reference
Holds archive data only relevant for archives used during SavePackage.
#include "ArchiveSavePackageData.h"
Public Member Functions
FArchiveSavePackageData (FObjectSavePackageSerializeContext &InSavePackageContext, const ITargetPlatform *InTargetPlatform, FArchiveCookContext *InCookContext)
Data Fields
FArchiveCookContext * CookContext = nullptr
Non-null if a cook save.
FObjectSavePackageSerializeContext & SavePackageContext
const ITargetPlatform * TargetPlatform = nullptr
Non-null if a cook save.
Detailed Description
Holds archive data only relevant for archives used during SavePackage.
Definition at line 10 of file ArchiveSavePackageData.h.
Constructor & Destructor Documentation
FArchiveSavePackageData()
FArchiveSavePackageData::FArchiveSavePackageData (FObjectSavePackageSerializeContext & InSavePackageContext, const ITargetPlatform * InTargetPlatform, FArchiveCookContext * InCookContext) inline
Definition at line 12 of file ArchiveSavePackageData.h.
References CookContext, SavePackageContext, and TargetPlatform.
Referenced by FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer(), FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer(), and FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer().
Field Documentation
CookContext
FArchiveCookContext* FArchiveSavePackageData::CookContext = nullptr
Non-null if a cook save.
Null if an editor save.
Definition at line 24 of file ArchiveSavePackageData.h.
Referenced by FArchiveSavePackageData(), and FArchiveSavePackageDataBuffer::SetConstructorTargetPlatform().
SavePackageContext
FObjectSavePackageSerializeContext& FArchiveSavePackageData::SavePackageContext
Definition at line 20 of file ArchiveSavePackageData.h.
Referenced by FArchiveSavePackageData().
TargetPlatform
const ITargetPlatform* FArchiveSavePackageData::TargetPlatform = nullptr
Non-null if a cook save.
Null if an editor save.
Definition at line 22 of file ArchiveSavePackageData.h.
Referenced by FArchiveSavePackageData(), FArchiveSavePackageDataBuffer::FArchiveSavePackageDataBuffer(), and FArchiveSavePackageDataBuffer::SetConstructorTargetPlatform().
The documentation for this struct was generated from the following file:
ArchiveSavePackageData.h