Unreal Engine 5.6 C++ API: FCompositeDragDropOp Class Reference
FCompositeDragDropOp Class Reference
#include "CompositeDragDropOp.h"
Public Member Functions
void AddSubOp (const TSharedPtr< FDragDropOperation > &SubOp)
DRAG_DROP_OPERATOR_TYPE (FCompositeDragDropOp, FDecoratedDragDropOp) FCompositeDragDropOp()
template<typename T>
TSharedPtr< T > GetSubOp ()
template<typename T>
const TSharedPtr< const T > GetSubOp () const
template<typename T>
TSharedPtr< T > HasSubOp ()
virtual void ResetToDefaultToolTip () override
Set the decorator back to the icon and text defined by the default.
Public Member Functions inherited from FDecoratedDragDropOp
FDecoratedDragDropOp ()
virtual void Construct () override
Overridden to provide public access.
DRAG_DROP_OPERATOR_TYPE (FDecoratedDragDropOp, FDragDropOperation) FText CurrentHoverText
String to show as hover text.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const override
The widget decorator to use.
FText GetDefaultHoverText () const
Gets the default hover text for this drag drop op.
FText GetHoverText () const
const FSlateBrush * GetIcon () const
FSlateColor GetIconColorAndOpacity () const
void SetToolTip (const FText &Text, const FSlateBrush *Icon)
Set the text and icon for this tooltip.
void SetupDefaults ()
Setup some default values for the decorator.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Attributes
TArray< TSharedPtr< FDragDropOperation > > SubOps
Protected Attributes inherited from FDecoratedDragDropOp
const FSlateBrush * DefaultHoverIcon
Default icon to be displayed.
FSlateColor DefaultHoverIconColorAndOpacity
Default color and opacity for the default icon to be displayed.
FText DefaultHoverText
Default string to show as hover text.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Private Member Functions
TSharedPtr< FDragDropOperation > GetSubOpPtr (const FString &TypeId) const
Additional Inherited Members
Data Fields inherited from FDecoratedDragDropOp
const FSlateBrush * CurrentIconBrush
Icon to be displayed.
FSlateColor CurrentIconColorAndOpacity
The color of the icon to be displayed.
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 9 of file CompositeDragDropOp.h.
Member Function Documentation
AddSubOp()
void FCompositeDragDropOp::AddSubOp (const TSharedPtr< FDragDropOperation > & SubOp) inline
Definition at line 16 of file CompositeDragDropOp.h.
References check, and SubOps.
DRAG_DROP_OPERATOR_TYPE()
FCompositeDragDropOp::DRAG_DROP_OPERATOR_TYPE (FCompositeDragDropOp , FDecoratedDragDropOp) inline
Definition at line 12 of file CompositeDragDropOp.h.
References FDecoratedDragDropOp::FDecoratedDragDropOp().
GetSubOp() [1/2]
template<typename T> TSharedPtr< T > FCompositeDragDropOp::GetSubOp () inline
Definition at line 36 of file CompositeDragDropOp.h.
References StaticCastSharedPtr(), and SubOps.
GetSubOp() [2/2]
template<typename T> const TSharedPtr< const T > FCompositeDragDropOp::GetSubOp () const inline
Definition at line 49 of file CompositeDragDropOp.h.
References StaticCastSharedPtr(), and SubOps.
GetSubOpPtr()
TSharedPtr< FDragDropOperation > FCompositeDragDropOp::GetSubOpPtr (const FString & TypeId) const inline private
Definition at line 78 of file CompositeDragDropOp.h.
References SubOps.
HasSubOp()
template<typename T> TSharedPtr< T > FCompositeDragDropOp::HasSubOp () inline
Definition at line 23 of file CompositeDragDropOp.h.
References SubOps.
ResetToDefaultToolTip()
virtual void FCompositeDragDropOp::ResetToDefaultToolTip () inline override virtual
Set the decorator back to the icon and text defined by the default.
Reimplemented from FDecoratedDragDropOp.
Definition at line 61 of file CompositeDragDropOp.h.
References FDecoratedDragDropOp::FDecoratedDragDropOp(), FDecoratedDragDropOp::ResetToDefaultToolTip(), StaticCastSharedPtr(), and SubOps.
Field Documentation
SubOps
TArray<TSharedPtr<FDragDropOperation> > FCompositeDragDropOp::SubOps protected
Definition at line 90 of file CompositeDragDropOp.h.
Referenced by AddSubOp(), GetSubOp(), GetSubOp(), GetSubOpPtr(), HasSubOp(), and ResetToDefaultToolTip().
The documentation for this class was generated from the following file:
CompositeDragDropOp.h