Unreal Engine 5.6 C++ API: FDisplayClusterLightCardEditorHelper::FSphericalCoordinates Struct Reference
FDisplayClusterLightCardEditorHelper::FSphericalCoordinates Struct Reference
#include "DisplayClusterLightCardEditorHelper.h"
Public Member Functions
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates ()
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates (const FVector &CartesianPosition)
Constructors.
DISPLAYCLUSTERSCENEPREVIEW_API FVector AsCartesian () const
Return equivalent cartesian coordinates.
DISPLAYCLUSTERSCENEPREVIEW_API void Conform ()
Conform parameters to their normal ranges.
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates GetConformed () const
Returns a conformed version of this struct without changing the current one.
DISPLAYCLUSTERSCENEPREVIEW_API bool IsPointingAtPole (double Margin=1e-6) const
Returns true if the inclination is pointing at north or south poles, within the given margin (in radians)
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates operator+ (FSphericalCoordinates const &Other) const
Addition operator.
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates operator- (FSphericalCoordinates const &Other) const
Subtraction operator.
Data Fields
double Azimuth = 0
double Inclination = 0
double Radius = 0
Detailed Description
Definition at line 42 of file DisplayClusterLightCardEditorHelper.h.
Constructor & Destructor Documentation
FSphericalCoordinates() [1/2]
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::FSphericalCoordinates (const FVector & CartesianPosition)
Constructors.
References FVector.
Referenced by GetConformed(), operator+(), and operator-().
FSphericalCoordinates() [2/2]
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::FSphericalCoordinates ()
Member Function Documentation
AsCartesian()
DISPLAYCLUSTERSCENEPREVIEW_API FVector FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::AsCartesian () const
Return equivalent cartesian coordinates.
References FVector.
Conform()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::Conform ()
Conform parameters to their normal ranges.
GetConformed()
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::GetConformed () const
Returns a conformed version of this struct without changing the current one.
References FSphericalCoordinates().
IsPointingAtPole()
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::IsPointingAtPole (double Margin = 1e-6) const
Returns true if the inclination is pointing at north or south poles, within the given margin (in radians)
operator+()
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::operator+ (FSphericalCoordinates const & Other) const
Addition operator.
References FSphericalCoordinates(), and Other.
operator-()
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::operator- (FSphericalCoordinates const & Other) const
Subtraction operator.
References FSphericalCoordinates(), and Other.
Field Documentation
Azimuth
double FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::Azimuth = 0
Definition at line 70 of file DisplayClusterLightCardEditorHelper.h.
Inclination
double FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::Inclination = 0
Definition at line 69 of file DisplayClusterLightCardEditorHelper.h.
Radius
double FDisplayClusterLightCardEditorHelper::FSphericalCoordinates::Radius = 0
Definition at line 68 of file DisplayClusterLightCardEditorHelper.h.
The documentation for this struct was generated from the following file:
DisplayClusterLightCardEditorHelper.h