Unreal Engine 5.6 C++ API: FGroomBindingBuilder Struct Reference
FGroomBindingBuilder Struct Reference
#include "GroomBindingBuilder.h"
Data Structures
struct FInput
Static Public Member Functions
static HAIRSTRANDSCORE_API bool BuildBinding (const FInput &In, uint32 InGroupIndex, const ITargetPlatform *TargetPlatform, UGroomBindingAsset::FHairGroupPlatformData &Out)
static HAIRSTRANDSCORE_API bool BuildBinding (UGroomBindingAsset *BindingAsset, bool bInitResource)
static HAIRSTRANDSCORE_API bool BuildBinding (UGroomBindingAsset *BindingAsset, uint32 InGroupIndex)
static HAIRSTRANDSCORE_API void GetRootData (FHairStrandsRootData &Out, const FHairStrandsRootBulkData &In)
static HAIRSTRANDSCORE_API FString GetVersion ()
Detailed Description
Definition at line 24 of file GroomBindingBuilder.h.
Member Function Documentation
BuildBinding() [1/3]
HAIRSTRANDSCORE_API bool FGroomBindingBuilder::BuildBinding (const FInput & In, uint32 InGroupIndex, const ITargetPlatform * TargetPlatform, UGroomBindingAsset::FHairGroupPlatformData & Out) static
References BuildBinding(), and UE_API.
BuildBinding() [2/3]
HAIRSTRANDSCORE_API bool FGroomBindingBuilder::BuildBinding (UGroomBindingAsset * BindingAsset, bool bInitResource) static
References BuildBinding(), UE_API, and UE_DEPRECATED.
Referenced by BuildBinding(), BuildBinding(), and BuildBinding().
BuildBinding() [3/3]
HAIRSTRANDSCORE_API bool FGroomBindingBuilder::BuildBinding (UGroomBindingAsset * BindingAsset, uint32 InGroupIndex) static
References BuildBinding(), and UE_API.
GetRootData()
HAIRSTRANDSCORE_API void FGroomBindingBuilder::GetRootData (FHairStrandsRootData & Out, const FHairStrandsRootBulkData & In) static
References GetRootData(), and UE_API.
Referenced by GetRootData().
GetVersion()
HAIRSTRANDSCORE_API FString FGroomBindingBuilder::GetVersion () static
References UE_API.
The documentation for this struct was generated from the following file:
GroomBindingBuilder.h