Unreal Engine 5.6 C++ API: UE::MovieScene::FInitialValueCache Struct Reference
UE::MovieScene::FInitialValueCache Struct Reference
Container that houses initial values for any properties animated through FEntityManager Each type is stored in its own container, organized by the initial value component ID The cache is stored as a singleton (through GetSharedInitialValues()) and added as an extension to UMovieSceneEntitySystemLinker where it is active.
#include "MovieSceneInitialValueCache.h"
Public Member Functions
template<typename PropertyTraits>
TPropertyValueStorage< PropertyTraits > * FindStorage (const TPropertyComponents< PropertyTraits > &PropertyComponents)
Retrieve the initial value storage for a given property type.
template<typename PropertyTraits>
TPropertyValueStorage< PropertyTraits > * FindStorage (FComponentTypeID InitialValueType)
Retrieve the initial value storage for a given initial value type.
template<typename PropertyTraits>
TPropertyValueStorage< PropertyTraits > * GetStorage (const TPropertyComponents< PropertyTraits > &PropertyComponents)
Retrieve the initial value storage for a given property type, creating it if necessary.
template<typename PropertyTraits>
TPropertyValueStorage< PropertyTraits > * GetStorage (FComponentTypeID InitialValueType)
Retrieve the initial value storage for a given initial value type, creating it if necessary.
void Reset (FComponentTypeID InitialValueType, TArrayView< const FInitialValueIndex > InitialValueIndices)
Reset all the initial values that relate to the specified type and indices.
Static Public Member Functions
static MOVIESCENE_API TEntitySystemLinkerExtensionID< FInitialValueCache > GetExtensionID ()
Retrieve the extension ID for this structure when added to a UMovieSceneEntitySystemLinker.
static MOVIESCENE_API TSharedPtr< FInitialValueCache > GetGlobalInitialValues ()
Retrieve a container used for sharing initial values between linkers.
Private Attributes
TMap< FComponentTypeID, TUniquePtr< IPropertyValueStorage > > StorageByComponent
Detailed Description
Container that houses initial values for any properties animated through FEntityManager Each type is stored in its own container, organized by the initial value component ID The cache is stored as a singleton (through GetSharedInitialValues()) and added as an extension to UMovieSceneEntitySystemLinker where it is active.
Definition at line 55 of file MovieSceneInitialValueCache.h.
Member Function Documentation
FindStorage() [1/2]
template<typename PropertyTraits> TPropertyValueStorage< PropertyTraits > * UE::MovieScene::FInitialValueCache::FindStorage (const TPropertyComponents< PropertyTraits > & PropertyComponents) inline
Retrieve the initial value storage for a given property type.
Parameters
PropertyComponents The property component definitions for the storage including its traits
Returns
Property storage for the initial values or nullptr if none exists
Definition at line 149 of file MovieSceneInitialValueCache.h.
References FindStorage(), and UE::MovieScene::TPropertyComponents< PropertyTraits >::InitialValue.
FindStorage() [2/2]
template<typename PropertyTraits> TPropertyValueStorage< PropertyTraits > * UE::MovieScene::FInitialValueCache::FindStorage (FComponentTypeID InitialValueType) inline
Retrieve the initial value storage for a given initial value type.
Note
: Care should be taken to ensure that the template parameter matches the traits defined by the TPropertyComponents for the property.
Parameters
InitialValueType The ComponentTypeID for the initial value
Returns
Property storage for the initial values or nullptr if none exists
Definition at line 129 of file MovieSceneInitialValueCache.h.
References check, and StorageByComponent.
Referenced by FindStorage(), and GetStorage().
GetExtensionID()
MOVIESCENE_API TEntitySystemLinkerExtensionID< FInitialValueCache > UE::MovieScene::FInitialValueCache::GetExtensionID () static
Retrieve the extension ID for this structure when added to a UMovieSceneEntitySystemLinker.
GetGlobalInitialValues()
MOVIESCENE_API TSharedPtr< FInitialValueCache > UE::MovieScene::FInitialValueCache::GetGlobalInitialValues () static
Retrieve a container used for sharing initial values between linkers.
Note
: The instance is not referenced internally, so will be destroyed when all externally owned shared pointers are destroyed.
GetStorage() [1/2]
template<typename PropertyTraits> TPropertyValueStorage< PropertyTraits > * UE::MovieScene::FInitialValueCache::GetStorage (const TPropertyComponents< PropertyTraits > & PropertyComponents) inline
Retrieve the initial value storage for a given property type, creating it if necessary.
Parameters
PropertyComponents The property component definitions for the storage including its traits
Returns
Property storage for the initial values or nullptr if none exists
Definition at line 114 of file MovieSceneInitialValueCache.h.
References GetStorage().
GetStorage() [2/2]
template<typename PropertyTraits> TPropertyValueStorage< PropertyTraits > * UE::MovieScene::FInitialValueCache::GetStorage (FComponentTypeID InitialValueType) inline
Retrieve the initial value storage for a given initial value type, creating it if necessary.
Note
: Care should be taken to ensure that the template parameter matches the traits defined by the TPropertyComponents for the property.
Parameters
InitialValueType The ComponentTypeID for the initial value
Returns
Property storage for the initial values
Definition at line 95 of file MovieSceneInitialValueCache.h.
References FindStorage(), and StorageByComponent.
Referenced by GetStorage(), and UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::Initialize().
Reset()
void UE::MovieScene::FInitialValueCache::Reset (FComponentTypeID InitialValueType, TArrayView< const FInitialValueIndex > InitialValueIndices) inline
Reset all the initial values that relate to the specified type and indices.
Parameters
InitialValueType The ComponentTypeID for the initial value that the indices relate to
InitialValueIndices An array containing all the indices to remove
Definition at line 78 of file MovieSceneInitialValueCache.h.
References StorageByComponent.
Field Documentation
StorageByComponent
TMap<FComponentTypeID, TUniquePtr<IPropertyValueStorage> > UE::MovieScene::FInitialValueCache::StorageByComponent private
Definition at line 156 of file MovieSceneInitialValueCache.h.
Referenced by FindStorage(), GetStorage(), and Reset().
The documentation for this struct was generated from the following file:
MovieSceneInitialValueCache.h