Unreal Engine 5.6 C++ API: FGraphPinHandle Struct Reference
FGraphPinHandle Struct Reference
A handle to a pin, defined by its owning node's GUID, and the pin's name.
#include "SGraphPin.h"
Public Member Functions
FGraphPinHandle ()=default
Default constructor Will contain a invalid node and pin GUID and IsValid() will return false.
FGraphPinHandle (UEdGraphPin *InPin)
Constructor.
TSharedPtr< class SGraphPin > FindInGraphPanel (const class SGraphPanel &InPanel) const
Find a pin widget in the specified panel from this handle.
UEdGraphPin * GetPinObj (const SGraphPanel &InPanel) const
bool IsValid () const
bool operator== (const FGraphPinHandle &Other) const
Data Fields
FGuid NodeGuid
The GUID of the node to which this pin belongs.
FGuid PinId
The GUID of the pin we are referencing.
Friends
uint32 GetTypeHash (const FGraphPinHandle &Handle)
Detailed Description
A handle to a pin, defined by its owning node's GUID, and the pin's name.
Used to reference a pin without referring to its widget
Definition at line 54 of file SGraphPin.h.
Constructor & Destructor Documentation
FGraphPinHandle() [1/2]
FGraphPinHandle::FGraphPinHandle () default
Default constructor Will contain a invalid node and pin GUID and IsValid() will return false.
Referenced by GetTypeHash, and operator==().
FGraphPinHandle() [2/2]
FGraphPinHandle::FGraphPinHandle (UEdGraphPin * InPin)
Constructor.
Member Function Documentation
FindInGraphPanel()
TSharedPtr< class SGraphPin > FGraphPinHandle::FindInGraphPanel (const class SGraphPanel & InPanel) const
Find a pin widget in the specified panel from this handle.
GetPinObj()
UEdGraphPin * FGraphPinHandle::GetPinObj (const SGraphPanel & InPanel) const
IsValid()
bool FGraphPinHandle::IsValid () const inline
Definition at line 78 of file SGraphPin.h.
References NodeGuid, and PinId.
operator==()
bool FGraphPinHandle::operator== (const FGraphPinHandle & Other) const inline
Definition at line 84 of file SGraphPin.h.
References FGraphPinHandle(), NodeGuid, Other, and PinId.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGraphPinHandle & Handle) friend
Definition at line 90 of file SGraphPin.h.
References FGraphPinHandle(), GetTypeHash, GetTypeHash(), Handle, and HashCombine().
Referenced by GetTypeHash.
Field Documentation
NodeGuid
FGuid FGraphPinHandle::NodeGuid
The GUID of the node to which this pin belongs.
Definition at line 57 of file SGraphPin.h.
Referenced by IsValid(), and operator==().
PinId
FGuid FGraphPinHandle::PinId
The GUID of the pin we are referencing.
Definition at line 60 of file SGraphPin.h.
Referenced by IsValid(), and operator==().
The documentation for this struct was generated from the following file:
SGraphPin.h