Unreal Engine 5.6 C++ API: FTSTicker Class Reference
FTSTicker Class Reference
Thread-safe ticker class.
#include "Ticker.h"
Data Structures
struct FElement
Internal structure to store a ticker delegate and related data.
Public Types
using FDelegateHandle = TWeakPtr<FElement>
Public Member Functions
FDelegateHandle AddTicker (const FTickerDelegate &InDelegate, float InDelay=0.0f)
Add a new ticker with a given delay / interval.
FDelegateHandle AddTicker (const TCHAR *InName, float InDelay, TUniqueFunction< bool(float)> &&InFunction)
Add a new ticker with a given delay / interval.
void Reset ()
Resets the instance to its default state.
void Tick (float DeltaTime)
Fire all tickers who have passed their delay and reschedule the ones that return true.
Static Public Member Functions
static FTSTicker & GetCoreTicker ()
Singleton used for the ticker in Core / Launch.
static void RemoveTicker (FDelegateHandle Handle)
Removes a previously added ticker delegate.
Private Types
using FElementPtr = TSharedPtr<FElement>
Private Attributes
TMpscQueue< FElementPtr > AddedElements
std::atomic< double > CurrentTime { 0.0 }
Current time of the ticker.
TArray< FElementPtr > Elements
Future delegates to fire.
Detailed Description
Thread-safe ticker class.
Fires delegates after a delay.
Definition at line 26 of file Ticker.h.
Member Typedef Documentation
FDelegateHandle
using FTSTicker::FDelegateHandle = TWeakPtr<FElement>
Definition at line 32 of file Ticker.h.
FElementPtr
using FTSTicker::FElementPtr = TSharedPtr<FElement> private
Definition at line 121 of file Ticker.h.
Member Function Documentation
AddTicker() [1/2]
FDelegateHandle FTSTicker::AddTicker (const FTickerDelegate & InDelegate, float InDelay = 0.0f)
Add a new ticker with a given delay / interval.
Can be called concurrently. Resources used by the delegate must be released on the ticking thread.
Parameters
InDelegate Delegate to fire after the delay
InDelay Delay until next fire; 0 means "next frame"
Referenced by Async(), and ExecuteOnGameThread().
AddTicker() [2/2]
FDelegateHandle FTSTicker::AddTicker (const TCHAR * InName, float InDelay, TUniqueFunction< bool(float)> && InFunction)
Add a new ticker with a given delay / interval.
Can be called concurrently.
Parameters
InName Name of this ticker for profiling
InDelay Delay until next fire; 0 means "next frame"
Function Function to execute. Should return true to fire after another InDelay time
References InName.
GetCoreTicker()
FTSTicker & FTSTicker::GetCoreTicker () static nodiscard
Singleton used for the ticker in Core / Launch.
If you add a new ticker for a different subsystem, do not put that singleton here!
Referenced by FTSTickerObjectBase::FTSTickerObjectBase(), Async(), and ExecuteOnGameThread().
RemoveTicker()
void FTSTicker::RemoveTicker (FDelegateHandle Handle) static
Removes a previously added ticker delegate.
Can be called concurrently. If is caleld in the middle of the delegate execution, it blocks until the execution finishes, and thus guarantees that the delegate won't be executed after the call.
Parameters
Handle The handle of the ticker to remove.
References Handle.
Reset()
void FTSTicker::Reset ()
Resets the instance to its default state.
Must be called from the ticking thread.
Tick()
void FTSTicker::Tick (float DeltaTime)
Fire all tickers who have passed their delay and reschedule the ones that return true.
Note: This reschedule has timer skew, meaning we always wait a full Delay period after each invocation even if we missed the last interval by a bit. For instance, setting a delay of 0.1 seconds will not necessarily fire the delegate 10 times per second, depending on the Tick() rate. What this DOES guarantee is that a delegate will never be called MORE FREQUENTLY than the Delay interval, regardless of how far we miss the scheduled interval.
Must not be called concurrently.
Parameters
DeltaTime time that has passed since the last tick call
References DeltaTime.
Field Documentation
AddedElements
TMpscQueue<FElementPtr> FTSTicker::AddedElements private
Definition at line 125 of file Ticker.h.
CurrentTime
std::atomic<double> FTSTicker::CurrentTime { 0.0 } private
Current time of the ticker.
Definition at line 128 of file Ticker.h.
Elements
TArray<FElementPtr> FTSTicker::Elements private
Future delegates to fire.
Definition at line 130 of file Ticker.h.
The documentation for this class was generated from the following file:
Ticker.h