Unreal Engine 5.6 C++ API: SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode > Class Template Reference
SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode > Class Template Reference
#include "SharedPointerInternals.h"
Public Member Functions
template<typename... ArgTypes>
TIntrusiveReferenceController (ArgTypes &&... Args)
TIntrusiveReferenceController (const TIntrusiveReferenceController &)=delete
virtual void DestroyObject () override
Destroys the object associated with this reference counter.
ObjectType * GetObjectPtr () const
TIntrusiveReferenceController & operator= (const TIntrusiveReferenceController &)=delete
Public Member Functions inherited from SharedPointerInternals::TReferenceControllerBase< Mode >
FORCEINLINE TReferenceControllerBase ()=default
TReferenceControllerBase (const TReferenceControllerBase &)=delete
virtual ~TReferenceControllerBase ()
FORCEINLINE void AddSharedReference ()
Adds a shared reference to this counter.
FORCEINLINE void AddWeakReference ()
Adds a weak reference to this counter.
bool ConditionallyAddSharedReference ()
Adds a shared reference to this counter ONLY if there is already at least one reference.
FORCEINLINE int32 GetSharedReferenceCount () const
Returns the shared reference count.
FORCEINLINE bool IsUnique () const
Checks if there is exactly one reference left to the object.
TReferenceControllerBase & operator= (const TReferenceControllerBase &)=delete
FORCEINLINE void ReleaseSharedReference ()
Releases a shared reference to this counter.
void ReleaseWeakReference ()
Releases a weak reference to this counter.
Private Attributes
TTypeCompatibleBytes< ObjectType > ObjectStorage
The object associated with this reference counter.
Additional Inherited Members
Data Fields inherited from SharedPointerInternals::TReferenceControllerBase< Mode >
RefCountType SharedReferenceCount {1}
RefCountType WeakReferenceCount {1}
Detailed Description
template<typename ObjectType, ESPMode Mode>
class SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >
Definition at line 388 of file SharedPointerInternals.h.
Constructor & Destructor Documentation
TIntrusiveReferenceController() [1/2]
template<typename ObjectType, ESPMode Mode> template<typename... ArgTypes> SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::TIntrusiveReferenceController (ArgTypes &&... Args) inline explicit
Definition at line 392 of file SharedPointerInternals.h.
References Forward(), and ObjectStorage.
Referenced by TIntrusiveReferenceController(), and operator=().
TIntrusiveReferenceController() [2/2]
template<typename ObjectType, ESPMode Mode> SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::TIntrusiveReferenceController (const TIntrusiveReferenceController< ObjectType, Mode > &) delete
References TIntrusiveReferenceController().
Member Function Documentation
DestroyObject()
template<typename ObjectType, ESPMode Mode> virtual void SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::DestroyObject () inline override virtual
Destroys the object associated with this reference counter.
Implements SharedPointerInternals::TReferenceControllerBase< Mode >.
Definition at line 422 of file SharedPointerInternals.h.
References DestructItem(), and ObjectStorage.
GetObjectPtr()
template<typename ObjectType, ESPMode Mode> ObjectType * SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::GetObjectPtr () const inline
Definition at line 417 of file SharedPointerInternals.h.
References ObjectStorage.
Referenced by MakeShared().
operator=()
template<typename ObjectType, ESPMode Mode> TIntrusiveReferenceController & SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::operator= (const TIntrusiveReferenceController< ObjectType, Mode > &) delete
References TIntrusiveReferenceController().
Field Documentation
ObjectStorage
template<typename ObjectType, ESPMode Mode> TTypeCompatibleBytes<ObjectType> SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::ObjectStorage mutable private
The object associated with this reference counter.
Definition at line 433 of file SharedPointerInternals.h.
Referenced by TIntrusiveReferenceController(), DestroyObject(), and GetObjectPtr().
The documentation for this class was generated from the following file:
SharedPointerInternals.h