Unreal Engine 5.6 C++ API: LowLevelTasks::FTask Class Reference
LowLevelTasks::FTask Class Reference final
#include "Task.h"
Data Structures
struct FInitData
Public Member Functions
FTask ()=default
~FTask ()
bool AllowBusyWaiting () const
bool AllowCancellation () const
const TCHAR * GetDebugName () const
FInitData GetInitData () const
ETaskPriority GetPriority () const
void * GetUserData () const
template<typename TRunnable>
void Init (const TCHAR *InDebugName, ETaskPriority InPriority, TRunnable &&InRunnable, ETaskFlags Flags=ETaskFlags::DefaultFlags)
template<typename TRunnable>
void Init (const TCHAR *InDebugName, TRunnable &&InRunnable, ETaskFlags Flags=ETaskFlags::DefaultFlags)
bool IsBackgroundTask () const
bool IsCompleted (std::memory_order MemoryOrder=std::memory_order_seq_cst) const
bool IsReady () const
void SetUserData (void *NewUserData) const
bool TryCancel (ECancellationFlags CancellationFlags=ECancellationFlags::DefaultFlags)
bool TryExecute ()
bool TryExecute (FTask *&Continuation)
bool TryExpedite ()
bool TryExpedite (FTask *&Continuation)
bool TryRevive ()
bool WasCanceled () const
bool WasExpedited () const
Static Public Member Functions
static const FTask * GetActiveTask ()
Private Member Functions
FTask * ExecuteTask ()
void InheritParentData (ETaskPriority &Priority)
template<bool bIsExpeditingThread>
void TryFinish ()
bool TryPrepareLaunch ()
UE_NONCOPYABLE (FTask)
bool WasCanceledOrIsExpediting () const
Static Private Member Functions
static bool PermitBackgroundWork ()
Static Private Attributes
static thread_local FTask * ActiveTask
Friends
class FScheduler
Detailed Description
Definition at line 309 of file Async/Fundamental/Task.h.
Constructor & Destructor Documentation
FTask()
LowLevelTasks::FTask::FTask () default
Referenced by ExecuteTask(), GetActiveTask(), InheritParentData(), Init(), TryExecute(), TryExecute(), TryExpedite(), TryExpedite(), and UE_NONCOPYABLE().
~FTask()
LowLevelTasks::FTask::~FTask () inline
Definition at line 514 of file Async/Fundamental/Task.h.
References checkf, IsCompleted(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and TEXT.
Member Function Documentation
AllowBusyWaiting()
bool LowLevelTasks::FTask::AllowBusyWaiting () const inline
Definition at line 652 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
AllowCancellation()
bool LowLevelTasks::FTask::AllowCancellation () const inline
Definition at line 657 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
ExecuteTask()
FTask * LowLevelTasks::FTask::ExecuteTask () inline private
Definition at line 618 of file Async/Fundamental/Task.h.
References FTask(), checkSlow, EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, LowLevelTasks::Tasks_Impl::FTaskBase::Runnable, and TryFinish().
Referenced by TryCancel(), and TryExecute().
GetActiveTask()
const FTask * LowLevelTasks::FTask::GetActiveTask () static
References FTask(), ActiveTask, and FORCEINLINE.
Referenced by TLocalWorkQueue< TaskType >::TLocalWorkQueue(), and InheritParentData().
GetDebugName()
const TCHAR * LowLevelTasks::FTask::GetDebugName () const inline
Definition at line 642 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
GetInitData()
FTask::FInitData LowLevelTasks::FTask::GetInitData () const inline
Definition at line 662 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetDebugName(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetPriority(), and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
GetPriority()
ETaskPriority LowLevelTasks::FTask::GetPriority () const inline
Definition at line 448 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
Referenced by InheritParentData().
GetUserData()
void * LowLevelTasks::FTask::GetUserData () const inline
Definition at line 422 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::UserData.
Referenced by InheritParentData().
InheritParentData()
void LowLevelTasks::FTask::InheritParentData (ETaskPriority & Priority) inline private
Definition at line 453 of file Async/Fundamental/Task.h.
References FTask(), LowLevelTasks::Default, GetActiveTask(), GetPriority(), GetUserData(), LowLevelTasks::Inherit, and LowLevelTasks::Tasks_Impl::FTaskBase::UserData.
Referenced by Init().
Init() [1/2]
template<typename TRunnable> void LowLevelTasks::FTask::Init (const TCHAR * InDebugName, ETaskPriority InPriority, TRunnable && InRunnable, ETaskFlags Flags = ETaskFlags::DefaultFlags) inline
Definition at line 475 of file Async/Fundamental/Task.h.
References FTask(), checkf, checkSlow, Flags, Forward(), InheritParentData(), IsCompleted(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, LowLevelTasks::Tasks_Impl::FTaskBase::Runnable, and TEXT.
Referenced by FQueuedLowLevelThreadPool::AddQueuedWork().
Init() [2/2]
template<typename TRunnable> void LowLevelTasks::FTask::Init (const TCHAR * InDebugName, TRunnable && InRunnable, ETaskFlags Flags = ETaskFlags::DefaultFlags) inline
Definition at line 509 of file Async/Fundamental/Task.h.
References LowLevelTasks::Default, Flags, Forward(), and Init.
IsBackgroundTask()
bool LowLevelTasks::FTask::IsBackgroundTask () const inline
Definition at line 647 of file Async/Fundamental/Task.h.
References LowLevelTasks::ForegroundCount, and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
IsCompleted()
bool LowLevelTasks::FTask::IsCompleted (std::memory_order MemoryOrder = std::memory_order_seq_cst) const inline
Definition at line 321 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and State.
Referenced by ~FTask(), and Init().
IsReady()
bool LowLevelTasks::FTask::IsReady () const inline
Definition at line 357 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and State.
PermitBackgroundWork()
bool LowLevelTasks::FTask::PermitBackgroundWork () inline static private
Definition at line 430 of file Async/Fundamental/Task.h.
References ActiveTask.
SetUserData()
void LowLevelTasks::FTask::SetUserData (void * NewUserData) const inline
Definition at line 423 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::UserData.
TryCancel()
bool LowLevelTasks::FTask::TryCancel (ECancellationFlags CancellationFlags = ECancellationFlags::DefaultFlags) inline
Definition at line 524 of file Async/Fundamental/Task.h.
References EnumHasAllFlags(), EnumHasAnyFlags(), ExecuteTask(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, LowLevelTasks::PrelaunchCancellation, LowLevelTasks::TryLaunchOnSuccess, TryPrepareLaunch(), verifySlow, and WasCanceled().
TryExecute() [1/2]
bool LowLevelTasks::FTask::TryExecute () inline
Definition at line 570 of file Async/Fundamental/Task.h.
References FTask(), checkSlow, and TryExecute().
Referenced by TryExecute().
TryExecute() [2/2]
bool LowLevelTasks::FTask::TryExecute (FTask *& Continuation) inline
Definition at line 560 of file Async/Fundamental/Task.h.
References FTask(), ExecuteTask(), and TryPrepareLaunch().
TryExpedite() [1/2]
bool LowLevelTasks::FTask::TryExpedite () inline
Definition at line 610 of file Async/Fundamental/Task.h.
References FTask(), checkSlow, and TryExpedite().
Referenced by TryExpedite().
TryExpedite() [2/2]
bool LowLevelTasks::FTask::TryExpedite (FTask *& Continuation) inline
Definition at line 597 of file Async/Fundamental/Task.h.
References FTask(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, LowLevelTasks::Tasks_Impl::FTaskBase::Runnable, and TryFinish().
TryFinish()
template<bool bIsExpeditingThread> void LowLevelTasks::FTask::TryFinish () inline private
Definition at line 579 of file Async/Fundamental/Task.h.
References checkSlow, EnumHasAnyFlags(), MoveTemp(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and LowLevelTasks::Tasks_Impl::FTaskBase::Runnable.
Referenced by ExecuteTask(), and TryExpedite().
TryPrepareLaunch()
bool LowLevelTasks::FTask::TryPrepareLaunch () inline private
Definition at line 519 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
Referenced by TryCancel(), and TryExecute().
TryRevive()
bool LowLevelTasks::FTask::TryRevive () inline
Definition at line 545 of file Async/Fundamental/Task.h.
References checkSlow, EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::GetState(), and LowLevelTasks::Tasks_Impl::FTaskBase::PackedData.
UE_NONCOPYABLE()
LowLevelTasks::FTask::UE_NONCOPYABLE (FTask) private
References FTask().
WasCanceled()
bool LowLevelTasks::FTask::WasCanceled () const inline
Definition at line 330 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and State.
Referenced by TryCancel().
WasCanceledOrIsExpediting()
bool LowLevelTasks::FTask::WasCanceledOrIsExpediting () const inline private
Definition at line 347 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and State.
WasExpedited()
bool LowLevelTasks::FTask::WasExpedited () const inline
Definition at line 339 of file Async/Fundamental/Task.h.
References EnumHasAnyFlags(), LowLevelTasks::Tasks_Impl::FTaskBase::PackedData, and State.
Friends And Related Symbol Documentation
FScheduler
friend class FScheduler friend
Definition at line 311 of file Async/Fundamental/Task.h.
References FScheduler.
Referenced by FScheduler.
Field Documentation
ActiveTask
thread_local FTask* LowLevelTasks::FTask::ActiveTask static private
Definition at line 314 of file Async/Fundamental/Task.h.
Referenced by GetActiveTask(), and PermitBackgroundWork().
The documentation for this class was generated from the following file:
Async/Fundamental/Task.h