Unreal Engine 5.6 C++ API: FObjectEditorUtils Namespace Reference
FObjectEditorUtils Namespace Reference
Functions
FString GetCategory (const FField *InField)
Gets the category this field belongs to.
FString GetCategory (const UField *InField)
Gets the category this field belongs to.
FName GetCategoryFName (const FField *InField)
Gets the FName of the category this field belongs to.
FName GetCategoryFName (const UField *InField)
Gets the FName of the category this field belongs to.
FText GetCategoryText (const FField *InField)
Gets the category this field belongs to.
FText GetCategoryText (const FName InName)
Gets the category text from this category FName.
FText GetCategoryText (const UField *InField)
Gets the category this field belongs to.
void GetClassDevelopmentStatus (UClass *Class, bool &bIsExperimental, bool &bIsEarlyAccess, FString &MostDerivedClassName)
Get the classes development status and return if it's either experimental or early access.
template<typename T>
static TArray< TWeakObjectPtr< T > > GetTypedWeakObjectPtrs (const TArray< UObject * > &InObjects)
Helper function to convert the input for GetActions to a list that can be used for delegates.
bool IsFunctionHiddenFromClass (const UFunction *InFunction, const UClass *Class)
Query if a function is flagged as hidden from the given class either by category or by function name.
bool IsStructExperimentalForValkyrie (const UStruct &Struct)
Check if this struct is experimental for Valkyrie.
bool IsStructValkyrieDeprecatedForValkyrie (const UStruct &Struct)
Check if this struct is deprecated for Valkyrie.
bool IsVariableCategoryHiddenFromClass (const FProperty *InVariable, const UClass *Class)
Query if a the category a variable belongs to is flagged as hidden from the given class.
template<typename SourceType, typename DestinationType>
bool MigratePropertyValue (SourceType *SourceObject, FName SourcePropertyName, DestinationType *DestinationObject, FName DestinationPropertyName)
Copy the value of a property from source object to a destination object.
bool MigratePropertyValue (UObject *SourceObject, FProperty *SourceProperty, UObject *DestinationObject, FProperty *DestinationProperty)
Copy the value of a property from source object to a destination object.
template<typename ObjectType, typename ValueType>
bool SetPropertyValue (ObjectType *Object, FName PropertyName, ValueType Value)
Set the value on an UObject using reflection.
Function Documentation
GetCategory() [1/2]
FString FObjectEditorUtils::GetCategory (const FField * InField)
Gets the category this field belongs to.
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetCategory() [2/2]
FString FObjectEditorUtils::GetCategory (const UField * InField)
Gets the category this field belongs to.
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetCategoryFName() [1/2]
FName FObjectEditorUtils::GetCategoryFName (const FField * InField)
Gets the FName of the category this field belongs to.
Note, this value is suitable for comparison against other categories but NOT suitable as a display name since it is not localized
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetCategoryFName() [2/2]
FName FObjectEditorUtils::GetCategoryFName (const UField * InField)
Gets the FName of the category this field belongs to.
Note, this value is suitable for comparison against other categories but NOT suitable as a display name since it is not localized
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetCategoryText() [1/3]
FText FObjectEditorUtils::GetCategoryText (const FField * InField)
Gets the category this field belongs to.
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetCategoryText() [2/3]
FText FObjectEditorUtils::GetCategoryText (const FName InName)
Gets the category text from this category FName.
Parameters
InName Category FName we want the text for
Returns
Category text for the provided category name
References InName.
GetCategoryText() [3/3]
FText FObjectEditorUtils::GetCategoryText (const UField * InField)
Gets the category this field belongs to.
Parameters
InField Field we want the category name of.
Returns
Category name of the given field.
GetClassDevelopmentStatus()
void FObjectEditorUtils::GetClassDevelopmentStatus (UClass * Class, bool & bIsExperimental, bool & bIsEarlyAccess, FString & MostDerivedClassName)
Get the classes development status and return if it's either experimental or early access.
Parameters
Class the class to inspect.
bIsExperimental [out] value indicating if the class is experimental.
bIsEarlyAccess [out] value indicating if the class is early access.
MostDerivedClassName [out] The name of the most derived class that is marked as experimental or early access (or empty string)
References Class.
GetTypedWeakObjectPtrs()
template<typename T> TArray< TWeakObjectPtr< T > > FObjectEditorUtils::GetTypedWeakObjectPtrs (const TArray< UObject * > & InObjects) static
Helper function to convert the input for GetActions to a list that can be used for delegates.
Definition at line 192 of file ObjectEditorUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), CastChecked(), check, TArray< InElementType, InAllocatorType >::CreateConstIterator(), and TArray< InElementType, InAllocatorType >::Num().
IsFunctionHiddenFromClass()
bool FObjectEditorUtils::IsFunctionHiddenFromClass (const UFunction * InFunction, const UClass * Class)
Query if a function is flagged as hidden from the given class either by category or by function name.
Parameters
InFunction Function to check
InClass Class to check hidden if the function is hidden in
Returns
true if the function is hidden in the specified class.
References Class.
IsStructExperimentalForValkyrie()
bool FObjectEditorUtils::IsStructExperimentalForValkyrie (const UStruct & Struct)
Check if this struct is experimental for Valkyrie.
Parameters
Struct the struct to inspect
Returns
true if it is experimental, otherwise false
References Struct.
IsStructValkyrieDeprecatedForValkyrie()
bool FObjectEditorUtils::IsStructValkyrieDeprecatedForValkyrie (const UStruct & Struct)
Check if this struct is deprecated for Valkyrie.
Parameters
Struct the struct to inspect
Returns
true if it is deprecated, otherwise false
References Struct.
IsVariableCategoryHiddenFromClass()
bool FObjectEditorUtils::IsVariableCategoryHiddenFromClass (const FProperty * InVariable, const UClass * Class)
Query if a the category a variable belongs to is flagged as hidden from the given class.
Parameters
InVariable Property to check
InClass Class to check hidden if the function is hidden in
Returns
true if the functions category is hidden in the specified class.
References Class.
MigratePropertyValue() [1/2]
template<typename SourceType, typename DestinationType> bool FObjectEditorUtils::MigratePropertyValue (SourceType * SourceObject, FName SourcePropertyName, DestinationType * DestinationObject, FName DestinationPropertyName)
Copy the value of a property from source object to a destination object.
Parameters
SourceObject The object to copy the property value from.
SourcePropertyName The name of the property on the SourceObject to copy the value from.
DestinationObject The object to copy the property value to.
DestinationPropertyName The name of the property on the DestinationObject to copy the value to.
Returns
true if the value was successfully migrated.
Definition at line 141 of file ObjectEditorUtils.h.
References FindFieldChecked(), and MigratePropertyValue().
MigratePropertyValue() [2/2]
bool FObjectEditorUtils::MigratePropertyValue (UObject * SourceObject, FProperty * SourceProperty, UObject * DestinationObject, FProperty * DestinationProperty)
Copy the value of a property from source object to a destination object.
Parameters
SourceObject The object to copy the property value from.
SourceProperty The property on the SourceObject to copy the value from.
DestinationObject The object to copy the property value to.
DestinationProperty The property on the DestinationObject to copy the value to.
Returns
true if the value was successfully migrated.
Referenced by MigratePropertyValue().
SetPropertyValue()
template<typename ObjectType, typename ValueType> bool FObjectEditorUtils::SetPropertyValue (ObjectType * Object, FName PropertyName, ValueType Value)
Set the value on an UObject using reflection.
Parameters
Object The object to copy the value into.
PropertyName The name of the property to set.
Value The value to assign to the property.
Returns
true if the value was set correctly
Definition at line 158 of file ObjectEditorUtils.h.
References TDoubleLinkedList< ElementType >::AddHead(), FindFieldChecked(), Object, Property, PropertyName, RF_ClassDefaultObject, and Value.