Unreal Engine 5.6 C++ API: UE::MovieScene::FPreAnimatedStorageGroupHandle Struct Reference
UE::MovieScene::FPreAnimatedStorageGroupHandle Struct Reference
#include "MovieScenePreAnimatedStateTypes.h"
Public Member Functions
FPreAnimatedStorageGroupHandle ()
FPreAnimatedStorageGroupHandle (int32 InNewValue)
bool IsValid () const
operator bool () const
operator int32 () const
FPreAnimatedStorageGroupHandle & operator= (int32 InNewValue)
Data Fields
int32 Value
Friends
uint32 GetTypeHash (const FPreAnimatedStorageGroupHandle &InHandle)
bool operator== (const FPreAnimatedStorageGroupHandle &A, const FPreAnimatedStorageGroupHandle &B)
Detailed Description
Definition at line 85 of file MovieScenePreAnimatedStateTypes.h.
Constructor & Destructor Documentation
FPreAnimatedStorageGroupHandle() [1/2]
UE::MovieScene::FPreAnimatedStorageGroupHandle::FPreAnimatedStorageGroupHandle () inline
Definition at line 87 of file MovieScenePreAnimatedStateTypes.h.
References INDEX_NONE, and Value.
Referenced by GetTypeHash, operator=(), and operator==.
FPreAnimatedStorageGroupHandle() [2/2]
UE::MovieScene::FPreAnimatedStorageGroupHandle::FPreAnimatedStorageGroupHandle (int32 InNewValue) inline
Definition at line 91 of file MovieScenePreAnimatedStateTypes.h.
References Value.
Member Function Documentation
IsValid()
bool UE::MovieScene::FPreAnimatedStorageGroupHandle::IsValid () const inline
Definition at line 101 of file MovieScenePreAnimatedStateTypes.h.
References INDEX_NONE, and Value.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue().
operator bool()
UE::MovieScene::FPreAnimatedStorageGroupHandle::operator bool () const inline explicit
Definition at line 106 of file MovieScenePreAnimatedStateTypes.h.
References INDEX_NONE, and Value.
operator int32()
UE::MovieScene::FPreAnimatedStorageGroupHandle::operator int32 () const inline
Definition at line 111 of file MovieScenePreAnimatedStateTypes.h.
References check, INDEX_NONE, and Value.
operator=()
FPreAnimatedStorageGroupHandle & UE::MovieScene::FPreAnimatedStorageGroupHandle::operator= (int32 InNewValue) inline
Definition at line 95 of file MovieScenePreAnimatedStateTypes.h.
References FPreAnimatedStorageGroupHandle(), and Value.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPreAnimatedStorageGroupHandle & InHandle) friend
Definition at line 117 of file MovieScenePreAnimatedStateTypes.h.
References FPreAnimatedStorageGroupHandle(), and Value.
operator==
bool operator== (const FPreAnimatedStorageGroupHandle & A, const FPreAnimatedStorageGroupHandle & B) friend
Definition at line 121 of file MovieScenePreAnimatedStateTypes.h.
References FPreAnimatedStorageGroupHandle(), A, and B.
Field Documentation
Value
int32 UE::MovieScene::FPreAnimatedStorageGroupHandle::Value
Definition at line 126 of file MovieScenePreAnimatedStateTypes.h.
Referenced by FPreAnimatedStorageGroupHandle(), FPreAnimatedStorageGroupHandle(), GetTypeHash, IsValid(), operator bool(), operator int32(), and operator=().
The documentation for this struct was generated from the following file:
MovieScenePreAnimatedStateTypes.h