Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolSequence Class Reference
UE::SequenceNavigator::FNavigationToolSequence Class Reference
Item in Navigation Tool representing a Sequence.
#include "NavigationToolSequence.h"
Public Member Functions
SEQUENCENAVIGATOR_API FNavigationToolSequence (INavigationTool &InTool, const FNavigationToolItemPtr &InParentItem, UMovieSceneSequence *const InSequence, UMovieSceneSubSection *const InSubSection, const int32 InSubSectionIndex)
virtual SEQUENCENAVIGATOR_API bool AddChild (const FNavigationToolAddItemParams &InAddItemParams) override
Adds another Child under this Item if such Item is supported.
virtual bool CanBeTopLevel () const override
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
virtual SEQUENCENAVIGATOR_API bool CanRename () const override
virtual SEQUENCENAVIGATOR_API EItemContainsPlayhead ContainsPlayhead () const override
virtual SEQUENCENAVIGATOR_API void FindChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive) override
Figures out the Children of this Item.
virtual SEQUENCENAVIGATOR_API FText GetClassName () const override
Gets the Class/Type of this Item (e.g.
virtual SEQUENCENAVIGATOR_API TOptional< FColor > GetColor () const override
virtual FText GetDisplayName () const override
Gets the Display Name Text of the Item.
virtual FSlateIcon GetIcon () const override
Gets the slate icon for the item.
virtual SEQUENCENAVIGATOR_API FText GetIconTooltipText () const override
Gets the tooltip text for the item icon.
virtual SEQUENCENAVIGATOR_API EItemSequenceInactiveState GetInactiveState () const override
virtual SEQUENCENAVIGATOR_API FFrameNumber GetInTime () const override
virtual SEQUENCENAVIGATOR_API UObject * GetItemObject () const override
Gets the UObject that this item represents.
virtual SEQUENCENAVIGATOR_API void GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > &OutItemProxies) override
Gets the Item Proxies for this Item (e.g.
virtual SEQUENCENAVIGATOR_API EItemSequenceLockState GetLockState () const override
virtual SEQUENCENAVIGATOR_API EItemMarkerVisibility GetMarkerVisibility () const override
virtual SEQUENCENAVIGATOR_API FFrameNumber GetOutTime () const override
virtual SEQUENCENAVIGATOR_API EItemRevisionControlState GetRevisionControlState () const override
virtual SEQUENCENAVIGATOR_API const FSlateBrush * GetRevisionControlStatusIcon () const override
virtual SEQUENCENAVIGATOR_API FText GetRevisionControlStatusText () const override
SEQUENCENAVIGATOR_API UMovieSceneSequence * GetSequence () const
SEQUENCENAVIGATOR_API UMovieScene * GetSequenceMovieScene () const
SEQUENCENAVIGATOR_API TArray< FMovieSceneBinding > GetSortedBindings () const
SEQUENCENAVIGATOR_API UMovieSceneSubSection * GetSubSection () const
SEQUENCENAVIGATOR_API int32 GetSubSectionIndex () const
virtual SEQUENCENAVIGATOR_API ENavigationToolItemViewMode GetSupportedViewModes (const INavigationToolView &InToolView) const override
Gets the View Modes that this Item Supports.
UE::Sequencer::TViewModelPtr< UE::Sequencer::FSectionModel > GetViewModel () const
virtual SEQUENCENAVIGATOR_API bool IsAllowedInTool () const override
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
virtual SEQUENCENAVIGATOR_API bool IsItemValid () const override
Determines whether the Item properties are in a valid state.
virtual SEQUENCENAVIGATOR_API bool IsSelected (const FNavigationToolScopedSelection &InSelection) const override
Determines whether the given Item is selected in the given Scoped Selection.
virtual SEQUENCENAVIGATOR_API void OnDoubleClick () override
Called when an Item is double-clicked with the mouse.
virtual SEQUENCENAVIGATOR_API void OnObjectsReplaced (const TMap< UObject *, UObject * > &InReplacementMap, bool bInRecursive) override
Called when objects have been replaced on the Engine side.
virtual SEQUENCENAVIGATOR_API void OnSelect () override
Called when an Item is selected.
virtual SEQUENCENAVIGATOR_API bool RemoveChild (const FNavigationToolRemoveItemParams &InRemoveItemParams) override
Removes the given child from this Item if it was ever indeed a child.
virtual SEQUENCENAVIGATOR_API bool Rename (const FString &InName) override
The implementation to rename the item.
virtual SEQUENCENAVIGATOR_API void Select (FNavigationToolScopedSelection &InSelection) const override
Used to signal the Scoped Selection that this Item should be Selected.
virtual SEQUENCENAVIGATOR_API void SetColor (const TOptional< FColor > &InColor) override
virtual SEQUENCENAVIGATOR_API void SetInTime (const FFrameNumber &InTime) override
virtual SEQUENCENAVIGATOR_API void SetIsInactive (const bool bInIsInactive) override
virtual SEQUENCENAVIGATOR_API void SetIsLocked (const bool bInIsLocked) override
virtual SEQUENCENAVIGATOR_API void SetMarkerVisibility (const bool bInVisible) override
virtual SEQUENCENAVIGATOR_API void SetOutTime (const FFrameNumber &InTime) override
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolSequence, FNavigationToolItem, IRenameableExtension, ISequenceInactivableExtension, ISequenceLockableExtension, IMarkerVisibilityExtension, IRevisionControlExtension, IPlayheadExtension, IInTimeExtension, IOutTimeExtension)
Public Member Functions inherited from UE::SequenceNavigator::FNavigationToolItem
FNavigationToolItem (INavigationTool &InTool, const FNavigationToolItemPtr &InParentItem)
virtual FReply AcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Processes the Drag and Drop Event for this Item.
virtual void AddFlags (ENavigationToolItemFlags Flags) override
virtual TOptional< EItemDropZone > CanAcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Determines if and where the incoming Drag Drop Event can be processed by this item.
virtual bool CanAddChild (const FNavigationToolItemPtr &InChild) const override
Determines whether the given Child is supported and can be added under this Item.
virtual bool CanAutoExpand () const override
Whether the Item is able to expand when AutoExpand functionality is enabled.
virtual bool CanDelete () const override
Whether this Item can be deleted or not.
virtual bool CanReceiveParentVisibilityPropagation () const override
Whether a change in Parent Visibility should also affect this Item's Visibility.
DECLARE_DELEGATE_RetVal_OneParam (FNavigationToolSaveState *, FNavigationToolGetToolState, const FNavigationToolItemPtr)
virtual bool Delete () override
The implementation to delete the item.
virtual TArray< FNavigationToolItemPtr > FindPath (const TArray< FNavigationToolItemPtr > &InItems) const override
virtual void FindValidChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive) override
virtual TSharedRef< SWidget > GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > &InRow) override
Function responsible of Generating the Label Widget for this Item (i.e.
virtual IndexType GetChildIndex (const FNavigationToolItemPtr &ChildItem) const override
Gets the Index that the given Child Item is at.
virtual const TArray< FNavigationToolItemPtr > & GetChildren () const override
Gets the current Child Items of this Item.
virtual TArray< FNavigationToolItemPtr > & GetChildrenMutable () override
Gets the current Child Items of this Item.
virtual ENavigationToolItemFlags GetFlags () const override
virtual const FSlateBrush * GetIconBrush () const override
virtual FSlateColor GetIconColor () const override
Gets the color for the item icon.
virtual FNavigationToolItemId GetItemId () const override final
Gets the Id of this Item.
virtual FSlateColor GetItemLabelColor () const override
Gets the color to use for the item label.
virtual FLinearColor GetItemTintColor () const override
Gets the color to use to tint the entire item row (all column content)
virtual INavigationTool & GetOwnerTool () const final override
Gets the Navigation Tool that owns this item.
virtual FNavigationToolItemPtr GetParent () const override
Gets the Parent of this Item.
virtual TSharedPtr< FNavigationToolProvider > GetProvider () const final override
Gets the module provider responsible for the creation of this item.
virtual FNavigationToolSaveState * GetProviderSaveState () const override
Gets the providers saved state.
virtual TArray< FName > GetTags () const override
Gets the Tags found for this Item (e.g.
virtual bool GetVisibility () const override
Whether this Item is currently visible or not for the Given Type.
virtual bool HasAllFlags (ENavigationToolItemFlags Flags) const override
virtual bool HasAnyFlags (ENavigationToolItemFlags Flags) const override
virtual bool IsExpanded () const override
Gets whether this item is expanded.
virtual FOnExpansionChanged & OnExpansionChanged () override
Called when Expansion state (Expanded/Collapsed) has been changed.
virtual FOnRenameAction & OnRenameAction () override
Broadcasts whenever a rename action takes place from a given view (e.g.
virtual void RefreshChildren () override
Refreshes what the Parent and Children are of this Item.
virtual void RemoveFlags (ENavigationToolItemFlags Flags) override
virtual void ResetChildren () override
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
virtual void SetExpansion (const bool bInExpand) override
Sets the expansion state of this item.
virtual void SetFlags (ENavigationToolItemFlags InFlags) override
virtual void SetParent (FNavigationToolItemPtr InParent) override
Sets the Parent.
virtual bool ShouldSort () const override
Determines whether this item can be sorted by the Navigation Tool or not.
virtual bool ShowVisibility () const override
Whether this Item supports Visibility for the Given Type.
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItem, INavigationToolItem, IColorExtension)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItem
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false)
Finds the first ancestor view model that implements the given type.
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false) const
template<typename InItemType>
TArray< InItemType * > FindAncestorsOfType (const bool bInIncludeThis=false) const
virtual FNavigationToolItemPtr GetChildAt (const IndexType Index) const
template<typename InItemType>
TArray< InItemType * > GetChildrenOfType (const bool bInIncludeThis=false) const
virtual const FSlateBrush * GetDefaultIconBrush () const
TArray< FNavigationToolItemPtr > GetDescendants (const bool bInIncludeThis=false)
template<typename InItemType>
TArray< InItemType * > GetDescendantsOfType (const bool bInIncludeThis=false) const
FString GetFullPath () const
Returns the path to this item in the tree.
virtual int32 GetItemTreeHeight () const
Returns the item's height in tree, Root Item should return 0 as it has no Parent.
virtual TSet< FNavigationToolItemPtr > GetParents (const bool bInIncludeRoot=false) const
Gets the list of all parents up the tree from this Item.
bool IsIgnoringPendingKill () const
Whether Ignoring Pending Kill.
virtual bool IsSelectable () const
Whether the Item can be selected in Navigation Tool at all.
virtual bool IsViewModeSupported (const ENavigationToolItemViewMode InViewMode, const INavigationToolView &InToolView) const
Whether this Item should be visualized in the given View Mode, for the given Navigation Tool View.
virtual FNavigationToolSerializedItem MakeSerializedItem ()
Converts this Navigation Tool item to a serialized item that can be saved in the sequence.
virtual void OnItemRegistered ()
Called when the Item has been registered into the Navigation Tool.
virtual void OnItemSelectionChanged (const bool bInIsSelected)
Called when the Item been selected/deselected from the Tree View.
virtual void OnItemUnregistered ()
Called when the Item has been unregistered from the Navigation Tool.
virtual void OnVisibilityChanged (const bool bInNewVisibility)
Called when the Visibility on Item has been changed on the Navigation Tool side.
UE_NAVIGATIONTOOL_INHERITS (INavigationToolItem, INavigationToolItemTypeCastable)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
virtual ~INavigationToolItemTypeCastable ()=default
template<typename InType>
InType * CastTo ()
template<typename InType>
const InType * CastTo () const
virtual const void * CastTo_Impl (FNavigationToolItemTypeId InId) const =0
virtual FNavigationToolItemTypeId GetTypeId () const =0
template<typename InType>
bool IsA () const
template<typename InType>
bool IsExactlyA () const
Public Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedRef< INavigationToolItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< INavigationToolItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::SequenceNavigator::IColorExtension
UE_NAVIGATIONTOOL_INHERITS (IColorExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual TOptional< FColor > GetColor() const =0
Public Member Functions inherited from UE::SequenceNavigator::IRenameableExtension
UE_NAVIGATIONTOOL_INHERITS (IRenameableExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual bool CanRename() const =0
Public Member Functions inherited from UE::SequenceNavigator::IInTimeExtension
UE_NAVIGATIONTOOL_INHERITS (IInTimeExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual FFrameNumber GetInTime() const =0
Public Member Functions inherited from UE::SequenceNavigator::IOutTimeExtension
UE_NAVIGATIONTOOL_INHERITS (IOutTimeExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual FFrameNumber GetOutTime() const =0
Protected Member Functions
virtual SEQUENCENAVIGATOR_API FNavigationToolItemId CalculateItemId () const override
Gets the Item Id with the latest information (e.g.
Protected Member Functions inherited from UE::SequenceNavigator::FNavigationToolItem
void AddChildChecked (const FNavigationToolAddItemParams &InAddItemParams)
The actual implementation of putting the given Item under the Children array.
void HandleNewSortableChildren (TArray< FNavigationToolItemPtr > InSortableChildren)
Careful handling of multiple children being detected and added to this item children array.
void RecalculateItemId ()
Sets the ItemId member var to what CalculateItemId returns.
bool RemoveChildChecked (const FNavigationToolRemoveItemParams &InRemoveItemParams)
The actual implementation of removing the given item from the Children array.
void SetProvider (const TWeakPtr< FNavigationToolProvider > &InWeakProvider)
Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
int32 SubSectionIndex = 0
TWeakObjectPtr< UMovieSceneSequence > WeakSequence
TWeakObjectPtr< UMovieSceneSubSection > WeakSubSection
Protected Attributes inherited from UE::SequenceNavigator::FNavigationToolItem
TArray< FNavigationToolItemPtr > Children
Array of Shared pointers to the Child Items.
ENavigationToolItemFlags ItemFlags = ENavigationToolItemFlags::None
The current flags set for this item.
FNavigationToolItemId ItemId
FOnExpansionChanged OnExpansionChangedDelegate
Delegate for when Expansion changes in the Item.
FOnRenameAction OnRenameActionDelegate
The delegate for renaming.
INavigationTool & Tool
Reference to the Owning Navigation Tool.
FNavigationToolItemWeakPtr WeakParent
Weak pointer to the Parent Item.
TWeakPtr< FNavigationToolProvider > WeakProvider
Tool provider that is responsible for the creation of this item.
Additional Inherited Members
Public Types inherited from UE::SequenceNavigator::INavigationToolItem
using FOnExpansionChanged = TMulticastDelegate<void(const TSharedPtr<INavigationToolView>&, bool)>
Delegate signature for when the Item Expansion Changes const TSharedPtr<FNavigationToolView>& - The Navigation Tool View where this Expansion happened bool - Whether the Item is expanded.
using FOnRenameAction = TMulticastDelegate<void(ENavigationToolRenameAction, const TSharedPtr<INavigationToolView>&)>
Delegate signature for relaying an Item Rename action ENavigationToolRenameAction the type of action being relayed (e.g.
Public Types inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
using FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Static Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
static FNavigationToolItemTypeId GetStaticTypeId ()
Protected Types inherited from UE::SequenceNavigator::INavigationToolItem
using IndexType = TArray<INavigationToolItem>::SizeType
Static Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Item in Navigation Tool representing a Sequence.
Definition at line 32 of file NavigationToolSequence.h.
Constructor & Destructor Documentation
FNavigationToolSequence()
SEQUENCENAVIGATOR_API UE::SequenceNavigator::FNavigationToolSequence::FNavigationToolSequence (INavigationTool & InTool, const FNavigationToolItemPtr & InParentItem, UMovieSceneSequence *const InSequence, UMovieSceneSubSection *const InSubSection, const int32 InSubSectionIndex)
References UE::SequenceNavigator::FNavigationToolItem::INavigationTool.
Referenced by UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER().
Member Function Documentation
AddChild()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::AddChild (const FNavigationToolAddItemParams & InAddItemParams) override virtual
Adds another Child under this Item if such Item is supported.
Returns true if it did, false if it could not add it (e.g. item not supported).
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
CalculateItemId()
virtual SEQUENCENAVIGATOR_API FNavigationToolItemId UE::SequenceNavigator::FNavigationToolSequence::CalculateItemId () const override protected virtual
Gets the Item Id with the latest information (e.g.
parent, object, etc)
Implements UE::SequenceNavigator::FNavigationToolItem.
CanBeTopLevel()
virtual bool UE::SequenceNavigator::FNavigationToolSequence::CanBeTopLevel () const inline override virtual
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
Actors can be Top Level, but Components or Materials can't
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
Definition at line 74 of file NavigationToolSequence.h.
CanRename()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::CanRename () const override virtual
ContainsPlayhead()
virtual SEQUENCENAVIGATOR_API EItemContainsPlayhead UE::SequenceNavigator::FNavigationToolSequence::ContainsPlayhead () const override virtual
FindChildren()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::FindChildren (TArray< FNavigationToolItemPtr > & OutChildren, const bool bInRecursive) override virtual
Figures out the Children of this Item.
This is only relevant for items that do have that functionality (e.g. Components or Actors)
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetClassName()
virtual SEQUENCENAVIGATOR_API FText UE::SequenceNavigator::FNavigationToolSequence::GetClassName () const override virtual
Gets the Class/Type of this Item (e.g.
for Items that represent UObjects, it will be the UObject class)
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetColor()
virtual SEQUENCENAVIGATOR_API TOptional< FColor > UE::SequenceNavigator::FNavigationToolSequence::GetColor () const override virtual
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetDisplayName()
virtual FText UE::SequenceNavigator::FNavigationToolSequence::GetDisplayName () const override virtual
Gets the Display Name Text of the Item.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetIcon()
virtual FSlateIcon UE::SequenceNavigator::FNavigationToolSequence::GetIcon () const override virtual
Gets the slate icon for the item.
Implements UE::SequenceNavigator::INavigationToolItem.
GetIconTooltipText()
virtual SEQUENCENAVIGATOR_API FText UE::SequenceNavigator::FNavigationToolSequence::GetIconTooltipText () const override virtual
Gets the tooltip text for the item icon.
Implements UE::SequenceNavigator::INavigationToolItem.
GetInactiveState()
virtual SEQUENCENAVIGATOR_API EItemSequenceInactiveState UE::SequenceNavigator::FNavigationToolSequence::GetInactiveState () const override virtual
GetInTime()
virtual SEQUENCENAVIGATOR_API FFrameNumber UE::SequenceNavigator::FNavigationToolSequence::GetInTime () const override virtual
GetItemObject()
virtual SEQUENCENAVIGATOR_API UObject * UE::SequenceNavigator::FNavigationToolSequence::GetItemObject () const override virtual
Gets the UObject that this item represents.
May be null due if no item association or multiple.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
GetItemProxies()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > & OutItemProxies) override virtual
Gets the Item Proxies for this Item (e.g.
Component Item that represent Primitives add in a Material Proxy to display)
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
GetLockState()
virtual SEQUENCENAVIGATOR_API EItemSequenceLockState UE::SequenceNavigator::FNavigationToolSequence::GetLockState () const override virtual
GetMarkerVisibility()
virtual SEQUENCENAVIGATOR_API EItemMarkerVisibility UE::SequenceNavigator::FNavigationToolSequence::GetMarkerVisibility () const override virtual
GetOutTime()
virtual SEQUENCENAVIGATOR_API FFrameNumber UE::SequenceNavigator::FNavigationToolSequence::GetOutTime () const override virtual
GetRevisionControlState()
virtual SEQUENCENAVIGATOR_API EItemRevisionControlState UE::SequenceNavigator::FNavigationToolSequence::GetRevisionControlState () const override virtual
GetRevisionControlStatusIcon()
virtual SEQUENCENAVIGATOR_API const FSlateBrush * UE::SequenceNavigator::FNavigationToolSequence::GetRevisionControlStatusIcon () const override virtual
GetRevisionControlStatusText()
virtual SEQUENCENAVIGATOR_API FText UE::SequenceNavigator::FNavigationToolSequence::GetRevisionControlStatusText () const override virtual
GetSequence()
SEQUENCENAVIGATOR_API UMovieSceneSequence * UE::SequenceNavigator::FNavigationToolSequence::GetSequence () const
GetSequenceMovieScene()
SEQUENCENAVIGATOR_API UMovieScene * UE::SequenceNavigator::FNavigationToolSequence::GetSequenceMovieScene () const
GetSortedBindings()
SEQUENCENAVIGATOR_API TArray< FMovieSceneBinding > UE::SequenceNavigator::FNavigationToolSequence::GetSortedBindings () const
GetSubSection()
SEQUENCENAVIGATOR_API UMovieSceneSubSection * UE::SequenceNavigator::FNavigationToolSequence::GetSubSection () const
GetSubSectionIndex()
SEQUENCENAVIGATOR_API int32 UE::SequenceNavigator::FNavigationToolSequence::GetSubSectionIndex () const
GetSupportedViewModes()
virtual SEQUENCENAVIGATOR_API ENavigationToolItemViewMode UE::SequenceNavigator::FNavigationToolSequence::GetSupportedViewModes (const INavigationToolView & InToolView) const override virtual
Gets the View Modes that this Item Supports.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetViewModel()
UE::Sequencer::TViewModelPtr< UE::Sequencer::FSectionModel > UE::SequenceNavigator::FNavigationToolSequence::GetViewModel () const
IsAllowedInTool()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::IsAllowedInTool () const override virtual
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
IsItemValid()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::IsItemValid () const override virtual
Determines whether the Item properties are in a valid state.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
IsSelected()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::IsSelected (const FNavigationToolScopedSelection & InSelection) const override virtual
Determines whether the given Item is selected in the given Scoped Selection.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
OnDoubleClick()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::OnDoubleClick () override virtual
Called when an Item is double-clicked with the mouse.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
OnObjectsReplaced()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::OnObjectsReplaced (const TMap< UObject *, UObject * > & InReplacementMap, bool bInRecursive) override virtual
Called when objects have been replaced on the Engine side.
Used to replace any UObjects used by this item
Parameters
InReplacementMap the map of old object that is garbage to the new object that replaced it
bInRecursive whether to recurse this same function to children items
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
OnSelect()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::OnSelect () override virtual
Called when an Item is selected.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
RemoveChild()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::RemoveChild (const FNavigationToolRemoveItemParams & InRemoveItemParams) override virtual
Removes the given child from this Item if it was ever indeed a child.
Returns true if the removal did happen.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
Rename()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolSequence::Rename (const FString & InName) override virtual
The implementation to rename the item.
Implements UE::SequenceNavigator::IRenameableExtension.
References InName.
Select()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::Select (FNavigationToolScopedSelection & InSelection) const override virtual
Used to signal the Scoped Selection that this Item should be Selected.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
SetColor()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetColor (const TOptional< FColor > & InColor) override virtual
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
SetInTime()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetInTime (const FFrameNumber & InTime) override virtual
Implements UE::SequenceNavigator::IInTimeExtension.
References InTime.
SetIsInactive()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetIsInactive (const bool bInIsInactive) override virtual
SetIsLocked()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetIsLocked (const bool bInIsLocked) override virtual
SetMarkerVisibility()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetMarkerVisibility (const bool bInVisible) override virtual
SetOutTime()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolSequence::SetOutTime (const FFrameNumber & InTime) override virtual
Implements UE::SequenceNavigator::IOutTimeExtension.
References InTime.
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER()
UE::SequenceNavigator::FNavigationToolSequence::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolSequence , FNavigationToolItem , IRenameableExtension , ISequenceInactivableExtension , ISequenceLockableExtension , IMarkerVisibilityExtension , IRevisionControlExtension , IPlayheadExtension , IInTimeExtension , IOutTimeExtension)
References UE::SequenceNavigator::FNavigationToolItem::FNavigationToolItem(), and FNavigationToolSequence().
Field Documentation
SubSectionIndex
int32 UE::SequenceNavigator::FNavigationToolSequence::SubSectionIndex = 0 protected
Definition at line 153 of file NavigationToolSequence.h.
WeakSequence
TWeakObjectPtr<UMovieSceneSequence> UE::SequenceNavigator::FNavigationToolSequence::WeakSequence protected
Definition at line 154 of file NavigationToolSequence.h.
WeakSubSection
TWeakObjectPtr<UMovieSceneSubSection> UE::SequenceNavigator::FNavigationToolSequence::WeakSubSection protected
Definition at line 152 of file NavigationToolSequence.h.
The documentation for this class was generated from the following file:
NavigationToolSequence.h