Unreal Engine 5.6 C++ API: FKeyHandleSet Struct Reference
FKeyHandleSet Struct Reference
A set of key handles implemented as a sorted array for transparent passing to TArrayView<> APIs.
#include "CurveEditorSelection.h"
Public Member Functions
void Add (FKeyHandle Handle, ECurvePointType PointType)
Add a new key handle to this set.
FORCEINLINE TArrayView< const FKeyHandle > AsArray () const
Retrieve a constant view of this set as an array.
bool Contains (FKeyHandle Handle, ECurvePointType PointType) const
Check whether the specified handle exists in this set.
FORCEINLINE int32 Num () const
Retrieve the number of handles in this set.
ECurvePointType PointType (FKeyHandle Handle) const
Retrieve the point type for this handle.
void Remove (FKeyHandle Handle, ECurvePointType PointType)
Remove a handle from this set.
void Toggle (FKeyHandle Handle, ECurvePointType PointType)
Remove a handle from this set if it already exists, otherwise add it to the set.
Private Attributes
TMap< FKeyHandle, ECurvePointType > HandleToPointType
Map of handle to point type (point, left, or right tangent)
TArray< FKeyHandle, TInlineAllocator< 1 > > SortedHandles
Sorted array of key handles.
Friends
FArchive & operator<< (FArchive &Ar, FKeyHandleSet &HandleSet)
Serializes the handle set.
Detailed Description
A set of key handles implemented as a sorted array for transparent passing to TArrayView<> APIs.
Lookup is achieved via binary search: O(log(n)).
Definition at line 27 of file CurveEditorSelection.h.
Member Function Documentation
Add()
void FKeyHandleSet::Add (FKeyHandle Handle, ECurvePointType PointType)
Add a new key handle to this set.
References Handle, and PointType().
AsArray()
FORCEINLINE TArrayView< const FKeyHandle > FKeyHandleSet::AsArray () const inline
Retrieve a constant view of this set as an array.
Definition at line 57 of file CurveEditorSelection.h.
References FORCEINLINE, and SortedHandles.
Contains()
bool FKeyHandleSet::Contains (FKeyHandle Handle, ECurvePointType PointType) const
Check whether the specified handle exists in this set.
References Handle, and PointType().
Num()
FORCEINLINE int32 FKeyHandleSet::Num () const inline
Retrieve the number of handles in this set.
Definition at line 52 of file CurveEditorSelection.h.
References FORCEINLINE, and SortedHandles.
PointType()
ECurvePointType FKeyHandleSet::PointType (FKeyHandle Handle) const inline
Retrieve the point type for this handle.
Definition at line 62 of file CurveEditorSelection.h.
References Handle, and HandleToPointType.
Referenced by Add(), Contains(), Remove(), and Toggle().
Remove()
void FKeyHandleSet::Remove (FKeyHandle Handle, ECurvePointType PointType)
Remove a handle from this set.
References Handle, and PointType().
Toggle()
void FKeyHandleSet::Toggle (FKeyHandle Handle, ECurvePointType PointType)
Remove a handle from this set if it already exists, otherwise add it to the set.
References Handle, and PointType().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FKeyHandleSet & HandleSet) friend
Serializes the handle set.
Definition at line 67 of file CurveEditorSelection.h.
References Ar, HandleToPointType, and SortedHandles.
Field Documentation
HandleToPointType
TMap<FKeyHandle, ECurvePointType> FKeyHandleSet::HandleToPointType private
Map of handle to point type (point, left, or right tangent)
Definition at line 80 of file CurveEditorSelection.h.
Referenced by operator<<, and PointType().
SortedHandles
TArray<FKeyHandle, TInlineAllocator<1> > FKeyHandleSet::SortedHandles private
Sorted array of key handles.
Definition at line 77 of file CurveEditorSelection.h.
Referenced by AsArray(), Num(), and operator<<.
The documentation for this struct was generated from the following file:
CurveEditorSelection.h