Unreal Engine 5.6 C++ API: UBTDecorator_ConditionalLoop Class Reference
UBTDecorator_ConditionalLoop Class Reference
#include "BTDecorator_ConditionalLoop.h"
Private Member Functions
virtual AIMODULE_API void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
GENERATED_UCLASS_BODY () AIMODULE_API virtual bool CalculateRawConditionValue(UBehaviorTreeComponent &OwnerComp
virtual AIMODULE_API uint16 GetInstanceMemorySize () const override
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
virtual AIMODULE_API EBlackboardNotificationResult OnBlackboardKeyValueChange (const UBlackboardComponent &Blackboard, FBlackboard::FKey ChangedKeyID) override
virtual AIMODULE_API void OnNodeDeactivation (FBehaviorTreeSearchData &SearchData, EBTNodeResult::Type NodeResult) override
Private Attributes
uint8 *NodeMemory const override
Additional Inherited Members
Public Member Functions inherited from UBTDecorator_Blackboard
virtual AIMODULE_API void BuildDescription ()
when observer can try to request abort?
Protected Member Functions inherited from UBTDecorator_Blackboard
AIMODULE_API bool EvaluateOnBlackboard (const UBlackboardComponent &BlackboardComp) const
take blackboard value and evaluate decorator's condition
virtual AIMODULE_API void InitializeFromAsset (UBehaviorTree &Asset) override
virtual AIMODULE_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
AIMODULE_API void RefreshEnumBasedDecorator (const FBlackboardEntry &Entry)
decorator using enum based key requires to synchronize 'StringValue' used for storage with 'IntValue' used for runtime evaluation.
UPROPERTY () FString CachedDescription
cached description
UPROPERTY () uint8 OperationType
operation type
UPROPERTY ()) float FloatValue
value for arithmetic operations
UPROPERTY ()) FString StringValue
value for string operations
UPROPERTY ()) int32 IntValue
value for arithmetic operations
Protected Attributes inherited from UBTDecorator_Blackboard
friend FBlackboardDecoratorDetails
Detailed Description
Definition at line 23 of file BTDecorator_ConditionalLoop.h.
Member Function Documentation
CleanupMemory()
virtual AIMODULE_API void UBTDecorator_ConditionalLoop::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override private virtual
References CleanupMemory(), and override.
Referenced by CleanupMemory().
GENERATED_UCLASS_BODY()
UBTDecorator_ConditionalLoop::GENERATED_UCLASS_BODY () & private
GetInstanceMemorySize()
virtual AIMODULE_API uint16 UBTDecorator_ConditionalLoop::GetInstanceMemorySize () const override private virtual
References GetInstanceMemorySize(), and override.
Referenced by GetInstanceMemorySize().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_ConditionalLoop::GetNodeIconName () const override private virtual
InitializeMemory()
virtual AIMODULE_API void UBTDecorator_ConditionalLoop::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override private virtual
References InitializeMemory(), and override.
Referenced by InitializeMemory().
OnBlackboardKeyValueChange()
virtual AIMODULE_API EBlackboardNotificationResult UBTDecorator_ConditionalLoop::OnBlackboardKeyValueChange (const UBlackboardComponent & Blackboard, FBlackboard::FKey ChangedKeyID) override private virtual
Reimplemented from UBTDecorator_Blackboard.
References OnBlackboardKeyValueChange(), and override.
Referenced by OnBlackboardKeyValueChange().
OnNodeDeactivation()
virtual AIMODULE_API void UBTDecorator_ConditionalLoop::OnNodeDeactivation (FBehaviorTreeSearchData & SearchData, EBTNodeResult::Type NodeResult) override private virtual
References OnNodeDeactivation(), and override.
Referenced by OnNodeDeactivation().
Field Documentation
override
uint8* NodeMemory const UBTDecorator_ConditionalLoop::override private
Definition at line 27 of file BTDecorator_ConditionalLoop.h.
Referenced by CleanupMemory(), GetInstanceMemorySize(), InitializeMemory(), OnBlackboardKeyValueChange(), and OnNodeDeactivation().
The documentation for this class was generated from the following file:
BTDecorator_ConditionalLoop.h