Unreal Engine 5.6 C++ API: UE::Cook::IDeterminismModifiedExportContext Struct Reference
UE::Cook::IDeterminismModifiedExportContext Struct Reference abstract
Struct to hold input and receive output of IDeterminismHelper::OnExportModified.
#include "CookDeterminismHelper.h"
Public Member Functions
virtual ~IDeterminismModifiedExportContext ()
virtual void AppendDiagnostics ()=0
Output function; calls AppendLog(GetCompareText()).
virtual void AppendLog (FStringView LogText)=0
Output function; add the given text to the -diffonly or -incrementalvalidate log output for the modified package.
virtual FString GetCompareText ()=0
Create a string version of the values of the old and new diagnostics for the export.
virtual const TMap< FUtf8String, FCbField > & GetNewDiagnostics ()=0
Returns a container of the diagnostics written for the export in the current in-memory version of the package from the current cook.
virtual const TMap< FUtf8String, FCbField > & GetOldDiagnostics ()=0
Returns a container of the diagnostics written for the export in the old version of the package from the previous cook.
virtual IDeterminismModifiedPackageContext & GetPackageContext ()=0
Return a reference to information about the package in general and all modified exports in the package.
virtual const ITargetPlatform * GetTargetPlatform ()=0
Reports the TargetPlatform for which the package was found to be modified.
virtual bool IsModified ()=0
True iff the export that registered the DeterminismHelper was found to have modifications in the bytes created by its Serialize function.
virtual bool IsPrimaryAsset ()=0
True iff the export that registered the DeterminismHelper is the primary asset in the package.
Detailed Description
Struct to hold input and receive output of IDeterminismHelper::OnExportModified.
Virtual base class so it can be implemented in the UnrealEd project.
Definition at line 47 of file CookDeterminismHelper.h.
Constructor & Destructor Documentation
~IDeterminismModifiedExportContext()
virtual UE::Cook::IDeterminismModifiedExportContext::~IDeterminismModifiedExportContext () inline virtual
Definition at line 49 of file CookDeterminismHelper.h.
Member Function Documentation
AppendDiagnostics()
virtual void UE::Cook::IDeterminismModifiedExportContext::AppendDiagnostics () pure virtual
Output function; calls AppendLog(GetCompareText()).
Activates only once per export if called multiple times.
Referenced by UE::Cook::IDeterminismHelper::OnPackageModified().
AppendLog()
virtual void UE::Cook::IDeterminismModifiedExportContext::AppendLog (FStringView LogText) pure virtual
Output function; add the given text to the -diffonly or -incrementalvalidate log output for the modified package.
GetCompareText()
virtual FString UE::Cook::IDeterminismModifiedExportContext::GetCompareText () pure virtual
Create a string version of the values of the old and new diagnostics for the export.
GetNewDiagnostics()
virtual const TMap< FUtf8String, FCbField > & UE::Cook::IDeterminismModifiedExportContext::GetNewDiagnostics () pure virtual
Returns a container of the diagnostics written for the export in the current in-memory version of the package from the current cook.
GetOldDiagnostics()
virtual const TMap< FUtf8String, FCbField > & UE::Cook::IDeterminismModifiedExportContext::GetOldDiagnostics () pure virtual
Returns a container of the diagnostics written for the export in the old version of the package from the previous cook.
GetPackageContext()
virtual IDeterminismModifiedPackageContext & UE::Cook::IDeterminismModifiedExportContext::GetPackageContext () pure virtual
Return a reference to information about the package in general and all modified exports in the package.
GetTargetPlatform()
virtual const ITargetPlatform * UE::Cook::IDeterminismModifiedExportContext::GetTargetPlatform () pure virtual
Reports the TargetPlatform for which the package was found to be modified.
IsModified()
virtual bool UE::Cook::IDeterminismModifiedExportContext::IsModified () pure virtual
True iff the export that registered the DeterminismHelper was found to have modifications in the bytes created by its Serialize function.
Referenced by UE::Cook::IDeterminismHelper::OnPackageModified().
IsPrimaryAsset()
virtual bool UE::Cook::IDeterminismModifiedExportContext::IsPrimaryAsset () pure virtual
True iff the export that registered the DeterminismHelper is the primary asset in the package.
Referenced by UE::Cook::IDeterminismHelper::OnPackageModified().
The documentation for this struct was generated from the following file:
CookDeterminismHelper.h