Unreal Engine 5.6 C++ API: FSparseDelegateStorage Struct Reference
FSparseDelegateStorage Struct Reference
Sparse delegates can be used for infrequently bound dynamic delegates so that the object uses only 1 byte of storage instead of having the full overhead of the delegate invocation list.
#include "SparseDelegate.h"
Data Structures
struct FObjectListener
Static Public Member Functions
static bool Add (const UObject *DelegateOwner, const FName DelegateName, FScriptDelegate Delegate)
Binds a sparse delegate to the owner.
static bool AddUnique (const UObject *DelegateOwner, const FName DelegateName, FScriptDelegate Delegate)
Binds a sparse delegate to the owner, verifying first that the delegate is not already bound.
static void Clear (const UObject *DelegateOwner, const FName DelegateName)
Clear all of the named sparse delegate bindings from the owner.
static bool Contains (const UObject *DelegateOwner, const FName DelegateName, const FScriptDelegate &Delegate)
Returns whether a sparse delegate is bound to the owner.
static bool Contains (const UObject *DelegateOwner, const FName DelegateName, const UObject *InObject, FName InFunctionName)
static FMulticastScriptDelegate * GetMulticastDelegate (const UObject *DelegateOwner, const FName DelegateName)
Acquires the actual Multicast Delegate from the annotation if any delegates are bound to it.
static TSharedPtr< FMulticastScriptDelegate > GetSharedMulticastDelegate (const UObject *DelegateOwner, const FName DelegateName)
Acquires the actual Multicast Delegate from the annotation if any delegates are bound to it as a shared pointer.
static void RegisterDelegateOffset (const UObject *OwningObject, FName DelegateName, size_t OffsetToOwner)
Registers the sparse delegate so that the offset can be determined.
static bool Remove (const UObject *DelegateOwner, const FName DelegateName, const FScriptDelegate &Delegate)
Removes a delegate binding from the owner's sparse delegate storage.
static bool Remove (const UObject *DelegateOwner, const FName DelegateName, const UObject *InObject, FName InFunctionName)
static bool RemoveAll (const UObject *DelegateOwner, const FName DelegateName, const UObject *UserObject)
Removes all sparse delegate binding from the owner for a given object.
static FSparseDelegate * ResolveSparseDelegate (const UObject *OwningObject, FName DelegateName)
Using the registry of sparse delegates recover the FSparseDelegate address from the UObject and name.
static UObject * ResolveSparseOwner (const FSparseDelegate &SparseDelegate, const FName OwningClassName, const FName DelegateName)
Using the registry of sparse delegates recover the UObject owner from the FSparseDelegate address owning class and delegate names.
static void SetMulticastDelegate (const UObject *DelegateOwner, const FName DelegateName, FMulticastScriptDelegate Delegate)
Directly sets the Multicast Delegate for this object/delegatename pair.
static void SparseDelegateReport (const TArray< FString > &, UWorld *, FOutputDevice &)
Outputs a report about which delegates are bound.
Private Types
typedef TMap< FName, TSharedPtr< FMulticastScriptDelegate > > FSparseDelegateMap
Delegate map is a map of Delegate names to a shared pointer of the multicast script delegate.
Static Private Attributes
static FTransactionallySafeCriticalSection SparseDelegateMapCritical
Critical Section for locking access to the sparse delegate map.
static FObjectListener SparseDelegateObjectListener
A listener to get notified when objects have been deleted and remove them from the map.
static TMap< TPair< FName, FName >, size_t > SparseDelegateObjectOffsets
Sparse delegate offsets are indexed by ActorClass/DelegateName pair.
static TMap< const UObjectBase *, FSparseDelegateMap > SparseDelegates
Map of objects to the map of delegates that are bound to that object.
Friends
struct FObjectListener
Allow the object listener to use the critical section and remove objects from the map.
Detailed Description
Sparse delegates can be used for infrequently bound dynamic delegates so that the object uses only 1 byte of storage instead of having the full overhead of the delegate invocation list.
The cost to invoke, add, remove, etc. from the delegate is higher than using the delegate directly and thus the memory savings benefit should be traded off against the frequency with which you would expect the delegate to be bound. Helper class for handling sparse delegate bindings
Definition at line 37 of file SparseDelegate.h.
Member Typedef Documentation
FSparseDelegateMap
typedef TMap<FName, TSharedPtr<FMulticastScriptDelegate> > FSparseDelegateStorage::FSparseDelegateMap private
Delegate map is a map of Delegate names to a shared pointer of the multicast script delegate.
Definition at line 108 of file SparseDelegate.h.
Member Function Documentation
Add()
bool FSparseDelegateStorage::Add (const UObject * DelegateOwner, const FName DelegateName, FScriptDelegate Delegate) static
Binds a sparse delegate to the owner.
Returns if the delegate was successfully bound.
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Add().
AddUnique()
bool FSparseDelegateStorage::AddUnique (const UObject * DelegateOwner, const FName DelegateName, FScriptDelegate Delegate) static
Binds a sparse delegate to the owner, verifying first that the delegate is not already bound.
Returns if the delegate was successfully bound.
Referenced by FSparseDelegate::__Internal_AddUnique().
Clear()
void FSparseDelegateStorage::Clear (const UObject * DelegateOwner, const FName DelegateName) static
Clear all of the named sparse delegate bindings from the owner.
Referenced by FSparseDelegate::__Internal_Clear().
Contains() [1/2]
bool FSparseDelegateStorage::Contains (const UObject * DelegateOwner, const FName DelegateName, const FScriptDelegate & Delegate) static
Returns whether a sparse delegate is bound to the owner.
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains(), and TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains().
Contains() [2/2]
bool FSparseDelegateStorage::Contains (const UObject * DelegateOwner, const FName DelegateName, const UObject * InObject, FName InFunctionName) static
GetMulticastDelegate()
FMulticastScriptDelegate * FSparseDelegateStorage::GetMulticastDelegate (const UObject * DelegateOwner, const FName DelegateName) static
Acquires the actual Multicast Delegate from the annotation if any delegates are bound to it.
Will be null if no entry exists in the annotation for this object/delegatename.
GetSharedMulticastDelegate()
TSharedPtr< FMulticastScriptDelegate > FSparseDelegateStorage::GetSharedMulticastDelegate (const UObject * DelegateOwner, const FName DelegateName) static
Acquires the actual Multicast Delegate from the annotation if any delegates are bound to it as a shared pointer.
Will be null if no entry exists in the annotation for this object/delegatename.
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetShared().
RegisterDelegateOffset()
void FSparseDelegateStorage::RegisterDelegateOffset (const UObject * OwningObject, FName DelegateName, size_t OffsetToOwner) static
Registers the sparse delegate so that the offset can be determined.
Remove() [1/2]
bool FSparseDelegateStorage::Remove (const UObject * DelegateOwner, const FName DelegateName, const FScriptDelegate & Delegate) static
Removes a delegate binding from the owner's sparse delegate storage.
Returns true if there are still bindings to the delegate.
Referenced by FSparseDelegate::__Internal_Remove(), and TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Remove().
Remove() [2/2]
bool FSparseDelegateStorage::Remove (const UObject * DelegateOwner, const FName DelegateName, const UObject * InObject, FName InFunctionName) static
RemoveAll()
bool FSparseDelegateStorage::RemoveAll (const UObject * DelegateOwner, const FName DelegateName, const UObject * UserObject) static
Removes all sparse delegate binding from the owner for a given object.
Returns true if there are still bindings to the delegate.
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::RemoveAll().
ResolveSparseDelegate()
FSparseDelegate * FSparseDelegateStorage::ResolveSparseDelegate (const UObject * OwningObject, FName DelegateName) static
Using the registry of sparse delegates recover the FSparseDelegate address from the UObject and name.
ResolveSparseOwner()
UObject * FSparseDelegateStorage::ResolveSparseOwner (const FSparseDelegate & SparseDelegate, const FName OwningClassName, const FName DelegateName) static
Using the registry of sparse delegates recover the UObject owner from the FSparseDelegate address owning class and delegate names.
SetMulticastDelegate()
void FSparseDelegateStorage::SetMulticastDelegate (const UObject * DelegateOwner, const FName DelegateName, FMulticastScriptDelegate Delegate) static
Directly sets the Multicast Delegate for this object/delegatename pair.
If the delegate is unbound it will be assigned/inserted anyways.
SparseDelegateReport()
void FSparseDelegateStorage::SparseDelegateReport (const TArray< FString > & , UWorld * , FOutputDevice &) static
Outputs a report about which delegates are bound.
Friends And Related Symbol Documentation
FObjectListener
friend struct FObjectListener friend
Allow the object listener to use the critical section and remove objects from the map.
Definition at line 99 of file SparseDelegate.h.
Field Documentation
SparseDelegateMapCritical
FTransactionallySafeCriticalSection FSparseDelegateStorage::SparseDelegateMapCritical static private
Critical Section for locking access to the sparse delegate map.
Definition at line 105 of file SparseDelegate.h.
SparseDelegateObjectListener
FObjectListener FSparseDelegateStorage::SparseDelegateObjectListener static private
A listener to get notified when objects have been deleted and remove them from the map.
Definition at line 102 of file SparseDelegate.h.
SparseDelegateObjectOffsets
TMap<TPair<FName, FName>, size_t> FSparseDelegateStorage::SparseDelegateObjectOffsets static private
Sparse delegate offsets are indexed by ActorClass/DelegateName pair.
Definition at line 114 of file SparseDelegate.h.
SparseDelegates
TMap<const UObjectBase*, FSparseDelegateMap> FSparseDelegateStorage::SparseDelegates static private
Map of objects to the map of delegates that are bound to that object.
Definition at line 111 of file SparseDelegate.h.
The documentation for this struct was generated from the following file:
SparseDelegate.h