Unreal Engine 5.6 C++ API: FThreadSafeCounter64 Class Reference
FThreadSafeCounter64 Class Reference
Thread safe counter for 64bit ints.
#include "ThreadSafeCounter64.h"
Public Types
typedef int64 IntegerType
Public Member Functions
FThreadSafeCounter64 ()
Default constructor.
FThreadSafeCounter64 (const FThreadSafeCounter64 &Other)
Copy Constructor.
FThreadSafeCounter64 (int64 Value)
Constructor, initializing counter to passed in value.
int64 Add (int64 Amount)
Adds an amount and returns the old value.
int64 Decrement ()
Decrement and return new value.
int64 GetValue () const
Gets the current value.
int64 Increment ()
Increment and return new value.
FThreadSafeCounter64 & operator= (const FThreadSafeCounter64 &Other)
Assignment has the same caveats as the copy ctor.
int64 Reset ()
Resets the counter's value to zero.
int64 Set (int64 Value)
Sets the counter to a specific value and returns the old value.
int64 Subtract (int64 Amount)
Subtracts an amount and returns the old value.
Private Attributes
volatile int64 Counter
Thread-safe counter.
Detailed Description
Thread safe counter for 64bit ints.
Definition at line 13 of file ThreadSafeCounter64.h.
Member Typedef Documentation
IntegerType
typedef int64 FThreadSafeCounter64::IntegerType
Definition at line 16 of file ThreadSafeCounter64.h.
Constructor & Destructor Documentation
FThreadSafeCounter64() [1/3]
FThreadSafeCounter64::FThreadSafeCounter64 () inline
Default constructor.
Initializes the counter to 0.
Definition at line 23 of file ThreadSafeCounter64.h.
References Counter.
Referenced by FThreadSafeCounter64(), and operator=().
FThreadSafeCounter64() [2/3]
FThreadSafeCounter64::FThreadSafeCounter64 (const FThreadSafeCounter64 & Other) inline
Copy Constructor.
If the counter in the Other parameter is changing from other threads, there are no guarantees as to which values you will get up to the caller to not care, synchronize or other way to make those guarantees.
Parameters
Other The other thread safe counter to copy
Definition at line 37 of file ThreadSafeCounter64.h.
References FThreadSafeCounter64(), Counter, and Other.
FThreadSafeCounter64() [3/3]
FThreadSafeCounter64::FThreadSafeCounter64 (int64 Value) inline
Constructor, initializing counter to passed in value.
Parameters
Value Value to initialize counter to
Definition at line 56 of file ThreadSafeCounter64.h.
References Counter, and Value.
Member Function Documentation
Add()
int64 FThreadSafeCounter64::Add (int64 Amount) inline
Adds an amount and returns the old value.
Parameters
Amount Amount to increase the counter by
Returns
the old value
See also
Decrement, Increment, Reset, Set, Subtract
Definition at line 79 of file ThreadSafeCounter64.h.
References Counter.
Decrement()
int64 FThreadSafeCounter64::Decrement () inline
Decrement and return new value.
Returns
the new, decremented value
See also
Add, Increment, Reset, Set, Subtract
Definition at line 90 of file ThreadSafeCounter64.h.
References Counter.
GetValue()
int64 FThreadSafeCounter64::GetValue () const inline
Gets the current value.
Returns
the current value
Definition at line 135 of file ThreadSafeCounter64.h.
References Counter.
Increment()
int64 FThreadSafeCounter64::Increment () inline
Increment and return new value.
Returns
the new, incremented value
See also
Add, Decrement, Reset, Set, Subtract
Definition at line 67 of file ThreadSafeCounter64.h.
References Counter.
operator=()
FThreadSafeCounter64 & FThreadSafeCounter64::operator= (const FThreadSafeCounter64 & Other) inline
Assignment has the same caveats as the copy ctor.
Definition at line 43 of file ThreadSafeCounter64.h.
References FThreadSafeCounter64(), Other, and Set().
Reset()
int64 FThreadSafeCounter64::Reset () inline
Resets the counter's value to zero.
Returns
the old value.
See also
Add, Decrement, Increment, Set, Subtract
Definition at line 125 of file ThreadSafeCounter64.h.
References Counter.
Set()
int64 FThreadSafeCounter64::Set (int64 Value) inline
Sets the counter to a specific value and returns the old value.
Parameters
Value Value to set the counter to
Returns
The old value
See also
Add, Decrement, Increment, Reset, Subtract
Definition at line 114 of file ThreadSafeCounter64.h.
References Counter, and Value.
Referenced by operator=().
Subtract()
int64 FThreadSafeCounter64::Subtract (int64 Amount) inline
Subtracts an amount and returns the old value.
Parameters
Amount Amount to decrease the counter by
Returns
the old value
See also
Add, Decrement, Increment, Reset, Set
Definition at line 102 of file ThreadSafeCounter64.h.
References Counter.
Field Documentation
Counter
volatile int64 FThreadSafeCounter64::Counter private
Thread-safe counter.
Definition at line 142 of file ThreadSafeCounter64.h.
Referenced by FThreadSafeCounter64(), FThreadSafeCounter64(), FThreadSafeCounter64(), Add(), Decrement(), GetValue(), Increment(), Reset(), Set(), and Subtract().
The documentation for this class was generated from the following file:
ThreadSafeCounter64.h