Unreal Engine 5.6 C++ API: FUInt128 Class Reference
FUInt128 Class Reference
#include "Int128.h"
Public Member Functions
FORCEINLINE FUInt128 ()
Default constructor.
FORCEINLINE FUInt128 (const FUInt128 &)=default
Default constructors.
FORCEINLINE FUInt128 (FUInt128 &&)=default
FORCEINLINE FUInt128 (uint32 A, uint32 B, uint32 C, uint32 D)
Constructor.
FORCEINLINE FUInt128 (uint64 A)
Constructor.
FORCEINLINE FUInt128 (uint64 A, uint64 B)
Constructor.
FORCEINLINE FUInt128 Add (uint32 Value)
Add an unsigned 32bit value.
FORCEINLINE FUInt128 Divide (uint32 Divisor, uint32 &Remainder)
Divide by an unsigned 32bit value.
FORCEINLINE uint32 GetQuadPart (uint32 Part) const
Gets internal quad parts.
FORCEINLINE bool IsEqual (const FUInt128 &Other) const
this == Other
FORCEINLINE bool IsGreater (const FUInt128 &Other) const
this > Other
FORCEINLINE bool IsGreaterOrEqual (const FUInt128 &Other) const
this >= Other
FORCEINLINE bool IsGreaterThanZero () const
FORCEINLINE bool IsLess (const FUInt128 &Other) const
this < Other
FORCEINLINE bool IsLessOrEqual (const FUInt128 &Other) const
this <= Other
FORCEINLINE bool IsZero () const
FORCEINLINE FUInt128 Multiply (uint32 Multiplier)
Multiply by an unsigned 32bit value.
FORCEINLINE FUInt128 & operator*= (uint32 Other)
FORCEINLINE FUInt128 & operator+= (uint32 Other)
Arithmetic operators.
FORCEINLINE FUInt128 & operator-= (uint32 Other)
FORCEINLINE FUInt128 & operator/= (uint32 Other)
FORCEINLINE bool operator< (const FUInt128 &Other) const
FORCEINLINE bool operator<= (const FUInt128 &Other) const
FORCEINLINE FUInt128 & operator= (FUInt128 &&)=default
FORCEINLINE FUInt128 & operator= (FUInt128 const &)=default
FORCEINLINE bool operator== (const FUInt128 &Other) const
FORCEINLINE bool operator> (const FUInt128 &Other) const
Comparison operators.
FORCEINLINE bool operator>= (const FUInt128 &Other) const
FORCEINLINE void Set (uint64 InHi, uint64 InLo)
Initializes this number with a pair of 64 bit integer values.
FORCEINLINE void SetQuadPart (uint32 Part, uint32 Value)
Sets internal quad parts.
FORCEINLINE FUInt128 Sub (uint32 Value)
FORCEINLINE void Zero ()
Sets this number to 0.
Private Member Functions
FORCEINLINE uint32 AddInternal (uint32 A, uint32 B, uint32 &Carry)
FORCEINLINE uint32 DivideInternal (uint32 Dividend, uint32 Divisor, uint32 &Remainder)
FORCEINLINE uint32 MultiplyInternal (uint32 Multiplicand, uint32 Multiplier, uint32 &Carry)
Private Attributes
uint64 Hi
Internal values representing this number.
uint64 Lo
Friends
FArchive & operator<< (FArchive &Ar, FUInt128 &Value)
Serialization.
Detailed Description
Definition at line 8 of file Int128.h.
Constructor & Destructor Documentation
FUInt128() [1/6]
FORCEINLINE FUInt128::FUInt128 (const FUInt128 &) nodiscard default
Default constructors.
References FUInt128(), and FORCEINLINE.
Referenced by FUInt128(), FUInt128(), Add(), Divide(), IsEqual(), IsGreater(), IsGreaterOrEqual(), IsLess(), IsLessOrEqual(), Multiply(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator<<, operator<=(), operator=(), operator=(), operator==(), operator>(), operator>=(), and Sub().
FUInt128() [2/6]
FORCEINLINE FUInt128::FUInt128 (FUInt128 &&) nodiscard default
References FUInt128(), and FORCEINLINE.
FUInt128() [3/6]
FORCEINLINE FUInt128::FUInt128 () inline nodiscard
Default constructor.
Initializes the number to zero.
Definition at line 85 of file Int128.h.
References FORCEINLINE, Hi, and Lo.
FUInt128() [4/6]
FORCEINLINE FUInt128::FUInt128 (uint64 A) inline nodiscard
Constructor.
Initializes this uint128 with a uint64 value.
Definition at line 91 of file Int128.h.
References A, FORCEINLINE, Hi, and Lo.
FUInt128() [5/6]
FORCEINLINE FUInt128::FUInt128 (uint64 A, uint64 B) inline nodiscard
Constructor.
Initializes this uint128 with two uint64 values.
Definition at line 97 of file Int128.h.
References A, B, FORCEINLINE, Hi, and Lo.
FUInt128() [6/6]
FORCEINLINE FUInt128::FUInt128 (uint32 A, uint32 B, uint32 C, uint32 D) inline nodiscard
Constructor.
Initializes this uint128 with four uint32 values.
Definition at line 103 of file Int128.h.
References A, B, FORCEINLINE, Hi, and Lo.
Member Function Documentation
Add()
FORCEINLINE FUInt128 FUInt128::Add (uint32 Value) inline
Add an unsigned 32bit value.
Definition at line 155 of file Int128.h.
References FUInt128(), AddInternal(), FORCEINLINE, GetQuadPart(), and Value.
AddInternal()
FORCEINLINE uint32 FUInt128::AddInternal (uint32 A, uint32 B, uint32 & Carry) inline private
Definition at line 15 of file Int128.h.
References A, B, and FORCEINLINE.
Referenced by Add(), and Sub().
Divide()
FORCEINLINE FUInt128 FUInt128::Divide (uint32 Divisor, uint32 & Remainder) inline
Divide by an unsigned 32bit value.
Definition at line 197 of file Int128.h.
References FUInt128(), DivideInternal(), FORCEINLINE, and GetQuadPart().
Referenced by operator/=().
DivideInternal()
FORCEINLINE uint32 FUInt128::DivideInternal (uint32 Dividend, uint32 Divisor, uint32 & Remainder) inline private
Definition at line 30 of file Int128.h.
References FORCEINLINE, and Value.
Referenced by Divide().
GetQuadPart()
FORCEINLINE uint32 FUInt128::GetQuadPart (uint32 Part) const inline nodiscard
Gets internal quad parts.
Definition at line 39 of file Int128.h.
References check, FORCEINLINE, Hi, and Lo.
Referenced by Add(), Divide(), Multiply(), and Sub().
IsEqual()
FORCEINLINE bool FUInt128::IsEqual (const FUInt128 & Other) const inline nodiscard
this == Other
Definition at line 149 of file Int128.h.
References FUInt128(), FORCEINLINE, Hi, Lo, and Other.
Referenced by operator==().
IsGreater()
FORCEINLINE bool FUInt128::IsGreater (const FUInt128 & Other) const inline nodiscard
this > Other
Definition at line 109 of file Int128.h.
References FUInt128(), FORCEINLINE, Hi, Lo, and Other.
Referenced by operator>().
IsGreaterOrEqual()
FORCEINLINE bool FUInt128::IsGreaterOrEqual (const FUInt128 & Other) const inline nodiscard
this >= Other
Definition at line 119 of file Int128.h.
References FUInt128(), FORCEINLINE, Hi, Lo, and Other.
Referenced by operator>=().
IsGreaterThanZero()
FORCEINLINE bool FUInt128::IsGreaterThanZero () const inline nodiscard
Definition at line 242 of file Int128.h.
References FORCEINLINE, and IsZero().
IsLess()
FORCEINLINE bool FUInt128::IsLess (const FUInt128 & Other) const inline nodiscard
this < Other
Definition at line 129 of file Int128.h.
References FUInt128(), FORCEINLINE, Hi, Lo, and Other.
Referenced by operator<().
IsLessOrEqual()
FORCEINLINE bool FUInt128::IsLessOrEqual (const FUInt128 & Other) const inline nodiscard
this <= Other
Definition at line 139 of file Int128.h.
References FUInt128(), FORCEINLINE, Hi, Lo, and Other.
Referenced by operator<=().
IsZero()
FORCEINLINE bool FUInt128::IsZero () const inline nodiscard
Definition at line 237 of file Int128.h.
References FORCEINLINE, Hi, and Lo.
Referenced by IsGreaterThanZero().
Multiply()
FORCEINLINE FUInt128 FUInt128::Multiply (uint32 Multiplier) inline
Multiply by an unsigned 32bit value.
Definition at line 184 of file Int128.h.
References FUInt128(), FORCEINLINE, GetQuadPart(), Multiplier, and MultiplyInternal().
Referenced by operator*=().
MultiplyInternal()
FORCEINLINE uint32 FUInt128::MultiplyInternal (uint32 Multiplicand, uint32 Multiplier, uint32 & Carry) inline private
Definition at line 22 of file Int128.h.
References FORCEINLINE, and Multiplier.
Referenced by Multiply().
operator*=()
FORCEINLINE FUInt128 & FUInt128::operator*= (uint32 Other) inline
Definition at line 262 of file Int128.h.
References FUInt128(), FORCEINLINE, Multiply(), and Other.
operator+=()
FORCEINLINE FUInt128 & FUInt128::operator+= (uint32 Other) inline
Arithmetic operators.
Definition at line 250 of file Int128.h.
References FUInt128(), Add, FORCEINLINE, and Other.
operator-=()
FORCEINLINE FUInt128 & FUInt128::operator-= (uint32 Other) inline
Definition at line 256 of file Int128.h.
References FUInt128(), FORCEINLINE, Other, and Sub().
operator/=()
FORCEINLINE FUInt128 & FUInt128::operator/= (uint32 Other) inline
Definition at line 268 of file Int128.h.
References FUInt128(), Divide(), FORCEINLINE, and Other.
operator<()
FORCEINLINE bool FUInt128::operator< (const FUInt128 & Other) const inline nodiscard
Definition at line 227 of file Int128.h.
References FUInt128(), FORCEINLINE, IsLess(), and Other.
operator<=()
FORCEINLINE bool FUInt128::operator<= (const FUInt128 & Other) const inline nodiscard
Definition at line 232 of file Int128.h.
References FUInt128(), FORCEINLINE, IsLessOrEqual(), and Other.
operator=() [1/2]
FORCEINLINE FUInt128 & FUInt128::operator= (FUInt128 &&) default
References FUInt128(), and FORCEINLINE.
operator=() [2/2]
FORCEINLINE FUInt128 & FUInt128::operator= (FUInt128 const &) default
References FUInt128(), and FORCEINLINE.
operator==()
FORCEINLINE bool FUInt128::operator== (const FUInt128 & Other) const inline nodiscard
Definition at line 222 of file Int128.h.
References FUInt128(), FORCEINLINE, IsEqual(), and Other.
operator>()
FORCEINLINE bool FUInt128::operator> (const FUInt128 & Other) const inline nodiscard
Comparison operators.
Definition at line 212 of file Int128.h.
References FUInt128(), FORCEINLINE, IsGreater(), and Other.
operator>=()
FORCEINLINE bool FUInt128::operator>= (const FUInt128 & Other) const inline nodiscard
Definition at line 217 of file Int128.h.
References FUInt128(), FORCEINLINE, IsGreaterOrEqual(), and Other.
Set()
FORCEINLINE void FUInt128::Set (uint64 InHi, uint64 InLo) inline
Initializes this number with a pair of 64 bit integer values.
Definition at line 72 of file Int128.h.
References FORCEINLINE, Hi, and Lo.
SetQuadPart()
FORCEINLINE void FUInt128::SetQuadPart (uint32 Part, uint32 Value) inline
Sets internal quad parts.
Definition at line 53 of file Int128.h.
References check, FORCEINLINE, Hi, Lo, and Value.
Sub()
FORCEINLINE FUInt128 FUInt128::Sub (uint32 Value) inline
Definition at line 168 of file Int128.h.
References FUInt128(), AddInternal(), FORCEINLINE, GetQuadPart(), and Value.
Referenced by operator-=().
Zero()
FORCEINLINE void FUInt128::Zero () inline
Sets this number to 0.
Definition at line 66 of file Int128.h.
References FORCEINLINE, Hi, and Lo.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FUInt128 & Value) friend
Serialization.
Definition at line 278 of file Int128.h.
References FUInt128(), Ar, and Value.
Field Documentation
Hi
uint64 FUInt128::Hi private
Internal values representing this number.
Definition at line 12 of file Int128.h.
Referenced by FUInt128(), FUInt128(), FUInt128(), FUInt128(), GetQuadPart(), IsEqual(), IsGreater(), IsGreaterOrEqual(), IsLess(), IsLessOrEqual(), IsZero(), Set(), SetQuadPart(), and Zero().
Lo
uint64 FUInt128::Lo private
Definition at line 13 of file Int128.h.
Referenced by FUInt128(), FUInt128(), FUInt128(), FUInt128(), GetQuadPart(), IsEqual(), IsGreater(), IsGreaterOrEqual(), IsLess(), IsLessOrEqual(), IsZero(), Set(), SetQuadPart(), and Zero().
The documentation for this class was generated from the following file:
Int128.h