Unreal Engine 5.6 C++ API: FSlateFontAtlas Class Reference
FSlateFontAtlas Class Reference
Representation of a texture for fonts in which characters are packed tightly based on their bounding rectangle.
#include "FontTypes.h"
Public Member Functions
FSlateFontAtlas (uint32 InWidth, uint32 InHeight, ESlateFontAtlasContentType InContentType, ESlateTextureAtlasPaddingStyle InPaddingStyle)
virtual ~FSlateFontAtlas ()
const struct FAtlasedTextureSlot * AddCharacter (const FCharacterRenderData &CharInfo)
Adds a character to the texture.
bool BeginDeferredAddCharacter (const int16 InSizeX, const int16 InSizeY, FDeferredCharacterRenderData &OutCharInfo)
Reserve a slot for a character but dont't update the texture yet.
void EndDeferredAddCharacter (const FDeferredCharacterRenderData &CharInfo)
Update a character in the texture for already reserved or added slot.
void Flush ()
Flushes all cached data.
virtual void GetAtlasDataCopy (TArray< uint8 > &OutData) const override
Retrieves a copy of the texture atlas data in this texture.
virtual FSlateShaderResource * GetAtlasTexture () const override
virtual ESlateFontAtlasContentType GetContentType () const override final
Returns the type of content in the texture.
virtual void ReleaseRenderingResources ()
Releases rendering resources of this texture.
Public Member Functions inherited from ISlateFontTexture
virtual ~ISlateFontTexture ()
virtual class FTextureResource * GetEngineTexture ()=0
Returns the texture resource used the Engine.
virtual class FSlateShaderResource * GetSlateTexture () const =0
Returns the texture resource used by Slate.
Public Member Functions inherited from FSlateTextureAtlas
FSlateTextureAtlas (uint32 InWidth, uint32 InHeight, uint32 InBytesPerPixel, ESlateTextureAtlasPaddingStyle InPaddingStyle, bool bInUpdatesAfterInitialization)
virtual ~FSlateTextureAtlas ()
const FAtlasedTextureSlot * AddTexture (uint32 TextureWidth, uint32 TextureHeight, const TArray< uint8 > &Data)
Adds a texture to the atlas.
virtual void ConditionalUpdateTexture ()=0
Updates the texture used for rendering if needed.
void EmptyAtlasData ()
Clears atlas cpu data.
uint32 GetHeight () const
const FAtlasedTextureSlot * GetSlotAtPosition (FIntPoint InPosition) const
uint32 GetWidth () const
void MarkTextureDirty ()
Marks the texture as dirty and needing its rendering resources updated.
virtual void ReleaseResources ()=0
Releases rendering resources of this texture.
Protected Attributes
ESlateFontAtlasContentType ContentType
Protected Attributes inherited from FSlateTextureAtlas
TArray< uint8 > AtlasData
Actual texture data contained in the atlas.
TArray< FAtlasedTextureSlot * > AtlasEmptySlotsMap
The list of atlas slots pointing to empty texture data in the atlas.
uint32 AtlasHeight
Height of the atlas.
ESlateTextureAtlasThreadId AtlasOwnerThread
The type of thread that owns this atlas - this is the only thread that can safely update it NOTE: We don't use the thread ID here, as the render thread can be recreated if it gets suspended and resumed, giving it a new ID.
FAtlasedTextureSlot * AtlasUsedSlots
The list of atlas slots pointing to used texture data in the atlas.
uint32 AtlasWidth
Width of the atlas.
bool bNeedsUpdate
True if this texture needs to have its rendering resources updated.
bool bUpdatesAfterInitialization
True if this texture can update after initialziation and we should preserve the atlas slots and cpu memory.
uint32 BytesPerPixel
Bytes per pixel in the atlas.
ESlateTextureAtlasPaddingStyle PaddingStyle
Padding style.
Additional Inherited Members
Protected Member Functions inherited from FSlateTextureAtlas
void AddFreeSlot (uint32 InX, uint32 InY, uint32 InWidth, uint32 InHeight)
Adds a new slot to the free slot list.
void CopyDataIntoSlot (const FAtlasedTextureSlot *SlotToCopyTo, const TArray< uint8 > &Data)
Copies texture data into the atlas at a given slot.
void CopyRow (const FCopyRowData &CopyRowData)
Copies a single row from a source texture to a dest texture, respecting the padding.
const FAtlasedTextureSlot * FindSlotForTexture (uint32 InWidth, uint32 InHeight)
Finds the optimal slot for a texture in the atlas.
void InitAtlasData ()
Creates enough space for a single texture the width and height of the atlas.
void ZeroRow (const FCopyRowData &CopyRowData)
Zeros out a row in the dest texture (used with PaddingStyle == PadWithZero).
Static Protected Member Functions inherited from FSlateTextureAtlas
static int32 GetFreeSlotSearchIndex (uint32 InWidth, uint32 InHeight)
Get the index to start looking for a free slot.
Detailed Description
Representation of a texture for fonts in which characters are packed tightly based on their bounding rectangle.
Definition at line 172 of file FontTypes.h.
Constructor & Destructor Documentation
FSlateFontAtlas()
FSlateFontAtlas::FSlateFontAtlas (uint32 InWidth, uint32 InHeight, ESlateFontAtlasContentType InContentType, ESlateTextureAtlasPaddingStyle InPaddingStyle)
~FSlateFontAtlas()
virtual FSlateFontAtlas::~FSlateFontAtlas () virtual
Member Function Documentation
AddCharacter()
const struct FAtlasedTextureSlot * FSlateFontAtlas::AddCharacter (const FCharacterRenderData & CharInfo)
Adds a character to the texture.
Parameters
CharInfo Information about the size of the character
BeginDeferredAddCharacter()
bool FSlateFontAtlas::BeginDeferredAddCharacter (const int16 InSizeX, const int16 InSizeY, FDeferredCharacterRenderData & OutCharInfo)
Reserve a slot for a character but dont't update the texture yet.
Parameters
InSizeX Width of the character
InSizeY Height of the character
EndDeferredAddCharacter()
void FSlateFontAtlas::EndDeferredAddCharacter (const FDeferredCharacterRenderData & CharInfo)
Update a character in the texture for already reserved or added slot.
Parameters
CharInfo Information about the location and size of the character
Flush()
void FSlateFontAtlas::Flush ()
Flushes all cached data.
GetAtlasDataCopy()
virtual void FSlateFontAtlas::GetAtlasDataCopy (TArray< uint8 > & OutData) const override virtual
Retrieves a copy of the texture atlas data in this texture.
This is a slow operation so this is recommended primarily for debugging and visualization tools.
Parameters
OutData An array that a caller provides. This array will be populated with a copy of the data in the atlas. It is up to the caller to verify that the array is populated and not empty.
Implements ISlateFontTexture.
GetAtlasTexture()
virtual FSlateShaderResource * FSlateFontAtlas::GetAtlasTexture () const inline override virtual
Implements FSlateTextureAtlas.
Definition at line 180 of file FontTypes.h.
References GetAtlasTexture(), and ISlateFontTexture::GetSlateTexture().
Referenced by GetAtlasTexture().
GetContentType()
virtual ESlateFontAtlasContentType FSlateFontAtlas::GetContentType () const final override virtual
Returns the type of content in the texture.
Implements ISlateFontTexture.
ReleaseRenderingResources()
virtual void FSlateFontAtlas::ReleaseRenderingResources () inline virtual
Releases rendering resources of this texture.
Implements ISlateFontTexture.
Definition at line 181 of file FontTypes.h.
References FSlateTextureAtlas::ReleaseResources().
Field Documentation
ContentType
ESlateFontAtlasContentType FSlateFontAtlas::ContentType protected
Definition at line 213 of file FontTypes.h.
The documentation for this class was generated from the following file:
FontTypes.h