Unreal Engine 5.6 C++ API: ALevelScriptActor Class Reference
ALevelScriptActor Class Reference
#include "LevelScriptActor.h"
Private Member Functions
virtual void DisableInput (class APlayerController *PlayerController) override
virtual void EnableInput (class APlayerController *PlayerController) override
TArray< ALevelScriptActor * > FindSiblingLevelScriptActors () const
Utility function for finding a map corruption issue that can cause duplicate level scripting events.
GENERATED_UCLASS_BODY () UFUNCTION()
Tries to find an event named "EventName" on all other levels, and calls it.
bool InputEnabled () const
virtual void PreInitializeComponents () override
virtual bool SupportsExternalPackaging () const override
UFUNCTION ()
Sets the cinematic mode on all PlayerControllers.
UFUNCTION () 1 void LevelReset()
UFUNCTION () 1 void WorldOriginLocationChanged(FIntVector OldOriginLocation
Event called on world origin location changes.
Private Attributes
Category
FIntVector NewOriginLocation
Detailed Description
Definition at line 25 of file LevelScriptActor.h.
Member Function Documentation
DisableInput()
virtual void ALevelScriptActor::DisableInput (class APlayerController * PlayerController) override private virtual
References DisableInput().
Referenced by DisableInput().
EnableInput()
virtual void ALevelScriptActor::EnableInput (class APlayerController * PlayerController) override private virtual
References EnableInput().
Referenced by EnableInput().
FindSiblingLevelScriptActors()
TArray< ALevelScriptActor * > ALevelScriptActor::FindSiblingLevelScriptActors () const private
Utility function for finding a map corruption issue that can cause duplicate level scripting events.
GENERATED_UCLASS_BODY()
ALevelScriptActor::GENERATED_UCLASS_BODY () private
Tries to find an event named "EventName" on all other levels, and calls it.
InputEnabled()
bool ALevelScriptActor::InputEnabled () const inline private
Definition at line 77 of file LevelScriptActor.h.
PreInitializeComponents()
virtual void ALevelScriptActor::PreInitializeComponents () override private virtual
References PreInitializeComponents().
Referenced by PreInitializeComponents().
SupportsExternalPackaging()
virtual bool ALevelScriptActor::SupportsExternalPackaging () const inline override private virtual
Definition at line 70 of file LevelScriptActor.h.
UFUNCTION() [1/3]
ALevelScriptActor::UFUNCTION () private
Sets the cinematic mode on all PlayerControllers.
Parameters
bInCinematicMode specify true if the player is entering cinematic mode; false if the player is leaving cinematic mode.
bHidePlayer specify true to hide the player's pawn (only relevant if bInCinematicMode is true)
bAffectsHUD specify true if we should show/hide the HUD to match the value of bCinematicMode
bAffectsMovement specify true to disable movement in cinematic mode, enable it when leaving
bAffectsTurning specify true to disable turning in cinematic mode or enable it when leaving
References Category, meta, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/3]
ALevelScriptActor::UFUNCTION () private
Todo
document
References UFUNCTION().
UFUNCTION() [3/3]
ALevelScriptActor::UFUNCTION () private
Event called on world origin location changes.
Parameters
OldOriginLocation Previous world origin location
NewOriginLocation New world origin location
References UFUNCTION().
Field Documentation
Category
ALevelScriptActor::Category private
Initial value:
="Miscellaneous")
    1 virtual bool RemoteEvent(FName EventName)
Definition at line 32 of file LevelScriptActor.h.
Referenced by UFUNCTION().
NewOriginLocation
FIntVector ALevelScriptActor::NewOriginLocation private
Definition at line 59 of file LevelScriptActor.h.
The documentation for this class was generated from the following file:
LevelScriptActor.h