Unreal Engine 5.6 C++ API: CompactBinaryContainerSerialization.h File Reference
CompactBinaryContainerSerialization.h File Reference
#include "Serialization/CompactBinary.h"
#include "Serialization/CompactBinaryWriter.h"
#include "Templates/Tuple.h"
Functions
template<typename... Types>
bool LoadFromCompactBinary (FCbFieldView Field, TTuple< Types... > &Tuple)
template<typename... Types>
FCbWriter & operator<< (FCbWriter &Writer, const TTuple< Types... > &Tuple)
Function Documentation
LoadFromCompactBinary()
template<typename... Types> bool LoadFromCompactBinary (FCbFieldView Field, TTuple< Types... > & Tuple) inline
Definition at line 19 of file CompactBinaryContainerSerialization.h.
References FCbFieldView::AsArrayView(), FCbFieldView::CreateViewIterator(), LoadFromCompactBinary(), FCbArrayView::Num(), and VisitTupleElements().
Referenced by LoadFromCompactBinary(), and FMaterialKeyGeneratorContext::Record().
operator<<()
template<typename... Types> FCbWriter & operator<< (FCbWriter & Writer, const TTuple< Types... > & Tuple) inline
Definition at line 10 of file CompactBinaryContainerSerialization.h.
References FCbWriter::BeginArray(), FCbWriter::EndArray(), and VisitTupleElements().