Unreal Engine 5.6 C++ API: FFrameTime Struct Reference
FFrameTime Struct Reference
Structure representing a time by a context-free frame number, plus a sub frame value in the range [0:1) Conversion to and from time in seconds is achieved in combination with FFrameRate.
#include "FrameTime.h"
Public Member Functions
FFrameTime ()
Default constructor initializing to zero.
FFrameTime (FFrameNumber InFrameNumber)
Implicit construction from a type-safe frame number.
FFrameTime (FFrameNumber InFrameNumber, float InSubFrame)
Construction from a frame number and a sub frame.
template<typename T, typename = typename TEnableIf<std::is_same_v<T, int32>>::Type>
FFrameTime (T InFrameNumber)
Implicit construction from a single integer, while disallowing implicit conversion from any other numeric type.
double AsDecimal () const
Retrieve a decimal representation of this frame time Sub frames are always added to the current frame number, so for negative frame times, a time of -10 [sub frame 0.25] will yield a decimal value of -9.75.
FFrameNumber CeilToFrame () const
Return the next frame number greater than or equal to this frame time.
FFrameNumber FloorToFrame () const
Return the first frame number less than or equal to this frame time.
FORCEINLINE FFrameNumber GetFrame () const
Access this time's frame number.
FORCEINLINE float GetSubFrame () const
Access this time's sub frame.
FFrameTime & operator= (FFrameNumber InFrameNumber)
Assignment from a type-safe frame number.
FFrameNumber RoundToFrame () const
Round to the nearest frame number.
bool Serialize (FArchive &Ar)
Serializes the given FrameTime from or into the specified archive.
Static Public Member Functions
static FFrameTime FromDecimal (double InDecimalFrame)
Convert a decimal representation to a frame time Note that sub frames are always positive, so negative decimal representations result in an inverted sub frame and floored frame number.
Data Fields
FFrameNumber FrameNumber
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
Static Public Attributes
static const float MaxSubframe
Private Attributes
float SubFrame
Must be 0.f <= SubFrame < 1.f.
Friends
FORCEINLINE_DEBUGGABLE bool operator!= (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE FFrameTime operator% (FFrameTime A, FFrameTime B)
FORCEINLINE FFrameTime operator* (double Scalar, FFrameTime A)
FORCEINLINE FFrameTime operator* (FFrameTime A, double Scalar)
FORCEINLINE_DEBUGGABLE FFrameTime operator+ (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE FFrameTime & operator+= (FFrameTime &LHS, FFrameTime RHS)
FORCEINLINE_DEBUGGABLE FFrameTime operator- (FFrameTime A)
FORCEINLINE_DEBUGGABLE FFrameTime operator- (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE FFrameTime & operator-= (FFrameTime &LHS, FFrameTime RHS)
FORCEINLINE FFrameTime operator/ (FFrameTime A, double Scalar)
FORCEINLINE_DEBUGGABLE bool operator< (FFrameTime A, FFrameTime B)
FArchive & operator<< (FArchive &Ar, FFrameTime &FrameTime)
Serializes the given FrameTime from or into the specified archive.
FORCEINLINE_DEBUGGABLE bool operator<= (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE bool operator== (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE bool operator> (FFrameTime A, FFrameTime B)
FORCEINLINE_DEBUGGABLE bool operator>= (FFrameTime A, FFrameTime B)
Detailed Description
Structure representing a time by a context-free frame number, plus a sub frame value in the range [0:1) Conversion to and from time in seconds is achieved in combination with FFrameRate.
Only the frame number part of this representation can be negative, sub frames are always a positive value between the frame number and its next logical frame
Definition at line 15 of file FrameTime.h.
Constructor & Destructor Documentation
FFrameTime() [1/4]
FFrameTime::FFrameTime () inline
Default constructor initializing to zero.
Definition at line 249 of file FrameTime.h.
References FrameNumber, and SubFrame.
Referenced by FromDecimal(), operator!=, operator%, operator*, operator*, operator+, operator+=, operator-, operator-, operator-=, operator/, operator<, operator<<, operator<=, operator=(), operator==, operator>, and operator>=.
FFrameTime() [2/4]
template<typename T, typename> FFrameTime::FFrameTime (T InFrameNumber)
Implicit construction from a single integer, while disallowing implicit conversion from any other numeric type.
Definition at line 255 of file FrameTime.h.
References FrameNumber, and SubFrame.
FFrameTime() [3/4]
FFrameTime::FFrameTime (FFrameNumber InFrameNumber) inline
Implicit construction from a type-safe frame number.
Definition at line 260 of file FrameTime.h.
References FrameNumber, and SubFrame.
FFrameTime() [4/4]
FFrameTime::FFrameTime (FFrameNumber InFrameNumber, float InSubFrame) inline
Construction from a frame number and a sub frame.
Definition at line 265 of file FrameTime.h.
References checkSlow, FMath::Clamp(), FrameNumber, MaxSubframe, and SubFrame.
Member Function Documentation
AsDecimal()
FORCEINLINE_DEBUGGABLE double FFrameTime::AsDecimal () const
Retrieve a decimal representation of this frame time Sub frames are always added to the current frame number, so for negative frame times, a time of -10 [sub frame 0.25] will yield a decimal value of -9.75.
Definition at line 308 of file FrameTime.h.
References FORCEINLINE_DEBUGGABLE, FrameNumber, and SubFrame.
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber(), and operator=().
CeilToFrame()
FORCEINLINE_DEBUGGABLE FFrameNumber FFrameTime::CeilToFrame () const
Return the next frame number greater than or equal to this frame time.
Definition at line 296 of file FrameTime.h.
References FORCEINLINE_DEBUGGABLE, FrameNumber, and SubFrame.
FloorToFrame()
FORCEINLINE_DEBUGGABLE FFrameNumber FFrameTime::FloorToFrame () const
Return the first frame number less than or equal to this frame time.
Definition at line 290 of file FrameTime.h.
References FORCEINLINE_DEBUGGABLE, and FrameNumber.
FromDecimal()
FORCEINLINE_DEBUGGABLE FFrameTime FFrameTime::FromDecimal (double InDecimalFrame) static
Convert a decimal representation to a frame time Note that sub frames are always positive, so negative decimal representations result in an inverted sub frame and floored frame number.
Definition at line 313 of file FrameTime.h.
References FFrameTime(), FMath::Clamp(), FORCEINLINE_DEBUGGABLE, and MaxSubframe.
Referenced by UE::MovieScene::ConvertToFrameTimeRange(), operator*, operator*, and operator/.
GetFrame()
FORCEINLINE FFrameNumber FFrameTime::GetFrame () const inline
Access this time's frame number.
Definition at line 56 of file FrameTime.h.
References FORCEINLINE, and FrameNumber.
Referenced by FFrameRate::AsSeconds(), ConvertFrameTime(), IAnimationDataController::ConvertSecondsToFrameNumber(), and DisplayClusterTypesConverter::ToString().
GetSubFrame()
FORCEINLINE float FFrameTime::GetSubFrame () const inline
Access this time's sub frame.
Definition at line 64 of file FrameTime.h.
References FORCEINLINE, and SubFrame.
Referenced by FFrameRate::AsSeconds(), ConvertFrameTime(), IAnimationDataController::ConvertSecondsToFrameNumber(), and DisplayClusterTypesConverter::ToString().
operator=()
FFrameTime & FFrameTime::operator= (FFrameNumber InFrameNumber) inline
Assignment from a type-safe frame number.
Definition at line 283 of file FrameTime.h.
References FFrameTime(), FrameNumber, and SubFrame.
RoundToFrame()
FORCEINLINE_DEBUGGABLE FFrameNumber FFrameTime::RoundToFrame () const
Round to the nearest frame number.
Definition at line 302 of file FrameTime.h.
References FORCEINLINE_DEBUGGABLE, FrameNumber, and SubFrame.
Referenced by TSubSectionMixin< ParentSectionClass >::GetSectionToolTip().
Serialize()
bool FFrameTime::Serialize (FArchive & Ar) inline
Serializes the given FrameTime from or into the specified archive.
Definition at line 275 of file FrameTime.h.
References Ar, FrameNumber, and SubFrame.
Referenced by operator<<.
Friends And Related Symbol Documentation
operator!=
FORCEINLINE_DEBUGGABLE bool operator!= (FFrameTime A, FFrameTime B) friend
Definition at line 126 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator%
FORCEINLINE_DEBUGGABLE FFrameTime operator% (FFrameTime A, FFrameTime B) friend
Definition at line 204 of file FrameTime.h.
References FFrameTime(), A, B, check, and FORCEINLINE_DEBUGGABLE.
operator* [1/2]
FORCEINLINE FFrameTime operator* (double Scalar, FFrameTime A) friend
Definition at line 237 of file FrameTime.h.
References FFrameTime(), A, FORCEINLINE, and FromDecimal().
operator* [2/2]
FORCEINLINE FFrameTime operator* (FFrameTime A, double Scalar) friend
Definition at line 232 of file FrameTime.h.
References FFrameTime(), A, FORCEINLINE, and FromDecimal().
operator+
FORCEINLINE_DEBUGGABLE FFrameTime operator+ (FFrameTime A, FFrameTime B) friend
Definition at line 168 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator+=
FORCEINLINE_DEBUGGABLE FFrameTime & operator+= (FFrameTime & LHS, FFrameTime RHS) friend
Definition at line 156 of file FrameTime.h.
References FFrameTime(), FORCEINLINE_DEBUGGABLE, FrameNumber, SubFrame, and FFrameNumber::Value.
operator- [1/2]
FORCEINLINE_DEBUGGABLE FFrameTime operator- (FFrameTime A) friend
Definition at line 224 of file FrameTime.h.
References FFrameTime(), A, and FORCEINLINE_DEBUGGABLE.
operator- [2/2]
FORCEINLINE_DEBUGGABLE FFrameTime operator- (FFrameTime A, FFrameTime B) friend
Definition at line 192 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator-=
FORCEINLINE_DEBUGGABLE FFrameTime & operator-= (FFrameTime & LHS, FFrameTime RHS) friend
Definition at line 177 of file FrameTime.h.
References FFrameTime(), FORCEINLINE_DEBUGGABLE, FrameNumber, SubFrame, and FFrameNumber::Value.
operator/
FORCEINLINE FFrameTime operator/ (FFrameTime A, double Scalar) friend
Definition at line 242 of file FrameTime.h.
References FFrameTime(), A, FORCEINLINE, and FromDecimal().
operator<
FORCEINLINE_DEBUGGABLE bool operator< (FFrameTime A, FFrameTime B) friend
Definition at line 144 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator<<
FArchive & operator<< (FArchive & Ar, FFrameTime & FrameTime) friend
Serializes the given FrameTime from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
FrameTime The frame time to serialize.
Returns
The archive used for serialization.
Definition at line 114 of file FrameTime.h.
References FFrameTime(), Ar, and Serialize().
operator<=
FORCEINLINE_DEBUGGABLE bool operator<= (FFrameTime A, FFrameTime B) friend
Definition at line 150 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator==
FORCEINLINE_DEBUGGABLE bool operator== (FFrameTime A, FFrameTime B) friend
Definition at line 120 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator>
FORCEINLINE_DEBUGGABLE bool operator> (FFrameTime A, FFrameTime B) friend
Definition at line 132 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
operator>=
FORCEINLINE_DEBUGGABLE bool operator>= (FFrameTime A, FFrameTime B) friend
Definition at line 138 of file FrameTime.h.
References FFrameTime(), A, B, and FORCEINLINE_DEBUGGABLE.
Field Documentation
FrameNumber
FFrameNumber FFrameTime::FrameNumber
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
Definition at line 98 of file FrameTime.h.
Referenced by FFrameTime(), FFrameTime(), FFrameTime(), FFrameTime(), AsDecimal(), CeilToFrame(), FloorToFrame(), GetFrame(), TSubSectionMixin< ParentSectionClass >::GetSectionTime(), operator+=, operator-=, operator=(), FMovieSceneContext::ReportOuterSectionRanges(), RoundToFrame(), and Serialize().
MaxSubframe
const float FFrameTime::MaxSubframe static
Definition at line 18 of file FrameTime.h.
Referenced by FFrameTime(), FFrameRate::AsFrameTime(), ConvertFrameTime(), and FromDecimal().
SubFrame
float FFrameTime::SubFrame private
Must be 0.f <= SubFrame < 1.f.
Definition at line 103 of file FrameTime.h.
Referenced by FFrameTime(), FFrameTime(), FFrameTime(), FFrameTime(), AsDecimal(), CeilToFrame(), GetSubFrame(), operator+=, operator-=, operator=(), RoundToFrame(), and Serialize().
The documentation for this struct was generated from the following file:
FrameTime.h