Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > Class Template Reference
UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > Class Template Reference
TDynamicVertexAttribute provides per-vertex storage of an attribute value.
#include "DynamicVertexAttribute.h"
Public Member Functions
TDynamicVertexAttribute ()
Create an empty overlay.
TDynamicVertexAttribute (ParentType *ParentIn, bool bAutoInit=true)
Create an attribute for the given parent.
virtual ~TDynamicVertexAttribute ()
virtual bool Append (const TDynamicAttributeBase< ParentType > &Source, const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
virtual void AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add default-valued elements, using the AppendInfo to determine the range to add.
virtual bool CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const override
Check validity of attribute.
void CompactCopy (const FCompactMaps &CompactMaps, const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > &ToCopy)
void CompactInPlace (const FCompactMaps &CompactMaps)
Compact the attribute in place.
void Copy (const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > &Copy)
Set this overlay to contain the same arrays as the copy overlay.
virtual bool CopyIn (int RawID, void *Buffer, int BufferSize) override
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyOut (int RawID, void *Buffer, int BufferSize) const override
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyThroughMapping (const TDynamicAttributeBase< ParentType > *Source, const FMeshIndexMappings &Mapping) override
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
void CopyValue (int FromVertexID, int ToVertexID)
Copy the attribute value at FromVertexID to ToVertexID.
virtual SIZE_T GetByteCount () const override
virtual AttribValueType GetDefaultAttributeValue ()
ParentType * GetParent ()
const ParentType * GetParent () const
template<typename AsType>
void GetValue (int VertexID, AsType &Data) const
Get the element at a given index.
void GetValue (int VertexID, AttribValueType *Data) const
Get the element at a given index.
void Initialize (AttribValueType InitialValue=(AttribValueType) 0)
Initialize the attribute values with InitialValue, and resize to the parent mesh's max vertex ID.
bool IsSameAs (const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > &Other, bool bIgnoreDataLayout) const
Returns true if this AttributeSet is the same as Other.
virtual TDynamicAttributeBase< ParentType > * MakeCompactCopy (const FCompactMaps &CompactMaps, ParentType *ParentTypeIn) const override
Allocate a new compact copy of the attribute layer, optionally with a different parent.
virtual TDynamicAttributeBase< ParentType > * MakeCopy (ParentType *ParentIn) const override
Allocate a new copy of the attribute layer, optionally with a different parent.
virtual TDynamicAttributeBase< ParentType > * MakeNew (ParentType *ParentIn) const override
Allocate a new empty instance of the same type of attribute layer.
virtual TUniquePtr< TDynamicAttributeChangeBase< ParentType > > NewBlankChange () const override
void OnCollapseEdge (const FDynamicMesh3::FEdgeCollapseInfo &CollapseInfo) override
Update the overlay to reflect an edge collapse in the parent.
void OnFlipEdge (const FDynamicMesh3::FEdgeFlipInfo &FlipInfo) override
Update the overlay to reflect an edge flip in the parent.
void OnMergeEdges (const FDynamicMesh3::FMergeEdgesInfo &MergeInfo) override
Update the overlay to reflect an edge merge in the parent.
void OnMergeVertices (const FDynamicMesh3::FMergeVerticesInfo &MergeInfo) override
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
virtual void OnNewVertex (int VertexID, bool bInserted) override
void OnPokeTriangle (const FDynamicMesh3::FPokeTriangleInfo &PokeInfo) override
Update the overlay to reflect a face poke in the parent.
void OnSplitEdge (const FDynamicMesh3::FEdgeSplitInfo &SplitInfo) override
Update the overlay to reflect an edge split in the parent.
void OnSplitVertex (const FDynamicMesh3::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate) override
Update the overlay to reflect a vertex split in the parent.
void ResizeAttribStoreIfNeeded (int VertexID)
void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
Serialize to and from an archive.
void SetNewValue (int NewVertexID, const AttribValueType *Data)
void SetScalarValue (int32 VertexID, const AttribValueType &SingleValue)
Set the element at a given index with a scalar value (the same value for each dimension)
template<typename AsType>
void SetValue (int VertexID, const AsType &Data)
Set the element at a given index.
void SetValue (int VertexID, const AttribValueType *Data)
Set the element at a given index.
Public Member Functions inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
virtual ~TDynamicAttributeBase ()
FName GetName () const
Get optional identifier for this attribute set.
virtual void OnNewTriangle (int TriangleID, bool bInserted)
virtual void OnRemoveTriangle (int TriangleID)
virtual void OnRemoveVertex (int VertexID)
virtual void OnReverseTriOrientation (int TriangleID)
void Serialize (FArchive &Ar)
Serialize to and from an archive.
void SetName (FName NameIn)
Set optional identifier for this attribute set.
Protected Types
using Super = TDynamicAttributeBase<ParentType>
Protected Member Functions
virtual void SetAttributeFromBary (int SetAttribute, int AttributeA, int AttributeB, int AttributeC, const FVector3d &BaryCoords)
Set the value at an Attribute to be a barycentric interpolation of three other Attributes.
virtual void SetAttributeFromLerp (int SetAttribute, int AttributeA, int AttributeB, double Alpha)
Set the value at an Attribute to be a linear interpolation of two other Attributes.
Protected Member Functions inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
virtual void CopyParentClassData (const TDynamicAttributeBase< ParentType > &Other)
Implementation of parent-class copy.
Protected Attributes
TDynamicVector< AttribValueType > AttribValues
List of per-vertex attribute values.
ParentType * Parent
The parent object (e.g.
Protected Attributes inherited from UE::Geometry::TDynamicAttributeBase< ParentType >
FName Name = FName()
Optional FName identifier for this attribute set.
Private Member Functions
void Reparent (ParentType *NewParent) override
Update any held pointer to the parent.
Friends
class FDynamicMeshAttributeSet
FArchive & operator<< (FArchive &Ar, TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > &Attr)
Serialization operator for TDynamicVertexAttribute.
Detailed Description
template<typename AttribValueType, int AttribDimension, typename ParentType>
class UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >
TDynamicVertexAttribute provides per-vertex storage of an attribute value.
Definition at line 48 of file DynamicVertexAttribute.h.
Member Typedef Documentation
Super
template<typename AttribValueType, int AttribDimension, typename ParentType> using UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Super = TDynamicAttributeBase<ParentType> protected
Definition at line 58 of file DynamicVertexAttribute.h.
Constructor & Destructor Documentation
TDynamicVertexAttribute() [1/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::TDynamicVertexAttribute () inline
Create an empty overlay.
Definition at line 64 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeCompactCopy(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeCopy(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeNew().
TDynamicVertexAttribute() [2/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::TDynamicVertexAttribute (ParentType * ParentIn, bool bAutoInit = true) inline
Create an attribute for the given parent.
Definition at line 69 of file DynamicVertexAttribute.h.
~TDynamicVertexAttribute()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::~TDynamicVertexAttribute () inline virtual
Definition at line 77 of file DynamicVertexAttribute.h.
Member Function Documentation
Append()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Append (const TDynamicAttributeBase< ParentType > & Source, const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
Returns
true if the append succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 189 of file DynamicVertexAttribute.h.
AppendDefaulted()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add default-valued elements, using the AppendInfo to determine the range to add.
Called when appending from a mesh that does not have this attribute.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 210 of file DynamicVertexAttribute.h.
CheckValidity()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const inline override virtual
Check validity of attribute.
Parameters
bAllowNonmanifold Accept non-manifold topology as valid. Note that this should almost always be true for attributes; non-manifold overlays are generally valid.
FailMode Desired behavior if mesh is found invalid
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 400 of file DynamicVertexAttribute.h.
CompactCopy()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CompactCopy (const FCompactMaps & CompactMaps, const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > & ToCopy) inline
Definition at line 133 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeCompactCopy().
CompactInPlace()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CompactInPlace (const FCompactMaps & CompactMaps) inline virtual
Compact the attribute in place.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 116 of file DynamicVertexAttribute.h.
Copy()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Copy (const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > & Copy) inline
Set this overlay to contain the same arrays as the copy overlay.
Definition at line 102 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeCopy().
CopyIn()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CopyIn (int RawID, void * Buffer, int BufferSize) inline override virtual
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 229 of file DynamicVertexAttribute.h.
CopyOut()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CopyOut (int RawID, void * Buffer, int BufferSize) const inline override virtual
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 215 of file DynamicVertexAttribute.h.
CopyThroughMapping()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CopyThroughMapping (const TDynamicAttributeBase< ParentType > * Source, const FMeshIndexMappings & Mapping) inline override virtual
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
Parameters
Source copy attribute data from this source
Mapping the correspondence from Source's parent to this attribute's parent
Returns
true if the copy succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 174 of file DynamicVertexAttribute.h.
CopyValue()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::CopyValue (int FromVertexID, int ToVertexID) inline
Copy the attribute value at FromVertexID to ToVertexID.
Definition at line 300 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactInPlace(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnSplitVertex().
GetByteCount()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual SIZE_T UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetByteCount () const inline override virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 548 of file DynamicVertexAttribute.h.
GetDefaultAttributeValue()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual AttribValueType UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetDefaultAttributeValue () inline virtual
Definition at line 332 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnNewVertex(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::ResizeAttribStoreIfNeeded().
GetParent() [1/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> ParentType * UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetParent () inline
Returns
the parent for this attribute
Definition at line 84 of file DynamicVertexAttribute.h.
GetParent() [2/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> const ParentType * UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetParent () const inline
Returns
the parent for this attribute
Definition at line 82 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttributeChange< AttribValueType, AttribDimension, ParentType >::Apply().
GetValue() [1/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> template<typename AsType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetValue (int VertexID, AsType & Data) const inline
Get the element at a given index.
For scalar access, use GetValue<T*const>(&Value) for a Value of type T.
Definition at line 256 of file DynamicVertexAttribute.h.
GetValue() [2/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::GetValue (int VertexID, AttribValueType * Data) const inline
Get the element at a given index.
Definition at line 245 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::TDynamicVertexAttributeChange< AttribValueType, AttribDimension, ParentType >::SaveInitialVertex(), and UE::Geometry::TDynamicVertexAttributeChange< AttribValueType, AttribDimension, ParentType >::StoreAllFinalVertices().
Initialize()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Initialize (AttribValueType InitialValue = (AttribValueType)0) inline
Initialize the attribute values with InitialValue, and resize to the parent mesh's max vertex ID.
Definition at line 152 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeCompactCopy(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::MakeNew().
IsSameAs()
template<typename AttribValueType, int AttribDimension, typename ParentType> bool UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::IsSameAs (const TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > & Other, bool bIgnoreDataLayout) const inline
Returns true if this AttributeSet is the same as Other.
Parameters
bIgnoreDataLayout Ignore gaps and padding in the data layout, i.e. the exact index is irrelevant as long as valid entries are equal in value and in the same order.
Definition at line 423 of file DynamicVertexAttribute.h.
MakeCompactCopy()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::MakeCompactCopy (const FCompactMaps & CompactMaps, ParentType * ParentIn) const inline override virtual
Allocate a new compact copy of the attribute layer, optionally with a different parent.
Default implementation does a full copy and then compacts it, usually derived class will want to override this with a more efficient direct compact copy implementation
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 108 of file DynamicVertexAttribute.h.
MakeCopy()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::MakeCopy (ParentType * ParentIn) const inline override virtual
Allocate a new copy of the attribute layer, optionally with a different parent.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 94 of file DynamicVertexAttribute.h.
MakeNew()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual TDynamicAttributeBase< ParentType > * UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::MakeNew (ParentType * ParentIn) const inline override virtual
Allocate a new empty instance of the same type of attribute layer.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 88 of file DynamicVertexAttribute.h.
NewBlankChange()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual TUniquePtr< TDynamicAttributeChangeBase< ParentType > > UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::NewBlankChange () const inline override virtual
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 389 of file DynamicVertexAttribute.h.
OnCollapseEdge()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnCollapseEdge (const FDynamicMesh3::FEdgeCollapseInfo & CollapseInfo) inline override virtual
Update the overlay to reflect an edge collapse in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 327 of file DynamicVertexAttribute.h.
OnFlipEdge()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnFlipEdge (const FDynamicMesh3::FEdgeFlipInfo & FlipInfo) inline override virtual
Update the overlay to reflect an edge flip in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 321 of file DynamicVertexAttribute.h.
OnMergeEdges()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnMergeEdges (const FDynamicMesh3::FMergeEdgesInfo & MergeInfo) inline override virtual
Update the overlay to reflect an edge merge in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 365 of file DynamicVertexAttribute.h.
OnMergeVertices()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnMergeVertices (const FDynamicMesh3::FMergeVerticesInfo & MergeInfo) inline override virtual
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
a vertex merge that resolves as bowtie creation).
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 378 of file DynamicVertexAttribute.h.
OnNewVertex()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnNewVertex (int VertexID, bool bInserted) inline override virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 350 of file DynamicVertexAttribute.h.
OnPokeTriangle()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnPokeTriangle (const FDynamicMesh3::FPokeTriangleInfo & PokeInfo) inline override virtual
Update the overlay to reflect a face poke in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 357 of file DynamicVertexAttribute.h.
OnSplitEdge()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnSplitEdge (const FDynamicMesh3::FEdgeSplitInfo & SplitInfo) inline override virtual
Update the overlay to reflect an edge split in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 314 of file DynamicVertexAttribute.h.
OnSplitVertex()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::OnSplitVertex (const FDynamicMesh3::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate) inline override virtual
Update the overlay to reflect a vertex split in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 384 of file DynamicVertexAttribute.h.
Reparent()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Reparent (ParentType * NewParent) inline override private virtual
Update any held pointer to the parent.
Implements UE::Geometry::TDynamicAttributeBase< ParentType >.
Definition at line 86 of file DynamicVertexAttribute.h.
ResizeAttribStoreIfNeeded()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::ResizeAttribStoreIfNeeded (int VertexID) inline
Definition at line 337 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnNewVertex(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnPokeTriangle(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnSplitEdge().
Serialize()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Serialize (FArchive & Ar, const FCompactMaps * CompactMaps, bool bUseCompression) inline
Serialize to and from an archive.
Parameters
Ar Archive to serialize with.
CompactMaps If this is not a null pointer, the mesh serialization compacted the vertex and/or triangle data using the provided mapping.
bUseCompression Use compression for serializing bulk data.
Definition at line 496 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::operator<<, and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize().
SetAttributeFromBary()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetAttributeFromBary (int SetAttribute, int AttributeA, int AttributeB, int AttributeC, const FVector3d & BaryCoords) inline protected virtual
Set the value at an Attribute to be a barycentric interpolation of three other Attributes.
Definition at line 572 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnPokeTriangle().
SetAttributeFromLerp()
template<typename AttribValueType, int AttribDimension, typename ParentType> virtual void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetAttributeFromLerp (int SetAttribute, int AttributeA, int AttributeB, double Alpha) inline protected virtual
Set the value at an Attribute to be a linear interpolation of two other Attributes.
Definition at line 559 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnCollapseEdge(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnMergeEdges(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnMergeVertices(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnSplitEdge().
SetNewValue()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetNewValue (int NewVertexID, const AttribValueType * Data) inline
Definition at line 159 of file DynamicVertexAttribute.h.
SetScalarValue()
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetScalarValue (int32 VertexID, const AttribValueType & SingleValue) inline
Set the element at a given index with a scalar value (the same value for each dimension)
Definition at line 288 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::OnNewVertex().
SetValue() [1/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> template<typename AsType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetValue (int VertexID, const AsType & Data) inline
Set the element at a given index.
Definition at line 278 of file DynamicVertexAttribute.h.
SetValue() [2/2]
template<typename AttribValueType, int AttribDimension, typename ParentType> void UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::SetValue (int VertexID, const AttribValueType * Data) inline
Set the element at a given index.
Definition at line 267 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Append(), UE::Geometry::TDynamicVertexAttributeChange< AttribValueType, AttribDimension, ParentType >::Apply(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CopyThroughMapping().
Friends And Related Symbol Documentation
FDynamicMeshAttributeSet
template<typename AttribValueType, int AttribDimension, typename ParentType> friend class FDynamicMeshAttributeSet friend
Definition at line 60 of file DynamicVertexAttribute.h.
operator<<
template<typename AttribValueType, int AttribDimension, typename ParentType> FArchive & operator<< (FArchive & Ar, TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType > & Attr) friend
Serialization operator for TDynamicVertexAttribute.
Parameters
Ar Archive to serialize with.
Attr Vertex attribute to serialize.
Returns
Passing down serializing archive.
Definition at line 483 of file DynamicVertexAttribute.h.
Field Documentation
AttribValues
template<typename AttribValueType, int AttribDimension, typename ParentType> TDynamicVector<AttribValueType> UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::AttribValues protected
List of per-vertex attribute values.
Definition at line 56 of file DynamicVertexAttribute.h.
Referenced by UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy().
Parent
template<typename AttribValueType, int AttribDimension, typename ParentType> ParentType* UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, ParentType >::Parent protected
The parent object (e.g.
mesh, point set) this attribute belongs to
Definition at line 53 of file DynamicVertexAttribute.h.
The documentation for this class was generated from the following file:
DynamicVertexAttribute.h