Unreal Engine 5.6 C++ API: MovieSceneObjectBindingID.h File Reference
MovieSceneObjectBindingID.h File Reference
#include "Containers/ArrayView.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Misc/Guid.h"
#include "MovieSceneFwd.h"
#include "MovieSceneSequenceID.h"
#include "Templates/TypeHash.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "MovieSceneObjectBindingID.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneObjectBindingID >
struct UE::MovieScene::FFixedObjectBindingID
A binding ID that is only resolveable through a fixed root sequence.
struct UE::MovieScene::FRelativeObjectBindingID
A binding ID whose target is resolved relative to the owner of this ID (either internal or external to that sequence through a parent or grandparent) Should be used for asignment to any serialized FMovieSceneObjectBindingID Represented by a local object binding ID and a parent index to which it is relative.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Functions
UENUM() enum class EMovieSceneObjectBindingSpace USTRUCT ()) struct FMovieSceneObjectBindingID
Enumeration specifying how a movie scene object binding ID relates to the sequence.
Function Documentation
USTRUCT()
UENUM() enum class EMovieSceneObjectBindingSpace USTRUCT ()
Enumeration specifying how a movie scene object binding ID relates to the sequence.
Persistent identifier to a specific object binding within a sequence hierarchy.
Binding IDs come in 3 flavors with Local and External being preferred as they are reslilient towards sequences being authored in isolation or included in other root sequences: Local: (ResolveParentIndex == 0) SequenceID relates to this sequence's local hierarchy; represents an object binding within the same sequence as the ID is resolved, or inside one of its sub-sequences. Sequence ID must be remapped at runtime. External: (ResolveParentIndex > 0) SequenceID is local to the parent sequence of this one denoted by the parent index (ie, 1 = parent, 2 = grandparent etc). Sequence ID must be remapped at runtime. Fixed: Represents a binding anywhere in the sequence; always resolved from the root sequence.
Fixed bindings will break if the sequence is evaluated inside a different root sequence.
Default construction to a root empty. Only to be used for UObject serialization and default UObject construction
Construction from an external object binding ID
Construction from a fixed object binding ID
Assignment from an external object binding ID
Assignment from a fixed object binding ID
Check whether this object binding ID has been set to something valied
Note
: does not imply that the ID resolves to a valid object
Check whether this binding is fixed to the root sequence - these bindings should be avoided or fixed up where possible to ensure portability
Access the guid that identifies the object binding within the sequence
Set the guid that identifies the object binding within the sequence
Get the relative sequence ID for this binding.
Note
: The meaning of this sequence ID is dependent upon ResolveParentIndex so should only be used where the context is known
Resolve this binding ID to a fixed object binding ID resolvable from the root sequence
Parameters
SourceSequenceID The source sequence ID that owns this binding ID
Player The movie scene player that is currently playing the root sequence
Returns
A fixed binding ID whose SequenceID relates to the root sequence hierarchy
Resolve the sequence ID for this binding for the root sequence
Parameters
SourceSequenceID The source sequence ID that owns this binding ID
Player The movie scene player that is currently playing the sequence
Returns
The sequence ID that holds the target object
Resolve the sequence ID for this binding for the root sequence
Parameters
SourceSequenceID The source sequence ID that owns this binding ID
Hierarchy The hierachy to use for computation of the relative path. Many be nullptr where Source and Targets are both MovieSceneSequenceID::Root
Returns
The sequence ID that holds the target object
Resolve all the bound objects for this binding ID
Parameters
SourceSequenceID The source sequence ID that owns this binding ID
Hierarchy The hierachy to use for computation of the relative path. Many be nullptr where Source and Targets are both MovieSceneSequenceID::Root
Returns
An array view of all bound objects
Resolve all the bound objects for this binding ID
Parameters
SequenceInstance The sequence instance for the sub sequence that is resolving the binding
Returns
An array view of all bound objects
Reinterpret this binding ID as a fixed binding. Should only be used when ResolveParentIndex == -1, although this is not enforced.
Identifier for the object binding within the sequence
Sequence ID stored as an int32 so that it can be used in the blueprint VM
The parent index to resolve the sequence ID from. 0 signifies the sequence this binding ID is serialized within, -1 signifies the root sequence (previously EMovieSceneObjectBindingSpace::Root)
Definition at line 201 of file MovieSceneObjectBindingID.h.
References A, Ar, B, BlueprintType, Category, ensureMsgf, GENERATED_BODY, GetTypeHash(), Guid, UE::MovieScene::FFixedObjectBindingID::Guid, UE::MovieScene::FRelativeObjectBindingID::Guid, HasNativeMake, IsValid(), meta, operator!=(), operator=(), operator==(), UE::MovieScene::FRelativeObjectBindingID::ResolveParentIndex, MovieSceneSequenceID::Root, UE::MovieScene::FFixedObjectBindingID::SequenceID, UE::MovieScene::FRelativeObjectBindingID::SequenceID, TEXT, and UPROPERTY.