Unreal Engine 5.6 C++ API: SkeletalMeshImportData::FVertex Struct Reference
SkeletalMeshImportData::FVertex Struct Reference
#include "SkeletalMeshLODImporterData.h"
Public Member Functions
FVertex ()
bool operator== (const FVertex &Other) const
Data Fields
FColor Color
uint8 MatIndex
uint8 Reserved
FVector2f UVs [MAX_TEXCOORDS]
uint32 VertexIndex
Friends
uint32 GetTypeHash (const FVertex &Vertex)
FArchive & operator<< (FArchive &Ar, FVertex &F)
Detailed Description
Definition at line 225 of file SkeletalMeshLODImporterData.h.
Constructor & Destructor Documentation
FVertex()
SkeletalMeshImportData::FVertex::FVertex () inline
Definition at line 233 of file SkeletalMeshLODImporterData.h.
References FVertex(), and FMemory::Memzero().
Referenced by FVertex(), GetTypeHash, operator<<, and operator==().
Member Function Documentation
operator==()
bool SkeletalMeshImportData::FVertex::operator== (const FVertex & Other) const inline
Definition at line 238 of file SkeletalMeshLODImporterData.h.
References FVertex(), Color, Equal, MatIndex, MAX_TEXCOORDS, Other, Reserved, UE_SMALL_NUMBER, UVs, and VertexIndex.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FVertex & Vertex) friend
Definition at line 262 of file SkeletalMeshLODImporterData.h.
References FVertex(), FCrc::MemCrc_DEPRECATED(), and Vertex.
operator<<
FArchive & operator<< (FArchive & Ar, FVertex & F) friend
Definition at line 267 of file SkeletalMeshLODImporterData.h.
References FVertex(), Ar, Color, MatIndex, MAX_TEXCOORDS, Reserved, UVs, and VertexIndex.
Field Documentation
Color
FColor SkeletalMeshImportData::FVertex::Color
Definition at line 229 of file SkeletalMeshLODImporterData.h.
Referenced by operator<<, and operator==().
MatIndex
uint8 SkeletalMeshImportData::FVertex::MatIndex
Definition at line 230 of file SkeletalMeshLODImporterData.h.
Referenced by operator<<, and operator==().
Reserved
uint8 SkeletalMeshImportData::FVertex::Reserved
Definition at line 231 of file SkeletalMeshLODImporterData.h.
Referenced by operator<<, and operator==().
UVs
FVector2f SkeletalMeshImportData::FVertex::UVs[MAX_TEXCOORDS]
Definition at line 228 of file SkeletalMeshLODImporterData.h.
Referenced by operator<<, and operator==().
VertexIndex
uint32 SkeletalMeshImportData::FVertex::VertexIndex
Definition at line 227 of file SkeletalMeshLODImporterData.h.
Referenced by operator<<, and operator==().
The documentation for this struct was generated from the following file:
SkeletalMeshLODImporterData.h