Unreal Engine 5.6 C++ API: TPaddingWidgetSlotMixin< MixedIntoType > Class Template Reference
TPaddingWidgetSlotMixin< MixedIntoType > Class Template Reference
Mixin to add the padding functionality to a base slot.
#include "BasicLayoutWidgetSlot.h"
Data Structures
struct FSlotArgumentsMixin
Public Member Functions
TPaddingWidgetSlotMixin ()
TPaddingWidgetSlotMixin (const FMargin &Margin)
FMargin GetPadding () const
void SetPadding (TAttribute< FMargin > InPadding)
Protected Member Functions
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Static Protected Member Functions
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Private Types
using SlotPaddingCompareType = TSlateAttributeComparePredicate<>
using SlotPaddingType = ::SlateAttributePrivate::TSlateContainedAttribute<FMargin, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, SlotPaddingCompareType>
Private Attributes
SlotPaddingType SlotPaddingAttribute
Detailed Description
template<typename MixedIntoType>
class TPaddingWidgetSlotMixin< MixedIntoType >
Mixin to add the padding functionality to a base slot.
Definition at line 201 of file BasicLayoutWidgetSlot.h.
Member Typedef Documentation
SlotPaddingCompareType
template<typename MixedIntoType> using TPaddingWidgetSlotMixin< MixedIntoType >::SlotPaddingCompareType = TSlateAttributeComparePredicate<> private
Definition at line 270 of file BasicLayoutWidgetSlot.h.
SlotPaddingType
template<typename MixedIntoType> using TPaddingWidgetSlotMixin< MixedIntoType >::SlotPaddingType = ::SlateAttributePrivate::TSlateContainedAttribute<FMargin, ::SlateAttributePrivate::FSlateAttributeNoInvalidationReason, SlotPaddingCompareType> private
Definition at line 271 of file BasicLayoutWidgetSlot.h.
Constructor & Destructor Documentation
TPaddingWidgetSlotMixin() [1/2]
template<typename MixedIntoType> TPaddingWidgetSlotMixin< MixedIntoType >::TPaddingWidgetSlotMixin () inline
Definition at line 204 of file BasicLayoutWidgetSlot.h.
References SlotPaddingAttribute.
TPaddingWidgetSlotMixin() [2/2]
template<typename MixedIntoType> TPaddingWidgetSlotMixin< MixedIntoType >::TPaddingWidgetSlotMixin (const FMargin & Margin) inline
Definition at line 207 of file BasicLayoutWidgetSlot.h.
References SlotPaddingAttribute.
Member Function Documentation
ConstructMixin()
template<typename MixedIntoType> void TPaddingWidgetSlotMixin< MixedIntoType >::ConstructMixin (const FChildren & SlotOwner, FSlotArgumentsMixin && InArgs) inline protected
Definition at line 245 of file BasicLayoutWidgetSlot.h.
References MoveTemp(), and SlotPaddingAttribute.
GetPadding()
template<typename MixedIntoType> FMargin TPaddingWidgetSlotMixin< MixedIntoType >::GetPadding () const inline
Definition at line 264 of file BasicLayoutWidgetSlot.h.
References SlotPaddingAttribute.
RegisterAttributesMixin()
template<typename MixedIntoType> void TPaddingWidgetSlotMixin< MixedIntoType >::RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer & AttributeInitializer) inline static protected
Definition at line 253 of file BasicLayoutWidgetSlot.h.
References Layout, SLATE_ADD_SLOT_ATTRIBUTE_DEFINITION_WITH_NAME, and SlotPaddingAttribute.
Referenced by TBasicLayoutWidgetSlot< SlotType >::RegisterAttributes().
SetPadding()
template<typename MixedIntoType> void TPaddingWidgetSlotMixin< MixedIntoType >::SetPadding (TAttribute< FMargin > InPadding) inline
Definition at line 259 of file BasicLayoutWidgetSlot.h.
References MoveTemp(), and SlotPaddingAttribute.
Field Documentation
SlotPaddingAttribute
template<typename MixedIntoType> SlotPaddingType TPaddingWidgetSlotMixin< MixedIntoType >::SlotPaddingAttribute private
Definition at line 272 of file BasicLayoutWidgetSlot.h.
Referenced by TPaddingWidgetSlotMixin(), TPaddingWidgetSlotMixin(), ConstructMixin(), GetPadding(), RegisterAttributesMixin(), and SetPadding().
The documentation for this class was generated from the following file:
BasicLayoutWidgetSlot.h