Unreal Engine 5.6 C++ API: UE::Sequencer::FScopedViewModelListHead Struct Reference
UE::Sequencer::FScopedViewModelListHead Struct Reference
Scoped object that adds a temporary child list to the specified model of the specified type.
#include "ViewModelHierarchy.h"
Public Member Functions
FScopedViewModelListHead (const FScopedViewModelListHead &)=delete
Non-copyable and non-moveable since a pointer to our ListHead member is added to our owner.
FScopedViewModelListHead (const TSharedPtr< FViewModel > &InModel, EViewModelListType InType)
Constructor that adds the list to the model.
FScopedViewModelListHead (FScopedViewModelListHead &&)=delete
~FScopedViewModelListHead ()
Destructor that removes the list to the model.
FViewModelChildren GetChildren ()
Retrieve this child list.
FScopedViewModelListHead & operator= (const FScopedViewModelListHead &)=delete
FScopedViewModelListHead & operator= (FScopedViewModelListHead &&)=delete
Private Attributes
FViewModelListHead ListHead
List head whose pointer is added to Model's ChildLists.
TSharedPtr< FViewModel > Model
The model that contains our child list.
Detailed Description
Scoped object that adds a temporary child list to the specified model of the specified type.
Primarily used during regeneration of children to temporarily introduce a 'Recycled' child list
Definition at line 155 of file ViewModelHierarchy.h.
Constructor & Destructor Documentation
FScopedViewModelListHead() [1/3]
UE::Sequencer::FScopedViewModelListHead::FScopedViewModelListHead (const TSharedPtr< FViewModel > & InModel, EViewModelListType InType)
Constructor that adds the list to the model.
Referenced by FScopedViewModelListHead(), FScopedViewModelListHead(), operator=(), and operator=().
~FScopedViewModelListHead()
UE::Sequencer::FScopedViewModelListHead::~FScopedViewModelListHead ()
Destructor that removes the list to the model.
FScopedViewModelListHead() [2/3]
UE::Sequencer::FScopedViewModelListHead::FScopedViewModelListHead (const FScopedViewModelListHead &) delete
Non-copyable and non-moveable since a pointer to our ListHead member is added to our owner.
References FScopedViewModelListHead().
FScopedViewModelListHead() [3/3]
UE::Sequencer::FScopedViewModelListHead::FScopedViewModelListHead (FScopedViewModelListHead &&) delete
References FScopedViewModelListHead().
Member Function Documentation
GetChildren()
FViewModelChildren UE::Sequencer::FScopedViewModelListHead::GetChildren ()
Retrieve this child list.
operator=() [1/2]
FScopedViewModelListHead & UE::Sequencer::FScopedViewModelListHead::operator= (const FScopedViewModelListHead &) delete
References FScopedViewModelListHead().
operator=() [2/2]
FScopedViewModelListHead & UE::Sequencer::FScopedViewModelListHead::operator= (FScopedViewModelListHead &&) delete
References FScopedViewModelListHead().
Field Documentation
ListHead
FViewModelListHead UE::Sequencer::FScopedViewModelListHead::ListHead private
List head whose pointer is added to Model's ChildLists.
Definition at line 179 of file ViewModelHierarchy.h.
Model
TSharedPtr<FViewModel> UE::Sequencer::FScopedViewModelListHead::Model private
The model that contains our child list.
Definition at line 177 of file ViewModelHierarchy.h.
The documentation for this struct was generated from the following file:
ViewModelHierarchy.h