Unreal Engine 5.6 C++ API: FSkelMeshUpdateContext Struct Reference
FSkelMeshUpdateContext Struct Reference
A context used to update or proceed with the next update step.
#include "SkeletalMeshUpdate.h"
Public Types
typedef int32 EThreadType
Public Member Functions
FSkelMeshUpdateContext (const USkeletalMesh *InMesh, EThreadType InCurrentThread)
FSkelMeshUpdateContext (const UStreamableRenderAsset *InMesh, EThreadType InCurrentThread)
EThreadType GetCurrentThread () const
Data Fields
int32 AssetLODBias = 0
Cached value of mesh its LOD bias (MinLOD for SkeletalMesh).
EThreadType CurrentThread
The thread on which the context was created.
TArrayView< FSkeletalMeshLODRenderData * > LODResourcesView
The array view of streamable LODs from the asset.
const USkeletalMesh * Mesh
The mesh to update, this must be the same one as the one used when creating the FSkeletalMeshUpdate object.
FSkeletalMeshRenderData * RenderData
The current render data of this mesh.
Detailed Description
A context used to update or proceed with the next update step.
The mesh and render data references could be stored in the update object but are currently kept outside to avoid lifetime management within the object.
Definition at line 28 of file SkeletalMeshUpdate.h.
Member Typedef Documentation
EThreadType
typedef int32 FSkelMeshUpdateContext::EThreadType
Definition at line 30 of file SkeletalMeshUpdate.h.
Constructor & Destructor Documentation
FSkelMeshUpdateContext() [1/2]
FSkelMeshUpdateContext::FSkelMeshUpdateContext (const USkeletalMesh * InMesh, EThreadType InCurrentThread)
Definition at line 27 of file SkeletalMeshUpdate.cpp.
References AssetLODBias, check, checkSlow, CurrentThread, IsInRenderingThread(), LODResourcesView, Mesh, RenderData, and FRenderAssetUpdate::TT_Render.
Referenced by FSkelMeshUpdateContext().
FSkelMeshUpdateContext() [2/2]
FSkelMeshUpdateContext::FSkelMeshUpdateContext (const UStreamableRenderAsset * InMesh, EThreadType InCurrentThread)
Definition at line 41 of file SkeletalMeshUpdate.cpp.
References FSkelMeshUpdateContext(), and Cast().
Member Function Documentation
GetCurrentThread()
EThreadType FSkelMeshUpdateContext::GetCurrentThread () const inline
Definition at line 36 of file SkeletalMeshUpdate.h.
References CurrentThread.
Field Documentation
AssetLODBias
int32 FSkelMeshUpdateContext::AssetLODBias = 0
Cached value of mesh its LOD bias (MinLOD for SkeletalMesh).
Definition at line 48 of file SkeletalMeshUpdate.h.
Referenced by FSkelMeshUpdateContext().
CurrentThread
EThreadType FSkelMeshUpdateContext::CurrentThread
The thread on which the context was created.
Definition at line 51 of file SkeletalMeshUpdate.h.
Referenced by FSkelMeshUpdateContext(), and GetCurrentThread().
LODResourcesView
TArrayView<FSkeletalMeshLODRenderData*> FSkelMeshUpdateContext::LODResourcesView
The array view of streamable LODs from the asset.
Takes into account FStreamableRenderResourceState::AssetLODBias and FStreamableRenderResourceState::MaxNumLODs.
Definition at line 46 of file SkeletalMeshUpdate.h.
Referenced by FSkelMeshUpdateContext().
Mesh
const USkeletalMesh* FSkelMeshUpdateContext::Mesh
The mesh to update, this must be the same one as the one used when creating the FSkeletalMeshUpdate object.
Definition at line 42 of file SkeletalMeshUpdate.h.
Referenced by FSkelMeshUpdateContext().
RenderData
FSkeletalMeshRenderData* FSkelMeshUpdateContext::RenderData
The current render data of this mesh.
Definition at line 44 of file SkeletalMeshUpdate.h.
Referenced by FSkelMeshUpdateContext().
The documentation for this struct was generated from the following files:
SkeletalMeshUpdate.h
SkeletalMeshUpdate.cpp