Unreal Engine 5.6 C++ API: TMeshElementArrayBase< ElementType > Class Template Reference
TMeshElementArrayBase< ElementType > Class Template Reference
This defines the container used to hold mesh elements.
#include "MeshElementArray.h"
Public Member Functions
void Compact (TSparseArray< int32 > &OutIndexRemap)
Compacts elements and returns a remapping table.
void Remap (const TSparseArray< int32 > &IndexRemap)
Remaps elements according to the passed remapping table.
Protected Attributes
TSparseArray< ElementType > Container
The actual container, represented by a sparse array.
Friends
FArchive & operator<< (FArchive &Ar, TMeshElementArrayBase &Array)
Custom serialization for TMeshElementArrayBase.
Detailed Description
template<typename ElementType>
class TMeshElementArrayBase< ElementType >
This defines the container used to hold mesh elements.
Its important properties are that it acts as an associative container (i.e. an element can be obtained from a given index), and that insert/delete/find are cheap. The current implementation is as a TSparseArray, but we abstract it so that this can be changed later if required, e.g. a TMap might be desirable if we wished to maintain unique indices for the lifetime of the container.
Definition at line 15 of file MeshElementArray.h.
Member Function Documentation
Compact()
template<typename ElementType> void TMeshElementArrayBase< ElementType >::Compact (TSparseArray< int32 > & OutIndexRemap)
Compacts elements and returns a remapping table.
Definition at line 268 of file MeshElementArray.h.
References TSparseArray< InElementType, Allocator >::Add(), Container, TSparseArray< InElementType, Allocator >::Empty(), TSparseArray< InElementType, Allocator >::Insert(), MoveTemp(), and TSparseArray< InElementType, Allocator >::Reserve().
Remap()
template<typename ElementType> void TMeshElementArrayBase< ElementType >::Remap (const TSparseArray< int32 > & IndexRemap)
Remaps elements according to the passed remapping table.
Definition at line 293 of file MeshElementArray.h.
References check, Container, TSparseArray< InElementType, Allocator >::GetMaxIndex(), TSparseArray< InElementType, Allocator >::Insert(), TSparseArray< InElementType, Allocator >::IsAllocated(), MoveTemp(), and TSparseArray< InElementType, Allocator >::Reserve().
Friends And Related Symbol Documentation
operator<<
template<typename ElementType> FArchive & operator<< (FArchive & Ar, TMeshElementArrayBase< ElementType > & Array) friend
Custom serialization for TMeshElementArrayBase.
The default TSparseArray serialization also compacts all the elements, removing the gaps and changing the indices. The indices are significant in editable meshes, hence this is a custom serializer which preserves them.
Definition at line 24 of file MeshElementArray.h.
References Ar, Array, TBitArray< Allocator >::Num(), and TBitArray< Allocator >::SetNumUninitialized().
Field Documentation
Container
template<typename ElementType> TSparseArray<ElementType> TMeshElementArrayBase< ElementType >::Container protected
The actual container, represented by a sparse array.
Definition at line 84 of file MeshElementArray.h.
Referenced by TMeshElementArray< ElementType, ElementIDType >::Add(), TMeshElementArray< ElementType, ElementIDType >::Add(), TMeshElementArray< ElementType, ElementIDType >::Add(), Compact(), TMeshElementArray< ElementType, ElementIDType >::GetArraySize(), TMeshElementArray< ElementType, ElementIDType >::GetElementIDs(), TMeshElementArray< ElementType, ElementIDType >::GetFirstValidID(), TMeshElementArray< ElementType, ElementIDType >::Insert(), TMeshElementArray< ElementType, ElementIDType >::Insert(), TMeshElementArray< ElementType, ElementIDType >::Insert(), TMeshElementArray< ElementType, ElementIDType >::IsValid(), TMeshElementArray< ElementType, ElementIDType >::Num(), TMeshElementArray< ElementType, ElementIDType >::operator[](), TMeshElementArray< ElementType, ElementIDType >::operator[](), Remap(), TMeshElementArray< ElementType, ElementIDType >::Remove(), TMeshElementArray< ElementType, ElementIDType >::Reserve(), and TMeshElementArray< ElementType, ElementIDType >::Reset().
The documentation for this class was generated from the following file:
MeshElementArray.h