Unreal Engine 5.6 C++ API: RigVMVariableDescription.h File Reference
RigVMVariableDescription.h File Reference
#include "RigVMCore/RigVMExternalVariable.h"
#include "RigVMModel/RigVMNode.h"
#include "EdGraphSchema_K2.h"
#include "RigVMDeveloperTypeUtils.h"
#include "RigVMVariableDescription.generated.h"
Functions
USTRUCT () struct FRigVMGraphVariableDescription
The variable description is used to convey information about unique variables within a Graph.
Function Documentation
USTRUCT()
USTRUCT ()
The variable description is used to convey information about unique variables within a Graph.
Multiple Variable Nodes can share the same variable description.
Definition at line 16 of file RigVMVariableDescription.h.
References BlueprintType, Category, RigVMTypeUtils::CPPTypeFromPinType(), RigVMTypeUtils::ExternalVariableFromRigVMVariableDescription(), FRigVMExternalVariable, GENERATED_BODY, Name, Object, operator==(), Other, RigVMTypeUtils::PinTypeFromRigVMVariableDescription(), and UPROPERTY.