Unreal Engine 5.6 C++ API: UObject::FAssetRegistryTag Struct Reference
UObject::FAssetRegistryTag Struct Reference
Struct used by GetAssetRegistryTags() to return tag info.
#include "Object.h"
Public Types
enum ETagDisplay {
TD_None = 0 , TD_Date = 1<<0 , TD_Time = 1<<1 , TD_InvariantTz = 1<<2 ,
TD_Memory = 1<<3
}
Flags controlling how this tag should be shown in the UI.
enum ETagType {
TT_Hidden , TT_Alphabetical , TT_Numerical , TT_Dimensional ,
TT_Chronological
}
Enum specifying the type of this tag.
Public Member Functions
FAssetRegistryTag ()=default
FAssetRegistryTag (FName InName, const FString &InValue, ETagType InType, uint32 InDisplayFlags=TD_None)
FAssetRegistryTag (FName InName, FString &&InValue, ETagType InType, uint32 InDisplayFlags=TD_None)
DECLARE_TS_MULTICAST_DELEGATE_OneParam (FOnGetObjectAssetRegistryTagsWithContext, FAssetRegistryTagsContext)
Event for listeners who want to add tags to some UObjects' GetAssetRegistryTags.
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnGetExtendedAssetRegistryTagsForSave, const UObject *, const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &)
DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnGetObjectAssetRegistryTags, const UObject *, TArray< FAssetRegistryTag > &)
UE_DEPRECATED (5.4, "Subscribe to OnGetExtraObjectTagsWithContext instead") 1 static FOnGetObjectAssetRegistryTags OnGetExtraObjectTags
UE_DEPRECATED (5.4, "Subscribe to OnGetExtraObjectTagsWithContext instead, and early exit if !Context.IsSaving") 1 static FOnGetExtendedAssetRegistryTagsForSave OnGetExtendedAssetRegistryTagsForSave
Data Fields
uint32 DisplayFlags = TD_None
Flags describing more detail for displaying in the UI.
FName Name
Logical name of this tag.
ETagType Type = TT_Alphabetical
Broad description of kind of data represented in Value.
FString Value
Value string for this tag, may represent any data type.
Static Public Attributes
static FOnGetObjectAssetRegistryTagsWithContext OnGetExtraObjectTagsWithContext
Detailed Description
Struct used by GetAssetRegistryTags() to return tag info.
Definition at line 828 of file Object.h.
Member Enumeration Documentation
ETagDisplay
enum UObject::FAssetRegistryTag::ETagDisplay
Flags controlling how this tag should be shown in the UI.
Enumerator
TD_None
No special display.
TD_Date
For TT_Chronological, include the date.
TD_Time
For TT_Chronological, include the time.
TD_InvariantTz
For TT_Chronological, specifies that the timestamp should be displayed using the invariant timezone (typically for timestamps that are already in local time)
TD_Memory
For TT_Numerical, specifies that the number is a value in bytes that should be displayed using FText::AsMemory.
Definition at line 846 of file Object.h.
ETagType
enum UObject::FAssetRegistryTag::ETagType
Enum specifying the type of this tag.
Enumerator
TT_Hidden
This tag should not be shown in the UI.
TT_Alphabetical
This tag should be shown, and sorted alphabetically in the UI.
TT_Numerical
This tag should be shown, and is a number.
TT_Dimensional
This tag should be shown, and is an "x" delimited list of dimensions.
TT_Chronological
This tag should be shown, and is a timestamp formatted via FDateTime::ToString.
Definition at line 831 of file Object.h.
Constructor & Destructor Documentation
FAssetRegistryTag() [1/3]
UObject::FAssetRegistryTag::FAssetRegistryTag () default
Referenced by DECLARE_TS_MULTICAST_DELEGATE_ThreeParams().
FAssetRegistryTag() [2/3]
UObject::FAssetRegistryTag::FAssetRegistryTag (FName InName, const FString & InValue, ETagType InType, uint32 InDisplayFlags = TD_None) inline
Definition at line 873 of file Object.h.
References DisplayFlags, InName, Name, TD_None, Type, and Value.
FAssetRegistryTag() [3/3]
UObject::FAssetRegistryTag::FAssetRegistryTag (FName InName, FString && InValue, ETagType InType, uint32 InDisplayFlags = TD_None) inline
Definition at line 875 of file Object.h.
References DisplayFlags, InName, MoveTemp(), Name, TD_None, Type, and Value.
Member Function Documentation
DECLARE_TS_MULTICAST_DELEGATE_OneParam()
UObject::FAssetRegistryTag::DECLARE_TS_MULTICAST_DELEGATE_OneParam (FOnGetObjectAssetRegistryTagsWithContext , FAssetRegistryTagsContext)
Event for listeners who want to add tags to some UObjects' GetAssetRegistryTags.
Listeners should be threadsafe as this event may be broadcast on a background thread during concurrent save
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams()
UObject::FAssetRegistryTag::DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnGetExtendedAssetRegistryTagsForSave , const UObject * , const ITargetPlatform * TargetPlatform, TArray< FAssetRegistryTag > &)
References FAssetRegistryTag(), UObject::UObject(), and DECLARE_TS_MULTICAST_DELEGATE_ThreeParams().
Referenced by DECLARE_TS_MULTICAST_DELEGATE_ThreeParams().
DECLARE_TS_MULTICAST_DELEGATE_TwoParams()
UObject::FAssetRegistryTag::DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnGetObjectAssetRegistryTags , const UObject * , TArray< FAssetRegistryTag > &)
References UObject::UObject().
UE_DEPRECATED() [1/2]
UObject::FAssetRegistryTag::UE_DEPRECATED (5. 4, "Subscribe to OnGetExtraObjectTagsWithContext instead")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UObject::FAssetRegistryTag::UE_DEPRECATED (5. 4, "Subscribe to OnGetExtraObjectTagsWithContext instead, and early exit if !Context.IsSaving")
References UE_DEPRECATED().
Field Documentation
DisplayFlags
uint32 UObject::FAssetRegistryTag::DisplayFlags = TD_None
Flags describing more detail for displaying in the UI.
Definition at line 870 of file Object.h.
Referenced by FAssetRegistryTag(), and FAssetRegistryTag().
Name
FName UObject::FAssetRegistryTag::Name
Logical name of this tag.
Definition at line 861 of file Object.h.
Referenced by FAssetRegistryTag(), and FAssetRegistryTag().
OnGetExtraObjectTagsWithContext
FOnGetObjectAssetRegistryTagsWithContext UObject::FAssetRegistryTag::OnGetExtraObjectTagsWithContext static
Definition at line 883 of file Object.h.
Type
ETagType UObject::FAssetRegistryTag::Type = TT_Alphabetical
Broad description of kind of data represented in Value.
Definition at line 867 of file Object.h.
Referenced by FAssetRegistryTag(), and FAssetRegistryTag().
Value
FString UObject::FAssetRegistryTag::Value
Value string for this tag, may represent any data type.
Definition at line 864 of file Object.h.
Referenced by FAssetRegistryTag(), and FAssetRegistryTag().
The documentation for this struct was generated from the following file:
Object.h