Unreal Engine 5.6 C++ API: UTextRenderComponent Class Reference
UTextRenderComponent Class Reference
#include "TextRenderComponent.h"
Private Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
GENERATED_UCLASS_BODY () UPROPERTY()) FText Text
Text content, can be multi line using
as line separator.
virtual UMaterialInterface * GetMaterial (int32 ElementIndex) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual int32 GetNumMaterials () const override
virtual FMatrix GetRenderMatrix () const override
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual void PostLoad () override
virtual void PrecachePSOs () override
virtual bool RequiresGameThreadEndOfFrameUpdates () const override
virtual void SetMaterial (int32 ElementIndex, UMaterialInterface *InMaterial) override
virtual bool ShouldRecreateProxyOnUpdateTransform () const override
UFUNCTION () 1 FVector GetTextLocalSize() const
Get local size of text.
UFUNCTION () 1 FVector GetTextWorldSize() const
Get world space size of text.
UFUNCTION () 1 void SetFont(UFont *Value)
Change the font and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetHorizontalAlignment(EHorizTextAligment Value)
Change the horizontal alignment and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetHorizSpacingAdjust(float Value)
Change the text horizontal spacing adjustment and signal the primitives to be rebuilt.
UPROPERTY() uint32 bAlwaysRenderAsText UFUNCTION () 1 void SetText(const FText &Value)
Allows text to draw unmodified when using debug visualization modes.
UFUNCTION () 1 void SetTextMaterial(UMaterialInterface *Material)
Change the text material and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetTextRenderColor(FColor Value)
Change the text render color and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetVerticalAlignment(EVerticalTextAligment Value)
Change the vertical alignment and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetVertSpacingAdjust(float Value)
Change the text vertical spacing adjustment and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetWorldSize(float Value)
Change the world size of the text and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetXScale(float Value)
Change the text X scale and signal the primitives to be rebuilt.
UFUNCTION () 1 void SetYScale(float Value)
Change the text Y scale and signal the primitives to be rebuilt.
UFUNCTION ()) 1 void K2_SetText(const FText &Value)
Change the text value and signal the primitives to be rebuilt.
virtual void UpdateBounds () override
UPROPERTY () FColor TextRenderColor
Color of the text, can be accessed as vertex color.
UPROPERTY () float HorizSpacingAdjust
Horizontal adjustment per character, default is 0.0.
UPROPERTY () float InvDefaultSize
The inverse of the Font's character height.
UPROPERTY () float VertSpacingAdjust
Vertical adjustment per character, default is 0.0.
UPROPERTY () float WorldSize
Vertical size of the fonts largest character in world units.
UPROPERTY () float XScale
Horizontal scale, default is 1.0.
UPROPERTY () float YScale
Vertical scale, default is 1.0.
UPROPERTY () TObjectPtr< class UFont > Font
Text font.
UPROPERTY () TObjectPtr< class UMaterialInterface > TextMaterial
Text material.
UPROPERTY ()) TEnumAsByte< enum EHorizTextAligment > HorizontalAlignment
Horizontal text alignment.
UPROPERTY ()) TEnumAsByte< enum EVerticalTextAligment > VerticalAlignment
Vertical text alignment.
Static Private Member Functions
static void InitializeMIDCache ()
static void ShutdownMIDCache ()
Detailed Description
Definition at line 44 of file TextRenderComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UTextRenderComponent::CalcBounds (const FTransform & LocalToWorld) const override private virtual
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UTextRenderComponent::CreateSceneProxy () override private virtual
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GENERATED_UCLASS_BODY()
UTextRenderComponent::GENERATED_UCLASS_BODY () private
Text content, can be multi line using
as line separator.
References Category, meta, Text, and UPROPERTY().
GetMaterial()
virtual UMaterialInterface * UTextRenderComponent::GetMaterial (int32 ElementIndex) const override private virtual
References GetMaterial().
Referenced by GetMaterial().
GetMaterialPropertyPath()
virtual bool UTextRenderComponent::GetMaterialPropertyPath (int32 ElementIndex, UObject *& OutOwner, FString & OutPropertyPath, FProperty *& OutProperty) override private virtual
GetNumMaterials()
virtual int32 UTextRenderComponent::GetNumMaterials () const override private virtual
References GetNumMaterials().
Referenced by GetNumMaterials().
GetRenderMatrix()
virtual FMatrix UTextRenderComponent::GetRenderMatrix () const override private virtual
References GetRenderMatrix().
Referenced by GetRenderMatrix().
GetUsedMaterials()
virtual void UTextRenderComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override private virtual
References GetUsedMaterials().
Referenced by GetUsedMaterials().
InitializeMIDCache()
void UTextRenderComponent::InitializeMIDCache () static private
PostLoad()
virtual void UTextRenderComponent::PostLoad () override private virtual
PrecachePSOs()
virtual void UTextRenderComponent::PrecachePSOs () override private virtual
RequiresGameThreadEndOfFrameUpdates()
virtual bool UTextRenderComponent::RequiresGameThreadEndOfFrameUpdates () const override private virtual
SetMaterial()
virtual void UTextRenderComponent::SetMaterial (int32 ElementIndex, UMaterialInterface * InMaterial) override private virtual
References SetMaterial().
Referenced by SetMaterial().
ShouldRecreateProxyOnUpdateTransform()
virtual bool UTextRenderComponent::ShouldRecreateProxyOnUpdateTransform () const override private virtual
References ShouldRecreateProxyOnUpdateTransform().
Referenced by ShouldRecreateProxyOnUpdateTransform().
ShutdownMIDCache()
void UTextRenderComponent::ShutdownMIDCache () static private
UFUNCTION() [1/14]
UTextRenderComponent::UFUNCTION () const private
Get local size of text.
References Category, FVector, and UFUNCTION().
UFUNCTION() [2/14]
UTextRenderComponent::UFUNCTION () const private
Get world space size of text.
References Category, FVector, and UFUNCTION().
UFUNCTION() [3/14]
UTextRenderComponent::UFUNCTION () private
Change the font and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [4/14]
UTextRenderComponent::UFUNCTION () private
Change the horizontal alignment and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [5/14]
UTextRenderComponent::UFUNCTION () private
Change the text horizontal spacing adjustment and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [6/14]
UPROPERTY() uint32 bAlwaysRenderAsText UTextRenderComponent::UFUNCTION () const & private
Allows text to draw unmodified when using debug visualization modes.
Change the text value and signal the primitives to be rebuilt
References UFUNCTION(), and Value.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [7/14]
UTextRenderComponent::UFUNCTION () private
Change the text material and signal the primitives to be rebuilt.
References Category, Material, and UFUNCTION().
UFUNCTION() [8/14]
UTextRenderComponent::UFUNCTION () private
Change the text render color and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [9/14]
UTextRenderComponent::UFUNCTION () private
Change the vertical alignment and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [10/14]
UTextRenderComponent::UFUNCTION () private
Change the text vertical spacing adjustment and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [11/14]
UTextRenderComponent::UFUNCTION () private
Change the world size of the text and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [12/14]
UTextRenderComponent::UFUNCTION () private
Change the text X scale and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [13/14]
UTextRenderComponent::UFUNCTION () private
Change the text Y scale and signal the primitives to be rebuilt.
References Category, UFUNCTION(), and Value.
UFUNCTION() [14/14]
UTextRenderComponent::UFUNCTION () const & private
Change the text value and signal the primitives to be rebuilt.
References Category, meta, UFUNCTION(), and Value.
UpdateBounds()
virtual void UTextRenderComponent::UpdateBounds () override private virtual
UPROPERTY() [1/11]
UTextRenderComponent::UPROPERTY () private
Color of the text, can be accessed as vertex color.
References Category, Text, and UPROPERTY().
UPROPERTY() [2/11]
UTextRenderComponent::UPROPERTY () private
Horizontal adjustment per character, default is 0.0.
References Category, Text, and UPROPERTY().
UPROPERTY() [3/11]
UTextRenderComponent::UPROPERTY () private
The inverse of the Font's character height.
References UPROPERTY().
UPROPERTY() [4/11]
UTextRenderComponent::UPROPERTY () private
Vertical adjustment per character, default is 0.0.
References Category, Text, and UPROPERTY().
UPROPERTY() [5/11]
UTextRenderComponent::UPROPERTY () private
Vertical size of the fonts largest character in world units.
Transform, XScale and YScale will affect final size.
References Category, Text, and UPROPERTY().
UPROPERTY() [6/11]
UTextRenderComponent::UPROPERTY () private
Horizontal scale, default is 1.0.
References Category, Text, and UPROPERTY().
UPROPERTY() [7/11]
UTextRenderComponent::UPROPERTY () private
Vertical scale, default is 1.0.
References Category, Text, and UPROPERTY().
UPROPERTY() [8/11]
UTextRenderComponent::UPROPERTY () private
Text font.
References Category, Text, and UPROPERTY().
UPROPERTY() [9/11]
UTextRenderComponent::UPROPERTY () private
Text material.
References Category, Text, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [10/11]
UTextRenderComponent::UPROPERTY () private
Horizontal text alignment.
References Category, meta, Text, and UPROPERTY().
UPROPERTY() [11/11]
UTextRenderComponent::UPROPERTY () private
Vertical text alignment.
References Category, meta, Text, and UPROPERTY().
The documentation for this class was generated from the following file:
TextRenderComponent.h