Unreal Engine 5.6 C++ API: TBulkData< ElementType > Class Template Reference
TBulkData< ElementType > Class Template Reference
Templated bulk data.
#include "BulkData.h"
Public Member Functions
FBulkDataBuffer< ElementType > GetCopyAsBuffer (int64 RequestedElementCount, bool bDiscardInternalCopy)
Returns a copy encapsulated by a FBulkDataBuffer.
int64 GetElementCount () const
Returns the number of elements in this bulk data array.
int32 GetElementSize () const
Element size in bytes.
ElementType * Realloc (int64 ElementCount)
Change size of locked bulk data.
void Serialize (FArchive &Ar, UObject *Owner, int32 Idx=INDEX_NONE, bool bAttemptFileMapping=false, EFileRegionType FileRegionType=EFileRegionType::None)
Serialize function used to serialize this bulk data structure.
void SerializeWithFlags (FArchive &Ar, UObject *Owner, uint32 SaveOverrideFlags, bool bAttemptFileMapping=false, EFileRegionType FileRegionType=EFileRegionType::None)
Serialize function used to serialize this bulk data structure, applying an override of the Bulk Data Flags when saving.
Public Member Functions inherited from FBulkData
FBulkData ()=default
Constructor, initializing all member variables.
FBulkData (const FBulkData &Other)
Copy constructor.
~FBulkData ()
Virtual destructor, free'ing allocated memory.
bool CanLoadBulkDataWithFileReader () const
Test if it is possible to load the bulk data using a file reader, even when no archive is attached to the bulk data.
bool CanLoadFromDisk () const
Returns true if the data can be loaded from disk.
void ClearBulkDataFlags (uint32 BulkDataFlagsToClear)
Clears the passed in bulk data flags.
FIoChunkId CreateChunkId () const
Returns a FIoChunkId for the bulkdata payload, this will be invalid if the bulkdata is not stored in the IoStore.
IBulkDataIORequest * CreateStreamingRequest (EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack *CompleteCallback, uint8 *UserSuppliedMemory) const
Create an async read request for the bulk data.
IBulkDataIORequest * CreateStreamingRequest (int64 OffsetInBulkData, int64 BytesToRead, EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack *CompleteCallback, uint8 *UserSuppliedMemory) const
Create an async read request for the bulk data.
bool DoesExist () const
Returns true if the data references a file that currently exists and can be referenced by the file system.
void ForceBulkDataResident ()
Forces the bulk data to be resident in memory and detaches the archive.
uint32 GetBulkDataAlignment () const
Gets the current bulk data alignment.
uint32 GetBulkDataFlags () const
Gets the current bulk data flags.
int64 GetBulkDataOffsetInFile () const
Returns the offset into the file the bulk data is located at.
int64 GetBulkDataSize () const
Returns the size of the bulk data in bytes.
int64 GetBulkDataSizeOnDisk () const
Returns the size of the bulk data on disk.
void GetBulkDataVersions (FArchive &InlineArchive, FPackageFileVersion &OutUEVersion, int32 &OutLicenseeUEVersion, FCustomVersionContainer &OutCustomVersions) const
Get the CustomVersions used in the file containing the BulkData payload.
void GetCopy (void **Dest, bool bDiscardInternalCopy=true)
Retrieves a copy of the bulk data.
FString GetDebugName () const
Returns a string representing the bulk data for debugging purposes.
FName GetDecompressionFormat () const
Returns flags usable to decompress the bulk data.
FIoFilenameHash GetIoFilenameHash () const
Returns the io filename hash associated with this bulk data.
bool IsBulkDataLoaded () const
Returns whether the bulk data is currently loaded and resident in memory.
bool IsDataMemoryMapped () const
Returns whether this bulk data is memory mapped or not.
bool IsDuplicateNonOptional () const
Returns whether this bulk data represents duplicate non-optional data or not.
bool IsInExternalResource () const
Returns whether this bulk data is stored in a PackageExternalResource rather than in a neighboring segment of its owner's PackagePath.
bool IsInlined () const
Returns whether this bulk data is currently stored inline or not.
bool IsInSeparateFile () const
Returns whether this bulk data is currently stored in it's own file or not.
bool IsLocked () const
Checks if this bulk is locked.
bool IsOptional () const
Returns whether this bulk data represents optional data or not.
bool IsSingleUse () const
Returns whether to deallocate the bulk data after lock.
bool IsStoredCompressedOnDisk () const
Returns whether the bulk data is stored compressed on disk.
bool IsUnlocked () const
Checks if this bulk is unlocked.
bool IsUsingIODispatcher () const
Returns whether this bulk data is accessed via the IoDispatcher or not.
bool LoadBulkDataWithFileReader ()
Load the bulk data using a file reader.
void * Lock (uint32 LockFlags)
Locks the bulk data and returns a pointer to it.
const void * LockReadOnly () const
Locks the bulk data and returns a read-only pointer to it.
IAsyncReadFileHandle * OpenAsyncReadHandle () const
Opens a new IAsyncReadFileHandle that references the file that the BulkData object represents.
FBulkData & operator= (const FBulkData &Other)
Copies the source array into this one after detaching from archive.
void * Realloc (int64 ElementCount, int64 ElementSize)
Change size of locked bulk data.
void RemoveBulkData ()
Clears/removes any currently allocated data payload and resets element count to 0.
void ResetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enable the given flags and disable all other flags.
void Serialize (FArchive &Ar, UObject *Owner, bool bAttemptFileMapping, int32 ElementSize, EFileRegionType FileRegionType)
Serialize function used to serialize this bulk data structure.
void SerializeBulkData (FArchive &Ar, void *Data, EBulkDataFlags InBulkDataFlags)
Serialize just the bulk data portion to/ from the passed in memory.
void SetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enables the given flags without affecting any previously set flags.
void SetCookedIndex (FBulkDataCookedIndex Index)
void SetFlagsFromDiskWrittenValues (EBulkDataFlags InBulkDataFlags, int64 InBulkDataOffsetInFile, int64 InBulkDataSizeOnDisk, int64 LinkerSummaryBulkDataStartOffset)
When saving BulkData, if we are overwriting the file we need to update the BulkData's (flags,offset,size) to be able to load from the new file.
FOwnedBulkDataPtr * StealFileMapping ()
void StoreCompressedOnDisk (FName CompressionFormat)
Sets whether we should store the data compressed on disk.
UE_DEPRECATED (5.3, "The feature is being removed, it is assumed that all bulkdata is available for use") 1 bool IsAvailableForUse() const
Returns whether this bulk data is used.
UE_DEPRECATED (5.5, "No longer provides any functionality (assume that this will always return true") 1 bool IsAsyncLoadingComplete() const
Deprecated.
bool UnloadBulkData ()
Deallocates bulk data without detaching the archive, so that further bulk data accesses require a reload.
void Unlock () const
Unlocks bulk data after which point the pointer returned by Lock no longer is valid.
Additional Inherited Members
Public Types inherited from FBulkData
using BulkDataRangeArray = TArray<FBulkData*, TInlineAllocator<8>>
using FSerializeBulkDataElements = TFunction<void(FArchive&, void*, int64, EBulkDataFlags)>
Static Public Member Functions inherited from FBulkData
static void ClearBulkDataFlagsOn (EBulkDataFlags &InOutAccumulator, EBulkDataFlags FlagsToClear)
Disable the given flags in the given accumulator variable.
static void DumpBulkDataUsage (FOutputDevice &Log)
Dumps detailed information of bulk data usage.
static FName GetDecompressionFormat (EBulkDataFlags InFlags)
Returns decompress method flags specified by the given bulk data flags.
static bool HasFlags (EBulkDataFlags Flags, EBulkDataFlags Contains)
Returns whether all of the specified flags are set.
static void SetBulkDataFlagsOn (EBulkDataFlags &InOutAccumulator, EBulkDataFlags FlagsToSet)
Enable the given flags in the given accumulator variable.
Static Public Attributes inherited from FBulkData
static constexpr SIZE_T MaxBulkDataSize = (1ull << 40) - 1
Protected Member Functions inherited from FBulkData
void SerializeBulkData (FArchive &Ar, void *Data, int64 DataSize, EBulkDataFlags InBulkDataFlags)
Protected Attributes inherited from FBulkData
FArchive * AttachedAr = nullptr
Archive associated with bulk data for serialization.
FBulkDataCookedIndex CookedIndex
The index to which the cooked version of the bulkdata payload should be assigned.
FLinkerLoad * Linker = nullptr
Used to make sure the linker doesn't get garbage collected at runtime for things with attached archives.
FSerializeBulkDataElements * SerializeBulkDataElements = nullptr
Custom bulk data serialization hook when using FUntypedBulkData.
Detailed Description
template<typename ElementType>
class TBulkData< ElementType >
Templated bulk data.
A bulk data array of typed elements.
Definition at line 1034 of file BulkData.h.
Member Function Documentation
GetCopyAsBuffer()
template<typename ElementType> FBulkDataBuffer< ElementType > TBulkData< ElementType >::GetCopyAsBuffer (int64 RequestedElementCount, bool bDiscardInternalCopy) inline
Returns a copy encapsulated by a FBulkDataBuffer.
Parameters
RequestedElementCount If set to greater than 0, the returned FBulkDataBuffer will be limited to this number of elements. This will give an error if larger than the actual number of elements in the BulkData object.
bDiscardInternalCopy If true then the BulkData object will free it's internal buffer once called.
Returns
A FBulkDataBuffer that owns a copy of the BulkData, this might be a subset of the data depending on the value of RequestedSize.
Definition at line 1079 of file BulkData.h.
GetElementCount()
template<typename ElementType> int64 TBulkData< ElementType >::GetElementCount () const inline
Returns the number of elements in this bulk data array.
Returns
Number of elements in this bulk data array
Definition at line 1055 of file BulkData.h.
Referenced by TBulkData< uint8 >::GetCopyAsBuffer().
GetElementSize()
template<typename ElementType> int32 TBulkData< ElementType >::GetElementSize () const inline
Element size in bytes.
Returns
Returns the element size in bytes.
Definition at line 1045 of file BulkData.h.
Referenced by TBulkData< uint8 >::Serialize(), and TBulkData< uint8 >::SerializeWithFlags().
Realloc()
template<typename ElementType> ElementType * TBulkData< ElementType >::Realloc (int64 ElementCount) inline
Change size of locked bulk data.
Only valid if locked via read-write lock.
Parameters
ElementCount Number of elements array should be resized to
Definition at line 1065 of file BulkData.h.
Serialize()
template<typename ElementType> void TBulkData< ElementType >::Serialize (FArchive & Ar, UObject * Owner, int32 Idx = INDEX_NONE, bool bAttemptFileMapping = false, EFileRegionType FileRegionType = EFileRegionType::None) inline
Serialize function used to serialize this bulk data structure.
Parameters
Ar Archive to serialize with
Owner Object owning the bulk data
Idx Index of bulk data item being serialized
bAttemptFileMapping If true, attempt to map this instead of loading it into malloc'ed memory
FileRegionType When cooking, a hint describing the type of data, used by some platforms to improve compression ratios
Definition at line 1102 of file BulkData.h.
SerializeWithFlags()
template<typename ElementType> void TBulkData< ElementType >::SerializeWithFlags (FArchive & Ar, UObject * Owner, uint32 SaveOverrideFlags, bool bAttemptFileMapping = false, EFileRegionType FileRegionType = EFileRegionType::None) inline
Serialize function used to serialize this bulk data structure, applying an override of the Bulk Data Flags when saving.
Parameters
Ar Archive to serialize with
Owner Object owning the bulk data
SaveOverrideFlags EBulkDataFlags to use when saving (restores original flags after serialization)
bAttemptFileMapping If true, attempt to map this instead of loading it into malloc'ed memory
FileRegionType When cooking, a hint describing the type of data, used by some platforms to improve compression ratios
Definition at line 1116 of file BulkData.h.
The documentation for this class was generated from the following file:
BulkData.h