Unreal Engine 5.6 C++ API: UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType > Class Template Reference
UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType > Class Template Reference
Compute discretely-sampled (ie gridded) signed distance field for a mesh within a specified narrow band.
#include "SparseNarrowBandMeshSDF.h"
Data Structures
struct FScatterCounter
struct FTriBBox
struct FTriIDBlockGrid
Public Types
enum EComputeModes { NarrowBandOnly = 1 , NarrowBand_SpatialFloodFill = 2 }
enum EInsideModes { CrossingCount = 0 , WindingCount = 1 }
Public Member Functions
TSparseNarrowBandMeshSDF (const TriangleMeshType *Mesh=nullptr, float CellSize=1.f, TMeshAABBTree3< TriangleMeshType > *Spatial=nullptr)
float At (int32 I, int32 J, int32 K) const
FVector3f CellCenter (int32 I, int32 J, int32 K) const
bool Compute (FAxisAlignedBox3d Bounds)
Compute the SDF.
FVector3i Dimensions () const
const FBlockedGrid3i & GetClosestTriGrid () const
const FBlockedGrid3i & GetIntersectionsGrid () const
float GetValue (const FVector3i &ijk) const
TTriLinearGridInterpolant< TSparseNarrowBandMeshSDF > MakeInterpolant ()
float operator[] (const FVector3i &ijk) const
bool Validate (const FAxisAlignedBox3d &Bounds)
Static Public Member Functions
static bool ShouldUseSpatial (int32 ExactCells, double CellSize, double AvgEdgeLen)
Encodes heuristic for deciding whether it will be faster to use.
Data Fields
int ApproxMaxCellsPerDimension = 4096
bool bComputeSigns = true
bool bUseParallel = true
bool bWantClosestTriGrid = false
bool bWantIntersectionsGrid = true
TFunction< bool()> CancelF
if this function returns true, the calculation will abort
float CellSize
EComputeModes ComputeMode = EComputeModes::NarrowBandOnly
int ExactBandWidth = 1
FVector3d ExpandBounds = FVector3d::Zero()
FBlockedGrid3f Grid
FVector3f GridOrigin
EInsideModes InsideMode = EInsideModes::WindingCount
TUniqueFunction< bool(const FVector3d &)> IsInsideFunction
const TriangleMeshType * Mesh = nullptr
double NarrowBandMaxDistance = 0
TMeshAABBTree3< TriangleMeshType > * Spatial = nullptr
Protected Attributes
FBlockedGrid3i ClosestTriGrid
FBlockedGrid3i IntersectionsGrid
Private Member Functions
FVector3f cell_center (const FVector3i &IJK) const
void CleanupUnwanted ()
void compute_intersections (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, const FBlockedGrid3f &DistanceGrid, FBlockedGrid3i &IntersectionCountGrid)
void compute_signs (int32 NI, int32 NJ, int32 NK, const FBlockedGrid3i &IntersectionCountGrid, FBlockedGrid3f &Distances)
TArray< FTriBBox > compute_tri_bboxes (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, int32 ExactBand)
template<typename FunctorType>
void inclusive_loop_3d (const FVector3i &start, const FVector3i &inclusive_end, FunctorType func)
void make_level_set3_parallel (const FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f &DistanceGrid, int32 ExactBand)
void make_level_set3_parallel_floodfill (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f &DistanceGrid, double NarrowBandWidth)
void make_level_set3_parallel_spatial (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f &DistanceGrid, int32 ExactBand)
FTriIDBlockGrid scatter_tris (const TArray< FTriBBox > &TriBBoxes, int32 NI, int32 NJ, int32 NK)
void update_signs (const FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f &Distances, FBlockedGrid3i &IntersectionCountGrid)
float upper_bound (const FVector3i &GridDimensions, float DX) const
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >
Compute discretely-sampled (ie gridded) signed distance field for a mesh within a specified narrow band.
The basic approach is, first compute exact Distances in a narrow band, and then The resulting unsigned Grid is then signed using ray-intersection counting, which is also computed on the Grid, so no BVH is necessary
The underlying grid data structures are blocked grids where spatial blocks are allocated as needed, so the memory footprint will generally be much lower than the TSweepingMeshSDF, or TCachingMeshSDF. But if distances in the full grid domain are desired (not just a narrow band), then the TSweepingMeshSDF should be used.
You can optionally provide a spatial data structure to allow faster computation of narrow-band Distances; this is most beneficial if we want a wider band
Caveats:
the "narrow band" is based on triangle bounding boxes, so it is not necessarily that "narrow" if you have large triangles on a diagonal to Grid axes
This code is based on the implementation found at https://github.com/christopherbatty/SDFGen
Definition at line 48 of file SparseNarrowBandMeshSDF.h.
Member Enumeration Documentation
EComputeModes
template<class TriangleMeshType> enum UE::Geometry::TSparseNarrowBandMeshSDF::EComputeModes
Enumerator
NarrowBandOnly
NarrowBand_SpatialFloodFill
Definition at line 75 of file SparseNarrowBandMeshSDF.h.
EInsideModes
template<class TriangleMeshType> enum UE::Geometry::TSparseNarrowBandMeshSDF::EInsideModes
Enumerator
CrossingCount
WindingCount
Definition at line 97 of file SparseNarrowBandMeshSDF.h.
Constructor & Destructor Documentation
TSparseNarrowBandMeshSDF()
template<class TriangleMeshType> UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::TSparseNarrowBandMeshSDF (const TriangleMeshType * Mesh = nullptr, float CellSize = 1.f, TMeshAABBTree3< TriangleMeshType > * Spatial = nullptr) inline
Parameters
Mesh Triangle mesh to build an SDF around
CellSize Spacing between Grid points
Spatial Optional AABB tree; note it must be provided if ComputeMode is set to NarrowBand_SpatialFloodFill
Definition at line 250 of file SparseNarrowBandMeshSDF.h.
Member Function Documentation
At()
template<class TriangleMeshType> float UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::At (int32 I, int32 J, int32 K) const inline
Returns
the distance value at the specified grid cell.
Definition at line 388 of file SparseNarrowBandMeshSDF.h.
cell_center()
template<class TriangleMeshType> FVector3f UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::cell_center (const FVector3i & IJK) const inline private
Definition at line 432 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::CellCenter().
CellCenter()
template<class TriangleMeshType> FVector3f UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::CellCenter (int32 I, int32 J, int32 K) const inline
Returns
the physical space location of specified grid point.
Definition at line 406 of file SparseNarrowBandMeshSDF.h.
CleanupUnwanted()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::CleanupUnwanted () inline private
Definition at line 1038 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
Compute()
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Compute (FAxisAlignedBox3d Bounds) inline
Compute the SDF.
Parameters
Bounds Bounding box for the mesh data (passed as param it is usually already available, depending on TriangleMeshType and whether an AABB tree was provided)
Returns
false if cancelled or failed (e.g. due to invalid arguments); true otherwise
Definition at line 301 of file SparseNarrowBandMeshSDF.h.
compute_intersections()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::compute_intersections (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, const FBlockedGrid3f & DistanceGrid, FBlockedGrid3i & IntersectionCountGrid) inline private
Definition at line 1054 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
compute_signs()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::compute_signs (int32 NI, int32 NJ, int32 NK, const FBlockedGrid3i & IntersectionCountGrid, FBlockedGrid3f & Distances) inline private
Definition at line 1204 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
compute_tri_bboxes()
template<class TriangleMeshType> TArray< FTriBBox > UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::compute_tri_bboxes (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, int32 ExactBand) inline private
Definition at line 522 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel().
Dimensions()
template<class TriangleMeshType> FVector3i UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Dimensions () const inline
Returns
the number of cells in each direction
Definition at line 368 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::MakeInterpolant().
GetClosestTriGrid()
template<class TriangleMeshType> const FBlockedGrid3i & UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::GetClosestTriGrid () const inline
Returns
a grid that can be sampled within the narrow band to find the ID of the closest triangle. Note: this is populated during Compute()
Definition at line 374 of file SparseNarrowBandMeshSDF.h.
GetIntersectionsGrid()
template<class TriangleMeshType> const FBlockedGrid3i & UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::GetIntersectionsGrid () const inline
Returns
a grid that can be sampled within the narrow band to find cells that actually contain mesh triangles. Note: this is populated during Compute()
Definition at line 381 of file SparseNarrowBandMeshSDF.h.
GetValue()
template<class TriangleMeshType> float UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::GetValue (const FVector3i & ijk) const inline
Returns
the distance value at the specified grid cell.
Definition at line 400 of file SparseNarrowBandMeshSDF.h.
inclusive_loop_3d()
template<class TriangleMeshType> template<typename FunctorType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::inclusive_loop_3d (const FVector3i & start, const FVector3i & inclusive_end, FunctorType func) inline private
Definition at line 417 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::scatter_tris().
make_level_set3_parallel()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::make_level_set3_parallel (const FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f & DistanceGrid, int32 ExactBand) inline private
Definition at line 645 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
make_level_set3_parallel_floodfill()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::make_level_set3_parallel_floodfill (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f & DistanceGrid, double NarrowBandWidth) inline private
Definition at line 836 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
make_level_set3_parallel_spatial()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::make_level_set3_parallel_spatial (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f & DistanceGrid, int32 ExactBand) inline private
Definition at line 735 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
MakeInterpolant()
template<class TriangleMeshType> TTriLinearGridInterpolant< TSparseNarrowBandMeshSDF > UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::MakeInterpolant () inline
Definition at line 258 of file SparseNarrowBandMeshSDF.h.
operator[]()
template<class TriangleMeshType> float UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::operator[] (const FVector3i & ijk) const inline
Returns
the distance value at the specified grid cell.
Definition at line 394 of file SparseNarrowBandMeshSDF.h.
scatter_tris()
template<class TriangleMeshType> FTriIDBlockGrid UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::scatter_tris (const TArray< FTriBBox > & TriBBoxes, int32 NI, int32 NJ, int32 NK) inline private
Definition at line 563 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel().
ShouldUseSpatial()
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ShouldUseSpatial (int32 ExactCells, double CellSize, double AvgEdgeLen) inline static
Encodes heuristic for deciding whether it will be faster to use.
NarrowBand_SpatialFloodFill
Or NarrowBandOnly The heuristic is to use the Spatial method unless you have relatively long edges relative to the width of the narrow band. For a 1-cell wide band, or one where few triangles interact w/ each cell in the band the spatial overhead will probably not be worthwhile. TODO: test and tune this ...
Definition at line 272 of file SparseNarrowBandMeshSDF.h.
update_signs()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::update_signs (const FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FBlockedGrid3f & Distances, FBlockedGrid3i & IntersectionCountGrid) inline private
Definition at line 445 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
upper_bound()
template<class TriangleMeshType> float UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::upper_bound (const FVector3i & GridDimensions, float DX) const inline private
Definition at line 439 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel().
Validate()
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Validate (const FAxisAlignedBox3d & Bounds) inline
Definition at line 279 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute().
Field Documentation
ApproxMaxCellsPerDimension
template<class TriangleMeshType> int UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ApproxMaxCellsPerDimension = 4096
Definition at line 72 of file SparseNarrowBandMeshSDF.h.
bComputeSigns
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::bComputeSigns = true
Definition at line 89 of file SparseNarrowBandMeshSDF.h.
bUseParallel
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::bUseParallel = true
Definition at line 69 of file SparseNarrowBandMeshSDF.h.
bWantClosestTriGrid
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::bWantClosestTriGrid = false
Definition at line 106 of file SparseNarrowBandMeshSDF.h.
bWantIntersectionsGrid
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::bWantIntersectionsGrid = true
Definition at line 109 of file SparseNarrowBandMeshSDF.h.
CancelF
template<class TriangleMeshType> TFunction<bool()> UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::CancelF
Initial value:
= []()
    {
        return false;
    }
if this function returns true, the calculation will abort
Definition at line 112 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::scatter_tris(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
CellSize
template<class TriangleMeshType> float UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::CellSize
Definition at line 58 of file SparseNarrowBandMeshSDF.h.
ClosestTriGrid
template<class TriangleMeshType> FBlockedGrid3i UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ClosestTriGrid protected
Definition at line 124 of file SparseNarrowBandMeshSDF.h.
ComputeMode
template<class TriangleMeshType> EComputeModes UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ComputeMode = EComputeModes::NarrowBandOnly
Definition at line 80 of file SparseNarrowBandMeshSDF.h.
ExactBandWidth
template<class TriangleMeshType> int UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ExactBandWidth = 1
Definition at line 62 of file SparseNarrowBandMeshSDF.h.
ExpandBounds
template<class TriangleMeshType> FVector3d UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::ExpandBounds = FVector3d::Zero()
Definition at line 66 of file SparseNarrowBandMeshSDF.h.
Grid
template<class TriangleMeshType> FBlockedGrid3f UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Grid
Definition at line 120 of file SparseNarrowBandMeshSDF.h.
GridOrigin
template<class TriangleMeshType> FVector3f UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::GridOrigin
Definition at line 119 of file SparseNarrowBandMeshSDF.h.
InsideMode
template<class TriangleMeshType> EInsideModes UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::InsideMode = EInsideModes::WindingCount
Definition at line 102 of file SparseNarrowBandMeshSDF.h.
IntersectionsGrid
template<class TriangleMeshType> FBlockedGrid3i UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::IntersectionsGrid protected
Definition at line 126 of file SparseNarrowBandMeshSDF.h.
IsInsideFunction
template<class TriangleMeshType> TUniqueFunction<bool(const FVector3d&)> UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::IsInsideFunction
Definition at line 55 of file SparseNarrowBandMeshSDF.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
Mesh
template<class TriangleMeshType> const TriangleMeshType* UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Mesh = nullptr
Definition at line 53 of file SparseNarrowBandMeshSDF.h.
NarrowBandMaxDistance
template<class TriangleMeshType> double UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::NarrowBandMaxDistance = 0
Definition at line 86 of file SparseNarrowBandMeshSDF.h.
Spatial
template<class TriangleMeshType> TMeshAABBTree3<TriangleMeshType>* UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::Spatial = nullptr
Definition at line 54 of file SparseNarrowBandMeshSDF.h.
The documentation for this class was generated from the following file:
SparseNarrowBandMeshSDF.h