Unreal Engine 5.6 C++ API: FFontFaceData Struct Reference
FFontFaceData Struct Reference
Raw font data for a Font Face asset.
#include "CompositeFont.h"
Public Member Functions
FFontFaceData ()
Default constructor.
FFontFaceData (TArray< uint8 > &&InData)
Construct from an existing block of font data.
~FFontFaceData ()
Destructor.
SIZE_T GetAllocatedSize () const
const TArray< uint8 > & GetData () const
TArrayView< const UE::Slate::FPreprocessedFontGeometry > GetPreprocessedFontGeometries () const
bool HasData () const
void Serialize (FArchive &Ar)
Serialize the data on this instance to/from an archive.
void SetData (TArray< uint8 > &&InData)
Set from an existing block of font data.
void SetPreprocessedFontGeometries (TArray< UE::Slate::FPreprocessedFontGeometry > &&InPreprocessedFontGeometries)
Set the preprocessed font geometry data per sub-face for the given font data.
Static Public Member Functions
static FFontFaceDataRef MakeFontFaceData ()
Helper function to construct a default font face data.
static FFontFaceDataRef MakeFontFaceData (TArray< uint8 > &&InData)
Helper function to construct a font face data from an existing block of font data.
Private Member Functions
void TrackMemoryUsage () const
Memory stat tracking.
void UntrackMemoryUsage () const
Private Attributes
TArray< uint8 > Data
Internal data.
TArray< UE::Slate::FPreprocessedFontGeometry > PreprocessedFontGeometries
Preprocessed font geometry data per font sub-face.
Detailed Description
Raw font data for a Font Face asset.
Note
Exists as a struct so it can be shared between its owner asset and the font cache without worrying about UObject lifetimes.
Definition at line 67 of file CompositeFont.h.
Constructor & Destructor Documentation
FFontFaceData() [1/2]
FFontFaceData::FFontFaceData ()
Default constructor.
FFontFaceData() [2/2]
FFontFaceData::FFontFaceData (TArray< uint8 > && InData)
Construct from an existing block of font data.
~FFontFaceData()
FFontFaceData::~FFontFaceData ()
Destructor.
Member Function Documentation
GetAllocatedSize()
SIZE_T FFontFaceData::GetAllocatedSize () const
Returns
the memory size of the raw font data and the associated preprocessed data
GetData()
const TArray< uint8 > & FFontFaceData::GetData () const inline
Returns
The data set on this instance
Definition at line 92 of file CompositeFont.h.
References Data.
GetPreprocessedFontGeometries()
TArrayView< const UE::Slate::FPreprocessedFontGeometry > FFontFaceData::GetPreprocessedFontGeometries () const inline
Returns
The preprocessed font geometry per sub-face of the font represented by Data
Definition at line 98 of file CompositeFont.h.
References PreprocessedFontGeometries.
HasData()
bool FFontFaceData::HasData () const inline
Returns
true if this instance has data set on it
Definition at line 80 of file CompositeFont.h.
References Data.
MakeFontFaceData() [1/2]
FFontFaceDataRef FFontFaceData::MakeFontFaceData () inline static
Helper function to construct a default font face data.
Definition at line 110 of file CompositeFont.h.
References MakeShared().
MakeFontFaceData() [2/2]
FFontFaceDataRef FFontFaceData::MakeFontFaceData (TArray< uint8 > && InData) inline static
Helper function to construct a font face data from an existing block of font data.
Definition at line 116 of file CompositeFont.h.
References MakeShared(), and MoveTemp().
Serialize()
void FFontFaceData::Serialize (FArchive & Ar)
Serialize the data on this instance to/from an archive.
References Ar.
SetData()
void FFontFaceData::SetData (TArray< uint8 > && InData)
Set from an existing block of font data.
SetPreprocessedFontGeometries()
void FFontFaceData::SetPreprocessedFontGeometries (TArray< UE::Slate::FPreprocessedFontGeometry > && InPreprocessedFontGeometries)
Set the preprocessed font geometry data per sub-face for the given font data.
TrackMemoryUsage()
void FFontFaceData::TrackMemoryUsage () const private
Memory stat tracking.
UntrackMemoryUsage()
void FFontFaceData::UntrackMemoryUsage () const private
Field Documentation
Data
TArray<uint8> FFontFaceData::Data private
Internal data.
Definition at line 127 of file CompositeFont.h.
Referenced by GetData(), and HasData().
PreprocessedFontGeometries
TArray<UE::Slate::FPreprocessedFontGeometry> FFontFaceData::PreprocessedFontGeometries private
Preprocessed font geometry data per font sub-face.
Definition at line 130 of file CompositeFont.h.
Referenced by GetPreprocessedFontGeometries().
The documentation for this struct was generated from the following file:
CompositeFont.h