Unreal Engine 5.6 C++ API: IMetaSoundDocumentInterface Class Reference
IMetaSoundDocumentInterface Class Reference abstract
#include "MetasoundDocumentInterface.h"
Private Member Functions
virtual bool ConformObjectToDocument ()=0
virtual const UClass & GetBaseMetaSoundUClass () const =0
virtual const UClass & GetBuilderUClass () const =0
virtual const FMetasoundFrontendDocument & GetConstDocument () const =0
virtual FMetasoundFrontendDocument & GetDocument ()=0
virtual bool IsActivelyBuilding () const =0
virtual void OnBeginActiveBuilder ()=0
virtual void OnFinishActiveBuilder ()=0
GENERATED_BODY() public UE_DEPRECATED (5.4, "Use GetConstDocument instead") virtual const FMetasoundFrontendDocument &GetDocument() const
Friends
struct FMetaSoundFrontendDocumentBuilder
Additional Inherited Members
Public Types inherited from IInterface
typedef UInterface UClassType
Protected Member Functions inherited from IInterface
virtual ~IInterface ()
Detailed Description
Definition at line 31 of file MetasoundDocumentInterface.h.
Member Function Documentation
ConformObjectToDocument()
virtual bool IMetaSoundDocumentInterface::ConformObjectToDocument () private pure virtual
GetBaseMetaSoundUClass()
virtual const UClass & IMetaSoundDocumentInterface::GetBaseMetaSoundUClass () const private pure virtual
GetBuilderUClass()
virtual const UClass & IMetaSoundDocumentInterface::GetBuilderUClass () const private pure virtual
GetConstDocument()
virtual const FMetasoundFrontendDocument & IMetaSoundDocumentInterface::GetConstDocument () const private pure virtual
Referenced by UE_DEPRECATED().
GetDocument()
virtual FMetasoundFrontendDocument & IMetaSoundDocumentInterface::GetDocument () private pure virtual
Referenced by UE_DEPRECATED().
IsActivelyBuilding()
virtual bool IMetaSoundDocumentInterface::IsActivelyBuilding () const private pure virtual
OnBeginActiveBuilder()
virtual void IMetaSoundDocumentInterface::OnBeginActiveBuilder () private pure virtual
OnFinishActiveBuilder()
virtual void IMetaSoundDocumentInterface::OnFinishActiveBuilder () private pure virtual
UE_DEPRECATED()
GENERATED_BODY() public IMetaSoundDocumentInterface::UE_DEPRECATED (5. 4, "Use GetConstDocument instead") const & inline private
Definition at line 40 of file MetasoundDocumentInterface.h.
References GetConstDocument(), and GetDocument().
Friends And Related Symbol Documentation
FMetaSoundFrontendDocumentBuilder
friend struct FMetaSoundFrontendDocumentBuilder friend
Definition at line 72 of file MetasoundDocumentInterface.h.
References FMetaSoundFrontendDocumentBuilder.
Referenced by FMetaSoundFrontendDocumentBuilder.
The documentation for this class was generated from the following file:
MetasoundDocumentInterface.h