Unreal Engine 5.6 C++ API: FCookStats::CallStats Struct Reference
FCookStats::CallStats Struct Reference
Struct to hold stats for a call.
#include "CookStats.h"
Data Structures
struct GameAndOtherThreadAccumulator
Contains a pair of accumulators, one for the game thread, one for the other threads.
Public Types
enum class EHitOrMiss : uint8 { Hit , Miss , MaxValue }
One group of accumulators for hits and misses.
enum class EStatType : uint8 { Counter , Cycles , Bytes , MaxValue }
Each hit or miss will contain these accumulator stats.
Public Member Functions
void Accumulate (EHitOrMiss HitOrMiss, EStatType StatType, int64 Value, bool bIsInGameThread)
Make it easier to update an accumulator by providing strongly typed access to the 2D array.
void Combine (const CallStats &Other)
int64 GetAccumulatedValue (EHitOrMiss HitOrMiss, EStatType StatType, bool bIsInGameThread) const
Make it easier to access an accumulator using a uniform, stronly typed interface.
int64 GetAccumulatedValueAnyThread (EHitOrMiss HitOrMiss, EStatType StatType) const
Make it easier to access an accumulator using a uniform, stronly typed interface.
void LogStats (FCookStatsManager::AddStatFuncRef AddStat, const FString &StatName, const FString &NodeName, const TCHAR *CallName) const
Used to log the instance in a common way.
Private Attributes
GameAndOtherThreadAccumulator Accumulators [(uint8) EHitOrMiss::MaxValue][(uint8) EStatType::MaxValue]
The actual accumulators.
Detailed Description
Struct to hold stats for a call.
The sub-structs and stuff look intimidating, but it is to unify the concept of accumulating any stat on the game or other thread, using raw int64 on the main thread, and thread safe accumulators on other threads.
Each call type that will be tracked will track call counts, call cycles, and bytes processed, grouped by hits and misses. Some stats will by definition be zero but it limits the branching in the tracking code.
Definition at line 182 of file CookStats.h.
Member Enumeration Documentation
EHitOrMiss
enum class FCookStats::CallStats::EHitOrMiss : uint8 strong
One group of accumulators for hits and misses.
Enumerator
Hit
Miss
MaxValue
Definition at line 185 of file CookStats.h.
EStatType
enum class FCookStats::CallStats::EStatType : uint8 strong
Each hit or miss will contain these accumulator stats.
Enumerator
Counter
Cycles
Bytes
MaxValue
Definition at line 193 of file CookStats.h.
Member Function Documentation
Accumulate()
void FCookStats::CallStats::Accumulate (EHitOrMiss HitOrMiss, EStatType StatType, int64 Value, bool bIsInGameThread) inline
Make it easier to update an accumulator by providing strongly typed access to the 2D array.
Definition at line 227 of file CookStats.h.
References Accumulators, StatType, and Value.
Referenced by Combine().
Combine()
void FCookStats::CallStats::Combine (const CallStats & Other) inline
Definition at line 274 of file CookStats.h.
References Accumulate(), MaxValue, Other, StatType, and Value.
GetAccumulatedValue()
int64 FCookStats::CallStats::GetAccumulatedValue (EHitOrMiss HitOrMiss, EStatType StatType, bool bIsInGameThread) const inline
Make it easier to access an accumulator using a uniform, stronly typed interface.
Definition at line 233 of file CookStats.h.
References Accumulators, and StatType.
Referenced by GetAccumulatedValueAnyThread(), and LogStats().
GetAccumulatedValueAnyThread()
int64 FCookStats::CallStats::GetAccumulatedValueAnyThread (EHitOrMiss HitOrMiss, EStatType StatType) const inline
Make it easier to access an accumulator using a uniform, stronly typed interface.
Definition at line 239 of file CookStats.h.
References GetAccumulatedValue(), and StatType.
LogStats()
void FCookStats::CallStats::LogStats (FCookStatsManager::AddStatFuncRef AddStat, const FString & StatName, const FString & NodeName, const TCHAR * CallName) const inline
Used to log the instance in a common way.
Definition at line 245 of file CookStats.h.
References Bytes, Counter, FCookStatsManager::CreateKeyValueArray(), Cycles, GetAccumulatedValue(), FGenericPlatformTime::GetSecondsPerCycle(), Hit, Miss, and TEXT.
Field Documentation
Accumulators
GameAndOtherThreadAccumulator FCookStats::CallStats::Accumulators[(uint8) EHitOrMiss::MaxValue][(uint8) EStatType::MaxValue] private
The actual accumulators.
All access should be from the above public functions.
Definition at line 291 of file CookStats.h.
Referenced by Accumulate(), and GetAccumulatedValue().
The documentation for this struct was generated from the following file:
CookStats.h