Unreal Engine 5.6 C++ API: UE::Geometry::FIndexFlagSet Class Reference
UE::Geometry::FIndexFlagSet Class Reference
This class provides optionally sparse or dense boolean flags for a set of integer indices.
#include "SparseIndexCollectionTypes.h"
Public Member Functions
FIndexFlagSet (bool bSetSparse=true, int MaxIndex=-1)
FIndexFlagSet (int MaxIndex, int SubsetCountEst)
FORCEINLINE void Add (int Index)
FORCEINLINE bool Contains (int Index) const
FORCEINLINE int Count () const
Returns number of values in set.
void InitAuto (int MaxIndex, int SubsetCountEst)
Initialize to either sparse or dense automatically, based on max index and estimated number of set indices.
void InitManual (bool bSetSparse, int MaxIndex=-1)
Initialize to sparse or dense based on the explicit caller choice.
const bool operator[] (unsigned int Index) const
Array-style accessor that returns true if Index is in set, false otherwise.
FORCEINLINE void Remove (int Index)
Private Attributes
TOptional< TArray< bool > > Dense
int DenseCount
TOptional< TSet< int > > Sparse
Detailed Description
This class provides optionally sparse or dense boolean flags for a set of integer indices.
Definition at line 20 of file SparseIndexCollectionTypes.h.
Constructor & Destructor Documentation
FIndexFlagSet() [1/2]
UE::Geometry::FIndexFlagSet::FIndexFlagSet (bool bSetSparse = true, int MaxIndex = -1) inline
Definition at line 28 of file SparseIndexCollectionTypes.h.
References InitManual().
FIndexFlagSet() [2/2]
UE::Geometry::FIndexFlagSet::FIndexFlagSet (int MaxIndex, int SubsetCountEst) inline
Definition at line 33 of file SparseIndexCollectionTypes.h.
References InitAuto().
Member Function Documentation
Add()
FORCEINLINE void UE::Geometry::FIndexFlagSet::Add (int Index) inline
Parameters
Index index to add to set
Definition at line 89 of file SparseIndexCollectionTypes.h.
References check, Dense, DenseCount, FORCEINLINE, Sparse, and Value.
Referenced by UE::Geometry::FDynamicSubmesh3::ComputeBoundaryInfo().
Contains()
FORCEINLINE bool UE::Geometry::FIndexFlagSet::Contains (int Index) const inline
Parameters
Index index to check for set membership
Returns
true if Index is in set
Definition at line 73 of file SparseIndexCollectionTypes.h.
References check, Dense, FORCEINLINE, and Sparse.
Referenced by operator[]().
Count()
FORCEINLINE int UE::Geometry::FIndexFlagSet::Count () const inline
Returns number of values in set.
Definition at line 131 of file SparseIndexCollectionTypes.h.
References Dense, DenseCount, FORCEINLINE, and Sparse.
InitAuto()
void UE::Geometry::FIndexFlagSet::InitAuto (int MaxIndex, int SubsetCountEst) inline
Initialize to either sparse or dense automatically, based on max index and estimated number of set indices.
Definition at line 41 of file SparseIndexCollectionTypes.h.
References InitManual().
Referenced by FIndexFlagSet().
InitManual()
void UE::Geometry::FIndexFlagSet::InitManual (bool bSetSparse, int MaxIndex = -1) inline
Initialize to sparse or dense based on the explicit caller choice.
Parameters
bSetSparse if true, will use sparse storage; otherwise will use dense
MaxIndex maximum valid index in set; must be non-negative for dense case
Definition at line 54 of file SparseIndexCollectionTypes.h.
References check, Dense, DenseCount, FMath::Max, and Sparse.
Referenced by FIndexFlagSet(), and InitAuto().
operator[]()
const bool UE::Geometry::FIndexFlagSet::operator[] (unsigned int Index) const inline
Array-style accessor that returns true if Index is in set, false otherwise.
Definition at line 146 of file SparseIndexCollectionTypes.h.
References Contains().
Remove()
FORCEINLINE void UE::Geometry::FIndexFlagSet::Remove (int Index) inline
Parameters
Index index to remove from set
Definition at line 110 of file SparseIndexCollectionTypes.h.
References check, Dense, DenseCount, FORCEINLINE, Sparse, and Value.
Field Documentation
Dense
TOptional<TArray<bool> > UE::Geometry::FIndexFlagSet::Dense private
Definition at line 23 of file SparseIndexCollectionTypes.h.
Referenced by Add(), Contains(), Count(), InitManual(), and Remove().
DenseCount
int UE::Geometry::FIndexFlagSet::DenseCount private
Definition at line 24 of file SparseIndexCollectionTypes.h.
Referenced by Add(), Count(), InitManual(), and Remove().
Sparse
TOptional<TSet<int> > UE::Geometry::FIndexFlagSet::Sparse private
Definition at line 25 of file SparseIndexCollectionTypes.h.
Referenced by Add(), Contains(), Count(), InitManual(), and Remove().
The documentation for this class was generated from the following file:
SparseIndexCollectionTypes.h