Unreal Engine 5.6 C++ API: FArrangedChildren Class Reference
FArrangedChildren Class Reference
The results of an ArrangeChildren are always returned as an FArrangedChildren.
#include "ArrangedChildren.h"
Public Types
typedef TArray< FArrangedWidget, TInlineAllocator< 4 > > FArrangedWidgetArray
Public Member Functions
FArrangedChildren (EVisibility InVisibilityFilter, bool bInAllow3DWidgets=false)
Construct a new container for arranged children that only accepts children that match the VisibilityFilter.
FORCEINLINE_DEBUGGABLE bool Accepts (EVisibility InVisibility) const
void AddWidget (const FArrangedWidget &InWidgetGeometry)
Add an arranged widget (i.e.
FORCEINLINE_DEBUGGABLE void AddWidget (EVisibility VisibilityOverride, const FArrangedWidget &InWidgetGeometry)
Add an arranged widget (i.e.
FORCEINLINE_DEBUGGABLE bool Allows3DWidgets () const
FORCEINLINE void Append (const FArrangedChildren &Source)
FORCEINLINE void Empty ()
FORCEINLINE int32 FindItemIndex (const FArrangedWidget &ItemToFind) const
template<typename PredicateType>
FORCEINLINE int32 FindLastByPredicate (const PredicateType &Pred) const
FORCEINLINE_DEBUGGABLE EVisibility GetFilter () const
FORCEINLINE FArrangedWidgetArray & GetInternalArray ()
FORCEINLINE const FArrangedWidgetArray & GetInternalArray () const
template<typename PredicateType>
FORCEINLINE int32 IndexOfByPredicate (const PredicateType &Pred) const
void InsertWidget (const FArrangedWidget &InWidgetGeometry, int32 Index)
FORCEINLINE_DEBUGGABLE void InsertWidget (EVisibility VisibilityOverride, const FArrangedWidget &InWidgetGeometry, int32 Index)
FORCEINLINE bool IsValidIndex (int32 Index)
FORCEINLINE FArrangedWidget & Last ()
FORCEINLINE const FArrangedWidget & Last () const
FORCEINLINE int32 Num () const
FORCEINLINE FArrangedWidget & operator[] (int32 Index)
FORCEINLINE const FArrangedWidget & operator[] (int32 Index) const
FORCEINLINE void Remove (int32 Index, int32 Count=1)
FORCEINLINE_DEBUGGABLE void Reserve (FArrangedWidgetArray::SizeType Number)
Reserves sufficient memory for the given number of arranged widgets.
void Reverse ()
Reverse the order of the arranged children.
FORCEINLINE_DEBUGGABLE void SetFilter (EVisibility InVisibility)
Static Public Member Functions
static FArrangedChildren Hittest2_FromArray (const TArrayView< FWidgetAndPointer > InWidgets)
Private Attributes
FArrangedWidgetArray Array
Internal representation of the array widgets.
bool bAllow3DWidgets
EVisibility VisibilityFilter
Detailed Description
The results of an ArrangeChildren are always returned as an FArrangedChildren.
FArrangedChildren supports a filter that is useful for excluding widgets with unwanted visibilities.
Definition at line 14 of file ArrangedChildren.h.
Member Typedef Documentation
FArrangedWidgetArray
typedef TArray<FArrangedWidget, TInlineAllocator<4> > FArrangedChildren::FArrangedWidgetArray
Definition at line 22 of file ArrangedChildren.h.
Constructor & Destructor Documentation
FArrangedChildren()
FArrangedChildren::FArrangedChildren (EVisibility InVisibilityFilter, bool bInAllow3DWidgets = false) inline
Construct a new container for arranged children that only accepts children that match the VisibilityFilter.
e.g. FArrangedChildren ArrangedChildren(VIS_All); // Children will be included regardless of visibility FArrangedChildren ArrangedChildren(EVisibility::Visible); // Only visible children will be included FArrangedChildren ArrangedChildren(EVisibility::Collapsed | EVisibility::Hidden); // Only hidden and collapsed children will be included.
Definition at line 31 of file ArrangedChildren.h.
References bAllow3DWidgets, and VisibilityFilter.
Referenced by Append(), and Hittest2_FromArray().
Member Function Documentation
Accepts()
FORCEINLINE_DEBUGGABLE bool FArrangedChildren::Accepts (EVisibility InVisibility) const inline
Definition at line 106 of file ArrangedChildren.h.
References EVisibility::DoesVisibilityPassFilter(), FORCEINLINE_DEBUGGABLE, and VisibilityFilter.
Referenced by AddWidget(), ArrangeSingleChild(), ArrangeSingleChild(), InsertWidget(), and SNodePanel::SNode::OnArrangeChildren().
AddWidget() [1/2]
void FArrangedChildren::AddWidget (const FArrangedWidget & InWidgetGeometry)
Add an arranged widget (i.e.
widget and its resulting geometry) to the list of Arranged children based on the the visibility filter and the arranged widget's visibility
AddWidget() [2/2]
FORCEINLINE_DEBUGGABLE void FArrangedChildren::AddWidget (EVisibility VisibilityOverride, const FArrangedWidget & InWidgetGeometry) inline
Add an arranged widget (i.e.
widget and its resulting geometry) to the list of Arranged children.
Parameters
VisibilityOverride The arrange function may override the visibility of the widget for the purposes of layout or performance (i.e. prevent redundant call to Widget->GetVisibility())
InWidgetGeometry The arranged widget (i.e. widget and its geometry)
Definition at line 66 of file ArrangedChildren.h.
References Accepts(), Array, and FORCEINLINE_DEBUGGABLE.
Referenced by ArrangeChildrenInStack(), ArrangeSingleChild(), ArrangeSingleChild(), and SNodePanel::SNode::OnArrangeChildren().
Allows3DWidgets()
FORCEINLINE_DEBUGGABLE bool FArrangedChildren::Allows3DWidgets () const inline
Definition at line 111 of file ArrangedChildren.h.
References bAllow3DWidgets, and FORCEINLINE_DEBUGGABLE.
Append()
FORCEINLINE void FArrangedChildren::Append (const FArrangedChildren & Source) inline
Definition at line 185 of file ArrangedChildren.h.
References FArrangedChildren(), Array, FORCEINLINE, and Source.
Empty()
FORCEINLINE void FArrangedChildren::Empty () inline
Definition at line 190 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
FindItemIndex()
FORCEINLINE int32 FArrangedChildren::FindItemIndex (const FArrangedWidget & ItemToFind) const inline
Definition at line 163 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
FindLastByPredicate()
template<typename PredicateType> FORCEINLINE int32 FArrangedChildren::FindLastByPredicate (const PredicateType & Pred) const inline
Definition at line 175 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
GetFilter()
FORCEINLINE_DEBUGGABLE EVisibility FArrangedChildren::GetFilter () const inline
Definition at line 101 of file ArrangedChildren.h.
References FORCEINLINE_DEBUGGABLE, and VisibilityFilter.
GetInternalArray() [1/2]
FORCEINLINE FArrangedWidgetArray & FArrangedChildren::GetInternalArray () inline
Definition at line 128 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
GetInternalArray() [2/2]
FORCEINLINE const FArrangedWidgetArray & FArrangedChildren::GetInternalArray () const inline
Definition at line 133 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Hittest2_FromArray()
FArrangedChildren FArrangedChildren::Hittest2_FromArray (const TArrayView< FWidgetAndPointer > InWidgets) inline static
Definition at line 38 of file ArrangedChildren.h.
References FArrangedChildren(), TArray< InElementType, InAllocatorType >::Add(), EVisibility::All, Array, TArrayView< InElementType, InSizeType >::Num(), and TArray< InElementType, InAllocatorType >::Reserve().
IndexOfByPredicate()
template<typename PredicateType> FORCEINLINE int32 FArrangedChildren::IndexOfByPredicate (const PredicateType & Pred) const inline
Definition at line 169 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
InsertWidget() [1/2]
void FArrangedChildren::InsertWidget (const FArrangedWidget & InWidgetGeometry, int32 Index)
InsertWidget() [2/2]
FORCEINLINE_DEBUGGABLE void FArrangedChildren::InsertWidget (EVisibility VisibilityOverride, const FArrangedWidget & InWidgetGeometry, int32 Index) inline
Definition at line 74 of file ArrangedChildren.h.
References Accepts(), Array, and FORCEINLINE_DEBUGGABLE.
IsValidIndex()
FORCEINLINE bool FArrangedChildren::IsValidIndex (int32 Index) inline
Definition at line 195 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Last() [1/2]
FORCEINLINE FArrangedWidget & FArrangedChildren::Last () inline
Definition at line 158 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Last() [2/2]
FORCEINLINE const FArrangedWidget & FArrangedChildren::Last () const inline
Definition at line 153 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Num()
FORCEINLINE int32 FArrangedChildren::Num () const inline
Definition at line 138 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Referenced by ArrangeChildrenInStack(), FWidgetPath::ExtendPathTo(), and SNodePanel::SNode::OnPaint().
operator[]() [1/2]
FORCEINLINE FArrangedWidget & FArrangedChildren::operator[] (int32 Index) inline
Definition at line 148 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
operator[]() [2/2]
FORCEINLINE const FArrangedWidget & FArrangedChildren::operator[] (int32 Index) const inline
Definition at line 143 of file ArrangedChildren.h.
References Array, and FORCEINLINE.
Remove()
FORCEINLINE void FArrangedChildren::Remove (int32 Index, int32 Count = 1) inline
Definition at line 180 of file ArrangedChildren.h.
References Array, Count, and FORCEINLINE.
Reserve()
FORCEINLINE_DEBUGGABLE void FArrangedChildren::Reserve (FArrangedWidgetArray::SizeType Number) inline
Reserves sufficient memory for the given number of arranged widgets.
Definition at line 83 of file ArrangedChildren.h.
References Array, and FORCEINLINE_DEBUGGABLE.
Referenced by ArrangeChildrenInStack().
Reverse()
void FArrangedChildren::Reverse () inline
Reverse the order of the arranged children.
Definition at line 50 of file ArrangedChildren.h.
References Array.
Referenced by FWidgetPath::GeneratePathToWidget().
SetFilter()
FORCEINLINE_DEBUGGABLE void FArrangedChildren::SetFilter (EVisibility InVisibility) inline
Definition at line 96 of file ArrangedChildren.h.
References FORCEINLINE_DEBUGGABLE, and VisibilityFilter.
Field Documentation
Array
FArrangedWidgetArray FArrangedChildren::Array private
Internal representation of the array widgets.
Definition at line 123 of file ArrangedChildren.h.
Referenced by AddWidget(), Append(), Empty(), FindItemIndex(), FindLastByPredicate(), GetInternalArray(), GetInternalArray(), Hittest2_FromArray(), IndexOfByPredicate(), InsertWidget(), IsValidIndex(), Last(), Last(), Num(), operator[](), operator[](), Remove(), Reserve(), and Reverse().
bAllow3DWidgets
bool FArrangedChildren::bAllow3DWidgets private
Definition at line 125 of file ArrangedChildren.h.
Referenced by FArrangedChildren(), and Allows3DWidgets().
VisibilityFilter
EVisibility FArrangedChildren::VisibilityFilter private
Definition at line 18 of file ArrangedChildren.h.
Referenced by FArrangedChildren(), Accepts(), GetFilter(), and SetFilter().
The documentation for this class was generated from the following file:
ArrangedChildren.h