Unreal Engine 5.6 C++ API: FCardRepresentationData Class Reference
FCardRepresentationData Class Reference
Card representation payload and output of the mesh build process.
#include "MeshCardBuild.h"
Public Member Functions
FCardRepresentationData ()
bool ContainsNaN () const
SIZE_T GetResourceSizeBytes () const
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
Public Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Data Fields
FCardRepresentationDataId CardRepresentationDataId
FMeshCardsBuildData MeshCardsBuildData
Friends
FArchive & operator<< (FArchive &Ar, FCardRepresentationData &Data)
Detailed Description
Card representation payload and output of the mesh build process.
Definition at line 136 of file MeshCardBuild.h.
Constructor & Destructor Documentation
FCardRepresentationData()
FCardRepresentationData::FCardRepresentationData () inline
Definition at line 144 of file MeshCardBuild.h.
References CardRepresentationDataId.
Referenced by operator<<.
Member Function Documentation
ContainsNaN()
bool FCardRepresentationData::ContainsNaN () const inline
Definition at line 163 of file MeshCardBuild.h.
References MeshCardsBuildData.
GetResourceSizeBytes()
SIZE_T FCardRepresentationData::GetResourceSizeBytes () const inline
Definition at line 156 of file MeshCardBuild.h.
References GetResourceSizeEx(), and FResourceSizeEx::GetTotalMemoryBytes().
GetResourceSizeEx()
void FCardRepresentationData::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const inline
Definition at line 151 of file MeshCardBuild.h.
References FResourceSizeEx::AddDedicatedSystemMemoryBytes().
Referenced by GetResourceSizeBytes().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FCardRepresentationData & Data) friend
Definition at line 193 of file MeshCardBuild.h.
References FCardRepresentationData(), Ar, and MeshCardsBuildData.
Field Documentation
CardRepresentationDataId
FCardRepresentationDataId FCardRepresentationData::CardRepresentationDataId
Definition at line 142 of file MeshCardBuild.h.
Referenced by FCardRepresentationData().
MeshCardsBuildData
FMeshCardsBuildData FCardRepresentationData::MeshCardsBuildData
Definition at line 140 of file MeshCardBuild.h.
Referenced by ContainsNaN(), and operator<<.
The documentation for this class was generated from the following file:
MeshCardBuild.h