Unreal Engine 5.6 C++ API: FQueuedThreadPool Class Reference
FQueuedThreadPool Class Reference abstract
Interface for queued thread pools.
#include "QueuedThreadPool.h"
Public Member Functions
FQueuedThreadPool ()
virtual ~FQueuedThreadPool ()
virtual void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal)=0
Checks to see if there is a thread available to perform the task.
virtual bool Create (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))=0
Creates the thread pool with the specified number of threads.
virtual bool CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
virtual void Destroy ()=0
Tells the pool to clean up all background threads.
virtual int32 GetNumThreads () const =0
Get the number of queued threads.
virtual bool RetractQueuedWork (IQueuedWork *InQueuedWork)=0
Attempts to retract a previously queued task.
Static Public Member Functions
static FQueuedThreadPool * Allocate ()
Allocates a thread pool.
Static Public Attributes
static uint32 OverrideStackSize
Stack size for threads created for the thread pool.
Detailed Description
Interface for queued thread pools.
This interface is used by all queued thread pools. It used as a callback by FQueuedThreads and is used to queue asynchronous work for callers.
Definition at line 104 of file QueuedThreadPool.h.
Constructor & Destructor Documentation
FQueuedThreadPool()
FQueuedThreadPool::FQueuedThreadPool ()
Referenced by FQueuedThreadPoolDynamicWrapper::FQueuedThreadPoolDynamicWrapper(), FQueuedThreadPoolWrapper::FQueuedThreadPoolWrapper(), and Allocate().
~FQueuedThreadPool()
virtual FQueuedThreadPool::~FQueuedThreadPool () virtual
Member Function Documentation
AddQueuedWork()
virtual void FQueuedThreadPool::AddQueuedWork (IQueuedWork * InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) pure virtual
Checks to see if there is a thread available to perform the task.
If not, it queues the work for later. Otherwise it is immediately dispatched.
Parameters
InQueuedWork The work that needs to be done asynchronously
InQueuedWorkPriority The priority at which to process this task
See also
RetractQueuedWork
Implemented in FQueuedLowLevelThreadPool, FQueuedThreadPoolDynamicWrapper, FQueuedThreadPoolTaskGraphWrapper, and FQueuedThreadPoolWrapper.
References Normal.
Referenced by FAutoDeleteAsyncTask< FCancelIORequestsTask >::Start().
Allocate()
FQueuedThreadPool * FQueuedThreadPool::Allocate () static
Allocates a thread pool.
Returns
A new thread pool.
References FQueuedThreadPool().
Create()
virtual bool FQueuedThreadPool::Create (uint32 InNumQueuedThreads, uint32 StackSize = (32 *1024), EThreadPriority ThreadPriority = TPri_Normal, const TCHAR * Name = TEXT("UnknownThreadPool")) pure virtual
Creates the thread pool with the specified number of threads.
Parameters
InNumQueuedThreads Specifies the number of threads to use in the pool
StackSize The size of stack the threads in the pool need (32K default)
ThreadPriority priority of new pool thread
Name optional name for the pool to be used for instrumentation
Returns
Whether the pool creation was successful or not
Implemented in FQueuedLowLevelThreadPool, FQueuedThreadPoolTaskGraphWrapper, and FQueuedThreadPoolWrapper.
References Name, and TPri_Normal.
CreateForkable()
virtual bool FQueuedThreadPool::CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize = (32 * 1024), EThreadPriority ThreadPriority = TPri_Normal, const TCHAR * Name = TEXT("UnknownThreadPool")) inline virtual
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
Currently only works after the process has been forked because GetSingleThreadInterface() isn't implemented for pooled threads
Parameters
InNumQueuedThreads Specifies the number of threads to use in the pool
StackSize The size of stack the threads in the pool need (32K default)
ThreadPriority priority of new pool thread
Name optional name for the pool to be used for instrumentation
Returns
Whether the pool creation was successful or not
Definition at line 129 of file QueuedThreadPool.h.
References Name, and TPri_Normal.
Destroy()
virtual void FQueuedThreadPool::Destroy () pure virtual
Tells the pool to clean up all background threads.
Implemented in FQueuedLowLevelThreadPool, FQueuedThreadPoolTaskGraphWrapper, and FQueuedThreadPoolWrapper.
GetNumThreads()
virtual int32 FQueuedThreadPool::GetNumThreads () const pure virtual
Get the number of queued threads.
Implemented in FQueuedLowLevelThreadPool, FQueuedThreadPoolTaskGraphWrapper, and FQueuedThreadPoolWrapper.
RetractQueuedWork()
virtual bool FQueuedThreadPool::RetractQueuedWork (IQueuedWork * InQueuedWork) pure virtual
Attempts to retract a previously queued task.
Parameters
InQueuedWork The work to try to retract
Returns
true if the work was retracted
See also
AddQueuedWork
Implemented in FQueuedLowLevelThreadPool, FQueuedThreadPoolTaskGraphWrapper, and FQueuedThreadPoolWrapper.
Field Documentation
OverrideStackSize
uint32 FQueuedThreadPool::OverrideStackSize static
Stack size for threads created for the thread pool.
Can be overridden by other projects. If 0 means to use the value passed in the Create method.
Definition at line 179 of file QueuedThreadPool.h.
The documentation for this class was generated from the following file:
QueuedThreadPool.h