Unreal Engine 5.6 C++ API: FShaderKey Class Reference
FShaderKey Class Reference
Encapsulates information about a shader's serialization behavior, used to detect when C++ serialization changes to auto-recompile.
#include "Shader.h"
Public Member Functions
FShaderKey (const FSHAHash &InMaterialShaderMapHash, const FShaderPipelineType *InShaderPipeline, FVertexFactoryType *InVertexFactoryType, int32 PermutationId, EShaderPlatform InPlatform)
Data Fields
FSHAHash MaterialShaderMapHash
int32 PermutationId
uint32 Platform: SP_NumBits
const FShaderPipelineType * ShaderPipeline
FVertexFactoryType * VertexFactoryType
Friends
uint32 GetTypeHash (const FShaderKey &Id)
RENDERCORE_API friend FArchive & operator<< (FArchive &Ar, FShaderKey &Ref)
bool operator== (const FShaderKey &X, const FShaderKey &Y)
Detailed Description
Encapsulates information about a shader's serialization behavior, used to detect when C++ serialization changes to auto-recompile.
Definition at line 670 of file Shader.h.
Constructor & Destructor Documentation
FShaderKey()
FShaderKey::FShaderKey (const FSHAHash & InMaterialShaderMapHash, const FShaderPipelineType * InShaderPipeline, FVertexFactoryType * InVertexFactoryType, int32 PermutationId, EShaderPlatform InPlatform) inline
Definition at line 673 of file Shader.h.
References MaterialShaderMapHash, PermutationId, Platform, ShaderPipeline, and VertexFactoryType.
Referenced by GetTypeHash, operator<<, and operator==.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FShaderKey & Id) friend
Definition at line 681 of file Shader.h.
References FShaderKey(), GetTypeHash, HashCombine(), MaterialShaderMapHash, PermutationId, Platform, and VertexFactoryType.
Referenced by GetTypeHash.
operator<<
RENDERCORE_API friend FArchive & operator<< (FArchive & Ar, FShaderKey & Ref) friend
References FShaderKey(), and Ar.
operator==
bool operator== (const FShaderKey & X, const FShaderKey & Y) friend
Definition at line 689 of file Shader.h.
References FShaderKey(), X, and Y.
Field Documentation
MaterialShaderMapHash
FSHAHash FShaderKey::MaterialShaderMapHash
Definition at line 702 of file Shader.h.
Referenced by FShaderKey(), and GetTypeHash.
PermutationId
int32 FShaderKey::PermutationId
Definition at line 703 of file Shader.h.
Referenced by FShaderKey(), and GetTypeHash.
Platform
uint32 FShaderKey::Platform
Definition at line 704 of file Shader.h.
Referenced by FShaderKey(), and GetTypeHash.
ShaderPipeline
const FShaderPipelineType* FShaderKey::ShaderPipeline
Definition at line 701 of file Shader.h.
Referenced by FShaderKey().
VertexFactoryType
FVertexFactoryType* FShaderKey::VertexFactoryType
Definition at line 700 of file Shader.h.
Referenced by FShaderKey(), and GetTypeHash.
The documentation for this class was generated from the following file:
Shader.h