Unreal Engine 5.6 C++ API: AGameplayCueNotify_Looping Class Reference
AGameplayCueNotify_Looping Class Reference
#include "GameplayCueNotify_Looping.h"
Protected Member Functions
virtual GAMEPLAYABILITIES_API void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual GAMEPLAYABILITIES_API EDataValidationResult IsDataValid (class FDataValidationContext &Context) const override
virtual GAMEPLAYABILITIES_API bool OnActive_Implementation (AActor *Target, const FGameplayCueParameters &Parameters) override
virtual GAMEPLAYABILITIES_API bool OnExecute_Implementation (AActor *Target, const FGameplayCueParameters &Parameters) override
virtual GAMEPLAYABILITIES_API bool OnRemove_Implementation (AActor *Target, const FGameplayCueParameters &Parameters) override
virtual GAMEPLAYABILITIES_API bool Recycle () override
GAMEPLAYABILITIES_API void RemoveLoopingEffects ()
UFUNCTION () GAMEPLAYABILITIES_API void OnApplication(AActor *Target
UFUNCTION () GAMEPLAYABILITIES_API void OnLoopingStart(AActor *Target
UFUNCTION () GAMEPLAYABILITIES_API void OnRecurring(AActor *Target
UFUNCTION () GAMEPLAYABILITIES_API void OnRemoval(AActor *Target
UPROPERTY () ") FGameplayCueNotify_BurstEffects ApplicationEffects
UPROPERTY () ") FGameplayCueNotify_BurstEffects RecurringEffects
UPROPERTY () ") FGameplayCueNotify_BurstEffects RemovalEffects
UPROPERTY () ") FGameplayCueNotify_LoopingEffects LoopingEffects
UPROPERTY () ") FGameplayCueNotify_SpawnResult ApplicationSpawnResults
UPROPERTY () ") FGameplayCueNotify_SpawnResult LoopingSpawnResults
UPROPERTY () ") FGameplayCueNotify_SpawnResult RecurringSpawnResults
UPROPERTY () ") FGameplayCueNotify_SpawnResult RemovalSpawnResults
UPROPERTY () FGameplayCueNotify_PlacementInfo DefaultPlacementInfo
UPROPERTY () FGameplayCueNotify_SpawnCondition DefaultSpawnCondition
virtual GAMEPLAYABILITIES_API bool WhileActive_Implementation (AActor *Target, const FGameplayCueParameters &Parameters) override
Protected Attributes
bool bLoopingEffectsRemoved
const FGameplayCueParameters & Parameters
const FGameplayCueParameters const FGameplayCueNotify_SpawnResult & SpawnResults
Detailed Description
Definition at line 20 of file GameplayCueNotify_Looping.h.
Member Function Documentation
EndPlay()
virtual GAMEPLAYABILITIES_API void AGameplayCueNotify_Looping::EndPlay (const EEndPlayReason::Type EndPlayReason) override protected virtual
References UE_API.
IsDataValid()
virtual GAMEPLAYABILITIES_API EDataValidationResult AGameplayCueNotify_Looping::IsDataValid (class FDataValidationContext & Context) const override protected virtual
References UE_API.
OnActive_Implementation()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_Looping::OnActive_Implementation (AActor * Target, const FGameplayCueParameters & Parameters) override protected virtual
References Parameters, Target, and UE_API.
OnExecute_Implementation()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_Looping::OnExecute_Implementation (AActor * Target, const FGameplayCueParameters & Parameters) override protected virtual
References Parameters, Target, and UE_API.
OnRemove_Implementation()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_Looping::OnRemove_Implementation (AActor * Target, const FGameplayCueParameters & Parameters) override protected virtual
References Parameters, Target, and UE_API.
Recycle()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_Looping::Recycle () override protected virtual
References UE_API.
RemoveLoopingEffects()
GAMEPLAYABILITIES_API void AGameplayCueNotify_Looping::RemoveLoopingEffects () protected
References RemoveLoopingEffects(), and UE_API.
Referenced by RemoveLoopingEffects().
UFUNCTION() [1/4]
AGameplayCueNotify_Looping::UFUNCTION () protected
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/4]
AGameplayCueNotify_Looping::UFUNCTION () protected
References Parameters, SpawnResults, Target, UE_API, and UFUNCTION().
UFUNCTION() [3/4]
AGameplayCueNotify_Looping::UFUNCTION () protected
References Parameters, SpawnResults, Target, UE_API, and UFUNCTION().
UFUNCTION() [4/4]
AGameplayCueNotify_Looping::UFUNCTION () protected
References Parameters, SpawnResults, Target, UE_API, and UFUNCTION().
UPROPERTY() [1/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [2/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [3/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [4/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [5/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [6/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [7/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [8/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [9/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [10/10]
AGameplayCueNotify_Looping::UPROPERTY () protected
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
WhileActive_Implementation()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_Looping::WhileActive_Implementation (AActor * Target, const FGameplayCueParameters & Parameters) override protected virtual
References Parameters, Target, and UE_API.
Field Documentation
bLoopingEffectsRemoved
bool AGameplayCueNotify_Looping::bLoopingEffectsRemoved protected
Definition at line 98 of file GameplayCueNotify_Looping.h.
Parameters
const FGameplayCueParameters & AGameplayCueNotify_Looping::Parameters protected
Definition at line 39 of file GameplayCueNotify_Looping.h.
Referenced by OnActive_Implementation(), OnExecute_Implementation(), OnRemove_Implementation(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and WhileActive_Implementation().
SpawnResults
const FGameplayCueParameters const FGameplayCueNotify_SpawnResult & AGameplayCueNotify_Looping::SpawnResults protected
Definition at line 39 of file GameplayCueNotify_Looping.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
The documentation for this class was generated from the following file:
GameplayCueNotify_Looping.h