Unreal Engine 5.6 C++ API: TDynamicStridePtr< DataType > Class Template Reference
TDynamicStridePtr< DataType > Class Template Reference
#include "StridePointer.h"
Public Member Functions
TDynamicStridePtr ()
TDynamicStridePtr (const TDynamicStridePtr &Other)
TDynamicStridePtr (DataType *InPointer, int32 InStride)
TDynamicStridePtr (int32 InStride)
void Init (const TDynamicStridePtr &Other)
operator DataType * ()
bool operator!= (const DataType *Other) const
bool operator!= (const TDynamicStridePtr &Other) const
DataType & operator* ()
DataType * operator+ (int32 Offset)
TDynamicStridePtr & operator++ ()
DataType * operator++ (int32)
TDynamicStridePtr & operator+= (int32 Offset)
DataType * operator- (int32 Offset)
TDynamicStridePtr & operator-- ()
DataType * operator-- (int32)
TDynamicStridePtr & operator-= (int32 Offset)
TDynamicStridePtr & operator= (const TDynamicStridePtr &Other)
TDynamicStridePtr & operator= (DataType *InPtr)
bool operator== (const DataType *Other) const
bool operator== (const TDynamicStridePtr &Other) const
DataType & operator[] (int32 Offset)
const DataType & operator[] (int32 Offset) const
Private Attributes
DataType * MyPointer
int32 Stride
Detailed Description
template<typename DataType>
class TDynamicStridePtr< DataType >
Definition at line 124 of file StridePointer.h.
Constructor & Destructor Documentation
TDynamicStridePtr() [1/4]
template<typename DataType> TDynamicStridePtr< DataType >::TDynamicStridePtr () inline
Definition at line 127 of file StridePointer.h.
References MyPointer, and Stride.
Referenced by TDynamicStridePtr(), Init(), operator!=(), operator++(), operator+=(), operator--(), operator-=(), operator=(), operator=(), and operator==().
TDynamicStridePtr() [2/4]
template<typename DataType> TDynamicStridePtr< DataType >::TDynamicStridePtr (DataType * InPointer, int32 InStride) inline
Definition at line 132 of file StridePointer.h.
References MyPointer, and Stride.
TDynamicStridePtr() [3/4]
template<typename DataType> TDynamicStridePtr< DataType >::TDynamicStridePtr (int32 InStride) inline
Definition at line 137 of file StridePointer.h.
References MyPointer, and Stride.
TDynamicStridePtr() [4/4]
template<typename DataType> TDynamicStridePtr< DataType >::TDynamicStridePtr (const TDynamicStridePtr< DataType > & Other) inline
Definition at line 142 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, Other, and Stride.
Member Function Documentation
Init()
template<typename DataType> void TDynamicStridePtr< DataType >::Init (const TDynamicStridePtr< DataType > & Other) inline
Definition at line 147 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, Other, and Stride.
operator DataType *()
template<typename DataType> TDynamicStridePtr< DataType >::operator DataType * () inline
Definition at line 166 of file StridePointer.h.
References MyPointer.
operator!=() [1/2]
template<typename DataType> bool TDynamicStridePtr< DataType >::operator!= (const DataType * Other) const inline
Definition at line 238 of file StridePointer.h.
References MyPointer, and Other.
operator!=() [2/2]
template<typename DataType> bool TDynamicStridePtr< DataType >::operator!= (const TDynamicStridePtr< DataType > & Other) const inline
Definition at line 233 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Other.
operator*()
template<typename DataType> DataType & TDynamicStridePtr< DataType >::operator* () inline
Definition at line 253 of file StridePointer.h.
References MyPointer.
operator+()
template<typename DataType> DataType * TDynamicStridePtr< DataType >::operator+ (int32 Offset) inline
Definition at line 171 of file StridePointer.h.
References MyPointer, and Stride.
operator++() [1/2]
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator++ () inline
Definition at line 194 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Stride.
operator++() [2/2]
template<typename DataType> DataType * TDynamicStridePtr< DataType >::operator++ (int32) inline
Definition at line 201 of file StridePointer.h.
References MyPointer, and Stride.
operator+=()
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator+= (int32 Offset) inline
Definition at line 181 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Stride.
operator-()
template<typename DataType> DataType * TDynamicStridePtr< DataType >::operator- (int32 Offset) inline
Definition at line 176 of file StridePointer.h.
References MyPointer, and Stride.
operator--() [1/2]
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator-- () inline
Definition at line 209 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Stride.
operator--() [2/2]
template<typename DataType> DataType * TDynamicStridePtr< DataType >::operator-- (int32) inline
Definition at line 216 of file StridePointer.h.
References MyPointer, and Stride.
operator-=()
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator-= (int32 Offset) inline
Definition at line 187 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Stride.
operator=() [1/2]
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator= (const TDynamicStridePtr< DataType > & Other) inline
Definition at line 159 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, Other, and Stride.
operator=() [2/2]
template<typename DataType> TDynamicStridePtr & TDynamicStridePtr< DataType >::operator= (DataType * InPtr) inline
Definition at line 153 of file StridePointer.h.
References TDynamicStridePtr(), and MyPointer.
operator==() [1/2]
template<typename DataType> bool TDynamicStridePtr< DataType >::operator== (const DataType * Other) const inline
Definition at line 228 of file StridePointer.h.
References MyPointer, and Other.
operator==() [2/2]
template<typename DataType> bool TDynamicStridePtr< DataType >::operator== (const TDynamicStridePtr< DataType > & Other) const inline
Definition at line 223 of file StridePointer.h.
References TDynamicStridePtr(), MyPointer, and Other.
operator[]() [1/2]
template<typename DataType> DataType & TDynamicStridePtr< DataType >::operator[] (int32 Offset) inline
Definition at line 248 of file StridePointer.h.
References MyPointer, and Stride.
operator[]() [2/2]
template<typename DataType> const DataType & TDynamicStridePtr< DataType >::operator[] (int32 Offset) const inline
Definition at line 243 of file StridePointer.h.
References MyPointer, and Stride.
Field Documentation
MyPointer
template<typename DataType> DataType* TDynamicStridePtr< DataType >::MyPointer private
Definition at line 260 of file StridePointer.h.
Referenced by TDynamicStridePtr(), TDynamicStridePtr(), TDynamicStridePtr(), TDynamicStridePtr(), Init(), operator DataType *(), operator!=(), operator!=(), operator*(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), operator=(), operator=(), operator==(), operator==(), operator[](), and operator[]().
Stride
template<typename DataType> int32 TDynamicStridePtr< DataType >::Stride private
Definition at line 259 of file StridePointer.h.
Referenced by TDynamicStridePtr(), TDynamicStridePtr(), TDynamicStridePtr(), TDynamicStridePtr(), Init(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), operator=(), operator[](), and operator[]().
The documentation for this class was generated from the following file:
StridePointer.h