Unreal Engine 5.6 C++ API: MemoryTrace.h File Reference
MemoryTrace.h File Reference
#include "HAL/Platform.h"
#include "Misc/EnumClassFlags.h"
#include "Trace/Config.h"
#include "Trace/Trace.h"
Macros
#define UE_MEMORY_TRACE(x)
#define UE_MEMORY_TRACE_AVAILABLE 0
#define UE_MEMORY_TRACE_ENABLED 0
#define UE_MEMORY_TRACE_LATE_INIT 0
Typedefs
typedef uint32 HeapId
Enumerations
enum class EMemoryTraceHeapAllocationFlags : uint8 { None = 0 , Heap = 1 << 0 , Swap = 2 << 0 }
enum class EMemoryTraceHeapFlags : uint16 { None = 0 , Root = 1 << 0 , NeverFrees = 1 << 1 }
enum class EMemoryTraceInit : uint8 {
Disabled = 0 , AllocEvents = 1 << 0 , Callstacks = 1 << 1 , Tags = 1 << 2 ,
Probing = 1 << 3 , Full = AllocEvents|Callstacks|Tags|Probing , Light = AllocEvents|Tags
}
enum EMemoryTraceRootHeap : uint8 { SystemMemory , VideoMemory , EndHardcoded = VideoMemory , EndReserved = 15 }
enum class EMemoryTraceSwapOperation : uint8 { PageOut = 0 , PageIn = 1 , FreeInSwap = 2 }
Functions
ENUM_CLASS_FLAGS (EMemoryTraceHeapAllocationFlags)
ENUM_CLASS_FLAGS (EMemoryTraceHeapFlags)
ENUM_CLASS_FLAGS (EMemoryTraceInit)
void MemoryTrace_Alloc (uint64 Address, uint64 Size, uint32 Alignment, HeapId RootHeap=EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId=0)
void MemoryTrace_Free (uint64 Address, HeapId RootHeap=EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId=0)
class FMalloc * MemoryTrace_GetAllocator ()
HeapId MemoryTrace_HeapSpec (HeapId ParentId, const TCHAR *Name, EMemoryTraceHeapFlags Flags=EMemoryTraceHeapFlags::None)
void MemoryTrace_MarkAllocAsHeap (uint64 Address, HeapId Heap)
void MemoryTrace_ReallocAlloc (uint64 Address, uint64 NewSize, uint32 Alignment, HeapId RootHeap=EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId=0)
void MemoryTrace_ReallocFree (uint64 Address, HeapId RootHeap=EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId=0)
HeapId MemoryTrace_RootHeapSpec (const TCHAR *Name, EMemoryTraceHeapFlags Flags=EMemoryTraceHeapFlags::None)
void MemoryTrace_SwapOp (uint64 PageAddress, EMemoryTraceSwapOperation SwapOperation, uint32 CompressedSize=0, uint32 CallstackId=0)
void MemoryTrace_UnmarkAllocAsHeap (uint64 Address, HeapId Heap)
void MemoryTrace_UpdateAlloc (uint64 Address, HeapId RootHeap=EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId=0)
Macro Definition Documentation
UE_MEMORY_TRACE
#define UE_MEMORY_TRACE (x)
Definition at line 194 of file MemoryTrace.h.
UE_MEMORY_TRACE_AVAILABLE
#define UE_MEMORY_TRACE_AVAILABLE 0
Definition at line 10 of file MemoryTrace.h.
UE_MEMORY_TRACE_ENABLED
#define UE_MEMORY_TRACE_ENABLED 0
Definition at line 26 of file MemoryTrace.h.
UE_MEMORY_TRACE_LATE_INIT
#define UE_MEMORY_TRACE_LATE_INIT 0
Definition at line 14 of file MemoryTrace.h.
Typedef Documentation
HeapId
typedef uint32 HeapId
Definition at line 30 of file MemoryTrace.h.
Enumeration Type Documentation
EMemoryTraceHeapAllocationFlags
enum class EMemoryTraceHeapAllocationFlags : uint8 strong
Enumerator
None
Heap
Swap
Definition at line 55 of file MemoryTrace.h.
EMemoryTraceHeapFlags
enum class EMemoryTraceHeapFlags : uint16 strong
Enumerator
None
Root
NeverFrees
Definition at line 44 of file MemoryTrace.h.
EMemoryTraceInit
enum class EMemoryTraceInit : uint8 strong
Enumerator
Disabled
AllocEvents
Callstacks
Tags
Probing
Full
Light
Definition at line 75 of file MemoryTrace.h.
EMemoryTraceRootHeap
enum EMemoryTraceRootHeap : uint8
Enumerator
SystemMemory
VideoMemory
EndHardcoded
EndReserved
Definition at line 33 of file MemoryTrace.h.
EMemoryTraceSwapOperation
enum class EMemoryTraceSwapOperation : uint8 strong
Enumerator
PageOut
PageIn
FreeInSwap
Definition at line 64 of file MemoryTrace.h.
Function Documentation
ENUM_CLASS_FLAGS() [1/3]
ENUM_CLASS_FLAGS (EMemoryTraceHeapAllocationFlags)
ENUM_CLASS_FLAGS() [2/3]
ENUM_CLASS_FLAGS (EMemoryTraceHeapFlags)
ENUM_CLASS_FLAGS() [3/3]
ENUM_CLASS_FLAGS (EMemoryTraceInit)
References Flags, Heap, Name, None, SystemMemory, and TSequenceHistory< HistorySize >::Size.
MemoryTrace_Alloc()
void MemoryTrace_Alloc (uint64 Address, uint64 Size, uint32 Alignment, HeapId RootHeap = EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId = 0) inline
Definition at line 199 of file MemoryTrace.h.
References SystemMemory, and TSequenceHistory< HistorySize >::Size.
Referenced by FGrowableMallocChunk::Malloc(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc(), and FMemory::UE_ALLOCATION_FUNCTION().
MemoryTrace_Free()
void MemoryTrace_Free (uint64 Address, HeapId RootHeap = EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId = 0) inline
Definition at line 200 of file MemoryTrace.h.
References SystemMemory.
Referenced by FGrowableMallocChunk::Free(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Free(), and FMemory::SystemFree().
MemoryTrace_GetAllocator()
class FMalloc * MemoryTrace_GetAllocator () inline
Definition at line 205 of file MemoryTrace.h.
MemoryTrace_HeapSpec()
HeapId MemoryTrace_HeapSpec (HeapId ParentId, const TCHAR * Name, EMemoryTraceHeapFlags Flags = EMemoryTraceHeapFlags::None) inline
Definition at line 196 of file MemoryTrace.h.
References Flags, Name, and None.
MemoryTrace_MarkAllocAsHeap()
void MemoryTrace_MarkAllocAsHeap (uint64 Address, HeapId Heap) inline
Definition at line 197 of file MemoryTrace.h.
References Heap.
Referenced by TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::AllocateBlock(), and TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc().
MemoryTrace_ReallocAlloc()
void MemoryTrace_ReallocAlloc (uint64 Address, uint64 NewSize, uint32 Alignment, HeapId RootHeap = EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId = 0) inline
Definition at line 202 of file MemoryTrace.h.
References SystemMemory.
MemoryTrace_ReallocFree()
void MemoryTrace_ReallocFree (uint64 Address, HeapId RootHeap = EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId = 0) inline
Definition at line 201 of file MemoryTrace.h.
References SystemMemory.
MemoryTrace_RootHeapSpec()
HeapId MemoryTrace_RootHeapSpec (const TCHAR * Name, EMemoryTraceHeapFlags Flags = EMemoryTraceHeapFlags::None) inline
Definition at line 195 of file MemoryTrace.h.
References Flags, Name, and None.
MemoryTrace_SwapOp()
void MemoryTrace_SwapOp (uint64 PageAddress, EMemoryTraceSwapOperation SwapOperation, uint32 CompressedSize = 0, uint32 CallstackId = 0) inline
Definition at line 204 of file MemoryTrace.h.
MemoryTrace_UnmarkAllocAsHeap()
void MemoryTrace_UnmarkAllocAsHeap (uint64 Address, HeapId Heap) inline
Definition at line 198 of file MemoryTrace.h.
References Heap.
Referenced by TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::FTLSCleanup::~FTLSCleanup(), and TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Free().
MemoryTrace_UpdateAlloc()
void MemoryTrace_UpdateAlloc (uint64 Address, HeapId RootHeap = EMemoryTraceRootHeap::SystemMemory, uint32 ExternalCallstackId = 0) inline
Definition at line 203 of file MemoryTrace.h.
References SystemMemory.