Unreal Engine 5.6 C++ API: Metasound::TAudioDataChannel< TDataType > Class Template Reference
Metasound::TAudioDataChannel< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TAudioDataChannel (const FOperatorSettings &InOperatorSettings)
virtual int64 CreateNewPayloadID () override
virtual FName GetDataType () override
virtual bool IsEmpty () const override
virtual void PopOpaque (IReceiver &InReceiver) override
virtual bool PushOpaque (ISender &InSender) override
Public Member Functions inherited from Metasound::IDataChannel
IDataChannel (FName DataType)
virtual ~IDataChannel ()=default
uint32 GetNumActiveReceivers () const
uint32 GetNumActiveSenders () const
virtual int64 GetPayloadID () const
TUniquePtr< IReceiver > NewReceiver (const FReceiverInitParams &InitParams)
TUniquePtr< ISender > NewSender (const FSenderInitParams &InitParams)
virtual bool PushLiteral (const FLiteral &InParam)
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Public Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedRef< IDataChannel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDataChannel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FName GetDataTypeName ()
Protected Member Functions
virtual TUniquePtr< IReceiver > ConstructNewReceiverImplementation (const FReceiverInitParams &InitParams) override
virtual TUniquePtr< ISender > ConstructNewSenderImplementation (const FSenderInitParams &InitParams) override
Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
TArray< Audio::FPatchMixerSplitter > AudioBuses
std::atomic< int64 > PayloadIDCounter
Static Private Attributes
static const int32 MaxChannels = 8
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TAudioDataChannel< TDataType >
Definition at line 855 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TAudioDataChannel()
template<typename TDataType> Metasound::TAudioDataChannel< TDataType >::TAudioDataChannel (const FOperatorSettings & InOperatorSettings) inline
Definition at line 860 of file MetasoundRouter.h.
References Metasound::IDataChannel::IDataChannel(), AudioBuses, GetDataTypeName(), MaxChannels, and PayloadIDCounter.
Member Function Documentation
ConstructNewReceiverImplementation()
template<typename TDataType> virtual TUniquePtr< IReceiver > Metasound::TAudioDataChannel< TDataType >::ConstructNewReceiverImplementation (const FReceiverInitParams & InitParams) inline override protected virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 902 of file MetasoundRouter.h.
References TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >::AsShared(), AudioBuses, and MoveTemp().
ConstructNewSenderImplementation()
template<typename TDataType> virtual TUniquePtr< ISender > Metasound::TAudioDataChannel< TDataType >::ConstructNewSenderImplementation (const FSenderInitParams & InitParams) inline override protected virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 913 of file MetasoundRouter.h.
References TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >::AsShared(), AudioBuses, and MoveTemp().
CreateNewPayloadID()
template<typename TDataType> virtual int64 Metasound::TAudioDataChannel< TDataType >::CreateNewPayloadID () inline override virtual
Implements Metasound::IDataChannel.
Definition at line 880 of file MetasoundRouter.h.
References PayloadIDCounter.
GetDataType()
template<typename TDataType> virtual FName Metasound::TAudioDataChannel< TDataType >::GetDataType () inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 896 of file MetasoundRouter.h.
References GetDataTypeName().
GetDataTypeName()
template<typename TDataType> FName Metasound::TAudioDataChannel< TDataType >::GetDataTypeName () inline static
Definition at line 891 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TAudioDataChannel(), and GetDataType().
IsEmpty()
template<typename TDataType> virtual bool Metasound::TAudioDataChannel< TDataType >::IsEmpty () const inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 886 of file MetasoundRouter.h.
PopOpaque()
template<typename TDataType> virtual void Metasound::TAudioDataChannel< TDataType >::PopOpaque (IReceiver & InReceiver) inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 872 of file MetasoundRouter.h.
References AudioBuses, and Metasound::IDataChannel::IReceiver.
PushOpaque()
template<typename TDataType> virtual bool Metasound::TAudioDataChannel< TDataType >::PushOpaque (ISender & InSender) inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 867 of file MetasoundRouter.h.
References Metasound::IDataChannel::ISender.
Field Documentation
AudioBuses
template<typename TDataType> TArray<Audio::FPatchMixerSplitter> Metasound::TAudioDataChannel< TDataType >::AudioBuses private
Definition at line 925 of file MetasoundRouter.h.
Referenced by TAudioDataChannel(), ConstructNewReceiverImplementation(), ConstructNewSenderImplementation(), and PopOpaque().
MaxChannels
template<typename TDataType> const int32 Metasound::TAudioDataChannel< TDataType >::MaxChannels = 8 static private
Definition at line 858 of file MetasoundRouter.h.
Referenced by TAudioDataChannel().
PayloadIDCounter
template<typename TDataType> std::atomic<int64> Metasound::TAudioDataChannel< TDataType >::PayloadIDCounter private
Definition at line 926 of file MetasoundRouter.h.
Referenced by TAudioDataChannel(), and CreateNewPayloadID().
The documentation for this class was generated from the following file:
MetasoundRouter.h