Unreal Engine 5.6 C++ API: FNetworkPredictionDriverBase< ModelDef > Struct Template Reference
FNetworkPredictionDriverBase< ModelDef > Struct Template Reference
#include "NetworkPredictionDriver.h"
Data Structures
struct CCallServerRPCMemberFuncable
struct CFinalizeFrameMemberFuncable
struct CFinalizeSmoothingFrameMemberFuncable
struct CGetPhysicsBodyInstanceMemberFuncable
struct CGetPhysicsPrimitiveComponentMemberFuncable
struct CInitializeSimulationStateFuncable
struct CProduceInputMemberFuncable
struct CRestoreFrameMemberFuncable
struct CSetHiddenForInterpolationFuncable
Public Types
using AuxType = typename StateTypes::AuxType
using DriverType = typename ModelDef::Driver
using InputType = typename StateTypes::InputType
using PhysicsState = typename ModelDef::PhysicsState
using Simulation = typename ModelDef::Simulation
using StateTypes = typename ModelDef::StateTypes
using SyncType = typename StateTypes::SyncType
Static Public Member Functions
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type BeginInterpolatedPhysics (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type BeginInterpolatedPhysics (DriverType *Driver)
template<bool HasFunc = HasFinalizeFrame>
static TEnableIf< HasFunc >::Type CallFinalizeFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool HasFunc = HasFinalizeFrame>
static TEnableIf<!HasFunc >::Type CallFinalizeFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool HasFunc = HasFinalizeSmoothingFrame>
static TEnableIf< HasFunc >::Type CallFinalizeSmoothingFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool HasFunc = HasFinalizeSmoothingFrame>
static TEnableIf<!HasFunc >::Type CallFinalizeSmoothingFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool HasFunc = HasInitializeSimulationState>
static TEnableIf< HasFunc >::Type CallInitializeSimulationStateMemberFunc (DriverType *Driver, SyncType *Sync, AuxType *Aux)
template<bool HasFunc = HasInitializeSimulationState>
static TEnableIf<!HasFunc >::Type CallInitializeSimulationStateMemberFunc (DriverType *Driver, SyncType *Sync, AuxType *Aux)
template<bool HasFunc = HasProduceInput>
static TEnableIf< HasFunc >::Type CallProduceInputMemberFunc (DriverType *Driver, int32 DeltaTimeMS, InputType *InputCmd)
template<bool HasFunc = HasProduceInput>
static TEnableIf<!HasFunc >::Type CallProduceInputMemberFunc (DriverType *Driver, int32 DeltaTimeMS, InputType *InputCmd)
template<bool HasFunc = HasRestoreFrame>
static TEnableIf< HasFunc >::Type CallRestoreFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool HasFunc = HasRestoreFrame>
static TEnableIf<!HasFunc >::Type CallRestoreFrameMemberFunc (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
static void CallServerRPC (DriverType *Driver)
template<bool HasFunc = HasCallServerRPC>
static TEnableIf< HasFunc >::Type CallServerRPCMemberFunc (DriverType *Driver)
template<bool HasFunc = HasCallServerRPC>
static TEnableIf<!HasFunc >::Type CallServerRPCMemberFunc (DriverType *Driver)
template<bool HasFunc = HasSetHiddenForInterpolation>
static TEnableIf< HasFunc >::Type CallSetHiddenForInterpolation (DriverType *Driver, bool bHide)
template<bool HasFunc = HasSetHiddenForInterpolation>
static TEnableIf<!HasFunc >::Type CallSetHiddenForInterpolation (DriverType *Driver, bool bHide)
static void CallSetHiddenForInterpolationFallback (AActor *Driver, bool bHide)
static void CallSetHiddenForInterpolationFallback (UActorComponent *Driver, bool bHide)
template<typename InDriverType = DriverType>
static void DispatchCues (TNetSimCueDispatcher< ModelDef > *CueDispatcher, InDriverType *Driver, int32 SimFrame, int32 SimTimeMS, const int32 FixedStepMS)
static void DispatchCues (TNetSimCueDispatcher< ModelDef > *CueDispatcher, void *Driver, int32 SimFrame, int32 SimTimeMS, const int32 FixedStepMS)
static void DrawDebugOutline (DriverType *Driver, FColor Color, float Lifetime=0.f)
static void DrawDebugText3D (DriverType *Driver, const TCHAR *Str, FColor Color, float Lifetime=0.f, float ZOffset=50.f)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type EndInterpolatedPhysics (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type EndInterpolatedPhysics (DriverType *Driver)
static void FinalizeFrame (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type FinalizeInterpolatedPhysics (DriverType *Driver, TConditionalState< PhysicsState > &Physics)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type FinalizeInterpolatedPhysics (DriverType *Driver, TConditionalState< PhysicsState > &Physics)
static void FinalizeSmoothingFrame (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
static constexpr FNetworkPredictionModelDefCapabilities GetCapabilities ()
static FNetworkPredictionInstanceConfig GetConfig (const FNetworkPredictionInstanceArchetype &Archetype, const FNetworkPredictionSettings &GlobalSettings, ENetRole Role, bool bHasNetConnection)
static FBox GetDebugBoundingBox (AActor *DriverActor)
static FBox GetDebugBoundingBox (UActorComponent *DriverComponent)
static FBox GetDebugBoundingBox (void *NoDriver)
static void GetDebugString (AActor *Actor, FStringBuilderBase &Builder)
static void GetDebugString (UActorComponent *ActorComp, FStringBuilderBase &Builder)
static void GetDebugString (void *NoDriver, FStringBuilderBase &Builder)
static void GetDebugStringFull (AActor *Actor, FStringBuilderBase &Builder)
static void GetDebugStringFull (UActorComponent *ActorComp, FStringBuilderBase &Builder)
static void GetDebugStringFull (void *NoDriver, FStringBuilderBase &Builder)
static FTransform GetDebugWorldTransform (AActor *DriverActor)
static FTransform GetDebugWorldTransform (UActorComponent *DriverComponent)
static FTransform GetDebugWorldTransform (void *NoDriver)
static bool GetDefaultArchetype (FNetworkPredictionInstanceArchetype &Archetype, ENetworkPredictionTickingPolicy PreferredTickingPolicy, bool bCanPhysicsTickPhysics)
template<bool HasFunc = HasGetBodyInstance>
static TEnableIf< HasFunc, FBodyInstance * >::Type GetPhysicsBodyInstance (DriverType *Driver)
template<bool HasFunc = HasGetBodyInstance>
static TEnableIf<!HasFunc, FBodyInstance * >::Type GetPhysicsBodyInstance (DriverType *Driver)
template<bool HasFunc = HasGetPrimitiveComp>
static TEnableIf< HasFunc, UPrimitiveComponent * >::Type GetPhysicsPrimitiveComponent (DriverType *Driver)
template<bool HasFunc = HasGetPrimitiveComp>
static TEnableIf<!HasFunc, UPrimitiveComponent * >::Type GetPhysicsPrimitiveComponent (DriverType *Driver)
static void GetTraceString (AActor *Actor, FStringBuilderBase &Builder)
static void GetTraceString (UActorComponent *ActorComp, FStringBuilderBase &Builder)
static void GetTraceString (void *NoDriver, FStringBuilderBase &Builder)
static constexpr bool HasDriver ()
static constexpr bool HasInput ()
static constexpr bool HasNpState ()
static constexpr bool HasPhysics ()
static constexpr bool HasSimulation ()
static void InitializeSimulationState (DriverType *Driver, FNetworkPredictionStateView *View)
static void InitializeSimulationState (DriverType *Driver, SyncType *Sync, AuxType *Aux)
static void Interpolate (const TSyncAuxPair< StateTypes > &From, const TSyncAuxPair< StateTypes > &To, const float PCT, SyncType *SyncOut, AuxType *AuxOut)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type InterpolatePhysics (TConditionalState< PhysicsState > &FromState, TConditionalState< PhysicsState > &ToState, float PCT, TConditionalState< PhysicsState > &OutState)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type InterpolatePhysics (TConditionalState< PhysicsState > &FromState, TConditionalState< PhysicsState > &ToState, float PCT, TConditionalState< PhysicsState > &OutState)
template<typename StateType>
static void InterpolateState (const StateType *From, const StateType *To, const float PCT, StateType *Out)
static void InterpolateState (const void *From, const void *To, const float PCT, void *Out)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type LogPhysicsState (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, FOutputDevice &Ar=*GLog)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type LogPhysicsState (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, FOutputDevice &Ar=*GLog)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type LogPhysicsState (TConditionalState< PhysicsState > &RecvState, FOutputDevice &Ar=*GLog)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type LogPhysicsState (TConditionalState< PhysicsState > &RecvState, FOutputDevice &Ar=*GLog)
template<typename StateType>
static void LogUserState (const StateType *State, FOutputDevice &Ar=*GLog)
static void LogUserStates (const TNetworkPredictionState< StateTypes > &UserStates, FOutputDevice &Ar=*GLog)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type MarshalPhysicsToComponent (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type MarshalPhysicsToComponent (DriverType *Driver)
template<typename StateType>
static void NetSerialize (TConditionalState< StateType > &State, const FNetSerializeParams &P)
static void NetSerialize (TConditionalState< void > &State, const FNetSerializeParams &P)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type PerformPhysicsRollback (DriverType *Driver, TConditionalState< PhysicsState > &RecvState)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type PerformPhysicsRollback (DriverType *Driver, TConditionalState< PhysicsState > &RecvState)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type PhysicsNetRecv (const FNetSerializeParams &P, TConditionalState< PhysicsState > &RecvState)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type PhysicsNetRecv (const FNetSerializeParams &P, TConditionalState< PhysicsState > &RecvState)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type PhysicsNetSend (const FNetSerializeParams &P, DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type PhysicsNetSend (const FNetSerializeParams &P, DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable, bool >::Type PhysicsStateIsConsistent (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable, bool >::Type PhysicsStateIsConsistent (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type PostPhysicsResimulate (DriverType *Driver)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type PostPhysicsResimulate (DriverType *Driver)
static void ProduceInput (DriverType *Driver, int32 DeltaTimeMS, InputType *InputCmd)
static void RestoreFrame (DriverType *Driver, const SyncType *SyncState, const AuxType *AuxState)
template<typename InDriverType>
static UPrimitiveComponent * SafeCastDriverToPrimitiveComponent (InDriverType *Driver)
static UPrimitiveComponent * SafeCastDriverToPrimitiveComponent (UPrimitiveComponent *Driver)
static void SetHiddenForInterpolation (DriverType *Driver, bool bHide)
template<typename StateType>
static bool ShouldReconcile (const StateType *Predicted, const StateType *Authority)
static bool ShouldReconcile (const TSyncAuxPair< StateTypes > &Predicted, const TSyncAuxPair< StateTypes > &Authority)
static bool ShouldReconcile (const void *Predicted, const void *Authority)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable, bool >::Type ShouldReconcilePhysics (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, TConditionalState< PhysicsState > &RecvState)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable, bool >::Type ShouldReconcilePhysics (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, TConditionalState< PhysicsState > &RecvState)
template<typename StateType>
static void ToString (const StateType *State, FAnsiStringBuilderBase &Builder)
static void ToString (const void *State, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type TracePhysicsState (DriverType *Driver, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type TracePhysicsState (DriverType *Driver, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type TracePhysicsState (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type TracePhysicsState (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf< bEnable >::Type TracePhysicsStateRecv (const TConditionalState< PhysicsState > &RecvState, FAnsiStringBuilderBase &Builder)
template<bool bEnable = HasPhysics()>
static TEnableIf<!bEnable >::Type TracePhysicsStateRecv (const TConditionalState< PhysicsState > &RecvState, FAnsiStringBuilderBase &Builder)
template<typename StateType>
static void TraceUserStateString (const StateType *State, FAnsiStringBuilderBase &Builder)
Static Public Attributes
static constexpr bool HasCallServerRPC = TModels_V<CCallServerRPCMemberFuncable, DriverType>
static constexpr bool HasFinalizeFrame = TModels_V<CFinalizeFrameMemberFuncable, DriverType, SyncType, AuxType>
static constexpr bool HasFinalizeSmoothingFrame = TModels_V<CFinalizeSmoothingFrameMemberFuncable, DriverType, SyncType, AuxType>
static constexpr bool HasGetBodyInstance = TModels_V<CGetPhysicsBodyInstanceMemberFuncable, DriverType>
static constexpr bool HasGetPrimitiveComp = TModels_V<CGetPhysicsPrimitiveComponentMemberFuncable, DriverType>
static constexpr bool HasInitializeSimulationState = TModels_V<CInitializeSimulationStateFuncable, DriverType, SyncType, AuxType>
static constexpr bool HasProduceInput = TModels_V<CProduceInputMemberFuncable, DriverType, int32, InputType>
static constexpr bool HasRestoreFrame = TModels_V<CRestoreFrameMemberFuncable, DriverType, SyncType, AuxType>
static constexpr bool HasSetHiddenForInterpolation = TModels_V<CSetHiddenForInterpolationFuncable, DriverType>
Detailed Description
template<typename ModelDef>
struct FNetworkPredictionDriverBase< ModelDef >
Definition at line 62 of file NetworkPredictionDriver.h.
Member Typedef Documentation
AuxType
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::AuxType = typename StateTypes::AuxType
Definition at line 69 of file NetworkPredictionDriver.h.
DriverType
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::DriverType = typename ModelDef::Driver
Definition at line 64 of file NetworkPredictionDriver.h.
InputType
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::InputType = typename StateTypes::InputType
Definition at line 67 of file NetworkPredictionDriver.h.
PhysicsState
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::PhysicsState = typename ModelDef::PhysicsState
Definition at line 70 of file NetworkPredictionDriver.h.
Simulation
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::Simulation = typename ModelDef::Simulation
Definition at line 65 of file NetworkPredictionDriver.h.
StateTypes
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::StateTypes = typename ModelDef::StateTypes
Definition at line 66 of file NetworkPredictionDriver.h.
SyncType
template<typename ModelDef> using FNetworkPredictionDriverBase< ModelDef >::SyncType = typename StateTypes::SyncType
Definition at line 68 of file NetworkPredictionDriver.h.
Member Function Documentation
BeginInterpolatedPhysics() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::BeginInterpolatedPhysics (DriverType * Driver) inline static
Definition at line 731 of file NetworkPredictionDriver.h.
References GetPhysicsPrimitiveComponent().
BeginInterpolatedPhysics() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::BeginInterpolatedPhysics (DriverType * Driver) inline static
Definition at line 737 of file NetworkPredictionDriver.h.
CallFinalizeFrameMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasFinalizeFrame> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallFinalizeFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 345 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by FinalizeFrame().
CallFinalizeFrameMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasFinalizeFrame> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallFinalizeFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 352 of file NetworkPredictionDriver.h.
References HasNpState(), npCheckf, and TEXT.
CallFinalizeSmoothingFrameMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasFinalizeSmoothingFrame> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallFinalizeSmoothingFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 377 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by FinalizeSmoothingFrame().
CallFinalizeSmoothingFrameMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasFinalizeSmoothingFrame> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallFinalizeSmoothingFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 384 of file NetworkPredictionDriver.h.
CallInitializeSimulationStateMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasInitializeSimulationState> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallInitializeSimulationStateMemberFunc (DriverType * Driver, SyncType * Sync, AuxType * Aux) inline static
Definition at line 280 of file NetworkPredictionDriver.h.
References Aux, npCheckSlow, and Sync.
Referenced by InitializeSimulationState().
CallInitializeSimulationStateMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasInitializeSimulationState> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallInitializeSimulationStateMemberFunc (DriverType * Driver, SyncType * Sync, AuxType * Aux) inline static
Definition at line 287 of file NetworkPredictionDriver.h.
References Aux, HasNpState(), npCheckf, Sync, and TEXT.
CallProduceInputMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasProduceInput> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallProduceInputMemberFunc (DriverType * Driver, int32 DeltaTimeMS, InputType * InputCmd) inline static
Definition at line 314 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by ProduceInput().
CallProduceInputMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasProduceInput> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallProduceInputMemberFunc (DriverType * Driver, int32 DeltaTimeMS, InputType * InputCmd) inline static
Definition at line 321 of file NetworkPredictionDriver.h.
References npCheckf, and TEXT.
CallRestoreFrameMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasRestoreFrame> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallRestoreFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 417 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by RestoreFrame().
CallRestoreFrameMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasRestoreFrame> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallRestoreFrameMemberFunc (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 424 of file NetworkPredictionDriver.h.
CallServerRPC()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::CallServerRPC (DriverType * Driver) inline static
Definition at line 439 of file NetworkPredictionDriver.h.
References CallServerRPCMemberFunc().
CallServerRPCMemberFunc() [1/2]
template<typename ModelDef> template<bool HasFunc = HasCallServerRPC> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallServerRPCMemberFunc (DriverType * Driver) inline static
Definition at line 453 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by CallServerRPC().
CallServerRPCMemberFunc() [2/2]
template<typename ModelDef> template<bool HasFunc = HasCallServerRPC> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallServerRPCMemberFunc (DriverType * Driver) inline static
Definition at line 460 of file NetworkPredictionDriver.h.
References npCheckf, and TEXT.
CallSetHiddenForInterpolation() [1/2]
template<typename ModelDef> template<bool HasFunc = HasSetHiddenForInterpolation> TEnableIf< HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallSetHiddenForInterpolation (DriverType * Driver, bool bHide) inline static
Definition at line 542 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by SetHiddenForInterpolation().
CallSetHiddenForInterpolation() [2/2]
template<typename ModelDef> template<bool HasFunc = HasSetHiddenForInterpolation> TEnableIf<!HasFunc >::Type FNetworkPredictionDriverBase< ModelDef >::CallSetHiddenForInterpolation (DriverType * Driver, bool bHide) inline static
Definition at line 549 of file NetworkPredictionDriver.h.
References CallSetHiddenForInterpolationFallback().
CallSetHiddenForInterpolationFallback() [1/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::CallSetHiddenForInterpolationFallback (AActor * Driver, bool bHide) inline static
Definition at line 554 of file NetworkPredictionDriver.h.
Referenced by CallSetHiddenForInterpolation().
CallSetHiddenForInterpolationFallback() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::CallSetHiddenForInterpolationFallback (UActorComponent * Driver, bool bHide) inline static
Definition at line 559 of file NetworkPredictionDriver.h.
References UActorComponent::GetOwner().
DispatchCues() [1/2]
template<typename ModelDef> template<typename InDriverType = DriverType> void FNetworkPredictionDriverBase< ModelDef >::DispatchCues (TNetSimCueDispatcher< ModelDef > * CueDispatcher, InDriverType * Driver, int32 SimFrame, int32 SimTimeMS, const int32 FixedStepMS) inline static
Definition at line 472 of file NetworkPredictionDriver.h.
References npCheckSlow.
DispatchCues() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::DispatchCues (TNetSimCueDispatcher< ModelDef > * CueDispatcher, void * Driver, int32 SimFrame, int32 SimTimeMS, const int32 FixedStepMS) inline static
Definition at line 478 of file NetworkPredictionDriver.h.
DrawDebugOutline()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::DrawDebugOutline (DriverType * Driver, FColor Color, float Lifetime = 0.f) inline static
Definition at line 239 of file NetworkPredictionDriver.h.
References Color, NetworkPredictionDebug::DrawDebugOutline(), GetDebugBoundingBox(), and GetDebugWorldTransform().
DrawDebugText3D()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::DrawDebugText3D (DriverType * Driver, const TCHAR * Str, FColor Color, float Lifetime = 0.f, float ZOffset = 50.f) inline static
Definition at line 244 of file NetworkPredictionDriver.h.
References Color, NetworkPredictionDebug::DrawDebugText3D(), FVector, GetDebugWorldTransform(), and Transform.
EndInterpolatedPhysics() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::EndInterpolatedPhysics (DriverType * Driver) inline static
Definition at line 743 of file NetworkPredictionDriver.h.
References GetPhysicsPrimitiveComponent().
EndInterpolatedPhysics() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::EndInterpolatedPhysics (DriverType * Driver) inline static
Definition at line 749 of file NetworkPredictionDriver.h.
FinalizeFrame()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::FinalizeFrame (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 331 of file NetworkPredictionDriver.h.
References CallFinalizeFrameMemberFunc().
FinalizeInterpolatedPhysics() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::FinalizeInterpolatedPhysics (DriverType * Driver, TConditionalState< PhysicsState > & Physics) inline static
Definition at line 719 of file NetworkPredictionDriver.h.
References GetPhysicsPrimitiveComponent(), and Physics.
FinalizeInterpolatedPhysics() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::FinalizeInterpolatedPhysics (DriverType * Driver, TConditionalState< PhysicsState > & Physics) inline static
Definition at line 725 of file NetworkPredictionDriver.h.
References Physics.
FinalizeSmoothingFrame()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::FinalizeSmoothingFrame (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 363 of file NetworkPredictionDriver.h.
References CallFinalizeSmoothingFrameMemberFunc().
GetCapabilities()
template<typename ModelDef> constexpr FNetworkPredictionModelDefCapabilities FNetworkPredictionDriverBase< ModelDef >::GetCapabilities () inline static constexpr
Definition at line 79 of file NetworkPredictionDriver.h.
References FNetworkPredictionModelDefCapabilities::FSupportedNetworkLODs::AP, FNetworkPredictionModelDefCapabilities::FixedNetworkLODs, HasPhysics(), HasSimulation(), FNetworkPredictionModelDefCapabilities::IndependentNetworkLODs, FNetworkPredictionModelDefCapabilities::FSupportedNetworkLODs::SP, and FNetworkPredictionModelDefCapabilities::SupportedTickingPolicies.
Referenced by GetConfig(), and GetDefaultArchetype().
GetConfig()
template<typename ModelDef> FNetworkPredictionInstanceConfig FNetworkPredictionDriverBase< ModelDef >::GetConfig (const FNetworkPredictionInstanceArchetype & Archetype, const FNetworkPredictionSettings & GlobalSettings, ENetRole Role, bool bHasNetConnection) inline static
Definition at line 125 of file NetworkPredictionDriver.h.
References FNetworkPredictionModelDefCapabilities::FSupportedNetworkLODs::AP, EnumHasAnyFlags(), FNetworkPredictionModelDefCapabilities::FixedNetworkLODs, GetCapabilities(), GetHighestNetworkLOD(), FNetworkPredictionModelDefCapabilities::IndependentNetworkLODs, Passive, PollPerSimFrame, Role, FNetworkPredictionModelDefCapabilities::FSupportedNetworkLODs::SP, and FNetworkPredictionInstanceArchetype::TickingMode.
GetDebugBoundingBox() [1/3]
template<typename ModelDef> FBox FNetworkPredictionDriverBase< ModelDef >::GetDebugBoundingBox (AActor * DriverActor) inline static
Definition at line 223 of file NetworkPredictionDriver.h.
Referenced by DrawDebugOutline(), and GetDebugBoundingBox().
GetDebugBoundingBox() [2/3]
template<typename ModelDef> FBox FNetworkPredictionDriverBase< ModelDef >::GetDebugBoundingBox (UActorComponent * DriverComponent) inline static
Definition at line 228 of file NetworkPredictionDriver.h.
References GetDebugBoundingBox(), and UActorComponent::GetOwner().
GetDebugBoundingBox() [3/3]
template<typename ModelDef> FBox FNetworkPredictionDriverBase< ModelDef >::GetDebugBoundingBox (void * NoDriver) inline static
Definition at line 233 of file NetworkPredictionDriver.h.
References npEnsure.
GetDebugString() [1/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugString (AActor * Actor, FStringBuilderBase & Builder) inline static
Definition at line 162 of file NetworkPredictionDriver.h.
References Actor, TStringBuilderBase< CharType >::Appendf(), and TEXT.
Referenced by TNetSimCueDispatcher< ModelDef >::GetDebugName().
GetDebugString() [2/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugString (UActorComponent * ActorComp, FStringBuilderBase & Builder) inline static
Definition at line 167 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Appendf(), UActorComponent::GetOwnerRole(), and TEXT.
GetDebugString() [3/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugString (void * NoDriver, FStringBuilderBase & Builder) inline static
Definition at line 172 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Append().
GetDebugStringFull() [1/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull (AActor * Actor, FStringBuilderBase & Builder) inline static
Definition at line 177 of file NetworkPredictionDriver.h.
References Actor, TStringBuilderBase< CharType >::Appendf(), and TEXT.
GetDebugStringFull() [2/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull (UActorComponent * ActorComp, FStringBuilderBase & Builder) inline static
Definition at line 182 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Appendf(), UActorComponent::GetOwnerRole(), UObjectBaseUtility::GetPathName(), and TEXT.
GetDebugStringFull() [3/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull (void * NoDriver, FStringBuilderBase & Builder) inline static
Definition at line 187 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Append().
GetDebugWorldTransform() [1/3]
template<typename ModelDef> FTransform FNetworkPredictionDriverBase< ModelDef >::GetDebugWorldTransform (AActor * DriverActor) inline static
Definition at line 207 of file NetworkPredictionDriver.h.
Referenced by DrawDebugOutline(), DrawDebugText3D(), and GetDebugWorldTransform().
GetDebugWorldTransform() [2/3]
template<typename ModelDef> FTransform FNetworkPredictionDriverBase< ModelDef >::GetDebugWorldTransform (UActorComponent * DriverComponent) inline static
Definition at line 212 of file NetworkPredictionDriver.h.
References GetDebugWorldTransform(), and UActorComponent::GetOwner().
GetDebugWorldTransform() [3/3]
template<typename ModelDef> FTransform FNetworkPredictionDriverBase< ModelDef >::GetDebugWorldTransform (void * NoDriver) inline static
Definition at line 217 of file NetworkPredictionDriver.h.
References UE::Math::TTransform< double >::Identity, and npEnsure.
GetDefaultArchetype()
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::GetDefaultArchetype (FNetworkPredictionInstanceArchetype & Archetype, ENetworkPredictionTickingPolicy PreferredTickingPolicy, bool bCanPhysicsTickPhysics) inline static
Definition at line 101 of file NetworkPredictionDriver.h.
References EnumHasAnyFlags(), GetCapabilities(), HasPhysics(), FNetworkPredictionModelDefCapabilities::SupportedTickingPolicies, and FNetworkPredictionInstanceArchetype::TickingMode.
GetPhysicsBodyInstance() [1/2]
template<typename ModelDef> template<bool HasFunc = HasGetBodyInstance> TEnableIf< HasFunc, FBodyInstance * >::Type FNetworkPredictionDriverBase< ModelDef >::GetPhysicsBodyInstance (DriverType * Driver) inline static
Definition at line 630 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by LogPhysicsState(), MarshalPhysicsToComponent(), PerformPhysicsRollback(), PhysicsNetSend(), PhysicsStateIsConsistent(), PostPhysicsResimulate(), ShouldReconcilePhysics(), TracePhysicsState(), and TracePhysicsState().
GetPhysicsBodyInstance() [2/2]
template<typename ModelDef> template<bool HasFunc = HasGetBodyInstance> TEnableIf<!HasFunc, FBodyInstance * >::Type FNetworkPredictionDriverBase< ModelDef >::GetPhysicsBodyInstance (DriverType * Driver) inline static
Definition at line 637 of file NetworkPredictionDriver.h.
References GetPhysicsPrimitiveComponent(), and npCheckSlow.
GetPhysicsPrimitiveComponent() [1/2]
template<typename ModelDef> template<bool HasFunc = HasGetPrimitiveComp> TEnableIf< HasFunc, UPrimitiveComponent * >::Type FNetworkPredictionDriverBase< ModelDef >::GetPhysicsPrimitiveComponent (DriverType * Driver) inline static
Definition at line 588 of file NetworkPredictionDriver.h.
References npCheckSlow.
Referenced by BeginInterpolatedPhysics(), EndInterpolatedPhysics(), FinalizeInterpolatedPhysics(), GetPhysicsBodyInstance(), MarshalPhysicsToComponent(), PhysicsStateIsConsistent(), and PostPhysicsResimulate().
GetPhysicsPrimitiveComponent() [2/2]
template<typename ModelDef> template<bool HasFunc = HasGetPrimitiveComp> TEnableIf<!HasFunc, UPrimitiveComponent * >::Type FNetworkPredictionDriverBase< ModelDef >::GetPhysicsPrimitiveComponent (DriverType * Driver) inline static
Definition at line 595 of file NetworkPredictionDriver.h.
References SafeCastDriverToPrimitiveComponent().
GetTraceString() [1/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetTraceString (AActor * Actor, FStringBuilderBase & Builder) inline static
Definition at line 197 of file NetworkPredictionDriver.h.
References Actor, TStringBuilderBase< CharType >::Appendf(), and TEXT.
GetTraceString() [2/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetTraceString (UActorComponent * ActorComp, FStringBuilderBase & Builder) inline static
Definition at line 192 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Appendf(), UObjectBaseUtility::GetName(), UActorComponent::GetOwner(), and TEXT.
Referenced by FNetworkPredictionTrace::TraceSimulationCreated().
GetTraceString() [3/3]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::GetTraceString (void * NoDriver, FStringBuilderBase & Builder) inline static
Definition at line 202 of file NetworkPredictionDriver.h.
References TStringBuilderBase< CharType >::Append().
HasDriver()
template<typename ModelDef> constexpr bool FNetworkPredictionDriverBase< ModelDef >::HasDriver () inline static constexpr
Definition at line 73 of file NetworkPredictionDriver.h.
HasInput()
template<typename ModelDef> constexpr bool FNetworkPredictionDriverBase< ModelDef >::HasInput () inline static constexpr
Definition at line 75 of file NetworkPredictionDriver.h.
HasNpState()
template<typename ModelDef> constexpr bool FNetworkPredictionDriverBase< ModelDef >::HasNpState () inline static constexpr
Definition at line 72 of file NetworkPredictionDriver.h.
Referenced by CallFinalizeFrameMemberFunc(), and CallInitializeSimulationStateMemberFunc().
HasPhysics()
template<typename ModelDef> constexpr bool FNetworkPredictionDriverBase< ModelDef >::HasPhysics () inline static constexpr
Definition at line 76 of file NetworkPredictionDriver.h.
Referenced by GetCapabilities(), GetDefaultArchetype(), FNetworkPredictionTrace::TracePhysicsStateAtFrame(), FNetworkPredictionTrace::TracePhysicsStateCurrent(), and FNetworkPredictionTrace::TracePhysicsStateRecv().
HasSimulation()
template<typename ModelDef> constexpr bool FNetworkPredictionDriverBase< ModelDef >::HasSimulation () inline static constexpr
Definition at line 74 of file NetworkPredictionDriver.h.
Referenced by GetCapabilities().
InitializeSimulationState() [1/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::InitializeSimulationState (DriverType * Driver, FNetworkPredictionStateView * View) inline static
Definition at line 260 of file NetworkPredictionDriver.h.
References InitializeSimulationState(), npCheckSlow, FNetworkPredictionStateView::PendingAuxState, and FNetworkPredictionStateView::PendingSyncState.
Referenced by InitializeSimulationState().
InitializeSimulationState() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::InitializeSimulationState (DriverType * Driver, SyncType * Sync, AuxType * Aux) inline static
Definition at line 266 of file NetworkPredictionDriver.h.
References Aux, CallInitializeSimulationStateMemberFunc(), and Sync.
Interpolate()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::Interpolate (const TSyncAuxPair< StateTypes > & From, const TSyncAuxPair< StateTypes > & To, const float PCT, SyncType * SyncOut, AuxType * AuxOut) inline static
Definition at line 506 of file NetworkPredictionDriver.h.
References TSyncAuxPair< StateType >::Aux, InterpolateState(), and TSyncAuxPair< StateType >::Sync.
InterpolatePhysics() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::InterpolatePhysics (TConditionalState< PhysicsState > & FromState, TConditionalState< PhysicsState > & ToState, float PCT, TConditionalState< PhysicsState > & OutState) inline static
Definition at line 705 of file NetworkPredictionDriver.h.
InterpolatePhysics() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::InterpolatePhysics (TConditionalState< PhysicsState > & FromState, TConditionalState< PhysicsState > & ToState, float PCT, TConditionalState< PhysicsState > & OutState) inline static
Definition at line 711 of file NetworkPredictionDriver.h.
InterpolateState() [1/2]
template<typename ModelDef> template<typename StateType> void FNetworkPredictionDriverBase< ModelDef >::InterpolateState (const StateType * From, const StateType * To, const float PCT, StateType * Out) inline static
Definition at line 513 of file NetworkPredictionDriver.h.
Referenced by Interpolate().
InterpolateState() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::InterpolateState (const void * From, const void * To, const float PCT, void * Out) inline static
Definition at line 518 of file NetworkPredictionDriver.h.
LogPhysicsState() [1/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, FOutputDevice & Ar = *GLog) inline static
Definition at line 809 of file NetworkPredictionDriver.h.
References Ar, GetPhysicsBodyInstance(), GLog, StringCast(), and TStringBuilderBase< CharType >::ToString().
LogPhysicsState() [2/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, FOutputDevice & Ar = *GLog) inline static
Definition at line 818 of file NetworkPredictionDriver.h.
References Ar, and GLog.
LogPhysicsState() [3/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState (TConditionalState< PhysicsState > & RecvState, FOutputDevice & Ar = *GLog) inline static
Definition at line 797 of file NetworkPredictionDriver.h.
References Ar, GLog, StringCast(), and TStringBuilderBase< CharType >::ToString().
LogPhysicsState() [4/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState (TConditionalState< PhysicsState > & RecvState, FOutputDevice & Ar = *GLog) inline static
Definition at line 806 of file NetworkPredictionDriver.h.
References Ar, and GLog.
LogUserState()
template<typename ModelDef> template<typename StateType> void FNetworkPredictionDriverBase< ModelDef >::LogUserState (const StateType * State, FOutputDevice & Ar = *GLog) inline static
Definition at line 883 of file NetworkPredictionDriver.h.
References Ar, GLog, State, StringCast(), ToString(), and TStringBuilderBase< CharType >::ToString().
LogUserStates()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::LogUserStates (const TNetworkPredictionState< StateTypes > & UserStates, FOutputDevice & Ar = *GLog) inline static
Definition at line 868 of file NetworkPredictionDriver.h.
References Ar, TNetworkPredictionState< StateType >::Aux, TNetworkPredictionState< StateType >::Cmd, GLog, StringCast(), TNetworkPredictionState< StateType >::Sync, ToString(), and TStringBuilderBase< CharType >::ToString().
MarshalPhysicsToComponent() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::MarshalPhysicsToComponent (DriverType * Driver) inline static
Definition at line 692 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance(), GetPhysicsPrimitiveComponent(), and npCheckSlow.
Referenced by RestoreFrame().
MarshalPhysicsToComponent() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::MarshalPhysicsToComponent (DriverType * Driver) inline static
Definition at line 699 of file NetworkPredictionDriver.h.
NetSerialize() [1/2]
template<typename ModelDef> template<typename StateType> void FNetworkPredictionDriverBase< ModelDef >::NetSerialize (TConditionalState< StateType > & State, const FNetSerializeParams & P) inline static
Definition at line 915 of file NetworkPredictionDriver.h.
References State.
Referenced by TFixedTickReplicator_Server< InModelDef >::EatCmd(), TIndependentTickReplicator_Server< InModelDef >::EatCmd(), TCommonReplicator_AP< ModelDef >::NetRecv(), TCommonReplicator_SP< InModelDef >::NetRecv(), TFixedTickReplicator_Server< InModelDef >::NetRecv(), TIndependentTickReplicator_Server< InModelDef >::NetRecv(), TCommonReplicator_AP< ModelDef >::NetSend(), TCommonReplicator_SP< InModelDef >::NetSend(), TFixedTickReplicator_Server< InModelDef >::NetSend(), and TIndependentTickReplicator_Server< InModelDef >::NetSend().
NetSerialize() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::NetSerialize (TConditionalState< void > & State, const FNetSerializeParams & P) inline static
Definition at line 920 of file NetworkPredictionDriver.h.
References State.
PerformPhysicsRollback() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PerformPhysicsRollback (DriverType * Driver, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 665 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance().
PerformPhysicsRollback() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PerformPhysicsRollback (DriverType * Driver, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 671 of file NetworkPredictionDriver.h.
PhysicsNetRecv() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsNetRecv (const FNetSerializeParams & P, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 767 of file NetworkPredictionDriver.h.
Referenced by TCommonReplicator_AP< ModelDef >::NetRecv(), and TCommonReplicator_SP< InModelDef >::NetRecv().
PhysicsNetRecv() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsNetRecv (const FNetSerializeParams & P, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 773 of file NetworkPredictionDriver.h.
PhysicsNetSend() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsNetSend (const FNetSerializeParams & P, DriverType * Driver) inline static
Definition at line 755 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance().
Referenced by TCommonReplicator_AP< ModelDef >::NetSend(), and TCommonReplicator_SP< InModelDef >::NetSend().
PhysicsNetSend() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsNetSend (const FNetSerializeParams & P, DriverType * Driver) inline static
Definition at line 761 of file NetworkPredictionDriver.h.
PhysicsStateIsConsistent() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable, bool >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsStateIsConsistent (DriverType * Driver) inline static
Definition at line 780 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance(), and GetPhysicsPrimitiveComponent().
PhysicsStateIsConsistent() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable, bool >::Type FNetworkPredictionDriverBase< ModelDef >::PhysicsStateIsConsistent (DriverType * Driver) inline static
Definition at line 787 of file NetworkPredictionDriver.h.
References npCheck.
PostPhysicsResimulate() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PostPhysicsResimulate (DriverType * Driver) inline static
Definition at line 677 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance(), and GetPhysicsPrimitiveComponent().
PostPhysicsResimulate() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::PostPhysicsResimulate (DriverType * Driver) inline static
Definition at line 683 of file NetworkPredictionDriver.h.
References npCheck.
ProduceInput()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::ProduceInput (DriverType * Driver, int32 DeltaTimeMS, InputType * InputCmd) inline static
Definition at line 300 of file NetworkPredictionDriver.h.
References CallProduceInputMemberFunc().
RestoreFrame()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::RestoreFrame (DriverType * Driver, const SyncType * SyncState, const AuxType * AuxState) inline static
Definition at line 402 of file NetworkPredictionDriver.h.
References CallRestoreFrameMemberFunc(), and MarshalPhysicsToComponent().
SafeCastDriverToPrimitiveComponent() [1/2]
template<typename ModelDef> template<typename InDriverType> UPrimitiveComponent * FNetworkPredictionDriverBase< ModelDef >::SafeCastDriverToPrimitiveComponent (InDriverType * Driver) inline static
Definition at line 601 of file NetworkPredictionDriver.h.
References npCheckf, and TEXT.
Referenced by GetPhysicsPrimitiveComponent().
SafeCastDriverToPrimitiveComponent() [2/2]
template<typename ModelDef> UPrimitiveComponent * FNetworkPredictionDriverBase< ModelDef >::SafeCastDriverToPrimitiveComponent (UPrimitiveComponent * Driver) inline static
Definition at line 612 of file NetworkPredictionDriver.h.
SetHiddenForInterpolation()
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::SetHiddenForInterpolation (DriverType * Driver, bool bHide) inline static
Definition at line 528 of file NetworkPredictionDriver.h.
References CallSetHiddenForInterpolation().
ShouldReconcile() [1/3]
template<typename ModelDef> template<typename StateType> bool FNetworkPredictionDriverBase< ModelDef >::ShouldReconcile (const StateType * Predicted, const StateType * Authority) inline static
Definition at line 494 of file NetworkPredictionDriver.h.
References Authority, and Predicted.
ShouldReconcile() [2/3]
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::ShouldReconcile (const TSyncAuxPair< StateTypes > & Predicted, const TSyncAuxPair< StateTypes > & Authority) inline static
Definition at line 488 of file NetworkPredictionDriver.h.
References Authority, Predicted, and ShouldReconcile().
Referenced by ShouldReconcile().
ShouldReconcile() [3/3]
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::ShouldReconcile (const void * Predicted, const void * Authority) inline static
Definition at line 499 of file NetworkPredictionDriver.h.
References Authority, and Predicted.
ShouldReconcilePhysics() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable, bool >::Type FNetworkPredictionDriverBase< ModelDef >::ShouldReconcilePhysics (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 649 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance().
ShouldReconcilePhysics() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable, bool >::Type FNetworkPredictionDriverBase< ModelDef >::ShouldReconcilePhysics (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, TConditionalState< PhysicsState > & RecvState) inline static
Definition at line 655 of file NetworkPredictionDriver.h.
ToString() [1/2]
template<typename ModelDef> template<typename StateType> void FNetworkPredictionDriverBase< ModelDef >::ToString (const StateType * State, FAnsiStringBuilderBase & Builder) inline static
Definition at line 902 of file NetworkPredictionDriver.h.
References State.
Referenced by LogUserState(), LogUserStates(), and TraceUserStateString().
ToString() [2/2]
template<typename ModelDef> void FNetworkPredictionDriverBase< ModelDef >::ToString (const void * State, FAnsiStringBuilderBase & Builder) inline static
Definition at line 907 of file NetworkPredictionDriver.h.
References State.
TracePhysicsState() [1/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState (DriverType * Driver, FAnsiStringBuilderBase & Builder) inline static
Definition at line 836 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance().
Referenced by FNetworkPredictionTrace::TracePhysicsStateAtFrame(), and FNetworkPredictionTrace::TracePhysicsStateCurrent().
TracePhysicsState() [2/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState (DriverType * Driver, FAnsiStringBuilderBase & Builder) inline static
Definition at line 842 of file NetworkPredictionDriver.h.
TracePhysicsState() [3/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, FAnsiStringBuilderBase & Builder) inline static
Definition at line 846 of file NetworkPredictionDriver.h.
References GetPhysicsBodyInstance().
TracePhysicsState() [4/4]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver, FAnsiStringBuilderBase & Builder) inline static
Definition at line 852 of file NetworkPredictionDriver.h.
TracePhysicsStateRecv() [1/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf< bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsStateRecv (const TConditionalState< PhysicsState > & RecvState, FAnsiStringBuilderBase & Builder) inline static
Definition at line 826 of file NetworkPredictionDriver.h.
References TConditionalState< TestType, UnderlyingType >::Get().
Referenced by FNetworkPredictionTrace::TracePhysicsStateRecv().
TracePhysicsStateRecv() [2/2]
template<typename ModelDef> template<bool bEnable = HasPhysics()> TEnableIf<!bEnable >::Type FNetworkPredictionDriverBase< ModelDef >::TracePhysicsStateRecv (const TConditionalState< PhysicsState > & RecvState, FAnsiStringBuilderBase & Builder) inline static
Definition at line 832 of file NetworkPredictionDriver.h.
TraceUserStateString()
template<typename ModelDef> template<typename StateType> void FNetworkPredictionDriverBase< ModelDef >::TraceUserStateString (const StateType * State, FAnsiStringBuilderBase & Builder) inline static
Definition at line 894 of file NetworkPredictionDriver.h.
References State, and ToString().
Referenced by FNetworkPredictionTrace::TraceUserState().
Field Documentation
HasCallServerRPC
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasCallServerRPC = TModels_V<CCallServerRPCMemberFuncable, DriverType> static constexpr
Definition at line 450 of file NetworkPredictionDriver.h.
HasFinalizeFrame
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasFinalizeFrame = TModels_V<CFinalizeFrameMemberFuncable, DriverType, SyncType, AuxType> static constexpr
Definition at line 342 of file NetworkPredictionDriver.h.
HasFinalizeSmoothingFrame
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasFinalizeSmoothingFrame = TModels_V<CFinalizeSmoothingFrameMemberFuncable, DriverType, SyncType, AuxType> static constexpr
Definition at line 374 of file NetworkPredictionDriver.h.
HasGetBodyInstance
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasGetBodyInstance = TModels_V<CGetPhysicsBodyInstanceMemberFuncable, DriverType> static constexpr
Definition at line 627 of file NetworkPredictionDriver.h.
HasGetPrimitiveComp
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasGetPrimitiveComp = TModels_V<CGetPhysicsPrimitiveComponentMemberFuncable, DriverType> static constexpr
Definition at line 585 of file NetworkPredictionDriver.h.
HasInitializeSimulationState
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasInitializeSimulationState = TModels_V<CInitializeSimulationStateFuncable, DriverType, SyncType, AuxType> static constexpr
Definition at line 277 of file NetworkPredictionDriver.h.
HasProduceInput
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasProduceInput = TModels_V<CProduceInputMemberFuncable, DriverType, int32, InputType> static constexpr
Definition at line 311 of file NetworkPredictionDriver.h.
HasRestoreFrame
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasRestoreFrame = TModels_V<CRestoreFrameMemberFuncable, DriverType, SyncType, AuxType> static constexpr
Definition at line 414 of file NetworkPredictionDriver.h.
HasSetHiddenForInterpolation
template<typename ModelDef> bool FNetworkPredictionDriverBase< ModelDef >::HasSetHiddenForInterpolation = TModels_V<CSetHiddenForInterpolationFuncable, DriverType> static constexpr
Definition at line 539 of file NetworkPredictionDriver.h.
The documentation for this struct was generated from the following file:
NetworkPredictionDriver.h