Unreal Engine 5.6 C++ API: FBulkDataCookedIndex Class Reference
FBulkDataCookedIndex Class Reference
#include "BulkDataCookedIndex.h"
Public Types
using ValueType = uint8
Public Member Functions
FBulkDataCookedIndex ()=default
FBulkDataCookedIndex (ValueType InValue)
~FBulkDataCookedIndex ()=default
FString GetAsExtension () const
ValueType GetValue () const
bool IsDefault () const
bool operator< (const FBulkDataCookedIndex &Other) const
bool operator== (const FBulkDataCookedIndex &Other) const
Static Public Member Functions
static FBulkDataCookedIndex ParseFromPath (FStringView Path)
Static Public Attributes
static const FBulkDataCookedIndex Default
static constexpr int32 MAX_DIGITS = 3
Private Attributes
ValueType Value = 0
Friends
uint32 GetTypeHash (const FBulkDataCookedIndex &ChunkGroup)
void operator<< (FStructuredArchive::FSlot Slot, FBulkDataCookedIndex &ChunkGroup)
Detailed Description
Definition at line 33 of file BulkDataCookedIndex.h.
Member Typedef Documentation
ValueType
using FBulkDataCookedIndex::ValueType = uint8
Definition at line 39 of file BulkDataCookedIndex.h.
Constructor & Destructor Documentation
FBulkDataCookedIndex() [1/2]
FBulkDataCookedIndex::FBulkDataCookedIndex () default
Referenced by GetTypeHash, operator<(), operator<<, operator==(), and ParseFromPath().
FBulkDataCookedIndex() [2/2]
FBulkDataCookedIndex::FBulkDataCookedIndex (ValueType InValue) inline explicit
Definition at line 45 of file BulkDataCookedIndex.h.
References Value.
~FBulkDataCookedIndex()
FBulkDataCookedIndex::~FBulkDataCookedIndex () default
Member Function Documentation
GetAsExtension()
FString FBulkDataCookedIndex::GetAsExtension () const inline
Definition at line 62 of file BulkDataCookedIndex.h.
References IsDefault(), TEXT, and Value.
GetValue()
ValueType FBulkDataCookedIndex::GetValue () const inline
Definition at line 74 of file BulkDataCookedIndex.h.
References Value.
IsDefault()
bool FBulkDataCookedIndex::IsDefault () const inline
Definition at line 53 of file BulkDataCookedIndex.h.
References Value.
Referenced by GetAsExtension().
operator<()
bool FBulkDataCookedIndex::operator< (const FBulkDataCookedIndex & Other) const inline
Definition at line 84 of file BulkDataCookedIndex.h.
References FBulkDataCookedIndex(), Other, and Value.
operator==()
bool FBulkDataCookedIndex::operator== (const FBulkDataCookedIndex & Other) const inline
Definition at line 79 of file BulkDataCookedIndex.h.
References FBulkDataCookedIndex(), Other, and Value.
ParseFromPath()
FBulkDataCookedIndex FBulkDataCookedIndex::ParseFromPath (FStringView Path) inline static
Definition at line 100 of file BulkDataCookedIndex.h.
References FBulkDataCookedIndex(), UE::String::IsNumericOnlyDigits(), FPathViews::IsSeparator(), LexFromString(), Path, and Value.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FBulkDataCookedIndex & ChunkGroup) friend
Definition at line 94 of file BulkDataCookedIndex.h.
References FBulkDataCookedIndex(), GetTypeHash, and Value.
Referenced by GetTypeHash.
operator<<
void operator<< (FStructuredArchive::FSlot Slot, FBulkDataCookedIndex & ChunkGroup) friend
Definition at line 89 of file BulkDataCookedIndex.h.
References FBulkDataCookedIndex(), and Value.
Field Documentation
Default
const FBulkDataCookedIndex FBulkDataCookedIndex::Default static
Definition at line 42 of file BulkDataCookedIndex.h.
Referenced by FLinkerSave::UE_DEPRECATED(), FLinkerSave::UE_DEPRECATED(), FLinkerSave::UE_DEPRECATED(), IPackageResourceManager::UE_DEPRECATED(), IPackageResourceManager::UE_DEPRECATED(), and IPackageResourceManager::UE_DEPRECATED().
MAX_DIGITS
int32 FBulkDataCookedIndex::MAX_DIGITS = 3 static constexpr
Definition at line 40 of file BulkDataCookedIndex.h.
Value
ValueType FBulkDataCookedIndex::Value = 0 private
Definition at line 138 of file BulkDataCookedIndex.h.
Referenced by FBulkDataCookedIndex(), GetAsExtension(), GetTypeHash, GetValue(), IsDefault(), operator<(), operator<<, operator==(), and ParseFromPath().
The documentation for this class was generated from the following file:
BulkDataCookedIndex.h