Unreal Engine 5.6 C++ API: FSizeParam Struct Reference
FSizeParam Struct Reference
Base structure for size parameters.
#include "SlateStructs.h"
Public Types
enum ESizeRule { SizeRule_Auto , SizeRule_Stretch , SizeRule_StretchContent }
Data Fields
TAttribute< float > ShrinkValue
The actual value this size parameter stores, used for shrinking.
ESizeRule SizeRule
The sizing rule to use.
TAttribute< float > Value
The actual value this size parameter stores.
Protected Member Functions
FSizeParam (ESizeRule InTypeOfSize, const TAttribute< float > &InValue, const TAttribute< float > &InShrinkValue)
Hidden constructor.
Detailed Description
Base structure for size parameters.
Describes a way in which a parent widget allocates available space to its child widgets.
When SizeRule is SizeRule_Auto, the required space is the widget's DesiredSize. When SizeRule is SizeRule_Stretch, the required space is the available space distributed proportionately between peer Widgets. When SizeRule is SizeRule_StretchContent, the required space is widget's content size adjusted proportionally to fit the available space.
Available space is space remaining after all the peers' SizeRule_Auto requirements have been satisfied. The available space is distributed proportionally between the peer widgets depending on the Value property.
FSizeParam cannot be constructed directly - see FStretch, FStretchContent, FAuto, and FAspectRatio
Definition at line 95 of file SlateStructs.h.
Member Enumeration Documentation
ESizeRule
enum FSizeParam::ESizeRule
Enumerator
SizeRule_Auto
SizeRule_Stretch
SizeRule_StretchContent
Definition at line 97 of file SlateStructs.h.
Constructor & Destructor Documentation
FSizeParam()
FSizeParam::FSizeParam (ESizeRule InTypeOfSize, const TAttribute< float > & InValue, const TAttribute< float > & InShrinkValue) inline protected
Hidden constructor.
Use FAspectRatio, FAuto, FStretch to instantiate size parameters.
See also
FAspectRatio, FAuto, FStretch
Definition at line 131 of file SlateStructs.h.
References ShrinkValue, SizeRule, and Value.
Referenced by FAuto::FAuto(), FStretch::FStretch(), FStretch::FStretch(), FStretchContent::FStretchContent(), FStretchContent::FStretchContent(), and FStretchContent::FStretchContent().
Field Documentation
ShrinkValue
TAttribute<float> FSizeParam::ShrinkValue
The actual value this size parameter stores, used for shrinking.
Treated as unused, if set to negative value.
This value can be driven by a delegate. It is only used for the StretchContent mode.
Definition at line 120 of file SlateStructs.h.
Referenced by FSizeParam(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetShrinkSizeValue(), and TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam().
SizeRule
ESizeRule FSizeParam::SizeRule
The sizing rule to use.
Definition at line 105 of file SlateStructs.h.
Referenced by FSizeParam(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeRule(), and TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam().
Value
TAttribute<float> FSizeParam::Value
The actual value this size parameter stores.
This value can be driven by a delegate. It is only used for the Stretch and StretchContent modes.
Definition at line 112 of file SlateStructs.h.
Referenced by FSizeParam(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeValue(), and TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam().
The documentation for this struct was generated from the following file:
SlateStructs.h