Unreal Engine 5.6 C++ API: TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator Class Reference
TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator Class Reference
Const map iterator.
#include "SortedMap.h"
Public Member Functions
FORCEINLINE TConstReverseIterator (const TSortedMap &InMap)
Public Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< true >
FORCEINLINE FSetElementId GetId () const
FORCEINLINE ItKeyType & Key () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TBaseReverseIterator &Rhs) const
FORCEINLINE PairType & operator* () const
FORCEINLINE TBaseReverseIterator & operator++ ()
FORCEINLINE PairType * operator-> () const
FORCEINLINE bool operator== (const TBaseReverseIterator &Rhs) const
FORCEINLINE ItValueType & Value () const
Additional Inherited Members
Public Types inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< true >
typedef std::conditional_t< bConst, const typename ElementArrayType::ElementType, typename ElementArrayType::ElementType > PairType
Protected Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< true >
FORCEINLINE TBaseReverseIterator (PairType *InData, SizeType InNum)
Protected Attributes inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< true >
PairType * Data
SizeType Index
Detailed Description
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate>
class TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator
Const map iterator.
Definition at line 796 of file SortedMap.h.
Constructor & Destructor Documentation
TConstReverseIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator::TConstReverseIterator (const TSortedMap & InMap) inline nodiscard
Definition at line 799 of file SortedMap.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< true >::TBaseReverseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap, FORCEINLINE, GetData(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Num(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Pairs.
The documentation for this class was generated from the following file:
SortedMap.h