Unreal Engine 5.6 C++ API: FRenderTransform Struct Reference
FRenderTransform Struct Reference
#include "RenderTransform.h"
Public Member Functions
FRenderTransform ()=default
FORCEINLINE FRenderTransform (const FMatrix44d &M)
FORCEINLINE FRenderTransform (const FMatrix44f &M)
FRenderTransform (const FRenderTransform &)=default
FORCEINLINE FRenderTransform (const FVector3f &InXAxis, const FVector3f &InYAxis, const FVector3f &InZAxis, const FVector3f &InOrigin)
FRenderTransform (FRenderTransform &&)=default
FORCEINLINE bool Equals (const FRenderTransform &Other, float Tolerance=UE_KINDA_SMALL_NUMBER) const
FORCEINLINE FVector3f GetScale () const
FORCEINLINE FRenderTransform Inverse () const
FORCEINLINE FRenderTransform InverseFast () const
FORCEINLINE bool IsScaleNonUniform () const
FORCEINLINE FRenderTransform operator* (const FMatrix44f &Other) const
FORCEINLINE FRenderTransform operator* (const FRenderTransform &Other) const
FORCEINLINE FRenderTransform & operator= (const FMatrix44d &From)
FORCEINLINE FRenderTransform & operator= (const FMatrix44f &From)
FRenderTransform & operator= (const FRenderTransform &)=default
FRenderTransform & operator= (FRenderTransform &&)=default
FORCEINLINE void Orthogonalize ()
FORCEINLINE float RotDeterminant () const
FORCEINLINE void SetIdentity ()
FORCEINLINE void To3x4MatrixTranspose (float *Result) const
FORCEINLINE FMatrix ToMatrix () const
FORCEINLINE FMatrix44f ToMatrix44f () const
Data Fields
FVector3f Origin
FVector3f TransformRows [3]
Static Public Attributes
static RENDERCORE_API FRenderTransform Identity
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FRenderTransform &T)
Serializes the render transform.
Detailed Description
Definition at line 22 of file RenderTransform.h.
Constructor & Destructor Documentation
FRenderTransform() [1/6]
FRenderTransform::FRenderTransform () default
Referenced by FRenderTransform(), FRenderTransform(), Equals(), Inverse(), InverseFast(), operator*(), operator*(), operator<<, operator=(), operator=(), operator=(), and operator=().
FRenderTransform() [2/6]
FRenderTransform::FRenderTransform (FRenderTransform &&) default
References FRenderTransform().
FRenderTransform() [3/6]
FRenderTransform::FRenderTransform (const FRenderTransform &) default
References FRenderTransform().
FRenderTransform() [4/6]
FORCEINLINE FRenderTransform::FRenderTransform (const FVector3f & InXAxis, const FVector3f & InYAxis, const FVector3f & InZAxis, const FVector3f & InOrigin) inline
Definition at line 34 of file RenderTransform.h.
References FORCEINLINE, Origin, and TransformRows.
FRenderTransform() [5/6]
FORCEINLINE FRenderTransform::FRenderTransform (const FMatrix44f & M) inline
Definition at line 42 of file RenderTransform.h.
References FORCEINLINE, UE::Math::TMatrix< T >::M, Origin, and TransformRows.
FRenderTransform() [6/6]
FORCEINLINE FRenderTransform::FRenderTransform (const FMatrix44d & M) inline
Definition at line 50 of file RenderTransform.h.
References FORCEINLINE, UE::Math::TMatrix< T >::M, Origin, and TransformRows.
Member Function Documentation
Equals()
FORCEINLINE bool FRenderTransform::Equals (const FRenderTransform & Other, float Tolerance = UE_KINDA_SMALL_NUMBER) const inline
Definition at line 78 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, Origin, Other, TransformRows, and UE_KINDA_SMALL_NUMBER.
GetScale()
FORCEINLINE FVector3f FRenderTransform::GetScale () const inline
Definition at line 202 of file RenderTransform.h.
References FORCEINLINE, Scale, and TransformRows.
Referenced by IsScaleNonUniform().
Inverse()
FORCEINLINE FRenderTransform FRenderTransform::Inverse () const inline
Definition at line 190 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, UE::Math::TMatrix< T >::Inverse(), and ToMatrix44f().
InverseFast()
FORCEINLINE FRenderTransform FRenderTransform::InverseFast () const inline
Definition at line 196 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, UE::Math::TMatrix< T >::InverseFast(), and ToMatrix44f().
IsScaleNonUniform()
FORCEINLINE bool FRenderTransform::IsScaleNonUniform () const inline
Definition at line 212 of file RenderTransform.h.
References FORCEINLINE, GetScale(), FMath::IsNearlyEqual(), and Scale.
Referenced by FInstanceSceneData::ComputeLocalToWorld(), and FInstanceDynamicData::ComputePrevLocalToWorld().
operator*() [1/2]
FORCEINLINE FRenderTransform FRenderTransform::operator* (const FMatrix44f & Other) const inline
Definition at line 175 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, Other, and ToMatrix44f().
operator*() [2/2]
FORCEINLINE FRenderTransform FRenderTransform::operator* (const FRenderTransform & Other) const inline
Definition at line 167 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, Other, and ToMatrix44f().
operator=() [1/4]
FORCEINLINE FRenderTransform & FRenderTransform::operator= (const FMatrix44d & From) inline
Definition at line 68 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, UE::Math::TMatrix< T >::M, Origin, and TransformRows.
operator=() [2/4]
FORCEINLINE FRenderTransform & FRenderTransform::operator= (const FMatrix44f & From) inline
Definition at line 59 of file RenderTransform.h.
References FRenderTransform(), FORCEINLINE, UE::Math::TMatrix< T >::M, Origin, and TransformRows.
operator=() [3/4]
FRenderTransform & FRenderTransform::operator= (const FRenderTransform &) default
References FRenderTransform().
operator=() [4/4]
FRenderTransform & FRenderTransform::operator= (FRenderTransform &&) default
References FRenderTransform().
Orthogonalize()
FORCEINLINE void FRenderTransform::Orthogonalize () inline
Definition at line 223 of file RenderTransform.h.
References FORCEINLINE, TransformRows, X, Y, and Z.
Referenced by FInstanceSceneData::ComputeLocalToWorld(), and FInstanceDynamicData::ComputePrevLocalToWorld().
RotDeterminant()
FORCEINLINE float FRenderTransform::RotDeterminant () const inline
Definition at line 182 of file RenderTransform.h.
References FORCEINLINE, TransformRows, X, Y, and Z.
Referenced by FInstanceSceneShaderData::BuildInternal().
SetIdentity()
FORCEINLINE void FRenderTransform::SetIdentity () inline
Definition at line 244 of file RenderTransform.h.
References FORCEINLINE, Origin, TransformRows, and UE::Math::TVector< float >::ZeroVector.
To3x4MatrixTranspose()
FORCEINLINE void FRenderTransform::To3x4MatrixTranspose (float * Result) const inline
Definition at line 127 of file RenderTransform.h.
References FORCEINLINE, MakeVectorRegisterFloat(), Origin, RESTRICT, TransformRows, VectorCombineHigh(), VectorCombineLow(), VectorDeinterleave(), VectorLoad(), VectorStore(), and X.
Referenced by FInstanceSceneShaderData::BuildInternal().
ToMatrix()
FORCEINLINE FMatrix FRenderTransform::ToMatrix () const inline
Definition at line 122 of file RenderTransform.h.
References FORCEINLINE, and ToMatrix44f().
ToMatrix44f()
FORCEINLINE FMatrix44f FRenderTransform::ToMatrix44f () const inline
Definition at line 87 of file RenderTransform.h.
References FORCEINLINE, MakeVectorRegisterFloat(), Matrix, Origin, RESTRICT, TransformRows, VectorLoad(), VectorSet_W0(), VectorStore(), and X.
Referenced by Inverse(), InverseFast(), operator*(), operator*(), and ToMatrix().
Friends And Related Symbol Documentation
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FRenderTransform & T) friend
Serializes the render transform.
Parameters
Ar Reference to the serialization archive.
T Reference to the render transform being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 259 of file RenderTransform.h.
References FRenderTransform(), Ar, and FORCEINLINE.
Field Documentation
Identity
RENDERCORE_API FRenderTransform FRenderTransform::Identity static
Definition at line 268 of file RenderTransform.h.
Origin
FVector3f FRenderTransform::Origin
Definition at line 25 of file RenderTransform.h.
Referenced by FCompressedTransform::FCompressedTransform(), FRenderTransform(), FRenderTransform(), FRenderTransform(), Equals(), operator=(), operator=(), SetIdentity(), To3x4MatrixTranspose(), ToMatrix44f(), and FCompressedTransform::ToRenderTransform().
TransformRows
FVector3f FRenderTransform::TransformRows[3]
Definition at line 24 of file RenderTransform.h.
Referenced by FCompressedTransform::FCompressedTransform(), FRenderTransform(), FRenderTransform(), FRenderTransform(), Equals(), GetScale(), operator=(), operator=(), Orthogonalize(), RotDeterminant(), SetIdentity(), To3x4MatrixTranspose(), ToMatrix44f(), and FCompressedTransform::ToRenderTransform().
The documentation for this struct was generated from the following file:
RenderTransform.h