Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... > Struct Template Reference
UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... > Struct Template Reference
#include "MovieScenePropertyComponentHandler.h"
Public Types
using CompleteSetterTask = std::conditional_t<bIsComposite, TSetCompositePropertyValues<PropertyTraits, CompositeTypes...>, TSetPropertyValues<PropertyTraits>>
using PreAnimatedStorageType = TPreAnimatedPropertyStorage<PropertyTraits>
using StorageType = typename PropertyTraits::StorageType
Public Member Functions
TPropertyComponentHandlerImpl ()
virtual void DispatchSetterTasks (const FPropertyDefinition &Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const FPropertyStats &Stats, FSystemTaskPrerequisites &InPrerequisites, FSystemSubsequentTasks &Subsequents, UMovieSceneEntitySystemLinker *Linker)
virtual TSharedPtr< IPreAnimatedStorage > GetPreAnimatedStateStorage (const FPropertyDefinition &Definition, FPreAnimatedStateExtension *Container) override
Retrieve the pre-animated storage for the property that this handler represents.
virtual TSharedPtr< IInitialValueProcessor > MakeInitialValueProcessor (const FPropertyDefinition &Definition) override
Retrieve an initial value processor interface for this property type.
virtual void RebuildOperational (const FPropertyDefinition &PropertyDefinition, TArrayView< const FPropertyCompositeDefinition > Composites, const TArrayView< FMovieSceneEntityID > &EntityIDs, UMovieSceneEntitySystemLinker *Linker, FPropertyComponentArrayView OutResult) override
Rebuild operational values from the given entities.
virtual void RecomposeBlendChannel (const FPropertyDefinition &PropertyDefinition, TArrayView< const FPropertyCompositeDefinition > Composites, int32 CompositeIndex, const FValueDecompositionParams &InParams, UMovieSceneBlenderSystem *Blender, double InCurrentValue, TArrayView< double > OutResults) override
Run a recomposition using the specified params and values.
void RecomposeBlendImpl (const FPropertyDefinition &PropertyDefinition, TArrayView< const FPropertyCompositeDefinition > Composites, const FValueDecompositionParams &InParams, UMovieSceneBlenderSystem *Blender, const StorageType &InCurrentValue, TArrayView< StorageType > OutResults)
virtual void RecomposeBlendOperational (const FPropertyDefinition &PropertyDefinition, TArrayView< const FPropertyCompositeDefinition > Composites, const FValueDecompositionParams &InParams, UMovieSceneBlenderSystem *Blender, FConstPropertyComponentView InCurrentValue, FPropertyComponentArrayView OutResult) override
Run a recomposition using the specified params and values.
virtual void ScheduleSetterTasks (const FPropertyDefinition &Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const FPropertyStats &Stats, IEntitySystemScheduler *TaskScheduler, UMovieSceneEntitySystemLinker *Linker)
Dispatch tasks that apply any entity that matches this property type to their final values.
Public Member Functions inherited from UE::MovieScene::IPropertyComponentHandler
virtual ~IPropertyComponentHandler ()
virtual void DispatchInitializePropertyMetaDataTasks (const FPropertyDefinition &Definition, FSystemTaskPrerequisites &InPrerequisites, FSystemSubsequentTasks &Subsequents, UMovieSceneEntitySystemLinker *Linker)
Dispatch tasks that cache a pre-animated value for any entities that have the CachePreAnimatedState tag.
Data Fields
TAutoRegisterPreAnimatedStorageID< PreAnimatedStorageType > StorageID
Static Public Attributes
static constexpr bool bIsComposite = IsCompositePropertyTraits((PropertyTraits*)nullptr)
Detailed Description
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices>
struct UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >
Definition at line 341 of file MovieScenePropertyComponentHandler.h.
Member Typedef Documentation
CompleteSetterTask
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> using UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::CompleteSetterTask = std::conditional_t<bIsComposite, TSetCompositePropertyValues<PropertyTraits, CompositeTypes...>, TSetPropertyValues<PropertyTraits>>
Definition at line 346 of file MovieScenePropertyComponentHandler.h.
PreAnimatedStorageType
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> using UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::PreAnimatedStorageType = TPreAnimatedPropertyStorage<PropertyTraits>
Definition at line 348 of file MovieScenePropertyComponentHandler.h.
StorageType
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> using UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::StorageType = typename PropertyTraits::StorageType
Definition at line 345 of file MovieScenePropertyComponentHandler.h.
Constructor & Destructor Documentation
TPropertyComponentHandlerImpl()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::TPropertyComponentHandlerImpl () inline
Definition at line 352 of file MovieScenePropertyComponentHandler.h.
Member Function Documentation
DispatchSetterTasks()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks (const FPropertyDefinition & Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const FPropertyStats & Stats, FSystemTaskPrerequisites & InPrerequisites, FSystemSubsequentTasks & Subsequents, UMovieSceneEntitySystemLinker * Linker) inline virtual
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 412 of file MovieScenePropertyComponentHandler.h.
References bIsComposite, UE::MovieScene::FBuiltInComponentTypes::BoundObject, UE::MovieScene::FBuiltInComponentTypes::CustomPropertyIndex, UE::MovieScene::FPropertyDefinition::CustomPropertyRegistration, UE::MovieScene::FBuiltInComponentTypes::FastPropertyOffset, UE::MovieScene::TEntityTaskComponents< T >::FilterAll(), UE::MovieScene::TEntityTaskComponents< T >::FilterAny(), UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FPropertyDefinition::GetMetaDataComponent(), UE::MovieScene::FBuiltInComponentTypes::Ignored, UE::MovieScene::FPropertyDefinition::PropertyType, UE::MovieScene::FComponentMask::Set(), UE::MovieScene::FBuiltInComponentTypes::SlowProperty, UE::MovieScene::FPropertyDefinition::StatID, and UE::MovieScene::FBuiltInComponentTypes::Tags.
GetPreAnimatedStateStorage()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual TSharedPtr< IPreAnimatedStorage > UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::GetPreAnimatedStateStorage (const FPropertyDefinition & Definition, FPreAnimatedStateExtension * Container) inline override virtual
Retrieve the pre-animated storage for the property that this handler represents.
Parameters
Definition The property definition this handler was registered for
Container The Pre-Animated state container extension that owns all pre-anim state for this evaluation
Reimplemented from UE::MovieScene::IPropertyComponentHandler.
Definition at line 356 of file MovieScenePropertyComponentHandler.h.
References Container, MakeShared(), and StorageID.
MakeInitialValueProcessor()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual TSharedPtr< IInitialValueProcessor > UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::MakeInitialValueProcessor (const FPropertyDefinition & Definition) inline override virtual
Retrieve an initial value processor interface for this property type.
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 455 of file MovieScenePropertyComponentHandler.h.
References UE::MovieScene::FPropertyDefinition::CustomPropertyRegistration, UE::MovieScene::FPropertyDefinition::InitialValueType, MakeShared(), UE::MovieScene::FPropertyDefinition::MetaDataTypes, and UE::MovieScene::FComponentTypeID::ReinterpretCast().
RebuildOperational()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RebuildOperational (const FPropertyDefinition & Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const TArrayView< FMovieSceneEntityID > & EntityIDs, UMovieSceneEntitySystemLinker * Linker, FPropertyComponentArrayView OutResult) inline override virtual
Rebuild operational values from the given entities.
These entities are expected to store the value type's composite values.
Parameters
Definition The property definition this handler was registered for
Composites The composite channels that this property type comproses
EntityIDs The entities on which the composite values will be found
Linker The linker that owns the entity manager where the entities live
OutResult The result to receieve rebuilt values, one for every entitiy in EntityIDs. Must be of type StorageType.
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 604 of file MovieScenePropertyComponentHandler.h.
References check, Location, TArrayView< InElementType, InSizeType >::Num(), UE::MovieScene::PatchCompositeValue(), and UE::MovieScene::FPropertyComponentArrayView::ReinterpretCast().
RecomposeBlendChannel()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendChannel (const FPropertyDefinition & Definition, TArrayView< const FPropertyCompositeDefinition > Composites, int32 CompositeIndex, const FValueDecompositionParams & Params, UMovieSceneBlenderSystem * Blender, double InCurrentValue, TArrayView< double > OutResults) inline override virtual
Run a recomposition using the specified params and values.
Parameters
Definition The property definition this handler was registered for
Composite The composite channel of the property type that we want to decompose
Params The decomposition parameters
Blender The blender system to recompose from
InCurrentValue The current value (of type StorageType) to recompose using. For instance, if a property comprises 3 additive values (a:1, b:2, c:3), and we recompose 'a' with an InCurrentValue of 10, the result for 'a' would be 5.
OutResults The result to receieve recomposed values, one for every entitiy in Params.Query.Entities.
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 547 of file MovieScenePropertyComponentHandler.h.
References UE::MovieScene::TComponentPtr< T >::AsPtr(), Cast(), check, UE::MovieScene::FPropertyDefinition::DoubleCompositeMask, UE::MovieScene::FDecompositionQuery::Entities, ENamedThreads::GameThread, FTaskGraphInterface::Get(), UE::MovieScene::FPropertyDefinition::InitialValueType, TArrayView< InElementType, InSizeType >::Num(), UE::MovieScene::FValueDecompositionParams::PropertyEntityID, UE::MovieScene::FValueDecompositionParams::Query, UE::MovieScene::FComponentTypeID::ReinterpretCast(), UE::MovieScene::FValueDecompositionParams::ResultComponentType, and FTaskGraphInterface::WaitUntilTaskCompletes().
RecomposeBlendImpl()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendImpl (const FPropertyDefinition & PropertyDefinition, TArrayView< const FPropertyCompositeDefinition > Composites, const FValueDecompositionParams & InParams, UMovieSceneBlenderSystem * Blender, const StorageType & InCurrentValue, TArrayView< StorageType > OutResults) inline
Definition at line 469 of file MovieScenePropertyComponentHandler.h.
References UE::MovieScene::TComponentPtr< T >::AsPtr(), Cast(), check, UE::MovieScene::FPropertyDefinition::DoubleCompositeMask, UE::MovieScene::FDecompositionQuery::Entities, ENamedThreads::GameThread, FTaskGraphInterface::Get(), UE::MovieScene::FPropertyDefinition::InitialValueType, TArrayView< InElementType, InSizeType >::Num(), UE::MovieScene::FValueDecompositionParams::PropertyEntityID, UE::MovieScene::FValueDecompositionParams::Query, UE::MovieScene::FComponentTypeID::ReinterpretCast(), UE::MovieScene::FValueDecompositionParams::ResultComponentType, and FTaskGraphInterface::WaitUntilTasksComplete().
Referenced by RecomposeBlendOperational().
RecomposeBlendOperational()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendOperational (const FPropertyDefinition & Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const FValueDecompositionParams & Params, UMovieSceneBlenderSystem * Blender, FConstPropertyComponentView InCurrentValue, FPropertyComponentArrayView OutResult) inline override virtual
Run a recomposition using the specified params and values.
The current value and result views must be of type StorageType
Parameters
Definition The property definition this handler was registered for
Composites The composite channels that this property type comprises
Params The decomposition parameters
Blender The blender system to recompose from
InCurrentValue The current value (of type StorageType) to recompose using. For instance, if a property comprises 3 additive values (a:1, b:2, c:3), and we recompose 'a' with an InCurrentValue of 10, the result for 'a' would be 5.
OutResult The result to receieve recomposed values, one for every entitiy in Params.Query.Entities. Must be of type StorageType.
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 464 of file MovieScenePropertyComponentHandler.h.
References RecomposeBlendImpl(), UE::MovieScene::FConstPropertyComponentView::ReinterpretCast(), and UE::MovieScene::FPropertyComponentArrayView::ReinterpretCast().
ScheduleSetterTasks()
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> virtual void UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks (const FPropertyDefinition & Definition, TArrayView< const FPropertyCompositeDefinition > Composites, const FPropertyStats & Stats, IEntitySystemScheduler * TaskScheduler, UMovieSceneEntitySystemLinker * Linker) inline virtual
Dispatch tasks that apply any entity that matches this property type to their final values.
Parameters
Definition The property definition this handler was registered for
Composites The composite channels that this property type comprises
Stats Stats pertaining to the entities that currently exist in the entity manager
InPrerequisites Task prerequisites for any entity system tasks that are dispatched
Subsequents Subsequents to add any dispatched tasks to
Linker The linker that owns the entity manager to dispatch tasks for
Implements UE::MovieScene::IPropertyComponentHandler.
Definition at line 369 of file MovieScenePropertyComponentHandler.h.
References bIsComposite, UE::MovieScene::FBuiltInComponentTypes::BoundObject, UE::MovieScene::FBuiltInComponentTypes::CustomPropertyIndex, UE::MovieScene::FPropertyDefinition::CustomPropertyRegistration, UE::MovieScene::FBuiltInComponentTypes::FastPropertyOffset, UE::MovieScene::TEntityTaskComponents< T >::FilterAll(), UE::MovieScene::TEntityTaskComponents< T >::FilterAny(), UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FPropertyDefinition::GetMetaDataComponent(), UE::MovieScene::FBuiltInComponentTypes::Ignored, UE::MovieScene::FPropertyDefinition::PropertyType, UE::MovieScene::FComponentMask::Set(), UE::MovieScene::FBuiltInComponentTypes::SlowProperty, UE::MovieScene::FPropertyDefinition::StatID, and UE::MovieScene::FBuiltInComponentTypes::Tags.
Field Documentation
bIsComposite
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> bool UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::bIsComposite = IsCompositePropertyTraits((PropertyTraits*)nullptr) static constexpr
Definition at line 343 of file MovieScenePropertyComponentHandler.h.
Referenced by DispatchSetterTasks(), and ScheduleSetterTasks().
StorageID
template<typename PropertyTraits, typename ... MetaDataTypes, int ... MetaDataIndices, typename ... CompositeTypes, int ... CompositeIndices> TAutoRegisterPreAnimatedStorageID<PreAnimatedStorageType> UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::StorageID
Definition at line 350 of file MovieScenePropertyComponentHandler.h.
Referenced by GetPreAnimatedStateStorage().
The documentation for this struct was generated from the following file:
MovieScenePropertyComponentHandler.h