Unreal Engine 5.6 C++ API: FBlueprintContext Class Reference
FBlueprintContext Class Reference
#include "Script.h"
Public Member Functions
FBlueprintContext ()
FVirtualStackAllocator * GetVirtualStackAllocator ()
Static Public Member Functions
static FBlueprintContext * GetThreadSingleton ()
Private Attributes
FVirtualStackAllocator VirtualStackAllocator
Detailed Description
Definition at line 73 of file Script.h.
Constructor & Destructor Documentation
FBlueprintContext()
FBlueprintContext::FBlueprintContext ()
Referenced by GetThreadSingleton().
Member Function Documentation
GetThreadSingleton()
FBlueprintContext * FBlueprintContext::GetThreadSingleton () static
References FBlueprintContext().
Referenced by FFrame::FFrame().
GetVirtualStackAllocator()
FVirtualStackAllocator * FBlueprintContext::GetVirtualStackAllocator () inline
Definition at line 81 of file Script.h.
References VirtualStackAllocator.
Referenced by FFrame::FFrame().
Field Documentation
VirtualStackAllocator
FVirtualStackAllocator FBlueprintContext::VirtualStackAllocator private
Definition at line 85 of file Script.h.
Referenced by GetVirtualStackAllocator().
The documentation for this class was generated from the following file:
Script.h