Unreal Engine 5.6 C++ API: SWidget.h File Reference
SWidget.h File Reference
#include "CoreMinimal.h"
#include "Misc/Attribute.h"
#include "Misc/FrameValue.h"
#include "Stats/Stats.h"
#include "Styling/SlateColor.h"
#include "Layout/SlateRect.h"
#include "Layout/Visibility.h"
#include "Layout/Clipping.h"
#include "Layout/Geometry.h"
#include "Layout/ArrangedWidget.h"
#include "Layout/LayoutGeometry.h"
#include "Layout/Margin.h"
#include "Layout/FlowDirection.h"
#include "Rendering/SlateLayoutTransform.h"
#include "Input/CursorReply.h"
#include "Input/Reply.h"
#include "Input/NavigationReply.h"
#include "Input/PopupMethodReply.h"
#include "Types/ISlateMetaData.h"
#include "Types/WidgetActiveTimerDelegate.h"
#include "Types/WidgetMouseEventsDelegate.h"
#include "Textures/SlateShaderResource.h"
#include "SlateGlobals.h"
#include "Types/PaintArgs.h"
#include "Types/SlateAttribute.h"
#include "Types/SlateVector2.h"
#include "FastUpdate/WidgetProxy.h"
#include "InvalidateWidgetReason.h"
#include "Widgets/SlateControlledConstruction.h"
#include "Widgets/Accessibility/SlateWidgetAccessibleTypes.h"
#include "WidgetPixelSnapping.h"
Data Structures
class FPopupLayer
An FPopupLayer hosts the pop-up content which could be anything you want to appear on top of a widget.
class SWidget
HOW TO DEPRECATE SLATE_ATTRIBUTES.
struct SWidget::TSlateAttribute< InObjectType, InInvalidationReasonValue, InComparePredicate >
A SlateAttribute that is member variable of a SWidget.
struct SWidget::TSlateAttribute< FText, EInvalidateWidgetReason::None >
struct SWidget::TSlateAttribute< FText, InInvalidationReasonValue >
struct SWidget::TSlateAttributeRef< InObjectType, InInvalidationReasonValue, InComparePredicate >
A Reference to a TSlateAttribute.
struct SWidget::TSlateAttributeRef< FText, EInvalidateWidgetReason::None >
struct SWidget::TSlateAttributeRef< FText, InInvalidationReasonValue >
struct SWidget::TSlateManagedAttribute< InObjectType, InInvalidationReasonValue, InComparePredicate >
A SlateAttribute that is NOT a member variable of a SWidget.
struct SWidget::TSlateManagedAttribute< FText, EInvalidateWidgetReason::None >
struct SWidget::TSlateManagedAttribute< FText, InInvalidationReasonValue >
Enumerations
enum class EAccessibleType : uint8 { Main , Summary }
Functions
DECLARE_CYCLE_STAT_EXTERN (TEXT("Execute Active Timers"), STAT_SlateExecuteActiveTimers, STATGROUP_Slate, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("SlatePrepass"), STAT_SlatePrepass, STATGROUP_Slate, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("SWidget MetaData"), STAT_SlateGetMetaData, STATGROUP_Slate, 1)
DECLARE_CYCLE_STAT_EXTERN (TEXT("Tick Widgets"), STAT_SlateTickWidgets, STATGROUP_Slate, 1)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Total Widgets"), STAT_SlateTotalWidgets, STATGROUP_SlateMemory, 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("SWidget::Paint (Count)"), STAT_SlateNumPaintedWidgets, STATGROUP_Slate, 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("SWidget::Tick (Count)"), STAT_SlateNumTickedWidgets, STATGROUP_Slate, 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Widgets Created (Per Frame)"), STAT_SlateTotalWidgetsPerFrame, STATGROUP_Slate, 1)
DECLARE_MEMORY_STAT_EXTERN (TEXT("SWidget Total Allocated Size"), STAT_SlateSWidgetAllocSize, STATGROUP_SlateMemory, 1)
template<typename TargetValueType, typename SourceValueType>
static bool SetWidgetAttribute (SWidget &ThisWidget, TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
template<typename TargetValueType, typename SourceValueType>
bool SetWidgetAttribute (SWidget &ThisWidget, TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Enumeration Type Documentation
EAccessibleType
enum class EAccessibleType : uint8 strong
Enumerator
Main
Summary
Definition at line 66 of file SWidget.h.
Function Documentation
DECLARE_CYCLE_STAT_EXTERN() [1/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("Execute Active Timers") , STAT_SlateExecuteActiveTimers , STATGROUP_Slate , 1)
DECLARE_CYCLE_STAT_EXTERN() [2/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("SlatePrepass") , STAT_SlatePrepass , STATGROUP_Slate , 1)
DECLARE_CYCLE_STAT_EXTERN() [3/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("SWidget MetaData") , STAT_SlateGetMetaData , STATGROUP_Slate , 1)
DECLARE_CYCLE_STAT_EXTERN() [4/4]
DECLARE_CYCLE_STAT_EXTERN (TEXT("Tick Widgets") , STAT_SlateTickWidgets , STATGROUP_Slate , 1)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN()
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Total Widgets") , STAT_SlateTotalWidgets , STATGROUP_SlateMemory , 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [1/3]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("SWidget::Paint (Count)") , STAT_SlateNumPaintedWidgets , STATGROUP_Slate , 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [2/3]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("SWidget::Tick (Count)") , STAT_SlateNumTickedWidgets , STATGROUP_Slate , 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [3/3]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Widgets Created (Per Frame)") , STAT_SlateTotalWidgetsPerFrame , STATGROUP_Slate , 1)
DECLARE_MEMORY_STAT_EXTERN()
DECLARE_MEMORY_STAT_EXTERN (TEXT("SWidget Total Allocated Size") , STAT_SlateSWidgetAllocSize , STATGROUP_SlateMemory , 1)
SetWidgetAttribute() [1/2]
template<typename TargetValueType, typename SourceValueType> bool SetWidgetAttribute (SWidget & ThisWidget, TAttribute< TargetValueType > & TargetValue, const TAttribute< SourceValueType > & SourceValue, EInvalidateWidgetReason BaseInvalidationReason) static
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
So if the boundness of the attribute didn't change volatility won't need to be recalculated. Returns true if the value changed.
Definition at line 1928 of file SWidget.h.
References TAttribute< ObjectType >::IdenticalTo(), SWidget::Invalidate(), TAttribute< ObjectType >::IsBound(), and PaintAndVolatility.
Referenced by SWidget::SetAttribute().
SetWidgetAttribute() [2/2]
template<typename TargetValueType, typename SourceValueType> bool SetWidgetAttribute (SWidget & ThisWidget, TAttribute< TargetValueType > & TargetValue, const TAttribute< SourceValueType > & SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
So if the boundness of the attribute didn't change volatility won't need to be recalculated. Returns true if the value changed.
Definition at line 1928 of file SWidget.h.
References TAttribute< ObjectType >::IdenticalTo(), SWidget::Invalidate(), TAttribute< ObjectType >::IsBound(), and PaintAndVolatility.
Referenced by SWidget::SetAttribute().