Unreal Engine 5.6 C++ API: FDetailsDisplayManager Class Reference
FDetailsDisplayManager Class Reference
An.
#include "DetailsDisplayManager.h"
Public Member Functions
PROPERTYEDITOR_API FDetailsDisplayManager ()
virtual PROPERTYEDITOR_API ~FDetailsDisplayManager ()
virtual PROPERTYEDITOR_API bool AddEmptyCategoryToDetailLayoutIfNeeded (TSharedRef< FComplexPropertyNode > Node, TSharedRef< FDetailLayoutBuilderImpl > DetailLayoutBuilder)
If TSharedRef<FComplexPropertyNode> Node has a valid UObject instance, add an empty properties Category to the DetailLayoutBuilder.
virtual PROPERTYEDITOR_API TSharedRef< SWidget > ConstructDetailTreeOverlay ()
Returns a widget which will be put in an overlay slot which is over the detail tree portion of the widget.
DECLARE_DELEGATE (FResetToDefault)
bool GetCategoryHasAnyUpdatedProperties (FName InCategoryObjectName) const
virtual PROPERTYEDITOR_API TSharedPtr< SWidget > GetCategoryMenu (FName InCategoryObjectName)
Gets the category menu SWidget and returns a shared pointer to it.
PROPERTYEDITOR_API const FDetailsViewStyle * GetDetailsViewStyle () const
Returns the.
virtual PROPERTYEDITOR_API const FDetailsViewStyleKey & GetDetailsViewStyleKey () const
Returns the.
virtual PROPERTYEDITOR_API bool GetIsScrollBarNeeded () const
Returns a bool indicating whether or not the scrollbar is needed on the details view.
FMargin GetTablePadding () const
Returns the FMargin which provides the padding around the whole details view table.
virtual PROPERTYEDITOR_API TOptional< bool > OverrideCreateCategoryNodes () const
void SetIsOuterCategory (bool bInIsOuterCategory)
sets whether the currently active category is an Outer category
virtual PROPERTYEDITOR_API void SetIsScrollBarNeeded (bool bInIsScrollBarNeeded)
Set a bool indicating whether or not the scrollbar is needed on the details view.
virtual PROPERTYEDITOR_API bool ShouldHideComponentEditor ()
Returns a boolean indicating if the Component Editor should be hidden.
virtual PROPERTYEDITOR_API bool ShouldShowCategoryMenu ()
Returns a.
virtual PROPERTYEDITOR_API bool ShowEmptyCategoryIfRootUObjectHasNoPropertyData (UObject *InNode) const
Returns true if the specified UObject is a Root Node Object and should show an empty Category stub even if it has no UProperty Data, else it returns false.
virtual PROPERTYEDITOR_API bool SupportsDetailTreeOverlay () const
Returns whether or not this display manager provides a widget to overlay over the detail tree.
UE_DEPRECATED (5.5, "Experimental API") PROPERTYEDITOR_API virtual bool CanConstructPropertyUpdatedWidgetBuilder() const
If returning true, the row widgets (ie.
UE_DEPRECATED (5.5, "Experimental API") PROPERTYEDITOR_API virtual TSharedPtr< FPropertyUpdatedWidgetBuilder > ConstructPropertyUpdatedWidgetBuilder(const FConstructPropertyUpdatedWidgetBuilderArgs &Args)
Returns a builder class which will generate a widget in place of the Extension widgets on an item row.
UE_DEPRECATED (5.5, "Use ConstructPropertyUpdatedWidgetBuilder") PROPERTYEDITOR_API virtual TSharedPtr< FPropertyUpdatedWidgetBuilder > GetPropertyUpdatedWidget(FResetToDefault ResetToDefault
Returns a widget which will show in place of the reset to default button, or a nullptr if the default reset button should be used.
UE_DEPRECATED (5.5, "Use ConstructPropertyUpdatedWidgetBuilder") PROPERTYEDITOR_API virtual TSharedPtr< FPropertyUpdatedWidgetBuilder > GetPropertyUpdatedWidget(FResetToDefault ResetToDefault
Returns a widget which will show in place of the reset to default button, or a nullptr if the default reset button should be used.
void UpdatePropertyForCategory (FName InCategoryObjectName, FProperty *Property, bool bAddProperty)
PROPERTYEDITOR_API void UpdateView () const
Updates the current details view.
Public Member Functions inherited from TSharedFromThis< FDetailsDisplayManager >
TSharedRef< FDetailsDisplayManager, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDetailsDisplayManager, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static PROPERTYEDITOR_API bool GetForceShowSubObjectEditor ()
Returns a boolean indicating whether the sub-object editor should show regardless of any object filter preference settings this would override any value retrieved from ShouldHideComponentEditor.
Data Fields
bool bIsCategoryUpdateWidget = false
bool FName InCategoryObjectName = NAME_None)
TSharedRef< FEditPropertyChain > FName InCategoryObjectName
TSharedRef< FEditPropertyChain > InEditorPropertyChain
FOnDetailsNeedsUpdate OnDetailsNeedsUpdate
Protected Attributes
bool bIsOuterCategory
A bool indicating whether or not the currently active category is an outer category.
bool bIsScrollBarNeeded = false
a bool indicating whether or not the scrollbar is needed on the details view.
TMap< FName, TSet< FProperty * > > CategoryNameToUpdatePropertySetMap
A map of category object name to a set of properties that has been updated for it.
FDetailsViewStyleKey PrimaryStyleKey
The primary style key for the details view.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FDetailsDisplayManager >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDetailsDisplayManager >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
An.
FDetailsDisplayManager
provides an API to tweak various settings of your details view, and provides some utility methods to work with Details.
Definition at line 21 of file DetailsDisplayManager.h.
Constructor & Destructor Documentation
FDetailsDisplayManager()
PROPERTYEDITOR_API FDetailsDisplayManager::FDetailsDisplayManager ()
~FDetailsDisplayManager()
virtual PROPERTYEDITOR_API FDetailsDisplayManager::~FDetailsDisplayManager () virtual
Member Function Documentation
AddEmptyCategoryToDetailLayoutIfNeeded()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::AddEmptyCategoryToDetailLayoutIfNeeded (TSharedRef< FComplexPropertyNode > Node, TSharedRef< FDetailLayoutBuilderImpl > DetailLayoutBuilder) virtual
If TSharedRef<FComplexPropertyNode> Node has a valid UObject instance, add an empty properties Category to the DetailLayoutBuilder.
Parameters
Node the FComplexPropertyNode that wil be added as a property to the new Category
DetailLayoutBuilder The FDetailLayoutBuilderImpl that will have a stub category added to it
Returns
true if the Category was successfully added to FDetailLayoutBuilderImpl& DetailLayoutBuilder, else it returns false
ConstructDetailTreeOverlay()
virtual PROPERTYEDITOR_API TSharedRef< SWidget > FDetailsDisplayManager::ConstructDetailTreeOverlay () virtual
Returns a widget which will be put in an overlay slot which is over the detail tree portion of the widget.
Note
Implementations must manage hit test visibility of the supplied widget carefully to prevent blocking UI interactions with the detail tree widgets.
DECLARE_DELEGATE()
FDetailsDisplayManager::DECLARE_DELEGATE (FResetToDefault)
GetCategoryHasAnyUpdatedProperties()
bool FDetailsDisplayManager::GetCategoryHasAnyUpdatedProperties (FName InCategoryObjectName) const
References GetCategoryHasAnyUpdatedProperties(), and InCategoryObjectName.
Referenced by GetCategoryHasAnyUpdatedProperties().
GetCategoryMenu()
virtual PROPERTYEDITOR_API TSharedPtr< SWidget > FDetailsDisplayManager::GetCategoryMenu (FName InCategoryObjectName) virtual
Gets the category menu SWidget and returns a shared pointer to it.
Parameters
InCategoryObjectName the name of the category
References InCategoryObjectName.
GetDetailsViewStyle()
PROPERTYEDITOR_API const FDetailsViewStyle * FDetailsDisplayManager::GetDetailsViewStyle () const
Returns the.
FDetailsViewStyle
that is the current FDetailsViewStyle style
GetDetailsViewStyleKey()
virtual PROPERTYEDITOR_API const FDetailsViewStyleKey & FDetailsDisplayManager::GetDetailsViewStyleKey () const virtual
Returns the.
FDetailsViewStyleKey
that is the Key to the current FDetailsViewStyle style
GetForceShowSubObjectEditor()
PROPERTYEDITOR_API bool FDetailsDisplayManager::GetForceShowSubObjectEditor () static
Returns a boolean indicating whether the sub-object editor should show regardless of any object filter preference settings this would override any value retrieved from ShouldHideComponentEditor.
GetIsScrollBarNeeded()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::GetIsScrollBarNeeded () const virtual
Returns a bool indicating whether or not the scrollbar is needed on the details view.
Note that the "needed" here means that in this value the work has been done to figure out if the scrollbar should show, and anything can query this to see if it needs to alter the display accordingly
GetTablePadding()
FMargin FDetailsDisplayManager::GetTablePadding () const
Returns the FMargin which provides the padding around the whole details view table.
OverrideCreateCategoryNodes()
virtual PROPERTYEDITOR_API TOptional< bool > FDetailsDisplayManager::OverrideCreateCategoryNodes () const virtual
SetIsOuterCategory()
void FDetailsDisplayManager::SetIsOuterCategory (bool bInIsOuterCategory)
sets whether the currently active category is an Outer category
SetIsScrollBarNeeded()
virtual PROPERTYEDITOR_API void FDetailsDisplayManager::SetIsScrollBarNeeded (bool bInIsScrollBarNeeded) virtual
Set a bool indicating whether or not the scrollbar is needed on the details view.
Note that the "needed" here means that in this value the work has been done to figure out if the scrollbar should show, and anything can query this to see if it needs to alter the display accordingly
Parameters
bInIsScrollBarNeeded a bool indicating whether or not the scrollbar is Needed on the details view
ShouldHideComponentEditor()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::ShouldHideComponentEditor () virtual
Returns a boolean indicating if the Component Editor should be hidden.
ShouldShowCategoryMenu()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::ShouldShowCategoryMenu () virtual
Returns a.
bool
indicating whether this
DetailsViewObjectFilter
instance should show a category menu
ShowEmptyCategoryIfRootUObjectHasNoPropertyData()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::ShowEmptyCategoryIfRootUObjectHasNoPropertyData (UObject * InNode) const virtual
Returns true if the specified UObject is a Root Node Object and should show an empty Category stub even if it has no UProperty Data, else it returns false.
Parameters
InNode the
UObject*
which will be tested to see if it needs an empty category stub
References ShowEmptyCategoryIfRootUObjectHasNoPropertyData().
Referenced by ShowEmptyCategoryIfRootUObjectHasNoPropertyData().
SupportsDetailTreeOverlay()
virtual PROPERTYEDITOR_API bool FDetailsDisplayManager::SupportsDetailTreeOverlay () const inline virtual
Returns whether or not this display manager provides a widget to overlay over the detail tree.
This can be used to facilitate interactions like drag and drop.
Definition at line 100 of file DetailsDisplayManager.h.
UE_DEPRECATED() [1/4]
FDetailsDisplayManager::UE_DEPRECATED (5. 5, "Experimental API") const
If returning true, the row widgets (ie.
SDetailSingleItemRow, SDetailCategoryTableRow) will call ConstructPropertyUpdatedWidgetBuilder. Enables potentially expensive setup to be elided
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FDetailsDisplayManager::UE_DEPRECATED (5. 5, "Experimental API") const &
Returns a builder class which will generate a widget in place of the Extension widgets on an item row.
For non-item rows (ie. category), a widget will be placed in the same location
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FDetailsDisplayManager::UE_DEPRECATED (5. 5, "Use ConstructPropertyUpdatedWidgetBuilder")
Returns a widget which will show in place of the reset to default button, or a nullptr if the default reset button should be used.
Parameters
ResetToDefault the delegate which should be called to reset the row to default
bIsCategoryUpdateWidget if true this widget builder is for a Category instead of a property within
InCategoryObjectName the name of the UObject associated with the Category for the widget builder, if one exists, else it is NAME_NONE
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FDetailsDisplayManager::UE_DEPRECATED (5. 5, "Use ConstructPropertyUpdatedWidgetBuilder")
Returns a widget which will show in place of the reset to default button, or a nullptr if the default reset button should be used.
Parameters
ResetToDefault the delegate which should be called to reset the row to default
InEditorPropertyChain the FEditorPropertyChain for the FPropertyNode whose state is visualized by this property updated widget
InCategoryObjectName the name of the UObject for which the Category is displayed, if one is associated with the Category
References UE_DEPRECATED().
UpdatePropertyForCategory()
void FDetailsDisplayManager::UpdatePropertyForCategory (FName InCategoryObjectName, FProperty * Property, bool bAddProperty)
References InCategoryObjectName, Property, and UpdatePropertyForCategory().
Referenced by UpdatePropertyForCategory().
UpdateView()
PROPERTYEDITOR_API void FDetailsDisplayManager::UpdateView () const
Updates the current details view.
Field Documentation
bIsCategoryUpdateWidget
bool FDetailsDisplayManager::bIsCategoryUpdateWidget = false
Definition at line 128 of file DetailsDisplayManager.h.
bIsOuterCategory
bool FDetailsDisplayManager::bIsOuterCategory protected
A bool indicating whether or not the currently active category is an outer category.
Definition at line 177 of file DetailsDisplayManager.h.
bIsScrollBarNeeded
bool FDetailsDisplayManager::bIsScrollBarNeeded = false protected
a bool indicating whether or not the scrollbar is needed on the details view.
Note that the "needed" here means that in this value the work has been done to figure out if the scrollbar should show
Definition at line 183 of file DetailsDisplayManager.h.
CategoryNameToUpdatePropertySetMap
TMap<FName, TSet<FProperty*> > FDetailsDisplayManager::CategoryNameToUpdatePropertySetMap protected
A map of category object name to a set of properties that has been updated for it.
Definition at line 186 of file DetailsDisplayManager.h.
InCategoryObjectName [1/2]
bool FName FDetailsDisplayManager::InCategoryObjectName = NAME_None)
Definition at line 128 of file DetailsDisplayManager.h.
Referenced by GetCategoryHasAnyUpdatedProperties(), GetCategoryMenu(), and UpdatePropertyForCategory().
InCategoryObjectName [2/2]
TSharedRef<FEditPropertyChain> FName FDetailsDisplayManager::InCategoryObjectName
Definition at line 138 of file DetailsDisplayManager.h.
InEditorPropertyChain
TSharedRef<FEditPropertyChain> FDetailsDisplayManager::InEditorPropertyChain
Definition at line 138 of file DetailsDisplayManager.h.
OnDetailsNeedsUpdate
FOnDetailsNeedsUpdate FDetailsDisplayManager::OnDetailsNeedsUpdate
Definition at line 26 of file DetailsDisplayManager.h.
PrimaryStyleKey
FDetailsViewStyleKey FDetailsDisplayManager::PrimaryStyleKey protected
The primary style key for the details view.
Definition at line 172 of file DetailsDisplayManager.h.
The documentation for this class was generated from the following file:
DetailsDisplayManager.h