Unreal Engine 5.6 C++ API: PropertyPath.h File Reference
PropertyPath.h File Reference
#include "CoreMinimal.h"
#include "UObject/UnrealType.h"
#include "UObject/WeakFieldPtr.h"
Data Structures
struct FPropertyInfo
class FPropertyPath
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
Functions
FORCEINLINE uint32 GetTypeHash (FPropertyPath const &Path)
FORCEINLINE bool operator!= (const FPropertyPath &LHS, const FPropertyPath &RHS)
FORCEINLINE bool operator== (const FPropertyPath &LHS, const FPropertyPath &RHS)
Function Documentation
GetTypeHash()
FORCEINLINE uint32 GetTypeHash (FPropertyPath const & Path)
Definition at line 238 of file PropertyPath.h.
References end(), FORCEINLINE, GetTypeHash(), and Path.
Referenced by GetTypeHash().
operator!=()
FORCEINLINE bool operator!= (const FPropertyPath & LHS, const FPropertyPath & RHS)
Definition at line 233 of file PropertyPath.h.
References FORCEINLINE.
operator==()
FORCEINLINE bool operator== (const FPropertyPath & LHS, const FPropertyPath & RHS)
Definition at line 215 of file PropertyPath.h.
References end(), FORCEINLINE, FPropertyPath::GetNumProperties(), and FPropertyPath::GetPropertyInfo().