Unreal Engine 5.6 C++ API: FWeakObjectPtr Struct Reference
FWeakObjectPtr Struct Reference
FWeakObjectPtr is a weak pointer to a UObject.
#include "WeakObjectPtr.h"
Public Member Functions
FWeakObjectPtr ()=default
FWeakObjectPtr (const FWeakObjectPtr &Other)=default
Construct from another weak pointer.
FORCEINLINE FWeakObjectPtr (const UObject *Object)
FORCEINLINE FWeakObjectPtr (FObjectPtr Object)
Construct from an object pointer or something that can be implicitly converted to an object pointer.
template<typename T>
FORCEINLINE FWeakObjectPtr (TObjectPtr< T > Object)
FORCEINLINE FWeakObjectPtr (TYPE_OF_NULLPTR)
class UObject * Get () const
Dereference the weak pointer.
class UObject * Get (bool bEvenIfGarbage) const
Dereference the weak pointer.
class UObject * GetEvenIfUnreachable () const
Dereference the weak pointer even if it is marked as Garbage or Unreachable.
FORCEINLINE uint32 GetTypeHash () const
Hash function.
FORCEINLINE bool HasSameIndexAndSerialNumber (const FWeakObjectPtr &Other) const
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
FORCEINLINE bool IsExplicitlyNull () const
Returns true if this pointer was explicitly assigned to null, was reset, or was never initialized.
FORCEINLINE bool IsRemote () const
bool IsStale (bool bIncludingGarbage=true, bool bThreadsafeTest=false) const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
bool IsValid () const
Test if this points to a live UObject.
bool IsValid (bool bEvenIfGarbage, bool bThreadsafeTest=false) const
Test if this points to a live UObject This should be done only when needed as excess resolution of the underlying pointer can cause performance issues.
operator bool () const =delete
FORCEINLINE bool operator!= (const FWeakObjectPtr &Other) const
Compare weak pointers for inequality.
FWeakObjectPtr & operator= (const FWeakObjectPtr &Other)=default
Construct from another weak pointer.
FORCEINLINE void operator= (const UObject *Object)
void operator= (FObjectPtr Object)
Copy from an object pointer.
template<typename T>
FORCEINLINE void operator= (TObjectPtr< T > Object)
FORCEINLINE bool operator== (const FWeakObjectPtr &Other) const
Compare weak pointers for equality.
class TStrongObjectPtr< UObject > Pin () const
Get a strong object ptr to the weak pointer.
class TStrongObjectPtr< UObject > Pin (bool bEvenIfGarbage) const
Get a strong object ptr to the weak pointer.
class TStrongObjectPtr< UObject > PinEvenIfUnreachable () const
FORCEINLINE void Reset ()
Reset the weak pointer back to the null state.
void Serialize (FArchive &Ar)
Weak object pointer serialization.
class TStrongObjectPtr< UObject > TryPin (bool &bOutPinValid) const
Attempt to get a strong object ptr to the weak pointer, but only if garbage collection is not in progress.
class TStrongObjectPtr< UObject > TryPin (bool &bOutPinValid, bool bEvenIfGarbage) const
Attempt to get a strong object ptr to the weak pointer, but only if garbage collection is not in progress.
bool TryPinEvenIfUnreachable (class TStrongObjectPtr< UObject > &OutResult) const
UE_DEPRECATED (5.6, "Constructing a FWeakObjectPtr from NULL has been deprecated - please use nullptr instead.") FORCEINLINE FWeakObjectPtr(int)
Protected Member Functions
UE_DEPRECATED (5.1, "GetObjectIndex is now deprecated, and will be removed.") FORCEINLINE int32 GetObjectIndex() const
Private Member Functions
FORCEINLINE int32 GetObjectIndex_Private () const
FORCEINLINE_DEBUGGABLE UObject * Internal_Get (bool bEvenIfGarbage) const
Private (inlined) version for internal use only.
FORCEINLINE FUObjectItem * Internal_GetObjectItem () const
FORCEINLINE_DEBUGGABLE bool Internal_IsValid (bool bEvenIfGarbage, bool bThreadsafeTest) const
Private (inlined) version for internal use only.
TStrongObjectPtr< UObject > Internal_Pin (bool bEvenIfGarbage) const
TStrongObjectPtr< UObject > Internal_TryPin (bool &bOutPinValid, bool bEvenIfGarbage) const
FORCEINLINE_DEBUGGABLE bool SerialNumbersMatch () const
internal function to test for serial number matches
FORCEINLINE_DEBUGGABLE bool SerialNumbersMatch (FUObjectItem *ObjectItem) const
Private Attributes
int32 ObjectIndex = UE::Core::Private::InvalidWeakObjectIndex
int32 ObjectSerialNumber = 0
Friends
struct FObjectKey
template<class, class>
struct TWeakObjectPtr
Detailed Description
FWeakObjectPtr is a weak pointer to a UObject.
It can return nullptr later if the object is garbage collected. It has no impact on if the object is garbage collected or not. It can't be directly used across a network.
Most often it is used when you explicitly do NOT want to prevent something from being garbage collected.
Definition at line 48 of file WeakObjectPtr.h.
Constructor & Destructor Documentation
FWeakObjectPtr() [1/6]
FWeakObjectPtr::FWeakObjectPtr () default
Referenced by FWeakObjectPtr(), FWeakObjectPtr(), FWeakObjectPtr(), FWeakObjectPtr(), HasSameIndexAndSerialNumber(), operator!=(), operator=(), operator==(), and UE_DEPRECATED().
FWeakObjectPtr() [2/6]
FORCEINLINE FWeakObjectPtr::FWeakObjectPtr (TYPE_OF_NULLPTR) inline
Definition at line 58 of file WeakObjectPtr.h.
References FWeakObjectPtr(), and FORCEINLINE.
FWeakObjectPtr() [3/6]
FORCEINLINE FWeakObjectPtr::FWeakObjectPtr (FObjectPtr Object) inline
Construct from an object pointer or something that can be implicitly converted to an object pointer.
Parameters
Object object to create a weak pointer to
Definition at line 89 of file WeakObjectPtr.h.
References FORCEINLINE, and Object.
FWeakObjectPtr() [4/6]
FORCEINLINE FWeakObjectPtr::FWeakObjectPtr (const UObject * Object) inline
Definition at line 93 of file WeakObjectPtr.h.
References FWeakObjectPtr(), FORCEINLINE, and Object.
FWeakObjectPtr() [5/6]
template<typename T> FORCEINLINE FWeakObjectPtr::FWeakObjectPtr (TObjectPtr< T > Object) inline
Definition at line 98 of file WeakObjectPtr.h.
References FWeakObjectPtr(), FORCEINLINE, Get(), ImplicitConv(), and Object.
FWeakObjectPtr() [6/6]
FWeakObjectPtr::FWeakObjectPtr (const FWeakObjectPtr & Other) default
Construct from another weak pointer.
Parameters
Other weak pointer to copy from
References FWeakObjectPtr(), ObjectIndex, ObjectSerialNumber, and Other.
Member Function Documentation
Get() [1/2]
class UObject * FWeakObjectPtr::Get () const
Dereference the weak pointer.
This is an optimized version implying bEvenIfGarbage=false.
Returns
nullptr if this object is gone or the weak pointer is explicitly null, otherwise a valid uobject pointer
Get() [2/2]
class UObject * FWeakObjectPtr::Get (bool bEvenIfGarbage) const
Dereference the weak pointer.
Parameters
bEvenIfGarbage if this is true, Garbage objects are considered valid
Returns
nullptr if this object is gone or the weak pointer is explicitly null, otherwise a valid uobject pointer
Referenced by FWeakObjectPtr(), TPersistentObjectPtr< FUniqueObjectGuid >::Get(), FObjectKey::ResolveObjectPtr(), and FObjectKey::ResolveObjectPtrEvenIfGarbage().
GetEvenIfUnreachable()
class UObject * FWeakObjectPtr::GetEvenIfUnreachable () const
Dereference the weak pointer even if it is marked as Garbage or Unreachable.
Referenced by FObjectKey::ResolveObjectPtrEvenIfUnreachable().
GetObjectIndex_Private()
FORCEINLINE int32 FWeakObjectPtr::GetObjectIndex_Private () const inline private
Definition at line 378 of file WeakObjectPtr.h.
References FORCEINLINE, UE::Core::Private::InvalidWeakObjectIndex, and ObjectIndex.
GetTypeHash()
FORCEINLINE uint32 FWeakObjectPtr::GetTypeHash () const inline
Hash function.
Definition at line 353 of file WeakObjectPtr.h.
References FORCEINLINE, ObjectIndex, and ObjectSerialNumber.
HasSameIndexAndSerialNumber()
FORCEINLINE bool FWeakObjectPtr::HasSameIndexAndSerialNumber (const FWeakObjectPtr & Other) const inline
Returns true if two weak pointers were originally set to the same object, even if they are now stale.
Parameters
Other weak pointer to compare to
Definition at line 204 of file WeakObjectPtr.h.
References FWeakObjectPtr(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
Internal_Get()
FORCEINLINE_DEBUGGABLE UObject * FWeakObjectPtr::Internal_Get (bool bEvenIfGarbage) const inline private
Private (inlined) version for internal use only.
Definition at line 541 of file WeakObjectPtr.h.
References FORCEINLINE_DEBUGGABLE, FUObjectItem::GetObject(), GUObjectArray, and Internal_GetObjectItem().
Internal_GetObjectItem()
FORCEINLINE FUObjectItem * FWeakObjectPtr::Internal_GetObjectItem () const inline private
Definition at line 430 of file WeakObjectPtr.h.
References checkSlow, FORCEINLINE, GUObjectArray, FUObjectItem::HasAnyFlags(), UE::Core::Private::InvalidWeakObjectIndex, IsExplicitlyNull(), ObjectIndex, ObjectSerialNumber, Remote, and SerialNumbersMatch().
Referenced by Internal_Get(), and Internal_IsValid().
Internal_IsValid()
FORCEINLINE_DEBUGGABLE bool FWeakObjectPtr::Internal_IsValid (bool bEvenIfGarbage, bool bThreadsafeTest) const inline private
Private (inlined) version for internal use only.
Definition at line 526 of file WeakObjectPtr.h.
References FORCEINLINE_DEBUGGABLE, GUObjectArray, and Internal_GetObjectItem().
Internal_Pin()
TStrongObjectPtr< UObject > FWeakObjectPtr::Internal_Pin (bool bEvenIfGarbage) const private
Internal_TryPin()
TStrongObjectPtr< UObject > FWeakObjectPtr::Internal_TryPin (bool & bOutPinValid, bool bEvenIfGarbage) const private
IsExplicitlyNull()
FORCEINLINE bool FWeakObjectPtr::IsExplicitlyNull () const inline
Returns true if this pointer was explicitly assigned to null, was reset, or was never initialized.
If this returns true, IsValid() and IsStale() will both return false.
Definition at line 310 of file WeakObjectPtr.h.
References FORCEINLINE, UE::Core::Private::InvalidWeakObjectIndex, ObjectIndex, and ObjectSerialNumber.
Referenced by Internal_GetObjectItem().
IsRemote()
FORCEINLINE bool FWeakObjectPtr::IsRemote () const inline
Definition at line 346 of file WeakObjectPtr.h.
References FORCEINLINE.
IsStale()
bool FWeakObjectPtr::IsStale (bool bIncludingGarbage = true, bool bThreadsafeTest = false) const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
Parameters
bIncludingGarbage if this is false, Garbage objects are NOT considered stale
bThreadsafeTest set it to true when testing outside of Game Thread. Results in false if WeakObjPtr point to an existing object (no flags checked)
Returns
true if this used to point at a real object but no longer does.
IsValid() [1/2]
bool FWeakObjectPtr::IsValid () const
Test if this points to a live UObject.
This is an optimized version implying bEvenIfGarbage=false, bThreadsafeTest=false. This should be done only when needed as excess resolution of the underlying pointer can cause performance issues. Note that IsValid can not be used on another thread as it will incorrectly return false during the mark phase of the GC due to the Unreachable flag being set. (see bThreadsafeTest above)
Returns
true if Get() would return a valid non-null pointer.
Referenced by operator!=(), and operator==().
IsValid() [2/2]
bool FWeakObjectPtr::IsValid (bool bEvenIfGarbage, bool bThreadsafeTest = false) const
Test if this points to a live UObject This should be done only when needed as excess resolution of the underlying pointer can cause performance issues.
Parameters
bEvenIfGarbage if this is true, Garbage objects are considered valid. When false, an object is considered invalid as soon as it is marked for destruction.
bThreadsafeTest if true then function will just give you information whether referenced UObject is gone forever (return false) or if it is still there (return true, no object flags checked). This is required as without it IsValid can return false during the mark phase of the GC due to the presence of the Unreachable flag.
Returns
true if Get() would return a valid non-null pointer
operator bool()
FWeakObjectPtr::operator bool () const explicit delete
operator!=()
FORCEINLINE bool FWeakObjectPtr::operator!= (const FWeakObjectPtr & Other) const inline
Compare weak pointers for inequality.
Parameters
Other weak pointer to compare to
Definition at line 188 of file WeakObjectPtr.h.
References FWeakObjectPtr(), FORCEINLINE, IsValid(), ObjectIndex, ObjectSerialNumber, and Other.
operator=() [1/4]
FWeakObjectPtr & FWeakObjectPtr::operator= (const FWeakObjectPtr & Other) default
Construct from another weak pointer.
Parameters
Other weak pointer to copy from
References FWeakObjectPtr(), and Other.
operator=() [2/4]
FORCEINLINE void FWeakObjectPtr::operator= (const UObject * Object) inline
Definition at line 145 of file WeakObjectPtr.h.
References FORCEINLINE, and Object.
operator=() [3/4]
void FWeakObjectPtr::operator= (FObjectPtr Object)
Copy from an object pointer.
Parameters
Object object to create a weak pointer to
References Object.
operator=() [4/4]
template<typename T> FORCEINLINE void FWeakObjectPtr::operator= (TObjectPtr< T > Object) inline
Definition at line 150 of file WeakObjectPtr.h.
References FORCEINLINE, and Object.
operator==()
FORCEINLINE bool FWeakObjectPtr::operator== (const FWeakObjectPtr & Other) const inline
Compare weak pointers for equality.
If both pointers would return nullptr from Get() they count as equal even if they were not initialized to the same object.
Parameters
Other weak pointer to compare to
Definition at line 172 of file WeakObjectPtr.h.
References FWeakObjectPtr(), FORCEINLINE, IsValid(), ObjectIndex, ObjectSerialNumber, and Other.
Pin() [1/2]
class TStrongObjectPtr< UObject > FWeakObjectPtr::Pin () const
Get a strong object ptr to the weak pointer.
This is an optimized version implying bEvenIfGarbage=false.
Returns
TStrongObjectPtr will be invalid if this object is gone or the weak pointer is explicitly null, otherwise a valid TStrongObjectPtr
References Pin().
Pin() [2/2]
class TStrongObjectPtr< UObject > FWeakObjectPtr::Pin (bool bEvenIfGarbage) const
Get a strong object ptr to the weak pointer.
Parameters
bEvenIfGarbage if this is true, Garbage objects are considered valid
Returns
TStrongObjectPtr will be invalid if this object is gone or the weak pointer is explicitly null, otherwise a valid TStrongObjectPtr
References bool, and Pin().
Referenced by Pin(), and Pin().
PinEvenIfUnreachable()
class TStrongObjectPtr< UObject > FWeakObjectPtr::PinEvenIfUnreachable () const
References PinEvenIfUnreachable().
Referenced by PinEvenIfUnreachable().
Reset()
FORCEINLINE void FWeakObjectPtr::Reset () inline
Reset the weak pointer back to the null state.
Definition at line 129 of file WeakObjectPtr.h.
References FORCEINLINE, UE::Core::Private::InvalidWeakObjectIndex, ObjectIndex, and ObjectSerialNumber.
Serialize()
void FWeakObjectPtr::Serialize (FArchive & Ar)
Weak object pointer serialization.
Weak object pointers only have weak references to objects and won't serialize the object when gathering references for garbage collection. So in many cases, you don't need to bother serializing weak object pointers. However, serialization is required if you want to load and save your object.
References Ar.
SerialNumbersMatch() [1/2]
FORCEINLINE_DEBUGGABLE bool FWeakObjectPtr::SerialNumbersMatch () const inline private
internal function to test for serial number matches
Returns
true if the serial number in this matches the central table
Definition at line 402 of file WeakObjectPtr.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, GUObjectArray, ObjectIndex, ObjectSerialNumber, and FUObjectArray::START_SERIAL_NUMBER.
Referenced by Internal_GetObjectItem().
SerialNumbersMatch() [2/2]
FORCEINLINE_DEBUGGABLE bool FWeakObjectPtr::SerialNumbersMatch (FUObjectItem * ObjectItem) const inline private
Definition at line 416 of file WeakObjectPtr.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, FUObjectItem::GetSerialNumber(), ObjectIndex, ObjectSerialNumber, and FUObjectArray::START_SERIAL_NUMBER.
TryPin() [1/2]
class TStrongObjectPtr< UObject > FWeakObjectPtr::TryPin (bool & bOutPinValid) const
Attempt to get a strong object ptr to the weak pointer, but only if garbage collection is not in progress.
This is an optimized version implying bEvenIfGarbage=false.
Parameters
bOutPinValid will be true if the pin attempt was successful, and false if it was blocked by garbage collection
Returns
TStrongObjectPtr will be invalid if this object is gone or the weak pointer is explicitly null, otherwise a valid TStrongObjectPtr
References bool, and TryPin().
TryPin() [2/2]
class TStrongObjectPtr< UObject > FWeakObjectPtr::TryPin (bool & bOutPinValid, bool bEvenIfGarbage) const
Attempt to get a strong object ptr to the weak pointer, but only if garbage collection is not in progress.
Parameters
bEvenIfGarbage if this is true, Garbage objects are considered valid
bOutPinValid will be true if the pin attempt was successful, and false if it was blocked by garbage collection
Returns
TStrongObjectPtr will be invalid if this object is gone or the weak pointer is explicitly null, otherwise a valid TStrongObjectPtr
References bool, and TryPin().
Referenced by TryPin(), and TryPin().
TryPinEvenIfUnreachable()
bool FWeakObjectPtr::TryPinEvenIfUnreachable (class TStrongObjectPtr< UObject > & OutResult) const
UE_DEPRECATED() [1/2]
FWeakObjectPtr::UE_DEPRECATED (5. 1, "GetObjectIndex is now deprecated, and will be removed.") const inline protected
Definition at line 371 of file WeakObjectPtr.h.
References FORCEINLINE, and ObjectIndex.
UE_DEPRECATED() [2/2]
FWeakObjectPtr::UE_DEPRECATED (5. 6, "Constructing a FWeakObjectPtr from NULL has been deprecated - please use nullptr instead.") inline
Definition at line 79 of file WeakObjectPtr.h.
References FWeakObjectPtr(), and FORCEINLINE.
Friends And Related Symbol Documentation
FObjectKey
friend struct FObjectKey friend
Definition at line 391 of file WeakObjectPtr.h.
References FObjectKey.
Referenced by FObjectKey.
TWeakObjectPtr
template<class, class> friend struct TWeakObjectPtr friend
Definition at line 53 of file WeakObjectPtr.h.
References TWeakObjectPtr.
Referenced by TWeakObjectPtr.
Field Documentation
ObjectIndex
int32 FWeakObjectPtr::ObjectIndex = UE::Core::Private::InvalidWeakObjectIndex private
Definition at line 551 of file WeakObjectPtr.h.
Referenced by FWeakObjectPtr(), GetObjectIndex_Private(), GetTypeHash(), FObjectKey::GetWeakObjectPtr(), HasSameIndexAndSerialNumber(), Internal_GetObjectItem(), IsExplicitlyNull(), operator!=(), operator==(), Reset(), FObjectKey::ResolveObjectPtr(), FObjectKey::ResolveObjectPtrEvenIfGarbage(), FObjectKey::ResolveObjectPtrEvenIfUnreachable(), SerialNumbersMatch(), SerialNumbersMatch(), and UE_DEPRECATED().
ObjectSerialNumber
int32 FWeakObjectPtr::ObjectSerialNumber = 0 private
Definition at line 552 of file WeakObjectPtr.h.
Referenced by FWeakObjectPtr(), GetTypeHash(), FObjectKey::GetWeakObjectPtr(), HasSameIndexAndSerialNumber(), Internal_GetObjectItem(), IsExplicitlyNull(), operator!=(), operator==(), Reset(), FObjectKey::ResolveObjectPtr(), FObjectKey::ResolveObjectPtrEvenIfGarbage(), FObjectKey::ResolveObjectPtrEvenIfUnreachable(), SerialNumbersMatch(), and SerialNumbersMatch().
The documentation for this struct was generated from the following file:
WeakObjectPtr.h