Unreal Engine 5.6 C++ API: FSuspensionOutputData Struct Reference
FSuspensionOutputData Struct Reference
#include "SuspensionSimModule.h"
Public Member Functions
virtual CHAOSMODULARVEHICLEENGINE_API void FillOutputState (const Chaos::ISimulationModuleBase *SimModule) override
virtual CHAOSMODULARVEHICLEENGINE_API void Lerp (const FSimOutputData &InCurrent, const Chaos::FSimOutputData &InNext, float Alpha) override
virtual FSimOutputData * MakeNewData () override
virtual CHAOSMODULARVEHICLEENGINE_API FString ToString () override
Static Public Member Functions
static FSimOutputData * MakeNew ()
Data Fields
FVector ImpactNormal
float SpringDisplacement
FVector SpringDisplacementVector
float SpringSpeed
Detailed Description
Definition at line 49 of file SuspensionSimModule.h.
Member Function Documentation
FillOutputState()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionOutputData::FillOutputState (const Chaos::ISimulationModuleBase * SimModule) override virtual
References UE_API.
Lerp()
virtual CHAOSMODULARVEHICLEENGINE_API void FSuspensionOutputData::Lerp (const FSimOutputData & InCurrent, const Chaos::FSimOutputData & InNext, float Alpha) override virtual
References Alpha, and UE_API.
MakeNew()
FSimOutputData * FSuspensionOutputData::MakeNew () inline static
Definition at line 54 of file SuspensionSimModule.h.
Referenced by FSuspensionSimModule::GenerateOutputData(), and MakeNewData().
MakeNewData()
virtual FSimOutputData * FSuspensionOutputData::MakeNewData () inline override virtual
Definition at line 53 of file SuspensionSimModule.h.
References MakeNew().
ToString()
virtual CHAOSMODULARVEHICLEENGINE_API FString FSuspensionOutputData::ToString () override virtual
References UE_API.
Field Documentation
ImpactNormal
FVector FSuspensionOutputData::ImpactNormal
Definition at line 66 of file SuspensionSimModule.h.
SpringDisplacement
float FSuspensionOutputData::SpringDisplacement
Definition at line 63 of file SuspensionSimModule.h.
SpringDisplacementVector
FVector FSuspensionOutputData::SpringDisplacementVector
Definition at line 64 of file SuspensionSimModule.h.
SpringSpeed
float FSuspensionOutputData::SpringSpeed
Definition at line 65 of file SuspensionSimModule.h.
The documentation for this struct was generated from the following file:
SuspensionSimModule.h