Unreal Engine 5.6 C++ API: TKeyTimeIterator< TimeType > Struct Template Reference
TKeyTimeIterator< TimeType > Struct Template Reference
Key time iterator for TKeyFrameManipulator.
#include "IKeyFrameManipulator.h"
Public Member Functions
TKeyTimeIterator (const TKeyFrameManipulator< TimeType > &InManipulator)
int32 GetEndIndex () const
FKeyHandle GetKeyHandle ()
int32 GetStartIndex () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE TimeType operator* () const
FORCEINLINE TKeyTimeIterator & operator++ ()
FORCEINLINE bool operator== (const TKeyTimeIterator &RHS) const
Private Attributes
int32 Index
const TKeyFrameManipulator< TimeType > & Manipulator
Friends
FORCEINLINE friend TKeyTimeIterator< TimeType > begin (const TKeyTimeIterator< TimeType > &Iter)
FORCEINLINE friend TKeyTimeIterator< TimeType > end (const TKeyTimeIterator< TimeType > &Iter)
FORCEINLINE friend bool operator!= (const TKeyTimeIterator &LHS, const TKeyTimeIterator &RHS)
Detailed Description
template<typename TimeType>
struct TKeyTimeIterator< TimeType >
Key time iterator for TKeyFrameManipulator.
Definition at line 134 of file IKeyFrameManipulator.h.
Constructor & Destructor Documentation
TKeyTimeIterator()
template<typename TimeType> TKeyTimeIterator< TimeType >::TKeyTimeIterator (const TKeyFrameManipulator< TimeType > & InManipulator) inline
Definition at line 136 of file IKeyFrameManipulator.h.
References Index, and Manipulator.
Referenced by begin, end, operator!=, operator++(), and operator==().
Member Function Documentation
GetEndIndex()
template<typename TimeType> int32 TKeyTimeIterator< TimeType >::GetEndIndex () const inline
Definition at line 183 of file IKeyFrameManipulator.h.
References Manipulator.
Referenced by end.
GetKeyHandle()
template<typename TimeType> FKeyHandle TKeyTimeIterator< TimeType >::GetKeyHandle () inline
Definition at line 173 of file IKeyFrameManipulator.h.
References Index, and Manipulator.
GetStartIndex()
template<typename TimeType> int32 TKeyTimeIterator< TimeType >::GetStartIndex () const inline
Definition at line 178 of file IKeyFrameManipulator.h.
Referenced by begin.
operator bool()
template<typename TimeType> FORCEINLINE TKeyTimeIterator< TimeType >::operator bool () const inline explicit
conversion to "bool" returning true if the iterator is valid.
Definition at line 148 of file IKeyFrameManipulator.h.
References FORCEINLINE, Index, and Manipulator.
operator!()
template<typename TimeType> FORCEINLINE bool TKeyTimeIterator< TimeType >::operator! () const inline
inverse of the "bool" operator
Definition at line 153 of file IKeyFrameManipulator.h.
References bool, and FORCEINLINE.
operator*()
template<typename TimeType> FORCEINLINE TimeType TKeyTimeIterator< TimeType >::operator* () const inline
Definition at line 168 of file IKeyFrameManipulator.h.
References FORCEINLINE, Index, and Manipulator.
operator++()
template<typename TimeType> FORCEINLINE TKeyTimeIterator & TKeyTimeIterator< TimeType >::operator++ () inline
Definition at line 141 of file IKeyFrameManipulator.h.
References TKeyTimeIterator(), FORCEINLINE, and Index.
operator==()
template<typename TimeType> FORCEINLINE bool TKeyTimeIterator< TimeType >::operator== (const TKeyTimeIterator< TimeType > & RHS) const inline
Definition at line 158 of file IKeyFrameManipulator.h.
References TKeyTimeIterator(), FORCEINLINE, Index, and Manipulator.
Friends And Related Symbol Documentation
begin
template<typename TimeType> FORCEINLINE friend TKeyTimeIterator< TimeType > begin (const TKeyTimeIterator< TimeType > & Iter) friend
Definition at line 188 of file IKeyFrameManipulator.h.
References TKeyTimeIterator(), FORCEINLINE, GetStartIndex(), and Index.
end
template<typename TimeType> FORCEINLINE friend TKeyTimeIterator< TimeType > end (const TKeyTimeIterator< TimeType > & Iter) friend
Definition at line 194 of file IKeyFrameManipulator.h.
References TKeyTimeIterator(), FORCEINLINE, GetEndIndex(), and Index.
operator!=
template<typename TimeType> FORCEINLINE friend bool operator!= (const TKeyTimeIterator< TimeType > & LHS, const TKeyTimeIterator< TimeType > & RHS) friend
Definition at line 163 of file IKeyFrameManipulator.h.
References TKeyTimeIterator(), and FORCEINLINE.
Field Documentation
Index
template<typename TimeType> int32 TKeyTimeIterator< TimeType >::Index private
Definition at line 203 of file IKeyFrameManipulator.h.
Referenced by TKeyTimeIterator(), begin, end, GetKeyHandle(), operator bool(), operator*(), operator++(), and operator==().
Manipulator
template<typename TimeType> const TKeyFrameManipulator<TimeType>& TKeyTimeIterator< TimeType >::Manipulator private
Definition at line 202 of file IKeyFrameManipulator.h.
Referenced by TKeyTimeIterator(), GetEndIndex(), GetKeyHandle(), operator bool(), operator*(), and operator==().
The documentation for this struct was generated from the following file:
IKeyFrameManipulator.h