Unreal Engine 5.6 C++ API: TransformCalculus.h File Reference
TransformCalculus.h File Reference
#include "CoreTypes.h"
#include "Math/Vector2D.h"
#include "Math/Vector.h"
Data Structures
struct ConcatenateRules< TransformTypeA, TransformTypeB >
Provides default rules defining the result of concatenating two types.
struct ConcatenateRules< TransformType, TransformType >
Partial specialization for concatenating two of the same types.
struct TransformConverter< TransformType >
Provides default logic (used by TransformCast) to convert one transform type to another via a conversion ctor.
Functions
template<typename ReturnType, typename LHSType, typename RHSType>
ReturnType Concatenate (const LHSType &LHS, const RHSType &RHS)
Special overload that allows one to explicitly define the result type, which applies TransformCast on each argument first.
template<typename TransformType>
auto Concatenate (const TransformType &LHS, const TransformType &RHS) -> decltype(LHS.Concatenate(RHS))
Specialization for concatenating two transforms of the same type.
template<typename TransformType1, typename TransformType2, typename... TransformTypeRest>
decltype(auto) Concatenate (const TransformType1 &TransformAToB, const TransformType2 &TransformBToC, TransformTypeRest &&... TransformCToRest)
Concatenates three or more transforms.
template<typename TransformTypeA, typename TransformTypeB>
ConcatenateRules< TransformTypeA, TransformTypeB >::ResultType Concatenate (const TransformTypeA &LHS, const TransformTypeB &RHS)
Concatenates two transforms.
template<typename FloatType UE_REQUIRES>
FloatType Concatenate (FloatType LHS, FloatType RHS)
Specialization for concatenating two scales.
template<typename TransformType>
auto Inverse (const TransformType &Transform) -> decltype(Transform.Inverse())
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename FloatType UE_REQUIRES>
FloatType Inverse (FloatType Scale)
Inverts a transform from space A to space B so it transforms from space B to space A.
template<typename ResultType, typename TransformType>
decltype(auto) TransformCast (const TransformType &Transform)
Casts one TransformType to ResultType using rules laid out by TransformConverter<>::Convert<>().
template<typename TransformType, typename PositionType>
PositionType TransformPoint (const TransformType &Transform, const PositionType &Point)
Generic implementation of TransformPoint.
template<typename PositionType>
UE::Math::TVector< PositionType > TransformPoint (double Transform, const UE::Math::TVector< PositionType > &Point)
template<typename PositionType>
UE::Math::TVector< PositionType > TransformPoint (float Transform, const UE::Math::TVector< PositionType > &Point)
Specialization for uniform Scale.
template<typename TransformType, typename VectorType>
VectorType TransformVector (const TransformType &Transform, const VectorType &Vector)
Generic implementation of TransformVector.
template<typename VectorType>
UE::Math::TVector< VectorType > TransformVector (double Transform, const UE::Math::TVector< VectorType > &Vector)
template<typename VectorType>
UE::Math::TVector< VectorType > TransformVector (float Transform, const UE::Math::TVector< VectorType > &Vector)
Specialization for uniform Scale.
Function Documentation
Concatenate() [1/5]
template<typename ReturnType, typename LHSType, typename RHSType> ReturnType Concatenate (const LHSType & LHS, const RHSType & RHS) inline nodiscard
Special overload that allows one to explicitly define the result type, which applies TransformCast on each argument first.
Definition at line 305 of file TransformCalculus.h.
References Concatenate(), and TransformCast().
Concatenate() [2/5]
template<typename TransformType> auto Concatenate (const TransformType & LHS, const TransformType & RHS) -> decltype(LHS.Concatenate(RHS)) inline nodiscard
Specialization for concatenating two transforms of the same type.
By default we try to use a member function on the type.
Parameters
LHS Transformation that goes from space A to space B
RHS Transformation that goes from space B to space C.
Returns
a new transform representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 319 of file TransformCalculus.h.
Concatenate() [3/5]
template<typename TransformType1, typename TransformType2, typename... TransformTypeRest> decltype(auto) Concatenate (const TransformType1 & TransformAToB, const TransformType2 & TransformBToC, TransformTypeRest &&... TransformCToRest) inline nodiscard
Concatenates three or more transforms.
Uses two-argument Concatenate to do its work, and infers the return type using decltype.
Parameters
TransformAToB Transformation that goes from space A to space B
TransformBToC Transformation that goes from space B to space C.
TransformCToRest Transformation that goes from space C onwards.
Returns
a new Transform representing the complete transformation.
Definition at line 336 of file TransformCalculus.h.
References Concatenate(), and Forward().
Concatenate() [4/5]
template<typename TransformTypeA, typename TransformTypeB> ConcatenateRules< TransformTypeA, TransformTypeB >::ResultType Concatenate (const TransformTypeA & LHS, const TransformTypeB & RHS) inline nodiscard
Concatenates two transforms.
Uses TransformCast<> to convert them first. If more efficient means are available to concatenate two transforms, provide a non-template overload (or possibly a specialization). Concatenation is performed in left to right order, so the output space of LHS must match the input space of RHS.
Parameters
LHS Transformation that goes from space A to space B
RHS Transformation that goes from space B to space C.
Returns
a new transform representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 293 of file TransformCalculus.h.
References Concatenate(), and TransformCast().
Referenced by FPaintGeometry::AppendTransform(), Concatenate(), Concatenate(), Concatenate(), Concatenate(), Concatenate(), FSlateRotatedRect::MakeRotatedRect(), FSlateRotatedRect::MakeSnappedRotatedRect(), and USTRUCT().
Concatenate() [5/5]
template<typename FloatType UE_REQUIRES> FloatType Concatenate (FloatType LHS, FloatType RHS) inline nodiscard
Specialization for concatenating two scales.
Parameters
LHS Scale that goes from space A to space B
RHS Scale that goes from space B to space C.
Returns
a new Scale representing the transformation from the input space of LHS to the output space of RHS.
Definition at line 388 of file TransformCalculus.h.
Inverse() [1/2]
template<typename TransformType> auto Inverse (const TransformType & Transform) -> decltype(Transform.Inverse()) inline nodiscard
Inverts a transform from space A to space B so it transforms from space B to space A.
By default attempts to call a member function on the transform type.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 349 of file TransformCalculus.h.
References Transform.
Referenced by FDisplayClusterMeshProjectionTransform::FDisplayClusterMeshProjectionTransform(), FPaintGeometry::CommitTransformsIfUsingLegacyConstructor(), FSlateDrawElement::GetInverseLayoutTransform(), USTRUCT(), and USTRUCT().
Inverse() [2/2]
template<typename FloatType UE_REQUIRES> FloatType Inverse (FloatType Scale) inline nodiscard
Inverts a transform from space A to space B so it transforms from space B to space A.
Specialization for uniform scale.
Parameters
Transform Input transform from space A to space B.
Returns
Inverted transform from space B to space A.
Definition at line 401 of file TransformCalculus.h.
References Scale.
TransformCast()
template<typename ResultType, typename TransformType> decltype(auto) TransformCast (const TransformType & Transform) inline nodiscard
Casts one TransformType to ResultType using rules laid out by TransformConverter<>::Convert<>().
Return type uses decltype to support classes that can return by const-ref more efficiently than returning a new value.
Definition at line 262 of file TransformCalculus.h.
References TransformConverter< TransformType >::Convert(), and Transform.
Referenced by Concatenate(), Concatenate(), Concatenate(), and USTRUCT().
TransformPoint() [1/3]
template<typename TransformType, typename PositionType> PositionType TransformPoint (const TransformType & Transform, const PositionType & Point) inline nodiscard
Generic implementation of TransformPoint.
Attempts to use a member function of the TransformType.
Definition at line 358 of file TransformCalculus.h.
References Point, and Transform.
Referenced by FPaintGeometry::AppendTransform(), Concatenate(), Concatenate(), Concatenate(), Concatenate(), Concatenate(), Concatenate(), TransformConverter< FMatrix44d >::Convert(), FSlateVertex::InitCommon(), TransformRect(), TransformRect(), and USTRUCT().
TransformPoint() [2/3]
template<typename PositionType> UE::Math::TVector< PositionType > TransformPoint (double Transform, const UE::Math::TVector< PositionType > & Point) inline nodiscard
Definition at line 416 of file TransformCalculus.h.
References Point, and Transform.
TransformPoint() [3/3]
template<typename PositionType> UE::Math::TVector< PositionType > TransformPoint (float Transform, const UE::Math::TVector< PositionType > & Point) inline nodiscard
Specialization for uniform Scale.
Definition at line 410 of file TransformCalculus.h.
References Point, and Transform.
TransformVector() [1/3]
template<typename TransformType, typename VectorType> VectorType TransformVector (const TransformType & Transform, const VectorType & Vector) inline nodiscard
Generic implementation of TransformVector.
Attempts to use a member function of the TransformType.
Definition at line 367 of file TransformCalculus.h.
References Transform, and Vector.
Referenced by FPaintGeometry::CommitTransformsIfUsingLegacyConstructor(), UE::Math::TTransform< T >::GetScaledAxis(), FLayoutGeometry::GetSizeInParentSpace(), TransformRect(), and USTRUCT().
TransformVector() [2/3]
template<typename VectorType> UE::Math::TVector< VectorType > TransformVector (double Transform, const UE::Math::TVector< VectorType > & Vector) inline nodiscard
Definition at line 431 of file TransformCalculus.h.
References Transform, and Vector.
TransformVector() [3/3]
template<typename VectorType> UE::Math::TVector< VectorType > TransformVector (float Transform, const UE::Math::TVector< VectorType > & Vector) inline nodiscard
Specialization for uniform Scale.
Definition at line 425 of file TransformCalculus.h.
References Transform, and Vector.