Unreal Engine 5.6 C++ API: FShaderCodeLibraryPipeline Struct Reference
FShaderCodeLibraryPipeline Struct Reference
#include "ShaderCodeLibrary.h"
Public Member Functions
FShaderCodeLibraryPipeline ()
RENDERCORE_API void GetPipelineHash (FSHAHash &Output)
Computes a longer hash that uniquely identifies the whole pipeline, used in FStableShaderKeyAndValue.
RENDERCORE_API void Initialize (const FShaderPipeline *Pipeline)
Fills the hashes from the pipeline stage shaders.
Data Fields
uint32 Hash
FSHAHash Shaders [SF_NumGraphicsFrequencies]
Friends
uint32 GetTypeHash (const FShaderCodeLibraryPipeline &Key)
FArchive & operator<< (FArchive &Ar, FShaderCodeLibraryPipeline &Info)
bool operator== (const FShaderCodeLibraryPipeline &A, const FShaderCodeLibraryPipeline &B)
Detailed Description
Definition at line 47 of file ShaderCodeLibrary.h.
Constructor & Destructor Documentation
FShaderCodeLibraryPipeline()
FShaderCodeLibraryPipeline::FShaderCodeLibraryPipeline () inline
Definition at line 55 of file ShaderCodeLibrary.h.
References Hash.
Referenced by GetTypeHash, operator<<, and operator==.
Member Function Documentation
GetPipelineHash()
RENDERCORE_API void FShaderCodeLibraryPipeline::GetPipelineHash (FSHAHash & Output)
Computes a longer hash that uniquely identifies the whole pipeline, used in FStableShaderKeyAndValue.
Initialize()
RENDERCORE_API void FShaderCodeLibraryPipeline::Initialize (const FShaderPipeline * Pipeline)
Fills the hashes from the pipeline stage shaders.
References Pipeline.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FShaderCodeLibraryPipeline & Key) friend
Definition at line 69 of file ShaderCodeLibrary.h.
References FShaderCodeLibraryPipeline(), Frequency, Key, and FCrc::MemCrc32().
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCodeLibraryPipeline & Info) friend
Definition at line 84 of file ShaderCodeLibrary.h.
References FShaderCodeLibraryPipeline(), Ar, Frequency, and Info.
operator==
bool operator== (const FShaderCodeLibraryPipeline & A, const FShaderCodeLibraryPipeline & B) friend
Definition at line 57 of file ShaderCodeLibrary.h.
References FShaderCodeLibraryPipeline(), A, B, and Frequency.
Field Documentation
Hash
uint32 FShaderCodeLibraryPipeline::Hash mutable
Definition at line 50 of file ShaderCodeLibrary.h.
Referenced by FShaderCodeLibraryPipeline().
Shaders
FSHAHash FShaderCodeLibraryPipeline::Shaders[SF_NumGraphicsFrequencies]
Definition at line 49 of file ShaderCodeLibrary.h.
The documentation for this struct was generated from the following file:
ShaderCodeLibrary.h