Unreal Engine 5.6 C++ API: FShaderKeyGenerator Class Reference
FShaderKeyGenerator Class Reference
Output class passed to Append functions for shader data.
#include "ShaderKeyGenerator.h"
Public Member Functions
FShaderKeyGenerator (FString &InResultString)
Constructor that writes the appended data to a long human-readable debug string.
FShaderKeyGenerator (TUniqueFunction< void(const void *Data, uint64 Size)> &&InResultFunc)
Constructor that writes the appended data to a hash function.
~FShaderKeyGenerator ()
void Append (const FBlake3Hash &Value)
Append Value to the output string (equivalent to LexToString) or pass it as binary data to the hash function.
void Append (const FGuid &Value)
Append Value to the output string (EGuidFormats::Digits) or pass it as binary data to the hash function.
void Append (const FSHAHash &Value)
Append Value to the output string (equivalent to LexToString) or pass it as binary data to the hash function.
void Append (const TCHAR *Value)
Append arbitrary text to the output string or hash function.
void Append (FName Value)
Convert the FName to text (case-sensitive) and append it to the output string or hash function.
void Append (FStringView Value)
Append arbitrary text to the output string or hash function.
void Append (int32 Value)
Appendf the integer to the output string or pass it as binary data to the hash function.
void Append (int64 Value)
Appendf the integer to the output string or pass it as binary data to the hash function.
void Append (uint32 Value)
Appendf the integer to the output string or pass it as binary data to the hash function.
void Append (uint64 Value)
Appendf the integer to the output string or pass it as binary data to the hash function.
void AppendBoolInt (bool Value)
Appendf 0 or 1 to the output string or pass a 0 or 1 uint8 the hash function.
void AppendDebugText (FStringView Value)
Append arbitrary text to the output human-readable string.
void AppendHex (uint32 Value)
Appendf the integer to the output string, using X format, or pass it as binary data to the hash function.
void AppendSeparator ()
Append the separator character '_' to the output human-readable string.
void BinaryAppend (const void *Data, uint64 Size)
Must not be called unless IsBinary is true.
bool IsBinary () const
True iff the KeyGen is writing to a hash function.
bool IsText () const
True iff the KeyGen is writing to a human-readable debug string.
FString & TextGetResultString ()
Must not be called unless IsText is true.
Private Types
enum class EOutputType { Text , Binary }
Private Attributes
EOutputType OutputType = EOutputType::Text
TUniqueFunction< void(const void *Data, uint64 Size)> ResultFunc
FString * ResultString = nullptr
Detailed Description
Output class passed to Append functions for shader data.
It receives Append calls for the input data for shader compilation. These input data should trigger a recompile if they change, and they are therefore added into the key used for storage of shader data in DDC and incremental cooks.
Known types are appended through FShaderKeyGenerator Append member functions. For other types, the standard API (which is used by e.g. the append function for TArray) for types that can be appended to FShaderKeyGenerator is the function in global namespace: void Append(FShaderKeyGenerator& KeyGen, const TypeName& Value);
The proper Append function can be called for any type using operator<<.
Definition at line 28 of file ShaderKeyGenerator.h.
Member Enumeration Documentation
EOutputType
enum class FShaderKeyGenerator::EOutputType strong private
Enumerator
Text
Binary
Definition at line 84 of file ShaderKeyGenerator.h.
Constructor & Destructor Documentation
FShaderKeyGenerator() [1/2]
FShaderKeyGenerator::FShaderKeyGenerator (TUniqueFunction< void(const void *Data, uint64 Size)> && InResultFunc) inline
Constructor that writes the appended data to a hash function.
(FShaderKeyGenerator&)KeyGen << (const T&) Value;
Append the given Value to the KeyGen, using FShaderKeyGenerator::Append for known types, or Append(FShaderKeyGenerator&, const T&) for unknown types. Forward declare not possible, see implementation below.
Definition at line 124 of file ShaderKeyGenerator.h.
References Binary, MoveTemp(), OutputType, ResultFunc, and TSequenceHistory< HistorySize >::Size.
FShaderKeyGenerator() [2/2]
FShaderKeyGenerator::FShaderKeyGenerator (FString & InResultString) inline
Constructor that writes the appended data to a long human-readable debug string.
Definition at line 130 of file ShaderKeyGenerator.h.
References OutputType, ResultString, and Text.
~FShaderKeyGenerator()
FShaderKeyGenerator::~FShaderKeyGenerator () inline default
References TSequenceHistory< HistorySize >::Size, and Value.
Member Function Documentation
Append() [1/10]
void FShaderKeyGenerator::Append (const FBlake3Hash & Value)
Append Value to the output string (equivalent to LexToString) or pass it as binary data to the hash function.
References Value.
Append() [2/10]
void FShaderKeyGenerator::Append (const FGuid & Value)
Append Value to the output string (EGuidFormats::Digits) or pass it as binary data to the hash function.
References Value.
Append() [3/10]
void FShaderKeyGenerator::Append (const FSHAHash & Value)
Append Value to the output string (equivalent to LexToString) or pass it as binary data to the hash function.
References Value.
Append() [4/10]
void FShaderKeyGenerator::Append (const TCHAR * Value) inline
Append arbitrary text to the output string or hash function.
Null-terminated character pointer. Null pointer is a noop.
Definition at line 176 of file ShaderKeyGenerator.h.
References Append(), and Value.
Append() [5/10]
void FShaderKeyGenerator::Append (FName Value) inline
Convert the FName to text (case-sensitive) and append it to the output string or hash function.
Definition at line 181 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, TStringBuilderBase< CharType >::GetData(), InPlace, TStringBuilderBase< CharType >::Len(), OutputType, ResultFunc, ResultString, Text, and Value.
Append() [6/10]
void FShaderKeyGenerator::Append (FStringView Value) inline
Append arbitrary text to the output string or hash function.
Definition at line 161 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, Text, and Value.
Referenced by Append(), and operator<<().
Append() [7/10]
void FShaderKeyGenerator::Append (int32 Value) inline
Appendf the integer to the output string or pass it as binary data to the hash function.
Definition at line 229 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, TEXT, Text, and Value.
Append() [8/10]
void FShaderKeyGenerator::Append (int64 Value) inline
Appendf the integer to the output string or pass it as binary data to the hash function.
Definition at line 199 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, INT64_FMT, OutputType, ResultFunc, ResultString, TEXT, Text, and Value.
Append() [9/10]
void FShaderKeyGenerator::Append (uint32 Value) inline
Appendf the integer to the output string or pass it as binary data to the hash function.
Definition at line 244 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, TEXT, Text, and Value.
Append() [10/10]
void FShaderKeyGenerator::Append (uint64 Value) inline
Appendf the integer to the output string or pass it as binary data to the hash function.
Definition at line 214 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, TEXT, Text, UINT64_FMT, and Value.
AppendBoolInt()
void FShaderKeyGenerator::AppendBoolInt (bool Value) inline
Appendf 0 or 1 to the output string or pass a 0 or 1 uint8 the hash function.
Definition at line 274 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, Text, and Value.
AppendDebugText()
void FShaderKeyGenerator::AppendDebugText (FStringView Value) inline
Append arbitrary text to the output human-readable string.
Noop if !IsText.
Definition at line 292 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultString, Text, and Value.
AppendHex()
void FShaderKeyGenerator::AppendHex (uint32 Value) inline
Appendf the integer to the output string, using X format, or pass it as binary data to the hash function.
Definition at line 259 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultFunc, ResultString, TEXT, Text, and Value.
AppendSeparator()
void FShaderKeyGenerator::AppendSeparator () inline
Append the separator character '_' to the output human-readable string.
Noop if !IsText.
Definition at line 307 of file ShaderKeyGenerator.h.
References Binary, checkNoEntry, OutputType, ResultString, and Text.
BinaryAppend()
void FShaderKeyGenerator::BinaryAppend (const void * Data, uint64 Size) inline
Must not be called unless IsBinary is true.
Append data directly to the hash function.
Definition at line 149 of file ShaderKeyGenerator.h.
References check, IsBinary(), ResultFunc, and TSequenceHistory< HistorySize >::Size.
IsBinary()
bool FShaderKeyGenerator::IsBinary () const inline
True iff the KeyGen is writing to a hash function.
Writing to a hash function also implies that debugtext and separators will be skipped in the output.
Definition at line 139 of file ShaderKeyGenerator.h.
References Binary, and OutputType.
Referenced by BinaryAppend().
IsText()
bool FShaderKeyGenerator::IsText () const inline
True iff the KeyGen is writing to a human-readable debug string.
Definition at line 144 of file ShaderKeyGenerator.h.
References OutputType, and Text.
Referenced by TextGetResultString().
TextGetResultString()
FString & FShaderKeyGenerator::TextGetResultString () inline
Must not be called unless IsText is true.
Return a modifiable reference to the string being written.
Definition at line 155 of file ShaderKeyGenerator.h.
References check, IsText(), and ResultString.
Field Documentation
OutputType
EOutputType FShaderKeyGenerator::OutputType = EOutputType::Text private
Definition at line 93 of file ShaderKeyGenerator.h.
Referenced by FShaderKeyGenerator(), FShaderKeyGenerator(), Append(), Append(), Append(), Append(), Append(), Append(), AppendBoolInt(), AppendDebugText(), AppendHex(), AppendSeparator(), IsBinary(), and IsText().
ResultFunc
TUniqueFunction<void(const void* Data, uint64 Size)> FShaderKeyGenerator::ResultFunc private
Definition at line 91 of file ShaderKeyGenerator.h.
Referenced by FShaderKeyGenerator(), Append(), Append(), Append(), Append(), Append(), Append(), AppendBoolInt(), AppendHex(), and BinaryAppend().
ResultString
FString* FShaderKeyGenerator::ResultString = nullptr private
Definition at line 92 of file ShaderKeyGenerator.h.
Referenced by FShaderKeyGenerator(), Append(), Append(), Append(), Append(), Append(), Append(), AppendBoolInt(), AppendDebugText(), AppendHex(), AppendSeparator(), and TextGetResultString().
The documentation for this class was generated from the following file:
ShaderKeyGenerator.h