Unreal Engine 5.6 C++ API: UUVEditorLayoutToolBuilder Class Reference
UUVEditorLayoutToolBuilder Class Reference
#include "UVEditorLayoutTool.h"
Public Member Functions
virtual UInteractiveTool * BuildTool (const FToolBuilderState &SceneState) const override
virtual bool CanBuildTool (const FToolBuilderState &SceneState) const override
Data Fields
const TArray< TObjectPtr< UUVEditorToolMeshInput > > * Targets = nullptr
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 20 of file UVEditorLayoutTool.h.
Member Function Documentation
BuildTool()
virtual UInteractiveTool * UUVEditorLayoutToolBuilder::BuildTool (const FToolBuilderState & SceneState) const override virtual
References BuildTool().
Referenced by BuildTool().
CanBuildTool()
virtual bool UUVEditorLayoutToolBuilder::CanBuildTool (const FToolBuilderState & SceneState) const override virtual
References CanBuildTool().
Referenced by CanBuildTool().
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorLayoutToolBuilder::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 22 of file UVEditorLayoutTool.h.
Targets
const TArray<TObjectPtr<UUVEditorToolMeshInput> >* UUVEditorLayoutToolBuilder::Targets = nullptr
Definition at line 30 of file UVEditorLayoutTool.h.
The documentation for this class was generated from the following file:
UVEditorLayoutTool.h