Unreal Engine 5.6 C++ API: FInputDeviceTriggerFeedbackProperty Struct Reference
FInputDeviceTriggerFeedbackProperty Struct Reference
Trigger resistance that is applied at a single position with the given strength.
#include "IInputInterface.h"
Public Member Functions
FInputDeviceTriggerFeedbackProperty ()
Public Member Functions inherited from FInputDeviceTriggerProperty
FInputDeviceTriggerProperty (FName InName)
Static Public Member Functions
static FName PropertyName ()
Data Fields
int32 Position = 0
int32 Strengh = 0
Data Fields inherited from FInputDeviceTriggerProperty
EInputDeviceTriggerMask AffectedTriggers = EInputDeviceTriggerMask::None
Which trigger this property should effect.
Detailed Description
Trigger resistance that is applied at a single position with the given strength.
Definition at line 192 of file IInputInterface.h.
Constructor & Destructor Documentation
FInputDeviceTriggerFeedbackProperty()
FInputDeviceTriggerFeedbackProperty::FInputDeviceTriggerFeedbackProperty () inline
Definition at line 194 of file IInputInterface.h.
References FInputDeviceTriggerProperty::FInputDeviceTriggerProperty(), and PropertyName().
Member Function Documentation
PropertyName()
FName FInputDeviceTriggerFeedbackProperty::PropertyName () inline static
Definition at line 198 of file IInputInterface.h.
References FName.
Referenced by FInputDeviceTriggerFeedbackProperty().
Field Documentation
Position
int32 FInputDeviceTriggerFeedbackProperty::Position = 0
Definition at line 200 of file IInputInterface.h.
Strengh
int32 FInputDeviceTriggerFeedbackProperty::Strengh = 0
Definition at line 202 of file IInputInterface.h.
The documentation for this struct was generated from the following file:
IInputInterface.h