Unreal Engine 5.6 C++ API: FNavPathType Struct Reference
FNavPathType Struct Reference
path type data
#include "NavigationTypes.h"
Public Member Functions
FNavPathType (const FNavPathType *Parent=nullptr)
bool IsA (const FNavPathType &Other) const
bool operator== (const FNavPathType &Other) const
Private Attributes
uint32 Id
const FNavPathType * ParentType
Static Private Attributes
static uint32 NextUniqueId
Detailed Description
path type data
Definition at line 315 of file NavigationTypes.h.
Constructor & Destructor Documentation
FNavPathType()
FNavPathType::FNavPathType (const FNavPathType * Parent = nullptr) inline explicit
Definition at line 317 of file NavigationTypes.h.
References FNavPathType(), Id, NextUniqueId, Parent, and ParentType.
Referenced by FNavPathType(), IsA(), and operator==().
Member Function Documentation
IsA()
bool FNavPathType::IsA (const FNavPathType & Other) const inline
Definition at line 324 of file NavigationTypes.h.
References FNavPathType(), Id, Other, and ParentType.
operator==()
bool FNavPathType::operator== (const FNavPathType & Other) const inline
Definition at line 319 of file NavigationTypes.h.
References FNavPathType(), Id, Other, and ParentType.
Field Documentation
Id
uint32 FNavPathType::Id private
Definition at line 331 of file NavigationTypes.h.
Referenced by FNavPathType(), IsA(), and operator==().
NextUniqueId
uint32 FNavPathType::NextUniqueId static private
Definition at line 330 of file NavigationTypes.h.
Referenced by FNavPathType().
ParentType
const FNavPathType* FNavPathType::ParentType private
Definition at line 332 of file NavigationTypes.h.
Referenced by FNavPathType(), IsA(), and operator==().
The documentation for this struct was generated from the following file:
NavigationTypes.h