Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVector< Type, BlockSize > Class Template Reference
UE::Geometry::TDynamicVector< Type, BlockSize > Class Template Reference
#include "DynamicVector.h"
Data Structures
class FConstIterator
class FIterator
struct TBlock
Public Types
using ElementType = Type
Public Member Functions
TDynamicVector ()
TDynamicVector (const TArray< Type > &Array)
TDynamicVector (const TDynamicVector &Copy)
TDynamicVector (TArrayView< const Type > Array)
TDynamicVector (TDynamicVector &&Moved)
~TDynamicVector ()
void Add (const TArray< Type > &Data)
template<int32 BlockSizeData>
void Add (const TDynamicVector< Type, BlockSizeData > &Data)
void Add (const Type &Data)
void Add (TArrayView< const Type > Data)
template<typename Func>
void Apply (const Func &ApplyFunc)
const Type & Back () const
FIterator begin ()
FConstIterator begin () const
void Clear ()
Type & ElementAt (unsigned int Index, Type InitialValue=Type{})
FIterator end ()
FConstIterator end () const
void Fill (const Type &Value)
const Type & Front () const
size_t GetByteCount () const
size_t GetLength () const
void InsertAt (const Type &Data, unsigned int Index)
void InsertAt (const Type &Data, unsigned int Index, const Type &InitValue)
bool IsEmpty () const
size_t Num () const
TDynamicVector & operator= (const TDynamicVector &Copy)
TDynamicVector & operator= (TDynamicVector &&Moved)
Type & operator[] (uint32 Index)
const Type & operator[] (uint32 Index) const
void PopBack ()
void Resize (unsigned int Count)
void Resize (unsigned int Count, const Type &InitValue)
template<bool bForceBulkSerialization = false, bool bUseCompression = false>
void Serialize (FArchive &Ar)
Serialize vector to and from an archive.
bool SetMinimumSize (unsigned int Count, const Type &InitValue)
Resize if Num() is less than Count; returns true if resize occurred.
void SetNum (unsigned int Count)
Static Public Member Functions
static constexpr int32 GetBlockSize ()
Private Member Functions
void AddAllocatedBlock ()
void Empty (int32 NewReservedBlockCount=0)
Type & GetElement (int32 BlockIndex, int32 IndexInBlock)
const Type & GetElement (int32 BlockIndex, int32 IndexInBlock) const
void SetCurBlock (SIZE_T Count)
void TruncateBlocks (int32 NewBlockCount, EAllowShrinking AllowShrinking)
Static Private Member Functions
static constexpr uint32 GetBlockIndex (const uint32 Index)
static constexpr uint32 GetIndexInBlock (const uint32 Index)
static constexpr uint32 NumBitsNeeded (const uint32 N)
Private Attributes
TArray< TBlock * > Blocks
unsigned int CurBlock {0}
unsigned int CurBlockUsed {0}
Friends
template<int32 BlockSizeRhs>
bool operator!= (const TDynamicVector &Lhs, const TDynamicVector< Type, BlockSizeRhs > &Rhs)
FArchive & operator<< (FArchive &Ar, TDynamicVector &Vec)
Serialization operator for TDynamicVector.
template<int32 BlockSizeRhs>
bool operator== (const TDynamicVector &Lhs, const TDynamicVector< Type, BlockSizeRhs > &Rhs)
Detailed Description
template<typename Type, int32 BlockSize = 512>
class UE::Geometry::TDynamicVector< Type, BlockSize >
Definition at line 26 of file DynamicVector.h.
Member Typedef Documentation
ElementType
template<typename Type, int32 BlockSize = 512> using UE::Geometry::TDynamicVector< Type, BlockSize >::ElementType = Type
Definition at line 48 of file DynamicVector.h.
Constructor & Destructor Documentation
TDynamicVector() [1/5]
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector () inline
Definition at line 50 of file DynamicVector.h.
References AddAllocatedBlock().
Referenced by TDynamicVector(), TDynamicVector(), Add(), GetElement(), operator!=, operator<<, operator=(), operator=(), operator==, and operator[]().
TDynamicVector() [2/5]
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector (const TDynamicVector< Type, BlockSize > & Copy) inline
Definition at line 55 of file DynamicVector.h.
References TDynamicVector(), Blocks, Copy, CurBlock, and CurBlockUsed.
TDynamicVector() [3/5]
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector (TDynamicVector< Type, BlockSize > && Moved) inline
Definition at line 67 of file DynamicVector.h.
References TDynamicVector(), Blocks, CurBlock, CurBlockUsed, and MoveTemp().
TDynamicVector() [4/5]
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector (const TArray< Type > & Array) inline
Definition at line 110 of file DynamicVector.h.
References Array, and SetNum().
TDynamicVector() [5/5]
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::TDynamicVector (TArrayView< const Type > Array) inline
Definition at line 121 of file DynamicVector.h.
References Array, and SetNum().
~TDynamicVector()
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::~TDynamicVector () inline
Definition at line 132 of file DynamicVector.h.
References UE::TSharedString< CharType >::Empty.
Member Function Documentation
Add() [1/4]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Add (const TArray< Type > & Data)
Definition at line 688 of file DynamicVector.h.
References Num, TArray< InElementType, InAllocatorType >::Num(), and SetNum().
Add() [2/4]
template<typename Type, int32 BlockSize> template<int32 BlockSizeData> void UE::Geometry::TDynamicVector< Type, BlockSize >::Add (const TDynamicVector< Type, BlockSizeData > & Data)
Definition at line 675 of file DynamicVector.h.
References TDynamicVector(), Num, Num(), and SetNum().
Add() [3/4]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Add (const Type & Data) inline
Definition at line 657 of file DynamicVector.h.
References AddAllocatedBlock(), Blocks, checkSlow, CurBlock, CurBlockUsed, GetElement(), GetLength(), and MAX_uint32.
Referenced by UE::Geometry::FMeshFaceSelection::FloodFill(), and UE::Geometry::FMeshVertexSelection::FloodFill().
Add() [4/4]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Add (TArrayView< const Type > Data)
Definition at line 700 of file DynamicVector.h.
References Num, TArrayView< InElementType, InSizeType >::Num(), and SetNum().
AddAllocatedBlock()
template<typename Type, int32 BlockSize = 512> void UE::Geometry::TDynamicVector< Type, BlockSize >::AddAllocatedBlock () inline private
Definition at line 329 of file DynamicVector.h.
References Blocks.
Referenced by TDynamicVector(), Add(), Clear(), Resize(), and Serialize().
Apply()
template<typename Type, int32 BlockSize> template<typename Func> void UE::Geometry::TDynamicVector< Type, BlockSize >::Apply (const Func & ApplyFunc)
Definition at line 774 of file DynamicVector.h.
References Blocks, CurBlock, and CurBlockUsed.
Back()
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::Back () const inline
Definition at line 167 of file DynamicVector.h.
References checkSlow, CurBlock, CurBlockUsed, and GetElement().
Referenced by UE::Geometry::FMeshFaceSelection::FloodFill(), and UE::Geometry::FMeshVertexSelection::FloodFill().
begin() [1/2]
template<typename Type, int32 BlockSize = 512> FIterator UE::Geometry::TDynamicVector< Type, BlockSize >::begin () inline
Returns
iterator at beginning of vector
Definition at line 259 of file DynamicVector.h.
begin() [2/2]
template<typename Type, int32 BlockSize = 512> FConstIterator UE::Geometry::TDynamicVector< Type, BlockSize >::begin () const inline
Returns
iterator at beginning of vector
Definition at line 308 of file DynamicVector.h.
Clear()
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Clear () inline
Definition at line 573 of file DynamicVector.h.
References AddAllocatedBlock(), Blocks, CurBlock, CurBlockUsed, No, and TruncateBlocks().
ElementAt()
template<typename Type, int32 BlockSize> Type & UE::Geometry::TDynamicVector< Type, BlockSize >::ElementAt (unsigned int Index, Type InitialValue = Type{}) inline
Definition at line 726 of file DynamicVector.h.
References UE::Geometry::Add, GetLength(), and Resize().
Empty()
template<typename Type, int32 BlockSize = 512> void UE::Geometry::TDynamicVector< Type, BlockSize >::Empty (int32 NewReservedBlockCount = 0) inline private
Definition at line 334 of file DynamicVector.h.
References Blocks.
end() [1/2]
template<typename Type, int32 BlockSize = 512> FIterator UE::Geometry::TDynamicVector< Type, BlockSize >::end () inline
Returns
iterator at end of vector
Definition at line 264 of file DynamicVector.h.
References GetLength().
end() [2/2]
template<typename Type, int32 BlockSize = 512> FConstIterator UE::Geometry::TDynamicVector< Type, BlockSize >::end () const inline
Returns
iterator at end of vector
Definition at line 313 of file DynamicVector.h.
References GetLength().
Fill()
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Fill (const Type & Value) inline
Definition at line 585 of file DynamicVector.h.
References Blocks, GetElement(), GetLength(), and Value.
Front()
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::Front () const inline
Definition at line 161 of file DynamicVector.h.
References checkSlow, CurBlockUsed, and GetElement().
GetBlockIndex()
template<typename Type, int32 BlockSize = 512> constexpr uint32 UE::Geometry::TDynamicVector< Type, BlockSize >::GetBlockIndex (const uint32 Index) inline static constexpr private
Definition at line 35 of file DynamicVector.h.
References NumBitsNeeded().
Referenced by operator[](), and SetCurBlock().
GetBlockSize()
template<typename Type, int32 BlockSize = 512> constexpr int32 UE::Geometry::TDynamicVector< Type, BlockSize >::GetBlockSize () inline static constexpr
Definition at line 148 of file DynamicVector.h.
GetByteCount()
template<typename Type, int32 BlockSize = 512> size_t UE::Geometry::TDynamicVector< Type, BlockSize >::GetByteCount () const inline
Definition at line 149 of file DynamicVector.h.
References Blocks.
GetElement() [1/2]
template<typename Type, int32 BlockSize = 512> Type & UE::Geometry::TDynamicVector< Type, BlockSize >::GetElement (int32 BlockIndex, int32 IndexInBlock) inline private
Definition at line 349 of file DynamicVector.h.
References TDynamicVector().
GetElement() [2/2]
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::GetElement (int32 BlockIndex, int32 IndexInBlock) const inline private
Definition at line 343 of file DynamicVector.h.
References Blocks, and checkSlow.
Referenced by Add(), Back(), Fill(), Front(), and operator[]().
GetIndexInBlock()
template<typename Type, int32 BlockSize = 512> constexpr uint32 UE::Geometry::TDynamicVector< Type, BlockSize >::GetIndexInBlock (const uint32 Index) inline static constexpr private
Definition at line 41 of file DynamicVector.h.
Referenced by operator[](), and SetCurBlock().
GetLength()
template<typename Type, int32 BlockSize = 512> size_t UE::Geometry::TDynamicVector< Type, BlockSize >::GetLength () const inline
Definition at line 146 of file DynamicVector.h.
References CurBlock, and CurBlockUsed.
Referenced by Add(), ElementAt(), end(), end(), Fill(), InsertAt(), InsertAt(), Num(), Resize(), Resize(), and SetMinimumSize().
InsertAt() [1/2]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::InsertAt (const Type & Data, unsigned int Index) inline
Definition at line 742 of file DynamicVector.h.
References UE::Geometry::Add, GetLength(), and Resize().
Referenced by UE::Geometry::FSegmentTree3::BuildTopDown(), InsertAt(), UE::Geometry::TDynamicMeshScalarTriangleAttribute< int32 >::SetNewValue(), UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint().
InsertAt() [2/2]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::InsertAt (const Type & Data, unsigned int Index, const Type & InitValue) inline
Definition at line 761 of file DynamicVector.h.
References GetLength(), and InsertAt().
IsEmpty()
template<typename Type, int32 BlockSize = 512> bool UE::Geometry::TDynamicVector< Type, BlockSize >::IsEmpty () const inline
Definition at line 145 of file DynamicVector.h.
References CurBlock, and CurBlockUsed.
Referenced by operator==.
Num()
template<typename Type, int32 BlockSize = 512> size_t UE::Geometry::TDynamicVector< Type, BlockSize >::Num () const inline
Definition at line 147 of file DynamicVector.h.
References GetLength().
Referenced by Add(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::Append(), UE::Geometry::FSegmentTree3::BuildTopDown(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::CompactCopy(), UE::Geometry::FMeshFaceSelection::FloodFill(), UE::Geometry::FMeshVertexSelection::FloodFill(), operator==, and operator[]().
NumBitsNeeded()
template<typename Type, int32 BlockSize = 512> constexpr uint32 UE::Geometry::TDynamicVector< Type, BlockSize >::NumBitsNeeded (const uint32 N) inline static constexpr private
Definition at line 31 of file DynamicVector.h.
References NumBitsNeeded().
Referenced by GetBlockIndex(), and NumBitsNeeded().
operator=() [1/2]
template<typename Type, int32 BlockSize = 512> TDynamicVector & UE::Geometry::TDynamicVector< Type, BlockSize >::operator= (const TDynamicVector< Type, BlockSize > & Copy) inline
Definition at line 77 of file DynamicVector.h.
References TDynamicVector(), Blocks, Copy, CurBlock, CurBlockUsed, and UE::TSharedString< CharType >::Empty.
operator=() [2/2]
template<typename Type, int32 BlockSize = 512> TDynamicVector & UE::Geometry::TDynamicVector< Type, BlockSize >::operator= (TDynamicVector< Type, BlockSize > && Moved) inline
Definition at line 93 of file DynamicVector.h.
References TDynamicVector(), Blocks, CurBlock, CurBlockUsed, MoveTemp(), and UE::TSharedString< CharType >::Empty.
operator[]() [1/2]
template<typename Type, int32 BlockSize = 512> Type & UE::Geometry::TDynamicVector< Type, BlockSize >::operator[] (uint32 Index) inline
Definition at line 185 of file DynamicVector.h.
References TDynamicVector().
operator[]() [2/2]
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::operator[] (uint32 Index) const inline
Definition at line 176 of file DynamicVector.h.
References checkSlow, GetBlockIndex(), GetElement(), GetIndexInBlock(), and Num().
PopBack()
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::PopBack () inline
Definition at line 712 of file DynamicVector.h.
References CurBlock, and CurBlockUsed.
Referenced by UE::Geometry::FMeshFaceSelection::FloodFill(), and UE::Geometry::FMeshVertexSelection::FloodFill().
Resize() [1/2]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Resize (unsigned int Count) inline
Definition at line 598 of file DynamicVector.h.
References AddAllocatedBlock(), Blocks, UE::Count, GetLength(), FMath::Max, No, SetCurBlock(), and TruncateBlocks().
Referenced by ElementAt(), InsertAt(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), Resize(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize(), SetMinimumSize(), and SetNum().
Resize() [2/2]
template<typename Type, int32 BlockSize> void UE::Geometry::TDynamicVector< Type, BlockSize >::Resize (unsigned int Count, const Type & InitValue) inline
Definition at line 630 of file DynamicVector.h.
References UE::Count, GetLength(), and Resize().
Serialize()
template<typename Type, int32 BlockSize> template<bool bForceBulkSerialization, bool bUseCompression> void UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize (FArchive & Ar)
Serialize vector to and from an archive.
Template Parameters
bForceBulkSerialization Forces serialization to consider data to be trivial and serialize it in bulk to potentially achieve better performance.
bUseCompression Use compression to serialize data; the resulting size will likely be smaller but serialization will take significantly longer.
Parameters
Ar Archive to serialize with
Definition at line 789 of file DynamicVector.h.
References UE::Geometry::Add, AddAllocatedBlock(), Ar, BlockElements, Blocks, Buffer, Clear(), COMPRESS_NoFlags, CurBlock, CurBlockUsed, UE::Geometry::TDynamicVector< Type, BlockSize >::TBlock::Elements, TArray< InElementType, InAllocatorType >::GetData(), FUE5MainStreamObjectVersion::GUID, LARGE_WORLD_COORDINATES, FMemory::Memcpy(), FMath::Min, Num, SetCurBlock(), TArray< InElementType, InAllocatorType >::SetNum(), UE::TSharedString< CharType >::Empty, and TCanBulkSerialize< T >::Value.
Referenced by operator<<, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize().
SetCurBlock()
template<typename Type, int32 BlockSize = 512> void UE::Geometry::TDynamicVector< Type, BlockSize >::SetCurBlock (SIZE_T Count) inline private
Definition at line 409 of file DynamicVector.h.
References UE::Count, CurBlock, CurBlockUsed, GetBlockIndex(), and GetIndexInBlock().
Referenced by Resize(), and Serialize().
SetMinimumSize()
template<typename Type, int32 BlockSize> bool UE::Geometry::TDynamicVector< Type, BlockSize >::SetMinimumSize (unsigned int Count, const Type & InitValue) inline
Resize if Num() is less than Count; returns true if resize occurred.
Definition at line 641 of file DynamicVector.h.
References UE::Count, GetLength(), and Resize().
SetNum()
template<typename Type, int32 BlockSize = 512> void UE::Geometry::TDynamicVector< Type, BlockSize >::SetNum (unsigned int Count) inline
Definition at line 143 of file DynamicVector.h.
References UE::Count, and Resize().
Referenced by TDynamicVector(), TDynamicVector(), Add(), Add(), Add(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Serialize(), and UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::Serialize().
TruncateBlocks()
template<typename Type, int32 BlockSize = 512> void UE::Geometry::TDynamicVector< Type, BlockSize >::TruncateBlocks (int32 NewBlockCount, EAllowShrinking AllowShrinking) inline private
Definition at line 354 of file DynamicVector.h.
References Blocks.
Referenced by Clear(), and Resize().
Friends And Related Symbol Documentation
operator!=
template<typename Type, int32 BlockSize = 512> template<int32 BlockSizeRhs> bool operator!= (const TDynamicVector< Type, BlockSize > & Lhs, const TDynamicVector< Type, BlockSizeRhs > & Rhs) friend
Definition at line 404 of file DynamicVector.h.
References TDynamicVector().
operator<<
template<typename Type, int32 BlockSize = 512> FArchive & operator<< (FArchive & Ar, TDynamicVector< Type, BlockSize > & Vec) friend
Serialization operator for TDynamicVector.
Parameters
Ar Archive to serialize with.
Vec Vector to serialize.
Returns
Passing down serializing archive.
Definition at line 201 of file DynamicVector.h.
References TDynamicVector(), Ar, and Serialize().
operator==
template<typename Type, int32 BlockSize = 512> template<int32 BlockSizeRhs> bool operator== (const TDynamicVector< Type, BlockSize > & Lhs, const TDynamicVector< Type, BlockSizeRhs > & Rhs) friend
Definition at line 365 of file DynamicVector.h.
References TDynamicVector(), Blocks, CompareItems(), CurBlock, CurBlockUsed, IsEmpty(), and Num().
Field Documentation
Blocks
template<typename Type, int32 BlockSize = 512> TArray<TBlock*> UE::Geometry::TDynamicVector< Type, BlockSize >::Blocks private
Definition at line 327 of file DynamicVector.h.
Referenced by TDynamicVector(), TDynamicVector(), Add(), AddAllocatedBlock(), Apply(), Clear(), Empty(), Fill(), GetByteCount(), GetElement(), operator=(), operator=(), operator==, Resize(), Serialize(), and TruncateBlocks().
CurBlock
template<typename Type, int32 BlockSize = 512> unsigned int UE::Geometry::TDynamicVector< Type, BlockSize >::CurBlock {0} private
Definition at line 324 of file DynamicVector.h.
Referenced by TDynamicVector(), TDynamicVector(), Add(), Apply(), Back(), Clear(), GetLength(), IsEmpty(), operator=(), operator=(), operator==, PopBack(), Serialize(), and SetCurBlock().
CurBlockUsed
template<typename Type, int32 BlockSize = 512> unsigned int UE::Geometry::TDynamicVector< Type, BlockSize >::CurBlockUsed {0} private
Definition at line 325 of file DynamicVector.h.
Referenced by TDynamicVector(), TDynamicVector(), Add(), Apply(), Back(), Clear(), Front(), GetLength(), IsEmpty(), operator=(), operator=(), operator==, PopBack(), Serialize(), and SetCurBlock().
The documentation for this class was generated from the following file:
DynamicVector.h