Unreal Engine 5.6 C++ API: IPixelStreaming2HMDModule Class Reference
IPixelStreaming2HMDModule Class Reference abstract
The public interface provides functionality for interacting with Pixel Streaming and Head Mounted Display (HMD) systems.
#include "IPixelStreaming2HMDModule.h"
Public Member Functions
virtual EPixelStreaming2XRSystem GetActiveXRSystem ()=0
Get the Active XR System.
virtual IPixelStreaming2HMD * GetPixelStreaming2HMD () const =0
Get the Pixel Streaming HMD object.
virtual void SetActiveXRSystem (EPixelStreaming2XRSystem System)=0
Set the Active XR System.
Static Public Member Functions
static IPixelStreaming2HMDModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
The public interface provides functionality for interacting with Pixel Streaming and Head Mounted Display (HMD) systems.
Definition at line 14 of file IPixelStreaming2HMDModule.h.
Member Function Documentation
Get()
IPixelStreaming2HMDModule & IPixelStreaming2HMDModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 23 of file IPixelStreaming2HMDModule.h.
References FModuleManager::LoadModuleChecked().
GetActiveXRSystem()
virtual EPixelStreaming2XRSystem IPixelStreaming2HMDModule::GetActiveXRSystem () pure virtual
Get the Active XR System.
Returns
The Active XR System.
GetPixelStreaming2HMD()
virtual IPixelStreaming2HMD * IPixelStreaming2HMDModule::GetPixelStreaming2HMD () const pure virtual
Get the Pixel Streaming HMD object.
Returns
Pointer to the Pixel Streaming HMD.
IsAvailable()
bool IPixelStreaming2HMDModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 32 of file IPixelStreaming2HMDModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
SetActiveXRSystem()
virtual void IPixelStreaming2HMDModule::SetActiveXRSystem (EPixelStreaming2XRSystem System) pure virtual
Set the Active XR System.
Parameters
System The Active XR System to set.
The documentation for this class was generated from the following file:
IPixelStreaming2HMDModule.h