Unreal Engine 5.6 C++ API: TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal Struct Reference
TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal Struct Reference
#include "MallocBinnedCommon.h"
Public Types
using PoolInfo = typename AllocType::FPoolInfo
Static Public Member Functions
static PoolInfo * FindPoolInfo (AllocType &Allocator, void *InPtr)
static PoolInfo * GetOrCreatePoolInfo (AllocType &Allocator, void *InPtr, typename PoolInfo::ECanary Kind)
Gets the PoolInfo for a large block memory address.
Detailed Description
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize>
struct TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal
Definition at line 616 of file MallocBinnedCommon.h.
Member Typedef Documentation
PoolInfo
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> using TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal::PoolInfo = typename AllocType::FPoolInfo
Definition at line 618 of file MallocBinnedCommon.h.
Member Function Documentation
FindPoolInfo()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> PoolInfo * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal::FindPoolInfo (AllocType & Allocator, void * InPtr) inline static
Definition at line 710 of file MallocBinnedCommon.h.
References Allocator, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::BucketIndex, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::FirstPool, and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::Next.
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetAllocationSizeExternal().
GetOrCreatePoolInfo()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> PoolInfo * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal::GetOrCreatePoolInfo (AllocType & Allocator, void * InPtr, typename PoolInfo::ECanary Kind) inline static
Gets the PoolInfo for a large block memory address.
If no valid info exists one is created.
Creates an array of PoolInfo structures for tracking allocations.
Definition at line 622 of file MallocBinnedCommon.h.
References Allocator, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::BucketIndex, DefaultConstructItems(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::FirstPool, FMallocBinnedCommonBase::HashMemory, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::Link(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::Next, OutOfMemory, FMallocBinnedCommonBase::PoolInfoMemory, UE_MBC_UPDATE_STATS, and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPoolHashBucket::Unlink().
The documentation for this struct was generated from the following file:
MallocBinnedCommon.h