Unreal Engine 5.6 C++ API: AudioComponent.h File Reference
AudioComponent.h File Reference
#include "Audio.h"
#include "Audio/SoundParameterControllerInterface.h"
#include "Components/SceneComponent.h"
#include "CoreMinimal.h"
#include "Engine/EngineTypes.h"
#include "IAudioParameterTransmitter.h"
#include "Math/RandomStream.h"
#include "Misc/TransactionallySafeCriticalSection.h"
#include "Quartz/AudioMixerQuantizedCommands.h"
#include "Sound/QuartzQuantizationUtilities.h"
#include "Sound/QuartzSubscription.h"
#include "Sound/SoundAttenuation.h"
#include "Sound/SoundModulationDestination.h"
#include "Sound/SoundSubmixSend.h"
#include "Sound/SoundSourceBusSend.h"
#include "UObject/ObjectMacros.h"
#include "AudioComponent.generated.h"
Data Structures
class UAudioComponent
struct UAudioComponent::FAudioComponentPendingQuartzCommandData
struct UAudioComponent::FPendingSourceBusSendInfo
struct UAudioComponent::FSoundWavePlaybackTimeData
struct UAudioComponent::PlayInternalRequestData
Typedefs
using FSharedISourceBufferListenerPtr = TSharedPtr<ISourceBufferListener, ESPMode::ThreadSafe>
Functions
DECLARE_DYNAMIC_DELEGATE_TwoParams (FOnQueueSubtitles, const TArray< struct FSubtitleCue > &, Subtitles, float, CueDuration)
Called when subtitles are sent to the SubtitleManager.
UENUM() enum class EAudioComponentPlayState DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnAudioFinished)
called when we finish playing audio, either because it played to completion or because a Stop() call turned it off early
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnAudioPlayStateChanged, EAudioComponentPlayState, PlayState)
Called when sound's PlayState changes.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnAudioVirtualizationChanged, bool, bIsVirtualized)
Called when sound becomes virtualized or realized (resumes playback from virtualization).
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams (FOnAudioMultiEnvelopeValue, const float, AverageEnvelopeValue, const float, MaxEnvelope, const int32, NumWaveInstances)
Called while a sound plays and returns the sound's average and max envelope value (using an envelope follower in the audio renderer per wave instance).
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnAudioPlaybackPercent, const USoundWave *, PlayingSoundWave, const float, PlaybackPercent)
Called as a sound plays on the audio component to allow BP to perform actions based on playback percentage.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnAudioSingleEnvelopeValue, const class USoundWave *, PlayingSoundWave, const float, EnvelopeValue)
Called while a sound plays and returns the sound's envelope value (using an envelope follower in the audio renderer).
DECLARE_MULTICAST_DELEGATE_FourParams (FOnAudioMultiEnvelopeValueNative, const UAudioComponent *, const float, const float, const int32)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAudioFinishedNative, UAudioComponent *)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnAudioPlaybackPercentNative, const UAudioComponent *, const USoundWave *, const float)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnAudioSingleEnvelopeValueNative, const UAudioComponent *, const USoundWave *, const float)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAudioPlayStateChangedNative, const UAudioComponent *, EAudioComponentPlayState)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAudioVirtualizationChangedNative, const UAudioComponent *, bool)
shadow delegate declaration for above
UCLASS() class UInitialActiveSoundParams UCLASS ()
Convenience class to get audio parameters set on an active sound's playback.
UENUM() enum class EAudioFaderCurve USTRUCT () struct UE_DEPRECATED(5.0
Type of fade to use when adjusting the audio component's volume.
Variables
UENUM() enum class EAudioFaderCurve FAudioComponentParam has been deprecated
UENUM() enum class EAudioFaderCurve FAudioComponentParam has been use FAudioParameter FAudioComponentParam
UCLASS() class UInitialActiveSoundParams HideCategories =(Object, ActorComponent, Physics, Rendering, Mobility, LOD)
UCLASS() class UInitialActiveSoundParams meta =(BlueprintSpawnableComponent)
UCLASS() class UInitialActiveSoundParams ShowCategories =Trigger
Typedef Documentation
FSharedISourceBufferListenerPtr
using FSharedISourceBufferListenerPtr = TSharedPtr<ISourceBufferListener, ESPMode::ThreadSafe>
Definition at line 34 of file AudioComponent.h.
Function Documentation
DECLARE_DYNAMIC_DELEGATE_TwoParams()
DECLARE_DYNAMIC_DELEGATE_TwoParams (FOnQueueSubtitles , const TArray< struct FSubtitleCue > & , Subtitles , float , CueDuration)
Called when subtitles are sent to the SubtitleManager.
Set this delegate if you want to hijack the subtitles for other purposes
References Subtitles.
DECLARE_DYNAMIC_MULTICAST_DELEGATE()
UENUM() enum class EAudioComponentPlayState DECLARE_DYNAMIC_MULTICAST_DELEGATE (FOnAudioFinished)
called when we finish playing audio, either because it played to completion or because a Stop() call turned it off early
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam() [1/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnAudioPlayStateChanged , EAudioComponentPlayState , PlayState)
Called when sound's PlayState changes.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam() [2/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnAudioVirtualizationChanged , bool , bIsVirtualized)
Called when sound becomes virtualized or realized (resumes playback from virtualization).
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams (FOnAudioMultiEnvelopeValue , const float , AverageEnvelopeValue , const float , MaxEnvelope , const int32 , NumWaveInstances)
Called while a sound plays and returns the sound's average and max envelope value (using an envelope follower in the audio renderer per wave instance).
This only works in the audio mixer.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [1/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnAudioPlaybackPercent , const USoundWave * , PlayingSoundWave , const float , PlaybackPercent)
Called as a sound plays on the audio component to allow BP to perform actions based on playback percentage.
Computed as samples played divided by total samples, taking into account pitch. Not currently implemented on all platforms.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [2/2]
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnAudioSingleEnvelopeValue , const class USoundWave * , PlayingSoundWave , const float , EnvelopeValue)
Called while a sound plays and returns the sound's envelope value (using an envelope follower in the audio renderer).
This only works in the audio mixer.
DECLARE_MULTICAST_DELEGATE_FourParams()
DECLARE_MULTICAST_DELEGATE_FourParams (FOnAudioMultiEnvelopeValueNative , const UAudioComponent * , const float , const float , const int32)
shadow delegate declaration for above
References BlueprintType, Count, Hidden, and Linear.
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAudioFinishedNative , UAudioComponent *)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnAudioPlaybackPercentNative , const UAudioComponent * , const USoundWave * , const float)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnAudioSingleEnvelopeValueNative , const UAudioComponent * , const USoundWave * , const float)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/2]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAudioPlayStateChangedNative , const UAudioComponent * , EAudioComponentPlayState)
shadow delegate declaration for above
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/2]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAudioVirtualizationChangedNative , const UAudioComponent * , bool)
shadow delegate declaration for above
UCLASS()
UCLASS() class UInitialActiveSoundParams UCLASS ()
Convenience class to get audio parameters set on an active sound's playback.
AudioComponent is used to play a Sound
See also
https://docs.unrealengine.com/WorkingWithAudio/Overview
USoundBase
USTRUCT()
UENUM() enum class EAudioFaderCurve USTRUCT ()
Type of fade to use when adjusting the audio component's volume.
Legacy struct used for storing named parameter for a given AudioComponent.
Variable Documentation
deprecated
FLandscapeProxyMaterialOverride is deprecated
Definition at line 133 of file AudioComponent.h.
FAudioComponentParam
UENUM() enum class EAudioFaderCurve FAudioComponentParam has been use FAudioParameter FAudioComponentParam
Definition at line 133 of file AudioComponent.h.
HideCategories
UCLASS() class UInitialActiveSoundParams HideCategories =(Object, ActorComponent, Physics, Rendering, Mobility, LOD)
Definition at line 166 of file AudioComponent.h.
meta
UCLASS() class UInitialActiveSoundParams meta =(BlueprintSpawnableComponent)
Definition at line 166 of file AudioComponent.h.
Referenced by UAudioComponent::UFUNCTION(), UAudioComponent::UFUNCTION(), UAudioComponent::UFUNCTION(), UAudioComponent::UFUNCTION(), UAudioComponent::UFUNCTION(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), UAudioComponent::UPROPERTY(), and UAudioComponent::UPROPERTY().
ShowCategories
UCLASS() class UInitialActiveSoundParams ShowCategories =Trigger
Definition at line 166 of file AudioComponent.h.