Unreal Engine 5.6 C++ API: FIoRequestImpl Class Reference
FIoRequestImpl Class Reference
I/O request object.
#include "IoDispatcherBackend.h"
Public Member Functions
FIoRequestImpl (class FIoRequestAllocator &InAllocator)
void CreateBuffer (uint64 Size)
Creates a new buffer for the request.
FIoBuffer & GetBuffer ()
Returns the internal buffer.
uint64 GetStartTime () const
bool HasBuffer () const
Returns whether request has a valid buffer.
bool IsCancelled () const
Returns whether the request has been cancelled.
bool IsFailed () const
Returns whether the request failed.
void SetFailed ()
Mark the request as failed (EIoErrorCode::ReadError).
void SetLastBackendError (EIoErrorCode InError)
void SetResult (FIoBuffer InBuffer)
Sets a new buffer.
Data Fields
void * BackendData = nullptr
Custom data that can be used freely by the I/O dispatcher backend(s).
FIoChunkId ChunkId
The chunk ID.
FIoRequestImpl * NextRequest = nullptr
Pointer to the next request that can be used freely by the I/O dispatcher backend(s).
FIoReadOptions Options
Read options.
int32 Priority = 0
I/O dispatcher priority (EIoDispatcherPriority).
Private Member Functions
void AddRef ()
void FreeRequest ()
void ReleaseRef ()
Private Member Functions inherited from UE::FInheritedContextBase
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Private Attributes
FIoRequestAllocator & Allocator
struct IIoDispatcherBackend * Backend = nullptr
FIoBatchImpl * Batch = nullptr
TOptional< FIoBuffer > Buffer
FIoReadCallback Callback
TAtomic< EIoErrorCode > ErrorCode { EIoErrorCode::Unknown }
EIoErrorCode LastBackendError = EIoErrorCode::Ok
TAtomic< uint32 > RefCount { 0 }
Friends
class FIoBatch
class FIoDispatcherImpl
class FIoRequest
class FIoRequestStats
Detailed Description
I/O request object.
Definition at line 22 of file IoDispatcherBackend.h.
Constructor & Destructor Documentation
FIoRequestImpl()
FIoRequestImpl::FIoRequestImpl (class FIoRequestAllocator & InAllocator) inline
Definition at line 36 of file IoDispatcherBackend.h.
References Allocator, and UE::FInheritedContextBase::CaptureInheritedContext().
Member Function Documentation
AddRef()
void FIoRequestImpl::AddRef () inline private
Definition at line 109 of file IoDispatcherBackend.h.
References RefCount.
CreateBuffer()
void FIoRequestImpl::CreateBuffer (uint64 Size)
Creates a new buffer for the request.
References TSequenceHistory< HistorySize >::Size.
FreeRequest()
void FIoRequestImpl::FreeRequest () private
Referenced by ReleaseRef().
GetBuffer()
FIoBuffer & FIoRequestImpl::GetBuffer () inline
Returns the internal buffer.
Definition at line 83 of file IoDispatcherBackend.h.
References Buffer.
GetStartTime()
uint64 FIoRequestImpl::GetStartTime () const inline
Definition at line 94 of file IoDispatcherBackend.h.
HasBuffer()
bool FIoRequestImpl::HasBuffer () const inline
Returns whether request has a valid buffer.
Definition at line 74 of file IoDispatcherBackend.h.
References Buffer.
IsCancelled()
bool FIoRequestImpl::IsCancelled () const inline
Returns whether the request has been cancelled.
Definition at line 43 of file IoDispatcherBackend.h.
References Cancelled, and LastBackendError.
Referenced by SetFailed(), and SetLastBackendError().
IsFailed()
bool FIoRequestImpl::IsFailed () const inline
Returns whether the request failed.
Definition at line 49 of file IoDispatcherBackend.h.
References Cancelled, LastBackendError, and Ok.
ReleaseRef()
void FIoRequestImpl::ReleaseRef () inline private
Definition at line 114 of file IoDispatcherBackend.h.
References FreeRequest(), and RefCount.
SetFailed()
void FIoRequestImpl::SetFailed () inline
Mark the request as failed (EIoErrorCode::ReadError).
Definition at line 57 of file IoDispatcherBackend.h.
References IsCancelled(), LastBackendError, and ReadError.
SetLastBackendError()
void FIoRequestImpl::SetLastBackendError (EIoErrorCode InError) inline
Definition at line 65 of file IoDispatcherBackend.h.
References IsCancelled(), and LastBackendError.
SetResult()
void FIoRequestImpl::SetResult (FIoBuffer InBuffer) inline
Sets a new buffer.
Definition at line 89 of file IoDispatcherBackend.h.
References Buffer.
Friends And Related Symbol Documentation
FIoBatch
friend class FIoBatch friend
Definition at line 106 of file IoDispatcherBackend.h.
References FIoBatch.
Referenced by FIoBatch.
FIoDispatcherImpl
friend class FIoDispatcherImpl friend
Definition at line 104 of file IoDispatcherBackend.h.
References FIoDispatcherImpl.
Referenced by FIoDispatcherImpl.
FIoRequest
friend class FIoRequest friend
Definition at line 105 of file IoDispatcherBackend.h.
References FIoRequest.
Referenced by FIoRequest.
FIoRequestStats
friend class FIoRequestStats friend
Definition at line 107 of file IoDispatcherBackend.h.
References FIoRequestStats.
Referenced by FIoRequestStats.
Field Documentation
Allocator
FIoRequestAllocator& FIoRequestImpl::Allocator private
Definition at line 124 of file IoDispatcherBackend.h.
Referenced by FIoRequestImpl().
Backend
struct IIoDispatcherBackend* FIoRequestImpl::Backend = nullptr private
Definition at line 125 of file IoDispatcherBackend.h.
BackendData
void* FIoRequestImpl::BackendData = nullptr
Custom data that can be used freely by the I/O dispatcher backend(s).
Definition at line 28 of file IoDispatcherBackend.h.
Batch
FIoBatchImpl* FIoRequestImpl::Batch = nullptr private
Definition at line 126 of file IoDispatcherBackend.h.
Buffer
TOptional<FIoBuffer> FIoRequestImpl::Buffer private
Definition at line 130 of file IoDispatcherBackend.h.
Referenced by GetBuffer(), HasBuffer(), and SetResult().
Callback
FIoReadCallback FIoRequestImpl::Callback private
Definition at line 131 of file IoDispatcherBackend.h.
ChunkId
FIoChunkId FIoRequestImpl::ChunkId
The chunk ID.
Definition at line 30 of file IoDispatcherBackend.h.
ErrorCode
TAtomic<EIoErrorCode> FIoRequestImpl::ErrorCode { EIoErrorCode::Unknown } private
Definition at line 133 of file IoDispatcherBackend.h.
LastBackendError
EIoErrorCode FIoRequestImpl::LastBackendError = EIoErrorCode::Ok private
Definition at line 134 of file IoDispatcherBackend.h.
Referenced by IsCancelled(), IsFailed(), SetFailed(), and SetLastBackendError().
NextRequest
FIoRequestImpl* FIoRequestImpl::NextRequest = nullptr
Pointer to the next request that can be used freely by the I/O dispatcher backend(s).
Definition at line 26 of file IoDispatcherBackend.h.
Referenced by UE::Private::FIoRequestListTraits::GetNext(), and UE::Private::FIoRequestListTraits::SetNext().
Options
FIoReadOptions FIoRequestImpl::Options
Read options.
Definition at line 32 of file IoDispatcherBackend.h.
Priority
int32 FIoRequestImpl::Priority = 0
I/O dispatcher priority (EIoDispatcherPriority).
Definition at line 34 of file IoDispatcherBackend.h.
RefCount
TAtomic<uint32> FIoRequestImpl::RefCount { 0 } private
Definition at line 132 of file IoDispatcherBackend.h.
Referenced by AddRef(), and ReleaseRef().
The documentation for this class was generated from the following file:
IoDispatcherBackend.h