Unreal Engine 5.6 C++ API: ISoundHandleSystem Class Reference
ISoundHandleSystem Class Reference
This interface should be used with systems aiming to create Sound Handles: gameplay thread representations of sounds.
#include "ISoundHandleSystem.h"
Public Member Functions
virtual ~ISoundHandleSystem ()=default
virtual Audio::FSoundHandleID CreateSoundHandle (USoundBase *Sound, ISoundHandleOwner *Owner)
This should create a sound and we should map it to an identifier.
virtual Audio::EResult Play (Audio::FSoundHandleID ID)
Play the sound that is represented by the sound handle with the following ID.
virtual void SetTransform (Audio::FSoundHandleID ID, const FTransform &Transform)
Set the transform on the sound that is represented by the sound handle with the following ID.
virtual void Stop (Audio::FSoundHandleID ID)
Stop the sound that is represented by the sound handle with the following ID.
Static Public Member Functions
static FName GetModularFeatureName ()
Get the name of all Sound Handle implementations in the Modular Features registry.
static TArray< ISoundHandleSystem * > GetRegisteredInterfaces ()
Detailed Description
This interface should be used with systems aiming to create Sound Handles: gameplay thread representations of sounds.
Definition at line 25 of file ISoundHandleSystem.h.
Constructor & Destructor Documentation
~ISoundHandleSystem()
virtual ISoundHandleSystem::~ISoundHandleSystem () virtual default
Member Function Documentation
CreateSoundHandle()
virtual Audio::FSoundHandleID ISoundHandleSystem::CreateSoundHandle (USoundBase * Sound, ISoundHandleOwner * Owner) inline virtual
This should create a sound and we should map it to an identifier.
Then return the identifier to the owner to keep track of
Parameters
Sound
Owner
Returns
Definition at line 48 of file ISoundHandleSystem.h.
References INDEX_NONE, Owner, and Sound.
GetModularFeatureName()
FName ISoundHandleSystem::GetModularFeatureName () inline static
Get the name of all Sound Handle implementations in the Modular Features registry.
Returns
"SoundHandles"
Definition at line 32 of file ISoundHandleSystem.h.
References FName, and TEXT.
Referenced by GetRegisteredInterfaces().
GetRegisteredInterfaces()
TArray< ISoundHandleSystem * > ISoundHandleSystem::GetRegisteredInterfaces () inline static
Definition at line 72 of file ISoundHandleSystem.h.
References IModularFeatures::Get(), IModularFeatures::GetModularFeatureImplementations(), GetModularFeatureName(), IModularFeatures::LockModularFeatureList(), and IModularFeatures::UnlockModularFeatureList().
Referenced by ISoundHandleOwner::CreateSoundHandle().
Play()
virtual Audio::EResult ISoundHandleSystem::Play (Audio::FSoundHandleID ID) inline virtual
Play the sound that is represented by the sound handle with the following ID.
Parameters
ID
Definition at line 63 of file ISoundHandleSystem.h.
References ID, and Audio::NotImplemented.
SetTransform()
virtual void ISoundHandleSystem::SetTransform (Audio::FSoundHandleID ID, const FTransform & Transform) inline virtual
Set the transform on the sound that is represented by the sound handle with the following ID.
Parameters
ID
Transform
Definition at line 56 of file ISoundHandleSystem.h.
References ID, and Transform.
Stop()
virtual void ISoundHandleSystem::Stop (Audio::FSoundHandleID ID) inline virtual
Stop the sound that is represented by the sound handle with the following ID.
Parameters
ID
Definition at line 70 of file ISoundHandleSystem.h.
References ID.
The documentation for this class was generated from the following file:
ISoundHandleSystem.h