Unreal Engine 5.6 C++ API: ShaderParameterStruct.h File Reference
ShaderParameterStruct.h File Reference
#include "Containers/Array.h"
#include "CoreMinimal.h"
#include "HAL/Platform.h"
#include "Misc/AssertionMacros.h"
#include "RHI.h"
#include "RHIDefinitions.h"
#include "RenderGraphResources.h"
#include "Serialization/MemoryImage.h"
#include "Shader.h"
Macros
#define SHADER_ROOT_PARAMETERS_SIGNATURE()
#define SHADER_USE_PARAMETER_STRUCT(ShaderClass, ShaderParentClass)
#define SHADER_USE_PARAMETER_STRUCT_INTERNAL(ShaderClass, ShaderParentClass, bShouldBindEverything)
Tag a shader class to use the structured shader parameters API.
#define SHADER_USE_PARAMETER_STRUCT_MIXED(ShaderClass, ShaderParentClass)
Use when sharing shader parameter binding with legacy parameters in the base class; i.e.
#define SHADER_USE_PARAMETER_STRUCT_WITH_LEGACY_BASE(ShaderClass, ShaderParentClass)
Use when sharing shader parameter binding with legacy parameters in the base class; i.e.
#define SHADER_USE_ROOT_PARAMETER_STRUCT(ShaderClass, ShaderParentClass)
Functions
template<typename FParameterStruct>
void BindForLegacyShaderParameters (FShader *Shader, int32 PermutationId, const FShaderParameterMap &ParameterMap, bool bShouldBindEverything=false)
template<typename TParameterType>
void CollectSRVsToUnset (FRHIBatchedShaderUnbinds &BatchedUnbinds, const TMemoryImageArray< TParameterType > &InParameters)
template<typename TParameterType>
void CollectUAVsToUnset (FRHIBatchedShaderUnbinds &BatchedUnbinds, const TMemoryImageArray< TParameterType > &InParameters)
RENDERCORE_API void EmitNullShaderParameterFatalError (const TShaderRef< FShader > &Shader, const FShaderParametersMetadata *ParametersMetadata, uint16 MemberOffset)
Raise fatal error when a required shader parameter has not been set.
FRHIResource * GetShaderParameterResourceRHI (const void *Contents, uint16 MemberOffset, EUniformBufferBaseType MemberType)
Dereferences the RHI resource from a shader parameter struct.
RENDERCORE_API void SetAllShaderParametersAsBindless (FRHIBatchedShaderParameters &BatchedParameters, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
Set all resources described by ParametersMetadata using data from ParametersData as BindlessParameters.
template<typename TParameters>
void SetAllShaderParametersAsBindless (FRHIBatchedShaderParameters &BatchedParameters, const TParameters &InParameters)
RENDERCORE_API void SetShaderParameters (FRHIBatchedShaderParameters &BatchedParameters, const FShaderParameterBindings &Bindings, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
template<typename TShaderClass>
void SetShaderParameters (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderClass > &Shader, const FShaderParametersMetadata *ParametersMetadata, const typename TShaderClass::FParameters &Parameters)
template<typename TShaderClass>
void SetShaderParameters (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderClass > &Shader, const typename TShaderClass::FParameters &Parameters)
RENDERCORE_API void SetShaderParameters (FRHICommandList &RHICmdList, FRHIComputeShader *ShaderRHI, const FShaderParameterBindings &Bindings, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
RENDERCORE_API void SetShaderParameters (FRHICommandList &RHICmdList, FRHIGraphicsShader *ShaderRHI, const FShaderParameterBindings &Bindings, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
RENDERCORE_API void SetShaderParameters (FRHIComputeCommandList &RHICmdList, FRHIComputeShader *ShaderRHI, const FShaderParameterBindings &Bindings, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
template<typename TRHICmdList, typename TShaderClass, typename TShaderRHI>
void SetShaderParameters (TRHICmdList &RHICmdList, const TShaderRef< TShaderClass > &Shader, TShaderRHI *ShaderRHI, const FShaderParametersMetadata *ParametersMetadata, const typename TShaderClass::FParameters &Parameters)
template<typename TRHICmdList, typename TShaderClass, typename TShaderRHI>
void SetShaderParameters (TRHICmdList &RHICmdList, const TShaderRef< TShaderClass > &Shader, TShaderRHI *ShaderRHI, const typename TShaderClass::FParameters &Parameters)
void UnsetShaderSRVs (FRHIBatchedShaderUnbinds &BatchedUnbinds, const FShaderParameterBindings &Bindings)
template<typename TShaderClass>
void UnsetShaderSRVs (FRHIBatchedShaderUnbinds &BatchedUnbinds, const TShaderRef< TShaderClass > &Shader)
template<typename TRHICmdList, typename TShaderClass>
void UnsetShaderSRVs (TRHICmdList &RHICmdList, const TShaderRef< TShaderClass > &Shader, FRHIComputeShader *ShaderRHI)
Unset compute shader SRVs.
template<typename TRHICmdList, typename TShaderClass>
void UnsetShaderSRVs (TRHICmdList &RHICmdList, const TShaderRef< TShaderClass > &Shader, FRHIGraphicsShader *ShaderRHI)
Unset compute shader SRVs.
void UnsetShaderUAVs (FRHIBatchedShaderUnbinds &BatchedUnbinds, const FShaderParameterBindings &Bindings)
template<typename TShaderClass>
void UnsetShaderUAVs (FRHIBatchedShaderUnbinds &BatchedUnbinds, const TShaderRef< TShaderClass > &Shader)
template<typename TRHICmdList, typename TShaderClass>
void UnsetShaderUAVs (TRHICmdList &RHICmdList, const TShaderRef< TShaderClass > &Shader, FRHIComputeShader *ShaderRHI)
Unset compute shader UAVs.
RENDERCORE_API void ValidateShaderParameterResourcesRHI (const void *Contents, const FRHIUniformBufferLayout &Layout)
Validates that all resource parameters of a uniform buffer are set.
RENDERCORE_API void ValidateShaderParameters (const TShaderRef< FShader > &Shader, const FShaderParametersMetadata *ParametersMetadata, const void *ParametersData)
Validates that all resource parameters of a shader are set.
template<typename TShaderClass>
void ValidateShaderParameters (const TShaderRef< TShaderClass > &Shader, const typename TShaderClass::FParameters &Parameters)
Macro Definition Documentation
SHADER_ROOT_PARAMETERS_SIGNATURE
#define SHADER_ROOT_PARAMETERS_SIGNATURE ()
Value:
    static inline const FShaderParametersMetadata* GetRootParametersMetadata() { return FParameters::FTypeInfo::GetStructMetadata(); }
Definition at line 58 of file ShaderParameterStruct.h.
SHADER_USE_PARAMETER_STRUCT
#define SHADER_USE_PARAMETER_STRUCT (ShaderClass, ShaderParentClass)
Value:
    SHADER_USE_PARAMETER_STRUCT_INTERNAL(ShaderClass, ShaderParentClass, true) \
    SHADER_ROOT_PARAMETERS_SIGNATURE()
Definition at line 62 of file ShaderParameterStruct.h.
SHADER_USE_PARAMETER_STRUCT_INTERNAL
#define SHADER_USE_PARAMETER_STRUCT_INTERNAL (ShaderClass, ShaderParentClass, bShouldBindEverything)
Value:
    ShaderClass() = default; \
    ShaderClass(const ShaderMetaType::CompiledShaderInitializerType& Initializer) \
        : ShaderParentClass(Initializer) \
    { \
        BindForLegacyShaderParameters<FParameters>(this, Initializer.PermutationId, Initializer.ParameterMap, bShouldBindEverything); \
    }
Tag a shader class to use the structured shader parameters API.
class FMyShaderClassCS : public FGlobalShader { DECLARE_GLOBAL_SHADER(FMyShaderClassCS); SHADER_USE_PARAMETER_STRUCT(FMyShaderClassCS, FGlobalShader);
BEGIN_SHADER_PARAMETER_STRUCT(FParameters) SHADER_PARAMETER(FMatrix44f, ViewToClip) //... END_SHADER_PARAMETER_STRUCT() };
Notes: Long term, this macro will no longer be needed. Instead, parameter binding will become the default behavior for shader declarations.
Definition at line 50 of file ShaderParameterStruct.h.
SHADER_USE_PARAMETER_STRUCT_MIXED
#define SHADER_USE_PARAMETER_STRUCT_MIXED (ShaderClass, ShaderParentClass)
Value:
    SHADER_USE_PARAMETER_STRUCT_INTERNAL(ShaderClass, ShaderParentClass, false) \
    SHADER_ROOT_PARAMETERS_SIGNATURE()
Use when sharing shader parameter binding with legacy parameters in the base class; i.e.
FMaterialShader or FMeshMaterialShader. This forces the shader to be compiled with the Parameters.
Definition at line 75 of file ShaderParameterStruct.h.
SHADER_USE_PARAMETER_STRUCT_WITH_LEGACY_BASE
#define SHADER_USE_PARAMETER_STRUCT_WITH_LEGACY_BASE (ShaderClass, ShaderParentClass)
Value:
    SHADER_USE_PARAMETER_STRUCT_INTERNAL(ShaderClass, ShaderParentClass, false)
Use when sharing shader parameter binding with legacy parameters in the base class; i.e.
FMaterialShader or FMeshMaterialShader. Note that this disables validation that the parameter struct contains all shader bindings.
Definition at line 69 of file ShaderParameterStruct.h.
SHADER_USE_ROOT_PARAMETER_STRUCT
#define SHADER_USE_ROOT_PARAMETER_STRUCT (ShaderClass, ShaderParentClass)
Value:
    SHADER_ROOT_PARAMETERS_SIGNATURE() \
    ShaderClass() = default; \
    ShaderClass(const ShaderMetaType::CompiledShaderInitializerType& Initializer) \
        : ShaderParentClass(Initializer) \
    { \
        this->Bindings.BindForRootShaderParameters(this, Initializer.PermutationId, Initializer.ParameterMap); \
    }
Definition at line 79 of file ShaderParameterStruct.h.
Function Documentation
BindForLegacyShaderParameters()
template<typename FParameterStruct> void BindForLegacyShaderParameters (FShader * Shader, int32 PermutationId, const FShaderParameterMap & ParameterMap, bool bShouldBindEverything = false)
Definition at line 29 of file ShaderParameterStruct.h.
CollectSRVsToUnset()
template<typename TParameterType> void CollectSRVsToUnset (FRHIBatchedShaderUnbinds & BatchedUnbinds, const TMemoryImageArray< TParameterType > & InParameters) inline
Definition at line 149 of file ShaderParameterStruct.h.
References GetParameterIndex().
Referenced by UnsetShaderSRVs().
CollectUAVsToUnset()
template<typename TParameterType> void CollectUAVsToUnset (FRHIBatchedShaderUnbinds & BatchedUnbinds, const TMemoryImageArray< TParameterType > & InParameters) inline
Definition at line 135 of file ShaderParameterStruct.h.
References GetParameterIndex().
Referenced by UnsetShaderUAVs().
EmitNullShaderParameterFatalError()
RENDERCORE_API void EmitNullShaderParameterFatalError (const TShaderRef< FShader > & Shader, const FShaderParametersMetadata * ParametersMetadata, uint16 MemberOffset) extern
Raise fatal error when a required shader parameter has not been set.
GetShaderParameterResourceRHI()
FRHIResource * GetShaderParameterResourceRHI (const void * Contents, uint16 MemberOffset, EUniformBufferBaseType MemberType) inline
Dereferences the RHI resource from a shader parameter struct.
Definition at line 89 of file ShaderParameterStruct.h.
References checkSlow, and FRDGResource::GetRHI().
SetAllShaderParametersAsBindless() [1/2]
RENDERCORE_API void SetAllShaderParametersAsBindless (FRHIBatchedShaderParameters & BatchedParameters, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData)
Set all resources described by ParametersMetadata using data from ParametersData as BindlessParameters.
Referenced by SetAllShaderParametersAsBindless().
SetAllShaderParametersAsBindless() [2/2]
template<typename TParameters> void SetAllShaderParametersAsBindless (FRHIBatchedShaderParameters & BatchedParameters, const TParameters & InParameters) inline
Definition at line 239 of file ShaderParameterStruct.h.
References SetAllShaderParametersAsBindless().
SetShaderParameters() [1/8]
RENDERCORE_API void SetShaderParameters (FRHIBatchedShaderParameters & BatchedParameters, const FShaderParameterBindings & Bindings, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData)
Referenced by FPixelShaderUtils::AddRasterizeToRectsPass(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), FPixelShaderUtils::DrawFullscreenPixelShader(), FComputeShaderUtils::Private::PrepareDispatch(), SetBatchedShaderParametersMixed(), SetShaderParameters(), SetShaderParameters(), SetShaderParameters(), and SetShaderParameters().
SetShaderParameters() [2/8]
template<typename TShaderClass> void SetShaderParameters (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderClass > & Shader, const FShaderParametersMetadata * ParametersMetadata, const typename TShaderClass::FParameters & Parameters) inline
Definition at line 254 of file ShaderParameterStruct.h.
References SetShaderParameters(), and ValidateShaderParameters().
SetShaderParameters() [3/8]
template<typename TShaderClass> void SetShaderParameters (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderClass > & Shader, const typename TShaderClass::FParameters & Parameters) inline
Definition at line 275 of file ShaderParameterStruct.h.
References SetShaderParameters().
SetShaderParameters() [4/8]
RENDERCORE_API void SetShaderParameters (FRHICommandList & RHICmdList, FRHIComputeShader * ShaderRHI, const FShaderParameterBindings & Bindings, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData)
SetShaderParameters() [5/8]
RENDERCORE_API void SetShaderParameters (FRHICommandList & RHICmdList, FRHIGraphicsShader * ShaderRHI, const FShaderParameterBindings & Bindings, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData)
SetShaderParameters() [6/8]
RENDERCORE_API void SetShaderParameters (FRHIComputeCommandList & RHICmdList, FRHIComputeShader * ShaderRHI, const FShaderParameterBindings & Bindings, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData)
SetShaderParameters() [7/8]
template<typename TRHICmdList, typename TShaderClass, typename TShaderRHI> void SetShaderParameters (TRHICmdList & RHICmdList, const TShaderRef< TShaderClass > & Shader, TShaderRHI * ShaderRHI, const FShaderParametersMetadata * ParametersMetadata, const typename TShaderClass::FParameters & Parameters) inline
Definition at line 303 of file ShaderParameterStruct.h.
References SetShaderParameters(), and ValidateShaderParameters().
SetShaderParameters() [8/8]
template<typename TRHICmdList, typename TShaderClass, typename TShaderRHI> void SetShaderParameters (TRHICmdList & RHICmdList, const TShaderRef< TShaderClass > & Shader, TShaderRHI * ShaderRHI, const typename TShaderClass::FParameters & Parameters) inline
Definition at line 318 of file ShaderParameterStruct.h.
References SetShaderParameters().
UnsetShaderSRVs() [1/4]
void UnsetShaderSRVs (FRHIBatchedShaderUnbinds & BatchedUnbinds, const FShaderParameterBindings & Bindings) inline
Definition at line 168 of file ShaderParameterStruct.h.
References CollectSRVsToUnset().
Referenced by UnsetShaderSRVs(), UnsetShaderSRVs(), and UnsetShaderSRVs().
UnsetShaderSRVs() [2/4]
template<typename TShaderClass> void UnsetShaderSRVs (FRHIBatchedShaderUnbinds & BatchedUnbinds, const TShaderRef< TShaderClass > & Shader) inline
Definition at line 185 of file ShaderParameterStruct.h.
References checkf, FShaderParameterBindings::kInvalidBufferIndex, TEXT, and UnsetShaderSRVs().
UnsetShaderSRVs() [3/4]
template<typename TRHICmdList, typename TShaderClass> void UnsetShaderSRVs (TRHICmdList & RHICmdList, const TShaderRef< TShaderClass > & Shader, FRHIComputeShader * ShaderRHI) inline
Unset compute shader SRVs.
Definition at line 209 of file ShaderParameterStruct.h.
References UnsetShaderSRVs().
UnsetShaderSRVs() [4/4]
template<typename TRHICmdList, typename TShaderClass> void UnsetShaderSRVs (TRHICmdList & RHICmdList, const TShaderRef< TShaderClass > & Shader, FRHIGraphicsShader * ShaderRHI) inline
Unset compute shader SRVs.
Definition at line 221 of file ShaderParameterStruct.h.
References UnsetShaderSRVs().
UnsetShaderUAVs() [1/3]
void UnsetShaderUAVs (FRHIBatchedShaderUnbinds & BatchedUnbinds, const FShaderParameterBindings & Bindings) inline
Definition at line 163 of file ShaderParameterStruct.h.
References CollectUAVsToUnset().
Referenced by FComputeShaderUtils::Private::AfterDispatch(), UnsetShaderUAVs(), and UnsetShaderUAVs().
UnsetShaderUAVs() [2/3]
template<typename TShaderClass> void UnsetShaderUAVs (FRHIBatchedShaderUnbinds & BatchedUnbinds, const TShaderRef< TShaderClass > & Shader) inline
Definition at line 174 of file ShaderParameterStruct.h.
References checkf, FShaderParameterBindings::kInvalidBufferIndex, TEXT, and UnsetShaderUAVs().
UnsetShaderUAVs() [3/3]
template<typename TRHICmdList, typename TShaderClass> void UnsetShaderUAVs (TRHICmdList & RHICmdList, const TShaderRef< TShaderClass > & Shader, FRHIComputeShader * ShaderRHI) inline
Unset compute shader UAVs.
Definition at line 197 of file ShaderParameterStruct.h.
References UnsetShaderUAVs().
ValidateShaderParameterResourcesRHI()
RENDERCORE_API void ValidateShaderParameterResourcesRHI (const void * Contents, const FRHIUniformBufferLayout & Layout) extern
Validates that all resource parameters of a uniform buffer are set.
References FORCEINLINE, and Layout.
ValidateShaderParameters() [1/2]
RENDERCORE_API void ValidateShaderParameters (const TShaderRef< FShader > & Shader, const FShaderParametersMetadata * ParametersMetadata, const void * ParametersData) extern
Validates that all resource parameters of a shader are set.
References FORCEINLINE.
Referenced by SetShaderParameters(), SetShaderParameters(), and ValidateShaderParameters().
ValidateShaderParameters() [2/2]
template<typename TShaderClass> void ValidateShaderParameters (const TShaderRef< TShaderClass > & Shader, const typename TShaderClass::FParameters & Parameters)
Definition at line 129 of file ShaderParameterStruct.h.
References FORCEINLINE, and ValidateShaderParameters().