Unreal Engine 5.6 C++ API: TArray< InElementType, InAllocatorType > Class Template Reference
TArray< InElementType, InAllocatorType > Class Template Reference
Templated dynamic array.
#include "Array.h"
Inherited by TRDGResourceAccessArray< FRDGBufferAccess >, TRDGResourceAccessArray< FRDGTextureAccess >, TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >, UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >, and UE::Anim::TTypedIndexRange< BoneIndexType, TArray< ElementType, InAllocatorType > >.
Public Types
using AllocatorType = InAllocatorType
using ElementAllocatorType
using ElementType = InElementType
using IntrusiveUnsetOptionalStateType = TArray
using RangedForConstIteratorType = TCheckedPointerIterator<const ElementType, SizeType, false>
using RangedForConstReverseIteratorType = TCheckedPointerIterator<const ElementType, SizeType, true>
using RangedForIteratorType = TCheckedPointerIterator< ElementType, SizeType, false>
using RangedForReverseIteratorType = TCheckedPointerIterator< ElementType, SizeType, true>
using SizeType = typename InAllocatorType::SizeType
using TConstIterator = TIndexedContainerIterator<const TArray, const ElementType, SizeType>
using TIterator = TIndexedContainerIterator< TArray, ElementType, SizeType>
Public Member Functions
FORCEINLINE TArray ()
Constructor, initializes element number counters.
FORCEINLINE TArray (const ElementType *Ptr, SizeType Count)
Constructor from a raw array of elements.
FORCEINLINE TArray (const TArray &Other)
Copy constructor.
FORCEINLINE TArray (const TArray &Other, SizeType ExtraSlack)
Copy constructor.
template<typename OtherElementType, typename OtherAllocator UE_REQUIRES>
FORCEINLINE TArray (const TArray< OtherElementType, OtherAllocator > &Other)
Copy constructor with changed allocator.
template<typename OtherElementType, typename OtherSizeType>
TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
template<typename OtherElementType, typename OtherSizeType>
FORCEINLINE TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
UE_NODEBUG TArray (FIntrusiveUnsetOptionalState Tag)
TArray (std::initializer_list< InElementType > InitList)
Initializer list constructor.
FORCEINLINE TArray (TArray &&Other)
Move constructor.
template<typename OtherElementType UE_REQUIRES>
TArray (TArray< OtherElementType, AllocatorType > &&Other, SizeType ExtraSlack)
Move constructor.
template<typename OtherElementType, typename OtherAllocator UE_REQUIRES>
FORCEINLINE TArray (TArray< OtherElementType, OtherAllocator > &&Other)
Move constructor.
~TArray ()
Destructor.
UE_NODEBUG FORCEINLINE SizeType Add (const ElementType &Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE SizeType Add (ElementType &&Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (const ElementType &Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (ElementType &&Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted (SizeType Count)
ElementType & AddDefaulted_GetRef () UE_LIFETIMEBOUND
Add a new item to the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE SizeType AddUninitialized ()
Adds a given number of uninitialized elements into the array.
FORCEINLINE SizeType AddUninitialized (SizeType Count)
FORCEINLINE SizeType AddUnique (const ElementType &Item)
Adds unique element to array if it doesn't exist.
FORCEINLINE SizeType AddUnique (ElementType &&Item)
Adds unique element to array if it doesn't exist.
SizeType AddZeroed ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddZeroed (SizeType Count)
ElementType & AddZeroed_GetRef () UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
void Append (const ElementType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
template<typename OtherElementType, typename OtherAllocatorType>
void Append (const TArray< OtherElementType, OtherAllocatorType > &Source)
Appends the specified array to this array.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
void Append (const typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
template<typename RangeType UE_REQUIRES>
void Append (RangeType &&Source)
Appends the elements from a contiguous range to this array.
FORCEINLINE void Append (std::initializer_list< ElementType > InitList)
Adds an initializer list of elements to the end of the TArray.
template<typename OtherElementType, typename OtherAllocator>
void Append (TArray< OtherElementType, OtherAllocator > &&Source)
Appends the specified array to this array.
UE_NODEBUG FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
UE_NODEBUG FORCEINLINE RangedForConstIteratorType begin () const
void BulkSerialize (FArchive &Ar, bool bForcePerElementSerialization=false)
Bulk serialize array as a single memory blob when loading.
FORCEINLINE void CheckAddress (const ElementType *Addr) const
Checks that the specified address is not part of an element within the container.
UE_NODEBUG FORCEINLINE void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero and less than or equal to the maximum.
template<typename ComparisonType>
bool Contains (const ComparisonType &Item) const
Checks if this array contains the element.
template<typename Predicate>
UE_NODEBUG FORCEINLINE bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains an element for which the predicate is true.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
UE_NODEBUG void CountBytes (FArchive &Ar) const
Count bytes needed to serialize this array.
UE_NODEBUG TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this array.
UE_NODEBUG TIterator CreateIterator ()
Creates an iterator for the contents of this array.
template<typename... ArgsType>
FORCEINLINE SizeType Emplace (ArgsType &&... Args)
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE ElementType & Emplace_GetRef (ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE void EmplaceAt (SizeType Index, ArgsType &&... Args)
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE ElementType & EmplaceAt_GetRef (SizeType Index, ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
void Empty (SizeType Slack=0)
Empties the array.
UE_NODEBUG FORCEINLINE RangedForIteratorType end ()
UE_NODEBUG FORCEINLINE RangedForConstIteratorType end () const
template<typename Predicate>
TArray< ElementType > FilterByPredicate (Predicate Pred) const
Filters the elements in the array based on a predicate functor.
SizeType Find (const ElementType &Item) const
Finds element within the array.
UE_NODEBUG FORCEINLINE bool Find (const ElementType &Item, SizeType &Index) const
Finds element within the array.
template<typename KeyType>
ElementType * FindByKey (const KeyType &Key)
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename KeyType>
UE_NODEBUG FORCEINLINE const ElementType * FindByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
ElementType * FindByPredicate (Predicate Pred)
Finds an element which matches a predicate functor.
template<typename Predicate>
UE_NODEBUG FORCEINLINE const ElementType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
template<typename SearchType>
bool FindItemByClass (SearchType **Item=nullptr, SizeType *ItemIndex=nullptr, SizeType StartIndex=0) const
Searches for the first entry of the specified type, will only work with TArray<UObject*>.
SizeType FindLast (const ElementType &Item) const
Finds element within the array starting from the end.
UE_NODEBUG FORCEINLINE bool FindLast (const ElementType &Item, SizeType &Index) const
Finds element within the array starting from the end.
template<typename Predicate>
UE_NODEBUG FORCEINLINE SizeType FindLastByPredicate (Predicate Pred) const
Searches the array for the last occurrence of an element which matches the specified predicate.
template<typename Predicate>
SizeType FindLastByPredicate (Predicate Pred, SizeType Count) const
Searches an initial subrange of the array for the last occurrence of an element which matches the specified predicate.
UE_NODEBUG FORCEINLINE SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
UE_NODEBUG ElementAllocatorType & GetAllocatorInstance ()
UE_NODEBUG const ElementAllocatorType & GetAllocatorInstance () const
UE_NODEBUG FORCEINLINE const ElementType * GetData () const UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE ElementType * GetData () UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE SizeType GetSlack () const
Returns the amount of slack in this array in elements.
UE_NODEBUG void Heapify ()
Builds an implicit heap from the array.
template<class PREDICATE_CLASS>
UE_NODEBUG FORCEINLINE void Heapify (const PREDICATE_CLASS &Predicate)
Implicit heaps.
template<class PREDICATE_CLASS>
void HeapPop (ElementType &OutItem, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPop (ElementType &OutItem, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
template<class PREDICATE_CLASS>
void HeapPopDiscard (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPopDiscard (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG SizeType HeapPush (const ElementType &InItem)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
SizeType HeapPush (const ElementType &InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
UE_NODEBUG SizeType HeapPush (ElementType &&InItem)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
SizeType HeapPush (ElementType &&InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
void HeapRemoveAt (SizeType Index, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapRemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapSort ()
Performs heap sort on the array.
template<class PREDICATE_CLASS>
UE_NODEBUG void HeapSort (const PREDICATE_CLASS &Predicate)
Performs heap sort on the array.
UE_NODEBUG const ElementType & HeapTop () const UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
UE_NODEBUG ElementType & HeapTop () UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
template<typename KeyType>
SizeType IndexOfByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
SizeType IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
void Init (const ElementType &Element, SizeType Number)
Sets the size of the array, filling it with the given element.
SizeType Insert (const ElementType &Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (const ElementType *Ptr, SizeType Count, SizeType Index)
Inserts a raw array of elements at a particular index in the TArray.
template<typename OtherAllocator>
SizeType Insert (const TArray< ElementType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
SizeType Insert (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (ElementType &&Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (std::initializer_list< ElementType > InitList, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator>
SizeType Insert (TArray< ElementType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
SizeType Insert (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
ElementType & Insert_GetRef (const ElementType &Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
ElementType & Insert_GetRef (ElementType &&Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
void InsertDefaulted (SizeType Index)
Inserts a given number of default-constructed elements into the array at a given location.
void InsertDefaulted (SizeType Index, SizeType Count)
ElementType & InsertDefaulted_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a default-constructed element into the array at a given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index)
Inserts a given number of uninitialized elements into the array at given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index, SizeType Count)
void InsertZeroed (SizeType Index)
Inserts a given number of zeroed elements into the array at given location.
void InsertZeroed (SizeType Index, SizeType Count)
ElementType & InsertZeroed_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a zeroed element into the array at given location.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
UE_NODEBUG FORCEINLINE bool IsValidIndex (SizeType Index) const
Tests if index is valid, i.e.
UE_NODEBUG FORCEINLINE const ElementType & Last (SizeType IndexFromTheEnd=0) const UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE ElementType & Last (SizeType IndexFromTheEnd=0) UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE SizeType Max () const
Returns maximum number of elements in array.
UE_NODEBUG FORCEINLINE SizeType Num () const
Returns number of elements in array.
UE_NODEBUG FORCEINLINE SIZE_T NumBytes () const
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)>
operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & () const
Immutable implicit conversion operator to constant container of compatible element type.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)>
operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & ()
Mutable implicit conversion operator to container of compatible element type.
UE_NODEBUG FORCEINLINE bool operator!= (const TArray &OtherArray) const
Inequality operator.
UE_NODEBUG TArray & operator+= (const TArray &Other)
Appends the specified array to this array.
UE_NODEBUG TArray & operator+= (std::initializer_list< ElementType > InitList)
Appends the specified initializer list to this array.
UE_NODEBUG TArray & operator+= (TArray &&Other)
Appends the specified array to this array.
TArray & operator= (const TArray &Other)
Assignment operator.
template<typename OtherAllocatorType>
TArray & operator= (const TArray< ElementType, OtherAllocatorType > &Other)
Assignment operator.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TArray & operator= (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Other)
Assignment operator.
template<typename OtherElementType, typename OtherSizeType>
TArray & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
template<typename OtherElementType, typename OtherSizeType>
FORCEINLINE TArray< InElementType, InAllocatorType > & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
TArray & operator= (std::initializer_list< InElementType > InitList)
Initializer list assignment operator.
TArray & operator= (TArray &&Other)
Move assignment operator.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TArray & operator= (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, AllocatorType > &&Other)
Move assignment operator.
UE_NODEBUG bool operator== (const TArray &OtherArray) const
Equality operator.
UE_NODEBUG bool operator== (FIntrusiveUnsetOptionalState Tag) const
UE_NODEBUG FORCEINLINE const ElementType & operator[] (SizeType Index) const UE_LIFETIMEBOUND
Array bracket operator.
UE_NODEBUG FORCEINLINE ElementType & operator[] (SizeType Index) UE_LIFETIMEBOUND
Array bracket operator.
ElementType Pop (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Pops element from the array.
UE_NODEBUG FORCEINLINE void Push (const ElementType &Item)
Pushes element into the array.
UE_NODEBUG FORCEINLINE void Push (ElementType &&Item)
Pushes element into the array.
FORCEINLINE void RangeCheck (SizeType Index) const
Checks if index is in array range.
FORCEINLINE void RangeCheck (SizeType Index, SizeType Count) const
Checks if a range of indices are in the array range.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rbegin ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rbegin () const
SizeType Remove (const ElementType &Item)
Removes as many instances of Item as there are in the array, maintaining order but not indices.
template<class PREDICATE_CLASS>
SizeType RemoveAll (const PREDICATE_CLASS &Predicate)
Remove all instances that match the predicate, maintaining order but not indices Optimized to work with runs of matches/non-matches.
template<class PREDICATE_CLASS>
SizeType RemoveAllSwap (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Remove all instances that match the predicate.
template<typename CountType UE_REQUIRES>
FORCEINLINE void RemoveAt (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
void RemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
template<typename CountType UE_REQUIRES>
FORCEINLINE void RemoveAtSwap (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
FORCEINLINE void RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
SizeType RemoveSingle (const ElementType &Item)
Removes the first occurrence of the specified item in the array, maintaining order but not indices.
SizeType RemoveSingleSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the first occurrence of the specified item in the array.
SizeType RemoveSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes all instances of a given item from the array.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rend ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rend () const
FORCEINLINE void Reserve (SizeType Number)
Reserves memory such that the array can contain at least Number elements.
void Reset (SizeType NewSize=0)
Same as empty, but doesn't change memory allocations, unless the new size is larger than the current array.
void SetNum (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUninitialized (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUnsafeInternal (SizeType NewNum)
Does nothing except setting the new number of elements in the array.
void SetNumZeroed (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements, optionally shrinking it.
FORCEINLINE void Shrink ()
Shrinks the array's used memory to smallest possible to store elements currently in it.
UE_NODEBUG void Sort ()
Sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
UE_NODEBUG void Sort (const PREDICATE_CLASS &Predicate)
Sorts the array using user define predicate class.
UE_NODEBUG void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
UE_NODEBUG void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the array using user defined predicate class.
FORCEINLINE void Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array element swap.
FORCEINLINE void SwapMemory (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array memory swap.
UE_NODEBUG FORCEINLINE const ElementType & Top () const UE_LIFETIMEBOUND
Returns the top element, i.e.
UE_NODEBUG FORCEINLINE ElementType & Top () UE_LIFETIMEBOUND
Returns the top element, i.e.
void ToString (const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext) const
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(bool bAllowShrinking)
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(const PREDICATE_CLASS &Predicate
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG FORCEINLINE void HeapRemoveAt(SizeType Index
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG void HeapRemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") UE_NODEBUG FORCEINLINE ElementType Pop(bool bAllowShrinking)
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAllSwap") UE_NODEBUG FORCEINLINE SizeType RemoveAllSwap(const PREDICATE_CLASS &Predicate
template<typename CountType>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt") FORCEINLINE void RemoveAt(SizeType Index
template<typename CountType>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") UE_NODEBUG FORCEINLINE void RemoveAtSwap(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSingleSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum") UE_NODEBUG FORCEINLINE void SetNum(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") UE_NODEBUG FORCEINLINE void SetNumUninitialized(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumZeroed") UE_NODEBUG FORCEINLINE void SetNumZeroed(SizeType NewNum
template<class PREDICATE_CLASS>
UE_NODEBUG void VerifyHeap (const PREDICATE_CLASS &Predicate)
Verifies the heap.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Member Functions
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
UE_NODEBUG static FORCEINLINE constexpr uint32 GetTypeSize ()
Helper function returning the size of the inner type.
Data Fields
CountType bool bAllowShrinking
bool bAllowShrinking
const PREDICATE_CLASS bool bAllowShrinking
CountType Count
const PREDICATE_CLASS & Predicate
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Protected Attributes
ElementAllocatorType AllocatorInstance
SizeType ArrayMax
SizeType ArrayNum
Private Types
using USizeType = typename std::make_unsigned_t<SizeType>
Private Member Functions
template<typename ArgsType>
SizeType AddUniqueImpl (ArgsType &&Args)
Adds unique element to array if it doesn't exist.
template<typename OtherElementType, typename OtherSizeType>
void CopyToEmpty (const OtherElementType *OtherData, OtherSizeType OtherNum, SizeType PrevMax)
Copies data from one array into this array.
template<typename OtherElementType, typename OtherSizeType>
void CopyToEmptyWithSlack (const OtherElementType *OtherData, OtherSizeType OtherNum, SizeType PrevMax, SizeType ExtraSlack)
Copies data from one array into this array.
void InsertUninitializedImpl (SizeType Index)
template<typename OtherSizeType UE_REQUIRES>
UE_NODEBUG void InsertUninitializedImpl (SizeType Index, OtherSizeType Count)
void InsertUninitializedImpl (SizeType Index, SizeType Count)
void RemoveAtImpl (SizeType Index)
void RemoveAtImpl (SizeType Index, SizeType Count)
void RemoveAtSwapImpl (SizeType Index)
void RemoveAtSwapImpl (SizeType Index, SizeType Count)
FORCEINLINE void SlackTrackerNumChanged ()
Static Private Member Functions
template<typename FromArrayType, typename ToArrayType>
static FORCEINLINE void MoveOrCopy (ToArrayType &ToArray, FromArrayType &FromArray, SizeType PrevMax)
Moves or copies array.
template<typename FromArrayType, typename ToArrayType>
static FORCEINLINE void MoveOrCopyWithSlack (ToArrayType &ToArray, FromArrayType &FromArray, SizeType PrevMax, SizeType ExtraSlack)
Moves or copies array.
Friends
template<typename OtherInElementType, typename OtherAllocator>
class TArray
struct TArrayPrivateFriend
template<typename ElementType, typename AllocatorType>
class TIndirectArray
Detailed Description
template<typename InElementType, typename InAllocatorType>
class TArray< InElementType, InAllocatorType >
Templated dynamic array.
A dynamically sized array of typed elements. Makes the assumption that your elements are relocate-able; i.e. that they can be transparently moved to new memory without a copy constructor. The main implication is that pointers to elements in the TArray may be invalidated by adding or removing other elements to the array. Removal of elements is O(N) and invalidates the indices of subsequent elements.
Caution: as noted below some methods are not safe for element types that require constructors.
Definition at line 651 of file Array.h.
Member Typedef Documentation
AllocatorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::AllocatorType = InAllocatorType
Definition at line 659 of file Array.h.
ElementAllocatorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::ElementAllocatorType
Initial value:
 std::conditional_t<
        AllocatorType::NeedsElementType,
        typename AllocatorType::template ForElementType<ElementType>,
        typename AllocatorType::ForAnyElementType
    >
Definition at line 665 of file Array.h.
ElementType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::ElementType = InElementType
Definition at line 658 of file Array.h.
IntrusiveUnsetOptionalStateType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::IntrusiveUnsetOptionalStateType = TArray
Definition at line 978 of file Array.h.
RangedForConstIteratorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::RangedForConstIteratorType = TCheckedPointerIterator<const ElementType, SizeType, false>
Definition at line 3379 of file Array.h.
RangedForConstReverseIteratorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::RangedForConstReverseIteratorType = TCheckedPointerIterator<const ElementType, SizeType, true>
Definition at line 3381 of file Array.h.
RangedForIteratorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::RangedForIteratorType = TCheckedPointerIterator< ElementType, SizeType, false>
Definition at line 3378 of file Array.h.
RangedForReverseIteratorType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::RangedForReverseIteratorType = TCheckedPointerIterator< ElementType, SizeType, true>
Definition at line 3380 of file Array.h.
SizeType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::SizeType = typename InAllocatorType::SizeType
Definition at line 657 of file Array.h.
TConstIterator
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::TConstIterator = TIndexedContainerIterator<const TArray, const ElementType, SizeType>
Definition at line 3355 of file Array.h.
TIterator
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::TIterator = TIndexedContainerIterator< TArray, ElementType, SizeType>
Definition at line 3354 of file Array.h.
USizeType
template<typename InElementType, typename InAllocatorType> using TArray< InElementType, InAllocatorType >::USizeType = typename std::make_unsigned_t<SizeType> private
Definition at line 662 of file Array.h.
Constructor & Destructor Documentation
TArray() [1/12]
template<typename InElementType, typename InAllocatorType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray () inline nodiscard
Constructor, initializes element number counters.
Definition at line 676 of file Array.h.
TArray() [2/12]
template<typename InElementType, typename InAllocatorType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (const ElementType * Ptr, SizeType Count) inline nodiscard
Constructor from a raw array of elements.
Parameters
Ptr A pointer to an array of elements to copy.
Count The number of elements to copy from Ptr.
See also
Append
Definition at line 689 of file Array.h.
TArray() [3/12]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> TArray< InElementType, InAllocatorType >::TArray (const TArrayView< OtherElementType, OtherSizeType > & Other) explicit nodiscard
TArray() [4/12]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::TArray (std::initializer_list< InElementType > InitList) inline nodiscard
Initializer list constructor.
Definition at line 708 of file Array.h.
TArray() [5/12]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherAllocator UE_REQUIRES> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (const TArray< OtherElementType, OtherAllocator > & Other) inline explicit nodiscard
Copy constructor with changed allocator.
Use the common routine to perform the copy.
Parameters
Other The source array to copy.
Definition at line 726 of file Array.h.
TArray() [6/12]
template<typename InElementType, typename InAllocatorType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (const TArray< InElementType, InAllocatorType > & Other) inline nodiscard
Copy constructor.
Use the common routine to perform the copy.
Parameters
Other The source array to copy.
Definition at line 736 of file Array.h.
TArray() [7/12]
template<typename InElementType, typename InAllocatorType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (const TArray< InElementType, InAllocatorType > & Other, SizeType ExtraSlack) inline nodiscard
Copy constructor.
Use the common routine to perform the copy.
Parameters
Other The source array to copy.
ExtraSlack Tells how much extra memory should be preallocated at the end of the array in the number of elements.
Definition at line 748 of file Array.h.
TArray() [8/12]
template<typename InElementType, typename InAllocatorType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (TArray< InElementType, InAllocatorType > && Other) inline nodiscard
Move constructor.
Parameters
Other Array to move from.
Definition at line 914 of file Array.h.
TArray() [9/12]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherAllocator UE_REQUIRES> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (TArray< OtherElementType, OtherAllocator > && Other) inline explicit nodiscard
Move constructor.
Parameters
Other Array to move from.
Definition at line 929 of file Array.h.
TArray() [10/12]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType UE_REQUIRES> TArray< InElementType, InAllocatorType >::TArray (TArray< OtherElementType, AllocatorType > && Other, SizeType ExtraSlack) inline nodiscard
Move constructor.
Parameters
Other Array to move from.
ExtraSlack Tells how much extra memory should be preallocated at the end of the array in the number of elements.
Definition at line 945 of file Array.h.
~TArray()
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::~TArray () inline
Destructor.
Definition at line 966 of file Array.h.
TArray() [11/12]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TArray< InElementType, InAllocatorType >::TArray (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 980 of file Array.h.
TArray() [12/12]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> FORCEINLINE TArray< InElementType, InAllocatorType >::TArray (const TArrayView< OtherElementType, OtherSizeType > & Other) nodiscard
Definition at line 973 of file ArrayView.h.
Member Function Documentation
Add() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::Add (const ElementType & Item) inline
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
Parameters
Item The item to add
Returns
Index to the new item
See also
AddDefaulted, AddUnique, AddZeroed, Append, Insert
Definition at line 2719 of file Array.h.
Add() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::Add (ElementType && Item) inline
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
Move semantics version.
Parameters
Item The item to add
Returns
Index to the new item
See also
AddDefaulted, AddUnique, AddZeroed, Append, Insert
Definition at line 2706 of file Array.h.
Referenced by FCookTagList::Add(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add(), UE::Geometry::TConstrainedDelaunay2< float >::Add(), Metasound::AddBuildError(), FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), FKeyframeTrackEditor< TrackType >::AddKeysToSection(), TRangeAllocator< FAllocatorModifier >::Alloc(), FMaterialOverlayHelper::AppendAllOverlayMaterial(), BufferUtil::AppendElements(), UE::Geometry::FSegmentTree3::Build(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), FCSPose< PoseType >::CalculateComponentSpaceTransform(), CleanupPointerArray(), UE::Geometry::CurveUtil::ClipConvexToBounds(), UE::Geometry::CurveUtil::ClipConvexToPlane(), UE::Geometry::FMeshFaceSelection::ClipFins(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), UE::Geometry::FSizedDisjointSet::CompactedGroupIndexToGroupID(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), UE::Geometry::FClusterKMeans::ComputeClusters(), ConvexHull2D::ComputeConvexHull(), ConvexHull2D::ComputeConvexHullLegacy(), ConvexHull2D::ComputeConvexHullLegacy2(), SRigVMActionMenu::ConstructActionContext(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), UE::Geometry::FMeshEdgeSelection::ContractByBorderEdges(), UE::Geometry::FMeshVertexSelection::ContractByBorderVertices(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), Metasound::TParamPackFixedArray< typename T::ElementType, MaxNumItems >::CopyToArray(), FWaterMeshIndexBuffer::CreateIndexBuffer(), UE::Geometry::FGeometrySelectionEditor::Deselect(), TPerlinNoiseChannelInterface< ChannelContainerType >::DrawExtra_Raw(), EditorAnimUtils::DuplicateAssets(), ENUM_CLASS_FLAGS(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), AnimationEditorUtils::ExecuteNewAnimAsset(), UE::Geometry::FMeshFaceSelection::ExpandToFaceNeighbours(), UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_FindNeighborsHelper(), UE::Geometry::FMeshVertexSelection::ExpandToOneRingNeighbours(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::ExportTypes(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendKeyMenu_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendSectionMenu_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::ExtendSidebarMenu_Raw(), TLocklessGrowingStorage< T >::ExtractShards(), UE::Geometry::FMeshFaceSelection::FillEars(), RangedForIteratorType< FAnimNextTraitEventPtr >::FilterByPredicate(), TArrayView< FTransform >::FilterByPredicate(), UE::Geometry::FArrangement2d::find_intersecting_edges(), UE::Geometry::FArrangement2d::find_intersecting_floating_vertices(), DisplayClusterHelpers::game::FindAllActors(), UE::SequenceNavigator::INavigationToolItem::FindAncestorsOfType(), UE::Geometry::FMeshFaceSelection::FindBorderTris(), UE::Geometry::FMeshConstraints::FindConstrainedEdgesBySetID(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), UE::Geometry::FMeshFaceSelection::FindNeighbourTris(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FindPathToNearestSeed(), UE::Geometry::TMeshDijkstra< PointSetType >::FindPathToNearestSeed(), UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), FLayoutExtender::FindStackExtensions(), FLayoutExtender::FindTabExtensions(), UE::Geometry::FGroupTopology::ForGroupSetEdges(), FMovieSceneDirectorBlueprintConditionUtils::GatherDirectorBlueprintConditions(), FMovieSceneDynamicBindingUtils::GatherDynamicBindings(), TTableViewMetadata< ItemType >::GatherSelectedRows(), UE::Geometry::FCylinderGenerator::Generate(), UE::Geometry::FWindingNumberBasedSolidify::Generate(), UE::Geometry::TImplicitSolidify< TriangleMeshType >::Generate(), UE::Geometry::FMarchingCubes::generate_continuation(), UE::Geometry::FMarchingCubes::generate_continuation_parallel(), UE::Geometry::TImplicitBlend< TriangleMeshType >::GenerateBlendAnalytic(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateKeyArray(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GenerateKeyArray(), FClassTree::GenerateMaskedClassTree(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateValueArray(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GenerateValueArray(), UE::Geometry::TMeshLocalParam< PointSetType >::GetAllComputedUVs(), SBreadcrumbTrail< ItemType >::GetAllCrumbData(), SWidget::GetAllMetaData(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::GetAllObjectRefsEvenIfUnreachable(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::GetAllObjects(), GetAllPhysicsObjectsById(), FWidgetBlueprintEditor::GetAnimationEventContexts(), UE::Geometry::TConvexHull3< float >::GetAsHalfspaces(), UE::Geometry::TConvexHull3< float >::GetAsHalfspaces(), EditorAnimUtils::GetAssetsFromProperties(), IMeshDescriptionProvider::GetAvailableLODs(), UMaterialExpressionCurveAtlasRowParameter::GetCaption(), FClassTree::GetChildClasses(), FClassTree::GetChildClasses(), FClassTree::GetChildClasses(), UE::SequenceNavigator::INavigationToolItem::GetChildrenOfType(), FLocalVertexFactory::GetColorOverrideStream(), FStreamableHandle::GetContextDataOfType(), UE::SequenceNavigator::INavigationToolItem::GetDescendants(), UE::SequenceNavigator::INavigationToolItem::GetDescendantsOfType(), UE::FPlatformIoDispatcherRequestMgr::GetFileBlockRequests(), FWidgetTemplate::GetFilterStrings(), TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements(), TLruCache< KeyType, ValueType, KeyComp >::GetKeys(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GetKeys(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys(), Nanite::FSceneProxy::GetLCIs(), FStreamableHandle::GetLoadedAssets(), Nanite::Private::GetMaterialSlotInfos(), FRigVMGraphEnumDetailCustomization::GetMemoryBeingCustomized(), IModularFeatures::GetModularFeatureImplementations(), FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), ObjectElementDataUtil::GetObjectsFromHandles(), ObjectElementDataUtil::GetObjectsFromHandlesChecked(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::GetOccupiedBlockIDs(), DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs(), FPoly::GetOutsideWindings(), TBVTree< InElementType, InAllocator >::GetOverlapping(), FMeshDescription::GetPolygonAdjacentPolygons(), FMeshDescription::GetPolygonInternalEdges(), FReferenceSkeleton::GetRawRefBoneNames(), FLightMap2D::GetReferencedTextures(), FGenericSaveGameSystem::GetSaveGameNames(), SListView< TSharedPtr< FString > >::GetSelectedItems(), SListView< TSharedPtr< FString > >::GetSelectedItems(), UE::Geometry::GetShapeSet(), UE::PixelStreaming2::GetSimulcastParameters(), SMInstanceElementDataUtil::GetSMInstancesFromHandles(), SMInstanceElementDataUtil::GetSMInstancesFromHandlesChecked(), IWorldPartitionStreamingSourceProvider::GetStreamingSources(), UE::Tasks::Private::FTaskHandle::GetTraceIds, FMeshDescription::GetTriangleAdjacentTriangles(), FObjectEditorUtils::GetTypedWeakObjectPtrs(), UE::Geometry::FClusterKMeans::GetUniformSpacedInitialCenters(), FSkinnedMeshComponentHelper::GetUsedMaterials(), FStaticMeshComponentHelper::GetUsedMaterials(), UE::Geometry::FDynamicMesh3::GetVertexEdgesList(), UE::Geometry::FEdgeLoop::GetVertices(), UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), FArrangedChildren::Hittest2_FromArray(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::Init(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), UE::Geometry::FArrangement2d::insert_segment(), Algo::KahnTopologicalSort(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FLandscapeDataInterface::LockMip(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), MakeConstMeshBuildVertexView(), MakeMeshBuildVertexView(), MovieSceneToolHelpers::MergeChannels(), FShaderPreprocessOutput::MoveDirectives(), FConfigSection::MultiFind(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFind(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFindPointer(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFindPointer(), SSCS_RowWidget::OnAttachToDropAction(), TreeFilterHandler< TSharedPtr< FItem > >::OnGetFilteredChildren(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), Sequencer::PasteKeys(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement(), FReferenceSkeleton::RemoveIndividualBone(), UE::Geometry::FMeshRegionOperator::RepairPossibleNonManifoldEdges(), UE::FIoFileBlockRequestQueue::Reprioritize(), UE::FPlatformIoDispatcherBase::ScatterGather(), UE::Geometry::FGeometrySelectionEditor::Select(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV(), FHeightmapAccessor< bInUseInterp >::SetData(), FReimportHandler::SetReimportPaths(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges(), TQuadTree< ElementType, NodeCapacity >::Split(), DisplayClusterHelpers::str::StrToArray(), FGameModeInfoCustomizer::SyncBrowserToClass(), UE::Sequencer::FViewModelListIterator::ToArray(), UE::Sequencer::FViewModelSubListIterator::ToArray(), UE::Geometry::FDelaunay2::Triangulate(), FTaskGraphInterface::TriggerEventWhenTaskCompletes(), UE::FPlatformIoDispatcherRequestMgr::TryCancelAllReadRequests(), TDirectoryTree< ValueType >::FTreeNode::TryGetChildren(), UCLASS(), TRange< float >::Union(), UE::Anim::FNamedValueArrayUtils::Union(), FBuoyancyComponentSim::UpdateBuoyancy(), UE::Geometry::FDynamicMeshOctree3::UpdateLevelCutSet(), USTRUCT(), USTRUCT(), FSoundWaveLoadingBehaviorUtil::WalkClassHierarchy(), and WriteNetReport().
Add_GetRef() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::Add_GetRef (const ElementType & Item) inline nodiscard
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
Parameters
Item The item to add
Returns
A reference to the newly-inserted element.
See also
AddDefaulted_GetRef, AddUnique_GetRef, AddZeroed_GetRef, Insert_GetRef
Definition at line 2747 of file Array.h.
Add_GetRef() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::Add_GetRef (ElementType && Item) inline nodiscard
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
Move semantics version.
Parameters
Item The item to add
Returns
A reference to the newly-inserted element.
See also
AddDefaulted_GetRef, AddUnique_GetRef, AddZeroed_GetRef, Insert_GetRef
Definition at line 2734 of file Array.h.
Referenced by UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), and UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom().
AddDefaulted() [1/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::AddDefaulted () inline
Adds new items to the end of the array, possibly reallocating the whole array to fit.
The new items will be default-constructed.
Parameters
Count The number of new items to add.
Returns
Index to the first of the new items.
See also
Add, AddZeroed, AddUnique, Append, Insert
Definition at line 2805 of file Array.h.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), SAnimAttributeView::DisplayNewAttributeContainerSnapshots(), ParallelForWithPreWorkWithTaskContext(), ParallelForWithTaskContext(), ParallelForWithTaskContext(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PreLockComponentHeaders(), and DisplayClusterHelpers::str::StrToArray().
AddDefaulted() [2/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::AddDefaulted (SizeType Count) inline
Definition at line 2811 of file Array.h.
AddDefaulted_GetRef()
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::AddDefaulted_GetRef () inline nodiscard
Add a new item to the end of the array, possibly reallocating the whole array to fit.
The new item will be default-constructed.
Returns
A reference to the newly-inserted element.
See also
Add_GetRef, AddZeroed_GetRef, AddUnique_GetRef, Insert_GetRef
Definition at line 2825 of file Array.h.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled(), and TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByStartTime().
AddUninitialized() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::AddUninitialized () inline
Adds a given number of uninitialized elements into the array.
Caution, AddUninitialized() will create elements without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Parameters
Count Number of elements to add.
Returns
Number of elements in array before addition.
Definition at line 1671 of file Array.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::FTriIDBlockGrid(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::BulkSerialize(), TextureLayoutTools::ComputeDifferenceArray(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), FLandscapeConfigHelper::CopySubregion(), TChunkedArray< TUniquePtr< DescType > >::CopyToLinearArray(), TBVTree< InElementType, InAllocator >::CreateCommonInternal(), FLandscapeConfigHelper::ExpandData(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), Algo::LevenshteinDistance(), ParallelForWithTaskContext(), ParallelForWithTaskContext(), FShadowSignedDistanceFieldData2D::Quantize(), FLandscapeConfigHelper::ResampleData(), TSkeletalMeshVertexData< VertexDataType >::ResizeBuffer(), FDynamicEmitterReplayDataBase::Serialize(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNum(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUninitialized(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
AddUninitialized() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::AddUninitialized (SizeType Count) inline
Definition at line 1718 of file Array.h.
AddUnique() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::AddUnique (const ElementType & Item) inline
Adds unique element to array if it doesn't exist.
Parameters
Item Item to add.
Returns
Index of the element in the array.
See also
Add, AddDefaulted, AddZeroed, Append, Insert
Definition at line 3015 of file Array.h.
AddUnique() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::AddUnique (ElementType && Item) inline
Adds unique element to array if it doesn't exist.
Move semantics version.
Parameters
Item Item to add.
Returns
Index of the element in the array.
See also
Add, AddDefaulted, AddZeroed, Append, Insert
Definition at line 3003 of file Array.h.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), FShaderCompilerInput::GatherSharedInputs(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetAllKeyNames(), FIoStoreShaderCodeArchive::GetAllShaderIndices(), FShaderCodeArchive::GetAllShaderIndices(), FMeshDescription::GetEdgeConnectedPolygons(), FPoly::GetOutsideWindings(), FMeshDescription::GetVertexConnectedPolygons(), FMeshDescription::GetVertexInstanceConnectedPolygons(), USoundCue::RecursiveFindNode(), and USoundCue::RecursiveFindNode().
AddUniqueImpl()
template<typename InElementType, typename InAllocatorType> template<typename ArgsType> SizeType TArray< InElementType, InAllocatorType >::AddUniqueImpl (ArgsType && Args) inline private
Adds unique element to array if it doesn't exist.
Parameters
Args Item to add.
Returns
Index of the element in the array.
Definition at line 2981 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AddUnique(), and RangedForIteratorType< FAnimNextTraitEventPtr >::AddUnique().
AddZeroed() [1/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::AddZeroed () inline
Adds new items to the end of the array, possibly reallocating the whole array to fit.
The new items will be zeroed.
Caution, AddZeroed() will create elements without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Parameters
Count The number of new items to add.
Returns
Index to the first of the new items.
See also
Add, AddDefaulted, AddUnique, Append, Insert
Definition at line 2765 of file Array.h.
Referenced by UE::MeshDeformation::ConstructIDTCotangentLaplacian(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::DumpStats(), UE::Math::TVector< T >::GenerateClusterCenters(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumZeroed(), USTRUCT(), and USTRUCT().
AddZeroed() [2/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::AddZeroed (SizeType Count) inline
Definition at line 2771 of file Array.h.
AddZeroed_GetRef()
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::AddZeroed_GetRef () inline nodiscard
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
The new item will be zeroed.
Caution, AddZeroed_GetRef() will create elements without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Returns
A reference to the newly-inserted element.
See also
Add_GetRef, AddDefaulted_GetRef, AddUnique_GetRef, Insert_GetRef
Definition at line 2789 of file Array.h.
Append() [1/6]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::Append (const ElementType * Ptr, SizeType Count) inline
Adds a raw array of elements to the end of the TArray.
Parameters
Ptr A pointer to an array of elements to add.
Count The number of elements to insert from Ptr.
See also
Add, Insert
Definition at line 2505 of file Array.h.
Append() [2/6]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherAllocatorType> void TArray< InElementType, InAllocatorType >::Append (const TArray< OtherElementType, OtherAllocatorType > & Source) inline
Appends the specified array to this array.
AllocatorType changing version.
Parameters
Source The array to append.
See also
Add, Insert
Definition at line 2422 of file Array.h.
Referenced by FActorIteratorState::FActorIteratorState(), FUObjectSerializeContext::AppendLoadedObjectsAndEmpty(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::CollapseNodesInternal(), TEvaluationTreeEntryContainer< ElementType >::Compact(), UE::Geometry::FClusterKMeans::ComputeClusters(), FBlueprintEditorUtils::GetAllNodesOfClass(), UE::SequenceNavigator::INavigationToolItem::GetDescendants(), UE::SequenceNavigator::INavigationToolItem::GetDescendantsOfType(), Metasound::TArrayConcatOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayNumOperator< ArrayType >::GetNodeInfo(), Metasound::TArraySubsetOperator< ArrayType >::GetNodeInfo(), FPoly::GetOutsideWindings(), UE::SequenceNavigator::FNavigationToolEditorSelection::GetSelectedObjects(), FStaticMeshComponentHelper::GetUsedRayTracingOnlyMaterials(), FMeshDescription::GetVertexConnectedTriangles(), UE::Geometry::TMeshQueries< TriangleMeshType >::MeshDistanceStatistics(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator+=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator+=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator+=(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), and UE::Geometry::FDelaunay2::Triangulate().
Append() [3/6]
template<typename InElementType, typename InAllocatorType> template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> void TArray< InElementType, InAllocatorType >::Append (const typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType * Ptr, SizeType Count) inline
Adds a raw array of elements to the end of the TArray.
Compatible element type version.
Parameters
Ptr A pointer to an array of elements to add.
Count The number of elements to insert from Ptr.
See also
Add, Insert
Definition at line 2963 of file Array.h.
Append() [4/6]
template<typename InElementType, typename InAllocatorType> template<typename RangeType UE_REQUIRES> void TArray< InElementType, InAllocatorType >::Append (RangeType && Source) inline
Appends the elements from a contiguous range to this array.
Parameters
Source The range of elements to append.
See also
Add, Insert
Definition at line 2480 of file Array.h.
Append() [5/6]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::Append (std::initializer_list< ElementType > InitList) inline
Adds an initializer list of elements to the end of the TArray.
Parameters
InitList The initializer list of elements to add.
See also
Add, Insert
Definition at line 2519 of file Array.h.
Append() [6/6]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherAllocator> void TArray< InElementType, InAllocatorType >::Append (TArray< OtherElementType, OtherAllocator > && Source) inline
Appends the specified array to this array.
Parameters
Source The array to append.
See also
Add, Insert
Definition at line 2446 of file Array.h.
AppendHash()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::AppendHash (const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher) inline static
Definition at line 3617 of file Array.h.
begin() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForIteratorType TArray< InElementType, InAllocatorType >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 3396 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), and USTRUCT().
begin() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForConstIteratorType TArray< InElementType, InAllocatorType >::begin () const inline nodiscard
Definition at line 3397 of file Array.h.
BulkSerialize()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::BulkSerialize (FArchive & Ar, bool bForcePerElementSerialization = false) inline
Bulk serialize array as a single memory blob when loading.
Uses regular serialization code for saving and doesn't serialize at all otherwise (e.g. transient, garbage collection, ...).
Requirements:
T's << operator needs to serialize ALL member variables in the SAME order they are layed out in memory.
T's << operator can NOT perform any fixup operations. This limitation can be lifted by manually copying the code after the BulkSerialize call.
T can NOT contain any member variables requiring constructor calls or pointers
sizeof(ElementType) must be equal to the sum of sizes of it's member variables.
e.g. use pragma pack (push,1)/ (pop) to ensure alignment
match up uint8/ WORDs so everything always end up being properly aligned
Code can not rely on serialization of T if neither IsLoading() nor IsSaving() is true.
Can only be called platforms that either have the same endianness as the one the content was saved with or had the endian conversion occur in a cooking process like e.g. for consoles.
Notes:
it is safe to call BulkSerialize on TTransArrays
IMPORTANT:
This is Overridden in XeD3dResourceArray.h Please make certain changes are propagated accordingly
Parameters
Ar FArchive to bulk serialize this TArray to/from
Definition at line 1600 of file Array.h.
Referenced by FKCachedConvexDataElement::operator<<, and FKCachedPerTriData::operator<<.
CheckAddress()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::CheckAddress (const ElementType * Addr) const inline
Checks that the specified address is not part of an element within the container.
Used for implementations to check that reference arguments aren't going to be invalidated by possible reallocation.
Parameters
Addr The address to check.
See also
Add, Remove
Definition at line 1962 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Add(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Remove(), and RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSwap().
CheckInvariants()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::CheckInvariants () const inline
Checks array invariants: if array size is greater than or equal to zero and less than or equal to the maximum.
Definition at line 1050 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::RangeCheck(), RangedForIteratorType< FAnimNextTraitEventPtr >::RangeCheck(), and RangedForIteratorType< FAnimNextTraitEventPtr >::Shrink().
Contains()
template<typename InElementType, typename InAllocatorType> template<typename ComparisonType> bool TArray< InElementType, InAllocatorType >::Contains (const ComparisonType & Item) const inline nodiscard
Checks if this array contains the element.
Returns
True if found. False otherwise.
See also
ContainsByPredicate, FilterByPredicate, FindByPredicate
Definition at line 1525 of file Array.h.
Referenced by TFindObjectReferencers< T >::TFindObjectReferencers(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), DoActionToAllPackages(), UE::Geometry::FGroupTopology::ForGroupSetEdges(), TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements(), FMeshDescription::GetPolygonInternalEdges(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), FSceneViewOwner::IsPartOf(), IAnimationDataController::IsSupportedCurveType(), FReferenceSkeleton::RemoveBonesByName(), and RigVMTypeUtils::RequiresCPPTypeObject().
ContainsByPredicate()
template<typename InElementType, typename InAllocatorType> template<typename Predicate> UE_NODEBUG FORCEINLINE bool TArray< InElementType, InAllocatorType >::ContainsByPredicate (Predicate Pred) const inline nodiscard
Checks if this array contains an element for which the predicate is true.
Parameters
Predicate to use
Returns
True if found. False otherwise.
See also
Contains, Find
Definition at line 1545 of file Array.h.
CopyToEmpty()
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> void TArray< InElementType, InAllocatorType >::CopyToEmpty (const OtherElementType * OtherData, OtherSizeType OtherNum, SizeType PrevMax) inline private
Copies data from one array into this array.
Uses the fast path if the data in question does not need a constructor.
Parameters
Source The source array to copy
PrevMax The previous allocated size
Definition at line 3504 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::TArray(), RangedForIteratorType< FAnimNextTraitEventPtr >::TArray(), RangedForIteratorType< FAnimNextTraitEventPtr >::TArray(), and RangedForIteratorType< FAnimNextTraitEventPtr >::TArray().
CopyToEmptyWithSlack()
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> void TArray< InElementType, InAllocatorType >::CopyToEmptyWithSlack (const OtherElementType * OtherData, OtherSizeType OtherNum, SizeType PrevMax, SizeType ExtraSlack) inline private
Copies data from one array into this array.
Uses the fast path if the data in question does not need a constructor.
Parameters
Source The source array to copy
PrevMax The previous allocated size
ExtraSlack Additional amount of memory to allocate at the end of the buffer. Counted in elements.
Definition at line 3541 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::TArray().
CopyUnfrozen()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::CopyUnfrozen (const FMemoryUnfreezeContent & Context, void * Dst) const inline
Definition at line 3603 of file Array.h.
CountBytes()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::CountBytes (FArchive & Ar) const inline
Count bytes needed to serialize this array.
Parameters
Ar Archive to count for.
Definition at line 1656 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::BulkSerialize(), and USTRUCT().
CreateConstIterator()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TConstIterator TArray< InElementType, InAllocatorType >::CreateConstIterator () const inline nodiscard
Creates a const iterator for the contents of this array.
Returns
The const iterator.
Definition at line 3372 of file Array.h.
Referenced by EditorAnimUtils::DuplicateAssets(), and FObjectEditorUtils::GetTypedWeakObjectPtrs().
CreateIterator()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TIterator TArray< InElementType, InAllocatorType >::CreateIterator () inline nodiscard
Creates an iterator for the contents of this array.
Returns
The iterator.
Definition at line 3362 of file Array.h.
Emplace()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::Emplace (ArgsType &&... Args) inline
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
Parameters
Args The arguments to forward to the constructor of the new item.
Returns
Index to the new item
Definition at line 2571 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Add(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), ConvertInsertAndSort(), UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), FMaterial::DeferredDeleteArray(), FMaterial::DeferredDeleteArray(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), UE::Geometry::TImplicitBlend< TriangleMeshType >::GenerateBlendAnalytic(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::GetEnumDataTypeInterface(), DisplayClusterHelpers::filesystem::GetFullPathForConfig(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), ParallelForWithPreWorkWithTaskContext(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), and FAsyncAddPrimitiveQueue::Tick().
Emplace_GetRef()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::Emplace_GetRef (ArgsType &&... Args) inline nodiscard
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
Parameters
Args The arguments to forward to the constructor of the new item.
Returns
A reference to the newly-inserted element.
Definition at line 2623 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Add_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Add_GetRef(), UE::Geometry::TPlanarComplex< double >::ConvertOutputToGeneralPolygons(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::Init(), FNetSimCueDispatcher::Invoke(), LoadFromCompactBinary(), and FAsyncAddPrimitiveQueue::Tick().
EmplaceAt()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> FORCEINLINE void TArray< InElementType, InAllocatorType >::EmplaceAt (SizeType Index, ArgsType &&... Args) inline
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
Parameters
Index The index to add the item at.
Args The arguments to forward to the constructor of the new item.
Definition at line 2675 of file Array.h.
EmplaceAt_GetRef()
template<typename InElementType, typename InAllocatorType> template<typename... ArgsType> FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::EmplaceAt_GetRef (SizeType Index, ArgsType &&... Args) inline nodiscard
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
Parameters
Index The index to add the item at.
Args The arguments to forward to the constructor of the new item.
Returns
A reference to the newly-inserted element.
Definition at line 2689 of file Array.h.
Empty()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::Empty (SizeType Slack = 0) inline
Empties the array.
It calls the destructors on held items if needed.
Parameters
Slack (Optional) The expected usage size after empty operation. Default is 0.
Definition at line 2286 of file Array.h.
Referenced by UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), FLandscapeConfigHelper::CopySubregion(), Metasound::TParamPackFixedArray< typename T::ElementType, MaxNumItems >::CopyToArray(), FCookStatsManager::CreateKeyValueArray(), FMaterial::DeferredDeleteArray(), FScopedWidgetSlotArguments< FNodeSlot >::Empty(), TSlotlessChildren< ChildType >::Empty(), FLandscapeConfigHelper::ExpandData(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateKeyArray(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GenerateKeyArray(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateValueArray(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GenerateValueArray(), EditorAnimUtils::GetAssetsFromProperties(), UMaterialExpressionCurveAtlasRowParameter::GetCaption(), FClassTree::GetChildClasses(), FClassTree::GetChildClasses(), FPoly::GetOutsideWindings(), SListView< TSharedPtr< FString > >::GetSelectedItems(), SListView< TSharedPtr< FString > >::GetSelectedItems(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), FShadowSignedDistanceFieldData2D::Quantize(), FLandscapeConfigHelper::ResampleData(), FHeightmapAccessor< bInUseInterp >::SetData(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
end() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForIteratorType TArray< InElementType, InAllocatorType >::end () inline nodiscard
Definition at line 3398 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), and USTRUCT().
end() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForConstIteratorType TArray< InElementType, InAllocatorType >::end () const inline nodiscard
Definition at line 3399 of file Array.h.
FilterByPredicate()
template<typename InElementType, typename InAllocatorType> template<typename Predicate> TArray< ElementType > TArray< InElementType, InAllocatorType >::FilterByPredicate (Predicate Pred) const inline nodiscard
Filters the elements in the array based on a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
TArray with the same type as this object which contains the subset of elements for which the functor returns true.
See also
FindByPredicate, ContainsByPredicate
Definition at line 1505 of file Array.h.
Find() [1/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Find (const ElementType & Item) const inline nodiscard
Finds element within the array.
Parameters
Item Item to look for.
Returns
Index of the found element. INDEX_NONE otherwise.
See also
FindLast, FindLastByPredicate
Definition at line 1306 of file Array.h.
Find() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE bool TArray< InElementType, InAllocatorType >::Find (const ElementType & Item, SizeType & Index) const inline
Finds element within the array.
Parameters
Item Item to look for.
Index Will contain the found index.
Returns
True if found. False otherwise.
See also
FindLast, FindLastByPredicate
Definition at line 1293 of file Array.h.
Referenced by FPoly::GetOutsideWindings(), FShaderCompilerInput::SerializeSharedInputs(), and FTickableObjectRenderThread::Unregister().
FindByKey() [1/2]
template<typename InElementType, typename InAllocatorType> template<typename KeyType> ElementType * TArray< InElementType, InAllocatorType >::FindByKey (const KeyType & Key) inline nodiscard
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
Time Complexity: O(n), starts iteration from the beginning so better performance if Key is in the front
Parameters
Key The key to search by.
Returns
Pointer to the first matching element, or nullptr if none is found.
See also
Find
Definition at line 1450 of file Array.h.
FindByKey() [2/2]
template<typename InElementType, typename InAllocatorType> template<typename KeyType> UE_NODEBUG FORCEINLINE const ElementType * TArray< InElementType, InAllocatorType >::FindByKey (const KeyType & Key) const inline nodiscard
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
Parameters
Key The key to search by.
Returns
Pointer to the first matching element, or nullptr if none is found.
See also
Find
Definition at line 1436 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::FindByKey().
FindByPredicate() [1/2]
template<typename InElementType, typename InAllocatorType> template<typename Predicate> ElementType * TArray< InElementType, InAllocatorType >::FindByPredicate (Predicate Pred) inline nodiscard
Finds an element which matches a predicate functor.
Parameters
Pred The functor to apply to each element. true, or nullptr if none is found.
See also
FilterByPredicate, ContainsByPredicate
Definition at line 1483 of file Array.h.
FindByPredicate() [2/2]
template<typename InElementType, typename InAllocatorType> template<typename Predicate> UE_NODEBUG FORCEINLINE const ElementType * TArray< InElementType, InAllocatorType >::FindByPredicate (Predicate Pred) const inline nodiscard
Finds an element which matches a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
Pointer to the first element for which the predicate returns true, or nullptr if none is found.
See also
FilterByPredicate, ContainsByPredicate
Definition at line 1471 of file Array.h.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::ContainsByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindByPredicate(), Metasound::Frontend::IEnumDataTypeInterface::FindEntryBy(), and FMeshDescription::GetVertexInstanceForPolygonVertex().
FindItemByClass()
template<typename InElementType, typename InAllocatorType> template<typename SearchType> bool TArray< InElementType, InAllocatorType >::FindItemByClass (SearchType ** Item = nullptr, SizeType * ItemIndex = nullptr, SizeType StartIndex = 0) const inline
Searches for the first entry of the specified type, will only work with TArray<UObject*>.
Optionally return the item's index, and can specify the start index.
Parameters
Item (Optional output) If it's not null, then it will point to the found element. Untouched if element hasn't been found.
ItemIndex (Optional output) If it's not null, then it will be set to the position of found element in the array. Untouched if element hasn't been found.
StartIndex (Optional) Index in array at which the function should start to look for element.
Returns
True if element was found. False otherwise.
Definition at line 3332 of file Array.h.
FindLast() [1/2]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::FindLast (const ElementType & Item) const inline nodiscard
Finds element within the array starting from the end.
Parameters
Item Item to look for.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 1339 of file Array.h.
FindLast() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE bool TArray< InElementType, InAllocatorType >::FindLast (const ElementType & Item, SizeType & Index) const inline
Finds element within the array starting from the end.
Parameters
Item Item to look for.
Index Output parameter. Found index.
Returns
True if found. False otherwise.
See also
Find, FindLastByPredicate
Definition at line 1327 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::FindLast().
FindLastByPredicate() [1/2]
template<typename InElementType, typename InAllocatorType> template<typename Predicate> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::FindLastByPredicate (Predicate Pred) const inline nodiscard
Searches the array for the last occurrence of an element which matches the specified predicate.
Parameters
Pred Predicate taking array element and returns true if element matches search criteria, false otherwise.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 1381 of file Array.h.
FindLastByPredicate() [2/2]
template<typename InElementType, typename InAllocatorType> template<typename Predicate> SizeType TArray< InElementType, InAllocatorType >::FindLastByPredicate (Predicate Pred, SizeType Count) const inline nodiscard
Searches an initial subrange of the array for the last occurrence of an element which matches the specified predicate.
Parameters
Pred Predicate taking array element and returns true if element matches search criteria, false otherwise.
Count The number of elements from the front of the array through which to search.
Returns
Index of the found element. INDEX_NONE otherwise.
Definition at line 1360 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::FindLastByPredicate().
GetAllocatedSize()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SIZE_T TArray< InElementType, InAllocatorType >::GetAllocatedSize (void) const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
Number of bytes allocated by this container.
Definition at line 1031 of file Array.h.
Referenced by USTRUCT().
GetAllocatorInstance() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG ElementAllocatorType & TArray< InElementType, InAllocatorType >::GetAllocatorInstance () inline nodiscard
Definition at line 3949 of file Array.h.
GetAllocatorInstance() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG const ElementAllocatorType & TArray< InElementType, InAllocatorType >::GetAllocatorInstance () const inline nodiscard
Definition at line 3945 of file Array.h.
GetData() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE const ElementType * TArray< InElementType, InAllocatorType >::GetData () const inline nodiscard
Helper function for returning a typed pointer to the first array entry.
Returns
Pointer to first array entry or nullptr if ArrayMax == 0.
Definition at line 1009 of file Array.h.
GetData() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType * TArray< InElementType, InAllocatorType >::GetData () inline nodiscard
Helper function for returning a typed pointer to the first array entry.
Returns
Pointer to first array entry or nullptr if ArrayMax == 0.
Definition at line 999 of file Array.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::FTriIDBlockGrid(), RangedForIteratorType< FAnimNextTraitEventPtr >::~TArray(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted_GetRef(), FReferenceCollector::AROPrivate::AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::AddTriID(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::begin(), RangedForIteratorType< FAnimNextTraitEventPtr >::begin(), RangedForIteratorType< FAnimNextTraitEventPtr >::BulkSerialize(), RangedForIteratorType< FAnimNextTraitEventPtr >::CheckAddress(), FOodleCompressedArray::CompressTArray(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), RangedForIteratorType< FAnimNextTraitEventPtr >::Contains(), FMediaIOAudioOutput::ConvertAndUpmixBuffer(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmpty(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmptyWithSlack(), UE::AnimNext::FLODPose::CopyTransformsFrom(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyUnfrozen(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), CreateByteAddressBuffer(), CreateStructuredBuffer(), CreateStructuredBuffer(), FOodleCompressedArray::DecompressToTArray(), FTransactionallySafeArchiveWriter::DoDeferredWrites(), RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Empty(), RangedForIteratorType< FAnimNextTraitEventPtr >::end(), RangedForIteratorType< FAnimNextTraitEventPtr >::end(), UE::Geometry::FVertexConnectedComponents::EnumerateContiguousComponentsFromArray(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled(), TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByStartTime(), RangedForIteratorType< FAnimNextTraitEventPtr >::FilterByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::Find(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindByKey(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindLast(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindLastByPredicate(), TAttributeArrayContainer< AttributeType >::Get(), TAttributeArrayContainer< AttributeType >::Get(), FMovieSceneChannelProxy::GetChannels(), UE::Net::TStructNetTokenDataStoreHelper< T >::GetStateFromReplayExportGroup(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPopDiscard(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::IndexOfByKey(), RangedForIteratorType< FAnimNextTraitEventPtr >::IndexOfByPredicate(), UE::ChaosDeformable::FHalfArrayBufferWithSRV::Init(), FColorVertexBuffer::InitFromColorArray(), StringConv::InlineCombineSurrogates_Array(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Last(), RangedForIteratorType< FAnimNextTraitEventPtr >::Last(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator==(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator[](), RangedForIteratorType< FAnimNextTraitEventPtr >::operator[](), FOodleCompressedArray::PeekSizes(), RangedForIteratorType< FAnimNextTraitEventPtr >::Pop(), RangedForIteratorType< FAnimNextTraitEventPtr >::rbegin(), RangedForIteratorType< FAnimNextTraitEventPtr >::rbegin(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAll(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSingle(), RangedForIteratorType< FAnimNextTraitEventPtr >::rend(), RangedForIteratorType< FAnimNextTraitEventPtr >::rend(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reset(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::scatter_tris(), FDynamicEmitterReplayDataBase::Serialize(), UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize(), TAttributeArrayContainer< AttributeType >::SetElementSize(), Nanite::FPackedCluster::SetVertResourceBatchInfo(), TBVTree< InElementType, InAllocator >::Subdivide(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), USTRUCT(), USTRUCT(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
GetSlack()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::GetSlack () const inline nodiscard
Returns the amount of slack in this array in elements.
See also
Num, Shrink
Definition at line 1041 of file Array.h.
GetTypeSize()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG static FORCEINLINE constexpr uint32 TArray< InElementType, InAllocatorType >::GetTypeSize () inline static nodiscard constexpr
Helper function returning the size of the inner type.
Returns
Size in bytes of array type.
Definition at line 1019 of file Array.h.
Referenced by CreateByteAddressBuffer(), CreateStructuredBuffer(), and CreateStructuredBuffer().
Heapify() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::Heapify () inline
Builds an implicit heap from the array.
Assumes < operator is defined for the template type.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3661 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Heapify().
Heapify() [2/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::Heapify (const PREDICATE_CLASS & Predicate) inline
Implicit heaps.
Builds an implicit heap from the array.
Parameters
Predicate Predicate class instance.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3647 of file Array.h.
HeapPop() [1/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> void TArray< InElementType, InAllocatorType >::HeapPop (ElementType & OutItem, const PREDICATE_CLASS & Predicate, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the top element from the heap.
Parameters
OutItem The removed item.
Predicate Predicate class instance.
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3754 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), and RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
HeapPop() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::HeapPop (ElementType & OutItem, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the top element from the heap.
Assumes < operator is defined for the template type.
Parameters
OutItem The removed item.
AllowShrinking (Optional) Tells if this call can shrink the array allocation if suitable after the pop. Default is yes.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3780 of file Array.h.
HeapPopDiscard() [1/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> void TArray< InElementType, InAllocatorType >::HeapPopDiscard (const PREDICATE_CLASS & Predicate, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the top element from the heap.
Parameters
Predicate Predicate class instance.
AllowShrinking (Optional) Tells if this call can shrink the array allocation if suitable after the discard. Default is yes.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3812 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPopDiscard(), RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED(), and RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
HeapPopDiscard() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::HeapPopDiscard (EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the top element from the heap.
Assumes < operator is defined for the template type.
Parameters
AllowShrinking (Optional) Tells if this call can shrink the array allocation if suitable after the discard. Default is yes.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3835 of file Array.h.
HeapPush() [1/4]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG SizeType TArray< InElementType, InAllocatorType >::HeapPush (const ElementType & InItem) inline
Adds a new element to the heap.
Assumes < operator is defined for the template type.
Parameters
InItem Item to be added.
Returns
The index of the new element.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3737 of file Array.h.
HeapPush() [2/4]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> SizeType TArray< InElementType, InAllocatorType >::HeapPush (const ElementType & InItem, const PREDICATE_CLASS & Predicate) inline
Adds a new element to the heap.
Parameters
InItem Item to be added.
Predicate Predicate class instance.
Returns
The index of the new element.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3700 of file Array.h.
HeapPush() [3/4]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG SizeType TArray< InElementType, InAllocatorType >::HeapPush (ElementType && InItem) inline
Adds a new element to the heap.
Assumes < operator is defined for the template type.
Parameters
InItem Item to be added.
Returns
The index of the new element.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3721 of file Array.h.
HeapPush() [4/4]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> SizeType TArray< InElementType, InAllocatorType >::HeapPush (ElementType && InItem, const PREDICATE_CLASS & Predicate) inline
Adds a new element to the heap.
Parameters
InItem Item to be added.
Predicate Predicate class instance.
Returns
The index of the new element.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3678 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), and RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush().
HeapRemoveAt() [1/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> void TArray< InElementType, InAllocatorType >::HeapRemoveAt (SizeType Index, const PREDICATE_CLASS & Predicate, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element from the heap.
Parameters
Index Position at which to remove item.
Predicate Predicate class instance.
AllowShrinking (Optional) Tells if this call can shrink the array allocation if suitable after the remove (default = yes).
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3880 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED(), and RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
HeapRemoveAt() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::HeapRemoveAt (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element from the heap.
Assumes < operator is defined for the template type.
Parameters
Index Position at which to remove item.
AllowShrinking (Optional) Tells if this call can shrink the array allocation if suitable after the remove (default = yes).
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3906 of file Array.h.
HeapSort() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::HeapSort () inline
Performs heap sort on the array.
Assumes < operator is defined for the template type.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your array will be heapified by the values being pointed to, rather than the pointers' values. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3940 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapSort().
HeapSort() [2/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> UE_NODEBUG void TArray< InElementType, InAllocatorType >::HeapSort (const PREDICATE_CLASS & Predicate) inline
Performs heap sort on the array.
Parameters
Predicate Predicate class instance.
Note
: If your array contains raw pointers, they will be automatically dereferenced during heapification. Therefore, your predicate will be passed references rather than pointers. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3926 of file Array.h.
HeapTop() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG const ElementType & TArray< InElementType, InAllocatorType >::HeapTop () const inline nodiscard
Returns the top element from the heap (does not remove the element).
Const version.
Returns
The reference to the top element from the heap.
Definition at line 3852 of file Array.h.
HeapTop() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG ElementType & TArray< InElementType, InAllocatorType >::HeapTop () inline nodiscard
Returns the top element from the heap (does not remove the element).
Returns
The reference to the top element from the heap.
Definition at line 3862 of file Array.h.
IndexOfByKey()
template<typename InElementType, typename InAllocatorType> template<typename KeyType> SizeType TArray< InElementType, InAllocatorType >::IndexOfByKey (const KeyType & Key) const inline nodiscard
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
Parameters
Key The key to search by.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 1394 of file Array.h.
Referenced by UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey(), and UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Remove().
IndexOfByPredicate()
template<typename InElementType, typename InAllocatorType> template<typename Predicate> SizeType TArray< InElementType, InAllocatorType >::IndexOfByPredicate (Predicate Pred) const inline nodiscard
Finds an item by predicate.
Parameters
Pred The predicate to match.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 1414 of file Array.h.
Referenced by FCompressedAnimSequence::GetTrackIndexFromSkeletonIndex().
Init()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::Init (const ElementType & Element, SizeType Number) inline
Sets the size of the array, filling it with the given element.
Parameters
Element The element to fill array with.
Number The number of elements that the array should be able to contain after allocation.
Definition at line 3053 of file Array.h.
Referenced by ArrangeChildrenInStack(), UE::Geometry::FSparseDynamicPointOctree3::CheckValidity(), UE::Geometry::FSizedDisjointSet::CompactedGroupIndexToGroupID(), UE::Geometry::FSparseDynamicPointOctree3::ComputeStatistics(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetAllEdgeLengths(), UE::Geometry::GetFKElement(), and UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select().
Insert() [1/8]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Insert (const ElementType & Item, SizeType Index) inline
Inserts a given element into the array at given location.
Parameters
Item The element to insert.
Index Tells where to insert the new elements.
Returns
Location at which the insert was done.
See also
Add, Remove
Definition at line 1995 of file Array.h.
Insert() [2/8]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Insert (const ElementType * Ptr, SizeType Count, SizeType Index) inline
Inserts a raw array of elements at a particular index in the TArray.
Parameters
Ptr A pointer to an array of elements to add.
Count The number of elements to insert from Ptr.
Index The index to insert the elements at.
Returns
The index of the first element inserted.
See also
Add, Remove
Definition at line 1944 of file Array.h.
Insert() [3/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocator> SizeType TArray< InElementType, InAllocatorType >::Insert (const TArray< ElementType, OtherAllocator > & Items, const SizeType InIndex) inline
Inserts given elements into the array at given location.
Parameters
Items Array of elements to insert.
InIndex Tells where to insert the new elements.
Returns
Location at which the item was inserted.
Definition at line 1900 of file Array.h.
Insert() [4/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> SizeType TArray< InElementType, InAllocatorType >::Insert (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > & Items, const SizeType InIndex) inline
Inserts given elements into the array at given location.
Compatible element type version.
Parameters
Items Array of elements to insert.
InIndex Tells where to insert the new elements.
Returns
Location at which the item was inserted.
Definition at line 2910 of file Array.h.
Insert() [5/8]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Insert (ElementType && Item, SizeType Index) inline
Inserts a given element into the array at given location.
Move semantics version.
Parameters
Item The element to insert.
Index Tells where to insert the new elements.
Returns
Location at which the insert was done.
See also
Add, Remove
Definition at line 1976 of file Array.h.
Insert() [6/8]
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Insert (std::initializer_list< ElementType > InitList, const SizeType InIndex) inline
Inserts given elements into the array at given location.
Parameters
InitList Array of elements to insert.
InIndex Tells where to insert the new elements.
Returns
Location at which the item was inserted.
Definition at line 1882 of file Array.h.
Referenced by ConvertInsertAndSort(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), and FRigVMGraphMathTypeDetailCustomization::GetPropertyChain().
Insert() [7/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocator> SizeType TArray< InElementType, InAllocatorType >::Insert (TArray< ElementType, OtherAllocator > && Items, const SizeType InIndex) inline
Inserts given elements into the array at given location.
Parameters
Items Array of elements to insert.
InIndex Tells where to insert the new elements.
Returns
Location at which the item was inserted.
Definition at line 1920 of file Array.h.
Insert() [8/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> SizeType TArray< InElementType, InAllocatorType >::Insert (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > && Items, const SizeType InIndex) inline
Inserts given elements into the array at given location.
Compatible element type version.
Parameters
Items Array of elements to insert.
InIndex Tells where to insert the new elements.
Returns
Location at which the item was inserted.
Definition at line 2935 of file Array.h.
Insert_GetRef() [1/2]
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::Insert_GetRef (const ElementType & Item, SizeType Index) inline nodiscard
Inserts a given element into the array at given location.
Parameters
Item The element to insert.
Index Tells where to insert the new element.
Returns
A reference to the newly-inserted element.
See also
Add, Remove
Definition at line 2035 of file Array.h.
Insert_GetRef() [2/2]
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::Insert_GetRef (ElementType && Item, SizeType Index) inline nodiscard
Inserts a given element into the array at given location.
Move semantics version.
Parameters
Item The element to insert.
Index Tells where to insert the new element.
Returns
A reference to the newly-inserted element.
See also
Add, Remove
Definition at line 2015 of file Array.h.
InsertDefaulted() [1/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertDefaulted (SizeType Index) inline
Inserts a given number of default-constructed elements into the array at a given location.
Parameters
Index Tells where to insert the new elements.
Count Number of elements to add.
See also
Insert, InsertUninitialized, InsertZeroed
Definition at line 1848 of file Array.h.
InsertDefaulted() [2/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertDefaulted (SizeType Index, SizeType Count) inline
Definition at line 1853 of file Array.h.
InsertDefaulted_GetRef()
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::InsertDefaulted_GetRef (SizeType Index) inline
Inserts a default-constructed element into the array at a given location.
Parameters
Index Tells where to insert the new element.
Returns
A reference to the newly-inserted element.
See also
Insert_GetRef, InsertZeroed_GetRef
Definition at line 1867 of file Array.h.
InsertUninitialized() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::InsertUninitialized (SizeType Index) inline
Inserts a given number of uninitialized elements into the array at given location.
Caution, InsertUninitialized() will create elements without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Parameters
Index Tells where to insert the new elements.
Count Number of elements to add.
See also
Insert, InsertZeroed, InsertDefaulted
Definition at line 1789 of file Array.h.
Referenced by UE::Anim::FNamedValueArrayUtils::Union().
InsertUninitialized() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::InsertUninitialized (SizeType Index, SizeType Count) inline
Definition at line 1793 of file Array.h.
InsertUninitializedImpl() [1/3]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertUninitializedImpl (SizeType Index) inline private
Definition at line 1732 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::EmplaceAt_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted_GetRef(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), and RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed_GetRef().
InsertUninitializedImpl() [2/3]
template<typename InElementType, typename InAllocatorType> template<typename OtherSizeType UE_REQUIRES> UE_NODEBUG void TArray< InElementType, InAllocatorType >::InsertUninitializedImpl (SizeType Index, OtherSizeType Count) inline private
Definition at line 1770 of file Array.h.
InsertUninitializedImpl() [3/3]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertUninitializedImpl (SizeType Index, SizeType Count) inline private
Definition at line 1752 of file Array.h.
InsertZeroed() [1/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertZeroed (SizeType Index) inline
Inserts a given number of zeroed elements into the array at given location.
Caution, InsertZeroed() will create elements without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Parameters
Index Tells where to insert the new elements.
Count Number of elements to add.
See also
Insert, InsertUninitialized, InsertDefaulted
Definition at line 1810 of file Array.h.
InsertZeroed() [2/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::InsertZeroed (SizeType Index, SizeType Count) inline
Definition at line 1815 of file Array.h.
InsertZeroed_GetRef()
template<typename InElementType, typename InAllocatorType> ElementType & TArray< InElementType, InAllocatorType >::InsertZeroed_GetRef (SizeType Index) inline
Inserts a zeroed element into the array at given location.
Caution, InsertZeroed_GetRef() will create an element without calling the constructor and this is not appropriate for element types that require a constructor to function properly.
Parameters
Index Tells where to insert the new element.
Returns
A reference to the newly-inserted element.
See also
Insert_GetRef, InsertDefaulted_GetRef
Definition at line 1832 of file Array.h.
IsEmpty()
template<typename InElementType, typename InAllocatorType> bool TArray< InElementType, InAllocatorType >::IsEmpty () const inline nodiscard
Returns true if the array is empty and contains no elements.
Returns
True if the array is empty.
See also
Num
Definition at line 1105 of file Array.h.
Referenced by FActorIteratorState::FActorIteratorState(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTrianglesImpl(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), FStreamingSourceShapeHelper::ForEachShape(), FStaticMeshComponentHelper::GetUsedRayTracingOnlyMaterials(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::Initialize(), STreeView< FRigVMSearchResult >::PopulatePinnedItems(), UE::FGenericPlatformIoDispatcher::ProcessFileIo(), TAsyncTreeDifferences< InNodeType >::ProcessTopOfQueue(), FAsyncAddPrimitiveQueue::Push(), FSendRenderDynamicDataPrimitivesQueue::Push(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), FAsyncAddPrimitiveQueue::Tick(), and UE::FPlatformIoDispatcherRequestMgr::TryCancelAllReadRequests().
IsValidIndex()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE bool TArray< InElementType, InAllocatorType >::IsValidIndex (SizeType Index) const inline nodiscard
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of elements in the array.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 1094 of file Array.h.
Referenced by FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr(), FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef(), FShaderCompilerInput::DeserializeSharedInputs(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), UE::SequenceNavigator::INavigationToolItem::GetChildAt(), FReferenceSkeleton::GetParentIndexInternal(), UE::Anim::Conversion::MakeIndex(), STreeView< FRigVMSearchResult >::PopulatePinnedItems(), and USTRUCT().
Last() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE const ElementType & TArray< InElementType, InAllocatorType >::Last (SizeType IndexFromTheEnd = 0) const inline nodiscard
Returns n-th last element from the array.
Const version of the above.
Parameters
IndexFromTheEnd (Optional) Index from the end of array (default = 0).
Returns
Reference to n-th last element from the array.
Definition at line 1258 of file Array.h.
Last() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::Last (SizeType IndexFromTheEnd = 0) inline nodiscard
Returns n-th last element from the array.
Parameters
IndexFromTheEnd (Optional) Index from the end of array (default = 0).
Returns
Reference to n-th last element from the array.
Definition at line 1244 of file Array.h.
Referenced by ConvexHull2D::ComputeConvexHullLegacy2(), UE::Geometry::FVerticalCylinderGeneratorBase::GenerateVerticalCircleSweep(), FRigVMASTProxy::GetSibling(), and UE::Geometry::TPolyline< T, 2 >< double >::Simplify().
Max()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::Max () const inline nodiscard
Returns maximum number of elements in array.
Returns
Maximum number of elements in array.
See also
GetSlack
Definition at line 1133 of file Array.h.
MoveOrCopy()
template<typename InElementType, typename InAllocatorType> template<typename FromArrayType, typename ToArrayType> FORCEINLINE void TArray< InElementType, InAllocatorType >::MoveOrCopy (ToArrayType & ToArray, FromArrayType & FromArray, SizeType PrevMax) inline static private
Moves or copies array.
Depends on the array type traits.
Parameters
ToArray Array to move into.
FromArray Array to move from.
PrevMax The previous allocated size.
Definition at line 824 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopyWithSlack(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::TArray(), and RangedForIteratorType< FAnimNextTraitEventPtr >::TArray().
MoveOrCopyWithSlack()
template<typename InElementType, typename InAllocatorType> template<typename FromArrayType, typename ToArrayType> FORCEINLINE void TArray< InElementType, InAllocatorType >::MoveOrCopyWithSlack (ToArrayType & ToArray, FromArrayType & FromArray, SizeType PrevMax, SizeType ExtraSlack) inline static private
Moves or copies array.
Depends on the array type traits.
Parameters
ToArray Array to move into.
FromArray Array to move from.
PrevMax The previous allocated size.
ExtraSlack Tells how much extra memory should be preallocated at the end of the array in the number of elements.
Definition at line 881 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::TArray().
Num()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SizeType TArray< InElementType, InAllocatorType >::Num () const inline nodiscard
Returns number of elements in array.
Returns
Number of elements in array.
See also
GetSlack
Definition at line 1116 of file Array.h.
Referenced by FActorIteratorState::FActorIteratorState(), FArchiveReferenceMarker::FArchiveReferenceMarker(), FCanvasTriangleItem::FCanvasTriangleItem(), FLandscapeGrassWeightExporter_RenderThread::FComponentInfo::FComponentInfo(), UE::PixelStreaming2::FEpicRtcBoolArray::FEpicRtcBoolArray(), UE::PixelStreaming2::FEpicRtcCodecBufferUsageArray::FEpicRtcCodecBufferUsageArray(), UE::PixelStreaming2::FEpicRtcDecodeTargetIndicationArray::FEpicRtcDecodeTargetIndicationArray(), UE::PixelStreaming2::FEpicRtcVideoResolutionArray::FEpicRtcVideoResolutionArray(), FSimpleLinkNavModifier::FSimpleLinkNavModifier(), FSimpleLinkNavModifier::FSimpleLinkNavModifier(), TComponentInterfaceIterator< T >::TComponentInterfaceIterator(), TFindObjectReferencers< T >::TFindObjectReferencers(), TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >< 32 >::TMemoryWriterBase(), UE::Geometry::TPolygon2< double >::TPolygon2(), FRenderThreadScope::~FRenderThreadScope(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add(), UE::Geometry::TConstrainedDelaunay2< float >::Add(), UE::Geometry::TDynamicVector< Type, BlockSize >::Add(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElementToNode(), FSlateRenderBatch::AddIndices(), FEnvQueryInstance::AddItemData(), FReferenceCollector::AROPrivate::AddReferencedObjects(), FReferenceCollector::AROPrivate::AddReferencedObjects(), Audio::FTabularRenderHelper::AddRow(), FScopedWidgetSlotArguments< FNodeSlot >::AddSlots(), FSlateRenderBatch::AddVertices(), TRangeAllocator< FAllocatorModifier >::Alloc(), TActorDescContainerCollection< ActorDescContPtrType >::Append(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::Append(), UE::Geometry::TPolyline< T, 2 >< double >::AppendVertices(), FGroupEraseBrushOp::ApplyStampByTriangles(), FGroupPaintBrushOp::ApplyStampByTriangles(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexColorSoftenBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), Nanite::FNaniteResourcesHelper::AuditMaterials(), TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), RangedForIteratorType< FAnimNextTraitEventPtr >::BulkSerialize(), FInstancedSkinnedMeshComponentHelper::CalcBounds(), FCSPose< PoseType >::CalculateComponentSpaceTransform(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForDiffNodes(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForMatchingValues(), UE::Geometry::TPolygon2< double >::Chamfer(), FDisplayClusterShaderParameters_ICVFX::CleanupCamerasForRender(), UE::Geometry::FMeshFaceSelection::ClipFins(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), TEvaluationTreeEntryContainer< ElementType >::Compact(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), CompareUnsortedArrays(), CompareValueArraysByExpressionGUID(), FOodleCompressedArray::CompressTArray(), UE::Geometry::FClusterKMeans::ComputeClusters(), FastTriWinding::ComputeCoeffs(), ConvexHull2D::ComputeConvexHullLegacy(), UE::Geometry::FImageOccupancyMap::ComputeGutterTexelsFromGutterSamples(), UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill(), UE::MeshDeformation::ComputeNumMatrixElements(), UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToMaxDistance(), FSkeletalMeshStreamOut::ConditionalMarkComponentsDirty(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), ContainsObjectOfClass(), FMediaIOAudioOutput::ConvertAndUpmixBuffer(), UE::LWC::ConvertArrayType(), UE::LWC::ConvertArrayTypeClampMax(), SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector(), FBaseCompactPose< InAllocator >::CopyBonesFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), TChunkedArray< TUniquePtr< DescType > >::CopyToLinearArray(), UE::AnimNext::FLODPose::CopyTransformsFrom(), UE::AnimNext::FLODPose::CopyTransformsTo(), UE::Geometry::TMeshTangents< RealType >::CopyTriVertexTangents(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), BufferUtil::CountValid(), SSegmentedControl< OptionType >::Create(), CreateByteAddressBuffer(), CreateByteAddressUploadBuffer(), FWaterMeshIndexBuffer::CreateIndexBuffer(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CreatePooledResource(), CreateStructuredBuffer(), CreateStructuredBuffer(), CreateStructuredUploadBuffer(), DECLARE_MULTICAST_DELEGATE_OneParam(), FMaterial::DeferredDeleteArray(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Dispatch_PerEntity(), FKelvinletBrushOp::DisplaceKelvinlet(), UE::Geometry::FDisplaceMesh::DisplaceMeshWithVertexWeights(), SAnimAttributeView::DisplayNewAttributeContainerSnapshots(), DoActionToAllPackages(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::DumpStats(), ITypedElementWorldInterface::DuplicateElement(), RangedForIteratorType< FAnimNextTraitEventPtr >::end(), RangedForIteratorType< FAnimNextTraitEventPtr >::end(), UE::Geometry::FVertexConnectedComponents::EnumerateContiguousComponentsFromArray(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled(), TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByStartTime(), FBaseGraphTask::Execute(), UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_Helper(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), UE::Geometry::FMeshFaceSelection::FillEars(), BufferUtil::FilterInPlace(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindLastByPredicate(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd(), DisplayClusterTypesConverter::FromHexString(), DisplayClusterTypesConverter::FromString(), UE::Geometry::FMarchingCubes::generate_continuation(), UE::Geometry::FMarchingCubes::generate_continuation_parallel(), UE::Geometry::TImplicitBlend< TriangleMeshType >::GenerateBlendAnalytic(), UE::Math::TVector< T >::GenerateClusterCenters(), FBlueprintEditorUtils::GetAllNodesOfClass(), GetAllPhysicsObjectsById(), FCompressibleAnimData::GetApproxRawDataArraySize(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), UE::Geometry::GetArrayMesh(), FMovieSceneChannelProxy::GetChannels(), FInstancedSkinnedMeshComponentHelper::GetComponentDesc(), FAssetData::GetFirstAssetDataOfClass(), FObjectThumbnail::GetImage(), TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::GetKeys(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys(), FMeshComponentHelper::GetMaterialSlotsOverlayMaterial(), TSkeletalMeshVertexData< VertexDataType >::GetNumVertices(), FPoly::GetOutsideWindings(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), UE::Geometry::GetShape(), FObjectEditorUtils::GetTypedWeakObjectPtrs(), UE::Geometry::FClusterKMeans::GetUniformSpacedInitialCenters(), FStaticMeshComponentHelper::GetUsedMaterials(), SGraphPinVector4< NumericType >::GetValue(), SGraphPinVector4Slider< NumericType >::GetValue(), SGraphPinVector< NumericType >::GetValue(), SGraphPinVectorSlider< NumericType >::GetValue(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPopDiscard(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), TRange< float >::Hull(), FLevelDragDropOp::Init(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::Init(), UE::ChaosDeformable::FHalfArrayBufferWithSRV::Init(), UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init(), UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init(), FColorVertexBuffer::InitFromColorArray(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::Initialize(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), StringConv::InlineCombineSurrogates_Array(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), UE::Geometry::FArrangement2d::insert_segment(), UE::Geometry::FDynamicMeshOctree3::InsertTriangles(), FKelvinletBrushOp::IntegrateKelvinlet(), TRange< float >::Intersection(), Algo::KahnTopologicalSort(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), TAllocPlaybackLog< FModifier, FAllocOp >::Load(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FCSPose< PoseType >::LocalBlendCSBoneTransforms(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), MakeConstMeshBuildVertexView(), MakeMeshBuildVertexView(), MakeMeshBuildVertexView(), MakeStaticMeshVertex(), MovieSceneToolHelpers::MergeChannels(), MovieSceneToolHelpers::MergeSections(), MovieSceneToolHelpers::MergeValue(), UE::Geometry::TMeshQueries< TriangleMeshType >::MeshDistanceStatistics(), FExportTextDragDropOp::New(), UE::Core::Private::TAdderReserverVTableImpl< SizeType, ContainerType >::Num(), SComboBox< OptionType >::OnButtonClicked(), SRigVMActionMenu::OnGetActionList(), SComboBox< OptionType >::OnKeyDown(), SComboBox< OptionType >::OnKeyDownHandler(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &(), TActorIteratorBase< FActorIterator >::operator++(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator+=(), operator<<(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator==(), AWorldDataLayers::OverwriteDataLayerRuntimeStates(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), FAllocOpBase::ParseValueStrings(), FOodleCompressedArray::PeekSizes(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), STreeView< FRigVMSearchResult >::PopulatePinnedItems(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PreLockComponentHeaders(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs(), FComponentEditorUtils::PropagateDefaultValueChange(), UE::MovieScene::FSystemInterrogator::QueryPropertyValues(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), RangedForIteratorType< FAnimNextTraitEventPtr >::rbegin(), RangedForIteratorType< FAnimNextTraitEventPtr >::rbegin(), SListView< TSharedPtr< FString > >::ReGeneratePinnedItems(), TInteractiveToolCommands< CommandContextType >::RegisterCommands(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Remove(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAllSwap(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement(), UE::Geometry::FMeshRegionOperator::RepairPossibleNonManifoldEdges(), FLandscapeConfigHelper::ResampleData(), TNetworkPredictionBuffer< ElementType, SingleElement >::Resize(), TNetworkSimAuxBuffer< ElementType >::Resize(), TSkeletalMeshVertexData< VertexDataType >::ResizeBuffer(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::scatter_tris(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV(), FLiveLinkProvider::SendMessage(), FLiveLinkProvider::SendMessage(), FDynamicEmitterReplayDataBase::Serialize(), FHeightmapAccessor< bInUseInterp >::SetData(), TAttributeArrayContainer< AttributeType >::SetElementSize(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNum(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUnsafeInternal(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumZeroed(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetValue(), UE::Geometry::TPolyline< T, 2 >< double >::SetVertices(), Nanite::FPackedCluster::SetVertResourceBatchInfo(), SAnimAttributeView::ShouldInvalidateListViewCache(), FLandscapeEditDataInterface::ShrinkData(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::SplitTriSetMidpoint(), FAnimNodeTracker::Top(), Verse::FNativeConverter::ToVValue(), UE::Geometry::FDelaunay2::Triangulate(), SRigVMActionMenu::TryInsertPromoteToVariable(), UE_DEPRECATED(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs(), MaterialInstance_Private::UpdateParameterSet_FullTraversal(), MaterialInstance_Private::UpdateParameterSet_WithCachedData(), FMeshRenderBufferSet::UpdateRaytracingGeometryIfEnabled(), TIndexedValuesChangeBuilder< ValueType, ChangeClassType >::UpdateValues(), FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), FClassTree::Validate(), VerifyLayout(), FKismetVariableDragDropAction::WillBreakLinks(), WriteCustomReport(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
NumBytes()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE SIZE_T TArray< InElementType, InAllocatorType >::NumBytes () const inline nodiscard
Returns
Number of bytes used, excluding slack
Definition at line 1122 of file Array.h.
Referenced by FTransactionallySafeArchiveWriter::DoDeferredWrites(), and UE::Net::TStructNetTokenDataStoreHelper< T >::GetStateFromReplayExportGroup().
operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &()
template<typename InElementType, typename InAllocatorType> template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)> TArray< InElementType, InAllocatorType >::operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & () const inline nodiscard
Immutable implicit conversion operator to constant container of compatible element type.
Definition at line 2852 of file Array.h.
operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > &()
template<typename InElementType, typename InAllocatorType> template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)> TArray< InElementType, InAllocatorType >::operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & () inline nodiscard
Mutable implicit conversion operator to container of compatible element type.
Definition at line 2839 of file Array.h.
operator!=()
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE bool TArray< InElementType, InAllocatorType >::operator!= (const TArray< InElementType, InAllocatorType > & OtherArray) const inline nodiscard
Inequality operator.
Parameters
OtherArray Array to compare.
Returns
True if this array is NOT the same as OtherArray. False otherwise.
Definition at line 1570 of file Array.h.
operator+=() [1/3]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TArray & TArray< InElementType, InAllocatorType >::operator+= (const TArray< InElementType, InAllocatorType > & Other) inline
Appends the specified array to this array.
Cannot append to self.
Parameters
Other The array to append.
Definition at line 2547 of file Array.h.
operator+=() [2/3]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TArray & TArray< InElementType, InAllocatorType >::operator+= (std::initializer_list< ElementType > InitList) inline
Appends the specified initializer list to this array.
Parameters
InitList The initializer list to append.
Definition at line 2558 of file Array.h.
operator+=() [3/3]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG TArray & TArray< InElementType, InAllocatorType >::operator+= (TArray< InElementType, InAllocatorType > && Other) inline
Appends the specified array to this array.
Cannot append to self.
Move semantics version.
Parameters
Other The array to append.
Definition at line 2535 of file Array.h.
operator=() [1/8]
template<typename InElementType, typename InAllocatorType> TArray & TArray< InElementType, InAllocatorType >::operator= (const TArray< InElementType, InAllocatorType > & Other) inline
Assignment operator.
First deletes all currently contained elements and then copies from other array.
Parameters
Other The source array to assign from.
Definition at line 791 of file Array.h.
operator=() [2/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocatorType> TArray & TArray< InElementType, InAllocatorType >::operator= (const TArray< ElementType, OtherAllocatorType > & Other) inline
Assignment operator.
First deletes all currently contained elements and then copies from other array.
AllocatorType changing version.
Parameters
Other The source array to assign from.
Definition at line 778 of file Array.h.
operator=() [3/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> TArray & TArray< InElementType, InAllocatorType >::operator= (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > & Other) inline
Assignment operator.
First deletes all currently contained elements and then copies from other array. Compatible element type version.
Parameters
Other The source array to assign from.
Definition at line 2889 of file Array.h.
operator=() [4/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> TArray & TArray< InElementType, InAllocatorType >::operator= (const TArrayView< OtherElementType, OtherSizeType > & Other)
operator=() [5/8]
template<typename InElementType, typename InAllocatorType> template<typename OtherElementType, typename OtherSizeType> FORCEINLINE TArray< InElementType, InAllocatorType > & TArray< InElementType, InAllocatorType >::operator= (const TArrayView< OtherElementType, OtherSizeType > & Other)
Definition at line 980 of file ArrayView.h.
operator=() [6/8]
template<typename InElementType, typename InAllocatorType> TArray & TArray< InElementType, InAllocatorType >::operator= (std::initializer_list< InElementType > InitList) inline
Initializer list assignment operator.
First deletes all currently contained elements and then copies from initializer list.
Parameters
InitList The initializer_list to copy from.
Definition at line 759 of file Array.h.
Referenced by UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator=(), and UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator=().
operator=() [7/8]
template<typename InElementType, typename InAllocatorType> TArray & TArray< InElementType, InAllocatorType >::operator= (TArray< InElementType, InAllocatorType > && Other) inline
Move assignment operator.
Parameters
Other Array to assign and move from.
Definition at line 955 of file Array.h.
operator=() [8/8]
template<typename InElementType, typename InAllocatorType> template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> TArray & TArray< InElementType, InAllocatorType >::operator= (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, AllocatorType > && Other) inline
Move assignment operator.
Compatible element type version.
Parameters
Other Array to assign and move from.
Definition at line 2869 of file Array.h.
operator==() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG bool TArray< InElementType, InAllocatorType >::operator== (const TArray< InElementType, InAllocatorType > & OtherArray) const inline nodiscard
Equality operator.
Parameters
OtherArray Array to compare.
Returns
True if this array is the same as OtherArray. False otherwise.
Definition at line 1556 of file Array.h.
operator==() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG bool TArray< InElementType, InAllocatorType >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 986 of file Array.h.
operator[]() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE const ElementType & TArray< InElementType, InAllocatorType >::operator[] (SizeType Index) const inline nodiscard
Array bracket operator.
Returns reference to element at given index.
Const version of the above.
Returns
Reference to indexed element.
Definition at line 1156 of file Array.h.
operator[]() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::operator[] (SizeType Index) inline nodiscard
Array bracket operator.
Returns reference to element at given index.
Returns
Reference to indexed element.
Definition at line 1143 of file Array.h.
Referenced by UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator[](), UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator[](), UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator[](), and UE::Anim::TTypedIndexRange< IndexType, TArray< TArrayArgs... > >::operator[]().
Pop()
template<typename InElementType, typename InAllocatorType> ElementType TArray< InElementType, InAllocatorType >::Pop (EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Pops element from the array.
Parameters
AllowShrinking If this call allows shrinking of the array during element remove.
Returns
Popped element.
Definition at line 1168 of file Array.h.
Referenced by FCSPose< PoseType >::CalculateComponentSpaceTransform(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::Geometry::FDynamicMeshOctree3::CollectTriangles(), TResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CreatePooledResource(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), FAnimNodeTracker::Pop(), FAnimNodeTracker::Pop(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV(), and RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
Push() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::Push (const ElementType & Item) inline
Pushes element into the array.
Const ref version of the above.
Parameters
Item Item to push.
See also
Pop, Top
Definition at line 1209 of file Array.h.
Push() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE void TArray< InElementType, InAllocatorType >::Push (ElementType && Item) inline
Pushes element into the array.
Parameters
Item Item to push.
Definition at line 1196 of file Array.h.
Referenced by FAnimNodeTracker::CopyTopsOnly(), FAnimNodeTracker::Push(), and Verse::FNativeConverter::ToVValue().
RangeCheck() [1/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::RangeCheck (SizeType Index) const inline
Checks if index is in array range.
Parameters
Index Index to check.
Definition at line 1060 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Last(), RangedForIteratorType< FAnimNextTraitEventPtr >::Last(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator[](), RangedForIteratorType< FAnimNextTraitEventPtr >::operator[](), RangedForIteratorType< FAnimNextTraitEventPtr >::Pop(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap(), and RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap().
RangeCheck() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::RangeCheck (SizeType Index, SizeType Count) const inline
Checks if a range of indices are in the array range.
Parameters
Index Index of the start of the range to check.
Count Number of elements in the range.
Definition at line 1077 of file Array.h.
rbegin() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForReverseIteratorType TArray< InElementType, InAllocatorType >::rbegin () inline nodiscard
Definition at line 3400 of file Array.h.
rbegin() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType TArray< InElementType, InAllocatorType >::rbegin () const inline nodiscard
Definition at line 3401 of file Array.h.
Remove()
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::Remove (const ElementType & Item) inline
Removes as many instances of Item as there are in the array, maintaining order but not indices.
Parameters
Item Item to remove from array.
Returns
Number of removed elements.
See also
Add, Insert, RemoveAll, RemoveAllSwap, RemoveSingle, RemoveSwap
Definition at line 3101 of file Array.h.
RemoveAll()
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> SizeType TArray< InElementType, InAllocatorType >::RemoveAll (const PREDICATE_CLASS & Predicate) inline
Remove all instances that match the predicate, maintaining order but not indices Optimized to work with runs of matches/non-matches.
Parameters
Predicate Predicate class instance
Returns
Number of removed elements.
See also
Add, Insert, RemoveAllSwap, RemoveSingle, RemoveSwap
Definition at line 3118 of file Array.h.
Referenced by UE::SequenceNavigator::INavigationToolItem::FindValidChildren(), FStaticMeshComponentHelper::GetUsedRayTracingOnlyMaterials(), and RangedForIteratorType< FAnimNextTraitEventPtr >::Remove().
RemoveAllSwap()
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> SizeType TArray< InElementType, InAllocatorType >::RemoveAllSwap (const PREDICATE_CLASS & Predicate, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Remove all instances that match the predicate.
Parameters
Predicate Predicate class instance
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
See also
Remove, RemoveSingle, RemoveSingleSwap, RemoveSwap
Definition at line 3172 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
RemoveAt() [1/2]
template<typename InElementType, typename InAllocatorType> template<typename CountType UE_REQUIRES> FORCEINLINE void TArray< InElementType, InAllocatorType >::RemoveAt (SizeType Index, CountType Count, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element (or elements) at given location, optionally shrinking the array.
Parameters
Index Location in array of the element to remove.
Count (Optional) Number of elements to remove. Default is 1.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 2118 of file Array.h.
RemoveAt() [2/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::RemoveAt (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element (or elements) at given location, then shrinks the array.
Parameters
Index Location in array of the element to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 2090 of file Array.h.
Referenced by UE::Anim::FCurveUtils::Filter(), UE::Geometry::FMarchingCubes::generate_continuation(), FPoly::GetOutsideWindings(), UE::Anim::FNamedValueArrayUtils::RemoveByPredicate(), TSkeletalMeshVertexData< VertexDataType >::ResizeBuffer(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNum(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumZeroed(), FLandscapeEditDataInterface::ShrinkData(), and FTickableObjectRenderThread::Unregister().
RemoveAtImpl() [1/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::RemoveAtImpl (SizeType Index) inline private
Definition at line 2048 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Pop(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt(), and RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt().
RemoveAtImpl() [2/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::RemoveAtImpl (SizeType Index, SizeType Count) inline private
Definition at line 2065 of file Array.h.
RemoveAtSwap() [1/2]
template<typename InElementType, typename InAllocatorType> template<typename CountType UE_REQUIRES> FORCEINLINE void TArray< InElementType, InAllocatorType >::RemoveAtSwap (SizeType Index, CountType Count, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element (or elements) at given location, optionally shrinking the array.
This version is much more efficient than RemoveAt (O(Count) instead of O(ArrayNum)), but does not preserve the order.
Parameters
Index Location in array of the element to remove.
Count (Optional) Number of elements to remove. Default is 1.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 2227 of file Array.h.
RemoveAtSwap() [2/2]
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes an element (or elements) at given location, then shrinks the array.
This version is much more efficient than RemoveAt (O(Count) instead of O(ArrayNum)), but does not preserve the order.
Parameters
Index Location in array of the element to remove.
AllowShrinking (Optional) Tells if this call can shrink array if suitable after remove. Default is yes.
Definition at line 2195 of file Array.h.
Referenced by FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), UE::Geometry::FClusterKMeans::ComputeClusters(), UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_Helper(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPopDiscard(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Remove(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAllSwap(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSingleSwap(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSwap(), FAsyncAddPrimitiveQueue::Tick(), and RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
RemoveAtSwapImpl() [1/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::RemoveAtSwapImpl (SizeType Index) inline private
Definition at line 2145 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap(), and RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap().
RemoveAtSwapImpl() [2/2]
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::RemoveAtSwapImpl (SizeType Index, SizeType Count) inline private
Definition at line 2164 of file Array.h.
RemoveSingle()
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::RemoveSingle (const ElementType & Item) inline
Removes the first occurrence of the specified item in the array, maintaining order but not indices.
Parameters
Item The item to remove.
Returns
The number of items removed. For RemoveSingleItem, this is always either 0 or 1.
See also
Add, Insert, Remove, RemoveAll, RemoveAllSwap
Definition at line 3070 of file Array.h.
RemoveSingleSwap()
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::RemoveSingleSwap (const ElementType & Item, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the first occurrence of the specified item in the array.
This version is much more efficient O(Count) instead of O(ArrayNum), but does not preserve the order
Parameters
Item The item to remove
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Returns
The number of items removed. For RemoveSingleItem, this is always either 0 or 1.
See also
Add, Insert, Remove, RemoveAll, RemoveAllSwap, RemoveSwap
Definition at line 3219 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
RemoveSwap()
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::RemoveSwap (const ElementType & Item, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes all instances of a given item from the array.
This version is much more efficient, because it uses RemoveAtSwap internally which is O(Count) instead of RemoveAt which is O(ArrayNum), but does not preserve the order.
Parameters
Item The item to remove
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Returns
Number of elements removed.
See also
Add, Insert, Remove, RemoveAll, RemoveAllSwap
Definition at line 3251 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
rend() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForReverseIteratorType TArray< InElementType, InAllocatorType >::rend () inline nodiscard
Definition at line 3402 of file Array.h.
rend() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType TArray< InElementType, InAllocatorType >::rend () const inline nodiscard
Definition at line 3403 of file Array.h.
Reserve()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::Reserve (SizeType Number) inline
Reserves memory such that the array can contain at least Number elements.
Parameters
Number The number of elements that the array should be able to contain after allocation.
See also
Shrink
Definition at line 3026 of file Array.h.
Referenced by FActorIteratorState::FActorIteratorState(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::AddPage(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::ApplyOffset(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FMeshRegionOperator::BackPropropagate(), UE::Geometry::FSegmentTree3::Build(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), FCSPose< PoseType >::CalculateComponentSpaceTransform(), UE::Geometry::CurveUtil::ClipConvexToBounds(), UE::Geometry::FClusterKMeans::ComputeClusters(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), FWaterMeshIndexBuffer::CreateIndexBuffer(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), TPerlinNoiseChannelInterface< ChannelContainerType >::DrawExtra_Raw(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), FText::FormatOrdered(), DisplayClusterTypesConverter::FromString(), UE::Geometry::TImplicitBlend< TriangleMeshType >::GenerateBlendAnalytic(), GetAllPhysicsObjectsById(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::GetEnumDataTypeInterface(), TQuadTree< ElementType, NodeCapacity >::GetIntersectingElements(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), FRigVMGraphEnumDetailCustomization::GetMemoryBeingCustomized(), ObjectElementDataUtil::GetObjectsFromHandles(), ObjectElementDataUtil::GetObjectsFromHandlesChecked(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::GetOccupiedBlockIDs(), FReferenceSkeleton::GetRawRefBoneNames(), SMInstanceElementDataUtil::GetSMInstancesFromHandles(), SMInstanceElementDataUtil::GetSMInstancesFromHandlesChecked(), UE::Tasks::Private::FTaskHandle::GetTraceIds, FArrangedChildren::Hittest2_FromArray(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), Algo::KahnTopologicalSort(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), MakeConstMeshBuildVertexView(), MakeMeshBuildVertexView(), RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopyWithSlack(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::RemoveElement(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement(), TSkeletalMeshVertexData< VertexDataType >::ResizeBuffer(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges(), Verse::FNativeConverter::ToVValue(), UE::Geometry::FDelaunay2::Triangulate(), UE::SoftObjectPath::Private::UE_DEPRECATED(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Reset()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::Reset (SizeType NewSize = 0) inline
Same as empty, but doesn't change memory allocations, unless the new size is larger than the current array.
It calls the destructors on held items if needed and then zeros the ArrayNum.
Parameters
NewSize The expected usage size after calling this function.
Definition at line 2259 of file Array.h.
Referenced by TComponentInterfaceIterator< T >::TComponentInterfaceIterator(), TFindObjectReferencers< T >::TFindObjectReferencers(), UE::Geometry::CurveUtil::ClipConvexToBounds(), UE::Geometry::CurveUtil::ClipConvexToPlane(), UE::Geometry::FSizedDisjointSet::CompactedGroupIndexToGroupID(), UE::Geometry::FClusterKMeans::ComputeClusters(), ConvexHull2D::ComputeConvexHullLegacy(), TextureLayoutTools::ComputeDifferenceArray(), UE::Geometry::FMeshEdgeSelection::ContractByBorderEdges(), UE::Geometry::FMeshVertexSelection::ContractByBorderVertices(), UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), FTransactionallySafeArchiveWriter::DoDeferredWrites(), UE::Geometry::FMeshEdgeSelection::ExpandToOneRingNeighbors_Helper(), UE::Anim::FCurveUtils::Filter(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FindPathToNearestSeed(), UE::Geometry::TMeshDijkstra< PointSetType >::FindPathToNearestSeed(), FLayoutExtender::FindStackExtensions(), FLayoutExtender::FindTabExtensions(), FSoundWaveLoadingBehaviorUtil::GetChainOfClassesForLoadingBehaviorInheritance(), FMeshDescription::GetEdgeConnectedPolygons(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys(), FMeshDescription::GetPolygonAdjacentPolygons(), FMeshDescription::GetPolygonInternalEdges(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), FRigVMGraphMathTypeDetailCustomization::GetPropertyChain(), FMeshDescription::GetTriangleAdjacentTriangles(), UE::Geometry::FClusterKMeans::GetUniformSpacedInitialCenters(), FMeshDescription::GetVertexConnectedPolygons(), FMeshDescription::GetVertexConnectedTriangles(), FMeshDescription::GetVertexInstanceConnectedPolygons(), LoadFromCompactBinary(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), MovieSceneToolHelpers::MergeChannels(), ParallelForWithPreWorkWithTaskContext(), ParallelForWithPreWorkWithTaskContext(), ParallelForWithTaskContext(), ParallelForWithTaskContext(), ParallelForWithTaskContext(), ParallelForWithTaskContext(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs(), UE::Geometry::FSparseDynamicPointOctree3::RangeQuery(), TSlotlessChildren< ChildType >::Reset(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), UCLASS(), UE::Anim::FNamedValueArrayUtils::Union(), USTRUCT(), and USTRUCT().
SetNum()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::SetNum (SizeType NewNum, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Resizes array to given number of elements.
Parameters
NewNum New size of the array.
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Definition at line 2320 of file Array.h.
Referenced by UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::FEpicRtcFrameDependencyStructure(), UE::Geometry::TConstrainedDelaunay2< float >::Add(), UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), UE::Geometry::FMeshRegionOperator::BackPropropagate(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForDiffNodes(), TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForMatchingValues(), UE::Geometry::FMeshOffsetBaseOp::CalculateResult(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_tri_bboxes(), ConvexHull2D::ComputeConvexHull(), UE::Geometry::FImageOccupancyMap::ComputeGutterTexelsFromGutterSamples(), UE::Geometry::FVerticalCylinderGeneratorBase::ComputeSegLengths(), UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToMaxDistance(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), FMediaIOAudioOutput::ConvertAndUpmixBuffer(), TNetRewindHistory< DataType >::DebugData(), DECLARE_MULTICAST_DELEGATE_OneParam(), FOodleCompressedArray::DecompressToTArray(), FBaseKelvinletBrushOp::DisplaceKelvinlet(), FKelvinletBrushOp::DisplaceKelvinlet(), UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), UE::Geometry::FGeneralizedCylinderGenerator::Generate(), UE::Geometry::FGridBoxMeshGenerator::Generate(), UE::Geometry::FVerticalCylinderGeneratorBase::GenerateVerticalCircleSweep(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::GetValue(), StringConv::InlineCombineSurrogates_Array(), FBaseKelvinletBrushOp::IntegrateKelvinlet(), FKelvinletBrushOp::IntegrateKelvinlet(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Geometry::FVertexConnectedComponents::MakeContiguousComponentsArray(), UE::Geometry::TGaussian2< float >::MakeKernelFromWidth(), operator<<(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FImageOccupancyMap::ParallelProcessingPass(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::MovieScene::FSystemInterrogator::QueryPropertyValues(), UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel(), UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize(), TAttributeArrayContainer< AttributeType >::SetElementSize(), TAttributeArrayContainer< AttributeType >::SetNum(), UE::Geometry::TPolygon2< double >::SimplifyDouglasPeucker(), UE::Geometry::TPolyline< T, 2 >< double >::SimplifyDouglasPeucker(), UE::Geometry::TPolyline< T, 2 >< double >::SmoothSubdivide(), and FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays().
SetNumUninitialized()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::SetNumUninitialized (SizeType NewNum, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Resizes array to given number of elements.
New elements will be uninitialized.
Parameters
NewNum New size of the array.
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Definition at line 2379 of file Array.h.
Referenced by UE::Anim::FCurveUtils::BuildUnsorted(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactCopy(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::CompactInPlace(), UE::Geometry::FClusterKMeans::ComputeClusters(), ConvexHull2D::ComputeConvexHull(), UE::MeshDeformation::ComputeNumMatrixElements(), UE::MeshDeformation::ConstructTriangleDataArray(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructValenceWeightedLaplacian(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), UE::Geometry::FArrowGenerator::Generate(), FMeshDescription::GetPolygonPerimeterEdges(), FMeshDescription::GetPolygonVertexInstances(), FMeshDescription::GetPolygonVertices(), FMeshDescription::GetVertexAdjacentVertices(), FCSPose< PoseType >::LocalBlendCSBoneTransforms(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::TPolygon2< double >::PolyOffset(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), UE::Geometry::TPolygon2< double >::Simplify(), RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED(), and UE::Geometry::TPolygon2< double >::VtxNormalOffset().
SetNumUnsafeInternal()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::SetNumUnsafeInternal (SizeType NewNum) inline
Does nothing except setting the new number of elements in the array.
Does not destruct items, does not de-allocate memory.
Parameters
NewNum New number of elements in the array, must be <= the current number of elements in the array.
Definition at line 2405 of file Array.h.
SetNumZeroed()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::SetNumZeroed (SizeType NewNum, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Resizes array to given number of elements, optionally shrinking it.
New elements will be zeroed.
Parameters
NewNum New size of the array.
AllowShrinking Tell if this function can shrink the memory in-use if suitable.
Definition at line 2351 of file Array.h.
Referenced by UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), FMediaIOAudioOutput::ConvertAndUpmixBuffer(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyUnfrozen(), UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestCoverage(), RangedForIteratorType< FAnimNextTraitEventPtr >::UE_ALLOWSHRINKING_BOOL_DEPRECATED(), UE::Geometry::TMeshQueries< TriangleMeshType >::VertexToSurfaceDistances(), and UE::Geometry::TMeshQueries< TriangleMeshType >::VertexToSurfaceDistancesSerial().
Shrink()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::Shrink () inline
Shrinks the array's used memory to smallest possible to store elements currently in it.
See also
Slack
Definition at line 1269 of file Array.h.
Referenced by TEvaluationTreeEntryContainer< ElementType >::Compact().
SlackTrackerNumChanged()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::SlackTrackerNumChanged () inline private
Definition at line 806 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmpty(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmptyWithSlack(), RangedForIteratorType< FAnimNextTraitEventPtr >::Empty(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAll(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSingle(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reset(), and RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUnsafeInternal().
Sort() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::Sort () inline
Sorts the array assuming < operator is defined for the item type.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your array will be sorted by the values being pointed to, rather than the pointers' values. If this is not desirable, please use Algo::Sort(MyArray) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3425 of file Array.h.
Referenced by FMovieSceneAdditiveCameraTrackBlender::Blend(), UE::Anim::FCurveUtils::BuildUnsorted(), CompareUnsortedArrays(), CompareValueArraysByExpressionGUID(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTrianglesImpl(), UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), and UE::Geometry::FArrangement2d::insert_segment().
Sort() [2/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> UE_NODEBUG void TArray< InElementType, InAllocatorType >::Sort (const PREDICATE_CLASS & Predicate) inline
Sorts the array using user define predicate class.
Parameters
Predicate Predicate class instance.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your predicate will be passed references rather than pointers. If this is not desirable, please use Algo::Sort(MyArray, Predicate) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3441 of file Array.h.
StableSort() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG void TArray< InElementType, InAllocatorType >::StableSort () inline
Stable sorts the array assuming < operator is defined for the item type.
Stable sort is slower than non-stable algorithm.
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your array will be sorted by the values being pointed to, rather than the pointers' values. If this is not desirable, please use Algo::StableSort(MyArray) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3457 of file Array.h.
StableSort() [2/2]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> UE_NODEBUG void TArray< InElementType, InAllocatorType >::StableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the array using user defined predicate class.
Stable sort is slower than non-stable algorithm.
Parameters
Predicate Predicate class instance
Note
: If your array contains raw pointers, they will be automatically dereferenced during sorting. Therefore, your predicate will be passed references rather than pointers. If this is not desirable, please use Algo::StableSort(MyArray, Predicate) directly instead. The auto-dereferencing behavior does not occur with smart pointers.
Definition at line 3475 of file Array.h.
Swap()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap) inline
Element-wise array element swap.
This version is doing more sanity checks than SwapMemory.
Parameters
FirstIndexToSwap Position of the first element to swap.
SecondIndexToSwap Position of the second element to swap.
Definition at line 3307 of file Array.h.
SwapMemory()
template<typename InElementType, typename InAllocatorType> FORCEINLINE void TArray< InElementType, InAllocatorType >::SwapMemory (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap) inline
Element-wise array memory swap.
Parameters
FirstIndexToSwap Position of the first element to swap.
SecondIndexToSwap Position of the second element to swap.
Definition at line 3291 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Swap().
Top() [1/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE const ElementType & TArray< InElementType, InAllocatorType >::Top () const inline nodiscard
Returns the top element, i.e.
the last one.
Const version of the above.
Returns
Reference to the top element.
See also
Pop, Push
Definition at line 1233 of file Array.h.
Top() [2/2]
template<typename InElementType, typename InAllocatorType> UE_NODEBUG FORCEINLINE ElementType & TArray< InElementType, InAllocatorType >::Top () inline nodiscard
Returns the top element, i.e.
the last one.
Returns
Reference to the top element.
See also
Pop, Push
Definition at line 1220 of file Array.h.
Referenced by FAnimNodeTracker::Top().
ToString()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::ToString (const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext) const inline
Definition at line 3625 of file Array.h.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/15]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [3/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") inline
Definition at line 3839 of file Array.h.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [4/15]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [5/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [6/15]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [7/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") inline
Definition at line 1185 of file Array.h.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [8/15]
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAllSwap") const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [9/15]
template<typename InElementType, typename InAllocatorType> template<typename CountType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [10/15]
template<typename InElementType, typename InAllocatorType> template<typename CountType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [11/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [12/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSwap") const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [13/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [14/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [15/15]
template<typename InElementType, typename InAllocatorType> TArray< InElementType, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumZeroed")
VerifyHeap()
template<typename InElementType, typename InAllocatorType> template<class PREDICATE_CLASS> UE_NODEBUG void TArray< InElementType, InAllocatorType >::VerifyHeap (const PREDICATE_CLASS & Predicate) inline
Verifies the heap.
Parameters
Predicate Predicate class instance.
Definition at line 3796 of file Array.h.
WriteMemoryImage()
template<typename InElementType, typename InAllocatorType> void TArray< InElementType, InAllocatorType >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 3586 of file Array.h.
Friends And Related Symbol Documentation
TArray
template<typename InElementType, typename InAllocatorType> template<typename OtherInElementType, typename OtherAllocator> friend class TArray friend
Definition at line 654 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::CopyUnfrozen(), TSkeletalMeshVertexData< VertexDataType >::operator=(), and RangedForIteratorType< FAnimNextTraitEventPtr >::WriteMemoryImage().
TArrayPrivateFriend
template<typename InElementType, typename InAllocatorType> friend struct TArrayPrivateFriend friend
Definition at line 3954 of file Array.h.
TIndirectArray
template<typename InElementType, typename InAllocatorType> template<typename ElementType, typename AllocatorType> friend class TIndirectArray friend
Definition at line 3579 of file Array.h.
Field Documentation
AllocatorInstance
template<typename InElementType, typename InAllocatorType> ElementAllocatorType TArray< InElementType, InAllocatorType >::AllocatorInstance protected
Definition at line 3581 of file Array.h.
ArrayMax
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::ArrayMax protected
Definition at line 3583 of file Array.h.
ArrayNum
template<typename InElementType, typename InAllocatorType> SizeType TArray< InElementType, InAllocatorType >::ArrayNum protected
Definition at line 3582 of file Array.h.
bAllowShrinking [1/3]
template<typename InElementType, typename InAllocatorType> bool TArray< InElementType, InAllocatorType >::bAllowShrinking
Initial value:
{
        RemoveAt(Index, Count, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 2139 of file Array.h.
bAllowShrinking [2/3]
template<typename InElementType, typename InAllocatorType> bool TArray< InElementType, InAllocatorType >::bAllowShrinking
Initial value:
{
        SetNum(NewNum, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 2339 of file Array.h.
bAllowShrinking [3/3]
template<typename InElementType, typename InAllocatorType> const PREDICATE_CLASS bool TArray< InElementType, InAllocatorType >::bAllowShrinking
Initial value:
{
        HeapPop(OutItem, Predicate, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 3764 of file Array.h.
bHasIntrusiveUnsetOptionalState
template<typename InElementType, typename InAllocatorType> bool TArray< InElementType, InAllocatorType >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 977 of file Array.h.
Count
template<typename InElementType, typename InAllocatorType> CountType TArray< InElementType, InAllocatorType >::Count
Definition at line 2139 of file Array.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::FindLastByPredicate(), and FPoly::GetOutsideWindings().
Predicate
template<typename InElementType, typename InAllocatorType> const PREDICATE_CLASS & TArray< InElementType, InAllocatorType >::Predicate
Definition at line 3764 of file Array.h.
The documentation for this class was generated from the following files:
Array.h
ArrayView.h