Unreal Engine 5.6 C++ API: StringBuilder.h File Reference
StringBuilder.h File Reference
#include "Containers/StringFwd.h"
#include "Containers/StringView.h"
#include "CoreTypes.h"
#include "HAL/PlatformString.h"
#include "HAL/UnrealMemory.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Templates/EnableIf.h"
#include "Templates/IsArrayOrRefOfTypeByPredicate.h"
#include "Templates/IsValidVariadicFunctionArg.h"
#include "Templates/Requires.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "Traits/IsCharEncodingCompatibleWith.h"
#include "Traits/IsCharEncodingSimplyConvertibleTo.h"
#include "Traits/IsCharType.h"
#include "Traits/IsContiguousContainer.h"
#include <type_traits>
Data Structures
struct TIsContiguousContainer< TWriteToString< CharType, BufferSize > >
class TStringBuilderBase< CharType >
String Builder.
class TStringBuilderWithBuffer< CharType, BufferSize >
A string builder with inline storage.
Functions
template<typename CharType>
auto AppendChars (TStringBuilderBase< CharType > &Builder)
Returns an object that can be used as the output container for algorithms by appending to the builder.
template<typename CharType>
constexpr int32 GetNum (const TStringBuilderBase< CharType > &Builder)
FStringBuilderBase & operator+= (FStringBuilderBase &Builder, ANSICHAR Char)
FStringBuilderBase & operator+= (FStringBuilderBase &Builder, FUtf8StringView Str)
FStringBuilderBase & operator+= (FStringBuilderBase &Builder, FWideStringView Str)
FStringBuilderBase & operator+= (FStringBuilderBase &Builder, UTF8CHAR Char)
FStringBuilderBase & operator+= (FStringBuilderBase &Builder, WIDECHAR Char)
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase &Builder, ANSICHAR Char)
template<typename T UE_REQUIRES>
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase &Builder, T Value)
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase &Builder, UTF8CHAR Char)=delete
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase &Builder, WIDECHAR Char)=delete
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, ANSICHAR Char)
template<typename T UE_REQUIRES>
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, T Value)
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, UTF32CHAR Char)
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, UTF8CHAR Char)
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, WIDECHAR Char)=delete
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, ANSICHAR Char)
template<typename T UE_REQUIRES>
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, T Value)
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, UTF32CHAR Char)
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, UTF8CHAR Char)=delete
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, WIDECHAR Char)
template<typename CharType, typename CharRangeType>
auto operator<< (TStringBuilderBase< CharType > &Builder, CharRangeType &&Str) -> decltype(Builder.Append(MakeStringView(Forward< CharRangeType >(Str))))
template<typename CharType, typename T UE_REQUIRES>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, const T &Value)
template<int32 BufferSize, typename... ArgTypes>
TStringBuilderWithBuffer< ANSICHAR, BufferSize > WriteToAnsiString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
template<int32 BufferSize, typename... ArgTypes>
PRAGMA_ENABLE_DEPRECATION_WARNINGS TStringBuilderWithBuffer< TCHAR, BufferSize > WriteToString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
template<int32 BufferSize, typename... ArgTypes>
TStringBuilderWithBuffer< UTF8CHAR, BufferSize > WriteToUtf8String (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
template<int32 BufferSize, typename... ArgTypes>
TStringBuilderWithBuffer< WIDECHAR, BufferSize > WriteToWideString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
Variables
template<typename T>
constexpr bool TIsFormattedStringBuilderType_V = false
Trait which determines whether or not a type can be appended to TStringBuilderBase via TFormatSpecifier.
template<typename T>
constexpr bool TIsFormattedStringBuilderType_V< const T > = TIsFormattedStringBuilderType_V<T>
template<typename T>
constexpr bool TIsFormattedStringBuilderType_V< const volatile T > = TIsFormattedStringBuilderType_V<T>
template<>
constexpr bool TIsFormattedStringBuilderType_V< double > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< float > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< int16 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< int32 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< int64 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< int8 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< long > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< long double > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< uint16 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< uint32 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< uint64 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< uint8 > = true
template<>
constexpr bool TIsFormattedStringBuilderType_V< unsigned long > = true
template<typename T>
constexpr bool TIsFormattedStringBuilderType_V< volatile T > = TIsFormattedStringBuilderType_V<T>
Function Documentation
AppendChars()
template<typename CharType> auto AppendChars (TStringBuilderBase< CharType > & Builder)
Returns an object that can be used as the output container for algorithms by appending to the builder.
Example: Algo::Transform(StringView, AppendChars(Builder), FChar::ToLower)
Definition at line 638 of file StringBuilder.h.
References Add, and TStringBuilderBase< CharType >::AppendChar().
GetNum()
template<typename CharType> int32 GetNum (const TStringBuilderBase< CharType > & Builder) inline constexpr
Definition at line 459 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Len().
operator+=() [1/5]
FStringBuilderBase & operator+= (FStringBuilderBase & Builder, ANSICHAR Char) inline
Definition at line 527 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator+=() [2/5]
FStringBuilderBase & operator+= (FStringBuilderBase & Builder, FUtf8StringView Str) inline
Definition at line 531 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Append().
operator+=() [3/5]
FStringBuilderBase & operator+= (FStringBuilderBase & Builder, FWideStringView Str) inline
Definition at line 530 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Append().
operator+=() [4/5]
FStringBuilderBase & operator+= (FStringBuilderBase & Builder, UTF8CHAR Char) inline
Definition at line 529 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator+=() [5/5]
FStringBuilderBase & operator+= (FStringBuilderBase & Builder, WIDECHAR Char) inline
Definition at line 528 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [1/16]
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase & Builder, ANSICHAR Char) inline
Definition at line 514 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [2/16]
template<typename T UE_REQUIRES> FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase & Builder, T Value) inline
Definition at line 536 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Append(), and Value.
operator<<() [3/16]
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase & Builder, UTF8CHAR Char) inline delete
operator<<() [4/16]
FAnsiStringBuilderBase & operator<< (FAnsiStringBuilderBase & Builder, WIDECHAR Char) inline delete
operator<<() [5/16]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, ANSICHAR Char) inline
Definition at line 520 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [6/16]
template<typename T UE_REQUIRES> FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, T Value) inline
Definition at line 540 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Append(), UTF8TEXT, and Value.
operator<<() [7/16]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, UTF32CHAR Char) inline
Definition at line 524 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [8/16]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, UTF8CHAR Char) inline
Definition at line 521 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [9/16]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, WIDECHAR Char) inline delete
operator<<() [10/16]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, ANSICHAR Char) inline
Definition at line 517 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [11/16]
template<typename T UE_REQUIRES> FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, T Value) inline
Definition at line 538 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Append(), Value, and WIDETEXT.
operator<<() [12/16]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, UTF32CHAR Char) inline
Definition at line 523 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [13/16]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, UTF8CHAR Char) inline delete
operator<<() [14/16]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, WIDECHAR Char) inline
Definition at line 519 of file StringBuilder.h.
References TStringBuilderBase< CharType >::AppendChar().
operator<<() [15/16]
template<typename CharType, typename CharRangeType> auto operator<< (TStringBuilderBase< CharType > & Builder, CharRangeType && Str) -> decltype(Builder.Append(MakeStringView(Forward<CharRangeType>(Str)))) inline
Definition at line 501 of file StringBuilder.h.
References Forward(), ImplicitConv(), and MakeStringView().
operator<<() [16/16]
template<typename CharType, typename T UE_REQUIRES> TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > & Builder, const T & Value) inline
Definition at line 563 of file StringBuilder.h.
References TStringBuilderBase< CharType >::Appendf(), TIsFormattedStringBuilderType_V, and Value.
WriteToAnsiString()
template<int32 BufferSize, typename... ArgTypes> TStringBuilderWithBuffer< ANSICHAR, BufferSize > WriteToAnsiString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
See WriteToString.
Definition at line 613 of file StringBuilder.h.
References InPlace.
WriteToString()
template<int32 BufferSize, typename... ArgTypes> PRAGMA_ENABLE_DEPRECATION_WARNINGS TStringBuilderWithBuffer< TCHAR, BufferSize > WriteToString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
Example Use Cases:
For void Action(FStringView) -> Action(WriteToString<64>(Arg1, Arg2)); For UE_LOG or checkf -> checkf(Condition, TEXT("%s"), *WriteToString<32>(Arg));
Definition at line 606 of file StringBuilder.h.
References InPlace.
WriteToUtf8String()
template<int32 BufferSize, typename... ArgTypes> TStringBuilderWithBuffer< UTF8CHAR, BufferSize > WriteToUtf8String (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
See WriteToString.
Definition at line 627 of file StringBuilder.h.
References InPlace.
WriteToWideString()
template<int32 BufferSize, typename... ArgTypes> TStringBuilderWithBuffer< WIDECHAR, BufferSize > WriteToWideString (ArgTypes &&... Args)
A function to create and append to a temporary string builder.
See WriteToString.
Definition at line 620 of file StringBuilder.h.
References InPlace.
Variable Documentation
TIsFormattedStringBuilderType_V
template<typename T> bool TIsFormattedStringBuilderType_V = false constexpr
Trait which determines whether or not a type can be appended to TStringBuilderBase via TFormatSpecifier.
Definition at line 546 of file StringBuilder.h.
Referenced by operator<<().
TIsFormattedStringBuilderType_V< const T >
template<typename T> bool TIsFormattedStringBuilderType_V< const T > = TIsFormattedStringBuilderType_V<T> constexpr
Definition at line 561 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< const volatile T >
template<typename T> bool TIsFormattedStringBuilderType_V< const volatile T > = TIsFormattedStringBuilderType_V<T> constexpr
Definition at line 563 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< double >
template<> bool TIsFormattedStringBuilderType_V< double > = true inline constexpr
Definition at line 556 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< float >
template<> bool TIsFormattedStringBuilderType_V< float > = true inline constexpr
Definition at line 555 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< int16 >
template<> bool TIsFormattedStringBuilderType_V< int16 > = true inline constexpr
Definition at line 552 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< int32 >
template<> bool TIsFormattedStringBuilderType_V< int32 > = true inline constexpr
Definition at line 553 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< int64 >
template<> bool TIsFormattedStringBuilderType_V< int64 > = true inline constexpr
Definition at line 554 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< int8 >
template<> bool TIsFormattedStringBuilderType_V< int8 > = true inline constexpr
Definition at line 551 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< long >
template<> bool TIsFormattedStringBuilderType_V< long > = true inline constexpr
Definition at line 558 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< long double >
template<> bool TIsFormattedStringBuilderType_V< long double > = true inline constexpr
Definition at line 557 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< uint16 >
template<> bool TIsFormattedStringBuilderType_V< uint16 > = true inline constexpr
Definition at line 548 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< uint32 >
template<> bool TIsFormattedStringBuilderType_V< uint32 > = true inline constexpr
Definition at line 549 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< uint64 >
template<> bool TIsFormattedStringBuilderType_V< uint64 > = true inline constexpr
Definition at line 550 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< uint8 >
template<> bool TIsFormattedStringBuilderType_V< uint8 > = true inline constexpr
Definition at line 547 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< unsigned long >
template<> bool TIsFormattedStringBuilderType_V< unsigned long > = true inline constexpr
Definition at line 559 of file StringBuilder.h.
TIsFormattedStringBuilderType_V< volatile T >
template<typename T> bool TIsFormattedStringBuilderType_V< volatile T > = TIsFormattedStringBuilderType_V<T> constexpr
Definition at line 562 of file StringBuilder.h.