Unreal Engine 5.6 C++ API: Metasound::TLiteralTraits< DataType > Struct Template Reference
Metasound::TLiteralTraits< DataType > Struct Template Reference
Determines whether a DataType supports construction using the given literal.
#include "MetasoundDataFactory.h"
Public Types
using TVariantConstructorTraits = DataFactoryPrivate::TDataTypeVariantConstructorTraits<DataType, FLiteral::FVariantType>
Static Public Member Functions
static const bool IsParsable (const FLiteral &InLiteral)
Determines if a constructor for the DataType exists which accepts an FOperatorSettings with the literals constructor arg type, and/or one that accepts the literal constructor arg type.
Static Public Attributes
static constexpr bool bIsParsableFromAnyLiteralType
static constexpr bool bIsParseableFromAnyArrayLiteralType
Detailed Description
template<typename DataType>
struct Metasound::TLiteralTraits< DataType >
Determines whether a DataType supports construction using the given literal.
Template Parameters
DataType - The registered Metasound Data Type.
Definition at line 779 of file MetasoundDataFactory.h.
Member Typedef Documentation
TVariantConstructorTraits
template<typename DataType> using Metasound::TLiteralTraits< DataType >::TVariantConstructorTraits = DataFactoryPrivate::TDataTypeVariantConstructorTraits<DataType, FLiteral::FVariantType>
Definition at line 781 of file MetasoundDataFactory.h.
Member Function Documentation
IsParsable()
template<typename DataType> const bool Metasound::TLiteralTraits< DataType >::IsParsable (const FLiteral & InLiteral) inline static
Determines if a constructor for the DataType exists which accepts an FOperatorSettings with the literals constructor arg type, and/or one that accepts the literal constructor arg type.
Parameters
InLiteral - The literal containing the constructor argument.
Returns
True if a constructor for the DataType exists which accepts an FOperatorSettings with the literals constructor arg type, or one that accepts the literal constructor arg type. It returns False otherwise.
Definition at line 806 of file MetasoundDataFactory.h.
References Metasound::Boolean, Metasound::BooleanArray, checkNoEntry, Metasound::Float, Metasound::FloatArray, Metasound::FLiteral::GetType(), Metasound::Integer, Metasound::IntegerArray, Metasound::Invalid, Metasound::None, Metasound::NoneArray, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, Metasound::String, Metasound::StringArray, Metasound::UObjectProxy, Metasound::UObjectProxyArray, Metasound::Value, and Metasound::TIsParsable< DataType, ArgTypes >::Value.
Referenced by Metasound::TCopyableDataChannel< TDataType >::PushLiteral(), and Metasound::TSender< TDataType >::PushLiteral().
Field Documentation
bIsParsableFromAnyLiteralType
template<typename DataType> bool Metasound::TLiteralTraits< DataType >::bIsParsableFromAnyLiteralType static constexpr
Initial value:
=
            TVariantConstructorTraits::bIsDefaultConstructible ||
            TVariantConstructorTraits::bIsConstructibleWithSettings ||
            TVariantConstructorTraits::bIsConstructibleWithArgs ||
            TVariantConstructorTraits::bIsConstructibleWithSettingsAndArgs ||
            bIsParseableFromAnyArrayLiteralType
Definition at line 789 of file MetasoundDataFactory.h.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::CreateDataTypeInfo(), and Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
bIsParseableFromAnyArrayLiteralType
template<typename DataType> bool Metasound::TLiteralTraits< DataType >::bIsParseableFromAnyArrayLiteralType static constexpr
Initial value:
=
            TVariantConstructorTraits::bIsArrayDefaultConstructible ||
            TVariantConstructorTraits::bIsArrayConstructibleWithSettings ||
            TVariantConstructorTraits::bIsArrayConstructibleWithArgs ||
            TVariantConstructorTraits::bIsArrayConstructibleWithSettingsAndArgs
Definition at line 783 of file MetasoundDataFactory.h.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::CreateDataTypeInfo().
The documentation for this struct was generated from the following file:
MetasoundDataFactory.h