Unreal Engine 5.6 C++ API: DisplayClusterHelpers::str Namespace Reference
DisplayClusterHelpers::str Namespace Reference
Functions
template<typename TVal>
static FString ArrayToStr (const TArray< TVal > &InData, const FString &InSeparator=FString(DisplayClusterStrings::common::ArrayValSeparator), bool bAddQuotes=true)
static FString BoolToStr (bool bVal, bool bAsWord=true)
template<typename TVal>
static bool ExtractArray (const FString &InLine, const FString &InParamName, const FString &InSeparator, TArray< TVal > &OutValue)
template<typename TKey, typename TVal>
static bool ExtractMap (const FString &InLine, const FString &InParamName, TMap< TKey, TVal > &OutData, const FString &InPairSeparator=FString(DisplayClusterStrings::common::PairSeparator), const FString &InKeyValSeparator=FString(DisplayClusterStrings::common::KeyValSeparator))
template<typename T>
static bool ExtractValue (const FString &InLine, const FString &InParamName, T &OutValue, bool bInTrimQuotes=true)
template<typename TKey, typename TVal>
FString MapToStr (const TMap< TKey, TVal > &InData, const FString &InPairSeparator=FString(DisplayClusterStrings::common::PairSeparator), const FString &InKeyValSeparator=FString(DisplayClusterStrings::common::KeyValSeparator), bool bAddQuoutes=true)
template<typename TVal>
static FString SetToStr (const TSet< TVal > &InData, const FString &InSeparator=FString(DisplayClusterStrings::common::ArrayValSeparator), bool bAddQuotes=true)
template<typename TVal>
static void StrToArray (const FString &InData, const FString &InSeparator, TArray< TVal > &OutData, bool bCullEmpty=true)
template<typename TKey, typename TVal>
void StrToMap (const FString &InData, TMap< TKey, TVal > &OutData, const FString &InPairSeparator=FString(DisplayClusterStrings::common::PairSeparator), const FString &InKeyValSeparator=FString(DisplayClusterStrings::common::KeyValSeparator))
template<typename TVal>
static void StrToSet (const FString &InData, const FString &InSeparator, TSet< TVal > &OutData, bool bCullEmpty=true)
static FString TrimStringValue (const FString &InLine, bool bTrimQuotes=true)
static void TrimStringValue (FString &InLine, bool bTrimQuotes=true)
Function Documentation
ArrayToStr()
template<typename TVal> FString DisplayClusterHelpers::str::ArrayToStr (const TArray< TVal > & InData, const FString & InSeparator = FString(DisplayClusterStrings::common::ArrayValSeparator), bool bAddQuotes = true) static
Definition at line 95 of file DisplayClusterHelpers.h.
References DisplayClusterStrings::common::ArrayValSeparator, No, TEXT, ToString(), and Yes.
Referenced by SetToStr().
BoolToStr()
FString DisplayClusterHelpers::str::BoolToStr (bool bVal, bool bAsWord = true) inline static
Definition at line 32 of file DisplayClusterHelpers.h.
References TEXT.
ExtractArray()
template<typename TVal> bool DisplayClusterHelpers::str::ExtractArray (const FString & InLine, const FString & InParamName, const FString & InSeparator, TArray< TVal > & OutValue) static
Definition at line 239 of file DisplayClusterHelpers.h.
References ExtractValue(), and StrToArray().
Referenced by ExtractMap().
ExtractMap()
template<typename TKey, typename TVal> bool DisplayClusterHelpers::str::ExtractMap (const FString & InLine, const FString & InParamName, TMap< TKey, TVal > & OutData, const FString & InPairSeparator = FString(DisplayClusterStrings::common::PairSeparator), const FString & InKeyValSeparator = FString(DisplayClusterStrings::common::KeyValSeparator)) static
Definition at line 256 of file DisplayClusterHelpers.h.
References ExtractArray(), DisplayClusterStrings::common::KeyValSeparator, DisplayClusterStrings::common::PairSeparator, and StrToMap().
ExtractValue()
template<typename T> bool DisplayClusterHelpers::str::ExtractValue (const FString & InLine, const FString & InParamName, T & OutValue, bool bInTrimQuotes = true) static
Definition at line 217 of file DisplayClusterHelpers.h.
References TrimStringValue(), and FParse::Value().
Referenced by ExtractArray().
MapToStr()
template<typename TKey, typename TVal> FString DisplayClusterHelpers::str::MapToStr (const TMap< TKey, TVal > & InData, const FString & InPairSeparator = FString(DisplayClusterStrings::common::PairSeparator), const FString & InKeyValSeparator = FString(DisplayClusterStrings::common::KeyValSeparator), bool bAddQuoutes = true)
Definition at line 174 of file DisplayClusterHelpers.h.
References DisplayClusterStrings::common::KeyValSeparator, No, DisplayClusterStrings::common::PairSeparator, TEXT, ToString(), and Yes.
SetToStr()
template<typename TVal> FString DisplayClusterHelpers::str::SetToStr (const TSet< TVal > & InData, const FString & InSeparator = FString(DisplayClusterStrings::common::ArrayValSeparator), bool bAddQuotes = true) static
Definition at line 139 of file DisplayClusterHelpers.h.
References ArrayToStr(), and DisplayClusterStrings::common::ArrayValSeparator.
StrToArray()
template<typename TVal> void DisplayClusterHelpers::str::StrToArray (const FString & InData, const FString & InSeparator, TArray< TVal > & OutData, bool bCullEmpty = true) static
Definition at line 69 of file DisplayClusterHelpers.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::AddDefaulted(), Item, and TrimStringValue().
Referenced by ExtractArray(), StrToMap(), and StrToSet().
StrToMap()
template<typename TKey, typename TVal> void DisplayClusterHelpers::str::StrToMap (const FString & InData, TMap< TKey, TVal > & OutData, const FString & InPairSeparator = FString(DisplayClusterStrings::common::PairSeparator), const FString & InKeyValSeparator = FString(DisplayClusterStrings::common::KeyValSeparator))
Definition at line 147 of file DisplayClusterHelpers.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace(), ESearchCase::IgnoreCase, DisplayClusterStrings::common::KeyValSeparator, DisplayClusterStrings::common::PairSeparator, StrToArray(), and TrimStringValue().
Referenced by ExtractMap().
StrToSet()
template<typename TVal> void DisplayClusterHelpers::str::StrToSet (const FString & InData, const FString & InSeparator, TSet< TVal > & OutData, bool bCullEmpty = true) static
Definition at line 128 of file DisplayClusterHelpers.h.
References TSet< InElementType, KeyFuncs, Allocator >::Append(), TSet< InElementType, KeyFuncs, Allocator >::Reset(), and StrToArray().
TrimStringValue() [1/2]
FString DisplayClusterHelpers::str::TrimStringValue (const FString & InLine, bool bTrimQuotes = true) static
Definition at line 59 of file DisplayClusterHelpers.h.
References TrimStringValue().
TrimStringValue() [2/2]
void DisplayClusterHelpers::str::TrimStringValue (FString & InLine, bool bTrimQuotes = true) static
Definition at line 39 of file DisplayClusterHelpers.h.
Referenced by ExtractValue(), DisplayClusterHelpers::filesystem::GetFullPathForConfigResource(), DisplayClusterHelpers::filesystem::GetRelativePathForConfigResource(), StrToArray(), StrToMap(), and TrimStringValue().