Unreal Engine 5.6 C++ Documentation: UPlayerInput Class Reference
UPlayerInput Class Reference
Object within PlayerController that processes player input.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerInput.h>
Public Member Functions
UPlayerInput ()
bool GetAxisProperties (const FKey AxisKey, FInputAxisProperties &AxisProperties)
Gets the axis properties for a given AxisKey.
void SetAxisProperties (const FKey AxisKey, const FInputAxisProperties &AxisProperties)
Gets the axis properties for a given AxisKey.
void SetMouseSensitivity (const float SensitivityX, const float SensitivityY)
Exec function to change the mouse sensitivity.
void SetMouseSensitivity (const float Sensitivity)
Sets both X and Y axis sensitivity to the supplied value.
void SetBind (FName BindName, const FString &Command)
Exec function to add a debug exec command.
float GetMouseSensitivityX ()
Returns the mouse sensitivity along the X-axis, or the Y-axis, or 1.0 if none are known.
float GetMouseSensitivityY ()
Returns the mouse sensitivity along the Y-axis, or 1.0 if none are known.
bool GetInvertAxisKey (const FKey AxisKey)
Returns whether an Axis Key is inverted.
bool GetInvertAxis (const FName AxisName)
Returns whether an Axis Mapping is inverted.
void InvertAxisKey (const FKey AxisKey)
Exec function to invert an axis key.
void InvertAxis (const FName AxisName)
Exec function to invert an axis mapping.
void ClearSmoothing ()
Exec function to reset mouse smoothing values.
void AddActionMapping (const FInputActionKeyMapping &KeyMapping)
Add a player specific action mapping.
void RemoveActionMapping (const FInputActionKeyMapping &KeyMapping)
Remove a player specific action mapping.
void AddAxisMapping (const FInputAxisKeyMapping &KeyMapping)
Add a player specific axis mapping.
void RemoveAxisMapping (const FInputAxisKeyMapping &KeyMapping)
Remove a player specific axis mapping.
void ForceRebuildingKeyMaps (const bool bRestoreDefaults=false)
Clear the current cached key maps and rebuild from the source arrays.
APlayerController * GetOuterAPlayerController () const
Return's this object casted to a player controller.
ULocalPlayer * GetOwningLocalPlayer () const
Returns the owning local player of this Input Object.
virtual void PostInitProperties () override
virtual UWorld * GetWorld () const override
virtual void FlushPressedKeys ()
Flushes the current key state.
void FlushPressedActionBindingKeys (FName ActionName)
Flushes the current key state of the keys associated with the action name passed in.
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS bool InputKey (const FInputKeyParams &Params) final
Handles a key input event.
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool InputKey (const FInputKeyEventArgs &Params)
Handles a key input event.
bool InputTouch (uint32 Handle, ETouchType::Type Type, const FVector2D &TouchLocation, float Force, FDateTime DeviceTimestamp, uint32 TouchpadIndex)
Handles a touch input event.
bool InputTouch (const FInputDeviceId DeviceId, uint32 Handle, ETouchType::Type Type, const FVector2D &TouchLocation, float Force, uint32 TouchpadIndex, const uint64 Timestamp)
Handles a touch input event.
bool InputMotion (const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration)
Handles a motion input event.
bool InputMotion (const FInputDeviceId DeviceId, const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, const uint64 Timestamp)
Handles a motion input event.
bool InputGesture (const FKey Gesture, const EInputEvent Event, const float Value)
Handles a gesture input event.
bool InputGesture (const FInputDeviceId DeviceId, const FKey Gesture, const EInputEvent Event, const float Value, const uint64 Timestamp)
Handles a gesture input event.
void UpdatePinchStartDistance ()
Manually update the GestureRecognizer AnchorDistance using the current locations of the touches.
void Tick (float DeltaTime)
Per frame tick function.
virtual void ProcessInputStack (const TArray< UInputComponent * > &InputComponentStack, const float DeltaTime, const bool bGamePaused)
Process the frame's input events given the current input component stack.
void DiscardPlayerInput ()
Rather than processing input, consume it and discard without doing anything useful with it.
virtual float SmoothMouse (float aMouse, uint8 &SampleCount, int32 Index)
Smooth mouse movement, because mouse sampling doesn't match up with tick time.
virtual void DisplayDebug (class UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos)
Draw important PlayerInput variables on canvas.
FKeyState * GetKeyState (FKey InKey)
const FKeyState * GetKeyState (FKey InKey) const
bool IsPressed (FKey InKey) const
bool WasJustPressed (FKey InKey) const
bool WasJustReleased (FKey InKey) const
return true if InKey went from down to up since player input was last processed.
float GetTimeDown (FKey InKey) const
float GetKeyValue (FKey InKey) const
float GetRawKeyValue (FKey InKey) const
FVector GetProcessedVectorKeyValue (FKey InKey) const
FVector GetRawVectorKeyValue (FKey InKey) const
bool IsAltPressed () const
bool IsCtrlPressed () const
bool IsShiftPressed () const
bool IsCmdPressed () const
uint32 GetKeyMapBuildIndex () const
bool Exec (UWorld *UInWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Exec handler.
FString GetBind (FKey Key)
Returns the command for a given key in the legacy binding system.
FKeyBind GetExecBind (FString const &ExecCommand)
Get the legacy Exec key binding for the given command.
bool ExecInputCommands (UWorld *InWorld, const TCHAR *Cmd, class FOutputDevice &Ar)
Execute input commands within the legacy key binding system.
const TArray< FInputActionKeyMapping > & GetKeysForAction (const FName ActionName) const
Returns the list of keys mapped to the specified Action Name.
const TArray< FInputAxisKeyMapping > & GetKeysForAxis (const FName AxisName) const
Returns the list of keys mapped to the specified Axis Name.
Static Public Member Functions
static void AddEngineDefinedActionMapping (const FInputActionKeyMapping &ActionMapping)
Add an engine defined action mapping that cannot be remapped.
static void AddEngineDefinedAxisMapping (const FInputAxisKeyMapping &AxisMapping)
Add an engine defined axis mapping that cannot be remapped.
static const TArray< FInputActionKeyMapping > & GetEngineDefinedActionMappings ()
static const TArray< FInputAxisKeyMapping > & GetEngineDefinedAxisMappings ()
Public Attributes
FVector Touches [EKeys::NUM_TOUCH_KEYS]
TMap< uint32, FVector > TouchEventLocations
Used to store paired touch locations for event ids during the frame and flushed when processed.
float ZeroTime [2]
float SmoothedMouse [2]
How long received mouse movement has been zero.
int32 MouseSamples
Current average mouse movement/sample.
float MouseSamplingTotal
Number of mouse samples since mouse movement has been zero.
TArray< struct FKeyBind > DebugExecBindings
Generic bindings of keys to Exec()-compatible strings for development purposes only.
TArray< struct FInputAxisConfigEntry > AxisConfig
This player's version of the Axis Properties.
TArray< struct FInputActionKeyMapping > ActionMappings
This player's version of the Action Mappings.
TArray< struct FInputAxisKeyMapping > AxisMappings
This player's version of Axis Mappings.
TArray< FName > InvertedAxis
List of Axis Mappings that have been inverted.
Protected Member Functions
virtual void EvaluateKeyMapState (const float DeltaTime, const bool bGamePaused, OUT TArray< TPair< FKey, FKeyState * > > &KeysWithEvents)
Evaluates the current state of the KeyStateMap this tick.
virtual void EvaluateInputDelegates (const TArray< UInputComponent * > &InputComponentStack, const float DeltaTime, const bool bGamePaused, const TArray< TPair< FKey, FKeyState * > > &KeysWithEvents)
Evaluates the state of any bound input delegates on the given Input Component Stack.
TMap< FKey, FKeyState > & GetKeyStateMap ()
virtual FVector MassageVectorAxisInput (FKey Key, FVector RawValue)
Given raw keystate value of a vector axis, returns the "massaged" value.
virtual float MassageAxisInput (FKey Key, float RawValue)
Given raw keystate value, returns the "massaged" value.
void ConditionalInitAxisProperties ()
Initialized axis properties (i.e deadzone values) if needed.
virtual bool IsKeyHandledByAction (FKey Key) const
void GetActionsBoundToKey (UInputComponent *InputComponent, FKey Key, TArray< TSharedPtr< FInputActionBinding > > &Actions)
Retrieves the actions bound to the given input component which are triggered by a given key.
Friends
class UEnhancedPlayerInput
Detailed Description
Object within PlayerController that processes player input.
Only exists on the client in network games.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Input/index.html
Definition at line 411 of file PlayerInput.h.
Constructor & Destructor Documentation
UPlayerInput()
UPlayerInput::UPlayerInput ()
Member Function Documentation
AddActionMapping()
void UPlayerInput::AddActionMapping (const FInputActionKeyMapping & KeyMapping)
Add a player specific action mapping.
References AddActionMapping().
AddAxisMapping()
void UPlayerInput::AddAxisMapping (const FInputAxisKeyMapping & KeyMapping)
Add a player specific axis mapping.
References AddAxisMapping().
AddEngineDefinedActionMapping()
void UPlayerInput::AddEngineDefinedActionMapping (const FInputActionKeyMapping & ActionMapping) static
Add an engine defined action mapping that cannot be remapped.
References AddEngineDefinedActionMapping().
AddEngineDefinedAxisMapping()
void UPlayerInput::AddEngineDefinedAxisMapping (const FInputAxisKeyMapping & AxisMapping) static
Add an engine defined axis mapping that cannot be remapped.
References AddEngineDefinedAxisMapping().
ClearSmoothing()
void UPlayerInput::ClearSmoothing ()
Exec function to reset mouse smoothing values.
References ClearSmoothing().
ConditionalInitAxisProperties()
void UPlayerInput::ConditionalInitAxisProperties () protected
Initialized axis properties (i.e deadzone values) if needed.
DiscardPlayerInput()
void UPlayerInput::DiscardPlayerInput ()
Rather than processing input, consume it and discard without doing anything useful with it.
Like calling ProcessInputStack() and ignoring all results.
References DiscardPlayerInput().
DisplayDebug()
virtual void UPlayerInput::DisplayDebug (class UCanvas * Canvas, const FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) virtual
Draw important PlayerInput variables on canvas.
HUD will call DisplayDebug() on the current ViewTarget when the ShowDebug exec is used
Parameters
Canvas - Canvas to draw on
DebugDisplay - Contains information about what debug data to display
YL - Height of the current font
YPos - Y position on Canvas. YPos += YL, gives position to draw text for next debug line.
References DisplayDebug().
EvaluateInputDelegates()
virtual void UPlayerInput::EvaluateInputDelegates (const TArray< UInputComponent * > & InputComponentStack, const float DeltaTime, const bool bGamePaused, const TArray< TPair< FKey, FKeyState * > > & KeysWithEvents) protected virtual
Evaluates the state of any bound input delegates on the given Input Component Stack.
This should only be called from UPlayerInput::ProcessInputStack
References EvaluateInputDelegates().
EvaluateKeyMapState()
virtual void UPlayerInput::EvaluateKeyMapState (const float DeltaTime, const bool bGamePaused, OUT TArray< TPair< FKey, FKeyState * > > & KeysWithEvents) protected virtual
Evaluates the current state of the KeyStateMap this tick.
Should only be called from UPlayerInput::ProcessInputStack
References EvaluateKeyMapState().
Exec()
bool UPlayerInput::Exec (UWorld * UInWorld, const TCHAR * Cmd, FOutputDevice & Ar)
Exec handler.
ExecInputCommands()
bool UPlayerInput::ExecInputCommands (UWorld * InWorld, const TCHAR * Cmd, class FOutputDevice & Ar)
Execute input commands within the legacy key binding system.
FlushPressedActionBindingKeys()
void UPlayerInput::FlushPressedActionBindingKeys (FName ActionName)
Flushes the current key state of the keys associated with the action name passed in.
FlushPressedKeys()
virtual void UPlayerInput::FlushPressedKeys () virtual
Flushes the current key state.
ForceRebuildingKeyMaps()
void UPlayerInput::ForceRebuildingKeyMaps (const bool bRestoreDefaults = false)
Clear the current cached key maps and rebuild from the source arrays.
References ForceRebuildingKeyMaps().
GetActionsBoundToKey()
void UPlayerInput::GetActionsBoundToKey (UInputComponent * InputComponent, FKey Key, TArray< TSharedPtr< FInputActionBinding > > & Actions) protected
Retrieves the actions bound to the given input component which are triggered by a given key.
GetAxisProperties()
bool UPlayerInput::GetAxisProperties (const FKey AxisKey, FInputAxisProperties & AxisProperties)
Gets the axis properties for a given AxisKey.
Returns if true if AxisKey was found in the AxisConfig array.
References GetAxisProperties().
GetBind()
FString UPlayerInput::GetBind (FKey Key)
Returns the command for a given key in the legacy binding system.
GetEngineDefinedActionMappings()
const TArray< FInputActionKeyMapping > & UPlayerInput::GetEngineDefinedActionMappings () inline static
Definition at line 745 of file PlayerInput.h.
GetEngineDefinedAxisMappings()
const TArray< FInputAxisKeyMapping > & UPlayerInput::GetEngineDefinedAxisMappings () inline static
Definition at line 746 of file PlayerInput.h.
GetExecBind()
FKeyBind UPlayerInput::GetExecBind (FString const & ExecCommand)
Get the legacy Exec key binding for the given command.
GetInvertAxis()
bool UPlayerInput::GetInvertAxis (const FName AxisName)
Returns whether an Axis Mapping is inverted.
References GetInvertAxis().
GetInvertAxisKey()
bool UPlayerInput::GetInvertAxisKey (const FKey AxisKey)
Returns whether an Axis Key is inverted.
References GetInvertAxisKey().
GetKeyMapBuildIndex()
uint32 UPlayerInput::GetKeyMapBuildIndex () const inline
Definition at line 721 of file PlayerInput.h.
GetKeysForAction()
const TArray< FInputActionKeyMapping > & UPlayerInput::GetKeysForAction (const FName ActionName) const
Returns the list of keys mapped to the specified Action Name.
GetKeysForAxis()
const TArray< FInputAxisKeyMapping > & UPlayerInput::GetKeysForAxis (const FName AxisName) const
Returns the list of keys mapped to the specified Axis Name.
GetKeyState() [1/2]
FKeyState * UPlayerInput::GetKeyState (FKey InKey) inline
Returns
key state of the InKey
Definition at line 682 of file PlayerInput.h.
References GetKeyState().
GetKeyState() [2/2]
const FKeyState * UPlayerInput::GetKeyState (FKey InKey) const inline
Definition at line 683 of file PlayerInput.h.
GetKeyStateMap()
TMap< FKey, FKeyState > & UPlayerInput::GetKeyStateMap () inline protected
Definition at line 749 of file PlayerInput.h.
GetKeyValue()
float UPlayerInput::GetKeyValue (FKey InKey) const
Returns
current state of the InKey
GetMouseSensitivityX()
float UPlayerInput::GetMouseSensitivityX ()
Returns the mouse sensitivity along the X-axis, or the Y-axis, or 1.0 if none are known.
References GetMouseSensitivityX().
GetMouseSensitivityY()
float UPlayerInput::GetMouseSensitivityY ()
Returns the mouse sensitivity along the Y-axis, or 1.0 if none are known.
References GetMouseSensitivityY().
GetOuterAPlayerController()
APlayerController * UPlayerInput::GetOuterAPlayerController () const
Return's this object casted to a player controller.
This can be null if there is no player controller.
References GetOuterAPlayerController().
GetOwningLocalPlayer()
ULocalPlayer * UPlayerInput::GetOwningLocalPlayer () const
Returns the owning local player of this Input Object.
This will only be valid if there is a current outer player controller.
References GetOwningLocalPlayer().
GetProcessedVectorKeyValue()
FVector UPlayerInput::GetProcessedVectorKeyValue (FKey InKey) const
Returns
processed value of the InKey
GetRawKeyValue()
float UPlayerInput::GetRawKeyValue (FKey InKey) const
Returns
current state of the InKey
GetRawVectorKeyValue()
FVector UPlayerInput::GetRawVectorKeyValue (FKey InKey) const
Returns
raw value of the InKey
GetTimeDown()
float UPlayerInput::GetTimeDown (FKey InKey) const
Returns
how long the key has been held down, or 0.f if not down.
GetWorld()
virtual UWorld * UPlayerInput::GetWorld () const override virtual
InputGesture() [1/2]
bool UPlayerInput::InputGesture (const FInputDeviceId DeviceId, const FKey Gesture, const EInputEvent Event, const float Value, const uint64 Timestamp)
Handles a gesture input event.
Returns true.
References InputGesture(), and uint64.
InputGesture() [2/2]
bool UPlayerInput::InputGesture (const FKey Gesture, const EInputEvent Event, const float Value)
Handles a gesture input event.
Returns true.
References InputGesture().
InputKey() [1/2]
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool UPlayerInput::InputKey (const FInputKeyEventArgs & Params) virtual
Handles a key input event.
Returns true if there is an action that handles the specified key.
References InputKey().
InputKey() [2/2]
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS bool UPlayerInput::InputKey (const FInputKeyParams & Params) final virtual
Handles a key input event.
Returns true if there is an action that handles the specified key.
References InputKey().
InputMotion() [1/2]
bool UPlayerInput::InputMotion (const FInputDeviceId DeviceId, const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration, const uint64 Timestamp)
Handles a motion input event.
Returns true.
References Acceleration, InputMotion(), and uint64.
InputMotion() [2/2]
bool UPlayerInput::InputMotion (const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration)
Handles a motion input event.
Returns true.
References Acceleration, and InputMotion().
InputTouch() [1/2]
bool UPlayerInput::InputTouch (const FInputDeviceId DeviceId, uint32 Handle, ETouchType::Type Type, const FVector2D & TouchLocation, float Force, uint32 TouchpadIndex, const uint64 Timestamp)
Handles a touch input event.
Returns true.
References InputTouch(), and uint64.
InputTouch() [2/2]
bool UPlayerInput::InputTouch (uint32 Handle, ETouchType::Type Type, const FVector2D & TouchLocation, float Force, FDateTime DeviceTimestamp, uint32 TouchpadIndex)
Handles a touch input event.
Returns true.
References InputTouch().
InvertAxis()
void UPlayerInput::InvertAxis (const FName AxisName)
Exec function to invert an axis mapping.
References InvertAxis().
InvertAxisKey()
void UPlayerInput::InvertAxisKey (const FKey AxisKey)
Exec function to invert an axis key.
References InvertAxisKey().
IsAltPressed()
bool UPlayerInput::IsAltPressed () const
Returns
true if alt key is pressed
IsCmdPressed()
bool UPlayerInput::IsCmdPressed () const
Returns
true if cmd key is pressed
IsCtrlPressed()
bool UPlayerInput::IsCtrlPressed () const
Returns
true if ctrl key is pressed
IsKeyHandledByAction()
virtual bool UPlayerInput::IsKeyHandledByAction (FKey Key) const protected virtual
Returns
True if a key is handled by an action binding
IsPressed()
bool UPlayerInput::IsPressed (FKey InKey) const
Returns
true if InKey is currently held
IsShiftPressed()
bool UPlayerInput::IsShiftPressed () const
Returns
true if shift key is pressed
MassageAxisInput()
virtual float UPlayerInput::MassageAxisInput (FKey Key, float RawValue) protected virtual
Given raw keystate value, returns the "massaged" value.
Override for any custom behavior, such as input changes dependent on a particular game state.
MassageVectorAxisInput()
virtual FVector UPlayerInput::MassageVectorAxisInput (FKey Key, FVector RawValue) protected virtual
Given raw keystate value of a vector axis, returns the "massaged" value.
Override for any custom behavior, such as input changes dependent on a particular game state.
PostInitProperties()
virtual void UPlayerInput::PostInitProperties () override virtual
ProcessInputStack()
virtual void UPlayerInput::ProcessInputStack (const TArray< UInputComponent * > & InputComponentStack, const float DeltaTime, const bool bGamePaused) virtual
Process the frame's input events given the current input component stack.
References ProcessInputStack().
RemoveActionMapping()
void UPlayerInput::RemoveActionMapping (const FInputActionKeyMapping & KeyMapping)
Remove a player specific action mapping.
References RemoveActionMapping().
RemoveAxisMapping()
void UPlayerInput::RemoveAxisMapping (const FInputAxisKeyMapping & KeyMapping)
Remove a player specific axis mapping.
References RemoveAxisMapping().
SetAxisProperties()
void UPlayerInput::SetAxisProperties (const FKey AxisKey, const FInputAxisProperties & AxisProperties)
Gets the axis properties for a given AxisKey.
Returns if true if AxisKey was found in the AxisConfig array.
References SetAxisProperties().
SetBind()
void UPlayerInput::SetBind (FName BindName, const FString & Command)
Exec function to add a debug exec command.
References SetBind().
SetMouseSensitivity() [1/2]
void UPlayerInput::SetMouseSensitivity (const float Sensitivity) inline
Sets both X and Y axis sensitivity to the supplied value.
Definition at line 467 of file PlayerInput.h.
References SetMouseSensitivity(), and SetMouseSensitivity().
SetMouseSensitivity() [2/2]
void UPlayerInput::SetMouseSensitivity (const float SensitivityX, const float SensitivityY)
Exec function to change the mouse sensitivity.
References SetMouseSensitivity().
SmoothMouse()
virtual float UPlayerInput::SmoothMouse (float aMouse, uint8 & SampleCount, int32 Index) virtual
Smooth mouse movement, because mouse sampling doesn't match up with tick time.
\note : if we got sample event for zero mouse samples (so we didn't have to guess whether a 0 was caused by no sample occuring during the tick (at high frame rates) or because the mouse actually stopped)
Parameters
aMouse is the mouse axis movement received from DirectInput
SampleCount is the number of mouse samples received from DirectInput
Index is 0 for X axis, 1 for Y axis
Returns
the smoothed mouse axis movement
References SmoothMouse().
Tick()
void UPlayerInput::Tick (float DeltaTime)
Per frame tick function.
Primarily for gesture recognition
References Tick().
UpdatePinchStartDistance()
void UPlayerInput::UpdatePinchStartDistance ()
Manually update the GestureRecognizer AnchorDistance using the current locations of the touches.
References UpdatePinchStartDistance().
WasJustPressed()
bool UPlayerInput::WasJustPressed (FKey InKey) const
Returns
true if InKey went from up to down since player input was last processed.
WasJustReleased()
bool UPlayerInput::WasJustReleased (FKey InKey) const
return true if InKey went from down to up since player input was last processed.
Friends And Related Symbol Documentation
UEnhancedPlayerInput
friend class UEnhancedPlayerInput friend
Definition at line 869 of file PlayerInput.h.
References UEnhancedPlayerInput.
Member Data Documentation
ActionMappings
TArray<struct FInputActionKeyMapping> UPlayerInput::ActionMappings
This player's version of the Action Mappings.
Definition at line 447 of file PlayerInput.h.
AxisConfig
TArray<struct FInputAxisConfigEntry> UPlayerInput::AxisConfig
This player's version of the Axis Properties.
Definition at line 444 of file PlayerInput.h.
AxisMappings
TArray<struct FInputAxisKeyMapping> UPlayerInput::AxisMappings
This player's version of Axis Mappings.
Definition at line 450 of file PlayerInput.h.
DebugExecBindings
TArray<struct FKeyBind> UPlayerInput::DebugExecBindings
Generic bindings of keys to Exec()-compatible strings for development purposes only.
Definition at line 441 of file PlayerInput.h.
InvertedAxis
TArray<FName> UPlayerInput::InvertedAxis
List of Axis Mappings that have been inverted.
Definition at line 454 of file PlayerInput.h.
MouseSamples
int32 UPlayerInput::MouseSamples
Current average mouse movement/sample.
Definition at line 431 of file PlayerInput.h.
MouseSamplingTotal
float UPlayerInput::MouseSamplingTotal
Number of mouse samples since mouse movement has been zero.
Definition at line 432 of file PlayerInput.h.
SmoothedMouse
float UPlayerInput::SmoothedMouse[2]
How long received mouse movement has been zero.
Definition at line 430 of file PlayerInput.h.
Touches
FVector UPlayerInput::Touches[EKeys::NUM_TOUCH_KEYS]
Definition at line 423 of file PlayerInput.h.
TouchEventLocations
TMap<uint32, FVector> UPlayerInput::TouchEventLocations
Used to store paired touch locations for event ids during the frame and flushed when processed.
Definition at line 426 of file PlayerInput.h.
ZeroTime
float UPlayerInput::ZeroTime[2]
Definition at line 429 of file PlayerInput.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerInput.h