Unreal Engine 5.6 C++ API: UObjectBaseUtility Class Reference
UObjectBaseUtility Class Reference
Provides utility functions for UObject, this class should not be used directly.
#include "UObjectBaseUtility.h"
Public Member Functions
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Static Public Member Functions
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Static Private Member Functions
template<typename ClassType>
static FORCEINLINE bool IsChildOfWorkaround (const ClassType *ObjClass, const ClassType *TestCls)
Static Private Attributes
static bool bGarbageEliminationEnabled
If true references to objects marked as Garbage will be automatically eliminated by Garbage Collector.
Friends
struct FInternalUObjectBaseUtilityIsValidFlagsChecker
void InitGarbageElimination ()
Additional Inherited Members
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Detailed Description
Provides utility functions for UObject, this class should not be used directly.
Definition at line 44 of file UObjectBaseUtility.h.
Constructor & Destructor Documentation
UObjectBaseUtility() [1/2]
UObjectBaseUtility::UObjectBaseUtility () inline
Definition at line 54 of file UObjectBaseUtility.h.
Referenced by AddToCluster(), GetImplementingOuter(), GetImplementingOuterObject(), GetNativeInterfaceAddress(), and operator<().
UObjectBaseUtility() [2/2]
UObjectBaseUtility::UObjectBaseUtility (EObjectFlags InFlags) inline
Definition at line 55 of file UObjectBaseUtility.h.
References UObjectBase::UObjectBase().
Member Function Documentation
AddToCluster()
void UObjectBaseUtility::AddToCluster (UObjectBaseUtility * ClusterRootOrObjectFromCluster, bool bAddAsMutableObject = false)
Adds this objects to a GC cluster that already exists.
Parameters
ClusterRootOrObjectFromCluster Object that belongs to the cluster we want to add this object to.
Add this object to the target cluster as a mutable object without adding this object's references.
References UObjectBaseUtility().
AddToRoot()
FORCEINLINE void UObjectBaseUtility::AddToRoot () inline
Add an object to the root set.
This prevents the object and all its descendants from being deleted during garbage collection.
Definition at line 206 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, and UObjectBase::InternalIndex.
Referenced by ConstructorHelpersInternal::FindOrLoadClass().
AppendName()
FORCEINLINE void UObjectBaseUtility::AppendName (FString & ResultString) const inline
Optimized version of GetName that appends to an existing string.
Definition at line 440 of file UObjectBaseUtility.h.
References FName::AppendString(), FORCEINLINE, and UObjectBase::GetFName().
AtomicallyClearInternalFlags()
FORCEINLINE bool UObjectBaseUtility::AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const inline
Atomically clears passed in internal flags.
Parameters
FlagsToClear Object flags to clear.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 303 of file UObjectBaseUtility.h.
References checkf, FORCEINLINE, Garbage, FUObjectItem::GetFlags(), GUObjectArray, UObjectBase::InternalIndex, None, TEXT, and FUObjectItem::ThisThreadAtomicallyClearedFlag().
Referenced by MarkAsGarbage().
CanBeClusterRoot()
virtual bool UObjectBaseUtility::CanBeClusterRoot () const inline virtual
Called after load to determine if the object can be a cluster root.
Returns
true if this object can be a cluster root
Definition at line 386 of file UObjectBaseUtility.h.
CanBeInCluster()
virtual bool UObjectBaseUtility::CanBeInCluster () const virtual
Called during cluster construction if the object can be added to a cluster.
Returns
true if this object can be inside of a cluster
ClearFlags()
FORCEINLINE void UObjectBaseUtility::ClearFlags (EObjectFlags FlagsToClear) inline
Clears subset of flags for a specific object.
Definition at line 74 of file UObjectBaseUtility.h.
References UObjectBase::AtomicallyClearFlags(), checkf, checkSlow, FORCEINLINE, UObjectBase::GetFlags(), RF_AllFlags, RF_MarkAsNative, RF_MarkAsRootSet, RF_MirroredGarbage, RF_NoFlags, and TEXT.
Referenced by UPackage::MarkAsUnloaded().
ClearGarbage()
FORCEINLINE void UObjectBaseUtility::ClearGarbage () inline
Unmarks this object as Garbage.
Definition at line 196 of file UObjectBaseUtility.h.
References UObjectBase::AtomicallyClearFlags(), FORCEINLINE, GUObjectArray, UObjectBase::InternalIndex, and RF_MirroredGarbage.
ClearInternalFlags()
FORCEINLINE void UObjectBaseUtility::ClearInternalFlags (EInternalObjectFlags FlagsToClear) const inline
Clears passed in internal flags.
Parameters
FlagsToClear Object flags to clear.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 290 of file UObjectBaseUtility.h.
References checkf, FUObjectItem::ClearFlags(), FORCEINLINE, Garbage, FUObjectItem::GetFlags(), GUObjectArray, UObjectBase::InternalIndex, None, and TEXT.
CreateCluster()
virtual void UObjectBaseUtility::CreateCluster () virtual
Called after PostLoad to create UObject cluster.
DetachExternalPackage()
void UObjectBaseUtility::DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
FindNearestCommonBaseClass()
const UClass * UObjectBaseUtility::FindNearestCommonBaseClass (const UClass * TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
Parameters
TestClass the class to find the common base for
GetAllMarks()
FORCEINLINE EObjectMark UObjectBaseUtility::GetAllMarks () const inline
Returns all of the object marks on a specific object.
Parameters
Object Object to get marks for
Returns
all Marks for an object
Definition at line 168 of file UObjectBaseUtility.h.
References FORCEINLINE, and ObjectGetAllMarks().
GetFullGroupName()
FString UObjectBaseUtility::GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
Parameters
bStartWithOuter whether to include this object's name in the returned string
Returns
string containing the path name for this object, minus the outermost-package's name
GetFullName() [1/3]
void UObjectBaseUtility::GetFullName (const UObject * StopOuter, FString & ResultString, EObjectFullNameFlags Flags = EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
References Flags, and None.
GetFullName() [2/3]
FString UObjectBaseUtility::GetFullName (const UObject * StopOuter = NULL, EObjectFullNameFlags Flags = EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
Parameters
StopOuter if specified, indicates that the output string should be relative to this object. if StopOuter does not exist in this object's Outer chain, the result would be the same as passing NULL.
Flags flags that control the behavior of full name generation
Note
safe to call on NULL object pointers!
References Flags, and None.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext(), FindFieldChecked(), and UObject::SetNetPushIdDynamic().
GetFullName() [3/3]
void UObjectBaseUtility::GetFullName (FStringBuilderBase & ResultString, const UObject * StopOuter = NULL, EObjectFullNameFlags Flags = EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
Parameters
ResultString StringBuilder to populate
StopOuter if specified, indicates that the output string should be relative to this object. if StopOuter does not exist in this object's Outer chain, the result would be the same as passing NULL.
Flags flags that control the behavior of full name generation
Note
safe to call on NULL object pointers!
References Flags, and None.
GetImplementingOuter()
template<typename InterfaceClassType> InterfaceClassType * UObjectBaseUtility::GetImplementingOuter () const inline
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
Returns
a pointer to the interface on the first object in this object's Outer chain which implements the specified interface.
Definition at line 538 of file UObjectBaseUtility.h.
References UObjectBaseUtility(), and GetImplementingOuterObject().
GetImplementingOuterObject()
UObjectBaseUtility * UObjectBaseUtility::GetImplementingOuterObject (const UClass * InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
Parameters
InInterfaceClass Target interface to search for
Returns
a pointer to the first object in this object's Outer chain which implements the specified interface.
References UObjectBaseUtility().
Referenced by GetImplementingOuter().
GetInterfaceAddress()
void * UObjectBaseUtility::GetInterfaceAddress (UClass * InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
Parameters
InterfaceClass the interface class to use for the returned type
Returns
a pointer that can be assigned to a variable of the interface type specified, or NULL if this object's class doesn't implement the interface indicated. Will be the same value as 'this' if the interface class isn't native.
Referenced by Cast(), and CastChecked().
GetInternalFlags()
FORCEINLINE EInternalObjectFlags UObjectBaseUtility::GetInternalFlags () const inline
Gets internal flags.
Parameters
FlagsToClear Object flags to clear.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 268 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, and UObjectBase::InternalIndex.
GetLinker()
class FLinkerLoad * UObjectBaseUtility::GetLinker () const
Returns the linker for this object.
Returns
a pointer to the linker for this object, or NULL if this object has no linker
GetLinkerCustomVersion()
int32 UObjectBaseUtility::GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
Returns
the custom version of the engine's package file when this object was last saved, or the current version if this object does not have a linker, which indicates that a) this object is a native only class, or b) this object's linker has been detached, in which case it is already fully loaded
GetLinkerIndex()
int32 UObjectBaseUtility::GetLinkerIndex () const
Returns this object's LinkerIndex.
Returns
the index into my linker's ExportMap for the FObjectExport corresponding to this object.
GetLinkerLicenseeUEVersion()
int32 UObjectBaseUtility::GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
Returns
the licensee version of the engine's package file when this object was last saved, or GPackageFileLicenseeVersion (current version) if this object does not have a linker, which indicates that a) this object is a native only class, or b) this object's linker has been detached, in which case it is already fully loaded
Referenced by UE_DEPRECATED().
GetLinkerUEVersion()
FPackageFileVersion UObjectBaseUtility::GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
Returns
the UE version of the engine's package file when this object was last saved, or GPackageFileUEVersion (current version) if this object does not have a linker, which indicates that a) this object is a native only class, or b) this object's linker has been detached, in which case it is already fully loaded
Referenced by UE_DEPRECATED().
GetMaskedFlags()
FORCEINLINE EObjectFlags UObjectBaseUtility::GetMaskedFlags (EObjectFlags Mask = RF_AllFlags) const inline
Returns object flags that are both in the mask and set on the object.
Parameters
Mask Mask to mask object flags with
Objects flags that are set in both the object and the mask
Definition at line 111 of file UObjectBaseUtility.h.
References FORCEINLINE, UObjectBase::GetFlags(), Mask, and RF_AllFlags.
GetName() [1/2]
FORCEINLINE FString UObjectBaseUtility::GetName () const inline
Returns the name of this object (with no path information)
Returns
Name of the object.
Definition at line 429 of file UObjectBaseUtility.h.
References FORCEINLINE, UObjectBase::GetFName(), and FName::ToString().
Referenced by FClassTree::AddChildNode(), IAnimationDataController::CheckOuterClass(), UProperty::ContainerUObjectPtrToValuePtrInternal(), BlueprintNodeHelpers::GetNodeName(), FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), FActorPartitionIdentifier::GetTypeHash, TStructOnScope< T >::InitializeFromChecked(), FTrackInstancePropertyBindings::InvokeSetterFunction(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), and operator<().
GetName() [2/2]
FORCEINLINE void UObjectBaseUtility::GetName (FString & ResultString) const inline
Optimized version of GetName that overwrites an existing string.
Definition at line 435 of file UObjectBaseUtility.h.
References FORCEINLINE, UObjectBase::GetFName(), and FName::ToString().
GetNativeInterfaceAddress() [1/2]
void * UObjectBaseUtility::GetNativeInterfaceAddress (UClass * InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
Returns NULL if this object does not implement InterfaceClass, or does not do so natively.
Referenced by GetNativeInterfaceAddress().
GetNativeInterfaceAddress() [2/2]
const void * UObjectBaseUtility::GetNativeInterfaceAddress (UClass * InterfaceClass) const inline
Returns a pointer to the const I* native interface object that this object implements.
Returns NULL if this object does not implement InterfaceClass, or does not do so natively.
Definition at line 659 of file UObjectBaseUtility.h.
References UObjectBaseUtility(), and GetNativeInterfaceAddress().
GetOutermost()
UPackage * UObjectBaseUtility::GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
Returns
the package the object is in.
See also
GetPackage
Referenced by FCookTagList::Add(), and FExclusiveLoadPackageTimeTracker::PushPostLoad().
GetOutermostObject()
UObject * UObjectBaseUtility::GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
Will return null if called on a package
Returns
outermost non package Outer.
Referenced by FArchiveReplaceOrClearExternalReferences< T >::operator<<().
GetPackage()
UPackage * UObjectBaseUtility::GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
Returns
the package the object is in.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages(), and FArchiveReplaceOrClearExternalReferences< T >::operator<<().
GetPathName() [1/3]
void UObjectBaseUtility::GetPathName (const UObject * StopOuter, FString & ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
GetPathName() [2/3]
void UObjectBaseUtility::GetPathName (const UObject * StopOuter, FStringBuilderBase & ResultString) const
GetPathName() [3/3]
FString UObjectBaseUtility::GetPathName (const UObject * StopOuter = NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
Parameters
StopOuter if specified, indicates that the output string should be relative to this object. if StopOuter does not exist in this object's Outer chain, the result would be the same as passing NULL.
Note
safe to call on NULL object pointers!
Referenced by AWorldDataLayers::CreateDataLayer(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::FindThumbnailScene(), UScriptStruct::GetCppStructOps(), FGameModeInfoCustomizer::GetCurrentGameModeClass(), FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull(), FGameModeInfoCustomizer::OnUseSelectedGameModeClicked(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::RemoveThumbnailScene(), FGameModeInfoCustomizer::SetCurrentGameModeClass(), and FDisplayClusterActorRef::SetSceneActor().
GetStatID()
FORCEINLINE TStatId UObjectBaseUtility::GetStatID (bool bForDeferredUse = false) const inline
Returns the stat ID of the object, used for profiling.
This will create a stat ID if needed.
Parameters
bForDeferred If true, a stat ID will be created even if a group is disabled
Definition at line 780 of file UObjectBaseUtility.h.
References FORCEINLINE, GCycleStatsShouldEmitNamedEvents, GET_STATID, GUObjectArray, and UObjectBase::InternalIndex.
GetTypedOuter() [1/2]
template<typename T> T * UObjectBaseUtility::GetTypedOuter () const inline
Traverses the outer chain searching for the next object of a certain type.
(T must be derived from UObject)
Returns
a pointer to the first object in this object's Outer chain which is of the correct type.
Definition at line 527 of file UObjectBaseUtility.h.
References GetTypedOuter().
Referenced by GetTypedOuter().
GetTypedOuter() [2/2]
UObject * UObjectBaseUtility::GetTypedOuter (UClass * Target) const
Traverses the outer chain searching for the next object of a certain type.
(T must be derived from UObject)
Parameters
Target class to search for
Returns
a pointer to the first object in this object's Outer chain which is of the correct type.
References Target.
Referenced by FCurveModel::GetOwningObjectOrOuter().
GetVersePath()
virtual UE_INTERNAL UE::Core::FVersePath UObjectBaseUtility::GetVersePath () const virtual
Gets the versepath of the UObject.
Returns
The VersePath of the object
References UE_INTERNAL.
HasAllFlags()
FORCEINLINE bool UObjectBaseUtility::HasAllFlags (EObjectFlags FlagsToCheck) const inline
Used to safely check whether all of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for
Returns
true if all of the passed in flags are set (including no flags passed in), false otherwise
Definition at line 99 of file UObjectBaseUtility.h.
References checkSlow, FORCEINLINE, UObjectBase::GetFlags(), RF_AllFlags, RF_MarkAsNative, and RF_MarkAsRootSet.
HasAllMarks()
FORCEINLINE bool UObjectBaseUtility::HasAllMarks (EObjectMark Marks) const inline
Tests an object for having ALL of a set of marks.
Parameters
Marks Logical OR of OBJECTMARK_'s to test
Returns
true if the object has any of the given marks.
Definition at line 157 of file UObjectBaseUtility.h.
References FORCEINLINE, and ObjectHasAllMarks().
HasAnyFlags()
FORCEINLINE bool UObjectBaseUtility::HasAnyFlags (EObjectFlags FlagsToCheck) const inline
Used to safely check whether any of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 87 of file UObjectBaseUtility.h.
References checkSlow, FORCEINLINE, UObjectBase::GetFlags(), RF_AllFlags, RF_MarkAsNative, and RF_MarkAsRootSet.
Referenced by FReferenceGraphNode::GetObjectToDisplay(), UPhysicsCollisionHandler::GetWorld(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FArchiveReplaceOrClearExternalReferences< T >::operator<<(), FComponentEditorUtils::PropagateDefaultValueChange(), and USTRUCT().
HasAnyInternalFlags()
FORCEINLINE bool UObjectBaseUtility::HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const inline
Used to safely check whether any of the passed in internal flags are set.
Parameters
FlagsToCheck Object flags to check for.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 279 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, and UObjectBase::InternalIndex.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::CanCacheObjectPointer(), and FPropertyReferenceCollector::HandleObjectReference().
HasAnyMarks()
FORCEINLINE bool UObjectBaseUtility::HasAnyMarks (EObjectMark Marks) const inline
Tests an object for having ANY of a set of marks.
Parameters
Marks Logical OR of OBJECTMARK_'s to test
Returns
true if the object has any of the given marks.
Definition at line 146 of file UObjectBaseUtility.h.
References FORCEINLINE, and ObjectHasAnyMarks().
IsA() [1/2]
template<class T> bool UObjectBaseUtility::IsA () const inline
Returns true if this object is of the template type.
Definition at line 626 of file UObjectBaseUtility.h.
References IsA().
Referenced by UProperty::ContainerUObjectPtrToValuePtrInternal(), UClass::IsA(), and IsA().
IsA() [2/2]
template<typename OtherClassType> FORCEINLINE bool UObjectBaseUtility::IsA (OtherClassType SomeBase) const inline
Returns true if this object is of the specified type.
Definition at line 605 of file UObjectBaseUtility.h.
References checkfSlow, FORCEINLINE, UObjectBase::GetClass(), IsChildOfWorkaround(), TEXT, and UE_ASSUME.
Referenced by UClass::AddDefaultSubobject(), IMovieSceneObjectSpawner::CanSetupDefaultsForSpawnable(), UClass::GetDefaultObject(), FReferenceGraphNode::GetObjectToDisplay(), Verse::FNativeTypeBase::IsTypeOf(), FSequencerTrackFilter_ComponentType< InComponentType >::PassesFilter(), and FDocumentTabFactoryForObjects< BaseClass >::SupportsObjectType().
IsChildOfWorkaround()
template<typename ClassType> FORCEINLINE bool UObjectBaseUtility::IsChildOfWorkaround (const ClassType * ObjClass, const ClassType * TestCls) inline static private
Definition at line 597 of file UObjectBaseUtility.h.
References FORCEINLINE.
Referenced by IsA().
IsDefaultSubobject()
bool UObjectBaseUtility::IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
This will return true for all instanced objects created from an archetype that is not a class default object, but will only return true for template objects nested directly inside a class default object.
Warning
The behavior of this function is inconsistent for historical reasons and is not equivalent to RF_DefaultSubobject. Call IsTemplateSubobject to handle all types of subobject templates, or call GetArchetype() first if you have an instance.
Returns
true if this was instanced from a subobject template, or is the direct subobject of a class default object
IsGarbageEliminationEnabled()
bool UObjectBaseUtility::IsGarbageEliminationEnabled () inline static
Helper function to access the private bGarbageEliminationEnabled variable.
Definition at line 363 of file UObjectBaseUtility.h.
References bGarbageEliminationEnabled.
Referenced by UE_DEPRECATED().
IsIn() [1/2]
bool UObjectBaseUtility::IsIn (const UObject * SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
Legacy function, preferably use IsInOuter or IsInPackage depending on use case.
Referenced by TFindObjectReferencers< T >::TFindObjectReferencers().
IsIn() [2/2]
bool UObjectBaseUtility::IsIn (const UPackage * SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
Calls IsInPackage.
IsInA()
bool UObjectBaseUtility::IsInA (const UClass * SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
Parameters
SomeBaseClass The base class to compare against
Returns
True if this object is in an object of the given type.
IsInOuter()
bool UObjectBaseUtility::IsInOuter (const UObject * SomeOuter) const
Returns true if the object is contained in the specified outer.
IsInPackage()
bool UObjectBaseUtility::IsInPackage (const UPackage * SomePackage) const
Returns true if the object is contained in the specified package.
IsNative()
FORCEINLINE bool UObjectBaseUtility::IsNative () const inline
Checks if the object is native.
Definition at line 242 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, UObjectBase::InternalIndex, and Native.
Referenced by TActorDescViewMap< Type >::FindByExactNativeClass().
IsPackageExternal()
bool UObjectBaseUtility::IsPackageExternal () const
Get the object packaging mode.
Returns
true if object has a different package than its outer's package
IsRooted()
FORCEINLINE bool UObjectBaseUtility::IsRooted () const inline
Returns true if this object is explicitly rooted.
Returns
true if the object was explicitly added as part of the root set.
Definition at line 222 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, and UObjectBase::InternalIndex.
Referenced by MarkAsGarbage().
IsTemplate()
bool UObjectBaseUtility::IsTemplate (EObjectFlags TemplateTypes = RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
Parameters
TemplateTypes Specific flags to look for, the default checks class default and non-class templates
Returns
true if this object is a template object that can be used as an archetype
References RF_ArchetypeObject, and RF_ClassDefaultObject.
Referenced by TFindObjectReferencers< T >::TFindObjectReferencers().
IsTemplateForSubobjects()
bool UObjectBaseUtility::IsTemplateForSubobjects (EObjectFlags TemplateTypes = RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
By default this includes subobjects of a class default object and other templates associated with a class.
Parameters
TemplateTypes Specific flags to check on this object and the outer chain
Returns
true if this is a template for creating instanced subobjects
References RF_ClassDefaultObject, RF_DefaultSubObject, and RF_InheritableComponentTemplate.
IsUnreachable()
FORCEINLINE bool UObjectBaseUtility::IsUnreachable () const inline
Checks if the object is unreachable.
Definition at line 236 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, UObjectBase::InternalIndex, and IsUnreachable().
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext(), UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage(), and IsUnreachable().
Mark()
FORCEINLINE void UObjectBaseUtility::Mark (EObjectMark Marks) const inline
Adds marks to an object.
Parameters
Marks Logical OR of OBJECTMARK_'s to apply
Definition at line 125 of file UObjectBaseUtility.h.
References FORCEINLINE, and MarkObject().
MarkAsGarbage()
FORCEINLINE void UObjectBaseUtility::MarkAsGarbage () inline
Marks this object as Garbage.
Definition at line 176 of file UObjectBaseUtility.h.
References Async, AtomicallyClearInternalFlags(), UObjectBase::AtomicallySetFlags(), check, FORCEINLINE, GUObjectArray, UObjectBase::InternalIndex, IsRooted(), and RF_MirroredGarbage.
MarkPackageDirty()
bool UObjectBaseUtility::MarkPackageDirty () const
Finds the outermost package and marks it dirty.
The editor suppresses this behavior during load as it is against policy to dirty packages simply by loading them.
Returns
false if the request to mark the package dirty was suppressed by the editor and true otherwise.
OnClusterMarkedAsPendingKill()
virtual void UObjectBaseUtility::OnClusterMarkedAsPendingKill () inline virtual
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
Definition at line 406 of file UObjectBaseUtility.h.
operator<()
FORCEINLINE bool UObjectBaseUtility::operator< (const UObjectBaseUtility & Other) const inline
Overloaded < operator.
Compares objects by name.
Returns
true if this object's name is lexicographically smaller than the other object's name
Definition at line 756 of file UObjectBaseUtility.h.
References UObjectBaseUtility(), FORCEINLINE, GetName(), and Other.
ReattachExternalPackage()
void UObjectBaseUtility::ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
ReloadObjectsFromModifiedConfigSections()
void UObjectBaseUtility::ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker * ChangeTracker) static
RemoveFromRoot()
FORCEINLINE void UObjectBaseUtility::RemoveFromRoot () inline
Remove an object from the root set.
Definition at line 212 of file UObjectBaseUtility.h.
References FORCEINLINE, GUObjectArray, and UObjectBase::InternalIndex.
RootPackageHasAnyFlags()
bool UObjectBaseUtility::RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
Parameters
CheckFlagMask a bitmask of EPackageFlags values to check for
Returns
true if the PackageFlags member of this object's top-package has any bits from the mask set.
SetFlags()
FORCEINLINE void UObjectBaseUtility::SetFlags (EObjectFlags NewFlags) inline
Modifies object flags for a specific object.
Definition at line 66 of file UObjectBaseUtility.h.
References UObjectBase::AtomicallySetFlags(), checkf, checkSlow, FORCEINLINE, UObjectBase::GetFlags(), RF_MarkAsNative, RF_MarkAsRootSet, RF_MirroredGarbage, and TEXT.
Referenced by FComponentEditorUtils::ApplyDefaultValueChange(), and FExternalPackageHelper::LoadObjectsFromExternalPackages().
SetGarbageEliminationEnabled()
void UObjectBaseUtility::SetGarbageEliminationEnabled (bool bEnabled) inline static
Helper function to set the private bGarbageEliminationEnabled variable.
Definition at line 375 of file UObjectBaseUtility.h.
References bGarbageEliminationEnabled.
SetInternalFlags()
FORCEINLINE void UObjectBaseUtility::SetInternalFlags (EInternalObjectFlags FlagsToSet) const inline
Clears passed in internal flags.
Parameters
FlagsToClear Object flags to clear.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 253 of file UObjectBaseUtility.h.
References checkf, FORCEINLINE, Garbage, FUObjectItem::GetFlags(), GUObjectArray, UObjectBase::InternalIndex, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, FUObjectItem::SetFlags(), and TEXT.
UE_DEPRECATED() [1/4]
UObjectBaseUtility::UE_DEPRECATED (5. 0, "Use GetLinkerLicenseeUEVersion instead") const inline
Definition at line 736 of file UObjectBaseUtility.h.
References GetLinkerLicenseeUEVersion().
UE_DEPRECATED() [2/4]
UObjectBaseUtility::UE_DEPRECATED (5. 0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") const inline
Definition at line 716 of file UObjectBaseUtility.h.
References FPackageFileVersion::FileVersionUE4, and GetLinkerUEVersion().
UE_DEPRECATED() [3/4]
UObjectBaseUtility::UE_DEPRECATED (5. 4, "Use IsGarbageEliminationEnabled()") inline
Definition at line 368 of file UObjectBaseUtility.h.
References IsGarbageEliminationEnabled().
UE_DEPRECATED() [4/4]
UObjectBaseUtility::UE_DEPRECATED (5. 5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.")
Atomically clear the unreachable flag.
Returns
true if we are the thread that cleared RF_Unreachable
References bool.
UnMark()
FORCEINLINE void UObjectBaseUtility::UnMark (EObjectMark Marks) const inline
Removes marks from and object.
Parameters
Marks Logical OR of OBJECTMARK_'s to remove
Definition at line 135 of file UObjectBaseUtility.h.
References FORCEINLINE, and UnMarkObject().
Friends And Related Symbol Documentation
FInternalUObjectBaseUtilityIsValidFlagsChecker
friend struct FInternalUObjectBaseUtilityIsValidFlagsChecker friend
Definition at line 50 of file UObjectBaseUtility.h.
References FInternalUObjectBaseUtilityIsValidFlagsChecker.
Referenced by FInternalUObjectBaseUtilityIsValidFlagsChecker.
InitGarbageElimination
void InitGarbageElimination () friend
Field Documentation
bGarbageEliminationEnabled
bool UObjectBaseUtility::bGarbageEliminationEnabled static private
If true references to objects marked as Garbage will be automatically eliminated by Garbage Collector.
Definition at line 47 of file UObjectBaseUtility.h.
Referenced by IsGarbageEliminationEnabled(), and SetGarbageEliminationEnabled().
The documentation for this class was generated from the following file:
UObjectBaseUtility.h