Unreal Engine 5.6 C++ API: FAndroidWindow::FNativeAccessor Class Reference
FAndroidWindow::FNativeAccessor Class Reference
#include "AndroidWindow.h"
Public Member Functions
FNativeAccessor (bool bWriteAccessIn, FAndroidWindow *ProtectedObjIn)
FNativeAccessor (const FNativeAccessor &)=delete
FNativeAccessor (FNativeAccessor &&obj)
~FNativeAccessor ()
FAndroidWindow * Get ()
const FAndroidWindow * Get () const
ANativeWindow * GetANativeWindow () const
ANativeWindow * GetPreviousANativeWindow () const
FAndroidWindow * operator-> ()
const FAndroidWindow * operator-> () const
void SetANativeWindow (ANativeWindow *ANativeHandle)
Private Member Functions
FNativeAccessor ()
Private Attributes
bool bWriteAccess
class FAndroidWindow * ProtectedObj = nullptr
Detailed Description
Definition at line 79 of file AndroidWindow.h.
Constructor & Destructor Documentation
FNativeAccessor() [1/4]
FAndroidWindow::FNativeAccessor::FNativeAccessor () inline private
Definition at line 83 of file AndroidWindow.h.
Referenced by FNativeAccessor(), and FNativeAccessor().
FNativeAccessor() [2/4]
FAndroidWindow::FNativeAccessor::FNativeAccessor (FNativeAccessor && obj) inline
Definition at line 85 of file AndroidWindow.h.
References FNativeAccessor(), bWriteAccess, and ProtectedObj.
FNativeAccessor() [3/4]
FAndroidWindow::FNativeAccessor::FNativeAccessor (const FNativeAccessor &) delete
References FNativeAccessor().
FNativeAccessor() [4/4]
FAndroidWindow::FNativeAccessor::FNativeAccessor (bool bWriteAccessIn, FAndroidWindow * ProtectedObjIn) inline
Definition at line 93 of file AndroidWindow.h.
References FAndroidWindow::FAndroidWindow(), bWriteAccess, and ProtectedObj.
~FNativeAccessor()
FAndroidWindow::FNativeAccessor::~FNativeAccessor () inline
Definition at line 105 of file AndroidWindow.h.
References bWriteAccess, and ProtectedObj.
Member Function Documentation
Get() [1/2]
FAndroidWindow * FAndroidWindow::FNativeAccessor::Get () inline
Definition at line 120 of file AndroidWindow.h.
References FAndroidWindow::FAndroidWindow(), and ProtectedObj.
Referenced by operator->(), and operator->().
Get() [2/2]
const FAndroidWindow * FAndroidWindow::FNativeAccessor::Get () const inline
Definition at line 121 of file AndroidWindow.h.
References FAndroidWindow::FAndroidWindow(), and ProtectedObj.
GetANativeWindow()
ANativeWindow * FAndroidWindow::FNativeAccessor::GetANativeWindow () const inline
Definition at line 132 of file AndroidWindow.h.
References ProtectedObj.
Referenced by FAndroidWindowManager::FindFromANativeWindow().
GetPreviousANativeWindow()
ANativeWindow * FAndroidWindow::FNativeAccessor::GetPreviousANativeWindow () const inline
Definition at line 133 of file AndroidWindow.h.
References ProtectedObj.
Referenced by FAndroidWindowManager::FindFromANativeWindow().
operator->() [1/2]
FAndroidWindow * FAndroidWindow::FNativeAccessor::operator-> () inline
Definition at line 123 of file AndroidWindow.h.
References FAndroidWindow::FAndroidWindow(), and Get().
operator->() [2/2]
const FAndroidWindow * FAndroidWindow::FNativeAccessor::operator-> () const inline
Definition at line 124 of file AndroidWindow.h.
References FAndroidWindow::FAndroidWindow(), and Get().
SetANativeWindow()
void FAndroidWindow::FNativeAccessor::SetANativeWindow (ANativeWindow * ANativeHandle) inline
Definition at line 126 of file AndroidWindow.h.
References bWriteAccess, check, and ProtectedObj.
Field Documentation
bWriteAccess
bool FAndroidWindow::FNativeAccessor::bWriteAccess private
Definition at line 81 of file AndroidWindow.h.
Referenced by FNativeAccessor(), FNativeAccessor(), ~FNativeAccessor(), and SetANativeWindow().
ProtectedObj
class FAndroidWindow* FAndroidWindow::FNativeAccessor::ProtectedObj = nullptr private
Definition at line 82 of file AndroidWindow.h.
Referenced by FNativeAccessor(), FNativeAccessor(), ~FNativeAccessor(), Get(), Get(), GetANativeWindow(), GetPreviousANativeWindow(), and SetANativeWindow().
The documentation for this class was generated from the following file:
AndroidWindow.h