Unreal Engine 5.6 C++ API: Metasound::TArrayShuffleOperator< ArrayType > Class Template Reference
Metasound::TArrayShuffleOperator< ArrayType > Class Template Reference
TArrayShuffleOperator shuffles an array on trigger and outputs values sequentially on "next".
#include "MetasoundArrayShuffleNode.h"
Public Types
using ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
using FArrayDataReadReference = TDataReadReference<ArrayType>
using FElementTypeWriteReference = TDataWriteReference<ElementType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArrayShuffleOperator (const FBuildOperatorParams &InParams, const TDataReadReference< FTrigger > &InTriggerNext, const TDataReadReference< FTrigger > &InTriggerShuffle, const TDataReadReference< FTrigger > &InTriggerReset, const FArrayDataReadReference &InInputArray, const TDataReadReference< int32 > &InSeedValue, const TDataReadReference< bool > &bInAutoShuffle, const TDataReadReference< bool > &bInEnableSharedState)
virtual ~TArrayShuffleOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArrayShuffleOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Member Functions
bool GetNextIndex (int32 &OutIndex)
void InitializeShufflers (int32 InSize)
void Reset ()
void Seed (int32 InNewSeed)
void Shuffle ()
Private Attributes
TUniquePtr< FArrayIndexShuffler > ArrayIndexShuffler
TDataReadReference< bool > bAutoShuffle
TDataReadReference< bool > bEnableSharedState
FArrayDataReadReference InputArray
TDataWriteReference< ElementType > OutValue
int32 PrevArraySize = 0
int32 PrevSeedValue = INDEX_NONE
TDataReadReference< int32 > SeedValue
uint32 SharedStateUniqueId = INDEX_NONE
TDataReadReference< FTrigger > TriggerNext
TDataWriteReference< FTrigger > TriggerOnShuffle
TDataReadReference< FTrigger > TriggerReset
TDataReadReference< FTrigger > TriggerShuffle
Detailed Description
template<typename ArrayType>
class Metasound::TArrayShuffleOperator< ArrayType >
TArrayShuffleOperator shuffles an array on trigger and outputs values sequentially on "next".
It avoids repeating shuffled elements and supports auto-shuffling.
Definition at line 138 of file MetasoundArrayShuffleNode.h.
Member Typedef Documentation
ElementType
template<typename ArrayType> using Metasound::TArrayShuffleOperator< ArrayType >::ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
Definition at line 142 of file MetasoundArrayShuffleNode.h.
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArrayShuffleOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 141 of file MetasoundArrayShuffleNode.h.
FElementTypeWriteReference
template<typename ArrayType> using Metasound::TArrayShuffleOperator< ArrayType >::FElementTypeWriteReference = TDataWriteReference<ElementType>
Definition at line 143 of file MetasoundArrayShuffleNode.h.
Constructor & Destructor Documentation
TArrayShuffleOperator()
template<typename ArrayType> Metasound::TArrayShuffleOperator< ArrayType >::TArrayShuffleOperator (const FBuildOperatorParams & InParams, const TDataReadReference< FTrigger > & InTriggerNext, const TDataReadReference< FTrigger > & InTriggerShuffle, const TDataReadReference< FTrigger > & InTriggerReset, const FArrayDataReadReference & InInputArray, const TDataReadReference< int32 > & InSeedValue, const TDataReadReference< bool > & bInAutoShuffle, const TDataReadReference< bool > & bInEnableSharedState) inline
Definition at line 206 of file MetasoundArrayShuffleNode.h.
References bAutoShuffle, bEnableSharedState, InputArray, OutValue, Reset, SeedValue, TriggerNext, TriggerOnShuffle, TriggerReset, and TriggerShuffle.
~TArrayShuffleOperator()
template<typename ArrayType> virtual Metasound::TArrayShuffleOperator< ArrayType >::~TArrayShuffleOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArrayShuffleOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 230 of file MetasoundArrayShuffleNode.h.
References bAutoShuffle, bEnableSharedState, Metasound::FInputVertexInterfaceData::BindReadVertex(), InputArray, METASOUND_GET_PARAM_NAME, SeedValue, TriggerNext, TriggerReset, and TriggerShuffle.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArrayShuffleOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 243 of file MetasoundArrayShuffleNode.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, OutValue, TriggerNext, TriggerOnShuffle, and TriggerReset.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArrayShuffleOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 188 of file MetasoundArrayShuffleNode.h.
References Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
Execute()
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::Execute () inline
Definition at line 288 of file MetasoundArrayShuffleNode.h.
References EndFrame, GetNextIndex(), INDEX_NONE, InitializeShufflers(), InputArray, OutValue, PrevArraySize, PrevSeedValue, Reset, Seed, SeedValue, Shuffle(), TriggerNext, TriggerOnShuffle, TriggerReset, and TriggerShuffle.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArrayShuffleOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 145 of file MetasoundArrayShuffleNode.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayShuffleOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 253 of file MetasoundArrayShuffleNode.h.
References checkNoEntry.
GetNextIndex()
template<typename ArrayType> bool Metasound::TArrayShuffleOperator< ArrayType >::GetNextIndex (int32 & OutIndex) inline private
Definition at line 402 of file MetasoundArrayShuffleNode.h.
References ArrayIndexShuffler, bAutoShuffle, bEnableSharedState, checkNoEntry, Metasound::FSharedStateShuffleManager::Get(), INDEX_NONE, Metasound::FSharedStateShuffleManager::NextValue(), and SharedStateUniqueId.
Referenced by Execute().
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArrayShuffleOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 170 of file MetasoundArrayShuffleNode.h.
References Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metadata, METASOUND_LOCTEXT, and METASOUND_LOCTEXT_FORMAT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayShuffleOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 261 of file MetasoundArrayShuffleNode.h.
References checkNoEntry.
InitializeShufflers()
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::InitializeShufflers (int32 InSize) inline private
Definition at line 356 of file MetasoundArrayShuffleNode.h.
References ArrayIndexShuffler, Metasound::FSharedStateShuffleManager::Get(), INDEX_NONE, Metasound::FSharedStateShuffleManager::InitSharedState(), MakeUnique(), PrevArraySize, PrevSeedValue, and SharedStateUniqueId.
Referenced by Execute(), and Reset().
Reset() [1/2]
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::Reset () inline private
Definition at line 388 of file MetasoundArrayShuffleNode.h.
References ArrayIndexShuffler, Metasound::FSharedStateShuffleManager::Get(), INDEX_NONE, Metasound::FSharedStateShuffleManager::ResetSeed(), and SharedStateUniqueId.
Reset() [2/2]
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 269 of file MetasoundArrayShuffleNode.h.
References Metasound::FMetasoundEnvironment::Contains(), Metasound::TDataFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateAny(), Metasound::IOperator::FResetParams::Environment, Metasound::FMetasoundEnvironment::GetValue(), INDEX_NONE, InitializeShufflers(), InputArray, Metasound::IOperator::FResetParams::OperatorSettings, OutValue, PrevSeedValue, SeedValue, SharedStateUniqueId, and TriggerOnShuffle.
Seed()
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::Seed (int32 InNewSeed) inline private
Definition at line 372 of file MetasoundArrayShuffleNode.h.
References ArrayIndexShuffler, Metasound::FSharedStateShuffleManager::Get(), INDEX_NONE, PrevSeedValue, Metasound::FSharedStateShuffleManager::SetSeed(), and SharedStateUniqueId.
Shuffle()
template<typename ArrayType> void Metasound::TArrayShuffleOperator< ArrayType >::Shuffle () inline private
Definition at line 421 of file MetasoundArrayShuffleNode.h.
References ArrayIndexShuffler, Metasound::FSharedStateShuffleManager::Get(), INDEX_NONE, SharedStateUniqueId, and Metasound::FSharedStateShuffleManager::ShuffleArray().
Referenced by Execute().
Field Documentation
ArrayIndexShuffler
template<typename ArrayType> TUniquePtr<FArrayIndexShuffler> Metasound::TArrayShuffleOperator< ArrayType >::ArrayIndexShuffler private
Definition at line 449 of file MetasoundArrayShuffleNode.h.
Referenced by GetNextIndex(), InitializeShufflers(), Reset(), Seed(), and Shuffle().
bAutoShuffle
template<typename ArrayType> TDataReadReference<bool> Metasound::TArrayShuffleOperator< ArrayType >::bAutoShuffle private
Definition at line 441 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), and GetNextIndex().
bEnableSharedState
template<typename ArrayType> TDataReadReference<bool> Metasound::TArrayShuffleOperator< ArrayType >::bEnableSharedState private
Definition at line 442 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), and GetNextIndex().
InputArray
template<typename ArrayType> FArrayDataReadReference Metasound::TArrayShuffleOperator< ArrayType >::InputArray private
Definition at line 439 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), Execute(), and Reset().
OutValue
template<typename ArrayType> TDataWriteReference<ElementType> Metasound::TArrayShuffleOperator< ArrayType >::OutValue private
Definition at line 446 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindOutputs(), Execute(), and Reset().
PrevArraySize
template<typename ArrayType> int32 Metasound::TArrayShuffleOperator< ArrayType >::PrevArraySize = 0 private
Definition at line 451 of file MetasoundArrayShuffleNode.h.
Referenced by Execute(), and InitializeShufflers().
PrevSeedValue
template<typename ArrayType> int32 Metasound::TArrayShuffleOperator< ArrayType >::PrevSeedValue = INDEX_NONE private
Definition at line 450 of file MetasoundArrayShuffleNode.h.
Referenced by Execute(), InitializeShufflers(), Reset(), and Seed().
SeedValue
template<typename ArrayType> TDataReadReference<int32> Metasound::TArrayShuffleOperator< ArrayType >::SeedValue private
Definition at line 440 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), Execute(), and Reset().
SharedStateUniqueId
template<typename ArrayType> uint32 Metasound::TArrayShuffleOperator< ArrayType >::SharedStateUniqueId = INDEX_NONE private
Definition at line 452 of file MetasoundArrayShuffleNode.h.
Referenced by GetNextIndex(), InitializeShufflers(), Reset(), Reset(), Seed(), and Shuffle().
TriggerNext
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArrayShuffleOperator< ArrayType >::TriggerNext private
Definition at line 436 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), BindOutputs(), and Execute().
TriggerOnShuffle
template<typename ArrayType> TDataWriteReference<FTrigger> Metasound::TArrayShuffleOperator< ArrayType >::TriggerOnShuffle private
Definition at line 445 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindOutputs(), Execute(), and Reset().
TriggerReset
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArrayShuffleOperator< ArrayType >::TriggerReset private
Definition at line 438 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), BindOutputs(), and Execute().
TriggerShuffle
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArrayShuffleOperator< ArrayType >::TriggerShuffle private
Definition at line 437 of file MetasoundArrayShuffleNode.h.
Referenced by TArrayShuffleOperator(), BindInputs(), and Execute().
The documentation for this class was generated from the following file:
MetasoundArrayShuffleNode.h