Unreal Engine 5.6 C++ API: FPerceptionChannelAllowList Struct Reference
FPerceptionChannelAllowList Struct Reference
#include "AIPerceptionTypes.h"
Data Structures
struct FConstIterator
Public Types
typedef int32 FFlagsContainer
Public Member Functions
FPerceptionChannelAllowList ()
FORCEINLINE_DEBUGGABLE FPerceptionChannelAllowList & AcceptChannel (FAISenseID Channel)
void Clear ()
FORCEINLINE FPerceptionChannelAllowList & FilterOutChannel (FAISenseID Channel)
FORCEINLINE FFlagsContainer GetAcceptedChannelsMask () const
bool IsEmpty () const
FORCEINLINE FPerceptionChannelAllowList & MergeFilterIn (const FPerceptionChannelAllowList &OtherFilter)
FORCEINLINE bool ShouldRespondToChannel (FAISenseID Channel) const
Data Fields
FFlagsContainer AcceptedChannelsMask
Detailed Description
Definition at line 35 of file AIPerceptionTypes.h.
Member Typedef Documentation
FFlagsContainer
typedef int32 FPerceptionChannelAllowList::FFlagsContainer
Definition at line 37 of file AIPerceptionTypes.h.
Constructor & Destructor Documentation
FPerceptionChannelAllowList()
FPerceptionChannelAllowList::FPerceptionChannelAllowList () inline
Definition at line 42 of file AIPerceptionTypes.h.
References AcceptedChannelsMask.
Referenced by FPerceptionChannelAllowList::FConstIterator::FConstIterator(), AcceptChannel(), FilterOutChannel(), and MergeFilterIn().
Member Function Documentation
AcceptChannel()
FORCEINLINE_DEBUGGABLE FPerceptionChannelAllowList & FPerceptionChannelAllowList::AcceptChannel (FAISenseID Channel) inline
Definition at line 61 of file AIPerceptionTypes.h.
References FPerceptionChannelAllowList(), AcceptedChannelsMask, and FORCEINLINE_DEBUGGABLE.
Clear()
void FPerceptionChannelAllowList::Clear () inline
Definition at line 45 of file AIPerceptionTypes.h.
References AcceptedChannelsMask.
FilterOutChannel()
FORCEINLINE FPerceptionChannelAllowList & FPerceptionChannelAllowList::FilterOutChannel (FAISenseID Channel) inline
Definition at line 55 of file AIPerceptionTypes.h.
References FPerceptionChannelAllowList(), AcceptedChannelsMask, and FORCEINLINE.
GetAcceptedChannelsMask()
FORCEINLINE FFlagsContainer FPerceptionChannelAllowList::GetAcceptedChannelsMask () const inline
Definition at line 78 of file AIPerceptionTypes.h.
References AcceptedChannelsMask, and FORCEINLINE.
IsEmpty()
bool FPerceptionChannelAllowList::IsEmpty () const inline
Definition at line 50 of file AIPerceptionTypes.h.
References AcceptedChannelsMask.
MergeFilterIn()
FORCEINLINE FPerceptionChannelAllowList & FPerceptionChannelAllowList::MergeFilterIn (const FPerceptionChannelAllowList & OtherFilter) inline
Definition at line 72 of file AIPerceptionTypes.h.
References FPerceptionChannelAllowList(), AcceptedChannelsMask, and FORCEINLINE.
ShouldRespondToChannel()
FORCEINLINE bool FPerceptionChannelAllowList::ShouldRespondToChannel (FAISenseID Channel) const inline
Definition at line 67 of file AIPerceptionTypes.h.
References AcceptedChannelsMask, and FORCEINLINE.
Field Documentation
AcceptedChannelsMask
FFlagsContainer FPerceptionChannelAllowList::AcceptedChannelsMask
Definition at line 39 of file AIPerceptionTypes.h.
Referenced by FPerceptionChannelAllowList(), AcceptChannel(), Clear(), FilterOutChannel(), GetAcceptedChannelsMask(), IsEmpty(), MergeFilterIn(), and ShouldRespondToChannel().
The documentation for this struct was generated from the following file:
AIPerceptionTypes.h