Unreal Engine 5.6 C++ API: Windows Namespace Reference
Windows Namespace Reference
Data Structures
struct CRITICAL_SECTION
union LARGE_INTEGER
struct OVERLAPPED
struct SRWLOCK
Typedefs
typedef int32 BOOL
typedef BYTE BOOLEAN
typedef unsigned char BYTE
typedef unsigned long DWORD
typedef void * HANDLE
typedef HICON__ * HCURSOR
typedef HDC__ * HDC
typedef HICON__ * HICON
typedef HINSTANCE__ * HINSTANCE
typedef HKEY__ * HKEY
typedef HINSTANCE HMODULE
typedef HWND__ * HWND
typedef long LONG
typedef int64 LONGLONG
typedef _RTL_CRITICAL_SECTION * LPCRITICAL_SECTION
typedef const wchar_t * LPCTSTR
typedef const void * LPCVOID
typedef DWORD * LPDWORD
typedef _EXCEPTION_POINTERS * LPEXCEPTION_POINTERS
typedef _LARGE_INTEGER * LPLARGE_INTEGER
typedef long * LPLONG
typedef LONGLONG * LPLONGLONG
typedef _OVERLAPPED * LPOVERLAPPED
typedef void * LPVOID
typedef void(* PFLS_CALLBACK_FUNCTION) (void *lpFlsData)
typedef tagPROCESSENTRY32W PROCESSENTRY32
typedef _RTL_SRWLOCK * PRTL_SRWLOCK
typedef RTL_SRWLOCK * PSRWLOCK
typedef _RTL_SRWLOCK RTL_SRWLOCK
Functions
__declspec (dllimport) HMODULE __stdcall LoadLibraryW(LPCTSTR lpFileName)
FORCEINLINE void __stdcall AcquireSRWLockExclusive (SRWLOCK *SRWLock)
FORCEINLINE void __stdcall AcquireSRWLockShared (SRWLOCK *SRWLock)
FORCEINLINE BOOL __stdcall ConnectNamedPipe (HANDLE hNamedPipe, OVERLAPPED *lpOverlapped)
FORCEINLINE void __stdcall DeleteCriticalSection (CRITICAL_SECTION *lpCriticalSection)
FORCEINLINE void __stdcall EnterCriticalSection (CRITICAL_SECTION *lpCriticalSection)
FORCEINLINE BOOL __stdcall GetOverlappedResult (HANDLE hFile, OVERLAPPED *lpOverlapped, LPDWORD lpNumberOfBytesTransferred, BOOL bWait)
FORCEINLINE void __stdcall InitializeCriticalSection (CRITICAL_SECTION *lpCriticalSection)
FORCEINLINE BOOL __stdcall InitializeCriticalSectionAndSpinCount (CRITICAL_SECTION *lpCriticalSection, DWORD dwSpinCount)
FORCEINLINE void __stdcall InitializeSRWLock (SRWLOCK *SRWLock)
FORCEINLINE void __stdcall LeaveCriticalSection (CRITICAL_SECTION *lpCriticalSection)
FORCEINLINE BOOL __stdcall QueryPerformanceCounter (LARGE_INTEGER *Cycles)
FORCEINLINE BOOL __stdcall ReadFile (HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, OVERLAPPED *lpOverlapped)
FORCEINLINE void __stdcall ReleaseSRWLockExclusive (SRWLOCK *SRWLock)
FORCEINLINE void __stdcall ReleaseSRWLockShared (SRWLOCK *SRWLock)
FORCEINLINE DWORD __stdcall SetCriticalSectionSpinCount (CRITICAL_SECTION *lpCriticalSection, DWORD dwSpinCount)
FORCEINLINE BOOLEAN __stdcall TryAcquireSRWLockExclusive (SRWLOCK *SRWLock)
FORCEINLINE BOOLEAN __stdcall TryAcquireSRWLockShared (SRWLOCK *SRWLock)
FORCEINLINE BOOL __stdcall TryEnterCriticalSection (CRITICAL_SECTION *lpCriticalSection)
FORCEINLINE BOOL __stdcall WriteFile (HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, OVERLAPPED *lpOverlapped)
Variables
LPOVERLAPPED LPDWORD BOOL bWait
DWORD dwSpinCount
constexpr BOOL FALSE = 0
LPCVOID lpBuffer
LPVOID lpFlsValue
LPVOID DWORD LPDWORD lpNumberOfBytesRead
LPOVERLAPPED LPDWORD lpNumberOfBytesTransferred
LPCVOID DWORD LPDWORD lpNumberOfBytesWritten
LPOVERLAPPED lpOverlapped
LPVOID lpTlsValue
LPVOID DWORD nNumberOfBytesToRead
LPCVOID DWORD nNumberOfBytesToWrite
constexpr BOOL TRUE = 1
Typedef Documentation
BOOL
typedef int32 Windows::BOOL
Definition at line 64 of file Microsoft/MinimalWindowsApi.h.
BOOLEAN
typedef BYTE Windows::BOOLEAN
Definition at line 66 of file Microsoft/MinimalWindowsApi.h.
BYTE
typedef unsigned char Windows::BYTE
Definition at line 65 of file Microsoft/MinimalWindowsApi.h.
DWORD
typedef unsigned long Windows::DWORD
Definition at line 67 of file Microsoft/MinimalWindowsApi.h.
HANDLE
typedef void* Windows::HANDLE
Definition at line 78 of file Microsoft/MinimalWindowsApi.h.
HCURSOR
typedef HICON__* Windows::HCURSOR
Definition at line 85 of file Microsoft/MinimalWindowsApi.h.
HDC
typedef HDC__* Windows::HDC
Definition at line 83 of file Microsoft/MinimalWindowsApi.h.
HICON
typedef HICON__* Windows::HICON
Definition at line 84 of file Microsoft/MinimalWindowsApi.h.
HINSTANCE
typedef HINSTANCE__* Windows::HINSTANCE
Definition at line 79 of file Microsoft/MinimalWindowsApi.h.
HKEY
typedef HKEY__* Windows::HKEY
Definition at line 82 of file Microsoft/MinimalWindowsApi.h.
HMODULE
typedef HINSTANCE Windows::HMODULE
Definition at line 80 of file Microsoft/MinimalWindowsApi.h.
HWND
typedef HWND__* Windows::HWND
Definition at line 81 of file Microsoft/MinimalWindowsApi.h.
LONG
typedef long Windows::LONG
Definition at line 69 of file Microsoft/MinimalWindowsApi.h.
LONGLONG
typedef int64 Windows::LONGLONG
Definition at line 71 of file Microsoft/MinimalWindowsApi.h.
LPCRITICAL_SECTION
typedef _RTL_CRITICAL_SECTION* Windows::LPCRITICAL_SECTION
Definition at line 90 of file Microsoft/MinimalWindowsApi.h.
LPCTSTR
typedef const wchar_t* Windows::LPCTSTR
Definition at line 75 of file Microsoft/MinimalWindowsApi.h.
LPCVOID
typedef const void* Windows::LPCVOID
Definition at line 74 of file Microsoft/MinimalWindowsApi.h.
LPDWORD
typedef DWORD* Windows::LPDWORD
Definition at line 68 of file Microsoft/MinimalWindowsApi.h.
LPEXCEPTION_POINTERS
typedef _EXCEPTION_POINTERS* Windows::LPEXCEPTION_POINTERS
Definition at line 89 of file Microsoft/MinimalWindowsApi.h.
LPLARGE_INTEGER
typedef _LARGE_INTEGER* Windows::LPLARGE_INTEGER
Definition at line 92 of file Microsoft/MinimalWindowsApi.h.
LPLONG
typedef long* Windows::LPLONG
Definition at line 70 of file Microsoft/MinimalWindowsApi.h.
LPLONGLONG
typedef LONGLONG* Windows::LPLONGLONG
Definition at line 72 of file Microsoft/MinimalWindowsApi.h.
LPOVERLAPPED
typedef _OVERLAPPED* Windows::LPOVERLAPPED
Definition at line 91 of file Microsoft/MinimalWindowsApi.h.
LPVOID
typedef void* Windows::LPVOID
Definition at line 73 of file Microsoft/MinimalWindowsApi.h.
PFLS_CALLBACK_FUNCTION
typedef void(* Windows::PFLS_CALLBACK_FUNCTION) (void *lpFlsData)
Definition at line 97 of file Microsoft/MinimalWindowsApi.h.
PROCESSENTRY32
typedef tagPROCESSENTRY32W Windows::PROCESSENTRY32
Definition at line 88 of file Microsoft/MinimalWindowsApi.h.
PRTL_SRWLOCK
typedef _RTL_SRWLOCK * Windows::PRTL_SRWLOCK
Definition at line 94 of file Microsoft/MinimalWindowsApi.h.
PSRWLOCK
typedef RTL_SRWLOCK* Windows::PSRWLOCK
Definition at line 95 of file Microsoft/MinimalWindowsApi.h.
RTL_SRWLOCK
typedef _RTL_SRWLOCK Windows::RTL_SRWLOCK
Definition at line 94 of file Microsoft/MinimalWindowsApi.h.
Function Documentation
__declspec()
Windows::__declspec (dllimport)
References MINIMAL_WINDOWS_API, and WINAPI.
AcquireSRWLockExclusive()
FORCEINLINE void __stdcall Windows::AcquireSRWLockExclusive (SRWLOCK * SRWLock)
Definition at line 156 of file Microsoft/MinimalWindowsApi.h.
References AcquireSRWLockExclusive(), FORCEINLINE, and WINAPI.
Referenced by AcquireSRWLockExclusive(), and UE::FWindowsSharedMutex::Lock().
AcquireSRWLockShared()
FORCEINLINE void __stdcall Windows::AcquireSRWLockShared (SRWLOCK * SRWLock)
Definition at line 146 of file Microsoft/MinimalWindowsApi.h.
References AcquireSRWLockShared(), FORCEINLINE, and WINAPI.
Referenced by AcquireSRWLockShared(), and UE::FWindowsSharedMutex::LockShared().
ConnectNamedPipe()
FORCEINLINE BOOL __stdcall Windows::ConnectNamedPipe (HANDLE hNamedPipe, OVERLAPPED * lpOverlapped)
Definition at line 196 of file Microsoft/MinimalWindowsApi.h.
References ConnectNamedPipe(), FORCEINLINE, lpOverlapped, and WINAPI.
Referenced by ConnectNamedPipe().
DeleteCriticalSection()
FORCEINLINE void __stdcall Windows::DeleteCriticalSection (CRITICAL_SECTION * lpCriticalSection)
Definition at line 246 of file Microsoft/MinimalWindowsApi.h.
References DeleteCriticalSection(), FORCEINLINE, and WINAPI.
Referenced by UE::FWindowsRecursiveMutex::~FWindowsRecursiveMutex(), and DeleteCriticalSection().
EnterCriticalSection()
FORCEINLINE void __stdcall Windows::EnterCriticalSection (CRITICAL_SECTION * lpCriticalSection)
Definition at line 236 of file Microsoft/MinimalWindowsApi.h.
References EnterCriticalSection(), FORCEINLINE, and WINAPI.
Referenced by EnterCriticalSection(), and UE::FWindowsRecursiveMutex::Lock().
GetOverlappedResult()
FORCEINLINE BOOL __stdcall Windows::GetOverlappedResult (HANDLE hFile, OVERLAPPED * lpOverlapped, LPDWORD lpNumberOfBytesTransferred, BOOL bWait)
Definition at line 201 of file Microsoft/MinimalWindowsApi.h.
References bWait, FORCEINLINE, GetOverlappedResult(), lpNumberOfBytesTransferred, lpOverlapped, and WINAPI.
Referenced by GetOverlappedResult().
InitializeCriticalSection()
FORCEINLINE void __stdcall Windows::InitializeCriticalSection (CRITICAL_SECTION * lpCriticalSection)
Definition at line 216 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, InitializeCriticalSection(), and WINAPI.
Referenced by UE::FWindowsRecursiveMutex::FWindowsRecursiveMutex(), and InitializeCriticalSection().
InitializeCriticalSectionAndSpinCount()
FORCEINLINE BOOL __stdcall Windows::InitializeCriticalSectionAndSpinCount (CRITICAL_SECTION * lpCriticalSection, DWORD dwSpinCount)
Definition at line 221 of file Microsoft/MinimalWindowsApi.h.
References dwSpinCount, FORCEINLINE, InitializeCriticalSectionAndSpinCount(), and WINAPI.
Referenced by InitializeCriticalSectionAndSpinCount().
InitializeSRWLock()
FORCEINLINE void __stdcall Windows::InitializeSRWLock (SRWLOCK * SRWLock)
Definition at line 131 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, InitializeSRWLock(), and WINAPI.
Referenced by UE::FWindowsSharedMutex::FWindowsSharedMutex(), and InitializeSRWLock().
LeaveCriticalSection()
FORCEINLINE void __stdcall Windows::LeaveCriticalSection (CRITICAL_SECTION * lpCriticalSection)
Definition at line 241 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, LeaveCriticalSection(), and WINAPI.
Referenced by LeaveCriticalSection(), and UE::FWindowsRecursiveMutex::Unlock().
QueryPerformanceCounter()
FORCEINLINE BOOL __stdcall Windows::QueryPerformanceCounter (LARGE_INTEGER * Cycles)
Definition at line 251 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, QueryPerformanceCounter(), and WINAPI.
Referenced by FWindowsPlatformTime::Cycles(), QueryPerformanceCounter(), and FWindowsPlatformTime::Seconds().
ReadFile()
FORCEINLINE BOOL __stdcall Windows::ReadFile (HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, OVERLAPPED * lpOverlapped)
Definition at line 211 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, lpBuffer, lpNumberOfBytesRead, lpOverlapped, nNumberOfBytesToRead, ReadFile(), and WINAPI.
Referenced by ReadFile().
ReleaseSRWLockExclusive()
FORCEINLINE void __stdcall Windows::ReleaseSRWLockExclusive (SRWLOCK * SRWLock)
Definition at line 161 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, ReleaseSRWLockExclusive(), and WINAPI.
Referenced by UE::FWindowsSharedMutex::IsLocked(), ReleaseSRWLockExclusive(), and UE::FWindowsSharedMutex::Unlock().
ReleaseSRWLockShared()
FORCEINLINE void __stdcall Windows::ReleaseSRWLockShared (SRWLOCK * SRWLock)
Definition at line 151 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, ReleaseSRWLockShared(), and WINAPI.
Referenced by ReleaseSRWLockShared(), and UE::FWindowsSharedMutex::UnlockShared().
SetCriticalSectionSpinCount()
FORCEINLINE DWORD __stdcall Windows::SetCriticalSectionSpinCount (CRITICAL_SECTION * lpCriticalSection, DWORD dwSpinCount)
Definition at line 226 of file Microsoft/MinimalWindowsApi.h.
References dwSpinCount, FORCEINLINE, SetCriticalSectionSpinCount(), and WINAPI.
Referenced by UE::FWindowsRecursiveMutex::FWindowsRecursiveMutex(), and SetCriticalSectionSpinCount().
TryAcquireSRWLockExclusive()
FORCEINLINE BOOLEAN __stdcall Windows::TryAcquireSRWLockExclusive (SRWLOCK * SRWLock)
Definition at line 136 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, TryAcquireSRWLockExclusive(), and WINAPI.
Referenced by UE::FWindowsSharedMutex::IsLocked(), TryAcquireSRWLockExclusive(), and UE::FWindowsSharedMutex::TryLock().
TryAcquireSRWLockShared()
FORCEINLINE BOOLEAN __stdcall Windows::TryAcquireSRWLockShared (SRWLOCK * SRWLock)
Definition at line 141 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, TryAcquireSRWLockShared(), and WINAPI.
Referenced by TryAcquireSRWLockShared(), and UE::FWindowsSharedMutex::TryLockShared().
TryEnterCriticalSection()
FORCEINLINE BOOL __stdcall Windows::TryEnterCriticalSection (CRITICAL_SECTION * lpCriticalSection)
Definition at line 231 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, TryEnterCriticalSection(), and WINAPI.
Referenced by TryEnterCriticalSection(), and UE::FWindowsRecursiveMutex::TryLock().
WriteFile()
FORCEINLINE BOOL __stdcall Windows::WriteFile (HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, OVERLAPPED * lpOverlapped)
Definition at line 206 of file Microsoft/MinimalWindowsApi.h.
References FORCEINLINE, lpBuffer, lpNumberOfBytesWritten, lpOverlapped, nNumberOfBytesToWrite, WINAPI, and WriteFile().
Referenced by WriteFile().
Variable Documentation
bWait
LPOVERLAPPED LPDWORD BOOL Windows::bWait
Definition at line 168 of file Microsoft/MinimalWindowsApi.h.
Referenced by GetOverlappedResult().
dwSpinCount
DWORD Windows::dwSpinCount
Definition at line 116 of file Microsoft/MinimalWindowsApi.h.
Referenced by InitializeCriticalSectionAndSpinCount(), and SetCriticalSectionSpinCount().
FALSE
BOOL Windows::FALSE = 0 inline constexpr
Definition at line 108 of file Microsoft/MinimalWindowsApi.h.
lpBuffer
LPVOID Windows::lpBuffer
Definition at line 169 of file Microsoft/MinimalWindowsApi.h.
Referenced by ReadFile(), and WriteFile().
lpFlsValue
LPVOID Windows::lpFlsValue
Definition at line 185 of file Microsoft/MinimalWindowsApi.h.
lpNumberOfBytesRead
LPVOID DWORD LPDWORD Windows::lpNumberOfBytesRead
Definition at line 170 of file Microsoft/MinimalWindowsApi.h.
Referenced by ReadFile().
lpNumberOfBytesTransferred
LPOVERLAPPED LPDWORD Windows::lpNumberOfBytesTransferred
Definition at line 168 of file Microsoft/MinimalWindowsApi.h.
Referenced by GetOverlappedResult().
lpNumberOfBytesWritten
LPCVOID DWORD LPDWORD Windows::lpNumberOfBytesWritten
Definition at line 169 of file Microsoft/MinimalWindowsApi.h.
Referenced by WriteFile().
lpOverlapped
LPVOID DWORD LPDWORD LPOVERLAPPED Windows::lpOverlapped
Definition at line 167 of file Microsoft/MinimalWindowsApi.h.
Referenced by ConnectNamedPipe(), GetOverlappedResult(), ReadFile(), and WriteFile().
lpTlsValue
LPVOID Windows::lpTlsValue
Definition at line 179 of file Microsoft/MinimalWindowsApi.h.
nNumberOfBytesToRead
LPVOID DWORD Windows::nNumberOfBytesToRead
Definition at line 170 of file Microsoft/MinimalWindowsApi.h.
Referenced by ReadFile().
nNumberOfBytesToWrite
LPCVOID DWORD Windows::nNumberOfBytesToWrite
Definition at line 169 of file Microsoft/MinimalWindowsApi.h.
Referenced by WriteFile().
TRUE
BOOL Windows::TRUE = 1 inline constexpr
Definition at line 107 of file Microsoft/MinimalWindowsApi.h.