Unreal Engine 5.6 C++ API: FSlateRect Class Reference
FSlateRect Class Reference
A rectangle defined by upper-left and lower-right corners.
#include "SlateRect.h"
Public Member Functions
FSlateRect (const UE::Slate::FDeprecateVector2DParameter &InStartPos, const UE::Slate::FDeprecateVector2DParameter &InEndPos)
FSlateRect (float InLeft=-1, float InTop=-1, float InRight=-1, float InBottom=-1)
FORCEINLINE bool ContainsPoint (const UE::Slate::FDeprecateVector2DParameter &Point) const
Returns whether or not a point is inside the rectangle.
FORCEINLINE FSlateRect Expand (const FSlateRect &Other) const
Returns the rect that encompasses both rectangles.
FORCEINLINE FSlateRect ExtendBy (const FMargin &ExtendAmount) const
Return a rectangle that is extended on each side by the amount specified in each margin.
FORCEINLINE float GetArea () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetBottomLeft () const
Returns the bottom-left position of the rectangle.
FORCEINLINE FVector2f GetBottomLeft2f () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetBottomRight () const
Returns the bottom-right position of the rectangle.
FORCEINLINE FVector2f GetBottomRight2f () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetCenter () const
Returns the center of the rectangle.
FORCEINLINE FVector2f GetCenter2f () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetSize () const
Returns the size of the rectangle in each dimension.
FORCEINLINE FVector2f GetSize2f () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetTopLeft () const
Returns the top-left position of the rectangle.
FORCEINLINE FVector2f GetTopLeft2f () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetTopRight () const
Returns the top-right position of the rectangle.
FORCEINLINE FVector2f GetTopRight2f () const
bool InitFromString (const FString &InSourceString)
Returns a string of containing the coordinates of the rect.
FORCEINLINE FSlateRect InsetBy (const struct FMargin &InsetAmount) const
Return a rectangle that is contracted on each side by the amount specified in each margin.
FORCEINLINE FSlateRect IntersectionWith (const FSlateRect &Other) const
Returns the rectangle that is the intersection of this rectangle and Other.
FSlateRect IntersectionWith (const FSlateRect &Other, bool &OutOverlapping) const
Returns the rectangle that is the intersection of this rectangle and Other, as well as if they were overlapping at all.
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool IsValid () const
Determines if the rectangle has positive dimensions.
FORCEINLINE FSlateRect OffsetBy (const UE::Slate::FDeprecateVector2DParameter &OffsetAmount) const
Return a rectangle that is offset by the amount specified .
bool operator!= (const FSlateRect &Other) const
bool operator== (const FSlateRect &Other) const
FORCEINLINE FSlateRect Round () const
Rounds the Left, Top, Right and Bottom fields and returns a new FSlateRect with rounded components.
FORCEINLINE FSlateRect ScaleBy (float ScaleBy) const
Return a rectangle that is scaled by the amount specified.
FString ToString () const
Returns a string of containing the coordinates of the rect.
Static Public Member Functions
static bool DoRectanglesIntersect (const FSlateRect &A, const FSlateRect &B)
Do rectangles A and B intersect?
static FSlateRect FromPointAndExtent (const UE::Slate::FDeprecateVector2DParameter &TopLeft, const UE::Slate::FDeprecateVector2DParameter &Size)
Creates a rect from a top left point and extent.
static FORCEINLINE bool IsRectangleContained (const FSlateRect &A, const FSlateRect &B)
Is rectangle B contained within rectangle A?
Data Fields
float Bottom
float Left
float Right
float Top
Friends
FORCEINLINE uint32 GetTypeHash (const FSlateRect &Key)
FSlateRect operator* (float Scalar, const FSlateRect &Rect)
FSlateRect operator+ (const FSlateRect &A, const FSlateRect &B)
FSlateRect operator- (const FSlateRect &A, const FSlateRect &B)
Detailed Description
A rectangle defined by upper-left and lower-right corners.
Assumes a "screen-like" coordinate system where the origin is in the top-left, with the Y-axis going down. Functions like "contains" etc will not work with other conventions.
 +---------> X
 |
 |    (Left,Top)
 |            o----o
 |            |    |
 |            o----o
 |                (Right, Bottom)
 \/
 Y
Definition at line 25 of file SlateRect.h.
Constructor & Destructor Documentation
FSlateRect() [1/2]
FSlateRect::FSlateRect (float InLeft = -1, float InTop = -1, float InRight = -1, float InBottom = -1) inline explicit
Definition at line 34 of file SlateRect.h.
References Bottom, Left, Right, and Top.
Referenced by DoRectanglesIntersect(), Expand(), ExtendBy(), FromPointAndExtent(), GetTypeHash, InsetBy(), IntersectionWith(), IntersectionWith(), IsRectangleContained(), OffsetBy(), operator!=(), operator*, operator+, operator-, operator==(), Round(), and ScaleBy().
FSlateRect() [2/2]
FSlateRect::FSlateRect (const UE::Slate::FDeprecateVector2DParameter & InStartPos, const UE::Slate::FDeprecateVector2DParameter & InEndPos) inline
Definition at line 41 of file SlateRect.h.
References Bottom, Left, Right, Top, X, and Y.
Member Function Documentation
ContainsPoint()
FORCEINLINE bool FSlateRect::ContainsPoint (const UE::Slate::FDeprecateVector2DParameter & Point) const inline
Returns whether or not a point is inside the rectangle.
Parameters
Point The point to check
Returns
True if the point is inside the rectangle
Definition at line 283 of file SlateRect.h.
References Bottom, FORCEINLINE, Left, Point, Right, and Top.
DoRectanglesIntersect()
bool FSlateRect::DoRectanglesIntersect (const FSlateRect & A, const FSlateRect & B) inline static
Do rectangles A and B intersect?
Definition at line 318 of file SlateRect.h.
References FSlateRect(), A, and B.
Expand()
FORCEINLINE FSlateRect FSlateRect::Expand (const FSlateRect & Other) const inline
Returns the rect that encompasses both rectangles.
Parameters
Other The other rectangle
Returns
Rectangle that is big enough to fit both rectangles
Definition at line 223 of file SlateRect.h.
References FSlateRect(), Bottom, FORCEINLINE, Left, FMath::Max, FMath::Min, Other, Right, and Top.
ExtendBy()
FORCEINLINE FSlateRect FSlateRect::ExtendBy (const FMargin & ExtendAmount) const inline
Return a rectangle that is extended on each side by the amount specified in each margin.
Parameters
ExtendAmount The amount to extend the geometry.
Returns
An extended rectangle.
Definition at line 186 of file SlateRect.h.
References FSlateRect(), Bottom, FORCEINLINE, Left, Right, and Top.
Referenced by ScaleBy().
FromPointAndExtent()
FSlateRect FSlateRect::FromPointAndExtent (const UE::Slate::FDeprecateVector2DParameter & TopLeft, const UE::Slate::FDeprecateVector2DParameter & Size) inline static
Creates a rect from a top left point and extent.
Provided as a factory function to not conflict with the TopLeft + BottomRight ctor.
Definition at line 52 of file SlateRect.h.
References FSlateRect(), TopLeft, and TSequenceHistory< HistorySize >::Size.
GetArea()
FORCEINLINE float FSlateRect::GetArea () const inline
Returns
the area of the rectangle
Definition at line 92 of file SlateRect.h.
References Bottom, FORCEINLINE, Left, Right, and Top.
Referenced by IsEmpty().
GetBottomLeft()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetBottomLeft () const inline
Returns the bottom-left position of the rectangle.
Returns
The bottom-left position.
Definition at line 158 of file SlateRect.h.
References FORCEINLINE, and GetBottomLeft2f().
GetBottomLeft2f()
FORCEINLINE FVector2f FSlateRect::GetBottomLeft2f () const inline
Definition at line 162 of file SlateRect.h.
References Bottom, FORCEINLINE, and Left.
Referenced by GetBottomLeft().
GetBottomRight()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetBottomRight () const inline
Returns the bottom-right position of the rectangle.
Returns
The bottom-right position.
Definition at line 144 of file SlateRect.h.
References FORCEINLINE, and GetBottomRight2f().
GetBottomRight2f()
FORCEINLINE FVector2f FSlateRect::GetBottomRight2f () const inline
Definition at line 148 of file SlateRect.h.
References Bottom, FORCEINLINE, and Right.
Referenced by GetBottomRight(), and OffsetBy().
GetCenter()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetCenter () const inline
Returns the center of the rectangle.
Returns
The center point.
Definition at line 102 of file SlateRect.h.
References FORCEINLINE, and GetCenter2f().
GetCenter2f()
FORCEINLINE FVector2f FSlateRect::GetCenter2f () const inline
Definition at line 106 of file SlateRect.h.
References FORCEINLINE, GetSize2f(), Left, and Top.
Referenced by GetCenter().
GetSize()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetSize () const inline
Returns the size of the rectangle in each dimension.
Returns
The size as a vector.
Definition at line 80 of file SlateRect.h.
References FORCEINLINE, and GetSize2f().
Referenced by ScaleBy().
GetSize2f()
FORCEINLINE FVector2f FSlateRect::GetSize2f () const inline
Definition at line 84 of file SlateRect.h.
References Bottom, FORCEINLINE, Left, Right, and Top.
Referenced by GetCenter2f(), and GetSize().
GetTopLeft()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetTopLeft () const inline
Returns the top-left position of the rectangle.
Returns
The top-left position.
Definition at line 116 of file SlateRect.h.
References FORCEINLINE, and GetTopLeft2f().
GetTopLeft2f()
FORCEINLINE FVector2f FSlateRect::GetTopLeft2f () const inline
Definition at line 120 of file SlateRect.h.
References FORCEINLINE, Left, and Top.
Referenced by GetTopLeft(), and OffsetBy().
GetTopRight()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateRect::GetTopRight () const inline
Returns the top-right position of the rectangle.
Returns
The top-right position.
Definition at line 130 of file SlateRect.h.
References FORCEINLINE, and GetTopRight2f().
GetTopRight2f()
FORCEINLINE FVector2f FSlateRect::GetTopRight2f () const inline
Definition at line 134 of file SlateRect.h.
References FORCEINLINE, Right, and Top.
Referenced by GetTopRight().
InitFromString()
bool FSlateRect::InitFromString (const FString & InSourceString)
Returns a string of containing the coordinates of the rect.
Parameters
InSourceString A string containing the values to initialize this rect in format Left=Value Top=Value...
Returns
True if initialized successfully
InsetBy()
FORCEINLINE FSlateRect FSlateRect::InsetBy (const struct FMargin & InsetAmount) const inline
Return a rectangle that is contracted on each side by the amount specified in each margin.
Parameters
InsetAmount The amount to contract the geometry.
Returns
An inset rectangle.
Definition at line 174 of file SlateRect.h.
References FSlateRect(), Bottom, FORCEINLINE, Left, Right, and Top.
IntersectionWith() [1/2]
FORCEINLINE FSlateRect FSlateRect::IntersectionWith (const FSlateRect & Other) const inline
Returns the rectangle that is the intersection of this rectangle and Other.
Parameters
Other The other rectangle
Returns
Rectangle over intersection.
Definition at line 247 of file SlateRect.h.
References FSlateRect(), FORCEINLINE, IntersectionWith(), and Other.
Referenced by IntersectionWith().
IntersectionWith() [2/2]
FSlateRect FSlateRect::IntersectionWith (const FSlateRect & Other, bool & OutOverlapping) const inline
Returns the rectangle that is the intersection of this rectangle and Other, as well as if they were overlapping at all.
Parameters
Other The other rectangle
OutOverlapping [Out] Was there any overlap with the other rectangle.
Returns
Rectangle over intersection.
Definition at line 261 of file SlateRect.h.
References FSlateRect(), Bottom, Left, FMath::Max, FMath::Min, Other, Right, and Top.
IsEmpty()
FORCEINLINE bool FSlateRect::IsEmpty () const inline
Returns
true, if the rectangle has an effective size of 0.
Definition at line 70 of file SlateRect.h.
References FORCEINLINE, GetArea(), and UE_SMALL_NUMBER.
IsRectangleContained()
FORCEINLINE bool FSlateRect::IsRectangleContained (const FSlateRect & A, const FSlateRect & B) inline static
Is rectangle B contained within rectangle A?
Definition at line 338 of file SlateRect.h.
References FSlateRect(), A, B, and FORCEINLINE.
IsValid()
FORCEINLINE bool FSlateRect::IsValid () const inline
Determines if the rectangle has positive dimensions.
Definition at line 62 of file SlateRect.h.
References Bottom, FORCEINLINE, Left, Right, and Top.
OffsetBy()
FORCEINLINE FSlateRect FSlateRect::OffsetBy (const UE::Slate::FDeprecateVector2DParameter & OffsetAmount) const inline
Return a rectangle that is offset by the amount specified .
Parameters
OffsetAmount The amount to contract the geometry.
Returns
An offset rectangle.
Definition at line 198 of file SlateRect.h.
References FSlateRect(), FORCEINLINE, GetBottomRight2f(), and GetTopLeft2f().
operator!=()
bool FSlateRect::operator!= (const FSlateRect & Other) const inline
Definition at line 297 of file SlateRect.h.
References FSlateRect(), Bottom, Left, Other, Right, and Top.
operator==()
bool FSlateRect::operator== (const FSlateRect & Other) const inline
Definition at line 288 of file SlateRect.h.
References FSlateRect(), Bottom, Left, Other, Right, and Top.
Round()
FORCEINLINE FSlateRect FSlateRect::Round () const inline
Rounds the Left, Top, Right and Bottom fields and returns a new FSlateRect with rounded components.
Definition at line 231 of file SlateRect.h.
References FSlateRect(), Bottom, FORCEINLINE, Left, Right, and Top.
ScaleBy()
FORCEINLINE FSlateRect FSlateRect::ScaleBy (float ScaleBy) const inline
Return a rectangle that is scaled by the amount specified.
Parameters
ScaleBy The amount to scale the geometry.
Returns
An scaled rectangle.
Definition at line 210 of file SlateRect.h.
References FSlateRect(), ExtendBy(), FORCEINLINE, GetSize(), and ScaleBy().
Referenced by ScaleBy().
ToString()
FString FSlateRect::ToString () const
Returns a string of containing the coordinates of the rect.
Returns
A string of the rect coordinates
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FSlateRect & Key) friend
Definition at line 360 of file SlateRect.h.
References FSlateRect(), FORCEINLINE, GetTypeHash, Hash, HashCombine(), and Key.
Referenced by GetTypeHash.
operator*
FSlateRect operator* (float Scalar, const FSlateRect & Rect) friend
Definition at line 312 of file SlateRect.h.
References FSlateRect(), Bottom, Left, Right, and Top.
operator+
FSlateRect operator+ (const FSlateRect & A, const FSlateRect & B) friend
Definition at line 302 of file SlateRect.h.
References FSlateRect(), A, and B.
operator-
FSlateRect operator- (const FSlateRect & A, const FSlateRect & B) friend
Definition at line 307 of file SlateRect.h.
References FSlateRect(), A, and B.
Field Documentation
Bottom
float FSlateRect::Bottom
Definition at line 32 of file SlateRect.h.
Referenced by FSlateRect(), FSlateRect(), ContainsPoint(), Expand(), ExtendBy(), GetArea(), GetBottomLeft2f(), GetBottomRight2f(), GetSize2f(), InsetBy(), IntersectionWith(), IsValid(), operator!=(), operator*, operator==(), Round(), and TransformRect().
Left
float FSlateRect::Left
Definition at line 29 of file SlateRect.h.
Referenced by FSlateRect(), FSlateRect(), ContainsPoint(), Expand(), ExtendBy(), GetArea(), GetBottomLeft2f(), GetCenter2f(), GetSize2f(), GetTopLeft2f(), InsetBy(), IntersectionWith(), IsValid(), operator!=(), operator*, operator==(), Round(), and TransformRect().
Right
float FSlateRect::Right
Definition at line 31 of file SlateRect.h.
Referenced by FSlateRect(), FSlateRect(), ContainsPoint(), Expand(), ExtendBy(), GetArea(), GetBottomRight2f(), GetSize2f(), GetTopRight2f(), InsetBy(), IntersectionWith(), IsValid(), operator!=(), operator*, operator==(), Round(), and TransformRect().
Top
float FSlateRect::Top
Definition at line 30 of file SlateRect.h.
Referenced by FSlateRect(), FSlateRect(), ContainsPoint(), Expand(), ExtendBy(), GetArea(), GetCenter2f(), GetSize2f(), GetTopLeft2f(), GetTopRight2f(), InsetBy(), IntersectionWith(), IsValid(), operator!=(), operator*, operator==(), Round(), and TransformRect().
The documentation for this class was generated from the following file:
SlateRect.h