Unreal Engine 5.6 C++ API: FEditorDelegates Struct Reference
FEditorDelegates Struct Reference
FEditorDelegates Delegates used by the editor.
#include "Editor.h"
Public Member Functions
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnRestartRequested, const FString &)
delegate type for when the editor requests a restart, enables overriding how a restart is performed
DECLARE_MULTICAST_DELEGATE (FOnDeleteActorsBegin)
delegate type for before delete actors is handled
DECLARE_MULTICAST_DELEGATE (FOnDeleteActorsEnd)
delegate type for after delete actors is handled
DECLARE_MULTICAST_DELEGATE (FOnDuplicateActorsBegin)
delegate type for before edit duplicate actors is handled
DECLARE_MULTICAST_DELEGATE (FOnDuplicateActorsEnd)
delegate type for after edit duplicate actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditCopyActorsBegin)
delegate type for before edit copy actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditCopyActorsEnd)
delegate type for after edit copy actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditCutActorsBegin)
delegate type for before edit cut actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditCutActorsEnd)
delegate type for after edit cut actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditPasteActorsBegin)
delegate type for before edit paste actors is handled
DECLARE_MULTICAST_DELEGATE (FOnEditPasteActorsEnd)
delegate type for after edit paste actors is handled
DECLARE_MULTICAST_DELEGATE_FiveParams (FOnAssetPreImport, UFactory *, UClass *, UObject *, const FName &, const TCHAR *)
delegate type fired when new assets are being (re-)imported.
DECLARE_MULTICAST_DELEGATE_FourParams (FOnEditorCameraMoved, const FVector &, const FRotator &, ELevelViewportType, int32)
delegate type for editor camera movement
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAddLevelToWorld, ULevel *)
delegate type for when a new level is added to the world
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetReimport, UObject *)
delegate type fired when new assets have been reimported.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetsDeleted, const TArray< UClass * > &)
delegate type for when one or more assets have been deleted
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetsPreDelete, const TArray< UObject * > &)
delegate type for when a user requests to delete certain assets... DOES NOT mean the asset(s) will be deleted (the user could cancel)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorBoot, double Duration)
delegate for when the editor has booted
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorInitialized, double Duration)
delegate for when the editor has fully initialized
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorLoadDefaultStartupMap, FCanLoadMap &)
delegate for when the editor is about to load the default startup map - allows delegates to cancel the operation
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorModeIDTransitioned, const FEditorModeID &)
Delegate used for entering or exiting an editor mode.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorModeTransitioned, FEdMode *)
Delegate used for entering or exiting an editor mode.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnFinishPickingBlueprintClass, UClass *)
delegate type for finishing up construction of a new blueprint
DECLARE_MULTICAST_DELEGATE_OneParam (FOnFitTextureToSurface, UWorld *)
delegate type for when a texture is fit to surface
DECLARE_MULTICAST_DELEGATE_OneParam (FOnFocusViewportOnActors, const TArray< AActor * > &)
delegate type for triggering when focusing on a set of actors
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMapChanged, uint32)
delegate type for map change events (Params: uint32 MapChangeFlags (MapChangeEventFlags))
DECLARE_MULTICAST_DELEGATE_OneParam (FOnModeChanged, FEditorModeID)
delegate type for editor mode change events (Params: FEditorModeID NewMode)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNewAssetCreation, UFactory *)
delegate type for beginning or finishing configuration of the properties of a new asset
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPackageDeleted, UPackage *)
delegate type for when a user requests to delete certain package
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPIEEvent, const bool)
delegate for a PIE event (begin, end, pause/resume, etc) (Params: bool bIsSimulating)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPostSaveExternalActors, class UWorld *)
delegate type for post save external actors event, called by editor save codepaths and auto saves (UWorld* World)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreForceDeleteObjects, const TArray< UObject * > &)
delegate type for when a user requested force deleting objects.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreSaveExternalActors, class UWorld *)
delegate type for pre save external actors event, called by editor save codepaths and auto saves (UWorld* World)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnStandaloneLocalPlayEvent, const uint32)
delegate for a standalone local play event (Params: uint32 processID)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnViewAssetIdentifiers, TArray< FAssetIdentifier >)
delegate type to handle viewing/editing a set of asset identifiers which are packages or ids
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnExternalContentResolved, const FGuid &, const FAssetData &, const FAssetData &)
delegate when external content resolves and can replace placeholder data
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnPreDestructiveAssetAction, const TArray< UObject * > &, EDestructiveAssetActions, FResultMessage &)
delegate for when assets are about to undergo a destructive action caused by the Editor UI (Delete, Rename, Move, Privatize, etc.)
TArray< UObject * > & DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAddExtraObjectsToDelete, const TArray< UObject * > &, TSet< UObject * > &)
delegate type for when a user requests to delete certain assets... It allows the addition of secondary assets that should also be deleted
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnApplyObjectToActor, UObject *, AActor *)
delegate type for when attempting to apply an object to an actor
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetDragStarted, const TArray< FAssetData > &, class UActorFactory *)
delegate type for when a user starts dragging something out of content browser (can be multiple assets)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetPostImport, UFactory *, UObject *)
delegate type fired when new assets have been (re-)imported.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetsCanDelete, const TArray< UObject * > &, FCanDeleteAssetResult &)
delegate type to determine if a user requests can delete certain assets.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnDollyPerspectiveCamera, const FVector &, int32)
delegate type for dollying/zooming editor camera movement
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnEditorActorReplaced, AActor *, AActor *)
delegate type for triggering when an actor is replaced by another one in the editor.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnGridSnappingChanged, bool, float)
delegate type for triggering when grid snapping has changed
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMapLoad, const FString &, FCanLoadMap &)
delegate type for triggering when a map starts loading
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMapOpened, const FString &, bool)
delegate type for triggering when a map is opened
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNewActorsDropped, const TArray< UObject * > &, const TArray< AActor * > &)
delegate type for triggering when new actors are dropped on to the viewport via drag and drop
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNewActorsPlaced, UObject *, const TArray< AActor * > &)
delegate type for triggering when new actors are placed on to the viewport.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnOpenReferenceViewer, const TArray< FAssetIdentifier >, const FReferenceViewerParams)
delegate type to handle viewing/editing a set of asset identifiers (which are packages or ids) in the reference viewer
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPostSaveWorldWithContext, class UWorld *, FObjectPostSaveContext)
delegate type for post save world events (UWorld* World, FObjectPostSaveContext ObjectSaveContext)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPreSaveWorldWithContext, class UWorld *, FObjectPreSaveContext)
delegate type for pre save world events (UWorld* World, FObjectPreSaveContext ObjectSaveContext)
UE_DEPRECATED (4.22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()") static UNREALED_API FOnAssetPostImport OnAssetPostImport
Called when new assets have been (re-)imported.
UE_DEPRECATED (4.22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()") static UNREALED_API FOnAssetPreImport OnAssetPreImport
Called when new assets are being (re-)imported.
UE_DEPRECATED (4.22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()") static UNREALED_API FOnAssetReimport OnAssetReimport
Called after an asset has been reimported.
UE_DEPRECATED (4.24, "Use EditorModeIDEnter instead") static UNREALED_API FOnEditorModeTransitioned EditorModeEnter
Called when an editor mode is being entered.
UE_DEPRECATED (4.24, "Use EditorModeIDExit instead") static UNREALED_API FOnEditorModeTransitioned EditorModeExit
Called when an editor mode is being exited.
UE_DEPRECATED (5.0, "Use the asset editor's mode manager to scope mode enter notifications.") static UNREALED_API FOnEditorModeIDTransitioned EditorModeIDEnter
Called when an editor mode ID is being entered.
UE_DEPRECATED (5.0, "Use the asset editor's mode manager to scope mode exit notifications.") static UNREALED_API FOnEditorModeIDTransitioned EditorModeIDExit
Called when an editor mode ID is being exited.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.5, "Delegate signature for OnAssetsAddExtraObjectsToDelete has been deprecated please use new version OnAddExtraObjectsToDelete") static UNREALED_API FOnAssetsAddExtraObjectsToDelete OnAssetsAddExtraObjectsToDelete
Called when the user requests certain assets be deletedand allows the addition of secondary assets that should also be deleted.
UE_DEPRECATED (5.5, "FOnAssetsAddExtraObjectsToDelete has been deprecated, please use FOnAddExtraObjectsToDelete instead") DECLARE_MULTICAST_DELEGATE_OneParam(FOnAssetsAddExtraObjectsToDelete
delegate type for when a user requests to delete certain assets... It allows the addition of secondary assets that should also be deleted
Static Public Attributes
static UNREALED_API FSimpleMulticastDelegate ActorPropertiesChange
Called when properties of an actor have changed.
static UNREALED_API FOnPIEEvent BeginPIE
Sent when a PIE session is beginning (but hasn't actually started yet)
static UNREALED_API FOnStandaloneLocalPlayEvent BeginStandaloneLocalPlay
Sent when PC local play session is starting.
static UNREALED_API FSimpleMulticastDelegate CancelPIE
Sent when a PIE session is cancelled.
static UNREALED_API FOnModeChanged ChangeEditorMode
Called when the editor mode is changed.
static UNREALED_API FSimpleMulticastDelegate DisplayLoadErrors
Called when load errors are about to be displayed.
static UNREALED_API FOnPIEEvent EndPIE
Sent when a PIE session is ending.
static UNREALED_API FOnFitTextureToSurface FitTextureToSurface
Fits the currently assigned texture to the selected surfaces.
static UNREALED_API FSimpleMulticastDelegate LayerChange
Called when an actor is added to a layer.
static UNREALED_API FSimpleMulticastDelegate LoadSelectedAssetsIfNeeded
Called when an action is performed which interacts with the content browser; load any selected assets which aren't already loaded.
static UNREALED_API FOnMapChanged MapChange
Called when the map has changed.
static UNREALED_API FSimpleMulticastDelegate NewCurrentLevel
Called when the CurrentLevel is switched to a new level.
static UNREALED_API FSimpleMulticastDelegate OnActionAxisMappingsChanged
Called when Action or Axis mappings have been changed.
static PRAGMA_ENABLE_DEPRECATION_WARNINGS UNREALED_API FOnAddExtraObjectsToDelete OnAddExtraObjectsToDelete
static UNREALED_API FOnAddLevelToWorld OnAddLevelToWorld
Called from FEditorUtils::AddLevelToWorld after the level is added successfully to the world.
static UNREALED_API FOnApplyObjectToActor OnApplyObjectToActor
Called when when attempting to apply an object to an actor (via drag drop)
static UNREALED_API FOnAssetDragStarted OnAssetDragStarted
Called when a user starts dragging something out of content browser (can be multiple assets)
static UNREALED_API FOnAssetsCanDelete OnAssetsCanDelete
Called when the user requests assets to be deleted to determine if the operation is available.
static UNREALED_API FOnAssetsDeleted OnAssetsDeleted
Called when one or more assets have been deleted.
static UNREALED_API FOnAssetsPreDelete OnAssetsPreDelete
Called when the user requests certain assets be deleted (DOES NOT imply that the asset will be deleted... the user could cancel)
static UNREALED_API FOnNewAssetCreation OnConfigureNewAssetProperties
Called when beginning configuration of a new asset.
static UNREALED_API FOnDeleteActorsBegin OnDeleteActorsBegin
Sent when delete begin called.
static UNREALED_API FOnDeleteActorsEnd OnDeleteActorsEnd
Sent when delete end called.
static UNREALED_API FOnDollyPerspectiveCamera OnDollyPerspectiveCamera
Called when the editor camera is moved.
static UNREALED_API FOnDuplicateActorsBegin OnDuplicateActorsBegin
Sent before duplicate is handled.
static UNREALED_API FOnDuplicateActorsEnd OnDuplicateActorsEnd
Sent after duplicate is handled.
static UNREALED_API FOnViewAssetIdentifiers OnEditAssetIdentifiers
Called to try and edit an asset identifier, which could be a package or searchable name.
static UNREALED_API FOnEditCopyActorsBegin OnEditCopyActorsBegin
Sent before edit copy is handled.
static UNREALED_API FOnEditCopyActorsEnd OnEditCopyActorsEnd
Sent after edit copy is handled.
static UNREALED_API FOnEditCutActorsBegin OnEditCutActorsBegin
Sent before edit cut is handled.
static UNREALED_API FOnEditCutActorsEnd OnEditCutActorsEnd
Sent after edit cut is handled.
static UNREALED_API FOnEditorActorReplaced OnEditorActorReplaced
Called when an actor is replaced in the editor (once AActor::EditorReplacedActor is completed).
static UNREALED_API FOnEditorBoot OnEditorBoot
Called when the editor has booted.
static UNREALED_API FOnEditorCameraMoved OnEditorCameraMoved
Called when the editor camera is moved.
static UNREALED_API FOnEditorInitialized OnEditorInitialized
Called when the editor has initialized.
static UNREALED_API FOnEditorLoadDefaultStartupMap OnEditorLoadDefaultStartupMap
Called when the editor is about to load the default startup map.
static UNREALED_API FSimpleMulticastDelegate OnEditorPreExit
Called before the editor exits.
static UNREALED_API FOnEditPasteActorsBegin OnEditPasteActorsBegin
Sent before edit paste is handled.
static UNREALED_API FOnEditPasteActorsEnd OnEditPasteActorsEnd
Sent after edit paste is handled.
static UNREALED_API FSimpleMulticastDelegate OnEnableGestureRecognizerChanged
Called when a user changes the UInputSettings::bEnableGestureRecognizer setting to refresh the available actions.
static UNREALED_API FOnExternalContentResolved OnExternalContentResolved
Called when external content gets resolved.
static UNREALED_API FOnFinishPickingBlueprintClass OnFinishPickingBlueprintClass
Called when finishing picking a new blueprint class during construction.
static UNREALED_API FOnFocusViewportOnActors OnFocusViewportOnActors
Called when focusing viewport on a set of actors.
static UNREALED_API FOnGridSnappingChanged OnGridSnappingChanged
Called when grid snapping is changed.
static UNREALED_API FSimpleMulticastDelegate OnLightingBuildFailed
Called when a lighting build has failed (maybe called twice if cancelled)
static UNREALED_API FSimpleMulticastDelegate OnLightingBuildKept
Called when a lighting build has been kept.
static UNREALED_API FSimpleMulticastDelegate OnLightingBuildStarted
Called when a lighting build has started.
static UNREALED_API FSimpleMulticastDelegate OnLightingBuildSucceeded
Called when a lighting build has succeeded.
static UNREALED_API FOnMapLoad OnMapLoad
Called before LoadMap is processed.
static UNREALED_API FOnMapOpened OnMapOpened
Called when a map is opened, giving map name, and whether it was a template.
static UNREALED_API FOnNewActorsDropped OnNewActorsDropped
Called when new actors are dropped on to the viewport.
static UNREALED_API FOnNewActorsPlaced OnNewActorsPlaced
Called when new actors are placed in the viewport.
static UNREALED_API FOnNewAssetCreation OnNewAssetCreated
Called when finishing configuration of a new asset.
static UNREALED_API FOnViewAssetIdentifiers OnOpenAssetAudit
Called when you want to view things in the asset audit window.
static UNREALED_API FOnOpenReferenceViewer OnOpenReferenceViewer
Called when you want to view things in the reference viewer, these are bound to by asset manager editor plugins.
static UNREALED_API FOnViewAssetIdentifiers OnOpenSizeMap
Called when you want to view things in the size map.
static UNREALED_API FOnPackageDeleted OnPackageDeleted
Called when one or more packages have been deleted through save.
static UNREALED_API FSimpleMulticastDelegate OnPostAssetValidation
Called after asset validation happens by the Asset Validation subsystem.
static UNREALED_API FSimpleMulticastDelegate OnPreAssetValidation
Called before any asset validation happens via the Asset Validation subsystem.
static UNREALED_API FOnPreDestructiveAssetAction OnPreDestructiveAssetAction
Called when an asset is about to undergo a destructive action caused by the Editor UI (Delete, Move, Rename, Privatize, etc.)
static UNREALED_API FOnPreForceDeleteObjects OnPreForceDeleteObjects
Called when the user requests objects to be force deleted.
static UNREALED_API FOnPIEEvent OnPreSwitchBeginPIEAndSIE
Sent just before the user switches between from PIE to SIE, or vice-versa.
static UNREALED_API FOnRestartRequested OnRestartRequested
Called when the editor requests a restart.
static UNREALED_API FSimpleMulticastDelegate OnShutdownPostPackagesSaved
Called on editor shutdown after packages have been successfully saved.
static UNREALED_API FOnPIEEvent OnSwitchBeginPIEAndSIE
Sent after the user switches between from PIE to SIE, or vice-versa.
static UNREALED_API FOnPIEEvent PausePIE
Sent when a PIE session is paused.
static UNREALED_API FSimpleMulticastDelegate PostLandscapeLayerUpdated
Called after Landscape layer infomap update have completed.
static UNREALED_API FOnPIEEvent PostPIEStarted
Sent when a PIE session has fully started and after BeginPlay() has been called.
static UNREALED_API FOnPostSaveExternalActors PostSaveExternalActors
Called after any number of external actors has been saved.
static UNREALED_API FOnPostSaveWorldWithContext PostSaveWorldWithContext
Called after SaveWorld is processed.
static UNREALED_API FSimpleMulticastDelegate PostUndoRedo
Called after an undo/redo.
static UNREALED_API FOnPIEEvent PreBeginPIE
Sent when a PIE session is beginning (before we decide if PIE can run - allows clients to avoid blocking PIE)
static UNREALED_API FOnPIEEvent PrePIEEnded
Sent when a PIE session is ending, before anything else happens.
static UNREALED_API FOnPreSaveExternalActors PreSaveExternalActors
Called before any number of external actors will be saved.
static UNREALED_API FOnPreSaveWorldWithContext PreSaveWorldWithContext
Called before SaveWorld is processed.
static UNREALED_API FSimpleMulticastDelegate PropertySelectionChange
Within a property window, the currently selected item was changed.
static UNREALED_API FSimpleMulticastDelegate RefreshAllBrowsers
called when all browsers need to be refreshed
static UNREALED_API FSimpleMulticastDelegate RefreshEditor
Called when the editor needs to be refreshed.
static UNREALED_API FSimpleMulticastDelegate RefreshLayerBrowser
called when the layer browser need to be refreshed
static UNREALED_API FSimpleMulticastDelegate RefreshLevelBrowser
called when the level browser need to be refreshed
static UNREALED_API FSimpleMulticastDelegate RefreshPrimitiveStatsBrowser
called when the primitive stats browser need to be refreshed
static UNREALED_API FOnPIEEvent ResumePIE
Sent when a PIE session is resumed.
static UNREALED_API FSimpleMulticastDelegate SelectedProps
Sent when requesting to display the properties of selected actors or BSP surfaces.
static UNREALED_API FOnPIEEvent ShutdownPIE
Sent when a PIE session has completely shutdown.
static UNREALED_API FOnPIEEvent SingleStepPIE
Sent when a PIE session is single-stepped.
static UNREALED_API FOnPIEEvent StartPIE
Sent when a PIE session has been requested to Start.
static UNREALED_API FSimpleMulticastDelegate SurfProps
surfprops changed
Detailed Description
FEditorDelegates Delegates used by the editor.
Definition at line 79 of file Editor.h.
Member Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
FEditorDelegates::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnRestartRequested , const FString &)
delegate type for when the editor requests a restart, enables overriding how a restart is performed
References DECLARE_DELEGATE_RetVal_OneParam().
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_MULTICAST_DELEGATE() [1/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnDeleteActorsBegin)
delegate type for before delete actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [2/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnDeleteActorsEnd)
delegate type for after delete actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [3/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnDuplicateActorsBegin)
delegate type for before edit duplicate actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [4/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnDuplicateActorsEnd)
delegate type for after edit duplicate actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [5/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditCopyActorsBegin)
delegate type for before edit copy actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [6/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditCopyActorsEnd)
delegate type for after edit copy actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [7/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditCutActorsBegin)
delegate type for before edit cut actors is handled
References DECLARE_MULTICAST_DELEGATE().
Referenced by DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), DECLARE_MULTICAST_DELEGATE(), and DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [8/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditCutActorsEnd)
delegate type for after edit cut actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [9/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditPasteActorsBegin)
delegate type for before edit paste actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [10/10]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE (FOnEditPasteActorsEnd)
delegate type for after edit paste actors is handled
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE_FiveParams()
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_FiveParams (FOnAssetPreImport , UFactory * , UClass * , UObject * , const FName & , const TCHAR *)
delegate type fired when new assets are being (re-)imported.
Params: UFactory* InFactory, UClass* InClass, UObject* InParent, const FName& Name, const TCHAR* Type
DECLARE_MULTICAST_DELEGATE_FourParams()
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_FourParams (FOnEditorCameraMoved , const FVector & , const FRotator & , ELevelViewportType , int32)
delegate type for editor camera movement
References FVector.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAddLevelToWorld , ULevel *)
delegate type for when a new level is added to the world
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [2/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetReimport , UObject *)
delegate type fired when new assets have been reimported.
Note: InCreatedObject can be NULL if import failed. UObject* InCreatedObject
DECLARE_MULTICAST_DELEGATE_OneParam() [3/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetsDeleted , const TArray< UClass * > &)
delegate type for when one or more assets have been deleted
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [4/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetsPreDelete , const TArray< UObject * > &)
delegate type for when a user requests to delete certain assets... DOES NOT mean the asset(s) will be deleted (the user could cancel)
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [5/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorBoot , double Duration)
delegate for when the editor has booted
References DECLARE_MULTICAST_DELEGATE_OneParam(), and Duration.
DECLARE_MULTICAST_DELEGATE_OneParam() [6/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorInitialized , double Duration)
delegate for when the editor has fully initialized
References DECLARE_MULTICAST_DELEGATE_OneParam(), and Duration.
DECLARE_MULTICAST_DELEGATE_OneParam() [7/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorLoadDefaultStartupMap , FCanLoadMap &)
delegate for when the editor is about to load the default startup map - allows delegates to cancel the operation
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [8/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorModeIDTransitioned , const FEditorModeID &)
Delegate used for entering or exiting an editor mode.
DECLARE_MULTICAST_DELEGATE_OneParam() [9/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEditorModeTransitioned , FEdMode *)
Delegate used for entering or exiting an editor mode.
DECLARE_MULTICAST_DELEGATE_OneParam() [10/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnFinishPickingBlueprintClass , UClass *)
delegate type for finishing up construction of a new blueprint
DECLARE_MULTICAST_DELEGATE_OneParam() [11/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnFitTextureToSurface , UWorld *)
delegate type for when a texture is fit to surface
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [12/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnFocusViewportOnActors , const TArray< AActor * > &)
delegate type for triggering when focusing on a set of actors
DECLARE_MULTICAST_DELEGATE_OneParam() [13/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnMapChanged , uint32)
delegate type for map change events (Params: uint32 MapChangeFlags (MapChangeEventFlags))
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), and UE_DEPRECATED().
DECLARE_MULTICAST_DELEGATE_OneParam() [14/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnModeChanged , FEditorModeID)
delegate type for editor mode change events (Params: FEditorModeID NewMode)
DECLARE_MULTICAST_DELEGATE_OneParam() [15/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNewAssetCreation , UFactory *)
delegate type for beginning or finishing configuration of the properties of a new asset
DECLARE_MULTICAST_DELEGATE_OneParam() [16/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPackageDeleted , UPackage *)
delegate type for when a user requests to delete certain package
DECLARE_MULTICAST_DELEGATE_OneParam() [17/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPIEEvent , const bool)
delegate for a PIE event (begin, end, pause/resume, etc) (Params: bool bIsSimulating)
DECLARE_MULTICAST_DELEGATE_OneParam() [18/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPostSaveExternalActors , class UWorld *)
delegate type for post save external actors event, called by editor save codepaths and auto saves (UWorld* World)
DECLARE_MULTICAST_DELEGATE_OneParam() [19/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreForceDeleteObjects , const TArray< UObject * > &)
delegate type for when a user requested force deleting objects.
The objects(s) will be deleted (no possibility to cancel), so implementations should delete references
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [20/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreSaveExternalActors , class UWorld *)
delegate type for pre save external actors event, called by editor save codepaths and auto saves (UWorld* World)
DECLARE_MULTICAST_DELEGATE_OneParam() [21/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnStandaloneLocalPlayEvent , const uint32)
delegate for a standalone local play event (Params: uint32 processID)
DECLARE_MULTICAST_DELEGATE_OneParam() [22/22]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnViewAssetIdentifiers , TArray< FAssetIdentifier >)
delegate type to handle viewing/editing a set of asset identifiers which are packages or ids
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnExternalContentResolved , const FGuid & , const FAssetData & , const FAssetData &)
delegate when external content resolves and can replace placeholder data
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnPreDestructiveAssetAction , const TArray< UObject * > & , EDestructiveAssetActions , FResultMessage &)
delegate for when assets are about to undergo a destructive action caused by the Editor UI (Delete, Rename, Move, Privatize, etc.)
Referenced by DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/15]
TArray< UObject * > & FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAddExtraObjectsToDelete , const TArray< UObject * > & , TSet< UObject * > &)
delegate type for when a user requests to delete certain assets... It allows the addition of secondary assets that should also be deleted
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnApplyObjectToActor , UObject * , AActor *)
delegate type for when attempting to apply an object to an actor
DECLARE_MULTICAST_DELEGATE_TwoParams() [3/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetDragStarted , const TArray< FAssetData > & , class UActorFactory *)
delegate type for when a user starts dragging something out of content browser (can be multiple assets)
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [4/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetPostImport , UFactory * , UObject *)
delegate type fired when new assets have been (re-)imported.
Note: InCreatedObject can be NULL if import failed. Params: UFactory* InFactory, UObject* InCreatedObject
DECLARE_MULTICAST_DELEGATE_TwoParams() [5/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnAssetsCanDelete , const TArray< UObject * > & , FCanDeleteAssetResult &)
delegate type to determine if a user requests can delete certain assets.
DECLARE_MULTICAST_DELEGATE_TwoParams() [6/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnDollyPerspectiveCamera , const FVector & , int32)
delegate type for dollying/zooming editor camera movement
References FVector.
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams(), DECLARE_MULTICAST_DELEGATE_TwoParams(), and DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [7/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnEditorActorReplaced , AActor * , AActor *)
delegate type for triggering when an actor is replaced by another one in the editor.
Triggers once AActor::EditorReplacedActor is completed
DECLARE_MULTICAST_DELEGATE_TwoParams() [8/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnGridSnappingChanged , bool , float)
delegate type for triggering when grid snapping has changed
DECLARE_MULTICAST_DELEGATE_TwoParams() [9/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMapLoad , const FString & , FCanLoadMap &)
delegate type for triggering when a map starts loading
DECLARE_MULTICAST_DELEGATE_TwoParams() [10/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMapOpened , const FString & , bool)
delegate type for triggering when a map is opened
DECLARE_MULTICAST_DELEGATE_TwoParams() [11/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNewActorsDropped , const TArray< UObject * > & , const TArray< AActor * > &)
delegate type for triggering when new actors are dropped on to the viewport via drag and drop
DECLARE_MULTICAST_DELEGATE_TwoParams() [12/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNewActorsPlaced , UObject * , const TArray< AActor * > &)
delegate type for triggering when new actors are placed on to the viewport.
Triggers before NewActorsDropped if placement is caused by a drop action
DECLARE_MULTICAST_DELEGATE_TwoParams() [13/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnOpenReferenceViewer , const TArray< FAssetIdentifier > , const FReferenceViewerParams)
delegate type to handle viewing/editing a set of asset identifiers (which are packages or ids) in the reference viewer
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [14/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPostSaveWorldWithContext , class UWorld * , FObjectPostSaveContext)
delegate type for post save world events (UWorld* World, FObjectPostSaveContext ObjectSaveContext)
DECLARE_MULTICAST_DELEGATE_TwoParams() [15/15]
FEditorDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPreSaveWorldWithContext , class UWorld * , FObjectPreSaveContext)
delegate type for pre save world events (UWorld* World, FObjectPreSaveContext ObjectSaveContext)
UE_DEPRECATED() [1/9]
FEditorDelegates::UE_DEPRECATED (4. 22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()")
Called when new assets have been (re-)imported.
References UE_DEPRECATED().
UE_DEPRECATED() [2/9]
FEditorDelegates::UE_DEPRECATED (4. 22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()")
Called when new assets are being (re-)imported.
References UE_DEPRECATED().
UE_DEPRECATED() [3/9]
FEditorDelegates::UE_DEPRECATED (4. 22, "Use the ImportSubsystem instead. GEditor->GetEditorSubsystem<UImportSubsystem>()")
Called after an asset has been reimported.
References UE_DEPRECATED().
UE_DEPRECATED() [4/9]
FEditorDelegates::UE_DEPRECATED (4. 24, "Use EditorModeIDEnter instead")
Called when an editor mode is being entered.
References UE_DEPRECATED().
UE_DEPRECATED() [5/9]
FEditorDelegates::UE_DEPRECATED (4. 24, "Use EditorModeIDExit instead")
Called when an editor mode is being exited.
References UE_DEPRECATED().
UE_DEPRECATED() [6/9]
FEditorDelegates::UE_DEPRECATED (5. 0, "Use the asset editor's mode manager to scope mode enter notifications.")
Called when an editor mode ID is being entered.
References UE_DEPRECATED().
UE_DEPRECATED() [7/9]
FEditorDelegates::UE_DEPRECATED (5. 0, "Use the asset editor's mode manager to scope mode exit notifications.")
Called when an editor mode ID is being exited.
References UE_DEPRECATED().
UE_DEPRECATED() [8/9]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FEditorDelegates::UE_DEPRECATED (5. 5, "Delegate signature for OnAssetsAddExtraObjectsToDelete has been deprecated please use new version OnAddExtraObjectsToDelete")
Called when the user requests certain assets be deletedand allows the addition of secondary assets that should also be deleted.
References PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
UE_DEPRECATED() [9/9]
FEditorDelegates::UE_DEPRECATED (5. 5, "FOnAssetsAddExtraObjectsToDelete has been deprecated, please use FOnAddExtraObjectsToDelete instead")
delegate type for when a user requests to delete certain assets... It allows the addition of secondary assets that should also be deleted
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
ActorPropertiesChange
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::ActorPropertiesChange static
Called when properties of an actor have changed.
Definition at line 208 of file Editor.h.
Referenced by FScopedActorPropertiesChangeImpl::FireCallback().
BeginPIE
UNREALED_API FOnPIEEvent FEditorDelegates::BeginPIE static
Sent when a PIE session is beginning (but hasn't actually started yet)
Definition at line 241 of file Editor.h.
BeginStandaloneLocalPlay
UNREALED_API FOnStandaloneLocalPlayEvent FEditorDelegates::BeginStandaloneLocalPlay static
Sent when PC local play session is starting.
Definition at line 263 of file Editor.h.
CancelPIE
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::CancelPIE static
Sent when a PIE session is cancelled.
Definition at line 261 of file Editor.h.
ChangeEditorMode
UNREALED_API FOnModeChanged FEditorDelegates::ChangeEditorMode static
Called when the editor mode is changed.
Definition at line 206 of file Editor.h.
DisplayLoadErrors
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::DisplayLoadErrors static
Called when load errors are about to be displayed.
Definition at line 223 of file Editor.h.
EndPIE
UNREALED_API FOnPIEEvent FEditorDelegates::EndPIE static
Sent when a PIE session is ending.
Definition at line 247 of file Editor.h.
FitTextureToSurface
UNREALED_API FOnFitTextureToSurface FEditorDelegates::FitTextureToSurface static
Fits the currently assigned texture to the selected surfaces.
Definition at line 204 of file Editor.h.
LayerChange
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::LayerChange static
Called when an actor is added to a layer.
Definition at line 196 of file Editor.h.
LoadSelectedAssetsIfNeeded
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::LoadSelectedAssetsIfNeeded static
Called when an action is performed which interacts with the content browser; load any selected assets which aren't already loaded.
Definition at line 221 of file Editor.h.
Referenced by FGameModeInfoCustomizer::OnMakeSelectedDefaultClassClicked(), and FGameModeInfoCustomizer::OnUseSelectedGameModeClicked().
MapChange
UNREALED_API FOnMapChanged FEditorDelegates::MapChange static
Called when the map has changed.
Definition at line 194 of file Editor.h.
NewCurrentLevel
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::NewCurrentLevel static
Called when the CurrentLevel is switched to a new level.
Note that this event won't be fired for temporary changes to the current level, such as when copying/pasting actors.
Definition at line 192 of file Editor.h.
OnActionAxisMappingsChanged
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnActionAxisMappingsChanged static
Called when Action or Axis mappings have been changed.
Definition at line 348 of file Editor.h.
OnAddExtraObjectsToDelete
PRAGMA_ENABLE_DEPRECATION_WARNINGS UNREALED_API FOnAddExtraObjectsToDelete FEditorDelegates::OnAddExtraObjectsToDelete static
Definition at line 336 of file Editor.h.
OnAddLevelToWorld
UNREALED_API FOnAddLevelToWorld FEditorDelegates::OnAddLevelToWorld static
Called from FEditorUtils::AddLevelToWorld after the level is added successfully to the world.
Definition at line 350 of file Editor.h.
OnApplyObjectToActor
UNREALED_API FOnApplyObjectToActor FEditorDelegates::OnApplyObjectToActor static
Called when when attempting to apply an object to an actor (via drag drop)
Definition at line 314 of file Editor.h.
OnAssetDragStarted
UNREALED_API FOnAssetDragStarted FEditorDelegates::OnAssetDragStarted static
Called when a user starts dragging something out of content browser (can be multiple assets)
Definition at line 342 of file Editor.h.
OnAssetsCanDelete
UNREALED_API FOnAssetsCanDelete FEditorDelegates::OnAssetsCanDelete static
Called when the user requests assets to be deleted to determine if the operation is available.
Definition at line 330 of file Editor.h.
OnAssetsDeleted
UNREALED_API FOnAssetsDeleted FEditorDelegates::OnAssetsDeleted static
Called when one or more assets have been deleted.
Definition at line 340 of file Editor.h.
OnAssetsPreDelete
UNREALED_API FOnAssetsPreDelete FEditorDelegates::OnAssetsPreDelete static
Called when the user requests certain assets be deleted (DOES NOT imply that the asset will be deleted... the user could cancel)
Definition at line 338 of file Editor.h.
OnConfigureNewAssetProperties
UNREALED_API FOnNewAssetCreation FEditorDelegates::OnConfigureNewAssetProperties static
Called when beginning configuration of a new asset.
Definition at line 283 of file Editor.h.
OnDeleteActorsBegin
UNREALED_API FOnDeleteActorsBegin FEditorDelegates::OnDeleteActorsBegin static
Sent when delete begin called.
Definition at line 368 of file Editor.h.
OnDeleteActorsEnd
UNREALED_API FOnDeleteActorsEnd FEditorDelegates::OnDeleteActorsEnd static
Sent when delete end called.
Definition at line 370 of file Editor.h.
OnDollyPerspectiveCamera
UNREALED_API FOnDollyPerspectiveCamera FEditorDelegates::OnDollyPerspectiveCamera static
Called when the editor camera is moved.
Definition at line 324 of file Editor.h.
OnDuplicateActorsBegin
UNREALED_API FOnDuplicateActorsBegin FEditorDelegates::OnDuplicateActorsBegin static
Sent before duplicate is handled.
Definition at line 364 of file Editor.h.
OnDuplicateActorsEnd
UNREALED_API FOnDuplicateActorsEnd FEditorDelegates::OnDuplicateActorsEnd static
Sent after duplicate is handled.
Definition at line 366 of file Editor.h.
OnEditAssetIdentifiers
UNREALED_API FOnViewAssetIdentifiers FEditorDelegates::OnEditAssetIdentifiers static
Called to try and edit an asset identifier, which could be a package or searchable name.
Definition at line 378 of file Editor.h.
OnEditCopyActorsBegin
UNREALED_API FOnEditCopyActorsBegin FEditorDelegates::OnEditCopyActorsBegin static
Sent before edit copy is handled.
Definition at line 356 of file Editor.h.
OnEditCopyActorsEnd
UNREALED_API FOnEditCopyActorsEnd FEditorDelegates::OnEditCopyActorsEnd static
Sent after edit copy is handled.
Definition at line 358 of file Editor.h.
OnEditCutActorsBegin
UNREALED_API FOnEditCutActorsBegin FEditorDelegates::OnEditCutActorsBegin static
Sent before edit cut is handled.
Definition at line 352 of file Editor.h.
OnEditCutActorsEnd
UNREALED_API FOnEditCutActorsEnd FEditorDelegates::OnEditCutActorsEnd static
Sent after edit cut is handled.
Definition at line 354 of file Editor.h.
OnEditorActorReplaced
UNREALED_API FOnEditorActorReplaced FEditorDelegates::OnEditorActorReplaced static
Called when an actor is replaced in the editor (once AActor::EditorReplacedActor is completed).
The first parameter is the old actor, the second is the new actor.
Definition at line 302 of file Editor.h.
Referenced by TExternalDirtyActorsTracker< StoreType >::TExternalDirtyActorsTracker(), and TExternalDirtyActorsTracker< StoreType >::~TExternalDirtyActorsTracker().
OnEditorBoot
UNREALED_API FOnEditorBoot FEditorDelegates::OnEditorBoot static
Called when the editor has booted.
Definition at line 382 of file Editor.h.
OnEditorCameraMoved
UNREALED_API FOnEditorCameraMoved FEditorDelegates::OnEditorCameraMoved static
Called when the editor camera is moved.
Definition at line 322 of file Editor.h.
Referenced by FBookMarkTypeActions::ApplyBookmarkToViewportClient().
OnEditorInitialized
UNREALED_API FOnEditorInitialized FEditorDelegates::OnEditorInitialized static
Called when the editor has initialized.
Definition at line 386 of file Editor.h.
OnEditorLoadDefaultStartupMap
UNREALED_API FOnEditorLoadDefaultStartupMap FEditorDelegates::OnEditorLoadDefaultStartupMap static
Called when the editor is about to load the default startup map.
Definition at line 384 of file Editor.h.
OnEditorPreExit
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnEditorPreExit static
Called before the editor exits.
This is called before any editor subsystems are deinitialized, and also before FCoreDelegates::OnEnginePreExit
Definition at line 388 of file Editor.h.
OnEditPasteActorsBegin
UNREALED_API FOnEditPasteActorsBegin FEditorDelegates::OnEditPasteActorsBegin static
Sent before edit paste is handled.
Definition at line 360 of file Editor.h.
OnEditPasteActorsEnd
UNREALED_API FOnEditPasteActorsEnd FEditorDelegates::OnEditPasteActorsEnd static
Sent after edit paste is handled.
Definition at line 362 of file Editor.h.
OnEnableGestureRecognizerChanged
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnEnableGestureRecognizerChanged static
Called when a user changes the UInputSettings::bEnableGestureRecognizer setting to refresh the available actions.
Definition at line 346 of file Editor.h.
OnExternalContentResolved
UNREALED_API FOnExternalContentResolved FEditorDelegates::OnExternalContentResolved static
Called when external content gets resolved.
Definition at line 390 of file Editor.h.
OnFinishPickingBlueprintClass
UNREALED_API FOnFinishPickingBlueprintClass FEditorDelegates::OnFinishPickingBlueprintClass static
Called when finishing picking a new blueprint class during construction.
Definition at line 281 of file Editor.h.
OnFocusViewportOnActors
UNREALED_API FOnFocusViewportOnActors FEditorDelegates::OnFocusViewportOnActors static
Called when focusing viewport on a set of actors.
Definition at line 316 of file Editor.h.
OnGridSnappingChanged
UNREALED_API FOnGridSnappingChanged FEditorDelegates::OnGridSnappingChanged static
Called when grid snapping is changed.
Definition at line 304 of file Editor.h.
OnLightingBuildFailed
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnLightingBuildFailed static
Called when a lighting build has failed (maybe called twice if cancelled)
Definition at line 310 of file Editor.h.
OnLightingBuildKept
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnLightingBuildKept static
Called when a lighting build has been kept.
Definition at line 308 of file Editor.h.
OnLightingBuildStarted
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnLightingBuildStarted static
Called when a lighting build has started.
Definition at line 306 of file Editor.h.
OnLightingBuildSucceeded
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnLightingBuildSucceeded static
Called when a lighting build has succeeded.
Definition at line 312 of file Editor.h.
OnMapLoad
UNREALED_API FOnMapLoad FEditorDelegates::OnMapLoad static
Called before LoadMap is processed.
Definition at line 318 of file Editor.h.
OnMapOpened
UNREALED_API FOnMapOpened FEditorDelegates::OnMapOpened static
Called when a map is opened, giving map name, and whether it was a template.
Definition at line 320 of file Editor.h.
OnNewActorsDropped
UNREALED_API FOnNewActorsDropped FEditorDelegates::OnNewActorsDropped static
Called when new actors are dropped on to the viewport.
Definition at line 298 of file Editor.h.
OnNewActorsPlaced
UNREALED_API FOnNewActorsPlaced FEditorDelegates::OnNewActorsPlaced static
Called when new actors are placed in the viewport.
Definition at line 300 of file Editor.h.
OnNewAssetCreated
UNREALED_API FOnNewAssetCreation FEditorDelegates::OnNewAssetCreated static
Called when finishing configuration of a new asset.
Definition at line 287 of file Editor.h.
OnOpenAssetAudit
UNREALED_API FOnViewAssetIdentifiers FEditorDelegates::OnOpenAssetAudit static
Called when you want to view things in the asset audit window.
Definition at line 376 of file Editor.h.
OnOpenReferenceViewer
UNREALED_API FOnOpenReferenceViewer FEditorDelegates::OnOpenReferenceViewer static
Called when you want to view things in the reference viewer, these are bound to by asset manager editor plugins.
Definition at line 372 of file Editor.h.
OnOpenSizeMap
UNREALED_API FOnViewAssetIdentifiers FEditorDelegates::OnOpenSizeMap static
Called when you want to view things in the size map.
Definition at line 374 of file Editor.h.
OnPackageDeleted
UNREALED_API FOnPackageDeleted FEditorDelegates::OnPackageDeleted static
Called when one or more packages have been deleted through save.
Definition at line 328 of file Editor.h.
OnPostAssetValidation
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnPostAssetValidation static
Called after asset validation happens by the Asset Validation subsystem.
Definition at line 279 of file Editor.h.
OnPreAssetValidation
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnPreAssetValidation static
Called before any asset validation happens via the Asset Validation subsystem.
Definition at line 277 of file Editor.h.
OnPreDestructiveAssetAction
UNREALED_API FOnPreDestructiveAssetAction FEditorDelegates::OnPreDestructiveAssetAction static
Called when an asset is about to undergo a destructive action caused by the Editor UI (Delete, Move, Rename, Privatize, etc.)
Definition at line 285 of file Editor.h.
OnPreForceDeleteObjects
UNREALED_API FOnPreForceDeleteObjects FEditorDelegates::OnPreForceDeleteObjects static
Called when the user requests objects to be force deleted.
There is no possibility to cancel once this callback is made
Definition at line 344 of file Editor.h.
OnPreSwitchBeginPIEAndSIE
UNREALED_API FOnPIEEvent FEditorDelegates::OnPreSwitchBeginPIEAndSIE static
Sent just before the user switches between from PIE to SIE, or vice-versa.
Passes in whether we are currently in SIE
Definition at line 257 of file Editor.h.
OnRestartRequested
UNREALED_API FOnRestartRequested FEditorDelegates::OnRestartRequested static
Called when the editor requests a restart.
Definition at line 380 of file Editor.h.
OnShutdownPostPackagesSaved
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::OnShutdownPostPackagesSaved static
Called on editor shutdown after packages have been successfully saved.
Definition at line 326 of file Editor.h.
OnSwitchBeginPIEAndSIE
UNREALED_API FOnPIEEvent FEditorDelegates::OnSwitchBeginPIEAndSIE static
Sent after the user switches between from PIE to SIE, or vice-versa.
Passes in whether we are currently in SIE
Definition at line 259 of file Editor.h.
PausePIE
UNREALED_API FOnPIEEvent FEditorDelegates::PausePIE static
Sent when a PIE session is paused.
Definition at line 251 of file Editor.h.
PostLandscapeLayerUpdated
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::PostLandscapeLayerUpdated static
Called after Landscape layer infomap update have completed.
Definition at line 267 of file Editor.h.
PostPIEStarted
UNREALED_API FOnPIEEvent FEditorDelegates::PostPIEStarted static
Sent when a PIE session has fully started and after BeginPlay() has been called.
Definition at line 243 of file Editor.h.
PostSaveExternalActors
UNREALED_API FOnPostSaveExternalActors FEditorDelegates::PostSaveExternalActors static
Called after any number of external actors has been saved.
Definition at line 275 of file Editor.h.
PostSaveWorldWithContext
UNREALED_API FOnPostSaveWorldWithContext FEditorDelegates::PostSaveWorldWithContext static
Called after SaveWorld is processed.
Definition at line 271 of file Editor.h.
PostUndoRedo
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::PostUndoRedo static
Called after an undo/redo.
Definition at line 198 of file Editor.h.
PreBeginPIE
UNREALED_API FOnPIEEvent FEditorDelegates::PreBeginPIE static
Sent when a PIE session is beginning (before we decide if PIE can run - allows clients to avoid blocking PIE)
Definition at line 239 of file Editor.h.
PrePIEEnded
UNREALED_API FOnPIEEvent FEditorDelegates::PrePIEEnded static
Sent when a PIE session is ending, before anything else happens.
Definition at line 245 of file Editor.h.
PreSaveExternalActors
UNREALED_API FOnPreSaveExternalActors FEditorDelegates::PreSaveExternalActors static
Called before any number of external actors will be saved.
Definition at line 273 of file Editor.h.
PreSaveWorldWithContext
UNREALED_API FOnPreSaveWorldWithContext FEditorDelegates::PreSaveWorldWithContext static
Called before SaveWorld is processed.
Definition at line 269 of file Editor.h.
PropertySelectionChange
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::PropertySelectionChange static
Within a property window, the currently selected item was changed.
Definition at line 265 of file Editor.h.
RefreshAllBrowsers
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::RefreshAllBrowsers static
called when all browsers need to be refreshed
Definition at line 212 of file Editor.h.
Referenced by FScopedRefreshAllBrowsersImpl::FireCallback().
RefreshEditor
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::RefreshEditor static
Called when the editor needs to be refreshed.
Definition at line 210 of file Editor.h.
RefreshLayerBrowser
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::RefreshLayerBrowser static
called when the layer browser need to be refreshed
Definition at line 216 of file Editor.h.
RefreshLevelBrowser
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::RefreshLevelBrowser static
called when the level browser need to be refreshed
Definition at line 214 of file Editor.h.
RefreshPrimitiveStatsBrowser
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::RefreshPrimitiveStatsBrowser static
called when the primitive stats browser need to be refreshed
Definition at line 218 of file Editor.h.
ResumePIE
UNREALED_API FOnPIEEvent FEditorDelegates::ResumePIE static
Sent when a PIE session is resumed.
Definition at line 253 of file Editor.h.
SelectedProps
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::SelectedProps static
Sent when requesting to display the properties of selected actors or BSP surfaces.
Definition at line 202 of file Editor.h.
ShutdownPIE
UNREALED_API FOnPIEEvent FEditorDelegates::ShutdownPIE static
Sent when a PIE session has completely shutdown.
Definition at line 249 of file Editor.h.
SingleStepPIE
UNREALED_API FOnPIEEvent FEditorDelegates::SingleStepPIE static
Sent when a PIE session is single-stepped.
Definition at line 255 of file Editor.h.
StartPIE
UNREALED_API FOnPIEEvent FEditorDelegates::StartPIE static
Sent when a PIE session has been requested to Start.
Definition at line 237 of file Editor.h.
SurfProps
UNREALED_API FSimpleMulticastDelegate FEditorDelegates::SurfProps static
surfprops changed
Definition at line 200 of file Editor.h.
The documentation for this struct was generated from the following file:
Editor.h