Unreal Engine 5.6 C++ API: UE::Geometry::TIntrTriangle2Triangle2< Real > Class Template Reference
UE::Geometry::TIntrTriangle2Triangle2< Real > Class Template Reference
Compute intersection between 2D triangles.
#include "IntrTriangle2Triangle2.h"
Public Member Functions
TIntrTriangle2Triangle2 ()
TIntrTriangle2Triangle2 (TTriangle2< Real > T0, TTriangle2< Real > T1)
TIntrTriangle2Triangle2 * Compute ()
bool Find ()
TTriangle2< Real > GetTriangle0 () const
TTriangle2< Real > GetTriangle1 () const
bool IsSimpleIntersection ()
void SetTriangle0 (const TTriangle2< Real > &Triangle0In)
void SetTriangle1 (const TTriangle2< Real > &Triangle1In)
bool Test ()
Static Public Member Functions
static int WhichSide (const TTriangle2< Real > &V, const TVector2< Real > &P, const TVector2< Real > &D)
Data Fields
TVector2< Real > Points [6]
int Quantity = 0
EIntersectionResult Result = EIntersectionResult::NotComputed
EIntersectionType Type = EIntersectionType::Empty
Protected Attributes
TTriangle2< Real > Triangle0
TTriangle2< Real > Triangle1
Static Private Member Functions
static void ClipConvexPolygonAgainstLine (const TVector2< Real > &N, double c, int &quantity, TVector2< Real > V[6])
Detailed Description
template<typename Real>
class UE::Geometry::TIntrTriangle2Triangle2< Real >
Compute intersection between 2D triangles.
Definition at line 22 of file IntrTriangle2Triangle2.h.
Constructor & Destructor Documentation
TIntrTriangle2Triangle2() [1/2]
template<typename Real> UE::Geometry::TIntrTriangle2Triangle2< Real >::TIntrTriangle2Triangle2 () inline
Definition at line 43 of file IntrTriangle2Triangle2.h.
TIntrTriangle2Triangle2() [2/2]
template<typename Real> UE::Geometry::TIntrTriangle2Triangle2< Real >::TIntrTriangle2Triangle2 (TTriangle2< Real > T0, TTriangle2< Real > T1) inline
Definition at line 45 of file IntrTriangle2Triangle2.h.
Member Function Documentation
ClipConvexPolygonAgainstLine()
template<typename Real> void UE::Geometry::TIntrTriangle2Triangle2< Real >::ClipConvexPolygonAgainstLine (const TVector2< Real > & N, double c, int & quantity, TVector2< Real > V[6]) inline static private
Definition at line 197 of file IntrTriangle2Triangle2.h.
Referenced by UE::Geometry::TIntrTriangle2Triangle2< float >::Find().
Compute()
template<typename Real> TIntrTriangle2Triangle2 * UE::Geometry::TIntrTriangle2Triangle2< Real >::Compute () inline
Definition at line 105 of file IntrTriangle2Triangle2.h.
Find()
template<typename Real> bool UE::Geometry::TIntrTriangle2Triangle2< Real >::Find () inline
Definition at line 112 of file IntrTriangle2Triangle2.h.
Referenced by UE::Geometry::TIntrTriangle2Triangle2< float >::Compute(), and UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection().
GetTriangle0()
template<typename Real> TTriangle2< Real > UE::Geometry::TIntrTriangle2Triangle2< Real >::GetTriangle0 () const inline
Definition at line 49 of file IntrTriangle2Triangle2.h.
GetTriangle1()
template<typename Real> TTriangle2< Real > UE::Geometry::TIntrTriangle2Triangle2< Real >::GetTriangle1 () const inline
Definition at line 53 of file IntrTriangle2Triangle2.h.
IsSimpleIntersection()
template<typename Real> bool UE::Geometry::TIntrTriangle2Triangle2< Real >::IsSimpleIntersection () inline
Definition at line 34 of file IntrTriangle2Triangle2.h.
SetTriangle0()
template<typename Real> void UE::Geometry::TIntrTriangle2Triangle2< Real >::SetTriangle0 (const TTriangle2< Real > & Triangle0In) inline
Definition at line 57 of file IntrTriangle2Triangle2.h.
SetTriangle1()
template<typename Real> void UE::Geometry::TIntrTriangle2Triangle2< Real >::SetTriangle1 (const TTriangle2< Real > & Triangle1In) inline
Definition at line 62 of file IntrTriangle2Triangle2.h.
Test()
template<typename Real> bool UE::Geometry::TIntrTriangle2Triangle2< Real >::Test () inline
Definition at line 68 of file IntrTriangle2Triangle2.h.
WhichSide()
template<typename Real> int UE::Geometry::TIntrTriangle2Triangle2< Real >::WhichSide (const TTriangle2< Real > & V, const TVector2< Real > & P, const TVector2< Real > & D) inline static
Definition at line 162 of file IntrTriangle2Triangle2.h.
Referenced by UE::Geometry::TIntrTriangle2Triangle2< float >::Test().
Field Documentation
Points
template<typename Real> TVector2<Real> UE::Geometry::TIntrTriangle2Triangle2< Real >::Points[6]
Definition at line 41 of file IntrTriangle2Triangle2.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection().
Quantity
template<typename Real> int UE::Geometry::TIntrTriangle2Triangle2< Real >::Quantity = 0
Definition at line 30 of file IntrTriangle2Triangle2.h.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection().
Result
template<typename Real> EIntersectionResult UE::Geometry::TIntrTriangle2Triangle2< Real >::Result = EIntersectionResult::NotComputed
Definition at line 31 of file IntrTriangle2Triangle2.h.
Triangle0
template<typename Real> TTriangle2<Real> UE::Geometry::TIntrTriangle2Triangle2< Real >::Triangle0 protected
Definition at line 26 of file IntrTriangle2Triangle2.h.
Triangle1
template<typename Real> TTriangle2<Real> UE::Geometry::TIntrTriangle2Triangle2< Real >::Triangle1 protected
Definition at line 26 of file IntrTriangle2Triangle2.h.
Type
template<typename Real> EIntersectionType UE::Geometry::TIntrTriangle2Triangle2< Real >::Type = EIntersectionType::Empty
Definition at line 32 of file IntrTriangle2Triangle2.h.
The documentation for this class was generated from the following file:
IntrTriangle2Triangle2.h