Unreal Engine 5.6 C++ API: MovieSceneSequenceID.h File Reference
MovieSceneSequenceID.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "EntitySystem/MovieSceneComponentDebug.h"
#include "MovieSceneSequenceID.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneSequenceID >
Namespaces
namespace MovieSceneSequenceID
Typedefs
typedef TCallTraits< FMovieSceneSequenceID >::ParamType FMovieSceneSequenceIDRef
Functions
FString LexToString (const FMovieSceneSequenceID &SequenceID)
USTRUCT () struct FMovieSceneSequenceID
Variables
constexpr FMovieSceneSequenceID MovieSceneSequenceID::Invalid = FMovieSceneSequenceID(-1)
constexpr FMovieSceneSequenceID MovieSceneSequenceID::Root = FMovieSceneSequenceID(0)
Typedef Documentation
FMovieSceneSequenceIDRef
typedef TCallTraits<FMovieSceneSequenceID>::ParamType FMovieSceneSequenceIDRef
Definition at line 93 of file MovieSceneSequenceID.h.
Function Documentation
LexToString()
FString LexToString (const FMovieSceneSequenceID & SequenceID) inline
Definition at line 101 of file MovieSceneSequenceID.h.
References TEXT.
USTRUCT()
USTRUCT ()
Definition at line 11 of file MovieSceneSequenceID.h.
References Ar, FORCEINLINE, GENERATED_BODY, GetTypeHash(), HashCombine(), IsValid(), operator!=(), operator<(), operator<<(), operator==(), operator>(), FArchive::Serialize(), UPROPERTY, and Value.