Unreal Engine 5.6 C++ API: UniformBuffer.h File Reference
UniformBuffer.h File Reference
#include "ShaderParameterMacros.h"
#include "RenderingThread.h"
#include "RenderResource.h"
#include "Templates/IsArrayOrRefOfType.h"
Data Structures
class TUniformBuffer< TBufferStruct >
A uniform buffer resource.
Functions
template<typename TBufferStruct>
void BeginSetUniformBufferContents (TUniformBuffer< TBufferStruct > &UniformBuffer, const TBufferStruct &Struct)
Sends a message to the rendering thread to set the contents of a uniform buffer.
template<typename TBufferStruct>
TUniformBufferRef< TBufferStruct > CreateUniformBufferImmediate (const TBufferStruct &Value, EUniformBufferUsage Usage, EUniformBufferValidation Validation=EUniformBufferValidation::ValidateResources)
Creates a uniform buffer with the given value, and returns a structured reference to it.
Function Documentation
BeginSetUniformBufferContents()
template<typename TBufferStruct> void BeginSetUniformBufferContents (TUniformBuffer< TBufferStruct > & UniformBuffer, const TBufferStruct & Struct)
Sends a message to the rendering thread to set the contents of a uniform buffer.
Called by the game thread.
Definition at line 135 of file UniformBuffer.h.
References ENQUEUE_RENDER_COMMAND, TUniformBuffer< TBufferStruct >::SetContents(), Struct, and UniformBuffer.
CreateUniformBufferImmediate()
template<typename TBufferStruct> TUniformBufferRef< TBufferStruct > CreateUniformBufferImmediate (const TBufferStruct & Value, EUniformBufferUsage Usage, EUniformBufferValidation Validation = EUniformBufferValidation::ValidateResources)
Creates a uniform buffer with the given value, and returns a structured reference to it.
Definition at line 20 of file UniformBuffer.h.
References TUniformBufferRef< TBufferStruct >::CreateUniformBufferImmediate(), Validation, and Value.
Referenced by TUniformBuffer< FLightmapResourceClusterShaderParameters >::InitRHI().