Unreal Engine 5.6 C++ API: FTokenizedMessage Class Reference
FTokenizedMessage Class Reference
This class represents a rich tokenized message, such as would be used for compiler output with 'hyperlinks' to source file locations.
#include "TokenizedMessage.h"
Data Structures
struct FPrivateToken
Public Member Functions
FTokenizedMessage (FPrivateToken)
Private constructor - we want to only create these structures as shared references via Create()
TSharedRef< FTokenizedMessage > AddText (const FText &InText)
Adds a text token to a message.
template<typename... TArguments>
TSharedRef< FTokenizedMessage > AddText (FTextFormat InTextFormat, TArguments &&... InArgs)
Adds a text token to a message as by calling FText::FormatOrdered.
TSharedRef< FTokenizedMessage > AddToken (const TSharedRef< IMessageToken > &InToken)
Adds a token to a message.
TSharedRef< FTokenizedMessage > Clone () const
Clone this message.
FName GetIdentifier () const
TSharedPtr< IMessageToken > GetMessageLink () const
Gets the token action associated with this messages as a whole.
const TArray< TSharedRef< IMessageToken > > & GetMessageTokens () const
Get the tokens in this message.
EMessageSeverity::Type GetSeverity () const
Gets the severity of this message.
void SetIdentifier (FName InIdentifier)
Assigns Identifier for the message to the provided name.
void SetMessageLink (const TSharedRef< IMessageToken > &InToken)
Sets up a token action for the message as a whole (not to be displayed... intended to be invoked from a double click).
void SetSeverity (const EMessageSeverity::Type InSeverity)
Sets the severity of this message.
FText ToText () const
Get this tokenized message as a string.
Public Member Functions inherited from TSharedFromThis< FTokenizedMessage >
TSharedRef< FTokenizedMessage, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FTokenizedMessage, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FTokenizedMessage > Create (EMessageSeverity::Type InSeverity, const FText &InMessageText=FText())
Creates a new FTokenizedMessage.
static FName GetSeverityIconName (EMessageSeverity::Type InSeverity)
Helper function for getting a severity as an icon name.
static FText GetSeverityText (EMessageSeverity::Type InSeverity)
Helper function for getting a severity as text.
Protected Attributes
TSharedPtr< IMessageToken > MessageLink
A token associated with the entire message (doesn't display)
TArray< TSharedRef< IMessageToken > > MessageTokens
the array of message tokens this message contains
Private Attributes
FName Identifier
Identifier for the message.
EMessageSeverity::Type Severity
The severity of this message.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FTokenizedMessage >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FTokenizedMessage >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
This class represents a rich tokenized message, such as would be used for compiler output with 'hyperlinks' to source file locations.
Definition at line 111 of file TokenizedMessage.h.
Constructor & Destructor Documentation
FTokenizedMessage()
FTokenizedMessage::FTokenizedMessage (FPrivateToken) inline explicit
Private constructor - we want to only create these structures as shared references via Create()
Definition at line 229 of file TokenizedMessage.h.
References Identifier, Info, and Severity.
Member Function Documentation
AddText() [1/2]
TSharedRef< FTokenizedMessage > FTokenizedMessage::AddText (const FText & InText)
Adds a text token to a message.
Parameters
InMessage The message to insert a token into
InText The text to insert as a token
Returns
this message, for chaining calls.
Referenced by AddText().
AddText() [2/2]
template<typename... TArguments> TSharedRef< FTokenizedMessage > FTokenizedMessage::AddText (FTextFormat InTextFormat, TArguments &&... InArgs) inline
Adds a text token to a message as by calling FText::FormatOrdered.
Parameters
InMessage The message to insert a token into
InText The text to insert as a token
Returns
this message, for chaining calls.
Definition at line 163 of file TokenizedMessage.h.
References AddText(), FText::FormatOrdered(), and Forward().
AddToken()
TSharedRef< FTokenizedMessage > FTokenizedMessage::AddToken (const TSharedRef< IMessageToken > & InToken)
Adds a token to a message.
Parameters
InMessage The message to insert a token into
InToken The token to insert
Returns
this message, for chaining calls.
Referenced by FCompilerResultsLog::Tokenize(), and FCompilerResultsLog::Tokenize().
Clone()
TSharedRef< FTokenizedMessage > FTokenizedMessage::Clone () const
Clone this message.
Note
The message tokens are shared between the original and the clone.
Create()
TSharedRef< FTokenizedMessage > FTokenizedMessage::Create (EMessageSeverity::Type InSeverity, const FText & InMessageText = FText()) static
Creates a new FTokenizedMessage.
Parameters
InSeverity The severity of the message.
InMessageString The string to display for this message. If this is not empty, then a string token will be added to this message.
Returns
the generated message for temporary storage or so other tokens can be added to it if required.
Referenced by FCompilerResultsLog::Error(), FAnimationUpdateContext::LogMessage(), FPoseContext::LogMessage(), FCompilerResultsLog::Note(), FCompilerResultsLog::StorePotentialError(), FCompilerResultsLog::StorePotentialNote(), FCompilerResultsLog::StorePotentialWarning(), FCompilerResultsLog::Warning(), and FCompilerResultsLog::Warning().
GetIdentifier()
FName FTokenizedMessage::GetIdentifier () const
Returns
Identifier for the message, if set, else NAME_None
GetMessageLink()
TSharedPtr< IMessageToken > FTokenizedMessage::GetMessageLink () const
Gets the token action associated with this messages as a whole.
Should link to an associated element.
Returns
A token action that was set via SetMessageLink().
GetMessageTokens()
const TArray< TSharedRef< IMessageToken > > & FTokenizedMessage::GetMessageTokens () const
Get the tokens in this message.
Returns
an array of tokens
GetSeverity()
EMessageSeverity::Type FTokenizedMessage::GetSeverity () const
Gets the severity of this message.
Returns
the severity of this message
GetSeverityIconName()
FName FTokenizedMessage::GetSeverityIconName (EMessageSeverity::Type InSeverity) static
Helper function for getting a severity as an icon name.
Parameters
InSeverity the severity to use
Returns
the name of the icon for the severity
GetSeverityText()
FText FTokenizedMessage::GetSeverityText (EMessageSeverity::Type InSeverity) static
Helper function for getting a severity as text.
Parameters
InSeverity the severity to use
Returns
a string representation of the severity
Referenced by FSeverityToken::FSeverityToken().
SetIdentifier()
void FTokenizedMessage::SetIdentifier (FName InIdentifier)
Assigns Identifier for the message to the provided name.
SetMessageLink()
void FTokenizedMessage::SetMessageLink (const TSharedRef< IMessageToken > & InToken)
Sets up a token action for the message as a whole (not to be displayed... intended to be invoked from a double click).
Parameters
InToken A token for the entire message to link to.
SetSeverity()
void FTokenizedMessage::SetSeverity (const EMessageSeverity::Type InSeverity)
Sets the severity of this message.
Parameters
InSeverity The severity to set this message to
ToText()
FText FTokenizedMessage::ToText () const
Get this tokenized message as a string.
Returns
a string representation of this message
Field Documentation
Identifier
FName FTokenizedMessage::Identifier private
Identifier for the message.
Definition at line 249 of file TokenizedMessage.h.
Referenced by FTokenizedMessage().
MessageLink
TSharedPtr<IMessageToken> FTokenizedMessage::MessageLink protected
A token associated with the entire message (doesn't display)
Definition at line 241 of file TokenizedMessage.h.
MessageTokens
TArray< TSharedRef<IMessageToken> > FTokenizedMessage::MessageTokens protected
the array of message tokens this message contains
Definition at line 238 of file TokenizedMessage.h.
Severity
EMessageSeverity::Type FTokenizedMessage::Severity private
The severity of this message.
Definition at line 246 of file TokenizedMessage.h.
Referenced by FTokenizedMessage().
The documentation for this class was generated from the following file:
TokenizedMessage.h