Unreal Engine 5.6 C++ API: SGraphPanel Class Reference
SGraphPanel Class Reference
#include "SGraphPanel.h"
Public Member Functions
PRAGMA_ENABLE_DEPRECATION_WARNINGS SLATE_EVENT_DEPRECATED(5.6, "Use SGraphEditor::FOnSpawnNodeByShortcutAtLocation.", PRAGMA_DISABLE_DEPRECATION_WARNINGS SGraphEditor::FOnSpawnNodeByShortcut PRAGMA_ENABLE_DEPRECATION_WARNINGS, OnSpawnNodeByShortcut, OnSpawnNodeByShortcutAtLocation, ConvertOnSpawnNodeByShortcutDelegate) SLATE_EVENT(SGraphEditor ~SGraphPanel ()
Construct a widget.
virtual void AddGraphNode (const TSharedRef< SNode > &NodeToAdd) override
Add a slot to the CanvasPanel dynamically.
void AddPinToHoverSet (UEdGraphPin *HoveredPin)
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void ArrangeChildrenForContextMenuSummon (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const
void AttachGraphEvents (TSharedPtr< SGraphNode > CreatedSubNode)
helper to attach graph events to sub node, which won't be placed directly on the graph
virtual bool CustomPrepass (float LayoutScaleMultiplier) override
DECLARE_DELEGATE_RetVal_OneParam (FActionMenuContent, FOnGetContextMenuFor, const FGraphContextMenuArguments &) SLATE_BEGIN_ARGS(SGraphPanel)
void DismissContextMenu ()
void GetAllPins (TSet< TSharedRef< SWidget > > &AllPins)
bool GetBoundsForNode (const UObject *InNode, FVector2f &MinCorner, FVector2f &MaxCorner, float Padding=0.0f) const
UEdGraph * GetGraphObj () const
TSharedPtr< SGraphNode > GetNodeWidgetFromGuid (FGuid Guid) const
Get a graph node widget from the specified GUID, if it applies to any nodes in this graph.
SGraphEditor::EPinVisibility GetPinVisibility () const
const FGraphSplineOverlapResult & GetPreviousFrameSplineOverlap () const
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
TArray< UEdGraphNode * > GetSelectedGraphNodes () const
Get a list of selected editor graph nodes from the selection manager.
EActiveTimerReturnType InvalidatePerTick (double InCurrentTime, float InDeltaTime)
When the graph panel needs to be dynamically refreshing for animations, this function is registered to tick and invalidate the UI.
bool IsGraphEditable () const
Returns if this graph is editable.
bool IsNodeTitleVisible (const class UEdGraphNode *Node, bool bRequestRename)
Use to determine if a comment title is currently visible.
bool IsRectVisible (const UE::Slate::FDeprecateVector2DParameter &TopLeft, const UE::Slate::FDeprecateVector2DParameter &BottomRight)
Use to determine if a rectangle is currently visible.
bool IsRelinkingConnection () const
True in case a connection is currently being relinked, false if not.
void JumpToNode (const class UEdGraphNode *JumpToMe, bool bRequestRename, bool bSelectNode)
void JumpToPin (const class UEdGraphPin *JumptToMe)
bool JumpToRect (const UE::Slate::FDeprecateVector2DParameter &BottomLeft, const UE::Slate::FDeprecateVector2DParameter &TopRight)
Focuses the view on rectangle, zooming if neccesary.
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Panels arrange their children in a space described by the AllottedGeometry parameter.
void OnBeginMakingConnection (FGraphPinHandle PinHandle)
void OnBeginMakingConnection (UEdGraphPin *InOriginatingPin)
void OnBeginRelinkConnection (const FGraphPinHandle &InSourcePinHandle, const FGraphPinHandle &InTargetPinHandle)
Indicate that the connection from the given start to the given end pins is being relinked.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
void OnEndRelinkConnection (bool bForceStop=false)
The relink connection operation either got cancelled or has successfully been executed.
virtual bool OnHandleLeftMouseRelease (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
void OnStopMakingConnection (bool bForceStop=false)
virtual TSharedPtr< SWidget > OnSummonContextMenu (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
void PreservePinPreviewUntilForced ()
void PurgeVisualRepresentation ()
Purges the existing visual representation (typically followed by an Update call in the next tick)
void RefreshNode (UEdGraphNode &Node)
Refresh the visual state of a single node.
virtual void RemoveAllNodes () override
Remove all nodes from the panel.
void RemovePinFromHoverSet (UEdGraphPin *UnhoveredPin)
void SetNodeFactory (const TSharedRef< class FGraphNodeFactory > &NewNodeFactory)
Sets the current widget factory.
void SetPinVisibility (SGraphEditor::EPinVisibility InVisibility)
SLATE_EVENT (FOnGetContextMenuFor, OnGetContextMenuFor) SLATE_EVENT(SGraphEditor
SLATE_EVENT_DEPRECATED (5.6, "Use SGraphEditor::FOnDropActors.", SGraphEditor::FOnDropActor, OnDropActor, OnDropActors, ConvertOnDropActorDelegate) static SGraphEditor
SLATE_EVENT_DEPRECATED (5.6, "Use SGraphEditor::FOnDropStreamingLevels.", SGraphEditor::FOnDropStreamingLevel, OnDropStreamingLevel, OnDropStreamingLevels, ConvertOnDropStreamingLevelDelegate) PRAGMA_ENABLE_DEPRECATION_WARNINGS SLATE_EVENT(SGraphEditor
Show overlay elements for the graph state such as the PIE and read-only borders and text.
void StraightenConnections ()
Straighten all connections between the selected nodes.
void StraightenConnections (UEdGraphPin *SourcePin, UEdGraphPin *PinToAlign=nullptr)
Straighten any connections attached to the specified pin, optionally limiting to the specified pin to align.
TSharedPtr< SWidget > SummonContextMenu (const UE::Slate::FDeprecateVector2DParameter &WhereToSummon, const UE::Slate::FDeprecateVector2DParameter &WhereToAddNode, UEdGraphNode *ForNode, UEdGraphPin *ForPin, const TArray< UEdGraphPin * > &DragFromPins)
void SummonCreateNodeMenuFromUICommand (uint32 NumNodesAdded)
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") bool GetBoundsForNode(const UObject *InNode
Attempt to retrieve the bounds for the specified node.
void Update ()
Update this GraphPanel to match the data that it is observing.
Public Member Functions inherited from SNodePanel
SNodePanel ()
virtual FVector2D ComputeDesiredSize (float) const override
A Panel's desired size in the space required to arrange of its children on the screen while respecting all of the children's desired sizes and any layout-related options specified by the user.
bool Contains (UObject *Node) const
Is the given node being observed by a widget in this panel?
void FinalizeNodeMovements ()
Commit transactions for any node movements.
FChildren * GetAllChildren ()
Returns all the panel children rather than only visible.
bool GetBoundsForSelectedNodes (class FSlateRect &Rect, float Padding=0.0f)
Get the bounding area for the currently selected nodes.
virtual FChildren * GetChildren () override
All widgets must provide a way to access their children in a layout-agnostic way.
UObject * GetCurrentHoveredNode ()
EGraphRenderingLOD::Type GetCurrentLOD () const
Returns the current LOD level of this panel, based on the zoom factor.
UE::Slate::FDeprecateVector2DResult GetPastePosition () const
virtual float GetRelativeLayoutScale (int32 ChildIndex, float LayoutScaleMultiplier) const override
What is the Child's scale relative to this widget.
const FGuid & GetViewBookmarkId () const
UE::Slate::FDeprecateVector2DResult GetViewOffset () const
float GetZoomAmount () const
@retun the zoom amount; e.g.
bool GetZoomTargetRect (FVector2f &TopLeft, FVector2f &BottomRight) const
FText GetZoomText () const
FSlateColor GetZoomTextColorAndOpacity () const
bool HasDeferredObjectFocus () const
If it is focusing on a particular object.
bool HasDeferredZoomDestination () const
Query whether this graph is about to start panning/zooming towards a destination.
bool HasMoved () const
Returns if the panel has been panned or zoomed since the last update.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when the mouse wheel is spun.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent) override
Called when the user performs a gesture on trackpad.
UE::Slate::FDeprecateVector2DResult PanelCoordToGraphCoord (const UE::Slate::FDeprecateVector2DParameter &PanelSpaceCoordinate) const
Given a coordinate in panel space (i.e.
void RequestDeferredPan (const UE::Slate::FDeprecateVector2DParameter &TargetPosition)
Ask panel to scroll to location.
void RestoreViewSettings (const UE::Slate::FDeprecateVector2DParameter &InViewOffset, float InZoomAmount, const FGuid &InBookmarkGuid=FGuid())
Restore the graph panel to the supplied view offset/zoom.
void SetCurrentHoveredNode (UObject *InNode)
template<typename T>
void SetZoomLevelsContainer ()
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") bool GetZoomTargetRect(FVector2D &TopLeft
when a panel is scrolling/zooming to a target, this can be called to get it's destination
void ZoomToFit (bool bOnlySelection)
Zooms out to fit either all nodes or only the selected ones.
Public Member Functions inherited from SPanel
void Construct ()
Most panels do not create widgets as part of their implementation, so they do not need to implement a Construct()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Data Fields
TWeakPtr< SGraphPin > MarkedPin
Pin marked via shift-clicking.
FVector2D FVector2D & MaxCorner
FVector2D & MinCorner
FVector2D FVector2D float Padding = 0.0f) const
Data Fields inherited from SNodePanel
FVector2D &BottomRight const
FGraphSelectionManager SelectionManager
Nodes selected in this instance of the editor; the selection is per-instance of the GraphEditor.
Protected Types
enum AddNodeBehavior { CheckUserAddedNodesList , WasUserAdded , NotUserAdded }
Flag to control AddNode, more readable than a bool:
Protected Member Functions
void AddNode (class UEdGraphNode *Node, AddNodeBehavior Behavior)
Helper method to add a new node to the panel.
const TSharedRef< SGraphNode > GetChild (int32 ChildIndex)
void NotifyGraphChanged (const struct FEdGraphEditAction &InAction)
void RemoveAllNodesWithInvalidPointers ()
Helper method to remove all nodes from the panel holding garbage / invalid pointers.
void RemoveNode (const UEdGraphNode *Node)
Helper method to remove a node from the panel.
Protected Member Functions inherited from SNodePanel
virtual void ArrangeChildNodes (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const
Arrange child nodes - allows derived classes to supply non-node children in OnArrangeChildren.
void CancelZoomToFit ()
void CenterObject (const UObject *ObjectToCenter)
On the next tick, centers the widget associated with the object if it exists.
void ChangeZoomLevel (int32 ZoomLevelDelta, const FVector2f &WidgetSpaceZoomOrigin, bool bOverrideZoomLimiting)
Change zoom level by the specified zoom level delta, about the specified origin.
void Construct ()
Initialize members.
void FindNodesAffectedByMarquee (FGraphPanelSelectionSet &OutAffectedNodes) const
Figure out which nodes intersect the marquee rectangle.
bool GetBoundsForNode (const UObject *InNode, FVector2f &MinCorner, FVector2f &MaxCorner, float Padding=0.0f) const
bool GetBoundsForNodes (bool bSelectionSetOnly, FVector2f &MinCorner, FVector2f &MaxCorner, float Padding=0.0f) const
FVector2f GraphCoordToPanelCoord (const UE::Slate::FDeprecateVector2DParameter &GraphSpaceCoordinate) const
Given a coordinate in graph space (e.g.
bool IsNodeCulled (const TSharedRef< SNode > &Node, const FGeometry &AllottedGeometry) const
Determines if a specified node is not visually relevant.
virtual void OnBeginNodeInteraction (const TSharedRef< SNode > &InNodeToDrag, const FVector2D &GrabOffset) UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Lets the CanvasPanel know that the user is interacting with a node.
virtual void OnBeginNodeInteraction (const TSharedRef< SNode > &InNodeToDrag, const FVector2f &GrabOffset)
virtual void OnEndNodeInteraction (const TSharedRef< SNode > &InNodeToDrag)
Lets the CanvasPanel know that the user has ended interacting with a node.
void PaintBackgroundAsLines (const FSlateBrush *BackgroundImage, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 &DrawLayerId) const
void PaintComment (const FString &CommentText, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 DrawLayerId, const FLinearColor &CommentTinting, float &HeightAboveNode, const FWidgetStyle &InWidgetStyle) const
void PaintMarquee (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 DrawLayerId) const
void PaintSoftwareCursor (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 DrawLayerId) const
void PaintSurroundSunkenShadow (const FSlateBrush *ShadowImage, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 DrawLayerId) const
FSlateRect PanelRectToGraphRect (const FSlateRect &PanelSpaceRect) const
Given a rectangle in panel space, return a rectangle in graph space.
virtual void PopulateVisibleChildren (const FGeometry &AllottedGeometry)
Populate visibile children array.
void PostChangedZoom ()
void RequestZoomToFit ()
bool ScrollToLocation (const FGeometry &MyGeometry, FVector2f DesiredCenterPosition, const float InDeltaTime)
Scroll the view to the desired location.
void SelectAndCenterObject (const UObject *ObjectToSelect, bool bCenter)
On the next tick, centers and selects the widget associated with the object if it exists.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") bool GetBoundsForNode(const UObject *InNode
Get the bounds of the given node.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") bool GetBoundsForNodes(bool bSelectionSetOnly
Get the bounds of the selected nodes.
void UpdateViewOffset (const FGeometry &MyGeometry, const FVector2f &TargetPosition)
Update the new view offset location.
bool ZoomToLocation (const FVector2f &CurrentSizeWithoutZoom, const FVector2f &DesiredSize, bool bDoneScrolling)
Zoom to fit the desired size.
void ZoomToTarget (const FVector2f &TopLeft, const FVector2f &BottomRight)
Zooms to the specified target rect.
Protected Member Functions inherited from SPanel
SPanel ()
Hidden default constructor.
virtual ~SPanel ()
int32 PaintArrangedChildren (const FPaintArgs &Args, const FArrangedChildren &ArrangedChildren, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Just like OnPaint, but takes already arranged children.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bIsDrawStateCached = false
FCurveSequence BounceCurve
Bouncing curve.
bool bPreservePinPreviewConnection
bool bShowPIENotification
Whether to draw the overlay indicating we're in PIE.
FDeprecateSlateVector2D CachedAllottedGeometryScaledSize
Geometry cache.
TSet< FEdGraphPinReference > CurrentHoveredPins
List of pins currently being hovered over.
TSharedPtr< TArray< FDiffSingleResult > > DiffResults
TAttribute< int32 > FocusedDiffResult
TObjectPtr< UEdGraph > GraphObj
FPointerEvent LastPointerEvent
FGeometry LastPointerGeometry
The mouse state from the last mouse move event, used to synthesize pin actions when hovering over a spline on the panel.
SGraphEditor::FOnMouseButtonDown OnClicked
Called when the graph itself is clicked.
SGraphEditor::FOnDisallowedPinConnection OnDisallowedPinConnection
Called when the user generates a warning tooltip because a connection was invalid.
SGraphEditor::FOnDoubleClicked OnDoubleClicked
Called when the graph itself is double clicked.
SGraphEditor::FOnDropActors OnDropActors
Invoked when an actor is dropped onto the panel.
SGraphEditor::FOnDropStreamingLevels OnDropStreamingLevels
Invoked when a streaming level is dropped onto the panel.
FOnGetContextMenuFor OnGetContextMenuFor
Invoked when we need to summon a context menu.
FSingleNodeEvent OnNodeDoubleClicked
What to do when a node is double-clicked.
FOnNodeTextCommitted OnTextCommitted
Invoked when text is committed on panel.
FOnUpdateGraphPanel OnUpdateGraphPanel
Invoked when the panel is updated.
FOnNodeVerifyTextCommit OnVerifyTextCommit
Invoked when text is being committed on panel to verify it.
SGraphEditor::EPinVisibility PinVisibility
Pin visibility mode.
FDeprecateSlateVector2D PreviewConnectorEndpoint
TArray< FGraphPinHandle > PreviewConnectorFromPins
Sometimes the panel draws a preview connector; e.g.
FDeprecateSlateVector2D PreviousFrameSavedMousePosForSplineOverlap
The overlap results from the previous OnPaint call.
FGraphSplineOverlapResult PreviousFrameSplineOverlap
FDeprecateSlateVector2D SavedMousePosForOnPaintEventLocalSpace
Last mouse position seen, used for paint-centric highlighting.
TAttribute< bool > ShowGraphStateOverlay
Whether to draw decorations for graph state (PIE / ReadOnly etc.)
double TimeWhenMouseEnteredPin
Time since the last mouse enter/exit on a pin.
double TimeWhenMouseLeftPin
Protected Attributes inherited from SNodePanel
bool bAllowContinousZoomInterpolation
Allow continous zoom interpolation?
bool bDeferredZoomToNodeExtents
Deferred zoom to node extents.
bool bDeferredZoomToSelection
Deferred zoom to selected node extents.
bool bIsPanning
Are we panning the view at the moment?
bool bIsZoomingWithTrackpad
Are we zooming the view with trackpad at the moment?
bool bRequestDeferredPan
true if pending request for deferred panning
bool bShowSoftwareCursor
Whether the software cursor should be drawn.
bool bTeleportInsteadOfScrollingWhenZoomingToFit
Teleport immediately, or smoothly scroll when doing a deferred zoom.
bool bVisualUpdatePending
A flag to detect when a visual update is pending to prevent deferred commands like zoom to fit from running when there are no widgets.
FGeometry CachedGeometry
Cached geometry for use within the active timer.
TSlotlessChildren< SNode > Children
The graph node widgets owned by this panel.
TObjectPtr< class UObject > CurrentHoveredNode
The currently hovered SNode's UObject.
EGraphRenderingLOD::Type CurrentLOD
Current LOD level for nodes/pins.
const UObject * DeferredMovementTargetObject
If non-null and a part of this panel, this node will be brought into view on the next Tick.
FDeprecateSlateVector2D DeferredPanPosition
Position to pan to.
TSet< const UObject * > DeferredSelectionTargetObjects
If not empty and a part of this panel, this node will be selected and brought into view on the next Tick.
TAttribute< bool > IsEditable
Is the graph editable (can nodes be moved, etc...)?
FInputChord LastKeyChordDetected
The last key chord detected in this graph panel.
FMarqueeOperation Marquee
A pending marquee operation if it's active.
FVector2D FVector2D & MaxCorner
FVector2D & MinCorner
FDeprecateSlateVector2D NodeGrabOffset
Where in the title the user grabbed to initiate the drag.
TMap< UObject *, TSharedRef< SNode > > NodeToWidgetLookup
Given a node, find the corresponding widget.
TWeakPtr< SNode > NodeUnderMousePtr
The node that the user is dragging.
FDeprecateSlateVector2D OldViewOffset
The position within the graph at which the user was looking last tick.
float OldZoomAmount
The actual scalar zoom amount last tick.
SGraphEditor::FOnNodeSingleClicked OnNodeSingleClicked
Called when the user left clicks on a node without dragging.
SGraphEditor::FOnSpawnNodeByShortcutAtLocation OnSpawnNodeByShortcutAtLocation
Invoked when the user may be attempting to spawn a node using a shortcut.
TMap< TWeakPtr< SNode >, FVector2f > OriginalNodePositions
Node positions pre-drag, used to limit transaction creation on drag.
FVector2D FVector2D float Padding = 0.0f) const
FDeprecateSlateVector2D PastePosition
The position where we should paste when a user executes the paste command.
int32 PreviousZoomLevel
Previous Zoom Level.
TSharedPtr< FScopedTransaction > ScopedTransactionPtr
The current transaction for undo/redo.
FDeprecateSlateVector2D SoftwareCursorPosition
The current position of the software cursor.
float TotalGestureMagnify
Cumulative magnify delta from trackpad gesture.
float TotalMouseDelta
The total distance that the mouse has been dragged while down.
float TotalMouseDeltaXY
The additive X and Y components of mouse drag (used when zooming)
FDeprecateSlateVector2D ViewOffset
The position within the graph at which the user is looking.
TSlotlessChildren< SNode > VisibleChildren
int32 ZoomLevel
How zoomed in/out we are.
FCurveSequence ZoomLevelFade
Curve that handles fading the 'Zoom +X' text.
FCurveSequence ZoomLevelGraphFade
Fade on zoom for graph.
TUniquePtr< FZoomLevelsContainer > ZoomLevels
float ZoomPadding
Zoom selection padding.
FDeprecateSlateVector2D ZoomStartOffset
Offset in the panel the user started the LMB+RMB zoom from.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
void AdjustNewlySpawnedNodePositions (TArrayView< UEdGraphNode *const > SpawnedNodes, TArrayView< UEdGraphPin * > DraggedFromPins, FVector2f SpawnGraphPosition)
If the spawned nodes were auto-wired from any of the dragged pins, then this will try to make the newly connected pin end up at SpawnGraphPosition.
class SGraphPin * GetBestPinFromHoveredSpline () const
Returns the pin that we're considering as hovered if we are hovering over a spline; may be null.
TSharedPtr< SGraphNode > GetGraphNodeUnderMouse (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Returns the top most graph node under the mouse pointer.
UEdGraphPin * GetPinUnderMouse (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent, TSharedPtr< SGraphNode > GraphNode) const
Returns a pin that is under the mouse, given a specified node.
void MoveNodesToAnchorPinAtGraphPosition (TArrayView< UEdGraphNode *const > NodesToMove, FGraphPinHandle PinToAnchor, FVector2f DesiredPinGraphPosition)
Will move a group of nodes by the amount needed for an anchor pin to be at a certain position.
void OnBeginPIE (const bool bIsSimulating)
Called when PIE begins.
void OnEndPIE (const bool bIsSimulating)
Called when PIE ends.
void OnGraphChanged (const FEdGraphEditAction &InAction)
Called when watched graph changes.
FReply OnMouseDownDisconnectClosestPinFromWire (TSharedRef< class SGraphPin > ClosestPin, TSharedRef< class SGraphPin > ConnectedPin)
Begins a drag operation that disconnects the pin at ClosestPin, but only from the ConnectedPin, rather than all connections.
bool OnSplineHoverStateChanged (const FGraphSplineOverlapResult &NewSplineHoverState)
Handle updating the spline hover state.
bool PassesAssetReferenceFilter (const TArray< FAssetData > &ReferencedAssets, FText *OutFailureReason=nullptr) const
Returns true if all assets in the ReferencedAssets array are allowed to be referenced by this graph according to the AssetReferenceFilter.
void UpdateSelectedNodesPositions (const FVector2f &PositionIncrement)
Update all selected nodes position by provided vector2d.
Private Attributes
TWeakPtr< FActiveTimerHandle > ActiveTimerHandleInvalidatePerTick
Handle to timer callback that allows the UI to refresh it's arrangement each tick, allows animations to occur within the UI.
bool bCheckNodeGraphObjValidity
A flag indicating that we need to check if we have any nodes which use invalid pointers.
TWeakPtr< IMenu > ContextMenu
Weak pointer to the last summoned context menu, for dismissing it when requested.
TAttribute< bool > DisplayAsReadOnly
Should the graph display all nodes in a read-only state (grayed)?
FOnGraphChanged::FDelegate MyRegisteredGraphChangedDelegate
FDelegateHandle MyRegisteredGraphChangedDelegateHandle
TSharedPtr< class FGraphNodeFactory > NodeFactory
The current node factory to create nodes, pins and connections.
TMap< FGuid, TWeakPtr< SGraphNode > > NodeGuidMap
A map of guid -> graph nodes.
TArray< FConnectionDrawingPolicy::FRelinkConnection > RelinkConnections
List of currently relinked connections.
float TimeLeftToInvalidatePerTick
Amount of time left to invalidate the UI per tick.
TSet< const class UEdGraphNode * > UserAddedNodes
Set of user-added nodes for the panel, tracked while a visual update is pending.
TSet< TWeakObjectPtr< class UEdGraphNode > > UserSelectedNodes
Set of nodes selected by the user, tracked while a visual update is pending.
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from SNodePanel
static uint32 GetSnapGridSize ()
Get the grid snap size.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from SNodePanel
static void ApplyMarqueeSelection (const FMarqueeOperation &InMarquee, const FGraphPanelSelectionSet &CurrentSelection, TSet< TObjectPtr< UObject > > &OutNewSelection)
Apply the marquee operation to the current selection.
static FVector2f ComputeEdgePanAmount (const FGeometry &MyGeometry, const FVector2f &MouseEvent)
Compute much panel needs to change to pan to location.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 75 of file SGraphPanel.h.
Member Enumeration Documentation
AddNodeBehavior
enum SGraphPanel::AddNodeBehavior protected
Flag to control AddNode, more readable than a bool:
Enumerator
CheckUserAddedNodesList
WasUserAdded
NotUserAdded
Definition at line 289 of file SGraphPanel.h.
Constructor & Destructor Documentation
~SGraphPanel()
PRAGMA_ENABLE_DEPRECATION_WARNINGS SLATE_EVENT_DEPRECATED(5.6, "Use SGraphEditor::FOnSpawnNodeByShortcutAtLocation.", PRAGMA_DISABLE_DEPRECATION_WARNINGS SGraphEditor::FOnSpawnNodeByShortcut PRAGMA_ENABLE_DEPRECATION_WARNINGS, OnSpawnNodeByShortcut, OnSpawnNodeByShortcutAtLocation, ConvertOnSpawnNodeByShortcutDelegate) SLATE_EVENT(SGraphEditor SGraphPanel::~SGraphPanel ()
Construct a widget.
Parameters
InArgs The declaration describing how the widgets should be constructed.
Member Function Documentation
AddGraphNode()
virtual void SGraphPanel::AddGraphNode (const TSharedRef< SNode > & NodeToAdd) override virtual
Add a slot to the CanvasPanel dynamically.
Reimplemented from SNodePanel.
References AddGraphNode(), and SNodePanel::const.
Referenced by AddGraphNode().
AddNode()
void SGraphPanel::AddNode (class UEdGraphNode * Node, AddNodeBehavior Behavior) protected
Helper method to add a new node to the panel.
AddPinToHoverSet()
void SGraphPanel::AddPinToHoverSet (UEdGraphPin * HoveredPin)
References AddPinToHoverSet().
Referenced by AddPinToHoverSet().
AddReferencedObjects()
virtual void SGraphPanel::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
References AddReferencedObjects().
Referenced by AddReferencedObjects().
AdjustNewlySpawnedNodePositions()
void SGraphPanel::AdjustNewlySpawnedNodePositions (TArrayView< UEdGraphNode *const > SpawnedNodes, TArrayView< UEdGraphPin * > DraggedFromPins, FVector2f SpawnGraphPosition) private
If the spawned nodes were auto-wired from any of the dragged pins, then this will try to make the newly connected pin end up at SpawnGraphPosition.
ArrangeChildrenForContextMenuSummon()
void SGraphPanel::ArrangeChildrenForContextMenuSummon (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const
References ArrangeChildrenForContextMenuSummon(), and SNodePanel::const.
Referenced by ArrangeChildrenForContextMenuSummon().
AttachGraphEvents()
void SGraphPanel::AttachGraphEvents (TSharedPtr< SGraphNode > CreatedSubNode)
helper to attach graph events to sub node, which won't be placed directly on the graph
CustomPrepass()
virtual bool SGraphPanel::CustomPrepass (float LayoutScaleMultiplier) override virtual
Reimplemented from SWidget.
References CustomPrepass().
Referenced by CustomPrepass().
DECLARE_DELEGATE_RetVal_OneParam()
SGraphPanel::DECLARE_DELEGATE_RetVal_OneParam (FActionMenuContent , FOnGetContextMenuFor , const FGraphContextMenuArguments &) inline
Definition at line 78 of file SGraphPanel.h.
DismissContextMenu()
void SGraphPanel::DismissContextMenu ()
References DismissContextMenu().
Referenced by DismissContextMenu().
GetAllPins()
void SGraphPanel::GetAllPins (TSet< TSharedRef< SWidget > > & AllPins)
References SWidget::SWidget(), and GetAllPins().
Referenced by GetAllPins().
GetBestPinFromHoveredSpline()
class SGraphPin * SGraphPanel::GetBestPinFromHoveredSpline () const private
Returns the pin that we're considering as hovered if we are hovering over a spline; may be null.
GetBoundsForNode()
bool SGraphPanel::GetBoundsForNode (const UObject * InNode, FVector2f & MinCorner, FVector2f & MaxCorner, float Padding = 0.0f) const
References SNodePanel::const, GetBoundsForNode(), MaxCorner, MinCorner, and Padding.
Referenced by GetBoundsForNode().
GetChild()
const TSharedRef< SGraphNode > SGraphPanel::GetChild (int32 ChildIndex) protected
References SNodePanel::const, and GetChild().
Referenced by GetChild().
GetGraphNodeUnderMouse()
TSharedPtr< SGraphNode > SGraphPanel::GetGraphNodeUnderMouse (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) private
Returns the top most graph node under the mouse pointer.
Returns nullptr if no node found
References MouseEvent.
GetGraphObj()
UEdGraph * SGraphPanel::GetGraphObj () const inline
Definition at line 254 of file SGraphPanel.h.
References GraphObj.
GetNodeWidgetFromGuid()
TSharedPtr< SGraphNode > SGraphPanel::GetNodeWidgetFromGuid (FGuid Guid) const
Get a graph node widget from the specified GUID, if it applies to any nodes in this graph.
References Guid.
GetPinUnderMouse()
UEdGraphPin * SGraphPanel::GetPinUnderMouse (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent, TSharedPtr< SGraphNode > GraphNode) const private
Returns a pin that is under the mouse, given a specified node.
Returns nullptr if no valid node is given or no pin found
References MouseEvent.
GetPinVisibility()
SGraphEditor::EPinVisibility SGraphPanel::GetPinVisibility () const inline
Definition at line 251 of file SGraphPanel.h.
References GetPinVisibility(), and PinVisibility.
Referenced by GetPinVisibility().
GetPreviousFrameSplineOverlap()
const FGraphSplineOverlapResult & SGraphPanel::GetPreviousFrameSplineOverlap () const inline
Definition at line 314 of file SGraphPanel.h.
References PreviousFrameSplineOverlap.
GetReferencerName()
virtual FString SGraphPanel::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
References SNodePanel::const, and GetReferencerName().
Referenced by GetReferencerName().
GetSelectedGraphNodes()
TArray< UEdGraphNode * > SGraphPanel::GetSelectedGraphNodes () const
Get a list of selected editor graph nodes from the selection manager.
InvalidatePerTick()
EActiveTimerReturnType SGraphPanel::InvalidatePerTick (double InCurrentTime, float InDeltaTime)
When the graph panel needs to be dynamically refreshing for animations, this function is registered to tick and invalidate the UI.
References InvalidatePerTick().
Referenced by InvalidatePerTick().
IsGraphEditable()
bool SGraphPanel::IsGraphEditable () const inline
Returns if this graph is editable.
Definition at line 260 of file SGraphPanel.h.
References SNodePanel::IsEditable.
IsNodeTitleVisible()
bool SGraphPanel::IsNodeTitleVisible (const class UEdGraphNode * Node, bool bRequestRename)
Use to determine if a comment title is currently visible.
References SNodePanel::const, and IsNodeTitleVisible().
Referenced by IsNodeTitleVisible().
IsRectVisible()
bool SGraphPanel::IsRectVisible (const UE::Slate::FDeprecateVector2DParameter & TopLeft, const UE::Slate::FDeprecateVector2DParameter & BottomRight)
Use to determine if a rectangle is currently visible.
References BottomRight, SNodePanel::const, IsRectVisible(), and TopLeft.
Referenced by IsRectVisible().
IsRelinkingConnection()
bool SGraphPanel::IsRelinkingConnection () const
True in case a connection is currently being relinked, false if not.
References SNodePanel::const, and IsRelinkingConnection().
Referenced by IsRelinkingConnection().
JumpToNode()
void SGraphPanel::JumpToNode (const class UEdGraphNode * JumpToMe, bool bRequestRename, bool bSelectNode)
References SNodePanel::const, and JumpToNode().
Referenced by JumpToNode().
JumpToPin()
void SGraphPanel::JumpToPin (const class UEdGraphPin * JumptToMe)
References SNodePanel::const, and JumpToPin().
Referenced by JumpToPin().
JumpToRect()
bool SGraphPanel::JumpToRect (const UE::Slate::FDeprecateVector2DParameter & BottomLeft, const UE::Slate::FDeprecateVector2DParameter & TopRight)
Focuses the view on rectangle, zooming if neccesary.
References BottomLeft, SNodePanel::const, JumpToRect(), and TopRight.
Referenced by JumpToRect().
MoveNodesToAnchorPinAtGraphPosition()
void SGraphPanel::MoveNodesToAnchorPinAtGraphPosition (TArrayView< UEdGraphNode *const > NodesToMove, FGraphPinHandle PinToAnchor, FVector2f DesiredPinGraphPosition) private
Will move a group of nodes by the amount needed for an anchor pin to be at a certain position.
NotifyGraphChanged()
void SGraphPanel::NotifyGraphChanged (const struct FEdGraphEditAction & InAction) protected
References SNodePanel::const, and NotifyGraphChanged().
Referenced by NotifyGraphChanged().
OnArrangeChildren()
virtual void SGraphPanel::OnArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const override virtual
Panels arrange their children in a space described by the AllottedGeometry parameter.
The results of the arrangement should be returned by appending a FArrangedWidget pair for every child widget. See StackPanel for an example
Parameters
AllottedGeometry The geometry allotted for this widget by its parent.
ArrangedChildren The array to which to add the WidgetGeometries that represent the arranged children.
Reimplemented from SNodePanel.
References SNodePanel::const, and OnArrangeChildren().
Referenced by OnArrangeChildren().
OnBeginMakingConnection() [1/2]
void SGraphPanel::OnBeginMakingConnection (FGraphPinHandle PinHandle)
References OnBeginMakingConnection().
OnBeginMakingConnection() [2/2]
void SGraphPanel::OnBeginMakingConnection (UEdGraphPin * InOriginatingPin)
References OnBeginMakingConnection().
Referenced by OnBeginMakingConnection(), and OnBeginMakingConnection().
OnBeginPIE()
void SGraphPanel::OnBeginPIE (const bool bIsSimulating) private
Called when PIE begins.
OnBeginRelinkConnection()
void SGraphPanel::OnBeginRelinkConnection (const FGraphPinHandle & InSourcePinHandle, const FGraphPinHandle & InTargetPinHandle)
Indicate that the connection from the given start to the given end pins is being relinked.
A preview connection is being drawn for the relinked connection.
References SNodePanel::const, and OnBeginRelinkConnection().
Referenced by OnBeginRelinkConnection().
OnDragEnter()
virtual void SGraphPanel::OnDragEnter (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag enters a widget.
Enter/Leave events in slate are meant as lightweight notifications. So we do not want to capture mouse or set focus in response to these. However, OnDragEnter must also support external APIs (e.g. OLE Drag/Drop) Those require that we let them know whether we can handle the content being dragged OnDragEnter.
The concession is to return a can_handled/cannot_handle boolean rather than a full FReply.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether the contents of the DragDropEvent can potentially be processed by this widget.
Reimplemented from SWidget.
References SNodePanel::const, and OnDragEnter().
Referenced by OnDragEnter().
OnDragLeave()
virtual void SGraphPanel::OnDragLeave (const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag leaves a widget.
Parameters
DragDropEvent The drag and drop event.
Reimplemented from SWidget.
References SNodePanel::const, and OnDragLeave().
Referenced by OnDragLeave().
OnDragOver()
virtual FReply SGraphPanel::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References SNodePanel::const, and OnDragOver().
Referenced by OnDragOver().
OnDrop()
virtual FReply SGraphPanel::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References SNodePanel::const, and OnDrop().
Referenced by OnDrop().
OnEndPIE()
void SGraphPanel::OnEndPIE (const bool bIsSimulating) private
Called when PIE ends.
OnEndRelinkConnection()
void SGraphPanel::OnEndRelinkConnection (bool bForceStop = false)
The relink connection operation either got cancelled or has successfully been executed.
Preview connection won't be drawn anymore.
References OnEndRelinkConnection().
Referenced by OnEndRelinkConnection().
OnGraphChanged()
void SGraphPanel::OnGraphChanged (const FEdGraphEditAction & InAction) private
Called when watched graph changes.
OnHandleLeftMouseRelease()
virtual bool SGraphPanel::OnHandleLeftMouseRelease (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Reimplemented from SNodePanel.
References SNodePanel::const, MouseEvent, and OnHandleLeftMouseRelease().
Referenced by OnHandleLeftMouseRelease().
OnKeyDown()
virtual FReply SGraphPanel::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SNodePanel.
References SNodePanel::const, and OnKeyDown().
Referenced by OnKeyDown().
OnMouseButtonDoubleClick()
virtual FReply SGraphPanel::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References SNodePanel::const, and OnMouseButtonDoubleClick().
Referenced by OnMouseButtonDoubleClick().
OnMouseButtonDown()
virtual FReply SGraphPanel::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SNodePanel.
References SNodePanel::const, MouseEvent, and OnMouseButtonDown().
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
virtual FReply SGraphPanel::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SNodePanel.
References SNodePanel::const, MouseEvent, and OnMouseButtonUp().
Referenced by OnMouseButtonUp().
OnMouseDownDisconnectClosestPinFromWire()
FReply SGraphPanel::OnMouseDownDisconnectClosestPinFromWire (TSharedRef< class SGraphPin > ClosestPin, TSharedRef< class SGraphPin > ConnectedPin) private
Begins a drag operation that disconnects the pin at ClosestPin, but only from the ConnectedPin, rather than all connections.
OnMouseMove()
virtual FReply SGraphPanel::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SNodePanel.
References SNodePanel::const, MouseEvent, and OnMouseMove().
Referenced by OnMouseMove().
OnPaint()
virtual int32 SGraphPanel::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from SPanel.
References SNodePanel::const, SWidget::FSlateWindowElementList, and OnPaint().
Referenced by OnPaint().
OnSplineHoverStateChanged()
bool SGraphPanel::OnSplineHoverStateChanged (const FGraphSplineOverlapResult & NewSplineHoverState) private
Handle updating the spline hover state.
OnStopMakingConnection()
void SGraphPanel::OnStopMakingConnection (bool bForceStop = false)
References OnStopMakingConnection().
Referenced by OnStopMakingConnection().
OnSummonContextMenu()
virtual TSharedPtr< SWidget > SGraphPanel::OnSummonContextMenu (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Returns
the widget in the summoned context menu that should be focused.
Reimplemented from SNodePanel.
References SWidget::SWidget(), SNodePanel::const, MouseEvent, and OnSummonContextMenu().
Referenced by OnSummonContextMenu().
PassesAssetReferenceFilter()
bool SGraphPanel::PassesAssetReferenceFilter (const TArray< FAssetData > & ReferencedAssets, FText * OutFailureReason = nullptr) const private
Returns true if all assets in the ReferencedAssets array are allowed to be referenced by this graph according to the AssetReferenceFilter.
OutFailureReason if supplied if it is not.
PreservePinPreviewUntilForced()
void SGraphPanel::PreservePinPreviewUntilForced ()
References PreservePinPreviewUntilForced().
Referenced by PreservePinPreviewUntilForced().
PurgeVisualRepresentation()
void SGraphPanel::PurgeVisualRepresentation ()
Purges the existing visual representation (typically followed by an Update call in the next tick)
References PurgeVisualRepresentation().
Referenced by PurgeVisualRepresentation().
RefreshNode()
void SGraphPanel::RefreshNode (UEdGraphNode & Node)
Refresh the visual state of a single node.
References RefreshNode().
Referenced by RefreshNode().
RemoveAllNodes()
virtual void SGraphPanel::RemoveAllNodes () override virtual
Remove all nodes from the panel.
Reimplemented from SNodePanel.
References RemoveAllNodes().
Referenced by RemoveAllNodes().
RemoveAllNodesWithInvalidPointers()
void SGraphPanel::RemoveAllNodesWithInvalidPointers () protected
Helper method to remove all nodes from the panel holding garbage / invalid pointers.
RemoveNode()
void SGraphPanel::RemoveNode (const UEdGraphNode * Node) protected
Helper method to remove a node from the panel.
RemovePinFromHoverSet()
void SGraphPanel::RemovePinFromHoverSet (UEdGraphPin * UnhoveredPin)
References RemovePinFromHoverSet().
Referenced by RemovePinFromHoverSet().
SetNodeFactory()
void SGraphPanel::SetNodeFactory (const TSharedRef< class FGraphNodeFactory > & NewNodeFactory)
Sets the current widget factory.
References SNodePanel::const, and SetNodeFactory().
Referenced by SetNodeFactory().
SetPinVisibility()
void SGraphPanel::SetPinVisibility (SGraphEditor::EPinVisibility InVisibility) inline
Definition at line 252 of file SGraphPanel.h.
References PinVisibility.
SLATE_EVENT()
SGraphPanel::SLATE_EVENT (FOnGetContextMenuFor , OnGetContextMenuFor) inline
Definition at line 94 of file SGraphPanel.h.
References Actors, OnDropActors, OnGetContextMenuFor, OnNodeDoubleClicked, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
SLATE_EVENT_DEPRECATED() [1/2]
SGraphPanel::SLATE_EVENT_DEPRECATED (5. 6, "Use SGraphEditor::FOnDropActors." , SGraphEditor::FOnDropActor , OnDropActor , OnDropActors , ConvertOnDropActorDelegate) inline
Definition at line 112 of file SGraphPanel.h.
References OnDropActors.
SLATE_EVENT_DEPRECATED() [2/2]
SGraphPanel::SLATE_EVENT_DEPRECATED (5. 6, "Use SGraphEditor::FOnDropStreamingLevels." , SGraphEditor::FOnDropStreamingLevel , OnDropStreamingLevel , OnDropStreamingLevels , ConvertOnDropStreamingLevelDelegate) inline
Show overlay elements for the graph state such as the PIE and read-only borders and text.
Definition at line 127 of file SGraphPanel.h.
References DiffResults, DisplayAsReadOnly, FocusedDiffResult, SGraphEditor::FOnSpawnNodeByShortcut, GraphObj, SNodePanel::IsEditable, OnDropStreamingLevels, OnTextCommitted, OnVerifyTextCommit, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and ShowGraphStateOverlay.
StraightenConnections() [1/2]
void SGraphPanel::StraightenConnections ()
Straighten all connections between the selected nodes.
References StraightenConnections().
Referenced by StraightenConnections(), and StraightenConnections().
StraightenConnections() [2/2]
void SGraphPanel::StraightenConnections (UEdGraphPin * SourcePin, UEdGraphPin * PinToAlign = nullptr)
Straighten any connections attached to the specified pin, optionally limiting to the specified pin to align.
References StraightenConnections().
SummonContextMenu()
TSharedPtr< SWidget > SGraphPanel::SummonContextMenu (const UE::Slate::FDeprecateVector2DParameter & WhereToSummon, const UE::Slate::FDeprecateVector2DParameter & WhereToAddNode, UEdGraphNode * ForNode, UEdGraphPin * ForPin, const TArray< UEdGraphPin * > & DragFromPins)
References SWidget::SWidget(), SNodePanel::const, and SummonContextMenu().
Referenced by SummonContextMenu().
SummonCreateNodeMenuFromUICommand()
void SGraphPanel::SummonCreateNodeMenuFromUICommand (uint32 NumNodesAdded)
References SummonCreateNodeMenuFromUICommand().
Referenced by SummonCreateNodeMenuFromUICommand().
SupportsKeyboardFocus()
virtual bool SGraphPanel::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
References SNodePanel::const, and SupportsKeyboardFocus().
Referenced by SupportsKeyboardFocus().
UE_DEPRECATED()
SGraphPanel::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const
Attempt to retrieve the bounds for the specified node.
Update()
void SGraphPanel::Update ()
Update this GraphPanel to match the data that it is observing.
Expected to be called during ticking.
References Update().
Referenced by Update().
UpdateSelectedNodesPositions()
void SGraphPanel::UpdateSelectedNodesPositions (const FVector2f & PositionIncrement) private
Update all selected nodes position by provided vector2d.
Field Documentation
ActiveTimerHandleInvalidatePerTick
TWeakPtr<FActiveTimerHandle> SGraphPanel::ActiveTimerHandleInvalidatePerTick private
Handle to timer callback that allows the UI to refresh it's arrangement each tick, allows animations to occur within the UI.
Definition at line 453 of file SGraphPanel.h.
bCheckNodeGraphObjValidity
bool SGraphPanel::bCheckNodeGraphObjValidity private
A flag indicating that we need to check if we have any nodes which use invalid pointers.
Definition at line 465 of file SGraphPanel.h.
bIsDrawStateCached
bool SGraphPanel::bIsDrawStateCached = false mutable protected
Definition at line 348 of file SGraphPanel.h.
BounceCurve
FCurveSequence SGraphPanel::BounceCurve protected
Bouncing curve.
Definition at line 374 of file SGraphPanel.h.
bPreservePinPreviewConnection
bool SGraphPanel::bPreservePinPreviewConnection protected
Definition at line 333 of file SGraphPanel.h.
bShowPIENotification
bool SGraphPanel::bShowPIENotification protected
Whether to draw the overlay indicating we're in PIE.
Definition at line 398 of file SGraphPanel.h.
CachedAllottedGeometryScaledSize
FDeprecateSlateVector2D SGraphPanel::CachedAllottedGeometryScaledSize mutable protected
Geometry cache.
Definition at line 377 of file SGraphPanel.h.
ContextMenu
TWeakPtr<IMenu> SGraphPanel::ContextMenu private
Weak pointer to the last summoned context menu, for dismissing it when requested.
Definition at line 462 of file SGraphPanel.h.
CurrentHoveredPins
TSet< FEdGraphPinReference > SGraphPanel::CurrentHoveredPins protected
List of pins currently being hovered over.
Definition at line 339 of file SGraphPanel.h.
DiffResults
TSharedPtr<TArray<FDiffSingleResult> > SGraphPanel::DiffResults protected
Definition at line 329 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
DisplayAsReadOnly
TAttribute<bool> SGraphPanel::DisplayAsReadOnly private
Should the graph display all nodes in a read-only state (grayed)?
This does not affect functionality of using them (IsEditable)
Definition at line 411 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
FocusedDiffResult
TAttribute<int32> SGraphPanel::FocusedDiffResult protected
Definition at line 330 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
GraphObj
TObjectPtr<UEdGraph> SGraphPanel::GraphObj protected
Definition at line 325 of file SGraphPanel.h.
Referenced by GetGraphObj(), and SLATE_EVENT_DEPRECATED().
LastPointerEvent
FPointerEvent SGraphPanel::LastPointerEvent protected
Definition at line 359 of file SGraphPanel.h.
LastPointerGeometry
FGeometry SGraphPanel::LastPointerGeometry protected
The mouse state from the last mouse move event, used to synthesize pin actions when hovering over a spline on the panel.
Definition at line 358 of file SGraphPanel.h.
MarkedPin
TWeakPtr<SGraphPin> SGraphPanel::MarkedPin
Pin marked via shift-clicking.
Definition at line 306 of file SGraphPanel.h.
MaxCorner
FVector2D FVector2D& SGraphPanel::MaxCorner
Definition at line 264 of file SGraphPanel.h.
Referenced by GetBoundsForNode().
MinCorner
FVector2D& SGraphPanel::MinCorner
Definition at line 264 of file SGraphPanel.h.
Referenced by GetBoundsForNode().
MyRegisteredGraphChangedDelegate
FOnGraphChanged::FDelegate SGraphPanel::MyRegisteredGraphChangedDelegate private
Definition at line 413 of file SGraphPanel.h.
MyRegisteredGraphChangedDelegateHandle
FDelegateHandle SGraphPanel::MyRegisteredGraphChangedDelegateHandle private
Definition at line 414 of file SGraphPanel.h.
NodeFactory
TSharedPtr<class FGraphNodeFactory> SGraphPanel::NodeFactory private
The current node factory to create nodes, pins and connections.
Uses the static FNodeFactory if not set.
Definition at line 459 of file SGraphPanel.h.
NodeGuidMap
TMap<FGuid, TWeakPtr<SGraphNode> > SGraphPanel::NodeGuidMap private
A map of guid -> graph nodes.
Definition at line 319 of file SGraphPanel.h.
OnClicked
SGraphEditor::FOnMouseButtonDown SGraphPanel::OnClicked protected
Called when the graph itself is clicked.
Definition at line 395 of file SGraphPanel.h.
OnDisallowedPinConnection
SGraphEditor::FOnDisallowedPinConnection SGraphPanel::OnDisallowedPinConnection protected
Called when the user generates a warning tooltip because a connection was invalid.
Definition at line 389 of file SGraphPanel.h.
OnDoubleClicked
SGraphEditor::FOnDoubleClicked SGraphPanel::OnDoubleClicked protected
Called when the graph itself is double clicked.
Definition at line 392 of file SGraphPanel.h.
OnDropActors
SGraphEditor::FOnDropActors SGraphPanel::OnDropActors protected
Invoked when an actor is dropped onto the panel.
Definition at line 365 of file SGraphPanel.h.
Referenced by SLATE_EVENT(), and SLATE_EVENT_DEPRECATED().
OnDropStreamingLevels
SGraphEditor::FOnDropStreamingLevels SGraphPanel::OnDropStreamingLevels protected
Invoked when a streaming level is dropped onto the panel.
Definition at line 368 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
OnGetContextMenuFor
FOnGetContextMenuFor SGraphPanel::OnGetContextMenuFor protected
Invoked when we need to summon a context menu.
Definition at line 362 of file SGraphPanel.h.
Referenced by SLATE_EVENT().
OnNodeDoubleClicked
FSingleNodeEvent SGraphPanel::OnNodeDoubleClicked protected
What to do when a node is double-clicked.
Definition at line 371 of file SGraphPanel.h.
Referenced by SLATE_EVENT().
OnTextCommitted
FOnNodeTextCommitted SGraphPanel::OnTextCommitted protected
Invoked when text is committed on panel.
Definition at line 383 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
OnUpdateGraphPanel
FOnUpdateGraphPanel SGraphPanel::OnUpdateGraphPanel protected
Invoked when the panel is updated.
Definition at line 386 of file SGraphPanel.h.
OnVerifyTextCommit
FOnNodeVerifyTextCommit SGraphPanel::OnVerifyTextCommit protected
Invoked when text is being committed on panel to verify it.
Definition at line 380 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
Padding
FVector2D FVector2D float SGraphPanel::Padding = 0.0f) const
Definition at line 264 of file SGraphPanel.h.
Referenced by GetBoundsForNode().
PinVisibility
SGraphEditor::EPinVisibility SGraphPanel::PinVisibility protected
Pin visibility mode.
Definition at line 336 of file SGraphPanel.h.
Referenced by GetPinVisibility(), and SetPinVisibility().
PreviewConnectorEndpoint
FDeprecateSlateVector2D SGraphPanel::PreviewConnectorEndpoint protected
Definition at line 347 of file SGraphPanel.h.
PreviewConnectorFromPins
TArray< FGraphPinHandle > SGraphPanel::PreviewConnectorFromPins protected
Sometimes the panel draws a preview connector; e.g.
when the user is connecting pins
Definition at line 346 of file SGraphPanel.h.
PreviousFrameSavedMousePosForSplineOverlap
FDeprecateSlateVector2D SGraphPanel::PreviousFrameSavedMousePosForSplineOverlap protected
The overlap results from the previous OnPaint call.
Definition at line 354 of file SGraphPanel.h.
PreviousFrameSplineOverlap
FGraphSplineOverlapResult SGraphPanel::PreviousFrameSplineOverlap protected
Definition at line 355 of file SGraphPanel.h.
Referenced by GetPreviousFrameSplineOverlap().
RelinkConnections
TArray<FConnectionDrawingPolicy::FRelinkConnection> SGraphPanel::RelinkConnections private
List of currently relinked connections.
Definition at line 322 of file SGraphPanel.h.
SavedMousePosForOnPaintEventLocalSpace
FDeprecateSlateVector2D SGraphPanel::SavedMousePosForOnPaintEventLocalSpace protected
Last mouse position seen, used for paint-centric highlighting.
Definition at line 351 of file SGraphPanel.h.
ShowGraphStateOverlay
TAttribute<bool> SGraphPanel::ShowGraphStateOverlay protected
Whether to draw decorations for graph state (PIE / ReadOnly etc.)
Definition at line 401 of file SGraphPanel.h.
Referenced by SLATE_EVENT_DEPRECATED().
TimeLeftToInvalidatePerTick
float SGraphPanel::TimeLeftToInvalidatePerTick private
Amount of time left to invalidate the UI per tick.
Definition at line 456 of file SGraphPanel.h.
TimeWhenMouseEnteredPin
double SGraphPanel::TimeWhenMouseEnteredPin protected
Time since the last mouse enter/exit on a pin.
Definition at line 342 of file SGraphPanel.h.
TimeWhenMouseLeftPin
double SGraphPanel::TimeWhenMouseLeftPin protected
Definition at line 343 of file SGraphPanel.h.
UserAddedNodes
TSet<const class UEdGraphNode*> SGraphPanel::UserAddedNodes private
Set of user-added nodes for the panel, tracked while a visual update is pending.
Definition at line 408 of file SGraphPanel.h.
UserSelectedNodes
TSet<TWeakObjectPtr<class UEdGraphNode> > SGraphPanel::UserSelectedNodes private
Set of nodes selected by the user, tracked while a visual update is pending.
Definition at line 405 of file SGraphPanel.h.
The documentation for this class was generated from the following file:
SGraphPanel.h