Unreal Engine 5.6 C++ API: FSimpleLinkNavModifier Struct Reference
FSimpleLinkNavModifier Struct Reference
This modifier allows defining ad-hoc navigation links defining connections in an straightforward way.
#include "NavigationModifier.h"
Public Member Functions
FSimpleLinkNavModifier ()
FSimpleLinkNavModifier (const FNavigationLink &InLink, const FTransform &InLocalToWorld)
FSimpleLinkNavModifier (const FNavigationSegmentLink &InLink, const FTransform &InLocalToWorld)
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSimpleLinkNavModifier (const FSimpleLinkNavModifier &)=default
FSimpleLinkNavModifier (const TArray< FNavigationLink > &InLinks, const FTransform &InLocalToWorld)
FSimpleLinkNavModifier (const TArray< FNavigationSegmentLink > &InSegmentLinks, const FTransform &InLocalToWorld)
FSimpleLinkNavModifier (FSimpleLinkNavModifier &&Other)=default
void AddLink (const FNavigationLink &InLink)
void AddSegmentLink (const FNavigationSegmentLink &InLink)
void AppendLinks (const TArray< FNavigationLink > &InLinks)
void AppendSegmentLinks (const TArray< FNavigationSegmentLink > &InLinks)
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE bool HasFallDownLinks () const
FSimpleLinkNavModifier & operator= (const FSimpleLinkNavModifier &Other)=default
FSimpleLinkNavModifier & operator= (FSimpleLinkNavModifier &&Other)=default
void SetLinks (const TArray< FNavigationLink > &InLinks)
void SetSegmentLinks (const TArray< FNavigationSegmentLink > &InLinks)
UE_DEPRECATED (5.3, "Use NavLinkId instead, this id is no longer used in the engine.") int32 UserId
void UpdateFlags ()
Public Member Functions inherited from FNavigationModifier
FNavigationModifier ()
FORCEINLINE bool HasMetaAreas () const
Data Fields
TArray< FNavigationLink > Links
use Set/Append/Add function to update links, they will take care of meta areas
FTransform LocalToWorld
FNavLinkId NavLinkId
TArray< FNavigationSegmentLink > SegmentLinks
Protected Attributes
int32 bHasFallDownLinks: 1
set to true if any of links stored is a "fall down" link, i.e.
int32 bHasMetaAreasPoint: 1
int32 bHasMetaAreasSegment: 1
Protected Attributes inherited from FNavigationModifier
int32 bHasMetaAreas: 1
set to true if any of areas used by this modifier is a meta nav area (UNavArea::IsMetaArea is true)
Detailed Description
This modifier allows defining ad-hoc navigation links defining connections in an straightforward way.
Definition at line 173 of file NavigationModifier.h.
Constructor & Destructor Documentation
FSimpleLinkNavModifier() [1/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier () inline
Definition at line 185 of file NavigationModifier.h.
References FSimpleLinkNavModifier(), bHasFallDownLinks, bHasMetaAreasPoint, and bHasMetaAreasSegment.
Referenced by FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), operator=(), and operator=().
FSimpleLinkNavModifier() [2/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier (const FNavigationLink & InLink, const FTransform & InLocalToWorld) inline
Definition at line 192 of file NavigationModifier.h.
References AddLink(), bHasFallDownLinks, bHasMetaAreasPoint, bHasMetaAreasSegment, LocalToWorld, and NavLinkId.
FSimpleLinkNavModifier() [3/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier (const TArray< FNavigationLink > & InLinks, const FTransform & InLocalToWorld) inline
Definition at line 202 of file NavigationModifier.h.
References bHasFallDownLinks, bHasMetaAreasPoint, bHasMetaAreasSegment, LocalToWorld, and TArray< InElementType, InAllocatorType >::Num().
FSimpleLinkNavModifier() [4/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier (const FNavigationSegmentLink & InLink, const FTransform & InLocalToWorld) inline
Definition at line 215 of file NavigationModifier.h.
References AddSegmentLink(), bHasFallDownLinks, bHasMetaAreasPoint, bHasMetaAreasSegment, LocalToWorld, and NavLinkId.
FSimpleLinkNavModifier() [5/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier (const TArray< FNavigationSegmentLink > & InSegmentLinks, const FTransform & InLocalToWorld) inline
Definition at line 225 of file NavigationModifier.h.
References bHasFallDownLinks, bHasMetaAreasPoint, bHasMetaAreasSegment, LocalToWorld, and TArray< InElementType, InAllocatorType >::Num().
FSimpleLinkNavModifier() [6/7]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSimpleLinkNavModifier::FSimpleLinkNavModifier (const FSimpleLinkNavModifier &) default
References FSimpleLinkNavModifier().
FSimpleLinkNavModifier() [7/7]
FSimpleLinkNavModifier::FSimpleLinkNavModifier (FSimpleLinkNavModifier && Other) default
References FSimpleLinkNavModifier(), and Other.
Member Function Documentation
AddLink()
void FSimpleLinkNavModifier::AddLink (const FNavigationLink & InLink)
Referenced by FSimpleLinkNavModifier().
AddSegmentLink()
void FSimpleLinkNavModifier::AddSegmentLink (const FNavigationSegmentLink & InLink)
Referenced by FSimpleLinkNavModifier().
AppendLinks()
void FSimpleLinkNavModifier::AppendLinks (const TArray< FNavigationLink > & InLinks)
AppendSegmentLinks()
void FSimpleLinkNavModifier::AppendSegmentLinks (const TArray< FNavigationSegmentLink > & InLinks)
HasFallDownLinks()
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE bool FSimpleLinkNavModifier::HasFallDownLinks () const inline
Definition at line 245 of file NavigationModifier.h.
References bHasFallDownLinks, and FORCEINLINE.
operator=() [1/2]
FSimpleLinkNavModifier & FSimpleLinkNavModifier::operator= (const FSimpleLinkNavModifier & Other) default
References FSimpleLinkNavModifier(), and Other.
operator=() [2/2]
FSimpleLinkNavModifier & FSimpleLinkNavModifier::operator= (FSimpleLinkNavModifier && Other) default
References FSimpleLinkNavModifier(), Other, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
SetLinks()
void FSimpleLinkNavModifier::SetLinks (const TArray< FNavigationLink > & InLinks)
SetSegmentLinks()
void FSimpleLinkNavModifier::SetSegmentLinks (const TArray< FNavigationSegmentLink > & InLinks)
UE_DEPRECATED()
FSimpleLinkNavModifier::UE_DEPRECATED (5. 3, "Use NavLinkId instead, this id is no longer used in the engine.")
UpdateFlags()
void FSimpleLinkNavModifier::UpdateFlags ()
Field Documentation
bHasFallDownLinks
int32 FSimpleLinkNavModifier::bHasFallDownLinks protected
set to true if any of links stored is a "fall down" link, i.e.
requires vertical snapping to geometry
Definition at line 256 of file NavigationModifier.h.
Referenced by FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), and HasFallDownLinks().
bHasMetaAreasPoint
int32 FSimpleLinkNavModifier::bHasMetaAreasPoint protected
Definition at line 257 of file NavigationModifier.h.
Referenced by FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), and FSimpleLinkNavModifier().
bHasMetaAreasSegment
int32 FSimpleLinkNavModifier::bHasMetaAreasSegment protected
Definition at line 258 of file NavigationModifier.h.
Referenced by FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), and FSimpleLinkNavModifier().
Links
TArray<FNavigationLink> FSimpleLinkNavModifier::Links
use Set/Append/Add function to update links, they will take care of meta areas
Definition at line 176 of file NavigationModifier.h.
LocalToWorld
FTransform FSimpleLinkNavModifier::LocalToWorld
Definition at line 178 of file NavigationModifier.h.
Referenced by FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), FSimpleLinkNavModifier(), and FSimpleLinkNavModifier().
NavLinkId
FNavLinkId FSimpleLinkNavModifier::NavLinkId
Definition at line 183 of file NavigationModifier.h.
Referenced by FSimpleLinkNavModifier(), and FSimpleLinkNavModifier().
SegmentLinks
TArray<FNavigationSegmentLink> FSimpleLinkNavModifier::SegmentLinks
Definition at line 177 of file NavigationModifier.h.
The documentation for this struct was generated from the following file:
NavigationModifier.h