Unreal Engine 5.6 C++ API: FRDGTextureAccess Class Reference
FRDGTextureAccess Class Reference
#include "ShaderParameterMacros.h"
Public Member Functions
FRDGTextureAccess ()=default
RENDERCORE_API FRDGTextureAccess (FRDGTexture *InTexture, ERHIAccess InAccess)
FRDGTextureAccess (FRDGTexture *InTexture, FRDGTextureSubresourceRange InSubresourceRange, ERHIAccess InAccess)
RENDERCORE_API FRDGTextureAccess (FRDGTextureSRV *InTextureSRV, ERHIAccess InAccess)
RENDERCORE_API FRDGTextureAccess (FRDGTextureUAV *InTextureUAV, ERHIAccess InAccess)
FORCEINLINE ERHIAccess GetAccess () const
FORCEINLINE FRDGTextureSubresourceRange GetSubresourceRange () const
FORCEINLINE FRDGTexture * GetTexture () const
FORCEINLINE operator bool () const
FORCEINLINE operator FRDGTexture * () const
FORCEINLINE bool operator!= (const FRDGTextureAccess &RHS) const
FORCEINLINE FRDGTexture * operator-> () const
FORCEINLINE bool operator== (const FRDGTextureAccess &RHS) const
Private Attributes
ERHIAccess Access = ERHIAccess::Unknown
FRDGTextureSubresourceRange SubresourceRange
TAlignedShaderParameterPtr< FRDGTexture * > Texture = nullptr
Detailed Description
Definition at line 428 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FRDGTextureAccess() [1/5]
FRDGTextureAccess::FRDGTextureAccess () default
Referenced by TRDGTextureAccess< InAccess >::TRDGTextureAccess(), TRDGTextureAccess< InAccess >::TRDGTextureAccess(), TRDGTextureAccess< InAccess >::TRDGTextureAccess(), TRDGTextureAccess< InAccess >::TRDGTextureAccess(), operator!=(), and operator==().
FRDGTextureAccess() [2/5]
FRDGTextureAccess::FRDGTextureAccess (FRDGTexture * InTexture, FRDGTextureSubresourceRange InSubresourceRange, ERHIAccess InAccess) inline
Definition at line 433 of file ShaderParameterMacros.h.
References Access, SubresourceRange, and Texture.
FRDGTextureAccess() [3/5]
RENDERCORE_API FRDGTextureAccess::FRDGTextureAccess (FRDGTexture * InTexture, ERHIAccess InAccess)
FRDGTextureAccess() [4/5]
RENDERCORE_API FRDGTextureAccess::FRDGTextureAccess (FRDGTextureSRV * InTextureSRV, ERHIAccess InAccess)
FRDGTextureAccess() [5/5]
RENDERCORE_API FRDGTextureAccess::FRDGTextureAccess (FRDGTextureUAV * InTextureUAV, ERHIAccess InAccess)
Member Function Documentation
GetAccess()
FORCEINLINE ERHIAccess FRDGTextureAccess::GetAccess () const inline
Definition at line 445 of file ShaderParameterMacros.h.
References Access, and FORCEINLINE.
GetSubresourceRange()
FORCEINLINE FRDGTextureSubresourceRange FRDGTextureAccess::GetSubresourceRange () const inline
Definition at line 444 of file ShaderParameterMacros.h.
References FORCEINLINE, and SubresourceRange.
GetTexture()
FORCEINLINE FRDGTexture * FRDGTextureAccess::GetTexture () const inline
Definition at line 443 of file ShaderParameterMacros.h.
References FORCEINLINE, and Texture.
operator bool()
FORCEINLINE FRDGTextureAccess::operator bool () const inline
Definition at line 447 of file ShaderParameterMacros.h.
References FORCEINLINE, and Texture.
operator FRDGTexture *()
FORCEINLINE FRDGTextureAccess::operator FRDGTexture * () const inline
Definition at line 458 of file ShaderParameterMacros.h.
References FORCEINLINE, and Texture.
operator!=()
FORCEINLINE bool FRDGTextureAccess::operator!= (const FRDGTextureAccess & RHS) const inline
Definition at line 468 of file ShaderParameterMacros.h.
References FRDGTextureAccess(), Access, FORCEINLINE, and Texture.
operator->()
FORCEINLINE FRDGTexture * FRDGTextureAccess::operator-> () const inline
Definition at line 452 of file ShaderParameterMacros.h.
References check, FORCEINLINE, and Texture.
operator==()
FORCEINLINE bool FRDGTextureAccess::operator== (const FRDGTextureAccess & RHS) const inline
Definition at line 463 of file ShaderParameterMacros.h.
References FRDGTextureAccess(), Access, FORCEINLINE, and Texture.
Field Documentation
Access
ERHIAccess FRDGTextureAccess::Access = ERHIAccess::Unknown private
Definition at line 476 of file ShaderParameterMacros.h.
Referenced by FRDGTextureAccess(), GetAccess(), operator!=(), and operator==().
SubresourceRange
FRDGTextureSubresourceRange FRDGTextureAccess::SubresourceRange private
Definition at line 475 of file ShaderParameterMacros.h.
Referenced by FRDGTextureAccess(), and GetSubresourceRange().
Texture
TAlignedShaderParameterPtr<FRDGTexture*> FRDGTextureAccess::Texture = nullptr private
Definition at line 474 of file ShaderParameterMacros.h.
Referenced by FRDGTextureAccess(), GetTexture(), operator bool(), operator FRDGTexture *(), operator!=(), operator->(), and operator==().
The documentation for this class was generated from the following file:
ShaderParameterMacros.h