Unreal Engine 5.6 C++ API: FConfigBranch Class Reference
FConfigBranch Class Reference
#include "ConfigCacheIni.h"
Public Types
using DynamicLayerList = TDoubleLinkedList<FConfigCommandStream*>
Public Member Functions
FConfigBranch ()
FConfigBranch (const FConfigFile &ExistingFile)
bool AddDynamicLayersToHierarchy (const TArray< FDynamicLayerInfo > &Layers, FConfigModificationTracker *ModificationTracker=nullptr, TSet< FString > *GlobalConfigFileCache=nullptr, TSet< FString > *PluginConfigFileCache=nullptr, bool bForceFullDynamicLayerUpdate=false)
bool AddDynamicLayerStringToHierarchy (const FString &Filename, const FString &Contents, FName Tag=NAME_None, DynamicLayerPriority Priority=DynamicLayerPriority::Unknown, FConfigModificationTracker *ModificationTracker=nullptr)
bool AddDynamicLayerToHierarchy (const FString &Filename, FConfigModificationTracker *ModificationTracker=nullptr, TSet< FString > *GlobalConfigFileCache=nullptr, TSet< FString > *PluginConfigFileCache=nullptr)
Appends a new INI file to the SourceIniHierarchy and combines it with the current contents Additonally, returns the FConfigFIle object that contains just the loaded sections Can return the modified sections if the callers wants to reloadconfig on classes.
bool Delete ()
Deletes the final saved branch file, such as "Saved/Config/Windows/Engine.ini".
void Dump (FOutputDevice &Ar)
void Flush ()
bool RemoveDynamicLayerFromHierarchy (const FString &Filename, FConfigModificationTracker *ModificationTracker=nullptr)
Removes a dyanmic file from the hierarchy and recalculates the branch's IniMemoryFile Can return the modified sections if the callers wants to reloadconfig on classes.
bool RemoveDynamicLayersFromHierarchy (const TArray< FString > &Filenames, FConfigModificationTracker *ModificationTracker=nullptr)
bool RemoveSection (const TCHAR *Section)
Removes the section completely from all layers of this branch This is destructive!
void RunOnEachCommandStream (TFunction< void(FConfigCommandStream &File, const FString &Name)> Func)
void RunOnEachFile (TFunction< void(FConfigFile &File, const FString &Name)> Func)
Run a function on every file in the branch.
void SafeReload ()
void SafeUnload ()
Frees up the static layer memory, which can be useful if a branch is loaded from, cached, and never used again.
void Shrink ()
UE_DEPRECATED (5.6, "Use AddDynamicLayersToHierarchy that takes a FDynamicLayerInfo list") 1 bool AddDynamicLayersToHierarchy(const TArray< FString > &Filenames
Data Fields
bool bAllowedToRemove = true
bool bIsHierarchical
bool bIsSafeUnloaded
FConfigFile CombinedStaticLayers
FConfigCommandStream CommandLineOverrides
DynamicLayerList DynamicLayers
FConfigFile FinalCombinedLayers
FConfigFileHierarchy Hierarchy
FName IniName
FString IniPath
FConfigFile InMemoryFile
FName DynamicLayerPriority FConfigModificationTracker * ModificationTracker =nullptr)
FName Platform
FName DynamicLayerPriority Priority =DynamicLayerPriority::Unknown
EBranchReplayMethod ReplayMethod = EBranchReplayMethod::NoReplay
FConfigCommandStream RuntimeChanges
FConfigCommandStream SavedLayer
FString SourceEngineConfigDir
FString SourceProjectConfigDir
TMap< FString, FConfigCommandStream > StaticLayers
FName Tag =NAME_None
Private Member Functions
void InitFiles ()
void RemoveTagsFromHierarchy (const TArray< FName > &Tags, FConfigModificationTracker *ModificationTracker)
Private Attributes
double InactiveTimer
Friends
class FConfigCacheIni
FArchive & operator<< (FArchive &Ar, FConfigBranch &ConfigBranch)
Detailed Description
Definition at line 1068 of file ConfigCacheIni.h.
Member Typedef Documentation
DynamicLayerList
using FConfigBranch::DynamicLayerList = TDoubleLinkedList<FConfigCommandStream*>
Definition at line 1100 of file ConfigCacheIni.h.
Constructor & Destructor Documentation
FConfigBranch() [1/2]
FConfigBranch::FConfigBranch ()
Referenced by operator<<.
FConfigBranch() [2/2]
FConfigBranch::FConfigBranch (const FConfigFile & ExistingFile)
Member Function Documentation
AddDynamicLayersToHierarchy()
bool FConfigBranch::AddDynamicLayersToHierarchy (const TArray< FDynamicLayerInfo > & Layers, FConfigModificationTracker * ModificationTracker = nullptr, TSet< FString > * GlobalConfigFileCache = nullptr, TSet< FString > * PluginConfigFileCache = nullptr, bool bForceFullDynamicLayerUpdate = false)
References ModificationTracker.
AddDynamicLayerStringToHierarchy()
bool FConfigBranch::AddDynamicLayerStringToHierarchy (const FString & Filename, const FString & Contents, FName Tag = NAME_None, DynamicLayerPriority Priority = DynamicLayerPriority::Unknown, FConfigModificationTracker * ModificationTracker = nullptr)
References AddDynamicLayerStringToHierarchy(), Filename, ModificationTracker, Priority, Tag, and Unknown.
Referenced by AddDynamicLayerStringToHierarchy().
AddDynamicLayerToHierarchy()
bool FConfigBranch::AddDynamicLayerToHierarchy (const FString & Filename, FConfigModificationTracker * ModificationTracker = nullptr, TSet< FString > * GlobalConfigFileCache = nullptr, TSet< FString > * PluginConfigFileCache = nullptr)
Appends a new INI file to the SourceIniHierarchy and combines it with the current contents Additonally, returns the FConfigFIle object that contains just the loaded sections Can return the modified sections if the callers wants to reloadconfig on classes.
References Filename, and ModificationTracker.
Delete()
bool FConfigBranch::Delete ()
Deletes the final saved branch file, such as "Saved/Config/Windows/Engine.ini".
Returns
Whether the file was successfully deleted.
References Delete().
Referenced by Delete().
Dump()
void FConfigBranch::Dump (FOutputDevice & Ar)
References Ar, and Dump().
Referenced by Dump().
Flush()
void FConfigBranch::Flush ()
References Flush().
Referenced by Flush().
InitFiles()
void FConfigBranch::InitFiles () private
References InitFiles().
Referenced by InitFiles().
RemoveDynamicLayerFromHierarchy()
bool FConfigBranch::RemoveDynamicLayerFromHierarchy (const FString & Filename, FConfigModificationTracker * ModificationTracker = nullptr)
Removes a dyanmic file from the hierarchy and recalculates the branch's IniMemoryFile Can return the modified sections if the callers wants to reloadconfig on classes.
References Filename, ModificationTracker, and RemoveDynamicLayerFromHierarchy().
Referenced by RemoveDynamicLayerFromHierarchy().
RemoveDynamicLayersFromHierarchy()
bool FConfigBranch::RemoveDynamicLayersFromHierarchy (const TArray< FString > & Filenames, FConfigModificationTracker * ModificationTracker = nullptr)
References ModificationTracker, and RemoveDynamicLayersFromHierarchy().
Referenced by RemoveDynamicLayersFromHierarchy().
RemoveSection()
bool FConfigBranch::RemoveSection (const TCHAR * Section)
Removes the section completely from all layers of this branch This is destructive!
It will not reload on demand (like SafeUnload does). Use this only when you know you will never need the values in the section again!
Returns
true if anything was removed
References RemoveSection().
Referenced by RemoveSection().
RemoveTagsFromHierarchy()
void FConfigBranch::RemoveTagsFromHierarchy (const TArray< FName > & Tags, FConfigModificationTracker * ModificationTracker) private
References ModificationTracker, RemoveTagsFromHierarchy(), and Tags.
Referenced by RemoveTagsFromHierarchy().
RunOnEachCommandStream()
void FConfigBranch::RunOnEachCommandStream (TFunction< void(FConfigCommandStream &File, const FString &Name)> Func)
References Name, and RunOnEachCommandStream().
Referenced by RunOnEachCommandStream().
RunOnEachFile()
void FConfigBranch::RunOnEachFile (TFunction< void(FConfigFile &File, const FString &Name)> Func)
Run a function on every file in the branch.
References Name, and RunOnEachFile().
Referenced by RunOnEachFile().
SafeReload()
void FConfigBranch::SafeReload ()
References SafeReload().
Referenced by SafeReload().
SafeUnload()
void FConfigBranch::SafeUnload ()
Frees up the static layer memory, which can be useful if a branch is loaded from, cached, and never used again.
However, if something does try to access it, it will reload in-place (can hitch your game, so be aware)
References SafeUnload().
Referenced by SafeUnload().
Shrink()
void FConfigBranch::Shrink ()
References Shrink().
Referenced by Shrink().
UE_DEPRECATED()
FConfigBranch::UE_DEPRECATED (5. 6, "Use AddDynamicLayersToHierarchy that takes a FDynamicLayerInfo list") const &
Friends And Related Symbol Documentation
FConfigCacheIni
friend class FConfigCacheIni friend
Definition at line 1178 of file ConfigCacheIni.h.
References FConfigCacheIni.
Referenced by FConfigCacheIni.
operator<<
FArchive & operator<< (FArchive & Ar, FConfigBranch & ConfigBranch) friend
References FConfigBranch(), and Ar.
Field Documentation
bAllowedToRemove
bool FConfigBranch::bAllowedToRemove = true
Definition at line 1093 of file ConfigCacheIni.h.
bIsHierarchical
bool FConfigBranch::bIsHierarchical
Definition at line 1091 of file ConfigCacheIni.h.
bIsSafeUnloaded
bool FConfigBranch::bIsSafeUnloaded
Definition at line 1090 of file ConfigCacheIni.h.
CombinedStaticLayers
FConfigFile FConfigBranch::CombinedStaticLayers
Definition at line 1105 of file ConfigCacheIni.h.
CommandLineOverrides
FConfigCommandStream FConfigBranch::CommandLineOverrides
Definition at line 1110 of file ConfigCacheIni.h.
DynamicLayers
DynamicLayerList FConfigBranch::DynamicLayers
Definition at line 1101 of file ConfigCacheIni.h.
FinalCombinedLayers
FConfigFile FConfigBranch::FinalCombinedLayers
Definition at line 1108 of file ConfigCacheIni.h.
Hierarchy
FConfigFileHierarchy FConfigBranch::Hierarchy
Definition at line 1097 of file ConfigCacheIni.h.
InactiveTimer
double FConfigBranch::InactiveTimer private
Definition at line 1181 of file ConfigCacheIni.h.
IniName
FName FConfigBranch::IniName
Definition at line 1079 of file ConfigCacheIni.h.
IniPath
FString FConfigBranch::IniPath
Definition at line 1082 of file ConfigCacheIni.h.
InMemoryFile
FConfigFile FConfigBranch::InMemoryFile
Definition at line 1113 of file ConfigCacheIni.h.
ModificationTracker
FName DynamicLayerPriority FConfigModificationTracker* FConfigBranch::ModificationTracker =nullptr)
Definition at line 1128 of file ConfigCacheIni.h.
Referenced by AddDynamicLayersToHierarchy(), AddDynamicLayerStringToHierarchy(), AddDynamicLayerToHierarchy(), RemoveDynamicLayerFromHierarchy(), RemoveDynamicLayersFromHierarchy(), and RemoveTagsFromHierarchy().
Platform
FName FConfigBranch::Platform
Definition at line 1084 of file ConfigCacheIni.h.
Priority
FName DynamicLayerPriority FConfigBranch::Priority =DynamicLayerPriority::Unknown
Definition at line 1128 of file ConfigCacheIni.h.
Referenced by AddDynamicLayerStringToHierarchy().
ReplayMethod
EBranchReplayMethod FConfigBranch::ReplayMethod = EBranchReplayMethod::NoReplay
Definition at line 1095 of file ConfigCacheIni.h.
RuntimeChanges
FConfigCommandStream FConfigBranch::RuntimeChanges
Definition at line 1116 of file ConfigCacheIni.h.
SavedLayer
FConfigCommandStream FConfigBranch::SavedLayer
Definition at line 1102 of file ConfigCacheIni.h.
SourceEngineConfigDir
FString FConfigBranch::SourceEngineConfigDir
Definition at line 1087 of file ConfigCacheIni.h.
SourceProjectConfigDir
FString FConfigBranch::SourceProjectConfigDir
Definition at line 1088 of file ConfigCacheIni.h.
StaticLayers
TMap<FString, FConfigCommandStream> FConfigBranch::StaticLayers
Definition at line 1099 of file ConfigCacheIni.h.
Tag
FName FConfigBranch::Tag =NAME_None
Definition at line 1128 of file ConfigCacheIni.h.
Referenced by AddDynamicLayerStringToHierarchy().
The documentation for this class was generated from the following file:
ConfigCacheIni.h