Unreal Engine 5.6 C++ API: TBlendableToken< DataType > Struct Template Reference
TBlendableToken< DataType > Struct Template Reference
Templated structure that encapsulates any blendable data type, and the information required to blend it.
#include "BlendableToken.h"
Data Structures
struct IData
Base class for all value types.
struct TData
Templated value data for any other type.
Public Types
typedef TBlendableTokenTraits< DataType >::WorkingDataType WorkingDataType
Public Member Functions
TBlendableToken ()=default
Default construction.
TBlendableToken (const TBlendableToken &)=delete
Copying is disabled.
template<typename T>
TBlendableToken (T &&InValue, const FMovieSceneEvaluationScope &InCurrentScope, const FMovieSceneContext &InContext, EMovieSceneBlendType InBlendType, float InWeight=1.f, int32 InBlendingOrder=INDEX_NONE)
Construction from a value, scope, context, blend method, and a weight.
template<typename T>
TBlendableToken (T &&InValue, EMovieSceneBlendType InBlendType, float InWeight=1.f, int32 InBlendingOrder=INDEX_NONE)
Construction from a value, blend method, and a weight.
TBlendableToken (TBlendableToken &&)=default
Move construction/assignment.
void AddTo (WorkingDataType &CumulativeBlend, TMovieSceneInitialValueStore< DataType > &InitialValueStore) const
Add this value into the specified cumulative blend.
bool operator< (const TBlendableToken &RHS) const
TBlendableToken & operator= (const TBlendableToken &)=delete
TBlendableToken & operator= (TBlendableToken &&)=default
Data Fields
FMovieSceneEvaluationScope AnimatingScope
The scope from which this token was generated.
int32 BlendingOrder = INDEX_NONE
Opitonal Blending Order, if present will be used to sort additives and override blend types.
EMovieSceneBlendType BlendType
Enumeration specifying how this token should be blended.
int32 HierarchicalBias
The hierarchical bias for this template instance.
float Weight
Weight to apply to the value.
Private Attributes
TInlineValue< IData, sizeof(DataType)> Value
The actual user provided value data, stored as inline bytes (unless it's > sizeof(DataType))
Detailed Description
template<typename DataType>
struct TBlendableToken< DataType >
Templated structure that encapsulates any blendable data type, and the information required to blend it.
Definition at line 99 of file BlendableToken.h.
Member Typedef Documentation
WorkingDataType
template<typename DataType> typedef TBlendableTokenTraits<DataType>::WorkingDataType TBlendableToken< DataType >::WorkingDataType
Definition at line 101 of file BlendableToken.h.
Constructor & Destructor Documentation
TBlendableToken() [1/5]
template<typename DataType> TBlendableToken< DataType >::TBlendableToken () default
Default construction.
Referenced by TBlendableToken(), TBlendableToken(), operator<(), operator=(), and operator=().
TBlendableToken() [2/5]
template<typename DataType> template<typename T> TBlendableToken< DataType >::TBlendableToken (T && InValue, EMovieSceneBlendType InBlendType, float InWeight = 1.f, int32 InBlendingOrder = INDEX_NONE) inline
Construction from a value, blend method, and a weight.
Scope and bias to be populated later
Definition at line 108 of file BlendableToken.h.
References BlendingOrder, BlendType, Forward(), HierarchicalBias, INDEX_NONE, Value, and Weight.
TBlendableToken() [3/5]
template<typename DataType> template<typename T> TBlendableToken< DataType >::TBlendableToken (T && InValue, const FMovieSceneEvaluationScope & InCurrentScope, const FMovieSceneContext & InContext, EMovieSceneBlendType InBlendType, float InWeight = 1.f, int32 InBlendingOrder = INDEX_NONE) inline
Construction from a value, scope, context, blend method, and a weight.
Definition at line 118 of file BlendableToken.h.
References AnimatingScope, BlendingOrder, BlendType, Forward(), HierarchicalBias, INDEX_NONE, Value, and Weight.
TBlendableToken() [4/5]
template<typename DataType> TBlendableToken< DataType >::TBlendableToken (const TBlendableToken< DataType > &) delete
Copying is disabled.
References TBlendableToken().
TBlendableToken() [5/5]
template<typename DataType> TBlendableToken< DataType >::TBlendableToken (TBlendableToken< DataType > &&) default
Move construction/assignment.
References TBlendableToken().
Member Function Documentation
AddTo()
template<typename DataType> void TBlendableToken< DataType >::AddTo (WorkingDataType & CumulativeBlend, TMovieSceneInitialValueStore< DataType > & InitialValueStore) const inline
Add this value into the specified cumulative blend.
Parameters
CumulativeBlend The working structure to add our value onto
Definition at line 142 of file BlendableToken.h.
References BlendingOrder, BlendType, check, Value, and Weight.
operator<()
template<typename DataType> bool TBlendableToken< DataType >::operator< (const TBlendableToken< DataType > & RHS) const inline
Definition at line 148 of file BlendableToken.h.
References TBlendableToken(), and BlendingOrder.
operator=() [1/2]
template<typename DataType> TBlendableToken & TBlendableToken< DataType >::operator= (const TBlendableToken< DataType > &) delete
References TBlendableToken().
operator=() [2/2]
template<typename DataType> TBlendableToken & TBlendableToken< DataType >::operator= (TBlendableToken< DataType > &&) default
References TBlendableToken().
Field Documentation
AnimatingScope
template<typename DataType> FMovieSceneEvaluationScope TBlendableToken< DataType >::AnimatingScope
The scope from which this token was generated.
Used for restoring pre-animated state where necessary.
Definition at line 191 of file BlendableToken.h.
Referenced by TBlendableToken().
BlendingOrder
template<typename DataType> int32 TBlendableToken< DataType >::BlendingOrder = INDEX_NONE
Opitonal Blending Order, if present will be used to sort additives and override blend types.
Definition at line 203 of file BlendableToken.h.
Referenced by TBlendableToken(), TBlendableToken(), AddTo(), TBlendableToken< DataType >::IData::AddTo(), and operator<().
BlendType
template<typename DataType> EMovieSceneBlendType TBlendableToken< DataType >::BlendType
Enumeration specifying how this token should be blended.
Definition at line 200 of file BlendableToken.h.
Referenced by TBlendableToken(), TBlendableToken(), AddTo(), and TBlendableToken< DataType >::IData::AddTo().
HierarchicalBias
template<typename DataType> int32 TBlendableToken< DataType >::HierarchicalBias
The hierarchical bias for this template instance.
Definition at line 194 of file BlendableToken.h.
Referenced by TBlendableToken(), TBlendableToken(), and TBlendableTokenStack< DataType >::AddToken().
Value
template<typename DataType> TInlineValue<IData, sizeof(DataType)> TBlendableToken< DataType >::Value private
The actual user provided value data, stored as inline bytes (unless it's > sizeof(DataType))
Definition at line 186 of file BlendableToken.h.
Referenced by TBlendableToken(), TBlendableToken(), and AddTo().
Weight
template<typename DataType> float TBlendableToken< DataType >::Weight
Weight to apply to the value.
Definition at line 197 of file BlendableToken.h.
Referenced by TBlendableToken(), TBlendableToken(), AddTo(), and TBlendableToken< DataType >::IData::AddTo().
The documentation for this struct was generated from the following file:
BlendableToken.h