Unreal Engine 5.6 C++ API: UE::Editor Namespace Reference
UE::Editor Namespace Reference
Namespaces
namespace Toolbars
Functions
template<typename ThumbnailClass>
ThumbnailClass * FindOrCreateThumbnailInfo (UObject *AssetObject)
UNREALED_API UThumbnailInfo * FindOrCreateThumbnailInfo (UObject *AssetObject, TSubclassOf< UThumbnailInfo > ThumbnailClass)
This function will find or set a new thumbnail info on the object if it either does not exist or the types don't match.
UNREALED_API bool TrySetExistingThumbnailInfo (UObject *InAssetObject, UThumbnailInfo *InThumbnailInfo)
Function Documentation
FindOrCreateThumbnailInfo() [1/2]
template<typename ThumbnailClass> ThumbnailClass * UE::Editor::FindOrCreateThumbnailInfo (UObject * AssetObject)
Definition at line 42 of file AssetDefinitionDefault.h.
References Cast(), and FindOrCreateThumbnailInfo().
FindOrCreateThumbnailInfo() [2/2]
UNREALED_API UThumbnailInfo * UE::Editor::FindOrCreateThumbnailInfo (UObject * AssetObject, TSubclassOf< UThumbnailInfo > ThumbnailClass)
This function will find or set a new thumbnail info on the object if it either does not exist or the types don't match.
This function has some requirements, such as the property MUST minimally exist as such,
UPROPERTY(Instanced) TObjectPtr<class UThumbnailInfo> ThumbnailInfo;
If your class needs the thumbnail to be set using a Setter/Getter, that's ok, you can have Getter=GetThumbnailInfo, Setter=SetThumbnailInfo, in the UProperty declaration to take advantage of native setters and getters.
References FindOrCreateThumbnailInfo().
Referenced by FindOrCreateThumbnailInfo(), and FindOrCreateThumbnailInfo().
TrySetExistingThumbnailInfo()
UNREALED_API bool UE::Editor::TrySetExistingThumbnailInfo (UObject * InAssetObject, UThumbnailInfo * InThumbnailInfo)
References TrySetExistingThumbnailInfo().
Referenced by TrySetExistingThumbnailInfo().