Unreal Engine 5.6 C++ API: GenericPlatformDriver.h File Reference
GenericPlatformDriver.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Containers/Array.h"
#include "Math/UnrealMathUtility.h"
#include "Containers/UnrealString.h"
#include "Misc/DateTime.h"
#include "Misc/Optional.h"
#include "Misc/Parse.h"
#include "Misc/ConfigCacheIni.h"
#include "Internationalization/Regex.h"
Data Structures
struct FDriverConfigEntryConstraints
struct FDriverDenyListEntry
struct FDriverDenyListEntry::FDriverDateDenyListEntry
struct FDriverDenyListEntry::FDriverVersionDenyListEntry
class FDriverVersion
class FGPUDriverHelper
struct FGPUDriverInfo
struct FSuggestedDriverEntry
Enumerations
enum EComparisonOp {
ECO_Unknown , ECO_Equal , ECO_NotEqual , ECO_Greater ,
ECO_GreaterOrEqual , ECO_Less , ECO_LessOrEqual
}
Functions
template<class T>
bool CompareWithOp (const T &A, EComparisonOp Op, const T &B)
EComparisonOp ParseComparisonOp (const TCHAR *&In)
static FDateTime ParseMonthDayYearDate (const FString &DateString)
Enumeration Type Documentation
EComparisonOp
enum EComparisonOp
Enumerator
ECO_Unknown
ECO_Equal
ECO_NotEqual
ECO_Greater
ECO_GreaterOrEqual
ECO_Less
ECO_LessOrEqual
Definition at line 95 of file GenericPlatformDriver.h.
Function Documentation
CompareWithOp()
template<class T> bool CompareWithOp (const T & A, EComparisonOp Op, const T & B)
Definition at line 140 of file GenericPlatformDriver.h.
References A, B, check, ECO_Equal, ECO_Greater, ECO_GreaterOrEqual, ECO_Less, ECO_LessOrEqual, and ECO_NotEqual.
Referenced by FDriverDenyListEntry::AppliesToDriver().
ParseComparisonOp()
EComparisonOp ParseComparisonOp (const TCHAR *& In) inline
Definition at line 103 of file GenericPlatformDriver.h.
References ECO_Equal, ECO_Greater, ECO_GreaterOrEqual, ECO_Less, ECO_LessOrEqual, and ECO_NotEqual.
Referenced by FDriverDenyListEntry::FDriverDateDenyListEntry::FromString(), and FDriverDenyListEntry::FDriverVersionDenyListEntry::FromString().
ParseMonthDayYearDate()
FDateTime ParseMonthDayYearDate (const FString & DateString) static
Definition at line 260 of file GenericPlatformDriver.h.
References TCString< TCHAR >::Atoi(), and TEXT.
Referenced by FDriverDenyListEntry::AppliesToDriver(), and FDriverDenyListEntry::FDriverDateDenyListEntry::FromString().