Unreal Engine 5.6 C++ API: UE::FGenericPlatformIoDispatcher Class Reference
UE::FGenericPlatformIoDispatcher Class Reference final
Data Structures
struct FFileHandle
Public Member Functions
FGenericPlatformIoDispatcher (FPlatformIoDispatcherCreateParams &&Params)
~FGenericPlatformIoDispatcher ()
virtual FIoStatus CloseFile (FIoFileHandle FileHandle) override
Close the file.
virtual TIoStatusOr< FIoFileHandle > OpenFile (const TCHAR *Filename, const FIoFileProperties &FileProperties, FIoFileStat *OutStat=nullptr) override
Open file for reading.
Public Member Functions inherited from UE::FPlatformIoDispatcherBase
virtual ~FPlatformIoDispatcherBase ()
virtual void CancelAllRequests (FIoFileHandle FileHandle) override
Cancel all inflight I/O request for the specified file.
virtual void CancelRequest (FIoFileReadRequest Request) override
Cancel inflight I/O request.
virtual void DeleteRequest (FIoFileReadRequest Request) override
Delete the request.
virtual bool Init () override final
Initializes the runnable object.
virtual FIoStatus Initialize () override final
Initialize the dispatcher.
virtual FIoFileReadRequest ReadDirect (FIoDirectReadRequestParams &&Params, FIoFileReadRequestCompleted &&OnCompleted) override
Issue a direct read request.
virtual uint32 Run () override final
Runs the runnable object.
virtual FIoFileReadRequest ScatterGather (FIoScatterGatherRequestParams &&Params, FIoFileReadRequestCompleted &&OnCompleted) override
Issue a scatter-gather request.
virtual void Stop () override final
Stops the runnable object.
virtual void UpdatePriority (FIoFileReadRequest Request, EIoFileReadPriority NewPriority) override
Update priority for an inflight I/O request.
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual class FSingleThreadRunnable * GetSingleThreadInterface ()
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
Public Member Functions inherited from UE::IPlatformIoDispatcher
virtual ~IPlatformIoDispatcher ()=default
Private Member Functions
virtual FIoPlatformFileInfo GetPlatformFileInfo (FIoFileHandle FileHandle) override final
virtual FIoStatus OnInitialize () override final
virtual uint32 OnIoThreadEntry () override final
virtual void OnWakeUp () override final
bool ProcessFileIo (bool &bOutWaitingForMemory)
virtual bool Tick () override final
Tick the dispatcher.
Private Attributes
FEventRef WakeUpEvent
Additional Inherited Members
Protected Member Functions inherited from UE::FPlatformIoDispatcherBase
FPlatformIoDispatcherBase (FPlatformIoDispatcherCreateParams &&Params)
void CompleteEncodedBlockRequest (FIoEncodedBlockRequest &EncodedBlockRequest)
void EnqueueBlocksToDecode (FIoEncodedBlockRequestList BlocksToDecode)
void EnqueueBlockToDecode (FIoEncodedBlockRequest &EncodedBlockRequest)
uint32 GetNextFileId ()
void ProcessCompletedFileBlock (FIoFileBlockRequest &FileBlockRequest)
void ProcessDecodedBlock (FIoEncodedBlockRequest &EncodedBlockRequest, FIoChunkBlockDecodeResult &&DecodeResult, FIoChunkBlockDecodeRequest &NextDecodeRequest)
void ScatterDecodedBlock (FIoEncodedBlockRequest &EncodedBlockRequest)
Protected Attributes inherited from UE::FPlatformIoDispatcherBase
FIoEncodedBlockRequestList BlocksReadyForDecoding
bool bMultithreaded = false
std::atomic_bool bStopRequested {false}
FIoChunkBlockMemoryPool ChunkBlockMemoryPool
FIoFileBlockCache FileBlockCache
FIoFileBlockMemoryPool FileBlockMemoryPool
UE::FMutex FileBlockMutex
FIoFileBlockRequestQueue FileBlockRequestQueue
uint32 FileBlockSize = 256 << 10
FPlatformIoDispatcherRequestMgr RequestMgr
UE::FMutex ScatterMutex
FPlatformIoDispatcherStats Stats
TUniquePtr< FRunnableThread > Thread
Detailed Description
Definition at line 17 of file GenericPlatformIoDispatcher.cpp.
Constructor & Destructor Documentation
FGenericPlatformIoDispatcher()
UE::FGenericPlatformIoDispatcher::FGenericPlatformIoDispatcher (FPlatformIoDispatcherCreateParams && Params)
Definition at line 51 of file GenericPlatformIoDispatcher.cpp.
References FGenericPlatformIoDispatcher(), UE::FPlatformIoDispatcherBase::FPlatformIoDispatcherBase(), MoveTemp(), and Params.
Referenced by FGenericPlatformIoDispatcher().
~FGenericPlatformIoDispatcher()
UE::FGenericPlatformIoDispatcher::~FGenericPlatformIoDispatcher ()
Definition at line 56 of file GenericPlatformIoDispatcher.cpp.
References UE::FPlatformIoDispatcherBase::bStopRequested, UE::FPlatformIoDispatcherBase::Thread, and WakeUpEvent.
Member Function Documentation
CloseFile()
FIoStatus UE::FGenericPlatformIoDispatcher::CloseFile (FIoFileHandle FileHandle) override virtual
Close the file.
Assumes no pending I/O requests are inflight for the specified file.
Implements UE::IPlatformIoDispatcher.
Definition at line 95 of file GenericPlatformIoDispatcher.cpp.
References Handle, UE::FIoFileHandle::IsValid(), FIoStatus::Ok, and UE::FIoFileHandle::Value().
GetPlatformFileInfo()
FIoPlatformFileInfo UE::FGenericPlatformIoDispatcher::GetPlatformFileInfo (FIoFileHandle FileHandle) final override private virtual
Implements UE::FPlatformIoDispatcherBase.
Definition at line 242 of file GenericPlatformIoDispatcher.cpp.
References UE::FIoFileHandle::Value().
OnInitialize()
FIoStatus UE::FGenericPlatformIoDispatcher::OnInitialize () final override private virtual
Reimplemented from UE::FPlatformIoDispatcherBase.
Definition at line 106 of file GenericPlatformIoDispatcher.cpp.
References UE::FPlatformIoDispatcherBase::ChunkBlockMemoryPool, UE::FPlatformIoDispatcherBase::FileBlockCache, UE::FPlatformIoDispatcherBase::FileBlockMemoryPool, UE::FPlatformIoDispatcherBase::FileBlockRequestQueue, UE::FPlatformIoDispatcherBase::FileBlockSize, GIoDispatcherBufferAlignment, GIoDispatcherBufferMemoryMB, GIoDispatcherBufferSizeKB, GIoDispatcherCacheSizeMB, GIoDispatcherDecompressionWorkerCount, GIoDispatcherSortRequestsByOffset, Log, FIoStatus::Ok, TEXT, and UE_LOG.
OnIoThreadEntry()
uint32 UE::FGenericPlatformIoDispatcher::OnIoThreadEntry () final override private virtual
Implements UE::FPlatformIoDispatcherBase.
Definition at line 140 of file GenericPlatformIoDispatcher.cpp.
References UE::FPlatformIoDispatcherBase::bStopRequested, ProcessFileIo(), TRACE_CPUPROFILER_EVENT_SCOPE, and WakeUpEvent.
OnWakeUp()
void UE::FGenericPlatformIoDispatcher::OnWakeUp () final override private virtual
Implements UE::FPlatformIoDispatcherBase.
Definition at line 169 of file GenericPlatformIoDispatcher.cpp.
References WakeUpEvent.
OpenFile()
TIoStatusOr< FIoFileHandle > UE::FGenericPlatformIoDispatcher::OpenFile (const TCHAR * Filename, const FIoFileProperties & FileProperties, FIoFileStat * OutStat = nullptr) override virtual
Open file for reading.
The file properties specifies whether the file is compressed, encrypted and signed.
Implements UE::IPlatformIoDispatcher.
Definition at line 66 of file GenericPlatformIoDispatcher.cpp.
References check, UE::FIoFileProperties::CompressionBlockSize, Filename, IPlatformFile::FileSize(), UE::FIoFileStat::FileSize, UE::FPlatformIoDispatcherBase::GetNextFileId(), IPlatformFile::GetPlatformPhysical(), TUniquePtr< T, Deleter >::IsValid(), MakeUnique(), NotFound, IPlatformFile::OpenReadNoBuffering(), and TUniquePtr< T, Deleter >::Release().
ProcessFileIo()
bool UE::FGenericPlatformIoDispatcher::ProcessFileIo (bool & bOutWaitingForMemory) private
Definition at line 174 of file GenericPlatformIoDispatcher.cpp.
References UE::FIoFileBlockRequest::Buffer, UE::FIoFileBlockRequest::BufferHandle, Cancelled, check, UE::FIoFileBlockRequest::Dequeued, UE::FIoFileBlockRequest::EncodedBlockRequests, UE::FIoFileBlockRequest::ErrorCode, UE::FPlatformIoDispatcherBase::FileBlockCache, UE::FPlatformIoDispatcherBase::FileBlockMemoryPool, UE::FPlatformIoDispatcherBase::FileBlockMutex, UE::FPlatformIoDispatcherBase::FileBlockRequestQueue, UE::FIoFileBlockRequest::FileHandle, UE::FIoFileBlockRequest::FileOffset, UE::FGenericPlatformIoDispatcher::FFileHandle::Handle, TArray< InElementType, InAllocatorType >::IsEmpty(), Ok, UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), UE::FIoFileBlockRequest::QueueStatus, IFileHandle::Read(), ReadError, IFileHandle::Seek(), UE::FIoFileBlockRequest::Size, UE::FPlatformIoDispatcherBase::Stats, TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, UE::FIoFileHandle::Value(), and Warning.
Referenced by OnIoThreadEntry(), and Tick().
Tick()
bool UE::FGenericPlatformIoDispatcher::Tick () final override private virtual
Tick the dispatcher.
Only used when multithreading is disabled.
Reimplemented from UE::FPlatformIoDispatcherBase.
Definition at line 123 of file GenericPlatformIoDispatcher.cpp.
References ProcessFileIo().
Field Documentation
WakeUpEvent
FEventRef UE::FGenericPlatformIoDispatcher::WakeUpEvent private
Definition at line 47 of file GenericPlatformIoDispatcher.cpp.
Referenced by ~FGenericPlatformIoDispatcher(), OnIoThreadEntry(), and OnWakeUp().
The documentation for this class was generated from the following file:
GenericPlatformIoDispatcher.cpp