Unreal Engine 5.6 C++ API: IAnimationDataController Class Reference
IAnimationDataController Class Reference abstract
#include "IAnimationDataController.h"
Public Member Functions
FFrameNumber ConvertSecondsToFrameNumber (double Seconds) const
Returns the final frame number calculating according to the Model its frame-rate, additionally outputs log information for invalid/loss of precision.
GENERATED_BODY () struct FScopedBracket
RAII helper to define a scoped-based bracket, opens and closes a controller bracket automatically.
virtual const IAnimationDataModel *const GetModel () const =0
virtual void InitializeModel ()=0
Initializes model data structures.
virtual void NotifyPopulated ()=0
Broadcast a EAnimDataModelNotifyType::Populated notify.
virtual void PopulateWithExistingModel (TScriptInterface< IAnimationDataModel > InModel)=0
Copies any animation relevant data from an already existing IAnimationDataModel object.
virtual void ResetModel (bool bShouldTransact=true)=0
Resets all data stored in the model, broadcasts a EAnimDataModelNotifyType::Reset and wraps all actions within BracketOpened/BracketClosed notifies.
virtual bool SetAttributeKey (const FAnimationAttributeIdentifier &AttributeIdentifier, float Time, const void *KeyValue, const UScriptStruct *TypeStruct, bool bShouldTransact=true)=0
Sets a single key for the attribute with provided identifier.
virtual bool SetAttributeKeys (const FAnimationAttributeIdentifier &AttributeIdentifier, TArrayView< const float > Times, TArrayView< const void * > KeyValues, const UScriptStruct *TypeStruct, bool bShouldTransact=true)=0
Replace the keys for the attribute with provided identifier.
virtual bool SetBoneTrackKeys (FName BoneName, const TArray< FVector3f > &PositionalKeys, const TArray< FQuat4f > &RotationalKeys, const TArray< FVector3f > &ScalingKeys, bool bShouldTransact=true)=0
Removes an existing bone animation track with the provided name.
virtual bool SetCurveAttributes (const FAnimationCurveIdentifier &CurveId, const FCurveAttributes &Attributes, bool bShouldTransact=true)=0
Changes the attributes of the curve with provided identifier.
template<typename AttributeType>
bool SetTypedAttributeKey (const FAnimationAttributeIdentifier &AttributeIdentifier, float Time, const AttributeType &KeyValue, bool bShouldTransact=true)
Sets a single key for the attribute with provided identifier.
template<typename AttributeType>
bool SetTypedAttributeKeys (const FAnimationAttributeIdentifier &AttributeIdentifier, TArrayView< const float > Times, TArrayView< const AttributeType > KeyValues, bool bShouldTransact=true)
Replace the keys for the attribute with provided identifier.
UE_DEPRECATED (5.1, "InsertBoneTrack has been deprecated, use AddBoneTrack instead") UFUNCTION()) virtual int32 InsertBoneTrack(FName BoneName
Inserts a new bone animation track for the provided name, at the provided index.
UE_DEPRECATED (5.1, "Resize with length in seconds in deprecated use ResizeInFrames using FFrameNumber instead") UFUNCTION()) virtual void Resize(float Length
UE_DEPRECATED (5.1, "ResizePlayLength with length in seconds in deprecated use ResizeNumberOfFrames using FFrameNumber instead") UFUNCTION()) virtual void ResizePlayLength(float NewLength
UE_DEPRECATED (5.1, "SetPlayLength with length in seconds in deprecated use SetNumberOfFrames using FFrameNumber instead") UFUNCTION()) virtual void SetPlayLength(float Length
UE_DEPRECATED (5.2, "AddBoneTrack returning index is deprecated use AddBoneCurve returning bool instead.") UFUNCTION()) virtual int32 AddBoneTrack(FName BoneName
Adds a new bone animation track for the provided name.
UE_DEPRECATED (5.3, "This function is no longer used.") UFUNCTION()) virtual void UpdateCurveNamesFromSkeleton(const USkeleton *Skeleton
Updates the display name values for any stored curve, with the names being retrieved from the provided skeleton.
UFUNCTION () virtual bool AddAttribute(const FAnimationAttributeIdentifier &AttributeIdentifier
Adds a new attribute with the provided information.
UFUNCTION () virtual bool AddCurve(const FAnimationCurveIdentifier &CurveId
Adds a new curve with the provided information.
UFUNCTION () virtual bool DuplicateAttribute(const FAnimationAttributeIdentifier &AttributeIdentifier
Duplicated the attribute (curve) with the identifier.
UFUNCTION () virtual bool DuplicateCurve(const FAnimationCurveIdentifier &CopyCurveId
Duplicated the curve with the identifier.
UFUNCTION () virtual bool RemoveAttribute(const FAnimationAttributeIdentifier &AttributeIdentifier
Removes an attribute, if found, with the provided information.
UFUNCTION () virtual bool RemoveAttributeKey(const FAnimationAttributeIdentifier &AttributeIdentifier
Remove a single key from the attribute with provided identifier.
UFUNCTION () virtual bool RemoveBoneTrack(FName BoneName
Removes an existing bone animation track with the provided name.
UFUNCTION () virtual bool RemoveCurve(const FAnimationCurveIdentifier &CurveId
Remove the curve with provided identifier.
UFUNCTION () virtual bool RemoveCurveKey(const FAnimationCurveIdentifier &CurveId
Remove a single key from the curve with provided identifier and name.
UFUNCTION () virtual bool RemoveTransformCurveKey(const FAnimationCurveIdentifier &CurveId
Removes a single key for the transform curve with provided identifier.
UFUNCTION () virtual bool RenameCurve(const FAnimationCurveIdentifier &CurveToRenameId
Renames the curve with provided identifier.
UFUNCTION () virtual bool ScaleCurve(const FAnimationCurveIdentifier &CurveId
Scales the curve with provided identifier.
UFUNCTION () virtual bool SetBoneTrackKeys(FName BoneName
Removes an existing bone animation track with the provided name.
UFUNCTION () virtual bool SetCurveColor(const FAnimationCurveIdentifier &CurveId
Changes the color of the curve with provided identifier.
UFUNCTION () virtual bool SetCurveComment(const FAnimationCurveIdentifier &CurveId
Changes the comment of the curve with provided identifier.
UFUNCTION () virtual bool SetCurveFlag(const FAnimationCurveIdentifier &CurveId
Set an individual flag for the curve with provided identifier.
UFUNCTION () virtual bool SetCurveFlags(const FAnimationCurveIdentifier &CurveId
Replace the flags for the curve with provided identifier.
UFUNCTION () virtual bool SetCurveKey(const FAnimationCurveIdentifier &CurveId
Sets a single key for the curve with provided identifier and name.
UFUNCTION () virtual bool SetCurveKeys(const FAnimationCurveIdentifier &CurveId
Replace the keys for the curve with provided identifier and name.
UFUNCTION () virtual bool SetTransformCurveKey(const FAnimationCurveIdentifier &CurveId
Sets a single key for the transform curve with provided identifier.
UFUNCTION () virtual bool SetTransformCurveKeys(const FAnimationCurveIdentifier &CurveId
Replace the keys for the transform curve with provided identifier.
UFUNCTION () virtual int32 RemoveAllAttributes(bool bShouldTransact
Removes all stored attributes.
UFUNCTION () virtual int32 RemoveAllAttributesForBone(const FName &BoneName
Removes all attributes for the specified bone name, if any.
UFUNCTION () virtual TScriptInterface< IAnimationDataModel > GetModelInterface() const =0
UFUNCTION () virtual void CloseBracket(bool bShouldTransact
Closes a previously opened interaction bracket, used for combining a set of controller actions.
UFUNCTION () virtual void OpenBracket(const FText &InTitle
Opens an interaction bracket, used for combining a set of controller actions.
UFUNCTION () virtual void RemoveAllBoneTracks(bool bShouldTransact
Removes all existing Bone Animation tracks.
UFUNCTION () virtual void RemoveAllCurvesOfType(ERawCurveTrackTypes SupportedCurveType
Removes all the curves of the provided type.
UFUNCTION () virtual void ResizeInFrames(FFrameNumber NewLengthInFrames
Sets the total play-able length in seconds and resizes curves.
UFUNCTION () virtual void ResizeNumberOfFrames(FFrameNumber NewLengthInFrames
UFUNCTION () virtual void SetFrameRate(FFrameRate FrameRate
Sets the frame rate according to which the bone animation is expected to be sampled.
UFUNCTION () virtual void SetModel(TScriptInterface< IAnimationDataModel > InModel)=0
Sets the AnimDataModel instance this controller is supposed to be targeting.
UFUNCTION () virtual void SetNumberOfFrames(FFrameNumber NewLengthInFrames
Sets the total play-able length in seconds.
virtual void UpdateAttributesFromSkeleton (const USkeleton *Skeleton, bool bShouldTransact=true)=0
Removes any bone attribute for which the name was not found in the provided skeleton.
virtual bool UpdateBoneTrackKeys (FName BoneName, const FInt32Range &KeyRangeToSet, const TArray< FVector > &PositionalKeys, const TArray< FQuat > &RotationalKeys, const TArray< FVector > &ScalingKeys, bool bShouldTransact=true)=0
Sets a range of keys for an existing bone animation track with the provided name.
virtual bool UpdateBoneTrackKeys (FName BoneName, const FInt32Range &KeyRangeToSet, const TArray< FVector3f > &PositionalKeys, const TArray< FQuat4f > &RotationalKeys, const TArray< FVector3f > &ScalingKeys, bool bShouldTransact=true)=0
Sets a range of keys for an existing bone animation track with the provided name.
virtual void UpdateWithSkeleton (USkeleton *TargetSkeleton, bool bShouldTransact=true)=0
Updates/removes/remaps contained animation data according to the newly assigned skeleton.
Static Public Member Functions
template<typename FmtType, typename... Types>
static void Reportf (ELogVerbosity::Type LogVerbosity, const UObject *ErrorObject, const FmtType &Fmt, Types... Args)
static void ReportMessage (const UObject *ErrorObject, const FText &InMessage, ELogVerbosity::Type LogVerbosity)
template<typename FmtType, typename... Types>
static void ReportObjectErrorf (const UObject *ErrorObject, const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
static void ReportObjectWarningf (const UObject *ErrorObject, const FmtType &Fmt, Types... Args)
Data Fields
bool bShouldTransact = true) = 0
FFrameNumber FFrameNumber bool bShouldTransact = true) = 0
float float bool bShouldTransact = true) = 0
int32 bool bShouldTransact = true) = 0
const TArray< FVector > const TArray< FQuat > const TArray< FVector > bool bShouldTransact = true) = 0
const FAnimationCurveIdentifier bool bShouldTransact = true) = 0
EAnimAssetCurveFlags bool bool bShouldTransact = true) = 0
const TArray< FTransform > const TArray< float > bool bShouldTransact = true) = 0
float const FTransform bool bShouldTransact = true) = 0
float bool bShouldTransact = true) = 0
FLinearColor bool bShouldTransact = true) = 0
const FString bool bShouldTransact = true) = 0
const FRichCurveKey bool bShouldTransact = true) = 0
const TArray< FRichCurveKey > bool bShouldTransact = true) = 0
ERawCurveTrackTypes bool bShouldTransact
const FAnimationAttributeIdentifier bool bShouldTransact = true) = 0
EAnimAssetCurveFlags bool bState = true
FLinearColor Color
const FString & Comment
int32 CurveFlags = 0x00000004
const TArray< FRichCurveKey > & CurveKeys
int32 DesiredIndex
float float Factor
EAnimAssetCurveFlags Flag
int32 Flags
const FRichCurveKey & Key
const FAnimationAttributeIdentifier & NewAttributeIdentifier
const FAnimationCurveIdentifier & NewCurveId
float Origin
const TArray< FVector > & PositionalKeys
const TArray< FVector > const TArray< FQuat > & RotationalKeys
const TArray< FVector > const TArray< FQuat > const TArray< FVector > & ScalingKeys
ERawCurveTrackTypes SupportedCurveType
FFrameNumber T0
float T0
FFrameNumber FFrameNumber T1
float float T1
float Time
const TArray< FTransform > const TArray< float > & TimeKeys
const TArray< FTransform > & TransformValues
float const FTransform & Value
Protected Types
typedef TUniquePtr< IAnimationDataController::FScopedBracket > FBracket
typedef TUniquePtr< UE::FScopedCompoundTransaction > FTransaction
Protected Member Functions
bool CheckOuterClass (UClass *InClass) const
Verifies whether or not the Model's outer object is (or is derived from) the specified UClass.
template<typename ActionClass, class... ActionArguments>
void ConditionalAction (bool bCondition, ActionArguments &&... Arguments)
FBracket ConditionalBracket (const FText &Description, bool bCondition)
FTransaction ConditionalTransaction (const FText &Description, bool bCondition)
virtual void NotifyBracketClosed ()=0
virtual void NotifyBracketOpen ()=0
Functionality used by FOpenBracketAction and FCloseBracketAction to broadcast their equivalent notifies without actually opening a bracket.
void Report (ELogVerbosity::Type Verbosity, const FText &Message) const
void ReportError (const FText &Message) const
template<typename FmtType, typename... Types>
void ReportErrorf (const FmtType &Fmt, Types... Args) const
template<typename FmtType, typename... Types>
void Reportf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args) const
void ReportWarning (const FText &Message) const
template<typename FmtType, typename... Types>
void ReportWarningf (const FmtType &Fmt, Types... Args) const
void ValidateModel () const
Ensures that a valid model is currently targeted.
Static Protected Member Functions
static FString GetCurveTypeValueName (ERawCurveTrackTypes InType)
Returns the string representation of the provided curve enum type value.
static bool IsSupportedCurveType (ERawCurveTrackTypes CurveType)
Returns whether or not the supplied curve type is supported by the controller functionality.
Protected Attributes
UE::FChangeTransactor ChangeTransactor
Static Protected Attributes
static constexpr int32 DefaultCurveFlags = EAnimAssetCurveFlags::AACF_Editable
Friends
class FAnimDataControllerTestBase
Detailed Description
Definition at line 49 of file IAnimationDataController.h.
Member Typedef Documentation
FBracket
typedef TUniquePtr<IAnimationDataController::FScopedBracket> IAnimationDataController::FBracket protected
Definition at line 824 of file IAnimationDataController.h.
FTransaction
typedef TUniquePtr<UE::FScopedCompoundTransaction> IAnimationDataController::FTransaction protected
Definition at line 813 of file IAnimationDataController.h.
Member Function Documentation
CheckOuterClass()
bool IAnimationDataController::CheckOuterClass (UClass * InClass) const inline protected
Verifies whether or not the Model's outer object is (or is derived from) the specified UClass.
Definition at line 772 of file IAnimationDataController.h.
References FText::FromString(), UObjectBase::GetClass(), UObjectBaseUtility::GetName(), UStruct::IsChildOf(), NSLOCTEXT, ReportErrorf(), and ValidateModel().
ConditionalAction()
template<typename ActionClass, class... ActionArguments> void IAnimationDataController::ConditionalAction (bool bCondition, ActionArguments &&... Arguments) inline protected
Definition at line 831 of file IAnimationDataController.h.
References UE::FChangeTransactor::CanTransactChanges(), ChangeTransactor, and Forward().
ConditionalBracket()
FBracket IAnimationDataController::ConditionalBracket (const FText & Description, bool bCondition) inline protected
Definition at line 825 of file IAnimationDataController.h.
References UE::FChangeTransactor::CanTransactChanges(), and MakeUnique().
ConditionalTransaction()
FTransaction IAnimationDataController::ConditionalTransaction (const FText & Description, bool bCondition) inline protected
Definition at line 814 of file IAnimationDataController.h.
References UE::FChangeTransactor::CanTransactChanges(), ChangeTransactor, and MakeUnique().
ConvertSecondsToFrameNumber()
FFrameNumber IAnimationDataController::ConvertSecondsToFrameNumber (double Seconds) const inline
Returns the final frame number calculating according to the Model its frame-rate, additionally outputs log information for invalid/loss of precision.
Definition at line 700 of file IAnimationDataController.h.
References FFrameTime::AsDecimal(), FFrameRate::AsFrameTime(), FText::AsNumber(), FFrameRate::AsSeconds(), ConvertSecondsToFrameNumber(), FFrameTime::GetFrame(), GetModel(), FFrameTime::GetSubFrame(), FMath::IsNearlyZero(), LOCTEXT, ReportWarningf(), Seconds, FNumberFormattingOptions::SetMaximumFractionalDigits(), FNumberFormattingOptions::SetMinimumFractionalDigits(), FFrameRate::ToPrettyText(), UE_DOUBLE_KINDA_SMALL_NUMBER, UE_KINDA_SMALL_NUMBER, and ValidateModel().
Referenced by ConvertSecondsToFrameNumber().
GENERATED_BODY()
IAnimationDataController::GENERATED_BODY () inline
RAII helper to define a scoped-based bracket, opens and closes a controller bracket automatically.
Definition at line 52 of file IAnimationDataController.h.
References bShouldTransact.
GetCurveTypeValueName()
FString IAnimationDataController::GetCurveTypeValueName (ERawCurveTrackTypes InType) inline static protected
Returns the string representation of the provided curve enum type value.
Definition at line 799 of file IAnimationDataController.h.
References Enum, and TEXT.
GetModel()
virtual const IAnimationDataModel *const IAnimationDataController::GetModel () const pure virtual
Returns
The IAnimationDataModel instance this controller is currently targeting
Referenced by ConvertSecondsToFrameNumber(), and ValidateModel().
InitializeModel()
virtual void IAnimationDataController::InitializeModel () pure virtual
Initializes model data structures.
References InitializeModel().
Referenced by InitializeModel().
IsSupportedCurveType()
bool IAnimationDataController::IsSupportedCurveType (ERawCurveTrackTypes CurveType) inline static protected
Returns whether or not the supplied curve type is supported by the controller functionality.
Definition at line 759 of file IAnimationDataController.h.
References TArray< InElementType, InAllocatorType >::Contains().
NotifyBracketClosed()
virtual void IAnimationDataController::NotifyBracketClosed () protected pure virtual
NotifyBracketOpen()
virtual void IAnimationDataController::NotifyBracketOpen () protected pure virtual
Functionality used by FOpenBracketAction and FCloseBracketAction to broadcast their equivalent notifies without actually opening a bracket.
NotifyPopulated()
virtual void IAnimationDataController::NotifyPopulated () pure virtual
Broadcast a EAnimDataModelNotifyType::Populated notify.
PopulateWithExistingModel()
virtual void IAnimationDataController::PopulateWithExistingModel (TScriptInterface< IAnimationDataModel > InModel) pure virtual
Copies any animation relevant data from an already existing IAnimationDataModel object.
References PopulateWithExistingModel().
Referenced by PopulateWithExistingModel().
Report()
void IAnimationDataController::Report (ELogVerbosity::Type Verbosity, const FText & Message) const inline protected
Definition at line 737 of file IAnimationDataController.h.
References ReportMessage().
ReportError()
void IAnimationDataController::ReportError (const FText & Message) const inline protected
Definition at line 753 of file IAnimationDataController.h.
References ELogVerbosity::Error, and ReportMessage().
Referenced by ReportErrorf().
ReportErrorf()
template<typename FmtType, typename... Types> void IAnimationDataController::ReportErrorf (const FmtType & Fmt, Types... Args) const inline protected
Definition at line 732 of file IAnimationDataController.h.
References FText::Format(), and ReportError().
Referenced by CheckOuterClass().
Reportf() [1/2]
template<typename FmtType, typename... Types> void IAnimationDataController::Reportf (ELogVerbosity::Type LogVerbosity, const UObject * ErrorObject, const FmtType & Fmt, Types... Args) inline static
Definition at line 856 of file IAnimationDataController.h.
References ELogVerbosity::Error, FText::Format(), and ReportMessage().
Reportf() [2/2]
template<typename FmtType, typename... Types> void IAnimationDataController::Reportf (ELogVerbosity::Type Verbosity, const FmtType & Fmt, Types... Args) const inline protected
Definition at line 743 of file IAnimationDataController.h.
References FText::Format(), and ReportMessage().
ReportMessage()
void IAnimationDataController::ReportMessage (const UObject * ErrorObject, const FText & InMessage, ELogVerbosity::Type LogVerbosity) static
Referenced by Report(), ReportError(), Reportf(), Reportf(), ReportObjectErrorf(), ReportObjectWarningf(), and ReportWarning().
ReportObjectErrorf()
template<typename FmtType, typename... Types> void IAnimationDataController::ReportObjectErrorf (const UObject * ErrorObject, const FmtType & Fmt, Types... Args) inline static
Definition at line 850 of file IAnimationDataController.h.
References ELogVerbosity::Error, FText::Format(), and ReportMessage().
ReportObjectWarningf()
template<typename FmtType, typename... Types> void IAnimationDataController::ReportObjectWarningf (const UObject * ErrorObject, const FmtType & Fmt, Types... Args) inline static
Definition at line 844 of file IAnimationDataController.h.
References FText::Format(), ReportMessage(), and ELogVerbosity::Warning.
ReportWarning()
void IAnimationDataController::ReportWarning (const FText & Message) const inline protected
Definition at line 748 of file IAnimationDataController.h.
References ReportMessage(), and ELogVerbosity::Warning.
Referenced by ReportWarningf().
ReportWarningf()
template<typename FmtType, typename... Types> void IAnimationDataController::ReportWarningf (const FmtType & Fmt, Types... Args) const inline protected
Definition at line 726 of file IAnimationDataController.h.
References FText::Format(), and ReportWarning().
Referenced by ConvertSecondsToFrameNumber().
ResetModel()
virtual void IAnimationDataController::ResetModel (bool bShouldTransact = true) pure virtual
Resets all data stored in the model, broadcasts a EAnimDataModelNotifyType::Reset and wraps all actions within BracketOpened/BracketClosed notifies.
Bone tracks, broadcasts a EAnimDataModelNotifyType::TrackRemoved for each
Curves, broadcasts a EAnimDataModelNotifyType::CurveRemoves for each
Play length to one frame at 30fps, broadcasts a EAnimDataModelNotifyType::PlayLengthChanged
Frame rate to 30fps, broadcasts a EAnimDataModelNotifyType::FrameRateChanged
Parameters
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact.
SetAttributeKey()
virtual bool IAnimationDataController::SetAttributeKey (const FAnimationAttributeIdentifier & AttributeIdentifier, float Time, const void * KeyValue, const UScriptStruct * TypeStruct, bool bShouldTransact = true) pure virtual
Sets a single key for the attribute with provided identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeChanged notify if successful. In case a key for the provided key time already exists the key is replaced.
Parameters
AttributeIdentifier Identifier for the attribute for which the key is to be set
Time Time of the to-be-set key
KeyValue Value of the to-be-set key
TypeStruct UScriptStruct describing the type of KeyValue
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the key was successfully set
References bShouldTransact, and Time.
Referenced by SetTypedAttributeKey().
SetAttributeKeys()
virtual bool IAnimationDataController::SetAttributeKeys (const FAnimationAttributeIdentifier & AttributeIdentifier, TArrayView< const float > Times, TArrayView< const void * > KeyValues, const UScriptStruct * TypeStruct, bool bShouldTransact = true) pure virtual
Replace the keys for the attribute with provided identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeChanged notify if successful.
Parameters
AttributeIdentifier Identifier for the attribute for which the keys are to be replaced
Times Times with which the existing key timings are to be replaced
KeyValues Values with which the existing key values are to be replaced
TypeStruct UScriptStruct describing the type of KeyValues
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not replacing the attribute keys was successful
References bShouldTransact.
Referenced by SetTypedAttributeKeys().
SetBoneTrackKeys()
virtual bool IAnimationDataController::SetBoneTrackKeys (FName BoneName, const TArray< FVector3f > & PositionalKeys, const TArray< FQuat4f > & RotationalKeys, const TArray< FVector3f > & ScalingKeys, bool bShouldTransact = true) pure virtual
Removes an existing bone animation track with the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackChanged notify if successful. The provided number of keys provided is expected to match for each component, and be non-zero.
Parameters
BoneName Bone name of the track for which the keys should be set
PositionalKeys Array of keys for the translation component
RotationalKeys Array of keys for the rotation component
ScalingKeys Array of keys for the scale component
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the keys were successfully set
References bShouldTransact, PositionalKeys, RotationalKeys, ScalingKeys, and SetBoneTrackKeys().
Referenced by SetBoneTrackKeys().
SetCurveAttributes()
virtual bool IAnimationDataController::SetCurveAttributes (const FAnimationCurveIdentifier & CurveId, const FCurveAttributes & Attributes, bool bShouldTransact = true) pure virtual
Changes the attributes of the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful.
Parameters
CurveId Identifier of the curve to change the color for
Attributes Attribute values to be applied
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve attributes were set successfully
References bShouldTransact, and SetCurveAttributes().
Referenced by SetCurveAttributes().
SetTypedAttributeKey()
template<typename AttributeType> bool IAnimationDataController::SetTypedAttributeKey (const FAnimationAttributeIdentifier & AttributeIdentifier, float Time, const AttributeType & KeyValue, bool bShouldTransact = true) inline
Sets a single key for the attribute with provided identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeChanged notify if successful. In case a key for the provided key time already exists the key is replaced.
Parameters
AttributeIdentifier Identifier for the attribute for which the key is to be set
Time Time of the to-be-set key
KeyValue Value (templated) of the to-be-set key
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the key was successfully set
Definition at line 607 of file IAnimationDataController.h.
References bShouldTransact, SetAttributeKey(), and Time.
SetTypedAttributeKeys()
template<typename AttributeType> bool IAnimationDataController::SetTypedAttributeKeys (const FAnimationAttributeIdentifier & AttributeIdentifier, TArrayView< const float > Times, TArrayView< const AttributeType > KeyValues, bool bShouldTransact = true) inline
Replace the keys for the attribute with provided identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeChanged notify if successful.
Parameters
AttributeIdentifier Identifier for the attribute for which the keys are to be replaced
Times Times with which the existing key timings are to be replaced
KeyValues Values (templated) with which the existing key values are to be replaced
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not replacing the attribute keys was successful
Definition at line 650 of file IAnimationDataController.h.
References bShouldTransact, MakeArrayView(), SetAttributeKeys(), Algo::Transform(), and Value.
Referenced by UE::Anim::AddTypedCustomAttribute().
UE_DEPRECATED() [1/6]
IAnimationDataController::UE_DEPRECATED (5. 1, "InsertBoneTrack has been deprecated, use AddBoneTrack instead")
Inserts a new bone animation track for the provided name, at the provided index.
Broadcasts a EAnimDataModelNotifyType::TrackAdded notify if successful. The bone name is verified with the AnimModel's outer target USkeleton to ensure the bone exists.
Parameters
BoneName Bone name for which a track should be inserted
DesiredIndex Index at which the track should be inserted
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
The index at which the bone track was inserted, INDEX_NONE if the insertion failed
References Category, meta, and UFUNCTION().
UE_DEPRECATED() [2/6]
IAnimationDataController::UE_DEPRECATED (5. 1, "Resize with length in seconds in deprecated use ResizeInFrames using FFrameNumber instead")
References bShouldTransact, Category, meta, T0, T1, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [3/6]
IAnimationDataController::UE_DEPRECATED (5. 1, "ResizePlayLength with length in seconds in deprecated use ResizeNumberOfFrames using FFrameNumber instead")
References Category, meta, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [4/6]
IAnimationDataController::UE_DEPRECATED (5. 1, "SetPlayLength with length in seconds in deprecated use SetNumberOfFrames using FFrameNumber instead")
References bShouldTransact, Category, meta, UE_DEPRECATED(), and UFUNCTION().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/6]
IAnimationDataController::UE_DEPRECATED (5. 2, "AddBoneTrack returning index is deprecated use AddBoneCurve returning bool instead.")
Adds a new bone animation track for the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackAdded notify if successful.
Parameters
BoneName Bone name for which a track should be added
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
The index at which the bone track was added, INDEX_NONE if adding it failed
References bShouldTransact, Category, INDEX_NONE, meta, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [6/6]
IAnimationDataController::UE_DEPRECATED (5. 3, "This function is no longer used.") const
Updates the display name values for any stored curve, with the names being retrieved from the provided skeleton.
Broadcasts a EAnimDataModelNotifyType::CurveRenamed for each to-be-updated curve name, wrapped within BracketOpened/BracketClosed notifies.
Parameters
Skeleton Skeleton to retrieve the display name values from
SupportedCurveType Curve type for which the names should be updated
bShouldTransact Whether or not any undo-redo changes should be generated
References Category, meta, UE_DEPRECATED(), and UFUNCTION().
UFUNCTION() [1/33]
IAnimationDataController::UFUNCTION () const &
Adds a new attribute with the provided information.
Broadcasts a EAnimDataModelNotifyType::AttributeAdded notify if successful.
Parameters
AttributeIdentifier Identifier for the to-be-added attribute
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the attribute was successfully added
References bShouldTransact, and Category.
UFUNCTION() [2/33]
IAnimationDataController::UFUNCTION () const &
Adds a new curve with the provided information.
Broadcasts a EAnimDataModelNotifyType::CurveAdded notify if successful.
Parameters
CurveId Identifier for the to-be-added curve
CurveFlags Flags to be set for the curve
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve was successfully added
References Category, and UFUNCTION().
UFUNCTION() [3/33]
IAnimationDataController::UFUNCTION () const &
Duplicated the attribute (curve) with the identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeAdded notify if successful.
Parameters
AttributeIdentifier Identifier for the to-be-duplicated attribute
NewAttributeIdentifier Identifier for the to-be-added attribute
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the attribute was successfully duplicated
References Category.
UFUNCTION() [4/33]
IAnimationDataController::UFUNCTION () const &
Duplicated the curve with the identifier.
Broadcasts a EAnimDataModelNotifyType::CurveAdded notify if successful.
Parameters
CopyCurveId Identifier for the to-be-duplicated curve
NewCurveId Identifier for the to-be-added curve
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve was successfully duplicated
References Category, and UFUNCTION().
UFUNCTION() [5/33]
IAnimationDataController::UFUNCTION () const &
Removes an attribute, if found, with the provided information.
Broadcasts a EAnimDataModelNotifyType::AttributeRemoved notify if successful.
Parameters
AttributeIdentifier Identifier for the to-be-removed attribute
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the attribute was successfully removed
References bShouldTransact, and Category.
UFUNCTION() [6/33]
IAnimationDataController::UFUNCTION () const &
Remove a single key from the attribute with provided identifier.
Broadcasts a EAnimDataModelNotifyType::AttributeChanged notify if successful.
Parameters
AttributeIdentifier Identifier for the attribute from which the key is to be removed
Time Time of the key to be removed
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the attribute key was successfully removed
References bShouldTransact, Category, and Time.
UFUNCTION() [7/33]
IAnimationDataController::UFUNCTION ()
Removes an existing bone animation track with the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackRemoved notify if successful.
Parameters
BoneName Bone name of the track which should be removed
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the removal was successful
References bShouldTransact, Category, and UFUNCTION().
UFUNCTION() [8/33]
IAnimationDataController::UFUNCTION () const &
Remove the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveRemoved notify if successful.
Parameters
CurveId Identifier for the to-be-removed curve
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve was successfully removed
References bShouldTransact, Category, and UFUNCTION().
UFUNCTION() [9/33]
IAnimationDataController::UFUNCTION () const &
Remove a single key from the curve with provided identifier and name.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful.
Parameters
CurveId Identifier for the curve for which the key is to be removed
Time Time of the key to be removed
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve key was successfully removed
References bShouldTransact, Category, Time, and UFUNCTION().
UFUNCTION() [10/33]
IAnimationDataController::UFUNCTION () const &
Removes a single key for the transform curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful.
Parameters
CurveId Identifier for the transform curve for which the key is to be removed
Time Time of the key to be removed
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the transform curve key was successfully removed
References Category, and UFUNCTION().
UFUNCTION() [11/33]
IAnimationDataController::UFUNCTION () const &
Renames the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveRenamed notify if successful.
Parameters
CurveToRenameId Identifier for the curve to be renamed
NewCurveId Time of the key to be removed
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve was successfully renamed
References bShouldTransact, Category, NewCurveId, and UFUNCTION().
UFUNCTION() [12/33]
IAnimationDataController::UFUNCTION () const &
Scales the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveScaled notify if successful.
Parameters
CurveId Identifier of the curve to scale
Origin Time to use as the origin when scaling the curve
Factor Factor with which the curve is supposed to be scaled
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not scaling the curve was successful
References Category, and UFUNCTION().
UFUNCTION() [13/33]
IAnimationDataController::UFUNCTION ()
Removes an existing bone animation track with the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackChanged notify if successful. The provided number of keys provided is expected to match for each component, and be non-zero.
Parameters
BoneName Bone name of the track for which the keys should be set
PositionalKeys Array of keys for the translation component
RotationalKeys Array of keys for the rotation component
ScalingKeys Array of keys for the scale component
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the keys were successfully set
References Category, and UFUNCTION().
UFUNCTION() [14/33]
IAnimationDataController::UFUNCTION () const &
Changes the color of the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveColorChanged notify if successful. Currently changing curve colors is only supported for float curves.
Parameters
CurveId Identifier of the curve to change the color for
Color Color to which the curve is to be set
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve color was successfully changed
References Category, and UFUNCTION().
UFUNCTION() [15/33]
IAnimationDataController::UFUNCTION () const &
Changes the comment of the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveCommentChanged notify if successful. Currently changing curve comments is only supported for float curves.
Parameters
CurveId Identifier of the curve to change the comment for
Comment Comment to which the curve is to be set
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve comment was successfully changed
References Category, and UFUNCTION().
UFUNCTION() [16/33]
IAnimationDataController::UFUNCTION () const &
Set an individual flag for the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveFlagsChanged notify if successful.
Parameters
CurveId Identifier for the curve for which the flag state is to be set
Flag Flag for which the state is supposed to be set
bState State of the flag to be, true=set/false=not set
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the flag state was successfully set
References Category, and UFUNCTION().
UFUNCTION() [17/33]
IAnimationDataController::UFUNCTION () const &
Replace the flags for the curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveFlagsChanged notify if successful.
Parameters
CurveId Identifier for the curve for which the flag state is to be set
Flags Flag mask with which the existing flags are to be replaced
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the flag mask was successfully set
References Category, and UFUNCTION().
UFUNCTION() [18/33]
IAnimationDataController::UFUNCTION () const &
Sets a single key for the curve with provided identifier and name.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful. In case a key for the provided key time already exists the key is replaced.
Parameters
CurveId Identifier for the curve for which the key is to be set
Key Key to be set
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the curve key was successfully set
References Category, and UFUNCTION().
UFUNCTION() [19/33]
IAnimationDataController::UFUNCTION () const &
Replace the keys for the curve with provided identifier and name.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful.
Parameters
CurveId Identifier for the curve for which the keys are to be replaced
CurveKeys Keys with which the existing keys are to be replaced
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not replacing curve keys was successful
References Category, and UFUNCTION().
UFUNCTION() [20/33]
IAnimationDataController::UFUNCTION () const &
Sets a single key for the transform curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful. In case a key for any of the individual transform channel curves already exists the value is replaced.
Parameters
CurveId Identifier for the transform curve for which the key is to be set
Time Time of the key to be set
Value Value of the key to be set
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the transform curve key was successfully set
References Category, and UFUNCTION().
UFUNCTION() [21/33]
IAnimationDataController::UFUNCTION () const &
Replace the keys for the transform curve with provided identifier.
Broadcasts a EAnimDataModelNotifyType::CurveChanged notify if successful.
Parameters
CurveId Identifier for the transform curve for which the keys are to be set
TransformValues Transform Values with which the existing values are to be replaced
TimeKeys Time Keys with which the existing keys are to be replaced
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the transform curve keys were successfully set
References Category, and UFUNCTION().
UFUNCTION() [22/33]
IAnimationDataController::UFUNCTION ()
Removes all stored attributes.
Broadcasts a EAnimDataModelNotifyType::AttributeRemoved notify for each removed attribute.
Parameters
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Total number of removes attributes
References bShouldTransact, and Category.
UFUNCTION() [23/33]
IAnimationDataController::UFUNCTION () const &
Removes all attributes for the specified bone name, if any.
Broadcasts a EAnimDataModelNotifyType::AttributeRemoved notify for each removed attribute.
Parameters
BoneName Name of the bone to remove attributes for
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Total number of removes attributes
References bShouldTransact, and Category.
UFUNCTION() [24/33]
IAnimationDataController::UFUNCTION () const pure virtual
Returns
The IAnimationDataModel instance this controller is currently targeting
References Category.
UFUNCTION() [25/33]
IAnimationDataController::UFUNCTION ()
Closes a previously opened interaction bracket, used for combining a set of controller actions.
Broadcasts a EAnimDataModelNotifyType::BracketClosed notify.
Parameters
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, and UFUNCTION().
UFUNCTION() [26/33]
IAnimationDataController::UFUNCTION () const &
Opens an interaction bracket, used for combining a set of controller actions.
Broadcasts a EAnimDataModelNotifyType::BracketOpened notify, this can be used by any Views or dependent systems to halt any unnecessary or invalid operations until the (last) bracket is closed.
Parameters
InTitle Description of the bracket, e.g. "Generating Curve Data"
bShouldTransact Whether or not any undo-redo changes should be generated
References Category.
UFUNCTION() [27/33]
IAnimationDataController::UFUNCTION ()
Removes all existing Bone Animation tracks.
Broadcasts a EAnimDataModelNotifyType::TrackRemoved for each removed track, wrapped within BracketOpened/BracketClosed notifies.
Parameters
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, and UFUNCTION().
UFUNCTION() [28/33]
IAnimationDataController::UFUNCTION ()
Removes all the curves of the provided type.
Broadcasts a EAnimDataModelNotifyType::CurveRemoved for each removed curve, wrapped within BracketOpened/BracketClosed notifies.
Parameters
SupportedCurveType Type for which all curves are to be removed
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, SupportedCurveType, and UFUNCTION().
UFUNCTION() [29/33]
IAnimationDataController::UFUNCTION ()
Sets the total play-able length in seconds and resizes curves.
Broadcasts EAnimDataModelNotifyType::SequenceLengthChanged and EAnimDataModelNotifyType::CurveChanged notifies if successful. T0 and T1 are expected to represent the window of time that was either added or removed. E.g. for insertion T0 indicates the time at which additional time starts and T1 were it ends. For removal T0 indicates the time at which time should be started to remove, and T1 indicates the end. Giving a total of T1 - T0 added or removed length. The number of frames and keys for the provided length is recalculated according to the current value of UAnimDataModel::FrameRate.
Parameters
NewLengthInFrames Total new play-able number of frames value (according to frame rate), has to be positive and non-zero
T0 Point between 0 and NewLengthInFrames at which the change in length starts
T1 Point between 0 and NewLengthInFrames at which the change in length ends
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, T0, T1, and UFUNCTION().
UFUNCTION() [30/33]
IAnimationDataController::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [31/33]
IAnimationDataController::UFUNCTION ()
Sets the frame rate according to which the bone animation is expected to be sampled.
Broadcasts a EAnimDataModelNotifyType::FrameRateChanged notify if successful. The number of frames and keys for the provided frame rate is recalculated according to the current value of UAnimDataModel::PlayLength.
Parameters
FrameRate The new sampling frame rate, has to be positive and non-zero
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, FrameRate, and UFUNCTION().
UFUNCTION() [32/33]
IAnimationDataController::UFUNCTION () pure virtual
Sets the AnimDataModel instance this controller is supposed to be targeting.
Parameters
InModel IAnimationDataModel instance to target
References Category.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [33/33]
IAnimationDataController::UFUNCTION ()
Sets the total play-able length in seconds.
Broadcasts a EAnimDataModelNotifyType::SequenceLengthChanged notify if successful. The number of frames and keys for the provided length is recalculated according to the current value of UAnimDataModel::FrameRate.
Parameters
NewLengthInFrames Total new play-able number of frames value (according to frame rate), has to be positive and non-zero
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, Category, and UFUNCTION().
UpdateAttributesFromSkeleton()
virtual void IAnimationDataController::UpdateAttributesFromSkeleton (const USkeleton * Skeleton, bool bShouldTransact = true) pure virtual
Removes any bone attribute for which the name was not found in the provided skeleton.
Broadcasts a EAnimDataModelNotifyType::AttributeRemoved for each attribute which was not found in the skeleton, wrapped within BracketOpened/BracketClosed notifies. Updates any bone attribute for which the bone index is different in the provided skeleton. Broadcasts a EAnimDataModelNotifyType::AttributeAdded and EAnimDataModelNotifyType::AttributeRemove for each attribute which was remapped
Parameters
Skeleton Skeleton to retrieve the bone information from
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, and Skeleton.
UpdateBoneTrackKeys() [1/2]
virtual bool IAnimationDataController::UpdateBoneTrackKeys (FName BoneName, const FInt32Range & KeyRangeToSet, const TArray< FVector > & PositionalKeys, const TArray< FQuat > & RotationalKeys, const TArray< FVector > & ScalingKeys, bool bShouldTransact = true) pure virtual
Sets a range of keys for an existing bone animation track with the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackChanged notify if successful. The provided number of keys provided is expected to match for each component, be between FrameLowerBound and FrameUpperBound (inclusive), and be non-zero.
Parameters
BoneName Bone name of the track for which the keys should be set
KeyRangeToSet Range of frames to set keys for
PositionalKeys Array of keys for the translation component
RotationalKeys Array of keys for the rotation component
ScalingKeys Array of keys for the scale component
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the keys were successfully set
References bShouldTransact, FVector, PositionalKeys, RotationalKeys, ScalingKeys, and UpdateBoneTrackKeys().
UpdateBoneTrackKeys() [2/2]
virtual bool IAnimationDataController::UpdateBoneTrackKeys (FName BoneName, const FInt32Range & KeyRangeToSet, const TArray< FVector3f > & PositionalKeys, const TArray< FQuat4f > & RotationalKeys, const TArray< FVector3f > & ScalingKeys, bool bShouldTransact = true) pure virtual
Sets a range of keys for an existing bone animation track with the provided name.
Broadcasts a EAnimDataModelNotifyType::TrackChanged notify if successful. The provided number of keys provided is expected to match for each component, be between FrameLowerBound and FrameUpperBound (inclusive), and be non-zero.
Parameters
BoneName Bone name of the track for which the keys should be set
KeyRangeToSet Range of frames to set keys for
PositionalKeys Array of keys for the translation component
RotationalKeys Array of keys for the rotation component
ScalingKeys Array of keys for the scale component
bShouldTransact Whether or not any undo-redo changes should be generated
Returns
Whether or not the keys were successfully set
References bShouldTransact, PositionalKeys, RotationalKeys, ScalingKeys, and UpdateBoneTrackKeys().
Referenced by UpdateBoneTrackKeys(), and UpdateBoneTrackKeys().
UpdateWithSkeleton()
virtual void IAnimationDataController::UpdateWithSkeleton (USkeleton * TargetSkeleton, bool bShouldTransact = true) pure virtual
Updates/removes/remaps contained animation data according to the newly assigned skeleton.
Parameters
TargetSkeleton Skeleton to which the contained animation data is to be mapped
bShouldTransact Whether or not any undo-redo changes should be generated
References bShouldTransact, and UpdateWithSkeleton().
Referenced by UpdateWithSkeleton().
ValidateModel()
void IAnimationDataController::ValidateModel () const inline protected
Ensures that a valid model is currently targeted.
Definition at line 766 of file IAnimationDataController.h.
References checkf, GetModel(), and TEXT.
Referenced by CheckOuterClass(), and ConvertSecondsToFrameNumber().
Friends And Related Symbol Documentation
FAnimDataControllerTestBase
friend class FAnimDataControllerTestBase friend
Definition at line 863 of file IAnimationDataController.h.
References FAnimDataControllerTestBase.
Referenced by FAnimDataControllerTestBase.
Field Documentation
bShouldTransact [1/16]
float bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 113 of file IAnimationDataController.h.
Referenced by GENERATED_BODY(), ResetModel(), SetAttributeKey(), SetAttributeKeys(), SetBoneTrackKeys(), SetCurveAttributes(), SetTypedAttributeKey(), SetTypedAttributeKeys(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UpdateAttributesFromSkeleton(), UpdateBoneTrackKeys(), UpdateBoneTrackKeys(), and UpdateWithSkeleton().
bShouldTransact [2/16]
FFrameNumber FFrameNumber bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 147 of file IAnimationDataController.h.
bShouldTransact [3/16]
float float bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 151 of file IAnimationDataController.h.
bShouldTransact [4/16]
int32 bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 209 of file IAnimationDataController.h.
bShouldTransact [5/16]
const TArray<FVector> const TArray<FQuat> const TArray<FVector> bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 257 of file IAnimationDataController.h.
bShouldTransact [6/16]
const FAnimationCurveIdentifier bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 311 of file IAnimationDataController.h.
bShouldTransact [7/16]
EAnimAssetCurveFlags bool bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 345 of file IAnimationDataController.h.
bShouldTransact [8/16]
const TArray<FTransform> const TArray<float> bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 370 of file IAnimationDataController.h.
bShouldTransact [9/16]
float const FTransform bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 384 of file IAnimationDataController.h.
bShouldTransact [10/16]
float bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 396 of file IAnimationDataController.h.
bShouldTransact [11/16]
FLinearColor bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 421 of file IAnimationDataController.h.
bShouldTransact [12/16]
const FString bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 434 of file IAnimationDataController.h.
bShouldTransact [13/16]
const FRichCurveKey bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 460 of file IAnimationDataController.h.
bShouldTransact [14/16]
const TArray<FRichCurveKey> bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 484 of file IAnimationDataController.h.
bShouldTransact [15/16]
ERawCurveTrackTypes bool IAnimationDataController::bShouldTransact
Initial value:
= true) {}
    UE_DEPRECATED(5.3, "This function is no longer used.")
     UFUNCTION() )
    virtual void FindOrAddCurveNamesOnSkeleton(USkeleton* Skeleton, ERawCurveTrackTypes SupportedCurveType, bool bShouldTransact = true) {}
    virtual bool RemoveBoneTracksMissingFromSkeleton(const USkeleton* Skeleton, bool bShouldTransact = true) = 0
Definition at line 506 of file IAnimationDataController.h.
bShouldTransact [16/16]
const FAnimationAttributeIdentifier bool IAnimationDataController::bShouldTransact = true) = 0
Definition at line 683 of file IAnimationDataController.h.
bState
EAnimAssetCurveFlags bool IAnimationDataController::bState = true
Definition at line 345 of file IAnimationDataController.h.
ChangeTransactor
UE::FChangeTransactor IAnimationDataController::ChangeTransactor protected
Definition at line 839 of file IAnimationDataController.h.
Referenced by ConditionalAction(), and ConditionalTransaction().
Color
FLinearColor IAnimationDataController::Color
Definition at line 421 of file IAnimationDataController.h.
Comment
const FString& IAnimationDataController::Comment
Definition at line 434 of file IAnimationDataController.h.
CurveFlags
int32 IAnimationDataController::CurveFlags = 0x00000004
Definition at line 299 of file IAnimationDataController.h.
CurveKeys
const TArray<FRichCurveKey>& IAnimationDataController::CurveKeys
Definition at line 484 of file IAnimationDataController.h.
DefaultCurveFlags
int32 IAnimationDataController::DefaultCurveFlags = EAnimAssetCurveFlags::AACF_Editable static constexpr protected
Definition at line 810 of file IAnimationDataController.h.
DesiredIndex
int32 IAnimationDataController::DesiredIndex
Definition at line 209 of file IAnimationDataController.h.
Factor
float float IAnimationDataController::Factor
Definition at line 447 of file IAnimationDataController.h.
Flag
EAnimAssetCurveFlags IAnimationDataController::Flag
Definition at line 345 of file IAnimationDataController.h.
Flags
int32 IAnimationDataController::Flags
Definition at line 357 of file IAnimationDataController.h.
Key
const FRichCurveKey& IAnimationDataController::Key
Definition at line 460 of file IAnimationDataController.h.
NewAttributeIdentifier
const FAnimationAttributeIdentifier& IAnimationDataController::NewAttributeIdentifier
Definition at line 683 of file IAnimationDataController.h.
NewCurveId
const FAnimationCurveIdentifier & IAnimationDataController::NewCurveId
Definition at line 311 of file IAnimationDataController.h.
Referenced by UFUNCTION().
Origin
float IAnimationDataController::Origin
Definition at line 447 of file IAnimationDataController.h.
PositionalKeys
const TArray<FVector>& IAnimationDataController::PositionalKeys
Definition at line 257 of file IAnimationDataController.h.
Referenced by SetBoneTrackKeys(), UpdateBoneTrackKeys(), and UpdateBoneTrackKeys().
RotationalKeys
const TArray<FVector> const TArray<FQuat>& IAnimationDataController::RotationalKeys
Definition at line 257 of file IAnimationDataController.h.
Referenced by SetBoneTrackKeys(), UpdateBoneTrackKeys(), and UpdateBoneTrackKeys().
ScalingKeys
const TArray<FVector> const TArray<FQuat> const TArray<FVector>& IAnimationDataController::ScalingKeys
Definition at line 257 of file IAnimationDataController.h.
Referenced by SetBoneTrackKeys(), UpdateBoneTrackKeys(), and UpdateBoneTrackKeys().
SupportedCurveType
ERawCurveTrackTypes IAnimationDataController::SupportedCurveType
Definition at line 506 of file IAnimationDataController.h.
Referenced by UFUNCTION().
T0 [1/2]
float IAnimationDataController::T0
Definition at line 147 of file IAnimationDataController.h.
Referenced by UE_DEPRECATED(), and UFUNCTION().
T0 [2/2]
float IAnimationDataController::T0
Definition at line 151 of file IAnimationDataController.h.
T1 [1/2]
float float IAnimationDataController::T1
Definition at line 147 of file IAnimationDataController.h.
Referenced by UE_DEPRECATED(), and UFUNCTION().
T1 [2/2]
float float IAnimationDataController::T1
Definition at line 151 of file IAnimationDataController.h.
Time
float IAnimationDataController::Time
Definition at line 384 of file IAnimationDataController.h.
Referenced by SetAttributeKey(), SetTypedAttributeKey(), UFUNCTION(), and UFUNCTION().
TimeKeys
const TArray<FTransform> const TArray<float>& IAnimationDataController::TimeKeys
Definition at line 370 of file IAnimationDataController.h.
TransformValues
const TArray<FTransform>& IAnimationDataController::TransformValues
Definition at line 370 of file IAnimationDataController.h.
Value
float const FTransform& IAnimationDataController::Value
Definition at line 384 of file IAnimationDataController.h.
Referenced by SetTypedAttributeKeys().
The documentation for this class was generated from the following file:
IAnimationDataController.h