Unreal Engine 5.6 C++ API: TConcurrentLinearBulkObjectAllocator< BlockAllocationTag > Class Template Reference
TConcurrentLinearBulkObjectAllocator< BlockAllocationTag > Class Template Reference
#include "ConcurrentLinearAllocator.h"
Data Structures
struct FAllocation
struct TObject
struct TObjectArray
Public Member Functions
TConcurrentLinearBulkObjectAllocator ()=default
~TConcurrentLinearBulkObjectAllocator ()
void BulkDelete ()
template<typename T, typename... TArgs>
T * Create (TArgs &&... Args)
template<typename T, typename... TArgs>
T * CreateArray (SIZE_T Num, const TArgs &... Args)
template<typename T>
T * Malloc ()
void * Malloc (SIZE_T Size, uint32 Alignment)
void * MallocAndMemset (SIZE_T Size, uint32 Alignment, uint8 MemsetChar)
template<typename T>
T * MallocAndMemset (uint8 MemsetChar)
template<typename T>
T * MallocAndMemsetArray (SIZE_T Num, uint8 MemsetChar)
template<typename T>
T * MallocArray (SIZE_T Num)
Private Types
using ThisType = TConcurrentLinearBulkObjectAllocator<BlockAllocationTag>
Private Member Functions
template<typename T>
T * CreateArrayNoInit (SIZE_T Num)
template<typename T>
T * CreateNoInit ()
Private Attributes
std::atomic< FAllocation * > Next { nullptr }
Detailed Description
template<typename BlockAllocationTag>
class TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >
Definition at line 731 of file ConcurrentLinearAllocator.h.
Member Typedef Documentation
ThisType
template<typename BlockAllocationTag> using TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::ThisType = TConcurrentLinearBulkObjectAllocator<BlockAllocationTag> private
Definition at line 733 of file ConcurrentLinearAllocator.h.
Constructor & Destructor Documentation
TConcurrentLinearBulkObjectAllocator()
template<typename BlockAllocationTag> TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TConcurrentLinearBulkObjectAllocator () default
~TConcurrentLinearBulkObjectAllocator()
template<typename BlockAllocationTag> TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::~TConcurrentLinearBulkObjectAllocator () inline
Definition at line 782 of file ConcurrentLinearAllocator.h.
Member Function Documentation
BulkDelete()
template<typename BlockAllocationTag> void TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::BulkDelete () inline
Definition at line 787 of file ConcurrentLinearAllocator.h.
Referenced by TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::~TConcurrentLinearBulkObjectAllocator().
Create()
template<typename BlockAllocationTag> template<typename T, typename... TArgs> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::Create (TArgs &&... Args) inline
Definition at line 850 of file ConcurrentLinearAllocator.h.
CreateArray()
template<typename BlockAllocationTag> template<typename T, typename... TArgs> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::CreateArray (SIZE_T Num, const TArgs &... Args) inline
Definition at line 858 of file ConcurrentLinearAllocator.h.
CreateArrayNoInit()
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::CreateArrayNoInit (SIZE_T Num) inline private
Definition at line 887 of file ConcurrentLinearAllocator.h.
Referenced by TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::CreateArray().
CreateNoInit()
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::CreateNoInit () inline private
Definition at line 870 of file ConcurrentLinearAllocator.h.
Referenced by TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::Create().
Malloc() [1/2]
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::Malloc () inline
Definition at line 822 of file ConcurrentLinearAllocator.h.
Referenced by TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::Malloc(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemset(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemset(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemsetArray(), and TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocArray().
Malloc() [2/2]
template<typename BlockAllocationTag> void * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::Malloc (SIZE_T Size, uint32 Alignment) inline
Definition at line 799 of file ConcurrentLinearAllocator.h.
MallocAndMemset() [1/2]
template<typename BlockAllocationTag> void * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::MallocAndMemset (SIZE_T Size, uint32 Alignment, uint8 MemsetChar) inline
Definition at line 814 of file ConcurrentLinearAllocator.h.
MallocAndMemset() [2/2]
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::MallocAndMemset (uint8 MemsetChar) inline
Definition at line 828 of file ConcurrentLinearAllocator.h.
MallocAndMemsetArray()
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::MallocAndMemsetArray (SIZE_T Num, uint8 MemsetChar) inline
Definition at line 842 of file ConcurrentLinearAllocator.h.
MallocArray()
template<typename BlockAllocationTag> template<typename T> T * TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::MallocArray (SIZE_T Num) inline
Definition at line 836 of file ConcurrentLinearAllocator.h.
Field Documentation
Next
template<typename BlockAllocationTag> std::atomic<FAllocation*> TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::Next { nullptr } private
Definition at line 778 of file ConcurrentLinearAllocator.h.
The documentation for this class was generated from the following file:
ConcurrentLinearAllocator.h