Unreal Engine 5.6 C++ API: UE::Sequencer::FSortingKey Struct Reference
UE::Sequencer::FSortingKey Struct Reference
Structure for sorting models of various types together.
#include "ISortableExtension.h"
Public Member Functions
FSortingKey ()
FSortingKey & DeprioritizeBy (int8 InOffset)
FSortingKey & PrioritizeBy (int8 InOffset)
Static Public Member Functions
static bool CompareCustomOrderFirst (const FSortingKey &A, const FSortingKey &B)
Compare custom orders (if both set), priorities, and identifiers.
static bool ComparePriorityFirst (const FSortingKey &A, const FSortingKey &B)
Compare priorities, identifiers, and custom orders.
Data Fields
int32 CustomOrder = -1
Custom order, only relevant if >= 0.
FText DisplayName
Identifier.
int8 Priority = 0
Priority order.
Friends
bool operator== (const FSortingKey &A, const FSortingKey &B)
Detailed Description
Structure for sorting models of various types together.
Lower values have more precedence than higher values, i.e. items associated with lower values are ordered before items with higher values.
Definition at line 26 of file ISortableExtension.h.
Constructor & Destructor Documentation
FSortingKey()
UE::Sequencer::FSortingKey::FSortingKey () inline
Definition at line 35 of file ISortableExtension.h.
Referenced by CompareCustomOrderFirst(), ComparePriorityFirst(), DeprioritizeBy(), operator==, and PrioritizeBy().
Member Function Documentation
CompareCustomOrderFirst()
bool UE::Sequencer::FSortingKey::CompareCustomOrderFirst (const FSortingKey & A, const FSortingKey & B) static
Compare custom orders (if both set), priorities, and identifiers.
References FSortingKey(), A, and B.
ComparePriorityFirst()
bool UE::Sequencer::FSortingKey::ComparePriorityFirst (const FSortingKey & A, const FSortingKey & B) static
Compare priorities, identifiers, and custom orders.
References FSortingKey(), A, and B.
DeprioritizeBy()
FSortingKey & UE::Sequencer::FSortingKey::DeprioritizeBy (int8 InOffset) inline
Definition at line 44 of file ISortableExtension.h.
References FSortingKey(), and Priority.
PrioritizeBy()
FSortingKey & UE::Sequencer::FSortingKey::PrioritizeBy (int8 InOffset) inline
Definition at line 38 of file ISortableExtension.h.
References FSortingKey(), and Priority.
Friends And Related Symbol Documentation
operator==
bool operator== (const FSortingKey & A, const FSortingKey & B) friend
Definition at line 55 of file ISortableExtension.h.
References FSortingKey(), A, and B.
Field Documentation
CustomOrder
int32 UE::Sequencer::FSortingKey::CustomOrder = -1
Custom order, only relevant if >= 0.
Definition at line 33 of file ISortableExtension.h.
DisplayName
FText UE::Sequencer::FSortingKey::DisplayName
Identifier.
Definition at line 31 of file ISortableExtension.h.
Priority
int8 UE::Sequencer::FSortingKey::Priority = 0
Priority order.
Definition at line 29 of file ISortableExtension.h.
Referenced by DeprioritizeBy(), and PrioritizeBy().
The documentation for this struct was generated from the following file:
ISortableExtension.h