Unreal Engine 5.6 C++ API: TIntrusiveDoubleLinkedListNode< InElementType, ContainerType > Class Template Reference
TIntrusiveDoubleLinkedListNode< InElementType, ContainerType > Class Template Reference
Node of an intrusive double linked list Structs/classes must inherit this, to use it, e.g: struct FMyStruct : public TIntrusiveDoubleLinkedListNode<FMyStruct> TIntrusiveDoubleLinkedListNode can be inherited multiple times, ex: if ElementType needs to be stored in several lists at once by specifying a different ContainerType template parameter to distinguish the nodes.
#include "IntrusiveDoubleLinkedList.h"
Public Types
using ElementType = InElementType
using NodeType = TIntrusiveDoubleLinkedListNode<InElementType, ContainerType>
Public Member Functions
TIntrusiveDoubleLinkedListNode ()
FORCEINLINE ElementType * GetNext () const
FORCEINLINE ElementType * GetPrev () const
FORCEINLINE void InsertAfter (ElementType *NewPrev)
Insert this node after the specified node.
FORCEINLINE void InsertBefore (ElementType *NewNext)
Insert this node before the specified node.
FORCEINLINE bool IsInList () const
FORCEINLINE void Remove ()
Removes this element from the list in constant time.
FORCEINLINE void Reset ()
Protected Member Functions
FORCEINLINE ElementType * GetThisElement ()
FORCEINLINE const ElementType * GetThisElement () const
Protected Attributes
ElementType * Next
ElementType * Prev
Friends
class TIntrusiveDoubleLinkedList< ElementType, ContainerType >
class TIntrusiveDoubleLinkedListIterator< TIntrusiveDoubleLinkedListNode >
Detailed Description
template<class InElementType, class ContainerType = InElementType>
class TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >
Node of an intrusive double linked list Structs/classes must inherit this, to use it, e.g: struct FMyStruct : public TIntrusiveDoubleLinkedListNode<FMyStruct> TIntrusiveDoubleLinkedListNode can be inherited multiple times, ex: if ElementType needs to be stored in several lists at once by specifying a different ContainerType template parameter to distinguish the nodes.
Definition at line 24 of file IntrusiveDoubleLinkedList.h.
Member Typedef Documentation
ElementType
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::ElementType = InElementType
Definition at line 28 of file IntrusiveDoubleLinkedList.h.
NodeType
template<class InElementType, class ContainerType = InElementType> using TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::NodeType = TIntrusiveDoubleLinkedListNode<InElementType, ContainerType>
Definition at line 27 of file IntrusiveDoubleLinkedList.h.
Constructor & Destructor Documentation
TIntrusiveDoubleLinkedListNode()
template<class InElementType, class ContainerType = InElementType> TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::TIntrusiveDoubleLinkedListNode () inline nodiscard
Definition at line 30 of file IntrusiveDoubleLinkedList.h.
Member Function Documentation
GetNext()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::GetNext () const inline nodiscard
Definition at line 44 of file IntrusiveDoubleLinkedList.h.
GetPrev()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::GetPrev () const inline nodiscard
Definition at line 48 of file IntrusiveDoubleLinkedList.h.
GetThisElement() [1/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE ElementType * TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::GetThisElement () inline nodiscard protected
Definition at line 91 of file IntrusiveDoubleLinkedList.h.
Referenced by InsertAfter(), InsertBefore(), IsInList(), Remove(), and Reset().
GetThisElement() [2/2]
template<class InElementType, class ContainerType = InElementType> FORCEINLINE const ElementType * TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::GetThisElement () const inline nodiscard protected
Definition at line 92 of file IntrusiveDoubleLinkedList.h.
InsertAfter()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::InsertAfter (ElementType * NewPrev) inline
Insert this node after the specified node.
Definition at line 66 of file IntrusiveDoubleLinkedList.h.
InsertBefore()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::InsertBefore (ElementType * NewNext) inline
Insert this node before the specified node.
Definition at line 78 of file IntrusiveDoubleLinkedList.h.
IsInList()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE bool TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::IsInList () const inline nodiscard
Definition at line 40 of file IntrusiveDoubleLinkedList.h.
Remove()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::Remove () inline
Removes this element from the list in constant time.
Definition at line 56 of file IntrusiveDoubleLinkedList.h.
Reset()
template<class InElementType, class ContainerType = InElementType> FORCEINLINE void TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::Reset () inline
Definition at line 35 of file IntrusiveDoubleLinkedList.h.
Friends And Related Symbol Documentation
TIntrusiveDoubleLinkedList< ElementType, ContainerType >
template<class InElementType, class ContainerType = InElementType> friend class TIntrusiveDoubleLinkedList< ElementType, ContainerType > friend
Definition at line 78 of file IntrusiveDoubleLinkedList.h.
TIntrusiveDoubleLinkedListIterator< TIntrusiveDoubleLinkedListNode >
template<class InElementType, class ContainerType = InElementType> friend class TIntrusiveDoubleLinkedListIterator< TIntrusiveDoubleLinkedListNode > friend
Definition at line 78 of file IntrusiveDoubleLinkedList.h.
Field Documentation
Next
template<class InElementType, class ContainerType = InElementType> ElementType* TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::Next protected
Definition at line 94 of file IntrusiveDoubleLinkedList.h.
Prev
template<class InElementType, class ContainerType = InElementType> ElementType* TIntrusiveDoubleLinkedListNode< InElementType, ContainerType >::Prev protected
Definition at line 95 of file IntrusiveDoubleLinkedList.h.
The documentation for this class was generated from the following file:
IntrusiveDoubleLinkedList.h