Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyValueStorage< PropertyTraits > Struct Template Reference
UE::MovieScene::TPropertyValueStorage< PropertyTraits > Struct Template Reference
Templated storage for any initial value type, templated on the same parameter as TPropertyComponents for correct retrieval of resolved properties Initial values are stored as a sparse array, with stable indices that uniquely identify the value.
#include "MovieSceneInitialValueCache.h"
Data Structures
struct FKeyType
Public Types
using StorageType = typename PropertyTraits::StorageType
Public Member Functions
FInitialValueIndex AddInitialValue (UObject *BoundObject, const StorageType &InValue, const FName &PropertyPath)
Add a cached value for the specified object and a propertypath, returning a unique index for the value.
FInitialValueIndex AddInitialValue (UObject *BoundObject, const StorageType &InValue, FCustomPropertyIndex AccessorIndex)
Add a cached value for the specified object and a custom property accessor, returning a unique index for the value.
FInitialValueIndex AddInitialValue (UObject *BoundObject, const StorageType &InValue, FTrackInstancePropertyBindings *SlowBindings)
Add a cached value for the specified object and a slow bindings instance, returning a unique index for the value.
FInitialValueIndex AddInitialValue (UObject *BoundObject, const StorageType &InValue, uint16 ResolvedPropertyOffset)
Add a cached value for the specified object and fast property ptr offset, returning a unique index for the value.
const StorageType * FindCachedValue (UObject *BoundObject, const FName &PropertyPath)
Find an initial value given its object and property name.
const StorageType * FindCachedValue (UObject *BoundObject, FCustomPropertyIndex CustomIndex)
Find an initial value given its object and custom accessor index.
const StorageType * FindCachedValue (UObject *BoundObject, uint16 ResolvedPropertyOffset)
Find an initial value given its object and property name.
TOptional< FInitialValueIndex > FindPropertyIndex (UObject *BoundObject, const FName &PropertyPath)
Find an initial value index given its object and property name.
TOptional< FInitialValueIndex > FindPropertyIndex (UObject *BoundObject, FCustomPropertyIndex AccessorIndex)
Find an initial value index given its object and custom accessor index.
TOptional< FInitialValueIndex > FindPropertyIndex (UObject *BoundObject, uint16 ResolvedPropertyOffset)
Find an initial value index given its object and fast ptr offset.
const StorageType & GetCachedValue (FInitialValueIndex Index)
Find an initial value given its object and property name.
virtual void Reset (TArrayView< const FInitialValueIndex > Indices) override
Reset all the initial values that relate to the specified indices.
Public Member Functions inherited from UE::MovieScene::IPropertyValueStorage
virtual ~IPropertyValueStorage ()
Private Types
using FPropertyKey = TVariant<uint16, FCustomPropertyIndex, FName>
Private Member Functions
FInitialValueIndex AddInitialValue (const FKeyType &InKey, const StorageType &InValue)
FORCEINLINE void CleanupStaleEntries ()
TOptional< FInitialValueIndex > FindPropertyIndex (const FKeyType &InKey)
Private Attributes
bool bLUTContainsInvalidEntries = false
When true, KeyToPropertyIndex contains invalid entries which must be purged before use.
TMap< FKeyType, uint16 > KeyToPropertyIndex
LUT from object+property to its index.
TSparseArray< StorageType > PropertyValues
Sparse array containing all cached property values.
Detailed Description
template<typename PropertyTraits>
struct UE::MovieScene::TPropertyValueStorage< PropertyTraits >
Templated storage for any initial value type, templated on the same parameter as TPropertyComponents for correct retrieval of resolved properties Initial values are stored as a sparse array, with stable indices that uniquely identify the value.
A look-up-table exists for finding indices based on an object and resolved property.
Definition at line 165 of file MovieSceneInitialValueCache.h.
Member Typedef Documentation
FPropertyKey
template<typename PropertyTraits> using UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FPropertyKey = TVariant<uint16, FCustomPropertyIndex, FName> private
Definition at line 327 of file MovieSceneInitialValueCache.h.
StorageType
template<typename PropertyTraits> using UE::MovieScene::TPropertyValueStorage< PropertyTraits >::StorageType = typename PropertyTraits::StorageType
Definition at line 167 of file MovieSceneInitialValueCache.h.
Member Function Documentation
AddInitialValue() [1/5]
template<typename PropertyTraits> FInitialValueIndex UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue (const FKeyType & InKey, const StorageType & InValue) inline private
Definition at line 383 of file MovieSceneInitialValueCache.h.
References check, checkSlow, KeyToPropertyIndex, and PropertyValues.
AddInitialValue() [2/5]
template<typename PropertyTraits> FInitialValueIndex UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue (UObject * BoundObject, const StorageType & InValue, const FName & PropertyPath) inline
Add a cached value for the specified object and a propertypath, returning a unique index for the value.
Note
: Value must not have been cached previously - doing so will result in a failed assertion
Parameters
BoundObject The object instance to cache the property from.
InValue The value to cache
PropertyPath The path of the property
Returns
A tuple containing the cached value and its index
Definition at line 247 of file MovieSceneInitialValueCache.h.
References AddInitialValue(), and Key.
AddInitialValue() [3/5]
template<typename PropertyTraits> FInitialValueIndex UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue (UObject * BoundObject, const StorageType & InValue, FCustomPropertyIndex AccessorIndex) inline
Add a cached value for the specified object and a custom property accessor, returning a unique index for the value.
Note
: Value must not have been cached previously - doing so will result in a failed assertion
Parameters
BoundObject The object instance to cache the property from.
InValue The value to cache
AccessorIndex The index into ICustomPropertyRegistration::GetAccessors to use for resolving the property
Returns
A tuple containing the cached value and its index
Definition at line 213 of file MovieSceneInitialValueCache.h.
References AddInitialValue(), and Key.
AddInitialValue() [4/5]
template<typename PropertyTraits> FInitialValueIndex UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue (UObject * BoundObject, const StorageType & InValue, FTrackInstancePropertyBindings * SlowBindings) inline
Add a cached value for the specified object and a slow bindings instance, returning a unique index for the value.
Note
: Value must not have been cached previously - doing so will result in a failed assertion
Parameters
BoundObject The object instance to cache the property from.
InValue The value to cache
SlowBindings Pointer to the track instance property bindings object used for retrieving the property value
Returns
A tuple containing the cached value and its index
Definition at line 230 of file MovieSceneInitialValueCache.h.
References AddInitialValue(), FTrackInstancePropertyBindings::GetPropertyPath(), and Key.
AddInitialValue() [5/5]
template<typename PropertyTraits> FInitialValueIndex UE::MovieScene::TPropertyValueStorage< PropertyTraits >::AddInitialValue (UObject * BoundObject, const StorageType & InValue, uint16 ResolvedPropertyOffset) inline
Add a cached value for the specified object and fast property ptr offset, returning a unique index for the value.
Note
: Value must not have been cached previously - doing so will result in a failed assertion
Parameters
BoundObject The object instance to cache the property from
InValue The value to cache
ResolvedPropertyOffset The byte offset from BoundObject that defines the address of the property
Returns
A tuple containing the cached value and its index
Definition at line 196 of file MovieSceneInitialValueCache.h.
References AddInitialValue(), and Key.
Referenced by AddInitialValue(), AddInitialValue(), AddInitialValue(), and AddInitialValue().
CleanupStaleEntries()
template<typename PropertyTraits> FORCEINLINE void UE::MovieScene::TPropertyValueStorage< PropertyTraits >::CleanupStaleEntries () inline private
Definition at line 358 of file MovieSceneInitialValueCache.h.
References bLUTContainsInvalidEntries, FORCEINLINE, KeyToPropertyIndex, and PropertyValues.
Referenced by FindPropertyIndex(), FindPropertyIndex(), FindPropertyIndex(), and FindPropertyIndex().
FindCachedValue() [1/3]
template<typename PropertyTraits> const StorageType * UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindCachedValue (UObject * BoundObject, const FName & PropertyPath) inline
Find an initial value given its object and property name.
Note
: Only properties cached using a FTrackInstancePropertyBindings instance will be retrieved using this method.
Definition at line 310 of file MovieSceneInitialValueCache.h.
References FindPropertyIndex(), and PropertyValues.
FindCachedValue() [2/3]
template<typename PropertyTraits> const StorageType * UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindCachedValue (UObject * BoundObject, FCustomPropertyIndex CustomIndex) inline
Find an initial value given its object and custom accessor index.
Definition at line 299 of file MovieSceneInitialValueCache.h.
References FindPropertyIndex(), and PropertyValues.
FindCachedValue() [3/3]
template<typename PropertyTraits> const StorageType * UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindCachedValue (UObject * BoundObject, uint16 ResolvedPropertyOffset) inline
Find an initial value given its object and property name.
Definition at line 289 of file MovieSceneInitialValueCache.h.
References FindPropertyIndex(), and PropertyValues.
FindPropertyIndex() [1/4]
template<typename PropertyTraits> TOptional< FInitialValueIndex > UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindPropertyIndex (const FKeyType & InKey) inline private
Definition at line 375 of file MovieSceneInitialValueCache.h.
References CleanupStaleEntries(), and KeyToPropertyIndex.
FindPropertyIndex() [2/4]
template<typename PropertyTraits> TOptional< FInitialValueIndex > UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindPropertyIndex (UObject * BoundObject, const FName & PropertyPath) inline
Find an initial value index given its object and property name.
Note
: Only properties cached using a FTrackInstancePropertyBindings instance will be retrieved using this method.
Definition at line 279 of file MovieSceneInitialValueCache.h.
References CleanupStaleEntries(), and FindPropertyIndex().
FindPropertyIndex() [3/4]
template<typename PropertyTraits> TOptional< FInitialValueIndex > UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindPropertyIndex (UObject * BoundObject, FCustomPropertyIndex AccessorIndex) inline
Find an initial value index given its object and custom accessor index.
Definition at line 268 of file MovieSceneInitialValueCache.h.
References CleanupStaleEntries(), and FindPropertyIndex().
FindPropertyIndex() [4/4]
template<typename PropertyTraits> TOptional< FInitialValueIndex > UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FindPropertyIndex (UObject * BoundObject, uint16 ResolvedPropertyOffset) inline
Find an initial value index given its object and fast ptr offset.
Definition at line 258 of file MovieSceneInitialValueCache.h.
References CleanupStaleEntries(), and FindPropertyIndex().
Referenced by FindCachedValue(), FindCachedValue(), FindCachedValue(), FindPropertyIndex(), FindPropertyIndex(), and FindPropertyIndex().
GetCachedValue()
template<typename PropertyTraits> const StorageType & UE::MovieScene::TPropertyValueStorage< PropertyTraits >::GetCachedValue (FInitialValueIndex Index) inline
Find an initial value given its object and property name.
Note
: Only properties cached using a FTrackInstancePropertyBindings instance will be retrieved using this method.
Definition at line 320 of file MovieSceneInitialValueCache.h.
References PropertyValues.
Reset()
template<typename PropertyTraits> virtual void UE::MovieScene::TPropertyValueStorage< PropertyTraits >::Reset (TArrayView< const FInitialValueIndex > Indices) inline override virtual
Reset all the initial values that relate to the specified indices.
Parameters
Indices A array specifying all of the indices to remove. Such indices will be invalid after this function call returns.
Implements UE::MovieScene::IPropertyValueStorage.
Definition at line 174 of file MovieSceneInitialValueCache.h.
References bLUTContainsInvalidEntries, and PropertyValues.
Field Documentation
bLUTContainsInvalidEntries
template<typename PropertyTraits> bool UE::MovieScene::TPropertyValueStorage< PropertyTraits >::bLUTContainsInvalidEntries = false private
When true, KeyToPropertyIndex contains invalid entries which must be purged before use.
Definition at line 401 of file MovieSceneInitialValueCache.h.
Referenced by CleanupStaleEntries(), and Reset().
KeyToPropertyIndex
template<typename PropertyTraits> TMap<FKeyType, uint16> UE::MovieScene::TPropertyValueStorage< PropertyTraits >::KeyToPropertyIndex private
LUT from object+property to its index.
May contain stale values if bLUTContainsInvalidEntries is true
Definition at line 399 of file MovieSceneInitialValueCache.h.
Referenced by AddInitialValue(), CleanupStaleEntries(), and FindPropertyIndex().
PropertyValues
template<typename PropertyTraits> TSparseArray<StorageType> UE::MovieScene::TPropertyValueStorage< PropertyTraits >::PropertyValues private
Sparse array containing all cached property values.
Definition at line 397 of file MovieSceneInitialValueCache.h.
Referenced by AddInitialValue(), CleanupStaleEntries(), FindCachedValue(), FindCachedValue(), FindCachedValue(), GetCachedValue(), and Reset().
The documentation for this struct was generated from the following file:
MovieSceneInitialValueCache.h