Unreal Engine 5.6 C++ API: UE::Geometry::FMarchingCubes Class Reference
UE::Geometry::FMarchingCubes Class Reference
#include "MarchingCubes.h"
Data Structures
struct FGridCell
struct FIndexedVertex
Public Member Functions
FMarchingCubes ()
virtual ~FMarchingCubes ()
FMeshShapeGenerator & Generate () override
Run MC algorithm and generate Output mesh.
FMeshShapeGenerator & GenerateContinuation (TArrayView< const FVector3d > Seeds)
bool Validate ()
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Data Fields
bool bEnableValueCaching = true
If true, code will assume that Implicit() is expensive enough that it is worth it to cache evaluations when possible.
TAxisAlignedBox3< double > Bounds
bounding-box we will mesh inside of.
bool bParallelCompute = true
Use multi-threading?
TFunction< bool(void)> CancelF = []() { return false; }
if this function returns true, we should abort calculation
FVector3i CellDimensions
double CubeSize = 0.1
Length of edges of cubes that are marching.
TFunction< double(TVector< double >)> Implicit
this is the function we will evaluate
double IsoValue = 0
mesh surface will be at this isovalue.
ERootfindingModes RootMode = ERootfindingModes::SingleLerp
Which rootfinding method will be used to converge on surface along edges.
int RootModeSteps = 5
number of iterations of rootfinding method (ignored for SingleLerp)
int SafetyMaxDimension = 4096
Max number of cells on any dimension; if exceeded, CubeSize will be automatically increased to fix.
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Protected Member Functions
void append_triangle (int A, int B, int C, int64 CellHash)
add triangle to mesh, with locking if we are computing in parallel
int append_vertex (TVector< double > V, int64 CellHash)
add vertex to mesh, with locking if we are computing in parallel
int AppendOrFindVertexID (int64 hash, TVector< double > Pos)
void BuildMesh ()
Populate FMeshShapeGenerator data structures from accumulated vertex/triangle sets.
FVector3i cell_index (const TVector< double > &Pos)
int64 corner_hash (const FVector3i &Idx)
int64 corner_hash (int X, int Y, int Z)
TVector< double > corner_pos (const FVector3i &IJK)
void corner_pos (const FVector3i &IJK, TVector< double > &Pos)
double corner_value_grid (const FVector3i &Idx)
double corner_value_grid_parallel (const FVector3i &Idx)
double corner_value_nohash (const FVector3i &Idx)
int64 edge_hash (const FVector3i &Idx1, const FVector3i &Idx2)
int edge_vertex_id (const FVector3i &Idx1, const FVector3i &Idx2, double F1, double F2)
void find_iso (const TVector< double > &P1, const TVector< double > &P2, double ValP1, double ValP2, TVector< double > &PIso)
root-find the intersection along edge from f(P1)=ValP1 to f(P2)=ValP2
int FindVertexID (int64 hash)
void generate_basic ()
fully sequential version, no threading
void generate_continuation (TArrayView< const FVector3d > Seeds)
fully sequential version, no threading
void generate_continuation_parallel (TArrayView< const FVector3d > Seeds)
parallel seed evaluation
void generate_parallel ()
processing z-slabs of cells in parallel
int GetTriangleSectionIndex (int64 hash)
int GetVertexSectionIndex (int64 hash)
void InitHashTables ()
void initialize_cell (FGridCell &Cell, const FVector3i &Idx)
compute 3D corner-positions and field values for cell at index
void initialize_cell_values_grid (FGridCell &Cell, bool Shift)
void initialize_cell_values_nohash (FGridCell &Cell, bool Shift)
bool polygonize_cell (FGridCell &Cell, int VertIndexArray[])
find edge crossings and generate triangles for this cell
void ResetMesh ()
Reset internal mesh-assembly data structures.
bool set_cell_if_not_done (const FVector3i &Idx)
void SetDimensions ()
void shift_cell_x (FGridCell &Cell, int XIdx)
Protected Attributes
FBlockedDenseGrid3f BlockedCornerValuesGrid
FBlockedDenseGrid3i BlockedDoneCells
const int64 EDGE_X = int64(1) << 60
const int64 EDGE_Y = int64(1) << 61
const int64 EDGE_Z = int64(1) << 62
TArray< FCriticalSection > EdgeVertexSectionLocks
TArray< TMap< int64, int > > EdgeVertexSections
FAxisAlignedBox3i GridBounds
FAxisAlignedBox3i LastGridBounds
const int64 NumEdgeVertexSections = 64
int64 NumTriangleSections = 64
int64 NumVertexSections = 64
bool parallel_mesh_access = false
TArray< TArray< FIndex3i > > TriangleSectionLists
TArray< FCriticalSection > TriangleSectionLocks
std::atomic< int32 > VertexCounter
TArray< TArray< FIndexedVertex > > VertexSectionLists
TArray< FCriticalSection > VertexSectionLocks
Static Protected Attributes
static constexpr int EdgeIndices [12][2]
static constexpr int EdgeTable [256]
static constexpr int TriTable [256][16]
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Detailed Description
Definition at line 50 of file MarchingCubes.h.
Constructor & Destructor Documentation
FMarchingCubes()
UE::Geometry::FMarchingCubes::FMarchingCubes () inline
Definition at line 116 of file MarchingCubes.h.
References Bounds, CubeSize, and UE::Math::TVector< T >::Zero().
~FMarchingCubes()
virtual UE::Geometry::FMarchingCubes::~FMarchingCubes () inline virtual
Definition at line 122 of file MarchingCubes.h.
Member Function Documentation
append_triangle()
void UE::Geometry::FMarchingCubes::append_triangle (int A, int B, int C, int64 CellHash) inline protected
add triangle to mesh, with locking if we are computing in parallel
Definition at line 908 of file MarchingCubes.h.
References A, B, GetTriangleSectionIndex(), parallel_mesh_access, TriangleSectionLists, and TriangleSectionLocks.
Referenced by polygonize_cell().
append_vertex()
int UE::Geometry::FMarchingCubes::append_vertex (TVector< double > V, int64 CellHash) inline protected
add vertex to mesh, with locking if we are computing in parallel
Definition at line 878 of file MarchingCubes.h.
References GetVertexSectionIndex(), parallel_mesh_access, VertexCounter, VertexSectionLists, and VertexSectionLocks.
Referenced by AppendOrFindVertexID().
AppendOrFindVertexID()
int UE::Geometry::FMarchingCubes::AppendOrFindVertexID (int64 hash, TVector< double > Pos) inline protected
Definition at line 334 of file MarchingCubes.h.
References append_vertex(), EdgeVertexSectionLocks, EdgeVertexSections, and NumEdgeVertexSections.
Referenced by edge_vertex_id().
BuildMesh()
void UE::Geometry::FMarchingCubes::BuildMesh () inline protected
Populate FMeshShapeGenerator data structures from accumulated vertex/triangle sets.
Definition at line 942 of file MarchingCubes.h.
References UE::Geometry::FMeshShapeGenerator::AppendTriangle(), UE::Geometry::FMeshShapeGenerator::AppendVertex(), TRACE_CPUPROFILER_EVENT_SCOPE, TriangleList, TriangleSectionLists, VertexBuffer, VertexCounter, and VertexSectionLists.
Referenced by Generate(), and GenerateContinuation().
cell_index()
FVector3i UE::Geometry::FMarchingCubes::cell_index (const TVector< double > & Pos) inline protected
Definition at line 268 of file MarchingCubes.h.
References Bounds, CubeSize, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by generate_continuation(), and generate_continuation_parallel().
corner_hash() [1/2]
int64 UE::Geometry::FMarchingCubes::corner_hash (const FVector3i & Idx) inline protected
Definition at line 284 of file MarchingCubes.h.
References UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by edge_hash(), and polygonize_cell().
corner_hash() [2/2]
int64 UE::Geometry::FMarchingCubes::corner_hash (int X, int Y, int Z) inline protected
Definition at line 288 of file MarchingCubes.h.
References X, Y, and Z.
corner_pos() [1/2]
TVector< double > UE::Geometry::FMarchingCubes::corner_pos (const FVector3i & IJK) inline protected
Definition at line 262 of file MarchingCubes.h.
References Bounds, CubeSize, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
corner_pos() [2/2]
void UE::Geometry::FMarchingCubes::corner_pos (const FVector3i & IJK, TVector< double > & Pos) inline protected
Definition at line 256 of file MarchingCubes.h.
References Bounds, CubeSize, UE::Geometry::FVector3i::X, UE::Math::TVector< T >::X, UE::Geometry::FVector3i::Y, UE::Math::TVector< T >::Y, UE::Geometry::FVector3i::Z, and UE::Math::TVector< T >::Z.
Referenced by corner_value_grid(), corner_value_grid_parallel(), corner_value_nohash(), and edge_vertex_id().
corner_value_grid()
double UE::Geometry::FMarchingCubes::corner_value_grid (const FVector3i & Idx) inline protected
Definition at line 412 of file MarchingCubes.h.
References BlockedCornerValuesGrid, bParallelCompute, corner_pos(), corner_value_grid_parallel(), float, Implicit, TMathUtilConstants< float >::MaxReal, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by initialize_cell_values_grid().
corner_value_grid_parallel()
double UE::Geometry::FMarchingCubes::corner_value_grid_parallel (const FVector3i & Idx) inline protected
Definition at line 389 of file MarchingCubes.h.
References BlockedCornerValuesGrid, corner_pos(), float, Implicit, TMathUtilConstants< float >::MaxReal, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by corner_value_grid().
corner_value_nohash()
double UE::Geometry::FMarchingCubes::corner_value_nohash (const FVector3i & Idx) inline protected
Definition at line 458 of file MarchingCubes.h.
References corner_pos(), and Implicit.
Referenced by initialize_cell_values_nohash().
edge_hash()
int64 UE::Geometry::FMarchingCubes::edge_hash (const FVector3i & Idx1, const FVector3i & Idx2) inline protected
Definition at line 297 of file MarchingCubes.h.
References corner_hash(), EDGE_X, EDGE_Y, EDGE_Z, FMath::Min, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by edge_vertex_id().
edge_vertex_id()
int UE::Geometry::FMarchingCubes::edge_vertex_id (const FVector3i & Idx1, const FVector3i & Idx2, double F1, double F2) inline protected
Definition at line 349 of file MarchingCubes.h.
References AppendOrFindVertexID(), corner_pos(), edge_hash(), find_iso(), FindVertexID(), IndexConstants::InvalidID, and UE::Math::TVector< T >::Zero().
Referenced by polygonize_cell().
find_iso()
void UE::Geometry::FMarchingCubes::find_iso (const TVector< double > & P1, const TVector< double > & P2, double ValP1, double ValP2, TVector< double > & PIso) inline protected
root-find the intersection along edge from f(P1)=ValP1 to f(P2)=ValP2
Definition at line 975 of file MarchingCubes.h.
References UE::Geometry::Bisection, TMathUtil< double >::Clamp(), Implicit, IsoValue, Lerp, UE::Geometry::LerpSteps, RootMode, RootModeSteps, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by edge_vertex_id().
FindVertexID()
int UE::Geometry::FMarchingCubes::FindVertexID (int64 hash) inline protected
Definition at line 326 of file MarchingCubes.h.
References EdgeVertexSectionLocks, EdgeVertexSections, Found, IndexConstants::InvalidID, and NumEdgeVertexSections.
Referenced by edge_vertex_id().
Generate()
FMeshShapeGenerator & UE::Geometry::FMarchingCubes::Generate () inline override virtual
Run MC algorithm and generate Output mesh.
Implements UE::Geometry::FMeshShapeGenerator.
Definition at line 134 of file MarchingCubes.h.
References bEnableValueCaching, BlockedCornerValuesGrid, bParallelCompute, BuildMesh(), CellDimensions, ensure, generate_basic(), generate_parallel(), GridBounds, InitHashTables(), TMathUtilConstants< float >::MaxReal, ResetMesh(), SetDimensions(), TRACE_CPUPROFILER_EVENT_SCOPE, Validate(), and UE::Geometry::FVector3i::Zero().
generate_basic()
void UE::Geometry::FMarchingCubes::generate_basic () inline protected
fully sequential version, no threading
Definition at line 584 of file MarchingCubes.h.
References CancelF, Cell, CellDimensions, initialize_cell(), polygonize_cell(), and shift_cell_x().
Referenced by Generate().
generate_continuation()
void UE::Geometry::FMarchingCubes::generate_continuation (TArrayView< const FVector3d > Seeds) inline protected
fully sequential version, no threading
Definition at line 617 of file MarchingCubes.h.
References TArray< InElementType, InAllocatorType >::Add(), BlockedDoneCells, CancelF, Cell, cell_index(), CellDimensions, GridBounds, IndexUtil::GridOffsets6, initialize_cell(), TArray< InElementType, InAllocatorType >::Num(), polygonize_cell(), TArray< InElementType, InAllocatorType >::RemoveAt(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by GenerateContinuation().
generate_continuation_parallel()
void UE::Geometry::FMarchingCubes::generate_continuation_parallel (TArrayView< const FVector3d > Seeds) inline protected
parallel seed evaluation
Definition at line 668 of file MarchingCubes.h.
References TArray< InElementType, InAllocatorType >::Add(), BlockedDoneCells, cell_index(), TArray< InElementType, InAllocatorType >::Num(), parallel_mesh_access, ParallelFor(), Seed, and set_cell_if_not_done().
Referenced by GenerateContinuation().
generate_parallel()
void UE::Geometry::FMarchingCubes::generate_parallel () inline protected
processing z-slabs of cells in parallel
Definition at line 547 of file MarchingCubes.h.
References CellDimensions, parallel_mesh_access, and ParallelFor().
Referenced by Generate().
GenerateContinuation()
FMeshShapeGenerator & UE::Geometry::FMarchingCubes::GenerateContinuation (TArrayView< const FVector3d > Seeds) inline
Definition at line 169 of file MarchingCubes.h.
References bEnableValueCaching, BlockedCornerValuesGrid, BlockedDoneCells, bParallelCompute, BuildMesh(), CellDimensions, ensure, generate_continuation(), generate_continuation_parallel(), GridBounds, InitHashTables(), LastGridBounds, TMathUtilConstants< float >::MaxReal, ResetMesh(), SetDimensions(), TRACE_CPUPROFILER_EVENT_SCOPE, Validate(), and UE::Geometry::FVector3i::Zero().
GetTriangleSectionIndex()
int UE::Geometry::FMarchingCubes::GetTriangleSectionIndex (int64 hash) inline protected
Definition at line 900 of file MarchingCubes.h.
References NumTriangleSections.
Referenced by append_triangle().
GetVertexSectionIndex()
int UE::Geometry::FMarchingCubes::GetVertexSectionIndex (int64 hash) inline protected
Definition at line 870 of file MarchingCubes.h.
References NumVertexSections.
Referenced by append_vertex().
InitHashTables()
void UE::Geometry::FMarchingCubes::InitHashTables () inline protected
Definition at line 532 of file MarchingCubes.h.
References EdgeVertexSectionLocks, EdgeVertexSections, and NumEdgeVertexSections.
Referenced by Generate(), and GenerateContinuation().
initialize_cell()
void UE::Geometry::FMarchingCubes::initialize_cell (FGridCell & Cell, const FVector3i & Idx) inline protected
compute 3D corner-positions and field values for cell at index
Definition at line 486 of file MarchingCubes.h.
References bEnableValueCaching, Cell, initialize_cell_values_grid(), initialize_cell_values_nohash(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by generate_basic(), and generate_continuation().
initialize_cell_values_grid()
void UE::Geometry::FMarchingCubes::initialize_cell_values_grid (FGridCell & Cell, bool Shift) inline protected
Definition at line 433 of file MarchingCubes.h.
References Cell, and corner_value_grid().
Referenced by initialize_cell(), and shift_cell_x().
initialize_cell_values_nohash()
void UE::Geometry::FMarchingCubes::initialize_cell_values_nohash (FGridCell & Cell, bool Shift) inline protected
Definition at line 463 of file MarchingCubes.h.
References Cell, and corner_value_nohash().
Referenced by initialize_cell(), and shift_cell_x().
polygonize_cell()
bool UE::Geometry::FMarchingCubes::polygonize_cell (FGridCell & Cell, int VertIndexArray[]) inline protected
find edge crossings and generate triangles for this cell
Definition at line 795 of file MarchingCubes.h.
References append_triangle(), Cell, corner_hash(), edge_vertex_id(), EdgeIndices, EdgeTable, ensure, IsoValue, TriTable, and UE::Math::TVector< T >::Zero().
Referenced by generate_basic(), and generate_continuation().
ResetMesh()
void UE::Geometry::FMarchingCubes::ResetMesh () inline protected
Reset internal mesh-assembly data structures.
Definition at line 926 of file MarchingCubes.h.
References NumTriangleSections, NumVertexSections, TriangleSectionLists, TriangleSectionLocks, VertexCounter, VertexSectionLists, and VertexSectionLocks.
Referenced by Generate(), and GenerateContinuation().
set_cell_if_not_done()
bool UE::Geometry::FMarchingCubes::set_cell_if_not_done (const FVector3i & Idx) inline protected
Definition at line 772 of file MarchingCubes.h.
References BlockedDoneCells, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by generate_continuation_parallel().
SetDimensions()
void UE::Geometry::FMarchingCubes::SetDimensions () inline protected
Definition at line 240 of file MarchingCubes.h.
References Bounds, CellDimensions, CubeSize, ensure, FMath::Max3(), and SafetyMaxDimension.
Referenced by Generate(), and GenerateContinuation().
shift_cell_x()
void UE::Geometry::FMarchingCubes::shift_cell_x (FGridCell & Cell, int XIdx) inline protected
Definition at line 511 of file MarchingCubes.h.
References bEnableValueCaching, Cell, initialize_cell_values_grid(), and initialize_cell_values_nohash().
Referenced by generate_basic().
Validate()
bool UE::Geometry::FMarchingCubes::Validate () inline
Definition at line 126 of file MarchingCubes.h.
References Bounds, and CubeSize.
Referenced by Generate(), and GenerateContinuation().
Field Documentation
bEnableValueCaching
bool UE::Geometry::FMarchingCubes::bEnableValueCaching = true
If true, code will assume that Implicit() is expensive enough that it is worth it to cache evaluations when possible.
For something simple like evaluation of an SDF defined by a discrete grid, this is generally not worth the overhead.
Definition at line 87 of file MarchingCubes.h.
Referenced by Generate(), GenerateContinuation(), initialize_cell(), and shift_cell_x().
BlockedCornerValuesGrid
FBlockedDenseGrid3f UE::Geometry::FMarchingCubes::BlockedCornerValuesGrid protected
Definition at line 387 of file MarchingCubes.h.
Referenced by corner_value_grid(), corner_value_grid_parallel(), Generate(), and GenerateContinuation().
BlockedDoneCells
FBlockedDenseGrid3i UE::Geometry::FMarchingCubes::BlockedDoneCells protected
Definition at line 770 of file MarchingCubes.h.
Referenced by generate_continuation(), generate_continuation_parallel(), GenerateContinuation(), and set_cell_if_not_done().
Bounds
TAxisAlignedBox3<double> UE::Geometry::FMarchingCubes::Bounds
bounding-box we will mesh inside of.
We use the min-corner and the width/height/depth, but do not clamp vertices to stay within max-corner, we may spill one cell over
Definition at line 68 of file MarchingCubes.h.
Referenced by FMarchingCubes(), cell_index(), corner_pos(), corner_pos(), SetDimensions(), and Validate().
bParallelCompute
bool UE::Geometry::FMarchingCubes::bParallelCompute = true
Use multi-threading?
Generally a good idea unless problem is very small or you are multi-threading at a higher level (which may be more efficient)
Definition at line 80 of file MarchingCubes.h.
Referenced by corner_value_grid(), Generate(), and GenerateContinuation().
CancelF
TFunction<bool(void)> UE::Geometry::FMarchingCubes::CancelF = []() { return false; }
if this function returns true, we should abort calculation
Definition at line 106 of file MarchingCubes.h.
Referenced by generate_basic(), and generate_continuation().
CellDimensions
FVector3i UE::Geometry::FMarchingCubes::CellDimensions
Definition at line 113 of file MarchingCubes.h.
Referenced by Generate(), generate_basic(), generate_continuation(), generate_parallel(), GenerateContinuation(), and SetDimensions().
CubeSize
double UE::Geometry::FMarchingCubes::CubeSize = 0.1
Length of edges of cubes that are marching.
currently, # of cells along axis = (int)(bounds_dimension / CellSize) + 1
Definition at line 74 of file MarchingCubes.h.
Referenced by FMarchingCubes(), cell_index(), corner_pos(), corner_pos(), SetDimensions(), and Validate().
EDGE_X
const int64 UE::Geometry::FMarchingCubes::EDGE_X = int64(1) << 60 protected
Definition at line 293 of file MarchingCubes.h.
Referenced by edge_hash().
EDGE_Y
const int64 UE::Geometry::FMarchingCubes::EDGE_Y = int64(1) << 61 protected
Definition at line 294 of file MarchingCubes.h.
Referenced by edge_hash().
EDGE_Z
const int64 UE::Geometry::FMarchingCubes::EDGE_Z = int64(1) << 62 protected
Definition at line 295 of file MarchingCubes.h.
Referenced by edge_hash().
EdgeIndices
int UE::Geometry::FMarchingCubes::EdgeIndices[12][2] static constexpr protected
Initial value:
= {
        {0,1}, {1,2}, {2,3}, {3,0}, {4,5}, {5,6}, {6,7}, {7,4}, {0,4}, {1,5}, {2,6}, {3,7}
    }
Definition at line 1069 of file MarchingCubes.h.
Referenced by polygonize_cell().
EdgeTable
int UE::Geometry::FMarchingCubes::EdgeTable[256] static constexpr protected
Definition at line 1073 of file MarchingCubes.h.
Referenced by polygonize_cell().
EdgeVertexSectionLocks
TArray<FCriticalSection> UE::Geometry::FMarchingCubes::EdgeVertexSectionLocks protected
Definition at line 324 of file MarchingCubes.h.
Referenced by AppendOrFindVertexID(), FindVertexID(), and InitHashTables().
EdgeVertexSections
TArray<TMap<int64, int> > UE::Geometry::FMarchingCubes::EdgeVertexSections protected
Definition at line 323 of file MarchingCubes.h.
Referenced by AppendOrFindVertexID(), FindVertexID(), and InitHashTables().
GridBounds
FAxisAlignedBox3i UE::Geometry::FMarchingCubes::GridBounds protected
Definition at line 228 of file MarchingCubes.h.
Referenced by Generate(), generate_continuation(), and GenerateContinuation().
Implicit
TFunction<double(TVector<double>)> UE::Geometry::FMarchingCubes::Implicit
this is the function we will evaluate
Definition at line 56 of file MarchingCubes.h.
Referenced by corner_value_grid(), corner_value_grid_parallel(), corner_value_nohash(), and find_iso().
IsoValue
double UE::Geometry::FMarchingCubes::IsoValue = 0
mesh surface will be at this isovalue.
Normally 0 unless you want offset surface or field is not a distance-field.
Definition at line 62 of file MarchingCubes.h.
Referenced by find_iso(), and polygonize_cell().
LastGridBounds
FAxisAlignedBox3i UE::Geometry::FMarchingCubes::LastGridBounds protected
Definition at line 229 of file MarchingCubes.h.
Referenced by GenerateContinuation().
NumEdgeVertexSections
const int64 UE::Geometry::FMarchingCubes::NumEdgeVertexSections = 64 protected
Definition at line 322 of file MarchingCubes.h.
Referenced by AppendOrFindVertexID(), FindVertexID(), and InitHashTables().
NumTriangleSections
int64 UE::Geometry::FMarchingCubes::NumTriangleSections = 64 protected
Definition at line 897 of file MarchingCubes.h.
Referenced by GetTriangleSectionIndex(), and ResetMesh().
NumVertexSections
int64 UE::Geometry::FMarchingCubes::NumVertexSections = 64 protected
Definition at line 867 of file MarchingCubes.h.
Referenced by GetVertexSectionIndex(), and ResetMesh().
parallel_mesh_access
bool UE::Geometry::FMarchingCubes::parallel_mesh_access = false protected
Definition at line 541 of file MarchingCubes.h.
Referenced by append_triangle(), append_vertex(), generate_continuation_parallel(), and generate_parallel().
RootMode
ERootfindingModes UE::Geometry::FMarchingCubes::RootMode = ERootfindingModes::SingleLerp
Which rootfinding method will be used to converge on surface along edges.
Definition at line 97 of file MarchingCubes.h.
Referenced by find_iso().
RootModeSteps
int UE::Geometry::FMarchingCubes::RootModeSteps = 5
number of iterations of rootfinding method (ignored for SingleLerp)
Definition at line 102 of file MarchingCubes.h.
Referenced by find_iso().
SafetyMaxDimension
int UE::Geometry::FMarchingCubes::SafetyMaxDimension = 4096
Max number of cells on any dimension; if exceeded, CubeSize will be automatically increased to fix.
Definition at line 92 of file MarchingCubes.h.
Referenced by SetDimensions().
TriangleSectionLists
TArray<TArray<FIndex3i> > UE::Geometry::FMarchingCubes::TriangleSectionLists protected
Definition at line 899 of file MarchingCubes.h.
Referenced by append_triangle(), BuildMesh(), and ResetMesh().
TriangleSectionLocks
TArray<FCriticalSection> UE::Geometry::FMarchingCubes::TriangleSectionLocks protected
Definition at line 898 of file MarchingCubes.h.
Referenced by append_triangle(), and ResetMesh().
TriTable
int UE::Geometry::FMarchingCubes::TriTable[256][16] static constexpr protected
Definition at line 1108 of file MarchingCubes.h.
Referenced by polygonize_cell().
VertexCounter
std::atomic<int32> UE::Geometry::FMarchingCubes::VertexCounter protected
Definition at line 865 of file MarchingCubes.h.
Referenced by append_vertex(), BuildMesh(), and ResetMesh().
VertexSectionLists
TArray<TArray<FIndexedVertex> > UE::Geometry::FMarchingCubes::VertexSectionLists protected
Definition at line 869 of file MarchingCubes.h.
Referenced by append_vertex(), BuildMesh(), and ResetMesh().
VertexSectionLocks
TArray<FCriticalSection> UE::Geometry::FMarchingCubes::VertexSectionLocks protected
Definition at line 868 of file MarchingCubes.h.
Referenced by append_vertex(), and ResetMesh().
The documentation for this class was generated from the following file:
MarchingCubes.h