Unreal Engine 5.6 C++ API: MetasoundArrayHashPrivate Namespace Reference
MetasoundArrayHashPrivate Namespace Reference
Functions
template<typename ElementType>
FGuid GetArrayContentHashGuid (const TArray< ElementType > &InArray)
Function Documentation
GetArrayContentHashGuid()
template<typename ElementType> FGuid MetasoundArrayHashPrivate::GetArrayContentHashGuid (const TArray< ElementType > & InArray)
Definition at line 24 of file MetasoundArrayRandomNode.h.
References A, B, Metasound::GetMetasoundDataTypeName(), Metasound::GetMetasoundDataTypeString(), GetTypeHash(), HashCombineFast(), TArray< InElementType, InAllocatorType >::Num(), TEXT, TModels_V, UE_LOG, and Warning.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext(), and Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset().