Unreal Engine 5.6 C++ API: FPropertySoftPath Struct Reference
FPropertySoftPath Struct Reference
FPropertySoftPath is a string of identifiers used to identify a single member of a UObject.
#include "DiffUtils.h"
Data Structures
struct FChainElement
Public Member Functions
UNREALED_API FPropertySoftPath ()
UNREALED_API FPropertySoftPath (const FProperty *Property)
UNREALED_API FPropertySoftPath (const FPropertySoftPath &MainPropertyPath, const FPropertySoftPath &SubPropertyPath)
UNREALED_API FPropertySoftPath (const FPropertySoftPath &SubPropertyPath, const FProperty *LeafProperty)
UNREALED_API FPropertySoftPath (const FPropertySoftPath &SubPropertyPath, int32 ContainerIndex)
UNREALED_API FPropertySoftPath (FPropertyPath InPropertyPath)
UNREALED_API FPropertySoftPath (TArray< FName > InPropertyChain)
UNREALED_API FPropertySoftPath GetRootProperty (int32 Depth) const
bool IsSubPropertyMatch (const FName PotentialBasePropertyName) const
Indicates whether a given property name is a base path of the current path.
bool IsSubPropertyMatch (const FPropertySoftPath &PotentialBasePropertyPath) const
Indicates whether a given path is a base path of the current path.
bool IsSubPropertyMatch (TConstArrayView< FName > PotentialBasePropertyNameArray) const
Indicates whether a given list of property names is a base path of the current path.
bool operator!= (FPropertySoftPath const &RHS) const
FPropertySoftPath & operator+= (FPropertySoftPath const &RHS)
bool operator== (FPropertySoftPath const &RHS) const
UNREALED_API FResolvedProperty Resolve (const UObject *Object) const
UNREALED_API FResolvedProperty Resolve (const UStruct *Struct, const void *StructData) const
UNREALED_API FPropertyPath ResolvePath (const UObject *Object) const
UNREALED_API FString ToDisplayName (const int32 NumberOfElements=INDEX_NONE) const
Provides a string of all elements in the property chain using the following format e.g., "X[3] Y Z".
UNREALED_API int32 TryReadIndex (int32 Index) const
Static Private Member Functions
static int32 TryReadIndex (const TArray< FChainElement > &LocalPropertyChain, int32 &OutIndex)
Private Attributes
TArray< FChainElement > PropertyChain
const UStruct * RootTypeHint
Friends
uint32 GetTypeHash (FPropertySoftPath const &Path)
Detailed Description
FPropertySoftPath is a string of identifiers used to identify a single member of a UObject.
It is primarily used when comparing unrelated UObjects for Diffing and Merging, but can also be used as a key select a property in a SDetailsView.
Definition at line 67 of file DiffUtils.h.
Constructor & Destructor Documentation
FPropertySoftPath() [1/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath ()
Referenced by FPropertySoftPath(), FPropertySoftPath(), FPropertySoftPath(), GetRootProperty(), GetTypeHash, IsSubPropertyMatch(), operator!=(), operator+=(), operator==(), and TryReadIndex().
FPropertySoftPath() [2/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (const FProperty * Property)
References Property.
FPropertySoftPath() [3/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (TArray< FName > InPropertyChain)
FPropertySoftPath() [4/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (FPropertyPath InPropertyPath)
FPropertySoftPath() [5/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (const FPropertySoftPath & MainPropertyPath, const FPropertySoftPath & SubPropertyPath)
References FPropertySoftPath().
FPropertySoftPath() [6/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (const FPropertySoftPath & SubPropertyPath, const FProperty * LeafProperty)
References FPropertySoftPath().
FPropertySoftPath() [7/7]
UNREALED_API FPropertySoftPath::FPropertySoftPath (const FPropertySoftPath & SubPropertyPath, int32 ContainerIndex)
References FPropertySoftPath(), and ContainerIndex.
Member Function Documentation
GetRootProperty()
UNREALED_API FPropertySoftPath FPropertySoftPath::GetRootProperty (int32 Depth) const
References FPropertySoftPath(), and Depth.
IsSubPropertyMatch() [1/3]
bool FPropertySoftPath::IsSubPropertyMatch (const FName PotentialBasePropertyName) const inline
Indicates whether a given property name is a base path of the current path.
Parameters
PotentialBasePropertyName Name of the single property to match
Returns
Whether the path contains a single element with the name provided or not
Definition at line 143 of file DiffUtils.h.
References IsSubPropertyMatch(), and MakeArrayView().
IsSubPropertyMatch() [2/3]
bool FPropertySoftPath::IsSubPropertyMatch (const FPropertySoftPath & PotentialBasePropertyPath) const inline
Indicates whether a given path is a base path of the current path.
Parameters
PotentialBasePropertyPath The path to look for as a base common path
Returns
Whether the path has the provided path as base path or not
Definition at line 97 of file DiffUtils.h.
References FPropertySoftPath(), and PropertyChain.
Referenced by IsSubPropertyMatch().
IsSubPropertyMatch() [3/3]
bool FPropertySoftPath::IsSubPropertyMatch (TConstArrayView< FName > PotentialBasePropertyNameArray) const inline
Indicates whether a given list of property names is a base path of the current path.
Parameters
PotentialBasePropertyNameArray The list of property names to look for as a base common path
Returns
Whether the path has the provided list of names as base path or not
Definition at line 120 of file DiffUtils.h.
References PropertyChain, and PropertyName.
operator!=()
bool FPropertySoftPath::operator!= (FPropertySoftPath const & RHS) const inline
Definition at line 153 of file DiffUtils.h.
References FPropertySoftPath().
operator+=()
FPropertySoftPath & FPropertySoftPath::operator+= (FPropertySoftPath const & RHS) inline
Definition at line 158 of file DiffUtils.h.
References FPropertySoftPath(), and PropertyChain.
operator==()
bool FPropertySoftPath::operator== (FPropertySoftPath const & RHS) const inline
Definition at line 148 of file DiffUtils.h.
References FPropertySoftPath(), and PropertyChain.
Resolve() [1/2]
UNREALED_API FResolvedProperty FPropertySoftPath::Resolve (const UObject * Object) const
References Object.
Resolve() [2/2]
UNREALED_API FResolvedProperty FPropertySoftPath::Resolve (const UStruct * Struct, const void * StructData) const
References Struct.
ResolvePath()
UNREALED_API FPropertyPath FPropertySoftPath::ResolvePath (const UObject * Object) const
References Object.
ToDisplayName()
UNREALED_API FString FPropertySoftPath::ToDisplayName (const int32 NumberOfElements = INDEX_NONE) const
Provides a string of all elements in the property chain using the following format e.g., "X[3] Y Z".
Parameters
NumberOfElements Optional argument to return a string containing only the last 'NumberOfElements' elements of the path
Returns
String of all elements in the property chain
References INDEX_NONE.
TryReadIndex() [1/2]
int32 FPropertySoftPath::TryReadIndex (const TArray< FChainElement > & LocalPropertyChain, int32 & OutIndex) static private
References FPropertySoftPath(), and Path.
TryReadIndex() [2/2]
UNREALED_API int32 FPropertySoftPath::TryReadIndex (int32 Index) const
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FPropertySoftPath const & Path) friend
Definition at line 231 of file DiffUtils.h.
References FPropertySoftPath(), FORCEINLINE, GetTypeHash(), Path, and FPropertySoftPath::FChainElement::PropertyName.
Field Documentation
PropertyChain
TArray<FChainElement> FPropertySoftPath::PropertyChain private
Definition at line 205 of file DiffUtils.h.
Referenced by IsSubPropertyMatch(), IsSubPropertyMatch(), operator+=(), and operator==().
RootTypeHint
const UStruct* FPropertySoftPath::RootTypeHint private
Definition at line 206 of file DiffUtils.h.
The documentation for this struct was generated from the following file:
DiffUtils.h