Unreal Engine 5.6 C++ API: FAnimationCompression_PerTrackUtils Class Reference
FAnimationCompression_PerTrackUtils Class Reference
This class contains helper methods for dealing with animations compressed with the per-track codec.
#include "AnimationCompression.h"
Static Public Member Functions
static uint16 CompressFixed16 (float Value, int32 Log2MaxValue=0)
Compresses a float into a signed fixed point number, which can range from the symmetrical values of -2^Log2MaxValue .
static FORCEINLINE void DecomposeHeader (int32 Header, int32 &KeyFormat, int32 &NumKeys, int32 &FormatFlags)
Decomposes a header created with MakeHeader into three/four fields (two are still left packed into FormatFlags):
static FORCEINLINE void DecomposeHeader (int32 Header, int32 &KeyFormat, int32 &NumKeys, int32 &FormatFlags, int32 &BytesPerKey, int32 &FixedBytes)
Decomposes a header created with MakeHeader into three/four fields (two are still left packed into FormatFlags):
template<int32 Log2MaxValue>
static float DecompressFixed16 (uint16 Value)
Decompresses a fixed point number encoded by ComrpessFixed16.
template<>
float DecompressFixed16 (uint16 Value)
template<bool bIsDataAligned = true>
static FORCEINLINE_DEBUGGABLE void DecompressRotation (int32 Format, int32 FormatFlags, FQuat4f &Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData)
Decompress a single rotation key from a single track that was compressed with the PerTrack codec (scalar)
template<bool bIsDataAligned = true>
static FORCEINLINE_DEBUGGABLE void DecompressScale (int32 Format, int32 FormatFlags, FVector3f &Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData)
Decompress a single Scale key from a single track that was compressed with the PerTrack codec (scalar)
template<bool bIsDataAligned = true>
static FORCEINLINE_DEBUGGABLE void DecompressTranslation (int32 Format, int32 FormatFlags, FVector3f &Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData)
Decompress a single translation key from a single track that was compressed with the PerTrack codec (scalar)
static void GetAllSizesFromFormat (int32 KeyFormat, int32 FormatFlags, int32 &KeyComponentCount, int32 &KeyComponentSize, int32 &FixedComponentCount, int32 &FixedComponentSize)
Figures out the size of various parts of a compressed track from the format and format flags combo.
static FORCEINLINE void GetByteSizesFromFormat (int32 KeyFormat, int32 FormatFlags, int32 &BytesPerKey, int32 &FixedBytes)
static int32 GetKeyCountFromHeader (int32 Header)
Extracts the number of keys from a header created by MakeHeader.
static int32 MakeHeader (const int32 NumKeys, const int32 KeyFormat, const int32 KeyFlags, bool bReallyNeedsFrameTable)
Creates a header integer with four fields: NumKeys can be no more than 24 bits (positions 0..23) KeyFlags can be no more than 3 bits (positions 24..27) bReallyNeedsFrameTable is a single bit (position 27) KeyFormat can be no more than 4 bits (positions 31..28)
Detailed Description
This class contains helper methods for dealing with animations compressed with the per-track codec.
Definition at line 692 of file AnimationCompression.h.
Member Function Documentation
CompressFixed16()
uint16 FAnimationCompression_PerTrackUtils::CompressFixed16 (float Value, int32 Log2MaxValue = 0) inline static
Compresses a float into a signed fixed point number, which can range from the symmetrical values of -2^Log2MaxValue .
. 2^Log2MaxValue. No clamping is done, values that don't fit will overflow.
For example, a Log2MaxValue of 0 can encode -1..1, and 7 can encode -128..128.
Parameters
Value Value to encode
Log2MaxValue Encoding range (can be 0..15)
Returns
The quantized value
Definition at line 709 of file AnimationCompression.h.
References float, and Value.
DecomposeHeader() [1/2]
FORCEINLINE void FAnimationCompression_PerTrackUtils::DecomposeHeader (int32 Header, int32 & KeyFormat, int32 & NumKeys, int32 & FormatFlags) inline static
Decomposes a header created with MakeHeader into three/four fields (two are still left packed into FormatFlags):
Parameters
Header The header to decompose
KeyFormat [OUT] The encoding format used for each key
NumKeys [OUT] The number of keys in this track
FormatFlags [OUT] Three bits of format-specific information and a single bit to indicate if a key->frame table follows the keys
Definition at line 809 of file AnimationCompression.h.
References FORCEINLINE, and Header.
DecomposeHeader() [2/2]
FORCEINLINE void FAnimationCompression_PerTrackUtils::DecomposeHeader (int32 Header, int32 & KeyFormat, int32 & NumKeys, int32 & FormatFlags, int32 & BytesPerKey, int32 & FixedBytes) inline static
Decomposes a header created with MakeHeader into three/four fields (two are still left packed into FormatFlags):
Parameters
Header The header to decompose
KeyFormat [OUT] The encoding format used for each key
NumKeys [OUT] The number of keys in this track
FormatFlags [OUT] Three bits of format-specific information and a single bit to indicate if a key->frame table follows the keys
And some derived values:
Parameters
BytesPerKey [OUT] The number of bytes each key takes up
FixedBytes [OUT] The number of fixed bytes at the head of the track stream
Definition at line 827 of file AnimationCompression.h.
References FORCEINLINE, GetByteSizesFromFormat(), and Header.
DecompressFixed16() [1/2]
template<int32 Log2MaxValue> float FAnimationCompression_PerTrackUtils::DecompressFixed16 (uint16 Value) inline static
Decompresses a fixed point number encoded by ComrpessFixed16.
Parameters
Value Value to decode
Log2MaxValue Encoding range (can be 0..15)
Returns
The decompressed value
Definition at line 725 of file AnimationCompression.h.
References float, and Value.
Referenced by DecompressScale(), and DecompressTranslation().
DecompressFixed16() [2/2]
template<> float FAnimationCompression_PerTrackUtils::DecompressFixed16 (uint16 Value) inline static
Definition at line 1132 of file AnimationCompression.h.
References Value.
DecompressRotation()
template<bool bIsDataAligned = true> FORCEINLINE_DEBUGGABLE void FAnimationCompression_PerTrackUtils::DecompressRotation (int32 Format, int32 FormatFlags, FQuat4f & Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData) inline static
Decompress a single rotation key from a single track that was compressed with the PerTrack codec (scalar)
Definition at line 949 of file AnimationCompression.h.
References Fatal, FORCEINLINE_DEBUGGABLE, Format, UE::Math::TQuat< float >::Identity, RESTRICT, TEXT, FQuatFixed32NoW::ToQuat(), FQuatFloat32NoW::ToQuat(), FQuatFloat96NoW::ToQuat(), FQuatIntervalFixed32NoW::ToQuat(), UE_LOG, AnimationCompressionUtils::UnalignedRead(), X, Y, and Z.
DecompressScale()
template<bool bIsDataAligned = true> FORCEINLINE_DEBUGGABLE void FAnimationCompression_PerTrackUtils::DecompressScale (int32 Format, int32 FormatFlags, FVector3f & Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData) inline static
Decompress a single Scale key from a single track that was compressed with the PerTrack codec (scalar)
Definition at line 1022 of file AnimationCompression.h.
References DecompressFixed16(), Fatal, FORCEINLINE_DEBUGGABLE, Format, RESTRICT, TEXT, FVectorIntervalFixed32NoW::ToVector(), UE_LOG, AnimationCompressionUtils::UnalignedRead(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and UE::Math::TVector< float >::ZeroVector.
DecompressTranslation()
template<bool bIsDataAligned = true> FORCEINLINE_DEBUGGABLE void FAnimationCompression_PerTrackUtils::DecompressTranslation (int32 Format, int32 FormatFlags, FVector3f & Out, const uint8 *RESTRICT TopOfStream, const uint8 *RESTRICT KeyData) inline static
Decompress a single translation key from a single track that was compressed with the PerTrack codec (scalar)
Definition at line 839 of file AnimationCompression.h.
References DecompressFixed16(), Fatal, FORCEINLINE_DEBUGGABLE, Format, RESTRICT, TEXT, FVectorIntervalFixed32NoW::ToVector(), UE_LOG, AnimationCompressionUtils::UnalignedRead(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and UE::Math::TVector< float >::ZeroVector.
GetAllSizesFromFormat()
void FAnimationCompression_PerTrackUtils::GetAllSizesFromFormat (int32 KeyFormat, int32 FormatFlags, int32 & KeyComponentCount, int32 & KeyComponentSize, int32 & FixedComponentCount, int32 & FixedComponentSize) inline static
Figures out the size of various parts of a compressed track from the format and format flags combo.
Parameters
KeyFormat The encoding format used for each key
FormatFlags Three bits of format-specific information and a single bit to indicate if a key->frame table follows the keys
Definition at line 762 of file AnimationCompression.h.
References CompressedRotationStrides, float, and PerTrackNumComponentTable.
Referenced by GetByteSizesFromFormat().
GetByteSizesFromFormat()
FORCEINLINE void FAnimationCompression_PerTrackUtils::GetByteSizesFromFormat (int32 KeyFormat, int32 FormatFlags, int32 & BytesPerKey, int32 & FixedBytes) inline static
Definition at line 789 of file AnimationCompression.h.
References FORCEINLINE, and GetAllSizesFromFormat().
Referenced by DecomposeHeader().
GetKeyCountFromHeader()
int32 FAnimationCompression_PerTrackUtils::GetKeyCountFromHeader (int32 Header) inline static
Extracts the number of keys from a header created by MakeHeader.
Parameters
Header Header to extract the number of keys from
Returns
The number of keys encoded in the header
Definition at line 751 of file AnimationCompression.h.
References Header.
MakeHeader()
int32 FAnimationCompression_PerTrackUtils::MakeHeader (const int32 NumKeys, const int32 KeyFormat, const int32 KeyFlags, bool bReallyNeedsFrameTable) inline static
Creates a header integer with four fields: NumKeys can be no more than 24 bits (positions 0..23) KeyFlags can be no more than 3 bits (positions 24..27) bReallyNeedsFrameTable is a single bit (position 27) KeyFormat can be no more than 4 bits (positions 31..28)
Definition at line 740 of file AnimationCompression.h.
The documentation for this class was generated from the following file:
AnimationCompression.h