Unreal Engine 5.6 C++ API: UE::Geometry::FAffineKelvinlet Class Reference
UE::Geometry::FAffineKelvinlet Class Reference
#include "Kelvinlets.h"
Public Types
typedef TBaseKelvinlet< FAffineKelvinlet > MyBase
Public Member Functions
FAffineKelvinlet (const FMatrix3d &ForceMatrix, const double Size, const double ShearModulus, const double PoissonRatio)
FVector3d Evaluate (const FVector3d &Pos) const
void UpdateForce (const FMatrix3d &NF)
Public Member Functions inherited from UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >
TBaseKelvinlet (const double Size, const double ShearModulus, const double PoissonRatio)
void SetMaterialParameters (const double ShearModulus, const double PoissonRatio)
void UpdateRegularization (const double R)
Public Member Functions inherited from UE::Geometry::TKelvinletIntegrator< KelvinletModelType >
FVector3d Evaluate (const FVector3d &Pos) const
FVector3d IntegrateRK3 (const FVector3d &Pos, double dt) const
Protected Attributes
double E2
FMatrix3d F
FMatrix3d SymF
Protected Attributes inherited from UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >
double a
double bhat
double E
Detailed Description
Definition at line 399 of file Kelvinlets.h.
Member Typedef Documentation
MyBase
typedef TBaseKelvinlet< FAffineKelvinlet> UE::Geometry::FAffineKelvinlet::MyBase
Definition at line 402 of file Kelvinlets.h.
Constructor & Destructor Documentation
FAffineKelvinlet()
UE::Geometry::FAffineKelvinlet::FAffineKelvinlet (const FMatrix3d & ForceMatrix, const double Size, const double ShearModulus, const double PoissonRatio) inline
Definition at line 404 of file Kelvinlets.h.
References UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >::E, E2, F, UE::Geometry::TMatrix3< double >::Identity(), SymF, and TSequenceHistory< HistorySize >::Size.
Member Function Documentation
Evaluate()
FVector3d UE::Geometry::FAffineKelvinlet::Evaluate (const FVector3d & Pos) const inline
Definition at line 418 of file Kelvinlets.h.
References UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >::a, UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >::bhat, UE::Math::TVector< T >::Dot(), UE::Geometry::TBaseKelvinlet< FAffineKelvinlet >::E, E2, F, UE::Math::TVector< T >::SquaredLength(), and SymF.
UpdateForce()
void UE::Geometry::FAffineKelvinlet::UpdateForce (const FMatrix3d & NF) inline
Definition at line 412 of file Kelvinlets.h.
References F, UE::Geometry::TMatrix3< double >::Identity(), and SymF.
Field Documentation
E2
double UE::Geometry::FAffineKelvinlet::E2 protected
Definition at line 450 of file Kelvinlets.h.
Referenced by FAffineKelvinlet(), and Evaluate().
F
FMatrix3d UE::Geometry::FAffineKelvinlet::F protected
Definition at line 445 of file Kelvinlets.h.
Referenced by FAffineKelvinlet(), Evaluate(), and UpdateForce().
SymF
FMatrix3d UE::Geometry::FAffineKelvinlet::SymF protected
Definition at line 448 of file Kelvinlets.h.
Referenced by FAffineKelvinlet(), Evaluate(), and UpdateForce().
The documentation for this class was generated from the following file:
Kelvinlets.h