Unreal Engine 5.6 C++ API: UE::Geometry::TConvexHull2< RealType > Class Template Reference
UE::Geometry::TConvexHull2< RealType > Class Template Reference
#include "ConvexHull2.h"
Public Member Functions
void Empty ()
Empty any previously-computed convex hull data.
int32 GetDimension () const
TLine2< RealType > GetLine (TArrayView< const TVector2< RealType > > Points) const
int32 GetNumUniquePoints () const
Number of unique points considered by convex hull construction (excludes exact duplicate points and filtered-out points)
TArray< int32 > const & GetPolygonIndices () const
bool IsSolutionAvailable () const
GEOMETRYCORE_API bool Solve (int32 NumPoints, TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc=[](int32 Idx) {return true;})
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
bool Solve (TArrayView< const TVector2< RealType > > Points)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
bool Solve (TArrayView< const TVector2< RealType > > Points, TFunctionRef< bool(int32)> FilterFunc)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
GEOMETRYCORE_API bool SolveSimplePolygon (int32 NumPolygonPoints, TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, bool bIsKnownCCW=false)
Generate convex hull for a simple polygon If input has fewer than 3 points, will return false If input is not a simple polygon (e.g.
Protected Member Functions
void GetHull (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > &Merged, int32 &IdxFirst, int32 &IdxLast)
void GetTangent (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > &Merged, int32 j0, int32 j1, int32 j2, int32 j3, int32 &i0, int32 &i1)
void Merge (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > &Merged, int32 j0, int32 j1, int32 j2, int32 j3, int32 &i0, int32 &i1)
Protected Attributes
int32 Dimension = 0
TArray< int32 > Hull
int32 NumUniquePoints = 0
Detailed Description
template<typename RealType>
class UE::Geometry::TConvexHull2< RealType >
Definition at line 28 of file ConvexHull2.h.
Member Function Documentation
Empty()
template<typename RealType> void UE::Geometry::TConvexHull2< RealType >::Empty () inline
Empty any previously-computed convex hull data.
Frees the hull memory. Note: You do not need to call this before calling Solve() with new data.
Definition at line 100 of file ConvexHull2.h.
GetDimension()
template<typename RealType> int32 UE::Geometry::TConvexHull2< RealType >::GetDimension () const inline
Returns
Number of dimensions spanned by the input points.
Definition at line 108 of file ConvexHull2.h.
GetHull()
template<typename RealType> void UE::Geometry::TConvexHull2< RealType >::GetHull (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > & Merged, int32 & IdxFirst, int32 & IdxLast) protected
GetLine()
template<typename RealType> TLine2< RealType > UE::Geometry::TConvexHull2< RealType >::GetLine (TArrayView< const TVector2< RealType > > Points) const inline
Returns
the line spanned by a collinear input. Only meaningful if GetDimension() == 1
Definition at line 127 of file ConvexHull2.h.
GetNumUniquePoints()
template<typename RealType> int32 UE::Geometry::TConvexHull2< RealType >::GetNumUniquePoints () const inline
Number of unique points considered by convex hull construction (excludes exact duplicate points and filtered-out points)
Definition at line 114 of file ConvexHull2.h.
GetPolygonIndices()
template<typename RealType> TArray< int32 > const & UE::Geometry::TConvexHull2< RealType >::GetPolygonIndices () const inline
Returns
the calculated polygon vertices, as indices into the point set passed to Solve()
Definition at line 120 of file ConvexHull2.h.
GetTangent()
template<typename RealType> void UE::Geometry::TConvexHull2< RealType >::GetTangent (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > & Merged, int32 j0, int32 j1, int32 j2, int32 j3, int32 & i0, int32 & i1) protected
IsSolutionAvailable()
template<typename RealType> bool UE::Geometry::TConvexHull2< RealType >::IsSolutionAvailable () const inline
Returns
true if convex hull is available
Definition at line 91 of file ConvexHull2.h.
Referenced by UE::Geometry::TConvexHull2< float >::GetPolygonIndices().
Merge()
template<typename RealType> void UE::Geometry::TConvexHull2< RealType >::Merge (TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TArray< int32 > & Merged, int32 j0, int32 j1, int32 j2, int32 j3, int32 & i0, int32 & i1) protected
Solve() [1/3]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TConvexHull2< RealType >::Solve (int32 NumPoints, TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc = [](int32 Idx) {return true;})
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Parameters
NumPoints Number of points to consider
GetPointFunc Function providing array-style access into points
FilterFunc Optional filter to include only a subset of the points in the output hull
Returns
true if hull was generated, false if points span < 2 dimensions
Referenced by UE::Geometry::TConvexHull2< float >::Solve(), and UE::Geometry::TConvexHull2< float >::Solve().
Solve() [2/3]
template<typename RealType> bool UE::Geometry::TConvexHull2< RealType >::Solve (TArrayView< const TVector2< RealType > > Points) inline
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Parameters
Points Array of points to consider
Returns
true if hull was generated, false if points span < 2 dimensions
Definition at line 82 of file ConvexHull2.h.
Solve() [3/3]
template<typename RealType> bool UE::Geometry::TConvexHull2< RealType >::Solve (TArrayView< const TVector2< RealType > > Points, TFunctionRef< bool(int32)> FilterFunc) inline
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Parameters
Points Array of points to consider
Filter Optional filter to include only a subset of the points in the output hull
Returns
true if hull was generated, false if points span < 2 dimensions
Definition at line 65 of file ConvexHull2.h.
SolveSimplePolygon()
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TConvexHull2< RealType >::SolveSimplePolygon (int32 NumPolygonPoints, TFunctionRef< TVector2< RealType >(int32)> GetPointFunc, bool bIsKnownCCW = false)
Generate convex hull for a simple polygon If input has fewer than 3 points, will return false If input is not a simple polygon (e.g.
if it has self-intersections), may not find a correct hull
Parameters
NumPolygonPoints Number of points in the polygon
GetPointFunc Function providing array-style access into the polygon points
bIsKnownCCW If true, will save some processing time by assuming input is wound counter-clockwise
Returns
true if a hull was generated
Field Documentation
Dimension
template<typename RealType> int32 UE::Geometry::TConvexHull2< RealType >::Dimension = 0 protected
Definition at line 144 of file ConvexHull2.h.
Hull
template<typename RealType> TArray<int32> UE::Geometry::TConvexHull2< RealType >::Hull protected
Definition at line 146 of file ConvexHull2.h.
NumUniquePoints
template<typename RealType> int32 UE::Geometry::TConvexHull2< RealType >::NumUniquePoints = 0 protected
Definition at line 145 of file ConvexHull2.h.
The documentation for this class was generated from the following file:
ConvexHull2.h