Unreal Engine 5.6 C++ API: TextKeyUtil Namespace Reference
TextKeyUtil Namespace Reference
Functions
FORCEINLINE uint32 HashString (const FString &InStr)
Utility to produce a hash for a string (as used by FTextKey)
FORCEINLINE uint32 HashString (const FString &InStr, const uint32 InBaseHash)
uint32 HashString (const FTCHARToUTF16 &InStr)
Utility to produce a hash for a UTF-16 string (as used by FTextKey)
FORCEINLINE uint32 HashString (const FTCHARToUTF16 &InStr, const uint32 InBaseHash)
FORCEINLINE uint32 HashString (const TCHAR *InStr)
Utility to produce a hash for a string (as used by FTextKey)
FORCEINLINE uint32 HashString (const TCHAR *InStr, const int32 InStrLen)
Utility to produce a hash for a string (as used by FTextKey)
FORCEINLINE uint32 HashString (const TCHAR *InStr, const int32 InStrLen, const uint32 InBaseHash)
FORCEINLINE uint32 HashString (const TCHAR *InStr, const uint32 InBaseHash)
FORCEINLINE uint32 HashString (FStringView InStr)
Utility to produce a hash for a string (as used by FTextKey)
FORCEINLINE uint32 HashString (FStringView InStr, const uint32 InBaseHash)
Function Documentation
HashString() [1/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const FString & InStr)
Utility to produce a hash for a string (as used by FTextKey)
Definition at line 50 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [2/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const FString & InStr, const uint32 InBaseHash)
Definition at line 54 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [3/10]
uint32 TextKeyUtil::HashString (const FTCHARToUTF16 & InStr)
Utility to produce a hash for a UTF-16 string (as used by FTextKey)
Referenced by HashString(), HashString(), HashString(), HashString(), HashString(), HashString(), HashString(), HashString(), and HashString().
HashString() [4/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const FTCHARToUTF16 & InStr, const uint32 InBaseHash)
Definition at line 20 of file TextKey.h.
References FORCEINLINE, HashCombine(), and HashString().
HashString() [5/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const TCHAR * InStr)
Utility to produce a hash for a string (as used by FTextKey)
Definition at line 26 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [6/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const TCHAR * InStr, const int32 InStrLen)
Utility to produce a hash for a string (as used by FTextKey)
Definition at line 38 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [7/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const TCHAR * InStr, const int32 InStrLen, const uint32 InBaseHash)
Definition at line 43 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [8/10]
FORCEINLINE uint32 TextKeyUtil::HashString (const TCHAR * InStr, const uint32 InBaseHash)
Definition at line 31 of file TextKey.h.
References FORCEINLINE, and HashString().
HashString() [9/10]
FORCEINLINE uint32 TextKeyUtil::HashString (FStringView InStr)
Utility to produce a hash for a string (as used by FTextKey)
Definition at line 60 of file TextKey.h.
References FORCEINLINE, TStringView< CharType >::GetData(), HashString(), and TStringView< CharType >::Len().
HashString() [10/10]
FORCEINLINE uint32 TextKeyUtil::HashString (FStringView InStr, const uint32 InBaseHash)
Definition at line 64 of file TextKey.h.
References FORCEINLINE, TStringView< CharType >::GetData(), HashString(), and TStringView< CharType >::Len().