Unreal Engine 5.6 C++ API: SmartObjectDefinitionReference.h File Reference
SmartObjectDefinitionReference.h File Reference
#include "StructUtils/PropertyBag.h"
#include "SmartObjectDefinitionReference.generated.h"
Data Structures
struct TStructOpsTypeTraits< FSmartObjectDefinitionReference >
Macros
#define UE_API SMARTOBJECTSMODULE_API
Functions
USTRUCT () struct FSmartObjectDefinitionReference
Struct to hold reference to a SmartObjectDefinition asset along with values to parameterized it.
Macro Definition Documentation
UE_API
#define UE_API SMARTOBJECTSMODULE_API
Definition at line 8 of file SmartObjectDefinitionReference.h.
Function Documentation
USTRUCT()
USTRUCT ()
Struct to hold reference to a SmartObjectDefinition asset along with values to parameterized it.
Returns
true if the reference is set.
Returns a variation of the USmartObjectDefinition based on the parameters defined in the reference.
Returns
Pointer to an asset variation.
Sets the SmartObject Definition asset and synchronize parameters.
Returns
const pointer to the referenced SmartObject Definition asset.
pointer to the referenced SmartObject Definition asset.
reference to the parameters for the referenced SmartObject Definition asset.
reference to the parameters for the referenced SmartObject Definition asset.
Enforce self parameters to be compatible with those exposed by the selected SmartObject Definition asset.
Indicates if current parameters are compatible with those available in the selected SmartObject Definition asset.
Returns
true when parameters requires to be synced to be compatible with those available in the selected SmartObject Definition asset, false otherwise.
Sync parameters to match the asset if required.
Returns
true if the property of specified ID is overridden.
Sets the override status of specified property by ID.
Returns
a valid hash based on the associated asset path and overriden parameters if the asset is valid; 0 otherwise
Array of overridden properties. Non-overridden properties will inherit the values from the SmartObjectDefinition default parameters.
Definition at line 15 of file SmartObjectDefinitionReference.h.
References Category, GENERATED_BODY, GetTypeHash(), IsValid(), meta, operator!=(), operator==(), UE_API, UE_DEPRECATED, and UPROPERTY.