Unreal Engine 5.6 C++ API: UE::Sequencer::FSequenceModel Class Reference
UE::Sequencer::FSequenceModel Class Reference
#include "SequenceModel.h"
Public Member Functions
FSequenceModel (TWeakPtr< FSequencerEditorViewModel > InEditorViewModel)
TOptional< EItemDropZone > CanAcceptDrop (const FViewModelPtr &TargetModel, const FDragDropEvent &DragDropEvent, EItemDropZone InItemDropZone) override
TSharedPtr< FViewModel > GetBottomSpacer () const
TSharedPtr< FSequencerEditorViewModel > GetEditor () const
UMovieScene * GetMovieScene () const
UMovieSceneSequence * GetSequence () const
FMovieSceneSequenceID GetSequenceID () const
TSharedPtr< ISequencer > GetSequencer () const
TSharedPtr< FSequencer > GetSequencerImpl () const
FSortingKey GetSortingKey () const override
Called by the part to sort this model among its siblings.
void InitializeExtensions ()
virtual void OnDecorationAdded (UObject *AddedDecoration) override
virtual void OnDecorationRemoved (UObject *RemovedDecoration) override
void OnModifiedDirectly (UMovieSceneSignedObject *) override
void OnModifiedIndirectly (UMovieSceneSignedObject *) override
void OnPostUndo () override
void PerformDrop (const FViewModelPtr &TargetModel, const FDragDropEvent &DragDropEvent, EItemDropZone InItemDropZone) override
void SetCustomOrder (int32 InCustomOrder) override
Set a custom sort index for this view model.
void SetSequence (UMovieSceneSequence *InSequence, FMovieSceneSequenceID InSequenceID)
void SortChildren () override
Called when the model should sort its immediate children.
UE_SEQUENCER_DECLARE_CASTABLE (FSequenceModel, FViewModel, ISortableExtension, IOutlinerDropTargetOutlinerExtension)
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::ISortableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISortableExtension) virtual ~ISortableExtension()
Public Member Functions inherited from UE::Sequencer::IOutlinerDropTargetOutlinerExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IOutlinerDropTargetOutlinerExtension) virtual ~IOutlinerDropTargetOutlinerExtension()
Public Member Functions inherited from UE::MovieScene::ISequenceDataEventHandler
virtual void OnBindingAdded (const FMovieSceneBinding &)
virtual void OnBindingParentChanged (const FGuid &ObjectBindingID, const FGuid &NewParent)
virtual void OnBindingRemoved (const FGuid &)
virtual void OnClockChanged (EUpdateClockSource NewClock, UMovieSceneClock *NewCustomClock)
virtual void OnRootFolderAdded (UMovieSceneFolder *)
virtual void OnRootFolderRemoved (UMovieSceneFolder *)
virtual void OnTrackAdded (UMovieSceneTrack *)
virtual void OnTrackAddedToBinding (UMovieSceneTrack *Track, const FGuid &ObjectBindingID)
virtual void OnTrackRemoved (UMovieSceneTrack *)
virtual void OnTrackRemovedFromBinding (UMovieSceneTrack *Track, const FGuid &ObjectBindingID)
Static Public Member Functions
static EViewModelListType GetDecorationModelListType ()
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Public Member Functions inherited from UE::Sequencer::ISortableExtension
static void SortChildren (FViewModelChildren &Children, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
static void SortChildren (TSharedPtr< FViewModel > ParentModel, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
Static Public Attributes
static FOnInitializeSequenceModel CreateExtensionsEvent
Private Attributes
TSharedPtr< FViewModel > BottomSpacer
FViewModelListHead DecorationModelList
MovieScene::TNonIntrusiveEventHandler< MovieScene::ISequenceDataEventHandler > MovieSceneDataEventHandler
MovieScene::TNonIntrusiveEventHandler< MovieScene::ISignedObjectEventHandler > MovieSceneEventHandler
FViewModelListHead RootOutlinerItems
MovieScene::TNonIntrusiveEventHandler< MovieScene::ISignedObjectEventHandler > SequenceEventHandler
FMovieSceneSequenceID SequenceID
TWeakPtr< FSequencerEditorViewModel > WeakEditor
TWeakObjectPtr< UMovieSceneSequence > WeakSequence
Additional Inherited Members
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Detailed Description
Definition at line 40 of file SequenceModel.h.
Constructor & Destructor Documentation
FSequenceModel()
UE::Sequencer::FSequenceModel::FSequenceModel (TWeakPtr< FSequencerEditorViewModel > InEditorViewModel)
Referenced by UE_SEQUENCER_DECLARE_CASTABLE().
Member Function Documentation
CanAcceptDrop()
TOptional< EItemDropZone > UE::Sequencer::FSequenceModel::CanAcceptDrop (const FViewModelPtr & TargetModel, const FDragDropEvent & DragDropEvent, EItemDropZone InItemDropZone) override virtual
Implements UE::Sequencer::IOutlinerDropTargetOutlinerExtension.
GetBottomSpacer()
TSharedPtr< FViewModel > UE::Sequencer::FSequenceModel::GetBottomSpacer () const inline
Definition at line 66 of file SequenceModel.h.
References BottomSpacer.
GetDecorationModelListType()
EViewModelListType UE::Sequencer::FSequenceModel::GetDecorationModelListType () static
GetEditor()
TSharedPtr< FSequencerEditorViewModel > UE::Sequencer::FSequenceModel::GetEditor () const
GetMovieScene()
UMovieScene * UE::Sequencer::FSequenceModel::GetMovieScene () const
GetSequence()
UMovieSceneSequence * UE::Sequencer::FSequenceModel::GetSequence () const
GetSequenceID()
FMovieSceneSequenceID UE::Sequencer::FSequenceModel::GetSequenceID () const
GetSequencer()
TSharedPtr< ISequencer > UE::Sequencer::FSequenceModel::GetSequencer () const
GetSequencerImpl()
TSharedPtr< FSequencer > UE::Sequencer::FSequenceModel::GetSequencerImpl () const
GetSortingKey()
FSortingKey UE::Sequencer::FSequenceModel::GetSortingKey () const override virtual
Called by the part to sort this model among its siblings.
Implements UE::Sequencer::ISortableExtension.
InitializeExtensions()
void UE::Sequencer::FSequenceModel::InitializeExtensions ()
OnDecorationAdded()
virtual void UE::Sequencer::FSequenceModel::OnDecorationAdded (UObject * AddedDecoration) override virtual
Reimplemented from UE::MovieScene::ISequenceDataEventHandler.
OnDecorationRemoved()
virtual void UE::Sequencer::FSequenceModel::OnDecorationRemoved (UObject * RemovedDecoration) override virtual
Reimplemented from UE::MovieScene::ISequenceDataEventHandler.
OnModifiedDirectly()
void UE::Sequencer::FSequenceModel::OnModifiedDirectly (UMovieSceneSignedObject *) override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
OnModifiedIndirectly()
void UE::Sequencer::FSequenceModel::OnModifiedIndirectly (UMovieSceneSignedObject *) override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
OnPostUndo()
void UE::Sequencer::FSequenceModel::OnPostUndo () override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
PerformDrop()
void UE::Sequencer::FSequenceModel::PerformDrop (const FViewModelPtr & TargetModel, const FDragDropEvent & DragDropEvent, EItemDropZone InItemDropZone) override virtual
Implements UE::Sequencer::IOutlinerDropTargetOutlinerExtension.
SetCustomOrder()
void UE::Sequencer::FSequenceModel::SetCustomOrder (int32 InCustomOrder) override virtual
Set a custom sort index for this view model.
Implements UE::Sequencer::ISortableExtension.
SetSequence()
void UE::Sequencer::FSequenceModel::SetSequence (UMovieSceneSequence * InSequence, FMovieSceneSequenceID InSequenceID)
SortChildren()
void UE::Sequencer::FSequenceModel::SortChildren () override virtual
Called when the model should sort its immediate children.
Implements UE::Sequencer::ISortableExtension.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FSequenceModel::UE_SEQUENCER_DECLARE_CASTABLE (FSequenceModel , FViewModel , ISortableExtension , IOutlinerDropTargetOutlinerExtension)
References FSequenceModel(), and UE::Sequencer::FViewModel::FViewModel().
Field Documentation
BottomSpacer
TSharedPtr<FViewModel> UE::Sequencer::FSequenceModel::BottomSpacer private
Definition at line 97 of file SequenceModel.h.
Referenced by GetBottomSpacer().
CreateExtensionsEvent
FOnInitializeSequenceModel UE::Sequencer::FSequenceModel::CreateExtensionsEvent static
Definition at line 51 of file SequenceModel.h.
DecorationModelList
FViewModelListHead UE::Sequencer::FSequenceModel::DecorationModelList private
Definition at line 92 of file SequenceModel.h.
MovieSceneDataEventHandler
MovieScene::TNonIntrusiveEventHandler<MovieScene::ISequenceDataEventHandler> UE::Sequencer::FSequenceModel::MovieSceneDataEventHandler private
Definition at line 102 of file SequenceModel.h.
MovieSceneEventHandler
MovieScene::TNonIntrusiveEventHandler<MovieScene::ISignedObjectEventHandler> UE::Sequencer::FSequenceModel::MovieSceneEventHandler private
Definition at line 101 of file SequenceModel.h.
RootOutlinerItems
FViewModelListHead UE::Sequencer::FSequenceModel::RootOutlinerItems private
Definition at line 91 of file SequenceModel.h.
SequenceEventHandler
MovieScene::TNonIntrusiveEventHandler<MovieScene::ISignedObjectEventHandler> UE::Sequencer::FSequenceModel::SequenceEventHandler private
Definition at line 100 of file SequenceModel.h.
SequenceID
FMovieSceneSequenceID UE::Sequencer::FSequenceModel::SequenceID private
Definition at line 98 of file SequenceModel.h.
WeakEditor
TWeakPtr<FSequencerEditorViewModel> UE::Sequencer::FSequenceModel::WeakEditor private
Definition at line 95 of file SequenceModel.h.
WeakSequence
TWeakObjectPtr<UMovieSceneSequence> UE::Sequencer::FSequenceModel::WeakSequence private
Definition at line 94 of file SequenceModel.h.
The documentation for this class was generated from the following file:
SequenceModel.h