Unreal Engine 5.6 C++ API: UE::GC::Private Namespace Reference
UE::GC::Private Namespace Reference
Data Structures
struct FIterationTimerStat
struct FMemberUnpacked
struct FMemberWordUnpacked
struct FStats
struct FStridedReferenceArray
struct FStridedReferenceIterator
struct FStridedReferenceView
Functions
FORCEINLINE FStridedReferenceIterator begin (FStridedReferenceView View)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void CallARO (DispatcherType &Dispatcher, uint8 *Instance, FMemberWord Word)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void CallARO (DispatcherType &Dispatcher, UObject *Instance, FMemberWord Word)
template<class DispatcherType>
FORCEINLINE void CallSlowARO (DispatcherType &, uint32 SlowAROIdx, uint8 *Instance, uint32 MemberIdx)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void CallSlowARO (DispatcherType &Dispatcher, uint32 SlowAROIdx, UObject *Instance, uint32 MemberIdx)
FORCEINLINE FStridedReferenceIterator end (FStridedReferenceView View)
FORCEINLINE int32 GetNum (FStridedReferenceView View)
FORCEINLINE const uint8 * GetSparseData (const FScriptSparseArray &Array)
FORCEINLINE uint8 * GetSparseData (FScriptSparseArray &Array)
static FORCENOINLINE void LogIllegalTypeFatal (EMemberType Type, uint32 Idx, uint8 *)
static FORCENOINLINE void LogIllegalTypeFatal (EMemberType Type, uint32 Idx, UObject *Instance)
template<class T, class R>
TMemberDeclaration< T > MakeMember (const char *Name, uint32 Offset, R T::*)
template<class T, class R>
TMemberDeclaration< T > MakeMember (const char *Name, uint32 Offset, TArray< R > T::*)
template<class T, class O>
TMemberDeclaration< T > MakeMember (const char *Name, uint32 Offset, TArray< TObjectPtr< O > > T::*)
template<class T, class O>
TMemberDeclaration< T > MakeMember (const char *Name, uint32 Offset, TObjectPtr< O > T::*)
template<class T, class S>
TMemberDeclaration< T > MakeNestedMember (const char *Name, uint32 Offset, TArray< S > T::*, TSchemaBuilder< S > &InnerSchema)
void SetSkipDestroy (bool bSkip)
FORCEINLINE FStridedReferenceView ToView (FStridedReferenceArray In)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitDynamicallyTypedValue (DispatcherType &Dispatcher, UE::FDynamicallyTypedValue &Value)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitFieldPath (DispatcherType &Dispatcher, FFieldPath &FieldPath, EOrigin Origin, uint32 MemberIdx)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitFieldPathArray (DispatcherType &Dispatcher, TArray< FFieldPath > &FieldPaths, EOrigin Origin, uint32 MemberIdx)
template<class DispatcherType, typename ObjectType>
FORCEINLINE_DEBUGGABLE void VisitMembers (DispatcherType &Dispatcher, FSchemaView Schema, ObjectType *Instance)
template<class DispatcherType>
FORCENOINLINE void VisitNestedStructMembers (DispatcherType &Dispatcher, FSchemaView Schema, uint8 *Instance)
template<class DispatcherType>
void VisitNestedStructMembers (DispatcherType &Dispatcher, FSchemaView Schema, uint8 *Instance)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitOptional (DispatcherType &Dispatcher, FSchemaView StructSchema, uint8 *Instance)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitSparseStructArray (DispatcherType &Dispatcher, FSchemaView StructSchema, FScriptSparseArray &Array)
template<class DispatcherType, class ArrayType>
FORCEINLINE_DEBUGGABLE void VisitStructArray (DispatcherType &Dispatcher, FSchemaView StructSchema, ArrayType &Array)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void VisitStructs (DispatcherType &Dispatcher, FSchemaView StructSchema, uint8 *It, const int32 Num)
Function Documentation
begin()
FORCEINLINE FStridedReferenceIterator UE::GC::Private::begin (FStridedReferenceView View)
Definition at line 490 of file FastReferenceCollector.h.
References UE::GC::Private::FStridedReferenceView::Data, FORCEINLINE, and UE::GC::Private::FStridedReferenceView::Stride.
CallARO() [1/2]
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallARO (DispatcherType & Dispatcher, uint8 * Instance, FMemberWord Word)
Definition at line 625 of file FastReferenceCollector.h.
References CallARO(), FORCEINLINE_DEBUGGABLE, Instance, and Word.
CallARO() [2/2]
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallARO (DispatcherType & Dispatcher, UObject * Instance, FMemberWord Word)
Definition at line 609 of file FastReferenceCollector.h.
References CallARO(), FORCEINLINE_DEBUGGABLE, Instance, TEXT, UE_LOG, Warning, and Word.
Referenced by CallARO(), CallARO(), and VisitMembers().
CallSlowARO() [1/2]
template<class DispatcherType> FORCEINLINE void UE::GC::Private::CallSlowARO (DispatcherType & , uint32 SlowAROIdx, uint8 * Instance, uint32 MemberIdx)
Definition at line 657 of file FastReferenceCollector.h.
References CallSlowARO(), FORCEINLINE, Instance, LogIllegalTypeFatal(), and UE::GC::SlowARO.
CallSlowARO() [2/2]
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallSlowARO (DispatcherType & Dispatcher, uint32 SlowAROIdx, UObject * Instance, uint32 MemberIdx)
Definition at line 631 of file FastReferenceCollector.h.
References CallSlowARO(), UE::GC::FSlowARO::CallSync(), FORCEINLINE_DEBUGGABLE, Instance, and UE::GC::FSlowARO::TryQueueCall().
Referenced by CallSlowARO(), CallSlowARO(), and VisitMembers().
end()
FORCEINLINE FStridedReferenceIterator UE::GC::Private::end (FStridedReferenceView View)
Definition at line 491 of file FastReferenceCollector.h.
References UE::GC::Private::FStridedReferenceView::Data, FORCEINLINE, UE::GC::Private::FStridedReferenceView::Num, and UE::GC::Private::FStridedReferenceView::Stride.
GetNum()
FORCEINLINE int32 UE::GC::Private::GetNum (FStridedReferenceView View)
Definition at line 492 of file FastReferenceCollector.h.
References FORCEINLINE, and UE::GC::Private::FStridedReferenceView::Num.
GetSparseData() [1/2]
FORCEINLINE const uint8 * UE::GC::Private::GetSparseData (const FScriptSparseArray & Array)
Definition at line 503 of file FastReferenceCollector.h.
References Array, FORCEINLINE, and GetSparseData().
GetSparseData() [2/2]
FORCEINLINE uint8 * UE::GC::Private::GetSparseData (FScriptSparseArray & Array)
Definition at line 498 of file FastReferenceCollector.h.
References Array, FORCEINLINE, and GetSparseData().
Referenced by GetSparseData(), GetSparseData(), and VisitSparseStructArray().
LogIllegalTypeFatal() [1/2]
FORCENOINLINE void UE::GC::Private::LogIllegalTypeFatal (EMemberType Type, uint32 Idx, uint8 *) static
Definition at line 651 of file FastReferenceCollector.h.
References Fatal, FORCENOINLINE, LogIllegalTypeFatal(), TEXT, and UE_LOG.
LogIllegalTypeFatal() [2/2]
FORCENOINLINE void UE::GC::Private::LogIllegalTypeFatal (EMemberType Type, uint32 Idx, UObject * Instance) static
Definition at line 646 of file FastReferenceCollector.h.
References Fatal, FORCENOINLINE, GetNameSafe(), GetPathNameSafe(), Instance, LogIllegalTypeFatal(), TEXT, and UE_LOG.
Referenced by CallSlowARO(), LogIllegalTypeFatal(), LogIllegalTypeFatal(), and VisitMembers().
MakeMember() [1/4]
template<class T, class R> TMemberDeclaration< T > UE::GC::Private::MakeMember (const char * Name, uint32 Offset, R T::*)
Definition at line 309 of file GarbageCollectionSchema.h.
References Name, R, and UE::GC::Reference.
MakeMember() [2/4]
template<class T, class R> TMemberDeclaration< T > UE::GC::Private::MakeMember (const char * Name, uint32 Offset, TArray< R > T::*)
Definition at line 316 of file GarbageCollectionSchema.h.
References Name, and UE::GC::ReferenceArray.
MakeMember() [3/4]
template<class T, class O> TMemberDeclaration< T > UE::GC::Private::MakeMember (const char * Name, uint32 Offset, TArray< TObjectPtr< O > > T::*)
Definition at line 329 of file GarbageCollectionSchema.h.
References Name, and UE::GC::ReferenceArray.
MakeMember() [4/4]
template<class T, class O> TMemberDeclaration< T > UE::GC::Private::MakeMember (const char * Name, uint32 Offset, TObjectPtr< O > T::*)
Definition at line 323 of file GarbageCollectionSchema.h.
References Name, and UE::GC::Reference.
MakeNestedMember()
template<class T, class S> TMemberDeclaration< T > UE::GC::Private::MakeNestedMember (const char * Name, uint32 Offset, TArray< S > T::* , TSchemaBuilder< S > & InnerSchema)
Definition at line 335 of file GarbageCollectionSchema.h.
References UE::GC::FSchemaBuilder::Build(), Name, and UE::GC::StructArray.
SetSkipDestroy()
void UE::GC::Private::SetSkipDestroy (bool bSkip)
ToView()
FORCEINLINE FStridedReferenceView UE::GC::Private::ToView (FStridedReferenceArray In)
Definition at line 493 of file FastReferenceCollector.h.
References UE::GC::Private::FStridedReferenceArray::Array, FORCEINLINE, TScriptArray< AllocatorType >::GetData(), UE::GC::Private::FStridedReferenceArray::Layout, TScriptArray< AllocatorType >::Num(), ToView(), UE::GC::FStridedLayout::WordOffset, and UE::GC::FStridedLayout::WordStride.
Referenced by ToView().
VisitDynamicallyTypedValue()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitDynamicallyTypedValue (DispatcherType & Dispatcher, UE::FDynamicallyTypedValue & Value)
Definition at line 595 of file FastReferenceCollector.h.
References UE::FDynamicallyTypedValueType::DoesNot, FORCEINLINE_DEBUGGABLE, Value, and VisitDynamicallyTypedValue().
Referenced by VisitDynamicallyTypedValue(), and VisitMembers().
VisitFieldPath()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitFieldPath (DispatcherType & Dispatcher, FFieldPath & FieldPath, EOrigin Origin, uint32 MemberIdx)
Definition at line 560 of file FastReferenceCollector.h.
References FGCInternals::ClearCachedField(), UE::GC::FieldPath, FORCEINLINE_DEBUGGABLE, FGCInternals::GetResolvedOwner(), Origin, and VisitFieldPath().
Referenced by VisitFieldPath(), VisitFieldPathArray(), and VisitMembers().
VisitFieldPathArray()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitFieldPathArray (DispatcherType & Dispatcher, TArray< FFieldPath > & FieldPaths, EOrigin Origin, uint32 MemberIdx)
Definition at line 576 of file FastReferenceCollector.h.
References UE::GC::FieldPath, FORCEINLINE_DEBUGGABLE, Origin, VisitFieldPath(), and VisitFieldPathArray().
Referenced by VisitFieldPathArray(), and VisitMembers().
VisitMembers()
template<class DispatcherType, typename ObjectType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitMembers (DispatcherType & Dispatcher, FSchemaView Schema, ObjectType * Instance)
Definition at line 663 of file FastReferenceCollector.h.
References UE::GC::ARO, CallARO(), CallSlowARO(), check, UE::GC::Count, UE::GC::DynamicallyTypedValue, UE::GC::FieldPath, UE::GC::FieldPathArray, FORCEINLINE_DEBUGGABLE, UE::GC::FreezableReferenceArray, UE::GC::FreezableStructArray, UE::GC::FSchemaView::GetOrigin(), UE::GC::FSchemaView::GetWords(), Instance, UE::GC::FSchemaView::IsEmpty(), UE::GC::Jump, LogIllegalTypeFatal(), UE::GC::MemberARO, UE::GC::FMemberPacked::OffsetRange, UE::GC::Optional, Origin, Quad, UE::GC::Reference, UE::GC::ReferenceArray, UE::GC::SlowARO, UE::GC::SparseStructArray, UE::GC::Stop, UE::GC::StridedArray, UE::GC::StructArray, UE_GC_DEBUGNAMES, VisitDynamicallyTypedValue(), VisitFieldPath(), VisitFieldPathArray(), VisitMembers(), VisitOptional(), VisitSparseStructArray(), and VisitStructArray().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects(), VisitMembers(), and VisitNestedStructMembers().
VisitNestedStructMembers() [1/2]
template<class DispatcherType> FORCENOINLINE void UE::GC::Private::VisitNestedStructMembers (DispatcherType & Dispatcher, FSchemaView Schema, uint8 * Instance)
Definition at line 729 of file FastReferenceCollector.h.
References Instance, VisitMembers(), and VisitNestedStructMembers().
Referenced by VisitNestedStructMembers(), VisitSparseStructArray(), and VisitStructs().
VisitNestedStructMembers() [2/2]
template<class DispatcherType> void UE::GC::Private::VisitNestedStructMembers (DispatcherType & Dispatcher, FSchemaView Schema, uint8 * Instance)
Definition at line 729 of file FastReferenceCollector.h.
References Instance, VisitMembers(), and VisitNestedStructMembers().
Referenced by VisitNestedStructMembers(), VisitSparseStructArray(), and VisitStructs().
VisitOptional()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitOptional (DispatcherType & Dispatcher, FSchemaView StructSchema, uint8 * Instance)
Definition at line 585 of file FastReferenceCollector.h.
References check, FORCEINLINE_DEBUGGABLE, UE::GC::FSchemaView::GetStructStride(), Instance, UE::GC::FSchemaView::IsEmpty(), VisitOptional(), and VisitStructs().
Referenced by VisitMembers(), and VisitOptional().
VisitSparseStructArray()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitSparseStructArray (DispatcherType & Dispatcher, FSchemaView StructSchema, FScriptSparseArray & Array)
Definition at line 537 of file FastReferenceCollector.h.
References Array, check, FORCEINLINE_DEBUGGABLE, GetSparseData(), UE::GC::FSchemaView::GetStructStride(), UE::GC::FSchemaView::IsEmpty(), Num, VisitNestedStructMembers(), and VisitSparseStructArray().
Referenced by VisitMembers(), and VisitSparseStructArray().
VisitStructArray()
template<class DispatcherType, class ArrayType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitStructArray (DispatcherType & Dispatcher, FSchemaView StructSchema, ArrayType & Array)
Definition at line 530 of file FastReferenceCollector.h.
References Array, FORCEINLINE_DEBUGGABLE, VisitStructArray(), and VisitStructs().
Referenced by VisitMembers(), and VisitStructArray().
VisitStructs()
template<class DispatcherType> FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitStructs (DispatcherType & Dispatcher, FSchemaView StructSchema, uint8 * It, const int32 Num)
Definition at line 512 of file FastReferenceCollector.h.
References check, End, FORCEINLINE_DEBUGGABLE, UE::GC::FSchemaView::GetStructStride(), UE::GC::FSchemaView::IsEmpty(), Num, VisitNestedStructMembers(), and VisitStructs().
Referenced by VisitOptional(), VisitStructArray(), and VisitStructs().