Unreal Engine 5.6 C++ API: FGlobalCueTypeTable Class Reference
FGlobalCueTypeTable Class Reference
#include "NetworkPredictionCues.h"
Data Structures
struct FRegisteredCueTypeInfo
struct FTypeInfo
Public Member Functions
FNetSimCueWrapperBase * Allocate (FNetSimCueTypeId ID)
void FinalizeCueTypes ()
FString GetTypeName (FNetSimCueTypeId ID) const
Static Public Member Functions
static FGlobalCueTypeTable & Get ()
static bool IsRegisterationTypeInfoDirty ()
template<typename TCue>
static FORCENOINLINE void RegisterCueType (const FString &TypeName)
static FDelegateHandle RegisterDispatchTableCallback (const TFunction< void()> &RegisterFunc)
template<typename TCue>
static void UnregisterCueType ()
static void UnregisterDispatchTableCallback (FDelegateHandle Handle)
Static Private Member Functions
static NETWORKPREDICTION_API FRegisteredCueTypeInfo & GetRegistedTypeInfo ()
Private Attributes
TMap< FNetSimCueTypeId, FTypeInfo > TypeInfoMap
Static Private Attributes
static NETWORKPREDICTION_API FGlobalCueTypeTable Singleton
Detailed Description
Definition at line 122 of file NetworkPredictionCues.h.
Member Function Documentation
Allocate()
FNetSimCueWrapperBase * FGlobalCueTypeTable::Allocate (FNetSimCueTypeId ID) inline
Definition at line 235 of file NetworkPredictionCues.h.
References ID, and TypeInfoMap.
FinalizeCueTypes()
void FGlobalCueTypeTable::FinalizeCueTypes () inline
Definition at line 202 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, check, FGlobalCueTypeTable::FRegisteredCueTypeInfo::CueTypes, GetRegistedTypeInfo(), ID, FGlobalCueTypeTable::FTypeInfo::IDPtr, FGlobalCueTypeTable::FRegisteredCueTypeInfo::InitDispatchTablesDelegate, TEXT, TypeInfoMap, FGlobalCueTypeTable::FTypeInfo::TypeName, UE_LOG, and Verbose.
Get()
FGlobalCueTypeTable & FGlobalCueTypeTable::Get () inline static
Definition at line 230 of file NetworkPredictionCues.h.
References Singleton.
Referenced by TCueDispatchTable< TCueHandler >::Dispatch(), FSavedCue::GetDebugName(), FNetSimCueDispatcher::Invoke(), and FSavedCue::NetSerialize().
GetRegistedTypeInfo()
NETWORKPREDICTION_API FRegisteredCueTypeInfo & FGlobalCueTypeTable::GetRegistedTypeInfo () static private
Referenced by FinalizeCueTypes(), IsRegisterationTypeInfoDirty(), RegisterCueType(), RegisterDispatchTableCallback(), UnregisterCueType(), and UnregisterDispatchTableCallback().
GetTypeName()
FString FGlobalCueTypeTable::GetTypeName (FNetSimCueTypeId ID) const inline
Definition at line 240 of file NetworkPredictionCues.h.
References ID, and TypeInfoMap.
IsRegisterationTypeInfoDirty()
bool FGlobalCueTypeTable::IsRegisterationTypeInfoDirty () inline static
Definition at line 179 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, and GetRegistedTypeInfo().
Referenced by TCueDispatchTable< TCueHandler >::Dispatch(), FNetSimCueDispatcher::Invoke(), and FSavedCue::NetSerialize().
RegisterCueType()
template<typename TCue> FORCENOINLINE void FGlobalCueTypeTable::RegisterCueType (const FString & TypeName) inline static
Definition at line 131 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, FGlobalCueTypeTable::FRegisteredCueTypeInfo::CueTypes, FORCENOINLINE, GetRegistedTypeInfo(), TNetSimCueTypeRequirements< TCue >::RequiresNetIdentical, TNetSimCueTypeRequirements< TCue >::RequiresNetSerialize, TEXT, UE_LOG, THasNetIdenticalHelper< TCue >::Value, and Verbose.
Referenced by TNetSimCueTypeAutoRegisterHelper< TCue >::TNetSimCueTypeAutoRegisterHelper().
RegisterDispatchTableCallback()
FDelegateHandle FGlobalCueTypeTable::RegisterDispatchTableCallback (const TFunction< void()> & RegisterFunc) inline static
Definition at line 181 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, GetRegistedTypeInfo(), and FGlobalCueTypeTable::FRegisteredCueTypeInfo::InitDispatchTablesDelegate.
Referenced by TNetSimCueHandlerAutoRegisterHelper< THandler >::TNetSimCueHandlerAutoRegisterHelper(), and TNetSimCueSetHandlerAutoRegisterHelper< THandler, TCueSet >::TNetSimCueSetHandlerAutoRegisterHelper().
UnregisterCueType()
template<typename TCue> void FGlobalCueTypeTable::UnregisterCueType () inline static
Definition at line 152 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, FGlobalCueTypeTable::FRegisteredCueTypeInfo::CueTypes, GetRegistedTypeInfo(), FGlobalCueTypeTable::FTypeInfo::IDPtr, IsEngineExitRequested(), No, npEnsureMsgf, Singleton, TEXT, UE_LOG, and Verbose.
Referenced by TNetSimCueTypeAutoRegisterHelper< TCue >::~TNetSimCueTypeAutoRegisterHelper().
UnregisterDispatchTableCallback()
void FGlobalCueTypeTable::UnregisterDispatchTableCallback (FDelegateHandle Handle) inline static
Definition at line 189 of file NetworkPredictionCues.h.
References FGlobalCueTypeTable::FRegisteredCueTypeInfo::bDirty, GetRegistedTypeInfo(), Handle, FGlobalCueTypeTable::FRegisteredCueTypeInfo::InitDispatchTablesDelegate, and IsEngineExitRequested().
Referenced by TNetSimCueHandlerAutoRegisterHelper< THandler >::~TNetSimCueHandlerAutoRegisterHelper(), and TNetSimCueSetHandlerAutoRegisterHelper< THandler, TCueSet >::~TNetSimCueSetHandlerAutoRegisterHelper().
Field Documentation
Singleton
NETWORKPREDICTION_API FGlobalCueTypeTable FGlobalCueTypeTable::Singleton static private
Definition at line 266 of file NetworkPredictionCues.h.
Referenced by Get(), and UnregisterCueType().
TypeInfoMap
TMap<FNetSimCueTypeId, FTypeInfo> FGlobalCueTypeTable::TypeInfoMap private
Definition at line 264 of file NetworkPredictionCues.h.
Referenced by Allocate(), FinalizeCueTypes(), and GetTypeName().
The documentation for this class was generated from the following file:
NetworkPredictionCues.h