Unreal Engine 5.6 C++ API: Metasound::Frontend::IDataTypeRegistry Class Reference
Metasound::Frontend::IDataTypeRegistry Class Reference abstract
#include "MetasoundFrontendDataTypeRegistry.h"
Public Member Functions
virtual ~IDataTypeRegistry ()=default
virtual TUniquePtr< INode > CreateConstructorInputNode (const FName &InInputType, FNodeData InNodeData) const =0
virtual TUniquePtr< INode > CreateConstructorOutputNode (const FName &InDataTypeName, FNodeData InNodeData) const =0
virtual TSharedPtr< IDataChannel, ESPMode::ThreadSafe > CreateDataChannel (const FName &InDataType, const FOperatorSettings &InOperatorSettings) const =0
virtual TOptional< FAnyDataReference > CreateDataReference (const FName &InDataType, EDataReferenceAccessType InAccessType, const FLiteral &InLiteral, const FOperatorSettings &InOperatorSettings) const =0
Create a data reference of the data type given a literal.
virtual FLiteral CreateDefaultLiteral (const FName &InDataType) const =0
virtual TUniquePtr< INode > CreateInputNode (const FName &InInputType, FNodeData InNodeData) const =0
virtual FLiteral CreateLiteralFromUObject (const FName &InDataType, UObject *InObject) const =0
virtual FLiteral CreateLiteralFromUObjectArray (const FName &InDataType, const TArray< UObject * > &InObjectArray) const =0
virtual TUniquePtr< INode > CreateOutputNode (const FName &InDataTypeName, FNodeData InNodeData) const =0
virtual TSharedPtr< Audio::IProxyData > CreateProxyFromUObject (const FName &InDataType, UObject *InObject) const =0
virtual TUniquePtr< INode > CreateVariableAccessorNode (const FName &InDataType, FNodeData InNodeData) const =0
virtual TUniquePtr< INode > CreateVariableDeferredAccessorNode (const FName &InDataType, FNodeData InNodeData) const =0
virtual TUniquePtr< INode > CreateVariableMutatorNode (const FName &InDataType, FNodeData InNodeData) const =0
virtual TUniquePtr< INode > CreateVariableNode (const FName &InDataType, FLiteral InLiteral, FNodeData InNodeData) const =0
virtual const IDataTypeRegistryEntry * FindDataTypeRegistryEntry (const FName &InDataTypeName) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetConstructorInputClassMetadata (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetConstructorOutputClassMetadata (const FName &InDataType) const =0
virtual bool GetDataTypeInfo (const FName &InDataType, FDataTypeRegistryInfo &OutInfo) const =0
Returns DataType info associated with the provided DataType name.
virtual bool GetDataTypeInfo (const UObject *InObject, FDataTypeRegistryInfo &OutInfo) const =0
Returns DataType info associated with the provided object.
virtual ELiteralType GetDesiredLiteralType (const FName &InDataType) const =0
virtual TSharedPtr< const IEnumDataTypeInterface > GetEnumInterfaceForDataType (const FName &InDataType) const =0
Return the enum interface for a data type.
virtual bool GetFrontendConstructorInputClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an input node of the data type.
virtual bool GetFrontendConstructorOutputClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an output node of the data type.
virtual bool GetFrontendInputClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an input node of the data type.
virtual bool GetFrontendLiteralClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing a variable node of the data type.
virtual bool GetFrontendOutputClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an output node of the data type.
virtual bool GetFrontendVariableAccessorClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an get variable node of the data type.
virtual bool GetFrontendVariableClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an init variable node of the data type.
virtual bool GetFrontendVariableDeferredAccessorClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an get delayed variable node of the data type.
virtual bool GetFrontendVariableMutatorClass (const FName &InDataType, FMetasoundFrontendClass &OutClass) const =0
Return an FMetasoundFrontendClass representing an set variable node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetInputClassMetadata (const FName &InDataType) const =0
Below are class metadata accessor for the special nodes related to a data type.
virtual FLiteralAssignmentFunction GetLiteralAssignmentFunction (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetOutputClassMetadata (const FName &InDataType) const =0
virtual const IParameterAssignmentFunction & GetRawAssignmentFunction (const FName &InDataType) const =0
virtual void GetRegisteredDataTypeNames (TArray< FName > &OutNames) const =0
Provides all names of registered DataTypes.
virtual UClass * GetUClassForDataType (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetVariableAccessorClassMetadata (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetVariableClassMetadata (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetVariableDeferredAccessorClassMetadata (const FName &InDataType) const =0
virtual TSharedPtr< const FNodeClassMetadata > GetVariableMutatorClassMetadata (const FName &InDataType) const =0
virtual bool IsLiteralTypeSupported (const FName &InDataType, ELiteralType InLiteralType) const =0
virtual bool IsLiteralTypeSupported (const FName &InDataType, EMetasoundFrontendLiteralType InLiteralType) const =0
virtual bool IsRegistered (const FName &InDataType) const =0
Returns whether or not a DataType is registered with the given name.
virtual bool IsUObjectProxyFactory (UObject *InObject) const =0
virtual bool IsValidUObjectForDataType (const FName &InDataTypeName, const UObject *InUObject) const =0
virtual void IterateDataTypeInfo (TFunctionRef< void(const FDataTypeRegistryInfo &)> InFunction) const =0
Iterates all registered data type info.
virtual bool RegisterDataType (TUniquePtr< IDataTypeRegistryEntry > &&InEntry)=0
Register a data type.
UE_DEPRECATED (5.6, "Create constructor input nodes with FNodeData") virtual TUniquePtr< INode > CreateConstructorInputNode(const FName &InInputType
UE_DEPRECATED (5.6, "Create input nodes with FNodeData") virtual TUniquePtr< INode > CreateInputNode(const FName &InInputType
Below are node creation methods for creation special nodes related to an individual data type.
UE_DEPRECATED (5.6, "Create output nodes with FNodeData") virtual TUniquePtr< INode > CreateConstructorOutputNode(const FName &InDataTypeName
UE_DEPRECATED (5.6, "Create output nodes with FNodeData") virtual TUniquePtr< INode > CreateOutputNode(const FName &InDataTypeName
UE_DEPRECATED (5.6, "Create variable accessor nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableAccessorNode(const FName &InDataType
UE_DEPRECATED (5.6, "Create variable deferred accessor nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableDeferredAccessorNode(const FName &InDataType
UE_DEPRECATED (5.6, "Create variable mutator nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableMutatorNode(const FName &InDataType
UE_DEPRECATED (5.6, "Create Variable Node with FNodeData") virtual TUniquePtr< INode > CreateVariableNode(const FName &InDataType
UE_DEPRECATED (5.6, "Direct creation of literal nodes will no longer be supported") virtual TUniquePtr< INode > CreateLiteralNode(const FName &InLiteralType
UE_DEPRECATED (5.6, "Direct creation of receive nodes will no longer be supported") virtual TUniquePtr< INode > CreateReceiveNode(const FName &InDataType
Static Public Member Functions
static METASOUNDFRONTEND_API IDataTypeRegistry & Get ()
Data Fields
FInputNodeConstructorParams &&InParams const = 0
FLiteralNodeConstructorParams &&InParams const = 0
FOutputNodeConstructorParams &&InParams const = 0
const FNodeInitData & const = 0
FVariableNodeConstructorParams &&InParams const = 0
const FNodeInitData &InParams const = 0
Detailed Description
Definition at line 294 of file MetasoundFrontendDataTypeRegistry.h.
Constructor & Destructor Documentation
~IDataTypeRegistry()
virtual Metasound::Frontend::IDataTypeRegistry::~IDataTypeRegistry () virtual default
Member Function Documentation
CreateConstructorInputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateConstructorInputNode (const FName & InInputType, FNodeData InNodeData) const pure virtual
References const, and CreateConstructorInputNode().
Referenced by CreateConstructorInputNode(), and UE_DEPRECATED().
CreateConstructorOutputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateConstructorOutputNode (const FName & InDataTypeName, FNodeData InNodeData) const pure virtual
References const, and CreateConstructorOutputNode().
Referenced by CreateConstructorOutputNode(), and UE_DEPRECATED().
CreateDataChannel()
virtual TSharedPtr< IDataChannel, ESPMode::ThreadSafe > Metasound::Frontend::IDataTypeRegistry::CreateDataChannel (const FName & InDataType, const FOperatorSettings & InOperatorSettings) const pure virtual
CreateDataReference()
virtual TOptional< FAnyDataReference > Metasound::Frontend::IDataTypeRegistry::CreateDataReference (const FName & InDataType, EDataReferenceAccessType InAccessType, const FLiteral & InLiteral, const FOperatorSettings & InOperatorSettings) const pure virtual
Create a data reference of the data type given a literal.
If not supported, the result will be not be set.
CreateDefaultLiteral()
virtual FLiteral Metasound::Frontend::IDataTypeRegistry::CreateDefaultLiteral (const FName & InDataType) const pure virtual
CreateInputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateInputNode (const FName & InInputType, FNodeData InNodeData) const pure virtual
References const, and CreateInputNode().
Referenced by CreateInputNode().
CreateLiteralFromUObject()
virtual FLiteral Metasound::Frontend::IDataTypeRegistry::CreateLiteralFromUObject (const FName & InDataType, UObject * InObject) const pure virtual
CreateLiteralFromUObjectArray()
virtual FLiteral Metasound::Frontend::IDataTypeRegistry::CreateLiteralFromUObjectArray (const FName & InDataType, const TArray< UObject * > & InObjectArray) const pure virtual
CreateOutputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateOutputNode (const FName & InDataTypeName, FNodeData InNodeData) const pure virtual
References const, and CreateOutputNode().
Referenced by CreateOutputNode().
CreateProxyFromUObject()
virtual TSharedPtr< Audio::IProxyData > Metasound::Frontend::IDataTypeRegistry::CreateProxyFromUObject (const FName & InDataType, UObject * InObject) const pure virtual
CreateVariableAccessorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateVariableAccessorNode (const FName & InDataType, FNodeData InNodeData) const pure virtual
References const, and CreateVariableAccessorNode().
Referenced by CreateVariableAccessorNode(), and UE_DEPRECATED().
CreateVariableDeferredAccessorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateVariableDeferredAccessorNode (const FName & InDataType, FNodeData InNodeData) const pure virtual
References const, and CreateVariableDeferredAccessorNode().
Referenced by CreateVariableDeferredAccessorNode(), and UE_DEPRECATED().
CreateVariableMutatorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateVariableMutatorNode (const FName & InDataType, FNodeData InNodeData) const pure virtual
References const, and CreateVariableMutatorNode().
Referenced by CreateVariableMutatorNode().
CreateVariableNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistry::CreateVariableNode (const FName & InDataType, FLiteral InLiteral, FNodeData InNodeData) const pure virtual
References const, and CreateVariableNode().
Referenced by CreateVariableNode().
FindDataTypeRegistryEntry()
virtual const IDataTypeRegistryEntry * Metasound::Frontend::IDataTypeRegistry::FindDataTypeRegistryEntry (const FName & InDataTypeName) const pure virtual
Get()
METASOUNDFRONTEND_API IDataTypeRegistry & Metasound::Frontend::IDataTypeRegistry::Get () static
References UE_API.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
GetConstructorInputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetConstructorInputClassMetadata (const FName & InDataType) const pure virtual
GetConstructorOutputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetConstructorOutputClassMetadata (const FName & InDataType) const pure virtual
GetDataTypeInfo() [1/2]
virtual bool Metasound::Frontend::IDataTypeRegistry::GetDataTypeInfo (const FName & InDataType, FDataTypeRegistryInfo & OutInfo) const pure virtual
Returns DataType info associated with the provided DataType name.
GetDataTypeInfo() [2/2]
virtual bool Metasound::Frontend::IDataTypeRegistry::GetDataTypeInfo (const UObject * InObject, FDataTypeRegistryInfo & OutInfo) const pure virtual
Returns DataType info associated with the provided object.
GetDesiredLiteralType()
virtual ELiteralType Metasound::Frontend::IDataTypeRegistry::GetDesiredLiteralType (const FName & InDataType) const pure virtual
GetEnumInterfaceForDataType()
virtual TSharedPtr< const IEnumDataTypeInterface > Metasound::Frontend::IDataTypeRegistry::GetEnumInterfaceForDataType (const FName & InDataType) const pure virtual
Return the enum interface for a data type.
If the data type does not have an enum interface, returns a nullptr.
GetFrontendConstructorInputClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendConstructorInputClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an input node of the data type.
GetFrontendConstructorOutputClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendConstructorOutputClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an output node of the data type.
GetFrontendInputClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendInputClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an input node of the data type.
GetFrontendLiteralClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendLiteralClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing a variable node of the data type.
GetFrontendOutputClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendOutputClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an output node of the data type.
GetFrontendVariableAccessorClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendVariableAccessorClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an get variable node of the data type.
GetFrontendVariableClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendVariableClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an init variable node of the data type.
GetFrontendVariableDeferredAccessorClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendVariableDeferredAccessorClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an get delayed variable node of the data type.
GetFrontendVariableMutatorClass()
virtual bool Metasound::Frontend::IDataTypeRegistry::GetFrontendVariableMutatorClass (const FName & InDataType, FMetasoundFrontendClass & OutClass) const pure virtual
Return an FMetasoundFrontendClass representing an set variable node of the data type.
GetInputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetInputClassMetadata (const FName & InDataType) const pure virtual
Below are class metadata accessor for the special nodes related to a data type.
GetLiteralAssignmentFunction()
virtual FLiteralAssignmentFunction Metasound::Frontend::IDataTypeRegistry::GetLiteralAssignmentFunction (const FName & InDataType) const pure virtual
GetOutputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetOutputClassMetadata (const FName & InDataType) const pure virtual
GetRawAssignmentFunction()
virtual const IParameterAssignmentFunction & Metasound::Frontend::IDataTypeRegistry::GetRawAssignmentFunction (const FName & InDataType) const pure virtual
GetRegisteredDataTypeNames()
virtual void Metasound::Frontend::IDataTypeRegistry::GetRegisteredDataTypeNames (TArray< FName > & OutNames) const pure virtual
Provides all names of registered DataTypes.
GetUClassForDataType()
virtual UClass * Metasound::Frontend::IDataTypeRegistry::GetUClassForDataType (const FName & InDataType) const pure virtual
GetVariableAccessorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetVariableAccessorClassMetadata (const FName & InDataType) const pure virtual
GetVariableClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetVariableClassMetadata (const FName & InDataType) const pure virtual
GetVariableDeferredAccessorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetVariableDeferredAccessorClassMetadata (const FName & InDataType) const pure virtual
GetVariableMutatorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistry::GetVariableMutatorClassMetadata (const FName & InDataType) const pure virtual
IsLiteralTypeSupported() [1/2]
virtual bool Metasound::Frontend::IDataTypeRegistry::IsLiteralTypeSupported (const FName & InDataType, ELiteralType InLiteralType) const pure virtual
IsLiteralTypeSupported() [2/2]
virtual bool Metasound::Frontend::IDataTypeRegistry::IsLiteralTypeSupported (const FName & InDataType, EMetasoundFrontendLiteralType InLiteralType) const pure virtual
IsRegistered()
virtual bool Metasound::Frontend::IDataTypeRegistry::IsRegistered (const FName & InDataType) const pure virtual
Returns whether or not a DataType is registered with the given name.
IsUObjectProxyFactory()
virtual bool Metasound::Frontend::IDataTypeRegistry::IsUObjectProxyFactory (UObject * InObject) const pure virtual
IsValidUObjectForDataType()
virtual bool Metasound::Frontend::IDataTypeRegistry::IsValidUObjectForDataType (const FName & InDataTypeName, const UObject * InUObject) const pure virtual
IterateDataTypeInfo()
virtual void Metasound::Frontend::IDataTypeRegistry::IterateDataTypeInfo (TFunctionRef< void(const FDataTypeRegistryInfo &)> InFunction) const pure virtual
Iterates all registered data type info.
RegisterDataType()
virtual bool Metasound::Frontend::IDataTypeRegistry::RegisterDataType (TUniquePtr< IDataTypeRegistryEntry > && InEntry) pure virtual
Register a data type.
Parameters
InName - Name of data type.
InEntry - TUniquePtr to data type registry entry.
Returns
True on success, false on failure.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
UE_DEPRECATED() [1/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create constructor input nodes with FNodeData") const &
References const, CreateConstructorInputNode(), and UE_DEPRECATED().
UE_DEPRECATED() [2/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create input nodes with FNodeData") const &
Below are node creation methods for creation special nodes related to an individual data type.
These nodes power core features of metasounds such as Inputs, Outputs, and Variables.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create output nodes with FNodeData") const &
References const, CreateConstructorOutputNode(), and UE_DEPRECATED().
UE_DEPRECATED() [4/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create output nodes with FNodeData") const &
References UE_DEPRECATED().
UE_DEPRECATED() [5/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create variable accessor nodes with FNodeData") const &
References const, CreateVariableAccessorNode(), and UE_DEPRECATED().
UE_DEPRECATED() [6/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create variable deferred accessor nodes with FNodeData") const &
References const, CreateVariableDeferredAccessorNode(), and UE_DEPRECATED().
UE_DEPRECATED() [7/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create variable mutator nodes with FNodeData") const &
References UE_DEPRECATED().
UE_DEPRECATED() [8/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Create Variable Node with FNodeData") const &
References UE_DEPRECATED().
UE_DEPRECATED() [9/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Direct creation of literal nodes will no longer be supported") const &
References UE_DEPRECATED().
UE_DEPRECATED() [10/10]
Metasound::Frontend::IDataTypeRegistry::UE_DEPRECATED (5. 6, "Direct creation of receive nodes will no longer be supported") const &
References UE_DEPRECATED().
Field Documentation
const [1/6]
const FNodeInitData &InParams Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 399 of file MetasoundFrontendDataTypeRegistry.h.
Referenced by CreateConstructorInputNode(), CreateConstructorOutputNode(), CreateInputNode(), CreateOutputNode(), CreateVariableAccessorNode(), CreateVariableDeferredAccessorNode(), CreateVariableMutatorNode(), CreateVariableNode(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
const [2/6]
FLiteralNodeConstructorParams&& InParams Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 407 of file MetasoundFrontendDataTypeRegistry.h.
const [3/6]
FOutputNodeConstructorParams&& InParams Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 410 of file MetasoundFrontendDataTypeRegistry.h.
const [4/6]
const FNodeInitData& Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 418 of file MetasoundFrontendDataTypeRegistry.h.
const [5/6]
FVariableNodeConstructorParams&& InParams Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 421 of file MetasoundFrontendDataTypeRegistry.h.
const [6/6]
const FNodeInitData& InParams Metasound::Frontend::IDataTypeRegistry::const = 0
Definition at line 425 of file MetasoundFrontendDataTypeRegistry.h.
The documentation for this class was generated from the following file:
MetasoundFrontendDataTypeRegistry.h