Unreal Engine 5.6 C++ API: TextFilterUtils Namespace Reference
TextFilterUtils Namespace Reference
Data Structures
struct FNameBufferWithNumber
Functions
template<typename CharType>
void IntToStringBuffer (CharType *Dest, int32 Source, int32 MaxLen)
int32 NameStrincmp (const FName &Name, const FString &WideOther, const TArray< ANSICHAR > &AnsiOther, int32 Length)
Compare FNameEntry vs Wide or Ansi string.
bool TestBasicStringExpression (const FTextFilterString &InValue1, const FTextFilterString &InValue2, const ETextFilterTextComparisonMode InTextComparisonMode)
Utility function to perform a basic string test for the given values.
bool TestComplexExpression (const FTextFilterString &InValue1, const FTextFilterString &InValue2, const ETextFilterComparisonOperation InComparisonOperation, const ETextFilterTextComparisonMode InTextComparisonMode)
Utility function to perform a complex expression test for the given values.
bool TryConvertWideToAnsi (const FString &SourceWideString, TArray< ANSICHAR > &DestAnsiString)
Convert a wide string to ansi if all characters are ansi.
Function Documentation
IntToStringBuffer()
template<typename CharType> void TextFilterUtils::IntToStringBuffer (CharType * Dest, int32 Source, int32 MaxLen)
Definition at line 109 of file TextFilterUtils.h.
References Num, Source, and TCString< T >::Strncpy().
Referenced by TextFilterUtils::FNameBufferWithNumber::Init().
NameStrincmp()
int32 TextFilterUtils::NameStrincmp (const FName & Name, const FString & WideOther, const TArray< ANSICHAR > & AnsiOther, int32 Length)
Compare FNameEntry vs Wide or Ansi string.
References Name.
TestBasicStringExpression()
bool TextFilterUtils::TestBasicStringExpression (const FTextFilterString & InValue1, const FTextFilterString & InValue2, const ETextFilterTextComparisonMode InTextComparisonMode)
Utility function to perform a basic string test for the given values.
Referenced by FBasicStringFilterExpressionContext::TestBasicStringExpression(), and TTextFilter< ItemType >::FTextFilterExpressionContext::TestBasicStringExpression().
TestComplexExpression()
bool TextFilterUtils::TestComplexExpression (const FTextFilterString & InValue1, const FTextFilterString & InValue2, const ETextFilterComparisonOperation InComparisonOperation, const ETextFilterTextComparisonMode InTextComparisonMode)
Utility function to perform a complex expression test for the given values.
TryConvertWideToAnsi()
bool TextFilterUtils::TryConvertWideToAnsi (const FString & SourceWideString, TArray< ANSICHAR > & DestAnsiString)
Convert a wide string to ansi if all characters are ansi.