Unreal Engine 5.6 C++ API: TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention > Class Template Reference
TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
bool IsClosed () const
Check if the list is closed.
template<typename ContainerType>
void PopAllAndClose (ContainerType &Output)
Pop all items from the list and atomically close it.
bool PushIfNotClosed (T *NewItem)
Push an item onto the head of the list, unless the list is closed.
void Reset ()
Reset the list to the initial state.
Additional Inherited Members
Private Member Functions inherited from FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, 2 >
FLockFreePointerListLIFOBase ()=default
~FLockFreePointerListLIFOBase ()
FORCEINLINE uint64 GetState () const
FORCEINLINE bool IsEmpty () const
T * Pop ()
void PopAll (ContainerType &OutContainer)
void PopAllAndApply (FunctorType InFunctor)
void PopAllAndChangeState (ContainerType &OutContainer, TFunctionRef< uint64(uint64)> StateChange)
void Push (T *InPayload)
bool PushIf (T *InPayload, TFunctionRef< bool(uint64)> OkToPush)
void Reset ()
Detailed Description
template<class T, int TPaddingForCacheContention>
class TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >
Definition at line 958 of file LockFreeList.h.
Member Function Documentation
IsClosed()
template<class T, int TPaddingForCacheContention> bool TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::IsClosed () const inline nodiscard
Check if the list is closed.
Returns
true if the list is closed.
Definition at line 1002 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::GetState().
PopAllAndClose()
template<class T, int TPaddingForCacheContention> template<typename ContainerType> void TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::PopAllAndClose (ContainerType & Output) inline
Pop all items from the list and atomically close it.
Parameters
Output The array to hold the returned items. Must be empty.
Definition at line 987 of file LockFreeList.h.
References checkLockFreePointerList, FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndChangeState(), and State.
PushIfNotClosed()
template<class T, int TPaddingForCacheContention> bool TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::PushIfNotClosed (T * NewItem) inline
Push an item onto the head of the list, unless the list is closed.
Parameters
NewItem,the new item to push on the list, cannot be NULL
Returns
true if the item was pushed on the list, false if the list was closed.
Definition at line 976 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PushIf(), and State.
Reset()
template<class T, int TPaddingForCacheContention> void TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::Reset () inline
Reset the list to the initial state.
Not thread safe, but used for recycling when we know all users are gone.
Definition at line 965 of file LockFreeList.h.
References FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Reset().
The documentation for this class was generated from the following file:
LockFreeList.h