Unreal Engine 5.6 C++ API: UParticleModuleLocation_Seeded Class Reference
UParticleModuleLocation_Seeded Class Reference
#include "ParticleModuleLocation_Seeded.h"
Private Member Functions
virtual void EmitterLoopingNotify (FParticleEmitterInstance *Owner) override
GENERATED_UCLASS_BODY () UPROPERTY() struct FParticleRandomSeedInfo RandomSeedInfo
The random seed(s) to use for looking up values in StartLocation.
virtual FParticleRandomSeedInfo * GetRandomSeedInfo () override
Additional Inherited Members
Public Member Functions inherited from UParticleModuleLocation
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void Render3DPreview (const FPreviewContext &Context) override
virtual void Spawn (const FSpawnContext &Context) override
Protected Member Functions inherited from UParticleModuleLocation
virtual void SpawnEx (const FSpawnContext &Context, struct FRandomStream *InRandomStream)
Extended version of spawn, allows for using a random stream for distribution value retrieval.
Detailed Description
Definition at line 14 of file ParticleModuleLocation_Seeded.h.
Member Function Documentation
EmitterLoopingNotify()
virtual void UParticleModuleLocation_Seeded::EmitterLoopingNotify (FParticleEmitterInstance * Owner) override private virtual
References Owner.
GENERATED_UCLASS_BODY()
UParticleModuleLocation_Seeded::GENERATED_UCLASS_BODY () private
The random seed(s) to use for looking up values in StartLocation.
References Category, and UParticleModuleLocation::UPROPERTY().
GetRandomSeedInfo()
virtual FParticleRandomSeedInfo * UParticleModuleLocation_Seeded::GetRandomSeedInfo () inline override private virtual
Definition at line 24 of file ParticleModuleLocation_Seeded.h.
References GetRandomSeedInfo().
Referenced by GetRandomSeedInfo().
The documentation for this class was generated from the following file:
ParticleModuleLocation_Seeded.h