Unreal Engine 5.6 C++ API: FViewportClient Class Reference
FViewportClient Class Reference
An abstract interface to a viewport's client.
#include "ViewportClient.h"
Public Member Functions
virtual ~FViewportClient ()
virtual void Activated (FViewport *Viewport, const FWindowActivateEvent &InActivateEvent)
virtual void CapturedMouseMove (FViewport *InViewport, int32 InMouseX, int32 InMouseY)
Called when the mouse is moved while a window input capture is in effect.
virtual bool CaptureMouseOnLaunch ()
Gets whether or not the viewport captures the Mouse on launch of the application Technically this controls capture on the first window activate, so in situations where the application is launched but isn't activated the effect is delayed until activation.
virtual void CloseRequested (FViewport *Viewport)
virtual void ConditionalRestoreWorld (class UWorld *InWorld)
Restores GWorld to InWorld.
virtual class UWorld * ConditionalSetWorld ()
Sets GWorld to the appropriate world for this client.
virtual void Deactivated (FViewport *Viewport, const FWindowActivateEvent &InActivateEvent)
virtual void Draw (FViewport *Viewport, FCanvas *Canvas)
virtual EMouseCursor::Type GetCursor (FViewport *Viewport, int32 X, int32 Y)
Retrieves the cursor that should be displayed by the OS.
virtual float GetDPIScale () const
virtual const TArray< FString > * GetEnabledStats () const
Get a ptr to the enabled stats list.
virtual struct FEngineShowFlags * GetEngineShowFlags ()
virtual EMouseCaptureMode GetMouseCaptureMode () const
Gets the mouse capture behavior when the viewport is clicked.
virtual FStatHitchesData * GetStatHitchesData () const
Get a ptr to the stat unit data for this viewport.
virtual FStatUnitData * GetStatUnitData () const
Get a ptr to the stat unit data for this viewport.
virtual UWorld * GetWorld () const
virtual bool HandleNavigation (const uint32 InUserIndex, TSharedPtr< SWidget > InDestination)
Optionally do custom handling of a navigation.
virtual bool HideCursorDuringCapture () const
Gets whether or not the cursor is hidden when the viewport captures the mouse.
virtual bool IgnoreInput ()
Check whether we should ignore input.
virtual bool InputAxis (const FInputKeyEventArgs &Args)
Check an axis movement received by the viewport.
virtual bool InputChar (FViewport *Viewport, int32 ControllerId, TCHAR Character)
Check a character input received by the viewport.
virtual bool InputGesture (FViewport *Viewport, const FInputDeviceId DeviceId, EGestureEvent GestureType, const FVector2D &GestureDelta, bool bIsDirectionInvertedFromDevice, const uint64 Timestamp)
Check a gesture event received by the viewport.
virtual bool InputKey (const FInputKeyEventArgs &EventArgs)
Check a key event received by the viewport.
virtual bool InputMotion (FViewport *Viewport, const FInputDeviceId DeviceId, const FVector &Tilt, const FVector &RotationRate, const FVector &Gravity, const FVector &Acceleration, const uint64 Timestamp)
Each frame, the input system will update the motion data.
virtual bool InputTouch (FViewport *Viewport, const FInputDeviceId DeviceId, uint32 Handle, ETouchType::Type Type, const FVector2D &TouchLocation, float Force, uint32 TouchpadIndex, const uint64 Timestamp)
Check a key event received by the viewport.
virtual bool IsFocused (FViewport *Viewport)
virtual bool IsInGameView () const
Returns true if this viewport is excluding non-game elements from its display.
virtual bool IsInPermanentCapture ()
virtual bool IsOrtho () const
Returns true if this viewport is orthogonal.
virtual bool IsStatEnabled (const FString &InName) const
Check whether a specific stat is enabled for this viewport.
virtual bool LockDuringCapture ()
Gets whether or not the cursor is locked to the viewport when the viewport captures the mouse.
virtual void LostFocus (FViewport *Viewport)
virtual TOptional< TSharedRef< SWidget > > MapCursor (FViewport *Viewport, const FCursorReply &CursorReply)
Called to map a cursor reply to an actual widget to render.
virtual void MouseEnter (FViewport *Viewport, int32 x, int32 y)
virtual void MouseLeave (FViewport *Viewport)
virtual void MouseMove (FViewport *Viewport, int32 X, int32 Y)
virtual FPopupMethodReply OnQueryPopupMethod () const
Should we make new windows for popups or create an overlay in the current window.
virtual bool OverrideHighResScreenshotCaptureRegion (FIntRect &OutCaptureRegion)
Allow viewport client to override the current capture region.
virtual void Precache ()
virtual void ProcessAccumulatedPointerInput (FViewport *InViewport)
Called from slate when input is finished for this frame, and we should process any queued mouse moves.
virtual bool ProcessScreenShots (FViewport *Viewport)
virtual TOptional< bool > QueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void ReceivedFocus (FViewport *Viewport)
virtual void RedrawRequested (FViewport *Viewport)
virtual void RequestInvalidateHitProxy (FViewport *Viewport)
virtual bool RequiresHitProxyStorage ()
virtual bool RequiresKeyboardInput () const
Determine if the viewport client is going to need any keyboard input.
virtual bool RequiresUncapturedAxisInput () const
Determines whether this viewport client should receive calls to InputAxis() if the game's window is not currently capturing the mouse.
virtual void SetEnabledStats (const TArray< FString > &InEnabledStats)
Sets all the stats that should be enabled for the viewport.
virtual void SetIsSimulateInEditorViewport (bool bInIsSimulateInEditorViewport)
virtual void SetShowStats (bool bWantStats)
Sets whether stats should be visible for the viewport.
virtual bool ShouldAlwaysLockMouse ()
Gets whether or not the cursor should always be locked to the viewport.
virtual bool ShouldDPIScaleSceneCanvas () const
UE_DEPRECATED (5.6, "This function will be removed in a future release.") virtual bool WantsPollingMouseMovement(void) const
UE_DEPRECATED (5.6, "Use the version of InputAxis which takes in a FInputKeyEventArgs instead.") 1 virtual bool InputAxis(FViewport *Viewport
Check an axis movement received by the viewport.
UE_DEPRECATED (5.6, "Use the version which takes a uint64 timestamp instead") 1 virtual bool InputTouch(FViewport *Viewport
Check a key event received by the viewport.
UE_DEPRECATED (5.6, "Use the version which takes in a FInputDeviceId and a timestamp instead") 1 virtual bool InputMotion(FViewport *Viewport
Each frame, the input system will update the motion data.
UE_DEPRECATED (5.6, "Use the version which takes in a FInputDeviceId and uint64 Timestamp instead.") 1 virtual bool InputGesture(FViewport *Viewport
Check a gesture event received by the viewport.
virtual bool WindowCloseRequested ()
Called when the top level window associated with the viewport has been requested to close.
Data Fields
FInputDeviceId FKey float float int32 bool bGamepad = false) final
int32 ControllerId
FInputDeviceId FKey float Delta
FInputDeviceId FKey float float DeltaTime
int32 uint32 ETouchType::Type const FVector2D float FDateTime DeviceTimestamp
int32 uint32 ETouchType::Type const FVector2D float FDateTime uint32 TouchpadIndex final
EGestureEvent const FVector2D bool bIsDirectionInvertedFromDevice final
int32 const FVector const FVector const FVector const FVector &Acceleration final
int32 uint32 ETouchType::Type const FVector2D float Force
EGestureEvent const FVector2D & GestureDelta
EGestureEvent GestureType
int32 const FVector const FVector const FVector & Gravity
int32 uint32 Handle
FInputDeviceId InputDevice
FInputDeviceId FKey Key
FInputDeviceId FKey float float int32 NumSamples = 1
int32 const FVector const FVector & RotationRate
int32 const FVector & Tilt
int32 uint32 ETouchType::Type const FVector2D & TouchLocation
int32 uint32 ETouchType::Type Type
Detailed Description
An abstract interface to a viewport's client.
The viewport's client processes input received by the viewport, and draws the viewport.
Definition at line 27 of file ViewportClient.h.
Constructor & Destructor Documentation
~FViewportClient()
virtual FViewportClient::~FViewportClient () inline virtual
Definition at line 30 of file ViewportClient.h.
Member Function Documentation
Activated()
virtual void FViewportClient::Activated (FViewport * Viewport, const FWindowActivateEvent & InActivateEvent) inline virtual
Definition at line 258 of file ViewportClient.h.
CapturedMouseMove()
virtual void FViewportClient::CapturedMouseMove (FViewport * InViewport, int32 InMouseX, int32 InMouseY) inline virtual
Called when the mouse is moved while a window input capture is in effect.
Parameters
InViewport Viewport that captured the mouse input
InMouseX New mouse cursor X coordinate
InMouseY New mouse cursor Y coordinate
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 222 of file ViewportClient.h.
CaptureMouseOnLaunch()
virtual bool FViewportClient::CaptureMouseOnLaunch () inline virtual
Gets whether or not the viewport captures the Mouse on launch of the application Technically this controls capture on the first window activate, so in situations where the application is launched but isn't activated the effect is delayed until activation.
Definition at line 374 of file ViewportClient.h.
CloseRequested()
virtual void FViewportClient::CloseRequested (FViewport * Viewport) inline virtual
Definition at line 278 of file ViewportClient.h.
ConditionalRestoreWorld()
virtual void FViewportClient::ConditionalRestoreWorld (class UWorld * InWorld) inline virtual
Restores GWorld to InWorld.
Parameters
InWorld The world to restore
Reimplemented in FLevelEditorViewportClient.
Definition at line 318 of file ViewportClient.h.
ConditionalSetWorld()
virtual class UWorld * FViewportClient::ConditionalSetWorld () inline virtual
Sets GWorld to the appropriate world for this client.
Returns
the previous GWorld
Reimplemented in FLevelEditorViewportClient.
Definition at line 311 of file ViewportClient.h.
Deactivated()
virtual void FViewportClient::Deactivated (FViewport * Viewport, const FWindowActivateEvent & InActivateEvent) inline virtual
Definition at line 259 of file ViewportClient.h.
Draw()
virtual void FViewportClient::Draw (FViewport * Viewport, FCanvas * Canvas) inline virtual
Reimplemented in FEditorViewportClient.
Definition at line 34 of file ViewportClient.h.
GetCursor()
virtual EMouseCursor::Type FViewportClient::GetCursor (FViewport * Viewport, int32 X, int32 Y) inline virtual
Retrieves the cursor that should be displayed by the OS.
Parameters
Viewport the viewport that contains the cursor
X the x position of the cursor
Y the Y position of the cursor
Returns
the cursor that the OS should display
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 238 of file ViewportClient.h.
References EMouseCursor::Default, X, and Y.
GetDPIScale()
virtual float FViewportClient::GetDPIScale () const inline virtual
Returns
The DPI Scale of this viewport
Reimplemented in FCommonViewportClient.
Definition at line 409 of file ViewportClient.h.
GetEnabledStats()
virtual const TArray< FString > * FViewportClient::GetEnabledStats () const inline virtual
Get a ptr to the enabled stats list.
Reimplemented in FEditorViewportClient.
Definition at line 341 of file ViewportClient.h.
GetEngineShowFlags()
virtual struct FEngineShowFlags * FViewportClient::GetEngineShowFlags () inline virtual
Reimplemented in FEditorViewportClient.
Definition at line 37 of file ViewportClient.h.
GetMouseCaptureMode()
virtual EMouseCaptureMode FViewportClient::GetMouseCaptureMode () const inline virtual
Gets the mouse capture behavior when the viewport is clicked.
Definition at line 366 of file ViewportClient.h.
Referenced by IsInPermanentCapture().
GetStatHitchesData()
virtual FStatHitchesData * FViewportClient::GetStatHitchesData () const inline virtual
Get a ptr to the stat unit data for this viewport.
Reimplemented in FEditorViewportClient.
Definition at line 336 of file ViewportClient.h.
GetStatUnitData()
virtual FStatUnitData * FViewportClient::GetStatUnitData () const inline virtual
Get a ptr to the stat unit data for this viewport.
Reimplemented in FEditorViewportClient.
Definition at line 331 of file ViewportClient.h.
GetWorld()
virtual UWorld * FViewportClient::GetWorld () const inline virtual
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 36 of file ViewportClient.h.
HandleNavigation()
virtual bool FViewportClient::HandleNavigation (const uint32 InUserIndex, TSharedPtr< SWidget > InDestination) inline virtual
Optionally do custom handling of a navigation.
Definition at line 399 of file ViewportClient.h.
HideCursorDuringCapture()
virtual bool FViewportClient::HideCursorDuringCapture () const inline virtual
Gets whether or not the cursor is hidden when the viewport captures the mouse.
Definition at line 389 of file ViewportClient.h.
IgnoreInput()
virtual bool FViewportClient::IgnoreInput () inline virtual
Check whether we should ignore input.
Definition at line 361 of file ViewportClient.h.
InputAxis()
virtual bool FViewportClient::InputAxis (const FInputKeyEventArgs & Args) inline virtual
Check an axis movement received by the viewport.
If this viewport client uses this input and wants to consume it (stop it from being passed along to further viewports) then it should return true.
Parameters
Args The input event arguments for this axis movement.
Returns
True to consume the axis movement, false to pass it on.
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 78 of file ViewportClient.h.
References InputAxis().
Referenced by InputAxis(), and UE_DEPRECATED().
InputChar()
virtual bool FViewportClient::InputChar (FViewport * Viewport, int32 ControllerId, TCHAR Character) inline virtual
Check a character input received by the viewport.
If the viewport client uses the character, it should return true to consume it.
Parameters
Viewport - The viewport which the axis movement is from.
ControllerId - The controller which the axis movement is from.
Character - The character.
Returns
True to consume the character, false to pass it on.
Definition at line 88 of file ViewportClient.h.
References Character, and ControllerId.
InputGesture()
virtual bool FViewportClient::InputGesture (FViewport * Viewport, const FInputDeviceId DeviceId, EGestureEvent GestureType, const FVector2D & GestureDelta, bool bIsDirectionInvertedFromDevice, const uint64 Timestamp) inline virtual
Check a gesture event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
Viewport - The viewport which the event is from.
DeviceId - The input device id from which this gesture came from
GestureType - The type of gesture being input
GestureDelta - Delta values of this gesture from the previous instance of it
Timestamp - The timestamp of when this input event was originally polled in the form of CPU cycles.
Returns
True to consume the gesture event, false to pass it on.
Reimplemented in FEditorViewportClient.
Definition at line 155 of file ViewportClient.h.
References GestureDelta, GestureType, and InputGesture().
Referenced by InputGesture().
InputKey()
virtual bool FViewportClient::InputKey (const FInputKeyEventArgs & EventArgs) inline virtual
Check a key event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
EventArgs - The Input event args.
Returns
True to consume the key event, false to pass it on.
Reimplemented in FDataflowConstructionViewportClient, FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 46 of file ViewportClient.h.
InputMotion()
virtual bool FViewportClient::InputMotion (FViewport * Viewport, const FInputDeviceId DeviceId, const FVector & Tilt, const FVector & RotationRate, const FVector & Gravity, const FVector & Acceleration, const uint64 Timestamp) inline virtual
Each frame, the input system will update the motion data.
Parameters
Viewport - The viewport which the key event is from.
DeviceId - The input device which this event is from
Tilt The current orientation of the device
RotationRate How fast the tilt is changing
Gravity Describes the current gravity of the device
Acceleration Describes the acceleration of the device
Timestamp The timestamp of when this input event was originally polled in the form of CPU cycles.
Returns
True to consume the motion event, false to pass it on.
Definition at line 192 of file ViewportClient.h.
References Acceleration, FVector, Gravity, InputMotion(), RotationRate, and Tilt.
Referenced by InputMotion().
InputTouch()
virtual bool FViewportClient::InputTouch (FViewport * Viewport, const FInputDeviceId DeviceId, uint32 Handle, ETouchType::Type Type, const FVector2D & TouchLocation, float Force, uint32 TouchpadIndex, const uint64 Timestamp) inline virtual
Check a key event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
Viewport - The viewport which the event is from.
DeviceId - The input device id from which this event is from
Handle - Identifier unique to this touch event
Type - What kind of touch event this is (see ETouchType)
TouchLocation - Screen position of the touch
Force - How hard the touch is
TouchpadIndex - For devices with multiple touchpads, this is the index of which one
Timestamp - The timestamp of when this input event was originally polled in the form of CPU cycles.
Returns
True to consume the key event, false to pass it on.
Definition at line 119 of file ViewportClient.h.
References Force, Handle, InputTouch(), TouchLocation, and Type.
Referenced by InputTouch().
IsFocused()
virtual bool FViewportClient::IsFocused (FViewport * Viewport) inline virtual
Definition at line 256 of file ViewportClient.h.
IsInGameView()
virtual bool FViewportClient::IsInGameView () const inline virtual
Returns true if this viewport is excluding non-game elements from its display.
Reimplemented in FEditorViewportClient.
Definition at line 304 of file ViewportClient.h.
IsInPermanentCapture()
virtual bool FViewportClient::IsInPermanentCapture () inline virtual
Definition at line 261 of file ViewportClient.h.
References GetMouseCaptureMode(), and GIsEditor.
IsOrtho()
virtual bool FViewportClient::IsOrtho () const inline virtual
Returns true if this viewport is orthogonal.
If hit proxies are ever used in-game, this will need to be overridden correctly in GameViewportClient.
Reimplemented in FEditorViewportClient.
Definition at line 299 of file ViewportClient.h.
IsStatEnabled()
virtual bool FViewportClient::IsStatEnabled (const FString & InName) const inline virtual
Check whether a specific stat is enabled for this viewport.
Reimplemented in FEditorViewportClient.
Definition at line 351 of file ViewportClient.h.
References InName.
LockDuringCapture()
virtual bool FViewportClient::LockDuringCapture () inline virtual
Gets whether or not the cursor is locked to the viewport when the viewport captures the mouse.
Definition at line 379 of file ViewportClient.h.
LostFocus()
virtual void FViewportClient::LostFocus (FViewport * Viewport) inline virtual
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 254 of file ViewportClient.h.
MapCursor()
virtual TOptional< TSharedRef< SWidget > > FViewportClient::MapCursor (FViewport * Viewport, const FCursorReply & CursorReply) virtual
Called to map a cursor reply to an actual widget to render.
Returns
the widget that should be rendered for this cursor, return TOptional<TSharedRef<SWidget>>() if no mapping.
MouseEnter()
virtual void FViewportClient::MouseEnter (FViewport * Viewport, int32 x, int32 y) inline virtual
Reimplemented in FEditorViewportClient.
Definition at line 209 of file ViewportClient.h.
MouseLeave()
virtual void FViewportClient::MouseLeave (FViewport * Viewport) inline virtual
Reimplemented in FEditorViewportClient.
Definition at line 211 of file ViewportClient.h.
MouseMove()
virtual void FViewportClient::MouseMove (FViewport * Viewport, int32 X, int32 Y) inline virtual
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 213 of file ViewportClient.h.
References X, and Y.
OnQueryPopupMethod()
virtual FPopupMethodReply FViewportClient::OnQueryPopupMethod () const virtual
Should we make new windows for popups or create an overlay in the current window.
OverrideHighResScreenshotCaptureRegion()
virtual bool FViewportClient::OverrideHighResScreenshotCaptureRegion (FIntRect & OutCaptureRegion) inline virtual
Allow viewport client to override the current capture region.
Parameters
OutCaptureRegion Ref to rectangle where we will write the overridden region
Returns
true if capture region has been overridden, false otherwise
Reimplemented in FLevelEditorViewportClient.
Definition at line 326 of file ViewportClient.h.
Precache()
virtual void FViewportClient::Precache () inline virtual
Definition at line 31 of file ViewportClient.h.
ProcessAccumulatedPointerInput()
virtual void FViewportClient::ProcessAccumulatedPointerInput (FViewport * InViewport) inline virtual
Called from slate when input is finished for this frame, and we should process any queued mouse moves.
Reimplemented in FEditorViewportClient.
Definition at line 227 of file ViewportClient.h.
ProcessScreenShots()
virtual bool FViewportClient::ProcessScreenShots (FViewport * Viewport) inline virtual
Reimplemented in FEditorViewportClient.
Definition at line 35 of file ViewportClient.h.
QueryShowFocus()
virtual TOptional< bool > FViewportClient::QueryShowFocus (const EFocusCause InFocusCause) const inline virtual
Called to determine if we should render the focus brush.
Parameters
InFocusCause The cause of focus
Definition at line 252 of file ViewportClient.h.
ReceivedFocus()
virtual void FViewportClient::ReceivedFocus (FViewport * Viewport) inline virtual
Reimplemented in FEditorViewportClient, and FLevelEditorViewportClient.
Definition at line 255 of file ViewportClient.h.
RedrawRequested()
virtual void FViewportClient::RedrawRequested (FViewport * Viewport) virtual
Reimplemented in FEditorViewportClient.
RequestInvalidateHitProxy()
virtual void FViewportClient::RequestInvalidateHitProxy (FViewport * Viewport) virtual
Reimplemented in FEditorViewportClient.
RequiresHitProxyStorage()
virtual bool FViewportClient::RequiresHitProxyStorage () inline virtual
Definition at line 280 of file ViewportClient.h.
RequiresKeyboardInput()
virtual bool FViewportClient::RequiresKeyboardInput () const inline virtual
Determine if the viewport client is going to need any keyboard input.
Returns
true if keyboard input is needed
Definition at line 292 of file ViewportClient.h.
RequiresUncapturedAxisInput()
virtual bool FViewportClient::RequiresUncapturedAxisInput () const inline virtual
Determines whether this viewport client should receive calls to InputAxis() if the game's window is not currently capturing the mouse.
Used by the UI system to easily receive calls to InputAxis while the viewport's mouse capture is disabled.
Definition at line 286 of file ViewportClient.h.
SetEnabledStats()
virtual void FViewportClient::SetEnabledStats (const TArray< FString > & InEnabledStats) inline virtual
Sets all the stats that should be enabled for the viewport.
Reimplemented in FEditorViewportClient.
Definition at line 346 of file ViewportClient.h.
SetIsSimulateInEditorViewport()
virtual void FViewportClient::SetIsSimulateInEditorViewport (bool bInIsSimulateInEditorViewport) inline virtual
Reimplemented in FLevelEditorViewportClient.
Definition at line 204 of file ViewportClient.h.
SetShowStats()
virtual void FViewportClient::SetShowStats (bool bWantStats) inline virtual
Sets whether stats should be visible for the viewport.
Reimplemented in FEditorViewportClient.
Definition at line 356 of file ViewportClient.h.
ShouldAlwaysLockMouse()
virtual bool FViewportClient::ShouldAlwaysLockMouse () inline virtual
Gets whether or not the cursor should always be locked to the viewport.
Definition at line 384 of file ViewportClient.h.
ShouldDPIScaleSceneCanvas()
virtual bool FViewportClient::ShouldDPIScaleSceneCanvas () const inline virtual
Returns
Whether or not the scene canvas should be scaled. Note: The debug canvas is always scaled
Definition at line 404 of file ViewportClient.h.
UE_DEPRECATED() [1/5]
FViewportClient::UE_DEPRECATED (5. 6, "This function will be removed in a future release.") const inline
Definition at line 206 of file ViewportClient.h.
UE_DEPRECATED() [2/5]
FViewportClient::UE_DEPRECATED (5. 6, "Use the version of InputAxis which takes in a FInputKeyEventArgs instead.")
Check an axis movement received by the viewport.
If the viewport client uses the movement, it should return true to consume it.
Parameters
Viewport - The viewport which the axis movement is from.
InputDevice - The input device that triggered this axis movement
Key - The name of the axis which moved.
Delta - The axis movement delta.
DeltaTime - The time since the last axis update.
NumSamples - The number of device samples that contributed to this Delta, useful for things like smoothing
bGamepad - input came from gamepad (ie xbox controller)
Returns
True to consume the axis movement, false to pass it on.
References InputAxis().
UE_DEPRECATED() [3/5]
FViewportClient::UE_DEPRECATED (5. 6, "Use the version which takes a uint64 timestamp instead")
Check a key event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
Viewport - The viewport which the event is from.
ControllerId - The controller which the key event is from.
Handle - Identifier unique to this touch event
Type - What kind of touch event this is (see ETouchType)
TouchLocation - Screen position of the touch
Force - How hard the touch is
DeviceTimestamp - Timestamp of the event
TouchpadIndex - For devices with multiple touchpads, this is the index of which one
Returns
True to consume the key event, false to pass it on.
UE_DEPRECATED() [4/5]
FViewportClient::UE_DEPRECATED (5. 6, "Use the version which takes in a FInputDeviceId and a timestamp instead")
Each frame, the input system will update the motion data.
Parameters
Viewport - The viewport which the key event is from.
ControllerId - The controller which the key event is from.
Tilt The current orientation of the device
RotationRate How fast the tilt is changing
Gravity Describes the current gravity of the device
Acceleration Describes the acceleration of the device
Returns
True to consume the motion event, false to pass it on.
UE_DEPRECATED() [5/5]
FViewportClient::UE_DEPRECATED (5. 6, "Use the version which takes in a FInputDeviceId and uint64 Timestamp instead.")
Check a gesture event received by the viewport.
If the viewport client uses the event, it should return true to consume it.
Parameters
Viewport - The viewport which the event is from.
GestureType -
Todo
desc
Parameters
GestureDelta -
Todo
desc
Returns
True to consume the gesture event, false to pass it on.
WindowCloseRequested()
virtual bool FViewportClient::WindowCloseRequested () inline virtual
Called when the top level window associated with the viewport has been requested to close.
At this point, the viewport has not been closed and the operation may be canceled. This may not called from PIE, Editor Windows, on consoles, or before the game ends from other methods. This is only when the platform specific window is closed.
Returns
True if the viewport may be closed, false otherwise.
Definition at line 276 of file ViewportClient.h.
Field Documentation
bGamepad
FInputDeviceId FKey float float int32 bool FViewportClient::bGamepad = false) final
Definition at line 68 of file ViewportClient.h.
Referenced by FEditorViewportClient::Internal_InputAxis().
ControllerId
int32 FViewportClient::ControllerId
Definition at line 104 of file ViewportClient.h.
Referenced by InputChar().
Delta
FInputDeviceId FKey float FViewportClient::Delta
Definition at line 65 of file ViewportClient.h.
Referenced by FEditorViewportClient::Internal_InputAxis().
DeltaTime
FInputDeviceId FKey float float FViewportClient::DeltaTime
Definition at line 66 of file ViewportClient.h.
Referenced by FEditorViewportClient::Internal_InputAxis(), FEditorViewportClient::UpdateCameraMovement(), and FLevelEditorViewportClient::UpdateViewForLockedActor().
DeviceTimestamp
int32 uint32 ETouchType::Type const FVector2D float FDateTime FViewportClient::DeviceTimestamp
Definition at line 104 of file ViewportClient.h.
final [1/3]
int32 uint32 ETouchType::Type const FVector2D float FDateTime uint32 TouchpadIndex FViewportClient::final
Definition at line 104 of file ViewportClient.h.
final [2/3]
EGestureEvent const FVector2D bool bIsDirectionInvertedFromDevice FViewportClient::final
Definition at line 141 of file ViewportClient.h.
final [3/3]
int32 const FVector const FVector const FVector const FVector& Acceleration FViewportClient::final
Definition at line 178 of file ViewportClient.h.
Force
int32 uint32 ETouchType::Type const FVector2D float FViewportClient::Force
Definition at line 104 of file ViewportClient.h.
Referenced by InputTouch().
GestureDelta
EGestureEvent const FVector2D& FViewportClient::GestureDelta
Definition at line 141 of file ViewportClient.h.
Referenced by FEditorViewportClient::InputGesture(), and InputGesture().
GestureType
EGestureEvent FViewportClient::GestureType
Definition at line 141 of file ViewportClient.h.
Referenced by FEditorViewportClient::InputGesture(), and InputGesture().
Gravity
int32 const FVector const FVector const FVector& FViewportClient::Gravity
Definition at line 178 of file ViewportClient.h.
Referenced by InputMotion().
Handle
int32 uint32 FViewportClient::Handle
Definition at line 104 of file ViewportClient.h.
Referenced by InputTouch().
InputDevice
FInputDeviceId FViewportClient::InputDevice
Definition at line 63 of file ViewportClient.h.
Key
FInputDeviceId FKey FViewportClient::Key
Definition at line 64 of file ViewportClient.h.
Referenced by FEditorViewportClient::InputTakeScreenshot(), FEditorViewportClient::Internal_InputAxis(), FEditorViewportClient::ProcessClick(), and FLevelEditorViewportClient::ProcessClick().
NumSamples
FInputDeviceId FKey float float int32 FViewportClient::NumSamples = 1
Definition at line 67 of file ViewportClient.h.
Referenced by FEditorViewportClient::Internal_InputAxis().
RotationRate
int32 const FVector const FVector& FViewportClient::RotationRate
Definition at line 178 of file ViewportClient.h.
Referenced by InputMotion().
Tilt
int32 const FVector& FViewportClient::Tilt
Definition at line 178 of file ViewportClient.h.
Referenced by InputMotion().
TouchLocation
int32 uint32 ETouchType::Type const FVector2D& FViewportClient::TouchLocation
Definition at line 104 of file ViewportClient.h.
Referenced by InputTouch().
Type
int32 uint32 ETouchType::Type FViewportClient::Type
Definition at line 104 of file ViewportClient.h.
Referenced by InputTouch().
The documentation for this class was generated from the following file:
ViewportClient.h