Unreal Engine 5.6 C++ API: Metasound::TArrayRandomGetOperator< ArrayType > Class Template Reference
Metasound::TArrayRandomGetOperator< ArrayType > Class Template Reference
#include "MetasoundArrayRandomNode.h"
Public Types
using ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
using FArrayDataReadReference = TDataReadReference<ArrayType>
using FArrayWeightReadReference = TDataReadReference<TArray<float>>
using FElementTypeWriteReference = TDataWriteReference<ElementType>
using WeightsArrayType = TArray<float>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArrayRandomGetOperator (const FBuildOperatorParams &InParams, const FTriggerReadRef &InTriggerNext, const FTriggerReadRef &InTriggerReset, const FArrayDataReadReference &InInputArray, const TDataReadReference< WeightsArrayType > &InInputWeightsArray, const FInt32ReadRef &InSeedValue, const FInt32ReadRef &InNoRepeatOrder, const FBoolReadRef &bInEnableSharedState, const FEnumSharedStateBehaviorType InSharedStateBehavior)
virtual ~TArrayRandomGetOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArrayRandomGetOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Member Functions
void CreateSharedStateArgs (InitSharedStateArgs &InOutStateArgs)
void ExecuteTriggerNext (int32 StartFrame)
void ExecuteTriggerReset (int32 StartFrame)
FGuid GetSameNodeInCompositionId (const FGuid &InNodeId, const TArray< FGuid > &InGraphHierarchy) const
FGuid GetSameNodeSharedStateId (const FGuid &InNodeId, const FGuid &InOtherId) const
Private Attributes
TUniquePtr< FArrayRandomGet > ArrayRandomGet
FBoolReadRef bEnableSharedState
bool bHasLoggedEmptyArrayWarning = false
bool bHasLoggedMissingGraphHierarchyWarning = false
bool bIsPreviewSound = false
FString DebugSharedStateBehaviorString
FString GraphName
FArrayDataReadReference InputArray
TDataReadReference< WeightsArrayType > InputWeightsArray
FGuid NodeId
FInt32ReadRef NoRepeatOrder
FInt32WriteRef OutIndex
TDataWriteReference< ElementType > OutValue
FInt32ReadRef SeedValue
FEnumSharedStateBehaviorType SharedStateBehavior
FGuid SharedStateId
FTriggerReadRef TriggerNext
FTriggerWriteRef TriggerOnNext
FTriggerWriteRef TriggerOnReset
FTriggerReadRef TriggerReset
Detailed Description
template<typename ArrayType>
class Metasound::TArrayRandomGetOperator< ArrayType >
Definition at line 167 of file MetasoundArrayRandomNode.h.
Member Typedef Documentation
ElementType
template<typename ArrayType> using Metasound::TArrayRandomGetOperator< ArrayType >::ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
Definition at line 173 of file MetasoundArrayRandomNode.h.
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArrayRandomGetOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 170 of file MetasoundArrayRandomNode.h.
FArrayWeightReadReference
template<typename ArrayType> using Metasound::TArrayRandomGetOperator< ArrayType >::FArrayWeightReadReference = TDataReadReference<TArray<float>>
Definition at line 171 of file MetasoundArrayRandomNode.h.
FElementTypeWriteReference
template<typename ArrayType> using Metasound::TArrayRandomGetOperator< ArrayType >::FElementTypeWriteReference = TDataWriteReference<ElementType>
Definition at line 174 of file MetasoundArrayRandomNode.h.
WeightsArrayType
template<typename ArrayType> using Metasound::TArrayRandomGetOperator< ArrayType >::WeightsArrayType = TArray<float>
Definition at line 172 of file MetasoundArrayRandomNode.h.
Constructor & Destructor Documentation
TArrayRandomGetOperator()
template<typename ArrayType> Metasound::TArrayRandomGetOperator< ArrayType >::TArrayRandomGetOperator (const FBuildOperatorParams & InParams, const FTriggerReadRef & InTriggerNext, const FTriggerReadRef & InTriggerReset, const FArrayDataReadReference & InInputArray, const TDataReadReference< WeightsArrayType > & InInputWeightsArray, const FInt32ReadRef & InSeedValue, const FInt32ReadRef & InNoRepeatOrder, const FBoolReadRef & bInEnableSharedState, const FEnumSharedStateBehaviorType InSharedStateBehavior) inline
Definition at line 239 of file MetasoundArrayRandomNode.h.
References bEnableSharedState, Metasound::INodeBase::GetInstanceID(), INDEX_NONE, InputArray, InputWeightsArray, Metasound::FBuildOperatorParams::Node, NodeId, NoRepeatOrder, OutIndex, OutValue, Reset, SeedValue, SharedStateBehavior, TriggerNext, TriggerOnNext, TriggerOnReset, and TriggerReset.
~TArrayRandomGetOperator()
template<typename ArrayType> virtual Metasound::TArrayRandomGetOperator< ArrayType >::~TArrayRandomGetOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArrayRandomGetOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 268 of file MetasoundArrayRandomNode.h.
References bEnableSharedState, Metasound::FInputVertexInterfaceData::BindReadVertex(), InputArray, InputWeightsArray, METASOUND_GET_PARAM_NAME, NoRepeatOrder, SeedValue, Metasound::FInputVertexInterfaceData::SetValue(), SharedStateBehavior, TriggerNext, and TriggerReset.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArrayRandomGetOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 281 of file MetasoundArrayRandomNode.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, OutIndex, OutValue, TriggerOnNext, and TriggerOnReset.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArrayRandomGetOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 220 of file MetasoundArrayRandomNode.h.
References Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FInputVertexInterfaceData::GetOrCreateDefaultValue(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
CreateSharedStateArgs()
template<typename ArrayType> void Metasound::TArrayRandomGetOperator< ArrayType >::CreateSharedStateArgs (InitSharedStateArgs & InOutStateArgs) inline private
Definition at line 417 of file MetasoundArrayRandomNode.h.
References Metasound::InitSharedStateArgs::bIsPreviewSound, bIsPreviewSound, InputWeightsArray, Metasound::InitSharedStateArgs::NoRepeatOrder, NoRepeatOrder, Metasound::InitSharedStateArgs::NumElements, Metasound::InitSharedStateArgs::Seed, SeedValue, Metasound::InitSharedStateArgs::SharedStateId, SharedStateId, and Metasound::InitSharedStateArgs::Weights.
Referenced by ExecuteTriggerNext(), and ExecuteTriggerReset().
Execute()
template<typename ArrayType> void Metasound::TArrayRandomGetOperator< ArrayType >::Execute () inline
Definition at line 356 of file MetasoundArrayRandomNode.h.
References bHasLoggedEmptyArrayWarning, EndFrame, ExecuteTriggerNext(), ExecuteTriggerReset(), GraphName, InputArray, TEXT, TriggerNext, TriggerOnNext, TriggerOnReset, TriggerReset, UE_LOG, and Verbose.
ExecuteTriggerNext()
template<typename ArrayType> void Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext (int32 StartFrame) inline private
Definition at line 460 of file MetasoundArrayRandomNode.h.
References ArrayRandomGet, bEnableSharedState, bIsPreviewSound, check, CreateSharedStateArgs(), DebugSharedStateBehaviorString, Metasound::FSharedStateRandomGetManager::Get(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), Metasound::GetMetasoundDataTypeString(), GraphName, INDEX_NONE, InputArray, InputWeightsArray, MakeUnique(), Metasound::FSharedStateRandomGetManager::NextValue(), NodeId, NoRepeatOrder, OutIndex, OutValue, Metasound::SameData, SeedValue, SharedStateBehavior, SharedStateId, TEXT, TriggerOnNext, and UE_LOG.
Referenced by Execute().
ExecuteTriggerReset()
template<typename ArrayType> void Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerReset (int32 StartFrame) inline private
Definition at line 427 of file MetasoundArrayRandomNode.h.
References ArrayRandomGet, bEnableSharedState, bIsPreviewSound, CreateSharedStateArgs(), Metasound::FSharedStateRandomGetManager::Get(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), InputArray, InputWeightsArray, MakeUnique(), NoRepeatOrder, Metasound::FSharedStateRandomGetManager::ResetSeed(), Metasound::SameData, SeedValue, SharedStateBehavior, SharedStateId, and TriggerOnReset.
Referenced by Execute().
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArrayRandomGetOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 176 of file MetasoundArrayRandomNode.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA, and Metasound::SameNodeInComposition.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayRandomGetOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 290 of file MetasoundArrayRandomNode.h.
References checkNoEntry.
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArrayRandomGetOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 202 of file MetasoundArrayRandomNode.h.
References Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metadata, METASOUND_LOCTEXT, and METASOUND_LOCTEXT_FORMAT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayRandomGetOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 298 of file MetasoundArrayRandomNode.h.
References checkNoEntry.
GetSameNodeInCompositionId()
template<typename ArrayType> FGuid Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId (const FGuid & InNodeId, const TArray< FGuid > & InGraphHierarchy) const inline private
Definition at line 520 of file MetasoundArrayRandomNode.h.
References A, FGuid::A, B, FGuid::B, FGuid::C, FGuid::D, HashCombineFast(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by Reset().
GetSameNodeSharedStateId()
template<typename ArrayType> FGuid Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId (const FGuid & InNodeId, const FGuid & InOtherId) const inline private
Definition at line 509 of file MetasoundArrayRandomNode.h.
References FGuid::A, FGuid::B, FGuid::C, FGuid::D, and HashCombineFast().
Referenced by Reset().
Reset()
template<typename ArrayType> void Metasound::TArrayRandomGetOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 306 of file MetasoundArrayRandomNode.h.
References bHasLoggedMissingGraphHierarchyWarning, bIsPreviewSound, check, Metasound::FMetasoundEnvironment::Contains(), Metasound::TDataFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateAny(), DebugSharedStateBehaviorString, Metasound::IOperator::FResetParams::Environment, GetSameNodeInCompositionId(), GetSameNodeSharedStateId(), Metasound::FMetasoundEnvironment::GetValue(), TOptional< OptionalType >::GetValue(), Metasound::CoreInterface::Environment::GraphHierarchy, GraphName, INDEX_NONE, TOptional< OptionalType >::IsSet(), NodeId, Metasound::IOperator::FResetParams::OperatorSettings, OutIndex, OutValue, Metasound::SameNode, Metasound::SameNodeInComposition, SharedStateBehavior, SharedStateId, TEXT, Metasound::TEnum< ESharedStateBehaviorType, ESharedStateBehaviorType::SameNodeInComposition >::ToName(), TriggerOnNext, TriggerOnReset, UE_LOG, and Warning.
Field Documentation
ArrayRandomGet
template<typename ArrayType> TUniquePtr<FArrayRandomGet> Metasound::TArrayRandomGetOperator< ArrayType >::ArrayRandomGet private
Definition at line 557 of file MetasoundArrayRandomNode.h.
Referenced by ExecuteTriggerNext(), and ExecuteTriggerReset().
bEnableSharedState
template<typename ArrayType> FBoolReadRef Metasound::TArrayRandomGetOperator< ArrayType >::bEnableSharedState private
Definition at line 540 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), ExecuteTriggerNext(), and ExecuteTriggerReset().
bHasLoggedEmptyArrayWarning
template<typename ArrayType> bool Metasound::TArrayRandomGetOperator< ArrayType >::bHasLoggedEmptyArrayWarning = false private
Definition at line 551 of file MetasoundArrayRandomNode.h.
Referenced by Execute().
bHasLoggedMissingGraphHierarchyWarning
template<typename ArrayType> bool Metasound::TArrayRandomGetOperator< ArrayType >::bHasLoggedMissingGraphHierarchyWarning = false private
Definition at line 552 of file MetasoundArrayRandomNode.h.
Referenced by Reset().
bIsPreviewSound
template<typename ArrayType> bool Metasound::TArrayRandomGetOperator< ArrayType >::bIsPreviewSound = false private
Definition at line 560 of file MetasoundArrayRandomNode.h.
Referenced by CreateSharedStateArgs(), ExecuteTriggerNext(), ExecuteTriggerReset(), and Reset().
DebugSharedStateBehaviorString
template<typename ArrayType> FString Metasound::TArrayRandomGetOperator< ArrayType >::DebugSharedStateBehaviorString private
Definition at line 553 of file MetasoundArrayRandomNode.h.
Referenced by ExecuteTriggerNext(), and Reset().
GraphName
template<typename ArrayType> FString Metasound::TArrayRandomGetOperator< ArrayType >::GraphName private
Definition at line 550 of file MetasoundArrayRandomNode.h.
Referenced by Execute(), ExecuteTriggerNext(), and Reset().
InputArray
template<typename ArrayType> FArrayDataReadReference Metasound::TArrayRandomGetOperator< ArrayType >::InputArray private
Definition at line 536 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), Execute(), ExecuteTriggerNext(), and ExecuteTriggerReset().
InputWeightsArray
template<typename ArrayType> TDataReadReference<WeightsArrayType> Metasound::TArrayRandomGetOperator< ArrayType >::InputWeightsArray private
Definition at line 537 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), CreateSharedStateArgs(), ExecuteTriggerNext(), and ExecuteTriggerReset().
NodeId
template<typename ArrayType> FGuid Metasound::TArrayRandomGetOperator< ArrayType >::NodeId private
Definition at line 558 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), ExecuteTriggerNext(), and Reset().
NoRepeatOrder
template<typename ArrayType> FInt32ReadRef Metasound::TArrayRandomGetOperator< ArrayType >::NoRepeatOrder private
Definition at line 539 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), CreateSharedStateArgs(), ExecuteTriggerNext(), and ExecuteTriggerReset().
OutIndex
template<typename ArrayType> FInt32WriteRef Metasound::TArrayRandomGetOperator< ArrayType >::OutIndex private
Definition at line 547 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindOutputs(), ExecuteTriggerNext(), and Reset().
OutValue
template<typename ArrayType> TDataWriteReference<ElementType> Metasound::TArrayRandomGetOperator< ArrayType >::OutValue private
Definition at line 546 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindOutputs(), ExecuteTriggerNext(), and Reset().
SeedValue
template<typename ArrayType> FInt32ReadRef Metasound::TArrayRandomGetOperator< ArrayType >::SeedValue private
Definition at line 538 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), CreateSharedStateArgs(), ExecuteTriggerNext(), and ExecuteTriggerReset().
SharedStateBehavior
template<typename ArrayType> FEnumSharedStateBehaviorType Metasound::TArrayRandomGetOperator< ArrayType >::SharedStateBehavior private
Definition at line 541 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), ExecuteTriggerNext(), ExecuteTriggerReset(), and Reset().
SharedStateId
template<typename ArrayType> FGuid Metasound::TArrayRandomGetOperator< ArrayType >::SharedStateId private
Definition at line 559 of file MetasoundArrayRandomNode.h.
Referenced by CreateSharedStateArgs(), ExecuteTriggerNext(), ExecuteTriggerReset(), and Reset().
TriggerNext
template<typename ArrayType> FTriggerReadRef Metasound::TArrayRandomGetOperator< ArrayType >::TriggerNext private
Definition at line 534 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), and Execute().
TriggerOnNext
template<typename ArrayType> FTriggerWriteRef Metasound::TArrayRandomGetOperator< ArrayType >::TriggerOnNext private
Definition at line 544 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindOutputs(), Execute(), ExecuteTriggerNext(), and Reset().
TriggerOnReset
template<typename ArrayType> FTriggerWriteRef Metasound::TArrayRandomGetOperator< ArrayType >::TriggerOnReset private
Definition at line 545 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindOutputs(), Execute(), ExecuteTriggerReset(), and Reset().
TriggerReset
template<typename ArrayType> FTriggerReadRef Metasound::TArrayRandomGetOperator< ArrayType >::TriggerReset private
Definition at line 535 of file MetasoundArrayRandomNode.h.
Referenced by TArrayRandomGetOperator(), BindInputs(), and Execute().
The documentation for this class was generated from the following file:
MetasoundArrayRandomNode.h