Unreal Engine 5.6 C++ API: Metasound::IDataReference Class Reference
Metasound::IDataReference Class Reference abstract
A Data Reference Interface.
#include "MetasoundDataReference.h"
Public Member Functions
virtual ~IDataReference ()=default
virtual TUniquePtr< IDataReference > Clone () const =0
Creates a copy of the parameter type.
virtual const void *const GetDataTypeId () const =0
Returns the ID of the parameter type.
virtual const FName & GetDataTypeName () const =0
Returns the name of the data type.
virtual void * GetRaw () const =0
provides a raw pointer to the storage where the data actually resides.
Static Public Attributes
static METASOUNDGRAPHCORE_API const FName RouterName
Detailed Description
A Data Reference Interface.
A parameter references provides information and access to a shared object in the graph.
Definition at line 116 of file MetasoundDataReference.h.
Constructor & Destructor Documentation
~IDataReference()
virtual Metasound::IDataReference::~IDataReference () virtual default
Member Function Documentation
Clone()
virtual TUniquePtr< IDataReference > Metasound::IDataReference::Clone () const pure virtual
Creates a copy of the parameter type.
Implemented in Metasound::FAnyDataReference, Metasound::TDataReadReference< DataType >, Metasound::TDataReadReference< ArrayType >, Metasound::TDataReadReference< bool >, Metasound::TDataReadReference< ElementType >, Metasound::TDataReadReference< FAudioBuffer >, Metasound::TDataReadReference< FEnumDelayFilterType >, Metasound::TDataReadReference< FEnumDelayStereoType >, Metasound::TDataReadReference< FEnumMidiClockSubdivisionQuantizationType >, Metasound::TDataReadReference< FEnumSharedStateBehaviorType >, Metasound::TDataReadReference< FEnumStdMidiControllerID >, Metasound::TDataReadReference< FEnumTimeSyncOption >, Metasound::TDataReadReference< FFusionPatchAsset >, Metasound::TDataReadReference< FMetasoundParameterStorageWrapper >, Metasound::TDataReadReference< FMidiAsset >, Metasound::TDataReadReference< FMidiClock >, Metasound::TDataReadReference< FMidiClockSongPosition >, Metasound::TDataReadReference< FMidiEventInfo >, Metasound::TDataReadReference< FMidiStream >, Metasound::TDataReadReference< FMusicLoopConfiguration >, Metasound::TDataReadReference< FMusicSeekRequest >, Metasound::TDataReadReference< FMusicSeekTarget >, Metasound::TDataReadReference< FMusicTimestamp >, Metasound::TDataReadReference< FMusicTransportEvent >, Metasound::TDataReadReference< FMusicTransportEventStream >, Metasound::TDataReadReference< FromDataType >, Metasound::TDataReadReference< int32 >, Metasound::TDataReadReference< Metasound::FSendAddress >, Metasound::TDataReadReference< Metasound::FTrigger >, Metasound::TDataReadReference< TArray< float > >, Metasound::TDataReadReference< TDataType >, Metasound::TDataValueReference< DataType >, Metasound::TDataWriteReference< DataType >, Metasound::TDataWriteReference< ArrayType >, Metasound::TDataWriteReference< ElementType >, Metasound::TDataWriteReference< FAudioBuffer >, Metasound::TDataWriteReference< FEnumDelayFilterType >, Metasound::TDataWriteReference< FEnumDelayStereoType >, Metasound::TDataWriteReference< FEnumMidiClockSubdivisionQuantizationType >, Metasound::TDataWriteReference< FEnumSharedStateBehaviorType >, Metasound::TDataWriteReference< FEnumStdMidiControllerID >, Metasound::TDataWriteReference< FEnumTimeSyncOption >, Metasound::TDataWriteReference< FFusionPatchAsset >, Metasound::TDataWriteReference< float >, Metasound::TDataWriteReference< FMetasoundParameterStorageWrapper >, Metasound::TDataWriteReference< FMidiAsset >, Metasound::TDataWriteReference< FMidiClock >, Metasound::TDataWriteReference< FMidiClockSongPosition >, Metasound::TDataWriteReference< FMidiEventInfo >, Metasound::TDataWriteReference< FMidiStream >, Metasound::TDataWriteReference< FMusicLoopConfiguration >, Metasound::TDataWriteReference< FMusicSeekRequest >, Metasound::TDataWriteReference< FMusicSeekTarget >, Metasound::TDataWriteReference< FMusicTimestamp >, Metasound::TDataWriteReference< FMusicTransportEvent >, Metasound::TDataWriteReference< FMusicTransportEventStream >, Metasound::TDataWriteReference< int32 >, Metasound::TDataWriteReference< Metasound::FTime >, Metasound::TDataWriteReference< Metasound::FTrigger >, Metasound::TDataWriteReference< Metasound::TVariable >, Metasound::TDataWriteReference< TDataType >, and Metasound::TDataWriteReference< ToDataType >.
GetDataTypeId()
virtual const void *const Metasound::IDataReference::GetDataTypeId () const pure virtual
Returns the ID of the parameter type.
Implemented in Metasound::FAnyDataReference, Metasound::TDataReference< DataType >, Metasound::TDataReference< bool >, Metasound::TDataReference< ElementType >, Metasound::TDataReference< float >, Metasound::TDataReference< FromDataType >, Metasound::TDataReference< int32 >, Metasound::TDataReference< Metasound::FSendAddress >, Metasound::TDataReference< Metasound::FTime >, Metasound::TDataReference< Metasound::FTrigger >, Metasound::TDataReference< Metasound::TVariable >, Metasound::TDataReference< TDataType >, and Metasound::TDataReference< ToDataType >.
Referenced by Metasound::IsDataReferenceOfType().
GetDataTypeName()
virtual const FName & Metasound::IDataReference::GetDataTypeName () const pure virtual
Returns the name of the data type.
Implemented in Metasound::FAnyDataReference, Metasound::TDataReference< DataType >, Metasound::TDataReference< bool >, Metasound::TDataReference< ElementType >, Metasound::TDataReference< float >, Metasound::TDataReference< FromDataType >, Metasound::TDataReference< int32 >, Metasound::TDataReference< Metasound::FSendAddress >, Metasound::TDataReference< Metasound::FTime >, Metasound::TDataReference< Metasound::FTrigger >, Metasound::TDataReference< Metasound::TVariable >, Metasound::TDataReference< TDataType >, and Metasound::TDataReference< ToDataType >.
Referenced by Metasound::FAnyDataReference::TGetAs< TDataWriteReference< DataType > >::Get(), and Metasound::IsDataReferenceOfType().
GetRaw()
virtual void * Metasound::IDataReference::GetRaw () const pure virtual
provides a raw pointer to the storage where the data actually resides.
Implemented in Metasound::FAnyDataReference, Metasound::TDataReference< DataType >, Metasound::TDataReference< bool >, Metasound::TDataReference< ElementType >, Metasound::TDataReference< float >, Metasound::TDataReference< FromDataType >, Metasound::TDataReference< int32 >, Metasound::TDataReference< Metasound::FSendAddress >, Metasound::TDataReference< Metasound::FTime >, Metasound::TDataReference< Metasound::FTrigger >, Metasound::TDataReference< Metasound::TVariable >, Metasound::TDataReference< TDataType >, and Metasound::TDataReference< ToDataType >.
Referenced by Metasound::FAnyDataReference::TGetAs< ResultType >::Get(), and Metasound::GetDataReferenceID().
Field Documentation
RouterName
METASOUNDGRAPHCORE_API const FName Metasound::IDataReference::RouterName static
Definition at line 119 of file MetasoundDataReference.h.
The documentation for this class was generated from the following file:
MetasoundDataReference.h