Unreal Engine 5.6 C++ API: FShaderParameterParser Class Reference
FShaderParameterParser Class Reference
Validates and moves all the shader loose data parameter defined in the root scope of the shader into the root uniform buffer.
#include "ShaderParameterParser.h"
Data Structures
struct FParsedShaderParameter
struct FPlatformConfiguration
Public Member Functions
FShaderParameterParser ()=delete
RENDERCORE_API FShaderParameterParser (const FPlatformConfiguration &InPlatformConfiguration)
virtual RENDERCORE_API ~FShaderParameterParser ()
bool DidModifyShader () const
const FParsedShaderParameter & FindParameterInfos (const FString &ParameterName) const
Gets parsing information from a parameter binding name.
const FParsedShaderParameter * FindParameterInfosUnsafe (const FString &ParameterName) const
void GetParameterFileAndLine (const FParsedShaderParameter &ParsedParameter, FString &OutFile, FString &OutLine) const
Gets file and line of the parameter in the shader source code.
RENDERCORE_API bool ParseAndModify (const FShaderCompilerInput &CompilerInput, TArray< FShaderCompilerError > &OutErrors, FString &PreprocessedShaderSource)
RENDERCORE_API void ValidateShaderParameterType (const FShaderCompilerInput &CompilerInput, const FString &ShaderBindingName, int32 ReflectionOffset, int32 ReflectionSize, bool bPlatformSupportsPrecisionModifier, FShaderCompilerOutput &CompilerOutput) const
Validates the shader parameter in code is compatible with the shader parameter structure.
void ValidateShaderParameterType (const FShaderCompilerInput &CompilerInput, const FString &ShaderBindingName, int32 ReflectionOffset, int32 ReflectionSize, FShaderCompilerOutput &CompilerOutput) const
RENDERCORE_API void ValidateShaderParameterTypes (const FShaderCompilerInput &CompilerInput, bool bPlatformSupportsPrecisionModifier, FShaderCompilerOutput &CompilerOutput) const
Validates shader parameter map is compatible with the shader parameter structure.
void ValidateShaderParameterTypes (const FShaderCompilerInput &CompilerInput, FShaderCompilerOutput &CompilerOutput) const
Static Public Member Functions
static RENDERCORE_API FStringView GetBindlessParameterPrefix (EShaderParameterType InShaderParameterType)
static RENDERCORE_API EShaderParameterType ParseAndRemoveBindlessParameterPrefix (FString &InName)
static RENDERCORE_API EShaderParameterType ParseAndRemoveBindlessParameterPrefix (FStringView &InName)
static RENDERCORE_API bool RemoveBindlessParameterPrefix (FString &InName)
Static Public Attributes
static constexpr const TCHAR * kBindlessSamplerArrayPrefix = L"SamplerDescriptorHeap_"
static constexpr const TCHAR * kBindlessSamplerPrefix = L"BindlessSampler_"
static constexpr const TCHAR * kBindlessSRVArrayPrefix = L"SRVDescriptorHeap_"
static constexpr const TCHAR * kBindlessSRVPrefix = L"BindlessSRV_"
static constexpr const TCHAR * kBindlessUAVArrayPrefix = L"UAVDescriptorHeap_"
static constexpr const TCHAR * kBindlessUAVPrefix = L"BindlessUAV_"
Protected Member Functions
RENDERCORE_API void ApplyBindlessModifications (FString &PreprocessedShaderSource)
Converts parsed parameters into their bindless forms.
RENDERCORE_API void ExtractFileAndLine (int32 PragamLineoffset, int32 LineOffset, FString &OutFile, FString &OutLine) const
virtual RENDERCORE_API FString GenerateBindlessParameterDeclaration (const FParsedShaderParameter &ParsedParameter) const
Generates shader source code to declare a bindless resource or sampler (for automatic bindless conversion).
RENDERCORE_API bool MoveShaderParametersToRootConstantBuffer (const FShaderParametersMetadata *RootParametersStructure, FString &PreprocessedShaderSource)
Moves parsed parameters into the root constant buffer.
RENDERCORE_API bool ParseParameters (const FShaderParametersMetadata *RootParametersStructure, TArray< FShaderCompilerError > &OutErrors)
Parses the preprocessed shader code.
RENDERCORE_API EShaderParameterType ParseParameterType (FStringView InType)
RENDERCORE_API void RemoveMovingParametersFromSource (FString &PreprocessedShaderSource)
Protected Attributes
bool bBindlessResources = false
bool bBindlessSamplers = false
bool bModifiedShader = false
Indicates that the shader source was actually modified.
bool bMovedLoosedParametersToRootConstantBuffer = false
Indicates that parameters were actually moved to the root constant buffer.
bool bNeedToMoveToRootConstantBuffer = false
Indicates that parameters should be moved to the root cosntant buffer.
FString OriginalParsedShader
TMap< FString, FParsedShaderParameter > ParsedParameters
const FPlatformConfiguration & PlatformConfiguration
Detailed Description
Validates and moves all the shader loose data parameter defined in the root scope of the shader into the root uniform buffer.
Definition at line 40 of file ShaderParameterParser.h.
Constructor & Destructor Documentation
FShaderParameterParser() [1/2]
FShaderParameterParser::FShaderParameterParser () delete
FShaderParameterParser() [2/2]
RENDERCORE_API FShaderParameterParser::FShaderParameterParser (const FPlatformConfiguration & InPlatformConfiguration)
~FShaderParameterParser()
virtual RENDERCORE_API FShaderParameterParser::~FShaderParameterParser () virtual
Member Function Documentation
ApplyBindlessModifications()
RENDERCORE_API void FShaderParameterParser::ApplyBindlessModifications (FString & PreprocessedShaderSource) protected
Converts parsed parameters into their bindless forms.
DidModifyShader()
bool FShaderParameterParser::DidModifyShader () const inline
Definition at line 197 of file ShaderParameterParser.h.
References bModifiedShader.
ExtractFileAndLine()
RENDERCORE_API void FShaderParameterParser::ExtractFileAndLine (int32 PragamLineoffset, int32 LineOffset, FString & OutFile, FString & OutLine) const protected
Referenced by GetParameterFileAndLine().
FindParameterInfos()
const FParsedShaderParameter & FShaderParameterParser::FindParameterInfos (const FString & ParameterName) const inline
Gets parsing information from a parameter binding name.
Definition at line 147 of file ShaderParameterParser.h.
References checkf, ParsedParameters, and TEXT.
FindParameterInfosUnsafe()
const FParsedShaderParameter * FShaderParameterParser::FindParameterInfosUnsafe (const FString & ParameterName) const inline
Definition at line 154 of file ShaderParameterParser.h.
References ParsedParameters.
GenerateBindlessParameterDeclaration()
virtual RENDERCORE_API FString FShaderParameterParser::GenerateBindlessParameterDeclaration (const FParsedShaderParameter & ParsedParameter) const protected virtual
Generates shader source code to declare a bindless resource or sampler (for automatic bindless conversion).
May be overriden to allow custom implementations for different platforms.
GetBindlessParameterPrefix()
RENDERCORE_API FStringView FShaderParameterParser::GetBindlessParameterPrefix (EShaderParameterType InShaderParameterType) static
GetParameterFileAndLine()
void FShaderParameterParser::GetParameterFileAndLine (const FParsedShaderParameter & ParsedParameter, FString & OutFile, FString & OutLine) const inline
Gets file and line of the parameter in the shader source code.
Definition at line 192 of file ShaderParameterParser.h.
References ExtractFileAndLine(), FShaderParameterParser::FParsedShaderParameter::ParsedLineOffset, and FShaderParameterParser::FParsedShaderParameter::ParsedPragmaLineOffset.
MoveShaderParametersToRootConstantBuffer()
RENDERCORE_API bool FShaderParameterParser::MoveShaderParametersToRootConstantBuffer (const FShaderParametersMetadata * RootParametersStructure, FString & PreprocessedShaderSource) protected
Moves parsed parameters into the root constant buffer.
ParseAndModify()
RENDERCORE_API bool FShaderParameterParser::ParseAndModify (const FShaderCompilerInput & CompilerInput, TArray< FShaderCompilerError > & OutErrors, FString & PreprocessedShaderSource)
ParseAndRemoveBindlessParameterPrefix() [1/2]
RENDERCORE_API EShaderParameterType FShaderParameterParser::ParseAndRemoveBindlessParameterPrefix (FString & InName) static
References InName.
ParseAndRemoveBindlessParameterPrefix() [2/2]
RENDERCORE_API EShaderParameterType FShaderParameterParser::ParseAndRemoveBindlessParameterPrefix (FStringView & InName) static
References InName.
ParseParameters()
RENDERCORE_API bool FShaderParameterParser::ParseParameters (const FShaderParametersMetadata * RootParametersStructure, TArray< FShaderCompilerError > & OutErrors) protected
Parses the preprocessed shader code.
ParseParameterType()
RENDERCORE_API EShaderParameterType FShaderParameterParser::ParseParameterType (FStringView InType) protected
RemoveBindlessParameterPrefix()
RENDERCORE_API bool FShaderParameterParser::RemoveBindlessParameterPrefix (FString & InName) static
References InName.
RemoveMovingParametersFromSource()
RENDERCORE_API void FShaderParameterParser::RemoveMovingParametersFromSource (FString & PreprocessedShaderSource) protected
ValidateShaderParameterType() [1/2]
RENDERCORE_API void FShaderParameterParser::ValidateShaderParameterType (const FShaderCompilerInput & CompilerInput, const FString & ShaderBindingName, int32 ReflectionOffset, int32 ReflectionSize, bool bPlatformSupportsPrecisionModifier, FShaderCompilerOutput & CompilerOutput) const
Validates the shader parameter in code is compatible with the shader parameter structure.
Referenced by ValidateShaderParameterType().
ValidateShaderParameterType() [2/2]
void FShaderParameterParser::ValidateShaderParameterType (const FShaderCompilerInput & CompilerInput, const FString & ShaderBindingName, int32 ReflectionOffset, int32 ReflectionSize, FShaderCompilerOutput & CompilerOutput) const inline
Definition at line 168 of file ShaderParameterParser.h.
References ValidateShaderParameterType().
ValidateShaderParameterTypes() [1/2]
RENDERCORE_API void FShaderParameterParser::ValidateShaderParameterTypes (const FShaderCompilerInput & CompilerInput, bool bPlatformSupportsPrecisionModifier, FShaderCompilerOutput & CompilerOutput) const
Validates shader parameter map is compatible with the shader parameter structure.
Referenced by ValidateShaderParameterTypes().
ValidateShaderParameterTypes() [2/2]
void FShaderParameterParser::ValidateShaderParameterTypes (const FShaderCompilerInput & CompilerInput, FShaderCompilerOutput & CompilerOutput) const inline
Definition at line 184 of file ShaderParameterParser.h.
References ValidateShaderParameterTypes().
Field Documentation
bBindlessResources
bool FShaderParameterParser::bBindlessResources = false protected
Definition at line 237 of file ShaderParameterParser.h.
bBindlessSamplers
bool FShaderParameterParser::bBindlessSamplers = false protected
Definition at line 238 of file ShaderParameterParser.h.
bModifiedShader
bool FShaderParameterParser::bModifiedShader = false protected
Indicates that the shader source was actually modified.
Definition at line 247 of file ShaderParameterParser.h.
Referenced by DidModifyShader().
bMovedLoosedParametersToRootConstantBuffer
bool FShaderParameterParser::bMovedLoosedParametersToRootConstantBuffer = false protected
Indicates that parameters were actually moved to the root constant buffer.
Definition at line 244 of file ShaderParameterParser.h.
bNeedToMoveToRootConstantBuffer
bool FShaderParameterParser::bNeedToMoveToRootConstantBuffer = false protected
Indicates that parameters should be moved to the root cosntant buffer.
Definition at line 241 of file ShaderParameterParser.h.
kBindlessSamplerArrayPrefix
const TCHAR* FShaderParameterParser::kBindlessSamplerArrayPrefix = L"SamplerDescriptorHeap_" static constexpr
Definition at line 133 of file ShaderParameterParser.h.
kBindlessSamplerPrefix
const TCHAR* FShaderParameterParser::kBindlessSamplerPrefix = L"BindlessSampler_" static constexpr
Definition at line 128 of file ShaderParameterParser.h.
kBindlessSRVArrayPrefix
const TCHAR* FShaderParameterParser::kBindlessSRVArrayPrefix = L"SRVDescriptorHeap_" static constexpr
Definition at line 131 of file ShaderParameterParser.h.
kBindlessSRVPrefix
const TCHAR* FShaderParameterParser::kBindlessSRVPrefix = L"BindlessSRV_" static constexpr
Definition at line 126 of file ShaderParameterParser.h.
kBindlessUAVArrayPrefix
const TCHAR* FShaderParameterParser::kBindlessUAVArrayPrefix = L"UAVDescriptorHeap_" static constexpr
Definition at line 132 of file ShaderParameterParser.h.
kBindlessUAVPrefix
const TCHAR* FShaderParameterParser::kBindlessUAVPrefix = L"BindlessUAV_" static constexpr
Definition at line 127 of file ShaderParameterParser.h.
OriginalParsedShader
FString FShaderParameterParser::OriginalParsedShader protected
Definition at line 233 of file ShaderParameterParser.h.
ParsedParameters
TMap<FString, FParsedShaderParameter> FShaderParameterParser::ParsedParameters protected
Definition at line 235 of file ShaderParameterParser.h.
Referenced by FindParameterInfos(), and FindParameterInfosUnsafe().
PlatformConfiguration
const FPlatformConfiguration& FShaderParameterParser::PlatformConfiguration protected
Definition at line 231 of file ShaderParameterParser.h.
The documentation for this class was generated from the following file:
ShaderParameterParser.h