Unreal Engine 5.6 C++ API: UE::TDynamicSharedLock< LockType > Class Template Reference
UE::TDynamicSharedLock< LockType > Class Template Reference final
A shared mutex ownership wrapper that allows dynamic locking, unlocking, and deferred locking.
#include "SharedLock.h"
Public Member Functions
TDynamicSharedLock ()=default
TDynamicSharedLock (const TDynamicSharedLock &)=delete
TDynamicSharedLock (LockType &Lock)
Wrap a mutex and lock it in shared mode.
TDynamicSharedLock (LockType &Lock, FDeferLock)
Wrap a mutex without locking it in shared mode.
TDynamicSharedLock (TDynamicSharedLock &&Other)
Move from another lock, transferring any ownership to this lock.
~TDynamicSharedLock ()
Unlock the mutex if locked.
void Lock ()
Lock the associated mutex in shared mode.
operator bool () const
Returns true if this lock has its associated mutex locked.
TDynamicSharedLock & operator= (const TDynamicSharedLock &)=delete
TDynamicSharedLock & operator= (TDynamicSharedLock &&Other)
Move from another lock, transferring any ownership to this lock, and unlocking the previous mutex if locked.
bool OwnsLock () const
Returns true if this lock has its associated mutex locked.
bool TryLock ()
Try to lock the associated mutex in shared mode.
void Unlock ()
Unlock the associated mutex in shared mode.
Private Attributes
bool bLocked = false
LockType * Mutex = nullptr
Detailed Description
template<typename LockType>
class UE::TDynamicSharedLock< LockType >
A shared mutex ownership wrapper that allows dynamic locking, unlocking, and deferred locking.
LockType must contain LockShared() and UnlockShared() functions.
Use with mutex types like FSharedMutex and FSharedRecursiveMutex.
Definition at line 50 of file SharedLock.h.
Constructor & Destructor Documentation
TDynamicSharedLock() [1/5]
template<typename LockType> UE::TDynamicSharedLock< LockType >::TDynamicSharedLock () default
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), operator=(), and operator=().
TDynamicSharedLock() [2/5]
template<typename LockType> UE::TDynamicSharedLock< LockType >::TDynamicSharedLock (const TDynamicSharedLock< LockType > &) delete
References TDynamicSharedLock().
TDynamicSharedLock() [3/5]
template<typename LockType> UE::TDynamicSharedLock< LockType >::TDynamicSharedLock (LockType & Lock) inline explicit nodiscard
Wrap a mutex and lock it in shared mode.
Definition at line 59 of file SharedLock.h.
References bLocked, Lock(), and Mutex.
TDynamicSharedLock() [4/5]
template<typename LockType> UE::TDynamicSharedLock< LockType >::TDynamicSharedLock (LockType & Lock, FDeferLock) inline explicit nodiscard
Wrap a mutex without locking it in shared mode.
Definition at line 67 of file SharedLock.h.
References Lock(), and Mutex.
TDynamicSharedLock() [5/5]
template<typename LockType> UE::TDynamicSharedLock< LockType >::TDynamicSharedLock (TDynamicSharedLock< LockType > && Other) inline nodiscard
Move from another lock, transferring any ownership to this lock.
Definition at line 73 of file SharedLock.h.
References TDynamicSharedLock(), bLocked, Mutex, and Other.
~TDynamicSharedLock()
template<typename LockType> UE::TDynamicSharedLock< LockType >::~TDynamicSharedLock () inline
Unlock the mutex if locked.
Definition at line 96 of file SharedLock.h.
References bLocked, and Mutex.
Member Function Documentation
Lock()
template<typename LockType> void UE::TDynamicSharedLock< LockType >::Lock () inline
Lock the associated mutex in shared mode.
This lock must have a mutex and must not be locked.
Definition at line 114 of file SharedLock.h.
References bLocked, check, and Mutex.
Referenced by TDynamicSharedLock(), and TDynamicSharedLock().
operator bool()
template<typename LockType> UE::TDynamicSharedLock< LockType >::operator bool () const inline explicit
Returns true if this lock has its associated mutex locked.
Definition at line 137 of file SharedLock.h.
References OwnsLock().
operator=() [1/2]
template<typename LockType> TDynamicSharedLock & UE::TDynamicSharedLock< LockType >::operator= (const TDynamicSharedLock< LockType > &) delete
References TDynamicSharedLock().
operator=() [2/2]
template<typename LockType> TDynamicSharedLock & UE::TDynamicSharedLock< LockType >::operator= (TDynamicSharedLock< LockType > && Other) inline
Move from another lock, transferring any ownership to this lock, and unlocking the previous mutex if locked.
Definition at line 82 of file SharedLock.h.
References TDynamicSharedLock(), bLocked, Mutex, and Other.
OwnsLock()
template<typename LockType> bool UE::TDynamicSharedLock< LockType >::OwnsLock () const inline
Returns true if this lock has its associated mutex locked.
Definition at line 131 of file SharedLock.h.
References bLocked.
Referenced by operator bool(), and UE::TDynamicSharedLock< FSharedRecursiveMutex >::operator bool().
TryLock()
template<typename LockType> bool UE::TDynamicSharedLock< LockType >::TryLock () inline
Try to lock the associated mutex in shared mode.
This lock must have a mutex and must not be locked.
Definition at line 105 of file SharedLock.h.
References bLocked, check, and Mutex.
Unlock()
template<typename LockType> void UE::TDynamicSharedLock< LockType >::Unlock () inline
Unlock the associated mutex in shared mode.
This lock must have a mutex and must be locked.
Definition at line 123 of file SharedLock.h.
References bLocked, check, and Mutex.
Field Documentation
bLocked
template<typename LockType> bool UE::TDynamicSharedLock< LockType >::bLocked = false private
Definition at line 144 of file SharedLock.h.
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), ~TDynamicSharedLock(), Lock(), operator=(), OwnsLock(), TryLock(), and Unlock().
Mutex
template<typename LockType> LockType* UE::TDynamicSharedLock< LockType >::Mutex = nullptr private
Definition at line 143 of file SharedLock.h.
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), TDynamicSharedLock(), ~TDynamicSharedLock(), Lock(), operator=(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
SharedLock.h