Unreal Engine 5.6 C++ API: FUICommandList Class Reference
FUICommandList Class Reference
#include "UICommandList.h"
Public Member Functions
virtual ~FUICommandList ()
Virtual destructor.
void Append (const TSharedRef< FUICommandList > &InCommandsToAppend)
Append commands in InCommandsToAppend to this command list.
bool CanExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the CanExecuteAction associated with the provided command info to see if ExecuteAction can be called.
DECLARE_DELEGATE_RetVal_OneParam (bool, FCanProduceActionForCommand, const TSharedRef< const FUICommandInfo > &)
Determines if this UICommandList is capable of producing an action for the supplied command.
virtual bool ExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Executes the action associated with the provided command info Note: It is assumed at this point that CanExecuteAction was already checked.
const FUIAction * GetActionForCommand (TSharedPtr< const FUICommandInfo > Command) const
Attempts to find an action for the specified command in the current UICommandList.
ECheckBoxState GetCheckState (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the GetCheckState delegate to see if the visualization of this command in a multibox should appear checked.
const FUIActionContext * GetContextForCommand (TSharedPtr< const FUICommandInfo > Command) const
Attempts to find an context for the specified command in the current UICommandList.
EVisibility GetVisibility (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the IsVisible delegate associated with the provided command info to see if the command should be visible in a toolbar.
bool IsActionMapped (const TSharedPtr< const FUICommandInfo > InUICommandInfo) const
Checks if an action is already mapped.
virtual void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, const FUIAction &InUIAction)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
virtual void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, const FUIAction &InUIAction, const FUIActionContext &InUIActionContext)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input Additionally, add a container of context objects to also associate with this command.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FGetActionCheckState GetActionCheckState, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FGetActionCheckState GetActionCheckState, FIsActionButtonVisible IsVisibleDelegate, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FIsActionChecked IsCheckedDelegate, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
void MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FIsActionChecked IsCheckedDelegate, FIsActionButtonVisible IsVisibleDelegate, EUIActionRepeatMode RepeatMode=EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
bool ProcessCommandBindings (const FKey Key, const FModifierKeysState &ModifierKeysState, const bool bRepeat) const
Processes any UI commands which are activated by the specified key, modifier keys state and input event.
bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const
Processes any UI commands which are activated by the specified key event.
bool ProcessCommandBindings (const FPointerEvent &InMouseEvent) const
Processes any UI commands which are activated by the specified mouse event.
void SetCanProduceActionForCommand (const FCanProduceActionForCommand &NewCanProduceActionForCommand)
Sets the delegate that determines if this UICommandList is capable of producing an action for the supplied command.
bool TryExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Attempts to execute the action associated with the provided command info Note: This will check if the action can be executed before finally executing the action.
void UnmapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo)
Unmaps a command info that was previously mapped.
Public Member Functions inherited from TSharedFromThis< FUICommandList >
TSharedRef< FUICommandList, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FUICommandList, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
bool ConditionalProcessCommandBindings (const FKey Key, bool bCtrl, bool bAlt, bool bShift, bool bCmd, bool bRepeat) const
Helper function to execute delegate or exec command associated with a command (if valid)
void GatherContextsForList (TSet< FName > &OutAllContexts) const
Returns all contexts associated with this list.
void GatherContextsForListRecursively (TSet< FName > &OutAllContexts, TSet< TSharedRef< const FUICommandList > > &InOutVisitedLists) const
Returns all contexts associated with this list.
const FUIAction * GetActionForCommandRecursively (const TSharedRef< const FUICommandInfo > &Command, bool bIncludeChildren, bool bIncludeParents, TSet< TSharedRef< const FUICommandList > > &InOutVisitedLists) const
Attempts to find an action for the specified command in the current UICommandList.
const FUIActionContext * GetContextForCommandRecursively (const TSharedRef< const FUICommandInfo > &Command, bool bIncludeChildren, bool bIncludeParents, TSet< TSharedRef< const FUICommandList > > &InOutVisitedLists) const
Attempts to find an context for the specified command in the current UICommandList.
Protected Member Functions inherited from TSharedFromThis< FUICommandList >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Types
using FUIBindingMap = TMap<const TSharedPtr<const FUICommandInfo>, FUIAction>
using FUIContextMap = TMap<const TSharedPtr<const FUICommandInfo>, FUIActionContext>
Private Attributes
FCanProduceActionForCommand CanProduceActionForCommand
Determines if this UICommandList is capable of producing an action for the supplied command.
TArray< TWeakPtr< FUICommandList > > ChildUICommandLists
TSet< FName > ContextsInList
Known contexts in this list.
TArray< TWeakPtr< FUICommandList > > ParentUICommandLists
The list of parent and children UICommandLists.
FUIBindingMap UICommandBindingMap
Mapping of command to action.
FUIContextMap UICommandContextMap
Mapping of command to action context, used for special cases and thus much more sparse.
Friends
struct RecursiveCommandDataGetter
Helper struct for list recursion.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FUICommandList >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 14 of file UICommandList.h.
Member Typedef Documentation
FUIBindingMap
using FUICommandList::FUIBindingMap = TMap<const TSharedPtr<const FUICommandInfo>, FUIAction> private
Definition at line 251 of file UICommandList.h.
FUIContextMap
using FUICommandList::FUIContextMap = TMap<const TSharedPtr<const FUICommandInfo>, FUIActionContext> private
Definition at line 252 of file UICommandList.h.
Constructor & Destructor Documentation
~FUICommandList()
virtual FUICommandList::~FUICommandList () inline virtual
Virtual destructor.
Definition at line 20 of file UICommandList.h.
Member Function Documentation
Append()
void FUICommandList::Append (const TSharedRef< FUICommandList > & InCommandsToAppend)
Append commands in InCommandsToAppend to this command list.
CanExecuteAction()
bool FUICommandList::CanExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the CanExecuteAction associated with the provided command info to see if ExecuteAction can be called.
Parameters
InUICommandInfo The command info execute
Referenced by MapAction(), MapAction(), MapAction(), MapAction(), and MapAction().
ConditionalProcessCommandBindings()
bool FUICommandList::ConditionalProcessCommandBindings (const FKey Key, bool bCtrl, bool bAlt, bool bShift, bool bCmd, bool bRepeat) const protected
Helper function to execute delegate or exec command associated with a command (if valid)
Parameters
Key The current key that is pressed
bCtrl True if control is pressed
bAlt True if alt is pressed
bShift True if shift is pressed
bRepeat True if command is repeating (held)
Returns
True if a command was executed, False otherwise
References Key.
DECLARE_DELEGATE_RetVal_OneParam()
FUICommandList::DECLARE_DELEGATE_RetVal_OneParam (bool , FCanProduceActionForCommand , const TSharedRef< const FUICommandInfo > &)
Determines if this UICommandList is capable of producing an action for the supplied command.
ExecuteAction()
virtual bool FUICommandList::ExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const virtual
Executes the action associated with the provided command info Note: It is assumed at this point that CanExecuteAction was already checked.
Parameters
InUICommandInfo The command info execute
Referenced by MapAction(), MapAction(), MapAction(), MapAction(), MapAction(), and MapAction().
GatherContextsForList()
void FUICommandList::GatherContextsForList (TSet< FName > & OutAllContexts) const protected
Returns all contexts associated with this list.
This is a wrapper for GatherContextsForListRecursively
GatherContextsForListRecursively()
void FUICommandList::GatherContextsForListRecursively (TSet< FName > & OutAllContexts, TSet< TSharedRef< const FUICommandList > > & InOutVisitedLists) const protected
Returns all contexts associated with this list.
GetActionForCommand()
const FUIAction * FUICommandList::GetActionForCommand (TSharedPtr< const FUICommandInfo > Command) const
Attempts to find an action for the specified command in the current UICommandList.
This is a wrapper for GetActionForCommandRecursively.
Parameters
Command The UI command for which you are discovering an action
GetActionForCommandRecursively()
const FUIAction * FUICommandList::GetActionForCommandRecursively (const TSharedRef< const FUICommandInfo > & Command, bool bIncludeChildren, bool bIncludeParents, TSet< TSharedRef< const FUICommandList > > & InOutVisitedLists) const protected
Attempts to find an action for the specified command in the current UICommandList.
If it is not found, the action for the specified command is discovered in the children recursively then the parents recursively.
Parameters
Command The UI command for which you are discovering an action
bIncludeChildren If true, children of this command list will be searched in the event that the action is not found
bIncludeParents If true, parents of this command list will be searched in the event that the action is not found
OutVisitedLists The set of visited lists during recursion. This is used to prevent cycles.
GetCheckState()
ECheckBoxState FUICommandList::GetCheckState (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the GetCheckState delegate to see if the visualization of this command in a multibox should appear checked.
Parameters
InUICommandInfo The command info execute
GetContextForCommand()
const FUIActionContext * FUICommandList::GetContextForCommand (TSharedPtr< const FUICommandInfo > Command) const
Attempts to find an context for the specified command in the current UICommandList.
This is a wrapper for GetContextForCommandRecursively.
Parameters
Command The UI command for which you are discovering an action
GetContextForCommandRecursively()
const FUIActionContext * FUICommandList::GetContextForCommandRecursively (const TSharedRef< const FUICommandInfo > & Command, bool bIncludeChildren, bool bIncludeParents, TSet< TSharedRef< const FUICommandList > > & InOutVisitedLists) const protected
Attempts to find an context for the specified command in the current UICommandList.
If it is not found, the context for the specified command is discovered in the children recursively then the parents recursively.
Parameters
Command The UI command for which you are discovering an action
bIncludeChildren If true, children of this command list will be searched in the event that the action is not found
bIncludeParents If true, parents of this command list will be searched in the event that the action is not found
OutVisitedLists The set of visited lists during recursion. This is used to prevent cycles.
GetVisibility()
EVisibility FUICommandList::GetVisibility (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Calls the IsVisible delegate associated with the provided command info to see if the command should be visible in a toolbar.
Parameters
InUICommandInfo The command info execute
IsActionMapped()
bool FUICommandList::IsActionMapped (const TSharedPtr< const FUICommandInfo > InUICommandInfo) const
Checks if an action is already mapped.
Returns
True if an action is already mapped or false otherwise
MapAction() [1/8]
virtual void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, const FUIAction & InUIAction) virtual
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
InUIAction Action to map to this command
MapAction() [2/8]
virtual void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, const FUIAction & InUIAction, const FUIActionContext & InUIActionContext) virtual
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input Additionally, add a container of context objects to also associate with this command.
Parameters
InUICommandInfo The command info to map
InUIAction Action to map to this command
InUIActionContext Action context to map to this command
MapAction() [3/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References ExecuteAction(), and RepeatDisabled.
MapAction() [4/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
CanExecuteAction The delegate to call to see if the command can be executed
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References CanExecuteAction(), ExecuteAction(), and RepeatDisabled.
MapAction() [5/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FGetActionCheckState GetActionCheckState, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
CanExecuteAction The delegate to call to see if the command can be executed
GetActionCheckState The delegate to call to see what the check state of the action should be when visualized in a multibox
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References CanExecuteAction(), ExecuteAction(), and RepeatDisabled.
MapAction() [6/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FGetActionCheckState GetActionCheckState, FIsActionButtonVisible IsVisibleDelegate, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
CanExecuteAction The delegate to call to see if the command can be executed
GetActionCheckState The delegate to call to see what the check state of the action should be when visualized in a multibox
IsVisibleDelegate The delegate to call to see if the command should appear or be hidden when visualized in a multibox
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References CanExecuteAction(), ExecuteAction(), and RepeatDisabled.
MapAction() [7/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FIsActionChecked IsCheckedDelegate, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
CanExecuteAction The delegate to call to see if the command can be executed
IsCheckedDelegate The delegate to call to see if the command should appear checked when visualized in a multibox
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References CanExecuteAction(), ExecuteAction(), and RepeatDisabled.
MapAction() [8/8]
void FUICommandList::MapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo, FExecuteAction ExecuteAction, FCanExecuteAction CanExecuteAction, FIsActionChecked IsCheckedDelegate, FIsActionButtonVisible IsVisibleDelegate, EUIActionRepeatMode RepeatMode = EUIActionRepeatMode::RepeatDisabled)
Maps a command info to a series of delegates that are executed by a multibox or mouse/keyboard input.
Parameters
InUICommandInfo The command info to map
ExecuteAction The delegate to call when the command should be executed
CanExecuteAction The delegate to call to see if the command can be executed
IsCheckedDelegate The delegate to call to see if the command should appear checked when visualized in a multibox
IsVisibleDelegate The delegate to call to see if the command should appear or be hidden when visualized in a multibox
RepeatMode Can this action can be repeated if the chord used to call it is held down?
References CanExecuteAction(), ExecuteAction(), and RepeatDisabled.
ProcessCommandBindings() [1/3]
bool FUICommandList::ProcessCommandBindings (const FKey Key, const FModifierKeysState & ModifierKeysState, const bool bRepeat) const
Processes any UI commands which are activated by the specified key, modifier keys state and input event.
Parameters
Key The current key that is pressed
ModifierKeysState Pressed state of keys that are commonly used as modifiers
bRepeat True if input is repeating (held)
Returns
true if an action was processed
References Key.
ProcessCommandBindings() [2/3]
bool FUICommandList::ProcessCommandBindings (const FKeyEvent & InKeyEvent) const
Processes any UI commands which are activated by the specified key event.
Parameters
InKeyEvent The key event to check
Returns
true if an action was processed
ProcessCommandBindings() [3/3]
bool FUICommandList::ProcessCommandBindings (const FPointerEvent & InMouseEvent) const
Processes any UI commands which are activated by the specified mouse event.
Parameters
InKeyEvent The mouse event to check
Returns
true if an action was processed
SetCanProduceActionForCommand()
void FUICommandList::SetCanProduceActionForCommand (const FCanProduceActionForCommand & NewCanProduceActionForCommand) inline
Sets the delegate that determines if this UICommandList is capable of producing an action for the supplied command.
Definition at line 191 of file UICommandList.h.
References CanProduceActionForCommand.
TryExecuteAction()
bool FUICommandList::TryExecuteAction (const TSharedRef< const FUICommandInfo > InUICommandInfo) const
Attempts to execute the action associated with the provided command info Note: This will check if the action can be executed before finally executing the action.
Parameters
InUICommandInfo The command info execute
UnmapAction()
void FUICommandList::UnmapAction (const TSharedPtr< const FUICommandInfo > InUICommandInfo)
Unmaps a command info that was previously mapped.
Parameters
InUICommandInfo The command info to unmap
Friends And Related Symbol Documentation
RecursiveCommandDataGetter
friend struct RecursiveCommandDataGetter friend
Helper struct for list recursion.
Definition at line 271 of file UICommandList.h.
References RecursiveCommandDataGetter.
Referenced by RecursiveCommandDataGetter.
Field Documentation
CanProduceActionForCommand
FCanProduceActionForCommand FUICommandList::CanProduceActionForCommand private
Determines if this UICommandList is capable of producing an action for the supplied command.
Definition at line 268 of file UICommandList.h.
Referenced by SetCanProduceActionForCommand().
ChildUICommandLists
TArray<TWeakPtr<FUICommandList> > FUICommandList::ChildUICommandLists private
Definition at line 265 of file UICommandList.h.
ContextsInList
TSet<FName> FUICommandList::ContextsInList private
Known contexts in this list.
Each context must be known so we can quickly look up commands from bindings
Definition at line 255 of file UICommandList.h.
ParentUICommandLists
TArray<TWeakPtr<FUICommandList> > FUICommandList::ParentUICommandLists private
The list of parent and children UICommandLists.
Definition at line 264 of file UICommandList.h.
UICommandBindingMap
FUIBindingMap FUICommandList::UICommandBindingMap private
Mapping of command to action.
Definition at line 258 of file UICommandList.h.
UICommandContextMap
FUIContextMap FUICommandList::UICommandContextMap private
Mapping of command to action context, used for special cases and thus much more sparse.
Definition at line 261 of file UICommandList.h.
The documentation for this class was generated from the following file:
UICommandList.h