Unreal Engine 5.6 C++ API: UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes > Struct Template Reference
UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes > Struct Template Reference
#include "IMovieSceneChannelOverrideProvider.h"
Public Member Functions
TNamedChannelOverrideProviderTraits (const FChannelOverrideNames *InChannelNames)
virtual int32 GetChannelOverrideEntityID (FName ChannelName) const override
Convert a channel name to an override entity ID.
virtual FName GetChannelOverrideName (int32 EntityID) const override
Convert an override entity ID to a channel name.
virtual FName GetDefaultChannelTypeName (FName ChannelName) const override
Gets the channel ID for a given channel.
Public Member Functions inherited from UE::MovieScene::FChannelOverrideProviderTraits
virtual ~FChannelOverrideProviderTraits ()
Data Fields
const FChannelOverrideNames * ChannelNames
FName ChannelTypes [sizeof...(OverrideChannelTypes)]
Detailed Description
template<typename... OverrideChannelTypes>
struct UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >
Definition at line 107 of file IMovieSceneChannelOverrideProvider.h.
Constructor & Destructor Documentation
TNamedChannelOverrideProviderTraits()
template<typename... OverrideChannelTypes> UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::TNamedChannelOverrideProviderTraits (const FChannelOverrideNames * InChannelNames) inline
Definition at line 112 of file IMovieSceneChannelOverrideProvider.h.
References ChannelNames, ChannelTypes, and StaticStruct().
Member Function Documentation
GetChannelOverrideEntityID()
template<typename... OverrideChannelTypes> virtual int32 UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::GetChannelOverrideEntityID (FName ChannelName) const inline override virtual
Convert a channel name to an override entity ID.
Implements UE::MovieScene::FChannelOverrideProviderTraits.
Definition at line 124 of file IMovieSceneChannelOverrideProvider.h.
References ChannelNames.
GetChannelOverrideName()
template<typename... OverrideChannelTypes> virtual FName UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::GetChannelOverrideName (int32 EntityID) const inline override virtual
Convert an override entity ID to a channel name.
Implements UE::MovieScene::FChannelOverrideProviderTraits.
Definition at line 129 of file IMovieSceneChannelOverrideProvider.h.
References ChannelNames.
GetDefaultChannelTypeName()
template<typename... OverrideChannelTypes> virtual FName UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::GetDefaultChannelTypeName (FName ChannelName) const inline override virtual
Gets the channel ID for a given channel.
Implements UE::MovieScene::FChannelOverrideProviderTraits.
Definition at line 117 of file IMovieSceneChannelOverrideProvider.h.
References ChannelNames, ChannelTypes, and check.
Field Documentation
ChannelNames
template<typename... OverrideChannelTypes> const FChannelOverrideNames* UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::ChannelNames
Definition at line 109 of file IMovieSceneChannelOverrideProvider.h.
Referenced by TNamedChannelOverrideProviderTraits(), GetChannelOverrideEntityID(), GetChannelOverrideName(), and GetDefaultChannelTypeName().
ChannelTypes
template<typename... OverrideChannelTypes> FName UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::ChannelTypes[sizeof...(OverrideChannelTypes)]
Definition at line 110 of file IMovieSceneChannelOverrideProvider.h.
Referenced by TNamedChannelOverrideProviderTraits(), and GetDefaultChannelTypeName().
The documentation for this struct was generated from the following file:
IMovieSceneChannelOverrideProvider.h