Unreal Engine 5.6 C++ API: PerPlatformProperty::Private::FNameFuncs< FMemoryImageName > Struct Reference
PerPlatformProperty::Private::FNameFuncs< FMemoryImageName > Struct Reference
#include "PerPlatformProperties.h"
Static Public Member Functions
static FMemoryImageName NameToKey (FName Name)
template<typename ValueType>
static void SerializePerPlatformMap (FArchive &Ar, TMemoryImageMap< FMemoryImageName, ValueType > &Map)
template<typename ValueType>
static void SerializePerPlatformMap (FArchive &UnderlyingArchive, FStructuredArchive::FRecord &Record, TMemoryImageMap< FMemoryImageName, ValueType > &Map)
Detailed Description
Definition at line 50 of file CoreUObject/Public/UObject/PerPlatformProperties.h.
Member Function Documentation
NameToKey()
FMemoryImageName PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::NameToKey (FName Name) inline static
Definition at line 52 of file CoreUObject/Public/UObject/PerPlatformProperties.h.
References Name.
SerializePerPlatformMap() [1/2]
template<typename ValueType> void PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::SerializePerPlatformMap (FArchive & Ar, TMemoryImageMap< FMemoryImageName, ValueType > & Map) inline static
Definition at line 55 of file CoreUObject/Public/UObject/PerPlatformProperties.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), Ar, FName, and Map.
SerializePerPlatformMap() [2/2]
template<typename ValueType> void PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::SerializePerPlatformMap (FArchive & UnderlyingArchive, FStructuredArchive::FRecord & Record, TMemoryImageMap< FMemoryImageName, ValueType > & Map) inline static
Definition at line 79 of file CoreUObject/Public/UObject/PerPlatformProperties.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), FName, FArchive::IsLoading(), Map, Record, SA_VALUE, and TEXT.
The documentation for this struct was generated from the following file:
CoreUObject/Public/UObject/PerPlatformProperties.h