Unreal Engine 5.6 C++ API: FBlueprintCompileReinstancer Class Reference
FBlueprintCompileReinstancer Class Reference
#include "KismetReinstanceUtilities.h"
Data Structures
struct FReinstancingState
Public Member Functions
virtual UNREALED_API ~FBlueprintCompileReinstancer ()
virtual UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual UNREALED_API void BlueprintWasRecompiled (UBlueprint *BP, bool bBytecodeOnly)
UNREALED_API void FinalizeFastReinstancing (TArray< UObject * > &ObjectsToReplace)
UNREALED_API void GenerateFieldMappings (TMap< FFieldVariant, FFieldVariant > &FieldMapping)
Helper to gather mappings from the old class's fields to the new class's version.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual bool IsClassObjectReplaced () const
UNREALED_API void PropagateSparseClassDataToNewClass (UClass *NewClass)
Copies an owned sparse class data instance to a new class and frees any owned SCD.
UNREALED_API void ReinstanceObjects (bool bForceAlwaysReinstance=false)
Reinstances all objects in the ObjectReinstancingMap.
UNREALED_API void SaveClassFieldMapping (UClass *InClassToReinstance)
Saves a mapping of field names to their UField equivalents, so we can remap any bytecode that references them later.
UNREALED_API void SaveSparseClassData (const UClass *ForClass)
Populates SCDSnapshot, for use via PropagateSparseClassDataToNewClass.
UNREALED_API void TakeOwnershipOfSparseClassData (UClass *ForClass)
Instructs the reinstancer to take ownership of the sparse class data - doing so will make it difficult to identify archetype data.
UE_DEPRECATED (5.2, "Please use ReplaceInstancesOfClass() instead.") static UNREALED_API void ReplaceInstancesOfClassEx(const FReplaceInstancesOfClassParameters &Parameters)
UE_DEPRECATED (5.2, "Please use the version that takes an FReplaceInstancesOfClassParameters input instead.") static UNREALED_API void BatchReplaceInstancesOfClass(TMap< UClass *
UE_DEPRECATED (5.2, "Please use the version that takes an FReplaceInstancesOfClassParameters input instead.") static UNREALED_API void ReplaceInstancesOfClass(UClass *OldClass
UNREALED_API void UpdateBytecodeReferences (TSet< UBlueprint * > &OutDependentBlueprints, TMap< FFieldVariant, FFieldVariant > &OutFieldMapping)
Updates references to properties and functions of the class that has in the bytecode of dependent blueprints.
UNREALED_API void VerifyReplacement ()
Verify that all instances of the duplicated class have been replaced and collected.
Public Member Functions inherited from TSharedFromThis< FBlueprintCompileReinstancer >
TSharedRef< FBlueprintCompileReinstancer, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBlueprintCompileReinstancer, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static UNREALED_API void BatchReplaceInstancesOfClass (const TMap< UClass *, UClass * > &InOldToNewClassMap, const FReplaceInstancesOfClassParameters &Params)
Batch replaces a mapping of one or more classes to their new class.
static UNREALED_API void CopyPropertiesForUnrelatedObjects (UObject *OldObject, UObject *NewObject, bool bClearExternalReferences, bool bForceDeltaSerialization=false, bool bOnlyHandleDirectSubObjects=false, TMap< UObject *, UObject * > *OldToNewInstanceMap=nullptr, const TMap< UClass *, UClass * > *OldToNewClassMap=nullptr)
Attempts to copy as many properties as possible from the old object to the new.
static TSharedPtr< FBlueprintCompileReinstancer > Create (UClass *InClassToReinstance, EBlueprintCompileReinstancerFlags Flags=EBlueprintCompileReinstancerFlags::AutoInferSaveOnCompile)
static UNREALED_API void FinishUpdateBytecodeReferences (const TSet< UBlueprint * > &DependentBPs, const TMap< FFieldVariant, FFieldVariant > &FieldMappings)
Consumes the set and map populated by calls to UpdateBytecodeReferences.
static UNREALED_API void GetSortedClassHierarchy (UClass *ClassToSearch, TArray< UClass * > &OutHierarchy, UClass **OutNativeParent)
Gathers the full class Hierarchy of the ClassToSearch, sorted top down (0 index being UObject, n being the subclasses)
static UNREALED_API bool IsReinstClass (const UClass *Class)
Returns true if the given class is a REINST class (starts with the 'REINST_' prefix)
static UNREALED_API UClass * MoveCDOToNewClass (UClass *OwnerClass, const TMap< UClass *, UClass * > &OldToNewMap, bool bAvoidCDODuplication)
Function used to safely discard a CDO, so that the class can have its layout changed, callers must move parent CDOs aside before moving child CDOs aside:
static UNREALED_API void MoveDependentSkelToReinst (UClass *OwnerClass, TMap< UClass *, UClass * > &OldToNewMap)
Moves CDOs aside to immutable versions of classes(REINST) so that the CDO's can safely be GC'd.
static UNREALED_API void OptionallyRefreshNodes (UBlueprint *BP)
static UNREALED_API void PreCreateSubObjectsForReinstantiation (const TMap< UClass *, UClass * > &OldToNewClassMap, UObject *OldObject, UObject *NewUObject, TMap< UObject *, UObject * > &CreatedInstanceMap, const TMap< UObject *, UObject * > *OldToNewInstanceMap=nullptr, TArray< TTuple< UObject *, UObject * > > *OrderedListOfObjectToCopy=nullptr)
This method will pre-create all non-default sub object needed for a re-instantiation, what is left is to CopyPropertiesForUnrelatedObjects on the created instances map to finish the re-instancing If the re-instancing is done in a big batch and part to the sub object might already be re-instantiated, you will need to provide those via the OldToNewInstanceMap.
static UNREALED_API void ReconstructOwnerInstances (TSubclassOf< UActorComponent > ComponentClass)
When re-instancing a component, we have to make sure all instance owners' construction scripts are re-ran (in-case modifying the component alters the construction of the actor).
static UNREALED_API void ReplaceInstancesOfClass (UClass *OldClass, UClass *NewClass, const FReplaceInstancesOfClassParameters &Params)
Replace all instances of OldClass with a new instance of NewClass.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Data Fields
UClass PRAGMA_DISABLE_DEPRECATION_WARNINGS const FBatchReplaceInstancesOfClassParameters & BatchParams
UClass UObject TSet< UObject * > bool bClassObjectReplaced = false
UClass UObject TSet< UObject * > bool bool bPreserveRootComponent = true)
UClass *& InOldToNewClassMap
UClass * NewClass
UClass UObject TSet< UObject * > * ObjectsThatShouldUseOldStuff = nullptr
UClass UObject * OriginalCDO = nullptr
Protected Types
enum EReinstClassType { RCT_Unknown , RCT_BpSkeleton , RCT_BpGenerated , RCT_Native }
Cached value, mostly used to determine if we're explicitly targeting the skeleton class or not.
Protected Member Functions
FBlueprintCompileReinstancer ()
Default constructor, can only be used by derived classes.
UNREALED_API FBlueprintCompileReinstancer (UClass *InClassToReinstance, EBlueprintCompileReinstancerFlags Flags=EBlueprintCompileReinstancerFlags::AutoInferSaveOnCompile)
Sets the reinstancer up to work on every object of the specified class.
UNREALED_API void CompileChildren ()
bool IsReinstancingSkeleton () const
UNREALED_API TSharedPtr< FReinstanceFinalizer > ReinstanceFast ()
UNREALED_API TSharedPtr< FReinstanceFinalizer > ReinstanceInner (bool bForceAlwaysReinstance)
UNREALED_API void ReparentChild (UBlueprint *ChildBP)
Reparents the specified blueprint or class to be the duplicated class in order to allow properties to be copied from the previous CDO to the new one.
UNREALED_API void ReparentChild (UClass *ChildClass)
virtual bool ShouldPreserveRootComponentOfReinstancedActor () const
Determine whether reinstancing actors should preserve the root component of the new actor.
Protected Member Functions inherited from TSharedFromThis< FBlueprintCompileReinstancer >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bAllowResaveAtTheEndIfRequested
TRUE if this reinstancer should resave compiled Blueprints if the user has requested it.
bool bHasReinstanced
Whether or not this resinstancer has already reinstanced.
bool bIsRootReinstancer
TRUE if this is the root reinstancer that all other active reinstancing is spawned from.
bool bUseDeltaSerializationToCopyProperties
TRUE if delta serialization should be forced during FBlueprintCompileReinstancer::CopyPropertiesForUnrelatedObjects.
TArray< UBlueprint * > Children
Children of this blueprint, which will need to be recompiled and relinked temporarily to maintain the class layout.
UClass * ClassToReinstance
Reference to the class we're actively reinstancing.
uint32 ClassToReinstanceDefaultValuesCRC
TObjectPtr< UClass > DuplicatedClass
Reference to the duplicate of ClassToReinstance, which all previous instances are now instances of.
TMap< FName, TObjectPtr< UFunction > > FunctionMap
TSet< UObject * > ObjectsThatShouldUseOldStuff
Objects that should keep reference to old class.
TObjectPtr< UObject > OriginalCDO
The original CDO object for the class being actively reinstanced.
void * OriginalSCD
The original Sparse Class Data object for the class being actively reinstanced.
TObjectPtr< UScriptStruct > OriginalSCDStruct
The original SDO Struct for the class being actively reinstanced.
TMap< FName, FProperty * > PropertyMap
Mappings from old fields before recompilation to their new equivalents.
EReinstClassType ReinstClassType
TArray< uint8 > SCDSnapshot
A snapshot of the SCD, currently delta serialized from its archetype - taken before ownership of SCDs is taken.
Static Protected Attributes
static UNREALED_API TSet< TWeakObjectPtr< UBlueprint > > CompiledBlueprintsToSave
static UNREALED_API UClass * HotReloadedNewClass
static UNREALED_API UClass * HotReloadedOldClass
Static Private Member Functions
static UNREALED_API void CacheArchetypes (const TArray< UObject * > &ObjectsToReplace, FEditorCacheArchetypeManager &CacheManager, TSet< UObject * > &CachedArchetypeObjects)
Helper for caching archetypes before objects are reconstructed.
static UNREALED_API FBlake3Hash CalculateConstructionHash (const UClass *ForClass)
Returns a hash identifying the result of constructing an instance of the provided Class.
static UNREALED_API FBlake3Hash CalculateConstructionHashIfNecessary (const UClass *ForClass)
Returns the above, but only if there are instances of the class that would require reinstancing.
static void CategorizeClassesAndInstances (const TMap< UClass *, UClass * > &InOldToNewClassMap, TMap< UClass *, UClass * > &UnchangedClasses, TMap< UClass *, UClass * > &NormalReinstancingClasses, TMap< UClass *, UClass * > &ActiveActorReinstancingClasses, const FReinstancingState &ReinstancingState)
static void CheckAndSaveAttachedActorsOuterPackageToCleanList (TSet< UPackage * > &CleanPackageList, const AActor *Actor)
static void CheckAndSaveOuterPackageToCleanList (TSet< UPackage * > &CleanPackageList, const UObject *InObject)
static void GetObjectsToReinstance (const UClass *OldClass, TArray< UObject * > &ObjectsToReplace)
static UNREALED_API void PreCreateSubObjectsForReinstantiation_Inner (const TSet< UObject * > *OldInstancedSubObjects, const TMap< UClass *, UClass * > &OldToNewClassMap, UObject *OldObject, UObject *NewUObject, TMap< UObject *, UObject * > &CreatedInstanceMap, const TMap< UObject *, UObject * > *OldToNewInstanceMap, TArray< TTuple< UObject *, UObject * > > *OrderedListOfObjectToCopy)
Handles the sub object pre-creation recursively.
static UNREALED_API bool PrePopulateInstancingGraphForArchetype (FObjectInstancingGraph &InstancingGraph, TNotNull< UObject * > OldInstance, UObject *InArchetype, TMap< UObject *, UObject * > *OldToNewInstanceMap=nullptr)
Pre-populate instancing graph for a specified instance if needed.
static void ReinstanceActors (TMap< UClass *, UClass * > &OldToNewClassMap, const FReinstancingState &ReinstancingState)
static void ReinstanceNormalObjects (TMap< UClass *, UClass * > &OldToNewClassMap, const FReinstancingState &ReinstancingState)
static UNREALED_API bool ReinstancerOrderingFunction (UClass *A, UClass *B)
Returns true if A is higher up the class hierarchy.
static void ReinstanceWithVersioningData (const FReinstancingState &ReinstancingState)
static UNREALED_API void ReplaceInstancesOfClass_Inner (const TMap< UClass *, UClass * > &InOldToNewClassMap, const FReplaceInstancesOfClassParameters &Params)
Handles the work of ReplaceInstancesOfClass, handling both normal replacement of instances and batch.
static UNREALED_API void ReplaceObjectHelper (UObject *&OldObject, UClass *OldClass, UObject *&NewUObject, UClass *NewClass, TMap< UObject *, UObject * > &OldToNewInstanceMap, const TMap< UClass *, UClass * > &OldToNewClassMap, TMap< UObject *, FName > &OldToNewNameMap, int32 OldObjIndex, TArray< UObject * > &ObjectsToReplace, TArray< UObject * > &PotentialEditorsForRefreshing, TSet< AActor * > &OwnersToRerunConstructionScript, TFunctionRef< TArray< TObjectPtr< USceneComponent > > &(USceneComponent *)> GetAttachChildrenArray, bool bIsComponent, bool bArchetypesAreUpToDate)
Helper to replace an instance of an object.
static void RestoreClass (TMap< UClass *, UClass * > &OldToNewClassMap, const FReinstancingState &ReinstancingState)
static bool ShouldReinstanceActor (const AActor *OldActor)
static bool ShouldReinstanceObject (const UObject *OldObject, const TMap< UClass *, UClass * > &InOldToNewClassMap, const bool bIsComponent)
static void UpdateObjectBeingDebugged (UObject *InOldObject, UObject *InNewObject)
Friends
struct FBlueprintCompilationManagerImpl
struct FReinstancingJob
struct FRigVMBlueprintCompilationManagerImpl
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from TSharedFromThis< FBlueprintCompileReinstancer >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 107 of file KismetReinstanceUtilities.h.
Member Enumeration Documentation
EReinstClassType
enum FBlueprintCompileReinstancer::EReinstClassType protected
Cached value, mostly used to determine if we're explicitly targeting the skeleton class or not.
Enumerator
RCT_Unknown
RCT_BpSkeleton
RCT_BpGenerated
RCT_Native
Definition at line 148 of file KismetReinstanceUtilities.h.
Constructor & Destructor Documentation
~FBlueprintCompileReinstancer()
virtual UNREALED_API FBlueprintCompileReinstancer::~FBlueprintCompileReinstancer () virtual
FBlueprintCompileReinstancer() [1/2]
FBlueprintCompileReinstancer::FBlueprintCompileReinstancer () inline protected
Default constructor, can only be used by derived classes.
Definition at line 276 of file KismetReinstanceUtilities.h.
References bHasReinstanced, bIsRootReinstancer, ClassToReinstance, ClassToReinstanceDefaultValuesCRC, DuplicatedClass, OriginalCDO, RCT_Unknown, and ReinstClassType.
Referenced by Create().
FBlueprintCompileReinstancer() [2/2]
UNREALED_API FBlueprintCompileReinstancer::FBlueprintCompileReinstancer (UClass * InClassToReinstance, EBlueprintCompileReinstancerFlags Flags = EBlueprintCompileReinstancerFlags::AutoInferSaveOnCompile) protected
Sets the reinstancer up to work on every object of the specified class.
Parameters
InClassToReinstance Class being reinstanced
bIsBytecodeOnly TRUE if only the bytecode is being recompiled
bSkipGC TRUE if garbage collection should be skipped
bAutoInferSaveOnCompile TRUE if the reinstancer should infer whether or not save on compile should occur, FALSE if it should never save on compile
References AutoInferSaveOnCompile, and Flags.
Member Function Documentation
AddReferencedObjects()
virtual UNREALED_API void FBlueprintCompileReinstancer::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
BatchReplaceInstancesOfClass()
UNREALED_API void FBlueprintCompileReinstancer::BatchReplaceInstancesOfClass (const TMap< UClass *, UClass * > & InOldToNewClassMap, const FReplaceInstancesOfClassParameters & Params) static
Batch replaces a mapping of one or more classes to their new class.
References BatchReplaceInstancesOfClass(), InOldToNewClassMap, and Params.
Referenced by BatchReplaceInstancesOfClass().
BlueprintWasRecompiled()
virtual UNREALED_API void FBlueprintCompileReinstancer::BlueprintWasRecompiled (UBlueprint * BP, bool bBytecodeOnly) virtual
CacheArchetypes()
UNREALED_API void FBlueprintCompileReinstancer::CacheArchetypes (const TArray< UObject * > & ObjectsToReplace, FEditorCacheArchetypeManager & CacheManager, TSet< UObject * > & CachedArchetypeObjects) static private
Helper for caching archetypes before objects are reconstructed.
CalculateConstructionHash()
UNREALED_API FBlake3Hash FBlueprintCompileReinstancer::CalculateConstructionHash (const UClass * ForClass) static private
Returns a hash identifying the result of constructing an instance of the provided Class.
CalculateConstructionHashIfNecessary()
UNREALED_API FBlake3Hash FBlueprintCompileReinstancer::CalculateConstructionHashIfNecessary (const UClass * ForClass) static private
Returns the above, but only if there are instances of the class that would require reinstancing.
CategorizeClassesAndInstances()
void FBlueprintCompileReinstancer::CategorizeClassesAndInstances (const TMap< UClass *, UClass * > & InOldToNewClassMap, TMap< UClass *, UClass * > & UnchangedClasses, TMap< UClass *, UClass * > & NormalReinstancingClasses, TMap< UClass *, UClass * > & ActiveActorReinstancingClasses, const FReinstancingState & ReinstancingState) static private
References InOldToNewClassMap.
CheckAndSaveAttachedActorsOuterPackageToCleanList()
void FBlueprintCompileReinstancer::CheckAndSaveAttachedActorsOuterPackageToCleanList (TSet< UPackage * > & CleanPackageList, const AActor * Actor) static private
References Actor.
CheckAndSaveOuterPackageToCleanList()
void FBlueprintCompileReinstancer::CheckAndSaveOuterPackageToCleanList (TSet< UPackage * > & CleanPackageList, const UObject * InObject) static private
CompileChildren()
UNREALED_API void FBlueprintCompileReinstancer::CompileChildren () protected
CopyPropertiesForUnrelatedObjects()
UNREALED_API void FBlueprintCompileReinstancer::CopyPropertiesForUnrelatedObjects (UObject * OldObject, UObject * NewObject, bool bClearExternalReferences, bool bForceDeltaSerialization = false, bool bOnlyHandleDirectSubObjects = false, TMap< UObject *, UObject * > * OldToNewInstanceMap = nullptr, const TMap< UClass *, UClass * > * OldToNewClassMap = nullptr) static
Attempts to copy as many properties as possible from the old object to the new.
Use during BP compilation to copy properties from the old CDO to the new one.
Parameters
OldObject The old object to copy properties from
NewObject The new Object to copy properties to
bClearExternalReferences If true then attempt to replace references to old classes and instances on this object with the corresponding new ones
bForceDeltaSerialization If true the delta serialization will be used when copying
bOnlyHandleDirectSubObjects If true will only copy/handle immediate subobjects
OldToNewInstanceMap If != null it will be used to replace any references found in this object
OldToNewClassMap if != null it will be used to replace any class references found in this object
References NewObject().
Create()
TSharedPtr< FBlueprintCompileReinstancer > FBlueprintCompileReinstancer::Create (UClass * InClassToReinstance, EBlueprintCompileReinstancerFlags Flags = EBlueprintCompileReinstancerFlags::AutoInferSaveOnCompile) inline static
Definition at line 184 of file KismetReinstanceUtilities.h.
References FBlueprintCompileReinstancer(), AutoInferSaveOnCompile, Flags, and MakeShareable().
FinalizeFastReinstancing()
UNREALED_API void FBlueprintCompileReinstancer::FinalizeFastReinstancing (TArray< UObject * > & ObjectsToReplace)
FinishUpdateBytecodeReferences()
UNREALED_API void FBlueprintCompileReinstancer::FinishUpdateBytecodeReferences (const TSet< UBlueprint * > & DependentBPs, const TMap< FFieldVariant, FFieldVariant > & FieldMappings) static
Consumes the set and map populated by calls to UpdateBytecodeReferences.
GenerateFieldMappings()
UNREALED_API void FBlueprintCompileReinstancer::GenerateFieldMappings (TMap< FFieldVariant, FFieldVariant > & FieldMapping)
Helper to gather mappings from the old class's fields to the new class's version.
GetObjectsToReinstance()
void FBlueprintCompileReinstancer::GetObjectsToReinstance (const UClass * OldClass, TArray< UObject * > & ObjectsToReplace) static private
GetReferencerName()
virtual FString FBlueprintCompileReinstancer::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 174 of file KismetReinstanceUtilities.h.
References TEXT.
GetSortedClassHierarchy()
UNREALED_API void FBlueprintCompileReinstancer::GetSortedClassHierarchy (UClass * ClassToSearch, TArray< UClass * > & OutHierarchy, UClass ** OutNativeParent) static
Gathers the full class Hierarchy of the ClassToSearch, sorted top down (0 index being UObject, n being the subclasses)
References GetSortedClassHierarchy().
Referenced by GetSortedClassHierarchy().
IsClassObjectReplaced()
virtual bool FBlueprintCompileReinstancer::IsClassObjectReplaced () const inline virtual
Definition at line 262 of file KismetReinstanceUtilities.h.
References IsClassObjectReplaced().
Referenced by IsClassObjectReplaced().
IsReinstancingSkeleton()
bool FBlueprintCompileReinstancer::IsReinstancingSkeleton () const inline protected
Definition at line 273 of file KismetReinstanceUtilities.h.
References RCT_BpSkeleton, and ReinstClassType.
IsReinstClass()
UNREALED_API bool FBlueprintCompileReinstancer::IsReinstClass (const UClass * Class) static
Returns true if the given class is a REINST class (starts with the 'REINST_' prefix)
References Class, and IsReinstClass().
Referenced by IsReinstClass().
MoveCDOToNewClass()
UNREALED_API UClass * FBlueprintCompileReinstancer::MoveCDOToNewClass (UClass * OwnerClass, const TMap< UClass *, UClass * > & OldToNewMap, bool bAvoidCDODuplication) static
Function used to safely discard a CDO, so that the class can have its layout changed, callers must move parent CDOs aside before moving child CDOs aside:
References MoveCDOToNewClass().
Referenced by MoveCDOToNewClass().
MoveDependentSkelToReinst()
UNREALED_API void FBlueprintCompileReinstancer::MoveDependentSkelToReinst (UClass * OwnerClass, TMap< UClass *, UClass * > & OldToNewMap) static
Moves CDOs aside to immutable versions of classes(REINST) so that the CDO's can safely be GC'd.
These REINST classes will be re-parented to a native parent that we know will not be churning through this function again later, so we avoid O(N^2) processing of REINST classes. Maps each given SKEL class to its appropriate REINST version of itself
References MoveDependentSkelToReinst().
Referenced by MoveDependentSkelToReinst().
OptionallyRefreshNodes()
UNREALED_API void FBlueprintCompileReinstancer::OptionallyRefreshNodes (UBlueprint * BP) static
PreCreateSubObjectsForReinstantiation()
UNREALED_API void FBlueprintCompileReinstancer::PreCreateSubObjectsForReinstantiation (const TMap< UClass *, UClass * > & OldToNewClassMap, UObject * OldObject, UObject * NewUObject, TMap< UObject *, UObject * > & CreatedInstanceMap, const TMap< UObject *, UObject * > * OldToNewInstanceMap = nullptr, TArray< TTuple< UObject *, UObject * > > * OrderedListOfObjectToCopy = nullptr) static
This method will pre-create all non-default sub object needed for a re-instantiation, what is left is to CopyPropertiesForUnrelatedObjects on the created instances map to finish the re-instancing If the re-instancing is done in a big batch and part to the sub object might already be re-instantiated, you will need to provide those via the OldToNewInstanceMap.
Parameters
OldToNewClassMap in case there are subobject that will need new class type
OldObject to pre-create its non-default sub objects
NewUObject where to store those pre-created sub objects
CreatedInstanceMap in/out of the result of all of the pre-created objects
OldToNewInstanceMap optional parameter of the possible re-instanced sub objects if any
OrderedListOfObjectToCopy List of object to copy in order
PreCreateSubObjectsForReinstantiation_Inner()
UNREALED_API void FBlueprintCompileReinstancer::PreCreateSubObjectsForReinstantiation_Inner (const TSet< UObject * > * OldInstancedSubObjects, const TMap< UClass *, UClass * > & OldToNewClassMap, UObject * OldObject, UObject * NewUObject, TMap< UObject *, UObject * > & CreatedInstanceMap, const TMap< UObject *, UObject * > * OldToNewInstanceMap, TArray< TTuple< UObject *, UObject * > > * OrderedListOfObjectToCopy) static private
Handles the sub object pre-creation recursively.
PrePopulateInstancingGraphForArchetype()
UNREALED_API bool FBlueprintCompileReinstancer::PrePopulateInstancingGraphForArchetype (FObjectInstancingGraph & InstancingGraph, TNotNull< UObject * > OldInstance, UObject * InArchetype, TMap< UObject *, UObject * > * OldToNewInstanceMap = nullptr) static private
Pre-populate instancing graph for a specified instance if needed.
Parameters
InstancingGraph The instancing graph to populate
OldInstance Object that is about to be reallocated
InArchetype Archetype of ObjectInstance
OldToNewInstanceMap Possible instance mapping of instances
Returns
false if the instancing graph is not needed
PropagateSparseClassDataToNewClass()
UNREALED_API void FBlueprintCompileReinstancer::PropagateSparseClassDataToNewClass (UClass * NewClass)
Copies an owned sparse class data instance to a new class and frees any owned SCD.
References NewClass.
ReconstructOwnerInstances()
UNREALED_API void FBlueprintCompileReinstancer::ReconstructOwnerInstances (TSubclassOf< UActorComponent > ComponentClass) static
When re-instancing a component, we have to make sure all instance owners' construction scripts are re-ran (in-case modifying the component alters the construction of the actor).
Parameters
ComponentClass Identifies the component that was altered (used to find all its instances, and thusly all instance owners).
References ReconstructOwnerInstances().
Referenced by ReconstructOwnerInstances().
ReinstanceActors()
void FBlueprintCompileReinstancer::ReinstanceActors (TMap< UClass *, UClass * > & OldToNewClassMap, const FReinstancingState & ReinstancingState) static private
ReinstanceFast()
UNREALED_API TSharedPtr< FReinstanceFinalizer > FBlueprintCompileReinstancer::ReinstanceFast () protected
ReinstanceInner()
UNREALED_API TSharedPtr< FReinstanceFinalizer > FBlueprintCompileReinstancer::ReinstanceInner (bool bForceAlwaysReinstance) protected
ReinstanceNormalObjects()
void FBlueprintCompileReinstancer::ReinstanceNormalObjects (TMap< UClass *, UClass * > & OldToNewClassMap, const FReinstancingState & ReinstancingState) static private
ReinstanceObjects()
UNREALED_API void FBlueprintCompileReinstancer::ReinstanceObjects (bool bForceAlwaysReinstance = false)
Reinstances all objects in the ObjectReinstancingMap.
ReinstancerOrderingFunction()
UNREALED_API bool FBlueprintCompileReinstancer::ReinstancerOrderingFunction (UClass * A, UClass * B) static private
Returns true if A is higher up the class hierarchy.
References A, and B.
ReinstanceWithVersioningData()
void FBlueprintCompileReinstancer::ReinstanceWithVersioningData (const FReinstancingState & ReinstancingState) static private
ReparentChild() [1/2]
UNREALED_API void FBlueprintCompileReinstancer::ReparentChild (UBlueprint * ChildBP) protected
Reparents the specified blueprint or class to be the duplicated class in order to allow properties to be copied from the previous CDO to the new one.
ReparentChild() [2/2]
UNREALED_API void FBlueprintCompileReinstancer::ReparentChild (UClass * ChildClass) protected
ReplaceInstancesOfClass()
UNREALED_API void FBlueprintCompileReinstancer::ReplaceInstancesOfClass (UClass * OldClass, UClass * NewClass, const FReplaceInstancesOfClassParameters & Params) static
Replace all instances of OldClass with a new instance of NewClass.
References NewClass, Params, and ReplaceInstancesOfClass().
Referenced by ReplaceInstancesOfClass().
ReplaceInstancesOfClass_Inner()
UNREALED_API void FBlueprintCompileReinstancer::ReplaceInstancesOfClass_Inner (const TMap< UClass *, UClass * > & InOldToNewClassMap, const FReplaceInstancesOfClassParameters & Params) static private
Handles the work of ReplaceInstancesOfClass, handling both normal replacement of instances and batch.
References InOldToNewClassMap, and Params.
ReplaceObjectHelper()
UNREALED_API void FBlueprintCompileReinstancer::ReplaceObjectHelper (UObject *& OldObject, UClass * OldClass, UObject *& NewUObject, UClass * NewClass, TMap< UObject *, UObject * > & OldToNewInstanceMap, const TMap< UClass *, UClass * > & OldToNewClassMap, TMap< UObject *, FName > & OldToNewNameMap, int32 OldObjIndex, TArray< UObject * > & ObjectsToReplace, TArray< UObject * > & PotentialEditorsForRefreshing, TSet< AActor * > & OwnersToRerunConstructionScript, TFunctionRef< TArray< TObjectPtr< USceneComponent > > &(USceneComponent *)> GetAttachChildrenArray, bool bIsComponent, bool bArchetypesAreUpToDate) static private
Helper to replace an instance of an object.
References NewClass.
RestoreClass()
void FBlueprintCompileReinstancer::RestoreClass (TMap< UClass *, UClass * > & OldToNewClassMap, const FReinstancingState & ReinstancingState) static private
SaveClassFieldMapping()
UNREALED_API void FBlueprintCompileReinstancer::SaveClassFieldMapping (UClass * InClassToReinstance)
Saves a mapping of field names to their UField equivalents, so we can remap any bytecode that references them later.
SaveSparseClassData()
UNREALED_API void FBlueprintCompileReinstancer::SaveSparseClassData (const UClass * ForClass)
Populates SCDSnapshot, for use via PropagateSparseClassDataToNewClass.
ShouldPreserveRootComponentOfReinstancedActor()
virtual bool FBlueprintCompileReinstancer::ShouldPreserveRootComponentOfReinstancedActor () const inline protected virtual
Determine whether reinstancing actors should preserve the root component of the new actor.
Definition at line 301 of file KismetReinstanceUtilities.h.
ShouldReinstanceActor()
bool FBlueprintCompileReinstancer::ShouldReinstanceActor (const AActor * OldActor) static private
ShouldReinstanceObject()
bool FBlueprintCompileReinstancer::ShouldReinstanceObject (const UObject * OldObject, const TMap< UClass *, UClass * > & InOldToNewClassMap, const bool bIsComponent) static private
References InOldToNewClassMap.
TakeOwnershipOfSparseClassData()
UNREALED_API void FBlueprintCompileReinstancer::TakeOwnershipOfSparseClassData (UClass * ForClass)
Instructs the reinstancer to take ownership of the sparse class data - doing so will make it difficult to identify archetype data.
UE_DEPRECATED() [1/3]
FBlueprintCompileReinstancer::UE_DEPRECATED (5. 2, "Please use ReplaceInstancesOfClass() instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FBlueprintCompileReinstancer::UE_DEPRECATED (5. 2, "Please use the version that takes an FReplaceInstancesOfClassParameters input instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FBlueprintCompileReinstancer::UE_DEPRECATED (5. 2, "Please use the version that takes an FReplaceInstancesOfClassParameters input instead.")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UpdateBytecodeReferences()
UNREALED_API void FBlueprintCompileReinstancer::UpdateBytecodeReferences (TSet< UBlueprint * > & OutDependentBlueprints, TMap< FFieldVariant, FFieldVariant > & OutFieldMapping)
Updates references to properties and functions of the class that has in the bytecode of dependent blueprints.
UpdateObjectBeingDebugged()
void FBlueprintCompileReinstancer::UpdateObjectBeingDebugged (UObject * InOldObject, UObject * InNewObject) static private
VerifyReplacement()
UNREALED_API void FBlueprintCompileReinstancer::VerifyReplacement ()
Verify that all instances of the duplicated class have been replaced and collected.
References VerifyReplacement().
Referenced by VerifyReplacement().
Friends And Related Symbol Documentation
FBlueprintCompilationManagerImpl
friend struct FBlueprintCompilationManagerImpl friend
Definition at line 110 of file KismetReinstanceUtilities.h.
References FBlueprintCompilationManagerImpl.
Referenced by FBlueprintCompilationManagerImpl.
FReinstancingJob
friend struct FReinstancingJob friend
Definition at line 112 of file KismetReinstanceUtilities.h.
References FReinstancingJob.
Referenced by FReinstancingJob.
FRigVMBlueprintCompilationManagerImpl
friend struct FRigVMBlueprintCompilationManagerImpl friend
Definition at line 111 of file KismetReinstanceUtilities.h.
References FRigVMBlueprintCompilationManagerImpl.
Referenced by FRigVMBlueprintCompilationManagerImpl.
Field Documentation
bAllowResaveAtTheEndIfRequested
bool FBlueprintCompileReinstancer::bAllowResaveAtTheEndIfRequested protected
TRUE if this reinstancer should resave compiled Blueprints if the user has requested it.
Definition at line 166 of file KismetReinstanceUtilities.h.
BatchParams
UClass PRAGMA_DISABLE_DEPRECATION_WARNINGS const FBatchReplaceInstancesOfClassParameters& FBlueprintCompileReinstancer::BatchParams
Initial value:
= FBatchReplaceInstancesOfClassParameters()
PRAGMA_ENABLE_DEPRECATION_WARNINGS
    )
Definition at line 223 of file KismetReinstanceUtilities.h.
bClassObjectReplaced
UClass UObject TSet<UObject*> bool FBlueprintCompileReinstancer::bClassObjectReplaced = false
Definition at line 217 of file KismetReinstanceUtilities.h.
bHasReinstanced
bool FBlueprintCompileReinstancer::bHasReinstanced protected
Whether or not this resinstancer has already reinstanced.
Definition at line 145 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
bIsRootReinstancer
bool FBlueprintCompileReinstancer::bIsRootReinstancer protected
TRUE if this is the root reinstancer that all other active reinstancing is spawned from.
Definition at line 163 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
bPreserveRootComponent
UClass UObject TSet<UObject*> bool bool FBlueprintCompileReinstancer::bPreserveRootComponent = true)
Definition at line 217 of file KismetReinstanceUtilities.h.
bUseDeltaSerializationToCopyProperties
bool FBlueprintCompileReinstancer::bUseDeltaSerializationToCopyProperties protected
TRUE if delta serialization should be forced during FBlueprintCompileReinstancer::CopyPropertiesForUnrelatedObjects.
Definition at line 169 of file KismetReinstanceUtilities.h.
Children
TArray<UBlueprint*> FBlueprintCompileReinstancer::Children protected
Children of this blueprint, which will need to be recompiled and relinked temporarily to maintain the class layout.
Definition at line 138 of file KismetReinstanceUtilities.h.
ClassToReinstance
UClass* FBlueprintCompileReinstancer::ClassToReinstance protected
Reference to the class we're actively reinstancing.
Definition at line 120 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
ClassToReinstanceDefaultValuesCRC
uint32 FBlueprintCompileReinstancer::ClassToReinstanceDefaultValuesCRC protected
Definition at line 157 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
CompiledBlueprintsToSave
UNREALED_API TSet<TWeakObjectPtr<UBlueprint> > FBlueprintCompileReinstancer::CompiledBlueprintsToSave static protected
Definition at line 114 of file KismetReinstanceUtilities.h.
DuplicatedClass
TObjectPtr<UClass> FBlueprintCompileReinstancer::DuplicatedClass protected
Reference to the duplicate of ClassToReinstance, which all previous instances are now instances of.
Definition at line 123 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
FunctionMap
TMap<FName, TObjectPtr<UFunction> > FBlueprintCompileReinstancer::FunctionMap protected
Definition at line 142 of file KismetReinstanceUtilities.h.
HotReloadedNewClass
UNREALED_API UClass* FBlueprintCompileReinstancer::HotReloadedNewClass static protected
Definition at line 117 of file KismetReinstanceUtilities.h.
HotReloadedOldClass
UNREALED_API UClass* FBlueprintCompileReinstancer::HotReloadedOldClass static protected
Definition at line 116 of file KismetReinstanceUtilities.h.
InOldToNewClassMap
UClass* & FBlueprintCompileReinstancer::InOldToNewClassMap
Definition at line 221 of file KismetReinstanceUtilities.h.
Referenced by BatchReplaceInstancesOfClass(), CategorizeClassesAndInstances(), ReplaceInstancesOfClass_Inner(), and ShouldReinstanceObject().
NewClass
UClass* FBlueprintCompileReinstancer::NewClass
Definition at line 217 of file KismetReinstanceUtilities.h.
Referenced by PropagateSparseClassDataToNewClass(), ReplaceInstancesOfClass(), and ReplaceObjectHelper().
ObjectsThatShouldUseOldStuff [1/2]
TSet<UObject*> FBlueprintCompileReinstancer::ObjectsThatShouldUseOldStuff protected
Objects that should keep reference to old class.
Definition at line 160 of file KismetReinstanceUtilities.h.
ObjectsThatShouldUseOldStuff [2/2]
UClass UObject TSet<UObject*>* FBlueprintCompileReinstancer::ObjectsThatShouldUseOldStuff = nullptr
Definition at line 217 of file KismetReinstanceUtilities.h.
OriginalCDO [1/2]
TObjectPtr<UObject> FBlueprintCompileReinstancer::OriginalCDO protected
The original CDO object for the class being actively reinstanced.
Definition at line 126 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer().
OriginalCDO [2/2]
UClass UObject* FBlueprintCompileReinstancer::OriginalCDO = nullptr
Definition at line 217 of file KismetReinstanceUtilities.h.
OriginalSCD
void* FBlueprintCompileReinstancer::OriginalSCD protected
The original Sparse Class Data object for the class being actively reinstanced.
Definition at line 129 of file KismetReinstanceUtilities.h.
OriginalSCDStruct
TObjectPtr<UScriptStruct> FBlueprintCompileReinstancer::OriginalSCDStruct protected
The original SDO Struct for the class being actively reinstanced.
Definition at line 132 of file KismetReinstanceUtilities.h.
PropertyMap
TMap<FName, FProperty*> FBlueprintCompileReinstancer::PropertyMap protected
Mappings from old fields before recompilation to their new equivalents.
Definition at line 141 of file KismetReinstanceUtilities.h.
ReinstClassType
EReinstClassType FBlueprintCompileReinstancer::ReinstClassType protected
Definition at line 155 of file KismetReinstanceUtilities.h.
Referenced by FBlueprintCompileReinstancer(), and IsReinstancingSkeleton().
SCDSnapshot
TArray<uint8> FBlueprintCompileReinstancer::SCDSnapshot protected
A snapshot of the SCD, currently delta serialized from its archetype - taken before ownership of SCDs is taken.
Definition at line 135 of file KismetReinstanceUtilities.h.
The documentation for this class was generated from the following file:
KismetReinstanceUtilities.h