Unreal Engine 5.6 C++ API: TInstancedStruct< BaseStructT > Struct Template Reference
TInstancedStruct< BaseStructT > Struct Template Reference
TInstancedStruct is a type-safe FInstancedStruct wrapper against the given BaseStruct type.
#include "InstancedStruct.h"
Public Member Functions
TInstancedStruct ()=default
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct (const TConstStructView< T > InOther)
This constructor is explicit to avoid accidentally converting struct views to instanced structs (which would result in costly copy of the struct to be made).
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct (const TInstancedStruct< T > &InOther)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct (const UScriptStruct *InScriptStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct (TInstancedStruct< T > &&InOther)
void AddReferencedObjects (FReferenceCollector &Collector)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
const T & Get () const
Returns const reference to the struct, this getter assumes that all data is valid.
const uint8 * GetMemory () const
Returns const pointer to raw struct memory.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
T & GetMutable ()
Returns mutable reference to the struct, this getter assumes that all data is valid.
uint8 * GetMutableMemory ()
Returns a mutable pointer to raw struct memory.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
T * GetMutablePtr ()
Returns mutable pointer to the struct, or nullptr if cast is not valid.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
const T * GetPtr () const
Returns const pointer to the struct, or nullptr if cast is not valid.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
template<typename T = BaseStructT, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
void InitializeAs (TArgs &&... InArgs)
Initializes from struct type and emplace construct.
void InitializeAsScriptStruct (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
Initializes from a raw struct type and optional data.
bool IsValid () const
Returns True if the struct is valid.
bool NetSerialize (FArchive &Ar, UPackageMap *Map, bool &bOutSuccess)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator!= (const TInstancedStruct< T > &Other) const
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct & operator= (const TConstStructView< T > InOther)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct & operator= (const TInstancedStruct< T > &InOther)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TInstancedStruct & operator= (TInstancedStruct< T > &&InOther)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator== (const TInstancedStruct< T > &Other) const
Comparison operators.
void Reset ()
Reset to empty.
bool Serialize (FArchive &Ar)
Static Public Member Functions
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
static TInstancedStruct Make ()
Creates a new TInstancedStruct from templated struct type.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
static TInstancedStruct Make (const T &Struct)
Creates a new TInstancedStruct from templated struct.
template<typename T = BaseStructT, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
static TInstancedStruct Make (TArgs &&... InArgs)
Creates a new TInstancedStruct from the templated type and forward all arguments to constructor.
Private Attributes
FInstancedStruct InstancedStruct
Note: TInstancedStruct is a wrapper for a FInstancedStruct (rather than inheriting) so that it can provide a locked-down type-safe API for use in C++, without being able to accidentally take a reference to the untyped API to workaround the restrictions.
Friends
template<typename U>
struct TInstancedStruct
Detailed Description
template<typename BaseStructT>
struct TInstancedStruct< BaseStructT >
TInstancedStruct is a type-safe FInstancedStruct wrapper against the given BaseStruct type.
Note
When used as a property, this automatically defines the BaseStruct property meta-data.
Example:
UPROPERTY(EditAnywhere, Category = Foo) TInstancedStruct<FTestStructBase> Test;
UPROPERTY(EditAnywhere, Category = Foo) TArray<TInstancedStruct<FTestStructBase>> TestArray;
Definition at line 304 of file StructUtils/InstancedStruct.h.
Constructor & Destructor Documentation
TInstancedStruct() [1/5]
template<typename BaseStructT> TInstancedStruct< BaseStructT >::TInstancedStruct () default
TInstancedStruct() [2/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct< BaseStructT >::TInstancedStruct (const TConstStructView< T > InOther) inline explicit
This constructor is explicit to avoid accidentally converting struct views to instanced structs (which would result in costly copy of the struct to be made).
Implicit conversion could happen e.g. when comparing TInstancedStruct to TConstStructView.
Definition at line 314 of file StructUtils/InstancedStruct.h.
References FConstStructView::GetMemory(), FConstStructView::GetScriptStruct(), and InitializeAsScriptStruct().
TInstancedStruct() [3/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct< BaseStructT >::TInstancedStruct (const UScriptStruct * InScriptStruct) inline explicit
Definition at line 320 of file StructUtils/InstancedStruct.h.
References InitializeAsScriptStruct().
TInstancedStruct() [4/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct< BaseStructT >::TInstancedStruct (const TInstancedStruct< T > & InOther) inline
Definition at line 326 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, and InstancedStruct.
TInstancedStruct() [5/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct< BaseStructT >::TInstancedStruct (TInstancedStruct< T > && InOther) inline
Definition at line 332 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, InstancedStruct, and MoveTemp().
Member Function Documentation
AddReferencedObjects()
template<typename BaseStructT> void TInstancedStruct< BaseStructT >::AddReferencedObjects (FReferenceCollector & Collector) inline
Definition at line 487 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
Get()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> const T & TInstancedStruct< BaseStructT >::Get () const inline
Returns const reference to the struct, this getter assumes that all data is valid.
Definition at line 422 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetMemory()
template<typename BaseStructT> const uint8 * TInstancedStruct< BaseStructT >::GetMemory () const inline
Returns const pointer to raw struct memory.
Definition at line 409 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetMutable()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> T & TInstancedStruct< BaseStructT >::GetMutable () inline
Returns mutable reference to the struct, this getter assumes that all data is valid.
Definition at line 449 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetMutableMemory()
template<typename BaseStructT> uint8 * TInstancedStruct< BaseStructT >::GetMutableMemory () inline
Returns a mutable pointer to raw struct memory.
Definition at line 442 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetMutablePtr()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> T * TInstancedStruct< BaseStructT >::GetMutablePtr () inline
Returns mutable pointer to the struct, or nullptr if cast is not valid.
Definition at line 456 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetPtr()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> const T * TInstancedStruct< BaseStructT >::GetPtr () const inline
Returns const pointer to the struct, or nullptr if cast is not valid.
Definition at line 429 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
GetScriptStruct()
template<typename BaseStructT> const UScriptStruct * TInstancedStruct< BaseStructT >::GetScriptStruct () const inline
Returns struct type.
Definition at line 403 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
InitializeAs()
template<typename BaseStructT> template<typename T = BaseStructT, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> void TInstancedStruct< BaseStructT >::InitializeAs (TArgs &&... InArgs) inline
Initializes from struct type and emplace construct.
Definition at line 370 of file StructUtils/InstancedStruct.h.
References Forward(), and InstancedStruct.
Referenced by Make().
InitializeAsScriptStruct()
template<typename BaseStructT> void TInstancedStruct< BaseStructT >::InitializeAsScriptStruct (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory = nullptr) inline
Initializes from a raw struct type and optional data.
Definition at line 362 of file StructUtils/InstancedStruct.h.
References checkf, TBaseStructureBase< T, bHasStaticStruct >::Get(), InstancedStruct, UStruct::IsChildOf(), and TEXT.
Referenced by TInstancedStruct(), and TInstancedStruct().
IsValid()
template<typename BaseStructT> bool TInstancedStruct< BaseStructT >::IsValid () const inline
Returns True if the struct is valid.
Definition at line 469 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
Make() [1/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct TInstancedStruct< BaseStructT >::Make () inline static
Creates a new TInstancedStruct from templated struct type.
Definition at line 377 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, and TBaseStructureBase< T, bHasStaticStruct >::Get().
Referenced by Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntry< NodeType, ConfigurationType >::CreateFrontendNodeConfiguration().
Make() [2/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct TInstancedStruct< BaseStructT >::Make (const T & Struct) inline static
Creates a new TInstancedStruct from templated struct.
Definition at line 386 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, TBaseStructureBase< T, bHasStaticStruct >::Get(), and Struct.
Make() [3/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename... TArgs, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct TInstancedStruct< BaseStructT >::Make (TArgs &&... InArgs) inline static
Creates a new TInstancedStruct from the templated type and forward all arguments to constructor.
Definition at line 395 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, Forward(), and InitializeAs().
NetSerialize()
template<typename BaseStructT> bool TInstancedStruct< BaseStructT >::NetSerialize (FArchive & Ar, UPackageMap * Map, bool & bOutSuccess) inline
Definition at line 497 of file StructUtils/InstancedStruct.h.
References Ar, InstancedStruct, and Map.
operator!=()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TInstancedStruct< BaseStructT >::operator!= (const TInstancedStruct< T > & Other) const inline
Definition at line 482 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, InstancedStruct, and Other.
operator=() [1/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct & TInstancedStruct< BaseStructT >::operator= (const TConstStructView< T > InOther) inline
Definition at line 338 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, and InstancedStruct.
operator=() [2/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct & TInstancedStruct< BaseStructT >::operator= (const TInstancedStruct< T > & InOther) inline
Definition at line 348 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, and InstancedStruct.
operator=() [3/3]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TInstancedStruct & TInstancedStruct< BaseStructT >::operator= (TInstancedStruct< T > && InOther) inline
Definition at line 355 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, InstancedStruct, and MoveTemp().
operator==()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TInstancedStruct< BaseStructT >::operator== (const TInstancedStruct< T > & Other) const inline
Comparison operators.
Deep compares the struct instance when identical.
Definition at line 476 of file StructUtils/InstancedStruct.h.
References TInstancedStruct, InstancedStruct, and Other.
Reset()
template<typename BaseStructT> void TInstancedStruct< BaseStructT >::Reset () inline
Reset to empty.
Definition at line 415 of file StructUtils/InstancedStruct.h.
References InstancedStruct.
Serialize()
template<typename BaseStructT> bool TInstancedStruct< BaseStructT >::Serialize (FArchive & Ar) inline
Definition at line 492 of file StructUtils/InstancedStruct.h.
References Ar, and InstancedStruct.
Friends And Related Symbol Documentation
TInstancedStruct
template<typename BaseStructT> template<typename U> friend struct TInstancedStruct friend
Definition at line 513 of file StructUtils/InstancedStruct.h.
References TInstancedStruct.
Referenced by TInstancedStruct(), TInstancedStruct(), TInstancedStruct, Make(), Make(), Make(), operator!=(), operator=(), operator=(), operator=(), and operator==().
Field Documentation
InstancedStruct
template<typename BaseStructT> FInstancedStruct TInstancedStruct< BaseStructT >::InstancedStruct private
Note: TInstancedStruct is a wrapper for a FInstancedStruct (rather than inheriting) so that it can provide a locked-down type-safe API for use in C++, without being able to accidentally take a reference to the untyped API to workaround the restrictions.
TInstancedStruct MUST be the same size as FInstancedStruct, as the reflection layer treats a TInstancedStruct as a FInstancedStruct. This means that any reflected APIs (like ExportText) that accept an FInstancedStruct pointer can also accept a TInstancedStruct pointer.
Definition at line 511 of file StructUtils/InstancedStruct.h.
Referenced by TInstancedStruct(), TInstancedStruct(), AddReferencedObjects(), Get(), GetMemory(), GetMutable(), GetMutableMemory(), GetMutablePtr(), GetPtr(), GetScriptStruct(), InitializeAs(), InitializeAsScriptStruct(), IsValid(), NetSerialize(), operator!=(), operator=(), operator=(), operator=(), operator==(), Reset(), and Serialize().
The documentation for this struct was generated from the following file:
StructUtils/InstancedStruct.h