Unreal Engine 5.6 C++ API: TAttributeInterpolator< NumericType > Class Template Reference
TAttributeInterpolator< NumericType > Class Template Reference abstract
Attribute Interpolator Base Class.
#include "AttributeInterpolator.h"
Public Member Functions
TAttributeInterpolator ()
virtual ~TAttributeInterpolator ()
DECLARE_MULTICAST_DELEGATE_OneParam (FInterpolatorEvent, TOptional< NumericType >)
bool Equals (const double &InA, const double &InB, double InTolerance)
bool Equals (const float &InA, const float &InB, double InTolerance)
const NumericType & Get () const
Returns the interpolated value.
double GetOverAllDeltaTime () const
Returns the delta time between the start of the animation and now.
virtual bool IdenticalTo (const TAttributeInterpolator *InOther) const =0
Compares this interpolator to another one.
bool IsEnabled () const
bool IsSet () const
Returns true if this interpolator's value has even been set.
virtual bool IsTypeOf (EAttributeInterpolatorType InType) const =0
Returns true if the interpolator is of a given type.
FInterpolatorEvent & OnInterpolationStarted ()
FInterpolatorEvent & OnInterpolationStopped ()
void Reset () const
Resets the interpolator.
void SetDelayOneShot (float InDelay) const
Sets the delay for the next shot - delays are consumed and only used once.
void SetEnabled (bool InEnabled=true)
void SetTolerance (float InTolerance)
Sets the tolerance on this interpolator.
void SetValue (const NumericType &InValue) const
Set the internal state of the interpolator.
void SetValueAndStop (const NumericType &InValue) const
Set the internal state of the interpolator and disables animation.
void Tick (float InDeltaTime)
Updates the interpolator.
Static Public Member Functions
static bool Equals (const NumericType &InA, const NumericType &InB, double InTolerance=0.001)
Helper function to compare to values - to allow to specialize per type as needed.
Protected Member Functions
virtual void Interpolate () const =0
bool IsPlaying () const
virtual bool PlayIfStopped () const
virtual bool Restart () const
virtual bool Start () const
virtual bool Stop () const
Protected Attributes
bool bEnabled
TOptional< float > Delay
TOptional< NumericType > DesiredValue
TOptional< NumericType > InterpolatedValue
FInterpolatorEvent InterpolationStarted
FInterpolatorEvent InterpolationStopped
TOptional< NumericType > LastValue
TOptional< float > OverallDeltaTime
float Tolerance
Friends
template<typename>
class TAnimatedAttribute
Detailed Description
template<typename NumericType>
class TAttributeInterpolator< NumericType >
Attribute Interpolator Base Class.
Definition at line 19 of file AttributeInterpolator.h.
Constructor & Destructor Documentation
TAttributeInterpolator()
template<typename NumericType> TAttributeInterpolator< NumericType >::TAttributeInterpolator () inline
Definition at line 29 of file AttributeInterpolator.h.
References bEnabled, and Tolerance.
Referenced by TArriveAttributeInterpolator< NumericType >::IdenticalTo(), IdenticalTo(), TEasingAttributeInterpolator< NumericType >::IdenticalTo(), and TVerletAttributeInterpolator< NumericType >::IdenticalTo().
~TAttributeInterpolator()
template<typename NumericType> virtual TAttributeInterpolator< NumericType >::~TAttributeInterpolator () inline virtual
Definition at line 38 of file AttributeInterpolator.h.
Member Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam()
template<typename NumericType> TAttributeInterpolator< NumericType >::DECLARE_MULTICAST_DELEGATE_OneParam (FInterpolatorEvent , TOptional< NumericType >)
Equals() [1/3]
bool TAttributeInterpolator< double >::Equals (const double & InA, const double & InB, double InTolerance) inline
Definition at line 331 of file AttributeInterpolator.h.
References FMath::IsNearlyEqual().
Equals() [2/3]
bool TAttributeInterpolator< float >::Equals (const float & InA, const float & InB, double InTolerance) inline
Definition at line 325 of file AttributeInterpolator.h.
References FMath::IsNearlyEqual().
Equals() [3/3]
template<typename NumericType> bool TAttributeInterpolator< NumericType >::Equals (const NumericType & InA, const NumericType & InB, double InTolerance = 0.001) inline static
Helper function to compare to values - to allow to specialize per type as needed.
Parameters
InA The first value to compare
InB The second value to compare
Returns
True if the two values are considered "equal"
Definition at line 49 of file AttributeInterpolator.h.
Referenced by TArriveAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), SetValue(), and Tick().
Get()
template<typename NumericType> const NumericType & TAttributeInterpolator< NumericType >::Get () const inline
Returns the interpolated value.
Returns
The interpolated value
Definition at line 167 of file AttributeInterpolator.h.
References check, DesiredValue, InterpolatedValue, IsEnabled(), IsSet(), and LastValue.
GetOverAllDeltaTime()
template<typename NumericType> double TAttributeInterpolator< NumericType >::GetOverAllDeltaTime () const inline
Returns the delta time between the start of the animation and now.
Definition at line 224 of file AttributeInterpolator.h.
References IsPlaying(), and OverallDeltaTime.
Referenced by TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), and TVerletAttributeInterpolator< NumericType >::Interpolate().
IdenticalTo()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::IdenticalTo (const TAttributeInterpolator< NumericType > * InOther) const pure virtual
Compares this interpolator to another one.
Parameters
InOther The interpolator to compare this one to
Returns
True if the this interpolator is considered identical to the passed one
Implemented in TArriveAttributeInterpolator< NumericType >, TEasingAttributeInterpolator< NumericType >, and TVerletAttributeInterpolator< NumericType >.
References TAttributeInterpolator().
Interpolate()
template<typename NumericType> virtual void TAttributeInterpolator< NumericType >::Interpolate () const protected pure virtual
Implemented in TArriveAttributeInterpolator< NumericType >, TEasingAttributeInterpolator< NumericType >, and TVerletAttributeInterpolator< NumericType >.
Referenced by Tick().
IsEnabled()
template<typename NumericType> bool TAttributeInterpolator< NumericType >::IsEnabled () const inline
Definition at line 98 of file AttributeInterpolator.h.
References bEnabled.
Referenced by Get().
IsPlaying()
template<typename NumericType> bool TAttributeInterpolator< NumericType >::IsPlaying () const inline protected
Definition at line 269 of file AttributeInterpolator.h.
References InterpolatedValue.
Referenced by GetOverAllDeltaTime(), PlayIfStopped(), TArriveAttributeInterpolator< NumericType >::Restart(), TVerletAttributeInterpolator< NumericType >::Restart(), Stop(), and Tick().
IsSet()
template<typename NumericType> bool TAttributeInterpolator< NumericType >::IsSet () const inline
Returns true if this interpolator's value has even been set.
Returns
True if this interpolator's value has even been set
Definition at line 74 of file AttributeInterpolator.h.
References DesiredValue.
Referenced by Get(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), and TVerletAttributeInterpolator< NumericType >::Interpolate().
IsTypeOf()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::IsTypeOf (EAttributeInterpolatorType InType) const pure virtual
Returns true if the interpolator is of a given type.
Parameters
InType The type to compare agains
Returns
True if the interpolator matches the type
Implemented in TArriveAttributeInterpolator< NumericType >, TEasingAttributeInterpolator< NumericType >, and TVerletAttributeInterpolator< NumericType >.
Referenced by TArriveAttributeInterpolator< NumericType >::IdenticalTo(), TEasingAttributeInterpolator< NumericType >::IdenticalTo(), and TVerletAttributeInterpolator< NumericType >::IdenticalTo().
OnInterpolationStarted()
template<typename NumericType> FInterpolatorEvent & TAttributeInterpolator< NumericType >::OnInterpolationStarted () inline
Definition at line 255 of file AttributeInterpolator.h.
References InterpolationStarted.
OnInterpolationStopped()
template<typename NumericType> FInterpolatorEvent & TAttributeInterpolator< NumericType >::OnInterpolationStopped () inline
Definition at line 260 of file AttributeInterpolator.h.
References InterpolationStopped.
PlayIfStopped()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::PlayIfStopped () const inline protected virtual
Definition at line 282 of file AttributeInterpolator.h.
References IsPlaying(), and Start().
Referenced by Tick().
Reset()
template<typename NumericType> void TAttributeInterpolator< NumericType >::Reset () const inline
Resets the interpolator.
Definition at line 82 of file AttributeInterpolator.h.
References Delay, DesiredValue, InterpolatedValue, InterpolationStopped, LastValue, and Stop().
Restart()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::Restart () const inline protected virtual
Reimplemented in TArriveAttributeInterpolator< NumericType >, and TVerletAttributeInterpolator< NumericType >.
Definition at line 305 of file AttributeInterpolator.h.
References Start().
Referenced by TArriveAttributeInterpolator< NumericType >::Restart(), and TVerletAttributeInterpolator< NumericType >::Restart().
SetDelayOneShot()
template<typename NumericType> void TAttributeInterpolator< NumericType >::SetDelayOneShot (float InDelay) const inline
Sets the delay for the next shot - delays are consumed and only used once.
Definition at line 239 of file AttributeInterpolator.h.
References Delay.
SetEnabled()
template<typename NumericType> void TAttributeInterpolator< NumericType >::SetEnabled (bool InEnabled = true) inline
Definition at line 106 of file AttributeInterpolator.h.
References bEnabled, DesiredValue, and SetValueAndStop().
SetTolerance()
template<typename NumericType> void TAttributeInterpolator< NumericType >::SetTolerance (float InTolerance) inline
Sets the tolerance on this interpolator.
Definition at line 247 of file AttributeInterpolator.h.
References Tolerance.
SetValue()
template<typename NumericType> void TAttributeInterpolator< NumericType >::SetValue (const NumericType & InValue) const inline
Set the internal state of the interpolator.
Parameters
InValue The value to be set on the interpolator
Definition at line 126 of file AttributeInterpolator.h.
References DesiredValue, Equals(), InterpolatedValue, LastValue, SetValueAndStop(), and Tolerance.
SetValueAndStop()
template<typename NumericType> void TAttributeInterpolator< NumericType >::SetValueAndStop (const NumericType & InValue) const inline
Set the internal state of the interpolator and disables animation.
Parameters
InValue The value to be set on the interpolator
Definition at line 152 of file AttributeInterpolator.h.
References DesiredValue, InterpolationStopped, LastValue, and Stop().
Referenced by TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), SetEnabled(), SetValue(), and Tick().
Start()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::Start () const inline protected virtual
Reimplemented in TArriveAttributeInterpolator< NumericType >, and TVerletAttributeInterpolator< NumericType >.
Definition at line 275 of file AttributeInterpolator.h.
References InterpolatedValue, LastValue, and OverallDeltaTime.
Referenced by PlayIfStopped(), Restart(), TArriveAttributeInterpolator< NumericType >::Start(), and TVerletAttributeInterpolator< NumericType >::Start().
Stop()
template<typename NumericType> virtual bool TAttributeInterpolator< NumericType >::Stop () const inline protected virtual
Definition at line 292 of file AttributeInterpolator.h.
References Delay, InterpolatedValue, IsPlaying(), and OverallDeltaTime.
Referenced by Reset(), and SetValueAndStop().
Tick()
template<typename NumericType> void TAttributeInterpolator< NumericType >::Tick (float InDeltaTime) inline
Updates the interpolator.
Definition at line 188 of file AttributeInterpolator.h.
References Delay, DesiredValue, Equals(), Interpolate(), InterpolatedValue, IsPlaying(), LastValue, OverallDeltaTime, PlayIfStopped(), SetValueAndStop(), SMALL_NUMBER, and Tolerance.
Friends And Related Symbol Documentation
TAnimatedAttribute
template<typename NumericType> template<typename> friend class TAnimatedAttribute friend
Definition at line 321 of file AttributeInterpolator.h.
References TAnimatedAttribute.
Referenced by TAnimatedAttribute.
Field Documentation
bEnabled
template<typename NumericType> bool TAttributeInterpolator< NumericType >::bEnabled protected
Definition at line 310 of file AttributeInterpolator.h.
Referenced by TAttributeInterpolator(), IsEnabled(), and SetEnabled().
Delay
template<typename NumericType> TOptional<float> TAttributeInterpolator< NumericType >::Delay mutable protected
Definition at line 312 of file AttributeInterpolator.h.
Referenced by Reset(), SetDelayOneShot(), Stop(), and Tick().
DesiredValue
template<typename NumericType> TOptional<NumericType> TAttributeInterpolator< NumericType >::DesiredValue mutable protected
Definition at line 316 of file AttributeInterpolator.h.
Referenced by Get(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), IsSet(), Reset(), SetEnabled(), SetValue(), SetValueAndStop(), and Tick().
InterpolatedValue
template<typename NumericType> TOptional<NumericType> TAttributeInterpolator< NumericType >::InterpolatedValue mutable protected
Definition at line 314 of file AttributeInterpolator.h.
Referenced by Get(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), IsPlaying(), Reset(), TArriveAttributeInterpolator< NumericType >::Restart(), TVerletAttributeInterpolator< NumericType >::Restart(), SetValue(), Start(), Stop(), and Tick().
InterpolationStarted
template<typename NumericType> FInterpolatorEvent TAttributeInterpolator< NumericType >::InterpolationStarted protected
Definition at line 318 of file AttributeInterpolator.h.
Referenced by OnInterpolationStarted().
InterpolationStopped
template<typename NumericType> FInterpolatorEvent TAttributeInterpolator< NumericType >::InterpolationStopped protected
Definition at line 319 of file AttributeInterpolator.h.
Referenced by OnInterpolationStopped(), Reset(), and SetValueAndStop().
LastValue
template<typename NumericType> TOptional<NumericType> TAttributeInterpolator< NumericType >::LastValue mutable protected
Definition at line 315 of file AttributeInterpolator.h.
Referenced by Get(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TEasingAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), Reset(), TArriveAttributeInterpolator< NumericType >::Restart(), TVerletAttributeInterpolator< NumericType >::Restart(), SetValue(), SetValueAndStop(), Start(), and Tick().
OverallDeltaTime
template<typename NumericType> TOptional<float> TAttributeInterpolator< NumericType >::OverallDeltaTime mutable protected
Definition at line 313 of file AttributeInterpolator.h.
Referenced by GetOverAllDeltaTime(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), Start(), Stop(), and Tick().
Tolerance
template<typename NumericType> float TAttributeInterpolator< NumericType >::Tolerance protected
Definition at line 311 of file AttributeInterpolator.h.
Referenced by TAttributeInterpolator(), TArriveAttributeInterpolator< NumericType >::Interpolate(), TVerletAttributeInterpolator< NumericType >::Interpolate(), SetTolerance(), SetValue(), and Tick().
The documentation for this class was generated from the following file:
AttributeInterpolator.h