Unreal Engine 5.6 C++ API: Metasound::FTime Class Reference
Metasound::FTime Class Reference
#include "MetasoundTime.h"
Public Member Functions
FTime ()
FTime (const FTime &InOtherTime)
FTime (float InTime)
FTime (TimeType InTime)
TimeType GetSeconds () const
Return the time as seconds.
bool operator!= (const FTime &InRHS) const
template<typename ArithmeticType>
ArithmeticType operator* (const FTime &InRHS) const
FTime operator+ (const FTime &InRHS) const
FTime & operator+= (const FTime &InRHS)
FTime operator- (const FTime &InRHS) const
FTime & operator-= (const FTime &InRHS)
template<typename ArithmeticType>
ArithmeticType operator/ (const FTime &InRHS) const
bool operator< (const FTime &InRHS) const
bool operator<= (const FTime &InRHS) const
FTime & operator= (const FTime &InRHS)
bool operator> (const FTime &InRHS) const
bool operator>= (const FTime &InRHS) const
Static Public Member Functions
template<typename ArithmeticType>
static FTime FromMicroseconds (const ArithmeticType &InMicroseconds)
template<typename ArithmeticType>
static FTime FromMilliseconds (const ArithmeticType &InMilliseconds)
template<typename ArithmeticType>
static FTime FromSeconds (const ArithmeticType &InSeconds)
template<typename ArithmeticType = TimeType>
static ArithmeticType ToMicroseconds (const FTime &InTime)
template<typename ArithmeticType = TimeType>
static ArithmeticType ToMilliseconds (const FTime &InTime)
static const FTime & Zero ()
Data Fields
friend FSampleCounter
Private Types
using TimeType = double
Private Attributes
TimeType Time = 0
Friends
FORCEINLINE uint32 GetTypeHash (const FTime &InTime)
template<typename ArithmeticType>
bool operator!= (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator!= (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType operator* (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime operator* (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType & operator*= (ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime & operator*= (FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType operator+ (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime operator+ (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType & operator+= (ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime & operator+= (FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType operator- (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime operator- (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType & operator-= (ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime & operator-= (FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType & operator/ (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime operator/ (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
ArithmeticType & operator/= (ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
FTime & operator/= (FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
bool operator< (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator< (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
bool operator<= (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator<= (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
bool operator== (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator== (const FTime &InLHS, const ArithmeticType &InRHS)
bool operator== (const FTime &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator> (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator> (const FTime &InLHS, const ArithmeticType &InRHS)
template<typename ArithmeticType>
bool operator>= (const ArithmeticType &InLHS, const FTime &InRHS)
template<typename ArithmeticType>
bool operator>= (const FTime &InLHS, const ArithmeticType &InRHS)
Detailed Description
Definition at line 12 of file MetasoundTime.h.
Member Typedef Documentation
TimeType
using Metasound::FTime::TimeType = double private
Definition at line 14 of file MetasoundTime.h.
Constructor & Destructor Documentation
FTime() [1/4]
Metasound::FTime::FTime () inline
Definition at line 20 of file MetasoundTime.h.
Referenced by FTime(), FromMicroseconds(), FromMilliseconds(), FromSeconds(), GetTypeHash, operator!=, operator!=, operator!=(), operator*, operator*, operator*(), operator*=, operator*=, operator+, operator+, operator+(), operator+=, operator+=(), operator+=, operator-, operator-, operator-(), operator-=, operator-=(), operator-=, operator/, operator/, operator/(), operator/=, operator/=, operator<, operator<, operator<(), operator<=, operator<=, operator<=(), operator=(), operator==, operator==, operator==, operator>, operator>, operator>(), operator>=, operator>=, operator>=(), ToMicroseconds(), ToMilliseconds(), and Zero().
FTime() [2/4]
Metasound::FTime::FTime (TimeType InTime) inline explicit
Definition at line 24 of file MetasoundTime.h.
References InTime, and Time.
FTime() [3/4]
Metasound::FTime::FTime (float InTime) inline explicit
Definition at line 29 of file MetasoundTime.h.
References InTime, and Time.
FTime() [4/4]
Metasound::FTime::FTime (const FTime & InOtherTime) inline
Definition at line 34 of file MetasoundTime.h.
References FTime(), and Time.
Member Function Documentation
FromMicroseconds()
template<typename ArithmeticType> FTime Metasound::FTime::FromMicroseconds (const ArithmeticType & InMicroseconds) inline static
Definition at line 356 of file MetasoundTime.h.
References FTime(), and TIsArithmetic< T >::Value.
FromMilliseconds()
template<typename ArithmeticType> FTime Metasound::FTime::FromMilliseconds (const ArithmeticType & InMilliseconds) inline static
Definition at line 349 of file MetasoundTime.h.
References FTime(), and TIsArithmetic< T >::Value.
FromSeconds()
template<typename ArithmeticType> FTime Metasound::FTime::FromSeconds (const ArithmeticType & InSeconds) inline static
Definition at line 342 of file MetasoundTime.h.
References FTime(), and TIsArithmetic< T >::Value.
GetSeconds()
TimeType Metasound::FTime::GetSeconds () const inline
Return the time as seconds.
Definition at line 46 of file MetasoundTime.h.
References Time.
operator!=()
bool Metasound::FTime::operator!= (const FTime & InRHS) const inline
Definition at line 296 of file MetasoundTime.h.
References FTime(), and Time.
operator*()
template<typename ArithmeticType> ArithmeticType Metasound::FTime::operator* (const FTime & InRHS) const inline
Definition at line 172 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator+()
FTime Metasound::FTime::operator+ (const FTime & InRHS) const inline
Definition at line 152 of file MetasoundTime.h.
References FTime(), and Time.
operator+=()
FTime & Metasound::FTime::operator+= (const FTime & InRHS) inline
Definition at line 111 of file MetasoundTime.h.
References FTime(), and Time.
operator-()
FTime Metasound::FTime::operator- (const FTime & InRHS) const inline
Definition at line 133 of file MetasoundTime.h.
References FTime(), and Time.
operator-=()
FTime & Metasound::FTime::operator-= (const FTime & InRHS) inline
Definition at line 89 of file MetasoundTime.h.
References FTime(), and Time.
operator/()
template<typename ArithmeticType> ArithmeticType Metasound::FTime::operator/ (const FTime & InRHS) const inline
Definition at line 193 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator<()
bool Metasound::FTime::operator< (const FTime & InRHS) const inline
Definition at line 213 of file MetasoundTime.h.
References FTime(), and Time.
operator<=()
bool Metasound::FTime::operator<= (const FTime & InRHS) const inline
Definition at line 232 of file MetasoundTime.h.
References FTime(), and Time.
operator=()
FTime & Metasound::FTime::operator= (const FTime & InRHS) inline
Definition at line 51 of file MetasoundTime.h.
References FTime(), and Time.
operator>()
bool Metasound::FTime::operator> (const FTime & InRHS) const inline
Definition at line 251 of file MetasoundTime.h.
References FTime(), and Time.
operator>=()
bool Metasound::FTime::operator>= (const FTime & InRHS) const inline
Definition at line 270 of file MetasoundTime.h.
References FTime(), and Time.
ToMicroseconds()
template<typename ArithmeticType = TimeType> ArithmeticType Metasound::FTime::ToMicroseconds (const FTime & InTime) inline static
Definition at line 335 of file MetasoundTime.h.
References FTime(), InTime, and TIsArithmetic< T >::Value.
ToMilliseconds()
template<typename ArithmeticType = TimeType> ArithmeticType Metasound::FTime::ToMilliseconds (const FTime & InTime) inline static
Definition at line 328 of file MetasoundTime.h.
References FTime(), InTime, and TIsArithmetic< T >::Value.
Zero()
const FTime & Metasound::FTime::Zero () inline static
Definition at line 39 of file MetasoundTime.h.
References FTime().
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FTime & InTime) friend
Definition at line 362 of file MetasoundTime.h.
References FTime(), FORCEINLINE, and InTime.
operator!= [1/2]
template<typename ArithmeticType> bool operator!= (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 290 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator!= [2/2]
template<typename ArithmeticType> bool operator!= (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 302 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator* [1/2]
template<typename ArithmeticType> ArithmeticType operator* (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 179 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator* [2/2]
template<typename ArithmeticType> FTime operator* (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 186 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator*= [1/2]
template<typename ArithmeticType> ArithmeticType & operator*= (ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 58 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator*= [2/2]
template<typename ArithmeticType> FTime & operator*= (FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 66 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator+ [1/2]
template<typename ArithmeticType> ArithmeticType operator+ (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 158 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator+ [2/2]
template<typename ArithmeticType> FTime operator+ (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 165 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator+= [1/2]
template<typename ArithmeticType> ArithmeticType & operator+= (ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 118 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator+= [2/2]
template<typename ArithmeticType> FTime & operator+= (FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 126 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator- [1/2]
template<typename ArithmeticType> ArithmeticType operator- (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 139 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator- [2/2]
template<typename ArithmeticType> FTime operator- (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 146 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator-= [1/2]
template<typename ArithmeticType> ArithmeticType & operator-= (ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 96 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator-= [2/2]
template<typename ArithmeticType> FTime & operator-= (FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 104 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator/ [1/2]
template<typename ArithmeticType> ArithmeticType & operator/ (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 200 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator/ [2/2]
template<typename ArithmeticType> FTime operator/ (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 207 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator/= [1/2]
template<typename ArithmeticType> ArithmeticType & operator/= (ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 74 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator/= [2/2]
template<typename ArithmeticType> FTime & operator/= (FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 82 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator< [1/2]
template<typename ArithmeticType> bool operator< (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 219 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator< [2/2]
template<typename ArithmeticType> bool operator< (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 226 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator<= [1/2]
template<typename ArithmeticType> bool operator<= (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 238 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator<= [2/2]
template<typename ArithmeticType> bool operator<= (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 245 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator== [1/3]
template<typename ArithmeticType> bool operator== (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 314 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator== [2/3]
template<typename ArithmeticType> bool operator== (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 321 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator== [3/3]
bool operator== (const FTime & InLHS, const FTime & InRHS) friend
Definition at line 308 of file MetasoundTime.h.
References FTime(), and Time.
operator> [1/2]
template<typename ArithmeticType> bool operator> (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 264 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator> [2/2]
template<typename ArithmeticType> bool operator> (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 257 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator>= [1/2]
template<typename ArithmeticType> bool operator>= (const ArithmeticType & InLHS, const FTime & InRHS) friend
Definition at line 276 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
operator>= [2/2]
template<typename ArithmeticType> bool operator>= (const FTime & InLHS, const ArithmeticType & InRHS) friend
Definition at line 283 of file MetasoundTime.h.
References FTime(), Time, and TIsArithmetic< T >::Value.
Field Documentation
FSampleCounter
friend Metasound::FTime::FSampleCounter
Definition at line 367 of file MetasoundTime.h.
Time
TimeType Metasound::FTime::Time = 0 private
Definition at line 17 of file MetasoundTime.h.
Referenced by FTime(), FTime(), FTime(), GetSeconds(), operator!=, operator!=, operator!=(), operator*, operator*, operator*(), operator*=, operator*=, operator+, operator+, operator+(), operator+=, operator+=(), operator+=, operator-, operator-, operator-(), operator-=, operator-=(), operator-=, operator/, operator/, operator/(), operator/=, operator/=, operator<, operator<, operator<(), operator<=, operator<=, operator<=(), operator=(), operator==, operator==, operator==, operator>, operator>, operator>(), operator>=, operator>=, and operator>=().
The documentation for this class was generated from the following file:
MetasoundTime.h