Unreal Engine 5.6 C++ API: FEnvQueryInstance Struct Reference
FEnvQueryInstance Struct Reference
#include "EnvQueryTypes.h"
Public Types
typedef float FNamedParamValueType
Public Member Functions
AIMODULE_API FEnvQueryInstance ()
AIMODULE_API FEnvQueryInstance (const FEnvQueryInstance &Other)
AIMODULE_API ~FEnvQueryInstance ()
template<typename TypeItem>
void AddItemData (TArray< typename TypeItem::FValueType > &ItemCollection)
AddItemData specialization for arrays if values.
template<typename TypeItem, typename TypeValue>
void AddItemData (TArray< TypeValue > &ItemCollection)
template<typename TypeItem>
void AddItemData (typename TypeItem::FValueType ItemValue)
template<typename TypeItem, typename TypeValue>
void AddItemData (TypeValue ItemValue)
bool CanBatchTest () const
check if current test can batch its calculations
FORCEINLINE void DecStats ()
AIMODULE_API void ExecuteOneStep (double TimeLimit)
execute single step of query
FORCEINLINE uint32 GetAllocatedSize () const
AIMODULE_API FBox GetBoundingBox () const
FORCEINLINE uint32 GetContextAllocatedSize () const
AIMODULE_API FString GetExecutionTimeDescription () const
describe for logging purposes what the query spent time on
FORCEINLINE void IncStats ()
bool IsCurrentlyRunningAsync () const
bool IsInSingleItemFinalSearch () const
AIMODULE_API void Log (const FString Msg) const
AIMODULE_API bool PrepareContext (UClass *Context, FEnvQueryContextData &ContextData)
update context cache
AIMODULE_API bool PrepareContext (UClass *Context, TArray< AActor * > &Data)
helpers for reading actor data from context
AIMODULE_API bool PrepareContext (UClass *Context, TArray< FEnvQuerySpatialData > &Data)
helpers for reading spatial data from context
AIMODULE_API bool PrepareContext (UClass *Context, TArray< FRotator > &Data)
AIMODULE_API bool PrepareContext (UClass *Context, TArray< FVector > &Data)
AIMODULE_API void ReserveItemData (int32 NumAdditionalItems)
raw data operations
AIMODULE_API void StripRedundantData ()
removes all runtime data that can be used for debugging (not a part of actual query result)
Data Fields
uint8 bFoundSingleResult: 1
used to breaking from item iterator loops
uint8 bHasLoggedTimeLimitWarning: 1
true if this query has logged a warning that it overran the time limit
uint8 bIsCurrentlyRunningAsync: 1
true if current Generator or Test is running asynchronously
uint8 bPassOnSingleResult: 1
set when testing final condition of an option
uint8 bStoreDebugInfo: 1
set to true to store additional debug info
TMap< UClass *, FEnvQueryContextData > ContextCache
contexts in use
double CurrentStepTimeLimit
if > 0 then it's how much time query has for performing current step
int32 CurrentTest
currently processed test (-1 = generator)
int32 CurrentTestStartingItem
non-zero if test run last step has been stopped mid-process.
FEnvQueryDebugData DebugData
FQueryFinishedSignature FinishDelegate
observer's delegate
double GenerationTimeWarningSeconds = 0.01f
Maximum EQS Generator duration (in seconds) before a warning is reported in non-shipping build.
TArray< FEnvQueryItemDetails > ItemDetails
list of item details
UEnvQueryItemType_ActorBase * ItemTypeActorCDO
item type's CDO for actor tests
UEnvQueryItemType_VectorBase * ItemTypeVectorCDO
item type's CDO for location tests
EEnvQueryRunMode::Type Mode
run mode
TMap< FName, FNamedParamValueType > NamedParams
execution params
int32 NumProcessedItems
number of items processed in current step
int32 NumValidItems
number of valid items on list
TArray< FEnvQueryOptionInstance > Options
list of options
FString QueryName
short name of query template - friendly name for debugging
double StartTime
timestamp of creating query instance
double TotalExecutionTime
time spent executing this query
FName UniqueName
unique name of query template - object name
uint16 ValueSize
size of current value
UWorld * World
world owning this query instance
Static Public Attributes
static AIMODULE_API bool bDebuggingInfoEnabled
Protected Member Functions
AIMODULE_API void FinalizeGeneration ()
prepare item data after generator has finished
AIMODULE_API void FinalizeQuery ()
final pass on items of finished query
AIMODULE_API void FinalizeTest ()
update costs and flags after test has finished
AIMODULE_API void NormalizeScores ()
normalize total score in range 0..1
AIMODULE_API void PickRandomItemOfScoreAtLeast (float MinScore)
pick one of items with score equal or higher than specified
AIMODULE_API void PickSingleItem (int32 ItemIndex)
discard all items but one
AIMODULE_API void SortScores ()
sort all scores, from highest to lowest
Detailed Description
Definition at line 758 of file EnvQueryTypes.h.
Member Typedef Documentation
FNamedParamValueType
typedef float FEnvQueryInstance::FNamedParamValueType
Definition at line 760 of file EnvQueryTypes.h.
Constructor & Destructor Documentation
FEnvQueryInstance() [1/2]
AIMODULE_API FEnvQueryInstance::FEnvQueryInstance ()
Referenced by FEnvQueryInstance(), and GetExecutionTimeDescription().
FEnvQueryInstance() [2/2]
AIMODULE_API FEnvQueryInstance::FEnvQueryInstance (const FEnvQueryInstance & Other)
References FEnvQueryInstance(), and Other.
~FEnvQueryInstance()
AIMODULE_API FEnvQueryInstance::~FEnvQueryInstance ()
Member Function Documentation
AddItemData() [1/4]
template<typename TypeItem> void FEnvQueryInstance::AddItemData (TArray< typename TypeItem::FValueType > & ItemCollection) inline
AddItemData specialization for arrays if values.
Definition at line 887 of file EnvQueryTypes.h.
References check, DEC_MEMORY_STAT_BY, GetDefault(), INC_MEMORY_STAT_BY, Item, TArray< InElementType, InAllocatorType >::Num(), RawData, and ValueSize.
AddItemData() [2/4]
template<typename TypeItem, typename TypeValue> void FEnvQueryInstance::AddItemData (TArray< TypeValue > & ItemCollection) inline
Definition at line 919 of file EnvQueryTypes.h.
References AddItemData(), and Item.
AddItemData() [3/4]
template<typename TypeItem> void FEnvQueryInstance::AddItemData (typename TypeItem::FValueType ItemValue) inline
Definition at line 869 of file EnvQueryTypes.h.
References check, DEC_MEMORY_STAT_BY, GetDefault(), INC_MEMORY_STAT_BY, RawData, and ValueSize.
Referenced by AddItemData(), and AddItemData().
AddItemData() [4/4]
template<typename TypeItem, typename TypeValue> void FEnvQueryInstance::AddItemData (TypeValue ItemValue) inline
Definition at line 913 of file EnvQueryTypes.h.
References AddItemData().
CanBatchTest()
bool FEnvQueryInstance::CanBatchTest () const inline
check if current test can batch its calculations
Definition at line 861 of file EnvQueryTypes.h.
References IsInSingleItemFinalSearch().
DecStats()
FORCEINLINE void FEnvQueryInstance::DecStats () inline
Definition at line 974 of file EnvQueryTypes.h.
References FORCEINLINE.
ExecuteOneStep()
AIMODULE_API void FEnvQueryInstance::ExecuteOneStep (double TimeLimit)
execute single step of query
References TimeLimit.
FinalizeGeneration()
AIMODULE_API void FEnvQueryInstance::FinalizeGeneration () protected
prepare item data after generator has finished
FinalizeQuery()
AIMODULE_API void FEnvQueryInstance::FinalizeQuery () protected
final pass on items of finished query
FinalizeTest()
AIMODULE_API void FEnvQueryInstance::FinalizeTest () protected
update costs and flags after test has finished
GetAllocatedSize()
FORCEINLINE uint32 FEnvQueryInstance::GetAllocatedSize () const inline
Definition at line 971 of file EnvQueryTypes.h.
References FORCEINLINE.
Referenced by StripRedundantData().
GetBoundingBox()
AIMODULE_API FBox FEnvQueryInstance::GetBoundingBox () const
GetContextAllocatedSize()
FORCEINLINE uint32 FEnvQueryInstance::GetContextAllocatedSize () const inline
Definition at line 972 of file EnvQueryTypes.h.
References FORCEINLINE.
GetExecutionTimeDescription()
AIMODULE_API FString FEnvQueryInstance::GetExecutionTimeDescription () const
describe for logging purposes what the query spent time on
References FEnvQueryInstance(), CurrentTestStartingItem, INDEX_NONE, and Instance.
IncStats()
FORCEINLINE void FEnvQueryInstance::IncStats () inline
Definition at line 973 of file EnvQueryTypes.h.
References FORCEINLINE.
Referenced by StripRedundantData().
IsCurrentlyRunningAsync()
bool FEnvQueryInstance::IsCurrentlyRunningAsync () const inline
Definition at line 863 of file EnvQueryTypes.h.
References bIsCurrentlyRunningAsync.
IsInSingleItemFinalSearch()
bool FEnvQueryInstance::IsInSingleItemFinalSearch () const inline
Definition at line 859 of file EnvQueryTypes.h.
References bPassOnSingleResult.
Referenced by CanBatchTest().
Log()
AIMODULE_API void FEnvQueryInstance::Log (const FString Msg) const
NormalizeScores()
AIMODULE_API void FEnvQueryInstance::NormalizeScores () protected
normalize total score in range 0..1
PickRandomItemOfScoreAtLeast()
AIMODULE_API void FEnvQueryInstance::PickRandomItemOfScoreAtLeast (float MinScore) protected
pick one of items with score equal or higher than specified
PickSingleItem()
AIMODULE_API void FEnvQueryInstance::PickSingleItem (int32 ItemIndex) protected
discard all items but one
PrepareContext() [1/5]
AIMODULE_API bool FEnvQueryInstance::PrepareContext (UClass * Context, FEnvQueryContextData & ContextData)
update context cache
PrepareContext() [2/5]
AIMODULE_API bool FEnvQueryInstance::PrepareContext (UClass * Context, TArray< AActor * > & Data)
helpers for reading actor data from context
PrepareContext() [3/5]
AIMODULE_API bool FEnvQueryInstance::PrepareContext (UClass * Context, TArray< FEnvQuerySpatialData > & Data)
helpers for reading spatial data from context
PrepareContext() [4/5]
AIMODULE_API bool FEnvQueryInstance::PrepareContext (UClass * Context, TArray< FRotator > & Data)
PrepareContext() [5/5]
AIMODULE_API bool FEnvQueryInstance::PrepareContext (UClass * Context, TArray< FVector > & Data)
ReserveItemData()
AIMODULE_API void FEnvQueryInstance::ReserveItemData (int32 NumAdditionalItems)
raw data operations
SortScores()
AIMODULE_API void FEnvQueryInstance::SortScores () protected
sort all scores, from highest to lowest
StripRedundantData()
AIMODULE_API void FEnvQueryInstance::StripRedundantData ()
removes all runtime data that can be used for debugging (not a part of actual query result)
References FORCEINLINE, GetAllocatedSize(), and IncStats().
Field Documentation
bDebuggingInfoEnabled
AIMODULE_API bool FEnvQueryInstance::bDebuggingInfoEnabled static
Definition at line 1279 of file EnvQueryTypes.h.
bFoundSingleResult
uint8 FEnvQueryInstance::bFoundSingleResult
used to breaking from item iterator loops
Definition at line 808 of file EnvQueryTypes.h.
bHasLoggedTimeLimitWarning
uint8 FEnvQueryInstance::bHasLoggedTimeLimitWarning
true if this query has logged a warning that it overran the time limit
Definition at line 814 of file EnvQueryTypes.h.
bIsCurrentlyRunningAsync
uint8 FEnvQueryInstance::bIsCurrentlyRunningAsync
true if current Generator or Test is running asynchronously
Definition at line 817 of file EnvQueryTypes.h.
Referenced by IsCurrentlyRunningAsync().
bPassOnSingleResult
uint8 FEnvQueryInstance::bPassOnSingleResult
set when testing final condition of an option
Definition at line 811 of file EnvQueryTypes.h.
Referenced by IsInSingleItemFinalSearch().
bStoreDebugInfo
uint8 FEnvQueryInstance::bStoreDebugInfo
set to true to store additional debug info
Definition at line 804 of file EnvQueryTypes.h.
ContextCache
TMap<UClass*, FEnvQueryContextData> FEnvQueryInstance::ContextCache
contexts in use
Definition at line 778 of file EnvQueryTypes.h.
CurrentStepTimeLimit
double FEnvQueryInstance::CurrentStepTimeLimit
if > 0 then it's how much time query has for performing current step
Definition at line 826 of file EnvQueryTypes.h.
CurrentTest
int32 FEnvQueryInstance::CurrentTest
currently processed test (-1 = generator)
Definition at line 784 of file EnvQueryTypes.h.
CurrentTestStartingItem
int32 FEnvQueryInstance::CurrentTestStartingItem
non-zero if test run last step has been stopped mid-process.
This indicates index of the first item that needs processing when resumed
Definition at line 788 of file EnvQueryTypes.h.
Referenced by GetExecutionTimeDescription().
DebugData
FEnvQueryDebugData FEnvQueryInstance::DebugData
Definition at line 1278 of file EnvQueryTypes.h.
FinishDelegate
FQueryFinishedSignature FEnvQueryInstance::FinishDelegate
observer's delegate
Definition at line 772 of file EnvQueryTypes.h.
GenerationTimeWarningSeconds
double FEnvQueryInstance::GenerationTimeWarningSeconds = 0.01f
Maximum EQS Generator duration (in seconds) before a warning is reported in non-shipping build.
Definition at line 830 of file EnvQueryTypes.h.
ItemDetails
TArray<FEnvQueryItemDetails> FEnvQueryInstance::ItemDetails
list of item details
Definition at line 791 of file EnvQueryTypes.h.
ItemTypeActorCDO
UEnvQueryItemType_ActorBase* FEnvQueryInstance::ItemTypeActorCDO
item type's CDO for actor tests
Definition at line 840 of file EnvQueryTypes.h.
ItemTypeVectorCDO
UEnvQueryItemType_VectorBase* FEnvQueryInstance::ItemTypeVectorCDO
item type's CDO for location tests
Definition at line 837 of file EnvQueryTypes.h.
Mode
EEnvQueryRunMode::Type FEnvQueryInstance::Mode
run mode
Definition at line 834 of file EnvQueryTypes.h.
NamedParams
TMap<FName, FNamedParamValueType> FEnvQueryInstance::NamedParams
execution params
Definition at line 775 of file EnvQueryTypes.h.
NumProcessedItems
int32 FEnvQueryInstance::NumProcessedItems
number of items processed in current step
Definition at line 801 of file EnvQueryTypes.h.
NumValidItems
int32 FEnvQueryInstance::NumValidItems
number of valid items on list
Definition at line 794 of file EnvQueryTypes.h.
Options
TArray<FEnvQueryOptionInstance> FEnvQueryInstance::Options
list of options
Definition at line 781 of file EnvQueryTypes.h.
QueryName
FString FEnvQueryInstance::QueryName
short name of query template - friendly name for debugging
Definition at line 763 of file EnvQueryTypes.h.
StartTime
double FEnvQueryInstance::StartTime
timestamp of creating query instance
Definition at line 820 of file EnvQueryTypes.h.
TotalExecutionTime
double FEnvQueryInstance::TotalExecutionTime
time spent executing this query
Definition at line 823 of file EnvQueryTypes.h.
UniqueName
FName FEnvQueryInstance::UniqueName
unique name of query template - object name
Definition at line 766 of file EnvQueryTypes.h.
ValueSize
uint16 FEnvQueryInstance::ValueSize
size of current value
Definition at line 797 of file EnvQueryTypes.h.
Referenced by AddItemData(), and AddItemData().
World
UWorld* FEnvQueryInstance::World
world owning this query instance
Definition at line 769 of file EnvQueryTypes.h.
The documentation for this struct was generated from the following file:
EnvQueryTypes.h