Unreal Engine 5.6 C++ API: FLiveLinkBaseDataStruct< BaseType > Class Template Reference
FLiveLinkBaseDataStruct< BaseType > Class Template Reference
Wrapper around FStructOnScope to handle FLiveLinkBaseFrameData Can safely cast to the specific outer type.
#include "LiveLinkTypes.h"
Data Structures
struct FCastImpl
Public Member Functions
FLiveLinkBaseDataStruct ()=default
FLiveLinkBaseDataStruct (const UScriptStruct *InType)
FLiveLinkBaseDataStruct (const UScriptStruct *InType, BaseType *InData)
FLiveLinkBaseDataStruct (FLiveLinkBaseDataStruct &&InOther)
template<typename Type>
Type * Cast ()
template<typename Type>
const Type * Cast () const
BaseType * CloneData () const
BaseType * GetBaseData ()
const BaseType * GetBaseData () const
const UScriptStruct * GetStruct () const
template<typename DataType>
void InitializeWith (const DataType *InData)
Initialize ourselves with another data struct directly.
void InitializeWith (const FLiveLinkBaseDataStruct &InOther)
Initialize ourselves with another data struct.
void InitializeWith (const UScriptStruct *InOtherStruct, const BaseType *InData)
Initialize ourselves with another struct.
bool IsValid () const
bool operator!= (const FLiveLinkBaseDataStruct &Other) const
FLiveLinkBaseDataStruct & operator= (FLiveLinkBaseDataStruct &&InOther)
bool operator== (const FLiveLinkBaseDataStruct &Other) const
void Reset ()
Protected Attributes
FStructOnScope WrappedStruct
Friends
FArchive & operator<< (FArchive &Ar, FLiveLinkBaseDataStruct &InStruct)
Detailed Description
template<typename BaseType>
class FLiveLinkBaseDataStruct< BaseType >
Wrapper around FStructOnScope to handle FLiveLinkBaseFrameData Can safely cast to the specific outer type.
Definition at line 300 of file LiveLinkTypes.h.
Constructor & Destructor Documentation
FLiveLinkBaseDataStruct() [1/4]
template<typename BaseType> FLiveLinkBaseDataStruct< BaseType >::FLiveLinkBaseDataStruct () default
FLiveLinkBaseDataStruct() [2/4]
template<typename BaseType> FLiveLinkBaseDataStruct< BaseType >::FLiveLinkBaseDataStruct (const UScriptStruct * InType, BaseType * InData) inline
Definition at line 306 of file LiveLinkTypes.h.
FLiveLinkBaseDataStruct() [3/4]
template<typename BaseType> FLiveLinkBaseDataStruct< BaseType >::FLiveLinkBaseDataStruct (const UScriptStruct * InType) inline
Definition at line 312 of file LiveLinkTypes.h.
FLiveLinkBaseDataStruct() [4/4]
template<typename BaseType> FLiveLinkBaseDataStruct< BaseType >::FLiveLinkBaseDataStruct (FLiveLinkBaseDataStruct< BaseType > && InOther) inline
Definition at line 317 of file LiveLinkTypes.h.
Member Function Documentation
Cast() [1/2]
template<typename BaseType> template<typename Type> Type * FLiveLinkBaseDataStruct< BaseType >::Cast () inline
Definition at line 402 of file LiveLinkTypes.h.
Referenced by FLiveLinkBaseDataStruct< BaseType >::FCastImpl< Type >::ConstCast().
Cast() [2/2]
template<typename BaseType> template<typename Type> const Type * FLiveLinkBaseDataStruct< BaseType >::Cast () const inline
Definition at line 408 of file LiveLinkTypes.h.
CloneData()
template<typename BaseType> BaseType * FLiveLinkBaseDataStruct< BaseType >::CloneData () const inline
Definition at line 389 of file LiveLinkTypes.h.
GetBaseData() [1/2]
template<typename BaseType> BaseType * FLiveLinkBaseDataStruct< BaseType >::GetBaseData () inline
Definition at line 333 of file LiveLinkTypes.h.
Referenced by FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::Cast(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::Cast(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::CloneData(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::InitializeWith(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::InitializeWith(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::IsValid(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator<<, and FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator==().
GetBaseData() [2/2]
template<typename BaseType> const BaseType * FLiveLinkBaseDataStruct< BaseType >::GetBaseData () const inline
Definition at line 338 of file LiveLinkTypes.h.
GetStruct()
template<typename BaseType> const UScriptStruct * FLiveLinkBaseDataStruct< BaseType >::GetStruct () const inline
Definition at line 343 of file LiveLinkTypes.h.
Referenced by FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::Cast(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::Cast(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::InitializeWith(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::InitializeWith(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator<<, and FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator==().
InitializeWith() [1/3]
template<typename BaseType> template<typename DataType> void FLiveLinkBaseDataStruct< BaseType >::InitializeWith (const DataType * InData) inline
Initialize ourselves with another data struct directly.
Note
: We could have been initialized before so if it's the case, previous memory will be destroyed.
Definition at line 353 of file LiveLinkTypes.h.
Referenced by FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::InitializeWith().
InitializeWith() [2/3]
template<typename BaseType> void FLiveLinkBaseDataStruct< BaseType >::InitializeWith (const FLiveLinkBaseDataStruct< BaseType > & InOther) inline
Initialize ourselves with another data struct.
Note
: We could have been initialized before so if it's the case, previous memory will be destroyed.
Definition at line 379 of file LiveLinkTypes.h.
InitializeWith() [3/3]
template<typename BaseType> void FLiveLinkBaseDataStruct< BaseType >::InitializeWith (const UScriptStruct * InOtherStruct, const BaseType * InData) inline
Initialize ourselves with another struct.
Note
: We could have been initialized before so if it's the case, previous memory will be destroyed.
Definition at line 363 of file LiveLinkTypes.h.
IsValid()
template<typename BaseType> bool FLiveLinkBaseDataStruct< BaseType >::IsValid () const inline
Definition at line 323 of file LiveLinkTypes.h.
operator!=()
template<typename BaseType> bool FLiveLinkBaseDataStruct< BaseType >::operator!= (const FLiveLinkBaseDataStruct< BaseType > & Other) const inline
Definition at line 432 of file LiveLinkTypes.h.
operator=()
template<typename BaseType> FLiveLinkBaseDataStruct & FLiveLinkBaseDataStruct< BaseType >::operator= (FLiveLinkBaseDataStruct< BaseType > && InOther) inline
Definition at line 413 of file LiveLinkTypes.h.
operator==()
template<typename BaseType> bool FLiveLinkBaseDataStruct< BaseType >::operator== (const FLiveLinkBaseDataStruct< BaseType > & Other) const inline
Definition at line 419 of file LiveLinkTypes.h.
Reset()
template<typename BaseType> void FLiveLinkBaseDataStruct< BaseType >::Reset () inline
Definition at line 328 of file LiveLinkTypes.h.
Friends And Related Symbol Documentation
operator<<
template<typename BaseType> FArchive & operator<< (FArchive & Ar, FLiveLinkBaseDataStruct< BaseType > & InStruct) friend
Definition at line 437 of file LiveLinkTypes.h.
Field Documentation
WrappedStruct
template<typename BaseType> FStructOnScope FLiveLinkBaseDataStruct< BaseType >::WrappedStruct protected
Definition at line 508 of file LiveLinkTypes.h.
Referenced by FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator<<.
The documentation for this class was generated from the following file:
LiveLinkTypes.h