Unreal Engine 5.6 C++ API: SHeaderRow Class Reference
SHeaderRow Class Reference
The header that appears above lists and trees when they are showing multiple columns.
#include "SHeaderRow.h"
Data Structures
class FColumn
Describes a single column header.
Public Member Functions
void AddColumn (const FColumn::FArguments &NewColumnArgs)
Adds a column to the header.
void AddColumn (FColumn &NewColumn)
void ClearColumns ()
Removes all columns from the header.
DECLARE_EVENT_OneParam (SHeaderRow, FColumnsChanged, const TSharedRef< SHeaderRow > &)
const TIndirectArray< FColumn > & GetColumns () const
TArray< FName > GetHiddenColumnIds () const
FVector2D GetRowSizeForSlotIndex (int32 SlotIndex) const
Will return the size for this row at the specified slot index.
void InsertColumn (const FColumn::FArguments &NewColumnArgs, int32 InsertIdx)
Inserts a column at the specified index in the header.
void InsertColumn (FColumn &NewColumn, int32 InsertIdx)
bool IsColumnGenerated (const FName &InColumnId) const
bool IsColumnVisible (const FName &InColumnId) const
FColumnsChanged * OnColumnsChanged ()
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
void RefreshColumns ()
Force refreshing of the column widgets.
void RemoveColumn (const FName &InColumnId)
Removes a column from the header.
SLATE_STYLE_ARGUMENT(FHeaderRowStyle, Style) SLATE_SUPPORTS_SLOT_WITH_ARGS(FColumn) SLATE_EVENT(FColumnsChanged void ResetColumnWidths ()
Can select the columns generated by right clicking on the header menu.
void SetAssociatedVerticalScrollBar (const TSharedRef< SScrollBar > &ScrollBar, const float ScrollBarSize)
void SetColumnWidth (const FName &InColumnId, float InWidth)
Sets the column, with the specified name, to the desired width.
void SetOnGetMaxRowSizeForColumn (const FOnGetMaxRowSizeForColumn &Delegate)
Simple function to set the delegate to fetch the max row size for column id.
void SetShowGeneratedColumn (const FName &InColumnIdm, bool InShow=true)
Show or Hide a generated column.
bool ShouldGeneratedColumn (const FName &InColumnId) const
SLATE_BEGIN_ARGS (SHeaderRow)
Public Member Functions inherited from SBorder
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FColumn::FArguments Column (const FName &InColumnId)
Create a column with the specified ColumnId.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Private Member Functions
bool CanToggleAllColumns () const
ECheckBoxState GetGeneratedColumnCheckedState (FName ColumnId) const
ECheckBoxState GetSelectAllColumnsCheckState () const
FText GetToggleAllColumnsText () const
void OnGenerateSelectColumnsSubMenu (FMenuBuilder &InSubMenuBuilder)
void RegenerateWidgets ()
Regenerates all widgets in the header.
void ToggleAllColumns ()
void ToggleGeneratedColumn (FName ColumnId)
Private Attributes
bool bCanSelectGeneratedColumn
TIndirectArray< FColumn > Columns
Information about the various columns.
FColumnsChanged ColumnsChanged
TArray< TSharedPtr< class STableColumnHeader > > HeaderWidgets
FOnGetMaxRowSizeForColumn OnGetMaxRowSizeForColumn
FSimpleDelegate OnHiddenColumnsListChanged
ESplitterResizeMode::Type ResizeMode
FVector2f ScrollBarThickness
TAttribute< EVisibility > ScrollBarVisibility
float SplitterHandleSize
const FHeaderRowStyle * Style
Additional Inherited Members
Protected Member Functions inherited from SBorder
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FSlateColor > GetBorderBackgroundColorAttribute () const
TSlateAttributeRef< const FSlateBrush * > GetBorderImageAttribute () const
FVector2D GetDesiredSizeScale () const
Get the desired size scale multiplier.
TSlateAttributeRef< FVector2D > GetDesiredSizeScaleAttribute () const
bool GetShowDisabledEffect () const
Get whether or not to show the disabled effect when this border is disabled.
TSlateAttributeRef< bool > GetShowDisabledEffectAttribute () const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
The header that appears above lists and trees when they are showing multiple columns.
Definition at line 96 of file SHeaderRow.h.
Member Function Documentation
AddColumn() [1/2]
void SHeaderRow::AddColumn (const FColumn::FArguments & NewColumnArgs)
Adds a column to the header.
References AddColumn().
Referenced by AddColumn(), and AddColumn().
AddColumn() [2/2]
void SHeaderRow::AddColumn (FColumn & NewColumn)
References AddColumn().
CanToggleAllColumns()
bool SHeaderRow::CanToggleAllColumns () const private
ClearColumns()
void SHeaderRow::ClearColumns ()
Removes all columns from the header.
References ClearColumns().
Referenced by ClearColumns().
Column()
FColumn::FArguments SHeaderRow::Column (const FName & InColumnId) inline static
Create a column with the specified ColumnId.
Definition at line 287 of file SHeaderRow.h.
DECLARE_EVENT_OneParam()
SHeaderRow::DECLARE_EVENT_OneParam (SHeaderRow , FColumnsChanged , const TSharedRef< SHeaderRow > &)
GetColumns()
const TIndirectArray< FColumn > & SHeaderRow::GetColumns () const
Returns
the Columns driven by the column headers
References GetColumns().
Referenced by GetColumns().
GetGeneratedColumnCheckedState()
ECheckBoxState SHeaderRow::GetGeneratedColumnCheckedState (FName ColumnId) const private
GetHiddenColumnIds()
TArray< FName > SHeaderRow::GetHiddenColumnIds () const
Returns
The columns id of the header widgets that were not generated
GetRowSizeForSlotIndex()
FVector2D SHeaderRow::GetRowSizeForSlotIndex (int32 SlotIndex) const
Will return the size for this row at the specified slot index.
References GetRowSizeForSlotIndex().
Referenced by GetRowSizeForSlotIndex().
GetSelectAllColumnsCheckState()
ECheckBoxState SHeaderRow::GetSelectAllColumnsCheckState () const private
GetToggleAllColumnsText()
FText SHeaderRow::GetToggleAllColumnsText () const private
InsertColumn() [1/2]
void SHeaderRow::InsertColumn (const FColumn::FArguments & NewColumnArgs, int32 InsertIdx)
Inserts a column at the specified index in the header.
References InsertColumn().
Referenced by InsertColumn(), and InsertColumn().
InsertColumn() [2/2]
void SHeaderRow::InsertColumn (FColumn & NewColumn, int32 InsertIdx)
References InsertColumn().
IsColumnGenerated()
bool SHeaderRow::IsColumnGenerated (const FName & InColumnId) const
Returns
is the header widget with the column id is generated
IsColumnVisible()
bool SHeaderRow::IsColumnVisible (const FName & InColumnId) const
Returns
true if the header widget with the column id is visible
OnColumnsChanged()
FColumnsChanged * SHeaderRow::OnColumnsChanged () inline
Definition at line 295 of file SHeaderRow.h.
References ColumnsChanged.
Referenced by SMultiColumnTableRow< ItemType >::Construct().
OnGenerateSelectColumnsSubMenu()
void SHeaderRow::OnGenerateSelectColumnsSubMenu (FMenuBuilder & InSubMenuBuilder) private
OnMouseButtonUp()
virtual FReply SHeaderRow::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
RefreshColumns()
void SHeaderRow::RefreshColumns ()
Force refreshing of the column widgets.
References RefreshColumns().
Referenced by RefreshColumns().
RegenerateWidgets()
void SHeaderRow::RegenerateWidgets () private
Regenerates all widgets in the header.
RemoveColumn()
void SHeaderRow::RemoveColumn (const FName & InColumnId)
Removes a column from the header.
References RemoveColumn().
Referenced by RemoveColumn().
ResetColumnWidths()
SLATE_STYLE_ARGUMENT(FHeaderRowStyle, Style) SLATE_SUPPORTS_SLOT_WITH_ARGS(FColumn) SLATE_EVENT(FColumnsChanged void SHeaderRow::ResetColumnWidths ()
Can select the columns generated by right clicking on the header menu.
FColumn with ShouldGenerateWidget set can not be selected. FColumn with MenuContent will still be displayed. The list of column ids that should not be generated by default. Triggered when columns visibility changed. Restore the columns to their original width
References ResetColumnWidths().
Referenced by ResetColumnWidths().
SetAssociatedVerticalScrollBar()
void SHeaderRow::SetAssociatedVerticalScrollBar (const TSharedRef< SScrollBar > & ScrollBar, const float ScrollBarSize)
References SetAssociatedVerticalScrollBar().
Referenced by SetAssociatedVerticalScrollBar().
SetColumnWidth()
void SHeaderRow::SetColumnWidth (const FName & InColumnId, float InWidth)
Sets the column, with the specified name, to the desired width.
References SetColumnWidth().
Referenced by SetColumnWidth().
SetOnGetMaxRowSizeForColumn()
void SHeaderRow::SetOnGetMaxRowSizeForColumn (const FOnGetMaxRowSizeForColumn & Delegate) inline
Simple function to set the delegate to fetch the max row size for column id.
Definition at line 355 of file SHeaderRow.h.
References OnGetMaxRowSizeForColumn, and SetOnGetMaxRowSizeForColumn().
Referenced by SetOnGetMaxRowSizeForColumn().
SetShowGeneratedColumn()
void SHeaderRow::SetShowGeneratedColumn (const FName & InColumnIdm, bool InShow = true)
Show or Hide a generated column.
ShouldGeneratedColumn()
bool SHeaderRow::ShouldGeneratedColumn (const FName & InColumnId) const
Returns
is the header widget should be generated
SLATE_BEGIN_ARGS()
SHeaderRow::SLATE_BEGIN_ARGS (SHeaderRow) inline
Definition at line 297 of file SHeaderRow.h.
ToggleAllColumns()
void SHeaderRow::ToggleAllColumns () private
ToggleGeneratedColumn()
void SHeaderRow::ToggleGeneratedColumn (FName ColumnId) private
Field Documentation
bCanSelectGeneratedColumn
bool SHeaderRow::bCanSelectGeneratedColumn private
Definition at line 404 of file SHeaderRow.h.
Columns
TIndirectArray<FColumn> SHeaderRow::Columns private
Information about the various columns.
Definition at line 392 of file SHeaderRow.h.
ColumnsChanged
FColumnsChanged SHeaderRow::ColumnsChanged private
Definition at line 398 of file SHeaderRow.h.
Referenced by OnColumnsChanged().
HeaderWidgets
TArray<TSharedPtr<class STableColumnHeader> > SHeaderRow::HeaderWidgets private
Definition at line 393 of file SHeaderRow.h.
OnGetMaxRowSizeForColumn
FOnGetMaxRowSizeForColumn SHeaderRow::OnGetMaxRowSizeForColumn private
Definition at line 401 of file SHeaderRow.h.
Referenced by SetOnGetMaxRowSizeForColumn().
OnHiddenColumnsListChanged
FSimpleDelegate SHeaderRow::OnHiddenColumnsListChanged private
Definition at line 403 of file SHeaderRow.h.
ResizeMode
ESplitterResizeMode::Type SHeaderRow::ResizeMode private
Definition at line 399 of file SHeaderRow.h.
ScrollBarThickness
FVector2f SHeaderRow::ScrollBarThickness private
Definition at line 395 of file SHeaderRow.h.
ScrollBarVisibility
TAttribute< EVisibility > SHeaderRow::ScrollBarVisibility private
Definition at line 396 of file SHeaderRow.h.
SplitterHandleSize
float SHeaderRow::SplitterHandleSize private
Definition at line 400 of file SHeaderRow.h.
Style
const FHeaderRowStyle* SHeaderRow::Style private
Definition at line 397 of file SHeaderRow.h.
The documentation for this class was generated from the following file:
SHeaderRow.h