Unreal Engine 5.6 C++ API: FRedirectCollector::FSoftObjectPathProperty Struct Reference
FRedirectCollector::FSoftObjectPathProperty Struct Reference
Helper struct for soft object path tracking.
Public Member Functions
FSoftObjectPathProperty (FSoftObjectPath InObjectPath, FName InProperty, bool bInReferencedByEditorOnlyProperty)
const FSoftObjectPath & GetObjectPath () const
const FName & GetPropertyName () const
bool GetReferencedByEditorOnlyProperty () const
bool operator== (const FSoftObjectPathProperty &Other) const
Private Attributes
bool bReferencedByEditorOnlyProperty
FSoftObjectPath ObjectPath
FName PropertyName
Friends
uint32 GetTypeHash (const FSoftObjectPathProperty &Key)
Detailed Description
Helper struct for soft object path tracking.
Definition at line 36 of file RedirectCollector.h.
Constructor & Destructor Documentation
FSoftObjectPathProperty()
FRedirectCollector::FSoftObjectPathProperty::FSoftObjectPathProperty (FSoftObjectPath InObjectPath, FName InProperty, bool bInReferencedByEditorOnlyProperty) inline
Definition at line 38 of file RedirectCollector.h.
References bReferencedByEditorOnlyProperty, MoveTemp(), ObjectPath, and PropertyName.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
GetObjectPath()
const FSoftObjectPath & FRedirectCollector::FSoftObjectPathProperty::GetObjectPath () const inline
Definition at line 60 of file RedirectCollector.h.
References ObjectPath.
GetPropertyName()
const FName & FRedirectCollector::FSoftObjectPathProperty::GetPropertyName () const inline
Definition at line 65 of file RedirectCollector.h.
References PropertyName.
GetReferencedByEditorOnlyProperty()
bool FRedirectCollector::FSoftObjectPathProperty::GetReferencedByEditorOnlyProperty () const inline
Definition at line 70 of file RedirectCollector.h.
References bReferencedByEditorOnlyProperty.
operator==()
bool FRedirectCollector::FSoftObjectPathProperty::operator== (const FSoftObjectPathProperty & Other) const inline
Definition at line 44 of file RedirectCollector.h.
References FSoftObjectPathProperty(), bReferencedByEditorOnlyProperty, ObjectPath, Other, and PropertyName.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSoftObjectPathProperty & Key) friend
Definition at line 51 of file RedirectCollector.h.
References FSoftObjectPathProperty(), GetTypeHash, Hash, HashCombine(), and Key.
Referenced by GetTypeHash.
Field Documentation
bReferencedByEditorOnlyProperty
bool FRedirectCollector::FSoftObjectPathProperty::bReferencedByEditorOnlyProperty private
Definition at line 78 of file RedirectCollector.h.
Referenced by FSoftObjectPathProperty(), GetReferencedByEditorOnlyProperty(), and operator==().
ObjectPath
FSoftObjectPath FRedirectCollector::FSoftObjectPathProperty::ObjectPath private
Definition at line 76 of file RedirectCollector.h.
Referenced by FSoftObjectPathProperty(), GetObjectPath(), and operator==().
PropertyName
FName FRedirectCollector::FSoftObjectPathProperty::PropertyName private
Definition at line 77 of file RedirectCollector.h.
Referenced by FSoftObjectPathProperty(), GetPropertyName(), and operator==().
The documentation for this struct was generated from the following file:
RedirectCollector.h