Unreal Engine 5.6 C++ API: FConfigCacheIni Class Reference
FConfigCacheIni Class Reference
#include "ConfigCacheIni.h"
Data Structures
struct FKnownConfigFiles
struct FPluginInfo
Public Member Functions
FConfigCacheIni ()
DO NOT USE.
FConfigCacheIni (EConfigCacheType Type, FName PlatformName=NAME_None, bool bInGloballyRegistered=false)
virtual ~FConfigCacheIni ()
FConfigFile & Add (const FString &Filename, const FConfigFile &File)
FConfigBranch & AddNewBranch (const FString &Filename)
Create a new branch for FIlename, and return it.
bool AddToSection (const TCHAR *Section, FName Key, const FString &Value, const FString &Filename)
Adds the given key/value pair to the Section in the given File.
bool AddUniqueToSection (const TCHAR *Section, FName Key, const FString &Value, const FString &Filename)
Adds the given key/value pair to the Section in the given File, if the pair didn't already exist This is equivalent to the + operator in .ini files.
bool AreFileOperationsDisabled ()
Returns whether or not file operations are disabled.
bool ContainsConfigFile (const FConfigFile *ConfigFile) const
Reports whether an FConfigFile* is pointing to a config file inside of this Used for downstream functions to check whether a config file they were passed came from this ConfigCacheIni or from a different source such as LoadLocalIniFile.
void Detach (const FString &Filename)
void DisableFileOperations ()
Disables any file IO by the config cache system.
bool DoesSectionExist (const TCHAR *Section, const FString &Filename)
void Dump (FOutputDevice &Ar, const TCHAR *IniName=NULL)
Prints out the entire config set, or just a single file if an ini is specified.
bool EmptySection (const TCHAR *Section, const FString &Filename)
bool EmptySectionsMatchingString (const TCHAR *SectionString, const FString &Filename)
void EnableFileOperations ()
Re-enables file IO by the config cache system.
void Exit ()
FConfigFile * Find (const FString &InFilename)
Finds, loads, or creates the in-memory config file for a config cache filename.
FConfigBranch * FindBranch (FName BaseIniName, const FString &Filename)
Finds an FConfigBranch, using base name or a filename (can pass in NAME_None or empty string as needed)
FConfigBranch * FindBranchWithNoReload (FName BaseIniName, const FString &Filename)
Same as FindBranch, but this will not reload a formerly SafeUnload'd branch.
FConfigFile * FindConfigFile (const FString &Filename)
Finds the in-memory config file for a config cache filename.
FConfigFile * FindConfigFileWithBaseName (FName BaseName)
Finds Config file that matches the base name such as "Engine".
void Flush (bool bRemoveFromCache, const FString &Filename=TEXT(""))
bool ForEachEntry (const FKeyValueSink &Visitor, const TCHAR *Section, const FString &Filename)
allows to iterate through all key value pairs
int32 GetArray (const TCHAR *Section, const TCHAR *Key, TArray< FString > &out_Arr, const FString &Filename)
bool GetBool (const TCHAR *Section, const TCHAR *Key, bool &Value, const FString &Filename)
bool GetBoolOrDefault (const TCHAR *Section, const TCHAR *Key, const bool DefaultValue, const FString &Filename)
bool GetColor (const TCHAR *Section, const TCHAR *Key, FColor &Value, const FString &Filename)
FString GetConfigFilename (const TCHAR *BaseIniName)
For a base ini name, gets the config cache filename key that is used by other functions like Find.
void GetConfigFilenames (TArray< FString > &ConfigFilenames)
Retrieve a list of all of the config files stored in the cache.
bool GetDouble (const TCHAR *Section, const TCHAR *Key, double &Value, const FString &Filename)
TArray< FString > GetFilenames ()
bool GetFloat (const TCHAR *Section, const TCHAR *Key, float &Value, const FString &Filename)
float GetFloatOrDefault (const TCHAR *Section, const TCHAR *Key, const float DefaultValue, const FString &Filename)
bool GetInt (const TCHAR *Section, const TCHAR *Key, int32 &Value, const FString &Filename)
bool GetInt64 (const TCHAR *Section, const TCHAR *Key, int64 &Value, const FString &Filename)
int32 GetIntOrDefault (const TCHAR *Section, const TCHAR *Key, const int32 DefaultValue, const FString &Filename)
SIZE_T GetMaxMemoryUsage ()
USed to get the max memory usage for the FConfigCacheIni.
bool GetPerObjectConfigSections (const FString &Filename, const FString &SearchClass, TArray< FString > &out_SectionNames, int32 MaxResults=1024)
Retrieve the names of sections which contain data for the specified PerObjectConfig class.
bool GetRotator (const TCHAR *Section, const TCHAR *Key, FRotator &Value, const FString &Filename)
const FConfigSection * GetSection (const TCHAR *Section, const bool Force, const FString &Filename)
bool GetSection (const TCHAR *Section, TArray< FString > &Result, const FString &Filename)
bool GetSectionNames (const FString &Filename, TArray< FString > &out_SectionNames)
Retrieve the names for all sections contained in the file specified by Filename.
int32 GetSingleLineArray (const TCHAR *Section, const TCHAR *Key, TArray< FString > &out_Arr, const FString &Filename)
Loads a "delimited" list of strings.
const TSet< FString > * GetStagedGlobalConfigCache () const
Returns the staged global config cache.
const TSet< FString > * GetStagedPluginConfigCache (FName PluginName) const
Finds the Staged Plugin ConfigCache if it exists from a PluginName Returns a pointer to the cache if it exists, a nullptr if not.
FString GetStr (const TCHAR *Section, const TCHAR *Key, const FString &Filename)
bool GetString (const TCHAR *Section, const TCHAR *Key, FString &Value, const FString &Filename)
FString GetStringOrDefault (const TCHAR *Section, const TCHAR *Key, const FString &DefaultValue, const FString &Filename)
bool GetText (const TCHAR *Section, const TCHAR *Key, FText &Value, const FString &Filename)
FText GetTextOrDefault (const TCHAR *Section, const TCHAR *Key, const FText &DefaultValue, const FString &Filename)
bool GetValue (const TCHAR *Section, const TCHAR *Key, bool &Value, const FString &Filename)
bool GetValue (const TCHAR *Section, const TCHAR *Key, float &Value, const FString &Filename)
bool GetValue (const TCHAR *Section, const TCHAR *Key, FString &Value, const FString &Filename)
bool GetValue (const TCHAR *Section, const TCHAR *Key, FText &Value, const FString &Filename)
bool GetValue (const TCHAR *Section, const TCHAR *Key, int32 &Value, const FString &Filename)
int32 GetValue (const TCHAR *Section, const TCHAR *Key, TArray< FString > &Value, const FString &Filename)
bool GetVector (const TCHAR *Section, const TCHAR *Key, FVector &Value, const FString &Filename)
bool GetVector2D (const TCHAR *Section, const TCHAR *Key, FVector2D &Value, const FString &Filename)
bool GetVector4 (const TCHAR *Section, const TCHAR *Key, FVector4 &Value, const FString &Filename)
bool IsGloballyRegistered () const
Return whether this is one of the global ConfigSystems: GConfig or FConfigCacheIni::ForPlatform.
bool IsKnownConfigName (FName ConfigName)
Returns true if the given name is one of the known configs, where the matching G****Ini property is going to match the base name ("Engine" returns true, which means GEngineIni's value is just "Engine")
bool IsReadyForUse ()
void LoadFile (const FString &InFilename, const FConfigFile *Fallback=NULL, const TCHAR *PlatformString=NULL)
void Parse1ToNSectionOfNames (const TCHAR *Section, const TCHAR *KeyOne, const TCHAR *KeyN, TMap< FName, TArray< FName > > &OutMap, const FString &Filename)
Parses apart an ini section that contains a list of 1-to-N mappings of names in the following format [PerMapPackages] MapName=Map1 Package=PackageA Package=PackageB MapName=Map2 Package=PackageC Package=PackageD.
void Parse1ToNSectionOfStrings (const TCHAR *Section, const TCHAR *KeyOne, const TCHAR *KeyN, TMap< FString, TArray< FString > > &OutMap, const FString &Filename)
Prases apart an ini section that contains a list of 1-to-N mappings of strings in the following format [PerMapPackages] MapName=Map1 Package=PackageA Package=PackageB MapName=Map2 Package=PackageC Package=PackageD.
int32 Remove (const FString &Filename)
bool RemoveFromSection (const TCHAR *Section, FName Key, const FString &Value, const FString &Filename)
Removes every entry in the Section in the given File that has the Key/Value pair This is equivalent to the - operator in .ini files (although it will remove all instances of the pair, not just a single one)
bool RemoveKey (const TCHAR *Section, const TCHAR *Key, const FString &Filename)
bool RemoveKeyFromSection (const TCHAR *Section, FName Key, const FString &Filename)
Removes every entry in the Section in the given File that has Key, no matter what the Value is This is equivalent to the !
bool RemoveSectionFromBranch (const TCHAR *Section, const TCHAR *Filename)
Removes the section completely from all layers of a branch.
bool ResetKeyInSection (const TCHAR *Section, FName Key, const FString &Filename)
Similar to RemvoeKeyFromSection, but if this File's changes are being tracked, then we remove all changes to the the key that have been tracked.
bool SafeUnloadBranch (const TCHAR *Filename)
Clears out the memory of a branch, but can reload it on demand if needed.
void SaveCurrentStateForBootstrap (const TCHAR *Filename)
Save the current config cache state into a file for bootstrapping other processes.
void Serialize (FArchive &Ar)
void SetArray (const TCHAR *Section, const TCHAR *Key, const TArray< FString > &Value, const FString &Filename)
void SetBool (const TCHAR *Section, const TCHAR *Key, bool Value, const FString &Filename)
void SetColor (const TCHAR *Section, const TCHAR *Key, FColor Value, const FString &Filename)
void SetDouble (const TCHAR *Section, const TCHAR *Key, double Value, const FString &Filename)
void SetFile (const FString &InFilename, const FConfigFile *NewConfigFile)
void SetFloat (const TCHAR *Section, const TCHAR *Key, float Value, const FString &Filename)
void SetInt (const TCHAR *Section, const TCHAR *Key, int32 Value, const FString &Filename)
void SetRotator (const TCHAR *Section, const TCHAR *Key, FRotator Value, const FString &Filename)
void SetSingleLineArray (const TCHAR *Section, const TCHAR *Key, const TArray< FString > &In_Arr, const FString &Filename)
Saves a "delimited" list of strings.
void SetString (const TCHAR *Section, const TCHAR *Key, const TCHAR *Value, const FString &Filename)
void SetText (const TCHAR *Section, const TCHAR *Key, const FText &Value, const FString &Filename)
void SetVector (const TCHAR *Section, const TCHAR *Key, FVector Value, const FString &Filename)
void SetVector2D (const TCHAR *Section, const TCHAR *Key, FVector2D Value, const FString &Filename)
void SetVector4 (const TCHAR *Section, const TCHAR *Key, const FVector4 &Value, const FString &Filename)
void ShowMemoryUsage (FOutputDevice &Ar)
Dumps memory stats for each file in the config cache to the specified archive.
void Tick (float DeltaSeconds)
Allow for periodic cleanup or other tasks.
UE_DEPRECATED (5.4, "Use GetSection instead, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") 1 FConfigSection *GetSectionPrivate(const TCHAR *Section
void UnloadFile (const FString &Filename)
Static Public Member Functions
static void AddMultiplePluginsToAllBranches (const TArray< FName > &PluginName, FConfigModificationTracker *ModificationTracker=nullptr)
static void AddPluginToAllBranches (FName PluginName, FConfigModificationTracker *ModificationTracker=nullptr)
static void ClearOtherPlatformConfigs ()
Wipe all cached platform configs.
static bool CreateGConfigFromSaved (const TCHAR *Filename)
Create GConfig from a saved file.
static FConfigFile * FindOrLoadPlatformConfig (FConfigFile &LocalFile, const TCHAR *IniName, const TCHAR *Platform=NULL)
This helper function searches the cache before trying to load the ini file using LoadLocalIniFile.
static FConfigFile * FindPlatformConfig (const TCHAR *IniName, const TCHAR *Platform)
Attempts to find the platform config in the cache.
static FConfigCacheIni * ForPlatform (FName PlatformName)
Retrieve the fully processed ini system for another platform.
static const FString & GetCustomConfigString ()
Returns the Custom Config string, which if set will load additional config files from Config/Custom/{CustomConfig}/DefaultX.ini to allow different types of builds.
static FString GetDestIniFilename (const TCHAR *BaseIniName, const TCHAR *PlatformName, const TCHAR *GeneratedConfigDir)
Calculates the name of a dest (generated) .ini file for a given base (ie Engine, Game, etc)
static void InitializeConfigSystem ()
Creates GConfig, loads the standard global ini files (Engine, Editor, etc), fills out GEngineIni, etc.
static bool InitializeKnownConfigFiles (FConfigContext &Context)
Load the standard (used on all platforms) ini files, like Engine, Input, etc.
static void LoadConsoleVariablesFromINI ()
Needs to be called after GConfig is set and LoadCoalescedFile was called.
static bool LoadExternalIniFile (FConfigFile &ConfigFile, const TCHAR *IniName, const TCHAR *EngineConfigDir, const TCHAR *SourceConfigDir, bool bIsBaseIniName, const TCHAR *Platform=NULL, bool bForceReload=false, bool bWriteDestIni=false, bool bAllowGeneratedIniWhenCooked=true, const TCHAR *GeneratedConfigDir= *FPaths::GeneratedConfigDir())
Load an ini file directly into an FConfigFile from the specified config folders, optionally writing to disk.
static bool LoadGlobalIniFile (FString &FinalIniFilename, const TCHAR *BaseIniName, const TCHAR *Platform=NULL, bool bForceReload=false, bool bRequireDefaultIni=false, bool bAllowGeneratedIniWhenCooked=true, bool bAllowRemoteConfig=true, const TCHAR *GeneratedConfigDir= *FPaths::GeneratedConfigDir(), FConfigCacheIni *ConfigSystem=GConfig)
Loads and generates a destination ini file and adds it to GConfig:
static bool LoadLocalIniFile (FConfigFile &ConfigFile, const TCHAR *IniName, bool bIsBaseIniName, const TCHAR *Platform=NULL, bool bForceReload=false)
Load an ini file directly into an FConfigFile, and nothing is written to GConfig or disk.
static FString NormalizeConfigIniPath (const FString &NonNormalizedPath)
Normalizes file paths to INI files.
static void PreInitializePlatformPlugins ()
Initializes configs and plugins for every supported platform on worker threads.
static void RegisterPlugin (FName PluginName, const FString &PluginDir, const TArray< FString > &ChildPluginDirs, DynamicLayerPriority Priority, bool bIncludePluginNameInBranchName)
Tell GConfig and the ForPlatform config systems about a plugin location.
static void RemoveMultipleTagsFromAllBranches (const TArray< FName > &Tags, FConfigModificationTracker *ModificationTracker=nullptr)
static void RemoveTagFromAllBranches (FName Tag, FConfigModificationTracker *ModificationTracker=nullptr)
Data Fields
const bool const bool Const
const bool const bool const FString & Filename
const bool Force
Private Member Functions
void AddPluginsToBranches (const TArray< FName > &PluginNames, FConfigModificationTracker *ModificationTracker)
bool IsConfigBranchNameInNeverUnloadList (const FName &ConfigBranchName)
Does this ConfigBranch IniName appear in our disallowed removal list.
void RemoveTagsFromBranches (const TArray< FName > &Tags, FConfigModificationTracker *ModificationTracker)
void SerializeStateForBootstrap_Impl (FArchive &Ar)
Serialize a bootstrapping state into or from an archive.
Static Private Member Functions
static void AsyncInitializeConfigForPlatforms ()
We only auto-initialize other platform configs in the editor to not slow down programs like ShaderCOmpileWorker.
Private Attributes
bool bAreFileOperationsDisabled
true if file operations should not be performed
bool bGloballyRegistered
bool bIsReadyForUse
true after the base .ini files have been loaded, and GConfig is generally "ready for use"
TArray< FString > ConfigBranchNamesToNeverUnload
List of ConfigBranch names that should never be unloaded.
friend FConfigContext
FKnownConfigFiles KnownFiles
The filenames for the known files in this config.
TArray< FString > OtherFileNames
Parallel array to OtherFiles.
TMap< FString, FConfigBranch * > OtherFiles
TArray< FName > PendingModificationPlugins
FName PlatformName
The platform this config system is for - if empty, then it can't be used with dynamic plugin layering.
TSet< FString > * StagedGlobalConfigCache = nullptr
TMap< FName, TSet< FString > > StagedPluginConfigCache
EConfigCacheType Type
The type of the cache (basically, do we call Flush in the destructor)
Static Private Attributes
static TMap< FName, FPluginInfo * > RegisteredPlugins
static FTransactionallySafeCriticalSection RegisteredPluginsLock
Friends
bool MakeBinaryConfig (const TCHAR *CmdLine)
Detailed Description
Definition at line 1186 of file ConfigCacheIni.h.
Constructor & Destructor Documentation
FConfigCacheIni() [1/2]
FConfigCacheIni::FConfigCacheIni (EConfigCacheType Type, FName PlatformName = NAME_None, bool bInGloballyRegistered = false)
References PlatformName, and Type.
Referenced by ForPlatform(), and LoadGlobalIniFile().
FConfigCacheIni() [2/2]
FConfigCacheIni::FConfigCacheIni ()
DO NOT USE.
This constructor is for internal usage only for hot-reload purposes.
~FConfigCacheIni()
virtual FConfigCacheIni::~FConfigCacheIni () virtual
Member Function Documentation
Add()
FConfigFile & FConfigCacheIni::Add (const FString & Filename, const FConfigFile & File)
References Filename.
AddMultiplePluginsToAllBranches()
void FConfigCacheIni::AddMultiplePluginsToAllBranches (const TArray< FName > & PluginName, FConfigModificationTracker * ModificationTracker = nullptr) static
AddNewBranch()
FConfigBranch & FConfigCacheIni::AddNewBranch (const FString & Filename)
Create a new branch for FIlename, and return it.
References Filename.
AddPluginsToBranches()
void FConfigCacheIni::AddPluginsToBranches (const TArray< FName > & PluginNames, FConfigModificationTracker * ModificationTracker) private
AddPluginToAllBranches()
void FConfigCacheIni::AddPluginToAllBranches (FName PluginName, FConfigModificationTracker * ModificationTracker = nullptr) static
AddToSection()
bool FConfigCacheIni::AddToSection (const TCHAR * Section, FName Key, const FString & Value, const FString & Filename)
Adds the given key/value pair to the Section in the given File.
This will always add this pair to the section, even if the pair already exists. This is equivalent to the . operator in .ini files
Returns
true if the section was modified
References Filename, Key, and Value.
AddUniqueToSection()
bool FConfigCacheIni::AddUniqueToSection (const TCHAR * Section, FName Key, const FString & Value, const FString & Filename)
Adds the given key/value pair to the Section in the given File, if the pair didn't already exist This is equivalent to the + operator in .ini files.
Returns
true if the section was modified
References Filename, Key, and Value.
AreFileOperationsDisabled()
bool FConfigCacheIni::AreFileOperationsDisabled ()
Returns whether or not file operations are disabled.
AsyncInitializeConfigForPlatforms()
void FConfigCacheIni::AsyncInitializeConfigForPlatforms () static private
We only auto-initialize other platform configs in the editor to not slow down programs like ShaderCOmpileWorker.
ClearOtherPlatformConfigs()
void FConfigCacheIni::ClearOtherPlatformConfigs () static
Wipe all cached platform configs.
Next ForPlatform call will load on-demand the platform configs
ContainsConfigFile()
bool FConfigCacheIni::ContainsConfigFile (const FConfigFile * ConfigFile) const
Reports whether an FConfigFile* is pointing to a config file inside of this Used for downstream functions to check whether a config file they were passed came from this ConfigCacheIni or from a different source such as LoadLocalIniFile.
CreateGConfigFromSaved()
bool FConfigCacheIni::CreateGConfigFromSaved (const TCHAR * Filename) static
Create GConfig from a saved file.
References Filename.
Detach()
void FConfigCacheIni::Detach (const FString & Filename)
References Filename.
DisableFileOperations()
void FConfigCacheIni::DisableFileOperations ()
Disables any file IO by the config cache system.
DoesSectionExist()
bool FConfigCacheIni::DoesSectionExist (const TCHAR * Section, const FString & Filename)
References Filename.
Dump()
void FConfigCacheIni::Dump (FOutputDevice & Ar, const TCHAR * IniName = NULL)
Prints out the entire config set, or just a single file if an ini is specified.
Parameters
Ar the device to write to
IniName An optional ini name to restrict the writing to (Engine or WrangleContent) - meant to be used with "final" .ini files (not Default*)
References Ar, and Dump().
Referenced by Dump().
EmptySection()
bool FConfigCacheIni::EmptySection (const TCHAR * Section, const FString & Filename)
References EmptySection(), and Filename.
Referenced by EmptySection().
EmptySectionsMatchingString()
bool FConfigCacheIni::EmptySectionsMatchingString (const TCHAR * SectionString, const FString & Filename)
References EmptySectionsMatchingString(), and Filename.
Referenced by EmptySectionsMatchingString().
EnableFileOperations()
void FConfigCacheIni::EnableFileOperations ()
Re-enables file IO by the config cache system.
Exit()
void FConfigCacheIni::Exit ()
References Exit().
Referenced by Exit().
Find()
FConfigFile * FConfigCacheIni::Find (const FString & InFilename)
Finds, loads, or creates the in-memory config file for a config cache filename.
Parameters
A known key like GEngineIni, or the return value of GetConfigFilename
Returns
A new or existing config file
FindBranch()
FConfigBranch * FConfigCacheIni::FindBranch (FName BaseIniName, const FString & Filename)
Finds an FConfigBranch, using base name or a filename (can pass in NAME_None or empty string as needed)
References Filename.
FindBranchWithNoReload()
FConfigBranch * FConfigCacheIni::FindBranchWithNoReload (FName BaseIniName, const FString & Filename)
Same as FindBranch, but this will not reload a formerly SafeUnload'd branch.
References Filename.
FindConfigFile()
FConfigFile * FConfigCacheIni::FindConfigFile (const FString & Filename)
Finds the in-memory config file for a config cache filename.
Parameters
A known key like GEngineIni, or the return value of GetConfigFilename
Returns
The existing config file or null if it does not exist in memory
References Filename.
FindConfigFileWithBaseName()
FConfigFile * FConfigCacheIni::FindConfigFileWithBaseName (FName BaseName)
Finds Config file that matches the base name such as "Engine".
FindOrLoadPlatformConfig()
FConfigFile * FConfigCacheIni::FindOrLoadPlatformConfig (FConfigFile & LocalFile, const TCHAR * IniName, const TCHAR * Platform = NULL) static
This helper function searches the cache before trying to load the ini file using LoadLocalIniFile.
Note that the returned FConfigFile pointer must have the same lifetime as the passed in LocalFile.
Parameters
LocalFile The output object to fill. If the FConfigFile is found in the cache, this won't be used.
IniName Either a Base ini name (Engine) or a full ini name (WrangleContent). NO PATH OR EXTENSION SHOULD BE USED!
Platform The platform to use for Base ini names, NULL means to use the current platform
Returns
FConfigFile Found or loaded FConfigFile
References Platform.
FindPlatformConfig()
FConfigFile * FConfigCacheIni::FindPlatformConfig (const TCHAR * IniName, const TCHAR * Platform) static
Attempts to find the platform config in the cache.
Parameters
IniName Either a Base ini name (Engine) or a full ini name (WrangleContent). NO PATH OR EXTENSION SHOULD BE USED!
Platform The platform to use for Base ini names, NULL means to use the current platform
Returns
FConfigFile Found FConfigFile
References Platform.
Flush()
void FConfigCacheIni::Flush (bool bRemoveFromCache, const FString & Filename = TEXT(""))
References Filename.
ForEachEntry()
bool FConfigCacheIni::ForEachEntry (const FKeyValueSink & Visitor, const TCHAR * Section, const FString & Filename)
allows to iterate through all key value pairs
Returns
false:error e.g. Section or Filename not found
References Filename, and ForEachEntry().
Referenced by ForEachEntry().
ForPlatform()
FConfigCacheIni * FConfigCacheIni::ForPlatform (FName PlatformName) static
Retrieve the fully processed ini system for another platform.
The editor will start loading these in the background on startup
References FConfigCacheIni(), and PlatformName.
GetArray()
int32 FConfigCacheIni::GetArray (const TCHAR * Section, const TCHAR * Key, TArray< FString > & out_Arr, const FString & Filename)
References Filename, GetArray(), and Key.
Referenced by GetArray(), and GetValue().
GetBool()
bool FConfigCacheIni::GetBool (const TCHAR * Section, const TCHAR * Key, bool & Value, const FString & Filename)
References Filename, GetBool(), Key, and Value.
Referenced by GetBool(), GetBoolOrDefault(), and GetValue().
GetBoolOrDefault()
bool FConfigCacheIni::GetBoolOrDefault (const TCHAR * Section, const TCHAR * Key, const bool DefaultValue, const FString & Filename) inline
Definition at line 1548 of file ConfigCacheIni.h.
References Filename, GetBool(), Key, and Value.
GetColor()
bool FConfigCacheIni::GetColor (const TCHAR * Section, const TCHAR * Key, FColor & Value, const FString & Filename)
References Filename, GetColor(), Key, and Value.
Referenced by GetColor().
GetConfigFilename()
FString FConfigCacheIni::GetConfigFilename (const TCHAR * BaseIniName)
For a base ini name, gets the config cache filename key that is used by other functions like Find.
This will be the base name for known configs like Engine and the destination filename for others.
Parameters
IniBaseName Base name of the .ini (Engine, Game, CustomSystem)
Returns
Filename key used by other cache functions
References GetConfigFilename().
Referenced by GetConfigFilename().
GetConfigFilenames()
void FConfigCacheIni::GetConfigFilenames (TArray< FString > & ConfigFilenames)
Retrieve a list of all of the config files stored in the cache.
Parameters
ConfigFilenames Out array to receive the list of filenames
References GetConfigFilenames().
Referenced by GetConfigFilenames().
GetCustomConfigString()
const FString & FConfigCacheIni::GetCustomConfigString () static
Returns the Custom Config string, which if set will load additional config files from Config/Custom/{CustomConfig}/DefaultX.ini to allow different types of builds.
It can be set from a game Target.cs file with CustomConfig = "Name". Or in development, it can be overridden with a -CustomConfig=Name command line parameter.
GetDestIniFilename()
FString FConfigCacheIni::GetDestIniFilename (const TCHAR * BaseIniName, const TCHAR * PlatformName, const TCHAR * GeneratedConfigDir) static
Calculates the name of a dest (generated) .ini file for a given base (ie Engine, Game, etc)
Parameters
IniBaseName Base name of the .ini (Engine, Game)
PlatformName Name of the platform to get the .ini path for (nullptr means to use the current platform)
GeneratedConfigDir The base folder that will contain the generated config files.
Returns
Standardized .ini filename
References PlatformName.
GetDouble()
bool FConfigCacheIni::GetDouble (const TCHAR * Section, const TCHAR * Key, double & Value, const FString & Filename)
References Filename, GetDouble(), Key, and Value.
Referenced by GetDouble().
GetFilenames()
TArray< FString > FConfigCacheIni::GetFilenames ()
GetFloat()
bool FConfigCacheIni::GetFloat (const TCHAR * Section, const TCHAR * Key, float & Value, const FString & Filename)
References Filename, GetFloat(), Key, and Value.
Referenced by GetFloat(), GetFloatOrDefault(), and GetValue().
GetFloatOrDefault()
float FConfigCacheIni::GetFloatOrDefault (const TCHAR * Section, const TCHAR * Key, const float DefaultValue, const FString & Filename) inline
Definition at line 1542 of file ConfigCacheIni.h.
References Filename, GetFloat(), Key, and Value.
GetInt()
bool FConfigCacheIni::GetInt (const TCHAR * Section, const TCHAR * Key, int32 & Value, const FString & Filename)
References Filename, GetInt(), Key, and Value.
Referenced by GetInt(), GetIntOrDefault(), and GetValue().
GetInt64()
bool FConfigCacheIni::GetInt64 (const TCHAR * Section, const TCHAR * Key, int64 & Value, const FString & Filename)
References Filename, GetInt64(), Key, and Value.
Referenced by GetInt64().
GetIntOrDefault()
int32 FConfigCacheIni::GetIntOrDefault (const TCHAR * Section, const TCHAR * Key, const int32 DefaultValue, const FString & Filename) inline
Definition at line 1536 of file ConfigCacheIni.h.
References Filename, GetInt(), Key, and Value.
GetMaxMemoryUsage()
SIZE_T FConfigCacheIni::GetMaxMemoryUsage ()
USed to get the max memory usage for the FConfigCacheIni.
Returns
the amount of memory in byes
References GetMaxMemoryUsage().
Referenced by GetMaxMemoryUsage().
GetPerObjectConfigSections()
bool FConfigCacheIni::GetPerObjectConfigSections (const FString & Filename, const FString & SearchClass, TArray< FString > & out_SectionNames, int32 MaxResults = 1024)
Retrieve the names of sections which contain data for the specified PerObjectConfig class.
Parameters
Filename the file to retrieve section names from
SearchClass the name of the PerObjectConfig class to retrieve sections for.
out_SectionNames will receive the list of section names that correspond to PerObjectConfig sections of the specified class
MaxResults the maximum number of section names to retrieve
Returns
true if the file specified was found and it contained at least 1 section for the specified class
References Filename, and GetPerObjectConfigSections().
Referenced by GetPerObjectConfigSections().
GetRotator()
bool FConfigCacheIni::GetRotator (const TCHAR * Section, const TCHAR * Key, FRotator & Value, const FString & Filename)
References Filename, GetRotator(), Key, and Value.
Referenced by GetRotator().
GetSection() [1/2]
const FConfigSection * FConfigCacheIni::GetSection (const TCHAR * Section, const bool Force, const FString & Filename)
References Filename, Force, and GetSection().
GetSection() [2/2]
bool FConfigCacheIni::GetSection (const TCHAR * Section, TArray< FString > & Result, const FString & Filename)
References Filename.
Referenced by GetSection().
GetSectionNames()
bool FConfigCacheIni::GetSectionNames (const FString & Filename, TArray< FString > & out_SectionNames)
Retrieve the names for all sections contained in the file specified by Filename.
Parameters
Filename the file to retrieve section names from
out_SectionNames will receive the list of section names
Returns
true if the file specified was successfully found;
References Filename, and GetSectionNames().
Referenced by GetSectionNames().
GetSingleLineArray()
int32 FConfigCacheIni::GetSingleLineArray (const TCHAR * Section, const TCHAR * Key, TArray< FString > & out_Arr, const FString & Filename)
Loads a "delimited" list of strings.
Parameters
Section - Section of the ini file to load from
Key - The key in the section of the ini file to load
out_Arr - Array to load into
Filename - Ini file to load from
References Filename, GetSingleLineArray(), and Key.
Referenced by GetSingleLineArray().
GetStagedGlobalConfigCache()
const TSet< FString > * FConfigCacheIni::GetStagedGlobalConfigCache () const
Returns the staged global config cache.
GetStagedPluginConfigCache()
const TSet< FString > * FConfigCacheIni::GetStagedPluginConfigCache (FName PluginName) const
Finds the Staged Plugin ConfigCache if it exists from a PluginName Returns a pointer to the cache if it exists, a nullptr if not.
GetStr()
FString FConfigCacheIni::GetStr (const TCHAR * Section, const TCHAR * Key, const FString & Filename)
References Filename, GetStr(), and Key.
Referenced by GetStr().
GetString()
bool FConfigCacheIni::GetString (const TCHAR * Section, const TCHAR * Key, FString & Value, const FString & Filename)
References Filename, Key, and Value.
Referenced by GetStringOrDefault(), and GetValue().
GetStringOrDefault()
FString FConfigCacheIni::GetStringOrDefault (const TCHAR * Section, const TCHAR * Key, const FString & DefaultValue, const FString & Filename) inline
Definition at line 1554 of file ConfigCacheIni.h.
References Filename, GetString(), Key, and Value.
GetText()
bool FConfigCacheIni::GetText (const TCHAR * Section, const TCHAR * Key, FText & Value, const FString & Filename)
References Filename, Key, and Value.
Referenced by GetTextOrDefault(), and GetValue().
GetTextOrDefault()
FText FConfigCacheIni::GetTextOrDefault (const TCHAR * Section, const TCHAR * Key, const FText & DefaultValue, const FString & Filename) inline
Definition at line 1566 of file ConfigCacheIni.h.
References Filename, GetText(), Key, and Value.
GetValue() [1/6]
bool FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, bool & Value, const FString & Filename) inline
Definition at line 1523 of file ConfigCacheIni.h.
References Filename, GetBool(), Key, and Value.
GetValue() [2/6]
bool FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, float & Value, const FString & Filename) inline
Definition at line 1519 of file ConfigCacheIni.h.
References Filename, GetFloat(), Key, and Value.
GetValue() [3/6]
bool FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, FString & Value, const FString & Filename) inline
Definition at line 1507 of file ConfigCacheIni.h.
References Filename, GetString(), GetValue(), Key, and Value.
Referenced by GetValue().
GetValue() [4/6]
bool FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, FText & Value, const FString & Filename) inline
Definition at line 1511 of file ConfigCacheIni.h.
References Filename, GetText(), Key, and Value.
GetValue() [5/6]
bool FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, int32 & Value, const FString & Filename) inline
Definition at line 1515 of file ConfigCacheIni.h.
References Filename, GetInt(), Key, and Value.
GetValue() [6/6]
int32 FConfigCacheIni::GetValue (const TCHAR * Section, const TCHAR * Key, TArray< FString > & Value, const FString & Filename) inline
Definition at line 1527 of file ConfigCacheIni.h.
References Filename, GetArray(), Key, and Value.
GetVector()
bool FConfigCacheIni::GetVector (const TCHAR * Section, const TCHAR * Key, FVector & Value, const FString & Filename)
References Filename, FVector, GetVector(), Key, and Value.
Referenced by GetVector().
GetVector2D()
bool FConfigCacheIni::GetVector2D (const TCHAR * Section, const TCHAR * Key, FVector2D & Value, const FString & Filename)
References Filename, GetVector2D(), Key, and Value.
Referenced by GetVector2D().
GetVector4()
bool FConfigCacheIni::GetVector4 (const TCHAR * Section, const TCHAR * Key, FVector4 & Value, const FString & Filename)
References Filename, GetVector4(), Key, and Value.
Referenced by GetVector4().
InitializeConfigSystem()
void FConfigCacheIni::InitializeConfigSystem () static
Creates GConfig, loads the standard global ini files (Engine, Editor, etc), fills out GEngineIni, etc.
and marks GConfig as ready for use
InitializeKnownConfigFiles()
bool FConfigCacheIni::InitializeKnownConfigFiles (FConfigContext & Context) static
Load the standard (used on all platforms) ini files, like Engine, Input, etc.
Parameters
FConfigContext The loading context that controls the destination of the loaded ini files
return True if the engine ini was loaded
References FConfigContext.
IsConfigBranchNameInNeverUnloadList()
bool FConfigCacheIni::IsConfigBranchNameInNeverUnloadList (const FName & ConfigBranchName) private
Does this ConfigBranch IniName appear in our disallowed removal list.
IsGloballyRegistered()
bool FConfigCacheIni::IsGloballyRegistered () const inline
Return whether this is one of the global ConfigSystems: GConfig or FConfigCacheIni::ForPlatform.
Definition at line 1221 of file ConfigCacheIni.h.
References bGloballyRegistered.
IsKnownConfigName()
bool FConfigCacheIni::IsKnownConfigName (FName ConfigName)
Returns true if the given name is one of the known configs, where the matching G****Ini property is going to match the base name ("Engine" returns true, which means GEngineIni's value is just "Engine")
IsReadyForUse()
bool FConfigCacheIni::IsReadyForUse () inline
Returns
true after after the basic .ini files have been loaded
Definition at line 1215 of file ConfigCacheIni.h.
References bIsReadyForUse.
LoadConsoleVariablesFromINI()
void FConfigCacheIni::LoadConsoleVariablesFromINI () static
Needs to be called after GConfig is set and LoadCoalescedFile was called.
Loads the state of console variables. Works even if the variable is registered after the ini file was loaded.
LoadExternalIniFile()
bool FConfigCacheIni::LoadExternalIniFile (FConfigFile & ConfigFile, const TCHAR * IniName, const TCHAR * EngineConfigDir, const TCHAR * SourceConfigDir, bool bIsBaseIniName, const TCHAR * Platform = NULL, bool bForceReload = false, bool bWriteDestIni = false, bool bAllowGeneratedIniWhenCooked = true, const TCHAR * GeneratedConfigDir = *FPaths::GeneratedConfigDir()) static
Load an ini file directly into an FConfigFile from the specified config folders, optionally writing to disk.
The passed in .ini name can be a "base" (Engine, Game) which will be modified by platform and/or commandline override, or it can be a full ini filename (ie WrangleContent) loaded from the Source config directory
Parameters
ConfigFile The output object to fill
IniName Either a Base ini name (Engine) or a full ini name (WrangleContent). NO PATH OR EXTENSION SHOULD BE USED!
EngineConfigDir Engine config directory.
SourceConfigDir Game config directory.
bIsBaseIniName true if IniName is a Base name, which can be overridden on commandline, etc.
Platform The platform to use for Base ini names
bForceReload force reload the ini file from disk this is required if you make changes to the ini file not using the config system as the hierarchy cache will not be updated in this case
bWriteDestIni write out a destination ini file to the Saved folder, only valid if bIsBaseIniName is true
bAllowGeneratedIniWhenCooked If true, the engine will attempt to load the generated/user INI file when loading cooked games
GeneratedConfigDir The location where generated config files are made.
Returns
true if the ini file was loaded successfully
References FPaths::GeneratedConfigDir(), and Platform.
LoadFile()
void FConfigCacheIni::LoadFile (const FString & InFilename, const FConfigFile * Fallback = NULL, const TCHAR * PlatformString = NULL)
LoadGlobalIniFile()
bool FConfigCacheIni::LoadGlobalIniFile (FString & FinalIniFilename, const TCHAR * BaseIniName, const TCHAR * Platform = NULL, bool bForceReload = false, bool bRequireDefaultIni = false, bool bAllowGeneratedIniWhenCooked = true, bool bAllowRemoteConfig = true, const TCHAR * GeneratedConfigDir = *FPaths::GeneratedConfigDir(), FConfigCacheIni * ConfigSystem = GConfig) static
Loads and generates a destination ini file and adds it to GConfig:
Looking on commandline for override source/dest .ini filenames
Generating the name for the engine to refer to the ini
Loading a source .ini file hierarchy
Filling out an FConfigFile
Save the generated ini
Adds the FConfigFile to GConfig
Parameters
FinalIniFilename The output name of the generated .ini file (in Game\Saved\Config)
BaseIniName The "base" ini name, with no extension (ie, Engine, Game, etc)
Platform The platform to load the .ini for (if NULL, uses current)
bForceReload If true, the destination .in will be regenerated from the source, otherwise this will only process if the dest isn't in GConfig
bRequireDefaultIni If true, the Default*.ini file is required to exist when generating the final ini file.
bAllowGeneratedIniWhenCooked If true, the engine will attempt to load the generated/user INI file when loading cooked games
GeneratedConfigDir The location where generated config files are made.
Returns
true if the final ini was created successfully.
References FConfigCacheIni(), GConfig, FPaths::GeneratedConfigDir(), and Platform.
LoadLocalIniFile()
bool FConfigCacheIni::LoadLocalIniFile (FConfigFile & ConfigFile, const TCHAR * IniName, bool bIsBaseIniName, const TCHAR * Platform = NULL, bool bForceReload = false) static
Load an ini file directly into an FConfigFile, and nothing is written to GConfig or disk.
The passed in .ini name can be a "base" (Engine, Game) which will be modified by platform and/or commandline override, or it can be a full ini filename (ie WrangleContent) loaded from the Source config directory
Parameters
ConfigFile The output object to fill
IniName Either a Base ini name (Engine) or a full ini name (WrangleContent). NO PATH OR EXTENSION SHOULD BE USED!
bIsBaseIniName true if IniName is a Base name, which can be overridden on commandline, etc.
Platform The platform to use for Base ini names, NULL means to use the current platform
bForceReload force reload the ini file from disk this is required if you make changes to the ini file not using the config system as the hierarchy cache will not be updated in this case
Returns
true if the ini file was loaded successfully
References Platform.
NormalizeConfigIniPath()
FString FConfigCacheIni::NormalizeConfigIniPath (const FString & NonNormalizedPath) static
Normalizes file paths to INI files.
If an INI file is accessed with multiple paths, then we can run into issues where we cache multiple versions of the file. Specifically, any updates to the file may only be applied to one cached version, and could cause changes to be lost.
E.G.
// Standard path.
C:\ProjectDir\Engine\Config\DefaultEngine.ini
// Lowercase drive, and an extra slash between ProjectDir and Engine.
c:\ProjectDir\\Engine\Confg\DefaultEngine.ini
// Relative to a project binary.
..\..\..\ConfigDefaultEngine.ini
The paths above could all be used to reference the same ini file (namely, DefaultEngine.ini).
However, they would end up generating unique entries in the GConfigCache.
That means any modifications to *one* of the entries would not propagate to the others, and if
any / all of the ini files are saved, they will stomp changes to the other entries.
We can prevent these types of issues by enforcing normalized paths when accessing configs.
Parameters
NonNormalizedPath The path to the INI file we want to access.
Returns
A normalized version of the path (may be the same as the input).
Parse1ToNSectionOfNames()
void FConfigCacheIni::Parse1ToNSectionOfNames (const TCHAR * Section, const TCHAR * KeyOne, const TCHAR * KeyN, TMap< FName, TArray< FName > > & OutMap, const FString & Filename)
Parses apart an ini section that contains a list of 1-to-N mappings of names in the following format [PerMapPackages] MapName=Map1 Package=PackageA Package=PackageB MapName=Map2 Package=PackageC Package=PackageD.
Parameters
Section Name of section to look in
KeyOne Key to use for the 1 in the 1-to-N (MapName in the above example)
KeyN Key to use for the N in the 1-to-N (Package in the above example)
OutMap Map containing parsed results
Filename Filename to use to find the section
NOTE: The function naming is weird because you can't apparently have an overridden function differnt only by template type params
References Filename.
Parse1ToNSectionOfStrings()
void FConfigCacheIni::Parse1ToNSectionOfStrings (const TCHAR * Section, const TCHAR * KeyOne, const TCHAR * KeyN, TMap< FString, TArray< FString > > & OutMap, const FString & Filename)
Prases apart an ini section that contains a list of 1-to-N mappings of strings in the following format [PerMapPackages] MapName=Map1 Package=PackageA Package=PackageB MapName=Map2 Package=PackageC Package=PackageD.
Parameters
Section Name of section to look in
KeyOne Key to use for the 1 in the 1-to-N (MapName in the above example)
KeyN Key to use for the N in the 1-to-N (Package in the above example)
OutMap Map containing parsed results
Filename Filename to use to find the section
NOTE: The function naming is weird because you can't apparently have an overridden function differnt only by template type params
References Filename.
PreInitializePlatformPlugins()
void FConfigCacheIni::PreInitializePlatformPlugins () static
Initializes configs and plugins for every supported platform on worker threads.
This function can be called prior to normal platform initialization to speed up the full initialization process.
RegisterPlugin()
void FConfigCacheIni::RegisterPlugin (FName PluginName, const FString & PluginDir, const TArray< FString > & ChildPluginDirs, DynamicLayerPriority Priority, bool bIncludePluginNameInBranchName) static
Tell GConfig and the ForPlatform config systems about a plugin location.
Remove()
int32 FConfigCacheIni::Remove (const FString & Filename)
References Filename.
RemoveFromSection()
bool FConfigCacheIni::RemoveFromSection (const TCHAR * Section, FName Key, const FString & Value, const FString & Filename)
Removes every entry in the Section in the given File that has the Key/Value pair This is equivalent to the - operator in .ini files (although it will remove all instances of the pair, not just a single one)
Returns
true if the section was modified
References Filename, Key, and Value.
RemoveKey()
bool FConfigCacheIni::RemoveKey (const TCHAR * Section, const TCHAR * Key, const FString & Filename)
References Filename, Key, and RemoveKey().
Referenced by RemoveKey().
RemoveKeyFromSection()
bool FConfigCacheIni::RemoveKeyFromSection (const TCHAR * Section, FName Key, const FString & Filename)
Removes every entry in the Section in the given File that has Key, no matter what the Value is This is equivalent to the !
operator in .ini files
Returns
true if the section was modified
References Filename, and Key.
RemoveMultipleTagsFromAllBranches()
void FConfigCacheIni::RemoveMultipleTagsFromAllBranches (const TArray< FName > & Tags, FConfigModificationTracker * ModificationTracker = nullptr) static
References Tags.
RemoveSectionFromBranch()
bool FConfigCacheIni::RemoveSectionFromBranch (const TCHAR * Section, const TCHAR * Filename)
Removes the section completely from all layers of a branch.
This is destructive! It will not reload on demand (like SafeUnloadBranch does). Use this only when you know you will never need the values in the section again!
Returns
true if anything was removed
References Filename.
RemoveTagFromAllBranches()
void FConfigCacheIni::RemoveTagFromAllBranches (FName Tag, FConfigModificationTracker * ModificationTracker = nullptr) static
RemoveTagsFromBranches()
void FConfigCacheIni::RemoveTagsFromBranches (const TArray< FName > & Tags, FConfigModificationTracker * ModificationTracker) private
References Tags.
ResetKeyInSection()
bool FConfigCacheIni::ResetKeyInSection (const TCHAR * Section, FName Key, const FString & Filename)
Similar to RemvoeKeyFromSection, but if this File's changes are being tracked, then we remove all changes to the the key that have been tracked.
This would be used to remove enries in a layer so that the values from previous layers are used, unmodified. "Reset To Defaults" This is equivalent to deleting the keys from a .ini file
Returns
true if the section was modified
References Filename, and Key.
SafeUnloadBranch()
bool FConfigCacheIni::SafeUnloadBranch (const TCHAR * Filename)
Clears out the memory of a branch, but can reload it on demand if needed.
References Filename.
SaveCurrentStateForBootstrap()
void FConfigCacheIni::SaveCurrentStateForBootstrap (const TCHAR * Filename)
Save the current config cache state into a file for bootstrapping other processes.
References Filename.
Serialize()
void FConfigCacheIni::Serialize (FArchive & Ar)
References Ar.
SerializeStateForBootstrap_Impl()
void FConfigCacheIni::SerializeStateForBootstrap_Impl (FArchive & Ar) private
Serialize a bootstrapping state into or from an archive.
References Ar.
SetArray()
void FConfigCacheIni::SetArray (const TCHAR * Section, const TCHAR * Key, const TArray< FString > & Value, const FString & Filename)
References Filename, Key, and Value.
SetBool()
void FConfigCacheIni::SetBool (const TCHAR * Section, const TCHAR * Key, bool Value, const FString & Filename)
References Filename, Key, and Value.
SetColor()
void FConfigCacheIni::SetColor (const TCHAR * Section, const TCHAR * Key, FColor Value, const FString & Filename)
References Filename, Key, and Value.
SetDouble()
void FConfigCacheIni::SetDouble (const TCHAR * Section, const TCHAR * Key, double Value, const FString & Filename)
References Filename, Key, and Value.
SetFile()
void FConfigCacheIni::SetFile (const FString & InFilename, const FConfigFile * NewConfigFile)
SetFloat()
void FConfigCacheIni::SetFloat (const TCHAR * Section, const TCHAR * Key, float Value, const FString & Filename)
References Filename, Key, and Value.
SetInt()
void FConfigCacheIni::SetInt (const TCHAR * Section, const TCHAR * Key, int32 Value, const FString & Filename)
References Filename, Key, and Value.
SetRotator()
void FConfigCacheIni::SetRotator (const TCHAR * Section, const TCHAR * Key, FRotator Value, const FString & Filename)
References Filename, Key, and Value.
SetSingleLineArray()
void FConfigCacheIni::SetSingleLineArray (const TCHAR * Section, const TCHAR * Key, const TArray< FString > & In_Arr, const FString & Filename)
Saves a "delimited" list of strings.
Parameters
Section - Section of the ini file to save to
Key - The key in the section of the ini file to save
out_Arr - Array to save from
Filename - Ini file to save to
References Filename, and Key.
SetString()
void FConfigCacheIni::SetString (const TCHAR * Section, const TCHAR * Key, const TCHAR * Value, const FString & Filename)
References Filename, Key, SetString(), and Value.
Referenced by SetString().
SetText()
void FConfigCacheIni::SetText (const TCHAR * Section, const TCHAR * Key, const FText & Value, const FString & Filename)
References Filename, Key, SetText(), and Value.
Referenced by SetText().
SetVector()
void FConfigCacheIni::SetVector (const TCHAR * Section, const TCHAR * Key, FVector Value, const FString & Filename)
References Filename, FVector, Key, and Value.
SetVector2D()
void FConfigCacheIni::SetVector2D (const TCHAR * Section, const TCHAR * Key, FVector2D Value, const FString & Filename)
References Filename, Key, and Value.
SetVector4()
void FConfigCacheIni::SetVector4 (const TCHAR * Section, const TCHAR * Key, const FVector4 & Value, const FString & Filename)
References Filename, Key, and Value.
ShowMemoryUsage()
void FConfigCacheIni::ShowMemoryUsage (FOutputDevice & Ar)
Dumps memory stats for each file in the config cache to the specified archive.
Parameters
Ar the output device to dump the results to
References Ar, and ShowMemoryUsage().
Referenced by ShowMemoryUsage().
Tick()
void FConfigCacheIni::Tick (float DeltaSeconds)
Allow for periodic cleanup or other tasks.
UE_DEPRECATED()
FConfigCacheIni::UE_DEPRECATED (5. 4, "Use GetSection instead, and/or use the new AddToSection, etc APIs to modify sections without retrieving the section. See top of ConfigCacheIni.h for more info.") const
Parameters
Force Whether to create the Section on Filename if it did not exist previously.
Const If Const (and not Force), then it will not modify File->Dirty. If not Const (or Force is true), then File->Dirty will be set to true.
UnloadFile()
void FConfigCacheIni::UnloadFile (const FString & Filename)
References Filename.
Friends And Related Symbol Documentation
MakeBinaryConfig
bool MakeBinaryConfig (const TCHAR * CmdLine) friend
Field Documentation
bAreFileOperationsDisabled
bool FConfigCacheIni::bAreFileOperationsDisabled private
true if file operations should not be performed
Definition at line 1955 of file ConfigCacheIni.h.
bGloballyRegistered
bool FConfigCacheIni::bGloballyRegistered private
Definition at line 1960 of file ConfigCacheIni.h.
Referenced by IsGloballyRegistered().
bIsReadyForUse
bool FConfigCacheIni::bIsReadyForUse private
true after the base .ini files have been loaded, and GConfig is generally "ready for use"
Definition at line 1958 of file ConfigCacheIni.h.
Referenced by IsReadyForUse().
ConfigBranchNamesToNeverUnload
TArray<FString> FConfigCacheIni::ConfigBranchNamesToNeverUnload private
List of ConfigBranch names that should never be unloaded.
Read from parsing CVar. See ini.ConfigBranchesToNeverUnload
Definition at line 2000 of file ConfigCacheIni.h.
Const
const bool const bool FConfigCacheIni::Const
Definition at line 1332 of file ConfigCacheIni.h.
FConfigContext
friend FConfigCacheIni::FConfigContext private
Definition at line 2002 of file ConfigCacheIni.h.
Referenced by InitializeKnownConfigFiles().
Filename
const bool const bool const FString& FConfigCacheIni::Filename
Definition at line 1332 of file ConfigCacheIni.h.
Referenced by Add(), AddNewBranch(), AddToSection(), AddUniqueToSection(), CreateGConfigFromSaved(), Detach(), DoesSectionExist(), EmptySection(), EmptySectionsMatchingString(), FindBranch(), FindBranchWithNoReload(), FindConfigFile(), Flush(), ForEachEntry(), GetArray(), GetBool(), GetBoolOrDefault(), GetColor(), GetDouble(), GetFloat(), GetFloatOrDefault(), GetInt(), GetInt64(), GetIntOrDefault(), GetPerObjectConfigSections(), GetRotator(), GetSection(), GetSection(), GetSectionNames(), GetSingleLineArray(), GetStr(), GetString(), GetStringOrDefault(), GetText(), GetTextOrDefault(), GetValue(), GetValue(), GetValue(), GetValue(), GetValue(), GetValue(), GetVector(), GetVector2D(), GetVector4(), Parse1ToNSectionOfNames(), Parse1ToNSectionOfStrings(), Remove(), RemoveFromSection(), RemoveKey(), RemoveKeyFromSection(), RemoveSectionFromBranch(), ResetKeyInSection(), SafeUnloadBranch(), SaveCurrentStateForBootstrap(), SetArray(), SetBool(), SetColor(), SetDouble(), SetFloat(), SetInt(), SetRotator(), SetSingleLineArray(), SetString(), SetText(), SetVector(), SetVector2D(), SetVector4(), and UnloadFile().
Force
const bool FConfigCacheIni::Force
Definition at line 1332 of file ConfigCacheIni.h.
Referenced by GetSection().
KnownFiles
FKnownConfigFiles FConfigCacheIni::KnownFiles private
The filenames for the known files in this config.
Definition at line 1969 of file ConfigCacheIni.h.
OtherFileNames
TArray<FString> FConfigCacheIni::OtherFileNames private
Parallel array to OtherFiles.
Definition at line 1974 of file ConfigCacheIni.h.
OtherFiles
TMap<FString, FConfigBranch*> FConfigCacheIni::OtherFiles private
Definition at line 1971 of file ConfigCacheIni.h.
PendingModificationPlugins
TArray<FName> FConfigCacheIni::PendingModificationPlugins private
Definition at line 1985 of file ConfigCacheIni.h.
PlatformName
FName FConfigCacheIni::PlatformName private
The platform this config system is for - if empty, then it can't be used with dynamic plugin layering.
Definition at line 1966 of file ConfigCacheIni.h.
Referenced by FConfigCacheIni(), ForPlatform(), and GetDestIniFilename().
RegisteredPlugins
TMap<FName, FPluginInfo*> FConfigCacheIni::RegisteredPlugins static private
Definition at line 1984 of file ConfigCacheIni.h.
RegisteredPluginsLock
FTransactionallySafeCriticalSection FConfigCacheIni::RegisteredPluginsLock static private
Definition at line 1986 of file ConfigCacheIni.h.
StagedGlobalConfigCache
TSet<FString>* FConfigCacheIni::StagedGlobalConfigCache = nullptr private
Definition at line 1989 of file ConfigCacheIni.h.
StagedPluginConfigCache
TMap<FName, TSet<FString> > FConfigCacheIni::StagedPluginConfigCache private
Definition at line 1990 of file ConfigCacheIni.h.
Type
EConfigCacheType FConfigCacheIni::Type private
The type of the cache (basically, do we call Flush in the destructor)
Definition at line 1963 of file ConfigCacheIni.h.
Referenced by FConfigCacheIni().
The documentation for this class was generated from the following file:
ConfigCacheIni.h