Unreal Engine 5.6 C++ API: UHierarchicalLODSettings Class Reference
UHierarchicalLODSettings Class Reference
#include "HierarchicalLOD.h"
Private Member Functions
virtual UNREALED_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
GENERATED_UCLASS_BODY() public UPROPERTY () bool bSaveLODActorsToHLODPackages
If enabled will force the project set HLOD level settings to be used across all levels in the project when Building Clusters.
UPROPERTY () TSoftObjectPtr< class UMaterialInterface > BaseMaterial
Base material used for creating a Constant Material Instance as the Proxy Material.
UPROPERTY ()) TArray< FDirectoryPath > DirectoriesForHLODCommandlet
UPROPERTY ()) TArray< FFilePath > MapsToBuild
UPROPERTY ()) TSoftClassPtr< UHierarchicalLODSetup > DefaultSetup
When set in combination with.
Static Private Member Functions
static UNREALED_API bool IsValidFlattenMaterial (const UMaterialInterface *InBaseMaterial, bool bShowToaster)
Detailed Description
Definition at line 28 of file HierarchicalLOD.h.
Member Function Documentation
IsValidFlattenMaterial()
UNREALED_API bool UHierarchicalLODSettings::IsValidFlattenMaterial (const UMaterialInterface * InBaseMaterial, bool bShowToaster) static private
PostEditChangeProperty()
virtual UNREALED_API void UHierarchicalLODSettings::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override private virtual
UPROPERTY() [1/5]
GENERATED_UCLASS_BODY() public UHierarchicalLODSettings::UPROPERTY () private
If enabled will force the project set HLOD level settings to be used across all levels in the project when Building Clusters.
If enabled, will save LOD actors descriptions in the HLOD packages
References Category, and config.
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/5]
UHierarchicalLODSettings::UPROPERTY () private
Base material used for creating a Constant Material Instance as the Proxy Material.
References Category, config, and UPROPERTY().
UPROPERTY() [3/5]
UHierarchicalLODSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [4/5]
UHierarchicalLODSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [5/5]
UHierarchicalLODSettings::UPROPERTY () private
When set in combination with.
References Category, config, and meta.
The documentation for this class was generated from the following file:
HierarchicalLOD.h