Unreal Engine 5.6 C++ API: ShaderKeyGenerator.h File Reference
ShaderKeyGenerator.h File Reference
#include "Containers/StringView.h"
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Misc/StringBuilder.h"
#include "Templates/Function.h"
#include "UObject/NameTypes.h"
Data Structures
class FShaderKeyGenerator
Output class passed to Append functions for shader data.
struct IsFShaderKeyGeneratorKnownType< T, typename >
Template override for struct used in std::enable_if to report whether a type is a FShaderKeyGenerator known type with an Append member function.
struct IsFShaderKeyGeneratorKnownType< T, decltype(std::declval< FShaderKeyGenerator >().Append(std::declval< T >()), 0)>
Template override for struct used in std::enable_if to report whether a type is a FShaderKeyGenerator known type with an Append member function.
Functions
template<typename T>
void Append (FShaderKeyGenerator &KeyGen, const TArray< T > &Value)
Append an Array of handled types to the KeyGen.
template<typename T>
void Append (FShaderKeyGenerator &KeyGen, TConstArrayView< T > Value)
Append an ArrayView of handled types to the KeyGen.
template<typename T>
std::enable_if< IsFShaderKeyGeneratorKnownType< T >::value, FShaderKeyGenerator & >::type operator<< (FShaderKeyGenerator &KeyGen, const T &Value)
Template overide of FShaderKeyGenerator&& operator<<(FShaderKeyGenerator&, const T&), for known types.
template<typename T>
std::enable_if<!IsFShaderKeyGeneratorKnownType< T >::value, FShaderKeyGenerator & >::type operator<< (FShaderKeyGenerator &KeyGen, const T &Value)
Template overide of FShaderKeyGenerator&& operator<<(FShaderKeyGenerator&, const T&), for non-known types.
Function Documentation
Append() [1/2]
template<typename T> void Append (FShaderKeyGenerator & KeyGen, const TArray< T > & Value)
Append an Array of handled types to the KeyGen.
Definition at line 323 of file ShaderKeyGenerator.h.
References Append(), and Value.
Append() [2/2]
template<typename T> void Append (FShaderKeyGenerator & KeyGen, TConstArrayView< T > Value)
Append an ArrayView of handled types to the KeyGen.
Calls operator<<(KeyGen, TypeName) on each element.
Definition at line 329 of file ShaderKeyGenerator.h.
References Value.
Referenced by Append(), ENUM_CLASS_FLAGS(), operator<<(), TLinkedListBuilder< UField >::UE_DEPRECATED(), UE_DEPRECATED(), USTRUCT(), USTRUCT(), and USTRUCT().
operator<<() [1/2]
template<typename T> std::enable_if< IsFShaderKeyGeneratorKnownType< T >::value, FShaderKeyGenerator & >::type operator<< (FShaderKeyGenerator & KeyGen, const T & Value)
Template overide of FShaderKeyGenerator&& operator<<(FShaderKeyGenerator&, const T&), for known types.
Definition at line 359 of file ShaderKeyGenerator.h.
References FShaderKeyGenerator::Append(), and Value.
operator<<() [2/2]
template<typename T> std::enable_if<!IsFShaderKeyGeneratorKnownType< T >::value, FShaderKeyGenerator & >::type operator<< (FShaderKeyGenerator & KeyGen, const T & Value)
Template overide of FShaderKeyGenerator&& operator<<(FShaderKeyGenerator&, const T&), for non-known types.
Definition at line 368 of file ShaderKeyGenerator.h.
References Append(), and Value.