Unreal Engine 5.6 C++ API: UE::AnimNext::Private::FAllocatedBlock Struct Reference
UE::AnimNext::Private::FAllocatedBlock Struct Reference
#include "DataRegistryTypes.h"
Public Member Functions
FAllocatedBlock (void *InMemory, int32 InNumElem, FAnimNextParamType InType)
uint32 AddRef () const
uint32 GetRefCount () const
uint32 Release () const
Data Fields
void * Memory = nullptr
int32 NumElem = 0
int32 NumRefs = 0
FAnimNextParamType Type
Private Member Functions
FAllocatedBlock ()=delete
FAllocatedBlock (const FAllocatedBlock &Other)=delete
FAllocatedBlock (FAllocatedBlock &&Other)=delete
Detailed Description
Definition at line 20 of file DataRegistryTypes.h.
Constructor & Destructor Documentation
FAllocatedBlock() [1/4]
UE::AnimNext::Private::FAllocatedBlock::FAllocatedBlock (void * InMemory, int32 InNumElem, FAnimNextParamType InType) inline
Definition at line 27 of file DataRegistryTypes.h.
References Memory, NumElem, and Type.
Referenced by FAllocatedBlock(), and FAllocatedBlock().
FAllocatedBlock() [2/4]
UE::AnimNext::Private::FAllocatedBlock::FAllocatedBlock () private delete
FAllocatedBlock() [3/4]
UE::AnimNext::Private::FAllocatedBlock::FAllocatedBlock (const FAllocatedBlock & Other) private delete
References FAllocatedBlock(), and Other.
FAllocatedBlock() [4/4]
UE::AnimNext::Private::FAllocatedBlock::FAllocatedBlock (FAllocatedBlock && Other) private delete
References FAllocatedBlock(), and Other.
Member Function Documentation
AddRef()
uint32 UE::AnimNext::Private::FAllocatedBlock::AddRef () const inline
Definition at line 34 of file DataRegistryTypes.h.
References NumRefs.
Referenced by UE::AnimNext::FDataRegistry::PreAllocateMemory().
GetRefCount()
uint32 UE::AnimNext::Private::FAllocatedBlock::GetRefCount () const inline
Definition at line 49 of file DataRegistryTypes.h.
References NumRefs.
Release()
uint32 UE::AnimNext::Private::FAllocatedBlock::Release () const inline
Definition at line 39 of file DataRegistryTypes.h.
References check, and NumRefs.
Field Documentation
Memory
void* UE::AnimNext::Private::FAllocatedBlock::Memory = nullptr
Definition at line 22 of file DataRegistryTypes.h.
Referenced by FAllocatedBlock().
NumElem
int32 UE::AnimNext::Private::FAllocatedBlock::NumElem = 0
Definition at line 23 of file DataRegistryTypes.h.
Referenced by FAllocatedBlock().
NumRefs
int32 UE::AnimNext::Private::FAllocatedBlock::NumRefs = 0 mutable
Definition at line 24 of file DataRegistryTypes.h.
Referenced by AddRef(), GetRefCount(), and Release().
Type
FAnimNextParamType UE::AnimNext::Private::FAllocatedBlock::Type
Definition at line 25 of file DataRegistryTypes.h.
Referenced by FAllocatedBlock().
The documentation for this struct was generated from the following file:
DataRegistryTypes.h