Unreal Engine 5.6 C++ API: UUVEditorChannelEditToolActionPropertySet Class Reference
UUVEditorChannelEditToolActionPropertySet Class Reference
#include "UVEditorLayerEditTool.h"
Public Member Functions
void Apply ()
void Initialize (UUVEditorChannelEditTool *ParentToolIn)
void PostAction (EChannelEditToolAction Action)
Data Fields
TWeakObjectPtr< UUVEditorChannelEditTool > ParentTool
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 148 of file UVEditorLayerEditTool.h.
Member Function Documentation
Apply()
void UUVEditorChannelEditToolActionPropertySet::Apply ()
References Apply(), and UCLASS.
Referenced by Apply().
Initialize()
void UUVEditorChannelEditToolActionPropertySet::Initialize (UUVEditorChannelEditTool * ParentToolIn) inline
Definition at line 155 of file UVEditorLayerEditTool.h.
References Initialize(), and ParentTool.
Referenced by Initialize().
PostAction()
void UUVEditorChannelEditToolActionPropertySet::PostAction (EChannelEditToolAction Action)
References Category.
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorChannelEditToolActionPropertySet::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 150 of file UVEditorLayerEditTool.h.
ParentTool
TWeakObjectPtr<UUVEditorChannelEditTool> UUVEditorChannelEditToolActionPropertySet::ParentTool
Definition at line 153 of file UVEditorLayerEditTool.h.
Referenced by Initialize().
The documentation for this class was generated from the following file:
UVEditorLayerEditTool.h