Unreal Engine 5.6 C++ API: FCurveEditorTreeItemID Struct Reference
FCurveEditorTreeItemID Struct Reference
#include "CurveEditorTypes.h"
Public Member Functions
FCurveEditorTreeItemID ()
uint32 GetValue () const
bool IsValid () const
Static Public Member Functions
static FCurveEditorTreeItemID Invalid ()
Protected Attributes
uint32 Value
Friends
class FCurveEditorTree
uint32 GetTypeHash (FCurveEditorTreeItemID ID)
bool operator!= (FCurveEditorTreeItemID A, FCurveEditorTreeItemID B)
bool operator== (FCurveEditorTreeItemID A, FCurveEditorTreeItemID B)
Detailed Description
Definition at line 130 of file CurveEditorTypes.h.
Constructor & Destructor Documentation
FCurveEditorTreeItemID()
FCurveEditorTreeItemID::FCurveEditorTreeItemID () inline
Definition at line 132 of file CurveEditorTypes.h.
References Value.
Referenced by TListTypeTraits< FCurveEditorTreeItemID >::NullableType::NullableType(), GetTypeHash, Invalid(), operator!=, and operator==.
Member Function Documentation
GetValue()
uint32 FCurveEditorTreeItemID::GetValue () const inline
Definition at line 161 of file CurveEditorTypes.h.
References Value.
Referenced by TListTypeTraits< FCurveEditorTreeItemID >::DebugDump().
Invalid()
FCurveEditorTreeItemID FCurveEditorTreeItemID::Invalid () inline static
Definition at line 151 of file CurveEditorTypes.h.
References FCurveEditorTreeItemID().
Referenced by UE::Sequencer::FCurveEditorTreeItemExtensionShim::OnRemovedFromCurveEditor().
IsValid()
bool FCurveEditorTreeItemID::IsValid () const inline
Definition at line 156 of file CurveEditorTypes.h.
References Value.
Referenced by TListTypeTraits< FCurveEditorTreeItemID >::IsPtrValid().
Friends And Related Symbol Documentation
FCurveEditorTree
friend class FCurveEditorTree friend
Definition at line 168 of file CurveEditorTypes.h.
References FCurveEditorTree.
Referenced by FCurveEditorTree.
GetTypeHash
uint32 GetTypeHash (FCurveEditorTreeItemID ID) friend
Definition at line 146 of file CurveEditorTypes.h.
References FCurveEditorTreeItemID(), GetTypeHash, and ID.
Referenced by GetTypeHash.
operator!=
bool operator!= (FCurveEditorTreeItemID A, FCurveEditorTreeItemID B) friend
Definition at line 141 of file CurveEditorTypes.h.
References FCurveEditorTreeItemID(), A, and B.
operator==
bool operator== (FCurveEditorTreeItemID A, FCurveEditorTreeItemID B) friend
Definition at line 136 of file CurveEditorTypes.h.
References FCurveEditorTreeItemID(), A, and B.
Field Documentation
Value
uint32 FCurveEditorTreeItemID::Value protected
Definition at line 169 of file CurveEditorTypes.h.
Referenced by FCurveEditorTreeItemID(), GetValue(), and IsValid().
The documentation for this struct was generated from the following file:
CurveEditorTypes.h