Unreal Engine 5.6 C++ API: FHazardPointerCollection::THazardDeleter< D > Class Template Reference
FHazardPointerCollection::THazardDeleter< D > Class Template Reference final
Public Member Functions
THazardDeleter (D *InPointer)
void Delete () override
Public Member Functions inherited from HazardPointer_Impl::FHazardDeleter
FHazardDeleter (const FHazardDeleter &Other)
FHazardDeleter & operator= (const FHazardDeleter &Other)
bool operator== (const FHazardDeleter &Other) const
Additional Inherited Members
Protected Member Functions inherited from HazardPointer_Impl::FHazardDeleter
FHazardDeleter (void *InPointer)
Protected Attributes inherited from HazardPointer_Impl::FHazardDeleter
void * Pointer
Detailed Description
template<typename D>
class FHazardPointerCollection::THazardDeleter< D >
Definition at line 123 of file HazardPointer.h.
Constructor & Destructor Documentation
THazardDeleter()
template<typename D> FHazardPointerCollection::THazardDeleter< D >::THazardDeleter (D * InPointer) inline
Definition at line 126 of file HazardPointer.h.
References HazardPointer_Impl::FHazardDeleter::FHazardDeleter(), and THazardDeleter().
Referenced by THazardDeleter().
Member Function Documentation
Delete()
template<typename D> void FHazardPointerCollection::THazardDeleter< D >::Delete () inline override virtual
Reimplemented from HazardPointer_Impl::FHazardDeleter.
Definition at line 131 of file HazardPointer.h.
References HazardPointer_Impl::FHazardDeleter::Pointer.
The documentation for this class was generated from the following file:
HazardPointer.h