Unreal Engine 5.6 C++ API: FRigVMUnitNodeCreatedContext Struct Reference
FRigVMUnitNodeCreatedContext Struct Reference
A context struct passed to FRigVMStruct::OnUnitNodeCreated.
#include "RigVMStruct.h"
Data Structures
struct FScope
Public Member Functions
RIGVM_API FName AddExternalVariable (const FRigVMExternalVariable &InVariableToCreate, FString InDefaultValue=FString())
Creates a new variable within the host of this VM.
RIGVM_API bool BindPinToExternalVariable (FString InPinPath, FString InVariablePath)
Binds a pin to an external variable on the created node.
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value >::Type * = nullptr>
FName FindFirstVariableOfType () const
Returns the name of the first variable given a type (or NAME_None if not found)
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr>
FName FindFirstVariableOfType () const
Returns the name of the first variable given a type (or NAME_None if not found)
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr>
FName FindFirstVariableOfType () const
Returns the name of the first variable given a type (or NAME_None if not found)
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr>
FName FindFirstVariableOfType () const
Returns the name of the first variable given a type (or NAME_None if not found)
RIGVM_API FName FindFirstVariableOfType (FName InCPPTypeName) const
Returns the name of the first variable given a(or NAME_None if not found)
RIGVM_API FRigVMExternalVariable FindVariable (FName InVariableName) const
Returns a variable given a name (or a non-valid variable if not found)
FRigVMGetExternalVariablesDelegate & GetAllExternalVariablesDelegate ()
FRigVMBindPinToExternalVariableDelegate & GetBindPinToExternalVariableDelegate ()
URigVMController * GetController () const
FRigVMCreateExternalVariableDelegate & GetCreateExternalVariableDelegate ()
RIGVM_API TArray< FRigVMExternalVariable > GetExternalVariables () const
Returns all currently existing external variables.
IRigVMClientHost * GetHost () const
FName GetNodeName () const
Get the name of this node.
ERigVMNodeCreatedReason GetReason () const
Get the reason why this node was created.
RIGVM_API bool IsValid () const
Returns true if this context is valid to use.
Private Member Functions
RIGVM_API FName FindFirstVariableOfType (UObject *InCPPTypeObject) const
Private Attributes
FRigVMGetExternalVariablesDelegate AllExternalVariablesDelegate
FRigVMBindPinToExternalVariableDelegate BindPinToExternalVariableDelegate
URigVMController * Controller = nullptr
FRigVMCreateExternalVariableDelegate CreateExternalVariableDelegate
IRigVMClientHost * Host = nullptr
FName NodeName = NAME_None
ERigVMNodeCreatedReason Reason = ERigVMNodeCreatedReason::Unknown
Friends
struct FScope
class URigVMController
Detailed Description
A context struct passed to FRigVMStruct::OnUnitNodeCreated.
Definition at line 54 of file RigVMStruct.h.
Member Function Documentation
AddExternalVariable()
RIGVM_API FName FRigVMUnitNodeCreatedContext::AddExternalVariable (const FRigVMExternalVariable & InVariableToCreate, FString InDefaultValue = FString())
Creates a new variable within the host of this VM.
References FRigVMExternalVariable.
BindPinToExternalVariable()
RIGVM_API bool FRigVMUnitNodeCreatedContext::BindPinToExternalVariable (FString InPinPath, FString InVariablePath)
Binds a pin to an external variable on the created node.
FindFirstVariableOfType() [1/6]
template<typename T, typename TEnableIf< TRigVMIsBaseStructure< T >::Value >::Type * = nullptr> FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType () const inline
Returns the name of the first variable given a type (or NAME_None if not found)
Definition at line 124 of file RigVMStruct.h.
References FindFirstVariableOfType(), and TBaseStructureBase< T, bHasStaticStruct >::Get().
Referenced by FindFirstVariableOfType().
FindFirstVariableOfType() [2/6]
template<typename T, typename TEnableIf< TModels_V< CRigVMUStruct, T > >::Type * = nullptr> FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType () const inline
Returns the name of the first variable given a type (or NAME_None if not found)
Definition at line 134 of file RigVMStruct.h.
References FindFirstVariableOfType().
FindFirstVariableOfType() [3/6]
template<typename T, typename TEnableIf< TModels_V< CRigVMUClass, T > >::Type * = nullptr> FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType () const inline
Returns the name of the first variable given a type (or NAME_None if not found)
Definition at line 144 of file RigVMStruct.h.
References FindFirstVariableOfType().
FindFirstVariableOfType() [4/6]
template<typename T, typename TEnableIf< TIsEnum< T >::Value >::Type * = nullptr> FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType () const inline
Returns the name of the first variable given a type (or NAME_None if not found)
Definition at line 154 of file RigVMStruct.h.
References FindFirstVariableOfType(), and StaticEnum().
FindFirstVariableOfType() [5/6]
RIGVM_API FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType (FName InCPPTypeName) const
Returns the name of the first variable given a(or NAME_None if not found)
FindFirstVariableOfType() [6/6]
RIGVM_API FName FRigVMUnitNodeCreatedContext::FindFirstVariableOfType (UObject * InCPPTypeObject) const private
FindVariable()
RIGVM_API FRigVMExternalVariable FRigVMUnitNodeCreatedContext::FindVariable (FName InVariableName) const
Returns a variable given a name (or a non-valid variable if not found)
References FRigVMExternalVariable.
GetAllExternalVariablesDelegate()
FRigVMGetExternalVariablesDelegate & FRigVMUnitNodeCreatedContext::GetAllExternalVariablesDelegate () inline
Definition at line 159 of file RigVMStruct.h.
References AllExternalVariablesDelegate.
GetBindPinToExternalVariableDelegate()
FRigVMBindPinToExternalVariableDelegate & FRigVMUnitNodeCreatedContext::GetBindPinToExternalVariableDelegate () inline
Definition at line 161 of file RigVMStruct.h.
References BindPinToExternalVariableDelegate.
GetController()
URigVMController * FRigVMUnitNodeCreatedContext::GetController () const inline
Definition at line 97 of file RigVMStruct.h.
References Controller, and URigVMController.
GetCreateExternalVariableDelegate()
FRigVMCreateExternalVariableDelegate & FRigVMUnitNodeCreatedContext::GetCreateExternalVariableDelegate () inline
Definition at line 160 of file RigVMStruct.h.
References CreateExternalVariableDelegate, and FRigVMCreateExternalVariableDelegate.
GetExternalVariables()
RIGVM_API TArray< FRigVMExternalVariable > FRigVMUnitNodeCreatedContext::GetExternalVariables () const
Returns all currently existing external variables.
GetHost()
IRigVMClientHost * FRigVMUnitNodeCreatedContext::GetHost () const inline
Definition at line 98 of file RigVMStruct.h.
References Host.
Referenced by FRigVMUnitNodeCreatedContext::FScope::FScope().
GetNodeName()
FName FRigVMUnitNodeCreatedContext::GetNodeName () const inline
Get the name of this node.
Definition at line 102 of file RigVMStruct.h.
References NodeName.
GetReason()
ERigVMNodeCreatedReason FRigVMUnitNodeCreatedContext::GetReason () const inline
Get the reason why this node was created.
Definition at line 94 of file RigVMStruct.h.
References Reason.
Referenced by FRigVMUnitNodeCreatedContext::FScope::FScope().
IsValid()
RIGVM_API bool FRigVMUnitNodeCreatedContext::IsValid () const
Returns true if this context is valid to use.
Friends And Related Symbol Documentation
FScope
friend struct FScope friend
Definition at line 178 of file RigVMStruct.h.
URigVMController
friend class URigVMController friend
Definition at line 177 of file RigVMStruct.h.
References URigVMController.
Referenced by GetController(), and URigVMController.
Field Documentation
AllExternalVariablesDelegate
FRigVMGetExternalVariablesDelegate FRigVMUnitNodeCreatedContext::AllExternalVariablesDelegate private
Definition at line 171 of file RigVMStruct.h.
Referenced by GetAllExternalVariablesDelegate().
BindPinToExternalVariableDelegate
FRigVMBindPinToExternalVariableDelegate FRigVMUnitNodeCreatedContext::BindPinToExternalVariableDelegate private
Definition at line 173 of file RigVMStruct.h.
Referenced by GetBindPinToExternalVariableDelegate().
Controller
URigVMController* FRigVMUnitNodeCreatedContext::Controller = nullptr private
Definition at line 166 of file RigVMStruct.h.
Referenced by GetController().
CreateExternalVariableDelegate
FRigVMCreateExternalVariableDelegate FRigVMUnitNodeCreatedContext::CreateExternalVariableDelegate private
Definition at line 172 of file RigVMStruct.h.
Referenced by GetCreateExternalVariableDelegate().
Host
IRigVMClientHost* FRigVMUnitNodeCreatedContext::Host = nullptr private
Definition at line 167 of file RigVMStruct.h.
Referenced by GetHost().
NodeName
FName FRigVMUnitNodeCreatedContext::NodeName = NAME_None private
Definition at line 169 of file RigVMStruct.h.
Referenced by GetNodeName().
Reason
ERigVMNodeCreatedReason FRigVMUnitNodeCreatedContext::Reason = ERigVMNodeCreatedReason::Unknown private
Definition at line 170 of file RigVMStruct.h.
Referenced by GetReason().
The documentation for this struct was generated from the following file:
RigVMStruct.h