Unreal Engine 5.6 C++ API: FScriptSetHelper Class Reference
FScriptSetHelper Class Reference
FScriptSetHelper: Pseudo dynamic Set.
#include "UnrealType.h"
Public Types
using FIterator = TScriptContainerIterator<FScriptSetHelper>
Public Member Functions
FScriptSetHelper (const FSetProperty *InProperty, const void *InSet)
Constructor, brings together a property and an instance of the property located in memory.
FScriptSetHelper (FProperty *InElementProp, const void *InSet, const FScriptSetLayout &InLayout)
int32 AddDefaultValue_Invalid_NeedsRehash ()
Adds a blank, constructed value to a given size.
void AddElement (const void *ElementToAdd)
Adds the element to the set, returning true if the element was added, or false if the element was already present.
FORCEINLINE int32 AddUninitializedValue ()
Add an uninitialized value to the end of the set.
FIterator CreateIterator () const
FIterator CreateIterator (const int32 InLogicalIndex) const
void EmptyElements (int32 Slack=0)
Remove all values from the set, calling destructors, etc as appropriate.
int32 FindElementIndex (const void *ElementToFind, int32 IndexHint=0) const
Finds the index of an element in a set.
FORCEINLINE int32 FindElementIndexFromHash (const void *ElementToFind) const
Finds element index from hash, rather than linearly searching.
FORCEINLINE uint8 * FindElementPtr (const void *ElementToFind, int32 IndexHint=0)
Finds the pair in a map which matches the key in another pair.
FORCEINLINE uint8 * FindElementPtrFromHash (const void *ElementToFind)
Finds element pointer from hash, rather than linearly searching.
int32 FindInternalIndex (int32 LogicalIdx) const
Sets have gaps in their indices, so this function translates a logical index (ie.
int32 FindLogicalIndex (int32 InternalIdx) const
Sets have gaps in their indices, so this function translates a internal index to an logical index (ie.
uint8 * FindNthElementPtr (int32 N)
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
const uint8 * FindNthElementPtr (int32 N) const
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
FProperty * GetElementProperty () const
Returns the property representing the element of the set.
FORCEINLINE uint8 * GetElementPtr (const FIterator Iterator)
Returns a uint8 pointer to the element in the set.
FORCEINLINE const uint8 * GetElementPtr (const FIterator Iterator) const
Returns a uint8 pointer to the element in the set.
FORCEINLINE uint8 * GetElementPtr (int32 InternalIndex)
Returns a uint8 pointer to the element in the set.
FORCEINLINE const uint8 * GetElementPtr (int32 InternalIndex) const
Returns a uint8 pointer to the element in the set.
FORCEINLINE int32 GetMaxIndex () const
Returns the (non-inclusive) maximum index of elements in the set.
FORCEINLINE bool IsValidIndex (int32 InternalIndex) const
Index range check.
void MoveAssign (void *InOtherSet)
Move the allocation from another set and make it our own.
FORCEINLINE int32 Num () const
Returns the number of elements in the set.
FORCEINLINE int32 NumUnchecked () const
Returns the number of elements in the set.
void Rehash ()
Rehashes the keys in the set.
void RemoveAt (int32 InternalIndex, int32 Count=1)
Removes an element at the specified index, destroying it.
bool RemoveElement (const void *ElementToRemove)
Removes the element from the set.
Static Public Member Functions
static FScriptSetHelper CreateHelperFormElementProperty (FProperty *InElementProperty, const void *InSet)
static FORCEINLINE int32 Num (const void *Target)
Static version of Num() used when you don't need to bother to construct a FScriptSetHelper.
Data Fields
FProperty * ElementProp
FScriptSet * Set
FScriptSetLayout SetLayout
Private Member Functions
FScriptSetHelper ()
void ConstructItem (int32 InternalIndex)
Internal function to call into the property system to construct / initialize elements.
void DestructItems (int32 InternalIndex, int32 Count)
Internal function to call into the property system to destruct elements.
FORCEINLINE uint8 * GetElementPtrWithoutCheck (int32 InternalIndex)
Returns a uint8 pointer to the element in the array without checking the index.
FORCEINLINE const uint8 * GetElementPtrWithoutCheck (int32 InternalIndex) const
Returns a uint8 pointer to the element in the array without checking the index.
Friends
class FSetProperty
Detailed Description
FScriptSetHelper: Pseudo dynamic Set.
Used to work with Set properties in a sensible way. Note that the set can contain invalid entries some number of valid entries (i.e. Num()) can be smaller that the actual number of elements (i.e. GetMaxIndex()).
Internal index naming is used to identify the actual index in the container which can point to an invalid entry. It can be used for methods like Get<Item>Ptr, Get<Item>PtrWithoutCheck or IsValidIndex.
Logical index naming is used to identify only valid entries in the container so it can be smaller than the internal index in case we skipped invalid entries to reach the next valid one. This index is used on method like FindNth<Item>Ptr or FindInternalIndex. This is also the type of index we receive from most editor events (e.g. property change events) so it is strongly suggested to rely on FScriptSetHelper::FIterator to iterate or convert to internal index.
Definition at line 5327 of file UnrealType.h.
Member Typedef Documentation
FIterator
using FScriptSetHelper::FIterator = TScriptContainerIterator<FScriptSetHelper>
Definition at line 5333 of file UnrealType.h.
Constructor & Destructor Documentation
FScriptSetHelper() [1/3]
FScriptSetHelper::FScriptSetHelper (const FSetProperty * InProperty, const void * InSet) inline
Constructor, brings together a property and an instance of the property located in memory.
Parameters
InProperty The property associated with this memory
InSet Pointer to raw memory that corresponds to this Set. This can be NULL, and sometimes is, but in that case almost all operations will crash.
Definition at line 5351 of file UnrealType.h.
References FScriptSetHelper(), ElementProp, FSetProperty, and SetLayout.
Referenced by FPropertyBagSetRef::FPropertyBagSetRef(), FScriptSetHelper(), FScriptSetHelper_InContainer::FScriptSetHelper_InContainer(), CreateHelperFormElementProperty(), GetElementPtr(), GetElementPtr(), and GetElementPtrWithoutCheck().
FScriptSetHelper() [2/3]
FScriptSetHelper::FScriptSetHelper (FProperty * InElementProp, const void * InSet, const FScriptSetLayout & InLayout) inline
Definition at line 5356 of file UnrealType.h.
References check, ElementProp, Set, and SetLayout.
FScriptSetHelper() [3/3]
FScriptSetHelper::FScriptSetHelper () inline private
Definition at line 5817 of file UnrealType.h.
References ElementProp, Set, and SetLayout.
Member Function Documentation
AddDefaultValue_Invalid_NeedsRehash()
int32 FScriptSetHelper::AddDefaultValue_Invalid_NeedsRehash () inline
Adds a blank, constructed value to a given size.
Note that this will create an invalid Set because all the keys will be default constructed, and the set needs rehashing.
Returns
The index of the first element added.
Definition at line 5555 of file UnrealType.h.
References AddUninitializedValue(), checkSlow, ConstructItem(), and Num.
AddElement()
void FScriptSetHelper::AddElement (const void * ElementToAdd) inline
Adds the element to the set, returning true if the element was added, or false if the element was already present.
Definition at line 5748 of file UnrealType.h.
References A, B, FProperty::CopySingleValueToScriptVM(), FProperty::DestroyValue(), ElementProp, FProperty::GetSize(), FProperty::GetValueTypeHash(), FProperty::Identical, FProperty::InitializeValue(), FMemory::Memzero(), FProperty::PropertyFlags, Set, and SetLayout.
Referenced by FPropertyBagSetRef::Add().
AddUninitializedValue()
FORCEINLINE int32 FScriptSetHelper::AddUninitializedValue () inline
Add an uninitialized value to the end of the set.
Returns
The index of the added element.
Definition at line 5523 of file UnrealType.h.
References checkSlow, FORCEINLINE, Num, Set, and SetLayout.
Referenced by AddDefaultValue_Invalid_NeedsRehash().
ConstructItem()
void FScriptSetHelper::ConstructItem (int32 InternalIndex) inline private
Internal function to call into the property system to construct / initialize elements.
Parameters
InternalIndex First item to construct.
Count Number of items to construct.
Definition at line 5829 of file UnrealType.h.
References check, ElementProp, GetElementPtrWithoutCheck(), IsValidIndex(), FMemory::Memzero(), and SetLayout.
Referenced by AddDefaultValue_Invalid_NeedsRehash().
CreateHelperFormElementProperty()
FScriptSetHelper FScriptSetHelper::CreateHelperFormElementProperty (FProperty * InElementProperty, const void * InSet) inline static
Definition at line 5801 of file UnrealType.h.
References FScriptSetHelper(), check, ElementProp, FProperty::GetMinAlignment(), TScriptSet< FDefaultSetAllocator, FScriptSet >::GetScriptLayout(), FProperty::GetSize(), Set, and SetLayout.
CreateIterator() [1/2]
FIterator FScriptSetHelper::CreateIterator () const inline
Definition at line 5335 of file UnrealType.h.
CreateIterator() [2/2]
FIterator FScriptSetHelper::CreateIterator (const int32 InLogicalIndex) const inline
Definition at line 5340 of file UnrealType.h.
DestructItems()
void FScriptSetHelper::DestructItems (int32 InternalIndex, int32 Count) inline private
Internal function to call into the property system to destruct elements.
Definition at line 5851 of file UnrealType.h.
References check, Count, ElementProp, GetElementPtrWithoutCheck(), IsValidIndex(), and SetLayout.
EmptyElements()
void FScriptSetHelper::EmptyElements (int32 Slack = 0) inline
Remove all values from the set, calling destructors, etc as appropriate.
Parameters
Slack used to presize the set for a subsequent add, to avoid reallocation.
Definition at line 5534 of file UnrealType.h.
References checkSlow, DestructItems(), NumUnchecked(), Set, and SetLayout.
FindElementIndex()
int32 FScriptSetHelper::FindElementIndex (const void * ElementToFind, int32 IndexHint = 0) const inline
Finds the index of an element in a set.
Parameters
ElementToFind The address of an element to search for.
IndexHint The index to start searching from.
Returns
The index of an element found in SetHelper, or -1 if none was found.
Definition at line 5670 of file UnrealType.h.
References check, GetElementPtrWithoutCheck(), GetMaxIndex(), FProperty::Identical, INDEX_NONE, and IsValidIndex().
Referenced by FPropertyBagSetRef::Add(), FPropertyBagSetRef::Contains(), FindElementPtr(), and FPropertyBagSetRef::Remove().
FindElementIndexFromHash()
FORCEINLINE int32 FScriptSetHelper::FindElementIndexFromHash (const void * ElementToFind) const inline
Finds element index from hash, rather than linearly searching.
Definition at line 5728 of file UnrealType.h.
References A, B, ElementProp, FORCEINLINE, FProperty::GetValueTypeHash(), FProperty::Identical, Set, and SetLayout.
Referenced by FindElementPtrFromHash().
FindElementPtr()
FORCEINLINE uint8 * FScriptSetHelper::FindElementPtr (const void * ElementToFind, int32 IndexHint = 0) inline
Finds the pair in a map which matches the key in another pair.
Parameters
PairWithKeyToFind The address of a map pair which contains the key to search for.
IndexHint The index to start searching from.
Returns
A pointer to the found pair, or nullptr if none was found.
Definition at line 5720 of file UnrealType.h.
References FindElementIndex(), FORCEINLINE, and GetElementPtrWithoutCheck().
FindElementPtrFromHash()
FORCEINLINE uint8 * FScriptSetHelper::FindElementPtrFromHash (const void * ElementToFind) inline
Finds element pointer from hash, rather than linearly searching.
Definition at line 5740 of file UnrealType.h.
References FindElementIndexFromHash(), FORCEINLINE, and GetElementPtrWithoutCheck().
FindInternalIndex()
int32 FScriptSetHelper::FindInternalIndex (int32 LogicalIdx) const inline
Sets have gaps in their indices, so this function translates a logical index (ie.
Nth element) to an internal index that can be used for the other functions in this class. NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Definition at line 5604 of file UnrealType.h.
References GetMaxIndex(), INDEX_NONE, IsValidIndex(), and Num.
Referenced by FindNthElementPtr(), and FindNthElementPtr().
FindLogicalIndex()
int32 FScriptSetHelper::FindLogicalIndex (int32 InternalIdx) const inline
Sets have gaps in their indices, so this function translates a internal index to an logical index (ie.
Nth element). NOTE: This is slow, do not use this for iteration!
Definition at line 5637 of file UnrealType.h.
References GetMaxIndex(), INDEX_NONE, IsValidIndex(), and Num.
FindNthElementPtr() [1/2]
uint8 * FScriptSetHelper::FindNthElementPtr (int32 N) inline
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 5487 of file UnrealType.h.
References FindInternalIndex(), GetElementPtrWithoutCheck(), and INDEX_NONE.
FindNthElementPtr() [2/2]
const uint8 * FScriptSetHelper::FindNthElementPtr (int32 N) const inline
Returns a uint8 pointer to the the Nth valid element in the set (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 5499 of file UnrealType.h.
References FindInternalIndex(), GetElementPtrWithoutCheck(), and INDEX_NONE.
GetElementProperty()
FProperty * FScriptSetHelper::GetElementProperty () const inline
Returns the property representing the element of the set.
Definition at line 5568 of file UnrealType.h.
References ElementProp.
GetElementPtr() [1/4]
FORCEINLINE uint8 * FScriptSetHelper::GetElementPtr (const FIterator Iterator) inline
Returns a uint8 pointer to the element in the set.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the element, or will fail a check if an invalid iterator is provided.
Definition at line 5463 of file UnrealType.h.
References checkf, FORCEINLINE, TScriptContainerIterator< ContainerType >::GetInternalIndex(), Set, SetLayout, and TEXT.
GetElementPtr() [2/4]
FORCEINLINE const uint8 * FScriptSetHelper::GetElementPtr (const FIterator Iterator) const inline
Returns a uint8 pointer to the element in the set.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the element, or will fail a check if an invalid iterator is provided.
Definition at line 5476 of file UnrealType.h.
References FScriptSetHelper(), FORCEINLINE, and GetElementPtr().
GetElementPtr() [3/4]
FORCEINLINE uint8 * FScriptSetHelper::GetElementPtr (int32 InternalIndex) inline
Returns a uint8 pointer to the element in the set.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the element, or nullptr if the set is empty.
Definition at line 5432 of file UnrealType.h.
References checkf, FORCEINLINE, IsValidIndex(), Num, Set, SetLayout, and TEXT.
Referenced by GetElementPtr(), and GetElementPtr().
GetElementPtr() [4/4]
FORCEINLINE const uint8 * FScriptSetHelper::GetElementPtr (int32 InternalIndex) const inline
Returns a uint8 pointer to the element in the set.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the element, or nullptr if the set is empty.
Definition at line 5451 of file UnrealType.h.
References FScriptSetHelper(), FORCEINLINE, and GetElementPtr().
GetElementPtrWithoutCheck() [1/2]
FORCEINLINE uint8 * FScriptSetHelper::GetElementPtrWithoutCheck (int32 InternalIndex) inline private
Returns a uint8 pointer to the element in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the element, or nullptr if the array is empty.
Definition at line 5887 of file UnrealType.h.
References FORCEINLINE, Set, and SetLayout.
Referenced by ConstructItem(), DestructItems(), FindElementIndex(), FindElementPtr(), FindElementPtrFromHash(), FindNthElementPtr(), FindNthElementPtr(), and GetElementPtrWithoutCheck().
GetElementPtrWithoutCheck() [2/2]
FORCEINLINE const uint8 * FScriptSetHelper::GetElementPtrWithoutCheck (int32 InternalIndex) const inline private
Returns a uint8 pointer to the element in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the array is empty.
Definition at line 5899 of file UnrealType.h.
References FScriptSetHelper(), FORCEINLINE, and GetElementPtrWithoutCheck().
GetMaxIndex()
FORCEINLINE int32 FScriptSetHelper::GetMaxIndex () const inline
Returns the (non-inclusive) maximum index of elements in the set.
Returns
The (non-inclusive) maximum index of elements in the set.
Definition at line 5404 of file UnrealType.h.
References checkSlow, FORCEINLINE, Num, and Set.
Referenced by FindElementIndex(), FindInternalIndex(), and FindLogicalIndex().
IsValidIndex()
FORCEINLINE bool FScriptSetHelper::IsValidIndex (int32 InternalIndex) const inline
Index range check.
Parameters
InternalIndex Index to check
Returns
true if accessing this element is legal.
Definition at line 5371 of file UnrealType.h.
References FORCEINLINE, and Set.
Referenced by ConstructItem(), DestructItems(), FindElementIndex(), FindInternalIndex(), FindLogicalIndex(), GetElementPtr(), and RemoveAt().
MoveAssign()
void FScriptSetHelper::MoveAssign (void * InOtherSet) inline
Move the allocation from another set and make it our own.
Note
The sets MUST be of the same type, and this function will NOT validate that!
Parameters
InOtherSet The set to move the allocation from.
Definition at line 5511 of file UnrealType.h.
References checkSlow, Set, and SetLayout.
Num() [1/2]
FORCEINLINE int32 FScriptSetHelper::Num () const inline
Returns the number of elements in the set.
Returns
The number of elements in the set.
Definition at line 5381 of file UnrealType.h.
References checkSlow, FORCEINLINE, and Set.
Referenced by FPropertyBagSetRef::Num().
Num() [2/2]
FORCEINLINE int32 FScriptSetHelper::Num (const void * Target) inline static
Static version of Num() used when you don't need to bother to construct a FScriptSetHelper.
Returns the number of elements in the set.
Parameters
Target Pointer to the raw memory associated with a FScriptSet
Returns
The number of elements in the set.
Definition at line 5418 of file UnrealType.h.
References checkSlow, FORCEINLINE, and Target.
NumUnchecked()
FORCEINLINE int32 FScriptSetHelper::NumUnchecked () const inline
Returns the number of elements in the set.
Needed to allow reading of the num when the set is 'invalid' during its intrusive unset state.
Returns
The number of elements in the set.
Definition at line 5393 of file UnrealType.h.
References FORCEINLINE, and Set.
Referenced by EmptyElements().
Rehash()
void FScriptSetHelper::Rehash ()
Rehashes the keys in the set.
This function must be called to create a valid set.
RemoveAt()
void FScriptSetHelper::RemoveAt (int32 InternalIndex, int32 Count = 1) inline
Removes an element at the specified index, destroying it.
Parameters
InternalIndex The index of the element to remove.
Definition at line 5578 of file UnrealType.h.
References check, Count, DestructItems(), IsValidIndex(), Set, and SetLayout.
Referenced by FPropertyBagSetRef::Remove(), and RemoveElement().
RemoveElement()
bool FScriptSetHelper::RemoveElement (const void * ElementToRemove) inline
Removes the element from the set.
Definition at line 5781 of file UnrealType.h.
References A, B, ElementProp, FProperty::GetValueTypeHash(), FProperty::Identical, INDEX_NONE, RemoveAt(), Set, and SetLayout.
Friends And Related Symbol Documentation
FSetProperty
friend class FSetProperty friend
Definition at line 5329 of file UnrealType.h.
References FSetProperty.
Referenced by FPropertyBagSetRef::FPropertyBagSetRef(), FScriptSetHelper(), FScriptSetHelper_InContainer::FScriptSetHelper_InContainer(), and FSetProperty.
Field Documentation
ElementProp
FProperty* FScriptSetHelper::ElementProp
Definition at line 5905 of file UnrealType.h.
Referenced by FScriptSetHelper(), FScriptSetHelper(), FScriptSetHelper(), AddElement(), ConstructItem(), CreateHelperFormElementProperty(), DestructItems(), FindElementIndexFromHash(), GetElementProperty(), and RemoveElement().
Set
FScriptSet* FScriptSetHelper::Set
Definition at line 5906 of file UnrealType.h.
Referenced by FScriptSetHelper(), FScriptSetHelper(), AddElement(), AddUninitializedValue(), CreateHelperFormElementProperty(), EmptyElements(), FindElementIndexFromHash(), GetElementPtr(), GetElementPtr(), GetElementPtrWithoutCheck(), GetMaxIndex(), IsValidIndex(), MoveAssign(), Num(), NumUnchecked(), RemoveAt(), and RemoveElement().
SetLayout
FScriptSetLayout FScriptSetHelper::SetLayout
Definition at line 5907 of file UnrealType.h.
Referenced by FScriptSetHelper(), FScriptSetHelper(), FScriptSetHelper(), AddElement(), AddUninitializedValue(), ConstructItem(), CreateHelperFormElementProperty(), DestructItems(), EmptyElements(), FindElementIndexFromHash(), GetElementPtr(), GetElementPtr(), GetElementPtrWithoutCheck(), MoveAssign(), RemoveAt(), and RemoveElement().
The documentation for this class was generated from the following file:
UnrealType.h