Unreal Engine 5.6 C++ API: FReplayHelper Class Reference
FReplayHelper Class Reference
#include "ReplayHelper.h"
Data Structures
struct FCheckpointSaveStateContext
Checkpoint state.
struct FCheckpointStepHelper
struct FExternalDataWrapper
struct FLevelStatus
Helps keeps tabs on what levels are Ready, Have Seen data, Level Name, and Index into the main status list.
struct FNetGuidCacheItem
struct FPendingCheckPointActor
When we save a checkpoint, we remember all of the actors that need a checkpoint saved out by adding them to this list.
Public Member Functions
FReplayHelper ()
FReplayHelper (const FReplayHelper &)=delete
FReplayHelper (FReplayHelper &&)=delete
~FReplayHelper ()
FReplayHelper & operator= (const FReplayHelper &)=delete
FReplayHelper & operator= (FReplayHelper &&)=delete
void Serialize (FArchive &Ar)
Private Types
enum class ECheckpointSaveState {
Idle , ProcessCheckpointActors , SerializeDeletedStartupActors , SerializeDeltaDynamicDestroyed ,
SerializeDeltaClosedChannels , CacheNetGuids , SerializeGuidCache , SerializeNetFieldExportGroupMap ,
SerializeDemoFrameFromQueuedDemoPackets , Finalize
}
enum class EReadPacketMode { Default , SkipData }
enum class EReadPacketState { Success , End , Error }
Private Member Functions
void AddNewLevel (const FString &NewLevelName)
void AddOrUpdateEvent (const FString &Name, const FString &Group, const FString &Meta, const TArray< uint8 > &Data)
void CacheNetGuids (UNetConnection *Connection)
void ClearLevelMap ()
void ClearLevelStreamingState ()
APlayerController * CreateSpectatorController (UNetConnection *Connection)
DECLARE_DELEGATE_OneParam (FOnReplayPlaybackError, const UE::Net::TNetResult< EReplayResult > &)
DECLARE_DELEGATE_OneParam (FOnReplayRecordError, const UE::Net::TNetResult< EReplayResult > &)
FLevelStatus & FindOrAddLevelStatus (const FString &LevelPackageName)
FLevelStatus & FindOrAddLevelStatus (const ULevel &Level)
FLevelStatus & FindOrAddLevelStatus (FString &&LevelPackageName)
float GetCheckpointSaveMaxMSPerFrame () const
Returns either CheckpointSaveMaxMSPerFrame or the value of demo.CheckpointSaveMaxMSPerFrameOverride if it's >= 0.
ECheckpointSaveState GetCheckpointSaveState () const
uint32 GetDemoCurrentTimeInMS () const
uint32 GetLastCheckpointTimeInMS () const
FLevelStatus & GetLevelStatus (const FString &LevelPackageName)
FLevelStatus & GetLevelStatus (const int32 SeenLevelIndex)
FGuid GetPlaybackGuid () const
FReplayCustomVersion::Type GetPlaybackReplayVersion () const
bool HasDeltaCheckpoints () const
bool HasGameSpecificFrameData () const
bool HasLevelStreamingFixes () const
TSharedPtr< INetworkReplayStreamer > Init (const FURL &URL)
void LoadExternalData (FArchive &Ar, const float TimeSeconds)
void NotifyActorDestroyed (UNetConnection *Connection, AActor *Actor)
void NotifyReplayError (UE::Net::TNetResult< EReplayResult > &&Result)
void OnLevelAddedToWorld (ULevel *Level, UWorld *World)
void OnLevelRemovedFromWorld (ULevel *Level, UWorld *World)
void OnSeamlessTravelStart (UWorld *InWorld, const FString &LevelName, UNetConnection *Connection)
void OnStartRecordingComplete (const FStartStreamingResult &Result)
void ProcessCheckpointActors (UNetConnection *Connection, TArrayView< FPendingCheckPointActor > PendingActors, int32 &NextIndex, FRepActorsCheckpointParams &Params)
void ReadDeletedStartupActors (UNetConnection *Connection, FArchive &Ar, TSet< FString > &DeletedStartupActors)
bool ReadDemoFrame (UNetConnection *Connection, FArchive &Ar, TArray< FPlaybackPacket > &InPlaybackPackets, const bool bForLevelFastForward, const FArchivePos MaxArchiveReadPos, float *OutTime)
bool ReadPlaybackDemoHeader (FString &Error)
void RecordFrame (float DeltaSeconds, UNetConnection *Connection)
void RemoveActorFromCheckpoint (UNetConnection *Connection, AActor *Actor)
bool ReplicateActor (AActor *Actor, UNetConnection *Connection, bool bMustReplicate)
bool ReplicateCheckpointActor (AActor *ToReplicate, UNetConnection *Connection, class FRepActorsCheckpointParams &Params)
Replicates the given prioritized actors, so their packets can be captured for recording.
void RequestCheckpoint ()
void ResetDeltaCheckpointTracking (UNetConnection *Connection)
void ResetLevelMap ()
void ResetLevelStatuses ()
void ResetState ()
void SaveCheckpoint (UNetConnection *Connection)
void SaveExternalData (UNetConnection *Connection, FArchive &Ar)
bool SerializeDeletedStartupActors (UNetConnection *Connection, const FRepActorsCheckpointParams &Params, FArchive *CheckpointArchive)
bool SerializeDeltaClosedChannels (UNetConnection *Connection, const FRepActorsCheckpointParams &Params, FArchive *CheckpointArchive)
bool SerializeDeltaDynamicDestroyed (UNetConnection *Connection, const FRepActorsCheckpointParams &Params, FArchive *CheckpointArchive)
bool SerializeGuidCache (UNetConnection *Connection, const FRepActorsCheckpointParams &Params, FArchive *CheckpointArchive)
void SetAnalyticsProvider (TSharedPtr< IAnalyticsProvider > InProvider)
bool SetExternalDataForObject (UNetConnection *Connection, UObject *OwningObject, const uint8 *Src, const int32 NumBits)
void SetPlaybackNetworkVersions (FArchive &Ar)
void SetPlaybackNetworkVersions (UNetConnection *Connection)
bool ShouldSaveCheckpoint () const
void StartRecording (UNetConnection *Connection)
void StopReplay ()
void TickCheckpoint (UNetConnection *Connection)
void TickRecording (float DeltaSeconds, UNetConnection *Connection)
void WriteDemoFrame (UNetConnection *Connection, FArchive &Ar, TArray< FQueuedDemoPacket > &QueuedPackets, float FrameTime, EWriteDemoFrameFlags Flags)
void WriteNetworkDemoHeader (UNetConnection *Connection)
Static Private Member Functions
static void FlushNetChecked (UNetConnection &NetConnection)
static float GetClampedDeltaSeconds (UWorld *World, const float DeltaSeconds)
static FString GetLevelPackageName (const ULevel &InLevel)
static const EReadPacketState ReadPacket (FArchive &Archive, TArray< uint8 > &OutBuffer, const EReadPacketMode Mode)
Reads a formatted Demo Packet from the given archive (which is expected to be in Demo Frame format).
static void WritePacket (FArchive &Ar, uint8 *Data, int32 Count)
Private Attributes
FString ActiveReplayName
TArray< FLevelStatus > AllLevelStatuses
TSharedPtr< IAnalyticsProvider > AnalyticsProvider
bool bHasDeltaCheckpoints
bool bHasGameSpecificFrameData
bool bHasLevelStreamingFixes
bool bIsLoadingCheckpoint
bool bIsWaitingForStream
bool bPauseRecording
bool bPendingCheckpointRequest
bool bRecording
bool bRecordMapChanges
bool bWasStartRecordingSuccessful
FCheckpointSaveStateContext CheckpointSaveContext
float CheckpointSaveMaxMSPerFrame
int32 CurrentLevelIndex
Index of LevelNames that is currently loaded.
float DemoCurrentTime
Current record/playback position in seconds.
int32 DemoFrameNum
Current record/playback frame number.
float DemoTotalTime
Total time of demo in seconds.
FURL DemoURL
TMap< TWeakObjectPtr< UObject >, FExternalDataWrapper, FDefaultSetAllocator, TWeakObjectPtrMapKeyFuncs< TWeakObjectPtr< UObject >, FExternalDataWrapper > > ExternalDataMap
TMap< FNetworkGUID, FReplayExternalDataArray > ExternalDataToObjectMap
ExternalDataToObjectMap is used to map a FNetworkGUID to the proper FReplayExternalDataArray.
double LastCheckpointTime
float LatestReadFrameTime
TArray< FLevelNameAndTime > LevelNamesAndTimes
TSet< class ULevel * > LevelsPendingFastForward
TMap< FString, int32 > LevelStatusesByName
TMap< const ULevel *, int32 > LevelStatusIndexByLevel
TSet< TWeakObjectPtr< UObject > > NewStreamingLevelsThisFrame
During recording, streaming levels waiting to be saved next frame.
uint32 NumLevelsAddedThisFrame
TMap< TWeakObjectPtr< UObject >, FNetworkGUID, FDefaultSetAllocator, TWeakObjectPtrMapKeyFuncs< TWeakObjectPtr< UObject >, FNetworkGUID > > ObjectsWithExternalDataMap
FOnReplayPlaybackError OnReplayPlaybackError
FOnReplayRecordError OnReplayRecordError
TSet< FString > PlaybackDeletedNetStartupActors
Net startup actors that need to be destroyed after checkpoints are loaded.
TArray< TUniquePtr< FDeltaCheckpointData > > PlaybackDeltaCheckpointData
FNetworkDemoHeader PlaybackDemoHeader
TMap< float, TMap< FString, TArray< uint8 > > > PlaybackFrames
PlaybackFrames are used to buffer per frame data up when we read a demo frame, which we can then process when the time is right.
TArray< FQueuedDemoPacket > QueuedCheckpointPackets
TArray< FQueuedDemoPacket > QueuedDemoPackets
TArray< FString > RecordingDeletedNetStartupActors
Net startup actors that need to be destroyed after checkpoints are loaded.
FDeltaCheckpointData RecordingDeltaCheckpointData
TSharedPtr< INetworkReplayStreamer > ReplayStreamer
UE::Net::FNetResultManager ResultManager
TArray< int32 > SeenLevelStatuses
TSet< TWeakObjectPtr< UObject > > UniqueStreamingLevels
During recording, all unique streaming levels since recording started.
TMap< FName, TWeakObjectPtr< ULevel > > WeakLevelsByName
TWeakObjectPtr< UWorld > World
Static Private Attributes
static constexpr int32 MAX_DEMO_READ_WRITE_BUFFER = 1024 * 2
static constexpr int32 MAX_DEMO_STRING_SERIALIZATION_SIZE = 16 * 1024 * 1024
Friends
class FReplayResultHandler
class UDemoNetConnection
class UDemoNetDriver
class UReplayNetConnection
Detailed Description
Definition at line 32 of file ReplayHelper.h.
Member Enumeration Documentation
ECheckpointSaveState
enum class FReplayHelper::ECheckpointSaveState strong private
Enumerator
Idle
ProcessCheckpointActors
SerializeDeletedStartupActors
SerializeDeltaDynamicDestroyed
SerializeDeltaClosedChannels
CacheNetGuids
SerializeGuidCache
SerializeNetFieldExportGroupMap
SerializeDemoFrameFromQueuedDemoPackets
Finalize
Definition at line 259 of file ReplayHelper.h.
EReadPacketMode
enum class FReplayHelper::EReadPacketMode strong private
Enumerator
Default
SkipData
Definition at line 148 of file ReplayHelper.h.
EReadPacketState
enum class FReplayHelper::EReadPacketState strong private
Enumerator
Success
End
Error
Definition at line 141 of file ReplayHelper.h.
Constructor & Destructor Documentation
FReplayHelper() [1/3]
FReplayHelper::FReplayHelper ()
Referenced by FReplayHelper(), FReplayHelper(), operator=(), and operator=().
~FReplayHelper()
FReplayHelper::~FReplayHelper ()
FReplayHelper() [2/3]
FReplayHelper::FReplayHelper (FReplayHelper &&) delete
References FReplayHelper().
FReplayHelper() [3/3]
FReplayHelper::FReplayHelper (const FReplayHelper &) delete
References FReplayHelper().
Member Function Documentation
AddNewLevel()
void FReplayHelper::AddNewLevel (const FString & NewLevelName) private
AddOrUpdateEvent()
void FReplayHelper::AddOrUpdateEvent (const FString & Name, const FString & Group, const FString & Meta, const TArray< uint8 > & Data) private
References Group, Meta, and Name.
CacheNetGuids()
void FReplayHelper::CacheNetGuids (UNetConnection * Connection) private
ClearLevelMap()
void FReplayHelper::ClearLevelMap () private
ClearLevelStreamingState()
void FReplayHelper::ClearLevelStreamingState () inline private
Definition at line 485 of file ReplayHelper.h.
References AllLevelStatuses, LevelsPendingFastForward, LevelStatusesByName, LevelStatusIndexByLevel, NumLevelsAddedThisFrame, and SeenLevelStatuses.
CreateSpectatorController()
APlayerController * FReplayHelper::CreateSpectatorController (UNetConnection * Connection) private
DECLARE_DELEGATE_OneParam() [1/2]
FReplayHelper::DECLARE_DELEGATE_OneParam (FOnReplayPlaybackError , const UE::Net::TNetResult< EReplayResult > &) private
DECLARE_DELEGATE_OneParam() [2/2]
FReplayHelper::DECLARE_DELEGATE_OneParam (FOnReplayRecordError , const UE::Net::TNetResult< EReplayResult > &) private
FindOrAddLevelStatus() [1/3]
FLevelStatus & FReplayHelper::FindOrAddLevelStatus (const FString & LevelPackageName) inline private
Definition at line 511 of file ReplayHelper.h.
References FindOrAddLevelStatus().
FindOrAddLevelStatus() [2/3]
FLevelStatus & FReplayHelper::FindOrAddLevelStatus (const ULevel & Level) inline private
Definition at line 495 of file ReplayHelper.h.
References AllLevelStatuses, FindOrAddLevelStatus(), GetLevelPackageName(), FReplayHelper::FLevelStatus::LevelIndex, and LevelStatusIndexByLevel.
Referenced by FindOrAddLevelStatus(), and FindOrAddLevelStatus().
FindOrAddLevelStatus() [3/3]
FLevelStatus & FReplayHelper::FindOrAddLevelStatus (FString && LevelPackageName) inline private
Definition at line 516 of file ReplayHelper.h.
References AllLevelStatuses, LevelStatusesByName, MoveTemp(), and NumLevelsAddedThisFrame.
FlushNetChecked()
void FReplayHelper::FlushNetChecked (UNetConnection & NetConnection) static private
GetCheckpointSaveMaxMSPerFrame()
float FReplayHelper::GetCheckpointSaveMaxMSPerFrame () const private
Returns either CheckpointSaveMaxMSPerFrame or the value of demo.CheckpointSaveMaxMSPerFrameOverride if it's >= 0.
GetCheckpointSaveState()
ECheckpointSaveState FReplayHelper::GetCheckpointSaveState () const inline private
Definition at line 558 of file ReplayHelper.h.
References CheckpointSaveContext.
GetClampedDeltaSeconds()
float FReplayHelper::GetClampedDeltaSeconds (UWorld * World, const float DeltaSeconds) static private
References World.
GetDemoCurrentTimeInMS()
uint32 FReplayHelper::GetDemoCurrentTimeInMS () const inline private
Definition at line 115 of file ReplayHelper.h.
References DemoCurrentTime.
GetLastCheckpointTimeInMS()
uint32 FReplayHelper::GetLastCheckpointTimeInMS () const inline private
Definition at line 116 of file ReplayHelper.h.
References LastCheckpointTime.
GetLevelPackageName()
FString FReplayHelper::GetLevelPackageName (const ULevel & InLevel) static private
Referenced by FindOrAddLevelStatus().
GetLevelStatus() [1/2]
FLevelStatus & FReplayHelper::GetLevelStatus (const FString & LevelPackageName) inline private
Definition at line 537 of file ReplayHelper.h.
References AllLevelStatuses, and LevelStatusesByName.
GetLevelStatus() [2/2]
FLevelStatus & FReplayHelper::GetLevelStatus (const int32 SeenLevelIndex) inline private
Definition at line 532 of file ReplayHelper.h.
References AllLevelStatuses, and SeenLevelStatuses.
GetPlaybackGuid()
FGuid FReplayHelper::GetPlaybackGuid () const inline private
Definition at line 91 of file ReplayHelper.h.
References PlaybackDemoHeader.
GetPlaybackReplayVersion()
FReplayCustomVersion::Type FReplayHelper::GetPlaybackReplayVersion () const private
HasDeltaCheckpoints()
bool FReplayHelper::HasDeltaCheckpoints () const inline private
Definition at line 81 of file ReplayHelper.h.
References bHasDeltaCheckpoints.
HasGameSpecificFrameData()
bool FReplayHelper::HasGameSpecificFrameData () const inline private
Definition at line 86 of file ReplayHelper.h.
References bHasGameSpecificFrameData.
HasLevelStreamingFixes()
bool FReplayHelper::HasLevelStreamingFixes () const inline private
Definition at line 76 of file ReplayHelper.h.
References bHasLevelStreamingFixes.
Init()
TSharedPtr< INetworkReplayStreamer > FReplayHelper::Init (const FURL & URL) private
LoadExternalData()
void FReplayHelper::LoadExternalData (FArchive & Ar, const float TimeSeconds) private
References Ar.
NotifyActorDestroyed()
void FReplayHelper::NotifyActorDestroyed (UNetConnection * Connection, AActor * Actor) private
References Actor.
NotifyReplayError()
void FReplayHelper::NotifyReplayError (UE::Net::TNetResult< EReplayResult > && Result) private
OnLevelAddedToWorld()
void FReplayHelper::OnLevelAddedToWorld (ULevel * Level, UWorld * World) private
References World.
OnLevelRemovedFromWorld()
void FReplayHelper::OnLevelRemovedFromWorld (ULevel * Level, UWorld * World) private
References World.
OnSeamlessTravelStart()
void FReplayHelper::OnSeamlessTravelStart (UWorld * InWorld, const FString & LevelName, UNetConnection * Connection) private
OnStartRecordingComplete()
void FReplayHelper::OnStartRecordingComplete (const FStartStreamingResult & Result) private
operator=() [1/2]
FReplayHelper & FReplayHelper::operator= (const FReplayHelper &) delete
References FReplayHelper().
operator=() [2/2]
FReplayHelper & FReplayHelper::operator= (FReplayHelper &&) delete
References FReplayHelper().
ProcessCheckpointActors()
void FReplayHelper::ProcessCheckpointActors (UNetConnection * Connection, TArrayView< FPendingCheckPointActor > PendingActors, int32 & NextIndex, FRepActorsCheckpointParams & Params) private
References Params.
ReadDeletedStartupActors()
void FReplayHelper::ReadDeletedStartupActors (UNetConnection * Connection, FArchive & Ar, TSet< FString > & DeletedStartupActors) private
References Ar.
ReadDemoFrame()
bool FReplayHelper::ReadDemoFrame (UNetConnection * Connection, FArchive & Ar, TArray< FPlaybackPacket > & InPlaybackPackets, const bool bForLevelFastForward, const FArchivePos MaxArchiveReadPos, float * OutTime) private
References Ar.
ReadPacket()
const EReadPacketState FReplayHelper::ReadPacket (FArchive & Archive, TArray< uint8 > & OutBuffer, const EReadPacketMode Mode) static private
Reads a formatted Demo Packet from the given archive (which is expected to be in Demo Frame format).
Parameters
Archive The archive from which to read.
OutBuffer Data used to store the read packet data. Note, this will stomp on existing memory instead of appending.
MaxBufferSize Largest expected packet buffer size. Used to detect corruption.
Mode How to handle packet data
Returns
EReadPacketState
ReadPlaybackDemoHeader()
bool FReplayHelper::ReadPlaybackDemoHeader (FString & Error) private
References Error.
RecordFrame()
void FReplayHelper::RecordFrame (float DeltaSeconds, UNetConnection * Connection) private
RemoveActorFromCheckpoint()
void FReplayHelper::RemoveActorFromCheckpoint (UNetConnection * Connection, AActor * Actor) private
References Actor.
ReplicateActor()
bool FReplayHelper::ReplicateActor (AActor * Actor, UNetConnection * Connection, bool bMustReplicate) private
References Actor.
ReplicateCheckpointActor()
bool FReplayHelper::ReplicateCheckpointActor (AActor * ToReplicate, UNetConnection * Connection, class FRepActorsCheckpointParams & Params) private
Replicates the given prioritized actors, so their packets can be captured for recording.
This should be used for normal frame recording.
See also
ReplicateCheckpointActor for recording during checkpoints.
Parameters
ToReplicate The actors to replicate.
RepStartTime The start time for replication.
Returns
True if there is time remaining to replicate more Actors, False otherwise.
References Params.
RequestCheckpoint()
void FReplayHelper::RequestCheckpoint () private
ResetDeltaCheckpointTracking()
void FReplayHelper::ResetDeltaCheckpointTracking (UNetConnection * Connection) private
ResetLevelMap()
void FReplayHelper::ResetLevelMap () private
ResetLevelStatuses()
void FReplayHelper::ResetLevelStatuses () private
ResetState()
void FReplayHelper::ResetState () private
SaveCheckpoint()
void FReplayHelper::SaveCheckpoint (UNetConnection * Connection) private
SaveExternalData()
void FReplayHelper::SaveExternalData (UNetConnection * Connection, FArchive & Ar) private
References Ar.
Serialize()
void FReplayHelper::Serialize (FArchive & Ar)
References Ar.
SerializeDeletedStartupActors()
bool FReplayHelper::SerializeDeletedStartupActors (UNetConnection * Connection, const FRepActorsCheckpointParams & Params, FArchive * CheckpointArchive) private
References Params.
SerializeDeltaClosedChannels()
bool FReplayHelper::SerializeDeltaClosedChannels (UNetConnection * Connection, const FRepActorsCheckpointParams & Params, FArchive * CheckpointArchive) private
References Params.
SerializeDeltaDynamicDestroyed()
bool FReplayHelper::SerializeDeltaDynamicDestroyed (UNetConnection * Connection, const FRepActorsCheckpointParams & Params, FArchive * CheckpointArchive) private
References Params.
SerializeGuidCache()
bool FReplayHelper::SerializeGuidCache (UNetConnection * Connection, const FRepActorsCheckpointParams & Params, FArchive * CheckpointArchive) private
References Params.
SetAnalyticsProvider()
void FReplayHelper::SetAnalyticsProvider (TSharedPtr< IAnalyticsProvider > InProvider) private
SetExternalDataForObject()
bool FReplayHelper::SetExternalDataForObject (UNetConnection * Connection, UObject * OwningObject, const uint8 * Src, const int32 NumBits) private
SetPlaybackNetworkVersions() [1/2]
void FReplayHelper::SetPlaybackNetworkVersions (FArchive & Ar) private
References Ar.
SetPlaybackNetworkVersions() [2/2]
void FReplayHelper::SetPlaybackNetworkVersions (UNetConnection * Connection) private
ShouldSaveCheckpoint()
bool FReplayHelper::ShouldSaveCheckpoint () const private
StartRecording()
void FReplayHelper::StartRecording (UNetConnection * Connection) private
StopReplay()
void FReplayHelper::StopReplay () private
TickCheckpoint()
void FReplayHelper::TickCheckpoint (UNetConnection * Connection) private
TickRecording()
void FReplayHelper::TickRecording (float DeltaSeconds, UNetConnection * Connection) private
WriteDemoFrame()
void FReplayHelper::WriteDemoFrame (UNetConnection * Connection, FArchive & Ar, TArray< FQueuedDemoPacket > & QueuedPackets, float FrameTime, EWriteDemoFrameFlags Flags) private
References Ar, and Flags.
WriteNetworkDemoHeader()
void FReplayHelper::WriteNetworkDemoHeader (UNetConnection * Connection) private
WritePacket()
void FReplayHelper::WritePacket (FArchive & Ar, uint8 * Data, int32 Count) static private
References Ar, and Count.
Friends And Related Symbol Documentation
FReplayResultHandler
friend class FReplayResultHandler friend
Definition at line 37 of file ReplayHelper.h.
References FReplayResultHandler.
Referenced by FReplayResultHandler.
UDemoNetConnection
friend class UDemoNetConnection friend
Definition at line 35 of file ReplayHelper.h.
References UDemoNetConnection.
Referenced by UDemoNetConnection.
UDemoNetDriver
friend class UDemoNetDriver friend
Definition at line 34 of file ReplayHelper.h.
References UDemoNetDriver.
Referenced by UDemoNetDriver.
UReplayNetConnection
friend class UReplayNetConnection friend
Definition at line 36 of file ReplayHelper.h.
References UReplayNetConnection.
Referenced by UReplayNetConnection.
Field Documentation
ActiveReplayName
FString FReplayHelper::ActiveReplayName private
Definition at line 209 of file ReplayHelper.h.
AllLevelStatuses
TArray<FLevelStatus> FReplayHelper::AllLevelStatuses private
Definition at line 449 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState(), FindOrAddLevelStatus(), FindOrAddLevelStatus(), GetLevelStatus(), and GetLevelStatus().
AnalyticsProvider
TSharedPtr<IAnalyticsProvider> FReplayHelper::AnalyticsProvider private
Definition at line 554 of file ReplayHelper.h.
bHasDeltaCheckpoints
bool FReplayHelper::bHasDeltaCheckpoints private
Definition at line 244 of file ReplayHelper.h.
Referenced by HasDeltaCheckpoints().
bHasGameSpecificFrameData
bool FReplayHelper::bHasGameSpecificFrameData private
Definition at line 247 of file ReplayHelper.h.
Referenced by HasGameSpecificFrameData().
bHasLevelStreamingFixes
bool FReplayHelper::bHasLevelStreamingFixes private
Definition at line 241 of file ReplayHelper.h.
Referenced by HasLevelStreamingFixes().
bIsLoadingCheckpoint
bool FReplayHelper::bIsLoadingCheckpoint private
Definition at line 238 of file ReplayHelper.h.
bIsWaitingForStream
bool FReplayHelper::bIsWaitingForStream private
Definition at line 237 of file ReplayHelper.h.
bPauseRecording
bool FReplayHelper::bPauseRecording private
Definition at line 250 of file ReplayHelper.h.
bPendingCheckpointRequest
bool FReplayHelper::bPendingCheckpointRequest private
Definition at line 478 of file ReplayHelper.h.
bRecording
bool FReplayHelper::bRecording private
Definition at line 564 of file ReplayHelper.h.
bRecordMapChanges
bool FReplayHelper::bRecordMapChanges private
Definition at line 252 of file ReplayHelper.h.
bWasStartRecordingSuccessful
bool FReplayHelper::bWasStartRecordingSuccessful private
Definition at line 236 of file ReplayHelper.h.
CheckpointSaveContext
FCheckpointSaveStateContext FReplayHelper::CheckpointSaveContext private
Definition at line 384 of file ReplayHelper.h.
Referenced by GetCheckpointSaveState().
CheckpointSaveMaxMSPerFrame
float FReplayHelper::CheckpointSaveMaxMSPerFrame private
Definition at line 254 of file ReplayHelper.h.
CurrentLevelIndex
int32 FReplayHelper::CurrentLevelIndex private
Index of LevelNames that is currently loaded.
Definition at line 219 of file ReplayHelper.h.
DemoCurrentTime
float FReplayHelper::DemoCurrentTime private
Current record/playback position in seconds.
Definition at line 225 of file ReplayHelper.h.
Referenced by GetDemoCurrentTimeInMS().
DemoFrameNum
int32 FReplayHelper::DemoFrameNum private
Current record/playback frame number.
Definition at line 222 of file ReplayHelper.h.
DemoTotalTime
float FReplayHelper::DemoTotalTime private
Total time of demo in seconds.
Definition at line 228 of file ReplayHelper.h.
DemoURL
FURL FReplayHelper::DemoURL private
Definition at line 207 of file ReplayHelper.h.
ExternalDataMap
TMap<TWeakObjectPtr<UObject>, FExternalDataWrapper, FDefaultSetAllocator, TWeakObjectPtrMapKeyFuncs<TWeakObjectPtr<UObject>, FExternalDataWrapper> > FReplayHelper::ExternalDataMap private
Definition at line 197 of file ReplayHelper.h.
ExternalDataToObjectMap
TMap<FNetworkGUID, FReplayExternalDataArray> FReplayHelper::ExternalDataToObjectMap private
ExternalDataToObjectMap is used to map a FNetworkGUID to the proper FReplayExternalDataArray.
Definition at line 543 of file ReplayHelper.h.
LastCheckpointTime
double FReplayHelper::LastCheckpointTime private
Definition at line 231 of file ReplayHelper.h.
Referenced by GetLastCheckpointTimeInMS().
LatestReadFrameTime
float FReplayHelper::LatestReadFrameTime private
Definition at line 234 of file ReplayHelper.h.
LevelNamesAndTimes
TArray<FLevelNameAndTime> FReplayHelper::LevelNamesAndTimes private
Definition at line 216 of file ReplayHelper.h.
LevelsPendingFastForward
TSet<class ULevel*> FReplayHelper::LevelsPendingFastForward private
Definition at line 476 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState().
LevelStatusesByName
TMap<FString, int32> FReplayHelper::LevelStatusesByName private
Definition at line 456 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState(), FindOrAddLevelStatus(), and GetLevelStatus().
LevelStatusIndexByLevel
TMap<const ULevel*, int32> FReplayHelper::LevelStatusIndexByLevel private
Definition at line 459 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState(), and FindOrAddLevelStatus().
MAX_DEMO_READ_WRITE_BUFFER
int32 FReplayHelper::MAX_DEMO_READ_WRITE_BUFFER = 1024 * 2 static constexpr private
Definition at line 566 of file ReplayHelper.h.
MAX_DEMO_STRING_SERIALIZATION_SIZE
int32 FReplayHelper::MAX_DEMO_STRING_SERIALIZATION_SIZE = 16 * 1024 * 1024 static constexpr private
Definition at line 567 of file ReplayHelper.h.
NewStreamingLevelsThisFrame
TSet<TWeakObjectPtr<UObject> > FReplayHelper::NewStreamingLevelsThisFrame private
During recording, streaming levels waiting to be saved next frame.
During playback, streaming levels that have recently become visible.
Definition at line 400 of file ReplayHelper.h.
NumLevelsAddedThisFrame
uint32 FReplayHelper::NumLevelsAddedThisFrame private
Definition at line 472 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState(), and FindOrAddLevelStatus().
ObjectsWithExternalDataMap
TMap<TWeakObjectPtr<UObject>, FNetworkGUID, FDefaultSetAllocator, TWeakObjectPtrMapKeyFuncs<TWeakObjectPtr<UObject>, FNetworkGUID> > FReplayHelper::ObjectsWithExternalDataMap private
Definition at line 188 of file ReplayHelper.h.
OnReplayPlaybackError
FOnReplayPlaybackError FReplayHelper::OnReplayPlaybackError private
Definition at line 111 of file ReplayHelper.h.
OnReplayRecordError
FOnReplayRecordError FReplayHelper::OnReplayRecordError private
Definition at line 108 of file ReplayHelper.h.
PlaybackDeletedNetStartupActors
TSet<FString> FReplayHelper::PlaybackDeletedNetStartupActors private
Net startup actors that need to be destroyed after checkpoints are loaded.
Definition at line 552 of file ReplayHelper.h.
PlaybackDeltaCheckpointData
TArray<TUniquePtr<FDeltaCheckpointData> > FReplayHelper::PlaybackDeltaCheckpointData private
Definition at line 388 of file ReplayHelper.h.
PlaybackDemoHeader
FNetworkDemoHeader FReplayHelper::PlaybackDemoHeader private
Definition at line 257 of file ReplayHelper.h.
Referenced by GetPlaybackGuid().
PlaybackFrames
TMap<float, TMap<FString, TArray<uint8> > > FReplayHelper::PlaybackFrames private
PlaybackFrames are used to buffer per frame data up when we read a demo frame, which we can then process when the time is right.
Definition at line 546 of file ReplayHelper.h.
QueuedCheckpointPackets
TArray<FQueuedDemoPacket> FReplayHelper::QueuedCheckpointPackets private
Definition at line 403 of file ReplayHelper.h.
QueuedDemoPackets
TArray<FQueuedDemoPacket> FReplayHelper::QueuedDemoPackets private
Definition at line 402 of file ReplayHelper.h.
RecordingDeletedNetStartupActors
TArray<FString> FReplayHelper::RecordingDeletedNetStartupActors private
Net startup actors that need to be destroyed after checkpoints are loaded.
Definition at line 549 of file ReplayHelper.h.
RecordingDeltaCheckpointData
FDeltaCheckpointData FReplayHelper::RecordingDeltaCheckpointData private
Definition at line 386 of file ReplayHelper.h.
ReplayStreamer
TSharedPtr<INetworkReplayStreamer> FReplayHelper::ReplayStreamer private
Definition at line 211 of file ReplayHelper.h.
ResultManager
UE::Net::FNetResultManager FReplayHelper::ResultManager private
Definition at line 480 of file ReplayHelper.h.
SeenLevelStatuses
TArray<int32> FReplayHelper::SeenLevelStatuses private
Definition at line 469 of file ReplayHelper.h.
Referenced by ClearLevelStreamingState(), and GetLevelStatus().
UniqueStreamingLevels
TSet<TWeakObjectPtr<UObject> > FReplayHelper::UniqueStreamingLevels private
During recording, all unique streaming levels since recording started.
During playback, all streaming level instances we've created.
Definition at line 394 of file ReplayHelper.h.
WeakLevelsByName
TMap<FName, TWeakObjectPtr<ULevel> > FReplayHelper::WeakLevelsByName private
Definition at line 463 of file ReplayHelper.h.
World
TWeakObjectPtr<UWorld> FReplayHelper::World private
Definition at line 213 of file ReplayHelper.h.
Referenced by GetClampedDeltaSeconds(), OnLevelAddedToWorld(), and OnLevelRemovedFromWorld().
The documentation for this class was generated from the following file:
ReplayHelper.h