Unreal Engine 5.6 C++ API: ActorComponent.h File Reference
ActorComponent.h File Reference
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/Object.h"
#include "Templates/SubclassOf.h"
#include "Engine/EngineTypes.h"
#include "Engine/EngineBaseTypes.h"
#include "UObject/CoreNetTypes.h"
#include "UObject/ScriptMacros.h"
#include "Interfaces/Interface_AssetUserData.h"
#include "UObject/StructOnScope.h"
#include "PhysicsInterfaceDeclaresCore.h"
#include "PropertyPairsMap.h"
#include "ComponentInstanceDataCache.h"
#include "Experimental/ConcurrentLinearAllocator.h"
#include "Misc/ScopeRWLock.h"
#include "Misc/Timeout.h"
#include "Misc/TransactionallySafeRWLock.h"
#include "Physics/Experimental/AsyncPhysicsStateProcessorInterface.h"
#include "ActorComponent.generated.h"
Data Structures
class FRegisterComponentContext
class UActorComponent
Enumerations
enum class EUpdateTransformFlags : int32 { None = 0x0 , SkipPhysicsUpdate = 0x1 , PropagateFromParent = 0x2 , OnlyUpdateIfUsingSocket = 0x4 }
Information about how to update transform when something is moved.
Functions
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorComponentDeactivateSignature, UActorComponent, OnComponentDeactivated, UActorComponent *, Component)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorComponentActivatedSignature, UActorComponent, OnComponentActivated, UActorComponent *, Component, bool, bReset)
DECLARE_MULTICAST_DELEGATE_OneParam (FActorComponentGlobalCreatePhysicsSignature, UActorComponent *)
DECLARE_MULTICAST_DELEGATE_OneParam (FActorComponentGlobalDestroyPhysicsSignature, UActorComponent *)
constexpr bool operator! (EUpdateTransformFlags Value)
constexpr EUpdateTransformFlags operator& (EUpdateTransformFlags Left, EUpdateTransformFlags Right)
constexpr EUpdateTransformFlags operator| (EUpdateTransformFlags Left, EUpdateTransformFlags Right)
constexpr EUpdateTransformFlags operator~ (EUpdateTransformFlags Value)
FORCEINLINE EUpdateTransformFlags SkipPhysicsToEnum (bool bSkipPhysics)
Converts legacy bool into the SkipPhysicsUpdate bitflag.
UCLASS ()
ActorComponent is the base class for components that define reusable behavior that can be added to different types of Actors.
void UpdateAllPrimitiveSceneInfosForScenes (TSet< FSceneInterface * > ScenesToUpdateAllPrimitiveSceneInfos)
void UpdateAllPrimitiveSceneInfosForSingleComponent (UActorComponent *InComponent, TSet< FSceneInterface * > *InScenesToUpdateAllPrimitiveSceneInfosForBatching=nullptr)
void UpdateAllPrimitiveSceneInfosForSingleComponentInterface (IPrimitiveComponent *InComponent, TSet< FSceneInterface * > *InScenesToUpdateAllPrimitiveSceneInfosForBatching=nullptr)
Variables
config =Engine
int32 GEnableDeferredPhysicsCreation
TFunction< bool(const UActorComponent *)> GIsComponentSelectedInEditor
Callback for editor component selection.
Enumeration Type Documentation
EUpdateTransformFlags
enum class EUpdateTransformFlags : int32 strong
Information about how to update transform when something is moved.
Enumerator
None
Default options.
SkipPhysicsUpdate
Don't update the underlying physics.
PropagateFromParent
The update is coming as a result of the parent updating (i.e.
not called directly)
OnlyUpdateIfUsingSocket
Only update child transform if attached to parent via a socket.
Definition at line 88 of file ActorComponent.h.
Function Documentation
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FActorComponentDeactivateSignature , UActorComponent , OnComponentDeactivated , UActorComponent * , Component)
References Component.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_TwoParams (FActorComponentActivatedSignature , UActorComponent , OnComponentActivated , UActorComponent * , Component , bool , bReset)
References Component.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FActorComponentGlobalCreatePhysicsSignature , UActorComponent *)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FActorComponentGlobalDestroyPhysicsSignature , UActorComponent *)
operator!()
bool operator! (EUpdateTransformFlags Value) inline constexpr
Definition at line 110 of file ActorComponent.h.
References None, and Value.
operator&()
EUpdateTransformFlags operator& (EUpdateTransformFlags Left, EUpdateTransformFlags Right) inline constexpr
Definition at line 105 of file ActorComponent.h.
References Left, and Right.
operator|()
EUpdateTransformFlags operator| (EUpdateTransformFlags Left, EUpdateTransformFlags Right) inline constexpr
Definition at line 100 of file ActorComponent.h.
References Left, and Right.
operator~()
EUpdateTransformFlags operator~ (EUpdateTransformFlags Value) inline constexpr
Definition at line 115 of file ActorComponent.h.
References Value.
SkipPhysicsToEnum()
FORCEINLINE EUpdateTransformFlags SkipPhysicsToEnum (bool bSkipPhysics)
Converts legacy bool into the SkipPhysicsUpdate bitflag.
Definition at line 121 of file ActorComponent.h.
References FORCEINLINE, None, and SkipPhysicsUpdate.
UCLASS()
UCLASS ()
ActorComponent is the base class for components that define reusable behavior that can be added to different types of Actors.
ActorComponents that have a transform are known as SceneComponents and those that can be rendered are PrimitiveComponents.
See also
ActorComponent
USceneComponent
UPrimitiveComponent
UpdateAllPrimitiveSceneInfosForScenes()
void UpdateAllPrimitiveSceneInfosForScenes (TSet< FSceneInterface * > ScenesToUpdateAllPrimitiveSceneInfos) extern
Referenced by TComponentReregisterContext< ComponentType >::UpdateAllPrimitiveSceneInfos().
UpdateAllPrimitiveSceneInfosForSingleComponent()
void UpdateAllPrimitiveSceneInfosForSingleComponent (UActorComponent * InComponent, TSet< FSceneInterface * > * InScenesToUpdateAllPrimitiveSceneInfosForBatching = nullptr) extern
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
UpdateAllPrimitiveSceneInfosForSingleComponentInterface()
void UpdateAllPrimitiveSceneInfosForSingleComponentInterface (IPrimitiveComponent * InComponent, TSet< FSceneInterface * > * InScenesToUpdateAllPrimitiveSceneInfosForBatching = nullptr) extern
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
Variable Documentation
config
config =Engine
Definition at line 144 of file ActorComponent.h.
GEnableDeferredPhysicsCreation
int32 GEnableDeferredPhysicsCreation extern
GIsComponentSelectedInEditor
TFunction<bool(const UActorComponent*)> GIsComponentSelectedInEditor extern
Callback for editor component selection.
This must be in engine instead of editor for UActorComponent::IsSelectedInEditor to work