Unreal Engine 5.6 C++ API: FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType > Struct Template Reference
FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType > Struct Template Reference
Static Public Member Functions
static uint32 GetKeyHash (const FAssetRegistryExportPath &Key)
static uint32 GetKeyHash (const FMarshalledText &Key)
static uint32 GetKeyHash (const FNumberlessExportPath &Key)
static uint32 GetKeyHash (const FString &Key)
static uint32 GetKeyHash (const FUtf8String &Key)
static uint32 GetKeyHash (FName Key)
static uint32 GetKeyHash (FNameEntryId Key)
template<typename KeyType>
static const KeyType & GetSetKey (const TPair< KeyType, ValueType > &Element)
static bool Matches (const FAssetRegistryExportPath &A, const FAssetRegistryExportPath &B)
static bool Matches (const FMarshalledText &A, const FMarshalledText &B)
static bool Matches (const FNumberlessExportPath &A, const FNumberlessExportPath &B)
static bool Matches (const FString &A, const FString &B)
static bool Matches (const FUtf8String &A, const FUtf8String &B)
static bool Matches (FName A, FName B)
static bool Matches (FNameEntryId A, FNameEntryId B)
Additional Inherited Members
Public Types inherited from BaseKeyFuncs< ValueType, FString, false >
enum
typedef TCallTraits< ValueType >::ParamType ElementInitType
typedef TCallTraits< FString >::ParamType KeyInitType
typedef FString KeyType
Detailed Description
template<typename ValueType>
struct FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >
Definition at line 154 of file AssetDataTagMapSerializationDetails.h.
Member Function Documentation
GetKeyHash() [1/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (const FAssetRegistryExportPath & Key) inline static
Definition at line 210 of file AssetDataTagMapSerializationDetails.h.
References GetKeyHash(), FixedTagPrivate::HashCombineQuick(), and Key.
GetKeyHash() [2/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (const FMarshalledText & Key) inline static
Definition at line 220 of file AssetDataTagMapSerializationDetails.h.
References GetKeyHash(), and Key.
GetKeyHash() [3/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (const FNumberlessExportPath & Key) inline static
Definition at line 206 of file AssetDataTagMapSerializationDetails.h.
References GetKeyHash(), FixedTagPrivate::HashCombineQuick(), and Key.
GetKeyHash() [4/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (const FString & Key) inline static
Definition at line 170 of file AssetDataTagMapSerializationDetails.h.
References FixedTagPrivate::HashCaseSensitive(), and Key.
Referenced by GetKeyHash(), GetKeyHash(), and GetKeyHash().
GetKeyHash() [5/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (const FUtf8String & Key) inline static
Definition at line 174 of file AssetDataTagMapSerializationDetails.h.
References FixedTagPrivate::HashCaseSensitive(), and Key.
GetKeyHash() [6/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (FName Key) inline static
Definition at line 192 of file AssetDataTagMapSerializationDetails.h.
References FixedTagPrivate::GetTypeHash(), FixedTagPrivate::HashCombineQuick(), and Key.
GetKeyHash() [7/7]
template<typename ValueType> uint32 FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetKeyHash (FNameEntryId Key) inline static
Definition at line 183 of file AssetDataTagMapSerializationDetails.h.
References FixedTagPrivate::GetTypeHash(), and Key.
GetSetKey()
template<typename ValueType> template<typename KeyType> const KeyType & FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::GetSetKey (const TPair< KeyType, ValueType > & Element) inline static
Definition at line 157 of file AssetDataTagMapSerializationDetails.h.
Matches() [1/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (const FAssetRegistryExportPath & A, const FAssetRegistryExportPath & B) inline static
Definition at line 201 of file AssetDataTagMapSerializationDetails.h.
References A, B, and Matches().
Matches() [2/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (const FMarshalledText & A, const FMarshalledText & B) inline static
Definition at line 215 of file AssetDataTagMapSerializationDetails.h.
References A, B, and Matches().
Matches() [3/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (const FNumberlessExportPath & A, const FNumberlessExportPath & B) inline static
Definition at line 197 of file AssetDataTagMapSerializationDetails.h.
References A, B, and Matches().
Matches() [4/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (const FString & A, const FString & B) inline static
Definition at line 162 of file AssetDataTagMapSerializationDetails.h.
References A, B, and ESearchCase::CaseSensitive.
Referenced by Matches(), Matches(), and Matches().
Matches() [5/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (const FUtf8String & A, const FUtf8String & B) inline static
Definition at line 166 of file AssetDataTagMapSerializationDetails.h.
References A, B, and ESearchCase::CaseSensitive.
Matches() [6/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (FName A, FName B) inline static
Definition at line 188 of file AssetDataTagMapSerializationDetails.h.
References A, and B.
Matches() [7/7]
template<typename ValueType> bool FixedTagPrivate::FStoreBuilder::FCaseSensitiveFuncs< ValueType >::Matches (FNameEntryId A, FNameEntryId B) inline static
Definition at line 179 of file AssetDataTagMapSerializationDetails.h.
References A, and B.
The documentation for this struct was generated from the following file:
AssetDataTagMapSerializationDetails.h