Unreal Engine 5.6 C++ API: FVectorFixed48 Class Reference
FVectorFixed48 Class Reference
#include "AnimationCompression.h"
Public Member Functions
FVectorFixed48 ()
FVectorFixed48 (const FVector3f &Vec)
void FromVector (const FVector3f &Vec)
void ToVector (FVector3f &Out) const
Data Fields
uint16 X
uint16 Y
uint16 Z
Friends
FArchive & operator<< (FArchive &Ar, FVectorFixed48 &Vec)
Detailed Description
Definition at line 294 of file AnimationCompression.h.
Constructor & Destructor Documentation
FVectorFixed48() [1/2]
FVectorFixed48::FVectorFixed48 () inline
Definition at line 301 of file AnimationCompression.h.
Referenced by operator<<.
FVectorFixed48() [2/2]
FVectorFixed48::FVectorFixed48 (const FVector3f & Vec) inline explicit
Definition at line 304 of file AnimationCompression.h.
References FromVector().
Member Function Documentation
FromVector()
void FVectorFixed48::FromVector (const FVector3f & Vec) inline
Definition at line 309 of file AnimationCompression.h.
References Quant16BitFactor, Quant16BitOffs, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
Referenced by FVectorFixed48().
ToVector()
void FVectorFixed48::ToVector (FVector3f & Out) const inline
Definition at line 318 of file AnimationCompression.h.
References Quant16BitDiv, Quant16BitOffs, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FVectorFixed48 & Vec) friend
Definition at line 329 of file AnimationCompression.h.
References FVectorFixed48(), Ar, X, Y, and Z.
Field Documentation
X
uint16 FVectorFixed48::X
Definition at line 297 of file AnimationCompression.h.
Referenced by FromVector(), operator<<, and ToVector().
Y
uint16 FVectorFixed48::Y
Definition at line 298 of file AnimationCompression.h.
Referenced by FromVector(), operator<<, and ToVector().
Z
uint16 FVectorFixed48::Z
Definition at line 299 of file AnimationCompression.h.
Referenced by FromVector(), operator<<, and ToVector().
The documentation for this class was generated from the following file:
AnimationCompression.h