Unreal Engine 5.6 C++ API: Algo Namespace Reference
Algo Namespace Reference
Namespaces
namespace Private
Enumerations
enum ENoRef { NoRef }
A special enum indicating that reference should NOT be used when iterating a container.
enum class ETopologicalSort { None , AllowCycles }
Flags for behavior of TopologicalSort; see the function comment in TopologicalSort.h.
Functions
template<typename T, typename A>
FORCEINLINE T Accumulate (const A &Input, T Init)
Sums a range.
template<typename T, typename A, typename OpT>
FORCEINLINE T Accumulate (const A &Input, T Init, OpT Op)
Sums a range by successively applying Op.
template<typename RangeType>
FORCEINLINE bool AllOf (const RangeType &Range)
Checks if every element in the range is truthy.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool AllOf (const RangeType &Range, ProjectionType Projection)
Checks if every projection of the elements in the range is truthy.
template<typename RangeType>
FORCEINLINE bool AnyOf (const RangeType &Range)
Checks if any element in the range is truthy.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool AnyOf (const RangeType &Range, ProjectionType Projection)
Checks if any projection of the elements in the range is truthy.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool AnyOf (const RangeType &Range, ProjectionType Projection, ENoRef NoRef)
Checks if any projection of the elements in the range is truthy.
template<typename RangeType, typename ValueType>
FORCEINLINE auto BinarySearch (const RangeType &Range, const ValueType &Value)
template<typename RangeType, typename ValueType, typename SortPredicateType>
FORCEINLINE auto BinarySearch (const RangeType &Range, const ValueType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Returns index to the first found element matching a value in a range, the range must be sorted by <.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto BinarySearchBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection)
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto BinarySearchBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Returns index to the first found element with projected value matching Value in a range, the range must be sorted by predicate.
template<typename InAT, typename InBT>
constexpr bool Compare (const InAT &InputA, const InBT &InputB)
Compares two contiguous containers using operator== to compare pairs of elements.
template<typename InAT, typename InBT, typename PredicateT>
constexpr bool Compare (const InAT &InputA, const InBT &InputB, PredicateT Predicate)
Compares two contiguous containers using a predicate to compare pairs of elements.
template<typename InAT, typename InBT, typename ProjectionT>
constexpr bool CompareBy (const InAT &InputA, const InBT &InputB, ProjectionT Projection)
Compares two contiguous containers using operator== to compare pairs of projected elements.
template<typename InAT, typename InBT, typename ProjectionT, typename PredicateT>
constexpr bool CompareBy (const InAT &InputA, const InBT &InputB, ProjectionT Projection, PredicateT Predicate)
Compares two contiguous containers using a predicate to compare pairs of projected elements.
template<typename MapType>
int CompareMap (const MapType &A, const MapType &B)
template<typename MapType, typename KeyLessThanType>
int CompareMap (const MapType &A, const MapType &B, KeyLessThanType KeyLessThan)
template<typename MapType, typename KeyLessThanType, typename ValueLessThanType>
int CompareMap (const MapType &A, const MapType &B, KeyLessThanType KeyLessThan, ValueLessThanType ValueLessThan)
Compares two unique-key maps (e.g.
template<typename SetType>
int CompareSet (const SetType &A, const SetType &B)
template<typename SetType, typename KeyLessThanType>
int CompareSet (const SetType &A, const SetType &B, KeyLessThanType KeyLessThan)
Compares two sets (e.g.
template<typename RangeType, typename ValueType>
FORCEINLINE bool Contains (RangeType &&Range, const ValueType &Value)
Checks if the value exists in the range.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE bool ContainsBy (RangeType &&Range, const ValueType &Value, ProjectionType Proj)
Checks if the value exists in the range given by the projection.
template<typename InT, typename OutT>
FORCEINLINE void Copy (const InT &Input, OutT &Output)
Copies a range into a container.
template<typename InT, typename OutT>
FORCEINLINE void Copy (const InT &Input, OutT &Output, ENoRef NoRef)
Copies a range into a container.
template<typename InT, typename OutT, typename PredicateT>
FORCEINLINE void CopyIf (const InT &Input, OutT &Output, PredicateT Predicate)
Conditionally copies a range into a container.
template<typename InT, typename ValueT>
FORCEINLINE SIZE_T Count (const InT &Input, const ValueT &InValue)
Counts elements of a range that equal the supplied value.
template<typename InT, typename ValueT, typename ProjectionT>
FORCEINLINE SIZE_T CountBy (const InT &Input, const ValueT &InValue, ProjectionT Proj)
Counts elements of a range whose projection equals the supplied value.
template<typename InT, typename PredicateT>
FORCEINLINE SIZE_T CountIf (const InT &Input, PredicateT Predicate)
Counts elements of a range that match a given predicate.
ENUM_CLASS_FLAGS (ETopologicalSort)
template<typename RangeType, typename ValueType>
FORCEINLINE auto Find (RangeType &&Range, const ValueType &Value) -> decltype(AlgoImpl::FindBy(Forward< RangeType >(Range), Value, FIdentityFunctor()))
Returns a pointer to the first element in the range which is equal to the given value.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto FindBy (RangeType &&Range, const ValueType &Value, ProjectionType Proj) -> decltype(AlgoImpl::FindBy(Forward< RangeType >(Range), Value, MoveTemp(Proj)))
Returns a pointer to the first element in the range whose projection is equal to the given value.
template<typename RangeType, typename PredicateType>
FORCEINLINE auto FindByPredicate (RangeType &&Range, PredicateType Pred) -> decltype(AlgoImpl::FindByPredicate(Forward< RangeType >(Range), MoveTemp(Pred)))
Returns a pointer to the first element in the range which matches the predicate.
template<typename RangeType, typename ValueType>
FORCEINLINE auto FindLast (RangeType &&Range, const ValueType &Value) -> decltype(AlgoImpl::FindLastBy(GetData(Range), GetNum(Range), Value, FIdentityFunctor()))
Returns a pointer to the last element in the range which is equal to the given value.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto FindLastBy (RangeType &&Range, const ValueType &Value, ProjectionType Proj) -> decltype(AlgoImpl::FindLastBy(GetData(Range), GetNum(Range), Value, MoveTemp(Proj)))
Returns a pointer to the last element in the range whose projection is equal to the given value.
template<typename RangeType, typename PredicateType>
FORCEINLINE auto FindLastByPredicate (RangeType &&Range, PredicateType Pred) -> decltype(AlgoImpl::FindLastByPredicate(GetData(Range), GetNum(Range), MoveTemp(Pred)))
Returns a pointer to the last element in the range which matches the predicate.
template<typename RangeWhereType, typename RangeWhatType>
FORCEINLINE auto FindSequence (const RangeWhereType &Where, const RangeWhatType &What) -> decltype(AlgoImpl::FindSequence(GetData(Where), GetData(Where)+GetNum(Where), GetData(What), GetData(What)+GetNum(What)))
template<int32 ArraySize>
FORCEINLINE int32 FindSortedStringCaseInsensitive (const TCHAR *Str, const TCHAR *const (&SortedArray)[ArraySize])
Finds a string in an array of sorted strings, by case-insensitive search, by using binary subdivision of the array.
int32 FindSortedStringCaseInsensitive (const TCHAR *Str, const TCHAR *const *SortedArray, int32 ArrayCount)
Finds a string in an array of sorted strings, by case-insensitive search, by using binary subdivision of the array.
template<typename InT, typename CallableT>
FORCEINLINE void ForEach (InT &&Input, CallableT Callable)
Invokes a callable to each element in a range.
template<typename InT, typename PredicateT, typename CallableT>
FORCEINLINE void ForEachIf (InT &&Input, PredicateT Predicate, CallableT Callable)
Conditionally invokes a callable to each element in a range.
template<typename RangeType>
FORCEINLINE void Heapify (RangeType &&Range)
Builds an implicit min-heap from a range of elements.
template<typename RangeType, typename PredicateType>
FORCEINLINE void Heapify (RangeType &&Range, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void HeapifyBy (RangeType &&Range, ProjectionType Projection)
Builds an implicit min-heap from a range of elements.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void HeapifyBy (RangeType &&Range, ProjectionType Projection, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
template<typename RangeType>
FORCEINLINE void HeapSort (RangeType &&Range)
Performs heap sort on the elements.
template<typename RangeType, typename PredicateType>
FORCEINLINE void HeapSort (RangeType &&Range, PredicateType Predicate)
Performs heap sort on the elements.
template<typename RangeType, typename ProjectionType>
FORCEINLINE void HeapSortBy (RangeType &&Range, ProjectionType Projection)
Performs heap sort on the elements.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void HeapSortBy (RangeType &&Range, ProjectionType Projection, PredicateType Predicate)
Performs heap sort on the elements.
template<typename RangeTypeA, typename RangeTypeB>
constexpr bool Includes (const RangeTypeA &RangeA, const RangeTypeB &RangeB)
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of elements.
template<typename RangeTypeA, typename RangeTypeB, typename SortPredicateType>
constexpr bool Includes (const RangeTypeA &RangeA, const RangeTypeB &RangeB, SortPredicateType SortPredicate)
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of elements using a custom predicate.
template<typename RangeTypeA, typename RangeTypeB, typename ProjectionType>
constexpr bool IncludesBy (const RangeTypeA &RangeA, const RangeTypeB &RangeB, ProjectionType Projection)
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of projected elements.
template<typename RangeTypeA, typename RangeTypeB, typename ProjectionType, typename SortPredicateType>
constexpr bool IncludesBy (const RangeTypeA &RangeA, const RangeTypeB &RangeB, ProjectionType Projection, SortPredicateType SortPredicate)
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of projected elements using a custom predicate.
template<typename RangeType, typename ValueType>
FORCEINLINE auto IndexOf (const RangeType &Range, const ValueType &Value)
Returns the index of the first element in the range which is equal to the given value.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto IndexOfBy (const RangeType &Range, const ValueType &Value, ProjectionType Proj)
Returns the index of the first element in the range whose projection is equal to the given value.
template<typename RangeType, typename PredicateType>
FORCEINLINE auto IndexOfByPredicate (const RangeType &Range, PredicateType Pred)
Returns the index of the first element in the range which matches the predicate.
template<typename RangeType>
FORCEINLINE void IntroSort (RangeType &&Range)
Sort a range of elements using its operator<.
template<typename RangeType, typename PredicateType>
FORCEINLINE void IntroSort (RangeType &&Range, PredicateType Predicate)
Sort a range of elements using a user-defined predicate class.
template<typename RangeType, typename ProjectionType>
FORCEINLINE void IntroSortBy (RangeType &&Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void IntroSortBy (RangeType &&Range, ProjectionType Proj, PredicateType Predicate)
Sort a range of elements by a projection using a user-defined predicate class.
template<typename RangeType>
FORCEINLINE bool IsHeap (const RangeType &Range)
Verifies that the range is a min-heap (parent <= child).
template<typename RangeType, typename PredicateType>
FORCEINLINE bool IsHeap (const RangeType &Range, PredicateType Predicate)
Verifies that the range is a min-heap (parent <= child)
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool IsHeapBy (const RangeType &Range, ProjectionType Projection)
Verifies that the range is a min-heap (parent <= child).
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE bool IsHeapBy (const RangeType &Range, ProjectionType Projection, PredicateType Predicate)
Verifies that the range is a min-heap (parent <= child)
template<typename RangeType>
FORCEINLINE bool IsSorted (const RangeType &Range)
Tests if a range is sorted by its element type's operator<.
template<typename RangeType, typename PredType>
FORCEINLINE bool IsSorted (const RangeType &Range, PredType Pred)
Tests if a range is sorted by a user-defined predicate.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool IsSortedBy (const RangeType &Range, ProjectionType Projection)
Tests if a range is sorted by a projection of the element type, using the projection's operator<.
template<typename RangeType, typename ProjectionType, typename PredType>
FORCEINLINE bool IsSortedBy (const RangeType &Range, ProjectionType Projection, PredType Pred)
Tests if a range is sorted by a projection of the element type, using a user-defined predicate on the projection.
template<typename RangeType, typename GetElementDependenciesType>
bool KahnTopologicalSort (RangeType &&UniqueRange, GetElementDependenciesType GetElementDependencies, ETopologicalSort Flags)
Public entrypoint.
template<typename RangeType>
FORCEINLINE void LegacySort (RangeType &&Range)
Sort a range of elements using its operator<.
template<typename RangeType, typename PredicateType>
FORCEINLINE void LegacySort (RangeType &&Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
template<typename RangeType, typename ProjectionType>
FORCEINLINE void LegacySortBy (RangeType &&Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void LegacySortBy (RangeType &&Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
template<typename RangeAType, typename RangeBType>
int32 LevenshteinDistance (const RangeAType &RangeA, const RangeBType &RangeB)
LevenshteinDistance return the number of edit operation we need to transform RangeA to RangeB.
template<typename RangeType, typename ValueType>
FORCEINLINE auto LowerBound (const RangeType &Range, const ValueType &Value) -> decltype(GetNum(Range))
template<typename RangeType, typename ValueType, typename SortPredicateType>
FORCEINLINE auto LowerBound (const RangeType &Range, const ValueType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Performs binary search, resulting in position of the first element >= Value using predicate.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto LowerBoundBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection) -> decltype(GetNum(Range))
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto LowerBoundBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Performs binary search, resulting in position of the first element with projected value >= Value using predicate.
template<typename RangeType>
FORCEINLINE auto MaxElement (RangeType &&Range) -> decltype(AlgoImpl::MaxElementBy(Range, FIdentityFunctor(), TLess<>()))
Returns a pointer to the maximum element in a range.
template<typename RangeType, typename ComparatorType>
FORCEINLINE auto MaxElement (RangeType &&Range, ComparatorType Comp) -> decltype(AlgoImpl::MaxElementBy(Range, FIdentityFunctor(), MoveTemp(Comp)))
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
template<typename RangeType, typename ProjectionType>
FORCEINLINE auto MaxElementBy (RangeType &&Range, ProjectionType Proj) -> decltype(AlgoImpl::MaxElementBy(Range, MoveTemp(Proj), TLess<>()))
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
template<typename RangeType, typename ProjectionType, typename ComparatorType>
FORCEINLINE auto MaxElementBy (RangeType &&Range, ProjectionType Proj, ComparatorType Comp) -> decltype(AlgoImpl::MaxElementBy(Range, MoveTemp(Proj), MoveTemp(Comp)))
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
template<typename RangeType>
FORCEINLINE auto MinElement (RangeType &&Range) -> decltype(AlgoImpl::MinElementBy(Range, FIdentityFunctor(), TLess<>()))
Returns a pointer to the minimum element in a range.
template<typename RangeType, typename ComparatorType>
FORCEINLINE auto MinElement (RangeType &&Range, ComparatorType Comp) -> decltype(AlgoImpl::MinElementBy(Range, FIdentityFunctor(), MoveTemp(Comp)))
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
template<typename RangeType, typename ProjectionType>
FORCEINLINE auto MinElementBy (RangeType &&Range, ProjectionType Proj) -> decltype(AlgoImpl::MinElementBy(Range, MoveTemp(Proj), TLess<>()))
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
template<typename RangeType, typename ProjectionType, typename ComparatorType>
FORCEINLINE auto MinElementBy (RangeType &&Range, ProjectionType Proj, ComparatorType Comp) -> decltype(AlgoImpl::MinElementBy(Range, MoveTemp(Proj), MoveTemp(Comp)))
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
template<typename InputAType, typename InputBType>
constexpr auto Mismatch (const InputAType &InputA, const InputBType &InputB) -> std::common_type_t< decltype(GetNum(InputA)), decltype(GetNum(InputB))>
Returns the index at which two contiguous containers differ, using operator== to compare pairs of elements.
template<typename InputAType, typename InputBType, typename PredicateType>
constexpr auto Mismatch (const InputAType &InputA, const InputBType &InputB, PredicateType Predicate) -> std::common_type_t< decltype(GetNum(InputA)), decltype(GetNum(InputB))>
Returns the index at which two contiguous containers differ, using operator== to compare pairs of elements.
template<typename InputAType, typename InputBType, typename ProjectionType>
constexpr auto MismatchBy (const InputAType &InputA, const InputBType &InputB, ProjectionType Projection) -> std::common_type_t< decltype(GetNum(InputA)), decltype(GetNum(InputB))>
Returns the index at which two contiguous containers differ, using operator== to compare pairs of projected elements.
template<typename InputAType, typename InputBType, typename ProjectionType, typename PredicateType>
constexpr auto MismatchBy (const InputAType &InputA, const InputBType &InputB, ProjectionType Projection, PredicateType Predicate) -> std::common_type_t< decltype(GetNum(InputA)), decltype(GetNum(InputB))>
Returns the index at which two contiguous containers differ, using a predicate to compare pairs of projected elements.
template<typename RangeType>
FORCEINLINE bool NoneOf (const RangeType &Range)
Checks if no element in the range is truthy.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool NoneOf (const RangeType &Range, ProjectionType Projection)
Checks if no projection of the elements in the range is truthy.
template<typename RangeType, typename ProjectionType>
FORCEINLINE bool NoneOf (const RangeType &Range, ProjectionType Projection, ENoRef NoRef)
Checks if no projection of the elements in the range is truthy.
template<typename RangeType, typename UnaryPredicateType>
FORCEINLINE auto Partition (RangeType &&Range, UnaryPredicateType Predicate) -> decltype(GetNum(Range))
Rearranges the elements so that all the elements for which Predicate returns true precede all those for which it returns false.
template<class T, typename IndexType, typename UnaryPredicate>
IndexType Partition (T *Elements, const IndexType Num, UnaryPredicate Predicate)
Rearranges the elements so that all the elements for which Predicate returns true precede all those for which it returns false.
template<typename RangeType>
void RandomShuffle (RangeType &&Range)
Randomly shuffle a range of elements.
template<typename RangeType, typename Predicate>
int32 RemoveIf (RangeType &Range, Predicate Pred)
Moves all elements which do not match the predicate to the front of the range, while leaving all other elements is a constructed but unspecified state.
template<typename RangeType, typename ValueType>
FORCEINLINE void Replace (RangeType &&Range, const ValueType &InOld, const ValueType &InNew)
Replaces all elements that compare equal to one value with a new value.
template<typename RangeType, typename ValueType, typename PredicateType>
FORCEINLINE void ReplaceIf (RangeType &&Range, PredicateType InPred, const ValueType &InNew)
Replaces all elements that satisfy the predicate with the given value.
template<typename ContainerType>
FORCEINLINE void Reverse (ContainerType &&Container)
Reverses a range.
template<typename T>
FORCEINLINE void Reverse (T *Array, int32 ArraySize)
Reverses a range.
template<typename T, int32 ArraySize>
FORCEINLINE void Reverse (T(&Array)[ArraySize])
Reverses a range.
template<typename RangeType>
FORCEINLINE int32 Rotate (RangeType &&Range, int32 Count)
Rotates a given amount of elements from the front of the range to the end of the range.
template<typename RangeType, typename ProjectionType>
FORCEINLINE auto SelectRandomWeightedBy (RangeType &&Range, ProjectionType Proj) -> decltype(AlgoImpl::SelectRandomWeightedBy(Forward< RangeType >(Range), MoveTemp(Proj)))
Randomly select an element from a range of elements, weighted by a projection.
template<typename RangeType>
FORCEINLINE void Sort (RangeType &&Range)
Sort a range of elements using its operator<.
template<typename RangeType, typename PredicateType>
FORCEINLINE void Sort (RangeType &&Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
template<typename RangeType, typename ProjectionType>
FORCEINLINE void SortBy (RangeType &&Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void SortBy (RangeType &&Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
template<typename RangeType, typename Predicate>
int32 StableRemoveIf (RangeType &&Range, Predicate Pred)
Moves all elements which do not match the predicate to the front of the range, while leaving all other elements is a constructed but unspecified state.
template<typename RangeType>
FORCEINLINE void StableSort (RangeType &&Range)
Sort a range of elements using its operator<.
template<typename RangeType, typename PredicateType>
FORCEINLINE void StableSort (RangeType &&Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
template<typename RangeType, typename ProjectionType>
FORCEINLINE void StableSortBy (RangeType &&Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
template<typename RangeType, typename ProjectionType, typename PredicateType>
FORCEINLINE void StableSortBy (RangeType &&Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
template<typename... OutputTypes>
Private::TTiedTupleAdder< OutputTypes... > TieTupleAdd (OutputTypes &... Outputs)
Ties n objects with an Add function, usually containers, into one object with an Add function accepting an n-tuple that forwards the Add calls.
template<typename RangeType, typename GetElementDependenciesType>
FORCEINLINE bool TopologicalSort (RangeType &&UniqueRange, GetElementDependenciesType GetElementDependencies, ETopologicalSort Flags=ETopologicalSort::None)
Sorts the given range in leaf to root order: For every pair of elements (A,B) where SortedIndex(A) < SortedIndex(B), either B is not reachable from A, or A and B are mutually reachable.
template<typename InT, typename OutT, typename TransformT>
FORCEINLINE void Transform (const InT &Input, OutT &&Output, TransformT Trans)
Applies a transform to a range and stores the results into a container.
template<typename T, typename A, typename MapT>
FORCEINLINE T TransformAccumulate (const A &Input, MapT MapOp, T Init)
Sums a range by applying MapOp to each element, and then summing the results.
template<typename T, typename A, typename MapT, typename OpT>
FORCEINLINE T TransformAccumulate (const A &Input, MapT MapOp, T Init, OpT Op)
Sums a range by applying MapOp to each element, and then summing the results.
template<typename InT, typename OutT, typename PredicateT, typename TransformT>
FORCEINLINE void TransformIf (const InT &Input, OutT &&Output, PredicateT Predicate, TransformT Trans)
Conditionally applies a transform to a range and stores the results into a container.
template<typename RangeType, typename ValueType>
FORCEINLINE auto UpperBound (const RangeType &Range, const ValueType &Value) -> decltype(GetNum(Range))
template<typename RangeType, typename ValueType, typename SortPredicateType>
FORCEINLINE auto UpperBound (const RangeType &Range, const ValueType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Performs binary search, resulting in position of the first element > Value using predicate.
template<typename RangeType, typename ValueType, typename ProjectionType>
FORCEINLINE auto UpperBoundBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection) -> decltype(GetNum(Range))
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto UpperBoundBy (const RangeType &Range, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range))
Performs binary search, resulting in position of the first element with projected value > Value using predicate.
Enumeration Type Documentation
ENoRef
enum Algo::ENoRef
A special enum indicating that reference should NOT be used when iterating a container.
Enumerator
NoRef
Definition at line 10 of file Source/Runtime/Core/Public/Algo/Common.h.
ETopologicalSort
enum class Algo::ETopologicalSort strong
Flags for behavior of TopologicalSort; see the function comment in TopologicalSort.h.
Enumerator
None
AllowCycles
Definition at line 54 of file KahnTopologicalSort.h.
Function Documentation
Accumulate() [1/2]
template<typename T, typename A> FORCEINLINE T Algo::Accumulate (const A & Input, T Init) nodiscard
Sums a range.
Parameters
Input Any iterable type
Init Initial value for the summation
Returns
the result of summing all the elements of Input
Definition at line 54 of file Accumulate.h.
References A, Accumulate(), FORCEINLINE, Init, Input, and MoveTemp().
Accumulate() [2/2]
template<typename T, typename A, typename OpT> FORCEINLINE T Algo::Accumulate (const A & Input, T Init, OpT Op) nodiscard
Sums a range by successively applying Op.
Parameters
Input Any iterable type
Init Initial value for the summation
Op Summing Operation (the default is TPlus<>)
Returns
the result of summing all the elements of Input
Definition at line 35 of file Accumulate.h.
References A, FORCEINLINE, Init, Input, Invoke(), and MoveTemp().
Referenced by Accumulate(), and AlgoImpl::SelectRandomWeightedBy().
AllOf() [1/2]
template<typename RangeType> FORCEINLINE bool Algo::AllOf (const RangeType & Range) nodiscard
Checks if every element in the range is truthy.
Parameters
Range The range to check.
Returns
true if all the elements are truthy, false otherwise.
Definition at line 19 of file AllOf.h.
References FORCEINLINE.
Referenced by UE::MovieScene::FEntityManager::ContainsAllComponents().
AllOf() [2/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::AllOf (const RangeType & Range, ProjectionType Projection) nodiscard
Checks if every projection of the elements in the range is truthy.
Parameters
Range The range to check.
Projection The projection to apply to each element.
Returns
true if all the projections are truthy, false otherwise.
Definition at line 41 of file AllOf.h.
References FORCEINLINE, Invoke(), and Projection().
AnyOf() [1/3]
template<typename RangeType> FORCEINLINE bool Algo::AnyOf (const RangeType & Range) nodiscard
Checks if any element in the range is truthy.
Parameters
Range The range to check.
Returns
true if at least one element is truthy, false otherwise.
Definition at line 20 of file Algo/AnyOf.h.
References FORCEINLINE, and NoneOf().
Referenced by UE::MovieScene::FEntityManager::ContainsAnyComponent(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::ProcessInvalidatedOutputs().
AnyOf() [2/3]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::AnyOf (const RangeType & Range, ProjectionType Projection) nodiscard
Checks if any projection of the elements in the range is truthy.
Parameters
Range The range to check.
Projection The projection to apply to each element.
Returns
true if at least one projection is truthy, false otherwise.
Definition at line 34 of file Algo/AnyOf.h.
References FORCEINLINE, MoveTemp(), NoneOf(), and Projection().
AnyOf() [3/3]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::AnyOf (const RangeType & Range, ProjectionType Projection, ENoRef NoRef) nodiscard
Checks if any projection of the elements in the range is truthy.
Should be used when the range iterator doesn't return a reference.
Parameters
Range The range to check.
Projection The projection to apply to each element.
Returns
true if at least one projection is truthy, false otherwise.
Definition at line 49 of file Algo/AnyOf.h.
References FORCEINLINE, MoveTemp(), NoneOf(), NoRef, and Projection().
BinarySearch() [1/2]
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::BinarySearch (const RangeType & Range, const ValueType & Value) nodiscard
Definition at line 188 of file BinarySearch.h.
References BinarySearch(), FORCEINLINE, and Value.
BinarySearch() [2/2]
template<typename RangeType, typename ValueType, typename SortPredicateType> FORCEINLINE auto Algo::BinarySearch (const RangeType & Range, const ValueType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Returns index to the first found element matching a value in a range, the range must be sorted by <.
Parameters
Range The range to search, must be already sorted by SortPredicate
Value The value to search for
SortPredicate Predicate for sort comparison, defaults to <
Returns
Index of found element, or INDEX_NONE
Definition at line 173 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), INDEX_NONE, LowerBound(), and Value.
Referenced by BinarySearch(), FFindReferencersArchive::FTargetObjectContainer::GetRefCountPtr(), and FFindReferencersArchive::FTargetObjectContainer::TryGetRefCountPtr().
BinarySearchBy() [1/2]
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::BinarySearchBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection) nodiscard
Definition at line 218 of file BinarySearch.h.
References BinarySearchBy(), FORCEINLINE, Projection(), and Value.
BinarySearchBy() [2/2]
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto Algo::BinarySearchBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Returns index to the first found element with projected value matching Value in a range, the range must be sorted by predicate.
Parameters
Range The range to search, must be already sorted by SortPredicate
Value The value to search for
Projection Functor or data member pointer, called via Invoke to compare to Value
SortPredicate Predicate for sort comparison, defaults to <
Returns
Index of found element, or INDEX_NONE
Definition at line 203 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), INDEX_NONE, Invoke(), LowerBoundBy(), Projection(), and Value.
Referenced by BinarySearchBy(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindIndex(), FShaderMapContent::GetShaderPipeline(), and UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::IndexOf().
Compare() [1/2]
template<typename InAT, typename InBT> bool Algo::Compare (const InAT & InputA, const InBT & InputB) nodiscard constexpr
Compares two contiguous containers using operator== to compare pairs of elements.
Parameters
InputA Container of elements that are used as the first argument to operator==.
InputB Container of elements that are used as the second argument to operator==.
Returns
Whether the containers are the same size and operator== returned true for every pair of elements.
Definition at line 51 of file Compare.h.
References Algo::Private::Compare().
Referenced by CompareMap().
Compare() [2/2]
template<typename InAT, typename InBT, typename PredicateT> bool Algo::Compare (const InAT & InputA, const InBT & InputB, PredicateT Predicate) nodiscard constexpr
Compares two contiguous containers using a predicate to compare pairs of elements.
Parameters
InputA Container of elements that are used as the first argument to the predicate.
InputB Container of elements that are used as the second argument to the predicate.
Predicate Condition which returns true for elements which are deemed equal.
Returns
Whether the containers are the same size and the predicate returned true for every pair of elements.
Definition at line 66 of file Compare.h.
References Algo::Private::Compare(), MoveTemp(), and Predicate.
CompareBy() [1/2]
template<typename InAT, typename InBT, typename ProjectionT> bool Algo::CompareBy (const InAT & InputA, const InBT & InputB, ProjectionT Projection) nodiscard constexpr
Compares two contiguous containers using operator== to compare pairs of projected elements.
Parameters
InputA Container of elements that are used as the first argument to operator==.
InputB Container of elements that are used as the second argument to operator==.
Projection Projection to apply to the elements before comparing them.
Returns
Whether the containers are the same size and operator== returned true for every pair of elements.
Definition at line 81 of file Compare.h.
References Algo::Private::Compare(), MoveTemp(), and Projection().
CompareBy() [2/2]
template<typename InAT, typename InBT, typename ProjectionT, typename PredicateT> bool Algo::CompareBy (const InAT & InputA, const InBT & InputB, ProjectionT Projection, PredicateT Predicate) nodiscard constexpr
Compares two contiguous containers using a predicate to compare pairs of projected elements.
Parameters
InputA Container of elements that are used as the first argument to the predicate.
InputB Container of elements that are used as the second argument to the predicate.
Projection Projection to apply to the elements before comparing them.
Predicate Condition which returns true for elements which are deemed equal.
Returns
Whether the containers are the same size and the predicate returned true for every pair of elements.
Definition at line 97 of file Compare.h.
References Algo::Private::Compare(), MoveTemp(), Predicate, and Projection().
CompareMap() [1/3]
template<typename MapType> int Algo::CompareMap (const MapType & A, const MapType & B) nodiscard
Definition at line 194 of file Compare.h.
References A, B, and CompareMap().
CompareMap() [2/3]
template<typename MapType, typename KeyLessThanType> int Algo::CompareMap (const MapType & A, const MapType & B, KeyLessThanType KeyLessThan) nodiscard
Definition at line 200 of file Compare.h.
References A, B, CompareMap(), and MoveTempIfPossible().
CompareMap() [3/3]
template<typename MapType, typename KeyLessThanType, typename ValueLessThanType> int Algo::CompareMap (const MapType & A, const MapType & B, KeyLessThanType KeyLessThan, ValueLessThanType ValueLessThan) nodiscard
Compares two unique-key maps (e.g.
TMap) as if they were sorted arrays of key,value pairs sorted by Key and then by Value (almost, see note on sort order). Does not support multiple values per key (e.g. TMultiMap).
Note on sort order: Maps with a smaller number of elements are considered less than maps with a larger number of elements, no matter what keys are present in each map. This drastically improves performance when comparing maps of different sizes. This is different than would be exepcted from a lexical compare of strings, but it does match the comparison of two numbers represented as a string of digits.
MapType interface: typename KeyType, typename ValueType, IntType Num(), ValueType* Find(const KeyType&), IteratorType<PairType> begin(), end() PairType interface: const KeyType& Key, const ValueType& Value
Parameters
A Left-Hand-Side map container.
B Right-Hand-Side map container.
KeyLessThan bool(const KeyType& A, const KeyType& B) that returns A < B.
ValueLessThan bool(const ValueType& A, const ValueType& B) that returns A < B.
Returns
-1 if A < B, 0 if A == B, 1 if A > B
Definition at line 125 of file Compare.h.
References A, B, and Compare().
Referenced by CompareMap(), and CompareMap().
CompareSet() [1/2]
template<typename SetType> int Algo::CompareSet (const SetType & A, const SetType & B) nodiscard
Definition at line 276 of file Compare.h.
References A, B, and CompareSet().
CompareSet() [2/2]
template<typename SetType, typename KeyLessThanType> int Algo::CompareSet (const SetType & A, const SetType & B, KeyLessThanType KeyLessThan) nodiscard
Compares two sets (e.g.
TSet) as if they were sorted arrays of keys (almost, see note on sort order).
Note on sort order: Maps with a smaller number of elements are considered less than maps with a larger number of elements, no matter what keys are present in each map. This drastically improves performance when comparing maps of different sizes. This is different than would be exepcted from a lexical compare of strings, but it does match the comparison of two numbers represented as a string of digits.
SetType interface: typename ElementType IntType Num(), bool Contains(const KeyType&), IteratorType<KeyType> begin(), end()
Parameters
A Left-Hand-Side set container.
B Right-Hand-Side set container.
KeyLessThan bool(const KeyType& A, const KeyType& B) that returns A < B.
Returns
-1 if A < B, 0 if A == B, 1 if A > B
Definition at line 224 of file Compare.h.
References A, and B.
Referenced by CompareSet().
Contains()
template<typename RangeType, typename ValueType> FORCEINLINE bool Algo::Contains (RangeType && Range, const ValueType & Value) nodiscard
Checks if the value exists in the range.
Parameters
Range The range to search.
Value The value to search for.
Returns
true if an element was found, false otherwise.
Definition at line 19 of file Contains.h.
References Find(), FORCEINLINE, Forward(), and Value.
ContainsBy()
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE bool Algo::ContainsBy (RangeType && Range, const ValueType & Value, ProjectionType Proj) nodiscard
Checks if the value exists in the range given by the projection.
Parameters
Range The range to search.
Value The value to search for.
Proj The projection to apply to the element.
Returns
true if an element was found, false otherwise.
Definition at line 34 of file Contains.h.
References FindBy(), FORCEINLINE, Forward(), MoveTemp(), and Value.
Copy() [1/2]
template<typename InT, typename OutT> FORCEINLINE void Algo::Copy (const InT & Input, OutT & Output)
Copies a range into a container.
Parameters
Input Any iterable type
Output Container to hold the output
Definition at line 36 of file Copy.h.
References FORCEINLINE, Input, and Value.
Copy() [2/2]
template<typename InT, typename OutT> FORCEINLINE void Algo::Copy (const InT & Input, OutT & Output, ENoRef NoRef)
Copies a range into a container.
Should be used if when the input iterator doesn't return a reference.
Parameters
Input Any iterable type
Output Container to hold the output
Definition at line 52 of file Copy.h.
References FORCEINLINE, Input, NoRef, and Value.
CopyIf()
template<typename InT, typename OutT, typename PredicateT> FORCEINLINE void Algo::CopyIf (const InT & Input, OutT & Output, PredicateT Predicate)
Conditionally copies a range into a container.
Parameters
Input Any iterable type
Output Container to hold the output
Predicate Condition which returns true for elements that should be copied and false for elements that should be skipped
Definition at line 18 of file Copy.h.
References FORCEINLINE, Input, Invoke(), Predicate, and Value.
Count()
template<typename InT, typename ValueT> FORCEINLINE SIZE_T Algo::Count (const InT & Input, const ValueT & InValue) nodiscard
Counts elements of a range that equal the supplied value.
Parameters
Input Any iterable type
InValue Value to compare against
Definition at line 16 of file Count.h.
References FORCEINLINE, Input, and Value.
Referenced by Algo::Private::Compare(), and Rotate().
CountBy()
template<typename InT, typename ValueT, typename ProjectionT> FORCEINLINE SIZE_T Algo::CountBy (const InT & Input, const ValueT & InValue, ProjectionT Proj) nodiscard
Counts elements of a range whose projection equals the supplied value.
Parameters
Input Any iterable type
InValue Value to compare against
Projection The projection to apply to the element
Definition at line 57 of file Count.h.
References FORCEINLINE, Input, Invoke(), and Value.
CountIf()
template<typename InT, typename PredicateT> FORCEINLINE SIZE_T Algo::CountIf (const InT & Input, PredicateT Predicate) nodiscard
Counts elements of a range that match a given predicate.
Parameters
Input Any iterable type
Predicate Condition which returns true for elements that should be counted and false for elements that should be skipped
Definition at line 36 of file Count.h.
References FORCEINLINE, Input, Invoke(), Predicate, and Value.
ENUM_CLASS_FLAGS()
Algo::ENUM_CLASS_FLAGS (ETopologicalSort)
Find()
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::Find (RangeType && Range, const ValueType & Value) -> decltype(AlgoImpl::FindBy(Forward<RangeType>(Range), Value, FIdentityFunctor())) nodiscard
Returns a pointer to the first element in the range which is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Returns
A pointer to the first element found, or nullptr if none was found.
Definition at line 52 of file Algo/Find.h.
References AlgoImpl::FindBy(), FORCEINLINE, Forward(), and Value.
Referenced by Contains(), and TDefaultNumericTypeInterface< NumericType >::IsCharacterValid().
FindBy()
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::FindBy (RangeType && Range, const ValueType & Value, ProjectionType Proj) -> decltype(AlgoImpl::FindBy(Forward<RangeType>(Range), Value, MoveTemp(Proj))) nodiscard
Returns a pointer to the first element in the range whose projection is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Proj The projection to apply to the element.
Returns
A pointer to the first element found, or nullptr if none was found.
Definition at line 68 of file Algo/Find.h.
References AlgoImpl::FindBy(), FORCEINLINE, Forward(), MoveTemp(), and Value.
Referenced by ContainsBy(), DECLARE_STATS_GROUP(), and FPersistentStorageManager::GetPersistentStorageUsageByCategory().
FindByPredicate()
template<typename RangeType, typename PredicateType> FORCEINLINE auto Algo::FindByPredicate (RangeType && Range, PredicateType Pred) -> decltype(AlgoImpl::FindByPredicate(Forward<RangeType>(Range), MoveTemp(Pred))) nodiscard
Returns a pointer to the first element in the range which matches the predicate.
Parameters
Range The range to search.
Pred The predicate to search for.
Returns
A pointer to the first element found, or nullptr if none was found.
Definition at line 83 of file Algo/Find.h.
References AlgoImpl::FindByPredicate(), FORCEINLINE, Forward(), and MoveTemp().
Referenced by FMeshDescription::GetVertexInstanceForTriangleVertex(), and FPersistentStorageManager::TryManageFileInternal().
FindLast()
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::FindLast (RangeType && Range, const ValueType & Value) -> decltype(AlgoImpl::FindLastBy(GetData(Range), GetNum(Range), Value, FIdentityFunctor())) nodiscard
Returns a pointer to the last element in the range which is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Returns
A pointer to the last element found, or nullptr if none was found.
Definition at line 51 of file FindLast.h.
References AlgoImpl::FindLastBy(), FORCEINLINE, GetData(), GetNum(), and Value.
FindLastBy()
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::FindLastBy (RangeType && Range, const ValueType & Value, ProjectionType Proj) -> decltype(AlgoImpl::FindLastBy(GetData(Range), GetNum(Range), Value, MoveTemp(Proj))) nodiscard
Returns a pointer to the last element in the range whose projection is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Proj The projection to apply to the element.
Returns
A pointer to the last element found, or nullptr if none was found.
Definition at line 67 of file FindLast.h.
References AlgoImpl::FindLastBy(), FORCEINLINE, GetData(), GetNum(), MoveTemp(), and Value.
FindLastByPredicate()
template<typename RangeType, typename PredicateType> FORCEINLINE auto Algo::FindLastByPredicate (RangeType && Range, PredicateType Pred) -> decltype(AlgoImpl::FindLastByPredicate(GetData(Range), GetNum(Range), MoveTemp(Pred))) nodiscard
Returns a pointer to the last element in the range which matches the predicate.
Parameters
Range The range to search.
Pred The predicate to search for.
Returns
A pointer to the last element found, or nullptr if none was found.
Definition at line 82 of file FindLast.h.
References AlgoImpl::FindLastByPredicate(), FORCEINLINE, GetData(), GetNum(), and MoveTemp().
FindSequence()
template<typename RangeWhereType, typename RangeWhatType> FORCEINLINE auto Algo::FindSequence (const RangeWhereType & Where, const RangeWhatType & What) -> decltype(AlgoImpl::FindSequence(GetData(Where), GetData(Where) + GetNum(Where), GetData(What), GetData(What) + GetNum(What))) nodiscard
Definition at line 46 of file FindSequence.h.
References AlgoImpl::FindSequence(), FORCEINLINE, GetData(), and GetNum().
FindSortedStringCaseInsensitive() [1/2]
template<int32 ArraySize> FORCEINLINE int32 Algo::FindSortedStringCaseInsensitive (const TCHAR * Str, const TCHAR *const (&) SortedArray[ArraySize]) nodiscard
Finds a string in an array of sorted strings, by case-insensitive search, by using binary subdivision of the array.
Parameters
Str The string to look for.
SortedArray The array of strings to search. The strings must be sorted lexicographically, case-insensitively.
Returns
The index of the found string in the array, or -1 if the string was not found.
Definition at line 29 of file FindSortedStringCaseInsensitive.h.
References FindSortedStringCaseInsensitive(), and FORCEINLINE.
FindSortedStringCaseInsensitive() [2/2]
int32 Algo::FindSortedStringCaseInsensitive (const TCHAR * Str, const TCHAR *const * SortedArray, int32 ArrayCount) nodiscard
Finds a string in an array of sorted strings, by case-insensitive search, by using binary subdivision of the array.
Parameters
Str The string to look for.
SortedArray The array of strings to search. The strings must be sorted lexicographically, case-insensitively.
ArrayCount The number of strings in the array.
Returns
The index of the found string in the array, or -1 if the string was not found.
Referenced by FindSortedStringCaseInsensitive().
ForEach()
template<typename InT, typename CallableT> FORCEINLINE void Algo::ForEach (InT && Input, CallableT Callable)
Invokes a callable to each element in a range.
Parameters
Input Any iterable type
Callable Callable object
Definition at line 36 of file ForEach.h.
References FORCEINLINE, Input, Invoke(), and Value.
Referenced by FCurveEditorFilterStates::ForEachItemState(), and TStaticSpatialIndex< ValueType, Profile, SpatialIndexType, ElementsSorter >::InitSpatialIndex().
ForEachIf()
template<typename InT, typename PredicateT, typename CallableT> FORCEINLINE void Algo::ForEachIf (InT && Input, PredicateT Predicate, CallableT Callable)
Conditionally invokes a callable to each element in a range.
Parameters
Input Any iterable type
Predicate Condition which returns true for elements that should be called with and false for elements that should be skipped
Callable Callable object
Definition at line 18 of file ForEach.h.
References FORCEINLINE, Input, Invoke(), Predicate, and Value.
Heapify() [1/2]
template<typename RangeType> FORCEINLINE void Algo::Heapify (RangeType && Range)
Builds an implicit min-heap from a range of elements.
Assumes < operator is defined for the element type.
Parameters
Range The range to heapify.
Definition at line 20 of file Heapify.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::HeapifyInternal().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Heapify().
Heapify() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::Heapify (RangeType && Range, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
Parameters
Range The range to heapify.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 32 of file Heapify.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapifyInternal(), and Predicate.
HeapifyBy() [1/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::HeapifyBy (RangeType && Range, ProjectionType Projection)
Builds an implicit min-heap from a range of elements.
Assumes < operator is defined for the projected element type.
Parameters
Range The range to heapify.
Projection The projection to apply to the elements.
Definition at line 45 of file Heapify.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapifyInternal(), and Projection().
HeapifyBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::HeapifyBy (RangeType && Range, ProjectionType Projection, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
Parameters
Range The range to heapify.
Projection The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 58 of file Heapify.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapifyInternal(), Predicate, and Projection().
HeapSort() [1/2]
template<typename RangeType> FORCEINLINE void Algo::HeapSort (RangeType && Range)
Performs heap sort on the elements.
Assumes < operator is defined for the element type.
Parameters
Range The range to sort.
Definition at line 18 of file HeapSort.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::HeapSortInternal().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapSort().
HeapSort() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::HeapSort (RangeType && Range, PredicateType Predicate)
Performs heap sort on the elements.
Parameters
Range The range to sort.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 30 of file HeapSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapSortInternal(), MoveTemp(), and Predicate.
HeapSortBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE void Algo::HeapSortBy (RangeType && Range, ProjectionType Projection)
Performs heap sort on the elements.
Assumes < operator is defined for the projected element type.
Parameters
Range The range to sort.
Projection The projection to sort by when applied to the element.
Definition at line 42 of file HeapSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapSortInternal(), and Projection().
HeapSortBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::HeapSortBy (RangeType && Range, ProjectionType Projection, PredicateType Predicate)
Performs heap sort on the elements.
Parameters
Range The range to sort.
Projection The projection to sort by when applied to the element.
Predicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Definition at line 55 of file HeapSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::HeapSortInternal(), MoveTemp(), Predicate, and Projection().
Includes() [1/2]
template<typename RangeTypeA, typename RangeTypeB> bool Algo::Includes (const RangeTypeA & RangeA, const RangeTypeB & RangeB) nodiscard constexpr
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of elements.
The subsequence does not need to be contiguous. Uses operator< to compare pairs of elements.
Parameters
RangeA Container of elements to search through. Must be already sorted by operator<.
RangeB Container of elements to search for. Must be already sorted by operator<.
Returns
True if RangeB is a subsequence of RangeA, false otherwise.
Definition at line 55 of file Includes.h.
References GetData(), GetNum(), and Algo::Private::Includes().
Includes() [2/2]
template<typename RangeTypeA, typename RangeTypeB, typename SortPredicateType> bool Algo::Includes (const RangeTypeA & RangeA, const RangeTypeB & RangeB, SortPredicateType SortPredicate) nodiscard constexpr
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of elements using a custom predicate.
The subsequence does not need to be contiguous.
Parameters
RangeA Container of elements to search through. Must be already sorted by SortPredicate.
RangeB Container of elements to search for. Must be already sorted by SortPredicate.
SortPredicate A binary predicate object used to specify if one element should precede another.
Returns
True if RangeB is a subsequence of RangeA according to the provided predicate, false otherwise.
Definition at line 71 of file Includes.h.
References GetData(), GetNum(), Algo::Private::Includes(), and MoveTemp().
IncludesBy() [1/2]
template<typename RangeTypeA, typename RangeTypeB, typename ProjectionType> bool Algo::IncludesBy (const RangeTypeA & RangeA, const RangeTypeB & RangeB, ProjectionType Projection) nodiscard constexpr
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of projected elements.
The subsequence does not need to be contiguous. Uses operator< to compare pairs of projected elements.
Parameters
RangeA Container of elements to search through. Must be already sorted by operator<.
RangeB Container of elements to search for. Must be already sorted by operator<.
Projection Projection to apply to the elements before comparing them.
Returns
True if RangeB is a subsequence of RangeA, based on the comparison of projected elements, false otherwise.
Definition at line 87 of file Includes.h.
References GetData(), GetNum(), Algo::Private::Includes(), MoveTemp(), and Projection().
IncludesBy() [2/2]
template<typename RangeTypeA, typename RangeTypeB, typename ProjectionType, typename SortPredicateType> bool Algo::IncludesBy (const RangeTypeA & RangeA, const RangeTypeB & RangeB, ProjectionType Projection, SortPredicateType SortPredicate) nodiscard constexpr
Checks if one sorted contiguous container is a subsequence of another sorted contiguous container by comparing pairs of projected elements using a custom predicate.
The subsequence does not need to be contiguous.
Parameters
RangeA Container of elements to search through. Must be already sorted by SortPredicate.
RangeB Container of elements to search for. Must be already sorted by SortPredicate.
Projection Projection to apply to the elements before comparing them.
SortPredicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Returns
True if RangeB is a subsequence of RangeA according to the comparison of projected elements using the provided predicate, false otherwise.
Definition at line 104 of file Includes.h.
References GetData(), GetNum(), Algo::Private::Includes(), MoveTemp(), and Projection().
IndexOf()
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::IndexOf (const RangeType & Range, const ValueType & Value) nodiscard
Returns the index of the first element in the range which is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Returns
The index of the first element found, or (SizeType)-1 if none was found (where SizeType = decltype(GetNum(Range)))
Definition at line 59 of file IndexOf.h.
References FORCEINLINE, AlgoImpl::IndexOfBy(), TIsContiguousContainer< T >::Value, and Value.
IndexOfBy()
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::IndexOfBy (const RangeType & Range, const ValueType & Value, ProjectionType Proj) nodiscard
Returns the index of the first element in the range whose projection is equal to the given value.
Parameters
Range The range to search.
Value The value to search for.
Proj The projection to apply to the element.
Returns
The index of the first element found, or (SizeType)-1 if none was found (where SizeType = decltype(GetNum(Range)))
Definition at line 75 of file IndexOf.h.
References FORCEINLINE, AlgoImpl::IndexOfBy(), MoveTemp(), TIsContiguousContainer< T >::Value, and Value.
IndexOfByPredicate()
template<typename RangeType, typename PredicateType> FORCEINLINE auto Algo::IndexOfByPredicate (const RangeType & Range, PredicateType Pred) nodiscard
Returns the index of the first element in the range which matches the predicate.
Parameters
Range The range to search.
Pred The predicate to search for.
Returns
The index of the first element found, or (SizeType)-1 if none was found (where SizeType = decltype(GetNum(Range)))
Definition at line 90 of file IndexOf.h.
References FORCEINLINE, AlgoImpl::IndexOfByPredicate(), MoveTemp(), and TIsContiguousContainer< T >::Value.
IntroSort() [1/2]
template<typename RangeType> FORCEINLINE void Algo::IntroSort (RangeType && Range)
Sort a range of elements using its operator<.
The sort is unstable.
Parameters
Range The range to sort.
Definition at line 149 of file IntroSort.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::IntroSortInternal().
Referenced by Sort(), and Sort().
IntroSort() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::IntroSort (RangeType && Range, PredicateType Predicate)
Sort a range of elements using a user-defined predicate class.
The sort is unstable.
Parameters
Range The range to sort.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 161 of file IntroSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IntroSortInternal(), MoveTemp(), and Predicate.
IntroSortBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE void Algo::IntroSortBy (RangeType && Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
The sort is unstable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Definition at line 173 of file IntroSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IntroSortInternal(), MoveTemp(), and Projection().
Referenced by SortBy(), and SortBy().
IntroSortBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::IntroSortBy (RangeType && Range, ProjectionType Proj, PredicateType Predicate)
Sort a range of elements by a projection using a user-defined predicate class.
The sort is unstable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Predicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Definition at line 191 of file IntroSort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IntroSortInternal(), MoveTemp(), Predicate, and Projection().
IsHeap() [1/2]
template<typename RangeType> FORCEINLINE bool Algo::IsHeap (const RangeType & Range) nodiscard
Verifies that the range is a min-heap (parent <= child).
Assumes < operator is defined for the element type.
Parameters
Range The range to verify.
Returns
returns true if the range is a min-heap
Definition at line 50 of file IsHeap.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::IsHeapInternal().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::VerifyHeap().
IsHeap() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE bool Algo::IsHeap (const RangeType & Range, PredicateType Predicate) nodiscard
Verifies that the range is a min-heap (parent <= child)
Parameters
Range The range to verify.
Predicate A binary predicate object used to specify if one element should precede another.
Returns
returns true if the range is a min-heap
Definition at line 64 of file IsHeap.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsHeapInternal(), MoveTemp(), and Predicate.
IsHeapBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::IsHeapBy (const RangeType & Range, ProjectionType Projection) nodiscard
Verifies that the range is a min-heap (parent <= child).
Assumes < operator is defined for the projected element type.
Parameters
Range The range to verify.
Projection The projection to apply to the elements.
Returns
returns true if the range is a min-heap
Definition at line 78 of file IsHeap.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsHeapInternal(), MoveTemp(), and Projection().
IsHeapBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE bool Algo::IsHeapBy (const RangeType & Range, ProjectionType Projection, PredicateType Predicate) nodiscard
Verifies that the range is a min-heap (parent <= child)
Parameters
Range The range to verify.
Projection The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Returns
returns true if the range is a min-heap
Definition at line 93 of file IsHeap.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsHeapInternal(), MoveTemp(), Predicate, and Projection().
IsSorted() [1/2]
template<typename RangeType> FORCEINLINE bool Algo::IsSorted (const RangeType & Range) nodiscard
Tests if a range is sorted by its element type's operator<.
Parameters
Range The container to test for being sorted.
Returns
true if the range is sorted, false otherwise.
Definition at line 66 of file IsSorted.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::IsSortedBy().
Referenced by UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::CheckSorted().
IsSorted() [2/2]
template<typename RangeType, typename PredType> FORCEINLINE bool Algo::IsSorted (const RangeType & Range, PredType Pred) nodiscard
Tests if a range is sorted by a user-defined predicate.
Parameters
Range The container to test for being sorted.
Pred A binary sorting predicate which describes the ordering of the elements in the array.
Returns
true if the range is sorted, false otherwise.
Definition at line 80 of file IsSorted.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsSortedBy(), and MoveTemp().
IsSortedBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::IsSortedBy (const RangeType & Range, ProjectionType Projection) nodiscard
Tests if a range is sorted by a projection of the element type, using the projection's operator<.
Parameters
Range The container to test for being sorted.
Returns
true if the range is sorted, false otherwise.
Definition at line 93 of file IsSorted.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsSortedBy(), MoveTemp(), and Projection().
IsSortedBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredType> FORCEINLINE bool Algo::IsSortedBy (const RangeType & Range, ProjectionType Projection, PredType Pred) nodiscard
Tests if a range is sorted by a projection of the element type, using a user-defined predicate on the projection.
Parameters
Range The container to test for being sorted.
Pred A binary sorting predicate which describes the ordering of the elements in the array.
Returns
true if the range is sorted, false otherwise.
Definition at line 107 of file IsSorted.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::IsSortedBy(), MoveTemp(), and Projection().
KahnTopologicalSort()
template<typename RangeType, typename GetElementDependenciesType> bool Algo::KahnTopologicalSort (RangeType && UniqueRange, GetElementDependenciesType GetElementDependencies, ETopologicalSort Flags)
Public entrypoint.
Implements Algo::TopologicalSort using the Kahn Topological Sort algorithm.
Definition at line 63 of file KahnTopologicalSort.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), AllowCycles, check, EnumHasAnyFlags(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), Flags, Forward(), INDEX_NONE, TSet< InElementType, KeyFuncs, Allocator >::IsEmpty(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), TSet< InElementType, KeyFuncs, Allocator >::Num(), TSet< InElementType, KeyFuncs, Allocator >::Remove(), TArray< InElementType, InAllocatorType >::Reserve(), TSet< InElementType, KeyFuncs, Allocator >::Reserve(), TSet< InElementType, KeyFuncs, Allocator >::Reset(), Swap, and Vertex.
Referenced by TopologicalSort().
LegacySort() [1/2]
template<typename RangeType> FORCEINLINE void Algo::LegacySort (RangeType && Range)
Sort a range of elements using its operator<.
The sort is unstable. This used to be Algo::Sort and is now considered legacy.
Parameters
Range The range to sort.
Definition at line 120 of file LegacySort.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::LegacySortInternal().
LegacySort() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::LegacySort (RangeType && Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
The sort is unstable. This used to be Algo::Sort and is now considered legacy.
Parameters
Range The range to sort.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 133 of file LegacySort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LegacySortInternal(), and MoveTemp().
LegacySortBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE void Algo::LegacySortBy (RangeType && Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
The sort is unstable. This used to be Algo::Sort and is now considered legacy.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Definition at line 146 of file LegacySort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LegacySortInternal(), and MoveTemp().
LegacySortBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::LegacySortBy (RangeType && Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
The sort is unstable. This used to be Algo::Sort and is now considered legacy.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Predicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Definition at line 160 of file LegacySort.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LegacySortInternal(), and MoveTemp().
LevenshteinDistance()
template<typename RangeAType, typename RangeBType> int32 Algo::LevenshteinDistance (const RangeAType & RangeA, const RangeBType & RangeB) nodiscard
LevenshteinDistance return the number of edit operation we need to transform RangeA to RangeB.
Operation type are Add/Remove/substitution of range element. Base on Levenshtein algorithm.
Range[A/B]Type: Support [] operator and the range element must be able to be compare with == operator Support GetNum() functionality
Parameters
RangeA The first range of element
RangeB The second range of element
Returns
The number of operation to transform RangeA to RangeB
Definition at line 23 of file LevenshteinDistance.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), GetData(), GetNum(), and FMath::Min3().
Referenced by UnFbx::FFbxHelper::NameCompareWeight().
LowerBound() [1/2]
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::LowerBound (const RangeType & Range, const ValueType & Value) -> decltype(GetNum(Range)) nodiscard
Definition at line 97 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LowerBoundInternal(), and Value.
LowerBound() [2/2]
template<typename RangeType, typename ValueType, typename SortPredicateType> FORCEINLINE auto Algo::LowerBound (const RangeType & Range, const ValueType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Performs binary search, resulting in position of the first element >= Value using predicate.
Parameters
Range Range to search through, must be already sorted by SortPredicate
Value Value to look for
SortPredicate Predicate for sort comparison, defaults to <
Returns
Position of the first element >= Value, may be position after last element in range
Definition at line 92 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LowerBoundInternal(), and Value.
Referenced by BinarySearch(), Metasound::FTrigger::LookAhead(), UE::MovieScene::Optimize(), and FIndexedHandleManagerBase< TIndexedHandle, TIndexType, TSerialType, bOptimizeHandleReuse >::RemoveHandle().
LowerBoundBy() [1/2]
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::LowerBoundBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection) -> decltype(GetNum(Range)) nodiscard
Definition at line 118 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LowerBoundInternal(), Projection(), and Value.
LowerBoundBy() [2/2]
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto Algo::LowerBoundBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Performs binary search, resulting in position of the first element with projected value >= Value using predicate.
Parameters
Range Range to search through, must be already sorted by SortPredicate
Value Value to look for
Projection Functor or data member pointer, called via Invoke to compare to Value
SortPredicate Predicate for sort comparison, defaults to <
Returns
Position of the first element >= Value, may be position after last element in range
Definition at line 113 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::LowerBoundInternal(), Projection(), and Value.
Referenced by FMovieSceneChannelProxyData::AddInternal(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::AllocateMemoryForEmplace(), BinarySearchBy(), TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), TIoPriorityQueue< T >::FindOrAddQueueByPriority(), TIoPriorityQueue< T >::FindQueueByPriority(), TIoPriorityQueue< T >::FindQueueByPriority(), UE::FIoFileBlockRequestQueue::GetByOffset(), and TraceServices::PagedArrayAlgoImpl::LowerBoundInternal().
MaxElement() [1/2]
template<typename RangeType> FORCEINLINE auto Algo::MaxElement (RangeType && Range) -> decltype(AlgoImpl::MaxElementBy(Range, FIdentityFunctor(), TLess<>())) nodiscard
Returns a pointer to the maximum element in a range.
If the range contains multiple maximum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the maximum element in.
Returns
A pointer to the maximum element, or nullptr if the range was empty.
Definition at line 40 of file MaxElement.h.
References FORCEINLINE, and AlgoImpl::MaxElementBy().
MaxElement() [2/2]
template<typename RangeType, typename ComparatorType> FORCEINLINE auto Algo::MaxElement (RangeType && Range, ComparatorType Comp) -> decltype(AlgoImpl::MaxElementBy(Range, FIdentityFunctor(), MoveTemp(Comp))) nodiscard
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
If the range contains multiple maximum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the maximum element in.
Comp The comparator to use when comparing two elements.
Returns
A pointer to the maximum element, or nullptr if the range was empty.
Definition at line 55 of file MaxElement.h.
References FORCEINLINE, AlgoImpl::MaxElementBy(), and MoveTemp().
MaxElementBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE auto Algo::MaxElementBy (RangeType && Range, ProjectionType Proj) -> decltype(AlgoImpl::MaxElementBy(Range, MoveTemp(Proj), TLess<>())) nodiscard
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
If the range contains multiple maximum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the maximum element in.
Proj The projection to apply to the element to use for comparison.
Returns
A pointer to the maximum element, or nullptr if the range was empty.
Definition at line 70 of file MaxElement.h.
References FORCEINLINE, AlgoImpl::MaxElementBy(), and MoveTemp().
MaxElementBy() [2/2]
template<typename RangeType, typename ProjectionType, typename ComparatorType> FORCEINLINE auto Algo::MaxElementBy (RangeType && Range, ProjectionType Proj, ComparatorType Comp) -> decltype(AlgoImpl::MaxElementBy(Range, MoveTemp(Proj), MoveTemp(Comp))) nodiscard
Returns a pointer to the maximum element in a range with a user-defined binary comparator.
If the range contains multiple maximum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the maximum element in.
Proj The projection to apply to the element to use for comparison.
Comp The comparator to use when comparing two elements.
Returns
A pointer to the maximum element, or nullptr if the range was empty.
Definition at line 86 of file MaxElement.h.
References FORCEINLINE, AlgoImpl::MaxElementBy(), and MoveTemp().
MinElement() [1/2]
template<typename RangeType> FORCEINLINE auto Algo::MinElement (RangeType && Range) -> decltype(AlgoImpl::MinElementBy(Range, FIdentityFunctor(), TLess<>())) nodiscard
Returns a pointer to the minimum element in a range.
If the range contains multiple minimum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the minimum element in.
Returns
A pointer to the minimum element, or nullptr if the range was empty.
Definition at line 40 of file MinElement.h.
References FORCEINLINE, and AlgoImpl::MinElementBy().
Referenced by FCurveSnapMetrics::SnapOutput().
MinElement() [2/2]
template<typename RangeType, typename ComparatorType> FORCEINLINE auto Algo::MinElement (RangeType && Range, ComparatorType Comp) -> decltype(AlgoImpl::MinElementBy(Range, FIdentityFunctor(), MoveTemp(Comp))) nodiscard
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
If the range contains multiple minimum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the minimum element in.
Comp The comparator to use when comparing two elements.
Returns
A pointer to the minimum element, or nullptr if the range was empty.
Definition at line 55 of file MinElement.h.
References FORCEINLINE, AlgoImpl::MinElementBy(), and MoveTemp().
MinElementBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE auto Algo::MinElementBy (RangeType && Range, ProjectionType Proj) -> decltype(AlgoImpl::MinElementBy(Range, MoveTemp(Proj), TLess<>())) nodiscard
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
If the range contains multiple minimum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the minimum element in.
Proj The projection to apply to the element to use for comparison.
Returns
A pointer to the minimum element, or nullptr if the range was empty.
Definition at line 70 of file MinElement.h.
References FORCEINLINE, AlgoImpl::MinElementBy(), and MoveTemp().
MinElementBy() [2/2]
template<typename RangeType, typename ProjectionType, typename ComparatorType> FORCEINLINE auto Algo::MinElementBy (RangeType && Range, ProjectionType Proj, ComparatorType Comp) -> decltype(AlgoImpl::MinElementBy(Range, MoveTemp(Proj), MoveTemp(Comp))) nodiscard
Returns a pointer to the minimum element in a range with a user-defined binary comparator.
If the range contains multiple minimum elements, a pointer to the first one will be returned.
Parameters
Range The range to find the minimum element in.
Proj The projection to apply to the element to use for comparison.
Comp The comparator to use when comparing two elements.
Returns
A pointer to the minimum element, or nullptr if the range was empty.
Definition at line 86 of file MinElement.h.
References FORCEINLINE, AlgoImpl::MinElementBy(), and MoveTemp().
Mismatch() [1/2]
template<typename InputAType, typename InputBType> auto Algo::Mismatch (const InputAType & InputA, const InputBType & InputB) -> std::common_type_t<decltype(GetNum(InputA)), decltype(GetNum(InputB))> nodiscard constexpr
Returns the index at which two contiguous containers differ, using operator== to compare pairs of elements.
Parameters
InputA Container of elements that are used as the first argument to operator==.
InputB Container of elements that are used as the second argument to operator==.
Returns
The index at which the containers differ.
Definition at line 58 of file Mismatch.h.
References Algo::Private::Mismatch().
Mismatch() [2/2]
template<typename InputAType, typename InputBType, typename PredicateType> auto Algo::Mismatch (const InputAType & InputA, const InputBType & InputB, PredicateType Predicate) -> std::common_type_t<decltype(GetNum(InputA)), decltype(GetNum(InputB))> nodiscard constexpr
Returns the index at which two contiguous containers differ, using operator== to compare pairs of elements.
Parameters
InputA Container of elements that are used as the first argument to operator==.
InputB Container of elements that are used as the second argument to operator==.
Predicate Condition which returns true for elements which are deemed equal.
Returns
The index at which the containers differ.
Definition at line 73 of file Mismatch.h.
References Algo::Private::Mismatch(), MoveTemp(), and Predicate.
MismatchBy() [1/2]
template<typename InputAType, typename InputBType, typename ProjectionType> auto Algo::MismatchBy (const InputAType & InputA, const InputBType & InputB, ProjectionType Projection) -> std::common_type_t<decltype(GetNum(InputA)), decltype(GetNum(InputB))> nodiscard constexpr
Returns the index at which two contiguous containers differ, using operator== to compare pairs of projected elements.
Parameters
InputA Container of elements that are used as the first argument to operator==.
InputB Container of elements that are used as the second argument to operator==.
Projection Projection to apply to the elements before comparing them.
Returns
The index at which the containers differ.
Definition at line 88 of file Mismatch.h.
References Algo::Private::Mismatch(), MoveTemp(), and Projection().
MismatchBy() [2/2]
template<typename InputAType, typename InputBType, typename ProjectionType, typename PredicateType> auto Algo::MismatchBy (const InputAType & InputA, const InputBType & InputB, ProjectionType Projection, PredicateType Predicate) -> std::common_type_t<decltype(GetNum(InputA)), decltype(GetNum(InputB))> nodiscard constexpr
Returns the index at which two contiguous containers differ, using a predicate to compare pairs of projected elements.
Parameters
InputA Container of elements that are used as the first argument to the predicate.
InputB Container of elements that are used as the second argument to the predicate.
Projection Projection to apply to the elements before comparing them.
Predicate Condition which returns true for elements which are deemed equal.
Returns
The index at which the containers differ.
Definition at line 104 of file Mismatch.h.
References Algo::Private::Mismatch(), MoveTemp(), Predicate, and Projection().
NoneOf() [1/3]
template<typename RangeType> FORCEINLINE bool Algo::NoneOf (const RangeType & Range) nodiscard
Checks if no element in the range is truthy.
Parameters
Range The range to check.
Returns
true if no element is truthy, false otherwise.
Definition at line 20 of file NoneOf.h.
References FORCEINLINE.
Referenced by AnyOf(), AnyOf(), and AnyOf().
NoneOf() [2/3]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::NoneOf (const RangeType & Range, ProjectionType Projection) nodiscard
Checks if no projection of the elements in the range is truthy.
Parameters
Range The range to check.
Projection The projection to apply to each element.
Returns
true if none of the projections are truthy, false otherwise.
Definition at line 42 of file NoneOf.h.
References FORCEINLINE, Invoke(), and Projection().
NoneOf() [3/3]
template<typename RangeType, typename ProjectionType> FORCEINLINE bool Algo::NoneOf (const RangeType & Range, ProjectionType Projection, ENoRef NoRef) nodiscard
Checks if no projection of the elements in the range is truthy.
Should be used when the range iterator doesn't return a reference.
Parameters
Range The range to check.
Projection The projection to apply to each element.
Returns
true if none of the projections are truthy, false otherwise.
Definition at line 65 of file NoneOf.h.
References FORCEINLINE, Invoke(), NoRef, and Projection().
Partition() [1/2]
template<typename RangeType, typename UnaryPredicateType> FORCEINLINE auto Algo::Partition (RangeType && Range, UnaryPredicateType Predicate) -> decltype(GetNum(Range))
Rearranges the elements so that all the elements for which Predicate returns true precede all those for which it returns false.
(not stable)
Parameters
Range the range to sort
Predicate a unary predicate object
Returns
index of the first element in the second group
Definition at line 58 of file Partition.h.
References FORCEINLINE, GetData(), GetNum(), MoveTemp(), Partition(), and Predicate.
Partition() [2/2]
template<class T, typename IndexType, typename UnaryPredicate> IndexType Algo::Partition (T * Elements, const IndexType Num, UnaryPredicate Predicate)
Rearranges the elements so that all the elements for which Predicate returns true precede all those for which it returns false.
(not stable)
Parameters
First pointer to the first element
Num the number of items
Predicate unary predicate class
Returns
index of the first element in the second group
Definition at line 18 of file Partition.h.
References Exchange(), First, Last, Num, and Predicate.
Referenced by Partition().
RandomShuffle()
template<typename RangeType> void Algo::RandomShuffle (RangeType && Range)
Randomly shuffle a range of elements.
Parameters
Range Any contiguous container.
Definition at line 16 of file RandomShuffle.h.
References GetData(), GetNum(), Num, FMath::RandHelper64(), and Swap.
RemoveIf()
template<typename RangeType, typename Predicate> int32 Algo::RemoveIf (RangeType & Range, Predicate Pred) nodiscard
Moves all elements which do not match the predicate to the front of the range, while leaving all other elements is a constructed but unspecified state.
The elements which were not removed are not guaranteed to be kept in order (unstable).
Parameters
Range The range of elements to manipulate.
Pred A callable which maps elements to truthy values, specifying elements to be removed.
Returns
The index of the first element after those which were not removed.
Definition at line 21 of file RemoveIf.h.
References First, GetData(), GetNum(), Invoke(), Last, MoveTemp(), Predicate, and UE_PTRDIFF_TO_INT32.
Referenced by UE::Geometry::FMeshRegionOperator::BackPropropagate().
Replace()
template<typename RangeType, typename ValueType> FORCEINLINE void Algo::Replace (RangeType && Range, const ValueType & InOld, const ValueType & InNew)
Replaces all elements that compare equal to one value with a new value.
Parameters
Range The range to search and modify in-place.
InOld The value to search for.
InNew The value to copy in as a replacement.
Definition at line 18 of file Replace.h.
References FORCEINLINE, and Forward().
ReplaceIf()
template<typename RangeType, typename ValueType, typename PredicateType> FORCEINLINE void Algo::ReplaceIf (RangeType && Range, PredicateType InPred, const ValueType & InNew)
Replaces all elements that satisfy the predicate with the given value.
Parameters
Range The range to search and modify in-place.
InPred The predicate to apply to each element.
InNew The value to copy in as a replacement for each element satisfying the predicate.
Definition at line 37 of file Replace.h.
References FORCEINLINE, Forward(), and Invoke().
Reverse() [1/3]
template<typename ContainerType> FORCEINLINE void Algo::Reverse (ContainerType && Container)
Reverses a range.
Parameters
Container The container to reverse
Definition at line 51 of file Reverse.h.
References Container, FORCEINLINE, and AlgoImpl::Reverse().
Reverse() [2/3]
template<typename T> FORCEINLINE void Algo::Reverse (T * Array, int32 ArraySize)
Reverses a range.
Parameters
Array A pointer to the array to reverse
ArraySize The number of elements in the array.
Definition at line 40 of file Reverse.h.
References Array, FORCEINLINE, and AlgoImpl::Reverse().
Reverse() [3/3]
template<typename T, int32 ArraySize> FORCEINLINE void Algo::Reverse (T(&) Array[ArraySize])
Reverses a range.
Parameters
Array The array to reverse.
Definition at line 28 of file Reverse.h.
References Array, FORCEINLINE, and AlgoImpl::Reverse().
Referenced by UE::SequenceNavigator::INavigationToolItem::FindPath(), FConfigSection::MultiFind(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFind(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFindPointer(), TConstKeyIterator< FFixedObjectBindingID, FName >::MultiFindPointer(), STreeView< FRigVMSearchResult >::PopulatePinnedItems(), TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists(), UE::Geometry::FEdgeLoop::Reverse(), UE::Geometry::FEdgeSpan::Reverse(), and UE::Geometry::TPolygon2< double >::Reverse().
Rotate()
template<typename RangeType> FORCEINLINE int32 Algo::Rotate (RangeType && Range, int32 Count)
Rotates a given amount of elements from the front of the range to the end of the range.
Parameters
Range The range to rotate.
Num The number of elements to rotate from the front of the range.
Returns
The new index of the element that was previously at the start of the range.
Definition at line 59 of file Rotate.h.
References Count(), FORCEINLINE, GetData(), GetNum(), and AlgoImpl::RotateInternal().
Referenced by TAttributeArrayContainer< AttributeType >::InsertIntoElement().
SelectRandomWeightedBy()
template<typename RangeType, typename ProjectionType> FORCEINLINE auto Algo::SelectRandomWeightedBy (RangeType && Range, ProjectionType Proj) -> decltype(AlgoImpl::SelectRandomWeightedBy(Forward<RangeType>(Range), MoveTemp(Proj)))
Randomly select an element from a range of elements, weighted by a projection.
The chance of any element being chosen is its weight / the sum of all the weights in the range. Negative- or zero- weighted elements will not be chosen or count toward the total.
Parameters
Range The range to select from. Can be any iterable type.
Proj The projection to weight the random selection by. Should yield a numeric type.
Definition at line 61 of file SelectRandomWeighted.h.
References FORCEINLINE, Forward(), MoveTemp(), and AlgoImpl::SelectRandomWeightedBy().
Sort() [1/2]
template<typename RangeType> FORCEINLINE void Algo::Sort (RangeType && Range)
Sort a range of elements using its operator<.
The sort is unstable.
Parameters
Range The range to sort.
Definition at line 16 of file Sort.h.
References FORCEINLINE, Forward(), and IntroSort().
Referenced by ConvexHull2D::ComputeConvexHull(), UE::Graph::ConvertToGraph(), FFindReferencersArchive::FTargetObjectContainer::Freeze(), UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), RangedForIteratorType< FAnimNextTraitEventPtr >::Sort(), RangedForIteratorType< FAnimNextTraitEventPtr >::Sort(), TArrayView< FTransform >::Sort(), TArrayView< FTransform >::Sort(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Sort(), UE::TMultiUniqueLock< TLockType >::SortAndLock(), UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::SortElementsIfRequired(), FMaxErrorStatTracker< DataType, SortType, MaxItems >::StoreErrorStat(), TBVTree< InElementType, InAllocator >::Subdivide(), and UE_DEPRECATED().
Sort() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::Sort (RangeType && Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
The sort is unstable.
Parameters
Range The range to sort.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 28 of file Sort.h.
References FORCEINLINE, Forward(), IntroSort(), and MoveTemp().
SortBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE void Algo::SortBy (RangeType && Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
The sort is unstable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Definition at line 40 of file Sort.h.
References FORCEINLINE, Forward(), IntroSortBy(), and MoveTemp().
Referenced by TSortedMapPrivateFriend::Serialize(), and UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges().
SortBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::SortBy (RangeType && Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
The sort is unstable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Predicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Definition at line 53 of file Sort.h.
References FORCEINLINE, Forward(), IntroSortBy(), and MoveTemp().
StableRemoveIf()
template<typename RangeType, typename Predicate> int32 Algo::StableRemoveIf (RangeType && Range, Predicate Pred) nodiscard
Moves all elements which do not match the predicate to the front of the range, while leaving all other elements is a constructed but unspecified state.
The elements which were not removed are guaranteed to be kept in order (stable).
Parameters
Range The range of elements to manipulate.
Pred A callable which maps elements to truthy values, specifying elements to be removed.
Returns
The index of the first element after those which were not removed.
Definition at line 80 of file RemoveIf.h.
References First, GetData(), GetNum(), Invoke(), Last, MoveTemp(), Predicate, and UE_PTRDIFF_TO_INT32.
StableSort() [1/2]
template<typename RangeType> FORCEINLINE void Algo::StableSort (RangeType && Range)
Sort a range of elements using its operator<.
The sort is stable.
Parameters
Range The range to sort.
Definition at line 125 of file StableSort.h.
References FORCEINLINE, GetData(), GetNum(), and AlgoImpl::StableSortInternal().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::StableSort(), RangedForIteratorType< FAnimNextTraitEventPtr >::StableSort(), TArrayView< FTransform >::StableSort(), TArrayView< FTransform >::StableSort(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::StableSort().
StableSort() [2/2]
template<typename RangeType, typename PredicateType> FORCEINLINE void Algo::StableSort (RangeType && Range, PredicateType Pred)
Sort a range of elements using a user-defined predicate class.
The sort is stable.
Parameters
Range The range to sort.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 137 of file StableSort.h.
References FORCEINLINE, GetData(), GetNum(), MoveTemp(), and AlgoImpl::StableSortInternal().
StableSortBy() [1/2]
template<typename RangeType, typename ProjectionType> FORCEINLINE void Algo::StableSortBy (RangeType && Range, ProjectionType Proj)
Sort a range of elements by a projection using the projection's operator<.
The sort is stable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Definition at line 149 of file StableSort.h.
References FORCEINLINE, GetData(), GetNum(), MoveTemp(), and AlgoImpl::StableSortInternal().
StableSortBy() [2/2]
template<typename RangeType, typename ProjectionType, typename PredicateType> FORCEINLINE void Algo::StableSortBy (RangeType && Range, ProjectionType Proj, PredicateType Pred)
Sort a range of elements by a projection using a user-defined predicate class.
The sort is stable.
Parameters
Range The range to sort.
Proj The projection to sort by when applied to the element.
Predicate A binary predicate object, applied to the projection, used to specify if one element should precede another.
Definition at line 162 of file StableSort.h.
References FORCEINLINE, GetData(), GetNum(), MoveTemp(), and AlgoImpl::StableSortInternal().
TieTupleAdd()
template<typename... OutputTypes> Private::TTiedTupleAdder< OutputTypes... > Algo::TieTupleAdd (OutputTypes &... Outputs) nodiscard
Ties n objects with an Add function, usually containers, into one object with an Add function accepting an n-tuple that forwards the Add calls.
This is useful for algorithms such as Algo::Transform and Algo::Copy.
Example: TArray<int32> Out1; TArray<FString> Out2; TieTupleAdd(Out1, Out2).Add(MakeTuple(42, TEXT("42"))); // Out1 = { 42 }, Out2 = { "42" }
Parameters
Outputs Objects with an Add() function
Returns
An object with an Add function that will call Add on the tied elements
Definition at line 52 of file TiedTupleOutput.h.
TopologicalSort()
template<typename RangeType, typename GetElementDependenciesType> FORCEINLINE bool Algo::TopologicalSort (RangeType && UniqueRange, GetElementDependenciesType GetElementDependencies, ETopologicalSort Flags = ETopologicalSort::None)
Sorts the given range in leaf to root order: For every pair of elements (A,B) where SortedIndex(A) < SortedIndex(B), either B is not reachable from A, or A and B are mutually reachable.
Parameters
UniqueRange A range with element type T Type T must support GetTypeHash and copy+move constructors; T being pointertype is recommended. In/Out Variable, is sorted in place. Will be unmodified if function returns false.
GetElementDependencies A callable with prototype that is one of RangeType<T> GetElementDependencies(const T& Element) const RangeType<T>& GetElementDependencies(const T& Element) It should return the leaf-ward vertices of directed edges from the root-wards Element.
Flags ETopologicalSort::AllowCycles: If present, cycles will be allowed, with the caveat that the sorted ordering of MutuallyReachable vertices in the sorted range is arbitrary. If not present, the presence of a cycle will cause a failure to sort.
Returns
True if succeeded, false if failed due to cycles.
Definition at line 31 of file TopologicalSort.h.
References Flags, FORCEINLINE, Forward(), KahnTopologicalSort(), and None.
Transform()
template<typename InT, typename OutT, typename TransformT> FORCEINLINE void Algo::Transform (const InT & Input, OutT && Output, TransformT Trans)
Applies a transform to a range and stores the results into a container.
Parameters
Input Any iterable type
Output Container to hold the output
Trans Transformation operation
Definition at line 66 of file Algo/Transform.h.
References FORCEINLINE, Input, Invoke(), and Value.
Referenced by Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum(), Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum(), UE::Anim::AddTypedCustomAttribute(), DECLARE_MULTICAST_DELEGATE_OneParam(), UE::CurveEditor::Private::InvertKeyAttributes(), UE::CurveEditor::Private::InvertKeyPositions(), IAnimationDataController::SetTypedAttributeKeys(), and UE::SoftObjectPath::Private::UE_DEPRECATED().
TransformAccumulate() [1/2]
template<typename T, typename A, typename MapT> FORCEINLINE T Algo::TransformAccumulate (const A & Input, MapT MapOp, T Init) nodiscard
Sums a range by applying MapOp to each element, and then summing the results.
Parameters
Input Any iterable type
MapOp Mapping Operation
Init Initial value for the summation
Returns
the result of mapping and then summing all the elements of Input
Definition at line 90 of file Accumulate.h.
References A, FORCEINLINE, Init, Input, MoveTemp(), and TransformAccumulate().
TransformAccumulate() [2/2]
template<typename T, typename A, typename MapT, typename OpT> FORCEINLINE T Algo::TransformAccumulate (const A & Input, MapT MapOp, T Init, OpT Op) nodiscard
Sums a range by applying MapOp to each element, and then summing the results.
Parameters
Input Any iterable type
MapOp Mapping Operation
Init Initial value for the summation
Op Summing Operation (the default is TPlus<>)
Returns
the result of mapping and then summing all the elements of Input
Definition at line 70 of file Accumulate.h.
References A, FORCEINLINE, Init, Input, Invoke(), and MoveTemp().
Referenced by UE::Geometry::TMeshQueries< TriangleMeshType >::AverageEdgeLength(), FMeshDescription::GetNumVertexConnectedTriangles(), and TransformAccumulate().
TransformIf()
template<typename InT, typename OutT, typename PredicateT, typename TransformT> FORCEINLINE void Algo::TransformIf (const InT & Input, OutT && Output, PredicateT Predicate, TransformT Trans)
Conditionally applies a transform to a range and stores the results into a container.
Parameters
Input Any iterable type
Output Container to hold the output
Predicate Condition which returns true for elements that should be transformed and false for elements that should be skipped
Trans Transformation operation
Definition at line 47 of file Algo/Transform.h.
References FORCEINLINE, Input, Invoke(), Predicate, and Value.
Referenced by FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::FGridCellDataChunk(), IDetailLayoutBuilder::GetObjectsOfTypeBeingCustomized(), and IDetailLayoutBuilder::GetSelectedObjectsOfType().
UpperBound() [1/2]
template<typename RangeType, typename ValueType> FORCEINLINE auto Algo::UpperBound (const RangeType & Range, const ValueType & Value) -> decltype(GetNum(Range)) nodiscard
Definition at line 138 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::UpperBoundInternal(), and Value.
UpperBound() [2/2]
template<typename RangeType, typename ValueType, typename SortPredicateType> FORCEINLINE auto Algo::UpperBound (const RangeType & Range, const ValueType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Performs binary search, resulting in position of the first element > Value using predicate.
Parameters
Range Range to search through, must be already sorted by SortPredicate
Value Value to look for
SortPredicate Predicate for sort comparison, defaults to <
Returns
Position of the first element > Value, may be past end of range
Definition at line 133 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), AlgoImpl::UpperBoundInternal(), and Value.
Referenced by UE::MovieScene::Optimize().
UpperBoundBy() [1/2]
template<typename RangeType, typename ValueType, typename ProjectionType> FORCEINLINE auto Algo::UpperBoundBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection) -> decltype(GetNum(Range)) nodiscard
Definition at line 159 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), Projection(), AlgoImpl::UpperBoundInternal(), and Value.
UpperBoundBy() [2/2]
template<typename RangeType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto Algo::UpperBoundBy (const RangeType & Range, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(Range)) nodiscard
Performs binary search, resulting in position of the first element with projected value > Value using predicate.
Parameters
Range Range to search through, must be already sorted by SortPredicate
Value Value to look for
Projection Functor or data member pointer, called via Invoke to compare to Value
SortPredicate Predicate for sort comparison, defaults to <
Returns
Position of the first element > Value, may be past end of range
Definition at line 154 of file BinarySearch.h.
References FORCEINLINE, GetData(), GetNum(), Projection(), AlgoImpl::UpperBoundInternal(), and Value.
Referenced by UE::FIoFileBlockRequestQueue::Enqueue(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwardsDownSampled(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync(), TraceServices::TVariablePagedArray< ItemType >::FindItemChecked(), TRangeAllocator< FAllocatorModifier >::FChunk::Free(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetDepthAt(), TraceServices::GetElementRangeOverlappingGivenRange(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEventInfo(), Audio::GetInterpolationParametersAtTimestamp(), TraceServices::TVariablePagedArray< ItemType >::Insert(), UE::FIoFileBlockRequestQueue::Reprioritize(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().