Unreal Engine 5.6 C++ API: Metasound::Frontend::MetasoundDataTypeRegistrationPrivate Namespace Reference
Metasound::Frontend::MetasoundDataTypeRegistrationPrivate Namespace Reference
Data Structures
class FDataTypeRegistryEntryBase
struct HasRawParameterAssignmentOp
struct HasRawParameterAssignmentOp< T, decltype(&T::AssignRawParameter, void())>
struct TDataTypeProxyConstructorDeprecation
struct TExecutableDataTypeDeprecation
struct TLiteralArrayEnum
struct TLiteralArrayEnum< ELiteralType::Boolean >
struct TLiteralArrayEnum< ELiteralType::Float >
struct TLiteralArrayEnum< ELiteralType::Integer >
struct TLiteralArrayEnum< ELiteralType::None >
struct TLiteralArrayEnum< ELiteralType::String >
struct TLiteralArrayEnum< ELiteralType::UObjectProxy >
Functions
template<typename TFromDataType, typename TToDataType, typename std::enable_if< TIsAutoConvertible< TFromDataType, TToDataType >::Value, bool >::type = true>
void AttemptToRegisterConverter ()
template<typename TDataType, typename TEnableIf< TIsTransmittable< TDataType >::Value, bool >::Type = true>
void AttemptToRegisterSendAndReceiveNodes ()
template<typename TDataType, ELiteralType PreferredArgType, typename UClassToUse>
Frontend::FDataTypeRegistryInfo CreateDataTypeInfo ()
Creates the FDataTypeRegistryInfo for a data type.
template<typename TDataType>
TSharedPtr< Frontend::IEnumDataTypeInterface > GetEnumDataTypeInterface ()
Returns an IEnumDataTypeInterface pointer for the data type.
template<typename TDataType>
void RegisterConverterNodes ()
template<typename TDataType, ELiteralType PreferredArgType>
bool RegisterDataTypeArrayWithFrontend ()
Registers an array of a data type with the MetaSound Frontend.
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void>
bool RegisterDataTypeWithFrontendInternal ()
Registers a data type with the MetaSound Frontend.
Function Documentation
AttemptToRegisterConverter()
template<typename TFromDataType, typename TToDataType, typename std::enable_if< TIsAutoConvertible< TFromDataType, TToDataType >::Value, bool >::type = true> void Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::AttemptToRegisterConverter ()
Definition at line 140 of file MetasoundDataTypeRegistrationMacro.h.
References ensureAlways, Metasound::Frontend::INodeClassRegistry::Get(), Key, Metadata, RegisterConversionNode(), Metasound::Frontend::RegisterNode(), and Metasound::TEnableAutoConverterNodeRegistration< Type >::Value.
Referenced by RegisterConverterNodes().
AttemptToRegisterSendAndReceiveNodes()
template<typename TDataType, typename TEnableIf< TIsTransmittable< TDataType >::Value, bool >::Type = true> void Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::AttemptToRegisterSendAndReceiveNodes ()
Definition at line 121 of file MetasoundDataTypeRegistrationMacro.h.
References ensureAlways, Metasound::Frontend::RegisterNode(), and Metasound::TEnableTransmissionNodeRegistration< Type >::Value.
Referenced by RegisterDataTypeWithFrontendInternal().
CreateDataTypeInfo()
template<typename TDataType, ELiteralType PreferredArgType, typename UClassToUse> Frontend::FDataTypeRegistryInfo Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::CreateDataTypeInfo ()
Creates the FDataTypeRegistryInfo for a data type.
Template Parameters
TDataType - The data type to create info for.
PreferredArgType - The preferred constructor argument type to use when creating an instance of the data type.
UClassToUse - The preferred UObject class to use when constructing from an Audio::IProxyData.
Definition at line 189 of file MetasoundDataTypeRegistrationMacro.h.
References Metasound::Frontend::FDataTypeRegistryInfo::bIsArrayParseable, Metasound::Frontend::FDataTypeRegistryInfo::bIsArrayType, Metasound::Frontend::FDataTypeRegistryInfo::bIsBoolArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsBoolParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsConstructorType, Metasound::Frontend::FDataTypeRegistryInfo::bIsDefaultArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsDefaultParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsEnum, Metasound::TEnumTraits< T >::bIsEnum, Metasound::Frontend::FDataTypeRegistryInfo::bIsExplicit, Metasound::Frontend::FDataTypeRegistryInfo::bIsFloatArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsFloatParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsIntArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsIntParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsParsable, Metasound::TLiteralTraits< DataType >::bIsParsableFromAnyLiteralType, Metasound::TLiteralTraits< DataType >::bIsParseableFromAnyArrayLiteralType, Metasound::Frontend::FDataTypeRegistryInfo::bIsProxyArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsProxyParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsStringArrayParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsStringParsable, Metasound::Frontend::FDataTypeRegistryInfo::bIsTransmittable, Metasound::Frontend::FDataTypeRegistryInfo::bIsUniquePtrProxyArrayParsable_DEPRECATED, Metasound::Frontend::FDataTypeRegistryInfo::bIsUniquePtrProxyParsable_DEPRECATED, Metasound::Frontend::FDataTypeRegistryInfo::bIsVariable, Metasound::Frontend::FDataTypeRegistryInfo::DataTypeDisplayText, Metasound::Frontend::FDataTypeRegistryInfo::DataTypeName, Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metasound::Frontend::FDataTypeRegistryInfo::PreferredLiteralType, Metasound::Frontend::FDataTypeRegistryInfo::ProxyGeneratorClass, Metasound::Value, Metasound::TIsArrayType< DataType >::Value, Metasound::TIsConstructorVertexSupported< TDataType >::Value, Metasound::TIsExplicit< TDataType >::Value, Metasound::TIsParsable< DataType, ArgTypes >::Value, Metasound::TIsTransmittable< TDataType >::Value, and Metasound::TIsVariable< DataType >::Value.
Referenced by RegisterDataTypeWithFrontendInternal().
GetEnumDataTypeInterface()
template<typename TDataType> TSharedPtr< Frontend::IEnumDataTypeInterface > Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::GetEnumDataTypeInterface ()
Returns an IEnumDataTypeInterface pointer for the data type.
If the data type has no IEnumDataTypeInterface, the returned pointer will be invalid.
Template Parameters
TDataType - The data type to create the interface for.
Returns
A shared pointer to the IEnumDataTypeInterface. If the TDataType does not have an IEnumDataTypeInterface, returns an invalid pointer.
Definition at line 249 of file MetasoundDataTypeRegistrationMacro.h.
References Metasound::TEnumTraits< T >::DefaultValue, TArray< InElementType, InAllocatorType >::Emplace(), MakeShared(), Num, and TArray< InElementType, InAllocatorType >::Reserve().
Referenced by RegisterDataTypeWithFrontendInternal().
RegisterConverterNodes()
template<typename TDataType> void Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterConverterNodes ()
Definition at line 167 of file MetasoundDataTypeRegistrationMacro.h.
References AttemptToRegisterConverter().
Referenced by RegisterDataTypeWithFrontendInternal().
RegisterDataTypeArrayWithFrontend()
template<typename TDataType, ELiteralType PreferredArgType> bool Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeArrayWithFrontend ()
Registers an array of a data type with the MetaSound Frontend.
This allows an array of the data type to be used in Input, Output, Send and Receive nodes by informing the Frontend how to instantiate an instance.
Template Parameters
TDataType - The data type to register.
PreferredArgType - The preferred constructor argument type to use when creating an instance of the data type.
UClassToUse - The preferred UObject class to use when constructing from an Audio::IProxyDataPtr. If the type is not constructible with an Audio::IProxyDataPtr, then this should be void.
Returns
True on success, false on failure.
Definition at line 800 of file MetasoundDataTypeRegistrationMacro.h.
References Metasound::Frontend::RegisterArrayNodes(), RegisterDataTypeWithFrontendInternal(), and Metasound::TEnableAutoArrayTypeRegistration< Type >::Value.
RegisterDataTypeWithFrontendInternal()
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void> bool Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal ()
Registers a data type with the MetaSound Frontend.
This allows the data type to be used in Input and Output nodes by informing the Frontend how to instantiate an instance.
Template Parameters
TDataType - The data type to register.
PreferredArgType - The preferred constructor argument type to use when creating an instance of the data type.
UClassToUse - The preferred UObject class to use when constructing from an Audio::IProxyDataPtr. If the type is not constructible with an Audio::IProxyDataPtr, then this should be void.
Returns
True on success, false on failure.
Definition at line 373 of file MetasoundDataTypeRegistrationMacro.h.
References AttemptToRegisterSendAndReceiveNodes(), Metasound::TLiteralTraits< DataType >::bIsParsableFromAnyLiteralType, Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::TDataTypeProxyConstructorDeprecation< DataType >::bOnlySupportsDeprecatedProxyPtr, Metasound::TParamPackFixedArray< ElementType, NumInlineElements >::CopyToArray(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase::CreateConstructorOutputNode(), Metasound::FTransmissionDataChannelFactory::CreateDataChannel(), CreateDataTypeInfo(), Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), Metasound::TDataLiteralFactory< DataType, TDataReadReference< DataType > >::CreateExplicitArgs(), Metasound::TDataLiteralFactory< DataType, TDataValueReference< DataType > >::CreateExplicitArgs(), Metasound::TDataLiteralFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), Metasound::FOutputNode::CreateNodeClassMetadata(), Metasound::TInputNode< DataType, VertexAccess >::CreateNodeClassMetadata(), Metasound::TNodeFacade< MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType > >::CreateNodeClassMetadata(), Metasound::TNodeFacade< MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType > >::CreateNodeClassMetadata(), Metasound::TNodeFacade< MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType > >::CreateNodeClassMetadata(), Metasound::TVariableNode< DataType >::CreateNodeClassMetadata(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase::CreateOutputNode(), Display, ensure, ensureAlways, ensureAlwaysMsgf, Metasound::Frontend::GenerateClass(), Metasound::Frontend::IDataTypeRegistry::Get(), GetEnumDataTypeInterface(), Metasound::FVertexInterface::GetInputInterface(), Metasound::FNode::GetMetadata(), Metasound::GetMetasoundDataTypeName(), Metasound::GetMetasoundDataTypeString(), Metasound::FNodeInitData::InstanceID, Metasound::FNodeData::Interface, MakeShared(), MakeUnique(), MoveTemp(), Metasound::Read, Metasound::Reference, RegisterConverterNodes(), Metasound::Frontend::IDataTypeRegistry::RegisterDataType(), TEXT, UE_DEPRECATED, UE_LOG, Metasound::Value, Metasound::TIsArrayType< DataType >::Value, Metasound::TIsConstructorVertexSupported< TDataType >::Value, Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::HasRawParameterAssignmentOp< T, V >::value, Warning, and Metasound::Write.
Referenced by RegisterDataTypeArrayWithFrontend().