Unreal Engine 5.6 C++ API: FReadOnlyCVARCache Struct Reference
FReadOnlyCVARCache Struct Reference
#include "ReadOnlyCVARCache.h"
Static Public Member Functions
static bool AllowStaticLighting ()
static bool EnableLowQualityLightmaps ()
static bool EnablePointLightShadows (const FStaticShaderPlatform Platform)
static bool EnableStationarySkylight ()
static void Initialize ()
static bool MobileAllowDistanceFieldShadows ()
static bool MobileDeferredShading (EShaderPlatform Platform)
static int32 MobileEarlyZPass (EShaderPlatform Platform)
static bool MobileEnableMovableLightCSMShaderCulling ()
static bool MobileEnableMovableSpotlightsShadow (EShaderPlatform Platform)
static bool MobileEnableStaticAndCSMShadowReceivers ()
static int32 MobileForwardDecalLighting ()
static int32 MobileForwardLocalLights (EShaderPlatform Platform)
static int32 MobileForwardParticleLights (EShaderPlatform Platform)
static bool MobileHDR ()
static bool MobileSupportsGPUScene ()
static bool SupportSkyAtmosphere ()
Static Private Member Functions
static RENDERCORE_API bool MobileDeferredShadingIniValue (EShaderPlatform Platform)
static RENDERCORE_API int32 MobileEarlyZPassIniValue (EShaderPlatform Platform)
static RENDERCORE_API bool MobileEnableMovableSpotlightsShadowIniValue (EShaderPlatform Platform)
static RENDERCORE_API int32 MobileForwardLocalLightsIniValue (EShaderPlatform Platform)
static RENDERCORE_API bool MobileForwardParticleLightsIniValue (EShaderPlatform Platform)
Static Private Attributes
static RENDERCORE_API bool bAllowStaticLighting
static RENDERCORE_API bool bEnableLowQualityLightmaps
static RENDERCORE_API bool bEnablePointLightShadows
static RENDERCORE_API bool bEnableStationarySkylight
static RENDERCORE_API bool bInitialized
static RENDERCORE_API bool bMobileAllowDistanceFieldShadows
static RENDERCORE_API bool bMobileDeferredShadingValue
static RENDERCORE_API bool bMobileEnableMovableLightCSMShaderCulling
static RENDERCORE_API bool bMobileEnableMovableSpotlightsShadowValue
static RENDERCORE_API bool bMobileEnableStaticAndCSMShadowReceivers
static RENDERCORE_API bool bMobileForwardParticleLights
static RENDERCORE_API bool bMobileHDR
static RENDERCORE_API bool bMobileSupportsGPUScene
static RENDERCORE_API bool bSupportSkyAtmosphere
static RENDERCORE_API int32 MobileEarlyZPassValue
static RENDERCORE_API int32 MobileForwardDecalLightingValue
static RENDERCORE_API int32 MobileForwardLocalLightsValue
Detailed Description
Definition at line 13 of file ReadOnlyCVARCache.h.
Member Function Documentation
AllowStaticLighting()
bool FReadOnlyCVARCache::AllowStaticLighting () inline static
Definition at line 17 of file ReadOnlyCVARCache.h.
References bAllowStaticLighting, bInitialized, and checkSlow.
Referenced by IsStaticLightingAllowed().
EnableLowQualityLightmaps()
bool FReadOnlyCVARCache::EnableLowQualityLightmaps () inline static
Definition at line 45 of file ReadOnlyCVARCache.h.
References bEnableLowQualityLightmaps.
EnablePointLightShadows()
bool FReadOnlyCVARCache::EnablePointLightShadows (const FStaticShaderPlatform Platform) inline static
Definition at line 27 of file ReadOnlyCVARCache.h.
References bEnablePointLightShadows, FShaderPlatformCachedIniValue< Type >::Get(), MobileSupportsGPUScene(), Platform, and TEXT.
EnableStationarySkylight()
bool FReadOnlyCVARCache::EnableStationarySkylight () inline static
Definition at line 40 of file ReadOnlyCVARCache.h.
References bEnableStationarySkylight.
Initialize()
void FReadOnlyCVARCache::Initialize () static
MobileAllowDistanceFieldShadows()
bool FReadOnlyCVARCache::MobileAllowDistanceFieldShadows () inline static
Definition at line 76 of file ReadOnlyCVARCache.h.
References bMobileAllowDistanceFieldShadows.
MobileDeferredShading()
bool FReadOnlyCVARCache::MobileDeferredShading (EShaderPlatform Platform) inline static
Definition at line 127 of file ReadOnlyCVARCache.h.
References bMobileDeferredShadingValue, MobileDeferredShadingIniValue(), and Platform.
Referenced by IsMobileDeferredShadingEnabled().
MobileDeferredShadingIniValue()
RENDERCORE_API bool FReadOnlyCVARCache::MobileDeferredShadingIniValue (EShaderPlatform Platform) static private
References Platform.
Referenced by MobileDeferredShading().
MobileEarlyZPass()
int32 FReadOnlyCVARCache::MobileEarlyZPass (EShaderPlatform Platform) inline static
Definition at line 96 of file ReadOnlyCVARCache.h.
References MobileEarlyZPassIniValue(), MobileEarlyZPassValue, and Platform.
MobileEarlyZPassIniValue()
RENDERCORE_API int32 FReadOnlyCVARCache::MobileEarlyZPassIniValue (EShaderPlatform Platform) static private
References Platform.
Referenced by MobileEarlyZPass().
MobileEnableMovableLightCSMShaderCulling()
bool FReadOnlyCVARCache::MobileEnableMovableLightCSMShaderCulling () inline static
Definition at line 86 of file ReadOnlyCVARCache.h.
References bMobileEnableMovableLightCSMShaderCulling.
MobileEnableMovableSpotlightsShadow()
bool FReadOnlyCVARCache::MobileEnableMovableSpotlightsShadow (EShaderPlatform Platform) inline static
Definition at line 138 of file ReadOnlyCVARCache.h.
References bMobileEnableMovableSpotlightsShadowValue, MobileEnableMovableSpotlightsShadowIniValue(), and Platform.
MobileEnableMovableSpotlightsShadowIniValue()
RENDERCORE_API bool FReadOnlyCVARCache::MobileEnableMovableSpotlightsShadowIniValue (EShaderPlatform Platform) static private
References Platform.
Referenced by MobileEnableMovableSpotlightsShadow().
MobileEnableStaticAndCSMShadowReceivers()
bool FReadOnlyCVARCache::MobileEnableStaticAndCSMShadowReceivers () inline static
Definition at line 81 of file ReadOnlyCVARCache.h.
References bMobileEnableStaticAndCSMShadowReceivers.
MobileForwardDecalLighting()
int32 FReadOnlyCVARCache::MobileForwardDecalLighting () inline static
Definition at line 91 of file ReadOnlyCVARCache.h.
References MobileForwardDecalLightingValue.
MobileForwardLocalLights()
int32 FReadOnlyCVARCache::MobileForwardLocalLights (EShaderPlatform Platform) inline static
Definition at line 105 of file ReadOnlyCVARCache.h.
References MobileForwardLocalLightsIniValue(), MobileForwardLocalLightsValue, and Platform.
Referenced by MobileForwardEnableLocalLights().
MobileForwardLocalLightsIniValue()
RENDERCORE_API int32 FReadOnlyCVARCache::MobileForwardLocalLightsIniValue (EShaderPlatform Platform) static private
References Platform.
Referenced by MobileForwardLocalLights().
MobileForwardParticleLights()
int32 FReadOnlyCVARCache::MobileForwardParticleLights (EShaderPlatform Platform) inline static
Definition at line 116 of file ReadOnlyCVARCache.h.
References bMobileForwardParticleLights, MobileForwardParticleLightsIniValue(), and Platform.
Referenced by MobileForwardEnableParticleLights().
MobileForwardParticleLightsIniValue()
RENDERCORE_API bool FReadOnlyCVARCache::MobileForwardParticleLightsIniValue (EShaderPlatform Platform) static private
References Platform.
Referenced by MobileForwardParticleLights().
MobileHDR()
bool FReadOnlyCVARCache::MobileHDR () inline static
Definition at line 56 of file ReadOnlyCVARCache.h.
References bInitialized, bMobileHDR, and checkSlow.
Referenced by IsMobileHDR().
MobileSupportsGPUScene()
bool FReadOnlyCVARCache::MobileSupportsGPUScene () inline static
Definition at line 66 of file ReadOnlyCVARCache.h.
References bInitialized, bMobileSupportsGPUScene, and checkSlow.
Referenced by EnablePointLightShadows(), and MobileSupportsGPUScene().
SupportSkyAtmosphere()
bool FReadOnlyCVARCache::SupportSkyAtmosphere () inline static
Definition at line 50 of file ReadOnlyCVARCache.h.
References bSupportSkyAtmosphere.
Field Documentation
bAllowStaticLighting
RENDERCORE_API bool FReadOnlyCVARCache::bAllowStaticLighting static private
Definition at line 150 of file ReadOnlyCVARCache.h.
Referenced by AllowStaticLighting().
bEnableLowQualityLightmaps
RENDERCORE_API bool FReadOnlyCVARCache::bEnableLowQualityLightmaps static private
Definition at line 153 of file ReadOnlyCVARCache.h.
Referenced by EnableLowQualityLightmaps().
bEnablePointLightShadows
RENDERCORE_API bool FReadOnlyCVARCache::bEnablePointLightShadows static private
Definition at line 151 of file ReadOnlyCVARCache.h.
Referenced by EnablePointLightShadows().
bEnableStationarySkylight
RENDERCORE_API bool FReadOnlyCVARCache::bEnableStationarySkylight static private
Definition at line 152 of file ReadOnlyCVARCache.h.
Referenced by EnableStationarySkylight().
bInitialized
RENDERCORE_API bool FReadOnlyCVARCache::bInitialized static private
Definition at line 148 of file ReadOnlyCVARCache.h.
Referenced by AllowStaticLighting(), MobileHDR(), and MobileSupportsGPUScene().
bMobileAllowDistanceFieldShadows
RENDERCORE_API bool FReadOnlyCVARCache::bMobileAllowDistanceFieldShadows static private
Definition at line 158 of file ReadOnlyCVARCache.h.
Referenced by MobileAllowDistanceFieldShadows().
bMobileDeferredShadingValue
RENDERCORE_API bool FReadOnlyCVARCache::bMobileDeferredShadingValue static private
Definition at line 166 of file ReadOnlyCVARCache.h.
Referenced by MobileDeferredShading().
bMobileEnableMovableLightCSMShaderCulling
RENDERCORE_API bool FReadOnlyCVARCache::bMobileEnableMovableLightCSMShaderCulling static private
Definition at line 160 of file ReadOnlyCVARCache.h.
Referenced by MobileEnableMovableLightCSMShaderCulling().
bMobileEnableMovableSpotlightsShadowValue
RENDERCORE_API bool FReadOnlyCVARCache::bMobileEnableMovableSpotlightsShadowValue static private
Definition at line 167 of file ReadOnlyCVARCache.h.
Referenced by MobileEnableMovableSpotlightsShadow().
bMobileEnableStaticAndCSMShadowReceivers
RENDERCORE_API bool FReadOnlyCVARCache::bMobileEnableStaticAndCSMShadowReceivers static private
Definition at line 159 of file ReadOnlyCVARCache.h.
Referenced by MobileEnableStaticAndCSMShadowReceivers().
bMobileForwardParticleLights
RENDERCORE_API bool FReadOnlyCVARCache::bMobileForwardParticleLights static private
Definition at line 164 of file ReadOnlyCVARCache.h.
Referenced by MobileForwardParticleLights().
bMobileHDR
RENDERCORE_API bool FReadOnlyCVARCache::bMobileHDR static private
Definition at line 157 of file ReadOnlyCVARCache.h.
Referenced by MobileHDR().
bMobileSupportsGPUScene
RENDERCORE_API bool FReadOnlyCVARCache::bMobileSupportsGPUScene static private
Definition at line 161 of file ReadOnlyCVARCache.h.
Referenced by MobileSupportsGPUScene().
bSupportSkyAtmosphere
RENDERCORE_API bool FReadOnlyCVARCache::bSupportSkyAtmosphere static private
Definition at line 154 of file ReadOnlyCVARCache.h.
Referenced by SupportSkyAtmosphere().
MobileEarlyZPassValue
RENDERCORE_API int32 FReadOnlyCVARCache::MobileEarlyZPassValue static private
Definition at line 162 of file ReadOnlyCVARCache.h.
Referenced by MobileEarlyZPass().
MobileForwardDecalLightingValue
RENDERCORE_API int32 FReadOnlyCVARCache::MobileForwardDecalLightingValue static private
Definition at line 165 of file ReadOnlyCVARCache.h.
Referenced by MobileForwardDecalLighting().
MobileForwardLocalLightsValue
RENDERCORE_API int32 FReadOnlyCVARCache::MobileForwardLocalLightsValue static private
Definition at line 163 of file ReadOnlyCVARCache.h.
Referenced by MobileForwardLocalLights().
The documentation for this struct was generated from the following file:
ReadOnlyCVARCache.h