Unreal Engine 5.6 C++ API: TIndependentTickReplicator_SP< InModelDef > Class Template Reference
TIndependentTickReplicator_SP< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using ModelDef = InModelDef
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TClientRecvData< ModelDef > &ClientRecvState, TModelDataStore< ModelDef > *DataStore, FVariableTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, const FVariableTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, const TServerRecvData_Independent< ModelDef > &IndependentTickState, const FVariableTickState *VariableTickState)
Static Private Member Functions
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, int32 IndependentSimTime, int32 ServerTotalSimTime, int32 PendingFrame)
Detailed Description
template<typename InModelDef>
class TIndependentTickReplicator_SP< InModelDef >
Definition at line 625 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
ModelDef
template<typename InModelDef> using TIndependentTickReplicator_SP< InModelDef >::ModelDef = InModelDef
Definition at line 629 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename InModelDef> void TIndependentTickReplicator_SP< InModelDef >::NetRecv (const FNetSerializeParams & P, TClientRecvData< ModelDef > & ClientRecvState, TModelDataStore< ModelDef > * DataStore, FVariableTickState * TickState) inline static
Definition at line 634 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, TInstanceData< ModelDef >::CueDispatcher, INDEX_NONE, TClientRecvData< ModelDef >::InstanceIdx, TModelDataStore< ModelDef >::Instances, FVariableTickState::Interpolation, FVariableTickState::FInterpolationState::LatestRecvTimeMS, FMath::Max, TCommonReplicator_SP< InModelDef >::NetRecv(), npEnsure, npEnsureSlow, FVariableTickState::PendingFrame, FNetworkPredictionSerialization::SerializeTimeMS(), TClientRecvData< ModelDef >::SimTimeMS, and UE_NP_TRACE_NET_RECV.
NetSend() [1/3]
template<typename InModelDef> void TIndependentTickReplicator_SP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, const FVariableTickState * TickState) inline static
Definition at line 673 of file NetworkPredictionSerialization.h.
References FVariableTickState::Frames, ID, NetSend(), and FVariableTickState::PendingFrame.
Referenced by NetSend(), and NetSend().
NetSend() [2/3]
template<typename InModelDef> void TIndependentTickReplicator_SP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, const TServerRecvData_Independent< ModelDef > & IndependentTickState, const FVariableTickState * VariableTickState) inline static
Definition at line 680 of file NetworkPredictionSerialization.h.
References FVariableTickState::Frames, ID, NetSend(), npCheckSlow, FVariableTickState::PendingFrame, TServerRecvData_Independent< ModelDef >::PendingFrame, TModelDataStore< ModelDef >::ServerRecv_IndependentTick, and TServerRecvData_Independent< ModelDef >::TotalSimTimeMS.
NetSend() [3/3]
template<typename InModelDef> void TIndependentTickReplicator_SP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, int32 IndependentSimTime, int32 ServerTotalSimTime, int32 PendingFrame) inline static private
Definition at line 700 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, ID, Instance, TModelDataStore< ModelDef >::Instances, Interpolators, TCommonReplicator_SP< InModelDef >::NetSend(), npCheckSlow, FNetworkPredictionSerialization::SerializeTimeMS(), and SimulatedProxy.
The documentation for this class was generated from the following file:
NetworkPredictionSerialization.h