Unreal Engine 5.6 C++ API: UE::FPropertyPathNameTree::FKey Struct Reference
UE::FPropertyPathNameTree::FKey Struct Reference
Key corresponding to a FPropertyPathNameSegment with no index.
Data Fields
FName Name
FPropertyTypeName Type
Friends
void AppendHash (FBlake3 &Builder, const FKey &Key)
uint32 GetTypeHash (const FKey &Key)
bool operator< (const FKey &Lhs, const FKey &Rhs)
bool operator== (const FKey &Lhs, const FKey &Rhs)
Detailed Description
Key corresponding to a FPropertyPathNameSegment with no index.
Definition at line 27 of file PropertyPathNameTree.h.
Friends And Related Symbol Documentation
AppendHash
void AppendHash (FBlake3 & Builder, const FKey & Key) friend
Definition at line 51 of file PropertyPathNameTree.h.
References DispatchAppendHash(), and Key.
GetTypeHash
uint32 GetTypeHash (const FKey & Key) friend
Definition at line 46 of file PropertyPathNameTree.h.
References GetTypeHash, HashCombineFast(), and Key.
Referenced by GetTypeHash.
operator<
bool operator< (const FKey & Lhs, const FKey & Rhs) friend
Definition at line 37 of file PropertyPathNameTree.h.
References FName::Compare(), Name, and Type.
operator==
bool operator== (const FKey & Lhs, const FKey & Rhs) friend
Definition at line 32 of file PropertyPathNameTree.h.
References Name, and Type.
Field Documentation
Name
FName UE::FPropertyPathNameTree::FKey::Name
Definition at line 29 of file PropertyPathNameTree.h.
Referenced by operator<, and operator==.
Type
FPropertyTypeName UE::FPropertyPathNameTree::FKey::Type
Definition at line 30 of file PropertyPathNameTree.h.
Referenced by operator<, and operator==.
The documentation for this struct was generated from the following file:
PropertyPathNameTree.h