Unreal Engine 5.6 C++ API: IOSAppDelegate.h File Reference
IOSAppDelegate.h File Reference
import <UIKit/UIKit.h>
import <GameKit/GKGameCenterViewController.h>
import <AVFoundation/AVAudioSession.h>
#include "Delegates/Delegate.h"
#include "Logging/LogMacros.h"
#include "Containers/UnrealString.h"
import <UserNotifications/UserNotifications.h>
Data Structures
class FIOSCoreDelegates
struct FIOSCoreDelegates::FFilterDelegateAndHandle
class IOSAppDelegate
Namespaces
namespace FAppEntry
Macros
#define USE_MUTE_SWITCH_DETECTION 0
Enumerations
enum class EAudioFeature : uint8 {
Playback , Record , DoNotMixWithOthers , VoiceChat ,
UseReceiver , DisableBluetoothSpeaker , BluetoothMicrophone , BackgroundAudio ,
NumFeatures
}
Functions
DECLARE_DELEGATE_RetVal_OneParam (bool, FPushNotificationFilter, NSDictionary *)
DECLARE_LOG_CATEGORY_EXTERN (LogIOSAudioSession, Log, All)
void FAppEntry::DecrementAudioSuspendCounters ()
void FAppEntry::IncrementAudioSuspendCounters ()
void FAppEntry::Init ()
void InstallSignalHandlers ()
bool FAppEntry::IsStartupMoviePlaying ()
void LexFromString (EAudioFeature &OutFeature, const TCHAR *String)
FString LexToString (EAudioFeature Feature)
void FAppEntry::PlatformInit ()
void FAppEntry::PreInit (IOSAppDelegate *AppDelegate, UIApplication *Application)
void FAppEntry::ResetAudioContextResumeTime ()
void FAppEntry::RestartAudio ()
void FAppEntry::Resume (bool bIsInterrupt=false)
void FAppEntry::ResumeAudioContext ()
void FAppEntry::Shutdown ()
void FAppEntry::Suspend (bool bIsInterrupt=false)
void FAppEntry::SuspendTick ()
void FAppEntry::Tick ()
Variables
bool FAppEntry::gAppLaunchedWithLocalNotification
FString FAppEntry::gLaunchLocalNotificationActivationEvent
int32 FAppEntry::gLaunchLocalNotificationFireDate
Macro Definition Documentation
USE_MUTE_SWITCH_DETECTION
#define USE_MUTE_SWITCH_DETECTION 0
Definition at line 21 of file IOSAppDelegate.h.
Enumeration Type Documentation
EAudioFeature
enum class EAudioFeature : uint8 strong
Enumerator
Playback
Record
DoNotMixWithOthers
VoiceChat
UseReceiver
DisableBluetoothSpeaker
BluetoothMicrophone
BackgroundAudio
NumFeatures
Definition at line 25 of file IOSAppDelegate.h.
Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
DECLARE_DELEGATE_RetVal_OneParam (bool , FPushNotificationFilter , NSDictionary *)
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogIOSAudioSession , Log , All)
References All, and Log.
InstallSignalHandlers()
void InstallSignalHandlers ()
LexFromString()
void LexFromString (EAudioFeature & OutFeature, const TCHAR * String)
References String.
Referenced by TTypeFromString< T >::FromString(), SGraphPinNum< NumericType >::GetNumericValue(), SGraphPinNumSlider< NumericType >::GetNumericValue(), FAssetData::GetTagValue(), FAssetData::GetTagValueRef(), LexTryParseString(), LexTryParseString(), FBulkDataCookedIndex::ParseFromPath(), TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString(), and TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString_InContainer().
LexToString()
FString LexToString (EAudioFeature Feature)