Unreal Engine 5.6 C++ API: UE::Net::FNetIDVariant Class Reference
UE::Net::FNetIDVariant Class Reference
Simple variant wrapper to hold a generic or Iris network object ID (FNetworkGUID or FNetRefHandle).
#include "NetIDVariant.h"
Data Structures
struct FEmptyID
Placeholder to represent empty/unknown type.
Public Types
using FVariantType = TVariant<FEmptyID, FNetworkGUID>
Public Member Functions
FNetIDVariant ()=default
Constructs a variant holding an FEmptyID.
FNetIDVariant (FNetworkGUID NetGUID)
FVariantType GetVariant () const
Returns the stored TVariant.
bool IsValid () const
Returns whether the stored ID or handle is valid.
bool operator== (const FNetIDVariant &RHS) const
Equality comparison.
FString ToString () const
Output to string.
Private Attributes
FVariantType Variant
Friends
FArchive & operator<< (FArchive &Ar, FNetIDVariant &NetID)
Serializes or deserializes the stored ID or handle, suitable for networking.
Detailed Description
Simple variant wrapper to hold a generic or Iris network object ID (FNetworkGUID or FNetRefHandle).
Intended for transitioning systems that were using FNetworkGUID directly to Iris, not intended for general use.
Definition at line 21 of file NetIDVariant.h.
Member Typedef Documentation
FVariantType
using UE::Net::FNetIDVariant::FVariantType = TVariant<FEmptyID, FNetworkGUID>
Definition at line 30 of file NetIDVariant.h.
Constructor & Destructor Documentation
FNetIDVariant() [1/2]
UE::Net::FNetIDVariant::FNetIDVariant () default
Constructs a variant holding an FEmptyID.
Referenced by operator<<, and operator==().
FNetIDVariant() [2/2]
UE::Net::FNetIDVariant::FNetIDVariant (FNetworkGUID NetGUID) explicit
Member Function Documentation
GetVariant()
FVariantType UE::Net::FNetIDVariant::GetVariant () const inline
Returns the stored TVariant.
Definition at line 48 of file NetIDVariant.h.
References Variant.
Referenced by UE::Net::GetTypeHash().
IsValid()
bool UE::Net::FNetIDVariant::IsValid () const
Returns whether the stored ID or handle is valid.
operator==()
bool UE::Net::FNetIDVariant::operator== (const FNetIDVariant & RHS) const
Equality comparison.
References FNetIDVariant().
ToString()
FString UE::Net::FNetIDVariant::ToString () const
Output to string.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FNetIDVariant & NetID) friend
Serializes or deserializes the stored ID or handle, suitable for networking.
References FNetIDVariant(), and Ar.
Field Documentation
Variant
FVariantType UE::Net::FNetIDVariant::Variant private
Definition at line 60 of file NetIDVariant.h.
Referenced by GetVariant().
The documentation for this class was generated from the following file:
NetIDVariant.h