Unreal Engine 5.6 C++ API: ALevelSequenceMediaController Class Reference
ALevelSequenceMediaController Class Reference
#include "SequenceMediaController.h"
Public Member Functions
GENERATED_BODY () LEVELSEQUENCE_API ALevelSequenceMediaController(const FObjectInitializer &Init)
UFUNCTION () ALevelSequenceActor *GetSequence() const
Access this actor's Level Sequence Actor.
UFUNCTION () LEVELSEQUENCE_API void Play()
UFUNCTION () LEVELSEQUENCE_API void SynchronizeToServer(float DesyncThresholdSeconds
Forcibly synchronize the sequence to the server's position if it has diverged by more than the specified threshold.
UFUNCTION () UMediaComponent *GetMediaComponent() const
Access this actor's media component.
Public Member Functions inherited from IMovieSceneCustomClockSource
GENERATED_BODY () UFUNCTION() virtual void OnTick(float DeltaSeconds
Private Member Functions
LEVELSEQUENCE_API void Client_ConditionallyForceTime (float DesyncThresholdSeconds)
LEVELSEQUENCE_API void Client_Play ()
virtual LEVELSEQUENCE_API void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const
virtual LEVELSEQUENCE_API FFrameTime OnRequestCurrentTime (const FQualifiedFrameTime &InCurrentTime, float InPlayRate) override final
virtual LEVELSEQUENCE_API void OnStartPlaying (const FQualifiedFrameTime &InStartTime) override final
virtual LEVELSEQUENCE_API void OnStopPlaying (const FQualifiedFrameTime &InStopTime) override final
virtual LEVELSEQUENCE_API void OnTick (float DeltaSeconds, float InPlayRate) override final
UFUNCTION () LEVELSEQUENCE_API void OnRep_ServerStartTimeSeconds()
UPROPERTY () TObjectPtr< ALevelSequenceActor > Sequence
Pointer to the sequence actor to use for playback.
UPROPERTY () TObjectPtr< UMediaComponent > MediaComponent
Media component that contains the media player to synchronize with.
UPROPERTY ()) float ServerStartTimeSeconds
Replicated time at which the server started the sequence (taken from AGameStateBase::GetServerWorldTimeSeconds)
Private Attributes
double SequencePositionSeconds
Time to use for the sequence playback position.
Detailed Description
Definition at line 21 of file SequenceMediaController.h.
Member Function Documentation
Client_ConditionallyForceTime()
LEVELSEQUENCE_API void ALevelSequenceMediaController::Client_ConditionallyForceTime (float DesyncThresholdSeconds) private
References Client_ConditionallyForceTime().
Referenced by Client_ConditionallyForceTime().
Client_Play()
LEVELSEQUENCE_API void ALevelSequenceMediaController::Client_Play () private
References Client_Play().
Referenced by Client_Play().
GENERATED_BODY()
ALevelSequenceMediaController::GENERATED_BODY () const &
References Init.
GetLifetimeReplicatedProps()
virtual LEVELSEQUENCE_API void ALevelSequenceMediaController::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const private virtual
References GetLifetimeReplicatedProps().
Referenced by GetLifetimeReplicatedProps().
OnRequestCurrentTime()
virtual LEVELSEQUENCE_API FFrameTime ALevelSequenceMediaController::OnRequestCurrentTime (const FQualifiedFrameTime & InCurrentTime, float InPlayRate) final override private virtual
References OnRequestCurrentTime().
Referenced by OnRequestCurrentTime().
OnStartPlaying()
virtual LEVELSEQUENCE_API void ALevelSequenceMediaController::OnStartPlaying (const FQualifiedFrameTime & InStartTime) final override private virtual
References OnStartPlaying().
Referenced by OnStartPlaying().
OnStopPlaying()
virtual LEVELSEQUENCE_API void ALevelSequenceMediaController::OnStopPlaying (const FQualifiedFrameTime & InStopTime) final override private virtual
References OnStopPlaying().
Referenced by OnStopPlaying().
OnTick()
virtual LEVELSEQUENCE_API void ALevelSequenceMediaController::OnTick (float DeltaSeconds, float InPlayRate) final override private virtual
References OnTick().
Referenced by OnTick().
UFUNCTION() [1/5]
ALevelSequenceMediaController::UFUNCTION () const inline
Access this actor's Level Sequence Actor.
Definition at line 46 of file SequenceMediaController.h.
References Category.
UFUNCTION() [2/5]
ALevelSequenceMediaController::UFUNCTION () private
References UFUNCTION().
UFUNCTION() [3/5]
ALevelSequenceMediaController::UFUNCTION ()
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/5]
ALevelSequenceMediaController::UFUNCTION ()
Forcibly synchronize the sequence to the server's position if it has diverged by more than the specified threshold.
References Category.
UFUNCTION() [5/5]
ALevelSequenceMediaController::UFUNCTION () const inline
Access this actor's media component.
Definition at line 37 of file SequenceMediaController.h.
References Category, and UFUNCTION().
UPROPERTY() [1/3]
ALevelSequenceMediaController::UPROPERTY () private
Pointer to the sequence actor to use for playback.
References Category, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/3]
ALevelSequenceMediaController::UPROPERTY () private
Media component that contains the media player to synchronize with.
References Category, and UPROPERTY().
UPROPERTY() [3/3]
ALevelSequenceMediaController::UPROPERTY () private
Replicated time at which the server started the sequence (taken from AGameStateBase::GetServerWorldTimeSeconds)
References Category, meta, and UPROPERTY().
Field Documentation
SequencePositionSeconds
double ALevelSequenceMediaController::SequencePositionSeconds private
Time to use for the sequence playback position.
Definition at line 93 of file SequenceMediaController.h.
The documentation for this class was generated from the following file:
SequenceMediaController.h