Unreal Engine 5.6 C++ API: FObjectKey Struct Reference
FObjectKey Struct Reference
FObjectKey is an immutable, copyable key which can be used to uniquely identify an object for the lifetime of the application.
#include "ObjectKey.h"
Public Member Functions
FORCEINLINE FObjectKey ()
Default constructor.
FORCEINLINE FObjectKey (const UObject *Object)
Construct from an object pointer.
template<typename U UE_REQUIRES>
FORCEINLINE FObjectKey (U Object)
FWeakObjectPtr GetWeakObjectPtr () const
Create an FWeakObjectPtr that points to the same object as this key.
FORCEINLINE bool operator!= (const FObjectKey &Other) const
Compare this key with another.
FORCEINLINE bool operator< (const FObjectKey &Other) const
Compare this key with another.
FORCEINLINE bool operator<= (const FObjectKey &Other) const
Compare this key with another.
FORCEINLINE bool operator== (const FObjectKey &Other) const
Compare this key with another.
FORCEINLINE bool operator> (const FObjectKey &Other) const
Compare this key with another.
FORCEINLINE bool operator>= (const FObjectKey &Other) const
Compare this key with another.
UObject * ResolveObjectPtr () const
Attempt to access the object from which this key was constructed.
UObject * ResolveObjectPtrEvenIfGarbage () const
Attempt to access the object from which this key was constructed, even if it is marked as Garbage.
UObject * ResolveObjectPtrEvenIfUnreachable () const
Attempt to access the object from which this key was constructed, even if it is RF_PendingKill or RF_Unreachable.
UE_DEPRECATED (5.4, "Use ResolveObjectPtrEvenIfGarbage().") UObject *ResolveObjectPtrEvenIfPendingKill() const
Private Member Functions
FObjectKey (int32 Index, int32 Serial)
Private Attributes
int32 ObjectIndex
int32 ObjectSerialNumber
Friends
uint32 GetTypeHash (const FObjectKey &Key)
Hash function.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FObjectKey &Key)
FObjectKey UE::CoreUObject::Private::MakeObjectKey (int32 ObjectIndex, int32 ObjectSerialNumber)
Detailed Description
FObjectKey is an immutable, copyable key which can be used to uniquely identify an object for the lifetime of the application.
Definition at line 18 of file ObjectKey.h.
Constructor & Destructor Documentation
FObjectKey() [1/4]
FORCEINLINE FObjectKey::FObjectKey () inline
Default constructor.
Definition at line 22 of file ObjectKey.h.
References Core, FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Private.
Referenced by FObjectKey(), GetTypeHash, operator!=(), operator<(), operator<<, operator<=(), operator==(), operator>(), operator>=(), and UE::CoreUObject::Private::MakeObjectKey.
FObjectKey() [2/4]
FORCEINLINE FObjectKey::FObjectKey (const UObject * Object) inline
Construct from an object pointer.
Definition at line 29 of file ObjectKey.h.
References Core, FORCEINLINE, Object, ObjectIndex, ObjectSerialNumber, and Private.
FObjectKey() [3/4]
template<typename U UE_REQUIRES> FORCEINLINE FObjectKey::FObjectKey (U Object) inline
Definition at line 47 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ImplicitConv(), and Object.
FObjectKey() [4/4]
FObjectKey::FObjectKey (int32 Index, int32 Serial) inline private
Definition at line 209 of file ObjectKey.h.
References ObjectIndex, and ObjectSerialNumber.
Member Function Documentation
GetWeakObjectPtr()
FWeakObjectPtr FObjectKey::GetWeakObjectPtr () const inline
Create an FWeakObjectPtr that points to the same object as this key.
Returns
The new FWeakObjectPtr.
Definition at line 178 of file ObjectKey.h.
References ObjectIndex, FWeakObjectPtr::ObjectIndex, ObjectSerialNumber, and FWeakObjectPtr::ObjectSerialNumber.
operator!=()
FORCEINLINE bool FObjectKey::operator!= (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 63 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
operator<()
FORCEINLINE bool FObjectKey::operator< (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 73 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
operator<=()
FORCEINLINE bool FObjectKey::operator<= (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 83 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
operator==()
FORCEINLINE bool FObjectKey::operator== (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 53 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
operator>()
FORCEINLINE bool FObjectKey::operator> (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 93 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
operator>=()
FORCEINLINE bool FObjectKey::operator>= (const FObjectKey & Other) const inline
Compare this key with another.
Definition at line 103 of file ObjectKey.h.
References FObjectKey(), FORCEINLINE, ObjectIndex, ObjectSerialNumber, and Other.
ResolveObjectPtr()
UObject * FObjectKey::ResolveObjectPtr () const inline
Attempt to access the object from which this key was constructed.
Returns
The object used to construct this key, or nullptr if it is no longer valid
Definition at line 126 of file ObjectKey.h.
References FWeakObjectPtr::Get(), ObjectIndex, FWeakObjectPtr::ObjectIndex, ObjectSerialNumber, and FWeakObjectPtr::ObjectSerialNumber.
Referenced by FFolder::GetRootObjectPtr(), and UE::MovieScene::FGarbageTraits::IsGarbage().
ResolveObjectPtrEvenIfGarbage()
UObject * FObjectKey::ResolveObjectPtrEvenIfGarbage () const inline
Attempt to access the object from which this key was constructed, even if it is marked as Garbage.
Returns
The object used to construct this key, or nullptr if it is no longer valid
Definition at line 141 of file ObjectKey.h.
References FWeakObjectPtr::Get(), ObjectIndex, FWeakObjectPtr::ObjectIndex, ObjectSerialNumber, and FWeakObjectPtr::ObjectSerialNumber.
Referenced by UE_DEPRECATED().
ResolveObjectPtrEvenIfUnreachable()
UObject * FObjectKey::ResolveObjectPtrEvenIfUnreachable () const inline
Attempt to access the object from which this key was constructed, even if it is RF_PendingKill or RF_Unreachable.
Returns
The object used to construct this key, or nullptr if it is no longer valid
Definition at line 163 of file ObjectKey.h.
References FWeakObjectPtr::GetEvenIfUnreachable(), ObjectIndex, FWeakObjectPtr::ObjectIndex, ObjectSerialNumber, and FWeakObjectPtr::ObjectSerialNumber.
UE_DEPRECATED()
FObjectKey::UE_DEPRECATED (5. 4, "Use ResolveObjectPtrEvenIfGarbage().") const inline
Definition at line 153 of file ObjectKey.h.
References ResolveObjectPtrEvenIfGarbage().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FObjectKey & Key) friend
Hash function.
Definition at line 190 of file ObjectKey.h.
References FObjectKey(), GetTypeHash, HashCombine(), and Key.
Referenced by GetTypeHash.
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FObjectKey & Key) friend
Definition at line 112 of file ObjectKey.h.
References FObjectKey(), Ar, check, FORCEINLINE, and Key.
UE::CoreUObject::Private::MakeObjectKey
FObjectKey UE::CoreUObject::Private::MakeObjectKey (int32 ObjectIndex, int32 ObjectSerialNumber) friend
References FObjectKey(), ObjectIndex, and ObjectSerialNumber.
Field Documentation
ObjectIndex
int32 FObjectKey::ObjectIndex private
Definition at line 218 of file ObjectKey.h.
Referenced by FObjectKey(), FObjectKey(), FObjectKey(), GetWeakObjectPtr(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), ResolveObjectPtr(), ResolveObjectPtrEvenIfGarbage(), ResolveObjectPtrEvenIfUnreachable(), and UE::CoreUObject::Private::MakeObjectKey.
ObjectSerialNumber
int32 FObjectKey::ObjectSerialNumber private
Definition at line 219 of file ObjectKey.h.
Referenced by FObjectKey(), FObjectKey(), FObjectKey(), GetWeakObjectPtr(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), ResolveObjectPtr(), ResolveObjectPtrEvenIfGarbage(), ResolveObjectPtrEvenIfUnreachable(), and UE::CoreUObject::Private::MakeObjectKey.
The documentation for this struct was generated from the following file:
ObjectKey.h