Unreal Engine 5.6 C++ API: FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck > Struct Template Reference
FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck > Struct Template Reference
Generic graph A* implementation.
#include "GraphAStar.h"
Data Structures
struct CQueryGetCostLimit
struct CQueryGetHeuristicCost
struct CQueryGetNeighbour
struct CQueryGetNeighbourCount
struct CQueryGetNeighbourCountV2
struct CQueryGetTraversalCost
struct CQueryHasExceededCostLimit
struct CQueryHasReachMaxSearchNodes
struct CQuerySetPathInfo
struct CQueryShouldFailOnInvalidEndNode
struct CQueryShouldIgnoreClosedNodes
struct CQueryShouldIncludeStartNodeInPath
struct FNodePool
struct FNodeSorter
struct FOpenList
Public Types
typedef TGraph::FNodeRef FGraphNodeRef
using FIndexArray = TArray<int32, FRangeChecklessAllocator<DoRangeCheck>>
using FNodeArray = TArray<FSearchNode, FRangeChecklessAllocator<DoRangeCheck>>
using FNodeMap = TMap<FGraphNodeRef, int32, FRangeChecklessSetAllocator>
using FRangeChecklessSetAllocator = TSetAllocator<TSparseArrayAllocator<FRangeChecklessAllocator<DoRangeCheck>, TInlineAllocator<4, FRangeChecklessAllocator<DoRangeCheck>>>, TInlineAllocator<1, FRangeChecklessAllocator<DoRangeCheck>>>
typedef TSearchNode FSearchNode
Public Member Functions
FGraphAStar (const TGraph &InGraph)
template<typename TQueryFilter, typename TResultPathInfo = TArray<FGraphNodeRef>>
EGraphAStarResult FindPath (const FSearchNode &StartNode, const FSearchNode &EndNode, const TQueryFilter &Filter, TResultPathInfo &OutPath)
Performs the actual search.
template<typename TQueryFilter>
EGraphAStarResult FloodFrom (const FSearchNode &StartNode, const TQueryFilter &Filter)
Floods node pool until running out of either free nodes or open set.
template<typename TQueryFilter>
bool HasReachMaxSearchNodes (const TQueryFilter &Filter) const
template<typename TQueryFilter>
FORCEINLINE_DEBUGGABLE bool ProcessSingleNode (const FSearchNode &EndNode, const bool bIsBound, const TQueryFilter &Filter, int32 &OutBestNodeIndex, FVector::FReal &OutBestNodeCost)
Single run of A* loop: get node from open set and process neighbors returns true if loop should be continued.
template<typename TQueryFilter>
UE_DEPRECATED (5.1, "Please use ProcessSingleNode() taking FVector::FReal& OutBestNodeCost instead!") FORCEINLINE_DEBUGGABLE bool ProcessSingleNode(const FSearchNode &EndNode
Single run of A* loop: get node from open set and process neighbors returns true if loop should be continued.
Static Public Member Functions
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetCostLimit (const TemplateClass &Obj)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetHeuristicCost (const TemplateClass &Obj, const FSearchNode &Param1, const FSearchNode &Param2)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetNeighbour (const TemplateClass &Obj, const FSearchNode &Param1, const int32 Param2)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetNeighbourCount (const TemplateClass &Obj, const FGraphNodeRef Param1)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetNeighbourCountV2 (const TemplateClass &Obj, const FSearchNode &Param1)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) GetTraversalCost (const TemplateClass &Obj, const FSearchNode &Param1, const FSearchNode &Param2)
template<typename TemplateClass>
static FORCEINLINE bool HasExceededCostLimit (const TemplateClass &Obj, FVector::FReal Cost)
template<typename TemplateClass>
static FORCEINLINE bool HasReachMaxSearchNodes (const TemplateClass &Obj, uint32 NodeCount)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) SetPathInfo (TemplateClass &Obj, const int32 Param1, const FSearchNode &Param2)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) ShouldFailOnInvalidEndNode (const TemplateClass &Obj)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) ShouldIgnoreClosedNodes (const TemplateClass &Obj)
template<typename TemplateClass>
static FORCEINLINE decltype(auto) ShouldIncludeStartNodeInPath (const TemplateClass &Obj)
Data Fields
const bool bIsBound
const bool bSucess = ProcessSingleNode(EndNode, bIsBound, Filter, OutBestNodeIndex, BestNodeCost)
return bSucess
const bool const TQueryFilter & Filter
const TGraph & Graph
FNodePool NodePool
FNodeSorter NodeSorter
FOpenList OpenList
const bool const TQueryFilter int32 float & OutBestNodeCost
OutBestNodeCost = UE_REAL_TO_FLOAT_CLAMPED_MAX(BestNodeCost)
const bool const TQueryFilter int32 & OutBestNodeIndex
Detailed Description
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false>
struct FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >
Generic graph A* implementation.
TGraph holds graph representation. Needs to implement functions: bool IsValidRef(FNodeRef NodeRef) const; - returns whether given node identyfication is correct FNodeRef GetNeighbour(const FSearchNode& NodeRef, const int32 NeighbourIndex) const; - returns neighbour ref
it also needs to specify node type FNodeRef - type used as identification of nodes in the graph
TQueryFilter (FindPath's parameter) filter class is what decides which graph edges can be used and at what cost. It needs to implement following functions: FVector::FReal GetHeuristicScale() const; - used as GetHeuristicCost's multiplier FVector::FReal GetHeuristicCost(const FSearchNode& StartNode, const FSearchNode& EndNode) const; - estimate of cost from StartNode to EndNode from a search node FVector::FReal GetTraversalCost(const FSearchNode& StartNode, const FSearchNode& EndNode) const; - real cost of traveling from StartNode directly to EndNode from a search node bool IsTraversalAllowed(const FNodeRef NodeA, const FNodeRef NodeB) const; - whether traversing given edge is allowed from a NodeRef bool WantsPartialSolution() const; - whether to accept solutions that do not reach the goal
// Backward compatible methods, please use the FSearchNode version. If the FSearchNode version are implemented, these methods will not be called at all. FNodeRef GetNeighbour(const FNodeRef NodeRef, const int32 NeighbourIndex) const; - returns neighbour ref FVector::FReal GetHeuristicCost(const FNodeRef StartNodeRef, const FNodeRef EndNodeRef) const; - estimate of cost from StartNode to EndNode from a NodeRef FVector::FReal GetTraversalCost(const FNodeRef StartNodeRef, const FNodeRef EndNodeRef) const; - real cost of traveling from StartNode directly to EndNode from a NodeRef
// Optionally implemented methods to parameterize the search int32 GetNeighbourCount(FNodeRef NodeRef) const; - returns number of neighbours that the graph node identified with NodeRef has, it is ok if not implemented, the logic will stop calling GetNeighbour once it received an invalid noderef bool ShouldIgnoreClosedNodes() const; - whether to revisit closed node or not bool ShouldIncludeStartNodeInPath() const; - whether to put the start node in the resulting path bool ShouldFailOnInvalidEndNode() const; - whether to early out if the end node is not valid int32 GetMaxSearchNodes() const; - whether to limit the number of search nodes to a maximum FVector::FReal GetCostLimit() const - whether to limit the search to a maximum cost
Definition at line 190 of file GraphAStar.h.
Member Typedef Documentation
FGraphNodeRef
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> typedef TGraph::FNodeRef FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FGraphNodeRef
Definition at line 192 of file GraphAStar.h.
FIndexArray
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> using FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FIndexArray = TArray<int32, FRangeChecklessAllocator<DoRangeCheck>>
Definition at line 198 of file GraphAStar.h.
FNodeArray
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> using FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FNodeArray = TArray<FSearchNode, FRangeChecklessAllocator<DoRangeCheck>>
Definition at line 195 of file GraphAStar.h.
FNodeMap
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> using FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FNodeMap = TMap<FGraphNodeRef, int32, FRangeChecklessSetAllocator>
Definition at line 197 of file GraphAStar.h.
FRangeChecklessSetAllocator
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> using FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FRangeChecklessSetAllocator = TSetAllocator<TSparseArrayAllocator<FRangeChecklessAllocator<DoRangeCheck>, TInlineAllocator<4, FRangeChecklessAllocator<DoRangeCheck>>>, TInlineAllocator<1, FRangeChecklessAllocator<DoRangeCheck>>>
Definition at line 196 of file GraphAStar.h.
FSearchNode
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> typedef TSearchNode FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FSearchNode
Definition at line 193 of file GraphAStar.h.
Constructor & Destructor Documentation
FGraphAStar()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FGraphAStar (const TGraph & InGraph) inline
Definition at line 345 of file GraphAStar.h.
References FGraphAStar(), and Graph.
Referenced by FGraphAStar().
Member Function Documentation
FindPath()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TQueryFilter, typename TResultPathInfo = TArray<FGraphNodeRef>> EGraphAStarResult FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FindPath (const FSearchNode & StartNode, const FSearchNode & EndNode, const TQueryFilter & Filter, TResultPathInfo & OutPath) inline
Performs the actual search.
Parameters
[OUT] OutPath - on successful search contains a sequence of graph nodes representing solution optimal within given constraints
Definition at line 504 of file GraphAStar.h.
References bIsBound, Display, ensure, Filter, GetHeuristicCost(), GoalUnreachable, Graph, INDEX_NONE, InfiniteLoop, NodePool, OpenList, ProcessSingleNode(), SearchFail, SearchSuccess, SetPathInfo(), ShouldFailOnInvalidEndNode(), ShouldIncludeStartNodeInPath(), TEXT, and UE_GRAPH_ASTAR_LOG.
FloodFrom()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TQueryFilter> EGraphAStarResult FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FloodFrom (const FSearchNode & StartNode, const TQueryFilter & Filter) inline
Floods node pool until running out of either free nodes or open set.
Definition at line 609 of file GraphAStar.h.
References bIsBound, Filter, Graph, INDEX_NONE, NodePool, OpenList, ProcessSingleNode(), SearchFail, and SearchSuccess.
GetCostLimit()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetCostLimit (const TemplateClass & Obj) inline static
Definition at line 337 of file GraphAStar.h.
References DECLARE_OPTIONALLY_IMPLEMENTED_TEMPLATE_CLASS_FUNCTION_CONST, FVector, GetCostLimit(), and Max.
Referenced by GetCostLimit(), HasExceededCostLimit(), and ProcessSingleNode().
GetHeuristicCost()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetHeuristicCost (const TemplateClass & Obj, const FSearchNode & Param1, const FSearchNode & Param2) inline static
Definition at line 333 of file GraphAStar.h.
References DECLARE_OPTIONALLY_IMPLEMENTED_TEMPLATE_CLASS_FUNCTION_2PARAMS_CONST, FVector, and GetHeuristicCost().
Referenced by FindPath(), GetHeuristicCost(), and ProcessSingleNode().
GetNeighbour()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetNeighbour (const TemplateClass & Obj, const FSearchNode & Param1, const int32 Param2) inline static
Definition at line 329 of file GraphAStar.h.
References GetNeighbour().
Referenced by GetNeighbour(), and ProcessSingleNode().
GetNeighbourCount()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetNeighbourCount (const TemplateClass & Obj, const FGraphNodeRef Param1) inline static
Definition at line 327 of file GraphAStar.h.
References GetNeighbourCount(), and NO_COUNT.
Referenced by GetNeighbourCount().
GetNeighbourCountV2()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetNeighbourCountV2 (const TemplateClass & Obj, const FSearchNode & Param1) inline static
Definition at line 328 of file GraphAStar.h.
References GetNeighbourCountV2().
Referenced by GetNeighbourCountV2(), and ProcessSingleNode().
GetTraversalCost()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::GetTraversalCost (const TemplateClass & Obj, const FSearchNode & Param1, const FSearchNode & Param2) inline static
Definition at line 332 of file GraphAStar.h.
References GetTraversalCost().
Referenced by GetTraversalCost(), and ProcessSingleNode().
HasExceededCostLimit()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::HasExceededCostLimit (const TemplateClass & Obj, FVector::FReal Cost) inline static
Definition at line 340 of file GraphAStar.h.
References DECLARE_OPTIONALLY_IMPLEMENTED_TEMPLATE_CLASS_FUNCTION_CUSTOM, FVector, GetCostLimit(), and HasExceededCostLimit().
Referenced by HasExceededCostLimit(), and ProcessSingleNode().
HasReachMaxSearchNodes() [1/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::HasReachMaxSearchNodes (const TemplateClass & Obj, uint32 NodeCount) inline static
Definition at line 339 of file GraphAStar.h.
References DECLARE_OPTIONALLY_IMPLEMENTED_TEMPLATE_CLASS_FUNCTION_CUSTOM, and HasReachMaxSearchNodes().
Referenced by HasReachMaxSearchNodes(), HasReachMaxSearchNodes(), and ProcessSingleNode().
HasReachMaxSearchNodes() [2/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TQueryFilter> bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::HasReachMaxSearchNodes (const TQueryFilter & Filter) const inline
Definition at line 647 of file GraphAStar.h.
References Filter, HasReachMaxSearchNodes(), and NodePool.
ProcessSingleNode()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TQueryFilter> FORCEINLINE_DEBUGGABLE bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::ProcessSingleNode (const FSearchNode & EndNode, const bool bIsBound, const TQueryFilter & Filter, int32 & OutBestNodeIndex, FVector::FReal & OutBestNodeCost) inline
Single run of A* loop: get node from open set and process neighbors returns true if loop should be continued.
Definition at line 371 of file GraphAStar.h.
References bIsBound, Display, Filter, FORCEINLINE_DEBUGGABLE, GetCostLimit(), GetHeuristicCost(), GetNeighbour(), GetNeighbourCountV2(), GetTraversalCost(), Graph, HasExceededCostLimit(), HasReachMaxSearchNodes(), NO_COUNT, NodePool, OpenList, OutBestNodeCost, OutBestNodeIndex, ShouldIgnoreClosedNodes(), TEXT, and UE_GRAPH_ASTAR_LOG.
Referenced by FindPath(), and FloodFrom().
SetPathInfo()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::SetPathInfo (TemplateClass & Obj, const int32 Param1, const FSearchNode & Param2) inline static
Definition at line 343 of file GraphAStar.h.
Referenced by FindPath(), and FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::CQuerySetPathInfo::Requires().
ShouldFailOnInvalidEndNode()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::ShouldFailOnInvalidEndNode (const TemplateClass & Obj) inline static
Definition at line 336 of file GraphAStar.h.
Referenced by FindPath(), and FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::CQueryShouldFailOnInvalidEndNode::Requires().
ShouldIgnoreClosedNodes()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::ShouldIgnoreClosedNodes (const TemplateClass & Obj) inline static
Definition at line 334 of file GraphAStar.h.
Referenced by ProcessSingleNode(), and FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::CQueryShouldIgnoreClosedNodes::Requires().
ShouldIncludeStartNodeInPath()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TemplateClass> FORCEINLINE decltype(auto) FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::ShouldIncludeStartNodeInPath (const TemplateClass & Obj) inline static
Definition at line 335 of file GraphAStar.h.
Referenced by FindPath(), and FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::CQueryShouldIncludeStartNodeInPath::Requires().
UE_DEPRECATED()
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> template<typename TQueryFilter> FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::UE_DEPRECATED (5. 1, "Please use ProcessSingleNode() taking FVector::FReal& OutBestNodeCost instead!") const &
Single run of A* loop: get node from open set and process neighbors returns true if loop should be continued.
Field Documentation
bIsBound
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::bIsBound
Definition at line 357 of file GraphAStar.h.
Referenced by FindPath(), FloodFrom(), and ProcessSingleNode().
bSucess [1/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const bool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::bSucess = ProcessSingleNode(EndNode, bIsBound, Filter, OutBestNodeIndex, BestNodeCost)
Definition at line 361 of file GraphAStar.h.
bSucess [2/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> return FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::bSucess
Definition at line 363 of file GraphAStar.h.
Filter
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const bool const TQueryFilter& FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::Filter
Definition at line 357 of file GraphAStar.h.
Referenced by FindPath(), FloodFrom(), HasReachMaxSearchNodes(), and ProcessSingleNode().
Graph
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const TGraph& FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::Graph
Definition at line 320 of file GraphAStar.h.
Referenced by FGraphAStar(), FindPath(), FloodFrom(), and ProcessSingleNode().
NodePool
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> FNodePool FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::NodePool
Definition at line 321 of file GraphAStar.h.
Referenced by FindPath(), FloodFrom(), HasReachMaxSearchNodes(), and ProcessSingleNode().
NodeSorter
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> FNodeSorter FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::NodeSorter
Definition at line 322 of file GraphAStar.h.
OpenList
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> FOpenList FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::OpenList
Definition at line 323 of file GraphAStar.h.
Referenced by FindPath(), FloodFrom(), and ProcessSingleNode().
OutBestNodeCost [1/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const bool const TQueryFilter int32 float& FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::OutBestNodeCost
Initial value:
{
        double BestNodeCost
Definition at line 357 of file GraphAStar.h.
Referenced by ProcessSingleNode().
OutBestNodeCost [2/2]
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::OutBestNodeCost = UE_REAL_TO_FLOAT_CLAMPED_MAX(BestNodeCost)
Definition at line 362 of file GraphAStar.h.
OutBestNodeIndex
template<typename TGraph, typename Policy = FGraphAStarDefaultPolicy, typename TSearchNode = FGraphAStarDefaultNode<TGraph>, bool DoRangeCheck = false> const bool const TQueryFilter int32& FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::OutBestNodeIndex
Definition at line 357 of file GraphAStar.h.
Referenced by ProcessSingleNode().
The documentation for this struct was generated from the following file:
GraphAStar.h