Unreal Engine 5.6 C++ API: TAnimatedAttributeBase Class Reference
TAnimatedAttributeBase Class Reference abstract
Animated Attribute Base Layer - used for registering the attribute centrally.
#include "AnimatedAttributeManager.h"
Protected Member Functions
TAnimatedAttributeBase ()
virtual ~TAnimatedAttributeBase ()
void Register ()
virtual void Tick (float InDeltaTime)=0
void Unregister ()
Protected Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
TAnimatedAttributeBase (const TAnimatedAttributeBase &InOther)=delete
TAnimatedAttributeBase & operator= (const TAnimatedAttributeBase &Other)=delete
Private Attributes
bool bIsRegistered
Friends
class FAnimatedAttributeManager
Additional Inherited Members
Public Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
TSharedRef< TAnimatedAttributeBase, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< TAnimatedAttributeBase, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Protected Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Animated Attribute Base Layer - used for registering the attribute centrally.
Definition at line 11 of file AnimatedAttributeManager.h.
Constructor & Destructor Documentation
TAnimatedAttributeBase() [1/2]
TAnimatedAttributeBase::TAnimatedAttributeBase () protected
Referenced by TAnimatedAttributeBase(), and operator=().
~TAnimatedAttributeBase()
virtual TAnimatedAttributeBase::~TAnimatedAttributeBase () protected virtual
TAnimatedAttributeBase() [2/2]
TAnimatedAttributeBase::TAnimatedAttributeBase (const TAnimatedAttributeBase & InOther) private delete
References TAnimatedAttributeBase().
Member Function Documentation
operator=()
TAnimatedAttributeBase & TAnimatedAttributeBase::operator= (const TAnimatedAttributeBase & Other) private delete
References TAnimatedAttributeBase(), and Other.
Register()
void TAnimatedAttributeBase::Register () protected
Tick()
virtual void TAnimatedAttributeBase::Tick (float InDeltaTime) protected pure virtual
Implemented in TAnimatedAttribute< NumericType >.
Unregister()
void TAnimatedAttributeBase::Unregister () protected
Friends And Related Symbol Documentation
FAnimatedAttributeManager
friend class FAnimatedAttributeManager friend
Definition at line 30 of file AnimatedAttributeManager.h.
References FAnimatedAttributeManager.
Referenced by FAnimatedAttributeManager.
Field Documentation
bIsRegistered
bool TAnimatedAttributeBase::bIsRegistered private
Definition at line 28 of file AnimatedAttributeManager.h.
The documentation for this class was generated from the following file:
AnimatedAttributeManager.h