Unreal Engine 5.6 C++ API: FRPCDoSDetection Class Reference
FRPCDoSDetection Class Reference
RPC DoS detection.
#include "RPCDoSDetection.h"
Data Structures
struct FLightweightRPCTracking
Lightweight RPC tracking state.
class FPacketScope
Variables and functions that should only be accessible while receiving an individual packet.
class FSequentialRPCScope
Variables and functions that should only be accessible while receiving the same RPC individually/sequentially.
class FTickScope
Variables and functions that should only be accessible during TickDispatch.
class TScopeBase
Base class for setting code scope activity.
Public Member Functions
void Init (FName NetDriverName, TSharedPtr< FNetAnalyticsAggregator > &AnalyticsAggregator, FGetWorld &&InWorldFunc, FGetRPCDoSAddress &&InAddressFunc, FGetRPCDoSPlayerUID &&InPlayerUIDFunc, FRPCDoSKickPlayer &&InKickPlayerFunc)
Initialize RPC DoS Detection, inputting callbacks for retrieving external information necessary for analytics.
void InitConfig (FName NetDriverName)
Initializes configuration settings for RPC DoS Detection - with support for hot reloading.
bool IsRPCDoSDetectionEnabled () const
Whether or not RPC DoS Detection is enabled.
void LightweightReceivedRPC (UFunction *Function, FName FunctionName)
If RPC monitoring is disabled, does extremely lightweight tracking of RPC calls, for monitoring tracking triggers, and to allow a chance for deducing full RPC tracking information if monitoring is enabled while receiving (so that e.g.
void NotifyClose ()
Triggered upon NetConnection Close (for committing analytics)
ERPCNotifyResult NotifyReceivedRPC (FNetBitReader &Reader, TSet< FNetworkGUID > &UnmappedGuids, UObject *Object, UFunction *Function, FName FunctionName)
If RPC monitoring is enabled, provides a notification for every RPC that is received, with the ability to block it.
void PostReceivedPacket (double TimeSeconds)
Called after the current NetConnection receives a packet.
void PostReceivedRPC ()
Called after the current NetConnection receives an RPC.
void PostReceivedRPCPacket (double TimeSeconds)
Called after the current NetConnection receives a packet, when RPC DoS Detection is active and the packet contains an RPC.
void PostSequentialRPC (EPostSequentialRPCType SequenceType, double TimeSeconds, FRPCDoSCounters *RPCCounter, FRPCTrackingInfo *RPCTrackingInfo)
Called after the same RPC was received once or multiple times sequentially, for optimal timing.
void PostTickDispatch ()
Called after the packet-loop TickDispatch.
void PreReceivedPacket (double TimeSeconds)
Called prior to the current NetConnection receiving a packet.
void PreTickDispatch (double TimeSeconds)
Called prior to the packet-loop TickDispatch.
void SetAddressFunc (FGetRPCDoSAddress &&InAddressFunc)
Overrides the current AddressFunc.
void SetKickPlayerFunc (FRPCDoSKickPlayer &&InKickPlayerFunc)
Overrides the current KickPlayerFunc.
void SetPlayerUIDFunc (FGetRPCDoSPlayerUID &&InPlayerUIDFunc)
Overrides the current PlayerUIDFunc.
bool ShouldMonitorReceivedRPC () const
Whether or not monitoring of received RPC's (i.e.
UE_DEPRECATED (5.1, "UpdateSeverity will be made private soon.") void UpdateSeverity(ERPCDoSSeverityUpdate Update
Updates the current RPC DoS detection severity state.
Data Fields
ERPCDoSEscalateReason Reason
Private Member Functions
void CachePlayerAddress ()
Caches the player address, based on AddressFunc.
void CachePlayerUID ()
Caches the player UID, based on PlayerUIDFunc.
ERPCNotifyResult CheckRPCTracking (UFunction *Function, FName FunctionName)
When RPC monitoring and tracking are enabled, tracks every RPC received.
void ClearStaleRPCTracking (double TimeSeconds)
Used to periodically clear stale RPC tracking.
void CondCheckCountQuota ()
Heavily rate limited RPC count quota checks.
void CondCheckTimeQuota (double TimeSeconds)
Heavily rate limited RPC time quota checks.
void DisableRPCTracking (double TimeSeconds)
Disables tracking of individual RPC's.
void EnableForcedRPCTracking (UFunction *Function, FName FunctionName, double TimeSeconds)
Enables forced tracking of individual RPC's.
void EnableRPCTracking (double TimeSeconds)
Enables tracking of individual RPC's.
FRPCTrackingInfo & FindOrAddRPCTracking (UFunction *InFunc, bool &bOutNewTracking)
Adds or retrieves the specified RPC from tracking.
FPacketScope & GetPacketScope ()
Gets a reference to the packet receive scoped variable/function accessor.
const FString & GetPlayerAddress ()
Returns the net address for the owning NetConnection.
const FString & GetPlayerUID ()
Returns the unique id for the owning player.
FSequentialRPCScope & GetSequentialRPCScope ()
Gets a reference to the sequential RPC scoped variable/function accessor.
FTickScope & GetTickScope ()
Gets a reference to the TickDispatch scoped variable/function accessor.
void InitState (double TimeSeconds)
Initializes a newly active escalation state.
void PreSequentialRPC ()
Called when we begin receiving the same RPC once or multiple times sequentially.
void RecalculatePeriodHistory (const TArray< int8 > &InTimePeriods, FRPCDoSCounters(&OutPerPeriodHistory)[16], int32 StartPerSecHistoryIdx=INDEX_NONE)
Recalculates cached RPC counter history information, after an interval or state change which affects time period tracking.
void UpdateSeverity_Private (ERPCDoSSeverityUpdate Update, ERPCDoSEscalateReason Reason)
Updates the current RPC DoS detection severity state.
Private Attributes
TArray< FActiveRPCTrackingInfo > ActiveRPCTracking
Stores a reference to active/valid RPCTracking entries, for faster cleanup - as the above map stores values sparsely.
int8 ActiveState = 0
The currently active RPC DoS severity state settings.
FGetRPCDoSAddress AddressFunc
Callback used for getting the address of the NetConnection the RPC DoS Detection is associated with.
double AnalyticsMinTimePerSecThreshold = 0.0
The minimum RPC time per second threshold, for doing analytics updates/checks.
FRPCDoSAnalyticsVars AnalyticsVars
The locally cached/updated analytics variables, for the RPC DoS Detection - aggregated upon connection Close.
bool bHitchSuspendDetection = false
Whether or not RPC DoS Detection has been suspended, due to a hitch impairing the accuracy of measurements.
bool bRPCDoSAnalytics = false
Whether or not analytics for RPC DoS detection is enabled.
bool bRPCDoSDetection = false
Whether or not RPC DoS detection is presently enabled.
bool bRPCTrackingEnabled = false
Whether or not RPC Tracking has been enabled by RPC DoS escalation or other checks.
FString CachedAddress
Player IP cached from AddressFunc.
FString CachedPlayerUID
Player UID cached from PlayerUIDFunc.
FRPCDoSCounters CounterPerPeriodHistory [16] = {}
Counter history which is precalculated/cached from CounterPerSecHistory, for tracking per-period time (up to a maximum of 16s)
TArray< FRPCDoSCounters > CounterPerSecHistory
Stores enough per second quota history, to allow all DetectionSeverity states to recalculate if their CooloffTime is reached.
TArray< FRPCDoSStateConfig > DetectionSeverity
The different RPC DoS detection states, of escalating severity, depending on the amount of RPC spam.
FName ForcedRPCTracking
If the related CVar is set, the name of the RPC which should forcibly enable tracking.
double ForcedRPCTrackingChance = 1.0
Specifies the chance (between 0.0 and 1.0) that tracking will be enabled, when encountering the ForcedRPCTracking RPC.
double ForcedRPCTrackingEndTime = 0.0
Specifies the time at which forced RPC tracking should end, if tracking isn't enabled by the active state.
double ForcedRPCTrackingLength = 0.0
Specifies the length of time forced RPC tracking should be enabled (disabled the next tick, if 0.0)
double HitchSuspendDetectionStartTime = 0.0
Timestamp for when RPC DoS Detection was suspended, due to a hitch.
int32 HitchSuspendDetectionTimeMS = 0
The amount of time to suspend RPC DoS Detection, once a hitch is encountered, to prevent false positives from built-up packets.
int32 HitchTimeQuotaMS = 0
The amount of time since the previous frame, for detecting hitches, to prevent false positives from built-up packets.
FRPCDoSKickPlayer KickPlayerFunc
Callback used for kicking the player after a bad enough RPC DoS.
double LastAnalyticsThresholdRecalc = 0.0
The last time the 'AnalyticsMinTimePerSecThreshold' was recalculated.
int32 LastCounterPerSecHistoryIdx = 0
The last written index of CounterPerSecHistory.
double LastMetEscalationConditions = 0.0
The last time the previous severity states escalation conditions were met (to prevent bouncing up/down between states)
double LastPerSecQuotaBegin = 0.0
Timestamp for the last time per-second quota counting began.
double LastPreTickDispatchTime = 0.0
Cached PreTickDispatch timestamp, to reuse for minimizing timestamp retrieval.
double LastRPCTrackingClean = 0.0
The last time RPCTracking was cleaned out.
int8 MaxRPCTrackingPeriod = 0
The runtime maximum number of seconds of RPC tracking that is used.
double NextTimeQuotaCheck = 0.0
Timestamp for when time quota's should next be checked.
FPacketScope PacketScopePrivate
Scoped variables/functions accessible while receiving an individual packet.
FGetRPCDoSPlayerUID PlayerUIDFunc
Callback used for getting the unique id of the NetConnection the RPC DoS Detection is associated with.
double ReceivedPacketEndTime = 0.0
Cached free/external timestamp, for when the last received packet finished processing.
TArray< FName > RPCBlockAllowList
List of RPC's which should never be blocked.
TNetAnalyticsDataPtr< FRPCDoSAnalyticsData > RPCDoSAnalyticsData
The net analytics data holder for the RPC DoS analytics, which is where analytics variables are aggregated upon Close.
uint32 RPCIntervalCounter = 0
Unbounded RPC counter, for performing RPC checks at every 'x' intervals.
TMap< void *, TSharedPtr< FRPCTrackingInfo > > RPCTracking
Maps UFunction pointers to live function tracking structs (NOTE: Treats the UFunction's as potentially invalid/GC'd, hence void*)
FRPCDoSCounters SecondCounter
Per-second RPC counting (approximate - may cover more than one second, in the case of expensive/long-running RPCs)
uint8 SecondsIncrementer = 0
Wrapping count of seconds passed, for RPC tracking.
FSequentialRPCScope SequentialRPCScopePrivate
Scoped variables/functions accessible while receiving the same RPC individually/sequentially.
FTickScope TickScopePrivate
Scoped variables/functions accessible during TickDispatch.
int8 WorstActiveState = 0
The worst RPC DoS severity state that has been active.
int8 WorstAnalyticsState = 0
The worst RPC DoS severity state that has been active and passed confirmation thresholds - used for limiting analytics events.
Static Private Attributes
static constexpr int32 DefaultActiveRPCTrackingSize = 128
Default size for ActiveRPCTracking, to minimize realloc.
static constexpr double TimeQuotaCheckInterval = 0.005
Interval for time quota checks, in seconds.
Friends
struct FRPCDoSStateConfig
Detailed Description
RPC DoS detection.
Implements DoS detection for NetConnection RPC's, using an escalating series of detection states depending on the severity of the DoS, to prevent false positives and minimize any performance impact.
RPC's are profiled based on count and execution time, with careful implementation of tracking to balance lookup speed, memory usage, timing, and analytics tracking.
Definition at line 418 of file RPCDoSDetection.h.
Member Function Documentation
CachePlayerAddress()
void FRPCDoSDetection::CachePlayerAddress () private
Caches the player address, based on AddressFunc.
CachePlayerUID()
void FRPCDoSDetection::CachePlayerUID () private
Caches the player UID, based on PlayerUIDFunc.
CheckRPCTracking()
ERPCNotifyResult FRPCDoSDetection::CheckRPCTracking (UFunction * Function, FName FunctionName) private
When RPC monitoring and tracking are enabled, tracks every RPC received.
WARNING: Potentially expensive! RPC DoS Detection should be configured, so that tracking is rarely enabled.
Parameters
Function The UFunction representing the RPC
FunctionName The cached name of the function
Returns
Whether or not to block the RPC
References Function.
ClearStaleRPCTracking()
void FRPCDoSDetection::ClearStaleRPCTracking (double TimeSeconds) private
Used to periodically clear stale RPC tracking.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
CondCheckCountQuota()
void FRPCDoSDetection::CondCheckCountQuota () inline private
Heavily rate limited RPC count quota checks.
Definition at line 769 of file RPCDoSDetection.h.
References CounterPerPeriodHistory, CountLimit, Escalate, FRPCDoSDetection::FTickScope::FrameCounter, GetTickScope(), RPCIntervalCounter, and FRPCDoSDetection::FTickScope::UpdateSeverity().
CondCheckTimeQuota()
void FRPCDoSDetection::CondCheckTimeQuota (double TimeSeconds) inline private
Heavily rate limited RPC time quota checks.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
Definition at line 788 of file RPCDoSDetection.h.
References CounterPerPeriodHistory, Escalate, FRPCDoSDetection::FTickScope::FrameCounter, GetTickScope(), NextTimeQuotaCheck, TimeLimit, TimeQuotaCheckInterval, and FRPCDoSDetection::FTickScope::UpdateSeverity().
DisableRPCTracking()
void FRPCDoSDetection::DisableRPCTracking (double TimeSeconds) private
Disables tracking of individual RPC's.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
EnableForcedRPCTracking()
void FRPCDoSDetection::EnableForcedRPCTracking (UFunction * Function, FName FunctionName, double TimeSeconds) private
Enables forced tracking of individual RPC's.
Parameters
Function The function which triggered forced RPC tracking
FunctionName The name of the function which triggered forced RPC tracking
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
References Function.
Referenced by LightweightReceivedRPC().
EnableRPCTracking()
void FRPCDoSDetection::EnableRPCTracking (double TimeSeconds) private
Enables tracking of individual RPC's.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
FindOrAddRPCTracking()
FRPCTrackingInfo & FRPCDoSDetection::FindOrAddRPCTracking (UFunction * InFunc, bool & bOutNewTracking) inline private
Adds or retrieves the specified RPC from tracking.
Parameters
InFunc The RPC UFunction for tracking
bOutNewTracking Whether or not the RPC was newly added to tracking
Returns
Returns the RPC tracking info
Definition at line 854 of file RPCDoSDetection.h.
References ActiveRPCTracking, TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), MakeShared(), and RPCTracking.
GetPacketScope()
FPacketScope & FRPCDoSDetection::GetPacketScope () inline private
Gets a reference to the packet receive scoped variable/function accessor.
Definition at line 1019 of file RPCDoSDetection.h.
References ensure, UE::Net::GRPCDoSScopeDebugging, and PacketScopePrivate.
Referenced by PostReceivedPacket(), PostReceivedRPC(), and PreReceivedPacket().
GetPlayerAddress()
const FString & FRPCDoSDetection::GetPlayerAddress () inline private
Returns the net address for the owning NetConnection.
Returns
The net address for the owning connection.
Definition at line 893 of file RPCDoSDetection.h.
References CachedAddress.
GetPlayerUID()
const FString & FRPCDoSDetection::GetPlayerUID () inline private
Returns the unique id for the owning player.
Returns
The unique id for the owning player.
Definition at line 903 of file RPCDoSDetection.h.
References CachedPlayerUID.
GetSequentialRPCScope()
FSequentialRPCScope & FRPCDoSDetection::GetSequentialRPCScope () inline private
Gets a reference to the sequential RPC scoped variable/function accessor.
Definition at line 1114 of file RPCDoSDetection.h.
References ensure, UE::Net::GRPCDoSScopeDebugging, and SequentialRPCScopePrivate.
Referenced by LightweightReceivedRPC(), NotifyReceivedRPC(), and PostReceivedRPC().
GetTickScope()
FTickScope & FRPCDoSDetection::GetTickScope () inline private
Gets a reference to the TickDispatch scoped variable/function accessor.
Definition at line 983 of file RPCDoSDetection.h.
References ensure, UE::Net::GRPCDoSScopeDebugging, and TickScopePrivate.
Referenced by CondCheckCountQuota(), CondCheckTimeQuota(), and PostReceivedRPC().
Init()
void FRPCDoSDetection::Init (FName NetDriverName, TSharedPtr< FNetAnalyticsAggregator > & AnalyticsAggregator, FGetWorld && InWorldFunc, FGetRPCDoSAddress && InAddressFunc, FGetRPCDoSPlayerUID && InPlayerUIDFunc, FRPCDoSKickPlayer && InKickPlayerFunc)
Initialize RPC DoS Detection, inputting callbacks for retrieving external information necessary for analytics.
Parameters
NetDriverName The name of the NetDriver which RPC DoS Detection belongs to (e.g. GameNetDriver)
AnalyticsAggregator Reference to the NetDriver analytics aggregator
InWorldFunc Callback for getting the current NetConnection World.
InAddressFunc Callback for getting the current NetConnection address.
InPlayerUIDFunc Callback for getting the current NetConnection player UID.
InKickPlayerFunc Callback for kicking the player after a bad enough RPC DoS.
InitConfig()
void FRPCDoSDetection::InitConfig (FName NetDriverName)
Initializes configuration settings for RPC DoS Detection - with support for hot reloading.
Parameters
NetDriverName The name of the NetDriver which RPC DoS Detection belongs to (e.g. GameNetDriver)
InitState()
void FRPCDoSDetection::InitState (double TimeSeconds) private
Initializes a newly active escalation state.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
IsRPCDoSDetectionEnabled()
bool FRPCDoSDetection::IsRPCDoSDetectionEnabled () const inline
Whether or not RPC DoS Detection is enabled.
Definition at line 708 of file RPCDoSDetection.h.
References bRPCDoSDetection.
LightweightReceivedRPC()
void FRPCDoSDetection::LightweightReceivedRPC (UFunction * Function, FName FunctionName) inline
If RPC monitoring is disabled, does extremely lightweight tracking of RPC calls, for monitoring tracking triggers, and to allow a chance for deducing full RPC tracking information if monitoring is enabled while receiving (so that e.g.
if an RPC DoS attack enables monitoring, information on the RPC responsible can be recovered).
Parameters
Function The UFunction representing the RPC
FunctionName The cached name of the function
Definition at line 570 of file RPCDoSDetection.h.
References bHitchSuspendDetection, bRPCDoSDetection, FRPCDoSDetection::FLightweightRPCTracking::Count, CSV_SCOPED_TIMING_STAT_EXCLUSIVE, EnableForcedRPCTracking(), ForcedRPCTracking, ForcedRPCTrackingChance, Function, FRPCDoSDetection::FLightweightRPCTracking::FLightweightRPCEntry::Function, GetSequentialRPCScope(), FRPCDoSDetection::FSequentialRPCScope::LightweightRPCTracking, FRPCDoSDetection::FLightweightRPCTracking::FLightweightRPCEntry::Name, PreSequentialRPC(), FRPCDoSDetection::FLightweightRPCTracking::RPC, FAndroidTime::Seconds(), SequentialRPCScopePrivate, and UNLIKELY.
NotifyClose()
void FRPCDoSDetection::NotifyClose ()
Triggered upon NetConnection Close (for committing analytics)
NotifyReceivedRPC()
ERPCNotifyResult FRPCDoSDetection::NotifyReceivedRPC (FNetBitReader & Reader, TSet< FNetworkGUID > & UnmappedGuids, UObject * Object, UFunction * Function, FName FunctionName) inline
If RPC monitoring is enabled, provides a notification for every RPC that is received, with the ability to block it.
Parameters
Reader The net bit reader containing the packet data, in case parsing of RPC parameters is desired
UnmappedGuids Reference to the set of unmapped Guid's - in case it's necessary for parsing RPC parameters
Object The UObject the RPC will be called on
Function The UFunction representing the RPC
FunctionName The cached name of the function
Returns
Whether or not to block the RPC
Definition at line 528 of file RPCDoSDetection.h.
References bHitchSuspendDetection, bRPCDoSDetection, bRPCTrackingEnabled, FRPCDoSDetection::FSequentialRPCScope::CheckRPCTracking(), CSV_SCOPED_TIMING_STAT_EXCLUSIVE, ExecuteRPC, Function, GetSequentialRPCScope(), Object, PreSequentialRPC(), FAndroidTime::Seconds(), and SequentialRPCScopePrivate.
PostReceivedPacket()
void FRPCDoSDetection::PostReceivedPacket (double TimeSeconds) inline
Called after the current NetConnection receives a packet.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
Definition at line 649 of file RPCDoSDetection.h.
References CSV_SCOPED_TIMING_STAT_EXCLUSIVE, ensure, GetPacketScope(), UE::Net::GRPCDoSScopeDebugging, PacketScopePrivate, PostReceivedRPCPacket(), ReceivedPacketEndTime, SequentialRPCScopePrivate, and TickScopePrivate.
PostReceivedRPC()
void FRPCDoSDetection::PostReceivedRPC () inline
Called after the current NetConnection receives an RPC.
Definition at line 602 of file RPCDoSDetection.h.
References bHitchSuspendDetection, FRPCDoSDetection::FPacketScope::bPacketContainsRPC, bRPCDoSDetection, FRPCDoSDetection::FTickScope::CondCheckCountQuota(), CSV_SCOPED_TIMING_STAT_EXCLUSIVE, FRPCDoSDetection::FTickScope::FrameCounter, GetPacketScope(), GetSequentialRPCScope(), GetTickScope(), FRPCDoSDetection::FSequentialRPCScope::ReceivedPacketRPCCount, FRPCDoSCounters::RPCCounter, RPCIntervalCounter, and FAndroidTime::Seconds().
PostReceivedRPCPacket()
void FRPCDoSDetection::PostReceivedRPCPacket (double TimeSeconds)
Called after the current NetConnection receives a packet, when RPC DoS Detection is active and the packet contains an RPC.
NOTE: Timing is approximate - may include multiple-RPC and non-RPC packet processing time - but low cost
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
Referenced by PostReceivedPacket().
PostSequentialRPC()
void FRPCDoSDetection::PostSequentialRPC (EPostSequentialRPCType SequenceType, double TimeSeconds, FRPCDoSCounters * RPCCounter, FRPCTrackingInfo * RPCTrackingInfo)
Called after the same RPC was received once or multiple times sequentially, for optimal timing.
Parameters
SequenceType The type of sequential RPC call (a sequence stopping mid-packet, or at the end of the packet)
TimeSeconds The current time, in seconds (may be approximate)
RPCCounter Cached pointer to the currently active counter, for this RPC
RPCTrackingInfo Cached pointer to the tracking info, for this RPC
PostTickDispatch()
void FRPCDoSDetection::PostTickDispatch ()
Called after the packet-loop TickDispatch.
PreReceivedPacket()
void FRPCDoSDetection::PreReceivedPacket (double TimeSeconds) inline
Called prior to the current NetConnection receiving a packet.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
Definition at line 493 of file RPCDoSDetection.h.
References CSV_SCOPED_TIMING_STAT_EXCLUSIVE, ensure, GetPacketScope(), UE::Net::GRPCDoSScopeDebugging, PacketScopePrivate, FRPCDoSDetection::FPacketScope::ReceivedPacketStartTime, SequentialRPCScopePrivate, and TickScopePrivate.
PreSequentialRPC()
void FRPCDoSDetection::PreSequentialRPC () inline private
Called when we begin receiving the same RPC once or multiple times sequentially.
Definition at line 739 of file RPCDoSDetection.h.
References ensure, UE::Net::GRPCDoSScopeDebugging, PacketScopePrivate, SequentialRPCScopePrivate, and TickScopePrivate.
Referenced by LightweightReceivedRPC(), and NotifyReceivedRPC().
PreTickDispatch()
void FRPCDoSDetection::PreTickDispatch (double TimeSeconds)
Called prior to the packet-loop TickDispatch.
Parameters
TimeSeconds Cached/approximate timestamp, to save grabbing a new timestamp
RecalculatePeriodHistory()
void FRPCDoSDetection::RecalculatePeriodHistory (const TArray< int8 > & InTimePeriods, FRPCDoSCounters(&) OutPerPeriodHistory[16], int32 StartPerSecHistoryIdx = INDEX_NONE) private
Recalculates cached RPC counter history information, after an interval or state change which affects time period tracking.
Parameters
InTimePeriods The time period values which need caching (e.g. a period of 2 seconds, and a period of 8 seconds).
OutPerPeriodHistory Outputs the recalculated RPC counter cache, for the specified time periods (e.g. elements 1 and 7 only).
StartPerSecHistoryIdx The index in CounterPerSecHistory to start calculating from
References INDEX_NONE.
SetAddressFunc()
void FRPCDoSDetection::SetAddressFunc (FGetRPCDoSAddress && InAddressFunc)
Overrides the current AddressFunc.
Parameters
InAddressFunc The new AddressFunc
SetKickPlayerFunc()
void FRPCDoSDetection::SetKickPlayerFunc (FRPCDoSKickPlayer && InKickPlayerFunc)
Overrides the current KickPlayerFunc.
Parameters
InKickPlayerFunc The new KickPlayerFunc
SetPlayerUIDFunc()
void FRPCDoSDetection::SetPlayerUIDFunc (FGetRPCDoSPlayerUID && InPlayerUIDFunc)
Overrides the current PlayerUIDFunc.
Parameters
InPlayerUIDFunc The new PlayerUIDFunc
ShouldMonitorReceivedRPC()
bool FRPCDoSDetection::ShouldMonitorReceivedRPC () const inline
Whether or not monitoring of received RPC's (i.e.
calling of NotifyReceivedRPC) should be performed
Returns
Whether or not to monitor received RPC's.
Definition at line 696 of file RPCDoSDetection.h.
References bRPCTrackingEnabled.
UE_DEPRECATED()
FRPCDoSDetection::UE_DEPRECATED (5. 1, "UpdateSeverity will be made private soon.")
Updates the current RPC DoS detection severity state.
Parameters
Update Whether or not we are escalating or de-escalating the severity state
Reason The reason for the escalation change
UpdateSeverity_Private()
void FRPCDoSDetection::UpdateSeverity_Private (ERPCDoSSeverityUpdate Update, ERPCDoSEscalateReason Reason) private
Updates the current RPC DoS detection severity state.
Parameters
Update Whether or not we are escalating or de-escalating the severity state
Reason The reason for the escalation change
References Reason.
Friends And Related Symbol Documentation
FRPCDoSStateConfig
friend struct FRPCDoSStateConfig friend
Definition at line 420 of file RPCDoSDetection.h.
References FRPCDoSStateConfig.
Referenced by FRPCDoSStateConfig.
Field Documentation
ActiveRPCTracking
TArray<FActiveRPCTrackingInfo> FRPCDoSDetection::ActiveRPCTracking private
Stores a reference to active/valid RPCTracking entries, for faster cleanup - as the above map stores values sparsely.
Definition at line 1238 of file RPCDoSDetection.h.
Referenced by FindOrAddRPCTracking().
ActiveState
int8 FRPCDoSDetection::ActiveState = 0 private
The currently active RPC DoS severity state settings.
Definition at line 1175 of file RPCDoSDetection.h.
AddressFunc
FGetRPCDoSAddress FRPCDoSDetection::AddressFunc private
Callback used for getting the address of the NetConnection the RPC DoS Detection is associated with.
Definition at line 1156 of file RPCDoSDetection.h.
AnalyticsMinTimePerSecThreshold
double FRPCDoSDetection::AnalyticsMinTimePerSecThreshold = 0.0 private
The minimum RPC time per second threshold, for doing analytics updates/checks.
Definition at line 1254 of file RPCDoSDetection.h.
AnalyticsVars
FRPCDoSAnalyticsVars FRPCDoSDetection::AnalyticsVars private
The locally cached/updated analytics variables, for the RPC DoS Detection - aggregated upon connection Close.
Definition at line 1248 of file RPCDoSDetection.h.
bHitchSuspendDetection
bool FRPCDoSDetection::bHitchSuspendDetection = false private
Whether or not RPC DoS Detection has been suspended, due to a hitch impairing the accuracy of measurements.
Definition at line 1187 of file RPCDoSDetection.h.
Referenced by LightweightReceivedRPC(), NotifyReceivedRPC(), and PostReceivedRPC().
bRPCDoSAnalytics
bool FRPCDoSDetection::bRPCDoSAnalytics = false private
Whether or not analytics for RPC DoS detection is enabled.
Definition at line 1131 of file RPCDoSDetection.h.
bRPCDoSDetection
bool FRPCDoSDetection::bRPCDoSDetection = false private
Whether or not RPC DoS detection is presently enabled.
Definition at line 1128 of file RPCDoSDetection.h.
Referenced by IsRPCDoSDetectionEnabled(), LightweightReceivedRPC(), NotifyReceivedRPC(), and PostReceivedRPC().
bRPCTrackingEnabled
bool FRPCDoSDetection::bRPCTrackingEnabled = false private
Whether or not RPC Tracking has been enabled by RPC DoS escalation or other checks.
Definition at line 1229 of file RPCDoSDetection.h.
Referenced by NotifyReceivedRPC(), and ShouldMonitorReceivedRPC().
CachedAddress
FString FRPCDoSDetection::CachedAddress private
Player IP cached from AddressFunc.
Definition at line 1159 of file RPCDoSDetection.h.
Referenced by GetPlayerAddress().
CachedPlayerUID
FString FRPCDoSDetection::CachedPlayerUID private
Player UID cached from PlayerUIDFunc.
Definition at line 1165 of file RPCDoSDetection.h.
Referenced by GetPlayerUID().
CounterPerPeriodHistory
FRPCDoSCounters FRPCDoSDetection::CounterPerPeriodHistory[16] = {} private
Counter history which is precalculated/cached from CounterPerSecHistory, for tracking per-period time (up to a maximum of 16s)
Definition at line 1206 of file RPCDoSDetection.h.
Referenced by CondCheckCountQuota(), and CondCheckTimeQuota().
CounterPerSecHistory
TArray<FRPCDoSCounters> FRPCDoSDetection::CounterPerSecHistory private
Stores enough per second quota history, to allow all DetectionSeverity states to recalculate if their CooloffTime is reached.
Definition at line 1200 of file RPCDoSDetection.h.
DefaultActiveRPCTrackingSize
int32 FRPCDoSDetection::DefaultActiveRPCTrackingSize = 128 static constexpr private
Default size for ActiveRPCTracking, to minimize realloc.
Definition at line 1241 of file RPCDoSDetection.h.
DetectionSeverity
TArray<FRPCDoSStateConfig> FRPCDoSDetection::DetectionSeverity private
The different RPC DoS detection states, of escalating severity, depending on the amount of RPC spam.
Definition at line 1172 of file RPCDoSDetection.h.
ForcedRPCTracking
FName FRPCDoSDetection::ForcedRPCTracking private
If the related CVar is set, the name of the RPC which should forcibly enable tracking.
Definition at line 1143 of file RPCDoSDetection.h.
Referenced by LightweightReceivedRPC().
ForcedRPCTrackingChance
double FRPCDoSDetection::ForcedRPCTrackingChance = 1.0 private
Specifies the chance (between 0.0 and 1.0) that tracking will be enabled, when encountering the ForcedRPCTracking RPC.
Definition at line 1146 of file RPCDoSDetection.h.
Referenced by LightweightReceivedRPC().
ForcedRPCTrackingEndTime
double FRPCDoSDetection::ForcedRPCTrackingEndTime = 0.0 private
Specifies the time at which forced RPC tracking should end, if tracking isn't enabled by the active state.
Definition at line 1152 of file RPCDoSDetection.h.
ForcedRPCTrackingLength
double FRPCDoSDetection::ForcedRPCTrackingLength = 0.0 private
Specifies the length of time forced RPC tracking should be enabled (disabled the next tick, if 0.0)
Definition at line 1149 of file RPCDoSDetection.h.
HitchSuspendDetectionStartTime
double FRPCDoSDetection::HitchSuspendDetectionStartTime = 0.0 private
Timestamp for when RPC DoS Detection was suspended, due to a hitch.
Definition at line 1190 of file RPCDoSDetection.h.
HitchSuspendDetectionTimeMS
int32 FRPCDoSDetection::HitchSuspendDetectionTimeMS = 0 private
The amount of time to suspend RPC DoS Detection, once a hitch is encountered, to prevent false positives from built-up packets.
Definition at line 1137 of file RPCDoSDetection.h.
HitchTimeQuotaMS
int32 FRPCDoSDetection::HitchTimeQuotaMS = 0 private
The amount of time since the previous frame, for detecting hitches, to prevent false positives from built-up packets.
Definition at line 1134 of file RPCDoSDetection.h.
KickPlayerFunc
FRPCDoSKickPlayer FRPCDoSDetection::KickPlayerFunc private
Callback used for kicking the player after a bad enough RPC DoS.
Definition at line 1168 of file RPCDoSDetection.h.
LastAnalyticsThresholdRecalc
double FRPCDoSDetection::LastAnalyticsThresholdRecalc = 0.0 private
The last time the 'AnalyticsMinTimePerSecThreshold' was recalculated.
Definition at line 1257 of file RPCDoSDetection.h.
LastCounterPerSecHistoryIdx
int32 FRPCDoSDetection::LastCounterPerSecHistoryIdx = 0 private
The last written index of CounterPerSecHistory.
Definition at line 1203 of file RPCDoSDetection.h.
LastMetEscalationConditions
double FRPCDoSDetection::LastMetEscalationConditions = 0.0 private
The last time the previous severity states escalation conditions were met (to prevent bouncing up/down between states)
Definition at line 1184 of file RPCDoSDetection.h.
LastPerSecQuotaBegin
double FRPCDoSDetection::LastPerSecQuotaBegin = 0.0 private
Timestamp for the last time per-second quota counting began.
Definition at line 1197 of file RPCDoSDetection.h.
LastPreTickDispatchTime
double FRPCDoSDetection::LastPreTickDispatchTime = 0.0 private
Cached PreTickDispatch timestamp, to reuse for minimizing timestamp retrieval.
Definition at line 1216 of file RPCDoSDetection.h.
LastRPCTrackingClean
double FRPCDoSDetection::LastRPCTrackingClean = 0.0 private
The last time RPCTracking was cleaned out.
Definition at line 1244 of file RPCDoSDetection.h.
MaxRPCTrackingPeriod
int8 FRPCDoSDetection::MaxRPCTrackingPeriod = 0 private
The runtime maximum number of seconds of RPC tracking that is used.
Definition at line 1232 of file RPCDoSDetection.h.
NextTimeQuotaCheck
double FRPCDoSDetection::NextTimeQuotaCheck = 0.0 private
Timestamp for when time quota's should next be checked.
Definition at line 1222 of file RPCDoSDetection.h.
Referenced by CondCheckTimeQuota().
PacketScopePrivate
FPacketScope FRPCDoSDetection::PacketScopePrivate private
Scoped variables/functions accessible while receiving an individual packet.
Definition at line 1015 of file RPCDoSDetection.h.
Referenced by GetPacketScope(), PostReceivedPacket(), PreReceivedPacket(), and PreSequentialRPC().
PlayerUIDFunc
FGetRPCDoSPlayerUID FRPCDoSDetection::PlayerUIDFunc private
Callback used for getting the unique id of the NetConnection the RPC DoS Detection is associated with.
Definition at line 1162 of file RPCDoSDetection.h.
Reason
ERPCDoSEscalateReason FRPCDoSDetection::Reason
Initial value:
{
        UpdateSeverity_Private(Update, Reason)
Definition at line 475 of file RPCDoSDetection.h.
Referenced by FRPCDoSDetection::FTickScope::UpdateSeverity(), and UpdateSeverity_Private().
ReceivedPacketEndTime
double FRPCDoSDetection::ReceivedPacketEndTime = 0.0 private
Cached free/external timestamp, for when the last received packet finished processing.
Definition at line 1213 of file RPCDoSDetection.h.
Referenced by PostReceivedPacket().
RPCBlockAllowList
TArray<FName> FRPCDoSDetection::RPCBlockAllowList private
List of RPC's which should never be blocked.
Definition at line 1140 of file RPCDoSDetection.h.
RPCDoSAnalyticsData
TNetAnalyticsDataPtr<FRPCDoSAnalyticsData> FRPCDoSDetection::RPCDoSAnalyticsData private
The net analytics data holder for the RPC DoS analytics, which is where analytics variables are aggregated upon Close.
Definition at line 1251 of file RPCDoSDetection.h.
RPCIntervalCounter
uint32 FRPCDoSDetection::RPCIntervalCounter = 0 private
Unbounded RPC counter, for performing RPC checks at every 'x' intervals.
Definition at line 1219 of file RPCDoSDetection.h.
Referenced by CondCheckCountQuota(), and PostReceivedRPC().
RPCTracking
TMap<void*, TSharedPtr<FRPCTrackingInfo> > FRPCDoSDetection::RPCTracking private
Maps UFunction pointers to live function tracking structs (NOTE: Treats the UFunction's as potentially invalid/GC'd, hence void*)
Definition at line 1235 of file RPCDoSDetection.h.
Referenced by FindOrAddRPCTracking().
SecondCounter
FRPCDoSCounters FRPCDoSDetection::SecondCounter private
Per-second RPC counting (approximate - may cover more than one second, in the case of expensive/long-running RPCs)
Definition at line 1194 of file RPCDoSDetection.h.
SecondsIncrementer
uint8 FRPCDoSDetection::SecondsIncrementer = 0 private
Wrapping count of seconds passed, for RPC tracking.
Definition at line 1209 of file RPCDoSDetection.h.
SequentialRPCScopePrivate
FSequentialRPCScope FRPCDoSDetection::SequentialRPCScopePrivate private
Scoped variables/functions accessible while receiving the same RPC individually/sequentially.
Definition at line 1111 of file RPCDoSDetection.h.
Referenced by GetSequentialRPCScope(), LightweightReceivedRPC(), NotifyReceivedRPC(), PostReceivedPacket(), PreReceivedPacket(), and PreSequentialRPC().
TickScopePrivate
FTickScope FRPCDoSDetection::TickScopePrivate private
Scoped variables/functions accessible during TickDispatch.
Definition at line 979 of file RPCDoSDetection.h.
Referenced by GetTickScope(), PostReceivedPacket(), PreReceivedPacket(), and PreSequentialRPC().
TimeQuotaCheckInterval
double FRPCDoSDetection::TimeQuotaCheckInterval = 0.005 static constexpr private
Interval for time quota checks, in seconds.
Definition at line 1225 of file RPCDoSDetection.h.
Referenced by CondCheckTimeQuota().
WorstActiveState
int8 FRPCDoSDetection::WorstActiveState = 0 private
The worst RPC DoS severity state that has been active.
Definition at line 1178 of file RPCDoSDetection.h.
WorstAnalyticsState
int8 FRPCDoSDetection::WorstAnalyticsState = 0 private
The worst RPC DoS severity state that has been active and passed confirmation thresholds - used for limiting analytics events.
Definition at line 1181 of file RPCDoSDetection.h.
The documentation for this class was generated from the following file:
RPCDoSDetection.h