Unreal Engine 5.6 C++ API: FCanvasBatchedElementRenderItem Class Reference
FCanvasBatchedElementRenderItem Class Reference
Info needed to render a batched element set.
#include "CanvasBatchedElementRenderItem.h"
Data Structures
class FRenderData
Public Member Functions
FCanvasBatchedElementRenderItem (FBatchedElementParameters *InBatchedElementParameters=NULL, const FTexture *InTexture=NULL, ESimpleElementBlendMode InBlendMode=SE_BLEND_MAX, FCanvas::EElementType InElementType=FCanvas::ET_MAX, const FCanvas::FTransformEntry &InTransform=FCanvas::FTransformEntry(FMatrix::Identity), const FDepthFieldGlowInfo &InGlowInfo=FDepthFieldGlowInfo())
Init constructor.
virtual ~FCanvasBatchedElementRenderItem ()
Destructor to delete data in case nothing rendered.
FORCEINLINE FBatchedElements * GetBatchedElements ()
Accessor for the batched elements.
virtual class FCanvasBatchedElementRenderItem * GetCanvasBatchedElementRenderItem () override
FCanvasBatchedElementRenderItem instance accessor.
bool IsMatch (FBatchedElementParameters *BatchedElementParameters, const FTexture *InTexture, ESimpleElementBlendMode InBlendMode, FCanvas::EElementType InElementType, const FCanvas::FTransformEntry &InTransform, const FDepthFieldGlowInfo &InGlowInfo)
Determine if this is a matching set by comparing texture,blendmode,elementype,transform.
virtual bool Render_GameThread (const FCanvas *Canvas, FCanvasRenderThreadScope &RenderScope) override
Renders the canvas item.
virtual bool Render_RenderThread (FCanvasRenderContext &RenderContext, FMeshPassProcessorRenderState &DrawRenderState, const FCanvas *Canvas) override
Renders the canvas item.
Public Member Functions inherited from FCanvasBaseRenderItem
virtual ~FCanvasBaseRenderItem ()
virtual class FCanvasTileRendererItem * GetCanvasTileRendererItem ()
FCanvasTileRendererItem instance accessor.
virtual class FCanvasTriangleRendererItem * GetCanvasTriangleRendererItem ()
FCanvasTriangleRendererItem instance accessor.
Private Attributes
FRenderData * Data
Render data which is allocated when a new FCanvasBatchedElementRenderItem is added for rendering.
Detailed Description
Info needed to render a batched element set.
Definition at line 15 of file CanvasBatchedElementRenderItem.h.
Constructor & Destructor Documentation
FCanvasBatchedElementRenderItem()
FCanvasBatchedElementRenderItem::FCanvasBatchedElementRenderItem (FBatchedElementParameters * InBatchedElementParameters = NULL, const FTexture * InTexture = NULL, ESimpleElementBlendMode InBlendMode = SE_BLEND_MAX, FCanvas::EElementType InElementType = FCanvas::ET_MAX, const FCanvas::FTransformEntry & InTransform = FCanvas::FTransformEntry(FMatrix::Identity), const FDepthFieldGlowInfo & InGlowInfo = FDepthFieldGlowInfo()) inline
Init constructor.
Definition at line 21 of file CanvasBatchedElementRenderItem.h.
References Data, FCanvas::ET_MAX, UE::Math::TMatrix< double >::Identity, and SE_BLEND_MAX.
Referenced by GetCanvasBatchedElementRenderItem().
~FCanvasBatchedElementRenderItem()
virtual FCanvasBatchedElementRenderItem::~FCanvasBatchedElementRenderItem () inline virtual
Destructor to delete data in case nothing rendered.
Definition at line 35 of file CanvasBatchedElementRenderItem.h.
References Data.
Member Function Documentation
GetBatchedElements()
FORCEINLINE FBatchedElements * FCanvasBatchedElementRenderItem::GetBatchedElements () inline
Accessor for the batched elements.
This can be used for adding triangles and primitives to the batched elements
Returns
pointer to batched elements struct
Definition at line 95 of file CanvasBatchedElementRenderItem.h.
References Data, and FORCEINLINE.
GetCanvasBatchedElementRenderItem()
virtual class FCanvasBatchedElementRenderItem * FCanvasBatchedElementRenderItem::GetCanvasBatchedElementRenderItem () inline override virtual
FCanvasBatchedElementRenderItem instance accessor.
Returns
this instance
Reimplemented from FCanvasBaseRenderItem.
Definition at line 45 of file CanvasBatchedElementRenderItem.h.
References FCanvasBatchedElementRenderItem().
IsMatch()
bool FCanvasBatchedElementRenderItem::IsMatch (FBatchedElementParameters * BatchedElementParameters, const FTexture * InTexture, ESimpleElementBlendMode InBlendMode, FCanvas::EElementType InElementType, const FCanvas::FTransformEntry & InTransform, const FDepthFieldGlowInfo & InGlowInfo) inline
Determine if this is a matching set by comparing texture,blendmode,elementype,transform.
All must match
Parameters
BatchedElementParameters - parameters for this batched element
InTexture - texture resource for the item being rendered
InBlendMode - current alpha blend mode
InElementType - type of item being rendered: triangle,line,etc
InTransform - the transform for the item being rendered
InGlowInfo - the depth field glow of the item being rendered
Returns
true if the parameters match this render item
Definition at line 80 of file CanvasBatchedElementRenderItem.h.
References Data, and FCanvas::FTransformEntry::GetMatrixCRC().
Render_GameThread()
virtual bool FCanvasBatchedElementRenderItem::Render_GameThread (const FCanvas * Canvas, FCanvasRenderThreadScope & RenderScope) override virtual
Renders the canvas item.
Iterates over all batched elements and draws them with their own transforms
Parameters
Canvas - canvas currently being rendered
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
Render_RenderThread()
virtual bool FCanvasBatchedElementRenderItem::Render_RenderThread (FCanvasRenderContext & RenderContext, FMeshPassProcessorRenderState & DrawRenderState, const FCanvas * Canvas) override virtual
Renders the canvas item.
Iterates over all batched elements and draws them with their own transforms
Parameters
Canvas - canvas currently being rendered
RHICmdList - command list to use
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
Field Documentation
Data
FRenderData* FCanvasBatchedElementRenderItem::Data private
Render data which is allocated when a new FCanvasBatchedElementRenderItem is added for rendering.
This data is only freed on the rendering thread once the item has finished rendering
Definition at line 141 of file CanvasBatchedElementRenderItem.h.
Referenced by FCanvasBatchedElementRenderItem(), ~FCanvasBatchedElementRenderItem(), GetBatchedElements(), and IsMatch().
The documentation for this class was generated from the following file:
CanvasBatchedElementRenderItem.h