Unreal Engine 5.6 C++ API: Nanite::FSceneProxyBase::FMaterialSection Struct Reference
Nanite::FSceneProxyBase::FMaterialSection Struct Reference
#include "NaniteSceneProxy.h"
Public Member Functions
bool IsPixelProgrammableRaster () const
bool IsProgrammableRaster (bool bEvaluateWPO) const
bool IsVertexProgrammableRaster (bool bEvaluateWPO) const
void ResetToDefaultMaterial (bool bShading=true, bool bRaster=true)
Data Fields
uint8 bAlwaysEvaluateWPO: 1 = false
uint8 bCastShadow: 1 = false
uint8 bHasPerInstanceCustomData: 1 = false
uint8 bHasPerInstanceRandomID: 1 = false
uint8 bHidden: 1 = false
FDisplacementFadeRange DisplacementFadeRange
FDisplacementScaling DisplacementScaling
HHitProxy * HitProxy = nullptr
FVector4f LocalUVDensities = FVector4f(1.0f)
int32 MaterialIndex = INDEX_NONE
FMaterialRelevance MaterialRelevance
float MaxWPOExtent = 0.0f
FMaterialRenderProxy * RasterMaterialProxy = nullptr
FMaterialRenderProxy * ShadingMaterialProxy = nullptr
Detailed Description
Definition at line 205 of file NaniteSceneProxy.h.
Member Function Documentation
IsPixelProgrammableRaster()
bool Nanite::FSceneProxyBase::FMaterialSection::IsPixelProgrammableRaster () const inline
Definition at line 245 of file NaniteSceneProxy.h.
References MaterialRelevance.
Referenced by IsProgrammableRaster(), and IsVertexProgrammableRaster().
IsProgrammableRaster()
bool Nanite::FSceneProxyBase::FMaterialSection::IsProgrammableRaster (bool bEvaluateWPO) const inline
Definition at line 233 of file NaniteSceneProxy.h.
References IsPixelProgrammableRaster(), and IsVertexProgrammableRaster().
IsVertexProgrammableRaster()
bool Nanite::FSceneProxyBase::FMaterialSection::IsVertexProgrammableRaster (bool bEvaluateWPO) const inline
Definition at line 238 of file NaniteSceneProxy.h.
References IsPixelProgrammableRaster(), and MaterialRelevance.
Referenced by IsProgrammableRaster().
ResetToDefaultMaterial()
void Nanite::FSceneProxyBase::FMaterialSection::ResetToDefaultMaterial (bool bShading = true, bool bRaster = true)
Field Documentation
bAlwaysEvaluateWPO
uint8 Nanite::FSceneProxyBase::FMaterialSection::bAlwaysEvaluateWPO
Definition at line 226 of file NaniteSceneProxy.h.
bCastShadow
uint8 Nanite::FSceneProxyBase::FMaterialSection::bCastShadow
Definition at line 225 of file NaniteSceneProxy.h.
bHasPerInstanceCustomData
uint8 Nanite::FSceneProxyBase::FMaterialSection::bHasPerInstanceCustomData
Definition at line 223 of file NaniteSceneProxy.h.
bHasPerInstanceRandomID
uint8 Nanite::FSceneProxyBase::FMaterialSection::bHasPerInstanceRandomID
Definition at line 222 of file NaniteSceneProxy.h.
bHidden
uint8 Nanite::FSceneProxyBase::FMaterialSection::bHidden
Definition at line 224 of file NaniteSceneProxy.h.
DisplacementFadeRange
FDisplacementFadeRange Nanite::FSceneProxyBase::FMaterialSection::DisplacementFadeRange
Definition at line 217 of file NaniteSceneProxy.h.
DisplacementScaling
FDisplacementScaling Nanite::FSceneProxyBase::FMaterialSection::DisplacementScaling
Definition at line 216 of file NaniteSceneProxy.h.
HitProxy
HHitProxy* Nanite::FSceneProxyBase::FMaterialSection::HitProxy = nullptr
Definition at line 211 of file NaniteSceneProxy.h.
LocalUVDensities
FVector4f Nanite::FSceneProxyBase::FMaterialSection::LocalUVDensities = FVector4f(1.0f)
Definition at line 220 of file NaniteSceneProxy.h.
MaterialIndex
int32 Nanite::FSceneProxyBase::FMaterialSection::MaterialIndex = INDEX_NONE
Definition at line 213 of file NaniteSceneProxy.h.
MaterialRelevance
FMaterialRelevance Nanite::FSceneProxyBase::FMaterialSection::MaterialRelevance
Definition at line 219 of file NaniteSceneProxy.h.
Referenced by IsPixelProgrammableRaster(), and IsVertexProgrammableRaster().
MaxWPOExtent
float Nanite::FSceneProxyBase::FMaterialSection::MaxWPOExtent = 0.0f
Definition at line 214 of file NaniteSceneProxy.h.
RasterMaterialProxy
FMaterialRenderProxy* Nanite::FSceneProxyBase::FMaterialSection::RasterMaterialProxy = nullptr
Definition at line 207 of file NaniteSceneProxy.h.
ShadingMaterialProxy
FMaterialRenderProxy* Nanite::FSceneProxyBase::FMaterialSection::ShadingMaterialProxy = nullptr
Definition at line 208 of file NaniteSceneProxy.h.
The documentation for this struct was generated from the following file:
NaniteSceneProxy.h