Unreal Engine 5.6 C++ API: FEditorModeTools Class Reference
FEditorModeTools Class Reference
A helper class to store the state of the various editor modes.
#include "EditorModeManager.h"
Public Member Functions
UNREALED_API FEditorModeTools ()
virtual UNREALED_API ~FEditorModeTools ()
UNREALED_API void ActivateDefaultMode ()
Activates the default modes defined by this class.
UNREALED_API void ActivateMode (FEditorModeID InID, bool bToggle=false)
Activates an editor mode.
UNREALED_API void ActorMoveNotify ()
UNREALED_API void ActorPropChangeNotify ()
UNREALED_API void ActorsDuplicatedNotify (TArray< AActor * > &InPreDuplicateSelection, TArray< AActor * > &InPostDuplicateSelection, const bool bOffsetLocations)
UNREALED_API void ActorSelectionChangeNotify ()
UNREALED_API void AddDefaultMode (const FEditorModeID DefaultModeID)
Adds a new default mode to this tool's list of default modes.
virtual UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
UNREALED_API bool AllowsViewportDragTool () const
UNREALED_API bool AllowWidgetMove () const
True if we should allow widget move.
UNREALED_API bool BeginTransform (const FGizmoState &InState)
UNREALED_API bool BoxSelect (FBox &InBox, bool InSelect)
Notifies all active modes of box selection attempts.
void BroadcastCoordSystemChanged (ECoordSystem InCoordSystem)
Broadcasts the CoordSystemChangedEvent event.
void BroadcastEditorModeIDChanged (const FEditorModeID &ModeID, bool IsEnteringMode)
Broadcasts the EditorModeIDChanged event.
void BroadcastIsEditingDisallowedChanged ()
Broadcasts the IsEditingDisallowedChangedEvent event.
void BroadcastWidgetModeChanged (UE::Widget::EWidgetMode InWidgetMode)
Broadcasts the WidgetModeChanged event.
UNREALED_API bool CanAutoSave () const
returns true if all active EdModes are OK with an AutoSave happening now
UNREALED_API bool CanCycleWidgetMode () const
Check with modes to see if the widget mode can be cycled.
UNREALED_API bool CapturedMouseMove (FEditorViewportClient *InViewportClient, FViewport *InViewport, int32 InMouseX, int32 InMouseY)
Notifies all active modes of captured mouse movement.
UNREALED_API bool ComputeBoundingBoxForViewportFocus (AActor *Actor, UPrimitiveComponent *PrimitiveComponent, FBox &InOutBox)
Allows editor modes to override the bounding box used to focus the viewport on a selection.
UNREALED_API void CycleWidgetMode (void)
Cycle the widget mode, forwarding queries to modes.
UNREALED_API void DeactivateAllModes ()
Deactivates all modes, note some modes can never be deactivated.
UNREALED_API void DeactivateMode (FEditorModeID InID)
Deactivates an editor mode.
DECLARE_EVENT (FEditorModeTools, FIsEditingDisallowedChangedEvent)
Delegate type for triggering when a mode Editing Disallowed changed.
DECLARE_EVENT_OneParam (FEditorModeTools, FCoordSystemChangedEvent, ECoordSystem)
delegate type for triggering when coordinate system changed
DECLARE_EVENT_OneParam (FEditorModeTools, FWidgetModeChangedEvent, UE::Widget::EWidgetMode)
delegate type for triggering when widget mode changed
DECLARE_EVENT_TwoParams (FEditorModeTools, FEditorModeIDChangedEvent, const FEditorModeID &, bool)
Multicast delegate for OnModeEntered and OnModeExited callbacks.
UNREALED_API void DestroyMode (FEditorModeID InID)
Deactivate the mode and entirely purge it from memory.
UNREALED_API bool DisallowMouseDeltaTracking () const
True if we should disallow mouse delta tracking.
UNREALED_API void DrawActiveModes (const FSceneView *InView, FPrimitiveDrawInterface *PDI)
Draws all active modes.
UNREALED_API void DrawHUD (FEditorViewportClient *InViewportClient, FViewport *Viewport, const FSceneView *View, FCanvas *Canvas)
Draws the HUD for all active modes.
UNREALED_API void ElementSelectionChangeNotify ()
UNREALED_API bool EndTracking (FEditorViewportClient *InViewportClient, FViewport *InViewport)
UNREALED_API bool EndTransform (const FGizmoState &InState) const
UNREALED_API bool EnsureNotInMode (FEditorModeID ModeID, const FText &ErrorMsg=FText::GetEmpty(), bool bNotifyUser=false) const
Returns true if the current mode is not the specified ModeID.
UNREALED_API bool FrustumSelect (const FConvexVolume &InFrustum, FEditorViewportClient *InViewportClient, bool InSelect)
Notifies all active modes of frustum selection attempts.
UNREALED_API EEditAction::Type GetActionEditCopy ()
UNREALED_API EEditAction::Type GetActionEditCut ()
UNREALED_API EEditAction::Type GetActionEditDelete ()
UNREALED_API EEditAction::Type GetActionEditDuplicate ()
UNREALED_API EEditAction::Type GetActionEditPaste ()
UNREALED_API FEdMode * GetActiveMode (FEditorModeID InID)
Returns a pointer to an active mode specified by the passed in ID If the editor mode is not active, NULL is returned.
UNREALED_API const FEdMode * GetActiveMode (FEditorModeID InID) const
template<typename SpecificModeType>
SpecificModeType * GetActiveModeTyped (FEditorModeID InID)
template<typename SpecificModeType>
const SpecificModeType * GetActiveModeTyped (FEditorModeID InID) const
UNREALED_API UEdMode * GetActiveScriptableMode (FEditorModeID InID) const
UNREALED_API const FModeTool * GetActiveTool (FEditorModeID InID) const
Returns the active tool of the passed in editor mode.
UNREALED_API ECoordSystem GetCoordSystem (bool bGetRawValue=false) const
Returns the current CoordSystem.
UNREALED_API bool GetCursor (EMouseCursor::Type &OutCursor) const
Get a cursor to override the default with, if any.
UNREALED_API FMatrix GetCustomDrawingCoordinateSystem () const
UNREALED_API FMatrix GetCustomInputCoordinateSystem () const
virtual UNREALED_API UTypedElementSelectionSet * GetEditorSelectionSet () const
Returns the selection set for the toolkit host.
UNREALED_API FMatrix GetExplicitCoordinateSystem () const
UNREALED_API FEditorViewportClient * GetFocusedViewportClient () const
Returns the currently focused viewport client.
UNREALED_API UEditorTransformGizmoContextObject * GetGizmoContext () const
UNREALED_API IGizmoStateTarget * GetGizmoStateTarget ()
Begin New TRS Gizmo interface.
UNREALED_API FEditorViewportClient * GetHoveredViewportClient () const
Returns the currently hovered viewport client.
UNREALED_API UModeManagerInteractiveToolsContext * GetInteractiveToolsContext () const
UNREALED_API FMatrix GetLocalCoordinateSystem () const
UNREALED_API bool GetOverrideCursorVisibility (bool &bWantsOverride, bool &bHardwareCursorVisible, bool bSoftwareCursorVisible) const
Get override cursor visibility settings.
UNREALED_API FMatrix GetParentSpaceCoordinateSystem () const
UNREALED_API bool GetPivotForOrbit (FVector &OutPivot) const
Get a pivot point specified by any active modes around which the camera should orbit.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
UNREALED_API const FRotationContext & GetRotationContext () const
virtual UNREALED_API USelection * GetSelectedActors () const
Returns the set of selected actors.
virtual UNREALED_API USelection * GetSelectedComponents () const
Returns the set of selected components.
virtual UNREALED_API USelection * GetSelectedObjects () const
UNREALED_API bool GetShowWidget () const
UNREALED_API TSharedPtr< IToolkitHost > GetToolkitHost () const
Returns the host for toolkits created via modes from this mode manager.
virtual UNREALED_API UTexture2D * GetVertexTexture () const
UNREALED_API EAxisList::Type GetWidgetAxisToDraw (UE::Widget::EWidgetMode InWidgetMode) const
Gets the widget axis to be drawn.
UNREALED_API FVector GetWidgetLocation () const
Returns a good location to draw the widget at.
UNREALED_API UE::Widget::EWidgetMode GetWidgetMode () const
Retrieves the current widget mode, taking overrides into account.
UNREALED_API float GetWidgetScale () const
Get Widget Scale.
virtual UNREALED_API UWorld * GetWorld () const
Returns the world that is being edited by this mode manager.
UNREALED_API bool HandleClick (FEditorViewportClient *InViewportClient, HHitProxy *HitProxy, const FViewportClick &Click)
Notifies all active modes of mouse click messages.
UNREALED_API bool HasOngoingTransform () const
UNREALED_API bool HasToolkitHost () const
Check if toolkit host exists.
UNREALED_API bool InputAxis (FEditorViewportClient *InViewportClient, FViewport *Viewport, int32 ControllerId, FKey Key, float Delta, float DeltaTime)
Notifies all active modes of axis movement.
UNREALED_API bool InputDelta (FEditorViewportClient *InViewportClient, FViewport *InViewport, FVector &InDrag, FRotator &InRot, FVector &InScale)
Notifies all active modes of any change in mouse movement.
UNREALED_API bool InputKey (FEditorViewportClient *InViewportClient, FViewport *Viewport, FKey Key, EInputEvent Event, bool bRouteToToolsContext=true)
Notifies all active modes of keyboard input.
bool IsDefaultMode (const FEditorModeID ModeID) const
Returns whether or not the provided mode ID is a default mode.
UNREALED_API bool IsDefaultModeActive () const
Returns true if the default modes are active.
UNREALED_API bool IsEditingDisallowed (AActor *InActor) const
UNREALED_API bool IsModeActive (FEditorModeID InID) const
Returns true if the passed in editor mode is active.
UNREALED_API bool IsOnlyActiveMode (FEditorModeID InMode) const
UNREALED_API bool IsOnlyVisibleActiveMode (FEditorModeID InMode) const
UNREALED_API bool IsOperationSupportedForCurrentAsset (EAssetOperation InOperation) const
returns true if all active EdModes are OK support operation on current asset
UNREALED_API bool IsSelectionAllowed (AActor *InActor, const bool bInSelected) const
UNREALED_API bool IsSelectionHandled (AActor *InActor, const bool bInSelected) const
UNREALED_API bool IsSnapRotationEnabled () const
bool IsTracking () const
bool IsViewportUIHidden () const
Is the viewport UI hidden?
UNREALED_API void LoadConfig (void)
Loads the state that was saved in the INI file.
UNREALED_API void LoadWidgetSettings ()
Load Widget Settings from Ini file.
UNREALED_API bool LostFocus (FEditorViewportClient *InViewportClient, FViewport *Viewport)
Notifies all active modes that a viewport has lost focus.
UNREALED_API void MapChangeNotify ()
Notifies all active modes that a map change has occured.
UNREALED_API bool MouseEnter (FEditorViewportClient *InViewportClient, FViewport *Viewport, int32 X, int32 Y)
UNREALED_API bool MouseLeave (FEditorViewportClient *InViewportClient, FViewport *Viewport)
UNREALED_API bool MouseMove (FEditorViewportClient *InViewportClient, FViewport *Viewport, int32 X, int32 Y)
Notifies all active modes that the mouse has moved.
FCoordSystemChangedEvent & OnCoordSystemChanged ()
FEditorModeIDChangedEvent & OnEditorModeIDChanged ()
FIsEditingDisallowedChangedEvent & OnIsEditingDisallowedChanged ()
UNREALED_API bool OnRequestClose ()
Called by Editors when they are about to close.
FWidgetModeChangedEvent & OnWidgetModeChanged ()
UNREALED_API bool PostConvertMouseMovement (FEditorViewportClient *InViewportClient)
Called after converting mouse movement to drag/rot.
virtual UNREALED_API void PostRedo (bool bSuccess) override
Signal that client should run any PostRedo code.
virtual UNREALED_API void PostUndo (bool bSuccess) override
Calls PostUndo on all active modes.
UNREALED_API bool PreConvertMouseMovement (FEditorViewportClient *InViewportClient)
Called before converting mouse movement to drag/rot.
UNREALED_API bool ProcessCapturedMouseMoves (FEditorViewportClient *InViewportClient, FViewport *InViewport, const TArrayView< FIntPoint > &CapturedMouseMoves)
Notifies all active modes of all captured mouse movement.
UNREALED_API bool ProcessEditCopy ()
UNREALED_API bool ProcessEditCut ()
UNREALED_API bool ProcessEditDelete ()
UNREALED_API bool ProcessEditDuplicate ()
UNREALED_API bool ProcessEditPaste ()
UNREALED_API bool ReceivedFocus (FEditorViewportClient *InViewportClient, FViewport *Viewport)
Notifies all active modes that a viewport has received focus.
UNREALED_API void RemoveAllDelegateHandlers ()
UNREALED_API void RemoveDefaultMode (const FEditorModeID DefaultModeID)
Removes a default mode.
UNREALED_API void Render (const FSceneView *InView, FViewport *Viewport, FPrimitiveDrawInterface *PDI)
Renders all active modes.
UNREALED_API void RestoreSelection (FName SelectionStoreKey)
Restores the selection to the state that was stored using the given key.
UNREALED_API void SaveConfig (void)
Saves the current state to the INI file.
UNREALED_API void SaveWidgetSettings ()
Save Widget Settings to Ini file.
UNREALED_API bool SelectionHasSceneComponent () const
Whether or not the current selection has a scene component selected.
UNREALED_API void SelectNone ()
Notifies all active modes to empty their selections.
UNREALED_API void SetCoordSystem (ECoordSystem NewCoordSystem)
Sets the current CoordSystem.
UNREALED_API void SetCurrentWidgetAxis (EAxisList::Type NewAxis)
Sets the current widget axis.
UNREALED_API void SetDefaultMode (const FEditorModeID DefaultModeID)
Set the default editor mode for these tools.
void SetHideViewportUI (bool bInHideViewportUI)
Sets the hide viewport UI state.
UNREALED_API void SetPivotLocation (const FVector &Location, const bool bIncGridBase)
Sets the pivot locations.
UNREALED_API void SetSelectionHasSceneComponent (bool bHasSceneComponent)
void SetShowWidget (bool InShowWidget)
UNREALED_API void SetToolkitHost (TSharedRef< IToolkitHost > Host)
Sets the host for toolkits created via modes from this mode manager (can only be called once)
UNREALED_API void SetWidgetMode (UE::Widget::EWidgetMode InWidgetMode)
Changes the current widget mode.
UNREALED_API void SetWidgetModeOverride (UE::Widget::EWidgetMode InWidgetMode)
Allows you to temporarily override the widget mode.
UNREALED_API void SetWidgetScale (float InScale)
Set Scale On The Widget.
UNREALED_API bool ShouldDrawBrushVertices () const
true if brush vertices should be drawn
UNREALED_API bool ShouldDrawBrushWireframe (AActor *InActor) const
true if the passed in brush actor should be drawn in wireframe
UNREALED_API bool SnapRotatorToGridOverride (FRotator &InRotation) const
UNREALED_API bool StartTracking (FEditorViewportClient *InViewportClient, FViewport *InViewport)
Mouse tracking interface.
UNREALED_API void StoreSelection (FName SelectionStoreKey, bool bClearSelection=true)
Stores the current selection under the given key, and clears the current selection state if requested.
UNREALED_API void Tick (FEditorViewportClient *ViewportClient, float DeltaTime)
Ticks all active modes.
UE_DEPRECATED (4.26, "Individual toolkit hosts, such as the level editor, should handle determining if they show a mode toolbox for hosted toolkits.") UNREALED_API bool ShouldShowModeToolbox() const
Whether or not the mode toolbox (where mode details panels and some tools are) should be shown.
UE_DEPRECATED (5.0, "This function is redundant, and is handled as part of a call to ActivateMode.") UNREALED_API void DeactivateOtherVisibleModes(FEditorModeID InMode)
UNREALED_API void UpdateInternalData ()
UNREALED_API bool UsesTransformWidget () const
true if any active mode uses a transform widget
UNREALED_API bool UsesTransformWidget (UE::Widget::EWidgetMode CheckMode) const
true if any active mode uses the passed in transform widget
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FEditorUndoClient
virtual UNREALED_API ~FEditorUndoClient ()
Always unregister for undo on destruction, just in case.
virtual FString GetTransactionContext () const
Return the transaction context for this client.
virtual bool MatchesContext (const FTransactionContext &InContext, const TArray< TPair< UObject *, FTransactionObjectEvent > > &TransactionObjectContexts) const
Called to see if the context of the current undo/redo operation is a match for the client Default state matching old context-less undo is Context="" and PrimaryObject=NULL.
Public Member Functions inherited from TSharedFromThis< FEditorModeTools >
TSharedRef< FEditorModeTools, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FEditorModeTools, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FVector CachedLocation
FVector GridBase
FString InfoString
Draws in the top level corner of all FEditorViewportClient windows (can be used to relay info to the user).
FVector PivotLocation
bool PivotShown
bool SnappedActor
FVector SnappedLocation
bool Snapping
float TranslateRotate2DAngle
The angles for the 2d translate rotate widget.
float TranslateRotateXAxisAngle
The angle for the translate rotate widget.
Protected Member Functions
UNREALED_API void DeactivateModeAtIndex (int32 Index)
virtual UNREALED_API void DrawBrackets (FEditorViewportClient *ViewportClient, FViewport *Viewport, const FSceneView *View, FCanvas *Canvas)
UNREALED_API void ExitAllModesPendingDeactivate ()
UNREALED_API void ExitMode (UEdMode *InMode)
Exits the given editor mode.
template<class InterfaceToCastTo>
void ForEachEdMode (TFunctionRef< bool(InterfaceToCastTo *)> InCallback) const
UNREALED_API void ForEachEdMode (TFunctionRef< bool(UEdMode *)> InCalllback) const
FMatrix GetCustomCoordinateSystem (TUniqueFunction< void(const TTypedElement< ITypedElementWorldInterface > &, FTransform &)> &&InGetTransformFunc) const
Returns the custom coordinate matrix using a callback-type request.
UNREALED_API void OnEditorSelectionChanged (UObject *NewSelection)
End New TRS Gizmo interface.
UNREALED_API void OnEditorSelectNone ()
UNREALED_API void OnModeUnregistered (FEditorModeID ModeID)
Removes the mode ID from the tools manager when a mode is unregistered.
UNREALED_API void OnWorldCleanup (UWorld *InWorld, bool bSessionEnded, bool bCleanupResources)
Handles the notification when a world is going through GC to clean up any modes pending deactivation.
UNREALED_API bool TestAllModes (TFunctionRef< bool(UEdMode *)> InCalllback, bool bExpected) const
Protected Member Functions inherited from TSharedFromThis< FEditorModeTools >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< TObjectPtr< UEdMode > > ActiveScriptableModes
A list of active editor modes.
bool bHideViewportUI
if true, the viewports will hide all UI overlays
bool bSelectionHasSceneComponent
if true the current selection has a scene component
bool bShowWidget
If 1, draw the widget and let the user interact with it.
TArray< FEditorModeID > DefaultModeIDs
List of default modes for this tool.
TObjectPtr< UModeManagerInteractiveToolsContext > InteractiveToolsContext
UE::Widget::EWidgetMode OverrideWidgetMode
If the widget mode is being overridden, this will be != WM_None.
TMap< FEditorModeID, TObjectPtr< UEdMode > > PendingDeactivateModes
A list of previously active editor modes that we will potentially recycle.
TMap< FEditorModeID, TObjectPtr< UEdMode > > RecycledScriptableModes
A list of previously active editor modes that we will potentially recycle.
TWeakPtr< IToolkitHost > ToolkitHost
The host of the toolkits created by these modes.
UE::Widget::EWidgetMode WidgetMode
The mode that the editor viewport widget is in.
float WidgetScale
Scale Factor for Widget.
Private Attributes
bool bHasOngoingTransform = false
Flag to track if we started a new TRS gizmo transform.
bool bIsExitingModesDuringTick = false
Guard to prevent modes from entering as part of their exit routine.
bool bIsTracking
Flag set between calls to StartTracking() and EndTracking()
ECoordSystem CoordSystem
The coordinate system the widget is operating within.
FCoordSystemChangedEvent CoordSystemChangedEvent
Multicast delegate that is broadcast when the coordinate system is changed.
FEditorModeIDChangedEvent EditorModeIDChangedEvent
Multicast delegate that is broadcast when a mode is entered or exited.
FEditorViewportClient * FocusedViewportClient = nullptr
FEditorViewportClient * HoveredViewportClient = nullptr
FIsEditingDisallowedChangedEvent IsEditingDisallowedChangedEvent
Multicast delegate that is broadcast when a mode Editing Disallowed changed.
TMap< FName, FTypedElementSelectionSetState > StoredSelectionSets
TWeakObjectPtr< UEditorTransformGizmoContextObject > WeakGizmoContext
GizmoContext used to get context specific gizmo properties.
TWeakObjectPtr< UEditorGizmoStateTarget > WeakGizmoStateTarget
GizmoStateTarget used to handle a new TRS gizmo transform begin/end sequence.
FWidgetModeChangedEvent WidgetModeChangedEvent
Multicast delegate that is broadcast when a widget mode is changed.
Static Private Attributes
static TAutoConsoleVariable< int32 > CVarEnableITFCursorOverrideSupport
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from TSharedFromThis< FEditorModeTools >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A helper class to store the state of the various editor modes.
Definition at line 42 of file EditorModeManager.h.
Constructor & Destructor Documentation
FEditorModeTools()
UNREALED_API FEditorModeTools::FEditorModeTools ()
Referenced by DECLARE_EVENT(), DECLARE_EVENT_OneParam(), DECLARE_EVENT_OneParam(), and DECLARE_EVENT_TwoParams().
~FEditorModeTools()
virtual UNREALED_API FEditorModeTools::~FEditorModeTools () virtual
Member Function Documentation
ActivateDefaultMode()
UNREALED_API void FEditorModeTools::ActivateDefaultMode ()
Activates the default modes defined by this class.
Note that there can be more than one default mode, and this call will activate them all in sequence.
ActivateMode()
UNREALED_API void FEditorModeTools::ActivateMode (FEditorModeID InID, bool bToggle = false)
Activates an editor mode.
Shuts down all other active modes which cannot run with the passed in mode.
Parameters
InID The ID of the editor mode to activate.
bToggle true if the passed in editor mode should be toggled off if it is already active.
ActorMoveNotify()
UNREALED_API void FEditorModeTools::ActorMoveNotify ()
References ActorMoveNotify().
Referenced by ActorMoveNotify().
ActorPropChangeNotify()
UNREALED_API void FEditorModeTools::ActorPropChangeNotify ()
References ActorPropChangeNotify().
Referenced by ActorPropChangeNotify().
ActorsDuplicatedNotify()
UNREALED_API void FEditorModeTools::ActorsDuplicatedNotify (TArray< AActor * > & InPreDuplicateSelection, TArray< AActor * > & InPostDuplicateSelection, const bool bOffsetLocations)
References ActorsDuplicatedNotify().
Referenced by ActorsDuplicatedNotify().
ActorSelectionChangeNotify()
UNREALED_API void FEditorModeTools::ActorSelectionChangeNotify ()
References ActorSelectionChangeNotify().
Referenced by ActorSelectionChangeNotify().
AddDefaultMode()
UNREALED_API void FEditorModeTools::AddDefaultMode (const FEditorModeID DefaultModeID)
Adds a new default mode to this tool's list of default modes.
You can have multiple default modes, but they all must be compatible with each other.
Parameters
DefaultModeID The mode ID for the new default mode
AddReferencedObjects()
virtual UNREALED_API void FEditorModeTools::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Reimplemented in IPersonaEditorModeManager.
AllowsViewportDragTool()
UNREALED_API bool FEditorModeTools::AllowsViewportDragTool () const
AllowWidgetMove()
UNREALED_API bool FEditorModeTools::AllowWidgetMove () const
True if we should allow widget move.
BeginTransform()
UNREALED_API bool FEditorModeTools::BeginTransform (const FGizmoState & InState)
References BeginTransform().
Referenced by BeginTransform().
BoxSelect()
UNREALED_API bool FEditorModeTools::BoxSelect (FBox & InBox, bool InSelect)
Notifies all active modes of box selection attempts.
BroadcastCoordSystemChanged()
void FEditorModeTools::BroadcastCoordSystemChanged (ECoordSystem InCoordSystem) inline
Broadcasts the CoordSystemChangedEvent event.
Definition at line 399 of file EditorModeManager.h.
References CoordSystemChangedEvent.
BroadcastEditorModeIDChanged()
void FEditorModeTools::BroadcastEditorModeIDChanged (const FEditorModeID & ModeID, bool IsEnteringMode) inline
Broadcasts the EditorModeIDChanged event.
Definition at line 392 of file EditorModeManager.h.
References EditorModeIDChangedEvent.
BroadcastIsEditingDisallowedChanged()
void FEditorModeTools::BroadcastIsEditingDisallowedChanged () inline
Broadcasts the IsEditingDisallowedChangedEvent event.
Definition at line 406 of file EditorModeManager.h.
References IsEditingDisallowedChangedEvent.
BroadcastWidgetModeChanged()
void FEditorModeTools::BroadcastWidgetModeChanged (UE::Widget::EWidgetMode InWidgetMode) inline
Broadcasts the WidgetModeChanged event.
Definition at line 389 of file EditorModeManager.h.
References WidgetModeChangedEvent.
CanAutoSave()
UNREALED_API bool FEditorModeTools::CanAutoSave () const
returns true if all active EdModes are OK with an AutoSave happening now
References CanAutoSave().
Referenced by CanAutoSave().
CanCycleWidgetMode()
UNREALED_API bool FEditorModeTools::CanCycleWidgetMode () const
Check with modes to see if the widget mode can be cycled.
CapturedMouseMove()
UNREALED_API bool FEditorModeTools::CapturedMouseMove (FEditorViewportClient * InViewportClient, FViewport * InViewport, int32 InMouseX, int32 InMouseY)
Notifies all active modes of captured mouse movement.
ComputeBoundingBoxForViewportFocus()
UNREALED_API bool FEditorModeTools::ComputeBoundingBoxForViewportFocus (AActor * Actor, UPrimitiveComponent * PrimitiveComponent, FBox & InOutBox)
Allows editor modes to override the bounding box used to focus the viewport on a selection.
Parameters
Actor The selected actor that is being considered for focus
PrimitiveComponent The component in the actor being considered for focus
InOutBox The box that should be computed for the actor and component
Returns
bool true if a mode overrides the box and populated InOutBox, false if it did not populate InOutBox
References Actor.
CycleWidgetMode()
UNREALED_API void FEditorModeTools::CycleWidgetMode (void)
Cycle the widget mode, forwarding queries to modes.
DeactivateAllModes()
UNREALED_API void FEditorModeTools::DeactivateAllModes ()
Deactivates all modes, note some modes can never be deactivated.
References DeactivateAllModes().
Referenced by DeactivateAllModes().
DeactivateMode()
UNREALED_API void FEditorModeTools::DeactivateMode (FEditorModeID InID)
Deactivates an editor mode.
Parameters
InID The ID of the editor mode to deactivate.
DeactivateModeAtIndex()
UNREALED_API void FEditorModeTools::DeactivateModeAtIndex (int32 Index) protected
References DeactivateModeAtIndex().
Referenced by DeactivateModeAtIndex().
DECLARE_EVENT()
FEditorModeTools::DECLARE_EVENT (FEditorModeTools , FIsEditingDisallowedChangedEvent)
Delegate type for triggering when a mode Editing Disallowed changed.
References FEditorModeTools().
DECLARE_EVENT_OneParam() [1/2]
FEditorModeTools::DECLARE_EVENT_OneParam (FEditorModeTools , FCoordSystemChangedEvent , ECoordSystem)
delegate type for triggering when coordinate system changed
References FEditorModeTools().
DECLARE_EVENT_OneParam() [2/2]
FEditorModeTools::DECLARE_EVENT_OneParam (FEditorModeTools , FWidgetModeChangedEvent , UE::Widget::EWidgetMode)
delegate type for triggering when widget mode changed
References FEditorModeTools().
DECLARE_EVENT_TwoParams()
FEditorModeTools::DECLARE_EVENT_TwoParams (FEditorModeTools , FEditorModeIDChangedEvent , const FEditorModeID & , bool)
Multicast delegate for OnModeEntered and OnModeExited callbacks.
First parameter: The editor mode that was changed Second parameter: True if entering the mode, or false if exiting the mode
References FEditorModeTools().
DestroyMode()
UNREALED_API void FEditorModeTools::DestroyMode (FEditorModeID InID)
Deactivate the mode and entirely purge it from memory.
Used when a mode type is unregistered
DisallowMouseDeltaTracking()
UNREALED_API bool FEditorModeTools::DisallowMouseDeltaTracking () const
True if we should disallow mouse delta tracking.
DrawActiveModes()
UNREALED_API void FEditorModeTools::DrawActiveModes (const FSceneView * InView, FPrimitiveDrawInterface * PDI)
Draws all active modes.
DrawBrackets()
virtual UNREALED_API void FEditorModeTools::DrawBrackets (FEditorViewportClient * ViewportClient, FViewport * Viewport, const FSceneView * View, FCanvas * Canvas) protected virtual
References DrawBrackets().
Referenced by DrawBrackets().
DrawHUD()
UNREALED_API void FEditorModeTools::DrawHUD (FEditorViewportClient * InViewportClient, FViewport * Viewport, const FSceneView * View, FCanvas * Canvas)
Draws the HUD for all active modes.
ElementSelectionChangeNotify()
UNREALED_API void FEditorModeTools::ElementSelectionChangeNotify ()
References ElementSelectionChangeNotify().
Referenced by ElementSelectionChangeNotify().
EndTracking()
UNREALED_API bool FEditorModeTools::EndTracking (FEditorViewportClient * InViewportClient, FViewport * InViewport)
EndTransform()
UNREALED_API bool FEditorModeTools::EndTransform (const FGizmoState & InState) const
References EndTransform().
Referenced by EndTransform().
EnsureNotInMode()
UNREALED_API bool FEditorModeTools::EnsureNotInMode (FEditorModeID ModeID, const FText & ErrorMsg = FText::GetEmpty(), bool bNotifyUser = false) const
Returns true if the current mode is not the specified ModeID.
Also optionally warns the user.
Parameters
ModeID The editor mode to query.
ErrorMsg If specified, inform the user the reason why this is a problem
bNotifyUser If true, display the error as a notification, instead of a dialog
Returns
true if the current mode is not the specified mode.
References EnsureNotInMode().
Referenced by EnsureNotInMode().
ExitAllModesPendingDeactivate()
UNREALED_API void FEditorModeTools::ExitAllModesPendingDeactivate () protected
ExitMode()
UNREALED_API void FEditorModeTools::ExitMode (UEdMode * InMode) protected
Exits the given editor mode.
References ExitMode().
Referenced by ExitMode().
ForEachEdMode() [1/2]
template<class InterfaceToCastTo> void FEditorModeTools::ForEachEdMode (TFunctionRef< bool(InterfaceToCastTo *)> InCallback) const inline protected
Definition at line 578 of file EditorModeManager.h.
References Cast(), and ForEachEdMode().
ForEachEdMode() [2/2]
UNREALED_API void FEditorModeTools::ForEachEdMode (TFunctionRef< bool(UEdMode *)> InCalllback) const protected
References ForEachEdMode().
Referenced by ForEachEdMode(), and ForEachEdMode().
FrustumSelect()
UNREALED_API bool FEditorModeTools::FrustumSelect (const FConvexVolume & InFrustum, FEditorViewportClient * InViewportClient, bool InSelect)
Notifies all active modes of frustum selection attempts.
GetActionEditCopy()
UNREALED_API EEditAction::Type FEditorModeTools::GetActionEditCopy ()
GetActionEditCut()
UNREALED_API EEditAction::Type FEditorModeTools::GetActionEditCut ()
GetActionEditDelete()
UNREALED_API EEditAction::Type FEditorModeTools::GetActionEditDelete ()
GetActionEditDuplicate()
UNREALED_API EEditAction::Type FEditorModeTools::GetActionEditDuplicate ()
GetActionEditPaste()
UNREALED_API EEditAction::Type FEditorModeTools::GetActionEditPaste ()
GetActiveMode() [1/2]
UNREALED_API FEdMode * FEditorModeTools::GetActiveMode (FEditorModeID InID)
Returns a pointer to an active mode specified by the passed in ID If the editor mode is not active, NULL is returned.
References GetActiveMode().
Referenced by GetActiveMode(), GetActiveMode(), GetActiveModeTyped(), and GetActiveModeTyped().
GetActiveMode() [2/2]
UNREALED_API const FEdMode * FEditorModeTools::GetActiveMode (FEditorModeID InID) const
References GetActiveMode().
GetActiveModeTyped() [1/2]
template<typename SpecificModeType> SpecificModeType * FEditorModeTools::GetActiveModeTyped (FEditorModeID InID) inline
Definition at line 159 of file EditorModeManager.h.
References GetActiveMode(), and GetActiveModeTyped().
Referenced by GetActiveModeTyped().
GetActiveModeTyped() [2/2]
template<typename SpecificModeType> const SpecificModeType * FEditorModeTools::GetActiveModeTyped (FEditorModeID InID) const inline
Definition at line 165 of file EditorModeManager.h.
References GetActiveMode().
GetActiveScriptableMode()
UNREALED_API UEdMode * FEditorModeTools::GetActiveScriptableMode (FEditorModeID InID) const
References GetActiveScriptableMode().
Referenced by GetActiveScriptableMode().
GetActiveTool()
UNREALED_API const FModeTool * FEditorModeTools::GetActiveTool (FEditorModeID InID) const
Returns the active tool of the passed in editor mode.
If the passed in editor mode is not active or the mode has no active tool, NULL is returned
GetCoordSystem()
UNREALED_API ECoordSystem FEditorModeTools::GetCoordSystem (bool bGetRawValue = false) const
Returns the current CoordSystem.
Parameters
bGetRawValue true when you want the actual value of CoordSystem, not the value modified by the state.
GetCursor()
UNREALED_API bool FEditorModeTools::GetCursor (EMouseCursor::Type & OutCursor) const
Get a cursor to override the default with, if any.
GetCustomCoordinateSystem()
FMatrix FEditorModeTools::GetCustomCoordinateSystem (TUniqueFunction< void(const TTypedElement< ITypedElementWorldInterface > &, FTransform &)> && InGetTransformFunc) const protected
Returns the custom coordinate matrix using a callback-type request.
GetCustomDrawingCoordinateSystem()
UNREALED_API FMatrix FEditorModeTools::GetCustomDrawingCoordinateSystem () const
References GetCustomDrawingCoordinateSystem().
Referenced by GetCustomDrawingCoordinateSystem().
GetCustomInputCoordinateSystem()
UNREALED_API FMatrix FEditorModeTools::GetCustomInputCoordinateSystem () const
References GetCustomInputCoordinateSystem().
Referenced by GetCustomInputCoordinateSystem().
GetEditorSelectionSet()
virtual UNREALED_API UTypedElementSelectionSet * FEditorModeTools::GetEditorSelectionSet () const virtual
Returns the selection set for the toolkit host.
(i.e. the selection set for the level editor)
GetExplicitCoordinateSystem()
UNREALED_API FMatrix FEditorModeTools::GetExplicitCoordinateSystem () const
References GetExplicitCoordinateSystem().
Referenced by GetExplicitCoordinateSystem().
GetFocusedViewportClient()
UNREALED_API FEditorViewportClient * FEditorModeTools::GetFocusedViewportClient () const
Returns the currently focused viewport client.
GetGizmoContext()
UNREALED_API UEditorTransformGizmoContextObject * FEditorModeTools::GetGizmoContext () const
References GetGizmoContext().
Referenced by GetGizmoContext().
GetGizmoStateTarget()
UNREALED_API IGizmoStateTarget * FEditorModeTools::GetGizmoStateTarget ()
Begin New TRS Gizmo interface.
References GetGizmoStateTarget().
Referenced by GetGizmoStateTarget().
GetHoveredViewportClient()
UNREALED_API FEditorViewportClient * FEditorModeTools::GetHoveredViewportClient () const
Returns the currently hovered viewport client.
GetInteractiveToolsContext()
UNREALED_API UModeManagerInteractiveToolsContext * FEditorModeTools::GetInteractiveToolsContext () const
Returns
ToolsContext for this Mode Manager
References GetInteractiveToolsContext().
Referenced by GetInteractiveToolsContext().
GetLocalCoordinateSystem()
UNREALED_API FMatrix FEditorModeTools::GetLocalCoordinateSystem () const
References GetLocalCoordinateSystem().
Referenced by GetLocalCoordinateSystem().
GetOverrideCursorVisibility()
UNREALED_API bool FEditorModeTools::GetOverrideCursorVisibility (bool & bWantsOverride, bool & bHardwareCursorVisible, bool bSoftwareCursorVisible) const
Get override cursor visibility settings.
GetParentSpaceCoordinateSystem()
UNREALED_API FMatrix FEditorModeTools::GetParentSpaceCoordinateSystem () const
References GetParentSpaceCoordinateSystem().
Referenced by GetParentSpaceCoordinateSystem().
GetPivotForOrbit()
UNREALED_API bool FEditorModeTools::GetPivotForOrbit (FVector & OutPivot) const
Get a pivot point specified by any active modes around which the camera should orbit.
Parameters
OutPivot The custom pivot point returned by the mode/tool
Returns
true if a custom pivot point was specified, false otherwise.
References FVector.
GetReferencerName()
virtual FString FEditorModeTools::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 351 of file EditorModeManager.h.
References TEXT.
GetRotationContext()
UNREALED_API const FRotationContext & FEditorModeTools::GetRotationContext () const
References GetRotationContext().
Referenced by GetRotationContext().
GetSelectedActors()
virtual UNREALED_API USelection * FEditorModeTools::GetSelectedActors () const virtual
Returns the set of selected actors.
Reimplemented in FAssetEditorModeManager.
GetSelectedComponents()
virtual UNREALED_API USelection * FEditorModeTools::GetSelectedComponents () const virtual
Returns the set of selected components.
Reimplemented in FAssetEditorModeManager.
GetSelectedObjects()
virtual UNREALED_API USelection * FEditorModeTools::GetSelectedObjects () const virtual
Returns
the set of selected non-actor objects.
Reimplemented in FAssetEditorModeManager.
GetShowWidget()
UNREALED_API bool FEditorModeTools::GetShowWidget () const
GetToolkitHost()
UNREALED_API TSharedPtr< IToolkitHost > FEditorModeTools::GetToolkitHost () const
Returns the host for toolkits created via modes from this mode manager.
GetVertexTexture()
virtual UNREALED_API UTexture2D * FEditorModeTools::GetVertexTexture () const virtual
References GetVertexTexture().
Referenced by GetVertexTexture().
GetWidgetAxisToDraw()
UNREALED_API EAxisList::Type FEditorModeTools::GetWidgetAxisToDraw (UE::Widget::EWidgetMode InWidgetMode) const
Gets the widget axis to be drawn.
GetWidgetLocation()
UNREALED_API FVector FEditorModeTools::GetWidgetLocation () const
Returns a good location to draw the widget at.
References FVector.
GetWidgetMode()
UNREALED_API UE::Widget::EWidgetMode FEditorModeTools::GetWidgetMode () const
Retrieves the current widget mode, taking overrides into account.
GetWidgetScale()
UNREALED_API float FEditorModeTools::GetWidgetScale () const
Get Widget Scale.
GetWorld()
virtual UNREALED_API UWorld * FEditorModeTools::GetWorld () const virtual
Returns the world that is being edited by this mode manager.
Reimplemented in FAssetEditorModeManager.
HandleClick()
UNREALED_API bool FEditorModeTools::HandleClick (FEditorViewportClient * InViewportClient, HHitProxy * HitProxy, const FViewportClick & Click)
Notifies all active modes of mouse click messages.
References Click.
HasOngoingTransform()
UNREALED_API bool FEditorModeTools::HasOngoingTransform () const
References HasOngoingTransform().
Referenced by HasOngoingTransform().
HasToolkitHost()
UNREALED_API bool FEditorModeTools::HasToolkitHost () const
Check if toolkit host exists.
InputAxis()
UNREALED_API bool FEditorModeTools::InputAxis (FEditorViewportClient * InViewportClient, FViewport * Viewport, int32 ControllerId, FKey Key, float Delta, float DeltaTime)
Notifies all active modes of axis movement.
References DeltaTime, and Key.
InputDelta()
UNREALED_API bool FEditorModeTools::InputDelta (FEditorViewportClient * InViewportClient, FViewport * InViewport, FVector & InDrag, FRotator & InRot, FVector & InScale)
Notifies all active modes of any change in mouse movement.
References FVector.
InputKey()
UNREALED_API bool FEditorModeTools::InputKey (FEditorViewportClient * InViewportClient, FViewport * Viewport, FKey Key, EInputEvent Event, bool bRouteToToolsContext = true)
Notifies all active modes of keyboard input.
Parameters
bRouteToToolsContext If true, routes to the tools context and its input router before routing to modes (and does not route to modes if tools context handles it). We currently need the ability to set this to false due to some behaviors being routed in different conditions to legacy modes compared to the input router (see its use in EditorViewportClient.cpp).
References Event, and Key.
IsDefaultMode()
bool FEditorModeTools::IsDefaultMode (const FEditorModeID ModeID) const inline
Returns whether or not the provided mode ID is a default mode.
Definition at line 72 of file EditorModeManager.h.
References DefaultModeIDs.
IsDefaultModeActive()
UNREALED_API bool FEditorModeTools::IsDefaultModeActive () const
Returns true if the default modes are active.
Note that there can be more than one default mode, and this will only return true if all default modes are active.
IsEditingDisallowed()
UNREALED_API bool FEditorModeTools::IsEditingDisallowed (AActor * InActor) const
IsModeActive()
UNREALED_API bool FEditorModeTools::IsModeActive (FEditorModeID InID) const
Returns true if the passed in editor mode is active.
References IsModeActive().
Referenced by IsModeActive().
IsOnlyActiveMode()
UNREALED_API bool FEditorModeTools::IsOnlyActiveMode (FEditorModeID InMode) const
References IsOnlyActiveMode().
Referenced by IsOnlyActiveMode().
IsOnlyVisibleActiveMode()
UNREALED_API bool FEditorModeTools::IsOnlyVisibleActiveMode (FEditorModeID InMode) const
References IsOnlyVisibleActiveMode().
Referenced by IsOnlyVisibleActiveMode().
IsOperationSupportedForCurrentAsset()
UNREALED_API bool FEditorModeTools::IsOperationSupportedForCurrentAsset (EAssetOperation InOperation) const
returns true if all active EdModes are OK support operation on current asset
References IsOperationSupportedForCurrentAsset().
Referenced by IsOperationSupportedForCurrentAsset().
IsSelectionAllowed()
UNREALED_API bool FEditorModeTools::IsSelectionAllowed (AActor * InActor, const bool bInSelected) const
IsSelectionHandled()
UNREALED_API bool FEditorModeTools::IsSelectionHandled (AActor * InActor, const bool bInSelected) const
IsSnapRotationEnabled()
UNREALED_API bool FEditorModeTools::IsSnapRotationEnabled () const
References IsSnapRotationEnabled().
Referenced by IsSnapRotationEnabled().
IsTracking()
bool FEditorModeTools::IsTracking () const inline
Definition at line 196 of file EditorModeManager.h.
References bIsTracking.
IsViewportUIHidden()
bool FEditorModeTools::IsViewportUIHidden () const inline
Is the viewport UI hidden?
Definition at line 422 of file EditorModeManager.h.
References bHideViewportUI.
LoadConfig()
UNREALED_API void FEditorModeTools::LoadConfig (void)
Loads the state that was saved in the INI file.
LoadWidgetSettings()
UNREALED_API void FEditorModeTools::LoadWidgetSettings ()
Load Widget Settings from Ini file.
LostFocus()
UNREALED_API bool FEditorModeTools::LostFocus (FEditorViewportClient * InViewportClient, FViewport * Viewport)
Notifies all active modes that a viewport has lost focus.
MapChangeNotify()
UNREALED_API void FEditorModeTools::MapChangeNotify ()
Notifies all active modes that a map change has occured.
MouseEnter()
UNREALED_API bool FEditorModeTools::MouseEnter (FEditorViewportClient * InViewportClient, FViewport * Viewport, int32 X, int32 Y)
References X, and Y.
MouseLeave()
UNREALED_API bool FEditorModeTools::MouseLeave (FEditorViewportClient * InViewportClient, FViewport * Viewport)
MouseMove()
UNREALED_API bool FEditorModeTools::MouseMove (FEditorViewportClient * InViewportClient, FViewport * Viewport, int32 X, int32 Y)
Notifies all active modes that the mouse has moved.
References X, and Y.
OnCoordSystemChanged()
FCoordSystemChangedEvent & FEditorModeTools::OnCoordSystemChanged () inline
Definition at line 396 of file EditorModeManager.h.
References CoordSystemChangedEvent.
OnEditorModeIDChanged()
FEditorModeIDChangedEvent & FEditorModeTools::OnEditorModeIDChanged () inline
Definition at line 382 of file EditorModeManager.h.
References EditorModeIDChangedEvent.
OnEditorSelectionChanged()
UNREALED_API void FEditorModeTools::OnEditorSelectionChanged (UObject * NewSelection) protected
End New TRS Gizmo interface.
Delegate handlers
References OnEditorSelectionChanged().
Referenced by OnEditorSelectionChanged().
OnEditorSelectNone()
UNREALED_API void FEditorModeTools::OnEditorSelectNone () protected
References OnEditorSelectNone().
Referenced by OnEditorSelectNone().
OnIsEditingDisallowedChanged()
FIsEditingDisallowedChangedEvent & FEditorModeTools::OnIsEditingDisallowedChanged () inline
Definition at line 403 of file EditorModeManager.h.
References IsEditingDisallowedChangedEvent.
OnModeUnregistered()
UNREALED_API void FEditorModeTools::OnModeUnregistered (FEditorModeID ModeID) protected
Removes the mode ID from the tools manager when a mode is unregistered.
References OnModeUnregistered().
Referenced by OnModeUnregistered().
OnRequestClose()
UNREALED_API bool FEditorModeTools::OnRequestClose ()
Called by Editors when they are about to close.
OnWidgetModeChanged()
FWidgetModeChangedEvent & FEditorModeTools::OnWidgetModeChanged () inline
Definition at line 386 of file EditorModeManager.h.
References WidgetModeChangedEvent.
OnWorldCleanup()
UNREALED_API void FEditorModeTools::OnWorldCleanup (UWorld * InWorld, bool bSessionEnded, bool bCleanupResources) protected
Handles the notification when a world is going through GC to clean up any modes pending deactivation.
References OnWorldCleanup().
Referenced by OnWorldCleanup().
PostConvertMouseMovement()
UNREALED_API bool FEditorModeTools::PostConvertMouseMovement (FEditorViewportClient * InViewportClient)
Called after converting mouse movement to drag/rot.
PostRedo()
virtual UNREALED_API void FEditorModeTools::PostRedo (bool bSuccess) override virtual
Signal that client should run any PostRedo code.
Parameters
bSuccess If true than redo succeeded, false if redo failed
Reimplemented from FEditorUndoClient.
PostUndo()
virtual UNREALED_API void FEditorModeTools::PostUndo (bool bSuccess) override virtual
Calls PostUndo on all active modes.
Reimplemented from FEditorUndoClient.
PreConvertMouseMovement()
UNREALED_API bool FEditorModeTools::PreConvertMouseMovement (FEditorViewportClient * InViewportClient)
Called before converting mouse movement to drag/rot.
ProcessCapturedMouseMoves()
UNREALED_API bool FEditorModeTools::ProcessCapturedMouseMoves (FEditorViewportClient * InViewportClient, FViewport * InViewport, const TArrayView< FIntPoint > & CapturedMouseMoves)
Notifies all active modes of all captured mouse movement.
ProcessEditCopy()
UNREALED_API bool FEditorModeTools::ProcessEditCopy ()
ProcessEditCut()
UNREALED_API bool FEditorModeTools::ProcessEditCut ()
ProcessEditDelete()
UNREALED_API bool FEditorModeTools::ProcessEditDelete ()
ProcessEditDuplicate()
UNREALED_API bool FEditorModeTools::ProcessEditDuplicate ()
ProcessEditPaste()
UNREALED_API bool FEditorModeTools::ProcessEditPaste ()
ReceivedFocus()
UNREALED_API bool FEditorModeTools::ReceivedFocus (FEditorViewportClient * InViewportClient, FViewport * Viewport)
Notifies all active modes that a viewport has received focus.
RemoveAllDelegateHandlers()
UNREALED_API void FEditorModeTools::RemoveAllDelegateHandlers ()
References RemoveAllDelegateHandlers().
Referenced by RemoveAllDelegateHandlers().
RemoveDefaultMode()
UNREALED_API void FEditorModeTools::RemoveDefaultMode (const FEditorModeID DefaultModeID)
Removes a default mode.
Parameters
DefaultModeID The mode ID for the default mode to remove
Render()
UNREALED_API void FEditorModeTools::Render (const FSceneView * InView, FViewport * Viewport, FPrimitiveDrawInterface * PDI)
Renders all active modes.
RestoreSelection()
UNREALED_API void FEditorModeTools::RestoreSelection (FName SelectionStoreKey)
Restores the selection to the state that was stored using the given key.
SaveConfig()
UNREALED_API void FEditorModeTools::SaveConfig (void)
Saves the current state to the INI file.
SaveWidgetSettings()
UNREALED_API void FEditorModeTools::SaveWidgetSettings ()
Save Widget Settings to Ini file.
SelectionHasSceneComponent()
UNREALED_API bool FEditorModeTools::SelectionHasSceneComponent () const
Whether or not the current selection has a scene component selected.
SelectNone()
UNREALED_API void FEditorModeTools::SelectNone ()
Notifies all active modes to empty their selections.
SetCoordSystem()
UNREALED_API void FEditorModeTools::SetCoordSystem (ECoordSystem NewCoordSystem)
Sets the current CoordSystem.
SetCurrentWidgetAxis()
UNREALED_API void FEditorModeTools::SetCurrentWidgetAxis (EAxisList::Type NewAxis)
Sets the current widget axis.
SetDefaultMode()
UNREALED_API void FEditorModeTools::SetDefaultMode (const FEditorModeID DefaultModeID)
Set the default editor mode for these tools.
Parameters
DefaultModeID The mode ID for the new default mode
SetHideViewportUI()
void FEditorModeTools::SetHideViewportUI (bool bInHideViewportUI) inline
Sets the hide viewport UI state.
Definition at line 419 of file EditorModeManager.h.
References bHideViewportUI.
SetPivotLocation()
UNREALED_API void FEditorModeTools::SetPivotLocation (const FVector & Location, const bool bIncGridBase)
Sets the pivot locations.
Parameters
Location The location to set
bIncGridBase Whether or not to also set the GridBase
References FVector, and Location.
SetSelectionHasSceneComponent()
UNREALED_API void FEditorModeTools::SetSelectionHasSceneComponent (bool bHasSceneComponent)
SetShowWidget()
void FEditorModeTools::SetShowWidget (bool InShowWidget) inline
Definition at line 176 of file EditorModeManager.h.
References bShowWidget.
SetToolkitHost()
UNREALED_API void FEditorModeTools::SetToolkitHost (TSharedRef< IToolkitHost > Host)
Sets the host for toolkits created via modes from this mode manager (can only be called once)
SetWidgetMode()
UNREALED_API void FEditorModeTools::SetWidgetMode (UE::Widget::EWidgetMode InWidgetMode)
Changes the current widget mode.
SetWidgetModeOverride()
UNREALED_API void FEditorModeTools::SetWidgetModeOverride (UE::Widget::EWidgetMode InWidgetMode)
Allows you to temporarily override the widget mode.
Call this function again with WM_None to turn off the override.
SetWidgetScale()
UNREALED_API void FEditorModeTools::SetWidgetScale (float InScale)
Set Scale On The Widget.
ShouldDrawBrushVertices()
UNREALED_API bool FEditorModeTools::ShouldDrawBrushVertices () const
true if brush vertices should be drawn
ShouldDrawBrushWireframe()
UNREALED_API bool FEditorModeTools::ShouldDrawBrushWireframe (AActor * InActor) const
true if the passed in brush actor should be drawn in wireframe
SnapRotatorToGridOverride()
UNREALED_API bool FEditorModeTools::SnapRotatorToGridOverride (FRotator & InRotation) const
References SnapRotatorToGridOverride().
Referenced by SnapRotatorToGridOverride().
StartTracking()
UNREALED_API bool FEditorModeTools::StartTracking (FEditorViewportClient * InViewportClient, FViewport * InViewport)
Mouse tracking interface.
Passes tracking messages to all active modes
StoreSelection()
UNREALED_API void FEditorModeTools::StoreSelection (FName SelectionStoreKey, bool bClearSelection = true)
Stores the current selection under the given key, and clears the current selection state if requested.
TestAllModes()
UNREALED_API bool FEditorModeTools::TestAllModes (TFunctionRef< bool(UEdMode *)> InCalllback, bool bExpected) const protected
References TestAllModes().
Referenced by TestAllModes().
Tick()
UNREALED_API void FEditorModeTools::Tick (FEditorViewportClient * ViewportClient, float DeltaTime)
Ticks all active modes.
References DeltaTime.
UE_DEPRECATED() [1/2]
FEditorModeTools::UE_DEPRECATED (4. 26, "Individual toolkit hosts, such as the level editor, should handle determining if they show a mode toolbox for hosted toolkits.") const
Whether or not the mode toolbox (where mode details panels and some tools are) should be shown.
UE_DEPRECATED() [2/2]
FEditorModeTools::UE_DEPRECATED (5. 0, "This function is redundant, and is handled as part of a call to ActivateMode.")
UpdateInternalData()
UNREALED_API void FEditorModeTools::UpdateInternalData ()
References UpdateInternalData().
Referenced by UpdateInternalData().
UsesTransformWidget() [1/2]
UNREALED_API bool FEditorModeTools::UsesTransformWidget () const
true if any active mode uses a transform widget
UsesTransformWidget() [2/2]
UNREALED_API bool FEditorModeTools::UsesTransformWidget (UE::Widget::EWidgetMode CheckMode) const
true if any active mode uses the passed in transform widget
Field Documentation
ActiveScriptableModes
TArray< TObjectPtr<UEdMode> > FEditorModeTools::ActiveScriptableModes protected
A list of active editor modes.
Definition at line 600 of file EditorModeManager.h.
bHasOngoingTransform
bool FEditorModeTools::bHasOngoingTransform = false private
Flag to track if we started a new TRS gizmo transform.
NOTE: we have to use it for now as StartTracking / EndTracking iterates thru the modes even if the ITF context captured something. This might not be needed anymore in the future but as some routing behavior had to be kept for legacy reasons, we use that extra flag. If StartTracking / EndTracking were to be changed (which needs more testing), this could probably be removed.
Definition at line 665 of file EditorModeManager.h.
bHideViewportUI
bool FEditorModeTools::bHideViewportUI protected
if true, the viewports will hide all UI overlays
Definition at line 621 of file EditorModeManager.h.
Referenced by IsViewportUIHidden(), and SetHideViewportUI().
bIsExitingModesDuringTick
bool FEditorModeTools::bIsExitingModesDuringTick = false private
Guard to prevent modes from entering as part of their exit routine.
Definition at line 652 of file EditorModeManager.h.
bIsTracking
bool FEditorModeTools::bIsTracking private
Flag set between calls to StartTracking() and EndTracking()
Definition at line 649 of file EditorModeManager.h.
Referenced by IsTracking().
bSelectionHasSceneComponent
bool FEditorModeTools::bSelectionHasSceneComponent protected
if true the current selection has a scene component
Definition at line 624 of file EditorModeManager.h.
bShowWidget
bool FEditorModeTools::bShowWidget protected
If 1, draw the widget and let the user interact with it.
Definition at line 618 of file EditorModeManager.h.
Referenced by SetShowWidget().
CachedLocation
FVector FEditorModeTools::CachedLocation
Definition at line 431 of file EditorModeManager.h.
CoordSystem
ECoordSystem FEditorModeTools::CoordSystem private
The coordinate system the widget is operating within.
Definition at line 634 of file EditorModeManager.h.
CoordSystemChangedEvent
FCoordSystemChangedEvent FEditorModeTools::CoordSystemChangedEvent private
Multicast delegate that is broadcast when the coordinate system is changed.
Definition at line 643 of file EditorModeManager.h.
Referenced by BroadcastCoordSystemChanged(), and OnCoordSystemChanged().
CVarEnableITFCursorOverrideSupport
TAutoConsoleVariable<int32> FEditorModeTools::CVarEnableITFCursorOverrideSupport static private
Definition at line 672 of file EditorModeManager.h.
DefaultModeIDs
TArray<FEditorModeID> FEditorModeTools::DefaultModeIDs protected
List of default modes for this tool.
These must all be compatible with each other.
Definition at line 597 of file EditorModeManager.h.
Referenced by IsDefaultMode().
EditorModeIDChangedEvent
FEditorModeIDChangedEvent FEditorModeTools::EditorModeIDChangedEvent private
Multicast delegate that is broadcast when a mode is entered or exited.
Definition at line 637 of file EditorModeManager.h.
Referenced by BroadcastEditorModeIDChanged(), and OnEditorModeIDChanged().
FocusedViewportClient
FEditorViewportClient* FEditorModeTools::FocusedViewportClient = nullptr private
Definition at line 668 of file EditorModeManager.h.
GridBase
FVector FEditorModeTools::GridBase
Definition at line 434 of file EditorModeManager.h.
HoveredViewportClient
FEditorViewportClient* FEditorModeTools::HoveredViewportClient = nullptr private
Definition at line 667 of file EditorModeManager.h.
InfoString
FString FEditorModeTools::InfoString
Draws in the top level corner of all FEditorViewportClient windows (can be used to relay info to the user).
Definition at line 443 of file EditorModeManager.h.
InteractiveToolsContext
TObjectPtr<UModeManagerInteractiveToolsContext> FEditorModeTools::InteractiveToolsContext protected
Definition at line 629 of file EditorModeManager.h.
IsEditingDisallowedChangedEvent
FIsEditingDisallowedChangedEvent FEditorModeTools::IsEditingDisallowedChangedEvent private
Multicast delegate that is broadcast when a mode Editing Disallowed changed.
Definition at line 646 of file EditorModeManager.h.
Referenced by BroadcastIsEditingDisallowedChanged(), and OnIsEditingDisallowedChanged().
OverrideWidgetMode
UE::Widget::EWidgetMode FEditorModeTools::OverrideWidgetMode protected
If the widget mode is being overridden, this will be != WM_None.
Definition at line 615 of file EditorModeManager.h.
PendingDeactivateModes
TMap< FEditorModeID, TObjectPtr<UEdMode> > FEditorModeTools::PendingDeactivateModes protected
A list of previously active editor modes that we will potentially recycle.
Definition at line 609 of file EditorModeManager.h.
PivotLocation
FVector FEditorModeTools::PivotLocation
Definition at line 432 of file EditorModeManager.h.
PivotShown
bool FEditorModeTools::PivotShown
Definition at line 427 of file EditorModeManager.h.
RecycledScriptableModes
TMap< FEditorModeID, TObjectPtr<UEdMode> > FEditorModeTools::RecycledScriptableModes protected
A list of previously active editor modes that we will potentially recycle.
Definition at line 606 of file EditorModeManager.h.
SnappedActor
bool FEditorModeTools::SnappedActor
Definition at line 429 of file EditorModeManager.h.
SnappedLocation
FVector FEditorModeTools::SnappedLocation
Definition at line 433 of file EditorModeManager.h.
Snapping
bool FEditorModeTools::Snapping
Definition at line 428 of file EditorModeManager.h.
StoredSelectionSets
TMap<FName, FTypedElementSelectionSetState> FEditorModeTools::StoredSelectionSets private
Definition at line 670 of file EditorModeManager.h.
ToolkitHost
TWeakPtr<IToolkitHost> FEditorModeTools::ToolkitHost protected
The host of the toolkits created by these modes.
Definition at line 603 of file EditorModeManager.h.
TranslateRotate2DAngle
float FEditorModeTools::TranslateRotate2DAngle
The angles for the 2d translate rotate widget.
Definition at line 440 of file EditorModeManager.h.
TranslateRotateXAxisAngle
float FEditorModeTools::TranslateRotateXAxisAngle
The angle for the translate rotate widget.
Definition at line 437 of file EditorModeManager.h.
WeakGizmoContext
TWeakObjectPtr<UEditorTransformGizmoContextObject> FEditorModeTools::WeakGizmoContext mutable private
GizmoContext used to get context specific gizmo properties.
Definition at line 658 of file EditorModeManager.h.
WeakGizmoStateTarget
TWeakObjectPtr<UEditorGizmoStateTarget> FEditorModeTools::WeakGizmoStateTarget private
GizmoStateTarget used to handle a new TRS gizmo transform begin/end sequence.
Definition at line 655 of file EditorModeManager.h.
WidgetMode
UE::Widget::EWidgetMode FEditorModeTools::WidgetMode protected
The mode that the editor viewport widget is in.
Definition at line 612 of file EditorModeManager.h.
WidgetModeChangedEvent
FWidgetModeChangedEvent FEditorModeTools::WidgetModeChangedEvent private
Multicast delegate that is broadcast when a widget mode is changed.
Definition at line 640 of file EditorModeManager.h.
Referenced by BroadcastWidgetModeChanged(), and OnWidgetModeChanged().
WidgetScale
float FEditorModeTools::WidgetScale protected
Scale Factor for Widget.
Definition at line 627 of file EditorModeManager.h.
The documentation for this class was generated from the following file:
EditorModeManager.h