Unreal Engine 5.6 C++ API: FMeshBatchDynamicPrimitiveData Struct Reference
FMeshBatchDynamicPrimitiveData Struct Reference
Dynamic primitive/instance data for a mesh batch element.
#include "MeshBatch.h"
Public Member Functions
FORCEINLINE void EnableInstanceDynamicData (bool bEnable)
FORCEINLINE void EnableInstanceLocalBounds (bool bEnable)
FORCEINLINE void EnableInstanceSkinningData (bool bEnable)
FORCEINLINE uint32 GetPayloadFloat4Stride () const
Computes the full float4 stride of the instance's payload data.
FORCEINLINE void SetNumInstanceCustomDataFloats (uint32 NumFloats)
FORCEINLINE void SetPayloadDataFlags (uint16 Flags, bool bValue)
FORCEINLINE void Validate (uint32 NumInstances) const
Data Fields
FGPUSceneWriteDelegateRef DataWriterGPU
EGPUSceneGPUWritePass DataWriterGPUPass = EGPUSceneGPUWritePass::None
TConstArrayView< float > InstanceCustomData
TConstArrayView< FInstanceDynamicData > InstanceDynamicData
TConstArrayView< FRenderBounds > InstanceLocalBounds
TConstArrayView< FInstanceSceneData > InstanceSceneData
uint32 NumInstanceCustomDataFloats = 0
uint16 PayloadDataFlags = 0
Detailed Description
Dynamic primitive/instance data for a mesh batch element.
NOTES:
When applied to a FMeshBatchElement, data provided to the TConstArrayView members are expected to live until the end of the frame on the render thread
If DataWriterGPU is bound and the TConstArrayView members are left empty, the delegate is expected to write any missing data, as it will not be uploaded
Definition at line 123 of file MeshBatch.h.
Member Function Documentation
EnableInstanceDynamicData()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::EnableInstanceDynamicData (bool bEnable) inline
Definition at line 146 of file MeshBatch.h.
References FORCEINLINE, and SetPayloadDataFlags().
EnableInstanceLocalBounds()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::EnableInstanceLocalBounds (bool bEnable) inline
Definition at line 148 of file MeshBatch.h.
References FORCEINLINE, and SetPayloadDataFlags().
EnableInstanceSkinningData()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::EnableInstanceSkinningData (bool bEnable) inline
Definition at line 147 of file MeshBatch.h.
References FORCEINLINE, and SetPayloadDataFlags().
GetPayloadFloat4Stride()
FORCEINLINE uint32 FMeshBatchDynamicPrimitiveData::GetPayloadFloat4Stride () const inline
Computes the full float4 stride of the instance's payload data.
NOTE: Needs to align with GetInstancePayloadDataOffsets in SceneData.ush
Definition at line 159 of file MeshBatch.h.
References AreCompressedTransformsSupported(), FMath::DivideAndRoundUp(), FORCEINLINE, NumInstanceCustomDataFloats, and PayloadDataFlags.
SetNumInstanceCustomDataFloats()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::SetNumInstanceCustomDataFloats (uint32 NumFloats) inline
Definition at line 149 of file MeshBatch.h.
References FORCEINLINE, NumInstanceCustomDataFloats, and SetPayloadDataFlags().
SetPayloadDataFlags()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::SetPayloadDataFlags (uint16 Flags, bool bValue) inline
Definition at line 134 of file MeshBatch.h.
References Flags, FORCEINLINE, and PayloadDataFlags.
Referenced by EnableInstanceDynamicData(), EnableInstanceLocalBounds(), EnableInstanceSkinningData(), and SetNumInstanceCustomDataFloats().
Validate()
FORCEINLINE void FMeshBatchDynamicPrimitiveData::Validate (uint32 NumInstances) const inline
Definition at line 202 of file MeshBatch.h.
References checkf, DataWriterGPU, FORCEINLINE, InstanceCustomData, InstanceDynamicData, InstanceSceneData, NumInstanceCustomDataFloats, PayloadDataFlags, and TEXT.
Field Documentation
DataWriterGPU
FGPUSceneWriteDelegateRef FMeshBatchDynamicPrimitiveData::DataWriterGPU
Definition at line 129 of file MeshBatch.h.
Referenced by Validate().
DataWriterGPUPass
EGPUSceneGPUWritePass FMeshBatchDynamicPrimitiveData::DataWriterGPUPass = EGPUSceneGPUWritePass::None
Definition at line 130 of file MeshBatch.h.
InstanceCustomData
TConstArrayView<float> FMeshBatchDynamicPrimitiveData::InstanceCustomData
Definition at line 128 of file MeshBatch.h.
Referenced by Validate().
InstanceDynamicData
TConstArrayView<FInstanceDynamicData> FMeshBatchDynamicPrimitiveData::InstanceDynamicData
Definition at line 126 of file MeshBatch.h.
Referenced by Validate().
InstanceLocalBounds
TConstArrayView<FRenderBounds> FMeshBatchDynamicPrimitiveData::InstanceLocalBounds
Definition at line 127 of file MeshBatch.h.
InstanceSceneData
TConstArrayView<FInstanceSceneData> FMeshBatchDynamicPrimitiveData::InstanceSceneData
Definition at line 125 of file MeshBatch.h.
Referenced by Validate().
NumInstanceCustomDataFloats
uint32 FMeshBatchDynamicPrimitiveData::NumInstanceCustomDataFloats = 0
Definition at line 132 of file MeshBatch.h.
Referenced by GetPayloadFloat4Stride(), SetNumInstanceCustomDataFloats(), and Validate().
PayloadDataFlags
uint16 FMeshBatchDynamicPrimitiveData::PayloadDataFlags = 0
Definition at line 131 of file MeshBatch.h.
Referenced by GetPayloadFloat4Stride(), SetPayloadDataFlags(), and Validate().
The documentation for this struct was generated from the following file:
MeshBatch.h