Unreal Engine 5.6 C++ API: FRigVMTemplate Struct Reference
FRigVMTemplate Struct Reference
The template is used to group multiple rigvm functions that share the same notation.
#include "RigVMTemplate.h"
Public Types
typedef FRigVMTemplateTypeMap FTypeMap
typedef TPair< FName, TRigVMTypeIndex > FTypePair
Public Member Functions
RIGVM_API FRigVMTemplate ()
RIGVM_API bool ArgumentSupportsTypeIndex (const FName &InArgumentName, TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex *OutTypeIndex=nullptr) const
RIGVM_API void ComputeNotationFromArguments (const FString &InTemplateName)
RIGVM_API bool ContainsPermutation (const FRigVMFunction *InPermutation, bool bLockRegistry=true) const
RIGVM_API bool ContainsPermutation (const FTypeMap &InTypes, bool bLockRegistry=true) const
RIGVM_API bool ContainsPermutation_NoLock (const FRigVMFunction *InPermutation) const
RIGVM_API bool ContainsPermutation_NoLock (const FTypeMap &InTypes) const
RIGVM_API const FRigVMTemplateArgument * FindArgument (const FName &InArgumentName) const
RIGVM_API const FRigVMExecuteArgument * FindExecuteArgument (const FName &InArgumentName, const FRigVMDispatchContext &InContext) const
RIGVM_API int32 FindPermutation (const FRigVMFunction *InPermutation) const
RIGVM_API int32 FindPermutation (const FTypeMap &InTypes, bool bLockRegistry=true) const
RIGVM_API bool FullyResolve (FTypeMap &InOutTypes, int32 &OutPermutationIndex, bool bLockRegistry=true) const
const FRigVMTemplateArgument * GetArgument (int32 InIndex) const
RIGVM_API FString GetArgumentMetaData (const FName &InArgumentName, const FName &InMetaDataKey, const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API FTypeMap GetArgumentTypesFromString (const FString &InTypeString, const FRigVMUserDefinedTypeResolver *InTypeResolver=nullptr) const
RIGVM_API FString GetCategory () const
RIGVM_API FLinearColor GetColor (const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API const FRigVMDispatchFactory * GetDispatchFactory (const bool bLockRegistry=true) const
const FRigVMDispatchFactory * GetDispatchFactory_NoLock () const
RIGVM_API FText GetDisplayNameForArgument (const FName &InArgumentName, const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API const FRigVMExecuteArgument * GetExecuteArgument (int32 InIndex, const FRigVMDispatchContext &InContext) const
RIGVM_API const UScriptStruct * GetExecuteContextStruct (bool bLockRegistry=true) const
RIGVM_API FString GetKeywords () const
RIGVM_API FName GetName () const
RIGVM_API FName GetNodeName () const
RIGVM_API const FName & GetNotation () const
RIGVM_API const FRigVMFunction * GetOrCreatePermutation (int32 InIndex, bool bLockRegistry=true)
RIGVM_API const FRigVMFunction * GetPermutation (int32 InIndex, bool bLockRegistry=true) const
RIGVM_API const FRigVMFunction * GetPrimaryPermutation (bool bLockRegistry=true) const
RIGVM_API FText GetTooltipText (const TArray< int32 > &InPermutationIndices=TArray< int32 >()) const
RIGVM_API FRigVMTemplateTypeMap GetTypesForPermutation (const int32 InPermutationIndex, const bool bLockRegistry=true) const
RIGVM_API FRigVMTemplateTypeMap GetTypesForPermutation_NoLock (const int32 InPermutationIndex) const
RIGVM_API uint32 GetTypesHashFromTypes (const FTypeMap &InTypes) const
RIGVM_API bool HandlePropagatedArgumentType (const TRigVMTypeIndex InTypeIndex)
RIGVM_API void HandleTypeRemoval (TRigVMTypeIndex InTypeIndex)
RIGVM_API bool IsValid () const
RIGVM_API bool Merge (const FRigVMTemplate &InOther)
int32 NumArguments () const
RIGVM_API int32 NumExecuteArguments (const FRigVMDispatchContext &InContext) const
int32 NumPermutations () const
FRigVMTemplate_NewArgumentTypeDelegate & OnNewArgumentType ()
RIGVM_API void RecomputeTypesHashToPermutations ()
RIGVM_API void RecomputeTypesHashToPermutations (const TArray< FRigVMTypeCacheScope_NoLock > &InTypeCaches)
RIGVM_API bool Resolve (FTypeMap &InOutTypes, TArray< int32 > &OutPermutationIndices, bool bAllowFloatingPointCasts, bool bLockRegistry=true) const
RIGVM_API bool ResolveArgument (const FName &InArgumentName, const TRigVMTypeIndex InTypeIndex, FTypeMap &InOutTypes, bool bLockRegistry=true) const
RIGVM_API bool SupportsExecuteContextStruct (const UScriptStruct *InExecuteContextStruct) const
RIGVM_API bool UpdateAllArgumentTypesSlow ()
RIGVM_API void UpdateTypesHashToPermutation (const int32 InPermutation)
bool UsesDispatch () const
Static Public Member Functions
static RIGVM_API FString GetArgumentNotation (const FName InName, const ERigVMPinDirection InDirection)
static RIGVM_API const FString & GetDirectionPrefix (const ERigVMPinDirection InDirection)
static RIGVM_API FString GetStringFromArgumentTypes (const FTypeMap &InTypes, bool bLockRegistry=true)
static RIGVM_API TArray< UStruct * > GetSuperStructs (UStruct *InStruct, bool bIncludeLeaf=true)
static RIGVM_API bool IsValidArgumentForTemplate (const ERigVMPinDirection InDirection)
Private Member Functions
FRigVMTemplate (const FName &InTemplateName, const TArray< FRigVMTemplateArgumentInfo > &InInfos)
FRigVMTemplate (UScriptStruct *InStruct, const FString &InTemplateName, int32 InFunctionIndex=INDEX_NONE)
uint32 ComputeTypeHash () const
FTypeMap GetArgumentTypesFromString_Impl (const FString &InTypeString, const FRigVMUserDefinedTypeResolver *InTypeResolver, bool bLockRegistry) const
RIGVM_API const TArray< FRigVMExecuteArgument > & GetExecuteArguments (const FRigVMDispatchContext &InContext) const
const FRigVMFunction * GetOrCreatePermutation_NoLock (int32 InIndex)
const FRigVMFunction * GetPermutation_NoLock (int32 InIndex) const
void InvalidateHash ()
bool UpdateArgumentTypes_Impl (const FRigVMTemplateArgument &InPrimaryArgument, const TRigVMTypeIndex InPrimaryTypeIndex, const FRigVMRegistry_NoLock &InRegistry, const FRigVMDispatchFactory *InFactory, TArray< FRigVMTemplateTypeMap, TInlineAllocator< 1 > > &InOutTypesArray)
Static Private Member Functions
static FLinearColor GetColorFromMetadata (FString InMetadata)
Private Attributes
TArray< FRigVMTemplateArgument > Arguments
FRigVMTemplateDelegates Delegates
TArray< FRigVMExecuteArgument > ExecuteArguments
uint32 Hash
int32 Index
FName Notation
TArray< int32 > Permutations
TMap< uint32, int32 > TypesHashToPermutation
Friends
struct FRigVMDispatchFactory
struct FRigVMRegistry_NoLock
RIGVM_API friend uint32 GetTypeHash (const FRigVMTemplate &InTemplate)
RIGVM_API friend uint32 GetTypeHash_NoLock (const FRigVMTemplate &InTemplate)
class URigVMController
class URigVMLibraryNode
Detailed Description
The template is used to group multiple rigvm functions that share the same notation.
Templates can then be used to build polymorphic nodes (RigVMTemplateNode) that can take on any of the permutations supported by the template.
Definition at line 398 of file RigVMTemplate.h.
Member Typedef Documentation
FTypeMap
typedef FRigVMTemplateTypeMap FRigVMTemplate::FTypeMap
Definition at line 402 of file RigVMTemplate.h.
FTypePair
typedef TPair<FName, TRigVMTypeIndex> FRigVMTemplate::FTypePair
Definition at line 403 of file RigVMTemplate.h.
Constructor & Destructor Documentation
FRigVMTemplate() [1/3]
RIGVM_API FRigVMTemplate::FRigVMTemplate ()
Referenced by GetTypeHash, GetTypeHash_NoLock, and Merge().
FRigVMTemplate() [2/3]
FRigVMTemplate::FRigVMTemplate (UScriptStruct * InStruct, const FString & InTemplateName, int32 InFunctionIndex = INDEX_NONE) private
References INDEX_NONE.
FRigVMTemplate() [3/3]
FRigVMTemplate::FRigVMTemplate (const FName & InTemplateName, const TArray< FRigVMTemplateArgumentInfo > & InInfos) private
Member Function Documentation
ArgumentSupportsTypeIndex()
RIGVM_API bool FRigVMTemplate::ArgumentSupportsTypeIndex (const FName & InArgumentName, TRigVMTypeIndex InTypeIndex, TRigVMTypeIndex * OutTypeIndex = nullptr) const
ComputeNotationFromArguments()
RIGVM_API void FRigVMTemplate::ComputeNotationFromArguments (const FString & InTemplateName)
ComputeTypeHash()
uint32 FRigVMTemplate::ComputeTypeHash () const private
ContainsPermutation() [1/2]
RIGVM_API bool FRigVMTemplate::ContainsPermutation (const FRigVMFunction * InPermutation, bool bLockRegistry = true) const
ContainsPermutation() [2/2]
RIGVM_API bool FRigVMTemplate::ContainsPermutation (const FTypeMap & InTypes, bool bLockRegistry = true) const
ContainsPermutation_NoLock() [1/2]
RIGVM_API bool FRigVMTemplate::ContainsPermutation_NoLock (const FRigVMFunction * InPermutation) const
ContainsPermutation_NoLock() [2/2]
RIGVM_API bool FRigVMTemplate::ContainsPermutation_NoLock (const FTypeMap & InTypes) const
FindArgument()
RIGVM_API const FRigVMTemplateArgument * FRigVMTemplate::FindArgument (const FName & InArgumentName) const
FindExecuteArgument()
RIGVM_API const FRigVMExecuteArgument * FRigVMTemplate::FindExecuteArgument (const FName & InArgumentName, const FRigVMDispatchContext & InContext) const
FindPermutation() [1/2]
RIGVM_API int32 FRigVMTemplate::FindPermutation (const FRigVMFunction * InPermutation) const
FindPermutation() [2/2]
RIGVM_API int32 FRigVMTemplate::FindPermutation (const FTypeMap & InTypes, bool bLockRegistry = true) const
FullyResolve()
RIGVM_API bool FRigVMTemplate::FullyResolve (FTypeMap & InOutTypes, int32 & OutPermutationIndex, bool bLockRegistry = true) const
GetArgument()
const FRigVMTemplateArgument * FRigVMTemplate::GetArgument (int32 InIndex) const inline
Definition at line 427 of file RigVMTemplate.h.
References Arguments.
GetArgumentMetaData()
RIGVM_API FString FRigVMTemplate::GetArgumentMetaData (const FName & InArgumentName, const FName & InMetaDataKey, const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetArgumentNotation()
RIGVM_API FString FRigVMTemplate::GetArgumentNotation (const FName InName, const ERigVMPinDirection InDirection) static
References InName.
GetArgumentTypesFromString()
RIGVM_API FTypeMap FRigVMTemplate::GetArgumentTypesFromString (const FString & InTypeString, const FRigVMUserDefinedTypeResolver * InTypeResolver = nullptr) const
GetArgumentTypesFromString_Impl()
FTypeMap FRigVMTemplate::GetArgumentTypesFromString_Impl (const FString & InTypeString, const FRigVMUserDefinedTypeResolver * InTypeResolver, bool bLockRegistry) const private
GetCategory()
RIGVM_API FString FRigVMTemplate::GetCategory () const
GetColor()
RIGVM_API FLinearColor FRigVMTemplate::GetColor (const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetColorFromMetadata()
FLinearColor FRigVMTemplate::GetColorFromMetadata (FString InMetadata) static private
GetDirectionPrefix()
RIGVM_API const FString & FRigVMTemplate::GetDirectionPrefix (const ERigVMPinDirection InDirection) static
GetDispatchFactory()
RIGVM_API const FRigVMDispatchFactory * FRigVMTemplate::GetDispatchFactory (const bool bLockRegistry = true) const
References FRigVMDispatchFactory.
GetDispatchFactory_NoLock()
const FRigVMDispatchFactory * FRigVMTemplate::GetDispatchFactory_NoLock () const inline
Definition at line 553 of file RigVMTemplate.h.
References Delegates, FRigVMDispatchFactory, and UsesDispatch().
GetDisplayNameForArgument()
RIGVM_API FText FRigVMTemplate::GetDisplayNameForArgument (const FName & InArgumentName, const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetExecuteArgument()
RIGVM_API const FRigVMExecuteArgument * FRigVMTemplate::GetExecuteArgument (int32 InIndex, const FRigVMDispatchContext & InContext) const
GetExecuteArguments()
RIGVM_API const TArray< FRigVMExecuteArgument > & FRigVMTemplate::GetExecuteArguments (const FRigVMDispatchContext & InContext) const private
GetExecuteContextStruct()
RIGVM_API const UScriptStruct * FRigVMTemplate::GetExecuteContextStruct (bool bLockRegistry = true) const
GetKeywords()
RIGVM_API FString FRigVMTemplate::GetKeywords () const
GetName()
RIGVM_API FName FRigVMTemplate::GetName () const
GetNodeName()
RIGVM_API FName FRigVMTemplate::GetNodeName () const
GetNotation()
RIGVM_API const FName & FRigVMTemplate::GetNotation () const
GetOrCreatePermutation()
RIGVM_API const FRigVMFunction * FRigVMTemplate::GetOrCreatePermutation (int32 InIndex, bool bLockRegistry = true)
GetOrCreatePermutation_NoLock()
const FRigVMFunction * FRigVMTemplate::GetOrCreatePermutation_NoLock (int32 InIndex) private
GetPermutation()
RIGVM_API const FRigVMFunction * FRigVMTemplate::GetPermutation (int32 InIndex, bool bLockRegistry = true) const
GetPermutation_NoLock()
const FRigVMFunction * FRigVMTemplate::GetPermutation_NoLock (int32 InIndex) const private
GetPrimaryPermutation()
RIGVM_API const FRigVMFunction * FRigVMTemplate::GetPrimaryPermutation (bool bLockRegistry = true) const
GetStringFromArgumentTypes()
RIGVM_API FString FRigVMTemplate::GetStringFromArgumentTypes (const FTypeMap & InTypes, bool bLockRegistry = true) static
GetSuperStructs()
RIGVM_API TArray< UStruct * > FRigVMTemplate::GetSuperStructs (UStruct * InStruct, bool bIncludeLeaf = true) static
GetTooltipText()
RIGVM_API FText FRigVMTemplate::GetTooltipText (const TArray< int32 > & InPermutationIndices = TArray< int32 >()) const
GetTypesForPermutation()
RIGVM_API FRigVMTemplateTypeMap FRigVMTemplate::GetTypesForPermutation (const int32 InPermutationIndex, const bool bLockRegistry = true) const
GetTypesForPermutation_NoLock()
RIGVM_API FRigVMTemplateTypeMap FRigVMTemplate::GetTypesForPermutation_NoLock (const int32 InPermutationIndex) const
GetTypesHashFromTypes()
RIGVM_API uint32 FRigVMTemplate::GetTypesHashFromTypes (const FTypeMap & InTypes) const
HandlePropagatedArgumentType()
RIGVM_API bool FRigVMTemplate::HandlePropagatedArgumentType (const TRigVMTypeIndex InTypeIndex)
HandleTypeRemoval()
RIGVM_API void FRigVMTemplate::HandleTypeRemoval (TRigVMTypeIndex InTypeIndex)
InvalidateHash()
void FRigVMTemplate::InvalidateHash () inline private
Definition at line 582 of file RigVMTemplate.h.
References Hash.
IsValid()
RIGVM_API bool FRigVMTemplate::IsValid () const
IsValidArgumentForTemplate()
RIGVM_API bool FRigVMTemplate::IsValidArgumentForTemplate (const ERigVMPinDirection InDirection) static
Merge()
RIGVM_API bool FRigVMTemplate::Merge (const FRigVMTemplate & InOther)
References FRigVMTemplate().
NumArguments()
int32 FRigVMTemplate::NumArguments () const inline
Definition at line 424 of file RigVMTemplate.h.
References Arguments.
NumExecuteArguments()
RIGVM_API int32 FRigVMTemplate::NumExecuteArguments (const FRigVMDispatchContext & InContext) const
NumPermutations()
int32 FRigVMTemplate::NumPermutations () const inline
Definition at line 453 of file RigVMTemplate.h.
References Permutations.
OnNewArgumentType()
FRigVMTemplate_NewArgumentTypeDelegate & FRigVMTemplate::OnNewArgumentType () inline
Definition at line 547 of file RigVMTemplate.h.
References Delegates.
RecomputeTypesHashToPermutations() [1/2]
RIGVM_API void FRigVMTemplate::RecomputeTypesHashToPermutations ()
RecomputeTypesHashToPermutations() [2/2]
RIGVM_API void FRigVMTemplate::RecomputeTypesHashToPermutations (const TArray< FRigVMTypeCacheScope_NoLock > & InTypeCaches)
Resolve()
RIGVM_API bool FRigVMTemplate::Resolve (FTypeMap & InOutTypes, TArray< int32 > & OutPermutationIndices, bool bAllowFloatingPointCasts, bool bLockRegistry = true) const
ResolveArgument()
RIGVM_API bool FRigVMTemplate::ResolveArgument (const FName & InArgumentName, const TRigVMTypeIndex InTypeIndex, FTypeMap & InOutTypes, bool bLockRegistry = true) const
SupportsExecuteContextStruct()
RIGVM_API bool FRigVMTemplate::SupportsExecuteContextStruct (const UScriptStruct * InExecuteContextStruct) const
UpdateAllArgumentTypesSlow()
RIGVM_API bool FRigVMTemplate::UpdateAllArgumentTypesSlow ()
UpdateArgumentTypes_Impl()
bool FRigVMTemplate::UpdateArgumentTypes_Impl (const FRigVMTemplateArgument & InPrimaryArgument, const TRigVMTypeIndex InPrimaryTypeIndex, const FRigVMRegistry_NoLock & InRegistry, const FRigVMDispatchFactory * InFactory, TArray< FRigVMTemplateTypeMap, TInlineAllocator< 1 > > & InOutTypesArray) private
References FRigVMDispatchFactory, and FRigVMRegistry_NoLock.
UpdateTypesHashToPermutation()
RIGVM_API void FRigVMTemplate::UpdateTypesHashToPermutation (const int32 InPermutation)
UsesDispatch()
bool FRigVMTemplate::UsesDispatch () const inline
Definition at line 559 of file RigVMTemplate.h.
References Delegates.
Referenced by GetDispatchFactory_NoLock().
Friends And Related Symbol Documentation
FRigVMDispatchFactory
friend struct FRigVMDispatchFactory friend
Definition at line 612 of file RigVMTemplate.h.
References FRigVMDispatchFactory.
Referenced by FRigVMDispatchFactory, GetDispatchFactory(), GetDispatchFactory_NoLock(), and UpdateArgumentTypes_Impl().
FRigVMRegistry_NoLock
friend struct FRigVMRegistry_NoLock friend
Definition at line 609 of file RigVMTemplate.h.
References FRigVMRegistry_NoLock.
Referenced by FRigVMRegistry_NoLock, and UpdateArgumentTypes_Impl().
GetTypeHash
RIGVM_API friend uint32 GetTypeHash (const FRigVMTemplate & InTemplate) friend
References FRigVMTemplate().
GetTypeHash_NoLock
RIGVM_API friend uint32 GetTypeHash_NoLock (const FRigVMTemplate & InTemplate) friend
References FRigVMTemplate().
URigVMController
friend class URigVMController friend
Definition at line 610 of file RigVMTemplate.h.
References URigVMController.
Referenced by URigVMController.
URigVMLibraryNode
friend class URigVMLibraryNode friend
Definition at line 611 of file RigVMTemplate.h.
References URigVMLibraryNode.
Referenced by URigVMLibraryNode.
Field Documentation
Arguments
TArray<FRigVMTemplateArgument> FRigVMTemplate::Arguments private
Definition at line 601 of file RigVMTemplate.h.
Referenced by GetArgument(), and NumArguments().
Delegates
FRigVMTemplateDelegates FRigVMTemplate::Delegates private
Definition at line 607 of file RigVMTemplate.h.
Referenced by GetDispatchFactory_NoLock(), OnNewArgumentType(), and UsesDispatch().
ExecuteArguments
TArray<FRigVMExecuteArgument> FRigVMTemplate::ExecuteArguments mutable private
Definition at line 602 of file RigVMTemplate.h.
Hash
uint32 FRigVMTemplate::Hash mutable private
Definition at line 605 of file RigVMTemplate.h.
Referenced by InvalidateHash().
Index
int32 FRigVMTemplate::Index private
Definition at line 599 of file RigVMTemplate.h.
Notation
FName FRigVMTemplate::Notation private
Definition at line 600 of file RigVMTemplate.h.
Permutations
TArray<int32> FRigVMTemplate::Permutations private
Definition at line 603 of file RigVMTemplate.h.
Referenced by NumPermutations().
TypesHashToPermutation
TMap<uint32, int32> FRigVMTemplate::TypesHashToPermutation private
Definition at line 604 of file RigVMTemplate.h.
The documentation for this struct was generated from the following file:
RigVMTemplate.h