Unreal Engine 5.6 C++ API: FSharedPersistentDataKey Struct Reference
FSharedPersistentDataKey Struct Reference
A key to a piece of data that is potentially shared between multiple tracks.
#include "PersistentEvaluationData.h"
Public Member Functions
FSharedPersistentDataKey (FMovieSceneSharedDataId InUniqueId, const FMovieSceneEvaluationOperand &InOperand)
Construction from a shared data ID, and an operand.
Data Fields
FMovieSceneEvaluationOperand Operand
The operand that this key relates to (may be invalid where the data pertains to root tracks)
FMovieSceneSharedDataId UniqueId
The actual shared ID.
Friends
uint32 GetTypeHash (const FSharedPersistentDataKey &In)
bool operator== (const FSharedPersistentDataKey &A, const FSharedPersistentDataKey &B)
Detailed Description
A key to a piece of data that is potentially shared between multiple tracks.
Definition at line 44 of file PersistentEvaluationData.h.
Constructor & Destructor Documentation
FSharedPersistentDataKey()
FSharedPersistentDataKey::FSharedPersistentDataKey (FMovieSceneSharedDataId InUniqueId, const FMovieSceneEvaluationOperand & InOperand) inline
Construction from a shared data ID, and an operand.
Definition at line 49 of file PersistentEvaluationData.h.
References Operand, and UniqueId.
Referenced by GetTypeHash, and operator==.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSharedPersistentDataKey & In) friend
Definition at line 59 of file PersistentEvaluationData.h.
References FSharedPersistentDataKey(), GetTypeHash, HashCombine(), Operand, and UniqueId.
Referenced by GetTypeHash.
operator==
bool operator== (const FSharedPersistentDataKey & A, const FSharedPersistentDataKey & B) friend
Definition at line 54 of file PersistentEvaluationData.h.
References FSharedPersistentDataKey(), A, and B.
Field Documentation
Operand
FMovieSceneEvaluationOperand FSharedPersistentDataKey::Operand
The operand that this key relates to (may be invalid where the data pertains to root tracks)
Definition at line 68 of file PersistentEvaluationData.h.
Referenced by FSharedPersistentDataKey(), and GetTypeHash.
UniqueId
FMovieSceneSharedDataId FSharedPersistentDataKey::UniqueId
The actual shared ID.
Definition at line 65 of file PersistentEvaluationData.h.
Referenced by FSharedPersistentDataKey(), and GetTypeHash.
The documentation for this struct was generated from the following file:
PersistentEvaluationData.h