Unreal Engine 5.6 C++ API: UEnvQueryGenerator_ActorsOfClass Class Reference
UEnvQueryGenerator_ActorsOfClass Class Reference
#include "EnvQueryGenerator_ActorsOfClass.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) TSubclassOf< AActor > SearchedActorClass
virtual AIMODULE_API void GenerateItems (FEnvQueryInstance &QueryInstance) const override
if set, tests will be automatically sorted for best performance before running query
virtual AIMODULE_API FText GetDescriptionDetails () const override
virtual AIMODULE_API FText GetDescriptionTitle () const override
virtual void ProcessItems (FEnvQueryInstance &QueryInstance, TArray< AActor * > &MatchingActors) const
UPROPERTY () FAIDataProviderBoolValue GenerateOnlyActorsInRadius
If true, this will only returns actors of the specified class within the SearchRadius of the SearchCenter context.
UPROPERTY () FAIDataProviderFloatValue SearchRadius
Max distance of path between point and context.
UPROPERTY () TSubclassOf< UEnvQueryContext > SearchCenter
context
Detailed Description
Definition at line 15 of file EnvQueryGenerator_ActorsOfClass.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_ActorsOfClass::GENERATED_UCLASS_BODY () private
References Category, meta, and UPROPERTY().
GenerateItems()
virtual AIMODULE_API void UEnvQueryGenerator_ActorsOfClass::GenerateItems (FEnvQueryInstance & QueryInstance) const override private virtual
if set, tests will be automatically sorted for best performance before running query
Reimplemented from UEnvQueryGenerator.
References GenerateItems().
Referenced by GenerateItems().
GetDescriptionDetails()
virtual AIMODULE_API FText UEnvQueryGenerator_ActorsOfClass::GetDescriptionDetails () const override private virtual
GetDescriptionTitle()
virtual AIMODULE_API FText UEnvQueryGenerator_ActorsOfClass::GetDescriptionTitle () const override private virtual
ProcessItems()
virtual void UEnvQueryGenerator_ActorsOfClass::ProcessItems (FEnvQueryInstance & QueryInstance, TArray< AActor * > & MatchingActors) const inline private virtual
Definition at line 37 of file EnvQueryGenerator_ActorsOfClass.h.
References ProcessItems().
Referenced by ProcessItems().
UPROPERTY() [1/3]
UEnvQueryGenerator_ActorsOfClass::UPROPERTY () private
If true, this will only returns actors of the specified class within the SearchRadius of the SearchCenter context.
If false, it will return ALL actors of the specified class in the world.
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/3]
UEnvQueryGenerator_ActorsOfClass::UPROPERTY () private
Max distance of path between point and context.
NOTE: Zero and negative values will never return any results if UseRadius is true. "Within" requires Distance < Radius. Actors ON the circle (Distance == Radius) are excluded.
References Category, and UPROPERTY().
UPROPERTY() [3/3]
UEnvQueryGenerator_ActorsOfClass::UPROPERTY () private
context
References Category, and UPROPERTY().
The documentation for this class was generated from the following file:
EnvQueryGenerator_ActorsOfClass.h