Unreal Engine 5.6 C++ API: SGraphActionMenu Class Reference
SGraphActionMenu Class Reference
Class that displays a list of graph actions and them to be searched and selected.
#include "SGraphActionMenu.h"
Public Member Functions
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
bool CanRequestRenameOnActionNode () const
Queries if a rename on the selected action node is possible.
DECLARE_DELEGATE_OneParam (FOnActionDoubleClicked, const TArray< TSharedPtr< FEdGraphSchemaAction > > &)
Delegate executed when an action is double clicked.
DECLARE_DELEGATE_OneParam (FOnCollectAllActions, FGraphActionListBuilderBase &)
Delegate executed when the list of all actions needs to be refreshed.
DECLARE_DELEGATE_OneParam (FOnCollectStaticSections, TArray< int32 > &) DECLARE_DELEGATE_ThreeParams(FOnCategoryTextCommitted
Delegate executed when the list of all actions needs to be refreshed, should return any sections that should always be visible, even if they don't have children.
DECLARE_DELEGATE_RetVal (FText, FGetFilterText)
Delegate to get the filter text.
DECLARE_DELEGATE_RetVal (TSharedRef< FGraphActionListBuilderBase >, FOnGetActionList)
Delegate that can be used to create and/or get a custom action list.
DECLARE_DELEGATE_RetVal_OneParam (bool, FCanRenameSelectedAction, TWeakPtr< FGraphActionNode >)
Delegate executed to check if the selected action is valid for renaming.
DECLARE_DELEGATE_RetVal_OneParam (FText, FGetSectionTitle, int32)
Delegate to get the name of a section if the widget is a section separator.
DECLARE_DELEGATE_RetVal_OneParam (TSharedPtr< IToolTip >, FGetSectionToolTip, int32)
Delegate to get the tooltip of a section if the widget is a section separator.
DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< SExpanderArrow >, FOnCreateCustomRowExpander, FCustomExpanderData const &)
Delegate that can be used to create a custom "expander" widget for a particular row.
DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< SWidget >, FOnCreateWidgetForAction, FCreateWidgetForActionData *const)
Delegate that can be used to create a widget for a particular action.
DECLARE_DELEGATE_RetVal_TwoParams (bool, FOnActionMatchesName, FEdGraphSchemaAction *, const FName &)
Delegate to check if an action matches a specified name (used for renaming items etc.)
DECLARE_DELEGATE_RetVal_TwoParams (FReply, FOnActionDragged, const TArray< TSharedPtr< FEdGraphSchemaAction > > &, const FPointerEvent &)
Delegate executed when an action is dragged.
DECLARE_DELEGATE_RetVal_TwoParams (FReply, FOnCategoryDragged, const FText &, const FPointerEvent &)
Delegate executed when a category is dragged.
DECLARE_DELEGATE_RetVal_TwoParams (TSharedRef< SWidget >, FGetSectionWidget, TSharedRef< SWidget >, int32)
Delegate to get the widget that appears on the section bar in the section separator.
DECLARE_DELEGATE_TwoParams (FOnActionSelected, const TArray< TSharedPtr< FEdGraphSchemaAction > > &, ESelectInfo::Type)
Delegate executed when an action is selected.
void ExpandCategory (const FText &CategoryName)
Expands any category with the associated name.
void GenerateFilteredItems (bool bPreserveExpansion)
Regenerated filtered results (FilteredRootAction) based on filter text.
void GetCategorySubActions (TWeakPtr< FGraphActionNode > InAction, TArray< TSharedPtr< FEdGraphSchemaAction > > &OutActions) const
Get category child actions for the passed in action.
TSharedRef< SEditableTextBox > GetFilterTextBox ()
Get filter text box widget.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
void GetSectionExpansion (TMap< int32, bool > &SectionExpansion) const
Returns a map of all top level sections and their current expansion state.
void GetSelectedActions (TArray< TSharedPtr< FEdGraphSchemaAction > > &OutSelectedActions) const
Get action that is currently selected.
FString GetSelectedCategoryName () const
Get category that is currently selected.
void GetSelectedCategorySubActions (TArray< TSharedPtr< FEdGraphSchemaAction > > &OutActions) const
Get category child actions that is currently selected.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &KeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
bool OnMouseButtonDownEvent (TWeakPtr< FEdGraphSchemaAction > InAction)
void OnRequestRenameOnActionNode ()
Initiates a rename on the selected action node, if possible.
void RefreshAllActions (bool bPreserveExpansion, bool bHandleOnSelectionEvent=true)
Refreshes the actions that this widget should display.
bool SelectItemByName (const FName &ItemName, ESelectInfo::Type SelectInfo=ESelectInfo::Direct, int32 SectionId=INDEX_NONE, bool bIsCategory=false)
Selects an non-creation item in the list, searching by FName, deselects if name is none.
void SetSectionExpansion (const TMap< int32, bool > &SectionExpansion)
Sets the sections to be expanded of all top level sections.
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SLATE_ARGUMENT (bool, AlphaSortItems) SLATE_ARGUMENT(bool
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling SLATE_ARGUMENT (bool, bAllowPreselectedItemActivation) SLATE_ARGUMENT(int32
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel GraphObj SLATE_ARGUMENT (bool, bAutomaticallySelectSingleAction) SLATE_END_ARGS() void Construct(const FArguments &InArgs
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively SLATE_ARGUMENT (bool, ShowFilterTextBox) SLATE_ARGUMENT(bool
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel SLATE_ARGUMENT (TArray< UEdGraphPin * >, DraggedFromPins) SLATE_ARGUMENT(UEdGraph *
SLATE_BEGIN_ARGS (SGraphActionMenu)
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction SLATE_EVENT (FGetSectionTitle, OnGetSectionTitle) SLATE_EVENT(FGetSectionToolTip
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip SLATE_EVENT (FGetSectionWidget, OnGetSectionWidget) SLATE_EVENT(FGetFilterText
OnActionDoubleClicked SLATE_EVENT (FOnActionDragged, OnActionDragged) SLATE_EVENT(FOnCategoryDragged
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText SLATE_EVENT (FOnActionMatchesName, OnActionMatchesName) SLATE_ARGUMENT(bool
SLATE_EVENT (FOnActionSelected, OnActionSelected) SLATE_EVENT(FOnActionDoubleClicked
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections SLATE_EVENT (FOnCategoryTextCommitted, OnCategoryTextCommitted) SLATE_EVENT(FCanRenameSelectedAction
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList SLATE_EVENT (FOnCollectAllActions, OnCollectAllActions) SLATE_EVENT(FOnCollectStaticSections
OnActionDoubleClicked OnCategoryDragged SLATE_EVENT (FOnContextMenuOpening, OnContextMenuOpening) SLATE_EVENT(FOnCreateWidgetForAction
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction SLATE_EVENT (FOnCreateCustomRowExpander, OnCreateCustomRowExpander) SLATE_EVENT(FOnGetActionList
void UpdateForNewActions (int32 IdxStart)
Updates the displayed list starting from IdxStart, useful for async building the display list of actions.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Data Fields
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel GraphObj bool bIsReadOnly = true)
const FText TWeakPtr< FGraphActionNode >
Static Public Attributes
static FString LastUsedFilterText
The last typed action within the graph action menu.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions
bool CanRenameNode (TWeakPtr< FGraphActionNode > InNode) const
Checks if the passed in node is safe for renaming.
const TArray< TSharedPtr< FGraphActionNode > > & GetFilteredActionNodes (int32 *OutSelectedIndex=nullptr)
FText GetFilterText () const
Get current filter text.
TSharedPtr< FGraphActionNode > GetFirstAction ()
General helper functions for accessing the filtered tree.
int32 GetTotalLeafNodes () const
bool HandleSelection (TSharedPtr< FGraphActionNode > &InSelectedItem, ESelectInfo::Type InSelectionType)
Executes the selection delegate providing it has been bound, and the provided action node given is valid and is an action node.
TSharedRef< ITableRow > MakeWidget (TSharedPtr< FGraphActionNode > InItem, const TSharedRef< STableViewBase > &OwnerTable, bool bIsReadOnly)
Create widget for the supplied node.
void MarkActiveSuggestion ()
Change the selection to reflect the active suggestion.
void OnFilterTextChanged (const FText &InFilterText)
Called when filter text changes.
void OnFilterTextCommitted (const FText &InText, ETextCommit::Type CommitInfo)
Called when enter is hit in search box.
void OnGetChildrenForCategory (TSharedPtr< FGraphActionNode > InItem, TArray< TSharedPtr< FGraphActionNode > > &OutChildren)
Get children.
void OnItemDoubleClicked (TSharedPtr< FGraphActionNode > InClickedItem)
Called when tree item is double clicked.
FReply OnItemDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when tree item dragged.
void OnItemScrolledIntoView (TSharedPtr< FGraphActionNode > InActionNode, const TSharedPtr< ITableRow > &InWidget)
Handler for when an item has scrolled into view after having been requested to do so.
void OnItemSelected (TSharedPtr< FGraphActionNode > InSelectedItem, ESelectInfo::Type SelectInfo)
Called when tree item is selected.
void OnNameTextCommitted (const FText &NewText, ETextCommit::Type InTextCommit, TWeakPtr< FGraphActionNode > InAction)
Callback when rename text is committed.
void OnSetExpansionRecursive (TSharedPtr< FGraphActionNode > InTreeNode, bool bInIsItemExpanded)
Callback for expanding tree items recursively.
void ScoreAndAddActions (int32 StartingIndex=INDEX_NONE)
Helper function for adding and scoring actions from our builder.
void SelectFirstAction ()
void SelectLastAction ()
void SelectNextAction (int32 Num=1)
void SelectPreviousAction (int32 Num=1)
Helper functions for keyboard interaction.
bool ShouldExpandNodes () const
Returns true if the tree should be autoexpanded.
bool TryToSpawnActiveSuggestion ()
Try to spawn the node reflected by the active suggestion.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TSharedPtr< FGraphActionListBuilderBase > AllActions
List of all actions we can browser.
bool bAllowPreselectedItemActivation
Whether we allow pre-selected items to be activated with a left-click.
bool bAlphaSortItems
Don't sort items alphabetically.
bool bAutoExpandActionMenu
Should we auto-expand categories.
bool bAutomaticallySelectSingleAction
Whether to automatically proceed with an action if it's the only one in the list.
bool bIgnoreUIUpdate
Allows us to set selection (via keyboard) without triggering action.
bool bIsKeyboardNavigating
True if the user is using the keyboard to navigatethe list, halting scoring of newly added entries so that selection is stable.
bool bShowFilterTextBox
Should we display the filter text box.
bool bSortItemsRecursively
If only the top entries should be sorted or subentries as well.
bool bUseSectionStyling
Should the rows and sections be styled like the details panel?
int32 DefaultRowExpanderBaseIndentLevel
The BaseIndentLevel of the default-created row expander.
int32 DisplayIndex
The slot that the selected item should be displayed at.
TArray< TSharedPtr< FGraphActionNode > > FilteredActionNodes
Flattened list of all actions passing the filter - access via GetFilteredActionNodes to ensure it's up to date.
TSharedPtr< FGraphActionNode > FilteredRootAction
Root of filtered actions tree.
TSharedPtr< SSearchBox > FilterTextBox
Text box used for searching for actions.
FOnActionDoubleClicked OnActionDoubleClicked
Delegate to call when action is double clicked.
FOnActionDragged OnActionDragged
Delegate to call when an action is dragged.
FOnActionMatchesName OnActionMatchesName
Delegate to check if an action matches a specified name (used for renaming items etc.)
FOnActionSelected OnActionSelected
Delegate to call when action is selected.
FCanRenameSelectedAction OnCanRenameSelectedAction
Delegate to call to check if a selected action is valid for renaming.
FOnCategoryDragged OnCategoryDragged
Delegate to call when a category is dragged.
FOnCategoryTextCommitted OnCategoryTextCommitted
Delegate to call to handle any post-category rename events.
FOnCollectAllActions OnCollectAllActions
Delegate to call to collect all actions.
FOnCollectStaticSections OnCollectStaticSections
Delegate to call to collect all always visible sections.
FOnCreateCustomRowExpander OnCreateCustomRowExpander
Delegate to call for creating a custom "expander" widget for indenting a menu row with.
FOnCreateWidgetForAction OnCreateWidgetForAction
Delegate to call to create widget for an action.
FOnGetActionList OnGetActionList
Delegate to call to get a custom action list.
FGetFilterText OnGetFilterText
Delegate to get the filter text if supplied from an external source.
FGetSectionTitle OnGetSectionTitle
Delegate to get the name of a section separator.
FGetSectionToolTip OnGetSectionToolTip
Delegate to get the tooltip of a section separator.
FGetSectionWidget OnGetSectionWidget
Delegate to get the widgets of a section separator.
TSharedPtr< FGraphActionNode > SelectedAction
The actual item selected - possibly redundant to selection information in the treeview, but the tree is rebuilt requently.
float SelectedSuggestionScore
Stored score for our current selection, so that we can quickly maintain selection when building the list asynchronously.
int32 SelectedSuggestionSourceIndex
Stored index in the AllActions list builder that we think is the best fit.
TSharedPtr< STreeView< TSharedPtr< FGraphActionNode > > > TreeView
Tree view for showing actions.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Attributes
TArray< UEdGraphPin * > DraggedFromPins
The pins that have been dragged off of to prompt the creation of this action menu.
UEdGraph * GraphObj
The graph that this menu is being constructed in.
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Class that displays a list of graph actions and them to be searched and selected.
Definition at line 112 of file SGraphActionMenu.h.
Member Function Documentation
AddReferencedObjects()
virtual void SGraphActionMenu::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
References AddReferencedObjects().
Referenced by AddReferencedObjects().
CanRenameNode()
bool SGraphActionMenu::CanRenameNode (TWeakPtr< FGraphActionNode > InNode) const protected
Checks if the passed in node is safe for renaming.
References CanRenameNode().
Referenced by CanRenameNode().
CanRequestRenameOnActionNode()
bool SGraphActionMenu::CanRequestRenameOnActionNode () const
Queries if a rename on the selected action node is possible.
References CanRequestRenameOnActionNode().
Referenced by CanRequestRenameOnActionNode().
DECLARE_DELEGATE_OneParam() [1/3]
SGraphActionMenu::DECLARE_DELEGATE_OneParam (FOnActionDoubleClicked , const TArray< TSharedPtr< FEdGraphSchemaAction > > &)
Delegate executed when an action is double clicked.
DECLARE_DELEGATE_OneParam() [2/3]
SGraphActionMenu::DECLARE_DELEGATE_OneParam (FOnCollectAllActions , FGraphActionListBuilderBase &)
Delegate executed when the list of all actions needs to be refreshed.
DECLARE_DELEGATE_OneParam() [3/3]
SGraphActionMenu::DECLARE_DELEGATE_OneParam (FOnCollectStaticSections , TArray< int32 > &)
Delegate executed when the list of all actions needs to be refreshed, should return any sections that should always be visible, even if they don't have children.
Delegate executed when a category is being renamed so any post-rename actions can be handled
DECLARE_DELEGATE_RetVal() [1/2]
SGraphActionMenu::DECLARE_DELEGATE_RetVal (FText , FGetFilterText)
Delegate to get the filter text.
References DECLARE_DELEGATE_RetVal().
Referenced by DECLARE_DELEGATE_RetVal(), and DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal() [2/2]
SGraphActionMenu::DECLARE_DELEGATE_RetVal (TSharedRef< FGraphActionListBuilderBase > , FOnGetActionList)
Delegate that can be used to create and/or get a custom action list.
References DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal_OneParam() [1/5]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_OneParam (bool , FCanRenameSelectedAction , TWeakPtr< FGraphActionNode >)
Delegate executed to check if the selected action is valid for renaming.
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [2/5]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_OneParam (FText , FGetSectionTitle , int32)
Delegate to get the name of a section if the widget is a section separator.
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [3/5]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_OneParam (TSharedPtr< IToolTip > , FGetSectionToolTip , int32)
Delegate to get the tooltip of a section if the widget is a section separator.
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [4/5]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< SExpanderArrow > , FOnCreateCustomRowExpander , FCustomExpanderData const &)
Delegate that can be used to create a custom "expander" widget for a particular row.
DECLARE_DELEGATE_RetVal_OneParam() [5/5]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< SWidget > , FOnCreateWidgetForAction , FCreateWidgetForActionData * const)
Delegate that can be used to create a widget for a particular action.
Referenced by DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_RetVal_OneParam(), and DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_TwoParams() [1/4]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_TwoParams (bool , FOnActionMatchesName , FEdGraphSchemaAction * , const FName &)
Delegate to check if an action matches a specified name (used for renaming items etc.)
References DECLARE_DELEGATE_RetVal_TwoParams().
DECLARE_DELEGATE_RetVal_TwoParams() [2/4]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_TwoParams (FReply , FOnActionDragged , const TArray< TSharedPtr< FEdGraphSchemaAction > > & , const FPointerEvent &)
Delegate executed when an action is dragged.
Referenced by DECLARE_DELEGATE_RetVal_TwoParams(), and DECLARE_DELEGATE_RetVal_TwoParams().
DECLARE_DELEGATE_RetVal_TwoParams() [3/4]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_TwoParams (FReply , FOnCategoryDragged , const FText & , const FPointerEvent &)
Delegate executed when a category is dragged.
DECLARE_DELEGATE_RetVal_TwoParams() [4/4]
SGraphActionMenu::DECLARE_DELEGATE_RetVal_TwoParams (TSharedRef< SWidget > , FGetSectionWidget , TSharedRef< SWidget > , int32)
Delegate to get the widget that appears on the section bar in the section separator.
References SWidget::SWidget(), and DECLARE_DELEGATE_RetVal_TwoParams().
DECLARE_DELEGATE_TwoParams()
SGraphActionMenu::DECLARE_DELEGATE_TwoParams (FOnActionSelected , const TArray< TSharedPtr< FEdGraphSchemaAction > > & , ESelectInfo::Type)
Delegate executed when an action is selected.
ExpandCategory()
void SGraphActionMenu::ExpandCategory (const FText & CategoryName)
Expands any category with the associated name.
References ExpandCategory().
Referenced by ExpandCategory().
GenerateFilteredItems()
void SGraphActionMenu::GenerateFilteredItems (bool bPreserveExpansion)
Regenerated filtered results (FilteredRootAction) based on filter text.
References GenerateFilteredItems().
Referenced by GenerateFilteredItems().
GetCategorySubActions()
void SGraphActionMenu::GetCategorySubActions (TWeakPtr< FGraphActionNode > InAction, TArray< TSharedPtr< FEdGraphSchemaAction > > & OutActions) const
Get category child actions for the passed in action.
References GetCategorySubActions().
Referenced by GetCategorySubActions().
GetFilteredActionNodes()
const TArray< TSharedPtr< FGraphActionNode > > & SGraphActionMenu::GetFilteredActionNodes (int32 * OutSelectedIndex = nullptr) protected
References GetFilteredActionNodes().
Referenced by GetFilteredActionNodes().
GetFilterText()
FText SGraphActionMenu::GetFilterText () const protected
Get current filter text.
References GetFilterText().
Referenced by GetFilterText().
GetFilterTextBox()
TSharedRef< SEditableTextBox > SGraphActionMenu::GetFilterTextBox ()
Get filter text box widget.
References GetFilterTextBox().
Referenced by GetFilterTextBox().
GetFirstAction()
TSharedPtr< FGraphActionNode > SGraphActionMenu::GetFirstAction () protected
General helper functions for accessing the filtered tree.
References GetFirstAction().
Referenced by GetFirstAction().
GetReferencerName()
virtual FString SGraphActionMenu::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
References GetReferencerName().
Referenced by GetReferencerName().
GetSectionExpansion()
void SGraphActionMenu::GetSectionExpansion (TMap< int32, bool > & SectionExpansion) const
Returns a map of all top level sections and their current expansion state.
References GetSectionExpansion().
Referenced by GetSectionExpansion().
GetSelectedActions()
void SGraphActionMenu::GetSelectedActions (TArray< TSharedPtr< FEdGraphSchemaAction > > & OutSelectedActions) const
Get action that is currently selected.
References GetSelectedActions().
Referenced by GetSelectedActions().
GetSelectedCategoryName()
FString SGraphActionMenu::GetSelectedCategoryName () const
Get category that is currently selected.
References GetSelectedCategoryName().
Referenced by GetSelectedCategoryName().
GetSelectedCategorySubActions()
void SGraphActionMenu::GetSelectedCategorySubActions (TArray< TSharedPtr< FEdGraphSchemaAction > > & OutActions) const
Get category child actions that is currently selected.
References GetSelectedCategorySubActions().
Referenced by GetSelectedCategorySubActions().
GetTotalLeafNodes()
int32 SGraphActionMenu::GetTotalLeafNodes () const protected
References GetTotalLeafNodes().
Referenced by GetTotalLeafNodes().
HandleSelection()
bool SGraphActionMenu::HandleSelection (TSharedPtr< FGraphActionNode > & InSelectedItem, ESelectInfo::Type InSelectionType) protected
Executes the selection delegate providing it has been bound, and the provided action node given is valid and is an action node.
Parameters
InselectedItem The graph action node selected
Returns
true if item selection delegate was executed
References HandleSelection().
Referenced by HandleSelection().
MakeWidget()
TSharedRef< ITableRow > SGraphActionMenu::MakeWidget (TSharedPtr< FGraphActionNode > InItem, const TSharedRef< STableViewBase > & OwnerTable, bool bIsReadOnly) protected
Create widget for the supplied node.
References bIsReadOnly, and MakeWidget().
Referenced by MakeWidget().
MarkActiveSuggestion()
void SGraphActionMenu::MarkActiveSuggestion () protected
Change the selection to reflect the active suggestion.
References MarkActiveSuggestion().
Referenced by MarkActiveSuggestion().
OnFilterTextChanged()
void SGraphActionMenu::OnFilterTextChanged (const FText & InFilterText) protected
Called when filter text changes.
References OnFilterTextChanged().
Referenced by OnFilterTextChanged().
OnFilterTextCommitted()
void SGraphActionMenu::OnFilterTextCommitted (const FText & InText, ETextCommit::Type CommitInfo) protected
Called when enter is hit in search box.
References OnFilterTextCommitted().
Referenced by OnFilterTextCommitted().
OnGetChildrenForCategory()
void SGraphActionMenu::OnGetChildrenForCategory (TSharedPtr< FGraphActionNode > InItem, TArray< TSharedPtr< FGraphActionNode > > & OutChildren) protected
Get children.
References OnGetChildrenForCategory().
Referenced by OnGetChildrenForCategory().
OnItemDoubleClicked()
void SGraphActionMenu::OnItemDoubleClicked (TSharedPtr< FGraphActionNode > InClickedItem) protected
Called when tree item is double clicked.
References OnItemDoubleClicked().
Referenced by OnItemDoubleClicked().
OnItemDragDetected()
FReply SGraphActionMenu::OnItemDragDetected (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) protected
Called when tree item dragged.
References MouseEvent, and OnItemDragDetected().
Referenced by OnItemDragDetected().
OnItemScrolledIntoView()
void SGraphActionMenu::OnItemScrolledIntoView (TSharedPtr< FGraphActionNode > InActionNode, const TSharedPtr< ITableRow > & InWidget) protected
Handler for when an item has scrolled into view after having been requested to do so.
References OnItemScrolledIntoView().
Referenced by OnItemScrolledIntoView().
OnItemSelected()
void SGraphActionMenu::OnItemSelected (TSharedPtr< FGraphActionNode > InSelectedItem, ESelectInfo::Type SelectInfo) protected
Called when tree item is selected.
Parameters
InSelectedItem The action node that is being selected
SelectInfo Selection type - Only OnMouseClick and OnKeyPress will trigger a call to HandleSelection
References OnItemSelected().
Referenced by OnItemSelected().
OnKeyDown()
virtual FReply SGraphActionMenu::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnMouseButtonDownEvent()
bool SGraphActionMenu::OnMouseButtonDownEvent (TWeakPtr< FEdGraphSchemaAction > InAction)
References OnMouseButtonDownEvent().
Referenced by OnMouseButtonDownEvent().
OnNameTextCommitted()
void SGraphActionMenu::OnNameTextCommitted (const FText & NewText, ETextCommit::Type InTextCommit, TWeakPtr< FGraphActionNode > InAction) protected
Callback when rename text is committed.
References OnNameTextCommitted().
Referenced by OnNameTextCommitted().
OnRequestRenameOnActionNode()
void SGraphActionMenu::OnRequestRenameOnActionNode ()
Initiates a rename on the selected action node, if possible.
References OnRequestRenameOnActionNode().
Referenced by OnRequestRenameOnActionNode().
OnSetExpansionRecursive()
void SGraphActionMenu::OnSetExpansionRecursive (TSharedPtr< FGraphActionNode > InTreeNode, bool bInIsItemExpanded) protected
Callback for expanding tree items recursively.
References OnSetExpansionRecursive().
Referenced by OnSetExpansionRecursive().
RefreshAllActions()
void SGraphActionMenu::RefreshAllActions (bool bPreserveExpansion, bool bHandleOnSelectionEvent = true)
Refreshes the actions that this widget should display.
Parameters
bPreserveExpansion TRUE if the expansion state of the tree should be preserved
bHandleOnSelectionEvent TRUE if the item should be selected and any actions that occur with selection will be handled. FALSE and only selection will occur
References RefreshAllActions().
Referenced by RefreshAllActions().
ScoreAndAddActions()
void SGraphActionMenu::ScoreAndAddActions (int32 StartingIndex = INDEX_NONE) protected
Helper function for adding and scoring actions from our builder.
References INDEX_NONE, and ScoreAndAddActions().
Referenced by ScoreAndAddActions().
SelectFirstAction()
void SGraphActionMenu::SelectFirstAction () protected
References SelectFirstAction().
Referenced by SelectFirstAction().
SelectItemByName()
bool SGraphActionMenu::SelectItemByName (const FName & ItemName, ESelectInfo::Type SelectInfo = ESelectInfo::Direct, int32 SectionId = INDEX_NONE, bool bIsCategory = false)
Selects an non-creation item in the list, searching by FName, deselects if name is none.
Parameters
ItemName The name of the item to select
SelectInfo The selection type
SectionId If known, the section Id to restrict the selection to, useful in the case of categories where they can exist multiple times
bIsCategory TRUE if the selection is a category, categories obey different rules and it's hard to re-select properly without this knowledge
Returns
TRUE if the item was successfully selected or the tree cleared, FALSE if unsuccessful
References Direct, INDEX_NONE, and SelectItemByName().
Referenced by SelectItemByName().
SelectLastAction()
void SGraphActionMenu::SelectLastAction () protected
References SelectLastAction().
Referenced by SelectLastAction().
SelectNextAction()
void SGraphActionMenu::SelectNextAction (int32 Num = 1) protected
References Num, and SelectNextAction().
Referenced by SelectNextAction().
SelectPreviousAction()
void SGraphActionMenu::SelectPreviousAction (int32 Num = 1) protected
Helper functions for keyboard interaction.
References Num, and SelectPreviousAction().
Referenced by SelectPreviousAction().
SetSectionExpansion()
void SGraphActionMenu::SetSectionExpansion (const TMap< int32, bool > & SectionExpansion)
Sets the sections to be expanded of all top level sections.
References SetSectionExpansion().
Referenced by SetSectionExpansion().
ShouldExpandNodes()
bool SGraphActionMenu::ShouldExpandNodes () const protected
Returns true if the tree should be autoexpanded.
References ShouldExpandNodes().
Referenced by ShouldExpandNodes().
SLATE_ARGUMENT() [1/5]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SGraphActionMenu::SLATE_ARGUMENT (bool , AlphaSortItems)
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ARGUMENT() [2/5]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling SGraphActionMenu::SLATE_ARGUMENT (bool , bAllowPreselectedItemActivation)
References bAllowPreselectedItemActivation, DefaultRowExpanderBaseIndentLevel, and SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/5]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel GraphObj SGraphActionMenu::SLATE_ARGUMENT (bool , bAutomaticallySelectSingleAction) const &
References bAutomaticallySelectSingleAction, SLATE_ARGUMENT(), and SLATE_END_ARGS.
SLATE_ARGUMENT() [4/5]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively SGraphActionMenu::SLATE_ARGUMENT (bool , ShowFilterTextBox)
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [5/5]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel SGraphActionMenu::SLATE_ARGUMENT (TArray< UEdGraphPin * > , DraggedFromPins)
References DraggedFromPins, GraphObj, and SLATE_ARGUMENT().
SLATE_BEGIN_ARGS()
SGraphActionMenu::SLATE_BEGIN_ARGS (SGraphActionMenu) inline
Definition at line 148 of file SGraphActionMenu.h.
References SLATE_BEGIN_ARGS().
Referenced by SLATE_BEGIN_ARGS().
SLATE_EVENT() [1/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction SGraphActionMenu::SLATE_EVENT (FGetSectionTitle , OnGetSectionTitle)
References OnGetSectionTitle, OnGetSectionToolTip, and SLATE_EVENT().
SLATE_EVENT() [2/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip SGraphActionMenu::SLATE_EVENT (FGetSectionWidget , OnGetSectionWidget)
References OnGetFilterText, OnGetSectionWidget, and SLATE_EVENT().
SLATE_EVENT() [3/9]
OnActionDoubleClicked SGraphActionMenu::SLATE_EVENT (FOnActionDragged , OnActionDragged)
References OnActionDragged, OnCategoryDragged, and SLATE_EVENT().
SLATE_EVENT() [4/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText SGraphActionMenu::SLATE_EVENT (FOnActionMatchesName , OnActionMatchesName)
References OnActionMatchesName, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_EVENT() [5/9]
SGraphActionMenu::SLATE_EVENT (FOnActionSelected , OnActionSelected)
References OnActionDoubleClicked, and OnActionSelected.
Referenced by SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [6/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections SGraphActionMenu::SLATE_EVENT (FOnCategoryTextCommitted , OnCategoryTextCommitted)
References OnCanRenameSelectedAction, OnCategoryTextCommitted, and SLATE_EVENT().
SLATE_EVENT() [7/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList SGraphActionMenu::SLATE_EVENT (FOnCollectAllActions , OnCollectAllActions)
References OnCollectAllActions, OnCollectStaticSections, and SLATE_EVENT().
SLATE_EVENT() [8/9]
OnActionDoubleClicked OnCategoryDragged SGraphActionMenu::SLATE_EVENT (FOnContextMenuOpening , OnContextMenuOpening)
References OnCreateWidgetForAction, and SLATE_EVENT().
SLATE_EVENT() [9/9]
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction SGraphActionMenu::SLATE_EVENT (FOnCreateCustomRowExpander , OnCreateCustomRowExpander)
References OnCreateCustomRowExpander, OnGetActionList, and SLATE_EVENT().
TryToSpawnActiveSuggestion()
bool SGraphActionMenu::TryToSpawnActiveSuggestion () protected
Try to spawn the node reflected by the active suggestion.
References TryToSpawnActiveSuggestion().
Referenced by TryToSpawnActiveSuggestion().
UpdateForNewActions()
void SGraphActionMenu::UpdateForNewActions (int32 IdxStart)
Updates the displayed list starting from IdxStart, useful for async building the display list of actions.
References UpdateForNewActions().
Referenced by UpdateForNewActions().
Field Documentation
AllActions
TSharedPtr<FGraphActionListBuilderBase> SGraphActionMenu::AllActions protected
List of all actions we can browser.
Definition at line 216 of file SGraphActionMenu.h.
bAllowPreselectedItemActivation
bool SGraphActionMenu::bAllowPreselectedItemActivation protected
Whether we allow pre-selected items to be activated with a left-click.
Definition at line 246 of file SGraphActionMenu.h.
Referenced by SLATE_ARGUMENT().
bAlphaSortItems
bool SGraphActionMenu::bAlphaSortItems protected
Don't sort items alphabetically.
Definition at line 238 of file SGraphActionMenu.h.
bAutoExpandActionMenu
bool SGraphActionMenu::bAutoExpandActionMenu protected
Should we auto-expand categories.
Definition at line 234 of file SGraphActionMenu.h.
bAutomaticallySelectSingleAction
bool SGraphActionMenu::bAutomaticallySelectSingleAction protected
Whether to automatically proceed with an action if it's the only one in the list.
Definition at line 248 of file SGraphActionMenu.h.
Referenced by SLATE_ARGUMENT().
bIgnoreUIUpdate
bool SGraphActionMenu::bIgnoreUIUpdate protected
Allows us to set selection (via keyboard) without triggering action.
Definition at line 232 of file SGraphActionMenu.h.
bIsKeyboardNavigating
bool SGraphActionMenu::bIsKeyboardNavigating protected
True if the user is using the keyboard to navigatethe list, halting scoring of newly added entries so that selection is stable.
Definition at line 244 of file SGraphActionMenu.h.
bIsReadOnly
OnActionDoubleClicked OnCategoryDragged OnCreateWidgetForAction OnGetActionList OnCollectStaticSections OnCanRenameSelectedAction OnGetSectionToolTip OnGetFilterText AutoExpandActionMenu SortItemsRecursively UseSectionStyling DefaultRowExpanderBaseIndentLevel GraphObj bool SGraphActionMenu::bIsReadOnly = true)
Definition at line 190 of file SGraphActionMenu.h.
Referenced by MakeWidget().
bShowFilterTextBox
bool SGraphActionMenu::bShowFilterTextBox protected
Should we display the filter text box.
Definition at line 236 of file SGraphActionMenu.h.
bSortItemsRecursively
bool SGraphActionMenu::bSortItemsRecursively protected
If only the top entries should be sorted or subentries as well.
Definition at line 240 of file SGraphActionMenu.h.
bUseSectionStyling
bool SGraphActionMenu::bUseSectionStyling protected
Should the rows and sections be styled like the details panel?
Definition at line 242 of file SGraphActionMenu.h.
DefaultRowExpanderBaseIndentLevel
int32 SGraphActionMenu::DefaultRowExpanderBaseIndentLevel protected
The BaseIndentLevel of the default-created row expander.
Not used with OnCreateCustomRowExpander.
Definition at line 250 of file SGraphActionMenu.h.
Referenced by SLATE_ARGUMENT().
DisplayIndex
int32 SGraphActionMenu::DisplayIndex protected
The slot that the selected item should be displayed at.
Definition at line 252 of file SGraphActionMenu.h.
DraggedFromPins
TArray<UEdGraphPin*> SGraphActionMenu::DraggedFromPins private
The pins that have been dragged off of to prompt the creation of this action menu.
Definition at line 406 of file SGraphActionMenu.h.
Referenced by SLATE_ARGUMENT().
FilteredActionNodes
TArray< TSharedPtr<FGraphActionNode> > SGraphActionMenu::FilteredActionNodes protected
Flattened list of all actions passing the filter - access via GetFilteredActionNodes to ensure it's up to date.
Definition at line 219 of file SGraphActionMenu.h.
FilteredRootAction
TSharedPtr<FGraphActionNode> SGraphActionMenu::FilteredRootAction protected
Root of filtered actions tree.
Definition at line 222 of file SGraphActionMenu.h.
FilterTextBox
TSharedPtr<SSearchBox> SGraphActionMenu::FilterTextBox protected
Text box used for searching for actions.
Definition at line 213 of file SGraphActionMenu.h.
GraphObj
UEdGraph* SGraphActionMenu::GraphObj private
The graph that this menu is being constructed in.
Definition at line 409 of file SGraphActionMenu.h.
Referenced by SLATE_ARGUMENT().
LastUsedFilterText
FString SGraphActionMenu::LastUsedFilterText static
The last typed action within the graph action menu.
Definition at line 336 of file SGraphActionMenu.h.
OnActionDoubleClicked
FOnActionDoubleClicked SGraphActionMenu::OnActionDoubleClicked protected
Delegate to call when action is double clicked.
Definition at line 257 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnActionDragged
FOnActionDragged SGraphActionMenu::OnActionDragged protected
Delegate to call when an action is dragged.
Definition at line 259 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnActionMatchesName
FOnActionMatchesName SGraphActionMenu::OnActionMatchesName protected
Delegate to check if an action matches a specified name (used for renaming items etc.)
Definition at line 285 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnActionSelected
FOnActionSelected SGraphActionMenu::OnActionSelected protected
Delegate to call when action is selected.
Definition at line 255 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCanRenameSelectedAction
FCanRenameSelectedAction SGraphActionMenu::OnCanRenameSelectedAction protected
Delegate to call to check if a selected action is valid for renaming.
Definition at line 275 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCategoryDragged
FOnCategoryDragged SGraphActionMenu::OnCategoryDragged protected
Delegate to call when a category is dragged.
Definition at line 261 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCategoryTextCommitted
FOnCategoryTextCommitted SGraphActionMenu::OnCategoryTextCommitted protected
Delegate to call to handle any post-category rename events.
Definition at line 273 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCollectAllActions
FOnCollectAllActions SGraphActionMenu::OnCollectAllActions protected
Delegate to call to collect all actions.
Definition at line 269 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCollectStaticSections
FOnCollectStaticSections SGraphActionMenu::OnCollectStaticSections protected
Delegate to call to collect all always visible sections.
Definition at line 271 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCreateCustomRowExpander
FOnCreateCustomRowExpander SGraphActionMenu::OnCreateCustomRowExpander protected
Delegate to call for creating a custom "expander" widget for indenting a menu row with.
Definition at line 265 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnCreateWidgetForAction
FOnCreateWidgetForAction SGraphActionMenu::OnCreateWidgetForAction protected
Delegate to call to create widget for an action.
Definition at line 263 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnGetActionList
FOnGetActionList SGraphActionMenu::OnGetActionList protected
Delegate to call to get a custom action list.
Definition at line 267 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnGetFilterText
FGetFilterText SGraphActionMenu::OnGetFilterText protected
Delegate to get the filter text if supplied from an external source.
Definition at line 283 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnGetSectionTitle
FGetSectionTitle SGraphActionMenu::OnGetSectionTitle protected
Delegate to get the name of a section separator.
Definition at line 277 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnGetSectionToolTip
FGetSectionToolTip SGraphActionMenu::OnGetSectionToolTip protected
Delegate to get the tooltip of a section separator.
Definition at line 279 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
OnGetSectionWidget
FGetSectionWidget SGraphActionMenu::OnGetSectionWidget protected
Delegate to get the widgets of a section separator.
Definition at line 281 of file SGraphActionMenu.h.
Referenced by SLATE_EVENT().
SelectedAction
TSharedPtr<FGraphActionNode> SGraphActionMenu::SelectedAction protected
The actual item selected - possibly redundant to selection information in the treeview, but the tree is rebuilt requently.
Definition at line 229 of file SGraphActionMenu.h.
SelectedSuggestionScore
float SGraphActionMenu::SelectedSuggestionScore protected
Stored score for our current selection, so that we can quickly maintain selection when building the list asynchronously.
Definition at line 225 of file SGraphActionMenu.h.
SelectedSuggestionSourceIndex
int32 SGraphActionMenu::SelectedSuggestionSourceIndex protected
Stored index in the AllActions list builder that we think is the best fit.
Definition at line 227 of file SGraphActionMenu.h.
TreeView
TSharedPtr< STreeView< TSharedPtr<FGraphActionNode> > > SGraphActionMenu::TreeView protected
Tree view for showing actions.
Definition at line 211 of file SGraphActionMenu.h.
TWeakPtr< FGraphActionNode >
const FText SGraphActionMenu::TWeakPtr< FGraphActionNode >
Definition at line 132 of file SGraphActionMenu.h.
The documentation for this class was generated from the following file:
SGraphActionMenu.h