Unreal Engine 5.6 C++ API: FEditorClassUtils Namespace Reference
FEditorClassUtils Namespace Reference
Data Structures
struct FSourceLinkParams
Optional GetSourceLink parameters.
Functions
UNREALED_API UClass * GetClassFromString (const FString &ClassName)
Fetches a UClass from the string name of the class.
UNREALED_API FTopLevelAssetPath GetClassPathNameFromAsset (const FAssetData &InAssetData, bool bGenerateClassPathIfMissing=false)
Gets the object path of the class associated with the specified asset (i.e.
UNREALED_API FTopLevelAssetPath GetClassPathNameFromAssetTag (const FAssetData &InAssetData)
Gets the class path from the asset tag (i.e.
UNREALED_API FString GetDocumentationExcerpt (const UClass *Class)
Gets the excerpt to use for this class Excerpt will be contained on the page returned by GetDocumentationPage.
UNREALED_API FString GetDocumentationLink (const UClass *Class, const FString &OverrideExcerpt=FString())
Returns the link path to the documentation for a given class.
UNREALED_API FString GetDocumentationLinkBaseUrl (const UClass *Class, const FString &OverrideExcerpt=FString())
Returns the ID of the base documentation URL set for this class in its documentation excerpt.
UNREALED_API FString GetDocumentationLinkBaseUrlFromExcerpt (const FString &DocLink, const FString DocExcerpt)
Returns the ID of the base documentation URL set in the specified excerpt.
UNREALED_API FString GetDocumentationLinkFromExcerpt (const FString &DocLink, const FString DocExcerpt)
Return link path from a specified excerpt.
UNREALED_API TSharedRef< SWidget > GetDocumentationLinkWidget (const UClass *Class)
Creates a link widget to the documentation for a given class.
UNREALED_API FString GetDocumentationPage (const UClass *Class)
Gets the page that documentation for this class is contained on.
UNREALED_API TSharedRef< SWidget > GetDynamicDocumentationLinkWidget (const TAttribute< const UClass * > &ClassAttribute)
Create a link widget to the documentation for a potentially dynamic link widget.
UNREALED_API void GetImplementedInterfaceClassPathsFromAsset (const FAssetData &InAssetData, TArray< FString > &OutClassPaths)
Fetches the set of interface class object paths from an asset data entry containing the appropriate asset tag(s).
UNREALED_API TSharedRef< SWidget > GetSourceLink (const UClass *Class, const FSourceLinkParams &Params=FSourceLinkParams())
Creates an hyperlink to the source code or blueprint for a given class (or a text block/spacer if the link is unavailable for some reason)
UNREALED_API TSharedRef< SWidget > GetSourceLink (const UClass *Class, const TWeakObjectPtr< UObject > ObjectWeakPtr)
Creates an hyperlink to the source code or blueprint for a given class (or a spacer if the link is unavailable for some reason)
UNREALED_API TSharedRef< SWidget > GetSourceLinkFormatted (const UClass *Class, const TWeakObjectPtr< UObject > ObjectWeakPtr, const FText &BlueprintFormat, const FText &CodeFormat)
Creates an hyperlink to the source code or blueprint for a given class formatted however you need.
UNREALED_API TSharedRef< SToolTip > GetTooltip (const UClass *Class)
Gets the tooltip to display for a given class.
UNREALED_API TSharedRef< SToolTip > GetTooltip (const UClass *Class, const TAttribute< FText > &OverrideText)
Gets the tooltip to display for a given class with specified text for the tooltip.
UNREALED_API bool IsBlueprintAsset (const FAssetData &InAssetData, bool *bOutIsBPGC=nullptr)
Returns whether the specified asset is a UBlueprint or UBlueprintGeneratedClass (or any of their derived classes)
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use GetClassPathNameFromAsset.") UNREALED_API FName GetClassPathFromAsset(const FAssetData &InAssetData
Gets the object path of the class associated with the specified asset (i.e.
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use GetClassPathNameFromAssetTag.") UNREALED_API FName GetClassPathFromAssetTag(const FAssetData &InAssetData)
Gets the class path from the asset tag (i.e.
Variables
bool bGenerateClassPathIfMissing = false)
Function Documentation
GetClassFromString()
UNREALED_API UClass * FEditorClassUtils::GetClassFromString (const FString & ClassName)
Fetches a UClass from the string name of the class.
Parameters
ClassName Name of the class we want the UClass for
Returns
UClass pointer if it exists
Referenced by FGameModeInfoCustomizer::GetCurrentGameModeClass().
GetClassPathNameFromAsset()
UNREALED_API FTopLevelAssetPath FEditorClassUtils::GetClassPathNameFromAsset (const FAssetData & InAssetData, bool bGenerateClassPathIfMissing = false)
Gets the object path of the class associated with the specified asset (i.e.
the BlueprintGeneratedClass of a Blueprint asset or the BlueprintGeneratedClass asset itself)
Parameters
InAssetData Reference to an asset data entry
bGenerateClassPathIfMissing Whether to generate a class path if the class is missing (and the asset can have a class associated with it)
Returns
Class path or None if the asset cannot or doesn't have a class associated with it
References bGenerateClassPathIfMissing, and GetClassPathNameFromAsset().
Referenced by GetClassPathNameFromAsset().
GetClassPathNameFromAssetTag()
UNREALED_API FTopLevelAssetPath FEditorClassUtils::GetClassPathNameFromAssetTag (const FAssetData & InAssetData)
Gets the class path from the asset tag (i.e.
GeneratedClassPath tag on blueprints)
Parameters
InAssetData Reference to an asset data entry.
Returns
Class path or None if the asset cannot or doesn't have a class associated with it
References GetClassPathNameFromAssetTag().
Referenced by GetClassPathNameFromAssetTag().
GetDocumentationExcerpt()
UNREALED_API FString FEditorClassUtils::GetDocumentationExcerpt (const UClass * Class)
Gets the excerpt to use for this class Excerpt will be contained on the page returned by GetDocumentationPage.
Parameters
InClass Class we want to find the documentation excerpt of
Returns
Name of the to the documentation excerpt
References Class.
GetDocumentationLink()
UNREALED_API FString FEditorClassUtils::GetDocumentationLink (const UClass * Class, const FString & OverrideExcerpt = FString())
Returns the link path to the documentation for a given class.
Parameters
Class Class we want to build a link for
Returns
The path to the documentation for the class
References Class.
GetDocumentationLinkBaseUrl()
UNREALED_API FString FEditorClassUtils::GetDocumentationLinkBaseUrl (const UClass * Class, const FString & OverrideExcerpt = FString())
Returns the ID of the base documentation URL set for this class in its documentation excerpt.
Parameters
Class Class we want to build a link for
Returns
The ID of the base URL
References Class.
GetDocumentationLinkBaseUrlFromExcerpt()
UNREALED_API FString FEditorClassUtils::GetDocumentationLinkBaseUrlFromExcerpt (const FString & DocLink, const FString DocExcerpt)
Returns the ID of the base documentation URL set in the specified excerpt.
GetDocumentationLinkFromExcerpt()
UNREALED_API FString FEditorClassUtils::GetDocumentationLinkFromExcerpt (const FString & DocLink, const FString DocExcerpt)
Return link path from a specified excerpt.
GetDocumentationLinkWidget()
UNREALED_API TSharedRef< SWidget > FEditorClassUtils::GetDocumentationLinkWidget (const UClass * Class)
Creates a link widget to the documentation for a given class.
Parameters
Class Class we want to build a link for
Returns
Shared pointer to the constructed tooltip
References Class.
GetDocumentationPage()
UNREALED_API FString FEditorClassUtils::GetDocumentationPage (const UClass * Class)
Gets the page that documentation for this class is contained on.
Parameters
InClass Class we want to find the documentation page of
Returns
Path to the documentation page
References Class.
GetDynamicDocumentationLinkWidget()
UNREALED_API TSharedRef< SWidget > FEditorClassUtils::GetDynamicDocumentationLinkWidget (const TAttribute< const UClass * > & ClassAttribute)
Create a link widget to the documentation for a potentially dynamic link widget.
Parameters
Class The attribute of the class to show documentation for.
GetImplementedInterfaceClassPathsFromAsset()
UNREALED_API void FEditorClassUtils::GetImplementedInterfaceClassPathsFromAsset (const FAssetData & InAssetData, TArray< FString > & OutClassPaths)
Fetches the set of interface class object paths from an asset data entry containing the appropriate asset tag(s).
Parameters
InAssetData Reference to an asset data entry.
OutClassPaths One or more interface class object paths, or empty if the corresponding asset tag(s) were not found.
References GetImplementedInterfaceClassPathsFromAsset().
Referenced by GetImplementedInterfaceClassPathsFromAsset().
GetSourceLink() [1/2]
UNREALED_API TSharedRef< SWidget > FEditorClassUtils::GetSourceLink (const UClass * Class, const FSourceLinkParams & Params = FSourceLinkParams())
Creates an hyperlink to the source code or blueprint for a given class (or a text block/spacer if the link is unavailable for some reason)
Parameters
Class Class we want to build a link for
Params See FSourceLinkOptionalParams
Returns
Shared pointer to the constructed widget
References Class, and Params.
GetSourceLink() [2/2]
UNREALED_API TSharedRef< SWidget > FEditorClassUtils::GetSourceLink (const UClass * Class, const TWeakObjectPtr< UObject > ObjectWeakPtr)
Creates an hyperlink to the source code or blueprint for a given class (or a spacer if the link is unavailable for some reason)
Parameters
Class Class we want to build a link for
ObjectWeakPtr Optional object to set blueprint debugging to in the case we are choosing a blueprint
Returns
Shared pointer to the constructed widget
References Class.
GetSourceLinkFormatted()
UNREALED_API TSharedRef< SWidget > FEditorClassUtils::GetSourceLinkFormatted (const UClass * Class, const TWeakObjectPtr< UObject > ObjectWeakPtr, const FText & BlueprintFormat, const FText & CodeFormat)
Creates an hyperlink to the source code or blueprint for a given class formatted however you need.
Example "Edit {0}" (or a spacer if the link is unavailable for some reason)
Parameters
Class Class we want to build a link for
ObjectWeakPtr Optional object to set blueprint debugging to in the case we are choosing a blueprint
BlueprintFormat The text format for blueprint links
CodeFormat The text format for C++ code file links
Returns
Shared pointer to the constructed widget
References Class.
GetTooltip() [1/2]
UNREALED_API TSharedRef< SToolTip > FEditorClassUtils::GetTooltip (const UClass * Class)
Gets the tooltip to display for a given class.
Parameters
InClass Class we want to build a tooltip for
Returns
Shared reference to the constructed tooltip
References Class.
GetTooltip() [2/2]
UNREALED_API TSharedRef< SToolTip > FEditorClassUtils::GetTooltip (const UClass * Class, const TAttribute< FText > & OverrideText)
Gets the tooltip to display for a given class with specified text for the tooltip.
Parameters
InClass Class we want to build a tooltip for
OverrideText The text to display on the standard tooltip
Returns
Shared reference to the constructed tooltip
References Class.
IsBlueprintAsset()
UNREALED_API bool FEditorClassUtils::IsBlueprintAsset (const FAssetData & InAssetData, bool * bOutIsBPGC = nullptr)
Returns whether the specified asset is a UBlueprint or UBlueprintGeneratedClass (or any of their derived classes)
Parameters
InAssetData Reference to an asset data entry
bOutIsBPGC Outputs whether the asset is a BlueprintGeneratedClass (or any of its derived classes)
Returns
Whether the specified asset is a UBlueprint or UBlueprintGeneratedClass (or any of their derived classes)
UE_DEPRECATED() [1/2]
FEditorClassUtils::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use GetClassPathNameFromAsset.") const &
Gets the object path of the class associated with the specified asset (i.e.
the BlueprintGeneratedClass of a Blueprint asset or the BlueprintGeneratedClass asset itself)
Parameters
InAssetData Reference to an asset data entry
bGenerateClassPathIfMissing Whether to generate a class path if the class is missing (and the asset can have a class associated with it)
Returns
Class path or None if the asset cannot or doesn't have a class associated with it
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FEditorClassUtils::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use GetClassPathNameFromAssetTag.") const &
Gets the class path from the asset tag (i.e.
GeneratedClassPath tag on blueprints)
Parameters
InAssetData Reference to an asset data entry.
Returns
Class path or None if the asset cannot or doesn't have a class associated with it
Referenced by UE_DEPRECATED().
Variable Documentation
bGenerateClassPathIfMissing
bool FEditorClassUtils::bGenerateClassPathIfMissing = false)
Definition at line 189 of file EditorClassUtils.h.
Referenced by GetClassPathNameFromAsset().