Unreal Engine 5.6 C++ API: UObjectHash.h File Reference
UObjectHash.h File Reference
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/Map.h"
#include "Containers/Set.h"
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Stats/Stats.h"
#include "Templates/Function.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectArray.h"
#include "UObject/UnrealNames.h"
Data Structures
class FScopedUObjectHashTablesLock
Helper class for scoped hash tables lock.
Enumerations
enum class EObjectMemoryOverheadOptions { None , ShowIndividualStats = 1 << 0 , IncludeReflectionData = 1 << 1 }
Functions
bool ClassHasInstancesAsyncLoading (const UClass *ClassToLookFor)
Returns true if any instances of the class in question are currently being async loaded.
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("NumObjects"), STAT_Hash_NumObjects, STATGROUP_UObjectHash, 1)
DECLARE_STATS_GROUP_VERBOSE (TEXT("UObject Hash"), STATGROUP_UObjectHash, STATCAT_Advanced)
ENUM_CLASS_FLAGS (EObjectMemoryOverheadOptions) 1 void LogHashMemoryOverheadStatistics(FOutputDevice &Ar
Logs out information about the total object hash memory usage for debug purposes.
class UObjectBase * FindObjectWithOuter (const class UObjectBase *Outer, const class UClass *ClassToLookFor=nullptr, FName NameToLookFor=NAME_None)
Find an objects with a given name and or class within an outer.
void ForEachObjectOfClass (const UClass *ClassToLookFor, TFunctionRef< void(UObject *)> Operation, bool bIncludeDerivedClasses=true, EObjectFlags ExcludeFlags=RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Performs an operation on all objects of the provided class Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
void ForEachObjectOfClasses (TArrayView< const UClass *const > ClassesToLookFor, TFunctionRef< void(UObject *)> Operation, EObjectFlags ExcludeFlags=RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Performs an operation on all objects of the provided classes Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
void ForEachObjectWithOuter (const class UObjectBase *Outer, TFunctionRef< void(UObject *)> Operation, bool bIncludeNestedObjects=true, EObjectFlags ExclusionFlags=RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Performs an operation on all objects with a given outer Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
void ForEachObjectWithOuterBreakable (const class UObjectBase *Outer, TFunctionRef< bool(UObject *)> Operation, bool bIncludeNestedObjects=true, EObjectFlags ExclusionFlags=RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Performs an operation on objects with a given outer, with the possibility to break iteration Note that the operation must not modify the UObject hash maps so it can not create, rename or destroy UObjects.
void ForEachObjectWithPackage (const class UPackage *Outer, TFunctionRef< bool(UObject *)> Operation, bool bIncludeNestedObjects=true, EObjectFlags ExclusionFlags=RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Performs an operation on all objects found within a given package Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
TMap< UClass *, TSet< UClass * > > GetAllDerivedClasses ()
Get all base classes and their direct subclasses.
void GetDerivedClasses (const UClass *ClassToLookFor, TArray< UClass * > &Results, bool bRecursive=true)
Returns an array of classes that were derived from the specified class.
UPackage * GetObjectExternalPackageInternal (const class UObjectBase *Object)
Return the assigned external package of an object, if any.
UPackage * GetObjectExternalPackageThreadSafe (const class UObjectBase *Object)
Return the assigned external package of an object, if any.
void GetObjectsOfClass (const UClass *ClassToLookFor, TArray< UObject * > &Results, bool bIncludeDerivedClasses=true, EObjectFlags ExcludeFlags=RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Returns an array of objects of a specific class.
void GetObjectsWithOuter (const class UObjectBase *Outer, TArray< UObject * > &Results, bool bIncludeNestedObjects=true, EObjectFlags ExclusionFlags=RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Return all objects with a given outer.
void GetObjectsWithPackage (const class UPackage *Outer, TArray< UObject * > &Results, bool bIncludeNestedObjects=true, EObjectFlags ExclusionFlags=RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags=EInternalObjectFlags::None)
Returns an array of all objects found within a given package.
uint64 GetRegisteredClassesVersionNumber ()
Get a version number representing the current state of registered classes.
uint64 GetRegisteredNativeClassesVersionNumber ()
Get a version number representing the current state of registered native classes.
void HashObject (class UObjectBase *Object)
Add an object to the name hash tables.
void HashObjectExternalPackage (class UObjectBase *Object, class UPackage *Package)
Assign an external package directly to an object in the hash tables.
void LockUObjectHashTables ()
Locks UObject hash tables so that other threads can't hash or find new UObjects.
void LogHashOuterStatistics (FOutputDevice &Ar, const bool bShowHashBucketCollisionInfo)
Logs out information about the outer object hash for debug purposes.
void LogHashStatistics (FOutputDevice &Ar, const bool bShowHashBucketCollisionInfo)
Logs out information about the object hash for debug purposes.
void ShrinkUObjectHashTables ()
Shrink the UObject hash tables.
bool StaticFindAllObjectsFastInternal (TArray< UObject * > &OutFoundObjects, const UClass *ObjectClass, FName ObjectName, bool bExactClass, EObjectFlags ExcludeFlags=RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags=EInternalObjectFlags::None)
Private internal version of StaticFindAllObjectsFast that allows using 0 exclusion flags.
UObject * StaticFindFirstObjectFastInternal (const UClass *ObjectClass, FName ObjectName, bool bExactClass, EObjectFlags ExcludeFlag=RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags=EInternalObjectFlags::None)
Private internal version of StaticFindFirstObject that allows using 0 exclusion flags.
UObject * StaticFindObjectFastExplicit (const UClass *ObjectClass, FName ObjectName, const FString &ObjectPathName, bool bExactClass, EObjectFlags ExcludeFlags=RF_NoFlags)
Variation of StaticFindObjectFast that uses explicit path.
UObject * StaticFindObjectFastInternal (const UClass *Class, const UObject *InOuter, FName InName, bool ExactClass=false, EObjectFlags ExclusiveFlags=RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags=EInternalObjectFlags::None)
Private internal version of StaticFindObjectFast that allows using 0 exclusion flags.
UObject * StaticFindObjectFastInternal (FRemoteObjectId RemoteId, EObjectFlags InExclusiveFlags=RF_NoFlags, EInternalObjectFlags InExlusiveInternalFlags=EInternalObjectFlags::None)
Variation of StaticFindObjectFastInternal that uses remote id.
UE_DEPRECATED (5.1, "Support for searching for objects in ANY_PACKAGE has been deprecated. Please provide the actual Outer of an object you want to find.") 1 UObject *StaticFindObjectFastInternal(const UClass *Class
Private internal version of StaticFindObjectFast that allows using 0 exclusion flags.
UE_DEPRECATED (5.5, "LogHashMemoryOverheadStatistics that takes bool parameter has been deprecated.") inline void LogHashMemoryOverheadStatistics(FOutputDevice &Ar
Logs out information about the total object hash memory usage for debug purposes.
void UnhashObject (class UObjectBase *Object)
Remove an object to the name hash tables.
void UnhashObjectExternalPackage (class UObjectBase *Object)
Assign an external package directly to an object in the hash tables.
void UnlockUObjectHashTables ()
Unlocks UObject hash tables.
Variables
const UObject FName bool bool AnyPackage
const bool bShowIndividualStats
const UObject FName bool ExactClass
const UObject FName bool bool EObjectFlags ExclusiveFlags = RF_NoFlags
const UObject FName bool bool EObjectFlags EInternalObjectFlags ExclusiveInternalFlags = EInternalObjectFlags::None)
const UObject FName InName
const EObjectMemoryOverheadOptions InOptions
const UObject * InOuter
Enumeration Type Documentation
EObjectMemoryOverheadOptions
enum class EObjectMemoryOverheadOptions strong
Enumerator
None
ShowIndividualStats
IncludeReflectionData
Definition at line 308 of file UObjectHash.h.
Function Documentation
ClassHasInstancesAsyncLoading()
bool ClassHasInstancesAsyncLoading (const UClass * ClassToLookFor)
Returns true if any instances of the class in question are currently being async loaded.
Parameters
ClassToLookFor The class in question
Returns
True if there are any instances of the class being async loaded - includes instances based on derived classes. Otherwise, false
DECLARE_DWORD_COUNTER_STAT_EXTERN()
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("NumObjects") , STAT_Hash_NumObjects , STATGROUP_UObjectHash , 1)
DECLARE_STATS_GROUP_VERBOSE()
DECLARE_STATS_GROUP_VERBOSE (TEXT("UObject Hash") , STATGROUP_UObjectHash , STATCAT_Advanced)
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EObjectMemoryOverheadOptions) &
Logs out information about the total object hash memory usage for debug purposes.
Parameters
Ar the archive to write the log data to
InOptions Logging options
FindObjectWithOuter()
class UObjectBase * FindObjectWithOuter (const class UObjectBase * Outer, const class UClass * ClassToLookFor = nullptr, FName NameToLookFor = NAME_None)
Find an objects with a given name and or class within an outer.
Parameters
Outer Outer to search for
ClassToLookFor if NULL, ignore this parameter, otherwise require the returned object have this class
NameToLookFor if NAME_None, ignore this parameter, otherwise require the returned object have this name
References Outer.
Referenced by FComponentEditorUtils::PropagateDefaultValueChange().
ForEachObjectOfClass()
void ForEachObjectOfClass (const UClass * ClassToLookFor, TFunctionRef< void(UObject *)> Operation, bool bIncludeDerivedClasses = true, EObjectFlags ExcludeFlags = RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Performs an operation on all objects of the provided class Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
Parameters
Outer UObject class to loop over instances of
Operation Function to be called for each object
bIncludeDerivedClasses If true, the results will include objects of child classes as well.
AdditionalExcludeFlags Objects with any of these flags will be excluded from the results.
References None, and RF_ClassDefaultObject.
ForEachObjectOfClasses()
void ForEachObjectOfClasses (TArrayView< const UClass *const > ClassesToLookFor, TFunctionRef< void(UObject *)> Operation, EObjectFlags ExcludeFlags = RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Performs an operation on all objects of the provided classes Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
Parameters
Classes UObject Classes to loop over instances of
Operation Function to be called for each object
bIncludeDerivedClasses If true, the results will include objects of child classes as well.
AdditionalExcludeFlags Objects with any of these flags will be excluded from the results.
References None, and RF_ClassDefaultObject.
ForEachObjectWithOuter()
void ForEachObjectWithOuter (const class UObjectBase * Outer, TFunctionRef< void(UObject *)> Operation, bool bIncludeNestedObjects = true, EObjectFlags ExclusionFlags = RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None) inline
Performs an operation on all objects with a given outer Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
Parameters
Outer Outer to search for
Operation Function to be called for each object
bIncludeNestedObjects If true, then things whose outers directly or indirectly have Outer as an outer are included, these are the nested objects.
ExclusionFlags Specifies flags to use as a filter for which objects to return
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
Definition at line 141 of file UObjectHash.h.
References ForEachObjectWithOuter(), ForEachObjectWithOuterBreakable(), None, Object, Outer, and RF_NoFlags.
Referenced by ForEachObjectWithOuter().
ForEachObjectWithOuterBreakable()
void ForEachObjectWithOuterBreakable (const class UObjectBase * Outer, TFunctionRef< bool(UObject *)> Operation, bool bIncludeNestedObjects = true, EObjectFlags ExclusionFlags = RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Performs an operation on objects with a given outer, with the possibility to break iteration Note that the operation must not modify the UObject hash maps so it can not create, rename or destroy UObjects.
Parameters
Outer Outer to search for
Operation Function to be called for each object, returning if we want to continue iteration or not
bIncludeNestedObjects If true, then things whose outers directly or indirectly have Outer as an outer are included, these are the nested objects.
ExclusionFlags Specifies flags to use as a filter for which objects to return
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
References ForEachObjectWithOuterBreakable(), None, Outer, and RF_NoFlags.
Referenced by ForEachObjectWithOuter(), and ForEachObjectWithOuterBreakable().
ForEachObjectWithPackage()
void ForEachObjectWithPackage (const class UPackage * Outer, TFunctionRef< bool(UObject *)> Operation, bool bIncludeNestedObjects = true, EObjectFlags ExclusionFlags = RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Performs an operation on all objects found within a given package Note that the operation must not modify UObject hash maps so it can not create, rename or destroy UObjects.
Parameters
Package Package to iterate into
Operation Function to be called for each object, return false to break out of the iteration
bIncludeNestedObjects If true, then things whose outers directly or indirectly have Outer as an outer are included, these are the nested objects.
ExclusionFlags Specifies flags to use as a filter for which objects to return
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
References None, Outer, and RF_NoFlags.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages().
GetAllDerivedClasses()
TMap< UClass *, TSet< UClass * > > GetAllDerivedClasses ()
Get all base classes and their direct subclasses.
GetDerivedClasses()
void GetDerivedClasses (const UClass * ClassToLookFor, TArray< UClass * > & Results, bool bRecursive = true)
Returns an array of classes that were derived from the specified class.
Parameters
ClassToLookFor The parent class of the classes to return.
Results An output list of child classes of the specified parent class.
bRecursive If true, the results will include children of the children classes, recursively. Otherwise, only direct decedents will be included.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages().
GetObjectExternalPackageInternal()
UPackage * GetObjectExternalPackageInternal (const class UObjectBase * Object)
Return the assigned external package of an object, if any.
Parameters
Object Object to get the external package of
Returns
the assigned external package if any
Note
DO NOT USE, only for internal GC reference collecting
References Object.
GetObjectExternalPackageThreadSafe()
UPackage * GetObjectExternalPackageThreadSafe (const class UObjectBase * Object)
Return the assigned external package of an object, if any.
Parameters
Object Object to get the external package of
Returns
the assigned external package if any
References Object.
GetObjectsOfClass()
void GetObjectsOfClass (const UClass * ClassToLookFor, TArray< UObject * > & Results, bool bIncludeDerivedClasses = true, EObjectFlags ExcludeFlags = RF_ClassDefaultObject, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Returns an array of objects of a specific class.
Optionally, results can include objects of derived classes as well.
Parameters
ClassToLookFor Class of the objects to return.
Results An output list of objects of the specified class.
bIncludeDerivedClasses If true, the results will include objects of child classes as well.
AdditionalExcludeFlags Objects with any of these flags will be excluded from the results.
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
References None, and RF_ClassDefaultObject.
Referenced by FActorIteratorState::FActorIteratorState(), TComponentInterfaceIterator< T >::TComponentInterfaceIterator(), and TObjectIterator< T >::TObjectIterator().
GetObjectsWithOuter()
void GetObjectsWithOuter (const class UObjectBase * Outer, TArray< UObject * > & Results, bool bIncludeNestedObjects = true, EObjectFlags ExclusionFlags = RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Return all objects with a given outer.
Parameters
Outer Outer to search for
Results Returned results
bIncludeNestedObjects If true, then things whose outers directly or indirectly have Outer as an outer are included, these are the nested objects.
ExclusionFlags Specifies flags to use as a filter for which objects to return
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
References GetObjectsWithOuter(), None, Outer, and RF_NoFlags.
Referenced by FSoftObjectPathFixupArchive::Fixup(), and GetObjectsWithOuter().
GetObjectsWithPackage()
void GetObjectsWithPackage (const class UPackage * Outer, TArray< UObject * > & Results, bool bIncludeNestedObjects = true, EObjectFlags ExclusionFlags = RF_NoFlags, EInternalObjectFlags ExclusionInternalFlags = EInternalObjectFlags::None)
Returns an array of all objects found within a given package.
Parameters
Package Package to search into
Results Array to put the results
bIncludeNestedObjects If true, then things whose outers directly or indirectly have Outer as an outer are included, these are the nested objects.
ExclusionFlags Specifies flags to use as a filter for which objects to return
ExclusiveInternalFlags Specifies internal flags to use as a filter for which objects to return
References None, Outer, and RF_NoFlags.
GetRegisteredClassesVersionNumber()
uint64 GetRegisteredClassesVersionNumber ()
Get a version number representing the current state of registered classes.
Can be stored and then compared to invalidate external caching of classes hierarchy whenever it changes.
GetRegisteredNativeClassesVersionNumber()
uint64 GetRegisteredNativeClassesVersionNumber ()
Get a version number representing the current state of registered native classes.
Can be stored and then compared to invalidate external caching of native classes hierarchy whenever it changes.
HashObject()
void HashObject (class UObjectBase * Object)
Add an object to the name hash tables.
Parameters
Object Object to add to the hash tables
References Object.
HashObjectExternalPackage()
void HashObjectExternalPackage (class UObjectBase * Object, class UPackage * Package)
Assign an external package directly to an object in the hash tables.
Parameters
Object Object to assign a package to
Package Package to assign, null will call UnhashObjectExternalPackage
References Object, and Package.
LockUObjectHashTables()
void LockUObjectHashTables ()
Locks UObject hash tables so that other threads can't hash or find new UObjects.
Referenced by FScopedUObjectHashTablesLock::FScopedUObjectHashTablesLock().
LogHashOuterStatistics()
void LogHashOuterStatistics (FOutputDevice & Ar, const bool bShowHashBucketCollisionInfo)
Logs out information about the outer object hash for debug purposes.
Parameters
Ar the archive to write the log data to
bShowHashBucketCollisionInfo whether to log each bucket's collision count
References Ar.
LogHashStatistics()
void LogHashStatistics (FOutputDevice & Ar, const bool bShowHashBucketCollisionInfo)
Logs out information about the object hash for debug purposes.
Parameters
Ar the archive to write the log data to
bShowHashBucketCollisionInfo whether to log each bucket's collision count
References Ar.
ShrinkUObjectHashTables()
void ShrinkUObjectHashTables ()
Shrink the UObject hash tables.
StaticFindAllObjectsFastInternal()
bool StaticFindAllObjectsFastInternal (TArray< UObject * > & OutFoundObjects, const UClass * ObjectClass, FName ObjectName, bool bExactClass, EObjectFlags ExcludeFlags = RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags = EInternalObjectFlags::None)
Private internal version of StaticFindAllObjectsFast that allows using 0 exclusion flags.
Parameters
OutFoundObjects Array of objects matching the specified search parameters
ObjectClass The to be found object's class
ObjectName The to be found object's name
bExactClass Whether to require an exact match with the passed in class
ExcludeFlags Ignores objects that contain any of the specified exclusive flags
ExclusiveInternalFlags Ignores objects that contain any of the specified internal exclusive flags
Returns
Returns true if any objects were found, false otherwise
References bExactClass, ExclusiveInternalFlags, None, RF_NoFlags, and StaticFindAllObjectsFastInternal().
Referenced by StaticFindAllObjectsFastInternal().
StaticFindFirstObjectFastInternal()
UObject * StaticFindFirstObjectFastInternal (const UClass * ObjectClass, FName ObjectName, bool bExactClass, EObjectFlags ExcludeFlag = RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags = EInternalObjectFlags::None)
Private internal version of StaticFindFirstObject that allows using 0 exclusion flags.
Parameters
ObjectClass The to be found object's class
ObjectName The to be found object's name
bExactClass Whether to require an exact match with the passed in class
ExcludeFlag Ignores objects that contain any of the specified exclusive flags
ExclusiveInternalFlags Ignores objects that contain any of the specified internal exclusive flags
Returns
Returns first object with the specified name and class, null if not found
References bExactClass, ExclusiveInternalFlags, None, RF_NoFlags, and StaticFindFirstObjectFastInternal().
Referenced by StaticFindFirstObjectFastInternal().
StaticFindObjectFastExplicit()
UObject * StaticFindObjectFastExplicit (const UClass * ObjectClass, FName ObjectName, const FString & ObjectPathName, bool bExactClass, EObjectFlags ExcludeFlags = RF_NoFlags)
Variation of StaticFindObjectFast that uses explicit path.
Parameters
ObjectClass The to be found object's class
ObjectName The to be found object's name
ObjectPathName Full path name for the object to search for
ExactClass Whether to require an exact match with the passed in class
ExclusiveFlags Ignores objects that contain any of the specified exclusive flags
Returns
Returns a pointer to the found object or NULL if none could be found
References bExactClass, RF_NoFlags, and StaticFindObjectFastExplicit().
Referenced by StaticFindObjectFastExplicit().
StaticFindObjectFastInternal() [1/2]
UObject * StaticFindObjectFastInternal (const UClass * Class, const UObject * InOuter, FName InName, bool ExactClass = false, EObjectFlags ExclusiveFlags = RF_NoFlags, EInternalObjectFlags ExclusiveInternalFlags = EInternalObjectFlags::None)
Private internal version of StaticFindObjectFast that allows using 0 exclusion flags.
Parameters
Class The to be found object's class
InOuter The to be found object's outer
InName The to be found object's class
ExactClass Whether to require an exact match with the passed in class
ExclusiveFlags Ignores objects that contain any of the specified exclusive flags
ExclusiveInternalFlags Ignores objects that contain any of the specified internal exclusive flags
Returns
Returns a pointer to the found object or NULL if none could be found
References Class, ExactClass, ExclusiveFlags, ExclusiveInternalFlags, InName, InOuter, None, RF_NoFlags, and StaticFindObjectFastInternal().
Referenced by StaticFindObjectFastInternal(), and StaticFindObjectFastInternal().
StaticFindObjectFastInternal() [2/2]
UObject * StaticFindObjectFastInternal (FRemoteObjectId RemoteId, EObjectFlags InExclusiveFlags = RF_NoFlags, EInternalObjectFlags InExlusiveInternalFlags = EInternalObjectFlags::None)
Variation of StaticFindObjectFastInternal that uses remote id.
Parameters
RemoteId The to be found object's remote id
InExclusiveFlags Ignores objects that contain any of the specified exclusive flags
InExlusiveInternalFlags Ignores objects that contain any of the specified internal exclusive flags
Returns
Returns a pointer to the found object or NULL if none could be found
References None, RF_NoFlags, and StaticFindObjectFastInternal().
UE_DEPRECATED() [1/2]
UE_DEPRECATED (5. 1, "Support for searching for objects in ANY_PACKAGE has been deprecated. Please provide the actual Outer of an object you want to find.") const
Private internal version of StaticFindObjectFast that allows using 0 exclusion flags.
Parameters
Class The to be found object's class
InOuter The to be found object's outer
InName The to be found object's class
ExactClass Whether to require an exact match with the passed in class
AnyPackage Whether to look in any package
ExclusiveFlags Ignores objects that contain any of the specified exclusive flags
ExclusiveInternalFlags Ignores objects that contain any of the specified internal exclusive flags
Returns
Returns a pointer to the found object or NULL if none could be found
UE_DEPRECATED() [2/2]
UE_DEPRECATED (5. 5, "LogHashMemoryOverheadStatistics that takes bool parameter has been deprecated.") &
Logs out information about the total object hash memory usage for debug purposes.
Parameters
Ar the archive to write the log data to
bShowIndividualStats whether to log each hash/map memory usage separately
References UE_DEPRECATED.
UnhashObject()
void UnhashObject (class UObjectBase * Object)
Remove an object to the name hash tables.
Parameters
Object Object to remove from the hash tables
References Object.
UnhashObjectExternalPackage()
void UnhashObjectExternalPackage (class UObjectBase * Object)
Assign an external package directly to an object in the hash tables.
Parameters
Object Object to unassign a package from
References Object.
UnlockUObjectHashTables()
void UnlockUObjectHashTables ()
Unlocks UObject hash tables.
Referenced by FScopedUObjectHashTablesLock::~FScopedUObjectHashTablesLock().
Variable Documentation
AnyPackage
const UObject FName bool bool AnyPackage
Definition at line 46 of file UObjectHash.h.
bShowIndividualStats
const bool bShowIndividualStats
Initial value:
{
    LogHashMemoryOverheadStatistics(Ar, bShowIndividualStats ? EObjectMemoryOverheadOptions::ShowIndividualStats : EObjectMemoryOverheadOptions::None)
Definition at line 331 of file UObjectHash.h.
ExactClass
const UObject FName bool ExactClass
Definition at line 46 of file UObjectHash.h.
ExclusiveFlags
const UObject FName bool bool EObjectFlags ExclusiveFlags = RF_NoFlags
Definition at line 46 of file UObjectHash.h.
ExclusiveInternalFlags
const UObject FName bool bool EObjectFlags EInternalObjectFlags ExclusiveInternalFlags = EInternalObjectFlags::None)
Definition at line 46 of file UObjectHash.h.
InName
const UObject FName InName
Definition at line 46 of file UObjectHash.h.
InOptions
const EObjectMemoryOverheadOptions InOptions
Definition at line 322 of file UObjectHash.h.
Referenced by FAppleProResEncoder::FAppleProResEncoder(), FObjectInitializer::FObjectInitializer(), FixedTagPrivate::FStoreBuilder::FStoreBuilder(), FixedTagPrivate::FStoreBuilder::FStoreBuilder(), IPersonaViewport::AddNotification(), SFindInBlueprints::CacheAllBlueprints(), UE::UnrealEd::CreateCameraSubmenu(), DECLARE_DYNAMIC_DELEGATE_RetVal_TwoParams(), ENUM_CLASS_FLAGS(), SFindInBlueprints::OnCacheAllBlueprints(), UE::UnrealEd::PopulateCameraMenu(), FRigVMEditorModule::ShowWorkflowOptionsDialog(), UClass::TryFindTypeSlow(), UClass::TryFindTypeSlow(), UClass::TryFindTypeSlowSafe(), UClass::TryFindTypeSlowSafe(), USTRUCT(), and USTRUCT().
InOuter
const UObject* InOuter
Definition at line 46 of file UObjectHash.h.