Unreal Engine 5.6 C++ API: UE::MediaIOCore::FDeinterlacer Class Reference
UE::MediaIOCore::FDeinterlacer Class Reference
Handles deinterlacing a video signal.
#include "MediaIOCoreDeinterlacer.h"
Public Member Functions
FDeinterlacer ()=default
FDeinterlacer (FOnAcquireSample_AnyThread InOnAcquireSample, EMediaIOInterlaceFieldOrder InInterlaceFieldOrder)
virtual ~FDeinterlacer ()
DECLARE_DELEGATE_RetVal (TSharedPtr< FMediaIOCoreTextureSampleBase >, FOnAcquireSample_AnyThread)
virtual TArray< TSharedRef< FMediaIOCoreTextureSampleBase > > Deinterlace (const FVideoFrame &InVideoFrame) const
Default implementation which applies no deinterlacing.
Protected Attributes
FOnAcquireSample_AnyThread AcquireSampleDelegate
Delegate called to acquire samples.
EMediaIOInterlaceFieldOrder InterlaceFieldOrder = EMediaIOInterlaceFieldOrder::TopFieldFirst
What order should fields be read in.
Detailed Description
Handles deinterlacing a video signal.
Definition at line 55 of file MediaIOCoreDeinterlacer.h.
Constructor & Destructor Documentation
FDeinterlacer() [1/2]
UE::MediaIOCore::FDeinterlacer::FDeinterlacer () default
Referenced by UE::MediaIOCore::FBlendDeinterlacer::FBlendDeinterlacer(), UE::MediaIOCore::FBobDeinterlacer::FBobDeinterlacer(), and UE::MediaIOCore::FDiscardDeinterlacer::FDiscardDeinterlacer().
FDeinterlacer() [2/2]
UE::MediaIOCore::FDeinterlacer::FDeinterlacer (FOnAcquireSample_AnyThread InOnAcquireSample, EMediaIOInterlaceFieldOrder InInterlaceFieldOrder) inline
Definition at line 61 of file MediaIOCoreDeinterlacer.h.
References AcquireSampleDelegate, InterlaceFieldOrder, and MoveTemp().
~FDeinterlacer()
virtual UE::MediaIOCore::FDeinterlacer::~FDeinterlacer () inline virtual
Definition at line 67 of file MediaIOCoreDeinterlacer.h.
Member Function Documentation
DECLARE_DELEGATE_RetVal()
UE::MediaIOCore::FDeinterlacer::DECLARE_DELEGATE_RetVal (TSharedPtr< FMediaIOCoreTextureSampleBase > , FOnAcquireSample_AnyThread)
Deinterlace()
virtual TArray< TSharedRef< FMediaIOCoreTextureSampleBase > > UE::MediaIOCore::FDeinterlacer::Deinterlace (const FVideoFrame & InVideoFrame) const virtual
Default implementation which applies no deinterlacing.
Parameters
InVideoFrame The video buffer and its metadata.
Returns
One or more sample depending on the deinterlacing method.
Reimplemented in UE::MediaIOCore::FBlendDeinterlacer, UE::MediaIOCore::FBobDeinterlacer, and UE::MediaIOCore::FDiscardDeinterlacer.
Field Documentation
AcquireSampleDelegate
FOnAcquireSample_AnyThread UE::MediaIOCore::FDeinterlacer::AcquireSampleDelegate protected
Delegate called to acquire samples.
Definition at line 77 of file MediaIOCoreDeinterlacer.h.
Referenced by FDeinterlacer().
InterlaceFieldOrder
EMediaIOInterlaceFieldOrder UE::MediaIOCore::FDeinterlacer::InterlaceFieldOrder = EMediaIOInterlaceFieldOrder::TopFieldFirst protected
What order should fields be read in.
Definition at line 79 of file MediaIOCoreDeinterlacer.h.
Referenced by FDeinterlacer().
The documentation for this class was generated from the following file:
MediaIOCoreDeinterlacer.h