Unreal Engine 5.6 C++ API: FCompoundChange Class Reference
FCompoundChange Class Reference
FCompoundChange applies a sequence of FSwapChanges.
#include "Change.h"
Public Member Functions
FCompoundChange (FCompoundChangeInput &&InitInput)
Constructor.
virtual TUniquePtr< FChange > Execute (UObject *Object) override
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
virtual void PrintToLog (class FFeedbackContext &FeedbackContext, const int32 IndentLevel=0) override
Prints this change to the log, including sub-changes if there are any.
virtual FString ToString () const override
Describes this change (for debugging)
Public Member Functions inherited from FSwapChange
virtual void Apply (UObject *Object) final
Makes the change to the object.
virtual EChangeStyle GetChangeType () final
What style of change is this.
virtual void Revert (UObject *Object) final
Reverts change to the object.
Public Member Functions inherited from FChange
virtual ~FChange ()
Virtual destructor.
virtual void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
virtual bool HasExpired (UObject *Object) const
Private Member Functions
FCompoundChange (const FCompoundChange &)=delete
FCompoundChange & operator= (const FCompoundChange &)=delete
Private Attributes
FCompoundChangeInput Input
The data we need to make this change.
Additional Inherited Members
Public Types inherited from FChange
enum class EChangeStyle { InPlaceSwap , CommandPattern }
Protected Member Functions inherited from FChange
FChange ()
Protected default constructor.
Detailed Description
FCompoundChange applies a sequence of FSwapChanges.
The changes are executed in reverse order (this is like a mini undo stack)
Definition at line 168 of file Change.h.
Constructor & Destructor Documentation
FCompoundChange() [1/2]
FCompoundChange::FCompoundChange (FCompoundChangeInput && InitInput) inline explicit
Constructor.
Definition at line 174 of file Change.h.
References Input, and MoveTemp().
Referenced by FCompoundChange(), and operator=().
FCompoundChange() [2/2]
FCompoundChange::FCompoundChange (const FCompoundChange &) private delete
References FCompoundChange().
Member Function Documentation
Execute()
virtual TUniquePtr< FChange > FCompoundChange::Execute (UObject * Object) override virtual
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
Implements FChange.
References Object.
operator=()
FCompoundChange & FCompoundChange::operator= (const FCompoundChange &) private delete
References FCompoundChange().
PrintToLog()
virtual void FCompoundChange::PrintToLog (class FFeedbackContext & FeedbackContext, const int32 IndentLevel = 0) override virtual
Prints this change to the log, including sub-changes if there are any.
For compound changes, there might be multiple lines. You should not need to override this function.
Reimplemented from FChange.
ToString()
virtual FString FCompoundChange::ToString () const override virtual
Describes this change (for debugging)
Implements FChange.
Field Documentation
Input
FCompoundChangeInput FCompoundChange::Input private
The data we need to make this change.
Definition at line 188 of file Change.h.
Referenced by FCompoundChange().
The documentation for this class was generated from the following file:
Change.h