Unreal Engine 5.6 C++ API: Crc.h File Reference
Crc.h File Reference
#include "CoreTypes.h"
#include "HAL/PlatformString.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Misc/Char.h"
#include "Templates/UnrealTypeTraits.h"
#include "Traits/IsCharType.h"
Data Structures
struct FCrc
CRC hash generation for different types of input data.
struct TStringPointerMapKeyFuncs_DEPRECATED< InKeyType, InValueType, bInAllowDuplicateKeys >
An implementation of KeyFuncs for maps which hashes string pointers by FCrc::Strihash_DEPRECATED.
struct TStringPointerSetKeyFuncs_DEPRECATED< InKeyType, bInAllowDuplicateKeys >
An implementation of KeyFuncs for sets which hashes string pointers by FCrc::Strihash_DEPRECATED.
Functions
FORCEINLINE const TCHAR * ToCStr (const TCHAR *Ptr)
Gets a non-owning TCHAR pointer from a string type.
Function Documentation
ToCStr()
FORCEINLINE const TCHAR * ToCStr (const TCHAR * Ptr)
Gets a non-owning TCHAR pointer from a string type.
Can be used generically to get a const TCHAR*, when it is not known if the argument is a TCHAR* or an FString:
template <typename T> void LogValue(const T& Val) { Logf(TEXT("Value: %s"), ToCStr(LexToString(Val))); }
Definition at line 302 of file Crc.h.
References FORCEINLINE.
Referenced by FPlatformCompressionUtilities::AppendHash(), TStringPointerMapKeyFuncs_DEPRECATED< InKeyType, InValueType, bInAllowDuplicateKeys >::GetKeyHash(), and TStringPointerSetKeyFuncs_DEPRECATED< InKeyType, bInAllowDuplicateKeys >::GetKeyHash().