Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolCastableTypeTable Struct Reference
UE::SequenceNavigator::FNavigationToolCastableTypeTable Struct Reference
#include "NavigationToolCastableTypeTable.h"
Data Structures
struct FNavigationToolCastableTypeTableGenerator
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Public Member Functions
FNavigationToolCastableTypeTable (const FNavigationToolCastableTypeTable &)=delete
FNavigationToolCastableTypeTable (FNavigationToolCastableTypeTable &&)=delete
FNavigationToolCastableTypeTable (uint8 *InTypeMaskStorage)
const void * Cast (const ICastable *BasePtr, uint32 ToType) const
Use this type table to cast the specified base ptr to another type.
const void * Cast (const IDynamicExtension *BasePtr, uint32 ToType) const
Use this type table to cast the specified base ptr to another type.
uint32 GetTypeID () const
Retrieve the type ID for this type table.
FName GetTypeName () const
Retrieve the C++ type name that this type table relates to.
void operator= (const FNavigationToolCastableTypeTable &)=delete
void operator= (FNavigationToolCastableTypeTable &&)=delete
Static Public Member Functions
static SEQUENCERCORE_API const FNavigationToolCastableTypeTable * FindTypeByName (FName InName)
Attempt to locate a type table by its C++ name.
template<typename T>
static FNavigationToolCastableTypeTable * MakeTypeTable (const ICastable *Unused, uint32 TypeID, FName InName)
template<typename T>
static FNavigationToolCastableTypeTable * MakeTypeTable (const IDynamicExtension *Unused, uint32 TypeID, FName InName)
template<typename T>
static FNavigationToolCastableTypeTable * MakeTypeTable (const void *Unused, uint32 TypeID, FName InName)
Make a new type table for the templated type, ID and typename.
Private Member Functions
const void * CastImpl (const void *BasePtr, uint32 ToType) const
Cast implementation function.
Private Attributes
uint32 NumStaticTypes
The number of static types implemented within this type table.
int16 * StaticTypeOffsets
Ptr to the static type offsets allocated at the end of this struct.
uint32 ThisTypeID
Unique static type ID for this type.
FName ThisTypeName
The name of the C++ type that this table relates to.
MovieScene::TFixedSparseBitSet< uint32, MovieScene::TFixedSparseBitSetBucketStorage< uint8 > > TypeMask
Fixed sparse bitset of types that this table contains.
Detailed Description
Definition at line 25 of file NavigationToolCastableTypeTable.h.
Constructor & Destructor Documentation
FNavigationToolCastableTypeTable() [1/3]
UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTable (uint8 * InTypeMaskStorage) explicit
Referenced by FNavigationToolCastableTypeTable(), FNavigationToolCastableTypeTable(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ByteSize(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Commit(), FindTypeByName(), MakeTypeTable(), MakeTypeTable(), MakeTypeTable(), operator=(), and operator=().
FNavigationToolCastableTypeTable() [2/3]
UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTable (const FNavigationToolCastableTypeTable &) delete
References FNavigationToolCastableTypeTable().
FNavigationToolCastableTypeTable() [3/3]
UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTable (FNavigationToolCastableTypeTable &&) delete
References FNavigationToolCastableTypeTable().
Member Function Documentation
Cast() [1/2]
const void * UE::SequenceNavigator::FNavigationToolCastableTypeTable::Cast (const ICastable * BasePtr, uint32 ToType) const inline
Use this type table to cast the specified base ptr to another type.
Note
BasePtr must be an instance of the type specified by this type table, or the result is undefined.
Returns
BasePtr casted to the type ID specified by ToType, or nullptr if the cast failed
Definition at line 70 of file NavigationToolCastableTypeTable.h.
References CastImpl().
Cast() [2/2]
const void * UE::SequenceNavigator::FNavigationToolCastableTypeTable::Cast (const IDynamicExtension * BasePtr, uint32 ToType) const inline
Use this type table to cast the specified base ptr to another type.
Note
BasePtr must be an instance of the type specified by this type table, or the result is undefined.
Returns
BasePtr casted to the type ID specified by ToType, or nullptr if the cast failed
Definition at line 82 of file NavigationToolCastableTypeTable.h.
References CastImpl().
CastImpl()
const void * UE::SequenceNavigator::FNavigationToolCastableTypeTable::CastImpl (const void * BasePtr, uint32 ToType) const inline private
Cast implementation function.
Definition at line 110 of file NavigationToolCastableTypeTable.h.
References INDEX_NONE, StaticTypeOffsets, and TypeMask.
Referenced by Cast(), and Cast().
FindTypeByName()
SEQUENCERCORE_API const FNavigationToolCastableTypeTable * UE::SequenceNavigator::FNavigationToolCastableTypeTable::FindTypeByName (FName InName) static
Attempt to locate a type table by its C++ name.
References FNavigationToolCastableTypeTable(), and InName.
GetTypeID()
uint32 UE::SequenceNavigator::FNavigationToolCastableTypeTable::GetTypeID () const inline
Retrieve the type ID for this type table.
Warning: This type ID is not deterministic or stable across different processes and should not be saved persistently
Definition at line 100 of file NavigationToolCastableTypeTable.h.
References ThisTypeID.
GetTypeName()
FName UE::SequenceNavigator::FNavigationToolCastableTypeTable::GetTypeName () const inline
Retrieve the C++ type name that this type table relates to.
Definition at line 90 of file NavigationToolCastableTypeTable.h.
References ThisTypeName.
MakeTypeTable() [1/3]
template<typename T> FNavigationToolCastableTypeTable * UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable (const ICastable * Unused, uint32 TypeID, FName InName) inline static
Definition at line 44 of file NavigationToolCastableTypeTable.h.
References FNavigationToolCastableTypeTable(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Commit(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Generate(), InName, and Unused.
MakeTypeTable() [2/3]
template<typename T> FNavigationToolCastableTypeTable * UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable (const IDynamicExtension * Unused, uint32 TypeID, FName InName) inline static
Definition at line 51 of file NavigationToolCastableTypeTable.h.
References FNavigationToolCastableTypeTable(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Commit(), UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Generate(), InName, and Unused.
MakeTypeTable() [3/3]
template<typename T> FNavigationToolCastableTypeTable * UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable (const void * Unused, uint32 TypeID, FName InName) inline static
Make a new type table for the templated type, ID and typename.
The new table is allocated using malloc and is intentionally leaked
Definition at line 39 of file NavigationToolCastableTypeTable.h.
References FNavigationToolCastableTypeTable(), InName, and Unused.
operator=() [1/2]
void UE::SequenceNavigator::FNavigationToolCastableTypeTable::operator= (const FNavigationToolCastableTypeTable &) delete
References FNavigationToolCastableTypeTable().
operator=() [2/2]
void UE::SequenceNavigator::FNavigationToolCastableTypeTable::operator= (FNavigationToolCastableTypeTable &&) delete
References FNavigationToolCastableTypeTable().
Field Documentation
NumStaticTypes
uint32 UE::SequenceNavigator::FNavigationToolCastableTypeTable::NumStaticTypes private
The number of static types implemented within this type table.
Definition at line 242 of file NavigationToolCastableTypeTable.h.
StaticTypeOffsets
int16* UE::SequenceNavigator::FNavigationToolCastableTypeTable::StaticTypeOffsets private
Ptr to the static type offsets allocated at the end of this struct.
Size = NumStaticTypes
Definition at line 238 of file NavigationToolCastableTypeTable.h.
Referenced by CastImpl().
ThisTypeID
uint32 UE::SequenceNavigator::FNavigationToolCastableTypeTable::ThisTypeID private
Unique static type ID for this type.
Definition at line 244 of file NavigationToolCastableTypeTable.h.
Referenced by GetTypeID().
ThisTypeName
FName UE::SequenceNavigator::FNavigationToolCastableTypeTable::ThisTypeName private
The name of the C++ type that this table relates to.
Definition at line 246 of file NavigationToolCastableTypeTable.h.
Referenced by GetTypeName().
TypeMask
MovieScene::TFixedSparseBitSet<uint32, MovieScene::TFixedSparseBitSetBucketStorage<uint8> > UE::SequenceNavigator::FNavigationToolCastableTypeTable::TypeMask private
Fixed sparse bitset of types that this table contains.
Storage is allocated at the end of this struct.
Definition at line 240 of file NavigationToolCastableTypeTable.h.
Referenced by CastImpl().
The documentation for this struct was generated from the following file:
NavigationToolCastableTypeTable.h