Unreal Engine 5.6 C++ API: FMovieSceneInterrogationData Struct Reference
FMovieSceneInterrogationData Struct Reference
Data structure that is passed to all tracks and templates when interrogating them for data.
#include "MovieSceneTemplateInterrogation.h"
Public Member Functions
template<typename T>
void Add (T &&InData, FMovieSceneInterrogationKey Key)
Add arbitrary data to the container under the specified key.
MOVIESCENE_API void Finalize (const FMovieSceneContext &Context, UObject *BindingOverride)
MOVIESCENE_API FMovieSceneBlendingAccumulator & GetAccumulator ()
TArray< TInlineValue< IMovieSceneInterrogationToken > >::TConstIterator Iterate () const
Iterate all data stored in this container.
template<typename T>
TMovieSceneInterrogationIterator< T > Iterate (FMovieSceneInterrogationKey Key) const
Iterate any data in this container that matches the specified key Care should be taken by clients to ensure that data types that are added with specific keys are always accessed as the correct types.
Private Attributes
TSharedPtr< FMovieSceneBlendingAccumulator > Accumulator
Optional accumulator that is allocated when required.
TArray< TInlineValue< IMovieSceneInterrogationToken > > TokenData
Friends
template<typename T>
struct TMovieSceneInterrogationIterator
Detailed Description
Data structure that is passed to all tracks and templates when interrogating them for data.
Used by FMovieSceneEvaluationTrack::Interrogate
Definition at line 69 of file MovieSceneTemplateInterrogation.h.
Member Function Documentation
Add()
template<typename T> void FMovieSceneInterrogationData::Add (T && InData, FMovieSceneInterrogationKey Key) inline
Add arbitrary data to the container under the specified key.
Care should be taken by clients to ensure that data types that are added with specific keys are always accessed as the correct types
Definition at line 76 of file MovieSceneTemplateInterrogation.h.
References Forward(), Key, and TokenData.
Referenced by TPropertyActuator< PropertyType >::Actuate(), TPropertyActuator< PropertyType >::Actuate(), TPropertyActuator< PropertyType >::Actuate(), TPropertyActuator< PropertyType >::Actuate(), TPropertyActuator< PropertyType >::Actuate(), and TPropertyActuator< PropertyType >::Actuate().
Finalize()
MOVIESCENE_API void FMovieSceneInterrogationData::Finalize (const FMovieSceneContext & Context, UObject * BindingOverride)
GetAccumulator()
MOVIESCENE_API FMovieSceneBlendingAccumulator & FMovieSceneInterrogationData::GetAccumulator ()
Iterate() [1/2]
TArray< TInlineValue< IMovieSceneInterrogationToken > >::TConstIterator FMovieSceneInterrogationData::Iterate () const inline
Iterate all data stored in this container.
Definition at line 83 of file MovieSceneTemplateInterrogation.h.
References TokenData.
Iterate() [2/2]
template<typename T> TMovieSceneInterrogationIterator< T > FMovieSceneInterrogationData::Iterate (FMovieSceneInterrogationKey Key) const inline
Iterate any data in this container that matches the specified key Care should be taken by clients to ensure that data types that are added with specific keys are always accessed as the correct types.
Definition at line 93 of file MovieSceneTemplateInterrogation.h.
References Key, and TMovieSceneInterrogationIterator.
Friends And Related Symbol Documentation
TMovieSceneInterrogationIterator
template<typename T> friend struct TMovieSceneInterrogationIterator friend
Definition at line 104 of file MovieSceneTemplateInterrogation.h.
References TMovieSceneInterrogationIterator.
Referenced by Iterate(), and TMovieSceneInterrogationIterator.
Field Documentation
Accumulator
TSharedPtr<FMovieSceneBlendingAccumulator> FMovieSceneInterrogationData::Accumulator private
Optional accumulator that is allocated when required.
Definition at line 108 of file MovieSceneTemplateInterrogation.h.
TokenData
TArray<TInlineValue<IMovieSceneInterrogationToken> > FMovieSceneInterrogationData::TokenData private
Definition at line 105 of file MovieSceneTemplateInterrogation.h.
Referenced by Add(), and Iterate().
The documentation for this struct was generated from the following file:
MovieSceneTemplateInterrogation.h