Unreal Engine 5.6 C++ API: UE::Geometry::TCircle3< RealType > Struct Template Reference
UE::Geometry::TCircle3< RealType > Struct Template Reference
#include "CircleTypes.h"
Public Member Functions
TCircle3 ()
TCircle3 (const RealType &RadiusIn)
TCircle3 (const TFrame3< RealType > &FrameIn, const RealType &RadiusIn)
TCircle3 (const TVector< RealType > &CenterIn, const RealType &RadiusIn)
TVector< RealType > ClosestPoint (const TVector< RealType > &QueryPoint) const
RealType Distance (const TVector< RealType > &Point) const
RealType DistanceSquared (const TVector< RealType > &Point) const
RealType GetArea () const
TOrientedBox3< RealType > GetBoundingBox () const
const TVector< RealType > & GetCenter () const
RealType GetCircumference () const
RealType GetCurvature () const
RealType GetDiameter () const
TVector< RealType > GetNormal () const
TVector< RealType > GetPointFromAngleD (RealType AngleDeg) const
TVector< RealType > GetPointFromAngleR (RealType AngleRad) const
TVector< RealType > GetPointFromUnitParameter (RealType UnitParam) const
RealType GetSignedCurvature () const
void SetArea (RealType NewArea)
void SetCircumference (RealType NewCircumference)
void SetDiameter (RealType NewDiameter)
Data Fields
bool bIsReversed = false
TFrame3< RealType > Frame
RealType Radius = (RealType)1
Detailed Description
template<typename RealType>
struct UE::Geometry::TCircle3< RealType >
Definition at line 147 of file CircleTypes.h.
Constructor & Destructor Documentation
TCircle3() [1/4]
template<typename RealType> UE::Geometry::TCircle3< RealType >::TCircle3 () inline
Definition at line 153 of file CircleTypes.h.
TCircle3() [2/4]
template<typename RealType> UE::Geometry::TCircle3< RealType >::TCircle3 (const RealType & RadiusIn) inline explicit
Definition at line 155 of file CircleTypes.h.
TCircle3() [3/4]
template<typename RealType> UE::Geometry::TCircle3< RealType >::TCircle3 (const TVector< RealType > & CenterIn, const RealType & RadiusIn) inline
Definition at line 160 of file CircleTypes.h.
TCircle3() [4/4]
template<typename RealType> UE::Geometry::TCircle3< RealType >::TCircle3 (const TFrame3< RealType > & FrameIn, const RealType & RadiusIn) inline
Definition at line 166 of file CircleTypes.h.
Member Function Documentation
ClosestPoint()
template<typename RealType> TVector< RealType > UE::Geometry::TCircle3< RealType >::ClosestPoint (const TVector< RealType > & QueryPoint) const inline
Definition at line 244 of file CircleTypes.h.
Referenced by UE::Geometry::TCircle3< float >::DistanceSquared().
Distance()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::Distance (const TVector< RealType > & Point) const inline
Definition at line 268 of file CircleTypes.h.
DistanceSquared()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::DistanceSquared (const TVector< RealType > & Point) const inline
Definition at line 263 of file CircleTypes.h.
Referenced by UE::Geometry::TCircle3< float >::Distance().
GetArea()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::GetArea () const inline
Definition at line 203 of file CircleTypes.h.
GetBoundingBox()
template<typename RealType> TOrientedBox3< RealType > UE::Geometry::TCircle3< RealType >::GetBoundingBox () const inline
Definition at line 273 of file CircleTypes.h.
GetCenter()
template<typename RealType> const TVector< RealType > & UE::Geometry::TCircle3< RealType >::GetCenter () const inline
Definition at line 173 of file CircleTypes.h.
GetCircumference()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::GetCircumference () const inline
Definition at line 184 of file CircleTypes.h.
GetCurvature()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::GetCurvature () const inline
Definition at line 213 of file CircleTypes.h.
GetDiameter()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::GetDiameter () const inline
Definition at line 194 of file CircleTypes.h.
GetNormal()
template<typename RealType> TVector< RealType > UE::Geometry::TCircle3< RealType >::GetNormal () const inline
Definition at line 178 of file CircleTypes.h.
GetPointFromAngleD()
template<typename RealType> TVector< RealType > UE::Geometry::TCircle3< RealType >::GetPointFromAngleD (RealType AngleDeg) const inline
Definition at line 224 of file CircleTypes.h.
GetPointFromAngleR()
template<typename RealType> TVector< RealType > UE::Geometry::TCircle3< RealType >::GetPointFromAngleR (RealType AngleRad) const inline
Definition at line 229 of file CircleTypes.h.
Referenced by UE::Geometry::TCircle3< float >::GetPointFromAngleD(), and UE::Geometry::TCircle3< float >::GetPointFromUnitParameter().
GetPointFromUnitParameter()
template<typename RealType> TVector< RealType > UE::Geometry::TCircle3< RealType >::GetPointFromUnitParameter (RealType UnitParam) const inline
Definition at line 235 of file CircleTypes.h.
GetSignedCurvature()
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::GetSignedCurvature () const inline
Definition at line 218 of file CircleTypes.h.
SetArea()
template<typename RealType> void UE::Geometry::TCircle3< RealType >::SetArea (RealType NewArea) inline
Definition at line 207 of file CircleTypes.h.
SetCircumference()
template<typename RealType> void UE::Geometry::TCircle3< RealType >::SetCircumference (RealType NewCircumference) inline
Definition at line 188 of file CircleTypes.h.
SetDiameter()
template<typename RealType> void UE::Geometry::TCircle3< RealType >::SetDiameter (RealType NewDiameter) inline
Definition at line 198 of file CircleTypes.h.
Field Documentation
bIsReversed
template<typename RealType> bool UE::Geometry::TCircle3< RealType >::bIsReversed = false
Definition at line 151 of file CircleTypes.h.
Frame
template<typename RealType> TFrame3<RealType> UE::Geometry::TCircle3< RealType >::Frame
Definition at line 149 of file CircleTypes.h.
Radius
template<typename RealType> RealType UE::Geometry::TCircle3< RealType >::Radius = (RealType)1
Definition at line 150 of file CircleTypes.h.
The documentation for this struct was generated from the following file:
CircleTypes.h