Unreal Engine 5.6 C++ API: FSlateDynamicImageBrush Struct Reference
FSlateDynamicImageBrush Struct Reference
Ignores the Margin.
#include "SlateDynamicImageBrush.h"
Public Member Functions
FORCENOINLINE FSlateDynamicImageBrush (class UTexture2D *InTexture, const UE::Slate::FDeprecateVector2DParameter &InImageSize, const FName InTextureName, const FLinearColor &InTint=FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling=ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType=ESlateBrushImageType::FullColor)
FORCENOINLINE FSlateDynamicImageBrush (class UTexture2DDynamic *InTexture, const UE::Slate::FDeprecateVector2DParameter &InImageSize, const FName InTextureName, const FLinearColor &InTint=FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling=ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType=ESlateBrushImageType::FullColor)
FORCENOINLINE FSlateDynamicImageBrush (const FName InTextureName, const UE::Slate::FDeprecateVector2DParameter &InImageSize, const FLinearColor &InTint=FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling=ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType=ESlateBrushImageType::FullColor)
virtual ~FSlateDynamicImageBrush ()
Destructor.
void ReleaseResource ()
Releases the resource when it is safe to do so.
Public Member Functions inherited from TSharedFromThis< FSlateDynamicImageBrush >
TSharedRef< FSlateDynamicImageBrush, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSlateDynamicImageBrush, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< FSlateDynamicImageBrush > CreateWithImageData (const FName InTextureName, const UE::Slate::FDeprecateVector2DParameter &InImageSize, const TArray< uint8 > &InImageData, const FLinearColor &InTint=FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling=ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType=ESlateBrushImageType::FullColor)
Private Member Functions
void InitFromTextureObject (FName InTextureName)
void ReleaseResourceInternal ()
Private Attributes
bool bIsInitalized: 1
If the resource has been initialized.
bool bRemoveResourceFromRootSet: 1
Tracks if Resource was in root set to avoid unnecessary removing it from there.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FSlateDynamicImageBrush >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FSlateDynamicImageBrush >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Ignores the Margin.
Just renders the image. Can tile the image instead of stretching.
Definition at line 13 of file SlateDynamicImageBrush.h.
Constructor & Destructor Documentation
FSlateDynamicImageBrush() [1/3]
FORCENOINLINE FSlateDynamicImageBrush::FSlateDynamicImageBrush (class UTexture2D * InTexture, const UE::Slate::FDeprecateVector2DParameter & InImageSize, const FName InTextureName, const FLinearColor & InTint = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling = ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType = ESlateBrushImageType::FullColor) inline
Parameters
InTexture The UTexture2D being used for this brush.
InImageSize How large should the image be (not necessarily the image size on disk)
InTint The tint of the image
InTiling How do we tile if at all?
InImageType The type of image this this is
Definition at line 23 of file SlateDynamicImageBrush.h.
References bIsInitalized, bRemoveResourceFromRootSet, FORCENOINLINE, InitFromTextureObject(), and TEXT.
FSlateDynamicImageBrush() [2/3]
FORCENOINLINE FSlateDynamicImageBrush::FSlateDynamicImageBrush (class UTexture2DDynamic * InTexture, const UE::Slate::FDeprecateVector2DParameter & InImageSize, const FName InTextureName, const FLinearColor & InTint = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling = ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType = ESlateBrushImageType::FullColor) inline
Parameters
InTexture The UTexture2DDynamic being used for this brush.
InImageSize How large should the image be (not necessarily the image size on disk)
InTint The tint of the image
InTiling How do we tile if at all?
InImageType The type of image this this is
Definition at line 46 of file SlateDynamicImageBrush.h.
References bIsInitalized, bRemoveResourceFromRootSet, FORCENOINLINE, InitFromTextureObject(), and TEXT.
FSlateDynamicImageBrush() [3/3]
FORCENOINLINE FSlateDynamicImageBrush::FSlateDynamicImageBrush (const FName InTextureName, const UE::Slate::FDeprecateVector2DParameter & InImageSize, const FLinearColor & InTint = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling = ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType = ESlateBrushImageType::FullColor) inline
Parameters
InTextureName The name of the texture to load.
InImageSize How large should the image be (not necessarily the image size on disk)
InTint The tint of the image.
InTiling How do we tile if at all?
InImageType The type of image this this is
Definition at line 69 of file SlateDynamicImageBrush.h.
References bIsInitalized, bRemoveResourceFromRootSet, and FORCENOINLINE.
~FSlateDynamicImageBrush()
virtual FSlateDynamicImageBrush::~FSlateDynamicImageBrush () virtual
Destructor.
Member Function Documentation
CreateWithImageData()
TSharedPtr< FSlateDynamicImageBrush > FSlateDynamicImageBrush::CreateWithImageData (const FName InTextureName, const UE::Slate::FDeprecateVector2DParameter & InImageSize, const TArray< uint8 > & InImageData, const FLinearColor & InTint = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f), ESlateBrushTileType::Type InTiling = ESlateBrushTileType::NoTile, ESlateBrushImageType::Type InImageType = ESlateBrushImageType::FullColor) static
Parameters
InTextureName The name to use when registering the image data as a texture.
InImageSize How large should the image be (not necessarily the image size on disk)
InImageData The raw image data formatted as BGRA
InTint The tint of the image.
InTiling How do we tile if at all?
InImageType The type of image this this is
InitFromTextureObject()
void FSlateDynamicImageBrush::InitFromTextureObject (FName InTextureName) inline private
Definition at line 109 of file SlateDynamicImageBrush.h.
References bRemoveResourceFromRootSet, ensureMsgf, Object, and TEXT.
Referenced by FSlateDynamicImageBrush(), and FSlateDynamicImageBrush().
ReleaseResource()
void FSlateDynamicImageBrush::ReleaseResource ()
Releases the resource when it is safe to do so.
ReleaseResourceInternal()
void FSlateDynamicImageBrush::ReleaseResourceInternal () private
Field Documentation
bIsInitalized
bool FSlateDynamicImageBrush::bIsInitalized private
If the resource has been initialized.
Definition at line 135 of file SlateDynamicImageBrush.h.
Referenced by FSlateDynamicImageBrush(), FSlateDynamicImageBrush(), and FSlateDynamicImageBrush().
bRemoveResourceFromRootSet
bool FSlateDynamicImageBrush::bRemoveResourceFromRootSet private
Tracks if Resource was in root set to avoid unnecessary removing it from there.
Definition at line 132 of file SlateDynamicImageBrush.h.
Referenced by FSlateDynamicImageBrush(), FSlateDynamicImageBrush(), FSlateDynamicImageBrush(), and InitFromTextureObject().
The documentation for this struct was generated from the following file:
SlateDynamicImageBrush.h