Unreal Engine 5.6 C++ API: ALevelSequenceActor Class Reference
ALevelSequenceActor Class Reference
#include "LevelSequenceActor.h"
Public Member Functions
DECLARE_DYNAMIC_DELEGATE (FOnLevelSequenceLoaded)
GENERATED_BODY () LEVELSEQUENCE_API ALevelSequenceActor(const FObjectInitializer &Init)
Create and initialize a new instance.
virtual LEVELSEQUENCE_API TSharedPtr< FStructOnScope > GetObjectPickerProxy (TSharedPtr< IPropertyHandle > PropertyHandle) override
Return a proxy struct used for editing the bound object.
virtual LEVELSEQUENCE_API bool GetReferencedContentObjects (TArray< UObject * > &Objects) const override
const FWorldPartitionResolveData & GetWorldPartitionResolveData () const
LEVELSEQUENCE_API void InitializePlayer ()
Initialize the player object by loading the asset, using async loading when necessary.
LEVELSEQUENCE_API void InitializePlayerWithSequence (ULevelSequence *LevelSequenceAsset)
Initialize the player object with the specified asset.
LEVELSEQUENCE_API void OnSequenceLoaded (const FName &PackageName, UPackage *Package, EAsyncLoadingResult::Type Result)
LEVELSEQUENCE_API void RefreshBurnIn ()
Refresh this actor's burn in.
virtual LEVELSEQUENCE_API UMovieSceneSequence * RetrieveOwnedSequence () const override
virtual void SetWorldPartitionResolveData (const FWorldPartitionResolveData &InWorldPartitionResolveData)
UE_DEPRECATED (5.4, "Direct access to SequencePlayer will be removed. Please use GetSequencePlayer()") UPROPERTY()) TObjectPtr< ULevelSequencePlayer > SequencePlayer
UFUNCTION () LEVELSEQUENCE_API const TArray< FMovieSceneObjectBindingID > &FindNamedBindings(FName Tag) const
Retrieve all the bindings that have been tagged with the specified name.
UFUNCTION () LEVELSEQUENCE_API FMovieSceneObjectBindingID FindNamedBinding(FName Tag) const
Retrieve the first object binding that has been tagged with the specified name.
UFUNCTION () LEVELSEQUENCE_API ULevelSequence *GetSequence() const
Get the level sequence being played by this actor.
UFUNCTION () LEVELSEQUENCE_API ULevelSequencePlayer *GetSequencePlayer() const
Access this actor's sequence player, or None if it is not yet initialized.
UFUNCTION () LEVELSEQUENCE_API void AddBinding(FMovieSceneObjectBindingID Binding
Adds the specified actor to the overridden bindings for the specified binding ID, optionally still allowing the bindings defined in the Level Sequence asset.
UFUNCTION () LEVELSEQUENCE_API void AddBindingByTag(FName BindingTag
Binds an actor to all the bindings tagged with the specified name in this sequence.
UFUNCTION () LEVELSEQUENCE_API void HideBurnin()
UFUNCTION () LEVELSEQUENCE_API void RemoveBinding(FMovieSceneObjectBindingID Binding
Removes the specified actor from the specified binding's actor array.
UFUNCTION () LEVELSEQUENCE_API void RemoveBindingByTag(FName Tag
Removes the specified actor from the specified binding's actor array.
UFUNCTION () LEVELSEQUENCE_API void ResetBinding(FMovieSceneObjectBindingID Binding)
Resets the specified binding back to the defaults defined by the Level Sequence asset.
UFUNCTION () LEVELSEQUENCE_API void ResetBindings()
Resets all overridden bindings back to the defaults defined by the Level Sequence asset.
UFUNCTION () LEVELSEQUENCE_API void SetBinding(FMovieSceneObjectBindingID Binding
Overrides the specified binding with the specified actors, optionally still allowing the bindings defined in the Level Sequence asset.
UFUNCTION () LEVELSEQUENCE_API void SetBindingByTag(FName BindingTag
Assigns an set of actors to all the bindings tagged with the specified name in this sequence.
UFUNCTION () LEVELSEQUENCE_API void SetReplicatePlayback(bool ReplicatePlayback)
Set whether or not to replicate playback for this actor.
UFUNCTION () LEVELSEQUENCE_API void SetSequence(ULevelSequence *InSequence)
Set the level sequence being played by this actor.
UFUNCTION () LEVELSEQUENCE_API void ShowBurnin()
virtual LEVELSEQUENCE_API void UpdateObjectFromProxy (FStructOnScope &Proxy, IPropertyHandle &ObjectPropertyHandle) override
Update the specified object property handle based on the proxy structure's contents.
UPROPERTY () TObjectPtr< ULevelSequenceBurnInOptions > BurnInOptions
UPROPERTY () TObjectPtr< UMovieSceneBindingOverrides > BindingOverrides
Mapping of actors to override the sequence bindings with.
UPROPERTY() uint8 bAutoPlay_DEPRECATED UPROPERTY() uint8 bOverrideInstanceData UPROPERTY()) uint8 bReplicatePlayback UPROPERTY () TObjectPtr< UObject > DefaultInstanceData
Enable specification of dynamic instance data to be supplied to the sequence during playback.
UPROPERTY ()) FLevelSequenceCameraSettings CameraSettings
UPROPERTY ()) FMovieSceneSequencePlaybackSettings PlaybackSettings
UPROPERTY ()) TObjectPtr< ULevelSequence > LevelSequenceAsset
Public Member Functions inherited from IMovieScenePlaybackClient
virtual void WarpEvaluationRange (FMovieSceneEvaluationRange &InOutRange) const
Public Member Functions inherited from IMovieSceneBindingOwnerInterface
GENERATED_BODY () virtual UMovieSceneSequence *RetrieveOwnedSequence() const =0
Retrieve the sequence that we own.
Data Fields
AActor * Actor
const TArray< AActor * > & Actors
const TArray< AActor * > bool bAllowBindingsFromAsset = false)
AActor bool bAllowBindingsFromAsset = false)
Protected Member Functions
virtual LEVELSEQUENCE_API void BeginPlay () override
virtual bool CanChangeIsSpatiallyLoadedFlag () const override
virtual LEVELSEQUENCE_API void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual LEVELSEQUENCE_API TOptional< EAspectRatioAxisConstraint > GetAspectRatioAxisConstraint () const override
Whether this playback client wants a specific aspect ratio axis constraint during playback.
virtual LEVELSEQUENCE_API UObject * GetInstanceData () const override
Retrieve the optional instance data that should be used for this evaluation.
virtual LEVELSEQUENCE_API bool GetIsReplicatedPlayback () const override
virtual LEVELSEQUENCE_API void PostInitializeComponents () override
virtual LEVELSEQUENCE_API void PostInitProperties () override
virtual LEVELSEQUENCE_API void PostLoad () override
virtual LEVELSEQUENCE_API void PostNetReceive () override
virtual LEVELSEQUENCE_API void PreInitializeComponents () override
virtual LEVELSEQUENCE_API bool RetrieveBindingOverrides (const FGuid &InBindingId, FMovieSceneSequenceID InSequenceID, TArray< UObject *, TInlineAllocator< 1 > > &OutObjects) const override
Locate bound objects that relate to the specified binding ID.
virtual LEVELSEQUENCE_API void RewindForReplay () override
Private Member Functions
UPROPERTY () bool bShowBurnin
UPROPERTY () FWorldPartitionResolveData WorldPartitionResolveData
UPROPERTY () TObjectPtr< ULevelSequenceBurnIn > BurnInInstance
Burn-in widget.
Additional Inherited Members
Static Public Member Functions inherited from IMovieSceneBindingOwnerInterface
static IMovieSceneBindingOwnerInterface * FindFromObject (UObject *InObject)
Find an IMovieSceneBindingOwnerInterface ptr from the specified object or its outers.
Detailed Description
Definition at line 66 of file LevelSequenceActor.h.
Member Function Documentation
BeginPlay()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::BeginPlay () override protected virtual
CanChangeIsSpatiallyLoadedFlag()
virtual bool ALevelSequenceActor::CanChangeIsSpatiallyLoadedFlag () const inline override protected virtual
Definition at line 283 of file LevelSequenceActor.h.
DECLARE_DYNAMIC_DELEGATE()
ALevelSequenceActor::DECLARE_DYNAMIC_DELEGATE (FOnLevelSequenceLoaded)
EndPlay()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::EndPlay (const EEndPlayReason::Type EndPlayReason) override protected virtual
GENERATED_BODY()
ALevelSequenceActor::GENERATED_BODY () const & virtual
Create and initialize a new instance.
Implements IWorldPartitionObjectResolver.
References Init.
GetAspectRatioAxisConstraint()
virtual LEVELSEQUENCE_API TOptional< EAspectRatioAxisConstraint > ALevelSequenceActor::GetAspectRatioAxisConstraint () const override protected virtual
Whether this playback client wants a specific aspect ratio axis constraint during playback.
Reimplemented from IMovieScenePlaybackClient.
References GetAspectRatioAxisConstraint().
Referenced by GetAspectRatioAxisConstraint().
GetInstanceData()
virtual LEVELSEQUENCE_API UObject * ALevelSequenceActor::GetInstanceData () const override protected virtual
Retrieve the optional instance data that should be used for this evaluation.
Implements IMovieScenePlaybackClient.
References GetInstanceData().
Referenced by GetInstanceData().
GetIsReplicatedPlayback()
virtual LEVELSEQUENCE_API bool ALevelSequenceActor::GetIsReplicatedPlayback () const override protected virtual
Reimplemented from IMovieScenePlaybackClient.
References GetIsReplicatedPlayback().
Referenced by GetIsReplicatedPlayback().
GetObjectPickerProxy()
virtual LEVELSEQUENCE_API TSharedPtr< FStructOnScope > ALevelSequenceActor::GetObjectPickerProxy (TSharedPtr< IPropertyHandle > ObjectPropertyHandle) override virtual
Return a proxy struct used for editing the bound object.
Implements IMovieSceneBindingOwnerInterface.
GetReferencedContentObjects()
virtual LEVELSEQUENCE_API bool ALevelSequenceActor::GetReferencedContentObjects (TArray< UObject * > & Objects) const override virtual
GetWorldPartitionResolveData()
const FWorldPartitionResolveData & ALevelSequenceActor::GetWorldPartitionResolveData () const inline virtual
Implements IWorldPartitionObjectResolver.
Definition at line 289 of file LevelSequenceActor.h.
InitializePlayer()
LEVELSEQUENCE_API void ALevelSequenceActor::InitializePlayer ()
Initialize the player object by loading the asset, using async loading when necessary.
InitializePlayerWithSequence()
LEVELSEQUENCE_API void ALevelSequenceActor::InitializePlayerWithSequence (ULevelSequence * LevelSequenceAsset)
Initialize the player object with the specified asset.
OnSequenceLoaded()
LEVELSEQUENCE_API void ALevelSequenceActor::OnSequenceLoaded (const FName & PackageName, UPackage * Package, EAsyncLoadingResult::Type Result)
References Package, and PackageName.
PostInitializeComponents()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::PostInitializeComponents () override protected virtual
PostInitProperties()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::PostInitProperties () override protected virtual
References PostInitProperties().
Referenced by PostInitProperties().
PostLoad()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::PostLoad () override protected virtual
References PostLoad().
Referenced by PostLoad().
PostNetReceive()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::PostNetReceive () override protected virtual
PreInitializeComponents()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::PreInitializeComponents () override protected virtual
RefreshBurnIn()
LEVELSEQUENCE_API void ALevelSequenceActor::RefreshBurnIn ()
Refresh this actor's burn in.
References RefreshBurnIn().
Referenced by RefreshBurnIn().
RetrieveBindingOverrides()
virtual LEVELSEQUENCE_API bool ALevelSequenceActor::RetrieveBindingOverrides (const FGuid & InBindingId, FMovieSceneSequenceID InSequenceID, TArray< UObject *, TInlineAllocator< 1 > > & OutObjects) const override protected virtual
Locate bound objects that relate to the specified binding ID.
Parameters
InBindingId The GUID of the object binding in the movie scene
OutObjects Array to populate with bound objects
Returns
true to prevent default lookup of the binding in the sequence itself, else false
Implements IMovieScenePlaybackClient.
References RetrieveBindingOverrides().
Referenced by RetrieveBindingOverrides().
RetrieveOwnedSequence()
virtual LEVELSEQUENCE_API UMovieSceneSequence * ALevelSequenceActor::RetrieveOwnedSequence () const override virtual
RewindForReplay()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::RewindForReplay () override protected virtual
SetWorldPartitionResolveData()
virtual void ALevelSequenceActor::SetWorldPartitionResolveData (const FWorldPartitionResolveData & InWorldPartitionResolveData) inline virtual
Definition at line 295 of file LevelSequenceActor.h.
UE_DEPRECATED()
ALevelSequenceActor::UE_DEPRECATED (5. 4, "Direct access to SequencePlayer will be removed. Please use GetSequencePlayer()")
References Category, meta, transient, UE_DEPRECATED(), and UPROPERTY().
Referenced by UE_DEPRECATED().
UFUNCTION() [1/16]
ALevelSequenceActor::UFUNCTION () const &
Retrieve all the bindings that have been tagged with the specified name.
Parameters
Tag The unique tag name to lookup bindings with. Object Bindings can be tagged within the sequence UI by RMB -> Tags... on the object binding in the tree.
Returns
An array containing all the bindings that are tagged with this name, potentially empty.
References Category, and UFUNCTION().
UFUNCTION() [2/16]
ALevelSequenceActor::UFUNCTION () const
Retrieve the first object binding that has been tagged with the specified name.
References Category, and UFUNCTION().
UFUNCTION() [3/16]
ALevelSequenceActor::UFUNCTION () const
Get the level sequence being played by this actor.
Returns
Level sequence, or nullptr if not assigned or if it cannot be loaded.
See also
SetSequence
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/16]
ALevelSequenceActor::UFUNCTION () const
Access this actor's sequence player, or None if it is not yet initialized.
References UFUNCTION().
UFUNCTION() [5/16]
ALevelSequenceActor::UFUNCTION ()
Adds the specified actor to the overridden bindings for the specified binding ID, optionally still allowing the bindings defined in the Level Sequence asset.
Parameters
Binding Binding to modify
Actor Actor to bind
bAllowBindingsFromAsset If false the new bindings being supplied here will replace the bindings set in the level sequence asset, meaning the original object animated by Sequencer will no longer be animated. Bindings set to spawnables will not spawn if false. If true, new bindings will be in addition to ones set set in Sequencer UI. This function will not modify the original asset.
References Category, and UFUNCTION().
UFUNCTION() [6/16]
ALevelSequenceActor::UFUNCTION ()
Binds an actor to all the bindings tagged with the specified name in this sequence.
Does not remove any exising bindings that have been set up through this API. Object Bindings can be tagged within the sequence UI by RMB -> Tags... on the object binding in the tree.
Parameters
BindingTag The unique tag name to lookup bindings with
Actor The actor to assign to all the tagged bindings
bAllowBindingsFromAsset If false the new bindings being supplied here will replace the bindings set in the level sequence asset, meaning the original object animated by Sequencer will no longer be animated. Bindings set to spawnables will not spawn if false. If true, new bindings will be in addition to ones set set in Sequencer UI. This function will not modify the original asset.
References Actor, bAllowBindingsFromAsset, Category, and UFUNCTION().
UFUNCTION() [7/16]
ALevelSequenceActor::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [8/16]
ALevelSequenceActor::UFUNCTION ()
Removes the specified actor from the specified binding's actor array.
References Actor, Category, and UFUNCTION().
UFUNCTION() [9/16]
ALevelSequenceActor::UFUNCTION ()
Removes the specified actor from the specified binding's actor array.
References Actor, Category, and UFUNCTION().
UFUNCTION() [10/16]
ALevelSequenceActor::UFUNCTION ()
Resets the specified binding back to the defaults defined by the Level Sequence asset.
References Category, and UFUNCTION().
UFUNCTION() [11/16]
ALevelSequenceActor::UFUNCTION ()
Resets all overridden bindings back to the defaults defined by the Level Sequence asset.
References Category, and UFUNCTION().
UFUNCTION() [12/16]
ALevelSequenceActor::UFUNCTION ()
Overrides the specified binding with the specified actors, optionally still allowing the bindings defined in the Level Sequence asset.
Parameters
Binding Binding to modify
Actors Actors to bind
bAllowBindingsFromAsset If false the new bindings being supplied here will replace the bindings set in the level sequence asset, meaning the original object animated by Sequencer will no longer be animated. Bindings set to spawnables will not spawn if false. If true, new bindings will be in addition to ones set set in Sequencer UI. This function will not modify the original asset.
References Category, and UFUNCTION().
UFUNCTION() [13/16]
ALevelSequenceActor::UFUNCTION ()
Assigns an set of actors to all the bindings tagged with the specified name in this sequence.
Object Bindings can be tagged within the sequence UI by RMB -> Tags... on the object binding in the tree.
Parameters
BindingTag The unique tag name to lookup bindings with
Actors The actors to assign to all the tagged bindings
bAllowBindingsFromAsset If false the new bindings being supplied here will replace the bindings set in the level sequence asset, meaning the original object animated by Sequencer will no longer be animated. Bindings set to spawnables will not spawn if false. If true, new bindings will be in addition to ones set set in Sequencer UI. This function will not modify the original asset.
References Actors, bAllowBindingsFromAsset, Category, and UFUNCTION().
UFUNCTION() [14/16]
ALevelSequenceActor::UFUNCTION ()
Set whether or not to replicate playback for this actor.
References UFUNCTION().
UFUNCTION() [15/16]
ALevelSequenceActor::UFUNCTION ()
Set the level sequence being played by this actor.
Parameters
InSequence The sequence object to set.
See also
GetSequence
References Category, and UFUNCTION().
UFUNCTION() [16/16]
ALevelSequenceActor::UFUNCTION ()
References Category, and UFUNCTION().
UpdateObjectFromProxy()
virtual LEVELSEQUENCE_API void ALevelSequenceActor::UpdateObjectFromProxy (FStructOnScope & Proxy, IPropertyHandle & ObjectPropertyHandle) override virtual
Update the specified object property handle based on the proxy structure's contents.
Implements IMovieSceneBindingOwnerInterface.
UPROPERTY() [1/9]
ALevelSequenceActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [2/9]
ALevelSequenceActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [3/9]
ALevelSequenceActor::UPROPERTY () private
Burn-in widget.
UPROPERTY() [4/9]
ALevelSequenceActor::UPROPERTY ()
References Category.
UPROPERTY() [5/9]
ALevelSequenceActor::UPROPERTY ()
Mapping of actors to override the sequence bindings with.
References Category, meta, and UPROPERTY().
UPROPERTY() [6/9]
UPROPERTY() uint8 bAutoPlay_DEPRECATED UPROPERTY() uint8 bOverrideInstanceData UPROPERTY()) uint8 bReplicatePlayback ALevelSequenceActor::UPROPERTY ()
Enable specification of dynamic instance data to be supplied to the sequence during playback.
If true, playback of this level sequence on the server will be synchronized across other clients Instance data that can be used to dynamically control sequence evaluation at runtime
References Category, and UPROPERTY().
UPROPERTY() [7/9]
ALevelSequenceActor::UPROPERTY ()
References Category, and meta.
UPROPERTY() [8/9]
ALevelSequenceActor::UPROPERTY ()
References Category, meta, and UPROPERTY().
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [9/9]
ALevelSequenceActor::UPROPERTY ()
References Category, meta, and UPROPERTY().
Field Documentation
Actor
AActor * ALevelSequenceActor::Actor
Definition at line 202 of file LevelSequenceActor.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
Actors
const TArray< AActor * > & ALevelSequenceActor::Actors
Definition at line 178 of file LevelSequenceActor.h.
Referenced by UFUNCTION().
bAllowBindingsFromAsset [1/2]
AActor bool ALevelSequenceActor::bAllowBindingsFromAsset = false)
Definition at line 178 of file LevelSequenceActor.h.
Referenced by UFUNCTION(), and UFUNCTION().
bAllowBindingsFromAsset [2/2]
AActor bool ALevelSequenceActor::bAllowBindingsFromAsset = false)
Definition at line 202 of file LevelSequenceActor.h.
The documentation for this class was generated from the following file:
LevelSequenceActor.h