Unreal Engine 5.6 C++ API: FStaticResolutionFractionHeuristic::FUserSettings Struct Reference
FStaticResolutionFractionHeuristic::FUserSettings Struct Reference
#include "LegacyScreenPercentageDriver.h"
Public Member Functions
void PullEditorRenderingSettings (EViewStatusForScreenPercentage ViewStatus)
Pulls the user settings from the editor cvars.
void PullRunTimeRenderingSettings (EViewStatusForScreenPercentage ViewStatus)
Pulls the user settings from the gameplay runtime cvars.
UE_DEPRECATED (5.3, "Uses PullEditorRenderingSettings(EViewStatusForScreenPercentage) instead") 1 void PullEditorRenderingSettings(bool bIsRealTime
UE_DEPRECATED (5.3, "Uses PullRunTimeRenderingSettings(EViewStatusForScreenPercentage) instead") 1 void PullRunTimeRenderingSettings()
Static Public Member Functions
static bool EditorOverridePIESettings ()
Return whether should use the editor settings for PIE.
Data Fields
float AutoPixelCountMultiplier = 1.0f
bool bAllowDisplayBasedScreenPercentageMode = true
bool bIsPathTraced
float GlobalResolutionFraction = 1.0f
float MaxRenderingResolution = 0.0f
float MinRenderingResolution = 0.0f
EScreenPercentageMode Mode = EScreenPercentageMode::Manual
Detailed Description
Definition at line 89 of file LegacyScreenPercentageDriver.h.
Member Function Documentation
EditorOverridePIESettings()
bool FStaticResolutionFractionHeuristic::FUserSettings::EditorOverridePIESettings () static
Return whether should use the editor settings for PIE.
References EditorOverridePIESettings().
Referenced by EditorOverridePIESettings().
PullEditorRenderingSettings()
void FStaticResolutionFractionHeuristic::FUserSettings::PullEditorRenderingSettings (EViewStatusForScreenPercentage ViewStatus)
Pulls the user settings from the editor cvars.
PullRunTimeRenderingSettings()
void FStaticResolutionFractionHeuristic::FUserSettings::PullRunTimeRenderingSettings (EViewStatusForScreenPercentage ViewStatus)
Pulls the user settings from the gameplay runtime cvars.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/2]
FStaticResolutionFractionHeuristic::FUserSettings::UE_DEPRECATED (5. 3, "Uses PullEditorRenderingSettings(EViewStatusForScreenPercentage) instead")
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FStaticResolutionFractionHeuristic::FUserSettings::UE_DEPRECATED (5. 3, "Uses PullRunTimeRenderingSettings(EViewStatusForScreenPercentage) instead")
References PullRunTimeRenderingSettings().
Referenced by UE_DEPRECATED().
Field Documentation
AutoPixelCountMultiplier
float FStaticResolutionFractionHeuristic::FUserSettings::AutoPixelCountMultiplier = 1.0f
Definition at line 101 of file LegacyScreenPercentageDriver.h.
bAllowDisplayBasedScreenPercentageMode
bool FStaticResolutionFractionHeuristic::FUserSettings::bAllowDisplayBasedScreenPercentageMode = true
Definition at line 104 of file LegacyScreenPercentageDriver.h.
bIsPathTraced
bool FStaticResolutionFractionHeuristic::FUserSettings::bIsPathTraced
Definition at line 126 of file LegacyScreenPercentageDriver.h.
GlobalResolutionFraction
float FStaticResolutionFractionHeuristic::FUserSettings::GlobalResolutionFraction = 1.0f
Definition at line 94 of file LegacyScreenPercentageDriver.h.
MaxRenderingResolution
float FStaticResolutionFractionHeuristic::FUserSettings::MaxRenderingResolution = 0.0f
Definition at line 98 of file LegacyScreenPercentageDriver.h.
MinRenderingResolution
float FStaticResolutionFractionHeuristic::FUserSettings::MinRenderingResolution = 0.0f
Definition at line 97 of file LegacyScreenPercentageDriver.h.
Mode
EScreenPercentageMode FStaticResolutionFractionHeuristic::FUserSettings::Mode = EScreenPercentageMode::Manual
Definition at line 91 of file LegacyScreenPercentageDriver.h.
The documentation for this struct was generated from the following file:
LegacyScreenPercentageDriver.h