Unreal Engine 5.6 C++ API: RichCurve.h File Reference
RichCurve.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "Curves/KeyHandle.h"
#include "Curves/RealCurve.h"
#include "Chaos/Curve.h"
#include "RichCurve.generated.h"
Data Structures
struct FRichCurveEditInfoTemplate< T >
Info about a curve to be edited.
struct TIsPODType< FRichCurveKey >
struct TStructOpsTypeTraits< FCompressedRichCurve >
struct TStructOpsTypeTraits< FRichCurveKey >
Typedefs
typedef FRichCurveEditInfoTemplate< FRealCurve * > FRichCurveEditInfo
typedef FRichCurveEditInfoTemplate< const FRealCurve * > FRichCurveEditInfoConst
Functions
UENUM() enum ERichCurveTangentMode UENUM() enum ERichCurveTangentWeightMode UENUM() enum ERichCurveCompressionFormat UENUM() enum ERichCurveKeyTimeCompressionFormat USTRUCT () struct FRichCurveKey
If using RCIM_Cubic, this enum describes how the tangents should be controlled in editor.
Typedef Documentation
FRichCurveEditInfo
typedef FRichCurveEditInfoTemplate<FRealCurve*> FRichCurveEditInfo
Definition at line 510 of file RichCurve.h.
FRichCurveEditInfoConst
typedef FRichCurveEditInfoTemplate<const FRealCurve*> FRichCurveEditInfoConst
Definition at line 511 of file RichCurve.h.
Function Documentation
USTRUCT()
UENUM() enum ERichCurveTangentMode UENUM() enum ERichCurveTangentWeightMode UENUM() enum ERichCurveCompressionFormat UENUM() enum ERichCurveKeyTimeCompressionFormat USTRUCT ()
If using RCIM_Cubic, this enum describes how the tangents should be controlled in editor.
A rich, editable float curve.
Enumerates tangent weight modes. Enumerates curve compression options. Enumerates key time compression options. One key in a rich, editable float curve
A runtime optimized representation of a FRichCurve. It consumes less memory and evaluates faster.
Interpolation mode between this key and the next
Mode for tangents at this key
If either tangent at this key is 'weighted'
Time at this key
Value at this key
If RCIM_Cubic, the arriving tangent at this key
If RCTWM_WeightedArrive or RCTWM_WeightedBoth, the weight of the left tangent
If RCIM_Cubic, the leaving tangent at this key
If RCTWM_WeightedLeave or RCTWM_WeightedBoth, the weight of the right tangent
Conversion constructor
ICPPStructOps interface
Compression format used by CompressedKeys
Compression format used to pack the key time
Pre-infinity extrapolation state
Post-infinity extrapolation state
If the compression format is constant, this is the value returned Inline here to reduce the likelihood of accessing the compressed keys data for the common case of constant/zero/empty curves When a curve is linear/cubic/mixed, the constant float value isn't used and instead we use the number of keys
Compressed keys, used only outside of the editor
Evaluate this rich curve at the specified time
Populate RichCurve with decompressed key-data
Evaluate this rich curve at the specified time
Evaluate this rich curve at the specified time
ICPPStructOps interface
Definition at line 79 of file RichCurve.h.
References Ar, ArriveTangent, BlueprintType, Category, GENERATED_USTRUCT_BODY, InTime, LeaveTangent, operator!=(), operator<<(), operator==(), Other, Time, UPROPERTY, and Value.