Unreal Engine 5.6 C++ API: UE::TSharedString< CharType > Class Template Reference
UE::TSharedString< CharType > Class Template Reference
A reference to an immutable, shared, reference-counted string.
#include "SharedString.h"
Public Types
using ElementType = CharType
Public Member Functions
TSharedString ()=default
TSharedString (const TSharedString &String)
TSharedString (TSharedString &&String)
TSharedString (TStringView< CharType > String)
Allocates a copy of the string and constructs this as a reference to it.
~TSharedString ()
bool IsEmpty () const
Returns true if the referenced string is empty.
int32 Len () const
Returns the length of the referenced string excluding the null terminator.
const CharType * operator* () const
Returns a pointer to the start of the referenced null-terminated string.
TSharedString & operator= (const TSharedString &String)
TSharedString & operator= (TSharedString &&String)
TSharedString & operator= (TStringView< CharType > String)
Allocates a copy of the string and assigns this as a reference to it.
void Reset ()
Resets this to reference the empty string.
Static Public Attributes
static const TSharedString Empty
An empty string provided mainly for returning a reference to an empty TSharedString.
Static Private Member Functions
static void AddRef (CharType *Chars)
static void Release (CharType *Chars)
Private Attributes
CharType * Chars = nullptr
Static Private Attributes
static constexpr CharType NullChar {}
Friends
constexpr const CharType * GetData (const TSharedString String)
constexpr auto GetNum (const TSharedString String)
uint32 GetTypeHash (const TSharedString &String)
bool operator< (const TSharedString &Lhs, const TSharedString &Rhs)
bool operator== (const TSharedString &Lhs, const TSharedString &Rhs)
Detailed Description
template<typename CharType>
class UE::TSharedString< CharType >
A reference to an immutable, shared, reference-counted string.
Prefer TStringView when there is a clear single point of ownership with a longer lifetime than the references to the string. This type is meant for cases where a shared string does not have an obvious owner or where the lifetime is not easy to manage.
The string is stored as a pointer to the start of the null-terminated string which is preceded by a 4-byte reference count and a 4-byte size.
Definition at line 28 of file SharedString.h.
Member Typedef Documentation
ElementType
template<typename CharType> using UE::TSharedString< CharType >::ElementType = CharType
Definition at line 31 of file SharedString.h.
Constructor & Destructor Documentation
TSharedString() [1/4]
template<typename CharType> UE::TSharedString< CharType >::TSharedString () nodiscard default
Referenced by TSharedString(), TSharedString(), operator=(), operator=(), and operator=().
TSharedString() [2/4]
template<typename CharType> UE::TSharedString< CharType >::TSharedString (TSharedString< CharType > && String) inline nodiscard
Definition at line 116 of file SharedString.h.
References TSharedString(), and Chars.
TSharedString() [3/4]
template<typename CharType> UE::TSharedString< CharType >::TSharedString (const TSharedString< CharType > & String) nodiscard
Definition at line 123 of file SharedString.h.
References TSharedString(), AddRef(), and Chars.
TSharedString() [4/4]
template<typename CharType> UE::TSharedString< CharType >::TSharedString (TStringView< CharType > String) nodiscard
Allocates a copy of the string and constructs this as a reference to it.
Definition at line 153 of file SharedString.h.
References Chars, Header, MIN_ALIGNMENT, and TSequenceHistory< HistorySize >::Size.
~TSharedString()
template<typename CharType> UE::TSharedString< CharType >::~TSharedString () inline
Definition at line 45 of file SharedString.h.
Member Function Documentation
AddRef()
template<typename CharType> void UE::TSharedString< CharType >::AddRef (CharType * Chars) inline static private
Definition at line 177 of file SharedString.h.
References Header.
Referenced by TSharedString(), and operator=().
IsEmpty()
template<typename CharType> bool UE::TSharedString< CharType >::IsEmpty () const inline nodiscard
Returns true if the referenced string is empty.
Definition at line 58 of file SharedString.h.
Len()
template<typename CharType> int32 UE::TSharedString< CharType >::Len () const inline nodiscard
Returns the length of the referenced string excluding the null terminator.
Definition at line 64 of file SharedString.h.
operator*()
template<typename CharType> const CharType * UE::TSharedString< CharType >::operator* () const inline nodiscard
Returns a pointer to the start of the referenced null-terminated string.
Definition at line 70 of file SharedString.h.
operator=() [1/3]
template<typename CharType> TSharedString< CharType > & UE::TSharedString< CharType >::operator= (const TSharedString< CharType > & String)
Definition at line 142 of file SharedString.h.
References TSharedString(), AddRef(), Chars, and Release().
operator=() [2/3]
template<typename CharType> TSharedString< CharType > & UE::TSharedString< CharType >::operator= (TSharedString< CharType > && String)
Definition at line 130 of file SharedString.h.
References TSharedString(), Chars, and Release().
operator=() [3/3]
template<typename CharType> TSharedString< CharType > & UE::TSharedString< CharType >::operator= (TStringView< CharType > String)
Allocates a copy of the string and assigns this as a reference to it.
Definition at line 171 of file SharedString.h.
References TSharedString().
Release()
template<typename CharType> void UE::TSharedString< CharType >::Release (CharType * Chars) inline static private
Definition at line 189 of file SharedString.h.
References FMemory::Free(), and Header.
Referenced by UE::TSharedString< TCHAR >::~TSharedString(), operator=(), operator=(), and UE::TSharedString< TCHAR >::Reset().
Reset()
template<typename CharType> void UE::TSharedString< CharType >::Reset () inline
Resets this to reference the empty string.
Definition at line 51 of file SharedString.h.
Friends And Related Symbol Documentation
GetData
template<typename CharType> const CharType * GetData (const TSharedString< CharType > String) friend
Definition at line 79 of file SharedString.h.
GetNum
template<typename CharType> auto GetNum (const TSharedString< CharType > String) friend
Definition at line 84 of file SharedString.h.
GetTypeHash
template<typename CharType> uint32 GetTypeHash (const TSharedString< CharType > & String) friend
Definition at line 89 of file SharedString.h.
Referenced by UE::TSharedString< TCHAR >::GetTypeHash.
operator<
template<typename CharType> bool operator< (const TSharedString< CharType > & Lhs, const TSharedString< CharType > & Rhs) friend
Definition at line 99 of file SharedString.h.
operator==
template<typename CharType> bool operator== (const TSharedString< CharType > & Lhs, const TSharedString< CharType > & Rhs) friend
Definition at line 94 of file SharedString.h.
Field Documentation
Chars
template<typename CharType> CharType* UE::TSharedString< CharType >::Chars = nullptr private
Definition at line 107 of file SharedString.h.
Referenced by TSharedString(), TSharedString(), TSharedString(), operator=(), and operator=().
Empty
template<typename CharType> const TSharedString UE::TSharedString< CharType >::Empty static
An empty string provided mainly for returning a reference to an empty TSharedString.
Definition at line 76 of file SharedString.h.
NullChar
template<typename CharType> CharType UE::TSharedString< CharType >::NullChar {} inline static constexpr private
Definition at line 109 of file SharedString.h.
The documentation for this class was generated from the following file:
SharedString.h