Unreal Engine 5.6 C++ API: FLightMapInteraction Class Reference
FLightMapInteraction Class Reference
Make sure at least one is defined.
#include "SceneManagement.h"
Public Member Functions
FLightMapInteraction ()
Default constructor.
FORCEINLINE bool AllowsHighQualityLightmaps () const
const FVector4f * GetAddArray () const
const ULightMapTexture2D * GetAOMaterialMaskTexture () const
const FVector2D & GetCoordinateBias () const
const FVector2D & GetCoordinateScale () const
uint32 GetNumLightmapCoefficients () const
const FVector4f * GetScaleArray () const
const ULightMapTexture2D * GetSkyOcclusionTexture () const
const ULightMapTexture2D * GetTexture (bool bHighQuality) const
ELightMapInteractionType GetType () const
const ULightMapVirtualTexture2D * GetVirtualTexture () const
void SetCoordinateBias (const FVector2D &InCoordinateBias)
Set the coordinate bias.
void SetCoordinateScale (const FVector2D &InCoordinateScale)
Set the coordinate scale.
void SetLightMapInteractionType (ELightMapInteractionType InType)
These functions are used for the Dummy lightmap policy used in LightMap density view mode.
Static Public Member Functions
static FLightMapInteraction GlobalVolume ()
static FLightMapInteraction InitVirtualTexture (const ULightMapVirtualTexture2D *VirtualTexture, const FVector4f *InCoefficientScales, const FVector4f *InCoefficientAdds, const FVector2D &InCoordinateScale, const FVector2D &InCoordinateBias, bool bAllowHighQualityLightMaps)
static FLightMapInteraction None ()
static FLightMapInteraction Texture (const class ULightMapTexture2D *const *InTextures, const ULightMapTexture2D *InSkyOcclusionTexture, const ULightMapTexture2D *InAOMaterialMaskTexture, const FVector4f *InCoefficientScales, const FVector4f *InCoefficientAdds, const FVector2D &InCoordinateScale, const FVector2D &InCoordinateBias, bool bAllowHighQualityLightMaps)
Private Attributes
const ULightMapTexture2D * AOMaterialMaskTexture
FVector2D CoordinateBias
FVector2D CoordinateScale
FVector4f HighQualityCoefficientAdds [NUM_HQ_LIGHTMAP_COEF]
FVector4f HighQualityCoefficientScales [NUM_HQ_LIGHTMAP_COEF]
const class ULightMapTexture2D * HighQualityTexture
const ULightMapTexture2D * SkyOcclusionTexture
ELightMapInteractionType Type
const ULightMapVirtualTexture2D * VirtualTexture
Detailed Description
Make sure at least one is defined.
Information about an interaction between a light and a mesh.
Definition at line 398 of file SceneManagement.h.
Constructor & Destructor Documentation
FLightMapInteraction()
FLightMapInteraction::FLightMapInteraction () inline
Default constructor.
Definition at line 436 of file SceneManagement.h.
References ALLOW_HQ_LIGHTMAPS, ALLOW_LQ_LIGHTMAPS, AOMaterialMaskTexture, HighQualityTexture, LMIT_None, SkyOcclusionTexture, Type, and VirtualTexture.
Referenced by GlobalVolume(), InitVirtualTexture(), None(), and Texture().
Member Function Documentation
AllowsHighQualityLightmaps()
FORCEINLINE bool FLightMapInteraction::AllowsHighQualityLightmaps () const inline
Returns
true if high quality lightmaps are allowed
Definition at line 549 of file SceneManagement.h.
References FORCEINLINE.
Referenced by GetAddArray(), GetNumLightmapCoefficients(), and GetScaleArray().
GetAddArray()
const FVector4f * FLightMapInteraction::GetAddArray () const inline
Definition at line 507 of file SceneManagement.h.
References AllowsHighQualityLightmaps(), and HighQualityCoefficientAdds.
GetAOMaterialMaskTexture()
const ULightMapTexture2D * FLightMapInteraction::GetAOMaterialMaskTexture () const inline
Definition at line 476 of file SceneManagement.h.
References AOMaterialMaskTexture, check, LMIT_Texture, and Type.
GetCoordinateBias()
const FVector2D & FLightMapInteraction::GetCoordinateBias () const inline
Definition at line 523 of file SceneManagement.h.
References check, CoordinateBias, LMIT_Texture, and Type.
GetCoordinateScale()
const FVector2D & FLightMapInteraction::GetCoordinateScale () const inline
Definition at line 518 of file SceneManagement.h.
References check, CoordinateScale, LMIT_Texture, and Type.
GetNumLightmapCoefficients()
uint32 FLightMapInteraction::GetNumLightmapCoefficients () const inline
Definition at line 529 of file SceneManagement.h.
References AllowsHighQualityLightmaps(), NUM_HQ_LIGHTMAP_COEF, and NUM_LQ_LIGHTMAP_COEF.
GetScaleArray()
const FVector4f * FLightMapInteraction::GetScaleArray () const inline
Definition at line 496 of file SceneManagement.h.
References AllowsHighQualityLightmaps(), and HighQualityCoefficientScales.
GetSkyOcclusionTexture()
const ULightMapTexture2D * FLightMapInteraction::GetSkyOcclusionTexture () const inline
Definition at line 466 of file SceneManagement.h.
References check, LMIT_Texture, SkyOcclusionTexture, and Type.
GetTexture()
const ULightMapTexture2D * FLightMapInteraction::GetTexture (bool bHighQuality) const inline
Definition at line 454 of file SceneManagement.h.
References check, HighQualityTexture, LMIT_Texture, and Type.
GetType()
ELightMapInteractionType FLightMapInteraction::GetType () const inline
Definition at line 452 of file SceneManagement.h.
References Type.
GetVirtualTexture()
const ULightMapVirtualTexture2D * FLightMapInteraction::GetVirtualTexture () const inline
Definition at line 486 of file SceneManagement.h.
References check, LMIT_Texture, Type, and VirtualTexture.
GlobalVolume()
FLightMapInteraction FLightMapInteraction::GlobalVolume () inline static
Definition at line 410 of file SceneManagement.h.
References FLightMapInteraction(), and LMIT_GlobalVolume.
InitVirtualTexture()
FLightMapInteraction FLightMapInteraction::InitVirtualTexture (const ULightMapVirtualTexture2D * VirtualTexture, const FVector4f * InCoefficientScales, const FVector4f * InCoefficientAdds, const FVector2D & InCoordinateScale, const FVector2D & InCoordinateBias, bool bAllowHighQualityLightMaps) static
References FLightMapInteraction(), and VirtualTexture.
None()
FLightMapInteraction FLightMapInteraction::None () inline static
Definition at line 403 of file SceneManagement.h.
References FLightMapInteraction(), and LMIT_None.
Referenced by FLegacyLightMap1D::GetInteraction().
SetCoordinateBias()
void FLightMapInteraction::SetCoordinateBias (const FVector2D & InCoordinateBias) inline
Set the coordinate bias.
Parameters
InCoordinateBias The bias to set it to.
Definition at line 584 of file SceneManagement.h.
References CoordinateBias.
SetCoordinateScale()
void FLightMapInteraction::SetCoordinateScale (const FVector2D & InCoordinateScale) inline
Set the coordinate scale.
Parameters
InCoordinateScale The scale to set it to.
Definition at line 575 of file SceneManagement.h.
References CoordinateScale.
SetLightMapInteractionType()
void FLightMapInteraction::SetLightMapInteractionType (ELightMapInteractionType InType) inline
These functions are used for the Dummy lightmap policy used in LightMap density view mode.
Set the type.
Parameters
InType The type to set it to.
Definition at line 566 of file SceneManagement.h.
References Type.
Texture()
FLightMapInteraction FLightMapInteraction::Texture (const class ULightMapTexture2D *const * InTextures, const ULightMapTexture2D * InSkyOcclusionTexture, const ULightMapTexture2D * InAOMaterialMaskTexture, const FVector4f * InCoefficientScales, const FVector4f * InCoefficientAdds, const FVector2D & InCoordinateScale, const FVector2D & InCoordinateBias, bool bAllowHighQualityLightMaps) static
References FLightMapInteraction().
Field Documentation
AOMaterialMaskTexture
const ULightMapTexture2D* FLightMapInteraction::AOMaterialMaskTexture private
Definition at line 596 of file SceneManagement.h.
Referenced by FLightMapInteraction(), and GetAOMaterialMaskTexture().
CoordinateBias
FVector2D FLightMapInteraction::CoordinateBias private
Definition at line 617 of file SceneManagement.h.
Referenced by GetCoordinateBias(), and SetCoordinateBias().
CoordinateScale
FVector2D FLightMapInteraction::CoordinateScale private
Definition at line 616 of file SceneManagement.h.
Referenced by GetCoordinateScale(), and SetCoordinateScale().
HighQualityCoefficientAdds
FVector4f FLightMapInteraction::HighQualityCoefficientAdds[NUM_HQ_LIGHTMAP_COEF] private
Definition at line 593 of file SceneManagement.h.
Referenced by GetAddArray().
HighQualityCoefficientScales
FVector4f FLightMapInteraction::HighQualityCoefficientScales[NUM_HQ_LIGHTMAP_COEF] private
Definition at line 592 of file SceneManagement.h.
Referenced by GetScaleArray().
HighQualityTexture
const class ULightMapTexture2D* FLightMapInteraction::HighQualityTexture private
Definition at line 594 of file SceneManagement.h.
Referenced by FLightMapInteraction(), and GetTexture().
SkyOcclusionTexture
const ULightMapTexture2D* FLightMapInteraction::SkyOcclusionTexture private
Definition at line 595 of file SceneManagement.h.
Referenced by FLightMapInteraction(), and GetSkyOcclusionTexture().
Type
ELightMapInteractionType FLightMapInteraction::Type private
Definition at line 614 of file SceneManagement.h.
Referenced by FLightMapInteraction(), GetAOMaterialMaskTexture(), GetCoordinateBias(), GetCoordinateScale(), GetSkyOcclusionTexture(), GetTexture(), GetType(), GetVirtualTexture(), and SetLightMapInteractionType().
VirtualTexture
const ULightMapVirtualTexture2D* FLightMapInteraction::VirtualTexture private
Definition at line 611 of file SceneManagement.h.
Referenced by FLightMapInteraction(), GetVirtualTexture(), and InitVirtualTexture().
The documentation for this class was generated from the following file:
SceneManagement.h