Unreal Engine 5.6 C++ API: UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite > Struct Template Reference
UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite > Struct Template Reference
Property accessor traits that talk directly to the reflected UObject property type.
#include "MovieScenePropertyTraits.h"
Public Types
using MetaDataType = TPropertyMetaData<>
using OperationalParamType = typename TCallTraits<StorageType>::ParamType
using PropertyParamType = typename TCallTraits<UObjectPropertyType>::ParamType
using StorageType = InMemoryType
using TraitsType = TIndirectPropertyTraits<UObjectPropertyType, InMemoryType>
Static Public Member Functions
template<typename ... T>
static StorageType CombineComposites (T &&... InComposites)
static void GetObjectPropertyValue (const UObject *InObject, const FCustomPropertyAccessor &BaseCustomAccessor, StorageType &OutValue)
Property Value Getters.
static void GetObjectPropertyValue (const UObject *InObject, const FName &PropertyPath, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FTrackInstancePropertyBindings *PropertyBindings, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, uint16 PropertyOffset, StorageType &OutValue)
static void SetObjectPropertyValue (UObject *InObject, const FCustomPropertyAccessor &BaseCustomAccessor, OperationalParamType InValue)
Property Value Setters.
static void SetObjectPropertyValue (UObject *InObject, FTrackInstancePropertyBindings *PropertyBindings, OperationalParamType InValue)
static void SetObjectPropertyValue (UObject *InObject, uint16 PropertyOffset, OperationalParamType InValue)
Static Public Attributes
static constexpr bool bIsComposite = bInIsComposite
Detailed Description
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true>
struct UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >
Property accessor traits that talk directly to the reflected UObject property type.
Definition at line 91 of file MovieScenePropertyTraits.h.
Member Typedef Documentation
MetaDataType
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> using UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::MetaDataType = TPropertyMetaData<>
Definition at line 96 of file MovieScenePropertyTraits.h.
OperationalParamType
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> using UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::OperationalParamType = typename TCallTraits<StorageType>::ParamType
Definition at line 100 of file MovieScenePropertyTraits.h.
PropertyParamType
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> using UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::PropertyParamType = typename TCallTraits<UObjectPropertyType>::ParamType
Definition at line 99 of file MovieScenePropertyTraits.h.
StorageType
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> using UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::StorageType = InMemoryType
Definition at line 95 of file MovieScenePropertyTraits.h.
TraitsType
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> using UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::TraitsType = TIndirectPropertyTraits<UObjectPropertyType, InMemoryType>
Definition at line 97 of file MovieScenePropertyTraits.h.
Member Function Documentation
CombineComposites()
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> template<typename ... T> StorageType UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::CombineComposites (T &&... InComposites) inline static
Definition at line 149 of file MovieScenePropertyTraits.h.
GetObjectPropertyValue() [1/4]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue (const UObject * InObject, const FCustomPropertyAccessor & BaseCustomAccessor, StorageType & OutValue) inline static
Property Value Getters.
Definition at line 103 of file MovieScenePropertyTraits.h.
Referenced by UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue(), and UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue().
GetObjectPropertyValue() [2/4]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue (const UObject * InObject, const FName & PropertyPath, StorageType & OutValue) inline static
Definition at line 120 of file MovieScenePropertyTraits.h.
GetObjectPropertyValue() [3/4]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue (const UObject * InObject, FTrackInstancePropertyBindings * PropertyBindings, StorageType & OutValue) inline static
Definition at line 114 of file MovieScenePropertyTraits.h.
GetObjectPropertyValue() [4/4]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue (const UObject * InObject, uint16 PropertyOffset, StorageType & OutValue) inline static
Definition at line 109 of file MovieScenePropertyTraits.h.
SetObjectPropertyValue() [1/3]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue (UObject * InObject, const FCustomPropertyAccessor & BaseCustomAccessor, OperationalParamType InValue) inline static
Property Value Setters.
Definition at line 130 of file MovieScenePropertyTraits.h.
Referenced by UE::MovieScene::FColorPropertyTraits::SetObjectPropertyValue(), UE::MovieScene::FColorPropertyTraits::SetObjectPropertyValue(), UE::MovieScene::FDoubleVectorPropertyTraits::SetObjectPropertyValue(), UE::MovieScene::FDoubleVectorPropertyTraits::SetObjectPropertyValue(), UE::MovieScene::FFloatVectorPropertyTraits::SetObjectPropertyValue(), and UE::MovieScene::FFloatVectorPropertyTraits::SetObjectPropertyValue().
SetObjectPropertyValue() [2/3]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue (UObject * InObject, FTrackInstancePropertyBindings * PropertyBindings, OperationalParamType InValue) inline static
Definition at line 140 of file MovieScenePropertyTraits.h.
SetObjectPropertyValue() [3/3]
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> void UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue (UObject * InObject, uint16 PropertyOffset, OperationalParamType InValue) inline static
Definition at line 135 of file MovieScenePropertyTraits.h.
Field Documentation
bIsComposite
template<typename UObjectPropertyType, typename InMemoryType, bool bInIsComposite = true> bool UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::bIsComposite = bInIsComposite static constexpr
Definition at line 93 of file MovieScenePropertyTraits.h.
The documentation for this struct was generated from the following file:
MovieScenePropertyTraits.h