Unreal Engine 5.6 C++ API: UE::MovieScene::FBoundObjectPreAnimatedStateTraits Struct Reference
UE::MovieScene::FBoundObjectPreAnimatedStateTraits Struct Reference
Group state class that groups pre-animated storage together by bound object.
#include "MovieScenePreAnimatedObjectStorage.h"
Public Types
enum { NeedsInitialize = true , SupportsGrouping = true , SupportsReplaceObject = true }
Public Types inherited from UE::MovieScene::FPreAnimatedStateTraits
enum { NeedsInitialize = false , SupportsGrouping = false , SupportsReplaceObject = false }
Public Member Functions
template<typename... T>
FPreAnimatedStorageGroupHandle FindGroup (const FObjectComponent &BoundObject, T &&... Unused)
template<typename... T>
FPreAnimatedStorageGroupHandle FindGroup (UObject *BoundObject, T &&... Unused)
MOVIESCENE_API FPreAnimatedStorageGroupHandle FindGroupImpl (const FObjectComponent &BoundObject)
MOVIESCENE_API FPreAnimatedStorageGroupHandle FindGroupImpl (UObject *BoundObject)
MOVIESCENE_API void Initialize (FPreAnimatedStorageID InStorageID, FPreAnimatedStateExtension *InParentExtension)
template<typename... T>
FPreAnimatedStorageGroupHandle MakeGroup (const FObjectComponent &BoundObject, T &&... Unused)
template<typename... T>
FPreAnimatedStorageGroupHandle MakeGroup (UObject *BoundObject, T &&... Unused)
MOVIESCENE_API FPreAnimatedStorageGroupHandle MakeGroupImpl (const FObjectComponent &BoundObject)
MOVIESCENE_API FPreAnimatedStorageGroupHandle MakeGroupImpl (UObject *BoundObject)
void ReplaceObject (FObjectKey &InOutKey, const FObjectKey &NewObject)
template<typename KeyType>
void ReplaceObject (KeyType &InOutKey, const FObjectKey &NewObject)
template<typename ObjectType>
void ReplaceObject (TObjectKey< ObjectType > &InOutKey, const FObjectKey &NewObject)
template<typename ... T>
void ReplaceObject (TTuple< FObjectKey, T... > &InOutKey, const FObjectKey &NewObject)
template<typename T>
T ResolveComponent (T &&In)
Data Fields
TSharedPtr< FPreAnimatedObjectGroupManager > ObjectGroupManager
Detailed Description
Group state class that groups pre-animated storage together by bound object.
Inherit from this class by implementing the following members:
using KeyType = FObjectKey; using StorageType = <your storage type>; StorageType CachePreAnimatedValue(const FObjectKey& Object); void RestorePreAnimatedValue(const FObjectKey& Object, StorageType& InOutCachedValue, const FRestoreStateParams& Params);
Definition at line 29 of file MovieScenePreAnimatedObjectStorage.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NeedsInitialize
SupportsGrouping
SupportsReplaceObject
Definition at line 31 of file MovieScenePreAnimatedObjectStorage.h.
Member Function Documentation
FindGroup() [1/2]
template<typename... T> FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::FindGroup (const FObjectComponent & BoundObject, T &&... Unused) inline
Definition at line 48 of file MovieScenePreAnimatedObjectStorage.h.
References FindGroupImpl(), and Unused.
FindGroup() [2/2]
template<typename... T> FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::FindGroup (UObject * BoundObject, T &&... Unused) inline
Definition at line 43 of file MovieScenePreAnimatedObjectStorage.h.
References FindGroupImpl(), and Unused.
FindGroupImpl() [1/2]
MOVIESCENE_API FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::FindGroupImpl (const FObjectComponent & BoundObject)
FindGroupImpl() [2/2]
MOVIESCENE_API FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::FindGroupImpl (UObject * BoundObject)
Referenced by FindGroup(), and FindGroup().
Initialize()
MOVIESCENE_API void UE::MovieScene::FBoundObjectPreAnimatedStateTraits::Initialize (FPreAnimatedStorageID InStorageID, FPreAnimatedStateExtension * InParentExtension)
MakeGroup() [1/2]
template<typename... T> FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::MakeGroup (const FObjectComponent & BoundObject, T &&... Unused) inline
Definition at line 60 of file MovieScenePreAnimatedObjectStorage.h.
References MakeGroupImpl(), and Unused.
MakeGroup() [2/2]
template<typename... T> FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::MakeGroup (UObject * BoundObject, T &&... Unused) inline
Definition at line 55 of file MovieScenePreAnimatedObjectStorage.h.
References MakeGroupImpl(), and Unused.
MakeGroupImpl() [1/2]
MOVIESCENE_API FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::MakeGroupImpl (const FObjectComponent & BoundObject)
MakeGroupImpl() [2/2]
MOVIESCENE_API FPreAnimatedStorageGroupHandle UE::MovieScene::FBoundObjectPreAnimatedStateTraits::MakeGroupImpl (UObject * BoundObject)
Referenced by MakeGroup(), and MakeGroup().
ReplaceObject() [1/4]
void UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ReplaceObject (FObjectKey & InOutKey, const FObjectKey & NewObject) inline
Definition at line 89 of file MovieScenePreAnimatedObjectStorage.h.
References NewObject().
ReplaceObject() [2/4]
template<typename KeyType> void UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ReplaceObject (KeyType & InOutKey, const FObjectKey & NewObject) inline
Definition at line 77 of file MovieScenePreAnimatedObjectStorage.h.
References NewObject().
ReplaceObject() [3/4]
template<typename ObjectType> void UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ReplaceObject (TObjectKey< ObjectType > & InOutKey, const FObjectKey & NewObject) inline
Definition at line 82 of file MovieScenePreAnimatedObjectStorage.h.
References Cast(), and NewObject().
ReplaceObject() [4/4]
template<typename ... T> void UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ReplaceObject (TTuple< FObjectKey, T... > & InOutKey, const FObjectKey & NewObject) inline
Definition at line 72 of file MovieScenePreAnimatedObjectStorage.h.
References NewObject().
ResolveComponent()
template<typename T> T UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ResolveComponent (T && In) inline
Definition at line 36 of file MovieScenePreAnimatedObjectStorage.h.
References Forward().
Field Documentation
ObjectGroupManager
TSharedPtr<FPreAnimatedObjectGroupManager> UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ObjectGroupManager
Definition at line 93 of file MovieScenePreAnimatedObjectStorage.h.
The documentation for this struct was generated from the following file:
MovieScenePreAnimatedObjectStorage.h