Unreal Engine 5.6 C++ API: Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType > Class Template Reference
Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType > Class Template Reference
#include "MetasoundNodeRegistrationMacro.h"
Public Member Functions
virtual TUniquePtr< INode > CreateNode (FNodeData InNodeData) const override
Create a node given FNodeData.
METASOUNDFRONTEND_API FNodeRegistryEntryBase (const Metasound::FNodeClassMetadata &InMetadata)
Public Member Functions inherited from Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase
METASOUNDFRONTEND_API FNodeRegistryEntryBase (const Metasound::FNodeClassMetadata &InMetadata)
virtual ~FNodeRegistryEntryBase ()=default
virtual METASOUNDFRONTEND_API TInstancedStruct< FMetaSoundFrontendNodeConfiguration > CreateFrontendNodeConfiguration () const override
Optionally create the node extension associated with the node.
virtual METASOUNDFRONTEND_API const FNodeClassInfo & GetClassInfo () const override
Return FNodeClassInfo for the node class.
virtual METASOUNDFRONTEND_API FVertexInterface GetDefaultVertexInterface () const override
virtual METASOUNDFRONTEND_API const FMetasoundFrontendClass & GetFrontendClass () const override
Return a FMetasoundFrontendClass which describes the node.
virtual METASOUNDFRONTEND_API const TSet< FMetasoundFrontendVersion > * GetImplementedInterfaces () const override
Returns set of implemented interface versions.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") METASOUNDFRONTEND_API virtual TUniquePtr< INode > CreateNode(const FNodeInitData &InInitData) const override
Create a node given FNodeInitData.
Public Member Functions inherited from Metasound::Frontend::INodeClassRegistryEntry
virtual ~INodeClassRegistryEntry ()=default
UE_DEPRECATED (5.6, "Node Class Registration Entries do not need to be cloned.") virtual TUniquePtr< INodeClassRegistryEntry > Clone() const
Clone this registry entry.
UE_DEPRECATED (5.6, "Node class registry no longer tracks nature of implementation (i.e. if was registered " "from an asset or c++. Use the MetaSoundAssetManager to determine if the class has been defined within an asset(s).") virtual bool IsNative() const
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultLiteralNodeConstructorParams &&) const
Create a node given FDefaultLiteralNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexNodeConstructorParams.
UE_DEPRECATED (5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< INode > CreateNode(FDefaultNamedVertexWithLiteralNodeConstructorParams &&) const
Create a node given FDefaultNamedVertexWithLiteralNodeConstructorParams.
Additional Inherited Members
Protected Member Functions inherited from Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase
METASOUNDFRONTEND_API TSharedRef< const FNodeClassMetadata > GetNodeClassMetadata () const
Detailed Description
template<typename TNodeType>
class Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >
Definition at line 64 of file MetasoundNodeRegistrationMacro.h.
Member Function Documentation
CreateNode()
template<typename TNodeType> virtual TUniquePtr< INode > Metasound::Frontend::NodeRegistrationPrivate::TNodeRegistryEntryBase< TNodeType >::CreateNode (FNodeData) const inline override virtual
Create a node given FNodeData.
If a node can be created with FNodeData, this function should return a valid node pointer.
Reimplemented from Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase.
Definition at line 73 of file MetasoundNodeRegistrationMacro.h.
References checkNoEntry, Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::GetNodeClassMetadata(), MakeUnique(), and MoveTemp().
FNodeRegistryEntryBase()
template<typename TNodeType> METASOUNDFRONTEND_API Metasound::Frontend::NodeRegistrationPrivate::FNodeRegistryEntryBase::FNodeRegistryEntryBase (const Metasound::FNodeClassMetadata & InMetadata)
The documentation for this class was generated from the following file:
MetasoundNodeRegistrationMacro.h