Unreal Engine 5.6 C++ API: FActiveSound Struct Reference
FActiveSound Struct Reference
#include "ActiveSound.h"
Data Structures
struct FAsyncTraceDetails
Public Types
enum class EFadeOut : uint8 { None , User , Concurrency }
Public Member Functions
FActiveSound ()
FActiveSound (const FActiveSound &)
~FActiveSound ()
void AddModulationRouting (const TSet< TObjectPtr< USoundModulatorBase > > &NewModulators, EModulationDestination Destination)
void AddReferencedObjects (FReferenceCollector &Collector)
void AddVolumeSubmixSends (FSoundParseParameters &ParseParams, EAudioVolumeLocationState LocationState)
Apply the submix sends to our parse params as appropriate.
FWaveInstance & AddWaveInstance (const UPTRINT WaveInstanceHash)
Add newly created wave instance to active sound.
void ApplyRadioFilter (const FSoundParseParameters &ParseParams)
Check whether to apply the radio filter.
bool CanDelete () const
Returns whether or not the active sound can be deleted.
void ClearAudioComponent ()
void ClearTransmitter ()
void ClearVirtualizationModeOverride ()
Stop using the Virtualization Mode Override.
void CollectAttenuationShapesForVisualization (TMultiMap< EAttenuationShape::Type, FBaseAttenuationSettings::AttenuationShapeDetails > &ShapeDetailsMap) const
int32 FindClosestListener () const
int32 FindClosestListener (const TArray< struct FListener > &InListeners) const
FWaveInstance * FindWaveInstance (const UPTRINT WaveInstanceHash)
Find an existing waveinstance attached to this audio component (if any)
bool GetAlwaysPlay () const
Returns whether or not sound or any active wave instances it manages are set to always play.
uint64 GetAudioComponentID () const
FString GetAudioComponentName () const
FName GetAudioComponentUserID () const
void GetBusSends (EBusSendType BusSendType, TArray< FSoundSourceBusSendInfo > &OutSends) const
Gets the sound source bus sends to use for this sound instance.
int32 GetClosestListenerIndex () const
bool GetConcurrencyFadeDuration (float &OutFadeDuration) const
void GetConcurrencyHandles (TArray< FConcurrencyHandle > &OutConcurrencyHandles) const
Gets the sound concurrency handles applicable to this sound instance.
float GetConcurrencyPriority () const
The priority used for concurrency calculations.
TArray< TSet< TObjectPtr< USoundModulatorBase > > > GetEffectiveVolumeModulators () const
Creates a copy of the modulation configuration for all WaveInstances on this ActiveSound.
float GetHighestPriority (bool bIgnoreAlwaysPlay=false) const
Returns the highest effective priority of the child wave instances.
uint32 GetInstanceID () const
Returns a unique identifier for this active sound object.
TArray< TTuple< EBusSendType, FSoundSourceBusSendInfo > > const & GetNewBusSends () const
Lets the audio thread know if additional Source Bus Send information has been added.
uint32 GetObjectId () const override
FSoundOwnerObjectID GetOwnerID () const
Returns the unique ID of the active sound's owner if it exists.
FString GetOwnerName () const
float GetPitch () const
int32 GetPlayCount () const override
uint32 GetPlayOrder () const
USoundBase * GetSound () const
USoundClass * GetSoundClass () const
Get the sound class to apply on this sound instance.
USoundSubmixBase * GetSoundSubmix () const
Get the sound submix to use for this sound instance.
void GetSoundSubmixSends (TArray< FSoundSubmixSendInfo > &OutSends) const
Gets the sound submix sends to use for this sound instance.
USoundEffectSourcePresetChain * GetSourceEffectChain () const
float GetTotalConcurrencyVolumeScale () const
Gets total concurrency gain stage based on all concurrency memberships of sound.
Audio::IParameterTransmitter * GetTransmitter ()
const Audio::IParameterTransmitter * GetTransmitter () const
EVirtualizationMode GetVirtualizationMode () const
float GetVolume () const
Gets volume product all gain stages pertaining to active sound.
const TMap< UPTRINT, FWaveInstance * > & GetWaveInstances () const
TWeakObjectPtr< UWorld > GetWeakWorld () const
UWorld * GetWorld () const
uint32 GetWorldID () const
bool HasNewBusSends () const
Checks whether there are Source Bus Sends that have not yet been updated.
bool IsLooping () const
Whether or not the active sound is a looping sound.
bool IsOneShot () const
Whether or not the active sound a one-shot sound.
bool IsPlayingAudio () const
Whether or not the active sound is currently playing audible sound.
bool IsPlayWhenSilent () const
Whether or not sound reference is valid and set to play when silent.
bool IsPreviewSound () const override
void OverrideVirtualizationMode (EVirtualizationMode Mode)
Override the Virtualization settings set on Audio Component/Sound.
void ParseAttenuation (FSoundParseParameters &OutParseParams, int32 ListenerIndex, const FSoundAttenuationSettings &InAttenuationSettings)
Applies the active sound's attenuation settings to the input parse params using the given listener.
void RemoveModulationRouting (const TSet< TObjectPtr< USoundModulatorBase > > &NewModulators, EModulationDestination Destination)
void RemoveWaveInstance (const UPTRINT WaveInstanceHash)
void ResetNewBusSends ()
Resets internal data of new Source Bus Sends.
void SetAttenuationSettingsAsset (TObjectPtr< USoundAttenuation > InSoundAttenuation)
void SetAttenuationSettingsOverride (bool bInIsAttenuationSettingsOverridden)
void SetAudioComponent (const FActiveSound &ActiveSound)
void SetAudioComponent (const UAudioComponent &Component)
void SetAudioDevice (FAudioDevice *InAudioDevice)
void SetNewModulationRouting (const FSoundModulationDefaultRoutingSettings &NewRouting)
void SetOwner (const AActor *Owner)
void SetPitch (float Value)
void SetSound (USoundBase *InSound)
void SetSoundClass (USoundClass *SoundClass)
void SetSourceBusSend (EBusSendType BusSendType, const FSoundSourceBusSendInfo &SourceBusSendInfo)
Sets the amount of audio from this active sound to send to the source bus.
void SetSourceEffectChain (USoundEffectSourcePresetChain *InSourceEffectChain)
void SetSourceListener (FSharedISourceBufferListenerPtr InListener, bool bShouldZeroBuffer)
void SetSubmixSend (const FSoundSubmixSendInfo &SubmixSendInfo)
Sets the amount of audio from this active sound to send to the submix.
void SetVolume (float Value)
void SetWorld (UWorld *World)
void Stop () override
UE_DEPRECATED (4.25, "Use ParseAttenuation that passes a ListenerIndex instead") 1 void ParseAttenuation(FSoundParseParameters &OutParseParams
Applies the active sound's attenuation settings to the input parse params using the given listener.
UE_DEPRECATED (4.25, "Use UpdateAttenuation that passes a ListenerIndex instead") 1 void UpdateAttenuation(float DeltaTime
Updates the active sound's attenuation settings to the input parse params using the given listener.
void UpdateAttenuation (float DeltaTime, FSoundParseParameters &ParseParams, int32 ListenerIndex, const FSoundAttenuationSettings *SettingsAttenuationNode=nullptr)
Updates the active sound's attenuation settings to the input parse params using the given listener.
void UpdateFocusData (float DeltaTime, const FAttenuationListenerData &ListenerData, FAttenuationFocusData *OutFocusData=nullptr)
Updates the provided focus data using the local.
void UpdateInterfaceParameters (const TArray< FListener > &InListeners)
void UpdateWaveInstances (TArray< FWaveInstance * > &OutWaveInstances, const float DeltaTime)
Static Public Member Functions
static FActiveSound * CreateVirtualCopy (const FActiveSound &ActiveSoundToCopy, FAudioDevice &AudioDevice)
static void OcclusionTraceDone (const FTraceHandle &TraceHandle, FTraceDatum &TraceDatum)
Delegate callback function when an async occlusion trace completes.
Data Fields
FSoundAttenuationSettings AttenuationSettings
FAudioDevice * AudioDevice
uint32 AudioVolumeID
TArray< FAudioVolumeSubmixSendSettings > AudioVolumeSubmixSendSettings
uint8 bAllowSpatialization:1
Is this sound allowed to be spatialized?
uint8 bAlwaysPlay:1
Whether to artificially prioritize the component to play.
uint8 bApplyInteriorVolumes:1
Whether some part of this sound will want interior sounds to be applied.
uint8 bApplyRadioFilter:1
If true, this sound will not be stopped when flushing the audio device.
FThreadSafeBool bAsyncOcclusionPending
Whether or not there is an async occlusion trace pending.
uint8 bCenterChannelOnly:1
Whether or not this sound class forces sounds to the center channel.
uint8 bEnableBusSendRoutingOverride: 1
What the value of the enablement overrides are.
uint8 bEnableHighPassFilter: 1
Whether or not we have a low-pass filter enabled on this active sound.
uint8 bEnableLowPassFilter: 1
Whether or not we have a low-pass filter enabled on this active sound.
uint8 bEnableMainSubmixOutputOverride: 1
uint8 bEnableSubmixSendRoutingOverride: 1
uint8 bFinished:1
Whether the current component has finished playing.
uint8 bGotInteriorSettings:1
Whether we have queried for the interior settings at least once.
uint8 bHandleSubtitles:1
If true, the AudioComponent will be notified when a Wave is started to handle subtitles.
uint8 bHasActiveBusSendRoutingOverride: 1
Whether or not we are overriding the routing enablement options on sounds.
uint8 bHasActiveMainSubmixOutputOverride: 1
uint8 bHasActiveSubmixSendRoutingOverride: 1
uint8 bHasAttenuationSettings:1
Does this sound have attenuation settings specified.
uint8 bHasCheckedOcclusion:1
Whether or not the sound has checked if it was occluded already.
uint8 bHasExternalSubtitles:1
If true, subtitles are being provided for the sound externally, so it still needs to make sure the sound plays to trigger the subtitles.
bool bHasNewBusSends
uint8 bHasVirtualized:1
Whether or not sound has been virtualized and then realized.
uint8 bIgnoreForFlushing:1
If true, this sound will not be stopped when flushing the audio device.
uint8 bIsAttenuationSettingsOverridden: 1
If this is true the active sound uses the overridden struct of the sound not the attenuation settings asset.
uint8 bIsFirstAttenuationUpdate: 1
uint8 bIsMusic:1
Whether or not this audio component is a music clip.
FThreadSafeBool bIsOccluded
whether we were occluded the last time we checked
uint8 bIsPaused:1
Whether or not the active sound is paused.
uint8 bIsPlayingAudio:1
Whether or not this active sound is playing audio, as in making audible sounds.
uint8 bIsPreviewSound:1
Whether or not this active sound is a preview sound.
uint8 bIsStopping:1
Whether or not the active sound is stopping.
uint8 bIsUISound:1
Whether or not this sound plays when the game is paused in the UI.
uint8 bLocationDefined:1
Whether the Location of the component is well defined.
uint8 bModulationRoutingUpdated: 1
uint8 bRadioFilterSelected:1
If true, the decision on whether to apply the radio filter has been made.
uint8 bReverb:1
Whether or not the audio component should be excluded from reverb EQ processing.
uint8 bShouldRemainActiveIfDropped:1
Whether the wave instances should remain active if they're dropped by the prioritization code.
bool bShouldSourceBufferListenerZeroBuffer = false
uint8 bShouldStopDueToMaxConcurrency:1
Whether or not to stop this active sound due to max concurrency.
uint8 bStartedWithinNonBinauralRadius: 1
uint8 bUpdateMultiEnvelopeValue:1
Whether or not this active sound will update the average envelope value of every wave instance that plays a sound source.
uint8 bUpdatePlaybackTime:1
Whether or not the active sound should update it's owning audio component's playback time.
uint8 bUpdatePlayPercentage:1
Whether or not this active sound will update play percentage.
uint8 bUpdateSingleEnvelopeValue:1
Whether or not this active sound will update the envelope value of every wave instance that plays a sound source.
uint8 bWarnedAboutOrphanedLooping:1
For debugging purposes, output to the log once that a looping sound has been orphaned.
Audio::FVolumeFader ComponentVolumeFader
Fader that tracks component volume.
TMap< FConcurrencyGroupID, FConcurrencySoundData > ConcurrencyGroupData
The concurrent groups that this sound is actively playing in.
TSet< TObjectPtr< USoundConcurrency > > ConcurrencySet
Optional USoundConcurrency to override for the sound.
float CurrentInteriorLPF
float CurrentInteriorVolume
FDynamicParameter CurrentOcclusionFilterFrequency
The interpolated parameter for the low-pass frequency due to occlusion.
FDynamicParameter CurrentOcclusionVolumeAttenuation
The interpolated parameter for the volume attenuation due to occlusion.
int32 EnvelopeFollowerAttackTime
int32 EnvelopeFollowerReleaseTime
EFadeOut FadeOut
Type of fade out currently being applied.
FAttenuationFocusData FocusData
Cached data pertaining to focus system updated each frame.
float HighPassFilterFrequency
The high-pass filter frequency to apply if bEnableHighPassFilter is true.
const FListener const FSoundAttenuationSettings & InAttenuationSettings
const FListener & InListener
FInteriorSettings InteriorSettings
Cache what volume settings we had last time so we don't have to search again if we didn't move.
FVector LastLocation
Location last time playback was updated.
float LastOcclusionCheckTime
Last time we checked for occlusion.
double LastUpdateTime
FSoundParseParameters const FListener & Listener
float LowPassFilterFrequency
The low-pass filter frequency to apply if bEnableLowPassFilter is true.
float MaxDistance
The max distance this sound will be audible.
float MaxSourceModulationValue
The source's final mixed Modulation value, used to evaluate VolumeConcurrency.
float MinCurrentPitch
FSoundModulationDefaultRoutingSettings ModulationRouting
TArray< TTuple< EBusSendType, FSoundSourceBusSendInfo > > NewBusSends
float OcclusionCheckInterval
The time in seconds with which to check for occlusion from its closest listener.
FSoundParseParameters & ParseParams
float PitchMultiplier
float PlaybackTime
Duration between now and when the sound has been started.
float PlaybackTimeNonVirtualized
If virtualized, duration between last time virtualized and now.
TArray< FAudioVolumeSubmixSendSettings > PreviousAudioVolumeSubmixSendSettings
float Priority
The product of the component priority and the USoundBase priority.
Audio::FQuartzQuantizedRequestData QuantizedRequestData
Quantization information.
float RequestedStartTime
FSoundParseParameters const FListener const FSoundAttenuationSettings * SettingsAttenuationNode = nullptr)
TArray< uint8 > SoundNodeData
TMap< UPTRINT, uint32 > SoundNodeOffsetMap
FSharedISourceBufferListenerPtr SourceBufferListener
Source buffer listener.
float SourceInteriorLPF
float SourceInteriorVolume
float SubtitlePriority
FTransform Transform
uint8 UserIndex
float VolumeConcurrency
The volume used to determine concurrency resolution for "quietest" active sound.
float VolumeMultiplier
Private Member Functions
void CheckOcclusion (const FVector ListenerLocation, const FVector SoundLocation, const FSoundAttenuationSettings *AttenuationSettingsPtr)
if OcclusionCheckInterval >= 0.0, periodically checks if the sound has become (un)occluded during playback When the interval is < 0.0, perform the initial occlusion check, but do not retest occlusion.
void GatherInteriorData (FSoundParseParameters &ParseParams)
Gather the interior settings needed for the sound.
float GetAttenuationFrequency (const FSoundAttenuationSettings *InSettings, const FAttenuationListenerData &ListenerData, const FVector2D &FrequencyRange, const FRuntimeFloatCurve &CustomCurve)
Helper function which retrieves attenuation frequency value for HPF and LPF distance-based filtering.
void HandleInteriorVolumes (FSoundParseParameters &ParseParams)
Apply the interior settings to the ambient sound as appropriate.
bool IsStopping () const
Whether or not the active sound is stopping.
void MarkPendingDestroy (bool bDestroyNow)
Marks the active sound as pending delete and begins termination of internal resources.
void UpdateConcurrencyVolumeScalars (const float DeltaTime)
Updates ramping concurrency volume scalars.
bool UpdateStoppingSources (uint64 CurrentTick, bool bEnsureStopped)
Called when an active sound has been stopped but needs to update it's stopping sounds.
Private Attributes
uint64 AudioComponentID
FName AudioComponentName
FName AudioComponentUserID
uint8 bEnableVirtualizationModeOverride: 1
TArray< FSoundSourceBusSendInfo > BusSendsOverride [(int32) EBusSendType::Count]
Optional override for the source bus sends for the sound.
int32 ClosestListenerIndex = INDEX_NONE
Cached index to the closest listener.
TSharedPtr< Audio::IParameterTransmitter > InstanceTransmitter
uint32 OwnerID
FName OwnerName
uint32 PlayOrder
TObjectPtr< USoundBase > Sound
TObjectPtr< USoundAttenuation > SoundAttenuation
TObjectPtr< USoundClass > SoundClassOverride
Optional SoundClass to override for the sound.
TArray< FSoundSubmixSendInfo > SoundSubmixSendsOverride
Optional override the submix sends for the sound.
TObjectPtr< USoundEffectSourcePresetChain > SourceEffectChain
EVirtualizationMode VirtualizationModeOverride
TMap< UPTRINT, FWaveInstance * > WaveInstances
TWeakObjectPtr< UWorld > World
uint32 WorldID
Static Private Attributes
static FTraceDelegate ActiveSoundTraceDelegate
static TMap< FTraceHandle, FAsyncTraceDetails > TraceToActiveSoundMap
Friends
class FAudioDevice
This is a friend so the audio device can call Stop() on the active sound.
FArchive & operator<< (FArchive &Ar, FActiveSound *ActiveSound)
Friend archive function used for serialization.
Detailed Description
Definition at line 283 of file ActiveSound.h.
Member Enumeration Documentation
EFadeOut
enum class FActiveSound::EFadeOut : uint8 strong
Enumerator
None
User
Concurrency
Definition at line 439 of file ActiveSound.h.
Constructor & Destructor Documentation
FActiveSound() [1/2]
FActiveSound::FActiveSound ()
Referenced by FActiveSound(), CreateVirtualCopy(), operator<<, and SetAudioComponent().
FActiveSound() [2/2]
FActiveSound::FActiveSound (const FActiveSound &)
References FActiveSound().
~FActiveSound()
FActiveSound::~FActiveSound ()
Member Function Documentation
AddModulationRouting()
void FActiveSound::AddModulationRouting (const TSet< TObjectPtr< USoundModulatorBase > > & NewModulators, EModulationDestination Destination)
AddReferencedObjects()
void FActiveSound::AddReferencedObjects (FReferenceCollector & Collector)
AddVolumeSubmixSends()
void FActiveSound::AddVolumeSubmixSends (FSoundParseParameters & ParseParams, EAudioVolumeLocationState LocationState)
Apply the submix sends to our parse params as appropriate.
References AddVolumeSubmixSends(), and ParseParams.
Referenced by AddVolumeSubmixSends().
AddWaveInstance()
FWaveInstance & FActiveSound::AddWaveInstance (const UPTRINT WaveInstanceHash)
Add newly created wave instance to active sound.
ApplyRadioFilter()
void FActiveSound::ApplyRadioFilter (const FSoundParseParameters & ParseParams)
Check whether to apply the radio filter.
References ParseParams.
CanDelete()
bool FActiveSound::CanDelete () const inline
Returns whether or not the active sound can be deleted.
Definition at line 372 of file ActiveSound.h.
References bAsyncOcclusionPending.
CheckOcclusion()
void FActiveSound::CheckOcclusion (const FVector ListenerLocation, const FVector SoundLocation, const FSoundAttenuationSettings * AttenuationSettingsPtr) private
if OcclusionCheckInterval >= 0.0, periodically checks if the sound has become (un)occluded during playback When the interval is < 0.0, perform the initial occlusion check, but do not retest occlusion.
Parameters
ListenerLocation - location of the closest listener to the sound
SoundLocation - location of the sound
AttenuationSettingsPtr - Attenuation settings used (subject to various overrides)
References FVector.
ClearAudioComponent()
void FActiveSound::ClearAudioComponent ()
ClearTransmitter()
void FActiveSound::ClearTransmitter () inline
Definition at line 434 of file ActiveSound.h.
References InstanceTransmitter.
ClearVirtualizationModeOverride()
void FActiveSound::ClearVirtualizationModeOverride ()
Stop using the Virtualization Mode Override.
CollectAttenuationShapesForVisualization()
void FActiveSound::CollectAttenuationShapesForVisualization (TMultiMap< EAttenuationShape::Type, FBaseAttenuationSettings::AttenuationShapeDetails > & ShapeDetailsMap) const
CreateVirtualCopy()
FActiveSound * FActiveSound::CreateVirtualCopy (const FActiveSound & ActiveSoundToCopy, FAudioDevice & AudioDevice) static
References FActiveSound(), AudioDevice, and FAudioDevice.
FindClosestListener() [1/2]
int32 FActiveSound::FindClosestListener () const
FindClosestListener() [2/2]
int32 FActiveSound::FindClosestListener (const TArray< struct FListener > & InListeners) const
FindWaveInstance()
FWaveInstance * FActiveSound::FindWaveInstance (const UPTRINT WaveInstanceHash)
Find an existing waveinstance attached to this audio component (if any)
GatherInteriorData()
void FActiveSound::GatherInteriorData (FSoundParseParameters & ParseParams) private
Gather the interior settings needed for the sound.
References ParseParams.
GetAlwaysPlay()
bool FActiveSound::GetAlwaysPlay () const
Returns whether or not sound or any active wave instances it manages are set to always play.
References GetAlwaysPlay().
Referenced by GetAlwaysPlay().
GetAttenuationFrequency()
float FActiveSound::GetAttenuationFrequency (const FSoundAttenuationSettings * InSettings, const FAttenuationListenerData & ListenerData, const FVector2D & FrequencyRange, const FRuntimeFloatCurve & CustomCurve) private
Helper function which retrieves attenuation frequency value for HPF and LPF distance-based filtering.
GetAudioComponentID()
uint64 FActiveSound::GetAudioComponentID () const inline
Definition at line 320 of file ActiveSound.h.
References AudioComponentID.
GetAudioComponentName()
FString FActiveSound::GetAudioComponentName () const
GetAudioComponentUserID()
FName FActiveSound::GetAudioComponentUserID () const inline
Definition at line 321 of file ActiveSound.h.
References AudioComponentUserID.
GetBusSends()
void FActiveSound::GetBusSends (EBusSendType BusSendType, TArray< FSoundSourceBusSendInfo > & OutSends) const
Gets the sound source bus sends to use for this sound instance.
GetClosestListenerIndex()
int32 FActiveSound::GetClosestListenerIndex () const
GetConcurrencyFadeDuration()
bool FActiveSound::GetConcurrencyFadeDuration (float & OutFadeDuration) const
GetConcurrencyHandles()
void FActiveSound::GetConcurrencyHandles (TArray< FConcurrencyHandle > & OutConcurrencyHandles) const
Gets the sound concurrency handles applicable to this sound instance.
GetConcurrencyPriority()
float FActiveSound::GetConcurrencyPriority () const
The priority used for concurrency calculations.
GetEffectiveVolumeModulators()
TArray< TSet< TObjectPtr< USoundModulatorBase > > > FActiveSound::GetEffectiveVolumeModulators () const
Creates a copy of the modulation configuration for all WaveInstances on this ActiveSound.
Each element in the array corresponds to a Wave Instance's modulation settings, factoring in the routing settings on the wave instances.
GetHighestPriority()
float FActiveSound::GetHighestPriority (bool bIgnoreAlwaysPlay = false) const
Returns the highest effective priority of the child wave instances.
If bIgnoreAlwaysPlay set to true, gives highest priority disregarding always play priority override.
References GetHighestPriority().
Referenced by GetHighestPriority().
GetInstanceID()
uint32 FActiveSound::GetInstanceID () const inline
Returns a unique identifier for this active sound object.
Definition at line 318 of file ActiveSound.h.
References PlayOrder.
GetNewBusSends()
TArray< TTuple< EBusSendType, FSoundSourceBusSendInfo > > const & FActiveSound::GetNewBusSends () const
Lets the audio thread know if additional Source Bus Send information has been added.
Returns
the array of Sound Bus Sends that have not yet been added to the render thread
GetObjectId()
uint32 FActiveSound::GetObjectId () const inline override
Definition at line 311 of file ActiveSound.h.
References INDEX_NONE, and Sound.
GetOwnerID()
FSoundOwnerObjectID FActiveSound::GetOwnerID () const inline
Returns the unique ID of the active sound's owner if it exists.
Returns 0 if the sound doesn't have an owner.
Definition at line 768 of file ActiveSound.h.
References OwnerID.
GetOwnerName()
FString FActiveSound::GetOwnerName () const
GetPitch()
float FActiveSound::GetPitch () const inline
Definition at line 340 of file ActiveSound.h.
References PitchMultiplier.
GetPlayCount()
int32 FActiveSound::GetPlayCount () const override
GetPlayOrder()
uint32 FActiveSound::GetPlayOrder () const inline
Definition at line 313 of file ActiveSound.h.
References PlayOrder.
GetSound()
USoundBase * FActiveSound::GetSound () const inline
Definition at line 345 of file ActiveSound.h.
References Sound.
GetSoundClass()
USoundClass * FActiveSound::GetSoundClass () const
Get the sound class to apply on this sound instance.
GetSoundSubmix()
USoundSubmixBase * FActiveSound::GetSoundSubmix () const
Get the sound submix to use for this sound instance.
GetSoundSubmixSends()
void FActiveSound::GetSoundSubmixSends (TArray< FSoundSubmixSendInfo > & OutSends) const
Gets the sound submix sends to use for this sound instance.
GetSourceEffectChain()
USoundEffectSourcePresetChain * FActiveSound::GetSourceEffectChain () const inline
Definition at line 348 of file ActiveSound.h.
References Sound, SourceEffectChain, and ToRawPtr().
GetTotalConcurrencyVolumeScale()
float FActiveSound::GetTotalConcurrencyVolumeScale () const
Gets total concurrency gain stage based on all concurrency memberships of sound.
GetTransmitter() [1/2]
Audio::IParameterTransmitter * FActiveSound::GetTransmitter () inline
Definition at line 424 of file ActiveSound.h.
References InstanceTransmitter.
GetTransmitter() [2/2]
const Audio::IParameterTransmitter * FActiveSound::GetTransmitter () const inline
Definition at line 429 of file ActiveSound.h.
References InstanceTransmitter.
GetVirtualizationMode()
EVirtualizationMode FActiveSound::GetVirtualizationMode () const
GetVolume()
float FActiveSound::GetVolume () const
Gets volume product all gain stages pertaining to active sound.
GetWaveInstances()
const TMap< UPTRINT, FWaveInstance * > & FActiveSound::GetWaveInstances () const inline
Definition at line 687 of file ActiveSound.h.
References WaveInstances.
GetWeakWorld()
TWeakObjectPtr< UWorld > FActiveSound::GetWeakWorld () const inline
Definition at line 330 of file ActiveSound.h.
References World.
GetWorld()
UWorld * FActiveSound::GetWorld () const inline
Definition at line 331 of file ActiveSound.h.
References World.
GetWorldID()
uint32 FActiveSound::GetWorldID () const inline
Definition at line 329 of file ActiveSound.h.
References WorldID.
HandleInteriorVolumes()
void FActiveSound::HandleInteriorVolumes (FSoundParseParameters & ParseParams) private
Apply the interior settings to the ambient sound as appropriate.
References ParseParams.
HasNewBusSends()
bool FActiveSound::HasNewBusSends () const
Checks whether there are Source Bus Sends that have not yet been updated.
Returns
true when there are new Source Bus Sends, false otherwise
IsLooping()
bool FActiveSound::IsLooping () const inline
Whether or not the active sound is a looping sound.
Definition at line 375 of file ActiveSound.h.
References Sound.
Referenced by IsOneShot().
IsOneShot()
bool FActiveSound::IsOneShot () const inline
Whether or not the active sound a one-shot sound.
Definition at line 378 of file ActiveSound.h.
References IsLooping().
IsPlayingAudio()
bool FActiveSound::IsPlayingAudio () const inline
Whether or not the active sound is currently playing audible sound.
Definition at line 381 of file ActiveSound.h.
References bIsPlayingAudio.
IsPlayWhenSilent()
bool FActiveSound::IsPlayWhenSilent () const
Whether or not sound reference is valid and set to play when silent.
IsPreviewSound()
bool FActiveSound::IsPreviewSound () const inline override
Definition at line 314 of file ActiveSound.h.
References bIsPreviewSound.
IsStopping()
bool FActiveSound::IsStopping () const inline private
Whether or not the active sound is stopping.
Definition at line 837 of file ActiveSound.h.
References bIsStopping.
MarkPendingDestroy()
void FActiveSound::MarkPendingDestroy (bool bDestroyNow) private
Marks the active sound as pending delete and begins termination of internal resources.
Only to be called from the owning audio device.
OcclusionTraceDone()
void FActiveSound::OcclusionTraceDone (const FTraceHandle & TraceHandle, FTraceDatum & TraceDatum) static
Delegate callback function when an async occlusion trace completes.
OverrideVirtualizationMode()
void FActiveSound::OverrideVirtualizationMode (EVirtualizationMode Mode)
Override the Virtualization settings set on Audio Component/Sound.
ParseAttenuation()
void FActiveSound::ParseAttenuation (FSoundParseParameters & OutParseParams, int32 ListenerIndex, const FSoundAttenuationSettings & InAttenuationSettings)
Applies the active sound's attenuation settings to the input parse params using the given listener.
References InAttenuationSettings, and ParseAttenuation().
Referenced by ParseAttenuation().
RemoveModulationRouting()
void FActiveSound::RemoveModulationRouting (const TSet< TObjectPtr< USoundModulatorBase > > & NewModulators, EModulationDestination Destination)
RemoveWaveInstance()
void FActiveSound::RemoveWaveInstance (const UPTRINT WaveInstanceHash)
ResetNewBusSends()
void FActiveSound::ResetNewBusSends ()
Resets internal data of new Source Bus Sends.
SetAttenuationSettingsAsset()
void FActiveSound::SetAttenuationSettingsAsset (TObjectPtr< USoundAttenuation > InSoundAttenuation)
SetAttenuationSettingsOverride()
void FActiveSound::SetAttenuationSettingsOverride (bool bInIsAttenuationSettingsOverridden)
SetAudioComponent() [1/2]
void FActiveSound::SetAudioComponent (const FActiveSound & ActiveSound)
References FActiveSound().
SetAudioComponent() [2/2]
void FActiveSound::SetAudioComponent (const UAudioComponent & Component)
References Component.
SetAudioDevice()
void FActiveSound::SetAudioDevice (FAudioDevice * InAudioDevice) inline
Definition at line 358 of file ActiveSound.h.
References AudioDevice, and FAudioDevice.
SetNewModulationRouting()
void FActiveSound::SetNewModulationRouting (const FSoundModulationDefaultRoutingSettings & NewRouting)
SetOwner()
void FActiveSound::SetOwner (const AActor * Owner)
References Owner.
SetPitch()
void FActiveSound::SetPitch (float Value)
References Value.
SetSound()
void FActiveSound::SetSound (USoundBase * InSound)
SetSoundClass()
void FActiveSound::SetSoundClass (USoundClass * SoundClass)
SetSourceBusSend()
void FActiveSound::SetSourceBusSend (EBusSendType BusSendType, const FSoundSourceBusSendInfo & SourceBusSendInfo)
Sets the amount of audio from this active sound to send to the source bus.
References SetSourceBusSend().
Referenced by SetSourceBusSend().
SetSourceEffectChain()
void FActiveSound::SetSourceEffectChain (USoundEffectSourcePresetChain * InSourceEffectChain)
SetSourceListener()
void FActiveSound::SetSourceListener (FSharedISourceBufferListenerPtr InListener, bool bShouldZeroBuffer) inline
Definition at line 363 of file ActiveSound.h.
References bShouldSourceBufferListenerZeroBuffer, InListener, and SourceBufferListener.
SetSubmixSend()
void FActiveSound::SetSubmixSend (const FSoundSubmixSendInfo & SubmixSendInfo)
Sets the amount of audio from this active sound to send to the submix.
References SetSubmixSend().
Referenced by SetSubmixSend().
SetVolume()
void FActiveSound::SetVolume (float Value)
References Value.
SetWorld()
void FActiveSound::SetWorld (UWorld * World)
References World.
Stop()
void FActiveSound::Stop () override
UE_DEPRECATED() [1/2]
FActiveSound::UE_DEPRECATED (4. 25, "Use ParseAttenuation that passes a ListenerIndex instead") &
Applies the active sound's attenuation settings to the input parse params using the given listener.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FActiveSound::UE_DEPRECATED (4. 25, "Use UpdateAttenuation that passes a ListenerIndex instead")
Updates the active sound's attenuation settings to the input parse params using the given listener.
References UE_DEPRECATED().
UpdateAttenuation()
void FActiveSound::UpdateAttenuation (float DeltaTime, FSoundParseParameters & ParseParams, int32 ListenerIndex, const FSoundAttenuationSettings * SettingsAttenuationNode = nullptr)
Updates the active sound's attenuation settings to the input parse params using the given listener.
References DeltaTime, ParseParams, SettingsAttenuationNode, and UpdateAttenuation().
Referenced by UpdateAttenuation().
UpdateConcurrencyVolumeScalars()
void FActiveSound::UpdateConcurrencyVolumeScalars (const float DeltaTime) private
Updates ramping concurrency volume scalars.
References DeltaTime.
UpdateFocusData()
void FActiveSound::UpdateFocusData (float DeltaTime, const FAttenuationListenerData & ListenerData, FAttenuationFocusData * OutFocusData = nullptr)
Updates the provided focus data using the local.
References DeltaTime, and UpdateFocusData().
Referenced by UpdateFocusData().
UpdateInterfaceParameters()
void FActiveSound::UpdateInterfaceParameters (const TArray< FListener > & InListeners)
UpdateStoppingSources()
bool FActiveSound::UpdateStoppingSources (uint64 CurrentTick, bool bEnsureStopped) private
Called when an active sound has been stopped but needs to update it's stopping sounds.
Returns true when stopping sources have finished stopping.
UpdateWaveInstances()
void FActiveSound::UpdateWaveInstances (TArray< FWaveInstance * > & OutWaveInstances, const float DeltaTime)
References DeltaTime.
Friends And Related Symbol Documentation
FAudioDevice
friend class FAudioDevice friend
This is a friend so the audio device can call Stop() on the active sound.
Definition at line 828 of file ActiveSound.h.
References FAudioDevice.
Referenced by CreateVirtualCopy(), FAudioDevice, and SetAudioDevice().
operator<<
FArchive & operator<< (FArchive & Ar, FActiveSound * ActiveSound) friend
Friend archive function used for serialization.
References FActiveSound(), and Ar.
Field Documentation
ActiveSoundTraceDelegate
FTraceDelegate FActiveSound::ActiveSoundTraceDelegate static private
Definition at line 822 of file ActiveSound.h.
AttenuationSettings
FSoundAttenuationSettings FActiveSound::AttenuationSettings
Definition at line 633 of file ActiveSound.h.
AudioComponentID
uint64 FActiveSound::AudioComponentID private
Definition at line 301 of file ActiveSound.h.
Referenced by GetAudioComponentID().
AudioComponentName
FName FActiveSound::AudioComponentName private
Definition at line 305 of file ActiveSound.h.
AudioComponentUserID
FName FActiveSound::AudioComponentUserID private
Definition at line 302 of file ActiveSound.h.
Referenced by GetAudioComponentUserID().
AudioDevice
FAudioDevice* FActiveSound::AudioDevice
Definition at line 397 of file ActiveSound.h.
Referenced by CreateVirtualCopy(), and SetAudioDevice().
AudioVolumeID
uint32 FActiveSound::AudioVolumeID
Definition at line 647 of file ActiveSound.h.
AudioVolumeSubmixSendSettings
TArray<FAudioVolumeSubmixSendSettings> FActiveSound::AudioVolumeSubmixSendSettings
Definition at line 644 of file ActiveSound.h.
bAllowSpatialization
uint8 FActiveSound::bAllowSpatialization
Is this sound allowed to be spatialized?
Definition at line 455 of file ActiveSound.h.
bAlwaysPlay
uint8 FActiveSound::bAlwaysPlay
Whether to artificially prioritize the component to play.
Definition at line 494 of file ActiveSound.h.
bApplyInteriorVolumes
uint8 FActiveSound::bApplyInteriorVolumes
Whether some part of this sound will want interior sounds to be applied.
Definition at line 515 of file ActiveSound.h.
bApplyRadioFilter
uint8 FActiveSound::bApplyRadioFilter
If true, this sound will not be stopped when flushing the audio device.
Definition at line 479 of file ActiveSound.h.
bAsyncOcclusionPending
FThreadSafeBool FActiveSound::bAsyncOcclusionPending
Whether or not there is an async occlusion trace pending.
Definition at line 573 of file ActiveSound.h.
Referenced by CanDelete().
bCenterChannelOnly
uint8 FActiveSound::bCenterChannelOnly
Whether or not this sound class forces sounds to the center channel.
Definition at line 506 of file ActiveSound.h.
bEnableBusSendRoutingOverride
uint8 FActiveSound::bEnableBusSendRoutingOverride
What the value of the enablement overrides are.
Definition at line 552 of file ActiveSound.h.
bEnableHighPassFilter
uint8 FActiveSound::bEnableHighPassFilter
Whether or not we have a low-pass filter enabled on this active sound.
Definition at line 526 of file ActiveSound.h.
bEnableLowPassFilter
uint8 FActiveSound::bEnableLowPassFilter
Whether or not we have a low-pass filter enabled on this active sound.
Definition at line 523 of file ActiveSound.h.
bEnableMainSubmixOutputOverride
uint8 FActiveSound::bEnableMainSubmixOutputOverride
Definition at line 553 of file ActiveSound.h.
bEnableSubmixSendRoutingOverride
uint8 FActiveSound::bEnableSubmixSendRoutingOverride
Definition at line 554 of file ActiveSound.h.
bEnableVirtualizationModeOverride
uint8 FActiveSound::bEnableVirtualizationModeOverride private
Definition at line 421 of file ActiveSound.h.
bFinished
uint8 FActiveSound::bFinished
Whether the current component has finished playing.
Definition at line 464 of file ActiveSound.h.
bGotInteriorSettings
uint8 FActiveSound::bGotInteriorSettings
Whether we have queried for the interior settings at least once.
Definition at line 512 of file ActiveSound.h.
bHandleSubtitles
uint8 FActiveSound::bHandleSubtitles
If true, the AudioComponent will be notified when a Wave is started to handle subtitles.
Definition at line 482 of file ActiveSound.h.
bHasActiveBusSendRoutingOverride
uint8 FActiveSound::bHasActiveBusSendRoutingOverride
Whether or not we are overriding the routing enablement options on sounds.
Definition at line 547 of file ActiveSound.h.
bHasActiveMainSubmixOutputOverride
uint8 FActiveSound::bHasActiveMainSubmixOutputOverride
Definition at line 548 of file ActiveSound.h.
bHasActiveSubmixSendRoutingOverride
uint8 FActiveSound::bHasActiveSubmixSendRoutingOverride
Definition at line 549 of file ActiveSound.h.
bHasAttenuationSettings
uint8 FActiveSound::bHasAttenuationSettings
Does this sound have attenuation settings specified.
Definition at line 458 of file ActiveSound.h.
bHasCheckedOcclusion
uint8 FActiveSound::bHasCheckedOcclusion
Whether or not the sound has checked if it was occluded already.
Used to initialize a sound as occluded and bypassing occlusion interpolation.
Definition at line 452 of file ActiveSound.h.
bHasExternalSubtitles
uint8 FActiveSound::bHasExternalSubtitles
If true, subtitles are being provided for the sound externally, so it still needs to make sure the sound plays to trigger the subtitles.
Definition at line 485 of file ActiveSound.h.
bHasNewBusSends
bool FActiveSound::bHasNewBusSends
Definition at line 664 of file ActiveSound.h.
bHasVirtualized
uint8 FActiveSound::bHasVirtualized
Whether or not sound has been virtualized and then realized.
Definition at line 473 of file ActiveSound.h.
bIgnoreForFlushing
uint8 FActiveSound::bIgnoreForFlushing
If true, this sound will not be stopped when flushing the audio device.
Definition at line 491 of file ActiveSound.h.
bIsAttenuationSettingsOverridden
uint8 FActiveSound::bIsAttenuationSettingsOverridden
If this is true the active sound uses the overridden struct of the sound not the attenuation settings asset.
Definition at line 562 of file ActiveSound.h.
bIsFirstAttenuationUpdate
uint8 FActiveSound::bIsFirstAttenuationUpdate
Definition at line 556 of file ActiveSound.h.
bIsMusic
uint8 FActiveSound::bIsMusic
Whether or not this audio component is a music clip.
Definition at line 500 of file ActiveSound.h.
bIsOccluded
FThreadSafeBool FActiveSound::bIsOccluded
whether we were occluded the last time we checked
Definition at line 570 of file ActiveSound.h.
bIsPaused
uint8 FActiveSound::bIsPaused
Whether or not the active sound is paused.
Independently set vs global pause or unpause.
Definition at line 467 of file ActiveSound.h.
bIsPlayingAudio
uint8 FActiveSound::bIsPlayingAudio
Whether or not this active sound is playing audio, as in making audible sounds.
Definition at line 541 of file ActiveSound.h.
Referenced by IsPlayingAudio().
bIsPreviewSound
uint8 FActiveSound::bIsPreviewSound
Whether or not this active sound is a preview sound.
Definition at line 509 of file ActiveSound.h.
Referenced by IsPreviewSound().
bIsStopping
uint8 FActiveSound::bIsStopping
Whether or not the active sound is stopping.
Definition at line 544 of file ActiveSound.h.
Referenced by IsStopping().
bIsUISound
uint8 FActiveSound::bIsUISound
Whether or not this sound plays when the game is paused in the UI.
Definition at line 497 of file ActiveSound.h.
bLocationDefined
uint8 FActiveSound::bLocationDefined
Whether the Location of the component is well defined.
Definition at line 488 of file ActiveSound.h.
bModulationRoutingUpdated
uint8 FActiveSound::bModulationRoutingUpdated
Definition at line 559 of file ActiveSound.h.
bRadioFilterSelected
uint8 FActiveSound::bRadioFilterSelected
If true, the decision on whether to apply the radio filter has been made.
Definition at line 476 of file ActiveSound.h.
bReverb
uint8 FActiveSound::bReverb
Whether or not the audio component should be excluded from reverb EQ processing.
Definition at line 503 of file ActiveSound.h.
bShouldRemainActiveIfDropped
uint8 FActiveSound::bShouldRemainActiveIfDropped
Whether the wave instances should remain active if they're dropped by the prioritization code.
Useful for e.g. vehicle sounds that shouldn't cut out.
Definition at line 461 of file ActiveSound.h.
bShouldSourceBufferListenerZeroBuffer
bool FActiveSound::bShouldSourceBufferListenerZeroBuffer = false
Definition at line 640 of file ActiveSound.h.
Referenced by SetSourceListener().
bShouldStopDueToMaxConcurrency
uint8 FActiveSound::bShouldStopDueToMaxConcurrency
Whether or not to stop this active sound due to max concurrency.
Definition at line 470 of file ActiveSound.h.
bStartedWithinNonBinauralRadius
uint8 FActiveSound::bStartedWithinNonBinauralRadius
Definition at line 557 of file ActiveSound.h.
bUpdateMultiEnvelopeValue
uint8 FActiveSound::bUpdateMultiEnvelopeValue
Whether or not this active sound will update the average envelope value of every wave instance that plays a sound source.
Based on set delegates on audio component.
Definition at line 535 of file ActiveSound.h.
bUpdatePlaybackTime
uint8 FActiveSound::bUpdatePlaybackTime
Whether or not the active sound should update it's owning audio component's playback time.
Definition at line 538 of file ActiveSound.h.
bUpdatePlayPercentage
uint8 FActiveSound::bUpdatePlayPercentage
Whether or not this active sound will update play percentage.
Based on set delegates on audio component.
Definition at line 529 of file ActiveSound.h.
bUpdateSingleEnvelopeValue
uint8 FActiveSound::bUpdateSingleEnvelopeValue
Whether or not this active sound will update the envelope value of every wave instance that plays a sound source.
Based on set delegates on audio component.
Definition at line 532 of file ActiveSound.h.
BusSendsOverride
TArray<FSoundSourceBusSendInfo> FActiveSound::BusSendsOverride[(int32) EBusSendType::Count] private
Optional override for the source bus sends for the sound.
Definition at line 413 of file ActiveSound.h.
bWarnedAboutOrphanedLooping
uint8 FActiveSound::bWarnedAboutOrphanedLooping
For debugging purposes, output to the log once that a looping sound has been orphaned.
Definition at line 519 of file ActiveSound.h.
ClosestListenerIndex
int32 FActiveSound::ClosestListenerIndex = INDEX_NONE private
Cached index to the closest listener.
So we don't have to do the work to find it twice.
Definition at line 825 of file ActiveSound.h.
ComponentVolumeFader
Audio::FVolumeFader FActiveSound::ComponentVolumeFader
Fader that tracks component volume.
Definition at line 594 of file ActiveSound.h.
ConcurrencyGroupData
TMap<FConcurrencyGroupID, FConcurrencySoundData> FActiveSound::ConcurrencyGroupData
The concurrent groups that this sound is actively playing in.
Definition at line 400 of file ActiveSound.h.
ConcurrencySet
TSet<TObjectPtr<USoundConcurrency> > FActiveSound::ConcurrencySet
Optional USoundConcurrency to override for the sound.
Definition at line 403 of file ActiveSound.h.
CurrentInteriorLPF
float FActiveSound::CurrentInteriorLPF
Definition at line 654 of file ActiveSound.h.
CurrentInteriorVolume
float FActiveSound::CurrentInteriorVolume
Definition at line 653 of file ActiveSound.h.
CurrentOcclusionFilterFrequency
FDynamicParameter FActiveSound::CurrentOcclusionFilterFrequency
The interpolated parameter for the low-pass frequency due to occlusion.
Definition at line 597 of file ActiveSound.h.
CurrentOcclusionVolumeAttenuation
FDynamicParameter FActiveSound::CurrentOcclusionVolumeAttenuation
The interpolated parameter for the volume attenuation due to occlusion.
Definition at line 600 of file ActiveSound.h.
EnvelopeFollowerAttackTime
int32 FActiveSound::EnvelopeFollowerAttackTime
Definition at line 657 of file ActiveSound.h.
EnvelopeFollowerReleaseTime
int32 FActiveSound::EnvelopeFollowerReleaseTime
Definition at line 658 of file ActiveSound.h.
FadeOut
EFadeOut FActiveSound::FadeOut
Type of fade out currently being applied.
Definition at line 567 of file ActiveSound.h.
FocusData
FAttenuationFocusData FActiveSound::FocusData
Cached data pertaining to focus system updated each frame.
Definition at line 628 of file ActiveSound.h.
HighPassFilterFrequency
float FActiveSound::HighPassFilterFrequency
The high-pass filter frequency to apply if bEnableHighPassFilter is true.
Definition at line 591 of file ActiveSound.h.
InAttenuationSettings
const FListener const FSoundAttenuationSettings& FActiveSound::InAttenuationSettings
Definition at line 780 of file ActiveSound.h.
Referenced by ParseAttenuation().
InListener
const FListener& FActiveSound::InListener
Definition at line 780 of file ActiveSound.h.
Referenced by SetSourceListener().
InstanceTransmitter
TSharedPtr<Audio::IParameterTransmitter> FActiveSound::InstanceTransmitter private
Definition at line 417 of file ActiveSound.h.
Referenced by ClearTransmitter(), GetTransmitter(), and GetTransmitter().
InteriorSettings
FInteriorSettings FActiveSound::InteriorSettings
Cache what volume settings we had last time so we don't have to search again if we didn't move.
Definition at line 643 of file ActiveSound.h.
LastLocation
FVector FActiveSound::LastLocation
Location last time playback was updated.
Definition at line 631 of file ActiveSound.h.
LastOcclusionCheckTime
float FActiveSound::LastOcclusionCheckTime
Last time we checked for occlusion.
Definition at line 618 of file ActiveSound.h.
LastUpdateTime
double FActiveSound::LastUpdateTime
Definition at line 650 of file ActiveSound.h.
Listener
FSoundParseParameters const FListener& FActiveSound::Listener
Definition at line 801 of file ActiveSound.h.
LowPassFilterFrequency
float FActiveSound::LowPassFilterFrequency
The low-pass filter frequency to apply if bEnableLowPassFilter is true.
Definition at line 588 of file ActiveSound.h.
MaxDistance
float FActiveSound::MaxDistance
The max distance this sound will be audible.
Definition at line 621 of file ActiveSound.h.
MaxSourceModulationValue
float FActiveSound::MaxSourceModulationValue
The source's final mixed Modulation value, used to evaluate VolumeConcurrency.
Definition at line 612 of file ActiveSound.h.
MinCurrentPitch
float FActiveSound::MinCurrentPitch
Definition at line 581 of file ActiveSound.h.
ModulationRouting
FSoundModulationDefaultRoutingSettings FActiveSound::ModulationRouting
Definition at line 669 of file ActiveSound.h.
NewBusSends
TArray<TTuple<EBusSendType, FSoundSourceBusSendInfo> > FActiveSound::NewBusSends
Definition at line 667 of file ActiveSound.h.
OcclusionCheckInterval
float FActiveSound::OcclusionCheckInterval
The time in seconds with which to check for occlusion from its closest listener.
Definition at line 615 of file ActiveSound.h.
OwnerID
uint32 FActiveSound::OwnerID private
Definition at line 303 of file ActiveSound.h.
Referenced by GetOwnerID().
OwnerName
FName FActiveSound::OwnerName private
Definition at line 306 of file ActiveSound.h.
ParseParams
FSoundParseParameters& FActiveSound::ParseParams
Definition at line 801 of file ActiveSound.h.
Referenced by AddVolumeSubmixSends(), ApplyRadioFilter(), GatherInteriorData(), HandleInteriorVolumes(), and UpdateAttenuation().
PitchMultiplier
float FActiveSound::PitchMultiplier
Definition at line 585 of file ActiveSound.h.
Referenced by GetPitch().
PlaybackTime
float FActiveSound::PlaybackTime
Duration between now and when the sound has been started.
Definition at line 576 of file ActiveSound.h.
PlaybackTimeNonVirtualized
float FActiveSound::PlaybackTimeNonVirtualized
If virtualized, duration between last time virtualized and now.
Definition at line 579 of file ActiveSound.h.
PlayOrder
uint32 FActiveSound::PlayOrder private
Definition at line 308 of file ActiveSound.h.
Referenced by GetInstanceID(), and GetPlayOrder().
PreviousAudioVolumeSubmixSendSettings
TArray<FAudioVolumeSubmixSendSettings> FActiveSound::PreviousAudioVolumeSubmixSendSettings
Definition at line 645 of file ActiveSound.h.
Priority
float FActiveSound::Priority
The product of the component priority and the USoundBase priority.
Definition at line 605 of file ActiveSound.h.
QuantizedRequestData
Audio::FQuartzQuantizedRequestData FActiveSound::QuantizedRequestData
Quantization information.
Definition at line 636 of file ActiveSound.h.
RequestedStartTime
float FActiveSound::RequestedStartTime
Definition at line 582 of file ActiveSound.h.
SettingsAttenuationNode
FSoundParseParameters const FListener const FSoundAttenuationSettings* FActiveSound::SettingsAttenuationNode = nullptr)
Definition at line 801 of file ActiveSound.h.
Referenced by UpdateAttenuation().
Sound
TObjectPtr<USoundBase> FActiveSound::Sound private
Definition at line 297 of file ActiveSound.h.
Referenced by GetObjectId(), GetSound(), GetSourceEffectChain(), and IsLooping().
SoundAttenuation
TObjectPtr<USoundAttenuation> FActiveSound::SoundAttenuation private
Definition at line 299 of file ActiveSound.h.
SoundClassOverride
TObjectPtr<USoundClass> FActiveSound::SoundClassOverride private
Optional SoundClass to override for the sound.
Definition at line 407 of file ActiveSound.h.
SoundNodeData
TArray<uint8> FActiveSound::SoundNodeData
Definition at line 661 of file ActiveSound.h.
SoundNodeOffsetMap
TMap<UPTRINT,uint32> FActiveSound::SoundNodeOffsetMap
Definition at line 660 of file ActiveSound.h.
SoundSubmixSendsOverride
TArray<FSoundSubmixSendInfo> FActiveSound::SoundSubmixSendsOverride private
Optional override the submix sends for the sound.
Definition at line 410 of file ActiveSound.h.
SourceBufferListener
FSharedISourceBufferListenerPtr FActiveSound::SourceBufferListener
Source buffer listener.
Definition at line 639 of file ActiveSound.h.
Referenced by SetSourceListener().
SourceEffectChain
TObjectPtr<USoundEffectSourcePresetChain> FActiveSound::SourceEffectChain private
Definition at line 298 of file ActiveSound.h.
Referenced by GetSourceEffectChain().
SourceInteriorLPF
float FActiveSound::SourceInteriorLPF
Definition at line 652 of file ActiveSound.h.
SourceInteriorVolume
float FActiveSound::SourceInteriorVolume
Definition at line 651 of file ActiveSound.h.
SubtitlePriority
float FActiveSound::SubtitlePriority
Definition at line 602 of file ActiveSound.h.
TraceToActiveSoundMap
TMap<FTraceHandle, FAsyncTraceDetails> FActiveSound::TraceToActiveSoundMap static private
Definition at line 820 of file ActiveSound.h.
Transform
FTransform FActiveSound::Transform
Definition at line 623 of file ActiveSound.h.
UserIndex
uint8 FActiveSound::UserIndex
Definition at line 564 of file ActiveSound.h.
VirtualizationModeOverride
EVirtualizationMode FActiveSound::VirtualizationModeOverride private
Definition at line 419 of file ActiveSound.h.
VolumeConcurrency
float FActiveSound::VolumeConcurrency
The volume used to determine concurrency resolution for "quietest" active sound.
If negative, tracking is disabled for lifetime of ActiveSound
Definition at line 609 of file ActiveSound.h.
VolumeMultiplier
float FActiveSound::VolumeMultiplier
Definition at line 584 of file ActiveSound.h.
WaveInstances
TMap<UPTRINT, FWaveInstance*> FActiveSound::WaveInstances private
Definition at line 415 of file ActiveSound.h.
Referenced by GetWaveInstances().
World
TWeakObjectPtr<UWorld> FActiveSound::World private
Definition at line 294 of file ActiveSound.h.
Referenced by GetWeakWorld(), GetWorld(), and SetWorld().
WorldID
uint32 FActiveSound::WorldID private
Definition at line 295 of file ActiveSound.h.
Referenced by GetWorldID().
The documentation for this struct was generated from the following file:
ActiveSound.h