Unreal Engine 5.6 C++ API: FRunnableThread Class Reference
FRunnableThread Class Reference abstract
Interface for runnable threads.
#include "RunnableThread.h"
Public Types
enum class ThreadType { Real , Fake , Forkable }
List of unique thread types we can create.
Public Member Functions
FRunnableThread ()
Default constructor.
virtual ~FRunnableThread ()
Virtual destructor.
const uint32 GetThreadID () const
Thread ID for this thread.
const FString & GetThreadName () const
Retrieves the given name of the thread.
EThreadPriority GetThreadPriority () const
Returns the runnable's thread priority.
virtual FRunnableThread::ThreadType GetThreadType () const
Returns the type of thread this is.
virtual bool Kill (bool bShouldWait=true)=0
Tells the thread to exit.
virtual bool SetThreadAffinity (const FThreadAffinity &Affinity)
Changes the thread affinity of the currently running thread.
virtual void SetThreadPriority (EThreadPriority NewPriority)=0
Changes the thread priority of the currently running thread.
virtual void Suspend (bool bShouldPause=true)=0
Tells the thread to either pause execution or resume depending on the passed in value.
virtual void WaitForCompletion ()=0
Halts the caller until this thread is has completed its work.
Static Public Member Functions
static FRunnableThread * Create (class FRunnable *InRunnable, const TCHAR *ThreadName, uint32 InStackSize=0, EThreadPriority InThreadPri=TPri_Normal, uint64 InThreadAffinityMask=FPlatformAffinity::GetNoAffinityMask(), EThreadCreateFlags InCreateFlags=EThreadCreateFlags::None)
Factory method to create a thread with the specified stack size and thread priority.
static FRunnableThread * GetRunnableThread ()
static uint32 GetTlsSlot ()
Gets a new Tls slot for storing the runnable thread pointer.
Protected Member Functions
virtual bool CreateInternal (FRunnable *InRunnable, const TCHAR *InThreadName, uint32 InStackSize=0, EThreadPriority InThreadPri=TPri_Normal, uint64 InThreadAffinityMask=0, EThreadCreateFlags InCreateFlags=EThreadCreateFlags::None)=0
Creates the thread with the specified stack size and thread priority.
void FreeTls ()
Deletes all FTlsAutoCleanup objects created for this thread.
void SetTls ()
Stores this instance in the runnable thread TLS slot.
Protected Attributes
FRunnable * Runnable
The runnable object to execute on this thread.
uint64 ThreadAffinityMask
The Affinity to run the thread with.
uint32 ThreadID
ID set during thread creation.
FEvent * ThreadInitSyncEvent
Sync event to make sure that Init() has been completed before allowing the main thread to continue.
FString ThreadName
Holds the name of the thread.
EThreadPriority ThreadPriority
The priority to run the thread at.
Private Member Functions
virtual void OnPostFork ()
Called on the forked process when the forkable thread can create a real thread.
virtual void OnPreFork ()
Called on the parent process before the fork occurs.
void PostCreate (EThreadPriority ThreadPriority)
Called after the internal thread is created so it can register debug information.
virtual void Tick ()
Used by the thread manager to tick threads in single-threaded mode.
Static Private Member Functions
static void SetupCreatedThread (FRunnableThread *&NewThread, class FRunnable *InRunnable, const TCHAR *ThreadName, uint32 InStackSize, EThreadPriority InThreadPri, uint64 InThreadAffinityMask, EThreadCreateFlags InCreateFlags)
Called to setup a newly created RunnableThread.
Static Private Attributes
static uint32 RunnableTlsSlot
Index of TLS slot for FRunnableThread pointer.
Friends
class FForkableThread
class FForkProcessHelper
class FThreadManager
class FThreadSingletonInitializer
class FTlsAutoCleanup
Detailed Description
Interface for runnable threads.
This interface specifies the methods used to manage a thread's life cycle.
Definition at line 19 of file RunnableThread.h.
Member Enumeration Documentation
ThreadType
enum class FRunnableThread::ThreadType strong
List of unique thread types we can create.
Enumerator
Real
Fake
Forkable
Definition at line 92 of file RunnableThread.h.
Constructor & Destructor Documentation
FRunnableThread()
FRunnableThread::FRunnableThread ()
Default constructor.
Referenced by Create(), GetRunnableThread(), and SetupCreatedThread().
~FRunnableThread()
virtual FRunnableThread::~FRunnableThread () virtual
Virtual destructor.
Member Function Documentation
Create()
FRunnableThread * FRunnableThread::Create (class FRunnable * InRunnable, const TCHAR * ThreadName, uint32 InStackSize = 0, EThreadPriority InThreadPri = TPri_Normal, uint64 InThreadAffinityMask = FPlatformAffinity::GetNoAffinityMask(), EThreadCreateFlags InCreateFlags = EThreadCreateFlags::None) static
Factory method to create a thread with the specified stack size and thread priority.
Parameters
InRunnable The runnable object to execute
ThreadName Name of the thread
InStackSize The size of the stack to create. 0 means use the current thread's stack size
InThreadPri Tells the thread whether it needs to adjust its priority or not. Defaults to normal priority
Returns
The newly created thread or nullptr if it failed
References FRunnableThread(), FGenericPlatformAffinity::GetNoAffinityMask(), None, ThreadName, and TPri_Normal.
Referenced by Async(), AsyncThread(), and UE::FPlatformIoDispatcherBase::Initialize().
CreateInternal()
virtual bool FRunnableThread::CreateInternal (FRunnable * InRunnable, const TCHAR * InThreadName, uint32 InStackSize = 0, EThreadPriority InThreadPri = TPri_Normal, uint64 InThreadAffinityMask = 0, EThreadCreateFlags InCreateFlags = EThreadCreateFlags::None) protected pure virtual
Creates the thread with the specified stack size and thread priority.
Parameters
InRunnable The runnable object to execute
ThreadName Name of the thread
InStackSize The size of the stack to create. 0 means use the current thread's stack size
InThreadPri Tells the thread whether it needs to adjust its priority or not. Defaults to normal priority
Returns
True if the thread and all of its initialization was successful, false otherwise
References None, and TPri_Normal.
FreeTls()
void FRunnableThread::FreeTls () protected
Deletes all FTlsAutoCleanup objects created for this thread.
GetRunnableThread()
FRunnableThread * FRunnableThread::GetRunnableThread () inline static
Returns
a runnable thread that is executing this runnable, if return value is nullptr, it means the running thread can be game thread or a thread created outside the runnable interface
Definition at line 145 of file RunnableThread.h.
References FRunnableThread(), FAndroidTLS::GetTlsValue(), and RunnableTlsSlot.
GetThreadID()
const uint32 FRunnableThread::GetThreadID () const inline
Thread ID for this thread.
Returns
ID that was set by CreateThread
See also
GetThreadName
Definition at line 114 of file RunnableThread.h.
References ThreadID.
GetThreadName()
const FString & FRunnableThread::GetThreadName () const inline
Retrieves the given name of the thread.
Returns
Name that was set by CreateThread
See also
GetThreadID
Definition at line 125 of file RunnableThread.h.
References ThreadName.
GetThreadPriority()
EThreadPriority FRunnableThread::GetThreadPriority () const inline
Returns the runnable's thread priority.
Definition at line 131 of file RunnableThread.h.
References ThreadPriority.
GetThreadType()
virtual FRunnableThread::ThreadType FRunnableThread::GetThreadType () const inline virtual
Returns the type of thread this is.
Definition at line 103 of file RunnableThread.h.
References Real.
Referenced by Async().
GetTlsSlot()
uint32 FRunnableThread::GetTlsSlot () static
Gets a new Tls slot for storing the runnable thread pointer.
Kill()
virtual bool FRunnableThread::Kill (bool bShouldWait = true) pure virtual
Tells the thread to exit.
If the caller needs to know when the thread has exited, it should use the bShouldWait value. It's highly recommended not to kill the thread without waiting for it. Having a thread forcibly destroyed can cause leaks and deadlocks.
The kill method is calling Stop() on the runnable to kill the thread gracefully.
Parameters
bShouldWait If true, the call will wait infinitely for the thread to exit.
Returns
Always true
OnPostFork()
virtual void FRunnableThread::OnPostFork () inline private virtual
Called on the forked process when the forkable thread can create a real thread.
Definition at line 210 of file RunnableThread.h.
References checkf, and TEXT.
OnPreFork()
virtual void FRunnableThread::OnPreFork () inline private virtual
Called on the parent process before the fork occurs.
Definition at line 202 of file RunnableThread.h.
References checkf, and TEXT.
PostCreate()
void FRunnableThread::PostCreate (EThreadPriority ThreadPriority) private
Called after the internal thread is created so it can register debug information.
References ThreadPriority.
SetThreadAffinity()
virtual bool FRunnableThread::SetThreadAffinity (const FThreadAffinity & Affinity) inline virtual
Changes the thread affinity of the currently running thread.
Parameters
ThreadAffinityMask The thread affinity to change to (can be 0 to keep previously set affinity mask)
ProcessorGroup The thread group to change to
Returns
returns true if the affinity changed, false if affinity did not change
Definition at line 66 of file RunnableThread.h.
SetThreadPriority()
virtual void FRunnableThread::SetThreadPriority (EThreadPriority NewPriority) pure virtual
Changes the thread priority of the currently running thread.
Parameters
NewPriority The thread priority to change to
SetTls()
void FRunnableThread::SetTls () protected
Stores this instance in the runnable thread TLS slot.
SetupCreatedThread()
void FRunnableThread::SetupCreatedThread (FRunnableThread *& NewThread, class FRunnable * InRunnable, const TCHAR * ThreadName, uint32 InStackSize, EThreadPriority InThreadPri, uint64 InThreadAffinityMask, EThreadCreateFlags InCreateFlags) static private
Called to setup a newly created RunnableThread.
References FRunnableThread(), and ThreadName.
Suspend()
virtual void FRunnableThread::Suspend (bool bShouldPause = true) pure virtual
Tells the thread to either pause execution or resume depending on the passed in value.
Parameters
bShouldPause Whether to pause the thread (true) or resume (false)
Tick()
virtual void FRunnableThread::Tick () inline private virtual
Used by the thread manager to tick threads in single-threaded mode.
Definition at line 197 of file RunnableThread.h.
WaitForCompletion()
virtual void FRunnableThread::WaitForCompletion () pure virtual
Halts the caller until this thread is has completed its work.
Friends And Related Symbol Documentation
FForkableThread
friend class FForkableThread friend
Definition at line 24 of file RunnableThread.h.
References FForkableThread.
Referenced by FForkableThread.
FForkProcessHelper
friend class FForkProcessHelper friend
Definition at line 25 of file RunnableThread.h.
References FForkProcessHelper.
Referenced by FForkProcessHelper.
FThreadManager
friend class FThreadManager friend
Definition at line 23 of file RunnableThread.h.
References FThreadManager.
Referenced by FThreadManager.
FThreadSingletonInitializer
friend class FThreadSingletonInitializer friend
Definition at line 21 of file RunnableThread.h.
References FThreadSingletonInitializer.
Referenced by FThreadSingletonInitializer.
FTlsAutoCleanup
friend class FTlsAutoCleanup friend
Definition at line 22 of file RunnableThread.h.
References FTlsAutoCleanup.
Referenced by FTlsAutoCleanup.
Field Documentation
Runnable
FRunnable* FRunnableThread::Runnable protected
The runnable object to execute on this thread.
Definition at line 177 of file RunnableThread.h.
RunnableTlsSlot
uint32 FRunnableThread::RunnableTlsSlot static private
Index of TLS slot for FRunnableThread pointer.
Definition at line 28 of file RunnableThread.h.
Referenced by GetRunnableThread().
ThreadAffinityMask
uint64 FRunnableThread::ThreadAffinityMask protected
The Affinity to run the thread with.
Definition at line 183 of file RunnableThread.h.
ThreadID
uint32 FRunnableThread::ThreadID protected
ID set during thread creation.
Definition at line 189 of file RunnableThread.h.
Referenced by GetThreadID().
ThreadInitSyncEvent
FEvent* FRunnableThread::ThreadInitSyncEvent protected
Sync event to make sure that Init() has been completed before allowing the main thread to continue.
Definition at line 180 of file RunnableThread.h.
ThreadName
FString FRunnableThread::ThreadName protected
Holds the name of the thread.
Definition at line 174 of file RunnableThread.h.
Referenced by Create(), GetThreadName(), and SetupCreatedThread().
ThreadPriority
EThreadPriority FRunnableThread::ThreadPriority protected
The priority to run the thread at.
Definition at line 186 of file RunnableThread.h.
Referenced by GetThreadPriority(), and PostCreate().
The documentation for this class was generated from the following file:
RunnableThread.h