Unreal Engine 5.6 C++ API: FMovieSceneBlendingAccumulator Struct Reference
FMovieSceneBlendingAccumulator Struct Reference
#include "MovieSceneBlendingAccumulator.h"
Public Member Functions
MOVIESCENE_API void Apply (const FMovieSceneContext &Context, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player)
Apply all currently accumulated blends.
template<typename ActuatorDataType>
void BlendToken (const FMovieSceneEvaluationOperand &InOperand, FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope &InScope, const FMovieSceneContext &InContext, ActuatorDataType &&InInputValue, EMovieSceneBlendType InBlendType, float InWeight=1.f, int32 InBlendingPriority=INDEX_NONE)
template<typename ActuatorDataType>
void BlendToken (const FMovieSceneEvaluationOperand &InOperand, FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope &InScope, const FMovieSceneContext &InContext, TBlendableToken< ActuatorDataType > &&InToken)
Add a token that will be blended together with other tokens of the same type and actuator this frame, and applied to all objects relating to the specified operand Such tokens are collated per-object and actuator, meaning the same data type can be blended in the same manner, but applied differently depending on context (ie, multiple float properties on the same object)
template<typename ActuatorDataType>
void BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope &InScope, const FMovieSceneContext &InContext, ActuatorDataType &&InInputValue, EMovieSceneBlendType InBlendType, float InWeight=1.f, int32 InBlendingPriority=INDEX_NONE)
template<typename ActuatorDataType>
void BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope &InScope, const FMovieSceneContext &InContext, TBlendableToken< ActuatorDataType > &&InToken)
Add a global token (not bound to a particular object) that will be blended together with other tokens of the same type and actuator this frame Such tokens are collated actuator, meaning the same data type can be blended in the same manner but applied differently depending on context (ie, multiple floats that relate to slomo and fade tracks)
void DefineActuator (FMovieSceneBlendingActuatorID InActuatorTypeID, TSharedRef< IMovieSceneBlendingActuator > InActuator)
Define an actuator with the specified unique ID that operates on a specific data type.
template<typename DataType>
TMovieSceneBlendingActuator< DataType > * FindActuator (FMovieSceneBlendingActuatorID InActuatorTypeID) const
Find an existing actuator with the specified ID that operates on a specific data type.
MOVIESCENE_API void Interrogate (const FMovieSceneContext &Context, FMovieSceneInterrogationData &InterrogationData, UObject *AnimatedObject)
Interrogate the final blended result when applied to the specified object.
Data Fields
TMap< FMovieSceneBlendingActuatorID, TSharedRef< IMovieSceneBlendingActuator > > Actuators
Map of actuator ID to actuator.
Private Attributes
TMap< FMovieSceneEvaluationOperand, FMovieSceneAccumulatedBlendState > OperandToBlendState
FMovieSceneAccumulatedBlendState UnboundBlendState
Detailed Description
Definition at line 25 of file MovieSceneBlendingAccumulator.h.
Member Function Documentation
Apply()
MOVIESCENE_API void FMovieSceneBlendingAccumulator::Apply (const FMovieSceneContext & Context, FPersistentEvaluationData & PersistentData, IMovieScenePlayer & Player)
Apply all currently accumulated blends.
BlendToken() [1/4]
template<typename ActuatorDataType> void FMovieSceneBlendingAccumulator::BlendToken (const FMovieSceneEvaluationOperand & InOperand, FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope & InScope, const FMovieSceneContext & InContext, ActuatorDataType && InInputValue, EMovieSceneBlendType InBlendType, float InWeight = 1.f, int32 InBlendingPriority = INDEX_NONE) inline
Definition at line 72 of file MovieSceneBlendingAccumulator.h.
References check, FindActuator(), Forward(), INDEX_NONE, and OperandToBlendState.
BlendToken() [2/4]
template<typename ActuatorDataType> void FMovieSceneBlendingAccumulator::BlendToken (const FMovieSceneEvaluationOperand & InOperand, FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope & InScope, const FMovieSceneContext & InContext, TBlendableToken< ActuatorDataType > && InToken) inline
Add a token that will be blended together with other tokens of the same type and actuator this frame, and applied to all objects relating to the specified operand Such tokens are collated per-object and actuator, meaning the same data type can be blended in the same manner, but applied differently depending on context (ie, multiple float properties on the same object)
See also
FindActuator, DefineActuator
Parameters
InOperand The operand to which this token should be applied
InActuatorTypeID Unique ID that identifies the actuator to use to apply the final blended state (must map to a valid actuator)
InToken The actual token data to blend
Definition at line 64 of file MovieSceneBlendingAccumulator.h.
References check, FindActuator(), FMovieSceneContext::GetHierarchicalBias(), MoveTemp(), and OperandToBlendState.
BlendToken() [3/4]
template<typename ActuatorDataType> void FMovieSceneBlendingAccumulator::BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope & InScope, const FMovieSceneContext & InContext, ActuatorDataType && InInputValue, EMovieSceneBlendType InBlendType, float InWeight = 1.f, int32 InBlendingPriority = INDEX_NONE) inline
Definition at line 47 of file MovieSceneBlendingAccumulator.h.
References check, FindActuator(), Forward(), INDEX_NONE, and UnboundBlendState.
BlendToken() [4/4]
template<typename ActuatorDataType> void FMovieSceneBlendingAccumulator::BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, const FMovieSceneEvaluationScope & InScope, const FMovieSceneContext & InContext, TBlendableToken< ActuatorDataType > && InToken) inline
Add a global token (not bound to a particular object) that will be blended together with other tokens of the same type and actuator this frame Such tokens are collated actuator, meaning the same data type can be blended in the same manner but applied differently depending on context (ie, multiple floats that relate to slomo and fade tracks)
See also
FindActuator, DefineActuator
Parameters
InScope The currently evaluating scope. Used to save preanimated state for the section
InActuatorTypeID Unique ID that identifies the actuator to use to apply the final blended state (must map to a valid actuator)
InToken The actual token data to blend
Definition at line 38 of file MovieSceneBlendingAccumulator.h.
References check, FindActuator(), FMovieSceneContext::GetHierarchicalBias(), MoveTemp(), and UnboundBlendState.
DefineActuator()
void FMovieSceneBlendingAccumulator::DefineActuator (FMovieSceneBlendingActuatorID InActuatorTypeID, TSharedRef< IMovieSceneBlendingActuator > InActuator) inline
Define an actuator with the specified unique ID that operates on a specific data type.
Parameters
InActuatorTypeID The ID that uniquely identifies the actuator to lookup
Returns
A pointer to an actuator if one already exists, nullptr otherwise
Definition at line 105 of file MovieSceneBlendingAccumulator.h.
References Actuators.
FindActuator()
template<typename DataType> TMovieSceneBlendingActuator< DataType > * FMovieSceneBlendingAccumulator::FindActuator (FMovieSceneBlendingActuatorID InActuatorTypeID) const inline
Find an existing actuator with the specified ID that operates on a specific data type.
Parameters
InActuatorTypeID The ID that uniquely identifies the actuator to lookup
Returns
A pointer to an actuator if one already exists, nullptr otherwise
Definition at line 85 of file MovieSceneBlendingAccumulator.h.
References Actuators, TSharedRef< ObjectType, InMode >::Get(), and GetBlendingDataType().
Referenced by BlendToken(), BlendToken(), BlendToken(), and BlendToken().
Interrogate()
MOVIESCENE_API void FMovieSceneBlendingAccumulator::Interrogate (const FMovieSceneContext & Context, FMovieSceneInterrogationData & InterrogationData, UObject * AnimatedObject)
Interrogate the final blended result when applied to the specified object.
Field Documentation
Actuators
TMap<FMovieSceneBlendingActuatorID, TSharedRef<IMovieSceneBlendingActuator> > FMovieSceneBlendingAccumulator::Actuators
Map of actuator ID to actuator.
Definition at line 121 of file MovieSceneBlendingAccumulator.h.
Referenced by DefineActuator(), and FindActuator().
OperandToBlendState
TMap<FMovieSceneEvaluationOperand, FMovieSceneAccumulatedBlendState> FMovieSceneBlendingAccumulator::OperandToBlendState private
Definition at line 125 of file MovieSceneBlendingAccumulator.h.
Referenced by BlendToken(), and BlendToken().
UnboundBlendState
FMovieSceneAccumulatedBlendState FMovieSceneBlendingAccumulator::UnboundBlendState private
Definition at line 126 of file MovieSceneBlendingAccumulator.h.
Referenced by BlendToken(), and BlendToken().
The documentation for this struct was generated from the following file:
MovieSceneBlendingAccumulator.h