Unreal Engine 5.6 C++ API: UFbxTextureImportData Class Reference
UFbxTextureImportData Class Reference
#include "FbxTextureImportData.h"
Private Member Functions
UNREALED_API bool CanEditChange (const FProperty *InProperty) const override
GENERATED_UCLASS_BODY() UPROPERTY()) uint32 bInvertNormalMaps UPROPERTY ()) EMaterialSearchLocation MaterialSearchLocation
If importing textures is enabled, this option will cause normal map Y (Green) values to be inverted.
UPROPERTY ()) FSoftObjectPath BaseMaterialName
Base material to instance from when importing materials.
UPROPERTY ()) FString BaseColorName
UPROPERTY ()) FString BaseDiffuseTextureName
UPROPERTY ()) FString BaseEmissiveColorName
UPROPERTY ()) FString BaseEmmisiveTextureName
UPROPERTY ()) FString BaseNormalTextureName
UPROPERTY ()) FString BaseOpacityTextureName
UPROPERTY ()) FString BaseSpecularTextureName
Private Attributes
bool bUseBaseMaterial
transient, ImportUI customize helper to store if we must show or not the BaseMaterialName property.
Detailed Description
Definition at line 16 of file FbxTextureImportData.h.
Member Function Documentation
CanEditChange()
UNREALED_API bool UFbxTextureImportData::CanEditChange (const FProperty * InProperty) const override private
References CanEditChange().
Referenced by CanEditChange().
UPROPERTY() [1/9]
GENERATED_UCLASS_BODY() UPROPERTY()) uint32 bInvertNormalMaps UFbxTextureImportData::UPROPERTY () private
If importing textures is enabled, this option will cause normal map Y (Green) values to be inverted.
Specify where we should search for matching materials when importing
References Category, config, and meta.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/9]
UFbxTextureImportData::UPROPERTY () private
Base material to instance from when importing materials.
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [3/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [4/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [5/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [6/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [7/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [8/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
UPROPERTY() [9/9]
UFbxTextureImportData::UPROPERTY () private
References Category, config, Material, meta, and UPROPERTY().
Field Documentation
bUseBaseMaterial
bool UFbxTextureImportData::bUseBaseMaterial private
transient, ImportUI customize helper to store if we must show or not the BaseMaterialName property.
Definition at line 33 of file FbxTextureImportData.h.
The documentation for this class was generated from the following file:
FbxTextureImportData.h