Unreal Engine 5.6 C++ API: StateTreePropertyRef.h File Reference
StateTreePropertyRef.h File Reference
#include "StateTreeAsyncExecutionContext.h"
#include "StateTreeExecutionContext.h"
#include "StateTreeIndexTypes.h"
#include "StateTreeInstanceData.h"
#include "StateTreePropertyRefHelpers.h"
#include "Templates/Tuple.h"
#include "StateTreePropertyRef.generated.h"
Data Structures
struct FStateTreePropertyRefExternalHandle
External Handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
struct TStateTreePropertyRef< TRef >
TStateTreePropertyRef is a type-safe FStateTreePropertyRef wrapper against a single given type.
struct TStateTreePropertyRefExternalHandle< TRef >
Single type safe external handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::StateTree
Data type the FStateTreeDataHandle is pointing at.
namespace UE::StateTree::PropertyRefHelpers
Functions
template<class T>
static T * UE::StateTree::PropertyRefHelpers::GetMutablePtrToProperty (const FStateTreePropertyRef &PropertyRef, FStateTreeInstanceStorage &InstanceDataStorage, const FStateTreeExecutionFrame &ExecutionFrame, const FStateTreeExecutionFrame *ParentExecutionFrame, const FProperty **OutSourceProperty=nullptr)
template<class... T>
static TTuple< T *... > UE::StateTree::PropertyRefHelpers::GetMutablePtrTupleToProperty (const FStateTreePropertyRef &PropertyRef, FStateTreeInstanceStorage &InstanceDataStorage, const FStateTreeExecutionFrame &ExecutionFrame, const FStateTreeExecutionFrame *ParentExecutionFrame)
USTRUCT () struct FStateTreePropertyRef
Property ref allows to get a pointer to selected property in StateTree.
Function Documentation
USTRUCT()
USTRUCT ()
Property ref allows to get a pointer to selected property in StateTree.
The expected type of the reference should be set in "RefType" meta specifier.
Meta specifiers for the type:
RefType = "<type>"
Specifies a comma separated list of type of property to reference
Supported types are: bool, byte, int32, int64, float, double, Name, String, Text, UObject pointers, and structs
Structs and Objects must use full path name
If multiple types are specified, GetMutablePtrTuple can be used to access the correct type
IsRefToArray
If specified, the reference is to an TArray<RefType>
CanRefToArray
If specified, the reference can bind to a Reftype or TArray<RefType>
Optional
If specified, the reference can be left unbound, otherwise the compiler report error if the reference is not bound
Example:
// Reference to float UPROPERTY(EditAnywhere, meta = (RefType = "float")) FStateTreePropertyRef RefToFloat;
// Reference to FTestStructBase UPROPERTY(EditAnywhere, meta = (RefType = "/Script/ModuleName.TestStructBase")) FStateTreePropertyRef RefToTest;
// Reference to TArray<FTestStructBase> UPROPERTY(EditAnywhere, meta = (RefType = "/Script/ModuleName.TestStructBase", IsRefToArray)) FStateTreePropertyRef RefToArrayOfTests;
// Reference to Vector, TArray<FVector>, AActor*, TArray<AActor*> UPROPERTY(EditAnywhere, meta = (RefType = "/Script/CoreUObject.Vector, /Script/Engine.Actor", CanRefToArray)) FStateTreePropertyRef RefToLocationLikeTypes;
Returns
pointer to the property if possible, nullptr otherwise.
pointer to the property if possible, nullptr otherwise.
a tuple of pointers of the given types to the property if possible, nullptr otherwise.
a tuple of pointers of the given types to the property if possible, nullptr otherwise.
Used internally.
Returns
index to referenced property access
Definition at line 134 of file StateTreePropertyRef.h.
References check, UE::StateTree::Async::FActivePathInfo::Frame, GENERATED_BODY, UE::StateTree::PropertyRefHelpers::GetMutablePtrToProperty(), UE::StateTree::PropertyRefHelpers::GetMutablePtrTupleToProperty(), UE::StateTree::Async::FActivePathInfo::IsValid(), UE::StateTree::Async::FActivePathInfo::ParentFrame, and UPROPERTY.