Unreal Engine 5.6 C++ API: UE::MovieScene::FFixedObjectBindingID Struct Reference
UE::MovieScene::FFixedObjectBindingID Struct Reference
A binding ID that is only resolveable through a fixed root sequence.
#include "MovieSceneObjectBindingID.h"
Public Member Functions
FFixedObjectBindingID ()
FFixedObjectBindingID (const FGuid &InGuid, FMovieSceneSequenceID InSequenceID)
MOVIESCENE_API FRelativeObjectBindingID ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, const FMovieSceneSequenceHierarchy *Hierarchy) const
Convert this fixed binding ID to one that is resolved relative to the specified Sequence.
MOVIESCENE_API FRelativeObjectBindingID ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, IMovieScenePlayer &InPlayer) const
MOVIESCENE_API FRelativeObjectBindingID ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) const
Convert this fixed binding ID to one that is resolved relative to the specified Sequence.
Data Fields
FGuid Guid
GUID of the Object Binding (ie, FMovieSceneBinding::GetObjectGuid)
FMovieSceneSequenceID SequenceID
The sequence ID that the object binding is found within.
Friends
uint32 GetTypeHash (const FFixedObjectBindingID &A)
bool operator!= (const FFixedObjectBindingID &A, const FFixedObjectBindingID &B)
bool operator== (const FFixedObjectBindingID &A, const FFixedObjectBindingID &B)
Detailed Description
A binding ID that is only resolveable through a fixed root sequence.
Use of this type should be reserved for editor code dealing with a specific sequence hierarchy where hashing or comparison is required. The SequenceID member is always an absolute sequence ID
Definition at line 113 of file MovieSceneObjectBindingID.h.
Constructor & Destructor Documentation
FFixedObjectBindingID() [1/2]
UE::MovieScene::FFixedObjectBindingID::FFixedObjectBindingID () inline
Definition at line 115 of file MovieSceneObjectBindingID.h.
Referenced by GetTypeHash, operator!=, and operator==.
FFixedObjectBindingID() [2/2]
UE::MovieScene::FFixedObjectBindingID::FFixedObjectBindingID (const FGuid & InGuid, FMovieSceneSequenceID InSequenceID) inline
Definition at line 118 of file MovieSceneObjectBindingID.h.
References Guid, and SequenceID.
Member Function Documentation
ConvertToRelative() [1/3]
MOVIESCENE_API FRelativeObjectBindingID UE::MovieScene::FFixedObjectBindingID::ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, const FMovieSceneSequenceHierarchy * Hierarchy) const
Convert this fixed binding ID to one that is resolved relative to the specified Sequence.
Parameters
SourceSequenceID The sequence ID to make this fixed ID relative to
Hierarchy The hierarchy that represents the root sequence that SourceSequenceID is contained within
Returns
A new binding ID that will resolve relative to the specified sequence
ConvertToRelative() [2/3]
MOVIESCENE_API FRelativeObjectBindingID UE::MovieScene::FFixedObjectBindingID::ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, IMovieScenePlayer & InPlayer) const
ConvertToRelative() [3/3]
MOVIESCENE_API FRelativeObjectBindingID UE::MovieScene::FFixedObjectBindingID::ConvertToRelative (FMovieSceneSequenceID SourceSequenceID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) const
Convert this fixed binding ID to one that is resolved relative to the specified Sequence.
Parameters
SourceSequenceID The sequence ID to make this fixed ID relative to
InPlayer The active movie scene player to retrieve a root sequence hierarchy from
Returns
A new binding ID that will resolve relative to the specified sequence
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFixedObjectBindingID & A) friend
Definition at line 125 of file MovieSceneObjectBindingID.h.
References FFixedObjectBindingID(), A, and GetTypeHash.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FFixedObjectBindingID & A, const FFixedObjectBindingID & B) friend
Definition at line 135 of file MovieSceneObjectBindingID.h.
References FFixedObjectBindingID(), A, and B.
operator==
bool operator== (const FFixedObjectBindingID & A, const FFixedObjectBindingID & B) friend
Definition at line 130 of file MovieSceneObjectBindingID.h.
References FFixedObjectBindingID(), A, and B.
Field Documentation
Guid
FGuid UE::MovieScene::FFixedObjectBindingID::Guid
GUID of the Object Binding (ie, FMovieSceneBinding::GetObjectGuid)
Definition at line 165 of file MovieSceneObjectBindingID.h.
Referenced by FFixedObjectBindingID(), and USTRUCT().
SequenceID
FMovieSceneSequenceID UE::MovieScene::FFixedObjectBindingID::SequenceID
The sequence ID that the object binding is found within.
Definition at line 168 of file MovieSceneObjectBindingID.h.
Referenced by FFixedObjectBindingID(), and USTRUCT().
The documentation for this struct was generated from the following file:
MovieSceneObjectBindingID.h