Unreal Engine 5.6 C++ API: UE::Sequencer::FLayerBarModel Class Reference
UE::Sequencer::FLayerBarModel Class Reference
#include "LayerBarModel.h"
Public Member Functions
FLayerBarModel (TWeakPtr< FViewModel > LayerRoot)
~FLayerBarModel ()
void AddToSnapField (const ISnapCandidate &Candidate, ISnapField &SnapField) const override
FTrackLaneVirtualAlignment ArrangeVirtualTrackLaneView () const override
bool CanDrag () const override
Returns whether the model can be dragged.
TRange< FFrameNumber > ComputeRange () const
TSharedPtr< ITrackLaneWidget > CreateTrackLaneView (const FCreateTrackLaneViewParams &InParams) override
ESelectionIntent IsSelectable () const override
void Offset (FFrameNumber Offset)
void OnBeginDrag (IDragOperation &DragOperation) override
Called at the beginning of the drag operation.
void OnEndDrag (IDragOperation &DragOperation) override
Called at the end of a drag operation.
void OnInitiateStretch (IStretchOperation &StretchOperation, EStretchConstraint Constraint, FStretchParameters *InOutGlobalParameters) override
UE_SEQUENCER_DECLARE_CASTABLE (FLayerBarModel, FViewModel, FLinkedOutlinerExtension, ITrackLaneExtension, ISelectableExtension, ISnappableExtension, IDraggableTrackAreaExtension, IStretchableExtension)
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::FLinkedOutlinerExtension
FLinkedOutlinerExtension ()
TViewModelPtr< IOutlinerExtension > GetLinkedOutlinerItem () const
void SetLinkedOutlinerItem (const TViewModelPtr< IOutlinerExtension > &InOutlinerItem)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (FLinkedOutlinerExtension)
Public Member Functions inherited from UE::Sequencer::ITrackLaneExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackLaneExtension) virtual ~ITrackLaneExtension()
Public Member Functions inherited from UE::Sequencer::ISelectableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISelectableExtension) virtual ~ISelectableExtension()
Public Member Functions inherited from UE::Sequencer::ISnappableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISnappableExtension) virtual ~ISnappableExtension()
Public Member Functions inherited from UE::Sequencer::IDraggableTrackAreaExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDraggableTrackAreaExtension) virtual ~IDraggableTrackAreaExtension()
Public Member Functions inherited from UE::Sequencer::IStretchableExtension
virtual EStretchResult OnBeginStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParameters, FStretchParameters *InOutParameters)
virtual void OnEndStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParametersm, FStretchParameters *InOutParameters)
virtual void OnStretch (const IStretchOperation &StretchOperation, const FStretchScreenParameters &ScreenParameters, FStretchParameters *InOutParameters)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IStretchableExtension) virtual ~IStretchableExtension()
Private Member Functions
void OnConstruct () override
Called once for this model when it is added to a parent that has valid shared data.
void OnDestruct () override
void OnExtensionsDirtied () override
Additional Inherited Members
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Member Functions inherited from UE::Sequencer::TViewModelExtensionCollection< ILayerBarExtension >
TViewModelExtensionCollection ()
void FilterExtensions (Predicate &&InPredicate)
TArrayView< ILayerBarExtension *const > GetExtensions () const
Protected Member Functions inherited from UE::Sequencer::FViewModelExtensionCollection
void Destroy ()
TSharedPtr< FViewModel > GetObservedModel () const
void Initialize ()
void Reinitialize (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth=-1)
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Detailed Description
Definition at line 29 of file LayerBarModel.h.
Constructor & Destructor Documentation
FLayerBarModel()
UE::Sequencer::FLayerBarModel::FLayerBarModel (TWeakPtr< FViewModel > LayerRoot)
Referenced by UE_SEQUENCER_DECLARE_CASTABLE().
~FLayerBarModel()
UE::Sequencer::FLayerBarModel::~FLayerBarModel ()
Member Function Documentation
AddToSnapField()
void UE::Sequencer::FLayerBarModel::AddToSnapField (const ISnapCandidate & Candidate, ISnapField & SnapField) const override virtual
Implements UE::Sequencer::ISnappableExtension.
ArrangeVirtualTrackLaneView()
FTrackLaneVirtualAlignment UE::Sequencer::FLayerBarModel::ArrangeVirtualTrackLaneView () const override virtual
Implements UE::Sequencer::ITrackLaneExtension.
CanDrag()
bool UE::Sequencer::FLayerBarModel::CanDrag () const override virtual
Returns whether the model can be dragged.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
ComputeRange()
TRange< FFrameNumber > UE::Sequencer::FLayerBarModel::ComputeRange () const
CreateTrackLaneView()
TSharedPtr< ITrackLaneWidget > UE::Sequencer::FLayerBarModel::CreateTrackLaneView (const FCreateTrackLaneViewParams & InParams) override virtual
Implements UE::Sequencer::ITrackLaneExtension.
IsSelectable()
ESelectionIntent UE::Sequencer::FLayerBarModel::IsSelectable () const override virtual
Reimplemented from UE::Sequencer::ISelectableExtension.
Offset()
void UE::Sequencer::FLayerBarModel::Offset (FFrameNumber Offset)
References Offset().
Referenced by Offset().
OnBeginDrag()
void UE::Sequencer::FLayerBarModel::OnBeginDrag (IDragOperation & DragOperation) override virtual
Called at the beginning of the drag operation.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
OnConstruct()
void UE::Sequencer::FLayerBarModel::OnConstruct () override private virtual
Called once for this model when it is added to a parent that has valid shared data.
Reimplemented from UE::Sequencer::FViewModel.
OnDestruct()
void UE::Sequencer::FLayerBarModel::OnDestruct () override private virtual
Reimplemented from UE::Sequencer::FViewModel.
OnEndDrag()
void UE::Sequencer::FLayerBarModel::OnEndDrag (IDragOperation & DragOperation) override virtual
Called at the end of a drag operation.
Implements UE::Sequencer::IDraggableTrackAreaExtension.
OnExtensionsDirtied()
void UE::Sequencer::FLayerBarModel::OnExtensionsDirtied () override private virtual
Reimplemented from UE::Sequencer::FViewModelExtensionCollection.
OnInitiateStretch()
void UE::Sequencer::FLayerBarModel::OnInitiateStretch (IStretchOperation & StretchOperation, EStretchConstraint Constraint, FStretchParameters * InOutGlobalParameters) override virtual
Reimplemented from UE::Sequencer::IStretchableExtension.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FLayerBarModel::UE_SEQUENCER_DECLARE_CASTABLE (FLayerBarModel , FViewModel , FLinkedOutlinerExtension , ITrackLaneExtension , ISelectableExtension , ISnappableExtension , IDraggableTrackAreaExtension , IStretchableExtension)
References FLayerBarModel(), UE::Sequencer::FLinkedOutlinerExtension::FLinkedOutlinerExtension(), and UE::Sequencer::FViewModel::FViewModel().
The documentation for this class was generated from the following file:
LayerBarModel.h