Unreal Engine 5.6 C++ API: HairDescription.h File Reference
HairDescription.h File Reference
#include "CoreMinimal.h"
#include "HairAttributes.h"
#include "MeshAttributeArray.h"
#include "MeshDescription.h"
#include "MeshTypes.h"
#include "Serialization/EditorBulkData.h"
Data Structures
struct FGroomID
class FHairDescription
struct FHairDescriptionBulkData
Bulk data storage for FHairDescription.
struct FHairDescriptionVersion
struct FStrandID
Typedefs
template<typename AttributeType>
using TGroomAttributesConstRef = TMeshAttributesConstRef<FGroomID, AttributeType>
template<typename AttributeType>
using TGroomAttributesRef = TMeshAttributesRef<FGroomID, AttributeType>
template<typename AttributeType>
using TStrandAttributesConstRef = TMeshAttributesConstRef<FStrandID, AttributeType>
template<typename AttributeType>
using TStrandAttributesRef = TMeshAttributesRef<FStrandID, AttributeType>
Functions
FArchive & operator<< (FArchive &Ar, FHairDescriptionVersion &Version)
template<typename AttributeType>
void SetGroomAttribute (FHairDescription &HairDescription, FGroomID GroomID, FName AttributeName, AttributeType AttributeValue)
template<typename AttributeType>
void SetHairStrandAttribute (FHairDescription &HairDescription, FStrandID StrandID, FName AttributeName, AttributeType AttributeValue)
template<typename AttributeType>
void SetHairVertexAttribute (FHairDescription &HairDescription, FVertexID VertexID, FName AttributeName, AttributeType AttributeValue)
Typedef Documentation
TGroomAttributesConstRef
template<typename AttributeType> using TGroomAttributesConstRef = TMeshAttributesConstRef<FGroomID, AttributeType>
Definition at line 178 of file HairDescription.h.
TGroomAttributesRef
template<typename AttributeType> using TGroomAttributesRef = TMeshAttributesRef<FGroomID, AttributeType>
Definition at line 175 of file HairDescription.h.
TStrandAttributesConstRef
template<typename AttributeType> using TStrandAttributesConstRef = TMeshAttributesConstRef<FStrandID, AttributeType>
Definition at line 177 of file HairDescription.h.
TStrandAttributesRef
template<typename AttributeType> using TStrandAttributesRef = TMeshAttributesRef<FStrandID, AttributeType>
Definition at line 174 of file HairDescription.h.
Function Documentation
operator<<()
FArchive & operator<< (FArchive & Ar, FHairDescriptionVersion & Version)
References Ar.
SetGroomAttribute()
template<typename AttributeType> void SetGroomAttribute (FHairDescription & HairDescription, FGroomID GroomID, FName AttributeName, AttributeType AttributeValue)
Definition at line 205 of file HairDescription.h.
References TAttributesSet< ElementIDType >::GetAttributesRef(), FHairDescription::GroomAttributes(), TMeshAttributesRef< ElementIDType, AttributeType >::IsValid(), and FAttributesSetBase::RegisterAttribute().
SetHairStrandAttribute()
template<typename AttributeType> void SetHairStrandAttribute (FHairDescription & HairDescription, FStrandID StrandID, FName AttributeName, AttributeType AttributeValue)
Definition at line 193 of file HairDescription.h.
References TAttributesSet< ElementIDType >::GetAttributesRef(), TMeshAttributesRef< ElementIDType, AttributeType >::IsValid(), FAttributesSetBase::RegisterAttribute(), FHairDescription::StrandAttributes(), and StrandID.
SetHairVertexAttribute()
template<typename AttributeType> void SetHairVertexAttribute (FHairDescription & HairDescription, FVertexID VertexID, FName AttributeName, AttributeType AttributeValue)
Definition at line 181 of file HairDescription.h.
References TAttributesSet< ElementIDType >::GetAttributesRef(), TMeshAttributesRef< ElementIDType, AttributeType >::IsValid(), FAttributesSetBase::RegisterAttribute(), and FHairDescription::VertexAttributes().