Unreal Engine 5.6 C++ API: FDelegateHandle Class Reference
FDelegateHandle Class Reference
Class representing a handle to a specific object/function pair bound to a delegate.
#include "IDelegateInstance.h"
Public Types
enum EGenerateNewHandleType { GenerateNewHandle }
Public Member Functions
FDelegateHandle ()
Creates an initially unset handle.
FDelegateHandle (EGenerateNewHandleType)
Creates a handle pointing to a new instance.
bool IsValid () const
Returns true if this was ever bound to a delegate, but you need to check with the owning delegate to confirm it is still valid.
bool operator!= (const FDelegateHandle &Rhs) const
bool operator== (const FDelegateHandle &Rhs) const
void Reset ()
Clear handle to indicate it is no longer bound.
Static Private Member Functions
static uint64 GenerateNewID ()
Generates a new ID for use the delegate handle.
Private Attributes
uint64 ID
Friends
FORCEINLINE uint32 GetTypeHash (const FDelegateHandle &Key)
Detailed Description
Class representing a handle to a specific object/function pair bound to a delegate.
Definition at line 13 of file IDelegateInstance.h.
Member Enumeration Documentation
EGenerateNewHandleType
enum FDelegateHandle::EGenerateNewHandleType
Enumerator
GenerateNewHandle
Definition at line 16 of file IDelegateInstance.h.
Constructor & Destructor Documentation
FDelegateHandle() [1/2]
FDelegateHandle::FDelegateHandle () inline
Creates an initially unset handle.
Definition at line 22 of file IDelegateInstance.h.
References ID.
Referenced by GetTypeHash, operator!=(), and operator==().
FDelegateHandle() [2/2]
FDelegateHandle::FDelegateHandle (EGenerateNewHandleType) inline explicit
Creates a handle pointing to a new instance.
Definition at line 28 of file IDelegateInstance.h.
References GenerateNewID(), and ID.
Member Function Documentation
GenerateNewID()
uint64 FDelegateHandle::GenerateNewID () static private
Generates a new ID for use the delegate handle.
Returns
A unique ID for the delegate.
Referenced by FDelegateHandle().
IsValid()
bool FDelegateHandle::IsValid () const inline
Returns true if this was ever bound to a delegate, but you need to check with the owning delegate to confirm it is still valid.
Definition at line 34 of file IDelegateInstance.h.
References ID.
operator!=()
bool FDelegateHandle::operator!= (const FDelegateHandle & Rhs) const inline
Definition at line 50 of file IDelegateInstance.h.
References FDelegateHandle(), and ID.
operator==()
bool FDelegateHandle::operator== (const FDelegateHandle & Rhs) const inline
Definition at line 45 of file IDelegateInstance.h.
References FDelegateHandle(), and ID.
Reset()
void FDelegateHandle::Reset () inline
Clear handle to indicate it is no longer bound.
Definition at line 40 of file IDelegateInstance.h.
References ID.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FDelegateHandle & Key) friend
Definition at line 55 of file IDelegateInstance.h.
References FDelegateHandle(), FORCEINLINE, GetTypeHash, and Key.
Referenced by GetTypeHash.
Field Documentation
ID
uint64 FDelegateHandle::ID private
Definition at line 69 of file IDelegateInstance.h.
Referenced by FDelegateHandle(), FDelegateHandle(), IsValid(), operator!=(), operator==(), and Reset().
The documentation for this class was generated from the following file:
IDelegateInstance.h