Unreal Engine 5.6 C++ API: UE::Insights::FTreeNodeGroupingByNameFirstLetter Class Reference
UE::Insights::FTreeNodeGroupingByNameFirstLetter Class Reference
Creates a group for each first letter of node names.
#include "TreeNodeGrouping.h"
Public Member Functions
FTreeNodeGroupingByNameFirstLetter ()
virtual ~FTreeNodeGroupingByNameFirstLetter ()
virtual FTreeNodeGroupInfo GetGroupForNode (const FBaseTreeNodePtr InNode) const override
Private Member Functions
INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByNameFirstLetter, FTreeNodeGrouping)
Additional Inherited Members
Protected Member Functions inherited from UE::Insights::FTreeNodeGrouping
UE_DEPRECATED (5.6, "BrushName is not used") FName BrushName
Protected Attributes inherited from UE::Insights::FTreeNodeGrouping
FText Description
const FSlateBrush * Icon
FText ShortName
FText TitleName
Detailed Description
Creates a group for each first letter of node names.
Definition at line 249 of file TreeNodeGrouping.h.
Constructor & Destructor Documentation
FTreeNodeGroupingByNameFirstLetter()
UE::Insights::FTreeNodeGroupingByNameFirstLetter::FTreeNodeGroupingByNameFirstLetter ()
Referenced by INSIGHTS_DECLARE_RTTI().
~FTreeNodeGroupingByNameFirstLetter()
virtual UE::Insights::FTreeNodeGroupingByNameFirstLetter::~FTreeNodeGroupingByNameFirstLetter () inline virtual
Definition at line 255 of file TreeNodeGrouping.h.
Member Function Documentation
GetGroupForNode()
virtual FTreeNodeGroupInfo UE::Insights::FTreeNodeGroupingByNameFirstLetter::GetGroupForNode (const FBaseTreeNodePtr InNode) const override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
INSIGHTS_DECLARE_RTTI()
UE::Insights::FTreeNodeGroupingByNameFirstLetter::INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByNameFirstLetter , FTreeNodeGrouping) private
References UE::Insights::FTreeNodeGrouping::FTreeNodeGrouping(), and FTreeNodeGroupingByNameFirstLetter().
The documentation for this class was generated from the following file:
TreeNodeGrouping.h