Unreal Engine 5.6 C++ API: ObjectElementDataUtil Namespace Reference
ObjectElementDataUtil Namespace Reference
Functions
UObject * GetObjectFromHandle (const FTypedElementHandle &InHandle, const bool bSilent=false)
Attempt to get the object from the given element handle.
UObject * GetObjectFromHandleChecked (const FTypedElementHandle &InHandle)
Attempt to get the object from the given element handle, asserting if the element handle doesn't contain FObjectElementData.
template<typename ElementHandleType>
TArray< UObject * > GetObjectsFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent=false)
Attempt to get the objects from the given element handles.
template<typename ElementHandleType>
TArray< UObject * > GetObjectsFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the objects from the given element handles, asserting if any element handle doesn't contain FObjectElementData.
Function Documentation
GetObjectFromHandle()
UObject * ObjectElementDataUtil::GetObjectFromHandle (const FTypedElementHandle & InHandle, const bool bSilent = false)
Attempt to get the object from the given element handle.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The object if the element handle contains FObjectElementData, otherwise null.
Referenced by GetObjectsFromHandles().
GetObjectFromHandleChecked()
UObject * ObjectElementDataUtil::GetObjectFromHandleChecked (const FTypedElementHandle & InHandle)
Attempt to get the object from the given element handle, asserting if the element handle doesn't contain FObjectElementData.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The object.
Referenced by GetObjectsFromHandlesChecked().
GetObjectsFromHandles()
template<typename ElementHandleType> TArray< UObject * > ObjectElementDataUtil::GetObjectsFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent = false)
Attempt to get the objects from the given element handles.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The objects of any element handles that contain FObjectElementData, skipping any that don't.
Definition at line 52 of file ObjectElementData.h.
References TArray< InElementType, InAllocatorType >::Add(), GetObjectFromHandle(), Handle, TArrayView< InElementType, InSizeType >::Num(), Object, and TArray< InElementType, InAllocatorType >::Reserve().
GetObjectsFromHandlesChecked()
template<typename ElementHandleType> TArray< UObject * > ObjectElementDataUtil::GetObjectsFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the objects from the given element handles, asserting if any element handle doesn't contain FObjectElementData.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The objects.
Definition at line 74 of file ObjectElementData.h.
References TArray< InElementType, InAllocatorType >::Add(), GetObjectFromHandleChecked(), Handle, TArrayView< InElementType, InSizeType >::Num(), and TArray< InElementType, InAllocatorType >::Reserve().