Unreal Engine 5.6 C++ API: Audio::FTabularRenderHelper Class Reference
Audio::FTabularRenderHelper Class Reference
#include "AudioDebugDraw.h"
Data Structures
struct FCol
struct FItem
Public Member Functions
FTabularRenderHelper ()=default
void AddCol (FString Text, int32 WidthInChars=0)
void AddRow (const TArray< FItem > &Items)
void Draw (FCanvas *Canvas, int32 X, int32 Y) const
Private Member Functions
void DrawHeaders (FCanvas *Canvas, int32 X, int32 Y, const FLinearColor &Color) const
void DrawRows (FCanvas *Canvas, const int32 InX, const int32 InY, const FLinearColor &Color) const
void RightJustify (FCanvas *Canvas, const int32 X, const int32 Y, const int32 InterColumnOffset, TCHAR const *Text, FLinearColor const &Color) const
Private Attributes
TArray< FCol > Cols
const UFont * Font = UEngine::GetTinyFont()
FColor HeaderColor = FColor::White
FColor RowColor = FColor::Green
Detailed Description
Definition at line 11 of file AudioDebugDraw.h.
Constructor & Destructor Documentation
FTabularRenderHelper()
Audio::FTabularRenderHelper::FTabularRenderHelper () default
Member Function Documentation
AddCol()
void Audio::FTabularRenderHelper::AddCol (FString Text, int32 WidthInChars = 0) inline
Definition at line 35 of file AudioDebugDraw.h.
References Cols, Font, StringSize(), Text, X, and Y.
AddRow()
void Audio::FTabularRenderHelper::AddRow (const TArray< FItem > & Items) inline
Definition at line 24 of file AudioDebugDraw.h.
References Color, Cols, TArray< InElementType, InAllocatorType >::Num(), and Text.
Draw()
void Audio::FTabularRenderHelper::Draw (FCanvas * Canvas, int32 X, int32 Y) const inline
Definition at line 16 of file AudioDebugDraw.h.
References DrawHeaders(), DrawRows(), Font, HeaderColor, RowColor, X, and Y.
DrawHeaders()
void Audio::FTabularRenderHelper::DrawHeaders (FCanvas * Canvas, int32 X, int32 Y, const FLinearColor & Color) const inline private
Definition at line 62 of file AudioDebugDraw.h.
References Color, Cols, RightJustify(), X, and Y.
Referenced by Draw().
DrawRows()
void Audio::FTabularRenderHelper::DrawRows (FCanvas * Canvas, const int32 InX, const int32 InY, const FLinearColor & Color) const inline private
Definition at line 70 of file AudioDebugDraw.h.
References Audio::C, Color, Cols, Font, FCanvas::GetParentCanvasSize(), Line, RightJustify(), X, Y, and UE::Math::TIntPoint< InIntType >::Y.
Referenced by Draw().
RightJustify()
void Audio::FTabularRenderHelper::RightJustify (FCanvas * Canvas, const int32 X, const int32 Y, const int32 InterColumnOffset, TCHAR const * Text, FLinearColor const & Color) const inline private
Definition at line 56 of file AudioDebugDraw.h.
References Color, FCanvas::DrawShadowedString(), Font, StringSize(), Text, X, and Y.
Referenced by DrawHeaders(), and DrawRows().
Field Documentation
Cols
TArray<FCol> Audio::FTabularRenderHelper::Cols private
Definition at line 51 of file AudioDebugDraw.h.
Referenced by AddCol(), AddRow(), DrawHeaders(), and DrawRows().
Font
const UFont* Audio::FTabularRenderHelper::Font = UEngine::GetTinyFont() private
Definition at line 54 of file AudioDebugDraw.h.
Referenced by AddCol(), Draw(), DrawRows(), and RightJustify().
HeaderColor
FColor Audio::FTabularRenderHelper::HeaderColor = FColor::White private
Definition at line 52 of file AudioDebugDraw.h.
Referenced by Draw().
RowColor
FColor Audio::FTabularRenderHelper::RowColor = FColor::Green private
Definition at line 53 of file AudioDebugDraw.h.
Referenced by Draw().
The documentation for this class was generated from the following file:
AudioDebugDraw.h