Unreal Engine 5.6 C++ API: IBreakIterator Class Reference
IBreakIterator Class Reference abstract
#include "IBreakIterator.h"
Public Member Functions
virtual ~IBreakIterator ()=default
virtual void ClearString ()
virtual int32 GetCurrentPosition () const =0
virtual int32 MoveToCandidateAfter (const int32 InIndex)=0
virtual int32 MoveToCandidateBefore (const int32 InIndex)=0
virtual int32 MoveToNext ()=0
virtual int32 MoveToPrevious ()=0
virtual int32 ResetToBeginning ()=0
virtual int32 ResetToEnd ()=0
virtual void SetString (const FString &InString)
virtual void SetString (const FText &InText)
virtual void SetString (const TCHAR *const InString, const int32 InStringLength)
virtual void SetString (FString &&InString)=0
virtual void SetStringRef (const FString &InString)
virtual void SetStringRef (const FString *InString)
virtual void SetStringRef (const FText &InText)
virtual void SetStringRef (const TCHAR *const InString, const int32 InStringLength)
virtual void SetStringRef (FStringView InString)=0
Detailed Description
Definition at line 8 of file IBreakIterator.h.
Constructor & Destructor Documentation
~IBreakIterator()
virtual IBreakIterator::~IBreakIterator () virtual default
Member Function Documentation
ClearString()
virtual void IBreakIterator::ClearString () inline virtual
Definition at line 46 of file IBreakIterator.h.
References SetStringRef().
GetCurrentPosition()
virtual int32 IBreakIterator::GetCurrentPosition () const pure virtual
MoveToCandidateAfter()
virtual int32 IBreakIterator::MoveToCandidateAfter (const int32 InIndex) pure virtual
MoveToCandidateBefore()
virtual int32 IBreakIterator::MoveToCandidateBefore (const int32 InIndex) pure virtual
MoveToNext()
virtual int32 IBreakIterator::MoveToNext () pure virtual
MoveToPrevious()
virtual int32 IBreakIterator::MoveToPrevious () pure virtual
ResetToBeginning()
virtual int32 IBreakIterator::ResetToBeginning () pure virtual
ResetToEnd()
virtual int32 IBreakIterator::ResetToEnd () pure virtual
SetString() [1/4]
virtual void IBreakIterator::SetString (const FString & InString) inline virtual
Definition at line 17 of file IBreakIterator.h.
References CopyTemp(), and SetString().
SetString() [2/4]
virtual void IBreakIterator::SetString (const FText & InText) inline virtual
Definition at line 13 of file IBreakIterator.h.
References CopyTemp(), and SetString().
Referenced by SetString(), SetString(), and SetString().
SetString() [3/4]
virtual void IBreakIterator::SetString (const TCHAR *const InString, const int32 InStringLength) inline virtual
Definition at line 21 of file IBreakIterator.h.
References SetString(), and TEXT.
SetString() [4/4]
virtual void IBreakIterator::SetString (FString && InString) pure virtual
SetStringRef() [1/5]
virtual void IBreakIterator::SetStringRef (const FString & InString) inline virtual
Definition at line 31 of file IBreakIterator.h.
References SetStringRef().
SetStringRef() [2/5]
virtual void IBreakIterator::SetStringRef (const FString * InString) inline virtual
Definition at line 39 of file IBreakIterator.h.
References check, and SetStringRef().
SetStringRef() [3/5]
virtual void IBreakIterator::SetStringRef (const FText & InText) inline virtual
Definition at line 27 of file IBreakIterator.h.
References SetStringRef().
Referenced by ClearString(), SetStringRef(), SetStringRef(), SetStringRef(), and SetStringRef().
SetStringRef() [4/5]
virtual void IBreakIterator::SetStringRef (const TCHAR *const InString, const int32 InStringLength) inline virtual
Definition at line 35 of file IBreakIterator.h.
References SetStringRef().
SetStringRef() [5/5]
virtual void IBreakIterator::SetStringRef (FStringView InString) pure virtual
The documentation for this class was generated from the following file:
IBreakIterator.h