Unreal Engine 5.6 C++ API: FPackageObjectIndex Class Reference
FPackageObjectIndex Class Reference
#include "AsyncLoading2.h"
Public Member Functions
FPackageObjectIndex ()=default
bool IsExport () const
bool IsImport () const
bool IsNull () const
bool IsPackageImport () const
bool IsScriptImport () const
bool operator!= (FPackageObjectIndex Other) const
bool operator== (FPackageObjectIndex Other) const
uint32 ToExport () const
FPackageImportReference ToPackageImportRef () const
uint64 Value () const
Static Public Member Functions
static FPackageObjectIndex FromExportIndex (const int32 Index)
static FPackageObjectIndex FromPackageImportRef (const FPackageImportReference &PackageImportRef)
static FPackageObjectIndex FromScriptPath (const FStringView &ScriptObjectPath)
static FPackageObjectIndex FromVersePath (FUtf8StringView VersePath)
Private Types
enum EType {
Export , ScriptImport , PackageImport , Null ,
TypeCount = Null
}
Private Member Functions
FPackageObjectIndex (EType InType, uint64 InId)
Static Private Member Functions
static uint64 GenerateImportHashFromObjectPath (const FStringView &ObjectPath)
static uint64 GenerateImportHashFromVersePath (FUtf8StringView VersePath)
Private Attributes
uint64 TypeAndId = Invalid
Static Private Attributes
static constexpr uint64 IndexBits = 62ull
static constexpr uint64 IndexMask = (1ull << IndexBits) - 1ull
static constexpr uint64 Invalid = ~0ull
static constexpr uint64 TypeMask = ~IndexMask
static constexpr uint64 TypeShift = IndexBits
Friends
uint32 GetTypeHash (const FPackageObjectIndex &Value)
FArchive & operator<< (FArchive &Ar, FPackageObjectIndex &Value)
Detailed Description
Definition at line 59 of file AsyncLoading2.h.
Member Enumeration Documentation
EType
enum FPackageObjectIndex::EType private
Enumerator
Export
ScriptImport
PackageImport
Null
TypeCount
Definition at line 69 of file AsyncLoading2.h.
Constructor & Destructor Documentation
FPackageObjectIndex() [1/2]
FPackageObjectIndex::FPackageObjectIndex (EType InType, uint64 InId) inline explicit private
Definition at line 79 of file AsyncLoading2.h.
References TypeAndId, and TypeShift.
Referenced by FromExportIndex(), FromPackageImportRef(), FromScriptPath(), FromVersePath(), GetTypeHash, operator!=(), operator<<, and operator==().
FPackageObjectIndex() [2/2]
FPackageObjectIndex::FPackageObjectIndex () default
Referenced by FromExportIndex(), FromPackageImportRef(), FromScriptPath(), and FromVersePath().
Member Function Documentation
FromExportIndex()
FPackageObjectIndex FPackageObjectIndex::FromExportIndex (const int32 Index) inline static
Definition at line 87 of file AsyncLoading2.h.
References FPackageObjectIndex(), FPackageObjectIndex(), and Export.
FromPackageImportRef()
FPackageObjectIndex FPackageObjectIndex::FromPackageImportRef (const FPackageImportReference & PackageImportRef) inline static
Definition at line 108 of file AsyncLoading2.h.
References FPackageObjectIndex(), FPackageObjectIndex(), check, FPackageImportReference::GetImportedPackageIndex(), FPackageImportReference::GetImportedPublicExportHashIndex(), PackageImport, and TypeMask.
FromScriptPath()
FPackageObjectIndex FPackageObjectIndex::FromScriptPath (const FStringView & ScriptObjectPath) inline static
Definition at line 92 of file AsyncLoading2.h.
References FPackageObjectIndex(), FPackageObjectIndex(), GenerateImportHashFromObjectPath(), and ScriptImport.
FromVersePath()
FPackageObjectIndex FPackageObjectIndex::FromVersePath (FUtf8StringView VersePath) inline static
Definition at line 103 of file AsyncLoading2.h.
References FPackageObjectIndex(), FPackageObjectIndex(), GenerateImportHashFromVersePath(), and ScriptImport.
GenerateImportHashFromObjectPath()
uint64 FPackageObjectIndex::GenerateImportHashFromObjectPath (const FStringView & ObjectPath) static private
Referenced by FromScriptPath().
GenerateImportHashFromVersePath()
uint64 FPackageObjectIndex::GenerateImportHashFromVersePath (FUtf8StringView VersePath) static private
Referenced by FromVersePath().
IsExport()
bool FPackageObjectIndex::IsExport () const inline
Definition at line 120 of file AsyncLoading2.h.
References Export, TypeAndId, and TypeShift.
Referenced by ToExport().
IsImport()
bool FPackageObjectIndex::IsImport () const inline
Definition at line 125 of file AsyncLoading2.h.
References IsPackageImport(), and IsScriptImport().
IsNull()
bool FPackageObjectIndex::IsNull () const inline
Definition at line 115 of file AsyncLoading2.h.
References Invalid, and TypeAndId.
IsPackageImport()
bool FPackageObjectIndex::IsPackageImport () const inline
Definition at line 135 of file AsyncLoading2.h.
References PackageImport, TypeAndId, and TypeShift.
Referenced by FPublicExportKey::FromPackageImport(), and IsImport().
IsScriptImport()
bool FPackageObjectIndex::IsScriptImport () const inline
Definition at line 130 of file AsyncLoading2.h.
References ScriptImport, TypeAndId, and TypeShift.
Referenced by IsImport().
operator!=()
bool FPackageObjectIndex::operator!= (FPackageObjectIndex Other) const inline
Definition at line 163 of file AsyncLoading2.h.
References FPackageObjectIndex(), Other, and TypeAndId.
operator==()
bool FPackageObjectIndex::operator== (FPackageObjectIndex Other) const inline
Definition at line 158 of file AsyncLoading2.h.
References FPackageObjectIndex(), Other, and TypeAndId.
ToExport()
uint32 FPackageObjectIndex::ToExport () const inline
Definition at line 140 of file AsyncLoading2.h.
References check, IsExport(), and TypeAndId.
ToPackageImportRef()
FPackageImportReference FPackageObjectIndex::ToPackageImportRef () const inline
Definition at line 146 of file AsyncLoading2.h.
References IndexMask, and TypeAndId.
Referenced by FPublicExportKey::FromPackageImport().
Value()
uint64 FPackageObjectIndex::Value () const inline
Definition at line 153 of file AsyncLoading2.h.
References IndexMask, and TypeAndId.
Referenced by GetTypeHash, and operator<<.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPackageObjectIndex & Value) friend
Definition at line 174 of file AsyncLoading2.h.
References FPackageObjectIndex(), and Value().
operator<<
FArchive & operator<< (FArchive & Ar, FPackageObjectIndex & Value) friend
Definition at line 168 of file AsyncLoading2.h.
References FPackageObjectIndex(), Ar, and Value().
Field Documentation
IndexBits
uint64 FPackageObjectIndex::IndexBits = 62ull static constexpr private
Definition at line 61 of file AsyncLoading2.h.
IndexMask
uint64 FPackageObjectIndex::IndexMask = (1ull << IndexBits) - 1ull static constexpr private
Definition at line 62 of file AsyncLoading2.h.
Referenced by ToPackageImportRef(), and Value().
Invalid
uint64 FPackageObjectIndex::Invalid = ~0ull static constexpr private
Definition at line 65 of file AsyncLoading2.h.
Referenced by IsNull().
TypeAndId
uint64 FPackageObjectIndex::TypeAndId = Invalid private
Definition at line 67 of file AsyncLoading2.h.
Referenced by FPackageObjectIndex(), IsExport(), IsNull(), IsPackageImport(), IsScriptImport(), operator!=(), operator==(), ToExport(), ToPackageImportRef(), and Value().
TypeMask
uint64 FPackageObjectIndex::TypeMask = ~IndexMask static constexpr private
Definition at line 63 of file AsyncLoading2.h.
Referenced by FromPackageImportRef().
TypeShift
uint64 FPackageObjectIndex::TypeShift = IndexBits static constexpr private
Definition at line 64 of file AsyncLoading2.h.
Referenced by FPackageObjectIndex(), IsExport(), IsPackageImport(), and IsScriptImport().
The documentation for this class was generated from the following file:
AsyncLoading2.h