Unreal Engine 5.6 C++ API: FLazyObjectPtr Struct Reference
FLazyObjectPtr Struct Reference
FLazyObjectPtr is a type of weak pointer to a UObject that uses a GUID created at save time.
#include "LazyObjectPtr.h"
Public Member Functions
FORCEINLINE FLazyObjectPtr ()
Default constructor, sets to null.
FORCEINLINE FLazyObjectPtr (const UObject *Object)
FORCEINLINE FLazyObjectPtr (FObjectPtr Object)
Construct from object already in memory.
template<typename T>
FORCEINLINE FLazyObjectPtr (TObjectPtr< T > Object)
FORCEINLINE void FixupForPIE (int32 PIEInstance)
Fixes up this FLazyObjectPtr to target the right UID as set in PIEGuidMap, this only works for directly serialized pointers.
FORCEINLINE void operator= (const FUniqueObjectGuid &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const UObject *Object)
FORCEINLINE void operator= (FObjectPtr Object)
Copy from an object already in memory.
template<typename T>
FORCEINLINE void operator= (TObjectPtr< T > Object)
Public Member Functions inherited from TPersistentObjectPtr< FUniqueObjectGuid >
FORCEINLINE TPersistentObjectPtr ()
Default constructor, will be null.
FORCEINLINE TPersistentObjectPtr (const FUniqueObjectGuid &InObjectID)
Construct from a unique object identifier.
FORCEINLINE UObject * Get () const
Dereference the pointer, which may cause it to become valid again.
FORCEINLINE UObject * Get (bool bEvenIfPendingKill) const
Dereference the lazy pointer, which may cause it to become valid again.
FORCEINLINE FUniqueObjectGuid & GetUniqueID ()
Non-const version of the above.
FORCEINLINE const FUniqueObjectGuid & GetUniqueID () const
Gets the unique object identifier associated with this lazy pointer.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE bool operator!= (const TPersistentObjectPtr &Rhs) const
Compare pointers for inequality.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE UObject & operator* () const
Dereference the pointer.
FORCEINLINE UObject * operator-> () const
Dereference the pointer.
FORCEINLINE void operator= (const FUniqueObjectGuid &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const FWeakObjectPtr &Other)
Copy from an existing weak pointer, reserve IDs if required.
FORCEINLINE void operator= (const UObject *Object)
void operator= (FObjectPtr Object)
Copy from an object pointer.
FORCEINLINE void operator= (TObjectPtr< T > Object)
FORCEINLINE bool operator== (const TPersistentObjectPtr &Rhs) const
Compare pointers for equality.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE void Reset ()
Reset the lazy pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
Static Public Member Functions
static void PossiblySerializeObjectGuid (UObject *Object, FStructuredArchive::FRecord Record)
Called by UObject::Serialize so that we can save / load the Guid possibly associated with an object.
static void ResetPIEFixups ()
Called when entering PIE to prepare it for PIE-specific fixups.
Private Types
using Super = TPersistentObjectPtr<FUniqueObjectGuid>
Additional Inherited Members
Public Types inherited from TPersistentObjectPtr< FUniqueObjectGuid >
using ElementType
Detailed Description
FLazyObjectPtr is a type of weak pointer to a UObject that uses a GUID created at save time.
Objects will only have consistent GUIDs if they are referenced by a lazy pointer and then saved. It will change back and forth between being valid or pending as the referenced object loads or unloads. It has no impact on if the object is garbage collected or not. It can't be directly used across a network.
NOTE: Because this only stores a GUID, it does not know how to load the destination object and does not work with Play In Editor. This will be deprecated in a future engine version and new features should use FSoftObjectPtr instead.
Definition at line 150 of file LazyObjectPtr.h.
Member Typedef Documentation
Super
using FLazyObjectPtr::Super = TPersistentObjectPtr<FUniqueObjectGuid> private
Definition at line 153 of file LazyObjectPtr.h.
Constructor & Destructor Documentation
FLazyObjectPtr() [1/4]
FORCEINLINE FLazyObjectPtr::FLazyObjectPtr () inline
Default constructor, sets to null.
Definition at line 157 of file LazyObjectPtr.h.
References FORCEINLINE.
Referenced by FLazyObjectPtr(), FLazyObjectPtr(), TLazyObjectPtr< T >::TLazyObjectPtr(), TLazyObjectPtr< T >::GetLazyObjecPtrTypeHash(), TLazyObjectPtr< T >::operator!=(), TLazyObjectPtr< T >::operator=(), and TLazyObjectPtr< T >::operator==().
FLazyObjectPtr() [2/4]
FORCEINLINE FLazyObjectPtr::FLazyObjectPtr (FObjectPtr Object) inline explicit
Construct from object already in memory.
Definition at line 162 of file LazyObjectPtr.h.
References FORCEINLINE, and Object.
FLazyObjectPtr() [3/4]
FORCEINLINE FLazyObjectPtr::FLazyObjectPtr (const UObject * Object) inline explicit
Definition at line 166 of file LazyObjectPtr.h.
References FLazyObjectPtr(), FORCEINLINE, and Object.
FLazyObjectPtr() [4/4]
template<typename T> FORCEINLINE FLazyObjectPtr::FLazyObjectPtr (TObjectPtr< T > Object) inline explicit
Definition at line 171 of file LazyObjectPtr.h.
References FLazyObjectPtr(), FORCEINLINE, and Object.
Member Function Documentation
FixupForPIE()
FORCEINLINE void FLazyObjectPtr::FixupForPIE (int32 PIEInstance) inline
Fixes up this FLazyObjectPtr to target the right UID as set in PIEGuidMap, this only works for directly serialized pointers.
Definition at line 209 of file LazyObjectPtr.h.
References FUniqueObjectGuid::FixupForPIE(), FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::GetUniqueID().
operator=() [1/4]
FORCEINLINE void FLazyObjectPtr::operator= (const FUniqueObjectGuid & InObjectID) inline
Copy from a unique object identifier.
Definition at line 203 of file LazyObjectPtr.h.
References FORCEINLINE, and TPersistentObjectPtr< FUniqueObjectGuid >::operator=().
operator=() [2/4]
FORCEINLINE void FLazyObjectPtr::operator= (const UObject * Object) inline
Definition at line 186 of file LazyObjectPtr.h.
References FORCEINLINE, and Object.
operator=() [3/4]
FORCEINLINE void FLazyObjectPtr::operator= (FObjectPtr Object) inline
Copy from an object already in memory.
Definition at line 182 of file LazyObjectPtr.h.
References FORCEINLINE, Object, and TPersistentObjectPtr< FUniqueObjectGuid >::operator=().
Referenced by TLazyObjectPtr< T >::TLazyObjectPtr(), TLazyObjectPtr< T >::operator=(), TLazyObjectPtr< T >::operator=(), and TLazyObjectPtr< T >::operator=().
operator=() [4/4]
template<typename T> FORCEINLINE void FLazyObjectPtr::operator= (TObjectPtr< T > Object) inline
Definition at line 191 of file LazyObjectPtr.h.
References FORCEINLINE, and Object.
PossiblySerializeObjectGuid()
void FLazyObjectPtr::PossiblySerializeObjectGuid (UObject * Object, FStructuredArchive::FRecord Record) static
Called by UObject::Serialize so that we can save / load the Guid possibly associated with an object.
References Object, and Record.
ResetPIEFixups()
void FLazyObjectPtr::ResetPIEFixups () static
Called when entering PIE to prepare it for PIE-specific fixups.
The documentation for this struct was generated from the following file:
LazyObjectPtr.h