Unreal Engine 5.6 C++ API: UE::Core::ArrayView::Private Namespace Reference
UE::Core::ArrayView::Private Namespace Reference
Data Structures
struct TIsCompatibleRangeType
Trait testing whether a type is compatible with the view type.
struct TIsReinterpretableRangeType
Trait testing whether a type is reinterpretable in a way that permits use with the view type.
Functions
template<typename T>
FORCEINLINE decltype(auto) GetDataHelper (T &&Arg)
template<typename T>
FORCEINLINE decltype(auto) GetReinterpretedDataHelper (T &&Arg)
Variables
template<typename T, typename ElementType>
constexpr bool TIsCompatibleElementType_V =std::is_convertible_v<T**, ElementType* const*>
Trait testing whether a type is compatible with the view type.
Function Documentation
GetDataHelper()
template<typename T> FORCEINLINE decltype(auto) UE::Core::ArrayView::Private::GetDataHelper (T && Arg)
Definition at line 31 of file ArrayView.h.
References FORCEINLINE, Forward(), and GetData().
Referenced by UE::Core::ArrayView::Private::TIsCompatibleRangeType< T, ElementType >::GetData().
GetReinterpretedDataHelper()
template<typename T> FORCEINLINE decltype(auto) UE::Core::ArrayView::Private::GetReinterpretedDataHelper (T && Arg)
Definition at line 38 of file ArrayView.h.
References FORCEINLINE, Forward(), GetData(), GetNum(), TContainerElementTypeCompatibility< InElementType >::ReinterpretRangeContiguous(), and TSequenceHistory< HistorySize >::Size.
Referenced by UE::Core::ArrayView::Private::TIsReinterpretableRangeType< T, ElementType >::GetData().
Variable Documentation
TIsCompatibleElementType_V
template<typename T, typename ElementType> bool UE::Core::ArrayView::Private::TIsCompatibleElementType_V =std::is_convertible_v<T**, ElementType* const*> constexpr
Trait testing whether a type is compatible with the view type.
The extra stars here are IMPORTANT They prevent TMultiArrayView<Base>(TArray<Derived>&) from compiling!
Definition at line 26 of file ArrayView.h.