Unreal Engine 5.6 C++ API: UE::Math::TSphere< T > Struct Template Reference
UE::Math::TSphere< T > Struct Template Reference
#include "Sphere.h"
Public Types
using FReal = T
Public Member Functions
TSphere ()=default
Default constructor (no initialization).
TSphere (const TSphere< double > *Spheres, int32 Count)
template<typename FArg UE_REQUIRES>
TSphere (const TSphere< FArg > &From)
TSphere (const TSphere< float > *Spheres, int32 Count)
TSphere (const TSphere< T > *Spheres, int32 Count)
Constructor.
TSphere (const TVector< double > *Points, int32 Count)
TSphere (const TVector< float > *Points, int32 Count)
TSphere (const TVector< T > *Points, int32 Count)
Constructor.
FORCEINLINE TSphere (EForceInit)
Constructor.
TSphere (int32)
Creates and initializes a new sphere.
TSphere (TVector< T > InV, T InW)
Creates and initializes a new sphere with the specified parameters.
bool Equals (const TSphere< T > &Sphere, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Check whether two spheres are the same within specified tolerance.
T GetVolume () const
Get volume of the current sphere.
FORCEINLINE bool Intersects (const TSphere< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Test whether this sphere intersects another.
bool IsInside (const FVector &In, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether the given location is inside this sphere.
bool IsInside (const TSphere< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Check whether sphere is inside of another.
bool operator!= (const TSphere< T > &Other) const
Compares two spheres for inequality.
TSphere< T > operator+ (const TSphere< T > &Other) const
Gets the result of addition to this bounding volume.
TSphere< T > & operator+= (const TSphere< T > &Other)
Adds to this sphere to include a new bounding volume.
bool operator== (const TSphere< T > &Other) const
Compares two spheres for equality.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FString ToString () const
Get a textual representation of the sphere.
TSphere< T > TransformBy (const FTransform &M) const
Get result of Transforming sphere with Transform.
TSphere< T > TransformBy (const TMatrix< T > &M) const
Get result of Transforming sphere by Matrix.
Data Fields
TVector< T > Center
The sphere's center point.
T W
The sphere's radius.
Detailed Description
template<typename T>
struct UE::Math::TSphere< T >
Definition at line 28 of file Sphere.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TSphere< T >::FReal = T
Definition at line 31 of file Sphere.h.
Constructor & Destructor Documentation
TSphere() [1/11]
template<typename T> UE::Math::TSphere< T >::TSphere () nodiscard default
Default constructor (no initialization).
Referenced by UE::Math::TSphere< double >::operator+(), operator+=(), TransformBy(), and TransformBy().
TSphere() [2/11]
template<typename T> UE::Math::TSphere< T >::TSphere (int32) inline nodiscard
Creates and initializes a new sphere.
Parameters
int32 Passing int32 sets up zeroed sphere.
Definition at line 48 of file Sphere.h.
TSphere() [3/11]
template<typename T> UE::Math::TSphere< T >::TSphere (TVector< T > InV, T InW) inline nodiscard
Creates and initializes a new sphere with the specified parameters.
Parameters
InV Center of sphere.
InW Radius of sphere.
Definition at line 59 of file Sphere.h.
TSphere() [4/11]
template<typename T> FORCEINLINE UE::Math::TSphere< T >::TSphere (EForceInit) inline explicit nodiscard
Constructor.
Parameters
EForceInit Force Init Enum.
Definition at line 69 of file Sphere.h.
TSphere() [5/11]
template<typename T> UE::Math::TSphere< T >::TSphere (const TVector< T > * Points, int32 Count) nodiscard
Constructor.
Parameters
Points Pointer to list of points this sphere must contain.
Count How many points are in the list.
TSphere() [6/11]
template<typename T> UE::Math::TSphere< T >::TSphere (const TSphere< T > * Spheres, int32 Count) nodiscard
Constructor.
Parameters
Spheres Pointer to list of spheres this sphere must contain.
Count How many points are in the list.
TSphere() [7/11]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TSphere< T >::TSphere (const TSphere< FArg > & From) inline explicit nodiscard
Definition at line 93 of file Sphere.h.
TSphere() [8/11]
UE::Math::TSphere< float >::TSphere (const TVector< float > * Points, int32 Count)
TSphere() [9/11]
UE::Math::TSphere< double >::TSphere (const TVector< double > * Points, int32 Count)
TSphere() [10/11]
UE::Math::TSphere< float >::TSphere (const TSphere< float > * Spheres, int32 Count)
TSphere() [11/11]
UE::Math::TSphere< double >::TSphere (const TSphere< double > * Spheres, int32 Count)
Member Function Documentation
Equals()
template<typename T> bool UE::Math::TSphere< T >::Equals (const TSphere< T > & Sphere, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Check whether two spheres are the same within specified tolerance.
Parameters
Sphere The other sphere.
Tolerance Error Tolerance.
Returns
true if spheres are equal within specified tolerance, otherwise false.
Definition at line 105 of file Sphere.h.
GetVolume()
template<typename T> T UE::Math::TSphere< T >::GetVolume () const inline nodiscard
Get volume of the current sphere.
Returns
Volume (in Unreal units).
Definition at line 212 of file Sphere.h.
Intersects()
template<typename T> FORCEINLINE bool UE::Math::TSphere< T >::Intersects (const TSphere< T > & Other, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Test whether this sphere intersects another.
Parameters
Other The other sphere.
Tolerance Error tolerance.
Returns
true if spheres intersect, false otherwise.
Definition at line 186 of file Sphere.h.
IsInside() [1/2]
template<typename T> bool UE::Math::TSphere< T >::IsInside (const FVector & In, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Checks whether the given location is inside this sphere.
Parameters
In The location to test for inside the bounding volume.
Returns
true if location is inside this volume.
Definition at line 174 of file Sphere.h.
IsInside() [2/2]
template<typename T> bool UE::Math::TSphere< T >::IsInside (const TSphere< T > & Other, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Check whether sphere is inside of another.
Parameters
Other The other sphere.
Tolerance Error Tolerance.
Returns
true if sphere is inside another, otherwise false.
Definition at line 158 of file Sphere.h.
Referenced by operator+=().
operator!=()
template<typename T> bool UE::Math::TSphere< T >::operator!= (const TSphere< T > & Other) const inline nodiscard
Compares two spheres for inequality.
Parameters
Other The other sphere to compare with.
Returns
true if the spheres are not equal, false otherwise.
Definition at line 127 of file Sphere.h.
operator+()
template<typename T> TSphere< T > UE::Math::TSphere< T >::operator+ (const TSphere< T > & Other) const inline nodiscard
Gets the result of addition to this bounding volume.
Parameters
Other The other volume to add to this.
Returns
A new bounding volume.
Definition at line 138 of file Sphere.h.
operator+=()
template<typename T> TSphere< T > & UE::Math::TSphere< T >::operator+= (const TSphere< T > & Other)
Adds to this sphere to include a new bounding volume.
Parameters
Other the bounding volume to increase the bounding volume to.
Returns
Reference to this bounding volume after resizing to include the other bounding volume.
Definition at line 325 of file Sphere.h.
References TSphere(), Center, checkSlow, IsInside(), Other, UE::Math::TVector< T >::SizeSquared(), FMath::Square(), UE_KINDA_SMALL_NUMBER, UE_SMALL_NUMBER, and W.
operator==()
template<typename T> bool UE::Math::TSphere< T >::operator== (const TSphere< T > & Other) const inline nodiscard
Compares two spheres for equality.
Parameters
Other The other sphere to compare with.
Returns
true if the spheres are equal, false otherwise.
Definition at line 116 of file Sphere.h.
Serialize()
template<typename T> bool UE::Math::TSphere< T >::Serialize (FArchive & Ar) inline
Definition at line 228 of file Sphere.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TSphere< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 234 of file Sphere.h.
ToString()
template<typename T> FString UE::Math::TSphere< T >::ToString () const inline nodiscard
Get a textual representation of the sphere.
Returns
Text describing the sphere.
Definition at line 222 of file Sphere.h.
TransformBy() [1/2]
template<typename T> TSphere< T > UE::Math::TSphere< T >::TransformBy (const FTransform & M) const nodiscard
Get result of Transforming sphere with Transform.
Parameters
M Transform information.
Returns
Result of transformation.
Definition at line 314 of file Sphere.h.
References TSphere(), Center, UE::Math::TTransform< T >::GetMaximumAxisScale(), UE::Math::TTransform< T >::TransformPosition(), and W.
TransformBy() [2/2]
template<typename T> TSphere< T > UE::Math::TSphere< T >::TransformBy (const TMatrix< T > & M) const nodiscard
Get result of Transforming sphere by Matrix.
Parameters
M Matrix to transform by.
Returns
Result of transformation.
Definition at line 296 of file Sphere.h.
References TSphere(), Center, UE::Math::TMatrix< T >::M, FMath::Max, UE::Math::TMatrix< T >::TransformPosition(), W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Field Documentation
Center
template<typename T> TVector<T> UE::Math::TSphere< T >::Center
The sphere's center point.
Definition at line 34 of file Sphere.h.
Referenced by operator+=(), TransformBy(), and TransformBy().
W
template<typename T> T UE::Math::TSphere< T >::W
The sphere's radius.
Definition at line 37 of file Sphere.h.
Referenced by operator+=(), TransformBy(), and TransformBy().
The documentation for this struct was generated from the following files:
MathFwd.h
Sphere.h