Unreal Engine 5.6 C++ API: FViewportDisplayDelegate Struct Reference
FViewportDisplayDelegate Struct Reference
Wrapper to allow multiple delegate types to be held in one container for the subsystem.
#include "ViewportStatsSubsystem.h"
Public Member Functions
FViewportDisplayDelegate ()=default
FViewportDisplayDelegate (const FViewportDisplayDelegate &)=delete
FViewportDisplayDelegate (FShouldDisplayFunc &&Callback)
FViewportDisplayDelegate (FViewportDisplayCallback const &D)
FViewportDisplayDelegate (FViewportDisplayDelegate &&)=default
bool Execute (FText &OutText, FLinearColor &OutColor)
bool IsBound () const
FViewportDisplayDelegate & operator= (const FViewportDisplayDelegate &)=delete
FViewportDisplayDelegate & operator= (FViewportDisplayDelegate &&)=default
void Unbind ()
Data Fields
FShouldDisplayFunc FuncCallback
FViewportDisplayCallback FuncDynDelegate
Detailed Description
Wrapper to allow multiple delegate types to be held in one container for the subsystem.
Definition at line 22 of file ViewportStatsSubsystem.h.
Constructor & Destructor Documentation
FViewportDisplayDelegate() [1/5]
FViewportDisplayDelegate::FViewportDisplayDelegate () default
Referenced by FViewportDisplayDelegate(), FViewportDisplayDelegate(), operator=(), and operator=().
FViewportDisplayDelegate() [2/5]
FViewportDisplayDelegate::FViewportDisplayDelegate (FViewportDisplayCallback const & D) inline
Definition at line 26 of file ViewportStatsSubsystem.h.
References FuncDynDelegate.
FViewportDisplayDelegate() [3/5]
FViewportDisplayDelegate::FViewportDisplayDelegate (FShouldDisplayFunc && Callback) inline
Definition at line 30 of file ViewportStatsSubsystem.h.
References FuncCallback, and MoveTemp().
FViewportDisplayDelegate() [4/5]
FViewportDisplayDelegate::FViewportDisplayDelegate (FViewportDisplayDelegate &&) default
References FViewportDisplayDelegate().
FViewportDisplayDelegate() [5/5]
FViewportDisplayDelegate::FViewportDisplayDelegate (const FViewportDisplayDelegate &) delete
References FViewportDisplayDelegate().
Member Function Documentation
Execute()
bool FViewportDisplayDelegate::Execute (FText & OutText, FLinearColor & OutColor)
IsBound()
bool FViewportDisplayDelegate::IsBound () const inline
Definition at line 39 of file ViewportStatsSubsystem.h.
References FuncCallback, and FuncDynDelegate.
operator=() [1/2]
FViewportDisplayDelegate & FViewportDisplayDelegate::operator= (const FViewportDisplayDelegate &) delete
References FViewportDisplayDelegate().
operator=() [2/2]
FViewportDisplayDelegate & FViewportDisplayDelegate::operator= (FViewportDisplayDelegate &&) default
References FViewportDisplayDelegate().
Unbind()
void FViewportDisplayDelegate::Unbind ()
Field Documentation
FuncCallback
FShouldDisplayFunc FViewportDisplayDelegate::FuncCallback
Definition at line 35 of file ViewportStatsSubsystem.h.
Referenced by FViewportDisplayDelegate(), and IsBound().
FuncDynDelegate
FViewportDisplayCallback FViewportDisplayDelegate::FuncDynDelegate
Definition at line 34 of file ViewportStatsSubsystem.h.
Referenced by FViewportDisplayDelegate(), and IsBound().
The documentation for this struct was generated from the following file:
ViewportStatsSubsystem.h