Unreal Engine 5.6 C++ API: TComPtr< T > Class Template Reference
TComPtr< T > Class Template Reference
Smart COM object pointer.
#include "COMPointer.h"
Public Types
typedef T PointerType
Public Member Functions
TComPtr ()
Default constructor (initialized to null).
TComPtr (const TComPtr< PointerType > &Other)
Copy constructor.
TComPtr (PointerType *const Object)
Create and initialize a new instance.
TComPtr (TComPtr< PointerType > &&Other)
Move constructor.
~TComPtr ()
Destructor.
void Attach (PointerType *Object)
Set the pointer without adding a reference.
void Detach ()
Reset the pointer without releasing a reference.
HRESULT FromQueryInterface (REFIID Riid, IUnknown *Unknown)
Initialize this pointer from a COM interface to be queried.
FORCEINLINE PointerType * Get () const
Get raw pointer to the object pointed to.
FORCEINLINE const bool IsValid () const
Whether this pointer is pointing to an actual object.
FORCEINLINE operator PointerType * () const
FORCEINLINE bool operator!= (PointerType *const Object) const
FORCEINLINE PointerType ** operator& ()
FORCEINLINE PointerType * operator-> () const
TComPtr< PointerType > & operator= (const TComPtr< PointerType > &Other)
Copy assignment operator.
TComPtr< PointerType > & operator= (PointerType *const Object)
Assignment operator.
TComPtr< PointerType > & operator= (TComPtr< PointerType > &&Other)
Move assignment operator.
FORCEINLINE bool operator== (PointerType *const Object) const
void Reset ()
Reset this pointer to null.
Private Attributes
PointerType * RawPointer
Pointer to the actual object, if any.
Friends
FORCEINLINE uint32 GetTypeHash (const TComPtr< T > &InObjectPtr)
Detailed Description
template<typename T>
class TComPtr< T >
Smart COM object pointer.
Definition at line 18 of file Microsoft/COMPointer.h.
Member Typedef Documentation
PointerType
template<typename T> typedef T TComPtr< T >::PointerType
Definition at line 22 of file Microsoft/COMPointer.h.
Constructor & Destructor Documentation
TComPtr() [1/4]
template<typename T> TComPtr< T >::TComPtr () inline
Default constructor (initialized to null).
Definition at line 27 of file Microsoft/COMPointer.h.
References RawPointer.
Referenced by TComPtr(), TComPtr(), GetTypeHash, operator=(), operator=(), and operator=().
TComPtr() [2/4]
template<typename T> TComPtr< T >::TComPtr (PointerType *const Object) inline
Create and initialize a new instance.
Parameters
Object The object to point to.
Definition at line 36 of file Microsoft/COMPointer.h.
References Object, and RawPointer.
TComPtr() [3/4]
template<typename T> TComPtr< T >::TComPtr (const TComPtr< PointerType > & Other) inline
Copy constructor.
Parameters
Other The instance to copy.
Definition at line 50 of file Microsoft/COMPointer.h.
References TComPtr(), Other, and RawPointer.
TComPtr() [4/4]
template<typename T> TComPtr< T >::TComPtr (TComPtr< PointerType > && Other) inline
Move constructor.
Parameters
Other The instance to move.
Definition at line 64 of file Microsoft/COMPointer.h.
References TComPtr(), Other, and RawPointer.
~TComPtr()
template<typename T> TComPtr< T >::~TComPtr () inline
Destructor.
Definition at line 142 of file Microsoft/COMPointer.h.
References RawPointer.
Member Function Documentation
Attach()
template<typename T> void TComPtr< T >::Attach (PointerType * Object) inline
Set the pointer without adding a reference.
Parameters
InRawPointer The object to point to.
See also
Detach
Definition at line 186 of file Microsoft/COMPointer.h.
References Object, and RawPointer.
Detach()
template<typename T> void TComPtr< T >::Detach () inline
Reset the pointer without releasing a reference.
See also
Attach
Definition at line 201 of file Microsoft/COMPointer.h.
References RawPointer.
FromQueryInterface()
template<typename T> HRESULT TComPtr< T >::FromQueryInterface (REFIID Riid, IUnknown * Unknown) inline
Initialize this pointer from a COM interface to be queried.
Parameters
Riid The ID of the interface to be queried.
Unknown The object to query the interface from.
Returns
The result code of the query.
Definition at line 213 of file Microsoft/COMPointer.h.
References RawPointer, and Unknown.
Get()
template<typename T> FORCEINLINE PointerType * TComPtr< T >::Get () const inline
Get raw pointer to the object pointed to.
Returns
Pointer to the object, or NULL if not valid.
See also
IsValid
Definition at line 230 of file Microsoft/COMPointer.h.
References FORCEINLINE, and RawPointer.
IsValid()
template<typename T> FORCEINLINE const bool TComPtr< T >::IsValid () const inline
Whether this pointer is pointing to an actual object.
Returns
true if the pointer is valid, false otherwise.
See also
Get
Definition at line 241 of file Microsoft/COMPointer.h.
References FORCEINLINE, and RawPointer.
operator PointerType *()
template<typename T> FORCEINLINE TComPtr< T >::operator PointerType * () const inline
Definition at line 173 of file Microsoft/COMPointer.h.
References FORCEINLINE, and RawPointer.
operator!=()
template<typename T> FORCEINLINE bool TComPtr< T >::operator!= (PointerType *const Object) const inline
Definition at line 168 of file Microsoft/COMPointer.h.
References FORCEINLINE, Object, and RawPointer.
operator&()
template<typename T> FORCEINLINE PointerType ** TComPtr< T >::operator& () inline
Definition at line 152 of file Microsoft/COMPointer.h.
References FORCEINLINE, and RawPointer.
operator->()
template<typename T> FORCEINLINE PointerType * TComPtr< T >::operator-> () const inline
Definition at line 157 of file Microsoft/COMPointer.h.
References check, FORCEINLINE, and RawPointer.
operator=() [1/3]
template<typename T> TComPtr< PointerType > & TComPtr< T >::operator= (const TComPtr< PointerType > & Other) inline
Copy assignment operator.
Parameters
Other The instance to copy.
Definition at line 100 of file Microsoft/COMPointer.h.
References TComPtr(), Other, and RawPointer.
operator=() [2/3]
template<typename T> TComPtr< PointerType > & TComPtr< T >::operator= (PointerType *const Object) inline
Assignment operator.
Parameters
Object The object to point to.
Definition at line 75 of file Microsoft/COMPointer.h.
References TComPtr(), Object, and RawPointer.
operator=() [3/3]
template<typename T> TComPtr< PointerType > & TComPtr< T >::operator= (TComPtr< PointerType > && Other) inline
Move assignment operator.
Parameters
Other The instance to move.
Definition at line 125 of file Microsoft/COMPointer.h.
References TComPtr(), Other, and RawPointer.
operator==()
template<typename T> FORCEINLINE bool TComPtr< T >::operator== (PointerType *const Object) const inline
Definition at line 163 of file Microsoft/COMPointer.h.
References FORCEINLINE, Object, and RawPointer.
Reset()
template<typename T> void TComPtr< T >::Reset () inline
Reset this pointer to null.
Definition at line 247 of file Microsoft/COMPointer.h.
References RawPointer.
Friends And Related Symbol Documentation
GetTypeHash
template<typename T> FORCEINLINE uint32 GetTypeHash (const TComPtr< T > & InObjectPtr) friend
Definition at line 261 of file Microsoft/COMPointer.h.
References TComPtr(), FORCEINLINE, GetTypeHash, and RawPointer.
Referenced by GetTypeHash.
Field Documentation
RawPointer
template<typename T> PointerType* TComPtr< T >::RawPointer private
Pointer to the actual object, if any.
Definition at line 259 of file Microsoft/COMPointer.h.
Referenced by TComPtr(), TComPtr(), TComPtr(), TComPtr(), ~TComPtr(), Attach(), Detach(), FromQueryInterface(), Get(), GetTypeHash, IsValid(), operator PointerType *(), operator!=(), operator&(), operator->(), operator=(), operator=(), operator=(), operator==(), and Reset().
The documentation for this class was generated from the following file:
Microsoft/COMPointer.h