Unreal Engine 5.6 C++ API: Audio::FConvolutionReverb::FChannelFormatConverterWrapper Class Reference
Audio::FConvolutionReverb::FChannelFormatConverterWrapper Class Reference
Public Member Functions
FChannelFormatConverterWrapper ()=default
FChannelFormatConverterWrapper (const FChannelFormatConverterWrapper &InOther)=delete
FChannelFormatConverterWrapper (FChannelFormatConverterWrapper &&InOther)
FChannelFormatConverterWrapper (TUniquePtr< FSimpleUpmixer > InConverter)
FChannelFormatConverterWrapper (TUniquePtr< IChannelFormatConverter > InConverter)
const FInputFormat & GetInputFormat () const
const FOutputFormat & GetOutputFormat () const
bool GetRearChannelFlip () const
bool IsValid () const
FChannelFormatConverterWrapper & operator= (const FChannelFormatConverterWrapper &InOther)=delete
FChannelFormatConverterWrapper & operator= (FChannelFormatConverterWrapper &&InOther)
void ProcessAudio (const TArray< FAlignedFloatBuffer > &InInputBuffers, TArray< FAlignedFloatBuffer > &OutOutputBuffers)
void SetRearChannelBleed (float InGain, bool bFadeToGain=true)
void SetRearChannelFlip (bool bInDoRearChannelFlip, bool bFadeFlip=true)
Private Attributes
IChannelFormatConverter * BaseConverter = nullptr
FSimpleUpmixer * SimpleUpmixer = nullptr
TUniquePtr< IChannelFormatConverter > Storage
Static Private Attributes
static FInputFormat DefaultInputFormat
static FOutputFormat DefaultOutputFormat
Detailed Description
Definition at line 184 of file ConvolutionReverb.h.
Constructor & Destructor Documentation
FChannelFormatConverterWrapper() [1/5]
Audio::FConvolutionReverb::FChannelFormatConverterWrapper::FChannelFormatConverterWrapper () default
Referenced by FChannelFormatConverterWrapper(), FChannelFormatConverterWrapper(), operator=(), and operator=().
FChannelFormatConverterWrapper() [2/5]
Audio::FConvolutionReverb::FChannelFormatConverterWrapper::FChannelFormatConverterWrapper (TUniquePtr< FSimpleUpmixer > InConverter)
FChannelFormatConverterWrapper() [3/5]
Audio::FConvolutionReverb::FChannelFormatConverterWrapper::FChannelFormatConverterWrapper (TUniquePtr< IChannelFormatConverter > InConverter)
FChannelFormatConverterWrapper() [4/5]
Audio::FConvolutionReverb::FChannelFormatConverterWrapper::FChannelFormatConverterWrapper (FChannelFormatConverterWrapper && InOther)
References FChannelFormatConverterWrapper().
FChannelFormatConverterWrapper() [5/5]
Audio::FConvolutionReverb::FChannelFormatConverterWrapper::FChannelFormatConverterWrapper (const FChannelFormatConverterWrapper & InOther) delete
References FChannelFormatConverterWrapper().
Member Function Documentation
GetInputFormat()
const FInputFormat & Audio::FConvolutionReverb::FChannelFormatConverterWrapper::GetInputFormat () const
GetOutputFormat()
const FOutputFormat & Audio::FConvolutionReverb::FChannelFormatConverterWrapper::GetOutputFormat () const
GetRearChannelFlip()
bool Audio::FConvolutionReverb::FChannelFormatConverterWrapper::GetRearChannelFlip () const
IsValid()
bool Audio::FConvolutionReverb::FChannelFormatConverterWrapper::IsValid () const
operator=() [1/2]
FChannelFormatConverterWrapper & Audio::FConvolutionReverb::FChannelFormatConverterWrapper::operator= (const FChannelFormatConverterWrapper & InOther) delete
References FChannelFormatConverterWrapper().
operator=() [2/2]
FChannelFormatConverterWrapper & Audio::FConvolutionReverb::FChannelFormatConverterWrapper::operator= (FChannelFormatConverterWrapper && InOther)
References FChannelFormatConverterWrapper().
ProcessAudio()
void Audio::FConvolutionReverb::FChannelFormatConverterWrapper::ProcessAudio (const TArray< FAlignedFloatBuffer > & InInputBuffers, TArray< FAlignedFloatBuffer > & OutOutputBuffers)
SetRearChannelBleed()
void Audio::FConvolutionReverb::FChannelFormatConverterWrapper::SetRearChannelBleed (float InGain, bool bFadeToGain = true)
SetRearChannelFlip()
void Audio::FConvolutionReverb::FChannelFormatConverterWrapper::SetRearChannelFlip (bool bInDoRearChannelFlip, bool bFadeFlip = true)
Field Documentation
BaseConverter
IChannelFormatConverter* Audio::FConvolutionReverb::FChannelFormatConverterWrapper::BaseConverter = nullptr private
Definition at line 214 of file ConvolutionReverb.h.
DefaultInputFormat
FInputFormat Audio::FConvolutionReverb::FChannelFormatConverterWrapper::DefaultInputFormat static private
Definition at line 217 of file ConvolutionReverb.h.
DefaultOutputFormat
FOutputFormat Audio::FConvolutionReverb::FChannelFormatConverterWrapper::DefaultOutputFormat static private
Definition at line 218 of file ConvolutionReverb.h.
SimpleUpmixer
FSimpleUpmixer* Audio::FConvolutionReverb::FChannelFormatConverterWrapper::SimpleUpmixer = nullptr private
Definition at line 215 of file ConvolutionReverb.h.
Storage
TUniquePtr<IChannelFormatConverter> Audio::FConvolutionReverb::FChannelFormatConverterWrapper::Storage private
Definition at line 212 of file ConvolutionReverb.h.
The documentation for this class was generated from the following file:
ConvolutionReverb.h