Unreal Engine 5.6 C++ API: FAnimPhysPose Struct Reference
FAnimPhysPose Struct Reference
Defines a transform (Position/Orientation) for an anim phys object without scaling.
#include "AnimPhysicsSolver.h"
Public Member Functions
FAnimPhysPose ()
FAnimPhysPose (const FVector &InPosition, const FQuat &InOrient)
FAnimPhysPose Inverse () const
FMatrix Matrix () const
FAnimPhysPose operator* (const FAnimPhysPose &InPose) const
FVector operator* (const FVector &InPoint) const
FPlane TransformPlane (const FPlane &InPlane)
Data Fields
FQuat Orientation
FVector Position
Detailed Description
Defines a transform (Position/Orientation) for an anim phys object without scaling.
Definition at line 114 of file AnimPhysicsSolver.h.
Constructor & Destructor Documentation
FAnimPhysPose() [1/2]
FAnimPhysPose::FAnimPhysPose (const FVector & InPosition, const FQuat & InOrient) inline
Definition at line 119 of file AnimPhysicsSolver.h.
References FVector, Orientation, and Position.
Referenced by Inverse(), and operator*().
FAnimPhysPose() [2/2]
FAnimPhysPose::FAnimPhysPose () inline
Definition at line 124 of file AnimPhysicsSolver.h.
References FVector, Orientation, and Position.
Referenced by Inverse(), and operator*().
Member Function Documentation
Inverse()
FAnimPhysPose FAnimPhysPose::Inverse () const inline
Definition at line 131 of file AnimPhysicsSolver.h.
References FAnimPhysPose(), FAnimPhysPose(), FVector, Orientation, and Position.
Matrix()
FMatrix FAnimPhysPose::Matrix () const inline
Definition at line 138 of file AnimPhysicsSolver.h.
References Orientation, Position, and UE::Math::TTransform< T >::ToMatrixNoScale().
operator*() [1/2]
FAnimPhysPose FAnimPhysPose::operator* (const FAnimPhysPose & InPose) const inline
Definition at line 148 of file AnimPhysicsSolver.h.
References FAnimPhysPose(), FAnimPhysPose(), Orientation, and Position.
operator*() [2/2]
FVector FAnimPhysPose::operator* (const FVector & InPoint) const inline
Definition at line 143 of file AnimPhysicsSolver.h.
References FVector, Orientation, and Position.
TransformPlane()
FPlane FAnimPhysPose::TransformPlane (const FPlane & InPlane) inline
Definition at line 153 of file AnimPhysicsSolver.h.
References UE::Math::TVector< double >::DotProduct(), FVector, Orientation, Position, UE::Math::TPlane< T >::W, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Field Documentation
Orientation
FQuat FAnimPhysPose::Orientation
Definition at line 117 of file AnimPhysicsSolver.h.
Referenced by FAnimPhysPose(), FAnimPhysPose(), Inverse(), Matrix(), operator*(), operator*(), and TransformPlane().
Position
FVector FAnimPhysPose::Position
Definition at line 116 of file AnimPhysicsSolver.h.
Referenced by FAnimPhysPose(), FAnimPhysPose(), Inverse(), Matrix(), operator*(), operator*(), and TransformPlane().
The documentation for this struct was generated from the following file:
AnimPhysicsSolver.h