Unreal Engine 5.6 C++ API: UE::Geometry::FQueueRemesher Class Reference
UE::Geometry::FQueueRemesher Class Reference
Extension to Remesher that is smarter about which edges/vertices to touch:
#include "QueueRemesher.h"
Data Structures
struct SettingState
Public Member Functions
FQueueRemesher (FDynamicMesh3 *MeshIn)
void BasicRemeshPass () override
"Outer loop" for all remeshing operations
DYNAMICMESH_API void FastestRemesh ()
Converge on remeshed result as quickly as possible.
Public Member Functions inherited from UE::Geometry::FRemesher
FRemesher (FDynamicMesh3 *MeshIn)
virtual ~FRemesher ()
virtual void OnEdgeCollapse (int EdgeID, int VertexA, int VertexB, const FDynamicMesh3::FEdgeCollapseInfo &CollapseInfo)
Callback for subclasses to override to implement custom behavior.
virtual void OnEdgeFlip (int EdgeID, const FDynamicMesh3::FEdgeFlipInfo &FlipInfo)
Callback for subclasses to override to implement custom behavior.
virtual DYNAMICMESH_API void Precompute ()
We can speed things up if we precompute some invariants.
DYNAMICMESH_API void SetTargetEdgeLength (double fLength)
Set min/max edge-lengths to sane values for given target edge length.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase (const FMeshRefinerBase &)=delete
FMeshRefinerBase (FMeshRefinerBase &&)=delete
virtual ~FMeshRefinerBase ()
virtual bool Cancelled ()
If this returns true, abort computation.
const TOptional< FMeshConstraints > & GetConstraints ()
Get the current mesh constraints.
double GetEdgeFlipTolerance ()
FDynamicMesh3 * GetMesh ()
Get the current mesh we are operating on.
FMeshRefinerBase & operator= (const FMeshRefinerBase &)=delete
FMeshRefinerBase & operator= (FMeshRefinerBase &&)=delete
IProjectionTarget * ProjectionTarget ()
Get the current Projection Target.
void SetEdgeFlipTolerance (double NewTolerance)
Set edge flip tolerance.
void SetExternalConstraints (TOptional< FMeshConstraints > ConstraintsIn)
Set external constraints.
DYNAMICMESH_API void SetMeshChangeTracker (FDynamicMeshChangeTracker *Tracker)
void SetProjectionTarget (IProjectionTarget *TargetIn)
Set a Projection Target.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBaseFixLayout
virtual ~FMeshRefinerBaseFixLayout ()=default
Data Fields
int MaxFastSplitIterations = 20
Max number of passes just doing edge splits.
int MaxRemeshIterations = 20
Max number of passes doing full remeshing operations.
double MinActiveEdgeFraction = 0.01
If fraction of active edges falls below this threshold, consider result converged and terminate before MaxRemeshIterations.
Data Fields inherited from UE::Geometry::FRemesher
bool bEnableCollapses = true
Controls whether edge collapses are allowed during remeshing pass.
bool bEnableFlips = true
Controls whether edge-flips are allowed during remeshing pass.
bool bEnableParallelProjection = true
enable parallel projection.
bool bEnableParallelSmooth = true
Enable parallel smoothing.
bool bEnableSmoothing = true
Controls whether vertex smoothing is applied during remeshing pass.
bool bEnableSmoothInPlace = false
If smoothing is done in-place, we don't need an extra buffer, but also there will some randomness introduced in results.
bool bEnableSplits = true
Controls whether edge splits are allowed during remeshing pass.
bool bPreventNormalFlips = false
Controls whether we try to prevent normal flips inside operations and smoothing.
bool bPreventTinyTriangles = false
Controls whether we disallow creation of triangles with small areas inside edge operations.
TFunction< double(const FDynamicMesh3 &Mesh, int VertexA, int VertexB)> CustomEdgeLengthScaleF
Scale the computed edge length to allow for adaptive remeshing.
TFunction< FVector3d(const FDynamicMesh3 &, int, double)> CustomSmoothF
Override default smoothing function.
TFunction< double(const FDynamicMesh3 &, int)> CustomSmoothSpeedF
Override constant SmoothSpeedT with function.
EFlipMetric FlipMetric = EFlipMetric::OptimalValence
Type of flip metric that will be applied.
double MaxEdgeLength = 3.0
Maximum target edge length.
double MinEdgeLength = 1.0
Minimum target edge length.
double MinLengthFlipThresh = 0.9
For MinEdgeLength metric, only flip if NewLength < (MinLengthFlipThresh * CurLength)
int ModifiedEdgesLastPass = 0
Number of edges that were modified in previous Remesh pass.
double SmoothSpeedT = 0.1
Smoothing speed, in range [0,1].
ESmoothTypes SmoothType = ESmoothTypes::Uniform
Type of smoothing that will be applied unless overridden by CustomSmoothF.
Data Fields inherited from UE::Geometry::FMeshRefinerBase
bool AllowCollapseFixedVertsWithSameSetID = true
If true, then when two Fixed vertices have the same non-invalid SetID, we treat them as not fixed and allow collapse.
int DEBUG_CHECK_LEVEL = 0
0 = no checking, 1 = check constraints each pass, 2 = and check validity each pass, 3 = and check validity after every mesh change (v slow but best for debugging)
TArray< int > DebugEdges
This is a debugging aid, will break to debugger if these edges are touched, in debug builds.
bool ENABLE_PROFILING = false
Set to true to profile various passes.
FProgressCancel * Progress = nullptr
Set this to be able to cancel running Remesher/Reducer.
ETargetProjectionMode ProjectionMode = ETargetProjectionMode::NoProjection
Method to use to project vertices onto target surface.
TFunction< EVertexControl(int)> VertexControlF = nullptr
This function allows client to specify fine-grained control over what happens to specific vertices.
Protected Member Functions
DYNAMICMESH_API int FastSplitIteration ()
This pass only does edge splits and enqueues modified vertex neighborhoods.
virtual DYNAMICMESH_API void InitializeVertexBufferForPass ()
void OnEdgeSplit (int EdgeID, int VertexA, int VertexB, const FDynamicMesh3::FEdgeSplitInfo &SplitInfo) final
Callback for subclasses to override to implement custom behavior.
void PopState ()
void PushState ()
void QueueEdge (int eid)
void QueueOneRing (int vid)
DYNAMICMESH_API void RemeshIteration (TFunctionRef< bool(void)> EarlyTerminationCheck)
This pass does all edge operations plug smoothing and reprojection.
void ResetQueue ()
virtual DYNAMICMESH_API void TrackedFullProjectionPass (bool bParallel)
DYNAMICMESH_API void TrackedFullSmoothPass_Buffer (bool bParallel)
DYNAMICMESH_API void TrackedMoveVerticesParallel (TFunction< FVector3d(int, bool &)> NewVertexPosition)
Protected Member Functions inherited from UE::Geometry::FRemesher
FRemesher ()
virtual DYNAMICMESH_API void ApplyToProjectVertices (const TFunction< void(int)> &VertexProjectFunc)
virtual DYNAMICMESH_API void ApplyToSmoothVertices (const TFunction< void(int)> &VertexSmoothFunc)
virtual DYNAMICMESH_API void ApplyVertexBuffer (bool bParallel)
virtual DYNAMICMESH_API FVector3d ComputeSmoothedVertexPos (int VertexID, TFunction< FVector3d(const FDynamicMesh3 &, int, double)> SmoothFunc, bool &bModified)
bool EnableInlineProjection () const
virtual DYNAMICMESH_API void FullProjectionPass (bool bParallel)
virtual DYNAMICMESH_API void FullSmoothPass_Buffer (bool bParallel)
virtual int GetNextEdge (int CurEdgeID, bool &bDone)
virtual DYNAMICMESH_API FVector3d GetProjectedCollapsePosition (int VertexID, const FVector3d &vNewPos)
virtual DYNAMICMESH_API TFunction< FVector3d(const FDynamicMesh3 &, int, double)> GetSmoothFunction ()
DYNAMICMESH_API void MoveVerticesParallel (TFunction< FVector3d(int, bool &)> NewVertexPosition)
virtual DYNAMICMESH_API EProcessResult ProcessEdge (int edgeID)
virtual void ProfileBeginCollapse ()
virtual void ProfileBeginFlip ()
virtual void ProfileBeginOps ()
virtual void ProfileBeginPass ()
virtual void ProfileBeginProject ()
virtual void ProfileBeginSmooth ()
virtual void ProfileBeginSplit ()
virtual void ProfileEndCollapse ()
virtual void ProfileEndFlip ()
virtual void ProfileEndOps ()
virtual void ProfileEndPass ()
virtual void ProfileEndProject ()
virtual void ProfileEndSmooth ()
virtual void ProfileEndSplit ()
virtual DYNAMICMESH_API void ProjectVertex (int VertexID, IProjectionTarget *UseTarget)
virtual int StartEdges ()
virtual DYNAMICMESH_API void UpdateAfterSplit (int edgeID, int va, int vb, const FDynamicMesh3::FEdgeSplitInfo &splitInfo)
Protected Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase ()
FMeshRefinerBase (FDynamicMesh3 *MeshIn)
DYNAMICMESH_API bool CanCollapseEdge (int eid, int a, int b, int c, int d, int tc, int td, int &collapse_to) const
Figure out if we can collapse edge eid=[a,b] under current constraint set.
DYNAMICMESH_API bool CanCollapseVertex (int eid, int a, int b, int &collapse_to) const
Resolve vertex constraints for collapsing edge eid=[a,b].
DYNAMICMESH_API bool CheckIfCollapseCreatesFlipOrInvalid (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a face-normal flip.
DYNAMICMESH_API bool CheckIfCollapseCreatesTinyTriangle (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a triangle with small area (either all vertices are close together, or in a sliver configuration) This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings.
DYNAMICMESH_API bool CheckIfFlipCreatesTinyTriangle (int OriginalEdgeVertexA, int OriginalEdgeVertexB, int OppositeEdgeVertexC, int OppositeEdgeVertexD, int OriginalTriangleIndex) const
Check if edge flip might create a triangle with small area (either all vertices are close together, or in a sliver configuration)
DYNAMICMESH_API bool CheckIfFlipInvertsNormals (int a, int b, int c, int d, int t0) const
Check if edge flip might reverse normal direction.
double ComputeEdgeFlipMetric (const FVector3d &Direction0, const FVector3d &Direction1) const
DYNAMICMESH_API void DebugCheckUVSeamConstraints ()
DYNAMICMESH_API void DebugCheckVertexConstraints ()
virtual DYNAMICMESH_API void DoDebugChecks (bool bEndOfPass=false)
FVertexConstraint GetVertexConstraint (int VertexID)
bool GetVertexConstraint (int VertexID, FVertexConstraint &OutConstraint)
bool IsVertexPositionConstrained (int VertexID)
DYNAMICMESH_API void RuntimeDebugCheck (int EdgeID)
virtual DYNAMICMESH_API void SaveEdgeBeforeModify (int32 EdgeID)
virtual DYNAMICMESH_API void SaveTriangleBeforeModify (int32 TriangleID)
virtual DYNAMICMESH_API void SaveVertexTrianglesBeforeModify (int32 VertexID)
Protected Attributes
TSet< int > EdgeBuffer
TArray< bool > EdgeShouldBeQueuedBuffer
TOptional< TSet< int > > ModifiedEdges
TFunction< void(int, int, int, int)> PostEdgeSplitFunction
SettingState SavedState
Protected Attributes inherited from UE::Geometry::FRemesher
bool bMeshIsClosed = false
we can avoid some checks/etc if we know that the mesh has no boundary edges.
int COUNT_COLLAPSES
int COUNT_FLIPS
int COUNT_SPLITS
uint64 MaxEdgeID = 0
TArray< bool > TempFlagBuffer
TDynamicVector< FVector3d > TempPosBuffer
Protected Attributes inherited from UE::Geometry::FMeshRefinerBase
FDynamicMeshChangeTracker * ActiveChangeTracker = nullptr
TOptional< FMeshConstraints > Constraints
Constraints are used to control how certain edges and vertices can be modified.
double EdgeFlipTolerance = 0.0f
If normals dot product is less than this, we consider it a normal flip.
FDynamicMesh3 * Mesh = nullptr
Mesh that will be refined.
IProjectionTarget * ProjTarget = nullptr
Vertices can be projected onto this surface when they are modified.
double TinyTriangleThreshold = SMALL_NUMBER
Avoid creation of triangles smaller than this value.
Additional Inherited Members
Public Types inherited from UE::Geometry::FRemesher
enum class EFlipMetric { OptimalValence = 0 , MinEdgeLength = 1 }
Available Edge Flip metrics.
enum class ESmoothTypes { Uniform = 0 , Cotan = 1 , MeanValue = 2 }
Built-in Smoothing types.
Public Types inherited from UE::Geometry::FMeshRefinerBase
enum class ETargetProjectionMode : uint8 { NoProjection = 0 , AfterRefinement = 1 , Inline = 2 }
Options for projecting vertices onto target surface.
enum class EVertexControl : uint8 { AllowAll = 0 , NoSmooth = 1 , NoProject = 2 , NoMovement = NoSmooth | NoProject }
Protected Types inherited from UE::Geometry::FRemesher
enum class EProcessResult {
Ok_Collapsed , Ok_Flipped , Ok_Split , Ignored_EdgeIsFine ,
Ignored_EdgeIsFullyConstrained , Failed_OpNotSuccessful , Failed_NotAnEdge
}
Detailed Description
Extension to Remesher that is smarter about which edges/vertices to touch:
A buffer tracks edges that were affected on last pass, and hence might need to be updated
FastSplitIteration() just does splits, to reach target edge length as quickly as possible
RemeshIteration() applies remesh pass for modified edges
TrackedFullSmoothPass_Buffer() smooths all vertices but only adds to queue if edge changes enough
TrackedFullProjectionPass() projects all vertices but only adds to queue if edge changes enough
Definition at line 24 of file QueueRemesher.h.
Constructor & Destructor Documentation
FQueueRemesher()
UE::Geometry::FQueueRemesher::FQueueRemesher (FDynamicMesh3 * MeshIn) inline
Definition at line 29 of file QueueRemesher.h.
References UE::Geometry::FRemesher::FRemesher().
Referenced by UE::Geometry::FNormalFlowRemesher::FNormalFlowRemesher().
Member Function Documentation
BasicRemeshPass()
void UE::Geometry::FQueueRemesher::BasicRemeshPass () inline override virtual
"Outer loop" for all remeshing operations
Reimplemented from UE::Geometry::FRemesher.
Definition at line 44 of file QueueRemesher.h.
References FastestRemesh().
FastestRemesh()
DYNAMICMESH_API void UE::Geometry::FQueueRemesher::FastestRemesh ()
Converge on remeshed result as quickly as possible.
Referenced by BasicRemeshPass().
FastSplitIteration()
DYNAMICMESH_API int UE::Geometry::FQueueRemesher::FastSplitIteration () protected
This pass only does edge splits and enqueues modified vertex neighborhoods.
Returns
Number of split edges.
InitializeVertexBufferForPass()
virtual DYNAMICMESH_API void UE::Geometry::FQueueRemesher::InitializeVertexBufferForPass () protected virtual
Reimplemented from UE::Geometry::FRemesher.
Referenced by UE::Geometry::FNormalFlowRemesher::InitializeVertexBufferForFacePass().
OnEdgeSplit()
void UE::Geometry::FQueueRemesher::OnEdgeSplit (int EdgeID, int VertexA, int VertexB, const FDynamicMesh3::FEdgeSplitInfo & SplitInfo) inline final protected virtual
Callback for subclasses to override to implement custom behavior.
Reimplemented from UE::Geometry::FRemesher.
Definition at line 66 of file QueueRemesher.h.
References PostEdgeSplitFunction.
PopState()
void UE::Geometry::FQueueRemesher::PopState () inline protected
Definition at line 105 of file QueueRemesher.h.
References UE::Geometry::FRemesher::bEnableCollapses, UE::Geometry::FRemesher::bEnableFlips, UE::Geometry::FRemesher::bEnableSmoothing, UE::Geometry::FRemesher::bEnableSplits, UE::Geometry::FRemesher::MaxEdgeLength, UE::Geometry::FRemesher::MinEdgeLength, UE::Geometry::FMeshRefinerBase::ProjectionMode, SavedState, UE::Geometry::FRemesher::SmoothSpeedT, and UE::Geometry::FRemesher::SmoothType.
PushState()
void UE::Geometry::FQueueRemesher::PushState () inline protected
Definition at line 92 of file QueueRemesher.h.
References UE::Geometry::FRemesher::bEnableCollapses, UE::Geometry::FRemesher::bEnableFlips, UE::Geometry::FRemesher::bEnableSmoothing, UE::Geometry::FRemesher::bEnableSplits, UE::Geometry::FRemesher::MaxEdgeLength, UE::Geometry::FRemesher::MinEdgeLength, UE::Geometry::FMeshRefinerBase::ProjectionMode, SavedState, UE::Geometry::FRemesher::SmoothSpeedT, and UE::Geometry::FRemesher::SmoothType.
QueueEdge()
void UE::Geometry::FQueueRemesher::QueueEdge (int eid) inline protected
Definition at line 131 of file QueueRemesher.h.
References check, and ModifiedEdges.
QueueOneRing()
void UE::Geometry::FQueueRemesher::QueueOneRing (int vid) inline protected
Definition at line 119 of file QueueRemesher.h.
References check, UE::Geometry::FMeshRefinerBase::Mesh, and ModifiedEdges.
RemeshIteration()
DYNAMICMESH_API void UE::Geometry::FQueueRemesher::RemeshIteration (TFunctionRef< bool(void)> EarlyTerminationCheck) protected
This pass does all edge operations plug smoothing and reprojection.
EarlyTerminationCheck will be called after remesh operations, before smoothing/reprojection. Caller can return true to abort further computation.
ResetQueue()
void UE::Geometry::FQueueRemesher::ResetQueue () inline protected
Definition at line 137 of file QueueRemesher.h.
References ModifiedEdges.
TrackedFullProjectionPass()
virtual DYNAMICMESH_API void UE::Geometry::FQueueRemesher::TrackedFullProjectionPass (bool bParallel) protected virtual
Reimplemented in UE::Geometry::FNormalFlowRemesher.
TrackedFullSmoothPass_Buffer()
DYNAMICMESH_API void UE::Geometry::FQueueRemesher::TrackedFullSmoothPass_Buffer (bool bParallel) protected
TrackedMoveVerticesParallel()
DYNAMICMESH_API void UE::Geometry::FQueueRemesher::TrackedMoveVerticesParallel (TFunction< FVector3d(int, bool &)> NewVertexPosition) protected
Field Documentation
EdgeBuffer
TSet<int> UE::Geometry::FQueueRemesher::EdgeBuffer protected
Definition at line 60 of file QueueRemesher.h.
EdgeShouldBeQueuedBuffer
TArray<bool> UE::Geometry::FQueueRemesher::EdgeShouldBeQueuedBuffer protected
Definition at line 151 of file QueueRemesher.h.
MaxFastSplitIterations
int UE::Geometry::FQueueRemesher::MaxFastSplitIterations = 20
Max number of passes just doing edge splits.
Definition at line 32 of file QueueRemesher.h.
MaxRemeshIterations
int UE::Geometry::FQueueRemesher::MaxRemeshIterations = 20
Max number of passes doing full remeshing operations.
Definition at line 35 of file QueueRemesher.h.
MinActiveEdgeFraction
double UE::Geometry::FQueueRemesher::MinActiveEdgeFraction = 0.01
If fraction of active edges falls below this threshold, consider result converged and terminate before MaxRemeshIterations.
Definition at line 38 of file QueueRemesher.h.
ModifiedEdges
TOptional<TSet<int> > UE::Geometry::FQueueRemesher::ModifiedEdges protected
Definition at line 57 of file QueueRemesher.h.
Referenced by QueueEdge(), QueueOneRing(), and ResetQueue().
PostEdgeSplitFunction
TFunction<void(int, int, int, int)> UE::Geometry::FQueueRemesher::PostEdgeSplitFunction protected
Definition at line 63 of file QueueRemesher.h.
Referenced by OnEdgeSplit().
SavedState
SettingState UE::Geometry::FQueueRemesher::SavedState protected
Definition at line 90 of file QueueRemesher.h.
Referenced by PopState(), and PushState().
The documentation for this class was generated from the following file:
QueueRemesher.h