Unreal Engine 5.6 C++ Documentation: FActiveDeviceProperty Struct Reference
FActiveDeviceProperty Struct Reference
Contains a pointer to an active device property and keeps track of how long it has been evaluated for.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceSubsystem.h>
Public Member Functions
FActiveDeviceProperty ()
bool operator== (const FActiveDeviceProperty &Other) const
bool operator!= (const FActiveDeviceProperty &Other) const
Public Attributes
TWeakObjectPtr< UInputDeviceProperty > Property
The active device property.
double EvaluatedDuration
How long this property has been evaluated for.
FPlatformUserId PlatformUser
The platform user that is actively receiving this device property.
FInputDeviceId DeviceId
The input device id that should receive this property.
FInputDevicePropertyHandle PropertyHandle
The handle of this active property.
uint8 bLooping: 1
If true, then the input device property will not be removed after it's evaluation time has completed.
uint8 bIgnoreTimeDilation: 1
If true, then this device property will ignore dilated delta time and use the Applications delta time instead.
uint8 bPlayWhilePaused: 1
If true, then this device property will be played even if the game world is paused.
uint8 bHasBeenAppliedAtLeastOnce: 1
This is set to true when this device property has been applied.
Friends
uint32 GetTypeHash (const FActiveDeviceProperty &InProp)
Active properties can just use the hash of their FInputDevicePropertyHandle for a fast and unique lookup.
bool operator== (const FActiveDeviceProperty &ActiveProp, const FInputDevicePropertyHandle &Handle)
bool operator!= (const FActiveDeviceProperty &ActiveProp, const FInputDevicePropertyHandle &Handle)
Detailed Description
Contains a pointer to an active device property and keeps track of how long it has been evaluated for.
Definition at line 54 of file InputDeviceSubsystem.h.
Constructor & Destructor Documentation
FActiveDeviceProperty()
FActiveDeviceProperty::FActiveDeviceProperty ()
References FActiveDeviceProperty().
Member Function Documentation
operator!=()
bool FActiveDeviceProperty::operator!= (const FActiveDeviceProperty & Other) const
References FActiveDeviceProperty().
operator==()
bool FActiveDeviceProperty::operator== (const FActiveDeviceProperty & Other) const
References FActiveDeviceProperty().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FActiveDeviceProperty & InProp) friend
Active properties can just use the hash of their FInputDevicePropertyHandle for a fast and unique lookup.
References FActiveDeviceProperty(), and GetTypeHash.
operator!=
bool operator!= (const FActiveDeviceProperty & ActiveProp, const FInputDevicePropertyHandle & Handle) friend
References FActiveDeviceProperty().
operator==
bool operator== (const FActiveDeviceProperty & ActiveProp, const FInputDevicePropertyHandle & Handle) friend
References FActiveDeviceProperty().
Member Data Documentation
bHasBeenAppliedAtLeastOnce
uint8 FActiveDeviceProperty::bHasBeenAppliedAtLeastOnce
This is set to true when this device property has been applied.
All device properties should be applied at least one time, no matter what. This handles cases where the evaluation time is longer then the duration of a property. I.e., your property is set to a duration of 0.1, but you get a delta time of .12 seconds for some reason (choppy frames, low perf client, debugging, etc).
Definition at line 104 of file InputDeviceSubsystem.h.
bIgnoreTimeDilation
uint8 FActiveDeviceProperty::bIgnoreTimeDilation
If true, then this device property will ignore dilated delta time and use the Applications delta time instead.
Definition at line 92 of file InputDeviceSubsystem.h.
bLooping
uint8 FActiveDeviceProperty::bLooping
If true, then the input device property will not be removed after it's evaluation time has completed.
Instead, it will remain active until manually removed with a RemoveDeviceProperty call.
Definition at line 89 of file InputDeviceSubsystem.h.
bPlayWhilePaused
uint8 FActiveDeviceProperty::bPlayWhilePaused
If true, then this device property will be played even if the game world is paused.
Definition at line 95 of file InputDeviceSubsystem.h.
DeviceId
FInputDeviceId FActiveDeviceProperty::DeviceId
The input device id that should receive this property.
Definition at line 80 of file InputDeviceSubsystem.h.
EvaluatedDuration
double FActiveDeviceProperty::EvaluatedDuration
How long this property has been evaluated for.
DeltaTime is added to this on tick
Definition at line 74 of file InputDeviceSubsystem.h.
PlatformUser
FPlatformUserId FActiveDeviceProperty::PlatformUser
The platform user that is actively receiving this device property.
Definition at line 77 of file InputDeviceSubsystem.h.
Property
TWeakObjectPtr<UInputDeviceProperty> FActiveDeviceProperty::Property
The active device property.
Definition at line 71 of file InputDeviceSubsystem.h.
PropertyHandle
FInputDevicePropertyHandle FActiveDeviceProperty::PropertyHandle
The handle of this active property.
Definition at line 83 of file InputDeviceSubsystem.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceSubsystem.h