Unreal Engine 5.6 C++ API: UInstancedStaticMeshComponent Class Reference
UInstancedStaticMeshComponent Class Reference abstract
#include "InstancedStaticMeshComponent.h"
Public Types
enum class EInstanceDeletionReason : uint8 { NotDeleting , EntryAlreadyRemoved , EntryRemoval , Clearing }
The reason why a deletion operation is currently happening.
Public Member Functions
FPrimitiveInstanceId AddInstanceById (const FTransform &InstanceTransforms, bool bWorldSpace=false)
TArray< FPrimitiveInstanceId > AddInstancesById (const TArrayView< const FTransform > &InstanceTransforms, bool bWorldSpace=false, bool bUpdateNavigation=true)
Preliminary ID-based interface.
virtual void ApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData *ComponentInstanceData)
Applies the cached component instance data to a newly blueprint constructed component.
virtual bool BatchUpdateInstancesData (int32 StartInstanceIndex, int32 NumInstances, FInstancedStaticMeshInstanceData *StartInstanceData, bool bMarkRenderStateDirty=false, bool bTeleport=false)
virtual bool BatchUpdateInstancesTransforms (int32 StartInstanceIndex, const TArray< FTransform > &NewInstancesTransforms, const TArray< FTransform > &NewInstancesPrevTransforms, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false)
Update the transform for an array of instances.
virtual bool BatchUpdateInstancesTransforms (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false)
this is array view version of the UFUNCTION, blueprints do not support ArrayViews at the time of adding this one
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
See: UObject::BeginCacheForCookedPlatformData.
virtual void BeginDestroy () override
virtual bool BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > &DependentResources, bool &bOutSupportsBuildTextureStreamingData) override
Build the data to compute accuracte StreaminTexture data.
virtual FBoxSphereBounds CalcBounds (const FTransform &BoundTransform) const override
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual bool CanEditSimulatePhysics () override
void ClearInstanceSelection ()
Deselect all instances.
virtual void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
Precache all PSOs which can be used by the component.
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual TArray< Chaos::FPhysicsObject * > GetAllPhysicsObjects () const override
virtual FBodyInstance * GetBodyInstance (FName BoneName=NAME_None, bool bGetWelded=true, int32 Index=INDEX_NONE) const override
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true) override
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
const TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > & GetInstanceDataSceneProxy () const
FORCEINLINE int32 GetInstanceIndexForId (FPrimitiveInstanceId InstanceId) const
Fetches current instance index for a given InstanceId.
bool GetInstancePrevTransform (int32 InstanceIndex, FTransform &OutInstanceTransform, bool bWorldSpace=false) const
Get the prev transform for the instance specified.
void GetInstancesMinMaxScale (FVector &MinScale, FVector &MaxScale) const
virtual void GetLightAndShadowMapMemoryUsage (int32 &LightMapMemoryUsage, int32 &ShadowMapMemoryUsage) const override
virtual bool GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo &MaterialData) const override
Get material, UV density and bounds for a given material index.
virtual FBox GetNavigationBounds () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
int32 GetNumInstances () const
virtual int32 GetNumRenderInstances () const
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateInstanceDataSceneProxy ()
virtual Chaos::FPhysicsObject * GetPhysicsObjectById (Chaos::FPhysicsObjectId Id) const override
FORCEINLINE int32 GetRenderIndex (int32 InInstanceIndex) const
Returns the render instance buffer index.
virtual FMatrix GetRenderMatrix () const override
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
virtual void GetStaticLightingInfo (FStaticLightingPrimitiveInfo &OutPrimitiveInfo, const TArray< ULightComponent * > &InRelevantLights, const FLightingBuildOptions &Options) override
virtual FBox GetStreamingBounds () const override
virtual void GetStreamingRenderAssetInfo (FStreamingTextureLevelContext &LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingRenderAssets) const override
Get the StreaminTexture data.
virtual float GetTextureStreamingTransformScale () const override
Get the scale comming form the component, when computing StreamingTexture data.
virtual FVector GetTranslatedInstanceSpaceOrigin () const
Get the translated space for instance transforms to be passed to the renderer.
FPrimitiveMaterialPropertyDescriptor GetUsedMaterialPropertyDesc (ERHIFeatureLevel::Type FeatureLevel) const
wrapper which is public so we can implement the LIST ISM command
void InvalidateInstanceDataTracking ()
Clears all the updated instance tracking data AND instance ID association, also forcing a full update of the instance data the next time it is flushed.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
See: UObject::IsCachedCookedPlatformDataLoaded.
virtual bool IsHLODRelevant () const override
bool IsInstanceSelected (int32 InInstanceIndex) const
Check to see if an instance is selected.
virtual bool IsInstanceTouchingSelectionBox (int32 InstanceIndex, const FBox &InBox, const bool bMustEncompassEntireInstance) const
virtual bool IsInstanceTouchingSelectionFrustum (int32 InstanceIndex, const FConvexVolume &InFrustum, const bool bMustEncompassEntireInstance) const
virtual bool IsNavigationRelevant () const override
bool IsValidId (FPrimitiveInstanceId InstanceId)
virtual bool LineTraceComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FCollisionQueryParams &Params) override
FInstanceDataFlags MakeInstanceDataFlags (bool bAnyMaterialHasPerInstanceRandom, bool bAnyMaterialHasPerInstanceCustomData) const
virtual void OnRegister () override
virtual void OnUnregister () override
virtual void OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) override
virtual bool OverlapComponent (const FVector &Pos, const FQuat &Rot, const FCollisionShape &CollisionShape) const override
virtual void PartialNavigationUpdate (int32 InstanceIdx)
Request to navigation system to update only part of navmesh occupied by specified instance.
virtual void PartialNavigationUpdates (TConstArrayView< FTransform > InstanceTransforms)
Request to navigation system to update only part of navmesh occupied specified instances transforms.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditUndo () override
virtual void PostLoad () override
virtual void PostStaticMeshCompilation () override
virtual void PreAllocateInstancesMemory (int32 AddedInstanceCount)
Preallocated memory to include the new added instances count, to prevent reallloc during the add operation.
void PreApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData *ComponentInstanceData)
Handle changes that must happen before the proxy is recreated.
virtual void PreSave (FObjectPreSaveContext ObjectSaveContext) override
virtual void PropagateLightingScenarioChange () override
void RemoveInstanceById (FPrimitiveInstanceId InstanceId)
virtual bool RemoveInstances (const TArray< int32 > &InstancesToRemove, bool bInstanceArrayAlreadySortedInReverseOrder)
Remove the instances specified.
virtual void RemoveInstancesById (const TArrayView< const FPrimitiveInstanceId > &InstanceIds, bool bUpdateNavigation=true)
void SelectInstance (bool bInSelected, int32 InInstanceIndex, int32 InInstanceCount=1)
Select/deselect an instance or group of instances.
virtual void SendRenderInstanceData_Concurrent () override
virtual void Serialize (FArchive &Ar) override
void SetBakedLightingDataChanged (int32 InInstanceIndex)
Mark the "shadowmap" or lightmap uv as modified for the instance since this is stored in external data.
void SetBakedLightingDataChangedAll ()
Mark the "shadowmap" or lightmap uv as modified for all the instances since this is stored in external data.
virtual bool SetCustomData (int32 InstanceIndex, TArrayView< const float > CustomDataFloats, bool bMarkRenderStateDirty=false)
Per Instance Custom Data.
virtual bool SetCustomData (int32 InstanceIndexStart, int32 InstanceIndexEnd, TConstArrayView< float > CustomDataFloats, bool bMarkRenderStateDirty=false)
void SetCustomDataById (const TArrayView< const FPrimitiveInstanceId > &InstanceIds, TArrayView< const float > CustomDataFloats)
void SetCustomDataById (FPrimitiveInstanceId InstanceId, TArrayView< const float > CustomDataFloats)
void SetCustomDataValueById (FPrimitiveInstanceId InstanceId, int32 CustomDataIndex, float CustomDataValue)
void SetHasPerInstancePrevTransforms (bool bInHasPreviousTransforms)
void SetPreviousTransformById (FPrimitiveInstanceId InstanceId, const FTransform &NewPrevInstanceTransform, bool bWorldSpace=false)
void SetRemoveSwap ()
Sets to use RemoveAtSwap on instance removal.
void SetUseConservativeBounds (bool bValue)
Sets whether to use conservative bounds.
virtual bool ShouldCreatePhysicsState () const override
virtual bool ShouldSkipDirtyAreaOnAddOrRemove () const override
virtual bool SupportsRemoveSwap () const
Returns true if RemoveAtSwap is enabled.
virtual bool SupportsStaticLighting () const override
Whether the component type supports static lighting.
virtual bool SweepComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FQuat &ShapRotation, const FCollisionShape &CollisionShape, bool bTraceComplex=false) override
UE_DEPRECATED (5.0, "Use AddInstance or AddInstances with bWorldSpace set to true.") UFUNCTION()) int32 AddInstanceWorldSpace(const FTransform &WorldTransform)
Add an instance to this component.
UE_DEPRECATED (5.4, "This function has been added only for the purposes of moving LWI code outside of the engine. Don't use it, it will be removed soon.") void OnPostPopulatePerInstanceData()
UFUNCTION () 1 bool GetInstanceTransform(int32 InstanceIndex
Get the transform for the instance specified.
UFUNCTION () 1 bool IsValidInstance(int32 InstanceIndex) const
Does the given index map to a valid instance in this component?
UFUNCTION () 1 int32 GetInstanceCount() const
Get the number of instances in this component.
UFUNCTION () 1 virtual bool BatchUpdateInstancesTransform(int32 StartInstanceIndex
Update the transform for a number of instances.
UFUNCTION () 1 virtual bool BatchUpdateInstancesTransforms(int32 StartInstanceIndex
Update the transform for an array of instances.
UFUNCTION () 1 virtual bool RemoveInstance(int32 InstanceIndex)
Remove the instance specified.
UFUNCTION () 1 virtual bool RemoveInstances(const TArray< int32 > &InstancesToRemove)
Remove the instances specified.
UFUNCTION () 1 virtual bool SetCustomDataValue(int32 InstanceIndex
Update custom data for specific instance.
UFUNCTION () 1 virtual bool UpdateInstanceTransform(int32 InstanceIndex
Update the transform for the instance specified.
UFUNCTION () 1 virtual int32 AddInstance(const FTransform &InstanceTransform
Add an instance to this component.
UFUNCTION () 1 virtual TArray< int32 > AddInstances(const TArray< FTransform > &InstanceTransforms
Add multiple instances to this component.
UFUNCTION () 1 virtual TArray< int32 > GetInstancesOverlappingBox(const FBox &Box
Returns the instances with instance bounds overlapping the specified box.
UFUNCTION () 1 virtual TArray< int32 > GetInstancesOverlappingSphere(const FVector &Center
Returns the instances with instance bounds overlapping the specified sphere.
UFUNCTION () 1 virtual void ClearInstances()
Clear all instances being rendered by this component.
UFUNCTION () 1 virtual void SetNumCustomDataFloats(int32 InNumCustomDataFloats)
Update number of custom data entries per instance.
UFUNCTION () 1 void SetCullDistances(int32 StartCullDistance
Sets the fading start and culling end distances for this component.
UFUNCTION () 1 void SetLODDistanceScale(float InLODDistanceScale)
Sets the LOD scale.
UFUNCTION () float GetLODDistanceScale() const
Gets the current LOD scale.
UFUNCTION () void GetCullDistances(int32 &OutStartCullDistance
Gets the fading start and culling end distances for this component.
virtual void UpdateBounds () override
void UpdateComponentTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport)
void UpdateInstanceTransformById (FPrimitiveInstanceId InstanceId, const FTransform &NewInstanceTransform, bool bWorldSpace=false, bool bTeleport=false)
UPROPERTY () TArray< int32 > InstanceReorderTable
Mapping from PerInstanceSMData order to instance render buffer order.
Public Member Functions inherited from UStaticMeshComponent
virtual ~UStaticMeshComponent ()
virtual UObject const * AdditionalStatObject () const override
virtual void AddMapBuildDataGUIDs (TSet< FGuid > &InGUIDs) const override
virtual FStaticMeshStaticLightingMesh * AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > &InRelevantLights)
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
virtual bool AllowsAsyncPhysicsStateCreation () const override
virtual bool AllowsAsyncPhysicsStateDestruction () const override
void ApplyComponentInstanceData (struct FStaticMeshComponentInstanceData *ComponentInstanceData)
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const override
virtual void BeginPlay () override
bool CanMeshPaintTextureColors () const
bool CanMeshPaintVertexColors () const
virtual void CheckForErrors () override
virtual uint32 ComputeHashTextureStreamingBuiltData () const override
virtual HHitProxy * CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) const override
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
DECLARE_DELEGATE_RetVal (const Nanite::FResources *, FOnGetNaniteResources)
Called during scene proxy creation to get the Nanite resource data.
DECLARE_EVENT_OneParam (UStaticMeshComponent, FOnStaticMeshChanged, UStaticMeshComponent *)
Called when the static mesh changes.
virtual bool DoesSocketExist (FName InSocketName) const override
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent) override
int32 GetBlueprintCreatedComponentIndex () const
Get this components index in its parents blueprint created components array (used for matching instance data)
virtual class UBodySetup * GetBodySetup () override
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const override
Get all default LOD sections overlay materials used by a mesh.
virtual FString GetDetailedInfoInternal () const override
virtual float GetDiffuseBoost (int32 ElementIndex) const override
virtual UMaterialInterface * GetEditorMaterial (int32 MaterialIndex) const override
virtual float GetEmissiveBoost (int32 ElementIndex) const override
virtual bool GetEstimatedLightAndShadowMapMemoryUsage (int32 &TextureLightMapMemoryUsage, int32 &TextureShadowMapMemoryUsage, int32 &VertexLightMapMemoryUsage, int32 &VertexShadowMapMemoryUsage, int32 &StaticLightingResolution, bool &bIsUsingTextureMapping, bool &bHasLightmapTexCoords) const
Returns the light and shadow map memory for this primite in its out variables.
virtual void GetEstimatedLightMapResolution (int32 &Width, int32 &Height) const
Returns the lightmap resolution used for this primitive instance in the case of it supporting texture light/ shadow maps.
FORCEINLINE int32 GetForcedLodModel () const
FORCEINLINE bool GetForceNaniteForMasked () const
virtual bool GetLightMapResolution (int32 &Width, int32 &Height) const override
virtual UMaterialInterface * GetMaterial (int32 MaterialIndex) const final
virtual UMaterialInterface * GetMaterialFromCollisionFaceIndex (int32 FaceIndex, int32 &SectionIndex) const override
virtual int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual TArray< FName > GetMaterialSlotNames () const override
const FMeshMapBuildData * GetMeshMapBuildData (const FStaticMeshComponentLODInfo &LODInfo, bool bCheckForResourceCluster=true) const
virtual UTexture * GetMeshPaintTexture () const override
Get the mesh paint texture set on this component.
virtual int32 GetMeshPaintTextureCoordinateIndex () const override
Get the default coordinate index for painting to the mesh paint texture on this component.
int32 GetMeshPaintTextureResolution () const
Returns the size to use when creating a mesh paint texture on this component.
FORCEINLINE int32 GetMinLOD () const
UMaterialInterface * GetNaniteAuditMaterial (int32 MaterialIndex) const
virtual const Nanite::FResources * GetNaniteResources () const
virtual int32 GetNumMaterials () const override
FORCEINLINE bool GetOverrideMinLOD () const
virtual void GetPrimitiveStats (FPrimitiveStats &PrimitiveStats) const override
virtual bool GetShadowIndirectOnly () const override
class UStaticMeshSocket const * GetSocketByName (FName InSocketName) const
Returns the named socket on the static mesh component.
virtual FTransform GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace=RTS_World) const override
virtual ELightMapInteractionType GetStaticLightingType () const override
virtual int32 GetStaticLightMapResolution () const override
TObjectPtr< UStaticMesh > GetStaticMesh () const
Get the StaticMesh used by this instance.
virtual float GetStreamingScale () const override
virtual void GetTextureLightAndShadowMapMemoryUsage (int32 InWidth, int32 InHeight, int32 &OutLightMapMemoryUsage, int32 &OutShadowMapMemoryUsage) const
Get the memory used for texture-based light and shadow maps of the given width and height.
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const final
virtual void GetUsedTextures (TArray< UTexture * > &OutTextures, EMaterialQualityLevel::Type QualityLevel) override
FColor GetWireframeColor () const
Returns the wireframe color to use for this component.
virtual bool HasAnySockets () const override
virtual bool HasLightmapTextureCoordinates () const
Returns true if the static mesh the component uses has valid lightmap texture coordinates.
virtual bool HasValidNaniteData () const
Returns true if the component has valid Nanite render data.
virtual bool HasValidSettingsForStaticLighting (bool bOverlookInvalidComponents) const override
Returns true if the component is static AND has the right static mesh setup to support lightmaps.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn) override
virtual void InitializeComponent () override
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) override
virtual bool IsCompiling () const override
FORCEINLINE bool IsDisallowNanite () const
FORCEINLINE bool IsForceDisableNanite () const
FORCEINLINE bool IsForceNaniteForMasked () const
virtual bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
virtual bool IsPostLoadThreadSafe () const override
virtual bool IsPrecomputedLightingValid () const override
FORCEINLINE bool IsReverseCulling () const
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
virtual FOnGetNaniteResources & OnGetNaniteResources ()
virtual const FOnGetNaniteResources & OnGetNaniteResources () const
void OnMeshRebuild (bool bRenderDataChanged)
virtual FOnStaticMeshChanged & OnStaticMeshChanged ()
virtual void PostApplyToComponent () override
virtual void PostDuplicate (bool bDuplicateForPIE) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditImport () override
virtual void PostInitProperties () override
virtual void PostReinitProperties () override
virtual void PrecachePSOs () override
virtual void PreEditUndo () override
virtual void PreStaticMeshCompilation ()
virtual bool PrestreamMeshLODs (float Seconds) override
virtual void QuerySupportedSockets (TArray< FComponentSocketDescription > &OutSockets) const override
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) override
Register a one-time callback that will be called when criteria met.
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&CallbackStreamingStart, FLODStreamingCallback &&CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) override
Register a one-time callback that will be called when streaming starts or ends.
void ReleaseResources ()
virtual bool RemapActorTextureStreamingBuiltDataToLevel (const class UActorTextureStreamingBuildDataComponent *InActorTextureBuildData) override
void RemoveInstanceVertexColorsFromLOD (int32 LODToRemoveColorsFrom)
Removes instance vertex colors from the specified LOD.
virtual bool RequiresGameThreadEndOfFrameRecreate () const override
virtual void SetCollisionProfileName (FName InCollisionProfileName, bool bUpdateOverlaps=true) override
bool SetLODDataCount (const uint32 MinSize, const uint32 MaxSize)
Add or remove elements to have the size in the specified range.
virtual void SetMeshPaintTexture (UTexture *Texture) override
Set the mesh paint texture on this component.
virtual void SetMeshPaintTextureOverride (UTexture *OverrideTexture) override
Set a transient override mesh paint texture on this component.
virtual bool SetStaticLightingMapping (bool bTextureMapping, int32 ResolutionToUse)
Switches the static mesh component to use either Texture or Vertex static lighting.
virtual bool ShouldCollideWhenPlacing () const override
virtual bool ShouldCreateRenderState () const override
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const override
virtual bool ShouldRecreateProxyOnUpdateTransform () const override
virtual bool ShouldRenderSelected () const override
virtual bool SupportsDefaultCollision ()
Whether or not the component supports default collision from its static mesh asset.
virtual bool SupportsDitheredLODTransitions (ERHIFeatureLevel::Type FeatureLevel)
Whether we can support dithered LOD transitions (default behavior checks all materials).
virtual bool SupportsWorldPositionOffsetVelocity () const override
UE_DEPRECATED (5.6, "Use UPrimitiveComponent::IsFirstPersonRelevant() instead.") bool IsStaticMeshFirstPersonRelevant() const
UFUNCTION () 1 virtual bool SetStaticMesh(class UStaticMesh *NewMesh)
Change the StaticMesh used by this instance.
UFUNCTION () 1 void GetLocalBounds(FVector &Min
Get Local bounds.
UFUNCTION () 1 void OnRep_StaticMesh(class UStaticMesh *OldStaticMesh)
UFUNCTION () 1 void SetDistanceFieldSelfShadowBias(float NewValue)
Sets the component's DistanceFieldSelfShadowBias.
UFUNCTION () 1 void SetEvaluateWorldPositionOffset(bool NewValue)
UFUNCTION () 1 void SetEvaluateWorldPositionOffsetInRayTracing(bool NewValue)
UFUNCTION () 1 void SetForceDisableNanite(bool bInForceDisableNanite)
Force disabling of Nanite rendering.
UFUNCTION () 1 void SetForcedLodModel(int32 NewForcedLodModel)
UFUNCTION () 1 void SetReverseCulling(bool ReverseCulling)
Set forced reverse culling.
UFUNCTION () 1 void SetWorldPositionOffsetDisableDistance(int32 NewValue)
UFUNCTION () bool GetInitialEvaluateWorldPositionOffset()
Get the initial value of bEvaluateWorldPositionOffset.
UFUNCTION () void UpdateInitialEvaluateWorldPositionOffset()
This manually updates the initial value of bEvaluateWorldPositionOffset to be the current value.
void UpdateCollisionFromStaticMesh ()
Sets the BodyInstance to use the mesh's body setup for external collision information.
void UpdateMapBuildDataId ()
void UpdateStaticLightingData ()
UPROPERTY () float DistanceFieldSelfShadowBias
Useful for reducing self shadowing from distance field methods when using world position offset to animate the mesh's vertices.
UPROPERTY () float NanitePixelProgrammableDistance
Used to forcefully disable pixel programmable rasterization of Nanite when the mesh is further than a given distance from the camera.
UPROPERTY () struct FLightmassPrimitiveSettings LightmassSettings
The Lightmass settings for this object.
UPROPERTY () TArray< FStreamingTextureBuildInfo > StreamingTextureData
The list of texture, bounds and scales.
UPROPERTY () TArray< struct FStaticMeshComponentLODInfo > LODData
Static mesh LOD data.
UPROPERTY () TObjectPtr< UTexture > MaterialCacheTexture
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureCooked
Cooked pointer to texture containing mesh painting for this mesh component.
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureOverride
Set this to override the locally stored mesh paint texture.
UPROPERTY ()) float DistanceFieldIndirectShadowMinVisibility
Controls how dark the dynamic indirect shadow can be.
UPROPERTY ()) float StreamingDistanceMultiplier
Allows adjusting the desired streaming distance of streaming textures that uses UV 0.
UPROPERTY ()) int32 OverriddenLightMapRes
Light map resolution to use on this component, used if bOverrideLightMapRes is true and there is a valid StaticMesh.
UPROPERTY()) uint8 bOverrideWireframeColor UPROPERTY() uint8 bOverrideMinLOD UPROPERTY() uint8 bOverrideNavigationExport UPROPERTY() uint8 bForceNavigationObstacle UPROPERTY() uint8 bDisallowMeshPaintPerInstance_DEPRECATED UPROPERTY() uint8 bIgnoreInstanceForTextureStreaming UPROPERTY()) uint8 bOverrideLightMapRes UPROPERTY()) uint8 bCastDistanceFieldIndirectShadow UPROPERTY() uint8 bOverrideDistanceFieldSelfShadowBias UPROPERTY() uint8 bUseSubDivisions UPROPERTY() uint8 bUseDefaultCollision UPROPERTY()) uint8 bSortTriangles UPROPERTY() uint8 bReverseCulling UPROPERTY() uint8 bEnableVertexColorMeshPainting UPROPERTY() uint8 bEnableTextureColorMeshPainting UPROPERTY()) uint8 bOverrideMeshPaintTextureCoordinateIndex UPROPERTY()) uint8 bOverrideMeshPaintTextureResolution UPROPERTY ()) int32 OverriddenMeshPaintTextureCoordinateIndex
If true, WireframeColorOverride will be used.
UPROPERTY ()) int32 OverriddenMeshPaintTextureResolution
The overriden resolution of texture color mesh paint textures on this component.
virtual bool UseNaniteOverrideMaterials () const override
Determines if we use the nanite overrides from any materials.
virtual bool UsesOnlyUnlitMaterials () const override
virtual bool UsesTextureLightmaps (int32 InWidth, int32 InHeight) const
Returns true if the component uses texture lightmaps.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Data Fields
bool bBoxInWorldSpace =true) const
bool bForceShowAllInstancesDetails = false
Indicates that the user has purposedly chosen to show the instance list in the details panel, despite the performance warning.
int32 float bool bMarkRenderStateDirty = false)
const FTransform bool bool bMarkRenderStateDirty =false
const TArray< FTransform > bool bool bMarkRenderStateDirty =false
int32 const FTransform bool bool bMarkRenderStateDirty =false
bool bShouldReturnIndices
float bool bSphereInWorldSpace =true) const
const FTransform bool bool bool bTeleport =false)
const TArray< FTransform > bool bool bool bTeleport =false)
int32 const FTransform bool bool bool bTeleport =false)
bool bool bool bUpdateNavigation = true)
bool bWorldSpace = false)
bool bool bWorldSpace = false
FTransform bool bWorldSpace = false) const
const FTransform bool bWorldSpace =false
const TArray< FTransform > bool bWorldSpace =false
int32 const FTransform bool bWorldSpace =false
int32 &OutEndCullDistance const { OutStartCullDistance = InstanceStartCullDistance
int32 CustomDataIndex
int32 float CustomDataValue
EInstanceDeletionReason DeletionState = EInstanceDeletionReason::NotDeleting
This will be set to the appropriate state when one or more instances are in the process of being deleted.
int32 EndCullDistance
TArray< FBodyInstance * > InstanceBodies
Physics representation of the instance bodies.
int32 const FTransform & NewInstancesTransform
const TArray< FTransform > & NewInstancesTransforms
const FTransform & NewInstanceTransform
int32 NumInstances
OutEndCullDistance = InstanceEndCullDistance
FTransform & OutInstanceTransform
SIZE_T ProxySize
Tracks outstanding proxysize, as this is a bit hard to do with the fire-and-forget grass.
float Radius
TBitArray SelectedInstances
One bit per instance if the instance is selected.
Data Fields inherited from UStaticMeshComponent
FVector &Max const
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Types
enum class EBoundsCacheType : uint8 {
Component , Navigation , Local , Count ,
Other
}
Protected Types inherited from UStaticMeshComponent
using GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)>
Shared implementation for all StaticMesh derived components.
Protected Member Functions
int32 AddInstanceInternal (int32 InstanceIndex, FInstancedStaticMeshInstanceData *InNewInstanceData, const FTransform &InstanceTransform, bool bWorldSpace)
Internal version of AddInstance.
TArray< int32 > AddInstancesInternal (TConstArrayView< FTransform > InstanceTransforms, bool bShouldReturnIndices, bool bWorldSpace, bool bUpdateNavigation=true)
Internal implementation of AddInstances.
void ApplyLightMapping (FStaticLightingTextureMapping_InstancedStaticMesh *InMapping, const FStaticLightingBuildContext *LightingContext)
virtual void BuildComponentInstanceData (ERHIFeatureLevel::Type FeatureLevel, FInstanceUpdateComponentDesc &OutData)
void BuildInstanceDataDeltaChangeSetCommon (FISMInstanceUpdateChangeSet &ChangeSet)
void BuildLegacyRenderData (FStaticMeshInstanceData &OutData)
Build instance buffer for rendering from current component data.
void CalcAndCacheNavigationBounds ()
FBoxSphereBounds CalcBoundsImpl (const FTransform &BoundTransform, const FBox &InstanceBounds) const
Calculates bounds from all instances.
virtual bool CanEditSMInstance (const FSMInstanceId &InstanceId) const override
virtual bool CanMoveSMInstance (const FSMInstanceId &InstanceId, const ETypedElementWorldType InWorldType) const override
Get the display name of the given static mesh instance.
void ClearAllInstanceBodies ()
Terminate all body instances owned by this component.
virtual bool ComponentOverlapComponentImpl (class UPrimitiveComponent *PrimComp, const FVector Pos, const FQuat &Quat, const FCollisionQueryParams &Params) override
virtual bool ComponentOverlapMultiImpl (TArray< struct FOverlapResult > &OutOverlaps, const class UWorld *InWorld, const FVector &Pos, const FQuat &Rot, ECollisionChannel TestChannel, const struct FComponentQueryParams &Params, const struct FCollisionObjectQueryParams &ObjectQueryParams=FCollisionObjectQueryParams::DefaultObjectQueryParam) const override
void CreateAllInstanceBodies ()
Creates body instances for all instances owned by this component.
void CreateHitProxyData (TArray< TRefCountPtr< HHitProxy > > &HitProxies)
virtual FPrimitiveSceneProxy * CreateStaticMeshSceneProxy (Nanite::FMaterialAudit &NaniteMaterials, bool bCreateNanite) override
virtual bool DeleteSMInstances (TArrayView< const FSMInstanceId > InstanceIds) override
Attempt to delete the given static mesh instances.
virtual bool DuplicateSMInstances (TArrayView< const FSMInstanceId > InstanceIds, TArray< FSMInstanceId > &OutNewInstanceIds) override
Attempt to duplicate the given static mesh instances, retrieving the IDs of any new instances.
virtual void FullNavigationUpdate ()
Request to navigation system to update for the bounds of the ISM.
FBox GetInstanceNavigationBounds () const
Returns the bounds of a single instance in local space.
virtual void GetNavigationPerInstanceTransforms (const FBox &AreaBox, TArray< FTransform > &InstanceData) const
Handles request from navigation system to gather instance transforms in a specific area box.
virtual bool GetSMInstanceTransform (const FSMInstanceId &InstanceId, FTransform &OutInstanceTransform, bool bWorldSpace=false) const override
Attempt to get the transform of the given static mesh instance.
void InitializeInstancingRandomSeed ()
void InitInstanceBody (int32 InstanceIdx, FBodyInstance *InBodyInstance)
Initializes the body instance for the specified instance of the static mesh.
void InvalidateCachedBounds ()
virtual void NotifySMInstanceMovementEnded (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is done being moved.
virtual void NotifySMInstanceMovementOngoing (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is currently being moved.
virtual void NotifySMInstanceMovementStarted (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is about to be moved.
virtual void NotifySMInstanceSelectionChanged (const FSMInstanceId &InstanceId, const bool bIsSelected) override
Notify that the given static mesh instance selection state has changed.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
virtual void OnCreatePhysicsState () override
virtual void OnDestroyPhysicsState () override
virtual void OnPostLoadPerInstanceData ()
Creates rendering buffer from serialized data, if any.
bool RemoveInstanceInternal (int32 InstanceIndex, bool InstanceAlreadyRemoved, bool bForceRemoveAtSwap=false, bool bUpdateNavigation=true)
Internal version of RemoveInstance.
void SerializeRenderData (FArchive &Ar)
Serialize instance buffer that is used for rendering.
virtual bool SetSMInstanceTransform (const FSMInstanceId &InstanceId, const FTransform &InstanceTransform, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
Attempt to set the transform of the given static mesh instance.
virtual bool SupportsPartialNavigationUpdate () const
Does this component support partial navigation updates.
UE_DEPRECATED (5.5, "Use version with FBox") FBoxSphereBounds CalcBoundsImpl(const FTransform &BoundTransform
UPROPERTY () int32 NumPendingLightmaps
Number of pending lightmaps still to be calculated (Apply()'d).
UPROPERTY () TArray< FInstancedStaticMeshMappingInfo > CachedMappings
The mappings for all the instances of this component.
Protected Member Functions inherited from UStaticMeshComponent
void CollectPSOPrecacheDataImpl (const FVertexFactoryType *VFType, const FPSOPrecacheParams &BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList &OutParams) const
bool ShouldCreateNaniteProxy (Nanite::FMaterialAudit *OutNaniteMaterials=nullptr) const
bool ShouldExportAsObstacle (const UNavCollisionBase &InNavCollision) const
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
uint8 bIsInstanceDataApplyCompleted: 1
bool bForNavigation const
friend FInstancedLightMap2D
friend FInstancedShadowMap2D
friend FStaticLightingTextureMapping_InstancedStaticMesh
FPrimitiveInstanceDataManager PrimitiveInstanceDataManager
Protected Attributes inherited from UStaticMeshComponent
uint8 bInitialEvaluateWorldPositionOffset: 1
Forces this component to always use Nanite for masked materials, even if FNaniteSettings::bAllowMaskedMaterials=false.
uint8 bMipLevelCallbackRegistered: 1
Whether mip callbacks have been registered and need to be removed on destroy.
uint8 bPrecachedPSOs: 1
Whether PrecachedPSOs was called.
uint8 bSupportMeshPainting: 1
Whether mesh painting is supported.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
virtual ~UInstancedStaticMeshComponent ()
void ApplyInheritedPerInstanceData (const UInstancedStaticMeshComponent *InArchetype)
bool BatchUpdateInstancesTransformsInternal (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport)
hidden Implementation of BatchUpdateInstancesTransforms - it is shared by the TArray and TArrayView version of public API
GENERATED_UCLASS_BODY () 1 UInstancedStaticMeshComponent(FVTableHelper &Helper)
Needs implementation in InstancedStaticMesh.cpp to compile UniquePtr for forward declared class.
FBoxSphereBounds GetOrCalcBounds (const FTransform &InBoundTransform, EBoundsCacheType InType) const
void PartialNavigateUpdateForCurrentInstances ()
void SetupNewInstanceData (FInstancedStaticMeshInstanceData &InOutNewInstanceData, int32 InInstanceIndex, const FTransform &InInstanceTransform)
Sets up new instance data to sensible defaults, creates physics counterparts if possible.
bool ShouldInheritPerInstanceData () const
bool ShouldInheritPerInstanceData (const UInstancedStaticMeshComponent *InArchetype) const
void UpdateInstanceBodyTransform (int32 InstanceIndex, const FTransform &WorldSpaceInstanceTransform, bool bTeleport)
Update instance body with a new transform.
UPROPERTY () float InstanceLODDistanceScale
Scale applied to change the computation of LOD distances when using the StaticMesh screen sizes.
UPROPERTY () FTransform PreviousComponentTransform
Main transform stored to be able to send updates when component's transform changed.
UPROPERTY () int32 InstanceEndCullDistance
Distance from camera at which each instance completely fades out.
UPROPERTY () int32 InstanceMinDrawDistance
Distance from camera at which each instance begins to draw.
UPROPERTY () int32 InstanceStartCullDistance
Distance from camera at which each instance begins to fade out.
UPROPERTY () int32 InstancingRandomSeed=0
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () int32 NumCustomDataFloats
Defines the number of floats that will be available per instance for custom data.
UPROPERTY () TArray< FInstancedStaticMeshRandomSeed > AdditionalRandomSeeds
Additional random seeds ranges.
UPROPERTY () TArray< FMatrix > PerInstancePrevTransform
Array of prev instance transforms.
UPROPERTY ()) TArray< FInstancedStaticMeshInstanceData > PerInstanceSMData
Array of instances, bulk serialized.
UPROPERTY ()) TArray< float > PerInstanceSMCustomData
Array of custom data for instances.
Private Attributes
TArray< FBodyInstance * > AsyncDestroyPhysicsStatePayload
Payload used by asynchronous destruction of physics state (see OnAsyncDestroyPhysicsState).
uint8 bHasPreviousTransforms: 1
uint8 bIsUpdatingBounds: 1
Internally used to know when CalcBounds is called by UpdateBounds.
UPROPERTY() uint8 bUseGpuLodSelection UPROPERTY() uint8 bInheritPerInstanceData UPROPERTY() uint8 bDisableCollision uint8 bSupportRemoveAtSwap: 1
If true, this component will use GPU LOD selection.
uint8 bUseConservativeBounds: 1
Flag for whether we are using conservative bounds.
FBox CachedConservativeInstanceBounds
Current cached conservativ bounds.
Additional Inherited Members
Static Public Member Functions inherited from UStaticMeshComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static const FName GetMemberNameChecked_StaticMesh ()
Helper function to get the FName of the private static mesh member.
Detailed Description
Definition at line 157 of file InstancedStaticMeshComponent.h.
Member Enumeration Documentation
EBoundsCacheType
enum class UInstancedStaticMeshComponent::EBoundsCacheType : uint8 strong protected
Enumerator
Component
Navigation
Local
Count
Other
Definition at line 696 of file InstancedStaticMeshComponent.h.
EInstanceDeletionReason
enum class UInstancedStaticMeshComponent::EInstanceDeletionReason : uint8 strong
The reason why a deletion operation is currently happening.
Enumerator
NotDeleting
EntryAlreadyRemoved
There is currently no deletion in progress.
EntryRemoval
The instance has been deleted externally.
Data synchronization in progress.
Clearing
The instance is being removed.
All instances are being removed.
Definition at line 496 of file InstancedStaticMeshComponent.h.
Constructor & Destructor Documentation
~UInstancedStaticMeshComponent()
virtual UInstancedStaticMeshComponent::~UInstancedStaticMeshComponent () private virtual
Member Function Documentation
AddInstanceById()
FPrimitiveInstanceId UInstancedStaticMeshComponent::AddInstanceById (const FTransform & InstanceTransforms, bool bWorldSpace = false)
References bWorldSpace.
AddInstanceInternal()
int32 UInstancedStaticMeshComponent::AddInstanceInternal (int32 InstanceIndex, FInstancedStaticMeshInstanceData * InNewInstanceData, const FTransform & InstanceTransform, bool bWorldSpace) protected
Internal version of AddInstance.
References bWorldSpace.
AddInstancesById()
TArray< FPrimitiveInstanceId > UInstancedStaticMeshComponent::AddInstancesById (const TArrayView< const FTransform > & InstanceTransforms, bool bWorldSpace = false, bool bUpdateNavigation = true)
Preliminary ID-based interface.
May only be used if no other manipulations are performed that cause invalidation of IDs. For example, cannot be used on HISM. ISMs edited in the editor can also not reliably be used, as some editor changes cause ID tracking to be lost.
References bUpdateNavigation, and bWorldSpace.
AddInstancesInternal()
TArray< int32 > UInstancedStaticMeshComponent::AddInstancesInternal (TConstArrayView< FTransform > InstanceTransforms, bool bShouldReturnIndices, bool bWorldSpace, bool bUpdateNavigation = true) protected
Internal implementation of AddInstances.
References bShouldReturnIndices, bUpdateNavigation, and bWorldSpace.
ApplyComponentInstanceData()
virtual void UInstancedStaticMeshComponent::ApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData * ComponentInstanceData) virtual
Applies the cached component instance data to a newly blueprint constructed component.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
ApplyInheritedPerInstanceData()
void UInstancedStaticMeshComponent::ApplyInheritedPerInstanceData (const UInstancedStaticMeshComponent * InArchetype) private
ApplyLightMapping()
void UInstancedStaticMeshComponent::ApplyLightMapping (FStaticLightingTextureMapping_InstancedStaticMesh * InMapping, const FStaticLightingBuildContext * LightingContext) protected
References FStaticLightingTextureMapping_InstancedStaticMesh.
Referenced by FStaticLightingTextureMapping_InstancedStaticMesh::Apply().
BatchUpdateInstancesData()
virtual bool UInstancedStaticMeshComponent::BatchUpdateInstancesData (int32 StartInstanceIndex, int32 NumInstances, FInstancedStaticMeshInstanceData * StartInstanceData, bool bMarkRenderStateDirty = false, bool bTeleport = false) virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References BatchUpdateInstancesData(), bMarkRenderStateDirty, bTeleport, and NumInstances.
Referenced by BatchUpdateInstancesData().
BatchUpdateInstancesTransforms() [1/2]
virtual bool UInstancedStaticMeshComponent::BatchUpdateInstancesTransforms (int32 StartInstanceIndex, const TArray< FTransform > & NewInstancesTransforms, const TArray< FTransform > & NewInstancesPrevTransforms, bool bWorldSpace = false, bool bMarkRenderStateDirty = false, bool bTeleport = false) virtual
Update the transform for an array of instances.
Overloaded version which takes an array of NewPreviousFrameTransforms.
References BatchUpdateInstancesTransforms(), bMarkRenderStateDirty, bTeleport, bWorldSpace, const, and NewInstancesTransforms.
BatchUpdateInstancesTransforms() [2/2]
virtual bool UInstancedStaticMeshComponent::BatchUpdateInstancesTransforms (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace = false, bool bMarkRenderStateDirty = false, bool bTeleport = false) virtual
this is array view version of the UFUNCTION, blueprints do not support ArrayViews at the time of adding this one
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References BatchUpdateInstancesTransforms(), bMarkRenderStateDirty, bTeleport, bWorldSpace, const, and NewInstancesTransforms.
Referenced by BatchUpdateInstancesTransforms(), and BatchUpdateInstancesTransforms().
BatchUpdateInstancesTransformsInternal()
bool UInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport) private
hidden Implementation of BatchUpdateInstancesTransforms - it is shared by the TArray and TArrayView version of public API
References bMarkRenderStateDirty, bTeleport, bWorldSpace, and NewInstancesTransforms.
BeginCacheForCookedPlatformData()
virtual void UInstancedStaticMeshComponent::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) override virtual
See: UObject::BeginCacheForCookedPlatformData.
Reimplemented from UStaticMeshComponent.
BeginDestroy()
virtual void UInstancedStaticMeshComponent::BeginDestroy () override virtual
Reimplemented from UStaticMeshComponent.
BuildComponentInstanceData()
virtual void UInstancedStaticMeshComponent::BuildComponentInstanceData (ERHIFeatureLevel::Type FeatureLevel, FInstanceUpdateComponentDesc & OutData) protected virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
BuildInstanceDataDeltaChangeSetCommon()
void UInstancedStaticMeshComponent::BuildInstanceDataDeltaChangeSetCommon (FISMInstanceUpdateChangeSet & ChangeSet) protected
BuildLegacyRenderData()
void UInstancedStaticMeshComponent::BuildLegacyRenderData (FStaticMeshInstanceData & OutData) protected
Build instance buffer for rendering from current component data.
Only used for cook
BuildTextureStreamingDataImpl()
virtual bool UInstancedStaticMeshComponent::BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > & DependentResources, bool & bOutSupportsBuildTextureStreamingData) override virtual
Build the data to compute accuracte StreaminTexture data.
Reimplemented from UStaticMeshComponent.
References BuildTextureStreamingDataImpl().
Referenced by BuildTextureStreamingDataImpl().
CalcAndCacheNavigationBounds()
void UInstancedStaticMeshComponent::CalcAndCacheNavigationBounds () protected
CalcBounds()
virtual FBoxSphereBounds UInstancedStaticMeshComponent::CalcBounds (const FTransform & BoundTransform) const override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
CalcBoundsImpl()
FBoxSphereBounds UInstancedStaticMeshComponent::CalcBoundsImpl (const FTransform & BoundTransform, const FBox & InstanceBounds) const protected
Calculates bounds from all instances.
Parameters
BoundTransform The bounds transform
InstanceBounds The instance bounds
References CalcBoundsImpl(), and const.
Referenced by CalcBoundsImpl().
CanEditChange()
virtual bool UInstancedStaticMeshComponent::CanEditChange (const FProperty * InProperty) const override virtual
Reimplemented from UStaticMeshComponent.
CanEditSimulatePhysics()
virtual bool UInstancedStaticMeshComponent::CanEditSimulatePhysics () override virtual
Reimplemented from UStaticMeshComponent.
CanEditSMInstance()
virtual bool UInstancedStaticMeshComponent::CanEditSMInstance (const FSMInstanceId & InstanceId) const override protected virtual
CanMoveSMInstance()
virtual bool UInstancedStaticMeshComponent::CanMoveSMInstance (const FSMInstanceId & InstanceId, const ETypedElementWorldType WorldType) const override protected virtual
Get the display name of the given static mesh instance.
Get the tooltip of the given static mesh instance. Can the given static mesh instance be edited?
Returns
True if it can be edited, false otherwise. Can the given static mesh instance be moved in the world?
True if it can be moved, false otherwise.
Implements ISMInstanceManager.
ClearAllInstanceBodies()
void UInstancedStaticMeshComponent::ClearAllInstanceBodies () protected
Terminate all body instances owned by this component.
ClearInstanceSelection()
void UInstancedStaticMeshComponent::ClearInstanceSelection ()
Deselect all instances.
CollectPSOPrecacheData()
virtual void UInstancedStaticMeshComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override virtual
Precache all PSOs which can be used by the component.
Reimplemented from UStaticMeshComponent.
ComponentIsTouchingSelectionBox()
virtual bool UInstancedStaticMeshComponent::ComponentIsTouchingSelectionBox (const FBox & InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
Reimplemented from UStaticMeshComponent.
ComponentIsTouchingSelectionFrustum()
virtual bool UInstancedStaticMeshComponent::ComponentIsTouchingSelectionFrustum (const FConvexVolume & InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
Reimplemented from UStaticMeshComponent.
ComponentOverlapComponentImpl()
virtual bool UInstancedStaticMeshComponent::ComponentOverlapComponentImpl (class UPrimitiveComponent * PrimComp, const FVector Pos, const FQuat & Quat, const FCollisionQueryParams & Params) override protected virtual
References FVector, Params, and Quat.
ComponentOverlapMultiImpl()
virtual bool UInstancedStaticMeshComponent::ComponentOverlapMultiImpl (TArray< struct FOverlapResult > & OutOverlaps, const class UWorld * InWorld, const FVector & Pos, const FQuat & Rot, ECollisionChannel TestChannel, const struct FComponentQueryParams & Params, const struct FCollisionObjectQueryParams & ObjectQueryParams = FCollisionObjectQueryParams::DefaultObjectQueryParam) const override protected virtual
References FCollisionObjectQueryParams::DefaultObjectQueryParam, FVector, and Params.
ComputeHLODHash()
virtual void UInstancedStaticMeshComponent::ComputeHLODHash (class FHLODHashBuilder & HashBuilder) const override virtual
Reimplemented from UStaticMeshComponent.
CreateAllInstanceBodies()
void UInstancedStaticMeshComponent::CreateAllInstanceBodies () protected
Creates body instances for all instances owned by this component.
CreateHitProxyData()
void UInstancedStaticMeshComponent::CreateHitProxyData (TArray< TRefCountPtr< HHitProxy > > & HitProxies) protected
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UInstancedStaticMeshComponent::CreateSceneProxy () override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
CreateStaticMeshSceneProxy()
virtual FPrimitiveSceneProxy * UInstancedStaticMeshComponent::CreateStaticMeshSceneProxy (Nanite::FMaterialAudit & NaniteMaterials, bool bCreateNanite) override protected virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
DeleteSMInstances()
virtual bool UInstancedStaticMeshComponent::DeleteSMInstances (TArrayView< const FSMInstanceId > InstanceIds) override protected virtual
Attempt to delete the given static mesh instances.
Returns
True if any instances were deleted, false otherwise.
Implements ISMInstanceManager.
DoCustomNavigableGeometryExport()
virtual bool UInstancedStaticMeshComponent::DoCustomNavigableGeometryExport (FNavigableGeometryExport & GeomExport) const override virtual
Reimplemented from UStaticMeshComponent.
DuplicateSMInstances()
virtual bool UInstancedStaticMeshComponent::DuplicateSMInstances (TArrayView< const FSMInstanceId > InstanceIds, TArray< FSMInstanceId > & OutNewInstanceIds) override protected virtual
Attempt to duplicate the given static mesh instances, retrieving the IDs of any new instances.
Returns
True if any instances were duplicated, false otherwise.
Implements ISMInstanceManager.
FullNavigationUpdate()
virtual void UInstancedStaticMeshComponent::FullNavigationUpdate () protected virtual
Request to navigation system to update for the bounds of the ISM.
GENERATED_UCLASS_BODY()
UInstancedStaticMeshComponent::GENERATED_UCLASS_BODY () & private
Needs implementation in InstancedStaticMesh.cpp to compile UniquePtr for forward declared class.
GetAllPhysicsObjects()
virtual TArray< Chaos::FPhysicsObject * > UInstancedStaticMeshComponent::GetAllPhysicsObjects () const override virtual
GetBodyInstance()
virtual FBodyInstance * UInstancedStaticMeshComponent::GetBodyInstance (FName BoneName = NAME_None, bool bGetWelded = true, int32 Index = INDEX_NONE) const override virtual
References INDEX_NONE.
GetComponentChildElements()
virtual void UInstancedStaticMeshComponent::GetComponentChildElements (TArray< FTypedElementHandle > & OutElementHandles, const bool bAllowCreate = true) override virtual
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > UInstancedStaticMeshComponent::GetComponentInstanceData () const override virtual
Reimplemented from UStaticMeshComponent.
GetInstanceDataSceneProxy()
const TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > & UInstancedStaticMeshComponent::GetInstanceDataSceneProxy () const
GetInstanceIndexForId()
FORCEINLINE int32 UInstancedStaticMeshComponent::GetInstanceIndexForId (FPrimitiveInstanceId InstanceId) const inline
Fetches current instance index for a given InstanceId.
Definition at line 307 of file InstancedStaticMeshComponent.h.
References FORCEINLINE, and PrimitiveInstanceDataManager.
GetInstanceNavigationBounds()
FBox UInstancedStaticMeshComponent::GetInstanceNavigationBounds () const protected
Returns the bounds of a single instance in local space.
It uses the NavCollision if available, then the StaticMesh bounds if available or an invalid box otherwise.
Returns
The bounds of a single instance in local space
GetInstancePrevTransform()
bool UInstancedStaticMeshComponent::GetInstancePrevTransform (int32 InstanceIndex, FTransform & OutInstanceTransform, bool bWorldSpace = false) const
Get the prev transform for the instance specified.
Only works if PerInstancePrevTransform has been setup and updated through BatchUpdateInstancesTransforms
References bWorldSpace, const, GetInstancePrevTransform(), and OutInstanceTransform.
Referenced by GetInstancePrevTransform().
GetInstancesMinMaxScale()
void UInstancedStaticMeshComponent::GetInstancesMinMaxScale (FVector & MinScale, FVector & MaxScale) const
References FVector.
GetLightAndShadowMapMemoryUsage()
virtual void UInstancedStaticMeshComponent::GetLightAndShadowMapMemoryUsage (int32 & LightMapMemoryUsage, int32 & ShadowMapMemoryUsage) const override virtual
Reimplemented from UStaticMeshComponent.
GetMaterialStreamingData()
virtual bool UInstancedStaticMeshComponent::GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo & MaterialData) const override virtual
Get material, UV density and bounds for a given material index.
Reimplemented from UStaticMeshComponent.
References const, and GetMaterialStreamingData().
Referenced by GetMaterialStreamingData().
GetNavigationBounds()
virtual FBox UInstancedStaticMeshComponent::GetNavigationBounds () const override virtual
Reimplemented from UStaticMeshComponent.
GetNavigationData()
virtual void UInstancedStaticMeshComponent::GetNavigationData (FNavigationRelevantData & Data) const override virtual
Reimplemented from UStaticMeshComponent.
GetNavigationPerInstanceTransforms()
virtual void UInstancedStaticMeshComponent::GetNavigationPerInstanceTransforms (const FBox & AreaBox, TArray< FTransform > & InstanceData) const protected virtual
Handles request from navigation system to gather instance transforms in a specific area box.
GetNumInstances()
int32 UInstancedStaticMeshComponent::GetNumInstances () const inline
Definition at line 275 of file InstancedStaticMeshComponent.h.
GetNumRenderInstances()
virtual int32 UInstancedStaticMeshComponent::GetNumRenderInstances () const inline virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
Definition at line 618 of file InstancedStaticMeshComponent.h.
GetOrCalcBounds()
FBoxSphereBounds UInstancedStaticMeshComponent::GetOrCalcBounds (const FTransform & InBoundTransform, EBoundsCacheType InType) const private
References Count.
GetOrCreateInstanceDataSceneProxy()
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > UInstancedStaticMeshComponent::GetOrCreateInstanceDataSceneProxy ()
GetPhysicsObjectById()
virtual Chaos::FPhysicsObject * UInstancedStaticMeshComponent::GetPhysicsObjectById (Chaos::FPhysicsObjectId Id) const override virtual
GetRenderIndex()
FORCEINLINE int32 UInstancedStaticMeshComponent::GetRenderIndex (int32 InInstanceIndex) const inline
Returns the render instance buffer index.
Definition at line 257 of file InstancedStaticMeshComponent.h.
References FORCEINLINE, and GetRenderIndex().
Referenced by GetRenderIndex().
GetRenderMatrix()
virtual FMatrix UInstancedStaticMeshComponent::GetRenderMatrix () const override virtual
GetResourceSizeEx()
virtual void UInstancedStaticMeshComponent::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
GetSMInstanceTransform()
virtual bool UInstancedStaticMeshComponent::GetSMInstanceTransform (const FSMInstanceId & InstanceId, FTransform & OutInstanceTransform, bool bWorldSpace = false) const override protected virtual
Attempt to get the transform of the given static mesh instance.
Note
The transform should be in the local space of the owner ISM component, unless bWorldSpace is set.
Returns
True if the transform was retrieved, false otherwise.
Implements ISMInstanceManager.
References bWorldSpace, and OutInstanceTransform.
GetStaticLightingInfo()
virtual void UInstancedStaticMeshComponent::GetStaticLightingInfo (FStaticLightingPrimitiveInfo & OutPrimitiveInfo, const TArray< ULightComponent * > & InRelevantLights, const FLightingBuildOptions & Options) override virtual
Reimplemented from UStaticMeshComponent.
GetStreamingBounds()
virtual FBox UInstancedStaticMeshComponent::GetStreamingBounds () const override virtual
GetStreamingRenderAssetInfo()
virtual void UInstancedStaticMeshComponent::GetStreamingRenderAssetInfo (FStreamingTextureLevelContext & LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > & OutStreamingRenderAssets) const override virtual
Get the StreaminTexture data.
Reimplemented from UStaticMeshComponent.
References const, and GetStreamingRenderAssetInfo().
Referenced by GetStreamingRenderAssetInfo().
GetTextureStreamingTransformScale()
virtual float UInstancedStaticMeshComponent::GetTextureStreamingTransformScale () const override virtual
Get the scale comming form the component, when computing StreamingTexture data.
Used to support instanced meshes.
Reimplemented from UStaticMeshComponent.
References const, and GetTextureStreamingTransformScale().
Referenced by GetTextureStreamingTransformScale().
GetTranslatedInstanceSpaceOrigin()
virtual FVector UInstancedStaticMeshComponent::GetTranslatedInstanceSpaceOrigin () const inline virtual
Get the translated space for instance transforms to be passed to the renderer.
In the renderer data structures we only have floating point precision for instance transforms relative to their owning primitive. The primitive transform itself has double precision. Some ISM that are authored in world space need to adjust the local space to keep instance transforms within precision limits.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
Definition at line 597 of file InstancedStaticMeshComponent.h.
References FVector, and UE::Math::TVector< double >::Zero().
GetUsedMaterialPropertyDesc()
FPrimitiveMaterialPropertyDescriptor UInstancedStaticMeshComponent::GetUsedMaterialPropertyDesc (ERHIFeatureLevel::Type FeatureLevel) const inline
wrapper which is public so we can implement the LIST ISM command
Definition at line 654 of file InstancedStaticMeshComponent.h.
InitializeInstancingRandomSeed()
void UInstancedStaticMeshComponent::InitializeInstancingRandomSeed () protected
InitInstanceBody()
void UInstancedStaticMeshComponent::InitInstanceBody (int32 InstanceIdx, FBodyInstance * InBodyInstance) protected
Initializes the body instance for the specified instance of the static mesh.
InvalidateCachedBounds()
void UInstancedStaticMeshComponent::InvalidateCachedBounds () protected
InvalidateInstanceDataTracking()
void UInstancedStaticMeshComponent::InvalidateInstanceDataTracking ()
Clears all the updated instance tracking data AND instance ID association, also forcing a full update of the instance data the next time it is flushed.
NOTE: Destroying the instance updated tracking means the renderer has to treat the instances as completely new, preventing e.g., velocity tracking and caching from working reliably. This function is only intended to be used when some outside entity has modified the instance data, this is not recommended and access to the public data will be removed in a future release.
IsCachedCookedPlatformDataLoaded()
virtual bool UInstancedStaticMeshComponent::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) override virtual
See: UObject::IsCachedCookedPlatformDataLoaded.
Reimplemented from UStaticMeshComponent.
IsHLODRelevant()
virtual bool UInstancedStaticMeshComponent::IsHLODRelevant () const override virtual
Reimplemented from UStaticMeshComponent.
IsInstanceSelected()
bool UInstancedStaticMeshComponent::IsInstanceSelected (int32 InInstanceIndex) const
Check to see if an instance is selected.
IsInstanceTouchingSelectionBox()
virtual bool UInstancedStaticMeshComponent::IsInstanceTouchingSelectionBox (int32 InstanceIndex, const FBox & InBox, const bool bMustEncompassEntireInstance) const virtual
IsInstanceTouchingSelectionFrustum()
virtual bool UInstancedStaticMeshComponent::IsInstanceTouchingSelectionFrustum (int32 InstanceIndex, const FConvexVolume & InFrustum, const bool bMustEncompassEntireInstance) const virtual
IsNavigationRelevant()
virtual bool UInstancedStaticMeshComponent::IsNavigationRelevant () const override virtual
Reimplemented from UStaticMeshComponent.
IsValidId()
bool UInstancedStaticMeshComponent::IsValidId (FPrimitiveInstanceId InstanceId)
LineTraceComponent()
virtual bool UInstancedStaticMeshComponent::LineTraceComponent (FHitResult & OutHit, const FVector Start, const FVector End, const FCollisionQueryParams & Params) override virtual
References End, FVector, and Params.
MakeInstanceDataFlags()
FInstanceDataFlags UInstancedStaticMeshComponent::MakeInstanceDataFlags (bool bAnyMaterialHasPerInstanceRandom, bool bAnyMaterialHasPerInstanceCustomData) const
NotifySMInstanceMovementEnded()
virtual void UInstancedStaticMeshComponent::NotifySMInstanceMovementEnded (const FSMInstanceId & InstanceId) override protected virtual
Notify that the given static mesh instance is done being moved.
Note
This gives the manager a chance to end a move operation.
Implements ISMInstanceManager.
NotifySMInstanceMovementOngoing()
virtual void UInstancedStaticMeshComponent::NotifySMInstanceMovementOngoing (const FSMInstanceId & InstanceId) override protected virtual
Notify that the given static mesh instance is currently being moved.
Note
This gives the manager a chance to update a move operation.
Implements ISMInstanceManager.
NotifySMInstanceMovementStarted()
virtual void UInstancedStaticMeshComponent::NotifySMInstanceMovementStarted (const FSMInstanceId & InstanceId) override protected virtual
Notify that the given static mesh instance is about to be moved.
Note
This gives the manager a chance to start a move operation, to avoid performing repeated work until the move is finished.
Implements ISMInstanceManager.
NotifySMInstanceSelectionChanged()
virtual void UInstancedStaticMeshComponent::NotifySMInstanceSelectionChanged (const FSMInstanceId & InstanceId, const bool bIsSelected) override protected virtual
Notify that the given static mesh instance selection state has changed.
Note
This gives the manager a chance to sync any internal selection state.
Implements ISMInstanceManager.
OnAsyncDestroyPhysicsState()
virtual bool UInstancedStaticMeshComponent::OnAsyncDestroyPhysicsState (const UE::FTimeout & Timeout) override protected virtual
References Timeout.
OnAsyncDestroyPhysicsStateBegin_GameThread()
virtual void UInstancedStaticMeshComponent::OnAsyncDestroyPhysicsStateBegin_GameThread () override protected virtual
OnCreatePhysicsState()
virtual void UInstancedStaticMeshComponent::OnCreatePhysicsState () override protected virtual
Reimplemented from UStaticMeshComponent.
OnDestroyPhysicsState()
virtual void UInstancedStaticMeshComponent::OnDestroyPhysicsState () override protected virtual
Reimplemented from UStaticMeshComponent.
OnPostLoadPerInstanceData()
virtual void UInstancedStaticMeshComponent::OnPostLoadPerInstanceData () protected virtual
Creates rendering buffer from serialized data, if any.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
Referenced by UE_DEPRECATED().
OnRegister()
virtual void UInstancedStaticMeshComponent::OnRegister () override virtual
References OnRegister().
Referenced by OnRegister().
OnUnregister()
virtual void UInstancedStaticMeshComponent::OnUnregister () override virtual
Reimplemented from UStaticMeshComponent.
References OnUnregister().
Referenced by OnUnregister().
OnUpdateTransform()
virtual void UInstancedStaticMeshComponent::OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) override virtual
References OnUpdateTransform().
Referenced by OnUpdateTransform().
OverlapComponent()
virtual bool UInstancedStaticMeshComponent::OverlapComponent (const FVector & Pos, const FQuat & Rot, const FCollisionShape & CollisionShape) const override virtual
References FVector.
PartialNavigateUpdateForCurrentInstances()
void UInstancedStaticMeshComponent::PartialNavigateUpdateForCurrentInstances () private
PartialNavigationUpdate()
virtual void UInstancedStaticMeshComponent::PartialNavigationUpdate (int32 InstanceIdx) virtual
Request to navigation system to update only part of navmesh occupied by specified instance.
Referenced by UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED().
PartialNavigationUpdates()
virtual void UInstancedStaticMeshComponent::PartialNavigationUpdates (TConstArrayView< FTransform > InstanceTransforms) virtual
Request to navigation system to update only part of navmesh occupied specified instances transforms.
PostEditChangeChainProperty()
virtual void UInstancedStaticMeshComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
Reimplemented from UMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
PostEditUndo()
virtual void UInstancedStaticMeshComponent::PostEditUndo () override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
PostLoad()
virtual void UInstancedStaticMeshComponent::PostLoad () override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References PostLoad().
Referenced by PostLoad().
PostStaticMeshCompilation()
virtual void UInstancedStaticMeshComponent::PostStaticMeshCompilation () override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
PreAllocateInstancesMemory()
virtual void UInstancedStaticMeshComponent::PreAllocateInstancesMemory (int32 AddedInstanceCount) virtual
Preallocated memory to include the new added instances count, to prevent reallloc during the add operation.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References PreAllocateInstancesMemory().
Referenced by PreAllocateInstancesMemory().
PreApplyComponentInstanceData()
void UInstancedStaticMeshComponent::PreApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData * ComponentInstanceData)
Handle changes that must happen before the proxy is recreated.
PreSave()
virtual void UInstancedStaticMeshComponent::PreSave (FObjectPreSaveContext ObjectSaveContext) override virtual
PropagateLightingScenarioChange()
virtual void UInstancedStaticMeshComponent::PropagateLightingScenarioChange () override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
RemoveInstanceById()
void UInstancedStaticMeshComponent::RemoveInstanceById (FPrimitiveInstanceId InstanceId) inline
Definition at line 295 of file InstancedStaticMeshComponent.h.
References MakeArrayView(), and RemoveInstancesById().
RemoveInstanceInternal()
bool UInstancedStaticMeshComponent::RemoveInstanceInternal (int32 InstanceIndex, bool InstanceAlreadyRemoved, bool bForceRemoveAtSwap = false, bool bUpdateNavigation = true) protected
Internal version of RemoveInstance.
References bUpdateNavigation.
RemoveInstances()
virtual bool UInstancedStaticMeshComponent::RemoveInstances (const TArray< int32 > & InstancesToRemove, bool bInstanceArrayAlreadySortedInReverseOrder) virtual
Remove the instances specified.
Returns True on success.
Parameters
InstancesToRemove array of the instance indices to remove (can be sorted
See also
bInstanceArrayAlreadySortedInReverseOrder)
Parameters
bInstanceArrayAlreadySortedInReverseOrder true is the array is already sorted in reverse order
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References const, and RemoveInstances().
Referenced by RemoveInstances(), and UFUNCTION().
RemoveInstancesById()
virtual void UInstancedStaticMeshComponent::RemoveInstancesById (const TArrayView< const FPrimitiveInstanceId > & InstanceIds, bool bUpdateNavigation = true) virtual
References bUpdateNavigation.
Referenced by RemoveInstanceById().
SelectInstance()
void UInstancedStaticMeshComponent::SelectInstance (bool bInSelected, int32 InInstanceIndex, int32 InInstanceCount = 1)
Select/deselect an instance or group of instances.
SendRenderInstanceData_Concurrent()
virtual void UInstancedStaticMeshComponent::SendRenderInstanceData_Concurrent () override virtual
Serialize()
virtual void UInstancedStaticMeshComponent::Serialize (FArchive & Ar) override virtual
Reimplemented from UStaticMeshComponent.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References Ar.
SerializeRenderData()
void UInstancedStaticMeshComponent::SerializeRenderData (FArchive & Ar) protected
Serialize instance buffer that is used for rendering.
Only for cooked content
References Ar.
SetBakedLightingDataChanged()
void UInstancedStaticMeshComponent::SetBakedLightingDataChanged (int32 InInstanceIndex)
Mark the "shadowmap" or lightmap uv as modified for the instance since this is stored in external data.
SetBakedLightingDataChangedAll()
void UInstancedStaticMeshComponent::SetBakedLightingDataChangedAll ()
Mark the "shadowmap" or lightmap uv as modified for all the instances since this is stored in external data.
SetCustomData() [1/2]
virtual bool UInstancedStaticMeshComponent::SetCustomData (int32 InstanceIndex, TArrayView< const float > CustomDataFloats, bool bMarkRenderStateDirty = false) virtual
Per Instance Custom Data.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
References bMarkRenderStateDirty, const, and SetCustomData().
Referenced by SetCustomData(), and SetCustomData().
SetCustomData() [2/2]
virtual bool UInstancedStaticMeshComponent::SetCustomData (int32 InstanceIndexStart, int32 InstanceIndexEnd, TConstArrayView< float > CustomDataFloats, bool bMarkRenderStateDirty = false) virtual
References bMarkRenderStateDirty, and SetCustomData().
SetCustomDataById() [1/2]
void UInstancedStaticMeshComponent::SetCustomDataById (const TArrayView< const FPrimitiveInstanceId > & InstanceIds, TArrayView< const float > CustomDataFloats)
SetCustomDataById() [2/2]
void UInstancedStaticMeshComponent::SetCustomDataById (FPrimitiveInstanceId InstanceId, TArrayView< const float > CustomDataFloats) inline
Definition at line 289 of file InstancedStaticMeshComponent.h.
References MakeArrayView(), and SetCustomDataById().
Referenced by SetCustomDataById().
SetCustomDataValueById()
void UInstancedStaticMeshComponent::SetCustomDataValueById (FPrimitiveInstanceId InstanceId, int32 CustomDataIndex, float CustomDataValue)
References CustomDataIndex, and CustomDataValue.
SetHasPerInstancePrevTransforms()
void UInstancedStaticMeshComponent::SetHasPerInstancePrevTransforms (bool bInHasPreviousTransforms)
SetPreviousTransformById()
void UInstancedStaticMeshComponent::SetPreviousTransformById (FPrimitiveInstanceId InstanceId, const FTransform & NewPrevInstanceTransform, bool bWorldSpace = false)
References bWorldSpace.
SetRemoveSwap()
void UInstancedStaticMeshComponent::SetRemoveSwap () inline
Sets to use RemoveAtSwap on instance removal.
This is an optimization, but will change the resultant instance reordering.
Definition at line 454 of file InstancedStaticMeshComponent.h.
References bSupportRemoveAtSwap, and SetRemoveSwap().
Referenced by SetRemoveSwap().
SetSMInstanceTransform()
virtual bool UInstancedStaticMeshComponent::SetSMInstanceTransform (const FSMInstanceId & InstanceId, const FTransform & InstanceTransform, bool bWorldSpace = false, bool bMarkRenderStateDirty = false, bool bTeleport = false) override protected virtual
Attempt to set the transform of the given static mesh instance.
Note
The transform should be in the local space of the owner ISM component, unless bWorldSpace is set.
Returns
True if the transform was updated, false otherwise.
Implements ISMInstanceManager.
References bMarkRenderStateDirty, bTeleport, and bWorldSpace.
SetupNewInstanceData()
void UInstancedStaticMeshComponent::SetupNewInstanceData (FInstancedStaticMeshInstanceData & InOutNewInstanceData, int32 InInstanceIndex, const FTransform & InInstanceTransform) private
Sets up new instance data to sensible defaults, creates physics counterparts if possible.
SetUseConservativeBounds()
void UInstancedStaticMeshComponent::SetUseConservativeBounds (bool bValue) inline
Sets whether to use conservative bounds.
This doesn't fully recalculate bounds on instance addition/removal/transform change. Instead maintains a conservative bound that only grows.
Definition at line 463 of file InstancedStaticMeshComponent.h.
References bUseConservativeBounds, and CachedConservativeInstanceBounds.
ShouldCreatePhysicsState()
virtual bool UInstancedStaticMeshComponent::ShouldCreatePhysicsState () const override virtual
Reimplemented from UStaticMeshComponent.
References const, and ShouldCreatePhysicsState().
Referenced by ShouldCreatePhysicsState().
ShouldInheritPerInstanceData() [1/2]
bool UInstancedStaticMeshComponent::ShouldInheritPerInstanceData () const private
ShouldInheritPerInstanceData() [2/2]
bool UInstancedStaticMeshComponent::ShouldInheritPerInstanceData (const UInstancedStaticMeshComponent * InArchetype) const private
ShouldSkipDirtyAreaOnAddOrRemove()
virtual bool UInstancedStaticMeshComponent::ShouldSkipDirtyAreaOnAddOrRemove () const override virtual
SupportsPartialNavigationUpdate()
virtual bool UInstancedStaticMeshComponent::SupportsPartialNavigationUpdate () const inline protected virtual
Does this component support partial navigation updates.
Definition at line 716 of file InstancedStaticMeshComponent.h.
References SupportsPartialNavigationUpdate().
Referenced by SupportsPartialNavigationUpdate(), and UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED().
SupportsRemoveSwap()
virtual bool UInstancedStaticMeshComponent::SupportsRemoveSwap () const virtual
Returns true if RemoveAtSwap is enabled.
Derived classes may always return true regardless of whether SetRemoveSwapEnabled() was called.
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
SupportsStaticLighting()
virtual bool UInstancedStaticMeshComponent::SupportsStaticLighting () const inline override virtual
Whether the component type supports static lighting.
Reimplemented from UStaticMeshComponent.
Definition at line 534 of file InstancedStaticMeshComponent.h.
SweepComponent()
virtual bool UInstancedStaticMeshComponent::SweepComponent (FHitResult & OutHit, const FVector Start, const FVector End, const FQuat & ShapRotation, const FCollisionShape & CollisionShape, bool bTraceComplex = false) override virtual
References End, and FVector.
UE_DEPRECATED() [1/3]
UInstancedStaticMeshComponent::UE_DEPRECATED (5. 0, "Use AddInstance or AddInstances with bWorldSpace set to true.") const & inline
Add an instance to this component.
Transform is given in world space.
Definition at line 268 of file InstancedStaticMeshComponent.h.
References Category, const, meta, UE_DEPRECATED(), and UFUNCTION().
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "This function has been added only for the purposes of moving LWI code outside of the engine. Don't use it, it will be removed soon.") inline
Definition at line 625 of file InstancedStaticMeshComponent.h.
References OnPostLoadPerInstanceData().
UE_DEPRECATED() [3/3]
UInstancedStaticMeshComponent::UE_DEPRECATED (5. 5, "Use version with FBox") const & protected
UFUNCTION() [1/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Get the transform for the instance specified.
Instance is returned in local space of this component unless bWorldSpace is set. Returns True on success.
References Category, and UFUNCTION().
UFUNCTION() [2/19]
UInstancedStaticMeshComponent::UFUNCTION () const
Does the given index map to a valid instance in this component?
References Category, const, and UFUNCTION().
UFUNCTION() [3/19]
UInstancedStaticMeshComponent::UFUNCTION () const
Get the number of instances in this component.
References Category, const, and UFUNCTION().
UFUNCTION() [4/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Update the transform for a number of instances.
Parameters
StartInstanceIndex The starting index of the instances to update
NumInstances The number of instances to update
NewInstancesTransform The new transform
bWorldSpace If true, the new transform is interpreted as a World Space transform, otherwise it is interpreted as Local Space
bMarkRenderStateDirty If true, the change should be visible immediately. If you are updating many instances you should only set this to true for the last instance.
bTeleport Whether or not the instances physics should be moved normally, or teleported (moved instantly, ignoring velocity).
Returns
True on success.
References Category, and UFUNCTION().
UFUNCTION() [5/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Update the transform for an array of instances.
Parameters
StartInstanceIndex The starting index of the instances to update
NewInstancesTransforms The new transforms
bWorldSpace If true, the new transforms are interpreted as a World Space transform, otherwise it is interpreted as Local Space
bMarkRenderStateDirty If true, the change should be visible immediately. If you are updating many instances you should only set this to true for the last instance.
bTeleport Whether or not the instances physics should be moved normally, or teleported (moved instantly, ignoring velocity).
Returns
True on success.
References Category, and UFUNCTION().
UFUNCTION() [6/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Remove the instance specified.
Returns True on success.
References Category, and UFUNCTION().
UFUNCTION() [7/19]
UInstancedStaticMeshComponent::UFUNCTION () const &
Remove the instances specified.
Returns True on success.
References Category, const, RemoveInstances(), and UFUNCTION().
UFUNCTION() [8/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Update custom data for specific instance.
References Category.
UFUNCTION() [9/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Update the transform for the instance specified.
Parameters
InstanceIndex The index of the instance to update
NewInstanceTransform The new transform
bWorldSpace If true, the new transform is interpreted as a World Space transform, otherwise it is interpreted as Local Space
bMarkRenderStateDirty If true, the change should be visible immediately. If you are updating many instances you should only set this to true for the last instance.
bTeleport Whether or not the instance's physics should be moved normally, or teleported (moved instantly, ignoring velocity).
Returns
True on success.
References Category, and UFUNCTION().
UFUNCTION() [10/19]
UInstancedStaticMeshComponent::UFUNCTION () const &
Add an instance to this component.
Transform is given in local space of this component unless bWorldSpace is set.
References Category.
Referenced by UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [11/19]
UInstancedStaticMeshComponent::UFUNCTION () const &
Add multiple instances to this component.
Transform is given in local space of this component unless bWorldSpace is set.
References Category, and UFUNCTION().
UFUNCTION() [12/19]
UInstancedStaticMeshComponent::UFUNCTION () const &
Returns the instances with instance bounds overlapping the specified box.
The return value is an array of instance indices.
References Category, and UFUNCTION().
UFUNCTION() [13/19]
UInstancedStaticMeshComponent::UFUNCTION () const &
Returns the instances with instance bounds overlapping the specified sphere.
The return value is an array of instance indices.
References Category.
UFUNCTION() [14/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Clear all instances being rendered by this component.
References Category, and UFUNCTION().
UFUNCTION() [15/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Update number of custom data entries per instance.
This applies to all instances and will reallocate the full custom data buffer and reset all values to 0
References Category, and UFUNCTION().
UFUNCTION() [16/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Sets the fading start and culling end distances for this component.
References Category, and UFUNCTION().
UFUNCTION() [17/19]
UInstancedStaticMeshComponent::UFUNCTION ()
Sets the LOD scale.
References Category.
UFUNCTION() [18/19]
UInstancedStaticMeshComponent::UFUNCTION () const inline
Gets the current LOD scale.
Definition at line 331 of file InstancedStaticMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [19/19]
UInstancedStaticMeshComponent::UFUNCTION () &
Gets the fading start and culling end distances for this component.
References Category, and UFUNCTION().
UpdateBounds()
virtual void UInstancedStaticMeshComponent::UpdateBounds () override virtual
Reimplemented from UStaticMeshComponent.
UpdateComponentTransform()
void UInstancedStaticMeshComponent::UpdateComponentTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport)
References UpdateComponentTransform().
Referenced by UpdateComponentTransform().
UpdateInstanceBodyTransform()
void UInstancedStaticMeshComponent::UpdateInstanceBodyTransform (int32 InstanceIndex, const FTransform & WorldSpaceInstanceTransform, bool bTeleport) private
Update instance body with a new transform.
References bTeleport.
UpdateInstanceTransformById()
void UInstancedStaticMeshComponent::UpdateInstanceTransformById (FPrimitiveInstanceId InstanceId, const FTransform & NewInstanceTransform, bool bWorldSpace = false, bool bTeleport = false)
References bTeleport, bWorldSpace, and NewInstanceTransform.
UPROPERTY() [1/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Scale applied to change the computation of LOD distances when using the StaticMesh screen sizes.
Smaller values make LODs transition earlier.
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [2/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Main transform stored to be able to send updates when component's transform changed.
Implements UStaticMeshComponent.
References Transient, and UPROPERTY().
UPROPERTY() [3/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Distance from camera at which each instance completely fades out.
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [4/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Distance from camera at which each instance begins to draw.
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [5/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Distance from camera at which each instance begins to fade out.
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [6/14]
UInstancedStaticMeshComponent::UPROPERTY () private pure virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UStaticMeshComponent.
Implemented in UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, and UHierarchicalInstancedStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [7/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Defines the number of floats that will be available per instance for custom data.
Implements UStaticMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [8/14]
UInstancedStaticMeshComponent::UPROPERTY () protected virtual
Number of pending lightmaps still to be calculated (Apply()'d).
Implements UStaticMeshComponent.
References Transient.
UPROPERTY() [9/14]
UInstancedStaticMeshComponent::UPROPERTY () protected virtual
The mappings for all the instances of this component.
Implements UStaticMeshComponent.
References Transient.
UPROPERTY() [10/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Additional random seeds ranges.
Each seed entry will be applied from AdditionalRandomSeeds[i].StartInstanceIndex to AdditionalRandomSeeds[i+1].StartInstanceIndex -1
Implements UStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [11/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Array of prev instance transforms.
Must match the length of PerInstanceSMData or have 0 elements
Implements UStaticMeshComponent.
References Transient, and UPROPERTY().
UPROPERTY() [12/14]
UInstancedStaticMeshComponent::UPROPERTY () virtual
Mapping from PerInstanceSMData order to instance render buffer order.
If empty, the PerInstanceSMData order is used.
Implements UStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [13/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Array of instances, bulk serialized.
Implements UStaticMeshComponent.
References Category, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [14/14]
UInstancedStaticMeshComponent::UPROPERTY () private virtual
Array of custom data for instances.
This will contains NumCustomDataFloats*InstanceCount entries. The entries are represented sequantially, in instance order. Can be read in a material and manipulated through Blueprints. Example: If NumCustomDataFloats is 1, then each entry will belong to an instance. Custom data 0 will belong to Instance 0. Custom data 1 will belong to Instance 1 etc. Example: If NumCustomDataFloats is 2, then each pair of sequential entries belong to an instance. Custom data 0 and 1 will belong to Instance 0. Custom data 2 and 3 will belong to Instance 2 etc.
Implements UStaticMeshComponent.
References Category, meta, and UPROPERTY().
Field Documentation
AsyncDestroyPhysicsStatePayload
TArray<FBodyInstance*> UInstancedStaticMeshComponent::AsyncDestroyPhysicsStatePayload private
Payload used by asynchronous destruction of physics state (see OnAsyncDestroyPhysicsState).
Definition at line 485 of file InstancedStaticMeshComponent.h.
bBoxInWorldSpace
bool UInstancedStaticMeshComponent::bBoxInWorldSpace =true) const
Definition at line 445 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::GetInstancesOverlappingBox().
bForceShowAllInstancesDetails
bool UInstancedStaticMeshComponent::bForceShowAllInstancesDetails = false
Indicates that the user has purposedly chosen to show the instance list in the details panel, despite the performance warning.
Definition at line 493 of file InstancedStaticMeshComponent.h.
bHasPreviousTransforms
uint8 UInstancedStaticMeshComponent::bHasPreviousTransforms private
Definition at line 240 of file InstancedStaticMeshComponent.h.
bIsInstanceDataApplyCompleted
uint8 UInstancedStaticMeshComponent::bIsInstanceDataApplyCompleted protected
Definition at line 237 of file InstancedStaticMeshComponent.h.
bIsUpdatingBounds
uint8 UInstancedStaticMeshComponent::bIsUpdatingBounds private
Internally used to know when CalcBounds is called by UpdateBounds.
Definition at line 246 of file InstancedStaticMeshComponent.h.
bMarkRenderStateDirty [1/4]
int32 float bool UInstancedStaticMeshComponent::bMarkRenderStateDirty = false)
Definition at line 313 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesData(), BatchUpdateInstancesData(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal(), BatchUpdateInstancesTransformsInternal(), UHierarchicalInstancedStaticMeshComponent::SetCustomData(), SetCustomData(), SetCustomData(), UHierarchicalInstancedStaticMeshComponent::SetCustomDataValue(), SetSMInstanceTransform(), and UHierarchicalInstancedStaticMeshComponent::UpdateInstanceTransform().
bMarkRenderStateDirty [2/4]
const FTransform bool bool UInstancedStaticMeshComponent::bMarkRenderStateDirty =false
Definition at line 365 of file InstancedStaticMeshComponent.h.
bMarkRenderStateDirty [3/4]
const TArray<FTransform> bool bool UInstancedStaticMeshComponent::bMarkRenderStateDirty =false
Definition at line 378 of file InstancedStaticMeshComponent.h.
bMarkRenderStateDirty [4/4]
int32 const FTransform bool bool UInstancedStaticMeshComponent::bMarkRenderStateDirty =false
Definition at line 401 of file InstancedStaticMeshComponent.h.
bShouldReturnIndices
bool UInstancedStaticMeshComponent::bShouldReturnIndices
Definition at line 265 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::AddInstances(), and AddInstancesInternal().
bSphereInWorldSpace
float bool UInstancedStaticMeshComponent::bSphereInWorldSpace =true) const
Definition at line 441 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::GetInstancesOverlappingSphere().
bSupportRemoveAtSwap
UPROPERTY () uint8 bUseGpuLodSelection UPROPERTY () uint8 bInheritPerInstanceData UPROPERTY () uint8 bDisableCollision uint8 UInstancedStaticMeshComponent::bSupportRemoveAtSwap private
If true, this component will use GPU LOD selection.
If true, this component will avoid serializing its per instance data / those properties will also not be editable Don't create any collision when this bool is set Flag for using RemoveAtSwap on instance removal. The implementation is free to ignore this flag, but should honor whatever behavior is being returned by SupportsRemoveSwap().
Definition at line 234 of file InstancedStaticMeshComponent.h.
Referenced by SetRemoveSwap().
bTeleport [1/3]
const FTransform bool bool bool UInstancedStaticMeshComponent::bTeleport =false)
Definition at line 365 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesData(), BatchUpdateInstancesData(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal(), BatchUpdateInstancesTransformsInternal(), SetSMInstanceTransform(), UpdateInstanceBodyTransform(), UHierarchicalInstancedStaticMeshComponent::UpdateInstanceTransform(), and UpdateInstanceTransformById().
bTeleport [2/3]
const TArray<FTransform> bool bool bool UInstancedStaticMeshComponent::bTeleport =false)
Definition at line 378 of file InstancedStaticMeshComponent.h.
bTeleport [3/3]
int32 const FTransform bool bool bool UInstancedStaticMeshComponent::bTeleport =false)
Definition at line 401 of file InstancedStaticMeshComponent.h.
bUpdateNavigation
bool bool bool UInstancedStaticMeshComponent::bUpdateNavigation = true)
Definition at line 265 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::AddInstances(), AddInstancesById(), AddInstancesInternal(), RemoveInstanceInternal(), and RemoveInstancesById().
bUseConservativeBounds
uint8 UInstancedStaticMeshComponent::bUseConservativeBounds private
Flag for whether we are using conservative bounds.
Definition at line 243 of file InstancedStaticMeshComponent.h.
Referenced by SetUseConservativeBounds().
bWorldSpace [1/6]
bool UInstancedStaticMeshComponent::bWorldSpace = false)
Definition at line 261 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::AddInstance(), AddInstanceById(), AddInstanceInternal(), UHierarchicalInstancedStaticMeshComponent::AddInstances(), AddInstancesById(), AddInstancesInternal(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal(), BatchUpdateInstancesTransformsInternal(), GetInstancePrevTransform(), GetSMInstanceTransform(), SetPreviousTransformById(), SetSMInstanceTransform(), UHierarchicalInstancedStaticMeshComponent::UpdateInstanceTransform(), and UpdateInstanceTransformById().
bWorldSpace [2/6]
bool bool UInstancedStaticMeshComponent::bWorldSpace = false
Definition at line 265 of file InstancedStaticMeshComponent.h.
bWorldSpace [3/6]
FTransform bool UInstancedStaticMeshComponent::bWorldSpace = false) const
Definition at line 328 of file InstancedStaticMeshComponent.h.
bWorldSpace [4/6]
const FTransform bool UInstancedStaticMeshComponent::bWorldSpace =false
Definition at line 365 of file InstancedStaticMeshComponent.h.
bWorldSpace [5/6]
const TArray<FTransform> bool UInstancedStaticMeshComponent::bWorldSpace =false
Definition at line 378 of file InstancedStaticMeshComponent.h.
bWorldSpace [6/6]
int32 const FTransform bool UInstancedStaticMeshComponent::bWorldSpace =false
Definition at line 401 of file InstancedStaticMeshComponent.h.
CachedConservativeInstanceBounds
FBox UInstancedStaticMeshComponent::CachedConservativeInstanceBounds private
Current cached conservativ bounds.
Definition at line 482 of file InstancedStaticMeshComponent.h.
Referenced by SetUseConservativeBounds().
const [1/2]
int32& OutEndCullDistance UInstancedStaticMeshComponent::const { OutStartCullDistance = InstanceStartCullDistance
Definition at line 437 of file InstancedStaticMeshComponent.h.
Referenced by BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal(), CalcBoundsImpl(), GetInstancePrevTransform(), GetMaterialStreamingData(), GetStreamingRenderAssetInfo(), GetTextureStreamingTransformScale(), RemoveInstances(), SetCustomData(), ShouldCreatePhysicsState(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
const [2/2]
bool bForNavigation UInstancedStaticMeshComponent::const protected
Definition at line 706 of file InstancedStaticMeshComponent.h.
CustomDataIndex
int32 UInstancedStaticMeshComponent::CustomDataIndex
Definition at line 313 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::SetCustomDataValue(), and SetCustomDataValueById().
CustomDataValue
int32 float UInstancedStaticMeshComponent::CustomDataValue
Definition at line 313 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::SetCustomDataValue(), and SetCustomDataValueById().
DeletionState
EInstanceDeletionReason UInstancedStaticMeshComponent::DeletionState = EInstanceDeletionReason::NotDeleting
This will be set to the appropriate state when one or more instances are in the process of being deleted.
This is primarily used for functions that round trip to this class, such as callbacks for deselecting instances.
Definition at line 506 of file InstancedStaticMeshComponent.h.
EndCullDistance
int32 UInstancedStaticMeshComponent::EndCullDistance
Definition at line 433 of file InstancedStaticMeshComponent.h.
FInstancedLightMap2D
friend UInstancedStaticMeshComponent::FInstancedLightMap2D protected
Definition at line 775 of file InstancedStaticMeshComponent.h.
FInstancedShadowMap2D
friend UInstancedStaticMeshComponent::FInstancedShadowMap2D protected
Definition at line 776 of file InstancedStaticMeshComponent.h.
FStaticLightingTextureMapping_InstancedStaticMesh
friend UInstancedStaticMeshComponent::FStaticLightingTextureMapping_InstancedStaticMesh protected
Definition at line 774 of file InstancedStaticMeshComponent.h.
Referenced by ApplyLightMapping().
InstanceBodies
TArray<FBodyInstance*> UInstancedStaticMeshComponent::InstanceBodies
Physics representation of the instance bodies.
Definition at line 509 of file InstancedStaticMeshComponent.h.
NewInstancesTransform
int32 const FTransform& UInstancedStaticMeshComponent::NewInstancesTransform
Definition at line 401 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform().
NewInstancesTransforms
const TArray<FTransform>& UInstancedStaticMeshComponent::NewInstancesTransforms
Definition at line 378 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), BatchUpdateInstancesTransforms(), UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal(), and BatchUpdateInstancesTransformsInternal().
NewInstanceTransform
const FTransform& UInstancedStaticMeshComponent::NewInstanceTransform
Definition at line 365 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::UpdateInstanceTransform(), and UpdateInstanceTransformById().
NumInstances
int32 UInstancedStaticMeshComponent::NumInstances
Definition at line 401 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesData(), BatchUpdateInstancesData(), and UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform().
OutEndCullDistance
UInstancedStaticMeshComponent::OutEndCullDistance = InstanceEndCullDistance
Definition at line 437 of file InstancedStaticMeshComponent.h.
OutInstanceTransform
FTransform& UInstancedStaticMeshComponent::OutInstanceTransform
Definition at line 328 of file InstancedStaticMeshComponent.h.
Referenced by GetInstancePrevTransform(), and GetSMInstanceTransform().
PrimitiveInstanceDataManager
FPrimitiveInstanceDataManager UInstancedStaticMeshComponent::PrimitiveInstanceDataManager protected
Definition at line 681 of file InstancedStaticMeshComponent.h.
Referenced by GetInstanceIndexForId().
ProxySize
SIZE_T UInstancedStaticMeshComponent::ProxySize
Tracks outstanding proxysize, as this is a bit hard to do with the fire-and-forget grass.
Definition at line 254 of file InstancedStaticMeshComponent.h.
Radius
float UInstancedStaticMeshComponent::Radius
Definition at line 441 of file InstancedStaticMeshComponent.h.
Referenced by UHierarchicalInstancedStaticMeshComponent::GetInstancesOverlappingSphere().
SelectedInstances
TBitArray UInstancedStaticMeshComponent::SelectedInstances
One bit per instance if the instance is selected.
Definition at line 490 of file InstancedStaticMeshComponent.h.
The documentation for this class was generated from the following file:
InstancedStaticMeshComponent.h