Unreal Engine 5.6 C++ API: FBindingObject Class Reference
FBindingObject Class Reference
#include "BlueprintNodeBinder.h"
Public Member Functions
FBindingObject ()
FBindingObject (const FFieldVariant &InFieldOrObject)
FBindingObject (FField *InField)
template<typename T UE_REQUIRES>
FBindingObject (T InObject)
void AddStructReferencedObjects (FReferenceCollector &Collector)
template<typename T>
T * Get () const
FName GetFName () const
FString GetFullName () const
FString GetName () const
FString GetPathName () const
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *InClass) const
bool IsA (const UClass *InClass) const
bool IsUObject () const
bool IsValid () const
bool operator!= (const FBindingObject &Other) const
FBindingObject & operator= (FField *InField)
template<typename T UE_REQUIRES>
FBindingObject & operator= (T InObject)
FBindingObject & operator= (TYPE_OF_NULLPTR)
bool operator== (const FBindingObject &Other) const
Private Attributes
bool bIsUObject
FField * Field
TObjectPtr< UObject > Object
Friends
uint32 GetTypeHash (const FBindingObject &BindingObject)
bool operator!= (const FBindingObject &Lhs, const FField *Rhs)
bool operator!= (const FBindingObject &Lhs, const UObject *Rhs)
bool operator!= (const FBindingObject &Lhs, TYPE_OF_NULLPTR)
bool operator!= (const FField *Lhs, const FBindingObject &Rhs)
bool operator!= (const UObject *Lhs, const FBindingObject &Rhs)
bool operator!= (TYPE_OF_NULLPTR, const FBindingObject &Rhs)
bool operator== (const FBindingObject &Lhs, const FField *Rhs)
bool operator== (const FBindingObject &Lhs, const UObject *Rhs)
bool operator== (const FBindingObject &Lhs, TYPE_OF_NULLPTR)
bool operator== (const FField *Lhs, const FBindingObject &Rhs)
bool operator== (const UObject *Lhs, const FBindingObject &Rhs)
bool operator== (TYPE_OF_NULLPTR, const FBindingObject &Rhs)
Detailed Description
Definition at line 16 of file BlueprintNodeBinder.h.
Constructor & Destructor Documentation
FBindingObject() [1/4]
FBindingObject::FBindingObject () inline
Definition at line 22 of file BlueprintNodeBinder.h.
References bIsUObject.
Referenced by GetTypeHash, operator!=, operator!=, operator!=, operator!=(), operator!=, operator!=, operator!=, operator=(), operator=(), operator=(), operator==, operator==, operator==, operator==(), operator==, operator==, and operator==.
FBindingObject() [2/4]
template<typename T UE_REQUIRES> FBindingObject::FBindingObject (T InObject) inline
Definition at line 29 of file BlueprintNodeBinder.h.
References bIsUObject, and Object.
FBindingObject() [3/4]
FBindingObject::FBindingObject (FField * InField) inline
Definition at line 33 of file BlueprintNodeBinder.h.
References bIsUObject, and Field.
FBindingObject() [4/4]
FBindingObject::FBindingObject (const FFieldVariant & InFieldOrObject) inline
Definition at line 37 of file BlueprintNodeBinder.h.
References bIsUObject, Field, FFieldVariant::IsUObject(), Object, FFieldVariant::ToField(), and FFieldVariant::ToUObject().
Member Function Documentation
AddStructReferencedObjects()
void FBindingObject::AddStructReferencedObjects (FReferenceCollector & Collector)
Get()
template<typename T> T * FBindingObject::Get () const inline
Definition at line 125 of file BlueprintNodeBinder.h.
References bIsUObject, Cast(), CastField(), Field, and Object.
GetFName()
FName FBindingObject::GetFName () const inline
Definition at line 81 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
GetFullName()
FString FBindingObject::GetFullName () const inline
Definition at line 93 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
GetName()
FString FBindingObject::GetName () const inline
Definition at line 85 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
GetPathName()
FString FBindingObject::GetPathName () const inline
Definition at line 89 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
IsA() [1/3]
template<typename T> bool FBindingObject::IsA () const inline
Definition at line 106 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
IsA() [2/3]
bool FBindingObject::IsA (const FFieldClass * InClass) const inline
Definition at line 101 of file BlueprintNodeBinder.h.
References bIsUObject, and Field.
IsA() [3/3]
bool FBindingObject::IsA (const UClass * InClass) const inline
Definition at line 97 of file BlueprintNodeBinder.h.
References bIsUObject, and Object.
IsUObject()
bool FBindingObject::IsUObject () const inline
Definition at line 73 of file BlueprintNodeBinder.h.
References bIsUObject.
Referenced by operator!=, operator!=, operator!=, operator!=, operator!=, operator!=, operator==, operator==, operator==, operator==, operator==, and operator==.
IsValid()
bool FBindingObject::IsValid () const inline
Definition at line 77 of file BlueprintNodeBinder.h.
References bIsUObject, Field, and Object.
operator!=()
bool FBindingObject::operator!= (const FBindingObject & Other) const inline
Definition at line 153 of file BlueprintNodeBinder.h.
References FBindingObject(), bIsUObject, Field, Object, and Other.
operator=() [1/3]
FBindingObject & FBindingObject::operator= (FField * InField) inline
Definition at line 60 of file BlueprintNodeBinder.h.
References FBindingObject(), bIsUObject, Field, and Object.
operator=() [2/3]
template<typename T UE_REQUIRES> FBindingObject & FBindingObject::operator= (T InObject) inline
Definition at line 53 of file BlueprintNodeBinder.h.
References FBindingObject(), bIsUObject, Field, ImplicitConv(), and Object.
operator=() [3/3]
FBindingObject & FBindingObject::operator= (TYPE_OF_NULLPTR) inline
Definition at line 67 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, and Object.
operator==()
bool FBindingObject::operator== (const FBindingObject & Other) const inline
Definition at line 149 of file BlueprintNodeBinder.h.
References FBindingObject(), bIsUObject, Field, Object, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FBindingObject & BindingObject) friend
Definition at line 144 of file BlueprintNodeBinder.h.
References FBindingObject(), bIsUObject, Field, GetTypeHash, and Object.
Referenced by GetTypeHash.
operator!= [1/6]
bool operator!= (const FBindingObject & Lhs, const FField * Rhs) friend
Definition at line 179 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, and IsUObject().
operator!= [2/6]
bool operator!= (const FBindingObject & Lhs, const UObject * Rhs) friend
Definition at line 162 of file BlueprintNodeBinder.h.
References FBindingObject(), IsUObject(), and Object.
operator!= [3/6]
bool operator!= (const FBindingObject & Lhs, TYPE_OF_NULLPTR) friend
Definition at line 196 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, IsUObject(), and Object.
operator!= [4/6]
bool operator!= (const FField * Lhs, const FBindingObject & Rhs) friend
Definition at line 187 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, and IsUObject().
operator!= [5/6]
bool operator!= (const UObject * Lhs, const FBindingObject & Rhs) friend
Definition at line 170 of file BlueprintNodeBinder.h.
References FBindingObject(), IsUObject(), and Object.
operator!= [6/6]
bool operator!= (TYPE_OF_NULLPTR , const FBindingObject & Rhs) friend
Definition at line 204 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, IsUObject(), and Object.
operator== [1/6]
bool operator== (const FBindingObject & Lhs, const FField * Rhs) friend
Definition at line 175 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, and IsUObject().
operator== [2/6]
bool operator== (const FBindingObject & Lhs, const UObject * Rhs) friend
Definition at line 158 of file BlueprintNodeBinder.h.
References FBindingObject(), IsUObject(), and Object.
operator== [3/6]
bool operator== (const FBindingObject & Lhs, TYPE_OF_NULLPTR) friend
Definition at line 192 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, IsUObject(), and Object.
operator== [4/6]
bool operator== (const FField * Lhs, const FBindingObject & Rhs) friend
Definition at line 183 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, and IsUObject().
operator== [5/6]
bool operator== (const UObject * Lhs, const FBindingObject & Rhs) friend
Definition at line 166 of file BlueprintNodeBinder.h.
References FBindingObject(), IsUObject(), and Object.
operator== [6/6]
bool operator== (TYPE_OF_NULLPTR , const FBindingObject & Rhs) friend
Definition at line 200 of file BlueprintNodeBinder.h.
References FBindingObject(), Field, IsUObject(), and Object.
Field Documentation
bIsUObject
bool FBindingObject::bIsUObject private
Definition at line 20 of file BlueprintNodeBinder.h.
Referenced by FBindingObject(), FBindingObject(), FBindingObject(), FBindingObject(), Get(), GetFName(), GetFullName(), GetName(), GetPathName(), GetTypeHash, IsA(), IsA(), IsA(), IsUObject(), IsValid(), operator!=(), operator=(), operator=(), and operator==().
Field
FField* FBindingObject::Field private
Definition at line 19 of file BlueprintNodeBinder.h.
Referenced by FBindingObject(), FBindingObject(), Get(), GetFName(), GetFullName(), GetName(), GetPathName(), GetTypeHash, IsA(), IsA(), IsValid(), operator!=, operator!=, operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==, operator==, operator==(), operator==, and operator==.
Object
TObjectPtr<UObject> FBindingObject::Object private
Definition at line 18 of file BlueprintNodeBinder.h.
Referenced by FBindingObject(), FBindingObject(), Get(), GetFName(), GetFullName(), GetName(), GetPathName(), GetTypeHash, IsA(), IsA(), IsValid(), operator!=, operator!=, operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==, operator==, operator==(), operator==, and operator==.
The documentation for this class was generated from the following file:
BlueprintNodeBinder.h