Unreal Engine 5.6 C++ API: IMovieSceneTracksModule Class Reference
IMovieSceneTracksModule Class Reference
The public interface of the MovieSceneTracks module.
#include "IMovieSceneTracksModule.h"
Static Public Member Functions
static IMovieSceneTracksModule & Get ()
Singleton-like access to IMovieSceneTracksModule.
static MOVIESCENETRACKS_API FName GetEvaluationGroupName (EBuiltInEvaluationGroup::Type InEvalGroup)
Retrieve the name of an evaluation group.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Additional Inherited Members
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Detailed Description
The public interface of the MovieSceneTracks module.
Definition at line 23 of file IMovieSceneTracksModule.h.
Member Function Documentation
Get()
IMovieSceneTracksModule & IMovieSceneTracksModule::Get () inline static
Singleton-like access to IMovieSceneTracksModule.
Returns
Returns MovieSceneTracksModule singleton instance, loading the module on demand if needed
Definition at line 33 of file IMovieSceneTracksModule.h.
References FModuleManager::LoadModuleChecked().
GetEvaluationGroupName()
MOVIESCENETRACKS_API FName IMovieSceneTracksModule::GetEvaluationGroupName (EBuiltInEvaluationGroup::Type InEvalGroup) static
Retrieve the name of an evaluation group.
IsAvailable()
bool IMovieSceneTracksModule::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 43 of file IMovieSceneTracksModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
The documentation for this class was generated from the following file:
IMovieSceneTracksModule.h