Unreal Engine 5.6 C++ API: FStaticMeshInstanceData Class Reference
FStaticMeshInstanceData Class Reference
The implementation of the static mesh instance data storage type.
#include "StaticMeshResources.h"
Data Structures
struct FInstanceLightMapVector
struct FInstanceTransformMatrix
Public Member Functions
FStaticMeshInstanceData ()
FStaticMeshInstanceData (bool bInUseHalfFloat)
Constructor.
~FStaticMeshInstanceData ()
void AllocateInstances (int32 InNumInstances, int32 InNumCustomDataFloats, EResizeBufferFlags BufferFlags, bool DestroyExistingInstances)
void ClearInstanceEditorData (int32 InstanceIndex)
FResourceArrayInterface * GetCustomDataResourceArray ()
uint32 GetCustomDataStride ()
void GetInstanceCustomDataValues (int32 InstanceIndex, TArrayView< float > OutCustomData) const
void GetInstanceEditorData (int32 InstanceIndex, FColor &HitProxyColorOut, bool &bSelectedOut) const
void GetInstanceLightMapData (int32 InstanceIndex, FVector4f &InstanceLightmapAndShadowMapUVBias) const
void GetInstanceRandomID (int32 InstanceIndex, float &RandomInstanceID) const
void GetInstanceTransform (int32 InstanceIndex, FRenderTransform &Transform) const
FResourceArrayInterface * GetLightMapResourceArray ()
uint32 GetLightMapStride ()
int32 GetNumCustomDataFloats () const
int32 GetNumInstances () const
FResourceArrayInterface * GetOriginResourceArray ()
uint32 GetOriginStride ()
SIZE_T GetResourceSize () const
FResourceArrayInterface * GetTransformResourceArray ()
uint32 GetTransformStride ()
bool GetTranslationUsesHalfs () const
int32 IsValidIndex (int32 Index) const
void NullifyInstance (int32 InstanceIndex)
void Serialize (FArchive &Ar)
void SetAllowCPUAccess (bool InNeedsCPUAccess)
void SetInstance (int32 InstanceIndex, const FMatrix44f &Transform)
void SetInstance (int32 InstanceIndex, const FMatrix44f &Transform, const FVector2D &LightmapUVBias, const FVector2D &ShadowmapUVBias)
void SetInstance (int32 InstanceIndex, const FMatrix44f &Transform, float RandomInstanceID)
void SetInstance (int32 InstanceIndex, const FMatrix44f &Transform, float RandomInstanceID, const FVector2D &LightmapUVBias, const FVector2D &ShadowmapUVBias)
void SetInstanceCustomData (int32 InstanceIndex, int32 Index, float CustomData)
void SetInstanceEditorData (int32 InstanceIndex, FColor HitProxyColor, bool bSelected)
void SetInstanceLightMapData (int32 InstanceIndex, const FVector2D &LightmapUVBias, const FVector2D &ShadowmapUVBias)
void SwapInstance (int32 Index1, int32 Index2)
Private Member Functions
void AllocateBuffers (int32 InNumInstances, EResizeBufferFlags BufferFlags=EResizeBufferFlags::None)
void GetInstanceCustomDataInternal (int32 InstanceIndex, TArrayView< float > OutCustomData) const
void GetInstanceLightMapDataInternal (int32 InstanceIndex, FVector4f &LightmapData) const
void GetInstanceOriginInternal (int32 InstanceIndex, FVector4f &Origin) const
template<typename T>
void GetInstanceTransformInternal (int32 InstanceIndex, FVector4f(&Transform)[3]) const
void SetInstanceCustomDataInternal (int32 InstanceIndex, int32 DataIndex, float CustomData)
void SetInstanceLightMapDataInternal (int32 InstanceIndex, const FVector4f &LightmapData) const
void SetInstanceOriginInternal (int32 InstanceIndex, const FVector4f &Origin) const
template<typename T>
void SetInstanceTransformInternal (int32 InstanceIndex, FVector4f(Transform)[3]) const
Private Attributes
bool bUseHalfFloat = false
FStaticMeshVertexDataInterface * InstanceCustomData = nullptr
uint8 * InstanceCustomDataPtr = nullptr
FStaticMeshVertexDataInterface * InstanceLightmapData = nullptr
uint8 * InstanceLightmapDataPtr = nullptr
FStaticMeshVertexDataInterface * InstanceOriginData = nullptr
uint8 * InstanceOriginDataPtr = nullptr
FStaticMeshVertexDataInterface * InstanceTransformData = nullptr
uint8 * InstanceTransformDataPtr = nullptr
int32 NumCustomDataFloats = 0
int32 NumInstances = 0
Detailed Description
The implementation of the static mesh instance data storage type.
Definition at line 1030 of file StaticMeshResources.h.
Constructor & Destructor Documentation
FStaticMeshInstanceData() [1/2]
FStaticMeshInstanceData::FStaticMeshInstanceData () inline
Definition at line 1075 of file StaticMeshResources.h.
FStaticMeshInstanceData() [2/2]
FStaticMeshInstanceData::FStaticMeshInstanceData (bool bInUseHalfFloat) inline
Constructor.
Parameters
bInUseHalfFloat - true if device has support for half float in vertex arrays
Definition at line 1083 of file StaticMeshResources.h.
References AllocateBuffers(), bUseHalfFloat, and PLATFORM_BUILTIN_VERTEX_HALF_FLOAT.
~FStaticMeshInstanceData()
FStaticMeshInstanceData::~FStaticMeshInstanceData () inline
Definition at line 1089 of file StaticMeshResources.h.
References InstanceCustomData, InstanceLightmapData, InstanceOriginData, and InstanceTransformData.
Member Function Documentation
AllocateBuffers()
void FStaticMeshInstanceData::AllocateBuffers (int32 InNumInstances, EResizeBufferFlags BufferFlags = EResizeBufferFlags::None) inline private
Definition at line 1641 of file StaticMeshResources.h.
References bUseHalfFloat, InstanceCustomData, InstanceLightmapData, InstanceLightmapDataPtr, InstanceOriginData, InstanceOriginDataPtr, InstanceTransformData, InstanceTransformDataPtr, None, and NumCustomDataFloats.
Referenced by FStaticMeshInstanceData().
AllocateInstances()
void FStaticMeshInstanceData::AllocateInstances (int32 InNumInstances, int32 InNumCustomDataFloats, EResizeBufferFlags BufferFlags, bool DestroyExistingInstances) inline
Definition at line 1099 of file StaticMeshResources.h.
References InstanceCustomData, InstanceCustomDataPtr, InstanceLightmapData, InstanceLightmapDataPtr, InstanceOriginData, InstanceOriginDataPtr, InstanceTransformData, InstanceTransformDataPtr, NumCustomDataFloats, and NumInstances.
ClearInstanceEditorData()
void FStaticMeshInstanceData::ClearInstanceEditorData (int32 InstanceIndex) inline
Definition at line 1298 of file StaticMeshResources.h.
References bUseHalfFloat, FORCEINLINE_DEBUGGABLE, GetInstanceTransformInternal(), and SetInstanceTransformInternal().
GetCustomDataResourceArray()
FResourceArrayInterface * FStaticMeshInstanceData::GetCustomDataResourceArray () inline
Definition at line 1443 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceCustomData.
GetCustomDataStride()
uint32 FStaticMeshInstanceData::GetCustomDataStride () inline
Definition at line 1463 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceCustomData.
GetInstanceCustomDataInternal()
void FStaticMeshInstanceData::GetInstanceCustomDataInternal (int32 InstanceIndex, TArrayView< float > OutCustomData) const inline private
Definition at line 1547 of file StaticMeshResources.h.
References check, ensure, FORCEINLINE_DEBUGGABLE, InstanceCustomData, InstanceCustomDataPtr, TArrayView< InElementType, InSizeType >::Num(), and NumCustomDataFloats.
Referenced by GetInstanceCustomDataValues().
GetInstanceCustomDataValues()
void FStaticMeshInstanceData::GetInstanceCustomDataValues (int32 InstanceIndex, TArrayView< float > OutCustomData) const inline
Definition at line 1186 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and GetInstanceCustomDataInternal().
GetInstanceEditorData()
void FStaticMeshInstanceData::GetInstanceEditorData (int32 InstanceIndex, FColor & HitProxyColorOut, bool & bSelectedOut) const inline
Definition at line 1162 of file StaticMeshResources.h.
References FColor::B, bUseHalfFloat, FORCEINLINE_DEBUGGABLE, FColor::G, GetInstanceTransformInternal(), and FColor::R.
GetInstanceLightMapData()
void FStaticMeshInstanceData::GetInstanceLightMapData (int32 InstanceIndex, FVector4f & InstanceLightmapAndShadowMapUVBias) const inline
Definition at line 1181 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and GetInstanceLightMapDataInternal().
GetInstanceLightMapDataInternal()
void FStaticMeshInstanceData::GetInstanceLightMapDataInternal (int32 InstanceIndex, FVector4f & LightmapData) const inline private
Definition at line 1525 of file StaticMeshResources.h.
References ensure, FORCEINLINE_DEBUGGABLE, InstanceLightmapData, and InstanceLightmapDataPtr.
Referenced by GetInstanceLightMapData().
GetInstanceOriginInternal()
void FStaticMeshInstanceData::GetInstanceOriginInternal (int32 InstanceIndex, FVector4f & Origin) const inline private
Definition at line 1509 of file StaticMeshResources.h.
References ensure, FORCEINLINE_DEBUGGABLE, InstanceOriginData, InstanceOriginDataPtr, and Origin.
Referenced by GetInstanceRandomID(), and GetInstanceTransform().
GetInstanceRandomID()
void FStaticMeshInstanceData::GetInstanceRandomID (int32 InstanceIndex, float & RandomInstanceID) const inline
Definition at line 1153 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, GetInstanceOriginInternal(), and Origin.
Referenced by SetInstance(), and SetInstance().
GetInstanceTransform()
void FStaticMeshInstanceData::GetInstanceTransform (int32 InstanceIndex, FRenderTransform & Transform) const inline
Definition at line 1132 of file StaticMeshResources.h.
References bUseHalfFloat, FORCEINLINE_DEBUGGABLE, GetInstanceOriginInternal(), GetInstanceTransformInternal(), Origin, Transform, X, Y, and Z.
GetInstanceTransformInternal()
template<typename T> void FStaticMeshInstanceData::GetInstanceTransformInternal (int32 InstanceIndex, FVector4f(&) Transform[3]) const inline private
Definition at line 1478 of file StaticMeshResources.h.
References ensure, FORCEINLINE_DEBUGGABLE, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform1, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform2, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform3, InstanceTransformData, InstanceTransformDataPtr, and Transform.
Referenced by ClearInstanceEditorData(), GetInstanceEditorData(), GetInstanceTransform(), and SetInstanceEditorData().
GetLightMapResourceArray()
FResourceArrayInterface * FStaticMeshInstanceData::GetLightMapResourceArray () inline
Definition at line 1438 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceLightmapData.
GetLightMapStride()
uint32 FStaticMeshInstanceData::GetLightMapStride () inline
Definition at line 1458 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceLightmapData.
GetNumCustomDataFloats()
int32 FStaticMeshInstanceData::GetNumCustomDataFloats () const inline
Definition at line 1398 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and NumCustomDataFloats.
GetNumInstances()
int32 FStaticMeshInstanceData::GetNumInstances () const inline
Definition at line 1393 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and NumInstances.
GetOriginResourceArray()
FResourceArrayInterface * FStaticMeshInstanceData::GetOriginResourceArray () inline
Definition at line 1428 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceOriginData.
GetOriginStride()
uint32 FStaticMeshInstanceData::GetOriginStride () inline
Definition at line 1448 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceOriginData.
GetResourceSize()
SIZE_T FStaticMeshInstanceData::GetResourceSize () const inline
Definition at line 1468 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, InstanceCustomData, InstanceLightmapData, InstanceOriginData, and InstanceTransformData.
GetTransformResourceArray()
FResourceArrayInterface * FStaticMeshInstanceData::GetTransformResourceArray () inline
Definition at line 1433 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceTransformData.
GetTransformStride()
uint32 FStaticMeshInstanceData::GetTransformStride () inline
Definition at line 1453 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceTransformData.
GetTranslationUsesHalfs()
bool FStaticMeshInstanceData::GetTranslationUsesHalfs () const inline
Definition at line 1423 of file StaticMeshResources.h.
References bUseHalfFloat, and FORCEINLINE_DEBUGGABLE.
IsValidIndex()
int32 FStaticMeshInstanceData::IsValidIndex (int32 Index) const inline
Definition at line 1127 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, and InstanceOriginData.
NullifyInstance()
void FStaticMeshInstanceData::NullifyInstance (int32 InstanceIndex) inline
Definition at line 1251 of file StaticMeshResources.h.
References bUseHalfFloat, FORCEINLINE_DEBUGGABLE, NumCustomDataFloats, SetInstanceCustomDataInternal(), SetInstanceLightMapDataInternal(), SetInstanceOriginInternal(), and SetInstanceTransformInternal().
Serialize()
void FStaticMeshInstanceData::Serialize (FArchive & Ar)
References Ar.
SetAllowCPUAccess()
void FStaticMeshInstanceData::SetAllowCPUAccess (bool InNeedsCPUAccess) inline
Definition at line 1403 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, InstanceCustomData, InstanceLightmapData, InstanceOriginData, and InstanceTransformData.
SetInstance() [1/4]
void FStaticMeshInstanceData::SetInstance (int32 InstanceIndex, const FMatrix44f & Transform) inline
Definition at line 1232 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, GetInstanceRandomID(), SetInstance(), Transform, and UE::Math::TVector2< double >::ZeroVector.
SetInstance() [2/4]
void FStaticMeshInstanceData::SetInstance (int32 InstanceIndex, const FMatrix44f & Transform, const FVector2D & LightmapUVBias, const FVector2D & ShadowmapUVBias) inline
Definition at line 1225 of file StaticMeshResources.h.
References FORCEINLINE, GetInstanceRandomID(), SetInstance(), and Transform.
SetInstance() [3/4]
void FStaticMeshInstanceData::SetInstance (int32 InstanceIndex, const FMatrix44f & Transform, float RandomInstanceID) inline
Definition at line 1218 of file StaticMeshResources.h.
References FORCEINLINE_DEBUGGABLE, SetInstance(), Transform, and UE::Math::TVector2< double >::ZeroVector.
SetInstance() [4/4]
void FStaticMeshInstanceData::SetInstance (int32 InstanceIndex, const FMatrix44f & Transform, float RandomInstanceID, const FVector2D & LightmapUVBias, const FVector2D & ShadowmapUVBias) inline
Definition at line 1191 of file StaticMeshResources.h.
References bUseHalfFloat, FORCEINLINE_DEBUGGABLE, NumCustomDataFloats, Origin, SetInstanceCustomDataInternal(), SetInstanceLightMapDataInternal(), SetInstanceOriginInternal(), SetInstanceTransformInternal(), Transform, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by SetInstance(), SetInstance(), and SetInstance().
SetInstanceCustomData()
void FStaticMeshInstanceData::SetInstanceCustomData (int32 InstanceIndex, int32 Index, float CustomData) inline
Definition at line 1246 of file StaticMeshResources.h.
References FORCEINLINE, and SetInstanceCustomDataInternal().
SetInstanceCustomDataInternal()
void FStaticMeshInstanceData::SetInstanceCustomDataInternal (int32 InstanceIndex, int32 DataIndex, float CustomData) inline private
Definition at line 1621 of file StaticMeshResources.h.
References ensure, FORCEINLINE_DEBUGGABLE, InstanceCustomData, InstanceCustomDataPtr, and NumCustomDataFloats.
Referenced by NullifyInstance(), SetInstance(), and SetInstanceCustomData().
SetInstanceEditorData()
void FStaticMeshInstanceData::SetInstanceEditorData (int32 InstanceIndex, FColor HitProxyColor, bool bSelected) inline
Definition at line 1277 of file StaticMeshResources.h.
References FColor::B, bUseHalfFloat, float, FORCEINLINE_DEBUGGABLE, FColor::G, GetInstanceTransformInternal(), FColor::R, and SetInstanceTransformInternal().
SetInstanceLightMapData()
void FStaticMeshInstanceData::SetInstanceLightMapData (int32 InstanceIndex, const FVector2D & LightmapUVBias, const FVector2D & ShadowmapUVBias) inline
Definition at line 1241 of file StaticMeshResources.h.
References FORCEINLINE, SetInstanceLightMapDataInternal(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
SetInstanceLightMapDataInternal()
void FStaticMeshInstanceData::SetInstanceLightMapDataInternal (int32 InstanceIndex, const FVector4f & LightmapData) const inline private
Definition at line 1604 of file StaticMeshResources.h.
References FMath::Clamp(), ensure, FORCEINLINE_DEBUGGABLE, FStaticMeshInstanceData::FInstanceLightMapVector::InstanceLightmapAndShadowMapUVBias, InstanceLightmapData, InstanceLightmapDataPtr, MAX_int16, MIN_int16, UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Referenced by NullifyInstance(), SetInstance(), and SetInstanceLightMapData().
SetInstanceOriginInternal()
void FStaticMeshInstanceData::SetInstanceOriginInternal (int32 InstanceIndex, const FVector4f & Origin) const inline private
Definition at line 1592 of file StaticMeshResources.h.
References ensureMsgf, FORCEINLINE_DEBUGGABLE, InstanceOriginData, InstanceOriginDataPtr, Origin, and TEXT.
Referenced by NullifyInstance(), and SetInstance().
SetInstanceTransformInternal()
template<typename T> void FStaticMeshInstanceData::SetInstanceTransformInternal (int32 InstanceIndex, FVector4f(Transform) [3]) const inline private
Definition at line 1567 of file StaticMeshResources.h.
References ensure, FORCEINLINE_DEBUGGABLE, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform1, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform2, FStaticMeshInstanceData::FInstanceTransformMatrix< F >::InstanceTransform3, InstanceTransformData, InstanceTransformDataPtr, and Transform.
Referenced by ClearInstanceEditorData(), NullifyInstance(), SetInstance(), and SetInstanceEditorData().
SwapInstance()
void FStaticMeshInstanceData::SwapInstance (int32 Index1, int32 Index2) inline
Definition at line 1319 of file StaticMeshResources.h.
References bUseHalfFloat, check, FORCEINLINE_DEBUGGABLE, InstanceCustomData, InstanceCustomDataPtr, InstanceLightmapData, InstanceLightmapDataPtr, InstanceOriginData, InstanceOriginDataPtr, InstanceTransformData, InstanceTransformDataPtr, and NumCustomDataFloats.
Field Documentation
bUseHalfFloat
bool FStaticMeshInstanceData::bUseHalfFloat = false private
Definition at line 1687 of file StaticMeshResources.h.
Referenced by FStaticMeshInstanceData(), AllocateBuffers(), ClearInstanceEditorData(), GetInstanceEditorData(), GetInstanceTransform(), GetTranslationUsesHalfs(), NullifyInstance(), SetInstance(), SetInstanceEditorData(), and SwapInstance().
InstanceCustomData
FStaticMeshVertexDataInterface* FStaticMeshInstanceData::InstanceCustomData = nullptr private
Definition at line 1682 of file StaticMeshResources.h.
Referenced by ~FStaticMeshInstanceData(), AllocateBuffers(), AllocateInstances(), GetCustomDataResourceArray(), GetCustomDataStride(), GetInstanceCustomDataInternal(), GetResourceSize(), SetAllowCPUAccess(), SetInstanceCustomDataInternal(), and SwapInstance().
InstanceCustomDataPtr
uint8* FStaticMeshInstanceData::InstanceCustomDataPtr = nullptr private
Definition at line 1683 of file StaticMeshResources.h.
Referenced by AllocateInstances(), GetInstanceCustomDataInternal(), SetInstanceCustomDataInternal(), and SwapInstance().
InstanceLightmapData
FStaticMeshVertexDataInterface* FStaticMeshInstanceData::InstanceLightmapData = nullptr private
Definition at line 1679 of file StaticMeshResources.h.
Referenced by ~FStaticMeshInstanceData(), AllocateBuffers(), AllocateInstances(), GetInstanceLightMapDataInternal(), GetLightMapResourceArray(), GetLightMapStride(), GetResourceSize(), SetAllowCPUAccess(), SetInstanceLightMapDataInternal(), and SwapInstance().
InstanceLightmapDataPtr
uint8* FStaticMeshInstanceData::InstanceLightmapDataPtr = nullptr private
Definition at line 1680 of file StaticMeshResources.h.
Referenced by AllocateBuffers(), AllocateInstances(), GetInstanceLightMapDataInternal(), SetInstanceLightMapDataInternal(), and SwapInstance().
InstanceOriginData
FStaticMeshVertexDataInterface* FStaticMeshInstanceData::InstanceOriginData = nullptr private
Definition at line 1673 of file StaticMeshResources.h.
Referenced by ~FStaticMeshInstanceData(), AllocateBuffers(), AllocateInstances(), GetInstanceOriginInternal(), GetOriginResourceArray(), GetOriginStride(), GetResourceSize(), IsValidIndex(), SetAllowCPUAccess(), SetInstanceOriginInternal(), and SwapInstance().
InstanceOriginDataPtr
uint8* FStaticMeshInstanceData::InstanceOriginDataPtr = nullptr private
Definition at line 1674 of file StaticMeshResources.h.
Referenced by AllocateBuffers(), AllocateInstances(), GetInstanceOriginInternal(), SetInstanceOriginInternal(), and SwapInstance().
InstanceTransformData
FStaticMeshVertexDataInterface* FStaticMeshInstanceData::InstanceTransformData = nullptr private
Definition at line 1676 of file StaticMeshResources.h.
Referenced by ~FStaticMeshInstanceData(), AllocateBuffers(), AllocateInstances(), GetInstanceTransformInternal(), GetResourceSize(), GetTransformResourceArray(), GetTransformStride(), SetAllowCPUAccess(), SetInstanceTransformInternal(), and SwapInstance().
InstanceTransformDataPtr
uint8* FStaticMeshInstanceData::InstanceTransformDataPtr = nullptr private
Definition at line 1677 of file StaticMeshResources.h.
Referenced by AllocateBuffers(), AllocateInstances(), GetInstanceTransformInternal(), SetInstanceTransformInternal(), and SwapInstance().
NumCustomDataFloats
int32 FStaticMeshInstanceData::NumCustomDataFloats = 0 private
Definition at line 1686 of file StaticMeshResources.h.
Referenced by AllocateBuffers(), AllocateInstances(), GetInstanceCustomDataInternal(), GetNumCustomDataFloats(), NullifyInstance(), SetInstance(), SetInstanceCustomDataInternal(), and SwapInstance().
NumInstances
int32 FStaticMeshInstanceData::NumInstances = 0 private
Definition at line 1685 of file StaticMeshResources.h.
Referenced by AllocateInstances(), and GetNumInstances().
The documentation for this class was generated from the following file:
StaticMeshResources.h