Unreal Engine 5.6 C++ API: FComposableVectorDistribution Class Reference
FComposableVectorDistribution Class Reference
#include "Distributions.h"
Public Member Functions
FComposableVectorDistribution ()
Default constructor.
FComposableVectorDistribution (const FComposableVectorDistribution &Other)
Copy constructor.
void AddConstantVector (const FVector &Value)
Adds a constant vector to each sample in the distribution.
void AddDistribution (const class UDistributionVector *VectorDistribution)
Adds each sample in the distribution to the corresponding sample in another distribution.
void Initialize (const class UDistributionVector *VectorDistribution)
Initializes this distribution from that specified.
void InitializeWithConstant (const FVector &Value)
Initializes this distribution with a constant value.
const FComposableVectorDistribution & operator= (const FComposableVectorDistribution &Other)
Assignment operator.
void Resample (float MinIn, float MaxIn)
Resamples the distribution to include only information from [MinIn,MaxIn].
void ScaleByConstant (float Scale)
Scales each sample in the distribution by a constant.
void ScaleByConstantVector (const FVector &Scale)
Scales each sample in the distribution by a constant vector.
void ScaleByDistribution (const class UDistributionFloat *FloatDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
void ScaleByVectorDistribution (const class UDistributionVector *VectorDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
void Splat (int32 ChannelIndex)
Splats the specified channel to all channels in the distribution.
Additional Inherited Members
Static Public Member Functions inherited from FComposableDistribution
static void BuildFloat (class FFloatDistribution &OutDistribution, const class FComposableFloatDistribution &X)
Constructs a type-safe floating point distribution.
static void BuildVector (class FVectorDistribution &OutDistribution, const class FComposableVectorDistribution &XYZ)
Constructs a type-safe vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableFloatDistribution &X, const class FComposableFloatDistribution &Y, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XY, const class FComposableFloatDistribution &Z, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void BuildVector4 (class FVector4Distribution &OutDistribution, const class FComposableVectorDistribution &XYZ, const class FComposableFloatDistribution &W)
Constructs a type-safe 4-vector distribution.
static void QuantizeVector4 (TArray< FColor > &OutQuantizedSamples, FVector4 &OutScale, FVector4 &OutBias, const class FVector4Distribution &Distribution)
Quantizes a 4-component vector distribution.
Protected Member Functions inherited from FComposableDistribution
FComposableDistribution ()
Constructor.
FComposableDistribution (const FComposableDistribution &Other)
Copy constructor.
~FComposableDistribution ()
Destructor.
const FComposableDistribution & operator= (const FComposableDistribution &Other)
Assignment operator.
Protected Attributes inherited from FComposableDistribution
FDistributionLookupTable LookupTable
The lookup table.
Detailed Description
Definition at line 665 of file Distributions.h.
Constructor & Destructor Documentation
FComposableVectorDistribution() [1/2]
FComposableVectorDistribution::FComposableVectorDistribution ()
Default constructor.
Referenced by FComposableVectorDistribution(), and operator=().
FComposableVectorDistribution() [2/2]
FComposableVectorDistribution::FComposableVectorDistribution (const FComposableVectorDistribution & Other) inline
Copy constructor.
Definition at line 672 of file Distributions.h.
References FComposableDistribution::FComposableDistribution(), FComposableVectorDistribution(), and Other.
Member Function Documentation
AddConstantVector()
void FComposableVectorDistribution::AddConstantVector (const FVector & Value)
Adds a constant vector to each sample in the distribution.
References FVector, and Value.
AddDistribution()
void FComposableVectorDistribution::AddDistribution (const class UDistributionVector * VectorDistribution)
Adds each sample in the distribution to the corresponding sample in another distribution.
Initialize()
void FComposableVectorDistribution::Initialize (const class UDistributionVector * VectorDistribution)
Initializes this distribution from that specified.
InitializeWithConstant()
void FComposableVectorDistribution::InitializeWithConstant (const FVector & Value)
Initializes this distribution with a constant value.
References FVector, and Value.
operator=()
const FComposableVectorDistribution & FComposableVectorDistribution::operator= (const FComposableVectorDistribution & Other) inline
Assignment operator.
Definition at line 678 of file Distributions.h.
References FComposableVectorDistribution(), FComposableDistribution::operator=(), and Other.
Resample()
void FComposableVectorDistribution::Resample (float MinIn, float MaxIn)
Resamples the distribution to include only information from [MinIn,MaxIn].
ScaleByConstant()
void FComposableVectorDistribution::ScaleByConstant (float Scale)
Scales each sample in the distribution by a constant.
References Scale.
ScaleByConstantVector()
void FComposableVectorDistribution::ScaleByConstantVector (const FVector & Scale)
Scales each sample in the distribution by a constant vector.
References FVector, and Scale.
ScaleByDistribution()
void FComposableVectorDistribution::ScaleByDistribution (const class UDistributionFloat * FloatDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
ScaleByVectorDistribution()
void FComposableVectorDistribution::ScaleByVectorDistribution (const class UDistributionVector * VectorDistribution)
Scale each sample in the distribution by the corresponding sample in another distribution.
Splat()
void FComposableVectorDistribution::Splat (int32 ChannelIndex)
Splats the specified channel to all channels in the distribution.
The documentation for this class was generated from the following file:
Distributions.h