Unreal Engine 5.6 C++ API: FLayoutBlockTextContext Struct Reference
FLayoutBlockTextContext Struct Reference
The context needed when creating a block from a run of a text.
#include "IRun.h"
Public Member Functions
FLayoutBlockTextContext (const FRunTextContext &InRunTextContext, const TextBiDi::ETextDirection InTextDirection)
FORCEINLINE bool operator!= (const FLayoutBlockTextContext &Other) const
FORCEINLINE bool operator== (const FLayoutBlockTextContext &Other) const
Public Member Functions inherited from FRunTextContext
FRunTextContext (const ETextShapingMethod InTextShapingMethod, const TextBiDi::ETextDirection InBaseDirection, FShapedTextCacheRef InShapedTextCache)
Public Member Functions inherited from FShapedTextContext
FShapedTextContext (const ETextShapingMethod InTextShapingMethod, const TextBiDi::ETextDirection InBaseDirection)
FORCEINLINE bool operator!= (const FShapedTextContext &Other) const
FORCEINLINE bool operator== (const FShapedTextContext &Other) const
Data Fields
TextBiDi::ETextDirection TextDirection
The reading direction of the text contained within this block.
Data Fields inherited from FRunTextContext
FShapedTextCacheRef ShapedTextCache
The shaped text cache that should be used by this line of text.
Data Fields inherited from FShapedTextContext
TextBiDi::ETextDirection BaseDirection
The base direction of the current line of text.
ETextShapingMethod TextShapingMethod
The method used to shape the text within this layout.
Friends
uint32 GetTypeHash (const FLayoutBlockTextContext &Key)
Detailed Description
The context needed when creating a block from a run of a text.
Definition at line 97 of file IRun.h.
Constructor & Destructor Documentation
FLayoutBlockTextContext()
FLayoutBlockTextContext::FLayoutBlockTextContext (const FRunTextContext & InRunTextContext, const TextBiDi::ETextDirection InTextDirection) inline
Definition at line 99 of file IRun.h.
References FRunTextContext::FRunTextContext(), and TextDirection.
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
FORCEINLINE bool FLayoutBlockTextContext::operator!= (const FLayoutBlockTextContext & Other) const inline
Definition at line 111 of file IRun.h.
References FLayoutBlockTextContext(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FLayoutBlockTextContext::operator== (const FLayoutBlockTextContext & Other) const inline
Definition at line 105 of file IRun.h.
References FLayoutBlockTextContext(), FORCEINLINE, FShapedTextContext::operator==(), Other, and TextDirection.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FLayoutBlockTextContext & Key) friend
Definition at line 116 of file IRun.h.
References FLayoutBlockTextContext(), FRunTextContext::FRunTextContext(), GetTypeHash, HashCombine(), and Key.
Referenced by GetTypeHash.
Field Documentation
TextDirection
TextBiDi::ETextDirection FLayoutBlockTextContext::TextDirection
The reading direction of the text contained within this block.
Definition at line 124 of file IRun.h.
Referenced by FLayoutBlockTextContext(), and operator==().
The documentation for this struct was generated from the following file:
IRun.h