Unreal Engine 5.6 C++ API: SampledSequenceDrawingUtils Namespace Reference
SampledSequenceDrawingUtils Namespace Reference
Data Structures
struct F2DLineCoordinates
struct FDimensionSlot
Represents a dimensional slot in which samples, sample bins or a grid can be drawn.
struct FGridData
DrawCoordinates: Coordinates of different grid lines PositionRatios: the Ratio of each grid line position in relationship to the main axis length.
struct FSampledSequenceDrawingParams
Enumerations
enum class ESampledSequenceDrawOrientation { Horizontal = 0 , Vertical , COUNT }
Params for drawing sequences of samples/sample bins.
Functions
void GenerateEvenlySplitGridForGeometry (TArray< FGridData > &OutGridData, const FGeometry &InAllottedGeometry, const uint16 NDimensions, const uint32 NumGridDivisions, const FSampledSequenceDrawingParams Params=FSampledSequenceDrawingParams())
Generates an evenly divided grid from a given geometry, following the orientation provided in the Params struct argument.
void AUDIOWIDGETS_API GenerateEvenlySplitGridForLine (TArray< double > &OutDrawCoordinates, TArray< float > &OutLinePositionRatios, const float LineLength, const uint32 NumGridDivisions, bool bEmptyOutArrays=true)
void GenerateMidpointSplitGridForGeometry (TArray< FGridData > &OutGridData, const FGeometry &InAllottedGeometry, const uint16 NDimensions, const uint32 DivisionDepth=3, const FSampledSequenceDrawingParams Params=FSampledSequenceDrawingParams())
Generates a midline divided grid from a given geometry, following the orientation provided in the Params struct argument.
void AUDIOWIDGETS_API GenerateMidpointSplitGridForLine (TArray< double > &OutDrawCoordinates, TArray< float > &OutLinePositionRatios, const float LineLength, const uint32 DivisionDepth=3, bool bEmptyOutArrays=true)
void GenerateSampleBinsCoordinatesForGeometry (TArray< F2DLineCoordinates > &OutDrawCoordinates, const FGeometry &InAllottedGeometry, const TArray< TRange< float > > &InSampleBins, const uint16 NDimensions, const FSampledSequenceDrawingParams Params=FSampledSequenceDrawingParams())
Generates an array of coordinates to draw binned samples as vertical lines.
void GenerateSequencedSamplesCoordinatesForGeometry (TArray< FVector2D > &OutDrawCoordinates, TArrayView< const float > InSampleData, const FGeometry &InAllottedGeometry, const uint16 NDimensions, const FFixedSampledSequenceGridMetrics InGridMetrics, const FSampledSequenceDrawingParams Params=FSampledSequenceDrawingParams())
Generates an array of coordinates to draw single samples in succession horizontally.
template<typename SamplesType>
void GroupInterleavedSampledTSIntoMinMaxBins (TArray< TRange< SamplesType > > &OutBins, const uint32 NumDesiredBins, const SamplesType *RawDataPtr, const uint32 TotalNumSamples, const uint32 SampleRate, const uint16 NDimensions=1, const float StartTime=0.f, float EndTime=-1.f)
Groups samples of a time series into an equal number of desired bins.
template<typename SamplesType>
void GroupInterleavedSamplesIntoMinMaxBins (TArray< TRange< SamplesType > > &OutBins, const uint32 NumDesiredBins, const SamplesType *RawDataPtr, const uint32 TotalNumSamples, const uint16 NDimensions=1, const double StartRatio=0.0, double EndRatio=1.0)
Groups samples evenly into a number of desired bins.
Enumeration Type Documentation
ESampledSequenceDrawOrientation
enum class SampledSequenceDrawingUtils::ESampledSequenceDrawOrientation strong
Params for drawing sequences of samples/sample bins.
Parameters
MaxDisplayedValue The highest value a sample can take
DimensionSlotMargin Margin to keep from the dimension slot boundaries (pixels)
MinSequenceHeightRatio The minimum height (ratio) the drawn sequence can take in a channel slot
MaxSequenceHeightRatio The maximum height (ratio) the drawn sequence can take in a channel slot
MinScaledBinValue Minimum value (in pixels) a bin can have
VerticalZoomFactor Sequence zoom factor
Enumerator
Horizontal
Vertical
COUNT
Definition at line 108 of file SampledSequenceDrawingUtils.h.
Function Documentation
GenerateEvenlySplitGridForGeometry()
void SampledSequenceDrawingUtils::GenerateEvenlySplitGridForGeometry (TArray< FGridData > & OutGridData, const FGeometry & InAllottedGeometry, const uint16 NDimensions, const uint32 NumGridDivisions, const FSampledSequenceDrawingParams Params = FSampledSequenceDrawingParams())
Generates an evenly divided grid from a given geometry, following the orientation provided in the Params struct argument.
Parameters
OutGridData The generated grid coordinates and ratios per each dimension
InAllottedGeometry The geometry the grid will be drawn into
NDimensions Dimensions to account for in the given geometry
NumGridDivisions Number of divisions the grid should be split into
Params Drawing Params
References Params.
GenerateEvenlySplitGridForLine()
void AUDIOWIDGETS_API SampledSequenceDrawingUtils::GenerateEvenlySplitGridForLine (TArray< double > & OutDrawCoordinates, TArray< float > & OutLinePositionRatios, const float LineLength, const uint32 NumGridDivisions, bool bEmptyOutArrays = true)
GenerateMidpointSplitGridForGeometry()
void SampledSequenceDrawingUtils::GenerateMidpointSplitGridForGeometry (TArray< FGridData > & OutGridData, const FGeometry & InAllottedGeometry, const uint16 NDimensions, const uint32 DivisionDepth = 3, const FSampledSequenceDrawingParams Params = FSampledSequenceDrawingParams())
Generates a midline divided grid from a given geometry, following the orientation provided in the Params struct argument.
The grid space will be divided in half, with the resulting halves being divided again and so on until the desired Division Depth is reached.
Parameters
OutGridData The generated grid coordinates and ratios per each dimension
InAllottedGeometry The geometry the grid will be drawn into
NDimensions Dimensions to account for in the given geometry
DivisionDepth Number of divisions that should be run
Params Drawing Params
References Params.
GenerateMidpointSplitGridForLine()
void AUDIOWIDGETS_API SampledSequenceDrawingUtils::GenerateMidpointSplitGridForLine (TArray< double > & OutDrawCoordinates, TArray< float > & OutLinePositionRatios, const float LineLength, const uint32 DivisionDepth = 3, bool bEmptyOutArrays = true)
GenerateSampleBinsCoordinatesForGeometry()
void SampledSequenceDrawingUtils::GenerateSampleBinsCoordinatesForGeometry (TArray< F2DLineCoordinates > & OutDrawCoordinates, const FGeometry & InAllottedGeometry, const TArray< TRange< float > > & InSampleBins, const uint16 NDimensions, const FSampledSequenceDrawingParams Params = FSampledSequenceDrawingParams())
Generates an array of coordinates to draw binned samples as vertical lines.
Coordinates will be generated for an horizontal view
Parameters
OutDrawCoordinates The generated coordinates
InAllottedGeometry The geometry to draw into
InSampleBins The bins to draw
NDimensions Number of interleaved dimensions in the time series
Params Drawing Params
References Params.
GenerateSequencedSamplesCoordinatesForGeometry()
void SampledSequenceDrawingUtils::GenerateSequencedSamplesCoordinatesForGeometry (TArray< FVector2D > & OutDrawCoordinates, TArrayView< const float > InSampleData, const FGeometry & InAllottedGeometry, const uint16 NDimensions, const FFixedSampledSequenceGridMetrics InGridMetrics, const FSampledSequenceDrawingParams Params = FSampledSequenceDrawingParams())
Generates an array of coordinates to draw single samples in succession horizontally.
Parameters
OutDrawCoordinates The generated coordinates
InSampleData The samples to draw
InAllottedGeometry The geometry to draw into
NDimensions Number of interleaved dimensions in the time series
InGridMetrics GridMetrics followed to lay down the samples
Params Drawing Params
References Params.
GroupInterleavedSampledTSIntoMinMaxBins()
template<typename SamplesType> void SampledSequenceDrawingUtils::GroupInterleavedSampledTSIntoMinMaxBins (TArray< TRange< SamplesType > > & OutBins, const uint32 NumDesiredBins, const SamplesType * RawDataPtr, const uint32 TotalNumSamples, const uint32 SampleRate, const uint16 NDimensions = 1, const float StartTime = 0.f, float EndTime = -1.f)
Groups samples of a time series into an equal number of desired bins.
Each bin contains the min and max values of the grouped samples.
Parameters
OutBins TArray where the bins will be written to
NumDesiredBins Number of output bins
RawDataPtr Ptr to the beginning of the samples
TotalNumSamples The total number of samples of the input time series
SampleRate SampleRate of the time series
NDimensions Number of interleaved dimensions in the time series
StartTime The time at which grouping should start
EndTime The time at which grouping should end.
Note: With a negative EndTime, the method will calculate automatically the EndTime by doing TotalNumSamples / (SampleRate * NDimensions)
Definition at line 89 of file SampledSequenceDrawingUtils.h.
References FMath::Clamp(), float, and GroupInterleavedSamplesIntoMinMaxBins().
GroupInterleavedSamplesIntoMinMaxBins()
template<typename SamplesType> void SampledSequenceDrawingUtils::GroupInterleavedSamplesIntoMinMaxBins (TArray< TRange< SamplesType > > & OutBins, const uint32 NumDesiredBins, const SamplesType * RawDataPtr, const uint32 TotalNumSamples, const uint16 NDimensions = 1, const double StartRatio = 0.0, double EndRatio = 1.0)
Groups samples evenly into a number of desired bins.
Each bin contains the min and max values of the grouped samples.
Parameters
OutBins TArray where the bins will be written to
NumDesiredBins Number of output bins
RawDataPtr Ptr to the beginning of the samples
TotalNumSamples The total number of samples of the input time series
NDimensions Number of interleaved dimensions in the time series
StartRatio The ratio of the total number of frames (in a range of 0-1) at which grouping should start
EndRatio The ratio of the total number of frames (in a range of 0-1) at which grouping should end.
Definition at line 29 of file SampledSequenceDrawingUtils.h.
References check, FMath::Max, FMath::Min, and NumFrames.
Referenced by GroupInterleavedSampledTSIntoMinMaxBins().