Unreal Engine 5.6 C++ API: UE::Geometry::FMeshPlaneCut Class Reference
UE::Geometry::FMeshPlaneCut Class Reference
Cut the Mesh with the Plane.
#include "MeshPlaneCut.h"
Data Structures
struct FCutResultRegion
struct FOpenBoundary
Public Member Functions
FMeshPlaneCut (FDynamicMesh3 *Mesh, FVector3d Origin, FVector3d Normal)
Cut mesh with plane.
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS ~FMeshPlaneCut ()
virtual DYNAMICMESH_API bool Cut ()
Compute the plane cut by splitting mesh edges that cross the cut plane, and then deleting any triangles on the positive side of the cutting plane.
virtual DYNAMICMESH_API bool CutWithoutDelete (bool bSplitVerticesAtPlane, float OffsetSeparatedPortion=0.0f, TDynamicMeshScalarTriangleAttribute< int > *TriLabels=nullptr, int NewLabelStartID=0, bool bAddBoundariesFirstHalf=true, bool bAddBoundariesSecondHalf=true)
Compute the plane cut by splitting mesh edges that cross the cut plane, but not deleting triangles on positive side.
virtual DYNAMICMESH_API bool HoleFill (TFunction< TArray< FIndex3i >(const FGeneralPolygon2d &)> PlanarTriangulationFunc, bool bFillSpans, int ConstantGroupID=-1, int MaterialID=-1)
Fill cut loops with FPlanarHoleFiller, using a caller-provided triangulation function.
virtual DYNAMICMESH_API bool MinimalHoleFill (int ConstantGroupID=-1)
virtual DYNAMICMESH_API bool SimpleHoleFill (int ConstantGroupID=-1)
Fill cut loops with FSimpleHoleFiller.
virtual bool SplitEdgesOnly (bool bAssignNewGroups, TSet< int32 > *OptionalTriangleSelection)
Compute the plane cut by splitting mesh edges that cross the cut plane, and then optionally update groups.
virtual DYNAMICMESH_API void TransferTriangleLabelsToHoleFillTriangles (TDynamicMeshScalarTriangleAttribute< int > *TriLabels)
UE_DEPRECATED (5.3, "Instead use the two-parameter version of SplitEdgesOnly, which has direction selection tracking and does not populate the deprecated ResultSeedTriangles") virtual bool SplitEdgesOnly(bool bAssignNewGroups)
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.3, "To preserve a triangle selection when using SplitEdgesOnly(), instead pass the selection as a pointer to that function.") TArray< int32 > ResultSeedTriangles
List of output cut triangles representing the seed triangles along the cut.
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS EOperationValidationResult Validate ()
Public Member Functions inherited from UE::Geometry::FMeshPlaneCutFixLayout
virtual ~FMeshPlaneCutFixLayout ()=default
Data Fields
bool bCollapseDegenerateEdgesOnCut = true
bool bSimplifyAlongNewEdges = false
Control whether we attempt to auto-simplify the small planar triangles that the plane cut operation tends to generate.
double DegenerateEdgeTol = FMathd::ZeroTolerance
TUniqueFunction< bool(int32)> EdgeFilterFunc = nullptr
If set, only edges that pass this filter will be split.
TArray< TArray< int > > HoleFillTriangles
FDynamicMesh3 * Mesh
TArray< FOpenBoundary > OpenBoundaries
FVector3d PlaneNormal
FVector3d PlaneOrigin
double PlaneTolerance = FMathf::ZeroTolerance * 10.0
Tolerance distance for considering a vertex to be 'on plane'.
TArray< FCutResultRegion > ResultRegions
List of output cut regions (eg that have separate GroupIDs).
FLocalPlanarSimplify SimplifySettings
Settings to apply if bSimplifyAlongNewEdges == true.
float UVScaleFactor = 1.0f
UVs on any hole fill surfaces are scaled by this amount.
Protected Member Functions
DYNAMICMESH_API void CollapseDegenerateEdges (TSet< int > &Edges, bool bRemoveAllDegenerateFromInputSet, TSet< int > *TriangleSelection=nullptr)
Collapse degenerate edges.
DYNAMICMESH_API bool ExtractBoundaryLoops (const TSet< int > &OnCutEdges, const TSet< int > &ZeroEdges, FMeshPlaneCut::FOpenBoundary &Boundary)
DYNAMICMESH_API void SplitCrossingEdges (bool bDeleteTrisOnPlane, TArray< double > &Signs, TSet< int > &AlreadyOnPlaneEdges, TSet< int32 > &CutPlaneEdges, TSet< int > *SplitEdges=nullptr, TSet< int > *OnPlaneVertices=nullptr, TSet< int > *TriangleSelection=nullptr)
DYNAMICMESH_API void SplitCrossingEdges (TArray< double > &Signs, TSet< int > &ZeroEdges, TSet< int > &OnCutEdges, bool bDeleteTrisOnPlane=true)
DYNAMICMESH_API void SplitCrossingEdges (TArray< double > &Signs, TSet< int > &ZeroEdges, TSet< int > &OnCutEdges, TSet< int > &OnSplitEdges, bool bDeleteTrisOnPlane=true)
UE_DEPRECATED (5.3, "If needed, explicitly request the vertices on the cut plane the the OnPlaneVertices argument of SplitCrossingEdges") TSet< int32 > OnCutVertices
UE_DEPRECATED (5.3, "Use the single-set CollapseDegenerateEdges instead") DYNAMICMESH_API void CollapseDegenerateEdges(const TSet< int > &OnCutEdges
Protected Attributes
const TSet< int > & ZeroEdges
Private Member Functions
DYNAMICMESH_API void ComputeVertexSignedDistances (TArray< double > &Signs, double InvalidDist)
DYNAMICMESH_API bool SplitEdgesOnlyHelper (bool bAssignNewGroups, TSet< int32 > *OptionalTriangleSelection, bool bAddDeprecatedResultSeedTriangles)
Detailed Description
Cut the Mesh with the Plane.
The positive side, ie (p-o).n > 0, is removed. If possible, returns boundary loop(s) along cut (this will fail if cut intersected with holes in mesh). Also FillHoles() for a topological fill. Or use CutLoops and fill yourself.
Algorithm is: 1) find all edge crossings 2) optionally discard any triangles with all vertex distances < epsilon. 3) Do edge splits at crossings 4 option a) (optionally) delete all vertices on positive side 4 option b) (OR optionally) disconnect all triangles w/ vertices on positive side (if keeping both sides) 4 option c) do nothing (if keeping both sides and not disconnecting them) 5) (optionally) collapse any degenerate boundary edges 6) (optionally) change an attribute tag for all triangles on positive side 7) find loops through valid boundary edges (ie connected to splits, or on-plane edges) (if second half was kept, do this separately for each separate mesh ID label)
Definition at line 50 of file MeshPlaneCut.h.
Constructor & Destructor Documentation
FMeshPlaneCut()
UE::Geometry::FMeshPlaneCut::FMeshPlaneCut (FDynamicMesh3 * Mesh, FVector3d Origin, FVector3d Normal) inline
Cut mesh with plane.
Assumption is that plane normal is Z value.
Definition at line 124 of file MeshPlaneCut.h.
References FMeshPlaneCut(), Mesh, UE::Geometry::Normal, UE::Geometry::Origin, PlaneNormal, and PlaneOrigin.
Referenced by FMeshPlaneCut(), and ExtractBoundaryLoops().
~FMeshPlaneCut()
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshPlaneCut::~FMeshPlaneCut () inline virtual
Definition at line 130 of file MeshPlaneCut.h.
Member Function Documentation
CollapseDegenerateEdges()
DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::CollapseDegenerateEdges (TSet< int > & Edges, bool bRemoveAllDegenerateFromInputSet, TSet< int > * TriangleSelection = nullptr) protected
Collapse degenerate edges.
Parameters
Edges Edges to consider for collapse; will updated by removing edges at they are collapsed
bRemoveAllDegenerateFromInputSet Whether we should also check whether the neighbor edges removed by collapse were also in the set (typically this is not needed, and has additional cost)
TriangleSelection Optional set tracking an active selection. Any triangles removed by collapse will also be removed from the set.
References CollapseDegenerateEdges(), and UE_API.
Referenced by CollapseDegenerateEdges().
ComputeVertexSignedDistances()
DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::ComputeVertexSignedDistances (TArray< double > & Signs, double InvalidDist) private
References ComputeVertexSignedDistances(), and UE_API.
Referenced by ComputeVertexSignedDistances().
Cut()
virtual DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::Cut () virtual
Compute the plane cut by splitting mesh edges that cross the cut plane, and then deleting any triangles on the positive side of the cutting plane.
Returns
true if operation succeeds
References UE_API.
CutWithoutDelete()
virtual DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::CutWithoutDelete (bool bSplitVerticesAtPlane, float OffsetSeparatedPortion = 0.0f, TDynamicMeshScalarTriangleAttribute< int > * TriLabels = nullptr, int NewLabelStartID = 0, bool bAddBoundariesFirstHalf = true, bool bAddBoundariesSecondHalf = true) virtual
Compute the plane cut by splitting mesh edges that cross the cut plane, but not deleting triangles on positive side.
Parameters
bSplitVerticesAtPlane if true, vertices on cutting plane are split into multiple vertices
OffsetSeparatedPortion positive side of cut mesh is offset by this distance along plane normal
TriLabels optional per-triangle integer labels
NewLabelStartID starting new label value
bAddBoundariesFirstHalf add open boundaries on "first" half to OpenBoundaries list (default true)
bAddBoundariesSecondHalf add open boundaries on "second" half to OpenBoundaries list (default true)
Returns
true if operation succeeds
References UE_API.
ExtractBoundaryLoops()
DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::ExtractBoundaryLoops (const TSet< int > & OnCutEdges, const TSet< int > & ZeroEdges, FMeshPlaneCut::FOpenBoundary & Boundary) protected
References FMeshPlaneCut(), ExtractBoundaryLoops(), UE_API, and ZeroEdges.
Referenced by ExtractBoundaryLoops().
HoleFill()
virtual DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::HoleFill (TFunction< TArray< FIndex3i >(const FGeneralPolygon2d &)> PlanarTriangulationFunc, bool bFillSpans, int ConstantGroupID = -1, int MaterialID = -1) virtual
Fill cut loops with FPlanarHoleFiller, using a caller-provided triangulation function.
References UE::Geometry::MaterialID, and UE_API.
MinimalHoleFill()
virtual DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::MinimalHoleFill (int ConstantGroupID = -1) virtual
References UE_API.
SimpleHoleFill()
virtual DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::SimpleHoleFill (int ConstantGroupID = -1) virtual
Fill cut loops with FSimpleHoleFiller.
References UE_API.
SplitCrossingEdges() [1/3]
DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::SplitCrossingEdges (bool bDeleteTrisOnPlane, TArray< double > & Signs, TSet< int > & AlreadyOnPlaneEdges, TSet< int32 > & CutPlaneEdges, TSet< int > * SplitEdges = nullptr, TSet< int > * OnPlaneVertices = nullptr, TSet< int > * TriangleSelection = nullptr) protected
References SplitCrossingEdges(), and UE_API.
SplitCrossingEdges() [2/3]
DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::SplitCrossingEdges (TArray< double > & Signs, TSet< int > & ZeroEdges, TSet< int > & OnCutEdges, bool bDeleteTrisOnPlane = true) protected
References SplitCrossingEdges(), UE_API, and ZeroEdges.
Referenced by SplitCrossingEdges(), SplitCrossingEdges(), and SplitCrossingEdges().
SplitCrossingEdges() [3/3]
DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::SplitCrossingEdges (TArray< double > & Signs, TSet< int > & ZeroEdges, TSet< int > & OnCutEdges, TSet< int > & OnSplitEdges, bool bDeleteTrisOnPlane = true) protected
References SplitCrossingEdges(), UE_API, and ZeroEdges.
SplitEdgesOnly()
virtual bool UE::Geometry::FMeshPlaneCut::SplitEdgesOnly (bool bAssignNewGroups, TSet< int32 > * OptionalTriangleSelection) inline virtual
Compute the plane cut by splitting mesh edges that cross the cut plane, and then optionally update groups.
Parameters
bAssignNewGroups if true, update group IDs such that each group-connected-component on either side of the cut plane is assigned a new unique group ID
OptionalTriangleSelection if non-null, a set of triangle IDs that must be updated along with any triangle splits or deletions in the edge split process
Returns
true if operation succeeds
Definition at line 169 of file MeshPlaneCut.h.
References SplitEdgesOnlyHelper().
Referenced by UE_DEPRECATED().
SplitEdgesOnlyHelper()
DYNAMICMESH_API bool UE::Geometry::FMeshPlaneCut::SplitEdgesOnlyHelper (bool bAssignNewGroups, TSet< int32 > * OptionalTriangleSelection, bool bAddDeprecatedResultSeedTriangles) private
References SplitEdgesOnlyHelper(), and UE_API.
Referenced by SplitEdgesOnly(), SplitEdgesOnlyHelper(), and UE_DEPRECATED().
TransferTriangleLabelsToHoleFillTriangles()
virtual DYNAMICMESH_API void UE::Geometry::FMeshPlaneCut::TransferTriangleLabelsToHoleFillTriangles (TDynamicMeshScalarTriangleAttribute< int > * TriLabels) virtual
References UE_API.
UE_DEPRECATED() [1/4]
UE::Geometry::FMeshPlaneCut::UE_DEPRECATED (5. 3, "If needed, explicitly request the vertices on the cut plane the the OnPlaneVertices argument of SplitCrossingEdges") protected
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
UE::Geometry::FMeshPlaneCut::UE_DEPRECATED (5. 3, "Instead use the two-parameter version of SplitEdgesOnly, which has direction selection tracking and does not populate the deprecated ResultSeedTriangles") inline
Definition at line 174 of file MeshPlaneCut.h.
References SplitEdgesOnly(), and SplitEdgesOnlyHelper().
UE_DEPRECATED() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshPlaneCut::UE_DEPRECATED (5. 3, "To preserve a triangle selection when using SplitEdgesOnly(), instead pass the selection as a pointer to that function.")
List of output cut triangles representing the seed triangles along the cut.
Currently only calculated by SplitEdgesOnly() path
References PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [4/4]
UE::Geometry::FMeshPlaneCut::UE_DEPRECATED (5. 3, "Use the single-set CollapseDegenerateEdges instead") const & protected
Validate()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS EOperationValidationResult UE::Geometry::FMeshPlaneCut::Validate () inline virtual
Returns
EOperationValidationResult::Ok if we can apply operation, or error code if we cannot
Definition at line 136 of file MeshPlaneCut.h.
References UE::Geometry::Ok.
Field Documentation
bCollapseDegenerateEdgesOnCut
bool UE::Geometry::FMeshPlaneCut::bCollapseDegenerateEdgesOnCut = true
Definition at line 68 of file MeshPlaneCut.h.
bSimplifyAlongNewEdges
bool UE::Geometry::FMeshPlaneCut::bSimplifyAlongNewEdges = false
Control whether we attempt to auto-simplify the small planar triangles that the plane cut operation tends to generate.
Definition at line 66 of file MeshPlaneCut.h.
DegenerateEdgeTol
double UE::Geometry::FMeshPlaneCut::DegenerateEdgeTol = FMathd::ZeroTolerance
Definition at line 73 of file MeshPlaneCut.h.
EdgeFilterFunc
TUniqueFunction<bool(int32)> UE::Geometry::FMeshPlaneCut::EdgeFilterFunc = nullptr
If set, only edges that pass this filter will be split.
Definition at line 63 of file MeshPlaneCut.h.
HoleFillTriangles
TArray<TArray<int> > UE::Geometry::FMeshPlaneCut::HoleFillTriangles
Definition at line 102 of file MeshPlaneCut.h.
Mesh
FDynamicMesh3* UE::Geometry::FMeshPlaneCut::Mesh
Definition at line 57 of file MeshPlaneCut.h.
Referenced by FMeshPlaneCut().
OpenBoundaries
TArray<FOpenBoundary> UE::Geometry::FMeshPlaneCut::OpenBoundaries
Definition at line 99 of file MeshPlaneCut.h.
PlaneNormal
FVector3d UE::Geometry::FMeshPlaneCut::PlaneNormal
Definition at line 58 of file MeshPlaneCut.h.
Referenced by FMeshPlaneCut().
PlaneOrigin
FVector3d UE::Geometry::FMeshPlaneCut::PlaneOrigin
Definition at line 58 of file MeshPlaneCut.h.
Referenced by FMeshPlaneCut().
PlaneTolerance
double UE::Geometry::FMeshPlaneCut::PlaneTolerance = FMathf::ZeroTolerance * 10.0
Tolerance distance for considering a vertex to be 'on plane'.
Definition at line 76 of file MeshPlaneCut.h.
ResultRegions
TArray<FCutResultRegion> UE::Geometry::FMeshPlaneCut::ResultRegions
List of output cut regions (eg that have separate GroupIDs).
Currently only calculated by SplitEdgesOnly() path
Definition at line 110 of file MeshPlaneCut.h.
SimplifySettings
FLocalPlanarSimplify UE::Geometry::FMeshPlaneCut::SimplifySettings
Settings to apply if bSimplifyAlongNewEdges == true.
Definition at line 79 of file MeshPlaneCut.h.
UVScaleFactor
float UE::Geometry::FMeshPlaneCut::UVScaleFactor = 1.0f
UVs on any hole fill surfaces are scaled by this amount.
Definition at line 71 of file MeshPlaneCut.h.
ZeroEdges
const TSet<int>& UE::Geometry::FMeshPlaneCut::ZeroEdges protected
Definition at line 198 of file MeshPlaneCut.h.
Referenced by ExtractBoundaryLoops(), SplitCrossingEdges(), and SplitCrossingEdges().
The documentation for this class was generated from the following file:
MeshPlaneCut.h