Unreal Engine 5.6 C++ API: UMeshComponent Class Reference
UMeshComponent Class Reference
#include "MeshComponent.h"
Data Structures
struct FMaterialParameterCache
Struct containing information about a given parameter name.
Public Member Functions
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Data Fields
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
void CleanUpMaterialSlotsOverlayMaterial ()
void CleanUpOverrideMaterials ()
void EmptyOverrideMaterials ()
This empties all override materials and used by editor when replacing preview mesh.
virtual UMaterialInterface * GetMaterial (int32 ElementIndex) const override
virtual UMaterialInterface * GetMaterialByName (FName MaterialSlotName) const override
virtual FMaterialRelevance GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const
Accesses the scene relevance information for the materials applied to the mesh.
void GetMaterialSlotsOverlayMaterial (TArray< TObjectPtr< class UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Fill the array with every material slot overlay material use by this instance.
virtual bool GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo &MaterialData) const
Get the material info for texture streaming.
virtual UTexture * GetMeshPaintTexture () const
Get the mesh paint texture set on this component.
virtual int32 GetMeshPaintTextureCoordinateIndex () const
Get the default coordinate index for painting to the mesh paint texture on this component.
virtual int32 GetNumMaterials () const override
virtual int32 GetNumOverrideMaterials () const
Returns override materials count.
void GetStreamingTextureInfoInner (FStreamingTextureLevelContext &LevelContext, const TArray< FStreamingTextureBuildInfo > *PreBuiltData, float ComponentScaling, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingTextures) const
Generate streaming data for all materials.
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
FColor GetWireframeColorForSceneProxy () const
Returns the wireframe color to use for this component.
bool HasOverrideMaterials ()
Returns true if there are any override materials set for this component.
virtual void LogMaterialsAndTextures (FOutputDevice &Ar, int32 Indent) const
Output to the log which materials and textures are used by this component.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn)
Register a one-time callback that will be called when criteria met.
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&CallbackStreamingStart, FLODStreamingCallback &&CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs)
Register a one-time callback that will be called when streaming starts or ends.
void SetMarkTextureAsEditorStreamingPool (bool bInMarkAsEditorStreamingPool)
Set the bMarkAsEditorStreamingPool on all textures used by this component.
virtual void SetMaterial (int32 ElementIndex, UMaterialInterface *Material) override
virtual void SetMaterialByName (FName MaterialSlotName, class UMaterialInterface *Material) override
virtual void SetMeshPaintTexture (UTexture *Texture)
Set the mesh paint texture on this component.
virtual void SetMeshPaintTextureOverride (UTexture *OverrideTexture)
Set a transient override mesh paint texture on this component.
virtual void SetTextureForceResidentFlag (bool bForceMiplevelsToBeResident)
Tell the streaming system whether or not all mip levels of all textures used by this component should be loaded and remain loaded.
UFUNCTION () 1 class UMaterialInterface *GetOverlayMaterial() const
Get the overlay material used by this instance.
UFUNCTION () 1 float GetOverlayMaterialMaxDrawDistance() const
Get the overlay material used by this instance.
GENERATED_UCLASS_BODY() public UFUNCTION () 1 virtual TArray< class UMaterialInterface * > GetMaterials() const
Per-Component material overrides.
UFUNCTION () 1 virtual void PrestreamTextures(float Seconds
Tell the streaming system to start loading all textures with all mip-levels.
UFUNCTION () 1 void SetOverlayMaterial(class UMaterialInterface *NewOverlayMaterial)
Change the overlay material used by this instance.
UFUNCTION () 1 void SetOverlayMaterialMaxDrawDistance(float InMaxDrawDistance)
Change the overlay material max draw distance used by this instance.
UFUNCTION ()) virtual bool PrestreamMeshLODs(float Seconds)
Tell the streaming system to start streaming in all LODs for the mesh.
UPROPERTY () float OverlayMaterialMaxDrawDistance
The max draw distance for overlay material.
UPROPERTY () TArray< TObjectPtr< class UMaterialInterface > > MaterialSlotsOverlayMaterial
Translucent material to blend on top of this mesh.
UPROPERTY () TObjectPtr< class UMaterialInterface > OverlayMaterial
Translucent material to blend on top of this mesh.
virtual bool UseNaniteOverrideMaterials () const
Determines if we use the nanite overrides from any materials.
Private Attributes
bool bPrioritizeCharacterTextures
bool int32 CinematicTextureGroups = 0)
Detailed Description
Definition at line 24 of file MeshComponent.h.
Member Function Documentation
BeginDestroy()
virtual void UMeshComponent::BeginDestroy () override protected virtual
Reimplemented in UDynamicMeshComponent, UGroomComponent, UInstancedStaticMeshComponent, and UStaticMeshComponent.
CacheMaterialParameterNameIndices()
void UMeshComponent::CacheMaterialParameterNameIndices () protected
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
CleanUpMaterialSlotsOverlayMaterial()
void UMeshComponent::CleanUpMaterialSlotsOverlayMaterial () private
CleanUpOverrideMaterials()
void UMeshComponent::CleanUpOverrideMaterials () private
EmptyOverrideMaterials()
void UMeshComponent::EmptyOverrideMaterials () private
This empties all override materials and used by editor when replacing preview mesh.
GetComponentMaterialSlotsOverlayMaterial()
const TArray< TObjectPtr< UMaterialInterface > > & UMeshComponent::GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
GetDefaultMaterialSlotsOverlayMaterial()
virtual void UMeshComponent::GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > & OutMaterialSlotOverlayMaterials) const inline virtual
Get all default material slots overlay materials from the mesh.
Reimplemented in UStaticMeshComponent.
Definition at line 231 of file MeshComponent.h.
GetDefaultOverlayMaterial()
virtual UMaterialInterface * UMeshComponent::GetDefaultOverlayMaterial () const inline protected virtual
Get the default overlay material used by a mesh.
Definition at line 240 of file MeshComponent.h.
GetDefaultOverlayMaterialMaxDrawDistance()
virtual float UMeshComponent::GetDefaultOverlayMaterialMaxDrawDistance () const inline protected virtual
Get the default overlay material max draw distance.
Definition at line 243 of file MeshComponent.h.
GetMaterial()
virtual UMaterialInterface * UMeshComponent::GetMaterial (int32 ElementIndex) const override private virtual
Reimplemented in UBaseDynamicMeshComponent, UGroomComponent, and UStaticMeshComponent.
GetMaterialByName()
virtual UMaterialInterface * UMeshComponent::GetMaterialByName (FName MaterialSlotName) const override private virtual
Reimplemented in UBaseDynamicMeshComponent.
GetMaterialRelevance()
virtual FMaterialRelevance UMeshComponent::GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const private virtual
Accesses the scene relevance information for the materials applied to the mesh.
Valid from game thread only.
Reimplemented in UBaseDynamicMeshComponent.
GetMaterialSlotsOverlayMaterial()
void UMeshComponent::GetMaterialSlotsOverlayMaterial (TArray< TObjectPtr< class UMaterialInterface > > & OutMaterialSlotOverlayMaterials) const private
Fill the array with every material slot overlay material use by this instance.
If this component material slot overlay material will be used if not null. If there is no valid component material slot overlay material, the mesh material slot overlay material will be used if not null. If there is no valid asset material slot overlay material, a null entry will be set for the material slot overlay material.
References GetMaterialSlotsOverlayMaterial().
Referenced by GetMaterialSlotsOverlayMaterial().
GetMaterialStreamingData()
virtual bool UMeshComponent::GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo & MaterialData) const inline private virtual
Get the material info for texture streaming.
Return whether the data is valid or not.
Reimplemented in UInstancedStaticMeshComponent, and UStaticMeshComponent.
Definition at line 174 of file MeshComponent.h.
GetMeshPaintTexture()
virtual UTexture * UMeshComponent::GetMeshPaintTexture () const inline private virtual
Get the mesh paint texture set on this component.
This does not take into account any transient override.
Reimplemented in UStaticMeshComponent.
Definition at line 191 of file MeshComponent.h.
GetMeshPaintTextureCoordinateIndex()
virtual int32 UMeshComponent::GetMeshPaintTextureCoordinateIndex () const inline private virtual
Get the default coordinate index for painting to the mesh paint texture on this component.
Reimplemented in UStaticMeshComponent.
Definition at line 197 of file MeshComponent.h.
GetNumMaterials()
virtual int32 UMeshComponent::GetNumMaterials () const override private virtual
Reimplemented in UBaseDynamicMeshComponent, UBasicLineSetComponentBase, UBasicPointSetComponentBase, UBasicTriangleSetComponentBase, UGroomComponent, UHeterogeneousVolumeComponent, UStaticMeshComponent, and UWaterMeshComponent.
GetNumOverrideMaterials()
virtual int32 UMeshComponent::GetNumOverrideMaterials () const private virtual
Returns override materials count.
GetScalarParameterDefaultValue()
float UMeshComponent::GetScalarParameterDefaultValue (const FName ParameterName) inline
Returns default value for the parameter input.
NOTE: This is not reliable when cooking, as initializing the default value requires a render resource that only exists if the owning world is rendering.
Definition at line 219 of file MeshComponent.h.
References GetScalarParameterDefaultValue(), MaterialParameterCache, and UMeshComponent::FMaterialParameterCache::ScalarParameterDefaultValue.
Referenced by GetScalarParameterDefaultValue().
GetStreamingTextureInfoInner()
void UMeshComponent::GetStreamingTextureInfoInner (FStreamingTextureLevelContext & LevelContext, const TArray< FStreamingTextureBuildInfo > * PreBuiltData, float ComponentScaling, TArray< FStreamingRenderAssetPrimitiveInfo > & OutStreamingTextures) const private
Generate streaming data for all materials.
GetUsedMaterials()
virtual void UMeshComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override private virtual
Reimplemented in UBaseDynamicMeshComponent, UGroomComponent, UHeterogeneousVolumeComponent, UStaticMeshComponent, and UWaterMeshComponent.
GetWireframeColorForSceneProxy()
FColor UMeshComponent::GetWireframeColorForSceneProxy () const private
Returns the wireframe color to use for this component.
HasOverrideMaterials()
bool UMeshComponent::HasOverrideMaterials () private
Returns true if there are any override materials set for this component.
LogMaterialsAndTextures()
virtual void UMeshComponent::LogMaterialsAndTextures (FOutputDevice & Ar, int32 Indent) const private virtual
Output to the log which materials and textures are used by this component.
Parameters
Indent Number of tabs to put before the log.
References Ar.
MarkCachedMaterialParameterNameIndicesDirty()
void UMeshComponent::MarkCachedMaterialParameterNameIndicesDirty () protected
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
PostEditChangeChainProperty()
virtual void UMeshComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override private virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
RegisterLODStreamingCallback() [1/2]
virtual void UMeshComponent::RegisterLODStreamingCallback (FLODStreamingCallback && Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) private virtual
Register a one-time callback that will be called when criteria met.
Parameters
Callback
LODIdx The LOD index expected. Specify -1 for the MinLOD.
TimeoutSecs Timeout in seconds
bOnStreamIn To get notified when the expected LOD is streamed in or out
Reimplemented in UStaticMeshComponent.
RegisterLODStreamingCallback() [2/2]
virtual void UMeshComponent::RegisterLODStreamingCallback (FLODStreamingCallback && CallbackStreamingStart, FLODStreamingCallback && CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) private virtual
Register a one-time callback that will be called when streaming starts or ends.
Parameters
CallbackStreamingStart The callback to notify when streaming new LODs in begins. The callback will not always be called if the asset is not streamable, or the asset or component is unloaded.
CallbackStreamingDone The callback to notify when streaming is done. The callback will not be called if the start timeout expired.
TimeoutStartSecs Timeout for streaming to start, in seconds
TimeoutDoneSecs Timeout for streaming to end, in seconds
Reimplemented in UStaticMeshComponent.
SetMarkTextureAsEditorStreamingPool()
void UMeshComponent::SetMarkTextureAsEditorStreamingPool (bool bInMarkAsEditorStreamingPool) private
Set the bMarkAsEditorStreamingPool on all textures used by this component.
Parameters
bInMarkAsEditorStreamingPool Whether textures should only be counted for the Editor pool stats.
SetMaterial()
virtual void UMeshComponent::SetMaterial (int32 ElementIndex, UMaterialInterface * Material) override private virtual
Reimplemented in UBaseDynamicMeshComponent, UHeterogeneousVolumeComponent, and UWaterMeshComponent.
References Material.
SetMaterialByName()
virtual void UMeshComponent::SetMaterialByName (FName MaterialSlotName, class UMaterialInterface * Material) override private virtual
References Material.
SetMeshPaintTexture()
virtual void UMeshComponent::SetMeshPaintTexture (UTexture * Texture) inline private virtual
Set the mesh paint texture on this component.
Reimplemented in UStaticMeshComponent.
Definition at line 193 of file MeshComponent.h.
References Texture.
SetMeshPaintTextureOverride()
virtual void UMeshComponent::SetMeshPaintTextureOverride (UTexture * OverrideTexture) inline private virtual
Set a transient override mesh paint texture on this component.
Reimplemented in UStaticMeshComponent.
Definition at line 195 of file MeshComponent.h.
SetTextureForceResidentFlag()
virtual void UMeshComponent::SetTextureForceResidentFlag (bool bForceMiplevelsToBeResident) private virtual
Tell the streaming system whether or not all mip levels of all textures used by this component should be loaded and remain loaded.
Parameters
bForceMiplevelsToBeResident Whether textures should be forced to be resident or not.
UFUNCTION() [1/10]
UMeshComponent::UFUNCTION () const private
Get the overlay material used by this instance.
References Category.
UFUNCTION() [2/10]
UMeshComponent::UFUNCTION () const private
Get the overlay material used by this instance.
References Category, and UFUNCTION().
UFUNCTION() [3/10]
GENERATED_UCLASS_BODY() public UMeshComponent::UFUNCTION () const private
Per-Component material overrides.
These must NOT be set directly or a race condition can occur between GC and the rendering thread.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/10]
UMeshComponent::UFUNCTION () private
Tell the streaming system to start loading all textures with all mip-levels.
Parameters
Seconds Number of seconds to force all mip-levels to be resident
bPrioritizeCharacterTextures Whether character textures should be prioritized for a while by the streaming system
CinematicTextureGroups Bitfield indicating which texture groups that use extra high-resolution mips
References Category.
UFUNCTION() [5/10]
UMeshComponent::UFUNCTION () const
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
References Category, and UFUNCTION().
UFUNCTION() [6/10]
UMeshComponent::UFUNCTION () private
Change the overlay material used by this instance.
References Category, and UFUNCTION().
UFUNCTION() [7/10]
UMeshComponent::UFUNCTION () private
Change the overlay material max draw distance used by this instance.
References Category, and UFUNCTION().
UFUNCTION() [8/10]
UMeshComponent::UFUNCTION () const
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
References Category.
UFUNCTION() [9/10]
UMeshComponent::UFUNCTION () const
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
References Category, and UFUNCTION().
UFUNCTION() [10/10]
UMeshComponent::UFUNCTION () inline private
Tell the streaming system to start streaming in all LODs for the mesh.
Note: this function may set bIgnoreStreamingMipBias on this component enable the FastForceResident system.
Returns
bool True if streaming was successfully requested
Parameters
Seconds Number of seconds to force all LODs to be resident
Definition at line 153 of file MeshComponent.h.
References Category, meta, Seconds, and UFUNCTION().
UPROPERTY() [1/3]
UMeshComponent::UPROPERTY () private
The max draw distance for overlay material.
A distance of 0 indicates that overlay will be culled using primitive max distance.
References Category.
UPROPERTY() [2/3]
UMeshComponent::UPROPERTY () private
Translucent material to blend on top of this mesh.
Mesh will be rendered twice - once with a base material and once with overlay material. The difference with the global OverlayMaterial is those are per material slot, if the entry is null or doesn't exist the global OverlayMaterial will be use for sections using the material slot.
References Category, and UPROPERTY().
UPROPERTY() [3/3]
UMeshComponent::UPROPERTY () private
Translucent material to blend on top of this mesh.
Mesh will be rendered twice - once with a base material and once with overlay material
References Category.
Referenced by UPROPERTY().
UseNaniteOverrideMaterials()
virtual bool UMeshComponent::UseNaniteOverrideMaterials () const inline private virtual
Determines if we use the nanite overrides from any materials.
Reimplemented in UStaticMeshComponent.
Definition at line 37 of file MeshComponent.h.
References UseNaniteOverrideMaterials().
Referenced by UseNaniteOverrideMaterials().
Field Documentation
bCachedMaterialParameterIndicesAreDirty
uint8 UMeshComponent::bCachedMaterialParameterIndicesAreDirty protected
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
Flag whether or not the cached material parameter indices map is dirty (defaults to true, and is set from SetMaterial/Set(Skeletal)Mesh
Definition at line 273 of file MeshComponent.h.
bPrioritizeCharacterTextures
bool UMeshComponent::bPrioritizeCharacterTextures private
Definition at line 145 of file MeshComponent.h.
CinematicTextureGroups
bool int32 UMeshComponent::CinematicTextureGroups = 0) private
Definition at line 145 of file MeshComponent.h.
MaterialParameterCache
TSortedMap<FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess> UMeshComponent::MaterialParameterCache protected
Definition at line 275 of file MeshComponent.h.
Referenced by GetScalarParameterDefaultValue().
ParameterValue [1/3]
const float UMeshComponent::ParameterValue
Definition at line 203 of file MeshComponent.h.
ParameterValue [2/3]
const FVector UMeshComponent::ParameterValue
Definition at line 207 of file MeshComponent.h.
ParameterValue [3/3]
const FLinearColor UMeshComponent::ParameterValue
Definition at line 211 of file MeshComponent.h.
The documentation for this class was generated from the following file:
MeshComponent.h