Unreal Engine 5.6 C++ API: UE::Sequencer::FChannelModel Class Reference
UE::Sequencer::FChannelModel Class Reference
Model for a single channel inside a section.
#include "ChannelModel.h"
Public Member Functions
FChannelModel (FName InChannelName, TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
~FChannelModel ()
FTrackLaneVirtualAlignment ArrangeVirtualTrackLaneView () const override
virtual void BuildContextMenu (FMenuBuilder &MenuBuilder, TViewModelPtr< FChannelGroupOutlinerModel > GroupOwner)
TUniquePtr< FCurveModel > CreateCurveModel () override
virtual TSharedPtr< SWidget > CreateOutlinerViewForColumn (const FCreateOutlinerViewParams &InParams, const FName &InColumnName)
TSharedPtr< ITrackLaneWidget > CreateTrackLaneView (const FCreateTrackLaneViewParams &InParams) override
int32 CustomPaint (const FSequencerChannelPaintArgs &CustomPaintArgs, int32 LayerId) const
void DrawKeys (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FKeyDrawParams > OutKeyDrawParams) override
FMovieSceneChannel * GetChannel () const
Returns the associated channel object.
FName GetChannelName () const
Returns the channel's name.
FOutlinerSizing GetDesiredSizing () const
Returns the desired sizing for the track area row.
bool GetFixedExtents (double &OutFixedMin, double &OutFixedMax) const override
TSharedPtr< IKeyArea > GetKeyArea () const
Returns the key area for the channel.
UObject * GetOwningObject () const
Returns the object that owns the associated channel.
UMovieSceneSection * GetSection () const
Returns the section object that owns the associated channel.
void Initialize (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
bool IsAnimated () const
Returns whether this channel has any keyframes on it.
void OnRecycle () override
UE_SEQUENCER_DECLARE_CASTABLE (FChannelModel, FViewModel, FLinkedOutlinerExtension, IGeometryExtension, ITrackLaneExtension, IRecyclableExtension, IKeyExtension)
bool UpdateCachedKeys (TSharedPtr< FCachedKeys > &OutCachedKeys) const override
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::FLinkedOutlinerExtension
FLinkedOutlinerExtension ()
TViewModelPtr< IOutlinerExtension > GetLinkedOutlinerItem () const
void SetLinkedOutlinerItem (const TViewModelPtr< IOutlinerExtension > &InOutlinerItem)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (FLinkedOutlinerExtension)
Public Member Functions inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry GetVirtualGeometry () const override
void ReportVirtualGeometry (const FVirtualGeometry &InVirtualGeometry) override
Public Member Functions inherited from UE::Sequencer::IGeometryExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGeometryExtension) virtual ~IGeometryExtension()
Public Member Functions inherited from UE::Sequencer::FLinkedOutlinerComputedSizingShim
FOutlinerSizing GetComputedSizing () const
void SetComputedSizing (const FOutlinerSizing &InSizing)
Public Member Functions inherited from UE::Sequencer::ITrackLaneExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackLaneExtension) virtual ~ITrackLaneExtension()
Public Member Functions inherited from UE::Sequencer::IRecyclableExtension
virtual ~IRecyclableExtension ()
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IRecyclableExtension) static void CallOnRecycle(const TViewModelPtr< IRecyclableExtension > &RecyclableItem)
Public Member Functions inherited from UE::Sequencer::IKeyExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IKeyExtension) virtual ~IKeyExtension()
Private Member Functions
FLinearColor GetKeyBarColor () const
Private Attributes
const FName ChannelName
const TPimplPtr< FCurveModelID > CurveModelID
Consistent ID that is reused and injected into the curve model every time it is created.
TSharedPtr< IKeyArea > KeyArea
Additional Inherited Members
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Public Member Functions inherited from UE::Sequencer::IGeometryExtension
static float UpdateVirtualGeometry (float InitialVirtualPosition, TSharedPtr< FViewModel > InInitialItem)
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Protected Attributes inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry VirtualGeometry
Protected Attributes inherited from UE::Sequencer::FLinkedOutlinerComputedSizingShim
FOutlinerSizing ComputedSizing
Detailed Description
Model for a single channel inside a section.
For instance, this represents the "Location.X" channel of a single transform section.
Definition at line 55 of file ChannelModel.h.
Constructor & Destructor Documentation
FChannelModel()
UE::Sequencer::FChannelModel::FChannelModel (FName InChannelName, TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
Referenced by UE_SEQUENCER_DECLARE_CASTABLE().
~FChannelModel()
UE::Sequencer::FChannelModel::~FChannelModel ()
Member Function Documentation
ArrangeVirtualTrackLaneView()
FTrackLaneVirtualAlignment UE::Sequencer::FChannelModel::ArrangeVirtualTrackLaneView () const override virtual
Implements UE::Sequencer::ITrackLaneExtension.
BuildContextMenu()
virtual void UE::Sequencer::FChannelModel::BuildContextMenu (FMenuBuilder & MenuBuilder, TViewModelPtr< FChannelGroupOutlinerModel > GroupOwner) inline virtual
Definition at line 110 of file ChannelModel.h.
CreateCurveModel()
TUniquePtr< FCurveModel > UE::Sequencer::FChannelModel::CreateCurveModel () override virtual
Implements UE::Sequencer::IKeyExtension.
CreateOutlinerViewForColumn()
virtual TSharedPtr< SWidget > UE::Sequencer::FChannelModel::CreateOutlinerViewForColumn (const FCreateOutlinerViewParams & InParams, const FName & InColumnName) inline virtual
Definition at line 111 of file ChannelModel.h.
CreateTrackLaneView()
TSharedPtr< ITrackLaneWidget > UE::Sequencer::FChannelModel::CreateTrackLaneView (const FCreateTrackLaneViewParams & InParams) override virtual
Implements UE::Sequencer::ITrackLaneExtension.
CustomPaint()
int32 UE::Sequencer::FChannelModel::CustomPaint (const FSequencerChannelPaintArgs & CustomPaintArgs, int32 LayerId) const
DrawKeys()
void UE::Sequencer::FChannelModel::DrawKeys (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FKeyDrawParams > OutKeyDrawParams) override virtual
Implements UE::Sequencer::IKeyExtension.
GetChannel()
FMovieSceneChannel * UE::Sequencer::FChannelModel::GetChannel () const
Returns the associated channel object.
GetChannelName()
FName UE::Sequencer::FChannelModel::GetChannelName () const inline
Returns the channel's name.
Definition at line 86 of file ChannelModel.h.
References ChannelName.
GetDesiredSizing()
FOutlinerSizing UE::Sequencer::FChannelModel::GetDesiredSizing () const
Returns the desired sizing for the track area row.
GetFixedExtents()
bool UE::Sequencer::FChannelModel::GetFixedExtents (double & OutFixedMin, double & OutFixedMax) const override virtual
Implements UE::Sequencer::IKeyExtension.
GetKeyArea()
TSharedPtr< IKeyArea > UE::Sequencer::FChannelModel::GetKeyArea () const inline
Returns the key area for the channel.
Definition at line 89 of file ChannelModel.h.
References KeyArea.
GetKeyBarColor()
FLinearColor UE::Sequencer::FChannelModel::GetKeyBarColor () const private
GetOwningObject()
UObject * UE::Sequencer::FChannelModel::GetOwningObject () const
Returns the object that owns the associated channel.
May return the same as GetSection().
GetSection()
UMovieSceneSection * UE::Sequencer::FChannelModel::GetSection () const
Returns the section object that owns the associated channel.
Initialize()
void UE::Sequencer::FChannelModel::Initialize (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
IsAnimated()
bool UE::Sequencer::FChannelModel::IsAnimated () const
Returns whether this channel has any keyframes on it.
OnRecycle()
void UE::Sequencer::FChannelModel::OnRecycle () override virtual
Implements UE::Sequencer::IRecyclableExtension.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FChannelModel::UE_SEQUENCER_DECLARE_CASTABLE (FChannelModel , FViewModel , FLinkedOutlinerExtension , IGeometryExtension , ITrackLaneExtension , IRecyclableExtension , IKeyExtension)
References FChannelModel(), UE::Sequencer::FLinkedOutlinerExtension::FLinkedOutlinerExtension(), and UE::Sequencer::FViewModel::FViewModel().
UpdateCachedKeys()
bool UE::Sequencer::FChannelModel::UpdateCachedKeys (TSharedPtr< FCachedKeys > & OutCachedKeys) const override virtual
Implements UE::Sequencer::IKeyExtension.
Field Documentation
ChannelName
const FName UE::Sequencer::FChannelModel::ChannelName private
Definition at line 123 of file ChannelModel.h.
Referenced by GetChannelName().
CurveModelID
const TPimplPtr<FCurveModelID> UE::Sequencer::FChannelModel::CurveModelID private
Consistent ID that is reused and injected into the curve model every time it is created.
Pimpl to avoid public build.cs dependency.
Definition at line 120 of file ChannelModel.h.
KeyArea
TSharedPtr<IKeyArea> UE::Sequencer::FChannelModel::KeyArea private
Definition at line 122 of file ChannelModel.h.
Referenced by GetKeyArea().
The documentation for this class was generated from the following file:
ChannelModel.h