Unreal Engine 5.6 C++ API: UE::Sequencer::FSelectionBase Class Reference
UE::Sequencer::FSelectionBase Class Reference abstract
Base class for all selection sets that can be added to an FSequencerCoreSelection owner.
#include "SequencerCoreSelectionTypes.h"
Public Member Functions
SEQUENCERCORE_API void Empty ()
Empty this selection set.
bool HasPendingChanges () const
Check whether this selection set has reported changes that are currently pending.
Data Fields
FSimpleMulticastDelegate OnChanged
Broadcast if this selection set has changed when all event suppressors have been destroyed.
Protected Member Functions
FSelectionBase ()
Should only be used by derived types.
virtual ~FSelectionBase ()
FSequencerCoreSelection * GetOwner () const
Retrieve the owner of this instance, assuming it has been added to one.
SEQUENCERCORE_API void ReportChanges (bool bInSelectionChanged=true)
Called by derived classes when they have changed.
Private Member Functions
virtual void EmptyImpl ()=0
Abstract function for emptying this selection.
Private Attributes
bool bSelectionChanged
Flag indicating whether this selection has changed within the current scope or not.
friend FSequencerCoreSelection
FSequencerCoreSelection * Owner
The owning instance of this class.
Detailed Description
Base class for all selection sets that can be added to an FSequencerCoreSelection owner.
Definition at line 21 of file SequencerCoreSelectionTypes.h.
Constructor & Destructor Documentation
FSelectionBase()
UE::Sequencer::FSelectionBase::FSelectionBase () inline protected
Should only be used by derived types.
Definition at line 48 of file SequencerCoreSelectionTypes.h.
References bSelectionChanged, and Owner.
~FSelectionBase()
virtual UE::Sequencer::FSelectionBase::~FSelectionBase () inline protected virtual
Definition at line 53 of file SequencerCoreSelectionTypes.h.
Member Function Documentation
Empty()
SEQUENCERCORE_API void UE::Sequencer::FSelectionBase::Empty ()
Empty this selection set.
EmptyImpl()
virtual void UE::Sequencer::FSelectionBase::EmptyImpl () private pure virtual
Abstract function for emptying this selection.
Implemented in UE::Sequencer::TSelectionSetBase< MixinType, KeyType >, UE::Sequencer::TSelectionSetBase< FMarkedFrameSelection, int32 >, UE::Sequencer::TSelectionSetBase< FOutlinerSelection, TWeakViewModelPtr< IOutlinerExtension > >, UE::Sequencer::TSelectionSetBase< FTrackAreaSelection, FWeakViewModelPtr >, UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >, and UE::Sequencer::TUniqueFragmentSelectionSet< FKeyHandle, FChannelModel >.
GetOwner()
FSequencerCoreSelection * UE::Sequencer::FSelectionBase::GetOwner () const inline protected
Retrieve the owner of this instance, assuming it has been added to one.
Definition at line 59 of file SequencerCoreSelectionTypes.h.
References FSequencerCoreSelection, and Owner.
Referenced by UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Deselect(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Deselect(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Empty(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Empty(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::RemoveByPredicate(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::RemoveByPredicate(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::ReplaceWith(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::ReplaceWith(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Select(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Select(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::SelectRange(), and UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::SelectRange().
HasPendingChanges()
bool UE::Sequencer::FSelectionBase::HasPendingChanges () const inline
Check whether this selection set has reported changes that are currently pending.
Definition at line 38 of file SequencerCoreSelectionTypes.h.
References bSelectionChanged.
ReportChanges()
SEQUENCERCORE_API void UE::Sequencer::FSelectionBase::ReportChanges (bool bInSelectionChanged = true) protected
Called by derived classes when they have changed.
Referenced by UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Deselect(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Deselect(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Empty(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::Empty(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::RemoveByPredicate(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::RemoveByPredicate(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::ReplaceWith(), UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::ReplaceWith(), UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::SelectRange(), and UE::Sequencer::TUniqueFragmentSelectionSet< KeyType, ModelType >::SelectRange().
Field Documentation
bSelectionChanged
bool UE::Sequencer::FSelectionBase::bSelectionChanged private
Flag indicating whether this selection has changed within the current scope or not.
Definition at line 81 of file SequencerCoreSelectionTypes.h.
Referenced by FSelectionBase(), and HasPendingChanges().
FSequencerCoreSelection
friend UE::Sequencer::FSelectionBase::FSequencerCoreSelection private
Definition at line 76 of file SequencerCoreSelectionTypes.h.
Referenced by GetOwner().
OnChanged
FSimpleMulticastDelegate UE::Sequencer::FSelectionBase::OnChanged
Broadcast if this selection set has changed when all event suppressors have been destroyed.
Definition at line 28 of file SequencerCoreSelectionTypes.h.
Owner
FSequencerCoreSelection* UE::Sequencer::FSelectionBase::Owner private
The owning instance of this class.
Definition at line 79 of file SequencerCoreSelectionTypes.h.
Referenced by FSelectionBase(), UE::Sequencer::FSequencerCoreSelection::AddSelectionSet(), and GetOwner().
The documentation for this class was generated from the following file:
SequencerCoreSelectionTypes.h