Unreal Engine 5.6 C++ API: FAIResourcesSet Struct Reference
FAIResourcesSet Struct Reference
#include "AITypes.h"
Public Member Functions
FAIResourcesSet (const FAIResourceID &Resource)
FAIResourcesSet (uint32 ResourceSetDescription=NoResources)
FAIResourcesSet & AddResource (const FAIResourceID &Resource)
FAIResourcesSet & AddResourceIndex (uint8 ResourceIndex)
void Clear ()
bool ContainsResource (const FAIResourceID &Resource) const
bool ContainsResourceIndex (uint8 ResourceID) const
bool IsEmpty () const
FAIResourcesSet & RemoveResource (const FAIResourceID &Resource)
FAIResourcesSet & RemoveResourceIndex (uint8 ResourceIndex)
Static Public Attributes
static constexpr uint32 AllResources = uint32(-1)
static constexpr uint8 MaxFlags = 32
static constexpr uint32 NoResources = 0
Private Attributes
uint32 Flags
Detailed Description
Definition at line 301 of file AITypes.h.
Constructor & Destructor Documentation
FAIResourcesSet() [1/2]
FAIResourcesSet::FAIResourcesSet (uint32 ResourceSetDescription = NoResources) inline
Definition at line 309 of file AITypes.h.
References Flags, and NoResources.
Referenced by AddResource(), AddResourceIndex(), RemoveResource(), and RemoveResourceIndex().
FAIResourcesSet() [2/2]
FAIResourcesSet::FAIResourcesSet (const FAIResourceID & Resource) inline
Definition at line 310 of file AITypes.h.
References AddResource(), and Flags.
Member Function Documentation
AddResource()
FAIResourcesSet & FAIResourcesSet::AddResource (const FAIResourceID & Resource) inline
Definition at line 319 of file AITypes.h.
References FAIResourcesSet(), AddResourceIndex(), and FAINamedID< TCounter >::Index.
Referenced by FAIResourcesSet().
AddResourceIndex()
FAIResourcesSet & FAIResourcesSet::AddResourceIndex (uint8 ResourceIndex) inline
Definition at line 315 of file AITypes.h.
References FAIResourcesSet(), and Flags.
Referenced by AddResource().
Clear()
void FAIResourcesSet::Clear () inline
Definition at line 324 of file AITypes.h.
References Flags.
ContainsResource()
bool FAIResourcesSet::ContainsResource (const FAIResourceID & Resource) const inline
Definition at line 321 of file AITypes.h.
References ContainsResourceIndex(), and FAINamedID< TCounter >::Index.
ContainsResourceIndex()
bool FAIResourcesSet::ContainsResourceIndex (uint8 ResourceID) const inline
Definition at line 317 of file AITypes.h.
References Flags.
Referenced by ContainsResource().
IsEmpty()
bool FAIResourcesSet::IsEmpty () const inline
Definition at line 323 of file AITypes.h.
References Flags.
RemoveResource()
FAIResourcesSet & FAIResourcesSet::RemoveResource (const FAIResourceID & Resource) inline
Definition at line 320 of file AITypes.h.
References FAIResourcesSet(), FAINamedID< TCounter >::Index, and RemoveResourceIndex().
RemoveResourceIndex()
FAIResourcesSet & FAIResourcesSet::RemoveResourceIndex (uint8 ResourceIndex) inline
Definition at line 316 of file AITypes.h.
References FAIResourcesSet(), and Flags.
Referenced by RemoveResource().
Field Documentation
AllResources
uint32 FAIResourcesSet::AllResources = uint32(-1) static constexpr
Definition at line 304 of file AITypes.h.
Flags
uint32 FAIResourcesSet::Flags private
Definition at line 307 of file AITypes.h.
Referenced by FAIResourcesSet(), FAIResourcesSet(), AddResourceIndex(), Clear(), ContainsResourceIndex(), IsEmpty(), and RemoveResourceIndex().
MaxFlags
uint8 FAIResourcesSet::MaxFlags = 32 static constexpr
Definition at line 305 of file AITypes.h.
NoResources
uint32 FAIResourcesSet::NoResources = 0 static constexpr
Definition at line 303 of file AITypes.h.
Referenced by FAIResourcesSet().
The documentation for this struct was generated from the following file:
AITypes.h