Unreal Engine 5.6 C++ API: FPackageIndex Class Reference
FPackageIndex Class Reference
Wrapper for index into a ULnker's ImportMap or ExportMap.
#include "ObjectResource.h"
Public Member Functions
FORCEINLINE FPackageIndex ()
Constructor, sets the value to null.
FORCEINLINE int32 ForDebugging () const
Return the raw value, for debugging purposes.
FORCEINLINE bool IsExport () const
return true if this is an index into the export map
FORCEINLINE bool IsImport () const
return true if this is an index into the import map
FORCEINLINE bool IsNull () const
return true if this null (i.e.
FORCEINLINE bool operator!= (const FPackageIndex &Other) const
Compare package indecies for inequality.
FORCEINLINE bool operator< (const FPackageIndex &Other) const
Compare package indecies.
FORCEINLINE bool operator<= (const FPackageIndex &Other) const
FORCEINLINE bool operator== (const FPackageIndex &Other) const
Compare package indecies for equality.
FORCEINLINE bool operator> (const FPackageIndex &Other) const
FORCEINLINE bool operator>= (const FPackageIndex &Other) const
FORCEINLINE int32 ToExport () const
Check that this is an export and return the index into the export map.
FORCEINLINE int32 ToImport () const
Check that this is an import and return the index into the import map.
Static Public Member Functions
static FORCEINLINE FPackageIndex FromExport (int32 ExportIndex)
Create a FPackageIndex from an export index.
static FORCEINLINE FPackageIndex FromImport (int32 ImportIndex)
Create a FPackageIndex from an import index.
Private Member Functions
FORCEINLINE FPackageIndex (int32 InIndex)
Internal constructor, sets the index directly.
Private Attributes
int32 Index
Values greater than zero indicate that this is an index into the ExportMap.
Friends
FORCEINLINE friend uint32 GetTypeHash (const FPackageIndex &In)
void LexFromString (FPackageIndex &Value, const TCHAR *String)
FString LexToString (const FPackageIndex &Value)
Lex functions.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FPackageIndex &Value)
Serializes a package index value from or into an archive.
FORCEINLINE friend void operator<< (FStructuredArchive::FSlot Slot, FPackageIndex &Value)
Serializes a package index value from or into a structured archive slot.
Detailed Description
Wrapper for index into a ULnker's ImportMap or ExportMap.
Values greater than zero indicate that this is an index into the ExportMap. The actual array index will be (FPackageIndex - 1).
Values less than zero indicate that this is an index into the ImportMap. The actual array index will be (-FPackageIndex - 1)
Definition at line 43 of file ObjectResource.h.
Constructor & Destructor Documentation
FPackageIndex() [1/2]
FORCEINLINE FPackageIndex::FPackageIndex (int32 InIndex) inline explicit private
Internal constructor, sets the index directly.
Definition at line 55 of file ObjectResource.h.
References FORCEINLINE, and Index.
Referenced by FromExport(), FromImport(), GetTypeHash, LexFromString, LexToString, operator!=(), operator<(), operator<<, operator<<, operator<=(), operator==(), operator>(), and operator>=().
FPackageIndex() [2/2]
FORCEINLINE FPackageIndex::FPackageIndex () inline
Constructor, sets the value to null.
Definition at line 62 of file ObjectResource.h.
References FORCEINLINE, and Index.
Referenced by FromExport(), and FromImport().
Member Function Documentation
ForDebugging()
FORCEINLINE int32 FPackageIndex::ForDebugging () const inline
Return the raw value, for debugging purposes.
Definition at line 95 of file ObjectResource.h.
References FORCEINLINE, and Index.
FromExport()
FORCEINLINE FPackageIndex FPackageIndex::FromExport (int32 ExportIndex) inline static
Create a FPackageIndex from an export index.
Definition at line 107 of file ObjectResource.h.
References FPackageIndex(), FPackageIndex(), check, and FORCEINLINE.
FromImport()
FORCEINLINE FPackageIndex FPackageIndex::FromImport (int32 ImportIndex) inline static
Create a FPackageIndex from an import index.
Definition at line 101 of file ObjectResource.h.
References FPackageIndex(), FPackageIndex(), check, and FORCEINLINE.
IsExport()
FORCEINLINE bool FPackageIndex::IsExport () const inline
return true if this is an index into the export map
Definition at line 73 of file ObjectResource.h.
References FORCEINLINE, and Index.
Referenced by FLinkerTables::GetClassName(), FLinkerTables::GetExportClassName(), FLinker::GetExportFullName(), FLinker::GetExportPathName(), FLinker::GetFullImpExpName(), FLinker::GetPathName(), and ToExport().
IsImport()
FORCEINLINE bool FPackageIndex::IsImport () const inline
return true if this is an index into the import map
Definition at line 68 of file ObjectResource.h.
References FORCEINLINE, and Index.
Referenced by FLinkerTables::GetClassName(), FLinker::GetFullImpExpName(), FLinkerTables::GetImportClassName(), FLinkerTables::GetImportFullName(), FLinkerTables::GetImportPathName(), FLinker::GetPathName(), and ToImport().
IsNull()
FORCEINLINE bool FPackageIndex::IsNull () const inline
return true if this null (i.e.
neither an import nor an export)
Definition at line 78 of file ObjectResource.h.
References FORCEINLINE, and Index.
operator!=()
FORCEINLINE bool FPackageIndex::operator!= (const FPackageIndex & Other) const inline
Compare package indecies for inequality.
Definition at line 119 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
operator<()
FORCEINLINE bool FPackageIndex::operator< (const FPackageIndex & Other) const inline
Compare package indecies.
Definition at line 125 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
operator<=()
FORCEINLINE bool FPackageIndex::operator<= (const FPackageIndex & Other) const inline
Definition at line 133 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
operator==()
FORCEINLINE bool FPackageIndex::operator== (const FPackageIndex & Other) const inline
Compare package indecies for equality.
Definition at line 114 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
operator>()
FORCEINLINE bool FPackageIndex::operator> (const FPackageIndex & Other) const inline
Definition at line 129 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
operator>=()
FORCEINLINE bool FPackageIndex::operator>= (const FPackageIndex & Other) const inline
Definition at line 137 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, Index, and Other.
ToExport()
FORCEINLINE int32 FPackageIndex::ToExport () const inline
Check that this is an export and return the index into the export map.
Definition at line 89 of file ObjectResource.h.
References check, FORCEINLINE, Index, and IsExport().
Referenced by FLinkerTables::GetExportClassName(), FLinker::GetExportFullName(), and FLinker::GetExportPathName().
ToImport()
FORCEINLINE int32 FPackageIndex::ToImport () const inline
Check that this is an import and return the index into the import map.
Definition at line 83 of file ObjectResource.h.
References check, FORCEINLINE, Index, and IsImport().
Referenced by FLinkerTables::GetImportClassName(), FLinkerTables::GetImportFullName(), and FLinkerTables::GetImportPathName().
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (const FPackageIndex & In) friend
Definition at line 164 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, and Index.
LexFromString
void LexFromString (FPackageIndex & Value, const TCHAR * String) friend
Definition at line 180 of file ObjectResource.h.
References FPackageIndex(), TCString< TCHAR >::Atoi(), String, and Value.
LexToString
FString LexToString (const FPackageIndex & Value) friend
Lex functions.
Lex functions
Definition at line 175 of file ObjectResource.h.
References FPackageIndex(), and Value.
operator<< [1/2]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FPackageIndex & Value) friend
Serializes a package index value from or into an archive.
Parameters
Ar - The archive to serialize from or to.
Value - The value to serialize.
Definition at line 147 of file ObjectResource.h.
References FPackageIndex(), Ar, FORCEINLINE, FStructuredArchiveFromArchive::GetSlot(), and Value.
operator<< [2/2]
FORCEINLINE friend void operator<< (FStructuredArchive::FSlot Slot, FPackageIndex & Value) friend
Serializes a package index value from or into a structured archive slot.
Parameters
Slot - The structured archive slot to serialize from or to.
Value - The value to serialize.
Definition at line 159 of file ObjectResource.h.
References FPackageIndex(), FORCEINLINE, and Value.
Field Documentation
Index
int32 FPackageIndex::Index private
Values greater than zero indicate that this is an index into the ExportMap.
The actual array index will be (FPackageIndex - 1).
Values less than zero indicate that this is an index into the ImportMap. The actual array index will be (-FPackageIndex - 1)
Definition at line 52 of file ObjectResource.h.
Referenced by FPackageIndex(), FPackageIndex(), ForDebugging(), GetTypeHash, IsExport(), IsImport(), IsNull(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), ToExport(), and ToImport().
The documentation for this class was generated from the following file:
ObjectResource.h