Unreal Engine 5.6 C++ API: SListView< ItemType >::FWidgetGenerator Class Reference
SListView< ItemType >::FWidgetGenerator Class Reference
A WidgetGenerator is a component responsible for creating widgets from data items.
Public Member Functions
FWidgetGenerator (SListView< ItemType > *InOwnerList)
void Clear ()
Clear everything so widgets will be regenerated.
TSharedPtr< ITableRow > GetWidgetForItem (const ItemType &Item) const
Find a widget for this item if it has already been constructed.
void OnBeginGenerationPass ()
Called at the beginning of the generation pass.
void OnEndGenerationPass ()
Called at the end of the generation pass.
void OnItemSeen (ItemType InItem, TSharedRef< ITableRow > InGeneratedWidget)
Keep track of every item and corresponding widget during a generation pass.
void ProcessItemCleanUp ()
void ValidateWidgetGeneration ()
Data Fields
TArray< ItemType > ItemsToBeCleanedUp
Items that need their widgets destroyed because they are no longer on screen.
TArray< TObjectPtrWrapTypeOf< ItemType > > ItemsWithGeneratedWidgets
A set of Items that currently have a generated widget.
TMap< ItemType, TSharedRef< ITableRow >, FDefaultSetAllocator, MapKeyFuncs > ItemToWidgetMap
Map of DataItems to corresponding SWidgets.
SListView< ItemType > * OwnerList
We store a pointer to the owner list for error purposes, so when asserts occur we can report which list it happened for.
int32 TotalItemsLastGeneration
Total number of DataItems the last time we performed a generation pass.
TMap< const ITableRow *, TObjectPtrWrapTypeOf< ItemType > > WidgetMapToItem
Map of SWidgets to DataItems from which they were generated.
Detailed Description
template<typename ItemType>
class SListView< ItemType >::FWidgetGenerator
A WidgetGenerator is a component responsible for creating widgets from data items.
It also provides mapping from currently generated widgets to the data items which they represent.
Definition at line 704 of file SListView.h.
Constructor & Destructor Documentation
FWidgetGenerator()
template<typename ItemType> SListView< ItemType >::FWidgetGenerator::FWidgetGenerator (SListView< ItemType > * InOwnerList) inline
Definition at line 707 of file SListView.h.
References SListView< ItemType >::SListView(), and OwnerList.
Member Function Documentation
Clear()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::Clear () inline
Clear everything so widgets will be regenerated.
Definition at line 775 of file SListView.h.
References ItemsToBeCleanedUp, ItemsWithGeneratedWidgets, and ProcessItemCleanUp().
GetWidgetForItem()
template<typename ItemType> TSharedPtr< ITableRow > SListView< ItemType >::FWidgetGenerator::GetWidgetForItem (const ItemType & Item) const inline nodiscard
Find a widget for this item if it has already been constructed.
Parameters
Item The item for which to find the widget.
Returns
A pointer to the corresponding widget if it exists; otherwise nullptr.
Definition at line 718 of file SListView.h.
References Item, and ItemToWidgetMap.
OnBeginGenerationPass()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::OnBeginGenerationPass () inline
Called at the beginning of the generation pass.
Begins tracking of which widgets were in view and which were not (so we can clean them up)
Parameters
InNumDataItems The total number of data items being observed
Definition at line 757 of file SListView.h.
References ItemsToBeCleanedUp, and ItemsWithGeneratedWidgets.
OnEndGenerationPass()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::OnEndGenerationPass () inline
Called at the end of the generation pass.
Cleans up any widgets associated with items that were not in view this frame.
Definition at line 768 of file SListView.h.
References ProcessItemCleanUp(), and ValidateWidgetGeneration().
OnItemSeen()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::OnItemSeen (ItemType InItem, TSharedRef< ITableRow > InGeneratedWidget) inline
Keep track of every item and corresponding widget during a generation pass.
Parameters
InItem The DataItem which is in view.
InGeneratedWidget The widget generated for this item; it may have been newly generated.
Definition at line 730 of file SListView.h.
References ensure, TSharedRef< ObjectType, InMode >::Get(), ItemsToBeCleanedUp, ItemsWithGeneratedWidgets, ItemToWidgetMap, OwnerList, and WidgetMapToItem.
ProcessItemCleanUp()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::ProcessItemCleanUp () inline
Definition at line 782 of file SListView.h.
References ensureMsgf, TSharedRef< ObjectType, InMode >::Get(), Item, ItemsToBeCleanedUp, ItemToWidgetMap, OwnerList, TEXT, and WidgetMapToItem.
Referenced by Clear(), and OnEndGenerationPass().
ValidateWidgetGeneration()
template<typename ItemType> void SListView< ItemType >::FWidgetGenerator::ValidateWidgetGeneration () inline
Definition at line 826 of file SListView.h.
References checkf, TSharedRef< ObjectType, InMode >::Get(), ItemsWithGeneratedWidgets, ItemToWidgetMap, OwnerList, TEXT, UE_LOG, UPTRINT_x_FMT, Warning, and WidgetMapToItem.
Referenced by OnEndGenerationPass().
Field Documentation
ItemsToBeCleanedUp
template<typename ItemType> TArray<ItemType> SListView< ItemType >::FWidgetGenerator::ItemsToBeCleanedUp
Items that need their widgets destroyed because they are no longer on screen.
Definition at line 901 of file SListView.h.
Referenced by Clear(), OnBeginGenerationPass(), OnItemSeen(), and ProcessItemCleanUp().
ItemsWithGeneratedWidgets
template<typename ItemType> TArray< TObjectPtrWrapTypeOf<ItemType> > SListView< ItemType >::FWidgetGenerator::ItemsWithGeneratedWidgets
A set of Items that currently have a generated widget.
Definition at line 895 of file SListView.h.
Referenced by Clear(), OnBeginGenerationPass(), OnItemSeen(), and ValidateWidgetGeneration().
ItemToWidgetMap
template<typename ItemType> TMap< ItemType, TSharedRef<ITableRow>, FDefaultSetAllocator, MapKeyFuncs > SListView< ItemType >::FWidgetGenerator::ItemToWidgetMap
Map of DataItems to corresponding SWidgets.
Definition at line 889 of file SListView.h.
Referenced by GetWidgetForItem(), OnItemSeen(), ProcessItemCleanUp(), and ValidateWidgetGeneration().
OwnerList
template<typename ItemType> SListView<ItemType>* SListView< ItemType >::FWidgetGenerator::OwnerList
We store a pointer to the owner list for error purposes, so when asserts occur we can report which list it happened for.
Definition at line 886 of file SListView.h.
Referenced by FWidgetGenerator(), OnItemSeen(), ProcessItemCleanUp(), and ValidateWidgetGeneration().
TotalItemsLastGeneration
template<typename ItemType> int32 SListView< ItemType >::FWidgetGenerator::TotalItemsLastGeneration
Total number of DataItems the last time we performed a generation pass.
Definition at line 898 of file SListView.h.
WidgetMapToItem
template<typename ItemType> TMap< const ITableRow*, TObjectPtrWrapTypeOf<ItemType> > SListView< ItemType >::FWidgetGenerator::WidgetMapToItem
Map of SWidgets to DataItems from which they were generated.
Definition at line 892 of file SListView.h.
Referenced by OnItemSeen(), ProcessItemCleanUp(), and ValidateWidgetGeneration().
The documentation for this class was generated from the following file:
SListView.h