Unreal Engine 5.6 C++ API: FFileSystemError Class Reference
FFileSystemError Class Reference
Stores custom error messages from the engine along with an optional system error code that can provider more detailed information.
#include "GenericPlatformFile.h"
Public Member Functions
FFileSystemError ()=delete
FFileSystemError (const FFileSystemError &)=delete
FFileSystemError (FFileSystemError &&)=default
FFileSystemError (FString &&InErrorMessage, int32 InSystemErrorCode=0)
FString GetMessage ()
Return the error message, if a valid system error code was provided then this will be appended to the end of the message.
FFileSystemError & operator= (const FFileSystemError &)=delete
FFileSystemError & operator= (FFileSystemError &&)=default
Private Attributes
FString ErrorMessage
int32 SystemErrorCode
Friends
template<typename CharType>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, const FFileSystemError &Error)
Return the error message, if a valid system error code was provided then this will be appended to the end of the message.
Detailed Description
Stores custom error messages from the engine along with an optional system error code that can provider more detailed information.
Definition at line 279 of file GenericPlatformFile.h.
Constructor & Destructor Documentation
FFileSystemError() [1/4]
FFileSystemError::FFileSystemError () delete
Referenced by FFileSystemError(), FFileSystemError(), operator<<, operator=(), and operator=().
FFileSystemError() [2/4]
FFileSystemError::FFileSystemError (const FFileSystemError &) delete
References FFileSystemError().
FFileSystemError() [3/4]
FFileSystemError::FFileSystemError (FFileSystemError &&) default
References FFileSystemError().
FFileSystemError() [4/4]
FFileSystemError::FFileSystemError (FString && InErrorMessage, int32 InSystemErrorCode = 0) inline explicit
Definition at line 289 of file GenericPlatformFile.h.
References ErrorMessage, MoveTemp(), and SystemErrorCode.
Member Function Documentation
GetMessage()
FString FFileSystemError::GetMessage () inline
Return the error message, if a valid system error code was provided then this will be appended to the end of the message.
Definition at line 296 of file GenericPlatformFile.h.
References ErrorMessage, FAndroidMisc::GetSystemErrorMessage(), MAX_SPRINTF, SystemErrorCode, TEXT, and UE_ARRAY_COUNT.
operator=() [1/2]
FFileSystemError & FFileSystemError::operator= (const FFileSystemError &) delete
References FFileSystemError().
operator=() [2/2]
FFileSystemError & FFileSystemError::operator= (FFileSystemError &&) default
References FFileSystemError().
Friends And Related Symbol Documentation
operator<<
template<typename CharType> TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > & Builder, const FFileSystemError & Error) friend
Return the error message, if a valid system error code was provided then this will be appended to the end of the message.
Definition at line 313 of file GenericPlatformFile.h.
References FFileSystemError(), Error, FAndroidMisc::GetSystemErrorMessage(), MAX_SPRINTF, TEXT, and UE_ARRAY_COUNT.
Field Documentation
ErrorMessage
FString FFileSystemError::ErrorMessage private
Definition at line 323 of file GenericPlatformFile.h.
Referenced by FFileSystemError(), and GetMessage().
SystemErrorCode
int32 FFileSystemError::SystemErrorCode private
Definition at line 324 of file GenericPlatformFile.h.
Referenced by FFileSystemError(), and GetMessage().
The documentation for this class was generated from the following file:
GenericPlatformFile.h