Unreal Engine 5.6 C++ API: TRangeSet< ElementType > Class Template Reference
TRangeSet< ElementType > Class Template Reference
Template for range sets.
#include "RangeSet.h"
Public Member Functions
TRangeSet ()
Default constructor.
~TRangeSet ()
Destructor.
void Add (RangeType Range)
Adds a range to the set.
bool Contains (const RangeType &Range) const
Checks whether this set contains the specified range.
bool Contains (ElementValueOrConstRef Element) const
Checks whether this set contains the specified element.
void Empty ()
Removes a range from the set.
BoundsType GetMaxBound () const
Gets the range set's uppermost bound.
ElementType GetMaxBoundValue () const
Gets the value of the uppermost bound.
BoundsType GetMinBound () const
Gets the range set's lowest bound.
ElementType GetMinBoundValue () const
Gets the value of the lowest bound.
template<typename Allocator>
const void GetRanges (TArray< RangeType, Allocator > &OutRanges) const
Returns a read-only collection of the ranges contained in this set.
bool HasMaxBound () const
Checks whether the range has an uppermost bound.
bool HasMinBound () const
Checks whether the range has a lowest bound.
bool IsEmpty () const
Checks whether this range set is empty.
void Merge (const TRangeSet &Other)
Merges another range set into this set.
bool Overlaps (const RangeType &Range) const
Checks whether this range set overlaps with the specified range.
bool Overlaps (const TRangeSet &Other) const
Checks whether this range set overlaps with another.
Private Types
typedef TRangeBound< ElementType > BoundsType
typedef TCallTraits< ElementType >::ParamType ElementValueOrConstRef
typedef TRange< ElementType > RangeType
Private Attributes
TArray< RangeType > Ranges
Holds the set of ranges.
Friends
class FArchive & operator<< (class FArchive &Ar, TRangeSet &RangeSet)
Serializes the given range set from or into the specified archive.
Detailed Description
template<typename ElementType>
class TRangeSet< ElementType >
Template for range sets.
Todo
gmp: Implement more efficient storage of range sets
Definition at line 16 of file RangeSet.h.
Member Typedef Documentation
BoundsType
template<typename ElementType> typedef TRangeBound<ElementType> TRangeSet< ElementType >::BoundsType private
Definition at line 18 of file RangeSet.h.
ElementValueOrConstRef
template<typename ElementType> typedef TCallTraits<ElementType>::ParamType TRangeSet< ElementType >::ElementValueOrConstRef private
Definition at line 22 of file RangeSet.h.
RangeType
template<typename ElementType> typedef TRange<ElementType> TRangeSet< ElementType >::RangeType private
Definition at line 19 of file RangeSet.h.
Constructor & Destructor Documentation
TRangeSet()
template<typename ElementType> TRangeSet< ElementType >::TRangeSet () inline nodiscard
Default constructor.
Definition at line 27 of file RangeSet.h.
Referenced by Merge(), operator<<, and Overlaps().
~TRangeSet()
template<typename ElementType> TRangeSet< ElementType >::~TRangeSet () inline
Destructor.
Definition at line 30 of file RangeSet.h.
Member Function Documentation
Add()
template<typename ElementType> void TRangeSet< ElementType >::Add (RangeType Range) inline
Adds a range to the set.
This method merges overlapping ranges into a single range (i.e. {[1, 5], [4, 6]} becomes [1, 6]). Adjacent ranges (i.e. {[1, 4), [4, 6)} are also merged.
Parameters
Range The range to add.
Definition at line 42 of file RangeSet.h.
References TRange< ElementType >::Adjoins(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::MaxUpper(), TRangeBound< ElementType >::MinLower(), TRange< ElementType >::Overlaps(), and Ranges.
Contains() [1/2]
template<typename ElementType> bool TRangeSet< ElementType >::Contains (const RangeType & Range) const inline nodiscard
Checks whether this set contains the specified range.
Parameters
Range The range to check.
Returns
true if the set contains the range, false otherwise.
Definition at line 138 of file RangeSet.h.
References Ranges.
Contains() [2/2]
template<typename ElementType> bool TRangeSet< ElementType >::Contains (ElementValueOrConstRef Element) const inline nodiscard
Checks whether this set contains the specified element.
Parameters
Element The element to check.
Returns
true if the element is in the set, false otherwise.
Definition at line 119 of file RangeSet.h.
References Ranges.
Empty()
template<typename ElementType> void TRangeSet< ElementType >::Empty () inline
Removes a range from the set.
Ranges that overlap with the removed range will be split.
Parameters
Range The range to remove. Removes all ranges from the set.
Definition at line 106 of file RangeSet.h.
References Ranges.
GetMaxBound()
template<typename ElementType> BoundsType TRangeSet< ElementType >::GetMaxBound () const inline nodiscard
Gets the range set's uppermost bound.
Returns
Uppermost bound.
See also
GetMaxBoundValue, GetMinBound, HasMaxBound
Definition at line 192 of file RangeSet.h.
References TRangeBound< ElementType >::MaxUpper(), and Ranges.
Referenced by GetMaxBoundValue(), and HasMaxBound().
GetMaxBoundValue()
template<typename ElementType> ElementType TRangeSet< ElementType >::GetMaxBoundValue () const inline nodiscard
Gets the value of the uppermost bound.
Use HasMaxBound() to ensure that this range actually has an upper bound.
Returns
Bound value.
See also
GetMaxBound, GetMinBoundValue, HasMaxBound
Definition at line 216 of file RangeSet.h.
References GetMaxBound(), and TRangeBound< ElementType >::GetValue().
GetMinBound()
template<typename ElementType> BoundsType TRangeSet< ElementType >::GetMinBound () const inline nodiscard
Gets the range set's lowest bound.
Returns
Lowest bound.
See also
GetMaxBound, GetMinBoundValue, HasMinBound
Definition at line 157 of file RangeSet.h.
References TRangeBound< ElementType >::MinLower(), and Ranges.
Referenced by GetMinBoundValue(), and HasMinBound().
GetMinBoundValue()
template<typename ElementType> ElementType TRangeSet< ElementType >::GetMinBoundValue () const inline nodiscard
Gets the value of the lowest bound.
Use HasMinBound() to ensure that this range set actually has a lowest bound.
Returns
Bound value.
See also
GetMaxBoundValue, GetMinBound, HasMinBound
Definition at line 181 of file RangeSet.h.
References GetMinBound(), and TRangeBound< ElementType >::GetValue().
GetRanges()
template<typename ElementType> template<typename Allocator> const void TRangeSet< ElementType >::GetRanges (TArray< RangeType, Allocator > & OutRanges) const inline
Returns a read-only collection of the ranges contained in this set.
Parameters
Allocator The array allocator to use.
OutRanges Will contain the collection of ranges.
Definition at line 229 of file RangeSet.h.
References Ranges.
HasMaxBound()
template<typename ElementType> bool TRangeSet< ElementType >::HasMaxBound () const inline nodiscard
Checks whether the range has an uppermost bound.
Returns
true if the range has an uppermost bound, false otherwise.
See also
GetUpperBound, GetUpperBoundValue, HasMinBound
Definition at line 251 of file RangeSet.h.
References GetMaxBound(), and TRangeBound< ElementType >::IsClosed().
HasMinBound()
template<typename ElementType> bool TRangeSet< ElementType >::HasMinBound () const inline nodiscard
Checks whether the range has a lowest bound.
Returns
true if the range has a lowest bound, false otherwise.
See also
GetMinBound, GetMinBoundValue, HasMaxBound
Definition at line 240 of file RangeSet.h.
References GetMinBound(), and TRangeBound< ElementType >::IsClosed().
IsEmpty()
template<typename ElementType> bool TRangeSet< ElementType >::IsEmpty () const inline nodiscard
Checks whether this range set is empty.
Returns
true if the range set is empty, false otherwise.
Definition at line 261 of file RangeSet.h.
References Ranges.
Merge()
template<typename ElementType> void TRangeSet< ElementType >::Merge (const TRangeSet< ElementType > & Other) inline
Merges another range set into this set.
Parameters
Other The range set to merge.
Definition at line 67 of file RangeSet.h.
References TRangeSet(), Add, and Other.
Overlaps() [1/2]
template<typename ElementType> bool TRangeSet< ElementType >::Overlaps (const RangeType & Range) const inline nodiscard
Checks whether this range set overlaps with the specified range.
Parameters
Range The range to check.
Returns
true if this set overlaps with the range, false otherwise.
Definition at line 272 of file RangeSet.h.
References Ranges.
Referenced by Overlaps().
Overlaps() [2/2]
template<typename ElementType> bool TRangeSet< ElementType >::Overlaps (const TRangeSet< ElementType > & Other) const inline nodiscard
Checks whether this range set overlaps with another.
Parameters
Other The other range set.
Returns
true if the range sets overlap, false otherwise.
Todo
gmp: This could be optimized to O(n*logn) using a line sweep on a pre-sorted array of bounds.
Definition at line 293 of file RangeSet.h.
References TRangeSet(), Other, and Overlaps().
Friends And Related Symbol Documentation
operator<<
template<typename ElementType> class FArchive & operator<< (class FArchive & Ar, TRangeSet< ElementType > & RangeSet) friend
Serializes the given range set from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
RangeSet The range set to serialize.
Returns
The archive.
Definition at line 315 of file RangeSet.h.
References TRangeSet(), Ar, and Ranges.
Field Documentation
Ranges
template<typename ElementType> TArray<RangeType> TRangeSet< ElementType >::Ranges private
Holds the set of ranges.
Definition at line 323 of file RangeSet.h.
Referenced by Add(), Contains(), Contains(), Empty(), GetMaxBound(), GetMinBound(), GetRanges(), IsEmpty(), operator<<, and Overlaps().
The documentation for this class was generated from the following file:
RangeSet.h