Unreal Engine 5.6 C++ API: FDurationAtomicTimer Class Reference
FDurationAtomicTimer Class Reference
Utility stopwatch class for tracking the duration of some action (tracks time in seconds and adds it to the specified variable on destruction), when the storage is std::atomic<double>.
#include "ScopedTimers.h"
Public Member Functions
FDurationAtomicTimer (std::atomic< double > &AccumulatorIn, std::memory_order InMemoryOrder=std::memory_order_relaxed)
double Start ()
double Stop ()
Protected Attributes
std::atomic< double > & Accumulator
Time variable to update.
std::memory_order MemoryOrder
Memory order specified in constructor and passed to fetch_add.
double StartTime
Start time, captured in ctor.
Detailed Description
Utility stopwatch class for tracking the duration of some action (tracks time in seconds and adds it to the specified variable on destruction), when the storage is std::atomic<double>.
Definition at line 108 of file ScopedTimers.h.
Constructor & Destructor Documentation
FDurationAtomicTimer()
FDurationAtomicTimer::FDurationAtomicTimer (std::atomic< double > & AccumulatorIn, std::memory_order InMemoryOrder = std::memory_order_relaxed) inline explicit
Definition at line 111 of file ScopedTimers.h.
References Accumulator, MemoryOrder, Seconds, and StartTime.
Referenced by FScopedDurationAtomicTimer::FScopedDurationAtomicTimer().
Member Function Documentation
Start()
double FDurationAtomicTimer::Start () inline
Definition at line 118 of file ScopedTimers.h.
References FAndroidTime::Seconds(), and StartTime.
Stop()
double FDurationAtomicTimer::Stop () inline
Definition at line 124 of file ScopedTimers.h.
References Accumulator, AtomicDoubleFetchAdd(), MemoryOrder, FAndroidTime::Seconds(), and StartTime.
Referenced by FScopedDurationAtomicTimer::~FScopedDurationAtomicTimer().
Field Documentation
Accumulator
std::atomic<double>& FDurationAtomicTimer::Accumulator protected
Time variable to update.
Definition at line 137 of file ScopedTimers.h.
Referenced by FDurationAtomicTimer(), and Stop().
MemoryOrder
std::memory_order FDurationAtomicTimer::MemoryOrder protected
Memory order specified in constructor and passed to fetch_add.
Definition at line 139 of file ScopedTimers.h.
Referenced by FDurationAtomicTimer(), and Stop().
StartTime
double FDurationAtomicTimer::StartTime protected
Start time, captured in ctor.
Definition at line 135 of file ScopedTimers.h.
Referenced by FDurationAtomicTimer(), Start(), and Stop().
The documentation for this class was generated from the following file:
ScopedTimers.h