Unreal Engine 5.6 C++ API: UE::StructuredArchive::Private Namespace Reference
UE::StructuredArchive::Private Namespace Reference
Data Structures
struct FElementId
class FSlotBase
class FSlotPosition
struct TNamedAttribute
Class to contain a named attribute for serialization.
struct TNamedValue
Class to contain a named value for serialization.
struct TOptionalNamedAttribute
Class to contain a named attribute for serialization, with a default.
Enumerations
enum class EElementType : unsigned char {
Root , Record , Array , Stream ,
Map , AttributedValue
}
enum class EEnteringAttributeState { NotEnteringAttribute , EnteringAttribute }
Functions
FElementId GetCurrentSlotElementIdImpl (FStructuredArchive &Ar)
FArchiveFormatterType & GetFormatterImpl (FStructuredArchive &Ar)
FORCEINLINE FArchive & GetUnderlyingArchiveImpl (FStructuredArchive &StructuredArchive)
FORCEINLINE FArchiveState & GetUnderlyingArchiveStateImpl (FStructuredArchive &StructuredArchive)
template<typename T>
FORCEINLINE TNamedAttribute< T > MakeNamedAttribute (FArchiveFieldName Name, T &Value)
template<typename T>
FORCEINLINE TNamedValue< T > MakeNamedValue (FArchiveFieldName Name, T &Value)
template<typename T>
FORCEINLINE TOptionalNamedAttribute< T > MakeOptionalNamedAttribute (FArchiveFieldName Name, T &Value, const typename TIdentity< T >::Type &Default)
Enumeration Type Documentation
EElementType
enum class UE::StructuredArchive::Private::EElementType : unsigned char strong
Enumerator
Root
Record
Array
Stream
Map
AttributedValue
Definition at line 30 of file StructuredArchive.h.
EEnteringAttributeState
enum class UE::StructuredArchive::Private::EEnteringAttributeState strong
Enumerator
NotEnteringAttribute
EnteringAttribute
Definition at line 40 of file StructuredArchive.h.
Function Documentation
GetCurrentSlotElementIdImpl()
FElementId UE::StructuredArchive::Private::GetCurrentSlotElementIdImpl (FStructuredArchive & Ar)
References Ar.
GetFormatterImpl()
FArchiveFormatterType & UE::StructuredArchive::Private::GetFormatterImpl (FStructuredArchive & Ar)
Definition at line 251 of file StructuredArchive.h.
References FORCEINLINE.
Referenced by FStructuredArchiveSlot::EnterArray(), FStructuredArchiveSlot::EnterAttribute(), FStructuredArchiveMap::EnterElement(), FStructuredArchiveSlot::EnterMap(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::operator<<(), FStructuredArchiveSlot::Serialize(), FStructuredArchiveSlot::Serialize(), FStructuredArchiveSlot::TryEnterAttribute(), and FStructuredArchiveRecord::TryEnterField().
GetUnderlyingArchiveImpl()
FORCEINLINE FArchive & UE::StructuredArchive::Private::GetUnderlyingArchiveImpl (FStructuredArchive & StructuredArchive)
Definition at line 234 of file StructuredArchive.h.
References FORCEINLINE.
GetUnderlyingArchiveStateImpl()
FORCEINLINE FArchiveState & UE::StructuredArchive::Private::GetUnderlyingArchiveStateImpl (FStructuredArchive & StructuredArchive)
Definition at line 239 of file StructuredArchive.h.
References FORCEINLINE.
MakeNamedAttribute()
template<typename T> FORCEINLINE TNamedAttribute< T > UE::StructuredArchive::Private::MakeNamedAttribute (FArchiveFieldName Name, T & Value)
Definition at line 64 of file StructuredArchiveNameHelpers.h.
References FORCEINLINE, Name, and Value.
MakeNamedValue()
template<typename T> FORCEINLINE TNamedValue< T > UE::StructuredArchive::Private::MakeNamedValue (FArchiveFieldName Name, T & Value)
Definition at line 58 of file StructuredArchiveNameHelpers.h.
References FORCEINLINE, Name, and Value.
MakeOptionalNamedAttribute()
template<typename T> FORCEINLINE TOptionalNamedAttribute< T > UE::StructuredArchive::Private::MakeOptionalNamedAttribute (FArchiveFieldName Name, T & Value, const typename TIdentity< T >::Type & Default)
Definition at line 70 of file StructuredArchiveNameHelpers.h.
References Default, FORCEINLINE, Name, and Value.