Unreal Engine 5.6 C++ API: FNumberParsingOptions Struct Reference
FNumberParsingOptions Struct Reference
#include "Text.h"
Public Member Functions
FNumberParsingOptions ()
bool IsIdentical (const FNumberParsingOptions &Other) const
Check to see if our parsing options match the other parsing options.
FNumberParsingOptions & SetInsideLimits (bool InValue)
FNumberParsingOptions & SetUseClamping (bool InValue)
FNumberParsingOptions & SetUseGrouping (bool InValue)
Static Public Member Functions
static const FNumberParsingOptions & DefaultNoGrouping ()
Get the default number parsing options with grouping disabled.
static const FNumberParsingOptions & DefaultWithGrouping ()
Get the default number parsing options with grouping enabled.
Data Fields
bool InsideLimits
The number needs to be representable inside its type limits to be considered valid.
bool UseClamping
Clamp the parsed value to its type limits.
bool UseGrouping
Friends
uint32 GetTypeHash (const FNumberParsingOptions &Key)
Get the hash code to use for the given parsing options.
void operator<< (FStructuredArchive::FSlot Slot, FNumberParsingOptions &Value)
Detailed Description
Definition at line 241 of file Text.h.
Constructor & Destructor Documentation
FNumberParsingOptions()
FNumberParsingOptions::FNumberParsingOptions ()
Referenced by DefaultNoGrouping(), DefaultWithGrouping(), GetTypeHash, IsIdentical(), operator<<, SetInsideLimits(), SetUseClamping(), and SetUseGrouping().
Member Function Documentation
DefaultNoGrouping()
const FNumberParsingOptions & FNumberParsingOptions::DefaultNoGrouping () static
Get the default number parsing options with grouping disabled.
References FNumberParsingOptions().
DefaultWithGrouping()
const FNumberParsingOptions & FNumberParsingOptions::DefaultWithGrouping () static
Get the default number parsing options with grouping enabled.
References FNumberParsingOptions().
IsIdentical()
bool FNumberParsingOptions::IsIdentical (const FNumberParsingOptions & Other) const
Check to see if our parsing options match the other parsing options.
References FNumberParsingOptions(), and Other.
SetInsideLimits()
FNumberParsingOptions & FNumberParsingOptions::SetInsideLimits (bool InValue) inline
Definition at line 250 of file Text.h.
References FNumberParsingOptions(), and InsideLimits.
SetUseClamping()
FNumberParsingOptions & FNumberParsingOptions::SetUseClamping (bool InValue) inline
Definition at line 254 of file Text.h.
References FNumberParsingOptions(), and UseClamping.
Referenced by TDefaultNumericTypeInterface< NumericType >::FromString().
SetUseGrouping()
FNumberParsingOptions & FNumberParsingOptions::SetUseGrouping (bool InValue) inline
Definition at line 246 of file Text.h.
References FNumberParsingOptions(), and UseGrouping.
Referenced by TDefaultNumericTypeInterface< NumericType >::FromString().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNumberParsingOptions & Key) friend
Get the hash code to use for the given parsing options.
References FNumberParsingOptions(), and Key.
operator<<
void operator<< (FStructuredArchive::FSlot Slot, FNumberParsingOptions & Value) friend
References FNumberParsingOptions(), and Value.
Field Documentation
InsideLimits
bool FNumberParsingOptions::InsideLimits
The number needs to be representable inside its type limits to be considered valid.
Definition at line 249 of file Text.h.
Referenced by SetInsideLimits().
UseClamping
bool FNumberParsingOptions::UseClamping
Clamp the parsed value to its type limits.
Definition at line 253 of file Text.h.
Referenced by SetUseClamping().
UseGrouping
bool FNumberParsingOptions::UseGrouping
Definition at line 245 of file Text.h.
Referenced by SetUseGrouping().
The documentation for this struct was generated from the following file:
Text.h