Unreal Engine 5.6 C++ API: FSendRenderDynamicDataPrimitivesQueue Struct Reference
FSendRenderDynamicDataPrimitivesQueue Struct Reference
#include "AsyncRegisterLevelContext.h"
Private Types
using FPrimitiveBatch = TArray<TWeakObjectPtr<UPrimitiveComponent>, FConcurrentLinearArrayAllocator>
Private Member Functions
FSendRenderDynamicDataPrimitivesQueue (FAsyncRegisterLevelContext &InContext)
~FSendRenderDynamicDataPrimitivesQueue ()
void AddSendRenderDynamicData (UPrimitiveComponent *InComponent)
void Flush ()
bool HasRemainingWork () const
bool IsRunningAsync () const
void Push (FPrimitiveBatch &InSendRenderDynamicDataPrimitives)
bool Tick ()
void WaitForAsyncTask ()
Private Attributes
FAsyncRegisterLevelContext & Context
friend FAsyncRegisterLevelContext
FPrimitiveBatch NextBatch
TArray< FPrimitiveBatch > SendRenderDynamicDataPrimitivesArray
Detailed Description
Definition at line 50 of file AsyncRegisterLevelContext.h.
Member Typedef Documentation
FPrimitiveBatch
using FSendRenderDynamicDataPrimitivesQueue::FPrimitiveBatch = TArray<TWeakObjectPtr<UPrimitiveComponent>, FConcurrentLinearArrayAllocator> private
Definition at line 55 of file AsyncRegisterLevelContext.h.
Constructor & Destructor Documentation
FSendRenderDynamicDataPrimitivesQueue()
FSendRenderDynamicDataPrimitivesQueue::FSendRenderDynamicDataPrimitivesQueue (FAsyncRegisterLevelContext & InContext) private
Definition at line 369 of file AsyncRegisterLevelContext.cpp.
References Context, and FAsyncRegisterLevelContext.
~FSendRenderDynamicDataPrimitivesQueue()
FSendRenderDynamicDataPrimitivesQueue::~FSendRenderDynamicDataPrimitivesQueue () private
Definition at line 373 of file AsyncRegisterLevelContext.cpp.
References check, and HasRemainingWork().
Member Function Documentation
AddSendRenderDynamicData()
void FSendRenderDynamicDataPrimitivesQueue::AddSendRenderDynamicData (UPrimitiveComponent * InComponent) private
Definition at line 378 of file AsyncRegisterLevelContext.cpp.
References checkSlow, Flush(), NextBatch, and LevelStreaming::AsyncRegisterLevelContext::PrimitiveBatchSize.
Flush()
void FSendRenderDynamicDataPrimitivesQueue::Flush () private
Definition at line 388 of file AsyncRegisterLevelContext.cpp.
References check, NextBatch, and Push().
Referenced by AddSendRenderDynamicData().
HasRemainingWork()
bool FSendRenderDynamicDataPrimitivesQueue::HasRemainingWork () const private
Definition at line 425 of file AsyncRegisterLevelContext.cpp.
References NextBatch, and SendRenderDynamicDataPrimitivesArray.
Referenced by ~FSendRenderDynamicDataPrimitivesQueue(), and Tick().
IsRunningAsync()
bool FSendRenderDynamicDataPrimitivesQueue::IsRunningAsync () const inline private
Definition at line 60 of file AsyncRegisterLevelContext.h.
Push()
void FSendRenderDynamicDataPrimitivesQueue::Push (FPrimitiveBatch & InSendRenderDynamicDataPrimitives) private
Definition at line 397 of file AsyncRegisterLevelContext.cpp.
References check, TArray< InElementType, InAllocatorType >::IsEmpty(), MoveTemp(), and SendRenderDynamicDataPrimitivesArray.
Referenced by Flush().
Tick()
bool FSendRenderDynamicDataPrimitivesQueue::Tick () private
Definition at line 403 of file AsyncRegisterLevelContext.cpp.
References HasRemainingWork(), MoveTemp(), No, and SendRenderDynamicDataPrimitivesArray.
WaitForAsyncTask()
void FSendRenderDynamicDataPrimitivesQueue::WaitForAsyncTask () inline private
Definition at line 62 of file AsyncRegisterLevelContext.h.
Field Documentation
Context
FAsyncRegisterLevelContext& FSendRenderDynamicDataPrimitivesQueue::Context private
Definition at line 64 of file AsyncRegisterLevelContext.h.
Referenced by FSendRenderDynamicDataPrimitivesQueue().
FAsyncRegisterLevelContext
friend FSendRenderDynamicDataPrimitivesQueue::FAsyncRegisterLevelContext private
Definition at line 67 of file AsyncRegisterLevelContext.h.
Referenced by FSendRenderDynamicDataPrimitivesQueue().
NextBatch
FPrimitiveBatch FSendRenderDynamicDataPrimitivesQueue::NextBatch private
Definition at line 65 of file AsyncRegisterLevelContext.h.
Referenced by AddSendRenderDynamicData(), Flush(), and HasRemainingWork().
SendRenderDynamicDataPrimitivesArray
TArray<FPrimitiveBatch> FSendRenderDynamicDataPrimitivesQueue::SendRenderDynamicDataPrimitivesArray private
Definition at line 66 of file AsyncRegisterLevelContext.h.
Referenced by HasRemainingWork(), Push(), and Tick().
The documentation for this struct was generated from the following files:
AsyncRegisterLevelContext.h
AsyncRegisterLevelContext.cpp