Unreal Engine 5.6 C++ API: FDynamicSpriteEmitterData Struct Reference
FDynamicSpriteEmitterData Struct Reference
Dynamic emitter data for sprite emitters.
#include "ParticleHelper.h"
Public Member Functions
FDynamicSpriteEmitterData (const UParticleModuleRequired *RequiredModule)
~FDynamicSpriteEmitterData ()
virtual void GatherSimpleLights (const FParticleSystemSceneProxy *Proxy, const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const override
Gathers simple lights for this emitter.
virtual void GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy *Proxy, const FSceneView *View, const FSceneViewFamily &ViewFamily, int32 ViewIndex, FMeshElementCollector &Collector) const override
virtual int32 GetDynamicParameterVertexStride () const override
Get the vertex stride for the dynamic parameter rendering data.
virtual int32 GetDynamicVertexStride (ERHIFeatureLevel::Type InFeatureLevel) const override
Get the vertex stride for the dynamic rendering data.
virtual const FDynamicEmitterReplayDataBase & GetSource () const override
Returns the source data for this particle system.
virtual const FDynamicSpriteEmitterReplayDataBase * GetSourceData () const override
Get the source replay data for this emitter.
bool GetVertexAndIndexData (void *VertexData, void *DynamicParameterVertexData, void *FillIndexData, FParticleOrder *ParticleOrder, const FVector &InCameraPosition, const FMatrix &InLocalToWorld, uint32 InstanceFactor) const
Retrieve the vertex and (optional) index required to render this emitter.
void Init (bool bInSelected)
Initialize this emitter's dynamic rendering data, called after source data has been filled in.
UE_DEPRECATED (4.25, "Non-instanced path is being removed") bool GetVertexAndIndexDataNonInstanced(void *VertexData
Retrieve the vertex and (optional) index required to render this emitter.
virtual void UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy *InOwnerProxy) override
Create the render thread resources for this emitter data.
Public Member Functions inherited from FDynamicSpriteEmitterDataBase
FDynamicSpriteEmitterDataBase (const UParticleModuleRequired *RequiredModule)
virtual ~FDynamicSpriteEmitterDataBase ()
void BuildViewFillData (const FParticleSystemSceneProxy *Proxy, const FSceneView *InView, int32 InVertexCount, int32 InVertexSize, int32 InDynamicParameterVertexSize, FGlobalDynamicIndexBuffer &DynamicIndexBuffer, FGlobalDynamicVertexBuffer &DynamicVertexBuffer, FGlobalDynamicVertexBufferAllocation &DynamicVertexAllocation, FGlobalDynamicIndexBufferAllocation &DynamicIndexAllocation, FGlobalDynamicVertexBufferAllocation *DynamicParameterAllocation, FAsyncBufferFillData &Data) const
Set up an buffer for async filling.
virtual void DoBufferFill (FAsyncBufferFillData &Me) const
virtual void GetIndexAllocInfo (int32 &OutNumIndices, int32 &OutStride) const
Gets the information required for allocating this emitters indices from the global index array.
const FMaterialRenderProxy * GetMaterialRenderProxy ()
Retrieve the material render proxy to use for rendering this emitter.
virtual void RenderDebug (const FParticleSystemSceneProxy *Proxy, FPrimitiveDrawInterface *PDI, const FSceneView *View, bool bCrosses) const
Debug rendering.
void SortSpriteParticles (int32 SortMode, bool bLocalSpace, int32 ParticleCount, const uint8 *ParticleData, int32 ParticleStride, const uint16 *ParticleIndices, const FSceneView *View, const FMatrix &LocalToWorld, FParticleOrder *ParticleOrder) const
Sort the given sprite particles.
Public Member Functions inherited from FDynamicEmitterDataBase
FDynamicEmitterDataBase (const class UParticleModuleRequired *RequiredModule)
virtual ~FDynamicEmitterDataBase ()
virtual const FMacroUVOverride & GetMacroUVOverride () const
Returns the current macro uv override.
void operator delete (void *RawMemory, size_t Size)
void * operator new (size_t Size)
Custom new/delete with recycling.
virtual void ReleaseRenderThreadResources (const FParticleSystemSceneProxy *InOwnerProxy)
Release the render thread resources for this emitter data.
Data Fields
void void FParticleOrder const FVector const FMatrix int32 NumVerticesPerParticle const
void * DynamicParameterVertexData
void void * FillIndexData
void void FParticleOrder const FVector & InCameraPosition
void void FParticleOrder const FVector const FMatrix & InLocalToWorld
void void FParticleOrder * ParticleOrder
FDynamicSpriteEmitterReplayData Source
The frame source data for this particle system.
FParticleSpriteUniformParameters UniformParameters
Uniform parameters.
Data Fields inherited from FDynamicSpriteEmitterDataBase
uint32 bUsesDynamicParameter:1
true if the particle emitter utilizes the DynamicParameter module
const FMaterialRenderProxy * MaterialResource
The material render proxy for this emitter.
Data Fields inherited from FDynamicEmitterDataBase
uint32 bSelected:1
true if this emitter is currently selected
uint32 bValid:1
true if this emitter has valid rendering data
int32 EmitterIndex
TStatId StatID
Stat id of this object, 0 if nobody asked for it yet.
Detailed Description
Dynamic emitter data for sprite emitters.
Definition at line 1508 of file ParticleHelper.h.
Constructor & Destructor Documentation
FDynamicSpriteEmitterData()
FDynamicSpriteEmitterData::FDynamicSpriteEmitterData (const UParticleModuleRequired * RequiredModule) inline
Definition at line 1510 of file ParticleHelper.h.
References FDynamicSpriteEmitterDataBase::FDynamicSpriteEmitterDataBase().
~FDynamicSpriteEmitterData()
FDynamicSpriteEmitterData::~FDynamicSpriteEmitterData () inline
Definition at line 1515 of file ParticleHelper.h.
Member Function Documentation
GatherSimpleLights()
virtual void FDynamicSpriteEmitterData::GatherSimpleLights (const FParticleSystemSceneProxy * Proxy, const FSceneViewFamily & ViewFamily, FSimpleLightArray & OutParticleLights) const override virtual
Gathers simple lights for this emitter.
Reimplemented from FDynamicEmitterDataBase.
References const, and GatherSimpleLights().
Referenced by GatherSimpleLights().
GetDynamicMeshElementsEmitter()
virtual void FDynamicSpriteEmitterData::GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy * Proxy, const FSceneView * View, const FSceneViewFamily & ViewFamily, int32 ViewIndex, FMeshElementCollector & Collector) const override virtual
Reimplemented from FDynamicEmitterDataBase.
References const, and GetDynamicMeshElementsEmitter().
Referenced by GetDynamicMeshElementsEmitter().
GetDynamicParameterVertexStride()
virtual int32 FDynamicSpriteEmitterData::GetDynamicParameterVertexStride () const inline override virtual
Get the vertex stride for the dynamic parameter rendering data.
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 1533 of file ParticleHelper.h.
GetDynamicVertexStride()
virtual int32 FDynamicSpriteEmitterData::GetDynamicVertexStride (ERHIFeatureLevel::Type InFeatureLevel) const inline override virtual
Get the vertex stride for the dynamic rendering data.
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 1525 of file ParticleHelper.h.
GetSource()
virtual const FDynamicEmitterReplayDataBase & FDynamicSpriteEmitterData::GetSource () const inline override virtual
Returns the source data for this particle system.
Implements FDynamicEmitterDataBase.
Definition at line 1592 of file ParticleHelper.h.
References const, GetSource(), and Source.
Referenced by GetSource().
GetSourceData()
virtual const FDynamicSpriteEmitterReplayDataBase * FDynamicSpriteEmitterData::GetSourceData () const inline override virtual
Get the source replay data for this emitter.
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 1541 of file ParticleHelper.h.
References Source.
GetVertexAndIndexData()
bool FDynamicSpriteEmitterData::GetVertexAndIndexData (void * VertexData, void * DynamicParameterVertexData, void * FillIndexData, FParticleOrder * ParticleOrder, const FVector & InCameraPosition, const FMatrix & InLocalToWorld, uint32 InstanceFactor) const
Retrieve the vertex and (optional) index required to render this emitter.
Render-thread only
Parameters
VertexData The memory to fill the vertex data into
FillIndexData The index data to fill in
ParticleOrder The (optional) particle ordering to use
InCameraPosition The position of the camera in world space.
InLocalToWorld Transform from local to world space.
InstanceFactor The factor to duplicate instances by.
Returns
bool true if successful, false if failed
References DynamicParameterVertexData, FillIndexData, FVector, InCameraPosition, InLocalToWorld, and ParticleOrder.
Init()
void FDynamicSpriteEmitterData::Init (bool bInSelected)
Initialize this emitter's dynamic rendering data, called after source data has been filled in.
UE_DEPRECATED()
FDynamicSpriteEmitterData::UE_DEPRECATED (4. 25, "Non-instanced path is being removed")
Retrieve the vertex and (optional) index required to render this emitter.
This version for non-instanced platforms. Render-thread only
Parameters
VertexData The memory to fill the vertex data into
FillIndexData The index data to fill in
ParticleOrder The (optional) particle ordering to use
InCameraPosition The position of the camera in world space.
InLocalToWorld Transform from local to world space.
Returns
bool true if successful, false if failed
UpdateRenderThreadResourcesEmitter()
virtual void FDynamicSpriteEmitterData::UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy * InOwnerProxy) override virtual
Create the render thread resources for this emitter data.
Parameters
InOwnerProxy The proxy that owns this dynamic emitter data
Returns
bool true if successful, false if failed
Reimplemented from FDynamicEmitterDataBase.
References const, and UpdateRenderThreadResourcesEmitter().
Referenced by UpdateRenderThreadResourcesEmitter().
Field Documentation
const
void void FParticleOrder const FVector const FMatrix int32 NumVerticesPerParticle FDynamicSpriteEmitterData::const
Definition at line 1575 of file ParticleHelper.h.
Referenced by GatherSimpleLights(), GetDynamicMeshElementsEmitter(), GetSource(), and UpdateRenderThreadResourcesEmitter().
DynamicParameterVertexData
void* FDynamicSpriteEmitterData::DynamicParameterVertexData
Definition at line 1575 of file ParticleHelper.h.
Referenced by GetVertexAndIndexData().
FillIndexData
void void* FDynamicSpriteEmitterData::FillIndexData
Definition at line 1575 of file ParticleHelper.h.
Referenced by GetVertexAndIndexData().
InCameraPosition
void void FParticleOrder const FVector& FDynamicSpriteEmitterData::InCameraPosition
Definition at line 1575 of file ParticleHelper.h.
Referenced by GetVertexAndIndexData().
InLocalToWorld
void void FParticleOrder const FVector const FMatrix& FDynamicSpriteEmitterData::InLocalToWorld
Definition at line 1575 of file ParticleHelper.h.
Referenced by GetVertexAndIndexData().
ParticleOrder
void void FParticleOrder* FDynamicSpriteEmitterData::ParticleOrder
Definition at line 1575 of file ParticleHelper.h.
Referenced by GetVertexAndIndexData().
Source
FDynamicSpriteEmitterReplayData FDynamicSpriteEmitterData::Source
The frame source data for this particle system.
This is everything needed to represent this this particle system frame. It does not include any transient rendering thread data. Also, for non-simulating 'replay' particle systems, this data may have come straight from disk!
Definition at line 1600 of file ParticleHelper.h.
Referenced by GetSource(), and GetSourceData().
UniformParameters
FParticleSpriteUniformParameters FDynamicSpriteEmitterData::UniformParameters
Uniform parameters.
Most fields are filled in when updates are sent to the rendering thread, some are per-view!
Definition at line 1603 of file ParticleHelper.h.
The documentation for this struct was generated from the following file:
ParticleHelper.h