Unreal Engine 5.6 C++ API: Metasound::FBasicNode Class Reference
Metasound::FBasicNode Class Reference
#include "MetasoundBasicNode.h"
Public Member Functions
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
virtual FOperatorFactorySharedRef GetDefaultOperatorFactory () const =0
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Private Attributes
TSharedRef< const FNodeClassMetadata > ClassMetadata
FNodeData NodeData
Detailed Description
Definition at line 12 of file MetasoundBasicNode.h.
Constructor & Destructor Documentation
FBasicNode()
METASOUNDGRAPHCORE_API Metasound::FBasicNode::FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
Parameters
InNodeData - Information unique to this node instance.
InClassMetadata - Shared object representing the node class.
References UE_API.
Referenced by Metasound::FNodeFacade::FNodeFacade(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode(), and Metasound::TVariableNode< DataType >::TVariableNode().
~FBasicNode()
virtual Metasound::FBasicNode::~FBasicNode () virtual default
Member Function Documentation
GetInstanceID()
virtual METASOUNDGRAPHCORE_API const FGuid & Metasound::FBasicNode::GetInstanceID () const override virtual
Return the ID of this specific instance of the node class.
Implements Metasound::INodeBase.
References UE_API.
GetInstanceName()
virtual METASOUNDGRAPHCORE_API const FName & Metasound::FBasicNode::GetInstanceName () const override virtual
Return the name of this specific instance of the node class.
Implements Metasound::INodeBase.
References UE_API.
GetMetadata()
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & Metasound::FBasicNode::GetMetadata () const override virtual
Return metadata associated with this node.
Implements Metasound::INodeBase.
References UE_API.
GetOperatorData()
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > Metasound::FBasicNode::GetOperatorData () const override virtual
Return the configuration for this node.
References UE_API.
GetVertexInterface()
virtual METASOUNDGRAPHCORE_API const FVertexInterface & Metasound::FBasicNode::GetVertexInterface () const override virtual
Return the interface associated with this node instance.
Implements Metasound::INodeBase.
References UE_API.
SetDefaultInput()
virtual METASOUNDGRAPHCORE_API void Metasound::FBasicNode::SetDefaultInput (const FVertexName & InVertexName, const FLiteral & InLiteral) override virtual
Set the default literal for an input vertex.
Reimplemented from Metasound::INodeBase.
References UE_API.
Field Documentation
ClassMetadata
TSharedRef<const FNodeClassMetadata> Metasound::FBasicNode::ClassMetadata private
Definition at line 45 of file MetasoundBasicNode.h.
NodeData
FNodeData Metasound::FBasicNode::NodeData private
Definition at line 44 of file MetasoundBasicNode.h.
The documentation for this class was generated from the following file:
MetasoundBasicNode.h