Unreal Engine 5.6 C++ API: FAISightTarget Struct Reference
FAISightTarget Struct Reference
#include "AISense_Sight.h"
Public Types
typedef uint32 FTargetId
Public Member Functions
AIMODULE_API FAISightTarget (AActor *InTarget=NULL, FGenericTeamId InTeamId=FGenericTeamId::NoTeam)
FORCEINLINE FVector GetLocationSimple () const
FORCEINLINE const AActor * GetTargetActor () const
UE_DEPRECATED_FORGAME (5.5, "SightTargetInterface is deprecated. Use WeakSightTargetInterface instead.") IAISightTargetInterface *SightTargetInterface
Data Fields
TWeakObjectPtr< AActor > Target
FTargetId TargetId
FGenericTeamId TeamId
TWeakInterfacePtr< IAISightTargetInterface > WeakSightTargetInterface
Static Public Attributes
static AIMODULE_API const FTargetId InvalidTargetId
Detailed Description
Definition at line 51 of file AISense_Sight.h.
Member Typedef Documentation
FTargetId
typedef uint32 FAISightTarget::FTargetId
Definition at line 53 of file AISense_Sight.h.
Constructor & Destructor Documentation
FAISightTarget()
AIMODULE_API FAISightTarget::FAISightTarget (AActor * InTarget = NULL, FGenericTeamId InTeamId = FGenericTeamId::NoTeam)
References FAISightTarget().
Referenced by FAISightTarget().
Member Function Documentation
GetLocationSimple()
FORCEINLINE FVector FAISightTarget::GetLocationSimple () const inline
Definition at line 66 of file AISense_Sight.h.
References FORCEINLINE, FVector, GetLocationSimple(), Target, and UE::Math::TVector< double >::ZeroVector.
Referenced by GetLocationSimple().
GetTargetActor()
FORCEINLINE const AActor * FAISightTarget::GetTargetActor () const inline
Definition at line 72 of file AISense_Sight.h.
References FORCEINLINE, and Target.
UE_DEPRECATED_FORGAME()
FAISightTarget::UE_DEPRECATED_FORGAME (5. 5, "SightTargetInterface is deprecated. Use WeakSightTargetInterface instead.")
Field Documentation
InvalidTargetId
AIMODULE_API const FTargetId FAISightTarget::InvalidTargetId static
Definition at line 54 of file AISense_Sight.h.
Referenced by FAISightQuery::FAISightQuery(), and FAISightQueryID::FAISightQueryID().
Target
TWeakObjectPtr<AActor> FAISightTarget::Target
Definition at line 56 of file AISense_Sight.h.
Referenced by GetLocationSimple(), and GetTargetActor().
TargetId
FTargetId FAISightTarget::TargetId
Definition at line 59 of file AISense_Sight.h.
TeamId
FGenericTeamId FAISightTarget::TeamId
Definition at line 58 of file AISense_Sight.h.
WeakSightTargetInterface
TWeakInterfacePtr<IAISightTargetInterface> FAISightTarget::WeakSightTargetInterface
Definition at line 57 of file AISense_Sight.h.
The documentation for this struct was generated from the following file:
AISense_Sight.h