Unreal Engine 5.6 C++ API: Metasound::IDataChannel Class Reference
Metasound::IDataChannel Class Reference abstract
#include "MetasoundRouter.h"
Public Member Functions
IDataChannel (FName DataType)
virtual ~IDataChannel ()=default
virtual int64 CreateNewPayloadID ()=0
virtual FName GetDataType ()
uint32 GetNumActiveReceivers () const
uint32 GetNumActiveSenders () const
virtual int64 GetPayloadID () const
virtual bool IsEmpty () const
TUniquePtr< IReceiver > NewReceiver (const FReceiverInitParams &InitParams)
TUniquePtr< ISender > NewSender (const FSenderInitParams &InitParams)
virtual void PopOpaque (IReceiver &InReceiver)
virtual bool PushLiteral (const FLiteral &InParam)
virtual bool PushOpaque (ISender &InSender)
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Public Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedRef< IDataChannel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDataChannel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual TUniquePtr< IReceiver > ConstructNewReceiverImplementation (const FReceiverInitParams &InitParams)
virtual TUniquePtr< ISender > ConstructNewSenderImplementation (const FSenderInitParams &InitParams)
Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
void OnReceiverDestroyed ()
void OnSenderDestroyed ()
Private Attributes
FThreadSafeCounter NumAliveReceivers
FThreadSafeCounter NumAliveSenders
Friends
class IReceiver
class ISender
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
Definition at line 280 of file MetasoundRouter.h.
Constructor & Destructor Documentation
~IDataChannel()
virtual Metasound::IDataChannel::~IDataChannel () virtual default
IDataChannel()
Metasound::IDataChannel::IDataChannel (FName DataType) inline
Definition at line 285 of file MetasoundRouter.h.
References Metasound::IDataTransmissionBase::IDataTransmissionBase(), and Metasound::IDataTransmissionBase::DataType.
Referenced by Metasound::TAudioDataChannel< TDataType >::TAudioDataChannel(), Metasound::TCopyableDataChannel< TDataType >::TCopyableDataChannel(), and Metasound::TNonOperationalDataChannel< TDataType >::TNonOperationalDataChannel().
Member Function Documentation
ConstructNewReceiverImplementation()
virtual TUniquePtr< IReceiver > Metasound::IDataChannel::ConstructNewReceiverImplementation (const FReceiverInitParams & InitParams) inline protected virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 322 of file MetasoundRouter.h.
Referenced by NewReceiver().
ConstructNewSenderImplementation()
virtual TUniquePtr< ISender > Metasound::IDataChannel::ConstructNewSenderImplementation (const FSenderInitParams & InitParams) inline protected virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 323 of file MetasoundRouter.h.
Referenced by NewSender().
CreateNewPayloadID()
virtual int64 Metasound::IDataChannel::CreateNewPayloadID () pure virtual
Implemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
GetDataType()
virtual FName Metasound::IDataChannel::GetDataType () inline virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 317 of file MetasoundRouter.h.
References FName.
GetNumActiveReceivers()
uint32 Metasound::IDataChannel::GetNumActiveReceivers () const inline
Definition at line 301 of file MetasoundRouter.h.
References NumAliveReceivers.
GetNumActiveSenders()
uint32 Metasound::IDataChannel::GetNumActiveSenders () const inline
Definition at line 306 of file MetasoundRouter.h.
References NumAliveSenders.
GetPayloadID()
virtual int64 Metasound::IDataChannel::GetPayloadID () const inline virtual
Reimplemented in Metasound::TCopyableDataChannel< TDataType >.
Definition at line 311 of file MetasoundRouter.h.
References INDEX_NONE.
IsEmpty()
virtual bool Metasound::IDataChannel::IsEmpty () const inline virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 315 of file MetasoundRouter.h.
NewReceiver()
TUniquePtr< IReceiver > Metasound::IDataChannel::NewReceiver (const FReceiverInitParams & InitParams) inline
Definition at line 289 of file MetasoundRouter.h.
References ConstructNewReceiverImplementation(), and NumAliveReceivers.
NewSender()
TUniquePtr< ISender > Metasound::IDataChannel::NewSender (const FSenderInitParams & InitParams) inline
Definition at line 295 of file MetasoundRouter.h.
References ConstructNewSenderImplementation(), and NumAliveSenders.
OnReceiverDestroyed()
void Metasound::IDataChannel::OnReceiverDestroyed () inline private
Definition at line 332 of file MetasoundRouter.h.
References check, and NumAliveReceivers.
OnSenderDestroyed()
void Metasound::IDataChannel::OnSenderDestroyed () inline private
Definition at line 326 of file MetasoundRouter.h.
References check, and NumAliveSenders.
PopOpaque()
virtual void Metasound::IDataChannel::PopOpaque (IReceiver & InReceiver) inline virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 314 of file MetasoundRouter.h.
References IReceiver.
PushLiteral()
virtual bool Metasound::IDataChannel::PushLiteral (const FLiteral & InParam) inline virtual
Reimplemented in Metasound::TCopyableDataChannel< TDataType >.
Definition at line 319 of file MetasoundRouter.h.
PushOpaque()
virtual bool Metasound::IDataChannel::PushOpaque (ISender & InSender) inline virtual
Reimplemented in Metasound::TAudioDataChannel< TDataType >, Metasound::TCopyableDataChannel< TDataType >, and Metasound::TNonOperationalDataChannel< TDataType >.
Definition at line 313 of file MetasoundRouter.h.
References ISender.
Friends And Related Symbol Documentation
IReceiver
friend class IReceiver friend
Definition at line 339 of file MetasoundRouter.h.
References IReceiver.
Referenced by IReceiver, PopOpaque(), Metasound::TAudioDataChannel< TDataType >::PopOpaque(), Metasound::TCopyableDataChannel< TDataType >::PopOpaque(), and Metasound::TNonOperationalDataChannel< TDataType >::PopOpaque().
ISender
friend class ISender friend
Definition at line 338 of file MetasoundRouter.h.
References ISender.
Referenced by ISender, PushOpaque(), Metasound::TAudioDataChannel< TDataType >::PushOpaque(), Metasound::TCopyableDataChannel< TDataType >::PushOpaque(), and Metasound::TNonOperationalDataChannel< TDataType >::PushOpaque().
Field Documentation
NumAliveReceivers
FThreadSafeCounter Metasound::IDataChannel::NumAliveReceivers private
Definition at line 341 of file MetasoundRouter.h.
Referenced by GetNumActiveReceivers(), NewReceiver(), and OnReceiverDestroyed().
NumAliveSenders
FThreadSafeCounter Metasound::IDataChannel::NumAliveSenders private
Definition at line 342 of file MetasoundRouter.h.
Referenced by GetNumActiveSenders(), NewSender(), and OnSenderDestroyed().
The documentation for this class was generated from the following file:
MetasoundRouter.h