Unreal Engine 5.6 C++ API: FWheelState Struct Reference
FWheelState Struct Reference
Commonly used Wheel state - evaluated once used wherever required for that frame.
#include "ChaosWheeledVehicleMovementComponent.h"
Public Member Functions
FWheelState ()
FWheelState (const FWheelState &Other)
~FWheelState ()
void CaptureState (int WheelIdx, const FVector &WheelOffset, const Chaos::FRigidBodyHandle_Internal *Handle)
void CaptureState (int WheelIdx, const FVector &WheelOffset, const Chaos::FRigidBodyHandle_Internal *VehicleHandle, const FVector &ContactPoint, const Chaos::FRigidBodyHandle_Internal *SurfaceHandle)
void CaptureState (int WheelIdx, const FVector &WheelOffset, const FBodyInstance *TargetInstance)
Commonly used Wheel state - evaluated once used wherever required for that frame.
void Init (int NumWheels)
FWheelState & operator= (const FWheelState &Other)
Static Public Member Functions
static FVector GetVelocityAtPoint (const Chaos::FRigidBodyHandle_Internal *Rigid, const FVector &InPoint)
Data Fields
TArray< FVector > LocalWheelVelocity
Current velocity at wheel location In World Coordinates - combined linear and angular.
TArray< Chaos::FSuspensionTrace > Trace
Local velocity of Wheel.
TArray< FHitResult > TraceResult
TArray< FVector > WheelLocalLocation
TArray< FVector > WheelWorldLocation
Current Location Of Wheels In Local Coordinates.
TArray< FVector > WorldWheelVelocity
Current Location Of Wheels In World Coordinates.
Detailed Description
Commonly used Wheel state - evaluated once used wherever required for that frame.
Definition at line 538 of file ChaosWheeledVehicleMovementComponent.h.
Constructor & Destructor Documentation
FWheelState() [1/2]
FWheelState::FWheelState ()
Referenced by FWheelState(), and operator=().
~FWheelState()
FWheelState::~FWheelState ()
FWheelState() [2/2]
FWheelState::FWheelState (const FWheelState & Other)
References FWheelState(), and Other.
Member Function Documentation
CaptureState() [1/3]
void FWheelState::CaptureState (int WheelIdx, const FVector & WheelOffset, const Chaos::FRigidBodyHandle_Internal * Handle)
References FVector, and Handle.
CaptureState() [2/3]
void FWheelState::CaptureState (int WheelIdx, const FVector & WheelOffset, const Chaos::FRigidBodyHandle_Internal * VehicleHandle, const FVector & ContactPoint, const Chaos::FRigidBodyHandle_Internal * SurfaceHandle)
References FVector.
CaptureState() [3/3]
void FWheelState::CaptureState (int WheelIdx, const FVector & WheelOffset, const FBodyInstance * TargetInstance)
Commonly used Wheel state - evaluated once used wherever required for that frame.
References FVector.
GetVelocityAtPoint()
FVector FWheelState::GetVelocityAtPoint (const Chaos::FRigidBodyHandle_Internal * Rigid, const FVector & InPoint) static
References FVector.
Init()
void FWheelState::Init (int NumWheels)
operator=()
FWheelState & FWheelState::operator= (const FWheelState & Other)
References FWheelState(), and Other.
Field Documentation
LocalWheelVelocity
TArray<FVector> FWheelState::LocalWheelVelocity
Current velocity at wheel location In World Coordinates - combined linear and angular.
Definition at line 557 of file ChaosWheeledVehicleMovementComponent.h.
Trace
TArray<Chaos::FSuspensionTrace> FWheelState::Trace
Local velocity of Wheel.
Definition at line 558 of file ChaosWheeledVehicleMovementComponent.h.
TraceResult
TArray<FHitResult> FWheelState::TraceResult
Definition at line 559 of file ChaosWheeledVehicleMovementComponent.h.
WheelLocalLocation
TArray<FVector> FWheelState::WheelLocalLocation
Definition at line 554 of file ChaosWheeledVehicleMovementComponent.h.
WheelWorldLocation
TArray<FVector> FWheelState::WheelWorldLocation
Current Location Of Wheels In Local Coordinates.
Definition at line 555 of file ChaosWheeledVehicleMovementComponent.h.
WorldWheelVelocity
TArray<FVector> FWheelState::WorldWheelVelocity
Current Location Of Wheels In World Coordinates.
Definition at line 556 of file ChaosWheeledVehicleMovementComponent.h.
The documentation for this struct was generated from the following file:
ChaosWheeledVehicleMovementComponent.h