Unreal Engine 5.6 C++ API: UE::FMutex Class Reference
UE::FMutex Class Reference final
A one-byte mutex that is not fair and does not support recursive locking.
#include "Mutex.h"
Public Member Functions
constexpr FMutex ()=default
FMutex (const FMutex &)=delete
FMutex (FAcquireLock)
Construct in a locked state.
bool IsLocked () const
void Lock ()
FMutex & operator= (const FMutex &)=delete
bool TryLock ()
void Unlock ()
Private Member Functions
void LockSlow ()
void WakeWaitingThread ()
Private Attributes
std::atomic< uint8 > State = 0
Static Private Attributes
static constexpr bool bUnlockImmediately = true
static constexpr uint8 IsLockedFlag = 1 << 0
static constexpr uint8 MayHaveWaitingLockFlag = 1 << 1
Detailed Description
A one-byte mutex that is not fair and does not support recursive locking.
Note: Changes to this class should also be ported to FExternalMutex.
Definition at line 18 of file Mutex.h.
Constructor & Destructor Documentation
FMutex() [1/3]
UE::FMutex::FMutex () constexpr default
Referenced by FMutex(), and operator=().
FMutex() [2/3]
UE::FMutex::FMutex (FAcquireLock) inline explicit
Construct in a locked state.
Avoids an expensive compare-and-swap at creation time.
Definition at line 24 of file Mutex.h.
References IsLockedFlag, and State.
FMutex() [3/3]
UE::FMutex::FMutex (const FMutex &) delete
References FMutex().
Member Function Documentation
IsLocked()
bool UE::FMutex::IsLocked () const inline
Definition at line 32 of file Mutex.h.
References IsLockedFlag, and State.
Lock()
void UE::FMutex::Lock () inline
Definition at line 44 of file Mutex.h.
References IsLockedFlag, LIKELY, LockSlow(), and State.
LockSlow()
void UE::FMutex::LockSlow () private
References UE_API.
Referenced by Lock().
operator=()
FMutex & UE::FMutex::operator= (const FMutex &) delete
References FMutex().
TryLock()
bool UE::FMutex::TryLock () inline
Definition at line 37 of file Mutex.h.
References IsLockedFlag, and State.
Unlock()
void UE::FMutex::Unlock () inline
Definition at line 54 of file Mutex.h.
References bUnlockImmediately, IsLockedFlag, LIKELY, MayHaveWaitingLockFlag, State, and WakeWaitingThread().
WakeWaitingThread()
void UE::FMutex::WakeWaitingThread () private
References UE_API.
Referenced by Unlock().
Field Documentation
bUnlockImmediately
bool UE::FMutex::bUnlockImmediately = true static constexpr private
Definition at line 81 of file Mutex.h.
Referenced by Unlock().
IsLockedFlag
uint8 UE::FMutex::IsLockedFlag = 1 << 0 static constexpr private
Definition at line 83 of file Mutex.h.
Referenced by FMutex(), IsLocked(), Lock(), TryLock(), and Unlock().
MayHaveWaitingLockFlag
uint8 UE::FMutex::MayHaveWaitingLockFlag = 1 << 1 static constexpr private
Definition at line 84 of file Mutex.h.
Referenced by Unlock().
State
std::atomic<uint8> UE::FMutex::State = 0 private
Definition at line 86 of file Mutex.h.
Referenced by FMutex(), IsLocked(), Lock(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
Mutex.h