Unreal Engine 5.6 C++ API: FDisplayClusterLightCardEditorHelper::FAddLightCardArgs Struct Reference
FDisplayClusterLightCardEditorHelper::FAddLightCardArgs Struct Reference
#include "DisplayClusterLightCardEditorHelper.h"
Public Member Functions
FAddLightCardArgs ()
UE_DEPRECATED (5.3, "Use LabelConfiguration to configure label scale.") float LabelScale
UE_DEPRECATED (5.3, "Use LabelConfiguration to configure label visibility.") bool bShowLabels
Data Fields
FDisplayClusterLabelConfiguration LabelConfiguration
Label configuration to use for the new light card.
Detailed Description
Definition at line 238 of file DisplayClusterLightCardEditorHelper.h.
Constructor & Destructor Documentation
FAddLightCardArgs()
FDisplayClusterLightCardEditorHelper::FAddLightCardArgs::FAddLightCardArgs () inline
Definition at line 248 of file DisplayClusterLightCardEditorHelper.h.
References FAddLightCardArgs(), and LabelConfiguration.
Referenced by FAddLightCardArgs().
Member Function Documentation
UE_DEPRECATED() [1/2]
FDisplayClusterLightCardEditorHelper::FAddLightCardArgs::UE_DEPRECATED (5. 3, "Use LabelConfiguration to configure label scale.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FDisplayClusterLightCardEditorHelper::FAddLightCardArgs::UE_DEPRECATED (5. 3, "Use LabelConfiguration to configure label visibility.")
References bool.
Referenced by UE_DEPRECATED().
Field Documentation
LabelConfiguration
FDisplayClusterLabelConfiguration FDisplayClusterLightCardEditorHelper::FAddLightCardArgs::LabelConfiguration
Label configuration to use for the new light card.
Definition at line 246 of file DisplayClusterLightCardEditorHelper.h.
Referenced by FAddLightCardArgs().
The documentation for this struct was generated from the following file:
DisplayClusterLightCardEditorHelper.h