Unreal Engine 5.6 C++ API: FPropertyValueIterator Class Reference
FPropertyValueIterator Class Reference
For recursively iterating over a UStruct to find nested FProperty pointers and values.
#include "UnrealType.h"
Public Types
using BasePairType = TPair<const FProperty*, const void*>
Public Member Functions
FPropertyValueIterator ()
Invalid iterator, start with empty stack.
FPropertyValueIterator (FFieldClass *InPropertyClass, const UStruct *InStruct, const void *InStructValue, EPropertyValueIteratorFlags InRecursionFlags=EPropertyValueIteratorFlags::FullRecursion, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedPropertyFlags=EFieldIteratorFlags::IncludeDeprecated)
Construct an iterator using a struct and struct value.
void GetPropertyChain (TArray< const FProperty * > &PropertyChain) const
Returns the full stack of properties for the property currently being iterated.
FString GetPropertyPathDebugString () const
Returns a string of the property chain in a form that makes reading it easy.
FORCEINLINE const FProperty * Key () const
Returns Property currently being iterated.
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const FPropertyValueIterator &Rhs) const
FORCEINLINE const BasePairType & operator* () const
Returns a TPair containing Property/Value currently being iterated.
FORCEINLINE void operator++ ()
Increments iterator.
FORCEINLINE const BasePairType * operator-> () const
FORCEINLINE bool operator== (const FPropertyValueIterator &Rhs) const
FORCEINLINE void SkipRecursiveProperty ()
Call when iterating a recursive property such as Array or Struct to stop it from iterating into that property.
FORCEINLINE const void * Value () const
Returns memory address currently being iterated.
Private Types
enum class EPropertyValueFlags : uint8 {
None = 0x0 , IsMatch = 0x01 , IsOptional = 0x08 , IsArray = 0x10 ,
IsMap = 0x20 , IsSet = 0x40 , IsStruct = 0x80
}
Private Member Functions
void FillStructProperties (const UStruct *Struct, FPropertyValueStackEntry &Entry)
Fills the Entry.ValueArray with all relevant properties found in Struct.
FRIEND_ENUM_CLASS_FLAGS (EPropertyValueFlags) struct FPropertyValueStackEntry
EPropertyValueFlags GetPropertyValueFlags (const FProperty *Property) const
Returns EPropertyValueFlags to describe if this Property is a match and/or a container/struct.
void IterateToNext ()
Iterates to next property being checked for or until reaching the end of the structure.
bool NextValue (EPropertyValueIteratorFlags RecursionFlags)
Goes to the next Property/value pair.
Private Attributes
bool bMatchAll = false
If true, all properties will be matched without checking IsA(PropertyClass)
bool bSkipRecursionOnce = false
If true, next iteration will skip recursing into containers/structs.
const EFieldIteratorFlags::DeprecatedPropertyFlags DeprecatedPropertyFlags
Inherits to child field iterator.
FFieldClass * PropertyClass = nullptr
Property type that is explicitly checked for.
TArray< FPropertyValueStackEntry, TInlineAllocator< 8 > > PropertyIteratorStack
Internal stack, one per continer/struct.
const EPropertyValueIteratorFlags RecursionFlags
Whether to recurse into containers/structs.
Detailed Description
For recursively iterating over a UStruct to find nested FProperty pointers and values.
Definition at line 7002 of file UnrealType.h.
Member Typedef Documentation
BasePairType
using FPropertyValueIterator::BasePairType = TPair<const FProperty*, const void*>
Definition at line 7005 of file UnrealType.h.
Member Enumeration Documentation
EPropertyValueFlags
enum class FPropertyValueIterator::EPropertyValueFlags : uint8 strong private
Enumerator
None
IsMatch
IsOptional
IsArray
IsMap
IsSet
IsStruct
Definition at line 7110 of file UnrealType.h.
Constructor & Destructor Documentation
FPropertyValueIterator() [1/2]
FPropertyValueIterator::FPropertyValueIterator (FFieldClass * InPropertyClass, const UStruct * InStruct, const void * InStructValue, EPropertyValueIteratorFlags InRecursionFlags = EPropertyValueIteratorFlags::FullRecursion, EFieldIteratorFlags::DeprecatedPropertyFlags InDeprecatedPropertyFlags = EFieldIteratorFlags::IncludeDeprecated) explicit
Construct an iterator using a struct and struct value.
Parameters
InPropertyClass The UClass of the FProperty type you are looking for
InStruct The UClass or UScriptStruct containing properties to search for
InStructValue Address in memory of struct to search for property values
InRecursionFlags Rather to recurse into container and struct properties
InDeprecatedPropertyFlags Rather to iterate over deprecated properties
References FullRecursion, and EFieldIteratorFlags::IncludeDeprecated.
Referenced by TPropertyValueIterator< T >::TPropertyValueIterator(), operator!=(), and operator==().
FPropertyValueIterator() [2/2]
FPropertyValueIterator::FPropertyValueIterator () inline
Invalid iterator, start with empty stack.
Definition at line 7021 of file UnrealType.h.
References bSkipRecursionOnce, DeprecatedPropertyFlags, FullRecursion, IncludeDeprecated, PropertyClass, and RecursionFlags.
Member Function Documentation
FillStructProperties()
void FPropertyValueIterator::FillStructProperties (const UStruct * Struct, FPropertyValueStackEntry & Entry) private
Fills the Entry.ValueArray with all relevant properties found in Struct.
References Struct.
FRIEND_ENUM_CLASS_FLAGS()
FPropertyValueIterator::FRIEND_ENUM_CLASS_FLAGS (EPropertyValueFlags) inline private
Address of owning UStruct or FProperty container
List of current root property+value pairs for the current top level FProperty
Current position inside ValueArray
Next position inside ValueArray
Definition at line 7123 of file UnrealType.h.
References FORCEINLINE, operator==(), and Owner.
GetPropertyChain()
void FPropertyValueIterator::GetPropertyChain (TArray< const FProperty * > & PropertyChain) const
Returns the full stack of properties for the property currently being iterated.
This includes struct and container properties
Parameters
PropertyChain Filled in with ordered list of Properties, with currently active property first and top parent last
GetPropertyPathDebugString()
FString FPropertyValueIterator::GetPropertyPathDebugString () const
Returns a string of the property chain in a form that makes reading it easy.
The format may change over time, do not depend on this being in a specific Unreal path format. It's primary intention is to aid in debugging and in reporting paths to the end developer in an editor environment.
Now for the implementation details, normally paths involving an array, will do things like print the array name twice, since an array in the path is actually 2 properties, one for the array and another for the index. Maps are similar. The end result is stuff like seeing, ActionsArray.ActionsArray.ActionIfo.ActionPower.
What this function does is tries to make this stuff a lot more human readable, by printing, ActionsArray[3].ActionIfo.ActionPower, so that you know the index it comes from. Similarly Maps would print ActionMap["Action Name"].ActionIfo.ActionPower, so that you know the index it comes from. Similarly Maps would print
GetPropertyValueFlags()
EPropertyValueFlags FPropertyValueIterator::GetPropertyValueFlags (const FProperty * Property) const private
Returns EPropertyValueFlags to describe if this Property is a match and/or a container/struct.
References Property.
IterateToNext()
void FPropertyValueIterator::IterateToNext () private
Iterates to next property being checked for or until reaching the end of the structure.
Referenced by operator++().
Key()
FORCEINLINE const FProperty * FPropertyValueIterator::Key () const inline
Returns Property currently being iterated.
Definition at line 7064 of file UnrealType.h.
References FORCEINLINE.
NextValue()
bool FPropertyValueIterator::NextValue (EPropertyValueIteratorFlags RecursionFlags) private
Goes to the next Property/value pair.
Returns false on a match or out of properties, true when iteration should continue
References RecursionFlags.
operator bool()
FORCEINLINE FPropertyValueIterator::operator bool () const inline explicit
Conversion to "bool" returning true if the iterator is valid.
Definition at line 7030 of file UnrealType.h.
References FORCEINLINE, and PropertyIteratorStack.
operator!=()
FORCEINLINE bool FPropertyValueIterator::operator!= (const FPropertyValueIterator & Rhs) const inline
Definition at line 7045 of file UnrealType.h.
References FPropertyValueIterator(), FORCEINLINE, and PropertyIteratorStack.
operator*()
FORCEINLINE const BasePairType & FPropertyValueIterator::operator* () const inline
Returns a TPair containing Property/Value currently being iterated.
Definition at line 7051 of file UnrealType.h.
References FORCEINLINE, and PropertyIteratorStack.
Referenced by TPropertyValueIterator< T >::operator*().
operator++()
FORCEINLINE void FPropertyValueIterator::operator++ () inline
Increments iterator.
Definition at line 7076 of file UnrealType.h.
References FORCEINLINE, and IterateToNext().
operator->()
FORCEINLINE const BasePairType * FPropertyValueIterator::operator-> () const inline
Definition at line 7057 of file UnrealType.h.
References FORCEINLINE, and PropertyIteratorStack.
Referenced by TPropertyValueIterator< T >::operator->().
operator==()
FORCEINLINE bool FPropertyValueIterator::operator== (const FPropertyValueIterator & Rhs) const inline
Definition at line 7040 of file UnrealType.h.
References FPropertyValueIterator(), FORCEINLINE, and PropertyIteratorStack.
SkipRecursiveProperty()
FORCEINLINE void FPropertyValueIterator::SkipRecursiveProperty () inline
Call when iterating a recursive property such as Array or Struct to stop it from iterating into that property.
Definition at line 7082 of file UnrealType.h.
References bSkipRecursionOnce, and FORCEINLINE.
Value()
FORCEINLINE const void * FPropertyValueIterator::Value () const inline
Returns memory address currently being iterated.
Definition at line 7070 of file UnrealType.h.
References FORCEINLINE.
Field Documentation
bMatchAll
bool FPropertyValueIterator::bMatchAll = false private
If true, all properties will be matched without checking IsA(PropertyClass)
Definition at line 7177 of file UnrealType.h.
bSkipRecursionOnce
bool FPropertyValueIterator::bSkipRecursionOnce = false private
If true, next iteration will skip recursing into containers/structs.
Definition at line 7174 of file UnrealType.h.
Referenced by FPropertyValueIterator(), and SkipRecursiveProperty().
DeprecatedPropertyFlags
const EFieldIteratorFlags::DeprecatedPropertyFlags FPropertyValueIterator::DeprecatedPropertyFlags private
Inherits to child field iterator.
Definition at line 7171 of file UnrealType.h.
Referenced by FPropertyValueIterator().
PropertyClass
FFieldClass* FPropertyValueIterator::PropertyClass = nullptr private
Property type that is explicitly checked for.
Definition at line 7165 of file UnrealType.h.
Referenced by FPropertyValueIterator().
PropertyIteratorStack
TArray<FPropertyValueStackEntry, TInlineAllocator<8> > FPropertyValueIterator::PropertyIteratorStack private
Internal stack, one per continer/struct.
Definition at line 7162 of file UnrealType.h.
Referenced by operator bool(), operator!=(), operator*(), operator->(), and operator==().
RecursionFlags
const EPropertyValueIteratorFlags FPropertyValueIterator::RecursionFlags private
Whether to recurse into containers/structs.
Definition at line 7168 of file UnrealType.h.
Referenced by FPropertyValueIterator(), and NextValue().
The documentation for this class was generated from the following file:
UnrealType.h