Unreal Engine 5.6 C++ API: GroomResources.h File Reference
GroomResources.h File Reference
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "HairDescription.h"
#include "HairStrandsDatas.h"
#include "HairCardsDatas.h"
#include "RenderResource.h"
#include "RayTracingGeometry.h"
#include "HairStrandsInterface.h"
#include "HairStrandsMeshProjection.h"
Data Structures
struct EHairResourceStatus
class FHairCardIndexBuffer
struct FHairCardsDeformedResource
struct FHairCardsInterpolationResource
struct FHairCardsRestResource
class FHairCardsVertexBuffer
struct FHairCommonResource
struct FHairMeshesDeformedResource
struct FHairMeshesRestResource
struct FHairResourceName
struct FHairStrandsClusterResource
struct FHairStrandsCullingResource
struct FHairStrandsDeformedResource
struct FHairStrandsDeformedRootResource
struct FHairStrandsInterpolationResource
struct FHairStrandsLODDeformedRootResource
struct FHairStrandsLODRestRootResource
struct FHairStrandsRestResource
struct FHairStrandsRestRootResource
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::DerivedData
Macros
#define HAIR_RESOURCE_DEBUG_NAME 0
Enumerations
enum class EHairResourceLoadingType : uint8 { Async , Sync }
enum class EHairStrandsAllocationType : uint8 { Immediate , Deferred }
enum class EHairStrandsResourcesType : uint8 { Guides , Strands , Cards }
Functions
void CreateHairStrandsDebugDatas (const FHairStrandsDatas &InData, FHairStrandsDebugDatas &Out)
void CreateHairStrandsDebugResources (class FRDGBuilder &GraphBuilder, const FHairStrandsDebugDatas *In, FHairStrandsDebugResources *Out)
DECLARE_RENDER_COMMAND_PIPE (Groom, HAIRSTRANDSCORE_API)
uint32 GetBufferTotalNumBytes (const FRDGExternalBuffer &In)
EHairResourceLoadingType GetHairResourceLoadingType (EHairGeometryType InGeometryType, int32 InLODIndex)
FORCEINLINE bool operator! (EHairResourceStatus A)
FORCEINLINE EHairResourceStatus operator& (EHairResourceStatus In, EHairResourceStatus::EStatus InStatus)
FORCEINLINE EHairResourceStatus operator| (EHairResourceStatus In, EHairResourceStatus::EStatus InStatus)
FORCEINLINE EHairResourceStatus & operator|= (EHairResourceStatus &Out, EHairResourceStatus::EStatus InStatus)
Macro Definition Documentation
HAIR_RESOURCE_DEBUG_NAME
#define HAIR_RESOURCE_DEBUG_NAME 0
Definition at line 41 of file GroomResources.h.
Enumeration Type Documentation
EHairResourceLoadingType
enum class EHairResourceLoadingType : uint8 strong
Enumerator
Async
Sync
Definition at line 64 of file GroomResources.h.
EHairStrandsAllocationType
enum class EHairStrandsAllocationType : uint8 strong
Enumerator
Immediate
Deferred
Definition at line 34 of file GroomResources.h.
EHairStrandsResourcesType
enum class EHairStrandsResourcesType : uint8 strong
Enumerator
Guides
Strands
Cards
Definition at line 27 of file GroomResources.h.
Function Documentation
CreateHairStrandsDebugDatas()
void CreateHairStrandsDebugDatas (const FHairStrandsDatas & InData, FHairStrandsDebugDatas & Out)
CreateHairStrandsDebugResources()
void CreateHairStrandsDebugResources (class FRDGBuilder & GraphBuilder, const FHairStrandsDebugDatas * In, FHairStrandsDebugResources * Out)
DECLARE_RENDER_COMMAND_PIPE()
DECLARE_RENDER_COMMAND_PIPE (Groom , HAIRSTRANDSCORE_API)
GetBufferTotalNumBytes()
uint32 GetBufferTotalNumBytes (const FRDGExternalBuffer & In) inline
Definition at line 22 of file GroomResources.h.
Referenced by FHairCardsDeformedResource::GetResourcesSize(), FHairCardsInterpolationResource::GetResourcesSize(), FHairMeshesDeformedResource::GetResourcesSize(), FHairStrandsClusterResource::GetResourcesSize(), FHairStrandsCullingResource::GetResourcesSize(), FHairStrandsDeformedResource::GetResourcesSize(), FHairStrandsInterpolationResource::GetResourcesSize(), FHairStrandsLODDeformedRootResource::GetResourcesSize(), FHairStrandsLODRestRootResource::GetResourcesSize(), and FHairStrandsRestResource::GetResourcesSize().
GetHairResourceLoadingType()
EHairResourceLoadingType GetHairResourceLoadingType (EHairGeometryType InGeometryType, int32 InLODIndex)
operator!()
FORCEINLINE bool operator! (EHairResourceStatus A)
Definition at line 88 of file GroomResources.h.
References A, and FORCEINLINE.
operator&()
FORCEINLINE EHairResourceStatus operator& (EHairResourceStatus In, EHairResourceStatus::EStatus InStatus)
Definition at line 84 of file GroomResources.h.
References FORCEINLINE, and EHairResourceStatus::Status.
operator|()
FORCEINLINE EHairResourceStatus operator| (EHairResourceStatus In, EHairResourceStatus::EStatus InStatus)
Definition at line 85 of file GroomResources.h.
References FORCEINLINE, and EHairResourceStatus::Status.
operator|=()
FORCEINLINE EHairResourceStatus & operator|= (EHairResourceStatus & Out, EHairResourceStatus::EStatus InStatus)
Definition at line 86 of file GroomResources.h.
References FORCEINLINE.