Unreal Engine 5.6 C++ API: UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ > Class Template Reference
UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ > Class Template Reference
TBlockedGrid3 represents a 3D uniform grid.
#include "BlockedDenseGrid3.h"
Public Types
typedef TBlockData3< ElemType, BlockSize_ > BlockData3Type
typedef TBasicBlockedDenseGrid3< ElemType, BlockSize_ > BlockedDenseGridType
typedef TBlockedGrid3Layout< BlockSize_ > BlockedGrid3LayoutType
Public Types inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
typedef TBlockData3< ElemType, BlockSize_ > BlockData3Type
typedef TBlockedGrid3Layout< BlockSize_ > BlockedGrid3LayoutType
Public Types inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
typedef TBlockData3Layout< BlockSize_ > FBlockData3Layout
Public Member Functions
TBlockedGrid3 ()
Create empty grid.
TBlockedGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Create grid with specified domain.
TArray< BlockData3Type * > GetAllocatedBlocks ()
TArray< const BlockData3Type * > GetAllocatedBlocks () const
TArray< const BlockData3Type * > GetAllocatedConstBlocks () const
TUniquePtr< BlockData3Type > & GetBlockData (const FVector3i &BlockIJK)
const TUniquePtr< BlockData3Type > & GetBlockData (const FVector3i &BlockIJK) const
TUniquePtr< BlockData3Type > & GetBlockData (int32 BlockIndex)
const TUniquePtr< BlockData3Type > & GetBlockData (int32 BlockIndex) const
ElemType GetBlockDefaultValue (const FVector3i &BlockIJK) const
int32 GetNumBlocks () const
bool IsBlockAllocated (const FVector3i &BlockIJK) const
template<typename ProcessFunc>
void ProcessBlockDefaultValue (const FVector3i &BlockIJK, ProcessFunc Func, bool bPruneBlock=true)
Update the default value for the specified block using a functor.
template<typename ProcessFunc, typename CriticalSectionProviderType>
void ProcessValueWithLock (const FVector3i &CellIJK, ProcessFunc Func, CriticalSectionProviderType CriticalSectionProvider)
Call an external lambda with a reference to the grid value at CellIJK.
template<typename ProcessFunc, typename CriticalSectionProviderType>
void ProcessValueWithLock (int32 I, int32 J, int32 K, ProcessFunc Func, CriticalSectionProviderType CriticalSectionProvider)
Call an external lambda with a reference to the grid value at (I,J,K).
void SetBlockDefaultValue (const FVector3i &BlockIJK, const ElemType &Value, bool bPruneBlock=true)
Update the default value for the specified block.
template<typename CriticalSectionProviderType>
void SetValueWithLock (const FVector3i &CellIJK, ElemType NewValue, CriticalSectionProviderType CriticalSectionProvider)
Set the grid value at CellIJK, with user supplied locking in the form of a function of the form.
template<typename CriticalSectionProviderType>
void SetValueWithLock (int32 I, int32 J, int32 K, ElemType NewValue, CriticalSectionProviderType &CriticalSectionProvider)
Set the grid value at (I,J,K), with user supplied locking in the form of a function of the form.
BlockData3Type & TouchBlockData (const FVector3i &BlockIJK)
Public Member Functions inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
TBasicBlockedDenseGrid3 ()
Create empty grid.
TBasicBlockedDenseGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Create grid with specified domain.
int32 GetNumBlocks () const
ElemType GetValue (const FVector3i &CellIJK) const
ElemType GetValue (int32 I, int32 J, int32 K) const
template<typename OtherElemType>
bool PreAllocateFromSourceGrid (const TBasicBlockedDenseGrid3< OtherElemType, BlockSize > &SourceGrid)
Pre-allocate the grid blocks that also exist in SourceGrid of the same dimensions.
template<typename ProcessFunc>
void ProcessValue (const FVector3i &CellIJK, ProcessFunc Func)
Call an external lambda with a reference to the grid value at CellIJK.
template<typename ProcessFunc>
void ProcessValue (int32 I, int32 J, int32 K, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (I,J,K).
void Reset ()
Discard all allocated blocks but retain grid dimensions.
void Reset (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Reconfigure the grid to have the target dimensions and default value.
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Reconfigure the grid to have the target dimensions.
void SetValue (const FVector3i &CellIJK, ElemType NewValue)
Set the grid value at CellIJK.
void SetValue (int32 I, int32 J, int32 K, ElemType NewValue)
Set the grid value at (I,J,K)
Public Member Functions inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
TBlockedGrid3Layout ()
TBlockedGrid3Layout (FVector3i Dims)
TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK)
int32 BlockIJKToBlockIndex (const FVector3i &BlockIJK) const
FVector3i BlockIndexToBlockIJK (const int32 BlockIndex) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
void GetBlockAndLocalIndex (const FVector3i &IJK, int32 &BlockIndexOut, int32 &LocalIndexOut) const
return the block index and local index of the cell at (I,J,K).
void GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 &BlockIndexOut, int32 &LocalIndexOut) const
const FVector3i & GetBlockDimensions () const
const FVector3i & GetDimensions () const
int32 IJKtoBlockIndex (const FVector3i &IJK) const
bool IsValidBlockIJK (const FVector3i &BlockIJK)
bool IsValidIJK (const FVector3i &IJK) const
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Recompute the block dimensions required to cover the requested cell dimensions.
int64 Size () const
Static Public Attributes
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Static Public Attributes inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Static Public Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Protected Types
typedef TBasicBlockedDenseGrid3< ElemType, BlockSize_ >::FBlock3 FBlock3
Protected Member Functions
ElemType ReadBlockDefaultValue (const FVector3i &BlockIJK) const
ElemType ReadBlockDefaultValue (const int32 &BlockIndex) const
template<typename FuncType>
void WriteBlockDefaultValue (const FVector3i &BlockIJK, FuncType Func, bool bDeallocateBock=true)
template<typename FuncType>
void WriteBlockDefaultValue (const int32 BlockIndex, FuncType Func, bool bDeallocateBock=true)
template<typename FuncType>
void WriteBlockDefaultValueWithLock (const int32 BlockIndex, FuncType Func, FCriticalSection *CriticalSection, bool bDeallocateBock=true)
Protected Member Functions inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
template<typename OtherGridType>
bool AllocateTopologyUnionImpl (const OtherGridType &OtherGrid)
FBlock3 & GetBlock (int32 Index)
const FBlock3 & GetBlock (int32 Index) const
bool IsBlockAllocated (const FBlock3 &Block) const
bool IsBlockAllocated (const int32 BlockIndex) const
ElemType ReadValue (const int32 &BlockIndex, const int32 &LocalIndex) const
ElemType ReadValue (int32 I, int32 J, int32 K) const
ElemType ReadValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FCriticalSection *CriticalSection)
BlockData3Type & TouchBlockData (const int32 BlockIndex)
return a reference to the block data buffer associated with the specified block, allocating if needed
template<typename FuncType>
void WriteValue (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func)
template<typename FuncType>
void WriteValue (int32 I, int32 J, int32 K, FuncType Func)
template<typename FuncType>
void WriteValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func, FCriticalSection *CriticalSection)
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, BlockSize_ >
TArray< FBlock3 > Blocks
ElemType DefaultValue = (ElemType)0
The value to use to initialize new blocks.
Protected Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
FVector3i BlockDimensions
FVector3i Dimensions
Detailed Description
template<typename ElemType, int32 BlockSize_>
class UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >
TBlockedGrid3 represents a 3D uniform grid.
The grid is allocated in BlockSize^3 blocks on-demand (BlockSize is a compile-time constant) allowing very large grids to be used without having to pre-allocate all the memory, eg for sparse/narrow-band use cases.
Block-level default values are returned when querying a grid cell in an unallocated block.,
Block-level access is provided to facilitate parallel algorithms. Additionally, 'Set' methods are provided that utilize critical sections provided by the caller.
Definition at line 431 of file BlockedDenseGrid3.h.
Member Typedef Documentation
BlockData3Type
template<typename ElemType, int32 BlockSize_> typedef TBlockData3<ElemType, BlockSize_> UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::BlockData3Type
Definition at line 436 of file BlockedDenseGrid3.h.
BlockedDenseGridType
template<typename ElemType, int32 BlockSize_> typedef TBasicBlockedDenseGrid3<ElemType, BlockSize_> UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::BlockedDenseGridType
Definition at line 434 of file BlockedDenseGrid3.h.
BlockedGrid3LayoutType
template<typename ElemType, int32 BlockSize_> typedef TBlockedGrid3Layout<BlockSize_> UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::BlockedGrid3LayoutType
Definition at line 435 of file BlockedDenseGrid3.h.
FBlock3
template<typename ElemType, int32 BlockSize_> typedef TBasicBlockedDenseGrid3<ElemType,BlockSize_>::FBlock3 UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::FBlock3 protected
Definition at line 445 of file BlockedDenseGrid3.h.
Constructor & Destructor Documentation
TBlockedGrid3() [1/2]
template<typename ElemType, int32 BlockSize_> UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::TBlockedGrid3 () inline
Create empty grid.
Definition at line 491 of file BlockedDenseGrid3.h.
TBlockedGrid3() [2/2]
template<typename ElemType, int32 BlockSize_> UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::TBlockedGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue) inline
Create grid with specified domain.
Definition at line 498 of file BlockedDenseGrid3.h.
Member Function Documentation
GetAllocatedBlocks() [1/2]
template<typename ElemType, int32 BlockSize_> TArray< BlockData3Type * > UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetAllocatedBlocks () inline
Returns
array of pointers to the allocated blocks. Note: the grid owns the blocks, so the calling code should not delete them.
Definition at line 589 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
GetAllocatedBlocks() [2/2]
template<typename ElemType, int32 BlockSize_> TArray< const BlockData3Type * > UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetAllocatedBlocks () const inline
Returns
array of pointers to the allocated blocks. Note: the grid owns the blocks, so the calling code should not delete them.
Definition at line 604 of file BlockedDenseGrid3.h.
GetAllocatedConstBlocks()
template<typename ElemType, int32 BlockSize_> TArray< const BlockData3Type * > UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetAllocatedConstBlocks () const inline
Returns
array of pointers to the allocated blocks. Note: the grid owns the blocks, so the calling code should not delete them.
Definition at line 574 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetAllocatedBlocks(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill().
GetBlockData() [1/4]
template<typename ElemType, int32 BlockSize_> TUniquePtr< BlockData3Type > & UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetBlockData (const FVector3i & BlockIJK) inline
Returns
reference to a unique pointer that points to a block that may or may not be allocated
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 632 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::TBlockedGrid3< float, 8 >::IsBlockAllocated(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill().
GetBlockData() [2/4]
template<typename ElemType, int32 BlockSize_> const TUniquePtr< BlockData3Type > & UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetBlockData (const FVector3i & BlockIJK) const inline
Returns
reference to a unique pointer that points to a block that may or may not be allocated
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 642 of file BlockedDenseGrid3.h.
GetBlockData() [3/4]
template<typename ElemType, int32 BlockSize_> TUniquePtr< BlockData3Type > & UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetBlockData (int32 BlockIndex) inline
Returns
reference to a unique pointer that points to a block that may or may not be allocated
Parameters
BlockIndex - the index of the block in an internal linearization of the blocks. Note: BlockIJK and BlockIndex can be converted by means of BlockIJKToBlockIndex() and BlockIndexToBlockIJK()
Definition at line 653 of file BlockedDenseGrid3.h.
GetBlockData() [4/4]
template<typename ElemType, int32 BlockSize_> const TUniquePtr< BlockData3Type > & UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetBlockData (int32 BlockIndex) const inline
Returns
reference to a unique pointer that points to a block that may or may not be allocated
Parameters
BlockIndex - the index of the block in an internal linearization of the blocks. Note: BlockIJK and BlockIndex can be converted by means of BlockIJKToBlockIndex() and BlockIndexToBlockIJK()
Definition at line 663 of file BlockedDenseGrid3.h.
GetBlockDefaultValue()
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetBlockDefaultValue (const FVector3i & BlockIJK) const inline
Returns
the default value for the specified block.
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 676 of file BlockedDenseGrid3.h.
GetNumBlocks()
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::GetNumBlocks () const inline
Returns
the total number of block units that covers the spatial dimensions of the grid.
Definition at line 567 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
IsBlockAllocated()
template<typename ElemType, int32 BlockSize_> bool UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::IsBlockAllocated (const FVector3i & BlockIJK) const inline
Returns
true if the specified block has been allocated.
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 613 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
ProcessBlockDefaultValue()
template<typename ElemType, int32 BlockSize_> template<typename ProcessFunc> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::ProcessBlockDefaultValue (const FVector3i & BlockIJK, ProcessFunc Func, bool bPruneBlock = true) inline
Update the default value for the specified block using a functor.
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Func - Func(ElemType& value){..} is called on the default value.
bPruneBlock - if true, any internal block allocation will be freed and the resulting deallocated block will just hold a single default value. if false, the allocation of the block will no change.
Definition at line 705 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
ProcessValueWithLock() [1/2]
template<typename ElemType, int32 BlockSize_> template<typename ProcessFunc, typename CriticalSectionProviderType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::ProcessValueWithLock (const FVector3i & CellIJK, ProcessFunc Func, CriticalSectionProviderType CriticalSectionProvider) inline
Call an external lambda with a reference to the grid value at CellIJK.
Called as Func(ElemType&), so the caller can both read and write the grid cell
note: if doing pure reads prefer the GetValue() methods because the ProcessValue method will allocate the underlying data block.
Definition at line 559 of file BlockedDenseGrid3.h.
ProcessValueWithLock() [2/2]
template<typename ElemType, int32 BlockSize_> template<typename ProcessFunc, typename CriticalSectionProviderType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::ProcessValueWithLock (int32 I, int32 J, int32 K, ProcessFunc Func, CriticalSectionProviderType CriticalSectionProvider) inline
Call an external lambda with a reference to the grid value at (I,J,K).
Called as Func(ElemType&), so the caller can both read and write the grid cell
note: if doing pure reads prefer the GetValue() methods because the ProcessValue method will allocate the underlying data block.
Definition at line 544 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::ProcessValueWithLock().
ReadBlockDefaultValue() [1/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::ReadBlockDefaultValue (const FVector3i & BlockIJK) const inline protected
Definition at line 481 of file BlockedDenseGrid3.h.
ReadBlockDefaultValue() [2/2]
template<typename ElemType, int32 BlockSize_> ElemType UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::ReadBlockDefaultValue (const int32 & BlockIndex) const inline protected
Definition at line 476 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockDefaultValue(), and UE::Geometry::TBlockedGrid3< float, 8 >::ReadBlockDefaultValue().
SetBlockDefaultValue()
template<typename ElemType, int32 BlockSize_> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::SetBlockDefaultValue (const FVector3i & BlockIJK, const ElemType & Value, bool bPruneBlock = true) inline
Update the default value for the specified block.
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Value - the new default value for this block
bPruneBlock - if true, any internal block allocation will be freed and the resulting deallocated block will just hold a single default value. if false, the allocation of the block will no change.
Definition at line 690 of file BlockedDenseGrid3.h.
SetValueWithLock() [1/2]
template<typename ElemType, int32 BlockSize_> template<typename CriticalSectionProviderType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::SetValueWithLock (const FVector3i & CellIJK, ElemType NewValue, CriticalSectionProviderType CriticalSectionProvider) inline
Set the grid value at CellIJK, with user supplied locking in the form of a function of the form.
FCriticalSection& CriticalSectionProvider(id)
that provides a critical section for each block id.
Definition at line 532 of file BlockedDenseGrid3.h.
SetValueWithLock() [2/2]
template<typename ElemType, int32 BlockSize_> template<typename CriticalSectionProviderType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::SetValueWithLock (int32 I, int32 J, int32 K, ElemType NewValue, CriticalSectionProviderType & CriticalSectionProvider) inline
Set the grid value at (I,J,K), with user supplied locking in the form of a function of the form.
FCriticalSection& CriticalSectionProvider(id)
that provides a critical section for each block id.
Definition at line 515 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), and UE::Geometry::TBlockedGrid3< float, 8 >::SetValueWithLock().
TouchBlockData()
template<typename ElemType, int32 BlockSize_> BlockData3Type & UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::TouchBlockData (const FVector3i & BlockIJK) inline
Returns
a references to the specified block, this will allocate the block if it doesn't already exists.
Parameters
BlockIJK - the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 622 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial().
WriteBlockDefaultValue() [1/2]
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::WriteBlockDefaultValue (const FVector3i & BlockIJK, FuncType Func, bool bDeallocateBock = true) inline protected
Definition at line 460 of file BlockedDenseGrid3.h.
WriteBlockDefaultValue() [2/2]
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::WriteBlockDefaultValue (const int32 BlockIndex, FuncType Func, bool bDeallocateBock = true) inline protected
Definition at line 449 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::ProcessBlockDefaultValue(), UE::Geometry::TBlockedGrid3< float, 8 >::SetBlockDefaultValue(), UE::Geometry::TBlockedGrid3< float, 8 >::WriteBlockDefaultValue(), and UE::Geometry::TBlockedGrid3< float, 8 >::WriteBlockDefaultValueWithLock().
WriteBlockDefaultValueWithLock()
template<typename ElemType, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::WriteBlockDefaultValueWithLock (const int32 BlockIndex, FuncType Func, FCriticalSection * CriticalSection, bool bDeallocateBock = true) inline protected
Definition at line 467 of file BlockedDenseGrid3.h.
Field Documentation
BlockElemCount
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::BlockElemCount = BlockSize * BlockSize * BlockSize static constexpr
Definition at line 440 of file BlockedDenseGrid3.h.
BlockSize
template<typename ElemType, int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3< ElemType, BlockSize_ >::BlockSize = BlockSize_ static constexpr
Definition at line 439 of file BlockedDenseGrid3.h.
The documentation for this class was generated from the following file:
BlockedDenseGrid3.h