Unreal Engine 5.6 C++ API: FLODCluster Struct Reference
FLODCluster Struct Reference
This is a LOD cluster struct that holds list of actors with relevant information.
#include "LODCluster.h"
Public Member Functions
FLODCluster ()
FLODCluster (AActor *Actor1)
FLODCluster (AActor *Actor1, AActor *Actor2)
FLODCluster (const FLODCluster &Other)
FLODCluster (FLODCluster &&Other)
bool Contains (FLODCluster &Other) const
Compare clusters and returns true when this contains any of Other's actors.
double GetCost () const
Return cost of the cluster, lower is better.
double GetMergedCost (const FLODCluster &Other) const
Return cost of the union of this cluster & the other cluster, lower is better.
void Invalidate ()
Invalidates this cluster.
bool IsValid () const
Returns whether or not this cluster is valid.
FLODCluster operator+ (const FLODCluster &Other) const
Cluster operators.
FLODCluster & operator+= (const FLODCluster &Other)
FLODCluster operator- (const FLODCluster &Other) const
FLODCluster & operator-= (const FLODCluster &Other)
FLODCluster & operator= (const FLODCluster &Other)
FLODCluster & operator= (FLODCluster &&Other)
bool operator== (const FLODCluster &Other) const
FString ToString () const
Returns data/info for this Cluster as a string.
Data Fields
TSet< AActor *, DefaultKeyFuncs< AActor * >, TInlineSetAllocator< 2 > > Actors
List of Actors that this cluster contains.
FSphere Bound
Cluster bounds.
double ClusterCost
Cached cluster cost, FMath::Pow(Bound.W, 3) / FillingFactor.
double FillingFactor
Filling factor for this cluster, determines how much of the cluster's bounds/area is occupied by the contained actors.
Private Member Functions
FSphere AddActor (AActor *NewActor)
Adds a new actor to this cluster and updates the bounds accordingly, the filling factor is NOT updated.
void MergeClusters (const FLODCluster &Other)
Merges this cluster with Other by combining the actor arrays and updating the bounds, filling factor and cluster cost.
void SubtractCluster (const FLODCluster &Other)
Subtracts the Other cluster from this cluster by removing Others actors and updating the bounds, filling factor and cluster cost This will invalidate the cluster if Actors.Num result to be 0.
Private Attributes
bool bValid
Bool flag whether or not this cluster is valid.
Detailed Description
This is a LOD cluster struct that holds list of actors with relevant information.
http://deim.urv.cat/~rivi/pub/3d/icra04b.pdf
This is used by Hierarchical LOD Builder to generates list of clusters that are together in vicinity and build as one actor
Definition at line 23 of file LODCluster.h.
Constructor & Destructor Documentation
FLODCluster() [1/5]
FLODCluster::FLODCluster (const FLODCluster & Other)
References FLODCluster(), and Other.
Referenced by FLODCluster(), FLODCluster(), Contains(), GetMergedCost(), MergeClusters(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator=(), operator==(), and SubtractCluster().
FLODCluster() [2/5]
FLODCluster::FLODCluster (FLODCluster && Other)
References FLODCluster(), and Other.
FLODCluster() [3/5]
FLODCluster::FLODCluster (AActor * Actor1)
FLODCluster() [4/5]
FLODCluster::FLODCluster (AActor * Actor1, AActor * Actor2)
FLODCluster() [5/5]
FLODCluster::FLODCluster ()
Member Function Documentation
AddActor()
FSphere FLODCluster::AddActor (AActor * NewActor) private
Adds a new actor to this cluster and updates the bounds accordingly, the filling factor is NOT updated.
Parameters
NewActor - Actor to be added to the cluster
Contains()
bool FLODCluster::Contains (FLODCluster & Other) const
Compare clusters and returns true when this contains any of Other's actors.
References FLODCluster(), and Other.
GetCost()
double FLODCluster::GetCost () const inline
Return cost of the cluster, lower is better.
Definition at line 50 of file LODCluster.h.
References ClusterCost.
GetMergedCost()
double FLODCluster::GetMergedCost (const FLODCluster & Other) const
Return cost of the union of this cluster & the other cluster, lower is better.
References FLODCluster(), and Other.
Invalidate()
void FLODCluster::Invalidate () inline
Invalidates this cluster.
Definition at line 44 of file LODCluster.h.
References bValid.
IsValid()
bool FLODCluster::IsValid () const inline
Returns whether or not this cluster is valid.
Definition at line 47 of file LODCluster.h.
References bValid.
MergeClusters()
void FLODCluster::MergeClusters (const FLODCluster & Other) private
Merges this cluster with Other by combining the actor arrays and updating the bounds, filling factor and cluster cost.
Parameters
Other - Other Cluster to merge with
References FLODCluster(), and Other.
operator+()
FLODCluster FLODCluster::operator+ (const FLODCluster & Other) const
Cluster operators.
References FLODCluster(), and Other.
operator+=()
FLODCluster & FLODCluster::operator+= (const FLODCluster & Other)
References FLODCluster(), and Other.
operator-()
FLODCluster FLODCluster::operator- (const FLODCluster & Other) const
References FLODCluster(), and Other.
operator-=()
FLODCluster & FLODCluster::operator-= (const FLODCluster & Other)
References FLODCluster(), and Other.
operator=() [1/2]
FLODCluster & FLODCluster::operator= (const FLODCluster & Other)
References FLODCluster(), and Other.
operator=() [2/2]
FLODCluster & FLODCluster::operator= (FLODCluster && Other)
References FLODCluster(), and Other.
operator==()
bool FLODCluster::operator== (const FLODCluster & Other) const
References FLODCluster(), and Other.
SubtractCluster()
void FLODCluster::SubtractCluster (const FLODCluster & Other) private
Subtracts the Other cluster from this cluster by removing Others actors and updating the bounds, filling factor and cluster cost This will invalidate the cluster if Actors.Num result to be 0.
Parameters
Other - Other cluster to subtract
References FLODCluster(), and Other.
ToString()
FString FLODCluster::ToString () const
Returns data/info for this Cluster as a string.
Field Documentation
Actors
TSet<AActor*, DefaultKeyFuncs<AActor*>, TInlineSetAllocator<2> > FLODCluster::Actors
List of Actors that this cluster contains.
Definition at line 66 of file LODCluster.h.
Bound
FSphere FLODCluster::Bound
Cluster bounds.
Definition at line 68 of file LODCluster.h.
bValid
bool FLODCluster::bValid private
Bool flag whether or not this cluster is valid.
Definition at line 98 of file LODCluster.h.
Referenced by Invalidate(), and IsValid().
ClusterCost
double FLODCluster::ClusterCost
Cached cluster cost, FMath::Pow(Bound.W, 3) / FillingFactor.
Definition at line 72 of file LODCluster.h.
Referenced by GetCost().
FillingFactor
double FLODCluster::FillingFactor
Filling factor for this cluster, determines how much of the cluster's bounds/area is occupied by the contained actors.
Definition at line 70 of file LODCluster.h.
The documentation for this struct was generated from the following file:
LODCluster.h