Unreal Engine 5.6 C++ API: TOneColorPixelShaderMRT Class Reference
TOneColorPixelShaderMRT Class Reference
Pixel shader for rendering a single, constant color to MRTs.
#include "OneColorShader.h"
Data Structures
class TOneColorPixelNumUintOutputs
class TOneColorPixelShader128bitRT
class TOneColorPixelShaderNumOutputs
Public Types
using FPermutationDomain = TShaderPermutationDomain<TOneColorPixelShaderNumOutputs, TOneColorPixelShader128bitRT, TOneColorPixelNumUintOutputs>
using ShaderMapType = FGlobalShaderMap
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FOneColorPS
using ShaderMapType = FGlobalShaderMap
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FGlobalShader
using FPermutationParameters = FGlobalShaderPermutationParameters
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FShader
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Public Member Functions
TOneColorPixelShaderMRT ()
TOneColorPixelShaderMRT (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
DECLARE_EXPORTED_TYPE_LAYOUT (TOneColorPixelShaderMRT, RENDERCORE_API, NonVirtual)
Public Member Functions inherited from FOneColorPS
FOneColorPS ()=default
FOneColorPS (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
DECLARE_EXPORTED_TYPE_LAYOUT (FOneColorPS, RENDERCORE_API, NonVirtual)
RENDERCORE_API void FillParameters (FParameters &Parameters, const FLinearColor *Colors, int32 NumColors)
Public Member Functions inherited from FGlobalShader
FGlobalShader ()=default
RENDERCORE_API FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
template<typename TViewUniformShaderParameters>
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHIUniformBuffer *ViewUniformBuffer)
Public Member Functions inherited from FShader
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static FShader * ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType &Initializer)
static FShader * ConstructSerializedInstance ()
static void GetPermutationIdStringImpl (int32 PermutationId, FString &OutString, bool bFullNames)
static RENDERCORE_API ShaderMetaType & GetStaticType ()
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static void ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static RENDERCORE_API void SetColors (FRHICommandList &RHICmdList, const TShaderMapRef< TOneColorPixelShaderMRT > &Shader, const FLinearColor *Colors, int32 NumColors)
static bool ShouldCompilePermutation (const FGlobalShaderPermutationParameters &Parameters)
static bool ShouldCompilePermutationImpl (const FShaderPermutationParameters &Parameters)
static EShaderPermutationPrecacheRequest ShouldPrecachePermutationImpl (const FShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FOneColorPS
static FShader * ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType &Initializer)
static FShader * ConstructSerializedInstance ()
static void GetPermutationIdStringImpl (int32 PermutationId, FString &OutString, bool bFullNames)
static const FShaderParametersMetadata * GetRootParametersMetadata ()
static RENDERCORE_API ShaderMetaType & GetStaticType ()
static void ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static RENDERCORE_API void SetColors (FRHICommandList &RHICmdList, const TShaderMapRef< FOneColorPS > &Shader, const FLinearColor *Colors, int32 NumColors)
static bool ShouldCompilePermutationImpl (const FShaderPermutationParameters &Parameters)
static EShaderPermutationPrecacheRequest ShouldPrecachePermutationImpl (const FShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FGlobalShader
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &Environment)
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Static Public Member Functions inherited from FShader
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Static Private Attributes
static FShaderTypeRegistration ShaderTypeRegistration
Additional Inherited Members
Protected Member Functions inherited from FShader
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Detailed Description
Pixel shader for rendering a single, constant color to MRTs.
Definition at line 98 of file OneColorShader.h.
Member Typedef Documentation
FPermutationDomain
using TOneColorPixelShaderMRT::FPermutationDomain = TShaderPermutationDomain<TOneColorPixelShaderNumOutputs, TOneColorPixelShader128bitRT, TOneColorPixelNumUintOutputs>
Definition at line 105 of file OneColorShader.h.
ShaderMapType
using TOneColorPixelShaderMRT::ShaderMapType = FGlobalShaderMap
Definition at line 100 of file OneColorShader.h.
ShaderMetaType
using TOneColorPixelShaderMRT::ShaderMetaType = FGlobalShaderType
Definition at line 100 of file OneColorShader.h.
Constructor & Destructor Documentation
TOneColorPixelShaderMRT() [1/2]
TOneColorPixelShaderMRT::TOneColorPixelShaderMRT ()
References TOneColorPixelShaderMRT().
Referenced by TOneColorPixelShaderMRT(), TOneColorPixelShaderMRT(), and ConstructCompiledInstance().
TOneColorPixelShaderMRT() [2/2]
TOneColorPixelShaderMRT::TOneColorPixelShaderMRT (const ShaderMetaType::CompiledShaderInitializerType & Initializer)
References TOneColorPixelShaderMRT().
Member Function Documentation
ConstructCompiledInstance()
FShader * TOneColorPixelShaderMRT::ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType & Initializer) inline static
Definition at line 100 of file OneColorShader.h.
References TOneColorPixelShaderMRT().
ConstructSerializedInstance()
FShader * TOneColorPixelShaderMRT::ConstructSerializedInstance () inline static
Definition at line 100 of file OneColorShader.h.
DECLARE_EXPORTED_TYPE_LAYOUT()
TOneColorPixelShaderMRT::DECLARE_EXPORTED_TYPE_LAYOUT (TOneColorPixelShaderMRT , RENDERCORE_API , NonVirtual)
GetPermutationIdStringImpl()
void TOneColorPixelShaderMRT::GetPermutationIdStringImpl (int32 PermutationId, FString & OutString, bool bFullNames) inline static
Definition at line 100 of file OneColorShader.h.
GetStaticType()
RENDERCORE_API ShaderMetaType & TOneColorPixelShaderMRT::GetStaticType () static
ModifyCompilationEnvironment()
void TOneColorPixelShaderMRT::ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
References ModifyCompilationEnvironment(), and UE_DEPRECATED.
Referenced by ModifyCompilationEnvironment().
ModifyCompilationEnvironmentImpl()
void TOneColorPixelShaderMRT::ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) inline static
Definition at line 100 of file OneColorShader.h.
SetColors()
RENDERCORE_API void TOneColorPixelShaderMRT::SetColors (FRHICommandList & RHICmdList, const TShaderMapRef< TOneColorPixelShaderMRT > & Shader, const FLinearColor * Colors, int32 NumColors) static
References SetColors().
Referenced by SetColors().
ShouldCompilePermutation()
bool TOneColorPixelShaderMRT::ShouldCompilePermutation (const FGlobalShaderPermutationParameters & Parameters) static
References bool, and ShouldCompilePermutation().
Referenced by ShouldCompilePermutation().
ShouldCompilePermutationImpl()
bool TOneColorPixelShaderMRT::ShouldCompilePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 100 of file OneColorShader.h.
ShouldPrecachePermutationImpl()
EShaderPermutationPrecacheRequest TOneColorPixelShaderMRT::ShouldPrecachePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 100 of file OneColorShader.h.
Field Documentation
ShaderTypeRegistration
FShaderTypeRegistration TOneColorPixelShaderMRT::ShaderTypeRegistration static private
Definition at line 100 of file OneColorShader.h.
The documentation for this class was generated from the following file:
OneColorShader.h