Unreal Engine 5.6 C++ API: FUIActionBinding Struct Reference
FUIActionBinding Struct Reference
#include "UIActionBinding.h"
Public Member Functions
FUIActionBinding ()=delete
FUIActionBinding (const FUIActionBinding &)=delete
FUIActionBinding (FUIActionBinding &&)=delete
COMMONUI_API void BeginHold ()
COMMONUI_API void BeginRollback (float TargetHoldRollbackTime, float HoldTime, FUIActionBindingHandle BindingHandle)
COMMONUI_API void CancelHold ()
DECLARE_MULTICAST_DELEGATE (FOnHoldActionPressed)
DECLARE_MULTICAST_DELEGATE (FOnHoldActionReleased)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnHoldActionProgressedMulticast, float)
COMMONUI_API FCommonInputActionDataBase * GetLegacyInputActionData () const
COMMONUI_API double GetSecondsHeld () const
COMMONUI_API bool IsHoldActive () const
bool operator== (const FUIActionBindingHandle &OtherHandle) const
COMMONUI_API EProcessHoldActionResult ProcessHoldInput (ECommonInputMode ActiveInputMode, FKey Key, EInputEvent InputEvent)
COMMONUI_API bool ProcessNormalInput (ECommonInputMode ActiveInputMode, FKey Key, EInputEvent InputEvent)
COMMONUI_API void ResetHold ()
COMMONUI_API FString ToDebugString () const
UE_DEPRECATED (5.6, "Calling FUIActionBinding::TryCreate without a user index is deprecated. Call the version with the UserIndex param.") static COMMONUI_API FUIActionBindingHandle TryCreate(const UWidget &InBoundWidget
COMMONUI_API bool UpdateHold (float TargetHoldTime)
Static Public Member Functions
static COMMONUI_API void CleanRegistrations ()
static COMMONUI_API TSharedPtr< FUIActionBinding > FindBinding (FUIActionBindingHandle Handle)
static COMMONUI_API FUIActionBindingHandle TryCreate (const UWidget &InBoundWidget, const FBindUIActionArgs &BindArgs, int32 UserIndex)
Data Fields
FText ActionDisplayName
FName ActionName
bool bConsumesInput = true
bool bDisplayInActionBar = false
const FBindUIActionArgs & BindArgs
bool bIsPersistent = false
TWeakObjectPtr< const UWidget > BoundWidget
FUIActionBindingHandle Handle
TArray< FUIActionKeyMapping > HoldMappings
TWeakObjectPtr< const UInputAction > InputAction
EInputEvent InputEvent
ECommonInputMode InputMode
TSet< ECommonInputType > InputTypesExemptFromValidKeyCheck
FDataTableRowHandle LegacyActionTableRow
TArray< FUIActionKeyMapping > NormalMappings
FSimpleDelegate OnExecuteAction
FOnHoldActionPressed OnHoldActionPressed
FOnHoldActionProgressedMulticast OnHoldActionProgressed
FOnHoldActionPressed OnHoldActionReleased
TWeakPtr< FActionRouterBindingCollection > OwningCollection
int32 PriorityWithinCollection = 0
int32 UserIndex = INDEX_NONE
Private Member Functions
COMMONUI_API FUIActionBinding (const UWidget &InBoundWidget, const FBindUIActionArgs &BindArgs)
Private Attributes
double CurrentHoldSecond = 0.0
FTSTicker::FDelegateHandle HoldProgressRollbackTickerHandle
double HoldRollbackMultiplier = 1.0
double HoldStartSecond = 0.0
double HoldStartTime = -1.0
double HoldTime = 0.0
Static Private Attributes
static COMMONUI_API TMap< FUIActionBindingHandle, TSharedPtr< FUIActionBinding > > AllRegistrationsByHandle
static COMMONUI_API TMap< FKey, FUIActionBindingHandle > CurrentHoldActionKeys
static COMMONUI_API int32 IdCounter
Friends
struct FUIActionBindingHandle
Detailed Description
Definition at line 29 of file UIActionBinding.h.
Constructor & Destructor Documentation
FUIActionBinding() [1/4]
FUIActionBinding::FUIActionBinding () delete
Referenced by FUIActionBinding(), FUIActionBinding(), and FindBinding().
FUIActionBinding() [2/4]
FUIActionBinding::FUIActionBinding (const FUIActionBinding &) delete
References FUIActionBinding().
FUIActionBinding() [3/4]
FUIActionBinding::FUIActionBinding (FUIActionBinding &&) delete
References FUIActionBinding().
FUIActionBinding() [4/4]
COMMONUI_API FUIActionBinding::FUIActionBinding (const UWidget & InBoundWidget, const FBindUIActionArgs & BindArgs) private
References BindArgs, and UE_API.
Member Function Documentation
BeginHold()
COMMONUI_API void FUIActionBinding::BeginHold ()
References UE_API.
BeginRollback()
COMMONUI_API void FUIActionBinding::BeginRollback (float TargetHoldRollbackTime, float HoldTime, FUIActionBindingHandle BindingHandle)
References FUIActionBindingHandle, HoldTime, and UE_API.
CancelHold()
COMMONUI_API void FUIActionBinding::CancelHold ()
References UE_API.
CleanRegistrations()
COMMONUI_API void FUIActionBinding::CleanRegistrations () static
References CleanRegistrations(), and UE_API.
Referenced by CleanRegistrations().
DECLARE_MULTICAST_DELEGATE() [1/2]
FUIActionBinding::DECLARE_MULTICAST_DELEGATE (FOnHoldActionPressed)
DECLARE_MULTICAST_DELEGATE() [2/2]
FUIActionBinding::DECLARE_MULTICAST_DELEGATE (FOnHoldActionReleased)
DECLARE_MULTICAST_DELEGATE_OneParam()
FUIActionBinding::DECLARE_MULTICAST_DELEGATE_OneParam (FOnHoldActionProgressedMulticast , float)
FindBinding()
COMMONUI_API TSharedPtr< FUIActionBinding > FUIActionBinding::FindBinding (FUIActionBindingHandle Handle) static
References FUIActionBinding(), FindBinding(), FUIActionBindingHandle, Handle, and UE_API.
Referenced by FindBinding().
GetLegacyInputActionData()
COMMONUI_API FCommonInputActionDataBase * FUIActionBinding::GetLegacyInputActionData () const
References UE_API.
GetSecondsHeld()
COMMONUI_API double FUIActionBinding::GetSecondsHeld () const
References UE_API.
IsHoldActive()
COMMONUI_API bool FUIActionBinding::IsHoldActive () const
References UE_API.
operator==()
bool FUIActionBinding::operator== (const FUIActionBindingHandle & OtherHandle) const inline
Definition at line 42 of file UIActionBinding.h.
References FUIActionBindingHandle, and Handle.
ProcessHoldInput()
COMMONUI_API EProcessHoldActionResult FUIActionBinding::ProcessHoldInput (ECommonInputMode ActiveInputMode, FKey Key, EInputEvent InputEvent)
References InputEvent, Key, and UE_API.
ProcessNormalInput()
COMMONUI_API bool FUIActionBinding::ProcessNormalInput (ECommonInputMode ActiveInputMode, FKey Key, EInputEvent InputEvent)
References InputEvent, Key, and UE_API.
ResetHold()
COMMONUI_API void FUIActionBinding::ResetHold ()
References UE_API.
ToDebugString()
COMMONUI_API FString FUIActionBinding::ToDebugString () const
References UE_API.
TryCreate()
COMMONUI_API FUIActionBindingHandle FUIActionBinding::TryCreate (const UWidget & InBoundWidget, const FBindUIActionArgs & BindArgs, int32 UserIndex) static
References BindArgs, FUIActionBindingHandle, TryCreate(), UE_API, and UserIndex.
Referenced by TryCreate().
UE_DEPRECATED()
FUIActionBinding::UE_DEPRECATED (5. 6, "Calling FUIActionBinding::TryCreate without a user index is deprecated. Call the version with the UserIndex param.") const &
UpdateHold()
COMMONUI_API bool FUIActionBinding::UpdateHold (float TargetHoldTime)
References UE_API.
Friends And Related Symbol Documentation
FUIActionBindingHandle
friend struct FUIActionBindingHandle friend
Definition at line 123 of file UIActionBinding.h.
References FUIActionBindingHandle.
Referenced by BeginRollback(), FindBinding(), FUIActionBindingHandle, operator==(), TryCreate(), and USTRUCT().
Field Documentation
ActionDisplayName
FText FUIActionBinding::ActionDisplayName
Definition at line 73 of file UIActionBinding.h.
ActionName
FName FUIActionBinding::ActionName
Definition at line 59 of file UIActionBinding.h.
AllRegistrationsByHandle
COMMONUI_API TMap<FUIActionBindingHandle, TSharedPtr<FUIActionBinding> > FUIActionBinding::AllRegistrationsByHandle static private
Definition at line 118 of file UIActionBinding.h.
bConsumesInput
bool FUIActionBinding::bConsumesInput = true
Definition at line 61 of file UIActionBinding.h.
bDisplayInActionBar
bool FUIActionBinding::bDisplayInActionBar = false
Definition at line 71 of file UIActionBinding.h.
BindArgs
const FBindUIActionArgs& FUIActionBinding::BindArgs
Definition at line 36 of file UIActionBinding.h.
Referenced by FUIActionBinding(), and TryCreate().
bIsPersistent
bool FUIActionBinding::bIsPersistent = false
Definition at line 62 of file UIActionBinding.h.
BoundWidget
TWeakObjectPtr<const UWidget> FUIActionBinding::BoundWidget
Definition at line 66 of file UIActionBinding.h.
CurrentHoldActionKeys
COMMONUI_API TMap<FKey, FUIActionBindingHandle> FUIActionBinding::CurrentHoldActionKeys static private
Definition at line 121 of file UIActionBinding.h.
CurrentHoldSecond
double FUIActionBinding::CurrentHoldSecond = 0.0 private
Definition at line 106 of file UIActionBinding.h.
Handle
FUIActionBindingHandle FUIActionBinding::Handle
Definition at line 77 of file UIActionBinding.h.
Referenced by FindBinding(), and operator==().
HoldMappings
TArray<FUIActionKeyMapping> FUIActionBinding::HoldMappings
Definition at line 80 of file UIActionBinding.h.
HoldProgressRollbackTickerHandle
FTSTicker::FDelegateHandle FUIActionBinding::HoldProgressRollbackTickerHandle private
Definition at line 115 of file UIActionBinding.h.
HoldRollbackMultiplier
double FUIActionBinding::HoldRollbackMultiplier = 1.0 private
Definition at line 109 of file UIActionBinding.h.
HoldStartSecond
double FUIActionBinding::HoldStartSecond = 0.0 private
Definition at line 103 of file UIActionBinding.h.
HoldStartTime
double FUIActionBinding::HoldStartTime = -1.0 private
Definition at line 100 of file UIActionBinding.h.
HoldTime
double FUIActionBinding::HoldTime = 0.0 private
Definition at line 112 of file UIActionBinding.h.
Referenced by BeginRollback().
IdCounter
COMMONUI_API int32 FUIActionBinding::IdCounter static private
Definition at line 117 of file UIActionBinding.h.
InputAction
TWeakObjectPtr<const UInputAction> FUIActionBinding::InputAction
Definition at line 94 of file UIActionBinding.h.
InputEvent
EInputEvent FUIActionBinding::InputEvent
Definition at line 60 of file UIActionBinding.h.
Referenced by ProcessHoldInput(), and ProcessNormalInput().
InputMode
ECommonInputMode FUIActionBinding::InputMode
Definition at line 67 of file UIActionBinding.h.
InputTypesExemptFromValidKeyCheck
TSet<ECommonInputType> FUIActionBinding::InputTypesExemptFromValidKeyCheck
Definition at line 72 of file UIActionBinding.h.
LegacyActionTableRow
FDataTableRowHandle FUIActionBinding::LegacyActionTableRow
Definition at line 92 of file UIActionBinding.h.
NormalMappings
TArray<FUIActionKeyMapping> FUIActionBinding::NormalMappings
Definition at line 79 of file UIActionBinding.h.
OnExecuteAction
FSimpleDelegate FUIActionBinding::OnExecuteAction
Definition at line 76 of file UIActionBinding.h.
OnHoldActionPressed
FOnHoldActionPressed FUIActionBinding::OnHoldActionPressed
Definition at line 86 of file UIActionBinding.h.
OnHoldActionProgressed
FOnHoldActionProgressedMulticast FUIActionBinding::OnHoldActionProgressed
Definition at line 83 of file UIActionBinding.h.
OnHoldActionReleased
FOnHoldActionPressed FUIActionBinding::OnHoldActionReleased
Definition at line 89 of file UIActionBinding.h.
OwningCollection
TWeakPtr<FActionRouterBindingCollection> FUIActionBinding::OwningCollection
Definition at line 75 of file UIActionBinding.h.
PriorityWithinCollection
int32 FUIActionBinding::PriorityWithinCollection = 0
Definition at line 64 of file UIActionBinding.h.
UserIndex
int32 FUIActionBinding::UserIndex = INDEX_NONE
Definition at line 69 of file UIActionBinding.h.
Referenced by TryCreate().
The documentation for this struct was generated from the following file:
UIActionBinding.h