Unreal Engine 5.6 C++ API: UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox Struct Reference
UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox Struct Reference
#include "SparseNarrowBandMeshSDF.h"
Public Member Functions
void Clamp (const FVector3i &OtherMin, const FVector3i &OtherMax)
bool IsValid () const
Data Fields
FVector3i BoxMax = FVector3i(INT32_MIN, INT32_MIN, INT32_MIN)
FVector3i BoxMin = FVector3i(INT32_MAX, INT32_MAX, INT32_MAX)
Detailed Description
template<class TriangleMeshType>
struct UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox
Definition at line 220 of file SparseNarrowBandMeshSDF.h.
Member Function Documentation
Clamp()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox::Clamp (const FVector3i & OtherMin, const FVector3i & OtherMax) inline
Definition at line 231 of file SparseNarrowBandMeshSDF.h.
References BoxMax, BoxMin, and FMath::Clamp().
IsValid()
template<class TriangleMeshType> bool UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox::IsValid () const inline
Definition at line 225 of file SparseNarrowBandMeshSDF.h.
References BoxMax, and BoxMin.
Field Documentation
BoxMax
template<class TriangleMeshType> FVector3i UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox::BoxMax = FVector3i(INT32_MIN, INT32_MIN, INT32_MIN)
Definition at line 223 of file SparseNarrowBandMeshSDF.h.
Referenced by Clamp(), and IsValid().
BoxMin
template<class TriangleMeshType> FVector3i UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriBBox::BoxMin = FVector3i(INT32_MAX, INT32_MAX, INT32_MAX)
Definition at line 222 of file SparseNarrowBandMeshSDF.h.
Referenced by Clamp(), and IsValid().
The documentation for this struct was generated from the following file:
SparseNarrowBandMeshSDF.h