Unreal Engine 5.6 C++ API: FEvent Class Reference
FEvent Class Reference abstract
Interface for waitable events.
#include "Event.h"
Public Member Functions
FEvent ()
Default constructor.
virtual ~FEvent ()
Virtual destructor.
void AdvanceStats ()
Advances stats associated with this event.
virtual bool IsManualReset ()=0
Whether the signaled state of this event needs to be reset manually.
virtual void Reset ()=0
Resets the event to an untriggered (waitable) state.
virtual void Trigger ()=0
Triggers the event so any waiting threads are activated.
UE_DEPRECATED (5.0, "Direct creation of FEvent is discouraged for performance reasons. Please use FPlatformProcess::GetSynchEventFromPool/ReturnSynchEventToPool.") virtual bool Create(bool bIsManualReset
Creates the event.
bool Wait ()
Waits an infinite amount of time for the event to be triggered.
bool Wait (const FTimespan &WaitTime, const bool bIgnoreThreadIdleStats=false)
Waits the specified amount of time for the event to be triggered.
virtual bool Wait (uint32 WaitTime, const bool bIgnoreThreadIdleStats=false)=0
Waits the specified amount of time for the event to be triggered.
Protected Member Functions
void ResetForStats ()
Resets start cycles to 0.
void TriggerForStats ()
Send to the stats a special message which encodes a trigger for the event.
void WaitForStats ()
Sends to the stats a special messages which encodes a wait for the event.
Protected Attributes
uint32 EventId
An unique id of this event.
TAtomic< uint32 > EventStartCycles
Greater than 0, if the event called wait.
Static Protected Attributes
static TAtomic< uint32 > EventUniqueId
Counter used to generate an unique id for the events.
Detailed Description
Interface for waitable events.
This interface has platform-specific implementations that are used to wait for another thread to signal that it is ready for the waiting thread to do some work. It can also be used for telling groups of threads to exit.
Consider using FEventRef as a safer and more convenient alternative.
Definition at line 20 of file Event.h.
Constructor & Destructor Documentation
FEvent()
FEvent::FEvent () inline
Default constructor.
Definition at line 93 of file Event.h.
References EventId, and EventStartCycles.
~FEvent()
virtual FEvent::~FEvent () inline virtual
Virtual destructor.
Definition at line 99 of file Event.h.
Member Function Documentation
AdvanceStats()
void FEvent::AdvanceStats ()
Advances stats associated with this event.
Used to monitor wait->trigger history.
IsManualReset()
virtual bool FEvent::IsManualReset () pure virtual
Whether the signaled state of this event needs to be reset manually.
Returns
true if the state requires manual resetting, false otherwise.
See also
Reset
Implemented in FPThreadEvent, and FSingleThreadEvent.
References IsManualReset().
Referenced by IsManualReset().
Reset()
virtual void FEvent::Reset () pure virtual
Resets the event to an untriggered (waitable) state.
See also
IsManualReset, Trigger
Implemented in FPThreadEvent, and FSingleThreadEvent.
References Reset().
Referenced by Reset().
ResetForStats()
void FEvent::ResetForStats () protected
Resets start cycles to 0.
Referenced by FPThreadEvent::Reset().
Trigger()
virtual void FEvent::Trigger () pure virtual
Triggers the event so any waiting threads are activated.
See also
IsManualReset, Reset
Implemented in FPThreadEvent, and FSingleThreadEvent.
References Trigger().
Referenced by Trigger().
TriggerForStats()
void FEvent::TriggerForStats () protected
Send to the stats a special message which encodes a trigger for the event.
Referenced by FPThreadEvent::Trigger().
UE_DEPRECATED()
FEvent::UE_DEPRECATED (5. 0, "Direct creation of FEvent is discouraged for performance reasons. Please use FPlatformProcess::GetSynchEventFromPool/ReturnSynchEventToPool.")
Creates the event.
Manually reset events stay triggered until reset. Named events share the same underlying event.
Parameters
bIsManualReset Whether the event requires manual reseting or not.
Returns
true if the event was created, false otherwise.
References Create.
Wait() [1/3]
bool FEvent::Wait () inline
Waits an infinite amount of time for the event to be triggered.
Returns
true if the event was triggered.
Definition at line 74 of file Event.h.
References MAX_uint32, Wait(), and Wait().
Referenced by Wait(), and Wait().
Wait() [2/3]
bool FEvent::Wait (const FTimespan & WaitTime, const bool bIgnoreThreadIdleStats = false) inline
Waits the specified amount of time for the event to be triggered.
Parameters
WaitTime The time to wait.
bIgnoreThreadIdleStats If true, ignores ThreadIdleStats
Returns
true if the event was triggered, false if the wait timed out.
Definition at line 86 of file Event.h.
References check, FMath::Clamp(), FTimespan::GetTicks(), MAX_uint32, ETimespan::TicksPerMillisecond, and Wait().
Wait() [3/3]
virtual bool FEvent::Wait (uint32 WaitTime, const bool bIgnoreThreadIdleStats = false) pure virtual
Waits the specified amount of time for the event to be triggered.
A wait time of MAX_uint32 is treated as infinite wait.
Parameters
WaitTime The time to wait (in milliseconds).
bIgnoreThreadIdleStats If true, ignores ThreadIdleStats
Returns
true if the event was triggered, false if the wait timed out.
Implemented in FPThreadEvent, and FSingleThreadEvent.
References Wait().
Referenced by ENUM_CLASS_FLAGS(), Wait(), and Wait().
WaitForStats()
void FEvent::WaitForStats () protected
Sends to the stats a special messages which encodes a wait for the event.
Field Documentation
EventId
uint32 FEvent::EventId protected
An unique id of this event.
Definition at line 121 of file Event.h.
Referenced by FEvent().
EventStartCycles
TAtomic<uint32> FEvent::EventStartCycles protected
Greater than 0, if the event called wait.
Definition at line 124 of file Event.h.
Referenced by FEvent().
EventUniqueId
TAtomic<uint32> FEvent::EventUniqueId static protected
Counter used to generate an unique id for the events.
Definition at line 118 of file Event.h.
The documentation for this class was generated from the following file:
Event.h