Unreal Engine 5.6 C++ API: FNavigationElementHandle Struct Reference
FNavigationElementHandle Struct Reference
Structure used to identify a unique navigation element registered in the Navigation system.
#include "NavigationElement.h"
Public Member Functions
FNavigationElementHandle ()=default
FNavigationElementHandle (const TWeakObjectPtr< const UObject > &WeakObject, const uint64 SubElementId=INDEX_NONE)
FNavigationElementHandle (const UObject *Object, const uint64 SubElementId=INDEX_NONE)
bool IsValid () const
operator bool () const
Conversion operator used to convert the handle to a boolean based on its validity.
bool operator!= (const FNavigationElementHandle &Other) const
bool operator== (const FNavigationElementHandle &Other) const
Static Public Attributes
static const FNavigationElementHandle Invalid
Private Attributes
TWeakObjectPtr< const UObject > OwnerUObject
Main mandatory part of the handle to associate it with either a UObject with a 1:1 relation with the registered navigation element, or a UObject that manages multiple non-UObject navigation elements.
uint64 SubElementId = INDEX_NONE
Second optional part of the handle used when the associated UObject manages multiple navigation elements.
Friends
uint32 GetTypeHash (const FNavigationElementHandle &Handle)
Hash function to use TSet/TMap.
FString LexToString (const FNavigationElementHandle &Handle)
Stringifies FNavigationElementHandle.
Detailed Description
Structure used to identify a unique navigation element registered in the Navigation system.
The handle can be created to represent two use cases:
Single UObject representing the navigation element constructed from a UObject raw or weak pointer
Single UObject managing multiple non-UObject navigation elements constructed from a UObject raw or weak pointer and using the optional constructor parameter to identity a unique sub-element
See also
FNavigationElement
Definition at line 33 of file NavigationElement.h.
Constructor & Destructor Documentation
FNavigationElementHandle() [1/3]
FNavigationElementHandle::FNavigationElementHandle () default
References FNavigationElementHandle(), Handle, INDEX_NONE, Object, Other, SubElementId, and WeakObject.
Referenced by FNavigationElementHandle(), GetTypeHash, LexToString, operator!=(), and operator==().
FNavigationElementHandle() [2/3]
FNavigationElementHandle::FNavigationElementHandle (const UObject * Object, const uint64 SubElementId = INDEX_NONE) inline explicit
Definition at line 335 of file NavigationElement.h.
References Object, OwnerUObject, and SubElementId.
FNavigationElementHandle() [3/3]
FNavigationElementHandle::FNavigationElementHandle (const TWeakObjectPtr< const UObject > & WeakObject, const uint64 SubElementId = INDEX_NONE) inline explicit
Definition at line 341 of file NavigationElement.h.
References OwnerUObject, SubElementId, and WeakObject.
Member Function Documentation
IsValid()
bool FNavigationElementHandle::IsValid () const inline
Returns
true if the handle has been properly assigned.
Definition at line 362 of file NavigationElement.h.
References Invalid.
operator bool()
FNavigationElementHandle::operator bool () const inline explicit
Conversion operator used to convert the handle to a boolean based on its validity.
See also
IsValid
Definition at line 357 of file NavigationElement.h.
References IsValid().
operator!=()
bool FNavigationElementHandle::operator!= (const FNavigationElementHandle & Other) const inline
Definition at line 352 of file NavigationElement.h.
References FNavigationElementHandle(), and Other.
operator==()
bool FNavigationElementHandle::operator== (const FNavigationElementHandle & Other) const inline
Definition at line 347 of file NavigationElement.h.
References FNavigationElementHandle(), Other, OwnerUObject, and SubElementId.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNavigationElementHandle & Handle) friend
Hash function to use TSet/TMap.
Definition at line 310 of file NavigationElement.h.
References FNavigationElementHandle(), GetTypeHash, GetTypeHash(), HashCombine(), and Key.
Referenced by GetTypeHash.
LexToString
FString LexToString (const FNavigationElementHandle & Handle) friend
Stringifies FNavigationElementHandle.
References FNavigationElementHandle(), and Handle.
Field Documentation
Invalid
const FNavigationElementHandle FNavigationElementHandle::Invalid static
Definition at line 35 of file NavigationElement.h.
Referenced by IsValid().
OwnerUObject
TWeakObjectPtr<const UObject> FNavigationElementHandle::OwnerUObject private
Main mandatory part of the handle to associate it with either a UObject with a 1:1 relation with the registered navigation element, or a UObject that manages multiple non-UObject navigation elements.
Definition at line 66 of file NavigationElement.h.
Referenced by FNavigationElementHandle(), FNavigationElementHandle(), and operator==().
SubElementId
uint64 FNavigationElementHandle::SubElementId = INDEX_NONE private
Second optional part of the handle used when the associated UObject manages multiple navigation elements.
Definition at line 71 of file NavigationElement.h.
Referenced by FNavigationElementHandle(), FNavigationElementHandle(), FNavigationElementHandle(), and operator==().
The documentation for this struct was generated from the following file:
NavigationElement.h