Unreal Engine 5.6 C++ API: FCbFieldIterator Class Reference
FCbFieldIterator Class Reference
Iterator for FCbField.
#include "CompactBinary.h"
Public Member Functions
constexpr FCbFieldIterator ()=default
Construct an empty field range.
void MakeOwned ()=delete
Call MakeRangeOwned() to make the range of the iterator owned.
void MakeRangeOwned ()
Clone the range, if necessary, to a buffer that this has ownership of.
Public Member Functions inherited from TCbFieldIterator< FCbField >
void AppendRangeHash (FIoHashBuilder &Builder) const
Append the hash of every field in the range.
constexpr TCbFieldIterator begin () const
DO NOT USE DIRECTLY.
void CopyRangeTo (FMutableMemoryView Buffer) const
Copy the field range into a buffer of exactly GetRangeSize() bytes.
constexpr FCbIteratorSentinel end () const
constexpr bool Equals (const TCbFieldIterator< OtherFieldType > &Other) const
FIoHash GetRangeHash () const
Calculate the hash of every field in the range.
uint64 GetRangeSize () const
Returns the size of the fields in the range in bytes.
void IterateRangeAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field range.
constexpr bool operator!= (const TCbFieldIterator< OtherFieldType > &Other) const
constexpr FCbField & operator* ()
TCbFieldIterator & operator++ ()
constexpr FCbField * operator-> ()
constexpr bool operator== (const TCbFieldIterator< OtherFieldType > &Other) const
void Reset ()
Reset this to an empty field range.
bool TryGetRangeView (FMemoryView &OutView) const
Try to get a view of every field in the range as they would be serialized.
Public Member Functions inherited from FCbField
FCbArray AsArray () &
Access the field as an array.
FCbArray AsArray () &&
FSharedBuffer AsBinary (const FSharedBuffer &Default=FSharedBuffer()) &
Access the field as binary.
FSharedBuffer AsBinary (const FSharedBuffer &Default=FSharedBuffer()) &&
FCbObject AsObject () &
Access the field as an object.
FCbObject AsObject () &&
FCompositeBuffer GetBuffer () const
Returns a buffer that contains the field as it would be serialized by CopyTo.
TCbBuffer ()=default
Construct a default value.
TCbBuffer (const ViewType &Value, FSharedBuffer OuterBuffer)
Construct a value that holds a reference to the buffer that contains it.
template<typename OtherViewType>
TCbBuffer (const ViewType &Value, TCbBuffer< OtherViewType > OuterBuffer)
Construct a value that holds a reference to the buffer of the outer that contains it.
TCbBuffer (FSharedBuffer ValueBuffer, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a value from a pointer to its data and an optional externally-provided type.
Public Member Functions inherited from TCbBuffer< FCbFieldView >
const FCbFieldView & AsView () const
Returns the value as a view.
FCbFieldIterator begin () const
DO NOT USE DIRECTLY.
FCbFieldIterator CreateIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
const FSharedBuffer & GetOuterBuffer () const &
Returns the outer buffer (if any) that contains this value.
bool IsOwned () const
Whether this reference has ownership of the memory in its buffer.
void MakeOwned ()
Clone the value, if necessary, to a buffer that this reference has ownership of.
FCbField operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
void Reset ()
Reset this to a default value and null buffer.
Public Member Functions inherited from FCbFieldView
constexpr FCbFieldView ()=default
Construct a field with no name and no value.
FCbFieldView (const FCbValue &Value)
Construct a field from a value, without access to the name.
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field from a pointer to its data and an optional externally-provided type.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the field, including the type and name.
FCbArrayView AsArrayView ()
Access the field as an array.
FIoHash AsAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an attachment.
FIoHash AsBinaryAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing a binary attachment.
FMemoryView AsBinaryView (FMemoryView Default=FMemoryView())
Access the field as binary.
bool AsBool (bool bDefault=false)
Access the field as a bool.
FMemoryView AsCustom (FUtf8StringView Name, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with a string identifier.
FMemoryView AsCustom (uint64 Id, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with an integer identifier.
FCbCustomById AsCustomById (FCbCustomById Default=FCbCustomById())
Access the field as a custom sub-type with an integer identifier.
FCbCustomByName AsCustomByName (FCbCustomByName Default=FCbCustomByName())
Access the field as a custom sub-type with a string identifier.
FDateTime AsDateTime ()
Access the field as a date/time.
FDateTime AsDateTime (FDateTime Default)
Access the field as a date/time.
int64 AsDateTimeTicks (int64 Default=0)
Access the field as a date/time tick count.
double AsDouble (double Default=0.0)
Access the field as a double.
float AsFloat (float Default=0.0f)
Access the field as a float.
FIoHash AsHash (const FIoHash &Default=FIoHash())
Access the field as a hash.
int16 AsInt16 (int16 Default=0)
Access the field as an int16.
int32 AsInt32 (int32 Default=0)
Access the field as an int32.
int64 AsInt64 (int64 Default=0)
Access the field as an int64.
int8 AsInt8 (int8 Default=0)
Access the field as an int8.
FIoHash AsObjectAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an object attachment.
FCbObjectId AsObjectId (const FCbObjectId &Default=FCbObjectId())
Access the field as an object identifier.
FCbObjectView AsObjectView ()
Access the field as an object.
FUtf8StringView AsString (FUtf8StringView Default=FUtf8StringView())
Access the field as a string.
FTimespan AsTimeSpan ()
Access the field as a timespan.
FTimespan AsTimeSpan (FTimespan Default)
Access the field as a timespan.
int64 AsTimeSpanTicks (int64 Default=0)
Access the field as a timespan tick count.
uint16 AsUInt16 (uint16 Default=0)
Access the field as a uint16.
uint32 AsUInt32 (uint32 Default=0)
Access the field as a uint32.
uint64 AsUInt64 (uint64 Default=0)
Access the field as a uint64.
uint8 AsUInt8 (uint8 Default=0)
Access the field as a uint8.
FGuid AsUuid ()
Access the field as a UUID.
FGuid AsUuid (const FGuid &Default)
Access the field as a UUID.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the field into an archive, including its type and name.
void CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
FCbFieldViewIterator CreateViewIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbFieldView &Other) const
Whether this field is identical to the other field.
constexpr ECbFieldError GetError () const
The type of error that occurred on the last field access, or None.
FIoHash GetHash () const
Calculate the hash of the field, including the type and name.
constexpr FUtf8StringView GetName () const
Returns the name of the field if it has a name, otherwise an empty view.
uint64 GetSize () const
Returns the size of the field in bytes, including the type and name.
FCbValue GetValue () const
Returns the value for unchecked access.
constexpr bool HasError () const
Whether the last field access encountered an error.
constexpr bool HasName () const
True if the field has a name.
constexpr bool HasValue () const
Whether the field has a value.
constexpr bool IsArray () const
constexpr bool IsAttachment () const
constexpr bool IsBinary () const
constexpr bool IsBinaryAttachment () const
constexpr bool IsBool () const
constexpr bool IsCustomById () const
constexpr bool IsCustomByName () const
constexpr bool IsDateTime () const
constexpr bool IsFloat () const
Whether the field is a float, or integer that supports implicit conversion.
constexpr bool IsHash () const
constexpr bool IsInteger () const
Whether the field is an integer of unspecified range and sign.
constexpr bool IsNull () const
constexpr bool IsObject () const
constexpr bool IsObjectAttachment () const
constexpr bool IsObjectId () const
constexpr bool IsString () const
constexpr bool IsTimeSpan () const
constexpr bool IsUuid () const
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
constexpr operator bool () const
Whether the field has a value.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
constexpr FCbFieldView RemoveName () const
Returns a copy of the field with the name removed.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the field as it would be serialized, such as by CopyTo.
Static Public Member Functions
static FCbFieldIterator CloneRange (const FCbFieldIterator &It)
Construct a field range from an owned clone of a range.
static FCbFieldIterator CloneRange (const FCbFieldViewIterator &It)
Construct a field range from an owned clone of a range.
static FCbFieldIterator MakeRange (FSharedBuffer Buffer, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field range from a buffer containing zero or more valid fields.
static FCbFieldIterator MakeRangeView (const FCbFieldViewIterator &It, FSharedBuffer OuterBuffer=FSharedBuffer())
Construct a field range from an iterator and its optional outer buffer.
static FCbFieldIterator MakeSingle (FCbField Field)
Construct a field range that contains exactly one field.
Static Public Member Functions inherited from TCbBufferFactory< FCbField, FCbFieldView >
static FCbField Clone (const void *const Data)
Construct a value from an owned clone of its memory.
static FCbField MakeView (const void *const Data, FSharedBuffer OuterBuffer=FSharedBuffer())
Construct a value from a read-only view of its memory and its optional outer buffer.
Private Member Functions
constexpr TCbFieldIterator ()=default
Construct an empty field range.
constexpr TCbFieldIterator (FieldType &&InField, const void *InFieldsEnd)
Construct a field range from the first field and a pointer to the end of the last field.
constexpr TCbFieldIterator (FieldType InField)
Construct a field range that contains exactly one field.
Additional Inherited Members
Protected Member Functions inherited from FCbFieldView
void Assign (const void *InData, const ECbFieldType InType)
Assign a field from a pointer to its data and an optional externally-provided type.
constexpr ECbFieldType GetType () const
Returns the type of the field excluding flags.
constexpr ECbFieldType GetTypeWithFlags () const
Returns the type of the field including flags.
constexpr const void * GetValueData () const
Returns the start of the value.
const void * GetValueEnd () const
Returns the end of the value.
uint64 GetValueSize () const
Returns the size of the value in bytes, which is the field excluding the type and name.
FMemoryView GetValueView () const
Returns a view of the value, which excludes the type and name.
FMemoryView GetView () const
Returns a view of the field, including the type and name when present.
FMemoryView GetViewNoType () const
Returns a view of the name and value, which excludes the type.
Static Protected Member Functions inherited from TCbFieldIterator< FCbField >
static const void * GetFieldsEnd (const TCbFieldIterator< OtherFieldType > &It)
Returns the end of the last field, or null for an iterator at the end.
Detailed Description
Iterator for FCbField.
See also
TCbFieldIterator
Definition at line 1287 of file CompactBinary.h.
Constructor & Destructor Documentation
FCbFieldIterator()
FCbFieldIterator::FCbFieldIterator () constexpr default
Construct an empty field range.
Referenced by CloneRange(), CloneRange(), MakeRange(), MakeRangeView(), and MakeSingle().
Member Function Documentation
CloneRange() [1/2]
FCbFieldIterator FCbFieldIterator::CloneRange (const FCbFieldIterator & It) inline static nodiscard
Construct a field range from an owned clone of a range.
Definition at line 1294 of file CompactBinary.h.
References FCbFieldIterator(), and CloneRange().
CloneRange() [2/2]
FCbFieldIterator FCbFieldIterator::CloneRange (const FCbFieldViewIterator & It) static nodiscard
Construct a field range from an owned clone of a range.
References FCbFieldIterator().
Referenced by CloneRange(), and MakeRangeOwned().
MakeOwned()
void FCbFieldIterator::MakeOwned () delete
Call MakeRangeOwned() to make the range of the iterator owned.
References TCbFieldIterator< FieldType >::TCbFieldIterator.
MakeRange()
FCbFieldIterator FCbFieldIterator::MakeRange (FSharedBuffer Buffer, ECbFieldType Type = ECbFieldType::HasFieldType) inline static nodiscard
Construct a field range from a buffer containing zero or more valid fields.
Parameters
Buffer A buffer containing zero or more valid fields.
Type HasFieldType means that Buffer contains the type. Otherwise, use the given type.
Definition at line 1311 of file CompactBinary.h.
References FCbFieldIterator(), TCbBuffer< FCbFieldView >::Buffer, HasFieldType, and MoveTemp().
MakeRangeOwned()
void FCbFieldIterator::MakeRangeOwned () inline
Clone the range, if necessary, to a buffer that this has ownership of.
Definition at line 1331 of file CompactBinary.h.
References CloneRange(), and TCbBuffer< FCbFieldView >::IsOwned().
MakeRangeView()
FCbFieldIterator FCbFieldIterator::MakeRangeView (const FCbFieldViewIterator & It, FSharedBuffer OuterBuffer = FSharedBuffer()) inline static nodiscard
Construct a field range from an iterator and its optional outer buffer.
Definition at line 1322 of file CompactBinary.h.
References FCbFieldIterator(), TCbFieldIterator< FCbField >::GetFieldsEnd(), and MoveTemp().
Referenced by TCbBuffer< ViewType >::CreateIterator().
MakeSingle()
FCbFieldIterator FCbFieldIterator::MakeSingle (FCbField Field) inline static nodiscard
Construct a field range that contains exactly one field.
Definition at line 1300 of file CompactBinary.h.
References FCbFieldIterator(), and MoveTemp().
TCbFieldIterator() [1/3]
TCbFieldIterator< FieldType >::TCbFieldIterator () constexpr private default
Construct an empty field range.
TCbFieldIterator() [2/3]
TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType && InField, const void * InFieldsEnd) inline constexpr private
Construct a field range from the first field and a pointer to the end of the last field.
Parameters
InField The first field, or the default field if there are no fields.
InFieldsEnd A pointer to the end of the value of the last field, or null.
Definition at line 437 of file CompactBinary.h.
TCbFieldIterator() [3/3]
TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType InField) inline explicit constexpr private
Construct a field range that contains exactly one field.
Definition at line 425 of file CompactBinary.h.
The documentation for this class was generated from the following file:
CompactBinary.h