Unreal Engine 5.6 C++ API: FInstancedStaticMeshComponentHelper Class Reference
FInstancedStaticMeshComponentHelper Class Reference
Helper class used to share implementation for different InstancedStaticMeshComponent types.
#include "InstancedStaticMeshComponentHelper.h"
Data Structures
class FDummyStaticMeshInstanceBuffer
Static Public Member Functions
template<class T>
static void CollectPSOPrecacheData (const T &Component, const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams)
template<class T>
static bool DoCustomNavigableGeometryExport (const T &Component, FNavigableGeometryExport &GeomExport, const FNavDataPerInstanceTransformDelegate &Delegate)
template<class T>
static FBox GetInstanceNavigationBounds (const T &Component)
template<class T>
static void GetNavigationData (const T &Component, FNavigationRelevantData &Data, const FNavDataPerInstanceTransformDelegate &Delegate)
template<class T>
static void GetNavigationPerInstanceTransforms (const T &Component, const FBox &AreaBox, TArray< FTransform > &InstanceData)
Static Private Attributes
static TGlobalResource< FDummyStaticMeshInstanceBuffer > DummyStaticMeshInstanceBuffer
Detailed Description
Helper class used to share implementation for different InstancedStaticMeshComponent types.
Definition at line 17 of file InstancedStaticMeshComponentHelper.h.
Member Function Documentation
CollectPSOPrecacheData()
template<class T> void FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData (const T & Component, const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) static
Definition at line 51 of file InstancedStaticMeshComponentHelper.h.
References FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), Component, Default, DummyStaticMeshInstanceBuffer, FInstancedStaticMeshVertexFactory::GetVertexElements(), FInstancedStaticMeshVertexFactory::InitInstancedStaticMeshVertexFactoryComponents(), LightMapCoordinateIndex, Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy(), FNaniteVertexFactory::StaticType, and UseGPUScene().
DoCustomNavigableGeometryExport()
template<class T> bool FInstancedStaticMeshComponentHelper::DoCustomNavigableGeometryExport (const T & Component, FNavigableGeometryExport & GeomExport, const FNavDataPerInstanceTransformDelegate & Delegate) static
Definition at line 108 of file InstancedStaticMeshComponentHelper.h.
References BodySetup, Component, FNavigableGeometryExport::ExportRigidBodySetup(), UE::Math::TTransform< double >::Identity, NavCollision, FNavigableGeometryExport::SetNavDataPerInstanceTransformDelegate(), and StaticMesh.
GetInstanceNavigationBounds()
template<class T> FBox FInstancedStaticMeshComponentHelper::GetInstanceNavigationBounds (const T & Component) static
Definition at line 163 of file InstancedStaticMeshComponentHelper.h.
References Component, UE::Math::TBox< T >::IsValid, Mesh, and NavCollision.
Referenced by GetNavigationPerInstanceTransforms().
GetNavigationData()
template<class T> void FInstancedStaticMeshComponentHelper::GetNavigationData (const T & Component, FNavigationRelevantData & Data, const FNavDataPerInstanceTransformDelegate & Delegate) static
Definition at line 87 of file InstancedStaticMeshComponentHelper.h.
References FPrimitiveComponentHelper::AddNavigationModifier(), Component, UE::Math::TTransform< double >::Identity, FCompositeNavModifier::MarkAsPerInstanceModifier(), FNavigationRelevantData::Modifiers, NavCollision, FNavigationRelevantData::NavDataPerInstanceTransformDelegate, and StaticMesh.
GetNavigationPerInstanceTransforms()
template<class T> void FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms (const T & Component, const FBox & AreaBox, TArray< FTransform > & InstanceData) static
Definition at line 141 of file InstancedStaticMeshComponentHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), Component, UE::Math::TBoxSphereBounds< T, TExtent >::GetBox(), GetInstanceNavigationBounds(), UE::Math::TTransform< T >::GetScale3D(), UE::Math::TBox< T >::Intersect(), UE::Math::TBox< T >::InverseTransformBy(), UE::Math::TBox< T >::IsValid, UE::Math::TVector< T >::IsZero(), and UE::Math::TBox< T >::TransformBy().
Field Documentation
DummyStaticMeshInstanceBuffer
TGlobalResource<FDummyStaticMeshInstanceBuffer> FInstancedStaticMeshComponentHelper::DummyStaticMeshInstanceBuffer static private
Definition at line 47 of file InstancedStaticMeshComponentHelper.h.
Referenced by CollectPSOPrecacheData().
The documentation for this class was generated from the following file:
InstancedStaticMeshComponentHelper.h