Unreal Engine 5.6 C++ API: FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf > Class Template Reference
FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf > Class Template Reference
#include "StaticSpatialIndex.h"
Data Structures
struct FNode
Public Member Functions
TRTreeImpl (const TStaticSpatialIndexDataInterface< Profile > &InDataInterface)
bool ForEachElement (TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FBox &InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FStaticSpatialIndex::FCone &InCone, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElement (const FStaticSpatialIndex::FSphere &InSphere, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
uint32 GetAllocatedSize () const
void Init ()
Public Member Functions inherited from FStaticSpatialIndex::TImpl< Profile >
TImpl (const TStaticSpatialIndexDataInterface< Profile > &InDataInterface)
Protected Member Functions
bool ForEachElementRecursive (const FNode *InNode, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElementRecursive (const FNode *InNode, const FBox &InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElementRecursive (const FNode *InNode, const FVector &InConeCenter, typename Profile::FReal InRadiusSquared, const FVector &InAxis, float InAngle, float InSinHalfAngle, float InCosHalfAngle, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
bool ForEachIntersectingElementRecursive (const FNode *InNode, const FVector &InSphereCenter, typename Profile::FReal InRadiusSquared, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const
Protected Attributes
FNode RootNode
Protected Attributes inherited from FStaticSpatialIndex::TImpl< Profile >
const TStaticSpatialIndexDataInterface< Profile > & DataInterface
Private Types
using FBox = typename Profile::FBox
using FVector = typename Profile::FVector
Detailed Description
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64>
class FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >
Definition at line 397 of file StaticSpatialIndex.h.
Member Typedef Documentation
FBox
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> using FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FBox = typename Profile::FBox private
Definition at line 400 of file StaticSpatialIndex.h.
FVector
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> using FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FVector = typename Profile::FVector private
Definition at line 399 of file StaticSpatialIndex.h.
Constructor & Destructor Documentation
TRTreeImpl()
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::TRTreeImpl (const TStaticSpatialIndexDataInterface< Profile > & InDataInterface) inline
Definition at line 403 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TImpl< Profile >::TImpl().
Member Function Documentation
ForEachElement()
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachElement (TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 484 of file StaticSpatialIndex.h.
References ForEachElementRecursive(), and RootNode.
ForEachElementRecursive()
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachElementRecursive (const FNode * InNode, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline protected
Definition at line 587 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, and ForEachElementRecursive().
Referenced by ForEachElement(), and ForEachElementRecursive().
ForEachIntersectingElement() [1/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElement (const FBox & InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 489 of file StaticSpatialIndex.h.
References ForEachIntersectingElementRecursive(), and RootNode.
ForEachIntersectingElement() [2/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElement (const FStaticSpatialIndex::FCone & InCone, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 500 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::FCone::Angle, FStaticSpatialIndex::FCone::Axis, FStaticSpatialIndex::FSphere::Center, ForEachIntersectingElementRecursive(), FStaticSpatialIndex::FSphere::Radius, RootNode, FMath::Square(), and UE_PI.
ForEachIntersectingElement() [3/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElement (const FStaticSpatialIndex::FSphere & InSphere, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline
Definition at line 494 of file StaticSpatialIndex.h.
References ForEachIntersectingElementRecursive(), RootNode, and FMath::Square().
ForEachIntersectingElementRecursive() [1/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive (const FNode * InNode, const FBox & InBox, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline protected
Definition at line 613 of file StaticSpatialIndex.h.
References Box, FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, FStaticSpatialIndex::TImpl< Profile >::DataInterface, and ForEachIntersectingElementRecursive().
Referenced by ForEachIntersectingElement(), ForEachIntersectingElement(), ForEachIntersectingElement(), ForEachIntersectingElementRecursive(), ForEachIntersectingElementRecursive(), and ForEachIntersectingElementRecursive().
ForEachIntersectingElementRecursive() [2/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive (const FNode * InNode, const FVector & InConeCenter, typename Profile::FReal InRadiusSquared, const FVector & InAxis, float InAngle, float InSinHalfAngle, float InCosHalfAngle, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline protected
Definition at line 685 of file StaticSpatialIndex.h.
References Box, FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, FStaticSpatialIndex::TImpl< Profile >::DataInterface, FStaticSpatialIndex::FastConeAABBIntersection(), FStaticSpatialIndex::FastSphereAABBIntersection(), and ForEachIntersectingElementRecursive().
ForEachIntersectingElementRecursive() [3/3]
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> bool FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive (const FNode * InNode, const FVector & InSphereCenter, typename Profile::FReal InRadiusSquared, TFunctionRef< bool(uint32 InValueIndex)> InFunc) const inline protected
Definition at line 649 of file StaticSpatialIndex.h.
References Box, FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, FStaticSpatialIndex::TImpl< Profile >::DataInterface, FStaticSpatialIndex::FastSphereAABBIntersection(), and ForEachIntersectingElementRecursive().
GetAllocatedSize()
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> uint32 FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::GetAllocatedSize () const inline
Definition at line 508 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, and RootNode.
Init()
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> void FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::Init () inline
Definition at line 407 of file StaticSpatialIndex.h.
References FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::BoxMax, FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::BoxMin, check, FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::FNode::Content, FStaticSpatialIndex::TImpl< Profile >::DataInterface, TArray< InElementType, InAllocatorType >::Emplace_GetRef(), ForceInit, MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), and RootNode.
Field Documentation
RootNode
template<typename Profile, int32 MaxNumElementsPerNode = 16, int32 MaxNumElementsPerLeaf = 64> FNode FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::RootNode protected
Definition at line 720 of file StaticSpatialIndex.h.
Referenced by ForEachElement(), ForEachIntersectingElement(), ForEachIntersectingElement(), ForEachIntersectingElement(), GetAllocatedSize(), and Init().
The documentation for this class was generated from the following file:
StaticSpatialIndex.h