Unreal Engine 5.6 C++ API: FMovieSceneInterrogationKey Struct Reference
FMovieSceneInterrogationKey Struct Reference
Key used for populating template interrogation data.
#include "MovieSceneTemplateInterrogation.h"
Public Member Functions
FMovieSceneInterrogationKey (FMovieSceneAnimTypeID InAnimTypeID)
Static Public Member Functions
static MOVIESCENE_API FMovieSceneInterrogationKey GetTransformInterrogationKey ()
Access the interrogation key for transform data - any interrogation data stored with this key is guaranteed to be of type 'FTransform' to be used by various editors and sections that reference transforms.
Data Fields
FMovieSceneAnimTypeID AnimTypeID
Unique identifier for the type of data that resulted from the interrogation - doesn't at all have to relate to any FMovieSceneAnimTypeIDs used at runtime.
Friends
bool operator!= (FMovieSceneInterrogationKey A, FMovieSceneInterrogationKey B)
bool operator== (FMovieSceneInterrogationKey A, FMovieSceneInterrogationKey B)
Detailed Description
Key used for populating template interrogation data.
Definition at line 21 of file MovieSceneTemplateInterrogation.h.
Constructor & Destructor Documentation
FMovieSceneInterrogationKey()
FMovieSceneInterrogationKey::FMovieSceneInterrogationKey (FMovieSceneAnimTypeID InAnimTypeID) inline
Definition at line 26 of file MovieSceneTemplateInterrogation.h.
References AnimTypeID.
Referenced by GetTransformInterrogationKey(), operator!=, and operator==.
Member Function Documentation
GetTransformInterrogationKey()
MOVIESCENE_API FMovieSceneInterrogationKey FMovieSceneInterrogationKey::GetTransformInterrogationKey () static
Access the interrogation key for transform data - any interrogation data stored with this key is guaranteed to be of type 'FTransform' to be used by various editors and sections that reference transforms.
References FMovieSceneInterrogationKey().
Referenced by TPropertyActuator< PropertyType >::Actuate(), and TPropertyActuator< PropertyType >::Actuate().
Friends And Related Symbol Documentation
operator!=
bool operator!= (FMovieSceneInterrogationKey A, FMovieSceneInterrogationKey B) friend
Definition at line 34 of file MovieSceneTemplateInterrogation.h.
References FMovieSceneInterrogationKey(), A, and B.
operator==
bool operator== (FMovieSceneInterrogationKey A, FMovieSceneInterrogationKey B) friend
Definition at line 30 of file MovieSceneTemplateInterrogation.h.
References FMovieSceneInterrogationKey(), A, and B.
Field Documentation
AnimTypeID
FMovieSceneAnimTypeID FMovieSceneInterrogationKey::AnimTypeID
Unique identifier for the type of data that resulted from the interrogation - doesn't at all have to relate to any FMovieSceneAnimTypeIDs used at runtime.
Definition at line 24 of file MovieSceneTemplateInterrogation.h.
Referenced by FMovieSceneInterrogationKey().
The documentation for this struct was generated from the following file:
MovieSceneTemplateInterrogation.h