Unreal Engine 5.6 C++ API: FPackageFileVersion Struct Reference
FPackageFileVersion Struct Reference
This object combines all of our version enums into a single easy to use structure which allows us to update older version numbers independently of the newer version numbers.
#include "ObjectVersion.h"
Public Member Functions
FPackageFileVersion ()=default
FPackageFileVersion (int32 UE4Version, EUnrealEngineObjectUE5Version UE5Version)
bool IsCompatible (const FPackageFileVersion &Other) const
Returns true if this object is compatible with the FPackageFileVersion passed in as the parameter.
bool operator!= (const FPackageFileVersion &Other) const
FPackageFileVersion comparisons.
bool operator!= (EUnrealEngineObjectUE4Version Version) const
UE4 version comparisons.
bool operator!= (EUnrealEngineObjectUE5Version Version) const
UE5 version comparisons.
bool operator< (EUnrealEngineObjectUE4Version Version) const
UE4 version comparisons.
bool operator< (EUnrealEngineObjectUE5Version Version) const
UE5 version comparisons.
bool operator== (const FPackageFileVersion &Other) const
FPackageFileVersion comparisons.
bool operator>= (EUnrealEngineObjectUE4Version Version) const
UE4 version comparisons.
bool operator>= (EUnrealEngineObjectUE5Version Version) const
UE5 version comparisons.
void Reset ()
Set all versions to the default state.
int32 ToValue () const
Returns the highest valid version number which is considered to be the 'true' version number.
Static Public Member Functions
static FPackageFileVersion CreateUE4Version (EUnrealEngineObjectUE4Version Version)
static FPackageFileVersion CreateUE4Version (int32 Version)
Creates and returns a FPackageFileVersion based on a single EUnrealEngineObjectUEVersion and no other versions.
Data Fields
int32 FileVersionUE4 = 0
int32 FileVersionUE5 = 0
Private Member Functions
bool TryRead (const FCbFieldView &FieldView)
FCbWriter & Write (FCbWriter &Writer) const
Friends
bool LoadFromCompactBinary (const FCbFieldView &FieldView, FPackageFileVersion &Version)
FArchive & operator<< (FArchive &Ar, FPackageFileVersion &Version)
Serialization members.
FCbWriter & operator<< (FCbWriter &Writer, const FPackageFileVersion &Version)
Serialization members implemented as hidden friends.
Detailed Description
This object combines all of our version enums into a single easy to use structure which allows us to update older version numbers independently of the newer version numbers.
Definition at line 758 of file ObjectVersion.h.
Constructor & Destructor Documentation
FPackageFileVersion() [1/2]
FPackageFileVersion::FPackageFileVersion () default
Referenced by CreateUE4Version(), CreateUE4Version(), IsCompatible(), LoadFromCompactBinary, operator!=(), operator<<, operator<<, and operator==().
FPackageFileVersion() [2/2]
FPackageFileVersion::FPackageFileVersion (int32 UE4Version, EUnrealEngineObjectUE5Version UE5Version) inline
Definition at line 761 of file ObjectVersion.h.
References FileVersionUE4, and FileVersionUE5.
Member Function Documentation
CreateUE4Version() [1/2]
FPackageFileVersion FPackageFileVersion::CreateUE4Version (EUnrealEngineObjectUE4Version Version) static
References FPackageFileVersion().
CreateUE4Version() [2/2]
FPackageFileVersion FPackageFileVersion::CreateUE4Version (int32 Version) static
Creates and returns a FPackageFileVersion based on a single EUnrealEngineObjectUEVersion and no other versions.
References FPackageFileVersion().
Referenced by FPackageFileSummary::InvalidateFileVersion().
IsCompatible()
bool FPackageFileVersion::IsCompatible (const FPackageFileVersion & Other) const inline
Returns true if this object is compatible with the FPackageFileVersion passed in as the parameter.
This means that all version numbers for the current object are equal or greater than the corresponding version numbers of the other structure.
Definition at line 833 of file ObjectVersion.h.
References FPackageFileVersion(), FileVersionUE4, FileVersionUE5, and Other.
operator!=() [1/3]
bool FPackageFileVersion::operator!= (const FPackageFileVersion & Other) const inline
FPackageFileVersion comparisons.
Definition at line 845 of file ObjectVersion.h.
References FPackageFileVersion(), and Other.
operator!=() [2/3]
bool FPackageFileVersion::operator!= (EUnrealEngineObjectUE4Version Version) const inline
UE4 version comparisons.
Definition at line 793 of file ObjectVersion.h.
References FileVersionUE4.
operator!=() [3/3]
bool FPackageFileVersion::operator!= (EUnrealEngineObjectUE5Version Version) const inline
UE5 version comparisons.
Definition at line 811 of file ObjectVersion.h.
References FileVersionUE5.
operator<() [1/2]
bool FPackageFileVersion::operator< (EUnrealEngineObjectUE4Version Version) const inline
UE4 version comparisons.
Definition at line 799 of file ObjectVersion.h.
References FileVersionUE4.
operator<() [2/2]
bool FPackageFileVersion::operator< (EUnrealEngineObjectUE5Version Version) const inline
UE5 version comparisons.
Definition at line 817 of file ObjectVersion.h.
References FileVersionUE5.
operator==()
bool FPackageFileVersion::operator== (const FPackageFileVersion & Other) const inline
FPackageFileVersion comparisons.
Definition at line 839 of file ObjectVersion.h.
References FPackageFileVersion(), FileVersionUE4, FileVersionUE5, and Other.
operator>=() [1/2]
bool FPackageFileVersion::operator>= (EUnrealEngineObjectUE4Version Version) const inline
UE4 version comparisons.
Definition at line 805 of file ObjectVersion.h.
References FileVersionUE4.
operator>=() [2/2]
bool FPackageFileVersion::operator>= (EUnrealEngineObjectUE5Version Version) const inline
UE5 version comparisons.
Definition at line 823 of file ObjectVersion.h.
References FileVersionUE5.
Reset()
void FPackageFileVersion::Reset () inline
Set all versions to the default state.
Definition at line 769 of file ObjectVersion.h.
References FileVersionUE4, and FileVersionUE5.
ToValue()
int32 FPackageFileVersion::ToValue () const inline
Returns the highest valid version number which is considered to be the 'true' version number.
Definition at line 780 of file ObjectVersion.h.
References FileVersionUE4, FileVersionUE5, and INITIAL_VERSION.
TryRead()
bool FPackageFileVersion::TryRead (const FCbFieldView & FieldView) private
Referenced by LoadFromCompactBinary.
Write()
FCbWriter & FPackageFileVersion::Write (FCbWriter & Writer) const private
Referenced by operator<<.
Friends And Related Symbol Documentation
LoadFromCompactBinary
bool LoadFromCompactBinary (const FCbFieldView & FieldView, FPackageFileVersion & Version) friend
Definition at line 859 of file ObjectVersion.h.
References FPackageFileVersion(), and TryRead().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPackageFileVersion & Version) friend
Serialization members.
References FPackageFileVersion(), and Ar.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FPackageFileVersion & Version) friend
Serialization members implemented as hidden friends.
Definition at line 854 of file ObjectVersion.h.
References FPackageFileVersion(), and Write().
Field Documentation
FileVersionUE4
int32 FPackageFileVersion::FileVersionUE4 = 0
Definition at line 867 of file ObjectVersion.h.
Referenced by FPackageFileVersion(), IsCompatible(), operator!=(), operator<(), operator==(), operator>=(), Reset(), ToValue(), and UObjectBaseUtility::UE_DEPRECATED().
FileVersionUE5
int32 FPackageFileVersion::FileVersionUE5 = 0
Definition at line 869 of file ObjectVersion.h.
Referenced by FPackageFileVersion(), IsCompatible(), operator!=(), operator<(), operator==(), operator>=(), Reset(), and ToValue().
The documentation for this struct was generated from the following file:
ObjectVersion.h