Unreal Engine 5.6 C++ API: UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid Struct Reference
UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid Struct Reference
#include "SparseNarrowBandMeshSDF.h"
Public Types
typedef TBlockedGrid3Layout< FBlockedGrid3f::BlockSize > MyLayout
Public Types inherited from UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >
typedef TBlockData3Layout< BlockSize_ > FBlockData3Layout
Public Member Functions
FTriIDBlockGrid (const FScatterCounter &TriCounter, bool bInitParallel)
void AddTriID (const int32 &BlockIndex, const int32 &TriId)
TArray< int32 > GetOccupiedBlockIDs () const
Public Member Functions inherited from UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >
TBlockedGrid3Layout ()
TBlockedGrid3Layout (FVector3i Dims)
TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK)
int32 BlockIJKToBlockIndex (const FVector3i &BlockIJK) const
FVector3i BlockIndexToBlockIJK (const int32 BlockIndex) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
void GetBlockAndLocalIndex (const FVector3i &IJK, int32 &BlockIndexOut, int32 &LocalIndexOut) const
return the block index and local index of the cell at (I,J,K).
void GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 &BlockIndexOut, int32 &LocalIndexOut) const
const FVector3i & GetBlockDimensions () const
const FVector3i & GetDimensions () const
int32 IJKtoBlockIndex (const FVector3i &IJK) const
bool IsValidBlockIJK (const FVector3i &BlockIJK)
bool IsValidIJK (const FVector3i &IJK) const
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Recompute the block dimensions required to cover the requested cell dimensions.
int64 Size () const
Data Fields
TArray< std::atomic< int > > PerBlockNum
TArray< TArray< int32 > > TrisInBlock
Additional Inherited Members
Static Public Attributes inherited from UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >
static constexpr int32 BlockElemCount
static constexpr int32 BlockSize
Protected Attributes inherited from UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >
FVector3i BlockDimensions
FVector3i Dimensions
Detailed Description
template<class TriangleMeshType>
struct UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid
Definition at line 160 of file SparseNarrowBandMeshSDF.h.
Member Typedef Documentation
MyLayout
template<class TriangleMeshType> typedef TBlockedGrid3Layout<FBlockedGrid3f::BlockSize> UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::MyLayout
Definition at line 162 of file SparseNarrowBandMeshSDF.h.
Constructor & Destructor Documentation
FTriIDBlockGrid()
template<class TriangleMeshType> UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::FTriIDBlockGrid (const FScatterCounter & TriCounter, bool bInitParallel) inline
Definition at line 164 of file SparseNarrowBandMeshSDF.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::GetBlockDimensions(), TArray< InElementType, InAllocatorType >::GetData(), UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::GetDimensions(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FScatterCounter::NumObjectsPerBlock, ParallelFor(), PerBlockNum, TrisInBlock, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Member Function Documentation
AddTriID()
template<class TriangleMeshType> void UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::AddTriID (const int32 & BlockIndex, const int32 & TriId) inline
Definition at line 184 of file SparseNarrowBandMeshSDF.h.
References TArray< InElementType, InAllocatorType >::GetData(), Num, PerBlockNum, and TrisInBlock.
GetOccupiedBlockIDs()
template<class TriangleMeshType> TArray< int32 > UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::GetOccupiedBlockIDs () const inline
Definition at line 192 of file SparseNarrowBandMeshSDF.h.
References TArray< InElementType, InAllocatorType >::Add(), Num, TArray< InElementType, InAllocatorType >::Reserve(), and TrisInBlock.
Field Documentation
PerBlockNum
template<class TriangleMeshType> TArray<std::atomic<int> > UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::PerBlockNum
Definition at line 216 of file SparseNarrowBandMeshSDF.h.
Referenced by FTriIDBlockGrid(), and AddTriID().
TrisInBlock
template<class TriangleMeshType> TArray<TArray<int32> > UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::TrisInBlock
Definition at line 217 of file SparseNarrowBandMeshSDF.h.
Referenced by FTriIDBlockGrid(), AddTriID(), and GetOccupiedBlockIDs().
The documentation for this struct was generated from the following file:
SparseNarrowBandMeshSDF.h