Unreal Engine 5.6 C++ API: FPackageStoreEntryResource Struct Reference
FPackageStoreEntryResource Struct Reference
Package store entry resource.
#include "PackageStore.h"
Public Member Functions
FPackageId GetPackageId () const
Returns the package ID.
bool HasCookError () const
bool HasOptionalSegment () const
bool HasPackageData () const
bool IsAutoOptional () const
Returns whether this package was saved as auto optional.
Static Public Member Functions
static FPackageStoreEntryResource CreateEmptyPackage (FName PackageName, bool bHasCookError)
Creates a PackageStoreEntryResource that records a packagename and will be in an op with possible metadata stored in attachments, but for which the op has no packagedata.
static FPackageStoreEntryResource FromCbObject (FCbObjectView Obj)
Data Fields
EPackageStoreEntryFlags Flags = EPackageStoreEntryFlags::None
The package store entry flags.
TArray< FPackageId > ImportedPackageIds
Imported package IDs.
TArray< FPackageId > OptionalSegmentImportedPackageIds
Editor data imported package IDs.
FPackageId PackageId
FName PackageName
The package name.
TArray< FSHAHash > ShaderMapHashes
Referenced shader map hashes.
TArray< FPackageId > SoftPackageReferences
Soft package references.
Friends
FArchive & operator<< (FArchive &Ar, FPackageStoreEntryResource &PackageStoreEntry)
FCbWriter & operator<< (FCbWriter &Writer, const FPackageStoreEntryResource &PackageStoreEntry)
Detailed Description
Package store entry resource.
This is a non-optimized serializable version of a package store entry. Used when cooking and when running cook-on-the-fly.
Definition at line 96 of file PackageStore.h.
Member Function Documentation
CreateEmptyPackage()
FPackageStoreEntryResource FPackageStoreEntryResource::CreateEmptyPackage (FName PackageName, bool bHasCookError) static
Creates a PackageStoreEntryResource that records a packagename and will be in an op with possible metadata stored in attachments, but for which the op has no packagedata.
This is used for tracking build dependencies on packages even if those packages fail to cook due to error or editoronly.
References PackageName.
FromCbObject()
FPackageStoreEntryResource FPackageStoreEntryResource::FromCbObject (FCbObjectView Obj) static
GetPackageId()
FPackageId FPackageStoreEntryResource::GetPackageId () const inline
Returns the package ID.
Definition at line 113 of file PackageStore.h.
References PackageId.
HasCookError()
bool FPackageStoreEntryResource::HasCookError () const inline
Definition at line 134 of file PackageStore.h.
References EnumHasAnyFlags(), Flags, and HasCookError.
HasOptionalSegment()
bool FPackageStoreEntryResource::HasOptionalSegment () const inline
Definition at line 124 of file PackageStore.h.
References EnumHasAnyFlags(), Flags, and OptionalSegment.
HasPackageData()
bool FPackageStoreEntryResource::HasPackageData () const inline
Definition at line 129 of file PackageStore.h.
References EnumHasAnyFlags(), Flags, and HasPackageData.
IsAutoOptional()
bool FPackageStoreEntryResource::IsAutoOptional () const inline
Returns whether this package was saved as auto optional.
Definition at line 119 of file PackageStore.h.
References AutoOptional, EnumHasAnyFlags(), and Flags.
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPackageStoreEntryResource & PackageStoreEntry) friend
References Ar, and PackageStoreEntry.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FPackageStoreEntryResource & PackageStoreEntry) friend
References PackageStoreEntry.
Field Documentation
Flags
EPackageStoreEntryFlags FPackageStoreEntryResource::Flags = EPackageStoreEntryFlags::None
The package store entry flags.
Definition at line 99 of file PackageStore.h.
Referenced by HasCookError(), HasOptionalSegment(), HasPackageData(), and IsAutoOptional().
ImportedPackageIds
TArray<FPackageId> FPackageStoreEntryResource::ImportedPackageIds
Imported package IDs.
Definition at line 104 of file PackageStore.h.
OptionalSegmentImportedPackageIds
TArray<FPackageId> FPackageStoreEntryResource::OptionalSegmentImportedPackageIds
Editor data imported package IDs.
Definition at line 108 of file PackageStore.h.
PackageId
FPackageId FPackageStoreEntryResource::PackageId
Definition at line 102 of file PackageStore.h.
Referenced by GetPackageId().
PackageName
FName FPackageStoreEntryResource::PackageName
The package name.
Definition at line 101 of file PackageStore.h.
Referenced by CreateEmptyPackage().
ShaderMapHashes
TArray<FSHAHash> FPackageStoreEntryResource::ShaderMapHashes
Referenced shader map hashes.
Definition at line 106 of file PackageStore.h.
SoftPackageReferences
TArray<FPackageId> FPackageStoreEntryResource::SoftPackageReferences
Soft package references.
Definition at line 110 of file PackageStore.h.
The documentation for this struct was generated from the following file:
PackageStore.h