Unreal Engine 5.6 C++ API: TUTF16ToUTF32_Convert< InFromType, InToType > Class Template Reference
TUTF16ToUTF32_Convert< InFromType, InToType > Class Template Reference
#include "StringConv.h"
Public Types
typedef InFromType FromType
typedef InToType ToType
Static Public Member Functions
template<typename SrcBufferType UE_REQUIRES>
static FORCEINLINE void Convert (ToType *Dest, const int32 DestLen, const SrcBufferType *Source, const int32 SourceLen)
Converts the UTF-16 string to UTF-32.
template<typename SrcBufferType UE_REQUIRES>
static int32 ConvertedLength (const SrcBufferType *Source, const int32 SourceLen)
Determines the length of the converted string.
Static Private Member Functions
static uint32 CodepointFromUtf16 (const FromType *&SourceString, const uint32 SourceLengthRemaining)
template<typename DestBufferType>
static void Convert_Impl (DestBufferType &ConvertedBuffer, int32 DestLen, const FromType *Source, const int32 SourceLen)
Read Source string, converting the data from UTF-16 into UTF-32, and placing these in the Destination.
Detailed Description
template<typename InFromType, typename InToType>
class TUTF16ToUTF32_Convert< InFromType, InToType >
Definition at line 546 of file StringConv.h.
Member Typedef Documentation
FromType
template<typename InFromType, typename InToType> typedef InFromType TUTF16ToUTF32_Convert< InFromType, InToType >::FromType
Definition at line 552 of file StringConv.h.
ToType
template<typename InFromType, typename InToType> typedef InToType TUTF16ToUTF32_Convert< InFromType, InToType >::ToType
Definition at line 553 of file StringConv.h.
Member Function Documentation
CodepointFromUtf16()
template<typename InFromType, typename InToType> uint32 TUTF16ToUTF32_Convert< InFromType, InToType >::CodepointFromUtf16 (const FromType *& SourceString, const uint32 SourceLengthRemaining) inline static nodiscard private
Definition at line 592 of file StringConv.h.
References checkSlow, StringConv::EncodeSurrogate(), StringConv::IsHighSurrogate(), StringConv::IsLowSurrogate(), and UNICODE_BOGUS_CHAR_CODEPOINT.
Referenced by Convert_Impl().
Convert()
template<typename InFromType, typename InToType> template<typename SrcBufferType UE_REQUIRES> FORCEINLINE void TUTF16ToUTF32_Convert< InFromType, InToType >::Convert (ToType * Dest, const int32 DestLen, const SrcBufferType * Source, const int32 SourceLen) inline static
Converts the UTF-16 string to UTF-32.
Parameters
Dest The destination buffer of the converted string.
DestLen The length of the destination buffer.
Source The source string to convert.
SourceLen The length of the source string.
Definition at line 567 of file StringConv.h.
References Convert_Impl(), FORCEINLINE, and Source.
Convert_Impl()
template<typename InFromType, typename InToType> template<typename DestBufferType> void TUTF16ToUTF32_Convert< InFromType, InToType >::Convert_Impl (DestBufferType & ConvertedBuffer, int32 DestLen, const FromType * Source, const int32 SourceLen) inline static private
Read Source string, converting the data from UTF-16 into UTF-32, and placing these in the Destination.
Definition at line 649 of file StringConv.h.
References CodepointFromUtf16(), and Source.
Referenced by Convert(), and ConvertedLength().
ConvertedLength()
template<typename InFromType, typename InToType> template<typename SrcBufferType UE_REQUIRES> int32 TUTF16ToUTF32_Convert< InFromType, InToType >::ConvertedLength (const SrcBufferType * Source, const int32 SourceLen) inline static nodiscard
Determines the length of the converted string.
Parameters
Source string to read and determine amount of ToType chars to represent
SourceLen Length of source string; we will not read past this amount, even if the characters tell us to
Returns
The length of the string in UTF-32 characters.
Definition at line 583 of file StringConv.h.
References Convert_Impl(), UE::Core::Private::FCountingOutputIterator::GetCount(), MAX_int32, and Source.
The documentation for this class was generated from the following file:
StringConv.h