Unreal Engine 5.6 C++ API: Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder Class Reference
Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder Class Reference
Interface builder for FOutputVertexInterface declarations.
#include "MetasoundVertex.h"
Public Member Functions
METASOUNDGRAPHCORE_API FOutputVertexInterfaceDeclarationBuilder (TArray< FOutputDataVertex > &OutVertices, TArray< FSubInterfaceLayout > &OutInstances)
template<typename... ArgTypes>
void Build (ArgTypes &&... InArgs)
Public Member Functions inherited from Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder
METASOUNDGRAPHCORE_API FSubInterfaceDeclarationBuilder (TArray< FSubInterfaceLayout > &OutSubInterfaceLayouts)
virtual METASOUNDGRAPHCORE_API ~FSubInterfaceDeclarationBuilder ()
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Add (FBeginSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FEndSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS void ReserveSubInterfaces (int32 Num)
Private Member Functions
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Add (FBeginSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FEndSubInterface &&InSubInterface)
METASOUNDGRAPHCORE_API void Add (FOutputDataVertex &&InVertex)
Private Attributes
TArray< FOutputDataVertex > & Vertices
Additional Inherited Members
Protected Member Functions inherited from Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder
METASOUNDGRAPHCORE_API void OnVertexAdded (const FVertexName &InVertexName)
Detailed Description
Interface builder for FOutputVertexInterface declarations.
Definition at line 578 of file MetasoundVertex.h.
Constructor & Destructor Documentation
FOutputVertexInterfaceDeclarationBuilder()
METASOUNDGRAPHCORE_API Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder::FOutputVertexInterfaceDeclarationBuilder (TArray< FOutputDataVertex > & OutVertices, TArray< FSubInterfaceLayout > & OutInstances)
References UE_API.
Member Function Documentation
Add() [1/3]
METASOUNDGRAPHCORE_API PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS void Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::Add (FBeginSubInterface && InSubInterface) private
Add() [2/3]
METASOUNDGRAPHCORE_API void Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::Add (FEndSubInterface && InSubInterface) private
Add() [3/3]
METASOUNDGRAPHCORE_API void Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder::Add (FOutputDataVertex && InVertex) private
References UE_API.
Build()
template<typename... ArgTypes> void Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder::Build (ArgTypes &&... InArgs) inline
Definition at line 584 of file MetasoundVertex.h.
References Add, Forward(), Metasound::VertexPrivate::TNumOfTypeInPack< T >::Get(), PRAGMA_DISABLE_EXPERIMENTAL_WARNINGS, PRAGMA_ENABLE_EXPERIMENTAL_WARNINGS, Metasound::VertexPrivate::FSubInterfaceDeclarationBuilder::ReserveSubInterfaces(), and Vertices.
Referenced by Metasound::FOutputVertexInterface::FOutputVertexInterface().
Field Documentation
Vertices
TArray<FOutputDataVertex>& Metasound::VertexPrivate::FOutputVertexInterfaceDeclarationBuilder::Vertices private
Definition at line 612 of file MetasoundVertex.h.
Referenced by Build().
The documentation for this class was generated from the following file:
MetasoundVertex.h