Unreal Engine 5.6 C++ API: TListTypeTraits< TWeakObjectPtr< T > > Struct Template Reference
TListTypeTraits< TWeakObjectPtr< T > > Struct Template Reference
Pointer-related functionality (e.g.
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TWeakObjectPtr<T>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TWeakObjectPtr<T>, FSparseItemInfo, false>
typedef TWeakObjectPtr< T > NullableType
using SetKeyFuncs = DefaultKeyFuncs< TWeakObjectPtr<T> >
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< TWeakObjectPtr< T > > &, TSet< TWeakObjectPtr< T > > &, TMap< const U *, TWeakObjectPtr< T > > &)
static FString DebugDump (TWeakObjectPtr< T > InPtr)
static bool IsPtrValid (const TWeakObjectPtr< T > &InPtr)
static TWeakObjectPtr< T > MakeNullPtr ()
static TWeakObjectPtr< T > NullableItemTypeConvertToItemType (const TWeakObjectPtr< T > &InPtr)
static void ResetPtr (TWeakObjectPtr< T > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TWeakObjectPtr< T > >
Pointer-related functionality (e.g.
setting to nullptr, testing for nullptr) specialized for SharedPointers.
Definition at line 406 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TWeakObjectPtr< T > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TWeakObjectPtr<T>, TSharedRef<ITableRow>, false>
Definition at line 411 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TWeakObjectPtr< T > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TWeakObjectPtr<T>, FSparseItemInfo, false>
Definition at line 412 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TWeakObjectPtr<T> TListTypeTraits< TWeakObjectPtr< T > >::NullableType
Definition at line 409 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TWeakObjectPtr< T > >::SetKeyFuncs = DefaultKeyFuncs< TWeakObjectPtr<T> >
Definition at line 413 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TWeakObjectPtr< T > >::AddReferencedObjects (FReferenceCollector & , TArray< TWeakObjectPtr< T > > & , TSet< TWeakObjectPtr< T > > & , TMap< const U *, TWeakObjectPtr< T > > &) inline static
Definition at line 416 of file TableViewTypeTraits.h.
DebugDump()
template<typename T> FString TListTypeTraits< TWeakObjectPtr< T > >::DebugDump (TWeakObjectPtr< T > InPtr) inline static
Definition at line 443 of file TableViewTypeTraits.h.
References TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TWeakObjectPtr< T > >::IsPtrValid (const TWeakObjectPtr< T > & InPtr) inline static
Definition at line 423 of file TableViewTypeTraits.h.
References TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid().
MakeNullPtr()
template<typename T> TWeakObjectPtr< T > TListTypeTraits< TWeakObjectPtr< T > >::MakeNullPtr () inline static
Definition at line 433 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TWeakObjectPtr< T > TListTypeTraits< TWeakObjectPtr< T > >::NullableItemTypeConvertToItemType (const TWeakObjectPtr< T > & InPtr) inline static
Definition at line 438 of file TableViewTypeTraits.h.
ResetPtr()
template<typename T> void TListTypeTraits< TWeakObjectPtr< T > >::ResetPtr (TWeakObjectPtr< T > & InPtr) inline static
Definition at line 428 of file TableViewTypeTraits.h.
References TWeakObjectPtr< T, TWeakObjectPtrBase >::Reset().
The documentation for this struct was generated from the following file:
TableViewTypeTraits.h