Unreal Engine 5.6 C++ API: Internal Namespace Reference
Internal Namespace Reference
Data Structures
struct FAttributesRefAdapter
struct FAttributesRefAdapterConst
class TVertexBoneWeightsBase
Functions
static FORCEINLINE uint16 ByteSwapGeneric16 (uint16 Value)
static FORCEINLINE uint32 ByteSwapGeneric32 (uint32 Value)
static FORCEINLINE uint64 ByteSwapGeneric64 (uint64 Value)
Function Documentation
ByteSwapGeneric16()
FORCEINLINE uint16 Internal::ByteSwapGeneric16 (uint16 Value) static
Definition at line 15 of file ByteSwap.h.
References BYTESWAP_ORDER16_unsigned, FORCEINLINE, and Value.
Referenced by BYTESWAP_ORDER16().
ByteSwapGeneric32()
FORCEINLINE uint32 Internal::ByteSwapGeneric32 (uint32 Value) static
Definition at line 20 of file ByteSwap.h.
References BYTESWAP_ORDER32_unsigned, FORCEINLINE, and Value.
Referenced by BYTESWAP_ORDER32().
ByteSwapGeneric64()
FORCEINLINE uint64 Internal::ByteSwapGeneric64 (uint64 Value) static
Definition at line 25 of file ByteSwap.h.
References FORCEINLINE, and Value.
Referenced by BYTESWAP_ORDER64().