Unreal Engine 5.6 C++ API: FEncryption Namespace Reference
FEncryption Namespace Reference
Math utils for encryption.
Functions
template<typename IntType>
IntType CalculateGCD (IntType ValueA, IntType ValueB)
Greatest common divisor of ValueA and ValueB.
template<typename IntType>
IntType CalculateMultiplicativeInverseOfExponent (IntType Exponent, IntType Totient)
Multiplicative inverse of exponent using extended GCD algorithm.
template<typename IntType>
void DecryptBytes (uint8 *DecryptedData, const IntType *Data, const int64 DataLength, const FEncryptionKey &DecryptionKey)
Decrypts a stream of bytes.
void DecryptSignature (const FEncryptedSignature &InEncryptedSignature, FDecryptedSignature &OutUnencryptedSignature, const FEncryptionKey &EncryptionKey)
template<typename IntType>
void EncryptBytes (IntType *EncryptedData, const uint8 *Data, const int64 DataLength, const FEncryptionKey &EncryptionKey)
Encrypts a stream of bytes.
void EncryptSignature (const FDecryptedSignature &InUnencryptedSignature, FEncryptedSignature &OutEncryptedSignature, const FEncryptionKey &EncryptionKey)
template<typename IntType>
void GenerateKeyPair (const IntType &P, const IntType &Q, FEncryptionKey &PublicKey, FEncryptionKey &PrivateKey)
Generate Key Pair for encryption and decryption.
template<typename IntType>
IntType ModularPow (IntType Base, IntType Exponent, IntType Modulus)
Raise Base to power of Exponent in mod Modulus.
Detailed Description
Math utils for encryption.
Function Documentation
CalculateGCD()
template<typename IntType> IntType FEncryption::CalculateGCD (IntType ValueA, IntType ValueB)
Greatest common divisor of ValueA and ValueB.
Definition at line 1053 of file BigInt.h.
References Swap.
Referenced by GenerateKeyPair().
CalculateMultiplicativeInverseOfExponent()
template<typename IntType> IntType FEncryption::CalculateMultiplicativeInverseOfExponent (IntType Exponent, IntType Totient)
Multiplicative inverse of exponent using extended GCD algorithm.
Extended gcd: ax + by = gcd(a, b), where a = exponent, b = fi(n), gcd(a, b) = gcd(e, fi(n)) = 1, fi(n) is the Euler's totient function of n We only care to find d = x, which is our multiplicatve inverse of e (a).
Definition at line 1106 of file BigInt.h.
Referenced by GenerateKeyPair().
DecryptBytes()
template<typename IntType> void FEncryption::DecryptBytes (uint8 * DecryptedData, const IntType * Data, const int64 DataLength, const FEncryptionKey & DecryptionKey)
Decrypts a stream of bytes.
Definition at line 1203 of file BigInt.h.
References TEncryptionKey< IntType >::Exponent, ModularPow(), and TEncryptionKey< IntType >::Modulus.
DecryptSignature()
void FEncryption::DecryptSignature (const FEncryptedSignature & InEncryptedSignature, FDecryptedSignature & OutUnencryptedSignature, const FEncryptionKey & EncryptionKey) inline
Definition at line 1302 of file BigInt.h.
References FSignatureBase< InDataType >::Data, TEncryptionKey< IntType >::Exponent, ModularPow(), and TEncryptionKey< IntType >::Modulus.
EncryptBytes()
template<typename IntType> void FEncryption::EncryptBytes (IntType * EncryptedData, const uint8 * Data, const int64 DataLength, const FEncryptionKey & EncryptionKey)
Encrypts a stream of bytes.
Definition at line 1191 of file BigInt.h.
References TEncryptionKey< IntType >::Exponent, ModularPow(), and TEncryptionKey< IntType >::Modulus.
EncryptSignature()
void FEncryption::EncryptSignature (const FDecryptedSignature & InUnencryptedSignature, FEncryptedSignature & OutEncryptedSignature, const FEncryptionKey & EncryptionKey) inline
Definition at line 1297 of file BigInt.h.
References FSignatureBase< InDataType >::Data, TEncryptionKey< IntType >::Exponent, ModularPow(), and TEncryptionKey< IntType >::Modulus.
GenerateKeyPair()
template<typename IntType> void FEncryption::GenerateKeyPair (const IntType & P, const IntType & Q, FEncryptionKey & PublicKey, FEncryptionKey & PrivateKey)
Generate Key Pair for encryption and decryption.
Definition at line 1146 of file BigInt.h.
References CalculateGCD(), CalculateMultiplicativeInverseOfExponent(), TEncryptionKey< IntType >::Exponent, and TEncryptionKey< IntType >::Modulus.
ModularPow()
template<typename IntType> IntType FEncryption::ModularPow (IntType Base, IntType Exponent, IntType Modulus)
Raise Base to power of Exponent in mod Modulus.
Definition at line 1171 of file BigInt.h.
References One.
Referenced by DecryptBytes(), DecryptSignature(), EncryptBytes(), and EncryptSignature().