Unreal Engine 5.6 C++ API: IDisplayClusterConfigurator Class Reference
IDisplayClusterConfigurator Class Reference abstract
Configurator editor module.
#include "IDisplayClusterConfigurator.h"
Public Member Functions
virtual ~IDisplayClusterConfigurator ()=default
virtual DISPLAYCLUSTERCONFIGURATOR_API const FDisplayClusterConfiguratorCommands & GetCommands () const =0
virtual DISPLAYCLUSTERCONFIGURATOR_API TSharedPtr< class FExtensibilityManager > GetMenuExtensibilityManager () const =0
virtual DISPLAYCLUSTERCONFIGURATOR_API TSharedPtr< class FExtensibilityManager > GetToolBarExtensibilityManager () const =0
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterConfigurator & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterConfigurator")
Detailed Description
Configurator editor module.
Definition at line 17 of file IDisplayClusterConfigurator.h.
Constructor & Destructor Documentation
~IDisplayClusterConfigurator()
virtual IDisplayClusterConfigurator::~IDisplayClusterConfigurator () virtual default
Member Function Documentation
Get()
IDisplayClusterConfigurator & IDisplayClusterConfigurator::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 33 of file IDisplayClusterConfigurator.h.
References FModuleManager::GetModuleChecked(), and ModuleName.
GetCommands()
virtual DISPLAYCLUSTERCONFIGURATOR_API const FDisplayClusterConfiguratorCommands & IDisplayClusterConfigurator::GetCommands () const pure virtual
GetMenuExtensibilityManager()
virtual DISPLAYCLUSTERCONFIGURATOR_API TSharedPtr< class FExtensibilityManager > IDisplayClusterConfigurator::GetMenuExtensibilityManager () const pure virtual
GetToolBarExtensibilityManager()
virtual DISPLAYCLUSTERCONFIGURATOR_API TSharedPtr< class FExtensibilityManager > IDisplayClusterConfigurator::GetToolBarExtensibilityManager () const pure virtual
IsAvailable()
bool IDisplayClusterConfigurator::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 43 of file IDisplayClusterConfigurator.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
Field Documentation
ModuleName
const TCHAR* IDisplayClusterConfigurator::ModuleName = TEXT("DisplayClusterConfigurator") static constexpr
Definition at line 21 of file IDisplayClusterConfigurator.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
IDisplayClusterConfigurator.h