Unreal Engine 5.6 C++ API: FFileRegion Struct Reference
FFileRegion Struct Reference
#include "FileRegions.h"
Public Member Functions
FFileRegion ()
FFileRegion (uint64 InOffset, uint64 InLength, EFileRegionType InType)
Static Public Member Functions
static void AccumulateFileRegions (TArray< FFileRegion > &InOutRegions, int64 EntryOffset, int64 PayloadOffset, int64 EndOffset, TArrayView< const FFileRegion > InnerFileRegions)
static bool LoadFromCompactBinary (FCbFieldView Obj, FFileRegion &OutRegion)
static EFileRegionType SelectType (EPixelFormat Format)
static void SerializeFileRegions (class FArchive &Ar, TArray< FFileRegion > &Regions)
Data Fields
uint64 Length
uint64 Offset
EFileRegionType Type
Static Public Attributes
static const TCHAR * RegionsFileExtension
Friends
FCbWriter & operator<< (FCbWriter &Writer, const FFileRegion &Region)
Detailed Description
Definition at line 30 of file FileRegions.h.
Constructor & Destructor Documentation
FFileRegion() [1/2]
FFileRegion::FFileRegion () inline
Definition at line 38 of file FileRegions.h.
References Length, None, Offset, and Type.
Referenced by LoadFromCompactBinary(), and operator<<.
FFileRegion() [2/2]
FFileRegion::FFileRegion (uint64 InOffset, uint64 InLength, EFileRegionType InType) inline
Definition at line 44 of file FileRegions.h.
References Length, Offset, and Type.
Member Function Documentation
AccumulateFileRegions()
void FFileRegion::AccumulateFileRegions (TArray< FFileRegion > & InOutRegions, int64 EntryOffset, int64 PayloadOffset, int64 EndOffset, TArrayView< const FFileRegion > InnerFileRegions) static
LoadFromCompactBinary()
bool FFileRegion::LoadFromCompactBinary (FCbFieldView Obj, FFileRegion & OutRegion) static
References FFileRegion().
SelectType()
EFileRegionType FFileRegion::SelectType (EPixelFormat Format) inline static
Definition at line 56 of file FileRegions.h.
References BC1, BC2, BC3, BC4, BC5, Format, None, PF_BC4, PF_BC5, PF_DXT1, PF_DXT3, and PF_DXT5.
SerializeFileRegions()
void FFileRegion::SerializeFileRegions (class FArchive & Ar, TArray< FFileRegion > & Regions) static
References Ar.
Friends And Related Symbol Documentation
operator<<
FCbWriter & operator<< (FCbWriter & Writer, const FFileRegion & Region) friend
References FFileRegion().
Field Documentation
Length
uint64 FFileRegion::Length
Definition at line 35 of file FileRegions.h.
Referenced by FFileRegion(), and FFileRegion().
Offset
uint64 FFileRegion::Offset
Definition at line 34 of file FileRegions.h.
Referenced by FFileRegion(), and FFileRegion().
RegionsFileExtension
const TCHAR* FFileRegion::RegionsFileExtension static
Definition at line 32 of file FileRegions.h.
Type
EFileRegionType FFileRegion::Type
Definition at line 36 of file FileRegions.h.
Referenced by FFileRegion(), and FFileRegion().
The documentation for this struct was generated from the following file:
FileRegions.h