Unreal Engine 5.6 C++ API: FMacPlatformApplicationMisc Struct Reference
FMacPlatformApplicationMisc Struct Reference
#include "MacPlatformApplicationMisc.h"
Static Public Member Functions
static void ActivateApplication ()
static void ClipboardCopy (const TCHAR *Str)
static void ClipboardPaste (class FString &Dest)
static bool ControlScreensaver (EScreenSaverAction Action)
static class GenericApplication * CreateApplication ()
static class FOutputDeviceConsole * CreateConsoleOutputDevice ()
static float GetDPIScaleFactorAtPoint (float X, float Y)
static class FOutputDeviceError * GetErrorOutputDevice ()
static class FFeedbackContext * GetFeedbackContext ()
static struct FLinearColor GetScreenPixelColor (const FVector2D &InScreenPos, float InGamma=1.0f)
static CGDisplayModeRef GetSupportedDisplayMode (CGDirectDisplayID DisplayID, uint32 Width, uint32 Height)
static bool IsHighDPIModeEnabled ()
static bool IsScreensaverEnabled ()
static bool IsThisApplicationForeground ()
static void LanguageChanged ()
static void LoadPreInitModules ()
static void PostInit ()
static void PreInit ()
static void PumpMessages (bool bFromMainLoop)
static void RequestMinimize ()
static void TearDown ()
static void UpdateApplicationMenu ()
static void UpdateCocoaWindows ()
static void UpdateWindowMenu ()
Static Public Member Functions inherited from FGenericPlatformApplicationMisc
static bool AnchorWindowWindowPositionTopLeft ()
static APPLICATIONCORE_API void ClipboardCopy (const TCHAR *Str)
Copies text to the operating system clipboard.
static APPLICATIONCORE_API void ClipboardPaste (class FString &Dest)
Pastes in text from the operating system clipboard.
static APPLICATIONCORE_API EScreenPhysicalAccuracy ComputePhysicalScreenDensity (int32 &OutScreenDensity)
Gets the physical size of the screen if possible.
static bool ControlScreensaver (EScreenSaverAction Action)
Disables screensaver (if platform supports such an API)
template<typename T, typename T2 UE_REQUIRES>
static EScreenPhysicalAccuracy ConvertInchesToPixels (T Inches, T2 &OutPixels)
If we know or can approximate the pixel density of the screen we will convert the incoming inches to pixels on the device.
template<typename T, typename T2 UE_REQUIRES>
static EScreenPhysicalAccuracy ConvertPixelsToInches (T Pixels, T2 &OutInches)
If we know or can approximate the pixel density of the screen we will convert the incoming pixels to inches on the device.
static APPLICATIONCORE_API class GenericApplication * CreateApplication ()
Creates an application instance.
static APPLICATIONCORE_API FOutputDeviceConsole * CreateConsoleOutputDevice ()
Creates a console output device for this platform.
static APPLICATIONCORE_API IPlatformInputDeviceMapper * CreatePlatformInputDeviceManager ()
Gets a pointer to the default platform input device manager.
static void EnableMotionData (bool bEnable)
static float GetDPIScaleFactorAtPoint (float X, float Y)
Returns monitor's DPI scale factor at given screen coordinates (expressed in pixels)
static APPLICATIONCORE_API FOutputDeviceError * GetErrorOutputDevice ()
Gets a pointer to the platform error output device singleton.
static APPLICATIONCORE_API FFeedbackContext * GetFeedbackContext ()
Gets a pointer to the default platform feedback context implementation.
static class UTexture2D * GetGamepadButtonGlyph (const FGamepadKeyNames::Type &ButtonKey, uint32 ControllerIndex)
static FString GetGamepadControllerName (int32 ControllerId)
static APPLICATIONCORE_API EScreenPhysicalAccuracy GetPhysicalScreenDensity (int32 &OutScreenDensity)
Gets the physical size of the screen if possible.
static APPLICATIONCORE_API struct FLinearColor GetScreenPixelColor (const FVector2D &InScreenPos, float InGamma=1.0f)
Sample the displayed pixel color from anywhere on the screen using the OS.
static bool GetWindowTitleMatchingText (const TCHAR *TitleStartsWith, FString &OutTitle)
Searches for a window that matches the window name or the title starts with a particular text.
static APPLICATIONCORE_API void Init ()
static bool IsControllerAssignedToGamepad (int32 ControllerId)
static APPLICATIONCORE_API bool IsHighDPIAwarenessEnabled ()
static bool IsMotionDataEnabled ()
static bool IsScreensaverEnabled ()
Returns state of screensaver (if platform supports it)
static APPLICATIONCORE_API bool IsThisApplicationForeground ()
Returns true if the specified application has a visible window, and that window is active/has focus/is selected.
static void LoadPreInitModules ()
Load the preinit modules required by this platform, typically they are the renderer modules.
static void LoadStartupModules ()
Load the platform-specific startup modules.
static APPLICATIONCORE_API void PostInit ()
static APPLICATIONCORE_API void PreInit ()
static void PreventScreenSaver ()
Prevents screen-saver from kicking in by moving the mouse by 0 pixels.
static FORCEINLINE void PumpMessages (bool bFromMainLoop)
Pumps Windows messages.
static APPLICATIONCORE_API void RequestMinimize ()
Request application to minimize (goto background).
static APPLICATIONCORE_API bool RequiresVirtualKeyboard ()
Returns whether the platform wants to use a touch screen for a virtual keyboard.
static void ResetGamepadAssignments ()
static void ResetGamepadAssignmentToController (int32 ControllerId)
static void SetGamepadsAllowed (bool bAllowed)
static void SetGamepadsBlockDeviceFeedback (bool bAllowed)
static void SetHighDPIMode ()
Allows the OS to enable high DPI mode.
static bool ShowInputDeviceSelector (FPlatformUserId InitiatingUserId, FShowInputDeviceSelectorComplete OnShowInputDeviceSelectorComplete)
Asyncronously display the platform-specific input device selection UI, if supported.
static bool ShowPlatformUserSelector (FInputDeviceId InitiatingInputDeviceId, EPlatformUserSelectorFlags Flags, FPlatformUserSelectionComplete OnUserSelectionComplete)
Asyncronously display the platform-specific user selection UI, if supported.
static APPLICATIONCORE_API void TearDown ()
Static Public Attributes
static bool bChachedMacMenuStateNeedsUpdate
static bool bIsHighResolutionCapable
static bool bLanguageChanged
static bool bMacApplicationModalMode
static id< NSObject > CommandletActivity
static MacApplicationExternalCb LanguageChangedCb
static MacApplicationExternalCb PostInitMacMenuStartupCb
static MacApplicationExternalCbOneBool UpdateApplicationMenuCb
static MacApplicationExternalCb UpdateCachedMacMenuStateCb
static MacApplicationExternalCbOneBool UpdateWindowMenuCb
Static Private Attributes
static bool bDisplaySleepEnabled
Additional Inherited Members
Public Types inherited from FGenericPlatformApplicationMisc
enum EScreenSaverAction { Disable , Enable }
Static Protected Attributes inherited from FGenericPlatformApplicationMisc
static APPLICATIONCORE_API EScreenPhysicalAccuracy CachedPhysicalScreenAccuracy
static APPLICATIONCORE_API bool CachedPhysicalScreenData
static APPLICATIONCORE_API int32 CachedPhysicalScreenDensity
static APPLICATIONCORE_API FAutoConsoleVariableRef CVarAllowVirtualKeyboard
static APPLICATIONCORE_API FAutoConsoleVariableRef CVarEnableHighDPIAwareness
Detailed Description
Definition at line 10 of file MacPlatformApplicationMisc.h.
Member Function Documentation
ActivateApplication()
void FMacPlatformApplicationMisc::ActivateApplication () static
ClipboardCopy()
void FMacPlatformApplicationMisc::ClipboardCopy (const TCHAR * Str) static
ClipboardPaste()
void FMacPlatformApplicationMisc::ClipboardPaste (class FString & Dest) static
ControlScreensaver()
bool FMacPlatformApplicationMisc::ControlScreensaver (EScreenSaverAction Action) static
CreateApplication()
class GenericApplication * FMacPlatformApplicationMisc::CreateApplication () static
CreateConsoleOutputDevice()
class FOutputDeviceConsole * FMacPlatformApplicationMisc::CreateConsoleOutputDevice () static
GetDPIScaleFactorAtPoint()
float FMacPlatformApplicationMisc::GetDPIScaleFactorAtPoint (float X, float Y) static
References X, and Y.
GetErrorOutputDevice()
class FOutputDeviceError * FMacPlatformApplicationMisc::GetErrorOutputDevice () static
GetFeedbackContext()
class FFeedbackContext * FMacPlatformApplicationMisc::GetFeedbackContext () static
GetScreenPixelColor()
struct FLinearColor FMacPlatformApplicationMisc::GetScreenPixelColor (const FVector2D & InScreenPos, float InGamma = 1.0f) static
References GetScreenPixelColor().
Referenced by GetScreenPixelColor().
GetSupportedDisplayMode()
CGDisplayModeRef FMacPlatformApplicationMisc::GetSupportedDisplayMode (CGDirectDisplayID DisplayID, uint32 Width, uint32 Height) static
References Width.
IsHighDPIModeEnabled()
bool FMacPlatformApplicationMisc::IsHighDPIModeEnabled () inline static
Definition at line 31 of file MacPlatformApplicationMisc.h.
References bIsHighResolutionCapable, and FGenericPlatformApplicationMisc::IsHighDPIAwarenessEnabled().
IsScreensaverEnabled()
bool FMacPlatformApplicationMisc::IsScreensaverEnabled () static
IsThisApplicationForeground()
bool FMacPlatformApplicationMisc::IsThisApplicationForeground () static
LanguageChanged()
void FMacPlatformApplicationMisc::LanguageChanged () static
LoadPreInitModules()
void FMacPlatformApplicationMisc::LoadPreInitModules () static
PostInit()
void FMacPlatformApplicationMisc::PostInit () static
PreInit()
void FMacPlatformApplicationMisc::PreInit () static
PumpMessages()
void FMacPlatformApplicationMisc::PumpMessages (bool bFromMainLoop) static
RequestMinimize()
void FMacPlatformApplicationMisc::RequestMinimize () static
TearDown()
void FMacPlatformApplicationMisc::TearDown () static
UpdateApplicationMenu()
void FMacPlatformApplicationMisc::UpdateApplicationMenu () static
UpdateCocoaWindows()
void FMacPlatformApplicationMisc::UpdateCocoaWindows () static
UpdateWindowMenu()
void FMacPlatformApplicationMisc::UpdateWindowMenu () static
Field Documentation
bChachedMacMenuStateNeedsUpdate
bool FMacPlatformApplicationMisc::bChachedMacMenuStateNeedsUpdate static
Definition at line 45 of file MacPlatformApplicationMisc.h.
bDisplaySleepEnabled
bool FMacPlatformApplicationMisc::bDisplaySleepEnabled static private
Definition at line 56 of file MacPlatformApplicationMisc.h.
bIsHighResolutionCapable
bool FMacPlatformApplicationMisc::bIsHighResolutionCapable static
Definition at line 51 of file MacPlatformApplicationMisc.h.
Referenced by IsHighDPIModeEnabled().
bLanguageChanged
bool FMacPlatformApplicationMisc::bLanguageChanged static
Definition at line 47 of file MacPlatformApplicationMisc.h.
bMacApplicationModalMode
bool FMacPlatformApplicationMisc::bMacApplicationModalMode static
Definition at line 49 of file MacPlatformApplicationMisc.h.
CommandletActivity
id<NSObject> FMacPlatformApplicationMisc::CommandletActivity static
Definition at line 53 of file MacPlatformApplicationMisc.h.
LanguageChangedCb
MacApplicationExternalCb FMacPlatformApplicationMisc::LanguageChangedCb static
Definition at line 43 of file MacPlatformApplicationMisc.h.
PostInitMacMenuStartupCb
MacApplicationExternalCb FMacPlatformApplicationMisc::PostInitMacMenuStartupCb static
Definition at line 40 of file MacPlatformApplicationMisc.h.
UpdateApplicationMenuCb
MacApplicationExternalCbOneBool FMacPlatformApplicationMisc::UpdateApplicationMenuCb static
Definition at line 41 of file MacPlatformApplicationMisc.h.
UpdateCachedMacMenuStateCb
MacApplicationExternalCb FMacPlatformApplicationMisc::UpdateCachedMacMenuStateCb static
Definition at line 39 of file MacPlatformApplicationMisc.h.
UpdateWindowMenuCb
MacApplicationExternalCbOneBool FMacPlatformApplicationMisc::UpdateWindowMenuCb static
Definition at line 42 of file MacPlatformApplicationMisc.h.
The documentation for this struct was generated from the following file:
MacPlatformApplicationMisc.h