Unreal Engine 5.6 C++ API: ImmediatePhysics_Chaos::FSimulation Struct Reference
ImmediatePhysics_Chaos::FSimulation Struct Reference
Owns all the data associated with the simulation.
#include "ImmediatePhysicsSimulation_Chaos.h"
Data Structures
struct FCollisionData
struct FIgnorePair
An array of actors to ignore.
Public Member Functions
FSimulation ()
~FSimulation ()
void AddToCollidingPairs (FActorHandle *ActorHandle)
Set up potential collisions between the actor and all other dynamic actors.
FActorHandle * CreateActor (FActorSetup &&ActorSetup)
FJointHandle * CreateJoint (const FJointSetup &JointSetup)
Create a physical joint and add it to the simulation.
void DebugDraw ()
Explicit debug draw path if the use case needs it to happen at a point outside of the simulation.
void DestroyActor (FActorHandle *ActorHandle)
void DestroyActorCollisions (FActorHandle *ActorHandle)
void DestroyJoint (FJointHandle *JointHandle)
FActorHandle * GetActorHandle (int32 ActorHandleIndex)
const FActorHandle * GetActorHandle (int32 ActorHandleIndex) const
const Chaos::FCollisionDetectorSettings & GetCollisionDetectorSettings () const
const Chaos::FSimulationSpaceSettings & GetSimulationSpaceSettings () const
void InitSimulationSpace (const FTransform &Transform)
int32 NumActors () const
void SetCollisionDetectorSettings (const Chaos::FCollisionDetectorSettings &Settings)
void SetEnabled (FActorHandle *ActorHandle, bool bEnable)
void SetHasCollision (FActorHandle *ActorHandle, bool bHasCollision)
void SetIgnoreCollisionActors (const TArray< FActorHandle * > &InIgnoreCollisionActors)
Set bodies that require no collision.
void SetIgnoreCollisionPairTable (const TArray< FIgnorePair > &InIgnoreCollisionPairTable)
Set pair of bodies to ignore collision for.
void SetIsKinematic (FActorHandle *ActorHandle, bool bKinematic)
void SetMaxNumRollingAverageStepTimes (const int32 MaxNumRollingAverageStepTimes)
void SetNumActiveBodies (int32 NumActiveBodies, TArray< int32 > ActiveBodyIndices)
Sets the number of active bodies.
void SetRewindVelocities (bool bRewindVelocities)
Sets whether velocities should be rewound when simulating - this may happen when the requested step size is smaller than the fixed simulation step.
void SetSimulationSpaceSettings (const bool bEnabled, const FReal DampingAlpha, const FVector &ExternalLinearEtherDrag)
void SetSimulationSpaceSettings (const Chaos::FSimulationSpaceSettings &SimulationSpaceSettings)
void SetSolverSettings (const FReal FixedDt, const FReal CullDistance, const FReal MaxDepenetrationVelocity, const int32 UseLinearJointSolver, const int32 PositionIts, const int32 VelocityIts, const int32 ProjectionIts, const int32 bUseManifolds)
Set settings.
void Simulate (FReal DeltaTime, FReal MaxStepTime, int32 MaxSubSteps, const FVector &InGravity, Chaos::FPBDJointSolverSettings *JointSolverSettings=nullptr, Chaos::FPBDCollisionSolverSettings *CollisionSolverSettings=nullptr, Chaos::FCollisionDetectorSettings *CollisionDetectorSettings=nullptr)
Advance the simulation by DeltaTime.
void Simulate_AssumesLocked (FReal DeltaTime, FReal MaxStepTime, int32 MaxSubSteps, const FVector &InGravity, Chaos::FPBDJointSolverSettings *JointSolverSettings=nullptr, Chaos::FPBDCollisionSolverSettings *CollisionSolverSettings=nullptr, Chaos::FCollisionDetectorSettings *CollisionDetectorSettings=nullptr)
UE_DEPRECATED (5.6, "Use CreateActor with FActorSetup") 1 FActorHandle *CreateActor(EActorType ActorType
UE_DEPRECATED (5.6, "Use CreateActor with FActorSetup") 1 FActorHandle *CreateDynamicActor(FBodyInstance *BodyInstance
UE_DEPRECATED (5.6, "Use CreateActor with FActorSetup") 1 FActorHandle *CreateKinematicActor(FBodyInstance *BodyInstance
UE_DEPRECATED (5.6, "Use CreateActor with FActorSetup") 1 FActorHandle *CreateStaticActor(FBodyInstance *BodyInstance)
UE_DEPRECATED (5.6, "Use CreateActor with FJointSetup") 1 FJointHandle *CreateJoint(FConstraintInstance *ConstraintInstance
Create a physical joint and add it to the simulation.
void UpdateSimulationSpace (const FTransform &Transform, const FVector &LinearVel, const FVector &AngularVel, const FVector &LinearAcc, const FVector &AngularAcc)
void VisitCollisions (TFunction< void(const FCollisionData &)> Visitor, Chaos::ECollisionVisitorFlags VisitorFlags) const
Data Fields
FActorHandle * Body1
FActorHandle FActorHandle * Body2
FBodyInstance * BodyInstance
const FTransform & Transform
FBodyInstance const FTransform & Transform
Private Member Functions
void DebugDrawConstraints ()
void DebugDrawDynamicParticles ()
void DebugDrawKinematicParticles ()
void DebugDrawSimulationSpace ()
void DebugDrawStaticParticles ()
void EnableDisableJoints ()
void PackCollidingPairs ()
void RemoveFromCollidingPairs (FActorHandle *ActorHandle)
void UpdateActivePotentiallyCollidingPairs ()
void UpdateInertiaConditioning (const FVector &Gravity)
void UpdateStatCounters ()
FReal UpdateStepTime (const FReal DeltaTime, const FReal MaxStepTime)
Private Attributes
TUniquePtr< FImplementation > Implementation
Detailed Description
Owns all the data associated with the simulation.
Can be considered a single scene or world
Definition at line 25 of file ImmediatePhysicsSimulation_Chaos.h.
Constructor & Destructor Documentation
FSimulation()
ImmediatePhysics_Chaos::FSimulation::FSimulation ()
~FSimulation()
ImmediatePhysics_Chaos::FSimulation::~FSimulation ()
Member Function Documentation
AddToCollidingPairs()
void ImmediatePhysics_Chaos::FSimulation::AddToCollidingPairs (FActorHandle * ActorHandle)
Set up potential collisions between the actor and all other dynamic actors.
CreateActor()
FActorHandle * ImmediatePhysics_Chaos::FSimulation::CreateActor (FActorSetup && ActorSetup)
References CreateActor().
Referenced by CreateActor().
CreateJoint()
FJointHandle * ImmediatePhysics_Chaos::FSimulation::CreateJoint (const FJointSetup & JointSetup)
Create a physical joint and add it to the simulation.
References CreateJoint().
Referenced by CreateJoint().
DebugDraw()
void ImmediatePhysics_Chaos::FSimulation::DebugDraw ()
Explicit debug draw path if the use case needs it to happen at a point outside of the simulation.
DebugDrawConstraints()
void ImmediatePhysics_Chaos::FSimulation::DebugDrawConstraints () private
DebugDrawDynamicParticles()
void ImmediatePhysics_Chaos::FSimulation::DebugDrawDynamicParticles () private
DebugDrawKinematicParticles()
void ImmediatePhysics_Chaos::FSimulation::DebugDrawKinematicParticles () private
DebugDrawSimulationSpace()
void ImmediatePhysics_Chaos::FSimulation::DebugDrawSimulationSpace () private
DebugDrawStaticParticles()
void ImmediatePhysics_Chaos::FSimulation::DebugDrawStaticParticles () private
DestroyActor()
void ImmediatePhysics_Chaos::FSimulation::DestroyActor (FActorHandle * ActorHandle)
References DestroyActor().
Referenced by DestroyActor().
DestroyActorCollisions()
void ImmediatePhysics_Chaos::FSimulation::DestroyActorCollisions (FActorHandle * ActorHandle)
References DestroyActorCollisions().
Referenced by DestroyActorCollisions().
DestroyJoint()
void ImmediatePhysics_Chaos::FSimulation::DestroyJoint (FJointHandle * JointHandle)
References DestroyJoint().
Referenced by DestroyJoint().
EnableDisableJoints()
void ImmediatePhysics_Chaos::FSimulation::EnableDisableJoints () private
GetActorHandle() [1/2]
FActorHandle * ImmediatePhysics_Chaos::FSimulation::GetActorHandle (int32 ActorHandleIndex)
GetActorHandle() [2/2]
const FActorHandle * ImmediatePhysics_Chaos::FSimulation::GetActorHandle (int32 ActorHandleIndex) const
GetCollisionDetectorSettings()
const Chaos::FCollisionDetectorSettings & ImmediatePhysics_Chaos::FSimulation::GetCollisionDetectorSettings () const
GetSimulationSpaceSettings()
const Chaos::FSimulationSpaceSettings & ImmediatePhysics_Chaos::FSimulation::GetSimulationSpaceSettings () const
InitSimulationSpace()
void ImmediatePhysics_Chaos::FSimulation::InitSimulationSpace (const FTransform & Transform)
References Transform.
NumActors()
int32 ImmediatePhysics_Chaos::FSimulation::NumActors () const
PackCollidingPairs()
void ImmediatePhysics_Chaos::FSimulation::PackCollidingPairs () private
RemoveFromCollidingPairs()
void ImmediatePhysics_Chaos::FSimulation::RemoveFromCollidingPairs (FActorHandle * ActorHandle) private
SetCollisionDetectorSettings()
void ImmediatePhysics_Chaos::FSimulation::SetCollisionDetectorSettings (const Chaos::FCollisionDetectorSettings & Settings)
SetEnabled()
void ImmediatePhysics_Chaos::FSimulation::SetEnabled (FActorHandle * ActorHandle, bool bEnable)
References SetEnabled().
Referenced by SetEnabled().
SetHasCollision()
void ImmediatePhysics_Chaos::FSimulation::SetHasCollision (FActorHandle * ActorHandle, bool bHasCollision)
References SetHasCollision().
Referenced by SetHasCollision().
SetIgnoreCollisionActors()
void ImmediatePhysics_Chaos::FSimulation::SetIgnoreCollisionActors (const TArray< FActorHandle * > & InIgnoreCollisionActors)
Set bodies that require no collision.
SetIgnoreCollisionPairTable()
void ImmediatePhysics_Chaos::FSimulation::SetIgnoreCollisionPairTable (const TArray< FIgnorePair > & InIgnoreCollisionPairTable)
Set pair of bodies to ignore collision for.
SetIsKinematic()
void ImmediatePhysics_Chaos::FSimulation::SetIsKinematic (FActorHandle * ActorHandle, bool bKinematic)
References SetIsKinematic().
Referenced by SetIsKinematic().
SetMaxNumRollingAverageStepTimes()
void ImmediatePhysics_Chaos::FSimulation::SetMaxNumRollingAverageStepTimes (const int32 MaxNumRollingAverageStepTimes)
SetNumActiveBodies()
void ImmediatePhysics_Chaos::FSimulation::SetNumActiveBodies (int32 NumActiveBodies, TArray< int32 > ActiveBodyIndices)
Sets the number of active bodies.
This number is reset any time a new simulated body is created
References SetNumActiveBodies().
Referenced by SetNumActiveBodies().
SetRewindVelocities()
void ImmediatePhysics_Chaos::FSimulation::SetRewindVelocities (bool bRewindVelocities)
Sets whether velocities should be rewound when simulating - this may happen when the requested step size is smaller than the fixed simulation step.
SetSimulationSpaceSettings() [1/2]
void ImmediatePhysics_Chaos::FSimulation::SetSimulationSpaceSettings (const bool bEnabled, const FReal DampingAlpha, const FVector & ExternalLinearEtherDrag)
References FVector.
SetSimulationSpaceSettings() [2/2]
void ImmediatePhysics_Chaos::FSimulation::SetSimulationSpaceSettings (const Chaos::FSimulationSpaceSettings & SimulationSpaceSettings)
SetSolverSettings()
void ImmediatePhysics_Chaos::FSimulation::SetSolverSettings (const FReal FixedDt, const FReal CullDistance, const FReal MaxDepenetrationVelocity, const int32 UseLinearJointSolver, const int32 PositionIts, const int32 VelocityIts, const int32 ProjectionIts, const int32 bUseManifolds)
Set settings.
Invalid (negative) values will leave that value unchanged from defaults
Simulate()
void ImmediatePhysics_Chaos::FSimulation::Simulate (FReal DeltaTime, FReal MaxStepTime, int32 MaxSubSteps, const FVector & InGravity, Chaos::FPBDJointSolverSettings * JointSolverSettings = nullptr, Chaos::FPBDCollisionSolverSettings * CollisionSolverSettings = nullptr, Chaos::FCollisionDetectorSettings * CollisionDetectorSettings = nullptr)
Advance the simulation by DeltaTime.
If settings are passed in they will be used, otherwise they will be taken from CVars
References DeltaTime, and FVector.
Referenced by Simulate_AssumesLocked().
Simulate_AssumesLocked()
void ImmediatePhysics_Chaos::FSimulation::Simulate_AssumesLocked (FReal DeltaTime, FReal MaxStepTime, int32 MaxSubSteps, const FVector & InGravity, Chaos::FPBDJointSolverSettings * JointSolverSettings = nullptr, Chaos::FPBDCollisionSolverSettings * CollisionSolverSettings = nullptr, Chaos::FCollisionDetectorSettings * CollisionDetectorSettings = nullptr) inline
Definition at line 104 of file ImmediatePhysicsSimulation_Chaos.h.
References DeltaTime, FVector, and Simulate().
UE_DEPRECATED() [1/5]
ImmediatePhysics_Chaos::FSimulation::UE_DEPRECATED (5. 6, "Use CreateActor with FActorSetup")
References UE_DEPRECATED().
UE_DEPRECATED() [2/5]
ImmediatePhysics_Chaos::FSimulation::UE_DEPRECATED (5. 6, "Use CreateActor with FActorSetup")
References BodyInstance, Transform, and UE_DEPRECATED().
UE_DEPRECATED() [3/5]
ImmediatePhysics_Chaos::FSimulation::UE_DEPRECATED (5. 6, "Use CreateActor with FActorSetup")
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
ImmediatePhysics_Chaos::FSimulation::UE_DEPRECATED (5. 6, "Use CreateActor with FActorSetup")
References BodyInstance.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/5]
ImmediatePhysics_Chaos::FSimulation::UE_DEPRECATED (5. 6, "Use CreateActor with FJointSetup")
Create a physical joint and add it to the simulation.
References UE_DEPRECATED().
UpdateActivePotentiallyCollidingPairs()
void ImmediatePhysics_Chaos::FSimulation::UpdateActivePotentiallyCollidingPairs () private
UpdateInertiaConditioning()
void ImmediatePhysics_Chaos::FSimulation::UpdateInertiaConditioning (const FVector & Gravity) private
References FVector.
UpdateSimulationSpace()
void ImmediatePhysics_Chaos::FSimulation::UpdateSimulationSpace (const FTransform & Transform, const FVector & LinearVel, const FVector & AngularVel, const FVector & LinearAcc, const FVector & AngularAcc)
References FVector, and Transform.
UpdateStatCounters()
void ImmediatePhysics_Chaos::FSimulation::UpdateStatCounters () private
UpdateStepTime()
FReal ImmediatePhysics_Chaos::FSimulation::UpdateStepTime (const FReal DeltaTime, const FReal MaxStepTime) private
References DeltaTime.
VisitCollisions()
void ImmediatePhysics_Chaos::FSimulation::VisitCollisions (TFunction< void(const FCollisionData &)> Visitor, Chaos::ECollisionVisitorFlags VisitorFlags) const
Field Documentation
Body1
FActorHandle* ImmediatePhysics_Chaos::FSimulation::Body1
Definition at line 62 of file ImmediatePhysicsSimulation_Chaos.h.
Body2
FActorHandle FActorHandle* ImmediatePhysics_Chaos::FSimulation::Body2
Definition at line 62 of file ImmediatePhysicsSimulation_Chaos.h.
BodyInstance
FBodyInstance* ImmediatePhysics_Chaos::FSimulation::BodyInstance
Definition at line 46 of file ImmediatePhysicsSimulation_Chaos.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Implementation
TUniquePtr<FImplementation> ImmediatePhysics_Chaos::FSimulation::Implementation private
Definition at line 203 of file ImmediatePhysicsSimulation_Chaos.h.
Transform [1/2]
const FTransform & ImmediatePhysics_Chaos::FSimulation::Transform
Definition at line 40 of file ImmediatePhysicsSimulation_Chaos.h.
Referenced by InitSimulationSpace(), UE_DEPRECATED(), and UpdateSimulationSpace().
Transform [2/2]
FBodyInstance const FTransform& ImmediatePhysics_Chaos::FSimulation::Transform
Definition at line 46 of file ImmediatePhysicsSimulation_Chaos.h.
The documentation for this struct was generated from the following file:
ImmediatePhysicsSimulation_Chaos.h