Unreal Engine 5.6 C++ API: TScriptContainerIterator< ContainerType > Struct Template Reference
TScriptContainerIterator< ContainerType > Struct Template Reference
Templated iterator to go through script helper containers that may contain invalid entries that are not part of the valid number of elements (i.e.
#include "UnrealType.h"
Public Member Functions
TScriptContainerIterator (const ContainerType &InContainer)
TScriptContainerIterator (const ContainerType &InContainer, const int32 InLogicalIndex)
int32 GetInternalIndex () const
int32 GetLogicalIndex () const
operator bool () const
TScriptContainerIterator & operator++ ()
TScriptContainerIterator operator++ (int)
UE_DEPRECATED (5.4, "Use Iterator directly, GetInternalIndex or GetLogicalIndex instead.") int32 operator*() const
Private Member Functions
void Advance ()
Private Attributes
const ContainerType & Container
int32 InternalIndex = INDEX_NONE
int32 LogicalIndex = INDEX_NONE
Detailed Description
template<typename ContainerType>
struct TScriptContainerIterator< ContainerType >
Templated iterator to go through script helper containers that may contain invalid entries that are not part of the valid number of elements (i.e.
GetMaxIndex() != Num()). The iterator
will advance to the first valid entry on creation and when incremented
can be dereferenced to an internal index to be used with methods like Get<Item>Ptr or Get<Item>PtrWithoutCheck
can also be used directly with methods like Get<Item>PtrChecked
can return the associated logical index (number of valid visited entries) by calling GetLogicalIndex()
Definition at line 4262 of file UnrealType.h.
Constructor & Destructor Documentation
TScriptContainerIterator() [1/2]
template<typename ContainerType> TScriptContainerIterator< ContainerType >::TScriptContainerIterator (const ContainerType & InContainer) inline explicit
Definition at line 4264 of file UnrealType.h.
TScriptContainerIterator() [2/2]
template<typename ContainerType> TScriptContainerIterator< ContainerType >::TScriptContainerIterator (const ContainerType & InContainer, const int32 InLogicalIndex) inline explicit
Definition at line 4269 of file UnrealType.h.
Member Function Documentation
Advance()
template<typename ContainerType> void TScriptContainerIterator< ContainerType >::Advance () inline private
Definition at line 4325 of file UnrealType.h.
GetInternalIndex()
template<typename ContainerType> int32 TScriptContainerIterator< ContainerType >::GetInternalIndex () const inline
Definition at line 4304 of file UnrealType.h.
Referenced by FScriptSetHelper::GetElementPtr(), FScriptMapHelper::GetKeyPtr(), FScriptMapHelper::GetPairPtr(), and FScriptMapHelper::GetValuePtr().
GetLogicalIndex()
template<typename ContainerType> int32 TScriptContainerIterator< ContainerType >::GetLogicalIndex () const inline
Definition at line 4309 of file UnrealType.h.
operator bool()
template<typename ContainerType> TScriptContainerIterator< ContainerType >::operator bool () const inline explicit
Definition at line 4299 of file UnrealType.h.
operator++() [1/2]
template<typename ContainerType> TScriptContainerIterator & TScriptContainerIterator< ContainerType >::operator++ () inline
Definition at line 4286 of file UnrealType.h.
operator++() [2/2]
template<typename ContainerType> TScriptContainerIterator TScriptContainerIterator< ContainerType >::operator++ (int) inline
Definition at line 4292 of file UnrealType.h.
UE_DEPRECATED()
template<typename ContainerType> TScriptContainerIterator< ContainerType >::UE_DEPRECATED (5. 4, "Use Iterator directly, GetInternalIndex or GetLogicalIndex instead.") const inline
Definition at line 4314 of file UnrealType.h.
Field Documentation
Container
template<typename ContainerType> const ContainerType& TScriptContainerIterator< ContainerType >::Container private
Definition at line 4321 of file UnrealType.h.
InternalIndex
template<typename ContainerType> int32 TScriptContainerIterator< ContainerType >::InternalIndex = INDEX_NONE private
Definition at line 4322 of file UnrealType.h.
LogicalIndex
template<typename ContainerType> int32 TScriptContainerIterator< ContainerType >::LogicalIndex = INDEX_NONE private
Definition at line 4323 of file UnrealType.h.
The documentation for this struct was generated from the following file:
UnrealType.h