Unreal Engine 5.6 C++ API: FSparseDistanceFieldMip Class Reference
FSparseDistanceFieldMip Class Reference
#include "DistanceFieldAtlas.h"
Public Member Functions
FSparseDistanceFieldMip ()
SIZE_T GetResourceSizeBytes () const
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
Data Fields
uint32 BulkOffset
uint32 BulkSize
FVector2f DistanceFieldToVolumeScaleBias
FInt32Vector IndirectionDimensions
int32 NumDistanceFieldBricks
FVector3f VolumeToVirtualUVAdd
FVector3f VolumeToVirtualUVScale
Friends
FArchive & operator<< (FArchive &Ar, FSparseDistanceFieldMip &Mip)
Detailed Description
Definition at line 198 of file DistanceFieldAtlas.h.
Constructor & Destructor Documentation
FSparseDistanceFieldMip()
FSparseDistanceFieldMip::FSparseDistanceFieldMip () inline
Definition at line 202 of file DistanceFieldAtlas.h.
References BulkOffset, BulkSize, DistanceFieldToVolumeScaleBias, IndirectionDimensions, NumDistanceFieldBricks, VolumeToVirtualUVAdd, and VolumeToVirtualUVScale.
Referenced by operator<<.
Member Function Documentation
GetResourceSizeBytes()
SIZE_T FSparseDistanceFieldMip::GetResourceSizeBytes () const inline
Definition at line 226 of file DistanceFieldAtlas.h.
References GetResourceSizeEx(), and FResourceSizeEx::GetTotalMemoryBytes().
GetResourceSizeEx()
void FSparseDistanceFieldMip::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const inline
Definition at line 233 of file DistanceFieldAtlas.h.
References FResourceSizeEx::AddDedicatedSystemMemoryBytes().
Referenced by GetResourceSizeBytes().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FSparseDistanceFieldMip & Mip) friend
Definition at line 220 of file DistanceFieldAtlas.h.
References FSparseDistanceFieldMip(), Ar, BulkOffset, BulkSize, DistanceFieldToVolumeScaleBias, IndirectionDimensions, NumDistanceFieldBricks, VolumeToVirtualUVAdd, and VolumeToVirtualUVScale.
Field Documentation
BulkOffset
uint32 FSparseDistanceFieldMip::BulkOffset
Definition at line 217 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
BulkSize
uint32 FSparseDistanceFieldMip::BulkSize
Definition at line 218 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
DistanceFieldToVolumeScaleBias
FVector2f FSparseDistanceFieldMip::DistanceFieldToVolumeScaleBias
Definition at line 216 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
IndirectionDimensions
FInt32Vector FSparseDistanceFieldMip::IndirectionDimensions
Definition at line 212 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
NumDistanceFieldBricks
int32 FSparseDistanceFieldMip::NumDistanceFieldBricks
Definition at line 213 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
VolumeToVirtualUVAdd
FVector3f FSparseDistanceFieldMip::VolumeToVirtualUVAdd
Definition at line 215 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
VolumeToVirtualUVScale
FVector3f FSparseDistanceFieldMip::VolumeToVirtualUVScale
Definition at line 214 of file DistanceFieldAtlas.h.
Referenced by FSparseDistanceFieldMip(), and operator<<.
The documentation for this class was generated from the following file:
DistanceFieldAtlas.h