Unreal Engine 5.6 C++ API: LocalLightComponent.h File Reference
LocalLightComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Components/LightComponent.h"
#include "LocalLightComponent.generated.h"
Data Structures
class ULocalLightComponent
Functions
UCLASS ()
A light component which emits light from a single point equally in all directions.
Variables
editinlinenew
hidecategories =(Object, LightShafts)
meta =(BlueprintSpawnableComponent)
Function Documentation
UCLASS()
UCLASS ()
A light component which emits light from a single point equally in all directions.
Variable Documentation
editinlinenew
editinlinenew
Definition at line 16 of file LocalLightComponent.h.
hidecategories
hidecategories =(Object, LightShafts)
Definition at line 16 of file LocalLightComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 16 of file LocalLightComponent.h.
Referenced by ULocalLightComponent::GENERATED_UCLASS_BODY(), ULocalLightComponent::UPROPERTY(), ULocalLightComponent::UPROPERTY(), and ULocalLightComponent::UPROPERTY().