Unreal Engine 5.6 C++ API: PlayerInput.h File Reference
PlayerInput.h File Reference
#include "CoreMinimal.h"
#include "Framework/Commands/InputChord.h"
#include "GestureRecognizer.h"
#include "InputCoreTypes.h"
#include "InputKeyEventArgs.h"
#include "KeyState.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ScriptMacros.h"
#include "PlayerInput.generated.h"
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogPlayerInput, Log, All)
struct UE_DEPRECATED (5.6, "Use FInputKeyEventArgs instead") FInputKeyParams
Paramaters to be considered when calling UPlayerInput::InputKey.
USTRUCT () struct FKeyBind
Struct containing mappings for legacy method of binding keys to exec commands.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogPlayerInput , Log , All)
References All, Category, config, FVector, Input, Log, MinimalAPI, transient, UFUNCTION, and UPROPERTY.
UE_DEPRECATED()
struct UE_DEPRECATED (5. 6, "Use FInputKeyEventArgs instead")
Paramaters to be considered when calling UPlayerInput::InputKey.
The key that has been pressed
The input device that has triggered this input
The event that has caused a Button key to be considered
The number of samples to be taken into account with the FKeyState::SampleCountAccumulator
The time between the previous frame and the current one
The Delta that the given key/axis has been changed by
If set to true, treat this input event as if it were from a gamepad, whether the FKey is a gamepad key or not.
Returns true if the Key used for this input is a gamepad key
Get the delta of the given axis for 1D axis
Get the delta of the given axis for 2D axis
Get the delta of the given axis for 3D axis
Definition at line 273 of file PlayerInput.h.
References BlueprintType, Category, FName, GENERATED_USTRUCT_BODY, FName::LexicalLess(), operator<(), operator==(), Other, TEXT, ToString(), and UPROPERTY.
USTRUCT()
USTRUCT ()
Struct containing mappings for legacy method of binding keys to exec commands.
Defines a mapping between an action and speech recognition.
Defines a mapping between an axis and key.
Defines a mapping between an action and key.
Configurable properties for control axes.
Configurable properties for control axes, used to transform raw input into game ready values.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Input/index.html
The key to be bound to the command
The command to execute when the key is pressed/released
Whether the control key needs to be held when the key event occurs
Whether the shift key needs to be held when the key event occurs
Whether the alt key needs to be held when the key event occurs
Whether the command key needs to be held when the key event occurs
Whether the control key must not be held when the key event occurs
Whether the shift key must not be held when the key event occurs
Whether the alt key must not be held when the key event occurs
Whether the command key must not be held when the key event occurs
What the dead zone of the axis is. For control axes such as analog sticks.
Scaling factor to multiply raw value by.
For applying curves to [0..1] axes, e.g. analog sticks
Inverts reported values for this axis
Axis Key these properties apply to
Properties for the Axis Key
Friendly name of action, e.g "jump"
true if one of the Shift keys must be down when the KeyEvent is received to be acknowledged
true if one of the Ctrl keys must be down when the KeyEvent is received to be acknowledged
true if one of the Alt keys must be down when the KeyEvent is received to be acknowledged
true if one of the Cmd keys must be down when the KeyEvent is received to be acknowledged
Key to bind it to.
Friendly name of axis, e.g "MoveForward"
Multiplier to use for the mapping when accumulating the axis value
Key to bind it to.
Friendly name of action, e.g "jump"
Key to bind it to.
Definition at line 33 of file PlayerInput.h.
References Category, Cmd, config, Control, GENERATED_USTRUCT_BODY, Key, transient, and UPROPERTY.