Unreal Engine 5.6 C++ API: GeneratedTypeName.h File Reference
GeneratedTypeName.h File Reference
#include "CoreTypes.h"
#include "Delegates/IntegerSequence.h"
Data Structures
struct UETypeName_Private::FSubstr
struct UETypeName_Private::TCharArray< NumChars >
Namespaces
namespace UETypeName_Private
Macros
#define SIG __PRETTY_FUNCTION__
#define SIG_ENDCHAR ']'
#define SIG_STARTCHAR '='
Functions
template<typename T>
const TCHAR * GetGeneratedTypeName ()
Returns a pointer to a static string representing the name of the type, e.g.:
template<typename T>
constexpr FSubstr UETypeName_Private::GetTypeSubstr ()
template<typename T, uint32... Indices>
constexpr TCharArray< sizeof...(Indices)> UETypeName_Private::TypeSubstrToCharArray (TIntegerSequence< uint32, Indices... >)
Macro Definition Documentation
SIG
#define SIG __PRETTY_FUNCTION__
Definition at line 16 of file GeneratedTypeName.h.
Referenced by UETypeName_Private::GetTypeSubstr().
SIG_ENDCHAR
#define SIG_ENDCHAR ']'
Definition at line 18 of file GeneratedTypeName.h.
Referenced by UETypeName_Private::GetTypeSubstr().
SIG_STARTCHAR
#define SIG_STARTCHAR '='
Definition at line 17 of file GeneratedTypeName.h.
Referenced by UETypeName_Private::GetTypeSubstr().
Function Documentation
GetGeneratedTypeName()
template<typename T> const TCHAR * GetGeneratedTypeName () inline
Returns a pointer to a static string representing the name of the type, e.g.:
const TCHAR* FStringName = GetGeneratedTypeName<FString>() // "FString"
Caveats:
The strings are compiler-dependent and thus non-portable, and so shouldn't be saved or relied upon as a form of identity, e.g. the example above returns "class FString" on MSVC.
Default template parameters are also handled differently by different compilers, sometimes ignored, sometimes not.
Only the concrete type is known to the compiler, aliases are ignored, e.g. GetGeneratedTypeName<TCHAR>() typically returns "wchar_t".
Definition at line 111 of file GeneratedTypeName.h.
References UETypeName_Private::GetTypeSubstr(), and UETypeName_Private::TypeSubstrToCharArray().
Referenced by FRDGBlackboard::Create(), UE::MovieScene::TEntityTaskComponents< T >::Fork_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Fork_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerEntity(), FRDGBlackboard::GetMutableChecked(), UE::MovieScene::FComponentRegistry::MakeComponentTypeInfoWithoutComponentOps(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerEntity(), and UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerEntity().