Unreal Engine 5.6 C++ API: TLinkedListBuilder< InElementType, InLinkAccessor > Struct Template Reference
TLinkedListBuilder< InElementType, InLinkAccessor > Struct Template Reference
Single linked list builder.
#include "LinkedListBuilder.h"
Public Types
using ElementType = InElementType
using LinkAccessor = InLinkAccessor
Public Member Functions
TLinkedListBuilder (ElementType **ListStartPtr)
FORCEINLINE void AppendNoTerminate (ElementType &Element)
FORCEINLINE void AppendTerminated (ElementType &Element)
FORCEINLINE ElementType * GetListEnd () const
FORCEINLINE ElementType * GetListStart () const
FORCEINLINE ElementType * GetNext (ElementType &Element) const
FORCEINLINE void MoveToEnd ()
FORCEINLINE bool MoveToNext ()
FORCEINLINE void NullTerminate ()
FORCEINLINE void Remove (ElementType &Element)
FORCEINLINE void Restart ()
UE_DEPRECATED (5.6, "Append is deprecated. Please use AppendTerminated instead.") FORCEINLINE void Append(ElementType &Element)
UE_NONCOPYABLE (TLinkedListBuilder)
Private Member Functions
FORCEINLINE ElementType *& GetNextRef (ElementType &Element) const
FORCEINLINE void WriteEndPtr (InElementType *NewValue)
Private Attributes
ElementType ** EndPtr
ElementType ** StartPtr
Detailed Description
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>>
struct TLinkedListBuilder< InElementType, InLinkAccessor >
Single linked list builder.
Definition at line 34 of file LinkedListBuilder.h.
Member Typedef Documentation
ElementType
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> using TLinkedListBuilder< InElementType, InLinkAccessor >::ElementType = InElementType
Definition at line 37 of file LinkedListBuilder.h.
LinkAccessor
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> using TLinkedListBuilder< InElementType, InLinkAccessor >::LinkAccessor = InLinkAccessor
Definition at line 38 of file LinkedListBuilder.h.
Constructor & Destructor Documentation
TLinkedListBuilder()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> TLinkedListBuilder< InElementType, InLinkAccessor >::TLinkedListBuilder (ElementType ** ListStartPtr) inline explicit nodiscard
Definition at line 54 of file LinkedListBuilder.h.
Member Function Documentation
AppendNoTerminate()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::AppendNoTerminate (ElementType & Element) inline
Definition at line 75 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::AppendTerminated().
AppendTerminated()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::AppendTerminated (ElementType & Element) inline
Definition at line 82 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::UE_DEPRECATED().
GetListEnd()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE ElementType * TLinkedListBuilder< InElementType, InLinkAccessor >::GetListEnd () const inline nodiscard
Definition at line 140 of file LinkedListBuilder.h.
GetListStart()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE ElementType * TLinkedListBuilder< InElementType, InLinkAccessor >::GetListStart () const inline nodiscard
Definition at line 135 of file LinkedListBuilder.h.
GetNext()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE ElementType * TLinkedListBuilder< InElementType, InLinkAccessor >::GetNext (ElementType & Element) const inline nodiscard
Definition at line 130 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::MoveToEnd(), and TLinkedListBuilder< UField >::Remove().
GetNextRef()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE ElementType *& TLinkedListBuilder< InElementType, InLinkAccessor >::GetNextRef (ElementType & Element) const inline nodiscard private
Definition at line 146 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::GetNext(), and TLinkedListBuilder< UField >::Remove().
MoveToEnd()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::MoveToEnd () inline
Definition at line 111 of file LinkedListBuilder.h.
MoveToNext()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE bool TLinkedListBuilder< InElementType, InLinkAccessor >::MoveToNext () inline
Definition at line 119 of file LinkedListBuilder.h.
NullTerminate()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::NullTerminate () inline
Definition at line 106 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::AppendTerminated().
Remove()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::Remove (ElementType & Element) inline
Definition at line 88 of file LinkedListBuilder.h.
Restart()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::Restart () inline
Definition at line 63 of file LinkedListBuilder.h.
UE_DEPRECATED()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> TLinkedListBuilder< InElementType, InLinkAccessor >::UE_DEPRECATED (5. 6, "Append is deprecated. Please use AppendTerminated instead.") & inline
Definition at line 68 of file LinkedListBuilder.h.
UE_NONCOPYABLE()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> TLinkedListBuilder< InElementType, InLinkAccessor >::UE_NONCOPYABLE (TLinkedListBuilder< InElementType, InLinkAccessor >)
WriteEndPtr()
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> FORCEINLINE void TLinkedListBuilder< InElementType, InLinkAccessor >::WriteEndPtr (InElementType * NewValue) inline private
Definition at line 43 of file LinkedListBuilder.h.
Referenced by TLinkedListBuilder< UField >::AppendNoTerminate(), and TLinkedListBuilder< UField >::NullTerminate().
Field Documentation
EndPtr
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> ElementType** TLinkedListBuilder< InElementType, InLinkAccessor >::EndPtr private
Definition at line 152 of file LinkedListBuilder.h.
StartPtr
template<typename InElementType, typename InLinkAccessor = TLinkedListBuilderNextLink<InElementType>> ElementType** TLinkedListBuilder< InElementType, InLinkAccessor >::StartPtr private
Definition at line 151 of file LinkedListBuilder.h.
The documentation for this struct was generated from the following file:
LinkedListBuilder.h