Unreal Engine 5.6 C++ API: FScriptIntegrationObjectHelper Class Reference
FScriptIntegrationObjectHelper Class Reference
Helper class for script integrations to access some UObject innards.
#include "UObjectGlobals.h"
Static Public Member Functions
static void InitProperties (const FObjectInitializer &ObjectInitializer, UObject *Obj, UClass *DefaultsClass, UObject *DefaultData)
Binary initialize object properties to zero or defaults.
static bool InitSubobjectProperties (const FObjectInitializer &ObjectInitializer)
Calls InitProperties for any default subobjects created through this ObjectInitializer.
static void InstanceSubobjects (const FObjectInitializer &ObjectInitializer, UClass *Class, bool bNeedInstancing, bool bNeedSubobjectInstancing)
Create copies of the object's components from their templates.
static void PostConstructInitObject (FObjectInitializer &ObjectInitializer)
Finalizes a constructed UObject by initializing properties, instancing & initializing sub-objects, etc.
Detailed Description
Helper class for script integrations to access some UObject innards.
Needed for script-generated UObject classes
Definition at line 1789 of file UObjectGlobals.h.
Member Function Documentation
InitProperties()
void FScriptIntegrationObjectHelper::InitProperties (const FObjectInitializer & ObjectInitializer, UObject * Obj, UClass * DefaultsClass, UObject * DefaultData) inline static
Binary initialize object properties to zero or defaults.
Parameters
ObjectInitializer FObjectInitializer helper
Obj object to initialize data for
DefaultsClass the class to use for initializing the data
DefaultData the buffer containing the source data for the initialization
Definition at line 1800 of file UObjectGlobals.h.
References FObjectInitializer::bCopyTransientsFromClassDefaults, and FObjectInitializer::InitProperties().
InitSubobjectProperties()
bool FScriptIntegrationObjectHelper::InitSubobjectProperties (const FObjectInitializer & ObjectInitializer) inline static
Calls InitProperties for any default subobjects created through this ObjectInitializer.
Parameters
bAllowInstancing Indicates whether the object's components may be copied from their templates.
Returns
true if there are any subobjects which require instancing.
Definition at line 1810 of file UObjectGlobals.h.
References FObjectInitializer::InitSubobjectProperties(), and FObjectInitializer::IsInstancingAllowed().
InstanceSubobjects()
void FScriptIntegrationObjectHelper::InstanceSubobjects (const FObjectInitializer & ObjectInitializer, UClass * Class, bool bNeedInstancing, bool bNeedSubobjectInstancing) inline static
Create copies of the object's components from their templates.
Parameters
ObjectInitializer FObjectInitializer helper
Class Class of the object we are initializing
bNeedInstancing Indicates whether the object's components need to be instanced
bNeedSubobjectInstancing Indicates whether subobjects of the object's components need to be instanced
Definition at line 1822 of file UObjectGlobals.h.
References Class, and FObjectInitializer::InstanceSubobjects().
PostConstructInitObject()
void FScriptIntegrationObjectHelper::PostConstructInitObject (FObjectInitializer & ObjectInitializer) inline static
Finalizes a constructed UObject by initializing properties, instancing & initializing sub-objects, etc.
Parameters
ObjectInitializer The initializer to run PostConstructInit() on.
Definition at line 1833 of file UObjectGlobals.h.
References FObjectInitializer::PostConstructInit().
The documentation for this class was generated from the following file:
UObjectGlobals.h