Unreal Engine 5.6 C++ API: UnrealNetwork.h File Reference
UnrealNetwork.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/CoreNet.h"
#include "EngineLogs.h"
#include "UObject/UnrealType.h"
#include "Engine/EngineBaseTypes.h"
#include "Net/Core/Connection/NetResult.h"
#include "Net/Core/PropertyConditions/PropertyConditions.h"
#include "Net/ReplayResult.h"
#include <type_traits>
Data Structures
struct CGetFastArrayCreateReplicationFragmentFuncable
struct FDoRepLifetimeParams
Struct containing various parameters that can be passed to DOREPLIFETIME_WITH_PARAMS to control how variables are replicated.
struct FNetworkReplayDelegates
struct NetworkingPrivate::FRepClassDescriptor
struct NetworkingPrivate::FRepPropertyDescriptor
Namespaces
namespace NetworkingPrivate
Macros
#define DISABLE_ALL_CLASS_REPLICATED_PROPERTIES(c, SuperClassBehavior)
Use this macro in GetLifetimeReplicatedProps to flag all replicated properties of a class as not-replicated.
#define DISABLE_ALL_CLASS_REPLICATED_PROPERTIES_FAST(c, SuperClassBehavior)
#define DISABLE_REPLICATED_PRIVATE_PROPERTY(c, v)
Use this macro to disable inherited properties that are private.
#define DISABLE_REPLICATED_PROPERTY(c, v)
Use this macro in GetLifetimeReplicatedProps to flag a replicated property as not-replicated.
#define DISABLE_REPLICATED_PROPERTY_FAST(c, v)
#define DISABLE_REPLICATED_PROPERTY_FAST_STATIC_ARRAY(c, v)
#define DOREPCUSTOMCONDITION_ACTIVE_FAST(c, v, active)
#define DOREPCUSTOMCONDITION_SETACTIVE_FAST(c, v, active)
#define DOREPCUSTOMCONDITION_SETACTIVE_FAST_STATIC_ARRAY(c, v, active)
#define DOREPDYNAMICCONDITION_INITCONDITION_FAST(c, v, cond)
To be used in a UObject's GetReplicatedCustomConditionState for example.
#define DOREPDYNAMICCONDITION_SETCONDITION_FAST(c, v, cond)
To be used when a condition is to be changed.
#define DOREPLIFETIME(c, v)
#define DOREPLIFETIME_ACTIVE_OVERRIDE(c, v, active)
#define DOREPLIFETIME_ACTIVE_OVERRIDE_FAST(c, v, active)
#define DOREPLIFETIME_ACTIVE_OVERRIDE_FAST_STATIC_ARRAY(c, v, active)
#define DOREPLIFETIME_CONDITION(c, v, cond)
#define DOREPLIFETIME_CONDITION_NOTIFY(c, v, cond, rncond)
Allows gamecode to specify RepNotify condition: REPNOTIFY_OnChanged (default) or REPNOTIFY_Always for when repnotify function is called.
#define DOREPLIFETIME_DIFFNAMES(c, v, n)
This macro is used by nativized code (DynamicClasses), so the Property may be recreated.
#define DOREPLIFETIME_WITH_PARAMS(c, v, params)
#define DOREPLIFETIME_WITH_PARAMS_FAST(c, v, params)
#define DOREPLIFETIME_WITH_PARAMS_FAST_STATIC_ARRAY(c, v, params)
#define RESET_REPLIFETIME(c, v)
#define RESET_REPLIFETIME_CONDITION(c, v, cond)
#define RESET_REPLIFETIME_CONDITION_FAST(c, v, cond)
#define RESET_REPLIFETIME_CONDITION_FAST_STATIC_ARRAY(c, v, cond)
#define RESET_REPLIFETIME_FAST(c, v)
#define RESET_REPLIFETIME_FAST_STATIC_ARRAY(c, v)
#define RESET_REPLIFETIME_FAST_WITH_PARAMS(c, v, params)
#define RESET_REPLIFETIME_WITH_PARAMS(c, v, params)
#define RPC_VALIDATE(expression)
Typedefs
typedef TMap< FString, TArray< uint8 > > FDemoFrameDataMap
Functions
int32 BestSignedDifference (int32 Value, int32 Reference, int32 Max)
DECLARE_DELEGATE_OneParam (FGetOverridableVersionDataForDemoHeaderReadDelegate, FOverridableReplayVersionData &)
DECLARE_DELEGATE_OneParam (FGetOverridableVersionDataForDemoHeaderWriteDelegate, FOverridableReplayVersionData &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayPlaybackCompleteDelegate, UWorld *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayRecordingCompleteDelegate, UWorld *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayRecordingStartAttemptDelegate, UWorld *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayScrubCompleteDelegate, UWorld *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayStartedDelegate, UWorld *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnWriteGameSpecificDemoHeader, TArray< FString > &)
AActor * DECLARE_MULTICAST_DELEGATE_OneParam (FPreReplayScrub, UWorld *)
Fired at the start of replay checkpoint loading.
DECLARE_MULTICAST_DELEGATE_OneParam (FReplayScrubTeardown, UWorld *)
Fired mid-checkpoint load after the previous game state is torn down, and prior to any GC.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnProcessGameSpecificFrameData, UWorld *, float, const FDemoFrameDataMap &)
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnWriteGameSpecificFrameData, UWorld *, float, FDemoFrameDataMap &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPauseChannelsChangedDelegate, UWorld *, bool)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnProcessGameSpecificDemoHeader, const TArray< FString > &, FString &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnReplayIDChangedDelegate, UWorld *, const FString &)
PRAGMA_ENABLE_DEPRECATION_WARNINGS DECLARE_MULTICAST_DELEGATE_TwoParams (FOnReplayPlaybackFailureDelegate, UWorld *, const UE::Net::TNetResult< EReplayResult > &)
void DisableAllReplicatedPropertiesOfClass (const NetworkingPrivate::FRepClassDescriptor &ClassDescriptor, EFieldIteratorFlags::SuperClassFlags SuperClassBehavior, TArray< FLifetimeProperty > &OutLifetimeProps)
void DisableAllReplicatedPropertiesOfClass (const UClass *ThisClass, const UClass *ClassToDisable, EFieldIteratorFlags::SuperClassFlags SuperClassBehavior, TArray< FLifetimeProperty > &OutLifetimeProps)
void DisableReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor &PropertyDescriptor, TArray< FLifetimeProperty > &OutLifetimeProps)
void DisableReplicatedLifetimeProperty (const UClass *ThisClass, const UClass *PropertyClass, FName PropertyName, TArray< FLifetimeProperty > &OutLifetimeProps)
template<typename T>
TEnableIf<!TModels_V< CGetFastArrayCreateReplicationFragmentFuncable, T >, constFDoRepLifetimeParams & >::Type FixupParams (const FDoRepLifetimeParams &Params)
FProperty * GetReplicatedProperty (const UClass *CallingClass, const UClass *PropClass, const FName &PropName)
wrapper to find replicated properties that also makes sure they're valid
int32 MakeRelative (int32 Value, int32 Reference, int32 Max)
void RegisterReplicatedLifetimeProperty (const FProperty *ReplicatedProperty, TArray< FLifetimeProperty > &OutLifetimeProps, const FDoRepLifetimeParams &Params)
void RegisterReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor &PropertyDescriptor, TArray< FLifetimeProperty > &OutLifetimeProps, const FDoRepLifetimeParams &Params)
void ResetReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor &PropertyDescriptor, const FDoRepLifetimeParams &Params, TArray< FLifetimeProperty > &OutLifetimeProps)
void ResetReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor &PropertyDescriptor, ELifetimeCondition LifetimeCondition, TArray< FLifetimeProperty > &OutLifetimeProps)
void ResetReplicatedLifetimeProperty (const UClass *ThisClass, const UClass *PropertyClass, FName PropertyName, const FDoRepLifetimeParams &Params, TArray< FLifetimeProperty > &OutLifetimeProps)
void ResetReplicatedLifetimeProperty (const UClass *ThisClass, const UClass *PropertyClass, FName PropertyName, ELifetimeCondition LifetimeCondition, TArray< FLifetimeProperty > &OutLifetimeProps)
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "Deprecated in favor of FOnReplayPlaybackFailureDelegate") DECLARE_MULTICAST_DELEGATE_TwoParams(FOnReplayStartFailureDelegate
UE_DEPRECATED (5.1, "No longer used.") DECLARE_MULTICAST_DELEGATE_OneParam(FPreActorDestroyReplayScrub
template<class BaseClass, class DerivedClass>
constexpr bool ValidateReplicatedClassInheritance ()
Macro Definition Documentation
DISABLE_ALL_CLASS_REPLICATED_PROPERTIES
#define DISABLE_ALL_CLASS_REPLICATED_PROPERTIES (c, SuperClassBehavior)
Value:
DisableAllReplicatedPropertiesOfClass(StaticClass(), c::StaticClass(), SuperClassBehavior, OutLifetimeProps);
Use this macro in GetLifetimeReplicatedProps to flag all replicated properties of a class as not-replicated.
Use the EFieldIteratorFlags enum to disable all inherited properties or only those of the class specified
Definition at line 437 of file UnrealNetwork.h.
DISABLE_ALL_CLASS_REPLICATED_PROPERTIES_FAST
#define DISABLE_ALL_CLASS_REPLICATED_PROPERTIES_FAST (c, SuperClassBehavior)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), "DISABLE_ALL_CLASS_REPLICATED_PROPERTIES"); \
    const TCHAR* DoRepClassName_##c(TEXT(#c)); \
    const NetworkingPrivate::FRepClassDescriptor ClassDescriptor_##c(DoRepClassName_##c, (int32)c::ENetFields_Private::NETFIELD_REP_START, (int32)c::ENetFields_Private::NETFIELD_REP_END); \
    DisableAllReplicatedPropertiesOfClass(ClassDescriptor_##c, SuperClassBehavior, OutLifetimeProps); \
}
Definition at line 440 of file UnrealNetwork.h.
DISABLE_REPLICATED_PRIVATE_PROPERTY
#define DISABLE_REPLICATED_PRIVATE_PROPERTY (c, v)
Value:
DisableReplicatedLifetimeProperty(StaticClass(), c::StaticClass(), FName(TEXT(#v)), OutLifetimeProps);
Use this macro to disable inherited properties that are private.
Be careful since it removes a compile-time error when the variable doesn't exist
Definition at line 415 of file UnrealNetwork.h.
DISABLE_REPLICATED_PROPERTY
#define DISABLE_REPLICATED_PROPERTY (c, v)
Value:
DisableReplicatedLifetimeProperty(StaticClass(), c::StaticClass(), GET_MEMBER_NAME_CHECKED(c,v), OutLifetimeProps);
Use this macro in GetLifetimeReplicatedProps to flag a replicated property as not-replicated.
Definition at line 411 of file UnrealNetwork.h.
DISABLE_REPLICATED_PROPERTY_FAST
#define DISABLE_REPLICATED_PROPERTY_FAST (c, v)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v, 1); \
    DisableReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, OutLifetimeProps); \
}
Definition at line 418 of file UnrealNetwork.h.
DISABLE_REPLICATED_PROPERTY_FAST_STATIC_ARRAY
#define DISABLE_REPLICATED_PROPERTY_FAST_STATIC_ARRAY (c, v)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v##_STATIC_ARRAY, (int32)c::EArrayDims_Private::v); \
    DisableReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, OutLifetimeProps); \
}
Definition at line 426 of file UnrealNetwork.h.
DOREPCUSTOMCONDITION_ACTIVE_FAST
#define DOREPCUSTOMCONDITION_ACTIVE_FAST (c, v, active)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    OutActiveState.SetActiveState((uint16)c::ENetFields_Private::v, active); \
}
Definition at line 324 of file UnrealNetwork.h.
DOREPCUSTOMCONDITION_SETACTIVE_FAST
#define DOREPCUSTOMCONDITION_SETACTIVE_FAST (c, v, active)
Value:
{ \
    UE::Net::Private::FNetPropertyConditionManager::Get().SetPropertyActive(this, (uint16)c::ENetFields_Private::v, active); \
}
Definition at line 330 of file UnrealNetwork.h.
DOREPCUSTOMCONDITION_SETACTIVE_FAST_STATIC_ARRAY
#define DOREPCUSTOMCONDITION_SETACTIVE_FAST_STATIC_ARRAY (c, v, active)
Value:
{ \
    UE::Net::Private::FNetPropertyConditionManager& PropertyConditionManager = UE::Net::Private::FNetPropertyConditionManager::Get(); \
    for (int32 i = 0; i < (int32)c::EArrayDims_Private::v; ++i) \
    { \
        PropertyConditionManager.SetPropertyActive(this, (uint16)c::ENetFields_Private::v##_STATIC_ARRAY + i, active); \
    } \
}
Definition at line 335 of file UnrealNetwork.h.
DOREPDYNAMICCONDITION_INITCONDITION_FAST
#define DOREPDYNAMICCONDITION_INITCONDITION_FAST (c, v, cond)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    OutActiveState.SetDynamicCondition((uint16)c::ENetFields_Private::v, cond); \
}
To be used in a UObject's GetReplicatedCustomConditionState for example.
Definition at line 345 of file UnrealNetwork.h.
DOREPDYNAMICCONDITION_SETCONDITION_FAST
#define DOREPDYNAMICCONDITION_SETCONDITION_FAST (c, v, cond)
Value:
{ \
    UE::Net::Private::FNetPropertyConditionManager::Get().SetPropertyDynamicCondition(this, (uint16)c::ENetFields_Private::v, cond); \
}
To be used when a condition is to be changed.
This should be called as soon as the condition changes, not during PreReplication.
Note
Changing the condition of a custom delta property, such as a FastArraySerializer, after it has replicated can result in unexpected behavior.
Definition at line 355 of file UnrealNetwork.h.
DOREPLIFETIME
#define DOREPLIFETIME (c, v)
Value:
DOREPLIFETIME_WITH_PARAMS(c,v,FDoRepLifetimeParams())
Definition at line 261 of file UnrealNetwork.h.
DOREPLIFETIME_ACTIVE_OVERRIDE
#define DOREPLIFETIME_ACTIVE_OVERRIDE (c, v, active)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    static FProperty* sp##v = GetReplicatedProperty(StaticClass(), c::StaticClass(),GET_MEMBER_NAME_CHECKED(c,v)); \
    UE::Net::Private::FNetPropertyConditionManager& PropertyConditionManager = UE::Net::Private::FNetPropertyConditionManager::Get(); \
    for (int32 i = 0; i < sp##v->ArrayDim; i++) \
    { \
        PropertyConditionManager.SetPropertyActiveOverride(this, sp##v->RepIndex + i, active); \
    } \
}
Definition at line 313 of file UnrealNetwork.h.
DOREPLIFETIME_ACTIVE_OVERRIDE_FAST
#define DOREPLIFETIME_ACTIVE_OVERRIDE_FAST (c, v, active)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    UE::Net::Private::FNetPropertyConditionManager::Get().SetPropertyActiveOverride(this, (int32)c::ENetFields_Private::v, active); \
}
Definition at line 297 of file UnrealNetwork.h.
DOREPLIFETIME_ACTIVE_OVERRIDE_FAST_STATIC_ARRAY
#define DOREPLIFETIME_ACTIVE_OVERRIDE_FAST_STATIC_ARRAY (c, v, active)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    UE::Net::Private::FNetPropertyConditionManager& PropertyConditionManager = UE::Net::Private::FNetPropertyConditionManager::Get(); \
    for (int32 i = 0; i < (int32)c::EArrayDims_Private::v; ++i) \
    { \
        PropertyConditionManager.SetPropertyActiveOverride(this, (int32)c::ENetFields_Private::v##_STATIC_ARRAY + i, active); \
    } \
}
Definition at line 303 of file UnrealNetwork.h.
DOREPLIFETIME_CONDITION
#define DOREPLIFETIME_CONDITION (c, v, cond)
Value:
{ \
    static_assert(cond != COND_NetGroup, "COND_NetGroup cannot be used on replicated properties. Only when registering subobjects"); \
    FDoRepLifetimeParams LocalDoRepParams; \
    LocalDoRepParams.Condition = cond; \
    DOREPLIFETIME_WITH_PARAMS(c,v,LocalDoRepParams); \
}
Definition at line 279 of file UnrealNetwork.h.
DOREPLIFETIME_CONDITION_NOTIFY
#define DOREPLIFETIME_CONDITION_NOTIFY (c, v, cond, rncond)
Value:
{ \
    static_assert(cond != COND_NetGroup, "COND_NetGroup cannot be used on replicated properties. Only when registering subobjects"); \
    FDoRepLifetimeParams LocalDoRepParams; \
    LocalDoRepParams.Condition = cond; \
    LocalDoRepParams.RepNotifyCondition = rncond; \
    DOREPLIFETIME_WITH_PARAMS(c,v,LocalDoRepParams); \
}
Allows gamecode to specify RepNotify condition: REPNOTIFY_OnChanged (default) or REPNOTIFY_Always for when repnotify function is called.
Definition at line 288 of file UnrealNetwork.h.
DOREPLIFETIME_DIFFNAMES
#define DOREPLIFETIME_DIFFNAMES (c, v, n)
Value:
{ \
    static TWeakFieldPtr<FProperty> __swp##v{};                         \
    const FProperty* sp##v = __swp##v.Get();                                \
    if (nullptr == sp##v)                                                   \
    {                                                                       \
        sp##v = GetReplicatedProperty(StaticClass(), c::StaticClass(), n);  \
        __swp##v = sp##v;                                                   \
    }                                                                       \
    for ( int32 i = 0; i < sp##v->ArrayDim; i++ )                          \
    {                                                                       \
        OutLifetimeProps.AddUnique( FLifetimeProperty( sp##v->RepIndex + i ) ); \
    }                                                                       \
}
This macro is used by nativized code (DynamicClasses), so the Property may be recreated.
Definition at line 264 of file UnrealNetwork.h.
DOREPLIFETIME_WITH_PARAMS
#define DOREPLIFETIME_WITH_PARAMS (c, v, params)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    FProperty* ReplicatedProperty = GetReplicatedProperty(StaticClass(), c::StaticClass(), GET_MEMBER_NAME_CHECKED(c,v)); \
    PRAGMA_DISABLE_DEPRECATION_WARNINGS \
    RegisterReplicatedLifetimeProperty(ReplicatedProperty, OutLifetimeProps, FixupParams<decltype(c::v)>(params)); \
    PRAGMA_ENABLE_DEPRECATION_WARNINGS \
}
Definition at line 252 of file UnrealNetwork.h.
DOREPLIFETIME_WITH_PARAMS_FAST
#define DOREPLIFETIME_WITH_PARAMS_FAST (c, v, params)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v, 1); \
\
    PRAGMA_DISABLE_DEPRECATION_WARNINGS \
    RegisterReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, OutLifetimeProps, FixupParams<decltype(c::v)>(params)); \
    PRAGMA_ENABLE_DEPRECATION_WARNINGS \
}
Definition at line 233 of file UnrealNetwork.h.
DOREPLIFETIME_WITH_PARAMS_FAST_STATIC_ARRAY
#define DOREPLIFETIME_WITH_PARAMS_FAST_STATIC_ARRAY (c, v, params)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v##_STATIC_ARRAY, (int32)c::EArrayDims_Private::v); \
    RegisterReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, OutLifetimeProps, params); \
}
Definition at line 244 of file UnrealNetwork.h.
RESET_REPLIFETIME
#define RESET_REPLIFETIME (c, v)
Value:
RESET_REPLIFETIME_CONDITION(c, v, COND_None)
Definition at line 461 of file UnrealNetwork.h.
RESET_REPLIFETIME_CONDITION
#define RESET_REPLIFETIME_CONDITION (c, v, cond)
Value:
ResetReplicatedLifetimeProperty(StaticClass(), c::StaticClass(), GET_MEMBER_NAME_CHECKED(c,v), cond, OutLifetimeProps);
Definition at line 459 of file UnrealNetwork.h.
RESET_REPLIFETIME_CONDITION_FAST
#define RESET_REPLIFETIME_CONDITION_FAST (c, v, cond)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v, 1); \
    ResetReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, cond, OutLifetimeProps); \
}
Definition at line 463 of file UnrealNetwork.h.
RESET_REPLIFETIME_CONDITION_FAST_STATIC_ARRAY
#define RESET_REPLIFETIME_CONDITION_FAST_STATIC_ARRAY (c, v, cond)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v##_STATIC_ARRAY, (int32)c::EArrayDims_Private::v); \
    ResetReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, cond, OutLifetimeProps); \
}
Definition at line 471 of file UnrealNetwork.h.
RESET_REPLIFETIME_FAST
#define RESET_REPLIFETIME_FAST (c, v)
Value:
RESET_REPLIFETIME_CONDITION_FAST(c, v, COND_None)
Definition at line 479 of file UnrealNetwork.h.
RESET_REPLIFETIME_FAST_STATIC_ARRAY
#define RESET_REPLIFETIME_FAST_STATIC_ARRAY (c, v)
Value:
RESET_REPLIFETIME_FAST_STATIC_ARRAY(c, v, COND_None)
Definition at line 480 of file UnrealNetwork.h.
RESET_REPLIFETIME_FAST_WITH_PARAMS
#define RESET_REPLIFETIME_FAST_WITH_PARAMS (c, v, params)
Value:
{ \
    static_assert(ValidateReplicatedClassInheritance<c, ThisClass>(), #c "." #v " is not accessible from this class."); \
    const TCHAR* DoRepPropertyName_##c_##v(TEXT(#v)); \
    const NetworkingPrivate::FRepPropertyDescriptor PropertyDescriptor_##c_##v(DoRepPropertyName_##c_##v, (int32)c::ENetFields_Private::v, 1); \
    ResetReplicatedLifetimeProperty(PropertyDescriptor_##c_##v, params, OutLifetimeProps); \
}
Definition at line 484 of file UnrealNetwork.h.
RESET_REPLIFETIME_WITH_PARAMS
#define RESET_REPLIFETIME_WITH_PARAMS (c, v, params)
Value:
ResetReplicatedLifetimeProperty(StaticClass(), c::StaticClass(), GET_MEMBER_NAME_CHECKED(c,v), params, OutLifetimeProps);
Definition at line 482 of file UnrealNetwork.h.
RPC_VALIDATE
#define RPC_VALIDATE (expression)
Value:
    if ( !( expression ) )                              \
    {                                                   \
        UE_LOG( LogNet, Warning,                     \
        TEXT("RPC_VALIDATE Failed: ")                   \
        TEXT( PREPROCESSOR_TO_STRING( expression ) )  \
        TEXT(" File: ")                                 \
        TEXT( PREPROCESSOR_TO_STRING( __FILE__ ) )        \
        TEXT(" Line: ")                                 \
        TEXT( PREPROCESSOR_TO_STRING( __LINE__ ) ) ); \
        return false;                                   \
    }
Definition at line 523 of file UnrealNetwork.h.
Typedef Documentation
FDemoFrameDataMap
typedef TMap<FString, TArray<uint8> > FDemoFrameDataMap
Definition at line 57 of file UnrealNetwork.h.
Function Documentation
BestSignedDifference()
int32 BestSignedDifference (int32 Value, int32 Reference, int32 Max) inline
Definition at line 36 of file UnrealNetwork.h.
References Max, and Value.
Referenced by MakeRelative().
DECLARE_DELEGATE_OneParam() [1/2]
DECLARE_DELEGATE_OneParam (FGetOverridableVersionDataForDemoHeaderReadDelegate , FOverridableReplayVersionData &)
References DECLARE_DELEGATE_OneParam.
DECLARE_DELEGATE_OneParam() [2/2]
DECLARE_DELEGATE_OneParam (FGetOverridableVersionDataForDemoHeaderWriteDelegate , FOverridableReplayVersionData &)
References DECLARE_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayPlaybackCompleteDelegate , UWorld *)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [2/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayRecordingCompleteDelegate , UWorld *)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [3/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayRecordingStartAttemptDelegate , UWorld *)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [4/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayScrubCompleteDelegate , UWorld *)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [5/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReplayStartedDelegate , UWorld *)
References DECLARE_MULTICAST_DELEGATE_OneParam, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
DECLARE_MULTICAST_DELEGATE_OneParam() [6/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnWriteGameSpecificDemoHeader , TArray< FString > &)
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [7/8]
AActor * DECLARE_MULTICAST_DELEGATE_OneParam (FPreReplayScrub , UWorld *)
Fired at the start of replay checkpoint loading.
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_OneParam() [8/8]
DECLARE_MULTICAST_DELEGATE_OneParam (FReplayScrubTeardown , UWorld *)
Fired mid-checkpoint load after the previous game state is torn down, and prior to any GC.
References DECLARE_MULTICAST_DELEGATE_OneParam.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnProcessGameSpecificFrameData , UWorld * , float , const FDemoFrameDataMap &)
References DECLARE_MULTICAST_DELEGATE_ThreeParams.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnWriteGameSpecificFrameData , UWorld * , float , FDemoFrameDataMap &)
References DECLARE_MULTICAST_DELEGATE_ThreeParams.
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/4]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPauseChannelsChangedDelegate , UWorld * , bool)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/4]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnProcessGameSpecificDemoHeader , const TArray< FString > & , FString &)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
DECLARE_MULTICAST_DELEGATE_TwoParams() [3/4]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnReplayIDChangedDelegate , UWorld * , const FString &)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
DECLARE_MULTICAST_DELEGATE_TwoParams() [4/4]
PRAGMA_ENABLE_DEPRECATION_WARNINGS DECLARE_MULTICAST_DELEGATE_TwoParams (FOnReplayPlaybackFailureDelegate , UWorld * , const UE::Net::TNetResult< EReplayResult > &)
References DECLARE_MULTICAST_DELEGATE_TwoParams.
DisableAllReplicatedPropertiesOfClass() [1/2]
void DisableAllReplicatedPropertiesOfClass (const NetworkingPrivate::FRepClassDescriptor & ClassDescriptor, EFieldIteratorFlags::SuperClassFlags SuperClassBehavior, TArray< FLifetimeProperty > & OutLifetimeProps)
DisableAllReplicatedPropertiesOfClass() [2/2]
void DisableAllReplicatedPropertiesOfClass (const UClass * ThisClass, const UClass * ClassToDisable, EFieldIteratorFlags::SuperClassFlags SuperClassBehavior, TArray< FLifetimeProperty > & OutLifetimeProps)
DisableReplicatedLifetimeProperty() [1/2]
void DisableReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor & PropertyDescriptor, TArray< FLifetimeProperty > & OutLifetimeProps)
DisableReplicatedLifetimeProperty() [2/2]
void DisableReplicatedLifetimeProperty (const UClass * ThisClass, const UClass * PropertyClass, FName PropertyName, TArray< FLifetimeProperty > & OutLifetimeProps)
References PropertyName.
FixupParams()
template<typename T> TEnableIf<!TModels_V< CGetFastArrayCreateReplicationFragmentFuncable, T >, constFDoRepLifetimeParams & >::Type FixupParams (const FDoRepLifetimeParams & Params) inline
Definition at line 398 of file UnrealNetwork.h.
References Params.
GetReplicatedProperty()
FProperty * GetReplicatedProperty (const UClass * CallingClass, const UClass * PropClass, const FName & PropName) inline
wrapper to find replicated properties that also makes sure they're valid
Definition at line 221 of file UnrealNetwork.h.
References Fatal, FindFieldChecked(), FField::GetFullName(), FProperty::PropertyFlags, TEXT, and UE_LOG.
MakeRelative()
int32 MakeRelative (int32 Value, int32 Reference, int32 Max) inline
Definition at line 40 of file UnrealNetwork.h.
References BestSignedDifference(), Max, and Value.
Referenced by FNetworkPredictionSerialization::SerializeFrame().
RegisterReplicatedLifetimeProperty() [1/2]
void RegisterReplicatedLifetimeProperty (const FProperty * ReplicatedProperty, TArray< FLifetimeProperty > & OutLifetimeProps, const FDoRepLifetimeParams & Params)
References Params.
RegisterReplicatedLifetimeProperty() [2/2]
void RegisterReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor & PropertyDescriptor, TArray< FLifetimeProperty > & OutLifetimeProps, const FDoRepLifetimeParams & Params)
References Params.
ResetReplicatedLifetimeProperty() [1/4]
void ResetReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor & PropertyDescriptor, const FDoRepLifetimeParams & Params, TArray< FLifetimeProperty > & OutLifetimeProps)
References Params.
ResetReplicatedLifetimeProperty() [2/4]
void ResetReplicatedLifetimeProperty (const NetworkingPrivate::FRepPropertyDescriptor & PropertyDescriptor, ELifetimeCondition LifetimeCondition, TArray< FLifetimeProperty > & OutLifetimeProps)
ResetReplicatedLifetimeProperty() [3/4]
void ResetReplicatedLifetimeProperty (const UClass * ThisClass, const UClass * PropertyClass, FName PropertyName, const FDoRepLifetimeParams & Params, TArray< FLifetimeProperty > & OutLifetimeProps)
References Params, and PropertyName.
ResetReplicatedLifetimeProperty() [4/4]
void ResetReplicatedLifetimeProperty (const UClass * ThisClass, const UClass * PropertyClass, FName PropertyName, ELifetimeCondition LifetimeCondition, TArray< FLifetimeProperty > & OutLifetimeProps)
References PropertyName.
UE_DEPRECATED() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5. 1, "Deprecated in favor of FOnReplayPlaybackFailureDelegate")
References DECLARE_MULTICAST_DELEGATE_TwoParams, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED.
UE_DEPRECATED() [2/2]
UE_DEPRECATED (5. 1, "No longer used.")
References DECLARE_MULTICAST_DELEGATE_OneParam.
ValidateReplicatedClassInheritance()
template<class BaseClass, class DerivedClass> bool ValidateReplicatedClassInheritance () constexpr
Definition at line 215 of file UnrealNetwork.h.