Unreal Engine 5.6 C++ API: UBTDecorator_TagCooldown Class Reference
UBTDecorator_TagCooldown Class Reference
#include "BTDecorator_TagCooldown.h"
Protected Member Functions
virtual AIMODULE_API void OnNodeDeactivation (FBehaviorTreeSearchData &SearchData, EBTNodeResult::Type NodeResult) override
virtual AIMODULE_API void TickNode (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, float DeltaSeconds) override
Private Member Functions
virtual AIMODULE_API bool CalculateRawConditionValue (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) const override
virtual AIMODULE_API void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () UPROPERTY() FGameplayTag CooldownTag
Gameplay tag that will be used for the cooldown.
virtual AIMODULE_API uint16 GetInstanceMemorySize () const override
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
bool HasCooldownFinished (const UBehaviorTreeComponent &OwnerComp) const
virtual AIMODULE_API void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
virtual AIMODULE_API void PostLoad () override
UPROPERTY ()) FValueOrBBKey_Bool bActivatesCooldown
Whether or not we are adding/setting to the cooldown tag's value when the decorator deactivates.
UPROPERTY ()) FValueOrBBKey_Bool bAddToExistingDuration
True if we are adding to any existing duration, false if we are setting the duration (potentially invalidating an existing end time).
UPROPERTY ()) FValueOrBBKey_Float CooldownDuration
Value we will add or set to the Cooldown tag when this node is deactivated.
Detailed Description
Definition at line 22 of file BTDecorator_TagCooldown.h.
Member Function Documentation
CalculateRawConditionValue()
virtual AIMODULE_API bool UBTDecorator_TagCooldown::CalculateRawConditionValue (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) const override private virtual
References CalculateRawConditionValue().
Referenced by CalculateRawConditionValue().
CleanupMemory()
virtual AIMODULE_API void UBTDecorator_TagCooldown::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override private virtual
References CleanupMemory().
Referenced by CleanupMemory().
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_TagCooldown::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues().
Referenced by DescribeRuntimeValues().
GENERATED_UCLASS_BODY()
UBTDecorator_TagCooldown::GENERATED_UCLASS_BODY () private
Gameplay tag that will be used for the cooldown.
References Category, and UPROPERTY().
GetInstanceMemorySize()
virtual AIMODULE_API uint16 UBTDecorator_TagCooldown::GetInstanceMemorySize () const override private virtual
References GetInstanceMemorySize().
Referenced by GetInstanceMemorySize().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_TagCooldown::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_TagCooldown::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
HasCooldownFinished()
bool UBTDecorator_TagCooldown::HasCooldownFinished (const UBehaviorTreeComponent & OwnerComp) const private
InitializeMemory()
virtual AIMODULE_API void UBTDecorator_TagCooldown::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override private virtual
References InitializeMemory().
Referenced by InitializeMemory().
OnNodeDeactivation()
virtual AIMODULE_API void UBTDecorator_TagCooldown::OnNodeDeactivation (FBehaviorTreeSearchData & SearchData, EBTNodeResult::Type NodeResult) override protected virtual
PostLoad()
virtual AIMODULE_API void UBTDecorator_TagCooldown::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
TickNode()
virtual AIMODULE_API void UBTDecorator_TagCooldown::TickNode (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, float DeltaSeconds) override protected virtual
UPROPERTY() [1/3]
UBTDecorator_TagCooldown::UPROPERTY () private
Whether or not we are adding/setting to the cooldown tag's value when the decorator deactivates.
References Category, meta, and UPROPERTY().
UPROPERTY() [2/3]
UBTDecorator_TagCooldown::UPROPERTY () private
True if we are adding to any existing duration, false if we are setting the duration (potentially invalidating an existing end time).
References Category, meta, and UPROPERTY().
UPROPERTY() [3/3]
UBTDecorator_TagCooldown::UPROPERTY () private
Value we will add or set to the Cooldown tag when this node is deactivated.
References Category, meta, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
BTDecorator_TagCooldown.h