Unreal Engine 5.6 C++ API: FMeshSculptBrushOp Class Reference
FMeshSculptBrushOp Class Reference abstract
#include "MeshBrushOpBase.h"
Public Types
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Public Member Functions
virtual ~FMeshSculptBrushOp ()
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewValuesOut)=0
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual bool GetAlignStampToView () const
virtual EBrushRegionType GetBrushRegionType () const
virtual ESculptBrushOpTargetType GetBrushTargetType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool IgnoreZeroMovements () const
virtual bool SupportsVariableSpacing () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool UsesAlpha () const
virtual bool WantsStampRegionPlane () const
Data Fields
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Detailed Description
Definition at line 110 of file MeshBrushOpBase.h.
Member Enumeration Documentation
EBrushRegionType
enum class FMeshSculptBrushOp::EBrushRegionType strong
Enumerator
LocalSphere
InfiniteCylinder
CylinderOnSphere
Definition at line 114 of file MeshBrushOpBase.h.
EReferencePlaneType
enum class FMeshSculptBrushOp::EReferencePlaneType strong
Enumerator
None
InitialROI
InitialROI_ViewAligned
WorkPlane
Definition at line 141 of file MeshBrushOpBase.h.
EStampAlignmentType
enum class FMeshSculptBrushOp::EStampAlignmentType strong
Enumerator
HitNormal
Camera
ReferencePlane
ReferenceSphere
Definition at line 127 of file MeshBrushOpBase.h.
Constructor & Destructor Documentation
~FMeshSculptBrushOp()
virtual FMeshSculptBrushOp::~FMeshSculptBrushOp () inline virtual
Definition at line 155 of file MeshBrushOpBase.h.
Member Function Documentation
ApplyStamp()
virtual void FMeshSculptBrushOp::ApplyStamp (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewValuesOut) pure virtual
Implemented in FEraseSculptLayerBrushOp, FEraseToBaseMeshBrushOp, FFlattenBrushOp, FInflateBrushOp, FMeshTriangleGroupEditBrushOp, FMoveBrushOp, FPinchBrushOp, FPlaneBrushOp, FSmoothBrushOp, FSmoothFillBrushOp, FSurfaceMaxSculptBrushOp, FSurfaceSculptBrushOp, and FViewAlignedSculptBrushOp.
References Mesh.
BeginStroke()
virtual void FMeshSculptBrushOp::BeginStroke (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & InitialVertices) inline virtual
Reimplemented in FPinchBrushOp, and FPlaneBrushOp.
Definition at line 188 of file MeshBrushOpBase.h.
References Mesh.
CancelStroke()
virtual void FMeshSculptBrushOp::CancelStroke () inline virtual
Definition at line 190 of file MeshBrushOpBase.h.
ConfigureOptions()
virtual void FMeshSculptBrushOp::ConfigureOptions (const FSculptBrushOptions & Options) inline virtual
Definition at line 183 of file MeshBrushOpBase.h.
References CurrentOptions.
EndStroke()
virtual void FMeshSculptBrushOp::EndStroke (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & FinalVertices) inline virtual
Definition at line 189 of file MeshBrushOpBase.h.
References Mesh.
GetAlignStampToView()
virtual bool FMeshSculptBrushOp::GetAlignStampToView () const inline virtual
Reimplemented in FViewAlignedSculptBrushOp.
Definition at line 221 of file MeshBrushOpBase.h.
Referenced by GetStampAlignmentType().
GetBrushRegionType()
virtual EBrushRegionType FMeshSculptBrushOp::GetBrushRegionType () const inline virtual
Definition at line 205 of file MeshBrushOpBase.h.
References LocalSphere.
GetBrushTargetType()
virtual ESculptBrushOpTargetType FMeshSculptBrushOp::GetBrushTargetType () const inline virtual
Reimplemented in FBiLaplacianPullKelvinletBrushOp, FEraseSculptLayerBrushOp, FEraseToBaseMeshBrushOp, FInflateBrushOp, FLaplacianPullKelvinletBrushOp, FMoveBrushOp, FPinchBrushOp, FPullKelvinletBrushOp, FSharpPullKelvinletBrushOp, FSurfaceMaxSculptBrushOp, FSurfaceSculptBrushOp, FTwistKelvinletBrushOp, and FViewAlignedSculptBrushOp.
Definition at line 199 of file MeshBrushOpBase.h.
References SculptMesh.
GetFalloff()
const FMeshSculptFallofFunc & FMeshSculptBrushOp::GetFalloff () const inline
Definition at line 181 of file MeshBrushOpBase.h.
References Falloff.
Referenced by FBaseKelvinletBrushOp::ApplyFalloff(), FEraseSculptLayerBrushOp::ApplyStamp(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), and UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors().
GetPropertySetAs() [1/2]
template<typename PropType> PropType * FMeshSculptBrushOp::GetPropertySetAs () inline
Definition at line 160 of file MeshBrushOpBase.h.
References Cast(), ensure, and PropertySet.
Referenced by FFlattenBrushOp::ApplyStamp(), FMoveBrushOp::ApplyStamp(), FPinchBrushOp::ApplyStamp(), FPlaneBrushOp::ApplyStamp(), FScaleKelvinletBrushOp::ApplyStamp(), FSmoothBrushOp::ApplyStamp(), FSmoothFillBrushOp::ApplyStamp(), FSurfaceMaxSculptBrushOp::ApplyStamp(), FTwistKelvinletBrushOp::ApplyStamp(), FGroupEraseBrushOp::ApplyStampByTriangles(), FGroupPaintBrushOp::ApplyStampByTriangles(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), and FBaseKelvinletBrushOp::SetBaseProperties().
GetPropertySetAs() [2/2]
template<typename PropType> const PropType * FMeshSculptBrushOp::GetPropertySetAs () const inline
Definition at line 169 of file MeshBrushOpBase.h.
References Cast(), ensure, and PropertySet.
GetReferencePlaneType()
virtual EReferencePlaneType FMeshSculptBrushOp::GetReferencePlaneType () const inline virtual
Reimplemented in FPlaneBrushOp.
Definition at line 243 of file MeshBrushOpBase.h.
References None.
GetStampAlignmentType()
virtual EStampAlignmentType FMeshSculptBrushOp::GetStampAlignmentType () const inline virtual
Definition at line 211 of file MeshBrushOpBase.h.
References Camera, GetAlignStampToView(), and HitNormal.
IgnoreZeroMovements()
virtual bool FMeshSculptBrushOp::IgnoreZeroMovements () const inline virtual
Reimplemented in FBiLaplacianPullKelvinletBrushOp, FEraseSculptLayerBrushOp, FLaplacianPullKelvinletBrushOp, FMoveBrushOp, FPullKelvinletBrushOp, and FSharpPullKelvinletBrushOp.
Definition at line 226 of file MeshBrushOpBase.h.
SupportsVariableSpacing()
virtual bool FMeshSculptBrushOp::SupportsVariableSpacing () const inline virtual
Reimplemented in FSurfaceMaxSculptBrushOp, FSurfaceSculptBrushOp, and FViewAlignedSculptBrushOp.
Definition at line 260 of file MeshBrushOpBase.h.
UseLastStampFrameOnZeroMovement()
virtual bool FMeshSculptBrushOp::UseLastStampFrameOnZeroMovement () const inline virtual
Definition at line 236 of file MeshBrushOpBase.h.
UsesAlpha()
virtual bool FMeshSculptBrushOp::UsesAlpha () const inline virtual
Reimplemented in FSurfaceMaxSculptBrushOp, FSurfaceSculptBrushOp, and FViewAlignedSculptBrushOp.
Definition at line 255 of file MeshBrushOpBase.h.
WantsStampRegionPlane()
virtual bool FMeshSculptBrushOp::WantsStampRegionPlane () const inline virtual
Reimplemented in FFlattenBrushOp.
Definition at line 250 of file MeshBrushOpBase.h.
Field Documentation
CurrentOptions
FSculptBrushOptions FMeshSculptBrushOp::CurrentOptions
Definition at line 179 of file MeshBrushOpBase.h.
Referenced by FPlaneBrushOp::BeginStroke(), and ConfigureOptions().
Falloff
TSharedPtr<FMeshSculptFallofFunc> FMeshSculptBrushOp::Falloff
Definition at line 178 of file MeshBrushOpBase.h.
Referenced by FBaseKelvinletBrushOp::ApplyFalloff(), FEraseSculptLayerBrushOp::ApplyStamp(), FSmoothBrushOp::ApplyStamp(), FSmoothFillBrushOp::ApplyStamp(), and GetFalloff().
PropertySet
TWeakObjectPtr<UMeshSculptBrushOpProps> FMeshSculptBrushOp::PropertySet
Definition at line 157 of file MeshBrushOpBase.h.
Referenced by GetPropertySetAs(), GetPropertySetAs(), and FPlaneBrushOp::GetReferencePlaneType().
The documentation for this class was generated from the following file:
MeshBrushOpBase.h