Unreal Engine 5.6 C++ API: FSavePackageArgs Struct Reference
FSavePackageArgs Struct Reference
Struct to encapsulate UPackage::Save arguments.
#include "SavePackage.h"
Public Member Functions
FSavePackageArgs ()=default
FSavePackageArgs (const FSavePackageArgs &)=default
FSavePackageArgs (FSavePackageArgs &&)=default
const ITargetPlatform * GetTargetPlatform () const
bool IsCooking () const
FSavePackageArgs & operator= (const FSavePackageArgs &)=default
FSavePackageArgs & operator= (FSavePackageArgs &&)=default
UE_DEPRECATED (5.6, "Use the default constructor and assign elements individually.") FSavePackageArgs(const ITargetPlatform *InTargetPlatform
Data Fields
FArchiveCookData * ArchiveCookData = nullptr
bool bForceByteSwapping = false
FArchiveCookData EObjectFlags uint32 bool bInForceByteSwapping
FArchiveCookData EObjectFlags uint32 bool bool bool bInSlowTask
FArchiveCookData EObjectFlags uint32 bool bool bInWarnOfLongFilename
bool bSlowTask = true
If true, the Save will send progress events that are displayed in the editor.
bool bWarnOfLongFilename = true
FOutputDevice * Error = GError
Receives error/warning messages sent by the Save, to log and respond to their severity level.
FDateTime FinalTimeStamp
FArchiveCookData * InArchiveCookData
FArchiveCookData EObjectFlags uint32 bool bool bool FDateTime FOutputDevice * InError
FArchiveCookData EObjectFlags uint32 bool bool bool FDateTime InFinalTimeStamp
TMap< UObject *, FObjectSaveOverride > * InOutSaveOverrides = nullptr
In/Out list of property overrides per object to apply to during save.
FArchiveCookData EObjectFlags uint32 InSaveFlags
FArchiveCookData EObjectFlags InTopLevelFlags
uint32 SaveFlags = SAVE_None
FSavePackageContext * SavePackageContext = nullptr
Structure to hold longer-lifetime parameters that apply to multiple saves.
EObjectFlags TopLevelFlags = RF_NoFlags
For all objects which are not referenced[either directly, or indirectly] through the InAsset provided to the Save call (See UPackage::Save), only objects that contain any of these flags will be saved.
Detailed Description
Struct to encapsulate UPackage::Save arguments.
These arguments are shared between packages when saving multiple packages concurrently.
Definition at line 62 of file SavePackage.h.
Constructor & Destructor Documentation
FSavePackageArgs() [1/3]
FSavePackageArgs::FSavePackageArgs () default
Referenced by FSavePackageArgs(), FSavePackageArgs(), operator=(), operator=(), and UE_DEPRECATED().
FSavePackageArgs() [2/3]
FSavePackageArgs::FSavePackageArgs (const FSavePackageArgs &) default
References FSavePackageArgs().
FSavePackageArgs() [3/3]
FSavePackageArgs::FSavePackageArgs (FSavePackageArgs &&) default
References FSavePackageArgs().
Member Function Documentation
GetTargetPlatform()
const ITargetPlatform * FSavePackageArgs::GetTargetPlatform () const inline
Definition at line 68 of file SavePackage.h.
References ArchiveCookData.
IsCooking()
bool FSavePackageArgs::IsCooking () const inline
Definition at line 67 of file SavePackage.h.
References ArchiveCookData.
operator=() [1/2]
FSavePackageArgs & FSavePackageArgs::operator= (const FSavePackageArgs &) default
References FSavePackageArgs().
operator=() [2/2]
FSavePackageArgs & FSavePackageArgs::operator= (FSavePackageArgs &&) default
References FSavePackageArgs().
UE_DEPRECATED()
FSavePackageArgs::UE_DEPRECATED (5. 6, "Use the default constructor and assign elements individually.") const
References FSavePackageArgs().
Field Documentation
ArchiveCookData
FArchiveCookData* FSavePackageArgs::ArchiveCookData = nullptr
Definition at line 65 of file SavePackage.h.
Referenced by GetTargetPlatform(), and IsCooking().
bForceByteSwapping
bool FSavePackageArgs::bForceByteSwapping = false
Definition at line 79 of file SavePackage.h.
bInForceByteSwapping
FArchiveCookData EObjectFlags uint32 bool FSavePackageArgs::bInForceByteSwapping
Definition at line 112 of file SavePackage.h.
bInSlowTask
FArchiveCookData EObjectFlags uint32 bool bool bool FSavePackageArgs::bInSlowTask
Definition at line 114 of file SavePackage.h.
bInWarnOfLongFilename
FArchiveCookData EObjectFlags uint32 bool bool FSavePackageArgs::bInWarnOfLongFilename
Definition at line 113 of file SavePackage.h.
bSlowTask
bool FSavePackageArgs::bSlowTask = true
If true, the Save will send progress events that are displayed in the editor.
Definition at line 83 of file SavePackage.h.
bWarnOfLongFilename
bool FSavePackageArgs::bWarnOfLongFilename = true
Definition at line 81 of file SavePackage.h.
Error
FOutputDevice* FSavePackageArgs::Error = GError
Receives error/warning messages sent by the Save, to log and respond to their severity level.
Definition at line 90 of file SavePackage.h.
FinalTimeStamp
FDateTime FSavePackageArgs::FinalTimeStamp
Definition at line 88 of file SavePackage.h.
InArchiveCookData
FArchiveCookData* FSavePackageArgs::InArchiveCookData
Definition at line 109 of file SavePackage.h.
InError
FArchiveCookData EObjectFlags uint32 bool bool bool FDateTime FOutputDevice* FSavePackageArgs::InError
Definition at line 116 of file SavePackage.h.
InFinalTimeStamp
FArchiveCookData EObjectFlags uint32 bool bool bool FDateTime FSavePackageArgs::InFinalTimeStamp
Definition at line 115 of file SavePackage.h.
InOutSaveOverrides
TMap<UObject*, FObjectSaveOverride>* FSavePackageArgs::InOutSaveOverrides = nullptr
In/Out list of property overrides per object to apply to during save.
This list can be extended by PreSave functions during the save.
Definition at line 98 of file SavePackage.h.
InSaveFlags
FArchiveCookData EObjectFlags uint32 FSavePackageArgs::InSaveFlags
Definition at line 111 of file SavePackage.h.
InTopLevelFlags
FArchiveCookData EObjectFlags FSavePackageArgs::InTopLevelFlags
Definition at line 110 of file SavePackage.h.
SaveFlags
uint32 FSavePackageArgs::SaveFlags = SAVE_None
Definition at line 77 of file SavePackage.h.
SavePackageContext
FSavePackageContext* FSavePackageArgs::SavePackageContext = nullptr
Structure to hold longer-lifetime parameters that apply to multiple saves.
Definition at line 92 of file SavePackage.h.
TopLevelFlags
EObjectFlags FSavePackageArgs::TopLevelFlags = RF_NoFlags
For all objects which are not referenced[either directly, or indirectly] through the InAsset provided to the Save call (See UPackage::Save), only objects that contain any of these flags will be saved.
If RF_NoFlags is specified, only objects which are referenced by InAsset will be saved into the package.
Definition at line 75 of file SavePackage.h.
The documentation for this struct was generated from the following file:
SavePackage.h