Unreal Engine 5.6 C++ API: UE::FPlatformIoDispatcherBase Class Reference
UE::FPlatformIoDispatcherBase Class Reference abstract
This is a base class for platform specific I/O dispatcher implementations.
#include "PlatformIoDispatcherBase.h"
Public Member Functions
virtual ~FPlatformIoDispatcherBase ()
virtual void CancelAllRequests (FIoFileHandle FileHandle) override
Cancel all inflight I/O request for the specified file.
virtual void CancelRequest (FIoFileReadRequest Request) override
Cancel inflight I/O request.
virtual void DeleteRequest (FIoFileReadRequest Request) override
Delete the request.
virtual bool Init () override final
Initializes the runnable object.
virtual FIoStatus Initialize () override final
Initialize the dispatcher.
virtual FIoFileReadRequest ReadDirect (FIoDirectReadRequestParams &&Params, FIoFileReadRequestCompleted &&OnCompleted) override
Issue a direct read request.
virtual uint32 Run () override final
Runs the runnable object.
virtual FIoFileReadRequest ScatterGather (FIoScatterGatherRequestParams &&Params, FIoFileReadRequestCompleted &&OnCompleted) override
Issue a scatter-gather request.
virtual void Stop () override final
Stops the runnable object.
virtual bool Tick () override
Tick the dispatcher.
virtual void UpdatePriority (FIoFileReadRequest Request, EIoFileReadPriority NewPriority) override
Update priority for an inflight I/O request.
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual class FSingleThreadRunnable * GetSingleThreadInterface ()
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
Public Member Functions inherited from UE::IPlatformIoDispatcher
virtual ~IPlatformIoDispatcher ()=default
virtual FIoStatus CloseFile (FIoFileHandle FileHandle)=0
Close the file.
virtual TIoStatusOr< FIoFileHandle > OpenFile (const TCHAR *Filename, const FIoFileProperties &FileProperties, FIoFileStat *OutStat=nullptr)=0
Open file for reading.
Protected Member Functions
FPlatformIoDispatcherBase (FPlatformIoDispatcherCreateParams &&Params)
void CompleteEncodedBlockRequest (FIoEncodedBlockRequest &EncodedBlockRequest)
void EnqueueBlocksToDecode (FIoEncodedBlockRequestList BlocksToDecode)
void EnqueueBlockToDecode (FIoEncodedBlockRequest &EncodedBlockRequest)
uint32 GetNextFileId ()
virtual FIoPlatformFileInfo GetPlatformFileInfo (FIoFileHandle FileHandle)=0
virtual FIoStatus OnInitialize ()
virtual uint32 OnIoThreadEntry ()=0
virtual void OnWakeUp ()=0
void ProcessCompletedFileBlock (FIoFileBlockRequest &FileBlockRequest)
void ProcessDecodedBlock (FIoEncodedBlockRequest &EncodedBlockRequest, FIoChunkBlockDecodeResult &&DecodeResult, FIoChunkBlockDecodeRequest &NextDecodeRequest)
void ScatterDecodedBlock (FIoEncodedBlockRequest &EncodedBlockRequest)
Protected Attributes
FIoEncodedBlockRequestList BlocksReadyForDecoding
bool bMultithreaded = false
std::atomic_bool bStopRequested {false}
FIoChunkBlockMemoryPool ChunkBlockMemoryPool
FIoFileBlockCache FileBlockCache
FIoFileBlockMemoryPool FileBlockMemoryPool
UE::FMutex FileBlockMutex
FIoFileBlockRequestQueue FileBlockRequestQueue
uint32 FileBlockSize = 256 << 10
FPlatformIoDispatcherRequestMgr RequestMgr
UE::FMutex ScatterMutex
FPlatformIoDispatcherStats Stats
TUniquePtr< FRunnableThread > Thread
Private Attributes
std::atomic_uint32_t NextFileId {1}
Detailed Description
This is a base class for platform specific I/O dispatcher implementations.
There are two kinds of I/O requests when reading data from disk. Direct-read requests for platforms with hardware decompression and scatter-gather requests. Scatter-gather requests are issued by specifying information about how the blocks on disk are encoded, i.e. compressed, encrypted and or signed and forms a set of encoded block request. Encoded block requests can be shared between user requests, i.e. if two user requests are reading the same encoded block, the block is decoded once and then scattered to the destination/targets buffers. The encoded block requests are devided into a set of larger file block requests. The size of the file blocks are configured with GIoDispatcherBufferSizeKB (default=256KiB). The maximum number of concurrent file block requests are constrained by the available memory in the file block memory pool configured with GIoDispatcherBufferMemoryMB (default=8MiB).
Definition at line 471 of file PlatformIoDispatcherBase.h.
Constructor & Destructor Documentation
~FPlatformIoDispatcherBase()
UE::FPlatformIoDispatcherBase::~FPlatformIoDispatcherBase () virtual
Definition at line 827 of file PlatformIoDispatcherBase.cpp.
References bStopRequested, check, and Thread.
FPlatformIoDispatcherBase()
UE::FPlatformIoDispatcherBase::FPlatformIoDispatcherBase (FPlatformIoDispatcherCreateParams && Params) protected
Definition at line 819 of file PlatformIoDispatcherBase.cpp.
References bMultithreaded, FileBlockCache, FileBlockMemoryPool, FileBlockRequestQueue, Params, and Stats.
Referenced by UE::FGenericPlatformIoDispatcher::FGenericPlatformIoDispatcher().
Member Function Documentation
CancelAllRequests()
void UE::FPlatformIoDispatcherBase::CancelAllRequests (FIoFileHandle FileHandle) override virtual
Cancel all inflight I/O request for the specified file.
Implements UE::IPlatformIoDispatcher.
Definition at line 1024 of file PlatformIoDispatcherBase.cpp.
References FileBlockMutex, FileBlockRequestQueue, UE::FIoFileHandle::IsValid(), RequestMgr, TEXT, UE_LOG, and Warning.
CancelRequest()
void UE::FPlatformIoDispatcherBase::CancelRequest (FIoFileReadRequest Request) override virtual
Cancel inflight I/O request.
Implements UE::IPlatformIoDispatcher.
Definition at line 978 of file PlatformIoDispatcherBase.cpp.
References Cancelled, UE::FIoPlatformReadRequest::ErrorCode, FileBlockMutex, FileBlockRequestQueue, UE::FIoFileReadRequest::IsValid(), MoveTemp(), Ok, UE::FIoPlatformReadRequest::OnCompleted, UE::FIoPlatformReadRequest::FScatterGather::RemainingBlocks, RequestMgr, UE::FIoPlatformReadRequest::ScatterGather, TEXT, UE_LOG, UE::FIoPlatformReadRequest::UserData, UE::FIoFileReadRequest::Value(), and Warning.
CompleteEncodedBlockRequest()
void UE::FPlatformIoDispatcherBase::CompleteEncodedBlockRequest (FIoEncodedBlockRequest & EncodedBlockRequest) protected
Definition at line 1409 of file PlatformIoDispatcherBase.cpp.
References TIntrusiveList< TypeTraits >::AddTail(), check, UE::FIoPlatformReadRequest::ErrorCode, UE::FIoPlatformReadRequest::FailedBlockId, UE::FIoPlatformReadRequest::IsScatterGather(), MoveTemp(), UE::FIoPlatformReadRequest::OnCompleted, TIntrusiveList< TypeTraits >::PopHead(), UE::FIoPlatformReadRequest::FScatterGather::RemainingBlocks, UE::FIoEncodedBlockRequest::FScatterTarget::Request, RequestMgr, UE::FIoPlatformReadRequest::ScatterGather, UE::FIoEncodedBlockRequest::ScatterTargets, Unknown, and UE::FIoPlatformReadRequest::UserData.
Referenced by EnqueueBlocksToDecode(), ProcessCompletedFileBlock(), and ProcessDecodedBlock().
DeleteRequest()
void UE::FPlatformIoDispatcherBase::DeleteRequest (FIoFileReadRequest Request) override virtual
Delete the request.
Must be called after the completion callback has been triggered.
Implements UE::IPlatformIoDispatcher.
Definition at line 1074 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileReadRequest::IsValid(), RequestMgr, and UE::FIoFileReadRequest::Value().
EnqueueBlocksToDecode()
void UE::FPlatformIoDispatcherBase::EnqueueBlocksToDecode (FIoEncodedBlockRequestList BlocksToDecode) protected
Definition at line 1202 of file PlatformIoDispatcherBase.cpp.
References TIntrusiveList< TypeTraits >::AddTail(), BlocksReadyForDecoding, bMultithreaded, check, ChunkBlockMemoryPool, CompleteEncodedBlockRequest(), FIoChunkEncoding::DecodeBlock(), EnqueueBlockToDecode(), FileBlockMemoryPool, FileBlockMutex, TIntrusiveList< TypeTraits >::PopHead(), ScatterDecodedBlock(), Stats, and Unknown.
Referenced by ProcessCompletedFileBlock().
EnqueueBlockToDecode()
void UE::FPlatformIoDispatcherBase::EnqueueBlockToDecode (FIoEncodedBlockRequest & EncodedBlockRequest) protected
Definition at line 1269 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockCompressedSize, UE::FIoEncodedBlockRequest::BlockHash, UE::FIoEncodedBlockRequest::BlockUncompressedSize, UE::FIoEncodedBlockRequest::BufferHandle, check, UE::FIoEncodedBlockRequest::CompressionMethod, UE::FIoEncodedBlockRequest::DecodedData, UE::FIoEncodedBlockRequest::EncodedData, UE::FIoEncodedBlockRequest::EncryptionKey, IIoChunkBlockDecoder::Enqueue(), UE::FIoEncodedBlockRequest::ErrorCode, FIoChunkBlockDecoder::Get(), UE::FIoBufferHandle::IsValid(), MoveTemp(), ProcessDecodedBlock(), and Unknown.
Referenced by EnqueueBlocksToDecode().
GetNextFileId()
uint32 UE::FPlatformIoDispatcherBase::GetNextFileId () protected
Definition at line 1089 of file PlatformIoDispatcherBase.cpp.
References NextFileId.
Referenced by UE::FGenericPlatformIoDispatcher::OpenFile().
GetPlatformFileInfo()
virtual FIoPlatformFileInfo UE::FPlatformIoDispatcherBase::GetPlatformFileInfo (FIoFileHandle FileHandle) protected pure virtual
Implemented in UE::FGenericPlatformIoDispatcher.
Referenced by ScatterGather().
Init()
bool UE::FPlatformIoDispatcherBase::Init () final override virtual
Initializes the runnable object.
This method is called in the context of the thread object that aggregates this, not the thread that passes this runnable to a new thread.
Returns
True if initialization was successful, false otherwise
See also
Run, Stop, Exit
Reimplemented from FRunnable.
Definition at line 833 of file PlatformIoDispatcherBase.cpp.
Initialize()
FIoStatus UE::FPlatformIoDispatcherBase::Initialize () final override virtual
Initialize the dispatcher.
Called after the config system has been initialized.
Implements UE::IPlatformIoDispatcher.
Definition at line 848 of file PlatformIoDispatcherBase.cpp.
References bMultithreaded, FRunnableThread::Create(), FIoStatus::IsOk(), OnInitialize(), TEXT, Thread, and TPri_AboveNormal.
OnInitialize()
FIoStatus UE::FPlatformIoDispatcherBase::OnInitialize () protected virtual
Reimplemented in UE::FGenericPlatformIoDispatcher.
Definition at line 1084 of file PlatformIoDispatcherBase.cpp.
References FIoStatus::Ok.
Referenced by Initialize().
OnIoThreadEntry()
virtual uint32 UE::FPlatformIoDispatcherBase::OnIoThreadEntry () protected pure virtual
Implemented in UE::FGenericPlatformIoDispatcher.
Referenced by Run().
OnWakeUp()
virtual void UE::FPlatformIoDispatcherBase::OnWakeUp () protected pure virtual
Implemented in UE::FGenericPlatformIoDispatcher.
Referenced by ProcessDecodedBlock(), and ScatterGather().
ProcessCompletedFileBlock()
void UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock (FIoFileBlockRequest & FileBlockRequest) protected
Definition at line 1099 of file PlatformIoDispatcherBase.cpp.
References TIntrusiveList< TypeTraits >::AddTail(), FAES::AESBlockSize, Align, UE::FIoFileBlockRequest::Buffer, UE::FIoFileBlockRequest::BufferHandle, Cancelled, check, CompleteEncodedBlockRequest(), TMemoryView< DataType >::CopyFrom(), UE::FIoFileBlockRequest::EncodedBlockRequests, EnqueueBlocksToDecode(), UE::FIoEncodedBlockRequest::ErrorCode, UE::FIoFileBlockRequest::ErrorCode, UE::FIoPlatformReadRequest::ErrorCode, FileBlockMemoryPool, FileBlockMutex, UE::FIoFileBlockRequest::FileOffset, TMemoryView< DataType >::GetData(), TMemoryView< DataType >::GetSize(), TIntrusiveList< TypeTraits >::IsEmpty(), UE::IsIoErrorAnyOf(), TMemoryView< DataType >::LeftInline(), TMemoryView< DataType >::Mid(), TMemoryView< DataType >::MidInline(), MoveTemp(), Ok, TIntrusiveList< TypeTraits >::PopHead(), ProcessCompletedFileBlock(), ReadError, UE::FIoEncodedBlockRequest::FScatterTarget::Request, RequestMgr, TMemoryView< DataType >::RightChopInline(), UE::FIoFileBlockRequest::Size, Stats, TRACE_CPUPROFILER_EVENT_SCOPE, and Unknown.
Referenced by ProcessCompletedFileBlock(), and UE::FGenericPlatformIoDispatcher::ProcessFileIo().
ProcessDecodedBlock()
void UE::FPlatformIoDispatcherBase::ProcessDecodedBlock (FIoEncodedBlockRequest & EncodedBlockRequest, FIoChunkBlockDecodeResult && DecodeResult, FIoChunkBlockDecodeRequest & NextDecodeRequest) protected
Definition at line 1295 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockCompressedSize, UE::FIoEncodedBlockRequest::BlockHash, BlocksReadyForDecoding, UE::FIoEncodedBlockRequest::BlockUncompressedSize, UE::FIoEncodedBlockRequest::BufferHandle, check, ChunkBlockMemoryPool, CompleteEncodedBlockRequest(), CompressionError, UE::FIoEncodedBlockRequest::CompressionMethod, UE::FIoEncodedBlockRequest::DecodedData, UE::FIoEncodedBlockRequest::EncodedData, UE::FIoEncodedBlockRequest::EncryptionKey, UE::FIoEncodedBlockRequest::ErrorCode, FileBlockMemoryPool, FileBlockMutex, UE::FIoEncodedBlockRequest::FileBufferHandle, MoveTemp(), Ok, OnWakeUp(), ProcessDecodedBlock(), ScatterDecodedBlock(), SignatureError, Stats, and Unknown.
Referenced by EnqueueBlockToDecode(), and ProcessDecodedBlock().
ReadDirect()
FIoFileReadRequest UE::FPlatformIoDispatcherBase::ReadDirect (FIoDirectReadRequestParams && Params, FIoFileReadRequestCompleted && OnCompleted) override virtual
Issue a direct read request.
Returns an invalid file handle if direct read is not supported for the specifid file.
Implements UE::IPlatformIoDispatcher.
Definition at line 973 of file PlatformIoDispatcherBase.cpp.
References Params.
Run()
uint32 UE::FPlatformIoDispatcherBase::Run () final override virtual
Runs the runnable object.
This is where all per object thread work is done. This is only called if the initialization was successful.
Returns
The exit code of the runnable object
See also
Init, Stop, Exit
Implements FRunnable.
Definition at line 838 of file PlatformIoDispatcherBase.cpp.
References OnIoThreadEntry().
ScatterDecodedBlock()
void UE::FPlatformIoDispatcherBase::ScatterDecodedBlock (FIoEncodedBlockRequest & EncodedBlockRequest) protected
Definition at line 1352 of file PlatformIoDispatcherBase.cpp.
References UE::FIoEncodedBlockRequest::BlockKey, UE::FIoEncodedBlockRequest::BlockUncompressedSize, check, TMemoryView< DataType >::CopyFrom(), UE::FIoEncodedBlockRequest::DecodedData, UE::FIoPlatformReadRequest::Dst, UE::FIoPlatformReadRequest::DstSize, UE::FIoEncodedBlockRequest::ErrorCode, UE::FIoPlatformReadRequest::ErrorCode, UE::FIoPlatformReadRequest::FailedBlockId, UE::FIoBlockKey::GetBlockId(), FIoBuffer::GetMutableView(), FIoBuffer::GetSize(), UE::FIoPlatformReadRequest::IsScatterGather(), LLM_SCOPE_BYNAME, TMemoryView< DataType >::Mid(), UE::FIoEncodedBlockRequest::FScatterTarget::OffsetInBlock, UE::FIoEncodedBlockRequest::FScatterTarget::OffsetInDst, Ok, UE::FIoPlatformReadRequest::FScatterGather::RemainingBlocks, UE::FIoEncodedBlockRequest::FScatterTarget::Request, UE::FInheritedContextBase::RestoreInheritedContext(), TMemoryView< DataType >::RightChop(), UE::FIoPlatformReadRequest::ScatterGather, ScatterMutex, UE::FIoEncodedBlockRequest::ScatterTargets, UE::FIoEncodedBlockRequest::FScatterTarget::SizeInBlock, Stats, TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, and Unknown.
Referenced by EnqueueBlocksToDecode(), and ProcessDecodedBlock().
ScatterGather()
FIoFileReadRequest UE::FPlatformIoDispatcherBase::ScatterGather (FIoScatterGatherRequestParams && Params, FIoFileReadRequestCompleted && OnCompleted) override virtual
Issue a scatter-gather request.
Implements UE::IPlatformIoDispatcher.
Definition at line 859 of file PlatformIoDispatcherBase.cpp.
References TArray< InElementType, InAllocatorType >::Add(), TIntrusiveList< TypeTraits >::AddTail(), FAES::AESBlockSize, Align, UE::FIoEncodedBlockRequest::BlockCompressedSize, UE::FIoScatterGatherRequestParams::FScatterParams::BlockCompressedSize, UE::FIoScatterGatherRequestParams::FScatterParams::BlockFileOffset, UE::FIoEncodedBlockRequest::BlockHash, UE::FIoScatterGatherRequestParams::FScatterParams::BlockHash, UE::FIoScatterGatherRequestParams::FScatterParams::BlockIndex, UE::FIoScatterGatherRequestParams::FScatterParams::BlockUncompresedSize, UE::FIoEncodedBlockRequest::BlockUncompressedSize, check, UE::FIoEncodedBlockRequest::CompressionMethod, UE::FIoScatterGatherRequestParams::FScatterParams::CompressionMethod, UE::FIoScatterGatherRequestParams::FScatterParams::DestinationOffset, UE::FIoFileBlockRequest::EncodedBlockRequests, UE::FIoEncodedBlockRequest::EncryptionKey, UE::FIoScatterGatherRequestParams::FScatterParams::EncryptionKey, UE::FIoEncodedBlockRequest::FileBlockCount, FileBlockMutex, FileBlockRequestQueue, FileBlockSize, UE::FIoFileBlockRequest::FileHandle, UE::FIoPlatformFileInfo::FileId, UE::FIoEncodedBlockRequest::FileOffset, UE::FIoFileBlockRequest::FileOffset, UE::FIoFileBlockRequest::FileSize, UE::FIoPlatformFileInfo::FileSize, GetPlatformFileInfo(), IntCastChecked(), MAX_uint32, MAX_uint8, FMath::Min, MoveTemp(), OnWakeUp(), Params, UE::FIoFileBlockRequest::Priority, UE::FIoPlatformReadRequest::RefCount, UE::FIoPlatformReadRequest::FScatterGather::RemainingBlocks, UE::FIoEncodedBlockRequest::RemainingFileBlocks, RequestMgr, UE::FIoPlatformReadRequest::ScatterGather, UE::FIoScatterGatherRequestParams::FScatterParams::ScatterOffset, UE::FIoScatterGatherRequestParams::FScatterParams::ScatterSize, UE::FIoEncodedBlockRequest::ScatterTargets, and UE::FIoFileBlockRequest::Size.
Stop()
void UE::FPlatformIoDispatcherBase::Stop () final override virtual
Stops the runnable object.
This is called if a thread is requested to terminate early.
See also
Init, Run, Exit
Reimplemented from FRunnable.
Definition at line 843 of file PlatformIoDispatcherBase.cpp.
References bStopRequested.
Tick()
virtual bool UE::FPlatformIoDispatcherBase::Tick () inline override virtual
Tick the dispatcher.
Only used when multithreading is disabled.
Implements UE::IPlatformIoDispatcher.
Reimplemented in UE::FGenericPlatformIoDispatcher.
Definition at line 487 of file PlatformIoDispatcherBase.h.
References bMultithreaded, and ensure.
UpdatePriority()
void UE::FPlatformIoDispatcherBase::UpdatePriority (FIoFileReadRequest Request, EIoFileReadPriority NewPriority) override virtual
Update priority for an inflight I/O request.
Implements UE::IPlatformIoDispatcher.
Definition at line 1042 of file PlatformIoDispatcherBase.cpp.
References FileBlockMutex, FileBlockRequestQueue, UE::FIoFileReadRequest::IsValid(), RequestMgr, TEXT, UE_LOG, UE::FIoFileReadRequest::Value(), and Warning.
Field Documentation
BlocksReadyForDecoding
FIoEncodedBlockRequestList UE::FPlatformIoDispatcherBase::BlocksReadyForDecoding protected
Definition at line 515 of file PlatformIoDispatcherBase.h.
Referenced by EnqueueBlocksToDecode(), and ProcessDecodedBlock().
bMultithreaded
bool UE::FPlatformIoDispatcherBase::bMultithreaded = false protected
Definition at line 519 of file PlatformIoDispatcherBase.h.
Referenced by FPlatformIoDispatcherBase(), EnqueueBlocksToDecode(), Initialize(), and Tick().
bStopRequested
std::atomic_bool UE::FPlatformIoDispatcherBase::bStopRequested {false} protected
Definition at line 520 of file PlatformIoDispatcherBase.h.
Referenced by UE::FGenericPlatformIoDispatcher::~FGenericPlatformIoDispatcher(), ~FPlatformIoDispatcherBase(), UE::FGenericPlatformIoDispatcher::OnIoThreadEntry(), and Stop().
ChunkBlockMemoryPool
FIoChunkBlockMemoryPool UE::FPlatformIoDispatcherBase::ChunkBlockMemoryPool protected
Definition at line 511 of file PlatformIoDispatcherBase.h.
Referenced by EnqueueBlocksToDecode(), UE::FGenericPlatformIoDispatcher::OnInitialize(), and ProcessDecodedBlock().
FileBlockCache
FIoFileBlockCache UE::FPlatformIoDispatcherBase::FileBlockCache protected
Definition at line 514 of file PlatformIoDispatcherBase.h.
Referenced by FPlatformIoDispatcherBase(), UE::FGenericPlatformIoDispatcher::OnInitialize(), and UE::FGenericPlatformIoDispatcher::ProcessFileIo().
FileBlockMemoryPool
FIoFileBlockMemoryPool UE::FPlatformIoDispatcherBase::FileBlockMemoryPool protected
Definition at line 512 of file PlatformIoDispatcherBase.h.
Referenced by FPlatformIoDispatcherBase(), EnqueueBlocksToDecode(), UE::FGenericPlatformIoDispatcher::OnInitialize(), ProcessCompletedFileBlock(), ProcessDecodedBlock(), and UE::FGenericPlatformIoDispatcher::ProcessFileIo().
FileBlockMutex
UE::FMutex UE::FPlatformIoDispatcherBase::FileBlockMutex protected
Definition at line 516 of file PlatformIoDispatcherBase.h.
Referenced by CancelAllRequests(), CancelRequest(), EnqueueBlocksToDecode(), ProcessCompletedFileBlock(), ProcessDecodedBlock(), UE::FGenericPlatformIoDispatcher::ProcessFileIo(), ScatterGather(), and UpdatePriority().
FileBlockRequestQueue
FIoFileBlockRequestQueue UE::FPlatformIoDispatcherBase::FileBlockRequestQueue protected
Definition at line 513 of file PlatformIoDispatcherBase.h.
Referenced by FPlatformIoDispatcherBase(), CancelAllRequests(), CancelRequest(), UE::FGenericPlatformIoDispatcher::OnInitialize(), UE::FGenericPlatformIoDispatcher::ProcessFileIo(), ScatterGather(), and UpdatePriority().
FileBlockSize
uint32 UE::FPlatformIoDispatcherBase::FileBlockSize = 256 << 10 protected
Definition at line 518 of file PlatformIoDispatcherBase.h.
Referenced by UE::FGenericPlatformIoDispatcher::OnInitialize(), and ScatterGather().
NextFileId
std::atomic_uint32_t UE::FPlatformIoDispatcherBase::NextFileId {1} private
Definition at line 523 of file PlatformIoDispatcherBase.h.
Referenced by GetNextFileId().
RequestMgr
FPlatformIoDispatcherRequestMgr UE::FPlatformIoDispatcherBase::RequestMgr protected
Definition at line 510 of file PlatformIoDispatcherBase.h.
Referenced by CancelAllRequests(), CancelRequest(), CompleteEncodedBlockRequest(), DeleteRequest(), ProcessCompletedFileBlock(), ScatterGather(), and UpdatePriority().
ScatterMutex
UE::FMutex UE::FPlatformIoDispatcherBase::ScatterMutex protected
Definition at line 517 of file PlatformIoDispatcherBase.h.
Referenced by ScatterDecodedBlock().
Stats
FPlatformIoDispatcherStats UE::FPlatformIoDispatcherBase::Stats protected
Definition at line 508 of file PlatformIoDispatcherBase.h.
Referenced by FPlatformIoDispatcherBase(), EnqueueBlocksToDecode(), ProcessCompletedFileBlock(), ProcessDecodedBlock(), UE::FGenericPlatformIoDispatcher::ProcessFileIo(), and ScatterDecodedBlock().
Thread
TUniquePtr<FRunnableThread> UE::FPlatformIoDispatcherBase::Thread protected
Definition at line 509 of file PlatformIoDispatcherBase.h.
Referenced by UE::FGenericPlatformIoDispatcher::~FGenericPlatformIoDispatcher(), ~FPlatformIoDispatcherBase(), and Initialize().
The documentation for this class was generated from the following files:
PlatformIoDispatcherBase.h
PlatformIoDispatcherBase.cpp