Unreal Engine 5.6 C++ API: IPersonaPreviewScene Class Reference
IPersonaPreviewScene Class Reference abstract
#include "IPersonaPreviewScene.h"
Public Member Functions
IPersonaPreviewScene (ConstructionValues CVS)
Constructor only here to pass ConstructionValues to base constructor.
virtual bool AllowMeshHitProxies () const =0
Get whether or not to ignore mesh hit proxies.
virtual bool AttachObjectToPreviewComponent (UObject *Object, FName AttachTo)=0
Attaches an object to the preview component using the supplied attach name, returning whether it was successfully attached or not.
virtual bool BroadcastMeshClick (HActor *HitProxy, const FViewportClick &Click)=0
Broadcasts that the preview mesh was clicked.
virtual void BroadcastOnLODChanged ()=0
Broadcasts that we want to force an update, after preview mesh's LOD has changed.
virtual void BroadcastOnMorphTargetsChanged ()=0
Broadcasts that the preview mesh morph targets has changed.
virtual void BroadcastOnSelectedLODChanged ()=0
Broadcast select LOD changed.
virtual void ClearRemoveAttachedComponentFilter ()=0
virtual void ClearSelectedActor ()=0
Clears the selected actor.
virtual void ClearSelectedBone ()=0
Clears the selected bone on the preview component.
virtual void ClearSelectedSocket ()=0
Clears the selected socket on the preview component.
virtual void DeselectAll ()=0
Clears all selection on the preview component.
virtual void EnableWind (bool bEnableWind)=0
Enable wind.
virtual void FlagTickable ()=0
Let the preview scene know that it should tick (because it is visible)
virtual void FocusViews ()=0
Request our views to focus on the current item.
virtual void ForEachPreviewMesh (TFunction< void(UDebugSkelMeshComponent *)> PerMeshFunction)=0
Run a lambda function on each preview mesh in the scene.
virtual AActor * GetActor () const =0
Get the main actor.
virtual TArray< UDebugSkelMeshComponent * > GetAllPreviewMeshComponents () const =0
Get array of all skeletal mesh components in the preview scene.
virtual EAnimationPlaybackSpeeds::Type GetAnimationPlaybackSpeedMode () const =0
Retrieve the current animation playback speed mode.
virtual TSharedPtr< FEditorCameraController > GetCurrentCameraOverride () const =0
Get the current camera override.
virtual float GetCustomAnimationSpeed () const =0
Get the current custom animation playback speed.
virtual float GetGravityScale () const =0
Get the gravity scale.
virtual TSharedRef< class IPersonaToolkit > GetPersonaToolkit () const =0
Get the persona toolkit we are associated with.
virtual UAnimationAsset * GetPreviewAnimationAsset () const =0
Get the animation asset we are previewing.
virtual USkeletalMesh * GetPreviewMesh () const =0
Get the preview mesh for this scene (does go via skeleton/asset)
virtual UDebugSkelMeshComponent * GetPreviewMeshComponent () const =0
Get the skeletal mesh component we are using for preview, if any.
virtual AActor * GetSelectedActor () const =0
Get the currently selected actor.
virtual int32 GetSelectedBoneIndex () const =0
Get the currently selected bone index.
virtual FSelectedSocketInfo GetSelectedSocket () const =0
Get the currently selected socket.
virtual float GetWindStrength () const =0
Get the wind strength.
virtual void HandleSkeletonTreeSelectionChanged (const TArrayView< TSharedPtr< ISkeletonTreeItem > > &InSelectedItems, ESelectInfo::Type InSelectInfo)=0
Handle syncing selection with the skeleton tree.
virtual void InvalidateViews ()=0
Flag that we want our views to be updated.
virtual bool IsPlaybackSpeedSelected (int32 InPlaybackSpeedMode) const =0
Function to return whether the supplied playback speed is the current active one.
virtual bool IsShowReferencePoseEnabled () const =0
virtual bool IsWindEnabled () const =0
Check whether wind is enabled.
virtual void RefreshAdditionalMeshes (bool bAllowOverrideBaseMesh)=0
Refreshes the additional meshes displayed in this preview scene.
virtual void RegisterOnAnimChanged (const FOnAnimChanged &Delegate)=0
Registers a delegate to be called after the preview animation has been changed.
virtual void RegisterOnCameraOverrideChanged (const FSimpleDelegate &Delegate)=0
Register callback for when the camera override is changed.
virtual FDelegateHandle RegisterOnDeselectAll (const FSimpleDelegate &Delegate)=0
Registers a delegate to be called when all sockets/bones are deselected.
virtual void RegisterOnFocusViews (const FSimpleDelegate &Delegate)=0
Registers a delegate to be called when the view should be focused.
virtual void RegisterOnInvalidateViews (const FSimpleDelegate &Delegate)=0
Registers a delegate to be called when the view is invalidated.
virtual void RegisterOnLODChanged (const FSimpleDelegate &Delegate)=0
Registers a delegate to be called when the preview mesh's LOD has changed.
virtual void RegisterOnMeshClick (const FOnMeshClick &Delegate)=0
Registers a delegate to be called when the preview mesh is clicked.
virtual void RegisterOnMorphTargetsChanged (const FSimpleDelegate &Delegate)=0
Registers a delegate to be called when the preview mesh's morph targets has changed.
virtual void RegisterOnPostTick (const FSimpleDelegate &Delegate)=0
Register a callback for just after the preview scene is ticked.
virtual void RegisterOnPreTick (const FSimpleDelegate &Delegate)=0
Register a callback for just before the preview scene is ticked.
virtual void RegisterOnPreviewMeshChanged (const FOnPreviewMeshChanged &Delegate)=0
Registers a delegate to be called when the preview mesh is changed.
virtual FDelegateHandle RegisterOnSelectedBonesChanged (const FOnSelectedBonesChanged &InDelegate)=0
Registers a delegate called when the bones selection has changed.
virtual void RegisterOnSelectedLODChanged (const FOnSelectedLODChanged &Delegate)=0
Register callback to be able to be notify when the select LOD is change.
virtual FDelegateHandle RegisterOnSelectedSocketChanged (const FOnSelectedSocketChanged &Delegate)=0
Registers a delegate to be called when the currently selected socket has changed.
virtual void RemoveAttachedObjectFromPreviewComponent (UObject *Object, FName AttachedTo)=0
Removes a currently attached object from the preview component.
virtual void SetActor (AActor *InActor)=0
Set the main actor.
virtual void SetAdditionalMeshes (class UDataAsset *InAdditionalMeshes)=0
Set the additional meshes used by this preview scene (sets the additional meshes on the skeleton)
virtual void SetAdditionalMeshesSelectable (bool bSelectable)=0
Set whether additional meshes are selectable.
virtual void SetAllowMeshHitProxies (bool bState)=0
Set whether or not to ignore mesh hit proxies.
virtual void SetAnimationPlaybackSpeedMode (EAnimationPlaybackSpeeds::Type InMode)=0
Set the playback speed mode.
virtual void SetCameraOverride (TSharedPtr< FEditorCameraController > NewCamera)=0
Function to override the editor camera for this scene.
virtual void SetCustomAnimationSpeed (float InAnimationSpeed)=0
Set the current custom animation playback speed.
virtual void SetDefaultAnimationMode (EPreviewSceneDefaultAnimationMode Mode, bool bShowNow=true)=0
Set the default mode this preview scene appears in.
virtual void SetEditableSkeleton (TSharedPtr< IEditableSkeleton > InEditableSkeleton)=0
Replaces the current editable skeleton.
virtual void SetGravityScale (float InGravityScale)=0
Set the gravity scale.
virtual void SetPreviewAnimationAsset (UAnimationAsset *AnimAsset, bool bEnablePreview=true)=0
Set the animation asset to preview.
virtual void SetPreviewAnimationBlueprint (UAnimBlueprint *InAnimBlueprint, UAnimBlueprint *InOverlayOrSubAnimBlueprint)=0
Set the preview animation blueprint and an optional overlay (for sub-layers)
virtual void SetPreviewMesh (USkeletalMesh *NewPreviewMesh, bool bAllowOverrideBaseMesh=true)=0
Set the preview mesh for this scene (does not set the preview mesh on the skeleton/asset)
virtual void SetPreviewMeshComponent (UDebugSkelMeshComponent *InSkeletalMeshComponent)=0
Set the skeletal mesh component we are going to preview.
virtual void SetRemoveAttachedComponentFilter (const FOnRemoveAttachedComponentFilter &Delegate)=0
setter/getter for can remove attach component
virtual void SetSelectedActor (AActor *InActor)=0
Sets the selected actor.
virtual void SetSelectedBone (const FName &BoneName, ESelectInfo::Type InSelectInfo)=0
Sets the selected bone on the preview component.
virtual void SetSelectedBones (const TArray< FName > &InBoneNames, ESelectInfo::Type InSelectInfo)=0
Sets the selected bones on the preview component.
virtual void SetSelectedSocket (const FSelectedSocketInfo &SocketInfo)=0
Sets the selected socket on the preview component.
virtual void SetWindStrength (float InWindStrength)=0
Set the wind strength.
virtual void ShowDefaultMode ()=0
Show the mode specifed by SetDefaultAnimationMode()
virtual void ShowReferencePose (bool bShowRefPose, bool bResetBoneTransforms=false)=0
Show the reference pose of the displayed skeletal mesh.
virtual void TogglePlayback ()=0
Toggle the playback of animation, if any.
UE_DEPRECATED (4.26, "Please call/implement SetSelectedBone with ESelectInfo") virtual void SetSelectedBone(const FName &BoneName) final
Sets the selected bone on the preview component.
UE_DEPRECATED (5.6, "Use RegisterOnSelectedBonesChanged instead.") virtual FDelegateHandle RegisterOnSelectedBoneChanged(const FOnSelectedBoneChanged &Delegate)=0
Registers a delegate to be called when the currently selected bone has changed.
UE_DEPRECATED (5.6, "Use UnregisterOnSelectedBonesChanged instead.") virtual void UnregisterOnSelectedBoneChanged(FDelegateHandle InHandle)=0
Unregisters a delegate called when the currently selected bone has changed.
virtual void UnregisterForUndo ()=0
Unregister this scene from the Undo chain.
virtual void UnregisterOnAnimChanged (FDelegateUserObject Thing)=0
Unregisters a delegate to be called after the preview animation has been changed.
virtual void UnregisterOnCameraOverrideChanged (FDelegateUserObject Thing)=0
Unregister callback for when the camera override is changed.
virtual void UnregisterOnDeselectAll (FDelegateHandle InHandle)=0
unregisters a delegate called when all sockets/bones are deselected
virtual void UnregisterOnFocusViews (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the view should be focused.
virtual void UnregisterOnInvalidateViews (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the view is invalidated.
virtual void UnregisterOnLODChanged (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the preview mesh's LOD has changed.
virtual void UnregisterOnMeshClick (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the preview mesh is clicked.
virtual void UnregisterOnMorphTargetsChanged (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the preview mesh's morph targets has changed.
virtual void UnregisterOnPostTick (FDelegateUserObject Thing)=0
Unregister a callback for just after the preview scene is ticked.
virtual void UnregisterOnPreTick (FDelegateUserObject Thing)=0
Unregister a callback for just before the preview scene is ticked.
virtual void UnregisterOnPreviewMeshChanged (FDelegateUserObject Thing)=0
Unregisters a delegate to be called when the preview mesh is changed.
virtual void UnregisterOnSelectedBonesChanged (FDelegateHandle InHandle)=0
Unregisters a delegate called when the bones selection has changed.
virtual void UnRegisterOnSelectedLODChanged (FDelegateUserObject Thing)=0
Unregister callback to free up the ressources.
virtual void UnregisterOnSelectedSocketChanged (FDelegateHandle InHandle)=0
Unregisters a delegate called when the currently selected socket has changed.
Detailed Description
Definition at line 71 of file IPersonaPreviewScene.h.
Constructor & Destructor Documentation
IPersonaPreviewScene()
IPersonaPreviewScene::IPersonaPreviewScene (ConstructionValues CVS) inline
Constructor only here to pass ConstructionValues to base constructor.
Definition at line 75 of file IPersonaPreviewScene.h.
Member Function Documentation
AllowMeshHitProxies()
virtual bool IPersonaPreviewScene::AllowMeshHitProxies () const pure virtual
Get whether or not to ignore mesh hit proxies.
References AllowMeshHitProxies().
Referenced by AllowMeshHitProxies().
AttachObjectToPreviewComponent()
virtual bool IPersonaPreviewScene::AttachObjectToPreviewComponent (UObject * Object, FName AttachTo) pure virtual
Attaches an object to the preview component using the supplied attach name, returning whether it was successfully attached or not.
References Object.
BroadcastMeshClick()
virtual bool IPersonaPreviewScene::BroadcastMeshClick (HActor * HitProxy, const FViewportClick & Click) pure virtual
Broadcasts that the preview mesh was clicked.
References BroadcastMeshClick(), and Click.
Referenced by BroadcastMeshClick().
BroadcastOnLODChanged()
virtual void IPersonaPreviewScene::BroadcastOnLODChanged () pure virtual
Broadcasts that we want to force an update, after preview mesh's LOD has changed.
BroadcastOnMorphTargetsChanged()
virtual void IPersonaPreviewScene::BroadcastOnMorphTargetsChanged () pure virtual
Broadcasts that the preview mesh morph targets has changed.
BroadcastOnSelectedLODChanged()
virtual void IPersonaPreviewScene::BroadcastOnSelectedLODChanged () pure virtual
Broadcast select LOD changed.
References BroadcastOnSelectedLODChanged().
Referenced by BroadcastOnSelectedLODChanged().
ClearRemoveAttachedComponentFilter()
virtual void IPersonaPreviewScene::ClearRemoveAttachedComponentFilter () pure virtual
References ClearRemoveAttachedComponentFilter().
Referenced by ClearRemoveAttachedComponentFilter().
ClearSelectedActor()
virtual void IPersonaPreviewScene::ClearSelectedActor () pure virtual
Clears the selected actor.
ClearSelectedBone()
virtual void IPersonaPreviewScene::ClearSelectedBone () pure virtual
Clears the selected bone on the preview component.
ClearSelectedSocket()
virtual void IPersonaPreviewScene::ClearSelectedSocket () pure virtual
Clears the selected socket on the preview component.
DeselectAll()
virtual void IPersonaPreviewScene::DeselectAll () pure virtual
Clears all selection on the preview component.
EnableWind()
virtual void IPersonaPreviewScene::EnableWind (bool bEnableWind) pure virtual
Enable wind.
Useful when simulating cloth.
References EnableWind().
Referenced by EnableWind().
FlagTickable()
virtual void IPersonaPreviewScene::FlagTickable () pure virtual
Let the preview scene know that it should tick (because it is visible)
References FlagTickable().
Referenced by FlagTickable().
FocusViews()
virtual void IPersonaPreviewScene::FocusViews () pure virtual
Request our views to focus on the current item.
ForEachPreviewMesh()
virtual void IPersonaPreviewScene::ForEachPreviewMesh (TFunction< void(UDebugSkelMeshComponent *)> PerMeshFunction) pure virtual
Run a lambda function on each preview mesh in the scene.
GetActor()
virtual AActor * IPersonaPreviewScene::GetActor () const pure virtual
Get the main actor.
References GetActor().
Referenced by GetActor().
GetAllPreviewMeshComponents()
virtual TArray< UDebugSkelMeshComponent * > IPersonaPreviewScene::GetAllPreviewMeshComponents () const pure virtual
Get array of all skeletal mesh components in the preview scene.
GetAnimationPlaybackSpeedMode()
virtual EAnimationPlaybackSpeeds::Type IPersonaPreviewScene::GetAnimationPlaybackSpeedMode () const pure virtual
Retrieve the current animation playback speed mode.
References GetAnimationPlaybackSpeedMode().
Referenced by GetAnimationPlaybackSpeedMode().
GetCurrentCameraOverride()
virtual TSharedPtr< FEditorCameraController > IPersonaPreviewScene::GetCurrentCameraOverride () const pure virtual
Get the current camera override.
References GetCurrentCameraOverride().
Referenced by GetCurrentCameraOverride().
GetCustomAnimationSpeed()
virtual float IPersonaPreviewScene::GetCustomAnimationSpeed () const pure virtual
Get the current custom animation playback speed.
References GetCustomAnimationSpeed().
Referenced by GetCustomAnimationSpeed().
GetGravityScale()
virtual float IPersonaPreviewScene::GetGravityScale () const pure virtual
Get the gravity scale.
References GetGravityScale().
Referenced by GetGravityScale().
GetPersonaToolkit()
virtual TSharedRef< class IPersonaToolkit > IPersonaPreviewScene::GetPersonaToolkit () const pure virtual
Get the persona toolkit we are associated with.
GetPreviewAnimationAsset()
virtual UAnimationAsset * IPersonaPreviewScene::GetPreviewAnimationAsset () const pure virtual
Get the animation asset we are previewing.
GetPreviewMesh()
virtual USkeletalMesh * IPersonaPreviewScene::GetPreviewMesh () const pure virtual
Get the preview mesh for this scene (does go via skeleton/asset)
GetPreviewMeshComponent()
virtual UDebugSkelMeshComponent * IPersonaPreviewScene::GetPreviewMeshComponent () const pure virtual
Get the skeletal mesh component we are using for preview, if any.
GetSelectedActor()
virtual AActor * IPersonaPreviewScene::GetSelectedActor () const pure virtual
Get the currently selected actor.
References GetSelectedActor().
Referenced by GetSelectedActor().
GetSelectedBoneIndex()
virtual int32 IPersonaPreviewScene::GetSelectedBoneIndex () const pure virtual
Get the currently selected bone index.
References GetSelectedBoneIndex().
Referenced by GetSelectedBoneIndex().
GetSelectedSocket()
virtual FSelectedSocketInfo IPersonaPreviewScene::GetSelectedSocket () const pure virtual
Get the currently selected socket.
References GetSelectedSocket().
Referenced by GetSelectedSocket().
GetWindStrength()
virtual float IPersonaPreviewScene::GetWindStrength () const pure virtual
Get the wind strength.
References GetWindStrength().
Referenced by GetWindStrength().
HandleSkeletonTreeSelectionChanged()
virtual void IPersonaPreviewScene::HandleSkeletonTreeSelectionChanged (const TArrayView< TSharedPtr< ISkeletonTreeItem > > & InSelectedItems, ESelectInfo::Type InSelectInfo) pure virtual
Handle syncing selection with the skeleton tree.
References HandleSkeletonTreeSelectionChanged().
Referenced by HandleSkeletonTreeSelectionChanged().
InvalidateViews()
virtual void IPersonaPreviewScene::InvalidateViews () pure virtual
Flag that we want our views to be updated.
IsPlaybackSpeedSelected()
virtual bool IPersonaPreviewScene::IsPlaybackSpeedSelected (int32 InPlaybackSpeedMode) const pure virtual
Function to return whether the supplied playback speed is the current active one.
References IsPlaybackSpeedSelected().
Referenced by IsPlaybackSpeedSelected().
IsShowReferencePoseEnabled()
virtual bool IPersonaPreviewScene::IsShowReferencePoseEnabled () const pure virtual
IsWindEnabled()
virtual bool IPersonaPreviewScene::IsWindEnabled () const pure virtual
Check whether wind is enabled.
References IsWindEnabled().
Referenced by IsWindEnabled().
RefreshAdditionalMeshes()
virtual void IPersonaPreviewScene::RefreshAdditionalMeshes (bool bAllowOverrideBaseMesh) pure virtual
Refreshes the additional meshes displayed in this preview scene.
RegisterOnAnimChanged()
virtual void IPersonaPreviewScene::RegisterOnAnimChanged (const FOnAnimChanged & Delegate) pure virtual
Registers a delegate to be called after the preview animation has been changed.
RegisterOnCameraOverrideChanged()
virtual void IPersonaPreviewScene::RegisterOnCameraOverrideChanged (const FSimpleDelegate & Delegate) pure virtual
Register callback for when the camera override is changed.
References RegisterOnCameraOverrideChanged().
Referenced by RegisterOnCameraOverrideChanged().
RegisterOnDeselectAll()
virtual FDelegateHandle IPersonaPreviewScene::RegisterOnDeselectAll (const FSimpleDelegate & Delegate) pure virtual
Registers a delegate to be called when all sockets/bones are deselected.
References RegisterOnDeselectAll().
Referenced by RegisterOnDeselectAll().
RegisterOnFocusViews()
virtual void IPersonaPreviewScene::RegisterOnFocusViews (const FSimpleDelegate & Delegate) pure virtual
Registers a delegate to be called when the view should be focused.
RegisterOnInvalidateViews()
virtual void IPersonaPreviewScene::RegisterOnInvalidateViews (const FSimpleDelegate & Delegate) pure virtual
Registers a delegate to be called when the view is invalidated.
RegisterOnLODChanged()
virtual void IPersonaPreviewScene::RegisterOnLODChanged (const FSimpleDelegate & Delegate) pure virtual
Registers a delegate to be called when the preview mesh's LOD has changed.
RegisterOnMeshClick()
virtual void IPersonaPreviewScene::RegisterOnMeshClick (const FOnMeshClick & Delegate) pure virtual
Registers a delegate to be called when the preview mesh is clicked.
RegisterOnMorphTargetsChanged()
virtual void IPersonaPreviewScene::RegisterOnMorphTargetsChanged (const FSimpleDelegate & Delegate) pure virtual
Registers a delegate to be called when the preview mesh's morph targets has changed.
RegisterOnPostTick()
virtual void IPersonaPreviewScene::RegisterOnPostTick (const FSimpleDelegate & Delegate) pure virtual
Register a callback for just after the preview scene is ticked.
References RegisterOnPostTick().
Referenced by RegisterOnPostTick().
RegisterOnPreTick()
virtual void IPersonaPreviewScene::RegisterOnPreTick (const FSimpleDelegate & Delegate) pure virtual
Register a callback for just before the preview scene is ticked.
References RegisterOnPreTick().
Referenced by RegisterOnPreTick().
RegisterOnPreviewMeshChanged()
virtual void IPersonaPreviewScene::RegisterOnPreviewMeshChanged (const FOnPreviewMeshChanged & Delegate) pure virtual
Registers a delegate to be called when the preview mesh is changed.
RegisterOnSelectedBonesChanged()
virtual FDelegateHandle IPersonaPreviewScene::RegisterOnSelectedBonesChanged (const FOnSelectedBonesChanged & InDelegate) pure virtual
Registers a delegate called when the bones selection has changed.
References RegisterOnSelectedBonesChanged().
Referenced by RegisterOnSelectedBonesChanged().
RegisterOnSelectedLODChanged()
virtual void IPersonaPreviewScene::RegisterOnSelectedLODChanged (const FOnSelectedLODChanged & Delegate) pure virtual
Register callback to be able to be notify when the select LOD is change.
References RegisterOnSelectedLODChanged().
Referenced by RegisterOnSelectedLODChanged().
RegisterOnSelectedSocketChanged()
virtual FDelegateHandle IPersonaPreviewScene::RegisterOnSelectedSocketChanged (const FOnSelectedSocketChanged & Delegate) pure virtual
Registers a delegate to be called when the currently selected socket has changed.
References RegisterOnSelectedSocketChanged().
Referenced by RegisterOnSelectedSocketChanged().
RemoveAttachedObjectFromPreviewComponent()
virtual void IPersonaPreviewScene::RemoveAttachedObjectFromPreviewComponent (UObject * Object, FName AttachedTo) pure virtual
Removes a currently attached object from the preview component.
References Object.
SetActor()
virtual void IPersonaPreviewScene::SetActor (AActor * InActor) pure virtual
Set the main actor.
References SetActor().
Referenced by SetActor().
SetAdditionalMeshes()
virtual void IPersonaPreviewScene::SetAdditionalMeshes (class UDataAsset * InAdditionalMeshes) pure virtual
Set the additional meshes used by this preview scene (sets the additional meshes on the skeleton)
SetAdditionalMeshesSelectable()
virtual void IPersonaPreviewScene::SetAdditionalMeshesSelectable (bool bSelectable) pure virtual
Set whether additional meshes are selectable.
SetAllowMeshHitProxies()
virtual void IPersonaPreviewScene::SetAllowMeshHitProxies (bool bState) pure virtual
Set whether or not to ignore mesh hit proxies.
References SetAllowMeshHitProxies().
Referenced by SetAllowMeshHitProxies().
SetAnimationPlaybackSpeedMode()
virtual void IPersonaPreviewScene::SetAnimationPlaybackSpeedMode (EAnimationPlaybackSpeeds::Type InMode) pure virtual
Set the playback speed mode.
References SetAnimationPlaybackSpeedMode().
Referenced by SetAnimationPlaybackSpeedMode().
SetCameraOverride()
virtual void IPersonaPreviewScene::SetCameraOverride (TSharedPtr< FEditorCameraController > NewCamera) pure virtual
Function to override the editor camera for this scene.
References SetCameraOverride().
Referenced by SetCameraOverride().
SetCustomAnimationSpeed()
virtual void IPersonaPreviewScene::SetCustomAnimationSpeed (float InAnimationSpeed) pure virtual
Set the current custom animation playback speed.
References SetCustomAnimationSpeed().
Referenced by SetCustomAnimationSpeed().
SetDefaultAnimationMode()
virtual void IPersonaPreviewScene::SetDefaultAnimationMode (EPreviewSceneDefaultAnimationMode Mode, bool bShowNow = true) pure virtual
Set the default mode this preview scene appears in.
Optionally show the default mode.
References SetDefaultAnimationMode().
Referenced by SetDefaultAnimationMode().
SetEditableSkeleton()
virtual void IPersonaPreviewScene::SetEditableSkeleton (TSharedPtr< IEditableSkeleton > InEditableSkeleton) pure virtual
Replaces the current editable skeleton.
This is not a safe operation unless you're working detached from other Persona components (eg. skeleton list).
References SetEditableSkeleton().
Referenced by SetEditableSkeleton().
SetGravityScale()
virtual void IPersonaPreviewScene::SetGravityScale (float InGravityScale) pure virtual
Set the gravity scale.
References SetGravityScale().
Referenced by SetGravityScale().
SetPreviewAnimationAsset()
virtual void IPersonaPreviewScene::SetPreviewAnimationAsset (UAnimationAsset * AnimAsset, bool bEnablePreview = true) pure virtual
Set the animation asset to preview.
SetPreviewAnimationBlueprint()
virtual void IPersonaPreviewScene::SetPreviewAnimationBlueprint (UAnimBlueprint * InAnimBlueprint, UAnimBlueprint * InOverlayOrSubAnimBlueprint) pure virtual
Set the preview animation blueprint and an optional overlay (for sub-layers)
SetPreviewMesh()
virtual void IPersonaPreviewScene::SetPreviewMesh (USkeletalMesh * NewPreviewMesh, bool bAllowOverrideBaseMesh = true) pure virtual
Set the preview mesh for this scene (does not set the preview mesh on the skeleton/asset)
SetPreviewMeshComponent()
virtual void IPersonaPreviewScene::SetPreviewMeshComponent (UDebugSkelMeshComponent * InSkeletalMeshComponent) pure virtual
Set the skeletal mesh component we are going to preview.
SetRemoveAttachedComponentFilter()
virtual void IPersonaPreviewScene::SetRemoveAttachedComponentFilter (const FOnRemoveAttachedComponentFilter & Delegate) pure virtual
setter/getter for can remove attach component
References SetRemoveAttachedComponentFilter().
Referenced by SetRemoveAttachedComponentFilter().
SetSelectedActor()
virtual void IPersonaPreviewScene::SetSelectedActor (AActor * InActor) pure virtual
Sets the selected actor.
SetSelectedBone()
virtual void IPersonaPreviewScene::SetSelectedBone (const FName & BoneName, ESelectInfo::Type InSelectInfo) pure virtual
Sets the selected bone on the preview component.
Referenced by UE_DEPRECATED().
SetSelectedBones()
virtual void IPersonaPreviewScene::SetSelectedBones (const TArray< FName > & InBoneNames, ESelectInfo::Type InSelectInfo) pure virtual
Sets the selected bones on the preview component.
SetSelectedSocket()
virtual void IPersonaPreviewScene::SetSelectedSocket (const FSelectedSocketInfo & SocketInfo) pure virtual
Sets the selected socket on the preview component.
SetWindStrength()
virtual void IPersonaPreviewScene::SetWindStrength (float InWindStrength) pure virtual
Set the wind strength.
References SetWindStrength().
Referenced by SetWindStrength().
ShowDefaultMode()
virtual void IPersonaPreviewScene::ShowDefaultMode () pure virtual
Show the mode specifed by SetDefaultAnimationMode()
References ShowDefaultMode().
Referenced by ShowDefaultMode().
ShowReferencePose()
virtual void IPersonaPreviewScene::ShowReferencePose (bool bShowRefPose, bool bResetBoneTransforms = false) pure virtual
Show the reference pose of the displayed skeletal mesh.
Otherwise display the default. Optionally reset bone transforms, if any.
TogglePlayback()
virtual void IPersonaPreviewScene::TogglePlayback () pure virtual
Toggle the playback of animation, if any.
References TogglePlayback().
Referenced by TogglePlayback().
UE_DEPRECATED() [1/3]
IPersonaPreviewScene::UE_DEPRECATED (4. 26, "Please call/implement SetSelectedBone with ESelectInfo") const & inline final
Sets the selected bone on the preview component.
Definition at line 140 of file IPersonaPreviewScene.h.
References SetSelectedBone().
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/3]
IPersonaPreviewScene::UE_DEPRECATED (5. 6, "Use RegisterOnSelectedBonesChanged instead.") const & pure virtual
Registers a delegate to be called when the currently selected bone has changed.
UE_DEPRECATED() [3/3]
IPersonaPreviewScene::UE_DEPRECATED (5. 6, "Use UnregisterOnSelectedBonesChanged instead.") pure virtual
Unregisters a delegate called when the currently selected bone has changed.
References UE_DEPRECATED().
UnregisterForUndo()
virtual void IPersonaPreviewScene::UnregisterForUndo () pure virtual
Unregister this scene from the Undo chain.
Necessary for certain editor windows.
UnregisterOnAnimChanged()
virtual void IPersonaPreviewScene::UnregisterOnAnimChanged (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called after the preview animation has been changed.
UnregisterOnCameraOverrideChanged()
virtual void IPersonaPreviewScene::UnregisterOnCameraOverrideChanged (FDelegateUserObject Thing) pure virtual
Unregister callback for when the camera override is changed.
References UnregisterOnCameraOverrideChanged().
Referenced by UnregisterOnCameraOverrideChanged().
UnregisterOnDeselectAll()
virtual void IPersonaPreviewScene::UnregisterOnDeselectAll (FDelegateHandle InHandle) pure virtual
unregisters a delegate called when all sockets/bones are deselected
References UnregisterOnDeselectAll().
Referenced by UnregisterOnDeselectAll().
UnregisterOnFocusViews()
virtual void IPersonaPreviewScene::UnregisterOnFocusViews (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the view should be focused.
UnregisterOnInvalidateViews()
virtual void IPersonaPreviewScene::UnregisterOnInvalidateViews (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the view is invalidated.
UnregisterOnLODChanged()
virtual void IPersonaPreviewScene::UnregisterOnLODChanged (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the preview mesh's LOD has changed.
UnregisterOnMeshClick()
virtual void IPersonaPreviewScene::UnregisterOnMeshClick (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the preview mesh is clicked.
UnregisterOnMorphTargetsChanged()
virtual void IPersonaPreviewScene::UnregisterOnMorphTargetsChanged (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the preview mesh's morph targets has changed.
UnregisterOnPostTick()
virtual void IPersonaPreviewScene::UnregisterOnPostTick (FDelegateUserObject Thing) pure virtual
Unregister a callback for just after the preview scene is ticked.
References UnregisterOnPostTick().
Referenced by UnregisterOnPostTick().
UnregisterOnPreTick()
virtual void IPersonaPreviewScene::UnregisterOnPreTick (FDelegateUserObject Thing) pure virtual
Unregister a callback for just before the preview scene is ticked.
References UnregisterOnPreTick().
Referenced by UnregisterOnPreTick().
UnregisterOnPreviewMeshChanged()
virtual void IPersonaPreviewScene::UnregisterOnPreviewMeshChanged (FDelegateUserObject Thing) pure virtual
Unregisters a delegate to be called when the preview mesh is changed.
UnregisterOnSelectedBonesChanged()
virtual void IPersonaPreviewScene::UnregisterOnSelectedBonesChanged (FDelegateHandle InHandle) pure virtual
Unregisters a delegate called when the bones selection has changed.
References UnregisterOnSelectedBonesChanged().
Referenced by UnregisterOnSelectedBonesChanged().
UnRegisterOnSelectedLODChanged()
virtual void IPersonaPreviewScene::UnRegisterOnSelectedLODChanged (FDelegateUserObject Thing) pure virtual
Unregister callback to free up the ressources.
References UnRegisterOnSelectedLODChanged().
Referenced by UnRegisterOnSelectedLODChanged().
UnregisterOnSelectedSocketChanged()
virtual void IPersonaPreviewScene::UnregisterOnSelectedSocketChanged (FDelegateHandle InHandle) pure virtual
Unregisters a delegate called when the currently selected socket has changed.
References UnregisterOnSelectedSocketChanged().
Referenced by UnregisterOnSelectedSocketChanged().
The documentation for this class was generated from the following file:
IPersonaPreviewScene.h