Unreal Engine 5.6 C++ API: FMetasoundParameterPackStorage::ParameterIterator Struct Reference
FMetasoundParameterPackStorage::ParameterIterator Struct Reference
#include "MetasoundParameterPack.h"
Public Member Functions
ParameterIterator (uint8 *Start, uint8 *End)
MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase * GetParameterBase ()
bool operator!= (const ParameterIterator &Other) const
ParameterIterator & operator++ ()
ParameterIterator operator++ (int)
MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase * operator-> ()
bool operator== (const ParameterIterator &Other) const
Data Fields
uint8 * CurrentNode
uint8 * EndAddress
Detailed Description
Definition at line 96 of file MetasoundParameterPack.h.
Constructor & Destructor Documentation
ParameterIterator()
FMetasoundParameterPackStorage::ParameterIterator::ParameterIterator (uint8 * Start, uint8 * End) inline
Definition at line 101 of file MetasoundParameterPack.h.
References CurrentNode, End, and EndAddress.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
GetParameterBase()
MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase * FMetasoundParameterPackStorage::ParameterIterator::GetParameterBase () inline
Definition at line 146 of file MetasoundParameterPack.h.
References CurrentNode.
operator!=()
bool FMetasoundParameterPackStorage::ParameterIterator::operator!= (const ParameterIterator & Other) const inline
Definition at line 135 of file MetasoundParameterPack.h.
References ParameterIterator(), CurrentNode, and Other.
operator++() [1/2]
ParameterIterator & FMetasoundParameterPackStorage::ParameterIterator::operator++ () inline
Definition at line 106 of file MetasoundParameterPack.h.
References ParameterIterator(), CurrentNode, EndAddress, and MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase::NextHeaderOffset.
operator++() [2/2]
ParameterIterator FMetasoundParameterPackStorage::ParameterIterator::operator++ (int) inline
Definition at line 123 of file MetasoundParameterPack.h.
References ParameterIterator().
operator->()
MetasoundParameterPackPrivate::FMetasoundParameterPackItemBase * FMetasoundParameterPackStorage::ParameterIterator::operator-> () inline
Definition at line 140 of file MetasoundParameterPack.h.
References CurrentNode.
operator==()
bool FMetasoundParameterPackStorage::ParameterIterator::operator== (const ParameterIterator & Other) const inline
Definition at line 130 of file MetasoundParameterPack.h.
References ParameterIterator(), CurrentNode, and Other.
Field Documentation
CurrentNode
uint8* FMetasoundParameterPackStorage::ParameterIterator::CurrentNode
Definition at line 98 of file MetasoundParameterPack.h.
Referenced by ParameterIterator(), GetParameterBase(), operator!=(), operator++(), operator->(), and operator==().
EndAddress
uint8* FMetasoundParameterPackStorage::ParameterIterator::EndAddress
Definition at line 99 of file MetasoundParameterPack.h.
Referenced by ParameterIterator(), and operator++().
The documentation for this struct was generated from the following file:
MetasoundParameterPack.h