Unreal Engine 5.6 C++ API: UE::Virtualization::FPushResult Struct Reference
UE::Virtualization::FPushResult Struct Reference
The result of a push operation on a single payload.
#include "VirtualizationSystem.h"
Public Types
enum class EStatus : int8 {
Error = -5 , ProcessDisabled = -4 , NoBackend = -3 , Invalid = -2 ,
Filtered = -1 , Pending = 0 , AlreadyExisted = 1 , Pushed = 2
}
Records the status of the push, negative values indicate an error, positive values indicate that the payload is stored in the target backend(s) and a zero value means that the operation has not yet run.
Public Member Functions
FPushResult ()=default
~FPushResult ()=default
EPayloadFilterReason GetFilterReason () const
Returns why the payload was rejected by the filtering system (if there was one)
bool IsFiltered () const
Returns true if the payload was rejected by the filtering system.
bool IsVirtualized () const
Returns true if the payload is stored in the target backend(s) after the operation completed.
bool WasError () const
Returns true if the payload experienced an error during upload.
bool WasPushed () const
Returns true if the payload was actually uploaded to the target backend(s)
Static Public Member Functions
static FPushResult GetAsAlreadyExists ()
static FPushResult GetAsError ()
static FPushResult GetAsFiltered (EPayloadFilterReason Reason)
static FPushResult GetAsInvalid ()
static FPushResult GetAsNoBackend ()
static FPushResult GetAsProcessDisabled ()
static FPushResult GetAsPushed ()
Private Member Functions
FPushResult (EStatus InStatus)
FPushResult (EStatus InStatus, EPayloadFilterReason InReason)
Private Attributes
EPayloadFilterReason FilterReason = EPayloadFilterReason::None
EStatus Status = EStatus::Pending
Detailed Description
The result of a push operation on a single payload.
Definition at line 105 of file VirtualizationSystem.h.
Member Enumeration Documentation
EStatus
enum class UE::Virtualization::FPushResult::EStatus : int8 strong
Records the status of the push, negative values indicate an error, positive values indicate that the payload is stored in the target backend(s) and a zero value means that the operation has not yet run.
Enumerator
Error
The push operation caused an error.
ProcessDisabled
The push operation storage type is disabled.
NoBackend
There were no backends that supported the push operation.
Invalid
The push operation was run on an invalid payload id.
Filtered
The payload was rejected by the filtering system.
Pending
The push operation has not yet been run.
AlreadyExisted
The payload was already present in the target backend(s)
Pushed
The payload was pushed to the backend(s)
Definition at line 112 of file VirtualizationSystem.h.
Constructor & Destructor Documentation
FPushResult() [1/3]
UE::Virtualization::FPushResult::FPushResult () default
Referenced by GetAsAlreadyExists(), GetAsError(), GetAsFiltered(), GetAsInvalid(), GetAsNoBackend(), GetAsProcessDisabled(), and GetAsPushed().
~FPushResult()
UE::Virtualization::FPushResult::~FPushResult () default
FPushResult() [2/3]
UE::Virtualization::FPushResult::FPushResult (EStatus InStatus) inline private
Definition at line 211 of file VirtualizationSystem.h.
References check, Pending, and Status.
FPushResult() [3/3]
UE::Virtualization::FPushResult::FPushResult (EStatus InStatus, EPayloadFilterReason InReason) inline private
Definition at line 217 of file VirtualizationSystem.h.
References check, FilterReason, UE::Virtualization::None, Pending, and Status.
Member Function Documentation
GetAsAlreadyExists()
FPushResult UE::Virtualization::FPushResult::GetAsAlreadyExists () inline static
Definition at line 160 of file VirtualizationSystem.h.
References FPushResult(), and AlreadyExisted.
GetAsError()
FPushResult UE::Virtualization::FPushResult::GetAsError () inline static
Definition at line 135 of file VirtualizationSystem.h.
References FPushResult(), and Error.
GetAsFiltered()
FPushResult UE::Virtualization::FPushResult::GetAsFiltered (EPayloadFilterReason Reason) inline static
Definition at line 155 of file VirtualizationSystem.h.
References FPushResult(), and Filtered.
GetAsInvalid()
FPushResult UE::Virtualization::FPushResult::GetAsInvalid () inline static
Definition at line 150 of file VirtualizationSystem.h.
References FPushResult(), and Invalid.
GetAsNoBackend()
FPushResult UE::Virtualization::FPushResult::GetAsNoBackend () inline static
Definition at line 145 of file VirtualizationSystem.h.
References FPushResult(), and NoBackend.
GetAsProcessDisabled()
FPushResult UE::Virtualization::FPushResult::GetAsProcessDisabled () inline static
Definition at line 140 of file VirtualizationSystem.h.
References FPushResult(), and ProcessDisabled.
GetAsPushed()
FPushResult UE::Virtualization::FPushResult::GetAsPushed () inline static
Definition at line 165 of file VirtualizationSystem.h.
References FPushResult(), and Pushed.
GetFilterReason()
EPayloadFilterReason UE::Virtualization::FPushResult::GetFilterReason () const inline
Returns why the payload was rejected by the filtering system (if there was one)
Definition at line 204 of file VirtualizationSystem.h.
References FilterReason.
IsFiltered()
bool UE::Virtualization::FPushResult::IsFiltered () const inline
Returns true if the payload was rejected by the filtering system.
Definition at line 189 of file VirtualizationSystem.h.
References check, Filtered, FilterReason, UE::Virtualization::None, and Status.
IsVirtualized()
bool UE::Virtualization::FPushResult::IsVirtualized () const inline
Returns true if the payload is stored in the target backend(s) after the operation completed.
Definition at line 183 of file VirtualizationSystem.h.
References Pending, and Status.
WasError()
bool UE::Virtualization::FPushResult::WasError () const inline
Returns true if the payload experienced an error during upload.
Definition at line 177 of file VirtualizationSystem.h.
References Pending, and Status.
WasPushed()
bool UE::Virtualization::FPushResult::WasPushed () const inline
Returns true if the payload was actually uploaded to the target backend(s)
Definition at line 171 of file VirtualizationSystem.h.
References Pushed, and Status.
Field Documentation
FilterReason
EPayloadFilterReason UE::Virtualization::FPushResult::FilterReason = EPayloadFilterReason::None private
Definition at line 226 of file VirtualizationSystem.h.
Referenced by FPushResult(), GetFilterReason(), and IsFiltered().
Status
EStatus UE::Virtualization::FPushResult::Status = EStatus::Pending private
Definition at line 225 of file VirtualizationSystem.h.
Referenced by FPushResult(), FPushResult(), IsFiltered(), IsVirtualized(), WasError(), and WasPushed().
The documentation for this struct was generated from the following file:
VirtualizationSystem.h