Unreal Engine 5.6 C++ API: FRigVMActionWrapper Struct Reference
FRigVMActionWrapper Struct Reference
The action wrapper is used to extract an action from a serialized key.
#include "RigVMControllerActions.h"
Public Member Functions
FRigVMActionWrapper (const FRigVMActionKey &Key)
~FRigVMActionWrapper ()
FString ExportText () const
FRigVMBaseAction * GetAction (URigVMController *InLastController=nullptr) const
const UScriptStruct * GetScriptStruct () const
Private Member Functions
FRigVMActionWrapper (const FRigVMActionWrapper &Other)=delete
FRigVMActionWrapper & operator= (const FRigVMActionWrapper &Other)=delete
Private Attributes
TSharedPtr< FStructOnScope > StructOnScope
Detailed Description
The action wrapper is used to extract an action from a serialized key.
Definition at line 75 of file RigVMControllerActions.h.
Constructor & Destructor Documentation
FRigVMActionWrapper() [1/2]
FRigVMActionWrapper::FRigVMActionWrapper (const FRigVMActionKey & Key)
References Key.
Referenced by FRigVMActionWrapper(), and operator=().
~FRigVMActionWrapper()
FRigVMActionWrapper::~FRigVMActionWrapper ()
FRigVMActionWrapper() [2/2]
FRigVMActionWrapper::FRigVMActionWrapper (const FRigVMActionWrapper & Other) private delete
References FRigVMActionWrapper(), and Other.
Member Function Documentation
ExportText()
FString FRigVMActionWrapper::ExportText () const
GetAction()
FRigVMBaseAction * FRigVMActionWrapper::GetAction (URigVMController * InLastController = nullptr) const
GetScriptStruct()
const UScriptStruct * FRigVMActionWrapper::GetScriptStruct () const
operator=()
FRigVMActionWrapper & FRigVMActionWrapper::operator= (const FRigVMActionWrapper & Other) private delete
References FRigVMActionWrapper(), and Other.
Field Documentation
StructOnScope
TSharedPtr<FStructOnScope> FRigVMActionWrapper::StructOnScope private
Definition at line 89 of file RigVMControllerActions.h.
The documentation for this struct was generated from the following file:
RigVMControllerActions.h