Unreal Engine 5.6 C++ Documentation: ALightWeightInstanceManager Class Reference
ALightWeightInstanceManager Class Reference
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/LightWeightInstanceManager.h>
Public Member Functions
virtual ~ALightWeightInstanceManager ()
virtual void Tick (float DeltaSeconds)
Function called every frame on this Actor.
FVector GetLocation (const FActorInstanceHandle &Handle) const
FRotator GetRotation (const FActorInstanceHandle &Handle) const
FString GetName (const FActorInstanceHandle &Handle) const
bool DoesRepresentClass (const UClass *OtherClass) const
bool DoesAcceptClass (const UClass *OtherClass) const
UClass * GetAcceptedClass () const
virtual void SetRepresentedClass (UClass *ActorClass)
int32 FindIndexForActor (const AActor *InActor) const
FActorInstanceHandle ConvertActorToLightWeightInstance (AActor *InActor)
virtual int32 GetGridSize () const
FInt32Vector3 ConvertPositionToCoord (const FVector &InPosition) const
FBox ConvertPositionToGridBounds (const FVector &InPosition) const
bool HasAnyValidInstancesOrManagedActors () const
virtual int32 ConvertCollisionIndexToInstanceIndex (int32 InIndex, const UPrimitiveComponent *RelevantComponent) const
virtual AActor * FindActor (const FActorInstanceHandle &Handle) override
virtual AActor * FindOrCreateActor (const FActorInstanceHandle &Handle) override
virtual UClass * GetRepresentedClass (const int32 InstanceIndex) const override
virtual ULevel * GetLevelForInstance (const int32 InstanceIndex) const override
virtual FTransform GetTransform (const FActorInstanceHandle &Handle) const
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Returns the properties used for network replication, this needs to be overridden by all actor classes with native replicated properties.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const override
Called when this actor begins replicating to initialize the state of custom property conditions.
virtual void OnRep_ReplicateMovement ()
Called on client when updated bReplicateMovement value is received for this actor.
virtual bool ShouldDuplicateInPIE () const
void SetCallPreReplication (bool bCall)
Set whether or not we should make calls to PreReplication.
void SetCallPreReplicationForReplay (bool bCall)
Set whether or not we should make calls to PreReplicationForReplay.
bool GetTearOff () const
If true, this actor is no longer replicated to new clients, and is "torn off" (becomes a ROLE_Authority) on clients to which it was being replicated.
virtual bool IsInEditingLevelInstance () const
Deprecated for a non virtual version.
bool IsInAnyEditLevelInstance () const
If true, the actor belongs to a level instance which is currently in an edit mode: edit or property override edit.
bool IsInEditLevelInstance () const
If true, the actor belongs to a level instance which is currently being edited.
bool IsInPropertyOverrideLevelInstance () const
If true, the actor belongs to a level instance which is currently in property override edit.
bool IsInEditLevelInstanceHierarchy () const
If true, the actor belongs to a level instance which is currently being edited or a parent level instance being edited.
bool HasLevelInstancePropertyOverrides () const
If true, this actor or one of its components has property overrides applied.
bool HasEditableLevelLevelInstancePropertyOverrides () const
If true, this actor or one of its components has property overrides applied from an editable level instance (level instance is in a non readonly level)
bool IsInLevelInstance () const
If true, the actor belongs to a level instance.
virtual void TearOff ()
Networking - Server - TearOff this actor to stop replication to clients.
virtual bool HasNetOwner () const
Does this actor have an owner responsible for replication?
virtual bool HasLocalNetOwner () const
Does this actor have a locally controlled owner responsible for replication?
bool GetAutoDestroyWhenFinished () const
void SetAutoDestroyWhenFinished (bool bVal)
EActorUpdateOverlapsMethod GetUpdateOverlapsMethodDuringLevelStreaming () const
Get the method used to UpdateOverlaps() when loaded via level streaming.
void SetReplicates (bool bInReplicates)
Set whether this actor replicates to network clients.
virtual void SetReplicateMovement (bool bInReplicateMovement)
Set whether this actor's movement replicates to network clients.
void SetAutonomousProxy (const bool bInAutonomousProxy, const bool bAllowForcePropertyCompare=true)
Sets whether or not this Actor is an autonomous proxy, which is an actor on a network client that is controlled by a user on that client.
void CopyRemoteRoleFrom (const AActor *CopyFromActor)
Copies RemoteRole from another Actor and adds this actor to the list of network actors if necessary.
ENetRole GetLocalRole () const
Returns how much control the local machine has over this actor.
ENetRole GetRemoteRole () const
Returns how much control the remote machine has over this actor.
void SetNetAddressable ()
Allows this actor to be net-addressable by full path name, even if the actor was spawned after map load.
const struct FRepAttachment & GetAttachmentReplication () const
Get read-only access to current AttachmentReplication.
virtual void OnRep_AttachmentReplication ()
Called on client when updated AttachmentReplication value is received for this actor.
virtual bool IsReplicationPausedForConnection (const FNetViewer &ConnectionOwnerNetViewer)
Gives the actor a chance to pause replication to a player represented by the passed in actor - only called on server.
virtual void OnReplicationPausedChanged (bool bIsReplicationPaused)
Called on the client when the replication paused value is changed.
void SetPhysicsReplicationMode (const EPhysicsReplicationMode ReplicationMode)
Set the physics replication mode of this body, via EPhysicsReplicationMode.
EPhysicsReplicationMode GetPhysicsReplicationMode ()
Get the physics replication mode of this body, via EPhysicsReplicationMode.
void RegisterAsFocalPointInPhysicsReplicationLOD () const
Register this actors root components physics object as a focal particle in Physics Repliocation LOD.
void UnregisterAsFocalPointInPhysicsReplicationLOD () const
Unregister this actors root components physics object from being a focal particle in Physics Repliocation LOD.
bool CanTriggerResimulation () const
Can this body trigger a resimulation when Physics Prediction is enabled.
float GetResimulationThreshold () const
Get the error threshold in centimeters before this object should enforce a resimulation to trigger.
void SetNetDriverName (FName NewNetDriverName)
Set the name of the net driver associated with this actor.
FName GetNetDriverName () const
Returns name of the net driver associated with this actor (all RPCs will go out via this connection)
bool IsUsingRegisteredSubObjectList () const
Returns true if this actor is replicating SubObjects & ActorComponents via the registration list.
virtual bool ReplicateSubobjects (class UActorChannel *Channel, class FOutBunch *Bunch, FReplicationFlags *RepFlags)
Method that allows an actor to replicate subobjects on its actor channel.
virtual void OnSubobjectCreatedFromReplication (UObject *NewSubobject)
Called on the actor when a new subobject is dynamically created via replication.
virtual void OnSubobjectDestroyFromReplication (UObject *Subobject)
Called on the actor when a subobject is dynamically destroyed via replication.
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the actor right before replication occurs.
virtual void PreReplicationForReplay (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the actor right before replication occurs.
virtual void RewindForReplay ()
Called on the actor before checkpoint data is applied during a replay.
void CallPreReplication (UNetDriver *NetDriver)
Called by the networking system to call PreReplication on this actor and its components using the given NetDriver to find or create RepChangedPropertyTrackers.
virtual void OnRep_Instigator ()
Called on clients when Instigator is replicated.
class UHLODLayer * GetHLODLayer () const
Return the HLOD layer that should include this actor.
void SetHLODLayer (class UHLODLayer *InHLODLayer)
Specify in which HLOD layer this actor should be included.
void SetRayTracingGroupId (int32 InRaytracingGroupId)
Specify a RayTracingGroupId for this actors.
int32 GetRayTracingGroupId () const
Return the RayTracingGroupId for this actor.
bool AllowReceiveTickEventOnDedicatedServer () const
Return the value of bAllowReceiveTickEventOnDedicatedServer, indicating whether the Blueprint ReceiveTick() event will occur on dedicated servers.
bool IsRunningUserConstructionScript () const
Returns if this actor is currently running the User Construction Script.
void SetPackageExternal (bool bExternal, bool bShouldDirty=true, UPackage *ActorExternalPackage=nullptr)
Set the actor packaging mode.
virtual bool ShouldLevelKeepRefIfExternal () const
Determine how this actor should be referenced by the level when external (saved in its own package).
bool IsMainWorldOnly () const
Whether this actor should be ignored when it is not loaded as part of the Main World (Persistent Level).
virtual FName GetRuntimeGrid () const
Returns this actor's current target runtime grid.
void SetRuntimeGrid (FName InRuntimeGrid)
Sets this actor's current target runtime grid.
const FGuid & GetActorGuid () const
Returns this actor's Guid.
const FGuid & GetActorInstanceGuid () const
Returns this actor's instance Guid.
const FGuid & GetContentBundleGuid () const
Returns this actor's content bundle Guid.
virtual bool IsLockLocation () const
Returns true if actor location should be locked.
void SetLockLocation (bool bInLockLocation)
Set the bLockLocation flag.
virtual void OnPlayFromHere ()
Called on actor which initiated the PIE session.
bool CanPlayFromHere () const
virtual TUniquePtr< class FWorldPartitionActorDesc > CreateClassActorDesc () const
Creates an uninitialized actor descriptor from this actor.
TUniquePtr< class FWorldPartitionActorDesc > CreateActorDesc () const
Creates an initialized actor descriptor from this actor.
virtual void GetActorDescProperties (FPropertyPairsMap &PropertyPairsMap) const
Add properties to the actor desc.
virtual void OnLoadedActorAddedToLevel ()
Called when this actor gets added to the level in the editor by world partition loading.
virtual void OnLoadedActorRemovedFromLevel ()
Called when this actor gets removed from the level in the editor by world partition unloading.
FString GetActorNameOrLabel () const
FStringView GetActorLabelView () const
virtual void EnableInput (class APlayerController *PlayerController)
Pushes this actor on to the stack of input being handled by a PlayerController.
virtual void CreateInputComponent (TSubclassOf< UInputComponent > InputComponentToCreate)
Creates an input component from the input component passed in.
virtual void DisableInput (class APlayerController *PlayerController)
Removes this actor from the stack of input being handled by a PlayerController.
float GetInputAxisValue (const FName InputAxisName) const
Gets the value of the input axis if input is enabled for this actor.
float GetInputAxisKeyValue (const FKey InputAxisKey) const
Gets the value of the input axis key if input is enabled for this actor.
FVector GetInputVectorAxisValue (const FKey InputAxisKey) const
Gets the value of the input axis key if input is enabled for this actor.
APawn * GetInstigator () const
Returns the instigator for this actor, or nullptr if there is none.
template<class T>
T * GetInstigator () const
Get the instigator, cast as a specific class.
AController * GetInstigatorController () const
Returns the instigator's controller for this actor, or nullptr if there is none.
template<class T>
T * GetInstigatorController () const
Returns the instigator's controller, cast as a specific class.
bool AddDataLayer (const UDataLayerInstance *DataLayerInstance)
PRAGMA_DISABLE_DEPRECATION_WARNINGS bool AddDataLayer (const UDEPRECATED_DataLayer *DataLayer)
bool AddDataLayer (const UDataLayerAsset *DataLayerAsset)
bool AddDataLayer (const FActorDataLayer &ActorDataLayer)
bool RemoveDataLayer (const UDataLayerInstance *DataLayerInstance)
bool RemoveDataLayer (const UDEPRECATED_DataLayer *DataLayer)
bool RemoveDataLayer (const UDataLayerAsset *DataLayerAsset)
bool RemoveDataLayer (const FActorDataLayer &ActorDataLayer)
bool CanAddDataLayer (const UDataLayerInstance *InDataLayerInstance, FText *OutReason=nullptr) const
TArray< const UDataLayerInstance * > RemoveAllDataLayers ()
bool SupportsDataLayerType (TSubclassOf< UDataLayerInstance > DataLayerType) const
TArray< const UDataLayerInstance * > GetDataLayerInstancesForLevel () const
TArray< FName > GetDataLayerInstanceNames () const
bool IsPropertyChangedAffectingDataLayers (FPropertyChangedEvent &PropertyChangedEvent) const
void FixupDataLayers (bool bRevertChangesOnLockedDataLayer=false)
TArray< const UDataLayerAsset * > GetDataLayerAssets (bool bIncludeExternalDataLayerAsset=true) const
bool HasExternalContent () const
virtual bool ActorTypeSupportsDataLayer () const
virtual bool ActorTypeSupportsExternalDataLayer () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool SupportsDataLayer () const
bool ContainsDataLayer (const FActorDataLayer &ActorDataLayer) const
bool ContainsDataLayer (const UDataLayerAsset *DataLayerAsset) const
bool ContainsDataLayer (const UDataLayerInstance *DataLayerInstance) const
TArray< FActorDataLayer > const & GetActorDataLayers () const
TArray< const UDataLayerInstance * > GetDataLayerInstances (const AWorldDataLayers *WorldDataLayers) const
TArray< const UDataLayerInstance * > GetDataLayerInstances () const
bool HasValidDataLayers () const
bool HasDataLayers () const
bool HasContentBundle () const
const UExternalDataLayerAsset * GetExternalDataLayerAsset () const
const FTransform & GetTransform () const
Get the actor-to-world transform.
const FTransform & ActorToWorld () const
Get the local-to-world transform of the RootComponent.
FVector K2_GetActorLocation () const
Returns the location of the RootComponent of this Actor.
bool K2_SetActorLocation (FVector NewLocation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Move the Actor to the specified location.
FRotator K2_GetActorRotation () const
Returns rotation of the RootComponent of this Actor.
FVector GetActorForwardVector () const
Get the forward (X) vector (length 1.0) from this Actor, in world space.
FVector GetActorUpVector () const
Get the up (Z) vector (length 1.0) from this Actor, in world space.
FVector GetActorRightVector () const
Get the right (Y) vector (length 1.0) from this Actor, in world space.
virtual void GetActorBounds (bool bOnlyCollidingComponents, FVector &Origin, FVector &BoxExtent, bool bIncludeFromChildActors=false) const
Returns the bounding box of all components that make up this Actor (excluding ChildActorComponents).
USceneComponent * K2_GetRootComponent () const
Returns the RootComponent of this Actor.
virtual FVector GetVelocity () const
Returns velocity (in cm/s (Unreal Units/second) of the rootcomponent if it is either using physics or has an associated MovementComponent.
bool SetActorLocation (const FVector &NewLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
Move the actor instantly to the specified location.
bool K2_SetActorRotation (FRotator NewRotation, bool bTeleportPhysics)
Set the Actor's rotation instantly to the specified rotation.
bool SetActorRotation (FRotator NewRotation, ETeleportType Teleport=ETeleportType::None)
Set the Actor's rotation instantly to the specified rotation.
bool SetActorRotation (const FQuat &NewRotation, ETeleportType Teleport=ETeleportType::None)
bool K2_SetActorLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Move the actor instantly to the specified location and rotation.
bool SetActorLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
Move the actor instantly to the specified location and rotation.
bool SetActorLocationAndRotation (FVector NewLocation, const FQuat &NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetActorScale3D (FVector NewScale3D)
Set the Actor's world-space scale.
FVector GetActorScale3D () const
Returns the Actor's world-space scale.
float GetDistanceTo (const AActor *OtherActor) const
Returns the distance from this Actor to OtherActor.
float GetSquaredDistanceTo (const AActor *OtherActor) const
Returns the squared distance from this Actor to OtherActor.
float GetHorizontalDistanceTo (const AActor *OtherActor) const
Returns the distance from this Actor to OtherActor, ignoring Z.
float GetSquaredHorizontalDistanceTo (const AActor *OtherActor) const
Returns the squared distance from this Actor to OtherActor, ignoring Z.
float GetVerticalDistanceTo (const AActor *OtherActor) const
Returns the distance from this Actor to OtherActor, ignoring XY.
float GetDotProductTo (const AActor *OtherActor) const
Returns the dot product from this Actor to OtherActor.
float GetHorizontalDotProductTo (const AActor *OtherActor) const
Returns the dot product from this Actor to OtherActor, ignoring Z.
void K2_AddActorWorldOffset (FVector DeltaLocation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the location of this actor in world space.
void AddActorWorldOffset (FVector DeltaLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorWorldRotation (FRotator DeltaRotation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the rotation of this actor in world space.
void AddActorWorldRotation (FRotator DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddActorWorldRotation (const FQuat &DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorWorldTransform (const FTransform &DeltaTransform, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the transform of this actor in world space.
void AddActorWorldTransform (const FTransform &DeltaTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorWorldTransformKeepScale (const FTransform &DeltaTransform, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the transform of this actor in world space.
void AddActorWorldTransformKeepScale (const FTransform &DeltaTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
bool K2_SetActorTransform (const FTransform &NewTransform, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Set the Actors transform to the specified one.
bool SetActorTransform (const FTransform &NewTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorLocalOffset (FVector DeltaLocation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the location of this component in its local reference frame.
void AddActorLocalOffset (FVector DeltaLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorLocalRotation (FRotator DeltaRotation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the rotation of this component in its local reference frame.
void AddActorLocalRotation (FRotator DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddActorLocalRotation (const FQuat &DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_AddActorLocalTransform (const FTransform &NewTransform, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Adds a delta to the transform of this component in its local reference frame.
void AddActorLocalTransform (const FTransform &NewTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_SetActorRelativeLocation (FVector NewRelativeLocation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Set the actor's RootComponent to the specified relative location.
void SetActorRelativeLocation (FVector NewRelativeLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_SetActorRelativeRotation (FRotator NewRelativeRotation, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Set the actor's RootComponent to the specified relative rotation.
void SetActorRelativeRotation (FRotator NewRelativeRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetActorRelativeRotation (const FQuat &NewRelativeRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void K2_SetActorRelativeTransform (const FTransform &NewRelativeTransform, bool bSweep, FHitResult &SweepHitResult, bool bTeleport)
Set the actor's RootComponent to the specified relative transform.
void SetActorRelativeTransform (const FTransform &NewRelativeTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetActorRelativeScale3D (FVector NewRelativeScale)
Set the actor's RootComponent to the specified relative scale 3d.
FVector GetActorRelativeScale3D () const
Return the actor's relative scale 3d.
void MarkNeedsRecomputeBoundsOnceForGame ()
Marks the bounds of all SceneComponents attached to this actor which have bComputeBoundsOnceForGame as needing to be recomputed the next time UpdateBounds is called.
virtual void SetActorHiddenInGame (bool bNewHidden)
Sets the actor to be hidden in the game.
void SetActorEnableCollision (bool bNewActorEnableCollision)
Allows enabling/disabling collision for the whole actor.
bool GetActorEnableCollision () const
Get current state of collision for the whole actor.
virtual void K2_DestroyActor ()
Destroy the actor.
bool HasAuthority () const
Returns whether this actor has network authority.
UActorComponent * AddComponent (FName TemplateName, bool bManualAttachment, const FTransform &RelativeTransform, const UObject *ComponentTemplateContext, bool bDeferredFinish=false)
Creates a new component and assigns ownership to the Actor this is called for.
UActorComponent * AddComponentByClass (UPARAM(meta=(AllowAbstract="false")) TSubclassOf< UActorComponent > Class, bool bManualAttachment, const FTransform &RelativeTransform, bool bDeferredFinish)
Creates a new component and assigns ownership to the Actor this is called for.
void FinishAddComponent (UActorComponent *Component, bool bManualAttachment, const FTransform &RelativeTransform)
Completes the creation of a new actor component.
void K2_AttachRootComponentTo (USceneComponent *InParent, FName InSocketName=NAME_None, EAttachLocation::Type AttachLocationType=EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies=true)
DEPRECATED - Use AttachToComponent() instead.
bool K2_AttachToComponent (USceneComponent *Parent, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule, bool bWeldSimulatedBodies)
Attaches the RootComponent of this Actor to the supplied component, optionally at a named socket.
bool AttachToComponent (USceneComponent *Parent, const FAttachmentTransformRules &AttachmentRules, FName SocketName=NAME_None)
Attaches the RootComponent of this Actor to the supplied component, optionally at a named socket.
void K2_AttachRootComponentToActor (AActor *InParentActor, FName InSocketName=NAME_None, EAttachLocation::Type AttachLocationType=EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies=true)
DEPRECATED - Use AttachToActor() instead.
bool AttachToActor (AActor *ParentActor, const FAttachmentTransformRules &AttachmentRules, FName SocketName=NAME_None)
Attaches the RootComponent of this Actor to the RootComponent of the supplied actor, optionally at a named socket.
bool K2_AttachToActor (AActor *ParentActor, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule, bool bWeldSimulatedBodies)
Attaches the RootComponent of this Actor to the supplied actor, optionally at a named socket.
void DetachRootComponentFromParent (bool bMaintainWorldPosition=true)
DEPRECATED - Use DetachFromActor() instead.
void K2_DetachFromActor (EDetachmentRule LocationRule=EDetachmentRule::KeepRelative, EDetachmentRule RotationRule=EDetachmentRule::KeepRelative, EDetachmentRule ScaleRule=EDetachmentRule::KeepRelative)
Detaches the RootComponent of this Actor from any SceneComponent it is currently attached to.
void DetachFromActor (const FDetachmentTransformRules &DetachmentRules)
Detaches the RootComponent of this Actor from any SceneComponent it is currently attached to.
void DetachAllSceneComponents (class USceneComponent *InParentComponent, const FDetachmentTransformRules &DetachmentRules)
Detaches all SceneComponents in this Actor from the supplied parent SceneComponent.
bool ActorHasTag (FName Tag) const
See if this actor's Tags array contains the supplied name tag.
float GetActorTimeDilation () const
Get ActorTimeDilation - this can be used for input control or speed control for slomo.
float GetActorTimeDilation (const UWorld &ActorWorld) const
More efficient version that takes the Actor's current world.
virtual void AddTickPrerequisiteActor (AActor *PrerequisiteActor)
Make this actor tick after PrerequisiteActor.
virtual void AddTickPrerequisiteComponent (UActorComponent *PrerequisiteComponent)
Make this actor tick after PrerequisiteComponent.
virtual void RemoveTickPrerequisiteActor (AActor *PrerequisiteActor)
Remove tick dependency on PrerequisiteActor.
virtual void RemoveTickPrerequisiteComponent (UActorComponent *PrerequisiteComponent)
Remove tick dependency on PrerequisiteComponent.
bool GetTickableWhenPaused ()
Gets whether this actor can tick when paused.
void SetTickableWhenPaused (bool bTickableWhenPaused)
Sets whether this actor can tick when paused.
float GetGameTimeSinceCreation () const
The number of seconds (in game time) since this Actor was created, relative to Get Game Time In Seconds.
void DispatchBeginPlay (bool bFromLevelStreaming=false)
Initiate a begin play call on this Actor, will handle calling in the correct order.
bool IsActorInitialized () const
Returns whether an actor has been initialized for gameplay.
bool IsActorBeginningPlay () const
Returns whether an actor is in the process of beginning play.
bool HasActorBegunPlay () const
Returns whether an actor has had BeginPlay called on it (and not subsequently had EndPlay called)
bool IsActorBeginningPlayFromLevelStreaming () const
Returns whether an actor is beginning play in DispatchBeginPlay() during level streaming (which includes initial level load).
bool IsActorBeingDestroyed () const
Returns true if this actor is currently being destroyed, some gameplay events may be unsafe.
bool HasActorRegisteredAllComponents () const
Returns bHasRegisteredAllComponents which indicates whether this actor has registered all their components without unregisatering all of them them.
void SetHasActorRegisteredAllComponents ()
Sets bHasRegisteredAllComponents true.
void ReceiveAnyDamage (float Damage, const class UDamageType *DamageType, class AController *InstigatedBy, AActor *DamageCauser)
Event when this actor takes ANY damage.
void ReceiveRadialDamage (float DamageReceived, const class UDamageType *DamageType, FVector Origin, const struct FHitResult &HitInfo, class AController *InstigatedBy, AActor *DamageCauser)
Event when this actor takes RADIAL damage.
void ReceivePointDamage (float Damage, const class UDamageType *DamageType, FVector HitLocation, FVector HitNormal, class UPrimitiveComponent *HitComponent, FName BoneName, FVector ShotFromDirection, class AController *InstigatedBy, AActor *DamageCauser, const FHitResult &HitInfo)
Event when this actor takes POINT damage.
void ReceiveTick (float DeltaSeconds)
Event called every frame, if ticking is enabled.
void ReceiveAsyncPhysicsTick (float DeltaSeconds, float SimSeconds)
Event called every physics tick if bAsyncPhysicsTickEnabled is true.
virtual void NotifyActorBeginOverlap (AActor *OtherActor)
Event when this actor overlaps another actor, for example a player walking into a trigger.
void ReceiveActorBeginOverlap (AActor *OtherActor)
Event when this actor overlaps another actor, for example a player walking into a trigger.
virtual void NotifyActorEndOverlap (AActor *OtherActor)
Event when an actor no longer overlaps another actor, and they have separated.
void ReceiveActorEndOverlap (AActor *OtherActor)
Event when an actor no longer overlaps another actor, and they have separated.
virtual void NotifyActorBeginCursorOver ()
Event when this actor has the mouse moved over it with the clickable interface.
void ReceiveActorBeginCursorOver ()
Event when this actor has the mouse moved over it with the clickable interface.
virtual void NotifyActorEndCursorOver ()
Event when this actor has the mouse moved off of it with the clickable interface.
void ReceiveActorEndCursorOver ()
Event when this actor has the mouse moved off of it with the clickable interface.
virtual void NotifyActorOnClicked (FKey ButtonPressed=EKeys::LeftMouseButton)
Event when this actor is clicked by the mouse when using the clickable interface.
void ReceiveActorOnClicked (FKey ButtonPressed=EKeys::LeftMouseButton)
Event when this actor is clicked by the mouse when using the clickable interface.
virtual void NotifyActorOnReleased (FKey ButtonReleased=EKeys::LeftMouseButton)
Event when this actor is under the mouse when left mouse button is released while using the clickable interface.
void ReceiveActorOnReleased (FKey ButtonReleased=EKeys::LeftMouseButton)
Event when this actor is under the mouse when left mouse button is released while using the clickable interface.
virtual void NotifyActorOnInputTouchBegin (const ETouchIndex::Type FingerIndex)
Event when this actor is touched when click events are enabled.
void ReceiveActorOnInputTouchBegin (const ETouchIndex::Type FingerIndex)
Event when this actor is touched when click events are enabled.
virtual void NotifyActorOnInputTouchEnd (const ETouchIndex::Type FingerIndex)
Event when this actor is under the finger when untouched when click events are enabled.
void ReceiveActorOnInputTouchEnd (const ETouchIndex::Type FingerIndex)
Event when this actor is under the finger when untouched when click events are enabled.
virtual void NotifyActorOnInputTouchEnter (const ETouchIndex::Type FingerIndex)
Event when this actor has a finger moved over it with the clickable interface.
void ReceiveActorOnInputTouchEnter (const ETouchIndex::Type FingerIndex)
Event when this actor has a finger moved over it with the clickable interface.
virtual void NotifyActorOnInputTouchLeave (const ETouchIndex::Type FingerIndex)
Event when this actor has a finger moved off of it with the clickable interface.
void ReceiveActorOnInputTouchLeave (const ETouchIndex::Type FingerIndex)
Event when this actor has a finger moved off of it with the clickable interface.
void GetOverlappingActors (TArray< AActor * > &OverlappingActors, TSubclassOf< AActor > ClassFilter=nullptr) const
Returns list of actors this actor is overlapping (any component overlapping any component).
void GetOverlappingActors (TSet< AActor * > &OverlappingActors, TSubclassOf< AActor > ClassFilter=nullptr) const
Returns set of actors this actor is overlapping (any component overlapping any component).
void GetOverlappingComponents (TArray< UPrimitiveComponent * > &OverlappingComponents) const
Returns list of components this actor is overlapping.
void GetOverlappingComponents (TSet< UPrimitiveComponent * > &OverlappingComponents) const
Returns set of components this actor is overlapping.
virtual void NotifyHit (class UPrimitiveComponent *MyComp, AActor *Other, class UPrimitiveComponent *OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult &Hit)
Event when this actor bumps into a blocking object, or blocks another actor that bumps into it.
void ReceiveHit (class UPrimitiveComponent *MyComp, AActor *Other, class UPrimitiveComponent *OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult &Hit)
Event when this actor bumps into a blocking object, or blocks another actor that bumps into it.
virtual void SetLifeSpan (float InLifespan)
Set the lifespan of this actor.
virtual float GetLifeSpan () const
Get the remaining lifespan of this actor.
void UserConstructionScript ()
Construction script, the place to spawn components and do other setup.
bool Destroy (bool bNetForce=false, bool bShouldModifyLevel=true)
Destroy this actor.
void ReceiveDestroyed ()
Called when the actor has been explicitly destroyed.
virtual bool CheckDefaultSubobjectsInternal () const override
virtual void PostInitProperties () override
virtual void ProcessEvent (UFunction *Function, void *Parameters) override
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack) override
virtual bool CallRemoteFunction (UFunction *Function, void *Parameters, FOutParmRec *OutParms, FFrame *Stack) override
virtual void Serialize (FArchive &Ar) override
virtual void PostLoad () override
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph) override
virtual void BeginDestroy () override
virtual bool IsReadyForFinishDestroy () override
virtual bool Rename (const TCHAR *NewName=nullptr, UObject *NewOuter=nullptr, ERenameFlags Flags=REN_None) override
virtual void PostRename (UObject *OldOuter, const FName OldName) override
virtual bool CanBeInCluster () const override
virtual bool IsEditorOnly () const override
virtual bool IsEditorOnlyLoadedInPIE () const
virtual bool IsRuntimeOnly () const
virtual bool IsAsset () const override
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext) override
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext) override
virtual void PreSave (FObjectPreSaveContext ObjectSaveContext) override
bool IsMainPackageActor () const
Used to check if Actor is the main actor of a package (currently Child Actors are not)
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
virtual void GetAssetRegistryTags (TArray< FAssetRegistryTag > &OutTags) const override
virtual bool NeedsLoadForTargetPlatform (const ITargetPlatform *TargetPlatform) const
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
virtual bool CanEditChange (const FProperty *InProperty) const
virtual void PreEditUndo () override
virtual void PostEditUndo () override
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation) override
virtual void PostEditImport () override
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent) override
virtual bool IsSelectedInEditor () const override
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS void PopulatePIEDuplicationSeed (FDuplicationSeedInterface &DupSeed)
Populate the duplication seed when duplicating the actor for PIE.
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool IsDefaultPreviewEnabled () const
Defines if preview should be shown when you select an actor, but none of its children.
virtual bool IsUserManaged () const
Used to know if actor supports some editor operations.
virtual bool CanDeleteSelectedActor (FText &OutReason) const
When selected can this actor be deleted?
virtual bool CanReplaceSelectedActor (FText &OutReason) const
When selected can this actor be replaced.
virtual bool SupportsExternalPackaging () const
Does this actor supports external packaging?
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const override
bool ReregisterComponentsWhenModified () const
Returns true if the component is allowed to re-register its components when modified.
virtual void PostEditMove (bool bFinished)
Called after an actor has been moved in the editor.
virtual void PreRenameFromRoot (const FWorldRenameFromRootContext &RenameContext)
virtual void PostRenameFromRoot (const FWorldRenameFromRootContext &RenameContext)
virtual void PreDuplicateFromRoot (FObjectDuplicationParameters &DupParams)
virtual void PreSaveFromRoot (FObjectPreSaveRootContext ObjectSaveContext)
virtual void PostSaveFromRoot (FObjectPostSaveRootContext ObjectSaveContext)
virtual bool CanEditChangeComponent (const UActorComponent *Component, const FProperty *InProperty) const
virtual void GatherCurrentMovement ()
Fills ReplicatedMovement property.
bool IsOwnedBy (const AActor *TestOwner) const
See if this actor is owned by TestOwner.
USceneComponent * GetRootComponent () const
Returns this actor's root component.
virtual USceneComponent * GetDefaultAttachComponent () const
Returns this actor's default attachment component for attaching children to.
bool SetRootComponent (USceneComponent *NewRootComponent)
Sets root component to be the specified component.
const FTransform & GetActorTransform () const
Returns the transform of the RootComponent of this Actor.
FVector GetActorLocation () const
Returns the location of the RootComponent of this Actor.
FRotator GetActorRotation () const
Returns the rotation of the RootComponent of this Actor.
FVector GetActorScale () const
Returns the scale of the RootComponent of this Actor.
FQuat GetActorQuat () const
Returns the quaternion of the RootComponent of this Actor.
void SetPivotOffset (const FVector &InPivotOffset)
Sets the local space offset added to the actor's pivot as used by the editor.
FVector GetPivotOffset () const
Gets the local space offset added to the actor's pivot as used by the editor.
virtual void GetStreamingBounds (FBox &OutRuntimeBounds, FBox &OutEditorBounds) const
Returns the bounding boxes of all components that make up this Actor for loading at runtime and editor.
FBox GetStreamingBounds () const
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift)
Called by owning level to shift an actor location and all relevant data structures by specified delta.
virtual bool IsLevelBoundsRelevant () const
Indicates whether this actor should participate in level bounds calculations.
virtual bool IsHLODRelevant () const
Indicates whether this actor contributes to the HLOD generation.
virtual bool HasHLODRelevantComponents () const
Indicates whether this actor can provide HLOD relevant components.
virtual TArray< UActorComponent * > GetHLODRelevantComponents () const
Return the list of components to use when building the HLOD representation of this actor.
void SetLODParent (class UPrimitiveComponent *InLODParent, float InParentDrawDistance)
Set LOD Parent component for all of our components, normally associated with an ALODActor.
virtual void EditorApplyTranslation (const FVector &DeltaTranslation, bool bAltDown, bool bShiftDown, bool bCtrlDown)
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
virtual void EditorApplyRotation (const FRotator &DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown)
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
virtual void EditorApplyScale (const FVector &DeltaScale, const FVector *PivotLocation, bool bAltDown, bool bShiftDown, bool bCtrlDown)
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
virtual void EditorApplyMirror (const FVector &MirrorScale, const FVector &PivotLocation)
Called by MirrorActors to perform a mirroring operation on the actor.
virtual void EditorGetUnderlyingActors (TSet< AActor * > &OutUnderlyingActors) const
Get underlying actors.
bool IsHiddenEdAtStartup () const
Returns true if the actor is hidden upon editor startup/by default, false if it is not.
virtual bool IsHiddenEd () const
Returns true if this actor is hidden in the editor viewports, also checking temporary flags.
virtual void SetIsTemporarilyHiddenInEditor (bool bIsHidden)
Explicitly sets whether or not this actor is hidden in the editor for the duration of the current editor session.
virtual bool SetIsHiddenEdLayer (bool bIsHiddenEdLayer)
Changes bHiddenEdLayer flag and returns true if flag changed.
virtual bool SupportsLayers () const
Returns true if the actor supports modifications to its Layers property.
bool IsForceExternalActorLevelReferenceForPIE () const
Returns if level should keep a reference to the external actor for PIE (used for always loaded actors).
void SetForceExternalActorLevelReferenceForPIE (bool bValue)
bool GetIsSpatiallyLoaded () const
Returns true if this actor is spatially loaded.
void SetIsSpatiallyLoaded (bool bInIsSpatiallyLoaded)
Set if this actor should be spatially loaded or not.
virtual bool CanChangeIsSpatiallyLoadedFlag () const
Returns true if this actor allows changing the spatially loaded flag.
bool IsTemporarilyHiddenInEditor (bool bIncludeParent=false) const
Returns whether or not this actor was explicitly hidden in the editor for the duration of the current editor session.
bool IsEditable () const
Returns true if this actor is allowed to be displayed, selected and manipulated by the editor.
virtual bool IsSelectable () const
Returns true if this actor can EVER be selected in a level in the editor.
virtual bool IsListedInSceneOutliner () const
Returns true if this actor should be shown in the scene outliner.
virtual bool EditorCanAttachTo (const AActor *InParent, FText &OutReason) const
Returns true if this actor is allowed to be attached to the given actor.
virtual bool EditorCanAttachFrom (const AActor *InChild, FText &OutReason) const
Returns true if this actor is allowed to be attached from the given actor.
virtual bool EditorCanDetachFrom (const AActor *InParent, FText &OutReason) const
Returns true if this actor is allowed to be detached from the given actor.
virtual AActor * GetSceneOutlinerParent () const
Returns the actor attachement parent that should be used in the scene outliner.
virtual UPackage * GetSceneOutlinerPackage () const
Returns the actor package that should be used in the scene outliner.
virtual UPackage * GetSceneOutlinerItemPackage () const
Returns the actor item package that should be used in the scene outliner.
virtual UPackage * GetSceneOutlinerTopParentPackage () const
Returns the actor top parent package that should be used in the scene outliner.
virtual bool ShouldExport ()
Called before editor copy, true allow export.
virtual bool ShouldImport (FString *ActorPropString, bool IsMovingLevel)
Called before editor paste, true allow import.
virtual bool ShouldImport (FStringView ActorPropString, bool IsMovingLevel)
Called before editor paste, true allow import.
virtual void EditorKeyPressed (FKey Key, EInputEvent Event)
Called by InputKey when an unhandled key is pressed with a selected actor.
virtual void EditorReplacedActor (AActor *OldActor)
Called by ReplaceSelectedActors to allow a new actor to copy properties from an old actor when it is replaced.
virtual void CheckForErrors ()
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
virtual void CheckForDeprecated ()
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
virtual FString GetDefaultActorLabel () const
Returns this actor's default label (does not include any numeric suffix).
const FString & GetActorLabel (bool bCreateIfNone=true) const
Returns this actor's current label.
void SetActorLabel (const FString &NewActorLabel, bool bMarkDirty=true)
Assigns a new label to this actor.
void ClearActorLabel ()
Advanced - clear the actor label.
void SetInitialActorLabel (FStringView InitialLabel)
Advanced - only to be called by UWorld::SpawnActor to set an initial label for this actor.
virtual bool IsActorLabelEditable () const
Returns if this actor's current label is editable.
FName GetFolderPath () const
Returns this actor's folder path.
FGuid GetFolderGuid (bool bDirectAccess=false) const
FFolder::FRootObject GetFolderRootObject () const
Returns the actor's folder root object.
void FixupActorFolder ()
Detects and fixes invalid actor folder.
bool CreateOrUpdateActorFolder ()
Creates or updates actor's folder object if necessary.
FFolder GetFolder () const
Returns a FFolder that contains the actor folder path and its folder root object.
void SetFolderPath (const FName &NewFolderPath)
Assigns a new folder to this actor.
void SetFolderPath_Recursively (const FName &NewFolderPath)
Assigns a new folder to this actor and any attached children.
virtual bool GetReferencedContentObjects (TArray< UObject * > &Objects) const
Used by the "Sync to Content Browser" right-click menu option in the editor.
virtual bool GetSoftReferencedContentObjects (TArray< FSoftObjectPath > &SoftObjects) const
Similar to GetReferencedContentObjects, but for soft referenced objects.
virtual bool OpenAssetEditor ()
Used to allow actor classes to open an actor specific editor.
const int32 GetNumUncachedStaticLightingInteractions () const
Returns NumUncachedStaticLightingInteractions for this actor.
virtual FName GetCustomIconName () const
Returns a custom brush icon name to use in place of the automatic class icon where actors are represented via 2d icons in the editor (e.g scene outliner and menus)
bool ShouldCookOptimizedBPComponentData () const
Returns whether or not to cook optimized Blueprint component data for this actor.
void SetBrowseToAssetOverride (const FString &PackageName)
Sets metadata on the Actor that allows it to point to a different asset than its source when browsing in the Content Browser.
const FString & GetBrowseToAssetOverride () const
Gets metadata on the Actor that says which package to show in the Content Browser when browsing to it, or an empty string if there is no override.
virtual float GetNetPriority (const FVector &ViewPos, const FVector &ViewDir, class AActor *Viewer, AActor *ViewTarget, UActorChannel *InChannel, float Time, bool bLowBandwidth)
Function used to prioritize actors when deciding which to replicate.
virtual float GetReplayPriority (const FVector &ViewPos, const FVector &ViewDir, class AActor *Viewer, AActor *ViewTarget, UActorChannel *const InChannel, float Time)
Similar to GetNetPriority, but will only be used for prioritizing actors while recording a replay.
virtual bool GetNetDormancy (const FVector &ViewPos, const FVector &ViewDir, class AActor *Viewer, AActor *ViewTarget, UActorChannel *InChannel, float Time, bool bLowBandwidth)
Returns true if the actor should be dormant for a specific net connection.
virtual void OnActorChannelOpen (class FInBunch &InBunch, class UNetConnection *Connection)
Allows for a specific response from the actor when the actor channel is opened (client side)
virtual bool UseShortConnectTimeout () const
Used by the net connection to determine if a net owning actor should switch to using the shortened timeout value.
virtual void OnSerializeNewActor (class FOutBunch &OutBunch)
SerializeNewActor has just been called on the actor before network replication (server side)
virtual void OnNetCleanup (class UNetConnection *Connection)
Handles cleaning up the associated Actor when killing the connection.
void ExchangeNetRoles (bool bRemoteOwner)
Swaps Role and RemoteRole if client.
void SwapRoles ()
Calls this to swap the Role and RemoteRole.
void RegisterAllActorTickFunctions (bool bRegister, bool bDoComponents)
When called, will call the virtual call chain to register all of the tick functions for both the actor and optionally all components Do not override this function or make it virtual.
virtual void SetActorTickEnabled (bool bEnabled)
Set this actor's tick functions to be enabled or disabled.
bool IsActorTickEnabled () const
Returns whether this actor has tick enabled or not.
void SetActorTickInterval (float TickInterval)
Sets the tick interval of this actor's primary tick function.
float GetActorTickInterval () const
Returns the tick interval of this actor's primary tick function.
virtual void TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction &ThisTickFunction)
Dispatches the once-per frame Tick() function for this actor.
virtual void AsyncPhysicsTickActor (float DeltaTime, float SimTime)
Override this function to implement custom logic to be executed every physics step.
virtual void PostActorCreated ()
Called when an actor is done spawning into the world (from UWorld::SpawnActor), both in the editor and during gameplay For actors with a root component, the location and rotation will have already been set.
virtual void LifeSpanExpired ()
Called when the lifespan of an actor expires (if it has one).
virtual void PreNetReceive () override
Always called immediately before properties are received from the remote.
virtual void PostNetReceive () override
Always called immediately after properties are received from the remote.
virtual void PostNetReceiveRole ()
Always called immediately after a new Role is received from the remote.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsSupportedForNetworking () const override
IsSupportedForNetworking means an object can be referenced over the network.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList) override
Returns a list of sub-objects that have stable names for networking.
virtual void PostNetInit ()
Always called immediately after spawning and reading in replicated properties.
virtual void OnRep_ReplicatedMovement ()
ReplicatedMovement struct replication event.
virtual void PostNetReceiveLocationAndRotation ()
Update location and rotation from ReplicatedMovement.
virtual void PostNetReceiveVelocity (const FVector &NewVelocity)
Update velocity - typically from ReplicatedMovement, not called for simulated physics!
virtual void PostNetReceivePhysicState ()
Update and smooth simulated physic state, replaces PostNetReceiveLocation() and PostNetReceiveVelocity()
void SetFakeNetPhysicsState (bool bShouldSleep)
Set the current state as a faked networked physics state for physics replication Limited for use with actors using EPhysicsReplicationMode::PredictiveInterpolation only.
virtual void SetOwner (AActor *NewOwner)
Set the owner of this Actor, used primarily for network replication.
AActor * GetOwner () const
Get the owner of this Actor, used primarily for network replication.
template<class T>
T * GetOwner () const
Templated version of GetOwner(), will return nullptr if cast fails.
virtual bool CheckStillInWorld ()
This will check to see if the Actor is still in the world.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const override
Returns Valid if this object has data validation rules set up for it and the data for this object is valid.
void ClearComponentOverlaps ()
Dispatch all EndOverlap for all of the Actor's PrimitiveComponents.
void UpdateOverlaps (bool bDoNotifies=true)
Queries world and updates overlap detection state for this actor.
bool IsOverlappingActor (const AActor *Other) const
Check whether any component of this Actor is overlapping any component of another Actor.
bool IsRootComponentStatic () const
See if the root component has ModifyFrequency of MF_Static.
bool IsRootComponentStationary () const
See if the root component has Mobility of EComponentMobility::Stationary.
bool IsRootComponentMovable () const
See if the root component has Mobility of EComponentMobility::Movable.
virtual APhysicsVolume * GetPhysicsVolume () const
Get the physics volume that is currently applied to this Actor (there can only ever be one)
bool CanEverTick () const
Accessor for the value of bCanEverTick.
virtual bool ShouldTickIfViewportsOnly () const
If true, actor is ticked even if TickType==LEVELTICK_ViewportsOnly.
virtual bool IsNetRelevantFor (const AActor *RealViewer, const AActor *ViewTarget, const FVector &SrcLocation) const
Checks to see if this actor is relevant for a specific network connection.
virtual bool IsReplayRelevantFor (const AActor *RealViewer, const AActor *ViewTarget, const FVector &SrcLocation, const float CullDistanceSquared) const
Checks to see if this actor is relevant for a recorded replay.
virtual bool IsRelevancyOwnerFor (const AActor *ReplicatedActor, const AActor *ActorOwner, const AActor *ConnectionActor) const
Check if this actor is the owner when doing relevancy checks for actors marked bOnlyRelevantToOwner.
void PostSpawnInitialize (FTransform const &SpawnTransform, AActor *InOwner, APawn *InInstigator, bool bRemoteOwned, bool bNoFail, bool bDeferConstruction, ESpawnActorScaleMethod TransformScaleMethod=ESpawnActorScaleMethod::MultiplyWithRoot)
Called after the actor is spawned in the world.
void FinishSpawning (const FTransform &Transform, bool bIsDefaultTransform=false, const FComponentInstanceDataCache *InstanceDataCache=nullptr, ESpawnActorScaleMethod TransformScaleMethod=ESpawnActorScaleMethod::OverrideRootScale)
Called to finish the spawning process, generally in the case of deferred spawning.
void PostActorConstruction ()
Called after the actor has run its construction.
virtual void PreInitializeComponents ()
Called right before components are initialized, only called during gameplay.
virtual void PostInitializeComponents ()
Allow actors to initialize themselves on the C++ side after all of their components have been initialized, only called during gameplay.
virtual void DispatchPhysicsCollisionHit (const struct FRigidBodyCollisionInfo &MyInfo, const struct FRigidBodyCollisionInfo &OtherInfo, const FCollisionImpactData &RigidCollisionData)
Dispatches ReceiveHit virtual and OnComponentHit delegate.
virtual const AActor * GetNetOwner () const
Return the actor responsible for replication, if any.
virtual class UPlayer * GetNetOwningPlayer ()
Return the owning UPlayer (if any) of this actor if it's role is ROLE_Authority.
virtual class UPlayer * GetNetOwningPlayerAnyRole ()
Return the owning UPlayer (if any) of this actor, regardless of it's current role.
virtual class UNetConnection * GetNetConnection () const
Get the owning connection used for communicating between client/server.
virtual bool DestroyNetworkActorHandled ()
Called by DestroyActor(), gives actors a chance to op out of actor destruction Used by network code to have the net connection timeout/cleanup first.
ENetMode GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this actor.
bool IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
class UNetDriver * GetNetDriver () const
Returns the net driver that this actor is bound to, may be null.
void SetNetDormancy (ENetDormancy NewDormancy)
Puts actor in dormant networking state.
void FlushNetDormancy ()
Forces dormant actor to replicate but doesn't change NetDormancy state (i.e., they will go dormant again if left dormant)
void ForcePropertyCompare ()
Forces properties on this actor to do a compare for one frame (rather than share shadow state)
bool IsChildActor () const
Returns whether this Actor was spawned by a child actor component.
virtual bool IsSelectionParentOfAttachedActors () const
Returns whether this actor can select its attached actors.
virtual bool IsSelectionChild () const
Returns whether this Actor is part of another's actor selection.
virtual AActor * GetSelectionParent () const
Returns immediate selection parent.
virtual AActor * GetRootSelectionParent () const
Returns top most selection parent.
virtual bool SupportsSubRootSelection () const
Returns true if actor can be selected as a sub selection of its root selection parent.
bool IsActorOrSelectionParentSelected () const
Returns if actor or selection parent is selected.
virtual void PushSelectionToProxies ()
Push Selection to actor.
virtual void PushLevelInstanceEditingStateToProxies (bool bInEditingState)
Push Foundation Editing state to primitive scene proxy.
void GetAllChildActors (TArray< AActor * > &ChildActors, bool bIncludeDescendants=true) const
Returns a list of all actors spawned by our Child Actor Components, including children of children.
UChildActorComponent * GetParentComponent () const
If this Actor was created by a Child Actor Component returns that Child Actor Component.
AActor * GetParentActor () const
If this Actor was created by a Child Actor Component returns the Actor that owns that Child Actor Component.
virtual void RegisterAllComponents ()
Ensure that all the components in the Components array are registered.
virtual void PreRegisterAllComponents ()
Called before all the components in the Components array are registered, called both in editor and during gameplay.
virtual void PostRegisterAllComponents ()
Called after all the components in the Components array are registered, called both in editor and during gameplay.
bool HasDeferredComponentRegistration () const
Returns true if Actor has deferred the RegisterAllComponents() call at spawn time (e.g.
bool HasValidRootComponent () const
Returns true if Actor has a registered root component.
virtual void UnregisterAllComponents (bool bForReregister=false)
Unregister all currently registered components.
virtual void PostUnregisterAllComponents ()
Called after all currently registered components are cleared.
virtual void ReregisterAllComponents ()
Will reregister all components on this actor.
void HandleRegisterComponentWithWorld (UActorComponent *Component)
Finish initializing the component and register tick functions and beginplay if it's the proper time to do so.
bool IncrementalRegisterComponents (int32 NumComponentsToRegister, FRegisterComponentContext *Context=nullptr)
Incrementally registers components associated with this actor, used during level streaming.
void MarkComponentsRenderStateDirty ()
Flags all component's render state as dirty.
void UpdateComponentTransforms ()
Update all components transforms.
void UpdateComponentVisibility ()
Update all components visibility state.
void InitializeComponents ()
Iterate over components array and call InitializeComponent, which happens once per actor.
void UninitializeComponents ()
Iterate over components array and call UninitializeComponent, called when the actor is ending play.
void DrawDebugComponents (FColor const &BaseColor=FColor::White) const
Debug rendering to visualize the component tree for this actor.
virtual void MarkComponentsAsPendingKill ()
virtual void MarkComponentsAsGarbage (bool bModify=true)
Called to mark all components as garbage when the actor is being destroyed.
bool IsPendingKillPending () const
Returns true if this actor has begun the destruction process.
void InvalidateLightingCache ()
Invalidate lighting cache with default options.
virtual void InvalidateLightingCacheDetailed (bool bTranslationOnly)
Invalidates anything produced by the last lighting build.
virtual bool TeleportTo (const FVector &DestLocation, const FRotator &DestRotation, bool bIsATest=false, bool bNoCheck=false)
Used for adding actors to levels or teleporting them to a new location.
bool K2_TeleportTo (FVector DestLocation, FRotator DestRotation)
Teleport this actor to a new location.
virtual void TeleportSucceeded (bool bIsATest)
Called from TeleportTo() when teleport succeeds.
bool ActorLineTraceSingle (struct FHitResult &OutHit, const FVector &Start, const FVector &End, ECollisionChannel TraceChannel, const struct FCollisionQueryParams &Params) const
Trace a ray against the Components of this Actor and return the first blocking hit.
float ActorGetDistanceToCollision (const FVector &Point, ECollisionChannel TraceChannel, FVector &ClosestPointOnCollision, UPrimitiveComponent **OutPrimitiveComponent=nullptr) const
returns Distance to closest Body Instance surface.
bool IsInLevel (const class ULevel *TestLevel) const
Returns true if this actor is contained by TestLevel.
ULevel * GetLevel () const
Return the ULevel that this Actor is part of.
FTransform GetLevelTransform () const
Return the FTransform of the level this actor is a part of.
virtual void ClearCrossLevelReferences ()
Do anything needed to clear out cross level references; Called from ULevel::PreSave.
void RouteEndPlay (const EEndPlayReason::Type EndPlayReason)
Non-virtual function to evaluate which portions of the EndPlay process should be dispatched for each actor.
virtual bool IsBasedOnActor (const AActor *Other) const
Iterates up the movement base chain to see whether or not this Actor is based on the given Actor, defaults to checking attachment.
virtual bool IsAttachedTo (const AActor *Other) const
Iterates up the attachment chain to see whether or not this Actor is attached to the given Actor.
FVector GetPlacementExtent () const
Get the extent used when placing this actor in the editor, used for 'pulling back' hit.
void SeedAllRandomStreams ()
Find all FRandomStream structs in this Actor and generate new random seeds for them.
void ResetPropertiesForConstruction ()
Reset private properties to defaults, and all FRandomStream structs in this Actor, so they will start their sequence of random numbers again.
bool HasNonTrivialUserConstructionScript () const
Returns true if the actor's class has a non trivial user construction script.
virtual void RerunConstructionScripts ()
Rerun construction scripts, destroying all autogenerated components; will attempt to preserve the root component location.
void DebugShowComponentHierarchy (const TCHAR *Info, bool bShowPosition=true)
Debug helper to show the component hierarchy of this actor.
void DebugShowOneComponentHierarchy (USceneComponent *SceneComp, int32 &NestLevel, bool bShowPosition)
Debug helper for showing the component hierarchy of one component.
bool ExecuteConstruction (const FTransform &Transform, const struct FRotationConversionCache *TransformRotationCache, const class FComponentInstanceDataCache *InstanceDataCache, bool bIsDefaultTransform=false, ESpawnActorScaleMethod TransformScaleMethod=ESpawnActorScaleMethod::OverrideRootScale)
Run any construction script for this Actor.
virtual void OnConstruction (const FTransform &Transform)
Called when an instance of this class is placed (in editor) or spawned.
void FinishAndRegisterComponent (UActorComponent *Component)
Helper function to register the specified component, and add it to the serialized components array.
UActorComponent * CreateComponentFromTemplate (UActorComponent *Template, const FName InName=NAME_None)
Util to create a component based on a template.
UActorComponent * CreateComponentFromTemplateData (const struct FBlueprintCookedComponentInstancingData *TemplateData, const FName InName=NAME_None)
void DestroyConstructedComponents ()
Destroys the constructed components.
void UpdateReplicatePhysicsCondition ()
Updates the ReplicatePhysics condition.
void CheckComponentInstanceName (const FName InName)
Checks for and resolve any name conflicts prior to instancing a new Blueprint Component.
AActor * GetAttachParentActor () const
Walk up the attachment chain from RootComponent until we encounter a different actor, and return it.
FName GetAttachParentSocketName () const
Walk up the attachment chain from RootComponent until we encounter a different actor, and return the socket name in the component.
void ForEachAttachedActors (TFunctionRef< bool(class AActor *)> Functor) const
Call a functor for Actors which are attached directly to a component in this actor.
void GetAttachedActors (TArray< AActor * > &OutActors, bool bResetArray=true, bool bRecursivelyIncludeAttachedActors=false) const
Find all Actors which are attached directly to a component in this actor.
void SetTickGroup (ETickingGroup NewTickGroup)
Sets the ticking group for this actor.
virtual void Destroyed ()
Called when this actor is explicitly being destroyed during gameplay or in the editor, not called during level streaming or gameplay ending.
void DispatchBlockingHit (UPrimitiveComponent *MyComp, UPrimitiveComponent *OtherComp, bool bSelfMoved, FHitResult const &Hit)
Call ReceiveHit, as well as delegates on Actor and Component.
virtual void FellOutOfWorld (const class UDamageType &dmgType)
Called when the actor falls out of the world 'safely' (below KillZ and such)
virtual void OutsideWorldBounds ()
Called when the Actor is outside the hard limit on world bounds.
virtual FBox GetComponentsBoundingBox (bool bNonColliding=false, bool bIncludeFromChildActors=false) const
Returns the world space bounding box of all components in this Actor.
virtual FBox CalculateComponentsBoundingBoxInLocalSpace (bool bNonColliding=false, bool bIncludeFromChildActors=false) const
Calculates the actor space bounding box of all components in this Actor.
virtual void GetComponentsBoundingCylinder (float &CollisionRadius, float &CollisionHalfHeight, bool bNonColliding=false, bool bIncludeFromChildActors=false) const
Get half-height/radius of a big axis-aligned cylinder around this actors registered colliding components, or all registered components if bNonColliding is false.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const
Get axis-aligned cylinder around this actor, used for simple collision checks (ie Pawns reaching a destination).
float GetSimpleCollisionRadius () const
Returns the radius of the collision cylinder from GetSimpleCollisionCylinder().
float GetSimpleCollisionHalfHeight () const
Returns the half height of the collision cylinder from GetSimpleCollisionCylinder().
FVector GetSimpleCollisionCylinderExtent () const
Returns collision extents vector for this Actor, based on GetSimpleCollisionCylinder().
virtual bool IsRootComponentCollisionRegistered () const
Returns true if the root component is registered and has collision enabled.
virtual void TornOff ()
Networking - called on client when actor is torn off (bTearOff==true), meaning it's no longer replicated to clients.
virtual ECollisionResponse GetComponentsCollisionResponseToChannel (ECollisionChannel Channel) const
Get Collision Response to the passed in Channel for all components It returns Max of state - i.e.
void DisableComponentsSimulatePhysics ()
Stop all simulation from all components in this actor.
class AWorldSettings * GetWorldSettings () const
Returns the WorldSettings for the World the actor is in If you'd like to know what UWorld this placed actor (not dynamic spawned actor) belong to, use GetTypedOuter<UWorld>()
virtual bool CanBeBaseForCharacter (class APawn *Pawn) const
Return true if the given Pawn can be "based" on this actor (ie walk on it).
virtual float TakeDamage (float DamageAmount, struct FDamageEvent const &DamageEvent, class AController *EventInstigator, AActor *DamageCauser)
Apply damage to this actor.
virtual void BecomeViewTarget (class APlayerController *PC)
Called when this actor becomes the given PlayerController's ViewTarget.
virtual void EndViewTarget (class APlayerController *PC)
Called when this actor is no longer the given PlayerController's ViewTarget.
void K2_OnBecomeViewTarget (class APlayerController *PC)
Event called when this Actor becomes the view target for the given PlayerController.
void K2_OnEndViewTarget (class APlayerController *PC)
Event called when this Actor is no longer the view target for the given PlayerController.
virtual void CalcCamera (float DeltaTime, struct FMinimalViewInfo &OutResult)
Calculate camera view point, when viewing this actor.
virtual bool HasActiveCameraComponent (bool bForceFindCamera=false) const
Returns true if the actor contains an active camera component.
virtual bool HasActivePawnControlCameraComponent () const
Returns true if the actor contains an active locked to HMD camera component.
virtual FString GetHumanReadableName () const
Returns the human readable string representation of an object.
virtual void Reset ()
Reset actor to initial state - used when restarting level without reloading.
void K2_OnReset ()
Event called when this Actor is reset to its initial state - used when restarting level without reloading.
bool WasRecentlyRendered (float Tolerance=0.2f) const
Returns true if this actor has been rendered "recently", with a tolerance in seconds to define what "recent" means.
virtual float GetLastRenderTime () const
Returns the most recent time any of this actor's components were rendered.
virtual void ForceNetRelevant ()
Forces this actor to be net relevant if it is not already by default.
virtual void ForceNetUpdate ()
Force actor to be updated to clients/demo net drivers.
virtual void PrestreamTextures (float Seconds, bool bEnableStreaming, int32 CinematicTextureGroups=0)
Calls PrestreamTextures() for all the actor's meshcomponents.
virtual void GetActorEyesViewPoint (FVector &OutLocation, FRotator &OutRotation) const
Returns the point of view of the actor.
virtual FVector GetTargetLocation (AActor *RequestedBy=nullptr) const
Returns the optimal location to fire weapons at this actor.
virtual void PostRenderFor (class APlayerController *PC, class UCanvas *Canvas, FVector CameraPosition, FVector CameraDir)
Hook to allow actors to render HUD overlays for themselves.
bool IsInPersistentLevel (bool bIncludeLevelStreamingPersistent=false) const
Returns whether this Actor is in the persistent level, i.e.
virtual UWorld * GetWorld () const override final
Getter for the cached world pointer, will return null if the actor is not actually spawned in a level.
class FTimerManager & GetWorldTimerManager () const
Get the timer instance from the actors world.
class UGameInstance * GetGameInstance () const
Gets the GameInstance that ultimately contains this actor.
template<class T>
T * GetGameInstance () const
Gets the GameInstance that ultimately contains this actor cast to the template type.
bool IsNetStartupActor () const
Returns true if this is a replicated actor that was placed in the map.
virtual UActorComponent * FindComponentByClass (const TSubclassOf< UActorComponent > ComponentClass) const
Searches components array and returns first encountered component of the specified class, native version of GetComponentByClass.
template<class T>
T * FindComponentByClass () const
Templatized version of FindComponentByClass that handles casting for you.
UActorComponent * GetComponentByClass (TSubclassOf< UActorComponent > ComponentClass) const
Searches components array and returns first encountered component of the specified class.
template<class T>
T * GetComponentByClass () const
Templated version of GetComponentByClass.
TArray< UActorComponent * > K2_GetComponentsByClass (TSubclassOf< UActorComponent > ComponentClass) const
Gets all the components that inherit from the given class.
UActorComponent * FindComponentByTag (TSubclassOf< UActorComponent > ComponentClass, FName Tag) const
Searches components array and returns first encountered component with a given tag.
template<class T>
T * FindComponentByTag (const FName &Tag) const
Templatized version of FindComponentByTag that handles casting for you.
TArray< UActorComponent * > GetComponentsByTag (TSubclassOf< UActorComponent > ComponentClass, FName Tag) const
Gets all the components that inherit from the given class with a given tag.
virtual UActorComponent * FindComponentByInterface (const TSubclassOf< UInterface > Interface) const
Searches components array and returns first encountered component that implements the given interface.
template<class T UE_REQUIRES>
T * FindComponentByInterface () const
Templatized version of FindComponentByInterface that handles casting for you.
template<class T UE_REQUIRES>
T * FindComponentByInterface () const
Templatized version of FindComponentByInterface that handles casting for you.
TArray< UActorComponent * > GetComponentsByInterface (TSubclassOf< UInterface > Interface) const
Gets all the components that implements the given interface.
template<class ComponentType, typename Func>
void ForEachComponent (bool bIncludeFromChildActors, Func InFunc) const
Calls the compile-time lambda on each component of the specified type.
template<typename Func>
void ForEachComponent (bool bIncludeFromChildActors, Func InFunc) const
Calls the compile-time lambda on each valid component.
template<class AllocatorType, class ComponentType>
void GetComponents (TSubclassOf< UActorComponent > ComponentClass, TArray< ComponentType *, AllocatorType > &OutComponents, bool bIncludeFromChildActors=false) const
Get all components derived from specified ComponentClass and fill in the OutComponents array with the result.
template<class ComponentType, class AllocatorType>
void GetComponents (TArray< ComponentType, AllocatorType > &OutComponents, bool bIncludeFromChildActors=false) const
Get all components derived from class 'ComponentType' and fill in the OutComponents array with the result.
template<class T, class AllocatorType>
void GetComponents (TArray< T *, AllocatorType > &OutComponents, bool bIncludeFromChildActors=false) const
Get all components derived from class 'ComponentType' and fill in the OutComponents array with the result.
template<class T, class AllocatorType>
void GetComponents (TArray< TObjectPtr< T >, AllocatorType > &OutComponents, bool bIncludeFromChildActors=false) const
Get all components derived from class 'T' and fill in the OutComponents array with the result.
template<class AllocatorType>
void GetComponents (TArray< UActorComponent *, AllocatorType > &OutComponents, bool bIncludeFromChildActors=false) const
UActorComponent specialization of GetComponents() to avoid unnecessary casts.
const TSet< UActorComponent * > & GetComponents () const
Get a direct reference to the Components set rather than a copy with the null pointers removed.
void AddOwnedComponent (UActorComponent *Component)
Puts a component in to the OwnedComponents array of the Actor.
void RemoveOwnedComponent (UActorComponent *Component)
Removes a component from the OwnedComponents array of the Actor.
void ResetOwnedComponents ()
Force the Actor to clear and rebuild its OwnedComponents array by evaluating all children (recursively) and locating components In general this should not need to be called directly, but can sometimes be necessary as part of undo/redo code paths.
void UpdateReplicatedComponent (UActorComponent *Component)
Called when the replicated state of a component changes to update the Actor's cached ReplicatedComponents array.
void UpdateAllReplicatedComponents ()
Completely synchronizes the replicated components array so that it contains exactly the number of replicated components currently owned.
virtual ELifetimeCondition AllowActorComponentToReplicate (const UActorComponent *ComponentToReplicate) const
Allows classes to control if a replicated component can actually be replicated or not in a specific actor class.
void SetReplicatedComponentNetCondition (const UActorComponent *ReplicatedComponent, ELifetimeCondition NetCondition)
Change the network condition of a replicated component but only after BeginPlay.
bool GetIsReplicated () const
Returns whether replication is enabled or not.
const TArray< UActorComponent * > & GetReplicatedComponents () const
Returns a constant reference to the replicated components set.
void AddReplicatedSubObject (UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor.
void RemoveReplicatedSubObject (UObject *SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
void DestroyReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated.
void DestroyReplicatedSubObjectOnRemotePeers (UActorComponent *OwnerComponent, UObject *SubObject)
Similar to the other destroy function but for subobjects owned by an ActorComponent.
void TearOffReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
void TearOffReplicatedSubObjectOnRemotePeers (UActorComponent *OwnerComponent, UObject *SubObject)
Similar to the other tear off function but for subobjects owned by an ActorComponent.
void AddActorComponentReplicatedSubObject (UActorComponent *OwnerComponent, UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor component owning it.
void RemoveActorComponentReplicatedSubObject (UActorComponent *OwnerComponent, UObject *SubObject)
Unregister a SubObject owned by an ActorComponent so it stops being replicated.
bool IsReplicatedSubObjectRegistered (const UObject *SubObject) const
Tells if the object has been registered as a replicated subobject of this actor.
bool IsReplicatedActorComponentRegistered (const UActorComponent *ReplicatedComponent) const
Tells if the component has been registered as a replicated component.
bool IsActorComponentReplicatedSubObjectRegistered (const UActorComponent *OwnerComponent, const UObject *SubObject) const
Tells if an object owned by a component has been registered as a replicated subobject of the component.
void AddInstanceComponent (UActorComponent *Component)
Adds a component to the instance components array.
void RemoveInstanceComponent (UActorComponent *Component)
Removes a component from the instance components array.
void ClearInstanceComponents (bool bDestroyComponents)
Clears the instance components array.
const TArray< UActorComponent * > & GetInstanceComponents () const
Returns the instance components array.
void MakeNoise (float Loudness=1.f, APawn *NoiseInstigator=nullptr, FVector NoiseLocation=FVector::ZeroVector, float MaxRange=0.f, FName Tag=NAME_None)
Trigger a noise caused by a given Pawn, at a given location.
virtual bool IsComponentRelevantForNavigation (UActorComponent *Component) const
Check if owned component should be relevant for navigation Allows implementing master switch to disable e.g.
virtual void DisplayDebug (class UCanvas *Canvas, const class FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos)
Draw important Actor variables on canvas.
bool IsHidden () const
Gets the literal value of bHidden.
void SetHidden (const bool bInHidden)
Sets the value of bHidden without causing other side effects to this instance.
bool IsReplicatingMovement () const
Gets the literal value of bReplicateMovement.
void SetReplicatingMovement (bool bInReplicateMovement)
Sets the value of bReplicateMovement without causing other side effects to this instance.
bool CanBeDamaged () const
Gets the literal value of bCanBeDamaged.
void SetCanBeDamaged (bool bInCanBeDamaged)
Sets the value of bCanBeDamaged without causing other side effects to this instance.
void SetRole (ENetRole InRole)
Sets the value of Role without causing other side effects to this instance.
const FRepMovement & GetReplicatedMovement () const
Gets the literal value of ReplicatedMovement.
FRepMovement & GetReplicatedMovement_Mutable ()
Gets a reference to ReplicatedMovement with the expectation that it will be modified.
void SetReplicatedMovement (const FRepMovement &InReplicatedMovement)
Sets the value of ReplicatedMovement without causing other side effects to this instance.
void SetNetUpdateFrequency (float Frequency)
Set the frequency at which this object will be considered for replication.
float GetNetUpdateFrequency () const
Get the current frequency at which this object will be considered for replication.
void SetMinNetUpdateFrequency (float MinFrequency)
Set the frequency to throttle down to when replicated properties are changing infrequently.
float GetMinNetUpdateFrequency () const
Get the frequency to throttle down to when replicated properties are changing infrequently.
void SetNetCullDistanceSquared (float DistanceSq)
Set the square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
float GetNetCullDistanceSquared () const
Get the square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
void SetInstigator (APawn *InInstigator)
Sets the value of Instigator without causing other side effects to this instance.
Static Public Member Functions
static const FName GetHLODLayerPropertyName ()
Gets the property name for HLODLayer.
static const FName GetRuntimeGridPropertyName ()
Gets the property name for RuntimeGrid.
static TUniquePtr< class FWorldPartitionActorDesc > StaticCreateClassActorDesc (const TSubclassOf< AActor > &ActorClass)
Creates an uninitialized actor descriptor from a specific class.
static const FName GetDataLayerAssetsPropertyName ()
static const FName GetDataLayerPropertyName ()
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static AActor * FindActorInPackage (UPackage *InPackage, bool bEvenIfPendingKill=true)
static const FName GetIsSpatiallyLoadedPropertyName ()
Gets the property name for bIsSpatiallyLoaded.
static void GetActorClassDefaultComponents (const TSubclassOf< AActor > &InActorClass, const TSubclassOf< UActorComponent > &InComponentClass, TArray< const UActorComponent * > &OutComponents)
Fetches all the components of ActorClass's CDO, including the ones added via the BP editor (which AActor.GetComponents fails to do for CDOs).
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type>
static void GetActorClassDefaultComponents (const TSubclassOf< AActor > &InActorClass, TArray< const TComponentClass * > &OutComponents)
Templated version of GetActorClassDefaultComponents()
static const UActorComponent * GetActorClassDefaultComponent (const TSubclassOf< AActor > &InActorClass, const TSubclassOf< UActorComponent > &InComponentClass)
Fetches the first component of ActorClass's CDO which match the requested component class.
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type>
static const TComponentClass * GetActorClassDefaultComponent (const TSubclassOf< AActor > &InActorClass)
Templated version of GetActorClassDefaultComponent()
static const UActorComponent * GetActorClassDefaultComponentByName (const TSubclassOf< AActor > &InActorClass, const TSubclassOf< UActorComponent > &InComponentClass, FName InComponentName)
Get the component of ActorClass's CDO that matches the given object name.
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type>
static const TComponentClass * GetActorClassDefaultComponentByName (const TSubclassOf< AActor > &InActorClass, FName InComponentName)
Templated version of GetActorClassDefaultComponentByName()
static void ForEachComponentOfActorClassDefault (const TSubclassOf< AActor > &InActorClass, const TSubclassOf< UActorComponent > &InComponentClass, TFunctionRef< bool(const UActorComponent *)> InFunc)
Iterate over the components of ActorClass's CDO, including the ones added via the BP editor (which AActor.GetComponents fails to return).
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type>
static void ForEachComponentOfActorClassDefault (const TSubclassOf< AActor > &InActorClass, TFunctionRef< bool(const TComponentClass *)> InFunc)
Templated version of ForEachComponentOfActorClassDefault()
static void MakeNoiseImpl (AActor *NoiseMaker, float Loudness, APawn *NoiseInstigator, const FVector &NoiseLocation, float MaxRange, FName Tag)
Default Implementation of MakeNoise.
static void SetMakeNoiseDelegate (const FMakeNoiseDelegate &NewDelegate)
Modifies the global delegate used for handling MakeNoise.
static FString GetDebugName (const AActor *Actor)
Retrieves actor's name used for logging, or string "NULL" if Actor is null.
static const FName GetHiddenPropertyName ()
Gets the property name for bHidden.
static const FName GetReplicateMovementPropertyName ()
Gets the property name for bReplicateMovement.
static const FName GetCanBeDamagedPropertyName ()
Gets the property name for bCanBeDamaged.
static const FName GetRolePropertyName ()
Gets the property name for Role.
static const FName GetInstigatorPropertyName ()
Gets the property name for Instigator.
Public Attributes
struct FActorTickFunction PrimaryActorTick
Primary Actor tick function, which calls TickActor().
uint8 bNetTemporary:1
If true, when the actor is spawned it will be sent to the client but receive no further replication updates from the server afterwards.
uint8 bNetStartup:1
If true, this actor was loaded directly from the map, and for networking purposes can be addressed by its full path name.
uint8 bOnlyRelevantToOwner:1
If true, this actor is only relevant to its owner.
uint8 bAlwaysRelevant:1
Always relevant for network (overrides bOnlyRelevantToOwner).
uint8 bIsMainWorldOnly: 1
uint8 bIgnoreInPIE: 1
Experimental: this will force this actor to be ignored in PIE, will not work if the actor has references to other actors without the flag set, use with care.
uint8 bExchangedRoles:1
Whether we have already exchanged Role/RemoteRole on the client, as when removing then re-adding a streaming level.
uint8 bNetLoadOnClient:1
This actor will be loaded on network clients during map load.
uint8 bNetUseOwnerRelevancy:1
If actor has valid Owner, call Owner's IsNetRelevantFor and GetNetPriority.
uint8 bRelevantForNetworkReplays:1
If true, this actor will be replicated to network replays (default is true)
uint8 bRelevantForLevelBounds:1
If true, this actor's component's bounds will be included in the level's bounding box unless the Actor's class has overridden IsLevelBoundsRelevant.
uint8 bReplayRewindable:1
If true, this actor will only be destroyed during scrubbing if the replay is set to a time before the actor existed.
uint8 bAllowTickBeforeBeginPlay:1
Whether we allow this Actor to tick before it receives the BeginPlay event.
uint8 bBlockInput:1
If true, all input on the stack below this actor will not be considered.
uint8 bCollideWhenPlacing:1
This actor collides with the world when placing in the editor, even if RootComponent collision is disabled.
uint8 bFindCameraComponentWhenViewTarget:1
If true, this actor should search for an owned camera component to view through when used as a view target.
uint8 bGenerateOverlapEventsDuringLevelStreaming:1
If true, this actor will generate overlap Begin/End events when spawned as part of level streaming, which includes initial level load.
uint8 bIgnoresOriginShifting:1
Whether this actor should not be affected by world origin shifting.
uint8 bEnableAutoLODGeneration:1
Whether this actor should be considered or not during HLOD generation.
uint8 bIsEditorOnlyActor:1
Whether this actor is editor-only.
uint8 bActorSeamlessTraveled:1
Indicates the actor was pulled through a seamless travel.
uint8 ActorCategory = 0
Project-specific field that help to categorize actors for reporting purposes.
float InitialLifeSpan
How long this Actor lives before dying, 0=forever.
float CustomTimeDilation
Allow each actor to run at a different time speed.
TObjectPtr< AActor > Owner
Owner of this Actor, used primarily for replication (bNetUseOwnerRelevancy & bOnlyRelevantToOwner) and visibility (PrimitiveComponent bOwnerNoSee and bOnlyOwnerSee)
TWeakObjectPtr< AActor > IntermediateOwner = nullptr
Used to track changes to Owner during Undo events.
TEnumAsByte< enum ENetDormancy > NetDormancy
Dormancy setting for actor to take itself off of the replication list without being destroyed on clients.
ESpawnActorCollisionHandlingMethod SpawnCollisionHandlingMethod
Controls how to handle spawning this actor in a situation where it's colliding with something else.
TEnumAsByte< EAutoReceiveInput::Type > AutoReceiveInput
Automatically registers this actor to receive input from a player.
int32 InputPriority
The priority of this input component when pushed in to the stack.
float CreationTime
The time this actor was created, relative to World->GetTimeSeconds().
TObjectPtr< class UInputComponent > InputComponent
Component that handles input for this actor, if input is enabled.
int32 NetTag
Internal - used by UNetDriver.
float NetCullDistanceSquared
Square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
float NetUpdateFrequency
How often (per second) this actor will be considered for replication, used to determine NetUpdateTime.
float MinNetUpdateFrequency
Used to determine what rate to throttle down to when replicated properties are changing infrequently.
float NetPriority
Priority for this actor when checking for replication in a low bandwidth or saturated situation, higher priority means it is more likely to replicate.
TArray< TObjectPtr< AActor > > Children
Array of all Actors whose Owner is this actor, these are not necessarily spawned by UChildActorComponent.
TArray< FName > Layers
Layers the actor belongs to.
uint32 CopyPasteId
The copy/paste id used to remap actors during copy operations.
TObjectPtr< AActor > GroupActor
The editor-only group this actor is a part of.
float SpriteScale
The scale to apply to any billboard components in editor builds (happens in any WITH_EDITOR build, including non-cooked games).
uint64 HiddenEditorViews
Bitflag to represent which views this actor is hidden in, via per-view layer visibility.
FActorOnPackagingModeChanged OnPackagingModeChanged
uint8 bHiddenEd:1
Whether this actor is hidden within the editor viewport.
uint8 bIsEditorPreviewActor:1
True if this actor is the preview actor dragged out of the content browser.
uint8 bHiddenEdLayer:1
Whether this actor is hidden by the layer browser.
uint8 bHiddenEdLevel:1
Whether this actor is hidden by the level browser.
uint8 bRunConstructionScriptOnDrag:1
If true during PostEditMove the construction script will be run every time.
uint8 bDefaultOutlinerExpansionState: 1
Default expansion state for this actor.
TArray< FName > Tags
Array of tags that can be used for grouping and categorizing.
FTakeAnyDamageSignature OnTakeAnyDamage
Called when the actor is damaged in any way.
FTakePointDamageSignature OnTakePointDamage
Called when the actor is damaged by point damage.
FTakeRadialDamageSignature OnTakeRadialDamage
Called when the actor is damaged by radial damage.
FActorBeginOverlapSignature OnActorBeginOverlap
Called when another actor begins to overlap this actor, for example a player walking into a trigger.
FActorEndOverlapSignature OnActorEndOverlap
Called when another actor stops overlapping this actor.
FActorBeginCursorOverSignature OnBeginCursorOver
Called when the mouse cursor is moved over this actor if mouse over events are enabled in the player controller.
FActorEndCursorOverSignature OnEndCursorOver
Called when the mouse cursor is moved off this actor if mouse over events are enabled in the player controller.
FActorOnClickedSignature OnClicked
Called when the left mouse button is clicked while the mouse is over this actor and click events are enabled in the player controller.
FActorOnReleasedSignature OnReleased
Called when the left mouse button is released while the mouse is over this actor and click events are enabled in the player controller.
FActorOnInputTouchBeginSignature OnInputTouchBegin
Called when a touch input is received over this actor when touch events are enabled in the player controller.
FActorOnInputTouchEndSignature OnInputTouchEnd
Called when a touch input is received over this component when touch events are enabled in the player controller.
FActorBeginTouchOverSignature OnInputTouchEnter
Called when a finger is moved over this actor when touch over events are enabled in the player controller.
FActorEndTouchOverSignature OnInputTouchLeave
Called when a finger is moved off this actor when touch over events are enabled in the player controller.
FActorHitSignature OnActorHit
Called when this Actor hits (or is hit by) something solid.
FActorDestroyedSignature OnDestroyed
Event triggered when the actor has been explicitly destroyed.
FActorEndPlaySignature OnEndPlay
Event triggered when the actor is being deleted or removed from a level.
TSharedPtr< FActorTransactionAnnotation > CurrentTransactionAnnotation
Cached pointer to the transaction annotation data from PostEditUndo to be used in the next RerunConstructionScript.
TArray< TObjectPtr< UActorComponent > > BlueprintCreatedComponents
Array of ActorComponents that are created by blueprints and serialized per-instance.
FRenderCommandFence DetachFence
A fence to track when the primitive is detached from the scene in the rendering thread.
Static Public Attributes
static bool bUsePercentageBasedScaling
static FOnProcessEvent ProcessEventDelegate
Delegate for globally hooking ProccessEvent calls - used by a non-public testing plugin.
Protected Member Functions
UClass * GetRepresentedClassInternal () const
AActor * ConvertInstanceToActor (const FActorInstanceHandle &Handle)
int32 AddNewInstance (FLWIData *InitData)
virtual void AddNewInstanceAt (FLWIData *InitData, int32 Index)
virtual void RemoveInstance (int32 Index)
bool IsIndexValid (int32 Index) const
bool FindActorForHandle (const FActorInstanceHandle &Handle) const
virtual void SetSpawnParameters (FActorSpawnParameters &SpawnParams)
virtual UClass * GetActorClassToSpawn (const FActorInstanceHandle &Handle) const
virtual void PreSpawnInitalization (const FActorInstanceHandle &Handle, AActor *SpawnedActor)
virtual void PostActorSpawn (const FActorInstanceHandle &Handle)
virtual void OnSpawnedActorDestroyed (AActor *DestroyedActor, const int32 DestroyedActorInstanceIndex)
virtual int32 ConvertInternalIndexToHandleIndex (int32 InInternalIndex) const
virtual int32 ConvertHandleIndexToInternalIndex (int32 InHandleIndex) const
virtual void OnRep_Transforms ()
virtual void GrowDataArrays ()
virtual void UpdateDataAtIndex (FLWIData *InData, int32 Index)
virtual FLWIData * AllocateInitData () const
virtual bool SetDataFromActor (FLWIData *InData, AActor *InActor) const
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
void SetRemoteRoleForBackwardsCompat (const ENetRole InRemoteRole)
This function should only be used in the constructor of classes that need to set the RemoteRole for backwards compatibility purposes.
virtual void OnRep_Owner ()
Called when owner changes, does nothing by default but can be overridden.
virtual bool IsDataLayerTypeSupported (TSubclassOf< UDataLayerInstance > DataLayerType) const final
void ReceiveBeginPlay ()
Event when play begins for this actor.
virtual void BeginPlay ()
Overridable native event for when play begins for this actor.
void ReceiveEndPlay (EEndPlayReason::Type EndPlayReason)
Event to notify blueprints this actor is being deleted or removed from a level.
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason)
Overridable function called whenever this actor is being removed from a level.
void SyncReplicatedPhysicsSimulation ()
Sync IsSimulatingPhysics() with ReplicatedMovement.bRepPhysics.
bool IsWithinNetRelevancyDistance (const FVector &SrcLocation) const
Determines whether or not the distance between the given SrcLocation and the Actor's location is within the net relevancy distance.
virtual void RegisterActorTickFunctions (bool bRegister)
Virtual call chain to register all tick functions for the actor class hierarchy.
void ProcessUserConstructionScript ()
Runs UserConstructionScript, delays component registration until it's complete.
bool CheckActorComponents () const
Checks components for validity, implemented in AActor.
void PostCreateBlueprintComponent (UActorComponent *NewActorComp)
Called after instancing a new Blueprint Component from either a template or cooked data.
virtual float InternalTakeRadialDamage (float Damage, struct FRadialDamageEvent const &RadialDamageEvent, class AController *EventInstigator, AActor *DamageCauser)
virtual float InternalTakePointDamage (float Damage, struct FPointDamageEvent const &PointDamageEvent, class AController *EventInstigator, AActor *DamageCauser)
Protected Attributes
FString BaseInstanceName
TSubclassOf< AActor > RepresentedClass
TSubclassOf< AActor > AcceptedClass
TArray< FTransform > InstanceTransforms
TMap< int32, TObjectPtr< AActor > > Actors
TArray< int32 > DestroyedActorIndices
TArray< int32 > FreeIndices
TArray< bool > ValidIndices
TArray< int32 > InstanceToActorConversionsInProgress
uint8 bReplicates:1
If true, this actor will replicate to remote machines.
uint8 bCanBeInCluster:1
If true, this actor can be put inside of a GC Cluster to improve Garbage Collection performance.
uint8 bAllowReceiveTickEventOnDedicatedServer:1
If false, the Blueprint ReceiveTick() event will be disabled on dedicated servers.
uint8 bNetCheckedInitialPhysicsState: 1
Flag indicating we have checked initial simulating physics state to sync networked proxies to the server.
uint8 bReplicateUsingRegisteredSubObjectList: 1
When true the replication system will only replicate the registered subobjects and the replicated actor components list When false the replication system will instead call the virtual ReplicateSubobjects() function where the subobjects and actor components need to be manually replicated.
uint8 bAsyncPhysicsTickEnabled: 1
Whether to use use the async physics tick with this actor.
EActorUpdateOverlapsMethod UpdateOverlapsMethodDuringLevelStreaming
Condition for calling UpdateOverlaps() to initialize overlap state when loaded in during level streaming.
PRAGMA_DISABLE_DEPRECATION_WARNINGS EActorGridPlacement GridPlacement_DEPRECATED
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName RuntimeGrid
Determine in which partition grid this actor will be placed in the partition (if the world is partitioned).
struct FRepAttachment AttachmentReplication
Used for replicating attachment of this actor's RootComponent to another actor.
FName NetDriverName
Used to specify the net driver to replicate on (NAME_None || NAME_GameNetDriver is the default net driver)
TObjectPtr< USceneComponent > RootComponent
The component that defines the transform (location, rotation, scale) of this Actor in the world, all other components must be attached to this one somehow.
FVector PivotOffset
Local space pivot offset for the actor, only used in the editor.
FTimerHandle TimerHandle_LifeSpanExpired
Handle for efficient management of LifeSpanExpired timer.
FGuid ActorGuid
The GUID for this actor; this guid will be the same for actors from instanced streaming levels.
FGuid ActorInstanceGuid
The instance GUID for this actor; this guid will be unique for actors from instanced streaming levels.
FGuid ContentBundleGuid
The GUID for this actor's content bundle.
TArray< FActorDataLayer > DataLayers
DataLayers the actor belongs to.
TArray< TSoftObjectPtr< UDataLayerAsset > > DataLayerAssets
DataLayers assets the actor belongs to.
TArray< TSoftObjectPtr< UDataLayerAsset > > PreEditChangeDataLayers
TObjectPtr< const UExternalDataLayerAsset > ExternalDataLayerAsset
uint8 bLockLocation:1
If true, prevents the actor from being moved in the editor viewport.
uint8 bActorLabelEditable:1
Is the actor label editable by the user?
uint8 bEditable:1
Whether the actor can be manipulated by editor operations.
uint8 bListedInSceneOutliner:1
Whether this actor should be listed in the scene outliner.
uint8 bOptimizeBPComponentData:1
Whether to cook additional data to speed up spawn events at runtime for any Blueprint classes based on this Actor.
uint8 bCanPlayFromHere: 1
Whether the actor can be used as a PlayFromHere origin (OnPlayFromHere() will be called on that actor)
uint8 bIsSpatiallyLoaded: 1
Determine if this actor is spatially loaded when placed in a partitioned world.
TArray< UActorComponent * > ReplicatedComponents
Set of replicated components, stored as an array to save space as this is generally not very large.
Friends
struct FLightWeightInstanceSubsystem
struct FActorInstanceHandle
class ULightWeightInstanceBlueprintFunctionLibrary
Detailed Description
Definition at line 30 of file LightWeightInstanceManager.h.
Constructor & Destructor Documentation
~ALightWeightInstanceManager()
virtual ALightWeightInstanceManager::~ALightWeightInstanceManager () virtual
Member Function Documentation
ActorGetDistanceToCollision()
float AActor::ActorGetDistanceToCollision (const FVector & Point, ECollisionChannel TraceChannel, FVector & ClosestPointOnCollision, UPrimitiveComponent ** OutPrimitiveComponent = nullptr) const inherited
returns Distance to closest Body Instance surface.
Checks against all components of this Actor having valid collision and blocking TraceChannel.
Parameters
Point World 3D vector
TraceChannel The 'channel' used to determine which components to consider.
ClosestPointOnCollision Point on the surface of collision closest to Point
OutPrimitiveComponent PrimitiveComponent ClosestPointOnCollision is on.
Returns
Success if returns > 0.f, if returns 0.f, it is either not convex or inside of the point If returns < 0.f, this Actor does not have any primitive with collision
ActorHasTag()
bool AActor::ActorHasTag (FName Tag) const inherited
See if this actor's Tags array contains the supplied name tag.
References ActorHasTag().
ActorLineTraceSingle()
bool AActor::ActorLineTraceSingle (struct FHitResult & OutHit, const FVector & Start, const FVector & End, ECollisionChannel TraceChannel, const struct FCollisionQueryParams & Params) const inherited
Trace a ray against the Components of this Actor and return the first blocking hit.
Parameters
OutHit First blocking hit found
Start Start location of the ray
End End location of the ray
TraceChannel The 'channel' that this ray is in, used to determine which components to hit
Params Additional parameters used for the trace
Returns
TRUE if a blocking hit is found
References Start.
ActorToWorld()
const FTransform & AActor::ActorToWorld () const inline inherited
Get the local-to-world transform of the RootComponent.
Identical to GetTransform().
Definition at line 1551 of file Actor.h.
References RootComponent.
ActorTypeSupportsDataLayer()
virtual bool AActor::ActorTypeSupportsDataLayer () const inline virtual inherited
Definition at line 1459 of file Actor.h.
ActorTypeSupportsExternalDataLayer()
virtual bool AActor::ActorTypeSupportsExternalDataLayer () const inline virtual inherited
Definition at line 1460 of file Actor.h.
AddActorComponentReplicatedSubObject()
void AActor::AddActorComponentReplicatedSubObject (UActorComponent * OwnerComponent, UObject * SubObject, ELifetimeCondition NetCondition = COND_None) inherited
Register a SubObject that will get replicated along with the actor component owning it.
The subobject needs to be manually removed from the list before it gets deleted.
Parameters
SubObject The SubObject to replicate
NetCondition Optional condition to select which type of connection we will replicate the object to.
AddActorLocalOffset()
void AActor::AddActorLocalOffset (FVector DeltaLocation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorLocalOffset().
AddActorLocalRotation() [1/2]
void AActor::AddActorLocalRotation (const FQuat & DeltaRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorLocalRotation().
AddActorLocalRotation() [2/2]
void AActor::AddActorLocalRotation (FRotator DeltaRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorLocalRotation().
AddActorLocalTransform()
void AActor::AddActorLocalTransform (const FTransform & NewTransform, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorLocalTransform().
AddActorWorldOffset()
void AActor::AddActorWorldOffset (FVector DeltaLocation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorWorldOffset().
AddActorWorldRotation() [1/2]
void AActor::AddActorWorldRotation (const FQuat & DeltaRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorWorldRotation().
AddActorWorldRotation() [2/2]
void AActor::AddActorWorldRotation (FRotator DeltaRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorWorldRotation().
AddActorWorldTransform()
void AActor::AddActorWorldTransform (const FTransform & DeltaTransform, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorWorldTransform().
AddActorWorldTransformKeepScale()
void AActor::AddActorWorldTransformKeepScale (const FTransform & DeltaTransform, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References AddActorWorldTransformKeepScale().
AddComponent()
UActorComponent * AActor::AddComponent (FName TemplateName, bool bManualAttachment, const FTransform & RelativeTransform, const UObject * ComponentTemplateContext, bool bDeferredFinish = false) inherited
Creates a new component and assigns ownership to the Actor this is called for.
Automatic attachment causes the first component created to become the root, and all subsequent components to be attached under that root. When bManualAttachment is set, automatic attachment is skipped and it is up to the user to attach the resulting component (or set it up as the root) themselves.
See also
UK2Node_AddComponent DO NOT CALL MANUALLY - BLUEPRINT INTERNAL USE ONLY (for Add Component nodes)
Parameters
TemplateName The name of the Component Template to use.
bManualAttachment Whether manual or automatic attachment is to be used
RelativeTransform The relative transform between the new component and its attach parent (automatic only)
ComponentTemplateContext Optional UBlueprintGeneratedClass reference to use to find the template in. If null (or not a BPGC), component is sought in this Actor's class
bDeferredFinish Whether or not to immediately complete the creation and registration process for this component. Will be false if there are expose on spawn properties being set
References AddComponent().
AddComponentByClass()
UActorComponent * AActor::AddComponentByClass (UPARAM(meta=(AllowAbstract="false")) TSubclassOf< UActorComponent > Class, bool bManualAttachment, const FTransform & RelativeTransform, bool bDeferredFinish) inherited
Creates a new component and assigns ownership to the Actor this is called for.
Automatic attachment causes the first component created to become the root, and all subsequent components to be attached under that root. When bManualAttachment is set, automatic attachment is skipped and it is up to the user to attach the resulting component (or set it up as the root) themselves.
See also
UK2Node_AddComponentByClass DO NOT CALL MANUALLY - BLUEPRINT INTERNAL USE ONLY (for Add Component nodes)
Parameters
Class The class of component to create
bManualAttachment Whether manual or automatic attachment is to be used
RelativeTransform The relative transform between the new component and its attach parent (automatic only)
bDeferredFinish Whether or not to immediately complete the creation and registration process for this component. Will be false if there are expose on spawn properties being set
References AddComponentByClass().
AddDataLayer() [1/4]
bool AActor::AddDataLayer (const FActorDataLayer & ActorDataLayer) inherited
References AddDataLayer().
AddDataLayer() [2/4]
bool AActor::AddDataLayer (const UDataLayerAsset * DataLayerAsset) inline inherited
Definition at line 1478 of file Actor.h.
References AddDataLayer().
AddDataLayer() [3/4]
bool AActor::AddDataLayer (const UDataLayerInstance * DataLayerInstance) inherited
AddDataLayer() [4/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS bool AActor::AddDataLayer (const UDEPRECATED_DataLayer * DataLayer) inherited
References AddDataLayer().
AddInstanceComponent()
void AActor::AddInstanceComponent (UActorComponent * Component) inherited
Adds a component to the instance components array.
References AddInstanceComponent().
AddNewInstance()
int32 ALightWeightInstanceManager::AddNewInstance (FLWIData * InitData) protected
AddNewInstanceAt()
virtual void ALightWeightInstanceManager::AddNewInstanceAt (FLWIData * InitData, int32 Index) protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
AddOwnedComponent()
void AActor::AddOwnedComponent (UActorComponent * Component) inherited
Puts a component in to the OwnedComponents array of the Actor.
The Component must be owned by the Actor or else it will assert In general this should not need to be called directly by anything other than UActorComponent functions
AddReferencedObjects()
void AActor::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static inherited
AddReplicatedSubObject()
void AActor::AddReplicatedSubObject (UObject * SubObject, ELifetimeCondition NetCondition = COND_None) inherited
Register a SubObject that will get replicated along with the actor.
The subobject needs to be manually removed from the list before it gets deleted.
Parameters
SubObject The SubObject to replicate
NetCondition Optional condition to select which type of connection we will replicate the object to.
AddTickPrerequisiteActor()
virtual void AActor::AddTickPrerequisiteActor (AActor * PrerequisiteActor) virtual inherited
Make this actor tick after PrerequisiteActor.
This only applies to this actor's tick function; dependencies for owned components must be set up separately if desired.
References AActor(), and AddTickPrerequisiteActor().
AddTickPrerequisiteComponent()
virtual void AActor::AddTickPrerequisiteComponent (UActorComponent * PrerequisiteComponent) virtual inherited
Make this actor tick after PrerequisiteComponent.
This only applies to this actor's tick function; dependencies for owned components must be set up separately if desired.
References AddTickPrerequisiteComponent().
AllocateInitData()
virtual FLWIData * ALightWeightInstanceManager::AllocateInitData () const protected virtual
References AllocateInitData().
AllowActorComponentToReplicate()
virtual ELifetimeCondition AActor::AllowActorComponentToReplicate (const UActorComponent * ComponentToReplicate) const virtual inherited
Allows classes to control if a replicated component can actually be replicated or not in a specific actor class.
You can also choose a netcondition to filter to whom the component is replicated to. Called on existing replicated component right before BeginPlay() and after that on every new replicated component added to the OwnedComponent list
Parameters
ComponentToReplicate The replicated component added to the actor.
Returns
Return COND_None if this component should be replicated to everyone, COND_Never if it should not be replicated at all or any other conditions for specific filtering.
AllowReceiveTickEventOnDedicatedServer()
bool AActor::AllowReceiveTickEventOnDedicatedServer () const inline inherited
Return the value of bAllowReceiveTickEventOnDedicatedServer, indicating whether the Blueprint ReceiveTick() event will occur on dedicated servers.
Definition at line 1026 of file Actor.h.
References bAllowReceiveTickEventOnDedicatedServer.
ApplyWorldOffset()
virtual void AActor::ApplyWorldOffset (const FVector & InOffset, bool bWorldShift) virtual inherited
Called by owning level to shift an actor location and all relevant data structures by specified delta.
Parameters
InOffset Offset vector to shift actor location
bWorldShift Whether this call is part of whole world shifting
AsyncPhysicsTickActor()
virtual void AActor::AsyncPhysicsTickActor (float DeltaTime, float SimTime) inline virtual inherited
Override this function to implement custom logic to be executed every physics step.
bAsyncPhysicsTick must be set to true.
Parameters
DeltaTime - The physics step delta time
SimTime - This is the total sim time since the sim began.
Definition at line 2914 of file Actor.h.
References AsyncPhysicsTickActor(), and ReceiveAsyncPhysicsTick().
AttachToActor()
bool AActor::AttachToActor (AActor * ParentActor, const FAttachmentTransformRules & AttachmentRules, FName SocketName = NAME_None) inherited
Attaches the RootComponent of this Actor to the RootComponent of the supplied actor, optionally at a named socket.
Parameters
ParentActor Actor to attach this actor's RootComponent to
AttachmentRules How to handle transforms and modification when attaching.
SocketName Socket name to attach to, if any
Returns
Whether the attachment was successful or not
References AActor(), and AttachToActor().
AttachToComponent()
bool AActor::AttachToComponent (USceneComponent * Parent, const FAttachmentTransformRules & AttachmentRules, FName SocketName = NAME_None) inherited
Attaches the RootComponent of this Actor to the supplied component, optionally at a named socket.
It is not valid to call this on components that are not Registered.
Parameters
Parent Parent to attach to.
AttachmentRules How to handle transforms and welding when attaching.
SocketName Optional socket to attach to on the parent.
Returns
Whether the attachment was successful or not
References AttachToComponent().
BecomeViewTarget()
virtual void AActor::BecomeViewTarget (class APlayerController * PC) virtual inherited
Called when this actor becomes the given PlayerController's ViewTarget.
Triggers the Blueprint event K2_OnBecomeViewTarget.
Reimplemented in APawn.
References BecomeViewTarget().
BeginDestroy()
virtual void AActor::BeginDestroy () override virtual inherited
BeginPlay()
virtual void AActor::BeginPlay () protected virtual inherited
Overridable native event for when play begins for this actor.
Reimplemented in ACharacter, APawn, and APlayerController.
References BeginPlay().
CalcCamera()
virtual void AActor::CalcCamera (float DeltaTime, struct FMinimalViewInfo & OutResult) virtual inherited
Calculate camera view point, when viewing this actor.
Parameters
DeltaTime Delta time seconds since last update
OutResult Camera configuration
Reimplemented in APlayerController.
References CalcCamera().
CalculateComponentsBoundingBoxInLocalSpace()
virtual FBox AActor::CalculateComponentsBoundingBoxInLocalSpace (bool bNonColliding = false, bool bIncludeFromChildActors = false) const virtual inherited
Calculates the actor space bounding box of all components in this Actor.
This is slower than GetComponentsBoundingBox(), because the local bounds of the components are not cached – they are recalculated every time this function is called.
Parameters
bNonColliding Indicates that you want to include non-colliding components in the bounding box
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
References CalculateComponentsBoundingBoxInLocalSpace().
CallPreReplication()
void AActor::CallPreReplication (UNetDriver * NetDriver) inherited
Called by the networking system to call PreReplication on this actor and its components using the given NetDriver to find or create RepChangedPropertyTrackers.
References OnRep_Instigator().
CallRemoteFunction()
virtual bool AActor::CallRemoteFunction (UFunction * Function, void * Parameters, FOutParmRec * OutParms, FFrame * Stack) override virtual inherited
References CallRemoteFunction().
CanAddDataLayer()
bool AActor::CanAddDataLayer (const UDataLayerInstance * InDataLayerInstance, FText * OutReason = nullptr) const inherited
CanBeBaseForCharacter()
virtual bool AActor::CanBeBaseForCharacter (class APawn * Pawn) const virtual inherited
Return true if the given Pawn can be "based" on this actor (ie walk on it).
Parameters
Pawn - The pawn that wants to be based on this actor
Reimplemented in APawn.
References CanBeBaseForCharacter().
CanBeDamaged()
bool AActor::CanBeDamaged () const inline inherited
Gets the literal value of bCanBeDamaged.
This exists so subclasses don't need to have direct access to the bCanBeDamaged property so it can be made private later.
Definition at line 4526 of file Actor.h.
CanBeInCluster()
virtual bool AActor::CanBeInCluster () const override virtual inherited
CanChangeIsSpatiallyLoadedFlag()
virtual bool AActor::CanChangeIsSpatiallyLoadedFlag () const virtual inherited
Returns true if this actor allows changing the spatially loaded flag.
Reimplemented in AInfo.
CanDeleteSelectedActor()
virtual bool AActor::CanDeleteSelectedActor (FText & OutReason) const virtual inherited
When selected can this actor be deleted?
Reimplemented in AWorldSettings.
CanEditChange()
virtual bool AActor::CanEditChange (const FProperty * InProperty) const virtual inherited
Reimplemented in AWorldSettings.
References CanEditChange().
CanEditChangeComponent()
virtual bool AActor::CanEditChangeComponent (const UActorComponent * Component, const FProperty * InProperty) const virtual inherited
CanEverTick()
bool AActor::CanEverTick () const inline inherited
Accessor for the value of bCanEverTick.
Definition at line 3039 of file Actor.h.
References CanEverTick(), and PrimaryActorTick.
CanPlayFromHere()
bool AActor::CanPlayFromHere () const inline inherited
Definition at line 1151 of file Actor.h.
References bCanPlayFromHere.
CanReplaceSelectedActor()
virtual bool AActor::CanReplaceSelectedActor (FText & OutReason) const virtual inherited
When selected can this actor be replaced.
Reimplemented in AWorldSettings.
CanTriggerResimulation()
bool AActor::CanTriggerResimulation () const inherited
Can this body trigger a resimulation when Physics Prediction is enabled.
References CanTriggerResimulation().
CheckActorComponents()
bool AActor::CheckActorComponents () const protected inherited
Checks components for validity, implemented in AActor.
CheckComponentInstanceName()
void AActor::CheckComponentInstanceName (const FName InName) inherited
Checks for and resolve any name conflicts prior to instancing a new Blueprint Component.
CheckDefaultSubobjectsInternal()
virtual bool AActor::CheckDefaultSubobjectsInternal () const override virtual inherited
References CheckDefaultSubobjectsInternal().
CheckForDeprecated()
virtual void AActor::CheckForDeprecated () virtual inherited
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
CheckForErrors()
virtual void AActor::CheckForErrors () virtual inherited
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
Reimplemented in AWorldSettings.
CheckStillInWorld()
virtual bool AActor::CheckStillInWorld () virtual inherited
This will check to see if the Actor is still in the world.
It will check things like the KillZ, outside world bounds, etc. and handle the situation.
ClearActorLabel()
void AActor::ClearActorLabel () inherited
Advanced - clear the actor label.
References ClearActorLabel().
ClearComponentOverlaps()
void AActor::ClearComponentOverlaps () inherited
Dispatch all EndOverlap for all of the Actor's PrimitiveComponents.
Generally used when removing the Actor from the world.
ClearCrossLevelReferences()
virtual void AActor::ClearCrossLevelReferences () virtual inherited
Do anything needed to clear out cross level references; Called from ULevel::PreSave.
Reimplemented in ACharacter.
References ClearCrossLevelReferences().
ClearInstanceComponents()
void AActor::ClearInstanceComponents (bool bDestroyComponents) inherited
Clears the instance components array.
References ClearInstanceComponents().
ContainsDataLayer() [1/3]
bool AActor::ContainsDataLayer (const FActorDataLayer & ActorDataLayer) const inherited
References ContainsDataLayer().
ContainsDataLayer() [2/3]
bool AActor::ContainsDataLayer (const UDataLayerAsset * DataLayerAsset) const inherited
ContainsDataLayer() [3/3]
bool AActor::ContainsDataLayer (const UDataLayerInstance * DataLayerInstance) const inherited
ConvertActorToLightWeightInstance()
FActorInstanceHandle ALightWeightInstanceManager::ConvertActorToLightWeightInstance (AActor * InActor)
References AActor::AActor(), ConvertActorToLightWeightInstance(), and FActorInstanceHandle.
ConvertCollisionIndexToInstanceIndex()
virtual int32 ALightWeightInstanceManager::ConvertCollisionIndexToInstanceIndex (int32 InIndex, const UPrimitiveComponent * RelevantComponent) const virtual
References ConvertCollisionIndexToInstanceIndex().
ConvertHandleIndexToInternalIndex()
virtual int32 ALightWeightInstanceManager::ConvertHandleIndexToInternalIndex (int32 InHandleIndex) const inline protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
Definition at line 129 of file LightWeightInstanceManager.h.
ConvertInstanceToActor()
AActor * ALightWeightInstanceManager::ConvertInstanceToActor (const FActorInstanceHandle & Handle) protected
References AActor::AActor(), and FActorInstanceHandle.
ConvertInternalIndexToHandleIndex()
virtual int32 ALightWeightInstanceManager::ConvertInternalIndexToHandleIndex (int32 InInternalIndex) const inline protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
Definition at line 128 of file LightWeightInstanceManager.h.
ConvertPositionToCoord()
FInt32Vector3 ALightWeightInstanceManager::ConvertPositionToCoord (const FVector & InPosition) const
References ConvertPositionToCoord().
ConvertPositionToGridBounds()
FBox ALightWeightInstanceManager::ConvertPositionToGridBounds (const FVector & InPosition) const
References ConvertPositionToGridBounds().
CopyRemoteRoleFrom()
void AActor::CopyRemoteRoleFrom (const AActor * CopyFromActor) inherited
Copies RemoteRole from another Actor and adds this actor to the list of network actors if necessary.
References AActor(), and CopyRemoteRoleFrom().
CreateActorDesc()
TUniquePtr< class FWorldPartitionActorDesc > AActor::CreateActorDesc () const inherited
Creates an initialized actor descriptor from this actor.
CreateClassActorDesc()
virtual TUniquePtr< class FWorldPartitionActorDesc > AActor::CreateClassActorDesc () const virtual inherited
Creates an uninitialized actor descriptor from this actor.
Meant to be called on the class CDO.
CreateComponentFromTemplate()
UActorComponent * AActor::CreateComponentFromTemplate (UActorComponent * Template, const FName InName = NAME_None) inherited
Util to create a component based on a template.
CreateComponentFromTemplateData()
UActorComponent * AActor::CreateComponentFromTemplateData (const struct FBlueprintCookedComponentInstancingData * TemplateData, const FName InName = NAME_None) inherited
CreateInputComponent()
virtual void AActor::CreateInputComponent (TSubclassOf< UInputComponent > InputComponentToCreate) virtual inherited
Creates an input component from the input component passed in.
Parameters
InputComponentToCreate The UInputComponent to create.
References CreateInputComponent().
CreateOrUpdateActorFolder()
bool AActor::CreateOrUpdateActorFolder () inherited
Creates or updates actor's folder object if necessary.
Returns false if an error occured while creating folder.
References CreateOrUpdateActorFolder().
DebugShowComponentHierarchy()
void AActor::DebugShowComponentHierarchy (const TCHAR * Info, bool bShowPosition = true) inherited
Debug helper to show the component hierarchy of this actor.
Parameters
Info Optional String to display at top of info
bShowPosition If true, will display component's position in world space
DebugShowOneComponentHierarchy()
void AActor::DebugShowOneComponentHierarchy (USceneComponent * SceneComp, int32 & NestLevel, bool bShowPosition) inherited
Debug helper for showing the component hierarchy of one component.
Destroy()
bool AActor::Destroy (bool bNetForce = false, bool bShouldModifyLevel = true) inherited
Destroy this actor.
Returns true if the actor is destroyed or already marked for destruction, false if indestructible. Destruction is latent. It occurs at the end of the tick.
Parameters
bNetForce [opt] Ignored unless called during play. Default is false.
bShouldModifyLevel [opt] If true, Modify() the level before removing the actor. Default is true.
Returns
true if destroyed or already marked for destruction, false if indestructible.
References Destroy().
DestroyConstructedComponents()
void AActor::DestroyConstructedComponents () inherited
Destroys the constructed components.
Destroyed()
virtual void AActor::Destroyed () virtual inherited
Called when this actor is explicitly being destroyed during gameplay or in the editor, not called during level streaming or gameplay ending.
Reimplemented in AController, APawn, APlayerController, and APlayerState.
References Destroyed().
DestroyNetworkActorHandled()
virtual bool AActor::DestroyNetworkActorHandled () virtual inherited
Called by DestroyActor(), gives actors a chance to op out of actor destruction Used by network code to have the net connection timeout/cleanup first.
Returns
true if DestroyActor() should not continue with actor destruction, false otherwise
Reimplemented in APlayerController.
DestroyReplicatedSubObjectOnRemotePeers() [1/2]
void AActor::DestroyReplicatedSubObjectOnRemotePeers (UActorComponent * OwnerComponent, UObject * SubObject) inherited
Similar to the other destroy function but for subobjects owned by an ActorComponent.
DestroyReplicatedSubObjectOnRemotePeers() [2/2]
void AActor::DestroyReplicatedSubObjectOnRemotePeers (UObject * SubObject) inherited
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated.
Note it is up to the caller to delete the local object on the authority. If you are using the legacy subobject replication method (ReplicateSubObjects() aka bReplicateUsingRegisteredSubObjectList=false) make sure the subobject doesn't get replicated there either.
Parameters
SubObject THe SubObject to delete
DetachAllSceneComponents()
void AActor::DetachAllSceneComponents (class USceneComponent * InParentComponent, const FDetachmentTransformRules & DetachmentRules) inherited
Detaches all SceneComponents in this Actor from the supplied parent SceneComponent.
Parameters
InParentComponent SceneComponent to detach this actor's components from
DetachmentRules Rules to apply when detaching components
References DetachAllSceneComponents().
DetachFromActor()
void AActor::DetachFromActor (const FDetachmentTransformRules & DetachmentRules) inherited
Detaches the RootComponent of this Actor from any SceneComponent it is currently attached to.
Parameters
DetachmentRules How to handle transforms when detaching.
References DetachFromActor().
DetachRootComponentFromParent()
void AActor::DetachRootComponentFromParent (bool bMaintainWorldPosition = true) inherited
DEPRECATED - Use DetachFromActor() instead.
References DetachRootComponentFromParent().
DisableComponentsSimulatePhysics()
void AActor::DisableComponentsSimulatePhysics () inherited
Stop all simulation from all components in this actor.
References DisableComponentsSimulatePhysics().
DisableInput()
virtual void AActor::DisableInput (class APlayerController * PlayerController) virtual inherited
Removes this actor from the stack of input being handled by a PlayerController.
Parameters
PlayerController The PlayerController whose input events we no longer want to receive. If null, this actor will stop receiving input from all PlayerControllers.
Reimplemented in APawn, and APlayerController.
References DisableInput().
DispatchBeginPlay()
void AActor::DispatchBeginPlay (bool bFromLevelStreaming = false) inherited
Initiate a begin play call on this Actor, will handle calling in the correct order.
References DispatchBeginPlay().
DispatchBlockingHit()
void AActor::DispatchBlockingHit (UPrimitiveComponent * MyComp, UPrimitiveComponent * OtherComp, bool bSelfMoved, FHitResult const & Hit) inherited
Call ReceiveHit, as well as delegates on Actor and Component.
References DispatchBlockingHit().
DispatchPhysicsCollisionHit()
virtual void AActor::DispatchPhysicsCollisionHit (const struct FRigidBodyCollisionInfo & MyInfo, const struct FRigidBodyCollisionInfo & OtherInfo, const FCollisionImpactData & RigidCollisionData) virtual inherited
Dispatches ReceiveHit virtual and OnComponentHit delegate.
References AActor().
DisplayDebug()
virtual void AActor::DisplayDebug (class UCanvas * Canvas, const class FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) virtual inherited
Draw important Actor variables on canvas.
HUD will call DisplayDebug() on the current ViewTarget when the ShowDebug exec is used
Parameters
Canvas Canvas to draw on
DebugDisplay Contains information about what debug data to display
YL [in] Height of the previously drawn line. [out] Height of the last line drawn by this function.
YPos [in] Y position on Canvas for the previously drawn line. YPos += YL, gives position to draw text for next debug line. [out] Y position on Canvas for the last line drawn by this function.
DoesAcceptClass()
bool ALightWeightInstanceManager::DoesAcceptClass (const UClass * OtherClass) const
References DoesAcceptClass().
DoesRepresentClass()
bool ALightWeightInstanceManager::DoesRepresentClass (const UClass * OtherClass) const
References DoesRepresentClass().
DrawDebugComponents()
void AActor::DrawDebugComponents (FColor const & BaseColor = FColor::White) const inherited
Debug rendering to visualize the component tree for this actor.
EditorApplyMirror()
virtual void AActor::EditorApplyMirror (const FVector & MirrorScale, const FVector & PivotLocation) virtual inherited
Called by MirrorActors to perform a mirroring operation on the actor.
EditorApplyRotation()
virtual void AActor::EditorApplyRotation (const FRotator & DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) virtual inherited
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
The default implementation is simply to modify the actor's rotation.
Reimplemented in APawn.
EditorApplyScale()
virtual void AActor::EditorApplyScale (const FVector & DeltaScale, const FVector * PivotLocation, bool bAltDown, bool bShiftDown, bool bCtrlDown) virtual inherited
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
The default implementation is simply to modify the actor's draw scale.
EditorApplyTranslation()
virtual void AActor::EditorApplyTranslation (const FVector & DeltaTranslation, bool bAltDown, bool bShiftDown, bool bCtrlDown) virtual inherited
Called by ApplyDeltaToActor to perform an actor class-specific operation based on widget manipulation.
The default implementation is simply to translate the actor's location.
EditorCanAttachFrom()
virtual bool AActor::EditorCanAttachFrom (const AActor * InChild, FText & OutReason) const virtual inherited
Returns true if this actor is allowed to be attached from the given actor.
References AActor(), and EditorCanAttachFrom().
EditorCanAttachTo()
virtual bool AActor::EditorCanAttachTo (const AActor * InParent, FText & OutReason) const virtual inherited
Returns true if this actor is allowed to be attached to the given actor.
References AActor(), and EditorCanAttachTo().
EditorCanDetachFrom()
virtual bool AActor::EditorCanDetachFrom (const AActor * InParent, FText & OutReason) const inline virtual inherited
Returns true if this actor is allowed to be detached from the given actor.
Definition at line 2670 of file Actor.h.
References AActor(), and EditorCanDetachFrom().
EditorGetUnderlyingActors()
virtual void AActor::EditorGetUnderlyingActors (TSet< AActor * > & OutUnderlyingActors) const virtual inherited
Get underlying actors.
EditorKeyPressed()
virtual void AActor::EditorKeyPressed (FKey Key, EInputEvent Event) inline virtual inherited
Called by InputKey when an unhandled key is pressed with a selected actor.
Definition at line 2697 of file Actor.h.
References EditorKeyPressed().
EditorReplacedActor()
virtual void AActor::EditorReplacedActor (AActor * OldActor) virtual inherited
Called by ReplaceSelectedActors to allow a new actor to copy properties from an old actor when it is replaced.
References AActor().
EnableInput()
virtual void AActor::EnableInput (class APlayerController * PlayerController) virtual inherited
Pushes this actor on to the stack of input being handled by a PlayerController.
Parameters
PlayerController The PlayerController whose input events we want to receive.
Reimplemented in APawn, and APlayerController.
References EnableInput().
EndPlay()
virtual void AActor::EndPlay (const EEndPlayReason::Type EndPlayReason) protected virtual inherited
Overridable function called whenever this actor is being removed from a level.
Reimplemented in APawn, and APlayerController.
References EndPlay().
EndViewTarget()
virtual void AActor::EndViewTarget (class APlayerController * PC) virtual inherited
Called when this actor is no longer the given PlayerController's ViewTarget.
Also triggers the Blueprint event K2_OnEndViewTarget.
Reimplemented in APawn.
References EndViewTarget().
ExchangeNetRoles()
void AActor::ExchangeNetRoles (bool bRemoteOwner) inherited
Swaps Role and RemoteRole if client.
ExecuteConstruction()
bool AActor::ExecuteConstruction (const FTransform & Transform, const struct FRotationConversionCache * TransformRotationCache, const class FComponentInstanceDataCache * InstanceDataCache, bool bIsDefaultTransform = false, ESpawnActorScaleMethod TransformScaleMethod = ESpawnActorScaleMethod::OverrideRootScale) inherited
Run any construction script for this Actor.
Will call OnConstruction.
Parameters
Transform The transform to construct the actor at.
TransformRotationCache Optional rotation cache to use when applying the transform.
InstanceDataCache Optional cache of state to apply to newly created components (e.g. precomputed lighting)
bIsDefaultTransform Whether or not the given transform is a "default" transform, in which case it can be overridden by template defaults
Returns
Returns false if the hierarchy was not error free and we've put the Actor is disaster recovery mode
References ESpawnActorScaleMethod.
FactoryTransactionAnnotation()
virtual TSharedPtr< ITransactionObjectAnnotation > AActor::FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const override virtual inherited
FellOutOfWorld()
virtual void AActor::FellOutOfWorld (const class UDamageType & dmgType) virtual inherited
Called when the actor falls out of the world 'safely' (below KillZ and such)
Reimplemented in APlayerController.
References FellOutOfWorld().
FindActor()
virtual AActor * ALightWeightInstanceManager::FindActor (const FActorInstanceHandle & Handle) override virtual
References AActor::AActor(), FActorInstanceHandle, and FindActor().
FindActorForHandle()
bool ALightWeightInstanceManager::FindActorForHandle (const FActorInstanceHandle & Handle) const protected
References FActorInstanceHandle.
FindActorInPackage()
AActor * AActor::FindActorInPackage (UPackage * InPackage, bool bEvenIfPendingKill = true) static inherited
References AActor().
FindComponentByClass() [1/2]
template<class T> T * AActor::FindComponentByClass () const inline inherited
Templatized version of FindComponentByClass that handles casting for you.
Definition at line 3782 of file Actor.h.
References FindComponentByClass(), and FindComponentByClass().
FindComponentByClass() [2/2]
virtual UActorComponent * AActor::FindComponentByClass (const TSubclassOf< UActorComponent > ComponentClass) const virtual inherited
Searches components array and returns first encountered component of the specified class, native version of GetComponentByClass.
Reimplemented in ACharacter.
FindComponentByInterface() [1/3]
template<class T UE_REQUIRES> T * AActor::FindComponentByInterface () const inline inherited
Templatized version of FindComponentByInterface that handles casting for you.
Definition at line 3801 of file Actor.h.
References FindComponentByInterface(), and FindComponentByInterface().
FindComponentByInterface() [2/3]
template<class T UE_REQUIRES> T * AActor::FindComponentByInterface () const inline inherited
Templatized version of FindComponentByInterface that handles casting for you.
Definition at line 3808 of file Actor.h.
References FindComponentByInterface().
FindComponentByInterface() [3/3]
virtual UActorComponent * AActor::FindComponentByInterface (const TSubclassOf< UInterface > Interface) const virtual inherited
Searches components array and returns first encountered component that implements the given interface.
References FindComponentByInterface().
FindComponentByTag() [1/2]
template<class T> T * AActor::FindComponentByTag (const FName & Tag) const inline inherited
Templatized version of FindComponentByTag that handles casting for you.
Definition at line 3791 of file Actor.h.
References FindComponentByTag().
FindComponentByTag() [2/2]
UActorComponent * AActor::FindComponentByTag (TSubclassOf< UActorComponent > ComponentClass, FName Tag) const inherited
Searches components array and returns first encountered component with a given tag.
References FindComponentByTag().
FindIndexForActor()
int32 ALightWeightInstanceManager::FindIndexForActor (const AActor * InActor) const
References AActor::AActor(), and FindIndexForActor().
FindOrCreateActor()
virtual AActor * ALightWeightInstanceManager::FindOrCreateActor (const FActorInstanceHandle & Handle) override virtual
References AActor::AActor(), FActorInstanceHandle, and FindOrCreateActor().
FinishAddComponent()
void AActor::FinishAddComponent (UActorComponent * Component, bool bManualAttachment, const FTransform & RelativeTransform) inherited
Completes the creation of a new actor component.
Called either from blueprint after expose on spawn properties are set, or directly from AddComponent
See also
UK2Node_AddComponent DO NOT CALL MANUALLY - BLUEPRINT INTERNAL USE ONLY (for Add Component nodes)
Parameters
Component The component created in AddComponent to finish creation of
bManualAttachment Whether manual or automatic attachment is to be used
RelativeTransform The relative transform between the new component and its attach parent (automatic only)
References FinishAddComponent().
FinishAndRegisterComponent()
void AActor::FinishAndRegisterComponent (UActorComponent * Component) inherited
Helper function to register the specified component, and add it to the serialized components array.
Parameters
Component Component to be finalized
FinishSpawning()
void AActor::FinishSpawning (const FTransform & Transform, bool bIsDefaultTransform = false, const FComponentInstanceDataCache * InstanceDataCache = nullptr, ESpawnActorScaleMethod TransformScaleMethod = ESpawnActorScaleMethod::OverrideRootScale) inherited
Called to finish the spawning process, generally in the case of deferred spawning.
References ESpawnActorScaleMethod.
FixupActorFolder()
void AActor::FixupActorFolder () inherited
Detects and fixes invalid actor folder.
References FixupActorFolder().
FixupDataLayers()
void AActor::FixupDataLayers (bool bRevertChangesOnLockedDataLayer = false) inherited
FlushNetDormancy()
void AActor::FlushNetDormancy () inherited
Forces dormant actor to replicate but doesn't change NetDormancy state (i.e., they will go dormant again if left dormant)
References FlushNetDormancy().
ForceNetRelevant()
virtual void AActor::ForceNetRelevant () virtual inherited
Forces this actor to be net relevant if it is not already by default.
References ForceNetRelevant().
ForceNetUpdate()
virtual void AActor::ForceNetUpdate () virtual inherited
Force actor to be updated to clients/demo net drivers.
References ForceNetUpdate().
ForcePropertyCompare()
void AActor::ForcePropertyCompare () inherited
Forces properties on this actor to do a compare for one frame (rather than share shadow state)
References ForcePropertyCompare().
ForEachAttachedActors()
void AActor::ForEachAttachedActors (TFunctionRef< bool(class AActor *)> Functor) const inherited
Call a functor for Actors which are attached directly to a component in this actor.
Functor should return true to carry on, false to abort.
References AActor(), and ForEachAttachedActors().
ForEachComponent() [1/2]
template<class ComponentType, typename Func> void AActor::ForEachComponent (bool bIncludeFromChildActors, Func InFunc) const inline inherited
Calls the compile-time lambda on each component of the specified type.
Parameters
ComponentType The component class to find all components of a class derived from
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 3911 of file Actor.h.
ForEachComponent() [2/2]
template<typename Func> void AActor::ForEachComponent (bool bIncludeFromChildActors, Func InFunc) const inline inherited
Calls the compile-time lambda on each valid component.
Parameters
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 3921 of file Actor.h.
ForEachComponentOfActorClassDefault() [1/2]
void AActor::ForEachComponentOfActorClassDefault (const TSubclassOf< AActor > & InActorClass, const TSubclassOf< UActorComponent > & InComponentClass, TFunctionRef< bool(const UActorComponent *)> InFunc) static inherited
Iterate over the components of ActorClass's CDO, including the ones added via the BP editor (which AActor.GetComponents fails to return).
Parameters
InActorClass Class of AActor for which we will retrieve all components.
InComponentClass Only consider components of this type.
InFunc Code that will be executed for each component. Must return true to continue iteration, or false to stop.
ForEachComponentOfActorClassDefault() [2/2]
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type> void AActor::ForEachComponentOfActorClassDefault (const TSubclassOf< AActor > & InActorClass, TFunctionRef< bool(const TComponentClass *)> InFunc) inline static inherited
Templated version of ForEachComponentOfActorClassDefault()
See also
ForEachComponentOfActorClassDefault
Definition at line 4240 of file Actor.h.
References ForEachComponentOfActorClassDefault().
GatherCurrentMovement()
virtual void AActor::GatherCurrentMovement () virtual inherited
Fills ReplicatedMovement property.
Reimplemented in ACharacter.
GetAcceptedClass()
UClass * ALightWeightInstanceManager::GetAcceptedClass () const
References GetAcceptedClass().
GetActorBounds()
virtual void AActor::GetActorBounds (bool bOnlyCollidingComponents, FVector & Origin, FVector & BoxExtent, bool bIncludeFromChildActors = false) const virtual inherited
Returns the bounding box of all components that make up this Actor (excluding ChildActorComponents).
Parameters
bOnlyCollidingComponents If true, will only return the bounding box for components with collision enabled.
Origin Set to the center of the actor in world space
BoxExtent Set to half the actor's size in 3d space
bIncludeFromChildActors If true then recurse in to ChildActor components
References GetActorBounds(), and K2_GetRootComponent().
GetActorClassDefaultComponent() [1/2]
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type> const TComponentClass * AActor::GetActorClassDefaultComponent (const TSubclassOf< AActor > & InActorClass) inline static inherited
Templated version of GetActorClassDefaultComponent()
See also
GetActorClassDefaultComponent
Definition at line 4220 of file Actor.h.
References GetActorClassDefaultComponent().
GetActorClassDefaultComponent() [2/2]
const UActorComponent * AActor::GetActorClassDefaultComponent (const TSubclassOf< AActor > & InActorClass, const TSubclassOf< UActorComponent > & InComponentClass) static inherited
Fetches the first component of ActorClass's CDO which match the requested component class.
Will include the components added via the BP editor (which AActor.GetComponents fails to do for CDOs).
Parameters
InActorClass Class of AActor for which we will retrieve all components.
InComponentClass Only retrieve components of this type.
OutComponents this is where the found components will end up. Note that the preexisting contents of OutComponents will get overridden.
GetActorClassDefaultComponentByName() [1/2]
const UActorComponent * AActor::GetActorClassDefaultComponentByName (const TSubclassOf< AActor > & InActorClass, const TSubclassOf< UActorComponent > & InComponentClass, FName InComponentName) static inherited
Get the component of ActorClass's CDO that matches the given object name.
Will consider all components, including the ones added via the BP editor (which AActor.GetComponents fails to do for CDOs).
Parameters
InActorClass Class of AActor for which we will search all components.
InComponentClass Only consider components of this type.
OutComponents this is where the found components will end up. Note that the preexisting contents of OutComponents will get overridden.
GetActorClassDefaultComponentByName() [2/2]
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type> const TComponentClass * AActor::GetActorClassDefaultComponentByName (const TSubclassOf< AActor > & InActorClass, FName InComponentName) inline static inherited
Templated version of GetActorClassDefaultComponentByName()
See also
GetActorClassDefaultComponentByName
Definition at line 4230 of file Actor.h.
References GetActorClassDefaultComponentByName().
GetActorClassDefaultComponents() [1/2]
void AActor::GetActorClassDefaultComponents (const TSubclassOf< AActor > & InActorClass, const TSubclassOf< UActorComponent > & InComponentClass, TArray< const UActorComponent * > & OutComponents) static inherited
Fetches all the components of ActorClass's CDO, including the ones added via the BP editor (which AActor.GetComponents fails to do for CDOs).
Parameters
InActorClass Class of AActor for which we will retrieve all components.
InComponentClass Only retrieve components of this type.
OutComponents this is where the found components will end up. Note that the preexisting contents of OutComponents will get overridden.
GetActorClassDefaultComponents() [2/2]
template<typename TComponentClass = UActorComponent, typename = typename TEnableIf<TIsDerivedFrom<TComponentClass, UActorComponent>::IsDerived>::Type> void AActor::GetActorClassDefaultComponents (const TSubclassOf< AActor > & InActorClass, TArray< const TComponentClass * > & OutComponents) inline static inherited
Templated version of GetActorClassDefaultComponents()
See also
GetActorClassDefaultComponents
Definition at line 4206 of file Actor.h.
References ForEachComponentOfActorClassDefault().
GetActorClassToSpawn()
virtual UClass * ALightWeightInstanceManager::GetActorClassToSpawn (const FActorInstanceHandle & Handle) const protected virtual
References FActorInstanceHandle.
GetActorDataLayers()
TArray< FActorDataLayer > const & AActor::GetActorDataLayers () const inline inherited
Definition at line 1493 of file Actor.h.
References DataLayers, and GetActorDataLayers().
GetActorDescProperties()
virtual void AActor::GetActorDescProperties (FPropertyPairsMap & PropertyPairsMap) const virtual inherited
Add properties to the actor desc.
GetActorEnableCollision()
FORCEINLINE_DEBUGGABLE bool AActor::GetActorEnableCollision () const inherited
Get current state of collision for the whole actor.
Definition at line 4906 of file Actor.h.
GetActorEyesViewPoint()
virtual void AActor::GetActorEyesViewPoint (FVector & OutLocation, FRotator & OutRotation) const virtual inherited
Returns the point of view of the actor.
Note that this doesn't mean the camera, but the 'eyes' of the actor. For example, for a Pawn, this would define the eye height location, and view rotation (which is different from the pawn rotation which has a zeroed pitch component). A camera first person view will typically use this view point. Most traces (weapon, AI) will be done from this view point.
Parameters
OutLocation - location of view point
OutRotation - view rotation of actor.
Reimplemented in AController, APawn, and APlayerController.
References GetActorEyesViewPoint().
GetActorForwardVector()
FORCEINLINE_DEBUGGABLE FVector AActor::GetActorForwardVector () const inherited
Get the forward (X) vector (length 1.0) from this Actor, in world space.
Definition at line 4869 of file Actor.h.
References RootComponent.
GetActorGuid()
const FGuid & AActor::GetActorGuid () const inline inherited
Returns this actor's Guid.
Actor Guids are only available in editor builds.
Definition at line 1134 of file Actor.h.
References ActorGuid.
GetActorInstanceGuid()
const FGuid & AActor::GetActorInstanceGuid () const inline inherited
Returns this actor's instance Guid.
Actor Guids are only available in editor builds.
Definition at line 1137 of file Actor.h.
References ActorGuid, and ActorInstanceGuid.
GetActorLabel()
const FString & AActor::GetActorLabel (bool bCreateIfNone = true) const inherited
Returns this actor's current label.
Actor labels are only available in development builds.
References GetActorLabel().
GetActorLabelView()
FStringView AActor::GetActorLabelView () const inline inherited
Definition at line 1207 of file Actor.h.
GetActorLocation()
FVector AActor::GetActorLocation () const inline inherited
Returns the location of the RootComponent of this Actor.
Definition at line 2482 of file Actor.h.
References RootComponent.
GetActorNameOrLabel()
FString AActor::GetActorNameOrLabel () const inline inherited
Definition at line 1196 of file Actor.h.
GetActorQuat()
FQuat AActor::GetActorQuat () const inline inherited
Returns the quaternion of the RootComponent of this Actor.
Definition at line 2500 of file Actor.h.
References RootComponent.
GetActorRelativeScale3D()
FVector AActor::GetActorRelativeScale3D () const inherited
Return the actor's relative scale 3d.
References GetActorRelativeScale3D().
GetActorRightVector()
FORCEINLINE_DEBUGGABLE FVector AActor::GetActorRightVector () const inherited
Get the right (Y) vector (length 1.0) from this Actor, in world space.
Definition at line 4879 of file Actor.h.
References RootComponent.
GetActorRotation()
FRotator AActor::GetActorRotation () const inline inherited
Returns the rotation of the RootComponent of this Actor.
Definition at line 2488 of file Actor.h.
References RootComponent.
GetActorScale()
FVector AActor::GetActorScale () const inline inherited
Returns the scale of the RootComponent of this Actor.
Definition at line 2494 of file Actor.h.
References RootComponent.
GetActorScale3D()
FVector AActor::GetActorScale3D () const inherited
Returns the Actor's world-space scale.
References GetActorScale3D().
GetActorTickInterval()
float AActor::GetActorTickInterval () const inherited
Returns the tick interval of this actor's primary tick function.
References GetActorTickInterval().
GetActorTimeDilation() [1/2]
float AActor::GetActorTimeDilation () const inherited
Get ActorTimeDilation - this can be used for input control or speed control for slomo.
We don't want to scale input globally because input can be used for UI, which do not care for TimeDilation.
References GetActorTimeDilation().
GetActorTimeDilation() [2/2]
float AActor::GetActorTimeDilation (const UWorld & ActorWorld) const inherited
More efficient version that takes the Actor's current world.
References GetActorTimeDilation().
GetActorTransform()
const FTransform & AActor::GetActorTransform () const inline inherited
Returns the transform of the RootComponent of this Actor.
Definition at line 2476 of file Actor.h.
References RootComponent.
GetActorUpVector()
FORCEINLINE_DEBUGGABLE FVector AActor::GetActorUpVector () const inherited
Get the up (Z) vector (length 1.0) from this Actor, in world space.
Definition at line 4874 of file Actor.h.
References RootComponent.
GetAllChildActors()
void AActor::GetAllChildActors (TArray< AActor * > & ChildActors, bool bIncludeDescendants = true) const inherited
Returns a list of all actors spawned by our Child Actor Components, including children of children.
This does not return the contents of the Children array
References AActor(), and GetAllChildActors().
GetAssetRegistryTags() [1/2]
virtual void AActor::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override virtual inherited
GetAssetRegistryTags() [2/2]
virtual void AActor::GetAssetRegistryTags (TArray< FAssetRegistryTag > & OutTags) const override virtual inherited
References GetAssetRegistryTags().
GetAttachedActors()
void AActor::GetAttachedActors (TArray< AActor * > & OutActors, bool bResetArray = true, bool bRecursivelyIncludeAttachedActors = false) const inherited
Find all Actors which are attached directly to a component in this actor.
References AActor(), and GetAttachedActors().
GetAttachmentReplication()
const struct FRepAttachment & AActor::GetAttachmentReplication () const inline inherited
Get read-only access to current AttachmentReplication.
Definition at line 805 of file Actor.h.
References AttachmentReplication, and GetAttachmentReplication().
GetAttachParentActor()
AActor * AActor::GetAttachParentActor () const inherited
Walk up the attachment chain from RootComponent until we encounter a different actor, and return it.
If we are not attached to a component in a different actor, returns nullptr
References AActor(), and GetAttachParentActor().
GetAttachParentSocketName()
FName AActor::GetAttachParentSocketName () const inherited
Walk up the attachment chain from RootComponent until we encounter a different actor, and return the socket name in the component.
If we are not attached to a component in a different actor, returns NAME_None
References GetAttachParentSocketName().
GetAutoDestroyWhenFinished()
bool AActor::GetAutoDestroyWhenFinished () const inline inherited
Definition at line 541 of file Actor.h.
References GetAutoDestroyWhenFinished().
GetBrowseToAssetOverride()
const FString & AActor::GetBrowseToAssetOverride () const inherited
Gets metadata on the Actor that says which package to show in the Content Browser when browsing to it, or an empty string if there is no override.
GetCanBeDamagedPropertyName()
const FName AActor::GetCanBeDamagedPropertyName () inline static inherited
Gets the property name for bCanBeDamaged.
This exists so subclasses don't need to have direct access to the bCanBeDamaged property so it can be made private later.
Definition at line 4515 of file Actor.h.
References AActor().
GetComponentByClass() [1/2]
template<class T> T * AActor::GetComponentByClass () const inline inherited
Templated version of GetComponentByClass.
Definition at line 3752 of file Actor.h.
References FindComponentByClass(), and GetComponentByClass().
GetComponentByClass() [2/2]
UActorComponent * AActor::GetComponentByClass (TSubclassOf< UActorComponent > ComponentClass) const inherited
Searches components array and returns first encountered component of the specified class.
References GetComponentByClass().
GetComponents() [1/6]
const TSet< UActorComponent * > & AActor::GetComponents () const inline inherited
Get a direct reference to the Components set rather than a copy with the null pointers removed.
WARNING: anything that could cause the component to change ownership or be destroyed will invalidate this array, so use caution when iterating this set!
Definition at line 4039 of file Actor.h.
GetComponents() [2/6]
template<class ComponentType, class AllocatorType> void AActor::GetComponents (TArray< ComponentType, AllocatorType > & OutComponents, bool bIncludeFromChildActors = false) const inline inherited
Get all components derived from class 'ComponentType' and fill in the OutComponents array with the result.
It's recommended to use TArrays with a TInlineAllocator to potentially avoid memory allocation costs. TInlineComponentArray is defined to make this easier, for example: { TInlineComponentArray<UPrimitiveComponent*> PrimComponents(Actor); }
Parameters
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 3958 of file Actor.h.
GetComponents() [3/6]
template<class T, class AllocatorType> void AActor::GetComponents (TArray< T *, AllocatorType > & OutComponents, bool bIncludeFromChildActors = false) const inline inherited
Get all components derived from class 'ComponentType' and fill in the OutComponents array with the result.
It's recommended to use TArrays with a TInlineAllocator to potentially avoid memory allocation costs. TInlineComponentArray is defined to make this easier, for example: { TInlineComponentArray<UPrimitiveComponent*> PrimComponents(Actor); }
Parameters
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 3980 of file Actor.h.
GetComponents() [4/6]
template<class T, class AllocatorType> void AActor::GetComponents (TArray< TObjectPtr< T >, AllocatorType > & OutComponents, bool bIncludeFromChildActors = false) const inline inherited
Get all components derived from class 'T' and fill in the OutComponents array with the result.
It's recommended to use TArrays with a TInlineAllocator to potentially avoid memory allocation costs. TInlineComponentArray is defined to make this easier, for example: { TInlineComponentArray<UPrimitiveComponent*> PrimComponents(Actor); }
Parameters
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 4004 of file Actor.h.
GetComponents() [5/6]
template<class AllocatorType> void AActor::GetComponents (TArray< UActorComponent *, AllocatorType > & OutComponents, bool bIncludeFromChildActors = false) const inline inherited
UActorComponent specialization of GetComponents() to avoid unnecessary casts.
It's recommended to use TArrays with a TInlineAllocator to potentially avoid memory allocation costs. TInlineComponentArray is defined to make this easier, for example: { TInlineComponentArray<UActorComponent*> PrimComponents; Actor->GetComponents(PrimComponents); }
Parameters
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 4025 of file Actor.h.
GetComponents() [6/6]
template<class AllocatorType, class ComponentType> void AActor::GetComponents (TSubclassOf< UActorComponent > ComponentClass, TArray< ComponentType *, AllocatorType > & OutComponents, bool bIncludeFromChildActors = false) const inline inherited
Get all components derived from specified ComponentClass and fill in the OutComponents array with the result.
It's recommended to use TArrays with a TInlineAllocator to potentially avoid memory allocation costs. TInlineComponentArray is defined to make this easier, for example: { TInlineComponentArray<UPrimitiveComponent*> PrimComponents(Actor); }
Parameters
ComponentClass The component class to find all components of a class derived from
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
Definition at line 3938 of file Actor.h.
GetComponentsBoundingBox()
virtual FBox AActor::GetComponentsBoundingBox (bool bNonColliding = false, bool bIncludeFromChildActors = false) const virtual inherited
Returns the world space bounding box of all components in this Actor.
Parameters
bNonColliding Indicates that you want to include non-colliding components in the bounding box
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
References GetComponentsBoundingBox().
GetComponentsBoundingCylinder()
virtual void AActor::GetComponentsBoundingCylinder (float & CollisionRadius, float & CollisionHalfHeight, bool bNonColliding = false, bool bIncludeFromChildActors = false) const virtual inherited
Get half-height/radius of a big axis-aligned cylinder around this actors registered colliding components, or all registered components if bNonColliding is false.
Parameters
bNonColliding Indicates that you want to include non-colliding components in the bounding cylinder
bIncludeFromChildActors If true then recurse in to ChildActor components and find components of the appropriate type in those Actors as well
References GetComponentsBoundingCylinder().
GetComponentsByInterface()
TArray< UActorComponent * > AActor::GetComponentsByInterface (TSubclassOf< UInterface > Interface) const inherited
Gets all the components that implements the given interface.
References GetComponentsByInterface().
GetComponentsByTag()
TArray< UActorComponent * > AActor::GetComponentsByTag (TSubclassOf< UActorComponent > ComponentClass, FName Tag) const inherited
Gets all the components that inherit from the given class with a given tag.
References GetComponentsByTag().
GetComponentsCollisionResponseToChannel()
virtual ECollisionResponse AActor::GetComponentsCollisionResponseToChannel (ECollisionChannel Channel) const virtual inherited
Get Collision Response to the passed in Channel for all components It returns Max of state - i.e.
if Component A overlaps, but if Component B blocks, it will return block as response if Component A ignores, but if Component B overlaps, it will return overlap
References GetComponentsCollisionResponseToChannel().
GetContentBundleGuid()
const FGuid & AActor::GetContentBundleGuid () const inline inherited
Returns this actor's content bundle Guid.
Definition at line 1140 of file Actor.h.
References ContentBundleGuid.
GetCustomIconName()
virtual FName AActor::GetCustomIconName () const inline virtual inherited
Returns a custom brush icon name to use in place of the automatic class icon where actors are represented via 2d icons in the editor (e.g scene outliner and menus)
Definition at line 2794 of file Actor.h.
GetDataLayerAssets()
TArray< const UDataLayerAsset * > AActor::GetDataLayerAssets (bool bIncludeExternalDataLayerAsset = true) const inherited
GetDataLayerAssetsPropertyName()
const FName AActor::GetDataLayerAssetsPropertyName () inline static inherited
Definition at line 1453 of file Actor.h.
References AActor(), and DataLayerAssets.
GetDataLayerInstanceNames()
TArray< FName > AActor::GetDataLayerInstanceNames () const inherited
GetDataLayerInstances() [1/2]
TArray< const UDataLayerInstance * > AActor::GetDataLayerInstances () const inherited
GetDataLayerInstances() [2/2]
TArray< const UDataLayerInstance * > AActor::GetDataLayerInstances (const AWorldDataLayers * WorldDataLayers) const inline inherited
Definition at line 1496 of file Actor.h.
References GetDataLayerInstances().
GetDataLayerInstancesForLevel()
TArray< const UDataLayerInstance * > AActor::GetDataLayerInstancesForLevel () const inherited
GetDataLayerPropertyName()
const FName AActor::GetDataLayerPropertyName () inline static inherited
Definition at line 1454 of file Actor.h.
References AActor(), and DataLayers.
GetDebugName()
FString AActor::GetDebugName (const AActor * Actor) inline static inherited
Retrieves actor's name used for logging, or string "NULL" if Actor is null.
Definition at line 4361 of file Actor.h.
References AActor().
GetDefaultActorLabel()
virtual FString AActor::GetDefaultActorLabel () const virtual inherited
Returns this actor's default label (does not include any numeric suffix).
Actor labels are only available in development builds.
References GetDefaultActorLabel().
GetDefaultAttachComponent()
virtual USceneComponent * AActor::GetDefaultAttachComponent () const inline virtual inherited
Returns this actor's default attachment component for attaching children to.
Returns
The scene component to be used as parent
Definition at line 2467 of file Actor.h.
References GetRootComponent().
GetDistanceTo()
float AActor::GetDistanceTo (const AActor * OtherActor) const inherited
Returns the distance from this Actor to OtherActor.
References AActor(), and GetDistanceTo().
GetDotProductTo()
float AActor::GetDotProductTo (const AActor * OtherActor) const inherited
Returns the dot product from this Actor to OtherActor.
Returns -2.0 on failure. Returns 0.0 for coincidental actors.
References AActor(), and GetDotProductTo().
GetExternalDataLayerAsset()
const UExternalDataLayerAsset * AActor::GetExternalDataLayerAsset () const inherited
GetFolder()
FFolder AActor::GetFolder () const inherited
Returns a FFolder that contains the actor folder path and its folder root object.
References GetFolder().
GetFolderGuid()
FGuid AActor::GetFolderGuid (bool bDirectAccess = false) const inherited
References GetFolderGuid().
GetFolderPath()
FName AActor::GetFolderPath () const inherited
Returns this actor's folder path.
Actor folder paths are only available in development builds.
References GetFolderPath().
GetFolderRootObject()
FFolder::FRootObject AActor::GetFolderRootObject () const inherited
Returns the actor's folder root object.
Null, is interpreted as the actor's world.
References GetFolderRootObject().
GetFunctionCallspace()
virtual int32 AActor::GetFunctionCallspace (UFunction * Function, FFrame * Stack) override virtual inherited
References GetFunctionCallspace().
GetGameInstance() [1/2]
class UGameInstance * AActor::GetGameInstance () const inherited
Gets the GameInstance that ultimately contains this actor.
References GetGameInstance().
GetGameInstance() [2/2]
template<class T> T * AActor::GetGameInstance () const inline inherited
Gets the GameInstance that ultimately contains this actor cast to the template type.
May return NULL if the cast fails.
Definition at line 3735 of file Actor.h.
References GetGameInstance().
GetGameTimeSinceCreation()
float AActor::GetGameTimeSinceCreation () const inherited
The number of seconds (in game time) since this Actor was created, relative to Get Game Time In Seconds.
References GetGameTimeSinceCreation().
GetGridSize()
virtual int32 ALightWeightInstanceManager::GetGridSize () const virtual
References GetGridSize().
GetHiddenPropertyName()
const FName AActor::GetHiddenPropertyName () inline static inherited
Gets the property name for bHidden.
This exists so subclasses don't need to have direct access to the bHidden property so it can be made private later.
Definition at line 4463 of file Actor.h.
References AActor().
GetHLODLayer()
class UHLODLayer * AActor::GetHLODLayer () const inherited
Return the HLOD layer that should include this actor.
GetHLODLayerPropertyName()
const FName AActor::GetHLODLayerPropertyName () inline static inherited
Gets the property name for HLODLayer.
Definition at line 1002 of file Actor.h.
References AActor().
GetHLODRelevantComponents()
virtual TArray< UActorComponent * > AActor::GetHLODRelevantComponents () const virtual inherited
Return the list of components to use when building the HLOD representation of this actor.
GetHorizontalDistanceTo()
float AActor::GetHorizontalDistanceTo (const AActor * OtherActor) const inherited
Returns the distance from this Actor to OtherActor, ignoring Z.
References AActor(), and GetHorizontalDistanceTo().
GetHorizontalDotProductTo()
float AActor::GetHorizontalDotProductTo (const AActor * OtherActor) const inherited
Returns the dot product from this Actor to OtherActor, ignoring Z.
Returns -2.0 on failure. Returns 0.0 for coincidental actors.
References AActor(), and GetHorizontalDotProductTo().
GetHumanReadableName()
virtual FString AActor::GetHumanReadableName () const virtual inherited
Returns the human readable string representation of an object.
Reimplemented in AController, APawn, and APlayerState.
References GetHumanReadableName().
GetInputAxisKeyValue()
float AActor::GetInputAxisKeyValue (const FKey InputAxisKey) const inherited
Gets the value of the input axis key if input is enabled for this actor.
References GetInputAxisKeyValue().
GetInputAxisValue()
float AActor::GetInputAxisValue (const FName InputAxisName) const inherited
Gets the value of the input axis if input is enabled for this actor.
References GetInputAxisValue().
GetInputVectorAxisValue()
FVector AActor::GetInputVectorAxisValue (const FKey InputAxisKey) const inherited
Gets the value of the input axis key if input is enabled for this actor.
References GetInputVectorAxisValue().
GetInstanceComponents()
const TArray< UActorComponent * > & AActor::GetInstanceComponents () const inherited
Returns the instance components array.
References GetInstanceComponents().
GetInstigator() [1/2]
APawn * AActor::GetInstigator () const inherited
Returns the instigator for this actor, or nullptr if there is none.
References GetInstigator().
GetInstigator() [2/2]
template<class T> T * AActor::GetInstigator () const inline inherited
Get the instigator, cast as a specific class.
Returns
The instigator for this actor if it is the specified type, nullptr otherwise.
Definition at line 1413 of file Actor.h.
References GetInstigator().
GetInstigatorController() [1/2]
AController * AActor::GetInstigatorController () const inherited
Returns the instigator's controller for this actor, or nullptr if there is none.
References GetInstigatorController().
GetInstigatorController() [2/2]
template<class T> T * AActor::GetInstigatorController () const inline inherited
Returns the instigator's controller, cast as a specific class.
Returns
The instigator's controller for this actor if it is the specified type, nullptr otherwise.
Definition at line 1427 of file Actor.h.
References GetInstigatorController().
GetInstigatorPropertyName()
const FName AActor::GetInstigatorPropertyName () inline static inherited
Gets the property name for Instigator.
This exists so subclasses don't need to have direct access to the Instigator property so it can be made private later.
Definition at line 4612 of file Actor.h.
References AActor(), and GetInstigatorPropertyName().
GetIsReplicated()
bool AActor::GetIsReplicated () const inline inherited
Returns whether replication is enabled or not.
Definition at line 4091 of file Actor.h.
References bReplicates.
GetIsSpatiallyLoaded()
bool AActor::GetIsSpatiallyLoaded () const inherited
Returns true if this actor is spatially loaded.
GetIsSpatiallyLoadedPropertyName()
const FName AActor::GetIsSpatiallyLoadedPropertyName () inline static inherited
Gets the property name for bIsSpatiallyLoaded.
Definition at line 2643 of file Actor.h.
References AActor(), and bIsSpatiallyLoaded.
GetLastRenderTime()
virtual float AActor::GetLastRenderTime () const virtual inherited
Returns the most recent time any of this actor's components were rendered.
References GetLastRenderTime().
GetLevel()
ULevel * AActor::GetLevel () const inherited
Return the ULevel that this Actor is part of.
References GetLevel().
GetLevelForInstance()
virtual ULevel * ALightWeightInstanceManager::GetLevelForInstance (const int32 InstanceIndex) const inline override virtual
Definition at line 87 of file LightWeightInstanceManager.h.
References AActor::GetLevel().
GetLevelTransform()
FTransform AActor::GetLevelTransform () const inherited
Return the FTransform of the level this actor is a part of.
References GetLevelTransform().
GetLifeSpan()
virtual float AActor::GetLifeSpan () const virtual inherited
Get the remaining lifespan of this actor.
If zero is returned the actor lives forever.
References GetLifeSpan().
GetLifetimeReplicatedProps()
virtual void ALightWeightInstanceManager::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
Returns the properties used for network replication, this needs to be overridden by all actor classes with native replicated properties.
Reimplemented from AActor.
Reimplemented in ALightWeightInstanceStaticMeshManager.
References AActor::AActor(), and OnSpawnedActorDestroyed().
GetLocalRole()
ENetRole AActor::GetLocalRole () const inline inherited
Returns how much control the local machine has over this actor.
Definition at line 726 of file Actor.h.
References GetLocalRole().
GetLocation()
FVector ALightWeightInstanceManager::GetLocation (const FActorInstanceHandle & Handle) const
References FActorInstanceHandle, and GetLocation().
GetMinNetUpdateFrequency()
float AActor::GetMinNetUpdateFrequency () const inherited
Get the frequency to throttle down to when replicated properties are changing infrequently.
References GetMinNetUpdateFrequency().
GetName()
FString ALightWeightInstanceManager::GetName (const FActorInstanceHandle & Handle) const
References FActorInstanceHandle, and GetName().
GetNetConnection()
virtual class UNetConnection * AActor::GetNetConnection () const virtual inherited
Get the owning connection used for communicating between client/server.
Returns
NetConnection to the client or server for this actor
Reimplemented in APawn, and APlayerController.
GetNetCullDistanceSquared()
float AActor::GetNetCullDistanceSquared () const inherited
Get the square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
References GetNetCullDistanceSquared().
GetNetDormancy()
virtual bool AActor::GetNetDormancy (const FVector & ViewPos, const FVector & ViewDir, class AActor * Viewer, AActor * ViewTarget, UActorChannel * InChannel, float Time, bool bLowBandwidth) virtual inherited
Returns true if the actor should be dormant for a specific net connection.
Only checked for DORM_DormantPartial
References AActor().
GetNetDriver()
class UNetDriver * AActor::GetNetDriver () const inherited
Returns the net driver that this actor is bound to, may be null.
GetNetDriverName()
FName AActor::GetNetDriverName () const inline inherited
Returns name of the net driver associated with this actor (all RPCs will go out via this connection)
Definition at line 922 of file Actor.h.
References GetNetDriverName(), and NetDriverName.
GetNetMode()
FORCEINLINE_DEBUGGABLE ENetMode AActor::GetNetMode () const inherited
Get the network mode (dedicated server, client, standalone, etc) for this actor.
See also
IsNetMode()
Definition at line 4933 of file Actor.h.
References NetDriverName.
GetNetOwner()
FORCEINLINE_DEBUGGABLE const AActor * AActor::GetNetOwner () const virtual inherited
Return the actor responsible for replication, if any.
Typically the player controller
Reimplemented in APawn, and APlayerController.
Definition at line 4921 of file Actor.h.
References AActor(), and Owner.
GetNetOwningPlayer()
virtual class UPlayer * AActor::GetNetOwningPlayer () virtual inherited
Return the owning UPlayer (if any) of this actor if it's role is ROLE_Authority.
This will be a local player, a net connection, or nullptr.
Reimplemented in APawn, and APlayerController.
GetNetOwningPlayerAnyRole()
virtual class UPlayer * AActor::GetNetOwningPlayerAnyRole () virtual inherited
Return the owning UPlayer (if any) of this actor, regardless of it's current role.
This will be a local player, a net connection, or nullptr.
Reimplemented in APawn, and APlayerController.
GetNetPriority()
virtual float AActor::GetNetPriority (const FVector & ViewPos, const FVector & ViewDir, class AActor * Viewer, AActor * ViewTarget, UActorChannel * InChannel, float Time, bool bLowBandwidth) virtual inherited
Function used to prioritize actors when deciding which to replicate.
Parameters
ViewPos Position of the viewer
ViewDir Vector direction of viewer
Viewer "net object" owned by the client for whom net priority is being determined (typically player controller)
ViewTarget The actor that is currently being viewed/controlled by Viewer, usually a pawn
InChannel Channel on which this actor is being replicated.
Time Time since actor was last replicated
bLowBandwidth True if low bandwidth of viewer
Returns
Priority of this actor for replication, higher is more important
Reimplemented in APlayerController.
References AActor().
GetNetUpdateFrequency()
float AActor::GetNetUpdateFrequency () const inherited
Get the current frequency at which this object will be considered for replication.
References GetNetUpdateFrequency().
GetNumUncachedStaticLightingInteractions()
const int32 AActor::GetNumUncachedStaticLightingInteractions () const inherited
Returns NumUncachedStaticLightingInteractions for this actor.
GetOverlappingActors() [1/2]
void AActor::GetOverlappingActors (TArray< AActor * > & OverlappingActors, TSubclassOf< AActor > ClassFilter = nullptr) const inherited
Returns list of actors this actor is overlapping (any component overlapping any component).
Does not return itself.
Parameters
OverlappingActors [out] Returned list of overlapping actors
ClassFilter [optional] If set, only returns actors of this class or subclasses
References AActor(), and GetOverlappingActors().
GetOverlappingActors() [2/2]
void AActor::GetOverlappingActors (TSet< AActor * > & OverlappingActors, TSubclassOf< AActor > ClassFilter = nullptr) const inherited
Returns set of actors this actor is overlapping (any component overlapping any component).
Does not return itself.
Parameters
OverlappingActors [out] Returned list of overlapping actors
ClassFilter [optional] If set, only returns actors of this class or subclasses
References AActor(), and GetOverlappingActors().
GetOverlappingComponents() [1/2]
void AActor::GetOverlappingComponents (TArray< UPrimitiveComponent * > & OverlappingComponents) const inherited
Returns list of components this actor is overlapping.
References GetOverlappingComponents().
GetOverlappingComponents() [2/2]
void AActor::GetOverlappingComponents (TSet< UPrimitiveComponent * > & OverlappingComponents) const inherited
Returns set of components this actor is overlapping.
References GetOverlappingComponents().
GetOwner() [1/2]
FORCEINLINE_DEBUGGABLE AActor * AActor::GetOwner () const inherited
Get the owner of this Actor, used primarily for network replication.
Definition at line 4916 of file Actor.h.
References AActor(), and Owner.
GetOwner() [2/2]
template<class T> T * AActor::GetOwner () const inline inherited
Templated version of GetOwner(), will return nullptr if cast fails.
Definition at line 2983 of file Actor.h.
References GetOwner().
GetParentActor()
AActor * AActor::GetParentActor () const inherited
If this Actor was created by a Child Actor Component returns the Actor that owns that Child Actor Component.
References AActor(), and GetParentActor().
GetParentComponent()
UChildActorComponent * AActor::GetParentComponent () const inherited
If this Actor was created by a Child Actor Component returns that Child Actor Component.
References GetParentComponent().
GetPhysicsReplicationMode()
EPhysicsReplicationMode AActor::GetPhysicsReplicationMode () inherited
Get the physics replication mode of this body, via EPhysicsReplicationMode.
References GetPhysicsReplicationMode().
GetPhysicsVolume()
virtual APhysicsVolume * AActor::GetPhysicsVolume () const virtual inherited
Get the physics volume that is currently applied to this Actor (there can only ever be one)
Reimplemented in APawn.
References GetPhysicsVolume().
GetPivotOffset()
FVector AActor::GetPivotOffset () const inline inherited
Gets the local space offset added to the actor's pivot as used by the editor.
Definition at line 2513 of file Actor.h.
References PivotOffset.
GetPlacementExtent()
FVector AActor::GetPlacementExtent () const inherited
Get the extent used when placing this actor in the editor, used for 'pulling back' hit.
References GetPlacementExtent().
GetRayTracingGroupId()
int32 AActor::GetRayTracingGroupId () const inherited
Return the RayTracingGroupId for this actor.
References GetRayTracingGroupId().
GetReferencedContentObjects()
virtual bool AActor::GetReferencedContentObjects (TArray< UObject * > & Objects) const virtual inherited
Used by the "Sync to Content Browser" right-click menu option in the editor.
Parameters
Objects Array to add content object references to.
Returns
Whether the object references content (all overrides of this function should return true)
References GetReferencedContentObjects().
GetRemoteRole()
FORCEINLINE_DEBUGGABLE ENetRole AActor::GetRemoteRole () const inherited
Returns how much control the remote machine has over this actor.
Definition at line 4928 of file Actor.h.
GetReplayPriority()
virtual float AActor::GetReplayPriority (const FVector & ViewPos, const FVector & ViewDir, class AActor * Viewer, AActor * ViewTarget, UActorChannel *const InChannel, float Time) virtual inherited
Similar to GetNetPriority, but will only be used for prioritizing actors while recording a replay.
Parameters
ViewPos Position of the viewer
ViewDir Vector direction of viewer
Viewer "net object" owned by the client for whom net priority is being determined (typically player controller)
ViewTarget The actor that is currently being viewed/controlled by Viewer, usually a pawn
InChannel Channel on which this actor is being replicated.
Time Time since actor was last replicated
Returns
Priority of this actor for replays, higher is more important
References AActor().
GetReplicatedComponents()
const TArray< UActorComponent * > & AActor::GetReplicatedComponents () const inline inherited
Returns a constant reference to the replicated components set.
Definition at line 4097 of file Actor.h.
References ReplicatedComponents.
GetReplicatedCustomConditionState()
virtual void AActor::GetReplicatedCustomConditionState (FCustomPropertyConditionState & OutActiveState) const override virtual inherited
Called when this actor begins replicating to initialize the state of custom property conditions.
Reimplemented in ACharacter.
References Tick().
GetReplicatedMovement()
const FRepMovement & AActor::GetReplicatedMovement () const inline inherited
Gets the literal value of ReplicatedMovement.
This exists so subclasses don't need to have direct access to the Role property so it can be made private later.
Definition at line 4555 of file Actor.h.
GetReplicatedMovement_Mutable()
FRepMovement & AActor::GetReplicatedMovement_Mutable () inherited
Gets a reference to ReplicatedMovement with the expectation that it will be modified.
This exists so subclasses don't need to have direct access to the ReplicatedMovement property so it can be made private later.
GetReplicateMovementPropertyName()
const FName AActor::GetReplicateMovementPropertyName () inline static inherited
Gets the property name for bReplicateMovement.
This exists so subclasses don't need to have direct access to the bReplicateMovement property so it can be made private later.
Definition at line 4491 of file Actor.h.
References AActor().
GetRepresentedClass()
virtual UClass * ALightWeightInstanceManager::GetRepresentedClass (const int32 InstanceIndex) const inline override virtual
Definition at line 86 of file LightWeightInstanceManager.h.
References GetRepresentedClass(), and GetRepresentedClassInternal().
GetRepresentedClassInternal()
UClass * ALightWeightInstanceManager::GetRepresentedClassInternal () const protected
GetResimulationThreshold()
float AActor::GetResimulationThreshold () const inherited
Get the error threshold in centimeters before this object should enforce a resimulation to trigger.
References FActorLastRenderTime, and GetResimulationThreshold().
GetRolePropertyName()
const FName AActor::GetRolePropertyName () inline static inherited
Gets the property name for Role.
This exists so subclasses don't need to have direct access to the Role property so it can be made private later.
Definition at line 4539 of file Actor.h.
References AActor().
GetRootComponent()
USceneComponent * AActor::GetRootComponent () const inline inherited
Returns this actor's root component.
Definition at line 2461 of file Actor.h.
References RootComponent.
GetRootSelectionParent()
virtual AActor * AActor::GetRootSelectionParent () const virtual inherited
Returns top most selection parent.
References AActor(), and GetRootSelectionParent().
GetRotation()
FRotator ALightWeightInstanceManager::GetRotation (const FActorInstanceHandle & Handle) const
References FActorInstanceHandle, and GetRotation().
GetRuntimeGrid()
virtual FName AActor::GetRuntimeGrid () const inline virtual inherited
Returns this actor's current target runtime grid.
Definition at line 1125 of file Actor.h.
References RuntimeGrid.
GetRuntimeGridPropertyName()
const FName AActor::GetRuntimeGridPropertyName () inline static inherited
Gets the property name for RuntimeGrid.
Definition at line 1131 of file Actor.h.
References AActor(), and RuntimeGrid.
GetSceneOutlinerItemPackage()
virtual UPackage * AActor::GetSceneOutlinerItemPackage () const virtual inherited
Returns the actor item package that should be used in the scene outliner.
References GetSceneOutlinerItemPackage().
GetSceneOutlinerPackage()
virtual UPackage * AActor::GetSceneOutlinerPackage () const virtual inherited
Returns the actor package that should be used in the scene outliner.
References GetSceneOutlinerPackage().
GetSceneOutlinerParent()
virtual AActor * AActor::GetSceneOutlinerParent () const virtual inherited
Returns the actor attachement parent that should be used in the scene outliner.
References AActor().
GetSceneOutlinerTopParentPackage()
virtual UPackage * AActor::GetSceneOutlinerTopParentPackage () const virtual inherited
Returns the actor top parent package that should be used in the scene outliner.
References GetSceneOutlinerTopParentPackage().
GetSelectionParent()
virtual AActor * AActor::GetSelectionParent () const virtual inherited
Returns immediate selection parent.
References AActor(), and GetSelectionParent().
GetSimpleCollisionCylinder()
virtual void AActor::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const virtual inherited
Get axis-aligned cylinder around this actor, used for simple collision checks (ie Pawns reaching a destination).
If IsRootComponentCollisionRegistered() returns true, just returns its bounding cylinder, otherwise falls back to GetComponentsBoundingCylinder.
Reimplemented in ACharacter.
References GetSimpleCollisionCylinder(), GetSimpleCollisionCylinderExtent(), GetSimpleCollisionHalfHeight(), and GetSimpleCollisionRadius().
GetSimpleCollisionCylinderExtent()
FVector AActor::GetSimpleCollisionCylinderExtent () const inline inherited
Returns collision extents vector for this Actor, based on GetSimpleCollisionCylinder().
Definition at line 4899 of file Actor.h.
References GetSimpleCollisionCylinder().
GetSimpleCollisionHalfHeight()
float AActor::GetSimpleCollisionHalfHeight () const inline inherited
Returns the half height of the collision cylinder from GetSimpleCollisionCylinder().
Definition at line 4892 of file Actor.h.
References GetSimpleCollisionCylinder().
GetSimpleCollisionRadius()
float AActor::GetSimpleCollisionRadius () const inline inherited
Returns the radius of the collision cylinder from GetSimpleCollisionCylinder().
Definition at line 4885 of file Actor.h.
References GetSimpleCollisionCylinder().
GetSoftReferencedContentObjects()
virtual bool AActor::GetSoftReferencedContentObjects (TArray< FSoftObjectPath > & SoftObjects) const virtual inherited
Similar to GetReferencedContentObjects, but for soft referenced objects.
References GetSoftReferencedContentObjects().
GetSquaredDistanceTo()
float AActor::GetSquaredDistanceTo (const AActor * OtherActor) const inherited
Returns the squared distance from this Actor to OtherActor.
References AActor(), and GetSquaredDistanceTo().
GetSquaredHorizontalDistanceTo()
float AActor::GetSquaredHorizontalDistanceTo (const AActor * OtherActor) const inherited
Returns the squared distance from this Actor to OtherActor, ignoring Z.
References AActor(), and GetSquaredHorizontalDistanceTo().
GetStreamingBounds() [1/2]
FBox AActor::GetStreamingBounds () const inherited
References GetStreamingBounds().
GetStreamingBounds() [2/2]
virtual void AActor::GetStreamingBounds (FBox & OutRuntimeBounds, FBox & OutEditorBounds) const virtual inherited
Returns the bounding boxes of all components that make up this Actor for loading at runtime and editor.
This function differs from GetActorBounds because it will return a valid origin and an empty extent if this actor doesn't have primitive components.
See also
GetActorBounds()
GetSubobjectsWithStableNamesForNetworking()
virtual void AActor::GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > & ObjList) override virtual inherited
Returns a list of sub-objects that have stable names for networking.
GetTargetLocation()
virtual FVector AActor::GetTargetLocation (AActor * RequestedBy = nullptr) const virtual inherited
Returns the optimal location to fire weapons at this actor.
Parameters
RequestedBy - the Actor requesting the target location
References AActor(), and GetTargetLocation().
GetTearOff()
bool AActor::GetTearOff () const inline inherited
If true, this actor is no longer replicated to new clients, and is "torn off" (becomes a ROLE_Authority) on clients to which it was being replicated.
Definition at line 376 of file Actor.h.
GetTickableWhenPaused()
bool AActor::GetTickableWhenPaused () inherited
Gets whether this actor can tick when paused.
References GetTickableWhenPaused().
GetTransform() [1/2]
const FTransform & AActor::GetTransform () const inline inherited
Get the actor-to-world transform.
Returns
The transform that transforms from actor space to world space.
Definition at line 1545 of file Actor.h.
References ActorToWorld(), and GetTransform().
GetTransform() [2/2]
virtual FTransform ALightWeightInstanceManager::GetTransform (const FActorInstanceHandle & Handle) const virtual
References FActorInstanceHandle.
GetUpdateOverlapsMethodDuringLevelStreaming()
EActorUpdateOverlapsMethod AActor::GetUpdateOverlapsMethodDuringLevelStreaming () const inherited
Get the method used to UpdateOverlaps() when loaded via level streaming.
Resolves the 'UseConfigDefault' option to the class default specified in config.
References EActorUpdateOverlapsMethod, and GetUpdateOverlapsMethodDuringLevelStreaming().
GetVelocity()
virtual FVector AActor::GetVelocity () const virtual inherited
Returns velocity (in cm/s (Unreal Units/second) of the rootcomponent if it is either using physics or has an associated MovementComponent.
Reimplemented in APawn.
References GetVelocity().
GetVerticalDistanceTo()
float AActor::GetVerticalDistanceTo (const AActor * OtherActor) const inherited
Returns the distance from this Actor to OtherActor, ignoring XY.
References AActor(), and GetVerticalDistanceTo().
GetWorld()
virtual UWorld * AActor::GetWorld () const final override virtual inherited
Getter for the cached world pointer, will return null if the actor is not actually spawned in a level.
References GetWorld().
GetWorldSettings()
class AWorldSettings * AActor::GetWorldSettings () const inherited
Returns the WorldSettings for the World the actor is in If you'd like to know what UWorld this placed actor (not dynamic spawned actor) belong to, use GetTypedOuter<UWorld>()
References GetWorldSettings().
GetWorldTimerManager()
class FTimerManager & AActor::GetWorldTimerManager () const inherited
Get the timer instance from the actors world.
References GetWorldTimerManager().
GrowDataArrays()
virtual void ALightWeightInstanceManager::GrowDataArrays () protected virtual
References GrowDataArrays().
HandleRegisterComponentWithWorld()
void AActor::HandleRegisterComponentWithWorld (UActorComponent * Component) inherited
Finish initializing the component and register tick functions and beginplay if it's the proper time to do so.
HasActiveCameraComponent()
virtual bool AActor::HasActiveCameraComponent (bool bForceFindCamera = false) const virtual inherited
Returns true if the actor contains an active camera component.
References HasActiveCameraComponent().
HasActivePawnControlCameraComponent()
virtual bool AActor::HasActivePawnControlCameraComponent () const virtual inherited
Returns true if the actor contains an active locked to HMD camera component.
References HasActivePawnControlCameraComponent().
HasActorBegunPlay()
bool AActor::HasActorBegunPlay () const inline inherited
Returns whether an actor has had BeginPlay called on it (and not subsequently had EndPlay called)
Definition at line 2135 of file Actor.h.
HasActorRegisteredAllComponents()
bool AActor::HasActorRegisteredAllComponents () const inline inherited
Returns bHasRegisteredAllComponents which indicates whether this actor has registered all their components without unregisatering all of them them.
bHasRegisteredAllComponents is set true just before PostRegisterAllComponents() is called and false just before PostUnregisterAllComponents() is called.
Definition at line 2151 of file Actor.h.
HasAnyValidInstancesOrManagedActors()
bool ALightWeightInstanceManager::HasAnyValidInstancesOrManagedActors () const
References HasAnyValidInstancesOrManagedActors().
HasAuthority()
FORCEINLINE_DEBUGGABLE bool AActor::HasAuthority () const inherited
Returns whether this actor has network authority.
Definition at line 4911 of file Actor.h.
References GetLocalRole().
HasContentBundle()
bool AActor::HasContentBundle () const inherited
HasDataLayers()
bool AActor::HasDataLayers () const inherited
HasDeferredComponentRegistration()
bool AActor::HasDeferredComponentRegistration () const inline inherited
Returns true if Actor has deferred the RegisterAllComponents() call at spawn time (e.g.
pending Blueprint SCS execution to set up a scene root component).
Definition at line 3228 of file Actor.h.
References HasDeferredComponentRegistration().
HasEditableLevelLevelInstancePropertyOverrides()
bool AActor::HasEditableLevelLevelInstancePropertyOverrides () const inline inherited
If true, this actor or one of its components has property overrides applied from an editable level instance (level instance is in a non readonly level)
Definition at line 420 of file Actor.h.
HasExternalContent()
bool AActor::HasExternalContent () const inherited
HasHLODRelevantComponents()
virtual bool AActor::HasHLODRelevantComponents () const virtual inherited
Indicates whether this actor can provide HLOD relevant components.
HasLevelInstancePropertyOverrides()
bool AActor::HasLevelInstancePropertyOverrides () const inline inherited
If true, this actor or one of its components has property overrides applied.
Definition at line 414 of file Actor.h.
HasLocalNetOwner()
virtual bool AActor::HasLocalNetOwner () const virtual inherited
Does this actor have a locally controlled owner responsible for replication?
(APlayerController typically)
Returns
true if this actor can call RPCs or false if no such owner chain exists
References HasLocalNetOwner().
HasNetOwner()
virtual bool AActor::HasNetOwner () const virtual inherited
Does this actor have an owner responsible for replication?
(APlayerController typically)
Returns
true if this actor can call RPCs or false if no such owner chain exists
Reimplemented in APlayerController.
References HasNetOwner().
HasNonTrivialUserConstructionScript()
bool AActor::HasNonTrivialUserConstructionScript () const inherited
Returns true if the actor's class has a non trivial user construction script.
HasValidDataLayers()
bool AActor::HasValidDataLayers () const inline inherited
Definition at line 1499 of file Actor.h.
References HasDataLayers(), and HasValidDataLayers().
HasValidRootComponent()
bool AActor::HasValidRootComponent () const inherited
Returns true if Actor has a registered root component.
IncrementalRegisterComponents()
bool AActor::IncrementalRegisterComponents (int32 NumComponentsToRegister, FRegisterComponentContext * Context = nullptr) inherited
Incrementally registers components associated with this actor, used during level streaming.
Parameters
NumComponentsToRegister Number of components to register in this run, 0 for all
Returns
true when all components were registered for this actor
InitializeComponents()
void AActor::InitializeComponents () inherited
Iterate over components array and call InitializeComponent, which happens once per actor.
InternalTakePointDamage()
virtual float AActor::InternalTakePointDamage (float Damage, struct FPointDamageEvent const & PointDamageEvent, class AController * EventInstigator, AActor * DamageCauser) protected virtual inherited
References AActor(), and InternalTakePointDamage().
InternalTakeRadialDamage()
virtual float AActor::InternalTakeRadialDamage (float Damage, struct FRadialDamageEvent const & RadialDamageEvent, class AController * EventInstigator, AActor * DamageCauser) protected virtual inherited
References AActor(), and InternalTakeRadialDamage().
InvalidateLightingCache()
void AActor::InvalidateLightingCache () inline inherited
Invalidate lighting cache with default options.
Definition at line 3295 of file Actor.h.
References InvalidateLightingCacheDetailed().
InvalidateLightingCacheDetailed()
virtual void AActor::InvalidateLightingCacheDetailed (bool bTranslationOnly) virtual inherited
Invalidates anything produced by the last lighting build.
IsActorBeginningPlay()
bool AActor::IsActorBeginningPlay () const inline inherited
Returns whether an actor is in the process of beginning play.
Definition at line 2132 of file Actor.h.
IsActorBeginningPlayFromLevelStreaming()
bool AActor::IsActorBeginningPlayFromLevelStreaming () const inline inherited
Returns whether an actor is beginning play in DispatchBeginPlay() during level streaming (which includes initial level load).
Definition at line 2138 of file Actor.h.
IsActorBeingDestroyed()
bool AActor::IsActorBeingDestroyed () const inline inherited
Returns true if this actor is currently being destroyed, some gameplay events may be unsafe.
Definition at line 2142 of file Actor.h.
References IsActorBeingDestroyed().
IsActorComponentReplicatedSubObjectRegistered()
bool AActor::IsActorComponentReplicatedSubObjectRegistered (const UActorComponent * OwnerComponent, const UObject * SubObject) const inherited
Tells if an object owned by a component has been registered as a replicated subobject of the component.
IsActorInitialized()
bool AActor::IsActorInitialized () const inline inherited
Returns whether an actor has been initialized for gameplay.
Definition at line 2129 of file Actor.h.
References IsActorInitialized().
IsActorLabelEditable()
virtual bool AActor::IsActorLabelEditable () const virtual inherited
Returns if this actor's current label is editable.
Actor labels are only available in development builds.
Returns
The editable status of the actor's label
References IsActorLabelEditable().
IsActorOrSelectionParentSelected()
bool AActor::IsActorOrSelectionParentSelected () const inherited
Returns if actor or selection parent is selected.
References IsActorOrSelectionParentSelected().
IsActorTickEnabled()
bool AActor::IsActorTickEnabled () const inherited
Returns whether this actor has tick enabled or not.
References IsActorTickEnabled().
IsAsset()
virtual bool AActor::IsAsset () const override virtual inherited
IsAttachedTo()
virtual bool AActor::IsAttachedTo (const AActor * Other) const virtual inherited
Iterates up the attachment chain to see whether or not this Actor is attached to the given Actor.
Parameters
Other the Actor to test for
Returns
true if this Actor is attached on Other Actor
References AActor(), and IsAttachedTo().
IsBasedOnActor()
virtual bool AActor::IsBasedOnActor (const AActor * Other) const virtual inherited
Iterates up the movement base chain to see whether or not this Actor is based on the given Actor, defaults to checking attachment.
Parameters
Other the Actor to test for
Returns
true if this Actor is based on Other Actor
Reimplemented in APawn.
References AActor(), and IsBasedOnActor().
IsChildActor()
bool AActor::IsChildActor () const inherited
Returns whether this Actor was spawned by a child actor component.
References IsChildActor().
IsComponentRelevantForNavigation()
virtual bool AActor::IsComponentRelevantForNavigation (UActorComponent * Component) const inline virtual inherited
Check if owned component should be relevant for navigation Allows implementing master switch to disable e.g.
collision export in projectiles
Definition at line 4335 of file Actor.h.
References IsComponentRelevantForNavigation().
IsDataLayerTypeSupported()
virtual bool AActor::IsDataLayerTypeSupported (TSubclassOf< UDataLayerInstance > DataLayerType) const inline final protected virtual inherited
Definition at line 1437 of file Actor.h.
References IsDataLayerTypeSupported().
IsDataValid()
virtual EDataValidationResult AActor::IsDataValid (class FDataValidationContext & Context) const override virtual inherited
Returns Valid if this object has data validation rules set up for it and the data for this object is valid.
Returns Invalid if it does not pass the rules. Returns NotValidated if no rules are set for this object.
IsDefaultPreviewEnabled()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS bool AActor::IsDefaultPreviewEnabled () const inline virtual inherited
Defines if preview should be shown when you select an actor, but none of its children.
Definition at line 2398 of file Actor.h.
IsEditable()
bool AActor::IsEditable () const inherited
Returns true if this actor is allowed to be displayed, selected and manipulated by the editor.
References IsEditable().
IsEditorOnly()
virtual bool AActor::IsEditorOnly () const override virtual inherited
IsEditorOnlyLoadedInPIE()
virtual bool AActor::IsEditorOnlyLoadedInPIE () const inline virtual inherited
Definition at line 2353 of file Actor.h.
IsForceExternalActorLevelReferenceForPIE()
bool AActor::IsForceExternalActorLevelReferenceForPIE () const inherited
Returns if level should keep a reference to the external actor for PIE (used for always loaded actors).
References IsForceExternalActorLevelReferenceForPIE().
IsHidden()
bool AActor::IsHidden () const inline inherited
Gets the literal value of bHidden.
This exists so subclasses don't need to have direct access to the bHidden property so it can be made private later.
Definition at line 4474 of file Actor.h.
IsHiddenEd()
virtual bool AActor::IsHiddenEd () const virtual inherited
Returns true if this actor is hidden in the editor viewports, also checking temporary flags.
References IsHiddenEd().
IsHiddenEdAtStartup()
bool AActor::IsHiddenEdAtStartup () const inline inherited
Returns true if the actor is hidden upon editor startup/by default, false if it is not.
Definition at line 2593 of file Actor.h.
References bHiddenEd, and IsHiddenEdAtStartup().
IsHLODRelevant()
virtual bool AActor::IsHLODRelevant () const virtual inherited
Indicates whether this actor contributes to the HLOD generation.
IsInAnyEditLevelInstance()
bool AActor::IsInAnyEditLevelInstance () const inline inherited
If true, the actor belongs to a level instance which is currently in an edit mode: edit or property override edit.
Definition at line 390 of file Actor.h.
References IsInEditLevelInstance(), and IsInPropertyOverrideLevelInstance().
IsIndexValid()
bool ALightWeightInstanceManager::IsIndexValid (int32 Index) const protected
IsInEditingLevelInstance()
virtual bool AActor::IsInEditingLevelInstance () const inline virtual inherited
Deprecated for a non virtual version.
Definition at line 384 of file Actor.h.
References IsInEditingLevelInstance(), and IsInEditLevelInstance().
IsInEditLevelInstance()
bool AActor::IsInEditLevelInstance () const inline inherited
If true, the actor belongs to a level instance which is currently being edited.
Definition at line 396 of file Actor.h.
IsInEditLevelInstanceHierarchy()
bool AActor::IsInEditLevelInstanceHierarchy () const inline inherited
If true, the actor belongs to a level instance which is currently being edited or a parent level instance being edited.
Definition at line 408 of file Actor.h.
IsInLevel()
bool AActor::IsInLevel (const class ULevel * TestLevel) const inherited
Returns true if this actor is contained by TestLevel.
IsInLevelInstance()
bool AActor::IsInLevelInstance () const inline inherited
If true, the actor belongs to a level instance.
Definition at line 426 of file Actor.h.
IsInPersistentLevel()
bool AActor::IsInPersistentLevel (bool bIncludeLevelStreamingPersistent = false) const inherited
Returns whether this Actor is in the persistent level, i.e.
not a sublevel
References IsInPersistentLevel().
IsInPropertyOverrideLevelInstance()
bool AActor::IsInPropertyOverrideLevelInstance () const inline inherited
If true, the actor belongs to a level instance which is currently in property override edit.
Definition at line 402 of file Actor.h.
IsLevelBoundsRelevant()
virtual bool AActor::IsLevelBoundsRelevant () const inline virtual inherited
Indicates whether this actor should participate in level bounds calculations.
Reimplemented in AInfo.
Definition at line 2545 of file Actor.h.
References bRelevantForLevelBounds.
IsListedInSceneOutliner()
virtual bool AActor::IsListedInSceneOutliner () const virtual inherited
Returns true if this actor should be shown in the scene outliner.
References IsListedInSceneOutliner().
IsLockLocation()
virtual bool AActor::IsLockLocation () const virtual inherited
Returns true if actor location should be locked.
IsMainPackageActor()
bool AActor::IsMainPackageActor () const inherited
Used to check if Actor is the main actor of a package (currently Child Actors are not)
IsMainWorldOnly()
bool AActor::IsMainWorldOnly () const inherited
Whether this actor should be ignored when it is not loaded as part of the Main World (Persistent Level).
eg. Will not be loaded through Level Instances.
IsNameStableForNetworking()
virtual bool AActor::IsNameStableForNetworking () const override virtual inherited
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
IsNetMode()
FORCEINLINE_DEBUGGABLE bool AActor::IsNetMode (ENetMode Mode) const inherited
Test whether net mode is the given mode.
In optimized non-editor builds this can be more efficient than GetNetMode() because it can check the static build flags without considering PIE.
Definition at line 4945 of file Actor.h.
References GetNetMode(), and NetDriverName.
IsNetRelevantFor()
virtual bool AActor::IsNetRelevantFor (const AActor * RealViewer, const AActor * ViewTarget, const FVector & SrcLocation) const virtual inherited
Checks to see if this actor is relevant for a specific network connection.
Parameters
RealViewer - is the "controlling net object" associated with the client for which network relevancy is being checked (typically player controller)
ViewTarget - is the Actor being used as the point of view for the RealViewer
SrcLocation - is the viewing location
Returns
bool - true if this actor is network relevant to the client associated with RealViewer
Reimplemented in APawn, and APlayerController.
References AActor().
IsNetStartupActor()
bool AActor::IsNetStartupActor () const inherited
Returns true if this is a replicated actor that was placed in the map.
IsOverlappingActor()
bool AActor::IsOverlappingActor (const AActor * Other) const inherited
Check whether any component of this Actor is overlapping any component of another Actor.
Parameters
Other The other Actor to test against
Returns
Whether any component of this Actor is overlapping any component of another Actor.
References AActor(), and IsOverlappingActor().
IsOwnedBy()
bool AActor::IsOwnedBy (const AActor * TestOwner) const inline inherited
See if this actor is owned by TestOwner.
Definition at line 2450 of file Actor.h.
References AActor().
IsPendingKillPending()
bool AActor::IsPendingKillPending () const inline inherited
Returns true if this actor has begun the destruction process.
This is set to true in UWorld::DestroyActor, after the network connection has been closed but before any other shutdown has been performed.
Returns
true if this actor has begun destruction, or if this actor has been destroyed already.
Definition at line 3289 of file Actor.h.
IsPropertyChangedAffectingDataLayers()
bool AActor::IsPropertyChangedAffectingDataLayers (FPropertyChangedEvent & PropertyChangedEvent) const inherited
IsReadyForFinishDestroy()
virtual bool AActor::IsReadyForFinishDestroy () override virtual inherited
IsRelevancyOwnerFor()
virtual bool AActor::IsRelevancyOwnerFor (const AActor * ReplicatedActor, const AActor * ActorOwner, const AActor * ConnectionActor) const virtual inherited
Check if this actor is the owner when doing relevancy checks for actors marked bOnlyRelevantToOwner.
Parameters
ReplicatedActor - the actor we're doing a relevancy test on
ActorOwner - the owner of ReplicatedActor
ConnectionActor - the controller of the connection that we're doing relevancy checks for
Returns
bool - true if this actor should be considered the owner
References AActor().
IsReplayRelevantFor()
virtual bool AActor::IsReplayRelevantFor (const AActor * RealViewer, const AActor * ViewTarget, const FVector & SrcLocation, const float CullDistanceSquared) const virtual inherited
Checks to see if this actor is relevant for a recorded replay.
Parameters
RealViewer - is the "controlling net object" associated with the client for which network relevancy is being checked (typically player controller)
ViewTarget - is the Actor being used as the point of view for the RealViewer
SrcLocation - is the viewing location
Returns
bool - true if this actor is replay relevant to the client associated with RealViewer
References AActor().
IsReplicatedActorComponentRegistered()
bool AActor::IsReplicatedActorComponentRegistered (const UActorComponent * ReplicatedComponent) const inherited
Tells if the component has been registered as a replicated component.
IsReplicatedSubObjectRegistered()
bool AActor::IsReplicatedSubObjectRegistered (const UObject * SubObject) const inherited
Tells if the object has been registered as a replicated subobject of this actor.
IsReplicatingMovement()
bool AActor::IsReplicatingMovement () const inline inherited
Gets the literal value of bReplicateMovement.
This exists so subclasses don't need to have direct access to the bReplicateMovement property so it can be made private later.
Definition at line 4502 of file Actor.h.
IsReplicationPausedForConnection()
virtual bool AActor::IsReplicationPausedForConnection (const FNetViewer & ConnectionOwnerNetViewer) virtual inherited
Gives the actor a chance to pause replication to a player represented by the passed in actor - only called on server.
References IsReplicationPausedForConnection().
IsRootComponentCollisionRegistered()
virtual bool AActor::IsRootComponentCollisionRegistered () const virtual inherited
Returns true if the root component is registered and has collision enabled.
References IsRootComponentCollisionRegistered().
IsRootComponentMovable()
bool AActor::IsRootComponentMovable () const inherited
See if the root component has Mobility of EComponentMobility::Movable.
References IsRootComponentMovable().
IsRootComponentStatic()
bool AActor::IsRootComponentStatic () const inherited
See if the root component has ModifyFrequency of MF_Static.
References IsRootComponentStatic().
IsRootComponentStationary()
bool AActor::IsRootComponentStationary () const inherited
See if the root component has Mobility of EComponentMobility::Stationary.
References IsRootComponentStationary().
IsRunningUserConstructionScript()
bool AActor::IsRunningUserConstructionScript () const inline inherited
Returns if this actor is currently running the User Construction Script.
Definition at line 1029 of file Actor.h.
IsRuntimeOnly()
virtual bool AActor::IsRuntimeOnly () const inline virtual inherited
Definition at line 2354 of file Actor.h.
IsSelectable()
virtual bool AActor::IsSelectable () const virtual inherited
Returns true if this actor can EVER be selected in a level in the editor.
Can be overridden by specific actors to make them unselectable.
Reimplemented in AWorldSettings.
References IsSelectable().
IsSelectedInEditor()
virtual bool AActor::IsSelectedInEditor () const override virtual inherited
References IsSelectedInEditor().
IsSelectionChild()
virtual bool AActor::IsSelectionChild () const virtual inherited
Returns whether this Actor is part of another's actor selection.
References IsSelectionChild().
IsSelectionParentOfAttachedActors()
virtual bool AActor::IsSelectionParentOfAttachedActors () const virtual inherited
Returns whether this actor can select its attached actors.
References IsSelectionParentOfAttachedActors().
IsSupportedForNetworking()
virtual bool AActor::IsSupportedForNetworking () const override virtual inherited
IsSupportedForNetworking means an object can be referenced over the network.
IsTemporarilyHiddenInEditor()
bool AActor::IsTemporarilyHiddenInEditor (bool bIncludeParent = false) const inherited
Returns whether or not this actor was explicitly hidden in the editor for the duration of the current editor session.
Parameters
bIncludeParent - Whether to recurse up child actor hierarchy or not
References IsTemporarilyHiddenInEditor().
IsUserManaged()
virtual bool AActor::IsUserManaged () const inline virtual inherited
Used to know if actor supports some editor operations.
(Delete, Replace)
Definition at line 2404 of file Actor.h.
IsUsingRegisteredSubObjectList()
bool AActor::IsUsingRegisteredSubObjectList () const inline inherited
Returns true if this actor is replicating SubObjects & ActorComponents via the registration list.
Returns false when it replicates them via the virtual ReplicateSubobjects method.
Definition at line 928 of file Actor.h.
References bReplicateUsingRegisteredSubObjectList.
IsWithinNetRelevancyDistance()
bool AActor::IsWithinNetRelevancyDistance (const FVector & SrcLocation) const protected inherited
Determines whether or not the distance between the given SrcLocation and the Actor's location is within the net relevancy distance.
Actors outside relevancy distance may not be replicated.
Parameters
SrcLocation Location to test against.
Returns
True if the actor is within net relevancy distance, false otherwise.
K2_AddActorLocalOffset()
void AActor::K2_AddActorLocalOffset (FVector DeltaLocation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the location of this component in its local reference frame.
Parameters
DelatLocation The change in location in local space.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
References K2_AddActorLocalOffset().
K2_AddActorLocalRotation()
void AActor::K2_AddActorLocalRotation (FRotator DeltaRotation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the rotation of this component in its local reference frame.
Parameters
DeltaRotation The change in rotation in local space.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the rotation without teleporting will not update the rotation of simulated child/attached components.
References K2_AddActorLocalRotation().
K2_AddActorLocalTransform()
void AActor::K2_AddActorLocalTransform (const FTransform & NewTransform, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the transform of this component in its local reference frame.
Parameters
NewTransform The change in transform in local space.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the transform without teleporting will not update the transform of simulated child/attached components.
References K2_AddActorLocalTransform().
K2_AddActorWorldOffset()
void AActor::K2_AddActorWorldOffset (FVector DeltaLocation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the location of this actor in world space.
Parameters
DeltaLocation The change in location.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
SweepHitResult The hit result from the move if swept.
References K2_AddActorWorldOffset().
K2_AddActorWorldRotation()
void AActor::K2_AddActorWorldRotation (FRotator DeltaRotation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the rotation of this actor in world space.
Parameters
DeltaRotation The change in rotation.
bSweep Whether to sweep to the target rotation (not currently supported for rotation).
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the rotation without teleporting will not update the rotation of simulated child/attached components.
SweepHitResult The hit result from the move if swept.
References K2_AddActorWorldRotation().
K2_AddActorWorldTransform()
void AActor::K2_AddActorWorldTransform (const FTransform & DeltaTransform, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the transform of this actor in world space.
Ignores scale and sets it to (1,1,1).
References K2_AddActorWorldTransform().
K2_AddActorWorldTransformKeepScale()
void AActor::K2_AddActorWorldTransformKeepScale (const FTransform & DeltaTransform, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Adds a delta to the transform of this actor in world space.
Scale is unchanged.
References K2_AddActorWorldTransformKeepScale().
K2_AttachRootComponentTo()
void AActor::K2_AttachRootComponentTo (USceneComponent * InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachLocationType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = true) inherited
DEPRECATED - Use AttachToComponent() instead.
References K2_AttachRootComponentTo().
K2_AttachRootComponentToActor()
void AActor::K2_AttachRootComponentToActor (AActor * InParentActor, FName InSocketName = NAME_None, EAttachLocation::Type AttachLocationType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = true) inherited
DEPRECATED - Use AttachToActor() instead.
References AActor(), and K2_AttachRootComponentToActor().
K2_AttachToActor()
bool AActor::K2_AttachToActor (AActor * ParentActor, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule, bool bWeldSimulatedBodies) inherited
Attaches the RootComponent of this Actor to the supplied actor, optionally at a named socket.
Parameters
ParentActor Actor to attach this actor's RootComponent to
SocketName Socket name to attach to, if any
LocationRule How to handle translation when attaching.
RotationRule How to handle rotation when attaching.
ScaleRule How to handle scale when attaching.
bWeldSimulatedBodies Whether to weld together simulated physics bodies.This transfers the shapes in the welded object into the parent (if simulated), which can result in permanent changes that persist even after subsequently detaching.
Returns
Whether the attachment was successful or not
References AActor(), and K2_AttachToActor().
K2_AttachToComponent()
bool AActor::K2_AttachToComponent (USceneComponent * Parent, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule, bool bWeldSimulatedBodies) inherited
Attaches the RootComponent of this Actor to the supplied component, optionally at a named socket.
It is not valid to call this on components that are not Registered.
Parameters
Parent Parent to attach to.
SocketName Optional socket to attach to on the parent.
LocationRule How to handle translation when attaching.
RotationRule How to handle rotation when attaching.
ScaleRule How to handle scale when attaching.
bWeldSimulatedBodies Whether to weld together simulated physics bodies. This transfers the shapes in the welded object into the parent (if simulated), which can result in permanent changes that persist even after subsequently detaching.
Returns
Whether the attachment was successful or not
References K2_AttachToComponent().
K2_DestroyActor()
virtual void AActor::K2_DestroyActor () virtual inherited
Destroy the actor.
Reimplemented in AController.
References HasAuthority(), and K2_DestroyActor().
K2_DetachFromActor()
void AActor::K2_DetachFromActor (EDetachmentRule LocationRule = EDetachmentRule::KeepRelative, EDetachmentRule RotationRule = EDetachmentRule::KeepRelative, EDetachmentRule ScaleRule = EDetachmentRule::KeepRelative) inherited
Detaches the RootComponent of this Actor from any SceneComponent it is currently attached to.
Parameters
LocationRule How to handle translation when detaching.
RotationRule How to handle rotation when detaching.
ScaleRule How to handle scale when detaching.
References K2_DetachFromActor().
K2_GetActorLocation()
FORCEINLINE_DEBUGGABLE FVector AActor::K2_GetActorLocation () const inherited
Returns the location of the RootComponent of this Actor.
Definition at line 4854 of file Actor.h.
References GetActorLocation().
K2_GetActorRotation()
FORCEINLINE_DEBUGGABLE FRotator AActor::K2_GetActorRotation () const inherited
Returns rotation of the RootComponent of this Actor.
Definition at line 4859 of file Actor.h.
References GetActorRotation().
K2_GetComponentsByClass()
TArray< UActorComponent * > AActor::K2_GetComponentsByClass (TSubclassOf< UActorComponent > ComponentClass) const inherited
Gets all the components that inherit from the given class.
Currently returns an array of UActorComponent which must be cast to the correct type. This intended to only be used by blueprints. Use GetComponents() in C++.
References K2_GetComponentsByClass().
K2_GetRootComponent()
FORCEINLINE_DEBUGGABLE USceneComponent * AActor::K2_GetRootComponent () const inherited
Returns the RootComponent of this Actor.
Definition at line 4864 of file Actor.h.
References GetRootComponent().
K2_OnBecomeViewTarget()
void AActor::K2_OnBecomeViewTarget (class APlayerController * PC) inherited
Event called when this Actor becomes the view target for the given PlayerController.
References K2_OnBecomeViewTarget().
K2_OnEndViewTarget()
void AActor::K2_OnEndViewTarget (class APlayerController * PC) inherited
Event called when this Actor is no longer the view target for the given PlayerController.
References K2_OnEndViewTarget().
K2_OnReset()
void AActor::K2_OnReset () inherited
Event called when this Actor is reset to its initial state - used when restarting level without reloading.
References K2_OnReset().
K2_SetActorLocation()
bool AActor::K2_SetActorLocation (FVector NewLocation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Move the Actor to the specified location.
Parameters
NewLocation The new location to move the Actor to.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
SweepHitResult The hit result from the move if swept.
Returns
Whether the location was successfully set (if not swept), or whether movement occurred at all (if swept).
References GetActorForwardVector(), GetActorRightVector(), GetActorUpVector(), K2_GetActorRotation(), and K2_SetActorLocation().
K2_SetActorLocationAndRotation()
bool AActor::K2_SetActorLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Move the actor instantly to the specified location and rotation.
Parameters
NewLocation The new location to teleport the Actor to.
NewRotation The new rotation for the Actor.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
SweepHitResult The hit result from the move if swept.
Returns
Whether the rotation was successfully set.
References K2_SetActorLocationAndRotation().
K2_SetActorRelativeLocation()
void AActor::K2_SetActorRelativeLocation (FVector NewRelativeLocation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Set the actor's RootComponent to the specified relative location.
Parameters
NewRelativeLocation New relative location of the actor's root component
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
References K2_SetActorRelativeLocation().
K2_SetActorRelativeRotation()
void AActor::K2_SetActorRelativeRotation (FRotator NewRelativeRotation, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Set the actor's RootComponent to the specified relative rotation.
Parameters
NewRelativeRotation New relative rotation of the actor's root component
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the rotation without teleporting will not update the rotation of simulated child/attached components.
References K2_SetActorRelativeRotation().
K2_SetActorRelativeTransform()
void AActor::K2_SetActorRelativeTransform (const FTransform & NewRelativeTransform, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Set the actor's RootComponent to the specified relative transform.
Parameters
NewRelativeTransform New relative transform of the actor's root component
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the transform without teleporting will not update the transform of simulated child/attached components.
References K2_SetActorRelativeTransform().
K2_SetActorRotation()
bool AActor::K2_SetActorRotation (FRotator NewRotation, bool bTeleportPhysics) inherited
Set the Actor's rotation instantly to the specified rotation.
Parameters
NewRotation The new rotation for the Actor.
bTeleportPhysics Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the rotation without teleporting will not update the rotation of simulated child/attached components.
Returns
Whether the rotation was successfully set.
References K2_SetActorRotation().
K2_SetActorTransform()
bool AActor::K2_SetActorTransform (const FTransform & NewTransform, bool bSweep, FHitResult & SweepHitResult, bool bTeleport) inherited
Set the Actors transform to the specified one.
Parameters
NewTransform The new transform.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
bTeleport Whether we teleport the physics state (if physics collision is enabled for this object). If true, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If false, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the transform without teleporting will not update the transform of simulated child/attached components.
References K2_SetActorTransform().
K2_TeleportTo()
bool AActor::K2_TeleportTo (FVector DestLocation, FRotator DestRotation) inherited
Teleport this actor to a new location.
If the actor doesn't fit exactly at the location specified, tries to slightly move it out of walls and such.
Parameters
DestLocation The target destination point
DestRotation The target rotation at the destination
Returns
true if the actor has been successfully moved, or false if it couldn't fit.
References K2_TeleportTo().
LifeSpanExpired()
virtual void AActor::LifeSpanExpired () virtual inherited
Called when the lifespan of an actor expires (if it has one).
MakeNoise()
void AActor::MakeNoise (float Loudness = 1.f, APawn * NoiseInstigator = nullptr, FVector NoiseLocation = FVector::ZeroVector, float MaxRange = 0.f, FName Tag = NAME_None) inherited
Trigger a noise caused by a given Pawn, at a given location.
Note that the NoiseInstigator Pawn MUST have a PawnNoiseEmitterComponent for the noise to be detected by a PawnSensingComponent. Senders of MakeNoise should have an Instigator if they are not pawns, or pass a NoiseInstigator.
Parameters
Loudness The relative loudness of this noise. Usual range is 0 (no noise) to 1 (full volume). If MaxRange is used, this scales the max range, otherwise it affects the hearing range specified by the sensor.
NoiseInstigator Pawn responsible for this noise. Uses the actor's Instigator if NoiseInstigator is null
NoiseLocation Position of noise source. If zero vector, use the actor's location.
MaxRange Max range at which the sound may be heard. A value of 0 indicates no max range (though perception may have its own range). Loudness scales the range. (Note: not supported for legacy PawnSensingComponent, only for AIPerception)
Tag Identifier for the noise.
References MakeNoise().
MakeNoiseImpl()
void AActor::MakeNoiseImpl (AActor * NoiseMaker, float Loudness, APawn * NoiseInstigator, const FVector & NoiseLocation, float MaxRange, FName Tag) static inherited
Default Implementation of MakeNoise.
References AActor(), and MakeNoiseImpl().
MarkComponentsAsGarbage()
virtual void AActor::MarkComponentsAsGarbage (bool bModify = true) virtual inherited
Called to mark all components as garbage when the actor is being destroyed.
Parameters
bModify if True, Modify will be called on actor before marking components
MarkComponentsAsPendingKill()
virtual void AActor::MarkComponentsAsPendingKill () inline virtual inherited
Definition at line 3276 of file Actor.h.
References MarkComponentsAsGarbage(), and MarkComponentsAsPendingKill().
MarkComponentsRenderStateDirty()
void AActor::MarkComponentsRenderStateDirty () inherited
Flags all component's render state as dirty.
MarkNeedsRecomputeBoundsOnceForGame()
void AActor::MarkNeedsRecomputeBoundsOnceForGame () inherited
Marks the bounds of all SceneComponents attached to this actor which have bComputeBoundsOnceForGame as needing to be recomputed the next time UpdateBounds is called.
This might be necessary if the bounds that were cached on cook no longer reflect the actor's transform (ex. if level transform is applied).
References MarkNeedsRecomputeBoundsOnceForGame().
Modify()
virtual bool AActor::Modify (bool bAlwaysMarkDirty = true) override virtual inherited
NeedsLoadForTargetPlatform()
virtual bool AActor::NeedsLoadForTargetPlatform (const ITargetPlatform * TargetPlatform) const virtual inherited
References NeedsLoadForTargetPlatform().
NotifyActorBeginCursorOver()
virtual void AActor::NotifyActorBeginCursorOver () virtual inherited
Event when this actor has the mouse moved over it with the clickable interface.
References NotifyActorBeginCursorOver().
NotifyActorBeginOverlap()
virtual void AActor::NotifyActorBeginOverlap (AActor * OtherActor) virtual inherited
Event when this actor overlaps another actor, for example a player walking into a trigger.
For events when objects have a blocking collision, for example a player hitting a wall, see 'Hit' events. \note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
Reimplemented in ACharacter.
References AActor(), and NotifyActorBeginOverlap().
NotifyActorEndCursorOver()
virtual void AActor::NotifyActorEndCursorOver () virtual inherited
Event when this actor has the mouse moved off of it with the clickable interface.
References NotifyActorEndCursorOver().
NotifyActorEndOverlap()
virtual void AActor::NotifyActorEndOverlap (AActor * OtherActor) virtual inherited
Event when an actor no longer overlaps another actor, and they have separated.
\note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
Reimplemented in ACharacter.
References AActor(), and NotifyActorEndOverlap().
NotifyActorOnClicked()
virtual void AActor::NotifyActorOnClicked (FKey ButtonPressed = EKeys::LeftMouseButton) virtual inherited
Event when this actor is clicked by the mouse when using the clickable interface.
References NotifyActorOnClicked().
NotifyActorOnInputTouchBegin()
virtual void AActor::NotifyActorOnInputTouchBegin (const ETouchIndex::Type FingerIndex) virtual inherited
Event when this actor is touched when click events are enabled.
References NotifyActorOnInputTouchBegin().
NotifyActorOnInputTouchEnd()
virtual void AActor::NotifyActorOnInputTouchEnd (const ETouchIndex::Type FingerIndex) virtual inherited
Event when this actor is under the finger when untouched when click events are enabled.
References NotifyActorOnInputTouchEnd().
NotifyActorOnInputTouchEnter()
virtual void AActor::NotifyActorOnInputTouchEnter (const ETouchIndex::Type FingerIndex) virtual inherited
Event when this actor has a finger moved over it with the clickable interface.
References NotifyActorOnInputTouchEnter().
NotifyActorOnInputTouchLeave()
virtual void AActor::NotifyActorOnInputTouchLeave (const ETouchIndex::Type FingerIndex) virtual inherited
Event when this actor has a finger moved off of it with the clickable interface.
References NotifyActorOnInputTouchLeave().
NotifyActorOnReleased()
virtual void AActor::NotifyActorOnReleased (FKey ButtonReleased = EKeys::LeftMouseButton) virtual inherited
Event when this actor is under the mouse when left mouse button is released while using the clickable interface.
References NotifyActorOnReleased().
NotifyHit()
virtual void AActor::NotifyHit (class UPrimitiveComponent * MyComp, AActor * Other, class UPrimitiveComponent * OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult & Hit) virtual inherited
Event when this actor bumps into a blocking object, or blocks another actor that bumps into it.
This could happen due to things like Character movement, using Set Location with 'sweep' enabled, or physics simulation. For events when objects overlap (e.g. walking into a trigger) see the 'Overlap' event.
\note For collisions during physics simulation to generate hit events, 'Simulation Generates Hit Events' must be enabled. \note When receiving a hit from another object's movement (bSelfMoved is false), the directions of 'Hit.Normal' and 'Hit.ImpactNormal' will be adjusted to indicate force from the other object against this object.
References AActor(), and NotifyHit().
OnActorChannelOpen()
virtual void AActor::OnActorChannelOpen (class FInBunch & InBunch, class UNetConnection * Connection) inline virtual inherited
Allows for a specific response from the actor when the actor channel is opened (client side)
Parameters
InBunch Bunch received at time of open
Connection the connection associated with this actor
Reimplemented in APlayerController.
Definition at line 2841 of file Actor.h.
OnConstruction()
virtual void AActor::OnConstruction (const FTransform & Transform) inline virtual inherited
Called when an instance of this class is placed (in editor) or spawned.
Parameters
Transform The transform the actor was constructed at.
Definition at line 3436 of file Actor.h.
OnLoadedActorAddedToLevel()
virtual void AActor::OnLoadedActorAddedToLevel () inline virtual inherited
Called when this actor gets added to the level in the editor by world partition loading.
Definition at line 1175 of file Actor.h.
OnLoadedActorRemovedFromLevel()
virtual void AActor::OnLoadedActorRemovedFromLevel () inline virtual inherited
Called when this actor gets removed from the level in the editor by world partition unloading.
Definition at line 1178 of file Actor.h.
OnNetCleanup()
virtual void AActor::OnNetCleanup (class UNetConnection * Connection) inline virtual inherited
Handles cleaning up the associated Actor when killing the connection.
Parameters
Connection the connection associated with this actor
Reimplemented in APlayerController.
Definition at line 2860 of file Actor.h.
OnPlayFromHere()
virtual void AActor::OnPlayFromHere () virtual inherited
Called on actor which initiated the PIE session.
OnRep_AttachmentReplication()
virtual void AActor::OnRep_AttachmentReplication () virtual inherited
Called on client when updated AttachmentReplication value is received for this actor.
References OnRep_AttachmentReplication().
OnRep_Instigator()
virtual void AActor::OnRep_Instigator () virtual inherited
Called on clients when Instigator is replicated.
References OnRep_Instigator().
OnRep_Owner()
virtual void AActor::OnRep_Owner () protected virtual inherited
Called when owner changes, does nothing by default but can be overridden.
References OnRep_Owner().
OnRep_ReplicatedMovement()
virtual void AActor::OnRep_ReplicatedMovement () virtual inherited
ReplicatedMovement struct replication event.
Reimplemented in ACharacter.
References OnRep_ReplicatedMovement().
OnRep_ReplicateMovement()
virtual void AActor::OnRep_ReplicateMovement () virtual inherited
Called on client when updated bReplicateMovement value is received for this actor.
References OnRep_ReplicateMovement().
OnRep_Transforms()
virtual void ALightWeightInstanceManager::OnRep_Transforms () protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
References OnRep_Transforms().
OnReplicationPausedChanged()
virtual void AActor::OnReplicationPausedChanged (bool bIsReplicationPaused) virtual inherited
Called on the client when the replication paused value is changed.
References OnReplicationPausedChanged().
OnSerializeNewActor()
virtual void AActor::OnSerializeNewActor (class FOutBunch & OutBunch) inline virtual inherited
SerializeNewActor has just been called on the actor before network replication (server side)
Parameters
OutBunch Bunch containing serialized contents of actor prior to replication
Reimplemented in APlayerController.
Definition at line 2854 of file Actor.h.
OnSpawnedActorDestroyed()
virtual void ALightWeightInstanceManager::OnSpawnedActorDestroyed (AActor * DestroyedActor, const int32 DestroyedActorInstanceIndex) protected virtual
References AActor::AActor().
OnSubobjectCreatedFromReplication()
virtual void AActor::OnSubobjectCreatedFromReplication (UObject * NewSubobject) virtual inherited
Called on the actor when a new subobject is dynamically created via replication.
OnSubobjectDestroyFromReplication()
virtual void AActor::OnSubobjectDestroyFromReplication (UObject * Subobject) virtual inherited
Called on the actor when a subobject is dynamically destroyed via replication.
OpenAssetEditor()
virtual bool AActor::OpenAssetEditor () inline virtual inherited
Used to allow actor classes to open an actor specific editor.
Definition at line 2788 of file Actor.h.
References OpenAssetEditor().
OutsideWorldBounds()
virtual void AActor::OutsideWorldBounds () virtual inherited
Called when the Actor is outside the hard limit on world bounds.
Reimplemented in APawn.
References OutsideWorldBounds().
PopulatePIEDuplicationSeed()
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS void AActor::PopulatePIEDuplicationSeed (FDuplicationSeedInterface & DupSeed) inline virtual inherited
Populate the duplication seed when duplicating the actor for PIE.
This allows objects to be remapped to existing objects rather than duplicating.
Definition at line 2394 of file Actor.h.
References PopulatePIEDuplicationSeed().
PostActorConstruction()
void AActor::PostActorConstruction () inherited
Called after the actor has run its construction.
Responsible for finishing the actor spawn process.
PostActorCreated()
virtual void AActor::PostActorCreated () virtual inherited
Called when an actor is done spawning into the world (from UWorld::SpawnActor), both in the editor and during gameplay For actors with a root component, the location and rotation will have already been set.
This is called before calling construction scripts, but after native components have been created
PostActorSpawn()
virtual void ALightWeightInstanceManager::PostActorSpawn (const FActorInstanceHandle & Handle) protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
References FActorInstanceHandle.
PostCreateBlueprintComponent()
void AActor::PostCreateBlueprintComponent (UActorComponent * NewActorComp) protected inherited
Called after instancing a new Blueprint Component from either a template or cooked data.
PostEditChangeProperty()
virtual void ALightWeightInstanceManager::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
Reimplemented from AActor.
PostEditImport()
virtual void AActor::PostEditImport () override virtual inherited
References PostEditImport().
PostEditMove()
virtual void AActor::PostEditMove (bool bFinished) virtual inherited
Called after an actor has been moved in the editor.
PostEditUndo() [1/2]
virtual void AActor::PostEditUndo () override virtual inherited
References PostEditUndo().
PostEditUndo() [2/2]
virtual void AActor::PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation) override virtual inherited
PostInitializeComponents()
virtual void AActor::PostInitializeComponents () virtual inherited
Allow actors to initialize themselves on the C++ side after all of their components have been initialized, only called during gameplay.
Reimplemented in ACharacter, AController, AGameState, AGameStateBase, AHUD, APawn, APlayerController, and APlayerState.
PostInitProperties()
virtual void AActor::PostInitProperties () override virtual inherited
Reimplemented in AWorldSettings.
References PostInitProperties().
PostLoad()
virtual void AActor::PostLoad () override virtual inherited
Reimplemented in ACharacter, AInfo, ALightWeightInstanceStaticMeshManager, APawn, APlayerController, and AWorldSettings.
References PostLoad().
PostLoadSubobjects()
virtual void AActor::PostLoadSubobjects (FObjectInstancingGraph * OuterInstanceGraph) override virtual inherited
References PostLoadSubobjects().
PostNetInit()
virtual void AActor::PostNetInit () virtual inherited
Always called immediately after spawning and reading in replicated properties.
PostNetReceive()
virtual void AActor::PostNetReceive () override virtual inherited
Always called immediately after properties are received from the remote.
Reimplemented in ACharacter.
PostNetReceiveLocationAndRotation()
virtual void AActor::PostNetReceiveLocationAndRotation () virtual inherited
Update location and rotation from ReplicatedMovement.
Not called for simulated physics!
Reimplemented in ACharacter, and APawn.
References PostNetReceiveLocationAndRotation().
PostNetReceivePhysicState()
virtual void AActor::PostNetReceivePhysicState () virtual inherited
Update and smooth simulated physic state, replaces PostNetReceiveLocation() and PostNetReceiveVelocity()
References PostNetReceivePhysicState().
PostNetReceiveRole()
virtual void AActor::PostNetReceiveRole () virtual inherited
Always called immediately after a new Role is received from the remote.
PostNetReceiveVelocity()
virtual void AActor::PostNetReceiveVelocity (const FVector & NewVelocity) virtual inherited
Update velocity - typically from ReplicatedMovement, not called for simulated physics!
Reimplemented in APawn.
References PostNetReceiveVelocity().
PostRegisterAllComponents()
virtual void AActor::PostRegisterAllComponents () virtual inherited
Called after all the components in the Components array are registered, called both in editor and during gameplay.
bHasRegisteredAllComponents must be set true prior to calling this function.
Reimplemented in APawn, and AWorldSettings.
References PostRegisterAllComponents().
PostRename()
virtual void AActor::PostRename (UObject * OldOuter, const FName OldName) override virtual inherited
PostRenameFromRoot()
virtual void AActor::PostRenameFromRoot (const FWorldRenameFromRootContext & RenameContext) inline virtual inherited
Definition at line 2433 of file Actor.h.
PostRenderFor()
virtual void AActor::PostRenderFor (class APlayerController * PC, class UCanvas * Canvas, FVector CameraPosition, FVector CameraDir) virtual inherited
Hook to allow actors to render HUD overlays for themselves.
Called from AHUD::DrawActorOverlays().
Parameters
PC is the PlayerController on whose view this overlay is rendered
Canvas is the Canvas on which to draw the overlay
CameraPosition Position of Camera
CameraDir direction camera is pointing in.
References PostRenderFor().
PostSaveFromRoot()
virtual void AActor::PostSaveFromRoot (FObjectPostSaveRootContext ObjectSaveContext) virtual inherited
PostSaveRoot()
virtual void AActor::PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext) override virtual inherited
PostSpawnInitialize()
void AActor::PostSpawnInitialize (FTransform const & SpawnTransform, AActor * InOwner, APawn * InInstigator, bool bRemoteOwned, bool bNoFail, bool bDeferConstruction, ESpawnActorScaleMethod TransformScaleMethod = ESpawnActorScaleMethod::MultiplyWithRoot) inherited
Called after the actor is spawned in the world.
Responsible for setting up actor for play.
References AActor(), and ESpawnActorScaleMethod.
PostTransacted()
virtual void AActor::PostTransacted (const FTransactionObjectEvent & TransactionEvent) override virtual inherited
Reimplemented in AWorldSettings.
References PostTransacted().
PostUnregisterAllComponents()
virtual void AActor::PostUnregisterAllComponents () virtual inherited
Called after all currently registered components are cleared.
PreDuplicateFromRoot()
virtual void AActor::PreDuplicateFromRoot (FObjectDuplicationParameters & DupParams) inline virtual inherited
Definition at line 2435 of file Actor.h.
PreEditChange()
virtual void AActor::PreEditChange (FProperty * PropertyThatWillChange) override virtual inherited
References PreEditChange().
PreEditUndo()
virtual void AActor::PreEditUndo () override virtual inherited
References PreEditUndo().
PreInitializeComponents()
virtual void AActor::PreInitializeComponents () virtual inherited
Called right before components are initialized, only called during gameplay.
Reimplemented in AGameModeBase, APawn, and AWorldSettings.
PreNetReceive()
virtual void AActor::PreNetReceive () override virtual inherited
Always called immediately before properties are received from the remote.
Reimplemented in ACharacter.
PreRegisterAllComponents()
virtual void AActor::PreRegisterAllComponents () virtual inherited
Called before all the components in the Components array are registered, called both in editor and during gameplay.
References PreRegisterAllComponents().
PreRenameFromRoot()
virtual void AActor::PreRenameFromRoot (const FWorldRenameFromRootContext & RenameContext) inline virtual inherited
Definition at line 2432 of file Actor.h.
PreReplication()
virtual void AActor::PreReplication (IRepChangedPropertyTracker & ChangedPropertyTracker) virtual inherited
Called on the actor right before replication occurs.
Only called on Server, and for autonomous proxies if recording a Client Replay.
Reimplemented in ACharacter, and APawn.
PreReplicationForReplay()
virtual void AActor::PreReplicationForReplay (IRepChangedPropertyTracker & ChangedPropertyTracker) virtual inherited
Called on the actor right before replication occurs.
Called for everyone when recording a Client Replay, including Simulated Proxies.
Reimplemented in ACharacter.
PreSave()
virtual void AActor::PreSave (FObjectPreSaveContext ObjectSaveContext) override virtual inherited
PreSaveFromRoot()
virtual void AActor::PreSaveFromRoot (FObjectPreSaveRootContext ObjectSaveContext) virtual inherited
PreSaveRoot()
virtual void AActor::PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext) override virtual inherited
PreSpawnInitalization()
virtual void ALightWeightInstanceManager::PreSpawnInitalization (const FActorInstanceHandle & Handle, AActor * SpawnedActor) protected virtual
References AActor::AActor(), and FActorInstanceHandle.
PrestreamTextures()
virtual void AActor::PrestreamTextures (float Seconds, bool bEnableStreaming, int32 CinematicTextureGroups = 0) virtual inherited
Calls PrestreamTextures() for all the actor's meshcomponents.
Parameters
Seconds - Number of seconds to force all mip-levels to be resident
bEnableStreaming - Whether to start (true) or stop (false) streaming
CinematicTextureGroups - Bitfield indicating which texture groups that use extra high-resolution mips
References PrestreamTextures().
ProcessEvent()
virtual void AActor::ProcessEvent (UFunction * Function, void * Parameters) override virtual inherited
References ProcessEvent().
ProcessUserConstructionScript()
void AActor::ProcessUserConstructionScript () protected inherited
Runs UserConstructionScript, delays component registration until it's complete.
PushLevelInstanceEditingStateToProxies()
virtual void AActor::PushLevelInstanceEditingStateToProxies (bool bInEditingState) virtual inherited
Push Foundation Editing state to primitive scene proxy.
PushSelectionToProxies()
virtual void AActor::PushSelectionToProxies () virtual inherited
Push Selection to actor.
References PushSelectionToProxies().
ReceiveActorBeginCursorOver()
void AActor::ReceiveActorBeginCursorOver () inherited
Event when this actor has the mouse moved over it with the clickable interface.
References ReceiveActorBeginCursorOver().
ReceiveActorBeginOverlap()
void AActor::ReceiveActorBeginOverlap (AActor * OtherActor) inherited
Event when this actor overlaps another actor, for example a player walking into a trigger.
For events when objects have a blocking collision, for example a player hitting a wall, see 'Hit' events. \note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
References AActor(), and ReceiveActorBeginOverlap().
ReceiveActorEndCursorOver()
void AActor::ReceiveActorEndCursorOver () inherited
Event when this actor has the mouse moved off of it with the clickable interface.
References ReceiveActorEndCursorOver().
ReceiveActorEndOverlap()
void AActor::ReceiveActorEndOverlap (AActor * OtherActor) inherited
Event when an actor no longer overlaps another actor, and they have separated.
\note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
References AActor(), and ReceiveActorEndOverlap().
ReceiveActorOnClicked()
void AActor::ReceiveActorOnClicked (FKey ButtonPressed = EKeys::LeftMouseButton) inherited
Event when this actor is clicked by the mouse when using the clickable interface.
References ReceiveActorOnClicked().
ReceiveActorOnInputTouchBegin()
void AActor::ReceiveActorOnInputTouchBegin (const ETouchIndex::Type FingerIndex) inherited
Event when this actor is touched when click events are enabled.
References ReceiveActorOnInputTouchBegin().
ReceiveActorOnInputTouchEnd()
void AActor::ReceiveActorOnInputTouchEnd (const ETouchIndex::Type FingerIndex) inherited
Event when this actor is under the finger when untouched when click events are enabled.
References ReceiveActorOnInputTouchEnd().
ReceiveActorOnInputTouchEnter()
void AActor::ReceiveActorOnInputTouchEnter (const ETouchIndex::Type FingerIndex) inherited
Event when this actor has a finger moved over it with the clickable interface.
References ReceiveActorOnInputTouchEnter().
ReceiveActorOnInputTouchLeave()
void AActor::ReceiveActorOnInputTouchLeave (const ETouchIndex::Type FingerIndex) inherited
Event when this actor has a finger moved off of it with the clickable interface.
References ReceiveActorOnInputTouchLeave().
ReceiveActorOnReleased()
void AActor::ReceiveActorOnReleased (FKey ButtonReleased = EKeys::LeftMouseButton) inherited
Event when this actor is under the mouse when left mouse button is released while using the clickable interface.
References ReceiveActorOnReleased().
ReceiveAnyDamage()
void AActor::ReceiveAnyDamage (float Damage, const class UDamageType * DamageType, class AController * InstigatedBy, AActor * DamageCauser) inherited
Event when this actor takes ANY damage.
References AActor(), and ReceiveAnyDamage().
ReceiveAsyncPhysicsTick()
void AActor::ReceiveAsyncPhysicsTick (float DeltaSeconds, float SimSeconds) inherited
Event called every physics tick if bAsyncPhysicsTickEnabled is true.
References ReceiveAsyncPhysicsTick().
ReceiveBeginPlay()
void AActor::ReceiveBeginPlay () protected inherited
Event when play begins for this actor.
References ReceiveBeginPlay().
ReceiveDestroyed()
void AActor::ReceiveDestroyed () inherited
Called when the actor has been explicitly destroyed.
References ReceiveDestroyed().
ReceiveEndPlay()
void AActor::ReceiveEndPlay (EEndPlayReason::Type EndPlayReason) protected inherited
Event to notify blueprints this actor is being deleted or removed from a level.
References ReceiveEndPlay().
ReceiveHit()
void AActor::ReceiveHit (class UPrimitiveComponent * MyComp, AActor * Other, class UPrimitiveComponent * OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult & Hit) inherited
Event when this actor bumps into a blocking object, or blocks another actor that bumps into it.
This could happen due to things like Character movement, using Set Location with 'sweep' enabled, or physics simulation. For events when objects overlap (e.g. walking into a trigger) see the 'Overlap' event.
\note For collisions during physics simulation to generate hit events, 'Simulation Generates Hit Events' must be enabled. \note When receiving a hit from another object's movement (bSelfMoved is false), the directions of 'Hit.Normal' and 'Hit.ImpactNormal' will be adjusted to indicate force from the other object against this object. \note NormalImpulse will be filled in for physics-simulating bodies, but will be zero for swept-component blocking collisions.
References AActor(), and ReceiveHit().
ReceivePointDamage()
void AActor::ReceivePointDamage (float Damage, const class UDamageType * DamageType, FVector HitLocation, FVector HitNormal, class UPrimitiveComponent * HitComponent, FName BoneName, FVector ShotFromDirection, class AController * InstigatedBy, AActor * DamageCauser, const FHitResult & HitInfo) inherited
Event when this actor takes POINT damage.
References AActor(), and ReceivePointDamage().
ReceiveRadialDamage()
void AActor::ReceiveRadialDamage (float DamageReceived, const class UDamageType * DamageType, FVector Origin, const struct FHitResult & HitInfo, class AController * InstigatedBy, AActor * DamageCauser) inherited
Event when this actor takes RADIAL damage.
References AActor(), and ReceiveRadialDamage().
ReceiveTick()
void AActor::ReceiveTick (float DeltaSeconds) inherited
Event called every frame, if ticking is enabled.
References ReceiveTick().
RegisterActorTickFunctions()
virtual void AActor::RegisterActorTickFunctions (bool bRegister) protected virtual inherited
Virtual call chain to register all tick functions for the actor class hierarchy.
Parameters
bRegister - true to register, false, to unregister
RegisterAllActorTickFunctions()
void AActor::RegisterAllActorTickFunctions (bool bRegister, bool bDoComponents) inherited
When called, will call the virtual call chain to register all of the tick functions for both the actor and optionally all components Do not override this function or make it virtual.
Parameters
bRegister - true to register, false, to unregister
bDoComponents - true to also apply the change to all components
RegisterAllComponents()
virtual void AActor::RegisterAllComponents () virtual inherited
Ensure that all the components in the Components array are registered.
References RegisterAllComponents().
RegisterAsFocalPointInPhysicsReplicationLOD()
void AActor::RegisterAsFocalPointInPhysicsReplicationLOD () const inherited
Register this actors root components physics object as a focal particle in Physics Repliocation LOD.
References RegisterAsFocalPointInPhysicsReplicationLOD().
RemoveActorComponentReplicatedSubObject()
void AActor::RemoveActorComponentReplicatedSubObject (UActorComponent * OwnerComponent, UObject * SubObject) inherited
Unregister a SubObject owned by an ActorComponent so it stops being replicated.
Parameters
SubObject The SubObject to remove
RemoveAllDataLayers()
TArray< const UDataLayerInstance * > AActor::RemoveAllDataLayers () inherited
RemoveDataLayer() [1/4]
bool AActor::RemoveDataLayer (const FActorDataLayer & ActorDataLayer) inherited
References RemoveDataLayer().
RemoveDataLayer() [2/4]
bool AActor::RemoveDataLayer (const UDataLayerAsset * DataLayerAsset) inline inherited
Definition at line 1481 of file Actor.h.
References RemoveDataLayer().
RemoveDataLayer() [3/4]
bool AActor::RemoveDataLayer (const UDataLayerInstance * DataLayerInstance) inherited
RemoveDataLayer() [4/4]
bool AActor::RemoveDataLayer (const UDEPRECATED_DataLayer * DataLayer) inherited
References RemoveDataLayer().
RemoveInstance()
virtual void ALightWeightInstanceManager::RemoveInstance (int32 Index) protected virtual
Reimplemented in ALightWeightInstanceStaticMeshManager.
RemoveInstanceComponent()
void AActor::RemoveInstanceComponent (UActorComponent * Component) inherited
Removes a component from the instance components array.
References RemoveInstanceComponent().
RemoveOwnedComponent()
void AActor::RemoveOwnedComponent (UActorComponent * Component) inherited
Removes a component from the OwnedComponents array of the Actor.
In general this should not need to be called directly by anything other than UActorComponent functions
RemoveReplicatedSubObject()
void AActor::RemoveReplicatedSubObject (UObject * SubObject) inherited
Unregister a SubObject to stop replicating it's properties to clients.
This does not remove or delete it from connections where it was already replicated. By default a replicated subobject gets deleted on clients when the original pointer on the authority becomes invalid. If you want to immediately remove it from client use the DestroyReplicatedSubObjectOnRemotePeers or TearOffReplicatedSubObject functions instead of this one.
Parameters
SubObject The SubObject to remove
RemoveTickPrerequisiteActor()
virtual void AActor::RemoveTickPrerequisiteActor (AActor * PrerequisiteActor) virtual inherited
Remove tick dependency on PrerequisiteActor.
References AActor(), and RemoveTickPrerequisiteActor().
RemoveTickPrerequisiteComponent()
virtual void AActor::RemoveTickPrerequisiteComponent (UActorComponent * PrerequisiteComponent) virtual inherited
Remove tick dependency on PrerequisiteComponent.
References RemoveTickPrerequisiteComponent().
Rename()
virtual bool AActor::Rename (const TCHAR * NewName = nullptr, UObject * NewOuter = nullptr, ERenameFlags Flags = REN_None) override virtual inherited
ReplicateSubobjects()
virtual bool AActor::ReplicateSubobjects (class UActorChannel * Channel, class FOutBunch * Bunch, FReplicationFlags * RepFlags) virtual inherited
Method that allows an actor to replicate subobjects on its actor channel.
Must return true if any data was serialized into the bunch. This method is used only when bReplicateUsingRegisteredSubObjectList is false. Otherwise this function is not called and only the ReplicatedSubObjects list is used.
ReregisterAllComponents()
virtual void AActor::ReregisterAllComponents () virtual inherited
Will reregister all components on this actor.
Does a lot of work - should only really be used in editor, generally use UpdateComponentTransforms or MarkComponentsRenderStateDirty.
ReregisterComponentsWhenModified()
bool AActor::ReregisterComponentsWhenModified () const inherited
Returns true if the component is allowed to re-register its components when modified.
False for CDOs or PIE instances.
RerunConstructionScripts()
virtual void AActor::RerunConstructionScripts () virtual inherited
Rerun construction scripts, destroying all autogenerated components; will attempt to preserve the root component location.
Reset()
virtual void AActor::Reset () virtual inherited
Reset actor to initial state - used when restarting level without reloading.
Reimplemented in AController, AGameModeBase, APawn, APlayerController, and APlayerState.
References Reset().
ResetOwnedComponents()
void AActor::ResetOwnedComponents () inherited
Force the Actor to clear and rebuild its OwnedComponents array by evaluating all children (recursively) and locating components In general this should not need to be called directly, but can sometimes be necessary as part of undo/redo code paths.
ResetPropertiesForConstruction()
void AActor::ResetPropertiesForConstruction () inherited
Reset private properties to defaults, and all FRandomStream structs in this Actor, so they will start their sequence of random numbers again.
RewindForReplay()
virtual void AActor::RewindForReplay () virtual inherited
Called on the actor before checkpoint data is applied during a replay.
Only called if bReplayRewindable is set.
Reimplemented in AWorldSettings.
RouteEndPlay()
void AActor::RouteEndPlay (const EEndPlayReason::Type EndPlayReason) inherited
Non-virtual function to evaluate which portions of the EndPlay process should be dispatched for each actor.
References RouteEndPlay().
SeedAllRandomStreams()
void AActor::SeedAllRandomStreams () inherited
Find all FRandomStream structs in this Actor and generate new random seeds for them.
Serialize()
virtual void AActor::Serialize (FArchive & Ar) override virtual inherited
Reimplemented in APlayerController.
References Serialize().
SetActorEnableCollision()
void AActor::SetActorEnableCollision (bool bNewActorEnableCollision) inherited
Allows enabling/disabling collision for the whole actor.
References GetActorEnableCollision(), and SetActorEnableCollision().
SetActorHiddenInGame()
virtual void AActor::SetActorHiddenInGame (bool bNewHidden) virtual inherited
Sets the actor to be hidden in the game.
Parameters
bNewHidden Whether or not to hide the actor and all its components
References SetActorHiddenInGame().
SetActorLabel()
void AActor::SetActorLabel (const FString & NewActorLabel, bool bMarkDirty = true) inherited
Assigns a new label to this actor.
Actor labels are only available in development builds.
Parameters
NewActorLabel The new label string to assign to the actor. If empty, the actor will have a default label.
bMarkDirty If true the actor's package will be marked dirty for saving. Otherwise it will not be. You should pass false for this parameter if dirtying is not allowed (like during loads)
References SetActorLabel().
SetActorLocation()
bool AActor::SetActorLocation (const FVector & NewLocation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
Move the actor instantly to the specified location.
Parameters
NewLocation The new location to teleport the Actor to.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
Teleport How we teleport the physics state (if physics collision is enabled for this object). If equal to ETeleportType::TeleportPhysics, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If equal to ETeleportType::None, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
OutSweepHitResult The hit result from the move if swept.
Returns
Whether the location was successfully set if not swept, or whether movement occurred if swept.
References SetActorLocation().
SetActorLocationAndRotation() [1/2]
bool AActor::SetActorLocationAndRotation (FVector NewLocation, const FQuat & NewRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorLocationAndRotation().
SetActorLocationAndRotation() [2/2]
bool AActor::SetActorLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
Move the actor instantly to the specified location and rotation.
Parameters
NewLocation The new location to teleport the Actor to.
NewRotation The new rotation for the Actor.
bSweep Whether we sweep to the destination location, triggering overlaps along the way and stopping short of the target if blocked by something. Only the root component is swept and checked for blocking collision, child components move without sweeping. If collision is off, this has no effect.
Teleport How we teleport the physics state (if physics collision is enabled for this object). If equal to ETeleportType::TeleportPhysics, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If equal to ETeleportType::None, physics velocity is updated based on the change in position (affecting ragdoll parts). If CCD is on and not teleporting, this will affect objects along the entire swept volume. Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the location without teleporting will not update the location of simulated child/attached components.
OutSweepHitResult The hit result from the move if swept.
Returns
Whether the rotation was successfully set.
References SetActorLocationAndRotation().
SetActorRelativeLocation()
void AActor::SetActorRelativeLocation (FVector NewRelativeLocation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorRelativeLocation().
SetActorRelativeRotation() [1/2]
void AActor::SetActorRelativeRotation (const FQuat & NewRelativeRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorRelativeRotation().
SetActorRelativeRotation() [2/2]
void AActor::SetActorRelativeRotation (FRotator NewRelativeRotation, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorRelativeRotation().
SetActorRelativeScale3D()
void AActor::SetActorRelativeScale3D (FVector NewRelativeScale) inherited
Set the actor's RootComponent to the specified relative scale 3d.
Parameters
NewRelativeScale New scale to set the actor's RootComponent to
References SetActorRelativeScale3D().
SetActorRelativeTransform()
void AActor::SetActorRelativeTransform (const FTransform & NewRelativeTransform, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorRelativeTransform().
SetActorRotation() [1/2]
bool AActor::SetActorRotation (const FQuat & NewRotation, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorRotation().
SetActorRotation() [2/2]
bool AActor::SetActorRotation (FRotator NewRotation, ETeleportType Teleport = ETeleportType::None) inherited
Set the Actor's rotation instantly to the specified rotation.
Parameters
NewRotation The new rotation for the Actor.
Teleport How we teleport the physics state (if physics collision is enabled for this object). If equal to ETeleportType::TeleportPhysics, physics velocity for this object is unchanged (so ragdoll parts are not affected by change in location). If equal to ETeleportType::None, physics velocity is updated based on the change in position (affecting ragdoll parts). Note that when teleporting, any child/attached components will be teleported too, maintaining their current offset even if they are being simulated. Setting the rotation without teleporting will not update the rotation of simulated child/attached components.
Returns
Whether the rotation was successfully set.
References SetActorRotation().
SetActorScale3D()
void AActor::SetActorScale3D (FVector NewScale3D) inherited
Set the Actor's world-space scale.
References SetActorScale3D().
SetActorTickEnabled()
virtual void AActor::SetActorTickEnabled (bool bEnabled) virtual inherited
Set this actor's tick functions to be enabled or disabled.
Only has an effect if the function is registered This only modifies the tick function on actor itself
Parameters
bEnabled Whether it should be enabled or not
References SetActorTickEnabled().
SetActorTickInterval()
void AActor::SetActorTickInterval (float TickInterval) inherited
Sets the tick interval of this actor's primary tick function.
Will not enable a disabled tick function. Takes effect on next tick.
Parameters
TickInterval The rate at which this actor should be ticking
References SetActorTickInterval().
SetActorTransform()
bool AActor::SetActorTransform (const FTransform & NewTransform, bool bSweep = false, FHitResult * OutSweepHitResult = nullptr, ETeleportType Teleport = ETeleportType::None) inherited
References SetActorTransform().
SetAutoDestroyWhenFinished()
void AActor::SetAutoDestroyWhenFinished (bool bVal) inherited
References SetAutoDestroyWhenFinished().
SetAutonomousProxy()
void AActor::SetAutonomousProxy (const bool bInAutonomousProxy, const bool bAllowForcePropertyCompare = true) inherited
Sets whether or not this Actor is an autonomous proxy, which is an actor on a network client that is controlled by a user on that client.
References SetAutonomousProxy().
SetBrowseToAssetOverride()
void AActor::SetBrowseToAssetOverride (const FString & PackageName) inherited
Sets metadata on the Actor that allows it to point to a different asset than its source when browsing in the Content Browser.
SetCallPreReplication()
void AActor::SetCallPreReplication (bool bCall) inherited
Set whether or not we should make calls to PreReplication.
SetCallPreReplicationForReplay()
void AActor::SetCallPreReplicationForReplay (bool bCall) inherited
Set whether or not we should make calls to PreReplicationForReplay.
SetCanBeDamaged()
void AActor::SetCanBeDamaged (bool bInCanBeDamaged) inherited
Sets the value of bCanBeDamaged without causing other side effects to this instance.
SetDataFromActor()
virtual bool ALightWeightInstanceManager::SetDataFromActor (FLWIData * InData, AActor * InActor) const protected virtual
References AActor::AActor(), and SetDataFromActor().
SetFakeNetPhysicsState()
void AActor::SetFakeNetPhysicsState (bool bShouldSleep) inherited
Set the current state as a faked networked physics state for physics replication Limited for use with actors using EPhysicsReplicationMode::PredictiveInterpolation only.
Parameters
bShouldSleep Should the replication force the object to sleep
References SetFakeNetPhysicsState().
SetFolderPath()
void AActor::SetFolderPath (const FName & NewFolderPath) inherited
Assigns a new folder to this actor.
Actor folder paths are only available in development builds.
Parameters
NewFolderPath The new folder to assign to the actor.
References SetFolderPath().
SetFolderPath_Recursively()
void AActor::SetFolderPath_Recursively (const FName & NewFolderPath) inherited
Assigns a new folder to this actor and any attached children.
Actor folder paths are only available in development builds.
Parameters
NewFolderPath The new folder to assign to the actors.
References SetFolderPath_Recursively().
SetForceExternalActorLevelReferenceForPIE()
void AActor::SetForceExternalActorLevelReferenceForPIE (bool bValue) inline inherited
Definition at line 2618 of file Actor.h.
References SetForceExternalActorLevelReferenceForPIE().
SetHasActorRegisteredAllComponents()
void AActor::SetHasActorRegisteredAllComponents () inline inherited
Sets bHasRegisteredAllComponents true.
bHasRegisteredAllComponents must be set true just prior to calling PostRegisterAllComponents().
Definition at line 2154 of file Actor.h.
SetHidden()
void AActor::SetHidden (const bool bInHidden) inherited
Sets the value of bHidden without causing other side effects to this instance.
SetActorHiddenInGame is preferred preferred in most cases because it respects virtual behavior.
SetHLODLayer()
void AActor::SetHLODLayer (class UHLODLayer * InHLODLayer) inherited
Specify in which HLOD layer this actor should be included.
SetInitialActorLabel()
void AActor::SetInitialActorLabel (FStringView InitialLabel) inherited
Advanced - only to be called by UWorld::SpawnActor to set an initial label for this actor.
References SetInitialActorLabel().
SetInstigator()
void AActor::SetInstigator (APawn * InInstigator) inherited
Sets the value of Instigator without causing other side effects to this instance.
SetIsHiddenEdLayer()
virtual bool AActor::SetIsHiddenEdLayer (bool bIsHiddenEdLayer) virtual inherited
Changes bHiddenEdLayer flag and returns true if flag changed.
References SetIsHiddenEdLayer().
SetIsSpatiallyLoaded()
void AActor::SetIsSpatiallyLoaded (bool bInIsSpatiallyLoaded) inline inherited
Set if this actor should be spatially loaded or not.
Definition at line 2630 of file Actor.h.
References bIsSpatiallyLoaded, and CanChangeIsSpatiallyLoadedFlag().
SetIsTemporarilyHiddenInEditor()
virtual void AActor::SetIsTemporarilyHiddenInEditor (bool bIsHidden) virtual inherited
Explicitly sets whether or not this actor is hidden in the editor for the duration of the current editor session.
Parameters
bIsHidden True if the actor is hidden
References SetIsTemporarilyHiddenInEditor().
SetLifeSpan()
virtual void AActor::SetLifeSpan (float InLifespan) virtual inherited
Set the lifespan of this actor.
When it expires the object will be destroyed. If requested lifespan is 0, the timer is cleared and the actor will not be destroyed.
References SetLifeSpan().
SetLockLocation()
void AActor::SetLockLocation (bool bInLockLocation) inline inherited
Set the bLockLocation flag.
Definition at line 1146 of file Actor.h.
References bLockLocation.
SetLODParent()
void AActor::SetLODParent (class UPrimitiveComponent * InLODParent, float InParentDrawDistance) inherited
Set LOD Parent component for all of our components, normally associated with an ALODActor.
Parameters
InLODParent This component used to compute visibility when hierarchical LOD is enabled.
InParentDrawDistance Updates the MinDrawDistances of the LODParent
SetMakeNoiseDelegate()
void AActor::SetMakeNoiseDelegate (const FMakeNoiseDelegate & NewDelegate) static inherited
Modifies the global delegate used for handling MakeNoise.
References SetMakeNoiseDelegate().
SetMinNetUpdateFrequency()
void AActor::SetMinNetUpdateFrequency (float MinFrequency) inherited
Set the frequency to throttle down to when replicated properties are changing infrequently.
References SetMinNetUpdateFrequency().
SetNetAddressable()
void AActor::SetNetAddressable () inherited
Allows this actor to be net-addressable by full path name, even if the actor was spawned after map load.
\note : The caller is required to ensure that this actor's name is stable between server/client. Must be called before FinishSpawning
SetNetCullDistanceSquared()
void AActor::SetNetCullDistanceSquared (float DistanceSq) inherited
Set the square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
References SetNetCullDistanceSquared().
SetNetDormancy()
void AActor::SetNetDormancy (ENetDormancy NewDormancy) inherited
Puts actor in dormant networking state.
References SetNetDormancy().
SetNetDriverName()
void AActor::SetNetDriverName (FName NewNetDriverName) inherited
Set the name of the net driver associated with this actor.
Will move the actor out of the list of network actors from the old net driver and add it to the new list
Parameters
NewNetDriverName name of the new net driver association
References SetNetDriverName().
SetNetUpdateFrequency()
void AActor::SetNetUpdateFrequency (float Frequency) inherited
Set the frequency at which this object will be considered for replication.
References SetNetUpdateFrequency().
SetOwner()
virtual void AActor::SetOwner (AActor * NewOwner) virtual inherited
Set the owner of this Actor, used primarily for network replication.
Parameters
NewOwner The Actor who takes over ownership of this Actor
References AActor(), GetOwner(), and SetOwner().
SetPackageExternal()
void AActor::SetPackageExternal (bool bExternal, bool bShouldDirty = true, UPackage * ActorExternalPackage = nullptr) inherited
Set the actor packaging mode.
Parameters
bExternal will set the actor packaging mode to external if true, to internal otherwise
bShouldDirty should dirty or not the level package
ActorExternalPackage if non-null and bExternal is true, will use the provided package instead of creating one
SetPhysicsReplicationMode()
void AActor::SetPhysicsReplicationMode (const EPhysicsReplicationMode ReplicationMode) inherited
Set the physics replication mode of this body, via EPhysicsReplicationMode.
References SetPhysicsReplicationMode().
SetPivotOffset()
void AActor::SetPivotOffset (const FVector & InPivotOffset) inline inherited
Sets the local space offset added to the actor's pivot as used by the editor.
Definition at line 2507 of file Actor.h.
References PivotOffset.
SetRayTracingGroupId()
void AActor::SetRayTracingGroupId (int32 InRaytracingGroupId) inherited
Specify a RayTracingGroupId for this actors.
Components with invalid RayTracingGroupId will inherit the actors.
References SetRayTracingGroupId().
SetRemoteRoleForBackwardsCompat()
void AActor::SetRemoteRoleForBackwardsCompat (const ENetRole InRemoteRole) inline protected inherited
This function should only be used in the constructor of classes that need to set the RemoteRole for backwards compatibility purposes.
Definition at line 555 of file Actor.h.
References SetRemoteRoleForBackwardsCompat().
SetReplicatedComponentNetCondition()
void AActor::SetReplicatedComponentNetCondition (const UActorComponent * ReplicatedComponent, ELifetimeCondition NetCondition) inherited
Change the network condition of a replicated component but only after BeginPlay.
Using a network condition can allow you to filter to which client the component gets replicated to.
SetReplicatedMovement()
void AActor::SetReplicatedMovement (const FRepMovement & InReplicatedMovement) inherited
Sets the value of ReplicatedMovement without causing other side effects to this instance.
SetReplicateMovement()
virtual void AActor::SetReplicateMovement (bool bInReplicateMovement) virtual inherited
Set whether this actor's movement replicates to network clients.
Parameters
bInReplicateMovement Whether this Actor's movement replicates to clients.
Reimplemented in ACharacter.
References SetReplicateMovement().
SetReplicates()
void AActor::SetReplicates (bool bInReplicates) inherited
Set whether this actor replicates to network clients.
When this actor is spawned on the server it will be sent to clients as well. Properties flagged for replication will update on clients if they change on the server. Internally changes the RemoteRole property and handles the cases where the actor needs to be added to the network actor list.
Parameters
bInReplicates Whether this Actor replicates to network clients.
See also
https://docs.unrealengine.com/InteractiveExperiences/Networking/Actors
References SetReplicates().
SetReplicatingMovement()
void AActor::SetReplicatingMovement (bool bInReplicateMovement) inherited
Sets the value of bReplicateMovement without causing other side effects to this instance.
SetRepresentedClass()
virtual void ALightWeightInstanceManager::SetRepresentedClass (UClass * ActorClass) virtual
References SetRepresentedClass().
SetRole()
void AActor::SetRole (ENetRole InRole) inherited
Sets the value of Role without causing other side effects to this instance.
SetRootComponent()
bool AActor::SetRootComponent (USceneComponent * NewRootComponent) inherited
Sets root component to be the specified component.
NewRootComponent's owner should be this actor.
Returns
true if successful
SetRuntimeGrid()
void AActor::SetRuntimeGrid (FName InRuntimeGrid) inline inherited
Sets this actor's current target runtime grid.
Definition at line 1128 of file Actor.h.
References RuntimeGrid.
SetSpawnParameters()
virtual void ALightWeightInstanceManager::SetSpawnParameters (FActorSpawnParameters & SpawnParams) protected virtual
SetTickableWhenPaused()
void AActor::SetTickableWhenPaused (bool bTickableWhenPaused) inherited
Sets whether this actor can tick when paused.
References SetTickableWhenPaused().
SetTickGroup()
void AActor::SetTickGroup (ETickingGroup NewTickGroup) inherited
Sets the ticking group for this actor.
Parameters
NewTickGroup the new value to assign
References SetTickGroup().
ShouldCookOptimizedBPComponentData()
bool AActor::ShouldCookOptimizedBPComponentData () const inline inherited
Returns whether or not to cook optimized Blueprint component data for this actor.
Definition at line 2797 of file Actor.h.
References bOptimizeBPComponentData.
ShouldDuplicateInPIE()
virtual bool AActor::ShouldDuplicateInPIE () const inline virtual inherited
Definition at line 304 of file Actor.h.
References bIgnoreInPIE.
ShouldExport()
virtual bool AActor::ShouldExport () inline virtual inherited
Called before editor copy, true allow export.
Definition at line 2686 of file Actor.h.
References ShouldExport().
ShouldImport() [1/2]
virtual bool AActor::ShouldImport (FString * ActorPropString, bool IsMovingLevel) inline virtual inherited
Called before editor paste, true allow import.
Definition at line 2690 of file Actor.h.
References ShouldImport().
ShouldImport() [2/2]
virtual bool AActor::ShouldImport (FStringView ActorPropString, bool IsMovingLevel) inline virtual inherited
Called before editor paste, true allow import.
Definition at line 2693 of file Actor.h.
ShouldLevelKeepRefIfExternal()
virtual bool AActor::ShouldLevelKeepRefIfExternal () const inline virtual inherited
Determine how this actor should be referenced by the level when external (saved in its own package).
/
Returns
true if the level should keep a reference to the actor even if it's saved in its own package.
Definition at line 1114 of file Actor.h.
ShouldTickIfViewportsOnly()
virtual bool AActor::ShouldTickIfViewportsOnly () const virtual inherited
If true, actor is ticked even if TickType==LEVELTICK_ViewportsOnly.
Reimplemented in APawn.
StaticCreateClassActorDesc()
TUniquePtr< class FWorldPartitionActorDesc > AActor::StaticCreateClassActorDesc (const TSubclassOf< AActor > & ActorClass) static inherited
Creates an uninitialized actor descriptor from a specific class.
SupportsDataLayer()
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool AActor::SupportsDataLayer () const inherited
References SupportsDataLayer().
SupportsDataLayerType()
bool AActor::SupportsDataLayerType (TSubclassOf< UDataLayerInstance > DataLayerType) const inherited
SupportsExternalPackaging()
virtual bool AActor::SupportsExternalPackaging () const virtual inherited
Does this actor supports external packaging?
Reimplemented in AWorldSettings.
SupportsLayers()
virtual bool AActor::SupportsLayers () const virtual inherited
Returns true if the actor supports modifications to its Layers property.
References SupportsLayers().
SupportsSubRootSelection()
virtual bool AActor::SupportsSubRootSelection () const virtual inherited
Returns true if actor can be selected as a sub selection of its root selection parent.
References SupportsSubRootSelection().
SwapRoles()
void AActor::SwapRoles () inherited
Calls this to swap the Role and RemoteRole.
Only call this if you know what you're doing!
SyncReplicatedPhysicsSimulation()
void AActor::SyncReplicatedPhysicsSimulation () protected inherited
Sync IsSimulatingPhysics() with ReplicatedMovement.bRepPhysics.
References SyncReplicatedPhysicsSimulation().
TakeDamage()
virtual float AActor::TakeDamage (float DamageAmount, struct FDamageEvent const & DamageEvent, class AController * EventInstigator, AActor * DamageCauser) virtual inherited
Apply damage to this actor.
See also
https://www.unrealengine.com/blog/damage-in-ue4
Parameters
DamageAmount How much damage to apply
DamageEvent Data package that fully describes the damage received.
EventInstigator The Controller responsible for the damage.
DamageCauser The Actor that directly caused the damage (e.g. the projectile that exploded, the rock that landed on you)
Returns
The amount of damage actually applied.
Reimplemented in APawn.
References AActor(), and TakeDamage().
TearOff()
virtual void AActor::TearOff () virtual inherited
Networking - Server - TearOff this actor to stop replication to clients.
Will set bTearOff to true.
References TearOff().
TearOffReplicatedSubObjectOnRemotePeers() [1/2]
void AActor::TearOffReplicatedSubObjectOnRemotePeers (UActorComponent * OwnerComponent, UObject * SubObject) inherited
Similar to the other tear off function but for subobjects owned by an ActorComponent.
TearOffReplicatedSubObjectOnRemotePeers() [2/2]
void AActor::TearOffReplicatedSubObjectOnRemotePeers (UObject * SubObject) inherited
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
This means that on the remote connection the network engine will stop holding a reference to the subobject and it's up to other systems to keep that reference active or the subobject will get garbage collected. Note that the subobject won't be replicated anymore, so it's final state on the client will be the one from the last replication update sent. If you are using the legacy subobject replication method (ReplicateSubObjects() aka bReplicateUsingRegisteredSubObjectList=false) make sure the subobject doesn't get replicated there either.
Parameters
SubObject The SubObject to tear off
TeleportSucceeded()
virtual void AActor::TeleportSucceeded (bool bIsATest) inline virtual inherited
Called from TeleportTo() when teleport succeeds.
Reimplemented in APawn.
Definition at line 3330 of file Actor.h.
References TeleportSucceeded().
TeleportTo()
virtual bool AActor::TeleportTo (const FVector & DestLocation, const FRotator & DestRotation, bool bIsATest = false, bool bNoCheck = false) virtual inherited
Used for adding actors to levels or teleporting them to a new location.
The result of this function is independent of the actor's current location and rotation. If the actor doesn't fit exactly at the location specified, tries to slightly move it out of walls and such if bNoCheck is false.
Parameters
DestLocation The target destination point
DestRotation The target rotation at the destination
bIsATest is true if this is a test movement, which shouldn't cause any notifications (used by AI pathfinding, for example)
bNoCheck is true if we should skip checking for encroachment in the world or other actors
Returns
true if the actor has been successfully moved, or false if it couldn't fit.
Tick()
virtual void ALightWeightInstanceManager::Tick (float DeltaSeconds) virtual
Function called every frame on this Actor.
Override this function to implement custom logic to be executed every frame. Note that Tick is disabled by default, and you will need to check PrimaryActorTick.bCanEverTick is set to true to enable it.
Parameters
DeltaSeconds Game time elapsed during last frame modified by the time dilation
Reimplemented from AActor.
References Tick().
TickActor()
virtual void AActor::TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction & ThisTickFunction) virtual inherited
Dispatches the once-per frame Tick() function for this actor.
Parameters
DeltaTime The time slice of this tick
TickType The type of tick that is happening
ThisTickFunction The tick function that is firing, useful for getting the completion handle
Reimplemented in AController, and APlayerController.
References TickActor().
TornOff()
virtual void AActor::TornOff () virtual inherited
Networking - called on client when actor is torn off (bTearOff==true), meaning it's no longer replicated to clients.
See also
bTearOff
Reimplemented in ACharacter.
References TornOff().
UninitializeComponents()
void AActor::UninitializeComponents () inherited
Iterate over components array and call UninitializeComponent, called when the actor is ending play.
UnregisterAllComponents()
virtual void AActor::UnregisterAllComponents (bool bForReregister = false) virtual inherited
Unregister all currently registered components.
Parameters
bForReregister If true, RegisterAllComponents will be called immediately after this so some slow operations can be avoided
UnregisterAsFocalPointInPhysicsReplicationLOD()
void AActor::UnregisterAsFocalPointInPhysicsReplicationLOD () const inherited
Unregister this actors root components physics object from being a focal particle in Physics Repliocation LOD.
References UnregisterAsFocalPointInPhysicsReplicationLOD().
UpdateAllReplicatedComponents()
void AActor::UpdateAllReplicatedComponents () inherited
Completely synchronizes the replicated components array so that it contains exactly the number of replicated components currently owned.
UpdateComponentTransforms()
void AActor::UpdateComponentTransforms () inherited
Update all components transforms.
UpdateComponentVisibility()
void AActor::UpdateComponentVisibility () inherited
Update all components visibility state.
UpdateDataAtIndex()
virtual void ALightWeightInstanceManager::UpdateDataAtIndex (FLWIData * InData, int32 Index) protected virtual
References UpdateDataAtIndex().
UpdateOverlaps()
void AActor::UpdateOverlaps (bool bDoNotifies = true) inherited
Queries world and updates overlap detection state for this actor.
Parameters
bDoNotifies True to dispatch being/end overlap notifications when these events occur.
UpdateReplicatedComponent()
void AActor::UpdateReplicatedComponent (UActorComponent * Component) inherited
Called when the replicated state of a component changes to update the Actor's cached ReplicatedComponents array.
UpdateReplicatePhysicsCondition()
void AActor::UpdateReplicatePhysicsCondition () inherited
Updates the ReplicatePhysics condition.
That information needs to be pushed to the ReplicationSystem.
UserConstructionScript()
void AActor::UserConstructionScript () inherited
Construction script, the place to spawn components and do other setup.
\note Name used in CreateBlueprint function
References UserConstructionScript().
UseShortConnectTimeout()
virtual bool AActor::UseShortConnectTimeout () const inline virtual inherited
Used by the net connection to determine if a net owning actor should switch to using the shortened timeout value.
Returns
true to switch from InitialConnectTimeout to ConnectionTimeout values on the net driver
Reimplemented in APlayerController.
Definition at line 2848 of file Actor.h.
WasRecentlyRendered()
bool AActor::WasRecentlyRendered (float Tolerance = 0.2f) const inherited
Returns true if this actor has been rendered "recently", with a tolerance in seconds to define what "recent" means.
e.g.: If a tolerance of 0.1 is used, this function will return true only if the actor was rendered in the last 0.1 seconds of game time.
Parameters
Tolerance How many seconds ago the actor last render time can be and still count as having been "recently" rendered.
Returns
Whether this actor was recently rendered.
References WasRecentlyRendered().
Friends And Related Symbol Documentation
FActorInstanceHandle
friend struct FActorInstanceHandle friend
Definition at line 36 of file LightWeightInstanceManager.h.
References FActorInstanceHandle.
FLightWeightInstanceSubsystem
friend struct FLightWeightInstanceSubsystem friend
Definition at line 35 of file LightWeightInstanceManager.h.
References FLightWeightInstanceSubsystem.
ULightWeightInstanceBlueprintFunctionLibrary
friend class ULightWeightInstanceBlueprintFunctionLibrary friend
Definition at line 37 of file LightWeightInstanceManager.h.
References ULightWeightInstanceBlueprintFunctionLibrary.
Member Data Documentation
AcceptedClass
TSubclassOf<AActor> ALightWeightInstanceManager::AcceptedClass protected
Definition at line 151 of file LightWeightInstanceManager.h.
ActorCategory
uint8 AActor::ActorCategory = 0 inherited
Project-specific field that help to categorize actors for reporting purposes.
Definition at line 740 of file Actor.h.
ActorGuid
FGuid AActor::ActorGuid protected inherited
The GUID for this actor; this guid will be the same for actors from instanced streaming levels.
See also
ActorInstanceGuid, FActorInstanceGuidMapper \note Don't use VisibleAnywhere here to avoid getting the CPF_Edit flag and get this property reset when resetting to defaults. See FActorDetails::AddActorCategory and EditorUtilities::CopySingleProperty for details.
Definition at line 1055 of file Actor.h.
ActorInstanceGuid
FGuid AActor::ActorInstanceGuid protected inherited
The instance GUID for this actor; this guid will be unique for actors from instanced streaming levels.
See also
ActorGuid \note This is not guaranteed to be valid during PostLoad, but safe to access from RegisterAllComponents.
Definition at line 1063 of file Actor.h.
Actors
TMap<int32, TObjectPtr<AActor> > ALightWeightInstanceManager::Actors protected
Definition at line 186 of file LightWeightInstanceManager.h.
AttachmentReplication
struct FRepAttachment AActor::AttachmentReplication protected inherited
Used for replicating attachment of this actor's RootComponent to another actor.
This is filled in via GatherCurrentMovement() when the RootComponent has an AttachParent.
Definition at line 776 of file Actor.h.
AutoReceiveInput
TEnumAsByte<EAutoReceiveInput::Type> AActor::AutoReceiveInput inherited
Automatically registers this actor to receive input from a player.
Definition at line 835 of file Actor.h.
bActorLabelEditable
uint8 AActor::bActorLabelEditable protected inherited
Is the actor label editable by the user?
Definition at line 1260 of file Actor.h.
bActorSeamlessTraveled
uint8 AActor::bActorSeamlessTraveled inherited
Indicates the actor was pulled through a seamless travel.
Definition at line 525 of file Actor.h.
bAllowReceiveTickEventOnDedicatedServer
uint8 AActor::bAllowReceiveTickEventOnDedicatedServer protected inherited
If false, the Blueprint ReceiveTick() event will be disabled on dedicated servers.
See also
AllowReceiveTickEventOnDedicatedServer()
Definition at line 570 of file Actor.h.
bAllowTickBeforeBeginPlay
uint8 AActor::bAllowTickBeforeBeginPlay inherited
Whether we allow this Actor to tick before it receives the BeginPlay event.
Normally we don't tick actors until after BeginPlay; this setting allows this behavior to be overridden. This Actor must be able to tick for this setting to be relevant.
Definition at line 476 of file Actor.h.
bAlwaysRelevant
uint8 AActor::bAlwaysRelevant inherited
Always relevant for network (overrides bOnlyRelevantToOwner).
Definition at line 297 of file Actor.h.
BaseInstanceName
FString ALightWeightInstanceManager::BaseInstanceName protected
Definition at line 145 of file LightWeightInstanceManager.h.
bAsyncPhysicsTickEnabled
uint8 AActor::bAsyncPhysicsTickEnabled protected inherited
Whether to use use the async physics tick with this actor.
Definition at line 649 of file Actor.h.
bBlockInput
uint8 AActor::bBlockInput inherited
If true, all input on the stack below this actor will not be considered.
Definition at line 494 of file Actor.h.
bCanBeInCluster
uint8 AActor::bCanBeInCluster protected inherited
If true, this actor can be put inside of a GC Cluster to improve Garbage Collection performance.
Definition at line 563 of file Actor.h.
bCanPlayFromHere
uint8 AActor::bCanPlayFromHere protected inherited
Whether the actor can be used as a PlayFromHere origin (OnPlayFromHere() will be called on that actor)
Definition at line 1276 of file Actor.h.
bCollideWhenPlacing
uint8 AActor::bCollideWhenPlacing inherited
This actor collides with the world when placing in the editor, even if RootComponent collision is disabled.
Does not affect spawning,
See also
SpawnCollisionHandlingMethod
Definition at line 498 of file Actor.h.
bDefaultOutlinerExpansionState
uint8 AActor::bDefaultOutlinerExpansionState inherited
Default expansion state for this actor.
Some actors have attached children that we may not want to automatically expand by default
Definition at line 1251 of file Actor.h.
bEditable
uint8 AActor::bEditable protected inherited
Whether the actor can be manipulated by editor operations.
Definition at line 1264 of file Actor.h.
bEnableAutoLODGeneration
uint8 AActor::bEnableAutoLODGeneration inherited
Whether this actor should be considered or not during HLOD generation.
Definition at line 518 of file Actor.h.
bExchangedRoles
uint8 AActor::bExchangedRoles inherited
Whether we have already exchanged Role/RemoteRole on the client, as when removing then re-adding a streaming level.
Causes all initialization to be performed again even though the actor may not have actually been reloaded.
Definition at line 441 of file Actor.h.
bFindCameraComponentWhenViewTarget
uint8 AActor::bFindCameraComponentWhenViewTarget inherited
If true, this actor should search for an owned camera component to view through when used as a view target.
Definition at line 502 of file Actor.h.
bGenerateOverlapEventsDuringLevelStreaming
uint8 AActor::bGenerateOverlapEventsDuringLevelStreaming inherited
If true, this actor will generate overlap Begin/End events when spawned as part of level streaming, which includes initial level load.
You might enable this is in the case where a streaming level loads around an actor and you want Begin/End overlap events to trigger.
See also
UpdateOverlapsMethodDuringLevelStreaming
Definition at line 510 of file Actor.h.
bHiddenEd
uint8 AActor::bHiddenEd inherited
Whether this actor is hidden within the editor viewport.
Definition at line 1233 of file Actor.h.
bHiddenEdLayer
uint8 AActor::bHiddenEdLayer inherited
Whether this actor is hidden by the layer browser.
Definition at line 1241 of file Actor.h.
bHiddenEdLevel
uint8 AActor::bHiddenEdLevel inherited
Whether this actor is hidden by the level browser.
Definition at line 1245 of file Actor.h.
bIgnoreInPIE
uint8 AActor::bIgnoreInPIE inherited
Experimental: this will force this actor to be ignored in PIE, will not work if the actor has references to other actors without the flag set, use with care.
Definition at line 357 of file Actor.h.
bIgnoresOriginShifting
uint8 AActor::bIgnoresOriginShifting inherited
Whether this actor should not be affected by world origin shifting.
Definition at line 514 of file Actor.h.
bIsEditorOnlyActor
uint8 AActor::bIsEditorOnlyActor inherited
Whether this actor is editor-only.
Use with care, as if this actor is referenced by anything else that reference will be NULL in cooked builds
Definition at line 522 of file Actor.h.
bIsEditorPreviewActor
uint8 AActor::bIsEditorPreviewActor inherited
True if this actor is the preview actor dragged out of the content browser.
Definition at line 1237 of file Actor.h.
bIsMainWorldOnly
uint8 AActor::bIsMainWorldOnly inherited
Definition at line 353 of file Actor.h.
bIsSpatiallyLoaded
uint8 AActor::bIsSpatiallyLoaded protected inherited
Determine if this actor is spatially loaded when placed in a partitioned world.
If true, this actor will be loaded when in the range of any streaming sources and if (1) in no data layers, or (2) one or more of its data layers are enabled. If false, this actor will be loaded if (1) in no data layers, or (2) one or more of its data layers are enabled.
Definition at line 1284 of file Actor.h.
bListedInSceneOutliner
uint8 AActor::bListedInSceneOutliner protected inherited
Whether this actor should be listed in the scene outliner.
Definition at line 1268 of file Actor.h.
bLockLocation
uint8 AActor::bLockLocation protected inherited
If true, prevents the actor from being moved in the editor viewport.
Definition at line 1256 of file Actor.h.
BlueprintCreatedComponents
TArray<TObjectPtr<UActorComponent> > AActor::BlueprintCreatedComponents inherited
Array of ActorComponents that are created by blueprints and serialized per-instance.
Definition at line 4294 of file Actor.h.
bNetCheckedInitialPhysicsState
uint8 AActor::bNetCheckedInitialPhysicsState protected inherited
Flag indicating we have checked initial simulating physics state to sync networked proxies to the server.
Definition at line 573 of file Actor.h.
bNetLoadOnClient
uint8 AActor::bNetLoadOnClient inherited
This actor will be loaded on network clients during map load.
Definition at line 445 of file Actor.h.
bNetStartup
uint8 AActor::bNetStartup inherited
If true, this actor was loaded directly from the map, and for networking purposes can be addressed by its full path name.
Definition at line 289 of file Actor.h.
bNetTemporary
uint8 AActor::bNetTemporary inherited
If true, when the actor is spawned it will be sent to the client but receive no further replication updates from the server afterwards.
Definition at line 286 of file Actor.h.
bNetUseOwnerRelevancy
uint8 AActor::bNetUseOwnerRelevancy inherited
If actor has valid Owner, call Owner's IsNetRelevantFor and GetNetPriority.
Definition at line 449 of file Actor.h.
bOnlyRelevantToOwner
uint8 AActor::bOnlyRelevantToOwner inherited
If true, this actor is only relevant to its owner.
If this flag is changed during play, all non-owner channels would need to be explicitly closed.
Definition at line 293 of file Actor.h.
bOptimizeBPComponentData
uint8 AActor::bOptimizeBPComponentData protected inherited
Whether to cook additional data to speed up spawn events at runtime for any Blueprint classes based on this Actor.
This option may slightly increase memory usage in a cooked build.
Definition at line 1272 of file Actor.h.
bRelevantForLevelBounds
uint8 AActor::bRelevantForLevelBounds inherited
If true, this actor's component's bounds will be included in the level's bounding box unless the Actor's class has overridden IsLevelBoundsRelevant.
Definition at line 460 of file Actor.h.
bRelevantForNetworkReplays
uint8 AActor::bRelevantForNetworkReplays inherited
If true, this actor will be replicated to network replays (default is true)
Definition at line 453 of file Actor.h.
bReplayRewindable
uint8 AActor::bReplayRewindable inherited
If true, this actor will only be destroyed during scrubbing if the replay is set to a time before the actor existed.
Otherwise, RewindForReplay will be called if we detect the actor needs to be reset. Note, this Actor must not be destroyed by gamecode, and RollbackViaDeletion may not be used.
Definition at line 468 of file Actor.h.
bReplicates
uint8 AActor::bReplicates protected inherited
If true, this actor will replicate to remote machines.
See also
SetReplicates()
Definition at line 552 of file Actor.h.
bReplicateUsingRegisteredSubObjectList
uint8 AActor::bReplicateUsingRegisteredSubObjectList protected inherited
When true the replication system will only replicate the registered subobjects and the replicated actor components list When false the replication system will instead call the virtual ReplicateSubobjects() function where the subobjects and actor components need to be manually replicated.
Definition at line 580 of file Actor.h.
bRunConstructionScriptOnDrag
uint8 AActor::bRunConstructionScriptOnDrag inherited
If true during PostEditMove the construction script will be run every time.
If false it will only run when the drag finishes.
Definition at line 1248 of file Actor.h.
bUsePercentageBasedScaling
bool AActor::bUsePercentageBasedScaling static inherited
Todo
: Remove this flag once it is decided that additive interactive scaling is what we want
Definition at line 2565 of file Actor.h.
Children
TArray<TObjectPtr<AActor> > AActor::Children inherited
Array of all Actors whose Owner is this actor, these are not necessarily spawned by UChildActorComponent.
Definition at line 977 of file Actor.h.
ContentBundleGuid
FGuid AActor::ContentBundleGuid protected inherited
The GUID for this actor's content bundle.
Definition at line 1069 of file Actor.h.
CopyPasteId
uint32 AActor::CopyPasteId inherited
The copy/paste id used to remap actors during copy operations.
Definition at line 1086 of file Actor.h.
CreationTime
float AActor::CreationTime inherited
The time this actor was created, relative to World->GetTimeSeconds().
See also
UWorld::GetTimeSeconds()
Definition at line 845 of file Actor.h.
CurrentTransactionAnnotation
TSharedPtr<FActorTransactionAnnotation> AActor::CurrentTransactionAnnotation inherited
Cached pointer to the transaction annotation data from PostEditUndo to be used in the next RerunConstructionScript.
Definition at line 2418 of file Actor.h.
CustomTimeDilation
float AActor::CustomTimeDilation inherited
Allow each actor to run at a different time speed.
The DeltaTime for a frame is multiplied by the global TimeDilation (in WorldSettings) and this CustomTimeDilation for this actor's tick.
Definition at line 748 of file Actor.h.
DataLayerAssets
TArray<TSoftObjectPtr<UDataLayerAsset> > AActor::DataLayerAssets protected inherited
DataLayers assets the actor belongs to.
Definition at line 1077 of file Actor.h.
DataLayers
TArray<FActorDataLayer> AActor::DataLayers protected inherited
DataLayers the actor belongs to.
Definition at line 1073 of file Actor.h.
DestroyedActorIndices
TArray<int32> ALightWeightInstanceManager::DestroyedActorIndices protected
Definition at line 188 of file LightWeightInstanceManager.h.
DetachFence
FRenderCommandFence AActor::DetachFence inherited
A fence to track when the primitive is detached from the scene in the rendering thread.
Definition at line 4371 of file Actor.h.
ExternalDataLayerAsset
TObjectPtr<const UExternalDataLayerAsset> AActor::ExternalDataLayerAsset protected inherited
Definition at line 1082 of file Actor.h.
FreeIndices
TArray<int32> ALightWeightInstanceManager::FreeIndices protected
Definition at line 192 of file LightWeightInstanceManager.h.
GridPlacement_DEPRECATED
PRAGMA_DISABLE_DEPRECATION_WARNINGS EActorGridPlacement AActor::GridPlacement_DEPRECATED protected inherited
Deprecated
Use bIsSpatiallyLoaded instead
Definition at line 760 of file Actor.h.
GroupActor
TObjectPtr<AActor> AActor::GroupActor inherited
The editor-only group this actor is a part of.
Definition at line 1090 of file Actor.h.
HiddenEditorViews
uint64 AActor::HiddenEditorViews inherited
Bitflag to represent which views this actor is hidden in, via per-view layer visibility.
Definition at line 1098 of file Actor.h.
InitialLifeSpan
float AActor::InitialLifeSpan inherited
How long this Actor lives before dying, 0=forever.
Note this is the INITIAL value and should not be modified once play has begun.
Definition at line 744 of file Actor.h.
InputComponent
TObjectPtr<class UInputComponent> AActor::InputComponent inherited
Component that handles input for this actor, if input is enabled.
Definition at line 849 of file Actor.h.
InputPriority
int32 AActor::InputPriority inherited
The priority of this input component when pushed in to the stack.
Definition at line 839 of file Actor.h.
InstanceToActorConversionsInProgress
TArray<int32> ALightWeightInstanceManager::InstanceToActorConversionsInProgress protected
Definition at line 206 of file LightWeightInstanceManager.h.
InstanceTransforms
TArray<FTransform> ALightWeightInstanceManager::InstanceTransforms protected
Definition at line 160 of file LightWeightInstanceManager.h.
IntermediateOwner
TWeakObjectPtr<AActor> AActor::IntermediateOwner = nullptr inherited
Used to track changes to Owner during Undo events.
Definition at line 795 of file Actor.h.
Layers
TArray< FName > AActor::Layers inherited
Layers the actor belongs to.
This is outside of the editoronly data to allow hiding of LD-specified layers at runtime for profiling.
Definition at line 1033 of file Actor.h.
MinNetUpdateFrequency
float AActor::MinNetUpdateFrequency inherited
Used to determine what rate to throttle down to when replicated properties are changing infrequently.
Definition at line 868 of file Actor.h.
NetCullDistanceSquared
float AActor::NetCullDistanceSquared inherited
Square of the max distance from the client's viewpoint that this actor is relevant and will be replicated.
Definition at line 858 of file Actor.h.
NetDormancy
TEnumAsByte<enum ENetDormancy> AActor::NetDormancy inherited
Dormancy setting for actor to take itself off of the replication list without being destroyed on clients.
Definition at line 819 of file Actor.h.
NetDriverName
FName AActor::NetDriverName protected inherited
Used to specify the net driver to replicate on (NAME_None || NAME_GameNetDriver is the default net driver)
Definition at line 801 of file Actor.h.
NetPriority
float AActor::NetPriority inherited
Priority for this actor when checking for replication in a low bandwidth or saturated situation, higher priority means it is more likely to replicate.
Definition at line 872 of file Actor.h.
NetTag
int32 AActor::NetTag inherited
Internal - used by UNetDriver.
Definition at line 853 of file Actor.h.
NetUpdateFrequency
float AActor::NetUpdateFrequency inherited
How often (per second) this actor will be considered for replication, used to determine NetUpdateTime.
Definition at line 863 of file Actor.h.
OnActorBeginOverlap
FActorBeginOverlapSignature AActor::OnActorBeginOverlap inherited
Called when another actor begins to overlap this actor, for example a player walking into a trigger.
For events when objects have a blocking collision, for example a player hitting a wall, see 'Hit' events. \note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
Definition at line 1322 of file Actor.h.
OnActorEndOverlap
FActorEndOverlapSignature AActor::OnActorEndOverlap inherited
Called when another actor stops overlapping this actor.
\note Components on both this and the other Actor must have bGenerateOverlapEvents set to true to generate overlap events.
Definition at line 1329 of file Actor.h.
OnActorHit
FActorHitSignature AActor::OnActorHit inherited
Called when this Actor hits (or is hit by) something solid.
This could happen due to things like Character movement, using Set Location with 'sweep' enabled, or physics simulation. For events when objects overlap (e.g. walking into a trigger) see the 'Overlap' event. \note For collisions during physics simulation to generate hit events, 'Simulation Generates Hit Events' must be enabled.
Definition at line 1369 of file Actor.h.
OnBeginCursorOver
FActorBeginCursorOverSignature AActor::OnBeginCursorOver inherited
Called when the mouse cursor is moved over this actor if mouse over events are enabled in the player controller.
Definition at line 1333 of file Actor.h.
OnClicked
FActorOnClickedSignature AActor::OnClicked inherited
Called when the left mouse button is clicked while the mouse is over this actor and click events are enabled in the player controller.
Definition at line 1341 of file Actor.h.
OnDestroyed
FActorDestroyedSignature AActor::OnDestroyed inherited
Event triggered when the actor has been explicitly destroyed.
Definition at line 2325 of file Actor.h.
OnEndCursorOver
FActorEndCursorOverSignature AActor::OnEndCursorOver inherited
Called when the mouse cursor is moved off this actor if mouse over events are enabled in the player controller.
Definition at line 1337 of file Actor.h.
OnEndPlay
FActorEndPlaySignature AActor::OnEndPlay inherited
Event triggered when the actor is being deleted or removed from a level.
Definition at line 2329 of file Actor.h.
OnInputTouchBegin
FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin inherited
Called when a touch input is received over this actor when touch events are enabled in the player controller.
Definition at line 1349 of file Actor.h.
OnInputTouchEnd
FActorOnInputTouchEndSignature AActor::OnInputTouchEnd inherited
Called when a touch input is received over this component when touch events are enabled in the player controller.
Definition at line 1353 of file Actor.h.
OnInputTouchEnter
FActorBeginTouchOverSignature AActor::OnInputTouchEnter inherited
Called when a finger is moved over this actor when touch over events are enabled in the player controller.
Definition at line 1357 of file Actor.h.
OnInputTouchLeave
FActorEndTouchOverSignature AActor::OnInputTouchLeave inherited
Called when a finger is moved off this actor when touch over events are enabled in the player controller.
Definition at line 1361 of file Actor.h.
OnPackagingModeChanged
FActorOnPackagingModeChanged AActor::OnPackagingModeChanged inherited
Definition at line 1122 of file Actor.h.
OnReleased
FActorOnReleasedSignature AActor::OnReleased inherited
Called when the left mouse button is released while the mouse is over this actor and click events are enabled in the player controller.
Definition at line 1345 of file Actor.h.
OnTakeAnyDamage
FTakeAnyDamageSignature AActor::OnTakeAnyDamage inherited
Called when the actor is damaged in any way.
Definition at line 1306 of file Actor.h.
OnTakePointDamage
FTakePointDamageSignature AActor::OnTakePointDamage inherited
Called when the actor is damaged by point damage.
Definition at line 1310 of file Actor.h.
OnTakeRadialDamage
FTakeRadialDamageSignature AActor::OnTakeRadialDamage inherited
Called when the actor is damaged by radial damage.
Definition at line 1314 of file Actor.h.
Owner
TObjectPtr<AActor> AActor::Owner inherited
Owner of this Actor, used primarily for replication (bNetUseOwnerRelevancy & bOnlyRelevantToOwner) and visibility (PrimitiveComponent bOwnerNoSee and bOnlyOwnerSee)
See also
SetOwner(), GetOwner()
Definition at line 789 of file Actor.h.
PivotOffset
FVector AActor::PivotOffset protected inherited
Local space pivot offset for the actor, only used in the editor.
Definition at line 987 of file Actor.h.
PreEditChangeDataLayers
TArray<TSoftObjectPtr<UDataLayerAsset> > AActor::PreEditChangeDataLayers protected inherited
Definition at line 1079 of file Actor.h.
PrimaryActorTick
struct FActorTickFunction AActor::PrimaryActorTick inherited
Primary Actor tick function, which calls TickActor().
Tick functions can be configured to control whether ticking is enabled, at what time during a frame the update occurs, and to set up tick dependencies.
See also
https://docs.unrealengine.com/API/Runtime/Engine/Engine/FTickFunction
AddTickPrerequisiteActor(), AddTickPrerequisiteComponent()
Definition at line 282 of file Actor.h.
ProcessEventDelegate
FOnProcessEvent AActor::ProcessEventDelegate static inherited
Delegate for globally hooking ProccessEvent calls - used by a non-public testing plugin.
Definition at line 4365 of file Actor.h.
ReplicatedComponents
TArray<UActorComponent*> AActor::ReplicatedComponents protected inherited
Set of replicated components, stored as an array to save space as this is generally not very large.
Definition at line 4273 of file Actor.h.
RepresentedClass
TSubclassOf<AActor> ALightWeightInstanceManager::RepresentedClass protected
Definition at line 148 of file LightWeightInstanceManager.h.
RootComponent
TObjectPtr<USceneComponent> AActor::RootComponent protected inherited
The component that defines the transform (location, rotation, scale) of this Actor in the world, all other components must be attached to this one somehow.
Definition at line 982 of file Actor.h.
RuntimeGrid
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName AActor::RuntimeGrid protected inherited
Determine in which partition grid this actor will be placed in the partition (if the world is partitioned).
If None, the decision will be left to the partition.
Definition at line 768 of file Actor.h.
SpawnCollisionHandlingMethod
ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod inherited
Controls how to handle spawning this actor in a situation where it's colliding with something else.
"Default" means AlwaysSpawn here.
Definition at line 831 of file Actor.h.
SpriteScale
float AActor::SpriteScale inherited
The scale to apply to any billboard components in editor builds (happens in any WITH_EDITOR build, including non-cooked games).
Definition at line 1094 of file Actor.h.
Tags
TArray<FName> AActor::Tags inherited
Array of tags that can be used for grouping and categorizing.
Definition at line 1298 of file Actor.h.
TimerHandle_LifeSpanExpired
FTimerHandle AActor::TimerHandle_LifeSpanExpired protected inherited
Handle for efficient management of LifeSpanExpired timer.
Definition at line 991 of file Actor.h.
UpdateOverlapsMethodDuringLevelStreaming
EActorUpdateOverlapsMethod AActor::UpdateOverlapsMethodDuringLevelStreaming protected inherited
Condition for calling UpdateOverlaps() to initialize overlap state when loaded in during level streaming.
If set to 'UseConfigDefault', the default specified in ini (displayed in 'DefaultUpdateOverlapsMethodDuringLevelStreaming') will be used. If overlaps are not initialized, this actor and attached components will not have an initial state of what objects are touching it, and overlap events may only come in once one of those objects update overlaps themselves (for example when moving). However if an object touching it does initialize state, both objects will know about their touching state with each other. This can be a potentially large performance savings during level loading and streaming, and is safe if the object and others initially overlapping it do not need the overlap state because they will not trigger overlap notifications.
Note that if 'bGenerateOverlapEventsDuringLevelStreaming' is true, overlaps are always updated in this case, but that flag determines whether the Begin/End overlap events are triggered.
See also
bGenerateOverlapEventsDuringLevelStreaming, DefaultUpdateOverlapsMethodDuringLevelStreaming, GetUpdateOverlapsMethodDuringLevelStreaming()
Definition at line 666 of file Actor.h.
ValidIndices
TArray<bool> ALightWeightInstanceManager::ValidIndices protected
Definition at line 196 of file LightWeightInstanceManager.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/LightWeightInstanceManager.h