Unreal Engine 5.6 C++ Documentation: FInputDevicePropertyHandle Struct Reference
FInputDevicePropertyHandle Struct Reference
A handle to an active input device property that is being used by the InputDeviceSubsytem.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDevicePropertyHandle.h>
Public Member Functions
FInputDevicePropertyHandle ()
~FInputDevicePropertyHandle ()=default
bool IsValid () const
Returns true if this handle is valid.
uint32 GetTypeHash () const
bool operator== (const FInputDevicePropertyHandle &Other) const
bool operator!= (const FInputDevicePropertyHandle &Other) const
FString ToString () const
Static Public Attributes
static FInputDevicePropertyHandle InvalidHandle
An invalid Input Device Property handle.
Friends
class UInputDeviceSubsystem
uint32 GetTypeHash (const FInputDevicePropertyHandle &InHandle)
Detailed Description
A handle to an active input device property that is being used by the InputDeviceSubsytem.
Definition at line 8 of file InputDevicePropertyHandle.h.
Constructor & Destructor Documentation
FInputDevicePropertyHandle()
FInputDevicePropertyHandle::FInputDevicePropertyHandle ()
References FInputDevicePropertyHandle().
~FInputDevicePropertyHandle()
FInputDevicePropertyHandle::~FInputDevicePropertyHandle () default
References FInputDevicePropertyHandle().
Member Function Documentation
GetTypeHash()
uint32 FInputDevicePropertyHandle::GetTypeHash () const
References GetTypeHash().
IsValid()
bool FInputDevicePropertyHandle::IsValid () const
Returns true if this handle is valid.
References IsValid().
operator!=()
bool FInputDevicePropertyHandle::operator!= (const FInputDevicePropertyHandle & Other) const
References FInputDevicePropertyHandle().
operator==()
bool FInputDevicePropertyHandle::operator== (const FInputDevicePropertyHandle & Other) const
References FInputDevicePropertyHandle().
ToString()
FString FInputDevicePropertyHandle::ToString () const
References FInputDevicePropertyHandle(), and ToString().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FInputDevicePropertyHandle & InHandle) friend
References FInputDevicePropertyHandle(), and GetTypeHash().
UInputDeviceSubsystem
friend class UInputDeviceSubsystem friend
Definition at line 11 of file InputDevicePropertyHandle.h.
References UInputDeviceSubsystem.
Member Data Documentation
InvalidHandle
FInputDevicePropertyHandle FInputDevicePropertyHandle::InvalidHandle static
An invalid Input Device Property handle.
Definition at line 22 of file InputDevicePropertyHandle.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDevicePropertyHandle.h