Unreal Engine 5.6 C++ Documentation: FPlayerMuteList Struct Reference
FPlayerMuteList Struct Reference
Container responsible for managing the mute state of a player controller at the gameplay level (VoiceInterface handles actual muting)
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerMuteList.h>
Public Member Functions
FPlayerMuteList ()
bool AddVoiceBlockReason (const FUniqueNetIdPtr &PlayerId, EVoiceBlockReasons VoiceBlockReason)
Add a filter reason for an id to this player's mutelist.
bool RemoveVoiceBlockReason (const FUniqueNetIdPtr &PlayerId, EVoiceBlockReasons VoiceBlockReason)
Remove a filter reason for an id from this player's mutelist.
void ServerMutePlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &MuteId)
Tell the server to mute a given player.
void ServerUnmutePlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &UnmuteId)
Tell the server to unmute a given player.
void GameplayMutePlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &MuteId)
Server muting based on gameplay rules.
void GameplayUnmutePlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &UnmuteId)
Server unmuting based on gameplay rules.
void GameplayUnmuteAllPlayers (class APlayerController *OwningPC)
Server unmuting all players muted based on gameplay rules.
void ServerBlockPlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &BlockId)
Tell the server to block a given player.
void ServerUnblockPlayer (class APlayerController *OwningPC, const FUniqueNetIdRepl &UnblockId)
Tell the server to unblock a given player.
bool IsPlayerMuted (const class FUniqueNetId &PlayerId)
Is a given player currently muted.
Public Attributes
TUniqueNetIdMap< EVoiceBlockReasons > VoicePacketFilterMap
Map of player ids and a bitfield containing filter reasons.
bool bHasVoiceHandshakeCompleted
Has server and client handshake completed.
int32 VoiceChannelIdx
Detailed Description
Container responsible for managing the mute state of a player controller at the gameplay level (VoiceInterface handles actual muting)
Definition at line 28 of file PlayerMuteList.h.
Constructor & Destructor Documentation
FPlayerMuteList()
FPlayerMuteList::FPlayerMuteList () inline
Definition at line 35 of file PlayerMuteList.h.
References bHasVoiceHandshakeCompleted, and VoiceChannelIdx.
Member Function Documentation
AddVoiceBlockReason()
bool FPlayerMuteList::AddVoiceBlockReason (const FUniqueNetIdPtr & PlayerId, EVoiceBlockReasons VoiceBlockReason)
Add a filter reason for an id to this player's mutelist.
Parameters
OwningPC player id to add a filter reason
VoiceBlockReason reason to add
Returns
true if it's the first reason to block voice from user
References AddVoiceBlockReason(), and EVoiceBlockReasons.
GameplayMutePlayer()
void FPlayerMuteList::GameplayMutePlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & MuteId)
Server muting based on gameplay rules.
Parameters
OwningPC player controller that would like to mute another player
MuteId player id that should be muted
References GameplayMutePlayer().
GameplayUnmuteAllPlayers()
void FPlayerMuteList::GameplayUnmuteAllPlayers (class APlayerController * OwningPC)
Server unmuting all players muted based on gameplay rules.
Parameters
OwningPC player controller that would like to unmute all players
References GameplayUnmuteAllPlayers().
GameplayUnmutePlayer()
void FPlayerMuteList::GameplayUnmutePlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & UnmuteId)
Server unmuting based on gameplay rules.
Parameters
OwningPC player controller that would like to unmute another player
UnmuteId player id that should be unmuted
References GameplayUnmutePlayer().
IsPlayerMuted()
bool FPlayerMuteList::IsPlayerMuted (const class FUniqueNetId & PlayerId)
Is a given player currently muted.
Parameters
PlayerId player to query mute state
Returns
true if the playerid is muted, false otherwise
References IsPlayerMuted().
RemoveVoiceBlockReason()
bool FPlayerMuteList::RemoveVoiceBlockReason (const FUniqueNetIdPtr & PlayerId, EVoiceBlockReasons VoiceBlockReason)
Remove a filter reason for an id from this player's mutelist.
Parameters
UniqueIdToRemove player id to remove a filter reason
VoiceBlockReason reason to remove
Returns
true if it's the last reason blocking voice from user
References EVoiceBlockReasons, and RemoveVoiceBlockReason().
ServerBlockPlayer()
void FPlayerMuteList::ServerBlockPlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & BlockId)
Tell the server to block a given player.
Parameters
OwningPC player controller that would like to block another player
BlockerId player id that should be blocked
References ServerBlockPlayer().
ServerMutePlayer()
void FPlayerMuteList::ServerMutePlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & MuteId)
Tell the server to mute a given player.
Parameters
OwningPC player controller that would like to mute another player
MuteId player id that should be muted
References ServerMutePlayer().
ServerUnblockPlayer()
void FPlayerMuteList::ServerUnblockPlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & UnblockId)
Tell the server to unblock a given player.
Parameters
UnblockedPC player controller that would like to unblock another player
BlockerId player id that should be unblocked
References ServerUnblockPlayer().
ServerUnmutePlayer()
void FPlayerMuteList::ServerUnmutePlayer (class APlayerController * OwningPC, const FUniqueNetIdRepl & UnmuteId)
Tell the server to unmute a given player.
Parameters
OwningPC player controller that would like to unmute another player
UnmuteId player id that should be unmuted
References ServerUnmutePlayer().
Member Data Documentation
bHasVoiceHandshakeCompleted
bool FPlayerMuteList::bHasVoiceHandshakeCompleted
Has server and client handshake completed.
Definition at line 46 of file PlayerMuteList.h.
VoiceChannelIdx
int32 FPlayerMuteList::VoiceChannelIdx
Definition at line 48 of file PlayerMuteList.h.
VoicePacketFilterMap
TUniqueNetIdMap<EVoiceBlockReasons> FPlayerMuteList::VoicePacketFilterMap
Map of player ids and a bitfield containing filter reasons.
Non-zero entries imply communication is blocked for that player
Definition at line 42 of file PlayerMuteList.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerMuteList.h