Unreal Engine 5.6 C++ Documentation: FInputActionSpeechMapping Struct Reference
FInputActionSpeechMapping Struct Reference
Defines a mapping between an action and speech recognition.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerInput.h>
Public Member Functions
FName GetActionName () const
FName GetSpeechKeyword () const
FName GetKeyName () const
bool operator== (const FInputActionSpeechMapping &Other) const
bool operator< (const FInputActionSpeechMapping &Other) const
FInputActionSpeechMapping (const FName InActionName=NAME_None, const FName InSpeechKeyword=NAME_None)
Static Public Member Functions
static FName GetKeyCategory ()
Detailed Description
Defines a mapping between an action and speech recognition.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Input/index.html
Definition at line 273 of file PlayerInput.h.
Constructor & Destructor Documentation
FInputActionSpeechMapping()
FInputActionSpeechMapping::FInputActionSpeechMapping (const FName InActionName = NAME_None, const FName InSpeechKeyword = NAME_None) inline
Definition at line 324 of file PlayerInput.h.
Member Function Documentation
GetActionName()
FName FInputActionSpeechMapping::GetActionName () const inline
Definition at line 282 of file PlayerInput.h.
GetKeyCategory()
FName FInputActionSpeechMapping::GetKeyCategory () inline static
Definition at line 278 of file PlayerInput.h.
References GetKeyCategory().
GetKeyName()
FName FInputActionSpeechMapping::GetKeyName () const inline
Definition at line 290 of file PlayerInput.h.
References GetKeyCategory().
GetSpeechKeyword()
FName FInputActionSpeechMapping::GetSpeechKeyword () const inline
Definition at line 286 of file PlayerInput.h.
operator<()
bool FInputActionSpeechMapping::operator< (const FInputActionSpeechMapping & Other) const inline
Definition at line 310 of file PlayerInput.h.
References FInputActionSpeechMapping().
operator==()
bool FInputActionSpeechMapping::operator== (const FInputActionSpeechMapping & Other) const inline
Definition at line 304 of file PlayerInput.h.
References FInputActionSpeechMapping().
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerInput.h