Unreal Engine 5.6 C++ Documentation: FInputModeGameAndUI Struct Reference
FInputModeGameAndUI Struct Reference
Data structure used to setup an input mode that allows the UI to respond to user input, and if the UI doesn't handle it player input / player controller gets a chance.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.h>
Public Member Functions
FInputModeGameAndUI ()
virtual ~FInputModeGameAndUI ()
FInputModeGameAndUI & SetWidgetToFocus (TSharedPtr< SWidget > InWidgetToFocus)
Widget to focus.
FInputModeGameAndUI & SetLockMouseToViewportBehavior (EMouseLockMode InMouseLockMode)
Sets the mouse locking behavior of the viewport.
FInputModeGameAndUI & SetHideCursorDuringCapture (bool InHideCursorDuringCapture)
Whether to hide the cursor during temporary mouse capture caused by a mouse down.
virtual bool ShouldFlushInputOnViewportFocus () const override
Protected Member Functions
virtual void ApplyInputMode (FReply &SlateOperations, class UGameViewportClient &GameViewportClient) const override
Derived classes override this function to apply the necessary settings for the desired input mode.
void SetFocusAndLocking (FReply &SlateOperations, TSharedPtr< class SWidget > InWidgetToFocus, bool bLockMouseToViewport, TSharedRef< class SViewport > InViewportWidget) const
Utility functions for derived classes.
Protected Attributes
TSharedPtr< SWidget > WidgetToFocus
EMouseLockMode MouseLockMode
bool bHideCursorDuringCapture
Detailed Description
Data structure used to setup an input mode that allows the UI to respond to user input, and if the UI doesn't handle it player input / player controller gets a chance.
Definition at line 179 of file PlayerController.h.
Constructor & Destructor Documentation
FInputModeGameAndUI()
FInputModeGameAndUI::FInputModeGameAndUI ()
~FInputModeGameAndUI()
virtual FInputModeGameAndUI::~FInputModeGameAndUI () virtual
Member Function Documentation
ApplyInputMode()
virtual void FInputModeGameAndUI::ApplyInputMode (FReply & SlateOperations, class UGameViewportClient & GameViewportClient) const override protected virtual
Derived classes override this function to apply the necessary settings for the desired input mode.
Implements FInputModeDataBase.
SetFocusAndLocking()
void FInputModeDataBase::SetFocusAndLocking (FReply & SlateOperations, TSharedPtr< class SWidget > InWidgetToFocus, bool bLockMouseToViewport, TSharedRef< class SViewport > InViewportWidget) const protected inherited
Utility functions for derived classes.
SetHideCursorDuringCapture()
FInputModeGameAndUI & FInputModeGameAndUI::SetHideCursorDuringCapture (bool InHideCursorDuringCapture) inline
Whether to hide the cursor during temporary mouse capture caused by a mouse down.
Definition at line 192 of file PlayerController.h.
References bHideCursorDuringCapture, and FInputModeGameAndUI().
SetLockMouseToViewportBehavior()
FInputModeGameAndUI & FInputModeGameAndUI::SetLockMouseToViewportBehavior (EMouseLockMode InMouseLockMode) inline
Sets the mouse locking behavior of the viewport.
Definition at line 189 of file PlayerController.h.
References FInputModeGameAndUI(), and MouseLockMode.
SetWidgetToFocus()
FInputModeGameAndUI & FInputModeGameAndUI::SetWidgetToFocus (TSharedPtr< SWidget > InWidgetToFocus) inline
Widget to focus.
Definition at line 186 of file PlayerController.h.
References FInputModeGameAndUI(), and WidgetToFocus.
ShouldFlushInputOnViewportFocus()
virtual bool FInputModeGameAndUI::ShouldFlushInputOnViewportFocus () const inline override virtual
Reimplemented from FInputModeDataBase.
Definition at line 194 of file PlayerController.h.
Member Data Documentation
bHideCursorDuringCapture
bool FInputModeGameAndUI::bHideCursorDuringCapture protected
Definition at line 204 of file PlayerController.h.
MouseLockMode
EMouseLockMode FInputModeGameAndUI::MouseLockMode protected
Definition at line 203 of file PlayerController.h.
WidgetToFocus
TSharedPtr<SWidget> FInputModeGameAndUI::WidgetToFocus protected
Definition at line 202 of file PlayerController.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.h