Unreal Engine 5.6 C++ Documentation: FRootMotionSourceStatus Struct Reference
FRootMotionSourceStatus Struct Reference
Structure for RootMotionSource status flags (used for convenience instead of having to manually manipulate flag bitfields)
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h>
Public Member Functions
FRootMotionSourceStatus ()
void Clear ()
void SetFlag (ERootMotionSourceStatusFlags Flag)
void UnSetFlag (ERootMotionSourceStatusFlags Flag)
bool HasFlag (ERootMotionSourceStatusFlags Flag) const
Public Attributes
uint8 Flags
Detailed Description
Structure for RootMotionSource status flags (used for convenience instead of having to manually manipulate flag bitfields)
Definition at line 98 of file RootMotionSource.h.
Constructor & Destructor Documentation
FRootMotionSourceStatus()
FRootMotionSourceStatus::FRootMotionSourceStatus ()
References FRootMotionSourceStatus().
Member Function Documentation
Clear()
void FRootMotionSourceStatus::Clear ()
References Clear().
HasFlag()
bool FRootMotionSourceStatus::HasFlag (ERootMotionSourceStatusFlags Flag) const
References ERootMotionSourceStatusFlags, and HasFlag().
SetFlag()
void FRootMotionSourceStatus::SetFlag (ERootMotionSourceStatusFlags Flag)
References ERootMotionSourceStatusFlags, and SetFlag().
UnSetFlag()
void FRootMotionSourceStatus::UnSetFlag (ERootMotionSourceStatusFlags Flag)
References ERootMotionSourceStatusFlags, and UnSetFlag().
Member Data Documentation
Flags
uint8 FRootMotionSourceStatus::Flags
Definition at line 104 of file RootMotionSource.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h