Unreal Engine 5.6 C++ Documentation: FUniqueNetIdRepl Struct Reference
FUniqueNetIdRepl Struct Reference
Wrapper for opaque type FUniqueNetId.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/OnlineReplStructs.h>
Public Member Functions
FUniqueNetIdRepl ()
FUniqueNetIdRepl (TYPE_OF_NULLPTR)
FUniqueNetIdRepl (const FUniqueNetIdRepl &InWrapper)
FUniqueNetIdRepl (const FUniqueNetIdWrapper &InWrapper)
FUniqueNetIdRepl (const FUniqueNetIdRef &InUniqueNetId)
FUniqueNetIdRepl (const FUniqueNetIdPtr &InUniqueNetId)
FUniqueNetIdRepl (const FUniqueNetId &InUniqueNetId)
virtual ~FUniqueNetIdRepl ()
virtual void SetUniqueNetId (const FUniqueNetIdPtr &UniqueNetId) override
virtual void SetAccountId (const UE::Online::FAccountId &AccountId) override
bool ExportTextItem (FString &ValueStr, FUniqueNetIdRepl const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
Export contents of this struct as a string.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
Import string contexts and try to map them into a unique id.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
Network serialization.
void NetSerializeLoadV1Encoded (FArchive &Ar, const EUniqueIdEncodingFlags EncodingFlags, bool &bOutSuccess)
void NetSerializeLoadV1Unencoded (FArchive &Ar, const EUniqueIdEncodingFlags EncodingFlags, bool &bOutSuccess)
void NetSerializeLoadV2 (FArchive &Ar, const EUniqueIdEncodingFlags EncodingFlags, bool &bOutSuccess)
bool Serialize (FArchive &Ar)
Serialization to any FArchive.
TSharedRef< FJsonValue > ToJson () const
Convert this unique id to a json value.
void FromJson (const FString &InValue)
Create a unique id from a json string.
Protected Member Functions
void UniqueIdFromString (FName Type, const FString &Contents)
Helper to create an FUniqueNetId from a string and its type.
void MakeReplicationData ()
Helper to make network serializable representation.
void MakeReplicationDataV1 ()
void MakeReplicationDataV2 ()
Static Protected Member Functions
static bool ShouldExportTextItemAsQuotedString (const FString &NetIdStr)
Protected Attributes
TArray< uint8 > ReplicationBytes
Network serialized data cache.
Friends
FArchive & operator<< (FArchive &Ar, FUniqueNetIdRepl &UniqueNetId)
Serialization to any FArchive.
uint32 GetTypeHash (FUniqueNetIdRepl const &Value)
For FUniqueNetIdRepl objects, we use the same hashing function as any other wrapper.
Detailed Description
Wrapper for opaque type FUniqueNetId.
Makes sure that the opaque aspects of FUniqueNetId are properly handled/serialized over network RPC and actor replication
Definition at line 24 of file OnlineReplStructs.h.
Constructor & Destructor Documentation
FUniqueNetIdRepl() [1/7]
FUniqueNetIdRepl::FUniqueNetIdRepl () inline
Definition at line 29 of file OnlineReplStructs.h.
References FUniqueNetIdRepl().
FUniqueNetIdRepl() [2/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (TYPE_OF_NULLPTR) inline
Definition at line 33 of file OnlineReplStructs.h.
FUniqueNetIdRepl() [3/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (const FUniqueNetIdRepl & InWrapper) inline
Definition at line 37 of file OnlineReplStructs.h.
References FUniqueNetIdRepl().
FUniqueNetIdRepl() [4/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (const FUniqueNetIdWrapper & InWrapper) inline
Definition at line 42 of file OnlineReplStructs.h.
FUniqueNetIdRepl() [5/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (const FUniqueNetIdRef & InUniqueNetId) inline
Definition at line 47 of file OnlineReplStructs.h.
FUniqueNetIdRepl() [6/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (const FUniqueNetIdPtr & InUniqueNetId) inline
Definition at line 52 of file OnlineReplStructs.h.
FUniqueNetIdRepl() [7/7]
FUniqueNetIdRepl::FUniqueNetIdRepl (const FUniqueNetId & InUniqueNetId) inline
Definition at line 57 of file OnlineReplStructs.h.
~FUniqueNetIdRepl()
virtual FUniqueNetIdRepl::~FUniqueNetIdRepl () inline virtual
Definition at line 62 of file OnlineReplStructs.h.
Member Function Documentation
ExportTextItem()
bool FUniqueNetIdRepl::ExportTextItem (FString & ValueStr, FUniqueNetIdRepl const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
Export contents of this struct as a string.
References FUniqueNetIdRepl().
FromJson()
void FUniqueNetIdRepl::FromJson (const FString & InValue)
Create a unique id from a json string.
ImportTextItem()
bool FUniqueNetIdRepl::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
Import string contexts and try to map them into a unique id.
MakeReplicationData()
void FUniqueNetIdRepl::MakeReplicationData () protected
Helper to make network serializable representation.
MakeReplicationDataV1()
void FUniqueNetIdRepl::MakeReplicationDataV1 () protected
MakeReplicationDataV2()
void FUniqueNetIdRepl::MakeReplicationDataV2 () protected
NetSerialize()
bool FUniqueNetIdRepl::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess)
Network serialization.
NetSerializeLoadV1Encoded()
void FUniqueNetIdRepl::NetSerializeLoadV1Encoded (FArchive & Ar, const EUniqueIdEncodingFlags EncodingFlags, bool & bOutSuccess)
NetSerializeLoadV1Unencoded()
void FUniqueNetIdRepl::NetSerializeLoadV1Unencoded (FArchive & Ar, const EUniqueIdEncodingFlags EncodingFlags, bool & bOutSuccess)
NetSerializeLoadV2()
void FUniqueNetIdRepl::NetSerializeLoadV2 (FArchive & Ar, const EUniqueIdEncodingFlags EncodingFlags, bool & bOutSuccess)
Serialize()
bool FUniqueNetIdRepl::Serialize (FArchive & Ar)
Serialization to any FArchive.
SetAccountId()
virtual void FUniqueNetIdRepl::SetAccountId (const UE::Online::FAccountId & AccountId) inline override virtual
Definition at line 70 of file OnlineReplStructs.h.
References ReplicationBytes.
SetUniqueNetId()
virtual void FUniqueNetIdRepl::SetUniqueNetId (const FUniqueNetIdPtr & UniqueNetId) inline override virtual
Definition at line 64 of file OnlineReplStructs.h.
References ReplicationBytes.
ShouldExportTextItemAsQuotedString()
bool FUniqueNetIdRepl::ShouldExportTextItemAsQuotedString (const FString & NetIdStr) static protected
References ShouldExportTextItemAsQuotedString().
ToJson()
TSharedRef< FJsonValue > FUniqueNetIdRepl::ToJson () const
Convert this unique id to a json value.
UniqueIdFromString()
void FUniqueNetIdRepl::UniqueIdFromString (FName Type, const FString & Contents) protected
Helper to create an FUniqueNetId from a string and its type.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FUniqueNetIdRepl const & Value) friend
For FUniqueNetIdRepl objects, we use the same hashing function as any other wrapper.
Definition at line 103 of file OnlineReplStructs.h.
References FUniqueNetIdRepl(), and GetTypeHash.
operator<<
FArchive & operator<< (FArchive & Ar, FUniqueNetIdRepl & UniqueNetId) friend
Serialization to any FArchive.
References FUniqueNetIdRepl().
Member Data Documentation
ReplicationBytes
TArray<uint8> FUniqueNetIdRepl::ReplicationBytes protected
Network serialized data cache.
Definition at line 126 of file OnlineReplStructs.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/OnlineReplStructs.h