Unreal Engine 5.6 C++ Documentation: FCharacterMovementComponentPostPhysicsTickFunction Struct Reference
FCharacterMovementComponentPostPhysicsTickFunction Struct Reference
Tick function that calls UCharacterMovementComponent::PostPhysicsTickComponent.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h>
Public Member Functions
virtual void ExecuteTick (float DeltaTime, enum ELevelTick TickType, ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent) override
Abstract function actually execute the tick.
virtual FString DiagnosticMessage () override
Abstract function to describe this tick.
virtual FName DiagnosticContext (bool bDetailed) override
Function used to describe this tick for active tick reporting.
Public Attributes
class UCharacterMovementComponent * Target
CharacterMovementComponent that is the target of this tick.
Detailed Description
Tick function that calls UCharacterMovementComponent::PostPhysicsTickComponent.
Definition at line 51 of file CharacterMovementComponent.h.
Member Function Documentation
DiagnosticContext()
virtual FName FCharacterMovementComponentPostPhysicsTickFunction::DiagnosticContext (bool bDetailed) override virtual
Function used to describe this tick for active tick reporting.
References DiagnosticContext().
DiagnosticMessage()
virtual FString FCharacterMovementComponentPostPhysicsTickFunction::DiagnosticMessage () override virtual
Abstract function to describe this tick.
Used to print messages about illegal cycles in the dependency graph
References DiagnosticMessage().
ExecuteTick()
virtual void FCharacterMovementComponentPostPhysicsTickFunction::ExecuteTick (float DeltaTime, enum ELevelTick TickType, ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) override virtual
Abstract function actually execute the tick.
Parameters
DeltaTime - frame time to advance, in seconds
TickType - kind of tick for this frame
CurrentThread - thread we are executing on, useful to pass along as new tasks are created
MyCompletionGraphEvent - completion event for this task. Useful for holding the completion of this task until certain child tasks are complete.
References ExecuteTick().
Member Data Documentation
Target
class UCharacterMovementComponent* FCharacterMovementComponentPostPhysicsTickFunction::Target
CharacterMovementComponent that is the target of this tick.
Definition at line 57 of file CharacterMovementComponent.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h