Unreal Engine 5.6 C++ Documentation: UAsyncActionHandleSaveGame Class Reference
UAsyncActionHandleSaveGame Class Reference
Async action to handle async load/save of a USaveGame.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/AsyncActionHandleSaveGame.h>
Public Member Functions
virtual void Activate () override
Execute the actual operation.
Static Public Member Functions
static UAsyncActionHandleSaveGame * AsyncSaveGameToSlot (UObject *WorldContextObject, USaveGame *SaveGameObject, const FString &SlotName, const int32 UserIndex)
Schedule an async save to a specific slot.
static UAsyncActionHandleSaveGame * AsyncLoadGameFromSlot (UObject *WorldContextObject, const FString &SlotName, const int32 UserIndex)
Schedule an async load of a specific slot.
Public Attributes
FOnAsyncHandleSaveGame Completed
Delegate called when the save/load completes.
Protected Types
enum class ESaveGameOperation : uint8 { Save , Load }
Protected Member Functions
virtual void HandleAsyncSave (const FString &SlotName, const int32 UserIndex, bool bSuccess)
Function callbacks for load/save.
virtual void HandleAsyncLoad (const FString &SlotName, const int32 UserIndex, USaveGame *LoadedSave)
virtual void ExecuteCompleted (bool bSuccess)
Called at completion of save/load to execute delegate.
Protected Attributes
ESaveGameOperation Operation
Which operation is being run.
FString SlotName
Slot/user to use.
int32 UserIndex
TObjectPtr< USaveGame > SaveGameObject
The object that was either saved or loaded.
Detailed Description
Async action to handle async load/save of a USaveGame.
This can be subclassed by a specific game
Definition at line 16 of file AsyncActionHandleSaveGame.h.
Member Enumeration Documentation
ESaveGameOperation
enum class UAsyncActionHandleSaveGame::ESaveGameOperation : uint8 strong protected
Enumerator
Save
Load
Definition at line 53 of file AsyncActionHandleSaveGame.h.
Member Function Documentation
Activate()
virtual void UAsyncActionHandleSaveGame::Activate () override virtual
Execute the actual operation.
References Activate().
AsyncLoadGameFromSlot()
UAsyncActionHandleSaveGame * UAsyncActionHandleSaveGame::AsyncLoadGameFromSlot (UObject * WorldContextObject, const FString & SlotName, const int32 UserIndex) static
Schedule an async load of a specific slot.
UGameplayStatics::AsyncLoadGameFromSlot is the native version of this. When the load has succeeded or failed, the completed pin is activated with success/failure and the newly loaded save game object if valid. Keep in mind that some platforms may not support trying to load and save at the same time.
Parameters
SlotName Name of the save game slot to load from.
UserIndex The platform user index that identifies the user doing the saving, ignored on some platforms.
References AsyncLoadGameFromSlot(), SlotName, and UserIndex.
AsyncSaveGameToSlot()
UAsyncActionHandleSaveGame * UAsyncActionHandleSaveGame::AsyncSaveGameToSlot (UObject * WorldContextObject, USaveGame * SaveGameObject, const FString & SlotName, const int32 UserIndex) static
Schedule an async save to a specific slot.
UGameplayStatics::AsyncSaveGameToSlot is the native version of this. When the save has succeeded or failed, the completed pin is activated with success/failure and the save game object. Keep in mind that some platforms may not support trying to load and save at the same time.
Parameters
SaveGameObject Object that contains data about the save game that we want to write out.
SlotName Name of the save game slot to load from.
UserIndex The platform user index that identifies the user doing the saving, ignored on some platforms.
References AsyncSaveGameToSlot(), SaveGameObject, SlotName, and UserIndex.
ExecuteCompleted()
virtual void UAsyncActionHandleSaveGame::ExecuteCompleted (bool bSuccess) protected virtual
Called at completion of save/load to execute delegate.
References ExecuteCompleted().
HandleAsyncLoad()
virtual void UAsyncActionHandleSaveGame::HandleAsyncLoad (const FString & SlotName, const int32 UserIndex, USaveGame * LoadedSave) protected virtual
References HandleAsyncLoad(), SlotName, and UserIndex.
HandleAsyncSave()
virtual void UAsyncActionHandleSaveGame::HandleAsyncSave (const FString & SlotName, const int32 UserIndex, bool bSuccess) protected virtual
Function callbacks for load/save.
References HandleAsyncSave(), SlotName, and UserIndex.
Member Data Documentation
Completed
FOnAsyncHandleSaveGame UAsyncActionHandleSaveGame::Completed
Delegate called when the save/load completes.
Definition at line 47 of file AsyncActionHandleSaveGame.h.
Operation
ESaveGameOperation UAsyncActionHandleSaveGame::Operation protected
Which operation is being run.
Definition at line 60 of file AsyncActionHandleSaveGame.h.
SaveGameObject
TObjectPtr<USaveGame> UAsyncActionHandleSaveGame::SaveGameObject protected
The object that was either saved or loaded.
Definition at line 68 of file AsyncActionHandleSaveGame.h.
SlotName
FString UAsyncActionHandleSaveGame::SlotName protected
Slot/user to use.
Definition at line 63 of file AsyncActionHandleSaveGame.h.
UserIndex
int32 UAsyncActionHandleSaveGame::UserIndex protected
Definition at line 64 of file AsyncActionHandleSaveGame.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/AsyncActionHandleSaveGame.h