Unreal Engine 5.6 C++ Documentation: UCharacterMovementComponent Class Reference
UCharacterMovementComponent Class Reference
CharacterMovementComponent handles movement logic for the associated Character owner.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h>
Public Types
enum class ERootMotionMapping : uint32 { MapSize = 16 }
Collection of the most recent ID mappings.
Public Member Functions
UCharacterMovementComponent (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
Default UObject constructor.
FVector GetLastUpdateLocation () const
Returns the location at the end of the last tick.
FRotator GetLastUpdateRotation () const
Returns the rotation at the end of the last tick.
FQuat GetLastUpdateQuat () const
Returns the rotation Quat at the end of the last tick.
FVector GetLastUpdateVelocity () const
Returns the velocity at the end of the last tick.
float GetServerLastTransformUpdateTimeStamp () const
Get the value of ServerLastTransformUpdateTimeStamp.
float GetSimulationTimeStep (float RemainingTime, int32 Iterations) const
Compute remaining time step given remaining time and current iterations.
UPrimitiveComponent * GetLastServerMovementBase () const
Accessor to the Last Server Movement Base, only relevant during server update.
virtual bool ShouldCorrectRotation () const
Returns if the character rotation should be corrected on clients when sending a server move response correction.
FVector GetLastUpdateRequestedVelocity () const
Returns velocity requested by path following.
void SetAvoidanceGroup (int32 GroupFlags)
void SetAvoidanceGroupMask (const FNavAvoidanceMask &GroupMask)
void SetGroupsToAvoid (int32 GroupFlags)
void SetGroupsToAvoidMask (const FNavAvoidanceMask &GroupMask)
void SetGroupsToIgnore (int32 GroupFlags)
void SetGroupsToIgnoreMask (const FNavAvoidanceMask &GroupMask)
void SetAvoidanceEnabled (bool bEnable)
Change avoidance state and registers in RVO manager if needed.
ACharacter * GetCharacterOwner () const
Get the Character that owns UpdatedComponent.
virtual void SetMovementMode (EMovementMode NewMovementMode, uint8 NewCustomMode=0)
Change movement mode.
void SetGroundMovementMode (EMovementMode NewGroundMovementMode)
Set movement mode to use when returning to walking movement (either MOVE_Walking or MOVE_NavWalking).
EMovementMode GetGroundMovementMode () const
Get current GroundMovementMode value.
virtual uint8 PackNetworkMovementMode () const
virtual void UnpackNetworkMovementMode (const uint8 ReceivedMode, TEnumAsByte< EMovementMode > &OutMode, uint8 &OutCustomMode, TEnumAsByte< EMovementMode > &OutGroundMode) const
virtual void ApplyNetworkMovementMode (const uint8 ReceivedMode)
virtual void Serialize (FArchive &Archive) override
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
virtual void OnRegister () override
Overridden to update component properties that should be updated while being edited.
virtual void BeginDestroy () override
virtual void BeginPlay () override
virtual void PostLoad () override
virtual void Deactivate () override
virtual void RegisterComponentTickFunctions (bool bRegister) override
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift) override
virtual float GetMaxSpeed () const override
Returns maximum speed of component in current movement mode.
virtual void StopActiveMovement () override
Stops applying further movement (usually zeros acceleration).
virtual bool IsCrouching () const override
Returns true if currently crouching.
virtual bool IsFalling () const override
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
virtual bool IsMovingOnGround () const override
Returns true if currently moving on the ground (e.g.
virtual bool IsSwimming () const override
Returns true if currently swimming (moving through a fluid volume)
virtual bool IsFlying () const override
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
virtual float GetGravityZ () const override
Returns gravity that affects this component.
virtual void AddRadialForce (const FVector &Origin, float Radius, float Strength, enum ERadialImpulseFalloff Falloff) override
Adds force from radial force components.
virtual void AddRadialImpulse (const FVector &Origin, float Radius, float Strength, enum ERadialImpulseFalloff Falloff, bool bVelChange) override
Adds impulse from radial force components.
bool IsWalking () const
Returns true if the character is in the 'Walking' movement mode.
bool IsMovementInProgress () const
Returns true if currently performing a movement update.
virtual FVector GetActorFeetLocation () const override
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
virtual void RequestDirectMove (const FVector &MoveVelocity, bool bForceMaxSpeed) override
path following: request new velocity
virtual void RequestPathMove (const FVector &MoveInput) override
path following: request new move input (normal vector = full strength)
virtual bool CanStartPathFollowing () const override
Returns true if path following can start.
virtual bool CanStopPathFollowing () const override
check if current move target can be reached right now if positions are matching (e.g.
virtual float GetPathFollowingBrakingDistance (float MaxSpeed) const override
Returns braking distance for acceleration driven path following.
virtual void NotifyBumpedPawn (APawn *BumpedPawn) override
Notify of collision in case we want to react, such as waking up avoidance or pathing code.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void DisableMovement ()
Make movement impossible (sets movement mode to MOVE_None).
virtual bool HasValidData () const
Return true if we have a valid CharacterOwner and UpdatedComponent.
virtual void PerformAirControlForPathFollowing (FVector Direction, float ZDiff)
If ShouldPerformAirControlForPathFollowing() returns true, it will update Velocity and Acceleration to air control in the desired Direction for character using path following.
virtual bool ShouldPerformAirControlForPathFollowing () const
Whether Character should perform air control via PerformAirControlForPathFollowing when falling and following a path at the same time Default implementation always returns true during MOVE_Falling.
virtual void StartFalling (int32 Iterations, float remainingTime, float timeTick, const FVector &Delta, const FVector &subLoc)
Transition from walking to falling.
virtual bool ShouldCatchAir (const FFindFloorResult &OldFloor, const FFindFloorResult &NewFloor)
Whether Character should go into falling mode when walking and changing position, based on an old and new floor result (both of which are considered walkable).
virtual void HandleWalkingOffLedge (const FVector &PreviousFloorImpactNormal, const FVector &PreviousFloorContactNormal, const FVector &PreviousLocation, float TimeDelta)
Trigger OnWalkingOffLedge event on CharacterOwner.
virtual void AdjustFloorHeight ()
Adjust distance from floor, trying to maintain a slight offset from the floor when walking (based on CurrentFloor).
UPrimitiveComponent * GetMovementBase () const
Return PrimitiveComponent we are based on (standing and walking on).
virtual void MaybeUpdateBasedMovement (float DeltaSeconds)
Update or defer updating of position based on Base movement.
virtual void UpdateBasedMovement (float DeltaSeconds)
Update position based on Base movement.
virtual void UpdateBasedRotation (FRotator &FinalRotation, const FRotator &ReducedRotation)
Update controller's view rotation as pawn's base rotates.
virtual void MaybeSaveBaseLocation ()
Call SaveBaseLocation() if not deferring updates (bDeferUpdateBasedMovement is false).
virtual void SaveBaseLocation ()
Update OldBaseLocation and OldBaseQuat if there is a valid movement base, and store the relative location/rotation if necessary.
virtual void ApplyImpartedMovementBaseVelocity ()
Apply inherited velocity when leaving base, for example from jumping off it.
virtual void StartNewPhysics (float deltaTime, int32 Iterations)
changes physics based on MovementMode
virtual bool DoJump (bool bReplayingMoves)
NOTE: THIS FUNCTION IS DEPRECATED, PLEASE CALL DoJump(bool bReplayingMoves, float DeltaTime) ...
virtual bool DoJump (bool bReplayingMoves, float DeltaTime)
Perform jump.
virtual bool CanAttemptJump () const
Returns true if current movement state allows an attempt at jumping.
virtual void Launch (FVector const &LaunchVel)
Queue a pending launch with velocity LaunchVel.
virtual bool HandlePendingLaunch ()
Handle a pending launch during an update.
virtual FVector GetImpartedMovementBaseVelocity () const
If we have a movement base, get the velocity that should be imparted by that base, usually when jumping off of it.
virtual void JumpOff (AActor *MovementBaseActor)
Force this pawn to bounce off its current base, which isn't an acceptable base for it.
virtual FVector GetBestDirectionOffActor (AActor *BaseActor) const
Can be overridden to choose to jump based on character velocity, base actor dimensions, etc.
virtual bool ShouldJumpOutOfWater (FVector &JumpDir)
Determine whether the Character should jump when exiting water.
virtual void JumpOutOfWater (FVector WallNormal)
Jump onto shore from water.
virtual FRotator GetDeltaRotation (float DeltaTime) const
Returns how far to rotate character during the time interval DeltaTime.
virtual FRotator ComputeOrientToMovementRotation (const FRotator &CurrentRotation, float DeltaTime, FRotator &DeltaRotation) const
Compute a target rotation based on current movement.
virtual bool ApplyRequestedMove (float DeltaTime, float MaxAccel, float MaxSpeed, float Friction, float BrakingDeceleration, FVector &OutAcceleration, float &OutRequestedSpeed)
Use velocity requested by path following to compute a requested acceleration and speed.
virtual void NotifyJumpApex ()
Called if bNotifyApex is true and character has just passed the apex of its jump.
virtual FVector NewFallVelocity (const FVector &InitialVelocity, const FVector &Gravity, float DeltaTime) const
Compute new falling velocity from given velocity and gravity.
virtual float ImmersionDepth () const
virtual void CalcVelocity (float DeltaTime, float Friction, bool bFluid, float BrakingDeceleration)
Updates Velocity and Acceleration based on the current state, applying the effects of friction and acceleration or deceleration.
virtual float GetMaxJumpHeight () const
Compute the max jump height based on the JumpZVelocity velocity and gravity.
virtual float GetMaxJumpHeightWithJumpTime () const
Compute the max jump height based on the JumpZVelocity velocity and gravity.
virtual float GetMinAnalogSpeed () const
Returns maximum acceleration for the current state.
virtual float GetMaxAcceleration () const
Returns maximum acceleration for the current state.
virtual float GetMaxBrakingDeceleration () const
Returns maximum deceleration for the current state when braking (ie when there is no acceleration).
FVector GetCurrentAcceleration () const
Returns current acceleration, computed from input vector each update.
float GetAnalogInputModifier () const
Returns modifier [0..1] based on the magnitude of the last input vector, which is used to modify the acceleration and max speed during movement.
virtual bool CanStepUp (const FHitResult &Hit) const
Returns true if we can step up on the actor in the given FHitResult.
virtual bool StepUp (const FVector &GravDir, const FVector &Delta, const FHitResult &Hit, FStepDownResult *OutStepDownResult=NULL)
Move up steps or slope.
virtual void SetBase (UPrimitiveComponent *NewBase, const FName BoneName=NAME_None, bool bNotifyActor=true)
Update the base of the character, which is the PrimitiveComponent we are standing on.
void SetBaseFromFloor (const FFindFloorResult &FloorResult)
Update the base of the character, using the given floor result if it is walkable, or null if not.
virtual void ApplyDownwardForce (float DeltaSeconds)
Applies downward force when walking on top of physics objects.
virtual void ApplyRepulsionForce (float DeltaSeconds)
Applies repulsion force to all touched components.
virtual void ApplyAccumulatedForces (float DeltaSeconds)
Applies momentum accumulated through AddImpulse() and AddForce(), then clears those forces.
virtual void ClearAccumulatedForces ()
Clears forces accumulated through AddImpulse() and AddForce(), and also pending launch velocity.
virtual void UpdateCharacterStateBeforeMovement (float DeltaSeconds)
Update the character state in PerformMovement right before doing the actual position change.
virtual void UpdateCharacterStateAfterMovement (float DeltaSeconds)
Update the character state in PerformMovement after the position change.
virtual void StartSwimming (FVector OldLocation, FVector OldVelocity, float timeTick, float remainingTime, int32 Iterations)
Handle start swimming functionality.
float Swim (FVector Delta, FHitResult &Hit)
FVector FindWaterLine (FVector Start, FVector End)
Get as close to waterline as possible, staying on same side as currently.
virtual void PhysFalling (float deltaTime, int32 Iterations)
Handle falling movement.
virtual FVector GetFallingLateralAcceleration (float DeltaTime)
Get the lateral acceleration to use during falling movement.
virtual bool ShouldLimitAirControl (float DeltaTime, const FVector &FallAcceleration) const
Returns true if falling movement should limit air control.
virtual FVector GetAirControl (float DeltaTime, float TickAirControl, const FVector &FallAcceleration)
Get the air control to use during falling movement.
virtual void SetGravityDirection (const FVector &GravityDir)
Set a custom, local gravity direction to use during movement simulation.
bool HasCustomGravity () const
Whether the gravity direction is different from UCharacterMovementComponent::DefaultGravityDirection.
FVector GetGravityDirection () const
Returns the current gravity direction.
FQuat GetWorldToGravityTransform () const
Returns a quaternion transforming from world to gravity space.
FQuat GetGravityToWorldTransform () const
Returns a quaternion transforming from gravity to world space.
FVector RotateGravityToWorld (const FVector &World) const
Rotate a vector from world to gravity space.
FVector RotateWorldToGravity (const FVector &Gravity) const
Rotate a vector from gravity to world space.
FVector ProjectToGravityFloor (const FVector &Vector) const
Project a vector onto the floor defined by the gravity direction.
FVector::FReal GetGravitySpaceZ (const FVector &Vector) const
Returns the size of a vector in the gravity-space vertical direction.
FVector GetGravitySpaceComponentZ (const FVector &Vector) const
Returns the component of the vector in the gravity-space vertical direction.
void SetGravitySpaceZ (FVector &Vector, const FVector::FReal Z) const
Set the vertical component of the vector to the given value in the gravity-space vertical direction.
virtual void OnTeleported () override
Called by owning Character upon successful teleport from AActor::TeleportTo().
virtual void Crouch (bool bClientSimulation=false)
Checks if new capsule size fits (no encroachment), and call CharacterOwner->OnStartCrouch() if successful.
virtual void UnCrouch (bool bClientSimulation=false)
Checks if default capsule size fits (no encroachment), and trigger OnEndCrouch() on the owner if successful.
virtual bool CanCrouchInCurrentState () const
Returns true if the character is allowed to crouch in the current state.
void SetCrouchedHalfHeight (const float NewValue)
Sets collision half-height when crouching and updates dependent computations.
float GetCrouchedHalfHeight () const
Returns the collision half-height when crouching (component scale is applied separately)
virtual bool CheckLedgeDirection (const FVector &OldLocation, const FVector &SideStep, const FFindFloorResult &OldFloor) const
Returns true if there is a suitable floor SideStep from current position.
virtual FVector GetLedgeMove (const FVector &OldLocation, const FVector &Delta, const FFindFloorResult &OldFloor) const
virtual bool CheckFall (const FFindFloorResult &OldFloor, const FHitResult &Hit, const FVector &Delta, const FVector &OldLocation, float remainingTime, float timeTick, int32 Iterations, bool bMustJump)
Check if pawn is falling.
void RevertMove (const FVector &OldLocation, UPrimitiveComponent *OldBase, const FVector &InOldBaseLocation, const FFindFloorResult &OldFloor, bool bFailMove)
Revert to previous position OldLocation, return to being based on OldBase.
virtual void PhysicsRotation (float DeltaTime)
Perform rotation over deltaTime.
virtual bool ShouldRemainVertical () const
if true, DesiredRotation will be restricted to only Yaw component in PhysicsRotation()
virtual void PhysicsVolumeChanged (class APhysicsVolume *NewVolume) override
Delegate when PhysicsVolume of UpdatedComponent has been changed.
virtual void SetDefaultMovementMode ()
Set movement mode to the default based on the current physics volume.
virtual void MoveSmooth (const FVector &InVelocity, const float DeltaSeconds, FStepDownResult *OutStepDownResult=NULL)
Moves along the given movement direction using simple movement rules based on the current movement mode (usually used by simulated proxies).
virtual void UpdateProxyAcceleration ()
Used during SimulateMovement for proxies, this computes a new value for Acceleration before running proxy simulation.
virtual void SetUpdatedComponent (USceneComponent *NewUpdatedComponent) override
Overridden to only allow registration with components owned by a Pawn.
virtual FString GetMovementName () const
Returns MovementMode string.
virtual void AddImpulse (FVector Impulse, bool bVelocityChange=false)
Add impulse to character.
virtual void AddForce (FVector Force)
Add force to character.
virtual void DisplayDebug (class UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos)
Draw important variables on canvas.
virtual float VisualizeMovement () const
Draw in-world debug information for character movement (called with p.VisualizeMovement > 0).
virtual bool CheckWaterJump (FVector CheckPoint, FVector &WallNormal)
Check if swimming pawn just ran into edge of the pool and should jump out.
virtual bool CanWalkOffLedges () const
Returns whether this pawn is currently allowed to walk off ledges.
float GetPerchRadiusThreshold () const
Returns The distance from the edge of the capsule within which we don't allow the character to perch on the edge of a surface.
float GetValidPerchRadius () const
Returns the radius within which we can stand on the edge of a surface without falling (if this is a walkable surface).
virtual bool IsWalkable (const FHitResult &Hit) const
Return true if the hit result should be considered a walkable surface for the character.
float GetWalkableFloorAngle () const
Get the max angle in degrees of a walkable surface for the character.
float K2_GetWalkableFloorAngle () const
Get the max angle in degrees of a walkable surface for the character.
void SetWalkableFloorAngle (float InWalkableFloorAngle)
Set the max angle in degrees of a walkable surface for the character.
float GetWalkableFloorZ () const
Get the Z component of the normal of the steepest walkable surface for the character.
float K2_GetWalkableFloorZ () const
Get the Z component of the normal of the steepest walkable surface for the character.
void SetWalkableFloorZ (float InWalkableFloorZ)
Set the Z component of the normal of the steepest walkable surface for the character.
virtual void PrePhysicsTickComponent (float DeltaTime, FCharacterMovementComponentPrePhysicsTickFunction &ThisTickFunction)
Tick function called before physics.
virtual void PostPhysicsTickComponent (float DeltaTime, FCharacterMovementComponentPostPhysicsTickFunction &ThisTickFunction)
Tick function called after physics (sync scene) has finished simulation, before cloth.
virtual bool IsWithinEdgeTolerance (const FVector &CapsuleLocation, const FVector &TestImpactPoint, const float CapsuleRadius) const
Return true if the 2D distance to the impact point is inside the edge tolerance (CapsuleRadius minus a small rejection threshold).
virtual void FindFloor (const FVector &CapsuleLocation, FFindFloorResult &OutFloorResult, bool bCanUseCachedLocation, const FHitResult *DownwardSweepResult=NULL) const
Sweeps a vertical trace to find the floor for the capsule at the given location.
virtual void K2_FindFloor (FVector CapsuleLocation, FFindFloorResult &FloorResult) const
Sweeps a vertical trace to find the floor for the capsule at the given location.
virtual void ComputeFloorDist (const FVector &CapsuleLocation, float LineDistance, float SweepDistance, FFindFloorResult &OutFloorResult, float SweepRadius, const FHitResult *DownwardSweepResult=NULL) const
Compute distance to the floor from bottom sphere of capsule and store the result in OutFloorResult.
virtual void K2_ComputeFloorDist (FVector CapsuleLocation, float LineDistance, float SweepDistance, float SweepRadius, FFindFloorResult &FloorResult) const
Compute distance to the floor from bottom sphere of capsule and store the result in FloorResult.
virtual bool FloorSweepTest (struct FHitResult &OutHit, const FVector &Start, const FVector &End, ECollisionChannel TraceChannel, const struct FCollisionShape &CollisionShape, const struct FCollisionQueryParams &Params, const struct FCollisionResponseParams &ResponseParam) const
Sweep against the world and return the first blocking hit.
virtual bool IsValidLandingSpot (const FVector &CapsuleLocation, const FHitResult &Hit) const
Verify that the supplied hit result is a valid landing spot when falling.
virtual bool ShouldCheckForValidLandingSpot (float DeltaTime, const FVector &Delta, const FHitResult &Hit) const
Determine whether we should try to find a valid landing spot after an impact with an invalid one (based on the Hit result).
virtual bool ShouldComputePerchResult (const FHitResult &InHit, bool bCheckRadius=true) const
Check if the result of a sweep test (passed in InHit) might be a valid location to perch, in which case we should use ComputePerchResult to validate the location.
virtual bool ComputePerchResult (const float TestRadius, const FHitResult &InHit, const float InMaxFloorDist, FFindFloorResult &OutPerchFloorResult) const
Compute the sweep result of the smaller capsule with radius specified by GetValidPerchRadius(), and return true if the sweep contacts a valid walkable normal within InMaxFloorDist of InHit.ImpactPoint.
virtual bool FindNavFloor (const FVector &TestLocation, FNavLocation &NavFloorLocation) const
Project a location to navmesh to find adjusted height.
virtual void ForceReplicationUpdate ()
Force a client update by making it appear on the server that the client hasn't updated in a long time.
void ForceClientAdjustment ()
Force a client adjustment.
virtual float GetNetworkSafeRandomAngleDegrees () const
Generate a random angle in degrees that is approximately equal between client and server.
virtual FVector RoundAcceleration (FVector InAccel) const
Round acceleration, for better consistency and lower bandwidth in networked games.
virtual void SendClientAdjustment () override
virtual bool ForcePositionUpdate (float DeltaTime) override
virtual void SmoothCorrection (const FVector &OldLocation, const FQuat &OldRotation, const FVector &NewLocation, const FQuat &NewRotation) override
React to new transform from network update.
virtual class FNetworkPredictionData_Client * GetPredictionData_Client () const override
Get prediction data for a client game.
virtual class FNetworkPredictionData_Server * GetPredictionData_Server () const override
Get prediction data for a server game.
class FNetworkPredictionData_Client_Character * GetPredictionData_Client_Character () const
class FNetworkPredictionData_Server_Character * GetPredictionData_Server_Character () const
virtual bool HasPredictionData_Client () const override
virtual bool HasPredictionData_Server () const override
virtual void ResetPredictionData_Client () override
virtual void ResetPredictionData_Server () override
virtual void UpdateFloorFromAdjustment ()
React to instantaneous change in position.
virtual bool VerifyClientTimeStamp (float TimeStamp, FNetworkPredictionData_Server_Character &ServerData)
On the Server, verify that an incoming client TimeStamp is valid and has not yet expired.
void ServerMovePacked_ClientSend (const FCharacterServerMovePackedBits &PackedBits)
The actual network RPCs for character movement are passed to ACharacter, which wrap to the _Implementation call here, to avoid Component RPC overhead.
void ServerMovePacked_ServerReceive (const FCharacterServerMovePackedBits &PackedBits)
On the server, receives packed move data from the Character RPC, unpacks them into the FCharacterNetworkMoveDataContainer returned from GetNetworkMoveDataContainer(), and passes the data container to ServerMove_HandleMoveData().
virtual bool ShouldUsePackedMovementRPCs () const
Determines whether to use packed movement RPCs with variable length payloads, or legacy code which has multiple functions required for different situations.
void MoveResponsePacked_ServerSend (const FCharacterMoveResponsePackedBits &PackedBits)
void MoveResponsePacked_ClientReceive (const FCharacterMoveResponsePackedBits &PackedBits)
virtual void ClientAckGoodMove_Implementation (float TimeStamp)
virtual void ClientAdjustPosition_Implementation (float TimeStamp, FVector NewLoc, FVector NewVel, UPrimitiveComponent *NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode, TOptional< FRotator > OptionalRotation=TOptional< FRotator >())
virtual void ClientVeryShortAdjustPosition_Implementation (float TimeStamp, FVector NewLoc, UPrimitiveComponent *NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
virtual void ClientAdjustRootMotionPosition_Implementation (float TimeStamp, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent *ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
virtual void ClientAdjustRootMotionSourcePosition_Implementation (float TimeStamp, FRootMotionSourceGroup ServerRootMotion, bool bHasAnimRootMotion, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent *ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
virtual void ServerMove_HandleMoveData (const FCharacterNetworkMoveDataContainer &MoveDataContainer)
Handle movement data after it's unpacked from the ServerMovePacked_ServerReceive() call.
virtual void ServerMove_PerformMovement (const FCharacterNetworkMoveData &MoveData)
Check timestamps, generate a delta time, and pass through movement params to MoveAutonomous.
void ServerSendMoveResponse (const FClientAdjustment &PendingAdjustment)
On the server, sends a packed move response to the client.
virtual void ClientHandleMoveResponse (const FCharacterMoveResponseDataContainer &MoveResponse)
On the client, handles the move response from the server after it has been received and unpacked in MoveResponsePacked_ClientReceive.
virtual void ServerMove (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Replicated function sent by client to server - contains client movement and view info.
virtual void ServerMove_Implementation (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual bool ServerMove_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual void ServerMoveDual (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Replicated function sent by client to server - contains client movement and view info for two moves.
virtual void ServerMoveDual_Implementation (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual bool ServerMoveDual_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual void ServerMoveDualHybridRootMotion (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Replicated function sent by client to server - contains client movement and view info for two moves.
virtual void ServerMoveDualHybridRootMotion_Implementation (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual bool ServerMoveDualHybridRootMotion_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
virtual void ServerMoveOld (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
virtual void ServerMoveOld_Implementation (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
virtual bool ServerMoveOld_Validate (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
virtual void ClientAckGoodMove (float TimeStamp)
If no client adjustment is needed after processing received ServerMove(), ack the good move so client can remove it from SavedMoves.
virtual void ClientAdjustPosition (float TimeStamp, FVector NewLoc, FVector NewVel, UPrimitiveComponent *NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
Replicate position correction to client, associated with a timestamped servermove.
virtual void ClientVeryShortAdjustPosition (float TimeStamp, FVector NewLoc, UPrimitiveComponent *NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
virtual void ClientAdjustRootMotionPosition (float TimeStamp, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent *ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
Replicate position correction to client when using root motion for movement.
virtual void ClientAdjustRootMotionSourcePosition (float TimeStamp, FRootMotionSourceGroup ServerRootMotion, bool bHasAnimRootMotion, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent *ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode)
Replicate root motion source correction to client when using root motion for movement.
const FSavedMove_Character * GetCurrentReplayedSavedMove () const
Gets the SavedMove being replayed on the client after a correction is received.
bool HasRootMotionSources () const
Returns true if we have Root Motion from any source to use in PerformMovement() physics.
uint16 ApplyRootMotionSource (TSharedPtr< FRootMotionSource > SourcePtr)
Apply a RootMotionSource to current root motion.
virtual void OnRootMotionSourceBeingApplied (const FRootMotionSource *Source)
Called during ApplyRootMotionSource call, useful for project-specific alerts for "something is about to be altering our movement".
TSharedPtr< FRootMotionSource > GetRootMotionSource (FName InstanceName)
Get a RootMotionSource from current root motion by name.
TSharedPtr< FRootMotionSource > GetRootMotionSourceByID (uint16 RootMotionSourceID)
Get a RootMotionSource from current root motion by ID.
void RemoveRootMotionSource (FName InstanceName)
Remove a RootMotionSource from current root motion by name.
void RemoveRootMotionSourceByID (uint16 RootMotionSourceID)
Remove a RootMotionSource from current root motion by ID.
void ConvertRootMotionServerIDsToLocalIDs (const FRootMotionSourceGroup &LocalRootMotionToMatchWith, FRootMotionSourceGroup &InOutServerRootMotion, float TimeStamp)
Converts received server IDs in a root motion group to local IDs.
bool HasAnimRootMotion () const
Returns true if we have Root Motion from animation to use in PerformMovement() physics.
FTransform ConvertLocalRootMotionToWorld (const FTransform &InLocalRootMotion, float DeltaSeconds)
void SimulateRootMotion (float DeltaSeconds, const FTransform &LocalRootMotionTransform)
Simulate Root Motion physics on Simulated Proxies.
virtual FVector CalcAnimRootMotionVelocity (const FVector &RootMotionDeltaMove, float DeltaSeconds, const FVector &CurrentVelocity) const
Calculate velocity from anim root motion.
virtual FVector ConstrainAnimRootMotionVelocity (const FVector &RootMotionVelocity, const FVector &CurrentVelocity) const
Constrain components of root motion velocity that may not be appropriate given the current movement mode (e.g.
virtual void CalcAvoidanceVelocity (float DeltaTime)
calculate RVO avoidance and apply it to current velocity
virtual void PostProcessAvoidanceVelocity (FVector &NewVelocity)
allows modifing avoidance velocity, called when bUseRVOPostProcess is set
virtual void FlushServerMoves ()
ETeleportType GetTeleportType () const
When moving the character, we should inform physics as to whether we are teleporting.
void SetAvoidanceVelocityLock (class UAvoidanceManager *Avoidance, float Duration)
lock avoidance velocity
virtual void SetRVOAvoidanceUID (int32 UID) override
BEGIN IRVOAvoidanceInterface.
virtual int32 GetRVOAvoidanceUID () override
virtual void SetRVOAvoidanceWeight (float Weight) override
virtual float GetRVOAvoidanceWeight () override
virtual FVector GetRVOAvoidanceOrigin () override
virtual float GetRVOAvoidanceRadius () override
virtual float GetRVOAvoidanceHeight () override
virtual float GetRVOAvoidanceConsiderationRadius () override
virtual FVector GetVelocityForRVOConsideration () override
virtual void SetAvoidanceGroupMask (int32 GroupFlags) override
virtual int32 GetAvoidanceGroupMask () override
virtual void SetGroupsToAvoidMask (int32 GroupFlags) override
virtual int32 GetGroupsToAvoidMask () override
virtual void SetGroupsToIgnoreMask (int32 GroupFlags) override
virtual int32 GetGroupsToIgnoreMask () override
int32 GetRVOAvoidanceUIDFast () const
END IRVOAvoidanceInterface.
virtual void AddInputVector (FVector WorldVector, bool bForce=false)
Adds the given vector to the accumulated input in world space.
FVector GetPendingInputVector () const
Return the pending input vector in world space.
FVector GetLastInputVector () const
Return the last input vector in world space that was processed by ConsumeInputVector(), which is usually done by the Pawn or PawnMovementComponent.
virtual FVector ConsumeInputVector ()
virtual bool IsMoveInputIgnored () const
Helper to see if move input is ignored.
class APawn * GetPawnOwner () const
Return the Pawn that owns UpdatedComponent.
void ApplyAsyncPhysicsStateAction (const UPrimitiveComponent *ActionComponent, const FName &BoneName, const EPhysicsStateAction ActionType, const FVector &ActionDatas, const FVector &ActionPosition=FVector::Zero())
Apply the async physics state action onto the solver.
virtual UObject * GetOwnerAsObject () const override
Get the owner of the object consuming nav movement.
virtual TObjectPtr< UObject > GetUpdatedObject () const override
Get the component this movement component is updating.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const override
Get axis-aligned cylinder around this actor, used for simple collision checks in nav movement.
virtual FVector GetSimpleCollisionCylinderExtent () const override
Returns collision extents vector for this object, based on GetSimpleCollisionCylinder.
virtual FVector GetForwardVector () const override
Get forward vector of the object being driven by nav movement.
virtual FVector GetVelocityForNavMovement () const override
Get the current velocity of the movement component.
virtual float GetMaxSpeedForNavMovement () const override
Get maximum movement speed of the agent.
virtual void StopMovementImmediately () override
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
void SetUpdateNavAgentWithOwnersCollisions (bool bUpdateWithOwner)
bool ShouldUpdateNavAgentWithOwnersCollision () const
FVector GetActorLocation () const
Returns location of controlled actor - meaning center of collision bounding box.
virtual FBasedPosition GetActorFeetLocationBased () const
Returns based location of controlled actor.
FVector GetActorNavLocation () const
Returns navigation location of controlled actor.
FTransform GetActorTransform () const
Returns the full world-coordinates transform of the associated scene component (the UpdatedComponent)
virtual FVector GetLocation () const override
Returns location of controlled actor - meaning center of collision bounding box.
virtual FVector GetFeetLocation () const override
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
virtual FBasedPosition GetFeetLocationBased () const override
Returns based location of controlled actor.
virtual void UpdateNavAgent (const UObject &ObjectToUpdateFrom) override
Set nav agent properties from an object.
virtual FNavMovementProperties * GetNavMovementProperties () override
Get Nav movement props struct this component uses.
virtual const FNavMovementProperties & GetNavMovementProperties () const override
Returns the NavMovementProps(const)
void ClearFixedBrakingDistance ()
clears fixed braking distance
virtual void SetPathFollowingAgent (IPathFollowingAgentInterface *InPathFollowingAgent) override
Set the path following agent this interface uses.
virtual IPathFollowingAgentInterface * GetPathFollowingAgent () override
Get path following agent this interface uses.
virtual const IPathFollowingAgentInterface * GetPathFollowingAgent () const override
Get path following agent this interface uses(const)
const FNavAgentProperties & GetNavAgentPropertiesRef () const override
Returns the NavAgentProps(const)
FNavAgentProperties & GetNavAgentPropertiesRef () override
Returns the NavAgentProps.
virtual void ResetMoveState () override
Resets runtime movement state to character's movement capabilities.
bool IsJumpAllowed () const
Returns true if component is allowed to jump.
void SetJumpAllowed (bool bAllowed)
Sets whether this component is allowed to jump.
virtual void InitializeComponent () override
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
virtual bool IsExceedingMaxSpeed (float MaxSpeed) const
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
virtual bool ShouldSkipUpdate (float DeltaTime) const
Possibly skip update if moved component is not rendered or can't move.
virtual APhysicsVolume * GetPhysicsVolume () const
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
virtual bool IsInWater () const
Returns true if it's in PhysicsVolume with water flag.
virtual void UpdateTickRegistration ()
Update tick registration state, determined by bAutoUpdateTickRegistration.
virtual void UpdateComponentVelocity ()
Update ComponentVelocity of UpdatedComponent.
virtual void InitCollisionParams (FCollisionQueryParams &OutParams, FCollisionResponseParams &OutResponseParam) const
Initialize collision params appropriately based on our collision settings.
virtual bool OverlapTest (const FVector &Location, const FQuat &RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape &CollisionShape, const AActor *IgnoreActor) const
Return true if the given collision shape overlaps other geometry at the given location and rotation.
bool MoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool MoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
bool K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult &OutHit, bool bSweep=true, bool bTeleport=false)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool SafeMoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
bool SafeMoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Try to move out of penetration in an object after a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FRotator &NewRotation)
virtual void SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting)
Set the plane constraint axis setting.
EPlaneConstraintAxisSetting GetPlaneConstraintAxisSetting () const
Get the plane constraint axis setting.
virtual void SetPlaneConstraintNormal (FVector PlaneNormal)
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintFromVectors (FVector Forward, FVector Up)
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintOrigin (FVector PlaneOrigin)
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintEnabled (bool bEnabled)
Sets whether or not the plane constraint is enabled.
const FVector & GetPlaneConstraintNormal () const
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
const FVector & GetPlaneConstraintOrigin () const
Get the plane constraint origin.
virtual FVector ConstrainDirectionToPlane (FVector Direction) const
Constrain a direction vector to the plane constraint, if enabled.
virtual FVector ConstrainLocationToPlane (FVector Location) const
Constrain a position vector to the plane constraint, if enabled.
virtual FVector ConstrainNormalToPlane (FVector Normal) const
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
virtual void SnapUpdatedComponentToPlane ()
Snap the updated component to the plane constraint, if enabled.
virtual UE_API void StopMovementKeepPathing ()
Stops movement immediately (reset velocity) but keeps following current path.
UE_API FVector GetNavLocation () const
Returns navigation location of controlled agent.
UE_API void SetFixedBrakingDistance (float DistanceToEndOfPath)
Set fixed braking distance.
UE_API bool UseAccelerationForPathFollowing () const
Returns true if acceleration should be used for path following.
virtual bool CanEverCrouch () const
Returns true if agent can crouch.
virtual bool CanEverJump () const
Returns true if agent can jump.
virtual bool CanEverMoveOnGround () const
Returns true if agent can move along the ground (walk, drive, etc)
virtual bool CanEverSwim () const
Returns true if agent can swim.
virtual bool CanEverFly () const
Returns true if agent can fly.
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static uint32 PackYawAndPitchTo32 (const float Yaw, const float Pitch)
static void PhysicsLockedAxisSettingChanged ()
Public Attributes
float GravityScale
Custom gravity scale.
float MaxStepHeight
Maximum height character can step up.
float JumpZVelocity
Initial velocity (instantaneous vertical acceleration) when jumping.
float JumpOffJumpZFactor
Fraction of JumpZVelocity to use when automatically "jumping off" of a base actor that's not allowed to be a base for a character.
TEnumAsByte< enum EMovementMode > MovementMode
Actor's current movement mode (walking, falling, etc).
uint8 CustomMovementMode
Current custom sub-mode if MovementMode is set to Custom.
ENetworkSmoothingMode NetworkSmoothingMode
Smoothing mode for simulated proxies in network game.
float GroundFriction
Setting that affects movement control.
FQuat OldBaseQuat
Saved location of object we are standing on, for UpdateBasedMovement() to determine if base moved in the last frame, and therefore pawn needs an update.
FVector OldBaseLocation
Saved location of object we are standing on, for UpdateBasedMovement() to determine if base moved in the last frame, and therefore pawn needs an update.
float MaxWalkSpeed
The maximum ground speed when walking.
float MaxWalkSpeedCrouched
The maximum ground speed when walking and crouched.
float MaxSwimSpeed
The maximum swimming speed.
float MaxFlySpeed
The maximum flying speed.
float MaxCustomMovementSpeed
The maximum speed when using Custom movement mode.
float MaxAcceleration
Max Acceleration (rate of change of velocity)
float MinAnalogWalkSpeed
The ground speed that we should accelerate up to when walking at minimum analog stick tilt.
float BrakingFrictionFactor
Factor used to multiply actual value of friction used when braking.
float BrakingFriction
Friction (drag) coefficient applied when braking (whenever Acceleration = 0, or if character is exceeding max speed); actual value used is this multiplied by BrakingFrictionFactor.
float BrakingSubStepTime
Time substepping when applying braking friction.
float BrakingDecelerationWalking
Deceleration when walking and not applying acceleration.
float BrakingDecelerationFalling
Lateral deceleration when falling and not applying acceleration.
float BrakingDecelerationSwimming
Deceleration when swimming and not applying acceleration.
float BrakingDecelerationFlying
Deceleration when flying and not applying acceleration.
float AirControl
When falling, amount of lateral movement control available to the character.
float AirControlBoostMultiplier
When falling, multiplier applied to AirControl when lateral velocity is less than AirControlBoostVelocityThreshold.
float AirControlBoostVelocityThreshold
When falling, if lateral velocity magnitude is less than this value, AirControl is multiplied by AirControlBoostMultiplier.
float FallingLateralFriction
Friction to apply to lateral air movement when falling.
float CrouchedHalfHeight
Collision half-height when crouching (component scale is applied separately)
float Buoyancy
Water buoyancy.
float PerchRadiusThreshold
Don't allow the character to perch on the edge of a surface if the contact is this close to the edge of the capsule.
float PerchAdditionalHeight
When perching on a ledge, add this additional distance to MaxStepHeight when determining how high above a walkable floor we can perch.
FRotator RotationRate
Change in rotation per second, used when UseControllerDesiredRotation or OrientRotationToMovement are true.
uint8 bUseSeparateBrakingFriction:1
If true, BrakingFriction will be used to slow the character to a stop (when there is no Acceleration).
uint8 bDontFallBelowJumpZVelocityDuringJump:1
True means while the jump key is held, we will not allow the vertical speed to fall below the JumpZVelocity tuning value even if a stronger force, such as gravity, is opposing the jump.
uint8 bApplyGravityWhileJumping:1
Apply gravity while the character is actively jumping (e.g.
uint8 bUseControllerDesiredRotation:1
If true, smoothly rotate the Character toward the Controller's desired rotation (typically Controller->ControlRotation), using RotationRate as the rate of rotation change.
uint8 bOrientRotationToMovement:1
If true, rotate the Character toward the direction of acceleration, using RotationRate as the rate of rotation change.
uint8 bSweepWhileNavWalking:1
Whether or not the character should sweep for collision geometry while walking.
uint8 bEnableScopedMovementUpdates:1
If true, high-level movement updates will be wrapped in a movement scope that accumulates updates and defers a bulk of the work until the end.
uint8 bEnableServerDualMoveScopedMovementUpdates: 1
Optional scoped movement update to combine moves for cheaper performance on the server when the client sends two moves in one packet.
uint8 bForceMaxAccel:1
Ignores size of acceleration component, and forces max acceleration to drive character at full velocity.
uint8 bRunPhysicsWithNoController:1
If true, movement will be performed even if there is no Controller for the Character owner.
uint8 bForceNextFloorCheck:1
Force the Character in MOVE_Walking to do a check for a valid floor even if it hasn't moved.
uint8 bShrinkProxyCapsule:1
If true, the capsule needs to be shrunk on this simulated proxy, to avoid replication rounding putting us in geometry.
uint8 bCanWalkOffLedges:1
If true, Character can walk off a ledge.
uint8 bCanWalkOffLedgesWhenCrouching:1
If true, Character can walk off a ledge when crouching.
uint8 bNetworkSmoothingComplete:1
Signals that smoothed position/rotation has reached target, and no more smoothing is necessary until a future update.
uint8 bNetworkLargeClientCorrection:1
Flag indicating the client correction was larger than NetworkLargeClientCorrectionThreshold.
uint8 bNetworkSkipProxyPredictionOnNetUpdate:1
Whether we skip prediction on frames where a proxy receives a network update.
uint8 bNetworkAlwaysReplicateTransformUpdateTimestamp:1
Flag used on the server to determine whether to always replicate ReplicatedServerLastTransformUpdateTimeStamp to clients.
uint8 bDeferUpdateMoveComponent:1
true to update CharacterOwner and UpdatedComponent after movement ends
uint8 bEnablePhysicsInteraction:1
If enabled, the player will interact with physics objects when walking into them.
uint8 bTouchForceScaledToMass:1
If enabled, the TouchForceFactor is applied per kg mass of the affected object.
uint8 bPushForceScaledToMass:1
If enabled, the PushForceFactor is applied per kg mass of the affected object.
uint8 bPushForceUsingZOffset:1
If enabled, the PushForce location is moved using PushForcePointZOffsetFactor.
uint8 bScalePushForceToVelocity:1
If enabled, the applied push force will try to get the physics object to the same velocity than the player, not faster.
TObjectPtr< USceneComponent > DeferredUpdatedMoveComponent
What to update CharacterOwner and UpdatedComponent after movement ends.
float MaxOutOfWaterStepHeight
Maximum step height for getting out of water.
float OutofWaterZ
Z velocity applied when pawn tries to get out of water.
float Mass
Mass of pawn (for when momentum is imparted to it).
float StandingDownwardForceScale
Force applied to objects we stand on (due to Mass and Gravity) is scaled by this amount.
float InitialPushForceFactor
Initial impulse force to apply when the player bounces into a blocking physics object.
float PushForceFactor
Force to apply when the player collides with a blocking physics object.
float PushForcePointZOffsetFactor
Z-Offset for the position the force is applied to.
float TouchForceFactor
Force to apply to physics objects that are touched by the player.
float MinTouchForce
Minimum Force applied to touched physics objects.
float MaxTouchForce
Maximum force applied to touched physics objects.
float RepulsionForce
Force per kg applied constantly to all overlapping components.
uint32 bForceBraking_DEPRECATED:1
float CrouchedSpeedMultiplier_DEPRECATED
Multiplier to max ground speed to use when crouched.
float UpperImpactNormalScale_DEPRECATED
float MaxSimulationTimeStep
Max time delta for each discrete simulation step.
int32 MaxSimulationIterations
Max number of iterations used for each discrete simulation step.
int32 MaxJumpApexAttemptsPerSimulation
Max number of attempts per simulation to attempt to exactly reach the jump apex when falling movement reaches the top of the arc.
float MaxDepenetrationWithGeometry
Max distance we allow simulated proxies to depenetrate when moving out of anything but Pawns.
float MaxDepenetrationWithGeometryAsProxy
Max distance we allow simulated proxies to depenetrate when moving out of anything but Pawns.
float MaxDepenetrationWithPawn
Max distance we are allowed to depenetrate when moving out of other Pawns.
float MaxDepenetrationWithPawnAsProxy
Max distance we allow simulated proxies to depenetrate when moving out of other Pawns.
float NetworkSimulatedSmoothLocationTime
How long to take to smoothly interpolate from the old pawn position on the client to the corrected one sent by the server.
float NetworkSimulatedSmoothRotationTime
How long to take to smoothly interpolate from the old pawn rotation on the client to the corrected one sent by the server.
float ListenServerNetworkSimulatedSmoothLocationTime
Similar setting as NetworkSimulatedSmoothLocationTime but only used on Listen servers.
float ListenServerNetworkSimulatedSmoothRotationTime
Similar setting as NetworkSimulatedSmoothRotationTime but only used on Listen servers.
float NetProxyShrinkRadius
Shrink simulated proxy capsule radius by this amount, to account for network rounding that may cause encroachment.
float NetProxyShrinkHalfHeight
Shrink simulated proxy capsule half height by this amount, to account for network rounding that may cause encroachment.
float NetworkMaxSmoothUpdateDistance
Maximum distance character is allowed to lag behind server location when interpolating between updates.
float NetworkNoSmoothUpdateDistance
Maximum distance beyond which character is teleported to the new server location without any smoothing.
float NetworkMinTimeBetweenClientAckGoodMoves
Minimum time on the server between acknowledging good client moves.
float NetworkMinTimeBetweenClientAdjustments
Minimum time on the server between sending client adjustments when client has exceeded allowable position error.
float NetworkMinTimeBetweenClientAdjustmentsLargeCorrection
Minimum time on the server between sending client adjustments when client has exceeded allowable position error by a large amount (NetworkLargeClientCorrectionDistance).
float NetworkLargeClientCorrectionDistance
If client error is larger than this, sets bNetworkLargeClientCorrection to reduce delay between client adjustments.
float LedgeCheckThreshold
Used in determining if pawn is going off ledge.
float JumpOutOfWaterPitch
When exiting water, jump if control pitch angle is this high or above.
FFindFloorResult CurrentFloor
Information about the floor the Character is standing on (updated only during walking movement).
TEnumAsByte< enum EMovementMode > DefaultLandMovementMode
Default movement mode when not in water.
TEnumAsByte< enum EMovementMode > DefaultWaterMovementMode
Default movement mode when in water.
uint8 bMaintainHorizontalGroundVelocity:1
If true, walking movement always maintains horizontal velocity when moving up ramps, which causes movement up ramps to be faster parallel to the ramp surface.
uint8 bImpartBaseVelocityX:1
If true, impart the base actor's X velocity when falling off it (which includes jumping)
uint8 bImpartBaseVelocityY:1
If true, impart the base actor's Y velocity when falling off it (which includes jumping)
uint8 bImpartBaseVelocityZ:1
If true, impart the base actor's Z velocity when falling off it (which includes jumping)
uint8 bImpartBaseAngularVelocity:1
If true, impart the base component's tangential components of angular velocity when jumping or falling off it.
uint8 bJustTeleported:1
Used by movement code to determine if a change in position is based on normal movement or a teleport.
uint8 bNetworkUpdateReceived:1
True when a network replication update is received for simulated proxies.
uint8 bNetworkMovementModeChanged:1
True when the networked movement mode has been replicated.
uint8 bNetworkGravityDirectionChanged:1
True when the networked gravity direction has been replicated.
uint8 bIgnoreClientMovementErrorChecksAndCorrection:1
If true, we should ignore server location difference checks for client error on this movement component.
uint8 bServerAcceptClientAuthoritativePosition: 1
If true, and server does not detect client position error, server will copy the client movement location/velocity/etc after simulating the move.
uint8 bNotifyApex:1
If true, event NotifyJumpApex() to CharacterOwner's controller when at apex of jump.
uint8 bCheatFlying:1
Instantly stop when in flying mode and no acceleration is being applied.
uint8 bWantsToCrouch:1
If true, try to crouch (or keep crouching) on next update.
uint8 bCrouchMaintainsBaseLocation:1
If true, crouching should keep the base of the capsule in place by lowering the center of the shrunken capsule.
uint8 bIgnoreBaseRotation:1
Whether the character ignores changes in rotation of the base it is standing on.
uint8 bFastAttachedMove:1
Set this to true if riding on a moving base that you know is clear from non-moving world obstructions.
uint8 bAlwaysCheckFloor:1
Whether we always force floor checks for stationary Characters while walking.
uint8 bUseFlatBaseForFloorChecks:1
Performs floor checks as if the character is using a shape with a flat base.
uint8 bPerformingJumpOff:1
Used to prevent reentry of JumpOff()
uint8 bWantsToLeaveNavWalking:1
Used to safely leave NavWalking movement mode.
uint8 bUseRVOAvoidance:1
If set, component will use RVO avoidance.
uint8 bRequestedMoveUseAcceleration:1
Should use acceleration for path following?
uint8 bIsNavWalkingOnServer: 1
Set on clients when server's movement mode is NavWalking.
uint8 bWasSimulatingRootMotion:1
True when SimulatedProxies are simulating RootMotion.
uint8 bAllowPhysicsRotationDuringAnimRootMotion: 1
float FormerBaseVelocityDecayHalfLife = 0.f
When applying a root motion override while falling off a moving object, this controls how long it takes to lose half the former base's velocity (in seconds).
float AvoidanceConsiderationRadius
FVector RequestedVelocity
Velocity requested by path following.
FVector LastUpdateRequestedVelocity
Velocity requested by path following during last Update Updated when we consume the value.
int32 AvoidanceUID
No default value, for now it's assumed to be valid if GetAvoidanceManager() returns non-NULL.
FNavAvoidanceMask AvoidanceGroup
Moving actor's group mask.
FNavAvoidanceMask GroupsToAvoid
Will avoid other agents if they are in one of specified groups.
FNavAvoidanceMask GroupsToIgnore
Will NOT avoid other agents if they are in one of specified groups, higher priority than GroupsToAvoid.
float AvoidanceWeight
De facto default value 0.5 (due to that being the default in the avoidance registration function), indicates RVO behavior.
FVector PendingLaunchVelocity
Temporarily holds launch velocity when pawn is to be launched so it happens at end of movement.
FNavLocation CachedNavLocation
last known location projected on navmesh, used by NavWalking mode
FHitResult CachedProjectedNavMeshHitResult
Last valid projected hit result from raycast to geometry from navmesh.
FName LastServerMovementBaseBoneName = NAME_None
Remember last server movement base bone so we can detect mounts/dismounts and respond accordingly.
bool bLastClientIsFalling = false
Remember if the client was previously falling so we can tell when they've just landed.
bool bLastServerIsFalling = false
Remember if the server was previously falling so we can tell when they've just landed.
bool bLastServerIsWalking = false
Whether we were just walking on something, used to help with transitions off moving objects.
bool bTeleportedSinceLastUpdate = false
True if the UpdatedComponent was moved outside of this CharacterMovementComponent since the last move – its starting location for this update doesn't match its ending position for the previous update.
bool bCanTrustClientOnLanding = false
Whether we're stepping off a moving platform (and should trust the client somewhat when landing).
float MaxServerClientErrorWhileFalling = 0.f
How loosely the client can follow the server location during this fall.
FVector DecayingFormerBaseVelocity = FVector::ZeroVector
Left over velocity when leaving a moving base.
float NavMeshProjectionInterval
How often we should raycast to project from navmesh to underlying geometry.
float NavMeshProjectionTimer
float NavMeshProjectionInterpSpeed
Speed at which to interpolate agent navmesh offset between traces.
float NavMeshProjectionHeightScaleUp
Scale of the total capsule height to use for projection from navmesh to underlying geometry in the upward direction.
float NavMeshProjectionHeightScaleDown
Scale of the total capsule height to use for projection from navmesh to underlying geometry in the downward direction.
float NavWalkingFloorDistTolerance
Ignore small differences in ground height between server and client data during NavWalking mode.
bool bBasedMovementIgnorePhysicsBase = false
Property to set if UpdateBasedMovement should ignore collision with actors part of the current MovementBase, if the base is simulated by physics.
bool bBaseOnAttachmentRoot = false
Property to set if characters should stay based on objects attachment root instead of the traced object.
bool bStayBasedInAir = false
Property to set if characters should stay based on objects while jumping.
float StayBasedInAirHeight = 1000.0f
Property used to set how high above base characters should stay based on objects while jumping if bStayBasedInAir is set.
struct FCharacterMovementComponentPrePhysicsTickFunction PrePhysicsTickFunction
Pre-physics tick function for this character.
struct FCharacterMovementComponentPostPhysicsTickFunction PostPhysicsTickFunction
Post-physics tick function for this character.
float MinTimeBetweenTimeStampResets
Minimum time between client TimeStamp resets.
FRootMotionSourceGroup CurrentRootMotion
Root Motion Group containing active root motion sources being applied to movement.
FRootMotionSourceGroup ServerCorrectionRootMotion
FRootMotionAsyncData AsyncRootMotion
TArray< FRootMotionServerToLocalIDMapping, TInlineAllocator<(uint32) ERootMotionMapping::MapSize > > RootMotionIDMappings
FRootMotionMovementParams RootMotionParams
Animation root motion (special case for now)
FVector AnimRootMotionVelocity
Velocity extracted from RootMotionParams when there is anim root motion active.
FOnProcessRootMotion ProcessRootMotionPreConvertToWorld
FOnProcessRootMotion ProcessRootMotionPostConvertToWorld
FNavAgentProperties NavAgentProps
Properties that define how the component can move.
FMovementProperties MovementState
Expresses runtime state of character's movement.
uint8 bUpdateOnlyIfRendered:1
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
uint8 bAutoUpdateTickRegistration:1
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
uint8 bTickBeforeOwner:1
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
uint8 bAutoRegisterUpdatedComponent:1
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
uint8 bConstrainToPlane:1
If true, movement will be constrained to a plane.
uint8 bSnapToPlaneAtStart:1
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
uint8 bAutoRegisterPhysicsVolumeUpdates:1
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
uint8 bComponentShouldUpdatePhysicsVolume:1
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Static Public Attributes
static const FVector DefaultGravityDirection
The default direction that gravity points for movement simulation.
static const float MIN_TICK_TIME
Minimum delta time considered when ticking.
static const float MIN_FLOOR_DIST
Minimum acceptable distance for Character capsule to float above floor when walking.
static const float MAX_FLOOR_DIST
Maximum acceptable distance for Character capsule to float above floor when walking.
static const float SWEEP_EDGE_REJECT_DISTANCE
Reject sweep impacts that are this close to the edge of the vertical portion of the capsule when performing vertical sweeps, and try again with a smaller capsule.
static const float BRAKE_TO_STOP_VELOCITY
Stop completely when braking and velocity magnitude is lower than this.
Protected Member Functions
virtual float ComputeAnalogInputModifier () const
Computes the analog input modifier based on current input vector and/or acceleration.
virtual void OnMovementModeChanged (EMovementMode PreviousMovementMode, uint8 PreviousCustomMode)
Called after MovementMode has changed.
virtual float BoostAirControl (float DeltaTime, float TickAirControl, const FVector &FallAcceleration)
Increase air control if conditions of AirControlBoostMultiplier and AirControlBoostVelocityThreshold are met.
virtual FVector LimitAirControl (float DeltaTime, const FVector &FallAcceleration, const FHitResult &HitResult, bool bCheckForValidLandingSpot)
Limits the air control to use during falling movement, given an impact while falling.
virtual void ProcessLanded (const FHitResult &Hit, float remainingTime, int32 Iterations)
Handle landing against Hit surface over remaingTime and iterations, calling SetPostLandedPhysics() and starting the new movement mode.
virtual void SetPostLandedPhysics (const FHitResult &Hit)
Use new physics after landing.
virtual void ControlledCharacterMove (const FVector &InputVector, float DeltaSeconds)
Updates acceleration and perform movement, called from the TickComponent on the authoritative side for controlled characters, or on the client for characters without a controller when either playing root motion or bRunPhysicsWithNoController is true.
virtual void SetNavWalkingPhysics (bool bEnable)
Switch collision settings for NavWalking mode (ignore world collisions)
const class INavigationDataInterface * GetNavData () const
Get Navigation data for the Character.
virtual bool TryToLeaveNavWalking ()
Checks to see if the current location is not encroaching blocking geometry so the character can leave NavWalking.
virtual FVector ProjectLocationFromNavMesh (float DeltaSeconds, const FVector &CurrentFeetLocation, const FVector &TargetNavLocation, float UpOffset, float DownOffset)
Attempts to better align navmesh walking characters with underlying geometry (sometimes navmesh can differ quite significantly from geometry).
virtual void FindBestNavMeshLocation (const FVector &TraceStart, const FVector &TraceEnd, const FVector &CurrentFeetLocation, const FVector &TargetNavLocation, FHitResult &OutHitResult) const
Performs trace for ProjectLocationFromNavMesh.
virtual bool ShouldComputeAccelerationToReachRequestedVelocity (const float RequestedSpeed) const
When a character requests a velocity (like when following a path), this method returns true if when we should compute the acceleration toward requested velocity (including friction).
virtual void PhysWalking (float deltaTime, int32 Iterations)
\note Movement update functions should only be called through StartNewPhysics()
virtual void PhysNavWalking (float deltaTime, int32 Iterations)
\note Movement update functions should only be called through StartNewPhysics()
virtual void PhysFlying (float deltaTime, int32 Iterations)
\note Movement update functions should only be called through StartNewPhysics()
virtual void PhysSwimming (float deltaTime, int32 Iterations)
\note Movement update functions should only be called through StartNewPhysics()
virtual void PhysCustom (float deltaTime, int32 Iterations)
\note Movement update functions should only be called through StartNewPhysics()
virtual void HandleSwimmingWallHit (const FHitResult &Hit, float DeltaTime)
virtual FVector ComputeGroundMovementDelta (const FVector &Delta, const FHitResult &RampHit, const bool bHitFromLineTrace) const
Compute a vector of movement, given a delta and a hit result of the surface we are on.
virtual void MoveAlongFloor (const FVector &InVelocity, float DeltaSeconds, FStepDownResult *OutStepDownResult=NULL)
Move along the floor, using CurrentFloor and ComputeGroundMovementDelta() to get a movement direction.
virtual void OnCharacterStuckInGeometry (const FHitResult *Hit)
Notification that the character is stuck in geometry.
virtual void MaintainHorizontalGroundVelocity ()
Adjusts velocity when walking so that Z velocity is zero.
virtual FVector GetPenetrationAdjustment (const FHitResult &Hit) const override
Overridden to enforce max distances based on hit geometry.
virtual bool ResolvePenetrationImpl (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation) override
Overridden to set bJustTeleported to true, so we don't make incorrect velocity calculations based on adjusted movement.
virtual void HandleImpact (const FHitResult &Hit, float TimeSlice=0.f, const FVector &MoveDelta=FVector::ZeroVector) override
Handle a blocking impact.
virtual void ApplyImpactPhysicsForces (const FHitResult &Impact, const FVector &ImpactAcceleration, const FVector &ImpactVelocity)
Apply physics forces to the impacted component, if bEnablePhysicsInteraction is true.
virtual float SlideAlongSurface (const FVector &Delta, float Time, const FVector &Normal, FHitResult &Hit, bool bHandleImpact) override
Custom version of SlideAlongSurface that handles different movement modes separately; namely during walking physics we might not want to slide up slopes.
virtual void TwoWallAdjust (FVector &WorldSpaceDelta, const FHitResult &Hit, const FVector &OldHitNormal) const override
Custom version that allows upwards slides when walking if the surface is walkable.
virtual FVector ComputeSlideVector (const FVector &Delta, const float Time, const FVector &Normal, const FHitResult &Hit) const override
Calculate slide vector along a surface.
virtual FVector HandleSlopeBoosting (const FVector &SlideResult, const FVector &Delta, const float Time, const FVector &Normal, const FHitResult &Hit) const
Limit the slide vector when falling if the resulting slide might boost the character faster upwards.
virtual void ApplyVelocityBraking (float DeltaTime, float Friction, float BrakingDeceleration)
Slows towards stop.
virtual void CapsuleTouched (UPrimitiveComponent *OverlappedComp, AActor *Other, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
Called when the collision capsule touches another primitive component.
FVector GetPawnCapsuleExtent (const EShrinkCapsuleExtent ShrinkMode, const float CustomShrinkAmount=0.f) const
Get the capsule extent for the Pawn owner, possibly reduced in size depending on ShrinkMode.
FCollisionShape GetPawnCapsuleCollisionShape (const EShrinkCapsuleExtent ShrinkMode, const float CustomShrinkAmount=0.f) const
Get the collision shape for the Pawn owner, possibly reduced in size depending on ShrinkMode.
virtual void AdjustProxyCapsuleSize ()
Adjust the size of the capsule on simulated proxies, to avoid overlaps due to replication rounding.
virtual FVector ConstrainInputAcceleration (const FVector &InputAcceleration) const
Enforce constraints on input given current state.
virtual FVector ScaleInputAcceleration (const FVector &InputAcceleration) const
Scale input acceleration, based on movement acceleration rate.
virtual void OnMovementUpdated (float DeltaSeconds, const FVector &OldLocation, const FVector &OldVelocity)
Event triggered at the end of a movement update.
virtual void CallMovementUpdateDelegate (float DeltaSeconds, const FVector &OldLocation, const FVector &OldVelocity)
Internal function to call OnMovementUpdated delegate on CharacterOwner.
virtual void OnUnableToFollowBaseMove (const FVector &DeltaPosition, const FVector &OldLocation, const FHitResult &MoveOnBaseHit)
Event triggered when we are moving on a base but we are not able to move the full DeltaPosition because something has blocked us.
virtual void AccumulateRootMotionForAsync (float DeltaSeconds, FRootMotionAsyncData &RootMotion)
virtual void FillAsyncInput (const FVector &InputVector, FCharacterMovementComponentAsyncInput &AsyncInput)
virtual void BuildAsyncInput ()
virtual void PostBuildAsyncInput ()
virtual void ApplyAsyncOutput (FCharacterMovementComponentAsyncOutput &Output)
virtual void ProcessAsyncOutput ()
virtual void RegisterAsyncCallback ()
virtual bool IsAsyncCallbackRegistered () const
virtual void PerformMovement (float DeltaTime)
Perform movement on an autonomous client.
virtual void SimulatedTick (float DeltaSeconds)
Special Tick for Simulated Proxies.
virtual void SimulateMovement (float DeltaTime)
Simulate movement on a non-owning client.
virtual void ServerAutonomousProxyTick (float DeltaSeconds)
Special Tick to allow custom server-side functionality on Autonomous Proxies.
virtual void SmoothClientPosition (float DeltaSeconds)
Smooth mesh location for network interpolation, based on values set up by SmoothCorrection.
void SmoothClientPosition_Interpolate (float DeltaSeconds)
Update interpolation values for client smoothing.
void SmoothClientPosition_UpdateVisuals ()
Update mesh location based on interpolated values.
virtual void ReplicateMoveToServer (float DeltaTime, const FVector &NewAcceleration)
Perform local movement and send the move to the server.
virtual bool ClientUpdatePositionAfterServerUpdate ()
If bUpdatePosition is true, then replay any unacked moves.
virtual void CallServerMove (const FSavedMove_Character *NewMove, const FSavedMove_Character *OldMove)
Call the appropriate replicated ServerMove() function to send a client player move to the server.
virtual void CallServerMovePacked (const FSavedMove_Character *NewMove, const FSavedMove_Character *PendingMove, const FSavedMove_Character *OldMove)
On the client, calls the ServerMovePacked_ClientSend() function with packed movement data.
virtual void ServerMoveHandleClientError (float ClientTimeStamp, float DeltaTime, const FVector &Accel, const FVector &RelativeClientLocation, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Have the server check if the client is outside an error tolerance, and queue a client adjustment if so.
virtual bool ServerCheckClientError (float ClientTimeStamp, float DeltaTime, const FVector &Accel, const FVector &ClientWorldLocation, const FVector &RelativeClientLocation, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Check for Server-Client disagreement in position or other movement state important enough to trigger a client correction.
virtual bool ServerExceedsAllowablePositionError (float ClientTimeStamp, float DeltaTime, const FVector &Accel, const FVector &ClientWorldLocation, const FVector &RelativeClientLocation, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
Check position error within ServerCheckClientError().
virtual bool ServerShouldUseAuthoritativePosition (float ClientTimeStamp, float DeltaTime, const FVector &Accel, const FVector &ClientWorldLocation, const FVector &RelativeClientLocation, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
If ServerCheckClientError() does not find an error, this determines if the server should also copy the client's movement params rather than keep the server sim result.
virtual void MoveAutonomous (float ClientTimeStamp, float DeltaTime, uint8 CompressedFlags, const FVector &NewAccel)
virtual void UpdateFromCompressedFlags (uint8 Flags)
Unpack compressed flags from a saved move and set state accordingly.
virtual bool CanDelaySendingMove (const FSavedMovePtr &NewMove)
Return true if it is OK to delay sending this player movement to the server, in order to conserve bandwidth.
virtual float GetClientNetSendDeltaTime (const APlayerController *PC, const FNetworkPredictionData_Client_Character *ClientData, const FSavedMovePtr &NewMove) const
Determine minimum delay between sending client updates to the server.
virtual void TickCharacterPose (float DeltaTime)
Ticks the characters pose and accumulates root motion.
virtual bool ShouldCancelAdaptiveReplication () const
On the server if we know we are having our replication rate throttled, this method checks if important replicated properties have changed that should cause us to return to the normal replication rate.
bool IsClientTimeStampValid (float TimeStamp, const FNetworkPredictionData_Server_Character &ServerData, bool &bTimeStampResetDetected) const
Internal const check for client timestamp validity without side-effects.
virtual void OnClientTimeStampResetDetected ()
Called by UCharacterMovementComponent::VerifyClientTimeStamp() when a client timestamp reset has been detected and is valid.
virtual void ProcessClientTimeStampForTimeDiscrepancy (float ClientTimeStamp, FNetworkPredictionData_Server_Character &ServerData)
Processes client timestamps from ServerMoves, detects and protects against time discrepancy between client-reported times and server time Called by UCharacterMovementComponent::VerifyClientTimeStamp() for valid timestamps.
virtual void OnTimeDiscrepancyDetected (float CurrentTimeDiscrepancy, float LifetimeRawTimeDiscrepancy, float Lifetime, float CurrentMoveError)
Called by UCharacterMovementComponent::ProcessClientTimeStampForTimeDiscrepancy() (on server) when the time from client moves significantly differs from the server time, indicating potential time manipulation by clients (speed hacks, significant network issues, client performance problems)
virtual void OnClientCorrectionReceived (class FNetworkPredictionData_Client_Character &ClientData, float TimeStamp, FVector NewLocation, FVector NewVelocity, UPrimitiveComponent *NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode, FVector ServerGravityDirection)
Event notification when client receives correction data from the server, before applying the data.
void SetNetworkMoveDataContainer (FCharacterNetworkMoveDataContainer &PersistentDataStorage)
Set custom struct used for client to server move RPC serialization.
FCharacterNetworkMoveDataContainer & GetNetworkMoveDataContainer () const
Get the struct used for client to server move RPC serialization.
FCharacterNetworkMoveData * GetCurrentNetworkMoveData () const
Current move data being processed or handled.
void SetCurrentNetworkMoveData (FCharacterNetworkMoveData *CurrentData)
Used internally to set the FCharacterNetworkMoveData currently being processed, either being serialized or replayed on the client, or being received and processed on the server.
void SetMoveResponseDataContainer (FCharacterMoveResponseDataContainer &PersistentDataStorage)
Set custom struct used for server response RPC serialization.
FCharacterMoveResponseDataContainer & GetMoveResponseDataContainer () const
Get the struct used for server response RPC serialization.
void SetCurrentReplayedSavedMove (FSavedMove_Character *SavedMove)
Used internally to save the SavedMove currently being replayed on the client so it is accessible to any functions that might need it.
virtual void RestorePreAdditiveRootMotionVelocity ()
Restores Velocity to LastPreAdditiveVelocity during Root Motion Phys*() function calls.
virtual void ApplyRootMotionToVelocity (float deltaTime)
Applies root motion from root motion sources to velocity (override and additive)
void DecayFormerBaseVelocity (float deltaTime)
Reduces former base velocity according to FormerBaseVelocityDecayHalfLife.
void UpdateDefaultAvoidance ()
called in Tick to update data in RVO avoidance manager
virtual AController * GetController () const
Returns this component's associated controller, typically from the owning Pawn.
void MarkForClientCameraUpdate ()
Attempts to mark the PlayerCameraManager as dirty, if the controller has one.
FVector GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const
Helper to compute the plane constraint axis from the current setting.
virtual bool MoveUpdatedComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
Protected Attributes
TObjectPtr< ACharacter > CharacterOwner
Character movement component belongs to.
TSharedPtr< FCharacterMovementComponentAsyncOutput, ESPMode::ThreadSafe > AsyncSimState
bool bMovementModeDirty = false
uint8 bMovementInProgress:1
True during movement update.
FVector Acceleration
Current acceleration vector (with magnitude).
FQuat LastUpdateRotation
Rotation after last PerformMovement or SimulateMovement update.
FVector LastUpdateLocation
Location after last PerformMovement or SimulateMovement update.
FVector LastUpdateVelocity
Velocity after last PerformMovement or SimulateMovement update.
float ServerLastTransformUpdateTimeStamp
Timestamp when location or rotation last changed during an update.
float ServerLastClientGoodMoveAckTime
Timestamp of last client adjustment sent.
float ServerLastClientAdjustmentTime
Timestamp of last client adjustment sent.
FVector PendingImpulseToApply
Accumulated impulse to be added next tick.
FVector PendingForceToApply
Accumulated force to be added next tick.
float AnalogInputModifier
Modifier to applied to values such as acceleration and max speed due to analog input.
float LastStuckWarningTime
Used for throttling "stuck in geometry" logging.
uint32 StuckWarningCountSinceNotify
Used when throttling "stuck in geometry" logging, to output the number of events we skipped if throttling.
int32 NumJumpApexAttempts
Used to limit number of jump apex attempts per tick.
uint8 bHasRequestedVelocity:1
Was velocity requested by path following?
uint8 bRequestedMoveWithMaxSpeed:1
Was acceleration requested to be always max speed?
uint8 bWasAvoidanceUpdated: 1
Was avoidance updated in this frame?
uint8 bUseRVOPostProcess: 1
if set, PostProcessAvoidanceVelocity will be called
uint8 bDeferUpdateBasedMovement: 1
Flag set in pre-physics update to indicate that based movement should be updated post-physics.
uint8 bProjectNavMeshWalking: 1
Whether to raycast to underlying geometry to better conform navmesh-walking characters.
uint8 bProjectNavMeshOnBothWorldChannels: 1
Use both WorldStatic and WorldDynamic channels for NavWalking geometry conforming.
FVector AvoidanceLockVelocity
forced avoidance velocity, used when AvoidanceLockTimer is > 0
float AvoidanceLockTimer
remaining time of avoidance velocity lock
class FNetworkPredictionData_Client_Character * ClientPredictionData
class FNetworkPredictionData_Server_Character * ServerPredictionData
FRandomStream RandomStream
float LastTimeStampResetServerTime
Clock time on the server of the last timestamp reset.
TObjectPtr< class APawn > PawnOwner
Pawn that owns this component.
float FixedPathBrakingDistance_DEPRECATED
Braking distance override used with acceleration driven path following (bUseAccelerationForPaths)
uint8 bUpdateNavAgentWithOwnersCollision_DEPRECATED:1
If set to true NavAgentProps' radius and height will be updated with Owner's collision capsule size.
uint8 bUseAccelerationForPaths_DEPRECATED: 1
If set, pathfollowing will control character movement via acceleration values.
uint8 bUseFixedBrakingDistanceForPaths_DEPRECATED: 1
If set, FixedPathBrakingDistance will be used for path following deceleration.
uint8 bStopMovementAbortPaths_DEPRECATED:1
If set, StopActiveMovement call will abort current path following request.
FNavMovementProperties NavMovementProperties
FVector PlaneConstraintNormal
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
FVector PlaneConstraintOrigin
The origin of the plane that constrains movement, if plane constraint is enabled.
Detailed Description
CharacterMovementComponent handles movement logic for the associated Character owner.
It supports various movement modes including: walking, falling, swimming, flying, custom.
Movement is affected primarily by current Velocity and Acceleration. Acceleration is updated each frame based on the input vector accumulated thus far (see UPawnMovementComponent::GetPendingInputVector()).
Networking is fully implemented, with server-client correction and prediction included.
See also
ACharacter, UPawnMovementComponent
https://docs.unrealengine.com/latest/INT/Gameplay/Framework/Pawn/Character/
Definition at line 134 of file CharacterMovementComponent.h.
Member Enumeration Documentation
ERootMotionMapping
enum class UCharacterMovementComponent::ERootMotionMapping : uint32 strong
Collection of the most recent ID mappings.
Enumerator
MapSize
Definition at line 2743 of file CharacterMovementComponent.h.
Constructor & Destructor Documentation
UCharacterMovementComponent()
UCharacterMovementComponent::UCharacterMovementComponent (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
Default UObject constructor.
Member Function Documentation
AccumulateRootMotionForAsync()
virtual void UCharacterMovementComponent::AccumulateRootMotionForAsync (float DeltaSeconds, FRootMotionAsyncData & RootMotion) protected virtual
References AccumulateRootMotionForAsync().
AddForce()
virtual void UCharacterMovementComponent::AddForce (FVector Force) virtual
Add force to character.
Forces are accumulated each tick and applied together so multiple calls to this function will accumulate. Forces are scaled depending on timestep, so they can be applied each frame. If you want an instantaneous force, use AddImpulse. Adding a force always takes the actor's mass into account. Note that changing the momentum of characters like this can change the movement mode.
Parameters
Force Force to apply.
References AddForce().
AddImpulse()
virtual void UCharacterMovementComponent::AddImpulse (FVector Impulse, bool bVelocityChange = false) virtual
Add impulse to character.
Impulses are accumulated each tick and applied together so multiple calls to this function will accumulate. An impulse is an instantaneous force, usually applied once. If you want to continually apply forces each frame, use AddForce(). Note that changing the momentum of characters like this can change the movement mode.
Parameters
Impulse Impulse to apply.
bVelocityChange Whether or not the impulse is relative to mass.
References AddImpulse().
AddInputVector()
virtual void UPawnMovementComponent::AddInputVector (FVector WorldVector, bool bForce = false) virtual inherited
Adds the given vector to the accumulated input in world space.
Input vectors are usually between 0 and 1 in magnitude. They are accumulated during a frame then applied as acceleration during the movement update.
Parameters
WorldVector Direction in world space to apply input
bForce If true always add the input, ignoring the result of IsMoveInputIgnored().
See also
APawn::AddMovementInput()
References AddInputVector().
AddRadialForce()
virtual void UCharacterMovementComponent::AddRadialForce (const FVector & Origin, float Radius, float Strength, enum ERadialImpulseFalloff Falloff) override virtual
Adds force from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
Reimplemented from UMovementComponent.
AddRadialImpulse()
virtual void UCharacterMovementComponent::AddRadialImpulse (const FVector & Origin, float Radius, float Strength, enum ERadialImpulseFalloff Falloff, bool bVelChange) override virtual
Adds impulse from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
bVelChange If true, the Strength is taken as a change in velocity instead of an impulse (ie. mass will have no effect).
Reimplemented from UMovementComponent.
References IsWalking().
AddReferencedObjects()
void UCharacterMovementComponent::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
AdjustFloorHeight()
virtual void UCharacterMovementComponent::AdjustFloorHeight () virtual
Adjust distance from floor, trying to maintain a slight offset from the floor when walking (based on CurrentFloor).
References AdjustFloorHeight().
AdjustProxyCapsuleSize()
virtual void UCharacterMovementComponent::AdjustProxyCapsuleSize () protected virtual
Adjust the size of the capsule on simulated proxies, to avoid overlaps due to replication rounding.
Changes to the capsule size on the proxy should set bShrinkProxyCapsule=true and possibly call AdjustProxyCapsuleSize() immediately if applicable.
References AdjustProxyCapsuleSize().
ApplyAccumulatedForces()
virtual void UCharacterMovementComponent::ApplyAccumulatedForces (float DeltaSeconds) virtual
Applies momentum accumulated through AddImpulse() and AddForce(), then clears those forces.
Does not use ClearAccumulatedForces() since that would clear pending launch velocity as well.
References ApplyAccumulatedForces().
ApplyAsyncOutput()
virtual void UCharacterMovementComponent::ApplyAsyncOutput (FCharacterMovementComponentAsyncOutput & Output) protected virtual
References ApplyAsyncOutput().
ApplyAsyncPhysicsStateAction()
void UPawnMovementComponent::ApplyAsyncPhysicsStateAction (const UPrimitiveComponent * ActionComponent, const FName & BoneName, const EPhysicsStateAction ActionType, const FVector & ActionDatas, const FVector & ActionPosition = FVector::Zero()) inherited
Apply the async physics state action onto the solver.
References EPhysicsStateAction.
ApplyDownwardForce()
virtual void UCharacterMovementComponent::ApplyDownwardForce (float DeltaSeconds) virtual
Applies downward force when walking on top of physics objects.
Parameters
DeltaSeconds Time elapsed since last frame.
References ApplyDownwardForce().
ApplyImpactPhysicsForces()
virtual void UCharacterMovementComponent::ApplyImpactPhysicsForces (const FHitResult & Impact, const FVector & ImpactAcceleration, const FVector & ImpactVelocity) protected virtual
Apply physics forces to the impacted component, if bEnablePhysicsInteraction is true.
Parameters
Impact HitResult that resulted in the impact
ImpactAcceleration Acceleration of the character at the time of impact
ImpactVelocity Velocity of the character at the time of impact
References ApplyImpactPhysicsForces().
ApplyImpartedMovementBaseVelocity()
virtual void UCharacterMovementComponent::ApplyImpartedMovementBaseVelocity () virtual
Apply inherited velocity when leaving base, for example from jumping off it.
References ApplyImpartedMovementBaseVelocity().
ApplyNetworkMovementMode()
virtual void UCharacterMovementComponent::ApplyNetworkMovementMode (const uint8 ReceivedMode) virtual
ApplyRepulsionForce()
virtual void UCharacterMovementComponent::ApplyRepulsionForce (float DeltaSeconds) virtual
Applies repulsion force to all touched components.
References ApplyRepulsionForce().
ApplyRequestedMove()
virtual bool UCharacterMovementComponent::ApplyRequestedMove (float DeltaTime, float MaxAccel, float MaxSpeed, float Friction, float BrakingDeceleration, FVector & OutAcceleration, float & OutRequestedSpeed) virtual
Use velocity requested by path following to compute a requested acceleration and speed.
This does not affect the Acceleration member variable, as that is used to indicate input acceleration. This may directly affect current Velocity.
Parameters
DeltaTime Time slice for this operation
MaxAccel Max acceleration allowed in OutAcceleration result.
MaxSpeed Max speed allowed when computing OutRequestedSpeed.
Friction Current friction.
BrakingDeceleration Current braking deceleration.
OutAcceleration Acceleration computed based on requested velocity.
OutRequestedSpeed Speed of resulting velocity request, which can affect the max speed allowed by movement.
Returns
Whether there is a requested velocity and acceleration, resulting in valid OutAcceleration and OutRequestedSpeed values.
References ApplyRequestedMove().
ApplyRootMotionSource()
uint16 UCharacterMovementComponent::ApplyRootMotionSource (TSharedPtr< FRootMotionSource > SourcePtr)
Apply a RootMotionSource to current root motion.
Returns
LocalID for this Root Motion Source
References ApplyRootMotionSource().
ApplyRootMotionToVelocity()
virtual void UCharacterMovementComponent::ApplyRootMotionToVelocity (float deltaTime) protected virtual
Applies root motion from root motion sources to velocity (override and additive)
ApplyVelocityBraking()
virtual void UCharacterMovementComponent::ApplyVelocityBraking (float DeltaTime, float Friction, float BrakingDeceleration) protected virtual
Slows towards stop.
References ApplyVelocityBraking().
ApplyWorldOffset()
virtual void UCharacterMovementComponent::ApplyWorldOffset (const FVector & InOffset, bool bWorldShift) override virtual
BeginDestroy()
virtual void UCharacterMovementComponent::BeginDestroy () override virtual
BeginPlay()
virtual void UCharacterMovementComponent::BeginPlay () override virtual
BoostAirControl()
virtual float UCharacterMovementComponent::BoostAirControl (float DeltaTime, float TickAirControl, const FVector & FallAcceleration) protected virtual
Increase air control if conditions of AirControlBoostMultiplier and AirControlBoostVelocityThreshold are met.
This function is used internally by GetAirControl().
Parameters
DeltaTime Time step for the current update.
TickAirControl Current air control value.
FallAcceleration Acceleration used during movement.
Returns
Modified air control to use during falling movement
See also
GetAirControl()
BuildAsyncInput()
virtual void UCharacterMovementComponent::BuildAsyncInput () protected virtual
References BuildAsyncInput().
CalcAnimRootMotionVelocity()
virtual FVector UCharacterMovementComponent::CalcAnimRootMotionVelocity (const FVector & RootMotionDeltaMove, float DeltaSeconds, const FVector & CurrentVelocity) const virtual
Calculate velocity from anim root motion.
Parameters
RootMotionDeltaMove Change in location from root motion.
DeltaSeconds Elapsed time
CurrentVelocity Non-root motion velocity at current time, used for components of result that may ignore root motion.
See also
ConstrainAnimRootMotionVelocity
CalcAvoidanceVelocity()
virtual void UCharacterMovementComponent::CalcAvoidanceVelocity (float DeltaTime) virtual
calculate RVO avoidance and apply it to current velocity
CalcVelocity()
virtual void UCharacterMovementComponent::CalcVelocity (float DeltaTime, float Friction, bool bFluid, float BrakingDeceleration) virtual
Updates Velocity and Acceleration based on the current state, applying the effects of friction and acceleration or deceleration.
Does not apply gravity. This is used internally during movement updates. Normally you don't need to call this from outside code, but you might want to use it for custom movement modes.
Parameters
DeltaTime time elapsed since last frame.
Friction coefficient of friction when not accelerating, or in the direction opposite acceleration.
bFluid true if moving through a fluid, causing Friction to always be applied regardless of acceleration.
BrakingDeceleration deceleration applied when not accelerating, or when exceeding max velocity.
References CalcVelocity().
CallMovementUpdateDelegate()
virtual void UCharacterMovementComponent::CallMovementUpdateDelegate (float DeltaSeconds, const FVector & OldLocation, const FVector & OldVelocity) protected virtual
Internal function to call OnMovementUpdated delegate on CharacterOwner.
References CallMovementUpdateDelegate().
CallServerMove()
virtual void UCharacterMovementComponent::CallServerMove (const FSavedMove_Character * NewMove, const FSavedMove_Character * OldMove) protected virtual
Call the appropriate replicated ServerMove() function to send a client player move to the server.
References CallServerMove().
CallServerMovePacked()
virtual void UCharacterMovementComponent::CallServerMovePacked (const FSavedMove_Character * NewMove, const FSavedMove_Character * PendingMove, const FSavedMove_Character * OldMove) protected virtual
On the client, calls the ServerMovePacked_ClientSend() function with packed movement data.
First the FCharacterNetworkMoveDataContainer from GetNetworkMoveDataContainer() is updated with ClientFillNetworkMoveData(), then serialized into a data stream to send client player moves to the server.
References CallServerMovePacked().
CanAttemptJump()
virtual bool UCharacterMovementComponent::CanAttemptJump () const virtual
Returns true if current movement state allows an attempt at jumping.
Used by Character::CanJump().
References CanAttemptJump().
CanCrouchInCurrentState()
virtual bool UCharacterMovementComponent::CanCrouchInCurrentState () const virtual
Returns true if the character is allowed to crouch in the current state.
By default it is allowed when walking or falling, if CanEverCrouch() is true.
CanDelaySendingMove()
virtual bool UCharacterMovementComponent::CanDelaySendingMove (const FSavedMovePtr & NewMove) protected virtual
Return true if it is OK to delay sending this player movement to the server, in order to conserve bandwidth.
References CanDelaySendingMove().
CanEverCrouch()
virtual bool INavMovementInterface::CanEverCrouch () const inline virtual inherited
Returns true if agent can crouch.
Definition at line 149 of file NavMovementInterface.h.
References CanEverCrouch(), and GetNavAgentPropertiesRef().
CanEverFly()
virtual bool INavMovementInterface::CanEverFly () const inline virtual inherited
Returns true if agent can fly.
Definition at line 161 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverJump()
virtual bool INavMovementInterface::CanEverJump () const inline virtual inherited
Returns true if agent can jump.
Definition at line 152 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverMoveOnGround()
virtual bool INavMovementInterface::CanEverMoveOnGround () const inline virtual inherited
Returns true if agent can move along the ground (walk, drive, etc)
Definition at line 155 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanEverSwim()
virtual bool INavMovementInterface::CanEverSwim () const inline virtual inherited
Returns true if agent can swim.
Definition at line 158 of file NavMovementInterface.h.
References GetNavAgentPropertiesRef().
CanStartPathFollowing()
virtual bool UCharacterMovementComponent::CanStartPathFollowing () const override virtual
Returns true if path following can start.
Reimplemented from UNavMovementComponent.
CanStepUp()
virtual bool UCharacterMovementComponent::CanStepUp (const FHitResult & Hit) const virtual
Returns true if we can step up on the actor in the given FHitResult.
References CanStepUp().
CanStopPathFollowing()
virtual bool UCharacterMovementComponent::CanStopPathFollowing () const override virtual
check if current move target can be reached right now if positions are matching (e.g.
performing scripted move and can't stop)
Reimplemented from UNavMovementComponent.
CanWalkOffLedges()
virtual bool UCharacterMovementComponent::CanWalkOffLedges () const virtual
Returns whether this pawn is currently allowed to walk off ledges.
References CanWalkOffLedges().
CapsuleTouched()
virtual void UCharacterMovementComponent::CapsuleTouched (UPrimitiveComponent * OverlappedComp, AActor * Other, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) protected virtual
Called when the collision capsule touches another primitive component.
References CapsuleTouched().
CheckFall()
virtual bool UCharacterMovementComponent::CheckFall (const FFindFloorResult & OldFloor, const FHitResult & Hit, const FVector & Delta, const FVector & OldLocation, float remainingTime, float timeTick, int32 Iterations, bool bMustJump) virtual
Check if pawn is falling.
References CheckFall().
CheckLedgeDirection()
virtual bool UCharacterMovementComponent::CheckLedgeDirection (const FVector & OldLocation, const FVector & SideStep, const FFindFloorResult & OldFloor) const virtual
Returns true if there is a suitable floor SideStep from current position.
References CheckLedgeDirection().
CheckWaterJump()
virtual bool UCharacterMovementComponent::CheckWaterJump (FVector CheckPoint, FVector & WallNormal) virtual
Check if swimming pawn just ran into edge of the pool and should jump out.
References CheckWaterJump().
ClearAccumulatedForces()
virtual void UCharacterMovementComponent::ClearAccumulatedForces () virtual
Clears forces accumulated through AddImpulse() and AddForce(), and also pending launch velocity.
References ClearAccumulatedForces().
ClearFixedBrakingDistance()
void UNavMovementComponent::ClearFixedBrakingDistance () inherited
clears fixed braking distance
ClientAckGoodMove()
virtual void UCharacterMovementComponent::ClientAckGoodMove (float TimeStamp) virtual
If no client adjustment is needed after processing received ServerMove(), ack the good move so client can remove it from SavedMoves.
References ClientAckGoodMove(), ClientAdjustPosition(), ClientHandleMoveResponse(), and DEPRECATED_CHARACTER_MOVEMENT_RPC.
ClientAckGoodMove_Implementation()
virtual void UCharacterMovementComponent::ClientAckGoodMove_Implementation (float TimeStamp) virtual
References ClientAckGoodMove_Implementation().
ClientAdjustPosition()
virtual void UCharacterMovementComponent::ClientAdjustPosition (float TimeStamp, FVector NewLoc, FVector NewVel, UPrimitiveComponent * NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
Replicate position correction to client, associated with a timestamped servermove.
Client will replay subsequent moves after applying adjustment.
References ClientAdjustPosition(), ClientHandleMoveResponse(), ClientVeryShortAdjustPosition(), and DEPRECATED_CHARACTER_MOVEMENT_RPC.
ClientAdjustPosition_Implementation()
virtual void UCharacterMovementComponent::ClientAdjustPosition_Implementation (float TimeStamp, FVector NewLoc, FVector NewVel, UPrimitiveComponent * NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode, TOptional< FRotator > OptionalRotation = TOptional< FRotator >()) virtual
References ClientAdjustPosition_Implementation().
ClientAdjustRootMotionPosition()
virtual void UCharacterMovementComponent::ClientAdjustRootMotionPosition (float TimeStamp, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent * ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
Replicate position correction to client when using root motion for movement.
(animation root motion specific)
References ClientAdjustRootMotionPosition(), ClientAdjustRootMotionSourcePosition(), ClientHandleMoveResponse(), and DEPRECATED_CHARACTER_MOVEMENT_RPC.
ClientAdjustRootMotionPosition_Implementation()
virtual void UCharacterMovementComponent::ClientAdjustRootMotionPosition_Implementation (float TimeStamp, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent * ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
References ClientAdjustRootMotionPosition_Implementation().
ClientAdjustRootMotionSourcePosition()
virtual void UCharacterMovementComponent::ClientAdjustRootMotionSourcePosition (float TimeStamp, FRootMotionSourceGroup ServerRootMotion, bool bHasAnimRootMotion, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent * ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
Replicate root motion source correction to client when using root motion for movement.
References ClientAdjustRootMotionSourcePosition().
ClientAdjustRootMotionSourcePosition_Implementation()
virtual void UCharacterMovementComponent::ClientAdjustRootMotionSourcePosition_Implementation (float TimeStamp, FRootMotionSourceGroup ServerRootMotion, bool bHasAnimRootMotion, float ServerMontageTrackPosition, FVector ServerLoc, FVector_NetQuantizeNormal ServerRotation, float ServerVelZ, UPrimitiveComponent * ServerBase, FName ServerBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
References ClientAdjustRootMotionSourcePosition_Implementation().
ClientHandleMoveResponse()
virtual void UCharacterMovementComponent::ClientHandleMoveResponse (const FCharacterMoveResponseDataContainer & MoveResponse) virtual
On the client, handles the move response from the server after it has been received and unpacked in MoveResponsePacked_ClientReceive.
Based on the data in the response, dispatches a call to ClientAckGoodMove_Implementation if there was no error from the server. Otherwise dispatches a call to one of ClientAdjustRootMotionSourcePosition_Implementation, ClientAdjustRootMotionPosition_Implementation, or ClientAdjustPosition_Implementation depending on the payload.
References ClientHandleMoveResponse(), DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove(), and ServerMovePacked_ClientSend().
ClientUpdatePositionAfterServerUpdate()
virtual bool UCharacterMovementComponent::ClientUpdatePositionAfterServerUpdate () protected virtual
If bUpdatePosition is true, then replay any unacked moves.
Returns whether any moves were actually replayed.
References CallServerMove(), and CallServerMovePacked().
ClientVeryShortAdjustPosition()
virtual void UCharacterMovementComponent::ClientVeryShortAdjustPosition (float TimeStamp, FVector NewLoc, UPrimitiveComponent * NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
References ClientAdjustRootMotionPosition(), ClientHandleMoveResponse(), ClientVeryShortAdjustPosition(), and DEPRECATED_CHARACTER_MOVEMENT_RPC.
ClientVeryShortAdjustPosition_Implementation()
virtual void UCharacterMovementComponent::ClientVeryShortAdjustPosition_Implementation (float TimeStamp, FVector NewLoc, UPrimitiveComponent * NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode) virtual
References ClientVeryShortAdjustPosition_Implementation().
ComputeAnalogInputModifier()
virtual float UCharacterMovementComponent::ComputeAnalogInputModifier () const protected virtual
Computes the analog input modifier based on current input vector and/or acceleration.
References ComputeAnalogInputModifier().
ComputeFloorDist()
virtual void UCharacterMovementComponent::ComputeFloorDist (const FVector & CapsuleLocation, float LineDistance, float SweepDistance, FFindFloorResult & OutFloorResult, float SweepRadius, const FHitResult * DownwardSweepResult = NULL) const virtual
Compute distance to the floor from bottom sphere of capsule and store the result in OutFloorResult.
This distance is the swept distance of the capsule to the first point impacted by the lower hemisphere, or distance from the bottom of the capsule in the case of a line trace. This function does not care if collision is disabled on the capsule (unlike FindFloor).
See also
FindFloor
Parameters
CapsuleLocation Location of the capsule used for the query
LineDistance If non-zero, max distance to test for a simple line check from the capsule base. Used only if the sweep test fails to find a walkable floor, and only returns a valid result if the impact normal is a walkable normal.
SweepDistance If non-zero, max distance to use when sweeping a capsule downwards for the test. MUST be greater than or equal to the line distance.
OutFloorResult Result of the floor check. The HitResult will contain the valid sweep or line test upon success, or the result of the sweep upon failure.
SweepRadius The radius to use for sweep tests. Should be <= capsule radius.
DownwardSweepResult If non-null and it contains valid blocking hit info, this will be used as the result of a downward sweep test instead of doing it as part of the update.
References ComputeFloorDist().
ComputeGroundMovementDelta()
virtual FVector UCharacterMovementComponent::ComputeGroundMovementDelta (const FVector & Delta, const FHitResult & RampHit, const bool bHitFromLineTrace) const protected virtual
Compute a vector of movement, given a delta and a hit result of the surface we are on.
Parameters
Delta Attempted movement direction
RampHit Hit result of sweep that found the ramp below the capsule
bHitFromLineTrace Whether the floor trace came from a line trace
Returns
If on a walkable surface, this returns a vector that moves parallel to the surface. The magnitude may be scaled if bMaintainHorizontalGroundVelocity is true. If a ramp vector can't be computed, this will just return Delta.
References ComputeGroundMovementDelta().
ComputeOrientToMovementRotation()
virtual FRotator UCharacterMovementComponent::ComputeOrientToMovementRotation (const FRotator & CurrentRotation, float DeltaTime, FRotator & DeltaRotation) const virtual
Compute a target rotation based on current movement.
Used by PhysicsRotation() when bOrientRotationToMovement is true. Default implementation targets a rotation based on Acceleration.
Parameters
CurrentRotation - Current rotation of the Character
DeltaTime - Time slice for this movement
DeltaRotation - Proposed rotation change based simply on DeltaTime * RotationRate
Returns
The target rotation given current movement.
References ComputeOrientToMovementRotation().
ComputePerchResult()
virtual bool UCharacterMovementComponent::ComputePerchResult (const float TestRadius, const FHitResult & InHit, const float InMaxFloorDist, FFindFloorResult & OutPerchFloorResult) const virtual
Compute the sweep result of the smaller capsule with radius specified by GetValidPerchRadius(), and return true if the sweep contacts a valid walkable normal within InMaxFloorDist of InHit.ImpactPoint.
This may be used to determine if the capsule can or cannot stay at the current location if perched on the edge of a small ledge or unwalkable surface. Note: Only returns a valid result if ShouldComputePerchResult returned true for the supplied hit value.
Parameters
TestRadius Radius to use for the sweep, usually GetValidPerchRadius().
InHit Result of the last sweep test before the query.
InMaxFloorDist Max distance to floor allowed by perching, from the supplied contact point (InHit.ImpactPoint).
OutPerchFloorResult Contains the result of the perch floor test.
Returns
True if the current location is a valid spot at which to perch.
References ComputePerchResult().
ComputeSlideVector()
virtual FVector UCharacterMovementComponent::ComputeSlideVector (const FVector & Delta, const float Time, const FVector & Normal, const FHitResult & Hit) const override protected virtual
Calculate slide vector along a surface.
Has special treatment when falling, to avoid boosting up slopes (calling HandleSlopeBoosting() in this case).
Parameters
Delta Attempted move.
Time Amount of move to apply (between 0 and 1).
Normal Normal opposed to movement. Not necessarily equal to Hit.Normal (but usually is).
Hit HitResult of the move that resulted in the slide.
Returns
New deflected vector of movement.
Reimplemented from UMovementComponent.
References ComputeSlideVector().
ConstrainAnimRootMotionVelocity()
virtual FVector UCharacterMovementComponent::ConstrainAnimRootMotionVelocity (const FVector & RootMotionVelocity, const FVector & CurrentVelocity) const virtual
Constrain components of root motion velocity that may not be appropriate given the current movement mode (e.g.
when falling Z may be ignored).
ConstrainDirectionToPlane()
virtual FVector UMovementComponent::ConstrainDirectionToPlane (FVector Direction) const virtual inherited
Constrain a direction vector to the plane constraint, if enabled.
See also
SetPlaneConstraint
References ConstrainDirectionToPlane().
ConstrainInputAcceleration()
virtual FVector UCharacterMovementComponent::ConstrainInputAcceleration (const FVector & InputAcceleration) const protected virtual
Enforce constraints on input given current state.
For instance, don't move upwards if walking and looking up.
References ConstrainInputAcceleration().
ConstrainLocationToPlane()
virtual FVector UMovementComponent::ConstrainLocationToPlane (FVector Location) const virtual inherited
Constrain a position vector to the plane constraint, if enabled.
References ConstrainLocationToPlane(), and Location.
ConstrainNormalToPlane()
virtual FVector UMovementComponent::ConstrainNormalToPlane (FVector Normal) const virtual inherited
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
References ConstrainNormalToPlane().
ConsumeInputVector()
virtual FVector UPawnMovementComponent::ConsumeInputVector () virtual inherited
References ConsumeInputVector().
ControlledCharacterMove()
virtual void UCharacterMovementComponent::ControlledCharacterMove (const FVector & InputVector, float DeltaSeconds) protected virtual
Updates acceleration and perform movement, called from the TickComponent on the authoritative side for controlled characters, or on the client for characters without a controller when either playing root motion or bRunPhysicsWithNoController is true.
ConvertLocalRootMotionToWorld()
FTransform UCharacterMovementComponent::ConvertLocalRootMotionToWorld (const FTransform & InLocalRootMotion, float DeltaSeconds)
ConvertRootMotionServerIDsToLocalIDs()
void UCharacterMovementComponent::ConvertRootMotionServerIDsToLocalIDs (const FRootMotionSourceGroup & LocalRootMotionToMatchWith, FRootMotionSourceGroup & InOutServerRootMotion, float TimeStamp)
Converts received server IDs in a root motion group to local IDs.
References ConvertRootMotionServerIDsToLocalIDs().
Crouch()
virtual void UCharacterMovementComponent::Crouch (bool bClientSimulation = false) virtual
Checks if new capsule size fits (no encroachment), and call CharacterOwner->OnStartCrouch() if successful.
In general you should set bWantsToCrouch instead to have the crouch persist during movement, or just use the crouch functions on the owning Character.
Parameters
bClientSimulation true when called when bIsCrouched is replicated to non owned clients, to update collision cylinder and offset.
Deactivate()
virtual void UCharacterMovementComponent::Deactivate () override virtual
Reimplemented from UMovementComponent.
DecayFormerBaseVelocity()
void UCharacterMovementComponent::DecayFormerBaseVelocity (float deltaTime) protected
Reduces former base velocity according to FormerBaseVelocityDecayHalfLife.
DisableMovement()
virtual void UCharacterMovementComponent::DisableMovement () virtual
Make movement impossible (sets movement mode to MOVE_None).
References DisableMovement().
DisplayDebug()
virtual void UCharacterMovementComponent::DisplayDebug (class UCanvas * Canvas, const FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) virtual
Draw important variables on canvas.
Character will call DisplayDebug() on the current ViewTarget when the ShowDebug exec is used
Parameters
Canvas - Canvas to draw on
DebugDisplay - Contains information about what debug data to display
YL - Height of the current font
YPos - Y position on Canvas. YPos += YL, gives position to draw text for next debug line.
References DisplayDebug().
DoJump() [1/2]
virtual bool UCharacterMovementComponent::DoJump (bool bReplayingMoves) virtual
NOTE: THIS FUNCTION IS DEPRECATED, PLEASE CALL DoJump(bool bReplayingMoves, float DeltaTime) ...
References DoJump().
DoJump() [2/2]
virtual bool UCharacterMovementComponent::DoJump (bool bReplayingMoves, float DeltaTime) virtual
Perform jump.
Called by Character when a jump has been detected because Character->bPressedJump was true. Checks Character->CanJump(). Note that you should usually trigger a jump through Character::Jump() instead.
Parameters
bReplayingMoves true if this is being done as part of replaying moves on a locally controlled client after a server correction.
DeltaTime time slice for this jump move
Returns
True if the jump was triggered successfully.
References DoJump().
FillAsyncInput()
virtual void UCharacterMovementComponent::FillAsyncInput (const FVector & InputVector, FCharacterMovementComponentAsyncInput & AsyncInput) protected virtual
References FillAsyncInput().
FindBestNavMeshLocation()
virtual void UCharacterMovementComponent::FindBestNavMeshLocation (const FVector & TraceStart, const FVector & TraceEnd, const FVector & CurrentFeetLocation, const FVector & TargetNavLocation, FHitResult & OutHitResult) const protected virtual
Performs trace for ProjectLocationFromNavMesh.
FindFloor()
virtual void UCharacterMovementComponent::FindFloor (const FVector & CapsuleLocation, FFindFloorResult & OutFloorResult, bool bCanUseCachedLocation, const FHitResult * DownwardSweepResult = NULL) const virtual
Sweeps a vertical trace to find the floor for the capsule at the given location.
Will attempt to perch if ShouldComputePerchResult() returns true for the downward sweep result. No floor will be found if collision is disabled on the capsule!
Parameters
CapsuleLocation Location where the capsule sweep should originate
OutFloorResult [Out] Contains the result of the floor check. The HitResult will contain the valid sweep or line test upon success, or the result of the sweep upon failure.
bCanUseCachedLocation If true, may use a cached value (can be used to avoid unnecessary floor tests, if for example the capsule was not moving since the last test).
DownwardSweepResult If non-null and it contains valid blocking hit info, this will be used as the result of a downward sweep test instead of doing it as part of the update.
References FindFloor().
FindNavFloor()
virtual bool UCharacterMovementComponent::FindNavFloor (const FVector & TestLocation, FNavLocation & NavFloorLocation) const virtual
Project a location to navmesh to find adjusted height.
Parameters
TestLocation Location to project
NavFloorLocation Location on navmesh
Returns
True if projection was performed (successfully or not)
References FindNavFloor().
FindWaterLine()
FVector UCharacterMovementComponent::FindWaterLine (FVector Start, FVector End)
Get as close to waterline as possible, staying on same side as currently.
References FindWaterLine(), and Start.
FloorSweepTest()
virtual bool UCharacterMovementComponent::FloorSweepTest (struct FHitResult & OutHit, const FVector & Start, const FVector & End, ECollisionChannel TraceChannel, const struct FCollisionShape & CollisionShape, const struct FCollisionQueryParams & Params, const struct FCollisionResponseParams & ResponseParam) const virtual
Sweep against the world and return the first blocking hit.
Intended for tests against the floor, because it may change the result of impacts on the lower area of the test (especially if bUseFlatBaseForFloorChecks is true).
Parameters
OutHit First blocking hit found.
Start Start location of the capsule.
End End location of the capsule.
TraceChannel The 'channel' that this trace is in, used to determine which components to hit.
CollisionShape Capsule collision shape.
Params Additional parameters used for the trace.
ResponseParam ResponseContainer to be used for this trace.
Returns
True if OutHit contains a blocking hit entry.
References FloorSweepTest(), and Start.
FlushServerMoves()
virtual void UCharacterMovementComponent::FlushServerMoves () virtual
ForceClientAdjustment()
void UCharacterMovementComponent::ForceClientAdjustment ()
Force a client adjustment.
Resets ServerLastClientAdjustmentTime.
ForcePositionUpdate()
virtual bool UCharacterMovementComponent::ForcePositionUpdate (float DeltaTime) override virtual
ForceReplicationUpdate()
virtual void UCharacterMovementComponent::ForceReplicationUpdate () virtual
Force a client update by making it appear on the server that the client hasn't updated in a long time.
GetActorFeetLocation()
virtual FVector UCharacterMovementComponent::GetActorFeetLocation () const override virtual
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
Reimplemented from UNavMovementComponent.
GetActorFeetLocationBased()
virtual FBasedPosition UNavMovementComponent::GetActorFeetLocationBased () const virtual inherited
Returns based location of controlled actor.
GetActorLocation()
FVector UNavMovementComponent::GetActorLocation () const inline inherited
Returns location of controlled actor - meaning center of collision bounding box.
Definition at line 102 of file NavMovementComponent.h.
GetActorNavLocation()
FVector UNavMovementComponent::GetActorNavLocation () const inline inherited
Returns navigation location of controlled actor.
Definition at line 108 of file NavMovementComponent.h.
GetActorTransform()
FTransform UNavMovementComponent::GetActorTransform () const inline inherited
Returns the full world-coordinates transform of the associated scene component (the UpdatedComponent)
Definition at line 110 of file NavMovementComponent.h.
GetAirControl()
virtual FVector UCharacterMovementComponent::GetAirControl (float DeltaTime, float TickAirControl, const FVector & FallAcceleration) virtual
Get the air control to use during falling movement.
Given an initial air control (TickAirControl), applies the result of BoostAirControl(). This function is used internally by GetFallingLateralAcceleration().
Parameters
DeltaTime Time step for the current update.
TickAirControl Current air control value.
FallAcceleration Acceleration used during movement.
Returns
Air control to use during falling movement.
See also
AirControl, BoostAirControl(), LimitAirControl(), GetFallingLateralAcceleration()
References GetAirControl().
GetAnalogInputModifier()
float UCharacterMovementComponent::GetAnalogInputModifier () const
Returns modifier [0..1] based on the magnitude of the last input vector, which is used to modify the acceleration and max speed during movement.
References GetAnalogInputModifier().
GetAvoidanceGroupMask()
virtual int32 UCharacterMovementComponent::GetAvoidanceGroupMask () override virtual
GetBestDirectionOffActor()
virtual FVector UCharacterMovementComponent::GetBestDirectionOffActor (AActor * BaseActor) const virtual
Can be overridden to choose to jump based on character velocity, base actor dimensions, etc.
References GetBestDirectionOffActor().
GetCharacterOwner()
ACharacter * UCharacterMovementComponent::GetCharacterOwner () const inline
Get the Character that owns UpdatedComponent.
Definition at line 2870 of file CharacterMovementComponent.h.
References CharacterOwner.
GetClientNetSendDeltaTime()
virtual float UCharacterMovementComponent::GetClientNetSendDeltaTime (const APlayerController * PC, const FNetworkPredictionData_Client_Character * ClientData, const FSavedMovePtr & NewMove) const protected virtual
Determine minimum delay between sending client updates to the server.
If updates occur more frequently this than this time, moves may be combined delayed.
References GetClientNetSendDeltaTime().
GetController()
virtual AController * UPawnMovementComponent::GetController () const protected virtual inherited
Returns this component's associated controller, typically from the owning Pawn.
May be null. May be overridden for special handling when the controller isn't paired with the Pawn that owns this component.
References GetController().
GetCrouchedHalfHeight()
float UCharacterMovementComponent::GetCrouchedHalfHeight () const
Returns the collision half-height when crouching (component scale is applied separately)
References GetCrouchedHalfHeight().
GetCurrentAcceleration()
FVector UCharacterMovementComponent::GetCurrentAcceleration () const
Returns current acceleration, computed from input vector each update.
References GetCurrentAcceleration().
GetCurrentNetworkMoveData()
FCharacterNetworkMoveData * UCharacterMovementComponent::GetCurrentNetworkMoveData () const inline protected
Current move data being processed or handled.
This is set before MoveAutonomous (for replayed moves and server moves), and cleared thereafter. Useful for being able to access custom movement data during internal movement functions such as MoveAutonomous() or UpdateFromCompressedFlags() to be able to maintain backwards API compatibility.
Definition at line 2630 of file CharacterMovementComponent.h.
GetCurrentReplayedSavedMove()
const FSavedMove_Character * UCharacterMovementComponent::GetCurrentReplayedSavedMove () const inline
Gets the SavedMove being replayed on the client after a correction is received.
See also
: ClientUpdatePositionAfterServerUpdate
Definition at line 2663 of file CharacterMovementComponent.h.
GetDeltaRotation()
virtual FRotator UCharacterMovementComponent::GetDeltaRotation (float DeltaTime) const virtual
Returns how far to rotate character during the time interval DeltaTime.
References GetDeltaRotation().
GetFallingLateralAcceleration()
virtual FVector UCharacterMovementComponent::GetFallingLateralAcceleration (float DeltaTime) virtual
Get the lateral acceleration to use during falling movement.
The Z component of the result is ignored. Default implementation returns current Acceleration value modified by GetAirControl(), with Z component removed, with magnitude clamped to GetMaxAcceleration(). This function is used internally by PhysFalling().
Parameters
DeltaTime Time step for the current update.
Returns
Acceleration to use during falling movement.
References GetFallingLateralAcceleration().
GetFeetLocation()
virtual FVector UNavMovementComponent::GetFeetLocation () const inline override virtual inherited
Returns location of controlled actor's "feet" meaning center of bottom of collision bounding box.
Implements INavMovementInterface.
Definition at line 115 of file NavMovementComponent.h.
References GetActorFeetLocation().
GetFeetLocationBased()
virtual FBasedPosition UNavMovementComponent::GetFeetLocationBased () const inline override virtual inherited
Returns based location of controlled actor.
Implements INavMovementInterface.
Definition at line 117 of file NavMovementComponent.h.
References GetActorFeetLocationBased().
GetForwardVector()
virtual FVector UNavMovementComponent::GetForwardVector () const override virtual inherited
Get forward vector of the object being driven by nav movement.
Implements INavMovementInterface.
GetGravityDirection()
FVector UCharacterMovementComponent::GetGravityDirection () const inline
Returns the current gravity direction.
Definition at line 1666 of file CharacterMovementComponent.h.
References GetGravityDirection().
GetGravitySpaceComponentZ()
FVector UCharacterMovementComponent::GetGravitySpaceComponentZ (const FVector & Vector) const inline
Returns the component of the vector in the gravity-space vertical direction.
Definition at line 1687 of file CharacterMovementComponent.h.
References GetGravityDirection().
GetGravitySpaceZ()
FVector::FReal UCharacterMovementComponent::GetGravitySpaceZ (const FVector & Vector) const inline
Returns the size of a vector in the gravity-space vertical direction.
Definition at line 1684 of file CharacterMovementComponent.h.
References GetGravityDirection().
GetGravityToWorldTransform()
FQuat UCharacterMovementComponent::GetGravityToWorldTransform () const inline
Returns a quaternion transforming from gravity to world space.
Definition at line 1672 of file CharacterMovementComponent.h.
GetGravityZ()
virtual float UCharacterMovementComponent::GetGravityZ () const override virtual
Returns gravity that affects this component.
Reimplemented from UMovementComponent.
GetGroundMovementMode()
EMovementMode UCharacterMovementComponent::GetGroundMovementMode () const inline
Get current GroundMovementMode value.
Returns
current GroundMovementMode
See also
GroundMovementMode, SetGroundMovementMode()
Definition at line 1260 of file CharacterMovementComponent.h.
References GetGroundMovementMode().
GetGroupsToAvoidMask()
virtual int32 UCharacterMovementComponent::GetGroupsToAvoidMask () override virtual
GetGroupsToIgnoreMask()
virtual int32 UCharacterMovementComponent::GetGroupsToIgnoreMask () override virtual
GetImpartedMovementBaseVelocity()
virtual FVector UCharacterMovementComponent::GetImpartedMovementBaseVelocity () const virtual
If we have a movement base, get the velocity that should be imparted by that base, usually when jumping off of it.
Only applies the components of the velocity enabled by bImpartBaseVelocityX, bImpartBaseVelocityY, bImpartBaseVelocityZ.
References GetImpartedMovementBaseVelocity().
GetLastInputVector()
FVector UPawnMovementComponent::GetLastInputVector () const inherited
Return the last input vector in world space that was processed by ConsumeInputVector(), which is usually done by the Pawn or PawnMovementComponent.
Any user that needs to know about the input that last affected movement should use this function.
Returns
The last input vector in world space that was processed by ConsumeInputVector().
See also
AddInputVector(), ConsumeInputVector(), GetPendingInputVector()
References GetLastInputVector().
GetLastServerMovementBase()
UPrimitiveComponent * UCharacterMovementComponent::GetLastServerMovementBase () const inline
Accessor to the Last Server Movement Base, only relevant during server update.
Definition at line 895 of file CharacterMovementComponent.h.
References GetLastServerMovementBase().
GetLastUpdateLocation()
FVector UCharacterMovementComponent::GetLastUpdateLocation () const inline
Returns the location at the end of the last tick.
Definition at line 701 of file CharacterMovementComponent.h.
References GetLastUpdateLocation(), and LastUpdateLocation.
GetLastUpdateQuat()
FQuat UCharacterMovementComponent::GetLastUpdateQuat () const inline
Returns the rotation Quat at the end of the last tick.
Definition at line 708 of file CharacterMovementComponent.h.
References LastUpdateRotation.
GetLastUpdateRequestedVelocity()
FVector UCharacterMovementComponent::GetLastUpdateRequestedVelocity () const
Returns velocity requested by path following.
References GetLastUpdateRequestedVelocity().
GetLastUpdateRotation()
FRotator UCharacterMovementComponent::GetLastUpdateRotation () const inline
Returns the rotation at the end of the last tick.
Definition at line 705 of file CharacterMovementComponent.h.
References GetLastUpdateRotation(), and LastUpdateRotation.
GetLastUpdateVelocity()
FVector UCharacterMovementComponent::GetLastUpdateVelocity () const inline
Returns the velocity at the end of the last tick.
Definition at line 712 of file CharacterMovementComponent.h.
References GetLastUpdateVelocity(), and LastUpdateVelocity.
GetLedgeMove()
virtual FVector UCharacterMovementComponent::GetLedgeMove (const FVector & OldLocation, const FVector & Delta, const FFindFloorResult & OldFloor) const virtual
Parameters
Delta is the current move delta (which ended up going over a ledge).
Returns
new delta which moves along the ledge
References GetLedgeMove().
GetLocation()
virtual FVector UNavMovementComponent::GetLocation () const inline override virtual inherited
Returns location of controlled actor - meaning center of collision bounding box.
Implements INavMovementInterface.
Definition at line 113 of file NavMovementComponent.h.
References GetActorLocation().
GetMaxAcceleration()
virtual float UCharacterMovementComponent::GetMaxAcceleration () const virtual
Returns maximum acceleration for the current state.
References GetMaxAcceleration().
GetMaxBrakingDeceleration()
virtual float UCharacterMovementComponent::GetMaxBrakingDeceleration () const virtual
Returns maximum deceleration for the current state when braking (ie when there is no acceleration).
References GetMaxBrakingDeceleration().
GetMaxJumpHeight()
virtual float UCharacterMovementComponent::GetMaxJumpHeight () const virtual
Compute the max jump height based on the JumpZVelocity velocity and gravity.
This does not take into account the CharacterOwner's MaxJumpHoldTime.
References GetMaxJumpHeight().
GetMaxJumpHeightWithJumpTime()
virtual float UCharacterMovementComponent::GetMaxJumpHeightWithJumpTime () const virtual
Compute the max jump height based on the JumpZVelocity velocity and gravity.
This does take into account the CharacterOwner's MaxJumpHoldTime.
References GetMaxJumpHeightWithJumpTime().
GetMaxSpeed()
virtual float UCharacterMovementComponent::GetMaxSpeed () const override virtual
Returns maximum speed of component in current movement mode.
Reimplemented from UMovementComponent.
GetMaxSpeedForNavMovement()
virtual float UNavMovementComponent::GetMaxSpeedForNavMovement () const inline override virtual inherited
Get maximum movement speed of the agent.
Implements INavMovementInterface.
Definition at line 93 of file NavMovementComponent.h.
References UMovementComponent::GetMaxSpeed().
GetMinAnalogSpeed()
virtual float UCharacterMovementComponent::GetMinAnalogSpeed () const virtual
Returns maximum acceleration for the current state.
References GetMinAnalogSpeed().
GetMovementBase()
UPrimitiveComponent * UCharacterMovementComponent::GetMovementBase () const
Return PrimitiveComponent we are based on (standing and walking on).
References GetMovementBase().
GetMovementName()
virtual FString UCharacterMovementComponent::GetMovementName () const virtual
Returns MovementMode string.
References GetMovementName().
GetMoveResponseDataContainer()
FCharacterMoveResponseDataContainer & UCharacterMovementComponent::GetMoveResponseDataContainer () const inline protected
Get the struct used for server response RPC serialization.
See also
SetMoveResponseDataContainer(), ClientHandleMoveResponse(), ServerSendMoveResponse().
Definition at line 2649 of file CharacterMovementComponent.h.
GetNavAgentPropertiesRef() [1/2]
const FNavAgentProperties & UNavMovementComponent::GetNavAgentPropertiesRef () const inline override virtual inherited
Returns the NavAgentProps(const)
Implements INavMovementInterface.
Definition at line 151 of file NavMovementComponent.h.
References NavAgentProps.
GetNavAgentPropertiesRef() [2/2]
FNavAgentProperties & UNavMovementComponent::GetNavAgentPropertiesRef () inline override virtual inherited
Returns the NavAgentProps.
Implements INavMovementInterface.
Definition at line 153 of file NavMovementComponent.h.
References NavAgentProps.
GetNavData()
const class INavigationDataInterface * UCharacterMovementComponent::GetNavData () const protected
Get Navigation data for the Character.
Returns null if there is no associated nav data.
GetNavLocation()
UE_API FVector INavMovementInterface::GetNavLocation () const inherited
Returns navigation location of controlled agent.
References GetNavLocation(), and UE_API.
GetNavMovementProperties() [1/2]
virtual const FNavMovementProperties & UNavMovementComponent::GetNavMovementProperties () const inline override virtual inherited
Returns the NavMovementProps(const)
Implements INavMovementInterface.
Definition at line 141 of file NavMovementComponent.h.
References NavMovementProperties.
GetNavMovementProperties() [2/2]
virtual FNavMovementProperties * UNavMovementComponent::GetNavMovementProperties () inline override virtual inherited
Get Nav movement props struct this component uses.
Implements INavMovementInterface.
Definition at line 139 of file NavMovementComponent.h.
References NavMovementProperties.
GetNetworkMoveDataContainer()
FCharacterNetworkMoveDataContainer & UCharacterMovementComponent::GetNetworkMoveDataContainer () const inline protected
Get the struct used for client to server move RPC serialization.
See also
SetNetworkMoveDataContainer()
Definition at line 2623 of file CharacterMovementComponent.h.
GetNetworkSafeRandomAngleDegrees()
virtual float UCharacterMovementComponent::GetNetworkSafeRandomAngleDegrees () const virtual
Generate a random angle in degrees that is approximately equal between client and server.
Note that in networked games this result changes with low frequency and has a low period, so should not be used for frequent randomization.
GetOwnerAsObject()
virtual UObject * UNavMovementComponent::GetOwnerAsObject () const inline override virtual inherited
Get the owner of the object consuming nav movement.
Implements INavMovementInterface.
Definition at line 75 of file NavMovementComponent.h.
References GetOwnerAsObject().
GetPathFollowingAgent() [1/2]
virtual const IPathFollowingAgentInterface * UNavMovementComponent::GetPathFollowingAgent () const inline override virtual inherited
Get path following agent this interface uses(const)
Implements INavMovementInterface.
Definition at line 148 of file NavMovementComponent.h.
GetPathFollowingAgent() [2/2]
virtual IPathFollowingAgentInterface * UNavMovementComponent::GetPathFollowingAgent () inline override virtual inherited
Get path following agent this interface uses.
Implements INavMovementInterface.
Definition at line 147 of file NavMovementComponent.h.
GetPathFollowingBrakingDistance()
virtual float UCharacterMovementComponent::GetPathFollowingBrakingDistance (float MaxSpeed) const override virtual
Returns braking distance for acceleration driven path following.
Reimplemented from INavMovementInterface.
GetPawnCapsuleCollisionShape()
FCollisionShape UCharacterMovementComponent::GetPawnCapsuleCollisionShape (const EShrinkCapsuleExtent ShrinkMode, const float CustomShrinkAmount = 0.f) const protected
Get the collision shape for the Pawn owner, possibly reduced in size depending on ShrinkMode.
Parameters
ShrinkMode Controls the way the capsule is resized.
CustomShrinkAmount The amount to shrink the capsule, used only for ShrinkModes that specify custom.
Returns
The capsule extent of the Pawn owner, possibly reduced in size depending on ShrinkMode.
References GetPawnCapsuleCollisionShape().
GetPawnCapsuleExtent()
FVector UCharacterMovementComponent::GetPawnCapsuleExtent (const EShrinkCapsuleExtent ShrinkMode, const float CustomShrinkAmount = 0.f) const protected
Get the capsule extent for the Pawn owner, possibly reduced in size depending on ShrinkMode.
Parameters
ShrinkMode Controls the way the capsule is resized.
CustomShrinkAmount The amount to shrink the capsule, used only for ShrinkModes that specify custom.
Returns
The capsule extent of the Pawn owner, possibly reduced in size depending on ShrinkMode.
References GetPawnCapsuleExtent().
GetPawnOwner()
class APawn * UPawnMovementComponent::GetPawnOwner () const inherited
Return the Pawn that owns UpdatedComponent.
References GetPawnOwner().
GetPendingInputVector()
FVector UPawnMovementComponent::GetPendingInputVector () const inherited
Return the pending input vector in world space.
This is the most up-to-date value of the input vector, pending ConsumeMovementInputVector() which clears it. PawnMovementComponents implementing movement usually want to use either this or ConsumeInputVector() as these functions represent the most recent state of input.
Returns
The pending input vector in world space.
See also
AddInputVector(), ConsumeInputVector(), GetLastInputVector()
References GetPendingInputVector().
GetPenetrationAdjustment()
virtual FVector UCharacterMovementComponent::GetPenetrationAdjustment (const FHitResult & Hit) const override protected virtual
Overridden to enforce max distances based on hit geometry.
Reimplemented from UMovementComponent.
References GetPenetrationAdjustment().
GetPerchRadiusThreshold()
float UCharacterMovementComponent::GetPerchRadiusThreshold () const
Returns The distance from the edge of the capsule within which we don't allow the character to perch on the edge of a surface.
References GetPerchRadiusThreshold().
GetPhysicsVolume()
virtual APhysicsVolume * UMovementComponent::GetPhysicsVolume () const virtual inherited
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
References GetPhysicsVolume().
GetPlaneConstraintAxisSetting()
EPlaneConstraintAxisSetting UMovementComponent::GetPlaneConstraintAxisSetting () const inline inherited
Get the plane constraint axis setting.
Definition at line 477 of file MovementComponent.h.
References EPlaneConstraintAxisSetting.
GetPlaneConstraintNormal()
const FVector & UMovementComponent::GetPlaneConstraintNormal () const inherited
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
References GetPlaneConstraintNormal().
GetPlaneConstraintNormalFromAxisSetting()
FVector UMovementComponent::GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const protected inherited
Helper to compute the plane constraint axis from the current setting.
Parameters
AxisSetting Setting to use when computing the axis.
Returns
Plane constraint axis/normal.
References EPlaneConstraintAxisSetting, and GetPlaneConstraintNormalFromAxisSetting().
GetPlaneConstraintOrigin()
const FVector & UMovementComponent::GetPlaneConstraintOrigin () const inherited
Get the plane constraint origin.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
Returns
The origin of the plane that constrains movement, if the plane constraint is enabled.
References GetPlaneConstraintOrigin().
GetPredictionData_Client()
virtual class FNetworkPredictionData_Client * UCharacterMovementComponent::GetPredictionData_Client () const override virtual
Get prediction data for a client game.
Should not be used if not running as a client. Allocates the data on demand and can be overridden to allocate a custom override if desired. Result must be a FNetworkPredictionData_Client_Character.
GetPredictionData_Client_Character()
class FNetworkPredictionData_Client_Character * UCharacterMovementComponent::GetPredictionData_Client_Character () const
GetPredictionData_Server()
virtual class FNetworkPredictionData_Server * UCharacterMovementComponent::GetPredictionData_Server () const override virtual
Get prediction data for a server game.
Should not be used if not running as a server. Allocates the data on demand and can be overridden to allocate a custom override if desired. Result must be a FNetworkPredictionData_Server_Character.
GetPredictionData_Server_Character()
class FNetworkPredictionData_Server_Character * UCharacterMovementComponent::GetPredictionData_Server_Character () const
GetRootMotionSource()
TSharedPtr< FRootMotionSource > UCharacterMovementComponent::GetRootMotionSource (FName InstanceName)
Get a RootMotionSource from current root motion by name.
References GetRootMotionSource().
GetRootMotionSourceByID()
TSharedPtr< FRootMotionSource > UCharacterMovementComponent::GetRootMotionSourceByID (uint16 RootMotionSourceID)
Get a RootMotionSource from current root motion by ID.
References GetRootMotionSourceByID().
GetRVOAvoidanceConsiderationRadius()
virtual float UCharacterMovementComponent::GetRVOAvoidanceConsiderationRadius () override virtual
GetRVOAvoidanceHeight()
virtual float UCharacterMovementComponent::GetRVOAvoidanceHeight () override virtual
GetRVOAvoidanceOrigin()
virtual FVector UCharacterMovementComponent::GetRVOAvoidanceOrigin () override virtual
GetRVOAvoidanceRadius()
virtual float UCharacterMovementComponent::GetRVOAvoidanceRadius () override virtual
GetRVOAvoidanceUID()
virtual int32 UCharacterMovementComponent::GetRVOAvoidanceUID () override virtual
GetRVOAvoidanceUIDFast()
int32 UCharacterMovementComponent::GetRVOAvoidanceUIDFast () const inline
END IRVOAvoidanceInterface.
a shortcut function to be called instead of GetRVOAvoidanceUID when callee knows it's dealing with a char movement comp
Definition at line 2849 of file CharacterMovementComponent.h.
References AvoidanceUID.
GetRVOAvoidanceWeight()
virtual float UCharacterMovementComponent::GetRVOAvoidanceWeight () override virtual
GetServerLastTransformUpdateTimeStamp()
float UCharacterMovementComponent::GetServerLastTransformUpdateTimeStamp () const inline
Get the value of ServerLastTransformUpdateTimeStamp.
Definition at line 715 of file CharacterMovementComponent.h.
References ServerLastTransformUpdateTimeStamp.
GetSimpleCollisionCylinder()
virtual void UNavMovementComponent::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const override virtual inherited
Get axis-aligned cylinder around this actor, used for simple collision checks in nav movement.
Implements INavMovementInterface.
GetSimpleCollisionCylinderExtent()
virtual FVector UNavMovementComponent::GetSimpleCollisionCylinderExtent () const override virtual inherited
Returns collision extents vector for this object, based on GetSimpleCollisionCylinder.
Implements INavMovementInterface.
GetSimulationTimeStep()
float UCharacterMovementComponent::GetSimulationTimeStep (float RemainingTime, int32 Iterations) const
Compute remaining time step given remaining time and current iterations.
The last iteration (limited by MaxSimulationIterations) always returns the remaining time, which may violate MaxSimulationTimeStep.
Parameters
RemainingTime Remaining time in the tick.
Iterations Current iteration of the tick (starting at 1).
Returns
The remaining time step to use for the next sub-step of iteration.
See also
MaxSimulationTimeStep, MaxSimulationIterations
GetTeleportType()
ETeleportType UCharacterMovementComponent::GetTeleportType () const
When moving the character, we should inform physics as to whether we are teleporting.
This allows physics to avoid injecting forces into simulations from client corrections (etc.)
GetUpdatedObject()
virtual TObjectPtr< UObject > UNavMovementComponent::GetUpdatedObject () const inline override virtual inherited
Get the component this movement component is updating.
Implements INavMovementInterface.
Definition at line 78 of file NavMovementComponent.h.
GetValidPerchRadius()
float UCharacterMovementComponent::GetValidPerchRadius () const
Returns the radius within which we can stand on the edge of a surface without falling (if this is a walkable surface).
Simply computed as the capsule radius minus the result of GetPerchRadiusThreshold().
References GetValidPerchRadius().
GetVelocityForNavMovement()
virtual FVector UNavMovementComponent::GetVelocityForNavMovement () const inline override virtual inherited
Get the current velocity of the movement component.
Implements INavMovementInterface.
Definition at line 91 of file NavMovementComponent.h.
References GetVelocityForNavMovement().
GetVelocityForRVOConsideration()
virtual FVector UCharacterMovementComponent::GetVelocityForRVOConsideration () override virtual
GetWalkableFloorAngle()
float UCharacterMovementComponent::GetWalkableFloorAngle () const inline
Get the max angle in degrees of a walkable surface for the character.
Definition at line 1903 of file CharacterMovementComponent.h.
References GetWalkableFloorAngle().
GetWalkableFloorZ()
float UCharacterMovementComponent::GetWalkableFloorZ () const inline
Get the Z component of the normal of the steepest walkable surface for the character.
Any lower than this and it is not walkable.
Definition at line 1914 of file CharacterMovementComponent.h.
References GetWalkableFloorZ().
GetWorldToGravityTransform()
FQuat UCharacterMovementComponent::GetWorldToGravityTransform () const inline
Returns a quaternion transforming from world to gravity space.
Definition at line 1669 of file CharacterMovementComponent.h.
HandleImpact()
virtual void UCharacterMovementComponent::HandleImpact (const FHitResult & Hit, float TimeSlice = 0.f, const FVector & MoveDelta = FVector::ZeroVector) override protected virtual
Handle a blocking impact.
Calls ApplyImpactPhysicsForces for the hit, if bEnablePhysicsInteraction is true.
Reimplemented from UMovementComponent.
References HandleImpact().
HandlePendingLaunch()
virtual bool UCharacterMovementComponent::HandlePendingLaunch () virtual
Handle a pending launch during an update.
Returns true if the launch was triggered.
References HandlePendingLaunch().
HandleSlopeBoosting()
virtual FVector UCharacterMovementComponent::HandleSlopeBoosting (const FVector & SlideResult, const FVector & Delta, const float Time, const FVector & Normal, const FHitResult & Hit) const protected virtual
Limit the slide vector when falling if the resulting slide might boost the character faster upwards.
Parameters
SlideResult Vector of movement for the slide (usually the result of ComputeSlideVector)
Delta Original attempted move
Time Amount of move to apply (between 0 and 1).
Normal Normal opposed to movement. Not necessarily equal to Hit.Normal (but usually is).
Hit HitResult of the move that resulted in the slide.
Returns
: New slide result.
References HandleSlopeBoosting().
HandleSwimmingWallHit()
virtual void UCharacterMovementComponent::HandleSwimmingWallHit (const FHitResult & Hit, float DeltaTime) protected virtual
References HandleSwimmingWallHit().
HandleWalkingOffLedge()
virtual void UCharacterMovementComponent::HandleWalkingOffLedge (const FVector & PreviousFloorImpactNormal, const FVector & PreviousFloorContactNormal, const FVector & PreviousLocation, float TimeDelta) virtual
Trigger OnWalkingOffLedge event on CharacterOwner.
References HandleWalkingOffLedge().
HasAnimRootMotion()
bool UCharacterMovementComponent::HasAnimRootMotion () const inline
Returns true if we have Root Motion from animation to use in PerformMovement() physics.
Not valid outside of the scope of that function. Since RootMotion is extracted and used in it.
Definition at line 2773 of file CharacterMovementComponent.h.
References HasAnimRootMotion(), and RootMotionParams.
HasCustomGravity()
bool UCharacterMovementComponent::HasCustomGravity () const inline
Whether the gravity direction is different from UCharacterMovementComponent::DefaultGravityDirection.
Definition at line 1662 of file CharacterMovementComponent.h.
References HasCustomGravity().
HasPredictionData_Client()
virtual bool UCharacterMovementComponent::HasPredictionData_Client () const override virtual
HasPredictionData_Server()
virtual bool UCharacterMovementComponent::HasPredictionData_Server () const override virtual
HasRootMotionSources()
bool UCharacterMovementComponent::HasRootMotionSources () const
Returns true if we have Root Motion from any source to use in PerformMovement() physics.
References HasRootMotionSources().
HasValidData()
virtual bool UCharacterMovementComponent::HasValidData () const virtual
Return true if we have a valid CharacterOwner and UpdatedComponent.
References HasValidData().
ImmersionDepth()
virtual float UCharacterMovementComponent::ImmersionDepth () const virtual
References ImmersionDepth().
InitCollisionParams()
virtual void UMovementComponent::InitCollisionParams (FCollisionQueryParams & OutParams, FCollisionResponseParams & OutResponseParam) const virtual inherited
Initialize collision params appropriately based on our collision settings.
Use this before any Line, Overlap, or Sweep tests.
References InitCollisionParams().
InitializeComponent()
virtual void UMovementComponent::InitializeComponent () override virtual inherited
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
Reimplemented in UProjectileMovementComponent.
IsAsyncCallbackRegistered()
virtual bool UCharacterMovementComponent::IsAsyncCallbackRegistered () const protected virtual
References IsAsyncCallbackRegistered().
IsClientTimeStampValid()
bool UCharacterMovementComponent::IsClientTimeStampValid (float TimeStamp, const FNetworkPredictionData_Server_Character & ServerData, bool & bTimeStampResetDetected) const protected
Internal const check for client timestamp validity without side-effects.
See also
VerifyClientTimeStamp
References IsClientTimeStampValid().
IsCrouching()
virtual bool UCharacterMovementComponent::IsCrouching () const override virtual
Returns true if currently crouching.
Reimplemented from UNavMovementComponent.
IsExceedingMaxSpeed()
virtual bool UMovementComponent::IsExceedingMaxSpeed (float MaxSpeed) const virtual inherited
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
Note that under normal circumstances updates cause by acceleration will not cause this to be true, however external forces or changes in the max speed limit can cause the max speed to be violated.
References IsExceedingMaxSpeed(), and StopMovementImmediately().
IsFalling()
virtual bool UCharacterMovementComponent::IsFalling () const override virtual
Returns true if currently falling (not flying, in a non-fluid volume, and not on the ground)
Reimplemented from UNavMovementComponent.
IsFlying()
virtual bool UCharacterMovementComponent::IsFlying () const override virtual
Returns true if currently flying (moving through a non-fluid volume without resting on the ground)
Reimplemented from UNavMovementComponent.
IsInWater()
virtual bool UMovementComponent::IsInWater () const virtual inherited
Returns true if it's in PhysicsVolume with water flag.
References IsInWater().
IsJumpAllowed()
bool UNavMovementComponent::IsJumpAllowed () const inline inherited
Returns true if component is allowed to jump.
Definition at line 162 of file NavMovementComponent.h.
References INavMovementInterface::CanEverJump(), and MovementState.
IsMoveInputIgnored()
virtual bool UPawnMovementComponent::IsMoveInputIgnored () const virtual inherited
Helper to see if move input is ignored.
If there is no Pawn or UpdatedComponent, returns true, otherwise defers to the Pawn's implementation of IsMoveInputIgnored().
References IsMoveInputIgnored().
IsMovementInProgress()
bool UCharacterMovementComponent::IsMovementInProgress () const inline
Returns true if currently performing a movement update.
See also
bMovementInProgress
Definition at line 1310 of file CharacterMovementComponent.h.
References bMovementInProgress, and IsMovementInProgress().
IsMovingOnGround()
virtual bool UCharacterMovementComponent::IsMovingOnGround () const override virtual
Returns true if currently moving on the ground (e.g.
walking or driving)
Reimplemented from UNavMovementComponent.
IsSwimming()
virtual bool UCharacterMovementComponent::IsSwimming () const override virtual
Returns true if currently swimming (moving through a fluid volume)
Reimplemented from UNavMovementComponent.
IsValidLandingSpot()
virtual bool UCharacterMovementComponent::IsValidLandingSpot (const FVector & CapsuleLocation, const FHitResult & Hit) const virtual
Verify that the supplied hit result is a valid landing spot when falling.
References IsValidLandingSpot().
IsWalkable()
virtual bool UCharacterMovementComponent::IsWalkable (const FHitResult & Hit) const virtual
Return true if the hit result should be considered a walkable surface for the character.
References IsWalkable().
IsWalking()
FORCEINLINE_DEBUGGABLE bool UCharacterMovementComponent::IsWalking () const
Returns true if the character is in the 'Walking' movement mode.
Definition at line 2875 of file CharacterMovementComponent.h.
References IsMovingOnGround().
IsWithinEdgeTolerance()
virtual bool UCharacterMovementComponent::IsWithinEdgeTolerance (const FVector & CapsuleLocation, const FVector & TestImpactPoint, const float CapsuleRadius) const virtual
Return true if the 2D distance to the impact point is inside the edge tolerance (CapsuleRadius minus a small rejection threshold).
Useful for rejecting adjacent hits when finding a floor or landing spot.
References IsWithinEdgeTolerance().
JumpOff()
virtual void UCharacterMovementComponent::JumpOff (AActor * MovementBaseActor) virtual
Force this pawn to bounce off its current base, which isn't an acceptable base for it.
References JumpOff().
JumpOutOfWater()
virtual void UCharacterMovementComponent::JumpOutOfWater (FVector WallNormal) virtual
Jump onto shore from water.
References JumpOutOfWater().
K2_ComputeFloorDist()
virtual void UCharacterMovementComponent::K2_ComputeFloorDist (FVector CapsuleLocation, float LineDistance, float SweepDistance, float SweepRadius, FFindFloorResult & FloorResult) const virtual
Compute distance to the floor from bottom sphere of capsule and store the result in FloorResult.
This distance is the swept distance of the capsule to the first point impacted by the lower hemisphere, or distance from the bottom of the capsule in the case of a line trace. This function does not care if collision is disabled on the capsule (unlike FindFloor).
Parameters
CapsuleLocation Location where the capsule sweep should originate
LineDistance If non-zero, max distance to test for a simple line check from the capsule base. Used only if the sweep test fails to find a walkable floor, and only returns a valid result if the impact normal is a walkable normal.
SweepDistance If non-zero, max distance to use when sweeping a capsule downwards for the test. MUST be greater than or equal to the line distance.
SweepRadius The radius to use for sweep tests. Should be <= capsule radius.
FloorResult Result of the floor check
References K2_ComputeFloorDist().
K2_FindFloor()
virtual void UCharacterMovementComponent::K2_FindFloor (FVector CapsuleLocation, FFindFloorResult & FloorResult) const virtual
Sweeps a vertical trace to find the floor for the capsule at the given location.
Will attempt to perch if ShouldComputePerchResult() returns true for the downward sweep result. No floor will be found if collision is disabled on the capsule!
Parameters
CapsuleLocation Location where the capsule sweep should originate
FloorResult Result of the floor check
References K2_FindFloor().
K2_GetWalkableFloorAngle()
float UCharacterMovementComponent::K2_GetWalkableFloorAngle () const
Get the max angle in degrees of a walkable surface for the character.
References K2_GetWalkableFloorAngle().
K2_GetWalkableFloorZ()
float UCharacterMovementComponent::K2_GetWalkableFloorZ () const
Get the Z component of the normal of the steepest walkable surface for the character.
Any lower than this and it is not walkable.
References K2_GetWalkableFloorZ().
K2_MoveUpdatedComponent()
bool UMovementComponent::K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult & OutHit, bool bSweep = true, bool bTeleport = false) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
References K2_MoveUpdatedComponent().
Launch()
virtual void UCharacterMovementComponent::Launch (FVector const & LaunchVel) virtual
Queue a pending launch with velocity LaunchVel.
References Launch().
LimitAirControl()
virtual FVector UCharacterMovementComponent::LimitAirControl (float DeltaTime, const FVector & FallAcceleration, const FHitResult & HitResult, bool bCheckForValidLandingSpot) protected virtual
Limits the air control to use during falling movement, given an impact while falling.
This function is used internally by PhysFalling().
Parameters
DeltaTime Time step for the current update.
FallAcceleration Acceleration used during movement.
HitResult Result of impact.
bCheckForValidLandingSpot If true, will use IsValidLandingSpot() to determine if HitResult is a walkable surface. If false, this check is skipped.
Returns
Modified air control acceleration to use during falling movement.
See also
PhysFalling()
MaintainHorizontalGroundVelocity()
virtual void UCharacterMovementComponent::MaintainHorizontalGroundVelocity () protected virtual
Adjusts velocity when walking so that Z velocity is zero.
When bMaintainHorizontalGroundVelocity is false, also rescales the velocity vector to maintain the original magnitude, but in the horizontal direction.
References MaintainHorizontalGroundVelocity().
MarkForClientCameraUpdate()
void UPawnMovementComponent::MarkForClientCameraUpdate () protected inherited
Attempts to mark the PlayerCameraManager as dirty, if the controller has one.
This will have no effect if called from the server.
References MarkForClientCameraUpdate().
MaybeSaveBaseLocation()
virtual void UCharacterMovementComponent::MaybeSaveBaseLocation () virtual
Call SaveBaseLocation() if not deferring updates (bDeferUpdateBasedMovement is false).
References MaybeSaveBaseLocation().
MaybeUpdateBasedMovement()
virtual void UCharacterMovementComponent::MaybeUpdateBasedMovement (float DeltaSeconds) virtual
Update or defer updating of position based on Base movement.
References MaybeUpdateBasedMovement().
MoveAlongFloor()
virtual void UCharacterMovementComponent::MoveAlongFloor (const FVector & InVelocity, float DeltaSeconds, FStepDownResult * OutStepDownResult = NULL) protected virtual
Move along the floor, using CurrentFloor and ComputeGroundMovementDelta() to get a movement direction.
If a second walkable surface is hit, it will also be moved along using the same approach.
Parameters
InVelocity Velocity of movement
DeltaSeconds Time over which movement occurs
OutStepDownResult [Out] If non-null, and a floor check is performed, this will be updated to reflect that result.
References MoveAlongFloor().
MoveAutonomous()
virtual void UCharacterMovementComponent::MoveAutonomous (float ClientTimeStamp, float DeltaTime, uint8 CompressedFlags, const FVector & NewAccel) protected virtual
References MoveAutonomous().
MoveResponsePacked_ClientReceive()
void UCharacterMovementComponent::MoveResponsePacked_ClientReceive (const FCharacterMoveResponsePackedBits & PackedBits)
References MoveResponsePacked_ClientReceive().
MoveResponsePacked_ServerSend()
void UCharacterMovementComponent::MoveResponsePacked_ServerSend (const FCharacterMoveResponsePackedBits & PackedBits)
References MoveResponsePacked_ServerSend().
MoveSmooth()
virtual void UCharacterMovementComponent::MoveSmooth (const FVector & InVelocity, const float DeltaSeconds, FStepDownResult * OutStepDownResult = NULL) virtual
Moves along the given movement direction using simple movement rules based on the current movement mode (usually used by simulated proxies).
Parameters
InVelocity Velocity of movement
DeltaSeconds Time over which movement occurs
OutStepDownResult [Out] If non-null, and a floor check is performed, this will be updated to reflect that result.
References MoveSmooth().
MoveUpdatedComponent() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled. \note This simply calls the virtual MoveUpdatedComponentImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
Definition at line 487 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 492 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponentImpl()
virtual bool UMovementComponent::MoveUpdatedComponentImpl (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) protected virtual inherited
References MoveUpdatedComponentImpl().
NewFallVelocity()
virtual FVector UCharacterMovementComponent::NewFallVelocity (const FVector & InitialVelocity, const FVector & Gravity, float DeltaTime) const virtual
Compute new falling velocity from given velocity and gravity.
Applies the limits of the current Physics Volume's TerminalVelocity.
References NewFallVelocity().
NotifyBumpedPawn()
virtual void UCharacterMovementComponent::NotifyBumpedPawn (APawn * BumpedPawn) override virtual
Notify of collision in case we want to react, such as waking up avoidance or pathing code.
Reimplemented from UPawnMovementComponent.
NotifyJumpApex()
virtual void UCharacterMovementComponent::NotifyJumpApex () virtual
Called if bNotifyApex is true and character has just passed the apex of its jump.
References NotifyJumpApex().
OnCharacterStuckInGeometry()
virtual void UCharacterMovementComponent::OnCharacterStuckInGeometry (const FHitResult * Hit) protected virtual
Notification that the character is stuck in geometry.
Only called during walking movement.
References OnCharacterStuckInGeometry().
OnClientCorrectionReceived()
virtual void UCharacterMovementComponent::OnClientCorrectionReceived (class FNetworkPredictionData_Client_Character & ClientData, float TimeStamp, FVector NewLocation, FVector NewVelocity, UPrimitiveComponent * NewBase, FName NewBaseBoneName, bool bHasBase, bool bBaseRelativePosition, uint8 ServerMovementMode, FVector ServerGravityDirection) protected virtual
Event notification when client receives correction data from the server, before applying the data.
Base implementation logs relevant data and draws debug info if "p.NetShowCorrections" is not equal to 0.
References OnClientCorrectionReceived().
OnClientTimeStampResetDetected()
virtual void UCharacterMovementComponent::OnClientTimeStampResetDetected () protected virtual
Called by UCharacterMovementComponent::VerifyClientTimeStamp() when a client timestamp reset has been detected and is valid.
References OnClientTimeStampResetDetected().
OnMovementModeChanged()
virtual void UCharacterMovementComponent::OnMovementModeChanged (EMovementMode PreviousMovementMode, uint8 PreviousCustomMode) protected virtual
Called after MovementMode has changed.
Base implementation does special handling for starting certain modes, then notifies the CharacterOwner.
OnMovementUpdated()
virtual void UCharacterMovementComponent::OnMovementUpdated (float DeltaSeconds, const FVector & OldLocation, const FVector & OldVelocity) protected virtual
Event triggered at the end of a movement update.
If scoped movement updates are enabled (bEnableScopedMovementUpdates), this is within such a scope. If that is not desired, bind to the CharacterOwner's OnMovementUpdated event instead, as that is triggered after the scoped movement update.
References OnMovementUpdated().
OnRegister()
virtual void UCharacterMovementComponent::OnRegister () override virtual
Overridden to update component properties that should be updated while being edited.
Reimplemented from UMovementComponent.
OnRootMotionSourceBeingApplied()
virtual void UCharacterMovementComponent::OnRootMotionSourceBeingApplied (const FRootMotionSource * Source) virtual
Called during ApplyRootMotionSource call, useful for project-specific alerts for "something is about to be altering our movement".
References OnRootMotionSourceBeingApplied().
OnTeleported()
virtual void UCharacterMovementComponent::OnTeleported () override virtual
Called by owning Character upon successful teleport from AActor::TeleportTo().
Reimplemented from UPawnMovementComponent.
OnTimeDiscrepancyDetected()
virtual void UCharacterMovementComponent::OnTimeDiscrepancyDetected (float CurrentTimeDiscrepancy, float LifetimeRawTimeDiscrepancy, float Lifetime, float CurrentMoveError) protected virtual
Called by UCharacterMovementComponent::ProcessClientTimeStampForTimeDiscrepancy() (on server) when the time from client moves significantly differs from the server time, indicating potential time manipulation by clients (speed hacks, significant network issues, client performance problems)
Parameters
CurrentTimeDiscrepancy Accumulated time difference between client ServerMove and server time - this is bounded by MovementTimeDiscrepancy config variables in AGameNetworkManager, and is the value with which we test against to trigger this function. This is reset when MovementTimeDiscrepancy resolution is enabled
LifetimeRawTimeDiscrepancy Accumulated time difference between client ServerMove and server time - this is unbounded and does NOT get affected by MovementTimeDiscrepancy resolution, and is useful as a longer-term view of how the given client is performing. High magnitude unbounded error points to intentional tampering by a client vs. occasional "naturally caused" spikes in error due to burst packet loss/performance hitches
Lifetime Game time over which LifetimeRawTimeDiscrepancy has accrued (useful for determining severity of LifetimeUnboundedError)
CurrentMoveError Time difference between client ServerMove and how much time has passed on the server for the current move that has caused TimeDiscrepancy to accumulate enough to trigger detection.
References OnTimeDiscrepancyDetected().
OnUnableToFollowBaseMove()
virtual void UCharacterMovementComponent::OnUnableToFollowBaseMove (const FVector & DeltaPosition, const FVector & OldLocation, const FHitResult & MoveOnBaseHit) protected virtual
Event triggered when we are moving on a base but we are not able to move the full DeltaPosition because something has blocked us.
Note: MoveComponentFlags includes the flag to ignore the movement base while this event is fired.
Parameters
DeltaPosition How far we tried to move with the base.
OldLocation Location before we tried to move with the base.
MoveOnBaseHit Hit result for the object we hit when trying to move with the base.
References OnUnableToFollowBaseMove().
OverlapTest()
virtual bool UMovementComponent::OverlapTest (const FVector & Location, const FQuat & RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape & CollisionShape, const AActor * IgnoreActor) const virtual inherited
Return true if the given collision shape overlaps other geometry at the given location and rotation.
The collision params are set by InitCollisionParams().
References Location, MoveUpdatedComponent(), and OverlapTest().
PackNetworkMovementMode()
virtual uint8 UCharacterMovementComponent::PackNetworkMovementMode () const virtual
PackYawAndPitchTo32()
uint32 UCharacterMovementComponent::PackYawAndPitchTo32 (const float Yaw, const float Pitch) inline static
Definition at line 2880 of file CharacterMovementComponent.h.
PerformAirControlForPathFollowing()
virtual void UCharacterMovementComponent::PerformAirControlForPathFollowing (FVector Direction, float ZDiff) virtual
If ShouldPerformAirControlForPathFollowing() returns true, it will update Velocity and Acceleration to air control in the desired Direction for character using path following.
Parameters
Direction is the desired direction of movement
ZDiff is the height difference between the destination and the Pawn's current position
See also
RequestDirectMove()
References PerformAirControlForPathFollowing().
PerformMovement()
virtual void UCharacterMovementComponent::PerformMovement (float DeltaTime) protected virtual
Perform movement on an autonomous client.
References PerformMovement().
PhysCustom()
virtual void UCharacterMovementComponent::PhysCustom (float deltaTime, int32 Iterations) protected virtual
\note Movement update functions should only be called through StartNewPhysics()
References PhysCustom().
PhysFalling()
virtual void UCharacterMovementComponent::PhysFalling (float deltaTime, int32 Iterations) virtual
Handle falling movement.
References PhysFalling().
PhysFlying()
virtual void UCharacterMovementComponent::PhysFlying (float deltaTime, int32 Iterations) protected virtual
\note Movement update functions should only be called through StartNewPhysics()
References PhysFlying().
PhysicsLockedAxisSettingChanged()
void UMovementComponent::PhysicsLockedAxisSettingChanged () static inherited
PhysicsRotation()
virtual void UCharacterMovementComponent::PhysicsRotation (float DeltaTime) virtual
Perform rotation over deltaTime.
References PhysicsRotation().
PhysicsVolumeChanged()
virtual void UCharacterMovementComponent::PhysicsVolumeChanged (class APhysicsVolume * NewVolume) override virtual
Delegate when PhysicsVolume of UpdatedComponent has been changed.
Reimplemented from UMovementComponent.
References PhysicsVolumeChanged().
PhysNavWalking()
virtual void UCharacterMovementComponent::PhysNavWalking (float deltaTime, int32 Iterations) protected virtual
\note Movement update functions should only be called through StartNewPhysics()
References PhysNavWalking().
PhysSwimming()
virtual void UCharacterMovementComponent::PhysSwimming (float deltaTime, int32 Iterations) protected virtual
\note Movement update functions should only be called through StartNewPhysics()
References PhysSwimming().
PhysWalking()
virtual void UCharacterMovementComponent::PhysWalking (float deltaTime, int32 Iterations) protected virtual
\note Movement update functions should only be called through StartNewPhysics()
References PhysWalking().
PostBuildAsyncInput()
virtual void UCharacterMovementComponent::PostBuildAsyncInput () protected virtual
References PostBuildAsyncInput().
PostEditChangeProperty()
virtual void UCharacterMovementComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from UNavMovementComponent.
PostLoad()
virtual void UCharacterMovementComponent::PostLoad () override virtual
Reimplemented from UMovementComponent.
PostPhysicsTickComponent()
virtual void UCharacterMovementComponent::PostPhysicsTickComponent (float DeltaTime, FCharacterMovementComponentPostPhysicsTickFunction & ThisTickFunction) virtual
Tick function called after physics (sync scene) has finished simulation, before cloth.
References PostPhysicsTickComponent().
PostProcessAvoidanceVelocity()
virtual void UCharacterMovementComponent::PostProcessAvoidanceVelocity (FVector & NewVelocity) virtual
allows modifing avoidance velocity, called when bUseRVOPostProcess is set
PrePhysicsTickComponent()
virtual void UCharacterMovementComponent::PrePhysicsTickComponent (float DeltaTime, FCharacterMovementComponentPrePhysicsTickFunction & ThisTickFunction) virtual
Tick function called before physics.
References PrePhysicsTickComponent().
ProcessAsyncOutput()
virtual void UCharacterMovementComponent::ProcessAsyncOutput () protected virtual
References ProcessAsyncOutput().
ProcessClientTimeStampForTimeDiscrepancy()
virtual void UCharacterMovementComponent::ProcessClientTimeStampForTimeDiscrepancy (float ClientTimeStamp, FNetworkPredictionData_Server_Character & ServerData) protected virtual
Processes client timestamps from ServerMoves, detects and protects against time discrepancy between client-reported times and server time Called by UCharacterMovementComponent::VerifyClientTimeStamp() for valid timestamps.
References ProcessClientTimeStampForTimeDiscrepancy().
ProcessLanded()
virtual void UCharacterMovementComponent::ProcessLanded (const FHitResult & Hit, float remainingTime, int32 Iterations) protected virtual
Handle landing against Hit surface over remaingTime and iterations, calling SetPostLandedPhysics() and starting the new movement mode.
ProjectLocationFromNavMesh()
virtual FVector UCharacterMovementComponent::ProjectLocationFromNavMesh (float DeltaSeconds, const FVector & CurrentFeetLocation, const FVector & TargetNavLocation, float UpOffset, float DownOffset) protected virtual
Attempts to better align navmesh walking characters with underlying geometry (sometimes navmesh can differ quite significantly from geometry).
Updates CachedProjectedNavMeshHitResult, access this for more info about hits.
ProjectToGravityFloor()
FVector UCharacterMovementComponent::ProjectToGravityFloor (const FVector & Vector) const inline
Project a vector onto the floor defined by the gravity direction.
Definition at line 1681 of file CharacterMovementComponent.h.
References GetGravityDirection().
RegisterAsyncCallback()
virtual void UCharacterMovementComponent::RegisterAsyncCallback () protected virtual
References RegisterAsyncCallback().
RegisterComponentTickFunctions()
virtual void UCharacterMovementComponent::RegisterComponentTickFunctions (bool bRegister) override virtual
Reimplemented from UMovementComponent.
RemoveRootMotionSource()
void UCharacterMovementComponent::RemoveRootMotionSource (FName InstanceName)
Remove a RootMotionSource from current root motion by name.
References RemoveRootMotionSource().
RemoveRootMotionSourceByID()
void UCharacterMovementComponent::RemoveRootMotionSourceByID (uint16 RootMotionSourceID)
Remove a RootMotionSource from current root motion by ID.
References RemoveRootMotionSourceByID().
ReplicateMoveToServer()
virtual void UCharacterMovementComponent::ReplicateMoveToServer (float DeltaTime, const FVector & NewAcceleration) protected virtual
Perform local movement and send the move to the server.
RequestDirectMove()
virtual void UCharacterMovementComponent::RequestDirectMove (const FVector & MoveVelocity, bool bForceMaxSpeed) override virtual
path following: request new velocity
Reimplemented from UNavMovementComponent.
RequestPathMove()
virtual void UCharacterMovementComponent::RequestPathMove (const FVector & MoveInput) override virtual
path following: request new move input (normal vector = full strength)
Reimplemented from UPawnMovementComponent.
ResetMoveState()
virtual void UNavMovementComponent::ResetMoveState () inline override virtual inherited
Resets runtime movement state to character's movement capabilities.
Implements INavMovementInterface.
Definition at line 156 of file NavMovementComponent.h.
References MovementState, and NavAgentProps.
ResetPredictionData_Client()
virtual void UCharacterMovementComponent::ResetPredictionData_Client () override virtual
ResetPredictionData_Server()
virtual void UCharacterMovementComponent::ResetPredictionData_Server () override virtual
ResolvePenetration() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) inherited
Try to move out of penetration in an object after a failed move.
This function should respect the plane constraint if applicable. \note This simply calls the virtual ResolvePenetrationImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat)..
Parameters
Adjustment The requested adjustment, usually from GetPenetrationAdjustment()
Hit The result of the failed move
Returns
True if the adjustment was successful and the original move should be retried, or false if no repeated attempt should be made.
Definition at line 497 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetration() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FRotator & NewRotation) inherited
Definition at line 502 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetrationImpl()
virtual bool UCharacterMovementComponent::ResolvePenetrationImpl (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) override protected virtual
Overridden to set bJustTeleported to true, so we don't make incorrect velocity calculations based on adjusted movement.
Reimplemented from UMovementComponent.
References ResolvePenetrationImpl().
RestorePreAdditiveRootMotionVelocity()
virtual void UCharacterMovementComponent::RestorePreAdditiveRootMotionVelocity () protected virtual
Restores Velocity to LastPreAdditiveVelocity during Root Motion Phys*() function calls.
RevertMove()
void UCharacterMovementComponent::RevertMove (const FVector & OldLocation, UPrimitiveComponent * OldBase, const FVector & InOldBaseLocation, const FFindFloorResult & OldFloor, bool bFailMove)
Revert to previous position OldLocation, return to being based on OldBase.
if bFailMove, stop movement and notify controller
References RevertMove().
RotateGravityToWorld()
FVector UCharacterMovementComponent::RotateGravityToWorld (const FVector & World) const inline
Rotate a vector from world to gravity space.
Definition at line 1675 of file CharacterMovementComponent.h.
RotateWorldToGravity()
FVector UCharacterMovementComponent::RotateWorldToGravity (const FVector & Gravity) const inline
Rotate a vector from gravity to world space.
Definition at line 1678 of file CharacterMovementComponent.h.
RoundAcceleration()
virtual FVector UCharacterMovementComponent::RoundAcceleration (FVector InAccel) const virtual
Round acceleration, for better consistency and lower bandwidth in networked games.
SafeMoveUpdatedComponent() [1/2]
bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
If this adjustment succeeds, the original movement will be attempted again. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
result of the final MoveUpdatedComponent() call.
References SafeMoveUpdatedComponent().
SafeMoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 482 of file MovementComponent.h.
References SafeMoveUpdatedComponent().
SaveBaseLocation()
virtual void UCharacterMovementComponent::SaveBaseLocation () virtual
Update OldBaseLocation and OldBaseQuat if there is a valid movement base, and store the relative location/rotation if necessary.
Ignores bDeferUpdateBasedMovement and forces the update.
References SaveBaseLocation().
ScaleInputAcceleration()
virtual FVector UCharacterMovementComponent::ScaleInputAcceleration (const FVector & InputAcceleration) const protected virtual
Scale input acceleration, based on movement acceleration rate.
References ScaleInputAcceleration().
SendClientAdjustment()
virtual void UCharacterMovementComponent::SendClientAdjustment () override virtual
Serialize()
virtual void UCharacterMovementComponent::Serialize (FArchive & Archive) override virtual
Reimplemented from UPawnMovementComponent.
ServerAutonomousProxyTick()
virtual void UCharacterMovementComponent::ServerAutonomousProxyTick (float DeltaSeconds) inline protected virtual
Special Tick to allow custom server-side functionality on Autonomous Proxies.
Called for all remote APs, including APs controlled on Listen Servers such as the hosting player's Character. If full server-side control is desired, you may need to override ControlledCharacterMove as well.
Definition at line 2247 of file CharacterMovementComponent.h.
References ServerAutonomousProxyTick().
ServerCheckClientError()
virtual bool UCharacterMovementComponent::ServerCheckClientError (float ClientTimeStamp, float DeltaTime, const FVector & Accel, const FVector & ClientWorldLocation, const FVector & RelativeClientLocation, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) protected virtual
Check for Server-Client disagreement in position or other movement state important enough to trigger a client correction.
See also
ServerMoveHandleClientError()
References ServerCheckClientError().
ServerExceedsAllowablePositionError()
virtual bool UCharacterMovementComponent::ServerExceedsAllowablePositionError (float ClientTimeStamp, float DeltaTime, const FVector & Accel, const FVector & ClientWorldLocation, const FVector & RelativeClientLocation, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) protected virtual
Check position error within ServerCheckClientError().
Set bNetworkLargeClientCorrection to true if the correction should be prioritized (delayed less in SendClientAdjustment).
References ServerExceedsAllowablePositionError().
ServerMove()
virtual void UCharacterMovementComponent::ServerMove (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
Replicated function sent by client to server - contains client movement and view info.
Calls either CharacterOwner->ServerMove() or CharacterOwner->ServerMoveNoBase() depending on whehter ClientMovementBase is null.
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove(), ServerMove_Implementation(), and ServerMove_PerformMovement().
ServerMove_HandleMoveData()
virtual void UCharacterMovementComponent::ServerMove_HandleMoveData (const FCharacterNetworkMoveDataContainer & MoveDataContainer) virtual
Handle movement data after it's unpacked from the ServerMovePacked_ServerReceive() call.
Default implementation passes through to ServerMove_PerformMovement(), which may be called twice in the case of a "dual move", and one additional time for an "old important move".
References ServerMove_HandleMoveData().
ServerMove_Implementation()
virtual void UCharacterMovementComponent::ServerMove_Implementation (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References ServerMove_Implementation().
ServerMove_PerformMovement()
virtual void UCharacterMovementComponent::ServerMove_PerformMovement (const FCharacterNetworkMoveData & MoveData) virtual
Check timestamps, generate a delta time, and pass through movement params to MoveAutonomous.
Error checking is optionally done on the final location, compared to 'ClientLoc'. The FCharacterNetworkMoveData parameter to this function is also the same returned by GetCurrentNetworkMoveData(), to assist in migration of code that may want to access the data without changing function signatures. (Note: this is similar to "ServerMove_Implementation" in legacy versions).
References ServerMove_PerformMovement().
ServerMove_Validate()
virtual bool UCharacterMovementComponent::ServerMove_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove_Validate(), ServerMoveDual(), and ServerMovePacked_ClientSend().
ServerMoveDual()
virtual void UCharacterMovementComponent::ServerMoveDual (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
Replicated function sent by client to server - contains client movement and view info for two moves.
Calls either CharacterOwner->ServerMoveDual() or CharacterOwner->ServerMoveDualNoBase() depending on whehter ClientMovementBase is null.
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove_PerformMovement(), ServerMoveDual(), and ServerMoveDual_Implementation().
ServerMoveDual_Implementation()
virtual void UCharacterMovementComponent::ServerMoveDual_Implementation (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References ServerMoveDual_Implementation().
ServerMoveDual_Validate()
virtual bool UCharacterMovementComponent::ServerMoveDual_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion(), and ServerMovePacked_ClientSend().
ServerMoveDualHybridRootMotion()
virtual void UCharacterMovementComponent::ServerMoveDualHybridRootMotion (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
Replicated function sent by client to server - contains client movement and view info for two moves.
First move is non root motion, second is root motion.
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove_PerformMovement(), ServerMoveDualHybridRootMotion(), and ServerMoveDualHybridRootMotion_Implementation().
ServerMoveDualHybridRootMotion_Implementation()
virtual void UCharacterMovementComponent::ServerMoveDualHybridRootMotion_Implementation (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References ServerMoveDualHybridRootMotion_Implementation().
ServerMoveDualHybridRootMotion_Validate()
virtual bool UCharacterMovementComponent::ServerMoveDualHybridRootMotion_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) virtual
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMoveDualHybridRootMotion_Validate(), ServerMoveOld(), and ServerMovePacked_ClientSend().
ServerMoveHandleClientError()
virtual void UCharacterMovementComponent::ServerMoveHandleClientError (float ClientTimeStamp, float DeltaTime, const FVector & Accel, const FVector & RelativeClientLocation, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) protected virtual
Have the server check if the client is outside an error tolerance, and queue a client adjustment if so.
If either GetPredictionData_Server_Character()->bForceClientUpdate or ServerCheckClientError() are true, the client adjustment will be sent. RelativeClientLocation will be a relative location if MovementBaseUtility::UseRelativePosition(ClientMovementBase) is true, or a world location if false.
See also
ServerCheckClientError()
References ServerMoveHandleClientError().
ServerMoveOld()
virtual void UCharacterMovementComponent::ServerMoveOld (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags) virtual
References DEPRECATED_CHARACTER_MOVEMENT_RPC, ServerMove_PerformMovement(), ServerMoveOld(), and ServerMoveOld_Implementation().
ServerMoveOld_Implementation()
virtual void UCharacterMovementComponent::ServerMoveOld_Implementation (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags) virtual
References ServerMoveOld_Implementation().
ServerMoveOld_Validate()
virtual bool UCharacterMovementComponent::ServerMoveOld_Validate (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags) virtual
References ClientAckGoodMove(), ClientHandleMoveResponse(), DEPRECATED_CHARACTER_MOVEMENT_RPC, and ServerMoveOld_Validate().
ServerMovePacked_ClientSend()
void UCharacterMovementComponent::ServerMovePacked_ClientSend (const FCharacterServerMovePackedBits & PackedBits)
The actual network RPCs for character movement are passed to ACharacter, which wrap to the _Implementation call here, to avoid Component RPC overhead.
For example: Client: UCharacterMovementComponent::ServerMovePacked_ClientSend() => Calls CharacterOwner->ServerMove() triggering RPC on the server. Server: ACharacter::ServerMovePacked_Implementation() from the RPC => Calls CharacterMovement->ServerMove_ServerReceive(), unpacked and sent to ServerMove_ServerHandleMoveData().
ServerMove_ClientSend() and ServerMove_ServerReceive() use a bitstream created from the current FCharacterNetworkMoveData data container that contains the client move. See GetNetworkMoveDataContainer()/SetNetworkMoveDataContainer() for details on setting a custom container with custom unpacking through FCharacterNetworkMoveData::Serialize(). Wrapper to send packed move data to the server, through the Character.
See also
CallServerMovePacked()
References ServerMovePacked_ClientSend().
ServerMovePacked_ServerReceive()
void UCharacterMovementComponent::ServerMovePacked_ServerReceive (const FCharacterServerMovePackedBits & PackedBits)
On the server, receives packed move data from the Character RPC, unpacks them into the FCharacterNetworkMoveDataContainer returned from GetNetworkMoveDataContainer(), and passes the data container to ServerMove_HandleMoveData().
References ServerMovePacked_ServerReceive().
ServerSendMoveResponse()
void UCharacterMovementComponent::ServerSendMoveResponse (const FClientAdjustment & PendingAdjustment)
On the server, sends a packed move response to the client.
First the FCharacterMoveResponseDataContainer from GetMoveResponseDataContainer() is filled in with ServerFillResponseData(). Then this data is serialized to a bit stream that is sent to the client via MoveResponsePacked_ServerSend().
References ServerSendMoveResponse().
ServerShouldUseAuthoritativePosition()
virtual bool UCharacterMovementComponent::ServerShouldUseAuthoritativePosition (float ClientTimeStamp, float DeltaTime, const FVector & Accel, const FVector & ClientWorldLocation, const FVector & RelativeClientLocation, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode) protected virtual
If ServerCheckClientError() does not find an error, this determines if the server should also copy the client's movement params rather than keep the server sim result.
References ServerShouldUseAuthoritativePosition().
SetAvoidanceEnabled()
void UCharacterMovementComponent::SetAvoidanceEnabled (bool bEnable)
Change avoidance state and registers in RVO manager if needed.
References GetCharacterOwner(), and SetAvoidanceEnabled().
SetAvoidanceGroup()
void UCharacterMovementComponent::SetAvoidanceGroup (int32 GroupFlags)
References SetAvoidanceGroup().
SetAvoidanceGroupMask() [1/2]
void UCharacterMovementComponent::SetAvoidanceGroupMask (const FNavAvoidanceMask & GroupMask)
References SetAvoidanceGroupMask().
SetAvoidanceGroupMask() [2/2]
virtual void UCharacterMovementComponent::SetAvoidanceGroupMask (int32 GroupFlags) override virtual
SetAvoidanceVelocityLock()
void UCharacterMovementComponent::SetAvoidanceVelocityLock (class UAvoidanceManager * Avoidance, float Duration)
lock avoidance velocity
SetBase()
virtual void UCharacterMovementComponent::SetBase (UPrimitiveComponent * NewBase, const FName BoneName = NAME_None, bool bNotifyActor = true) virtual
Update the base of the character, which is the PrimitiveComponent we are standing on.
References SetBase().
SetBaseFromFloor()
void UCharacterMovementComponent::SetBaseFromFloor (const FFindFloorResult & FloorResult)
Update the base of the character, using the given floor result if it is walkable, or null if not.
Calls SetBase().
References SetBaseFromFloor().
SetCrouchedHalfHeight()
void UCharacterMovementComponent::SetCrouchedHalfHeight (const float NewValue)
Sets collision half-height when crouching and updates dependent computations.
References SetCrouchedHalfHeight().
SetCurrentNetworkMoveData()
void UCharacterMovementComponent::SetCurrentNetworkMoveData (FCharacterNetworkMoveData * CurrentData) inline protected
Used internally to set the FCharacterNetworkMoveData currently being processed, either being serialized or replayed on the client, or being received and processed on the server.
See also
GetCurrentNetworkMoveData()
Definition at line 2636 of file CharacterMovementComponent.h.
SetCurrentReplayedSavedMove()
void UCharacterMovementComponent::SetCurrentReplayedSavedMove (FSavedMove_Character * SavedMove) inline protected
Used internally to save the SavedMove currently being replayed on the client so it is accessible to any functions that might need it.
See also
: ClientUpdatePositionAfterServerUpdate
Definition at line 2655 of file CharacterMovementComponent.h.
SetDefaultMovementMode()
virtual void UCharacterMovementComponent::SetDefaultMovementMode () virtual
Set movement mode to the default based on the current physics volume.
References SetDefaultMovementMode().
SetFixedBrakingDistance()
UE_API void INavMovementInterface::SetFixedBrakingDistance (float DistanceToEndOfPath) inherited
Set fixed braking distance.
References SetFixedBrakingDistance(), and UE_API.
SetGravityDirection()
virtual void UCharacterMovementComponent::SetGravityDirection (const FVector & GravityDir) virtual
Set a custom, local gravity direction to use during movement simulation.
The gravity direction must be synchronized by external systems between the autonomous and authority processes. The gravity direction will be corrected as part of movement corrections should the movement state diverge. SetGravityDirection is responsible for initializing cached values used to tranform to from gravity relative space.
Parameters
GravityDir A non-zero vector representing the new gravity direction. The vector will be normalized.
References SetGravityDirection().
SetGravitySpaceZ()
void UCharacterMovementComponent::SetGravitySpaceZ (FVector & Vector, const FVector::FReal Z) const inline
Set the vertical component of the vector to the given value in the gravity-space vertical direction.
Definition at line 1690 of file CharacterMovementComponent.h.
References GetGravityDirection(), ProjectToGravityFloor(), and Z.
SetGroundMovementMode()
void UCharacterMovementComponent::SetGroundMovementMode (EMovementMode NewGroundMovementMode)
Set movement mode to use when returning to walking movement (either MOVE_Walking or MOVE_NavWalking).
If movement mode is currently one of Walking or NavWalking, this will also change the current movement mode (via SetMovementMode()) if the new mode is not the current ground mode.
Parameters
NewGroundMovementMode New ground movement mode. Must be either MOVE_Walking or MOVE_NavWalking, other values are ignored.
See also
GroundMovementMode
References SetGroundMovementMode().
SetGroupsToAvoid()
void UCharacterMovementComponent::SetGroupsToAvoid (int32 GroupFlags)
References SetGroupsToAvoid().
SetGroupsToAvoidMask() [1/2]
void UCharacterMovementComponent::SetGroupsToAvoidMask (const FNavAvoidanceMask & GroupMask)
References SetGroupsToAvoidMask().
SetGroupsToAvoidMask() [2/2]
virtual void UCharacterMovementComponent::SetGroupsToAvoidMask (int32 GroupFlags) override virtual
SetGroupsToIgnore()
void UCharacterMovementComponent::SetGroupsToIgnore (int32 GroupFlags)
References SetGroupsToIgnore().
SetGroupsToIgnoreMask() [1/2]
void UCharacterMovementComponent::SetGroupsToIgnoreMask (const FNavAvoidanceMask & GroupMask)
References SetGroupsToIgnoreMask().
SetGroupsToIgnoreMask() [2/2]
virtual void UCharacterMovementComponent::SetGroupsToIgnoreMask (int32 GroupFlags) override virtual
SetJumpAllowed()
void UNavMovementComponent::SetJumpAllowed (bool bAllowed) inline inherited
Sets whether this component is allowed to jump.
Definition at line 165 of file NavMovementComponent.h.
References MovementState.
SetMovementMode()
virtual void UCharacterMovementComponent::SetMovementMode (EMovementMode NewMovementMode, uint8 NewCustomMode = 0) virtual
Change movement mode.
Parameters
NewMovementMode The new movement mode
NewCustomMode The new custom sub-mode, only applicable if NewMovementMode is Custom.
References SetMovementMode().
SetMoveResponseDataContainer()
void UCharacterMovementComponent::SetMoveResponseDataContainer (FCharacterMoveResponseDataContainer & PersistentDataStorage) inline protected
Set custom struct used for server response RPC serialization.
This is typically set in the constructor for this component and should persist for the lifetime of the component.
See also
GetMoveResponseDataContainer()
Definition at line 2643 of file CharacterMovementComponent.h.
SetNavWalkingPhysics()
virtual void UCharacterMovementComponent::SetNavWalkingPhysics (bool bEnable) protected virtual
Switch collision settings for NavWalking mode (ignore world collisions)
SetNetworkMoveDataContainer()
void UCharacterMovementComponent::SetNetworkMoveDataContainer (FCharacterNetworkMoveDataContainer & PersistentDataStorage) inline protected
Set custom struct used for client to server move RPC serialization.
This is typically set in the constructor for this component and should persist for the lifetime of the component.
See also
GetNetworkMoveDataContainer(), ServerMovePacked_ServerReceive(), ServerMove_HandleMoveData()
Definition at line 2617 of file CharacterMovementComponent.h.
References SetNetworkMoveDataContainer().
SetPathFollowingAgent()
virtual void UNavMovementComponent::SetPathFollowingAgent (IPathFollowingAgentInterface * InPathFollowingAgent) inline override virtual inherited
Set the path following agent this interface uses.
Must implement IPathFollowingAgentInterface.
Implements INavMovementInterface.
Definition at line 146 of file NavMovementComponent.h.
SetPlaneConstraintAxisSetting()
virtual void UMovementComponent::SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting) virtual inherited
Set the plane constraint axis setting.
Changing this setting will modify the current value of PlaneConstraintNormal.
Parameters
NewAxisSetting New plane constraint axis setting.
References EPlaneConstraintAxisSetting, GetPlaneConstraintAxisSetting(), and SetPlaneConstraintAxisSetting().
SetPlaneConstraintEnabled()
virtual void UMovementComponent::SetPlaneConstraintEnabled (bool bEnabled) virtual inherited
Sets whether or not the plane constraint is enabled.
References SetPlaneConstraintEnabled().
SetPlaneConstraintFromVectors()
virtual void UMovementComponent::SetPlaneConstraintFromVectors (FVector Forward, FVector Up) virtual inherited
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintFromVectors().
SetPlaneConstraintNormal()
virtual void UMovementComponent::SetPlaneConstraintNormal (FVector PlaneNormal) virtual inherited
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
Changing the normal automatically sets PlaneConstraintAxisSetting to "Custom".
Parameters
PlaneNormal The normal of the plane. If non-zero in length, it will be normalized.
References SetPlaneConstraintNormal().
SetPlaneConstraintOrigin()
virtual void UMovementComponent::SetPlaneConstraintOrigin (FVector PlaneOrigin) virtual inherited
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintOrigin().
SetPostLandedPhysics()
virtual void UCharacterMovementComponent::SetPostLandedPhysics (const FHitResult & Hit) protected virtual
Use new physics after landing.
Defaults to swimming if in water, walking otherwise.
SetRVOAvoidanceUID()
virtual void UCharacterMovementComponent::SetRVOAvoidanceUID (int32 UID) override virtual
BEGIN IRVOAvoidanceInterface.
SetRVOAvoidanceWeight()
virtual void UCharacterMovementComponent::SetRVOAvoidanceWeight (float Weight) override virtual
SetUpdatedComponent()
virtual void UCharacterMovementComponent::SetUpdatedComponent (USceneComponent * NewUpdatedComponent) override virtual
Overridden to only allow registration with components owned by a Pawn.
Reimplemented from UPawnMovementComponent.
References SetUpdatedComponent().
SetUpdateNavAgentWithOwnersCollisions()
void UNavMovementComponent::SetUpdateNavAgentWithOwnersCollisions (bool bUpdateWithOwner) inherited
SetWalkableFloorAngle()
void UCharacterMovementComponent::SetWalkableFloorAngle (float InWalkableFloorAngle)
Set the max angle in degrees of a walkable surface for the character.
Also computes WalkableFloorZ.
References SetWalkableFloorAngle().
SetWalkableFloorZ()
void UCharacterMovementComponent::SetWalkableFloorZ (float InWalkableFloorZ)
Set the Z component of the normal of the steepest walkable surface for the character.
Also computes WalkableFloorAngle.
References SetWalkableFloorZ().
ShouldCancelAdaptiveReplication()
virtual bool UCharacterMovementComponent::ShouldCancelAdaptiveReplication () const protected virtual
On the server if we know we are having our replication rate throttled, this method checks if important replicated properties have changed that should cause us to return to the normal replication rate.
References ShouldCancelAdaptiveReplication().
ShouldCatchAir()
virtual bool UCharacterMovementComponent::ShouldCatchAir (const FFindFloorResult & OldFloor, const FFindFloorResult & NewFloor) virtual
Whether Character should go into falling mode when walking and changing position, based on an old and new floor result (both of which are considered walkable).
Default implementation always returns false.
Returns
true if Character should start falling
References ShouldCatchAir().
ShouldCheckForValidLandingSpot()
virtual bool UCharacterMovementComponent::ShouldCheckForValidLandingSpot (float DeltaTime, const FVector & Delta, const FHitResult & Hit) const virtual
Determine whether we should try to find a valid landing spot after an impact with an invalid one (based on the Hit result).
For example, landing on the lower portion of the capsule on the edge of geometry may be a walkable surface, but could have reported an unwalkable impact normal.
References ShouldCheckForValidLandingSpot().
ShouldComputeAccelerationToReachRequestedVelocity()
virtual bool UCharacterMovementComponent::ShouldComputeAccelerationToReachRequestedVelocity (const float RequestedSpeed) const protected virtual
When a character requests a velocity (like when following a path), this method returns true if when we should compute the acceleration toward requested velocity (including friction).
If it returns false, it will snap instantly to requested velocity.
ShouldComputePerchResult()
virtual bool UCharacterMovementComponent::ShouldComputePerchResult (const FHitResult & InHit, bool bCheckRadius = true) const virtual
Check if the result of a sweep test (passed in InHit) might be a valid location to perch, in which case we should use ComputePerchResult to validate the location.
See also
ComputePerchResult
Parameters
InHit Result of the last sweep test before this query.
bCheckRadius If true, only allow the perch test if the impact point is outside the radius returned by GetValidPerchRadius().
Returns
Whether perching may be possible, such that ComputePerchResult can return a valid result.
References ShouldComputePerchResult().
ShouldCorrectRotation()
virtual bool UCharacterMovementComponent::ShouldCorrectRotation () const inline virtual
Returns if the character rotation should be corrected on clients when sending a server move response correction.
Definition at line 1104 of file CharacterMovementComponent.h.
References ShouldCorrectRotation().
ShouldJumpOutOfWater()
virtual bool UCharacterMovementComponent::ShouldJumpOutOfWater (FVector & JumpDir) virtual
Determine whether the Character should jump when exiting water.
Parameters
JumpDir is the desired direction to jump out of water
Returns
true if Pawn should jump out of water
References ShouldJumpOutOfWater().
ShouldLimitAirControl()
virtual bool UCharacterMovementComponent::ShouldLimitAirControl (float DeltaTime, const FVector & FallAcceleration) const virtual
Returns true if falling movement should limit air control.
Limiting air control prevents input acceleration during falling movement from allowing velocity to redirect forces upwards while falling, which could result in slower falling or even upward boosting.
See also
GetFallingLateralAcceleration(), BoostAirControl(), GetAirControl(), LimitAirControl()
References ShouldLimitAirControl().
ShouldPerformAirControlForPathFollowing()
virtual bool UCharacterMovementComponent::ShouldPerformAirControlForPathFollowing () const virtual
Whether Character should perform air control via PerformAirControlForPathFollowing when falling and following a path at the same time Default implementation always returns true during MOVE_Falling.
References ShouldPerformAirControlForPathFollowing().
ShouldRemainVertical()
virtual bool UCharacterMovementComponent::ShouldRemainVertical () const virtual
if true, DesiredRotation will be restricted to only Yaw component in PhysicsRotation()
References ShouldRemainVertical().
ShouldSkipUpdate()
virtual bool UMovementComponent::ShouldSkipUpdate (float DeltaTime) const virtual inherited
Possibly skip update if moved component is not rendered or can't move.
Parameters
DeltaTime
Todo
this parameter is not used in the function.
Returns
true if component movement update should be skipped
References ShouldSkipUpdate().
ShouldUpdateNavAgentWithOwnersCollision()
bool UNavMovementComponent::ShouldUpdateNavAgentWithOwnersCollision () const inline inherited
Definition at line 99 of file NavMovementComponent.h.
References NavMovementProperties.
ShouldUsePackedMovementRPCs()
virtual bool UCharacterMovementComponent::ShouldUsePackedMovementRPCs () const virtual
Determines whether to use packed movement RPCs with variable length payloads, or legacy code which has multiple functions required for different situations.
The default implementation checks the console variable "p.NetUsePackedMovementRPCs" and returns true if it is non-zero.
References ShouldUsePackedMovementRPCs().
SimulatedTick()
virtual void UCharacterMovementComponent::SimulatedTick (float DeltaSeconds) protected virtual
Special Tick for Simulated Proxies.
References SimulatedTick().
SimulateMovement()
virtual void UCharacterMovementComponent::SimulateMovement (float DeltaTime) protected virtual
Simulate movement on a non-owning client.
Called by SimulatedTick().
References SimulateMovement().
SimulateRootMotion()
void UCharacterMovementComponent::SimulateRootMotion (float DeltaSeconds, const FTransform & LocalRootMotionTransform)
Simulate Root Motion physics on Simulated Proxies.
SlideAlongSurface()
virtual float UCharacterMovementComponent::SlideAlongSurface (const FVector & Delta, float Time, const FVector & Normal, FHitResult & Hit, bool bHandleImpact) override protected virtual
Custom version of SlideAlongSurface that handles different movement modes separately; namely during walking physics we might not want to slide up slopes.
Reimplemented from UMovementComponent.
References SlideAlongSurface().
SmoothClientPosition()
virtual void UCharacterMovementComponent::SmoothClientPosition (float DeltaSeconds) protected virtual
Smooth mesh location for network interpolation, based on values set up by SmoothCorrection.
Internally this simply calls SmoothClientPosition_Interpolate() then SmoothClientPosition_UpdateVisuals(). This function is not called when bNetworkSmoothingComplete is true.
Parameters
DeltaSeconds Time since last update.
SmoothClientPosition_Interpolate()
void UCharacterMovementComponent::SmoothClientPosition_Interpolate (float DeltaSeconds) protected
Update interpolation values for client smoothing.
Does not change actual mesh location. Sets bNetworkSmoothingComplete to true when the interpolation reaches the target.
SmoothClientPosition_UpdateVisuals()
void UCharacterMovementComponent::SmoothClientPosition_UpdateVisuals () protected
Update mesh location based on interpolated values.
SmoothCorrection()
virtual void UCharacterMovementComponent::SmoothCorrection (const FVector & OldLocation, const FQuat & OldRotation, const FVector & NewLocation, const FQuat & NewRotation) override virtual
React to new transform from network update.
Sets bNetworkSmoothingComplete to false to ensure future smoothing updates. IMPORTANT: It is expected that this function triggers any movement/transform updates to match the network update if desired.
SnapUpdatedComponentToPlane()
virtual void UMovementComponent::SnapUpdatedComponentToPlane () virtual inherited
Snap the updated component to the plane constraint, if enabled.
References SnapUpdatedComponentToPlane().
StartFalling()
virtual void UCharacterMovementComponent::StartFalling (int32 Iterations, float remainingTime, float timeTick, const FVector & Delta, const FVector & subLoc) virtual
Transition from walking to falling.
References StartFalling().
StartNewPhysics()
virtual void UCharacterMovementComponent::StartNewPhysics (float deltaTime, int32 Iterations) virtual
changes physics based on MovementMode
References StartNewPhysics().
StartSwimming()
virtual void UCharacterMovementComponent::StartSwimming (FVector OldLocation, FVector OldVelocity, float timeTick, float remainingTime, int32 Iterations) virtual
Handle start swimming functionality.
Parameters
OldLocation - Location on last tick
OldVelocity - velocity at last tick
timeTick - time since at OldLocation
remainingTime - DeltaTime to complete transition to swimming
Iterations - physics iteration count
References StartSwimming().
StepUp()
virtual bool UCharacterMovementComponent::StepUp (const FVector & GravDir, const FVector & Delta, const FHitResult & Hit, FStepDownResult * OutStepDownResult = NULL) virtual
Move up steps or slope.
Does nothing and returns false if CanStepUp(Hit) returns false.
Parameters
GravDir Gravity vector direction (assumed normalized or zero)
Delta Requested move
Hit [In] The hit before the step up.
OutStepDownResult [Out] If non-null, a floor check will be performed if possible as part of the final step down, and it will be updated to reflect this result.
Returns
true if the step up was successful.
References StepUp().
StopActiveMovement()
virtual void UCharacterMovementComponent::StopActiveMovement () override virtual
Stops applying further movement (usually zeros acceleration).
Reimplemented from INavMovementInterface.
StopMovementImmediately()
void UNavMovementComponent::StopMovementImmediately () inline override virtual inherited
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
Reimplemented from UMovementComponent.
Definition at line 214 of file NavMovementComponent.h.
References INavMovementInterface::StopActiveMovement().
StopMovementKeepPathing()
virtual UE_API void INavMovementInterface::StopMovementKeepPathing () virtual inherited
Stops movement immediately (reset velocity) but keeps following current path.
References StopMovementKeepPathing(), and UE_API.
Swim()
float UCharacterMovementComponent::Swim (FVector Delta, FHitResult & Hit)
References Swim().
TickCharacterPose()
virtual void UCharacterMovementComponent::TickCharacterPose (float DeltaTime) protected virtual
Ticks the characters pose and accumulates root motion.
References TickCharacterPose().
TickComponent()
virtual void UCharacterMovementComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Reimplemented from UMovementComponent.
TryToLeaveNavWalking()
virtual bool UCharacterMovementComponent::TryToLeaveNavWalking () protected virtual
Checks to see if the current location is not encroaching blocking geometry so the character can leave NavWalking.
Restores collision settings and adjusts character location to avoid getting stuck in geometry. If it's not possible, MovementMode change will be delayed until character reach collision free spot.
Returns
True if movement mode was successfully changed
TwoWallAdjust()
virtual void UCharacterMovementComponent::TwoWallAdjust (FVector & WorldSpaceDelta, const FHitResult & Hit, const FVector & OldHitNormal) const override protected virtual
Custom version that allows upwards slides when walking if the surface is walkable.
Reimplemented from UMovementComponent.
References TwoWallAdjust().
UnCrouch()
virtual void UCharacterMovementComponent::UnCrouch (bool bClientSimulation = false) virtual
Checks if default capsule size fits (no encroachment), and trigger OnEndCrouch() on the owner if successful.
Parameters
bClientSimulation true when called when bIsCrouched is replicated to non owned clients, to update collision cylinder and offset.
UnpackNetworkMovementMode()
virtual void UCharacterMovementComponent::UnpackNetworkMovementMode (const uint8 ReceivedMode, TEnumAsByte< EMovementMode > & OutMode, uint8 & OutCustomMode, TEnumAsByte< EMovementMode > & OutGroundMode) const virtual
UpdateBasedMovement()
virtual void UCharacterMovementComponent::UpdateBasedMovement (float DeltaSeconds) virtual
Update position based on Base movement.
References UpdateBasedMovement().
UpdateBasedRotation()
virtual void UCharacterMovementComponent::UpdateBasedRotation (FRotator & FinalRotation, const FRotator & ReducedRotation) virtual
Update controller's view rotation as pawn's base rotates.
References UpdateBasedRotation().
UpdateCharacterStateAfterMovement()
virtual void UCharacterMovementComponent::UpdateCharacterStateAfterMovement (float DeltaSeconds) virtual
Update the character state in PerformMovement after the position change.
Some rotation updates happen after this.
References UpdateCharacterStateAfterMovement().
UpdateCharacterStateBeforeMovement()
virtual void UCharacterMovementComponent::UpdateCharacterStateBeforeMovement (float DeltaSeconds) virtual
Update the character state in PerformMovement right before doing the actual position change.
References UpdateCharacterStateBeforeMovement().
UpdateComponentVelocity()
virtual void UMovementComponent::UpdateComponentVelocity () virtual inherited
Update ComponentVelocity of UpdatedComponent.
This needs to be called by derived classes at the end of an update whenever Velocity has changed.
References UpdateComponentVelocity().
UpdateDefaultAvoidance()
void UCharacterMovementComponent::UpdateDefaultAvoidance () protected
called in Tick to update data in RVO avoidance manager
UpdateFloorFromAdjustment()
virtual void UCharacterMovementComponent::UpdateFloorFromAdjustment () virtual
React to instantaneous change in position.
Invalidates cached floor recomputes it if possible if there is a current movement base.
References UpdateFloorFromAdjustment().
UpdateFromCompressedFlags()
virtual void UCharacterMovementComponent::UpdateFromCompressedFlags (uint8 Flags) protected virtual
Unpack compressed flags from a saved move and set state accordingly.
See FSavedMove_Character.
References UpdateFromCompressedFlags().
UpdateNavAgent()
virtual void UNavMovementComponent::UpdateNavAgent (const UObject & ObjectToUpdateFrom) override virtual inherited
Set nav agent properties from an object.
Implements INavMovementInterface.
UpdateProxyAcceleration()
virtual void UCharacterMovementComponent::UpdateProxyAcceleration () virtual
Used during SimulateMovement for proxies, this computes a new value for Acceleration before running proxy simulation.
The base implementation simply derives a value from the normalized Velocity value, which may help animations that want some indication of the direction of movement. Proxies don't implement predictive acceleration by default so this value is not used for the actual simulation.
References UpdateProxyAcceleration().
UpdateTickRegistration()
virtual void UMovementComponent::UpdateTickRegistration () virtual inherited
Update tick registration state, determined by bAutoUpdateTickRegistration.
Called by SetUpdatedComponent.
Reimplemented in UProjectileMovementComponent.
References UpdateTickRegistration().
UseAccelerationForPathFollowing()
UE_API bool INavMovementInterface::UseAccelerationForPathFollowing () const inherited
Returns true if acceleration should be used for path following.
References UE_API, and UseAccelerationForPathFollowing().
VerifyClientTimeStamp()
virtual bool UCharacterMovementComponent::VerifyClientTimeStamp (float TimeStamp, FNetworkPredictionData_Server_Character & ServerData) virtual
On the Server, verify that an incoming client TimeStamp is valid and has not yet expired.
It will also handle TimeStamp resets if it detects a gap larger than MinTimeBetweenTimeStampResets / 2.f !! ServerData.CurrentClientTimeStamp can be reset !!
Returns
true if TimeStamp is valid, or false if it has expired.
References VerifyClientTimeStamp().
VisualizeMovement()
virtual float UCharacterMovementComponent::VisualizeMovement () const virtual
Draw in-world debug information for character movement (called with p.VisualizeMovement > 0).
References VisualizeMovement().
Member Data Documentation
Acceleration
FVector UCharacterMovementComponent::Acceleration protected
Current acceleration vector (with magnitude).
This is calculated each update based on the input vector and the constraints of MaxAcceleration and the current movement mode.
Definition at line 636 of file CharacterMovementComponent.h.
AirControl
float UCharacterMovementComponent::AirControl
When falling, amount of lateral movement control available to the character.
0 = no control, 1 = full control at max speed of MaxWalkSpeed.
Definition at line 349 of file CharacterMovementComponent.h.
AirControlBoostMultiplier
float UCharacterMovementComponent::AirControlBoostMultiplier
When falling, multiplier applied to AirControl when lateral velocity is less than AirControlBoostVelocityThreshold.
Setting this to zero will disable air control boosting. Final result is clamped at 1.
Definition at line 356 of file CharacterMovementComponent.h.
AirControlBoostVelocityThreshold
float UCharacterMovementComponent::AirControlBoostVelocityThreshold
When falling, if lateral velocity magnitude is less than this value, AirControl is multiplied by AirControlBoostMultiplier.
Setting this to zero will disable air control boosting.
Definition at line 363 of file CharacterMovementComponent.h.
AnalogInputModifier
float UCharacterMovementComponent::AnalogInputModifier protected
Modifier to applied to values such as acceleration and max speed due to analog input.
Definition at line 680 of file CharacterMovementComponent.h.
AnimRootMotionVelocity
FVector UCharacterMovementComponent::AnimRootMotionVelocity
Velocity extracted from RootMotionParams when there is anim root motion active.
Invalid to use when HasAnimRootMotion() returns false.
Definition at line 2769 of file CharacterMovementComponent.h.
AsyncRootMotion
FRootMotionAsyncData UCharacterMovementComponent::AsyncRootMotion
Definition at line 2715 of file CharacterMovementComponent.h.
AsyncSimState
TSharedPtr<FCharacterMovementComponentAsyncOutput, ESPMode::ThreadSafe> UCharacterMovementComponent::AsyncSimState protected
Definition at line 175 of file CharacterMovementComponent.h.
AvoidanceConsiderationRadius
float UCharacterMovementComponent::AvoidanceConsiderationRadius
Definition at line 1107 of file CharacterMovementComponent.h.
AvoidanceGroup
FNavAvoidanceMask UCharacterMovementComponent::AvoidanceGroup
Moving actor's group mask.
Definition at line 1133 of file CharacterMovementComponent.h.
AvoidanceLockTimer
float UCharacterMovementComponent::AvoidanceLockTimer protected
remaining time of avoidance velocity lock
Definition at line 1099 of file CharacterMovementComponent.h.
AvoidanceLockVelocity
FVector UCharacterMovementComponent::AvoidanceLockVelocity protected
forced avoidance velocity, used when AvoidanceLockTimer is > 0
Definition at line 1096 of file CharacterMovementComponent.h.
AvoidanceUID
int32 UCharacterMovementComponent::AvoidanceUID
No default value, for now it's assumed to be valid if GetAvoidanceManager() returns non-NULL.
Definition at line 1129 of file CharacterMovementComponent.h.
AvoidanceWeight
float UCharacterMovementComponent::AvoidanceWeight
De facto default value 0.5 (due to that being the default in the avoidance registration function), indicates RVO behavior.
Definition at line 1163 of file CharacterMovementComponent.h.
bAllowPhysicsRotationDuringAnimRootMotion
uint8 UCharacterMovementComponent::bAllowPhysicsRotationDuringAnimRootMotion
Definition at line 1054 of file CharacterMovementComponent.h.
bAlwaysCheckFloor
uint8 UCharacterMovementComponent::bAlwaysCheckFloor
Whether we always force floor checks for stationary Characters while walking.
Normally floor checks are avoided if possible when not moving, but this can be used to force them if there are use-cases where they are being skipped erroneously (such as objects moving up into the character from below).
Definition at line 1017 of file CharacterMovementComponent.h.
bApplyGravityWhileJumping
uint8 UCharacterMovementComponent::bApplyGravityWhileJumping
Apply gravity while the character is actively jumping (e.g.
holding the jump key). Helps remove frame-rate dependent jump height, but may alter base jump height.
Definition at line 422 of file CharacterMovementComponent.h.
bAutoRegisterPhysicsVolumeUpdates
uint8 UMovementComponent::bAutoRegisterPhysicsVolumeUpdates inherited
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
If false, will not change bShouldUpdatePhysicsVolume on the UpdatedComponent at all.
See also
bComponentShouldUpdatePhysicsVolume
Definition at line 166 of file MovementComponent.h.
bAutoRegisterUpdatedComponent
uint8 UMovementComponent::bAutoRegisterUpdatedComponent inherited
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
Definition at line 148 of file MovementComponent.h.
bAutoUpdateTickRegistration
uint8 UMovementComponent::bAutoUpdateTickRegistration inherited
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
This will NOT enable tick at startup if bAutoActivate is false, because presumably you have a good reason for not wanting it to start ticking initially.
Definition at line 136 of file MovementComponent.h.
bBasedMovementIgnorePhysicsBase
bool UCharacterMovementComponent::bBasedMovementIgnorePhysicsBase = false
Property to set if UpdateBasedMovement should ignore collision with actors part of the current MovementBase, if the base is simulated by physics.
Definition at line 1392 of file CharacterMovementComponent.h.
bBaseOnAttachmentRoot
bool UCharacterMovementComponent::bBaseOnAttachmentRoot = false
Property to set if characters should stay based on objects attachment root instead of the traced object.
Definition at line 1396 of file CharacterMovementComponent.h.
bCanTrustClientOnLanding
bool UCharacterMovementComponent::bCanTrustClientOnLanding = false
Whether we're stepping off a moving platform (and should trust the client somewhat when landing).
Definition at line 1191 of file CharacterMovementComponent.h.
bCanWalkOffLedges
uint8 UCharacterMovementComponent::bCanWalkOffLedges
If true, Character can walk off a ledge.
Definition at line 507 of file CharacterMovementComponent.h.
bCanWalkOffLedgesWhenCrouching
uint8 UCharacterMovementComponent::bCanWalkOffLedgesWhenCrouching
If true, Character can walk off a ledge when crouching.
Definition at line 511 of file CharacterMovementComponent.h.
bCheatFlying
uint8 UCharacterMovementComponent::bCheatFlying
Instantly stop when in flying mode and no acceleration is being applied.
Definition at line 982 of file CharacterMovementComponent.h.
bComponentShouldUpdatePhysicsVolume
uint8 UMovementComponent::bComponentShouldUpdatePhysicsVolume inherited
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Only enabled if bAutoRegisterPhysicsVolumeUpdates is true. WARNING: UpdatePhysicsVolume is potentially expensive if overlap events are also disabled because it requires a separate query against all physics volumes in the world.
Definition at line 174 of file MovementComponent.h.
bConstrainToPlane
uint8 UMovementComponent::bConstrainToPlane inherited
If true, movement will be constrained to a plane.
See also
PlaneConstraintNormal, PlaneConstraintOrigin, PlaneConstraintAxisSetting
Definition at line 155 of file MovementComponent.h.
bCrouchMaintainsBaseLocation
uint8 UCharacterMovementComponent::bCrouchMaintainsBaseLocation
If true, crouching should keep the base of the capsule in place by lowering the center of the shrunken capsule.
If false, the base of the capsule moves up and the center stays in place. The same behavior applies when the character uncrouches: if true, the base is kept in the same location and the center moves up. If false, the capsule grows and only moves up if the base impacts something. By default this variable is set when the movement mode changes: set to true when walking and false otherwise. Feel free to override the behavior when the movement mode changes.
Definition at line 994 of file CharacterMovementComponent.h.
bDeferUpdateBasedMovement
uint8 UCharacterMovementComponent::bDeferUpdateBasedMovement protected
Flag set in pre-physics update to indicate that based movement should be updated post-physics.
Definition at line 1085 of file CharacterMovementComponent.h.
bDeferUpdateMoveComponent
uint8 UCharacterMovementComponent::bDeferUpdateMoveComponent
true to update CharacterOwner and UpdatedComponent after movement ends
Definition at line 543 of file CharacterMovementComponent.h.
bDontFallBelowJumpZVelocityDuringJump
uint8 UCharacterMovementComponent::bDontFallBelowJumpZVelocityDuringJump
True means while the jump key is held, we will not allow the vertical speed to fall below the JumpZVelocity tuning value even if a stronger force, such as gravity, is opposing the jump.
Definition at line 415 of file CharacterMovementComponent.h.
bEnablePhysicsInteraction
uint8 UCharacterMovementComponent::bEnablePhysicsInteraction
If enabled, the player will interact with physics objects when walking into them.
Definition at line 547 of file CharacterMovementComponent.h.
bEnableScopedMovementUpdates
uint8 UCharacterMovementComponent::bEnableScopedMovementUpdates
If true, high-level movement updates will be wrapped in a movement scope that accumulates updates and defers a bulk of the work until the end.
When enabled, touch and hit events will not be triggered until the end of multiple moves within an update, which can improve performance.
See also
FScopedMovementUpdate
Definition at line 468 of file CharacterMovementComponent.h.
bEnableServerDualMoveScopedMovementUpdates
uint8 UCharacterMovementComponent::bEnableServerDualMoveScopedMovementUpdates
Optional scoped movement update to combine moves for cheaper performance on the server when the client sends two moves in one packet.
Be warned that since this wraps a larger scope than is normally done with bEnableScopedMovementUpdates, this can result in subtle changes in behavior in regards to when overlap events are handled, when attached components are moved, etc.
See also
bEnableScopedMovementUpdates
Definition at line 478 of file CharacterMovementComponent.h.
bFastAttachedMove
uint8 UCharacterMovementComponent::bFastAttachedMove
Set this to true if riding on a moving base that you know is clear from non-moving world obstructions.
Optimization to avoid sweeps during based movement, use with care.
Definition at line 1009 of file CharacterMovementComponent.h.
bForceBraking_DEPRECATED
uint32 UCharacterMovementComponent::bForceBraking_DEPRECATED
Definition at line 619 of file CharacterMovementComponent.h.
bForceMaxAccel
uint8 UCharacterMovementComponent::bForceMaxAccel
Ignores size of acceleration component, and forces max acceleration to drive character at full velocity.
Definition at line 482 of file CharacterMovementComponent.h.
bForceNextFloorCheck
uint8 UCharacterMovementComponent::bForceNextFloorCheck
Force the Character in MOVE_Walking to do a check for a valid floor even if it hasn't moved.
Cleared after next floor check. Normally if bAlwaysCheckFloor is false we try to avoid the floor check unless some conditions are met, but this can be used to force the next check to always run.
Definition at line 498 of file CharacterMovementComponent.h.
bHasRequestedVelocity
uint8 UCharacterMovementComponent::bHasRequestedVelocity protected
Was velocity requested by path following?
Definition at line 1071 of file CharacterMovementComponent.h.
bIgnoreBaseRotation
uint8 UCharacterMovementComponent::bIgnoreBaseRotation
Whether the character ignores changes in rotation of the base it is standing on.
If true, the character maintains current world rotation. If false, the character rotates with the moving base.
Definition at line 1002 of file CharacterMovementComponent.h.
bIgnoreClientMovementErrorChecksAndCorrection
uint8 UCharacterMovementComponent::bIgnoreClientMovementErrorChecksAndCorrection
If true, we should ignore server location difference checks for client error on this movement component.
This can be useful when character is moving at extreme speeds for a duration and you need it to look smooth on clients without the server correcting the client. Make sure to disable when done, as this would break this character's server-client movement correction.
See also
bServerAcceptClientAuthoritativePosition, ServerCheckClientError()
Definition at line 961 of file CharacterMovementComponent.h.
bImpartBaseAngularVelocity
uint8 UCharacterMovementComponent::bImpartBaseAngularVelocity
If true, impart the base component's tangential components of angular velocity when jumping or falling off it.
Only those components of the velocity allowed by the separate component settings (bImpartBaseVelocityX etc) will be applied.
See also
bImpartBaseVelocityX, bImpartBaseVelocityY, bImpartBaseVelocityZ
Definition at line 935 of file CharacterMovementComponent.h.
bImpartBaseVelocityX
uint8 UCharacterMovementComponent::bImpartBaseVelocityX
If true, impart the base actor's X velocity when falling off it (which includes jumping)
Definition at line 919 of file CharacterMovementComponent.h.
bImpartBaseVelocityY
uint8 UCharacterMovementComponent::bImpartBaseVelocityY
If true, impart the base actor's Y velocity when falling off it (which includes jumping)
Definition at line 923 of file CharacterMovementComponent.h.
bImpartBaseVelocityZ
uint8 UCharacterMovementComponent::bImpartBaseVelocityZ
If true, impart the base actor's Z velocity when falling off it (which includes jumping)
Definition at line 927 of file CharacterMovementComponent.h.
bIsNavWalkingOnServer
uint8 UCharacterMovementComponent::bIsNavWalkingOnServer
Set on clients when server's movement mode is NavWalking.
Definition at line 1047 of file CharacterMovementComponent.h.
bJustTeleported
uint8 UCharacterMovementComponent::bJustTeleported
Used by movement code to determine if a change in position is based on normal movement or a teleport.
If not a teleport, velocity can be recomputed based on the change in position.
Definition at line 939 of file CharacterMovementComponent.h.
bLastClientIsFalling
bool UCharacterMovementComponent::bLastClientIsFalling = false
Remember if the client was previously falling so we can tell when they've just landed.
Definition at line 1179 of file CharacterMovementComponent.h.
bLastServerIsFalling
bool UCharacterMovementComponent::bLastServerIsFalling = false
Remember if the server was previously falling so we can tell when they've just landed.
Definition at line 1182 of file CharacterMovementComponent.h.
bLastServerIsWalking
bool UCharacterMovementComponent::bLastServerIsWalking = false
Whether we were just walking on something, used to help with transitions off moving objects.
Definition at line 1185 of file CharacterMovementComponent.h.
bMaintainHorizontalGroundVelocity
uint8 UCharacterMovementComponent::bMaintainHorizontalGroundVelocity
If true, walking movement always maintains horizontal velocity when moving up ramps, which causes movement up ramps to be faster parallel to the ramp surface.
If false, then walking movement maintains velocity magnitude parallel to the ramp surface.
Definition at line 915 of file CharacterMovementComponent.h.
bMovementInProgress
uint8 UCharacterMovementComponent::bMovementInProgress protected
True during movement update.
Used internally so that attempts to change CharacterOwner and UpdatedComponent are deferred until after an update.
See also
IsMovementInProgress()
Definition at line 457 of file CharacterMovementComponent.h.
bMovementModeDirty
bool UCharacterMovementComponent::bMovementModeDirty = false protected
Definition at line 176 of file CharacterMovementComponent.h.
bNetworkAlwaysReplicateTransformUpdateTimestamp
uint8 UCharacterMovementComponent::bNetworkAlwaysReplicateTransformUpdateTimestamp
Flag used on the server to determine whether to always replicate ReplicatedServerLastTransformUpdateTimeStamp to clients.
Normally this is only sent when the network smoothing mode on character movement is set to Linear smoothing (on the server), to save bandwidth. Setting this to true will force the timestamp to replicate regardless, in case the server doesn't know about the smoothing mode, or if the timestamp is used for another purpose.
Definition at line 537 of file CharacterMovementComponent.h.
bNetworkGravityDirectionChanged
uint8 UCharacterMovementComponent::bNetworkGravityDirectionChanged
True when the networked gravity direction has been replicated.
Definition at line 951 of file CharacterMovementComponent.h.
bNetworkLargeClientCorrection
uint8 UCharacterMovementComponent::bNetworkLargeClientCorrection
Flag indicating the client correction was larger than NetworkLargeClientCorrectionThreshold.
Definition at line 522 of file CharacterMovementComponent.h.
bNetworkMovementModeChanged
uint8 UCharacterMovementComponent::bNetworkMovementModeChanged
True when the networked movement mode has been replicated.
Definition at line 947 of file CharacterMovementComponent.h.
bNetworkSkipProxyPredictionOnNetUpdate
uint8 UCharacterMovementComponent::bNetworkSkipProxyPredictionOnNetUpdate
Whether we skip prediction on frames where a proxy receives a network update.
This can avoid expensive prediction on those frames, with the side-effect of predicting with a frame of additional latency.
Definition at line 529 of file CharacterMovementComponent.h.
bNetworkSmoothingComplete
uint8 UCharacterMovementComponent::bNetworkSmoothingComplete
Signals that smoothed position/rotation has reached target, and no more smoothing is necessary until a future update.
This is used as an optimization to skip calls to SmoothClientPosition() when true. SmoothCorrection() sets it false when a new network update is received. SmoothClientPosition_Interpolate() sets this to true when the interpolation reaches the target, before one last call to SmoothClientPosition_UpdateVisuals(). If this is not desired, override SmoothClientPosition() to always set this to false to avoid this feature.
Definition at line 519 of file CharacterMovementComponent.h.
bNetworkUpdateReceived
uint8 UCharacterMovementComponent::bNetworkUpdateReceived
True when a network replication update is received for simulated proxies.
Definition at line 943 of file CharacterMovementComponent.h.
bNotifyApex
uint8 UCharacterMovementComponent::bNotifyApex
If true, event NotifyJumpApex() to CharacterOwner's controller when at apex of jump.
Is cleared when event is triggered. By default this is off, and if you want the event to fire you typically set it to true when movement mode changes to "Falling" from another mode (see OnMovementModeChanged).
Definition at line 978 of file CharacterMovementComponent.h.
bOrientRotationToMovement
uint8 UCharacterMovementComponent::bOrientRotationToMovement
If true, rotate the Character toward the direction of acceleration, using RotationRate as the rate of rotation change.
Overrides UseControllerDesiredRotation. Normally you will want to make sure that other settings are cleared, such as bUseControllerRotationYaw on the Character.
Definition at line 435 of file CharacterMovementComponent.h.
bPerformingJumpOff
uint8 UCharacterMovementComponent::bPerformingJumpOff
Used to prevent reentry of JumpOff()
Definition at line 1028 of file CharacterMovementComponent.h.
bProjectNavMeshOnBothWorldChannels
uint8 UCharacterMovementComponent::bProjectNavMeshOnBothWorldChannels protected
Use both WorldStatic and WorldDynamic channels for NavWalking geometry conforming.
Definition at line 1093 of file CharacterMovementComponent.h.
bProjectNavMeshWalking
uint8 UCharacterMovementComponent::bProjectNavMeshWalking protected
Whether to raycast to underlying geometry to better conform navmesh-walking characters.
Definition at line 1089 of file CharacterMovementComponent.h.
bPushForceScaledToMass
uint8 UCharacterMovementComponent::bPushForceScaledToMass
If enabled, the PushForceFactor is applied per kg mass of the affected object.
Definition at line 555 of file CharacterMovementComponent.h.
bPushForceUsingZOffset
uint8 UCharacterMovementComponent::bPushForceUsingZOffset
If enabled, the PushForce location is moved using PushForcePointZOffsetFactor.
Otherwise simply use the impact point.
Definition at line 559 of file CharacterMovementComponent.h.
BRAKE_TO_STOP_VELOCITY
const float UCharacterMovementComponent::BRAKE_TO_STOP_VELOCITY static
Stop completely when braking and velocity magnitude is lower than this.
Definition at line 2866 of file CharacterMovementComponent.h.
BrakingDecelerationFalling
float UCharacterMovementComponent::BrakingDecelerationFalling
Lateral deceleration when falling and not applying acceleration.
See also
MaxAcceleration
Definition at line 328 of file CharacterMovementComponent.h.
BrakingDecelerationFlying
float UCharacterMovementComponent::BrakingDecelerationFlying
Deceleration when flying and not applying acceleration.
See also
MaxAcceleration
Definition at line 342 of file CharacterMovementComponent.h.
BrakingDecelerationSwimming
float UCharacterMovementComponent::BrakingDecelerationSwimming
Deceleration when swimming and not applying acceleration.
See also
MaxAcceleration
Definition at line 335 of file CharacterMovementComponent.h.
BrakingDecelerationWalking
float UCharacterMovementComponent::BrakingDecelerationWalking
Deceleration when walking and not applying acceleration.
This is a constant opposing force that directly lowers velocity by a constant value.
See also
GroundFriction, MaxAcceleration
Definition at line 321 of file CharacterMovementComponent.h.
BrakingFriction
float UCharacterMovementComponent::BrakingFriction
Friction (drag) coefficient applied when braking (whenever Acceleration = 0, or if character is exceeding max speed); actual value used is this multiplied by BrakingFrictionFactor.
When braking, this property allows you to control how much friction is applied when moving across the ground, applying an opposing force that scales with current velocity. Braking is composed of friction (velocity-dependent drag) and constant deceleration. This is the current value, used in all movement modes; if this is not desired, override it or bUseSeparateBrakingFriction when movement mode changes. \note Only used if bUseSeparateBrakingFriction setting is true, otherwise current friction such as GroundFriction is used.
See also
bUseSeparateBrakingFriction, BrakingFrictionFactor, GroundFriction, BrakingDecelerationWalking
Definition at line 308 of file CharacterMovementComponent.h.
BrakingFrictionFactor
float UCharacterMovementComponent::BrakingFrictionFactor
Factor used to multiply actual value of friction used when braking.
This applies to any friction value that is currently used, which may depend on bUseSeparateBrakingFriction. \note This is 2 by default for historical reasons, a value of 1 gives the true drag equation.
See also
bUseSeparateBrakingFriction, GroundFriction, BrakingFriction
Definition at line 297 of file CharacterMovementComponent.h.
BrakingSubStepTime
float UCharacterMovementComponent::BrakingSubStepTime
Time substepping when applying braking friction.
Smaller time steps increase accuracy at the slight cost of performance, especially if there are large frame times.
Definition at line 314 of file CharacterMovementComponent.h.
bRequestedMoveUseAcceleration
uint8 UCharacterMovementComponent::bRequestedMoveUseAcceleration
Should use acceleration for path following?
If true, acceleration is applied when path following to reach the target velocity. If false, path following velocity is set directly, disregarding acceleration.
Definition at line 1044 of file CharacterMovementComponent.h.
bRequestedMoveWithMaxSpeed
uint8 UCharacterMovementComponent::bRequestedMoveWithMaxSpeed protected
Was acceleration requested to be always max speed?
Definition at line 1075 of file CharacterMovementComponent.h.
bRunPhysicsWithNoController
uint8 UCharacterMovementComponent::bRunPhysicsWithNoController
If true, movement will be performed even if there is no Controller for the Character owner.
Normally without a Controller, movement will be aborted and velocity and acceleration are zeroed if the character is walking. Characters that are spawned without a Controller but with this flag enabled will initialize the movement mode to DefaultLandMovementMode or DefaultWaterMovementMode appropriately.
See also
DefaultLandMovementMode, DefaultWaterMovementMode
Definition at line 491 of file CharacterMovementComponent.h.
bScalePushForceToVelocity
uint8 UCharacterMovementComponent::bScalePushForceToVelocity
If enabled, the applied push force will try to get the physics object to the same velocity than the player, not faster.
This will only scale the force down, it will never apply more force than defined by PushForceFactor.
Definition at line 564 of file CharacterMovementComponent.h.
bServerAcceptClientAuthoritativePosition
uint8 UCharacterMovementComponent::bServerAcceptClientAuthoritativePosition
If true, and server does not detect client position error, server will copy the client movement location/velocity/etc after simulating the move.
This can be useful for short bursts of movement that are difficult to sync over the network. Note that if bIgnoreClientMovementErrorChecksAndCorrection is used, this means the server will not detect an error. Also see GameNetworkManager->ClientAuthorativePosition which permanently enables this behavior.
See also
bIgnoreClientMovementErrorChecksAndCorrection, ServerShouldUseAuthoritativePosition()
Definition at line 971 of file CharacterMovementComponent.h.
bShrinkProxyCapsule
uint8 UCharacterMovementComponent::bShrinkProxyCapsule
If true, the capsule needs to be shrunk on this simulated proxy, to avoid replication rounding putting us in geometry.
Whenever this is set to true, this will cause the capsule to be shrunk again on the next update, and then set to false.
Definition at line 503 of file CharacterMovementComponent.h.
bSnapToPlaneAtStart
uint8 UMovementComponent::bSnapToPlaneAtStart inherited
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
Definition at line 159 of file MovementComponent.h.
bStayBasedInAir
bool UCharacterMovementComponent::bStayBasedInAir = false
Property to set if characters should stay based on objects while jumping.
Definition at line 1400 of file CharacterMovementComponent.h.
bStopMovementAbortPaths_DEPRECATED
uint8 UNavMovementComponent::bStopMovementAbortPaths_DEPRECATED protected inherited
If set, StopActiveMovement call will abort current path following request.
Definition at line 53 of file NavMovementComponent.h.
bSweepWhileNavWalking
uint8 UCharacterMovementComponent::bSweepWhileNavWalking
Whether or not the character should sweep for collision geometry while walking.
See also
USceneComponent::MoveComponent.
Definition at line 442 of file CharacterMovementComponent.h.
bTeleportedSinceLastUpdate
bool UCharacterMovementComponent::bTeleportedSinceLastUpdate = false
True if the UpdatedComponent was moved outside of this CharacterMovementComponent since the last move – its starting location for this update doesn't match its ending position for the previous update.
Definition at line 1188 of file CharacterMovementComponent.h.
bTickBeforeOwner
uint8 UMovementComponent::bTickBeforeOwner inherited
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
This is important when our tick causes an update in the owner's position, so that when the owner ticks it uses the most recent position without lag. Disabling this can improve performance if both objects tick but the order of ticks doesn't matter.
Definition at line 144 of file MovementComponent.h.
bTouchForceScaledToMass
uint8 UCharacterMovementComponent::bTouchForceScaledToMass
If enabled, the TouchForceFactor is applied per kg mass of the affected object.
Definition at line 551 of file CharacterMovementComponent.h.
Buoyancy
float UCharacterMovementComponent::Buoyancy
Water buoyancy.
A ratio (1.0 = neutral buoyancy, 0.0 = no buoyancy)
Definition at line 380 of file CharacterMovementComponent.h.
bUpdateNavAgentWithOwnersCollision_DEPRECATED
uint8 UNavMovementComponent::bUpdateNavAgentWithOwnersCollision_DEPRECATED protected inherited
If set to true NavAgentProps' radius and height will be updated with Owner's collision capsule size.
Definition at line 39 of file NavMovementComponent.h.
bUpdateOnlyIfRendered
uint8 UMovementComponent::bUpdateOnlyIfRendered inherited
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
Definition at line 129 of file MovementComponent.h.
bUseAccelerationForPaths_DEPRECATED
uint8 UNavMovementComponent::bUseAccelerationForPaths_DEPRECATED protected inherited
If set, pathfollowing will control character movement via acceleration values.
If false, it will set velocities directly.
Definition at line 44 of file NavMovementComponent.h.
bUseControllerDesiredRotation
uint8 UCharacterMovementComponent::bUseControllerDesiredRotation
If true, smoothly rotate the Character toward the Controller's desired rotation (typically Controller->ControlRotation), using RotationRate as the rate of rotation change.
Overridden by OrientRotationToMovement. Normally you will want to make sure that other settings are cleared, such as bUseControllerRotationYaw on the Character.
Definition at line 428 of file CharacterMovementComponent.h.
bUseFixedBrakingDistanceForPaths_DEPRECATED
uint8 UNavMovementComponent::bUseFixedBrakingDistanceForPaths_DEPRECATED protected inherited
If set, FixedPathBrakingDistance will be used for path following deceleration.
Definition at line 49 of file NavMovementComponent.h.
bUseFlatBaseForFloorChecks
uint8 UCharacterMovementComponent::bUseFlatBaseForFloorChecks
Performs floor checks as if the character is using a shape with a flat base.
This avoids the situation where characters slowly lower off the side of a ledge (as their capsule 'balances' on the edge).
Definition at line 1024 of file CharacterMovementComponent.h.
bUseRVOAvoidance
uint8 UCharacterMovementComponent::bUseRVOAvoidance
If set, component will use RVO avoidance.
This only runs on the server.
Definition at line 1036 of file CharacterMovementComponent.h.
bUseRVOPostProcess
uint8 UCharacterMovementComponent::bUseRVOPostProcess protected
if set, PostProcessAvoidanceVelocity will be called
Definition at line 1082 of file CharacterMovementComponent.h.
bUseSeparateBrakingFriction
uint8 UCharacterMovementComponent::bUseSeparateBrakingFriction
If true, BrakingFriction will be used to slow the character to a stop (when there is no Acceleration).
If false, braking uses the same friction passed to CalcVelocity() (ie GroundFriction when walking), multiplied by BrakingFrictionFactor. This setting applies to all movement modes; if only desired in certain modes, consider toggling it when movement modes change.
See also
BrakingFriction
Definition at line 408 of file CharacterMovementComponent.h.
bWantsToCrouch
uint8 UCharacterMovementComponent::bWantsToCrouch
If true, try to crouch (or keep crouching) on next update.
If false, try to stop crouching on next update.
Definition at line 986 of file CharacterMovementComponent.h.
bWantsToLeaveNavWalking
uint8 UCharacterMovementComponent::bWantsToLeaveNavWalking
Used to safely leave NavWalking movement mode.
Definition at line 1032 of file CharacterMovementComponent.h.
bWasAvoidanceUpdated
uint8 UCharacterMovementComponent::bWasAvoidanceUpdated protected
Was avoidance updated in this frame?
Definition at line 1079 of file CharacterMovementComponent.h.
bWasSimulatingRootMotion
uint8 UCharacterMovementComponent::bWasSimulatingRootMotion
True when SimulatedProxies are simulating RootMotion.
Definition at line 1051 of file CharacterMovementComponent.h.
CachedNavLocation
FNavLocation UCharacterMovementComponent::CachedNavLocation
last known location projected on navmesh, used by NavWalking mode
Definition at line 1170 of file CharacterMovementComponent.h.
CachedProjectedNavMeshHitResult
FHitResult UCharacterMovementComponent::CachedProjectedNavMeshHitResult
Last valid projected hit result from raycast to geometry from navmesh.
Definition at line 1173 of file CharacterMovementComponent.h.
CharacterOwner
TObjectPtr<ACharacter> UCharacterMovementComponent::CharacterOwner protected
Character movement component belongs to.
Definition at line 149 of file CharacterMovementComponent.h.
ClientPredictionData
class FNetworkPredictionData_Client_Character* UCharacterMovementComponent::ClientPredictionData protected
Definition at line 2303 of file CharacterMovementComponent.h.
CrouchedHalfHeight
float UCharacterMovementComponent::CrouchedHalfHeight
Collision half-height when crouching (component scale is applied separately)
Definition at line 376 of file CharacterMovementComponent.h.
CrouchedSpeedMultiplier_DEPRECATED
float UCharacterMovementComponent::CrouchedSpeedMultiplier_DEPRECATED
Multiplier to max ground speed to use when crouched.
Definition at line 623 of file CharacterMovementComponent.h.
CurrentFloor
FFindFloorResult UCharacterMovementComponent::CurrentFloor
Information about the floor the Character is standing on (updated only during walking movement).
Definition at line 876 of file CharacterMovementComponent.h.
CurrentRootMotion
FRootMotionSourceGroup UCharacterMovementComponent::CurrentRootMotion
Root Motion Group containing active root motion sources being applied to movement.
Definition at line 2710 of file CharacterMovementComponent.h.
CustomMovementMode
uint8 UCharacterMovementComponent::CustomMovementMode
Current custom sub-mode if MovementMode is set to Custom.
This is automatically replicated through the Character owner and for client-server movement functions.
See also
SetMovementMode()
Definition at line 237 of file CharacterMovementComponent.h.
DecayingFormerBaseVelocity
FVector UCharacterMovementComponent::DecayingFormerBaseVelocity = FVector::ZeroVector
Left over velocity when leaving a moving base.
Helps with airborne root motion.
Definition at line 1197 of file CharacterMovementComponent.h.
DefaultGravityDirection
const FVector UCharacterMovementComponent::DefaultGravityDirection static
The default direction that gravity points for movement simulation.
Definition at line 240 of file CharacterMovementComponent.h.
DefaultLandMovementMode
TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::DefaultLandMovementMode
Default movement mode when not in water.
Used at player startup or when teleported.
See also
DefaultWaterMovementMode
bRunPhysicsWithNoController
Definition at line 884 of file CharacterMovementComponent.h.
DefaultWaterMovementMode
TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::DefaultWaterMovementMode
Default movement mode when in water.
Used at player startup or when teleported.
See also
DefaultLandMovementMode
bRunPhysicsWithNoController
Definition at line 892 of file CharacterMovementComponent.h.
DeferredUpdatedMoveComponent
TObjectPtr<USceneComponent> UCharacterMovementComponent::DeferredUpdatedMoveComponent
What to update CharacterOwner and UpdatedComponent after movement ends.
Definition at line 568 of file CharacterMovementComponent.h.
FallingLateralFriction
float UCharacterMovementComponent::FallingLateralFriction
Friction to apply to lateral air movement when falling.
If bUseSeparateBrakingFriction is false, also affects the ability to stop more quickly when braking (whenever Acceleration is zero).
See also
BrakingFriction, bUseSeparateBrakingFriction
Definition at line 371 of file CharacterMovementComponent.h.
FixedPathBrakingDistance_DEPRECATED
float UNavMovementComponent::FixedPathBrakingDistance_DEPRECATED protected inherited
Braking distance override used with acceleration driven path following (bUseAccelerationForPaths)
Definition at line 34 of file NavMovementComponent.h.
FormerBaseVelocityDecayHalfLife
float UCharacterMovementComponent::FormerBaseVelocityDecayHalfLife = 0.f
When applying a root motion override while falling off a moving object, this controls how long it takes to lose half the former base's velocity (in seconds).
Set to 0 to ignore former bases (default). Set to -1 for no decay. Any other positive value sets the half-life for exponential decay.
Definition at line 1063 of file CharacterMovementComponent.h.
GravityScale
float UCharacterMovementComponent::GravityScale
Custom gravity scale.
Gravity is multiplied by this amount for the character.
Definition at line 155 of file CharacterMovementComponent.h.
GroundFriction
float UCharacterMovementComponent::GroundFriction
Setting that affects movement control.
Higher values allow faster changes in direction. If bUseSeparateBrakingFriction is false, also affects the ability to stop more quickly when braking (whenever Acceleration is zero), where it is multiplied by BrakingFrictionFactor. When braking, this property allows you to control how much friction is applied when moving across the ground, applying an opposing force that scales with current velocity. This can be used to simulate slippery surfaces such as ice or oil by changing the value (possibly based on the material pawn is standing on).
See also
BrakingDecelerationWalking, BrakingFriction, bUseSeparateBrakingFriction, BrakingFrictionFactor
Definition at line 254 of file CharacterMovementComponent.h.
GroupsToAvoid
FNavAvoidanceMask UCharacterMovementComponent::GroupsToAvoid
Will avoid other agents if they are in one of specified groups.
Definition at line 1143 of file CharacterMovementComponent.h.
GroupsToIgnore
FNavAvoidanceMask UCharacterMovementComponent::GroupsToIgnore
Will NOT avoid other agents if they are in one of specified groups, higher priority than GroupsToAvoid.
Definition at line 1153 of file CharacterMovementComponent.h.
InitialPushForceFactor
float UCharacterMovementComponent::InitialPushForceFactor
Initial impulse force to apply when the player bounces into a blocking physics object.
Definition at line 588 of file CharacterMovementComponent.h.
JumpOffJumpZFactor
float UCharacterMovementComponent::JumpOffJumpZFactor
Fraction of JumpZVelocity to use when automatically "jumping off" of a base actor that's not allowed to be a base for a character.
(For example, if you're not allowed to stand on other players.)
Definition at line 167 of file CharacterMovementComponent.h.
JumpOutOfWaterPitch
float UCharacterMovementComponent::JumpOutOfWaterPitch
When exiting water, jump if control pitch angle is this high or above.
Definition at line 872 of file CharacterMovementComponent.h.
JumpZVelocity
float UCharacterMovementComponent::JumpZVelocity
Initial velocity (instantaneous vertical acceleration) when jumping.
Definition at line 163 of file CharacterMovementComponent.h.
LastServerMovementBaseBoneName
FName UCharacterMovementComponent::LastServerMovementBaseBoneName = NAME_None
Remember last server movement base bone so we can detect mounts/dismounts and respond accordingly.
Definition at line 1176 of file CharacterMovementComponent.h.
LastStuckWarningTime
float UCharacterMovementComponent::LastStuckWarningTime protected
Used for throttling "stuck in geometry" logging.
Definition at line 686 of file CharacterMovementComponent.h.
LastTimeStampResetServerTime
float UCharacterMovementComponent::LastTimeStampResetServerTime protected
Clock time on the server of the last timestamp reset.
Definition at line 2428 of file CharacterMovementComponent.h.
LastUpdateLocation
FVector UCharacterMovementComponent::LastUpdateLocation protected
Location after last PerformMovement or SimulateMovement update.
Used internally to detect changes in position from outside character movement to try to validate the current floor.
Definition at line 648 of file CharacterMovementComponent.h.
LastUpdateRequestedVelocity
FVector UCharacterMovementComponent::LastUpdateRequestedVelocity
Velocity requested by path following during last Update Updated when we consume the value.
Definition at line 1121 of file CharacterMovementComponent.h.
LastUpdateRotation
FQuat UCharacterMovementComponent::LastUpdateRotation protected
Rotation after last PerformMovement or SimulateMovement update.
Definition at line 642 of file CharacterMovementComponent.h.
LastUpdateVelocity
FVector UCharacterMovementComponent::LastUpdateVelocity protected
Velocity after last PerformMovement or SimulateMovement update.
Used internally to detect changes in velocity from external sources.
Definition at line 654 of file CharacterMovementComponent.h.
LedgeCheckThreshold
float UCharacterMovementComponent::LedgeCheckThreshold
Used in determining if pawn is going off ledge.
If the ledge is "shorter" than this value then the pawn will be able to walk off it.
Definition at line 868 of file CharacterMovementComponent.h.
ListenServerNetworkSimulatedSmoothLocationTime
float UCharacterMovementComponent::ListenServerNetworkSimulatedSmoothLocationTime
Similar setting as NetworkSimulatedSmoothLocationTime but only used on Listen servers.
Definition at line 804 of file CharacterMovementComponent.h.
ListenServerNetworkSimulatedSmoothRotationTime
float UCharacterMovementComponent::ListenServerNetworkSimulatedSmoothRotationTime
Similar setting as NetworkSimulatedSmoothRotationTime but only used on Listen servers.
Definition at line 810 of file CharacterMovementComponent.h.
Mass
float UCharacterMovementComponent::Mass
Mass of pawn (for when momentum is imparted to it).
Definition at line 580 of file CharacterMovementComponent.h.
MAX_FLOOR_DIST
const float UCharacterMovementComponent::MAX_FLOOR_DIST static
Maximum acceptable distance for Character capsule to float above floor when walking.
Definition at line 2860 of file CharacterMovementComponent.h.
MaxAcceleration
float UCharacterMovementComponent::MaxAcceleration
Max Acceleration (rate of change of velocity)
Definition at line 284 of file CharacterMovementComponent.h.
MaxCustomMovementSpeed
float UCharacterMovementComponent::MaxCustomMovementSpeed
The maximum speed when using Custom movement mode.
Definition at line 280 of file CharacterMovementComponent.h.
MaxDepenetrationWithGeometry
float UCharacterMovementComponent::MaxDepenetrationWithGeometry
Max distance we allow simulated proxies to depenetrate when moving out of anything but Pawns.
This is generally more tolerant than with Pawns, because other geometry is either not moving, or is moving predictably with a bit of delay compared to on the server.
See also
MaxDepenetrationWithGeometryAsProxy, MaxDepenetrationWithPawn, MaxDepenetrationWithPawnAsProxy
Definition at line 763 of file CharacterMovementComponent.h.
MaxDepenetrationWithGeometryAsProxy
float UCharacterMovementComponent::MaxDepenetrationWithGeometryAsProxy
Max distance we allow simulated proxies to depenetrate when moving out of anything but Pawns.
This is generally more tolerant than with Pawns, because other geometry is either not moving, or is moving predictably with a bit of delay compared to on the server.
See also
MaxDepenetrationWithGeometry, MaxDepenetrationWithPawn, MaxDepenetrationWithPawnAsProxy
Definition at line 771 of file CharacterMovementComponent.h.
MaxDepenetrationWithPawn
float UCharacterMovementComponent::MaxDepenetrationWithPawn
Max distance we are allowed to depenetrate when moving out of other Pawns.
See also
MaxDepenetrationWithGeometry, MaxDepenetrationWithGeometryAsProxy, MaxDepenetrationWithPawnAsProxy
Definition at line 778 of file CharacterMovementComponent.h.
MaxDepenetrationWithPawnAsProxy
float UCharacterMovementComponent::MaxDepenetrationWithPawnAsProxy
Max distance we allow simulated proxies to depenetrate when moving out of other Pawns.
Typically we don't want a large value, because we receive a server authoritative position that we should not then ignore by pushing them out of the local player.
See also
MaxDepenetrationWithGeometry, MaxDepenetrationWithGeometryAsProxy, MaxDepenetrationWithPawn
Definition at line 786 of file CharacterMovementComponent.h.
MaxFlySpeed
float UCharacterMovementComponent::MaxFlySpeed
The maximum flying speed.
Definition at line 276 of file CharacterMovementComponent.h.
MaxJumpApexAttemptsPerSimulation
int32 UCharacterMovementComponent::MaxJumpApexAttemptsPerSimulation
Max number of attempts per simulation to attempt to exactly reach the jump apex when falling movement reaches the top of the arc.
Limiting this prevents deep recursion when special cases cause collision or other conditions which reactivate the apex condition.
Definition at line 755 of file CharacterMovementComponent.h.
MaxOutOfWaterStepHeight
float UCharacterMovementComponent::MaxOutOfWaterStepHeight
Maximum step height for getting out of water.
Definition at line 572 of file CharacterMovementComponent.h.
MaxServerClientErrorWhileFalling
float UCharacterMovementComponent::MaxServerClientErrorWhileFalling = 0.f
How loosely the client can follow the server location during this fall.
Definition at line 1194 of file CharacterMovementComponent.h.
MaxSimulationIterations
int32 UCharacterMovementComponent::MaxSimulationIterations
Max number of iterations used for each discrete simulation step.
Used primarily in the the more advanced movement modes that break up larger time steps (usually those applying gravity such as falling and walking). Increasing this value can address issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationTimeStep
Definition at line 748 of file CharacterMovementComponent.h.
MaxSimulationTimeStep
float UCharacterMovementComponent::MaxSimulationTimeStep
Max time delta for each discrete simulation step.
Used primarily in the the more advanced movement modes that break up larger time steps (usually those applying gravity such as falling and walking). Lowering this value can address issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationIterations
Definition at line 737 of file CharacterMovementComponent.h.
MaxStepHeight
float UCharacterMovementComponent::MaxStepHeight
Maximum height character can step up.
Definition at line 159 of file CharacterMovementComponent.h.
MaxSwimSpeed
float UCharacterMovementComponent::MaxSwimSpeed
The maximum swimming speed.
Definition at line 272 of file CharacterMovementComponent.h.
MaxTouchForce
float UCharacterMovementComponent::MaxTouchForce
Maximum force applied to touched physics objects.
If < 0.0f, there is no maximum.
Definition at line 608 of file CharacterMovementComponent.h.
MaxWalkSpeed
float UCharacterMovementComponent::MaxWalkSpeed
The maximum ground speed when walking.
Also determines maximum lateral speed when falling.
Definition at line 264 of file CharacterMovementComponent.h.
MaxWalkSpeedCrouched
float UCharacterMovementComponent::MaxWalkSpeedCrouched
The maximum ground speed when walking and crouched.
Definition at line 268 of file CharacterMovementComponent.h.
MIN_FLOOR_DIST
const float UCharacterMovementComponent::MIN_FLOOR_DIST static
Minimum acceptable distance for Character capsule to float above floor when walking.
Definition at line 2857 of file CharacterMovementComponent.h.
MIN_TICK_TIME
const float UCharacterMovementComponent::MIN_TICK_TIME static
Minimum delta time considered when ticking.
Delta times below this are not considered. This is a very small non-zero value to avoid potential divide-by-zero in simulation code.
Definition at line 2854 of file CharacterMovementComponent.h.
MinAnalogWalkSpeed
float UCharacterMovementComponent::MinAnalogWalkSpeed
The ground speed that we should accelerate up to when walking at minimum analog stick tilt.
Definition at line 288 of file CharacterMovementComponent.h.
MinTimeBetweenTimeStampResets
float UCharacterMovementComponent::MinTimeBetweenTimeStampResets
Minimum time between client TimeStamp resets.
!! This has to be large enough so that we don't confuse the server if the client can stall or timeout. We do this as we use floats for TimeStamps, and server derives DeltaTime from two TimeStamps. As time goes on, accuracy decreases from those floating point numbers. So we trigger a TimeStamp reset at regular intervals to maintain a high level of accuracy.
Definition at line 2417 of file CharacterMovementComponent.h.
MinTouchForce
float UCharacterMovementComponent::MinTouchForce
Minimum Force applied to touched physics objects.
If < 0.0f, there is no minimum.
Definition at line 604 of file CharacterMovementComponent.h.
MovementMode
TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::MovementMode
Actor's current movement mode (walking, falling, etc).
walking: Walking on a surface, under the effects of friction, and able to "step up" barriers. Vertical velocity is zero.
falling: Falling under the effects of gravity, after jumping or walking off the edge of a surface.
flying: Flying, ignoring the effects of gravity.
swimming: Swimming through a fluid volume, under the effects of gravity and buoyancy.
custom: User-defined custom movement mode, including many possible sub-modes. This is automatically replicated through the Character owner and for client-server movement functions.
See also
SetMovementMode(), CustomMovementMode
Definition at line 229 of file CharacterMovementComponent.h.
MovementState
FMovementProperties UNavMovementComponent::MovementState inherited
Expresses runtime state of character's movement.
Put all temporal changes to movement properties here
Definition at line 65 of file NavMovementComponent.h.
NavAgentProps
FNavAgentProperties UNavMovementComponent::NavAgentProps inherited
Properties that define how the component can move.
Definition at line 61 of file NavMovementComponent.h.
NavMeshProjectionHeightScaleDown
float UCharacterMovementComponent::NavMeshProjectionHeightScaleDown
Scale of the total capsule height to use for projection from navmesh to underlying geometry in the downward direction.
In other words, trace down to [CapsuleHeight * NavMeshProjectionHeightScaleDown] below nav mesh.
Definition at line 1222 of file CharacterMovementComponent.h.
NavMeshProjectionHeightScaleUp
float UCharacterMovementComponent::NavMeshProjectionHeightScaleUp
Scale of the total capsule height to use for projection from navmesh to underlying geometry in the upward direction.
In other words, start the trace at [CapsuleHeight * NavMeshProjectionHeightScaleUp] above nav mesh.
Definition at line 1215 of file CharacterMovementComponent.h.
NavMeshProjectionInterpSpeed
float UCharacterMovementComponent::NavMeshProjectionInterpSpeed
Speed at which to interpolate agent navmesh offset between traces.
0: Instant (no interp) > 0: Interp speed")
Definition at line 1208 of file CharacterMovementComponent.h.
NavMeshProjectionInterval
float UCharacterMovementComponent::NavMeshProjectionInterval
How often we should raycast to project from navmesh to underlying geometry.
Definition at line 1201 of file CharacterMovementComponent.h.
NavMeshProjectionTimer
float UCharacterMovementComponent::NavMeshProjectionTimer
Definition at line 1204 of file CharacterMovementComponent.h.
NavMovementProperties
FNavMovementProperties UNavMovementComponent::NavMovementProperties protected inherited
Definition at line 56 of file NavMovementComponent.h.
NavWalkingFloorDistTolerance
float UCharacterMovementComponent::NavWalkingFloorDistTolerance
Ignore small differences in ground height between server and client data during NavWalking mode.
Definition at line 1226 of file CharacterMovementComponent.h.
NetProxyShrinkHalfHeight
float UCharacterMovementComponent::NetProxyShrinkHalfHeight
Shrink simulated proxy capsule half height by this amount, to account for network rounding that may cause encroachment.
Changing during gameplay is not supported.
See also
AdjustProxyCapsuleSize()
Definition at line 824 of file CharacterMovementComponent.h.
NetProxyShrinkRadius
float UCharacterMovementComponent::NetProxyShrinkRadius
Shrink simulated proxy capsule radius by this amount, to account for network rounding that may cause encroachment.
Changing during gameplay is not supported.
See also
AdjustProxyCapsuleSize()
Definition at line 817 of file CharacterMovementComponent.h.
NetworkLargeClientCorrectionDistance
float UCharacterMovementComponent::NetworkLargeClientCorrectionDistance
If client error is larger than this, sets bNetworkLargeClientCorrection to reduce delay between client adjustments.
See also
NetworkMinTimeBetweenClientAdjustments, NetworkMinTimeBetweenClientAdjustmentsLargeCorrection
Definition at line 864 of file CharacterMovementComponent.h.
NetworkMaxSmoothUpdateDistance
float UCharacterMovementComponent::NetworkMaxSmoothUpdateDistance
Maximum distance character is allowed to lag behind server location when interpolating between updates.
Definition at line 828 of file CharacterMovementComponent.h.
NetworkMinTimeBetweenClientAckGoodMoves
float UCharacterMovementComponent::NetworkMinTimeBetweenClientAckGoodMoves
Minimum time on the server between acknowledging good client moves.
This can save on bandwidth. Set to 0 to disable throttling.
Definition at line 840 of file CharacterMovementComponent.h.
NetworkMinTimeBetweenClientAdjustments
float UCharacterMovementComponent::NetworkMinTimeBetweenClientAdjustments
Minimum time on the server between sending client adjustments when client has exceeded allowable position error.
Should be >= NetworkMinTimeBetweenClientAdjustmentsLargeCorrection (the larger value is used regardless). This can save on bandwidth. Set to 0 to disable throttling.
See also
ServerLastClientAdjustmentTime
Definition at line 849 of file CharacterMovementComponent.h.
NetworkMinTimeBetweenClientAdjustmentsLargeCorrection
float UCharacterMovementComponent::NetworkMinTimeBetweenClientAdjustmentsLargeCorrection
Minimum time on the server between sending client adjustments when client has exceeded allowable position error by a large amount (NetworkLargeClientCorrectionDistance).
Should be <= NetworkMinTimeBetweenClientAdjustments (the smaller value is used regardless).
See also
NetworkMinTimeBetweenClientAdjustments
Definition at line 857 of file CharacterMovementComponent.h.
NetworkNoSmoothUpdateDistance
float UCharacterMovementComponent::NetworkNoSmoothUpdateDistance
Maximum distance beyond which character is teleported to the new server location without any smoothing.
Definition at line 834 of file CharacterMovementComponent.h.
NetworkSimulatedSmoothLocationTime
float UCharacterMovementComponent::NetworkSimulatedSmoothLocationTime
How long to take to smoothly interpolate from the old pawn position on the client to the corrected one sent by the server.
Not used by Linear smoothing.
Definition at line 792 of file CharacterMovementComponent.h.
NetworkSimulatedSmoothRotationTime
float UCharacterMovementComponent::NetworkSimulatedSmoothRotationTime
How long to take to smoothly interpolate from the old pawn rotation on the client to the corrected one sent by the server.
Not used by Linear smoothing.
Definition at line 798 of file CharacterMovementComponent.h.
NetworkSmoothingMode
ENetworkSmoothingMode UCharacterMovementComponent::NetworkSmoothingMode
Smoothing mode for simulated proxies in network game.
Definition at line 244 of file CharacterMovementComponent.h.
NumJumpApexAttempts
int32 UCharacterMovementComponent::NumJumpApexAttempts protected
Used to limit number of jump apex attempts per tick.
See also
MaxJumpApexAttemptsPerSimulation
Definition at line 695 of file CharacterMovementComponent.h.
OldBaseLocation
FVector UCharacterMovementComponent::OldBaseLocation
Saved location of object we are standing on, for UpdateBasedMovement() to determine if base moved in the last frame, and therefore pawn needs an update.
Definition at line 260 of file CharacterMovementComponent.h.
OldBaseQuat
FQuat UCharacterMovementComponent::OldBaseQuat
Saved location of object we are standing on, for UpdateBasedMovement() to determine if base moved in the last frame, and therefore pawn needs an update.
Definition at line 257 of file CharacterMovementComponent.h.
OutofWaterZ
float UCharacterMovementComponent::OutofWaterZ
Z velocity applied when pawn tries to get out of water.
Definition at line 576 of file CharacterMovementComponent.h.
PawnOwner
TObjectPtr<class APawn> UPawnMovementComponent::PawnOwner protected inherited
Pawn that owns this component.
Definition at line 112 of file PawnMovementComponent.h.
PendingForceToApply
FVector UCharacterMovementComponent::PendingForceToApply protected
Accumulated force to be added next tick.
Definition at line 674 of file CharacterMovementComponent.h.
PendingImpulseToApply
FVector UCharacterMovementComponent::PendingImpulseToApply protected
Accumulated impulse to be added next tick.
Definition at line 670 of file CharacterMovementComponent.h.
PendingLaunchVelocity
FVector UCharacterMovementComponent::PendingLaunchVelocity
Temporarily holds launch velocity when pawn is to be launched so it happens at end of movement.
Definition at line 1167 of file CharacterMovementComponent.h.
PerchAdditionalHeight
float UCharacterMovementComponent::PerchAdditionalHeight
When perching on a ledge, add this additional distance to MaxStepHeight when determining how high above a walkable floor we can perch.
Note that we still enforce MaxStepHeight to start the step up; this just allows the character to hang off the edge or step slightly higher off the floor. (
See also
PerchRadiusThreshold)
Definition at line 395 of file CharacterMovementComponent.h.
PerchRadiusThreshold
float UCharacterMovementComponent::PerchRadiusThreshold
Don't allow the character to perch on the edge of a surface if the contact is this close to the edge of the capsule.
Note that characters will not fall off if they are within MaxStepHeight of a walkable surface below.
Definition at line 387 of file CharacterMovementComponent.h.
PlaneConstraintNormal
FVector UMovementComponent::PlaneConstraintNormal protected inherited
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
If for example you wanted to constrain movement to the X-Z plane (so that Y cannot change), the normal would be set to X=0 Y=1 Z=0. This is recalculated whenever PlaneConstraintAxisSetting changes. It is normalized once the component is registered with the game world.
See also
bConstrainToPlane, SetPlaneConstraintNormal(), SetPlaneConstraintFromVectors()
Definition at line 107 of file MovementComponent.h.
PlaneConstraintOrigin
FVector UMovementComponent::PlaneConstraintOrigin protected inherited
The origin of the plane that constrains movement, if plane constraint is enabled.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
See also
bConstrainToPlane, SetPlaneConstraintOrigin().
Definition at line 115 of file MovementComponent.h.
PostPhysicsTickFunction
struct FCharacterMovementComponentPostPhysicsTickFunction UCharacterMovementComponent::PostPhysicsTickFunction
Post-physics tick function for this character.
Definition at line 1932 of file CharacterMovementComponent.h.
PrePhysicsTickFunction
struct FCharacterMovementComponentPrePhysicsTickFunction UCharacterMovementComponent::PrePhysicsTickFunction
Pre-physics tick function for this character.
Definition at line 1925 of file CharacterMovementComponent.h.
ProcessRootMotionPostConvertToWorld
FOnProcessRootMotion UCharacterMovementComponent::ProcessRootMotionPostConvertToWorld
Definition at line 2785 of file CharacterMovementComponent.h.
ProcessRootMotionPreConvertToWorld
FOnProcessRootMotion UCharacterMovementComponent::ProcessRootMotionPreConvertToWorld
Definition at line 2782 of file CharacterMovementComponent.h.
PushForceFactor
float UCharacterMovementComponent::PushForceFactor
Force to apply when the player collides with a blocking physics object.
Definition at line 592 of file CharacterMovementComponent.h.
PushForcePointZOffsetFactor
float UCharacterMovementComponent::PushForcePointZOffsetFactor
Z-Offset for the position the force is applied to.
0.0f is the center of the physics object, 1.0f is the top and -1.0f is the bottom of the object.
Definition at line 596 of file CharacterMovementComponent.h.
RandomStream
FRandomStream UCharacterMovementComponent::RandomStream protected
Definition at line 2306 of file CharacterMovementComponent.h.
RepulsionForce
float UCharacterMovementComponent::RepulsionForce
Force per kg applied constantly to all overlapping components.
Definition at line 612 of file CharacterMovementComponent.h.
RequestedVelocity
FVector UCharacterMovementComponent::RequestedVelocity
Velocity requested by path following.
See also
RequestDirectMove()
Definition at line 1114 of file CharacterMovementComponent.h.
RootMotionIDMappings
TArray<FRootMotionServerToLocalIDMapping, TInlineAllocator<(uint32)ERootMotionMapping::MapSize> > UCharacterMovementComponent::RootMotionIDMappings
Definition at line 2744 of file CharacterMovementComponent.h.
RootMotionParams
FRootMotionMovementParams UCharacterMovementComponent::RootMotionParams
Animation root motion (special case for now)
Root Motion movement params. Holds result of anim montage root motion during PerformMovement(), and is overridden during autonomous move playback to force historical root motion for MoveAutonomous() calls
Definition at line 2765 of file CharacterMovementComponent.h.
RotationRate
FRotator UCharacterMovementComponent::RotationRate
Change in rotation per second, used when UseControllerDesiredRotation or OrientRotationToMovement are true.
Set a negative value for infinite rotation rate and instant turns.
Definition at line 399 of file CharacterMovementComponent.h.
ServerCorrectionRootMotion
FRootMotionSourceGroup UCharacterMovementComponent::ServerCorrectionRootMotion
Definition at line 2713 of file CharacterMovementComponent.h.
ServerLastClientAdjustmentTime
float UCharacterMovementComponent::ServerLastClientAdjustmentTime protected
Timestamp of last client adjustment sent.
See NetworkMinTimeBetweenClientAdjustments.
Definition at line 666 of file CharacterMovementComponent.h.
ServerLastClientGoodMoveAckTime
float UCharacterMovementComponent::ServerLastClientGoodMoveAckTime protected
Timestamp of last client adjustment sent.
See NetworkMinTimeBetweenClientAdjustments.
Definition at line 662 of file CharacterMovementComponent.h.
ServerLastTransformUpdateTimeStamp
float UCharacterMovementComponent::ServerLastTransformUpdateTimeStamp protected
Timestamp when location or rotation last changed during an update.
Only valid on the server.
Definition at line 658 of file CharacterMovementComponent.h.
ServerPredictionData
class FNetworkPredictionData_Server_Character* UCharacterMovementComponent::ServerPredictionData protected
Definition at line 2304 of file CharacterMovementComponent.h.
StandingDownwardForceScale
float UCharacterMovementComponent::StandingDownwardForceScale
Force applied to objects we stand on (due to Mass and Gravity) is scaled by this amount.
Definition at line 584 of file CharacterMovementComponent.h.
StayBasedInAirHeight
float UCharacterMovementComponent::StayBasedInAirHeight = 1000.0f
Property used to set how high above base characters should stay based on objects while jumping if bStayBasedInAir is set.
Definition at line 1404 of file CharacterMovementComponent.h.
StuckWarningCountSinceNotify
uint32 UCharacterMovementComponent::StuckWarningCountSinceNotify protected
Used when throttling "stuck in geometry" logging, to output the number of events we skipped if throttling.
Definition at line 689 of file CharacterMovementComponent.h.
SWEEP_EDGE_REJECT_DISTANCE
const float UCharacterMovementComponent::SWEEP_EDGE_REJECT_DISTANCE static
Reject sweep impacts that are this close to the edge of the vertical portion of the capsule when performing vertical sweeps, and try again with a smaller capsule.
Definition at line 2863 of file CharacterMovementComponent.h.
TouchForceFactor
float UCharacterMovementComponent::TouchForceFactor
Force to apply to physics objects that are touched by the player.
Definition at line 600 of file CharacterMovementComponent.h.
UpperImpactNormalScale_DEPRECATED
float UCharacterMovementComponent::UpperImpactNormalScale_DEPRECATED
Definition at line 626 of file CharacterMovementComponent.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h