Unreal Engine 5.6 C++ Documentation: UCheatManagerExtension Class Reference
UCheatManagerExtension Class Reference
A cheat manager extension can extend the main cheat manager in a modular way, being enabled or disabled when the system associated with the cheats is enabled or disabled.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CheatManager.h>
Public Member Functions
virtual UWorld * GetWorld () const override
Use the outer cheat manager to get a World.
APlayerController * GetPlayerController () const
void AddedToCheatManager ()
virtual void AddedToCheatManager_Implementation ()
void RemovedFromCheatManager ()
virtual void RemovedFromCheatManager_Implementation ()
virtual void DoExtensionSpecificBugItLog (FOutputDevice &OutputFile)
Detailed Description
A cheat manager extension can extend the main cheat manager in a modular way, being enabled or disabled when the system associated with the cheats is enabled or disabled.
Definition at line 70 of file CheatManager.h.
Member Function Documentation
AddedToCheatManager()
void UCheatManagerExtension::AddedToCheatManager ()
References AddedToCheatManager().
AddedToCheatManager_Implementation()
virtual void UCheatManagerExtension::AddedToCheatManager_Implementation () virtual
References AddedToCheatManager_Implementation().
DoExtensionSpecificBugItLog()
virtual void UCheatManagerExtension::DoExtensionSpecificBugItLog (FOutputDevice & OutputFile) virtual
References DoExtensionSpecificBugItLog().
GetPlayerController()
APlayerController * UCheatManagerExtension::GetPlayerController () const
References GetPlayerController().
GetWorld()
virtual UWorld * UCheatManagerExtension::GetWorld () const override virtual
Use the outer cheat manager to get a World.
RemovedFromCheatManager()
void UCheatManagerExtension::RemovedFromCheatManager ()
References RemovedFromCheatManager().
RemovedFromCheatManager_Implementation()
virtual void UCheatManagerExtension::RemovedFromCheatManager_Implementation () virtual
References RemovedFromCheatManager_Implementation().
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/CheatManager.h