Unreal Engine 5.6 C++ Documentation: UGameUserSettings Class Reference
UGameUserSettings Class Reference
Stores user settings for a game (for example graphics and sound settings), with the ability to save and load to and from a file.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/GameUserSettings.h>
Public Member Functions
virtual void ApplySettings (bool bCheckForCommandLineOverrides)
Applies all current user settings to the game and saves to permanent storage (e.g.
virtual void ApplyNonResolutionSettings ()
void ApplyResolutionSettings (bool bCheckForCommandLineOverrides)
FIntPoint GetScreenResolution () const
Returns the user setting for game screen resolution, in pixels.
FIntPoint GetLastConfirmedScreenResolution () const
Returns the last confirmed user setting for game screen resolution, in pixels.
FIntPoint GetDesktopResolution () const
Returns user's desktop resolution, in pixels.
void SetScreenResolution (FIntPoint Resolution)
Sets the user setting for game screen resolution, in pixels.
EWindowMode::Type GetFullscreenMode () const
Returns the user setting for game window fullscreen mode.
EWindowMode::Type GetLastConfirmedFullscreenMode () const
Returns the last confirmed user setting for game window fullscreen mode.
void SetFullscreenMode (EWindowMode::Type InFullscreenMode)
Sets the user setting for the game window fullscreen mode.
EWindowMode::Type GetPreferredFullscreenMode () const
Returns the user setting for game window fullscreen mode.
void SetVSyncEnabled (bool bEnable)
Sets the user setting for vsync.
bool IsVSyncEnabled () const
Returns the user setting for vsync.
void SetDynamicResolutionEnabled (bool bEnable)
Sets the user setting for dynamic resolution.
virtual bool IsDynamicResolutionEnabled () const
Returns the user setting for dynamic resolution.
bool IsScreenResolutionDirty () const
Checks if the Screen Resolution user setting is different from current.
bool IsFullscreenModeDirty () const
Checks if the FullscreenMode user setting is different from current.
bool IsVSyncDirty () const
Checks if the vsync user setting is different from current system setting.
bool IsDynamicResolutionDirty () const
Checks if the dynamic resolution user setting is different from current system setting.
virtual void ConfirmVideoMode ()
Mark current video mode settings (fullscreenmode/resolution) as being confirmed by the user.
void RevertVideoMode ()
Revert video mode (fullscreenmode/resolution) back to the last user confirmed values.
void SetBenchmarkFallbackValues ()
Set scalability settings to sensible fallback values, for use when the benchmark fails or potentially causes a crash.
void SetAudioQualityLevel (int32 QualityLevel)
Sets the user's audio quality level setting.
int32 GetAudioQualityLevel () const
Returns the user's audio quality level setting.
void SetFrameRateLimit (float NewLimit)
Sets the user's frame rate limit (0 will disable frame rate limiting)
float GetFrameRateLimit () const
Gets the user's frame rate limit (0 indiciates the frame rate limit is disabled)
virtual void SetOverallScalabilityLevel (int32 Value)
virtual int32 GetOverallScalabilityLevel () const
void GetResolutionScaleInformationEx (float &CurrentScaleNormalized, float &CurrentScaleValue, float &MinScaleValue, float &MaxScaleValue) const
float GetResolutionScaleNormalized () const
void SetResolutionScaleValueEx (float NewScaleValue)
void SetResolutionScaleNormalized (float NewScaleNormalized)
void SetViewDistanceQuality (int32 Value)
int32 GetViewDistanceQuality () const
void SetShadowQuality (int32 Value)
int32 GetShadowQuality () const
void SetGlobalIlluminationQuality (int32 Value)
int32 GetGlobalIlluminationQuality () const
void SetReflectionQuality (int32 Value)
int32 GetReflectionQuality () const
void SetAntiAliasingQuality (int32 Value)
int32 GetAntiAliasingQuality () const
void SetTextureQuality (int32 Value)
int32 GetTextureQuality () const
void SetVisualEffectQuality (int32 Value)
int32 GetVisualEffectQuality () const
void SetPostProcessingQuality (int32 Value)
int32 GetPostProcessingQuality () const
void SetFoliageQuality (int32 Value)
int32 GetFoliageQuality () const
void SetShadingQuality (int32 Value)
int32 GetShadingQuality () const
virtual bool IsDirty () const
Checks if any user settings is different from current.
virtual void ValidateSettings ()
Validates and resets bad user settings to default.
virtual void LoadSettings (bool bForceReload=false)
Loads the user settings from persistent storage.
virtual void SaveSettings ()
Save the user settings to persistent storage (automatically happens as part of ApplySettings)
virtual void ResetToCurrentSettings ()
This function resets all settings to the current system settings.
virtual void SetWindowPosition (int32 WindowPosX, int32 WindowPosY)
Sets the window position in save slot index 0.
virtual void SetWindowPosition (int32 WindowPosX, int32 WindowPosY, int32 SaveSlotIndex)
Sets the window position in the given index, which must be less than GetMaxNumWindowPositionSaveSlots().
virtual FIntPoint GetWindowPosition ()
Returns the window position in save slot index 0.
virtual FIntPoint GetWindowPosition (int32 SaveSlotIndex)
Returns the window position in the given index, or the default if the index is invalid.
void ReloadWindowPositions ()
Reloads the WindowPositions array from config files.
virtual void SetToDefaults ()
virtual float GetDefaultResolutionScale ()
Gets the desired resolution quality based on DesiredScreenWidth/Height and the current screen resolution.
virtual float GetRecommendedResolutionScale ()
Gets the recommended resolution quality based on LastRecommendedScreenWidth/Height and the current screen resolution.
virtual void RunHardwareBenchmark (int32 WorkScale=10, float CPUMultiplier=1.0f, float GPUMultiplier=1.0f)
Runs the hardware benchmark and populates ScalabilityQuality as well as the last benchmark results config members, but does not apply the settings it determines.
virtual void ApplyHardwareBenchmarkResults ()
Applies the settings stored in ScalabilityQuality and saves settings.
virtual bool SupportsHDRDisplayOutput () const
Whether the curently running system supports HDR display output.
void EnableHDRDisplayOutput (bool bEnable, int32 DisplayNits=1000)
Enables or disables HDR display output.
int32 GetCurrentHDRDisplayNits () const
Returns 0 if HDR isn't supported or is turned off.
bool IsHDREnabled () const
float GetLastCPUBenchmarkResult () const
Returns the last CPU benchmark result (set by RunHardwareBenchmark)
float GetLastGPUBenchmarkResult () const
Returns the last GPU benchmark result (set by RunHardwareBenchmark)
TArray< float > GetLastCPUBenchmarkSteps () const
Returns each individual step of the last CPU benchmark result (set by RunHardwareBenchmark)
TArray< float > GetLastGPUBenchmarkSteps () const
Returns each individual step of the last GPU benchmark result (set by RunHardwareBenchmark)
void RequestUIUpdate ()
int32 GetMaxNumWindowPositionSaveSlots () const
Returns the maximum supported number save slots for window positions.
DECLARE_DELEGATE_RetVal_OneParam (bool, FUpdateGameUserSettingsFileFromCloud, const FString &)
We call this to refresh the config file from a listening Cloud subsystem, before we open it.
DECLARE_DELEGATE_RetVal_OneParam (bool, FUpdateCloudDataFromGameUserSettings, const FString &)
We call this to notify any listening Cloud subsystem that we have updated the config file.
Static Public Member Functions
static FString GetConfigDir ()
static void PreloadResolutionSettings (bool bAllowCmdLineOverrides=true)
Loads the resolution settings before is object is available.
static FIntPoint GetDefaultResolution ()
Returns the default resolution when no resolution is set.
static FIntPoint GetDefaultWindowPosition ()
Returns the default window position when no position is set.
static EWindowMode::Type GetDefaultWindowMode ()
Returns the default window mode when no mode is set.
static int32 GetSyncInterval ()
Gets the current vsync interval setting.
static int32 GetFramePace ()
Gets the current frame pacing frame rate in fps, or 0 if none.
static void LoadConfigIni (bool bForceReload=false)
Loads the user .ini settings into GConfig.
static void RequestResolutionChange (int32 InResolutionX, int32 InResolutionY, EWindowMode::Type InWindowMode, bool bInDoOverrides=true)
Request a change to the specified resolution and window mode.
static UGameUserSettings * GetGameUserSettings ()
Returns the game local machine settings (resolution, windowing mode, scalability settings, etc...)
Public Attributes
bool bUseVSync
Whether to use VSync or not.
bool bUseDynamicResolution
Whether to use dynamic resolution or not.
Scalability::FQualityLevels ScalabilityQuality
FUpdateGameUserSettingsFileFromCloud OnUpdateGameUserSettingsFileFromCloud
FUpdateCloudDataFromGameUserSettings OnUpdateCloudDataFromGameUserSettings
Protected Member Functions
virtual bool IsVersionValid ()
Check if the current version of the game user settings is valid.
virtual void UpdateVersion ()
Update the version of the game user settings to the current version.
float FindResolutionQualityForScreenSize (float Width, float Height)
Picks the best resolution quality for a given screen size.
virtual float GetEffectiveFrameRateLimit ()
Returns the effective frame rate limit (by default it returns the FrameRateLimit member)
void UpdateResolutionQuality ()
void EnableHDRDisplayOutputInternal (bool bEnable, int32 DisplayNits, bool bFromUserSettings)
Static Protected Member Functions
static void SetFrameRateLimitCVar (float InLimit)
Sets the frame rate limit CVar to the passed in value, 0.0 indicates no limit.
static void SetSyncTypeCVar (int32 InInterval)
Sets the input latency mode 0 and 2.
Protected Attributes
uint32 ResolutionSizeX
Game screen resolution width, in pixels.
uint32 ResolutionSizeY
Game screen resolution height, in pixels.
uint32 LastUserConfirmedResolutionSizeX
Game screen resolution width, in pixels.
uint32 LastUserConfirmedResolutionSizeY
Game screen resolution height, in pixels.
int32 WindowPosX_DEPRECATED
Window PosX.
int32 WindowPosY_DEPRECATED
Window PosY.
TArray< FIntPoint > WindowPositions
Saved window positions.
int32 FullscreenMode
Game window fullscreen mode 0 = Fullscreen 1 = Windowed fullscreen 2 = Windowed.
int32 LastConfirmedFullscreenMode
Last user confirmed fullscreen mode setting.
int32 PreferredFullscreenMode
Fullscreen mode to use when toggling between windowed and fullscreen.
uint32 Version
All settings will be wiped and set to default if the serialized version differs from UE_GAMEUSERSETTINGS_VERSION.
int32 AudioQualityLevel
int32 LastConfirmedAudioQualityLevel
float FrameRateLimit
Frame rate cap.
float MinResolutionScale
Min resolution scale we allow in current display mode.
int32 DesiredScreenWidth
Desired screen width used to calculate the resolution scale when user changes display mode.
bool bUseDesiredScreenHeight
If true, the desired screen height will be used to scale the render resolution automatically.
int32 DesiredScreenHeight
Desired screen height used to calculate the resolution scale when user changes display mode.
int32 LastUserConfirmedDesiredScreenWidth
Desired screen width used to calculate the resolution scale when user changes display mode.
int32 LastUserConfirmedDesiredScreenHeight
Desired screen height used to calculate the resolution scale when user changes display mode.
float LastRecommendedScreenWidth
Result of the last benchmark; calculated resolution to use.
float LastRecommendedScreenHeight
Result of the last benchmark; calculated resolution to use.
float LastCPUBenchmarkResult
Result of the last benchmark (CPU); -1 if there has not been a benchmark run.
float LastGPUBenchmarkResult
Result of the last benchmark (GPU); -1 if there has not been a benchmark run.
TArray< float > LastCPUBenchmarkSteps
Result of each individual sub-section of the last CPU benchmark; empty if there has not been a benchmark run.
TArray< float > LastGPUBenchmarkSteps
Result of each individual sub-section of the last GPU benchmark; empty if there has not been a benchmark run.
float LastGPUBenchmarkMultiplier
Multiplier used against the last GPU benchmark.
bool bUseHDRDisplayOutput
HDR.
int32 HDRDisplayOutputNits
HDR.
bool bEnableScalabilitySettings = true
When set to false, scalability settings (ScalabilityQuality) are not considered user settings i.e.
Detailed Description
Stores user settings for a game (for example graphics and sound settings), with the ability to save and load to and from a file.
Definition at line 37 of file GameUserSettings.h.
Member Function Documentation
ApplyHardwareBenchmarkResults()
virtual void UGameUserSettings::ApplyHardwareBenchmarkResults () virtual
Applies the settings stored in ScalabilityQuality and saves settings.
References ApplyHardwareBenchmarkResults().
ApplyNonResolutionSettings()
virtual void UGameUserSettings::ApplyNonResolutionSettings () virtual
References ApplyNonResolutionSettings().
ApplyResolutionSettings()
void UGameUserSettings::ApplyResolutionSettings (bool bCheckForCommandLineOverrides)
References ApplyResolutionSettings().
ApplySettings()
virtual void UGameUserSettings::ApplySettings (bool bCheckForCommandLineOverrides) virtual
Applies all current user settings to the game and saves to permanent storage (e.g.
file), optionally checking for command line overrides.
References ApplySettings().
ConfirmVideoMode()
virtual void UGameUserSettings::ConfirmVideoMode () virtual
Mark current video mode settings (fullscreenmode/resolution) as being confirmed by the user.
References ConfirmVideoMode().
DECLARE_DELEGATE_RetVal_OneParam() [1/2]
UGameUserSettings::DECLARE_DELEGATE_RetVal_OneParam (bool , FUpdateCloudDataFromGameUserSettings , const FString &)
We call this to notify any listening Cloud subsystem that we have updated the config file.
DECLARE_DELEGATE_RetVal_OneParam() [2/2]
UGameUserSettings::DECLARE_DELEGATE_RetVal_OneParam (bool , FUpdateGameUserSettingsFileFromCloud , const FString &)
We call this to refresh the config file from a listening Cloud subsystem, before we open it.
EnableHDRDisplayOutput()
void UGameUserSettings::EnableHDRDisplayOutput (bool bEnable, int32 DisplayNits = 1000)
Enables or disables HDR display output.
Can be called again to change the desired nit level
References EnableHDRDisplayOutput().
EnableHDRDisplayOutputInternal()
void UGameUserSettings::EnableHDRDisplayOutputInternal (bool bEnable, int32 DisplayNits, bool bFromUserSettings) protected
FindResolutionQualityForScreenSize()
float UGameUserSettings::FindResolutionQualityForScreenSize (float Width, float Height) protected
Picks the best resolution quality for a given screen size.
GetAntiAliasingQuality()
int32 UGameUserSettings::GetAntiAliasingQuality () const
References GetAntiAliasingQuality().
GetAudioQualityLevel()
int32 UGameUserSettings::GetAudioQualityLevel () const inline
Returns the user's audio quality level setting.
Definition at line 139 of file GameUserSettings.h.
References AudioQualityLevel, and GetAudioQualityLevel().
GetConfigDir()
FString UGameUserSettings::GetConfigDir () static
Returns
the location where GGameUserSettingsIni will be found
GetCurrentHDRDisplayNits()
int32 UGameUserSettings::GetCurrentHDRDisplayNits () const
Returns 0 if HDR isn't supported or is turned off.
References GetCurrentHDRDisplayNits().
GetDefaultResolution()
FIntPoint UGameUserSettings::GetDefaultResolution () static
Returns the default resolution when no resolution is set.
References GetDefaultResolution().
GetDefaultResolutionScale()
virtual float UGameUserSettings::GetDefaultResolutionScale () virtual
Gets the desired resolution quality based on DesiredScreenWidth/Height and the current screen resolution.
References GetDefaultResolutionScale().
GetDefaultWindowMode()
EWindowMode::Type UGameUserSettings::GetDefaultWindowMode () static
Returns the default window mode when no mode is set.
References EWindowMode, and GetDefaultWindowMode().
GetDefaultWindowPosition()
FIntPoint UGameUserSettings::GetDefaultWindowPosition () static
Returns the default window position when no position is set.
References GetDefaultWindowPosition().
GetDesktopResolution()
FIntPoint UGameUserSettings::GetDesktopResolution () const
Returns user's desktop resolution, in pixels.
References GetDesktopResolution().
GetEffectiveFrameRateLimit()
virtual float UGameUserSettings::GetEffectiveFrameRateLimit () protected virtual
Returns the effective frame rate limit (by default it returns the FrameRateLimit member)
GetFoliageQuality()
int32 UGameUserSettings::GetFoliageQuality () const
References GetFoliageQuality().
GetFramePace()
int32 UGameUserSettings::GetFramePace () static
Gets the current frame pacing frame rate in fps, or 0 if none.
References GetFramePace().
GetFrameRateLimit()
float UGameUserSettings::GetFrameRateLimit () const
Gets the user's frame rate limit (0 indiciates the frame rate limit is disabled)
References GetFrameRateLimit().
GetFullscreenMode()
EWindowMode::Type UGameUserSettings::GetFullscreenMode () const
Returns the user setting for game window fullscreen mode.
References EWindowMode, and GetFullscreenMode().
GetGameUserSettings()
UGameUserSettings * UGameUserSettings::GetGameUserSettings () static
Returns the game local machine settings (resolution, windowing mode, scalability settings, etc...)
References GetGameUserSettings().
GetGlobalIlluminationQuality()
int32 UGameUserSettings::GetGlobalIlluminationQuality () const
References GetGlobalIlluminationQuality().
GetLastConfirmedFullscreenMode()
EWindowMode::Type UGameUserSettings::GetLastConfirmedFullscreenMode () const
Returns the last confirmed user setting for game window fullscreen mode.
References EWindowMode, and GetLastConfirmedFullscreenMode().
GetLastConfirmedScreenResolution()
FIntPoint UGameUserSettings::GetLastConfirmedScreenResolution () const
Returns the last confirmed user setting for game screen resolution, in pixels.
References GetLastConfirmedScreenResolution().
GetLastCPUBenchmarkResult()
float UGameUserSettings::GetLastCPUBenchmarkResult () const inline
Returns the last CPU benchmark result (set by RunHardwareBenchmark)
Definition at line 509 of file GameUserSettings.h.
References GetLastCPUBenchmarkResult(), and LastCPUBenchmarkResult.
GetLastCPUBenchmarkSteps()
TArray< float > UGameUserSettings::GetLastCPUBenchmarkSteps () const inline
Returns each individual step of the last CPU benchmark result (set by RunHardwareBenchmark)
Definition at line 521 of file GameUserSettings.h.
References LastCPUBenchmarkSteps.
GetLastGPUBenchmarkResult()
float UGameUserSettings::GetLastGPUBenchmarkResult () const inline
Returns the last GPU benchmark result (set by RunHardwareBenchmark)
Definition at line 515 of file GameUserSettings.h.
References LastGPUBenchmarkResult.
GetLastGPUBenchmarkSteps()
TArray< float > UGameUserSettings::GetLastGPUBenchmarkSteps () const inline
Returns each individual step of the last GPU benchmark result (set by RunHardwareBenchmark)
Definition at line 527 of file GameUserSettings.h.
References LastGPUBenchmarkSteps.
GetMaxNumWindowPositionSaveSlots()
int32 UGameUserSettings::GetMaxNumWindowPositionSaveSlots () const
Returns the maximum supported number save slots for window positions.
GetOverallScalabilityLevel()
virtual int32 UGameUserSettings::GetOverallScalabilityLevel () const virtual
References GetOverallScalabilityLevel().
GetPostProcessingQuality()
int32 UGameUserSettings::GetPostProcessingQuality () const
References GetPostProcessingQuality().
GetPreferredFullscreenMode()
EWindowMode::Type UGameUserSettings::GetPreferredFullscreenMode () const
Returns the user setting for game window fullscreen mode.
References EWindowMode, and GetPreferredFullscreenMode().
GetRecommendedResolutionScale()
virtual float UGameUserSettings::GetRecommendedResolutionScale () virtual
Gets the recommended resolution quality based on LastRecommendedScreenWidth/Height and the current screen resolution.
References GetRecommendedResolutionScale().
GetReflectionQuality()
int32 UGameUserSettings::GetReflectionQuality () const
References GetReflectionQuality().
GetResolutionScaleInformationEx()
void UGameUserSettings::GetResolutionScaleInformationEx (float & CurrentScaleNormalized, float & CurrentScaleValue, float & MinScaleValue, float & MaxScaleValue) const
References GetResolutionScaleInformationEx().
GetResolutionScaleNormalized()
float UGameUserSettings::GetResolutionScaleNormalized () const
References GetResolutionScaleNormalized().
GetScreenResolution()
FIntPoint UGameUserSettings::GetScreenResolution () const
Returns the user setting for game screen resolution, in pixels.
References GetScreenResolution().
GetShadingQuality()
int32 UGameUserSettings::GetShadingQuality () const
References GetShadingQuality().
GetShadowQuality()
int32 UGameUserSettings::GetShadowQuality () const
References GetShadowQuality().
GetSyncInterval()
int32 UGameUserSettings::GetSyncInterval () static
Gets the current vsync interval setting.
References GetSyncInterval().
GetTextureQuality()
int32 UGameUserSettings::GetTextureQuality () const
References GetTextureQuality().
GetViewDistanceQuality()
int32 UGameUserSettings::GetViewDistanceQuality () const
References GetViewDistanceQuality().
GetVisualEffectQuality()
int32 UGameUserSettings::GetVisualEffectQuality () const
References GetVisualEffectQuality().
GetWindowPosition() [1/2]
virtual FIntPoint UGameUserSettings::GetWindowPosition () virtual
Returns the window position in save slot index 0.
References GetWindowPosition().
GetWindowPosition() [2/2]
virtual FIntPoint UGameUserSettings::GetWindowPosition (int32 SaveSlotIndex) virtual
Returns the window position in the given index, or the default if the index is invalid.
References GetWindowPosition().
IsDirty()
virtual bool UGameUserSettings::IsDirty () const virtual
Checks if any user settings is different from current.
References IsDirty().
IsDynamicResolutionDirty()
bool UGameUserSettings::IsDynamicResolutionDirty () const
Checks if the dynamic resolution user setting is different from current system setting.
References IsDynamicResolutionDirty().
IsDynamicResolutionEnabled()
virtual bool UGameUserSettings::IsDynamicResolutionEnabled () const virtual
Returns the user setting for dynamic resolution.
References IsDynamicResolutionEnabled().
IsFullscreenModeDirty()
bool UGameUserSettings::IsFullscreenModeDirty () const
Checks if the FullscreenMode user setting is different from current.
References IsFullscreenModeDirty().
IsHDREnabled()
bool UGameUserSettings::IsHDREnabled () const
References IsHDREnabled().
IsScreenResolutionDirty()
bool UGameUserSettings::IsScreenResolutionDirty () const
Checks if the Screen Resolution user setting is different from current.
References IsScreenResolutionDirty().
IsVersionValid()
virtual bool UGameUserSettings::IsVersionValid () protected virtual
Check if the current version of the game user settings is valid.
Sub-classes can override this to provide game-specific versioning as necessary.
Returns
True if the current version is valid, false if it is not
IsVSyncDirty()
bool UGameUserSettings::IsVSyncDirty () const
Checks if the vsync user setting is different from current system setting.
References IsVSyncDirty().
IsVSyncEnabled()
bool UGameUserSettings::IsVSyncEnabled () const
Returns the user setting for vsync.
References IsVSyncEnabled().
LoadConfigIni()
void UGameUserSettings::LoadConfigIni (bool bForceReload = false) static
Loads the user .ini settings into GConfig.
References LoadConfigIni().
LoadSettings()
virtual void UGameUserSettings::LoadSettings (bool bForceReload = false) virtual
Loads the user settings from persistent storage.
References LoadSettings().
PreloadResolutionSettings()
void UGameUserSettings::PreloadResolutionSettings (bool bAllowCmdLineOverrides = true) static
Loads the resolution settings before is object is available.
References PreloadResolutionSettings().
ReloadWindowPositions()
void UGameUserSettings::ReloadWindowPositions ()
Reloads the WindowPositions array from config files.
Use before SaveConfig to avoid clobbering other processes' window positions.
References ReloadWindowPositions().
RequestResolutionChange()
void UGameUserSettings::RequestResolutionChange (int32 InResolutionX, int32 InResolutionY, EWindowMode::Type InWindowMode, bool bInDoOverrides = true) static
Request a change to the specified resolution and window mode.
Optionally apply cmd line overrides.
References EWindowMode, and RequestResolutionChange().
RequestUIUpdate()
void UGameUserSettings::RequestUIUpdate () inline
Definition at line 532 of file GameUserSettings.h.
ResetToCurrentSettings()
virtual void UGameUserSettings::ResetToCurrentSettings () virtual
This function resets all settings to the current system settings.
References ResetToCurrentSettings().
RevertVideoMode()
void UGameUserSettings::RevertVideoMode ()
Revert video mode (fullscreenmode/resolution) back to the last user confirmed values.
References RevertVideoMode().
RunHardwareBenchmark()
virtual void UGameUserSettings::RunHardwareBenchmark (int32 WorkScale = 10, float CPUMultiplier = 1.0f, float GPUMultiplier = 1.0f) virtual
Runs the hardware benchmark and populates ScalabilityQuality as well as the last benchmark results config members, but does not apply the settings it determines.
Designed to be called in conjunction with ApplyHardwareBenchmarkResults
References RunHardwareBenchmark().
SaveSettings()
virtual void UGameUserSettings::SaveSettings () virtual
Save the user settings to persistent storage (automatically happens as part of ApplySettings)
References SaveSettings().
SetAntiAliasingQuality()
void UGameUserSettings::SetAntiAliasingQuality (int32 Value)
References SetAntiAliasingQuality().
SetAudioQualityLevel()
void UGameUserSettings::SetAudioQualityLevel (int32 QualityLevel)
Sets the user's audio quality level setting.
References SetAudioQualityLevel().
SetBenchmarkFallbackValues()
void UGameUserSettings::SetBenchmarkFallbackValues ()
Set scalability settings to sensible fallback values, for use when the benchmark fails or potentially causes a crash.
References SetBenchmarkFallbackValues().
SetDynamicResolutionEnabled()
void UGameUserSettings::SetDynamicResolutionEnabled (bool bEnable)
Sets the user setting for dynamic resolution.
See UGameUserSettings::bUseDynamicResolution.
References SetDynamicResolutionEnabled().
SetFoliageQuality()
void UGameUserSettings::SetFoliageQuality (int32 Value)
References SetFoliageQuality().
SetFrameRateLimit()
void UGameUserSettings::SetFrameRateLimit (float NewLimit)
Sets the user's frame rate limit (0 will disable frame rate limiting)
References SetFrameRateLimit().
SetFrameRateLimitCVar()
void UGameUserSettings::SetFrameRateLimitCVar (float InLimit) static protected
Sets the frame rate limit CVar to the passed in value, 0.0 indicates no limit.
SetFullscreenMode()
void UGameUserSettings::SetFullscreenMode (EWindowMode::Type InFullscreenMode)
Sets the user setting for the game window fullscreen mode.
See UGameUserSettings::FullscreenMode.
References EWindowMode, and SetFullscreenMode().
SetGlobalIlluminationQuality()
void UGameUserSettings::SetGlobalIlluminationQuality (int32 Value)
References SetGlobalIlluminationQuality().
SetOverallScalabilityLevel()
virtual void UGameUserSettings::SetOverallScalabilityLevel (int32 Value) virtual
References SetOverallScalabilityLevel().
SetPostProcessingQuality()
void UGameUserSettings::SetPostProcessingQuality (int32 Value)
References SetPostProcessingQuality().
SetReflectionQuality()
void UGameUserSettings::SetReflectionQuality (int32 Value)
References SetReflectionQuality().
SetResolutionScaleNormalized()
void UGameUserSettings::SetResolutionScaleNormalized (float NewScaleNormalized)
References SetResolutionScaleNormalized().
SetResolutionScaleValueEx()
void UGameUserSettings::SetResolutionScaleValueEx (float NewScaleValue)
References SetResolutionScaleValueEx().
SetScreenResolution()
void UGameUserSettings::SetScreenResolution (FIntPoint Resolution)
Sets the user setting for game screen resolution, in pixels.
References SetScreenResolution().
SetShadingQuality()
void UGameUserSettings::SetShadingQuality (int32 Value)
References SetShadingQuality().
SetShadowQuality()
void UGameUserSettings::SetShadowQuality (int32 Value)
References SetShadowQuality().
SetSyncTypeCVar()
void UGameUserSettings::SetSyncTypeCVar (int32 InInterval) static protected
Sets the input latency mode 0 and 2.
SetTextureQuality()
void UGameUserSettings::SetTextureQuality (int32 Value)
References SetTextureQuality().
SetToDefaults()
virtual void UGameUserSettings::SetToDefaults () virtual
References SetToDefaults().
SetViewDistanceQuality()
void UGameUserSettings::SetViewDistanceQuality (int32 Value)
References SetViewDistanceQuality().
SetVisualEffectQuality()
void UGameUserSettings::SetVisualEffectQuality (int32 Value)
References SetVisualEffectQuality().
SetVSyncEnabled()
void UGameUserSettings::SetVSyncEnabled (bool bEnable)
Sets the user setting for vsync.
See UGameUserSettings::bUseVSync.
References SetVSyncEnabled().
SetWindowPosition() [1/2]
virtual void UGameUserSettings::SetWindowPosition (int32 WindowPosX, int32 WindowPosY) virtual
Sets the window position in save slot index 0.
References SetWindowPosition().
SetWindowPosition() [2/2]
virtual void UGameUserSettings::SetWindowPosition (int32 WindowPosX, int32 WindowPosY, int32 SaveSlotIndex) virtual
Sets the window position in the given index, which must be less than GetMaxNumWindowPositionSaveSlots().
References SetWindowPosition().
SupportsHDRDisplayOutput()
virtual bool UGameUserSettings::SupportsHDRDisplayOutput () const virtual
Whether the curently running system supports HDR display output.
References SupportsHDRDisplayOutput().
UpdateResolutionQuality()
void UGameUserSettings::UpdateResolutionQuality () protected
UpdateVersion()
virtual void UGameUserSettings::UpdateVersion () protected virtual
Update the version of the game user settings to the current version.
ValidateSettings()
virtual void UGameUserSettings::ValidateSettings () virtual
Validates and resets bad user settings to default.
Deletes stale user settings file if necessary.
References ValidateSettings().
Member Data Documentation
AudioQualityLevel
int32 UGameUserSettings::AudioQualityLevel protected
Definition at line 431 of file GameUserSettings.h.
bEnableScalabilitySettings
bool UGameUserSettings::bEnableScalabilitySettings = true protected
When set to false, scalability settings (ScalabilityQuality) are not considered user settings i.e.
they are not saved and applied.
Definition at line 505 of file GameUserSettings.h.
bUseDesiredScreenHeight
bool UGameUserSettings::bUseDesiredScreenHeight protected
If true, the desired screen height will be used to scale the render resolution automatically.
Definition at line 450 of file GameUserSettings.h.
bUseDynamicResolution
bool UGameUserSettings::bUseDynamicResolution
Whether to use dynamic resolution or not.
(public to allow UI to connect to it)
Definition at line 373 of file GameUserSettings.h.
bUseHDRDisplayOutput
bool UGameUserSettings::bUseHDRDisplayOutput protected
HDR.
Definition at line 496 of file GameUserSettings.h.
bUseVSync
bool UGameUserSettings::bUseVSync
Whether to use VSync or not.
(public to allow UI to connect to it)
Definition at line 369 of file GameUserSettings.h.
DesiredScreenHeight
int32 UGameUserSettings::DesiredScreenHeight protected
Desired screen height used to calculate the resolution scale when user changes display mode.
Definition at line 454 of file GameUserSettings.h.
DesiredScreenWidth
int32 UGameUserSettings::DesiredScreenWidth protected
Desired screen width used to calculate the resolution scale when user changes display mode.
Definition at line 446 of file GameUserSettings.h.
FrameRateLimit
float UGameUserSettings::FrameRateLimit protected
Frame rate cap.
Definition at line 438 of file GameUserSettings.h.
FullscreenMode
int32 UGameUserSettings::FullscreenMode protected
Game window fullscreen mode 0 = Fullscreen 1 = Windowed fullscreen 2 = Windowed.
Definition at line 416 of file GameUserSettings.h.
HDRDisplayOutputNits
int32 UGameUserSettings::HDRDisplayOutputNits protected
HDR.
Definition at line 500 of file GameUserSettings.h.
LastConfirmedAudioQualityLevel
int32 UGameUserSettings::LastConfirmedAudioQualityLevel protected
Definition at line 434 of file GameUserSettings.h.
LastConfirmedFullscreenMode
int32 UGameUserSettings::LastConfirmedFullscreenMode protected
Last user confirmed fullscreen mode setting.
Definition at line 420 of file GameUserSettings.h.
LastCPUBenchmarkResult
float UGameUserSettings::LastCPUBenchmarkResult protected
Result of the last benchmark (CPU); -1 if there has not been a benchmark run.
Definition at line 474 of file GameUserSettings.h.
LastCPUBenchmarkSteps
TArray<float> UGameUserSettings::LastCPUBenchmarkSteps protected
Result of each individual sub-section of the last CPU benchmark; empty if there has not been a benchmark run.
Definition at line 482 of file GameUserSettings.h.
LastGPUBenchmarkMultiplier
float UGameUserSettings::LastGPUBenchmarkMultiplier protected
Multiplier used against the last GPU benchmark.
Definition at line 492 of file GameUserSettings.h.
LastGPUBenchmarkResult
float UGameUserSettings::LastGPUBenchmarkResult protected
Result of the last benchmark (GPU); -1 if there has not been a benchmark run.
Definition at line 478 of file GameUserSettings.h.
LastGPUBenchmarkSteps
TArray<float> UGameUserSettings::LastGPUBenchmarkSteps protected
Result of each individual sub-section of the last GPU benchmark; empty if there has not been a benchmark run.
Definition at line 486 of file GameUserSettings.h.
LastRecommendedScreenHeight
float UGameUserSettings::LastRecommendedScreenHeight protected
Result of the last benchmark; calculated resolution to use.
Definition at line 470 of file GameUserSettings.h.
LastRecommendedScreenWidth
float UGameUserSettings::LastRecommendedScreenWidth protected
Result of the last benchmark; calculated resolution to use.
Definition at line 466 of file GameUserSettings.h.
LastUserConfirmedDesiredScreenHeight
int32 UGameUserSettings::LastUserConfirmedDesiredScreenHeight protected
Desired screen height used to calculate the resolution scale when user changes display mode.
Definition at line 462 of file GameUserSettings.h.
LastUserConfirmedDesiredScreenWidth
int32 UGameUserSettings::LastUserConfirmedDesiredScreenWidth protected
Desired screen width used to calculate the resolution scale when user changes display mode.
Definition at line 458 of file GameUserSettings.h.
LastUserConfirmedResolutionSizeX
uint32 UGameUserSettings::LastUserConfirmedResolutionSizeX protected
Game screen resolution width, in pixels.
Definition at line 389 of file GameUserSettings.h.
LastUserConfirmedResolutionSizeY
uint32 UGameUserSettings::LastUserConfirmedResolutionSizeY protected
Game screen resolution height, in pixels.
Definition at line 393 of file GameUserSettings.h.
MinResolutionScale
float UGameUserSettings::MinResolutionScale protected
Min resolution scale we allow in current display mode.
Definition at line 442 of file GameUserSettings.h.
OnUpdateCloudDataFromGameUserSettings
FUpdateCloudDataFromGameUserSettings UGameUserSettings::OnUpdateCloudDataFromGameUserSettings
Definition at line 550 of file GameUserSettings.h.
OnUpdateGameUserSettingsFileFromCloud
FUpdateGameUserSettingsFileFromCloud UGameUserSettings::OnUpdateGameUserSettingsFileFromCloud
Definition at line 544 of file GameUserSettings.h.
PreferredFullscreenMode
int32 UGameUserSettings::PreferredFullscreenMode protected
Fullscreen mode to use when toggling between windowed and fullscreen.
Same values as r.FullScreenMode.
Definition at line 424 of file GameUserSettings.h.
ResolutionSizeX
uint32 UGameUserSettings::ResolutionSizeX protected
Game screen resolution width, in pixels.
Definition at line 381 of file GameUserSettings.h.
ResolutionSizeY
uint32 UGameUserSettings::ResolutionSizeY protected
Game screen resolution height, in pixels.
Definition at line 385 of file GameUserSettings.h.
ScalabilityQuality
Scalability::FQualityLevels UGameUserSettings::ScalabilityQuality
Definition at line 376 of file GameUserSettings.h.
Version
uint32 UGameUserSettings::Version protected
All settings will be wiped and set to default if the serialized version differs from UE_GAMEUSERSETTINGS_VERSION.
Definition at line 428 of file GameUserSettings.h.
WindowPositions
TArray<FIntPoint> UGameUserSettings::WindowPositions protected
Saved window positions.
Multiple instances running simultaneously can use different ones.
Definition at line 407 of file GameUserSettings.h.
WindowPosX_DEPRECATED
int32 UGameUserSettings::WindowPosX_DEPRECATED protected
Window PosX.
Definition at line 398 of file GameUserSettings.h.
WindowPosY_DEPRECATED
int32 UGameUserSettings::WindowPosY_DEPRECATED protected
Window PosY.
Definition at line 403 of file GameUserSettings.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/GameUserSettings.h