Unreal Engine 5.6 C++ Documentation: UInputDeviceTriggerFeedbackProperty Class Reference
UInputDeviceTriggerFeedbackProperty Class Reference
Sets simple trigger feedback.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceProperties.h>
Public Member Functions
UInputDeviceTriggerFeedbackProperty ()
virtual void EvaluateDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration) override
Native C++ implementation of EvaluateDeviceProperty.
virtual FInputDeviceProperty * GetInternalDeviceProperty () override
Gets a pointer to the current input device property that the IInputInterface can use.
virtual float RecalculateDuration () override
Recalculates this device property's duration.
virtual void ResetDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset=false) override
Native C++ implementation of ResetDeviceProperty Override this in C++ to alter the device property behavior in native code.
virtual void ApplyDeviceProperty (const FPlatformUserId UserId, const FInputDeviceId DeviceId) override
Apply the device property from GetInternalDeviceProperty to the given platform user.
float GetDuration () const
The duration that this device property should last.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
Public Attributes
FDeviceTriggerFeedbackData TriggerData
What position on the trigger that the feedback should be applied to over time (1-9)
TMap< FName, FDeviceTriggerFeedbackData > DeviceOverrideData
A map of device specific color data.
FDeviceTriggerBaseData BaseTriggerData
Protected Member Functions
void EvaluateDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration)
Evaluate this device property for a given duration.
void ResetDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset=false)
Reset the current device property.
template<class TDataLayout>
const TDataLayout * GetDeviceSpecificData (const FPlatformUserId UserId, const FInputDeviceId DeviceId, const TMap< FName, TDataLayout > &InMap) const
Returns the device specific data for the given platform user.
template<class TDataLayout>
TDataLayout * GetDeviceSpecificDataMutable (const FPlatformUserId UserId, const FInputDeviceId DeviceId, TMap< FName, TDataLayout > &InMap)
Static Protected Member Functions
static void ApplyDeviceProperty_Internal (const FPlatformUserId UserId, const FInputDeviceId DeviceId, FInputDeviceProperty *RawProperty)
Apply the given device property.
Protected Attributes
FInputDeviceTriggerResetProperty ResetProperty = {}
Internal property that can be used to reset a given trigger.
float PropertyDuration = 0.0f
The duration that this device property should last.
Detailed Description
Sets simple trigger feedback.
NOTE: This property has platform specific implementations and may behave differently per platform. See the docs for more details on each platform.
Definition at line 330 of file InputDeviceProperties.h.
Constructor & Destructor Documentation
UInputDeviceTriggerFeedbackProperty()
UInputDeviceTriggerFeedbackProperty::UInputDeviceTriggerFeedbackProperty ()
Member Function Documentation
ApplyDeviceProperty()
virtual void UInputDeviceTriggerEffect::ApplyDeviceProperty (const FPlatformUserId UserId, const FInputDeviceId DeviceId) override virtual inherited
Apply the device property from GetInternalDeviceProperty to the given platform user.
Note: To remove any applied affects of this device property, call ResetDeviceProperty.
Parameters
UserId The owning Platform User whose input device this property should be applied to.
Reimplemented from UInputDeviceProperty.
ApplyDeviceProperty_Internal()
void UInputDeviceProperty::ApplyDeviceProperty_Internal (const FPlatformUserId UserId, const FInputDeviceId DeviceId, FInputDeviceProperty * RawProperty) static protected inherited
Apply the given device property.
Parameters
UserId The owning Platform User whose input device this property should be applied to.
RawProperty The internal input device property to apply.
EvaluateDeviceProperty()
void UInputDeviceProperty::EvaluateDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration) protected inherited
Evaluate this device property for a given duration.
If overriding in Blueprints, make sure to call the parent function!
Parameters
PlatformUser The platform user that should receive this device property change
DeltaTime Delta time
Duration The number of seconds that this property has been active. Use this to get things like curve data over time.
Returns
A pointer to the evaluated input device property.
References EvaluateDeviceProperty().
EvaluateDeviceProperty_Implementation()
virtual void UInputDeviceTriggerFeedbackProperty::EvaluateDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration) override virtual
Native C++ implementation of EvaluateDeviceProperty.
Override this to alter your device property in native code.
See also
UInputDeviceProperty::EvaluateDeviceProperty
Reimplemented from UInputDeviceProperty.
GetDeviceSpecificData()
template<class TDataLayout> const TDataLayout * UInputDeviceProperty::GetDeviceSpecificData (const FPlatformUserId UserId, const FInputDeviceId DeviceId, const TMap< FName, TDataLayout > & InMap) const protected inherited
Returns the device specific data for the given platform user.
Returns the default data if none are given
Definition at line 143 of file InputDeviceProperties.h.
References UInputDeviceSubsystem::Get(), GetDeviceSpecificData(), FHardwareDeviceIdentifier::HardwareDeviceIdentifier, UInputDeviceProperty(), and UInputDeviceSubsystem.
GetDeviceSpecificDataMutable()
template<class TDataLayout> TDataLayout * UInputDeviceProperty::GetDeviceSpecificDataMutable (const FPlatformUserId UserId, const FInputDeviceId DeviceId, TMap< FName, TDataLayout > & InMap) inline protected inherited
Definition at line 126 of file InputDeviceProperties.h.
References GetDeviceSpecificData().
GetDuration()
float UInputDeviceProperty::GetDuration () const inherited
The duration that this device property should last.
Override this if your property has any dynamic curves to be the max time range.
GetInternalDeviceProperty()
virtual FInputDeviceProperty * UInputDeviceTriggerFeedbackProperty::GetInternalDeviceProperty () override virtual
Gets a pointer to the current input device property that the IInputInterface can use.
Reimplemented from UInputDeviceTriggerEffect.
PostEditChangeChainProperty()
virtual void UInputDeviceProperty::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual inherited
RecalculateDuration()
virtual float UInputDeviceTriggerFeedbackProperty::RecalculateDuration () override virtual
Recalculates this device property's duration.
This should be called whenever there are changes made to things like curves, or other time sensitive properties.
Reimplemented from UInputDeviceProperty.
ResetDeviceProperty()
void UInputDeviceProperty::ResetDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset = false) protected inherited
Reset the current device property.
Provides an opportunity to reset device state after evaluation is complete. If overriding in Blueprints, make sure to call the parent function!
Parameters
PlatformUser The platform user that should receive this device property change
References ResetDeviceProperty().
ResetDeviceProperty_Implementation()
virtual void UInputDeviceTriggerEffect::ResetDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset = false) override virtual inherited
Native C++ implementation of ResetDeviceProperty Override this in C++ to alter the device property behavior in native code.
See also
ResetDeviceProperty
Reimplemented from UInputDeviceProperty.
Member Data Documentation
BaseTriggerData
FDeviceTriggerBaseData UInputDeviceTriggerEffect::BaseTriggerData inherited
Definition at line 299 of file InputDeviceProperties.h.
DeviceOverrideData
TMap<FName, FDeviceTriggerFeedbackData> UInputDeviceTriggerFeedbackProperty::DeviceOverrideData
A map of device specific color data.
If no overrides are specified, the Default hardware data will be used
Definition at line 349 of file InputDeviceProperties.h.
PropertyDuration
float UInputDeviceProperty::PropertyDuration = 0.0f protected inherited
The duration that this device property should last.
Override this if your property has any dynamic curves to be the max time range.
A duration of 0 means that the device property will be treated as a "One Shot" effect, being applied once before being removed by the Input Device Subsystem.
Definition at line 139 of file InputDeviceProperties.h.
ResetProperty
FInputDeviceTriggerResetProperty UInputDeviceTriggerEffect::ResetProperty = {} protected inherited
Internal property that can be used to reset a given trigger.
Definition at line 304 of file InputDeviceProperties.h.
TriggerData
FDeviceTriggerFeedbackData UInputDeviceTriggerFeedbackProperty::TriggerData
What position on the trigger that the feedback should be applied to over time (1-9)
Definition at line 345 of file InputDeviceProperties.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceProperties.h