Unreal Engine 5.6 C++ Documentation: UInputSettings Class Reference
UInputSettings Class Reference
Project wide settings for input handling.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputSettings.h>
Public Member Functions
virtual void PostEditChangeChainProperty (struct FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded) override
void RemoveInvalidKeys ()
virtual void PostInitProperties () override
void AddActionMapping (const FInputActionKeyMapping &KeyMapping, bool bForceRebuildKeymaps=true)
Programmatically add an action mapping to the project defaults.
void GetActionMappingByName (const FName InActionName, TArray< FInputActionKeyMapping > &OutMappings) const
void RemoveActionMapping (const FInputActionKeyMapping &KeyMapping, bool bForceRebuildKeymaps=true)
Programmatically remove an action mapping to the project defaults.
void AddAxisMapping (const FInputAxisKeyMapping &KeyMapping, bool bForceRebuildKeymaps=true)
Programmatically add an axis mapping to the project defaults.
void GetAxisMappingByName (const FName InAxisName, TArray< FInputAxisKeyMapping > &OutMappings) const
Retrieve all axis mappings by a certain name.
void RemoveAxisMapping (const FInputAxisKeyMapping &KeyMapping, bool bForceRebuildKeymaps=true)
Programmatically remove an axis mapping to the project defaults.
void SaveKeyMappings ()
Flush the current mapping values to the config file.
void GetActionNames (TArray< FName > &ActionNames) const
Populate a list of all defined action names.
void GetAxisNames (TArray< FName > &AxisNames) const
Populate a list of all defined axis names.
void ForceRebuildKeymaps ()
When changes are made to the default mappings, push those changes out to PlayerInput key maps.
FName GetUniqueActionName (const FName BaseActionMappingName)
Finds unique action name based on existing action names.
FName GetUniqueAxisName (const FName BaseAxisMappingName)
Finds unique axis name based on existing action names.
void AddActionMapping (FInputActionKeyMapping &NewMapping)
Append new mapping to existing list.
void AddAxisMapping (FInputAxisKeyMapping &NewMapping)
Append new mapping to existing list.
const TArray< FInputActionKeyMapping > & GetActionMappings () const
Ask for all the action mappings.
const TArray< FInputAxisKeyMapping > & GetAxisMappings () const
Ask for all the axis mappings.
const TArray< FInputActionSpeechMapping > & GetSpeechMappings () const
Ask for all the speech mappings.
bool DoesActionExist (const FName InActionName)
Finds unique action name based on existing action names.
bool DoesAxisExist (const FName InAxisName)
Finds unique axis name based on existing action names.
bool DoesSpeechExist (const FName InSpeechName)
Finds unique speech name based on existing speech names.
Static Public Member Functions
static UInputSettings * GetInputSettings ()
Returns the game local input settings (action mappings, axis mappings, etc...)
static const TArray< FName > & GetAllActionAndAxisNames ()
Returns all known legacy action and axis names that is useful for properties that you want a drop down selection of the available names on a UPROPERTY i.e.
static const FName GetActionMappingsPropertyName ()
Get the member name for the details panel.
static const FName GetAxisMappingsPropertyName ()
Get the member name for the details panel.
static UClass * GetDefaultPlayerInputClass ()
static UClass * GetDefaultInputComponentClass ()
static void SetDefaultPlayerInputClass (TSubclassOf< UPlayerInput > NewDefaultPlayerInputClass)
Set the default player input class.
static void SetDefaultInputComponentClass (TSubclassOf< UInputComponent > NewDefaultInputComponentClass)
Set the default input component class.
Public Attributes
FSoftObjectPath DefaultTouchInterface
The default on-screen touch input interface for the game (can be null to disable the onscreen interface)
TArray< FKey > ConsoleKeys
The keys which open the console.
Detailed Description
Project wide settings for input handling.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Input/index.html
Definition at line 22 of file InputSettings.h.
Member Function Documentation
AddActionMapping() [1/2]
void UInputSettings::AddActionMapping (const FInputActionKeyMapping & KeyMapping, bool bForceRebuildKeymaps = true)
Programmatically add an action mapping to the project defaults.
References AddActionMapping().
AddActionMapping() [2/2]
void UInputSettings::AddActionMapping (FInputActionKeyMapping & NewMapping)
Append new mapping to existing list.
References AddActionMapping().
AddAxisMapping() [1/2]
void UInputSettings::AddAxisMapping (const FInputAxisKeyMapping & KeyMapping, bool bForceRebuildKeymaps = true)
Programmatically add an axis mapping to the project defaults.
References AddAxisMapping().
AddAxisMapping() [2/2]
void UInputSettings::AddAxisMapping (FInputAxisKeyMapping & NewMapping)
Append new mapping to existing list.
References AddAxisMapping().
DoesActionExist()
bool UInputSettings::DoesActionExist (const FName InActionName)
Finds unique action name based on existing action names.
References DoesActionExist().
DoesAxisExist()
bool UInputSettings::DoesAxisExist (const FName InAxisName)
Finds unique axis name based on existing action names.
References DoesAxisExist().
DoesSpeechExist()
bool UInputSettings::DoesSpeechExist (const FName InSpeechName)
Finds unique speech name based on existing speech names.
References DoesSpeechExist().
ForceRebuildKeymaps()
void UInputSettings::ForceRebuildKeymaps ()
When changes are made to the default mappings, push those changes out to PlayerInput key maps.
References ForceRebuildKeymaps().
GetActionMappingByName()
void UInputSettings::GetActionMappingByName (const FName InActionName, TArray< FInputActionKeyMapping > & OutMappings) const
References GetActionMappingByName().
GetActionMappings()
const TArray< FInputActionKeyMapping > & UInputSettings::GetActionMappings () const
Ask for all the action mappings.
References GetActionMappings().
GetActionMappingsPropertyName()
const FName UInputSettings::GetActionMappingsPropertyName () static
Get the member name for the details panel.
References GetActionMappingsPropertyName().
GetActionNames()
void UInputSettings::GetActionNames (TArray< FName > & ActionNames) const
Populate a list of all defined action names.
References GetActionNames().
GetAllActionAndAxisNames()
const TArray< FName > & UInputSettings::GetAllActionAndAxisNames () static
Returns all known legacy action and axis names that is useful for properties that you want a drop down selection of the available names on a UPROPERTY i.e.
meta=(GetOptions="Engine.InputSettings.GetAllActionAndAxisNames")
References GetAllActionAndAxisNames().
GetAxisMappingByName()
void UInputSettings::GetAxisMappingByName (const FName InAxisName, TArray< FInputAxisKeyMapping > & OutMappings) const
Retrieve all axis mappings by a certain name.
References GetAxisMappingByName().
GetAxisMappings()
const TArray< FInputAxisKeyMapping > & UInputSettings::GetAxisMappings () const
Ask for all the axis mappings.
References GetAxisMappings().
GetAxisMappingsPropertyName()
const FName UInputSettings::GetAxisMappingsPropertyName () static
Get the member name for the details panel.
References GetAxisMappingsPropertyName().
GetAxisNames()
void UInputSettings::GetAxisNames (TArray< FName > & AxisNames) const
Populate a list of all defined axis names.
References GetAxisNames().
GetDefaultInputComponentClass()
UClass * UInputSettings::GetDefaultInputComponentClass () static
References GetDefaultInputComponentClass().
GetDefaultPlayerInputClass()
UClass * UInputSettings::GetDefaultPlayerInputClass () static
References GetDefaultPlayerInputClass().
GetInputSettings()
UInputSettings * UInputSettings::GetInputSettings () static
Returns the game local input settings (action mappings, axis mappings, etc...)
References GetInputSettings().
GetSpeechMappings()
const TArray< FInputActionSpeechMapping > & UInputSettings::GetSpeechMappings () const
Ask for all the speech mappings.
References GetSpeechMappings().
GetUniqueActionName()
FName UInputSettings::GetUniqueActionName (const FName BaseActionMappingName)
Finds unique action name based on existing action names.
References GetUniqueActionName().
GetUniqueAxisName()
FName UInputSettings::GetUniqueAxisName (const FName BaseAxisMappingName)
Finds unique axis name based on existing action names.
References GetUniqueAxisName().
PostEditChangeChainProperty()
virtual void UInputSettings::PostEditChangeChainProperty (struct FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UInputSettings::PostInitProperties () override virtual
PostReloadConfig()
virtual void UInputSettings::PostReloadConfig (class FProperty * PropertyThatWasLoaded) override virtual
RemoveActionMapping()
void UInputSettings::RemoveActionMapping (const FInputActionKeyMapping & KeyMapping, bool bForceRebuildKeymaps = true)
Programmatically remove an action mapping to the project defaults.
References RemoveActionMapping().
RemoveAxisMapping()
void UInputSettings::RemoveAxisMapping (const FInputAxisKeyMapping & KeyMapping, bool bForceRebuildKeymaps = true)
Programmatically remove an axis mapping to the project defaults.
References RemoveAxisMapping().
RemoveInvalidKeys()
void UInputSettings::RemoveInvalidKeys ()
SaveKeyMappings()
void UInputSettings::SaveKeyMappings ()
Flush the current mapping values to the config file.
References SaveKeyMappings().
SetDefaultInputComponentClass()
void UInputSettings::SetDefaultInputComponentClass (TSubclassOf< UInputComponent > NewDefaultInputComponentClass) static
Set the default input component class.
Parameters
NewDefaultInputComponentClass The new class to use.
References SetDefaultInputComponentClass().
SetDefaultPlayerInputClass()
void UInputSettings::SetDefaultPlayerInputClass (TSubclassOf< UPlayerInput > NewDefaultPlayerInputClass) static
Set the default player input class.
Parameters
NewDefaultPlayerInputClass The new class to use.
References SetDefaultPlayerInputClass().
Member Data Documentation
ConsoleKeys
TArray<FKey> UInputSettings::ConsoleKeys
The keys which open the console.
Definition at line 188 of file InputSettings.h.
DefaultTouchInterface
FSoftObjectPath UInputSettings::DefaultTouchInterface
The default on-screen touch input interface for the game (can be null to disable the onscreen interface)
Definition at line 184 of file InputSettings.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputSettings.h