Unreal Engine 5.6 C++ Documentation: UInputDeviceProperty Class Reference
UInputDeviceProperty Class Reference
Base class that represents a single Input Device Property.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceProperties.h>
Public Member Functions
UInputDeviceProperty (const FObjectInitializer &ObjectInitializer=FObjectInitializer::Get())
float GetDuration () const
The duration that this device property should last.
virtual float RecalculateDuration ()
Recalculates this device property's duration.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
Protected Member Functions
void EvaluateDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration)
Evaluate this device property for a given duration.
virtual void EvaluateDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration)
Native C++ implementation of EvaluateDeviceProperty.
void ResetDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset=false)
Reset the current device property.
virtual void ResetDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset=false)
Native C++ implementation of ResetDeviceProperty Override this in C++ to alter the device property behavior in native code.
virtual void ApplyDeviceProperty (const FPlatformUserId UserId, const FInputDeviceId DeviceId)
Apply the device property from GetInternalDeviceProperty to the given platform user.
virtual FInputDeviceProperty * GetInternalDeviceProperty ()
Gets a pointer to the current input device property that the IInputInterface can use.
template<class TDataLayout>
const TDataLayout * GetDeviceSpecificData (const FPlatformUserId UserId, const FInputDeviceId DeviceId, const TMap< FName, TDataLayout > &InMap) const
Returns the device specific data for the given platform user.
template<class TDataLayout>
TDataLayout * GetDeviceSpecificDataMutable (const FPlatformUserId UserId, const FInputDeviceId DeviceId, TMap< FName, TDataLayout > &InMap)
Static Protected Member Functions
static void ApplyDeviceProperty_Internal (const FPlatformUserId UserId, const FInputDeviceId DeviceId, FInputDeviceProperty *RawProperty)
Apply the given device property.
Protected Attributes
float PropertyDuration = 0.0f
The duration that this device property should last.
Friends
class UInputDeviceSubsystem
Detailed Description
Base class that represents a single Input Device Property.
An Input Device Property represents a feature that can be set on an input device. Things like what color a light is, advanced rumble patterns, or trigger haptics.
This top level object can then be evaluated at a specific time to create a lower level FInputDeviceProperty, which the IInputInterface implementation can interpret however it desires.
The behavior of device properties can vary depending on the current platform. Some platforms may not support certain device properties. An older gamepad may not have any advanced trigger haptics for example.
Definition at line 31 of file InputDeviceProperties.h.
Constructor & Destructor Documentation
UInputDeviceProperty()
UInputDeviceProperty::UInputDeviceProperty (const FObjectInitializer & ObjectInitializer = FObjectInitializer::Get())
References UInputDeviceProperty().
Member Function Documentation
ApplyDeviceProperty()
virtual void UInputDeviceProperty::ApplyDeviceProperty (const FPlatformUserId UserId, const FInputDeviceId DeviceId) protected virtual
Apply the device property from GetInternalDeviceProperty to the given platform user.
Note: To remove any applied affects of this device property, call ResetDeviceProperty.
Parameters
UserId The owning Platform User whose input device this property should be applied to.
Reimplemented in UInputDeviceAudioBasedVibrationProperty, and UInputDeviceTriggerEffect.
References ApplyDeviceProperty().
ApplyDeviceProperty_Internal()
void UInputDeviceProperty::ApplyDeviceProperty_Internal (const FPlatformUserId UserId, const FInputDeviceId DeviceId, FInputDeviceProperty * RawProperty) static protected
Apply the given device property.
Parameters
UserId The owning Platform User whose input device this property should be applied to.
RawProperty The internal input device property to apply.
EvaluateDeviceProperty()
void UInputDeviceProperty::EvaluateDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration) protected
Evaluate this device property for a given duration.
If overriding in Blueprints, make sure to call the parent function!
Parameters
PlatformUser The platform user that should receive this device property change
DeltaTime Delta time
Duration The number of seconds that this property has been active. Use this to get things like curve data over time.
Returns
A pointer to the evaluated input device property.
References EvaluateDeviceProperty().
EvaluateDeviceProperty_Implementation()
virtual void UInputDeviceProperty::EvaluateDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, const float DeltaTime, const float Duration) protected virtual
Native C++ implementation of EvaluateDeviceProperty.
Override this to alter your device property in native code.
See also
UInputDeviceProperty::EvaluateDeviceProperty
Reimplemented in UColorInputDeviceCurveProperty, UColorInputDeviceProperty, UInputDeviceAudioBasedVibrationProperty, UInputDeviceTriggerFeedbackProperty, UInputDeviceTriggerResistanceProperty, and UInputDeviceTriggerVibrationProperty.
References EvaluateDeviceProperty_Implementation().
GetDeviceSpecificData()
template<class TDataLayout> const TDataLayout * UInputDeviceProperty::GetDeviceSpecificData (const FPlatformUserId UserId, const FInputDeviceId DeviceId, const TMap< FName, TDataLayout > & InMap) const protected
Returns the device specific data for the given platform user.
Returns the default data if none are given
Definition at line 143 of file InputDeviceProperties.h.
References UInputDeviceSubsystem::Get(), GetDeviceSpecificData(), FHardwareDeviceIdentifier::HardwareDeviceIdentifier, UInputDeviceProperty(), and UInputDeviceSubsystem.
GetDeviceSpecificDataMutable()
template<class TDataLayout> TDataLayout * UInputDeviceProperty::GetDeviceSpecificDataMutable (const FPlatformUserId UserId, const FInputDeviceId DeviceId, TMap< FName, TDataLayout > & InMap) inline protected
Definition at line 126 of file InputDeviceProperties.h.
References GetDeviceSpecificData().
GetDuration()
float UInputDeviceProperty::GetDuration () const
The duration that this device property should last.
Override this if your property has any dynamic curves to be the max time range.
GetInternalDeviceProperty()
virtual FInputDeviceProperty * UInputDeviceProperty::GetInternalDeviceProperty () inline protected virtual
Gets a pointer to the current input device property that the IInputInterface can use.
Reimplemented in UColorInputDeviceCurveProperty, UColorInputDeviceProperty, UInputDeviceAudioBasedVibrationProperty, UInputDeviceTriggerEffect, UInputDeviceTriggerFeedbackProperty, UInputDeviceTriggerResistanceProperty, and UInputDeviceTriggerVibrationProperty.
Definition at line 90 of file InputDeviceProperties.h.
References GetInternalDeviceProperty().
PostEditChangeChainProperty()
virtual void UInputDeviceProperty::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
RecalculateDuration()
virtual float UInputDeviceProperty::RecalculateDuration () virtual
Recalculates this device property's duration.
This should be called whenever there are changes made to things like curves, or other time sensitive properties.
Reimplemented in UColorInputDeviceCurveProperty, UInputDeviceAudioBasedVibrationProperty, UInputDeviceTriggerFeedbackProperty, and UInputDeviceTriggerVibrationProperty.
ResetDeviceProperty()
void UInputDeviceProperty::ResetDeviceProperty (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset = false) protected
Reset the current device property.
Provides an opportunity to reset device state after evaluation is complete. If overriding in Blueprints, make sure to call the parent function!
Parameters
PlatformUser The platform user that should receive this device property change
References ResetDeviceProperty().
ResetDeviceProperty_Implementation()
virtual void UInputDeviceProperty::ResetDeviceProperty_Implementation (const FPlatformUserId PlatformUser, const FInputDeviceId DeviceId, bool bForceReset = false) protected virtual
Native C++ implementation of ResetDeviceProperty Override this in C++ to alter the device property behavior in native code.
See also
ResetDeviceProperty
Reimplemented in UColorInputDeviceCurveProperty, UColorInputDeviceProperty, and UInputDeviceTriggerEffect.
References ResetDeviceProperty_Implementation().
Friends And Related Symbol Documentation
UInputDeviceSubsystem
friend class UInputDeviceSubsystem friend
Definition at line 34 of file InputDeviceProperties.h.
References UInputDeviceSubsystem.
Member Data Documentation
PropertyDuration
float UInputDeviceProperty::PropertyDuration = 0.0f protected
The duration that this device property should last.
Override this if your property has any dynamic curves to be the max time range.
A duration of 0 means that the device property will be treated as a "One Shot" effect, being applied once before being removed by the Input Device Subsystem.
Definition at line 139 of file InputDeviceProperties.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceProperties.h