Unreal Engine 5.6 C++ Documentation: UInputDeviceSubsystem Class Reference
UInputDeviceSubsystem Class Reference
Delegate called when a user changed the hardware they are using for input.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceSubsystem.h>
Classes
struct FLatestInputDeviceData
Data store about the input device that was most recently used by a specific FPlatformUserId.
struct FResetPIEData
Public Member Functions
virtual void Initialize (FSubsystemCollectionBase &Collection) override
virtual void Deinitialize () override
virtual bool ShouldCreateSubsystem (UObject *Outer) const override
virtual UWorld * GetTickableGameObjectWorld () const override
virtual ETickableTickType GetTickableTickType () const override
virtual bool IsTickable () const override
virtual bool IsTickableInEditor () const override
virtual TStatId GetStatId () const override
virtual void Tick (float InDeltaTime) override
FInputDevicePropertyHandle ActivateDeviceProperty (UInputDeviceProperty *Property, const FActivateDevicePropertyParams &Params)
Starts tracking the given device property as an "Active" property.
FInputDevicePropertyHandle ActivateDevicePropertyOfClass (TSubclassOf< UInputDeviceProperty > PropertyClass, const FActivateDevicePropertyParams &Params)
Spawn a new instance of the given device property class and activate it.
UInputDeviceProperty * GetActiveDeviceProperty (const FInputDevicePropertyHandle Handle) const
Returns a pointer to the active input device property with the given handle.
bool IsPropertyActive (const FInputDevicePropertyHandle Handle) const
Returns true if the property associated with the given handle is currently active, and it is not pending removal.
void RemoveDevicePropertyByHandle (const FInputDevicePropertyHandle HandleToRemove)
Remove a single device property based on it's handle.
void RemoveDevicePropertyHandles (const TSet< FInputDevicePropertyHandle > &HandlesToRemove)
Remove a set of device properties based on their handles.
void RemoveAllDeviceProperties ()
Removes all the current Input Device Properties that are active, regardless of the Platform User.
FHardwareDeviceIdentifier GetMostRecentlyUsedHardwareDevice (const FPlatformUserId InUserId) const
Gets the most recently used hardware input device for the given platform user.
FInputDeviceId GetMostRecentlyUsedInputDeviceId (const FPlatformUserId InUserId, const EHardwareDevicePrimaryType OfType=EHardwareDevicePrimaryType::Unspecified) const
Returns the most recently used FInputDeviceId for the given platform user id.
FHardwareDeviceIdentifier GetInputDeviceHardwareIdentifier (const FInputDeviceId InputDevice) const
FInputDeviceId GetLatestDeviceOfType (const FPlatformUserId InUserId, const EHardwareDevicePrimaryType OfType) const
Returns the latest used input device for a specific type of hardware.
Static Public Member Functions
static UInputDeviceSubsystem * Get ()
Returns a pointer to the Input Device Engine Subsystem if it is available.
Public Attributes
FHardwareInputDeviceChanged OnInputHardwareDeviceChanged
A delegate that is fired when a platform user changes what Hardware Input device they are using.
Protected Member Functions
void SetMostRecentlyUsedHardwareDevice (const FInputDeviceId InDeviceId, const FHardwareDeviceIdentifier &InHardwareId)
Set the most recently used hardware device from the input processor.
void OnPrePIEStarted (bool bSimulating)
void OnPIEPaused (bool bSimulating)
void OnPIEResumed (bool bSimulating)
void OnPIEStopped (bool bSimulating)
Protected Attributes
bool bIsPIEPlaying = false
TArray< FResetPIEData > PropertyClassesRequiringReset
A set of device properties that should be reset when PIE ends.
TSet< FActiveDeviceProperty > ActiveProperties
Set of currently active input device properties that will be evaluated on tick.
TSet< FInputDevicePropertyHandle > PropertiesPendingRemoval
Set of property handles the properties that are currently pending manual removal.
TMap< FInputDeviceId, FHardwareDeviceIdentifier > LatestInputDeviceIdentifiers
A map of an input device to it's most recent hardware device identifier.
TMap< FPlatformUserId, FLatestInputDeviceData > LatestUserDeviceIdentifiers
A map of platform user's to their most recent hardware device identifiers.
TSharedPtr< class FInputDeviceSubsystemProcessor > InputPreprocessor
An input processor that is used to determine the most recently used hardware device for each user.
Friends
class FInputDeviceSubsystemProcessor
class FInputDeviceDebugTools
Detailed Description
Delegate called when a user changed the hardware they are using for input.
Parameters
UserId The Platform user whose device has changed The input device subsystem provides an interface to allow users to set Input Device Properties on any Platform User.
Definition at line 118 of file InputDeviceSubsystem.h.
Member Function Documentation
ActivateDeviceProperty()
FInputDevicePropertyHandle UInputDeviceSubsystem::ActivateDeviceProperty (UInputDeviceProperty * Property, const FActivateDevicePropertyParams & Params)
Starts tracking the given device property as an "Active" property.
This means that the property will be evaluted and applied to its platform user
NOTE: This does NOT make a new instance of the given property. If you pass in the same object before it is completely evaluated, then you see undesired effects.
References ActivateDeviceProperty().
ActivateDevicePropertyOfClass()
FInputDevicePropertyHandle UInputDeviceSubsystem::ActivateDevicePropertyOfClass (TSubclassOf< UInputDeviceProperty > PropertyClass, const FActivateDevicePropertyParams & Params)
Spawn a new instance of the given device property class and activate it.
References ActivateDevicePropertyOfClass().
Deinitialize()
virtual void UInputDeviceSubsystem::Deinitialize () override virtual
References Deinitialize().
Get()
UInputDeviceSubsystem * UInputDeviceSubsystem::Get () static
Returns a pointer to the Input Device Engine Subsystem if it is available.
NOTE: This may be null if the bEnableInputDeviceSubsystem flag in UInputSettings is set to false!
References Get().
GetActiveDeviceProperty()
UInputDeviceProperty * UInputDeviceSubsystem::GetActiveDeviceProperty (const FInputDevicePropertyHandle Handle) const
Returns a pointer to the active input device property with the given handle.
Returns null if the property doesn't exist
References GetActiveDeviceProperty().
GetInputDeviceHardwareIdentifier()
FHardwareDeviceIdentifier UInputDeviceSubsystem::GetInputDeviceHardwareIdentifier (const FInputDeviceId InputDevice) const
References GetInputDeviceHardwareIdentifier().
GetLatestDeviceOfType()
FInputDeviceId UInputDeviceSubsystem::GetLatestDeviceOfType (const FPlatformUserId InUserId, const EHardwareDevicePrimaryType OfType) const
Returns the latest used input device for a specific type of hardware.
References EHardwareDevicePrimaryType, and GetLatestDeviceOfType().
GetMostRecentlyUsedHardwareDevice()
FHardwareDeviceIdentifier UInputDeviceSubsystem::GetMostRecentlyUsedHardwareDevice (const FPlatformUserId InUserId) const
Gets the most recently used hardware input device for the given platform user.
References GetMostRecentlyUsedHardwareDevice().
GetMostRecentlyUsedInputDeviceId()
FInputDeviceId UInputDeviceSubsystem::GetMostRecentlyUsedInputDeviceId (const FPlatformUserId InUserId, const EHardwareDevicePrimaryType OfType = EHardwareDevicePrimaryType::Unspecified) const
Returns the most recently used FInputDeviceId for the given platform user id.
This will be INPUTDEVICEID_NONE if there is no known device for the given user.
Parameters
InUserId The platform user to find the most recent device for
OfType The type of input device to filter by. If unspecified, then the latest device regardless of its type will be returned.
References EHardwareDevicePrimaryType, GetMostRecentlyUsedInputDeviceId(), and Unspecified.
GetStatId()
virtual TStatId UInputDeviceSubsystem::GetStatId () const override virtual
References GetStatId().
GetTickableGameObjectWorld()
virtual UWorld * UInputDeviceSubsystem::GetTickableGameObjectWorld () const override virtual
References GetTickableGameObjectWorld().
GetTickableTickType()
virtual ETickableTickType UInputDeviceSubsystem::GetTickableTickType () const override virtual
References GetTickableTickType().
Initialize()
virtual void UInputDeviceSubsystem::Initialize (FSubsystemCollectionBase & Collection) override virtual
References Initialize().
IsPropertyActive()
bool UInputDeviceSubsystem::IsPropertyActive (const FInputDevicePropertyHandle Handle) const
Returns true if the property associated with the given handle is currently active, and it is not pending removal.
References IsPropertyActive().
IsTickable()
virtual bool UInputDeviceSubsystem::IsTickable () const override virtual
References IsTickable().
IsTickableInEditor()
virtual bool UInputDeviceSubsystem::IsTickableInEditor () const override virtual
References IsTickableInEditor().
OnPIEPaused()
void UInputDeviceSubsystem::OnPIEPaused (bool bSimulating) protected
OnPIEResumed()
void UInputDeviceSubsystem::OnPIEResumed (bool bSimulating) protected
OnPIEStopped()
void UInputDeviceSubsystem::OnPIEStopped (bool bSimulating) protected
OnPrePIEStarted()
void UInputDeviceSubsystem::OnPrePIEStarted (bool bSimulating) protected
RemoveAllDeviceProperties()
void UInputDeviceSubsystem::RemoveAllDeviceProperties ()
Removes all the current Input Device Properties that are active, regardless of the Platform User.
References RemoveAllDeviceProperties().
RemoveDevicePropertyByHandle()
void UInputDeviceSubsystem::RemoveDevicePropertyByHandle (const FInputDevicePropertyHandle HandleToRemove)
Remove a single device property based on it's handle.
Parameters
FInputDevicePropertyHandle Device property handle to be removed
Returns
The number of removed device properties.
References RemoveDevicePropertyByHandle().
RemoveDevicePropertyHandles()
void UInputDeviceSubsystem::RemoveDevicePropertyHandles (const TSet< FInputDevicePropertyHandle > & HandlesToRemove)
Remove a set of device properties based on their handles.
Parameters
HandlesToRemove The set of device property handles to remove
Returns
The number of removed device properties
References RemoveDevicePropertyHandles().
SetMostRecentlyUsedHardwareDevice()
void UInputDeviceSubsystem::SetMostRecentlyUsedHardwareDevice (const FInputDeviceId InDeviceId, const FHardwareDeviceIdentifier & InHardwareId) protected
Set the most recently used hardware device from the input processor.
References SetMostRecentlyUsedHardwareDevice().
ShouldCreateSubsystem()
virtual bool UInputDeviceSubsystem::ShouldCreateSubsystem (UObject * Outer) const override virtual
References ShouldCreateSubsystem().
Tick()
virtual void UInputDeviceSubsystem::Tick (float InDeltaTime) override virtual
References Tick().
Friends And Related Symbol Documentation
FInputDeviceDebugTools
friend class FInputDeviceDebugTools friend
Definition at line 122 of file InputDeviceSubsystem.h.
References FInputDeviceDebugTools.
FInputDeviceSubsystemProcessor
friend class FInputDeviceSubsystemProcessor friend
Definition at line 121 of file InputDeviceSubsystem.h.
References FInputDeviceSubsystemProcessor.
Member Data Documentation
ActiveProperties
TSet<FActiveDeviceProperty> UInputDeviceSubsystem::ActiveProperties protected
Set of currently active input device properties that will be evaluated on tick.
Definition at line 259 of file InputDeviceSubsystem.h.
bIsPIEPlaying
bool UInputDeviceSubsystem::bIsPIEPlaying = false protected
Definition at line 234 of file InputDeviceSubsystem.h.
InputPreprocessor
TSharedPtr<class FInputDeviceSubsystemProcessor> UInputDeviceSubsystem::InputPreprocessor protected
An input processor that is used to determine the most recently used hardware device for each user.
Definition at line 294 of file InputDeviceSubsystem.h.
LatestInputDeviceIdentifiers
TMap<FInputDeviceId, FHardwareDeviceIdentifier> UInputDeviceSubsystem::LatestInputDeviceIdentifiers protected
A map of an input device to it's most recent hardware device identifier.
Definition at line 271 of file InputDeviceSubsystem.h.
LatestUserDeviceIdentifiers
TMap<FPlatformUserId, FLatestInputDeviceData> UInputDeviceSubsystem::LatestUserDeviceIdentifiers protected
A map of platform user's to their most recent hardware device identifiers.
Definition at line 291 of file InputDeviceSubsystem.h.
OnInputHardwareDeviceChanged
FHardwareInputDeviceChanged UInputDeviceSubsystem::OnInputHardwareDeviceChanged
A delegate that is fired when a platform user changes what Hardware Input device they are using.
Definition at line 219 of file InputDeviceSubsystem.h.
PropertiesPendingRemoval
TSet<FInputDevicePropertyHandle> UInputDeviceSubsystem::PropertiesPendingRemoval protected
Set of property handles the properties that are currently pending manual removal.
This is populated by the "Remove device property" functions.
Definition at line 266 of file InputDeviceSubsystem.h.
PropertyClassesRequiringReset
TArray<FResetPIEData> UInputDeviceSubsystem::PropertyClassesRequiringReset protected
A set of device properties that should be reset when PIE ends.
This ensures that each device is reset for the editor
Definition at line 251 of file InputDeviceSubsystem.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/InputDeviceSubsystem.h