Unreal Engine 5.6 C++ API: UBTDecorator_TimeLimit Class Reference
UBTDecorator_TimeLimit Class Reference
#include "BTDecorator_TimeLimit.h"
Protected Member Functions
virtual bool CalculateRawConditionValue (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) const override
virtual void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
virtual uint16 GetInstanceMemorySize () const override
virtual void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
virtual void OnBecomeRelevant (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) override
virtual void OnCeaseRelevant (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) override
virtual void TickNode (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, float DeltaSeconds) override
Private Member Functions
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () UPROPERTY() FValueOrBBKey_Float TimeLimit
max allowed time for execution of underlying node
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
Detailed Description
Definition at line 15 of file BTDecorator_TimeLimit.h.
Member Function Documentation
CalculateRawConditionValue()
virtual bool UBTDecorator_TimeLimit::CalculateRawConditionValue (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) const override protected virtual
CleanupMemory()
virtual void UBTDecorator_TimeLimit::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override protected virtual
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_TimeLimit::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues().
Referenced by DescribeRuntimeValues().
GENERATED_UCLASS_BODY()
UBTDecorator_TimeLimit::GENERATED_UCLASS_BODY () private
max allowed time for execution of underlying node
References Category, TimeLimit, and UPROPERTY.
GetInstanceMemorySize()
virtual uint16 UBTDecorator_TimeLimit::GetInstanceMemorySize () const override protected virtual
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_TimeLimit::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_TimeLimit::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
InitializeMemory()
virtual void UBTDecorator_TimeLimit::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override protected virtual
OnBecomeRelevant()
virtual void UBTDecorator_TimeLimit::OnBecomeRelevant (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) override protected virtual
OnCeaseRelevant()
virtual void UBTDecorator_TimeLimit::OnCeaseRelevant (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) override protected virtual
TickNode()
virtual void UBTDecorator_TimeLimit::TickNode (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, float DeltaSeconds) override protected virtual
The documentation for this class was generated from the following file:
BTDecorator_TimeLimit.h