Unreal Engine 5.6 C++ API: FInstanceAttributeTracker::FAnyValidIterator< Mask > Class Template Reference
FInstanceAttributeTracker::FAnyValidIterator< Mask > Class Template Reference
Iterator for iterating tracked state with the given flags.
#include "InstanceAttributeTracker.h"
Public Member Functions
FORCEINLINE FAnyValidIterator ()=default
FORCEINLINE FAnyValidIterator (const FInstanceAttributeTracker *InTracker, int32 StartIndex)
FORCEINLINE void AdvanceToNext ()
FORCEINLINE void AdvanceUntilAny ()
FORCEINLINE int32 GetIndex () const
FORCEINLINE uint32 GetMask () const
FORCEINLINE operator bool () const
FORCEINLINE FAnyValidIterator & operator++ ()
template<EFlag Flag>
FORCEINLINE bool TestFlag () const
Private Attributes
ElementType CurrentElement
int32 ElementIndex = 0
int32 ElementOffset = 0
const FInstanceAttributeTracker * Tracker = nullptr
Static Private Attributes
static constexpr ElementType ElementMask = FBitManip::FRepMask<Mask, uint32(EFlag::Num)>::Result
Detailed Description
template<uint32 Mask = AnyFlagMask>
class FInstanceAttributeTracker::FAnyValidIterator< Mask >
Iterator for iterating tracked state with the given flags.
Uses bit logic to efficiently skip empty (under the given mask) sections.
Definition at line 316 of file InstanceAttributeTracker.h.
Constructor & Destructor Documentation
FAnyValidIterator() [1/2]
template<uint32 Mask = AnyFlagMask> FORCEINLINE FInstanceAttributeTracker::FAnyValidIterator< Mask >::FAnyValidIterator () default
References FORCEINLINE.
Referenced by operator++().
FAnyValidIterator() [2/2]
template<uint32 Mask = AnyFlagMask> FORCEINLINE FInstanceAttributeTracker::FAnyValidIterator< Mask >::FAnyValidIterator (const FInstanceAttributeTracker * InTracker, int32 StartIndex) inline
Definition at line 320 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FInstanceAttributeTracker(), AdvanceUntilAny(), CurrentElement, ElementIndex, ElementMask, ElementOffset, FORCEINLINE, FInstanceAttributeTracker::MasksPerElement, FInstanceAttributeTracker::Num, and Tracker.
Member Function Documentation
AdvanceToNext()
template<uint32 Mask = AnyFlagMask> FORCEINLINE void FInstanceAttributeTracker::FAnyValidIterator< Mask >::AdvanceToNext () inline
Definition at line 353 of file InstanceAttributeTracker.h.
References AdvanceUntilAny(), CurrentElement, FORCEINLINE, and Mask.
Referenced by operator++().
AdvanceUntilAny()
template<uint32 Mask = AnyFlagMask> FORCEINLINE void FInstanceAttributeTracker::FAnyValidIterator< Mask >::AdvanceUntilAny () inline
Definition at line 329 of file InstanceAttributeTracker.h.
References UE::InstanceAttributeTracker::Implementation::FBitManip< ElementType >::CountTrailingZeros(), CurrentElement, FInstanceAttributeTracker::Data, ElementIndex, ElementMask, ElementOffset, FORCEINLINE, FInstanceAttributeTracker::Num, and Tracker.
Referenced by FAnyValidIterator(), and AdvanceToNext().
GetIndex()
template<uint32 Mask = AnyFlagMask> FORCEINLINE int32 FInstanceAttributeTracker::FAnyValidIterator< Mask >::GetIndex () const inline
Definition at line 371 of file InstanceAttributeTracker.h.
References ElementIndex, ElementOffset, FORCEINLINE, and FInstanceAttributeTracker::MasksPerElement.
Referenced by operator bool().
GetMask()
template<uint32 Mask = AnyFlagMask> FORCEINLINE uint32 FInstanceAttributeTracker::FAnyValidIterator< Mask >::GetMask () const inline
Definition at line 380 of file InstanceAttributeTracker.h.
References CurrentElement, and FORCEINLINE.
operator bool()
template<uint32 Mask = AnyFlagMask> FORCEINLINE FInstanceAttributeTracker::FAnyValidIterator< Mask >::operator bool () const inline explicit
Definition at line 366 of file InstanceAttributeTracker.h.
References FORCEINLINE, GetIndex(), FMath::Min, and Tracker.
operator++()
template<uint32 Mask = AnyFlagMask> FORCEINLINE FAnyValidIterator & FInstanceAttributeTracker::FAnyValidIterator< Mask >::operator++ () inline
Definition at line 360 of file InstanceAttributeTracker.h.
References FAnyValidIterator(), AdvanceToNext(), and FORCEINLINE.
TestFlag()
template<uint32 Mask = AnyFlagMask> template<EFlag Flag> FORCEINLINE bool FInstanceAttributeTracker::FAnyValidIterator< Mask >::TestFlag () const inline
Definition at line 386 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FToBit< Flag >::Bit, CurrentElement, and FORCEINLINE.
Field Documentation
CurrentElement
template<uint32 Mask = AnyFlagMask> ElementType FInstanceAttributeTracker::FAnyValidIterator< Mask >::CurrentElement private
Definition at line 393 of file InstanceAttributeTracker.h.
Referenced by FAnyValidIterator(), AdvanceToNext(), AdvanceUntilAny(), GetMask(), and TestFlag().
ElementIndex
template<uint32 Mask = AnyFlagMask> int32 FInstanceAttributeTracker::FAnyValidIterator< Mask >::ElementIndex = 0 private
Definition at line 392 of file InstanceAttributeTracker.h.
Referenced by FAnyValidIterator(), AdvanceUntilAny(), and GetIndex().
ElementMask
template<uint32 Mask = AnyFlagMask> ElementType FInstanceAttributeTracker::FAnyValidIterator< Mask >::ElementMask = FBitManip::FRepMask<Mask, uint32(EFlag::Num)>::Result static constexpr private
Definition at line 395 of file InstanceAttributeTracker.h.
Referenced by FAnyValidIterator(), and AdvanceUntilAny().
ElementOffset
template<uint32 Mask = AnyFlagMask> int32 FInstanceAttributeTracker::FAnyValidIterator< Mask >::ElementOffset = 0 private
Definition at line 394 of file InstanceAttributeTracker.h.
Referenced by FAnyValidIterator(), AdvanceUntilAny(), and GetIndex().
Tracker
template<uint32 Mask = AnyFlagMask> const FInstanceAttributeTracker* FInstanceAttributeTracker::FAnyValidIterator< Mask >::Tracker = nullptr private
Definition at line 391 of file InstanceAttributeTracker.h.
Referenced by FAnyValidIterator(), AdvanceUntilAny(), and operator bool().
The documentation for this class was generated from the following file:
InstanceAttributeTracker.h