Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes > Struct Template Reference
UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
template<typename... ArgTypes>
TEntityTask (FEntityManager *InEntityManager, const TEntityTaskComponents< ComponentTypes... > &InComponents, ArgTypes &&... InArgs)
template<typename... ArgTypes>
TEntityTask (FEntityManager *InEntityManager, const TFilteredEntityTask< ComponentTypes... > &InFilteredTask, ArgTypes &&... InArgs)
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &CompletionGraphEvent)
Public Member Functions inherited from UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >
TEntityTaskBase (FEntityManager *InEntityManager, const TEntityTaskComponents< ComponentTypes... > &InComponents)
ENamedThreads::Type GetDesiredThread () const
TStatId GetStatId () const
void Run (TaskImpl &TaskImplInstance)
Static Public Member Functions
static ESubsequentsMode::Type GetSubsequentsMode ()
Private Attributes
TaskImpl TaskImplInstance
Additional Inherited Members
Protected Types inherited from UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >
using Caller
Static Protected Member Functions inherited from UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >
static void PostTask (void *,...)
static void PreTask (void *,...)
Protected Attributes inherited from UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >
FEntityManager * EntityManager
TFilteredEntityTask< ComponentTypes... > FilteredTask
FEntityAllocationWriteContext WriteContext
Detailed Description
template<typename TaskImpl, typename... ComponentTypes>
struct UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >
Definition at line 1604 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TEntityTask() [1/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename... ArgTypes> UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::TEntityTask (FEntityManager * InEntityManager, const TEntityTaskComponents< ComponentTypes... > & InComponents, ArgTypes &&... InArgs) inline explicit
Definition at line 1607 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >::TEntityTaskBase(), Forward(), and TaskImplInstance.
TEntityTask() [2/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename... ArgTypes> UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::TEntityTask (FEntityManager * InEntityManager, const TFilteredEntityTask< ComponentTypes... > & InFilteredTask, ArgTypes &&... InArgs) inline explicit
Definition at line 1613 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >::TEntityTaskBase(), Forward(), and TaskImplInstance.
Member Function Documentation
DoTask()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & CompletionGraphEvent) inline
Definition at line 1623 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkf, UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >::FilteredTask, UE::MovieScene::TEntityTaskBase< TaskImpl, ComponentTypes... >::Run(), TaskImplInstance, TEXT, and UE_DEBUG_BREAK.
GetSubsequentsMode()
template<typename TaskImpl, typename... ComponentTypes> ESubsequentsMode::Type UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::GetSubsequentsMode () inline static
Definition at line 1618 of file MovieSceneEntitySystemTask.h.
References ESubsequentsMode::TrackSubsequents.
Field Documentation
TaskImplInstance
template<typename TaskImpl, typename... ComponentTypes> TaskImpl UE::MovieScene::TEntityTask< TaskImpl, ComponentTypes >::TaskImplInstance private
Definition at line 1640 of file MovieSceneEntitySystemTask.h.
Referenced by TEntityTask(), TEntityTask(), and DoTask().
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h