Unreal Engine 5.6 C++ API: SNodePanel::SNode::FNodeSlot Class Reference
SNodePanel::SNode::FNodeSlot Class Reference
A slot that support alignment of content and padding and z-order.
#include "SNodePanel.h"
Public Member Functions
FNodeSlot ()
FNodeSlot (ENodeZone::Type InZone)
bool GetAllowScaling () const
FMargin GetPadding () const
UE::Slate::FDeprecateVector2DResult GetSlotOffset () const
UE::Slate::FDeprecateVector2DResult GetSlotSize () const
ENodeZone::Type GetZoneType () const
void SetAllowScaling (TAttribute< bool > InAllowScaling)
void SetPadding (TAttribute< FMargin > InPadding)
void SetSlotOffset (TAttribute< FVector2f > InOffset)
void SetSlotSize (TAttribute< FVector2f > InSize)
Padding SlotOffset2f SlotSize2f SLATE_ATTRIBUTE (bool, AllowScaling) SLATE_SLOT_END_ARGS() void Construct(const FChildren &SlotOwner
Padding SLATE_ATTRIBUTE_DEPRECATED (FVector2D, SlotOffset, 5.6, "Use SlotOffset2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") SLATE_ATTRIBUTE(FVector2f
Padding SlotOffset2f SLATE_ATTRIBUTE_DEPRECATED (FVector2D, SlotSize, 5.6, "UseSlotSize2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") SLATE_ATTRIBUTE(FVector2f
SLATE_SLOT_BEGIN_ARGS_OneMixin (FNodeSlot, TSlotBase< FNodeSlot >, TAlignmentWidgetSlotMixin< FNodeSlot >) SLATE_ATTRIBUTE(FMargin
UE_DEPRECATED (5.6, "This exists as a temporary bridge for deprecation of SlotSize Attribute. Please use the FVector2f version.") void SetSlotOffset(TAttribute< FVector2D > InOffset)
UE_DEPRECATED (5.6, "This exists as a temporary bridge for deprecation of SlotSize Attribute. Please use the FVector2f version.") void SetSlotSize(TAttribute< FVector2D > InSize)
Public Member Functions inherited from TSlotBase< FNodeSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FNodeSlot & Expose (FNodeSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FNodeSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TAlignmentWidgetSlotMixin< FNodeSlot >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Data Fields
Padding SlotOffset2f SlotSize2f FSlotArguments && InArgs
friend SNode
Private Member Functions
UE_DEPRECATED (5.6, "This exists as a temporary bridge for deprecation of SlotSize Attribute.") TAttribute< FVector2D > Offset_Deprecated
UE_DEPRECATED (5.6, "This exists as a temporary bridge for deprecation of SlotSize Attribute.") TAttribute< FVector2D > Size_Deprecated
Private Attributes
TAttribute< bool > AllowScale
TAttribute< FVector2f > Offset
TAttribute< FVector2f > Size
TAttribute< FMargin > SlotPadding
ENodeZone::Type Zone
The child widget contained in this slot.
Additional Inherited Members
Public Types inherited from TSlotBase< FNodeSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< FNodeSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Detailed Description
A slot that support alignment of content and padding and z-order.
Definition at line 321 of file SNodePanel.h.
Constructor & Destructor Documentation
FNodeSlot() [1/2]
SNodePanel::SNode::FNodeSlot::FNodeSlot () inline
Definition at line 326 of file SNodePanel.h.
References FNodeSlot(), and TopLeft.
Referenced by FNodeSlot(), FNodeSlot(), and SLATE_SLOT_BEGIN_ARGS_OneMixin().
FNodeSlot() [2/2]
SNodePanel::SNode::FNodeSlot::FNodeSlot (ENodeZone::Type InZone) inline
Definition at line 330 of file SNodePanel.h.
References FNodeSlot(), TAlignmentWidgetSlotMixin< FNodeSlot >::TAlignmentWidgetSlotMixin(), AllowScale, Offset, SlotPadding, and Zone.
Member Function Documentation
GetAllowScaling()
bool SNodePanel::SNode::FNodeSlot::GetAllowScaling () const inline
Definition at line 413 of file SNodePanel.h.
References AllowScale.
GetPadding()
FMargin SNodePanel::SNode::FNodeSlot::GetPadding () const inline
Definition at line 361 of file SNodePanel.h.
References SlotPadding.
GetSlotOffset()
UE::Slate::FDeprecateVector2DResult SNodePanel::SNode::FNodeSlot::GetSlotOffset () const inline
Definition at line 382 of file SNodePanel.h.
References Offset.
GetSlotSize()
UE::Slate::FDeprecateVector2DResult SNodePanel::SNode::FNodeSlot::GetSlotSize () const inline
Definition at line 403 of file SNodePanel.h.
References Size.
GetZoneType()
ENodeZone::Type SNodePanel::SNode::FNodeSlot::GetZoneType () const inline
Definition at line 351 of file SNodePanel.h.
References GetZoneType(), and Zone.
Referenced by GetZoneType().
SetAllowScaling()
void SNodePanel::SNode::FNodeSlot::SetAllowScaling (TAttribute< bool > InAllowScaling) inline
Definition at line 408 of file SNodePanel.h.
References AllowScale, and MoveTemp().
SetPadding()
void SNodePanel::SNode::FNodeSlot::SetPadding (TAttribute< FMargin > InPadding) inline
Definition at line 356 of file SNodePanel.h.
References MoveTemp(), and SlotPadding.
SetSlotOffset()
void SNodePanel::SNode::FNodeSlot::SetSlotOffset (TAttribute< FVector2f > InOffset) inline
Definition at line 377 of file SNodePanel.h.
References MoveTemp(), and Offset.
Referenced by UE_DEPRECATED().
SetSlotSize()
void SNodePanel::SNode::FNodeSlot::SetSlotSize (TAttribute< FVector2f > InSize) inline
Definition at line 398 of file SNodePanel.h.
References MoveTemp(), and Size.
Referenced by UE_DEPRECATED().
SLATE_ATTRIBUTE()
Padding SlotOffset2f SlotSize2f SNodePanel::SNode::FNodeSlot::SLATE_ATTRIBUTE (bool , AllowScaling) const &
References SLATE_ATTRIBUTE(), and SLATE_SLOT_END_ARGS.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE_DEPRECATED(), and SLATE_ATTRIBUTE_DEPRECATED().
SLATE_ATTRIBUTE_DEPRECATED() [1/2]
Padding SNodePanel::SNode::FNodeSlot::SLATE_ATTRIBUTE_DEPRECATED (FVector2D , SlotOffset , 5. 6, "Use SlotOffset2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.")
References SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE_DEPRECATED().
Referenced by SLATE_ATTRIBUTE_DEPRECATED(), and SLATE_ATTRIBUTE_DEPRECATED().
SLATE_ATTRIBUTE_DEPRECATED() [2/2]
Padding SlotOffset2f SNodePanel::SNode::FNodeSlot::SLATE_ATTRIBUTE_DEPRECATED (FVector2D , SlotSize , 5. 6, "UseSlotSize2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.")
References SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE_DEPRECATED().
SLATE_SLOT_BEGIN_ARGS_OneMixin()
SNodePanel::SNode::FNodeSlot::SLATE_SLOT_BEGIN_ARGS_OneMixin (FNodeSlot , TSlotBase< FNodeSlot > , TAlignmentWidgetSlotMixin< FNodeSlot >)
References FNodeSlot(), TAlignmentWidgetSlotMixin< FNodeSlot >::TAlignmentWidgetSlotMixin(), and SNodePanel::Padding.
UE_DEPRECATED() [1/4]
SNodePanel::SNode::FNodeSlot::UE_DEPRECATED (5. 6, "This exists as a temporary bridge for deprecation of SlotSize Attribute. Please use the FVector2f version.") inline
Definition at line 366 of file SNodePanel.h.
References UE::Slate::CastToVector2f(), MoveTemp(), Offset, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and SetSlotOffset().
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/4]
SNodePanel::SNode::FNodeSlot::UE_DEPRECATED (5. 6, "This exists as a temporary bridge for deprecation of SlotSize Attribute. Please use the FVector2f version.") inline
Definition at line 387 of file SNodePanel.h.
References UE::Slate::CastToVector2f(), MoveTemp(), Offset, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and SetSlotSize().
UE_DEPRECATED() [3/4]
SNodePanel::SNode::FNodeSlot::UE_DEPRECATED (5. 6, "This exists as a temporary bridge for deprecation of SlotSize Attribute.") private
References UE_DEPRECATED().
UE_DEPRECATED() [4/4]
SNodePanel::SNode::FNodeSlot::UE_DEPRECATED (5. 6, "This exists as a temporary bridge for deprecation of SlotSize Attribute.") private
Field Documentation
AllowScale
TAttribute<bool> SNodePanel::SNode::FNodeSlot::AllowScale private
Definition at line 428 of file SNodePanel.h.
Referenced by FNodeSlot(), GetAllowScaling(), SNodePanel::SNode::GetRelativeLayoutScale(), and SetAllowScaling().
InArgs
Padding SlotOffset2f SlotSize2f FSlotArguments&& SNodePanel::SNode::FNodeSlot::InArgs
Definition at line 348 of file SNodePanel.h.
Offset
TAttribute<FVector2f> SNodePanel::SNode::FNodeSlot::Offset private
Definition at line 422 of file SNodePanel.h.
Referenced by FNodeSlot(), GetSlotOffset(), SNodePanel::SNode::OnArrangeChildren(), SetSlotOffset(), UE_DEPRECATED(), and UE_DEPRECATED().
Size
TAttribute<FVector2f> SNodePanel::SNode::FNodeSlot::Size private
Definition at line 423 of file SNodePanel.h.
Referenced by GetSlotSize(), SNodePanel::SNode::OnArrangeChildren(), and SetSlotSize().
SlotPadding
TAttribute<FMargin> SNodePanel::SNode::FNodeSlot::SlotPadding private
Definition at line 421 of file SNodePanel.h.
Referenced by FNodeSlot(), SNodePanel::SNode::ComputeDesiredSize(), GetPadding(), SNodePanel::SNode::OnArrangeChildren(), and SetPadding().
SNode
friend SNodePanel::SNode::FNodeSlot::SNode
Definition at line 324 of file SNodePanel.h.
Zone
ENodeZone::Type SNodePanel::SNode::FNodeSlot::Zone private
The child widget contained in this slot.
Definition at line 420 of file SNodePanel.h.
Referenced by FNodeSlot(), and GetZoneType().
The documentation for this class was generated from the following file:
SNodePanel.h