Unreal Engine 5.6 C++ API: FShaderPipelineCache Class Reference
FShaderPipelineCache Class Reference
FShaderPipelineCache: The FShaderPipelineCache provides the new Pipeline State Object (PSO) logging, serialisation & precompilation mechanism that replaces FShaderCache.
#include "ShaderPipelineCache.h"
Data Structures
struct FPipelineCachePSOContext
class FShaderCachePrecompileContext
Allows handlers of FShaderCacheOpenedDelegate to send state to begin and complete pre-compilation delegates.
Public Types
enum class BatchMode { Background , Fast , Precompile }
enum ELibraryState { Opened , OpenedComponent , Closed }
Public Member Functions
RENDERCORE_API FShaderPipelineCache (EShaderPlatform Platform)
virtual RENDERCORE_API ~FShaderPipelineCache ()
DECLARE_MULTICAST_DELEGATE_FiveParams (FShaderCacheOpenedDelegate, FString const &, EShaderPlatform, uint32, const FGuid &, FShaderCachePrecompileContext &)
Delegate signature for being notified when a pipeline cache is opened.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FShaderCachePreOpenDelegate, FString const &, EShaderPlatform, bool &)
Delegate signature for being notified when we are about to open the pipeline cache.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FShaderPrecompilationCompleteDelegate, uint32, double, const FShaderCachePrecompileContext &)
Delegate signature for being notified that all currently viable PSOs have been precompiled from the cache, how many that was and how long spent precompiling (in sec.)
DECLARE_MULTICAST_DELEGATE_TwoParams (FShaderCacheClosedDelegate, FString const &, EShaderPlatform)
Delegate signature for being notified when a pipeline cache is closed.
DECLARE_MULTICAST_DELEGATE_TwoParams (FShaderPrecompilationBeginDelegate, uint32, const FShaderCachePrecompileContext &)
Delegate signature for being notified when currently viable PSOs have started to be precompiled from the cache, and how many will be precompiled.
RENDERCORE_API TStatId GetStatId () const
return the stat id to use for this tickable
RENDERCORE_API bool IsTickable () const
Pure virtual that must be overloaded by the inheriting class.
RENDERCORE_API bool NeedsRenderingResumedForRenderingThreadTick () const
Used to determine if a rendering thread tickable object must have rendering in a non-suspended state during it's Tick function.
RENDERCORE_API void Tick (float DeltaTime)
Pure virtual that must be overloaded by the inheriting class.
Public Member Functions inherited from FTickableObjectRenderThread
FTickableObjectRenderThread (bool bRegisterImmediately=true, bool bInHighFrequency=false)
Registers this instance with the static array of tickable objects.
virtual ~FTickableObjectRenderThread ()
Removes this instance from the static array of tickable objects.
void Register (bool bIsRenderingThreadObject=false)
Registers the object for ticking.
void Unregister ()
Static Public Member Functions
static RENDERCORE_API void CloseUserPipelineFileCache ()
Closes the existing pipeline cache, allowing it to be reopened with a different file and/or shader platform.
static FShaderCacheClosedDelegate & GetCacheClosedDelegate ()
Gets the event delegate to register to to be notified when a pipeline cache is closed.
static FShaderCacheOpenedDelegate & GetCacheOpenedDelegate ()
Gets the event delegate to register to to be notified when a pipeline cache is opened.
static FShaderCachePreOpenDelegate & GetCachePreOpenDelegate ()
Gets the event delegate to register to to be notified when we are about to open the pipeline cache.
static RENDERCORE_API int32 GetGameVersionForPSOFileCache ()
static FShaderPrecompilationBeginDelegate & GetPrecompilationBeginDelegate ()
Gets the event delegate to register to to be notified when currently viable PSOs have started to be precompiled from the cache.
static FShaderPrecompilationCompleteDelegate & GetPrecompilationCompleteDelegate ()
Gets the event delegate to register to to be notified when all currently viable PSOs have been precompiled from the cache.
static RENDERCORE_API void Initialize (EShaderPlatform Platform)
Initializes the shader pipeline cache for the desired platform, called by the engine.
static RENDERCORE_API bool IsBatchingPaused ()
static RENDERCORE_API bool IsPrecompiling ()
true if pipeline cache(s) are precompiling.
static RENDERCORE_API uint32 NumPrecompilesRemaining ()
Returns the number of pipelines waiting for precompilation of the current PSOFC task.
static RENDERCORE_API bool OpenPipelineFileCache (EShaderPlatform Platform)
Opens the shader pipeline cache file with either the LastOpened setting if available, or the project name otherwise.
static RENDERCORE_API bool OpenUserPipelineFileCache (EShaderPlatform Platform)
Opens the user pipeline cache file with either the LastOpened setting if available, or the project name otherwise.
static RENDERCORE_API void PauseBatching ()
Pauses precompilation.
static RENDERCORE_API void ResumeBatching ()
Resumes precompilation batching.
static RENDERCORE_API bool SavePipelineFileCache (FPipelineFileCacheManager::SaveMode Mode)
Saves the current shader pipeline cache to disk using one of the defined save modes, Fast uses an incremental approach whereas Slow will consolidate all data into the file.
static RENDERCORE_API void SetBatchMode (BatchMode Mode)
Sets the precompilation batching mode.
static RENDERCORE_API bool SetGameUsageMaskWithComparison (uint64 Mask, FPSOMaskComparisonFn InComparisonFnPtr)
Set the current PSO Game Usage Mask and comparsion function .
static RENDERCORE_API void ShaderLibraryStateChanged (ELibraryState State, EShaderPlatform Platform, FString const &Name, int32 ComponentID)
Called by FShaderCodeLibrary to notify us that the shader code library state changed and shader availability will need to be re-evaluated.
static RENDERCORE_API void Shutdown ()
Terminates the shader pipeline cache, called by the engine.
Private Member Functions
RENDERCORE_API int ApplyNewUsageMaskToAllTasks (uint64 Mask)
RENDERCORE_API void BeginNextPrecompileCacheTask ()
RENDERCORE_API void BeginNextPrecompileCacheTaskInternal ()
RENDERCORE_API void ClearPendingPrecompileTaskQueue ()
RENDERCORE_API void EnqueuePendingPrecompileTask (const FString &PSOCacheKey)
RENDERCORE_API FRHIBlendState * GetOrCreateBlendState (const FBlendStateInitializerRHI &Initializer)
RENDERCORE_API FRHIDepthStencilState * GetOrCreateDepthStencilState (const FDepthStencilStateInitializerRHI &Initializer)
RENDERCORE_API FRHIRasterizerState * GetOrCreateRasterizerState (const FRasterizerStateInitializerRHI &Initializer)
class FShaderPipelineCacheTask * GetTask (const FString &Name)
RENDERCORE_API bool OpenPipelineFileCacheInternal (bool bUserCache, const FString &PSOCacheKey, const FString &CacheName, EShaderPlatform Platform)
RENDERCORE_API bool ReadyForAutoSave () const
Static Private Member Functions
static FShaderPipelineCache * Get ()
Private Attributes
std::atomic_bool bHasShaderPipelineTask = false
TMap< FBlendStateInitializerRHI, FRHIBlendState * > BlendStateCache
bool bPaused
TSet< uint32 > CompiledHashes
FString CurrentPrecompilingPSOFCKey
TMap< FDepthStencilStateInitializerRHI, FRHIDepthStencilState * > DepthStencilStateCache
int32 LastAutoSaveNum = 0
double LastAutoSaveTime = 0.0
double LastAutoSaveTimeLogBoundPSO = 0.0
FCriticalSection Mutex
FGraphEventRef NextPrecompileCacheTask
int32 PausedCount
TArray< FString > PendingPrecompilePSOCacheKeys
TMap< FRasterizerStateInitializerRHI, FRHIRasterizerState * > RasterizerStateCache
TMap< FString, TUniquePtr< class FShaderPipelineCacheTask > > ShaderCacheTasks
UE::ShaderUtils::FShaderStableKeyDebugInfoReader ShaderHashToStableKey
Development tool that can describe PSOs in non-Shipping builds.
Static Private Attributes
static RENDERCORE_API uint32 BatchSize
static RENDERCORE_API float BatchTime
static RENDERCORE_API FShaderCacheClosedDelegate OnCachedClosed
static RENDERCORE_API FShaderCacheOpenedDelegate OnCachedOpened
static RENDERCORE_API FShaderCachePreOpenDelegate OnCachePreOpen
static RENDERCORE_API FShaderPrecompilationBeginDelegate OnPrecompilationBegin
static RENDERCORE_API FShaderPrecompilationCompleteDelegate OnPrecompilationComplete
static RENDERCORE_API FShaderPipelineCache * ShaderPipelineCache
static RENDERCORE_API FString UserCacheTaskKey
Friends
class FShaderPipelineCacheTask
Additional Inherited Members
Static Public Attributes inherited from FTickableObjectRenderThread
static RENDERCORE_API FRenderingThreadTickableObjectsArray RenderingThreadHighFrequencyTickableObjects
static RENDERCORE_API FRenderingThreadTickableObjectsArray RenderingThreadTickableObjects
Detailed Description
FShaderPipelineCache: The FShaderPipelineCache provides the new Pipeline State Object (PSO) logging, serialisation & precompilation mechanism that replaces FShaderCache.
Caching Pipeline State Objects and serialising the initialisers to disk allows for precompilation of these states the next time the game is run, which reduces hitching. To achieve this FShaderPipelineCache relies upon FShaderCodeLibrary & "Share Material Shader Code" and the RHI-level backend FPipelineFileCacheManager.
Basic Runtime Usage:
Enable the cache with r.ShaderPipelineCache.Enabled = 1, which allows the pipeline cache to load existing data from disk and precompile it.
Set the default batch size with r.ShaderPipelineCache.BatchSize = X, where X is the maximum number of PSOs to compile in a single batch when precompiling in the default Fast BatchMode.
Set the background batch size with r.ShaderPipelineCache.BackgroundBatchSize = X, where X is the maximum number of PSOs to compile when in the Background BatchMode.
Instrument the game code to call FShaderPipelineCache::SetBatchMode to switch the batch mode between Fast & Background modes.
BatchMode::Fast should be used when a loading screen or movie is being displayed to allow more PSOs to be compiled whereas Background should be used behind interactive menus.
If required call NumPrecompilesRemaining to determine the total number of outstanding PSOs to compile and keep the loading screen or movie visible until complete.
Depending on the game & target platform performance it may also be required to call PauseBatching to suspend precompilation during gameplay and then ResumeBatching when behind a loading screen, menu or movie to restart precompilation.
Other Runtime Options:
In the GGameIni (and thus also GGameUserSettingsIni) the Shader Pipeline Cache uses the [ShaderPipelineCache.CacheFile] section to store some settings.
The LastOpened setting stores the name of the last opened cache file as specified with Open, which if present will be used within FShaderPipelineCache::Initialize to open the existing cache. If not specified this will default to the AppName.
The SortMode settings stores the desired sort mode for the PSOs, which is one of:
Default: Loaded in the order specified in the file.
FirstToLatestUsed: Start with the PSOs with the lowest first-frame used and work toward those with the highest.
MostToLeastUsed: Start with the most often used PSOs working toward the least. Will use "Default" within FShaderPipelineCache::Initialize & OpenPipelineFileCache if nothing is specified.
The GameVersionKey is a read-only integer specified in the GGameIni that specifies the game content version to disambiguate incompatible versions of the game content. By default this is taken from the FEngineVersion changlist.
Logging Usage:
Enable the cache with r.ShaderPipelineCache.Enabled = 1 and also turn on runtime logging with r.ShaderPipelineCache.LogPSO = 1.
Ensure that you have configured the game to open the appropriate cache on startup (see above) and allow the game to play.
PSOs are logged as they are encountered as the Unreal Engine does not provide facility to cook them offline, so this system will only collect PSOs which are actually used to render.
As such you must either manually play through the game to collect logs or automate the process which is beyond the scope of this code.
The data can be saved at any time by calling FShaderPipelineCache::SavePipelineFileCache and this can happen automatically after a given number of PSOs by setting r.ShaderPipelineCache.SaveAfterPSOsLogged = X where X is the desired number of PSOs to log before saving (0 will disable auto-save).
Log files are shader platform specific to reduce overheads.
Notes:
The open cache file can be changed by closing the existing file with ClosePipelineFileCache (which implicitly Fast saves) and then opening a new one with OpenPipelineFileCache.
Different files can be used to minimise PSO compilation by having a file per-scalability bucket (i.e. one file for Low, one for Med, one for High).
When logging if you switch files only new entries from after the switch will be logged, which means you will miss any PSOs that should have been logged prior to switching. This prevents polluting the cache with unexpected entries.
The UnrealEd.MergeShaderPipelineCaches command-let can be used to merge cache files with the same file-version, shader platform and game-version.
File Locations & Packaging:
The writable cache file is always stored in the User Saved directory.
The game can also provide an immutable copy within its Game Content directory which will be used as the initial or seed data.
Having generated logs in development and merged them with UnrealEd.MergeShaderPipelineCaches they should be packaged inside the Gane Content directory for the relevant platform.
Requirements:
FShaderCodeLibrary must be enabled via Project Settings > Packaging > "Share Material Shader Code".
Enabling "Native Shader Libraries" is optional, but strongly preferred for Metal.
Definition at line 78 of file ShaderPipelineCache.h.
Member Enumeration Documentation
BatchMode
enum class FShaderPipelineCache::BatchMode strong
Enumerator
Background
Fast
Precompile
Definition at line 94 of file ShaderPipelineCache.h.
ELibraryState
enum FShaderPipelineCache::ELibraryState
Enumerator
Opened
OpenedComponent
Closed
Definition at line 147 of file ShaderPipelineCache.h.
Constructor & Destructor Documentation
FShaderPipelineCache()
RENDERCORE_API FShaderPipelineCache::FShaderPipelineCache (EShaderPlatform Platform)
References Platform.
Referenced by Get().
~FShaderPipelineCache()
virtual RENDERCORE_API FShaderPipelineCache::~FShaderPipelineCache () virtual
Member Function Documentation
ApplyNewUsageMaskToAllTasks()
RENDERCORE_API int FShaderPipelineCache::ApplyNewUsageMaskToAllTasks (uint64 Mask) private
References Mask.
BeginNextPrecompileCacheTask()
RENDERCORE_API void FShaderPipelineCache::BeginNextPrecompileCacheTask () private
BeginNextPrecompileCacheTaskInternal()
RENDERCORE_API void FShaderPipelineCache::BeginNextPrecompileCacheTaskInternal () private
ClearPendingPrecompileTaskQueue()
RENDERCORE_API void FShaderPipelineCache::ClearPendingPrecompileTaskQueue () private
CloseUserPipelineFileCache()
RENDERCORE_API void FShaderPipelineCache::CloseUserPipelineFileCache () static
Closes the existing pipeline cache, allowing it to be reopened with a different file and/or shader platform.
Will implicitly invoke a Fast Save.
DECLARE_MULTICAST_DELEGATE_FiveParams()
FShaderPipelineCache::DECLARE_MULTICAST_DELEGATE_FiveParams (FShaderCacheOpenedDelegate , FString const & , EShaderPlatform , uint32 , const FGuid & , FShaderCachePrecompileContext &)
Delegate signature for being notified when a pipeline cache is opened.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
FShaderPipelineCache::DECLARE_MULTICAST_DELEGATE_ThreeParams (FShaderCachePreOpenDelegate , FString const & , EShaderPlatform , bool &)
Delegate signature for being notified when we are about to open the pipeline cache.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
FShaderPipelineCache::DECLARE_MULTICAST_DELEGATE_ThreeParams (FShaderPrecompilationCompleteDelegate , uint32 , double , const FShaderCachePrecompileContext &)
Delegate signature for being notified that all currently viable PSOs have been precompiled from the cache, how many that was and how long spent precompiling (in sec.)
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/2]
FShaderPipelineCache::DECLARE_MULTICAST_DELEGATE_TwoParams (FShaderCacheClosedDelegate , FString const & , EShaderPlatform)
Delegate signature for being notified when a pipeline cache is closed.
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/2]
FShaderPipelineCache::DECLARE_MULTICAST_DELEGATE_TwoParams (FShaderPrecompilationBeginDelegate , uint32 , const FShaderCachePrecompileContext &)
Delegate signature for being notified when currently viable PSOs have started to be precompiled from the cache, and how many will be precompiled.
EnqueuePendingPrecompileTask()
RENDERCORE_API void FShaderPipelineCache::EnqueuePendingPrecompileTask (const FString & PSOCacheKey) private
Get()
FShaderPipelineCache * FShaderPipelineCache::Get () inline static private
Definition at line 222 of file ShaderPipelineCache.h.
References FShaderPipelineCache(), and ShaderPipelineCache.
Referenced by GetTask().
GetCacheClosedDelegate()
FShaderCacheClosedDelegate & FShaderPipelineCache::GetCacheClosedDelegate () inline static
Gets the event delegate to register to to be notified when a pipeline cache is closed.
Definition at line 199 of file ShaderPipelineCache.h.
References OnCachedClosed.
GetCacheOpenedDelegate()
FShaderCacheOpenedDelegate & FShaderPipelineCache::GetCacheOpenedDelegate () inline static
Gets the event delegate to register to to be notified when a pipeline cache is opened.
Definition at line 189 of file ShaderPipelineCache.h.
References OnCachedOpened.
GetCachePreOpenDelegate()
FShaderCachePreOpenDelegate & FShaderPipelineCache::GetCachePreOpenDelegate () inline static
Gets the event delegate to register to to be notified when we are about to open the pipeline cache.
Definition at line 179 of file ShaderPipelineCache.h.
References OnCachePreOpen.
GetGameVersionForPSOFileCache()
RENDERCORE_API int32 FShaderPipelineCache::GetGameVersionForPSOFileCache () static
GetOrCreateBlendState()
RENDERCORE_API FRHIBlendState * FShaderPipelineCache::GetOrCreateBlendState (const FBlendStateInitializerRHI & Initializer) private
GetOrCreateDepthStencilState()
RENDERCORE_API FRHIDepthStencilState * FShaderPipelineCache::GetOrCreateDepthStencilState (const FDepthStencilStateInitializerRHI & Initializer) private
GetOrCreateRasterizerState()
RENDERCORE_API FRHIRasterizerState * FShaderPipelineCache::GetOrCreateRasterizerState (const FRasterizerStateInitializerRHI & Initializer) private
GetPrecompilationBeginDelegate()
FShaderPrecompilationBeginDelegate & FShaderPipelineCache::GetPrecompilationBeginDelegate () inline static
Gets the event delegate to register to to be notified when currently viable PSOs have started to be precompiled from the cache.
Definition at line 214 of file ShaderPipelineCache.h.
References OnPrecompilationBegin.
GetPrecompilationCompleteDelegate()
FShaderPrecompilationCompleteDelegate & FShaderPipelineCache::GetPrecompilationCompleteDelegate () inline static
Gets the event delegate to register to to be notified when all currently viable PSOs have been precompiled from the cache.
Definition at line 219 of file ShaderPipelineCache.h.
References OnPrecompilationComplete.
GetStatId()
RENDERCORE_API TStatId FShaderPipelineCache::GetStatId () const virtual
return the stat id to use for this tickable
Implements FTickableObjectRenderThread.
GetTask()
class FShaderPipelineCacheTask * FShaderPipelineCache::GetTask (const FString & Name) inline private
Definition at line 264 of file ShaderPipelineCache.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), FShaderPipelineCacheTask, Get(), Name, and ShaderCacheTasks.
Initialize()
RENDERCORE_API void FShaderPipelineCache::Initialize (EShaderPlatform Platform) static
Initializes the shader pipeline cache for the desired platform, called by the engine.
The shader platform is used only to load the initial pipeline cache and can be changed by closing & reopening the cache if necessary.
References Platform.
IsBatchingPaused()
RENDERCORE_API bool FShaderPipelineCache::IsBatchingPaused () static
IsPrecompiling()
RENDERCORE_API bool FShaderPipelineCache::IsPrecompiling () static
true if pipeline cache(s) are precompiling.
IsTickable()
RENDERCORE_API bool FShaderPipelineCache::IsTickable () const virtual
Pure virtual that must be overloaded by the inheriting class.
It is used to determine whether an object is ready to be ticked. This is required for example for all UObject derived classes as they might be loaded async and therefore won't be ready immediately.
Returns
true if class is ready to be ticked, false otherwise.
Implements FTickableObjectRenderThread.
NeedsRenderingResumedForRenderingThreadTick()
RENDERCORE_API bool FShaderPipelineCache::NeedsRenderingResumedForRenderingThreadTick () const virtual
Used to determine if a rendering thread tickable object must have rendering in a non-suspended state during it's Tick function.
Returns
true if the RHIResumeRendering should be called before tick if rendering has been suspended
Reimplemented from FTickableObjectRenderThread.
NumPrecompilesRemaining()
RENDERCORE_API uint32 FShaderPipelineCache::NumPrecompilesRemaining () static
Returns the number of pipelines waiting for precompilation of the current PSOFC task.
if there are multiple PSOFCs pending this will return a minimum value of 1. It may increase as subsequent caches are processed.
OpenPipelineFileCache()
RENDERCORE_API bool FShaderPipelineCache::OpenPipelineFileCache (EShaderPlatform Platform) static
Opens the shader pipeline cache file with either the LastOpened setting if available, or the project name otherwise.
References Platform.
OpenPipelineFileCacheInternal()
RENDERCORE_API bool FShaderPipelineCache::OpenPipelineFileCacheInternal (bool bUserCache, const FString & PSOCacheKey, const FString & CacheName, EShaderPlatform Platform) private
References Platform.
OpenUserPipelineFileCache()
RENDERCORE_API bool FShaderPipelineCache::OpenUserPipelineFileCache (EShaderPlatform Platform) static
Opens the user pipeline cache file with either the LastOpened setting if available, or the project name otherwise.
References Platform.
PauseBatching()
RENDERCORE_API void FShaderPipelineCache::PauseBatching () static
Pauses precompilation.
ReadyForAutoSave()
RENDERCORE_API bool FShaderPipelineCache::ReadyForAutoSave () const private
ResumeBatching()
RENDERCORE_API void FShaderPipelineCache::ResumeBatching () static
Resumes precompilation batching.
SavePipelineFileCache()
RENDERCORE_API bool FShaderPipelineCache::SavePipelineFileCache (FPipelineFileCacheManager::SaveMode Mode) static
Saves the current shader pipeline cache to disk using one of the defined save modes, Fast uses an incremental approach whereas Slow will consolidate all data into the file.
SetBatchMode()
RENDERCORE_API void FShaderPipelineCache::SetBatchMode (BatchMode Mode) static
Sets the precompilation batching mode.
SetGameUsageMaskWithComparison()
RENDERCORE_API bool FShaderPipelineCache::SetGameUsageMaskWithComparison (uint64 Mask, FPSOMaskComparisonFn InComparisonFnPtr) static
Set the current PSO Game Usage Mask and comparsion function .
Returns true if this mask is different from the old mask or false if not or the cache system is disabled or if the mask feature is disabled Any new PSO's found will be logged with this value or existing PSO should have their masks updated. See FPipelineFileCacheManager for more details.
References Mask.
ShaderLibraryStateChanged()
RENDERCORE_API void FShaderPipelineCache::ShaderLibraryStateChanged (ELibraryState State, EShaderPlatform Platform, FString const & Name, int32 ComponentID) static
Called by FShaderCodeLibrary to notify us that the shader code library state changed and shader availability will need to be re-evaluated.
References Name, Platform, and State.
Shutdown()
RENDERCORE_API void FShaderPipelineCache::Shutdown () static
Terminates the shader pipeline cache, called by the engine.
Tick()
RENDERCORE_API void FShaderPipelineCache::Tick (float DeltaTime) virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called from within LevelTick.cpp after ticking all actors or from the rendering thread (depending on bIsRenderingThreadObject)
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectRenderThread.
References DeltaTime.
Friends And Related Symbol Documentation
FShaderPipelineCacheTask
friend class FShaderPipelineCacheTask friend
Definition at line 81 of file ShaderPipelineCache.h.
References FShaderPipelineCacheTask.
Referenced by FShaderPipelineCacheTask, and GetTask().
Field Documentation
BatchSize
RENDERCORE_API uint32 FShaderPipelineCache::BatchSize static private
Definition at line 240 of file ShaderPipelineCache.h.
BatchTime
RENDERCORE_API float FShaderPipelineCache::BatchTime static private
Definition at line 241 of file ShaderPipelineCache.h.
bHasShaderPipelineTask
std::atomic_bool FShaderPipelineCache::bHasShaderPipelineTask = false private
Definition at line 276 of file ShaderPipelineCache.h.
BlendStateCache
TMap<FBlendStateInitializerRHI, FRHIBlendState*> FShaderPipelineCache::BlendStateCache private
Definition at line 287 of file ShaderPipelineCache.h.
bPaused
bool FShaderPipelineCache::bPaused private
Definition at line 242 of file ShaderPipelineCache.h.
CompiledHashes
TSet<uint32> FShaderPipelineCache::CompiledHashes private
Definition at line 247 of file ShaderPipelineCache.h.
CurrentPrecompilingPSOFCKey
FString FShaderPipelineCache::CurrentPrecompilingPSOFCKey private
Definition at line 273 of file ShaderPipelineCache.h.
DepthStencilStateCache
TMap<FDepthStencilStateInitializerRHI, FRHIDepthStencilState*> FShaderPipelineCache::DepthStencilStateCache private
Definition at line 289 of file ShaderPipelineCache.h.
LastAutoSaveNum
int32 FShaderPipelineCache::LastAutoSaveNum = 0 private
Definition at line 246 of file ShaderPipelineCache.h.
LastAutoSaveTime
double FShaderPipelineCache::LastAutoSaveTime = 0.0 private
Definition at line 244 of file ShaderPipelineCache.h.
LastAutoSaveTimeLogBoundPSO
double FShaderPipelineCache::LastAutoSaveTimeLogBoundPSO = 0.0 private
Definition at line 245 of file ShaderPipelineCache.h.
Mutex
FCriticalSection FShaderPipelineCache::Mutex mutable private
Definition at line 278 of file ShaderPipelineCache.h.
NextPrecompileCacheTask
FGraphEventRef FShaderPipelineCache::NextPrecompileCacheTask private
Definition at line 279 of file ShaderPipelineCache.h.
OnCachedClosed
RENDERCORE_API FShaderCacheClosedDelegate FShaderPipelineCache::OnCachedClosed static private
Definition at line 283 of file ShaderPipelineCache.h.
Referenced by GetCacheClosedDelegate().
OnCachedOpened
RENDERCORE_API FShaderCacheOpenedDelegate FShaderPipelineCache::OnCachedOpened static private
Definition at line 282 of file ShaderPipelineCache.h.
Referenced by GetCacheOpenedDelegate().
OnCachePreOpen
RENDERCORE_API FShaderCachePreOpenDelegate FShaderPipelineCache::OnCachePreOpen static private
Definition at line 281 of file ShaderPipelineCache.h.
Referenced by GetCachePreOpenDelegate().
OnPrecompilationBegin
RENDERCORE_API FShaderPrecompilationBeginDelegate FShaderPipelineCache::OnPrecompilationBegin static private
Definition at line 284 of file ShaderPipelineCache.h.
Referenced by GetPrecompilationBeginDelegate().
OnPrecompilationComplete
RENDERCORE_API FShaderPrecompilationCompleteDelegate FShaderPipelineCache::OnPrecompilationComplete static private
Definition at line 285 of file ShaderPipelineCache.h.
Referenced by GetPrecompilationCompleteDelegate().
PausedCount
int32 FShaderPipelineCache::PausedCount private
Definition at line 243 of file ShaderPipelineCache.h.
PendingPrecompilePSOCacheKeys
TArray<FString> FShaderPipelineCache::PendingPrecompilePSOCacheKeys private
Definition at line 270 of file ShaderPipelineCache.h.
RasterizerStateCache
TMap<FRasterizerStateInitializerRHI, FRHIRasterizerState*> FShaderPipelineCache::RasterizerStateCache private
Definition at line 288 of file ShaderPipelineCache.h.
ShaderCacheTasks
TMap<FString, TUniquePtr<class FShaderPipelineCacheTask> > FShaderPipelineCache::ShaderCacheTasks private
Definition at line 262 of file ShaderPipelineCache.h.
Referenced by GetTask().
ShaderHashToStableKey
UE::ShaderUtils::FShaderStableKeyDebugInfoReader FShaderPipelineCache::ShaderHashToStableKey private
Development tool that can describe PSOs in non-Shipping builds.
Definition at line 250 of file ShaderPipelineCache.h.
ShaderPipelineCache
RENDERCORE_API FShaderPipelineCache* FShaderPipelineCache::ShaderPipelineCache static private
Definition at line 239 of file ShaderPipelineCache.h.
Referenced by Get().
UserCacheTaskKey
RENDERCORE_API FString FShaderPipelineCache::UserCacheTaskKey static private
Definition at line 252 of file ShaderPipelineCache.h.
The documentation for this class was generated from the following file:
ShaderPipelineCache.h