Unreal Engine 5.6 C++ API: SCurveEditorPanel Class Reference
SCurveEditorPanel Class Reference
Curve editor widget that reflects the state of an FCurveEditor.
#include "SCurveEditorPanel.h"
Private Types
enum class ETangentModeComboState : uint8 {
NoSelection , Constant , Linear , CubicAuto ,
CubicSmartAuto , CubicUser , CubicBreak , Mixed
}
Private Member Functions
~SCurveEditorPanel ()
void AddPostInfinityToMenu (FMenuBuilder &InMenuBuilder)
void AddPreInfinityToMenu (FMenuBuilder &InMenuBuilder)
void AddView (TSharedRef< SCurveEditorView > ViewToAdd)
void BindCommands ()
Bind command mappings for this widget.
void BuildToolbar (FToolBarBuilder &InToolBarBuilder, TSharedPtr< FExtender > InBaseExtender)
Adds all base curve editor UI elements to ToolbarBuilder.
bool CanSetKeyInterpolation () const
Check whether or not we can set a key interpolation on the current selection.
bool CanToggleWeightedTangents () const
Check whether we can toggle weighted tangents on the current selection.
TSharedPtr< FExtender > CombineEditorExtensions () const
bool CompareCommonInterpolationMode (ERichCurveInterpMode InterpMode) const
Compare all the currently selected keys' interp modes against the specified interp mode.
bool CompareCommonPostExtrapolationMode (ERichCurveExtrapolation PostExtrapolationMode) const
Compare all the visible curves' post-extrapolation modes against the specified extrapolation mode.
bool CompareCommonPreExtrapolationMode (ERichCurveExtrapolation PreExtrapolationMode) const
Compare all the visible curves' pre-extrapolation modes against the specified extrapolation mode.
bool CompareCommonTangentMode (ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode) const
Compare all the currently selected keys' tangent modes against the specified tangent mode.
bool CompareCommonTangentWeightMode (ERichCurveInterpMode InterpMode, ERichCurveTangentWeightMode TangentWeightMode) const
Compare all the currently selected keys' tangent modes against the specified tangent mode.
bool CompareViewMode (const ECurveEditorViewID InViewMode) const
Compare if our current view mode matches the specified one.
void Construct (const FArguments &InArgs, TSharedRef< FCurveEditor > InCurveEditor)
Construct a new curve editor panel widget.
TSharedPtr< SCurveEditorView > CreateViewOfType (FCurveModelID CurveModelID, ECurveEditorViewID ViewTypeID, bool bPinned)
Create a new view for a model of the specified type, and add the curve to the view.
ETangentModeComboState DetermineTangentMode () const
void EnablePendingFocusOnHovering (const bool InEnabled)
Enable/disable pending focus.
void FilterClassChanged ()
TMultiMap< FCurveModelID, TSharedRef< SCurveEditorView > >::TConstKeyIterator FindViews (TRetainedRef< FCurveModelID > InCurveID)
Find all the views that the specified curve is being displayed on.
float GetColumnFillCoefficient (int32 ColumnIndex) const
TSharedPtr< FUICommandList > GetCommands () const
Access the combined command list for this curve editor and panel widget.
FText GetCurrentToolDescription () const
FSlateIcon GetCurrentToolIcon () const
FText GetCurrentToolLabel () const
TSharedPtr< FCurveEditor > GetCurveEditor () const
Get a reference to the curve editor this panel represents.
FSlateIcon GetCurveExtrapolationPostIcon () const
FSlateIcon GetCurveExtrapolationPreIcon () const
TSharedPtr< class SCurveEditorFilterPanel > GetFilterPanel () const
Access the filter panel.
FLinearColor GetGridLineTint () const
Get the grid line tint to be used for views on panel.
TSharedPtr< class SCurveKeyDetailPanel > GetKeyDetailsView () const
Access the details view used for editing selected keys.
const FGeometry & GetScrollPanelGeometry () const
Access the cached geometry of the outer scroll panel that contains this panel's views.
EVisibility GetSplitterVisibility () const
Get the visibility for the value splitter control.
FSlateIcon GetTangentModeIcon () const
FText GetTangentModeLabel () const
FText GetTangentModeTooltip () const
FText GetTimeSnapMenuTooltip () const
TSharedPtr< FExtender > GetToolbarExtender ()
This returns an extender which is pre-configured with the standard set of Toolbar Icons.
TSharedPtr< class SCurveEditorToolProperties > GetToolPropertiesPanel () const
Access the tool properties panel.
const FGeometry & GetViewContainerGeometry () const
Access the cached geometry of container housing all this panel's views.
ECurveEditorViewID GetViewMode () const
Get the last set View Mode for this UI.
TArrayView< const TSharedPtr< SCurveEditorView > > GetViews () const
Get all the views stored in this panel.
bool IsInlineEditPanelEditable () const
bool IsTangentModeComboEnabled () const
TSharedRef< SWidget > MakeAxisSnapMenu ()
TSharedRef< SWidget > MakeCurveEditorCurveViewOptionsMenu (TSharedPtr< FExtender > InExtender)
Creates the drop-down list you see when changing Curve View options.
TSharedRef< SWidget > MakeCurvesMenu (TSharedPtr< FExtender > InExtender)
Creates the drop-down for changing curves on a whole.
TSharedRef< SWidget > MakeFlipCurveMenu (FCurveEditor::ECurveFlipDirection Direction)
TSharedRef< SWidget > MakeGridSpacingMenu ()
TSharedRef< SWidget > MakeTangentModeMenu ()
TSharedRef< SWidget > MakeTimeSnapMenu ()
TSharedRef< SWidget > MakeToolsComboMenu (TSharedPtr< FExtender > InExtender)
void OnColumnFillCoefficientChanged (float FillCoefficient, int32 ColumnIndex)
Called when a column fill percentage is changed by a splitter slot.
void OnCurveEditorToolChanged (FCurveEditorToolID InToolId)
Reconstructs the properties widget on tool switch.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
FSimpleMulticastDelegate & OnPostRebuildCurveViews ()
Broadcasts after the curve views have been rebuilt (by RebuildCurveViews).
void OnSplitterFinishedResizing ()
void PostUndo ()
Undo occurred, invalidate or update internal structures.
void RebuildCurveViews ()
Rebuild the Curve Views layout to match the currently specified View Mode.
void RemoveCurveFromViews (FCurveModelID InCurveID)
Remove the specified curve from all views it is currently displayed on.
void RemoveView (TSharedRef< SCurveEditorView > ViewToRemove)
void ResetMinMaxes ()
Reset Stored Min/Max's.
void ScrollBy (float Amount)
Scroll this panel's view scroll box vertically by the specified amount.
void SetAxisSnapping (ECurveEditorSnapAxis)
Sets the axis snapping to the specified value.
void SetCurveAttributes (FCurveAttributes CurveAttributes, FText Description)
Assign new curve attributes to all visible curves.
void SetKeyAttributes (FKeyAttributes KeyAttributes, FText Description)
Assign new attributes to the currently selected keys.
void SetViewMode (const ECurveEditorViewID NewViewMode)
Sets the View Mode for the UI to the specified mode.
EVisibility ShouldInstructionOverlayBeVisible () const
void ShowCurveFilterUI (TSubclassOf< UCurveEditorFilterBase > FilterClass)
Creates the Curve Editor Filter UI and pre-populates it with the specified class.
TabManager SLATE_ARGUMENT (TSharedPtr< ITimeSliderController >, ExternalTimeSliderController) SLATE_ATTRIBUTE(FText
Optional Time Slider Controller which allows us to synchronize with an externally controlled Time Slider.
SLATE_ATTRIBUTE (FLinearColor, GridLineTint) SLATE_ARGUMENT(TSharedPtr< FTabManager >
Color to draw grid lines.
SLATE_BEGIN_ARGS (SCurveEditorPanel)
TabManager DisabledTimeSnapTooltip MinimumViewPanelHeight SLATE_END_ARGS () SCurveEditorPanel()
TabManager DisabledTimeSnapTooltip SLATE_NAMED_SLOT (FArguments, TreeContent) SLATE_ARGUMENT(float
Widget slot for the tree content.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
void ToggleWeightedTangents ()
Toggle weighted tangents on the current selection.
void UpdateAxisSnapping ()
Update the axis snapping based on the settings.
void UpdateCommonCurveInfo ()
void UpdateEditBox ()
void UpdateTime ()
Private Attributes
bool bNeedsRefresh
Whether to explicitly refresh the views for this panel.
bool bSelectionSupportsWeightedTangents
True if the current selection supports weighted tangents, false otherwise.
uint32 CachedActiveCurvesSerialNumber
Serial number cached from FCurveEditor::GetActiveCurvesSerialNumber() on tick.
FCurveAttributes CachedCommonCurveAttributes
Cached curve attributes that are common to all visible curves.
FKeyAttributes CachedCommonKeyAttributes
Cached key attributes that are common to all selected keys.
uint32 CachedSelectionSerialNumber
Cached serial number from the curve editor selection.
FGeometry CachedViewGeometry
A copy of the View Geometry used to represent the View portion of the Curve Editor.
float ColumnFillCoefficients [2]
The fill coefficients of each column in the grid.
TSharedPtr< FUICommandList > CommandList
Command list for widget specific command bindings.
TSharedPtr< FCurveEditor > CurveEditor
The curve editor pointer.
TMap< FCurveModelID, TSharedPtr< SWidget > > CurveToEditUI
Map of edit UI widgets for each curve in the current selection set.
TMultiMap< FCurveModelID, TSharedRef< SCurveEditorView > > CurveViews
Map from curve model ID to the views that it is on.
TSharedPtr< SCurveEditorViewContainer > CurveViewsContainer
The container for all our vertically laid out curve views.
ECurveEditorViewID DefaultViewID
The last set View Mode for this UI.
TAttribute< FText > DisabledTimeSnapTooltipAttribute
Attribute used for retrieving the tooltip for when the Time Snap control is disabled.
TOptional< FCurveEditorDelayedDrag > DragOperation
(Optional) the current drag operation
TUniquePtr< FCurveEditorEditObjectContainer > EditObjects
Container of objects that are being used to edit keys on the curve editor.
TSet< TSharedRef< SCurveEditorView > > ExternalViews
Set of externally added views.
TSharedPtr< SCurveEditorFilterPanel > FilterPanel
TMultiMap< ECurveEditorViewID, TSharedRef< SCurveEditorView > > FreeViewsByType
TAttribute< FLinearColor > GridLineTintAttribute
Attribute used for retrieving the desired grid line color.
TSharedPtr< SCurveKeyDetailPanel > KeyDetailsView
Edit panel.
double LastOutputMax = DBL_MIN
double LastOutputMin = DBL_MAX
Last Output Min and Max values for the views.
FSimpleDelegate OnFilterClassChanged
Delegate for when the chosen filter class has changed.
FSimpleMulticastDelegate OnPostRebuildCurveViewsDelegate
Broadcasts after the curve views have been rebuilt (by RebuildCurveViews).
FPendingWidgetFocus PendingFocus
Pending focus handler.
TSharedPtr< SScrollBox > ScrollBox
The scrool box that all curve views live inside.
TUniquePtr< UE::CurveEditor::FPromotedFilterCommandBinder > ToolbarPromotedFilterBinder
Binds commands from FPromotedFilterContainer so the filters surfaced from SCurveEditorFilterPanel show up in the toolbar.
TSharedPtr< SCurveEditorToolProperties > ToolPropertiesPanel
Tool options panel.
TSharedPtr< class SSplitter > TreeViewSplitter
TWeakPtr< FTabManager > WeakTabManager
Additional Inherited Members
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Curve editor widget that reflects the state of an FCurveEditor.
Definition at line 58 of file SCurveEditorPanel.h.
Member Enumeration Documentation
ETangentModeComboState
enum class SCurveEditorPanel::ETangentModeComboState : uint8 strong private
Enumerator
NoSelection
Constant
Linear
CubicAuto
CubicSmartAuto
CubicUser
CubicBreak
Mixed
Definition at line 233 of file SCurveEditorPanel.h.
Constructor & Destructor Documentation
~SCurveEditorPanel()
SCurveEditorPanel::~SCurveEditorPanel () private
Member Function Documentation
AddPostInfinityToMenu()
void SCurveEditorPanel::AddPostInfinityToMenu (FMenuBuilder & InMenuBuilder) private
AddPreInfinityToMenu()
void SCurveEditorPanel::AddPreInfinityToMenu (FMenuBuilder & InMenuBuilder) private
AddView()
void SCurveEditorPanel::AddView (TSharedRef< SCurveEditorView > ViewToAdd) private
BindCommands()
void SCurveEditorPanel::BindCommands () private
Bind command mappings for this widget.
BuildToolbar()
void SCurveEditorPanel::BuildToolbar (FToolBarBuilder & InToolBarBuilder, TSharedPtr< FExtender > InBaseExtender) private
Adds all base curve editor UI elements to ToolbarBuilder.
CanSetKeyInterpolation()
bool SCurveEditorPanel::CanSetKeyInterpolation () const private
Check whether or not we can set a key interpolation on the current selection.
If no keys are selected, you can't set an interpolation!
CanToggleWeightedTangents()
bool SCurveEditorPanel::CanToggleWeightedTangents () const private
Check whether we can toggle weighted tangents on the current selection.
CombineEditorExtensions()
TSharedPtr< FExtender > SCurveEditorPanel::CombineEditorExtensions () const private
Returns
Extender combining all ICurveEditorModule::GetAllToolBarMenuExtenders and the owning FCurveEditor's ICurveEditorExtensions.
CompareCommonInterpolationMode()
bool SCurveEditorPanel::CompareCommonInterpolationMode (ERichCurveInterpMode InterpMode) const inline private
Compare all the currently selected keys' interp modes against the specified interp mode.
Definition at line 292 of file SCurveEditorPanel.h.
References CachedCommonKeyAttributes.
Referenced by CompareCommonTangentMode(), and CompareCommonTangentWeightMode().
CompareCommonPostExtrapolationMode()
bool SCurveEditorPanel::CompareCommonPostExtrapolationMode (ERichCurveExtrapolation PostExtrapolationMode) const inline private
Compare all the visible curves' post-extrapolation modes against the specified extrapolation mode.
Definition at line 316 of file SCurveEditorPanel.h.
References CachedCommonCurveAttributes.
CompareCommonPreExtrapolationMode()
bool SCurveEditorPanel::CompareCommonPreExtrapolationMode (ERichCurveExtrapolation PreExtrapolationMode) const inline private
Compare all the visible curves' pre-extrapolation modes against the specified extrapolation mode.
Definition at line 310 of file SCurveEditorPanel.h.
References CachedCommonCurveAttributes.
CompareCommonTangentMode()
bool SCurveEditorPanel::CompareCommonTangentMode (ERichCurveInterpMode InterpMode, ERichCurveTangentMode TangentMode) const inline private
Compare all the currently selected keys' tangent modes against the specified tangent mode.
Definition at line 298 of file SCurveEditorPanel.h.
References CachedCommonKeyAttributes, and CompareCommonInterpolationMode().
CompareCommonTangentWeightMode()
bool SCurveEditorPanel::CompareCommonTangentWeightMode (ERichCurveInterpMode InterpMode, ERichCurveTangentWeightMode TangentWeightMode) const inline private
Compare all the currently selected keys' tangent modes against the specified tangent mode.
Definition at line 304 of file SCurveEditorPanel.h.
References CachedCommonKeyAttributes, and CompareCommonInterpolationMode().
CompareViewMode()
bool SCurveEditorPanel::CompareViewMode (const ECurveEditorViewID InViewMode) const private
Compare if our current view mode matches the specified one.
Utility function for the UI.
Construct()
void SCurveEditorPanel::Construct (const FArguments & InArgs, TSharedRef< FCurveEditor > InCurveEditor) private
Construct a new curve editor panel widget.
References Construct().
Referenced by Construct().
CreateViewOfType()
TSharedPtr< SCurveEditorView > SCurveEditorPanel::CreateViewOfType (FCurveModelID CurveModelID, ECurveEditorViewID ViewTypeID, bool bPinned) private
Create a new view for a model of the specified type, and add the curve to the view.
Parameters
CurveModelID The ID of the curve we're creating a view for
ViewTypeID The ID of the view we'd like to create
bPinned Whether the view should be pinned or not
Returns
A new view or nullptr if one could not be created
DetermineTangentMode()
ETangentModeComboState SCurveEditorPanel::DetermineTangentMode () const private
EnablePendingFocusOnHovering()
void SCurveEditorPanel::EnablePendingFocusOnHovering (const bool InEnabled) private
Enable/disable pending focus.
FilterClassChanged()
void SCurveEditorPanel::FilterClassChanged () private
FindViews()
TMultiMap< FCurveModelID, TSharedRef< SCurveEditorView > >::TConstKeyIterator SCurveEditorPanel::FindViews (TRetainedRef< FCurveModelID > InCurveID) inline private
Find all the views that the specified curve is being displayed on.
Note
: Returns an in-place iterator to this curve's view mapping. Adding or removing curves from views will invalidate this iterator.
Parameters
InCurveID The identifier of the curve to find views for
Returns
An iterator to all the views that this cuvrve is displayed within.
Definition at line 157 of file SCurveEditorPanel.h.
References CurveViews, and TRetainedRef< T >::Get().
GetColumnFillCoefficient()
float SCurveEditorPanel::GetColumnFillCoefficient (int32 ColumnIndex) const inline private
Definition at line 342 of file SCurveEditorPanel.h.
References ColumnFillCoefficients, and ensure.
GetCommands()
TSharedPtr< FUICommandList > SCurveEditorPanel::GetCommands () const inline private
Access the combined command list for this curve editor and panel widget.
Definition at line 96 of file SCurveEditorPanel.h.
References CommandList, and GetCommands().
Referenced by GetCommands().
GetCurrentToolDescription()
FText SCurveEditorPanel::GetCurrentToolDescription () const private
GetCurrentToolIcon()
FSlateIcon SCurveEditorPanel::GetCurrentToolIcon () const private
GetCurrentToolLabel()
FText SCurveEditorPanel::GetCurrentToolLabel () const private
GetCurveEditor()
TSharedPtr< FCurveEditor > SCurveEditorPanel::GetCurveEditor () const inline private
Get a reference to the curve editor this panel represents.
Definition at line 340 of file SCurveEditorPanel.h.
GetCurveExtrapolationPostIcon()
FSlateIcon SCurveEditorPanel::GetCurveExtrapolationPostIcon () const private
GetCurveExtrapolationPreIcon()
FSlateIcon SCurveEditorPanel::GetCurveExtrapolationPreIcon () const private
GetFilterPanel()
TSharedPtr< class SCurveEditorFilterPanel > SCurveEditorPanel::GetFilterPanel () const inline private
Access the filter panel.
Definition at line 112 of file SCurveEditorPanel.h.
References FilterPanel.
GetGridLineTint()
FLinearColor SCurveEditorPanel::GetGridLineTint () const inline private
Get the grid line tint to be used for views on panel.
Definition at line 145 of file SCurveEditorPanel.h.
References GridLineTintAttribute.
GetKeyDetailsView()
TSharedPtr< class SCurveKeyDetailPanel > SCurveEditorPanel::GetKeyDetailsView () const inline private
Access the details view used for editing selected keys.
Definition at line 104 of file SCurveEditorPanel.h.
References KeyDetailsView.
GetScrollPanelGeometry()
const FGeometry & SCurveEditorPanel::GetScrollPanelGeometry () const private
Access the cached geometry of the outer scroll panel that contains this panel's views.
GetSplitterVisibility()
EVisibility SCurveEditorPanel::GetSplitterVisibility () const private
Get the visibility for the value splitter control.
GetTangentModeIcon()
FSlateIcon SCurveEditorPanel::GetTangentModeIcon () const private
GetTangentModeLabel()
FText SCurveEditorPanel::GetTangentModeLabel () const private
GetTangentModeTooltip()
FText SCurveEditorPanel::GetTangentModeTooltip () const private
GetTimeSnapMenuTooltip()
FText SCurveEditorPanel::GetTimeSnapMenuTooltip () const private
GetToolbarExtender()
TSharedPtr< FExtender > SCurveEditorPanel::GetToolbarExtender () private
This returns an extender which is pre-configured with the standard set of Toolbar Icons.
Implementers of SCurveEditorPanel should use this to generate the icons and then add any additional context-specific icons (such as save buttons in the Asset Editor) to ensure that the Curve Editor has a consistent set (and order) of icons across all usages.
GetToolPropertiesPanel()
TSharedPtr< class SCurveEditorToolProperties > SCurveEditorPanel::GetToolPropertiesPanel () const inline private
Access the tool properties panel.
Definition at line 120 of file SCurveEditorPanel.h.
References ToolPropertiesPanel.
GetViewContainerGeometry()
const FGeometry & SCurveEditorPanel::GetViewContainerGeometry () const private
Access the cached geometry of container housing all this panel's views.
GetViewMode()
ECurveEditorViewID SCurveEditorPanel::GetViewMode () const inline private
Get the last set View Mode for this UI.
Utility function for the UI.
Definition at line 168 of file SCurveEditorPanel.h.
References DefaultViewID.
GetViews()
TArrayView< const TSharedPtr< SCurveEditorView > > SCurveEditorPanel::GetViews () const private
Get all the views stored in this panel.
IsInlineEditPanelEditable()
bool SCurveEditorPanel::IsInlineEditPanelEditable () const private
IsTangentModeComboEnabled()
bool SCurveEditorPanel::IsTangentModeComboEnabled () const private
MakeAxisSnapMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeAxisSnapMenu () private
MakeCurveEditorCurveViewOptionsMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeCurveEditorCurveViewOptionsMenu (TSharedPtr< FExtender > InExtender) private
Creates the drop-down list you see when changing Curve View options.
MakeCurvesMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeCurvesMenu (TSharedPtr< FExtender > InExtender) private
Creates the drop-down for changing curves on a whole.
MakeFlipCurveMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeFlipCurveMenu (FCurveEditor::ECurveFlipDirection Direction) private
MakeGridSpacingMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeGridSpacingMenu () private
MakeTangentModeMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeTangentModeMenu () private
MakeTimeSnapMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeTimeSnapMenu () private
MakeToolsComboMenu()
TSharedRef< SWidget > SCurveEditorPanel::MakeToolsComboMenu (TSharedPtr< FExtender > InExtender) private
OnColumnFillCoefficientChanged()
void SCurveEditorPanel::OnColumnFillCoefficientChanged (float FillCoefficient, int32 ColumnIndex) private
Called when a column fill percentage is changed by a splitter slot.
OnCurveEditorToolChanged()
void SCurveEditorPanel::OnCurveEditorToolChanged (FCurveEditorToolID InToolId) private
Reconstructs the properties widget on tool switch.
OnKeyDown()
virtual FReply SCurveEditorPanel::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override private virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseEnter()
virtual void SCurveEditorPanel::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override private virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent.
OnMouseLeave()
virtual void SCurveEditorPanel::OnMouseLeave (const FPointerEvent & MouseEvent) override private virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent.
OnPostRebuildCurveViews()
FSimpleMulticastDelegate & SCurveEditorPanel::OnPostRebuildCurveViews () inline private
Broadcasts after the curve views have been rebuilt (by RebuildCurveViews).
Definition at line 187 of file SCurveEditorPanel.h.
References OnPostRebuildCurveViewsDelegate.
OnSplitterFinishedResizing()
void SCurveEditorPanel::OnSplitterFinishedResizing () private
PostUndo()
void SCurveEditorPanel::PostUndo () private
Undo occurred, invalidate or update internal structures.
RebuildCurveViews()
void SCurveEditorPanel::RebuildCurveViews () private
Rebuild the Curve Views layout to match the currently specified View Mode.
RemoveCurveFromViews()
void SCurveEditorPanel::RemoveCurveFromViews (FCurveModelID InCurveID) private
Remove the specified curve from all views it is currently displayed on.
RemoveView()
void SCurveEditorPanel::RemoveView (TSharedRef< SCurveEditorView > ViewToRemove) private
ResetMinMaxes()
void SCurveEditorPanel::ResetMinMaxes () private
Reset Stored Min/Max's.
ScrollBy()
void SCurveEditorPanel::ScrollBy (float Amount) private
Scroll this panel's view scroll box vertically by the specified amount.
SetAxisSnapping()
void SCurveEditorPanel::SetAxisSnapping (ECurveEditorSnapAxis) private
Sets the axis snapping to the specified value.
Only supports X, Y and None.
SetCurveAttributes()
void SCurveEditorPanel::SetCurveAttributes (FCurveAttributes CurveAttributes, FText Description) private
Assign new curve attributes to all visible curves.
SetKeyAttributes()
void SCurveEditorPanel::SetKeyAttributes (FKeyAttributes KeyAttributes, FText Description) private
Assign new attributes to the currently selected keys.
SetViewMode()
void SCurveEditorPanel::SetViewMode (const ECurveEditorViewID NewViewMode) private
Sets the View Mode for the UI to the specified mode.
This will destroy and re-create all views, but leave additional pinned views unmodified.
ShouldInstructionOverlayBeVisible()
EVisibility SCurveEditorPanel::ShouldInstructionOverlayBeVisible () const private
ShowCurveFilterUI()
void SCurveEditorPanel::ShowCurveFilterUI (TSubclassOf< UCurveEditorFilterBase > FilterClass) private
Creates the Curve Editor Filter UI and pre-populates it with the specified class.
SLATE_ARGUMENT()
TabManager SCurveEditorPanel::SLATE_ARGUMENT (TSharedPtr< ITimeSliderController > , ExternalTimeSliderController) private
Optional Time Slider Controller which allows us to synchronize with an externally controlled Time Slider.
If specified, causes the time snap adjustment UI controls to be disabled and specifies the tooltip to be used. Can be used to disable time snap controls when externally controlled.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), and SLATE_NAMED_SLOT().
SLATE_ATTRIBUTE()
SCurveEditorPanel::SLATE_ATTRIBUTE (FLinearColor , GridLineTint) private
Color to draw grid lines.
Tab Manager which owns this panel.
Referenced by SLATE_ARGUMENT().
SLATE_BEGIN_ARGS()
SCurveEditorPanel::SLATE_BEGIN_ARGS (SCurveEditorPanel) inline private
Definition at line 60 of file SCurveEditorPanel.h.
SLATE_END_ARGS()
TabManager DisabledTimeSnapTooltip MinimumViewPanelHeight SCurveEditorPanel::SLATE_END_ARGS () private
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
SLATE_NAMED_SLOT()
TabManager DisabledTimeSnapTooltip SCurveEditorPanel::SLATE_NAMED_SLOT (FArguments , TreeContent) private
Widget slot for the tree content.
The minimum height for the panel which contains the curve editor views.
References SLATE_ARGUMENT(), and SLATE_NAMED_SLOT().
Referenced by SLATE_NAMED_SLOT().
SupportsKeyboardFocus()
virtual bool SCurveEditorPanel::SupportsKeyboardFocus () const inline override private virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Definition at line 195 of file SCurveEditorPanel.h.
Tick()
virtual void SCurveEditorPanel::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override private virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
ToggleWeightedTangents()
void SCurveEditorPanel::ToggleWeightedTangents () private
Toggle weighted tangents on the current selection.
UpdateAxisSnapping()
void SCurveEditorPanel::UpdateAxisSnapping () private
Update the axis snapping based on the settings.
UpdateCommonCurveInfo()
void SCurveEditorPanel::UpdateCommonCurveInfo () private
UpdateEditBox()
void SCurveEditorPanel::UpdateEditBox () private
UpdateTime()
void SCurveEditorPanel::UpdateTime () private
Field Documentation
bNeedsRefresh
bool SCurveEditorPanel::bNeedsRefresh private
Whether to explicitly refresh the views for this panel.
Definition at line 453 of file SCurveEditorPanel.h.
bSelectionSupportsWeightedTangents
bool SCurveEditorPanel::bSelectionSupportsWeightedTangents private
True if the current selection supports weighted tangents, false otherwise.
Definition at line 386 of file SCurveEditorPanel.h.
CachedActiveCurvesSerialNumber
uint32 SCurveEditorPanel::CachedActiveCurvesSerialNumber private
Serial number cached from FCurveEditor::GetActiveCurvesSerialNumber() on tick.
Definition at line 456 of file SCurveEditorPanel.h.
CachedCommonCurveAttributes
FCurveAttributes SCurveEditorPanel::CachedCommonCurveAttributes private
Cached curve attributes that are common to all visible curves.
Definition at line 380 of file SCurveEditorPanel.h.
Referenced by CompareCommonPostExtrapolationMode(), and CompareCommonPreExtrapolationMode().
CachedCommonKeyAttributes
FKeyAttributes SCurveEditorPanel::CachedCommonKeyAttributes private
Cached key attributes that are common to all selected keys.
Definition at line 383 of file SCurveEditorPanel.h.
Referenced by CompareCommonInterpolationMode(), CompareCommonTangentMode(), and CompareCommonTangentWeightMode().
CachedSelectionSerialNumber
uint32 SCurveEditorPanel::CachedSelectionSerialNumber private
Cached serial number from the curve editor selection.
Used to update edit UIs when the selection changes.
Definition at line 413 of file SCurveEditorPanel.h.
CachedViewGeometry
FGeometry SCurveEditorPanel::CachedViewGeometry private
A copy of the View Geometry used to represent the View portion of the Curve Editor.
Definition at line 459 of file SCurveEditorPanel.h.
ColumnFillCoefficients
float SCurveEditorPanel::ColumnFillCoefficients[2] private
The fill coefficients of each column in the grid.
Definition at line 462 of file SCurveEditorPanel.h.
Referenced by GetColumnFillCoefficient().
CommandList
TSharedPtr<FUICommandList> SCurveEditorPanel::CommandList private
Command list for widget specific command bindings.
Definition at line 407 of file SCurveEditorPanel.h.
Referenced by GetCommands().
CurveEditor
TSharedPtr<FCurveEditor> SCurveEditorPanel::CurveEditor private
The curve editor pointer.
Definition at line 368 of file SCurveEditorPanel.h.
CurveToEditUI
TMap<FCurveModelID, TSharedPtr<SWidget> > SCurveEditorPanel::CurveToEditUI private
Map of edit UI widgets for each curve in the current selection set.
Definition at line 404 of file SCurveEditorPanel.h.
CurveViews
TMultiMap<FCurveModelID, TSharedRef<SCurveEditorView> > SCurveEditorPanel::CurveViews private
Map from curve model ID to the views that it is on.
Definition at line 371 of file SCurveEditorPanel.h.
Referenced by FindViews().
CurveViewsContainer
TSharedPtr<SCurveEditorViewContainer> SCurveEditorPanel::CurveViewsContainer private
The container for all our vertically laid out curve views.
Definition at line 445 of file SCurveEditorPanel.h.
DefaultViewID
ECurveEditorViewID SCurveEditorPanel::DefaultViewID private
The last set View Mode for this UI.
Definition at line 434 of file SCurveEditorPanel.h.
Referenced by GetViewMode().
DisabledTimeSnapTooltipAttribute
TAttribute<FText> SCurveEditorPanel::DisabledTimeSnapTooltipAttribute private
Attribute used for retrieving the tooltip for when the Time Snap control is disabled.
Specifying this causes the Time Snap Adjustment to be disabled.
Definition at line 392 of file SCurveEditorPanel.h.
DragOperation
TOptional<FCurveEditorDelayedDrag> SCurveEditorPanel::DragOperation private
(Optional) the current drag operation
Definition at line 377 of file SCurveEditorPanel.h.
EditObjects
TUniquePtr<FCurveEditorEditObjectContainer> SCurveEditorPanel::EditObjects private
Container of objects that are being used to edit keys on the curve editor.
Definition at line 467 of file SCurveEditorPanel.h.
ExternalViews
TSet<TSharedRef<SCurveEditorView> > SCurveEditorPanel::ExternalViews private
Set of externally added views.
Definition at line 374 of file SCurveEditorPanel.h.
FilterPanel
TSharedPtr<SCurveEditorFilterPanel> SCurveEditorPanel::FilterPanel private
Definition at line 398 of file SCurveEditorPanel.h.
Referenced by GetFilterPanel().
FreeViewsByType
TMultiMap<ECurveEditorViewID, TSharedRef<SCurveEditorView> > SCurveEditorPanel::FreeViewsByType private
Definition at line 439 of file SCurveEditorPanel.h.
GridLineTintAttribute
TAttribute<FLinearColor> SCurveEditorPanel::GridLineTintAttribute private
Attribute used for retrieving the desired grid line color.
Definition at line 389 of file SCurveEditorPanel.h.
Referenced by GetGridLineTint().
KeyDetailsView
TSharedPtr<SCurveKeyDetailPanel> SCurveEditorPanel::KeyDetailsView private
Edit panel.
Definition at line 395 of file SCurveEditorPanel.h.
Referenced by GetKeyDetailsView().
LastOutputMax
double SCurveEditorPanel::LastOutputMax = DBL_MIN private
Definition at line 431 of file SCurveEditorPanel.h.
LastOutputMin
double SCurveEditorPanel::LastOutputMin = DBL_MAX private
Last Output Min and Max values for the views.
Definition at line 430 of file SCurveEditorPanel.h.
OnFilterClassChanged
FSimpleDelegate SCurveEditorPanel::OnFilterClassChanged private
Delegate for when the chosen filter class has changed.
Definition at line 180 of file SCurveEditorPanel.h.
OnPostRebuildCurveViewsDelegate
FSimpleMulticastDelegate SCurveEditorPanel::OnPostRebuildCurveViewsDelegate private
Broadcasts after the curve views have been rebuilt (by RebuildCurveViews).
Definition at line 437 of file SCurveEditorPanel.h.
Referenced by OnPostRebuildCurveViews().
PendingFocus
FPendingWidgetFocus SCurveEditorPanel::PendingFocus private
Pending focus handler.
Definition at line 450 of file SCurveEditorPanel.h.
ScrollBox
TSharedPtr<SScrollBox> SCurveEditorPanel::ScrollBox private
The scrool box that all curve views live inside.
Definition at line 442 of file SCurveEditorPanel.h.
ToolbarPromotedFilterBinder
TUniquePtr<UE::CurveEditor::FPromotedFilterCommandBinder> SCurveEditorPanel::ToolbarPromotedFilterBinder private
Binds commands from FPromotedFilterContainer so the filters surfaced from SCurveEditorFilterPanel show up in the toolbar.
Definition at line 410 of file SCurveEditorPanel.h.
ToolPropertiesPanel
TSharedPtr<SCurveEditorToolProperties> SCurveEditorPanel::ToolPropertiesPanel private
Tool options panel.
Definition at line 401 of file SCurveEditorPanel.h.
Referenced by GetToolPropertiesPanel().
TreeViewSplitter
TSharedPtr<class SSplitter> SCurveEditorPanel::TreeViewSplitter private
Definition at line 464 of file SCurveEditorPanel.h.
WeakTabManager
TWeakPtr<FTabManager> SCurveEditorPanel::WeakTabManager private
Definition at line 469 of file SCurveEditorPanel.h.
The documentation for this class was generated from the following file:
SCurveEditorPanel.h