Unreal Engine 5.6 C++ API: FSlateAttributeDescriptor::FInitializer::FAttributeEntry Struct Reference
FSlateAttributeDescriptor::FInitializer::FAttributeEntry Struct Reference
#include "SlateAttributeDescriptor.h"
Public Member Functions
FAttributeEntry (FSlateAttributeDescriptor &Descriptor, int32 InAttributeIndex)
FAttributeEntry & AffectVisibility ()
The attribute affect the visibility of the widget.
FAttributeEntry & OnValueChanged (FAttributeValueChangedDelegate Callback)
Notified when the attribute value changed.
FAttributeEntry & UpdatePrerequisite (FName Prerequisite)
Update the attribute after the prerequisite.
Private Attributes
int32 AttributeIndex
FSlateAttributeDescriptor & Descriptor
Detailed Description
Definition at line 272 of file SlateAttributeDescriptor.h.
Constructor & Destructor Documentation
FAttributeEntry()
FSlateAttributeDescriptor::FInitializer::FAttributeEntry::FAttributeEntry (FSlateAttributeDescriptor & Descriptor, int32 InAttributeIndex)
References Descriptor.
Referenced by AffectVisibility(), OnValueChanged(), and UpdatePrerequisite().
Member Function Documentation
AffectVisibility()
FAttributeEntry & FSlateAttributeDescriptor::FInitializer::FAttributeEntry::AffectVisibility ()
The attribute affect the visibility of the widget.
We only update the attributes that can change the visibility of the widget when the widget is collapsed. Attributes that affect visibility must have the Visibility attribute as a Prerequisite or the Visibility attribute must have it as a Prerequisite.
References FAttributeEntry().
OnValueChanged()
FAttributeEntry & FSlateAttributeDescriptor::FInitializer::FAttributeEntry::OnValueChanged (FAttributeValueChangedDelegate Callback)
Notified when the attribute value changed.
It's preferable that you delay any action to the Tick or Paint function. You are not allowed to make changes that would affect the SWidget ChildOrder or its Visibility. It will not be called when the SWidget is in its construction phase.
See also
SWidget::IsConstructed
References FAttributeEntry().
UpdatePrerequisite()
FAttributeEntry & FSlateAttributeDescriptor::FInitializer::FAttributeEntry::UpdatePrerequisite (FName Prerequisite)
Update the attribute after the prerequisite.
The order is guaranteed but other attributes may be updated in between. No order is guaranteed if the prerequisite or this property is updated manually.
References FAttributeEntry().
Field Documentation
AttributeIndex
int32 FSlateAttributeDescriptor::FInitializer::FAttributeEntry::AttributeIndex private
Definition at line 301 of file SlateAttributeDescriptor.h.
Descriptor
FSlateAttributeDescriptor& FSlateAttributeDescriptor::FInitializer::FAttributeEntry::Descriptor private
Definition at line 300 of file SlateAttributeDescriptor.h.
Referenced by FAttributeEntry().
The documentation for this struct was generated from the following file:
SlateAttributeDescriptor.h