Unreal Engine 5.6 C++ API: TObjectPtr< T > Struct Template Reference
TObjectPtr< T > Struct Template Reference
TObjectPtr is a type of pointer to a UObject that is meant to function as a drop-in replacement for raw pointer member properties.
#include "ObjectPtr.h"
Public Types
using ElementType = T
Public Member Functions
TObjectPtr ()
TObjectPtr (const TObjectPtr< T > &Other)
template<typename U UE_REQUIRES>
FORCEINLINE TObjectPtr (const TObjectPtr< U > &Other)
template<typename U UE_REQUIRES>
FORCEINLINE TObjectPtr (const U &Object)
FORCEINLINE TObjectPtr (ENoInit)
FORCEINLINE TObjectPtr (FObjectPtr ObjPtr)
TObjectPtr (TObjectPtr< T > &&Other)
FORCEINLINE TObjectPtr (TPrivateObjectPtr< T > &&PrivatePtr)
FORCEINLINE TObjectPtr (TYPE_OF_NULLPTR)
FORCEINLINE T * Get () const
FORCEINLINE UClass * GetClass () const
FORCEINLINE FName GetFName () const
FORCEINLINE FString GetFullName (EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
FORCEINLINE FObjectHandle GetHandle () const
FORCEINLINE FString GetName () const
FORCEINLINE TObjectPtr< UObject > GetOuter () const
FORCEINLINE TObjectPtr< UPackage > GetPackage () const
FORCEINLINE FString GetPath () const
FORCEINLINE FString GetPathName () const
FORCEINLINE uint32 GetPtrTypeHash () const
template<typename U>
FORCEINLINE bool IsA () const
FORCEINLINE bool IsA (const UClass *SomeBase) const
FORCEINLINE bool IsIn (FObjectPtr SomeOuter) const
template<typename U>
FORCEINLINE bool IsIn (TObjectPtr< U > SomeOuter) const
FORCEINLINE bool IsRemote () const
FORCEINLINE bool IsResolved () const
FORCEINLINE operator bool () const
FORCEINLINE operator T* () const
FORCEINLINE operator T*& ()
template<typename U>
FORCEINLINE operator U* () const
FORCEINLINE operator UPTRINT () const
FORCEINLINE bool operator! () const
template<typename U>
FORCEINLINE auto operator!= (const U &Other) const -> decltype(!(*this==Other))
FORCEINLINE T & operator* () const
FORCEINLINE T * operator-> () const
TObjectPtr< T > & operator= (const TObjectPtr< T > &Other)
template<typename U UE_REQUIRES>
FORCEINLINE TObjectPtr< T > & operator= (const TObjectPtr< U > &Other)
TObjectPtr< T > & operator= (TObjectPtr< T > &&Other)
FORCEINLINE TObjectPtr< T > & operator= (TPrivateObjectPtr< T > &&PrivatePtr)
FORCEINLINE TObjectPtr< T > & operator= (TYPE_OF_NULLPTR)
template<typename U UE_REQUIRES>
FORCEINLINE TObjectPtr< T > & operator= (U &&Object)
template<typename U, typename Base = std::common_type_t<T*, U*>>
FORCEINLINE bool operator== (const TObjectPtr< U > &Other) const
template<typename U, typename = decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval<const TObjectPtr<T>&>(), std::declval<const U&>()))>
FORCEINLINE bool operator== (const U &Other) const
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE void SerializePtrStructured (FStructuredArchiveSlot Slot)
UE_DEPRECATED (5.6, "Constructing a TObjectPtr from a reference is deprecated - use a pointer instead.") FORCEINLINE TObjectPtr(T &Object)
Private Member Functions
FORCEINLINE T *& GetInternalRef ()
FORCEINLINE T * GetNoReadNoCheck () const
FORCEINLINE T * GetNoResolveNoCheck () const
Private Attributes
union {
T * DebugPtr
FObjectPtr ObjectPtr
};
Friends
template<typename U>
struct TObjectPtr
struct FObjectPtr
template<typename U, typename V>
bool ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType (const TObjectPtr< U > &Ptr, const V *Other)
Detailed Description
template<typename T>
struct TObjectPtr< T >
TObjectPtr is a type of pointer to a UObject that is meant to function as a drop-in replacement for raw pointer member properties.
It is size equivalent to a 64-bit pointer and supports access tracking and optional lazy load behavior in editor builds. It stores either the address to the referenced object or (in editor builds) an index in the object handle table that describes a referenced object that hasn't been loaded yet. It is serialized identically to a raw pointer to a UObject. When resolved, its participation in garbage collection is identical to a raw pointer to a UObject.
This is useful for automatic replacement of raw pointers to support advanced cook-time dependency tracking and editor-time lazy load use cases. See UnrealObjectPtrTool for tooling to automatically replace raw pointer members with FObjectPtr/TObjectPtr members instead.
Definition at line 501 of file ObjectPtr.h.
Member Typedef Documentation
ElementType
template<typename T> using TObjectPtr< T >::ElementType = T
Definition at line 514 of file ObjectPtr.h.
Constructor & Destructor Documentation
TObjectPtr() [1/9]
template<typename T> TObjectPtr< T >::TObjectPtr () inline nodiscard
Definition at line 516 of file ObjectPtr.h.
References ObjectPtr.
TObjectPtr() [2/9]
template<typename T> TObjectPtr< T >::TObjectPtr (TObjectPtr< T > && Other) inline nodiscard
Definition at line 522 of file ObjectPtr.h.
References TObjectPtr, MoveTemp(), ObjectPtr, and Other.
TObjectPtr() [3/9]
template<typename T> TObjectPtr< T >::TObjectPtr (const TObjectPtr< T > & Other) inline nodiscard
Definition at line 526 of file ObjectPtr.h.
References TObjectPtr, ObjectPtr, and Other.
TObjectPtr() [4/9]
template<typename T> FORCEINLINE TObjectPtr< T >::TObjectPtr (ENoInit) inline explicit nodiscard
Definition at line 535 of file ObjectPtr.h.
References FORCEINLINE, NoInit, and ObjectPtr.
TObjectPtr() [5/9]
template<typename T> FORCEINLINE TObjectPtr< T >::TObjectPtr (TYPE_OF_NULLPTR) inline nodiscard
Definition at line 540 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
TObjectPtr() [6/9]
template<typename T> FORCEINLINE TObjectPtr< T >::TObjectPtr (FObjectPtr ObjPtr) inline explicit nodiscard
Definition at line 545 of file ObjectPtr.h.
References FObjectPtr, FORCEINLINE, and ObjectPtr.
TObjectPtr() [7/9]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TObjectPtr< T >::TObjectPtr (const TObjectPtr< U > & Other) inline nodiscard
Definition at line 554 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, IWYU_MARKUP_IMPLICIT_CAST, ObjectPtr, and Other.
TObjectPtr() [8/9]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TObjectPtr< T >::TObjectPtr (const U & Object) inline nodiscard
Definition at line 564 of file ObjectPtr.h.
References FORCEINLINE, ImplicitConv(), Object, and ObjectPtr.
TObjectPtr() [9/9]
template<typename T> FORCEINLINE TObjectPtr< T >::TObjectPtr (TPrivateObjectPtr< T > && PrivatePtr) inline explicit nodiscard
Definition at line 575 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr, and Pointer.
Member Function Documentation
Get()
template<typename T> FORCEINLINE T * TObjectPtr< T >::Get () const inline nodiscard
Definition at line 681 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::Get(), and ObjectPtr.
Referenced by FMaterialParameterValue::FMaterialParameterValue(), FMaterialParameterValue::FMaterialParameterValue(), FMaterialParameterValue::FMaterialParameterValue(), FMaterialParameterValue::FMaterialParameterValue(), FSoftObjectPath::FSoftObjectPath(), TScriptInterface< const InterfaceType >::TScriptInterface(), FWidgetBlueprintEditor::AddSlotTrack(), CastChecked(), FSoftObjectPath::ConstructFromObject(), TListTypeTraits< TObjectPtr< T > >::DebugDump(), TObjectPtr< AActor >::operator AActor *(), operator U*(), operator UPTRINT(), operator*(), operator->(), FFrame::ReadObject(), StaticCastPtr(), ToRawPtr(), and USTRUCT().
GetClass()
template<typename T> FORCEINLINE UClass * TObjectPtr< T >::GetClass () const inline nodiscard
Definition at line 682 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
GetFName()
template<typename T> FORCEINLINE FName TObjectPtr< T >::GetFName () const inline nodiscard
Definition at line 759 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
GetFullName()
template<typename T> FORCEINLINE FString TObjectPtr< T >::GetFullName (EObjectFullNameFlags Flags = EObjectFullNameFlags::None) const inline nodiscard
Definition at line 767 of file ObjectPtr.h.
References Flags, FORCEINLINE, None, and ObjectPtr.
GetHandle()
template<typename T> FORCEINLINE FObjectHandle TObjectPtr< T >::GetHandle () const inline nodiscard
Definition at line 771 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
GetInternalRef()
template<typename T> FORCEINLINE T *& TObjectPtr< T >::GetInternalRef () inline private
Definition at line 814 of file ObjectPtr.h.
References check, FORCEINLINE, ObjectPtr_Private::Get(), and ObjectPtr.
Referenced by TObjectPtr< AActor >::operator AActor *&().
GetName()
template<typename T> FORCEINLINE FString TObjectPtr< T >::GetName () const inline nodiscard
Definition at line 763 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
GetNoReadNoCheck()
template<typename T> FORCEINLINE T * TObjectPtr< T >::GetNoReadNoCheck () const inline private
Definition at line 808 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr, and UE::CoreUObject::Private::ResolveObjectHandleNoReadNoCheck().
Referenced by ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType().
GetNoResolveNoCheck()
template<typename T> FORCEINLINE T * TObjectPtr< T >::GetNoResolveNoCheck () const inline private
Definition at line 809 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr, and UE::CoreUObject::Private::ReadObjectHandlePointerNoCheck().
Referenced by ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType().
GetOuter()
template<typename T> FORCEINLINE TObjectPtr< UObject > TObjectPtr< T >::GetOuter () const inline nodiscard
Definition at line 683 of file ObjectPtr.h.
References TObjectPtr, FObjectPtr, FORCEINLINE, and ObjectPtr.
GetPackage()
template<typename T> FORCEINLINE TObjectPtr< UPackage > TObjectPtr< T >::GetPackage () const inline nodiscard
Definition at line 689 of file ObjectPtr.h.
References TObjectPtr, FObjectPtr, FORCEINLINE, and ObjectPtr.
GetPath()
template<typename T> FORCEINLINE FString TObjectPtr< T >::GetPath () const inline nodiscard
Definition at line 751 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
GetPathName()
template<typename T> FORCEINLINE FString TObjectPtr< T >::GetPathName () const inline nodiscard
Definition at line 755 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
Referenced by FSoftObjectPath::FSoftObjectPath().
GetPtrTypeHash()
template<typename T> FORCEINLINE uint32 TObjectPtr< T >::GetPtrTypeHash () const inline nodiscard
Definition at line 785 of file ObjectPtr.h.
References FORCEINLINE, GetTypeHash(), and ObjectPtr.
IsA() [1/2]
template<typename T> template<typename U> FORCEINLINE bool TObjectPtr< T >::IsA () const inline nodiscard
Definition at line 780 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
IsA() [2/2]
template<typename T> FORCEINLINE bool TObjectPtr< T >::IsA (const UClass * SomeBase) const inline nodiscard
Definition at line 775 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
IsIn() [1/2]
template<typename T> FORCEINLINE bool TObjectPtr< T >::IsIn (FObjectPtr SomeOuter) const inline nodiscard
Definition at line 695 of file ObjectPtr.h.
References FObjectPtr, FORCEINLINE, and ObjectPtr.
IsIn() [2/2]
template<typename T> template<typename U> FORCEINLINE bool TObjectPtr< T >::IsIn (TObjectPtr< U > SomeOuter) const inline nodiscard
Definition at line 701 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, and ObjectPtr.
IsRemote()
template<typename T> FORCEINLINE bool TObjectPtr< T >::IsRemote () const inline nodiscard
Definition at line 747 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
Referenced by MakeWeakObjectPtr().
IsResolved()
template<typename T> FORCEINLINE bool TObjectPtr< T >::IsResolved () const inline nodiscard
Definition at line 743 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
Referenced by FSoftObjectPath::FSoftObjectPath(), and ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType().
operator bool()
template<typename T> FORCEINLINE TObjectPtr< T >::operator bool () const inline explicit nodiscard
Definition at line 739 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrNull(), and ObjectPtr.
operator T*()
template<typename T> FORCEINLINE TObjectPtr< T >::operator T* () const inline nodiscard
Definition at line 706 of file ObjectPtr.h.
operator T*&()
template<typename T> FORCEINLINE TObjectPtr< T >::operator T*& () inline explicit nodiscard
Definition at line 730 of file ObjectPtr.h.
operator U*()
template<typename T> template<typename U> FORCEINLINE TObjectPtr< T >::operator U* () const inline explicit nodiscard
Definition at line 712 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator UPTRINT()
template<typename T> FORCEINLINE TObjectPtr< T >::operator UPTRINT () const inline explicit nodiscard
Definition at line 716 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator!()
template<typename T> FORCEINLINE bool TObjectPtr< T >::operator! () const inline nodiscard
Definition at line 735 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrNull(), and ObjectPtr.
operator!=()
template<typename T> template<typename U> FORCEINLINE auto TObjectPtr< T >::operator!= (const U & Other) const -> decltype(!(*this == Other)) inline nodiscard
Definition at line 669 of file ObjectPtr.h.
References FORCEINLINE, and Other.
operator*()
template<typename T> FORCEINLINE T & TObjectPtr< T >::operator* () const inline nodiscard
Definition at line 724 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator->()
template<typename T> FORCEINLINE T * TObjectPtr< T >::operator-> () const inline nodiscard
Definition at line 720 of file ObjectPtr.h.
References FORCEINLINE, and Get().
operator=() [1/6]
template<typename T> TObjectPtr< T > & TObjectPtr< T >::operator= (const TObjectPtr< T > & Other) inline
Definition at line 586 of file ObjectPtr.h.
References TObjectPtr, ObjectPtr, and Other.
operator=() [2/6]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TObjectPtr< T > & TObjectPtr< T >::operator= (const TObjectPtr< U > & Other) inline
Definition at line 606 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, IWYU_MARKUP_IMPLICIT_CAST, ObjectPtr, and Other.
operator=() [3/6]
template<typename T> TObjectPtr< T > & TObjectPtr< T >::operator= (TObjectPtr< T > && Other) inline
Definition at line 581 of file ObjectPtr.h.
References TObjectPtr, MoveTemp(), ObjectPtr, and Other.
operator=() [4/6]
template<typename T> FORCEINLINE TObjectPtr< T > & TObjectPtr< T >::operator= (TPrivateObjectPtr< T > && PrivatePtr) inline
Definition at line 623 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, and ObjectPtr.
operator=() [5/6]
template<typename T> FORCEINLINE TObjectPtr< T > & TObjectPtr< T >::operator= (TYPE_OF_NULLPTR) inline
Definition at line 596 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, and ObjectPtr.
operator=() [6/6]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TObjectPtr< T > & TObjectPtr< T >::operator= (U && Object) inline
Definition at line 617 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, ImplicitConv(), Object, and ObjectPtr.
operator==() [1/3]
template<typename T> template<typename U, typename Base = std::common_type_t<T*, U*>> FORCEINLINE bool TObjectPtr< T >::operator== (const TObjectPtr< U > & Other) const inline nodiscard
Definition at line 634 of file ObjectPtr.h.
References TObjectPtr, FORCEINLINE, ObjectPtr_Private::IsObjectPtrNull(), ObjectPtr, and Other.
operator==() [2/3]
template<typename T> template<typename U, typename = decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval<const TObjectPtr<T>&>(), std::declval<const U&>()))> FORCEINLINE bool TObjectPtr< T >::operator== (const U & Other) const inline nodiscard
Definition at line 662 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrEqual(), and Other.
operator==() [3/3]
template<typename T> FORCEINLINE bool TObjectPtr< T >::operator== (TYPE_OF_NULLPTR) const inline nodiscard
Definition at line 652 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrNull(), and ObjectPtr.
SerializePtrStructured()
template<typename T> FORCEINLINE void TObjectPtr< T >::SerializePtrStructured (FStructuredArchiveSlot Slot) inline
Definition at line 790 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr.
UE_DEPRECATED()
template<typename T> TObjectPtr< T >::UE_DEPRECATED (5. 6, "Constructing a TObjectPtr< T > from a reference is deprecated - use a pointer instead.") & inline nodiscard
Definition at line 569 of file ObjectPtr.h.
References FORCEINLINE, Object, and ObjectPtr.
Friends And Related Symbol Documentation
TObjectPtr
template<typename T> template<typename U> friend struct TObjectPtr friend
Definition at line 804 of file ObjectPtr.h.
References TObjectPtr.
Referenced by TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr, GetOuter(), GetPackage(), IsIn(), ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType, operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().
FObjectPtr
template<typename T> friend struct FObjectPtr friend
Definition at line 803 of file ObjectPtr.h.
References FObjectPtr.
Referenced by TObjectPtr(), FObjectPtr, GetOuter(), GetPackage(), and IsIn().
ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType
template<typename T> template<typename U, typename V> bool ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType (const TObjectPtr< U > & Ptr, const V * Other) friend
References TObjectPtr, and Other.
Field Documentation
[union]
union { ... } TObjectPtr< T >
DebugPtr
template<typename T> T* TObjectPtr< T >::DebugPtr
Definition at line 828 of file ObjectPtr.h.
ObjectPtr
template<typename T> FObjectPtr TObjectPtr< T >::ObjectPtr
Definition at line 825 of file ObjectPtr.h.
Referenced by TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), TObjectPtr(), Get(), GetClass(), GetFName(), GetFullName(), GetHandle(), GetInternalRef(), GetName(), GetNoReadNoCheck(), GetNoResolveNoCheck(), GetOuter(), GetPackage(), GetPath(), GetPathName(), ObjectPtr_Private::Friend::GetPtrTypeHash(), GetPtrTypeHash(), IsA(), IsA(), IsIn(), IsIn(), IsRemote(), IsResolved(), ObjectPtr_Private::Friend::NoAccessTrackingGet(), ObjectPtr_Private::Friend::NoAccessTrackingGetNoResolve(), operator bool(), operator!(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), operator==(), ObjectPtr_Private::Friend::Serialize(), ObjectPtr_Private::Friend::SerializePtrStructured(), SerializePtrStructured(), and UE_DEPRECATED().
The documentation for this struct was generated from the following files:
EdGraphSchema_K2.h
ObjectPtr.h