Unreal Engine 5.6 C++ API: TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > > Struct Template Reference
TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > > Struct Template Reference
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>, FSparseItemInfo, false>
typedef TWeakPtr< T, ESPMode::ThreadSafe > NullableType
using SetKeyFuncs = DefaultKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>>
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< TWeakPtr< T, ESPMode::ThreadSafe > > &, TSet< TWeakPtr< T, ESPMode::ThreadSafe > > &, TMap< const U *, TWeakPtr< T, ESPMode::ThreadSafe > > &WidgetToItemMap)
static FString DebugDump (TWeakPtr< T, ESPMode::ThreadSafe > InPtr)
static bool IsPtrValid (const TWeakPtr< T, ESPMode::ThreadSafe > &InPtr)
static TWeakPtr< T, ESPMode::ThreadSafe > MakeNullPtr ()
static TWeakPtr< T, ESPMode::ThreadSafe > NullableItemTypeConvertToItemType (const TWeakPtr< T, ESPMode::ThreadSafe > &InPtr)
static void ResetPtr (TWeakPtr< T, ESPMode::ThreadSafe > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >
Definition at line 358 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>, TSharedRef<ITableRow>, false>
Definition at line 363 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>, FSparseItemInfo, false>
Definition at line 364 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TWeakPtr<T, ESPMode::ThreadSafe> TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::NullableType
Definition at line 361 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::SetKeyFuncs = DefaultKeyFuncs<TWeakPtr<T, ESPMode::ThreadSafe>>
Definition at line 365 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::AddReferencedObjects (FReferenceCollector & , TArray< TWeakPtr< T, ESPMode::ThreadSafe > > & , TSet< TWeakPtr< T, ESPMode::ThreadSafe > > & , TMap< const U *, TWeakPtr< T, ESPMode::ThreadSafe > > & WidgetToItemMap) inline static
Definition at line 368 of file TableViewTypeTraits.h.
DebugDump()
template<typename T> FString TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::DebugDump (TWeakPtr< T, ESPMode::ThreadSafe > InPtr) inline static
Definition at line 395 of file TableViewTypeTraits.h.
References TWeakPtr< ObjectType, InMode >::IsValid(), TWeakPtr< ObjectType, InMode >::Pin(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::IsPtrValid (const TWeakPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 375 of file TableViewTypeTraits.h.
References TWeakPtr< ObjectType, InMode >::Pin().
MakeNullPtr()
template<typename T> TWeakPtr< T, ESPMode::ThreadSafe > TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::MakeNullPtr () inline static
Definition at line 385 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TWeakPtr< T, ESPMode::ThreadSafe > TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::NullableItemTypeConvertToItemType (const TWeakPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 390 of file TableViewTypeTraits.h.
ResetPtr()
template<typename T> void TListTypeTraits< TWeakPtr< T, ESPMode::ThreadSafe > >::ResetPtr (TWeakPtr< T, ESPMode::ThreadSafe > & InPtr) inline static
Definition at line 380 of file TableViewTypeTraits.h.
The documentation for this struct was generated from the following file:
TableViewTypeTraits.h