Unreal Engine 5.6 C++ API: UE::Geometry::TGeneralPolygon2< T > Class Template Reference
UE::Geometry::TGeneralPolygon2< T > Class Template Reference
TGeneralPolygon2 is a 2D polygon with holes.
#include "GeneralPolygon2.h"
Public Member Functions
TGeneralPolygon2 ()
TGeneralPolygon2 (const TPolygon2< T > &ToSetOuter)
Construct a general polygon with the given polygon as boundary.
bool AddHole (TPolygon2< T > Hole, bool bCheckContainment=true, bool bCheckOrientation=true)
TAxisAlignedBox2< T > Bounds () const
void ClearHoles ()
bool Contains (TPolygon2< T > Poly) const
bool Contains (TVector2< T > vTest) const
double DistanceSquared (TVector2< T > p, int &iHoleIndex, int &iNearSeg, double &fNearSegT) const
void FilterHoles (TFunctionRef< bool(const TPolygon2< T > &)> RemoveHolePredicateFunc)
Remove any Hole polygons for which RemoveHolePredicateFunc(Hole) returns true.
const TArray< TPolygon2< T > > & GetHoles () const
TVector2< T > GetNormal (int iSegment, double segT, int iHoleIndex=-1) const
const TPolygon2< T > & GetOuter () const
TVector2< T > GetSegmentPoint (int iSegment, double fSegT, int iHoleIndex=-1) const
bool HasHoles () const
double HoleUnsignedArea () const
bool Intersects (TPolygon2< T > Poly) const
bool OuterIsClockwise () const
double Perimeter () const
void Reverse ()
void Scale (TVector2< T > scale, TVector2< T > origin)
TSegment2< T > Segment (int iSegment, int iHoleIndex=-1) const
void SetOuter (const TPolygon2< T > &ToSetOuter)
void SetOuterWithOrientation (const TPolygon2< T > &ToSetOuter, bool bToSetOuterIsCW)
double SignedArea () const
void Simplify (double ClusterTol=0.0001, double LineDeviationTol=0.01)
void Transform (const TFunction< TVector2< T >(const TVector2< T > &)> &TransformFunc)
void Translate (TVector2< T > translate)
void VtxNormalOffset (T OffsetDistance, bool bUseFaceAvg=false)
Offset each polygon by the given Distance along vertex "normal" direction (ie for positive offset, outer polygon grows and holes shrink)
Protected Attributes
bool bOuterIsCW
TArray< TPolygon2< T > > Holes
The list of Holes in the polygon.
TPolygon2< T > Outer
Detailed Description
template<typename T>
class UE::Geometry::TGeneralPolygon2< T >
TGeneralPolygon2 is a 2D polygon with holes.
Definition at line 27 of file GeneralPolygon2.h.
Constructor & Destructor Documentation
TGeneralPolygon2() [1/2]
template<typename T> UE::Geometry::TGeneralPolygon2< T >::TGeneralPolygon2 () inline
Definition at line 41 of file GeneralPolygon2.h.
TGeneralPolygon2() [2/2]
template<typename T> UE::Geometry::TGeneralPolygon2< T >::TGeneralPolygon2 (const TPolygon2< T > & ToSetOuter) inline
Construct a general polygon with the given polygon as boundary.
Definition at line 48 of file GeneralPolygon2.h.
Member Function Documentation
AddHole()
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::AddHole (TPolygon2< T > Hole, bool bCheckContainment = true, bool bCheckOrientation = true) inline
Definition at line 77 of file GeneralPolygon2.h.
Referenced by UE::Geometry::TPlanarComplex< double >::ConvertNestToGeneralPolygon(), and UE::Geometry::TPlanarComplex< double >::ConvertOutputToGeneralPolygons().
Bounds()
template<typename T> TAxisAlignedBox2< T > UE::Geometry::TGeneralPolygon2< T >::Bounds () const inline
Definition at line 173 of file GeneralPolygon2.h.
ClearHoles()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::ClearHoles () inline
Definition at line 109 of file GeneralPolygon2.h.
Contains() [1/2]
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::Contains (TPolygon2< T > Poly) const inline
Definition at line 242 of file GeneralPolygon2.h.
Contains() [2/2]
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::Contains (TVector2< T > vTest) const inline
Definition at line 226 of file GeneralPolygon2.h.
DistanceSquared()
template<typename T> double UE::Geometry::TGeneralPolygon2< T >::DistanceSquared (TVector2< T > p, int & iHoleIndex, int & iNearSeg, double & fNearSegT) const inline
Definition at line 303 of file GeneralPolygon2.h.
FilterHoles()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::FilterHoles (TFunctionRef< bool(const TPolygon2< T > &)> RemoveHolePredicateFunc) inline
Remove any Hole polygons for which RemoveHolePredicateFunc(Hole) returns true.
Definition at line 124 of file GeneralPolygon2.h.
GetHoles()
template<typename T> const TArray< TPolygon2< T > > & UE::Geometry::TGeneralPolygon2< T >::GetHoles () const inline
Definition at line 71 of file GeneralPolygon2.h.
Referenced by UE::Geometry::TConstrainedDelaunay2< float >::Add(), and UE::Geometry::FDelaunay2::Triangulate().
GetNormal()
template<typename T> TVector2< T > UE::Geometry::TGeneralPolygon2< T >::GetNormal (int iSegment, double segT, int iHoleIndex = -1) const inline
Definition at line 293 of file GeneralPolygon2.h.
GetOuter()
template<typename T> const TPolygon2< T > & UE::Geometry::TGeneralPolygon2< T >::GetOuter () const inline
Definition at line 66 of file GeneralPolygon2.h.
Referenced by UE::Geometry::TConstrainedDelaunay2< float >::Add(), and UE::Geometry::FDelaunay2::Triangulate().
GetSegmentPoint()
template<typename T> TVector2< T > UE::Geometry::TGeneralPolygon2< T >::GetSegmentPoint (int iSegment, double fSegT, int iHoleIndex = -1) const inline
Definition at line 275 of file GeneralPolygon2.h.
HasHoles()
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::HasHoles () const inline
Definition at line 115 of file GeneralPolygon2.h.
HoleUnsignedArea()
template<typename T> double UE::Geometry::TGeneralPolygon2< T >::HoleUnsignedArea () const inline
Definition at line 151 of file GeneralPolygon2.h.
Intersects()
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::Intersects (TPolygon2< T > Poly) const inline
Definition at line 258 of file GeneralPolygon2.h.
OuterIsClockwise()
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::OuterIsClockwise () const inline
Definition at line 221 of file GeneralPolygon2.h.
Referenced by UE::Geometry::FDelaunay2::Triangulate().
Perimeter()
template<typename T> double UE::Geometry::TGeneralPolygon2< T >::Perimeter () const inline
Definition at line 162 of file GeneralPolygon2.h.
Reverse()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::Reverse () inline
Definition at line 211 of file GeneralPolygon2.h.
Scale()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::Scale (TVector2< T > scale, TVector2< T > origin) inline
Definition at line 194 of file GeneralPolygon2.h.
Segment()
template<typename T> TSegment2< T > UE::Geometry::TGeneralPolygon2< T >::Segment (int iSegment, int iHoleIndex = -1) const inline
Definition at line 284 of file GeneralPolygon2.h.
SetOuter()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::SetOuter (const TPolygon2< T > & ToSetOuter) inline
Definition at line 53 of file GeneralPolygon2.h.
SetOuterWithOrientation()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::SetOuterWithOrientation (const TPolygon2< T > & ToSetOuter, bool bToSetOuterIsCW) inline
Definition at line 59 of file GeneralPolygon2.h.
SignedArea()
template<typename T> double UE::Geometry::TGeneralPolygon2< T >::SignedArea () const inline
Definition at line 139 of file GeneralPolygon2.h.
Simplify()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::Simplify (double ClusterTol = 0.0001, double LineDeviationTol = 0.01) inline
Definition at line 324 of file GeneralPolygon2.h.
Transform()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::Transform (const TFunction< TVector2< T >(const TVector2< T > &)> & TransformFunc) inline
Definition at line 202 of file GeneralPolygon2.h.
Translate()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::Translate (TVector2< T > translate) inline
Definition at line 184 of file GeneralPolygon2.h.
VtxNormalOffset()
template<typename T> void UE::Geometry::TGeneralPolygon2< T >::VtxNormalOffset (T OffsetDistance, bool bUseFaceAvg = false) inline
Offset each polygon by the given Distance along vertex "normal" direction (ie for positive offset, outer polygon grows and holes shrink)
Parameters
OffsetDistance the distance to offset
bUseFaceAvg if true, we offset by the average-face normal instead of the perpendicular-tangent normal
Definition at line 340 of file GeneralPolygon2.h.
Field Documentation
bOuterIsCW
template<typename T> bool UE::Geometry::TGeneralPolygon2< T >::bOuterIsCW protected
Definition at line 34 of file GeneralPolygon2.h.
Holes
template<typename T> TArray<TPolygon2<T> > UE::Geometry::TGeneralPolygon2< T >::Holes protected
The list of Holes in the polygon.
Definition at line 37 of file GeneralPolygon2.h.
Outer
template<typename T> TPolygon2<T> UE::Geometry::TGeneralPolygon2< T >::Outer protected
Definition at line 31 of file GeneralPolygon2.h.
The documentation for this class was generated from the following files:
Delaunay2.h
GeneralPolygon2.h