Unreal Engine 5.6 C++ API: FObjectSubsystemCollection< TBaseType > Class Template Reference
FObjectSubsystemCollection< TBaseType > Class Template Reference
Subsystem collection which delegates UObject references to its owning UObject (object needs to implement AddReferencedObjects and forward call to Collection.
#include "SubsystemCollection.h"
Public Member Functions
FObjectSubsystemCollection ()
Construct a FSubsystemCollection, pass in the owning object almost certainly (this).
void ForEachSubsystem (TFunctionRef< void(TBaseType *)> Operation, const TSubclassOf< TBaseType > &SubsystemClass={}) const
Perform an operation on all subsystems in the collection.
template<typename TSubsystemInterface>
void ForEachSubsystemWithInterface (TFunctionRef< void(TBaseType *)> Operation) const
template<typename TSubsystemClass>
TSubsystemClass * GetSubsystem (const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a Subsystem by type.
template<typename TSubsystemClass>
TArray< TSubsystemClass * > GetSubsystemArrayCopy (const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a list of Subsystems by type.
template<typename TSubsystemClass>
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const TArray< TSubsystemClass * > &GetSubsystemArray(const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a list of Subsystems by type.
Public Member Functions inherited from FSubsystemCollectionBase
void AddReferencedObjects (UObject *Referencer, FReferenceCollector &Collector)
Collect references held by this collection.
void Deinitialize ()
const UClass * GetBaseType () const
Get the collection BaseType.
void Initialize (UObject *NewOuter)
Initialize the collection of systems, systems will be created and initialized.
template<typename TSubsystemClass>
TSubsystemClass * InitializeDependency ()
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
USubsystem * InitializeDependency (TSubclassOf< USubsystem > SubsystemClass)
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
bool IsInitialized () const
Returns true if collection was already initialized.
Additional Inherited Members
Static Public Member Functions inherited from FSubsystemCollectionBase
static void ActivateExternalSubsystem (UClass *SubsystemClass)
Registers and adds instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
static void DeactivateExternalSubsystem (UClass *SubsystemClass)
Unregisters and removed instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
Protected Member Functions inherited from FSubsystemCollectionBase
FSubsystemCollectionBase ()
protected constructor - Use the FSubsystemCollection<TBaseType> class
FSubsystemCollectionBase (UClass *InBaseType)
protected constructor - for use by the template only(FSubsystemCollection<TBaseType>)
virtual ~FSubsystemCollectionBase ()
destructor will be called from virtual ~FGCObject in GC cleanup
FSubsystemArray & FindAndPopulateSubsystemArrayInternal (UClass *SubsystemClass) const
void ForEachSubsystem (TFunctionRef< void(USubsystem *)> Operation) const
Run the given operation on each registered subsystem.
void ForEachSubsystemOfClass (UClass *SubsystemClass, TFunctionRef< void(USubsystem *)> Operation) const
Perform an operation on all subsystems that derive from the given class.
TArray< USubsystem * > GetSubsystemArrayCopy (UClass *SubsystemClass) const
Get a list of Subsystems by type.
USubsystem * GetSubsystemInternal (UClass *SubsystemClass) const
Get a Subsystem by type.
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystemOfClass or GetSubsystemArrayCopy instead") 1 const TArray< USubsystem * > &GetSubsystemArrayInternal(UClass *SubsystemClass) const
Get a list of Subsystems by type.
Detailed Description
template<typename TBaseType>
class FObjectSubsystemCollection< TBaseType >
Subsystem collection which delegates UObject references to its owning UObject (object needs to implement AddReferencedObjects and forward call to Collection.
Definition at line 191 of file SubsystemCollection.h.
Constructor & Destructor Documentation
FObjectSubsystemCollection()
template<typename TBaseType> FObjectSubsystemCollection< TBaseType >::FObjectSubsystemCollection () inline
Construct a FSubsystemCollection, pass in the owning object almost certainly (this).
Definition at line 248 of file SubsystemCollection.h.
References FSubsystemCollectionBase::FSubsystemCollectionBase(), and StaticClass().
Member Function Documentation
ForEachSubsystem()
template<typename TBaseType> void FObjectSubsystemCollection< TBaseType >::ForEachSubsystem (TFunctionRef< void(TBaseType *)> Operation, const TSubclassOf< TBaseType > & SubsystemClass = {}) const inline
Perform an operation on all subsystems in the collection.
Definition at line 228 of file SubsystemCollection.h.
ForEachSubsystemWithInterface()
template<typename TBaseType> template<typename TSubsystemInterface> void FObjectSubsystemCollection< TBaseType >::ForEachSubsystemWithInterface (TFunctionRef< void(TBaseType *)> Operation) const inline
Definition at line 236 of file SubsystemCollection.h.
References CastChecked(), FSubsystemCollectionBase::ForEachSubsystemOfClass(), and MoveTemp().
GetSubsystem()
template<typename TBaseType> template<typename TSubsystemClass> TSubsystemClass * FObjectSubsystemCollection< TBaseType >::GetSubsystem (const TSubclassOf< TSubsystemClass > & SubsystemClass) const inline
Get a Subsystem by type.
Definition at line 196 of file SubsystemCollection.h.
References FSubsystemCollectionBase::GetSubsystemInternal(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
GetSubsystemArrayCopy()
template<typename TBaseType> template<typename TSubsystemClass> TArray< TSubsystemClass * > FObjectSubsystemCollection< TBaseType >::GetSubsystemArrayCopy (const TSubclassOf< TSubsystemClass > & SubsystemClass) const inline
Get a list of Subsystems by type.
Definition at line 218 of file SubsystemCollection.h.
References Array, and FSubsystemCollectionBase::FindAndPopulateSubsystemArrayInternal().
UE_DEPRECATED()
template<typename TBaseType> template<typename TSubsystemClass> FObjectSubsystemCollection< TBaseType >::UE_DEPRECATED (5. 4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const & inline
Get a list of Subsystems by type.
Definition at line 206 of file SubsystemCollection.h.
References Array, and FSubsystemCollectionBase::FindAndPopulateSubsystemArrayInternal().
The documentation for this class was generated from the following file:
SubsystemCollection.h