Unreal Engine 5.6 C++ API: TStringView< CharType > Class Template Reference
TStringView< CharType > Class Template Reference
A string view is a non-owning view of a range of characters.
#include "StringView.h"
Public Types
using ElementType = CharType
using ViewType = TStringView<CharType>
Public Member Functions
constexpr TStringView ()=default
Construct an empty view.
template<typename CharRangeType UE_REQUIRES>
constexpr TStringView (const CharRangeType &InRange UE_LIFETIMEBOUND)
Construct a view from a contiguous range of characters, such as FString or TStringBuilder.
constexpr TStringView (const CharType *InData UE_LIFETIMEBOUND)
Construct a view of the null-terminated string pointed to by InData.
constexpr TStringView (const CharType *InData UE_LIFETIMEBOUND, int32 InSize)
Construct a view of InSize characters beginning at InData.
template<typename OtherCharType UE_REQUIRES>
TStringView (const OtherCharType *InData UE_LIFETIMEBOUND)
Construct a view of the null-terminated string pointed to by InData.
template<typename OtherCharType UE_REQUIRES>
constexpr TStringView (const OtherCharType *InData UE_LIFETIMEBOUND, int32 InSize)
Construct a view of InSize characters beginning at InData.
constexpr const CharType * begin () const
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
template<typename OtherCharType>
int32 Compare (const OtherCharType *Other, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Compare this view with a null-terminated string.
template<typename OtherRangeType, decltype(MakeStringView(DeclVal< OtherRangeType >())) * = nullptr>
int32 Compare (OtherRangeType &&Other, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Compare this view with a character range.
template<typename OtherCharType UE_REQUIRES>
int32 Compare (TStringView< OtherCharType > Other, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Compare this view with a string view.
bool Contains (ViewType Search, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Returns whether this view contains the specified substring.
int32 CopyString (CharType *Dest, int32 CharCount, int32 Position=0) const
Copy characters from the view into a destination buffer without null termination.
constexpr const CharType * end () const
bool EndsWith (CharType Suffix) const
Returns whether this view ends with the suffix character compared case-sensitively.
bool EndsWith (ViewType Suffix, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase) const
Returns whether this view ends with the suffix with optional case sensitivity.
template<typename OtherCharType UE_REQUIRES>
bool Equals (const OtherCharType *Other, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Check whether this view is equivalent to a string view.
template<typename OtherRangeType, decltype(MakeStringView(DeclVal< OtherRangeType >())) * = nullptr>
bool Equals (OtherRangeType &&Other, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Check whether this view is equivalent to a character range.
int32 Find (ViewType Search, int32 StartPosition=0, ESearchCase::Type SearchCase=ESearchCase::CaseSensitive) const
Search the view for the first occurrence of a search string.
bool FindChar (CharType Search, int32 &OutIndex) const
Search the view for the first occurrence of a character.
bool FindLastChar (CharType Search, int32 &OutIndex) const
Search the view for the last occurrence of a character.
constexpr const CharType * GetData () const
Returns a pointer to the start of the view.
constexpr bool IsEmpty () const
Returns whether the string view is empty.
FORCEINLINE bool IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
ViewType Left (int32 CharCount) const
Returns the left-most part of the view by taking the given number of characters from the left.
ViewType LeftChop (int32 CharCount) const
Returns the left-most part of the view by chopping the given number of characters from the right.
void LeftChopInline (int32 CharCount)
Modifies the view by chopping the given number of characters from the right.
void LeftInline (int32 CharCount)
Modifies the view to be the given number of characters from the left.
constexpr int32 Len () const
Returns the length of the string view.
ViewType Mid (int32 Position, int32 CharCount=MAX_int32) const
Returns the middle part of the view by taking up to the given number of characters from the given position.
void MidInline (int32 Position, int32 CharCount=MAX_int32)
Modifies the view to be the middle part by taking up to the given number of characters from the given position.
constexpr SIZE_T NumBytes () const
const CharType & operator[] (int32 Index) const
Access the character at the given index in the view.
constexpr TReversePointerIterator< const CharType > rbegin () const
void RemovePrefix (int32 CharCount)
Modifies the view to remove the given number of characters from the start.
void RemoveSuffix (int32 CharCount)
Modifies the view to remove the given number of characters from the end.
constexpr TReversePointerIterator< const CharType > rend () const
void Reset ()
Resets to an empty view.
ViewType Right (int32 CharCount) const
Returns the right-most part of the view by taking the given number of characters from the right.
ViewType RightChop (int32 CharCount) const
Returns the right-most part of the view by chopping the given number of characters from the left.
void RightChopInline (int32 CharCount)
Modifies the view by chopping the given number of characters from the left.
void RightInline (int32 CharCount)
Modifies the view to be the given number of characters from the right.
bool StartsWith (CharType Prefix) const
Returns whether this view starts with the prefix character compared case-sensitively.
bool StartsWith (ViewType Prefix, ESearchCase::Type SearchCase=ESearchCase::IgnoreCase) const
Returns whether this view starts with the prefix with optional case sensitivity.
ViewType SubStr (int32 Position, int32 CharCount) const
Alias for Mid.
ViewType TrimEnd () const
Returns the left part of the view before any whitespace at the end.
void TrimEndInline ()
Modifies the view to be the left part before any whitespace at the end.
ViewType TrimStart () const
Returns the right part of the view after any whitespace at the start.
ViewType TrimStartAndEnd () const
Returns the middle part of the view between any whitespace at the start and end.
void TrimStartAndEndInline ()
Modifies the view to be the middle part between any whitespace at the start and end.
void TrimStartInline ()
Modifies the view to be the right part after any whitespace at the start.
Protected Attributes
const CharType * DataPtr = nullptr
int32 Size = 0
Private Member Functions
template<typename OtherCharType>
int32 PrivateCompare (TStringView< OtherCharType > Other, ESearchCase::Type SearchCase) const
template<typename OtherCharType>
bool PrivateEquals (const OtherCharType *Other, ESearchCase::Type SearchCase) const
Static Private Member Functions
static bool PrivateEquals (TStringView Lhs, const CharType *Rhs)
static bool PrivateEquals (TStringView Lhs, TStringView Rhs)
static bool PrivateLess (TStringView Lhs, TStringView Rhs)
Friends
constexpr auto GetNum (TStringView String)
uint32 GetTypeHash (TStringView View)
Case insensitive string hash function.
template<typename CharRangeType UE_REQUIRES>
auto operator!= (CharRangeType &&Lhs, TStringView Rhs)
bool operator!= (const CharType *Lhs, TStringView Rhs)
template<typename CharRangeType UE_REQUIRES>
auto operator!= (TStringView Lhs, CharRangeType &&Rhs)
bool operator!= (TStringView Lhs, const CharType *Rhs)
bool operator!= (TStringView Lhs, TStringView Rhs)
template<typename CharRangeType UE_REQUIRES>
auto operator< (CharRangeType &&Lhs, TStringView Rhs)
template<typename CharRangeType UE_REQUIRES>
auto operator< (TStringView Lhs, CharRangeType &&Rhs)
bool operator< (TStringView Lhs, TStringView Rhs)
template<typename CharRangeType UE_REQUIRES>
auto operator== (CharRangeType &&Lhs, TStringView Rhs)
bool operator== (const CharType *Lhs, TStringView Rhs)
template<typename CharRangeType UE_REQUIRES>
auto operator== (TStringView Lhs, CharRangeType &&Rhs)
bool operator== (TStringView Lhs, const CharType *Rhs)
bool operator== (TStringView Lhs, TStringView Rhs)
Detailed Description
template<typename CharType>
class TStringView< CharType >
A string view is a non-owning view of a range of characters.
Ensure that the underlying string is valid for the lifetime of the string view.
Be careful when constructing a string view from a temporary. Make a local copy if necessary.
FStringView View = Object->GetPathName(); // Invalid
FString PathName = Object->GetPathName(); // Valid FStringView View = PathName;
void ProcessPath(FStringView Path); // Valid ProcessPath(Object->GetPathName());
A string view is implicitly constructible from null-terminated strings, from contiguous ranges of characters such as FString and TStringBuilder, and from literals such as TEXTVIEW("...").
A string view is cheap to copy and is meant to be passed by value. Avoid passing by reference.
A string view is not guaranteed to represent a null-terminated string.
Log or format a string view using UE_LOG(TEXT("%.*s"), View.Len(), View.GetData());
A string view is a good fit for function parameters where the function has no requirements for how the string is stored. A caller may use FString, FStringView, TStringBuilder, a char array, a null-terminated string, or any other type which can convert to a string view.
The UE::String namespace contains many functions that can operate on string views. Most of these functions can be found in String/___.h in Core.
void UseString(FStringView InString);
FString String(TEXT("ABC"));
const TCHAR* CString = *String;
TStringBuilder<16> StringBuilder;
StringBuilder.Append(TEXT("ABC"));
UseString(String);
UseString(CString);
UseString(StringBuilder);
UseString(TEXT("ABC"));
UseString(TEXTVIEW("ABC"));
Definition at line 93 of file StringView.h.
Member Typedef Documentation
ElementType
template<typename CharType> using TStringView< CharType >::ElementType = CharType
Definition at line 96 of file StringView.h.
ViewType
template<typename CharType> using TStringView< CharType >::ViewType = TStringView<CharType>
Definition at line 97 of file StringView.h.
Constructor & Destructor Documentation
TStringView() [1/6]
template<typename CharType> TStringView< CharType >::TStringView () nodiscard constexpr default
Construct an empty view.
Referenced by Left(), LeftChop(), Mid(), PrivateCompare(), PrivateEquals(), PrivateEquals(), PrivateLess(), Right(), RightChop(), TrimEnd(), TrimStart(), and TrimStartAndEnd().
TStringView() [2/6]
template<typename CharType> TStringView< CharType >::TStringView (const CharType *InData UE_LIFETIMEBOUND) inline nodiscard constexpr
Construct a view of the null-terminated string pointed to by InData.
Definition at line 104 of file StringView.h.
TStringView() [3/6]
template<typename CharType> TStringView< CharType >::TStringView (const CharType *InData UE_LIFETIMEBOUND, int32 InSize) inline nodiscard constexpr
Construct a view of InSize characters beginning at InData.
Definition at line 111 of file StringView.h.
TStringView() [4/6]
template<typename CharType> template<typename OtherCharType UE_REQUIRES> TStringView< CharType >::TStringView (const OtherCharType *InData UE_LIFETIMEBOUND) inline nodiscard
Construct a view of the null-terminated string pointed to by InData.
Definition at line 127 of file StringView.h.
TStringView() [5/6]
template<typename CharType> template<typename OtherCharType UE_REQUIRES> TStringView< CharType >::TStringView (const OtherCharType *InData UE_LIFETIMEBOUND, int32 InSize) inline nodiscard constexpr
Construct a view of InSize characters beginning at InData.
Definition at line 143 of file StringView.h.
TStringView() [6/6]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> TStringView< CharType >::TStringView (const CharRangeType &InRange UE_LIFETIMEBOUND) inline nodiscard constexpr
Construct a view from a contiguous range of characters, such as FString or TStringBuilder.
Definition at line 162 of file StringView.h.
Member Function Documentation
begin()
template<typename CharType> const CharType * TStringView< CharType >::begin () const inline nodiscard constexpr
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 559 of file StringView.h.
Compare() [1/3]
template<typename CharType> template<typename OtherCharType> int32 TStringView< CharType >::Compare (const OtherCharType * Other, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Compare this view with a null-terminated string.
Parameters
Other A null-terminated string that is comparable with the character type of this view.
SearchCase Whether the comparison should ignore case.
Returns
0 is equal, negative if this view is less, positive if this view is greater.
Definition at line 777 of file StringView.h.
References ESearchCase::CaseSensitive, GetData(), IsEmpty(), Len(), Other, FAndroidPlatformString::Strncmp(), and FGenericPlatformStricmp::Strnicmp().
Compare() [2/3]
template<typename CharType> template<typename OtherRangeType, decltype(MakeStringView(DeclVal< OtherRangeType >())) * = nullptr> int32 TStringView< CharType >::Compare (OtherRangeType && Other, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Compare this view with a character range.
Parameters
Other A character range that is comparable with the character type of this view.
SearchCase Whether the comparison should ignore case.
Returns
0 is equal, negative if this view is less, positive if this view is greater.
Definition at line 346 of file StringView.h.
Referenced by TStringView< TCHAR >::Compare(), TStringView< TCHAR >::Equals(), TStringView< TCHAR >::operator<, and PrivateLess().
Compare() [3/3]
template<typename CharType> template<typename OtherCharType UE_REQUIRES> int32 TStringView< CharType >::Compare (TStringView< OtherCharType > Other, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Compare this view with a string view.
Parameters
Other A string view that is comparable with the character type of this view.
SearchCase Whether the comparison should ignore case.
Returns
0 is equal, negative if this view is less, positive if this view is greater.
Definition at line 362 of file StringView.h.
Contains()
template<typename CharType> bool TStringView< CharType >::Contains (ViewType Search, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Returns whether this view contains the specified substring.
Parameters
Search Text to search for
SearchCase Indicates whether the search is case sensitive or not
Returns
True if the view contains the search string, otherwise false.
Definition at line 406 of file StringView.h.
CopyString()
template<typename CharType> int32 TStringView< CharType >::CopyString (CharType * Dest, int32 CharCount, int32 Position = 0) const inline
Copy characters from the view into a destination buffer without null termination.
Parameters
Dest Buffer to write into. Must have space for at least CharCount characters.
CharCount The maximum number of characters to copy.
Position The offset into the view from which to start copying.
Returns
The number of characters written to the destination buffer.
Definition at line 639 of file StringView.h.
References DataPtr, FMemory::Memcpy(), FMath::Min, Position, and Size.
Referenced by TStringBuilderBase< TCHAR >::ReplaceAt().
end()
template<typename CharType> const CharType * TStringView< CharType >::end () const inline nodiscard constexpr
Definition at line 560 of file StringView.h.
EndsWith() [1/2]
template<typename CharType> bool TStringView< CharType >::EndsWith (CharType Suffix) const inline nodiscard
Returns whether this view ends with the suffix character compared case-sensitively.
Definition at line 383 of file StringView.h.
Referenced by UE::String::RemoveFromEnd().
EndsWith() [2/2]
template<typename CharType> bool TStringView< CharType >::EndsWith (ViewType Suffix, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase) const inline nodiscard
Returns whether this view ends with the suffix with optional case sensitivity.
Definition at line 810 of file StringView.h.
References Equals(), Len(), and Right.
Equals() [1/2]
template<typename CharType> template<typename OtherCharType UE_REQUIRES> bool TStringView< CharType >::Equals (const OtherCharType * Other, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Check whether this view is equivalent to a string view.
Parameters
Other A string that is comparable with the character type of this view.
SearchCase Whether the comparison should ignore case.
Definition at line 333 of file StringView.h.
Equals() [2/2]
template<typename CharType> template<typename OtherRangeType, decltype(MakeStringView(DeclVal< OtherRangeType >())) * = nullptr> bool TStringView< CharType >::Equals (OtherRangeType && Other, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Check whether this view is equivalent to a character range.
Parameters
Other A character range that is comparable with the character type of this view.
SearchCase Whether the comparison should ignore case.
Definition at line 317 of file StringView.h.
Referenced by FAssetData::DetectIsUAssetByNames(), EndsWith(), TDirectoryTree< ValueType >::FTreeNode::FindOrAdd(), TStringView< TCHAR >::operator==, PrivateEquals(), PrivateEquals(), and StartsWith().
Find()
template<typename CharType> int32 TStringView< CharType >::Find (ViewType Search, int32 StartPosition = 0, ESearchCase::Type SearchCase = ESearchCase::CaseSensitive) const inline nodiscard
Search the view for the first occurrence of a search string.
Parameters
Search The string to search for. Comparison is lexicographic.
StartPosition The character position to start searching from.
SearchCase Indicates whether the search is case sensitive or not
Returns
The index of the first occurrence of the search string if found, otherwise INDEX_NONE.
Definition at line 816 of file StringView.h.
References UE::String::FindFirst(), INDEX_NONE, and RightChop.
FindChar()
template<typename CharType> bool TStringView< CharType >::FindChar (CharType Search, int32 & OutIndex) const inline
Search the view for the first occurrence of a character.
Parameters
Search The character to search for. Comparison is lexicographic.
OutIndex [out] The position at which the character was found, or INDEX_NONE if not found.
Returns
True if the character was found in the view, otherwise false.
Definition at line 823 of file StringView.h.
References UE::String::FindFirstChar(), and INDEX_NONE.
Referenced by Verse::Names::RemoveQualifier(), and Verse::Names::RemoveQualifier().
FindLastChar()
template<typename CharType> bool TStringView< CharType >::FindLastChar (CharType Search, int32 & OutIndex) const inline
Search the view for the last occurrence of a character.
Parameters
Search The character to search for. Comparison is lexicographic.
OutIndex [out] The position at which the character was found, or INDEX_NONE if not found.
Returns
True if the character was found in the view, otherwise false.
Definition at line 830 of file StringView.h.
References UE::String::FindLastChar(), and INDEX_NONE.
GetData()
template<typename CharType> const CharType * TStringView< CharType >::GetData () const inline nodiscard constexpr
Returns a pointer to the start of the view.
This is NOT guaranteed to be null-terminated!
Definition at line 172 of file StringView.h.
Referenced by FName::FName(), FName::FName(), FName::FName(), FName::FName(), FName::FName(), FName::FName(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), TStringBuilderBase< TCHAR >::Append(), TDirectoryTree< ValueType >::FTreeNode::ContainsChildPaths(), TDirectoryTree< ValueType >::FTreeNode::FindOrAdd(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GetGroupName(), TStringView< TCHAR >::GetTypeHash, TextKeyUtil::HashString(), TextKeyUtil::HashString(), UE::CurveEditor::MakeResizeParams(), PrivateCompare(), UE::UnifiedError::FErrorRegistry::RegisterModule(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().
IsEmpty()
template<typename CharType> bool TStringView< CharType >::IsEmpty () const inline nodiscard constexpr
Returns whether the string view is empty.
Definition at line 192 of file StringView.h.
Referenced by Compare(), TDirectoryTree< ValueType >::FTreeNode::ContainsChildPaths(), TDirectoryTree< ValueType >::FTreeNode::Find(), TDirectoryTree< ValueType >::FTreeNode::FindOrAdd(), TDirectoryTree< ValueType >::FIteratorInternal::operator++(), PrivateEquals(), TDirectoryTree< ValueType >::FTreeNode::Remove(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), TDirectoryTree< ValueType >::FTreeNode::TryFindClosestPath(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().
IsValidIndex()
template<typename CharType> FORCEINLINE bool TStringView< CharType >::IsValidIndex (int32 Index) const inline nodiscard
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of characters in the string view.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 436 of file StringView.h.
Left()
template<typename CharType> TStringView< CharType > TStringView< CharType >::Left (int32 CharCount) const inline nodiscard
Returns the left-most part of the view by taking the given number of characters from the left.
Definition at line 647 of file StringView.h.
References TStringView(), FMath::Clamp(), DataPtr, and Size.
LeftChop()
template<typename CharType> TStringView< CharType > TStringView< CharType >::LeftChop (int32 CharCount) const inline nodiscard
Returns the left-most part of the view by chopping the given number of characters from the right.
Definition at line 653 of file StringView.h.
References TStringView(), FMath::Clamp(), DataPtr, and Size.
Referenced by UE::String::RemoveFromEnd().
LeftChopInline()
template<typename CharType> void TStringView< CharType >::LeftChopInline (int32 CharCount) inline
Modifies the view by chopping the given number of characters from the right.
Definition at line 267 of file StringView.h.
LeftInline()
template<typename CharType> void TStringView< CharType >::LeftInline (int32 CharCount) inline
Modifies the view to be the given number of characters from the left.
Definition at line 261 of file StringView.h.
Len()
template<typename CharType> int32 TStringView< CharType >::Len () const inline nodiscard constexpr
Returns the length of the string view.
Definition at line 186 of file StringView.h.
Referenced by FBlake3Hash::FBlake3Hash(), FBlake3Hash::FBlake3Hash(), FBlake3Hash::FBlake3Hash(), FIoHash::FIoHash(), FIoHash::FIoHash(), FIoHash::FIoHash(), FName::FName(), FName::FName(), FName::FName(), FName::FName(), FName::FName(), FName::FName(), FShaderParameterParser::FPlatformConfiguration::FPlatformConfiguration(), TStringBuilderBase< TCHAR >::Append(), Compare(), TDirectoryTree< ValueType >::FTreeNode::ContainsChildPaths(), EndsWith(), TStringView< TCHAR >::Equals(), TDirectoryTree< ValueType >::FTreeNode::FindOrAdd(), FSHAHash::FromString(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GetGroupName(), TStringView< TCHAR >::GetTypeHash, TextKeyUtil::HashString(), TextKeyUtil::HashString(), TStringView< TCHAR >::IsValidIndex(), Mid(), PrivateCompare(), PrivateEquals(), UE::String::RemoveFromEnd(), UE::String::RemoveFromStart(), TStringBuilderBase< TCHAR >::ReplaceAt(), StartsWith(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().
Mid()
template<typename CharType> TStringView< CharType > TStringView< CharType >::Mid (int32 Position, int32 CharCount = MAX_int32) const inline nodiscard
Returns the middle part of the view by taking up to the given number of characters from the given position.
Definition at line 673 of file StringView.h.
References TStringView(), FMath::Clamp(), GetData(), Len(), and Position.
Referenced by TStringView< TCHAR >::MidInline(), and TStringView< TCHAR >::SubStr().
MidInline()
template<typename CharType> void TStringView< CharType >::MidInline (int32 Position, int32 CharCount = MAX_int32) inline
Modifies the view to be the middle part by taking up to the given number of characters from the given position.
Definition at line 285 of file StringView.h.
NumBytes()
template<typename CharType> SIZE_T TStringView< CharType >::NumBytes () const inline nodiscard constexpr
Returns
Number of bytes used for the characters in the string view
Definition at line 180 of file StringView.h.
operator[]()
template<typename CharType> const CharType & TStringView< CharType >::operator[] (int32 Index) const inline nodiscard
Access the character at the given index in the view.
Definition at line 632 of file StringView.h.
References checkf, DataPtr, Size, and TEXT.
PrivateCompare()
template<typename CharType> template<typename OtherCharType> int32 TStringView< CharType >::PrivateCompare (TStringView< OtherCharType > Other, ESearchCase::Type SearchCase) const inline nodiscard private
Definition at line 746 of file StringView.h.
References TStringView(), ESearchCase::CaseSensitive, GetData(), GetData(), Len(), FMath::Min, FAndroidPlatformString::Strncmp(), and FGenericPlatformStricmp::Strnicmp().
Referenced by TStringView< TCHAR >::Compare().
PrivateEquals() [1/3]
template<typename CharType> template<typename OtherCharType> bool TStringView< CharType >::PrivateEquals (const OtherCharType * Other, ESearchCase::Type SearchCase) const inline nodiscard private
Definition at line 727 of file StringView.h.
References ESearchCase::CaseSensitive, GetData(), IsEmpty(), Len(), Other, FAndroidPlatformString::Strncmp(), and FGenericPlatformStricmp::Strnicmp().
PrivateEquals() [2/3]
template<typename CharType> bool TStringView< CharType >::PrivateEquals (TStringView< CharType > Lhs, const CharType * Rhs) inline static nodiscard private
Definition at line 837 of file StringView.h.
References TStringView(), Equals(), and ESearchCase::IgnoreCase.
Referenced by TStringView< TCHAR >::Equals(), TStringView< TCHAR >::operator!=, TStringView< TCHAR >::operator!=, TStringView< TCHAR >::operator==, TStringView< TCHAR >::operator==, and TStringView< TCHAR >::operator==.
PrivateEquals() [3/3]
template<typename CharType> bool TStringView< CharType >::PrivateEquals (TStringView< CharType > Lhs, TStringView< CharType > Rhs) inline static nodiscard private
Definition at line 843 of file StringView.h.
References TStringView(), Equals(), and ESearchCase::IgnoreCase.
PrivateLess()
template<typename CharType> bool TStringView< CharType >::PrivateLess (TStringView< CharType > Lhs, TStringView< CharType > Rhs) inline static nodiscard private
Definition at line 849 of file StringView.h.
References TStringView(), Compare(), and ESearchCase::IgnoreCase.
Referenced by TStringView< TCHAR >::operator<, and TStringView< TCHAR >::operator<.
rbegin()
template<typename CharType> TReversePointerIterator< const CharType > TStringView< CharType >::rbegin () const inline nodiscard constexpr
Definition at line 561 of file StringView.h.
RemovePrefix()
template<typename CharType> void TStringView< CharType >::RemovePrefix (int32 CharCount) inline
Modifies the view to remove the given number of characters from the start.
Definition at line 200 of file StringView.h.
Referenced by Verse::Names::RemoveQualifier(), and Verse::Names::RemoveQualifier().
RemoveSuffix()
template<typename CharType> void TStringView< CharType >::RemoveSuffix (int32 CharCount) inline
Modifies the view to remove the given number of characters from the end.
Definition at line 206 of file StringView.h.
rend()
template<typename CharType> TReversePointerIterator< const CharType > TStringView< CharType >::rend () const inline nodiscard constexpr
Definition at line 562 of file StringView.h.
Reset()
template<typename CharType> void TStringView< CharType >::Reset () inline
Resets to an empty view.
Definition at line 211 of file StringView.h.
Right()
template<typename CharType> TStringView< CharType > TStringView< CharType >::Right (int32 CharCount) const inline nodiscard
Returns the right-most part of the view by taking the given number of characters from the right.
Definition at line 659 of file StringView.h.
References TStringView(), FMath::Clamp(), DataPtr, and Size.
RightChop()
template<typename CharType> TStringView< CharType > TStringView< CharType >::RightChop (int32 CharCount) const inline nodiscard
Returns the right-most part of the view by chopping the given number of characters from the left.
Definition at line 666 of file StringView.h.
References TStringView(), FMath::Clamp(), DataPtr, and Size.
Referenced by UE::String::RemoveFromStart().
RightChopInline()
template<typename CharType> void TStringView< CharType >::RightChopInline (int32 CharCount) inline
Modifies the view by chopping the given number of characters from the left.
Definition at line 279 of file StringView.h.
RightInline()
template<typename CharType> void TStringView< CharType >::RightInline (int32 CharCount) inline
Modifies the view to be the given number of characters from the right.
Definition at line 273 of file StringView.h.
StartsWith() [1/2]
template<typename CharType> bool TStringView< CharType >::StartsWith (CharType Prefix) const inline nodiscard
Returns whether this view starts with the prefix character compared case-sensitively.
Definition at line 378 of file StringView.h.
Referenced by UE::String::RemoveFromStart().
StartsWith() [2/2]
template<typename CharType> bool TStringView< CharType >::StartsWith (ViewType Prefix, ESearchCase::Type SearchCase = ESearchCase::IgnoreCase) const inline nodiscard
Returns whether this view starts with the prefix with optional case sensitivity.
Definition at line 804 of file StringView.h.
References Equals(), Left, and Len().
SubStr()
template<typename CharType> ViewType TStringView< CharType >::SubStr (int32 Position, int32 CharCount) const inline nodiscard
Alias for Mid.
Definition at line 231 of file StringView.h.
TrimEnd()
template<typename CharType> TStringView< CharType > TStringView< CharType >::TrimEnd () const inline nodiscard
Returns the left part of the view before any whitespace at the end.
Definition at line 715 of file StringView.h.
References TStringView(), DataPtr, TChar< CharType >::IsWhitespace(), and Size.
Referenced by TStringView< TCHAR >::TrimEndInline().
TrimEndInline()
template<typename CharType> void TStringView< CharType >::TrimEndInline () inline
Modifies the view to be the left part before any whitespace at the end.
Definition at line 303 of file StringView.h.
TrimStart()
template<typename CharType> TStringView< CharType > TStringView< CharType >::TrimStart () const inline nodiscard
Returns the right part of the view after any whitespace at the start.
Definition at line 700 of file StringView.h.
References TStringView(), DataPtr, TChar< CharType >::IsWhitespace(), and Size.
Referenced by TrimStartAndEnd(), and TStringView< TCHAR >::TrimStartInline().
TrimStartAndEnd()
template<typename CharType> TStringView< CharType > TStringView< CharType >::TrimStartAndEnd () const inline nodiscard
Returns the middle part of the view between any whitespace at the start and end.
Definition at line 694 of file StringView.h.
References TStringView(), and TrimStart().
Referenced by TStringView< TCHAR >::TrimStartAndEndInline().
TrimStartAndEndInline()
template<typename CharType> void TStringView< CharType >::TrimStartAndEndInline () inline
Modifies the view to be the middle part between any whitespace at the start and end.
Definition at line 291 of file StringView.h.
TrimStartInline()
template<typename CharType> void TStringView< CharType >::TrimStartInline () inline
Modifies the view to be the right part after any whitespace at the start.
Definition at line 297 of file StringView.h.
Friends And Related Symbol Documentation
GetNum
template<typename CharType> auto GetNum (TStringView< CharType > String) friend
Definition at line 453 of file StringView.h.
GetTypeHash
template<typename CharType> uint32 GetTypeHash (TStringView< CharType > View) friend
Case insensitive string hash function.
Definition at line 459 of file StringView.h.
operator!= [1/5]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator!= (CharRangeType && Lhs, TStringView< CharType > Rhs) friend
Definition at line 511 of file StringView.h.
operator!= [2/5]
template<typename CharType> bool operator!= (const CharType * Lhs, TStringView< CharType > Rhs) friend
Definition at line 549 of file StringView.h.
operator!= [3/5]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator!= (TStringView< CharType > Lhs, CharRangeType && Rhs) friend
Definition at line 502 of file StringView.h.
operator!= [4/5]
template<typename CharType> bool operator!= (TStringView< CharType > Lhs, const CharType * Rhs) friend
Definition at line 544 of file StringView.h.
operator!= [5/5]
template<typename CharType> bool operator!= (TStringView< CharType > Lhs, TStringView< CharType > Rhs) friend
Definition at line 470 of file StringView.h.
operator< [1/3]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator< (CharRangeType && Lhs, TStringView< CharType > Rhs) friend
Definition at line 529 of file StringView.h.
operator< [2/3]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator< (TStringView< CharType > Lhs, CharRangeType && Rhs) friend
Definition at line 520 of file StringView.h.
operator< [3/3]
template<typename CharType> bool operator< (TStringView< CharType > Lhs, TStringView< CharType > Rhs) friend
Definition at line 475 of file StringView.h.
operator== [1/5]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator== (CharRangeType && Lhs, TStringView< CharType > Rhs) friend
Definition at line 493 of file StringView.h.
operator== [2/5]
template<typename CharType> bool operator== (const CharType * Lhs, TStringView< CharType > Rhs) friend
Definition at line 539 of file StringView.h.
operator== [3/5]
template<typename CharType> template<typename CharRangeType UE_REQUIRES> auto operator== (TStringView< CharType > Lhs, CharRangeType && Rhs) friend
Definition at line 484 of file StringView.h.
operator== [4/5]
template<typename CharType> bool operator== (TStringView< CharType > Lhs, const CharType * Rhs) friend
Definition at line 534 of file StringView.h.
operator== [5/5]
template<typename CharType> bool operator== (TStringView< CharType > Lhs, TStringView< CharType > Rhs) friend
Definition at line 465 of file StringView.h.
Field Documentation
DataPtr
template<typename CharType> const CharType* TStringView< CharType >::DataPtr = nullptr protected
Definition at line 565 of file StringView.h.
Referenced by CopyString(), Left(), LeftChop(), operator[](), Right(), RightChop(), TrimEnd(), and TrimStart().
Size
template<typename CharType> int32 TStringView< CharType >::Size = 0 protected
Definition at line 566 of file StringView.h.
Referenced by CopyString(), Left(), LeftChop(), operator[](), Right(), RightChop(), TrimEnd(), and TrimStart().
The documentation for this class was generated from the following files:
StringFwd.h
StringView.h