Unreal Engine 5.6 C++ API: TSoftObjectPtr< T > Struct Template Reference
TSoftObjectPtr< T > Struct Template Reference
TSoftObjectPtr is templatized wrapper of the generic FSoftObjectPtr, it can be used in UProperties.
#include "SoftObjectPtr.h"
Public Types
using ElementType = T
Public Member Functions
FORCEINLINE TSoftObjectPtr ()=default
template<typename U UE_REQUIRES>
FORCEINLINE TSoftObjectPtr (const TObjectPtr< U > Object)
Construct from a TObjectPtr which may or may not be in memory.
FORCEINLINE TSoftObjectPtr (const TSoftObjectPtr &Other)=default
template<class U UE_REQUIRES>
FORCEINLINE TSoftObjectPtr (const TSoftObjectPtr< U > &Other)
Construct from another soft pointer.
template<typename SoftObjectPathType UE_REQUIRES>
FORCEINLINE TSoftObjectPtr (SoftObjectPathType ObjectPath)
Construct from a soft object path.
FORCEINLINE TSoftObjectPtr (TSoftObjectPtr &&Other)=default
template<class U UE_REQUIRES>
FORCEINLINE TSoftObjectPtr (TSoftObjectPtr< U > &&Other)
Construct from a moveable soft pointer.
FORCEINLINE TSoftObjectPtr (TYPE_OF_NULLPTR)
Construct from a nullptr.
template<typename U UE_REQUIRES>
FORCEINLINE TSoftObjectPtr (U *Object)
Construct from an object already in memory.
FORCEINLINE ~TSoftObjectPtr ()=default
FORCEINLINE FString GetAssetName () const
Returns assetname string, leaving off the /package/path part.
FORCEINLINE FName GetLongPackageFName () const
Returns /package/path name, leaving off the asset name.
FORCEINLINE FString GetLongPackageName () const
Returns /package/path string, leaving off the asset name.
FORCEINLINE uint32 GetPtrTypeHash () const
Hash function.
FORCEINLINE const FSoftObjectPath & GetUniqueID () const
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
int32 LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams=FLoadAssetAsyncOptionalParams()) const
Attempts to asynchronously load the object referenced by this soft pointer.
T * LoadSynchronous () const
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
FORCEINLINE operator bool () const
Dereference soft pointer to see if it points somewhere valid.
FORCEINLINE T & operator* () const
Dereference the soft pointer.
FORCEINLINE T * operator-> () const
Dereference the soft pointer.
FORCEINLINE TSoftObjectPtr & operator= (const TSoftObjectPtr &Other)=default
FORCEINLINE TSoftObjectPtr & operator= (TSoftObjectPtr &&Other)=default
template<typename U UE_REQUIRES>
FORCEINLINE TSoftObjectPtr & operator= (U *Object)
Copy from an object already in memory.
FORCEINLINE void Reset ()
Reset the soft pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
FORCEINLINE void Serialize (FArchive &Ar)
FORCEINLINE const FSoftObjectPath & ToSoftObjectPath () const
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
FORCEINLINE FString ToString () const
Returns string representation of reference, in form /package/path.assetname.
template<typename U UE_REQUIRES>
UE_DEPRECATED (5.5, "Assigning TSoftObjectPtr from an incompatible pointer type has been deprecated.") FORCEINLINE TSoftObjectPtr &operator
UE_DEPRECATED (5.5, "Constructing TSoftObjectPtr from an FString has been deprecated - instead, explicitly construct a FSoftObjectPath.") explicit TSoftObjectPtr(const FString &Path)
template<typename U UE_REQUIRES>
UE_DEPRECATED (5.5, "Constructing TSoftObjectPtr from an incompatible pointer type has been deprecated.") FORCEINLINE TSoftObjectPtr(const TObjectPtr< U > Object)
template<class U UE_REQUIRES>
UE_DEPRECATED (5.5, "Constructing TSoftObjectPtr from an incompatible pointer type has been deprecated.") FORCEINLINE TSoftObjectPtr(const TSoftObjectPtr< U > &Other)
template<class U UE_REQUIRES>
UE_DEPRECATED (5.5, "Constructing TSoftObjectPtr from an incompatible pointer type has been deprecated.") FORCEINLINE TSoftObjectPtr(TSoftObjectPtr< U > &&Other)
template<typename U UE_REQUIRES>
UE_DEPRECATED (5.5, "Constructing TSoftObjectPtr from an incompatible pointer type has been deprecated.") FORCEINLINE TSoftObjectPtr(U *Object)
Private Attributes
FSoftObjectPtr SoftObjectPtr
Friends
template<class U>
struct TSoftObjectPtr
Detailed Description
template<class T = UObject>
struct TSoftObjectPtr< T >
TSoftObjectPtr is templatized wrapper of the generic FSoftObjectPtr, it can be used in UProperties.
Definition at line 173 of file SoftObjectPtr.h.
Member Typedef Documentation
ElementType
template<class T = UObject> using TSoftObjectPtr< T >::ElementType = T
Definition at line 179 of file SoftObjectPtr.h.
Constructor & Destructor Documentation
TSoftObjectPtr() [1/9]
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr () nodiscard default
TSoftObjectPtr() [2/9]
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (const TSoftObjectPtr< T > & Other) nodiscard default
TSoftObjectPtr() [3/9]
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (TSoftObjectPtr< T > && Other) nodiscard default
~TSoftObjectPtr()
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::~TSoftObjectPtr () default
TSoftObjectPtr() [4/9]
template<class T = UObject> template<class U UE_REQUIRES> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (const TSoftObjectPtr< U > & Other) inline nodiscard
Construct from another soft pointer.
Definition at line 193 of file SoftObjectPtr.h.
TSoftObjectPtr() [5/9]
template<class T = UObject> template<class U UE_REQUIRES> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (TSoftObjectPtr< U > && Other) inline nodiscard
Construct from a moveable soft pointer.
Definition at line 212 of file SoftObjectPtr.h.
TSoftObjectPtr() [6/9]
template<class T = UObject> template<typename U UE_REQUIRES> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (U * Object) inline nodiscard
Construct from an object already in memory.
Definition at line 231 of file SoftObjectPtr.h.
TSoftObjectPtr() [7/9]
template<class T = UObject> template<typename U UE_REQUIRES> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (const TObjectPtr< U > Object) inline nodiscard
Construct from a TObjectPtr which may or may not be in memory.
Definition at line 271 of file SoftObjectPtr.h.
TSoftObjectPtr() [8/9]
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (TYPE_OF_NULLPTR) inline nodiscard
Construct from a nullptr.
Definition at line 286 of file SoftObjectPtr.h.
TSoftObjectPtr() [9/9]
template<class T = UObject> template<typename SoftObjectPathType UE_REQUIRES> FORCEINLINE TSoftObjectPtr< T >::TSoftObjectPtr (SoftObjectPathType ObjectPath) inline explicit nodiscard
Construct from a soft object path.
Definition at line 296 of file SoftObjectPtr.h.
Member Function Documentation
GetAssetName()
template<class T = UObject> FORCEINLINE FString TSoftObjectPtr< T >::GetAssetName () const inline nodiscard
Returns assetname string, leaving off the /package/path part.
Definition at line 595 of file SoftObjectPtr.h.
GetLongPackageFName()
template<class T = UObject> FORCEINLINE FName TSoftObjectPtr< T >::GetLongPackageFName () const inline nodiscard
Returns /package/path name, leaving off the asset name.
Definition at line 589 of file SoftObjectPtr.h.
GetLongPackageName()
template<class T = UObject> FORCEINLINE FString TSoftObjectPtr< T >::GetLongPackageName () const inline nodiscard
Returns /package/path string, leaving off the asset name.
Definition at line 583 of file SoftObjectPtr.h.
GetPtrTypeHash()
template<class T = UObject> FORCEINLINE uint32 TSoftObjectPtr< T >::GetPtrTypeHash () const inline nodiscard
Hash function.
Definition at line 607 of file SoftObjectPtr.h.
GetUniqueID()
template<class T = UObject> FORCEINLINE const FSoftObjectPath & TSoftObjectPtr< T >::GetUniqueID () const inline nodiscard
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
Definition at line 565 of file SoftObjectPtr.h.
Referenced by FEdGraphNodeHandle::operator==().
IsNull()
template<class T = UObject> FORCEINLINE bool TSoftObjectPtr< T >::IsNull () const inline nodiscard
Test if this can never point to a live UObject.
Returns
true if this is explicitly pointing to no object
Definition at line 559 of file SoftObjectPtr.h.
IsPending()
template<class T = UObject> FORCEINLINE bool TSoftObjectPtr< T >::IsPending () const inline nodiscard
Test if this does not point to a live UObject, but may in the future.
Returns
true if this does not point to a real object, but could possibly
Definition at line 549 of file SoftObjectPtr.h.
IsValid()
template<class T = UObject> FORCEINLINE bool TSoftObjectPtr< T >::IsValid () const inline nodiscard
Test if this points to a live UObject.
Returns
true if Get() would return a valid non-null pointer
Definition at line 538 of file SoftObjectPtr.h.
Referenced by TSoftObjectPtr< const T >::operator bool().
LoadAsync()
template<class T = UObject> int32 TSoftObjectPtr< T >::LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams = FLoadAssetAsyncOptionalParams()) const inline
Attempts to asynchronously load the object referenced by this soft pointer.
This is a wrapper around the LoadAsync function in SoftObjectPath, and the delegate is responsible for validating it loaded the correct type
Parameters
InCompletionDelegate Delegate to be invoked when the async load finishes, this will execute on the game thread as soon as the load succeeds or fails
InOptionalParams Optional parameters for async loading the asset
Returns
Unique ID associated with this load request (the same object or package can be associated with multiple IDs).
Definition at line 528 of file SoftObjectPtr.h.
LoadSynchronous()
template<class T = UObject> T * TSoftObjectPtr< T >::LoadSynchronous () const inline
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
Definition at line 514 of file SoftObjectPtr.h.
Referenced by USTRUCT().
operator bool()
template<class T = UObject> FORCEINLINE TSoftObjectPtr< T >::operator bool () const inline explicit nodiscard
Dereference soft pointer to see if it points somewhere valid.
Definition at line 601 of file SoftObjectPtr.h.
operator*()
template<class T = UObject> FORCEINLINE T & TSoftObjectPtr< T >::operator* () const inline nodiscard
Dereference the soft pointer.
Definition at line 502 of file SoftObjectPtr.h.
operator->()
template<class T = UObject> FORCEINLINE T * TSoftObjectPtr< T >::operator-> () const inline nodiscard
Dereference the soft pointer.
Definition at line 508 of file SoftObjectPtr.h.
operator=() [1/3]
template<class T = UObject> FORCEINLINE TSoftObjectPtr & TSoftObjectPtr< T >::operator= (const TSoftObjectPtr< T > & Other) default
operator=() [2/3]
template<class T = UObject> FORCEINLINE TSoftObjectPtr & TSoftObjectPtr< T >::operator= (TSoftObjectPtr< T > && Other) default
operator=() [3/3]
template<class T = UObject> template<typename U UE_REQUIRES> FORCEINLINE TSoftObjectPtr & TSoftObjectPtr< T >::operator= (U * Object) inline
Copy from an object already in memory.
Definition at line 329 of file SoftObjectPtr.h.
Reset()
template<class T = UObject> FORCEINLINE void TSoftObjectPtr< T >::Reset () inline
Reset the soft pointer back to the null state.
Definition at line 313 of file SoftObjectPtr.h.
ResetWeakPtr()
template<class T = UObject> FORCEINLINE void TSoftObjectPtr< T >::ResetWeakPtr () inline
Resets the weak ptr only, call this when ObjectId may change.
Definition at line 319 of file SoftObjectPtr.h.
Serialize()
template<class T = UObject> FORCEINLINE void TSoftObjectPtr< T >::Serialize (FArchive & Ar) inline
Definition at line 612 of file SoftObjectPtr.h.
ToSoftObjectPath()
template<class T = UObject> FORCEINLINE const FSoftObjectPath & TSoftObjectPtr< T >::ToSoftObjectPath () const inline nodiscard
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
Definition at line 571 of file SoftObjectPtr.h.
Referenced by TSoftObjectPtr< const T >::GetAssetName(), TSoftObjectPtr< const T >::GetLongPackageFName(), TSoftObjectPtr< const T >::GetLongPackageName(), FEdGraphNodeHandle::GetTypeHash, FRigVMCompilerWorkData::FFunctionRegisterData::GetTypeHash, and TSoftObjectPtr< const T >::ToString().
ToString()
template<class T = UObject> FORCEINLINE FString TSoftObjectPtr< T >::ToString () const inline nodiscard
Returns string representation of reference, in form /package/path.assetname.
Definition at line 577 of file SoftObjectPtr.h.
UE_DEPRECATED() [1/6]
template<class T = UObject> template<typename U UE_REQUIRES> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Assigning TSoftObjectPtr< T > from an incompatible pointer type has been deprecated.") & nodiscard
UE_DEPRECATED() [2/6]
template<class T = UObject> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Constructing TSoftObjectPtr< T > from an FString has been deprecated - instead, explicitly construct a FSoftObjectPath.") const & inline nodiscard
Definition at line 306 of file SoftObjectPtr.h.
UE_DEPRECATED() [3/6]
template<class T = UObject> template<typename U UE_REQUIRES> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Constructing TSoftObjectPtr< T > from an incompatible pointer type has been deprecated.") const inline nodiscard
Definition at line 279 of file SoftObjectPtr.h.
UE_DEPRECATED() [4/6]
template<class T = UObject> template<class U UE_REQUIRES> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Constructing TSoftObjectPtr< T > from an incompatible pointer type has been deprecated.") const & inline nodiscard
Definition at line 201 of file SoftObjectPtr.h.
UE_DEPRECATED() [5/6]
template<class T = UObject> template<class U UE_REQUIRES> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Constructing TSoftObjectPtr< T > from an incompatible pointer type has been deprecated.") && inline nodiscard
Definition at line 220 of file SoftObjectPtr.h.
UE_DEPRECATED() [6/6]
template<class T = UObject> template<typename U UE_REQUIRES> TSoftObjectPtr< T >::UE_DEPRECATED (5. 5, "Constructing TSoftObjectPtr< T > from an incompatible pointer type has been deprecated.") inline nodiscard
Definition at line 239 of file SoftObjectPtr.h.
Friends And Related Symbol Documentation
TSoftObjectPtr
template<class T = UObject> template<class U> friend struct TSoftObjectPtr friend
Definition at line 176 of file SoftObjectPtr.h.
Field Documentation
SoftObjectPtr
template<class T = UObject> FSoftObjectPtr TSoftObjectPtr< T >::SoftObjectPtr private
Definition at line 618 of file SoftObjectPtr.h.
The documentation for this struct was generated from the following file:
SoftObjectPtr.h