Unreal Engine 5.6 C++ API: FClassTree Class Reference
FClassTree Class Reference
Manages an inheritance tree.
#include "ClassTree.h"
Data Structures
struct FScopedRecurseDepthCounter
Public Member Functions
FClassTree (UClass *BaseClass)
Constructor.
~FClassTree ()
Destructor.
bool AddClass (UClass *ChildClass)
Public interface for adding a new class to the tree.
bool ChangeParentClass (UClass *SearchClass, UClass *InNewParentClass=NULL)
Move a class node in the hierarchy tree after a class has changed its SuperClass.
void DumpClassTree (int32 IndentCount, FOutputDevice &Ar)
const FClassTree * FindNode (UClass *SearchClass) const
Find the node associated with the class specified.
template<class Comparator>
FClassTree * GenerateMaskedClassTree (const Comparator &Mask) const
Creates a new class tree rooted at this node's class, which contains only classes which match the class flags specified.
FORCEINLINE const FClassTree * GetChild (int32 Index) const
void GetChildClasses (TArray< const FClassTree * > &ChildClasses, bool bRecurse=false) const
Retrieve the child nodes of this node.
void GetChildClasses (TArray< FClassTree * > &ChildClasses, bool bRecurse=false)
Retrieve the child nodes of this node.
template<class Comparator>
void GetChildClasses (TArray< UClass * > &ChildClasses, const Comparator &Mask, bool bRecurse=false) const
Retrieve the child nodes of this node that match the flags specified.
UClass * GetClass () const
Get the class associated with this node.
FClassTree * GetNode (UClass *SearchClass)
Find the node associated with the class specified.
FClassTree * GetRootNode ()
Gets the root node for this class tree.
const FClassTree * GetRootNode () const
Gets the root node for this class tree.
int32 Num () const
Get the number of classes represented by this node, including any child nodes.
FORCEINLINE int32 NumChildren () const
Get the number of child nodes of this node.
void PopulateTree ()
Utility/convenience method for populating a class tree.
void Validate () const
Verify that this node is at the correct location in the class tree.
Private Member Functions
bool AddChildClass (UClass *ChildClass)
Private interface for adding a new UClass to the class tree.
int32 AddChildNode (FClassTree *NewChild)
Adds a new child node to this node, sorted alphabetically by name.
int32 FindChildIndex (UClass *SearchClass) const
Find the child index for the class specified.
FClassTree * GetNode (UClass *SearchClass, bool bBruteForce)
Find the node associated with the class specified.
void ReplaceChild (UClass *NewChild, FClassTree *CurrentChild)
Replaces an existing child with the class specified, and changes the existing child's parent node to the new child.
Private Attributes
TArray< FClassTree * > Children
UClass * Class
TDoubleLinkedList< UObject * > Instances
FClassTree * Parent
Detailed Description
Manages an inheritance tree.
There is one FClassTree node for each UClass. Each node stores pointers to its parent and child nodes. New nodes should always be added to the root node. This is enforced by allowing const references to child nodes.
Definition at line 30 of file ClassTree.h.
Constructor & Destructor Documentation
FClassTree()
FClassTree::FClassTree (UClass * BaseClass) inline
Constructor.
Parameters
BaseClass the class that should be associated with this node.
Definition at line 560 of file ClassTree.h.
References check, Class, and Parent.
Referenced by ~FClassTree(), AddChildClass(), AddChildNode(), AddClass(), ChangeParentClass(), DumpClassTree(), FindNode(), GenerateMaskedClassTree(), GetChild(), GetChildClasses(), GetNode(), GetNode(), GetRootNode(), GetRootNode(), PopulateTree(), and ReplaceChild().
~FClassTree()
FClassTree::~FClassTree () inline
Destructor.
Frees the memory for all child nodes, recursively.
Definition at line 568 of file ClassTree.h.
References FClassTree(), Children, and Class.
Member Function Documentation
AddChildClass()
bool FClassTree::AddChildClass (UClass * ChildClass) inline private
Private interface for adding a new UClass to the class tree.
Takes care of inserting the class into the correct location in the structure. It is not required to add parent classes before adding child classes.
Parameters
ChildClass the class to add to the tree
Returns
true if this node was succesfully added as a child node of this one
Definition at line 48 of file ClassTree.h.
References FClassTree(), AddChildClass(), AddChildNode(), check, Children, Class, UStruct::IsChildOf(), and Parent.
Referenced by AddChildClass(), and AddClass().
AddChildNode()
int32 FClassTree::AddChildNode (FClassTree * NewChild) inline private
Adds a new child node to this node, sorted alphabetically by name.
Ignores duplicate entries.
Parameters
NewChild the node to add to the Children array
Returns
the index into the Children array for the new node, or the index for the existing node is this is a duplicate
Definition at line 97 of file ClassTree.h.
References FClassTree(), check, Child, Children, GetClass(), UObjectBaseUtility::GetName(), INDEX_NONE, Parent, and TCString< TCHAR >::Stricmp().
Referenced by AddChildClass(), ChangeParentClass(), and ReplaceChild().
AddClass()
bool FClassTree::AddClass (UClass * ChildClass) inline
Public interface for adding a new class to the tree.
Actual functionality implemented separately in order to support being able to call AddClass() on any node in the tree structure and have it inserted into the correct location.
Can be called on any node in the tree. Takes care of inserting the class into the correct location in the structure. Correctly handles adding classes in any arbitrary order (i.e. parent classes do not need to be added before child classes, etc.)
Parameters
ChildClass the class to add to the tree
Returns
buffer that will contain the post processed text
Definition at line 241 of file ClassTree.h.
References FClassTree(), AddChildClass(), and Parent.
Referenced by ChangeParentClass(), and PopulateTree().
ChangeParentClass()
bool FClassTree::ChangeParentClass (UClass * SearchClass, UClass * InNewParentClass = NULL) inline
Move a class node in the hierarchy tree after a class has changed its SuperClass.
Parameters
SearchClass the class that has changed parents
InNewParentClass if non-null force reparenting to this instead of the SuperClass
Returns
true if SearchClass was successfully moved to the new location
Definition at line 457 of file ClassTree.h.
References FClassTree(), AddChildNode(), AddClass(), ChangeParentClass(), check, GetNode(), UClass::GetSuperClass(), INDEX_NONE, and Parent.
Referenced by ChangeParentClass().
DumpClassTree()
void FClassTree::DumpClassTree (int32 IndentCount, FOutputDevice & Ar) inline
Definition at line 585 of file ClassTree.h.
References FClassTree(), Ar, Children, Class, DumpClassTree(), TCString< TCHAR >::Spc(), and TEXT.
Referenced by DumpClassTree().
FindChildIndex()
int32 FClassTree::FindChildIndex (UClass * SearchClass) const inline private
Find the child index for the class specified.
Parameters
SearchClass the class to search for
Returns
the index into the Children array for the node associated with the class specified, or INDEX_NONE if that class isn't in the list of children
Definition at line 201 of file ClassTree.h.
References Children, GetClass(), and INDEX_NONE.
FindNode()
const FClassTree * FClassTree::FindNode (UClass * SearchClass) const inline
Find the node associated with the class specified.
Parameters
SearchClass the class to search for
Returns
a pointer to the node associated with the class specified, or NULL if this branch doesn't contain that class
Definition at line 432 of file ClassTree.h.
References FClassTree(), Child, Children, Class, and UStruct::IsChildOf().
GenerateMaskedClassTree()
template<class Comparator> FClassTree * FClassTree::GenerateMaskedClassTree (const Comparator & Mask) const inline
Creates a new class tree rooted at this node's class, which contains only classes which match the class flags specified.
Parameters
Mask information about the types of classes to include. Must implement bool IsValidClass(const FClassTree* Node) const.
Returns
a pointer to an FClassTree that contains only classes which match the parameters specified by MaskParams. If the class associated with this node does not meet the requirements of the MaskParams, the return value is a NULL pointer, and the class tree will not contain any of the children of that class. NOTE: the caller is responsible for deleting the FClassTree returned by this function!!
Definition at line 373 of file ClassTree.h.
References FClassTree(), TArray< InElementType, InAllocatorType >::Add(), Children, Class, Mask, and Parent.
GetChild()
FORCEINLINE const FClassTree * FClassTree::GetChild (int32 Index) const inline
Definition at line 605 of file ClassTree.h.
References FClassTree(), Children, and FORCEINLINE.
GetChildClasses() [1/3]
void FClassTree::GetChildClasses (TArray< const FClassTree * > & ChildClasses, bool bRecurse = false) const inline
Retrieve the child nodes of this node.
Parameters
ChildClasses [out] this node's children
bRecurse if false, only direct children of this node's class will be considered
Definition at line 311 of file ClassTree.h.
References TArray< InElementType, InAllocatorType >::Add(), Children, and TArray< InElementType, InAllocatorType >::Empty().
GetChildClasses() [2/3]
void FClassTree::GetChildClasses (TArray< FClassTree * > & ChildClasses, bool bRecurse = false) inline
Retrieve the child nodes of this node.
Parameters
ChildClasses [out] this node's children
bRecurse if false, only direct children of this node's class will be considered
Definition at line 283 of file ClassTree.h.
References TArray< InElementType, InAllocatorType >::Add(), Children, and TArray< InElementType, InAllocatorType >::Empty().
Referenced by GetChildClasses().
GetChildClasses() [3/3]
template<class Comparator> void FClassTree::GetChildClasses (TArray< UClass * > & ChildClasses, const Comparator & Mask, bool bRecurse = false) const inline
Retrieve the child nodes of this node that match the flags specified.
Parameters
ChildClasses [out] array of child classes with class flags matching the flags specified
Mask info on how to determine whether classes are included in the results. Must implement bool IsValidClass(const FClassTree* Node) const.
bRecurse if false, only direct children of this node's class will be considered
Definition at line 342 of file ClassTree.h.
References FClassTree(), TArray< InElementType, InAllocatorType >::Add(), Children, GetChildClasses(), GetClass(), and Mask.
GetClass()
UClass * FClassTree::GetClass () const inline
Get the class associated with this node.
Returns
a pointer to the class associated with this node
Definition at line 256 of file ClassTree.h.
References Class.
Referenced by AddChildNode(), FindChildIndex(), GetChildClasses(), and ReplaceChild().
GetNode() [1/2]
FClassTree * FClassTree::GetNode (UClass * SearchClass) inline
Find the node associated with the class specified.
Parameters
SearchClass the class to search for
Returns
a pointer to the node associated with the class specified, or NULL if this branch doesn't contain that class
Definition at line 420 of file ClassTree.h.
References FClassTree(), and GetNode().
GetNode() [2/2]
FClassTree * FClassTree::GetNode (UClass * SearchClass, bool bBruteForce) inline private
Find the node associated with the class specified.
Parameters
SearchClass the class to search for
bBruteForce if true, searches every node for the specified class, rather than using IsChildOf() to optimize the search
Returns
a pointer to the node associated with the class specified, or NULL if this branch doesn't contain that class
Definition at line 173 of file ClassTree.h.
References FClassTree(), Children, Class, and UStruct::IsChildOf().
Referenced by ChangeParentClass(), and GetNode().
GetRootNode() [1/2]
FClassTree * FClassTree::GetRootNode () inline
Gets the root node for this class tree.
Definition at line 396 of file ClassTree.h.
References FClassTree(), and Parent.
Referenced by PopulateTree().
GetRootNode() [2/2]
const FClassTree * FClassTree::GetRootNode () const inline
Gets the root node for this class tree.
Definition at line 406 of file ClassTree.h.
References FClassTree(), and Parent.
Num()
int32 FClassTree::Num () const inline
Get the number of classes represented by this node, including any child nodes.
Returns
the number of classes represented by this node, including any child nodes
Definition at line 507 of file ClassTree.h.
References Children, and Count.
NumChildren()
FORCEINLINE int32 FClassTree::NumChildren () const inline
Get the number of child nodes of this node.
Returns
the number of child nodes of this node
Definition at line 600 of file ClassTree.h.
References Children, and FORCEINLINE.
PopulateTree()
void FClassTree::PopulateTree () inline
Utility/convenience method for populating a class tree.
Definition at line 219 of file ClassTree.h.
References FClassTree(), AddClass(), and GetRootNode().
ReplaceChild()
void FClassTree::ReplaceChild (UClass * NewChild, FClassTree * CurrentChild) inline private
Replaces an existing child with the class specified, and changes the existing child's parent node to the new child.
For example, when changing NodeA -> NodeB -> NodeC to NodeA -> NodeC -> NodeB, NewChild is NodeC, and CurrentChild is NodeB
Parameters
NewChild the class that should be inserted into the chain between this node and the CurrentChild node
CurrentChild the existing node that should become a child of the new node
Definition at line 132 of file ClassTree.h.
References FClassTree(), AddChildNode(), Children, GetClass(), and UStruct::IsChildOf().
Validate()
void FClassTree::Validate () const inline
Verify that this node is at the correct location in the class tree.
Definition at line 521 of file ClassTree.h.
References check, Class, TArray< InElementType, InAllocatorType >::Num(), and Parent.
Field Documentation
Children
TArray<FClassTree*> FClassTree::Children private
Definition at line 34 of file ClassTree.h.
Referenced by ~FClassTree(), AddChildClass(), AddChildNode(), DumpClassTree(), FindChildIndex(), FindNode(), GenerateMaskedClassTree(), GetChild(), GetChildClasses(), GetChildClasses(), GetChildClasses(), GetNode(), Num(), NumChildren(), and ReplaceChild().
Class
UClass* FClassTree::Class private
Definition at line 32 of file ClassTree.h.
Referenced by FClassTree(), ~FClassTree(), AddChildClass(), DumpClassTree(), FindNode(), GenerateMaskedClassTree(), GetClass(), GetNode(), and Validate().
Instances
TDoubleLinkedList<UObject*> FClassTree::Instances private
Definition at line 35 of file ClassTree.h.
Parent
FClassTree* FClassTree::Parent private
Definition at line 33 of file ClassTree.h.
Referenced by FClassTree(), AddChildClass(), AddChildNode(), AddClass(), ChangeParentClass(), GenerateMaskedClassTree(), GetRootNode(), GetRootNode(), and Validate().
The documentation for this class was generated from the following file:
ClassTree.h