Unreal Engine 5.6 C++ API: UE::Geometry::FGridBoxMeshGenerator Class Reference
UE::Geometry::FGridBoxMeshGenerator Class Reference
Generate a mesh of a box that has "gridded" faces, i.e.
#include "GridBoxMeshGenerator.h"
Public Member Functions
virtual FMeshShapeGenerator & Generate () override
Generate the mesh.
Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
virtual ~FMeshShapeGenerator ()
int AppendNormal (const FVector3f &Normal, int ParentVertex)
int AppendTriangle (int A, int B, int C)
int AppendUV (const FVector2f &UV, int ParentVertex)
int AppendVertex (const FVector3d &Position)
Append a new vertex at the given Position.
void ExtendBufferSizes (int AddVertices, int AddTriangles, int AddUVs, int AddNormals)
Extends the various internal buffers to the correct sizes for the given additional element counts.
bool HasAttributes () const
void Reset ()
clear arrays so that Generate() can be run again
void ResetAttributes (bool bResetPolygonIDs=false)
void SetBufferSizes (int NumVertices, int NumTriangles, int NumUVs, int NumNormals)
Set the various internal buffers to the correct sizes for the given element counts.
void SetNormal (int Index, const FVector3f &Normal, int ParentVertex)
Set Normal at Index to given value with given ParentVertex.
void SetTriangle (int Index, const FIndex3i &Tri)
void SetTriangle (int Index, int A, int B, int C)
void SetTriangle (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleNormals (int Index, const FIndex3i &Tri)
void SetTriangleNormals (int Index, int A, int B, int C)
void SetTriangleNormals (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTrianglePolygon (int Index, int PolygonID)
void SetTriangleUVs (int Index, const FIndex3i &Tri)
void SetTriangleUVs (int Index, int A, int B, int C)
void SetTriangleUVs (int Index, int A, int B, int C, bool bClockwiseOverride)
void SetTriangleWithMatchedUVNormal (int Index, int A, int B, int C)
Set triangle and UVs and normals with matching indices Convenience function for shapes with no uv or normal seams.
void SetUV (int Index, const FVector2f &UV, int ParentVertex)
Set UV at Index to given value with given ParentVertex.
void SetVertex (int Index, const FVector3d &Position)
Set vertex at Index to given Position.
Data Fields
FOrientedBox3d Box
3D box
bool bPolygroupPerQuad = false
If true, each quad of box gets a separate polygroup.
bool bScaleUVByAspectRatio = true
If true (default), UVs are scaled so that there is no stretching.
FIndex3i EdgeVertices { 8,8,8 }
Data Fields inherited from UE::Geometry::FMeshShapeGenerator
bool bReverseOrientation = false
If true, reverse orientation of created mesh.
TArray< int > NormalParentVertex
Parent vertex index for each Normal.
TArray< FVector3f > Normals
Array of Normals.
TArray< FIndex3i > TriangleNormals
Array of triangle corner Normals, stored as tuples of indices into Normals array.
TArray< int > TrianglePolygonIDs
Array of per-triangle integer polygon IDs.
TArray< FIndex3i > Triangles
Array of triangle corner positions, stored as tuples of indices into Vertices array.
TArray< FIndex3i > TriangleUVs
Array of triangle corner UVs, stored as tuples of indices into UVs array.
TArray< int > UVParentVertex
Parent vertex index for each UV.
TArray< FVector2f > UVs
Array of UV positions.
TArray< FVector3d > Vertices
Array of vertex positions.
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::FMeshShapeGenerator
static FVector2d BilinearInterp (const FVector2d &v00, const FVector2d &v10, const FVector2d &v11, const FVector2d &v01, double tx, double ty)
static FVector2f BilinearInterp (const FVector2f &v00, const FVector2f &v10, const FVector2f &v11, const FVector2f &v01, float tx, float ty)
static FVector3d BilinearInterp (const FVector3d &v00, const FVector3d &v10, const FVector3d &v11, const FVector3d &v01, double tx, double ty)
static FVector3i LinearInterp (const FVector3i &a, const FVector3i &b, double t)
Detailed Description
Generate a mesh of a box that has "gridded" faces, i.e.
grid of triangulated quads, with EdgeVertices setting the number of verts along each edge in each dimension
Definition at line 18 of file GridBoxMeshGenerator.h.
Member Function Documentation
Generate()
virtual FMeshShapeGenerator & UE::Geometry::FGridBoxMeshGenerator::Generate () inline override virtual
Generate the mesh.
Implements UE::Geometry::FMeshShapeGenerator.
Reimplemented in UE::Geometry::FBoxSphereGenerator.
Definition at line 35 of file GridBoxMeshGenerator.h.
References UE::Geometry::FIndex3i::A, TMathUtil< double >::Abs(), UE::Geometry::FIndex3i::B, Box, bPolygroupPerQuad, bScaleUVByAspectRatio, UE::Geometry::FIndex3i::C, EdgeVertices, float, UE::Geometry::TOrientedBox3< double >::GetCornerSide(), Lerp, FMath::Max, UE::Geometry::MaxAbsElement(), UE::Geometry::Normal, UE::Geometry::FMeshShapeGenerator::NormalParentVertex, UE::Geometry::FMeshShapeGenerator::Normals, UE::Geometry::FMeshShapeGenerator::SetBufferSizes(), TArray< InElementType, InAllocatorType >::SetNum(), UE::Geometry::FMeshShapeGenerator::SetTriangle(), UE::Geometry::FMeshShapeGenerator::SetTriangleNormals(), UE::Geometry::FMeshShapeGenerator::SetTrianglePolygon(), UE::Geometry::FMeshShapeGenerator::SetTriangleUVs(), UV, UE::Geometry::FMeshShapeGenerator::UVParentVertex, UE::Geometry::FMeshShapeGenerator::UVs, and UE::Geometry::FMeshShapeGenerator::Vertices.
Referenced by UE::Geometry::FBoxSphereGenerator::Generate().
Field Documentation
Box
FOrientedBox3d UE::Geometry::FGridBoxMeshGenerator::Box
3D box
Definition at line 22 of file GridBoxMeshGenerator.h.
Referenced by UE::Geometry::FBoxSphereGenerator::Generate(), and Generate().
bPolygroupPerQuad
bool UE::Geometry::FGridBoxMeshGenerator::bPolygroupPerQuad = false
If true, each quad of box gets a separate polygroup.
Definition at line 30 of file GridBoxMeshGenerator.h.
Referenced by Generate().
bScaleUVByAspectRatio
bool UE::Geometry::FGridBoxMeshGenerator::bScaleUVByAspectRatio = true
If true (default), UVs are scaled so that there is no stretching.
If false, UVs are scaled to fill unit square
Definition at line 27 of file GridBoxMeshGenerator.h.
Referenced by Generate().
EdgeVertices
FIndex3i UE::Geometry::FGridBoxMeshGenerator::EdgeVertices { 8,8,8 }
Definition at line 24 of file GridBoxMeshGenerator.h.
Referenced by Generate().
The documentation for this class was generated from the following file:
GridBoxMeshGenerator.h