Unreal Engine 5.6 C++ API: FLocalVertexFactory Class Reference
FLocalVertexFactory Class Reference
A vertex factory which simply transforms explicit vertex attributes from local to world space.
#include "LocalVertexFactory.h"
Data Structures
struct FDataType
struct FDebugName
Public Member Functions
FLocalVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, const char *InDebugName)
virtual ~FLocalVertexFactory ()
checkf (IsInitialized() &&EnumHasAnyFlags(EVertexStreamUsage::Overridden, Data.ColorComponent.VertexStreamUsage) &&ColorStreamIndex > 0, TEXT("Per-mesh colors with bad stream setup! Name %s"), *ColorVertexBuffer->GetFriendlyName())
void Copy (const FLocalVertexFactory &Other)
Copy the data from another vertex factory.
FRHIShaderResourceView * GetColorComponentsSRV () const
const uint32 GetColorIndexMask () const
void GetColorOverrideStream (const FVertexBuffer *ColorVertexBuffer, FVertexInputStreamArray &VertexStreams) const
const int GetLightMapCoordinateIndex () const
const int GetNumTexcoords () const
FRHIShaderResourceView * GetPositionsSRV () const
FRHIShaderResourceView * GetPreSkinPositionSRV () const
FRHIShaderResourceView * GetTangentsSRV () const
FRHIShaderResourceView * GetTextureCoordinatesSRV () const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const override
FRHIUniformBuffer * GetUniformBuffer () const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void SetData (FRHICommandListBase &RHICmdList, const FDataType &InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
RHICmdList SetStreamSource (ColorStreamIndex, ColorVertexBuffer->VertexBufferRHI, 0)
UE_DEPRECATED (5.4, "SetData requires a command list.") 1 void SetData(const FDataType &InData)
UE_DEPRECATED (5.5, "SetColorOverrideStream is no longer used") FORCEINLINE_DEBUGGABLE void SetColorOverrideStream(FRHICommandList &RHICmdList
Public Member Functions inherited from FVertexFactory
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
virtual FVertexFactoryType * GetType () const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FVertexDeclarationElementList &Elements)
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Should we cache the material's shadertype on this platform with this vertex factory?
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Static Public Member Functions inherited from FVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields
const FVertexBuffer *ColorVertexBuffer const
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions
const FDataType & GetData () const
Protected Member Functions inherited from FVertexFactory
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType &Data, FVertexDeclarationElementList &Elements, FVertexStreamList &InOutStreams, int32 &OutColorStreamIndex)
Static Protected Member Functions inherited from FVertexFactory
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes
bool bGPUSkinPassThrough = false
int32 ColorStreamIndex
FDataType Data
struct FLocalVertexFactory::FDebugName DebugName
TUniformBufferRef< FLocalVertexFactoryUniformShaderParameters > UniformBuffer
Protected Attributes inherited from FVertexFactory
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Private Member Functions
DECLARE_VERTEX_FACTORY_TYPE_API (FLocalVertexFactory, 1)
Friends
class FLocalVertexFactoryShaderParameters
class FSkeletalMeshSceneProxy
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Protected Types inherited from FVertexFactory
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Detailed Description
A vertex factory which simply transforms explicit vertex attributes from local to world space.
Definition at line 50 of file LocalVertexFactory.h.
Constructor & Destructor Documentation
FLocalVertexFactory()
FLocalVertexFactory::FLocalVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, const char * InDebugName)
Referenced by FInstancedStaticMeshVertexFactory::FInstancedStaticMeshVertexFactory(), FSplineMeshVertexFactory::FSplineMeshVertexFactory(), Copy(), and DECLARE_VERTEX_FACTORY_TYPE_API().
~FLocalVertexFactory()
virtual FLocalVertexFactory::~FLocalVertexFactory () virtual
Member Function Documentation
checkf()
FLocalVertexFactory::checkf (IsInitialized() &&EnumHasAnyFlags(EVertexStreamUsage::Overridden, Data.ColorComponent.VertexStreamUsage) && ColorStreamIndex, 0 , TEXT("Per-mesh colors with bad stream setup! Name %s") , *ColorVertexBuffer-> GetFriendlyName())
References ColorStreamIndex, Data, Overridden, and TEXT.
Copy()
void FLocalVertexFactory::Copy (const FLocalVertexFactory & Other)
Copy the data from another vertex factory.
Parameters
Other - factory to copy from
References FLocalVertexFactory(), const, Copy(), and Other.
Referenced by Copy().
DECLARE_VERTEX_FACTORY_TYPE_API()
FLocalVertexFactory::DECLARE_VERTEX_FACTORY_TYPE_API (FLocalVertexFactory , 1) private
References FLocalVertexFactory().
GetColorComponentsSRV()
FRHIShaderResourceView * FLocalVertexFactory::GetColorComponentsSRV () const inline
Definition at line 142 of file LocalVertexFactory.h.
References Data.
GetColorIndexMask()
const uint32 FLocalVertexFactory::GetColorIndexMask () const inline
Definition at line 147 of file LocalVertexFactory.h.
References Data.
GetColorOverrideStream()
void FLocalVertexFactory::GetColorOverrideStream (const FVertexBuffer * ColorVertexBuffer, FVertexInputStreamArray & VertexStreams) const inline
Definition at line 109 of file LocalVertexFactory.h.
References TArray< InElementType, InAllocatorType >::Add(), checkf, ColorStreamIndex, Data, EnumHasAnyFlags(), FVertexBuffer::GetFriendlyName(), IsInitialized, FRenderResource::IsInitialized(), Overridden, TEXT, and FVertexBuffer::VertexBufferRHI.
GetData()
const FDataType & FLocalVertexFactory::GetData () const inline protected
Definition at line 177 of file LocalVertexFactory.h.
References Data.
GetLightMapCoordinateIndex()
const int FLocalVertexFactory::GetLightMapCoordinateIndex () const inline
Definition at line 152 of file LocalVertexFactory.h.
References Data.
GetNumTexcoords()
const int FLocalVertexFactory::GetNumTexcoords () const inline
Definition at line 157 of file LocalVertexFactory.h.
References Data.
GetPositionsSRV()
FRHIShaderResourceView * FLocalVertexFactory::GetPositionsSRV () const inline
Definition at line 122 of file LocalVertexFactory.h.
References Data.
Referenced by GetTriangleSortingPositionSRV().
GetPreSkinPositionSRV()
FRHIShaderResourceView * FLocalVertexFactory::GetPreSkinPositionSRV () const inline
Definition at line 127 of file LocalVertexFactory.h.
References Data, and GNullColorVertexBuffer.
GetPSOPrecacheVertexFetchElements()
void FLocalVertexFactory::GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) static
GetTangentsSRV()
FRHIShaderResourceView * FLocalVertexFactory::GetTangentsSRV () const inline
Definition at line 132 of file LocalVertexFactory.h.
References Data.
GetTextureCoordinatesSRV()
FRHIShaderResourceView * FLocalVertexFactory::GetTextureCoordinatesSRV () const inline
Definition at line 137 of file LocalVertexFactory.h.
References Data.
GetTriangleSortingPositionSRV()
virtual FShaderResourceViewRHIRef FLocalVertexFactory::GetTriangleSortingPositionSRV () const inline override virtual
Reimplemented from FVertexFactory.
Definition at line 117 of file LocalVertexFactory.h.
References GetPositionsSRV().
GetUniformBuffer()
FRHIUniformBuffer * FLocalVertexFactory::GetUniformBuffer () const inline
Definition at line 162 of file LocalVertexFactory.h.
References UniformBuffer.
GetVertexElements() [1/2]
void FLocalVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType & Data, FVertexDeclarationElementList & Elements) static
References Data, and FRenderResource::FeatureLevel.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheData().
GetVertexElements() [2/2]
void FLocalVertexFactory::GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, bool bSupportsManualVertexFetch, FDataType & Data, FVertexDeclarationElementList & Elements, FVertexStreamList & InOutStreams, int32 & OutColorStreamIndex) static protected
References Data, and FRenderResource::FeatureLevel.
InitRHI()
virtual void FLocalVertexFactory::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Reimplemented in FGPUSkinPassthroughVertexFactory, and FInstancedStaticMeshVertexFactory.
References InitRHI().
Referenced by InitRHI().
ModifyCompilationEnvironment()
void FLocalVertexFactory::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
ReleaseRHI()
virtual void FLocalVertexFactory::ReleaseRHI () inline override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexFactory.
Reimplemented in FGPUSkinPassthroughVertexFactory.
Definition at line 95 of file LocalVertexFactory.h.
References ReleaseRHI(), FVertexFactory::ReleaseRHI(), and UniformBuffer.
Referenced by FGPUSkinPassthroughVertexFactory::ReleaseRHI(), and ReleaseRHI().
SetData()
void FLocalVertexFactory::SetData (FRHICommandListBase & RHICmdList, const FDataType & InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Referenced by UE_DEPRECATED().
SetStreamSource()
RHICmdList FLocalVertexFactory::SetStreamSource (ColorStreamIndex , ColorVertexBuffer-> VertexBufferRHI, 0)
References ColorStreamIndex.
ShouldCompilePermutation()
bool FLocalVertexFactory::ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters & Parameters) static
Should we cache the material's shadertype on this platform with this vertex factory?
UE_DEPRECATED() [1/2]
FLocalVertexFactory::UE_DEPRECATED (5. 4, "SetData requires a command list.") const &
References const, and SetData().
UE_DEPRECATED() [2/2]
FLocalVertexFactory::UE_DEPRECATED (5. 5, "SetColorOverrideStream is no longer used") &
ValidateCompiledResult()
void FLocalVertexFactory::ValidateCompiledResult (const FVertexFactoryType * Type, EShaderPlatform Platform, const FShaderParameterMap & ParameterMap, TArray< FString > & OutErrors) static
References Platform.
Friends And Related Symbol Documentation
FLocalVertexFactoryShaderParameters
friend class FLocalVertexFactoryShaderParameters friend
Definition at line 174 of file LocalVertexFactory.h.
References FLocalVertexFactoryShaderParameters.
Referenced by FLocalVertexFactoryShaderParameters.
FSkeletalMeshSceneProxy
friend class FSkeletalMeshSceneProxy friend
Definition at line 175 of file LocalVertexFactory.h.
References FSkeletalMeshSceneProxy.
Referenced by FSkeletalMeshSceneProxy.
Field Documentation
bGPUSkinPassThrough
bool FLocalVertexFactory::bGPUSkinPassThrough = false protected
Definition at line 193 of file LocalVertexFactory.h.
ColorStreamIndex
int32 FLocalVertexFactory::ColorStreamIndex protected
Definition at line 191 of file LocalVertexFactory.h.
Referenced by checkf(), GetColorOverrideStream(), and SetStreamSource().
const
const FVertexBuffer* ColorVertexBuffer FLocalVertexFactory::const
Initial value:
{
        checkf(ColorVertexBuffer->IsInitialized(), TEXT("Color Vertex buffer was not initialized! Name %s"), *ColorVertexBuffer->GetFriendlyName())
Definition at line 102 of file LocalVertexFactory.h.
Referenced by Copy(), and UE_DEPRECATED().
Data
FDataType FLocalVertexFactory::Data protected
Definition at line 188 of file LocalVertexFactory.h.
Referenced by checkf(), GetColorComponentsSRV(), GetColorIndexMask(), GetColorOverrideStream(), GetData(), GetLightMapCoordinateIndex(), GetNumTexcoords(), GetPositionsSRV(), GetPreSkinPositionSRV(), GetTangentsSRV(), GetTextureCoordinatesSRV(), FInstancedStaticMeshVertexFactory::GetVertexElements(), FInstancedStaticMeshVertexFactory::GetVertexElements(), GetVertexElements(), GetVertexElements(), and FInstancedStaticMeshVertexFactory::SetData().
DebugName
struct FLocalVertexFactory::FDebugName FLocalVertexFactory::DebugName protected
UniformBuffer
TUniformBufferRef<FLocalVertexFactoryUniformShaderParameters> FLocalVertexFactory::UniformBuffer protected
Definition at line 189 of file LocalVertexFactory.h.
Referenced by GetUniformBuffer(), and ReleaseRHI().
The documentation for this class was generated from the following file:
LocalVertexFactory.h