Unreal Engine 5.6 C++ API: UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)> Struct Template Reference
UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)> Struct Template Reference
#include "Function.h"
Public Member Functions
TFunctionRefBase ()=default
TFunctionRefBase (const TFunctionRefBase &Other)
template<typename OtherStorage>
TFunctionRefBase (const TFunctionRefBase< OtherStorage, Ret(ParamTypes...)> &Other)
template<typename FunctorType UE_REQUIRES>
TFunctionRefBase (FunctorType &&InFunc)
TFunctionRefBase (TFunctionRefBase &&Other)
template<typename OtherStorage>
TFunctionRefBase (TFunctionRefBase< OtherStorage, Ret(ParamTypes...)> &&Other)
~TFunctionRefBase ()
FORCENOINLINE void CheckCallable () const
Ret operator() (ParamTypes... Params) const
TFunctionRefBase & operator= (const TFunctionRefBase &)=delete
TFunctionRefBase & operator= (TFunctionRefBase &&)=delete
void Reset ()
Removes any bound callable from the function, restoring it to the default 'empty' state.
Protected Member Functions
bool IsSet () const
Private Attributes
Ret(* Callable)(void *, ParamTypes &...) = nullptr
TDebugHelper< void > DebugPtrStorage
StorageType Storage
Friends
template<typename OtherStorageType, typename OtherFuncType>
struct TFunctionRefBase
Detailed Description
template<typename StorageType, typename Ret, typename... ParamTypes>
struct UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>
Definition at line 332 of file Function.h.
Constructor & Destructor Documentation
TFunctionRefBase() [1/6]
template<typename StorageType, typename Ret, typename... ParamTypes> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase () default
TFunctionRefBase() [2/6]
template<typename StorageType, typename Ret, typename... ParamTypes> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase (TFunctionRefBase< StorageType, Ret(ParamTypes...)> && Other) inline
Definition at line 339 of file Function.h.
References TFunctionRefBase, Callable, DebugPtrStorage, FMemory::Memcpy(), MoveTemp(), Other, and Storage.
TFunctionRefBase() [3/6]
template<typename StorageType, typename Ret, typename... ParamTypes> template<typename OtherStorage> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase (TFunctionRefBase< OtherStorage, Ret(ParamTypes...)> && Other) inline
Definition at line 359 of file Function.h.
References TFunctionRefBase, Callable, DebugPtrStorage, FMemory::Memcpy(), MoveTemp(), Other, and Storage.
TFunctionRefBase() [4/6]
template<typename StorageType, typename Ret, typename... ParamTypes> template<typename OtherStorage> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase (const TFunctionRefBase< OtherStorage, Ret(ParamTypes...)> & Other) inline
Definition at line 380 of file Function.h.
References TFunctionRefBase, Callable, DebugPtrStorage, FMemory::Memcpy(), Other, Storage, and UE_ENABLE_TFUNCTIONREF_VISUALIZATION.
TFunctionRefBase() [5/6]
template<typename StorageType, typename Ret, typename... ParamTypes> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase (const TFunctionRefBase< StorageType, Ret(ParamTypes...)> & Other) inline
Definition at line 403 of file Function.h.
References TFunctionRefBase, Callable, DebugPtrStorage, FMemory::Memcpy(), Other, Storage, and UE_ENABLE_TFUNCTIONREF_VISUALIZATION.
TFunctionRefBase() [6/6]
template<typename StorageType, typename Ret, typename... ParamTypes> template<typename FunctorType UE_REQUIRES> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase (FunctorType && InFunc) inline
Definition at line 428 of file Function.h.
References Callable, DebugPtrStorage, Forward(), and Storage.
~TFunctionRefBase()
template<typename StorageType, typename Ret, typename... ParamTypes> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::~TFunctionRefBase () inline
Definition at line 474 of file Function.h.
References Callable, and Storage.
Member Function Documentation
CheckCallable()
template<typename StorageType, typename Ret, typename... ParamTypes> FORCENOINLINE void UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::CheckCallable () const inline
Definition at line 458 of file Function.h.
References Callable, checkf, FORCENOINLINE, and TEXT.
Referenced by operator()().
IsSet()
template<typename StorageType, typename Ret, typename... ParamTypes> bool UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::IsSet () const inline protected
Definition at line 499 of file Function.h.
References Callable.
operator()()
template<typename StorageType, typename Ret, typename... ParamTypes> Ret UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::operator() (ParamTypes... Params) const inline
Definition at line 463 of file Function.h.
References Callable, CheckCallable(), Params, and Storage.
operator=() [1/2]
template<typename StorageType, typename Ret, typename... ParamTypes> TFunctionRefBase & UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::operator= (const TFunctionRefBase< StorageType, Ret(ParamTypes...)> &) delete
References TFunctionRefBase.
operator=() [2/2]
template<typename StorageType, typename Ret, typename... ParamTypes> TFunctionRefBase & UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::operator= (TFunctionRefBase< StorageType, Ret(ParamTypes...)> &&) delete
References TFunctionRefBase.
Reset()
template<typename StorageType, typename Ret, typename... ParamTypes> void UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::Reset () inline
Removes any bound callable from the function, restoring it to the default 'empty' state.
Definition at line 489 of file Function.h.
References Callable, and Storage.
Friends And Related Symbol Documentation
TFunctionRefBase
template<typename StorageType, typename Ret, typename... ParamTypes> template<typename OtherStorageType, typename OtherFuncType> friend struct TFunctionRefBase friend
Definition at line 335 of file Function.h.
References TFunctionRefBase.
Referenced by TFunctionRefBase, TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), operator=(), and operator=().
Field Documentation
Callable
template<typename StorageType, typename Ret, typename... ParamTypes> Ret(* UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::Callable) (void *, ParamTypes &...) = nullptr private
Definition at line 509 of file Function.h.
Referenced by TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), ~TFunctionRefBase(), CheckCallable(), IsSet(), operator()(), and Reset().
DebugPtrStorage
template<typename StorageType, typename Ret, typename... ParamTypes> TDebugHelper<void> UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::DebugPtrStorage private
Definition at line 515 of file Function.h.
Referenced by TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), and TFunctionRefBase().
Storage
template<typename StorageType, typename Ret, typename... ParamTypes> StorageType UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::Storage private
Definition at line 511 of file Function.h.
Referenced by TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), TFunctionRefBase(), ~TFunctionRefBase(), operator()(), and Reset().
The documentation for this struct was generated from the following file:
Function.h