Unreal Engine 5.6 C++ API: FAudioDevice Class Reference
FAudioDevice Class Reference abstract
#include "AudioDevice.h"
Data Structures
struct FAudioSpatializationInterfaceInfo
struct FAudioVolumeSettings
struct FCreateComponentParams
Public Member Functions
FAudioDevice ()
Constructor.
virtual ~FAudioDevice ()
void ActivateReverbEffect (UReverbEffect *ReverbEffect, FName TagName, float Priority, float Volume, float FadeTime)
Activates a Reverb Effect without the need for a volume.
void AddAudioVolumeProxy (const FAudioVolumeProxy &Proxy)
virtual void AddEnvelopeFollowerDelegate (USoundSubmix *InSubmix, const FOnSubmixEnvelopeBP &OnSubmixEnvelopeBP)
Adds an envelope follower delegate to the submix for this audio device.
void AddNewActiveSound (const FActiveSound &ActiveSound, const TArray< FAudioParameter > *InDefaultParams=nullptr)
Adds an active sound to the audio device.
void AddNewActiveSound (const FActiveSound &ActiveSound, TArray< FAudioParameter > &&InDefaultParams)
Adds an active sound to the audio device.
virtual Audio::FPatchOutputStrongPtr AddPatchForSubmix (uint32 InObjectId, float InPatchGain)
virtual Audio::FPatchInput AddPatchInputForAudioBus (uint32 InAudioBusId, int32 InFrames, int32 InChannels, float InGain=1.f)
virtual Audio::FPatchOutputStrongPtr AddPatchOutputForAudioBus (uint32 InAudioBusId, int32 InFrames, int32 InChannels, float InGain=1.f)
FDelegateHandle AddPostRenderDelegate (const FOnAudioDevicePostRender::FDelegate &InDelegate)
FDelegateHandle AddPreRenderDelegate (const FOnAudioDevicePreRender::FDelegate &InDelegate)
void AddReferencedObjects (FReferenceCollector &Collector)
Track references to UObjects.
void AddSoundToStop (FActiveSound *SoundToStop)
Marks a sound to be stopped.
virtual void AddSpectralAnalysisDelegate (USoundSubmix *InSubmix, const FSoundSpectrumAnalyzerDelegateSettings &InDelegateSettings, const FOnSubmixSpectralAnalysisBP &OnSubmixSpectralAnalysisBP)
void AddVirtualLoop (const FAudioVirtualLoop &InVirtualLoop)
void ApplyInteriorSettings (FActiveSound &ActiveSound, FSoundParseParameters &ParseParams) const
Applies interior settings from affecting volumes to the active sound (called on audio thread)
bool AreStartupSoundsPreCached () const
bool CanHaveMultipleActiveSounds (uint64 AudioComponentID) const
Whether a given Audio Component ID should be allowed to have multiple associated Active Sounds.
float ClampPitch (float InPitchScale) const
void ClearListenerAttenuationOverride (int32 ListenerIndex)
Removes a listener attenuation override for the specified listener.
void ClearSoundMixClassOverride (USoundMix *InSoundMix, USoundClass *InSoundClass, float FadeOutTime)
Clears a sound class override in the given sound mix.
void ClearSoundMixModifier (USoundMix *SoundMix)
Clear the effect of one SoundMix completely.
void ClearSoundMixModifiers ()
Clear the effect of all SoundMix modifiers.
virtual void ClearSubmixEffectChainOverride (USoundSubmix *InSoundSubmix, float InCrossfadeTime)
Clears all submix effect chain overrides from the submix.
virtual void CountBytes (FArchive &Ar)
Counts the bytes for the structures used in this class.
virtual FAudioEffectsManager * CreateEffectsManager ()
Creates a new platform specific sound source.
virtual FSoundSource * CreateSoundSource ()=0
Creates a new platform specific sound source.
void DeactivateReverbEffect (FName TagName)
Deactivates a Reverb Effect not applied by a volume.
void Deinitialize ()
De-initialization step that occurs after device destroyed broadcast, but before removal from the device manager.
void DestroyEffect (FSoundSource *Source)
Platform dependent call to destroy any effect related data.
virtual bool DisablePCMAudioCaching () const
Whether or not the platform disables caching of decompressed PCM data (i.e.
virtual void EnableDebugAudioOutput ()
Enables the audio device to output debug audio to test audio device output.
void EnableRadioEffect (bool bEnable=false)
Enables or Disables the radio effect.
virtual void FadeIn ()
virtual void FadeOut ()
Optional fadeout and fade in of audio to avoid clicks when closing or opening/reusing audio device.
int32 FindClosestListenerIndex (const FTransform &SoundTransform) const
Returns the index of the listener closest to the given sound transform.
int32 FindClosestListenerIndex (const FVector &Position, float &OutSqDistance, bool AllowAttenuationOverrides) const
void Flush (UWorld *WorldToFlush, bool bClearActivatedReverb=true)
Stop all the audio components and sources attached to the world.
virtual void FlushAudioRenderingCommands (bool bPumpSynchronously=false)
Allows audio rendering command queue to flush during audio device flush.
virtual void FlushExtended (UWorld *WorldToFlush, bool bClearActivatedReverb)
template<typename TSubsystemClass>
void ForEachSubsystem (TFunctionRef< void(TSubsystemClass *)> Operation) const
Performs the given operation on all subsystems of the given class.
void GatherInteriorData (FActiveSound &ActiveSound, FSoundParseParameters &ParseParams) const
Gathers data about interior volumes affecting the active sound (called on audio thread)
const TMap< FName, FActivatedReverb > & GetActiveReverb () const
const TArray< FActiveSound * > & GetActiveSounds () const
const TArray< FWaveInstance * > & GetActiveWaveInstances () const
double GetAudioClock () const
Returns the audio clock of the audio device.
virtual void GetAudioDeviceList (TArray< FString > &OutAudioDeviceNames) const
Returns an array of available audio devices names for the platform.
FName GetAudioStateProperty (const FName &PropertyName) const
virtual double GetAudioTime () const
Return the audio stream time.
void GetAudioVolumeSettings (const uint32 WorldID, const FVector &Location, FAudioVolumeSettings &OutSettings) const
TArray< FName > GetAvailableSpatializationPluginNames () const
Get the current list of available spatialization plugins.
void GetAzimuth (const FAttenuationListenerData &OutListenerData, float &OutAzimuth, float &AbsoluteAzimuth) const
Returns the azimuth angle of the sound relative to the sound's nearest listener.
int32 GetBufferLength () const
Returns the buffer length of the audio device.
float GetCompressionDurationThreshold (const FSoundGroup &SoundGroup)
UReverbEffect * GetCurrentReverbEffect () const
Returns the currently applied reverb effect if there is one.
virtual bool GetCurrentSourceEffectChain (const uint32 SourceEffectChainId, TArray< FSourceEffectChainEntry > &OutCurrentSourceEffectChainEntries)
Returns the current source effect chain entries set dynamically from BP or elsewhere.
FAudioSpatializationInterfaceInfo GetCurrentSpatializationPluginInterfaceInfo ()
bool GetDefaultAudioSettings (uint32 WorldID, FReverbSettings &OutReverbSettings, FInteriorSettings &OutInteriorSettings) const
Gets the default reverb and interior settings for the provided world.
USoundMix * GetDefaultBaseSoundMixModifier ()
float GetDefaultReverbSendLevel () const
Returns the default reverb send level used for sources which have reverb applied but no attenuation settings.
float GetDeviceDeltaTime () const
Returns the current audio device update delta time.
bool GetDistanceSquaredToListener (const FVector &Location, int32 ListenerIndex, float &OutSqDistance) const
Sets OutSqDistance to the distance from location to the appropriate listener representation, depending on calling thread.
bool GetDistanceSquaredToNearestListener (const FVector &Location, float &OutSqDistance) const
Sets OutSqDistance to the distance from location the closest listener, depending on calling thread.
float GetDistanceToNearestListener (const FVector &Location) const
Returns the distance to the nearest listener from the given location.
FAudioEffectsManager * GetEffects ()
Return the pointer to the sound effects handler.
const FAudioEffectsManager * GetEffects () const
Return the pointer to the sound effects handler.
float GetFocusFactor (const float Azimuth, const FSoundAttenuationSettings &AttenuationSettings) const
Returns the focus factor of a sound based on its position and listener data.
float GetGameDeltaTime () const
Returns the game's delta time.
const FGlobalFocusSettings & GetGlobalFocusSettings () const
TRange< float > GetGlobalPitchRange () const
Returns global pitch range.
const FDynamicParameter & GetGlobalPitchScale () const
virtual double GetInterpolatedAudioClock () const
Returns the audio clock interploated between audio device callbacks to provide a smoothed value.
const FVector & GetListenerAttenuationOverride (int32 ListenerIndex) const
Returns the listener attenuation override for the specified listener.
bool GetListenerPosition (int32 ListenerIndex, FVector &OutPosition, bool bAllowOverride) const
Returns a position from the appropriate listener representation, depending on calling thread.
const TArray< FListener > & GetListeners () const
bool GetListenerTransform (int32 ListenerIndex, FTransform &OutTransform) const
Returns the transform of the appropriate listener representation, depending on calling thread.
FVector GetListenerTransformedDirection (const FVector &Position, float *OutDistance)
Gets the direction of the given position vector transformed relative to listener.
bool GetListenerWorldID (int32 ListenerIndex, uint32 &OutWorldID) const
Returns the WorldID of the appropriate listener representation, depending on calling thread.
float GetLowPassFilterResonance () const
Low pass filter OneOverQ value.
virtual void GetMagnitudesForFrequencies (USoundSubmix *InSubmix, const TArray< float > &InFrequencies, TArray< float > &OutMagnitudes)
virtual USoundSubmix & GetMainSubmixObject () const
int32 GetMaxChannels () const
Returns the max channels used by the audio device.
void GetMaxDistanceAndFocusFactor (USoundBase *Sound, const UWorld *World, const FVector &Location, const FSoundAttenuationSettings *AttenuationSettingsToApply, float &OutMaxDistance, float &OutFocusFactor)
Gets the max distance and focus factor of a sound.
int32 GetMaxSources () const
Returns the maximum sources used by the audio device set on initialization, including the number of stopping voices reserved.
EDebugState GetMixDebugState () const
Gets the current audio debug state.
virtual int32 GetNumActiveSources () const
Returns the number of active sound sources.
int32 GetNumBuffers () const
Returns the number of buffers the audio device keeps queued.
int32 GetNumFreeSources () const
Returns the number of free sources.
virtual void GetPhasesForFrequencies (USoundSubmix *InSubmix, const TArray< float > &InFrequencies, TArray< float > &OutPhases)
float GetPlatformAudioHeadroom () const
const TArray< USoundMix * > & GetPrevPassiveSoundMixModifiers () const
float GetPrimaryVolume () const
Returns the volume that combines transient master volume and the FApp::GetVolumeMultiplier() value.
float GetSampleRate () const
Returns the sample rate used by the audio device.
int32 GetSortedActiveWaveInstances (TArray< FWaveInstance * > &WaveInstances, const ESortedActiveWaveGetType::Type GetType)
Iterate over the active AudioComponents for wave instances that could be playing.
FSoundClassProperties * GetSoundClassCurrentProperties (USoundClass *InSoundClass)
Gets the current properties of a sound class, if the sound class hasn't been registered, then it returns nullptr.
FSoundClassDynamicProperties * GetSoundClassDynamicProperties (USoundClass *InSoundClass)
Returns the parameters which are dynamic from the given sound class.
FSoundClassProperties & GetSoundClassPropertyMap () const
const TMap< USoundMix *, FSoundMixState > & GetSoundMixModifiers () const
FSoundSource * GetSoundSource (FWaveInstance *WaveInstance) const
TAudioSpatializationPtr GetSpatializationPluginInterface ()
Return the spatialization plugin interface.
template<typename TSubsystemClass>
TSubsystemClass * GetSubsystem () const
Get a Subsystem of specified type.
template<typename TSubsystemClass>
TArray< TSubsystemClass * > GetSubsystemArrayCopy () const
Gets all Subsystems of specified type, this is only necessary for interfaces that can have multiple implementations instanced at a time.
UAudioEngineSubsystem * GetSubsystemBase (TSubclassOf< UAudioEngineSubsystem > SubsystemClass) const
Get a Subsystem of specified type.
UAudioComponent * GetTestComponent (UWorld *InWorld)
float GetTransientPrimaryVolume () const
const TMap< FWaveInstance *, FSoundSource * > & GetWaveInstanceSourceMap () const
virtual bool HasCompressedAudioInfoClass (USoundWave *SoundWave)
Whether this SoundWave has an associated info class to decompress it.
bool Init (Audio::FDeviceId InDeviceID, int32 InMaxSources, int32 BufferSizeOverride=INDEX_NONE, int32 NumBuffersOverride=INDEX_NONE)
Basic initialization of the platform agnostic layer of the audio system.
void * InitEffect (FSoundSource *Source)
Platform dependent call to init effect data on a sound source.
virtual bool InitializeHardware ()
Starts up any platform specific hardware/APIs.
void InitSoundClasses ()
Set up the sound class hierarchy.
virtual void InitSoundSubmixes ()
Initializes sound submixes.
void InvalidateCachedInteriorVolumes () const
When the set of Audio volumes have changed invalidate the cached values of active sounds.
bool IsAudioDeviceMuted () const
bool IsBakedAnalaysisQueryingEnabled () const
Returns if baked analysis querying is enabled.
virtual bool IsExernalBackgroundSoundActive ()
Check if any background music or sound is playing through the audio device.
bool IsHRTFDisabled () const
Whether or not HRTF is disabled.
bool IsHRTFEnabledForAll () const
Whether or not HRTF spatialization is enabled for all.
bool IsMainAudioDevice () const
bool IsModulationPluginEnabled () const
Whether or not there's a modulation plugin enabled.
virtual bool IsNonRealtime () const
bool IsOcclusionPluginEnabled () const
Whether or not there's an occlusion plugin enabled.
bool IsPendingStop (FActiveSound *ActiveSound)
Whether the provided ActiveSound is currently pending to stop.
bool IsReverbPluginEnabled () const
Whether or not there's a reverb plugin enabled.
bool IsSourceDataOverridePluginEnabled () const
bool IsSpatializationPluginEnabled () const
Whether or not there's a spatialization plugin enabled.
bool IsStoppingVoicesEnabled () const
Returns if stopping voices is enabled.
bool IsUsingListenerAttenuationOverride (int32 ListenerIndex) const
Returns if the specific listener is using an attenuation override position.
bool LocationIsAudible (const FVector &Location, const float MaxDistance) const
Checks to see if a coordinate is within a distance of any listener.
bool LocationIsAudible (const FVector &Location, int32 ListenerIndex, const float MaxDistance) const
Checks to see if a coordinate is within a distance of a specific listener.
void NotifyActiveSoundOcclusionTraceDone (FActiveSound *ActiveSound, bool bIsOccluded)
Notify that a pending async occlusion trace finished on the active sound.
void OnBeginPIE (const bool bIsSimulating)
Deals with anything audio related that should happen when PIE starts.
void OnDeviceCreated (Audio::FDeviceId InDeviceID)
Called after FAudioDevice creation and init.
void OnDeviceDestroyed (Audio::FDeviceId InDeviceID)
Called before FAudioDevice teardown.
void OnEndPIE (const bool bIsSimulating)
Deals with anything audio related that should happen when PIE ends.
void OnPreGarbageCollect ()
void PauseActiveSound (uint64 AudioComponentID, const bool bInIsPaused)
Pauses the active sound for the specified audio component.
void PlaySoundAtLocation (USoundBase *Sound, UWorld *World, float VolumeMultiplier, float PitchMultiplier, float StartTime, const FVector &Location, const FRotator &Rotation, USoundAttenuation *AttenuationSettings=nullptr, USoundConcurrency *ConcurrencySettings=nullptr, const TArray< FAudioParameter > *Params=nullptr, const AActor *OwningActor=nullptr)
Plays a sound at the given location without creating an audio component.
bool PlayWhenSilentEnabled () const
Whether play when silent is enabled for all sounds associated with this audio device.
void PopSoundMixModifier (USoundMix *SoundMix, bool bIsPassive=false)
Pop a SoundMix from the Audio Device's list.
virtual void Precache (USoundWave *SoundWave, bool bSynchronous=false, bool bTrackMemory=true, bool bForceFullDecompression=false)
Precaches the passed in sound node wave object.
void PrecacheStartupSounds ()
Precaches all existing sounds.
void PushSoundMixModifier (USoundMix *SoundMix, bool bIsPassive=false, bool bIsRetrigger=false)
Push a SoundMix onto the Audio Device's list.
void RegisterPluginListener (const TAudioPluginListenerPtr PluginListener)
Registers a third party listener-observer to this audio device.
void RegisterSoundClass (USoundClass *InSoundClass)
Registers a sound class with the audio device.
virtual void RegisterSoundSubmix (USoundSubmixBase *SoundSubmix, bool bInit)
Registers the sound submix.
virtual void RegisterSubmixBufferListener (TSharedRef< ISubmixBufferListener, ESPMode::ThreadSafe > InSubmixBufferListener, USoundSubmix &SoundSubmix)
Registers the provided submix buffer listener with the given submix.
void RemoveActiveSound (FActiveSound *ActiveSound)
Removes an active sound from the active sounds array.
void RemoveAudioVolumeProxy (uint32 AudioVolumeID)
virtual void RemoveEnvelopeFollowerDelegate (USoundSubmix *InSubmix, const FOnSubmixEnvelopeBP &OnSubmixEnvelopeBP)
bool RemovePostRenderDelegate (const FDelegateHandle &InHandle)
bool RemovePreRenderDelegate (const FDelegateHandle &InHandle)
void RemoveSoundMix (USoundMix *SoundMix)
Removes a sound mix - called when SoundMix is unloaded.
virtual void RemoveSpectralAnalysisDelegate (USoundSubmix *InSubmix, const FOnSubmixSpectralAnalysisBP &OnSubmixSpectralAnalysisBP)
void ResetAudioVolumeProxyChangedState ()
void ResetInterpolation ()
Resets all interpolating values to defaults.
virtual void ResumeContext ()
Resume any context related objects.
void RetriggerVirtualLoop (FAudioVirtualLoop &VirtualLoop)
Attempts to retrigger a provided loop.
void SendCommandToActiveSounds (uint64 InAudioComponentID, TUniqueFunction< void(FActiveSound &)> InFunc, const TStatId InStatId=TStatId())
Performs an operation on all active sounds requested to execute by an audio component.
void SetAudioStateProperty (const FName &PropertyName, const FName &PropertyValue)
void SetBaseSoundMix (USoundMix *SoundMix)
Sets a new sound mix and applies it to all appropriate sound classes.
void SetCanHaveMultipleActiveSounds (uint64 AudioComponentID, bool InCanHaveMultipleActiveSounds)
Set whether a given Audio Component ID should be allowed to have multiple associated Active Sounds.
bool SetCurrentSpatializationPlugin (FName PluginName)
Set and initialize the current Spatialization plugin (by name)
void SetDefaultAudioSettings (UWorld *World, const FReverbSettings &DefaultReverbSettings, const FInteriorSettings &DefaultInteriorSettings)
Sets the default reverb and interior settings for the provided world.
void SetDefaultBaseSoundMix (USoundMix *SoundMix)
Sets the Sound Mix that should be active by default.
void SetDeviceMuted (bool bMuted)
void SetGlobalFocusSettings (const FGlobalFocusSettings &NewFocusSettings)
void SetGlobalPitchModulation (float PitchScale, float TimeSec)
void SetHRTFDisabled (bool InIsHRTFDisabled)
void SetHRTFEnabledForAll (bool InbHRTFEnabledForAll)
void SetListener (UWorld *World, int32 InListenerIndex, const FTransform &ListenerTransform, float InDeltaSeconds)
Sets the details about the listener.
void SetListenerAttenuationOverride (int32 ListenerIndex, const FVector AttenuationPosition)
Sets an override position for the specified listener to do attenuation calculations.
void SetMaxChannels (int32 InMaxChannels)
Sets the maximum number of channels dynamically.
void SetMaxChannelsScaled (float InScaledChannelCount)
Sets the maximum number of channels dynamically by scaled percentage.
void SetMixDebugState (EDebugState DebugState)
void SetPlatformAudioHeadroom (float PlatformHeadRoom)
void SetSoundClassDistanceScale (USoundClass *InSoundClass, float DistanceScale, float TimeSec)
Overrides the attenuation scale used on a sound class.
void SetSoundMixClassOverride (USoundMix *InSoundMix, USoundClass *InSoundClass, float Volume, float Pitch, float FadeInTime, bool bApplyToChildren)
Sets a sound class override in the given sound mix.
void SetSoundMixModifiers (const TMap< USoundMix *, FSoundMixState > &InSoundMixModifiers, const TArray< USoundMix * > &InPrevPassiveSoundMixModifiers, USoundMix *InDefaultBaseSoundMix)
void SetSpatializationInterfaceEnabled (bool InbSpatializationInterfaceEnabled)
virtual void SetSubmixAutoDisable (USoundSubmix *InSoundSubmix, bool bInAutoDisable)
Set whether or not a submix is auto-disabled.
virtual void SetSubmixAutoDisableTime (USoundSubmix *InSoundSubmix, float InDisableTime)
Set what the auto-disable time is.
virtual void SetSubmixDryLevel (USoundSubmix *InSoundSubmix, float InDryLevel)
Set the wet-dry level of the given submix.
virtual void SetSubmixEffectChainOverride (USoundSubmix *InSoundSubmix, const TArray< FSoundEffectSubmixPtr > &InSubmixEffectChain, float InCrossfadeTime)
Sets a submix effect chain override for the given submix.
virtual void SetSubmixModulationBaseLevels (USoundSubmix *InSoundSubmix, float InVolumeModBase, float InWetModBase, float InDryModBase)
virtual void SetSubmixOutputVolume (USoundSubmix *InSoundSubmix, float InOutputVolume)
Set the wet-dry level of the given submix.
virtual void SetSubmixWetDryLevel (USoundSubmix *InSoundSubmix, float InOutputVolume, float InWetLevel, float InDryLevel)
Set the wet-dry level of the given submix.
virtual void SetSubmixWetLevel (USoundSubmix *InSoundSubmix, float InWetLevel)
Set the wet-dry level of the given submix.
void SetTransientPrimaryVolume (float TransientPrimaryVolume)
void SetUseAttenuationForNonGameWorlds (bool bInUseAttenuationForNonGameWorlds)
Set whether or not we force the use of attenuation for non-game worlds (as by default we only care about game worlds)
bool ShouldUseRealtimeDecompression (bool bForceFullDecompression, const FSoundGroup &SoundGroup, USoundWave *SoundWave, float CompressedDurationThreshold) const
Returns true if a sound wave should be decompressed.
bool SoundIsAudible (USoundBase *Sound, const UWorld *World, const FVector &Location, const FSoundAttenuationSettings *AttenuationSettingsToApply, float MaxDistance, float FocusFactor) const
Checks if the given sound would be audible.
bool SpatializationPluginInterfacesAvailable ()
virtual void StartEnvelopeFollowing (USoundSubmix *InSubmix)
This is called by a USoundSubmix to start envelope following on a submix isntance on this device.
virtual void StartRecording (USoundSubmix *InSubmix, float ExpectedRecordingDuration)
This is called by a USoundSubmix to start recording a submix instance on this device.
virtual void StartSpectrumAnalysis (USoundSubmix *InSubmix, const FSoundSpectrumAnalyzerSettings &InSettings)
void StopActiveSound (FActiveSound *ActiveSound)
(Deprecated in favor of AddSoundToStop).
void StopActiveSound (uint64 AudioComponentID)
Removes the active sound for the specified audio component.
virtual void StopAllSounds (bool bShouldStopUISounds=false)
Stops all game sounds (and possibly UI) sounds.
virtual void StopEnvelopeFollowing (USoundSubmix *InSubmix)
This is called by a USoundSubmix when we stop envelope following a submix instance on this device.
virtual Audio::FAlignedFloatBuffer & StopRecording (USoundSubmix *InSubmix, float &OutNumChannels, float &OutSampleRate)
This is called by a USoundSubmix when we stop recording a submix on this device.
void StopSoundsUsingResource (USoundWave *SoundWave, TArray< UAudioComponent * > *StoppedComponents=nullptr)
Stop any playing sounds that are using a particular SoundWave.
virtual void StopSpectrumAnalysis (USoundSubmix *InSubmix)
void StopTestComponent ()
virtual bool SupportsRealtimeDecompression () const
Whether this device supports realtime decompression of sound waves (i.e.
void Suspend (bool bGameTicking)
Suspend/resume all sounds (global pause for device suspend/resume, etc.)
virtual void SuspendContext ()
Suspend any context related objects.
void Teardown ()
Tears down the audio device.
virtual void TeardownHardware ()
Shuts down any platform specific hardware/APIs.
UE_DEPRECATED (4.13, "Direct access of SoundClasses is no longer allowed. Instead you should use the SoundMixClassOverride system") const TMap< USoundClass *
UE_DEPRECATED (4.25, "Use ClearListenerAttenuationOverride that passes a ListenerIndex instead") void ClearListenerAttenuationOverride()
Removes a listener attenuation override.
UE_DEPRECATED (4.25, "Use GetDistanceSquaredToListener to check against a specific Listener") 1 float GetSquaredDistanceToListener(const FVector &Location
UE_DEPRECATED (4.25, "Use LocationIsAudible that passes a ListenerIndex to check against a specific Listener") 1 bool LocationIsAudible(const FVector &Location
Checks to see if a coordinate is within a distance of the given listener.
UE_DEPRECATED (4.25, "Use ParseAttenuation that passes a ListenerIndex instead") bool IsUsingListenerAttenuationOverride() const
Whether device is using listener attenuation override or not.
UE_DEPRECATED (4.25, "Use ParseAttenuation that passes a ListenerIndex instead") const FVector &GetListenerAttenuationOverride() const
Returns the listener attenuation override.
UE_DEPRECATED (4.25, "Use SetListenerAttenuationOverride that passes a ListenerIndex instead") void SetListenerAttenuationOverride(const FVector AttenuationPosition)
Sets an override for the listener to do attenuation calculations.
UE_DEPRECATED (5.0, "This call cannot be called from the GameThread & AudioComponents can now execute multiple ActiveSound instances at once. Use 'SendCommandToActiveSounds' instead.") 1 FActiveSound *FindActiveSound(uint64 AudioComponentID)
Finds the active sound for the specified audio component ID.
UE_DEPRECATED (5.1, "Do not access this member directly, it is not used. Call GetSpatializationPluginInterface() instead.") TAudioSpatializationPtr SpatializationPluginInterface
UE_DEPRECATED (5.1, "GetMasterVolume has been deprecated. Please use GetPrimaryVolume instead.") float GetMasterVolume() const
UE_DEPRECATED (5.1, "GetTransientMasterVolume has been deprecated. Please use GetTransientPrimaryVolume instead.") float GetTransientMasterVolume() const
UE_DEPRECATED (5.1, "SetTransientMasterVolume has been deprecated. Please use SetTransientPrimaryVolume instead.") 1 void SetTransientMasterVolume(float TransientPrimaryVolume)
UE_DEPRECATED(5.1, "This member is no longer in use. Use the return value of GetCurrentSpatializationPluginInterfaceInfo()") uint8 bSpatializationIsExternalSend UE_DEPRECATED (5.1, "This member is no longer in use. Use the return value of GetCurrentSpatializationPluginInterfaceInfo()") int32 MaxChannelsSupportedBySpatializationPlugin
Max amount of channels a source can be to be spatialized by our active spatialization plugin.
UE_DEPRECATED (5.1, "UpdateSubmixModulationSettings taking single modulators is deprecated. Use the overload that allows for modulator sets") virtual void UpdateSubmixModulationSettings(USoundSubmix *InSoundSubmix
UE_DEPRECATED (5.3, "NotifyPending is deprecated in public scope. Use IActiveSoundUpdateInterface::NotifyActiveSoundDeleting instead.") void NotifyPendingDelete(FActiveSound &ActiveSound) const
Notifies subsystems an active sound is about to be deleted (called on audio thread) - Deprecated, see NotifySubsystemsActiveSoundDeleting.
template<typename TSubsystemClass>
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const TArray< TSubsystemClass * > &GetSubsystemArray() const
Gets all Subsystems of specified type, this is only necessary for interfaces that can have multiple implementations instanced at a time.
UE_DEPRECATED (5.4, "Use RegisterSubmixBufferListener version that requires a shared reference to a listener and provide explicit reference to a submix: use GetMainSubmixObject to register with the Main Output Submix (rather than nullptr for safety), and instantiate buffer listener via the shared pointer API.") 1 virtual void RegisterSubmixBufferListener(ISubmixBufferListener *InSubmixBufferListener
UE_DEPRECATED (5.4, "Use UnregisterSubmixBufferListener version that requires a shared reference to a listener and provide explicit reference to a submix: use GetMainSubmixObject to unregister from the Main Output Submix (rather than nullptr for safety), and instantiate buffer listener via the shared pointer API.") 1 virtual void UnregisterSubmixBufferListener(ISubmixBufferListener *InSubmixBufferListener
UE_DEPRECATED (5.5, "No longer needed for resource managment, existing calls may be deleted") 1 void StopSourcesUsingBuffer(FSoundBuffer *SoundBuffer)
Stops any sound sources which are using the given buffer.
void UnlinkActiveSoundFromComponent (const FActiveSound &InActiveSound)
Disables ActiveSound from responding to calls from its associated AudioComponent.
void UnregisterPluginListener (const TAudioPluginListenerPtr PluginListener)
Unregisters a third party listener-observer to this audio device.
void UnregisterSoundClass (USoundClass *SoundClass)
Unregisters a sound class.
virtual void UnregisterSoundSubmix (const USoundSubmixBase *SoundSubmix, const bool bReparentChildren)
Unregisters the sound submix.
virtual void UnregisterSubmixBufferListener (TSharedRef< ISubmixBufferListener, ESPMode::ThreadSafe > InSubmixBufferListener, USoundSubmix &SoundSubmix)
Unregisters the provided submix buffer listener with the given submix.
void Update (bool bGameTicking)
The audio system's main "Tick" function.
void UpdateActiveSoundPlaybackTime (bool bIsTimeTicking)
Update the active sound playback time.
void UpdateAudioVolumeProxy (const FAudioVolumeProxy &Proxy)
virtual void UpdateDeviceDeltaTime ()
Sets the update delta time for the audio frame.
void * UpdateEffect (FSoundSource *Source)
Platform dependent call to update the sound output with new parameters The audio system's main "Tick" function.
virtual void UpdateGameThread ()
Update called on game thread.
virtual void UpdateHardware ()
Lets the platform any tick actions.
virtual void UpdateHardwareTiming ()
Updates timing information for hardware.
virtual void UpdateSourceEffectChain (const uint32 SourceEffectChainId, const TArray< FSourceEffectChainEntry > &SourceEffectChain, const bool bPlayEffectChainTails)
Updates the source effect chain.
virtual void UpdateSubmixModulationSettings (USoundSubmix *InSoundSubmix, const TSet< TObjectPtr< USoundModulatorBase > > &InOutputModulation, const TSet< TObjectPtr< USoundModulatorBase > > &InWetLevelModulation, const TSet< TObjectPtr< USoundModulatorBase > > &InDryLevelModulation)
virtual void UpdateSubmixProperties (USoundSubmixBase *InSubmix)
Updates the submix properties of any playing submix instances.
void UpdateVirtualLoops (bool bForceUpdate)
virtual bool ValidateAPICall (const TCHAR *Function, uint32 ErrorCode)
Check for errors and output a human readable string.
Public Member Functions inherited from FExec
virtual ~FExec ()
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Exec handler.
Static Public Member Functions
static bool CanUseVRAudioDevice ()
Query if the editor is in VR Preview for the current play world.
static UAudioComponent * CreateComponent (USoundBase *Sound, const FCreateComponentParams &Params=FCreateComponentParams())
Creates an audio component to handle playing a sound.
static int32 FindClosestListenerIndex (const FTransform &SoundTransform, const TArray< FListener > &InListeners)
Returns the index of the listener closest to the given sound transform.
static FAudioDeviceManager * GetAudioDeviceManager ()
Returns the audio device manager.
static FAudioDeviceHandle GetMainAudioDevice ()
Returns the main audio device of the engine.
static float GetMaxWorldDistance ()
Returns the global maximum distance used in the audio engine.
static const FAudioQualitySettings & GetQualityLevelSettings ()
Returns the quality settings used by the default audio settings.
template<typename TSubsystemClass>
static FORCEINLINE TSubsystemClass * GetSubsystem (const FAudioDeviceHandle &InHandle)
Get a Subsystem of specified type from the provided AudioDeviceHandle returns nullptr if the Subsystem cannot be found or the AudioDeviceHandle is invalid.
static bool IsOcclusionPluginLoaded ()
static bool IsReverbPluginLoaded ()
static bool IsSourceDataOverridePluginLoaded ()
static bool LegacyReverbDisabled ()
Data Fields
uint8 bAudioMixerModuleLoaded: 1
Whether or not the audio mixer module is being used by this device.
uint8 bDisableAudioCaching:1
HACK: Temporarily disable audio caching.
uint8 bIsAudioDeviceHardwareInitialized: 1
Whether or not the lower-level audio device hardware initialized.
uint8 bIsBakedAnalysisEnabled: 1
If baked analysis querying is enabled.
uint8 bIsStoppingVoicesEnabled: 1
uint8 bOcclusionIsExternalSend:1
Whether or not various audio plugin interfaces are external sends.
uint8 bReverbIsExternalSend:1
const FTransform const float MaxDistance const
const FTransform &ListenerTransform const
Audio::FDeviceId DeviceID
The handle for this audio device used in the audio device manager.
USoundModulatorBase USoundModulatorBase USoundModulatorBase * InDryLevelModulation
USoundModulatorBase * InOutputModulation
USoundModulatorBase USoundModulatorBase * InWetLevelModulation
TArray< FListenerProxy > ListenerProxies
const FTransform & ListenerTransform
TAudioModulationPtr ModulationInterface
3rd party modulation interface
int32 NumPrecacheFrames
The number of frames to precache.
int32 NumStoppingSources
The number of sources to reserve for stopping sounds.
TAudioOcclusionPtr OcclusionInterface
3rd party occlusion interface.
FAudioPlatformSettings PlatformSettings
The platform specific audio settings.
TArray< TAudioPluginListenerPtr > PluginListeners
3rd party listener observers registered to this audio device.
TAudioReverbPtr ReverbPluginInterface
3rd party reverb interface.
int32 SampleRate
The sample rate of all the audio devices.
USoundSubmix * SoundSubmix = nullptr)
TAudioSourceDataOverridePtr SourceDataOverridePluginInterface
3rd party source data override interface.
Protected Member Functions
void HandlePause (bool bGameTicking, bool bGlobalPause=false)
Handle pausing/unpausing of sources when entering or leaving pause mode, or global pause (like device suspend)
void InitializeSubsystemCollection ()
Create our subsystem collection root object and initialize subsystems.
void InitSoundSources ()
Set up the initial sound sources Allows us to initialize sound source early on, allowing for render callback hookups for iOS Audio.
FORCEINLINE bool IsInitialized () const
Whether the device was initialized.
void NotifyAudioDevicePostRender (const FAudioDeviceRenderInfo &InInfo)
void NotifyAudioDevicePreRender (const FAudioDeviceRenderInfo &InInfo)
void NotifySubsystemsActiveSoundCreated (FActiveSound &ActiveSound) const
Notifies subsystems an active sound has just been added (called on audio thread).
void NotifySubsystemsActiveSoundDeleting (FActiveSound &ActiveSound) const
Notifies subsystems an active sound is about to be deleted (called on audio thread).
void NotifySubsystemsSetOwner (FActiveSound &ActiveSound, const UObject *Owner) const
Notifies subsystems an owning object has been associated with a sound.
void NotifySubsystemsVirtualizedSoundCreated (FActiveSound &ActiveSound) const
Notifies subsystems a virtualized sound has just been added (called on audio thread).
void NotifySubsystemsVirtualizedSoundDeleting (FActiveSound &ActiveSound) const
Notifies subsystems a virtualized sound is about to be deleted (called on audio thread).
virtual void OnListenerUpdated (const TArray< FListener > &InListeners)
This is overridden in Audio::FMixerDevice to propogate listener information to the audio thread.
void StartSources (TArray< FWaveInstance * > &WaveInstances, int32 FirstActiveIndex, bool bGameTicking)
Start and/or update any sources that have a high enough priority to play.
void StopSources (TArray< FWaveInstance * > &WaveInstances, int32 FirstActiveIndex)
Stop sources that need to be stopped, and touch the ones that need to be kept alive Stop sounds that are too low in priority to be played.
UE_DEPRECATED (5.5, "NotifyAddActiveSound is deprecated. Use NotifySubsystemsActiveSoundCreated instead.") void NotifyAddActiveSound(FActiveSound &ActiveSound) const
UE_DEPRECATED (5.5, "NotifyPendingDeleteInternal is deprecated. Use NotifySubsystemsActiveSoundDeleting and/or NotifySubsystemsVirtualizedSoundDeleting instead.") void NotifyPendingDeleteInternal(FActiveSound &ActiveSound) const
Protected Member Functions inherited from FExec
virtual bool Exec_Dev (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in non-shipping targets.
virtual bool Exec_Editor (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in editor.
virtual bool Exec_Runtime (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is called on all targets where UE_ALLOW_EXEC_COMMANDS is true.
Protected Attributes
double AudioClock
The audio clock from the audio hardware.
uint8 bAllowCenterChannel3DPanning: 1
Whether or not we allow center channel panning (audio mixer only feature.)
FAudioSpatializationInterfaceInfo * CurrentSpatializationInterfaceInfoPtr = nullptr
FName CurrentSpatializationPluginInterfaceName
3rd party audio spatialization interface.
FDelegateHandle DeviceCreatedHandle
float DeviceDeltaTime
FDelegateHandle DeviceDestroyedHandle
FAudioEffectsManager * Effects
Interface to audio effects processing.
TArray< FSoundSource * > FreeSources
TArray< FListener > Listeners
FOnAudioDevicePostRender OnAudioDevicePostRender
FOnAudioDevicePreRender OnAudioDevicePreRender
FAudioPluginInitializationParams PluginInitializationParams
Cached parameters passed to the initialization of various audio plugins.
FCriticalSection RenderStateCallbackListCritSec
TArray< FSoundSource * > Sources
TArray< FAudioSpatializationInterfaceInfo > SpatializationInterfaces
Private Types
using FToggleSoloPtr = void (Audio::FAudioDebugger::*)(FName InName, bool bExclusive)
Handles all argument parsing for the solo commands in one place.
Private Member Functions
void AddNewActiveSoundInternal (const FActiveSound &InActiveSound, TArray< FAudioParameter > &&InDefaultParams, FAudioVirtualLoop *InVirtualLoopToRetrigger=nullptr)
Adds an active sound to the audio device.
void ApplyClassAdjusters (USoundMix *SoundMix, float InterpValue, float DeltaTime)
Sets the sound class adjusters from a SoundMix.
bool ApplySoundMix (USoundMix *NewMix, FSoundMixState *SoundMixState)
Set the mix for altering sound class properties.
void ClearSoundMix (USoundMix *SoundMix)
Clear the effect of a SoundMix completely - only called after checking it's safe to.
USoundMix * FindNextHighestEQPrioritySoundMix (USoundMix *IgnoredSoundMix)
Find the SoundMix with the next highest EQ priority to the one passed in.
float GetInterpolatedFrequency (const float InFrequency, const float InterpValue) const
Retrieve the filter frequency to use.
int32 GetNumPrecacheFrames () const
Returns the number of frames to use per precache buffer.
virtual FAudioPlatformSettings GetPlatformSettings () const
Allow platforms to optionally specify low-level audio platform settings.
void GetSoundClassInfo (TMap< FName, FAudioClassInfo > &AudioClassInfos)
Gets a summary of loaded sound collated by class.
bool HandleAudio3dVisualizeCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleAudioDebugSound (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleAudioMemoryInfo (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleAudioMixerDebugSound (const TCHAR *Cmd, FOutputDevice &Ar)
void HandleAudioSoloCommon (const TCHAR *Cmd, FOutputDevice &Ar, FToggleSoloPtr Funct)
bool HandleAudioSoloSoundClass (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleAudioSoloSoundCue (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleAudioSoloSoundWave (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleClearSoloCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleDisableHPFCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleDisableLPFCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleDisableRadioCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleDumpSoundInfoCommand (const TCHAR *Cmd, FOutputDevice &Ar)
Exec command handlers.
bool HandleEnableHRTFForAllCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleEnableRadioCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleGetDynamicSoundVolumeCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleIsolateDryAudioCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleIsolateReverbCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleListAudioComponentsCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleListSoundClassesCommand (const TCHAR *Cmd, FOutputDevice &Ar)
Lists a summary of loaded sound collated by class.
bool HandleListSoundClassVolumesCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleListSoundDurationsCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleListWavesCommand (const TCHAR *Cmd, FOutputDevice &Ar)
Lists all the playing waveinstances and their associated source.
bool HandlePlayAllPIEAudioCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleResetAllDynamicSoundVolumesCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleResetDynamicSoundVolumeCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleResetSoundStateCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleSetBaseSoundMixCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleSetDynamicSoundCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleShowSoundClassHierarchyCommand (const TCHAR *Cmd, FOutputDevice &Ar)
shows sound class hierarchy
bool HandleSoloCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleSoundClassFixup (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleSoundTemplateInfoCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleTestHPFCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleTestLFEBleedCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleTestLPFCommand (const TCHAR *Cmd, FOutputDevice &Ar)
bool HandleToggleSpatializationExtensionCommand (const TCHAR *Cmd, FOutputDevice &Ar)
void InitializePluginListeners (UWorld *World)
Initializes all plugin listeners belonging to this audio device.
void InitSoundParams (FActiveSound &InOutActiveSound, TArray< FAudioParameter > InDefaultParams, bool bInIsVirtualLoopRealzing) const
Initializes the parameters on the active sound.
float InterpolateAdjuster (const float Adjuster, const float InterpValue) const
Takes an adjuster value and modifies it by the proportion that is currently in effect.
void NotifyPluginListenersWorldChanged (UWorld *World)
Notifies all plugin listeners belonging to this audio device that the world changed.
void ParseSoundClasses (float InDeltaTime)
Parses the sound classes and propagates multiplicative properties down the tree.
void ProcessingPendingActiveSoundStops (bool bForceDelete=false)
Processes the set of pending sounds that need to be stopped.
void RecurseIntoSoundClasses (USoundClass *CurrentClass, FSoundClassProperties &ParentProperties)
Internal helper function used by ParseSoundClasses to traverse the tree.
void RecursiveApplyAdjuster (const FSoundClassAdjuster &InAdjuster, USoundClass *InSoundClass)
Recursively apply an adjuster to the passed in sound class and all children of the sound class.
bool RemoveVirtualLoop (FActiveSound &ActiveSound)
void ReportSoundFailedToStart (const uint64 AudioComponentID, FAudioVirtualLoop *VirtualLoop)
Reports if a sound fails to start when attempting to create a new active sound.
void SendUpdateResultsToGameThread (int32 FirstActiveIndex)
bool ShouldUseAttenuation (const UWorld *World) const
Check whether we should use attenuation settings.
void ShowSoundClassHierarchy (FOutputDevice &Ar, USoundClass *SoundClass=nullptr, int32 Indent=0) const
Lists a summary of loaded sound collated by class.
bool SoundIsAudible (const FActiveSound &NewActiveSound)
Checks if the given sound would be audible.
void StopOldestStoppingSource ()
Stops oldest sound source.
bool TryClearingEQSoundMix (USoundMix *SoundMix)
Attempt to remove this SoundMix's EQ effect - it may not currently be active.
bool TryClearingSoundMix (USoundMix *SoundMix, FSoundMixState *SoundMixState)
Attempt to clear the effect of a particular SoundMix.
void UpdateAudioEngineSubsystems ()
Updates audio engine subsystems on this device.
void UpdateAudioVolumeEffects ()
Updates audio volume effects.
void UpdateConcurrency (TArray< FWaveInstance * > &WaveInstances, TArray< FActiveSound * > &ActiveSoundsCopy)
Stops quiet/low priority sounds due to being evaluated as not fulfilling concurrency requirements.
void UpdateHighestPriorityReverb ()
Find the current highest priority reverb after a change to the list of active ones.
void UpdatePassiveSoundMixModifiers (TArray< FWaveInstance * > &WaveInstances, int32 FirstActiveIndex)
Updates list of SoundMixes that are applied passively, pushing and popping those that change.
void UpdateReferencedSoundWaves ()
void UpdateSoundClassProperties (float DeltaTime)
Construct the CurrentSoundClassProperties map.
void UpdateSoundDuration (FWaveInstance *WaveInstance, bool bGameTicking) const
Adjusts the active sound duration to make up for decode latency.
void UpdateSoundMix (USoundMix *SoundMix, FSoundMixState *SoundMixState)
Updates the state of a sound mix if it is pushed more than once.
void UpdateUnpreparedSound (FWaveInstance *WaveInstance, bool bGameTicking) const
Called by StartSources when sounds are not prepared to Init for whatever reason.
void VirtualizeInactiveLoops ()
Private Attributes
TMap< FName, FActivatedReverb > ActivatedReverbs
Reverb Effects activated without volumes - Game Thread owned.
TArray< FActiveSound * > ActiveSounds
The audio thread update delta time for this audio thread update tick.
TArray< FWaveInstance * > ActiveWaveInstances
TMap< uint64, TArray< FActiveSound * > > AudioComponentIDToActiveSoundMap
TMap< uint64, bool > AudioComponentIDToCanHaveMultipleActiveSoundsMap
Used to determine if a given Audio Component should be allowed to have multiple simultaneous associated active sounds.
TMap< FName, FName > AudioStateProperties
A generic mapping of FNames, used to store and retrieve tokens across the engine boundary.
FCriticalSection AudioThreadReferenceCritSec
TMap< uint32, FAudioVolumeProxy > AudioVolumeProxies
uint8 bAllowPlayWhenSilent:1
Whether or not we're supporting zero volume wave instances.
USoundMix * BaseSoundMix
The Base SoundMix that's currently active.
uint8 bGameWasTicking:1
uint8 bHasActivatedReverb:1
Whether the value in HighestPriorityActivatedReverb should be used - Audio Thread owned.
uint8 bHRTFDisabled:1
Whether or not HRTF is disabled.
bool bHRTFDisabled_OnGameThread
Gamethread representation of whether HRTF is disabbled for all 3d sounds.
uint8 bHRTFEnabledForAll:1
Whether HRTF is enabled for all 3d sounds.
bool bHRTFEnabledForAll_OnGameThread
Gamethread representation of whether HRTF is enabled for all 3d sounds.
uint8 bIsDeviceMuted:1
Whether the audio device is active (current audio device in-focus in PIE)
uint8 bIsInitialized:1
Whether the audio device has been initialized.
uint8 bModulationInterfaceEnabled:1
uint8 bOcclusionInterfaceEnabled:1
uint8 bPluginListenersInitialized:1
Whether or not we've initialized plugin listeners array.
uint8 bReverbInterfaceEnabled:1
uint8 bSourceDataOverrideInterfaceEnabled:1
uint8 bSpatializationInterfaceEnabled:1
Whether or not various audio plugin interfaces are enabled.
uint8 bStartupSoundsPreCached:1
True once the startup sounds have been precached.
uint8 bUseAttenuationForNonGameWorlds:1
Whether or not we force the use of attenuation for non-game worlds (as by default we only care about game worlds)
FSoundConcurrencyManager ConcurrencyManager
FAudioVolumeSettings CurrentAudioVolumeSettings
The current audio volume settings the listener is in.
UReverbEffect * CurrentReverbEffect
uint64 CurrentTick
TEnumAsByte< enum EDebugState > DebugState
The debug state of the audio device.
TObjectPtr< USoundMix > DefaultBaseSoundMix
The Base SoundMix that should be applied by default.
float DefaultReverbSendLevel
The default reverb send level to use for sources which have reverb applied but don't have an attenuation settings.
TMap< USoundClass *, FSoundClassDynamicProperties > DynamicSoundClassProperties
FGlobalFocusSettings GlobalFocusSettings
The global focus settings.
FGlobalFocusSettings GlobalFocusSettings_GameThread
float GlobalMaxPitch
float GlobalMinPitch
FDynamicParameter GlobalPitchScale
Global dynamic pitch scale parameter.
FActivatedReverb HighestPriorityActivatedReverb_AudioThread
The activated reverb that currently has the highest priority - Audio Thread owned.
TArray< FMatrix > InverseListenerTransforms
Inverse listener transformations, used for spatialization.
double LastUpdateTime
Timestamp of the last update.
int32 MaxActiveSoundsAddedPerFrame
Max number of active sounds to add per frame.
int32 MaxChannels
The maximum number of concurrent audible sounds.
int32 MaxChannels_GameThread
float MaxChannelsScale
Normalized (0.0f - 1.0f) scalar multiplier on max channels.
float MaxChannelsScale_GameThread
int32 MaxSources
The maximum number of sources.
int32 NextResourceID
Next resource ID to assign out to a wave/buffer.
uint32 OneShotCount
A count of the number of one-shot active sounds.
TSharedPtr< FActivatedReverb > PendingActivatedReverb
Most recently activated in-flight reverb going from the GT to the AT.
TQueue< FActiveSound * > PendingAddedActiveSounds
Pending active sounds waiting to be added.
TArray< FActiveSound * > PendingSoundsToDelete
A set of sounds which need to be deleted but weren't able to be deleted due to pending async operations.
TSet< FActiveSound * > PendingSoundsToStop
Set of sounds which will be stopped next audio frame update.
float PlatformAudioHeadroom
A volume headroom to apply to specific platforms to achieve better platform consistency.
TArray< USoundWave * > PrecachingSoundWaves
TArray< TObjectPtr< USoundMix > > PrevPassiveSoundMixModifiers
List of passive SoundMixes active last frame.
float PrimaryVolume
The master volume of the game combines the FApp::GetVolumeMultipler() value and the TransientPrimaryVolume.
TArray< TObjectPtr< USoundWave > > ReferencedSoundWaves
Array of sound waves to add references to avoid GC until guaranteed to be done with precache or decodes.
TArray< USoundWave * > ReferencedSoundWaves_AudioThread
TArray< FSoundClassAdjuster > SoundClassAdjustersCopy
Cached copy of sound class adjusters array.
TMap< USoundClass *, FSoundClassProperties > SoundClasses
Current properties of all sound classes.
TMap< USoundMix *, FSoundMixClassOverrideMap > SoundMixClassEffectOverrides
Map of sound mix sound class overrides.
TMap< TObjectPtr< USoundMix >, FSoundMixState > SoundMixModifiers
Map of sound mixes currently affecting audio properties.
FAudioSubsystemCollection SubsystemCollection
Subsystems tied to this device's lifecycle.
TStrongObjectPtr< UAudioSubsystemCollectionRoot > SubsystemCollectionRoot
Anchor used to connect UAudioEngineSubsystems to FAudioDevice.
TStrongObjectPtr< UAudioComponent > TestAudioComponent
An AudioComponent to play test sounds on.
float TransientPrimaryVolume
transient master volume multiplier that can be modified at runtime without affecting user settings automatically reset to 1.0 on level change
TMap< FActiveSound *, FAudioVirtualLoop > VirtualLoops
Array of dormant loops stopped due to proximity/applicable concurrency rules that can be retriggered.
TMap< FWaveInstance *, FSoundSource * > WaveInstanceSourceMap
Set of sources used to play sounds (platform will subclass these)
TMap< uint32, TPair< FReverbSettings, FInteriorSettings > > WorldIDToDefaultAudioVolumeSettingsMap
Friends
class FAudioEffectsManager
class FSoundConcurrencyManager
class FSoundSource
Detailed Description
Definition at line 419 of file AudioDevice.h.
Member Typedef Documentation
FToggleSoloPtr
using FAudioDevice::FToggleSoloPtr = void (Audio::FAudioDebugger::*)(FName InName, bool bExclusive) private
Handles all argument parsing for the solo commands in one place.
Definition at line 484 of file AudioDevice.h.
Constructor & Destructor Documentation
FAudioDevice()
FAudioDevice::FAudioDevice ()
Constructor.
Referenced by FAudioDevice::FAudioSpatializationInterfaceInfo::FAudioSpatializationInterfaceInfo(), SetHRTFDisabled(), and SetHRTFEnabledForAll().
~FAudioDevice()
virtual FAudioDevice::~FAudioDevice () virtual
Member Function Documentation
ActivateReverbEffect()
void FAudioDevice::ActivateReverbEffect (UReverbEffect * ReverbEffect, FName TagName, float Priority, float Volume, float FadeTime)
Activates a Reverb Effect without the need for a volume.
Parameters
ReverbEffect Reverb Effect to use
TagName Tag to associate with Reverb Effect
Priority Priority of the Reverb Effect
Volume Volume level of Reverb Effect
FadeTime Time before Reverb Effect is fully active
References ActivateReverbEffect(), and Volume.
Referenced by ActivateReverbEffect().
AddAudioVolumeProxy()
void FAudioDevice::AddAudioVolumeProxy (const FAudioVolumeProxy & Proxy)
References AddAudioVolumeProxy(), and const.
Referenced by AddAudioVolumeProxy().
AddEnvelopeFollowerDelegate()
virtual void FAudioDevice::AddEnvelopeFollowerDelegate (USoundSubmix * InSubmix, const FOnSubmixEnvelopeBP & OnSubmixEnvelopeBP) virtual
Adds an envelope follower delegate to the submix for this audio device.
AddNewActiveSound() [1/2]
void FAudioDevice::AddNewActiveSound (const FActiveSound & ActiveSound, const TArray< FAudioParameter > * InDefaultParams = nullptr)
Adds an active sound to the audio device.
AddNewActiveSound() [2/2]
void FAudioDevice::AddNewActiveSound (const FActiveSound & ActiveSound, TArray< FAudioParameter > && InDefaultParams)
Adds an active sound to the audio device.
AddNewActiveSoundInternal()
void FAudioDevice::AddNewActiveSoundInternal (const FActiveSound & InActiveSound, TArray< FAudioParameter > && InDefaultParams, FAudioVirtualLoop * InVirtualLoopToRetrigger = nullptr) private
Adds an active sound to the audio device.
Can be a new active sound or one provided by the re-triggering loop system.
AddPatchForSubmix()
virtual Audio::FPatchOutputStrongPtr FAudioDevice::AddPatchForSubmix (uint32 InObjectId, float InPatchGain) virtual
References AddPatchForSubmix().
Referenced by AddPatchForSubmix().
AddPatchInputForAudioBus()
virtual Audio::FPatchInput FAudioDevice::AddPatchInputForAudioBus (uint32 InAudioBusId, int32 InFrames, int32 InChannels, float InGain = 1.f) virtual
References AddPatchInputForAudioBus().
Referenced by AddPatchInputForAudioBus().
AddPatchOutputForAudioBus()
virtual Audio::FPatchOutputStrongPtr FAudioDevice::AddPatchOutputForAudioBus (uint32 InAudioBusId, int32 InFrames, int32 InChannels, float InGain = 1.f) virtual
References AddPatchOutputForAudioBus().
Referenced by AddPatchOutputForAudioBus().
AddPostRenderDelegate()
FDelegateHandle FAudioDevice::AddPostRenderDelegate (const FOnAudioDevicePostRender::FDelegate & InDelegate)
AddPreRenderDelegate()
FDelegateHandle FAudioDevice::AddPreRenderDelegate (const FOnAudioDevicePreRender::FDelegate & InDelegate)
AddReferencedObjects()
void FAudioDevice::AddReferencedObjects (FReferenceCollector & Collector)
Track references to UObjects.
AddSoundToStop()
void FAudioDevice::AddSoundToStop (FActiveSound * SoundToStop)
Marks a sound to be stopped.
Returns true if added to stop, false if already pending stop.
AddSpectralAnalysisDelegate()
virtual void FAudioDevice::AddSpectralAnalysisDelegate (USoundSubmix * InSubmix, const FSoundSpectrumAnalyzerDelegateSettings & InDelegateSettings, const FOnSubmixSpectralAnalysisBP & OnSubmixSpectralAnalysisBP) virtual
AddVirtualLoop()
void FAudioDevice::AddVirtualLoop (const FAudioVirtualLoop & InVirtualLoop)
ApplyClassAdjusters()
void FAudioDevice::ApplyClassAdjusters (USoundMix * SoundMix, float InterpValue, float DeltaTime) private
Sets the sound class adjusters from a SoundMix.
Parameters
SoundMix The SoundMix to apply adjusters from
InterpValue Proportion of adjuster to apply
DeltaTime The current frame delta time. Used to interpolate sound class adjusters.
References DeltaTime.
ApplyInteriorSettings()
void FAudioDevice::ApplyInteriorSettings (FActiveSound & ActiveSound, FSoundParseParameters & ParseParams) const
Applies interior settings from affecting volumes to the active sound (called on audio thread)
ApplySoundMix()
bool FAudioDevice::ApplySoundMix (USoundMix * NewMix, FSoundMixState * SoundMixState) private
Set the mix for altering sound class properties.
Parameters
NewMix The SoundMix to apply
SoundMixState The State associated with this SoundMix
AreStartupSoundsPreCached()
bool FAudioDevice::AreStartupSoundsPreCached () const inline
Definition at line 1888 of file AudioDevice.h.
References bStartupSoundsPreCached.
CanHaveMultipleActiveSounds()
bool FAudioDevice::CanHaveMultipleActiveSounds (uint64 AudioComponentID) const
Whether a given Audio Component ID should be allowed to have multiple associated Active Sounds.
References CanHaveMultipleActiveSounds(), and const.
Referenced by CanHaveMultipleActiveSounds().
CanUseVRAudioDevice()
bool FAudioDevice::CanUseVRAudioDevice () static
Query if the editor is in VR Preview for the current play world.
Returns false for non-editor builds
ClampPitch()
float FAudioDevice::ClampPitch (float InPitchScale) const
ClearListenerAttenuationOverride()
void FAudioDevice::ClearListenerAttenuationOverride (int32 ListenerIndex)
Removes a listener attenuation override for the specified listener.
Referenced by UE_DEPRECATED().
ClearSoundMix()
void FAudioDevice::ClearSoundMix (USoundMix * SoundMix) private
Clear the effect of a SoundMix completely - only called after checking it's safe to.
ClearSoundMixClassOverride()
void FAudioDevice::ClearSoundMixClassOverride (USoundMix * InSoundMix, USoundClass * InSoundClass, float FadeOutTime)
Clears a sound class override in the given sound mix.
References ClearSoundMixClassOverride().
Referenced by ClearSoundMixClassOverride().
ClearSoundMixModifier()
void FAudioDevice::ClearSoundMixModifier (USoundMix * SoundMix)
Clear the effect of one SoundMix completely.
Parameters
SoundMix The SoundMix to clear.
References ClearSoundMixModifier().
Referenced by ClearSoundMixModifier().
ClearSoundMixModifiers()
void FAudioDevice::ClearSoundMixModifiers ()
Clear the effect of all SoundMix modifiers.
References ClearSoundMixModifiers().
Referenced by ClearSoundMixModifiers().
ClearSubmixEffectChainOverride()
virtual void FAudioDevice::ClearSubmixEffectChainOverride (USoundSubmix * InSoundSubmix, float InCrossfadeTime) inline virtual
Clears all submix effect chain overrides from the submix.
Definition at line 1486 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
CountBytes()
virtual void FAudioDevice::CountBytes (FArchive & Ar) virtual
Counts the bytes for the structures used in this class.
References Ar.
CreateComponent()
UAudioComponent * FAudioDevice::CreateComponent (USoundBase * Sound, const FCreateComponentParams & Params = FCreateComponentParams()) static
Creates an audio component to handle playing a sound.
Parameters
Sound The USoundBase to play at the location.
Params The parameter block of properties to create the component based on
Returns
The created audio component if the function successfully created one or a nullptr if not successful. Note: if audio is disabled or if there were no hardware audio devices available, this will return nullptr.
References Params, and Sound.
CreateEffectsManager()
virtual FAudioEffectsManager * FAudioDevice::CreateEffectsManager () virtual
Creates a new platform specific sound source.
References FAudioEffectsManager.
CreateSoundSource()
virtual FSoundSource * FAudioDevice::CreateSoundSource () pure virtual
Creates a new platform specific sound source.
References FSoundSource.
DeactivateReverbEffect()
void FAudioDevice::DeactivateReverbEffect (FName TagName)
Deactivates a Reverb Effect not applied by a volume.
Parameters
TagName Tag associated with Reverb Effect to remove
References DeactivateReverbEffect().
Referenced by DeactivateReverbEffect().
Deinitialize()
void FAudioDevice::Deinitialize ()
De-initialization step that occurs after device destroyed broadcast, but before removal from the device manager.
DestroyEffect()
void FAudioDevice::DestroyEffect (FSoundSource * Source)
Platform dependent call to destroy any effect related data.
References FSoundSource, and Source.
DisablePCMAudioCaching()
virtual bool FAudioDevice::DisablePCMAudioCaching () const inline virtual
Whether or not the platform disables caching of decompressed PCM data (i.e.
to save memory on fixed memory platforms
Definition at line 1160 of file AudioDevice.h.
EnableDebugAudioOutput()
virtual void FAudioDevice::EnableDebugAudioOutput () inline virtual
Enables the audio device to output debug audio to test audio device output.
Definition at line 1287 of file AudioDevice.h.
EnableRadioEffect()
void FAudioDevice::EnableRadioEffect (bool bEnable = false)
Enables or Disables the radio effect.
References EnableRadioEffect().
Referenced by EnableRadioEffect().
FadeIn()
virtual void FAudioDevice::FadeIn () inline virtual
Definition at line 581 of file AudioDevice.h.
FadeOut()
virtual void FAudioDevice::FadeOut () inline virtual
Optional fadeout and fade in of audio to avoid clicks when closing or opening/reusing audio device.
Definition at line 580 of file AudioDevice.h.
FindClosestListenerIndex() [1/3]
int32 FAudioDevice::FindClosestListenerIndex (const FTransform & SoundTransform) const
Returns the index of the listener closest to the given sound transform.
FindClosestListenerIndex() [2/3]
int32 FAudioDevice::FindClosestListenerIndex (const FTransform & SoundTransform, const TArray< FListener > & InListeners) static
Returns the index of the listener closest to the given sound transform.
FindClosestListenerIndex() [3/3]
int32 FAudioDevice::FindClosestListenerIndex (const FVector & Position, float & OutSqDistance, bool AllowAttenuationOverrides) const
References FVector, and Position.
FindNextHighestEQPrioritySoundMix()
USoundMix * FAudioDevice::FindNextHighestEQPrioritySoundMix (USoundMix * IgnoredSoundMix) private
Find the SoundMix with the next highest EQ priority to the one passed in.
Parameters
SoundMix The highest priority SoundMix, which will be ignored
Returns
The next highest priority SoundMix or nullptr if one cannot be found
Flush()
void FAudioDevice::Flush (UWorld * WorldToFlush, bool bClearActivatedReverb = true)
Stop all the audio components and sources attached to the world.
nullptr world means all components.
FlushAudioRenderingCommands()
virtual void FAudioDevice::FlushAudioRenderingCommands (bool bPumpSynchronously = false) inline virtual
Allows audio rendering command queue to flush during audio device flush.
Parameters
bPumpSynchronously must be called in situations where the audio render thread is not being called.
Definition at line 597 of file AudioDevice.h.
FlushExtended()
virtual void FAudioDevice::FlushExtended (UWorld * WorldToFlush, bool bClearActivatedReverb) virtual
ForEachSubsystem()
template<typename TSubsystemClass> void FAudioDevice::ForEachSubsystem (TFunctionRef< void(TSubsystemClass *)> Operation) const inline
Performs the given operation on all subsystems of the given class.
It's safe to create new subsystems during this operation, but not to remove subsystems.
Definition at line 2002 of file AudioDevice.h.
References CastChecked(), ForEachSubsystem(), MoveTemp(), and SubsystemCollection.
Referenced by ForEachSubsystem().
GatherInteriorData()
void FAudioDevice::GatherInteriorData (FActiveSound & ActiveSound, FSoundParseParameters & ParseParams) const
Gathers data about interior volumes affecting the active sound (called on audio thread)
GetActiveReverb()
const TMap< FName, FActivatedReverb > & FAudioDevice::GetActiveReverb () const
GetActiveSounds()
const TArray< FActiveSound * > & FAudioDevice::GetActiveSounds () const inline
Definition at line 1173 of file AudioDevice.h.
References ActiveSounds, check, and IsInAudioThread().
GetActiveWaveInstances()
const TArray< FWaveInstance * > & FAudioDevice::GetActiveWaveInstances () const
GetAudioClock()
double FAudioDevice::GetAudioClock () const inline
Returns the audio clock of the audio device.
Not supported on all platforms.
Definition at line 1879 of file AudioDevice.h.
References AudioClock.
Referenced by GetInterpolatedAudioClock().
GetAudioDeviceList()
virtual void FAudioDevice::GetAudioDeviceList (TArray< FString > & OutAudioDeviceNames) const inline virtual
Returns an array of available audio devices names for the platform.
Definition at line 512 of file AudioDevice.h.
GetAudioDeviceManager()
FAudioDeviceManager * FAudioDevice::GetAudioDeviceManager () static
Returns the audio device manager.
GetAudioStateProperty()
FName FAudioDevice::GetAudioStateProperty (const FName & PropertyName) const
References PropertyName.
GetAudioTime()
virtual double FAudioDevice::GetAudioTime () const inline virtual
Return the audio stream time.
Definition at line 1281 of file AudioDevice.h.
GetAudioVolumeSettings()
void FAudioDevice::GetAudioVolumeSettings (const uint32 WorldID, const FVector & Location, FAudioVolumeSettings & OutSettings) const
References FVector, and Location.
GetAvailableSpatializationPluginNames()
TArray< FName > FAudioDevice::GetAvailableSpatializationPluginNames () const
Get the current list of available spatialization plugins.
GetAzimuth()
void FAudioDevice::GetAzimuth (const FAttenuationListenerData & OutListenerData, float & OutAzimuth, float & AbsoluteAzimuth) const
Returns the azimuth angle of the sound relative to the sound's nearest listener.
Used for 3d audio calculations.
GetBufferLength()
int32 FAudioDevice::GetBufferLength () const inline
Returns the buffer length of the audio device.
Definition at line 1310 of file AudioDevice.h.
References PlatformSettings.
GetCompressionDurationThreshold()
float FAudioDevice::GetCompressionDurationThreshold (const FSoundGroup & SoundGroup)
GetCurrentReverbEffect()
UReverbEffect * FAudioDevice::GetCurrentReverbEffect () const inline
Returns the currently applied reverb effect if there is one.
Definition at line 706 of file AudioDevice.h.
References check, CurrentReverbEffect, and IsInGameThread().
GetCurrentSourceEffectChain()
virtual bool FAudioDevice::GetCurrentSourceEffectChain (const uint32 SourceEffectChainId, TArray< FSourceEffectChainEntry > & OutCurrentSourceEffectChainEntries) inline virtual
Returns the current source effect chain entries set dynamically from BP or elsewhere.
Definition at line 1392 of file AudioDevice.h.
GetCurrentSpatializationPluginInterfaceInfo()
FAudioSpatializationInterfaceInfo FAudioDevice::GetCurrentSpatializationPluginInterfaceInfo ()
Referenced by GetSpatializationPluginInterface().
GetDefaultAudioSettings()
bool FAudioDevice::GetDefaultAudioSettings (uint32 WorldID, FReverbSettings & OutReverbSettings, FInteriorSettings & OutInteriorSettings) const
Gets the default reverb and interior settings for the provided world.
Returns true if settings with WorldID were located
GetDefaultBaseSoundMixModifier()
USoundMix * FAudioDevice::GetDefaultBaseSoundMixModifier () inline
Definition at line 1737 of file AudioDevice.h.
References DefaultBaseSoundMix.
GetDefaultReverbSendLevel()
float FAudioDevice::GetDefaultReverbSendLevel () const inline
Returns the default reverb send level used for sources which have reverb applied but no attenuation settings.
Definition at line 1943 of file AudioDevice.h.
References DefaultReverbSendLevel.
GetDeviceDeltaTime()
float FAudioDevice::GetDeviceDeltaTime () const
Returns the current audio device update delta time.
GetDistanceSquaredToListener()
bool FAudioDevice::GetDistanceSquaredToListener (const FVector & Location, int32 ListenerIndex, float & OutSqDistance) const
Sets OutSqDistance to the distance from location to the appropriate listener representation, depending on calling thread.
Returns true if listener position is valid, false if not (in which case, OutSqDistance is undefined).
References const, FVector, GetDistanceSquaredToListener(), and Location.
Referenced by GetDistanceSquaredToListener().
GetDistanceSquaredToNearestListener()
bool FAudioDevice::GetDistanceSquaredToNearestListener (const FVector & Location, float & OutSqDistance) const
Sets OutSqDistance to the distance from location the closest listener, depending on calling thread.
Returns true if listener position is valid, false if not (in which case, OutSqDistance is undefined).
References const, FVector, GetDistanceSquaredToNearestListener(), and Location.
Referenced by GetDistanceSquaredToNearestListener().
GetDistanceToNearestListener()
float FAudioDevice::GetDistanceToNearestListener (const FVector & Location) const
Returns the distance to the nearest listener from the given location.
References const, FVector, GetDistanceToNearestListener(), and Location.
Referenced by GetDistanceToNearestListener().
GetEffects() [1/2]
FAudioEffectsManager * FAudioDevice::GetEffects () inline
Return the pointer to the sound effects handler.
Definition at line 1712 of file AudioDevice.h.
References check, Effects, FAudioEffectsManager, and IsInAudioThread().
GetEffects() [2/2]
const FAudioEffectsManager * FAudioDevice::GetEffects () const inline
Return the pointer to the sound effects handler.
Definition at line 1721 of file AudioDevice.h.
References check, Effects, FAudioEffectsManager, and IsInAudioThread().
GetFocusFactor()
float FAudioDevice::GetFocusFactor (const float Azimuth, const FSoundAttenuationSettings & AttenuationSettings) const
Returns the focus factor of a sound based on its position and listener data.
GetGameDeltaTime()
float FAudioDevice::GetGameDeltaTime () const
Returns the game's delta time.
GetGlobalFocusSettings()
const FGlobalFocusSettings & FAudioDevice::GetGlobalFocusSettings () const
GetGlobalPitchRange()
TRange< float > FAudioDevice::GetGlobalPitchRange () const
Returns global pitch range.
GetGlobalPitchScale()
const FDynamicParameter & FAudioDevice::GetGlobalPitchScale () const inline
Definition at line 1910 of file AudioDevice.h.
References check, GlobalPitchScale, and IsInAudioThread().
GetInterpolatedAudioClock()
virtual double FAudioDevice::GetInterpolatedAudioClock () const inline virtual
Returns the audio clock interploated between audio device callbacks to provide a smoothed value.
Default implementation does not interpolate.
Definition at line 1884 of file AudioDevice.h.
References GetAudioClock().
GetInterpolatedFrequency()
float FAudioDevice::GetInterpolatedFrequency (const float InFrequency, const float InterpValue) const private
Retrieve the filter frequency to use.
Takes into account logarithmic nature of frequency.
GetListenerAttenuationOverride()
const FVector & FAudioDevice::GetListenerAttenuationOverride (int32 ListenerIndex) const
Returns the listener attenuation override for the specified listener.
References FVector.
Referenced by UE_DEPRECATED().
GetListenerPosition()
bool FAudioDevice::GetListenerPosition (int32 ListenerIndex, FVector & OutPosition, bool bAllowOverride) const
Returns a position from the appropriate listener representation, depending on calling thread.
Parameters
ListenerIndex index of the listener or proxy
OutPosition filled in position of the listener or proxy
bAllowOverride if true we will use the attenuation override for position, if set
Returns
true if successful
References const, FVector, and GetListenerPosition().
Referenced by GetListenerPosition().
GetListeners()
const TArray< FListener > & FAudioDevice::GetListeners () const inline
Definition at line 701 of file AudioDevice.h.
References check, IsInAudioThread(), and Listeners.
GetListenerTransform()
bool FAudioDevice::GetListenerTransform (int32 ListenerIndex, FTransform & OutTransform) const
Returns the transform of the appropriate listener representation, depending on calling thread.
References const, and GetListenerTransform().
Referenced by GetListenerTransform().
GetListenerTransformedDirection()
FVector FAudioDevice::GetListenerTransformedDirection (const FVector & Position, float * OutDistance)
Gets the direction of the given position vector transformed relative to listener.
Parameters
Position Input position vector to transform relative to listener
OutDistance Optional output of distance from position to listener
Returns
The input position relative to the listener.
References FVector, and Position.
GetListenerWorldID()
bool FAudioDevice::GetListenerWorldID (int32 ListenerIndex, uint32 & OutWorldID) const
Returns the WorldID of the appropriate listener representation, depending on calling thread.
References const, and GetListenerWorldID().
Referenced by GetListenerWorldID().
GetLowPassFilterResonance()
float FAudioDevice::GetLowPassFilterResonance () const
Low pass filter OneOverQ value.
GetMagnitudesForFrequencies()
virtual void FAudioDevice::GetMagnitudesForFrequencies (USoundSubmix * InSubmix, const TArray< float > & InFrequencies, TArray< float > & OutMagnitudes) virtual
GetMainAudioDevice()
FAudioDeviceHandle FAudioDevice::GetMainAudioDevice () static
Returns the main audio device of the engine.
GetMainSubmixObject()
virtual USoundSubmix & FAudioDevice::GetMainSubmixObject () const virtual
GetMaxChannels()
int32 FAudioDevice::GetMaxChannels () const
Returns the max channels used by the audio device.
GetMaxDistanceAndFocusFactor()
void FAudioDevice::GetMaxDistanceAndFocusFactor (USoundBase * Sound, const UWorld * World, const FVector & Location, const FSoundAttenuationSettings * AttenuationSettingsToApply, float & OutMaxDistance, float & OutFocusFactor)
Gets the max distance and focus factor of a sound.
References FVector, Location, and Sound.
GetMaxSources()
int32 FAudioDevice::GetMaxSources () const
Returns the maximum sources used by the audio device set on initialization, including the number of stopping voices reserved.
GetMaxWorldDistance()
float FAudioDevice::GetMaxWorldDistance () static
Returns the global maximum distance used in the audio engine.
References GetMaxWorldDistance().
Referenced by GetMaxWorldDistance().
GetMixDebugState()
EDebugState FAudioDevice::GetMixDebugState () const inline
Gets the current audio debug state.
Definition at line 917 of file AudioDevice.h.
References DebugState.
GetNumActiveSources()
virtual int32 FAudioDevice::GetNumActiveSources () const inline virtual
Returns the number of active sound sources.
Definition at line 1301 of file AudioDevice.h.
GetNumBuffers()
int32 FAudioDevice::GetNumBuffers () const inline
Returns the number of buffers the audio device keeps queued.
Definition at line 1313 of file AudioDevice.h.
References PlatformSettings.
GetNumFreeSources()
int32 FAudioDevice::GetNumFreeSources () const inline
Returns the number of free sources.
Definition at line 1304 of file AudioDevice.h.
References Sources.
GetNumPrecacheFrames()
int32 FAudioDevice::GetNumPrecacheFrames () const private
Returns the number of frames to use per precache buffer.
GetPhasesForFrequencies()
virtual void FAudioDevice::GetPhasesForFrequencies (USoundSubmix * InSubmix, const TArray< float > & InFrequencies, TArray< float > & OutPhases) virtual
GetPlatformAudioHeadroom()
float FAudioDevice::GetPlatformAudioHeadroom () const inline
Definition at line 1917 of file AudioDevice.h.
References check, IsInAudioThread(), and PlatformAudioHeadroom.
GetPlatformSettings()
virtual FAudioPlatformSettings FAudioDevice::GetPlatformSettings () const inline private virtual
Allow platforms to optionally specify low-level audio platform settings.
Definition at line 1678 of file AudioDevice.h.
GetPrevPassiveSoundMixModifiers()
const TArray< USoundMix * > & FAudioDevice::GetPrevPassiveSoundMixModifiers () const inline
Definition at line 1732 of file AudioDevice.h.
References ObjectPtrDecay(), and PrevPassiveSoundMixModifiers.
GetPrimaryVolume()
float FAudioDevice::GetPrimaryVolume () const inline
Returns the volume that combines transient master volume and the FApp::GetVolumeMultiplier() value.
Definition at line 1903 of file AudioDevice.h.
References PrimaryVolume.
GetQualityLevelSettings()
const FAudioQualitySettings & FAudioDevice::GetQualityLevelSettings () static
Returns the quality settings used by the default audio settings.
GetSampleRate()
float FAudioDevice::GetSampleRate () const inline
Returns the sample rate used by the audio device.
Definition at line 1307 of file AudioDevice.h.
References SampleRate.
GetSortedActiveWaveInstances()
int32 FAudioDevice::GetSortedActiveWaveInstances (TArray< FWaveInstance * > & WaveInstances, const ESortedActiveWaveGetType::Type GetType)
Iterate over the active AudioComponents for wave instances that could be playing.
Returns
Index of first wave instance that can have a source attached
GetSoundClassCurrentProperties()
FSoundClassProperties * FAudioDevice::GetSoundClassCurrentProperties (USoundClass * InSoundClass)
Gets the current properties of a sound class, if the sound class hasn't been registered, then it returns nullptr.
Parameters
SoundClassName name of sound class to retrieve
Returns
sound class properties if it exists
References GetSoundClassCurrentProperties().
Referenced by GetSoundClassCurrentProperties().
GetSoundClassDynamicProperties()
FSoundClassDynamicProperties * FAudioDevice::GetSoundClassDynamicProperties (USoundClass * InSoundClass)
Returns the parameters which are dynamic from the given sound class.
References GetSoundClassDynamicProperties().
Referenced by GetSoundClassDynamicProperties().
GetSoundClassInfo()
void FAudioDevice::GetSoundClassInfo (TMap< FName, FAudioClassInfo > & AudioClassInfos) private
Gets a summary of loaded sound collated by class.
GetSoundClassPropertyMap()
FSoundClassProperties & FAudioDevice::GetSoundClassPropertyMap () const inline
Definition at line 1923 of file AudioDevice.h.
References check, const, GetSoundClassPropertyMap(), IsInAudioThread(), and SoundClasses.
Referenced by GetSoundClassPropertyMap().
GetSoundMixModifiers()
const TMap< USoundMix *, FSoundMixState > & FAudioDevice::GetSoundMixModifiers () const inline
Definition at line 1727 of file AudioDevice.h.
References ObjectPtrDecay(), and SoundMixModifiers.
GetSoundSource()
FSoundSource * FAudioDevice::GetSoundSource (FWaveInstance * WaveInstance) const
References FSoundSource.
GetSpatializationPluginInterface()
TAudioSpatializationPtr FAudioDevice::GetSpatializationPluginInterface () inline
Return the spatialization plugin interface.
Definition at line 1328 of file AudioDevice.h.
References GetCurrentSpatializationPluginInterfaceInfo(), and FAudioDevice::FAudioSpatializationInterfaceInfo::SpatializationPlugin.
GetSubsystem() [1/2]
template<typename TSubsystemClass> TSubsystemClass * FAudioDevice::GetSubsystem () const inline
Get a Subsystem of specified type.
Definition at line 1958 of file AudioDevice.h.
References SubsystemCollection.
Referenced by GetSubsystem().
GetSubsystem() [2/2]
template<typename TSubsystemClass> FORCEINLINE TSubsystemClass * FAudioDevice::GetSubsystem (const FAudioDeviceHandle & InHandle) inline static
Get a Subsystem of specified type from the provided AudioDeviceHandle returns nullptr if the Subsystem cannot be found or the AudioDeviceHandle is invalid.
Definition at line 1968 of file AudioDevice.h.
References FORCEINLINE, GetSubsystem(), and FAudioDeviceHandle::IsValid().
GetSubsystemArrayCopy()
template<typename TSubsystemClass> TArray< TSubsystemClass * > FAudioDevice::GetSubsystemArrayCopy () const inline
Gets all Subsystems of specified type, this is only necessary for interfaces that can have multiple implementations instanced at a time.
Do not hold onto this Array reference unless you are sure the lifetime is less than that of the audio device
Definition at line 1993 of file AudioDevice.h.
References SubsystemCollection.
GetSubsystemBase()
UAudioEngineSubsystem * FAudioDevice::GetSubsystemBase (TSubclassOf< UAudioEngineSubsystem > SubsystemClass) const inline
Get a Subsystem of specified type.
Definition at line 1951 of file AudioDevice.h.
References SubsystemCollection.
GetTestComponent()
UAudioComponent * FAudioDevice::GetTestComponent (UWorld * InWorld)
GetTransientPrimaryVolume()
float FAudioDevice::GetTransientPrimaryVolume () const inline
Definition at line 1899 of file AudioDevice.h.
References check, IsInAudioThread(), and TransientPrimaryVolume.
GetWaveInstanceSourceMap()
const TMap< FWaveInstance *, FSoundSource * > & FAudioDevice::GetWaveInstanceSourceMap () const
HandleAudio3dVisualizeCommand()
bool FAudioDevice::HandleAudio3dVisualizeCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioDebugSound()
bool FAudioDevice::HandleAudioDebugSound (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioMemoryInfo()
bool FAudioDevice::HandleAudioMemoryInfo (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioMixerDebugSound()
bool FAudioDevice::HandleAudioMixerDebugSound (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioSoloCommon()
void FAudioDevice::HandleAudioSoloCommon (const TCHAR * Cmd, FOutputDevice & Ar, FToggleSoloPtr Funct) private
References Ar, and Cmd.
HandleAudioSoloSoundClass()
bool FAudioDevice::HandleAudioSoloSoundClass (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioSoloSoundCue()
bool FAudioDevice::HandleAudioSoloSoundCue (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleAudioSoloSoundWave()
bool FAudioDevice::HandleAudioSoloSoundWave (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleClearSoloCommand()
bool FAudioDevice::HandleClearSoloCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleDisableHPFCommand()
bool FAudioDevice::HandleDisableHPFCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleDisableLPFCommand()
bool FAudioDevice::HandleDisableLPFCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleDisableRadioCommand()
bool FAudioDevice::HandleDisableRadioCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleDumpSoundInfoCommand()
bool FAudioDevice::HandleDumpSoundInfoCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
Exec command handlers.
References Ar, and Cmd.
HandleEnableHRTFForAllCommand()
bool FAudioDevice::HandleEnableHRTFForAllCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleEnableRadioCommand()
bool FAudioDevice::HandleEnableRadioCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleGetDynamicSoundVolumeCommand()
bool FAudioDevice::HandleGetDynamicSoundVolumeCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleIsolateDryAudioCommand()
bool FAudioDevice::HandleIsolateDryAudioCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleIsolateReverbCommand()
bool FAudioDevice::HandleIsolateReverbCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleListAudioComponentsCommand()
bool FAudioDevice::HandleListAudioComponentsCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleListSoundClassesCommand()
bool FAudioDevice::HandleListSoundClassesCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
Lists a summary of loaded sound collated by class.
References Ar, and Cmd.
HandleListSoundClassVolumesCommand()
bool FAudioDevice::HandleListSoundClassVolumesCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleListSoundDurationsCommand()
bool FAudioDevice::HandleListSoundDurationsCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleListWavesCommand()
bool FAudioDevice::HandleListWavesCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
Lists all the playing waveinstances and their associated source.
References Ar, and Cmd.
HandlePause()
void FAudioDevice::HandlePause (bool bGameTicking, bool bGlobalPause = false) protected
Handle pausing/unpausing of sources when entering or leaving pause mode, or global pause (like device suspend)
HandlePlayAllPIEAudioCommand()
bool FAudioDevice::HandlePlayAllPIEAudioCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleResetAllDynamicSoundVolumesCommand()
bool FAudioDevice::HandleResetAllDynamicSoundVolumesCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleResetDynamicSoundVolumeCommand()
bool FAudioDevice::HandleResetDynamicSoundVolumeCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleResetSoundStateCommand()
bool FAudioDevice::HandleResetSoundStateCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleSetBaseSoundMixCommand()
bool FAudioDevice::HandleSetBaseSoundMixCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleSetDynamicSoundCommand()
bool FAudioDevice::HandleSetDynamicSoundCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleShowSoundClassHierarchyCommand()
bool FAudioDevice::HandleShowSoundClassHierarchyCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
shows sound class hierarchy
References Ar, and Cmd.
HandleSoloCommand()
bool FAudioDevice::HandleSoloCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleSoundClassFixup()
bool FAudioDevice::HandleSoundClassFixup (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleSoundTemplateInfoCommand()
bool FAudioDevice::HandleSoundTemplateInfoCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleTestHPFCommand()
bool FAudioDevice::HandleTestHPFCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleTestLFEBleedCommand()
bool FAudioDevice::HandleTestLFEBleedCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleTestLPFCommand()
bool FAudioDevice::HandleTestLPFCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HandleToggleSpatializationExtensionCommand()
bool FAudioDevice::HandleToggleSpatializationExtensionCommand (const TCHAR * Cmd, FOutputDevice & Ar) private
References Ar, and Cmd.
HasCompressedAudioInfoClass()
virtual bool FAudioDevice::HasCompressedAudioInfoClass (USoundWave * SoundWave) inline virtual
Whether this SoundWave has an associated info class to decompress it.
Definition at line 1151 of file AudioDevice.h.
References HasCompressedAudioInfoClass().
Referenced by HasCompressedAudioInfoClass().
Init()
bool FAudioDevice::Init (Audio::FDeviceId InDeviceID, int32 InMaxSources, int32 BufferSizeOverride = INDEX_NONE, int32 NumBuffersOverride = INDEX_NONE)
Basic initialization of the platform agnostic layer of the audio system.
References INDEX_NONE.
InitEffect()
void * FAudioDevice::InitEffect (FSoundSource * Source)
Platform dependent call to init effect data on a sound source.
References FSoundSource, and Source.
InitializeHardware()
virtual bool FAudioDevice::InitializeHardware () inline virtual
Starts up any platform specific hardware/APIs.
Definition at line 1778 of file AudioDevice.h.
InitializePluginListeners()
void FAudioDevice::InitializePluginListeners (UWorld * World) private
Initializes all plugin listeners belonging to this audio device.
Called in the game thread.
Parameters
World Pointer to the UWorld the listener is in.
InitializeSubsystemCollection()
void FAudioDevice::InitializeSubsystemCollection () protected
Create our subsystem collection root object and initialize subsystems.
InitSoundClasses()
void FAudioDevice::InitSoundClasses ()
Set up the sound class hierarchy.
InitSoundParams()
void FAudioDevice::InitSoundParams (FActiveSound & InOutActiveSound, TArray< FAudioParameter > InDefaultParams, bool bInIsVirtualLoopRealzing) const private
Initializes the parameters on the active sound.
InitSoundSources()
void FAudioDevice::InitSoundSources () protected
Set up the initial sound sources Allows us to initialize sound source early on, allowing for render callback hookups for iOS Audio.
InitSoundSubmixes()
virtual void FAudioDevice::InitSoundSubmixes () inline virtual
Initializes sound submixes.
Definition at line 965 of file AudioDevice.h.
InterpolateAdjuster()
float FAudioDevice::InterpolateAdjuster (const float Adjuster, const float InterpValue) const inline private
Takes an adjuster value and modifies it by the proportion that is currently in effect.
Definition at line 1669 of file AudioDevice.h.
InvalidateCachedInteriorVolumes()
void FAudioDevice::InvalidateCachedInteriorVolumes () const
When the set of Audio volumes have changed invalidate the cached values of active sounds.
IsAudioDeviceMuted()
bool FAudioDevice::IsAudioDeviceMuted () const
IsBakedAnalaysisQueryingEnabled()
bool FAudioDevice::IsBakedAnalaysisQueryingEnabled () const inline
Returns if baked analysis querying is enabled.
Definition at line 1375 of file AudioDevice.h.
References bIsBakedAnalysisEnabled.
IsExernalBackgroundSoundActive()
virtual bool FAudioDevice::IsExernalBackgroundSoundActive () inline virtual
Check if any background music or sound is playing through the audio device.
Definition at line 1189 of file AudioDevice.h.
IsHRTFDisabled()
bool FAudioDevice::IsHRTFDisabled () const
Whether or not HRTF is disabled.
IsHRTFEnabledForAll()
bool FAudioDevice::IsHRTFEnabledForAll () const
Whether or not HRTF spatialization is enabled for all.
IsInitialized()
FORCEINLINE bool FAudioDevice::IsInitialized () const inline protected
Whether the device was initialized.
Definition at line 2247 of file AudioDevice.h.
References bIsInitialized, FORCEINLINE, and IsInitialized().
Referenced by IsInitialized().
IsMainAudioDevice()
bool FAudioDevice::IsMainAudioDevice () const
IsModulationPluginEnabled()
bool FAudioDevice::IsModulationPluginEnabled () const inline
Whether or not there's a modulation plugin enabled.
Definition at line 1340 of file AudioDevice.h.
References bModulationInterfaceEnabled.
IsNonRealtime()
virtual bool FAudioDevice::IsNonRealtime () const inline virtual
Definition at line 1383 of file AudioDevice.h.
IsOcclusionPluginEnabled()
bool FAudioDevice::IsOcclusionPluginEnabled () const inline
Whether or not there's an occlusion plugin enabled.
Definition at line 1346 of file AudioDevice.h.
References bOcclusionInterfaceEnabled.
IsOcclusionPluginLoaded()
bool FAudioDevice::IsOcclusionPluginLoaded () static
IsPendingStop()
bool FAudioDevice::IsPendingStop (FActiveSound * ActiveSound)
Whether the provided ActiveSound is currently pending to stop.
IsReverbPluginEnabled()
bool FAudioDevice::IsReverbPluginEnabled () const inline
Whether or not there's a reverb plugin enabled.
Definition at line 1354 of file AudioDevice.h.
References bReverbInterfaceEnabled.
IsReverbPluginLoaded()
bool FAudioDevice::IsReverbPluginLoaded () static
IsSourceDataOverridePluginEnabled()
bool FAudioDevice::IsSourceDataOverridePluginEnabled () const inline
Definition at line 1361 of file AudioDevice.h.
References bSourceDataOverrideInterfaceEnabled.
IsSourceDataOverridePluginLoaded()
bool FAudioDevice::IsSourceDataOverridePluginLoaded () static
IsSpatializationPluginEnabled()
bool FAudioDevice::IsSpatializationPluginEnabled () const inline
Whether or not there's a spatialization plugin enabled.
Definition at line 1316 of file AudioDevice.h.
References bSpatializationInterfaceEnabled.
IsStoppingVoicesEnabled()
bool FAudioDevice::IsStoppingVoicesEnabled () const inline
Returns if stopping voices is enabled.
Definition at line 1369 of file AudioDevice.h.
References bIsStoppingVoicesEnabled.
IsUsingListenerAttenuationOverride()
bool FAudioDevice::IsUsingListenerAttenuationOverride (int32 ListenerIndex) const
Returns if the specific listener is using an attenuation override position.
Referenced by UE_DEPRECATED().
LegacyReverbDisabled()
bool FAudioDevice::LegacyReverbDisabled () static
LocationIsAudible() [1/2]
bool FAudioDevice::LocationIsAudible (const FVector & Location, const float MaxDistance) const
Checks to see if a coordinate is within a distance of any listener.
References const, FVector, Location, and LocationIsAudible().
Referenced by LocationIsAudible(), and LocationIsAudible().
LocationIsAudible() [2/2]
bool FAudioDevice::LocationIsAudible (const FVector & Location, int32 ListenerIndex, const float MaxDistance) const
Checks to see if a coordinate is within a distance of a specific listener.
References const, FVector, Location, and LocationIsAudible().
NotifyActiveSoundOcclusionTraceDone()
void FAudioDevice::NotifyActiveSoundOcclusionTraceDone (FActiveSound * ActiveSound, bool bIsOccluded)
Notify that a pending async occlusion trace finished on the active sound.
NotifyAudioDevicePostRender()
void FAudioDevice::NotifyAudioDevicePostRender (const FAudioDeviceRenderInfo & InInfo) protected
NotifyAudioDevicePreRender()
void FAudioDevice::NotifyAudioDevicePreRender (const FAudioDeviceRenderInfo & InInfo) protected
NotifyPluginListenersWorldChanged()
void FAudioDevice::NotifyPluginListenersWorldChanged (UWorld * World) private
Notifies all plugin listeners belonging to this audio device that the world changed.
Called in the game thread.
Parameters
World Pointer to the UWorld the listener is in.
NotifySubsystemsActiveSoundCreated()
void FAudioDevice::NotifySubsystemsActiveSoundCreated (FActiveSound & ActiveSound) const protected
Notifies subsystems an active sound has just been added (called on audio thread).
Called both for brand new sounds and for virtualized sounds that have just become active.
Referenced by UE_DEPRECATED().
NotifySubsystemsActiveSoundDeleting()
void FAudioDevice::NotifySubsystemsActiveSoundDeleting (FActiveSound & ActiveSound) const protected
Notifies subsystems an active sound is about to be deleted (called on audio thread).
Called when a sound is either stopped or virtualized. In either case, the referenced ActiveSound object no longer exists after this call; any pointers to it should be discarded.
Referenced by UE_DEPRECATED().
NotifySubsystemsSetOwner()
void FAudioDevice::NotifySubsystemsSetOwner (FActiveSound & ActiveSound, const UObject * Owner) const protected
Notifies subsystems an owning object has been associated with a sound.
References Owner.
NotifySubsystemsVirtualizedSoundCreated()
void FAudioDevice::NotifySubsystemsVirtualizedSoundCreated (FActiveSound & ActiveSound) const protected
Notifies subsystems a virtualized sound has just been added (called on audio thread).
Called both for brand new sounds and for active sounds that have just become virtualized.
NotifySubsystemsVirtualizedSoundDeleting()
void FAudioDevice::NotifySubsystemsVirtualizedSoundDeleting (FActiveSound & ActiveSound) const protected
Notifies subsystems a virtualized sound is about to be deleted (called on audio thread).
Called when a sound is either stopped or re-triggered. In either case, the referenced ActiveSound object no longer exists after this call; any pointers to it should be discarded.
OnBeginPIE()
void FAudioDevice::OnBeginPIE (const bool bIsSimulating)
Deals with anything audio related that should happen when PIE starts.
OnDeviceCreated()
void FAudioDevice::OnDeviceCreated (Audio::FDeviceId InDeviceID)
Called after FAudioDevice creation and init.
OnDeviceDestroyed()
void FAudioDevice::OnDeviceDestroyed (Audio::FDeviceId InDeviceID)
Called before FAudioDevice teardown.
OnEndPIE()
void FAudioDevice::OnEndPIE (const bool bIsSimulating)
Deals with anything audio related that should happen when PIE ends.
OnListenerUpdated()
virtual void FAudioDevice::OnListenerUpdated (const TArray< FListener > & InListeners) inline protected virtual
This is overridden in Audio::FMixerDevice to propogate listener information to the audio thread.
Definition at line 1525 of file AudioDevice.h.
OnPreGarbageCollect()
void FAudioDevice::OnPreGarbageCollect ()
ParseSoundClasses()
void FAudioDevice::ParseSoundClasses (float InDeltaTime) private
Parses the sound classes and propagates multiplicative properties down the tree.
PauseActiveSound()
void FAudioDevice::PauseActiveSound (uint64 AudioComponentID, const bool bInIsPaused)
Pauses the active sound for the specified audio component.
PlaySoundAtLocation()
void FAudioDevice::PlaySoundAtLocation (USoundBase * Sound, UWorld * World, float VolumeMultiplier, float PitchMultiplier, float StartTime, const FVector & Location, const FRotator & Rotation, USoundAttenuation * AttenuationSettings = nullptr, USoundConcurrency * ConcurrencySettings = nullptr, const TArray< FAudioParameter > * Params = nullptr, const AActor * OwningActor = nullptr)
Plays a sound at the given location without creating an audio component.
Parameters
Sound The USoundBase to play at the location.
World The world this sound is playing in.
VolumeMultiplier The volume multiplier to set on the sound.
PitchMultiplier The pitch multiplier to set on the sound.
StartTime The initial time offset for the sound.
Location The sound's position.
Rotation The sound's rotation.
AttenuationSettings The sound's attenuation settings to use (optional). Will default to the USoundBase's AttenuationSettings if not specified.
USoundConcurrency The sound's sound concurrency settings to use (optional). Will use the USoundBase's USoundConcurrency if not specified.
Params An optional list of audio component params to immediately apply to a sound.
References FVector, Location, Params, Rotation, and Sound.
PlayWhenSilentEnabled()
bool FAudioDevice::PlayWhenSilentEnabled () const inline
Whether play when silent is enabled for all sounds associated with this audio device.
Definition at line 1930 of file AudioDevice.h.
References bAllowPlayWhenSilent.
PopSoundMixModifier()
void FAudioDevice::PopSoundMixModifier (USoundMix * SoundMix, bool bIsPassive = false)
Pop a SoundMix from the Audio Device's list.
Parameters
SoundMix The SoundMix to pop.
bIsPassive Whether this is a passive pop from a sound finishing.
References PopSoundMixModifier().
Referenced by PopSoundMixModifier().
Precache()
virtual void FAudioDevice::Precache (USoundWave * SoundWave, bool bSynchronous = false, bool bTrackMemory = true, bool bForceFullDecompression = false) virtual
Precaches the passed in sound node wave object.
Parameters
SoundWave Resource to be precached.
bSynchronous If true, this function will block until a vorbis decompression is complete
bTrackMemory If true, the audio mem stats will be updated
bForceFullDecompression If true, the sound wave will be fully decompressed regardless of size.
PrecacheStartupSounds()
void FAudioDevice::PrecacheStartupSounds ()
Precaches all existing sounds.
Called when audio setup is complete
ProcessingPendingActiveSoundStops()
void FAudioDevice::ProcessingPendingActiveSoundStops (bool bForceDelete = false) private
Processes the set of pending sounds that need to be stopped.
PushSoundMixModifier()
void FAudioDevice::PushSoundMixModifier (USoundMix * SoundMix, bool bIsPassive = false, bool bIsRetrigger = false)
Push a SoundMix onto the Audio Device's list.
Parameters
SoundMix The SoundMix to push.
bIsPassive Whether this is a passive push from a playing sound.
References PushSoundMixModifier().
Referenced by PushSoundMixModifier().
RecurseIntoSoundClasses()
void FAudioDevice::RecurseIntoSoundClasses (USoundClass * CurrentClass, FSoundClassProperties & ParentProperties) private
Internal helper function used by ParseSoundClasses to traverse the tree.
Parameters
CurrentClass Subtree to deal with
ParentProperties Propagated properties of parent node
RecursiveApplyAdjuster()
void FAudioDevice::RecursiveApplyAdjuster (const FSoundClassAdjuster & InAdjuster, USoundClass * InSoundClass) private
Recursively apply an adjuster to the passed in sound class and all children of the sound class.
Parameters
InAdjuster The adjuster to apply
InSoundClassName The name of the sound class to apply the adjuster to. Also applies to all children of this class
RegisterPluginListener()
void FAudioDevice::RegisterPluginListener (const TAudioPluginListenerPtr PluginListener)
Registers a third party listener-observer to this audio device.
RegisterSoundClass()
void FAudioDevice::RegisterSoundClass (USoundClass * InSoundClass)
Registers a sound class with the audio device.
Parameters
SoundClassName name of sound class to retrieve
Returns
sound class properties if it exists
RegisterSoundSubmix()
virtual void FAudioDevice::RegisterSoundSubmix (USoundSubmixBase * SoundSubmix, bool bInit) inline virtual
Registers the sound submix.
Definition at line 968 of file AudioDevice.h.
References SoundSubmix.
RegisterSubmixBufferListener()
virtual void FAudioDevice::RegisterSubmixBufferListener (TSharedRef< ISubmixBufferListener, ESPMode::ThreadSafe > InSubmixBufferListener, USoundSubmix & SoundSubmix) virtual
Registers the provided submix buffer listener with the given submix.
References RegisterSubmixBufferListener(), SoundSubmix, and ThreadSafe.
Referenced by RegisterSubmixBufferListener().
RemoveActiveSound()
void FAudioDevice::RemoveActiveSound (FActiveSound * ActiveSound)
Removes an active sound from the active sounds array.
References RemoveActiveSound().
Referenced by RemoveActiveSound().
RemoveAudioVolumeProxy()
void FAudioDevice::RemoveAudioVolumeProxy (uint32 AudioVolumeID)
References RemoveAudioVolumeProxy().
Referenced by RemoveAudioVolumeProxy().
RemoveEnvelopeFollowerDelegate()
virtual void FAudioDevice::RemoveEnvelopeFollowerDelegate (USoundSubmix * InSubmix, const FOnSubmixEnvelopeBP & OnSubmixEnvelopeBP) virtual
RemovePostRenderDelegate()
bool FAudioDevice::RemovePostRenderDelegate (const FDelegateHandle & InHandle)
RemovePreRenderDelegate()
bool FAudioDevice::RemovePreRenderDelegate (const FDelegateHandle & InHandle)
RemoveSoundMix()
void FAudioDevice::RemoveSoundMix (USoundMix * SoundMix)
Removes a sound mix - called when SoundMix is unloaded.
References RemoveSoundMix().
Referenced by RemoveSoundMix().
RemoveSpectralAnalysisDelegate()
virtual void FAudioDevice::RemoveSpectralAnalysisDelegate (USoundSubmix * InSubmix, const FOnSubmixSpectralAnalysisBP & OnSubmixSpectralAnalysisBP) virtual
RemoveVirtualLoop()
bool FAudioDevice::RemoveVirtualLoop (FActiveSound & ActiveSound) private
ReportSoundFailedToStart()
void FAudioDevice::ReportSoundFailedToStart (const uint64 AudioComponentID, FAudioVirtualLoop * VirtualLoop) private
Reports if a sound fails to start when attempting to create a new active sound.
ResetAudioVolumeProxyChangedState()
void FAudioDevice::ResetAudioVolumeProxyChangedState ()
ResetInterpolation()
void FAudioDevice::ResetInterpolation ()
Resets all interpolating values to defaults.
References ResetInterpolation().
Referenced by ResetInterpolation().
ResumeContext()
virtual void FAudioDevice::ResumeContext () inline virtual
Resume any context related objects.
Definition at line 1186 of file AudioDevice.h.
RetriggerVirtualLoop()
void FAudioDevice::RetriggerVirtualLoop (FAudioVirtualLoop & VirtualLoop)
Attempts to retrigger a provided loop.
SendCommandToActiveSounds()
void FAudioDevice::SendCommandToActiveSounds (uint64 InAudioComponentID, TUniqueFunction< void(FActiveSound &)> InFunc, const TStatId InStatId = TStatId())
Performs an operation on all active sounds requested to execute by an audio component.
SendUpdateResultsToGameThread()
void FAudioDevice::SendUpdateResultsToGameThread (int32 FirstActiveIndex) private
SetAudioStateProperty()
void FAudioDevice::SetAudioStateProperty (const FName & PropertyName, const FName & PropertyValue)
References PropertyName.
SetBaseSoundMix()
void FAudioDevice::SetBaseSoundMix (USoundMix * SoundMix)
Sets a new sound mix and applies it to all appropriate sound classes.
References SetBaseSoundMix().
Referenced by SetBaseSoundMix().
SetCanHaveMultipleActiveSounds()
void FAudioDevice::SetCanHaveMultipleActiveSounds (uint64 AudioComponentID, bool InCanHaveMultipleActiveSounds)
Set whether a given Audio Component ID should be allowed to have multiple associated Active Sounds.
References SetCanHaveMultipleActiveSounds().
Referenced by SetCanHaveMultipleActiveSounds().
SetCurrentSpatializationPlugin()
bool FAudioDevice::SetCurrentSpatializationPlugin (FName PluginName)
Set and initialize the current Spatialization plugin (by name)
SetDefaultAudioSettings()
void FAudioDevice::SetDefaultAudioSettings (UWorld * World, const FReverbSettings & DefaultReverbSettings, const FInteriorSettings & DefaultInteriorSettings)
Sets the default reverb and interior settings for the provided world.
SetDefaultBaseSoundMix()
void FAudioDevice::SetDefaultBaseSoundMix (USoundMix * SoundMix)
Sets the Sound Mix that should be active by default.
References SetDefaultBaseSoundMix().
Referenced by SetDefaultBaseSoundMix().
SetDeviceMuted()
void FAudioDevice::SetDeviceMuted (bool bMuted)
SetGlobalFocusSettings()
void FAudioDevice::SetGlobalFocusSettings (const FGlobalFocusSettings & NewFocusSettings)
SetGlobalPitchModulation()
void FAudioDevice::SetGlobalPitchModulation (float PitchScale, float TimeSec)
SetHRTFDisabled()
void FAudioDevice::SetHRTFDisabled (bool InIsHRTFDisabled) inline
Definition at line 1213 of file AudioDevice.h.
References FAudioDevice(), bHRTFDisabled, bHRTFDisabled_OnGameThread, DECLARE_CYCLE_STAT, GET_STATID, FAudioThread::RunCommandOnAudioThread(), and TEXT.
SetHRTFEnabledForAll()
void FAudioDevice::SetHRTFEnabledForAll (bool InbHRTFEnabledForAll) inline
Definition at line 1194 of file AudioDevice.h.
References FAudioDevice(), bHRTFEnabledForAll, bHRTFEnabledForAll_OnGameThread, DECLARE_CYCLE_STAT, GET_STATID, FAudioThread::RunCommandOnAudioThread(), and TEXT.
SetListener()
void FAudioDevice::SetListener (UWorld * World, int32 InListenerIndex, const FTransform & ListenerTransform, float InDeltaSeconds)
Sets the details about the listener.
Parameters
World The world the listener is being set on.
ListenerIndex The index of the listener
ListenerTransform The listener's world transform
DeltaSeconds The amount of time over which velocity should be calculated. If 0, then velocity will not be calculated.
References const, ListenerTransform, and SetListener().
Referenced by SetListener().
SetListenerAttenuationOverride()
void FAudioDevice::SetListenerAttenuationOverride (int32 ListenerIndex, const FVector AttenuationPosition)
Sets an override position for the specified listener to do attenuation calculations.
References FVector.
Referenced by UE_DEPRECATED().
SetMaxChannels()
void FAudioDevice::SetMaxChannels (int32 InMaxChannels)
Sets the maximum number of channels dynamically.
Can't raise the cap over the initial value but can lower it
SetMaxChannelsScaled()
void FAudioDevice::SetMaxChannelsScaled (float InScaledChannelCount)
Sets the maximum number of channels dynamically by scaled percentage.
SetMixDebugState()
void FAudioDevice::SetMixDebugState (EDebugState DebugState)
References DebugState.
SetPlatformAudioHeadroom()
void FAudioDevice::SetPlatformAudioHeadroom (float PlatformHeadRoom)
SetSoundClassDistanceScale()
void FAudioDevice::SetSoundClassDistanceScale (USoundClass * InSoundClass, float DistanceScale, float TimeSec)
Overrides the attenuation scale used on a sound class.
SetSoundMixClassOverride()
void FAudioDevice::SetSoundMixClassOverride (USoundMix * InSoundMix, USoundClass * InSoundClass, float Volume, float Pitch, float FadeInTime, bool bApplyToChildren)
Sets a sound class override in the given sound mix.
References SetSoundMixClassOverride(), and Volume.
Referenced by SetSoundMixClassOverride().
SetSoundMixModifiers()
void FAudioDevice::SetSoundMixModifiers (const TMap< USoundMix *, FSoundMixState > & InSoundMixModifiers, const TArray< USoundMix * > & InPrevPassiveSoundMixModifiers, USoundMix * InDefaultBaseSoundMix) inline
Definition at line 1742 of file AudioDevice.h.
References DefaultBaseSoundMix, ObjectPtrWrap(), PrevPassiveSoundMixModifiers, and SoundMixModifiers.
SetSpatializationInterfaceEnabled()
void FAudioDevice::SetSpatializationInterfaceEnabled (bool InbSpatializationInterfaceEnabled) inline
Definition at line 1229 of file AudioDevice.h.
References bSpatializationInterfaceEnabled, FAudioThread::ResumeAudioThread(), and FAudioThread::SuspendAudioThread().
SetSubmixAutoDisable()
virtual void FAudioDevice::SetSubmixAutoDisable (USoundSubmix * InSoundSubmix, bool bInAutoDisable) inline virtual
Set whether or not a submix is auto-disabled.
Definition at line 1434 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixAutoDisableTime()
virtual void FAudioDevice::SetSubmixAutoDisableTime (USoundSubmix * InSoundSubmix, float InDisableTime) inline virtual
Set what the auto-disable time is.
Definition at line 1440 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixDryLevel()
virtual void FAudioDevice::SetSubmixDryLevel (USoundSubmix * InSoundSubmix, float InDryLevel) inline virtual
Set the wet-dry level of the given submix.
Definition at line 1474 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixEffectChainOverride()
virtual void FAudioDevice::SetSubmixEffectChainOverride (USoundSubmix * InSoundSubmix, const TArray< FSoundEffectSubmixPtr > & InSubmixEffectChain, float InCrossfadeTime) inline virtual
Sets a submix effect chain override for the given submix.
Definition at line 1480 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixModulationBaseLevels()
virtual void FAudioDevice::SetSubmixModulationBaseLevels (USoundSubmix * InSoundSubmix, float InVolumeModBase, float InWetModBase, float InDryModBase) inline virtual
Definition at line 1456 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixOutputVolume()
virtual void FAudioDevice::SetSubmixOutputVolume (USoundSubmix * InSoundSubmix, float InOutputVolume) inline virtual
Set the wet-dry level of the given submix.
Definition at line 1462 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixWetDryLevel()
virtual void FAudioDevice::SetSubmixWetDryLevel (USoundSubmix * InSoundSubmix, float InOutputVolume, float InWetLevel, float InDryLevel) inline virtual
Set the wet-dry level of the given submix.
Definition at line 1428 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetSubmixWetLevel()
virtual void FAudioDevice::SetSubmixWetLevel (USoundSubmix * InSoundSubmix, float InWetLevel) inline virtual
Set the wet-dry level of the given submix.
Definition at line 1468 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
SetTransientPrimaryVolume()
void FAudioDevice::SetTransientPrimaryVolume (float TransientPrimaryVolume)
References TransientPrimaryVolume.
SetUseAttenuationForNonGameWorlds()
void FAudioDevice::SetUseAttenuationForNonGameWorlds (bool bInUseAttenuationForNonGameWorlds) inline
Set whether or not we force the use of attenuation for non-game worlds (as by default we only care about game worlds)
Definition at line 1935 of file AudioDevice.h.
References bUseAttenuationForNonGameWorlds.
ShouldUseAttenuation()
bool FAudioDevice::ShouldUseAttenuation (const UWorld * World) const private
Check whether we should use attenuation settings.
ShouldUseRealtimeDecompression()
bool FAudioDevice::ShouldUseRealtimeDecompression (bool bForceFullDecompression, const FSoundGroup & SoundGroup, USoundWave * SoundWave, float CompressedDurationThreshold) const
Returns true if a sound wave should be decompressed.
ShowSoundClassHierarchy()
void FAudioDevice::ShowSoundClassHierarchy (FOutputDevice & Ar, USoundClass * SoundClass = nullptr, int32 Indent = 0) const private
Lists a summary of loaded sound collated by class.
References Ar.
SoundIsAudible() [1/2]
bool FAudioDevice::SoundIsAudible (const FActiveSound & NewActiveSound) private
Checks if the given sound would be audible.
Parameters
NewActiveSound The ActiveSound attempting to be created
Returns
True if the sound is audible, false otherwise.
SoundIsAudible() [2/2]
bool FAudioDevice::SoundIsAudible (USoundBase * Sound, const UWorld * World, const FVector & Location, const FSoundAttenuationSettings * AttenuationSettingsToApply, float MaxDistance, float FocusFactor) const
Checks if the given sound would be audible.
Parameters
Sound The sound to check if it would be audible
World The world the sound is playing in
Location The location the sound is playing in the world
AttenuationSettings The (optional) attenuation settings the sound is using
MaxDistance The computed max distance of the sound.
FocusFactor The focus factor of the sound.
Returns
Returns true if the sound is audible, false otherwise.
References FVector, Location, and Sound.
SpatializationPluginInterfacesAvailable()
bool FAudioDevice::SpatializationPluginInterfacesAvailable ()
StartEnvelopeFollowing()
virtual void FAudioDevice::StartEnvelopeFollowing (USoundSubmix * InSubmix) inline virtual
This is called by a USoundSubmix to start envelope following on a submix isntance on this device.
Definition at line 1416 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
StartRecording()
virtual void FAudioDevice::StartRecording (USoundSubmix * InSubmix, float ExpectedRecordingDuration) inline virtual
This is called by a USoundSubmix to start recording a submix instance on this device.
Definition at line 1401 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
StartSources()
void FAudioDevice::StartSources (TArray< FWaveInstance * > & WaveInstances, int32 FirstActiveIndex, bool bGameTicking) protected
Start and/or update any sources that have a high enough priority to play.
StartSpectrumAnalysis()
virtual void FAudioDevice::StartSpectrumAnalysis (USoundSubmix * InSubmix, const FSoundSpectrumAnalyzerSettings & InSettings) virtual
StopActiveSound() [1/2]
void FAudioDevice::StopActiveSound (FActiveSound * ActiveSound)
(Deprecated in favor of AddSoundToStop).
Stops the active sound
StopActiveSound() [2/2]
void FAudioDevice::StopActiveSound (uint64 AudioComponentID)
Removes the active sound for the specified audio component.
StopAllSounds()
virtual void FAudioDevice::StopAllSounds (bool bShouldStopUISounds = false) virtual
Stops all game sounds (and possibly UI) sounds.
Parameters
bShouldStopUISounds If true, this function will stop UI sounds as well
References StopAllSounds().
Referenced by StopAllSounds().
StopEnvelopeFollowing()
virtual void FAudioDevice::StopEnvelopeFollowing (USoundSubmix * InSubmix) inline virtual
This is called by a USoundSubmix when we stop envelope following a submix instance on this device.
Definition at line 1422 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
StopOldestStoppingSource()
void FAudioDevice::StopOldestStoppingSource () private
Stops oldest sound source.
StopRecording()
virtual Audio::FAlignedFloatBuffer & FAudioDevice::StopRecording (USoundSubmix * InSubmix, float & OutNumChannels, float & OutSampleRate) inline virtual
This is called by a USoundSubmix when we stop recording a submix on this device.
Definition at line 1407 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
StopSoundsUsingResource()
void FAudioDevice::StopSoundsUsingResource (USoundWave * SoundWave, TArray< UAudioComponent * > * StoppedComponents = nullptr)
Stop any playing sounds that are using a particular SoundWave.
Parameters
SoundWave Resource to stop any sounds that are using it
[out] StoppedComponents List of Audio Components that were stopped
StopSources()
void FAudioDevice::StopSources (TArray< FWaveInstance * > & WaveInstances, int32 FirstActiveIndex) protected
Stop sources that need to be stopped, and touch the ones that need to be kept alive Stop sounds that are too low in priority to be played.
StopSpectrumAnalysis()
virtual void FAudioDevice::StopSpectrumAnalysis (USoundSubmix * InSubmix) virtual
StopTestComponent()
void FAudioDevice::StopTestComponent ()
SupportsRealtimeDecompression()
virtual bool FAudioDevice::SupportsRealtimeDecompression () const inline virtual
Whether this device supports realtime decompression of sound waves (i.e.
DTYPE_RealTime)
Definition at line 1154 of file AudioDevice.h.
Suspend()
void FAudioDevice::Suspend (bool bGameTicking)
Suspend/resume all sounds (global pause for device suspend/resume, etc.)
Parameters
bGameTicking Whether the game is still ticking at the time of suspend
SuspendContext()
virtual void FAudioDevice::SuspendContext () inline virtual
Suspend any context related objects.
Definition at line 1183 of file AudioDevice.h.
Teardown()
void FAudioDevice::Teardown ()
Tears down the audio device.
TeardownHardware()
virtual void FAudioDevice::TeardownHardware () inline virtual
Shuts down any platform specific hardware/APIs.
Definition at line 1784 of file AudioDevice.h.
TryClearingEQSoundMix()
bool FAudioDevice::TryClearingEQSoundMix (USoundMix * SoundMix) private
Attempt to remove this SoundMix's EQ effect - it may not currently be active.
Parameters
SoundMix The SoundMix we're attempting to clear
Returns
Whether the effect of this SoundMix was cleared
TryClearingSoundMix()
bool FAudioDevice::TryClearingSoundMix (USoundMix * SoundMix, FSoundMixState * SoundMixState) private
Attempt to clear the effect of a particular SoundMix.
Parameters
SoundMix The SoundMix we're attempting to clear
SoundMixState The current state of this SoundMix
Returns
Whether this SoundMix could be cleared (only true when both ref counts are zero).
UE_DEPRECATED() [1/21]
FAudioDevice::UE_DEPRECATED (4. 13, "Direct access of SoundClasses is no longer allowed. Instead you should use the SoundMixClassOverride system") const
UE_DEPRECATED() [2/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use ClearListenerAttenuationOverride that passes a ListenerIndex instead") inline
Removes a listener attenuation override.
Definition at line 695 of file AudioDevice.h.
References ClearListenerAttenuationOverride().
UE_DEPRECATED() [3/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use GetDistanceSquaredToListener to check against a specific Listener") const &
References UE_DEPRECATED().
UE_DEPRECATED() [4/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use LocationIsAudible that passes a ListenerIndex to check against a specific Listener") const &
Checks to see if a coordinate is within a distance of the given listener.
References UE_DEPRECATED().
UE_DEPRECATED() [5/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use ParseAttenuation that passes a ListenerIndex instead") const inline
Whether device is using listener attenuation override or not.
Definition at line 1830 of file AudioDevice.h.
References bool, and IsUsingListenerAttenuationOverride().
UE_DEPRECATED() [6/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use ParseAttenuation that passes a ListenerIndex instead") const & inline
Returns the listener attenuation override.
Definition at line 1837 of file AudioDevice.h.
References const, FVector, and GetListenerAttenuationOverride().
UE_DEPRECATED() [7/21]
FAudioDevice::UE_DEPRECATED (4. 25, "Use SetListenerAttenuationOverride that passes a ListenerIndex instead") const inline
Sets an override for the listener to do attenuation calculations.
Definition at line 688 of file AudioDevice.h.
References const, FVector, SetListenerAttenuationOverride(), and UE_DEPRECATED().
UE_DEPRECATED() [8/21]
FAudioDevice::UE_DEPRECATED (5. 0, "This call cannot be called from the GameThread & AudioComponents can now execute multiple ActiveSound instances at once. Use 'SendCommandToActiveSounds' instead.")
Finds the active sound for the specified audio component ID.
This call cannot be called from the GameThread & AudioComponents can now execute multiple ActiveSound instances at once. Use 'SendCommandToActiveSounds' instead.
UE_DEPRECATED() [9/21]
FAudioDevice::UE_DEPRECATED (5. 1, "Do not access this member directly, it is not used. Call GetSpatializationPluginInterface() instead.")
UE_DEPRECATED() [10/21]
FAudioDevice::UE_DEPRECATED (5. 1, "GetMasterVolume has been deprecated. Please use GetPrimaryVolume instead.") const inline
Definition at line 1896 of file AudioDevice.h.
References PrimaryVolume, and UE_DEPRECATED().
UE_DEPRECATED() [11/21]
FAudioDevice::UE_DEPRECATED (5. 1, "GetTransientMasterVolume has been deprecated. Please use GetTransientPrimaryVolume instead.") const inline
Definition at line 1890 of file AudioDevice.h.
References check, float, IsInAudioThread(), and TransientPrimaryVolume.
UE_DEPRECATED() [12/21]
FAudioDevice::UE_DEPRECATED (5. 1, "SetTransientMasterVolume has been deprecated. Please use SetTransientPrimaryVolume instead.")
References TransientPrimaryVolume.
UE_DEPRECATED() [13/21]
UE_DEPRECATED(5.1, "This member is no longer in use. Use the return value of GetCurrentSpatializationPluginInterfaceInfo()") uint8 bSpatializationIsExternalSend FAudioDevice::UE_DEPRECATED (5. 1, "This member is no longer in use. Use the return value of GetCurrentSpatializationPluginInterfaceInfo()")
Max amount of channels a source can be to be spatialized by our active spatialization plugin.
References UE_DEPRECATED().
UE_DEPRECATED() [14/21]
FAudioDevice::UE_DEPRECATED (5. 1, "UpdateSubmixModulationSettings taking single modulators is deprecated. Use the overload that allows for modulator sets")
UE_DEPRECATED() [15/21]
FAudioDevice::UE_DEPRECATED (5. 3, "NotifyPending is deprecated in public scope. Use IActiveSoundUpdateInterface::NotifyActiveSoundDeleting instead.") const & inline
Notifies subsystems an active sound is about to be deleted (called on audio thread) - Deprecated, see NotifySubsystemsActiveSoundDeleting.
Definition at line 854 of file AudioDevice.h.
UE_DEPRECATED() [16/21]
template<typename TSubsystemClass> FAudioDevice::UE_DEPRECATED (5. 4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const & inline
Gets all Subsystems of specified type, this is only necessary for interfaces that can have multiple implementations instanced at a time.
Do not hold onto this Array reference unless you are sure the lifetime is less than that of the audio device
Definition at line 1982 of file AudioDevice.h.
References const, and SubsystemCollection.
UE_DEPRECATED() [17/21]
FAudioDevice::UE_DEPRECATED (5. 4, "Use RegisterSubmixBufferListener version that requires a shared reference to a listener and provide explicit reference to a submix: use GetMainSubmixObject to register with the Main Output Submix rather than nullptr for safety, and instantiate buffer listener via the shared pointer API.")
UE_DEPRECATED() [18/21]
FAudioDevice::UE_DEPRECATED (5. 4, "Use UnregisterSubmixBufferListener version that requires a shared reference to a listener and provide explicit reference to a submix: use GetMainSubmixObject to unregister from the Main Output Submix rather than nullptr for safety, and instantiate buffer listener via the shared pointer API.")
References SoundSubmix, UE_DEPRECATED(), and UnregisterSubmixBufferListener().
UE_DEPRECATED() [19/21]
FAudioDevice::UE_DEPRECATED (5. 5, "No longer needed for resource managment, existing calls may be deleted")
Stops any sound sources which are using the given buffer.
Parameters
FSoundBuffer Buffer to check against
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [20/21]
FAudioDevice::UE_DEPRECATED (5. 5, "NotifyAddActiveSound is deprecated. Use NotifySubsystemsActiveSoundCreated instead.") const & inline protected
Definition at line 885 of file AudioDevice.h.
References NotifySubsystemsActiveSoundCreated().
UE_DEPRECATED() [21/21]
FAudioDevice::UE_DEPRECATED (5. 5, "NotifyPendingDeleteInternal is deprecated. Use NotifySubsystemsActiveSoundDeleting and/or NotifySubsystemsVirtualizedSoundDeleting instead.") const & inline protected
Definition at line 891 of file AudioDevice.h.
References NotifySubsystemsActiveSoundDeleting().
UnlinkActiveSoundFromComponent()
void FAudioDevice::UnlinkActiveSoundFromComponent (const FActiveSound & InActiveSound)
Disables ActiveSound from responding to calls from its associated AudioComponent.
UnregisterPluginListener()
void FAudioDevice::UnregisterPluginListener (const TAudioPluginListenerPtr PluginListener)
Unregisters a third party listener-observer to this audio device.
UnregisterSoundClass()
void FAudioDevice::UnregisterSoundClass (USoundClass * SoundClass)
Unregisters a sound class.
UnregisterSoundSubmix()
virtual void FAudioDevice::UnregisterSoundSubmix (const USoundSubmixBase * SoundSubmix, const bool bReparentChildren) inline virtual
Unregisters the sound submix.
Definition at line 971 of file AudioDevice.h.
References SoundSubmix.
UnregisterSubmixBufferListener()
virtual void FAudioDevice::UnregisterSubmixBufferListener (TSharedRef< ISubmixBufferListener, ESPMode::ThreadSafe > InSubmixBufferListener, USoundSubmix & SoundSubmix) virtual
Unregisters the provided submix buffer listener with the given submix.
References SoundSubmix, ThreadSafe, and UnregisterSubmixBufferListener().
Referenced by UE_DEPRECATED(), and UnregisterSubmixBufferListener().
Update()
void FAudioDevice::Update (bool bGameTicking)
The audio system's main "Tick" function.
UpdateActiveSoundPlaybackTime()
void FAudioDevice::UpdateActiveSoundPlaybackTime (bool bIsTimeTicking)
Update the active sound playback time.
This is done here to do after all audio is updated.
UpdateAudioEngineSubsystems()
void FAudioDevice::UpdateAudioEngineSubsystems () private
Updates audio engine subsystems on this device.
UpdateAudioVolumeEffects()
void FAudioDevice::UpdateAudioVolumeEffects () private
Updates audio volume effects.
UpdateAudioVolumeProxy()
void FAudioDevice::UpdateAudioVolumeProxy (const FAudioVolumeProxy & Proxy)
References const, and UpdateAudioVolumeProxy().
Referenced by UpdateAudioVolumeProxy().
UpdateConcurrency()
void FAudioDevice::UpdateConcurrency (TArray< FWaveInstance * > & WaveInstances, TArray< FActiveSound * > & ActiveSoundsCopy) private
Stops quiet/low priority sounds due to being evaluated as not fulfilling concurrency requirements.
UpdateDeviceDeltaTime()
virtual void FAudioDevice::UpdateDeviceDeltaTime () inline virtual
Sets the update delta time for the audio frame.
Definition at line 1846 of file AudioDevice.h.
References DeviceDeltaTime, LastUpdateTime, FAndroidTime::Seconds(), and UE_REAL_TO_FLOAT.
UpdateEffect()
void * FAudioDevice::UpdateEffect (FSoundSource * Source)
Platform dependent call to update the sound output with new parameters The audio system's main "Tick" function.
References FSoundSource, and Source.
UpdateGameThread()
virtual void FAudioDevice::UpdateGameThread () inline virtual
Update called on game thread.
Definition at line 550 of file AudioDevice.h.
UpdateHardware()
virtual void FAudioDevice::UpdateHardware () inline virtual
Lets the platform any tick actions.
Definition at line 1794 of file AudioDevice.h.
UpdateHardwareTiming()
virtual void FAudioDevice::UpdateHardwareTiming () inline virtual
Updates timing information for hardware.
Definition at line 1789 of file AudioDevice.h.
UpdateHighestPriorityReverb()
void FAudioDevice::UpdateHighestPriorityReverb () private
Find the current highest priority reverb after a change to the list of active ones.
UpdatePassiveSoundMixModifiers()
void FAudioDevice::UpdatePassiveSoundMixModifiers (TArray< FWaveInstance * > & WaveInstances, int32 FirstActiveIndex) private
Updates list of SoundMixes that are applied passively, pushing and popping those that change.
Parameters
WaveInstances Sorted list of active wave instances
FirstActiveIndex Index of first wave instance that will be played.
UpdateReferencedSoundWaves()
void FAudioDevice::UpdateReferencedSoundWaves () private
UpdateSoundClassProperties()
void FAudioDevice::UpdateSoundClassProperties (float DeltaTime) private
Construct the CurrentSoundClassProperties map.
Parameters
DeltaTime The current frame delta. Used to interpolate sound class adjustments.
This contains the original sound class properties propagated properly, and all adjustments due to the sound mixes
References DeltaTime.
UpdateSoundDuration()
void FAudioDevice::UpdateSoundDuration (FWaveInstance * WaveInstance, bool bGameTicking) const private
Adjusts the active sound duration to make up for decode latency.
UpdateSoundMix()
void FAudioDevice::UpdateSoundMix (USoundMix * SoundMix, FSoundMixState * SoundMixState) private
Updates the state of a sound mix if it is pushed more than once.
Parameters
SoundMix The SoundMix we are updating
SoundMixState The State associated with this SoundMix
UpdateSourceEffectChain()
virtual void FAudioDevice::UpdateSourceEffectChain (const uint32 SourceEffectChainId, const TArray< FSourceEffectChainEntry > & SourceEffectChain, const bool bPlayEffectChainTails) inline virtual
Updates the source effect chain.
Only implemented in audio mixer.
Definition at line 1389 of file AudioDevice.h.
UpdateSubmixModulationSettings()
virtual void FAudioDevice::UpdateSubmixModulationSettings (USoundSubmix * InSoundSubmix, const TSet< TObjectPtr< USoundModulatorBase > > & InOutputModulation, const TSet< TObjectPtr< USoundModulatorBase > > & InWetLevelModulation, const TSet< TObjectPtr< USoundModulatorBase > > & InDryLevelModulation) inline virtual
Definition at line 1451 of file AudioDevice.h.
References Error, InDryLevelModulation, InOutputModulation, InWetLevelModulation, TEXT, and UE_LOG.
UpdateSubmixProperties()
virtual void FAudioDevice::UpdateSubmixProperties (USoundSubmixBase * InSubmix) inline virtual
Updates the submix properties of any playing submix instances.
Allows editor to make changes to submix properties and hear them propagate live.
Definition at line 1395 of file AudioDevice.h.
References Error, TEXT, and UE_LOG.
UpdateUnpreparedSound()
void FAudioDevice::UpdateUnpreparedSound (FWaveInstance * WaveInstance, bool bGameTicking) const private
Called by StartSources when sounds are not prepared to Init for whatever reason.
UpdateVirtualLoops()
void FAudioDevice::UpdateVirtualLoops (bool bForceUpdate)
ValidateAPICall()
virtual bool FAudioDevice::ValidateAPICall (const TCHAR * Function, uint32 ErrorCode) inline virtual
Check for errors and output a human readable string.
Definition at line 1168 of file AudioDevice.h.
References Function.
VirtualizeInactiveLoops()
void FAudioDevice::VirtualizeInactiveLoops () private
Friends And Related Symbol Documentation
FAudioEffectsManager
friend class FAudioEffectsManager friend
Definition at line 1090 of file AudioDevice.h.
References FAudioEffectsManager.
Referenced by CreateEffectsManager(), FAudioEffectsManager, GetEffects(), and GetEffects().
FSoundConcurrencyManager
friend class FSoundConcurrencyManager friend
Definition at line 2310 of file AudioDevice.h.
References FSoundConcurrencyManager.
Referenced by FSoundConcurrencyManager.
FSoundSource
friend class FSoundSource friend
Definition at line 1504 of file AudioDevice.h.
References FSoundSource.
Referenced by CreateSoundSource(), DestroyEffect(), FSoundSource, GetSoundSource(), InitEffect(), and UpdateEffect().
Field Documentation
ActivatedReverbs
TMap<FName, FActivatedReverb> FAudioDevice::ActivatedReverbs private
Reverb Effects activated without volumes - Game Thread owned.
Definition at line 2161 of file AudioDevice.h.
ActiveSounds
TArray<FActiveSound*> FAudioDevice::ActiveSounds private
The audio thread update delta time for this audio thread update tick.
Definition at line 2263 of file AudioDevice.h.
Referenced by GetActiveSounds().
ActiveWaveInstances
TArray<FWaveInstance*> FAudioDevice::ActiveWaveInstances private
Definition at line 2273 of file AudioDevice.h.
AudioClock
double FAudioDevice::AudioClock protected
The audio clock from the audio hardware.
Not supported on all platforms.
Definition at line 2239 of file AudioDevice.h.
Referenced by GetAudioClock().
AudioComponentIDToActiveSoundMap
TMap<uint64, TArray<FActiveSound*> > FAudioDevice::AudioComponentIDToActiveSoundMap private
Definition at line 2295 of file AudioDevice.h.
AudioComponentIDToCanHaveMultipleActiveSoundsMap
TMap<uint64, bool> FAudioDevice::AudioComponentIDToCanHaveMultipleActiveSoundsMap private
Used to determine if a given Audio Component should be allowed to have multiple simultaneous associated active sounds.
Definition at line 2298 of file AudioDevice.h.
AudioStateProperties
TMap<FName, FName> FAudioDevice::AudioStateProperties private
A generic mapping of FNames, used to store and retrieve tokens across the engine boundary.
Definition at line 2308 of file AudioDevice.h.
AudioThreadReferenceCritSec
FCriticalSection FAudioDevice::AudioThreadReferenceCritSec private
Definition at line 2269 of file AudioDevice.h.
AudioVolumeProxies
TMap<uint32, FAudioVolumeProxy> FAudioDevice::AudioVolumeProxies private
Definition at line 2300 of file AudioDevice.h.
bAllowCenterChannel3DPanning
uint8 FAudioDevice::bAllowCenterChannel3DPanning protected
Whether or not we allow center channel panning (audio mixer only feature.)
Definition at line 2242 of file AudioDevice.h.
bAllowPlayWhenSilent
uint8 FAudioDevice::bAllowPlayWhenSilent private
Whether or not we're supporting zero volume wave instances.
Definition at line 2255 of file AudioDevice.h.
Referenced by PlayWhenSilentEnabled().
BaseSoundMix
USoundMix* FAudioDevice::BaseSoundMix private
The Base SoundMix that's currently active.
Definition at line 2136 of file AudioDevice.h.
bAudioMixerModuleLoaded
uint8 FAudioDevice::bAudioMixerModuleLoaded
Whether or not the audio mixer module is being used by this device.
Definition at line 2193 of file AudioDevice.h.
bDisableAudioCaching
uint8 FAudioDevice::bDisableAudioCaching
HACK: Temporarily disable audio caching.
This will be done better by changing the decompression pool size in the future
Definition at line 2182 of file AudioDevice.h.
bGameWasTicking
uint8 FAudioDevice::bGameWasTicking private
Definition at line 2178 of file AudioDevice.h.
bHasActivatedReverb
uint8 FAudioDevice::bHasActivatedReverb private
Whether the value in HighestPriorityActivatedReverb should be used - Audio Thread owned.
Definition at line 2252 of file AudioDevice.h.
bHRTFDisabled
uint8 FAudioDevice::bHRTFDisabled private
Whether or not HRTF is disabled.
This will make any sounds which are set to HRTF spatialize to spatialize with panning.
Definition at line 2228 of file AudioDevice.h.
Referenced by SetHRTFDisabled().
bHRTFDisabled_OnGameThread
bool FAudioDevice::bHRTFDisabled_OnGameThread private
Gamethread representation of whether HRTF is disabbled for all 3d sounds.
Definition at line 2176 of file AudioDevice.h.
Referenced by SetHRTFDisabled().
bHRTFEnabledForAll
uint8 FAudioDevice::bHRTFEnabledForAll private
Whether HRTF is enabled for all 3d sounds.
This will automatically make all 3d mono sounds HRTF spatialized.
Definition at line 2225 of file AudioDevice.h.
Referenced by SetHRTFEnabledForAll().
bHRTFEnabledForAll_OnGameThread
bool FAudioDevice::bHRTFEnabledForAll_OnGameThread private
Gamethread representation of whether HRTF is enabled for all 3d sounds.
(not bitpacked to avoid thread issues)
Definition at line 2173 of file AudioDevice.h.
Referenced by SetHRTFEnabledForAll().
bIsAudioDeviceHardwareInitialized
uint8 FAudioDevice::bIsAudioDeviceHardwareInitialized
Whether or not the lower-level audio device hardware initialized.
Definition at line 2185 of file AudioDevice.h.
bIsBakedAnalysisEnabled
uint8 FAudioDevice::bIsBakedAnalysisEnabled
If baked analysis querying is enabled.
Definition at line 2190 of file AudioDevice.h.
Referenced by IsBakedAnalaysisQueryingEnabled().
bIsDeviceMuted
uint8 FAudioDevice::bIsDeviceMuted private
Whether the audio device is active (current audio device in-focus in PIE)
Definition at line 2231 of file AudioDevice.h.
bIsInitialized
uint8 FAudioDevice::bIsInitialized private
Whether the audio device has been initialized.
Definition at line 2234 of file AudioDevice.h.
Referenced by IsInitialized().
bIsStoppingVoicesEnabled
uint8 FAudioDevice::bIsStoppingVoicesEnabled
Definition at line 2187 of file AudioDevice.h.
Referenced by IsStoppingVoicesEnabled().
bModulationInterfaceEnabled
uint8 FAudioDevice::bModulationInterfaceEnabled private
Definition at line 2219 of file AudioDevice.h.
Referenced by IsModulationPluginEnabled().
bOcclusionInterfaceEnabled
uint8 FAudioDevice::bOcclusionInterfaceEnabled private
Definition at line 2216 of file AudioDevice.h.
Referenced by IsOcclusionPluginEnabled().
bOcclusionIsExternalSend
uint8 FAudioDevice::bOcclusionIsExternalSend
Whether or not various audio plugin interfaces are external sends.
Definition at line 2196 of file AudioDevice.h.
bPluginListenersInitialized
uint8 FAudioDevice::bPluginListenersInitialized private
Whether or not we've initialized plugin listeners array.
Definition at line 2222 of file AudioDevice.h.
bReverbInterfaceEnabled
uint8 FAudioDevice::bReverbInterfaceEnabled private
Definition at line 2217 of file AudioDevice.h.
Referenced by IsReverbPluginEnabled().
bReverbIsExternalSend
uint8 FAudioDevice::bReverbIsExternalSend
Definition at line 2197 of file AudioDevice.h.
bSourceDataOverrideInterfaceEnabled
uint8 FAudioDevice::bSourceDataOverrideInterfaceEnabled private
Definition at line 2218 of file AudioDevice.h.
Referenced by IsSourceDataOverridePluginEnabled().
bSpatializationInterfaceEnabled
uint8 FAudioDevice::bSpatializationInterfaceEnabled private
Whether or not various audio plugin interfaces are enabled.
Definition at line 2215 of file AudioDevice.h.
Referenced by IsSpatializationPluginEnabled(), and SetSpatializationInterfaceEnabled().
bStartupSoundsPreCached
uint8 FAudioDevice::bStartupSoundsPreCached private
True once the startup sounds have been precached.
Definition at line 2212 of file AudioDevice.h.
Referenced by AreStartupSoundsPreCached().
bUseAttenuationForNonGameWorlds
uint8 FAudioDevice::bUseAttenuationForNonGameWorlds private
Whether or not we force the use of attenuation for non-game worlds (as by default we only care about game worlds)
Definition at line 2258 of file AudioDevice.h.
Referenced by SetUseAttenuationForNonGameWorlds().
ConcurrencyManager
FSoundConcurrencyManager FAudioDevice::ConcurrencyManager private
Definition at line 2311 of file AudioDevice.h.
const [1/2]
const FTransform const float MaxDistance FAudioDevice::const
Definition at line 1020 of file AudioDevice.h.
Referenced by AddAudioVolumeProxy(), CanHaveMultipleActiveSounds(), GetDistanceSquaredToListener(), GetDistanceSquaredToNearestListener(), GetDistanceToNearestListener(), GetListenerPosition(), GetListenerTransform(), GetListenerWorldID(), GetSoundClassPropertyMap(), LocationIsAudible(), LocationIsAudible(), SetListener(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UpdateAudioVolumeProxy().
const [2/2]
const FTransform& ListenerTransform FAudioDevice::const
Definition at line 1033 of file AudioDevice.h.
CurrentAudioVolumeSettings
FAudioVolumeSettings FAudioDevice::CurrentAudioVolumeSettings private
The current audio volume settings the listener is in.
Definition at line 2170 of file AudioDevice.h.
CurrentReverbEffect
UReverbEffect* FAudioDevice::CurrentReverbEffect private
Definition at line 2152 of file AudioDevice.h.
Referenced by GetCurrentReverbEffect().
CurrentSpatializationInterfaceInfoPtr
FAudioSpatializationInterfaceInfo* FAudioDevice::CurrentSpatializationInterfaceInfoPtr = nullptr protected
Definition at line 2050 of file AudioDevice.h.
CurrentSpatializationPluginInterfaceName
FName FAudioDevice::CurrentSpatializationPluginInterfaceName protected
3rd party audio spatialization interface.
Definition at line 2048 of file AudioDevice.h.
CurrentTick
uint64 FAudioDevice::CurrentTick private
Definition at line 2086 of file AudioDevice.h.
DebugState
TEnumAsByte<enum EDebugState> FAudioDevice::DebugState private
The debug state of the audio device.
Definition at line 2092 of file AudioDevice.h.
Referenced by GetMixDebugState(), and SetMixDebugState().
DefaultBaseSoundMix
TObjectPtr<USoundMix> FAudioDevice::DefaultBaseSoundMix private
The Base SoundMix that should be applied by default.
Definition at line 2139 of file AudioDevice.h.
Referenced by GetDefaultBaseSoundMixModifier(), and SetSoundMixModifiers().
DefaultReverbSendLevel
float FAudioDevice::DefaultReverbSendLevel private
The default reverb send level to use for sources which have reverb applied but don't have an attenuation settings.
Definition at line 2158 of file AudioDevice.h.
Referenced by GetDefaultReverbSendLevel().
DeviceCreatedHandle
FDelegateHandle FAudioDevice::DeviceCreatedHandle protected
Definition at line 937 of file AudioDevice.h.
DeviceDeltaTime
float FAudioDevice::DeviceDeltaTime protected
Definition at line 2244 of file AudioDevice.h.
Referenced by UpdateDeviceDeltaTime().
DeviceDestroyedHandle
FDelegateHandle FAudioDevice::DeviceDestroyedHandle protected
Definition at line 940 of file AudioDevice.h.
DeviceID
Audio::FDeviceId FAudioDevice::DeviceID
The handle for this audio device used in the audio device manager.
Definition at line 2025 of file AudioDevice.h.
DynamicSoundClassProperties
TMap<USoundClass*, FSoundClassDynamicProperties> FAudioDevice::DynamicSoundClassProperties private
Definition at line 2133 of file AudioDevice.h.
Effects
FAudioEffectsManager* FAudioDevice::Effects protected
Interface to audio effects processing.
Definition at line 2149 of file AudioDevice.h.
Referenced by GetEffects(), and GetEffects().
FreeSources
TArray<FSoundSource*> FAudioDevice::FreeSources protected
Definition at line 2118 of file AudioDevice.h.
GlobalFocusSettings
FGlobalFocusSettings FAudioDevice::GlobalFocusSettings private
The global focus settings.
Definition at line 2104 of file AudioDevice.h.
GlobalFocusSettings_GameThread
FGlobalFocusSettings FAudioDevice::GlobalFocusSettings_GameThread private
Definition at line 2105 of file AudioDevice.h.
GlobalMaxPitch
float FAudioDevice::GlobalMaxPitch private
Definition at line 2321 of file AudioDevice.h.
GlobalMinPitch
float FAudioDevice::GlobalMinPitch private
Definition at line 2320 of file AudioDevice.h.
GlobalPitchScale
FDynamicParameter FAudioDevice::GlobalPitchScale private
Global dynamic pitch scale parameter.
Definition at line 2101 of file AudioDevice.h.
Referenced by GetGlobalPitchScale().
HighestPriorityActivatedReverb_AudioThread
FActivatedReverb FAudioDevice::HighestPriorityActivatedReverb_AudioThread private
The activated reverb that currently has the highest priority - Audio Thread owned.
Definition at line 2167 of file AudioDevice.h.
InDryLevelModulation
USoundModulatorBase USoundModulatorBase USoundModulatorBase* FAudioDevice::InDryLevelModulation
Initial value:
{
        UE_LOG(LogAudio, Error, TEXT("Submixes are only supported in audio mixer & 'UpdateSubmixModulationSettings' function taking single modulators no longer supported."))
Definition at line 1446 of file AudioDevice.h.
Referenced by UpdateSubmixModulationSettings().
InOutputModulation
USoundModulatorBase* FAudioDevice::InOutputModulation
Definition at line 1446 of file AudioDevice.h.
Referenced by UpdateSubmixModulationSettings().
InverseListenerTransforms
TArray<FMatrix> FAudioDevice::InverseListenerTransforms private
Inverse listener transformations, used for spatialization.
Definition at line 2314 of file AudioDevice.h.
InWetLevelModulation
USoundModulatorBase USoundModulatorBase* FAudioDevice::InWetLevelModulation
Definition at line 1446 of file AudioDevice.h.
Referenced by UpdateSubmixModulationSettings().
LastUpdateTime
double FAudioDevice::LastUpdateTime private
Timestamp of the last update.
Definition at line 2108 of file AudioDevice.h.
Referenced by UpdateDeviceDeltaTime().
ListenerProxies
TArray<FListenerProxy> FAudioDevice::ListenerProxies
Definition at line 2072 of file AudioDevice.h.
Listeners
TArray<FListener> FAudioDevice::Listeners protected
Definition at line 2115 of file AudioDevice.h.
Referenced by GetListeners().
ListenerTransform
const FTransform& FAudioDevice::ListenerTransform
Definition at line 1020 of file AudioDevice.h.
Referenced by SetListener().
MaxActiveSoundsAddedPerFrame
int32 FAudioDevice::MaxActiveSoundsAddedPerFrame private
Max number of active sounds to add per frame.
Definition at line 2290 of file AudioDevice.h.
MaxChannels
int32 FAudioDevice::MaxChannels private
The maximum number of concurrent audible sounds.
Value cannot exceed MaxSources.
Definition at line 2079 of file AudioDevice.h.
MaxChannels_GameThread
int32 FAudioDevice::MaxChannels_GameThread private
Definition at line 2080 of file AudioDevice.h.
MaxChannelsScale
float FAudioDevice::MaxChannelsScale private
Normalized (0.0f - 1.0f) scalar multiplier on max channels.
Definition at line 2083 of file AudioDevice.h.
MaxChannelsScale_GameThread
float FAudioDevice::MaxChannelsScale_GameThread private
Definition at line 2084 of file AudioDevice.h.
MaxSources
int32 FAudioDevice::MaxSources private
The maximum number of sources.
Value cannot change after initialization.
Definition at line 2076 of file AudioDevice.h.
ModulationInterface
TAudioModulationPtr FAudioDevice::ModulationInterface
3rd party modulation interface
Definition at line 2066 of file AudioDevice.h.
NextResourceID
int32 FAudioDevice::NextResourceID private
Next resource ID to assign out to a wave/buffer.
Definition at line 2111 of file AudioDevice.h.
NumPrecacheFrames
int32 FAudioDevice::NumPrecacheFrames
The number of frames to precache.
Definition at line 2022 of file AudioDevice.h.
NumStoppingSources
int32 FAudioDevice::NumStoppingSources
The number of sources to reserve for stopping sounds.
Definition at line 2013 of file AudioDevice.h.
OcclusionInterface
TAudioOcclusionPtr FAudioDevice::OcclusionInterface
3rd party occlusion interface.
Definition at line 2063 of file AudioDevice.h.
OnAudioDevicePostRender
FOnAudioDevicePostRender FAudioDevice::OnAudioDevicePostRender protected
Definition at line 948 of file AudioDevice.h.
OnAudioDevicePreRender
FOnAudioDevicePreRender FAudioDevice::OnAudioDevicePreRender protected
Definition at line 945 of file AudioDevice.h.
OneShotCount
uint32 FAudioDevice::OneShotCount private
A count of the number of one-shot active sounds.
Definition at line 2317 of file AudioDevice.h.
PendingActivatedReverb
TSharedPtr<FActivatedReverb> FAudioDevice::PendingActivatedReverb private
Most recently activated in-flight reverb going from the GT to the AT.
Definition at line 2164 of file AudioDevice.h.
PendingAddedActiveSounds
TQueue<FActiveSound*> FAudioDevice::PendingAddedActiveSounds private
Pending active sounds waiting to be added.
Definition at line 2287 of file AudioDevice.h.
PendingSoundsToDelete
TArray<FActiveSound*> FAudioDevice::PendingSoundsToDelete private
A set of sounds which need to be deleted but weren't able to be deleted due to pending async operations.
Definition at line 2293 of file AudioDevice.h.
PendingSoundsToStop
TSet<FActiveSound*> FAudioDevice::PendingSoundsToStop private
Set of sounds which will be stopped next audio frame update.
Definition at line 2284 of file AudioDevice.h.
PlatformAudioHeadroom
float FAudioDevice::PlatformAudioHeadroom private
A volume headroom to apply to specific platforms to achieve better platform consistency.
Definition at line 2155 of file AudioDevice.h.
Referenced by GetPlatformAudioHeadroom().
PlatformSettings
FAudioPlatformSettings FAudioDevice::PlatformSettings
The platform specific audio settings.
Definition at line 2019 of file AudioDevice.h.
Referenced by GetBufferLength(), and GetNumBuffers().
PluginInitializationParams
FAudioPluginInitializationParams FAudioDevice::PluginInitializationParams protected
Cached parameters passed to the initialization of various audio plugins.
Definition at line 2053 of file AudioDevice.h.
PluginListeners
TArray<TAudioPluginListenerPtr> FAudioDevice::PluginListeners
3rd party listener observers registered to this audio device.
Definition at line 2069 of file AudioDevice.h.
PrecachingSoundWaves
TArray<USoundWave*> FAudioDevice::PrecachingSoundWaves private
Definition at line 2271 of file AudioDevice.h.
PrevPassiveSoundMixModifiers
TArray<TObjectPtr<USoundMix> > FAudioDevice::PrevPassiveSoundMixModifiers private
List of passive SoundMixes active last frame.
Definition at line 2305 of file AudioDevice.h.
Referenced by GetPrevPassiveSoundMixModifiers(), and SetSoundMixModifiers().
PrimaryVolume
float FAudioDevice::PrimaryVolume private
The master volume of the game combines the FApp::GetVolumeMultipler() value and the TransientPrimaryVolume.
Definition at line 2098 of file AudioDevice.h.
Referenced by GetPrimaryVolume(), and UE_DEPRECATED().
ReferencedSoundWaves
TArray<TObjectPtr<USoundWave> > FAudioDevice::ReferencedSoundWaves private
Array of sound waves to add references to avoid GC until guaranteed to be done with precache or decodes.
Definition at line 2265 of file AudioDevice.h.
ReferencedSoundWaves_AudioThread
TArray<USoundWave*> FAudioDevice::ReferencedSoundWaves_AudioThread private
Definition at line 2268 of file AudioDevice.h.
RenderStateCallbackListCritSec
FCriticalSection FAudioDevice::RenderStateCallbackListCritSec protected
Definition at line 942 of file AudioDevice.h.
ReverbPluginInterface
TAudioReverbPtr FAudioDevice::ReverbPluginInterface
3rd party reverb interface.
Definition at line 2060 of file AudioDevice.h.
SampleRate
int32 FAudioDevice::SampleRate
The sample rate of all the audio devices.
Definition at line 2016 of file AudioDevice.h.
Referenced by GetSampleRate().
SoundClassAdjustersCopy
TArray<FSoundClassAdjuster> FAudioDevice::SoundClassAdjustersCopy private
Cached copy of sound class adjusters array.
Cached to avoid allocating every frame.
Definition at line 2281 of file AudioDevice.h.
SoundClasses
TMap<USoundClass*, FSoundClassProperties> FAudioDevice::SoundClasses private
Current properties of all sound classes.
Definition at line 2132 of file AudioDevice.h.
Referenced by GetSoundClassPropertyMap().
SoundMixClassEffectOverrides
TMap<USoundMix*, FSoundMixClassOverrideMap> FAudioDevice::SoundMixClassEffectOverrides private
Map of sound mix sound class overrides.
Will override any sound class effects for any sound mixes
Definition at line 2145 of file AudioDevice.h.
SoundMixModifiers
TMap<TObjectPtr<USoundMix>, FSoundMixState> FAudioDevice::SoundMixModifiers private
Map of sound mixes currently affecting audio properties.
Definition at line 2142 of file AudioDevice.h.
Referenced by GetSoundMixModifiers(), and SetSoundMixModifiers().
SoundSubmix
USoundSubmix * FAudioDevice::SoundSubmix = nullptr)
Definition at line 976 of file AudioDevice.h.
Referenced by RegisterSoundSubmix(), RegisterSubmixBufferListener(), UE_DEPRECATED(), UnregisterSoundSubmix(), and UnregisterSubmixBufferListener().
SourceDataOverridePluginInterface
TAudioSourceDataOverridePtr FAudioDevice::SourceDataOverridePluginInterface
3rd party source data override interface.
Definition at line 2057 of file AudioDevice.h.
Sources
TArray<FSoundSource*> FAudioDevice::Sources protected
Definition at line 2117 of file AudioDevice.h.
Referenced by GetNumFreeSources().
SpatializationInterfaces
TArray<FAudioSpatializationInterfaceInfo> FAudioDevice::SpatializationInterfaces protected
Definition at line 2049 of file AudioDevice.h.
SubsystemCollection
FAudioSubsystemCollection FAudioDevice::SubsystemCollection private
Subsystems tied to this device's lifecycle.
Definition at line 2126 of file AudioDevice.h.
Referenced by ForEachSubsystem(), GetSubsystem(), GetSubsystemArrayCopy(), GetSubsystemBase(), and UE_DEPRECATED().
SubsystemCollectionRoot
TStrongObjectPtr<UAudioSubsystemCollectionRoot> FAudioDevice::SubsystemCollectionRoot private
Anchor used to connect UAudioEngineSubsystems to FAudioDevice.
Definition at line 2123 of file AudioDevice.h.
TestAudioComponent
TStrongObjectPtr<UAudioComponent> FAudioDevice::TestAudioComponent private
An AudioComponent to play test sounds on.
Definition at line 2089 of file AudioDevice.h.
TransientPrimaryVolume
float FAudioDevice::TransientPrimaryVolume private
transient master volume multiplier that can be modified at runtime without affecting user settings automatically reset to 1.0 on level change
Definition at line 2095 of file AudioDevice.h.
Referenced by GetTransientPrimaryVolume(), SetTransientPrimaryVolume(), UE_DEPRECATED(), and UE_DEPRECATED().
VirtualLoops
TMap<FActiveSound*, FAudioVirtualLoop> FAudioDevice::VirtualLoops private
Array of dormant loops stopped due to proximity/applicable concurrency rules that can be retriggered.
Definition at line 2278 of file AudioDevice.h.
WaveInstanceSourceMap
TMap<FWaveInstance*, FSoundSource*> FAudioDevice::WaveInstanceSourceMap private
Set of sources used to play sounds (platform will subclass these)
Definition at line 2129 of file AudioDevice.h.
WorldIDToDefaultAudioVolumeSettingsMap
TMap<uint32, TPair<FReverbSettings,FInteriorSettings> > FAudioDevice::WorldIDToDefaultAudioVolumeSettingsMap private
Definition at line 2302 of file AudioDevice.h.
The documentation for this class was generated from the following file:
AudioDevice.h