Unreal Engine 5.6 C++ API: FMetasoundAssetBase Class Reference
FMetasoundAssetBase Class Reference abstract
FMetasoundAssetBase is a mix-in subclass for UObjects which utilize MetaSound objects.
#include "MetasoundAssetBase.h"
Data Structures
struct FSendInfoAndVertexName
Public Member Functions
FMetasoundAssetBase ()=default
virtual ~FMetasoundAssetBase ()=default
METASOUNDFRONTEND_API bool AddingReferenceCausesLoop (const FMetasoundAssetBase &InMetaSound) const
METASOUNDFRONTEND_API void CacheRegistryMetadata ()
virtual METASOUNDFRONTEND_API TSharedPtr< Audio::IProxyData > CreateProxyData (const Audio::FProxyDataInitParams &InitParams) override
virtual const TSet< FSoftObjectPath > & GetAsyncReferencedAssetClassPaths () const =0
virtual METASOUNDFRONTEND_API const FMetasoundFrontendDocument & GetConstDocumentChecked () const
METASOUNDFRONTEND_API const FMetasoundFrontendDocumentModifyContext & GetConstModifyContext () const
METASOUNDFRONTEND_API FMetasoundFrontendDocument & GetDocumentChecked ()
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentHandle GetDocumentHandle ()
METASOUNDFRONTEND_API Metasound::Frontend::FConstDocumentHandle GetDocumentHandle () const
METASOUNDFRONTEND_API const Metasound::Frontend::FGraphRegistryKey & GetGraphRegistryKey () const
METASOUNDFRONTEND_API FMetasoundFrontendDocumentModifyContext & GetModifyContext ()
virtual const UObject * GetOwningAsset () const =0
virtual UObject * GetOwningAsset ()=0
METASOUNDFRONTEND_API FString GetOwningAssetName () const
virtual const TSet< FString > & GetReferencedAssetClassKeys () const =0
virtual TArray< FMetasoundAssetBase * > GetReferencedAssets ()=0
METASOUNDFRONTEND_API Metasound::Frontend::FGraphHandle GetRootGraphHandle ()
METASOUNDFRONTEND_API Metasound::Frontend::FConstGraphHandle GetRootGraphHandle () const
METASOUNDFRONTEND_API bool ImportFromJSON (const FString &InJSON)
METASOUNDFRONTEND_API bool ImportFromJSONAsset (const FString &InAbsolutePath)
METASOUNDFRONTEND_API bool IsInterfaceDeclared (const FMetasoundFrontendVersion &InVersion) const
METASOUNDFRONTEND_API bool IsReferencedAsset (const FMetasoundAssetBase &InAssetToCheck) const
METASOUNDFRONTEND_API bool IsRegistered () const
METASOUNDFRONTEND_API bool MarkMetasoundDocumentDirty () const
virtual void OnAsyncReferencedAssetsLoaded (const TArray< FMetasoundAssetBase * > &InAsyncReferences)=0
METASOUNDFRONTEND_API void RebuildReferencedAssetClasses ()
UE_DEPRECATED (5.5, "Direct mutation of the document is no longer supported via AssetBase.") METASOUNDFRONTEND_API void SetDocument(FMetasoundFrontendDocument InDocument
UE_DEPRECATED (5.5, "Moved to IMetaSoundDocumentInterface::ConformObjectToDocument") METASOUNDFRONTEND_API virtual bool ConformObjectDataToInterfaces()
UE_DEPRECATED (5.5, "Moved to UpdateAndRegisterForSerialization instead, which is only in builds set to load editor-only data.") METASOUNDFRONTEND_API void CookMetaSound()
UE_DEPRECATED (5.5, "Use GetConstDocument from casting Owning Asset to IMetaSoundDocumentInterface (See 'GetOwningAsset') instead.") METASOUNDFRONTEND_API const FMetasoundFrontendDocument &GetDocumentChecked() const
UE_DEPRECATED (5.5, "Use GetConstModifyContext") METASOUNDFRONTEND_API const FMetasoundFrontendDocumentModifyContext &GetModifyContext() const
UE_DEPRECATED (5.5, "Use IMetaSoundDocumentInterface 'IsActivelyBuilding' instead") virtual bool IsBuilderActive() const
UE_DEPRECATED (5.5, "Use overload that is provided an AssetBase") METASOUNDFRONTEND_API bool AddingReferenceCausesLoop(const FSoftObjectPath &InReferencePath) const
UE_DEPRECATED(5.5, "Moved to UpdateAndRegisterForExecution.") METASOUNDFRONTEND_API virtual void RegisterGraphWithFrontend(Metasound METASOUNDFRONTEND_API void UnregisterGraphWithFrontend ()
virtual METASOUNDFRONTEND_API void UpdateAndRegisterForExecution (Metasound::Frontend::FMetaSoundAssetRegistrationOptions InRegistrationOptions=Metasound::Frontend::FMetaSoundAssetRegistrationOptions())
Data Fields
bool bMarkDirty = true)
Static Public Attributes
static METASOUNDFRONTEND_API const FString FileExtension
Protected Member Functions
virtual UE_DEPRECATED(5.6, "AccessPtrs are actively being deprecated. Writable access outside of the builder API " " is particularly problematic as in so accessing, the builder's caches are reset which can cause major " "editor performance regressions.") virtual Metasound Metasound::Frontend::FConstDocumentAccessPtr GetDocumentConstAccessPtr () const =0
METASOUNDFRONTEND_API void OnNotifyBeginDestroy ()
METASOUNDFRONTEND_API void RegisterAssetDependencies (const Metasound::Frontend::FMetaSoundAssetRegistrationOptions &InRegistrationOptions)
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void SetReferencedAssets (TSet< Metasound::Frontend::IMetaSoundAssetManager::FAssetRef > &&InAssetRefs)=0
UE_DEPRECATED (5.3, "MetaSounds no longer communicate using FSendInfo.") METASOUNDFRONTEND_API TArray< FSendInfoAndVertexName > GetSendInfos(uint64 InInstanceID) const
UE_DEPRECATED (5.5, "AutoUpdate implementation now private and implemented within 'Version Dependencies'") METASOUNDFRONTEND_API bool AutoUpdate(bool bInLogWarningsOnDroppedConnection)
UE_DEPRECATED (5.5, "Moved to private, non-cook specific implementation") METASOUNDFRONTEND_API void CookReferencedMetaSounds()
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Use SetReferencedAssets instead") virtual void SetReferencedAssetClasses(TSet< Metasound
Private Member Functions
METASOUNDFRONTEND_API FMetasoundFrontendInterface GetInterfaceToVersion (const FMetasoundFrontendVersion &InterfaceVersion) const
METASOUNDFRONTEND_API bool TryUpdateInterfaceFromVersion (const FMetasoundFrontendVersion &Version)
METASOUNDFRONTEND_API bool VersionDependencies (FMetaSoundFrontendDocumentBuilder &Builder, bool bInLogWarningsOnDroppedConnection)
Private Attributes
Metasound::Frontend::FGraphRegistryKey GraphRegistryKey
Detailed Description
FMetasoundAssetBase is a mix-in subclass for UObjects which utilize MetaSound objects.
As MetaSounds can now be generated dynamically via the Builder API, the name does not accurately reflect this classes current implementation. While it currently has some support for asset, editor graph & document accessors (actively being deprecated), its primary use is to support all access to runtime-specific, MetaSound features and associated data, such as proxy generation and runtime node class registration. For forward support of the MetaSound document model and supported accessors, see 'IMetaSoundDocumentInterface'.
Definition at line 56 of file MetasoundAssetBase.h.
Constructor & Destructor Documentation
FMetasoundAssetBase()
FMetasoundAssetBase::FMetasoundAssetBase () default
Referenced by AddingReferenceCausesLoop(), and IsReferencedAsset().
~FMetasoundAssetBase()
virtual FMetasoundAssetBase::~FMetasoundAssetBase () virtual default
Member Function Documentation
AddingReferenceCausesLoop()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::AddingReferenceCausesLoop (const FMetasoundAssetBase & InMetaSound) const
References FMetasoundAssetBase(), and UE_API.
Referenced by UE_DEPRECATED().
CacheRegistryMetadata()
METASOUNDFRONTEND_API void FMetasoundAssetBase::CacheRegistryMetadata ()
References UE_API.
CreateProxyData()
virtual METASOUNDFRONTEND_API TSharedPtr< Audio::IProxyData > FMetasoundAssetBase::CreateProxyData (const Audio::FProxyDataInitParams & InitParams) override virtual
References UE_API.
GetAsyncReferencedAssetClassPaths()
virtual const TSet< FSoftObjectPath > & FMetasoundAssetBase::GetAsyncReferencedAssetClassPaths () const pure virtual
GetConstDocumentChecked()
virtual METASOUNDFRONTEND_API const FMetasoundFrontendDocument & FMetasoundAssetBase::GetConstDocumentChecked () const virtual
References GetConstDocumentChecked(), and UE_API.
Referenced by GetConstDocumentChecked().
GetConstModifyContext()
METASOUNDFRONTEND_API const FMetasoundFrontendDocumentModifyContext & FMetasoundAssetBase::GetConstModifyContext () const
References GetConstModifyContext(), and UE_API.
Referenced by GetConstModifyContext().
GetDocumentChecked()
METASOUNDFRONTEND_API FMetasoundFrontendDocument & FMetasoundAssetBase::GetDocumentChecked ()
References GetDocumentChecked(), and UE_API.
Referenced by GetDocumentChecked(), and UE_DEPRECATED().
GetDocumentConstAccessPtr()
virtual UE_DEPRECATED(5.6, "AccessPtrs are actively being deprecated. Writable access outside of the builder API " " is particularly problematic as in so accessing, the builder's caches are reset which can cause major " "editor performance regressions.") virtual Metasound Metasound::Frontend::FConstDocumentAccessPtr FMetasoundAssetBase::GetDocumentConstAccessPtr () const protected pure virtual
References GetDocumentConstAccessPtr().
Referenced by GetDocumentConstAccessPtr().
GetDocumentHandle() [1/2]
METASOUNDFRONTEND_API Metasound::Frontend::FDocumentHandle FMetasoundAssetBase::GetDocumentHandle ()
References GetDocumentHandle(), and UE_API.
Referenced by GetDocumentHandle(), and GetDocumentHandle().
GetDocumentHandle() [2/2]
METASOUNDFRONTEND_API Metasound::Frontend::FConstDocumentHandle FMetasoundAssetBase::GetDocumentHandle () const
References GetDocumentHandle(), and UE_API.
GetGraphRegistryKey()
METASOUNDFRONTEND_API const Metasound::Frontend::FGraphRegistryKey & FMetasoundAssetBase::GetGraphRegistryKey () const
References GetGraphRegistryKey(), and UE_API.
Referenced by GetGraphRegistryKey().
GetInterfaceToVersion()
METASOUNDFRONTEND_API FMetasoundFrontendInterface FMetasoundAssetBase::GetInterfaceToVersion (const FMetasoundFrontendVersion & InterfaceVersion) const private
References UE_API.
GetModifyContext()
METASOUNDFRONTEND_API FMetasoundFrontendDocumentModifyContext & FMetasoundAssetBase::GetModifyContext ()
References UE_API.
Referenced by UE_DEPRECATED().
GetOwningAsset() [1/2]
virtual const UObject * FMetasoundAssetBase::GetOwningAsset () const pure virtual
GetOwningAsset() [2/2]
virtual UObject * FMetasoundAssetBase::GetOwningAsset () pure virtual
GetOwningAssetName()
METASOUNDFRONTEND_API FString FMetasoundAssetBase::GetOwningAssetName () const
References UE_API.
GetReferencedAssetClassKeys()
virtual const TSet< FString > & FMetasoundAssetBase::GetReferencedAssetClassKeys () const pure virtual
GetReferencedAssets()
virtual TArray< FMetasoundAssetBase * > FMetasoundAssetBase::GetReferencedAssets () pure virtual
GetRootGraphHandle() [1/2]
METASOUNDFRONTEND_API Metasound::Frontend::FGraphHandle FMetasoundAssetBase::GetRootGraphHandle ()
References GetRootGraphHandle(), and UE_API.
Referenced by GetRootGraphHandle(), and GetRootGraphHandle().
GetRootGraphHandle() [2/2]
METASOUNDFRONTEND_API Metasound::Frontend::FConstGraphHandle FMetasoundAssetBase::GetRootGraphHandle () const
References GetRootGraphHandle(), and UE_API.
ImportFromJSON()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::ImportFromJSON (const FString & InJSON)
References ImportFromJSON(), and UE_API.
Referenced by ImportFromJSON().
ImportFromJSONAsset()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::ImportFromJSONAsset (const FString & InAbsolutePath)
References ImportFromJSONAsset(), and UE_API.
Referenced by ImportFromJSONAsset().
IsInterfaceDeclared()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::IsInterfaceDeclared (const FMetasoundFrontendVersion & InVersion) const
References UE_API.
IsReferencedAsset()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::IsReferencedAsset (const FMetasoundAssetBase & InAssetToCheck) const
References FMetasoundAssetBase(), IsReferencedAsset(), and UE_API.
Referenced by IsReferencedAsset().
IsRegistered()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::IsRegistered () const
References IsRegistered(), and UE_API.
Referenced by IsRegistered().
MarkMetasoundDocumentDirty()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::MarkMetasoundDocumentDirty () const
References UE_API.
OnAsyncReferencedAssetsLoaded()
virtual void FMetasoundAssetBase::OnAsyncReferencedAssetsLoaded (const TArray< FMetasoundAssetBase * > & InAsyncReferences) pure virtual
OnNotifyBeginDestroy()
METASOUNDFRONTEND_API void FMetasoundAssetBase::OnNotifyBeginDestroy () protected
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
RebuildReferencedAssetClasses()
METASOUNDFRONTEND_API void FMetasoundAssetBase::RebuildReferencedAssetClasses ()
References UE_API.
RegisterAssetDependencies()
METASOUNDFRONTEND_API void FMetasoundAssetBase::RegisterAssetDependencies (const Metasound::Frontend::FMetaSoundAssetRegistrationOptions & InRegistrationOptions) protected
References RegisterAssetDependencies(), and UE_API.
Referenced by RegisterAssetDependencies().
SetReferencedAssets()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void FMetasoundAssetBase::SetReferencedAssets (TSet< Metasound::Frontend::IMetaSoundAssetManager::FAssetRef > && InAssetRefs) protected pure virtual
TryUpdateInterfaceFromVersion()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::TryUpdateInterfaceFromVersion (const FMetasoundFrontendVersion & Version) private
References UE_API.
UE_DEPRECATED() [1/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 3, "MetaSounds no longer communicate using FSendInfo.") const protected
References UE_API.
UE_DEPRECATED() [2/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "AutoUpdate implementation now private and implemented within 'Version Dependencies'") protected
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [3/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Direct mutation of the document is no longer supported via AssetBase.")
References UE_DEPRECATED().
UE_DEPRECATED() [4/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Moved to IMetaSoundDocumentInterface::ConformObjectToDocument")
References UE_API.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UpdateAndRegisterForExecution().
UE_DEPRECATED() [5/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Moved to private, non-cook specific implementation") protected
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [6/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Moved to UpdateAndRegisterForSerialization instead, which is only in builds set to load editor-only data.")
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [7/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Use GetConstDocument from casting Owning Asset to IMetaSoundDocumentInterface (See 'GetOwningAsset') instead.") const &
References GetDocumentChecked(), UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [8/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Use GetConstModifyContext") const &
References GetModifyContext(), and UE_API.
UE_DEPRECATED() [9/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Use IMetaSoundDocumentInterface 'IsActivelyBuilding' instead") const inline
Definition at line 210 of file MetasoundAssetBase.h.
References checkNoEntry.
UE_DEPRECATED() [10/11]
FMetasoundAssetBase::UE_DEPRECATED (5. 5, "Use overload that is provided an AssetBase") const &
References AddingReferenceCausesLoop(), and UE_API.
UE_DEPRECATED() [11/11]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMetasoundAssetBase::UE_DEPRECATED (5. 6, "Use SetReferencedAssets instead") inline protected
Definition at line 218 of file MetasoundAssetBase.h.
UnregisterGraphWithFrontend()
UE_DEPRECATED(5.5, "Moved to UpdateAndRegisterForExecution.") METASOUNDFRONTEND_API virtual void RegisterGraphWithFrontend(Metasound METASOUNDFRONTEND_API void FMetasoundAssetBase::UnregisterGraphWithFrontend ()
References UE_API, and UnregisterGraphWithFrontend().
Referenced by UnregisterGraphWithFrontend().
UpdateAndRegisterForExecution()
virtual METASOUNDFRONTEND_API void FMetasoundAssetBase::UpdateAndRegisterForExecution (Metasound::Frontend::FMetaSoundAssetRegistrationOptions InRegistrationOptions = Metasound::Frontend::FMetaSoundAssetRegistrationOptions()) virtual
References UE_API, UE_DEPRECATED(), and UpdateAndRegisterForExecution().
Referenced by UpdateAndRegisterForExecution().
VersionDependencies()
METASOUNDFRONTEND_API bool FMetasoundAssetBase::VersionDependencies (FMetaSoundFrontendDocumentBuilder & Builder, bool bInLogWarningsOnDroppedConnection) private
References UE_API.
Field Documentation
bMarkDirty
bool FMetasoundAssetBase::bMarkDirty = true)
Definition at line 153 of file MetasoundAssetBase.h.
FileExtension
METASOUNDFRONTEND_API const FString FMetasoundAssetBase::FileExtension static
Definition at line 61 of file MetasoundAssetBase.h.
GraphRegistryKey
Metasound::Frontend::FGraphRegistryKey FMetasoundAssetBase::GraphRegistryKey private
Definition at line 270 of file MetasoundAssetBase.h.
The documentation for this class was generated from the following file:
MetasoundAssetBase.h