Unreal Engine 5.6 C++ API: FInitStaticResourceRenderThreadTask Class Reference
FInitStaticResourceRenderThreadTask Class Reference
Helper task to initialize a static resource on the render thread.
#include "RHIStaticStates.h"
Public Member Functions
FInitStaticResourceRenderThreadTask (void(*InDoConstruct)(), FScopedEvent &InEvent)
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
ENamedThreads::Type GetDesiredThread ()
FORCEINLINE TStatId GetStatId () const
Static Public Member Functions
static ESubsequentsMode::Type GetSubsequentsMode ()
Private Attributes
void(* DoConstruct)()
FScopedEvent & Event
Detailed Description
Helper task to initialize a static resource on the render thread.
Definition at line 19 of file RHIStaticStates.h.
Constructor & Destructor Documentation
FInitStaticResourceRenderThreadTask()
FInitStaticResourceRenderThreadTask::FInitStaticResourceRenderThreadTask (void(* InDoConstruct)(), FScopedEvent & InEvent) inline
Definition at line 25 of file RHIStaticStates.h.
References DoConstruct, and Event.
Referenced by GetStatId().
Member Function Documentation
DoTask()
void FInitStaticResourceRenderThreadTask::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Definition at line 43 of file RHIStaticStates.h.
References DoConstruct, and Event.
GetDesiredThread()
ENamedThreads::Type FInitStaticResourceRenderThreadTask::GetDesiredThread () inline
Definition at line 36 of file RHIStaticStates.h.
References ENamedThreads::GetRenderThread_Local().
GetStatId()
FORCEINLINE TStatId FInitStaticResourceRenderThreadTask::GetStatId () const inline
Definition at line 31 of file RHIStaticStates.h.
References FInitStaticResourceRenderThreadTask(), FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
GetSubsequentsMode()
ESubsequentsMode::Type FInitStaticResourceRenderThreadTask::GetSubsequentsMode () inline static
Definition at line 41 of file RHIStaticStates.h.
References ESubsequentsMode::FireAndForget.
Field Documentation
DoConstruct
void(* FInitStaticResourceRenderThreadTask::DoConstruct) () private
Definition at line 21 of file RHIStaticStates.h.
Referenced by FInitStaticResourceRenderThreadTask(), and DoTask().
Event
FScopedEvent& FInitStaticResourceRenderThreadTask::Event private
Definition at line 22 of file RHIStaticStates.h.
Referenced by FInitStaticResourceRenderThreadTask(), and DoTask().
The documentation for this class was generated from the following file:
RHIStaticStates.h