Unreal Engine 5.6 C++ API: FMeshRenderBufferSet Class Reference
FMeshRenderBufferSet Class Reference
FMeshRenderBufferSet stores a set of RenderBuffers for a mesh.
#include "MeshRenderBufferSet.h"
Public Member Functions
FMeshRenderBufferSet (ERHIFeatureLevel::Type FeatureLevelType)
virtual ~FMeshRenderBufferSet ()
void InvalidateRayTracingData ()
GEOMETRYFRAMEWORK_API void TransferVertexUpdateToGPU (FRHICommandListBase &RHICmdList, bool bPositions, bool bNormals, bool bTexCoords, bool bColors)
Fast path to update various vertex buffers.
GEOMETRYFRAMEWORK_API void Upload ()
Upload initialized mesh buffers.
void UploadIndexBufferUpdate ()
Fast path to only update the primary and secondary index buffers.
GEOMETRYFRAMEWORK_API void UploadVertexUpdate (bool bPositions, bool bMeshAttribs, bool bColors)
Fast path to only update vertex buffers.
void ValidateRayTracingData ()
Static Public Member Functions
static void DestroyRenderBufferSet (FMeshRenderBufferSet *BufferSet)
Enqueue a command on the Render Thread to destroy the passed in buffer set.
Data Fields
bool bEnableRaytracing = false
configure whether raytracing should be enabled for this RenderBufferSet
bool bEnableSecondaryIndexBuffer = false
If secondary index buffer is enabled, we populate this index buffer with additional triangles indexing into the same vertex buffers.
FCriticalSection BuffersLock
In situations where we want to update the existing Vertex or Index buffers, we need to synchronize access between the Game and Render threads.
FColorVertexBuffer ColorVertexBuffer
The buffer containing the vertex color data.
FDynamicMeshIndexBuffer32 IndexBuffer
triangle indices
UMaterialInterface * Material = nullptr
Material to draw this mesh with.
FPositionVertexBuffer PositionVertexBuffer
The buffer containing the position vertex data.
FDynamicMeshIndexBuffer32 SecondaryIndexBuffer
partition or subset of IndexBuffer that indexes into same vertex buffers
FStaticMeshVertexBuffer StaticMeshVertexBuffer
The buffer containing vertex data.
int TriangleCount = 0
Number of triangles in this renderbuffer set.
TOptional< TArray< int > > Triangles
Optional list of triangles stored in this buffer.
FLocalVertexFactory VertexFactory
vertex factory
Protected Member Functions
void InitOrUpdateResource (FRHICommandListBase &RHICmdList, FRenderResource *Resource)
Initializes a render resource, or update it if already initialized.
void UpdateRaytracingGeometryIfEnabled ()
Detailed Description
FMeshRenderBufferSet stores a set of RenderBuffers for a mesh.
Definition at line 38 of file MeshRenderBufferSet.h.
Constructor & Destructor Documentation
FMeshRenderBufferSet()
FMeshRenderBufferSet::FMeshRenderBufferSet (ERHIFeatureLevel::Type FeatureLevelType) inline
Definition at line 97 of file MeshRenderBufferSet.h.
References EnumAddFlags(), IndexBuffer, SecondaryIndexBuffer, StaticMeshVertexBuffer, and VertexFactory.
Referenced by DestroyRenderBufferSet().
~FMeshRenderBufferSet()
virtual FMeshRenderBufferSet::~FMeshRenderBufferSet () inline virtual
Definition at line 109 of file MeshRenderBufferSet.h.
References bEnableRaytracing, ColorVertexBuffer, IndexBuffer, PositionVertexBuffer, FRenderResource::ReleaseResource(), SecondaryIndexBuffer, StaticMeshVertexBuffer, TriangleCount, and VertexFactory.
Member Function Documentation
DestroyRenderBufferSet()
void FMeshRenderBufferSet::DestroyRenderBufferSet (FMeshRenderBufferSet * BufferSet) inline static
Enqueue a command on the Render Thread to destroy the passed in buffer set.
At this point the buffer set should be considered invalid.
Definition at line 275 of file MeshRenderBufferSet.h.
References FMeshRenderBufferSet(), and TriangleCount.
InitOrUpdateResource()
void FMeshRenderBufferSet::InitOrUpdateResource (FRHICommandListBase & RHICmdList, FRenderResource * Resource) inline protected
Initializes a render resource, or update it if already initialized.
Warning
This function can only be called on the Render Thread
Definition at line 256 of file MeshRenderBufferSet.h.
References FRenderResource::InitResource(), FRenderResource::IsInitialized(), and FRenderResource::UpdateRHI().
Referenced by UploadIndexBufferUpdate().
InvalidateRayTracingData()
void FMeshRenderBufferSet::InvalidateRayTracingData () inline
Definition at line 186 of file MeshRenderBufferSet.h.
Referenced by UploadIndexBufferUpdate().
TransferVertexUpdateToGPU()
GEOMETRYFRAMEWORK_API void FMeshRenderBufferSet::TransferVertexUpdateToGPU (FRHICommandListBase & RHICmdList, bool bPositions, bool bNormals, bool bTexCoords, bool bColors)
Fast path to update various vertex buffers.
This path does not support changing the size/counts of any of the sub-buffers, a direct memcopy from the CPU-side buffer to the RHI buffer is used.
Warning
This can only be called on the Rendering Thread.
UpdateRaytracingGeometryIfEnabled()
void FMeshRenderBufferSet::UpdateRaytracingGeometryIfEnabled () inline protected
Definition at line 212 of file MeshRenderBufferSet.h.
References IndexBuffer, FIndexBuffer::IndexBufferRHI, FDynamicMeshIndexBuffer32::Indices, FRenderResource::InitResource(), MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), PositionVertexBuffer, FRenderResource::ReleaseResource(), SecondaryIndexBuffer, and Segment.
Referenced by ValidateRayTracingData().
Upload()
GEOMETRYFRAMEWORK_API void FMeshRenderBufferSet::Upload ()
Upload initialized mesh buffers.
Warning
This can only be called on the Rendering Thread.
UploadIndexBufferUpdate()
void FMeshRenderBufferSet::UploadIndexBufferUpdate () inline
Fast path to only update the primary and secondary index buffers.
This can be used when (eg) the secondary index buffer is being used to highlight/hide a subset of triangles.
Warning
This can only be called on the Rendering Thread.
Definition at line 150 of file MeshRenderBufferSet.h.
References bEnableSecondaryIndexBuffer, IndexBuffer, InitOrUpdateResource(), InvalidateRayTracingData(), SecondaryIndexBuffer, and ValidateRayTracingData().
UploadVertexUpdate()
GEOMETRYFRAMEWORK_API void FMeshRenderBufferSet::UploadVertexUpdate (bool bPositions, bool bMeshAttribs, bool bColors)
Fast path to only update vertex buffers.
This path rebuilds all the resources and reconfigures the vertex factory, so the counts/etc could be modified.
Warning
This can only be called on the Rendering Thread.
ValidateRayTracingData()
void FMeshRenderBufferSet::ValidateRayTracingData () inline
Definition at line 196 of file MeshRenderBufferSet.h.
References bEnableRaytracing, IsRayTracingEnabled(), and UpdateRaytracingGeometryIfEnabled().
Referenced by UploadIndexBufferUpdate().
Field Documentation
bEnableRaytracing
bool FMeshRenderBufferSet::bEnableRaytracing = false
configure whether raytracing should be enabled for this RenderBufferSet
Definition at line 79 of file MeshRenderBufferSet.h.
Referenced by ~FMeshRenderBufferSet(), and ValidateRayTracingData().
bEnableSecondaryIndexBuffer
bool FMeshRenderBufferSet::bEnableSecondaryIndexBuffer = false
If secondary index buffer is enabled, we populate this index buffer with additional triangles indexing into the same vertex buffers.
Definition at line 69 of file MeshRenderBufferSet.h.
Referenced by UploadIndexBufferUpdate().
BuffersLock
FCriticalSection FMeshRenderBufferSet::BuffersLock
In situations where we want to update the existing Vertex or Index buffers, we need to synchronize access between the Game and Render threads.
We use this lock to do that.
Definition at line 94 of file MeshRenderBufferSet.h.
ColorVertexBuffer
FColorVertexBuffer FMeshRenderBufferSet::ColorVertexBuffer
The buffer containing the vertex color data.
Definition at line 49 of file MeshRenderBufferSet.h.
Referenced by ~FMeshRenderBufferSet(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
IndexBuffer
FDynamicMeshIndexBuffer32 FMeshRenderBufferSet::IndexBuffer
triangle indices
Definition at line 52 of file MeshRenderBufferSet.h.
Referenced by FMeshRenderBufferSet(), ~FMeshRenderBufferSet(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), UpdateRaytracingGeometryIfEnabled(), and UploadIndexBufferUpdate().
Material
UMaterialInterface* FMeshRenderBufferSet::Material = nullptr
Material to draw this mesh with.
Definition at line 58 of file MeshRenderBufferSet.h.
PositionVertexBuffer
FPositionVertexBuffer FMeshRenderBufferSet::PositionVertexBuffer
The buffer containing the position vertex data.
Definition at line 47 of file MeshRenderBufferSet.h.
Referenced by ~FMeshRenderBufferSet(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), UpdateRaytracingGeometryIfEnabled(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
SecondaryIndexBuffer
FDynamicMeshIndexBuffer32 FMeshRenderBufferSet::SecondaryIndexBuffer
partition or subset of IndexBuffer that indexes into same vertex buffers
Definition at line 74 of file MeshRenderBufferSet.h.
Referenced by FMeshRenderBufferSet(), ~FMeshRenderBufferSet(), UpdateRaytracingGeometryIfEnabled(), and UploadIndexBufferUpdate().
StaticMeshVertexBuffer
FStaticMeshVertexBuffer FMeshRenderBufferSet::StaticMeshVertexBuffer
The buffer containing vertex data.
Definition at line 45 of file MeshRenderBufferSet.h.
Referenced by FMeshRenderBufferSet(), ~FMeshRenderBufferSet(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays().
TriangleCount
int FMeshRenderBufferSet::TriangleCount = 0
Number of triangles in this renderbuffer set.
Note that triangles may be split between IndexBuffer and SecondaryIndexBuffer.
Definition at line 42 of file MeshRenderBufferSet.h.
Referenced by ~FMeshRenderBufferSet(), DestroyRenderBufferSet(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays().
Triangles
TOptional<TArray<int> > FMeshRenderBufferSet::Triangles
Optional list of triangles stored in this buffer.
Storing this allows us to rebuild the buffers if vertex data changes.
Definition at line 64 of file MeshRenderBufferSet.h.
VertexFactory
FLocalVertexFactory FMeshRenderBufferSet::VertexFactory
vertex factory
Definition at line 55 of file MeshRenderBufferSet.h.
Referenced by FMeshRenderBufferSet(), and ~FMeshRenderBufferSet().
The documentation for this class was generated from the following file:
MeshRenderBufferSet.h