Unreal Engine 5.6 C++ API: FWorldPartitionActorDesc::FContainerInstance Struct Reference
FWorldPartitionActorDesc::FContainerInstance Struct Reference
#include "WorldPartitionActorDesc.h"
Public Member Functions
UE_DEPRECATED (5.4, "Use ContainerInstance instead") const UActorDescContainer *Container
UE_DEPRECATED (5.4, "Use FLoadedContainerInstance instead") bool bSupportsPartialEditorLoading
UE_DEPRECATED (5.4, "Use FLoadedContainerInstance instead") ULevel *LoadedLevel
Data Fields
EContainerClusterMode ClusterMode
UActorDescContainerInstance * ContainerInstance = nullptr
TMap< FActorContainerID, TSet< FGuid > > FilteredActors
FTransform Transform = FTransform::Identity
Detailed Description
Definition at line 253 of file WorldPartitionActorDesc.h.
Member Function Documentation
UE_DEPRECATED() [1/3]
FWorldPartitionActorDesc::FContainerInstance::UE_DEPRECATED (5. 4, "Use ContainerInstance instead") const
References FWorldPartitionActorDesc::Container, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FWorldPartitionActorDesc::FContainerInstance::UE_DEPRECATED (5. 4, "Use FLoadedContainerInstance instead")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FWorldPartitionActorDesc::FContainerInstance::UE_DEPRECATED (5. 4, "Use FLoadedContainerInstance instead")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
ClusterMode
EContainerClusterMode FWorldPartitionActorDesc::FContainerInstance::ClusterMode
Definition at line 257 of file WorldPartitionActorDesc.h.
ContainerInstance
UActorDescContainerInstance* FWorldPartitionActorDesc::FContainerInstance::ContainerInstance = nullptr
Definition at line 255 of file WorldPartitionActorDesc.h.
FilteredActors
TMap<FActorContainerID, TSet<FGuid> > FWorldPartitionActorDesc::FContainerInstance::FilteredActors
Definition at line 258 of file WorldPartitionActorDesc.h.
Transform
FTransform FWorldPartitionActorDesc::FContainerInstance::Transform = FTransform::Identity
Definition at line 256 of file WorldPartitionActorDesc.h.
The documentation for this struct was generated from the following file:
WorldPartitionActorDesc.h