Unreal Engine 5.6 C++ API: FRDGScatterUploadBuilder Class Reference
FRDGScatterUploadBuilder Class Reference
#include "UnifiedBuffer.h"
Data Structures
struct FPass
Public Types
using FPassFunction = TFunction<void(FRDGScatterUploader&)>
Public Member Functions
void AddPass (FRDGBuilder &GraphBuilder, FRDGAsyncScatterUploadBuffer &UploadBuffer, FRDGViewableResource *DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR *Name, FPassFunction &&Function)
Init with pre-existing destination index data, performs a bulk-copy.
void AddPass_PreSized (FRDGBuilder &GraphBuilder, FRDGAsyncScatterUploadBuffer &UploadBuffer, FRDGViewableResource *DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR *Name, FPassFunction &&Function)
Init with presized num scatters, expecting each to be set at a later point.
RENDERCORE_API UE::Tasks::FTask Execute (FRDGBuilder &GraphBuilder)
Static Public Member Functions
static RENDERCORE_API FRDGScatterUploadBuilder * Create (FRDGBuilder &GraphBuilder)
static UE::Tasks::FTask Process (FRDGBuilder &GraphBuilder, FRDGAsyncScatterUploadBuffer &UploadBuffer, FRDGViewableResource *DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR *Name, FPassFunction &&Function)
static UE::Tasks::FTask Process_PreSized (FRDGBuilder &GraphBuilder, FRDGAsyncScatterUploadBuffer &UploadBuffer, FRDGViewableResource *DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR *Name, FPassFunction &&Function)
Private Member Functions
FRDGScatterUploadBuilder ()=default
Private Attributes
uint32 MaxBytes = 0
TArray< FPass, SceneRenderingAllocator > Passes
Friends
class FRDGAllocator::TObject< FRDGScatterUploadBuilder >
Detailed Description
Definition at line 378 of file UnifiedBuffer.h.
Member Typedef Documentation
FPassFunction
using FRDGScatterUploadBuilder::FPassFunction = TFunction<void(FRDGScatterUploader&)>
Definition at line 381 of file UnifiedBuffer.h.
Constructor & Destructor Documentation
FRDGScatterUploadBuilder()
FRDGScatterUploadBuilder::FRDGScatterUploadBuilder () private default
Referenced by Create(), FRDGAllocator::TObject< FRDGScatterUploadBuilder >, Process(), and Process_PreSized().
Member Function Documentation
AddPass()
void FRDGScatterUploadBuilder::AddPass (FRDGBuilder & GraphBuilder, FRDGAsyncScatterUploadBuffer & UploadBuffer, FRDGViewableResource * DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR * Name, FPassFunction && Function) inline
Init with pre-existing destination index data, performs a bulk-copy.
Definition at line 414 of file UnifiedBuffer.h.
References FRDGAsyncScatterUploadBuffer::Begin(), Function, MaxBytes, MoveTemp(), Name, and Passes.
Referenced by Process().
AddPass_PreSized()
void FRDGScatterUploadBuilder::AddPass_PreSized (FRDGBuilder & GraphBuilder, FRDGAsyncScatterUploadBuffer & UploadBuffer, FRDGViewableResource * DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR * Name, FPassFunction && Function) inline
Init with presized num scatters, expecting each to be set at a later point.
Requires the user to keep track of the offsets to use.
Definition at line 428 of file UnifiedBuffer.h.
References FRDGAsyncScatterUploadBuffer::BeginPreSized(), Function, MaxBytes, MoveTemp(), Name, and Passes.
Referenced by Process_PreSized().
Create()
RENDERCORE_API FRDGScatterUploadBuilder * FRDGScatterUploadBuilder::Create (FRDGBuilder & GraphBuilder) static
References FRDGScatterUploadBuilder().
Execute()
RENDERCORE_API UE::Tasks::FTask FRDGScatterUploadBuilder::Execute (FRDGBuilder & GraphBuilder)
Referenced by Process(), and Process_PreSized().
Process()
UE::Tasks::FTask FRDGScatterUploadBuilder::Process (FRDGBuilder & GraphBuilder, FRDGAsyncScatterUploadBuffer & UploadBuffer, FRDGViewableResource * DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR * Name, FPassFunction && Function) inline static
Definition at line 383 of file UnifiedBuffer.h.
References FRDGScatterUploadBuilder(), AddPass(), Create, Execute(), Function, MoveTemp(), and Name.
Process_PreSized()
UE::Tasks::FTask FRDGScatterUploadBuilder::Process_PreSized (FRDGBuilder & GraphBuilder, FRDGAsyncScatterUploadBuffer & UploadBuffer, FRDGViewableResource * DstResource, uint32 NumElements, uint32 NumBytesPerElement, const TCHAR * Name, FPassFunction && Function) inline static
Definition at line 397 of file UnifiedBuffer.h.
References FRDGScatterUploadBuilder(), AddPass_PreSized(), Create, Execute(), Function, MoveTemp(), and Name.
Friends And Related Symbol Documentation
FRDGAllocator::TObject< FRDGScatterUploadBuilder >
friend class FRDGAllocator::TObject< FRDGScatterUploadBuilder > friend
Definition at line 460 of file UnifiedBuffer.h.
References FRDGScatterUploadBuilder(), and MaxBytes.
Field Documentation
MaxBytes
uint32 FRDGScatterUploadBuilder::MaxBytes = 0 private
Definition at line 460 of file UnifiedBuffer.h.
Referenced by AddPass(), AddPass_PreSized(), and FRDGAllocator::TObject< FRDGScatterUploadBuilder >.
Passes
TArray<FPass, SceneRenderingAllocator> FRDGScatterUploadBuilder::Passes private
Definition at line 459 of file UnifiedBuffer.h.
Referenced by AddPass(), and AddPass_PreSized().
The documentation for this class was generated from the following file:
UnifiedBuffer.h