Unreal Engine 5.6 C++ API: FMovieSceneChannelData Struct Reference
FMovieSceneChannelData Struct Reference
Base class channel data utility that provides a consistent interface to a sorted array of times and handles.
#include "MovieSceneChannelData.h"
Public Member Functions
MOVIESCENE_API int32 FindKey (FFrameNumber InTime, FFrameNumber InTolerance=0)
Attempt to find a key at a given time and tolerance.
MOVIESCENE_API void FindKeys (FFrameNumber InTime, int32 MaxNum, int32 &OutMinIndex, int32 &OutMaxIndex, int32 InTolerance)
Find the range of keys that fall around InTime +/- InTolerance up to a maximum.
MOVIESCENE_API FKeyHandle GetHandle (int32 Index)
Retrieve a key handle for the specified key time index.
MOVIESCENE_API int32 GetIndex (FKeyHandle Handle)
Attempt to retrieve the index of key from its handle.
MOVIESCENE_API void GetKeys (const TRange< FFrameNumber > &WithinRange, TArray< FFrameNumber > *OutKeyTimes, TArray< FKeyHandle > *OutKeyHandles)
Get all the keys in the given range.
MOVIESCENE_API void GetKeyTimes (TArrayView< const FKeyHandle > InHandles, TArrayView< FFrameNumber > OutKeyTimes)
Get key times for a number of keys in the channel data.
FORCEINLINE TArrayView< FFrameNumber > GetTimes ()
Mutable access to this channel's key times.
FORCEINLINE TArrayView< const FFrameNumber > GetTimes () const
Read-only access to this channel's key times.
MOVIESCENE_API TRange< FFrameNumber > GetTotalRange () const
Compute the total time range of the channel data.
MOVIESCENE_API void Offset (FFrameNumber DeltaTime)
Offset the channel data by a given delta time.
UE_DEPRECATED (5.6, "Please use RemapTimes") MOVIESCENE_API void ChangeFrameResolution(FFrameRate SourceRate
Convert the frame resolution of a movie scene channel by moving the key times to the equivalent frame time.
Data Fields
FFrameRate DestinationRate
Protected Member Functions
MOVIESCENE_API FMovieSceneChannelData (FMovieSceneChannel *InChannel, TArray< FFrameNumber > *InTimes, FKeyHandleLookupTable *InKeyHandles)
Constructor that takes a non-owning pointer to an array of times and a key handle map.
MOVIESCENE_API int32 AddKeyInternal (FFrameNumber InTime)
Add a new key at the specified time.
MOVIESCENE_API int32 MoveKeyInternal (int32 KeyIndex, FFrameNumber InNewTime)
Move the key at index KeyIndex to a new time.
UE_DEPRECATED (5.5, "Constructor that takes an optional FMovieSceneChannel is now deprecated. FMovieSceneChannel is now required.") MOVIESCENE_API FMovieSceneChannelData(TArray< FFrameNumber > *InTimes
Protected Attributes
FKeyHandleLookupTable FMovieSceneChannel * InChannel = nullptr)
FKeyHandleLookupTable * InKeyHandles
FKeyHandleLookupTable * KeyHandles
Pointer to an external key handle map.
FMovieSceneChannel * OwningChannel
Optional Pointer to the owning FMovieSceneChannel, should be set if the add,move, and delete callbacks are needed.
TArray< FFrameNumber > * Times
Pointer to an external array of sorted times.
Detailed Description
Base class channel data utility that provides a consistent interface to a sorted array of times and handles.
Complete access should be through TMovieSceneChannelData that allows mutation of the data
Definition at line 107 of file MovieSceneChannelData.h.
Constructor & Destructor Documentation
FMovieSceneChannelData()
MOVIESCENE_API FMovieSceneChannelData::FMovieSceneChannelData (FMovieSceneChannel * InChannel, TArray< FFrameNumber > * InTimes, FKeyHandleLookupTable * InKeyHandles) protected
Constructor that takes a non-owning pointer to an array of times and a key handle map.
Parameters
InTimes A pointer to an array that should be operated on by this class. Externally owned.
InKeyHandles A key handle map used for persistent, order independent identification of keys
InChannel A pointer to the owning channel.
References FMovieSceneChannelData(), InChannel, and InKeyHandles.
Referenced by FMovieSceneChannelData().
Member Function Documentation
AddKeyInternal()
MOVIESCENE_API int32 FMovieSceneChannelData::AddKeyInternal (FFrameNumber InTime) protected
Add a new key at the specified time.
Returns
The index of the key in its new position
References AddKeyInternal(), and InTime.
Referenced by AddKeyInternal().
FindKey()
MOVIESCENE_API int32 FMovieSceneChannelData::FindKey (FFrameNumber InTime, FFrameNumber InTolerance = 0)
Attempt to find a key at a given time and tolerance.
Parameters
InTime The time at which to search
InTolerance A tolerance of frame numbers to allow either side of the specified time
Returns
The index of the key closest to InTime and within InTolerance, or INDEX_NONE
References InTime.
FindKeys()
MOVIESCENE_API void FMovieSceneChannelData::FindKeys (FFrameNumber InTime, int32 MaxNum, int32 & OutMinIndex, int32 & OutMaxIndex, int32 InTolerance)
Find the range of keys that fall around InTime +/- InTolerance up to a maximum.
Parameters
InTime The time around which to search
MaxNum A maximum number of times to find, starting with those closest to the predicate time
OutMin The earliest index that met the conditions of the search
OutMax The latest index that met the conditions of the search
InTolerance The tolerance range to search around PredicateTime with
References InTime.
GetHandle()
MOVIESCENE_API FKeyHandle FMovieSceneChannelData::GetHandle (int32 Index)
Retrieve a key handle for the specified key time index.
Parameters
Index The index to retrieve
Returns
A key handle that identifies the key at the specified index, regardless of re-ordering
GetIndex()
MOVIESCENE_API int32 FMovieSceneChannelData::GetIndex (FKeyHandle Handle)
Attempt to retrieve the index of key from its handle.
Parameters
Handle The handle to retrieve
Returns
The index of the key, or INDEX_NONE
References Handle.
Referenced by AssignValue().
GetKeys()
MOVIESCENE_API void FMovieSceneChannelData::GetKeys (const TRange< FFrameNumber > & WithinRange, TArray< FFrameNumber > * OutKeyTimes, TArray< FKeyHandle > * OutKeyHandles)
Get all the keys in the given range.
Resulting arrays must be the same size where indices correspond to both arrays.
Parameters
WithinRange The bounds to get keys for
OutKeyTimes Array to receive all key times within the given range
OutKeyHandles Array to receive all key handles within the given range
References GetKeys().
Referenced by GetKeys().
GetKeyTimes()
MOVIESCENE_API void FMovieSceneChannelData::GetKeyTimes (TArrayView< const FKeyHandle > InHandles, TArrayView< FFrameNumber > OutKeyTimes)
Get key times for a number of keys in the channel data.
Parameters
InHandles Array of key handles that should have their times set
OutKeyTimes Array of times that should be set for each key handle. Must be exactly the size of InHandles
References GetKeyTimes().
Referenced by GetKeyTimes().
GetTimes() [1/2]
FORCEINLINE TArrayView< FFrameNumber > FMovieSceneChannelData::GetTimes () inline
Mutable access to this channel's key times.
Note
: Warning: any usage must keep times sorted. Any reordering of times will not be reflected in the values array.
Definition at line 121 of file MovieSceneChannelData.h.
References FORCEINLINE, and Times.
GetTimes() [2/2]
FORCEINLINE TArrayView< const FFrameNumber > FMovieSceneChannelData::GetTimes () const inline
Read-only access to this channel's key times.
Definition at line 112 of file MovieSceneChannelData.h.
References FORCEINLINE, and Times.
GetTotalRange()
MOVIESCENE_API TRange< FFrameNumber > FMovieSceneChannelData::GetTotalRange () const
Compute the total time range of the channel data.
Returns
The range of this channel data
MoveKeyInternal()
MOVIESCENE_API int32 FMovieSceneChannelData::MoveKeyInternal (int32 KeyIndex, FFrameNumber InNewTime) protected
Move the key at index KeyIndex to a new time.
Returns
The index of the key in its new position
References MoveKeyInternal().
Referenced by MoveKeyInternal().
Offset()
MOVIESCENE_API void FMovieSceneChannelData::Offset (FFrameNumber DeltaTime)
Offset the channel data by a given delta time.
Parameters
DeltaTime The time to offset by
References DeltaTime, and Offset().
Referenced by Offset().
UE_DEPRECATED() [1/2]
FMovieSceneChannelData::UE_DEPRECATED (5. 5, "Constructor that takes an optional FMovieSceneChannel is now deprecated. FMovieSceneChannel is now required.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FMovieSceneChannelData::UE_DEPRECATED (5. 6, "Please use RemapTimes")
Convert the frame resolution of a movie scene channel by moving the key times to the equivalent frame time.
Parameters
SourceRate The frame rate the channel is currently in
DestinationRate The new frame rate to convert the channel to
Referenced by UE_DEPRECATED().
Field Documentation
DestinationRate
FFrameRate FMovieSceneChannelData::DestinationRate
Definition at line 176 of file MovieSceneChannelData.h.
InChannel
FKeyHandleLookupTable FMovieSceneChannel* FMovieSceneChannelData::InChannel = nullptr) protected
Definition at line 214 of file MovieSceneChannelData.h.
Referenced by FMovieSceneChannelData().
InKeyHandles
FKeyHandleLookupTable* FMovieSceneChannelData::InKeyHandles protected
Definition at line 214 of file MovieSceneChannelData.h.
Referenced by FMovieSceneChannelData().
KeyHandles
FKeyHandleLookupTable* FMovieSceneChannelData::KeyHandles protected
Pointer to an external key handle map.
Definition at line 237 of file MovieSceneChannelData.h.
OwningChannel
FMovieSceneChannel* FMovieSceneChannelData::OwningChannel protected
Optional Pointer to the owning FMovieSceneChannel, should be set if the add,move, and delete callbacks are needed.
Definition at line 240 of file MovieSceneChannelData.h.
Times
TArray<FFrameNumber>* FMovieSceneChannelData::Times protected
Pointer to an external array of sorted times.
Must be kept in sync with a corresponding value array.
Definition at line 234 of file MovieSceneChannelData.h.
Referenced by GetTimes(), and GetTimes().
The documentation for this struct was generated from the following file:
MovieSceneChannelData.h