Unreal Engine 5.6 C++ API: UE::Tasks::FTaskConcurrencyLimiter Class Reference
UE::Tasks::FTaskConcurrencyLimiter Class Reference
A lightweight construct that limits the concurrency of tasks pushed into it.
#include "TaskConcurrencyLimiter.h"
Public Member Functions
FTaskConcurrencyLimiter (uint32 MaxConcurrency, ETaskPriority TaskPriority=ETaskPriority::Default)
Constructor.
template<typename TaskFunctionType>
void Push (const TCHAR *DebugName, TaskFunctionType &&TaskFunction)
Push a new task.
bool Wait (FTimespan Timeout=FTimespan::MaxValue())
Waits for task's completion with timeout.
Private Attributes
TSharedRef< TaskConcurrencyLimiter_Private::FPimpl > Pimpl
Detailed Description
A lightweight construct that limits the concurrency of tasks pushed into it.
Note
This class supports being destroyed before the tasks it contains are finished.
Definition at line 116 of file TaskConcurrencyLimiter.h.
Constructor & Destructor Documentation
FTaskConcurrencyLimiter()
UE::Tasks::FTaskConcurrencyLimiter::FTaskConcurrencyLimiter (uint32 MaxConcurrency, ETaskPriority TaskPriority = ETaskPriority::Default) inline explicit
Constructor.
Parameters
MaxConcurrency How wide the processing can go.
TaskPriority Priority the tasks will be launched with.
Definition at line 125 of file TaskConcurrencyLimiter.h.
References MakeShared(), and Pimpl.
Member Function Documentation
Push()
template<typename TaskFunctionType> void UE::Tasks::FTaskConcurrencyLimiter::Push (const TCHAR * DebugName, TaskFunctionType && TaskFunction) inline
Push a new task.
Parameters
DebugName Helps to identify the task in debugger and profiler.
TaskFunction A callable with a slot parameter, usually a lambda but can be also a functor object or a pointer to a function. The slot parameter is an index in [0..max_concurrency) range, unique at any moment of time, that can be used in user code to index a fixed-size buffer. See TaskConcurrencyLimiterStressTest() for an example.
Definition at line 140 of file TaskConcurrencyLimiter.h.
References MoveTemp(), and Pimpl.
Wait()
bool UE::Tasks::FTaskConcurrencyLimiter::Wait (FTimespan Timeout = FTimespan::MaxValue()) inline
Waits for task's completion with timeout.
Parameters
Timeout Maximum amount of time to wait for tasks to finish before returning.
Returns
true if all tasks are completed, false otherwise.
Note
A wait is satisfied once the internal task counter reaches 0 and is never reset afterward when more tasks are added. A new FTaskConcurrencyLimiter can be used for such a use case.
Definition at line 155 of file TaskConcurrencyLimiter.h.
References FTimespan::MaxValue(), Pimpl, and UE::Tasks::Timeout.
Field Documentation
Pimpl
TSharedRef<TaskConcurrencyLimiter_Private::FPimpl> UE::Tasks::FTaskConcurrencyLimiter::Pimpl private
Definition at line 161 of file TaskConcurrencyLimiter.h.
Referenced by FTaskConcurrencyLimiter(), Push(), and Wait().
The documentation for this class was generated from the following file:
TaskConcurrencyLimiter.h