Unreal Engine 5.6 C++ API: TSelectionIterator< SelectionFilter > Class Template Reference
TSelectionIterator< SelectionFilter > Class Template Reference
Manages selections of objects.
#include "Selection.h"
Public Member Functions
TSelectionIterator (USelection &InSelection)
int32 GetIndex () const
Returns an index to the current element.
operator bool () const
Returns true if the iterator has not yet reached the end of the selection set.
UObject * operator* () const
Element access.
void operator++ ()
Advances iterator to the next valid element in the container.
UObject * operator-> () const
Element access.
void Reset ()
Resets the iterator to the beginning of the selection set.
Private Member Functions
UObject * GetCurrentObject () const
bool IsIndexValid () const
bool IsObjectValid () const
Private Attributes
SelectionFilter Filter
int32 Index
USelection & Selection
Detailed Description
template<typename SelectionFilter>
class TSelectionIterator< SelectionFilter >
Manages selections of objects.
Used in the editor for selecting objects in the various browser windows.
Definition at line 381 of file Editor/UnrealEd/Public/Selection.h.
Constructor & Destructor Documentation
TSelectionIterator()
template<typename SelectionFilter> TSelectionIterator< SelectionFilter >::TSelectionIterator (USelection & InSelection) inline
Definition at line 384 of file Editor/UnrealEd/Public/Selection.h.
References Filter, Reset(), and Selection.
Member Function Documentation
GetCurrentObject()
template<typename SelectionFilter> UObject * TSelectionIterator< SelectionFilter >::GetCurrentObject () const inline private
Definition at line 444 of file Editor/UnrealEd/Public/Selection.h.
References Index, and Selection.
Referenced by IsObjectValid(), operator*(), and operator->().
GetIndex()
template<typename SelectionFilter> int32 TSelectionIterator< SelectionFilter >::GetIndex () const inline
Returns an index to the current element.
Definition at line 438 of file Editor/UnrealEd/Public/Selection.h.
References Index.
IsIndexValid()
template<typename SelectionFilter> bool TSelectionIterator< SelectionFilter >::IsIndexValid () const inline private
Definition at line 454 of file Editor/UnrealEd/Public/Selection.h.
References Index, and Selection.
Referenced by operator bool(), and operator++().
IsObjectValid()
template<typename SelectionFilter> bool TSelectionIterator< SelectionFilter >::IsObjectValid () const inline private
Definition at line 449 of file Editor/UnrealEd/Public/Selection.h.
References Filter, and GetCurrentObject().
Referenced by operator++().
operator bool()
template<typename SelectionFilter> TSelectionIterator< SelectionFilter >::operator bool () const inline explicit
Returns true if the iterator has not yet reached the end of the selection set.
Definition at line 425 of file Editor/UnrealEd/Public/Selection.h.
References IsIndexValid().
operator*()
template<typename SelectionFilter> UObject * TSelectionIterator< SelectionFilter >::operator* () const inline
Element access.
Definition at line 413 of file Editor/UnrealEd/Public/Selection.h.
References GetCurrentObject().
operator++()
template<typename SelectionFilter> void TSelectionIterator< SelectionFilter >::operator++ () inline
Advances iterator to the next valid element in the container.
Definition at line 392 of file Editor/UnrealEd/Public/Selection.h.
References Index, IsIndexValid(), and IsObjectValid().
operator->()
template<typename SelectionFilter> UObject * TSelectionIterator< SelectionFilter >::operator-> () const inline
Element access.
Definition at line 419 of file Editor/UnrealEd/Public/Selection.h.
References GetCurrentObject().
Reset()
template<typename SelectionFilter> void TSelectionIterator< SelectionFilter >::Reset () inline
Resets the iterator to the beginning of the selection set.
Definition at line 431 of file Editor/UnrealEd/Public/Selection.h.
References Index.
Referenced by TSelectionIterator().
Field Documentation
Filter
template<typename SelectionFilter> SelectionFilter TSelectionIterator< SelectionFilter >::Filter private
Definition at line 460 of file Editor/UnrealEd/Public/Selection.h.
Referenced by TSelectionIterator(), and IsObjectValid().
Index
template<typename SelectionFilter> int32 TSelectionIterator< SelectionFilter >::Index private
Definition at line 461 of file Editor/UnrealEd/Public/Selection.h.
Referenced by GetCurrentObject(), GetIndex(), IsIndexValid(), operator++(), and Reset().
Selection
template<typename SelectionFilter> USelection& TSelectionIterator< SelectionFilter >::Selection private
Definition at line 459 of file Editor/UnrealEd/Public/Selection.h.
Referenced by TSelectionIterator(), GetCurrentObject(), and IsIndexValid().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Selection.h