Unreal Engine 5.6 C++ API: UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes > Struct Template Reference
UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
template<typename... ArgTypes>
TScheduledEntityTask (const TEntityTaskComponents< ComponentTypes... > &InComponents, ArgTypes &&... InArgs)
void PostTask () const
void PreTask () const
Public Member Functions inherited from UE::MovieScene::ITaskContext
virtual ~ITaskContext ()
Static Public Member Functions
static void ScheduledRun_PerAllocation (FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, const ITaskContext *Context, FEntityAllocationWriteContext WriteContext)
static void ScheduledRun_PerEntity (FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, const ITaskContext *Context, FEntityAllocationWriteContext WriteContext)
Private Types
using Caller = TEntityTaskCaller<sizeof...(ComponentTypes), TEntityTaskTraits<TaskImpl>::AutoExpandAccessors >
Static Private Member Functions
template<typename T>
static void PostTaskImpl (T *InTask, decltype(&T::PostTask) *=0)
static void PostTaskImpl (void *,...)
template<typename T>
static void PreTaskImpl (T *InTask, decltype(&T::PreTask) *=0)
static void PreTaskImpl (void *,...)
Private Attributes
TEntityTaskComponents< ComponentTypes... > Components
TaskImpl TaskImplInstance
Detailed Description
template<typename TaskImpl, typename... ComponentTypes>
struct UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >
Definition at line 1644 of file MovieSceneEntitySystemTask.h.
Member Typedef Documentation
Caller
template<typename TaskImpl, typename... ComponentTypes> using UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::Caller = TEntityTaskCaller<sizeof...(ComponentTypes), TEntityTaskTraits<TaskImpl>::AutoExpandAccessors > private
Definition at line 1687 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TScheduledEntityTask()
template<typename TaskImpl, typename... ComponentTypes> template<typename... ArgTypes> UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::TScheduledEntityTask (const TEntityTaskComponents< ComponentTypes... > & InComponents, ArgTypes &&... InArgs) inline explicit
Definition at line 1647 of file MovieSceneEntitySystemTask.h.
References Components, Forward(), and TaskImplInstance.
Referenced by ScheduledRun_PerAllocation(), and ScheduledRun_PerEntity().
Member Function Documentation
PostTask()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PostTask () const inline
Definition at line 1657 of file MovieSceneEntitySystemTask.h.
References PostTaskImpl(), and TaskImplInstance.
PostTaskImpl() [1/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename T> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PostTaskImpl (T * InTask, decltype &::PostTask * = 0) inline static private
Definition at line 1682 of file MovieSceneEntitySystemTask.h.
PostTaskImpl() [2/2]
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PostTaskImpl (void * , ...) inline static private
Definition at line 1681 of file MovieSceneEntitySystemTask.h.
Referenced by PostTask().
PreTask()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PreTask () const inline
Definition at line 1652 of file MovieSceneEntitySystemTask.h.
References PreTaskImpl(), and TaskImplInstance.
PreTaskImpl() [1/2]
template<typename TaskImpl, typename... ComponentTypes> template<typename T> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PreTaskImpl (T * InTask, decltype &::PreTask * = 0) inline static private
Definition at line 1676 of file MovieSceneEntitySystemTask.h.
PreTaskImpl() [2/2]
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::PreTaskImpl (void * , ...) inline static private
Definition at line 1675 of file MovieSceneEntitySystemTask.h.
Referenced by PreTask().
ScheduledRun_PerAllocation()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerAllocation (FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, const ITaskContext * Context, FEntityAllocationWriteContext WriteContext) inline static
Definition at line 1668 of file MovieSceneEntitySystemTask.h.
References TScheduledEntityTask(), Item, and UE::MovieScene::This.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::Fork_PerAllocation(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerAllocation(), and UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerAllocation().
ScheduledRun_PerEntity()
template<typename TaskImpl, typename... ComponentTypes> void UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerEntity (FEntityAllocationIteratorItem Item, TArrayView< const FPreLockedDataPtr > PreLockedData, const ITaskContext * Context, FEntityAllocationWriteContext WriteContext) inline static
Definition at line 1663 of file MovieSceneEntitySystemTask.h.
References TScheduledEntityTask(), Item, and UE::MovieScene::This.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::Fork_PerEntity(), UE::MovieScene::TFilteredEntityTask< T >::Fork_PerEntity(), UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerEntity(), and UE::MovieScene::TFilteredEntityTask< T >::Schedule_PerEntity().
Field Documentation
Components
template<typename TaskImpl, typename... ComponentTypes> TEntityTaskComponents<ComponentTypes...> UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::Components private
Definition at line 1690 of file MovieSceneEntitySystemTask.h.
Referenced by TScheduledEntityTask().
TaskImplInstance
template<typename TaskImpl, typename... ComponentTypes> TaskImpl UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::TaskImplInstance private
Definition at line 1689 of file MovieSceneEntitySystemTask.h.
Referenced by TScheduledEntityTask(), PostTask(), and PreTask().
The documentation for this struct was generated from the following file:
MovieSceneEntitySystemTask.h