Unreal Engine 5.6 C++ API: FSnappedPositioningData Struct Reference
FSnappedPositioningData Struct Reference
Structure used for positioning actors with snapping.
#include "ActorPositioning.h"
Public Member Functions
FSnappedPositioningData (FLevelEditorViewportClient *InLevelViewportClient, const FVector &InSurfaceLocation, const FVector &InSurfaceNormal)
FSnappedPositioningData & AlignToSurfaceRotation (bool bInAlignRotation)
FSnappedPositioningData & DrawSnapHelpers (bool bInDrawSnapHelpers)
Whether to draw vertex snapping helpers or not when snapping.
FSnappedPositioningData & UseFactory (const UActorFactory *InActorFactory)
FSnappedPositioningData & UsePlacementExtent (const FVector &InPlacementExtent)
Mask these construction helpers to return the correct type.
FSnappedPositioningData & UseStartTransform (const FTransform &InStartTransform)
Public Member Functions inherited from FPositioningData
FPositioningData (const FVector &InSurfaceLocation, const FVector &InSurfaceNormal)
FPositioningData & AlignToSurfaceRotation (bool bInAlignRotation)
Whether to align to the surface normal, or just snap to its position.
FPositioningData & UseFactory (const UActorFactory *InActorFactory)
A factory to use for the alignment.
FPositioningData & UsePlacementExtent (const FVector &InPlacementExtent)
Placement extent offset to use (default = 0,0,0)
FPositioningData & UseStartTransform (const FTransform &InStartTransform)
The start transform we are using for positioning.
Data Fields
bool bDrawSnapHelpers
FLevelEditorViewportClient * LevelViewportClient
The level viewport - required for vertex snapping routines.
Data Fields inherited from FPositioningData
const UActorFactory * ActorFactory
bool bAlignRotation
FVector PlacementExtent
FTransform StartTransform
FVector SurfaceLocation
The surface location we want to position to.
FVector SurfaceNormal
The surface normal we want to potentially align to.
Detailed Description
Structure used for positioning actors with snapping.
Definition at line 53 of file ActorPositioning.h.
Constructor & Destructor Documentation
FSnappedPositioningData()
FSnappedPositioningData::FSnappedPositioningData (FLevelEditorViewportClient * InLevelViewportClient, const FVector & InSurfaceLocation, const FVector & InSurfaceNormal) inline
Definition at line 55 of file ActorPositioning.h.
References FPositioningData::FPositioningData(), bDrawSnapHelpers, FVector, and LevelViewportClient.
Referenced by AlignToSurfaceRotation(), DrawSnapHelpers(), UseFactory(), UsePlacementExtent(), and UseStartTransform().
Member Function Documentation
AlignToSurfaceRotation()
FSnappedPositioningData & FSnappedPositioningData::AlignToSurfaceRotation (bool bInAlignRotation) inline
Definition at line 72 of file ActorPositioning.h.
References FSnappedPositioningData(), and FPositioningData::bAlignRotation.
DrawSnapHelpers()
FSnappedPositioningData & FSnappedPositioningData::DrawSnapHelpers (bool bInDrawSnapHelpers) inline
Whether to draw vertex snapping helpers or not when snapping.
Definition at line 65 of file ActorPositioning.h.
References FSnappedPositioningData(), and bDrawSnapHelpers.
UseFactory()
FSnappedPositioningData & FSnappedPositioningData::UseFactory (const UActorFactory * InActorFactory) inline
Definition at line 71 of file ActorPositioning.h.
References FSnappedPositioningData(), and FPositioningData::ActorFactory.
UsePlacementExtent()
FSnappedPositioningData & FSnappedPositioningData::UsePlacementExtent (const FVector & InPlacementExtent) inline
Mask these construction helpers to return the correct type.
Definition at line 69 of file ActorPositioning.h.
References FSnappedPositioningData(), FVector, and FPositioningData::PlacementExtent.
UseStartTransform()
FSnappedPositioningData & FSnappedPositioningData::UseStartTransform (const FTransform & InStartTransform) inline
Definition at line 70 of file ActorPositioning.h.
References FSnappedPositioningData(), and FPositioningData::StartTransform.
Field Documentation
bDrawSnapHelpers
bool FSnappedPositioningData::bDrawSnapHelpers
Definition at line 66 of file ActorPositioning.h.
Referenced by FSnappedPositioningData(), and DrawSnapHelpers().
LevelViewportClient
FLevelEditorViewportClient* FSnappedPositioningData::LevelViewportClient
The level viewport - required for vertex snapping routines.
Definition at line 62 of file ActorPositioning.h.
Referenced by FSnappedPositioningData().
The documentation for this struct was generated from the following file:
ActorPositioning.h