Unreal Engine 5.6 C++ API: UE::Anim::Attributes Struct Reference
UE::Anim::Attributes Struct Reference
Helper functionality for attributes animation runtime.
#include "AttributesRuntime.h"
Public Member Functions
UE_DEPRECATED (5.1, "GetAttributeValue with signature using FAnimExtractContext is deprecated use other version instead") static 1 void GetAttributeValue(FStackAttributeContainer &OutAttributes
UE_DEPRECATED (5.2, "MirrorAttributes has been deprecated, use other signature instead") static 1 void MirrorAttributes(FStackAttributeContainer &Attributes
Static Public Member Functions
static void AccumulateAttributes (const FStackAttributeContainer &SourceAttributes, FStackAttributeContainer &OutAttributes, float Weight, EAdditiveAnimationType AdditiveType)
Add any new or accumulate with existing custom attributes.
static void BlendAttributes (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, FStackAttributeContainer &OutAttributes)
Blend custom attribute values from N set of inputs (ptr-values)
static void BlendAttributes (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, FStackAttributeContainer &OutAttributes)
Blend custom attribute values from N set of inputs, using input weight remapping.
static void BlendAttributes (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, FStackAttributeContainer &OutAttributes)
Blend custom attribute values from N set of inputs.
static void BlendAttributesPerBone (const FStackAttributeContainer &SourceAttributes1, const FStackAttributeContainer &SourceAttributes2, const TArrayView< const float > WeightsOfSource2, FStackAttributeContainer &OutAttributes)
static void BlendAttributesPerBone (TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > PerBoneInterpolationIndices, TArrayView< const FBlendSampleData > BlendSampleDataCache, FStackAttributeContainer &OutAttributes)
static void BlendAttributesPerBone (TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > PerBoneInterpolationIndices, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, FStackAttributeContainer &OutAttributes)
static void BlendAttributesPerBoneFilter (const FStackAttributeContainer &BaseAttributes, const TArrayView< const FStackAttributeContainer > BlendAttributes, const TArray< FPerBoneBlendWeight > &BoneBlendWeights, FStackAttributeContainer &OutAttributes)
static void ConvertToAdditive (const FStackAttributeContainer &BaseAttributes, FStackAttributeContainer &OutAdditiveAttributes)
Add (negated) any new or subtract from existing custom attributes.
static void CopyAndRemapAttributes (const FMeshAttributeContainer &SourceAttributes, FStackAttributeContainer &OutAttributes, const TMap< int32, int32 > &BoneMapToSource, const FBoneContainer &RequiredBones)
Copy attributes from source, and remap the bone indices according to BoneMapToSource.
static ECustomAttributeBlendType GetAttributeBlendType (const FAttributeId &Info)
Helper functionality to retrieve the correct blend type (from UAnimationSettings) for the provided attribute info.
static ECustomAttributeBlendType GetAttributeBlendType (const FName &InName)
Helper functionality to retrieve the correct blend type (from UAnimationSettings) for the provided attribute name.
static void GetAttributeValue (FStackAttributeContainer &OutAttributes, const FCompactPoseBoneIndex &PoseBoneIndex, const FAnimatedBoneAttribute &Attribute, double CurrentTime)
static void InterpolateAttributes (FMeshAttributeContainer &FromAttributes, const FMeshAttributeContainer &ToAttributes, float Alpha)
Interpolates between two sets of attributes.
static void MirrorAttributes (FStackAttributeContainer &Attributes, const UMirrorDataTable &MirrorDataTable, const TArray< FCompactPoseBoneIndex > &CompactPoseMirrorBones)
Mirror (swap) attributes with the specified MirrorDataTable.
static void OverrideAttributes (const FStackAttributeContainer &SourceAttributes, FStackAttributeContainer &OutAttributes, float Weight)
Add any new or override existing custom attributes.
Data Fields
const FCompactPoseBoneIndex const FAnimatedBoneAttribute & Attribute
const FCompactPoseBoneIndex const FAnimatedBoneAttribute const FAnimExtractContext & ExtractionContext
const UMirrorDataTable & MirrorDataTable
const FCompactPoseBoneIndex & PoseBoneIndex
Detailed Description
Helper functionality for attributes animation runtime.
Definition at line 56 of file AttributesRuntime.h.
Member Function Documentation
AccumulateAttributes()
void UE::Anim::Attributes::AccumulateAttributes (const FStackAttributeContainer & SourceAttributes, FStackAttributeContainer & OutAttributes, float Weight, EAdditiveAnimationType AdditiveType) static
Add any new or accumulate with existing custom attributes.
References Weight.
BlendAttributes() [1/3]
void UE::Anim::Attributes::BlendAttributes (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, FStackAttributeContainer & OutAttributes) static
Blend custom attribute values from N set of inputs (ptr-values)
BlendAttributes() [2/3]
void UE::Anim::Attributes::BlendAttributes (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, FStackAttributeContainer & OutAttributes) static
Blend custom attribute values from N set of inputs, using input weight remapping.
BlendAttributes() [3/3]
void UE::Anim::Attributes::BlendAttributes (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, FStackAttributeContainer & OutAttributes) static
Blend custom attribute values from N set of inputs.
Referenced by BlendAttributesPerBoneFilter().
BlendAttributesPerBone() [1/3]
void UE::Anim::Attributes::BlendAttributesPerBone (const FStackAttributeContainer & SourceAttributes1, const FStackAttributeContainer & SourceAttributes2, const TArrayView< const float > WeightsOfSource2, FStackAttributeContainer & OutAttributes) static
BlendAttributesPerBone() [2/3]
void UE::Anim::Attributes::BlendAttributesPerBone (TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > PerBoneInterpolationIndices, TArrayView< const FBlendSampleData > BlendSampleDataCache, FStackAttributeContainer & OutAttributes) static
BlendAttributesPerBone() [3/3]
void UE::Anim::Attributes::BlendAttributesPerBone (TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > PerBoneInterpolationIndices, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, FStackAttributeContainer & OutAttributes) static
BlendAttributesPerBoneFilter()
void UE::Anim::Attributes::BlendAttributesPerBoneFilter (const FStackAttributeContainer & BaseAttributes, const TArrayView< const FStackAttributeContainer > BlendAttributes, const TArray< FPerBoneBlendWeight > & BoneBlendWeights, FStackAttributeContainer & OutAttributes) static
References BlendAttributes().
ConvertToAdditive()
void UE::Anim::Attributes::ConvertToAdditive (const FStackAttributeContainer & BaseAttributes, FStackAttributeContainer & OutAdditiveAttributes) static
Add (negated) any new or subtract from existing custom attributes.
CopyAndRemapAttributes()
void UE::Anim::Attributes::CopyAndRemapAttributes (const FMeshAttributeContainer & SourceAttributes, FStackAttributeContainer & OutAttributes, const TMap< int32, int32 > & BoneMapToSource, const FBoneContainer & RequiredBones) static
Copy attributes from source, and remap the bone indices according to BoneMapToSource.
GetAttributeBlendType() [1/2]
ECustomAttributeBlendType UE::Anim::Attributes::GetAttributeBlendType (const FAttributeId & Info) static
Helper functionality to retrieve the correct blend type (from UAnimationSettings) for the provided attribute info.
References GetAttributeBlendType(), Info, and UE_DEPRECATED().
GetAttributeBlendType() [2/2]
ECustomAttributeBlendType UE::Anim::Attributes::GetAttributeBlendType (const FName & InName) static
Helper functionality to retrieve the correct blend type (from UAnimationSettings) for the provided attribute name.
References GetAttributeBlendType(), and InName.
Referenced by UE::Anim::FNonBlendableAttributeBlendOperator::Blend(), UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal(), GetAttributeBlendType(), and GetAttributeBlendType().
GetAttributeValue()
void UE::Anim::Attributes::GetAttributeValue (FStackAttributeContainer & OutAttributes, const FCompactPoseBoneIndex & PoseBoneIndex, const FAnimatedBoneAttribute & Attribute, double CurrentTime) static
References Attribute, GetAttributeValue(), and PoseBoneIndex.
Referenced by GetAttributeValue().
InterpolateAttributes()
void UE::Anim::Attributes::InterpolateAttributes (FMeshAttributeContainer & FromAttributes, const FMeshAttributeContainer & ToAttributes, float Alpha) static
Interpolates between two sets of attributes.
References Alpha.
MirrorAttributes()
void UE::Anim::Attributes::MirrorAttributes (FStackAttributeContainer & Attributes, const UMirrorDataTable & MirrorDataTable, const TArray< FCompactPoseBoneIndex > & CompactPoseMirrorBones) static
Mirror (swap) attributes with the specified MirrorDataTable.
Attributes are swapped using the bone mapping such that bones which are mirrored swap attributes
References MirrorDataTable.
OverrideAttributes()
void UE::Anim::Attributes::OverrideAttributes (const FStackAttributeContainer & SourceAttributes, FStackAttributeContainer & OutAttributes, float Weight) static
Add any new or override existing custom attributes.
References Weight.
UE_DEPRECATED() [1/2]
UE::Anim::Attributes::UE_DEPRECATED (5. 1, "GetAttributeValue with signature using FAnimExtractContext is deprecated use other version instead") &
Referenced by GetAttributeBlendType().
UE_DEPRECATED() [2/2]
UE::Anim::Attributes::UE_DEPRECATED (5. 2, "MirrorAttributes has been deprecated, use other signature instead") &
Field Documentation
Attribute
const FCompactPoseBoneIndex const FAnimatedBoneAttribute& UE::Anim::Attributes::Attribute
Definition at line 60 of file AttributesRuntime.h.
Referenced by GetAttributeValue().
ExtractionContext
const FCompactPoseBoneIndex const FAnimatedBoneAttribute const FAnimExtractContext& UE::Anim::Attributes::ExtractionContext
Definition at line 60 of file AttributesRuntime.h.
MirrorDataTable
const UMirrorDataTable& UE::Anim::Attributes::MirrorDataTable
Definition at line 105 of file AttributesRuntime.h.
Referenced by MirrorAttributes().
PoseBoneIndex
const FCompactPoseBoneIndex& UE::Anim::Attributes::PoseBoneIndex
Definition at line 60 of file AttributesRuntime.h.
Referenced by GetAttributeValue().
The documentation for this struct was generated from the following file:
AttributesRuntime.h