Unreal Engine 5.6 C++ API: UVirtualTexturePoolConfig Class Reference
UVirtualTexturePoolConfig Class Reference
#include "VirtualTexturePoolConfig.h"
Private Member Functions
bool AddOrModifyTransientPoolConfig (FVirtualTextureSpacePoolConfig const &InConfig)
Add a transient config.
void FindPoolConfig (TEnumAsByte< EPixelFormat > const *InFormats, int32 InNumLayers, int32 InTileSize, FVirtualTextureSpacePoolConfig &OutConfig) const
Find a matching config by first searching the TransientPools and then the Pools.
GENERATED_UCLASS_BODY () UPROPERTY() int32 DefaultSizeInMegabyte
Upper size limit in megabytes for any pools not explicitly matched by a config entry in the Pools array.
void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
UPROPERTY () bool bPoolAutoGrowInEditor
Enable physical pools growing on oversubscription.
UPROPERTY ()) TArray< FVirtualTextureSpacePoolConfig > Pools
Serialized array of configs.
UPROPERTY ()) TArray< FVirtualTextureSpacePoolConfig > TransientPools
Transient array of runtime detected configs used by the PoolAutoGrow system.
Detailed Description
Definition at line 58 of file VirtualTexturePoolConfig.h.
Member Function Documentation
AddOrModifyTransientPoolConfig()
bool UVirtualTexturePoolConfig::AddOrModifyTransientPoolConfig (FVirtualTextureSpacePoolConfig const & InConfig) private
Add a transient config.
If there is already a matching config, then this will just copy the SizeInMegabyte setting to the existing config. Returns false if no change is made.
References AddOrModifyTransientPoolConfig().
Referenced by AddOrModifyTransientPoolConfig().
FindPoolConfig()
void UVirtualTexturePoolConfig::FindPoolConfig (TEnumAsByte< EPixelFormat > const * InFormats, int32 InNumLayers, int32 InTileSize, FVirtualTextureSpacePoolConfig & OutConfig) const private
Find a matching config by first searching the TransientPools and then the Pools.
References FindPoolConfig().
Referenced by FindPoolConfig().
GENERATED_UCLASS_BODY()
UVirtualTexturePoolConfig::GENERATED_UCLASS_BODY () private
Upper size limit in megabytes for any pools not explicitly matched by a config entry in the Pools array.
References Category, config, and UPROPERTY().
PostEditChangeProperty()
void UVirtualTexturePoolConfig::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override private
UPROPERTY() [1/3]
UVirtualTexturePoolConfig::UPROPERTY () private
Enable physical pools growing on oversubscription.
Each physical pool will grow to the maximum size so far requested. This setting applies to the editor only. To have similar behavior in a cooked build use r.VT.PoolAutoGrow.
References Category, config, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/3]
UVirtualTexturePoolConfig::UPROPERTY () private
Serialized array of configs.
A virtual texture physical pool iterates these from last to first and uses the first matching config that it finds.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [3/3]
UVirtualTexturePoolConfig::UPROPERTY () private
Transient array of runtime detected configs used by the PoolAutoGrow system.
A virtual texture physical pool searches these to find a match before searching the configs in Pools. These tracked configs can be copied to the serialized Pools as a good estimation of the fixed pool sizes that a cooked project needs.
References Category, meta, Transient, and UPROPERTY().
The documentation for this class was generated from the following file:
VirtualTexturePoolConfig.h