Unreal Engine 5.6 C++ API: UE::Geometry::FRefCountVector::BaseIterator Class Reference
UE::Geometry::FRefCountVector::BaseIterator Class Reference
base iterator for indices with valid refcount (skips zero-refcount indices)
#include "RefCountVector.h"
Public Member Functions
BaseIterator ()
bool operator!= (const BaseIterator &Other) const
bool operator== (const BaseIterator &Other) const
Protected Member Functions
BaseIterator (const FRefCountVector *VectorIn, int IndexIn, int LastIn)
void goto_next ()
Protected Attributes
int Index
int LastIndex
const FRefCountVector * Vector
Friends
class FRefCountVector
Detailed Description
base iterator for indices with valid refcount (skips zero-refcount indices)
Definition at line 335 of file RefCountVector.h.
Constructor & Destructor Documentation
BaseIterator() [1/2]
UE::Geometry::FRefCountVector::BaseIterator::BaseIterator () inline
Definition at line 338 of file RefCountVector.h.
References Index, LastIndex, and Vector.
Referenced by UE::Geometry::FRefCountVector::IndexIterator::IndexIterator(), UE::Geometry::FRefCountVector::IndexIterator::IndexIterator(), operator!=(), and operator==().
BaseIterator() [2/2]
UE::Geometry::FRefCountVector::BaseIterator::BaseIterator (const FRefCountVector * VectorIn, int IndexIn, int LastIn) inline protected
Definition at line 364 of file RefCountVector.h.
References FRefCountVector, goto_next(), Index, LastIndex, and Vector.
Member Function Documentation
goto_next()
void UE::Geometry::FRefCountVector::BaseIterator::goto_next () inline protected
Definition at line 355 of file RefCountVector.h.
References Index, and UE::Geometry::FRefCountVector::IsValidUnsafe().
Referenced by BaseIterator(), UE::Geometry::FRefCountVector::IndexIterator::operator++(), and UE::Geometry::FRefCountVector::IndexIterator::operator++().
operator!=()
bool UE::Geometry::FRefCountVector::BaseIterator::operator!= (const BaseIterator & Other) const inline
Definition at line 349 of file RefCountVector.h.
References BaseIterator(), Index, and Other.
operator==()
bool UE::Geometry::FRefCountVector::BaseIterator::operator== (const BaseIterator & Other) const inline
Definition at line 345 of file RefCountVector.h.
References BaseIterator(), Index, and Other.
Friends And Related Symbol Documentation
FRefCountVector
friend class FRefCountVector friend
Definition at line 377 of file RefCountVector.h.
References FRefCountVector.
Referenced by BaseIterator(), and FRefCountVector.
Field Documentation
Index
int UE::Geometry::FRefCountVector::BaseIterator::Index protected
Definition at line 375 of file RefCountVector.h.
Referenced by BaseIterator(), BaseIterator(), UE::Geometry::FRefCountVector::IndexIterator::IndexIterator(), goto_next(), operator!=(), UE::Geometry::FRefCountVector::IndexIterator::operator*(), and operator==().
LastIndex
int UE::Geometry::FRefCountVector::BaseIterator::LastIndex protected
Definition at line 376 of file RefCountVector.h.
Referenced by BaseIterator(), and BaseIterator().
Vector
const FRefCountVector* UE::Geometry::FRefCountVector::BaseIterator::Vector protected
Definition at line 374 of file RefCountVector.h.
Referenced by BaseIterator(), and BaseIterator().
The documentation for this class was generated from the following file:
RefCountVector.h