Unreal Engine 5.6 C++ API: UE::MovieScene::FGarbageTraits Struct Reference
UE::MovieScene::FGarbageTraits Struct Reference
#include "MovieSceneOverlappingEntityTracker.h"
Static Public Member Functions
template<typename T>
static FORCEINLINE void AddReferencedObjects (FReferenceCollector &ReferenceCollector, T *In)
static FORCEINLINE constexpr bool IsGarbage (...)
static FORCEINLINE bool IsGarbage (FObjectComponent &InComponent)
static FORCEINLINE bool IsGarbage (FObjectKey InObject)
template<typename T>
static FORCEINLINE std::enable_if_t< TPointerIsConvertibleFromTo< T, const UObject >::Value, bool > IsGarbage (T *InObject)
template<typename T>
static FORCEINLINE bool IsGarbage (TObjectPtr< T > &InObject)
Detailed Description
Definition at line 31 of file MovieSceneOverlappingEntityTracker.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> FORCEINLINE void UE::MovieScene::FGarbageTraits::AddReferencedObjects (FReferenceCollector & ReferenceCollector, T * In) inline static
Definition at line 58 of file MovieSceneOverlappingEntityTracker.h.
References UE::MovieScene::AddReferencedObjectForComponent(), FORCEINLINE, and UE::MovieScene::THasAddReferencedObjectForComponent< T >::Value.
Referenced by UE::MovieScene::TGarbageTraitsImpl< TIntegerSequence< int, Indices... >, T... >::AddReferencedObjects(), and UE::MovieScene::TOverlappingEntityTracker_WithGarbage< OutputType, InputTypes... >::AddReferencedObjects().
IsGarbage() [1/5]
FORCEINLINE constexpr bool UE::MovieScene::FGarbageTraits::IsGarbage (...) inline static constexpr
Definition at line 33 of file MovieSceneOverlappingEntityTracker.h.
References FORCEINLINE.
Referenced by UE::MovieScene::TGarbageTraitsImpl< TIntegerSequence< int, Indices... >, T... >::IsGarbage().
IsGarbage() [2/5]
FORCEINLINE bool UE::MovieScene::FGarbageTraits::IsGarbage (FObjectComponent & InComponent) inline static
Definition at line 52 of file MovieSceneOverlappingEntityTracker.h.
References FORCEINLINE, UE::MovieScene::FObjectComponent::GetObject(), and UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage().
IsGarbage() [3/5]
FORCEINLINE bool UE::MovieScene::FGarbageTraits::IsGarbage (FObjectKey InObject) inline static
Definition at line 43 of file MovieSceneOverlappingEntityTracker.h.
References FORCEINLINE, UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage(), and FObjectKey::ResolveObjectPtr().
IsGarbage() [4/5]
template<typename T> FORCEINLINE std::enable_if_t< TPointerIsConvertibleFromTo< T, const UObject >::Value, bool > UE::MovieScene::FGarbageTraits::IsGarbage (T * InObject) inline static
Definition at line 38 of file MovieSceneOverlappingEntityTracker.h.
References FORCEINLINE.
IsGarbage() [5/5]
template<typename T> FORCEINLINE bool UE::MovieScene::FGarbageTraits::IsGarbage (TObjectPtr< T > & InObject) inline static
Definition at line 48 of file MovieSceneOverlappingEntityTracker.h.
References FORCEINLINE, and UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage().
The documentation for this struct was generated from the following file:
MovieSceneOverlappingEntityTracker.h