Unreal Engine 5.6 C++ API: UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage > Struct Template Reference
UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage > Struct Template Reference
NOTE: This class is currently considered internal only, and should only be used by engine code.
#include "SparseBitSet.h"
Data Structures
struct FBitOffsets
struct FIterator
Public Types
using BucketType = typename BucketStorage::BucketType
Public Member Functions
TFixedSparseBitSet ()
TFixedSparseBitSet (const TFixedSparseBitSet &)=default
template<typename ... StorageArgs>
TFixedSparseBitSet (StorageArgs &&...Storage)
TFixedSparseBitSet (TFixedSparseBitSet &&)=default
template<typename OtherHashType, typename OtherStorageType>
void CopyTo (TFixedSparseBitSet< OtherHashType, OtherStorageType > &Other) const
template<typename OtherHashType, typename OtherStorageType>
void CopyToUnsafe (TFixedSparseBitSet< OtherHashType, OtherStorageType > &Other, uint32 OtherBucketCapacity) const
Copy this bitset to another without resizing the destination's bucket storage.
uint32 CountSetBits () const
uint32 GetMaxNumBits () const
int32 GetSparseBucketIndex (uint32 BitIndex) const
Get the sparse bucket index of the specified bit.
bool IsBitSet (uint32 BitIndex) const
Check whether the specified bit index is set.
bool IsEmpty () const
uint32 NumBuckets () const
Count the number of buckets in this bitset.
TFixedSparseBitSet & operator= (const TFixedSparseBitSet &)=default
TFixedSparseBitSet & operator= (TFixedSparseBitSet &&)=default
TFixedSparseBitSet & operator|= (const TFixedSparseBitSet &Other)
ESparseBitSetBitResult SetBit (uint32 BitIndex)
Set the bit at the specified index.
Static Public Attributes
static constexpr uint32 BucketSize = sizeof(typename BucketStorage::BucketType)*8
static constexpr uint32 HashSize = sizeof(HashType)*8
static constexpr uint32 MaxNumBits = HashSize * BucketSize
Private Member Functions
FORCEINLINE void CheckIndex (uint32 BitIndex) const
Private Attributes
HashType BucketHash
BucketStorage Buckets
Friends
template<typename, typename>
struct TFixedSparseBitSet
FIterator begin (const TFixedSparseBitSet< HashType, BucketStorage > &In)
FIterator end (const TFixedSparseBitSet< HashType, BucketStorage > &In)
Detailed Description
template<typename HashType, typename BucketStorage>
struct UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >
NOTE: This class is currently considered internal only, and should only be used by engine code.
A sparse bitset comprising a hash of integer indexes with set bits, and a sparse array of unsigned integers (referred to as buckets) whose width is defined by the storage.
The maximum size bitfield that is representible by this bitset is defined as sizeof(HashType)*sizeof(BucketStorage::BucketType). For example, a 64 bit hash with 32 bit buckets can represent a bitfield of upto 2048 bits.
The hash allows for empty buckets to be completely omitted from memory, and affords very fast comparison for buckets that have no set bits. This container is specialized for relatively large bitfields that have small numbers of set bits (ie, needles in haystacks) as they will provide the best memory vs CPU tradeoffs.
Definition at line 79 of file SparseBitSet.h.
Member Typedef Documentation
BucketType
template<typename HashType, typename BucketStorage> using UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::BucketType = typename BucketStorage::BucketType
Definition at line 81 of file SparseBitSet.h.
Constructor & Destructor Documentation
TFixedSparseBitSet() [1/4]
template<typename HashType, typename BucketStorage> UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::TFixedSparseBitSet () inline explicit
Definition at line 86 of file SparseBitSet.h.
References BucketHash.
TFixedSparseBitSet() [2/4]
template<typename HashType, typename BucketStorage> template<typename ... StorageArgs> UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::TFixedSparseBitSet (StorageArgs &&... Storage) inline explicit
Definition at line 91 of file SparseBitSet.h.
References BucketHash, Buckets, and Forward().
TFixedSparseBitSet() [3/4]
template<typename HashType, typename BucketStorage> UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::TFixedSparseBitSet (const TFixedSparseBitSet< HashType, BucketStorage > &) default
References TFixedSparseBitSet.
TFixedSparseBitSet() [4/4]
template<typename HashType, typename BucketStorage> UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::TFixedSparseBitSet (TFixedSparseBitSet< HashType, BucketStorage > &&) default
References TFixedSparseBitSet.
Member Function Documentation
CheckIndex()
template<typename HashType, typename BucketStorage> FORCEINLINE void UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::CheckIndex (uint32 BitIndex) const inline private
Definition at line 389 of file SparseBitSet.h.
References checkfSlow, FORCEINLINE, MaxNumBits, and TEXT.
Referenced by GetSparseBucketIndex(), IsBitSet(), and SetBit().
CopyTo()
template<typename HashType, typename BucketStorage> template<typename OtherHashType, typename OtherStorageType> void UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::CopyTo (TFixedSparseBitSet< OtherHashType, OtherStorageType > & Other) const inline
Definition at line 103 of file SparseBitSet.h.
References TFixedSparseBitSet, BucketSize, CopyToUnsafe(), NumBuckets(), and Other.
CopyToUnsafe()
template<typename HashType, typename BucketStorage> template<typename OtherHashType, typename OtherStorageType> void UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::CopyToUnsafe (TFixedSparseBitSet< OtherHashType, OtherStorageType > & Other, uint32 OtherBucketCapacity) const inline
Copy this bitset to another without resizing the destination's bucket storage.
Bucket storage must be >= this size.
Definition at line 115 of file SparseBitSet.h.
References TFixedSparseBitSet, BucketHash, BucketSize, checkf, FMemory::Memcpy(), NumBuckets(), Other, and TEXT.
Referenced by CopyTo().
CountSetBits()
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::CountSetBits () const inline
Definition at line 174 of file SparseBitSet.h.
References Buckets, and NumBuckets().
GetMaxNumBits()
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::GetMaxNumBits () const inline
Definition at line 185 of file SparseBitSet.h.
References MaxNumBits.
GetSparseBucketIndex()
template<typename HashType, typename BucketStorage> int32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::GetSparseBucketIndex (uint32 BitIndex) const inline
Get the sparse bucket index of the specified bit.
Definition at line 246 of file SparseBitSet.h.
References BucketHash, Buckets, BucketSize, CheckIndex(), Hash, and INDEX_NONE.
IsBitSet()
template<typename HashType, typename BucketStorage> bool UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::IsBitSet (uint32 BitIndex) const inline
Check whether the specified bit index is set.
Definition at line 226 of file SparseBitSet.h.
References BucketHash, Buckets, BucketSize, CheckIndex(), and Hash.
Referenced by UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::IsBitSet().
IsEmpty()
template<typename HashType, typename BucketStorage> bool UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::IsEmpty () const inline
Definition at line 190 of file SparseBitSet.h.
References BucketHash.
NumBuckets()
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::NumBuckets () const inline
Count the number of buckets in this bitset.
Definition at line 169 of file SparseBitSet.h.
References BucketHash.
Referenced by CopyTo(), CopyToUnsafe(), and CountSetBits().
operator=() [1/2]
template<typename HashType, typename BucketStorage> TFixedSparseBitSet & UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::operator= (const TFixedSparseBitSet< HashType, BucketStorage > &) default
References TFixedSparseBitSet.
operator=() [2/2]
template<typename HashType, typename BucketStorage> TFixedSparseBitSet & UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::operator= (TFixedSparseBitSet< HashType, BucketStorage > &&) default
References TFixedSparseBitSet.
operator|=()
template<typename HashType, typename BucketStorage> TFixedSparseBitSet & UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::operator|= (const TFixedSparseBitSet< HashType, BucketStorage > & Other) inline
Definition at line 129 of file SparseBitSet.h.
References TFixedSparseBitSet, BucketHash, Buckets, UE::MovieScene::Private::CountTrailingZeros(), HashSize, One, and Other.
SetBit()
template<typename HashType, typename BucketStorage> ESparseBitSetBitResult UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::SetBit (uint32 BitIndex) inline
Set the bit at the specified index.
Any bits between Num and BitIndex will be considered 0.
Returns
true if the bit was previously considered 0 and is now set, false if it was already set.
Definition at line 201 of file SparseBitSet.h.
References UE::MovieScene::AlreadySet, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FBitOffsets::BitMaskWithinBucket, BucketHash, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FBitOffsets::BucketIndex, Buckets, CheckIndex(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FBitOffsets::HashBit, and UE::MovieScene::NewlySet.
Referenced by UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::SetBit().
Friends And Related Symbol Documentation
TFixedSparseBitSet
template<typename HashType, typename BucketStorage> template<typename, typename> friend struct TFixedSparseBitSet friend
Definition at line 387 of file SparseBitSet.h.
References TFixedSparseBitSet.
Referenced by TFixedSparseBitSet(), TFixedSparseBitSet(), TFixedSparseBitSet, UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin(), begin, CopyTo(), CopyToUnsafe(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::End(), end, operator=(), operator=(), and operator|=().
begin
template<typename HashType, typename BucketStorage> FIterator begin (const TFixedSparseBitSet< HashType, BucketStorage > & In) friend
Definition at line 381 of file SparseBitSet.h.
References TFixedSparseBitSet, and UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin().
end
template<typename HashType, typename BucketStorage> FIterator end (const TFixedSparseBitSet< HashType, BucketStorage > & In) friend
Definition at line 382 of file SparseBitSet.h.
References TFixedSparseBitSet, and UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::End().
Field Documentation
BucketHash
template<typename HashType, typename BucketStorage> HashType UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::BucketHash private
Definition at line 412 of file SparseBitSet.h.
Referenced by TFixedSparseBitSet(), TFixedSparseBitSet(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin(), CopyToUnsafe(), GetSparseBucketIndex(), IsBitSet(), IsEmpty(), NumBuckets(), operator|=(), and SetBit().
Buckets
template<typename HashType, typename BucketStorage> BucketStorage UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::Buckets private
Definition at line 411 of file SparseBitSet.h.
Referenced by TFixedSparseBitSet(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin(), CountSetBits(), GetSparseBucketIndex(), IsBitSet(), operator|=(), and SetBit().
BucketSize
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::BucketSize = sizeof(typename BucketStorage::BucketType)*8 static constexpr
Definition at line 83 of file SparseBitSet.h.
Referenced by UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FBitOffsets::FBitOffsets(), CopyTo(), CopyToUnsafe(), GetSparseBucketIndex(), IsBitSet(), and UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator*().
HashSize
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::HashSize = sizeof(HashType)*8 static constexpr
Definition at line 82 of file SparseBitSet.h.
Referenced by UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::Begin(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::End(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator bool(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::FIterator::operator++(), and operator|=().
MaxNumBits
template<typename HashType, typename BucketStorage> uint32 UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::MaxNumBits = HashSize * BucketSize static constexpr
Definition at line 84 of file SparseBitSet.h.
Referenced by UE::MovieScene::TDynamicSparseBitSet< HashType, BucketStorage >::FEntry::FEntry(), CheckIndex(), and GetMaxNumBits().
The documentation for this struct was generated from the following file:
SparseBitSet.h