Unreal Engine 5.6 C++ API: Verse::FNativeString Class Reference
Verse::FNativeString Class Reference
#include "VVMNativeString.h"
Public Types
using ElementType = FUtf8String::ElementType
Public Member Functions
FNativeString ()=default
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& TIsCharType_V<CharRangeElementType>)>
FORCEINLINE FNativeString (CharRangeType &&Range)
FORCEINLINE FNativeString (const ANSICHAR *Str)
FNativeString (const FNativeString &)=default
FNativeString (FNativeString &&)=default
FORCEINLINE FNativeString (FUtf8String &&InString)
FORCEINLINE bool Equals (const FNativeString &Other) const
FORCEINLINE bool IsEmpty () const
FORCEINLINE int Len () const
FORCEINLINE const ElementType * operator* () const UE_LIFETIMEBOUND
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& TIsCharType_V<CharRangeElementType>)>
FORCEINLINE FNativeString & operator+= (CharRangeType &&Str)
FORCEINLINE FNativeString & operator+= (const ANSICHAR *Str)
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& std::is_same_v<ElementType, CharRangeElementType>)>
FORCEINLINE FNativeString & operator= (CharRangeType &&Range)
FNativeString & operator= (const FNativeString &)=default
FNativeString & operator= (FNativeString &&)=default
FORCEINLINE const ElementType & operator[] (int32 Index) const UE_LIFETIMEBOUND
FORCEINLINE ElementType & operator[] (int32 Index) UE_LIFETIMEBOUND
void Reset (int32 NewReservedSize=0)
Static Public Member Functions
static void AutoRTFMAssignFromOpenToClosed (FNativeString &Closed, const FNativeString &Open)
template<typename... Types>
static FORCEINLINE FNativeString Printf (UE::Core::TCheckedFormatString< FUtf8String::FmtCharType, Types... > Fmt, Types... Args)
Private Attributes
FUtf8String String
Friends
FORCEINLINE const ElementType * GetData (const FNativeString &InString)
FORCEINLINE ElementType * GetData (FNativeString &InString)
FORCEINLINE int32 GetNum (const FNativeString &InString)
FORCEINLINE int32 GetTypeHash (const FNativeString &S)
FORCEINLINE friend bool operator!= (const FNativeString &Lhs, const FNativeString &Rhs)
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& std::is_same_v<ElementType, CharRangeElementType>)>
FORCEINLINE friend FNativeString operator+ (FNativeString &&Lhs, CharRangeType &&Rhs)
FORCEINLINE friend FNativeString operator+ (FNativeString &&Lhs, const ANSICHAR *Rhs)
FORCEINLINE FArchive & operator<< (FArchive &Ar, FNativeString &S)
FORCEINLINE friend bool operator== (const FNativeString &Lhs, const FNativeString &Rhs)
Detailed Description
Definition at line 27 of file VVMNativeString.h.
Member Typedef Documentation
ElementType
using Verse::FNativeString::ElementType = FUtf8String::ElementType
Definition at line 30 of file VVMNativeString.h.
Constructor & Destructor Documentation
FNativeString() [1/6]
Verse::FNativeString::FNativeString () default
Referenced by FNativeString(), FNativeString(), AutoRTFMAssignFromOpenToClosed(), Equals(), GetData, GetData, GetNum, GetTypeHash, operator!=, operator+, operator+, operator+=(), operator+=(), operator<<, operator=(), operator=(), operator=(), operator==, and Printf().
FNativeString() [2/6]
Verse::FNativeString::FNativeString (FNativeString &&) default
References FNativeString().
FNativeString() [3/6]
Verse::FNativeString::FNativeString (const FNativeString &) default
References FNativeString().
FNativeString() [4/6]
FORCEINLINE Verse::FNativeString::FNativeString (const ANSICHAR * Str) inline
Definition at line 42 of file VVMNativeString.h.
References FORCEINLINE, and String.
FNativeString() [5/6]
FORCEINLINE Verse::FNativeString::FNativeString (FUtf8String && InString) inline
Definition at line 45 of file VVMNativeString.h.
References FORCEINLINE, MoveTemp(), and String.
FNativeString() [6/6]
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& TIsCharType_V<CharRangeElementType>)> FORCEINLINE Verse::FNativeString::FNativeString (CharRangeType && Range) inline explicit
Definition at line 52 of file VVMNativeString.h.
References FORCEINLINE, Forward(), and String.
Member Function Documentation
AutoRTFMAssignFromOpenToClosed()
void Verse::FNativeString::AutoRTFMAssignFromOpenToClosed (FNativeString & Closed, const FNativeString & Open) inline static
Definition at line 141 of file VVMNativeString.h.
References FNativeString(), and ensure.
Equals()
FORCEINLINE bool Verse::FNativeString::Equals (const FNativeString & Other) const inline nodiscard
Definition at line 92 of file VVMNativeString.h.
References FNativeString(), ESearchCase::CaseSensitive, FORCEINLINE, Other, and String.
Referenced by operator!=, and operator==.
IsEmpty()
FORCEINLINE bool Verse::FNativeString::IsEmpty () const inline nodiscard
Definition at line 78 of file VVMNativeString.h.
References FORCEINLINE, and String.
Len()
FORCEINLINE int Verse::FNativeString::Len () const inline nodiscard
Definition at line 77 of file VVMNativeString.h.
References FORCEINLINE, and String.
operator*()
FORCEINLINE const ElementType * Verse::FNativeString::operator* () const inline nodiscard
Definition at line 75 of file VVMNativeString.h.
References FORCEINLINE, String, and UE_LIFETIMEBOUND.
operator+=() [1/2]
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& TIsCharType_V<CharRangeElementType>)> FORCEINLINE FNativeString & Verse::FNativeString::operator+= (CharRangeType && Str) inline
Definition at line 109 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, Forward(), and String.
operator+=() [2/2]
FORCEINLINE FNativeString & Verse::FNativeString::operator+= (const ANSICHAR * Str) inline
Definition at line 114 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, and String.
operator=() [1/3]
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& std::is_same_v<ElementType, CharRangeElementType>)> FORCEINLINE FNativeString & Verse::FNativeString::operator= (CharRangeType && Range) inline
Definition at line 61 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, Forward(), and String.
operator=() [2/3]
FNativeString & Verse::FNativeString::operator= (const FNativeString &) default
References FNativeString().
operator=() [3/3]
FNativeString & Verse::FNativeString::operator= (FNativeString &&) default
References FNativeString().
operator[]() [1/2]
FORCEINLINE const ElementType & Verse::FNativeString::operator[] (int32 Index) const inline
Definition at line 73 of file VVMNativeString.h.
References FORCEINLINE, String, and UE_LIFETIMEBOUND.
operator[]() [2/2]
FORCEINLINE ElementType & Verse::FNativeString::operator[] (int32 Index) inline
Definition at line 72 of file VVMNativeString.h.
References FORCEINLINE, String, and UE_LIFETIMEBOUND.
Printf()
template<typename... Types> FORCEINLINE FNativeString Verse::FNativeString::Printf (UE::Core::TCheckedFormatString< FUtf8String::FmtCharType, Types... > Fmt, Types... Args) inline static nodiscard
Definition at line 134 of file VVMNativeString.h.
References FNativeString(), and FORCEINLINE.
Reset()
void Verse::FNativeString::Reset (int32 NewReservedSize = 0) inline
Definition at line 103 of file VVMNativeString.h.
References String.
Friends And Related Symbol Documentation
GetData [1/2]
FORCEINLINE const ElementType * GetData (const FNativeString & InString) friend
Definition at line 68 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, GetData, and String.
Referenced by GetData.
GetData [2/2]
FORCEINLINE ElementType * GetData (FNativeString & InString) friend
Definition at line 67 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, GetData, and String.
Referenced by GetData, and GetTypeHash.
GetNum
FORCEINLINE int32 GetNum (const FNativeString & InString) friend
Definition at line 70 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, GetNum, and String.
Referenced by GetNum, and GetTypeHash.
GetTypeHash
FORCEINLINE int32 GetTypeHash (const FNativeString & S) friend
Definition at line 97 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, GetData, GetNum, and FCrc::StrCrc32Len().
operator!=
FORCEINLINE friend bool operator!= (const FNativeString & Lhs, const FNativeString & Rhs) friend
Definition at line 86 of file VVMNativeString.h.
References FNativeString(), Equals(), and FORCEINLINE.
operator+ [1/2]
template<typename CharRangeType, typename CharRangeElementType = TElementType_T<CharRangeType> UE_REQUIRES(TIsContiguousContainer<CharRangeType>::Value&& std::is_same_v<ElementType, CharRangeElementType>)> FORCEINLINE friend FNativeString operator+ (FNativeString && Lhs, CharRangeType && Rhs) friend
Definition at line 124 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, Forward(), and MoveTemp().
operator+ [2/2]
FORCEINLINE friend FNativeString operator+ (FNativeString && Lhs, const ANSICHAR * Rhs) friend
Definition at line 128 of file VVMNativeString.h.
References FNativeString(), FORCEINLINE, and MoveTemp().
operator<<
FORCEINLINE FArchive & operator<< (FArchive & Ar, FNativeString & S) friend
Definition at line 139 of file VVMNativeString.h.
References FNativeString(), Ar, FORCEINLINE, and String.
operator==
FORCEINLINE friend bool operator== (const FNativeString & Lhs, const FNativeString & Rhs) friend
Definition at line 80 of file VVMNativeString.h.
References FNativeString(), Equals(), and FORCEINLINE.
Field Documentation
String
FUtf8String Verse::FNativeString::String private
Definition at line 33 of file VVMNativeString.h.
Referenced by FNativeString(), FNativeString(), FNativeString(), Equals(), GetData, GetData, GetNum, IsEmpty(), Len(), operator*(), operator+=(), operator+=(), operator<<, operator=(), operator[](), operator[](), and Reset().
The documentation for this class was generated from the following file:
VVMNativeString.h