Unreal Engine 5.6 C++ API: FMemoryImageString Class Reference
FMemoryImageString Class Reference
#include "MemoryImage.h"
Public Types
using ElementType = TCHAR
Public Member Functions
FMemoryImageString ()=default
template<typename CharType, typename = typename TEnableIf<TIsCharType<CharType>::Value>::Type>
FORCEINLINE FMemoryImageString (const CharType *Src)
FMemoryImageString (const FMemoryImageString &)=default
FORCEINLINE FMemoryImageString (const FString &Other)
FMemoryImageString (FMemoryImageString &&)=default
FORCEINLINE SIZE_T GetAllocatedSize () const
DataType::ElementAllocatorType & GetAllocatorInstance ()
FORCEINLINE bool IsEmpty () const
FORCEINLINE int32 Len () const
FORCEINLINE operator FString () const
bool operator!= (const FMemoryImageString &Rhs) const
bool operator!= (const FString &Rhs) const
FORCEINLINE const TCHAR * operator* () const
FMemoryImageString & operator= (const FMemoryImageString &)=default
FMemoryImageString & operator= (FMemoryImageString &&)=default
bool operator== (const FMemoryImageString &Rhs) const
bool operator== (const FString &Rhs) const
Private Types
using DataType = TMemoryImageArray<TCHAR>
Array holding the character data.
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FMemoryImageString, 1, NonVirtual)
LAYOUT_FIELD (DataType, Data)
LAYOUT_TOSTRING (ToString)
void ToString (FMemoryToStringContext &OutContext) const
Friends
const TCHAR * GetData (const FMemoryImageString &String)
int32 GetNum (const FMemoryImageString &String)
FORCEINLINE uint32 GetTypeHash (const FMemoryImageString &S)
Case insensitive string hash function.
FArchive & operator<< (FArchive &Ar, FMemoryImageString &Ref)
Detailed Description
Definition at line 742 of file MemoryImage.h.
Member Typedef Documentation
DataType
using FMemoryImageString::DataType = TMemoryImageArray<TCHAR> private
Array holding the character data.
Definition at line 747 of file MemoryImage.h.
ElementType
using FMemoryImageString::ElementType = TCHAR
Definition at line 753 of file MemoryImage.h.
Constructor & Destructor Documentation
FMemoryImageString() [1/5]
FMemoryImageString::FMemoryImageString () default
Referenced by FMemoryImageString(), FMemoryImageString(), DECLARE_EXPORTED_TYPE_LAYOUT(), GetData, GetNum, GetTypeHash, operator!=(), operator<<, operator=(), operator=(), and operator==().
FMemoryImageString() [2/5]
FMemoryImageString::FMemoryImageString (FMemoryImageString &&) default
References FMemoryImageString().
FMemoryImageString() [3/5]
FMemoryImageString::FMemoryImageString (const FMemoryImageString &) default
References FMemoryImageString().
FMemoryImageString() [4/5]
FORCEINLINE FMemoryImageString::FMemoryImageString (const FString & Other) inline
Definition at line 761 of file MemoryImage.h.
References FORCEINLINE, and Other.
FMemoryImageString() [5/5]
template<typename CharType, typename = typename TEnableIf<TIsCharType<CharType>::Value>::Type> FORCEINLINE FMemoryImageString::FMemoryImageString (const CharType * Src) inline
Definition at line 767 of file MemoryImage.h.
References FGenericPlatformString::Convert(), FGenericPlatformString::ConvertedLength(), FORCEINLINE, and TCString< T >::Strlen().
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FMemoryImageString::DECLARE_EXPORTED_TYPE_LAYOUT (FMemoryImageString , 1 , NonVirtual) private
References FMemoryImageString().
GetAllocatedSize()
FORCEINLINE SIZE_T FMemoryImageString::GetAllocatedSize () const inline
Definition at line 789 of file MemoryImage.h.
References FORCEINLINE.
GetAllocatorInstance()
DataType::ElementAllocatorType & FMemoryImageString::GetAllocatorInstance () inline
Definition at line 832 of file MemoryImage.h.
IsEmpty()
FORCEINLINE bool FMemoryImageString::IsEmpty () const inline
Definition at line 788 of file MemoryImage.h.
References FORCEINLINE.
LAYOUT_FIELD()
FMemoryImageString::LAYOUT_FIELD (DataType , Data) private
LAYOUT_TOSTRING()
FMemoryImageString::LAYOUT_TOSTRING (ToString) private
References ToString().
Len()
FORCEINLINE int32 FMemoryImageString::Len () const inline
Definition at line 791 of file MemoryImage.h.
References FORCEINLINE.
Referenced by operator FString().
operator FString()
FORCEINLINE FMemoryImageString::operator FString () const inline
Definition at line 778 of file MemoryImage.h.
References FORCEINLINE, and Len().
operator!=() [1/2]
bool FMemoryImageString::operator!= (const FMemoryImageString & Rhs) const inline
Definition at line 817 of file MemoryImage.h.
References FMemoryImageString(), and TCString< TCHAR >::Stricmp().
operator!=() [2/2]
bool FMemoryImageString::operator!= (const FString & Rhs) const inline
Definition at line 827 of file MemoryImage.h.
References TCString< TCHAR >::Stricmp().
operator*()
FORCEINLINE const TCHAR * FMemoryImageString::operator* () const inline
Definition at line 783 of file MemoryImage.h.
References FORCEINLINE, and TEXT.
operator=() [1/2]
FMemoryImageString & FMemoryImageString::operator= (const FMemoryImageString &) default
References FMemoryImageString().
operator=() [2/2]
FMemoryImageString & FMemoryImageString::operator= (FMemoryImageString &&) default
References FMemoryImageString().
operator==() [1/2]
bool FMemoryImageString::operator== (const FMemoryImageString & Rhs) const inline
Definition at line 812 of file MemoryImage.h.
References FMemoryImageString(), and TCString< TCHAR >::Stricmp().
operator==() [2/2]
bool FMemoryImageString::operator== (const FString & Rhs) const inline
Definition at line 822 of file MemoryImage.h.
References TCString< TCHAR >::Stricmp().
ToString()
void FMemoryImageString::ToString (FMemoryToStringContext & OutContext) const private
Referenced by LAYOUT_TOSTRING().
Friends And Related Symbol Documentation
GetData
const TCHAR * GetData (const FMemoryImageString & String) friend
Definition at line 796 of file MemoryImage.h.
References FMemoryImageString(), and String.
GetNum
int32 GetNum (const FMemoryImageString & String) friend
Definition at line 801 of file MemoryImage.h.
References FMemoryImageString(), and String.
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FMemoryImageString & S) friend
Case insensitive string hash function.
Definition at line 835 of file MemoryImage.h.
References FMemoryImageString(), FORCEINLINE, and FCrc::Strihash_DEPRECATED().
operator<<
FArchive & operator<< (FArchive & Ar, FMemoryImageString & Ref) friend
Definition at line 806 of file MemoryImage.h.
References FMemoryImageString(), and Ar.
The documentation for this class was generated from the following file:
MemoryImage.h