Unreal Engine 5.6 C++ API: FGenericPlatformRHIFramePacer Struct Reference
FGenericPlatformRHIFramePacer Struct Reference
Generic implementation for most platforms.
#include "GenericPlatformFramePacer.h"
Static Public Member Functions
static int32 GetFramePace ()
The pace we are running at (30 = 30fps, 0 = unpaced) The generic implementation returns a result based on rhi.SyncInterval and FPlatformMisc::GetMaxRefreshRate().
static int32 SetFramePace (int32 FramePace)
Sets the pace we would like to running at (30 = 30fps, 0 = unpaced).
static APPLICATIONCORE_API bool SupportsFramePace (int32 QueryFramePace)
Returns whether the hardware is able to frame pace at the specified frame rate.
Static Protected Member Functions
static APPLICATIONCORE_API int32 GetFramePaceFromSyncInterval ()
The generic implementation returns a result based on rhi.SyncInterval and FPlatformMisc::GetMaxRefreshRate().
static APPLICATIONCORE_API int32 SetFramePaceToSyncInterval (int32 FramePace)
The generic implementation sets rhi.SyncInterval based on FPlatformMisc::GetMaxRefreshRate().
Detailed Description
Generic implementation for most platforms.
Definition at line 17 of file GenericPlatformFramePacer.h.
Member Function Documentation
GetFramePace()
int32 FGenericPlatformRHIFramePacer::GetFramePace () inline static
The pace we are running at (30 = 30fps, 0 = unpaced) The generic implementation returns a result based on rhi.SyncInterval and FPlatformMisc::GetMaxRefreshRate().
Definition at line 23 of file GenericPlatformFramePacer.h.
References GetFramePaceFromSyncInterval().
GetFramePaceFromSyncInterval()
APPLICATIONCORE_API int32 FGenericPlatformRHIFramePacer::GetFramePaceFromSyncInterval () static protected
The generic implementation returns a result based on rhi.SyncInterval and FPlatformMisc::GetMaxRefreshRate().
Referenced by GetFramePace().
SetFramePace()
int32 FGenericPlatformRHIFramePacer::SetFramePace (int32 FramePace) inline static
Sets the pace we would like to running at (30 = 30fps, 0 = unpaced).
The generic implementation sets the value for rhi.SyncInterval according to FPlatformMisc::GetMaxRefreshRate().
Returns
the pace we will run at.
Definition at line 34 of file GenericPlatformFramePacer.h.
References SetFramePaceToSyncInterval().
SetFramePaceToSyncInterval()
APPLICATIONCORE_API int32 FGenericPlatformRHIFramePacer::SetFramePaceToSyncInterval (int32 FramePace) static protected
The generic implementation sets rhi.SyncInterval based on FPlatformMisc::GetMaxRefreshRate().
Returns
the pace we will run at.
Referenced by SetFramePace().
SupportsFramePace()
APPLICATIONCORE_API bool FGenericPlatformRHIFramePacer::SupportsFramePace (int32 QueryFramePace) static
Returns whether the hardware is able to frame pace at the specified frame rate.
The documentation for this struct was generated from the following file:
GenericPlatformFramePacer.h