Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityManager Class Reference
UE::MovieScene::FEntityManager Class Reference
Top-level manager class that is responsible for all entity data and interaction/.
#include "MovieSceneEntityManager.h"
Data Structures
struct FEntityLocation
Public Member Functions
MOVIESCENE_API FEntityManager ()
FEntityManager (const FEntityManager &)=delete
FEntityManager (FEntityManager &&)=delete
MOVIESCENE_API ~FEntityManager ()
MOVIESCENE_API void AccumulateMask (const FEntityComponentFilter &InFilter, FComponentMask &OutMask) const
Accumulate a mask from all entity types that match the specified filter.
MOVIESCENE_API void AddChild (FMovieSceneEntityID ParentID, FMovieSceneEntityID ChildID)
Set up an entity to be a child of another.
MOVIESCENE_API void AddComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID)
Add the specified component type to an entity.
MOVIESCENE_API void AddComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID, EEntityRecursion Recursion)
template<typename T, typename ValueType>
void AddComponent (FMovieSceneEntityID EntityID, TComponentTypeID< T > ComponentTypeID, ValueType &&InValue)
Add the specified component value to an entity.
MOVIESCENE_API void AddComponents (FMovieSceneEntityID EntityID, const FComponentMask &EntityComponentMask)
Add the specified components to an entity.
MOVIESCENE_API void AddComponents (FMovieSceneEntityID EntityID, const FComponentMask &EntityComponentMask, EEntityRecursion Recursion)
MOVIESCENE_API void AddMutualComponents ()
Run through all entities in this entity manager, ensuring that all mutual components exist.
MOVIESCENE_API void AddMutualComponents (const FEntityComponentFilter &InFilter)
Run through all entities in this entity manager, ensuring that all mutual components exist for any component types that match the specified filter.
MOVIESCENE_API void AddReferencedObjects (FReferenceCollector &ReferenceCollector)
Explicitly add referenced objects from an external source.
MOVIESCENE_API FEntityDataLocation AllocateContiguousEntities (const FComponentMask &EntityComponentMask, int32 *InOutNum)
Attempt to allocate a number of entities of the same type contiguously in memory.
MOVIESCENE_API FMovieSceneEntityID AllocateEntity ()
Allocate a new entity with no components.
MOVIESCENE_API FEntityInfo AllocateEntity (const FComponentMask &EntityComponentMask)
Allocate a single entity with the specified components.
MOVIESCENE_API void ChangeEntityType (FMovieSceneEntityID InEntity, const FComponentMask &InNewMask)
Changes the components that exist on an entity to a new mask.
void CheckCanChangeStructure () const
MOVIESCENE_API void CombineComponents (FMovieSceneEntityID DestinationEntityID, FMovieSceneEntityID SourceEntityID, const FComponentMask *OptionalMask=nullptr)
Combine the components from one entity into another, overwriting any pre-existing component values.
MOVIESCENE_API void Compact ()
Goes through all entity data and compacts like-for-like allocations into as few allocations as possible, resulting in the optimal data layout.
MOVIESCENE_API EEntityThreadingModel ComputeThreadingModel () const
Compute and return this entity manager's threading model.
MOVIESCENE_API bool Contains (const FEntityComponentFilter &InFilter) const
Efficiently test whether this entity manager contains any allocations that match the specified filter.
bool ContainsAllComponents (std::initializer_list< FComponentTypeID > ComponentTypeIDs) const
Check whether all of the specified components exist anywhere in this entity manager.
bool ContainsAnyComponent (const FComponentMask &ComponentTypeIDs) const
Check whether any entity in this manager has any of the specified components.
bool ContainsAnyComponent (std::initializer_list< FComponentTypeID > ComponentTypeIDs) const
Check whether any entity in this manager has any of the specified components.
bool ContainsComponent (FComponentTypeID ComponentTypeID) const
Check whether any entity in this manager has the specified component.
MOVIESCENE_API bool CopyComponent (FMovieSceneEntityID SrcEntityID, FMovieSceneEntityID DstEntityID, FComponentTypeID ComponentTypeID)
Copy the specified component type from an entity if it exists.
MOVIESCENE_API void CopyComponents (FMovieSceneEntityID SrcEntityID, FMovieSceneEntityID DstEntityID, const FComponentMask &ComponentsToCopy)
Copy any and all the specified component types from one entity onto another.
MOVIESCENE_API void CountMemory (FArchive &Ar, FMovieSceneEntityID EntityID)
Run a serialization routine over the specified entity to approximate the memory it is using.
int32 DefineInstancedChildInitializer (TInlineValue< FChildEntityInitializer > &&InInitializer)
Defines a new child initializer that applies only to entities factoried within this entity manager.
MOVIESCENE_API void Destroy ()
Destroy this entity manager and all the entities and components contained within it, resetting it back to its default state.
void DestroyInstancedChildInitializer (int32 Index)
Destroy a previously registered instanced child initializer using its index.
MOVIESCENE_API FMovieSceneEntityID DuplicateEntity (FMovieSceneEntityID InOther)
Duplicate an entity, by creating an exact copy with a new ID.
MOVIESCENE_API void EnterIteration () const
Efficiently test whether this entity manager contains any allocations that match the specified filter.
MOVIESCENE_API void ExitIteration () const
MOVIESCENE_API void FilterComponents (FMovieSceneEntityID EntityID, const FComponentMask &EntitiesToKeep)
Remove all but the specified components from an entity.
MOVIESCENE_API int32 FreeEntities (const FEntityComponentFilter &Filter, TSet< FMovieSceneEntityID > *OutFreedEntities=nullptr)
Free all entities that match the specified filter.
MOVIESCENE_API int32 FreeEntities (const FFreeEntityOperation &Operation, TSet< FMovieSceneEntityID > *OutFreedEntities=nullptr)
Free all entities defined by the specified operation.
MOVIESCENE_API void FreeEntity (FMovieSceneEntityID EntityID)
Free an entity and relinquish its entity ID.
MOVIESCENE_API const FComponentMask & GetAccumulatedMask () const
Retrieve an up-to-date accumulation of all components present on entities in this manager.
MOVIESCENE_API void GetChildren_ParentFirst (FMovieSceneEntityID ParentID, TArray< FMovieSceneEntityID > &OutChildren) const
Retrieve all children, grandchildren etc of the specified entity using a parent first traversal.
FComponentRegistry * GetComponents () const
ENamedThreads::Type GetDispatchThread () const
MOVIESCENE_API FEntityInfo GetEntity (FMovieSceneEntityID EntityID) const
Retrieve an entity's allocation and component offset from its ID.
MOVIESCENE_API FEntityHandle GetEntityHandle (FMovieSceneEntityID EntityID)
Retrieve a handle to an entity.
MOVIESCENE_API const FComponentMask & GetEntityType (FMovieSceneEntityID InEntity) const
Retrieve the type mask for this component.
ENamedThreads::Type GetGatherThread () const
const FEntityComponentFilter & GetGlobalIterationFilter () const
Retrieve the entity filter that should be used for any entity iteration.
uint32 GetHandleGeneration () const
MOVIESCENE_API void GetImmediateChildren (FMovieSceneEntityID ParentID, TArray< FMovieSceneEntityID > &OutChildren) const
Retrieve the immediate children of the specified entity.
uint64 GetSystemSerial () const
Get the current serial number for any system ovserving this entity manager.
MOVIESCENE_API EEntityThreadingModel GetThreadingModel () const
Get this entitiy manager's current threading model based on the last time UpdateThreadingModel was called.
MOVIESCENE_API bool HasComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID) const
Check whether the specified component has a component of the specified type.
bool HasStructureChangedSince (uint64 CachedSerial) const
Check whether the structure of this entity manager has changed at all since the specified serial number.
void IncrementSystemSerial (uint64 IncAmount=1)
Increment the current serial number for systems observing this manager.
MOVIESCENE_API void InitializeChildAllocation (const FComponentMask &ParentType, const FComponentMask &ChildType, const FEntityAllocation *ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets, const FEntityRange &InChildEntityRange)
Runs all initializers for the specified parent/child allocation.
bool IsAllocated (FMovieSceneEntityID EntityID) const
Check whether an entity is allocated.
MOVIESCENE_API bool IsHandleValid (FEntityHandle EntityID) const
Check whether the specified entity handle is still valid.
bool IsLockedDown () const
MOVIESCENE_API FEntityAllocationIteratorProxy Iterate (const FEntityComponentFilter *InFilter) const
Iterate through all the allocations that match the specified component filter.
template<typename IteratorType>
void IterateChildren_ParentFirst (FMovieSceneEntityID ParentID, IteratorType &&Iterator) const
Iterate all children, grandchildren etc of the specified entity using a parent first traversal.
template<typename IteratorType>
void IterateImmediateChildren (FMovieSceneEntityID ParentID, IteratorType &&Iterator) const
Itereate the immediate children of the specified entity.
void LockDown ()
void MimicStructureChanged ()
Called in order to mimic the entity structure changing, even if it has not.
FEntityComponentFilter & ModifyGlobalIterationFilter ()
Modify the entity filter that should be used for any entity iteration.
MOVIESCENE_API int32 MutateAll (const FEntityComponentFilter &Filter, const IMovieSceneEntityMutation &Mutation, EMutuallyInclusiveComponentType MutualTypes=EMutuallyInclusiveComponentType::Mandatory)
Efficiently mutate all entities that match a filter.
MOVIESCENE_API int32 MutateConditional (const FEntityComponentFilter &Filter, const IMovieSceneConditionalEntityMutation &Mutation, EMutuallyInclusiveComponentType MutualTypes=EMutuallyInclusiveComponentType::Mandatory)
Efficiently mutate all entities that match a filter.
void operator= (const FEntityManager &)=delete
void operator= (FEntityManager &&)=delete
MOVIESCENE_API void OverwriteEntityWithDuplicate (FMovieSceneEntityID &InOutEntity, FMovieSceneEntityID InEntityToDuplicate)
Duplicate an entity over the top of an existing entity ID.
template<typename T>
TComponentLock< TReadOptional< T > > ReadComponent (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID) const
Attempt to read a component from an entity.
template<typename T>
T ReadComponentChecked (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID) const
Read a component value from an entity that is known to exist.
void ReleaseLockDown ()
MOVIESCENE_API void RemoveComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID)
Remove the specified component type from an entity if it exists.
MOVIESCENE_API void RemoveComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID, EEntityRecursion Recursion)
MOVIESCENE_API void RemoveComponents (FMovieSceneEntityID EntityID, const FComponentMask &ComponentsToRemove)
Remove the specified components from an entity, if they exist.
MOVIESCENE_API void RemoveComponents (FMovieSceneEntityID EntityID, const FComponentMask &ComponentsToRemove, EEntityRecursion Recursion)
MOVIESCENE_API void ReplaceEntityID (FMovieSceneEntityID &InOutEntity, FMovieSceneEntityID EntityToDiscard)
Replace an entity ID with the components from another, discarding the provided entity ID in the process.
void SetComponentRegistry (FComponentRegistry *InComponents)
void SetDebugName (FString &&InNewDebugName)
Set a debug name for this entity manager.
void SetDispatchThread (ENamedThreads::Type InDispatchThread)
void SetGatherThread (ENamedThreads::Type InGatherThread)
MOVIESCENE_API void TouchEntity (FMovieSceneEntityID EntityID)
Touch the specified entity, cause the allocation and component serial numbers to be incremented.
MOVIESCENE_API void UpdateThreadingModel ()
Compute and store the current threading model.
template<typename T>
TComponentLock< TWriteOptional< T > > WriteComponent (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID)
Attempt to write to an entity's component.
template<typename T, typename ValueType>
void WriteComponentChecked (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID, ValueType &&Value)
Write a component value that is known to exist to an entity.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Static Public Member Functions
static MOVIESCENE_API IComponentTypeHandler * FindComponentTypeHandler (const FGuid &ComponentGuid)
Find a component type hander from its registered GUID.
Private Types
enum class ELockdownState { Locked , Unlocked }
enum class EMemoryType { Uninitialized , DefaultConstructed }
Private Member Functions
MOVIESCENE_API int32 AddEntityToAllocation (int32 AllocationIndex, FMovieSceneEntityID ID, EMemoryType MemoryType=EMemoryType::DefaultConstructed)
MOVIESCENE_API void CheckInvariants ()
MOVIESCENE_API void CombineAllocations (int32 DestinationIndex, int32 SourceIndex)
MOVIESCENE_API void CopyComponents (int32 DestAllocationIndex, int32 DestEntityIndex, int32 SourceAllocationIndex, int32 SourceEntityIndex, const FComponentMask *OptionalMask=nullptr)
MOVIESCENE_API int32 CreateAllocationWithSlack (const FComponentMask &EntityComponentMask, int32 *InOutDesiredSlack=nullptr)
MOVIESCENE_API FEntityAllocation * CreateEntityAllocation (const FComponentMask &EntityComponentMask, uint16 InitialCapacity, uint16 MaxCapacity, FEntityAllocation *MigrateComponentDataFrom=nullptr)
MOVIESCENE_API int32 CreateEntityAllocationEntry (const FComponentMask &EntityComponentMask, uint16 InitialCapacity, uint16 MaxCapacity)
MOVIESCENE_API void DestroyAllocation (FEntityAllocation *Allocation, bool bDestructComponentData=true)
virtual SIZE_T GetAllocatedSize () const override
Returns the size of heap memory allocated internally by this listener.
FEntityAllocation * GetAllocation (int32 AllocationIndex) const
MOVIESCENE_API int32 GetOrCreateAllocationWithSlack (const FComponentMask &EntityComponentMask, int32 *InOutDesiredSlack=nullptr)
virtual MOVIESCENE_API FString GetReferencerName () const
MOVIESCENE_API FEntityAllocation * GrowAllocation (int32 AllocationIndex, int32 MinNumToGrowBy=1)
MOVIESCENE_API FEntityAllocation * MigrateAllocation (int32 AllocationIndex, const FComponentMask &NewComponentMask)
MOVIESCENE_API int32 MigrateEntity (int32 DestIndex, int32 SourceIndex, int32 SourceEntryIndexWithinAllocation)
virtual MOVIESCENE_API void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index) override
MOVIESCENE_API void OnStructureChanged ()
virtual MOVIESCENE_API void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
MOVIESCENE_API void RemoveEntityFromAllocation (int32 AllocationIndex, int32 SourceEntryIndexWithinAllocation)
MOVIESCENE_API int32 ReserveAllocation (int32 AllocationIndex, int32 NumToReserve)
Private Attributes
FComponentMask AccumulatedMask
TBitArray AllocationsWithCapacity
Bit mask of allocations that currently have capacity.
bool bAccumulatedMaskStale
bool bHandleGenerationStale
FComponentRegistry * ComponentRegistry
uint32 CurrentHandleGeneration
The current generation of entities - incremented any time an entity is destroyed.
ENamedThreads::Type DispatchThread
TSparseArray< FComponentMask > EntityAllocationMasks
Sparse array of masks that define each index within EntityAllocations' component types.
TSparseArray< FEntityAllocation * > EntityAllocations
Sparse array of entity allocation pointers.
TMap< FMovieSceneEntityID, uint32 > EntityGenerationMap
Map of entity ID to the generation its handle was created in.
TSparseArray< FEntityLocation > EntityLocations
Sparse array of entity location information for each allocated entity ID.
friend FFreeEntityOperation
ENamedThreads::Type GatherThread
FEntityComponentFilter GlobalIterationFilter
TSparseArray< TInlineValue< FChildEntityInitializer > > InstancedChildInitializers
FEntitySystemMaybeAtomicInt32 IterationCount
Atomic counter that is incremented when an iteration begins, and decremented when it finishes.
ELockdownState LockdownState
FString ManagerDebugName
Debug name for this entity manager.
uint32 NextAllocationID
Debugging ptr for natvis.
TMultiMap< FMovieSceneEntityID, FMovieSceneEntityID > ParentToChild
Map of parent -> child entities.
uint64 StructureMutationSystemSerialNumber
The value of this manager's SystemSerialNumber the last time any entities were allocated, freed, or mutated in some way (this does not include component values being written to)
uint64 SystemSerialNumber
System serial number incremented for every run of any system.
EEntityThreadingModel ThreadingModel
Friends
struct FEntityAllocationIterator
struct FEntityAllocationIteratorProxy
struct FEntityAllocationProxy
struct FEntityInitializer
Detailed Description
Top-level manager class that is responsible for all entity data and interaction/.
An entity is a stable index into the manager's EntityLocations, which defines the location for that entity's data. This allows the manager to relocate entity data at will without invalidating client held entity IDs. An entity may contain 0 or more components. Components are concrete pieces of data with a unique type identifier. Additionally, tags can be added to entities or whole batches of entities with zero memory overhead.
Entity Component data is stored in allocations organized by each unique combination of components. Each component type is stored as a contiguous array within each allocation, with each entity's component being a fixed offset from the start of each component array. This enables efficient read/write access into specific component arrays and makes issuing parallel tasks that require component data trivial. See FEntityAllocation for a more detailed explanation of entity component data layout.
Definition at line 80 of file MovieSceneEntityManager.h.
Member Enumeration Documentation
ELockdownState
enum class UE::MovieScene::FEntityManager::ELockdownState strong private
Enumerator
Locked
Unlocked
Definition at line 1034 of file MovieSceneEntityManager.h.
EMemoryType
enum class UE::MovieScene::FEntityManager::EMemoryType strong private
Enumerator
Uninitialized
DefaultConstructed
Definition at line 876 of file MovieSceneEntityManager.h.
Constructor & Destructor Documentation
FEntityManager() [1/3]
MOVIESCENE_API UE::MovieScene::FEntityManager::FEntityManager ()
Referenced by FEntityManager(), FEntityManager(), operator=(), and operator=().
~FEntityManager()
MOVIESCENE_API UE::MovieScene::FEntityManager::~FEntityManager ()
FEntityManager() [2/3]
UE::MovieScene::FEntityManager::FEntityManager (const FEntityManager &) delete
References FEntityManager().
FEntityManager() [3/3]
UE::MovieScene::FEntityManager::FEntityManager (FEntityManager &&) delete
References FEntityManager().
Member Function Documentation
AccumulateMask()
MOVIESCENE_API void UE::MovieScene::FEntityManager::AccumulateMask (const FEntityComponentFilter & InFilter, FComponentMask & OutMask) const
Accumulate a mask from all entity types that match the specified filter.
Parameters
InFilter The filter to match allocations against. Filter is copied into the iterator.
OutMask The mask to receive the binary OR accumulation of all entities that pass the filter
AddChild()
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddChild (FMovieSceneEntityID ParentID, FMovieSceneEntityID ChildID)
Set up an entity to be a child of another.
Child entities will only be cleaned up if their parents are marked Unlink, and TagOrphanedChildren is called
Parameters
ParentID The ID of the parent
ChildID The ID of the child
AddComponent() [1/3]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID)
Add the specified component type to an entity.
The component value will be default-initialized.
Parameters
EntityID The ID of the entity to add the component to
ComponentTypeID The ID of the component type to add to the entity
AddComponent() [2/3]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID, EEntityRecursion Recursion)
AddComponent() [3/3]
template<typename T, typename ValueType> void UE::MovieScene::FEntityManager::AddComponent (FMovieSceneEntityID EntityID, TComponentTypeID< T > ComponentTypeID, ValueType && InValue) inline
Add the specified component value to an entity.
Parameters
EntityID The ID of the entity to add the component to
ComponentTypeID The ID of the component type to add to the entity
InValue The value of the component to add
Definition at line 234 of file MovieSceneEntityManager.h.
References AddComponent(), Component, Forward(), GetEntity(), and Header.
Referenced by AddComponent().
AddComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddComponents (FMovieSceneEntityID EntityID, const FComponentMask & EntityComponentMask)
Add the specified components to an entity.
Existing components will remain unchanged. New component values will be default-initialized.
Parameters
EntityID The ID of the entity to add the components to
EntityComponentMask A mask constituting the components that should be added (set bits indicate components to add)
AddComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddComponents (FMovieSceneEntityID EntityID, const FComponentMask & EntityComponentMask, EEntityRecursion Recursion)
AddEntityToAllocation()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::AddEntityToAllocation (int32 AllocationIndex, FMovieSceneEntityID ID, EMemoryType MemoryType = EMemoryType::DefaultConstructed) private
References DefaultConstructed, and ID.
AddMutualComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddMutualComponents ()
Run through all entities in this entity manager, ensuring that all mutual components exist.
AddMutualComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddMutualComponents (const FEntityComponentFilter & InFilter)
Run through all entities in this entity manager, ensuring that all mutual components exist for any component types that match the specified filter.
AddReferencedObjects()
MOVIESCENE_API void UE::MovieScene::FEntityManager::AddReferencedObjects (FReferenceCollector & ReferenceCollector)
Explicitly add referenced objects from an external source.
This is not called by default for the global entity manager because each entity owner should do so to avoid cyclic dependencies.
AllocateContiguousEntities()
MOVIESCENE_API FEntityDataLocation UE::MovieScene::FEntityManager::AllocateContiguousEntities (const FComponentMask & EntityComponentMask, int32 * InOutNum)
Attempt to allocate a number of entities of the same type contiguously in memory.
Note
May allocate fewer than the desired number due to allocation capacity constraints. As such, subsequent calls may be required.
Parameters
EntityComponentMask Defines the components that should exist on the allocated components. Set bits denote allocated components and tags.
InOutNum A valid pointer to the desired number to allocate. Is overwritten with the number that were actually allocated.
Returns
A structure that points to the first entity that was allocated.
AllocateEntity() [1/2]
MOVIESCENE_API FMovieSceneEntityID UE::MovieScene::FEntityManager::AllocateEntity ()
Allocate a new entity with no components.
Returns
A stable ID that relates to this entity. Will remain valid until the entity is freed
AllocateEntity() [2/2]
MOVIESCENE_API FEntityInfo UE::MovieScene::FEntityManager::AllocateEntity (const FComponentMask & EntityComponentMask)
Allocate a single entity with the specified components.
Parameters
EntityComponentMask Defines the components that should exist on the allocated components. Set bits denote allocated components and tags.
Returns
A structure that points to the allocated entity.
ChangeEntityType()
MOVIESCENE_API void UE::MovieScene::FEntityManager::ChangeEntityType (FMovieSceneEntityID InEntity, const FComponentMask & InNewMask)
Changes the components that exist on an entity to a new mask.
Parameters
InEntity The ID of the entity
InNewMask The new mask of the entity that defines which components it should have
CheckCanChangeStructure()
void UE::MovieScene::FEntityManager::CheckCanChangeStructure () const inline
Definition at line 764 of file MovieSceneEntityManager.h.
References checkf, IterationCount, LockdownState, TEXT, ThreadingModel, and Unlocked.
CheckInvariants()
MOVIESCENE_API void UE::MovieScene::FEntityManager::CheckInvariants () private
CombineAllocations()
MOVIESCENE_API void UE::MovieScene::FEntityManager::CombineAllocations (int32 DestinationIndex, int32 SourceIndex) private
CombineComponents()
MOVIESCENE_API void UE::MovieScene::FEntityManager::CombineComponents (FMovieSceneEntityID DestinationEntityID, FMovieSceneEntityID SourceEntityID, const FComponentMask * OptionalMask = nullptr)
Combine the components from one entity into another, overwriting any pre-existing component values.
Does not free any entities.
Parameters
DestinationEntityID The ID of the entity to add new components to
SourceEntityID The ID of the entity to copy components from
OptionalMask (Optional) A mask constituting the components that should be copied
Compact()
MOVIESCENE_API void UE::MovieScene::FEntityManager::Compact ()
Goes through all entity data and compacts like-for-like allocations into as few allocations as possible, resulting in the optimal data layout.
ComputeThreadingModel()
MOVIESCENE_API EEntityThreadingModel UE::MovieScene::FEntityManager::ComputeThreadingModel () const
Compute and return this entity manager's threading model.
Does not change the current cached threading model.
Contains()
MOVIESCENE_API bool UE::MovieScene::FEntityManager::Contains (const FEntityComponentFilter & InFilter) const
Efficiently test whether this entity manager contains any allocations that match the specified filter.
Parameters
InFilter The filter to match allocations against.
Returns
True if the entity manager contains any allocations that match the filter, false otherwise
ContainsAllComponents()
bool UE::MovieScene::FEntityManager::ContainsAllComponents (std::initializer_list< FComponentTypeID > ComponentTypeIDs) const inline
Check whether all of the specified components exist anywhere in this entity manager.
Note
: Does not check whether the components exist on the same entity, just that they are present in the manager. Use Contains for a thorough filter match.
Parameters
ComponentTypeIDs The types of the components that are being tested for
Returns
true if each of the specified components exist anywhere in this manager, false otherwise
Definition at line 733 of file MovieSceneEntityManager.h.
References Algo::AllOf(), GetAccumulatedMask(), and Mask.
ContainsAnyComponent() [1/2]
bool UE::MovieScene::FEntityManager::ContainsAnyComponent (const FComponentMask & ComponentTypeIDs) const inline
Check whether any entity in this manager has any of the specified components.
Parameters
ComponentTypeIDs The types of the component that are being tested for
Returns
true if any one of the specified components exist anywhere in this manager, false otherwise
Definition at line 720 of file MovieSceneEntityManager.h.
References UE::MovieScene::FComponentMask::BitwiseAND(), UE::MovieScene::FComponentMask::First(), GetAccumulatedMask(), UE::MovieScene::FComponentTypeID::Invalid(), Mask, and MinSize.
ContainsAnyComponent() [2/2]
bool UE::MovieScene::FEntityManager::ContainsAnyComponent (std::initializer_list< FComponentTypeID > ComponentTypeIDs) const inline
Check whether any entity in this manager has any of the specified components.
Parameters
ComponentTypeIDs The types of the component that are being tested for
Returns
true if any one of the specified components exist anywhere in this manager, false otherwise
Definition at line 708 of file MovieSceneEntityManager.h.
References Algo::AnyOf(), GetAccumulatedMask(), and Mask.
ContainsComponent()
bool UE::MovieScene::FEntityManager::ContainsComponent (FComponentTypeID ComponentTypeID) const inline
Check whether any entity in this manager has the specified component.
Parameters
ComponentTypeID The type of the component that is being tested for
Returns
true if the specified component exists anywhere, false otherwise
Definition at line 696 of file MovieSceneEntityManager.h.
References UE::MovieScene::FComponentMask::Contains(), and GetAccumulatedMask().
CopyComponent()
MOVIESCENE_API bool UE::MovieScene::FEntityManager::CopyComponent (FMovieSceneEntityID SrcEntityID, FMovieSceneEntityID DstEntityID, FComponentTypeID ComponentTypeID)
Copy the specified component type from an entity if it exists.
Parameters
SrcEntityID The ID of the entity to copy from
DstEntityID The ID of the entity to copy to
ComponentTypeID The ID of the component type to copy. Must exist on SrcEntityID
CopyComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::CopyComponents (FMovieSceneEntityID SrcEntityID, FMovieSceneEntityID DstEntityID, const FComponentMask & ComponentsToCopy)
Copy any and all the specified component types from one entity onto another.
Missing components on the source entity are handled gracefully.
Parameters
SrcEntityID The ID of the entity to copy from
DstEntityID The ID of the entity to copy to
ComponentsToCopy A mask constituting the components that should be copied (set bits indicate components to copy)
CopyComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::CopyComponents (int32 DestAllocationIndex, int32 DestEntityIndex, int32 SourceAllocationIndex, int32 SourceEntityIndex, const FComponentMask * OptionalMask = nullptr) private
CountMemory()
MOVIESCENE_API void UE::MovieScene::FEntityManager::CountMemory (FArchive & Ar, FMovieSceneEntityID EntityID)
Run a serialization routine over the specified entity to approximate the memory it is using.
Note
Does not consider per-allocation overhead such as header sizes and other per-allocation meta-data
Parameters
Ar The archive to save to. Ar.IsCountingMemory() must be true.
EntityID Identifier for the entity to replace object references within
References Ar.
CreateAllocationWithSlack()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::CreateAllocationWithSlack (const FComponentMask & EntityComponentMask, int32 * InOutDesiredSlack = nullptr) private
CreateEntityAllocation()
MOVIESCENE_API FEntityAllocation * UE::MovieScene::FEntityManager::CreateEntityAllocation (const FComponentMask & EntityComponentMask, uint16 InitialCapacity, uint16 MaxCapacity, FEntityAllocation * MigrateComponentDataFrom = nullptr) private
CreateEntityAllocationEntry()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::CreateEntityAllocationEntry (const FComponentMask & EntityComponentMask, uint16 InitialCapacity, uint16 MaxCapacity) private
DefineInstancedChildInitializer()
int32 UE::MovieScene::FEntityManager::DefineInstancedChildInitializer (TInlineValue< FChildEntityInitializer > && InInitializer) inline
Defines a new child initializer that applies only to entities factoried within this entity manager.
Parameters
InInitializer The initializer to insert
Returns
An index into the array of initializers that should be used for removal
Definition at line 381 of file MovieSceneEntityManager.h.
References check, InstancedChildInitializers, and MoveTemp().
Destroy()
MOVIESCENE_API void UE::MovieScene::FEntityManager::Destroy ()
Destroy this entity manager and all the entities and components contained within it, resetting it back to its default state.
DestroyAllocation()
MOVIESCENE_API void UE::MovieScene::FEntityManager::DestroyAllocation (FEntityAllocation * Allocation, bool bDestructComponentData = true) private
DestroyInstancedChildInitializer()
void UE::MovieScene::FEntityManager::DestroyInstancedChildInitializer (int32 Index) inline
Destroy a previously registered instanced child initializer using its index.
Definition at line 395 of file MovieSceneEntityManager.h.
References InstancedChildInitializers.
DuplicateEntity()
MOVIESCENE_API FMovieSceneEntityID UE::MovieScene::FEntityManager::DuplicateEntity (FMovieSceneEntityID InOther)
Duplicate an entity, by creating an exact copy with a new ID.
Parameters
InOther The ID of the entity to duplicate
Returns
An ID to a new entity that has exactly the same combination and value of components as InOther
EnterIteration()
MOVIESCENE_API void UE::MovieScene::FEntityManager::EnterIteration () const
Efficiently test whether this entity manager contains any allocations that match the specified filter.
Parameters
InFilter The filter to match allocations against.
Returns
True if the entity manager contains any allocations that match the filter, false otherwise
ExitIteration()
MOVIESCENE_API void UE::MovieScene::FEntityManager::ExitIteration () const
FilterComponents()
MOVIESCENE_API void UE::MovieScene::FEntityManager::FilterComponents (FMovieSceneEntityID EntityID, const FComponentMask & EntitiesToKeep)
Remove all but the specified components from an entity.
Parameters
EntityID The ID of the entity to remove the components from
EntitiesToKeep A mask constituting the components that should be kept on the entity
FindComponentTypeHandler()
MOVIESCENE_API IComponentTypeHandler * UE::MovieScene::FEntityManager::FindComponentTypeHandler (const FGuid & ComponentGuid) static
Find a component type hander from its registered GUID.
FreeEntities() [1/2]
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::FreeEntities (const FEntityComponentFilter & Filter, TSet< FMovieSceneEntityID > * OutFreedEntities = nullptr)
Free all entities that match the specified filter.
Parameters
Filter A filter that defines the entities to free. Any entity that passes the filter will be destroyed.
OutFreedEntities (Optional) A set to populate with all the entities that were freed (including any children)
Returns
The number of entities released
References Filter.
FreeEntities() [2/2]
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::FreeEntities (const FFreeEntityOperation & Operation, TSet< FMovieSceneEntityID > * OutFreedEntities = nullptr)
Free all entities defined by the specified operation.
Parameters
Operation A pre-populated free entity operation definition
OutFreedEntities (Optional) A set to populate with all the entities that were freed (including any children)
Returns
The number of entities released
References FFreeEntityOperation.
FreeEntity()
MOVIESCENE_API void UE::MovieScene::FEntityManager::FreeEntity (FMovieSceneEntityID EntityID)
Free an entity and relinquish its entity ID.
Parameters
EntityID A valid entity ID to free
Returns
The number of entities released
GetAccumulatedMask()
MOVIESCENE_API const FComponentMask & UE::MovieScene::FEntityManager::GetAccumulatedMask () const
Retrieve an up-to-date accumulation of all components present on entities in this manager.
Referenced by ContainsAllComponents(), ContainsAnyComponent(), ContainsAnyComponent(), and ContainsComponent().
GetAllocatedSize()
virtual SIZE_T UE::MovieScene::FEntityManager::GetAllocatedSize () const inline override private virtual
Returns the size of heap memory allocated internally by this listener.
Reimplemented from FUObjectArray::FUObjectDeleteListener.
Definition at line 915 of file MovieSceneEntityManager.h.
GetAllocation()
FEntityAllocation * UE::MovieScene::FEntityManager::GetAllocation (int32 AllocationIndex) const inline private
Definition at line 899 of file MovieSceneEntityManager.h.
References EntityAllocations.
GetChildren_ParentFirst()
MOVIESCENE_API void UE::MovieScene::FEntityManager::GetChildren_ParentFirst (FMovieSceneEntityID ParentID, TArray< FMovieSceneEntityID > & OutChildren) const
Retrieve all children, grandchildren etc of the specified entity using a parent first traversal.
Note
: the array will not be emptied by this function - that is the responsibility of the callee, if desired.
Parameters
ParentID The ID of the parent
OutChildren (out) Array to populate with child entities.
GetComponents()
FComponentRegistry * UE::MovieScene::FEntityManager::GetComponents () const inline
Definition at line 94 of file MovieSceneEntityManager.h.
References ComponentRegistry.
GetDispatchThread()
ENamedThreads::Type UE::MovieScene::FEntityManager::GetDispatchThread () const inline
Definition at line 549 of file MovieSceneEntityManager.h.
References DispatchThread.
GetEntity()
MOVIESCENE_API FEntityInfo UE::MovieScene::FEntityManager::GetEntity (FMovieSceneEntityID EntityID) const
Retrieve an entity's allocation and component offset from its ID.
Returns
A structure that points to the allocated entity.
Referenced by AddComponent().
GetEntityHandle()
MOVIESCENE_API FEntityHandle UE::MovieScene::FEntityManager::GetEntityHandle (FMovieSceneEntityID EntityID)
Retrieve a handle to an entity.
Returns
A handle that points to the allocated entity.
GetEntityType()
MOVIESCENE_API const FComponentMask & UE::MovieScene::FEntityManager::GetEntityType (FMovieSceneEntityID InEntity) const
Retrieve the type mask for this component.
Parameters
InEntity The ID of the entity
Returns
The type mask for this entity, or an empty mask if it has no components
GetGatherThread()
ENamedThreads::Type UE::MovieScene::FEntityManager::GetGatherThread () const inline
Definition at line 539 of file MovieSceneEntityManager.h.
References GatherThread.
GetGlobalIterationFilter()
const FEntityComponentFilter & UE::MovieScene::FEntityManager::GetGlobalIterationFilter () const inline
Retrieve the entity filter that should be used for any entity iteration.
Can be used to constrain all iterations to specific types
Definition at line 788 of file MovieSceneEntityManager.h.
References GlobalIterationFilter.
GetHandleGeneration()
uint32 UE::MovieScene::FEntityManager::GetHandleGeneration () const inline
Definition at line 863 of file MovieSceneEntityManager.h.
References bHandleGenerationStale, and CurrentHandleGeneration.
GetImmediateChildren()
MOVIESCENE_API void UE::MovieScene::FEntityManager::GetImmediateChildren (FMovieSceneEntityID ParentID, TArray< FMovieSceneEntityID > & OutChildren) const
Retrieve the immediate children of the specified entity.
Note
: the array will not be emptied by this function - that is the responsibility of the callee, if desired.
Parameters
ParentID The ID of the parent
OutChildren (out) Array to populate with child entities.
GetOrCreateAllocationWithSlack()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::GetOrCreateAllocationWithSlack (const FComponentMask & EntityComponentMask, int32 * InOutDesiredSlack = nullptr) private
GetReferencerName()
virtual MOVIESCENE_API FString UE::MovieScene::FEntityManager::GetReferencerName () const private virtual
GetSystemSerial()
uint64 UE::MovieScene::FEntityManager::GetSystemSerial () const inline
Get the current serial number for any system ovserving this entity manager.
This serial number acts as a timestamp for the current state of this entity manager - any serial number more recent than this dictates more recent logic or state.
Definition at line 817 of file MovieSceneEntityManager.h.
References SystemSerialNumber.
GetThreadingModel()
MOVIESCENE_API EEntityThreadingModel UE::MovieScene::FEntityManager::GetThreadingModel () const
Get this entitiy manager's current threading model based on the last time UpdateThreadingModel was called.
Referenced by ReadComponent(), and WriteComponent().
GrowAllocation()
MOVIESCENE_API FEntityAllocation * UE::MovieScene::FEntityManager::GrowAllocation (int32 AllocationIndex, int32 MinNumToGrowBy = 1) private
HasComponent()
MOVIESCENE_API bool UE::MovieScene::FEntityManager::HasComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID) const
Check whether the specified component has a component of the specified type.
Parameters
EntityID The ID of the entity to check
ComponentTypeID The type of the component that is being tested for
HasStructureChangedSince()
bool UE::MovieScene::FEntityManager::HasStructureChangedSince (uint64 CachedSerial) const inline
Check whether the structure of this entity manager has changed at all since the specified serial number.
Definition at line 825 of file MovieSceneEntityManager.h.
References StructureMutationSystemSerialNumber.
IncrementSystemSerial()
void UE::MovieScene::FEntityManager::IncrementSystemSerial (uint64 IncAmount = 1) inline
Increment the current serial number for systems observing this manager.
Should be called after any system is run
Definition at line 808 of file MovieSceneEntityManager.h.
References SystemSerialNumber.
InitializeChildAllocation()
MOVIESCENE_API void UE::MovieScene::FEntityManager::InitializeChildAllocation (const FComponentMask & ParentType, const FComponentMask & ChildType, const FEntityAllocation * ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets, const FEntityRange & InChildEntityRange)
Runs all initializers for the specified parent/child allocation.
IsAllocated()
bool UE::MovieScene::FEntityManager::IsAllocated (FMovieSceneEntityID EntityID) const inline
Check whether an entity is allocated.
Note
: does not check serial numbers - should only be used when you are certain that another entity can not have been allocated over the top of the specified entity ID
Returns
true if the entity ID is allocated, false otherwise
Definition at line 192 of file MovieSceneEntityManager.h.
References UE::MovieScene::FMovieSceneEntityID::AsIndex(), and EntityLocations.
IsHandleValid()
MOVIESCENE_API bool UE::MovieScene::FEntityManager::IsHandleValid (FEntityHandle EntityID) const
Check whether the specified entity handle is still valid.
Returns
true if the entity ID is allocated, false otherwise
IsLockedDown()
bool UE::MovieScene::FEntityManager::IsLockedDown () const inline
Definition at line 770 of file MovieSceneEntityManager.h.
References LockdownState, and Locked.
Referenced by ModifyGlobalIterationFilter().
Iterate()
MOVIESCENE_API FEntityAllocationIteratorProxy UE::MovieScene::FEntityManager::Iterate (const FEntityComponentFilter * InFilter) const
Iterate through all the allocations that match the specified component filter.
Parameters
InFilter (required, non-null) The filter to match allocations against. Filter is copied into the iterator.
Returns
An iterator object that walks over all allocations matching the filter.
References FEntityAllocationIteratorProxy.
IterateChildren_ParentFirst()
template<typename IteratorType> void UE::MovieScene::FEntityManager::IterateChildren_ParentFirst (FMovieSceneEntityID ParentID, IteratorType && Iterator) const inline
Iterate all children, grandchildren etc of the specified entity using a parent first traversal.
Parameters
ParentID The ID of the parent
OutChildren (out) Array to populate with child entities.
Definition at line 643 of file MovieSceneEntityManager.h.
References IterateChildren_ParentFirst(), and ParentToChild.
Referenced by IterateChildren_ParentFirst().
IterateImmediateChildren()
template<typename IteratorType> void UE::MovieScene::FEntityManager::IterateImmediateChildren (FMovieSceneEntityID ParentID, IteratorType && Iterator) const inline
Itereate the immediate children of the specified entity.
Note
: the array will not be emptied by this function - that is the responsibility of the callee, if desired.
Parameters
ParentID The ID of the parent
OutChildren (out) Array to populate with child entities.
Definition at line 627 of file MovieSceneEntityManager.h.
References ParentToChild.
LockDown()
void UE::MovieScene::FEntityManager::LockDown () inline
Definition at line 775 of file MovieSceneEntityManager.h.
References LockdownState, and Locked.
MigrateAllocation()
MOVIESCENE_API FEntityAllocation * UE::MovieScene::FEntityManager::MigrateAllocation (int32 AllocationIndex, const FComponentMask & NewComponentMask) private
MigrateEntity()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::MigrateEntity (int32 DestIndex, int32 SourceIndex, int32 SourceEntryIndexWithinAllocation) private
MimicStructureChanged()
void UE::MovieScene::FEntityManager::MimicStructureChanged () inline
Called in order to mimic the entity structure changing, even if it has not.
Definition at line 833 of file MovieSceneEntityManager.h.
References OnStructureChanged().
ModifyGlobalIterationFilter()
FEntityComponentFilter & UE::MovieScene::FEntityManager::ModifyGlobalIterationFilter () inline
Modify the entity filter that should be used for any entity iteration.
Note
: Care should be take to reset this back to its original state when done, as leaving this populated during the instantiation phase can result in undefined results.
Definition at line 799 of file MovieSceneEntityManager.h.
References ensureMsgf, GlobalIterationFilter, IsLockedDown(), IterationCount, TEXT, and ThreadingModel.
MutateAll()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::MutateAll (const FEntityComponentFilter & Filter, const IMovieSceneEntityMutation & Mutation, EMutuallyInclusiveComponentType MutualTypes = EMutuallyInclusiveComponentType::Mandatory)
Efficiently mutate all entities that match a filter.
Mutations can add or remove components from batches of entity data.
Parameters
Filter The filter to match entity allocations against. Only entities that match the filter will be mutated
Mutation Implementation that defines how to mutate the entities that match the filter
Returns
The number of entities that were mutated, or 0 if none were matched
References Filter.
MutateConditional()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::MutateConditional (const FEntityComponentFilter & Filter, const IMovieSceneConditionalEntityMutation & Mutation, EMutuallyInclusiveComponentType MutualTypes = EMutuallyInclusiveComponentType::Mandatory)
Efficiently mutate all entities that match a filter.
Mutations can add or remove components from batches of entity data.
Parameters
Filter The filter to match entity allocations against. Only entities that match the filter will be mutated
Mutation Implementation that defines how to mutate the entities that match the filter
Returns
The number of entities that were mutated, or 0 if none were matched
References Filter.
NotifyUObjectDeleted()
virtual MOVIESCENE_API void UE::MovieScene::FEntityManager::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) override private virtual
OnStructureChanged()
MOVIESCENE_API void UE::MovieScene::FEntityManager::OnStructureChanged () private
Referenced by MimicStructureChanged().
OnUObjectArrayShutdown()
virtual MOVIESCENE_API void UE::MovieScene::FEntityManager::OnUObjectArrayShutdown () override private virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Implements FUObjectArray::FUObjectDeleteListener.
operator=() [1/2]
void UE::MovieScene::FEntityManager::operator= (const FEntityManager &) delete
References FEntityManager().
operator=() [2/2]
void UE::MovieScene::FEntityManager::operator= (FEntityManager &&) delete
References FEntityManager().
OverwriteEntityWithDuplicate()
MOVIESCENE_API void UE::MovieScene::FEntityManager::OverwriteEntityWithDuplicate (FMovieSceneEntityID & InOutEntity, FMovieSceneEntityID InEntityToDuplicate)
Duplicate an entity over the top of an existing entity ID.
Parameters
InOutEntity The ID of the entity to overwrite. Doesn't have to be valid.
InEntityToDuplicate The ID of the entity to duplicate
ReadComponent()
template<typename T> TComponentLock< TReadOptional< T > > UE::MovieScene::FEntityManager::ReadComponent (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID) const inline
Attempt to read a component from an entity.
Note
this is a general purpose convenience utility which should not be used for high-performance runtime code. See FEntityTaskBuilder.
Parameters
Entity The ID of the entity to read from
ComponentTypeID The component that is to be read
Returns
A scoped component ptr that points directly to the entity's component, or nullptr if it does not exist
Definition at line 422 of file MovieSceneEntityManager.h.
References UE::MovieScene::FMovieSceneEntityID::AsIndex(), check, EntityAllocationMasks, EntityAllocations, EntityLocations, GetThreadingModel(), Header, Location, and UE::MovieScene::NoThreading.
Referenced by ReadComponentChecked().
ReadComponentChecked()
template<typename T> T UE::MovieScene::FEntityManager::ReadComponentChecked (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID) const inline
Read a component value from an entity that is known to exist.
Note
this is a general purpose convenience utility which should not be used for high-performance runtime code. See FEntityTaskBuilder.
Parameters
Entity The ID of the entity to read from
ComponentTypeID The component that is to be read
Returns
The component value
Definition at line 465 of file MovieSceneEntityManager.h.
References check, ReadComponent(), and Value.
ReleaseLockDown()
void UE::MovieScene::FEntityManager::ReleaseLockDown () inline
Definition at line 780 of file MovieSceneEntityManager.h.
References LockdownState, and Unlocked.
RemoveComponent() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::RemoveComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID)
Remove the specified component type from an entity if it exists.
Parameters
EntityID The ID of the entity to remove the component from
ComponentTypeID The ID of the component type to remove from the entity
RemoveComponent() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::RemoveComponent (FMovieSceneEntityID EntityID, FComponentTypeID ComponentTypeID, EEntityRecursion Recursion)
RemoveComponents() [1/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::RemoveComponents (FMovieSceneEntityID EntityID, const FComponentMask & ComponentsToRemove)
Remove the specified components from an entity, if they exist.
Parameters
EntityID The ID of the entity to remove the components from
ComponentsToRemove A mask constituting the components that should be removed (set bits indicate components to add)
RemoveComponents() [2/2]
MOVIESCENE_API void UE::MovieScene::FEntityManager::RemoveComponents (FMovieSceneEntityID EntityID, const FComponentMask & ComponentsToRemove, EEntityRecursion Recursion)
RemoveEntityFromAllocation()
MOVIESCENE_API void UE::MovieScene::FEntityManager::RemoveEntityFromAllocation (int32 AllocationIndex, int32 SourceEntryIndexWithinAllocation) private
ReplaceEntityID()
MOVIESCENE_API void UE::MovieScene::FEntityManager::ReplaceEntityID (FMovieSceneEntityID & InOutEntity, FMovieSceneEntityID EntityToDiscard)
Replace an entity ID with the components from another, discarding the provided entity ID in the process.
Parameters
InOutEntity The entity ID to be reassigned. If it is already valid, the existing entity will be freed
EntityToDiscard The entity containing the components to replace InOutEntity with. This Entity ID will be invalid after this function call.
ReserveAllocation()
MOVIESCENE_API int32 UE::MovieScene::FEntityManager::ReserveAllocation (int32 AllocationIndex, int32 NumToReserve) private
SetComponentRegistry()
void UE::MovieScene::FEntityManager::SetComponentRegistry (FComponentRegistry * InComponents) inline
Definition at line 99 of file MovieSceneEntityManager.h.
References ComponentRegistry.
SetDebugName()
void UE::MovieScene::FEntityManager::SetDebugName (FString && InNewDebugName) inline
Set a debug name for this entity manager.
Definition at line 843 of file MovieSceneEntityManager.h.
References ManagerDebugName, and MoveTemp().
SetDispatchThread()
void UE::MovieScene::FEntityManager::SetDispatchThread (ENamedThreads::Type InDispatchThread) inline
Definition at line 544 of file MovieSceneEntityManager.h.
References DispatchThread.
SetGatherThread()
void UE::MovieScene::FEntityManager::SetGatherThread (ENamedThreads::Type InGatherThread) inline
Definition at line 534 of file MovieSceneEntityManager.h.
References GatherThread.
TouchEntity()
MOVIESCENE_API void UE::MovieScene::FEntityManager::TouchEntity (FMovieSceneEntityID EntityID)
Touch the specified entity, cause the allocation and component serial numbers to be incremented.
Will invalidate any transient caches maintained for serial such numbers.
Note
Allocation and component serial numbers relate to the entire allocation of entities that this entity resides within. As such, it will invalidate downstream caches for any cache that relates to the entire allocation
Parameters
EntityID The ID of the entity to touch.
UpdateThreadingModel()
MOVIESCENE_API void UE::MovieScene::FEntityManager::UpdateThreadingModel ()
Compute and store the current threading model.
WriteComponent()
template<typename T> TComponentLock< TWriteOptional< T > > UE::MovieScene::FEntityManager::WriteComponent (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID) inline
Attempt to write to an entity's component.
Note
this is a general purpose convenience utility which should not be used for high-performance runtime code. See FEntityTaskBuilder.
Parameters
Entity The ID of the entity to read from
ComponentTypeID The component that is to be read
Returns
A scoped component ptr that points directly to the entity's component, or nullptr if it does not exist
Definition at line 482 of file MovieSceneEntityManager.h.
References UE::MovieScene::FMovieSceneEntityID::AsIndex(), check, EntityAllocationMasks, EntityAllocations, EntityLocations, GetThreadingModel(), Header, Location, and UE::MovieScene::NoThreading.
Referenced by WriteComponentChecked().
WriteComponentChecked()
template<typename T, typename ValueType> void UE::MovieScene::FEntityManager::WriteComponentChecked (FMovieSceneEntityID Entity, TComponentTypeID< T > ComponentTypeID, ValueType && Value) inline
Write a component value that is known to exist to an entity.
Note
this is a general purpose convenience utility which should not be used for high-performance runtime code. See FEntityTaskBuilder.
Parameters
Entity The ID of the entity to read from
ComponentTypeID The component that is to be read
Value The value to write
Definition at line 525 of file MovieSceneEntityManager.h.
References check, Forward(), Value, and WriteComponent().
Friends And Related Symbol Documentation
FEntityAllocationIterator
friend struct FEntityAllocationIterator friend
Definition at line 921 of file MovieSceneEntityManager.h.
References FEntityAllocationIterator.
Referenced by FEntityAllocationIterator.
FEntityAllocationIteratorProxy
friend struct FEntityAllocationIteratorProxy friend
Definition at line 922 of file MovieSceneEntityManager.h.
References FEntityAllocationIteratorProxy.
Referenced by FEntityAllocationIteratorProxy, and Iterate().
FEntityAllocationProxy
friend struct FEntityAllocationProxy friend
Definition at line 920 of file MovieSceneEntityManager.h.
References FEntityAllocationProxy.
Referenced by FEntityAllocationProxy.
FEntityInitializer
friend struct FEntityInitializer friend
Definition at line 874 of file MovieSceneEntityManager.h.
References FEntityInitializer.
Referenced by FEntityInitializer.
Field Documentation
AccumulatedMask
FComponentMask UE::MovieScene::FEntityManager::AccumulatedMask private
Definition at line 1000 of file MovieSceneEntityManager.h.
AllocationsWithCapacity
TBitArray UE::MovieScene::FEntityManager::AllocationsWithCapacity private
Bit mask of allocations that currently have capacity.
Definition at line 984 of file MovieSceneEntityManager.h.
bAccumulatedMaskStale
bool UE::MovieScene::FEntityManager::bAccumulatedMaskStale mutable private
Definition at line 1025 of file MovieSceneEntityManager.h.
bHandleGenerationStale
bool UE::MovieScene::FEntityManager::bHandleGenerationStale mutable private
Definition at line 1024 of file MovieSceneEntityManager.h.
Referenced by GetHandleGeneration().
ComponentRegistry
FComponentRegistry* UE::MovieScene::FEntityManager::ComponentRegistry private
Definition at line 1003 of file MovieSceneEntityManager.h.
Referenced by GetComponents(), and SetComponentRegistry().
CurrentHandleGeneration
uint32 UE::MovieScene::FEntityManager::CurrentHandleGeneration mutable private
The current generation of entities - incremented any time an entity is destroyed.
Definition at line 1023 of file MovieSceneEntityManager.h.
Referenced by GetHandleGeneration().
DispatchThread
ENamedThreads::Type UE::MovieScene::FEntityManager::DispatchThread private
Definition at line 1031 of file MovieSceneEntityManager.h.
Referenced by GetDispatchThread(), and SetDispatchThread().
EntityAllocationMasks
TSparseArray<FComponentMask> UE::MovieScene::FEntityManager::EntityAllocationMasks private
Sparse array of masks that define each index within EntityAllocations' component types.
Definition at line 981 of file MovieSceneEntityManager.h.
Referenced by ReadComponent(), and WriteComponent().
EntityAllocations
TSparseArray<FEntityAllocation*> UE::MovieScene::FEntityManager::EntityAllocations private
Sparse array of entity allocation pointers.
Allocations are heap allocated.
Definition at line 987 of file MovieSceneEntityManager.h.
Referenced by GetAllocation(), ReadComponent(), and WriteComponent().
EntityGenerationMap
TMap<FMovieSceneEntityID, uint32> UE::MovieScene::FEntityManager::EntityGenerationMap private
Map of entity ID to the generation its handle was created in.
FEntityHandle::HandleGeneration matches the value if it is still valid
Definition at line 998 of file MovieSceneEntityManager.h.
EntityLocations
TSparseArray<FEntityLocation> UE::MovieScene::FEntityManager::EntityLocations private
Sparse array of entity location information for each allocated entity ID.
Definition at line 990 of file MovieSceneEntityManager.h.
Referenced by IsAllocated(), ReadComponent(), and WriteComponent().
FFreeEntityOperation
friend UE::MovieScene::FEntityManager::FFreeEntityOperation private
Definition at line 924 of file MovieSceneEntityManager.h.
Referenced by FreeEntities().
GatherThread
ENamedThreads::Type UE::MovieScene::FEntityManager::GatherThread private
Definition at line 1030 of file MovieSceneEntityManager.h.
Referenced by GetGatherThread(), and SetGatherThread().
GlobalIterationFilter
FEntityComponentFilter UE::MovieScene::FEntityManager::GlobalIterationFilter private
Definition at line 1001 of file MovieSceneEntityManager.h.
Referenced by GetGlobalIterationFilter(), and ModifyGlobalIterationFilter().
InstancedChildInitializers
TSparseArray<TInlineValue<FChildEntityInitializer> > UE::MovieScene::FEntityManager::InstancedChildInitializers private
Definition at line 995 of file MovieSceneEntityManager.h.
Referenced by DefineInstancedChildInitializer(), and DestroyInstancedChildInitializer().
IterationCount
FEntitySystemMaybeAtomicInt32 UE::MovieScene::FEntityManager::IterationCount mutable private
Atomic counter that is incremented when an iteration begins, and decremented when it finishes.
Definition at line 1028 of file MovieSceneEntityManager.h.
Referenced by CheckCanChangeStructure(), and ModifyGlobalIterationFilter().
LockdownState
ELockdownState UE::MovieScene::FEntityManager::LockdownState private
Definition at line 1039 of file MovieSceneEntityManager.h.
Referenced by CheckCanChangeStructure(), IsLockedDown(), LockDown(), and ReleaseLockDown().
ManagerDebugName
FString UE::MovieScene::FEntityManager::ManagerDebugName private
Debug name for this entity manager.
Definition at line 1006 of file MovieSceneEntityManager.h.
Referenced by SetDebugName().
NextAllocationID
uint32 UE::MovieScene::FEntityManager::NextAllocationID private
Debugging ptr for natvis.
Serially incrementing unique identifier that is assigned to each new entity allocation that is created
Definition at line 1020 of file MovieSceneEntityManager.h.
ParentToChild
TMultiMap<FMovieSceneEntityID, FMovieSceneEntityID> UE::MovieScene::FEntityManager::ParentToChild private
Map of parent -> child entities.
Definition at line 993 of file MovieSceneEntityManager.h.
Referenced by IterateChildren_ParentFirst(), and IterateImmediateChildren().
StructureMutationSystemSerialNumber
uint64 UE::MovieScene::FEntityManager::StructureMutationSystemSerialNumber private
The value of this manager's SystemSerialNumber the last time any entities were allocated, freed, or mutated in some way (this does not include component values being written to)
Definition at line 1012 of file MovieSceneEntityManager.h.
Referenced by HasStructureChangedSince().
SystemSerialNumber
uint64 UE::MovieScene::FEntityManager::SystemSerialNumber private
System serial number incremented for every run of any system.
Definition at line 1009 of file MovieSceneEntityManager.h.
Referenced by GetSystemSerial(), and IncrementSystemSerial().
ThreadingModel
EEntityThreadingModel UE::MovieScene::FEntityManager::ThreadingModel private
Definition at line 1032 of file MovieSceneEntityManager.h.
Referenced by CheckCanChangeStructure(), and ModifyGlobalIterationFilter().
The documentation for this class was generated from the following file:
MovieSceneEntityManager.h