Unreal Engine 5.6 C++ API: FGenericPlatformMisc Struct Reference
FGenericPlatformMisc Struct Reference
Generic implementation for most platforms.
#include "GenericPlatformMisc.h"
Public Member Functions
UE_DEPRECATED (4.14, "GetHasedMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetHashedMacAddressString()
Retrieve the Mac address of the current adapter as a hashed string (privacy).
UE_DEPRECATED (4.14, "GetMacAddress is deprecated. It is not reliable on all platforms") static 1 TArray< uint8 > GetMacAddress()
Retrieve the Mac address of the current adapter.
UE_DEPRECATED (4.14, "GetMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetMacAddressString()
Retrieve the Mac address of the current adapter as a string.
UE_DEPRECATED (4.14, "GetMachineId is deprecated. Use GetLoginId instead.") static 1 FGuid GetMachineId()
Get (or create) the unique ID used to identify this computer.
UE_DEPRECATED (4.18, "FPaths::SetOverrideGameDir() has been superseded by FPaths::SetOverrideProjectDir().") static FORCEINLINE void SetOverrideGameDir(const FString &InOverrideDir)
UE_DEPRECATED (4.19, "FPlatformMisc::DebugBreak is deprecated. Use the UE_DEBUG_BREAK() macro instead.") FORCEINLINE static void DebugBreak()
Break into the debugger, if IsDebuggerPresent returns true, otherwise do nothing.
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static 1 void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrientation)
Change the orientation of the device.
UE_DEPRECATED (5.2, "Must supply size when prefetching a block of data") FORCEINLINE static void PrefetchBlock(const void *Ptr)
Static Public Member Functions
static void AddAdditionalRootDirectory (const FString &RootDir)
add an additional root directory
static FDelegateHandle AddNetworkListener (FOnNetworkConnectionChangedDelegate &&InNewDelegate)
static bool AllowAudioThread ()
Checks if platform wants to allow an audio thread on current device (note: does not imply it will, only if okay given other criteria met)
static bool AllowLocalCaching ()
static bool AllowThreadHeartBeat ()
Checks if platform wants to allow the thread heartbeat hang detection.
static void BeginEnterBackgroundEvent (const TCHAR *Text)
Profiler enter background events.
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const ANSICHAR *Text)
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const TCHAR *Text)
static FORCEINLINE void BeginNamedEventFrame ()
static void CacheLaunchDir ()
Function to store the current working directory for use with LaunchDir()
static bool CheckPersistentDownloadStorageSpaceAvailable (uint64 BytesRequired, bool bAttemptToUseUI)
Ensure that there enough space in the persistent download dir.
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static FString CloudDir ()
Return the CloudDir.
static bool CommandLineCommands ()
Handles Game Explorer, Firewall and FirstInstall commands, typically from the installer.
static void CreateGuid (struct FGuid &Result)
Create a new globally unique identifier.
static FORCEINLINE void CustomNamedStat (const ANSICHAR *Text, float Value, const ANSICHAR *Graph, const ANSICHAR *Unit)
static FORCEINLINE void CustomNamedStat (const TCHAR *Text, float Value, const TCHAR *Graph, const TCHAR *Unit)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
Deletes the given section and its contained values in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
Deletes value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DesktopTouchScreen ()
static void DisableScreenTimeout ()
static void EnableScreenTimeout ()
static void EndEnterBackgroundEvent ()
static FORCEINLINE void EndNamedEvent ()
static const TCHAR * EngineDir ()
Get the engine directory.
static void EnsureNetworkIfNecessary ()
static bool Exec (class UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Out)
Platform-specific Exec function.
static FORCEINLINE bool Expand16BitIndicesTo32BitOnLoad ()
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static bool FullscreenSameAsWindowedFullscreen ()
static const TCHAR * GamePersistentDownloadDir ()
Return the GamePersistentDownloadDir.
static const TCHAR * GameTemporaryDownloadDir ()
Return the temporary directory.
static const TCHAR * GeneratedConfigDir ()
static TArray< FString > GetAdditionalRootDirectories ()
get additional directories which can be considered as root directories
static EDeviceScreenOrientation GetAllowedDeviceOrientation ()
Returns the allowed orientation of the device.
static FORCEINLINE int GetBatteryLevel ()
Gets the current battery level.
static bool GetBlockingIOStats (FProcessIOStats &OutStats, EInputOutputFlags Flags=EInputOutputFlags::All)
Gets Blocking Input/Output stats covering the lifetime of the process.
static FORCEINLINE float GetBrightness ()
static FORCEINLINE int32 GetChunkIDFromPakchunkIndex (int32 PakchunkIndex)
static const FString * GetConfigRulesVariable (const FString &Key)
static const class TMap< FString, FString > & GetConfigRuleVars ()
static bool GetContextSwitchStats (FContextSwitchStats &OutStats, EContextSwitchFlags Flags=EContextSwitchFlags::All)
Gets Context Switch stats covering the lifetime of the process.
static EConvertibleLaptopMode GetConvertibleLaptopMode ()
Gets the current mode of convertible laptops, i.e.
static FString GetCPUBrand ()
Uses cpuid instruction to get the CPU brand string.
static FString GetCPUChipset ()
Returns the CPU chipset if known.
static uint32 GetCPUInfo ()
On x86(-64) platforms, uses cpuid instruction to get the CPU signature.
static FString GetCPUVendor ()
Uses cpuid instruction to get the vendor string.
static ECrashHandlingType GetCrashHandlingType ()
Gets the current crash handling type.
static const TCHAR * GetDefaultDeviceProfileName ()
Gets the default profile name.
static FString GetDefaultLanguage ()
Get the default language (for localization) used by this platform.
static FString GetDefaultLocale ()
Get the default locale (for internationalization) used by this platform.
static const TCHAR * GetDefaultPathSeparator ()
static FString GetDeviceId ()
Returns a unique string for device identification.
static FString GetDeviceMakeAndModel ()
static EDeviceScreenOrientation GetDeviceOrientation ()
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
static FString GetDeviceTag ()
Get Device Tag of the device running the session.
static float GetDeviceTemperatureLevel ()
Returns the current device temperature level.
static int32 GetDeviceVolume ()
Returns the device volume if the device is capable of returning that information.
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
Retrieves information about the total number of bytes and number of free bytes for the specified disk path.
static bool GetEngineAndProjectAbsoluteDirsFromExecutable (FString &OutProjectDir, FString &OutEngineDir)
Return the engine and project directory based from the executable.
static const TCHAR * GetEngineMode ()
Get a string description of the mode the engine was running in.
static FString GetEnvironmentVariable (const TCHAR *VariableName)
Retrieve a environment variable from the system.
static FString GetEpicAccountId ()
Get the Epic account ID for the user who last used the Launcher.
static FText GetFileManagerName ()
static struct FGPUDriverInfo GetGPUDriverInfo (const FString &DeviceDescription)
static FString GetHostArchitecture ()
static FORCEINLINE uint32 GetLastError ()
static FString GetLocalCurrencyCode ()
Returns the currency code associated with the device's locale.
static FString GetLocalCurrencySymbol ()
Returns the currency symbol associated with the device's locale.
static FString GetLoginId ()
Returns a unique string associated with the login account of the current machine.
static FORCEINLINE int32 GetMaxPathLength ()
Returns the maximum length of a path.
static int32 GetMaxRefreshRate ()
retrieves the current maximum refresh rate supported by the platform
static int32 GetMaxSupportedRefreshRate ()
retrieves the maximum refresh rate supported by the platform
static int32 GetMaxSyncInterval ()
Returns the platform's maximum allowed value for rhi.SyncInterval.
static int GetMobilePropagateAlphaSetting ()
static ENetworkConnectionStatus GetNetworkConnectionStatus ()
Returns the current status for the network connection.
static ENetworkConnectionType GetNetworkConnectionType ()
Returns whether WiFi connection is currently active.
static FORCEINLINE void GetNetworkFileCustomData (TMap< FString, FString > &OutCustomPlatformData)
Returns any platform-specific key-value data that needs to be sent to the network file server.
static const TCHAR * GetNullRHIShaderFormat ()
Determines the shader format for the platform.
static FString GetOperatingSystemId ()
Gets a globally unique ID the represents a particular operating system install.
static FString GetOSVersion ()
Gets a string representing the numeric OS version (as opposed to a translated OS version that GetOSVersions returns).
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
Gets the OS Version and OS Subversion.
static bool GetPageFaultStats (FPageFaultStats &OutStats, EPageFaultFlags Flags=EPageFaultFlags::All)
Gets Page Fault stats covering the lifetime of the process.
static int32 GetPakchunkIndexFromPakFile (FStringView InFilename)
static FStringView GetPakFilenamePrefix ()
static const TCHAR * GetPathVarDelimiter ()
return the delimiter between paths in the PATH environment variable.
static FString GetPendingActivationProtocol ()
Returns activation protocol that's waiting to be broadcast.
static IPlatformChunkInstall * GetPlatformChunkInstall ()
Returns the platform specific chunk based install interface.
static IPlatformCompression * GetPlatformCompression ()
Returns the platform specific compression interface.
static const TCHAR * GetPlatformFeaturesModuleName ()
Return the name of the platform features module.
static IPlatformHostCommunication & GetPlatformHostCommunication ()
Returns the platform specific interface for communication with processes running on the host pc.
static bool GetPlatformScreenWarnings (TArray< FText > &PlatformScreenWarnings)
Returns any platform specific warning messages we want printed on screen.
static struct FAsyncIOSystemBase * GetPlatformSpecificAsyncIOSystem ()
Return the platform specific async IO system, or nullptr if the standard one should be used.
static FPlatformUserId GetPlatformUserForUserIndex (int32 LocalUserIndex)
static TArray< FString > GetPreferredLanguages ()
Returns an array of the user's preferred languages in order of preference.
static FString GetPrimaryGPUBrand ()
static EProcessDiagnosticFlags GetProcessDiagnostics ()
Returns non-zero if a performance-sensitive diagnostic, like a memory sanitizer, is detected for this process.
static const FProcessorGroupDesc & GetProcessorGroupDesc ()
static bool GetSHA256Signature (const void *Data, uint32 ByteSize, FSHA256Signature &OutSignature)
Generates the SHA256 signature of the given data.
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
Get the value for the given section and key from the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
Returns the last system error code in string form.
static TArray< uint8 > GetSystemFontBytes ()
static FString GetTimeZoneId ()
Get the timezone identifier for this platform, or an empty string if the default timezone calculation will work.
static const TCHAR * GetUBTPlatform ()
static const TCHAR * GetUBTTarget ()
static const TCHAR * GetUBTTargetName ()
static FString GetUniqueAdvertisingId ()
Returns a unique string for advertising identification.
static int32 GetUserIndexForPlatformUser (FPlatformUserId PlatformUser)
static bool GetUseVirtualJoysticks ()
Returns whether the platform wants to use a touch screen for virtual joysticks.
static void GetValidTargetPlatforms (TArray< FString > &TargetPlatformNames)
Return an ordered list of target platforms this runtime can support (ie Android_DXT, Android would mean that it prefers Android_DXT, but can use Android as well)
static const float GetVirtualKeyboardInputHeight ()
static bool GetVolumeButtonsHandledBySystem ()
static bool HasActiveWiFiConnection ()
Returns whether WiFi connection is currently active.
static bool HasMemoryWarningHandler ()
Determines if a warning handler has been set.
static bool HasNonoptionalCPUFeatures ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
Returns whether the given platform feature is currently available (for instance, Metal is only available in IOS8 and with A7 devices)
static bool HasProjectPersistentDownloadDir ()
Return true if the PersistentDownloadDir is available.
static bool HasSeparateChannelForDebugOutput ()
Whether the platform has a separate debug channel to stdout (eg.
static bool HasVariableHardware ()
Returns whether the platform has variable hardware (configurable/upgradeable system).
static void HidePlatformStartupScreen ()
static FORCEINLINE void InitTaggedStorage (uint32 NumTags)
Platform specific function for initializing storage of tagged memory buffers.
static FORCEINLINE bool Is64bitOperatingSystem ()
Detects whether we're running in a 64-bit operating system.
static bool IsCacheStorageAvailable ()
For platforms that support cache storage functionality, setting a directory for it when it's not available can result in errors.
static FORCEINLINE bool IsDebuggerPresent ()
Return true if a debugger is present.
static bool IsEnsureAllowed ()
Allows disabling ensure()s without rebuilding the binary, by either a commandline switch or a hotfix.
static FORCEINLINE bool IsInLowPowerMode ()
static bool IsLocalPrintThreadSafe ()
Whether LocalPrint can be called from any thread without overlapping.
static bool IsLowLevelOutputDebugStringStructured ()
Whether LowLevelOutputDebugString[f] can receive structured output as lines of JSON.
static bool IsPackagedForDistribution ()
static bool IsPGIActive ()
Returns true if PGI (profile-guided instrumentation, needed for PGO) is currently ongoing.
static bool IsPGICapableBinary ()
Returns true if this binary has been instrumented for collection of data needed for profile-guided optimization (PGO) This value is not expected to change during the run-time.
static bool IsPGOEnabled ()
Returns true if PGO is currently enabled.
static bool IsRegisteredForRemoteNotifications ()
Returns whether or not the device has been registered to receive remote notifications.
static bool IsRemoteSession ()
Check to see if the platform is being viewed remotely.
static bool IsRunningInCloud ()
Return if the game is running on cloud server.
static bool IsRunningOnBattery ()
Returns whether the platform is running on battery power or not.
static bool IsValidAbsolutePathFormat (const FString &Path)
Checks structure of the path against platform formatting requirements.
static const TCHAR * LaunchDir ()
Get the directory the application was launched from (useful for commandline utilities)
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
Loads a text file relative to the package root on platforms that distribute apps in package formats.
static void LocalPrint (const TCHAR *Str)
Prints string to the default output.
static void LogNameEventStatsInit ()
static void LowLevelOutputDebugString (const TCHAR *Message)
Sends a message to a remote tool, and debugger consoles.
static void VARARGS LowLevelOutputDebugStringf (const TCHAR *Format,...)
static FORCENOINLINE void MemoryBarrier ()
Enforces strict memory load/store ordering across the memory barrier call.
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
Show a message box if possible, otherwise print a message and return the default.
static bool NeedsNonoptionalCPUFeaturesCheck ()
static void NormalizePath (FString &InPath)
Platform-specific normalization of path E.g.
static void NormalizePath (FStringBuilderBase &InPath)
Platform-specific normalization of path E.g.
static int32 NumberOfCores ()
return the number of hardware CPU cores
static int32 NumberOfCoresIncludingHyperthreads ()
return the number of logical CPU cores
static int32 NumberOfIOWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn to service IO, NOT based on number of cores.
static int32 NumberOfWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn, based on number of cores.
static bool OsExecute (const TCHAR *CommandType, const TCHAR *Command, const TCHAR *CommandLine=NULL)
Has the OS execute a command and path pair (such as launch a browser)
static void ParseChunkIdPakchunkIndexMapping (TArray< FString > ChunkIndexRedirects, TMap< int32, int32 > &OutMapping)
static void PlatformHandleSplashScreen (bool ShowSplashScreen=false)
Called to dismiss splash screen.
static void PlatformInit ()
static void PlatformPreInit ()
Called during appInit() after cmd line setup.
static void PlatformTearDown ()
Called during AppExit().
static FORCEINLINE void Prefetch (const void *Ptr)
static FORCEINLINE void Prefetch (const void *Ptr, int32 Offset)
static FORCEINLINE void PrefetchBlock (const void *Ptr, int32 NumBytes)
static void PrepareMobileHaptics (EMobileHapticsType Type)
For mobile devices, this will crank up a haptic engine for the specified type to be played later with TriggerMobileHaptics If this is called again before Release, it will switch to this type.
static const TCHAR * ProjectDir ()
Return the project directory.
static void PromptForRemoteDebugging (bool bIsEnsure)
static void PumpEssentialAppMessages ()
Pumps app messages only if there are essential keep-alive messages pending.
static void PumpMessagesForSlowTask ()
static void PumpMessagesOutsideMainLoop ()
static void RaiseException (uint32 ExceptionCode)
static void RegisterForRemoteNotifications ()
Requests permission to send remote notifications to the user's device.
static void ReleaseMobileHaptics ()
For mobile devices, this will shutdown the haptics, allowing system to put it to reset as needed.
static bool RemoveNetworkListener (FDelegateHandle Handle)
static bool RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
Requests application exit.
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
Requests application exit with a specified return code.
static bool RestartApplication ()
Requests application to restart.
static bool RestartApplicationWithCmdLine (const char *CmdLine)
Requests application to restart appending the passed in CmdLine to the restart.
static const TCHAR * RootDir ()
Get the application root directory.
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
Change the allowed orientation of the device.
static FORCEINLINE void SetBrightness (float bBright)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
Installs handler for the unexpected (due to error) termination of the program, including, but not limited to, crashes.
static ECrashHandlingType SetCrashHandlingType (ECrashHandlingType Type)
Sets the type of crash handling done by the engine.
static void SetEnvironmentVar (const TCHAR *VariableName, const TCHAR *Value)
Sets an environment variable to the local process's environment.
static void SetGracefulTerminationHandler ()
Set/restore the Console Interrupt (Control-C, Control-Break, Close) handler.
static void SetLastError (uint32 ErrorCode)
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
Set a handler to be called when there is a memory warning from the OS.
static void SetNetworkConnectionStatus (ENetworkConnectionStatus NewNetworkConnectionStatus)
Updates the current status for the network connection.
static void SetOverrideProjectDir (const FString &InOverrideDir)
Allows a game/program/etc to control the game directory in a special place (for instance, monolithic programs that don't have .uprojects)
static void SetShouldPromptForRemoteDebugging (bool bInShouldPrompt)
static void SetShouldPromptForRemoteDebugOnEnsure (bool bInShouldPrompt)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool SetStoredValues (const FString &InStoreId, const FString &InSectionName, const TMap< FString, FString > &InKeyValues)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static void SetUBTTargetName (const TCHAR *InTargetName)
static bool SetupSyscallFilters ()
static void SetUTF8Output ()
Sets the default output to UTF8.
static void SetVolumeButtonsHandledBySystem (bool enabled)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
Perform a mobile-style sharing of a URL.
static bool ShouldDisablePluginAtRuntime (const FString &PluginName)
Allows platform at runtime to disable unsupported plugins.
static bool ShouldDisplayTouchInterfaceOnFakingTouchEvents ()
static void ShowConsoleWindow ()
static FORCEINLINE void ShutdownTaggedStorage ()
Platform specific function for freeing storage of tagged memory buffers.
static bool StartNewPGOCollection (const FString &AbsoluteFileName)
On platforms that support run-time PGI on/off, starts a new collection with a given file name.
template<typename CharType>
static void StatNamedEvent (const CharType *Text)
Stats logging for named event.
static bool StopPGOCollectionAndCloseFile ()
On platforms that support run-time PGI on/off, stops the current collection and writes out the file (or completes its write).
static void SubmitErrorReport (const TCHAR *InErrorHist, EErrorReportMode::Type InMode)
Submits a crash report to a central server (release builds only)
static FORCEINLINE bool SupportsBackbufferSampling ()
static FORCEINLINE bool SupportsBrightness ()
static bool SupportsDeviceCheckToken ()
static bool SupportsForceTouchInput ()
static bool SupportsFullCrashDumps ()
Platform can generate a full-memory crashdump during crash handling.
static bool SupportsLocalCaching ()
static bool SupportsMessaging ()
static bool SupportsMultithreadedFileHandles ()
static bool SupportsTouchInput ()
static FORCEINLINE void TagBuffer (const char *Label, uint32 Category, const void *Buffer, size_t BufferSize)
Platform specific function for tagging a memory buffer with a label.
static void TearDown ()
Frees any memory retained by FGenericPlatformMisc.
static void TickHotfixables ()
Ticks values that can be hotfixable in the config.
static void TickStatNamedEvents ()
static void TriggerMobileHaptics ()
For mobile devices, this will kick the haptic type that was set in PrepareMobileHaptics.
static void UnregisterForRemoteNotifications ()
Requests unregistering from receiving remote notifications on the user's device.
static void UpdateHotfixableEnsureSettings ()
Updates hotfixable ensure settings from config and commandline (config takes priority).
static FORCEINLINE bool UseHDRByDefault ()
static bool UseRenderThread ()
Checks if platform wants to use a rendering thread on current device.
static const FString VersionCheckPlatformName ()
static bool WasLaunchedStreaming ()
Return true if the game is being streamed to a separate client device.
Static Protected Member Functions
static void GetConfiguredCoreLimits (int32 PlatformNumPhysicalCores, int32 PlatformNumLogicalCores, bool &bOutFullyInitialized, int32 &OutPhysicalCoreLimit, int32 &OutLogicalCoreLimit, bool &bOutSetPhysicalCountToLogicalCount)
Parse CoreLimit from CommandLine or from the SetCoreLimit value.
Static Protected Attributes
static EDeviceScreenOrientation AllowedDeviceOrientation
static bool bPromptForRemoteDebugOnEnsure
Whether the user should be prompted to allow for a remote debugger to be attached on an ensure.
static bool bShouldPromptForRemoteDebugging
Whether the user should be prompted to allow for a remote debugger to be attached.
static ENetworkConnectionStatus CurrentNetworkConnectionStatus
Detailed Description
Generic implementation for most platforms.
Definition at line 560 of file GenericPlatformMisc.h.
Member Function Documentation
AddAdditionalRootDirectory()
void FGenericPlatformMisc::AddAdditionalRootDirectory (const FString & RootDir) static
add an additional root directory
References RootDir().
AddNetworkListener()
FDelegateHandle FGenericPlatformMisc::AddNetworkListener (FOnNetworkConnectionChangedDelegate && InNewDelegate) static
AllowAudioThread()
bool FGenericPlatformMisc::AllowAudioThread () inline static
Checks if platform wants to allow an audio thread on current device (note: does not imply it will, only if okay given other criteria met)
Returns
true if allowed, false if shouldn't use a separate audio thread
Definition at line 1148 of file GenericPlatformMisc.h.
AllowLocalCaching()
bool FGenericPlatformMisc::AllowLocalCaching () inline static
Definition at line 840 of file GenericPlatformMisc.h.
AllowThreadHeartBeat()
bool FGenericPlatformMisc::AllowThreadHeartBeat () static
Checks if platform wants to allow the thread heartbeat hang detection.
Returns
true if allows, false if shouldn't allow thread heartbeat hang detection
BeginEnterBackgroundEvent()
void FGenericPlatformMisc::BeginEnterBackgroundEvent (const TCHAR * Text) inline static
Profiler enter background events.
These are for timing backgrounding. Some platforms have a timeout for this
Definition at line 932 of file GenericPlatformMisc.h.
References Text.
Referenced by FScopedEnterBackgroundEvent::FScopedEnterBackgroundEvent().
BeginNamedEvent() [1/2]
FORCEINLINE void FGenericPlatformMisc::BeginNamedEvent (const struct FColor & Color, const ANSICHAR * Text) inline static
Definition at line 906 of file GenericPlatformMisc.h.
References Color, FORCEINLINE, and Text.
BeginNamedEvent() [2/2]
FORCEINLINE void FGenericPlatformMisc::BeginNamedEvent (const struct FColor & Color, const TCHAR * Text) inline static
Definition at line 903 of file GenericPlatformMisc.h.
References Color, FORCEINLINE, and Text.
Referenced by FScopedNamedEvent::FScopedNamedEvent(), FScopedNamedEvent::FScopedNamedEvent(), FScopedNamedEventConditional::FScopedNamedEventConditional(), FScopedNamedEventConditional::FScopedNamedEventConditional(), FScopedNamedEventConditionalStatic::FScopedNamedEventConditionalStatic(), FScopedNamedEventConditionalStatic::FScopedNamedEventConditionalStatic(), FScopedNamedEventStatic::FScopedNamedEventStatic(), FScopedNamedEventStatic::FScopedNamedEventStatic(), and RaiseException().
BeginNamedEventFrame()
FORCEINLINE void FGenericPlatformMisc::BeginNamedEventFrame () inline static
Definition at line 900 of file GenericPlatformMisc.h.
References FORCEINLINE.
Referenced by RaiseException().
CacheLaunchDir()
void FGenericPlatformMisc::CacheLaunchDir () static
Function to store the current working directory for use with LaunchDir()
CheckPersistentDownloadStorageSpaceAvailable()
bool FGenericPlatformMisc::CheckPersistentDownloadStorageSpaceAvailable (uint64 BytesRequired, bool bAttemptToUseUI) static
Ensure that there enough space in the persistent download dir.
Returns true if there is sufficient space. If there is insufficient space and bAttemptToUseUI is true, the function will return false and the user may be prompted to clear space
ChooseHDRDeviceAndColorGamut()
FORCEINLINE void FGenericPlatformMisc::ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat & OutputDevice, EDisplayColorGamut & ColorGamut) inline static
Definition at line 1849 of file GenericPlatformMisc.h.
References FORCEINLINE.
CloudDir()
FString FGenericPlatformMisc::CloudDir () static
Return the CloudDir.
CloudDir can be per-user.
CommandLineCommands()
bool FGenericPlatformMisc::CommandLineCommands () inline static
Handles Game Explorer, Firewall and FirstInstall commands, typically from the installer.
Returns
false if the game cannot continue.
Definition at line 1090 of file GenericPlatformMisc.h.
CreateGuid()
void FGenericPlatformMisc::CreateGuid (struct FGuid & Result) static
Create a new globally unique identifier.
CustomNamedStat() [1/2]
FORCEINLINE void FGenericPlatformMisc::CustomNamedStat (const ANSICHAR * Text, float Value, const ANSICHAR * Graph, const ANSICHAR * Unit) inline static
Definition at line 915 of file GenericPlatformMisc.h.
References FORCEINLINE, Text, and Value.
CustomNamedStat() [2/2]
FORCEINLINE void FGenericPlatformMisc::CustomNamedStat (const TCHAR * Text, float Value, const TCHAR * Graph, const TCHAR * Unit) inline static
Definition at line 912 of file GenericPlatformMisc.h.
References FORCEINLINE, Text, and Value.
Referenced by RaiseException().
DeleteStoredSection()
bool FGenericPlatformMisc::DeleteStoredSection (const FString & InStoreId, const FString & InSectionName) static
Deletes the given section and its contained values in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
Parameters
InStoreId The name used to identify the store you want to use (eg, MyGame)
InSectionName The section to delete.
Returns
bool true if the section was deleted, false if not found or couldn't delete
DeleteStoredValue()
bool FGenericPlatformMisc::DeleteStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName) static
Deletes value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
Parameters
InStoreId The name used to identify the store you want to use (eg, MyGame)
InSectionName The section that this key->value pair is placed within (can contain / separators, eg UserDetails/AccountInfo)
InKeyName The name of the key to set the value for
Returns
bool true if the value was deleted correctly, false if not found or couldn't delete
DesktopTouchScreen()
bool FGenericPlatformMisc::DesktopTouchScreen () inline static
Definition at line 1546 of file GenericPlatformMisc.h.
DisableScreenTimeout()
void FGenericPlatformMisc::DisableScreenTimeout () inline static
Definition at line 1973 of file GenericPlatformMisc.h.
EnableScreenTimeout()
void FGenericPlatformMisc::EnableScreenTimeout () inline static
Definition at line 1977 of file GenericPlatformMisc.h.
EndEnterBackgroundEvent()
void FGenericPlatformMisc::EndEnterBackgroundEvent () inline static
Definition at line 933 of file GenericPlatformMisc.h.
Referenced by FScopedEnterBackgroundEvent::~FScopedEnterBackgroundEvent().
EndNamedEvent()
FORCEINLINE void FGenericPlatformMisc::EndNamedEvent () inline static
Definition at line 909 of file GenericPlatformMisc.h.
References FORCEINLINE.
Referenced by FScopedNamedEvent::~FScopedNamedEvent(), FScopedNamedEventConditional::~FScopedNamedEventConditional(), FScopedNamedEventConditionalStatic::~FScopedNamedEventConditionalStatic(), FScopedNamedEventStatic::~FScopedNamedEventStatic(), and RaiseException().
EngineDir()
const TCHAR * FGenericPlatformMisc::EngineDir () static
Get the engine directory.
EnsureNetworkIfNecessary()
void FGenericPlatformMisc::EnsureNetworkIfNecessary () inline static
Definition at line 1606 of file GenericPlatformMisc.h.
Exec()
bool FGenericPlatformMisc::Exec (class UWorld * InWorld, const TCHAR * Cmd, FOutputDevice & Out) inline static
Platform-specific Exec function.
Parameters
InWorld World context
Cmd The command to execute
Out The output device to utilize
Returns
bool true if command was processed, false if not
Definition at line 1369 of file GenericPlatformMisc.h.
References Cmd.
Expand16BitIndicesTo32BitOnLoad()
FORCEINLINE bool FGenericPlatformMisc::Expand16BitIndicesTo32BitOnLoad () inline static
Definition at line 1862 of file GenericPlatformMisc.h.
References FORCEINLINE.
FileExistsInPlatformPackage()
bool FGenericPlatformMisc::FileExistsInPlatformPackage (const FString & RelativePath) static
FullscreenSameAsWindowedFullscreen()
bool FGenericPlatformMisc::FullscreenSameAsWindowedFullscreen () inline static
Definition at line 1555 of file GenericPlatformMisc.h.
GamePersistentDownloadDir()
const TCHAR * FGenericPlatformMisc::GamePersistentDownloadDir () static
Return the GamePersistentDownloadDir.
On some platforms, returns the writable directory for downloaded data that persists across play sessions. This dir is always per-game.
GameTemporaryDownloadDir()
const TCHAR * FGenericPlatformMisc::GameTemporaryDownloadDir () static
Return the temporary directory.
GeneratedConfigDir()
const TCHAR * FGenericPlatformMisc::GeneratedConfigDir () static
GetAdditionalRootDirectories()
TArray< FString > FGenericPlatformMisc::GetAdditionalRootDirectories () static
get additional directories which can be considered as root directories
GetAllowedDeviceOrientation()
EDeviceScreenOrientation FGenericPlatformMisc::GetAllowedDeviceOrientation () static
Returns the allowed orientation of the device.
This is NOT the same as GetDeviceOrientation, which only returns Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight. The allowed orientation limits what orientation your device can have. So if you set the allowed orientation to LandscapeLeft, GetDeviceOrientation will only ever return LandscapeLeft. But if you set the allowed orientation to LandscapeSensor, you are actually restricting the allowed orientations to LandscapeLeft OR LandscapeRight (depending on the sensor), so GetDeviceOrientation might return LandscapeLeft OR LandscapeRight.
Returns
An EDeviceScreenOrientation value.
References GetAllowedDeviceOrientation().
Referenced by GetAllowedDeviceOrientation().
GetBatteryLevel()
FORCEINLINE int FGenericPlatformMisc::GetBatteryLevel () inline static
Gets the current battery level.
Returns
the battery level between 0 and 100.
Definition at line 1474 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetBlockingIOStats()
bool FGenericPlatformMisc::GetBlockingIOStats (FProcessIOStats & OutStats, EInputOutputFlags Flags = EInputOutputFlags::All) inline static
Gets Blocking Input/Output stats covering the lifetime of the process.
Parameters
OutStats Outputs the IO stats
Flags The type of IO stats to retrieve
Returns
Whether or not stats were successfully retrieved
Definition at line 803 of file GenericPlatformMisc.h.
References All, and Flags.
GetBrightness()
FORCEINLINE float FGenericPlatformMisc::GetBrightness () inline static
Definition at line 1480 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetChunkIDFromPakchunkIndex()
FORCEINLINE int32 FGenericPlatformMisc::GetChunkIDFromPakchunkIndex (int32 PakchunkIndex) inline static
Definition at line 1853 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetConfigRulesVariable()
const FString * FGenericPlatformMisc::GetConfigRulesVariable (const FString & Key) static
References Key.
GetConfigRuleVars()
const class TMap< FString, FString > & FGenericPlatformMisc::GetConfigRuleVars () static
GetConfiguredCoreLimits()
void FGenericPlatformMisc::GetConfiguredCoreLimits (int32 PlatformNumPhysicalCores, int32 PlatformNumLogicalCores, bool & bOutFullyInitialized, int32 & OutPhysicalCoreLimit, int32 & OutLogicalCoreLimit, bool & bOutSetPhysicalCountToLogicalCount) static protected
Parse CoreLimit from CommandLine or from the SetCoreLimit value.
The real number of physical cores and logical cores must be provided so that CommandLine arguments can be translated.
Parameters
bOutFullyInitialized True if commandline was available. If false, values are set to defaults.
OutPhysicalCoreLimit The maximum number of physical cores to report in NumberOfCores. Non-negative. 0 indicates unlimited.
OutLogicalCoreLimit The maximum number of logical cores to report in NumberOfCoresIncludingHyperthreads. Non-negative. 0 indicates unlimited.
bOutSetPhysicalCountToLogicalCount Whether NumberOfCores should be overridden to return NumberOfCoresIncludingHyperthreads.
GetContextSwitchStats()
bool FGenericPlatformMisc::GetContextSwitchStats (FContextSwitchStats & OutStats, EContextSwitchFlags Flags = EContextSwitchFlags::All) inline static
Gets Context Switch stats covering the lifetime of the process.
Parameters
OutStats Outputs the Context Switch stats
Flags The type of Context Switch stats to retrieve
Returns
Whether or not stats were successfully retrieved
Definition at line 815 of file GenericPlatformMisc.h.
References All, and Flags.
GetConvertibleLaptopMode()
EConvertibleLaptopMode FGenericPlatformMisc::GetConvertibleLaptopMode () static
Gets the current mode of convertible laptops, i.e.
Laptop or Tablet.
Returns
The laptop mode, or Unknown if not known, or NotSupported if not a convertible laptop.
References GetConvertibleLaptopMode().
Referenced by GetConvertibleLaptopMode().
GetCPUBrand()
FString FGenericPlatformMisc::GetCPUBrand () static
Uses cpuid instruction to get the CPU brand string.
Returns
CPU brand string
GetCPUChipset()
FString FGenericPlatformMisc::GetCPUChipset () static
Returns the CPU chipset if known.
Returns
CPU chipset string (or "Unknown")
GetCPUInfo()
uint32 FGenericPlatformMisc::GetCPUInfo () static
On x86(-64) platforms, uses cpuid instruction to get the CPU signature.
Returns
CPU info bitfield
    Bits 0-3    Stepping ID
    Bits 4-7    Model
    Bits 8-11   Family
    Bits 12-13  Processor type (Intel) / Reserved (AMD)
    Bits 14-15  Reserved
    Bits 16-19  Extended model
    Bits 20-27  Extended family
    Bits 28-31  Reserved
GetCPUVendor()
FString FGenericPlatformMisc::GetCPUVendor () static
Uses cpuid instruction to get the vendor string.
Returns
CPU vendor name
GetCrashHandlingType()
ECrashHandlingType FGenericPlatformMisc::GetCrashHandlingType () inline static
Gets the current crash handling type.
Definition at line 594 of file GenericPlatformMisc.h.
References Default.
GetDefaultDeviceProfileName()
const TCHAR * FGenericPlatformMisc::GetDefaultDeviceProfileName () static
Gets the default profile name.
Used if there is no device profile specified
Returns
the default profile name.
GetDefaultLanguage()
FString FGenericPlatformMisc::GetDefaultLanguage () static
Get the default language (for localization) used by this platform.
Note
This is typically the same as GetDefaultLocale unless the platform distinguishes between the two.
This should be returned in IETF language tag form:
A two-letter ISO 639-1 language code (eg, "zh").
An optional four-letter ISO 15924 script code (eg, "Hans").
An optional two-letter ISO 3166-1 country code (eg, "CN").
GetDefaultLocale()
FString FGenericPlatformMisc::GetDefaultLocale () static
Get the default locale (for internationalization) used by this platform.
Note
This should be returned in IETF language tag form:
A two-letter ISO 639-1 language code (eg, "zh").
An optional four-letter ISO 15924 script code (eg, "Hans").
An optional two-letter ISO 3166-1 country code (eg, "CN").
GetDefaultPathSeparator()
const TCHAR * FGenericPlatformMisc::GetDefaultPathSeparator () static
Returns
platform specific path separator.
GetDeviceId()
FString FGenericPlatformMisc::GetDeviceId () static
Returns a unique string for device identification.
Differs from the deprecated GetUniqueDeviceId in that there is no default implementation (which used unreliable Mac address determiniation). This code is expected to use platform-specific methods to identify the device.
WARNING: Use of this method in your app may imply technical certification requirments for your platform! For instance, consoles often require cert waivers to be in place before calling APIs that can track a device, so be very careful that you are following your platform's protocols for accessing device IDs. See the platform- specific implementations of this method for details on what APIs are used.
If you do not have permission to call this on one or more of your platforms, set GET_DEVICE_ID_UNAVAILABLE=1 in your build step to ensure that any calls that may be made to this API will simply return an empty string.
Returns
the unique string generated by this platform for this device, or an empty string if one is not available.
References GetDeviceId().
Referenced by GetDeviceId().
GetDeviceMakeAndModel()
FString FGenericPlatformMisc::GetDeviceMakeAndModel () static
Returns
"DeviceMake|DeviceModel" if possible, and "CPUVendor|CPUBrand" otherwise, optionally returns "DeviceMake|DeviceModel|CPUChipset" if known
GetDeviceOrientation()
EDeviceScreenOrientation FGenericPlatformMisc::GetDeviceOrientation () static
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
Returns
An EDeviceScreenOrientation value.
GetDeviceTag()
FString FGenericPlatformMisc::GetDeviceTag () static
Get Device Tag of the device running the session.
Note: Gets from DeviceTag command line argument
Returns
empty string or the value from DeviceTag argument.
References GetDeviceTag().
Referenced by GetDeviceTag().
GetDeviceTemperatureLevel()
float FGenericPlatformMisc::GetDeviceTemperatureLevel () static
Returns the current device temperature level.
Level is a relative value that is platform dependent. Lower is cooler, higher is warmer. Level of -1 means Unimplemented.
GetDeviceVolume()
int32 FGenericPlatformMisc::GetDeviceVolume () static
Returns the device volume if the device is capable of returning that information.
-1 : Unknown 0 : Muted 100 : Full Volume
References GetDeviceVolume().
Referenced by GetDeviceVolume().
GetDiskTotalAndFreeSpace()
bool FGenericPlatformMisc::GetDiskTotalAndFreeSpace (const FString & InPath, uint64 & TotalNumberOfBytes, uint64 & NumberOfFreeBytes) static
Retrieves information about the total number of bytes and number of free bytes for the specified disk path.
GetEngineAndProjectAbsoluteDirsFromExecutable()
bool FGenericPlatformMisc::GetEngineAndProjectAbsoluteDirsFromExecutable (FString & OutProjectDir, FString & OutEngineDir) static
Return the engine and project directory based from the executable.
This function would return different results than EngineDir and Project dir if for example -basedir is set on cmd line and/or pak files are used
GetEngineMode()
const TCHAR * FGenericPlatformMisc::GetEngineMode () static
Get a string description of the mode the engine was running in.
References GetEngineMode().
Referenced by GetEngineMode().
GetEnvironmentVariable()
FString FGenericPlatformMisc::GetEnvironmentVariable (const TCHAR * VariableName) static
Retrieve a environment variable from the system.
Parameters
VariableName The name of the variable (ie "Path")
Returns
Value of the variable, or an empty string if not set.
GetEpicAccountId()
FString FGenericPlatformMisc::GetEpicAccountId () static
Get the Epic account ID for the user who last used the Launcher.
Note: This function is for Epic internal use only. Do not use.
Returns
an empty string if the account ID was not present or it failed to read it for any reason.
References GetEpicAccountId().
Referenced by GetEpicAccountId().
GetFileManagerName()
FText FGenericPlatformMisc::GetFileManagerName () static
Returns
Get the name of the platform specific file manager (eg, Explorer on Windows, Finder on OS X)
GetGPUDriverInfo()
struct FGPUDriverInfo FGenericPlatformMisc::GetGPUDriverInfo (const FString & DeviceDescription) static
References GetGPUDriverInfo().
Referenced by GetGPUDriverInfo().
GetHostArchitecture()
FString FGenericPlatformMisc::GetHostArchitecture () static
Returns
architecture of the host machine (x64, arm64 etc)
GetLastError()
FORCEINLINE uint32 FGenericPlatformMisc::GetLastError () inline static
Definition at line 877 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetLocalCurrencyCode()
FString FGenericPlatformMisc::GetLocalCurrencyCode () static
Returns the currency code associated with the device's locale.
Returns
the currency code associated with the device's locale
References GetLocalCurrencyCode().
Referenced by GetLocalCurrencyCode().
GetLocalCurrencySymbol()
FString FGenericPlatformMisc::GetLocalCurrencySymbol () static
Returns the currency symbol associated with the device's locale.
Returns
the currency symbol associated with the device's locale
References GetLocalCurrencySymbol().
Referenced by GetLocalCurrencySymbol().
GetLoginId()
FString FGenericPlatformMisc::GetLoginId () static
Returns a unique string associated with the login account of the current machine.
Implemented using persistent storage like the registry on window (using HKCU), so is susceptible to anything that could reset or revert that storage if the ID is created, which is generally during install or first run of the app.
Note: This is NOT a user or machine fingerprint, as multiple logins on the same machine will not share the same ID, and it is not based on the hardware of the user. It is completely random and non-identifiable.
Returns
a string containing the LoginID, or empty if not available.
References GetLoginId().
Referenced by GetLoginId().
GetMaxPathLength()
FORCEINLINE int32 FGenericPlatformMisc::GetMaxPathLength () inline static
Returns the maximum length of a path.
Definition at line 621 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetMaxRefreshRate()
int32 FGenericPlatformMisc::GetMaxRefreshRate () inline static
retrieves the current maximum refresh rate supported by the platform
Definition at line 1882 of file GenericPlatformMisc.h.
Referenced by GetMaxSupportedRefreshRate().
GetMaxSupportedRefreshRate()
int32 FGenericPlatformMisc::GetMaxSupportedRefreshRate () inline static
retrieves the maximum refresh rate supported by the platform
Definition at line 1890 of file GenericPlatformMisc.h.
References GetMaxRefreshRate().
GetMaxSyncInterval()
int32 FGenericPlatformMisc::GetMaxSyncInterval () inline static
Returns the platform's maximum allowed value for rhi.SyncInterval.
Definition at line 1898 of file GenericPlatformMisc.h.
References MAX_int32.
GetMobilePropagateAlphaSetting()
int FGenericPlatformMisc::GetMobilePropagateAlphaSetting () static
GetNetworkConnectionStatus()
ENetworkConnectionStatus FGenericPlatformMisc::GetNetworkConnectionStatus () static
Returns the current status for the network connection.
GetNetworkConnectionType()
ENetworkConnectionType FGenericPlatformMisc::GetNetworkConnectionType () inline static
Returns whether WiFi connection is currently active.
Definition at line 1601 of file GenericPlatformMisc.h.
References Unknown.
GetNetworkFileCustomData()
FORCEINLINE void FGenericPlatformMisc::GetNetworkFileCustomData (TMap< FString, FString > & OutCustomPlatformData) inline static
Returns any platform-specific key-value data that needs to be sent to the network file server.
Definition at line 1870 of file GenericPlatformMisc.h.
References FORCEINLINE.
GetNullRHIShaderFormat()
const TCHAR * FGenericPlatformMisc::GetNullRHIShaderFormat () static
Determines the shader format for the platform.
Returns
Returns the shader format to be used by that platform
GetOperatingSystemId()
FString FGenericPlatformMisc::GetOperatingSystemId () static
Gets a globally unique ID the represents a particular operating system install.
Returns
an opaque string representing the ID, or an empty string if the platform doesn't support one.
References GetOperatingSystemId().
Referenced by GetOperatingSystemId().
GetOSVersion()
FString FGenericPlatformMisc::GetOSVersion () static
Gets a string representing the numeric OS version (as opposed to a translated OS version that GetOSVersions returns).
The returned string should try to be brief and avoid newlines and symbols, but there's technically no restriction on the string it can return. If the implementation does not support this, it should return an empty string.
GetOSVersions()
void FGenericPlatformMisc::GetOSVersions (FString & out_OSVersionLabel, FString & out_OSSubVersionLabel) static
Gets the OS Version and OS Subversion.
GetPageFaultStats()
bool FGenericPlatformMisc::GetPageFaultStats (FPageFaultStats & OutStats, EPageFaultFlags Flags = EPageFaultFlags::All) inline static
Gets Page Fault stats covering the lifetime of the process.
Parameters
OutStats Outputs the page fault stats
Flags The type of page fault stats to retrieve
Returns
Whether or not stats were successfully retrieved
Definition at line 791 of file GenericPlatformMisc.h.
References All, and Flags.
GetPakchunkIndexFromPakFile()
int32 FGenericPlatformMisc::GetPakchunkIndexFromPakFile (FStringView InFilename) static
GetPakFilenamePrefix()
FStringView FGenericPlatformMisc::GetPakFilenamePrefix () static
GetPathVarDelimiter()
const TCHAR * FGenericPlatformMisc::GetPathVarDelimiter () static
return the delimiter between paths in the PATH environment variable.
GetPendingActivationProtocol()
FString FGenericPlatformMisc::GetPendingActivationProtocol () static
Returns activation protocol that's waiting to be broadcast.
References GetPendingActivationProtocol().
Referenced by GetPendingActivationProtocol().
GetPlatformChunkInstall()
IPlatformChunkInstall * FGenericPlatformMisc::GetPlatformChunkInstall () static
Returns the platform specific chunk based install interface.
Returns
Returns the platform specific chunk based install implementation
GetPlatformCompression()
IPlatformCompression * FGenericPlatformMisc::GetPlatformCompression () static
Returns the platform specific compression interface.
Returns
Returns the platform specific compression interface
GetPlatformFeaturesModuleName()
const TCHAR * FGenericPlatformMisc::GetPlatformFeaturesModuleName () inline static
Return the name of the platform features module.
Can be nullptr if there are no extra features for this platform
Definition at line 1195 of file GenericPlatformMisc.h.
Referenced by IPlatformFeaturesModule::Get().
GetPlatformHostCommunication()
IPlatformHostCommunication & FGenericPlatformMisc::GetPlatformHostCommunication () static
Returns the platform specific interface for communication with processes running on the host pc.
Returns
Returns the platform specific host communication interface.
GetPlatformScreenWarnings()
bool FGenericPlatformMisc::GetPlatformScreenWarnings (TArray< FText > & PlatformScreenWarnings) inline static
Returns any platform specific warning messages we want printed on screen.
Definition at line 1998 of file GenericPlatformMisc.h.
GetPlatformSpecificAsyncIOSystem()
struct FAsyncIOSystemBase * FGenericPlatformMisc::GetPlatformSpecificAsyncIOSystem () inline static
Return the platform specific async IO system, or nullptr if the standard one should be used.
Definition at line 1189 of file GenericPlatformMisc.h.
GetPlatformUserForUserIndex()
FPlatformUserId FGenericPlatformMisc::GetPlatformUserForUserIndex (int32 LocalUserIndex) static
Referenced by FGenericApplicationMessageHandler::OnMotionDetected(), FGenericApplicationMessageHandler::OnTouchEnded(), FGenericApplicationMessageHandler::OnTouchFirstMove(), FGenericApplicationMessageHandler::OnTouchForceChanged(), FGenericApplicationMessageHandler::OnTouchMoved(), and FGenericApplicationMessageHandler::OnTouchStarted().
GetPreferredLanguages()
TArray< FString > FGenericPlatformMisc::GetPreferredLanguages () static
Returns an array of the user's preferred languages in order of preference.
Returns
An array of language IDs ordered from most preferred to least
References GetPreferredLanguages().
Referenced by GetPreferredLanguages().
GetPrimaryGPUBrand()
FString FGenericPlatformMisc::GetPrimaryGPUBrand () static
Returns
primary GPU brand string
GetProcessDiagnostics()
EProcessDiagnosticFlags FGenericPlatformMisc::GetProcessDiagnostics () static
Returns non-zero if a performance-sensitive diagnostic, like a memory sanitizer, is detected for this process.
GetProcessorGroupDesc()
const FProcessorGroupDesc & FGenericPlatformMisc::GetProcessorGroupDesc () static
Returns
a description of all the groups in the current system and their affinities
GetSHA256Signature()
bool FGenericPlatformMisc::GetSHA256Signature (const void * Data, uint32 ByteSize, FSHA256Signature & OutSignature) static
Generates the SHA256 signature of the given data.
Parameters
Data Pointer to the beginning of the data to hash
Bytesize Size of the data to has, in bytes.
OutSignature Output Structure to hold the computed signature.
Returns
whether the hash was computed successfully
GetStoredValue()
bool FGenericPlatformMisc::GetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, FString & OutValue) static
Get the value for the given section and key from the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
Parameters
InStoreId The name used to identify the store you want to use (eg, MyGame)
InSectionName The section that this key->value pair is placed within (can contain / separators, eg UserDetails/AccountInfo)
InKeyName The name of the key to get the value for
OutValue The value found
Returns
bool true if the entry was found (and OutValue contains the result), false if not
GetSystemErrorMessage()
const TCHAR * FGenericPlatformMisc::GetSystemErrorMessage (TCHAR * OutBuffer, int32 BufferCount, int32 Error) static
Returns the last system error code in string form.
NOTE: Only one return value is valid at a time!
Parameters
OutBuffer the buffer to be filled with the error message
BufferLength the size of the buffer in character count
Error the error code to convert to string form
References Error.
GetSystemFontBytes()
TArray< uint8 > FGenericPlatformMisc::GetSystemFontBytes () static
Returns
Memory representing a true type or open type font provided by the platform as a default font for unreal to consume; empty array if the default font failed to load.
GetTimeZoneId()
FString FGenericPlatformMisc::GetTimeZoneId () static
Get the timezone identifier for this platform, or an empty string if the default timezone calculation will work.
Note
This should return either an Olson timezone (eg, "America/Los_Angeles") or an offset from GMT/UTC (eg, "GMT-8:00").
GetUBTPlatform()
const TCHAR * FGenericPlatformMisc::GetUBTPlatform () static
GetUBTTarget()
const TCHAR * FGenericPlatformMisc::GetUBTTarget () static
GetUBTTargetName()
const TCHAR * FGenericPlatformMisc::GetUBTTargetName () static
GetUniqueAdvertisingId()
FString FGenericPlatformMisc::GetUniqueAdvertisingId () static
Returns a unique string for advertising identification.
Returns
the unique string generated by this platform for this device
References GetUniqueAdvertisingId().
Referenced by GetUniqueAdvertisingId().
GetUserIndexForPlatformUser()
int32 FGenericPlatformMisc::GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) static
GetUseVirtualJoysticks()
bool FGenericPlatformMisc::GetUseVirtualJoysticks () inline static
Returns whether the platform wants to use a touch screen for virtual joysticks.
Definition at line 1525 of file GenericPlatformMisc.h.
References PLATFORM_HAS_TOUCH_MAIN_SCREEN.
GetValidTargetPlatforms()
void FGenericPlatformMisc::GetValidTargetPlatforms (TArray< FString > & TargetPlatformNames) static
Return an ordered list of target platforms this runtime can support (ie Android_DXT, Android would mean that it prefers Android_DXT, but can use Android as well)
GetVirtualKeyboardInputHeight()
const float FGenericPlatformMisc::GetVirtualKeyboardInputHeight () inline static
Definition at line 1989 of file GenericPlatformMisc.h.
GetVolumeButtonsHandledBySystem()
bool FGenericPlatformMisc::GetVolumeButtonsHandledBySystem () inline static
Definition at line 1566 of file GenericPlatformMisc.h.
HasActiveWiFiConnection()
bool FGenericPlatformMisc::HasActiveWiFiConnection () inline static
Returns whether WiFi connection is currently active.
Definition at line 1583 of file GenericPlatformMisc.h.
HasMemoryWarningHandler()
bool FGenericPlatformMisc::HasMemoryWarningHandler () inline static
Determines if a warning handler has been set.
Definition at line 872 of file GenericPlatformMisc.h.
HasNonoptionalCPUFeatures()
bool FGenericPlatformMisc::HasNonoptionalCPUFeatures () static
Returns
whether this cpu supports certain required instructions or not
HasPlatformFeature()
bool FGenericPlatformMisc::HasPlatformFeature (const TCHAR * FeatureName) inline static
Returns whether the given platform feature is currently available (for instance, Metal is only available in IOS8 and with A7 devices)
Definition at line 1620 of file GenericPlatformMisc.h.
HasProjectPersistentDownloadDir()
bool FGenericPlatformMisc::HasProjectPersistentDownloadDir () inline static
Return true if the PersistentDownloadDir is available.
On some platforms, a writable directory might not be available by default. Using this function allows handling that case early.
Definition at line 1239 of file GenericPlatformMisc.h.
HasSeparateChannelForDebugOutput()
bool FGenericPlatformMisc::HasSeparateChannelForDebugOutput () static
Whether the platform has a separate debug channel to stdout (eg.
OutputDebugString on Windows). Used to suppress messages being output twice if both go to the same place.
HasVariableHardware()
bool FGenericPlatformMisc::HasVariableHardware () inline static
Returns whether the platform has variable hardware (configurable/upgradeable system).
Definition at line 1611 of file GenericPlatformMisc.h.
HidePlatformStartupScreen()
void FGenericPlatformMisc::HidePlatformStartupScreen () inline static
Definition at line 1839 of file GenericPlatformMisc.h.
InitTaggedStorage()
FORCEINLINE void FGenericPlatformMisc::InitTaggedStorage (uint32 NumTags) inline static
Platform specific function for initializing storage of tagged memory buffers.
Definition at line 939 of file GenericPlatformMisc.h.
References FORCEINLINE.
Is64bitOperatingSystem()
FORCEINLINE bool FGenericPlatformMisc::Is64bitOperatingSystem () inline static
Detects whether we're running in a 64-bit operating system.
Returns
true if we're running in a 64-bit operating system
Definition at line 1100 of file GenericPlatformMisc.h.
References FORCEINLINE, and PLATFORM_64BITS.
IsCacheStorageAvailable()
bool FGenericPlatformMisc::IsCacheStorageAvailable () inline static
For platforms that support cache storage functionality, setting a directory for it when it's not available can result in errors.
This method's purpose is to be overridden in such platforms, with logic that checks if said cache is available. In all other platforms without this constraint, it should return true by default.
Definition at line 830 of file GenericPlatformMisc.h.
IsDebuggerPresent()
FORCEINLINE bool FGenericPlatformMisc::IsDebuggerPresent () inline static
Return true if a debugger is present.
Definition at line 690 of file GenericPlatformMisc.h.
References FORCEINLINE.
Referenced by UE_DEPRECATED().
IsEnsureAllowed()
bool FGenericPlatformMisc::IsEnsureAllowed () inline static
Allows disabling ensure()s without rebuilding the binary, by either a commandline switch or a hotfix.
Returns
ensure is allowed
Definition at line 1403 of file GenericPlatformMisc.h.
IsInLowPowerMode()
FORCEINLINE bool FGenericPlatformMisc::IsInLowPowerMode () inline static
Definition at line 1483 of file GenericPlatformMisc.h.
References FORCEINLINE.
IsLocalPrintThreadSafe()
bool FGenericPlatformMisc::IsLocalPrintThreadSafe () inline static
Whether LocalPrint can be called from any thread without overlapping.
Definition at line 1027 of file GenericPlatformMisc.h.
IsLowLevelOutputDebugStringStructured()
bool FGenericPlatformMisc::IsLowLevelOutputDebugStringStructured () static
Whether LowLevelOutputDebugString[f] can receive structured output as lines of JSON.
IsPackagedForDistribution()
bool FGenericPlatformMisc::IsPackagedForDistribution () inline static
Returns
true if this build is meant for release to retail
Definition at line 1315 of file GenericPlatformMisc.h.
IsPGIActive()
bool FGenericPlatformMisc::IsPGIActive () static
Returns true if PGI (profile-guided instrumentation, needed for PGO) is currently ongoing.
Note that on some platforms can start and stop profile data collection.
IsPGICapableBinary()
bool FGenericPlatformMisc::IsPGICapableBinary () static
Returns true if this binary has been instrumented for collection of data needed for profile-guided optimization (PGO) This value is not expected to change during the run-time.
IsPGOEnabled()
bool FGenericPlatformMisc::IsPGOEnabled () static
Returns true if PGO is currently enabled.
IsRegisteredForRemoteNotifications()
bool FGenericPlatformMisc::IsRegisteredForRemoteNotifications () static
Returns whether or not the device has been registered to receive remote notifications.
References IsRegisteredForRemoteNotifications().
Referenced by IsRegisteredForRemoteNotifications().
IsRemoteSession()
bool FGenericPlatformMisc::IsRemoteSession () inline static
Check to see if the platform is being viewed remotely.
In such a mode we should aim to minimize screen refresh to get the best performance on the remote viewer
Definition at line 684 of file GenericPlatformMisc.h.
References IsRemoteSession().
Referenced by IsRemoteSession().
IsRunningInCloud()
bool FGenericPlatformMisc::IsRunningInCloud () inline static
Return if the game is running on cloud server.
Definition at line 1960 of file GenericPlatformMisc.h.
IsRunningOnBattery()
bool FGenericPlatformMisc::IsRunningOnBattery () static
Returns whether the platform is running on battery power or not.
IsValidAbsolutePathFormat()
bool FGenericPlatformMisc::IsValidAbsolutePathFormat (const FString & Path) inline static
Checks structure of the path against platform formatting requirements.
return true if path is formatted validly
Definition at line 1110 of file GenericPlatformMisc.h.
References Path.
LaunchDir()
const TCHAR * FGenericPlatformMisc::LaunchDir () static
Get the directory the application was launched from (useful for commandline utilities)
LoadTextFileFromPlatformPackage()
FString FGenericPlatformMisc::LoadTextFileFromPlatformPackage (const FString & RelativePath) static
Loads a text file relative to the package root on platforms that distribute apps in package formats.
For other platforms, the path is relative to the root directory.
LocalPrint()
void FGenericPlatformMisc::LocalPrint (const TCHAR * Str) static
Prints string to the default output.
LogNameEventStatsInit()
void FGenericPlatformMisc::LogNameEventStatsInit () static
LowLevelOutputDebugString()
void FGenericPlatformMisc::LowLevelOutputDebugString (const TCHAR * Message) static
Sends a message to a remote tool, and debugger consoles.
Referenced by FFileHandleRegistry::FreeHandles().
LowLevelOutputDebugStringf()
void VARARGS FGenericPlatformMisc::LowLevelOutputDebugStringf (const TCHAR * Format, ...) static
References Format, and VARARGS.
Referenced by TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::~TGenericGrowableAllocator(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::DumpMemoryInfo(), FIOSCommandLineHelper::InitCommandArgs(), FGrowableMallocChunk::Malloc(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::OutOfMemory(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::ShowAllocationInfo(), TGenericGrowableAllocator< ChunkAllocatorType, GrowableAllocationBaseType >::ShowFullAllocationInfo(), FGrowableMallocChunk::ShowFullAllocationList(), and FIOSCommandLineHelper::TryReadCommandLineFile().
MemoryBarrier()
FORCENOINLINE void FGenericPlatformMisc::MemoryBarrier () static
Enforces strict memory load/store ordering across the memory barrier call.
References FORCENOINLINE.
MessageBoxExt()
EAppReturnType::Type FGenericPlatformMisc::MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR * Text, const TCHAR * Caption) static
Show a message box if possible, otherwise print a message and return the default.
Parameters
MsgType What sort of options are provided
Text Specific message
Caption String indicating the title of the message box
Returns
Very strange convention...not really EAppReturnType, see implementation
References Caption, and Text.
NeedsNonoptionalCPUFeaturesCheck()
bool FGenericPlatformMisc::NeedsNonoptionalCPUFeaturesCheck () static
Returns
whether to check for specific CPU compatibility or not
NormalizePath() [1/2]
void FGenericPlatformMisc::NormalizePath (FString & InPath) inline static
Platform-specific normalization of path E.g.
on Linux/Unix platforms, replaces ~ with user home directory, so ~/.config becomes /home/joe/.config (or /Users/Joe/.config)
Definition at line 1119 of file GenericPlatformMisc.h.
NormalizePath() [2/2]
void FGenericPlatformMisc::NormalizePath (FStringBuilderBase & InPath) inline static
Platform-specific normalization of path E.g.
on Linux/Unix platforms, replaces ~ with user home directory, so ~/.config becomes /home/joe/.config (or /Users/Joe/.config)
Definition at line 1127 of file GenericPlatformMisc.h.
NumberOfCores()
int32 FGenericPlatformMisc::NumberOfCores () static
return the number of hardware CPU cores
NumberOfCoresIncludingHyperthreads()
int32 FGenericPlatformMisc::NumberOfCoresIncludingHyperthreads () static
return the number of logical CPU cores
NumberOfIOWorkerThreadsToSpawn()
int32 FGenericPlatformMisc::NumberOfIOWorkerThreadsToSpawn () static
Return the number of worker threads we should spawn to service IO, NOT based on number of cores.
NumberOfWorkerThreadsToSpawn()
int32 FGenericPlatformMisc::NumberOfWorkerThreadsToSpawn () static
Return the number of worker threads we should spawn, based on number of cores.
OsExecute()
bool FGenericPlatformMisc::OsExecute (const TCHAR * CommandType, const TCHAR * Command, const TCHAR * CommandLine = NULL) inline static
Has the OS execute a command and path pair (such as launch a browser)
Parameters
ComandType OS hint as to the type of command
Command the command to execute
CommandLine the commands to pass to the executable
Returns
whether the command was successful or not
Definition at line 1307 of file GenericPlatformMisc.h.
ParseChunkIdPakchunkIndexMapping()
void FGenericPlatformMisc::ParseChunkIdPakchunkIndexMapping (TArray< FString > ChunkIndexRedirects, TMap< int32, int32 > & OutMapping) static
PlatformHandleSplashScreen()
void FGenericPlatformMisc::PlatformHandleSplashScreen (bool ShowSplashScreen = false) inline static
Called to dismiss splash screen.
Definition at line 575 of file GenericPlatformMisc.h.
PlatformInit()
void FGenericPlatformMisc::PlatformInit () inline static
Definition at line 566 of file GenericPlatformMisc.h.
PlatformPreInit()
void FGenericPlatformMisc::PlatformPreInit () static
Called during appInit() after cmd line setup.
PlatformTearDown()
void FGenericPlatformMisc::PlatformTearDown () inline static
Called during AppExit().
Log, Config still exist at this point, but not much else does.
Definition at line 580 of file GenericPlatformMisc.h.
Prefetch() [1/2]
FORCEINLINE void FGenericPlatformMisc::Prefetch (const void * Ptr) inline static
Definition at line 1424 of file GenericPlatformMisc.h.
References FORCEINLINE, and UE_FORCE_CRASH.
Referenced by UE::GC::FPrefetchingObjectIterator::Advance(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::AdvanceToNextIntersectingElement(), FLightVolumeOctreeSemantics::GetBoundingBox(), Prefetch(), PrefetchBlock(), UObjectBase::PrefetchClass(), FChunkedFixedUObjectArray::PrefetchObjectPtr(), UObjectBase::PrefetchOuter(), and UE_DEPRECATED().
Prefetch() [2/2]
FORCEINLINE void FGenericPlatformMisc::Prefetch (const void * Ptr, int32 Offset) inline static
Definition at line 1442 of file GenericPlatformMisc.h.
References FORCEINLINE, and Prefetch().
PrefetchBlock()
FORCEINLINE void FGenericPlatformMisc::PrefetchBlock (const void * Ptr, int32 NumBytes) inline static
Definition at line 1453 of file GenericPlatformMisc.h.
References FORCEINLINE, Line, PLATFORM_CACHE_LINE_SIZE, and Prefetch().
Referenced by UE_DEPRECATED().
PrepareMobileHaptics()
void FGenericPlatformMisc::PrepareMobileHaptics (EMobileHapticsType Type) inline static
For mobile devices, this will crank up a haptic engine for the specified type to be played later with TriggerMobileHaptics If this is called again before Release, it will switch to this type.
Definition at line 1776 of file GenericPlatformMisc.h.
ProjectDir()
const TCHAR * FGenericPlatformMisc::ProjectDir () static
Return the project directory.
PromptForRemoteDebugging()
void FGenericPlatformMisc::PromptForRemoteDebugging (bool bIsEnsure) inline static
Definition at line 1420 of file GenericPlatformMisc.h.
PumpEssentialAppMessages()
void FGenericPlatformMisc::PumpEssentialAppMessages () inline static
Pumps app messages only if there are essential keep-alive messages pending.
This function called from time-sensitive parts of the code and should take minimal time if there are no essential messages waiting
Definition at line 1835 of file GenericPlatformMisc.h.
PumpMessagesForSlowTask()
void FGenericPlatformMisc::PumpMessagesForSlowTask () inline static
Definition at line 1828 of file GenericPlatformMisc.h.
PumpMessagesOutsideMainLoop()
void FGenericPlatformMisc::PumpMessagesOutsideMainLoop () inline static
Definition at line 1824 of file GenericPlatformMisc.h.
RaiseException()
void FGenericPlatformMisc::RaiseException (uint32 ExceptionCode) static
References BeginNamedEvent(), BeginNamedEventFrame(), Color, CustomNamedStat(), EndNamedEvent(), Text, and Value.
RegisterForRemoteNotifications()
void FGenericPlatformMisc::RegisterForRemoteNotifications () static
Requests permission to send remote notifications to the user's device.
References RegisterForRemoteNotifications().
Referenced by RegisterForRemoteNotifications().
ReleaseMobileHaptics()
void FGenericPlatformMisc::ReleaseMobileHaptics () inline static
For mobile devices, this will shutdown the haptics, allowing system to put it to reset as needed.
Definition at line 1791 of file GenericPlatformMisc.h.
RemoveNetworkListener()
bool FGenericPlatformMisc::RemoveNetworkListener (FDelegateHandle Handle) static
References Handle.
RequestDeviceCheckToken()
bool FGenericPlatformMisc::RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc) static
RequestExit()
void FGenericPlatformMisc::RequestExit (bool Force, const TCHAR * CallSite = nullptr) static
Requests application exit.
Parameters
Force If true, perform immediate exit (dangerous because config code isn't flushed, etc). If false, request clean main-loop exit from the platform specific code.
CallSite a diagnostic message identifying the callsite.
References Force.
RequestExitWithStatus()
void FGenericPlatformMisc::RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR * CallSite = nullptr) static
Requests application exit with a specified return code.
Name is different from RequestExit() so overloads of just one of functions are possible.
Parameters
Force If true, perform immediate exit (dangerous because config code isn't flushed, etc). If false, request clean main-loop exit from the platform specific code.
ReturnCode This value will be returned from the program (on the platforms where it's possible). Limited to 0-255 to conform with POSIX.
CallSite a diagnostic message identifying the callsite.
References Force.
RestartApplication()
bool FGenericPlatformMisc::RestartApplication () static
Requests application to restart.
RestartApplicationWithCmdLine()
bool FGenericPlatformMisc::RestartApplicationWithCmdLine (const char * CmdLine) static
Requests application to restart appending the passed in CmdLine to the restart.
RootDir()
const TCHAR * FGenericPlatformMisc::RootDir () static
Get the application root directory.
Referenced by AddAdditionalRootDirectory().
SetAllowedDeviceOrientation()
void FGenericPlatformMisc::SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation) static
Change the allowed orientation of the device.
References SetAllowedDeviceOrientation().
Referenced by SetAllowedDeviceOrientation().
SetBrightness()
FORCEINLINE void FGenericPlatformMisc::SetBrightness (float bBright) inline static
Definition at line 1479 of file GenericPlatformMisc.h.
References FORCEINLINE.
SetCrashHandler()
void FGenericPlatformMisc::SetCrashHandler (void(* CrashHandler)(const FGenericCrashContext &Context)) inline static
Installs handler for the unexpected (due to error) termination of the program, including, but not limited to, crashes.
Definition at line 589 of file GenericPlatformMisc.h.
SetCrashHandlingType()
ECrashHandlingType FGenericPlatformMisc::SetCrashHandlingType (ECrashHandlingType Type) inline static
Sets the type of crash handling done by the engine.
Returns the new crash handling type. If disabling crash handling make sure an alternative is active since threads that crash will just disappear.
Definition at line 600 of file GenericPlatformMisc.h.
References Default.
SetEnvironmentVar()
void FGenericPlatformMisc::SetEnvironmentVar (const TCHAR * VariableName, const TCHAR * Value) static
Sets an environment variable to the local process's environment.
Parameters
VariableName The name of the variable (ie "Path")
Value The string to set the variable to.
References Value.
SetGracefulTerminationHandler()
void FGenericPlatformMisc::SetGracefulTerminationHandler () inline static
Set/restore the Console Interrupt (Control-C, Control-Break, Close) handler.
Definition at line 583 of file GenericPlatformMisc.h.
SetLastError()
void FGenericPlatformMisc::SetLastError (uint32 ErrorCode) inline static
Definition at line 882 of file GenericPlatformMisc.h.
SetMemoryWarningHandler()
void FGenericPlatformMisc::SetMemoryWarningHandler (void(* Handler)(const FGenericMemoryWarningContext &Context)) inline static
Set a handler to be called when there is a memory warning from the OS.
Parameters
Handler The handler to call
Definition at line 865 of file GenericPlatformMisc.h.
SetNetworkConnectionStatus()
void FGenericPlatformMisc::SetNetworkConnectionStatus (ENetworkConnectionStatus NewNetworkConnectionStatus) static
Updates the current status for the network connection.
SetOverrideProjectDir()
void FGenericPlatformMisc::SetOverrideProjectDir (const FString & InOverrideDir) static
Allows a game/program/etc to control the game directory in a special place (for instance, monolithic programs that don't have .uprojects)
Referenced by UE_DEPRECATED().
SetShouldPromptForRemoteDebugging()
void FGenericPlatformMisc::SetShouldPromptForRemoteDebugging (bool bInShouldPrompt) inline static
Definition at line 1384 of file GenericPlatformMisc.h.
References bShouldPromptForRemoteDebugging.
SetShouldPromptForRemoteDebugOnEnsure()
void FGenericPlatformMisc::SetShouldPromptForRemoteDebugOnEnsure (bool bInShouldPrompt) inline static
Definition at line 1389 of file GenericPlatformMisc.h.
References bPromptForRemoteDebugOnEnsure.
SetStoredValue()
bool FGenericPlatformMisc::SetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, const FString & InValue) static
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
Parameters
InStoreId The name used to identify the store you want to use (eg, MyGame)
InSectionName The section that this key->value pair is placed within (can contain / separators, eg UserDetails/AccountInfo)
InKeyName The name of the key to set the value for
InValue The value to set
Returns
bool true if the value was set correctly, false if not
SetStoredValues()
bool FGenericPlatformMisc::SetStoredValues (const FString & InStoreId, const FString & InSectionName, const TMap< FString, FString > & InKeyValues) static
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
Parameters
InStoreId The name used to identify the store you want to use (eg, MyGame)
InSectionName The section that this key->value pair is placed within (can contain / separators, eg UserDetails/AccountInfo)
InKeyValues The mapping of key->value pairs to set
Returns
bool true if the value was set correctly, false if not
SetUBTTargetName()
void FGenericPlatformMisc::SetUBTTargetName (const TCHAR * InTargetName) static
SetupSyscallFilters()
bool FGenericPlatformMisc::SetupSyscallFilters () inline static
Definition at line 1984 of file GenericPlatformMisc.h.
SetUTF8Output()
void FGenericPlatformMisc::SetUTF8Output () static
Sets the default output to UTF8.
SetVolumeButtonsHandledBySystem()
void FGenericPlatformMisc::SetVolumeButtonsHandledBySystem (bool enabled) inline static
Definition at line 1574 of file GenericPlatformMisc.h.
ShareURL()
void FGenericPlatformMisc::ShareURL (const FString & URL, const FText & Description, int32 LocationHintX, int32 LocationHintY) inline static
Perform a mobile-style sharing of a URL.
Will use native UI to display sharing target
Definition at line 1798 of file GenericPlatformMisc.h.
ShouldDisablePluginAtRuntime()
bool FGenericPlatformMisc::ShouldDisablePluginAtRuntime (const FString & PluginName) inline static
Allows platform at runtime to disable unsupported plugins.
Parameters
PluginName Name of enabled plugin to consider
Returns
bool true if plugin should be disabled
Definition at line 1767 of file GenericPlatformMisc.h.
References ShouldDisablePluginAtRuntime().
Referenced by ShouldDisablePluginAtRuntime().
ShouldDisplayTouchInterfaceOnFakingTouchEvents()
bool FGenericPlatformMisc::ShouldDisplayTouchInterfaceOnFakingTouchEvents () inline static
Definition at line 1540 of file GenericPlatformMisc.h.
ShowConsoleWindow()
void FGenericPlatformMisc::ShowConsoleWindow () static
ShutdownTaggedStorage()
FORCEINLINE void FGenericPlatformMisc::ShutdownTaggedStorage () inline static
Platform specific function for freeing storage of tagged memory buffers.
Definition at line 946 of file GenericPlatformMisc.h.
References FORCEINLINE.
StartNewPGOCollection()
bool FGenericPlatformMisc::StartNewPGOCollection (const FString & AbsoluteFileName) inline static
On platforms that support run-time PGI on/off, starts a new collection with a given file name.
Parameters
AbsoluteFileName File to put the collection into
Returns
true if everything was successful
Definition at line 1931 of file GenericPlatformMisc.h.
StatNamedEvent()
template<typename CharType> void FGenericPlatformMisc::StatNamedEvent (const CharType * Text) static
Stats logging for named event.
References Text.
StopPGOCollectionAndCloseFile()
bool FGenericPlatformMisc::StopPGOCollectionAndCloseFile () inline static
On platforms that support run-time PGI on/off, stops the current collection and writes out the file (or completes its write).
The filename must have been given to the StartNewPGICollection() at the start of collection (it is needed in advance since the collection process may stream to it).
Returns
true if everything was successful
Definition at line 1948 of file GenericPlatformMisc.h.
SubmitErrorReport()
void FGenericPlatformMisc::SubmitErrorReport (const TCHAR * InErrorHist, EErrorReportMode::Type InMode) static
Submits a crash report to a central server (release builds only)
References SubmitErrorReport().
Referenced by SubmitErrorReport().
SupportsBackbufferSampling()
FORCEINLINE bool FGenericPlatformMisc::SupportsBackbufferSampling () inline static
Definition at line 1874 of file GenericPlatformMisc.h.
References FORCEINLINE.
SupportsBrightness()
FORCEINLINE bool FGenericPlatformMisc::SupportsBrightness () inline static
Definition at line 1481 of file GenericPlatformMisc.h.
References FORCEINLINE.
SupportsDeviceCheckToken()
bool FGenericPlatformMisc::SupportsDeviceCheckToken () inline static
Definition at line 1802 of file GenericPlatformMisc.h.
SupportsForceTouchInput()
bool FGenericPlatformMisc::SupportsForceTouchInput () inline static
Definition at line 1535 of file GenericPlatformMisc.h.
SupportsFullCrashDumps()
bool FGenericPlatformMisc::SupportsFullCrashDumps () inline static
Platform can generate a full-memory crashdump during crash handling.
Definition at line 850 of file GenericPlatformMisc.h.
SupportsLocalCaching()
bool FGenericPlatformMisc::SupportsLocalCaching () inline static
Definition at line 835 of file GenericPlatformMisc.h.
SupportsMessaging()
bool FGenericPlatformMisc::SupportsMessaging () inline static
Definition at line 820 of file GenericPlatformMisc.h.
SupportsMultithreadedFileHandles()
bool FGenericPlatformMisc::SupportsMultithreadedFileHandles () inline static
Returns
Whether filehandles can be opened on one thread and read/written on another thread
Definition at line 1378 of file GenericPlatformMisc.h.
SupportsTouchInput()
bool FGenericPlatformMisc::SupportsTouchInput () inline static
Definition at line 1530 of file GenericPlatformMisc.h.
References PLATFORM_HAS_TOUCH_MAIN_SCREEN.
TagBuffer()
FORCEINLINE void FGenericPlatformMisc::TagBuffer (const char * Label, uint32 Category, const void * Buffer, size_t BufferSize) inline static
Platform specific function for tagging a memory buffer with a label.
Helps see memory access in profilers
Definition at line 953 of file GenericPlatformMisc.h.
References Buffer, Category, and FORCEINLINE.
TearDown()
void FGenericPlatformMisc::TearDown () static
Frees any memory retained by FGenericPlatformMisc.
TickHotfixables()
void FGenericPlatformMisc::TickHotfixables () static
Ticks values that can be hotfixable in the config.
TickStatNamedEvents()
void FGenericPlatformMisc::TickStatNamedEvents () static
TriggerMobileHaptics()
void FGenericPlatformMisc::TriggerMobileHaptics () inline static
For mobile devices, this will kick the haptic type that was set in PrepareMobileHaptics.
It can be called multiple times with only a single call to Prepare
Definition at line 1784 of file GenericPlatformMisc.h.
UE_DEPRECATED() [1/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 14, "GetHasedMacAddressString is deprecated. It is not reliable on all platforms")
Retrieve the Mac address of the current adapter as a hashed string (privacy).
This generally relies on GetMacAddress() being implemented for the platform, if possible.
Returns
String representing the hashed Mac address, or empty string.
References UE_DEPRECATED().
UE_DEPRECATED() [2/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 14, "GetMacAddress is deprecated. It is not reliable on all platforms")
Retrieve the Mac address of the current adapter.
This is generally platform-dependent code that other platforms must implement.
Returns
array of bytes representing the Mac address, or empty array if unable to determine.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 14, "GetMacAddressString is deprecated. It is not reliable on all platforms")
Retrieve the Mac address of the current adapter as a string.
This generally relies on GetMacAddress() being implemented for the platform, if possible.
Returns
String representing the Mac address, or empty string.
References UE_DEPRECATED().
UE_DEPRECATED() [4/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 14, "GetMachineId is deprecated. Use GetLoginId instead.")
Get (or create) the unique ID used to identify this computer.
This is sort of a misnomer, as there will actually be one per user account on the operating system. This is NOT based on a machine fingerprint.
References UE_DEPRECATED().
UE_DEPRECATED() [5/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 18, "FPaths::SetOverrideGameDir() has been superseded by FPaths::SetOverrideProjectDir().") const & inline
Definition at line 1497 of file GenericPlatformMisc.h.
References FORCEINLINE, and SetOverrideProjectDir().
UE_DEPRECATED() [6/8]
FGenericPlatformMisc::UE_DEPRECATED (4. 19, "FPlatformMisc::DebugBreak is deprecated. Use the UE_DEBUG_BREAK() macro instead.") inline
Break into the debugger, if IsDebuggerPresent returns true, otherwise do nothing.
Definition at line 703 of file GenericPlatformMisc.h.
References FORCEINLINE, and IsDebuggerPresent().
UE_DEPRECATED() [7/8]
FGenericPlatformMisc::UE_DEPRECATED (5. 1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.")
Change the orientation of the device.
UE_DEPRECATED() [8/8]
FGenericPlatformMisc::UE_DEPRECATED (5. 2, "Must supply size when prefetching a block of data") const inline
Definition at line 1447 of file GenericPlatformMisc.h.
References FORCEINLINE, Prefetch(), and PrefetchBlock().
UnregisterForRemoteNotifications()
void FGenericPlatformMisc::UnregisterForRemoteNotifications () static
Requests unregistering from receiving remote notifications on the user's device.
References UnregisterForRemoteNotifications().
Referenced by UnregisterForRemoteNotifications().
UpdateHotfixableEnsureSettings()
void FGenericPlatformMisc::UpdateHotfixableEnsureSettings () inline static
Updates hotfixable ensure settings from config and commandline (config takes priority).
Definition at line 1412 of file GenericPlatformMisc.h.
UseHDRByDefault()
FORCEINLINE bool FGenericPlatformMisc::UseHDRByDefault () inline static
Definition at line 1844 of file GenericPlatformMisc.h.
References FORCEINLINE.
UseRenderThread()
bool FGenericPlatformMisc::UseRenderThread () static
Checks if platform wants to use a rendering thread on current device.
Returns
true if allowed, false if shouldn't use a separate rendering thread
VersionCheckPlatformName()
const FString FGenericPlatformMisc::VersionCheckPlatformName () static
WasLaunchedStreaming()
bool FGenericPlatformMisc::WasLaunchedStreaming () inline static
Return true if the game is being streamed to a separate client device.
Definition at line 1968 of file GenericPlatformMisc.h.
Field Documentation
AllowedDeviceOrientation
EDeviceScreenOrientation FGenericPlatformMisc::AllowedDeviceOrientation static protected
Definition at line 2010 of file GenericPlatformMisc.h.
bPromptForRemoteDebugOnEnsure
bool FGenericPlatformMisc::bPromptForRemoteDebugOnEnsure static protected
Whether the user should be prompted to allow for a remote debugger to be attached on an ensure.
Definition at line 2007 of file GenericPlatformMisc.h.
Referenced by SetShouldPromptForRemoteDebugOnEnsure().
bShouldPromptForRemoteDebugging
bool FGenericPlatformMisc::bShouldPromptForRemoteDebugging static protected
Whether the user should be prompted to allow for a remote debugger to be attached.
Definition at line 2005 of file GenericPlatformMisc.h.
Referenced by SetShouldPromptForRemoteDebugging().
CurrentNetworkConnectionStatus
ENetworkConnectionStatus FGenericPlatformMisc::CurrentNetworkConnectionStatus static protected
Definition at line 2012 of file GenericPlatformMisc.h.
The documentation for this struct was generated from the following file:
GenericPlatformMisc.h