Unreal Engine 5.6 C++ API: FSquare2DGridHelper::FGridLevel Struct Reference
FSquare2DGridHelper::FGridLevel Struct Reference
#include "RuntimeSpatialHashGridHelper.h"
Data Structures
struct FGridCell
struct FGridCellDataChunk
Public Member Functions
FGridLevel (const FVector2D &InOrigin, int64 InCellSize, int64 InGridSize, int32 InLevel)
FGridCell & GetCell (const FGridCellCoord2 &InCoords)
Returns the cell at the specified grid coordinate.
const FGridCell & GetCell (const FGridCellCoord2 &InCoords) const
Returns the cell at the specified grid coordinate.
Public Member Functions inherited from FSquare2DGridHelper::FGrid2D
FGrid2D (const FVector2D &InOrigin, int64 InCellSize, int64 InGridSize)
int32 ForEachIntersectingCells (const FBox &InBox, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
int32 ForEachIntersectingCells (const FSphere &InSphere, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided sphere.
int32 ForEachIntersectingCells (const FSphericalSector &InShape, TFunctionRef< void(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided spherical sector.
int32 ForEachIntersectingCellsBreakable (const FBox &InBox, TFunctionRef< bool(const FGridCellCoord2 &)> InOperation) const
Runs a function on all intersecting cells for the provided box.
bool GetCellBounds (const FGridCellCoord2 &InCoords, FBox2D &OutBounds, bool bCheckIsValidCoord=true) const
Returns the cell bounds.
bool GetCellBounds (int64 InIndex, FBox2D &OutBounds) const
Returns the cell bounds.
bool GetCellCoords (const FBox2D &InBounds2D, FGridCellCoord2 &OutMinCellCoords, FGridCellCoord2 &OutMaxCellCoords) const
Returns the cells coordinates of the provided box.
bool GetCellCoords (const FVector2D &InPos, FGridCellCoord2 &OutCoords) const
Returns the cell coordinates of the provided position.
bool GetCellIndex (const FGridCellCoord2 &InCoords, uint64 &OutIndex) const
Returns the cell index of the provided coords.
bool GetCellIndex (const FVector &InPos, uint64 &OutIndex) const
Returns the cell index of the provided position.
int32 GetNumIntersectingCells (const FBox &InBox) const
Get the number of intersecting cells of the provided box.
bool IsValidCoords (const FGridCellCoord2 &InCoords) const
Validate that the coordinates fit the grid size.
Data Fields
TArray< FGridCell > Cells
TMap< int64, int64 > CellsMapping
int32 Level
Data Fields inherited from FSquare2DGridHelper::FGrid2D
int64 CellSize
int64 GridSize
FVector2D Origin
Detailed Description
Definition at line 267 of file RuntimeSpatialHashGridHelper.h.
Constructor & Destructor Documentation
FGridLevel()
FSquare2DGridHelper::FGridLevel::FGridLevel (const FVector2D & InOrigin, int64 InCellSize, int64 InGridSize, int32 InLevel) inline
Definition at line 340 of file RuntimeSpatialHashGridHelper.h.
References FSquare2DGridHelper::FGrid2D::FGrid2D(), FSquare2DGridHelper::InCellSize, FSquare2DGridHelper::InOrigin, and Level.
Member Function Documentation
GetCell() [1/2]
FGridCell & FSquare2DGridHelper::FGridLevel::GetCell (const FGridCellCoord2 & InCoords) inline
Returns the cell at the specified grid coordinate.
Returns
the cell at the specified grid coordinate
Definition at line 350 of file RuntimeSpatialHashGridHelper.h.
References Cells, CellsMapping, check, FSquare2DGridHelper::FGrid2D::GetCellIndex(), FSquare2DGridHelper::FGrid2D::IsValidCoords(), Level, verify, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
GetCell() [2/2]
const FGridCell & FSquare2DGridHelper::FGridLevel::GetCell (const FGridCellCoord2 & InCoords) const inline
Returns the cell at the specified grid coordinate.
Returns
the cell at the specified grid coordinate
Definition at line 377 of file RuntimeSpatialHashGridHelper.h.
References Cell, Cells, CellsMapping, check, FSquare2DGridHelper::FGrid2D::GetCellIndex(), FSquare2DGridHelper::FGrid2D::IsValidCoords(), Level, verify, UE::Math::TIntVector2< InIntType >::X, and UE::Math::TIntVector2< InIntType >::Y.
Field Documentation
Cells
TArray<FGridCell> FSquare2DGridHelper::FGridLevel::Cells
Definition at line 392 of file RuntimeSpatialHashGridHelper.h.
Referenced by GetCell(), and GetCell().
CellsMapping
TMap<int64, int64> FSquare2DGridHelper::FGridLevel::CellsMapping
Definition at line 393 of file RuntimeSpatialHashGridHelper.h.
Referenced by GetCell(), and GetCell().
Level
int32 FSquare2DGridHelper::FGridLevel::Level
Definition at line 391 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGridLevel(), GetCell(), and GetCell().
The documentation for this struct was generated from the following file:
RuntimeSpatialHashGridHelper.h