Unreal Engine 5.6 C++ API: UE::PixelStreaming2::FEpicRtcDataTrack Class Reference
UE::PixelStreaming2::FEpicRtcDataTrack Class Reference
#include "EpicRtcDataTrack.h"
Public Member Functions
virtual ~FEpicRtcDataTrack ()=default
EpicRtcTrackState GetState () const
bool SendArbitraryData (const FString &MessageType, const TArray64< uint8 > &DataBytes) const
Sends a large buffer of data to the data track, will chunk into multiple data frames if frames greater than 16KB.
template<typename... Args>
bool SendMessage (FString MessageType, Args... VarArgs) const
Sends a series of arguments to the data channel with the given type.
void SetSendTrack (TRefCountPtr< EpicRtcDataTrackInterface > InSendTrack)
Public Member Functions inherited from UE::PixelStreaming2::TEpicRtcTrack< EpicRtcDataTrackInterface >
TEpicRtcTrack (TrackInterface *Track)
virtual ~TEpicRtcTrack ()=default
EpicRtcStringView GetTrackId () const
Public Member Functions inherited from TSharedFromThis< FEpicRtcDataTrack >
TSharedRef< FEpicRtcDataTrack, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FEpicRtcDataTrack, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< FEpicRtcDataTrack > Create (TRefCountPtr< EpicRtcDataTrackInterface > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol)
Protected Member Functions
FEpicRtcDataTrack (TRefCountPtr< EpicRtcDataTrackInterface > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol)
FEpicRtcDataTrack (TSharedPtr< FEpicRtcDataTrack > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol)
bool GetMessageId (const FString &MessageType, uint8 &OutMessageId) const
bool IsActive () const
virtual void PrependData (FBufferBuilder &Builder) const
Protected Member Functions inherited from TSharedFromThis< FEpicRtcDataTrack >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
template<typename... Args>
FBufferBuilder EncodeMessage (uint8 Type, Args... VarArgs) const
bool Send (TArray< uint8 > &Buffer) const
Private Attributes
TRefCountPtr< EpicRtcDataTrackInterface > SendTrack
Track that is used for sending data with Consumer/Producer architecture.
TWeakPtr< IPixelStreaming2DataProtocol > WeakDataProtocol
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FEpicRtcDataTrack >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::PixelStreaming2::TEpicRtcTrack< EpicRtcDataTrackInterface >
TRefCountPtr< TrackInterface > Track
Detailed Description
Definition at line 96 of file EpicRtcDataTrack.h.
Constructor & Destructor Documentation
~FEpicRtcDataTrack()
virtual UE::PixelStreaming2::FEpicRtcDataTrack::~FEpicRtcDataTrack () virtual default
FEpicRtcDataTrack() [1/2]
UE::PixelStreaming2::FEpicRtcDataTrack::FEpicRtcDataTrack (TRefCountPtr< EpicRtcDataTrackInterface > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol) protected
FEpicRtcDataTrack() [2/2]
UE::PixelStreaming2::FEpicRtcDataTrack::FEpicRtcDataTrack (TSharedPtr< FEpicRtcDataTrack > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol) protected
Member Function Documentation
Create()
TSharedPtr< FEpicRtcDataTrack > UE::PixelStreaming2::FEpicRtcDataTrack::Create (TRefCountPtr< EpicRtcDataTrackInterface > InTrack, TWeakPtr< IPixelStreaming2DataProtocol > InDataProtocol) static
EncodeMessage()
template<typename... Args> FBufferBuilder UE::PixelStreaming2::FEpicRtcDataTrack::EncodeMessage (uint8 Type, Args... VarArgs) const inline private
Definition at line 163 of file EpicRtcDataTrack.h.
References Forward(), UE::PixelStreaming2::GetByteSizeOf(), UE::PixelStreaming2::FBufferBuilder::Insert(), MoveTemp(), and PrependData().
Referenced by SendMessage().
GetMessageId()
bool UE::PixelStreaming2::FEpicRtcDataTrack::GetMessageId (const FString & MessageType, uint8 & OutMessageId) const protected
Referenced by SendMessage().
GetState()
EpicRtcTrackState UE::PixelStreaming2::FEpicRtcDataTrack::GetState () const inline
Returns
The state of the underlying EpicRtc data track.
Definition at line 138 of file EpicRtcDataTrack.h.
References UE::PixelStreaming2::TEpicRtcTrack< EpicRtcDataTrackInterface >::Track.
IsActive()
bool UE::PixelStreaming2::FEpicRtcDataTrack::IsActive () const protected
Referenced by SendMessage().
PrependData()
virtual void UE::PixelStreaming2::FEpicRtcDataTrack::PrependData (FBufferBuilder & Builder) const inline protected virtual
Reimplemented in UE::PixelStreaming2::FEpicRtcMutliplexDataTrack.
Definition at line 146 of file EpicRtcDataTrack.h.
Referenced by EncodeMessage().
Send()
bool UE::PixelStreaming2::FEpicRtcDataTrack::Send (TArray< uint8 > & Buffer) const private
References Buffer.
SendArbitraryData()
bool UE::PixelStreaming2::FEpicRtcDataTrack::SendArbitraryData (const FString & MessageType, const TArray64< uint8 > & DataBytes) const
Sends a large buffer of data to the data track, will chunk into multiple data frames if frames greater than 16KB.
Parameters
MessageType The name of the message, it must be registered in IPixelStreaming2InputHandler::GetTo/FromStreamerProtocol()
DataBytes The raw byte buffer to send.
Returns
True of the message was successfully sent.
SendMessage()
template<typename... Args> bool UE::PixelStreaming2::FEpicRtcDataTrack::SendMessage (FString MessageType, Args... VarArgs) const inline
Sends a series of arguments to the data channel with the given type.
Parameters
MessageType The name of the message you want to send. This message name must be registered IPixelStreaming2InputHandler::GetFromStreamerProtocol().
Returns
True of the message was successfully sent.
Definition at line 109 of file EpicRtcDataTrack.h.
References UE::PixelStreaming2::FBufferBuilder::Buffer, EncodeMessage(), Forward(), GetMessageId(), IsActive(), and Send.
SetSendTrack()
void UE::PixelStreaming2::FEpicRtcDataTrack::SetSendTrack (TRefCountPtr< EpicRtcDataTrackInterface > InSendTrack) inline
Definition at line 140 of file EpicRtcDataTrack.h.
References SendTrack.
Field Documentation
SendTrack
TRefCountPtr<EpicRtcDataTrackInterface> UE::PixelStreaming2::FEpicRtcDataTrack::SendTrack private
Track that is used for sending data with Consumer/Producer architecture.
Definition at line 156 of file EpicRtcDataTrack.h.
Referenced by SetSendTrack().
WeakDataProtocol
TWeakPtr<IPixelStreaming2DataProtocol> UE::PixelStreaming2::FEpicRtcDataTrack::WeakDataProtocol private
Definition at line 158 of file EpicRtcDataTrack.h.
The documentation for this class was generated from the following file:
EpicRtcDataTrack.h