Unreal Engine 5.6 C++ API: TMeshAttributeArraySet< AttributeType > Class Template Reference
TMeshAttributeArraySet< AttributeType > Class Template Reference final
This is a type-specific attribute array, which is actually instanced in the attribute set.
#include "MeshAttributeArray.h"
Public Member Functions
FORCEINLINE TMeshAttributeArraySet (const int32 Extent=1)
Constructors.
FORCEINLINE TMeshAttributeArraySet (const int32 NumberOfChannels, const AttributeType &InDefaultValue, const EMeshAttributeFlags InFlags, const int32 InNumberOfElements, const uint32 Extent)
virtual TUniquePtr< FMeshAttributeArraySetBase > Clone () const override
Creates a copy of itself and returns a TUniquePtr to it.
FORCEINLINE TMeshAttributeArrayBase< AttributeType > & GetArrayForChannel (const int32 Index)
FORCEINLINE const TMeshAttributeArrayBase< AttributeType > & GetArrayForChannel (const int32 Index) const
Return the TMeshAttributeArrayBase corresponding to the given attribute channel.
FORCEINLINE AttributeType GetDefaultValue () const
Return default value for this attribute type.
virtual uint32 GetHash () const override
virtual int32 GetNumChannels () const override
Return number of channels this attribute has.
virtual void Initialize (const int32 Count) override
Sets the number of elements to the exact number provided, and initializes them to the default value.
virtual void Insert (const int32 Index) override
Insert the element at the given index.
virtual void InsertChannel (const int32 Index) override
Insert a new attribute channel.
virtual void Remap (const TSparseArray< int32 > &IndexRemap) override
Performs an element index remap according to the passed array.
virtual void Remove (const int32 Index) override
Remove the element at the given index, replacing it with a default value.
virtual void RemoveChannel (const int32 Index) override
Remove the channel at the given index.
virtual void Serialize (FArchive &Ar) override
Polymorphic serialization.
virtual void SetNumChannels (const int32 NumChannels) override
Sets number of channels this attribute has.
virtual void SetNumElements (const int32 Count) override
Sets the number of elements to the exact number provided, preserving existing elements if the number is bigger.
UE_DEPRECATED (5.0, "Please use GetArrayForChannel().") FORCEINLINE const TMeshAttributeArrayBase< AttributeType > &GetArrayForIndex(const int32 Index) const
UE_DEPRECATED (5.0, "Please use GetArrayForChannel().") FORCEINLINE TMeshAttributeArrayBase< AttributeType > &GetArrayForIndex(const int32 Index)
UE_DEPRECATED (5.0, "Please use GetNumChannels().") virtual inline int32 GetNumIndices() const override
UE_DEPRECATED (5.0, "Please use InsertChannel().") virtual void InsertIndex(const int32 Index) override
UE_DEPRECATED (5.0, "Please use RemoveChannel().") virtual void RemoveIndex(const int32 Index) override
UE_DEPRECATED (5.0, "Please use SetNumChannels().") virtual void SetNumIndices(const int32 NumIndices) override
Public Member Functions inherited from FMeshAttributeArraySetBase
FORCEINLINE FMeshAttributeArraySetBase (const uint32 InType, const EMeshAttributeFlags InFlags, const int32 InNumberOfElements, const uint32 InExtent)
Constructor.
virtual ~FMeshAttributeArraySetBase ()=default
Virtual interface.
FORCEINLINE uint32 GetExtent () const
Get the type extent of this attribute array set.
FORCEINLINE EMeshAttributeFlags GetFlags () const
Get the flags for this attribute array set.
FORCEINLINE int32 GetNumElements () const
Return number of elements each attribute index has.
virtual int32 GetNumIndices () const =0
FORCEINLINE uint32 GetType () const
Get the type index of this attribute array set.
template<typename T>
FORCEINLINE bool HasType () const
Determine whether this attribute array set is of the given type.
virtual void InsertIndex (const int32 Index)=0
virtual void RemoveIndex (const int32 Index)=0
FORCEINLINE void SetFlags (const EMeshAttributeFlags InFlags)
Set the flags for this attribute array set.
virtual void SetNumIndices (const int32 NumIndices)=0
Protected Attributes
TArray< TMeshAttributeArrayBase< AttributeType >, TInlineAllocator< 1 > > ArrayForChannels
An array of MeshAttributeArrays, one per channel.
AttributeType DefaultValue
The default value for an attribute of this name.
Protected Attributes inherited from FMeshAttributeArraySetBase
uint32 Extent
Extent of the type, i.e.
EMeshAttributeFlags Flags
Implementation-defined attribute name flags.
int32 NumElements
Number of elements in each index.
uint32 Type
Type of the attribute array (based on the tuple element index from AttributeTypes)
Private Types
using Super = FMeshAttributeArraySetBase
Friends
FArchive & operator<< (FArchive &Ar, TMeshAttributeArraySet &AttributeArraySet)
Serializer.
Detailed Description
template<typename AttributeType>
class TMeshAttributeArraySet< AttributeType >
This is a type-specific attribute array, which is actually instanced in the attribute set.
Definition at line 393 of file MeshAttributeArray.h.
Member Typedef Documentation
Super
template<typename AttributeType> using TMeshAttributeArraySet< AttributeType >::Super = FMeshAttributeArraySetBase private
Definition at line 397 of file MeshAttributeArray.h.
Constructor & Destructor Documentation
TMeshAttributeArraySet() [1/2]
template<typename AttributeType> FORCEINLINE TMeshAttributeArraySet< AttributeType >::TMeshAttributeArraySet (const int32 Extent = 1) inline explicit
Constructors.
Definition at line 401 of file MeshAttributeArray.h.
References FMeshAttributeArraySetBase::Extent, FORCEINLINE, None, and Value.
Referenced by operator<<.
TMeshAttributeArraySet() [2/2]
template<typename AttributeType> FORCEINLINE TMeshAttributeArraySet< AttributeType >::TMeshAttributeArraySet (const int32 NumberOfChannels, const AttributeType & InDefaultValue, const EMeshAttributeFlags InFlags, const int32 InNumberOfElements, const uint32 Extent) inline explicit
Definition at line 405 of file MeshAttributeArray.h.
References DefaultValue, FMeshAttributeArraySetBase::Extent, FORCEINLINE, SetNumChannels(), and Value.
Member Function Documentation
Clone()
template<typename AttributeType> virtual TUniquePtr< FMeshAttributeArraySetBase > TMeshAttributeArraySet< AttributeType >::Clone () const inline override virtual
Creates a copy of itself and returns a TUniquePtr to it.
Implements FMeshAttributeArraySetBase.
Definition at line 413 of file MeshAttributeArray.h.
References MakeUnique().
GetArrayForChannel() [1/2]
template<typename AttributeType> FORCEINLINE TMeshAttributeArrayBase< AttributeType > & TMeshAttributeArraySet< AttributeType >::GetArrayForChannel (const int32 Index) inline
Definition at line 542 of file MeshAttributeArray.h.
References ArrayForChannels, and FORCEINLINE.
GetArrayForChannel() [2/2]
template<typename AttributeType> FORCEINLINE const TMeshAttributeArrayBase< AttributeType > & TMeshAttributeArraySet< AttributeType >::GetArrayForChannel (const int32 Index) const inline
Return the TMeshAttributeArrayBase corresponding to the given attribute channel.
Definition at line 541 of file MeshAttributeArray.h.
References ArrayForChannels, and FORCEINLINE.
GetDefaultValue()
template<typename AttributeType> FORCEINLINE AttributeType TMeshAttributeArraySet< AttributeType >::GetDefaultValue () const inline
Return default value for this attribute type.
Definition at line 545 of file MeshAttributeArray.h.
References DefaultValue, and FORCEINLINE.
GetHash()
template<typename AttributeType> virtual uint32 TMeshAttributeArraySet< AttributeType >::GetHash () const inline override virtual
Implements FMeshAttributeArraySetBase.
Definition at line 458 of file MeshAttributeArray.h.
References ArrayForChannels.
GetNumChannels()
template<typename AttributeType> virtual int32 TMeshAttributeArraySet< AttributeType >::GetNumChannels () const inline override virtual
Return number of channels this attribute has.
Implements FMeshAttributeArraySetBase.
Definition at line 488 of file MeshAttributeArray.h.
References ArrayForChannels.
Referenced by UE_DEPRECATED().
Initialize()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::Initialize (const int32 Count) inline override virtual
Sets the number of elements to the exact number provided, and initializes them to the default value.
Implements FMeshAttributeArraySetBase.
Definition at line 439 of file MeshAttributeArray.h.
References ArrayForChannels, Count, DefaultValue, and FMeshAttributeArraySetBase::NumElements.
Insert()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::Insert (const int32 Index) inline override virtual
Insert the element at the given index.
Implements FMeshAttributeArraySetBase.
Definition at line 419 of file MeshAttributeArray.h.
References ArrayForChannels, DefaultValue, FMath::Max, and FMeshAttributeArraySetBase::NumElements.
InsertChannel()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::InsertChannel (const int32 Index) inline override virtual
Insert a new attribute channel.
Implements FMeshAttributeArraySetBase.
Definition at line 516 of file MeshAttributeArray.h.
References Array, ArrayForChannels, DefaultValue, FMeshAttributeArraySetBase::Extent, and FMeshAttributeArraySetBase::NumElements.
Referenced by UE_DEPRECATED().
Remap()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::Remap (const TSparseArray< int32 > & IndexRemap) inline override virtual
Performs an element index remap according to the passed array.
Implements FMeshAttributeArraySetBase.
Definition at line 475 of file MeshAttributeArray.h.
References ArrayForChannels, DefaultValue, and FMeshAttributeArraySetBase::NumElements.
Remove()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::Remove (const int32 Index) inline override virtual
Remove the element at the given index, replacing it with a default value.
Implements FMeshAttributeArraySetBase.
Definition at line 430 of file MeshAttributeArray.h.
References ArrayForChannels, and DefaultValue.
RemoveChannel()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::RemoveChannel (const int32 Index) inline override virtual
Remove the channel at the given index.
Implements FMeshAttributeArraySetBase.
Definition at line 529 of file MeshAttributeArray.h.
References ArrayForChannels.
Referenced by UE_DEPRECATED().
Serialize()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::Serialize (FArchive & Ar) inline override virtual
Polymorphic serialization.
Implements FMeshAttributeArraySetBase.
Definition at line 469 of file MeshAttributeArray.h.
References Ar.
SetNumChannels()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::SetNumChannels (const int32 NumChannels) inline override virtual
Sets number of channels this attribute has.
Implements FMeshAttributeArraySetBase.
Definition at line 494 of file MeshAttributeArray.h.
References Array, ArrayForChannels, DefaultValue, FMeshAttributeArraySetBase::Extent, and FMeshAttributeArraySetBase::NumElements.
Referenced by TMeshAttributeArraySet(), and UE_DEPRECATED().
SetNumElements()
template<typename AttributeType> virtual void TMeshAttributeArraySet< AttributeType >::SetNumElements (const int32 Count) inline override virtual
Sets the number of elements to the exact number provided, preserving existing elements if the number is bigger.
Implements FMeshAttributeArraySetBase.
Definition at line 449 of file MeshAttributeArray.h.
References ArrayForChannels, Count, DefaultValue, and FMeshAttributeArraySetBase::NumElements.
UE_DEPRECATED() [1/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use GetArrayForChannel().") const & inline
Definition at line 535 of file MeshAttributeArray.h.
References ArrayForChannels, and FORCEINLINE.
UE_DEPRECATED() [2/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use GetArrayForChannel().") const & inline
Definition at line 537 of file MeshAttributeArray.h.
References ArrayForChannels, and FORCEINLINE.
UE_DEPRECATED() [3/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use GetNumChannels().") const inline override
Definition at line 484 of file MeshAttributeArray.h.
References GetNumChannels(), and FMeshAttributeArraySetBase::GetNumIndices().
UE_DEPRECATED() [4/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use InsertChannel().") const inline override
Definition at line 509 of file MeshAttributeArray.h.
References InsertChannel(), and FMeshAttributeArraySetBase::InsertIndex().
UE_DEPRECATED() [5/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use RemoveChannel().") const inline override
Definition at line 522 of file MeshAttributeArray.h.
References RemoveChannel(), and FMeshAttributeArraySetBase::RemoveIndex().
UE_DEPRECATED() [6/6]
template<typename AttributeType> TMeshAttributeArraySet< AttributeType >::UE_DEPRECATED (5. 0, "Please use SetNumChannels().") const inline override
Definition at line 490 of file MeshAttributeArray.h.
References SetNumChannels(), and FMeshAttributeArraySetBase::SetNumIndices().
Friends And Related Symbol Documentation
operator<<
template<typename AttributeType> FArchive & operator<< (FArchive & Ar, TMeshAttributeArraySet< AttributeType > & AttributeArraySet) friend
Serializer.
Definition at line 548 of file MeshAttributeArray.h.
References TMeshAttributeArraySet(), Ar, ArrayForChannels, DefaultValue, FMeshAttributeArraySetBase::Flags, and FMeshAttributeArraySetBase::NumElements.
Field Documentation
ArrayForChannels
template<typename AttributeType> TArray<TMeshAttributeArrayBase<AttributeType>, TInlineAllocator<1> > TMeshAttributeArraySet< AttributeType >::ArrayForChannels protected
An array of MeshAttributeArrays, one per channel.
Definition at line 560 of file MeshAttributeArray.h.
Referenced by GetArrayForChannel(), GetArrayForChannel(), GetHash(), GetNumChannels(), Initialize(), Insert(), InsertChannel(), operator<<, Remap(), Remove(), RemoveChannel(), SetNumChannels(), SetNumElements(), UE_DEPRECATED(), and UE_DEPRECATED().
DefaultValue
template<typename AttributeType> AttributeType TMeshAttributeArraySet< AttributeType >::DefaultValue protected
The default value for an attribute of this name.
Definition at line 563 of file MeshAttributeArray.h.
Referenced by TMeshAttributeArraySet(), GetDefaultValue(), Initialize(), Insert(), InsertChannel(), operator<<, Remap(), Remove(), SetNumChannels(), and SetNumElements().
The documentation for this class was generated from the following file:
MeshAttributeArray.h