Unreal Engine 5.6 C++ API: RigVMExternalVariable.h File Reference
RigVMExternalVariable.h File Reference
#include "CoreMinimal.h"
#include "RigVMTraits.h"
#include "RigVMModule.h"
#include "RigVMPropertyUtils.h"
#include "RigVMTypeIndex.h"
#include "RigVMTypeUtils.h"
#include "UObject/UnrealType.h"
#include "UObject/TextProperty.h"
#include "EdGraphSchema_K2.h"
#include "RigVMExternalVariable.generated.h"
Namespaces
namespace RigVMTypeUtils
Functions
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromBPVariableDescription (const FBPVariableDescription &InVariableDescription)
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromBPVariableDescription (const FBPVariableDescription &InVariableDescription, void *Container)
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromCPPType (const FName &InName, const FString &InCPPType, UObject *InCPPTypeObject, bool bInPublic=false, bool bInReadonly=false)
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromCPPTypePath (const FName &InName, const FString &InCPPTypePath, bool bInPublic=false, bool bInReadonly=false)
RIGVM_API FRigVMExternalVariable RigVMTypeUtils::ExternalVariableFromPinType (const FName &InName, const FEdGraphPinType &InPinType, bool bInPublic=false, bool bInReadonly=false)
RIGVM_API TArray< FRigVMExternalVariableDef > RigVMTypeUtils::GetExternalVariableDefs (const TArray< FRigVMExternalVariable > &ExternalVariables)
FArchive & operator<< (FArchive &Ar, FRigVMExternalVariable &Variable)
USTRUCT() struct FRigVMExternalVariable FArchive & operator<< (FArchive &Ar, FRigVMExternalVariableDef &Variable)
USTRUCT () struct FRigVMExternalVariableDef
The external variable can be used to map external / unowned memory into the VM and back out.
Function Documentation
operator<<() [1/2]
FArchive & operator<< (FArchive & Ar, FRigVMExternalVariable & Variable) inline
Definition at line 520 of file RigVMExternalVariable.h.
References Ar, and FRigVMExternalVariable.
operator<<() [2/2]
USTRUCT() struct FRigVMExternalVariable FArchive & operator<< (FArchive & Ar, FRigVMExternalVariableDef & Variable) inline
Definition at line 496 of file RigVMExternalVariable.h.
References Ar, and FSoftObjectPath::ResolveObject().
USTRUCT()
USTRUCT ()
The external variable can be used to map external / unowned memory into the VM and back out.
Definition at line 22 of file RigVMExternalVariable.h.
References RigVMTypeUtils::ArrayTypeFromBaseType(), BlueprintType, GENERATED_BODY, IsValid(), Name, operator==(), Other, Property, and TSequenceHistory< HistorySize >::Size.