Unreal Engine 5.6 C++ API: FDisplayClusterColorEncoding Struct Reference
FDisplayClusterColorEncoding Struct Reference
Color encoding data.
#include "DisplayClusterColorEncoding.h"
Public Member Functions
FDisplayClusterColorEncoding ()=default
Constructors.
FDisplayClusterColorEncoding (const EDisplayClusterColorEncoding InColorEncoding, const EDisplayClusterColorPremultiply InPremultiply=EDisplayClusterColorPremultiply::None)
FDisplayClusterColorEncoding (float InGamma, const EDisplayClusterColorPremultiply InPremultiply=EDisplayClusterColorPremultiply::None)
EDisplayClusterColorEncoding GetEqualEncoding () const
Return equal encoding value.
bool IsEqualsGammaEncoding (const FDisplayClusterColorEncoding &In) const
Compare only gamma encodings.
bool operator== (const FDisplayClusterColorEncoding &In) const
Returns true if the color encodings are the same.
Data Fields
EDisplayClusterColorEncoding Encoding = EDisplayClusterColorEncoding::Gamma
Color space encoding type.
float GammaValue = 0.f
The gamma value for the EDisplayClusterColorEncoding::Gamma.
EDisplayClusterColorPremultiply Premultiply = EDisplayClusterColorPremultiply::None
Color premultiply modifiers.
Detailed Description
Color encoding data.
Definition at line 37 of file DisplayClusterColorEncoding.h.
Constructor & Destructor Documentation
FDisplayClusterColorEncoding() [1/3]
FDisplayClusterColorEncoding::FDisplayClusterColorEncoding () default
Constructors.
Referenced by IsEqualsGammaEncoding(), and operator==().
FDisplayClusterColorEncoding() [2/3]
FDisplayClusterColorEncoding::FDisplayClusterColorEncoding (const EDisplayClusterColorEncoding InColorEncoding, const EDisplayClusterColorPremultiply InPremultiply = EDisplayClusterColorPremultiply::None) inline
Definition at line 41 of file DisplayClusterColorEncoding.h.
References Encoding, None, and Premultiply.
FDisplayClusterColorEncoding() [3/3]
FDisplayClusterColorEncoding::FDisplayClusterColorEncoding (float InGamma, const EDisplayClusterColorPremultiply InPremultiply = EDisplayClusterColorPremultiply::None) inline
Definition at line 45 of file DisplayClusterColorEncoding.h.
References Encoding, Gamma, GammaValue, None, and Premultiply.
Member Function Documentation
GetEqualEncoding()
EDisplayClusterColorEncoding FDisplayClusterColorEncoding::GetEqualEncoding () const inline
Return equal encoding value.
Definition at line 51 of file DisplayClusterColorEncoding.h.
References Encoding, Gamma, GammaValue, Linear, and sRGB.
Referenced by IsEqualsGammaEncoding().
IsEqualsGammaEncoding()
bool FDisplayClusterColorEncoding::IsEqualsGammaEncoding (const FDisplayClusterColorEncoding & In) const inline
Compare only gamma encodings.
Definition at line 79 of file DisplayClusterColorEncoding.h.
References FDisplayClusterColorEncoding(), Encoding, Gamma, GammaValue, and GetEqualEncoding().
Referenced by operator==().
operator==()
bool FDisplayClusterColorEncoding::operator== (const FDisplayClusterColorEncoding & In) const inline
Returns true if the color encodings are the same.
Definition at line 68 of file DisplayClusterColorEncoding.h.
References FDisplayClusterColorEncoding(), IsEqualsGammaEncoding(), and Premultiply.
Field Documentation
Encoding
EDisplayClusterColorEncoding FDisplayClusterColorEncoding::Encoding = EDisplayClusterColorEncoding::Gamma
Color space encoding type.
Definition at line 106 of file DisplayClusterColorEncoding.h.
Referenced by FDisplayClusterColorEncoding(), FDisplayClusterColorEncoding(), GetEqualEncoding(), and IsEqualsGammaEncoding().
GammaValue
float FDisplayClusterColorEncoding::GammaValue = 0.f
The gamma value for the EDisplayClusterColorEncoding::Gamma.
Zero value means default gamma.
Definition at line 111 of file DisplayClusterColorEncoding.h.
Referenced by FDisplayClusterColorEncoding(), GetEqualEncoding(), and IsEqualsGammaEncoding().
Premultiply
EDisplayClusterColorPremultiply FDisplayClusterColorEncoding::Premultiply = EDisplayClusterColorPremultiply::None
Color premultiply modifiers.
Definition at line 114 of file DisplayClusterColorEncoding.h.
Referenced by FDisplayClusterColorEncoding(), FDisplayClusterColorEncoding(), and operator==().
The documentation for this struct was generated from the following file:
DisplayClusterColorEncoding.h