Unreal Engine 5.6 C++ API: FSoftClassPath Struct Reference
FSoftClassPath Struct Reference
A struct that contains a string reference to a class, can be used to make soft references to classes.
#include "SoftObjectPath.h"
Public Member Functions
FSoftClassPath ()=default
FSoftClassPath (const FSoftClassPath &Other)=default
FSoftClassPath (const FString &PathString)
Construct from a path string.
FSoftClassPath (const UClass *InClass)
Construct from an existing class, will do some string processing.
FSoftClassPath (FSoftClassPath &&Other)=default
~FSoftClassPath ()=default
FSoftClassPath & operator= (const FSoftClassPath &Path)=default
FSoftClassPath & operator= (FSoftClassPath &&Path)=default
UClass * ResolveClass () const
Attempts to find a currently loaded object that matches this object ID.
bool SerializeFromMismatchedTag (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot)
template<typename T>
UClass * TryLoadClass () const
Attempts to load the class.
Public Member Functions inherited from FSoftObjectPath
FSoftObjectPath ()=default
FSoftObjectPath (const ANSICHAR *Path)
FSoftObjectPath (const FObjectPtr &InObject)
FSoftObjectPath (const FSoftObjectPath &Other)=default
FSoftObjectPath (const FString &Path)
Construct from a path string.
template<typename T>
FSoftObjectPath (const TObjectPtr< T > &InObject)
FSoftObjectPath (const UObject *InObject)
Construct from an existing object in memory.
FSoftObjectPath (const WIDECHAR *Path)
FSoftObjectPath (FAnsiStringView Path)
FSoftObjectPath (FSoftObjectPath &&Other)=default
FSoftObjectPath (FTopLevelAssetPath InAssetPath)
Explicitly extend a top-level object path with an empty subobject path.
FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString)
FSoftObjectPath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString)
FSoftObjectPath (FWideStringView Path)
FSoftObjectPath (TYPE_OF_NULLPTR)
~FSoftObjectPath ()=default
void AppendString (FString &Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
void AppendString (FStringBuilderBase &Builder) const
void AppendString (FUtf8StringBuilderBase &Builder) const
bool ExportTextItem (FString &ValueStr, FSoftObjectPath const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
bool FastLess (const FSoftObjectPath &Other) const
Return true if this path appears before Other using fast index-based fname order.
bool FixupCoreRedirects ()
Fixes soft object path for CoreRedirects to handle renamed native objects, returns true if it was modified.
bool FixupForPIE (int32 PIEInstance, TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction=FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix for the given PIEInstance index, returns true if it was modified.
bool FixupForPIE (TFunctionRef< void(int32, FSoftObjectPath &)> InPreFixupForPIECustomFunction=FSoftObjectPath_DefaultPreFixupForPIEFunction)
Fixes up this SoftObjectPath to add the PIE prefix depending on what is currently active, returns true if it was modified.
FName GetAssetFName () const
Returns assetname string, leaving off the /package/path part and sub object.
FString GetAssetName () const
Returns assetname string, leaving off the /package/path part and sub object.
FTopLevelAssetPath GetAssetPath () const
Returns the top-level asset part of this path, without the subobject path.
FORCEINLINE FString GetAssetPathString () const
Returns string version of asset path, including both package and asset but not sub object.
FName GetLongPackageFName () const
Returns /package/path, leaving off the asset name and sub object.
FString GetLongPackageName () const
Returns /package/path, leaving off the asset name and sub object.
FORCEINLINE FString GetSubPathString () const
Returns the sub path, which is often empty.
FORCEINLINE const FUtf8String & GetSubPathUtf8String () const
FSoftObjectPath GetWithoutSubPath () const
Returns this path without the SubPath component, restricting the result to a top level asset but keeping the type as FSoftObjectPath in contrast to GetAssetPath.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText, FArchive *InSerializingArchive=nullptr)
FORCEINLINE bool IsAsset () const
Check if this represents an asset, meaning it is not null but does not have a sub path.
FORCEINLINE bool IsNull () const
Checks to see if this is initialized to null.
FORCEINLINE bool IsSubobject () const
Check if this represents a sub object, meaning it has a sub path.
FORCEINLINE bool IsValid () const
Check if this could possibly refer to a real object, or was initialized to null.
bool LexicalLess (const FSoftObjectPath &Other) const
Return true if this path appears before Other in lexical order.
int32 LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams=FLoadAssetAsyncOptionalParams()) const
Attempts to asynchronously load the object referenced by this path.
bool operator!= (FSoftObjectPath const &Other) const
FSoftObjectPath & operator= (const ANSICHAR *Path)
FSoftObjectPath & operator= (const FSoftObjectPath &Path)=default
FSoftObjectPath & operator= (const FString &Path)
FSoftObjectPath & operator= (const FTopLevelAssetPath Path)
FSoftObjectPath & operator= (const WIDECHAR *Path)
FSoftObjectPath & operator= (FAnsiStringView Path)
FSoftObjectPath & operator= (FSoftObjectPath &&Path)=default
FSoftObjectPath & operator= (FWideStringView Path)
FSoftObjectPath & operator= (TYPE_OF_NULLPTR)
bool operator== (FSoftObjectPath const &Other) const
void PostLoadPath (FArchive *InArchive) const
Handles when a path has been loaded, call if loading with a method that skips SerializePath.
bool PreSavePath (bool *bReportSoftObjectPathRedirects=nullptr)
Fixes up path for saving, call if saving with a method that skips SerializePath.
bool RemapPackage (FName OldPackageName, FName NewPackageName)
Remap the package to handle renames.
void Reset ()
Resets reference to point to null.
UObject * ResolveObject () const
Attempts to find a currently loaded object that matches this path.
bool Serialize (FArchive &Ar)
Struct overrides.
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot)
void SerializePath (FArchive &Ar)
Serializes the internal path and also handles save/PIE fixups.
void SerializePathWithoutFixup (FArchive &Ar)
Serializes the internal path without any save/PIE fixups.
void SetPath (const ANSICHAR *Path)
void SetPath (const FString &Path)
void SetPath (const FTopLevelAssetPath &InAssetPath)
Sets asset path of this reference based on a string path.
void SetPath (const FTopLevelAssetPath &InAssetPath, TStringOverload< FUtf8String > InSubPathString)
void SetPath (const FTopLevelAssetPath &InAssetPath, TStringOverload< FWideString > InSubPathString)
void SetPath (const UObject *InObject)
void SetPath (const WIDECHAR *Path)
void SetPath (FAnsiStringView Path)
void SetPath (FUtf8StringView Path)
void SetPath (FWideStringView Path)
FORCEINLINE void SetSubPathString (TStringOverload< FUtf8String > InSubPathString)
FORCEINLINE void SetSubPathString (TStringOverload< FWideString > InSubPathString)
FString ToString () const
Returns string representation of reference, in form /package/path.assetname[:subpath].
void ToString (FStringBuilderBase &Builder) const
Append string representation of reference, in form /package/path.assetname[:subpath].
void ToString (FUtf8StringBuilderBase &Builder) const
UObject * TryLoad (FUObjectSerializeContext *InLoadContext=nullptr) const
Attempts to load the asset, this will call LoadObject which can be very slow.
UE_DEPRECATED (5.6, "FSoftObjectPath which takes a package name and asset name has been deprecated - please pass FTopLevelAssetPath instead.") explicit FSoftObjectPath(FName InPackageName
UE_DEPRECATED (5.6, "FSoftObjectPath::ConstructFromPackageAsset has been deprecated - please use ConstructFromAssetPath instead.") 1 static FSoftObjectPath ConstructFromPackageAsset(FName InPackageName
UE_DEPRECATED (5.6, "FSoftObjectPath::ConstructFromPackageAssetSubpath has been deprecated - please use ConstructFromAssetPathAndSubpath instead.") 1 static FSoftObjectPath ConstructFromPackageAssetSubpath(FName InPackageName
Static methods for more meaningful construction sites.
Static Public Member Functions
static FSoftClassPath GetOrCreateIDForClass (const UClass *InClass)
Static Public Member Functions inherited from FSoftObjectPath
static void AddPIEPackageName (FName NewPIEPackageName)
Adds list of packages names that have been created specifically for PIE, this is used for editor fixup.
static void ClearPIEPackageNames ()
Disables special PIE path handling, call when PIE finishes to clear list.
static FSoftObjectPath ConstructFromAssetPath (FTopLevelAssetPath InAssetPath)
static FSoftObjectPath ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FUtf8String > InSubPathString)
static FSoftObjectPath ConstructFromAssetPathAndSubpath (FTopLevelAssetPath InAssetPath, TStringOverload< FWideString > InSubPathString)
static FSoftObjectPath ConstructFromObject (const FObjectPtr &InObject)
template<typename T>
static FSoftObjectPath ConstructFromObject (const TObjectPtr< T > &InObject)
static FSoftObjectPath ConstructFromObject (const UObject *InObject)
static FSoftObjectPath ConstructFromStringPath (FString &&InPath)
static FSoftObjectPath ConstructFromStringPath (FStringView InPath)
static FSoftObjectPath ConstructFromStringPath (FUtf8StringView InPath)
static FORCEINLINE FSoftObjectPath GetOrCreateIDForObject (const UObject *Object)
static FSoftObjectPath GetOrCreateIDForObject (FObjectPtr Object)
template<typename T>
static FORCEINLINE FSoftObjectPath GetOrCreateIDForObject (TObjectPtr< T > Object)
Private Member Functions
FSoftClassPath (const UObject *InObject)
Forbid creation for UObject.
Static Private Member Functions
static FSoftObjectPath GetOrCreateIDForObject (const UObject *Object)
Forbidden.
Additional Inherited Members
Data Fields inherited from FSoftObjectPath
FName InAssetName
FName const FString & InSubPathString
Static Public Attributes inherited from FSoftObjectPath
static FName NAME_Untracked
Text of the Untracked parameter in a UPROPERTY's meta field, if this parameter is present it marks that the SoftObjectPath reference should not cause the target package to be added to the cook.
Detailed Description
A struct that contains a string reference to a class, can be used to make soft references to classes.
Definition at line 511 of file SoftObjectPath.h.
Constructor & Destructor Documentation
FSoftClassPath() [1/6]
FSoftClassPath::FSoftClassPath () nodiscard default
Referenced by FSoftClassPath(), FSoftClassPath(), GetOrCreateIDForClass(), operator=(), and operator=().
FSoftClassPath() [2/6]
FSoftClassPath::FSoftClassPath (const FSoftClassPath & Other) nodiscard default
References FSoftClassPath(), and Other.
FSoftClassPath() [3/6]
FSoftClassPath::FSoftClassPath (FSoftClassPath && Other) nodiscard default
References FSoftClassPath(), and Other.
~FSoftClassPath()
FSoftClassPath::~FSoftClassPath () default
FSoftClassPath() [4/6]
FSoftClassPath::FSoftClassPath (const FString & PathString) inline nodiscard
Construct from a path string.
Definition at line 523 of file SoftObjectPath.h.
References FSoftObjectPath::FSoftObjectPath().
FSoftClassPath() [5/6]
FSoftClassPath::FSoftClassPath (const UClass * InClass) inline nodiscard
Construct from an existing class, will do some string processing.
Definition at line 531 of file SoftObjectPath.h.
References FSoftObjectPath::FSoftObjectPath().
FSoftClassPath() [6/6]
FSoftClassPath::FSoftClassPath (const UObject * InObject) inline explicit nodiscard private
Forbid creation for UObject.
This class is for UClass only. Use FSoftObjectPath instead.
Definition at line 563 of file SoftObjectPath.h.
Member Function Documentation
GetOrCreateIDForClass()
FSoftClassPath FSoftClassPath::GetOrCreateIDForClass (const UClass * InClass) static nodiscard
References FSoftClassPath().
GetOrCreateIDForObject()
FSoftObjectPath FSoftClassPath::GetOrCreateIDForObject (const UObject * Object) static private
Forbidden.
This class is for UClass only. Use FSoftObjectPath instead.
References FSoftObjectPath::FSoftObjectPath(), and Object.
operator=() [1/2]
FSoftClassPath & FSoftClassPath::operator= (const FSoftClassPath & Path) default
References FSoftClassPath(), and Path.
operator=() [2/2]
FSoftClassPath & FSoftClassPath::operator= (FSoftClassPath && Path) default
References FSoftClassPath(), and Path.
ResolveClass()
UClass * FSoftClassPath::ResolveClass () const nodiscard
Attempts to find a currently loaded object that matches this object ID.
Returns
Found UClass, or NULL if not currently loaded
SerializeFromMismatchedTag()
bool FSoftClassPath::SerializeFromMismatchedTag (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot)
TryLoadClass()
template<typename T> UClass * FSoftClassPath::TryLoadClass () const inline
Attempts to load the class.
Returns
Loaded UObject, or null if the class fails to load, or if the reference is not valid.
Definition at line 541 of file SoftObjectPath.h.
References FSoftObjectPath::IsValid(), LOAD_None, and FSoftObjectPath::ToString().
The documentation for this struct was generated from the following file:
SoftObjectPath.h