Unreal Engine 5.6 C++ API: FStructOnScope Class Reference
FStructOnScope Class Reference
#include "StructOnScope.h"
Public Member Functions
FStructOnScope ()
FStructOnScope (const FStructOnScope &)=delete
FStructOnScope (const UStruct *InScriptStruct)
FStructOnScope (const UStruct *InScriptStruct, uint8 *InData)
FStructOnScope (FStructOnScope &&InOther)
virtual ~FStructOnScope ()
void AddReferencedObjects (FReferenceCollector &Collector)
virtual void Destroy ()
virtual UPackage * GetPackage () const
virtual const UStruct * GetStruct () const
virtual uint8 * GetStructMemory ()
virtual const uint8 * GetStructMemory () const
TWeakObjectPtr< const UStruct > & GetStructPtr ()
void Initialize (TWeakObjectPtr< const UStruct > InScriptStruct)
Re-initializes the scope with a specified UStruct.
virtual bool IsValid () const
FStructOnScope & operator= (const FStructOnScope &)=delete
FStructOnScope & operator= (FStructOnScope &&InOther)
virtual bool OwnsStructMemory () const
virtual void Reset ()
virtual void SetPackage (UPackage *InPackage)
Protected Member Functions
virtual void Initialize ()
Protected Attributes
bool OwnsMemory
Whether the struct memory is owned by this instance.
TWeakObjectPtr< UPackage > Package
uint8 * SampleStructMemory
TWeakObjectPtr< const UStruct > ScriptStruct
Detailed Description
Definition at line 12 of file StructOnScope.h.
Constructor & Destructor Documentation
FStructOnScope() [1/5]
FStructOnScope::FStructOnScope ()
Referenced by FStructOnScope(), FStructOnScope(), FUserStructOnScopeIgnoreDefaults::FUserStructOnScopeIgnoreDefaults(), TStructOnScope< T >::TStructOnScope(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFromChecked(), TStructOnScope< T >::InitializeFromChecked(), operator=(), and operator=().
FStructOnScope() [2/5]
FStructOnScope::FStructOnScope (const UStruct * InScriptStruct)
FStructOnScope() [3/5]
FStructOnScope::FStructOnScope (const UStruct * InScriptStruct, uint8 * InData)
FStructOnScope() [4/5]
FStructOnScope::FStructOnScope (FStructOnScope && InOther)
References FStructOnScope().
FStructOnScope() [5/5]
FStructOnScope::FStructOnScope (const FStructOnScope &) delete
References FStructOnScope().
~FStructOnScope()
virtual FStructOnScope::~FStructOnScope () virtual
Member Function Documentation
AddReferencedObjects()
void FStructOnScope::AddReferencedObjects (FReferenceCollector & Collector)
Destroy()
virtual void FStructOnScope::Destroy () inline virtual
Reimplemented in TStructOnScope< T >.
Definition at line 90 of file StructOnScope.h.
References FMemory::Free(), OwnsMemory, SampleStructMemory, and ScriptStruct.
Referenced by Initialize(), and Reset().
GetPackage()
virtual UPackage * FStructOnScope::GetPackage () const virtual
Reimplemented in TStructOnScope< T >.
GetStruct()
virtual const UStruct * FStructOnScope::GetStruct () const inline virtual
Definition at line 72 of file StructOnScope.h.
References ScriptStruct.
Referenced by TStructOnScope< T >::Cast(), FSequencerKeyStructGenerator::CopyInstanceToKey(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFromChecked(), and USTRUCT().
GetStructMemory() [1/2]
virtual uint8 * FStructOnScope::GetStructMemory () inline virtual
Reimplemented in TStructOnScope< T >.
Definition at line 62 of file StructOnScope.h.
References SampleStructMemory.
Referenced by FSequencerKeyStructGenerator::CopyInstanceToKey(), TStructOnScope< T >::InitializeFrom(), and USTRUCT().
GetStructMemory() [2/2]
virtual const uint8 * FStructOnScope::GetStructMemory () const inline virtual
Reimplemented in TStructOnScope< T >.
Definition at line 67 of file StructOnScope.h.
References SampleStructMemory.
GetStructPtr()
TWeakObjectPtr< const UStruct > & FStructOnScope::GetStructPtr () inline
Definition at line 77 of file StructOnScope.h.
References ScriptStruct.
Initialize() [1/2]
virtual void FStructOnScope::Initialize () inline protected virtual
Reimplemented in FUserStructOnScopeIgnoreDefaults, and TStructOnScope< T >.
Definition at line 21 of file StructOnScope.h.
References OwnsMemory, SampleStructMemory, and ScriptStruct.
Referenced by Initialize(), and FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator<<.
Initialize() [2/2]
void FStructOnScope::Initialize (TWeakObjectPtr< const UStruct > InScriptStruct) inline
Re-initializes the scope with a specified UStruct.
Definition at line 125 of file StructOnScope.h.
References Destroy(), Initialize(), and ScriptStruct.
IsValid()
virtual bool FStructOnScope::IsValid () const inline virtual
Definition at line 85 of file StructOnScope.h.
References SampleStructMemory, and ScriptStruct.
Referenced by TStructOnScope< T >::CastChecked(), and TStructOnScope< T >::operator bool().
operator=() [1/2]
FStructOnScope & FStructOnScope::operator= (const FStructOnScope &) delete
References FStructOnScope().
operator=() [2/2]
FStructOnScope & FStructOnScope::operator= (FStructOnScope && InOther) inline
Definition at line 38 of file StructOnScope.h.
References FStructOnScope(), OwnsMemory, Reset(), SampleStructMemory, and ScriptStruct.
OwnsStructMemory()
virtual bool FStructOnScope::OwnsStructMemory () const inline virtual
Reimplemented in TStructOnScope< T >.
Definition at line 57 of file StructOnScope.h.
References OwnsMemory.
Reset()
virtual void FStructOnScope::Reset () inline virtual
Definition at line 113 of file StructOnScope.h.
References Destroy(), OwnsMemory, SampleStructMemory, and ScriptStruct.
Referenced by operator=().
SetPackage()
virtual void FStructOnScope::SetPackage (UPackage * InPackage) virtual
Reimplemented in TStructOnScope< T >.
Field Documentation
OwnsMemory
bool FStructOnScope::OwnsMemory protected
Whether the struct memory is owned by this instance.
Definition at line 19 of file StructOnScope.h.
Referenced by Destroy(), Initialize(), TStructOnScope< T >::InitializeAs(), operator=(), OwnsStructMemory(), and Reset().
Package
TWeakObjectPtr<UPackage> FStructOnScope::Package protected
Definition at line 17 of file StructOnScope.h.
SampleStructMemory
uint8* FStructOnScope::SampleStructMemory protected
Definition at line 16 of file StructOnScope.h.
Referenced by TStructOnScope< T >::Cast(), Destroy(), TStructOnScope< T >::Get(), GetStructMemory(), GetStructMemory(), Initialize(), TStructOnScope< T >::InitializeAs(), TStructOnScope< T >::InitializeFrom(), IsValid(), operator=(), TStructOnScope< T >::operator=(), Reset(), and TStructOnScope< T >::Serialize().
ScriptStruct
TWeakObjectPtr<const UStruct> FStructOnScope::ScriptStruct protected
Definition at line 15 of file StructOnScope.h.
Referenced by TStructOnScope< T >::TStructOnScope(), Destroy(), GetStruct(), GetStructPtr(), Initialize(), Initialize(), TStructOnScope< T >::InitializeAs(), IsValid(), operator=(), TStructOnScope< T >::operator=(), Reset(), and TStructOnScope< T >::Serialize().
The documentation for this class was generated from the following file:
StructOnScope.h