Unreal Engine 5.6 C++ API: UE::Geometry::FMeshTriInfoCache Struct Reference
UE::Geometry::FMeshTriInfoCache Struct Reference
#include "MeshCaches.h"
Public Member Functions
void GetTriInfo (int TriangleID, FVector3d &NormalOut, double &AreaOut, FVector3d &CentroidOut) const
Static Public Member Functions
template<class TriangleMeshType>
static FMeshTriInfoCache BuildTriInfoCache (const TriangleMeshType &Mesh)
Data Fields
TDynamicVector< double > Areas
TDynamicVector< FVector3d > Centroids
TDynamicVector< FVector3d > Normals
Detailed Description
Definition at line 18 of file MeshCaches.h.
Member Function Documentation
BuildTriInfoCache()
template<class TriangleMeshType> FMeshTriInfoCache UE::Geometry::FMeshTriInfoCache::BuildTriInfoCache (const TriangleMeshType & Mesh) inline static
Definition at line 32 of file MeshCaches.h.
References UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriNormalAreaCentroid(), UE::Geometry::Mesh, and ParallelFor().
Referenced by UE::Geometry::TFastWindingTree< TriangleMeshType >::build_fast_winding_cache().
GetTriInfo()
void UE::Geometry::FMeshTriInfoCache::GetTriInfo (int TriangleID, FVector3d & NormalOut, double & AreaOut, FVector3d & CentroidOut) const inline
Definition at line 24 of file MeshCaches.h.
References Areas, Centroids, and Normals.
Referenced by FastTriWinding::ComputeCoeffs(), and FastTriWinding::ComputeCoeffsSerial().
Field Documentation
Areas
TDynamicVector<double> UE::Geometry::FMeshTriInfoCache::Areas
Definition at line 22 of file MeshCaches.h.
Referenced by FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), and GetTriInfo().
Centroids
TDynamicVector<FVector3d> UE::Geometry::FMeshTriInfoCache::Centroids
Definition at line 20 of file MeshCaches.h.
Referenced by FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), and GetTriInfo().
Normals
TDynamicVector<FVector3d> UE::Geometry::FMeshTriInfoCache::Normals
Definition at line 21 of file MeshCaches.h.
Referenced by GetTriInfo().
The documentation for this struct was generated from the following file:
MeshCaches.h