Unreal Engine 5.6 C++ Documentation: UProjectileMovementComponent Class Reference
UProjectileMovementComponent Class Reference
ProjectileMovementComponent updates the position of another component during its tick.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/ProjectileMovementComponent.h>
Public Member Functions
bool IsVelocityUnderSimulationThreshold () const
Returns true if velocity magnitude is less than BounceVelocityStopSimulatingThreshold.
virtual void SetVelocityInLocalSpace (FVector NewVelocity)
Sets the velocity to the new value, rotated into Actor space.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
virtual void PostLoad () override
virtual float GetMaxSpeed () const override
Returns maximum speed of component in current movement mode.
virtual void InitializeComponent () override
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
virtual void UpdateTickRegistration () override
Update tick registration state, determined by bAutoUpdateTickRegistration.
virtual bool CheckStillInWorld ()
This will check to see if the projectile is still in the world.
float GetBuoyancy () const
bool ShouldApplyGravity () const
virtual FVector ComputeVelocity (FVector InitialVelocity, float DeltaTime) const
Given an initial velocity and a time step, compute a new velocity.
virtual void StopSimulating (const FHitResult &HitResult)
Clears the reference to UpdatedComponent, fires stop event (OnProjectileStop), and stops ticking (if bAutoUpdateTickRegistration is true).
bool HasStoppedSimulation ()
float GetSimulationTimeStep (float RemainingTime, int32 Iterations) const
Compute remaining time step given remaining time and current iterations.
virtual bool ShouldUseSubStepping () const
Determine whether or not to use substepping in the projectile motion update.
virtual void SetInterpolatedComponent (USceneComponent *Component)
Assigns the component that will be used for network interpolation/smoothing.
USceneComponent * GetInterpolatedComponent () const
Returns the component used for network interpolation.
virtual void MoveInterpolationTarget (const FVector &NewLocation, const FRotator &NewRotation)
Moves the UpdatedComponent, which is also the interpolation target for the interpolated component.
virtual void ResetInterpolation ()
Resets interpolation so that interpolated component snaps back to the initial location/rotation without any additional offsets.
bool IsInterpolationComplete () const
Returns whether interpolation is complete because the target has been reached.
FVector LimitVelocity (FVector NewVelocity) const
Don't allow velocity magnitude to exceed MaxSpeed, if MaxSpeed is non-zero.
virtual FVector ComputeMoveDelta (const FVector &InVelocity, float DeltaTime) const
Compute the distance we should move in the given time, at a given a velocity.
virtual FVector ComputeAcceleration (const FVector &InVelocity, float DeltaTime) const
Compute the acceleration that will be applied.
virtual FVector ComputeHomingAcceleration (const FVector &InVelocity, float DeltaTime) const
Allow the projectile to track towards its homing target.
void AddForce (FVector Force)
Adds a force which is accumulated until next tick, used by ComputeAcceleration() to affect Velocity.
FVector GetPendingForce () const
Returns the sum of pending forces from AddForce().
void ClearPendingForce (bool bClearImmediateForce=false)
Clears any pending forces from AddForce().
virtual float GetGravityZ () const override
Compute gravity effect given current physics volume, projectile gravity scale, etc.
virtual void RegisterComponentTickFunctions (bool bRegister) override
virtual void Deactivate () override
virtual void Serialize (FArchive &Ar) override
virtual void OnRegister () override
Overridden to update component properties that should be updated while being edited.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual bool IsExceedingMaxSpeed (float MaxSpeed) const
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
virtual void StopMovementImmediately ()
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
virtual bool ShouldSkipUpdate (float DeltaTime) const
Possibly skip update if moved component is not rendered or can't move.
virtual APhysicsVolume * GetPhysicsVolume () const
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
virtual void PhysicsVolumeChanged (class APhysicsVolume *NewVolume)
Delegate when PhysicsVolume of UpdatedComponent has been changed.
virtual void SetUpdatedComponent (USceneComponent *NewUpdatedComponent)
Assign the component we move and update.
virtual bool IsInWater () const
Returns true if it's in PhysicsVolume with water flag.
virtual void UpdateComponentVelocity ()
Update ComponentVelocity of UpdatedComponent.
virtual void InitCollisionParams (FCollisionQueryParams &OutParams, FCollisionResponseParams &OutResponseParam) const
Initialize collision params appropriately based on our collision settings.
virtual bool OverlapTest (const FVector &Location, const FQuat &RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape &CollisionShape, const AActor *IgnoreActor) const
Return true if the given collision shape overlaps other geometry at the given location and rotation.
bool MoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool MoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
bool K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult &OutHit, bool bSweep=true, bool bTeleport=false)
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
bool SafeMoveUpdatedComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
bool SafeMoveUpdatedComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult &OutHit, ETeleportType Teleport=ETeleportType::None)
virtual FVector GetPenetrationAdjustment (const FHitResult &Hit) const
Calculate a movement adjustment to try to move out of a penetration from a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Try to move out of penetration in an object after a failed move.
bool ResolvePenetration (const FVector &Adjustment, const FHitResult &Hit, const FRotator &NewRotation)
virtual FVector ComputeSlideVector (const FVector &Delta, const float Time, const FVector &Normal, const FHitResult &Hit) const
Compute a vector to slide along a surface, given an attempted move, time, and normal.
virtual float SlideAlongSurface (const FVector &Delta, float Time, const FVector &Normal, FHitResult &Hit, bool bHandleImpact=false)
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
virtual void TwoWallAdjust (FVector &Delta, const FHitResult &Hit, const FVector &OldHitNormal) const
Compute a movement direction when contacting two surfaces.
virtual void AddRadialForce (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff)
Adds force from radial force components.
virtual void AddRadialImpulse (const FVector &Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange)
Adds impulse from radial force components.
virtual void SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting)
Set the plane constraint axis setting.
EPlaneConstraintAxisSetting GetPlaneConstraintAxisSetting () const
Get the plane constraint axis setting.
virtual void SetPlaneConstraintNormal (FVector PlaneNormal)
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintFromVectors (FVector Forward, FVector Up)
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintOrigin (FVector PlaneOrigin)
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
virtual void SetPlaneConstraintEnabled (bool bEnabled)
Sets whether or not the plane constraint is enabled.
const FVector & GetPlaneConstraintNormal () const
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
const FVector & GetPlaneConstraintOrigin () const
Get the plane constraint origin.
virtual FVector ConstrainDirectionToPlane (FVector Direction) const
Constrain a direction vector to the plane constraint, if enabled.
virtual FVector ConstrainLocationToPlane (FVector Location) const
Constrain a position vector to the plane constraint, if enabled.
virtual FVector ConstrainNormalToPlane (FVector Normal) const
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
virtual void SnapUpdatedComponentToPlane ()
Snap the updated component to the plane constraint, if enabled.
virtual void OnTeleported ()
Called by owning Actor upon successful teleport from AActor::TeleportTo().
Static Public Member Functions
static void PhysicsLockedAxisSettingChanged ()
Public Attributes
uint8 bSimulationUseScopedMovement:1
If true, uses FScopedMovementUpdate to avoid moving the UpdatedComponent more than once during a tick during simulation.
uint8 bInterpolationUseScopedMovement:1
If true, uses FScopedMovementUpdate to avoid moving the attached interpolated object's children more than once during a tick when it would both interpolate and move during projectile simulation.
float PreviousHitTime
Saved HitResult Time (0 to 1) from previous simulation step.
FVector PreviousHitNormal
Saved HitResult Normal from previous simulation step that resulted in an impact.
float ProjectileGravityScale
Custom gravity scale for this projectile.
float Buoyancy
Buoyancy of UpdatedComponent in fluid.
float Bounciness
Percentage of velocity maintained after the bounce in the direction of the normal of impact (coefficient of restitution).
float Friction
Coefficient of friction, affecting the resistance to sliding along a surface.
float BounceVelocityStopSimulatingThreshold
If velocity is below this threshold after a bounce, stops simulating and triggers the OnProjectileStop event.
float MinFrictionFraction
When bounce angle affects friction, apply at least this fraction of normal friction.
FOnProjectileBounceDelegate OnProjectileBounce
Called when projectile impacts something and bounces are enabled.
FOnProjectileStopDelegate OnProjectileStop
Called when projectile has come to a stop (velocity is below simulation threshold, bounces are disabled, or it is forcibly stopped).
float HomingAccelerationMagnitude
The magnitude of our acceleration towards the homing target.
TWeakObjectPtr< USceneComponent > HomingTargetComponent
The current target we are homing towards.
float MaxSimulationTimeStep
Max time delta for each discrete simulation step.
int32 MaxSimulationIterations
Max number of iterations used for each discrete simulation step.
int32 BounceAdditionalIterations
On the first few bounces (up to this amount), allow extra iterations over MaxSimulationIterations if necessary.
float InterpLocationTime
"Time" over which most of the location interpolation occurs, when the UpdatedComponent (target) moves ahead of the interpolated component.
float InterpRotationTime
"Time" over which most of the rotation interpolation occurs, when the UpdatedComponent (target) moves ahead of the interpolated component.
float InterpLocationMaxLagDistance
Max distance behind UpdatedComponent which the interpolated component is allowed to lag.
float InterpLocationSnapToTargetDistance
Max distance behind UpdatedComponent beyond which the interpolated component is snapped to the target location instead.
float ThrottleInterpolationThresholdNotRenderedShortTime
Time after not rendered recently when we consider throttling interpolation.
float ThrottleInterpolationThresholdNotRenderedLongTime
Time after not rendered for a long time when we consider throttling interpolation.
int32 ThrottleInterpolationSkipFramesRecent
When recently relevant, skip this many frames of interpolation if throttling is enabled.
int32 ThrottleInterpolationSkipFramesNotRecent
When not recently relevant, skip this many frames of interpolation if throttling is enabled.
uint8 bUpdateOnlyIfRendered:1
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
uint8 bAutoUpdateTickRegistration:1
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
uint8 bTickBeforeOwner:1
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
uint8 bAutoRegisterUpdatedComponent:1
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
uint8 bConstrainToPlane:1
If true, movement will be constrained to a plane.
uint8 bSnapToPlaneAtStart:1
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
uint8 bAutoRegisterPhysicsVolumeUpdates:1
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
uint8 bComponentShouldUpdatePhysicsVolume:1
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Protected Types
enum class EHandleBlockingHitResult { Deflect , AdvanceNextSubstep , Abort }
Protected Member Functions
bool UpdateThrottleInterpolation (float DeltaTime, USceneComponent *InterpComponent)
Update interpolation throttling for this frame.
virtual int32 ComputeThrottleInterpolationMaxFrames (float DeltaTime, USceneComponent *InterpComponent)
Determine the number of frames to allow to skip when interpolating.
virtual void ResetThrottleInterpolation (float DeltaTime)
Custom hook to reset throttle interpolation tracking when it was throttling previously.
virtual EHandleBlockingHitResult HandleBlockingHit (const FHitResult &Hit, float TimeTick, const FVector &MoveDelta, float &SubTickTimeRemaining)
Handle blocking hit during simulation update.
virtual void HandleImpact (const FHitResult &Hit, float TimeSlice=0.f, const FVector &MoveDelta=FVector::ZeroVector) override
Applies bounce logic if enabled to affect velocity upon impact (using ComputeBounceResult()), or stops the projectile if bounces are not enabled or velocity is below BounceVelocityStopSimulatingThreshold.
virtual bool HandleDeflection (FHitResult &Hit, const FVector &OldVelocity, const uint32 NumBounces, float &SubTickTimeRemaining)
Handle a blocking hit after HandleBlockingHit() returns a result indicating that deflection occured.
virtual bool HandleSliding (FHitResult &Hit, float &SubTickTimeRemaining)
Handle case where projectile is sliding along a surface.
virtual FVector ComputeBounceResult (const FHitResult &Hit, float TimeSlice, const FVector &MoveDelta)
Computes result of a bounce and returns the new velocity.
virtual void TickInterpolation (float DeltaTime)
FVector GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const
Helper to compute the plane constraint axis from the current setting.
virtual bool MoveUpdatedComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, ETeleportType Teleport=ETeleportType::None)
virtual bool ResolvePenetrationImpl (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation)
Protected Attributes
uint8 bInterpolationComplete:1
True if interpolation has reached the target, false if there is more interpolation required.
int32 ThrottleInterpolationFramesSinceInterp
Tracks the number of frames since the last interpolation.
FVector PendingForceThisUpdate
FVector InterpLocationOffset
FVector InterpInitialLocationOffset
TWeakObjectPtr< USceneComponent > InterpolatedComponentPtr
FQuat InterpRotationOffset
FQuat InterpInitialRotationOffset
FVector PlaneConstraintNormal
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
FVector PlaneConstraintOrigin
The origin of the plane that constrains movement, if plane constraint is enabled.
Static Protected Attributes
static const float MIN_TICK_TIME
Minimum delta time considered when ticking.
Detailed Description
ProjectileMovementComponent updates the position of another component during its tick.
Behavior such as bouncing after impacts and homing toward a target are supported.
Normally the root component of the owning actor is moved, however another component may be selected (see SetUpdatedComponent()). If the updated component is simulating physics, only the initial launch parameters (when initial velocity is non-zero) will affect the projectile, and the physics sim will take over from there.
See also
UMovementComponent
Definition at line 26 of file ProjectileMovementComponent.h.
Member Enumeration Documentation
EHandleBlockingHitResult
enum class UProjectileMovementComponent::EHandleBlockingHitResult strong protected
Enumerator
Deflect
AdvanceNextSubstep
Assume velocity has been deflected, and trigger HandleDeflection().
This is the default return value of HandleBlockingHit().
Abort
Advance to the next simulation update.
Typically used when additional slide/multi-bounce logic can be ignored, such as when an object that blocked the projectile is destroyed and movement should continue.
Definition at line 424 of file ProjectileMovementComponent.h.
Member Function Documentation
AddForce()
void UProjectileMovementComponent::AddForce (FVector Force)
Adds a force which is accumulated until next tick, used by ComputeAcceleration() to affect Velocity.
References AddForce().
AddRadialForce()
virtual void UMovementComponent::AddRadialForce (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff) virtual inherited
Adds force from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
Reimplemented in UCharacterMovementComponent.
References AddRadialForce().
AddRadialImpulse()
virtual void UMovementComponent::AddRadialImpulse (const FVector & Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange) virtual inherited
Adds impulse from radial force components.
Intended to be overridden by subclasses; default implementation does nothing.
Parameters
Origin The origin of the force
Radius The radius in which the force will be applied
Strength The strength of the force
Falloff The falloff from the force's origin
bVelChange If true, the Strength is taken as a change in velocity instead of an impulse (ie. mass will have no effect).
Reimplemented in UCharacterMovementComponent.
References AddRadialImpulse().
CheckStillInWorld()
virtual bool UProjectileMovementComponent::CheckStillInWorld () virtual
This will check to see if the projectile is still in the world.
It will check things like the KillZ, outside world bounds, etc. and handle the situation.
ClearPendingForce()
void UProjectileMovementComponent::ClearPendingForce (bool bClearImmediateForce = false)
Clears any pending forces from AddForce().
If bClearImmediateForce is true, clears any force being processed during this update as well.
ComputeAcceleration()
virtual FVector UProjectileMovementComponent::ComputeAcceleration (const FVector & InVelocity, float DeltaTime) const virtual
Compute the acceleration that will be applied.
References ComputeAcceleration().
ComputeBounceResult()
virtual FVector UProjectileMovementComponent::ComputeBounceResult (const FHitResult & Hit, float TimeSlice, const FVector & MoveDelta) protected virtual
Computes result of a bounce and returns the new velocity.
ComputeHomingAcceleration()
virtual FVector UProjectileMovementComponent::ComputeHomingAcceleration (const FVector & InVelocity, float DeltaTime) const virtual
Allow the projectile to track towards its homing target.
References ComputeHomingAcceleration().
ComputeMoveDelta()
virtual FVector UProjectileMovementComponent::ComputeMoveDelta (const FVector & InVelocity, float DeltaTime) const virtual
Compute the distance we should move in the given time, at a given a velocity.
References ComputeMoveDelta().
ComputeSlideVector()
virtual FVector UMovementComponent::ComputeSlideVector (const FVector & Delta, const float Time, const FVector & Normal, const FHitResult & Hit) const virtual inherited
Compute a vector to slide along a surface, given an attempted move, time, and normal.
Parameters
Delta Attempted move.
Time Amount of move to apply (between 0 and 1).
Normal Normal opposed to movement. Not necessarily equal to Hit.Normal.
Hit HitResult of the move that resulted in the slide.
Reimplemented in UCharacterMovementComponent.
References ComputeSlideVector().
ComputeThrottleInterpolationMaxFrames()
virtual int32 UProjectileMovementComponent::ComputeThrottleInterpolationMaxFrames (float DeltaTime, USceneComponent * InterpComponent) protected virtual
Determine the number of frames to allow to skip when interpolating.
Returning 0 means not to allow throttling. Default implementation chooses between ThrottleInterpolationThresholdNotRenderedShortTime and ThrottleInterpolationThresholdNotRenderedLongTime based on WasRecentlyRendered(), extend or override this for custom behavior.
ComputeVelocity()
virtual FVector UProjectileMovementComponent::ComputeVelocity (FVector InitialVelocity, float DeltaTime) const virtual
Given an initial velocity and a time step, compute a new velocity.
Default implementation applies the result of ComputeAcceleration() to velocity.
Parameters
InitialVelocity Initial velocity.
DeltaTime Time step of the update.
Returns
Velocity after DeltaTime time step.
ConstrainDirectionToPlane()
virtual FVector UMovementComponent::ConstrainDirectionToPlane (FVector Direction) const virtual inherited
Constrain a direction vector to the plane constraint, if enabled.
See also
SetPlaneConstraint
References ConstrainDirectionToPlane().
ConstrainLocationToPlane()
virtual FVector UMovementComponent::ConstrainLocationToPlane (FVector Location) const virtual inherited
Constrain a position vector to the plane constraint, if enabled.
References ConstrainLocationToPlane(), and Location.
ConstrainNormalToPlane()
virtual FVector UMovementComponent::ConstrainNormalToPlane (FVector Normal) const virtual inherited
Constrain a normal vector (of unit length) to the plane constraint, if enabled.
References ConstrainNormalToPlane().
Deactivate()
virtual void UMovementComponent::Deactivate () override virtual inherited
Reimplemented in UCharacterMovementComponent.
GetBuoyancy()
float UProjectileMovementComponent::GetBuoyancy () const inline
Returns
Buoyancy of UpdatedComponent in fluid. 0.0=sinks as fast as in air, 1.0=neutral buoyancy
Definition at line 251 of file ProjectileMovementComponent.h.
References Buoyancy.
GetGravityZ()
virtual float UProjectileMovementComponent::GetGravityZ () const override virtual
Compute gravity effect given current physics volume, projectile gravity scale, etc.
Reimplemented from UMovementComponent.
GetInterpolatedComponent()
USceneComponent * UProjectileMovementComponent::GetInterpolatedComponent () const
Returns the component used for network interpolation.
References GetInterpolatedComponent().
GetMaxSpeed()
virtual float UProjectileMovementComponent::GetMaxSpeed () const inline override virtual
Returns maximum speed of component in current movement mode.
Reimplemented from UMovementComponent.
Definition at line 239 of file ProjectileMovementComponent.h.
References GetMaxSpeed().
GetPendingForce()
FVector UProjectileMovementComponent::GetPendingForce () const inline
Returns the sum of pending forces from AddForce().
Definition at line 499 of file ProjectileMovementComponent.h.
References GetPendingForce().
GetPenetrationAdjustment()
virtual FVector UMovementComponent::GetPenetrationAdjustment (const FHitResult & Hit) const virtual inherited
Calculate a movement adjustment to try to move out of a penetration from a failed move.
Parameters
Hit the result of the failed move
Returns
The adjustment to use after a failed move, or a zero vector if no attempt should be made.
Reimplemented in UCharacterMovementComponent.
References GetPenetrationAdjustment(), and ResolvePenetration().
GetPhysicsVolume()
virtual APhysicsVolume * UMovementComponent::GetPhysicsVolume () const virtual inherited
Returns the PhysicsVolume this MovementComponent is using, or the world's default physics volume if none.
References GetPhysicsVolume().
GetPlaneConstraintAxisSetting()
EPlaneConstraintAxisSetting UMovementComponent::GetPlaneConstraintAxisSetting () const inline inherited
Get the plane constraint axis setting.
Definition at line 477 of file MovementComponent.h.
References EPlaneConstraintAxisSetting.
GetPlaneConstraintNormal()
const FVector & UMovementComponent::GetPlaneConstraintNormal () const inherited
Returns the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
References GetPlaneConstraintNormal().
GetPlaneConstraintNormalFromAxisSetting()
FVector UMovementComponent::GetPlaneConstraintNormalFromAxisSetting (EPlaneConstraintAxisSetting AxisSetting) const protected inherited
Helper to compute the plane constraint axis from the current setting.
Parameters
AxisSetting Setting to use when computing the axis.
Returns
Plane constraint axis/normal.
References EPlaneConstraintAxisSetting, and GetPlaneConstraintNormalFromAxisSetting().
GetPlaneConstraintOrigin()
const FVector & UMovementComponent::GetPlaneConstraintOrigin () const inherited
Get the plane constraint origin.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
Returns
The origin of the plane that constrains movement, if the plane constraint is enabled.
References GetPlaneConstraintOrigin().
GetSimulationTimeStep()
float UProjectileMovementComponent::GetSimulationTimeStep (float RemainingTime, int32 Iterations) const
Compute remaining time step given remaining time and current iterations.
The last iteration (limited by MaxSimulationIterations) always returns the remaining time, which may violate MaxSimulationTimeStep.
Parameters
RemainingTime Remaining time in the tick.
Iterations Current iteration of the tick (starting at 1).
Returns
The remaining time step to use for the next sub-step of iteration.
See also
MaxSimulationTimeStep, MaxSimulationIterations
ShouldUseSubStepping()
HandleBlockingHit()
virtual EHandleBlockingHitResult UProjectileMovementComponent::HandleBlockingHit (const FHitResult & Hit, float TimeTick, const FVector & MoveDelta, float & SubTickTimeRemaining) protected virtual
Handle blocking hit during simulation update.
Checks that simulation remains valid after collision. If simulating then calls HandleImpact(), and returns EHandleHitWallResult::Deflect by default to enable multi-bounce and sliding support through HandleDeflection(). If no longer simulating then returns EHandleHitWallResult::Abort, which aborts attempts at further simulation.
Parameters
Hit Blocking hit that occurred.
TimeTick Time delta of last move that resulted in the blocking hit.
MoveDelta Movement delta for the current sub-step.
SubTickTimeRemaining How much time to continue simulating in the current sub-step, which may change as a result of this function. Initial default value is: TimeTick * (1.f - Hit.Time)
Returns
Result indicating how simulation should proceed.
See also
EHandleHitWallResult, HandleImpact()
HandleDeflection()
virtual bool UProjectileMovementComponent::HandleDeflection (FHitResult & Hit, const FVector & OldVelocity, const uint32 NumBounces, float & SubTickTimeRemaining) protected virtual
Handle a blocking hit after HandleBlockingHit() returns a result indicating that deflection occured.
Default implementation increments NumBounces, checks conditions that could indicate a slide, and calls HandleSliding() if necessary.
Parameters
Hit Blocking hit that occurred. May be changed to indicate the last hit result of further movement.
OldVelocity Velocity at the start of the simulation update sub-step. Current Velocity may differ (as a result of a bounce).
NumBounces Number of bounces that have occurred thus far in the tick.
SubTickTimeRemaining Time remaining in the simulation sub-step. May be changed to indicate change to remaining time.
Returns
True if simulation of the projectile should continue, false otherwise.
See also
HandleSliding()
HandleImpact()
virtual void UProjectileMovementComponent::HandleImpact (const FHitResult & Hit, float TimeSlice = 0.f, const FVector & MoveDelta = FVector::ZeroVector) override protected virtual
Applies bounce logic if enabled to affect velocity upon impact (using ComputeBounceResult()), or stops the projectile if bounces are not enabled or velocity is below BounceVelocityStopSimulatingThreshold.
Triggers applicable events (OnProjectileBounce).
Reimplemented from UMovementComponent.
HandleSliding()
virtual bool UProjectileMovementComponent::HandleSliding (FHitResult & Hit, float & SubTickTimeRemaining) protected virtual
Handle case where projectile is sliding along a surface.
Velocity will be parallel to the impact surface upon entry to this method.
Parameters
InitialHit Hit result of impact causing slide. May be modified by this function to reflect any subsequent movement.
SubTickTimeRemaining Time remaining in the tick. This function may update this time with any reduction to the simulation time requested.
Returns
True if simulation of the projectile should continue, false otherwise.
HasStoppedSimulation()
bool UProjectileMovementComponent::HasStoppedSimulation () inline
Definition at line 269 of file ProjectileMovementComponent.h.
References HasStoppedSimulation().
InitCollisionParams()
virtual void UMovementComponent::InitCollisionParams (FCollisionQueryParams & OutParams, FCollisionResponseParams & OutResponseParam) const virtual inherited
Initialize collision params appropriately based on our collision settings.
Use this before any Line, Overlap, or Sweep tests.
References InitCollisionParams().
InitializeComponent()
virtual void UProjectileMovementComponent::InitializeComponent () override virtual
Overridden to auto-register the updated component if it starts NULL, and we can find a root component on our owner.
Reimplemented from UMovementComponent.
IsExceedingMaxSpeed()
virtual bool UMovementComponent::IsExceedingMaxSpeed (float MaxSpeed) const virtual inherited
Returns true if the current velocity is exceeding the given max speed (usually the result of GetMaxSpeed()), within a small error tolerance.
Note that under normal circumstances updates cause by acceleration will not cause this to be true, however external forces or changes in the max speed limit can cause the max speed to be violated.
References IsExceedingMaxSpeed(), and StopMovementImmediately().
IsInterpolationComplete()
bool UProjectileMovementComponent::IsInterpolationComplete () const inline
Returns whether interpolation is complete because the target has been reached.
True when interpolation is disabled.
Definition at line 401 of file ProjectileMovementComponent.h.
References bInterpolationComplete, and IsInterpolationComplete().
IsInWater()
virtual bool UMovementComponent::IsInWater () const virtual inherited
Returns true if it's in PhysicsVolume with water flag.
References IsInWater().
IsVelocityUnderSimulationThreshold()
bool UProjectileMovementComponent::IsVelocityUnderSimulationThreshold () const inline
Returns true if velocity magnitude is less than BounceVelocityStopSimulatingThreshold.
Definition at line 208 of file ProjectileMovementComponent.h.
References BounceVelocityStopSimulatingThreshold, and IsVelocityUnderSimulationThreshold().
K2_MoveUpdatedComponent()
bool UMovementComponent::K2_MoveUpdatedComponent (FVector Delta, FRotator NewRotation, FHitResult & OutHit, bool bSweep = true, bool bTeleport = false) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
References K2_MoveUpdatedComponent().
LimitVelocity()
FVector UProjectileMovementComponent::LimitVelocity (FVector NewVelocity) const
Don't allow velocity magnitude to exceed MaxSpeed, if MaxSpeed is non-zero.
References LimitVelocity().
MoveInterpolationTarget()
virtual void UProjectileMovementComponent::MoveInterpolationTarget (const FVector & NewLocation, const FRotator & NewRotation) virtual
Moves the UpdatedComponent, which is also the interpolation target for the interpolated component.
If there is not interpolated component, this simply moves UpdatedComponent. Use this typically from PostNetReceiveLocationAndRotation() or similar from an Actor.
References MoveInterpolationTarget().
MoveUpdatedComponent() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Moves our UpdatedComponent by the given Delta, and sets rotation to NewRotation.
Respects the plane constraint, if enabled. \note This simply calls the virtual MoveUpdatedComponentImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
True if some movement occurred, false if no movement occurred. Result of any impact will be stored in OutHit.
Definition at line 487 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::MoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 492 of file MovementComponent.h.
References MoveUpdatedComponentImpl().
MoveUpdatedComponentImpl()
virtual bool UMovementComponent::MoveUpdatedComponentImpl (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, ETeleportType Teleport = ETeleportType::None) protected virtual inherited
References MoveUpdatedComponentImpl().
OnRegister()
virtual void UMovementComponent::OnRegister () override virtual inherited
Overridden to update component properties that should be updated while being edited.
Reimplemented in UCharacterMovementComponent.
OnTeleported()
virtual void UMovementComponent::OnTeleported () inline virtual inherited
Called by owning Actor upon successful teleport from AActor::TeleportTo().
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
Definition at line 459 of file MovementComponent.h.
References OnTeleported().
OverlapTest()
virtual bool UMovementComponent::OverlapTest (const FVector & Location, const FQuat & RotationQuat, const ECollisionChannel CollisionChannel, const FCollisionShape & CollisionShape, const AActor * IgnoreActor) const virtual inherited
Return true if the given collision shape overlaps other geometry at the given location and rotation.
The collision params are set by InitCollisionParams().
References Location, MoveUpdatedComponent(), and OverlapTest().
PhysicsLockedAxisSettingChanged()
void UMovementComponent::PhysicsLockedAxisSettingChanged () static inherited
PhysicsVolumeChanged()
virtual void UMovementComponent::PhysicsVolumeChanged (class APhysicsVolume * NewVolume) virtual inherited
Delegate when PhysicsVolume of UpdatedComponent has been changed.
Reimplemented in UCharacterMovementComponent.
References PhysicsVolumeChanged().
PostEditChangeProperty()
virtual void UMovementComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual inherited
Reimplemented in UCharacterMovementComponent, and UNavMovementComponent.
PostLoad()
virtual void UProjectileMovementComponent::PostLoad () override virtual
Reimplemented from UMovementComponent.
References PostLoad().
RegisterComponentTickFunctions()
virtual void UMovementComponent::RegisterComponentTickFunctions (bool bRegister) override virtual inherited
Reimplemented in UCharacterMovementComponent.
ResetInterpolation()
virtual void UProjectileMovementComponent::ResetInterpolation () virtual
Resets interpolation so that interpolated component snaps back to the initial location/rotation without any additional offsets.
References ResetInterpolation().
ResetThrottleInterpolation()
virtual void UProjectileMovementComponent::ResetThrottleInterpolation (float DeltaTime) protected virtual
Custom hook to reset throttle interpolation tracking when it was throttling previously.
ResolvePenetration() [1/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) inherited
Try to move out of penetration in an object after a failed move.
This function should respect the plane constraint if applicable. \note This simply calls the virtual ResolvePenetrationImpl() which can be overridden to implement custom behavior. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat)..
Parameters
Adjustment The requested adjustment, usually from GetPenetrationAdjustment()
Hit The result of the failed move
Returns
True if the adjustment was successful and the original move should be retried, or false if no repeated attempt should be made.
Definition at line 497 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetration() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::ResolvePenetration (const FVector & Adjustment, const FHitResult & Hit, const FRotator & NewRotation) inherited
Definition at line 502 of file MovementComponent.h.
References ResolvePenetrationImpl().
ResolvePenetrationImpl()
virtual bool UMovementComponent::ResolvePenetrationImpl (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) protected virtual inherited
Reimplemented in UCharacterMovementComponent, and UFloatingPawnMovement.
References ResolvePenetrationImpl().
SafeMoveUpdatedComponent() [1/2]
bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Calls MoveUpdatedComponent(), handling initial penetrations by calling ResolvePenetration().
If this adjustment succeeds, the original movement will be attempted again. \note The overload taking rotation as an FQuat is slightly faster than the version using FRotator (which will be converted to an FQuat). \note The 'Teleport' flag is currently always treated as 'None' (not teleporting) when used in an active FScopedMovementUpdate.
Returns
result of the final MoveUpdatedComponent() call.
References SafeMoveUpdatedComponent().
SafeMoveUpdatedComponent() [2/2]
FORCEINLINE_DEBUGGABLE bool UMovementComponent::SafeMoveUpdatedComponent (const FVector & Delta, const FRotator & NewRotation, bool bSweep, FHitResult & OutHit, ETeleportType Teleport = ETeleportType::None) inherited
Definition at line 482 of file MovementComponent.h.
References SafeMoveUpdatedComponent().
Serialize()
virtual void UMovementComponent::Serialize (FArchive & Ar) override virtual inherited
Reimplemented in UCharacterMovementComponent, UNavMovementComponent, and UPawnMovementComponent.
SetInterpolatedComponent()
virtual void UProjectileMovementComponent::SetInterpolatedComponent (USceneComponent * Component) virtual
Assigns the component that will be used for network interpolation/smoothing.
It is expected that this is a component attached somewhere below the UpdatedComponent. When network updates use MoveInterpolationTarget() to move the UpdatedComponent, the interpolated component's relative offset will be maintained and smoothed over the course of future component ticks. The current relative location and rotation of the component is saved as the target offset for future interpolation.
See also
MoveInterpolationTarget(), bInterpMovement, bInterpRotation
References SetInterpolatedComponent().
SetPlaneConstraintAxisSetting()
virtual void UMovementComponent::SetPlaneConstraintAxisSetting (EPlaneConstraintAxisSetting NewAxisSetting) virtual inherited
Set the plane constraint axis setting.
Changing this setting will modify the current value of PlaneConstraintNormal.
Parameters
NewAxisSetting New plane constraint axis setting.
References EPlaneConstraintAxisSetting, GetPlaneConstraintAxisSetting(), and SetPlaneConstraintAxisSetting().
SetPlaneConstraintEnabled()
virtual void UMovementComponent::SetPlaneConstraintEnabled (bool bEnabled) virtual inherited
Sets whether or not the plane constraint is enabled.
References SetPlaneConstraintEnabled().
SetPlaneConstraintFromVectors()
virtual void UMovementComponent::SetPlaneConstraintFromVectors (FVector Forward, FVector Up) virtual inherited
Uses the Forward and Up vectors to compute the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintFromVectors().
SetPlaneConstraintNormal()
virtual void UMovementComponent::SetPlaneConstraintNormal (FVector PlaneNormal) virtual inherited
Sets the normal of the plane that constrains movement, enforced if the plane constraint is enabled.
Changing the normal automatically sets PlaneConstraintAxisSetting to "Custom".
Parameters
PlaneNormal The normal of the plane. If non-zero in length, it will be normalized.
References SetPlaneConstraintNormal().
SetPlaneConstraintOrigin()
virtual void UMovementComponent::SetPlaneConstraintOrigin (FVector PlaneOrigin) virtual inherited
Sets the origin of the plane that constrains movement, enforced if the plane constraint is enabled.
References SetPlaneConstraintOrigin().
SetUpdatedComponent()
virtual void UMovementComponent::SetUpdatedComponent (USceneComponent * NewUpdatedComponent) virtual inherited
Assign the component we move and update.
Reimplemented in UCharacterMovementComponent, and UPawnMovementComponent.
References SetUpdatedComponent().
SetVelocityInLocalSpace()
virtual void UProjectileMovementComponent::SetVelocityInLocalSpace (FVector NewVelocity) virtual
Sets the velocity to the new value, rotated into Actor space.
References SetVelocityInLocalSpace().
ShouldApplyGravity()
bool UProjectileMovementComponent::ShouldApplyGravity () const inline
Definition at line 253 of file ProjectileMovementComponent.h.
References ProjectileGravityScale.
ShouldSkipUpdate()
virtual bool UMovementComponent::ShouldSkipUpdate (float DeltaTime) const virtual inherited
Possibly skip update if moved component is not rendered or can't move.
Parameters
DeltaTime
Todo
this parameter is not used in the function.
Returns
true if component movement update should be skipped
References ShouldSkipUpdate().
ShouldUseSubStepping()
virtual bool UProjectileMovementComponent::ShouldUseSubStepping () const virtual
Determine whether or not to use substepping in the projectile motion update.
If true, GetSimulationTimeStep() will be used to time-slice the update. If false, all remaining time will be used during the tick.
Returns
Whether or not to use substepping in the projectile motion update.
See also
GetSimulationTimeStep()
SlideAlongSurface()
virtual float UMovementComponent::SlideAlongSurface (const FVector & Delta, float Time, const FVector & Normal, FHitResult & Hit, bool bHandleImpact = false) virtual inherited
Slide smoothly along a surface, and slide away from multiple impacts using TwoWallAdjust if necessary.
Calls HandleImpact for each surface hit, if requested. Uses SafeMoveUpdatedComponent() for movement, and ComputeSlideVector() to determine the slide direction.
Parameters
Delta Attempted movement vector.
Time Percent of Delta to apply (between 0 and 1). Usually equal to the remaining time after a collision: (1.0 - Hit.Time).
Normal Normal opposing movement, along which we will slide.
Hit [In] HitResult of the attempted move that resulted in the impact triggering the slide. [Out] HitResult of last attempted move.
bHandleImpact Whether to call HandleImpact on each hit.
Returns
The percentage of requested distance (Delta * Percent) actually applied (between 0 and 1). 0 if no movement occurred, non-zero if movement occurred.
Reimplemented in UCharacterMovementComponent.
References SlideAlongSurface().
SnapUpdatedComponentToPlane()
virtual void UMovementComponent::SnapUpdatedComponentToPlane () virtual inherited
Snap the updated component to the plane constraint, if enabled.
References SnapUpdatedComponentToPlane().
StopMovementImmediately()
void UMovementComponent::StopMovementImmediately () inline virtual inherited
Stops movement immediately (zeroes velocity, usually zeros acceleration for components with acceleration).
Reimplemented in UNavMovementComponent.
Definition at line 471 of file MovementComponent.h.
References UpdateComponentVelocity().
StopSimulating()
virtual void UProjectileMovementComponent::StopSimulating (const FHitResult & HitResult) virtual
Clears the reference to UpdatedComponent, fires stop event (OnProjectileStop), and stops ticking (if bAutoUpdateTickRegistration is true).
References StopSimulating().
TickComponent()
virtual void UProjectileMovementComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Reimplemented from UMovementComponent.
References TickComponent().
TickInterpolation()
virtual void UProjectileMovementComponent::TickInterpolation (float DeltaTime) protected virtual
TwoWallAdjust()
virtual void UMovementComponent::TwoWallAdjust (FVector & Delta, const FHitResult & Hit, const FVector & OldHitNormal) const virtual inherited
Compute a movement direction when contacting two surfaces.
Parameters
Delta [In] Amount of move attempted before impact. [Out] Computed adjustment based on impacts.
Hit Impact from last attempted move
OldHitNormal Normal of impact before last attempted move
Returns
Result in Delta that is the direction to move when contacting two surfaces.
Reimplemented in UCharacterMovementComponent.
References TwoWallAdjust().
UpdateComponentVelocity()
virtual void UMovementComponent::UpdateComponentVelocity () virtual inherited
Update ComponentVelocity of UpdatedComponent.
This needs to be called by derived classes at the end of an update whenever Velocity has changed.
References UpdateComponentVelocity().
UpdateThrottleInterpolation()
bool UProjectileMovementComponent::UpdateThrottleInterpolation (float DeltaTime, USceneComponent * InterpComponent) protected
Update interpolation throttling for this frame.
Uses ComputeThrottleInterpolationMaxFrames() to determine the number of frames to allow to be skipped.
Returns
true if throttled this frame, false if there should be an update.
UpdateTickRegistration()
virtual void UProjectileMovementComponent::UpdateTickRegistration () override virtual
Update tick registration state, determined by bAutoUpdateTickRegistration.
Called by SetUpdatedComponent.
Reimplemented from UMovementComponent.
Member Data Documentation
bAutoRegisterPhysicsVolumeUpdates
uint8 UMovementComponent::bAutoRegisterPhysicsVolumeUpdates inherited
If true, then applies the value of bComponentShouldUpdatePhysicsVolume to the UpdatedComponent.
If false, will not change bShouldUpdatePhysicsVolume on the UpdatedComponent at all.
See also
bComponentShouldUpdatePhysicsVolume
Definition at line 166 of file MovementComponent.h.
bAutoRegisterUpdatedComponent
uint8 UMovementComponent::bAutoRegisterUpdatedComponent inherited
If true, registers the owner's Root component as the UpdatedComponent if there is not one currently assigned.
Definition at line 148 of file MovementComponent.h.
bAutoUpdateTickRegistration
uint8 UMovementComponent::bAutoUpdateTickRegistration inherited
If true, whenever the updated component is changed, this component will enable or disable its tick dependent on whether it has something to update.
This will NOT enable tick at startup if bAutoActivate is false, because presumably you have a good reason for not wanting it to start ticking initially.
Definition at line 136 of file MovementComponent.h.
bComponentShouldUpdatePhysicsVolume
uint8 UMovementComponent::bComponentShouldUpdatePhysicsVolume inherited
If true, enables bShouldUpdatePhysicsVolume on the UpdatedComponent during initialization from SetUpdatedComponent(), otherwise disables such updates.
Only enabled if bAutoRegisterPhysicsVolumeUpdates is true. WARNING: UpdatePhysicsVolume is potentially expensive if overlap events are also disabled because it requires a separate query against all physics volumes in the world.
Definition at line 174 of file MovementComponent.h.
bConstrainToPlane
uint8 UMovementComponent::bConstrainToPlane inherited
If true, movement will be constrained to a plane.
See also
PlaneConstraintNormal, PlaneConstraintOrigin, PlaneConstraintAxisSetting
Definition at line 155 of file MovementComponent.h.
bInterpolationComplete
uint8 UProjectileMovementComponent::bInterpolationComplete protected
True if interpolation has reached the target, false if there is more interpolation required.
Definition at line 133 of file ProjectileMovementComponent.h.
bInterpolationUseScopedMovement
uint8 UProjectileMovementComponent::bInterpolationUseScopedMovement
If true, uses FScopedMovementUpdate to avoid moving the attached interpolated object's children more than once during a tick when it would both interpolate and move during projectile simulation.
This also defers overlap updates for the interpolated object until after the simulation update completes.
Definition at line 154 of file ProjectileMovementComponent.h.
BounceAdditionalIterations
int32 UProjectileMovementComponent::BounceAdditionalIterations
On the first few bounces (up to this amount), allow extra iterations over MaxSimulationIterations if necessary.
Definition at line 315 of file ProjectileMovementComponent.h.
BounceVelocityStopSimulatingThreshold
float UProjectileMovementComponent::BounceVelocityStopSimulatingThreshold
If velocity is below this threshold after a bounce, stops simulating and triggers the OnProjectileStop event.
Ignored if bShouldBounce is false, in which case the projectile stops simulating on the first impact.
See also
StopSimulating(), OnProjectileStop
Definition at line 195 of file ProjectileMovementComponent.h.
Bounciness
float UProjectileMovementComponent::Bounciness
Percentage of velocity maintained after the bounce in the direction of the normal of impact (coefficient of restitution).
1.0 = no velocity lost, 0.0 = no bounce. Ignored if bShouldBounce is false.
Definition at line 177 of file ProjectileMovementComponent.h.
bSimulationUseScopedMovement
uint8 UProjectileMovementComponent::bSimulationUseScopedMovement
If true, uses FScopedMovementUpdate to avoid moving the UpdatedComponent more than once during a tick during simulation.
This also defers overlap updates and some impact events until after the simulation update completes, so it may delay important events and continue deflection, so use with caution.
Definition at line 147 of file ProjectileMovementComponent.h.
bSnapToPlaneAtStart
uint8 UMovementComponent::bSnapToPlaneAtStart inherited
If true and plane constraints are enabled, then the updated component will be snapped to the plane when first attached.
Definition at line 159 of file MovementComponent.h.
bTickBeforeOwner
uint8 UMovementComponent::bTickBeforeOwner inherited
If true, after registration we will add a tick dependency to tick before our owner (if we can both tick).
This is important when our tick causes an update in the owner's position, so that when the owner ticks it uses the most recent position without lag. Disabling this can improve performance if both objects tick but the order of ticks doesn't matter.
Definition at line 144 of file MovementComponent.h.
Buoyancy
float UProjectileMovementComponent::Buoyancy
Buoyancy of UpdatedComponent in fluid.
0.0=sinks as fast as in air, 1.0=neutral buoyancy
Definition at line 170 of file ProjectileMovementComponent.h.
bUpdateOnlyIfRendered
uint8 UMovementComponent::bUpdateOnlyIfRendered inherited
If true, skips TickComponent() if UpdatedComponent was not recently rendered.
Definition at line 129 of file MovementComponent.h.
Friction
float UProjectileMovementComponent::Friction
Coefficient of friction, affecting the resistance to sliding along a surface.
Normal range is [0,1] : 0.0 = no friction, 1.0+ = very high friction. Also affects the percentage of velocity maintained after the bounce in the direction tangent to the normal of impact. Ignored if bShouldBounce is false.
See also
bBounceAngleAffectsFriction
Definition at line 187 of file ProjectileMovementComponent.h.
HomingAccelerationMagnitude
float UProjectileMovementComponent::HomingAccelerationMagnitude
The magnitude of our acceleration towards the homing target.
Overall velocity magnitude will still be limited by MaxSpeed.
Definition at line 220 of file ProjectileMovementComponent.h.
HomingTargetComponent
TWeakObjectPtr<USceneComponent> UProjectileMovementComponent::HomingTargetComponent
The current target we are homing towards.
Can only be set at runtime (when projectile is spawned or updating).
See also
bIsHomingProjectile
Definition at line 227 of file ProjectileMovementComponent.h.
InterpInitialLocationOffset
FVector UProjectileMovementComponent::InterpInitialLocationOffset protected
Definition at line 513 of file ProjectileMovementComponent.h.
InterpInitialRotationOffset
FQuat UProjectileMovementComponent::InterpInitialRotationOffset protected
Definition at line 516 of file ProjectileMovementComponent.h.
InterpLocationMaxLagDistance
float UProjectileMovementComponent::InterpLocationMaxLagDistance
Max distance behind UpdatedComponent which the interpolated component is allowed to lag.
Definition at line 364 of file ProjectileMovementComponent.h.
InterpLocationOffset
FVector UProjectileMovementComponent::InterpLocationOffset protected
Definition at line 512 of file ProjectileMovementComponent.h.
InterpLocationSnapToTargetDistance
float UProjectileMovementComponent::InterpLocationSnapToTargetDistance
Max distance behind UpdatedComponent beyond which the interpolated component is snapped to the target location instead.
For instance if the target teleports this far beyond the interpolated component, the interpolation is snapped to match the target.
Definition at line 371 of file ProjectileMovementComponent.h.
InterpLocationTime
float UProjectileMovementComponent::InterpLocationTime
"Time" over which most of the location interpolation occurs, when the UpdatedComponent (target) moves ahead of the interpolated component.
Since the implementation uses exponential lagged smoothing, this is a rough time value and experimentation should inform a final result. A value of zero is effectively instantaneous interpolation.
Definition at line 350 of file ProjectileMovementComponent.h.
InterpolatedComponentPtr
TWeakObjectPtr<USceneComponent> UProjectileMovementComponent::InterpolatedComponentPtr protected
Definition at line 514 of file ProjectileMovementComponent.h.
InterpRotationOffset
FQuat UProjectileMovementComponent::InterpRotationOffset protected
Definition at line 515 of file ProjectileMovementComponent.h.
InterpRotationTime
float UProjectileMovementComponent::InterpRotationTime
"Time" over which most of the rotation interpolation occurs, when the UpdatedComponent (target) moves ahead of the interpolated component.
Since the implementation uses exponential lagged smoothing, this is a rough time value and experimentation should inform a final result. A value of zero is effectively instantaneous interpolation.
Definition at line 358 of file ProjectileMovementComponent.h.
MaxSimulationIterations
int32 UProjectileMovementComponent::MaxSimulationIterations
Max number of iterations used for each discrete simulation step.
Increasing this value can address precision issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationTimeStep, bForceSubStepping
Definition at line 309 of file ProjectileMovementComponent.h.
MaxSimulationTimeStep
float UProjectileMovementComponent::MaxSimulationTimeStep
Max time delta for each discrete simulation step.
Lowering this value can address precision issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationIterations, bForceSubStepping
Definition at line 299 of file ProjectileMovementComponent.h.
MIN_TICK_TIME
const float UProjectileMovementComponent::MIN_TICK_TIME static protected
Minimum delta time considered when ticking.
Delta times below this are not considered. This is a very small non-zero positive value to avoid potential divide-by-zero in simulation code.
Definition at line 529 of file ProjectileMovementComponent.h.
MinFrictionFraction
float UProjectileMovementComponent::MinFrictionFraction
When bounce angle affects friction, apply at least this fraction of normal friction.
Helps consistently slow objects sliding or rolling along surfaces or in valleys when the usual friction amount would take a very long time to settle.
Definition at line 202 of file ProjectileMovementComponent.h.
OnProjectileBounce
FOnProjectileBounceDelegate UProjectileMovementComponent::OnProjectileBounce
Called when projectile impacts something and bounces are enabled.
Definition at line 212 of file ProjectileMovementComponent.h.
OnProjectileStop
FOnProjectileStopDelegate UProjectileMovementComponent::OnProjectileStop
Called when projectile has come to a stop (velocity is below simulation threshold, bounces are disabled, or it is forcibly stopped).
Definition at line 216 of file ProjectileMovementComponent.h.
PendingForceThisUpdate
FVector UProjectileMovementComponent::PendingForceThisUpdate protected
Definition at line 508 of file ProjectileMovementComponent.h.
PlaneConstraintNormal
FVector UMovementComponent::PlaneConstraintNormal protected inherited
The normal or axis of the plane that constrains movement, if bConstrainToPlane is enabled.
If for example you wanted to constrain movement to the X-Z plane (so that Y cannot change), the normal would be set to X=0 Y=1 Z=0. This is recalculated whenever PlaneConstraintAxisSetting changes. It is normalized once the component is registered with the game world.
See also
bConstrainToPlane, SetPlaneConstraintNormal(), SetPlaneConstraintFromVectors()
Definition at line 107 of file MovementComponent.h.
PlaneConstraintOrigin
FVector UMovementComponent::PlaneConstraintOrigin protected inherited
The origin of the plane that constrains movement, if plane constraint is enabled.
This defines the behavior of snapping a position to the plane, such as by SnapUpdatedComponentToPlane().
See also
bConstrainToPlane, SetPlaneConstraintOrigin().
Definition at line 115 of file MovementComponent.h.
PreviousHitNormal
FVector UProjectileMovementComponent::PreviousHitNormal
Saved HitResult Normal from previous simulation step that resulted in an impact.
If PreviousHitTime is 1.0, then the hit was not in the last step.
Definition at line 162 of file ProjectileMovementComponent.h.
PreviousHitTime
float UProjectileMovementComponent::PreviousHitTime
Saved HitResult Time (0 to 1) from previous simulation step.
Equal to 1.0 when there was no impact.
Definition at line 158 of file ProjectileMovementComponent.h.
ProjectileGravityScale
float UProjectileMovementComponent::ProjectileGravityScale
Custom gravity scale for this projectile.
Set to 0 for no gravity.
Definition at line 166 of file ProjectileMovementComponent.h.
ThrottleInterpolationFramesSinceInterp
int32 UProjectileMovementComponent::ThrottleInterpolationFramesSinceInterp protected
Tracks the number of frames since the last interpolation.
Definition at line 138 of file ProjectileMovementComponent.h.
ThrottleInterpolationSkipFramesNotRecent
int32 UProjectileMovementComponent::ThrottleInterpolationSkipFramesNotRecent
When not recently relevant, skip this many frames of interpolation if throttling is enabled.
Definition at line 395 of file ProjectileMovementComponent.h.
ThrottleInterpolationSkipFramesRecent
int32 UProjectileMovementComponent::ThrottleInterpolationSkipFramesRecent
When recently relevant, skip this many frames of interpolation if throttling is enabled.
Definition at line 389 of file ProjectileMovementComponent.h.
ThrottleInterpolationThresholdNotRenderedLongTime
float UProjectileMovementComponent::ThrottleInterpolationThresholdNotRenderedLongTime
Time after not rendered for a long time when we consider throttling interpolation.
Definition at line 383 of file ProjectileMovementComponent.h.
ThrottleInterpolationThresholdNotRenderedShortTime
float UProjectileMovementComponent::ThrottleInterpolationThresholdNotRenderedShortTime
Time after not rendered recently when we consider throttling interpolation.
Definition at line 377 of file ProjectileMovementComponent.h.
The documentation for this class was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/ProjectileMovementComponent.h