Unreal Engine 5.6 C++ API: Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType > Class Template Reference
Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType > Class Template Reference
Operator for providing delayed access to a variable.
#include "MetasoundVariableNodes.h"
Public Types
using FVariable = TVariable<DataType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TVariableDeferredAccessorOperator (TDataWriteReference< FVariable > InVariable)
virtual ~TVariableDeferredAccessorOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
Public Member Functions inherited from Metasound::FNoOpOperator
virtual ~FNoOpOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static FVertexInterface DeclareVertexInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
TDataReadReference< DataType > DelayedData
TDataWriteReference< FVariable > Variable
Detailed Description
template<typename DataType>
class Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >
Operator for providing delayed access to a variable.
Definition at line 288 of file MetasoundVariableNodes.h.
Member Typedef Documentation
FVariable
template<typename DataType> using Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::FVariable = TVariable<DataType>
Definition at line 292 of file MetasoundVariableNodes.h.
Constructor & Destructor Documentation
TVariableDeferredAccessorOperator()
template<typename DataType> Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::TVariableDeferredAccessorOperator (TDataWriteReference< FVariable > InVariable) inline
Definition at line 335 of file MetasoundVariableNodes.h.
References DelayedData, and Variable.
~TVariableDeferredAccessorOperator()
template<typename DataType> virtual Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::~TVariableDeferredAccessorOperator () virtual default
Member Function Documentation
BindInputs()
template<typename DataType> virtual void Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 362 of file MetasoundVariableNodes.h.
References Metasound::FInputVertexInterfaceData::BindWriteVertex(), checkf, Metasound::MetasoundVariableNodesPrivate::IsSupportedVertexData(), METASOUND_GET_PARAM_NAME, TEXT, and Variable.
BindOutputs()
template<typename DataType> virtual void Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 371 of file MetasoundVariableNodes.h.
References Metasound::FOutputVertexInterfaceData::BindWriteVertex(), METASOUND_GET_PARAM_NAME, and Variable.
CreateOperator()
template<typename DataType> TUniquePtr< IOperator > Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 341 of file MetasoundVariableNodes.h.
References Metasound::FInputVertexInterfaceData::FindDataReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, Metasound::FBuildOperatorParams::OperatorSettings, TEXT, UE_LOG, and Verbose.
DeclareVertexInterface()
template<typename DataType> FVertexInterface Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::DeclareVertexInterface () inline static
Definition at line 294 of file MetasoundVariableNodes.h.
References METASOUND_GET_PARAM_NAME.
Referenced by GetNodeInfo().
GetNodeInfo()
template<typename DataType> const FNodeClassMetadata & Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::GetNodeInfo () inline static
Definition at line 309 of file MetasoundVariableNodes.h.
References DeclareVertexInterface(), Metasound::VariableNames::GetVariableDeferredAccessorNodeClassName(), Info, LOCTEXT, Metadata, Metasound::PluginAuthor, and Metasound::PluginNodeMissingPrompt.
Field Documentation
DelayedData
template<typename DataType> TDataReadReference<DataType> Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::DelayedData private
Definition at line 382 of file MetasoundVariableNodes.h.
Referenced by TVariableDeferredAccessorOperator().
Variable
template<typename DataType> TDataWriteReference<FVariable> Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::Variable private
Definition at line 381 of file MetasoundVariableNodes.h.
Referenced by TVariableDeferredAccessorOperator(), BindInputs(), and BindOutputs().
The documentation for this class was generated from the following file:
MetasoundVariableNodes.h