Unreal Engine 5.6 C++ API: KeyChainUtilities Namespace Reference
KeyChainUtilities Namespace Reference
Functions
static void ApplyEncryptionKeys (const FKeyChain &KeyChain)
static void LoadKeyChainFromFile (const FString &InFilename, FKeyChain &OutCryptoSettings)
static FRSAKeyHandle ParseRSAKeyFromJson (TSharedPtr< FJsonObject > InObj)
Function Documentation
ApplyEncryptionKeys()
void KeyChainUtilities::ApplyEncryptionKeys (const FKeyChain & KeyChain) static
Definition at line 199 of file KeyChainUtilities.h.
References ApplyEncryptionKeys(), FKeyChain::GetEncryptionKeys(), FCoreDelegates::GetPakEncryptionKeyDelegate(), FCoreDelegates::GetRegisterEncryptionKeyMulticastDelegate(), FAES::FAESKey::Key, Key, and FMemory::Memcpy().
Referenced by ApplyEncryptionKeys().
LoadKeyChainFromFile()
void KeyChainUtilities::LoadKeyChainFromFile (const FString & InFilename, FKeyChain & OutCryptoSettings) static
Definition at line 139 of file KeyChainUtilities.h.
References check, checkf, IFileManager::CreateFileReader(), FBase64::Decode(), IFileManager::Get(), FKeyChain::GetEncryptionKeys(), FAES::FAESKey::Key, Key, LoadKeyChainFromFile(), FMemory::Memcpy(), FGuid::Parse(), ParseRSAKeyFromJson(), FKeyChain::SetPrincipalEncryptionKey(), FKeyChain::SetSigningKey(), and TEXT.
Referenced by LoadKeyChainFromFile().
ParseRSAKeyFromJson()
FRSAKeyHandle KeyChainUtilities::ParseRSAKeyFromJson (TSharedPtr< FJsonObject > InObj) static
Definition at line 112 of file KeyChainUtilities.h.
References check, FBase64::Decode(), ParseRSAKeyFromJson(), and TEXT.
Referenced by LoadKeyChainFromFile(), and ParseRSAKeyFromJson().