Unreal Engine 5.6 C++ API: UE::Insights::FFilterConfigurator Class Reference
UE::Insights::FFilterConfigurator Class Reference
#include "FilterConfigurator.h"
Public Member Functions
FFilterConfigurator ()
FFilterConfigurator (const FFilterConfigurator &Other)
virtual ~FFilterConfigurator ()
void Add (TSharedPtr< FFilter > InFilter)
virtual bool ApplyFilters (const FFilterContext &Context) const override
DECLARE_MULTICAST_DELEGATE (FOnChangesCommittedEvent)
The event to execute when the changes to the Filter Widget are saved by clicking on the OK Button.
DECLARE_MULTICAST_DELEGATE (FOnDestroyedEvent)
The event to execute when an instance is destroyed.
TSharedPtr< TArray< TSharedPtr< FFilter > > > & GetAvailableFilters ()
FOnChangesCommittedEvent & GetOnChangesCommittedEvent ()
FOnDestroyedEvent & GetOnDestroyedEvent ()
FFilterConfiguratorNodePtr GetRootNode ()
bool IsEmpty () const
bool IsKeyUsed (int32 Key) const
bool operator!= (const FFilterConfigurator &Other) const
FFilterConfigurator & operator= (const FFilterConfigurator &Other)
bool operator== (const FFilterConfigurator &Other) const
void Update ()
Called to update the internal state of some filters.
Public Member Functions inherited from UE::Insights::IFilterExecutor
virtual bool ApplyFilters (const class FFilterContext &Context) const =0
Private Member Functions
void ComputeUsedKeys ()
Private Attributes
TSharedPtr< TArray< TSharedPtr< FFilter > > > AvailableFilters
TSet< int32 > KeysUsed
FOnChangesCommittedEvent OnChangesCommittedEvent
FOnDestroyedEvent OnDestroyedEvent
FFilterConfiguratorNodePtr RootNode
Detailed Description
Definition at line 16 of file FilterConfigurator.h.
Constructor & Destructor Documentation
FFilterConfigurator() [1/2]
UE::Insights::FFilterConfigurator::FFilterConfigurator ()
Referenced by FFilterConfigurator(), operator!=(), operator=(), and operator==().
FFilterConfigurator() [2/2]
UE::Insights::FFilterConfigurator::FFilterConfigurator (const FFilterConfigurator & Other)
References FFilterConfigurator(), and Other.
~FFilterConfigurator()
virtual UE::Insights::FFilterConfigurator::~FFilterConfigurator () virtual
Member Function Documentation
Add()
void UE::Insights::FFilterConfigurator::Add (TSharedPtr< FFilter > InFilter) inline
Definition at line 41 of file FilterConfigurator.h.
References AvailableFilters.
ApplyFilters()
virtual bool UE::Insights::FFilterConfigurator::ApplyFilters (const FFilterContext & Context) const override virtual
ComputeUsedKeys()
void UE::Insights::FFilterConfigurator::ComputeUsedKeys () private
DECLARE_MULTICAST_DELEGATE() [1/2]
UE::Insights::FFilterConfigurator::DECLARE_MULTICAST_DELEGATE (FOnChangesCommittedEvent)
The event to execute when the changes to the Filter Widget are saved by clicking on the OK Button.
DECLARE_MULTICAST_DELEGATE() [2/2]
UE::Insights::FFilterConfigurator::DECLARE_MULTICAST_DELEGATE (FOnDestroyedEvent)
The event to execute when an instance is destroyed.
GetAvailableFilters()
TSharedPtr< TArray< TSharedPtr< FFilter > > > & UE::Insights::FFilterConfigurator::GetAvailableFilters () inline
Definition at line 39 of file FilterConfigurator.h.
References AvailableFilters.
GetOnChangesCommittedEvent()
FOnChangesCommittedEvent & UE::Insights::FFilterConfigurator::GetOnChangesCommittedEvent () inline
Definition at line 60 of file FilterConfigurator.h.
References OnChangesCommittedEvent.
GetOnDestroyedEvent()
FOnDestroyedEvent & UE::Insights::FFilterConfigurator::GetOnDestroyedEvent () inline
Definition at line 49 of file FilterConfigurator.h.
References OnDestroyedEvent.
GetRootNode()
FFilterConfiguratorNodePtr UE::Insights::FFilterConfigurator::GetRootNode () inline
Definition at line 38 of file FilterConfigurator.h.
References RootNode.
IsEmpty()
bool UE::Insights::FFilterConfigurator::IsEmpty () const inline
Definition at line 29 of file FilterConfigurator.h.
References RootNode.
IsKeyUsed()
bool UE::Insights::FFilterConfigurator::IsKeyUsed (int32 Key) const
References Key.
operator!=()
bool UE::Insights::FFilterConfigurator::operator!= (const FFilterConfigurator & Other) const inline
Definition at line 25 of file FilterConfigurator.h.
References FFilterConfigurator(), and Other.
operator=()
FFilterConfigurator & UE::Insights::FFilterConfigurator::operator= (const FFilterConfigurator & Other)
References FFilterConfigurator(), and Other.
operator==()
bool UE::Insights::FFilterConfigurator::operator== (const FFilterConfigurator & Other) const
References FFilterConfigurator(), and Other.
Update()
void UE::Insights::FFilterConfigurator::Update () inline
Called to update the internal state of some filters.
Definition at line 32 of file FilterConfigurator.h.
References RootNode.
Field Documentation
AvailableFilters
TSharedPtr<TArray<TSharedPtr<FFilter> > > UE::Insights::FFilterConfigurator::AvailableFilters private
Definition at line 73 of file FilterConfigurator.h.
Referenced by Add(), and GetAvailableFilters().
KeysUsed
TSet<int32> UE::Insights::FFilterConfigurator::KeysUsed private
Definition at line 75 of file FilterConfigurator.h.
OnChangesCommittedEvent
FOnChangesCommittedEvent UE::Insights::FFilterConfigurator::OnChangesCommittedEvent private
Definition at line 63 of file FilterConfigurator.h.
Referenced by GetOnChangesCommittedEvent().
OnDestroyedEvent
FOnDestroyedEvent UE::Insights::FFilterConfigurator::OnDestroyedEvent private
Definition at line 52 of file FilterConfigurator.h.
Referenced by GetOnDestroyedEvent().
RootNode
FFilterConfiguratorNodePtr UE::Insights::FFilterConfigurator::RootNode private
Definition at line 71 of file FilterConfigurator.h.
Referenced by GetRootNode(), IsEmpty(), and Update().
The documentation for this class was generated from the following file:
FilterConfigurator.h