Unreal Engine 5.6 C++ API: Metasound::FFilterClassesByOutputVertexDataType Class Reference
Metasound::FFilterClassesByOutputVertexDataType Class Reference
#include "MetasoundFrontendQuerySteps.h"
Public Member Functions
template<typename DataType>
FFilterClassesByOutputVertexDataType ()
METASOUNDFRONTEND_API FFilterClassesByOutputVertexDataType (const FName &InTypeName)
virtual METASOUNDFRONTEND_API bool Filter (const FFrontendQueryEntry &InEntry) const override
Public Member Functions inherited from Metasound::IFrontendQueryFilterStep
virtual ~IFrontendQueryFilterStep ()=default
Public Member Functions inherited from Metasound::IFrontendQueryStep
virtual ~IFrontendQueryStep ()=default
Private Attributes
FName OutputVertexTypeName
Detailed Description
Definition at line 84 of file MetasoundFrontendQuerySteps.h.
Constructor & Destructor Documentation
FFilterClassesByOutputVertexDataType() [1/2]
template<typename DataType> Metasound::FFilterClassesByOutputVertexDataType::FFilterClassesByOutputVertexDataType () inline
Definition at line 88 of file MetasoundFrontendQuerySteps.h.
References FFilterClassesByOutputVertexDataType(), and Metasound::GetMetasoundDataTypeName().
Referenced by FFilterClassesByOutputVertexDataType().
FFilterClassesByOutputVertexDataType() [2/2]
METASOUNDFRONTEND_API Metasound::FFilterClassesByOutputVertexDataType::FFilterClassesByOutputVertexDataType (const FName & InTypeName)
References UE_API.
Member Function Documentation
Filter()
virtual METASOUNDFRONTEND_API bool Metasound::FFilterClassesByOutputVertexDataType::Filter (const FFrontendQueryEntry & InEntry) const override virtual
Implements Metasound::IFrontendQueryFilterStep.
References UE_API.
Field Documentation
OutputVertexTypeName
FName Metasound::FFilterClassesByOutputVertexDataType::OutputVertexTypeName private
Definition at line 98 of file MetasoundFrontendQuerySteps.h.
The documentation for this class was generated from the following file:
MetasoundFrontendQuerySteps.h