Unreal Engine 5.6 C++ API: FAndroidWindowManager Class Reference
FAndroidWindowManager Class Reference
#include "AndroidWindow.h"
Data Structures
class FPendingWindowAccessor
Public Member Functions
TOptional< FAndroidWindow::FNativeAccessor > FindFromANativeWindow (bool bWriteAccess, bool bSearchPrevious, const void *SearchANativeHandle)
TOptional< FAndroidWindow::FNativeAccessor > GetMainWindowAsNativeAccessor (bool bWriteAccess)
Static Public Member Functions
static FAndroidWindowManager & Get ()
static FPendingWindowAccessor GetPendingWindowAccessor ()
Private Member Functions
int AddWindow (TSharedRef< FAndroidWindow > AddMe)
void RemoveWindow (TSharedRef< FAndroidWindow > RemoveMe)
Private Attributes
UE::FMutex WindowManagerLock
TArray< TSharedRef< FAndroidWindow > > Windows
Friends
class FAndroidWindow
Detailed Description
Definition at line 170 of file AndroidWindow.h.
Member Function Documentation
AddWindow()
int FAndroidWindowManager::AddWindow (TSharedRef< FAndroidWindow > AddMe) inline private
Definition at line 234 of file AndroidWindow.h.
References WindowManagerLock.
FindFromANativeWindow()
TOptional< FAndroidWindow::FNativeAccessor > FAndroidWindowManager::FindFromANativeWindow (bool bWriteAccess, bool bSearchPrevious, const void * SearchANativeHandle) inline
Definition at line 195 of file AndroidWindow.h.
References FAndroidWindow::GetANativeAccessor(), FAndroidWindow::FNativeAccessor::GetANativeWindow(), FAndroidWindow::FNativeAccessor::GetPreviousANativeWindow(), MoveTemp(), and WindowManagerLock.
Get()
FAndroidWindowManager & FAndroidWindowManager::Get () inline static
Definition at line 176 of file AndroidWindow.h.
References Single.
GetMainWindowAsNativeAccessor()
TOptional< FAndroidWindow::FNativeAccessor > FAndroidWindowManager::GetMainWindowAsNativeAccessor (bool bWriteAccess) inline
Definition at line 182 of file AndroidWindow.h.
References MoveTemp(), and WindowManagerLock.
GetPendingWindowAccessor()
FPendingWindowAccessor FAndroidWindowManager::GetPendingWindowAccessor () inline static
Definition at line 226 of file AndroidWindow.h.
RemoveWindow()
void FAndroidWindowManager::RemoveWindow (TSharedRef< FAndroidWindow > RemoveMe) inline private
Definition at line 241 of file AndroidWindow.h.
References WindowManagerLock.
Friends And Related Symbol Documentation
FAndroidWindow
friend class FAndroidWindow friend
Definition at line 172 of file AndroidWindow.h.
References FAndroidWindow.
Referenced by FAndroidWindow.
Field Documentation
WindowManagerLock
UE::FMutex FAndroidWindowManager::WindowManagerLock mutable private
Definition at line 247 of file AndroidWindow.h.
Referenced by AddWindow(), FindFromANativeWindow(), GetMainWindowAsNativeAccessor(), and RemoveWindow().
Windows
TArray< TSharedRef<FAndroidWindow> > FAndroidWindowManager::Windows private
Definition at line 232 of file AndroidWindow.h.
The documentation for this class was generated from the following file:
AndroidWindow.h