Unreal Engine 5.6 C++ API: UE::Geometry::TIntrLine2Line2< RealType > Class Template Reference
UE::Geometry::TIntrLine2Line2< RealType > Class Template Reference
Compute intersection between two 2D lines.
#include "IntrLine2Line2.h"
Public Member Functions
TIntrLine2Line2 (const TLine2< RealType > &Line1In, const TLine2< RealType > &Line2In)
TIntrLine2Line2 & Compute ()
bool Find ()
RealType GetDistThreshold () const
RealType GetDotThreshold () const
const TLine2< RealType > & GetLine1 () const
const TLine2< RealType > & GetLine2 () const
bool IsSimpleIntersection () const
void SetDistThreshold (RealType Value)
void SetDotThreshold (RealType Value)
void SetLine1 (const TLine2< RealType > &Value)
void SetLine2 (TLine2< RealType > &Value)
Static Public Member Functions
static EIntersectionType Classify (const TVector2< RealType > &P0, const TVector2< RealType > &D0, const TVector2< RealType > &P1, const TVector2< RealType > &D1, RealType DotThreshold, RealType DistThreshold, TVector2< RealType > &s)
Data Fields
TVector2< RealType > Point
int Quantity = 0
EIntersectionResult Result = EIntersectionResult::NotComputed
RealType Segment1Parameter
RealType Segment2Parameter
EIntersectionType Type = EIntersectionType::Empty
Protected Attributes
RealType DistThresh = TMathUtil<RealType>::ZeroTolerance
RealType dotThresh = TMathUtil<RealType>::ZeroTolerance
TLine2< RealType > Line1
TLine2< RealType > Line2
Detailed Description
template<typename RealType>
class UE::Geometry::TIntrLine2Line2< RealType >
Compute intersection between two 2D lines.
Definition at line 22 of file IntrLine2Line2.h.
Constructor & Destructor Documentation
TIntrLine2Line2()
template<typename RealType> UE::Geometry::TIntrLine2Line2< RealType >::TIntrLine2Line2 (const TLine2< RealType > & Line1In, const TLine2< RealType > & Line2In) inline
Definition at line 42 of file IntrLine2Line2.h.
Member Function Documentation
Classify()
template<typename RealType> EIntersectionType UE::Geometry::TIntrLine2Line2< RealType >::Classify (const TVector2< RealType > & P0, const TVector2< RealType > & D0, const TVector2< RealType > & P1, const TVector2< RealType > & D1, RealType DotThreshold, RealType DistThreshold, TVector2< RealType > & s) inline static
Definition at line 150 of file IntrLine2Line2.h.
Referenced by UE::Geometry::TIntrLine2Line2< double >::Find(), and UE::Geometry::TIntrSegment2Segment2< double >::Find().
Compute()
template<typename RealType> TIntrLine2Line2 & UE::Geometry::TIntrLine2Line2< RealType >::Compute () inline
Definition at line 100 of file IntrLine2Line2.h.
Find()
template<typename RealType> bool UE::Geometry::TIntrLine2Line2< RealType >::Find () inline
Definition at line 107 of file IntrLine2Line2.h.
Referenced by UE::Geometry::TIntrLine2Line2< double >::Compute().
GetDistThreshold()
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::GetDistThreshold () const inline
Definition at line 76 of file IntrLine2Line2.h.
GetDotThreshold()
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::GetDotThreshold () const inline
Definition at line 71 of file IntrLine2Line2.h.
GetLine1()
template<typename RealType> const TLine2< RealType > & UE::Geometry::TIntrLine2Line2< RealType >::GetLine1 () const inline
Definition at line 48 of file IntrLine2Line2.h.
GetLine2()
template<typename RealType> const TLine2< RealType > & UE::Geometry::TIntrLine2Line2< RealType >::GetLine2 () const inline
Definition at line 59 of file IntrLine2Line2.h.
IsSimpleIntersection()
template<typename RealType> bool UE::Geometry::TIntrLine2Line2< RealType >::IsSimpleIntersection () const inline
Definition at line 94 of file IntrLine2Line2.h.
SetDistThreshold()
template<typename RealType> void UE::Geometry::TIntrLine2Line2< RealType >::SetDistThreshold (RealType Value) inline
Definition at line 87 of file IntrLine2Line2.h.
SetDotThreshold()
template<typename RealType> void UE::Geometry::TIntrLine2Line2< RealType >::SetDotThreshold (RealType Value) inline
Definition at line 81 of file IntrLine2Line2.h.
SetLine1()
template<typename RealType> void UE::Geometry::TIntrLine2Line2< RealType >::SetLine1 (const TLine2< RealType > & Value) inline
Definition at line 53 of file IntrLine2Line2.h.
SetLine2()
template<typename RealType> void UE::Geometry::TIntrLine2Line2< RealType >::SetLine2 (TLine2< RealType > & Value) inline
Definition at line 64 of file IntrLine2Line2.h.
Field Documentation
DistThresh
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::DistThresh = TMathUtil<RealType>::ZeroTolerance protected
Definition at line 29 of file IntrLine2Line2.h.
dotThresh
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::dotThresh = TMathUtil<RealType>::ZeroTolerance protected
Definition at line 28 of file IntrLine2Line2.h.
Line1
template<typename RealType> TLine2<RealType> UE::Geometry::TIntrLine2Line2< RealType >::Line1 protected
Definition at line 26 of file IntrLine2Line2.h.
Line2
template<typename RealType> TLine2<RealType> UE::Geometry::TIntrLine2Line2< RealType >::Line2 protected
Definition at line 27 of file IntrLine2Line2.h.
Point
template<typename RealType> TVector2<RealType> UE::Geometry::TIntrLine2Line2< RealType >::Point
Definition at line 33 of file IntrLine2Line2.h.
Quantity
template<typename RealType> int UE::Geometry::TIntrLine2Line2< RealType >::Quantity = 0
Definition at line 36 of file IntrLine2Line2.h.
Result
template<typename RealType> EIntersectionResult UE::Geometry::TIntrLine2Line2< RealType >::Result = EIntersectionResult::NotComputed
Definition at line 37 of file IntrLine2Line2.h.
Segment1Parameter
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::Segment1Parameter
Definition at line 34 of file IntrLine2Line2.h.
Segment2Parameter
template<typename RealType> RealType UE::Geometry::TIntrLine2Line2< RealType >::Segment2Parameter
Definition at line 35 of file IntrLine2Line2.h.
Type
template<typename RealType> EIntersectionType UE::Geometry::TIntrLine2Line2< RealType >::Type = EIntersectionType::Empty
Definition at line 38 of file IntrLine2Line2.h.
The documentation for this class was generated from the following file:
IntrLine2Line2.h