Unreal Engine 5.6 C++ API: SAudioSpectrumPlot Class Reference
SAudioSpectrumPlot Class Reference
Slate Widget for plotting an audio power spectrum, with linear or log frequency scale, and decibels sound levels.
#include "SAudioSpectrumPlot.h"
Public Member Functions
AUDIOWIDGETS_API TSharedRef< const FExtensionBase > AddContextMenuExtension (EExtensionHook::Position HookPosition, const TSharedPtr< FUICommandList > &CommandList, const FMenuExtensionDelegate &MenuExtensionDelegate)
AUDIOWIDGETS_API FAudioSpectrumPlotScaleInfo GetScaleInfo () const
virtual AUDIOWIDGETS_API FReply OnMouseButtonDown (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual AUDIOWIDGETS_API FReply OnMouseButtonUp (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual AUDIOWIDGETS_API void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual AUDIOWIDGETS_API FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
AUDIOWIDGETS_API void RemoveContextMenuExtension (const TSharedRef< const FExtensionBase > &Extension)
void SetAllowContextMenu (bool bInAllowContextMenu)
void SetDisplayCrosshair (bool bInDisplayCrosshair)
void SetDisplayFrequencyAxisLabels (bool bInDisplayFrequencyAxisLabels)
void SetDisplayFrequencyGridLines (bool bInDisplayFrequencyGridLines)
void SetDisplaySoundLevelAxisLabels (bool bInDisplaySoundLevelAxisLabels)
void SetDisplaySoundLevelGridLines (bool bInDisplaySoundLevelGridLines)
void SetFrequencyAxisPixelBucketMode (EAudioSpectrumPlotFrequencyAxisPixelBucketMode InFrequencyAxisPixelBucketMode)
void SetFrequencyAxisScale (EAudioSpectrumPlotFrequencyAxisScale InFrequencyAxisScale)
void SetSelectedFrequency (TOptional< float > InSelectedFrequency)
void SetTiltExponent (float InTiltExponent)
void SetTiltPivotFrequency (float InTiltPivotFrequency)
void SetViewMaxFrequency (float InViewMaxFrequency)
void SetViewMaxSoundLevel (float InViewMaxSoundLevel)
void SetViewMinFrequency (float InViewMinFrequency)
void SetViewMinSoundLevel (float InViewMinSoundLevel)
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor SLATE_ATTRIBUTE (bool, AllowContextMenu) SLATE_EVENT(FOnContextMenuOpening
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency SLATE_ATTRIBUTE (bool, DisplayCrosshair) SLATE_ATTRIBUTE(bool
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels SLATE_ATTRIBUTE (bool, DisplaySoundLevelAxisLabels) SLATE_ATTRIBUTE(bool
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines SLATE_ATTRIBUTE (bool, DisplaySoundLevelGridLines) SLATE_ATTRIBUTE(EAudioSpectrumPlotFrequencyAxisScale
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale SLATE_ATTRIBUTE (EAudioSpectrumPlotFrequencyAxisPixelBucketMode, FrequencyAxisPixelBucketMode) SLATE_ATTRIBUTE(FSlateColor
ViewMinFrequency ViewMinSoundLevel TiltExponent SLATE_ATTRIBUTE (float, TiltPivotFrequency) SLATE_ATTRIBUTE(TOptional< float >
ViewMinFrequency SLATE_ATTRIBUTE (float, ViewMaxFrequency) SLATE_ATTRIBUTE(float
ViewMinFrequency ViewMinSoundLevel SLATE_ATTRIBUTE (float, ViewMaxSoundLevel) SLATE_ATTRIBUTE(float
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SLATE_ATTRIBUTE (FSlateColor, CrosshairColor) SLATE_ATTRIBUTE(FSlateColor
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor SLATE_ATTRIBUTE (FSlateColor, GridColor) SLATE_ATTRIBUTE(FSlateColor
SLATE_BEGIN_ARGS (SAudioSpectrumPlot)
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked OnDisplayFrequencyAxisLabelsButtonToggled OnGetAudioSpectrumData SLATE_END_ARGS () AUDIOWIDGETS_API void Construct(const FArguments &InArgs)
Constructs this widget with InArgs.
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked OnDisplayFrequencyAxisLabelsButtonToggled SLATE_EVENT (FOnDisplayAxisLabelsButtonToggled, OnDisplaySoundLevelAxisLabelsButtonToggled) SLATE_EVENT(FGetAudioSpectrumData
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked SLATE_EVENT (FOnFrequencyAxisScaleMenuEntryClicked, OnFrequencyAxisScaleMenuEntryClicked) SLATE_EVENT(FOnDisplayAxisLabelsButtonToggled
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening SLATE_EVENT (FOnTiltSpectrumMenuEntryClicked, OnTiltSpectrumMenuEntryClicked) SLATE_EVENT(FOnFrequencyAxisPixelBucketModeMenuEntryClicked
SLATE_STYLE_ARGUMENT (FAudioSpectrumPlotStyle, Style) SLATE_ATTRIBUTE(float
void UnbindOnGetAudioSpectrumData ()
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static AUDIOWIDGETS_API float GetTiltExponentValue (const EAudioSpectrumPlotTilt InTilt)
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Private Member Functions
AUDIOWIDGETS_API TSharedRef< SWidget > BuildDefaultContextMenu ()
AUDIOWIDGETS_API void BuildFrequencyAxisPixelBucketModeSubMenu (FMenuBuilder &SubMenu)
AUDIOWIDGETS_API void BuildFrequencyAxisScaleSubMenu (FMenuBuilder &SubMenu)
AUDIOWIDGETS_API void BuildTiltSpectrumSubMenu (FMenuBuilder &SubMenu)
AUDIOWIDGETS_API int32 DrawCrosshairAndAxisLabels (const FGeometry &AllottedGeometry, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, const FAudioSpectrumPlotScaleInfo &ScaleInfo, TConstArrayView< FVector2f > LinePoints) const
AUDIOWIDGETS_API int32 DrawGrid (const FGeometry &AllottedGeometry, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, const FAudioSpectrumPlotScaleInfo &ScaleInfo) const
AUDIOWIDGETS_API int32 DrawPowerSpectrum (const FGeometry &AllottedGeometry, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, const FAudioSpectrumPlotScaleInfo &ScaleInfo) const
AUDIOWIDGETS_API int32 DrawSolidBackgroundRectangle (const FGeometry &AllottedGeometry, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle) const
AUDIOWIDGETS_API FLinearColor GetAxisLabelColor (const FWidgetStyle &InWidgetStyle) const
AUDIOWIDGETS_API FLinearColor GetBackgroundColor (const FWidgetStyle &InWidgetStyle) const
AUDIOWIDGETS_API FLinearColor GetCrosshairColor (const FWidgetStyle &InWidgetStyle) const
AUDIOWIDGETS_API FLinearColor GetGridColor (const FWidgetStyle &InWidgetStyle) const
AUDIOWIDGETS_API void GetGridLineFrequencies (TArray< float > &AllGridLineFrequencies, TArray< float > &MajorGridLineFrequencies) const
AUDIOWIDGETS_API void GetGridLineSoundLevels (TArray< float > &GridLineSoundLevels) const
AUDIOWIDGETS_API FAudioPowerSpectrumData GetPowerSpectrum () const
AUDIOWIDGETS_API FLinearColor GetSpectrumColor (const FWidgetStyle &InWidgetStyle) const
virtual AUDIOWIDGETS_API int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Static Private Member Functions
static AUDIOWIDGETS_API void GetSpectrumLinePoints (TArray< FVector2f > &OutLinePoints, TConstArrayView< FVector2f > DataPoints, const FAudioSpectrumPlotScaleInfo &ScaleInfo, TFunctionRef< float(const FVector2f &DataPoint)> CostFunction)
Private Attributes
TAttribute< FSlateColor > AxisLabelColor
TAttribute< FSlateColor > BackgroundColor
TAttribute< bool > bAllowContextMenu
TAttribute< bool > bDisplayCrosshair
TAttribute< bool > bDisplayFrequencyAxisLabels
TAttribute< bool > bDisplayFrequencyGridLines
TAttribute< bool > bDisplaySoundLevelAxisLabels
TAttribute< bool > bDisplaySoundLevelGridLines
TSharedPtr< FExtender > ContextMenuExtender
TAttribute< FSlateColor > CrosshairColor
TAttribute< EAudioSpectrumPlotFrequencyAxisPixelBucketMode > FrequencyAxisPixelBucketMode
TAttribute< EAudioSpectrumPlotFrequencyAxisScale > FrequencyAxisScale
TAttribute< FSlateColor > GridColor
FOnContextMenuOpening OnContextMenuOpening
FOnDisplayAxisLabelsButtonToggled OnDisplayFrequencyAxisLabelsButtonToggled
FOnDisplayAxisLabelsButtonToggled OnDisplaySoundLevelAxisLabelsButtonToggled
FOnFrequencyAxisPixelBucketModeMenuEntryClicked OnFrequencyAxisPixelBucketModeMenuEntryClicked
FOnFrequencyAxisScaleMenuEntryClicked OnFrequencyAxisScaleMenuEntryClicked
FGetAudioSpectrumData OnGetAudioSpectrumData
FOnTiltSpectrumMenuEntryClicked OnTiltSpectrumMenuEntryClicked
TAttribute< TOptional< float > > SelectedFrequency
TAttribute< FSlateColor > SpectrumColor
const FAudioSpectrumPlotStyle * Style
TAttribute< float > TiltExponent
TAttribute< float > TiltPivotFrequency
TAttribute< float > ViewMaxFrequency
TAttribute< float > ViewMaxSoundLevel
TAttribute< float > ViewMinFrequency
TAttribute< float > ViewMinSoundLevel
Static Private Attributes
static AUDIOWIDGETS_API const float ClampMinSoundLevel
static AUDIOWIDGETS_API FName ContextMenuExtensionHook
Additional Inherited Members
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Slate Widget for plotting an audio power spectrum, with linear or log frequency scale, and decibels sound levels.
Definition at line 132 of file SAudioSpectrumPlot.h.
Member Function Documentation
AddContextMenuExtension()
AUDIOWIDGETS_API TSharedRef< const FExtensionBase > SAudioSpectrumPlot::AddContextMenuExtension (EExtensionHook::Position HookPosition, const TSharedPtr< FUICommandList > & CommandList, const FMenuExtensionDelegate & MenuExtensionDelegate)
References UE_API.
BuildDefaultContextMenu()
AUDIOWIDGETS_API TSharedRef< SWidget > SAudioSpectrumPlot::BuildDefaultContextMenu () private
References UE_API.
BuildFrequencyAxisPixelBucketModeSubMenu()
AUDIOWIDGETS_API void SAudioSpectrumPlot::BuildFrequencyAxisPixelBucketModeSubMenu (FMenuBuilder & SubMenu) private
References UE_API.
BuildFrequencyAxisScaleSubMenu()
AUDIOWIDGETS_API void SAudioSpectrumPlot::BuildFrequencyAxisScaleSubMenu (FMenuBuilder & SubMenu) private
References UE_API.
BuildTiltSpectrumSubMenu()
AUDIOWIDGETS_API void SAudioSpectrumPlot::BuildTiltSpectrumSubMenu (FMenuBuilder & SubMenu) private
References UE_API.
DrawCrosshairAndAxisLabels()
AUDIOWIDGETS_API int32 SAudioSpectrumPlot::DrawCrosshairAndAxisLabels (const FGeometry & AllottedGeometry, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, const FAudioSpectrumPlotScaleInfo & ScaleInfo, TConstArrayView< FVector2f > LinePoints) const private
References SWidget::FSlateWindowElementList, and UE_API.
DrawGrid()
AUDIOWIDGETS_API int32 SAudioSpectrumPlot::DrawGrid (const FGeometry & AllottedGeometry, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, const FAudioSpectrumPlotScaleInfo & ScaleInfo) const private
References SWidget::FSlateWindowElementList, and UE_API.
DrawPowerSpectrum()
AUDIOWIDGETS_API int32 SAudioSpectrumPlot::DrawPowerSpectrum (const FGeometry & AllottedGeometry, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, const FAudioSpectrumPlotScaleInfo & ScaleInfo) const private
References SWidget::FSlateWindowElementList, and UE_API.
DrawSolidBackgroundRectangle()
AUDIOWIDGETS_API int32 SAudioSpectrumPlot::DrawSolidBackgroundRectangle (const FGeometry & AllottedGeometry, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle) const private
References SWidget::FSlateWindowElementList, and UE_API.
GetAxisLabelColor()
AUDIOWIDGETS_API FLinearColor SAudioSpectrumPlot::GetAxisLabelColor (const FWidgetStyle & InWidgetStyle) const private
References UE_API.
GetBackgroundColor()
AUDIOWIDGETS_API FLinearColor SAudioSpectrumPlot::GetBackgroundColor (const FWidgetStyle & InWidgetStyle) const private
References UE_API.
GetCrosshairColor()
AUDIOWIDGETS_API FLinearColor SAudioSpectrumPlot::GetCrosshairColor (const FWidgetStyle & InWidgetStyle) const private
References UE_API.
GetGridColor()
AUDIOWIDGETS_API FLinearColor SAudioSpectrumPlot::GetGridColor (const FWidgetStyle & InWidgetStyle) const private
References UE_API.
GetGridLineFrequencies()
AUDIOWIDGETS_API void SAudioSpectrumPlot::GetGridLineFrequencies (TArray< float > & AllGridLineFrequencies, TArray< float > & MajorGridLineFrequencies) const private
References UE_API.
GetGridLineSoundLevels()
AUDIOWIDGETS_API void SAudioSpectrumPlot::GetGridLineSoundLevels (TArray< float > & GridLineSoundLevels) const private
References UE_API.
GetPowerSpectrum()
AUDIOWIDGETS_API FAudioPowerSpectrumData SAudioSpectrumPlot::GetPowerSpectrum () const private
References UE_API.
GetScaleInfo()
AUDIOWIDGETS_API FAudioSpectrumPlotScaleInfo SAudioSpectrumPlot::GetScaleInfo () const
References UE_API.
GetSpectrumColor()
AUDIOWIDGETS_API FLinearColor SAudioSpectrumPlot::GetSpectrumColor (const FWidgetStyle & InWidgetStyle) const private
References UE_API.
GetSpectrumLinePoints()
AUDIOWIDGETS_API void SAudioSpectrumPlot::GetSpectrumLinePoints (TArray< FVector2f > & OutLinePoints, TConstArrayView< FVector2f > DataPoints, const FAudioSpectrumPlotScaleInfo & ScaleInfo, TFunctionRef< float(const FVector2f &DataPoint)> CostFunction) static private
References UE_API.
GetTiltExponentValue()
AUDIOWIDGETS_API float SAudioSpectrumPlot::GetTiltExponentValue (const EAudioSpectrumPlotTilt InTilt) static
References UE_API.
OnMouseButtonDown()
virtual AUDIOWIDGETS_API FReply SAudioSpectrumPlot::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References UE_API.
OnMouseButtonUp()
virtual AUDIOWIDGETS_API FReply SAudioSpectrumPlot::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References UE_API.
OnMouseLeave()
virtual AUDIOWIDGETS_API void SAudioSpectrumPlot::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent, and UE_API.
OnMouseMove()
virtual AUDIOWIDGETS_API FReply SAudioSpectrumPlot::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and UE_API.
OnPaint()
virtual AUDIOWIDGETS_API int32 SAudioSpectrumPlot::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override private virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from SCompoundWidget.
References SWidget::FSlateWindowElementList, and UE_API.
RemoveContextMenuExtension()
AUDIOWIDGETS_API void SAudioSpectrumPlot::RemoveContextMenuExtension (const TSharedRef< const FExtensionBase > & Extension)
References UE_API.
SetAllowContextMenu()
void SAudioSpectrumPlot::SetAllowContextMenu (bool bInAllowContextMenu) inline
Definition at line 204 of file SAudioSpectrumPlot.h.
References bAllowContextMenu.
SetDisplayCrosshair()
void SAudioSpectrumPlot::SetDisplayCrosshair (bool bInDisplayCrosshair) inline
Definition at line 197 of file SAudioSpectrumPlot.h.
References bDisplayCrosshair.
SetDisplayFrequencyAxisLabels()
void SAudioSpectrumPlot::SetDisplayFrequencyAxisLabels (bool bInDisplayFrequencyAxisLabels) inline
Definition at line 198 of file SAudioSpectrumPlot.h.
References bDisplayFrequencyAxisLabels.
SetDisplayFrequencyGridLines()
void SAudioSpectrumPlot::SetDisplayFrequencyGridLines (bool bInDisplayFrequencyGridLines) inline
Definition at line 200 of file SAudioSpectrumPlot.h.
References bDisplayFrequencyGridLines.
SetDisplaySoundLevelAxisLabels()
void SAudioSpectrumPlot::SetDisplaySoundLevelAxisLabels (bool bInDisplaySoundLevelAxisLabels) inline
Definition at line 199 of file SAudioSpectrumPlot.h.
References bDisplaySoundLevelAxisLabels.
SetDisplaySoundLevelGridLines()
void SAudioSpectrumPlot::SetDisplaySoundLevelGridLines (bool bInDisplaySoundLevelGridLines) inline
Definition at line 201 of file SAudioSpectrumPlot.h.
References bDisplaySoundLevelGridLines.
SetFrequencyAxisPixelBucketMode()
void SAudioSpectrumPlot::SetFrequencyAxisPixelBucketMode (EAudioSpectrumPlotFrequencyAxisPixelBucketMode InFrequencyAxisPixelBucketMode) inline
Definition at line 203 of file SAudioSpectrumPlot.h.
References FrequencyAxisPixelBucketMode.
SetFrequencyAxisScale()
void SAudioSpectrumPlot::SetFrequencyAxisScale (EAudioSpectrumPlotFrequencyAxisScale InFrequencyAxisScale) inline
Definition at line 202 of file SAudioSpectrumPlot.h.
References FrequencyAxisScale.
SetSelectedFrequency()
void SAudioSpectrumPlot::SetSelectedFrequency (TOptional< float > InSelectedFrequency) inline
Definition at line 196 of file SAudioSpectrumPlot.h.
References SelectedFrequency.
SetTiltExponent()
void SAudioSpectrumPlot::SetTiltExponent (float InTiltExponent) inline
Definition at line 194 of file SAudioSpectrumPlot.h.
References TiltExponent.
SetTiltPivotFrequency()
void SAudioSpectrumPlot::SetTiltPivotFrequency (float InTiltPivotFrequency) inline
Definition at line 195 of file SAudioSpectrumPlot.h.
References TiltPivotFrequency.
SetViewMaxFrequency()
void SAudioSpectrumPlot::SetViewMaxFrequency (float InViewMaxFrequency) inline
Definition at line 191 of file SAudioSpectrumPlot.h.
References ViewMaxFrequency.
SetViewMaxSoundLevel()
void SAudioSpectrumPlot::SetViewMaxSoundLevel (float InViewMaxSoundLevel) inline
Definition at line 193 of file SAudioSpectrumPlot.h.
References ViewMaxSoundLevel.
SetViewMinFrequency()
void SAudioSpectrumPlot::SetViewMinFrequency (float InViewMinFrequency) inline
Definition at line 190 of file SAudioSpectrumPlot.h.
References SetViewMinFrequency(), and ViewMinFrequency.
Referenced by SetViewMinFrequency().
SetViewMinSoundLevel()
void SAudioSpectrumPlot::SetViewMinSoundLevel (float InViewMinSoundLevel) inline
Definition at line 192 of file SAudioSpectrumPlot.h.
References ViewMinSoundLevel.
SLATE_ATTRIBUTE() [1/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor SAudioSpectrumPlot::SLATE_ATTRIBUTE (bool , AllowContextMenu)
References OnContextMenuOpening, SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [2/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency SAudioSpectrumPlot::SLATE_ATTRIBUTE (bool , DisplayCrosshair)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels SAudioSpectrumPlot::SLATE_ATTRIBUTE (bool , DisplaySoundLevelAxisLabels)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines SAudioSpectrumPlot::SLATE_ATTRIBUTE (bool , DisplaySoundLevelGridLines)
References FrequencyAxisScale, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [5/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale SAudioSpectrumPlot::SLATE_ATTRIBUTE (EAudioSpectrumPlotFrequencyAxisPixelBucketMode , FrequencyAxisPixelBucketMode)
References BackgroundColor, FrequencyAxisPixelBucketMode, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [6/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SAudioSpectrumPlot::SLATE_ATTRIBUTE (float , TiltPivotFrequency)
References SelectedFrequency, SLATE_ATTRIBUTE(), and TiltPivotFrequency.
SLATE_ATTRIBUTE() [7/10]
ViewMinFrequency SAudioSpectrumPlot::SLATE_ATTRIBUTE (float , ViewMaxFrequency)
References SLATE_ATTRIBUTE(), ViewMaxFrequency, and ViewMinSoundLevel.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [8/10]
ViewMinFrequency ViewMinSoundLevel SAudioSpectrumPlot::SLATE_ATTRIBUTE (float , ViewMaxSoundLevel)
References SLATE_ATTRIBUTE(), TiltExponent, and ViewMaxSoundLevel.
SLATE_ATTRIBUTE() [9/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SAudioSpectrumPlot::SLATE_ATTRIBUTE (FSlateColor , CrosshairColor)
References CrosshairColor, SLATE_ATTRIBUTE(), and SpectrumColor.
SLATE_ATTRIBUTE() [10/10]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor SAudioSpectrumPlot::SLATE_ATTRIBUTE (FSlateColor , GridColor)
References AxisLabelColor, GridColor, and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SAudioSpectrumPlot::SLATE_BEGIN_ARGS (SAudioSpectrumPlot) inline
Definition at line 135 of file SAudioSpectrumPlot.h.
References Average.
SLATE_END_ARGS()
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked OnDisplayFrequencyAxisLabelsButtonToggled OnGetAudioSpectrumData SAudioSpectrumPlot::SLATE_END_ARGS () const &
Constructs this widget with InArgs.
References SLATE_END_ARGS(), and UE_API.
Referenced by SLATE_END_ARGS().
SLATE_EVENT() [1/3]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked OnDisplayFrequencyAxisLabelsButtonToggled SAudioSpectrumPlot::SLATE_EVENT (FOnDisplayAxisLabelsButtonToggled , OnDisplaySoundLevelAxisLabelsButtonToggled)
References OnDisplaySoundLevelAxisLabelsButtonToggled, OnGetAudioSpectrumData, and SLATE_EVENT().
SLATE_EVENT() [2/3]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening OnFrequencyAxisPixelBucketModeMenuEntryClicked SAudioSpectrumPlot::SLATE_EVENT (FOnFrequencyAxisScaleMenuEntryClicked , OnFrequencyAxisScaleMenuEntryClicked)
References OnDisplayFrequencyAxisLabelsButtonToggled, OnFrequencyAxisScaleMenuEntryClicked, and SLATE_EVENT().
SLATE_EVENT() [3/3]
ViewMinFrequency ViewMinSoundLevel TiltExponent SelectedFrequency DisplayFrequencyAxisLabels DisplayFrequencyGridLines FrequencyAxisScale BackgroundColor AxisLabelColor SpectrumColor OnContextMenuOpening SAudioSpectrumPlot::SLATE_EVENT (FOnTiltSpectrumMenuEntryClicked , OnTiltSpectrumMenuEntryClicked)
References OnFrequencyAxisPixelBucketModeMenuEntryClicked, OnTiltSpectrumMenuEntryClicked, and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
SAudioSpectrumPlot::SLATE_STYLE_ARGUMENT (FAudioSpectrumPlotStyle , Style)
References Style, and ViewMinFrequency.
UnbindOnGetAudioSpectrumData()
void SAudioSpectrumPlot::UnbindOnGetAudioSpectrumData () inline
Definition at line 216 of file SAudioSpectrumPlot.h.
References OnGetAudioSpectrumData.
Field Documentation
AxisLabelColor
TAttribute<FSlateColor> SAudioSpectrumPlot::AxisLabelColor private
Definition at line 275 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
BackgroundColor
TAttribute<FSlateColor> SAudioSpectrumPlot::BackgroundColor private
Definition at line 273 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
bAllowContextMenu
TAttribute<bool> SAudioSpectrumPlot::bAllowContextMenu private
Definition at line 278 of file SAudioSpectrumPlot.h.
Referenced by SetAllowContextMenu().
bDisplayCrosshair
TAttribute<bool> SAudioSpectrumPlot::bDisplayCrosshair private
Definition at line 266 of file SAudioSpectrumPlot.h.
Referenced by SetDisplayCrosshair().
bDisplayFrequencyAxisLabels
TAttribute<bool> SAudioSpectrumPlot::bDisplayFrequencyAxisLabels private
Definition at line 267 of file SAudioSpectrumPlot.h.
Referenced by SetDisplayFrequencyAxisLabels().
bDisplayFrequencyGridLines
TAttribute<bool> SAudioSpectrumPlot::bDisplayFrequencyGridLines private
Definition at line 269 of file SAudioSpectrumPlot.h.
Referenced by SetDisplayFrequencyGridLines().
bDisplaySoundLevelAxisLabels
TAttribute<bool> SAudioSpectrumPlot::bDisplaySoundLevelAxisLabels private
Definition at line 268 of file SAudioSpectrumPlot.h.
Referenced by SetDisplaySoundLevelAxisLabels().
bDisplaySoundLevelGridLines
TAttribute<bool> SAudioSpectrumPlot::bDisplaySoundLevelGridLines private
Definition at line 270 of file SAudioSpectrumPlot.h.
Referenced by SetDisplaySoundLevelGridLines().
ClampMinSoundLevel
AUDIOWIDGETS_API const float SAudioSpectrumPlot::ClampMinSoundLevel static private
Definition at line 253 of file SAudioSpectrumPlot.h.
ContextMenuExtender
TSharedPtr<FExtender> SAudioSpectrumPlot::ContextMenuExtender private
Definition at line 256 of file SAudioSpectrumPlot.h.
ContextMenuExtensionHook
AUDIOWIDGETS_API FName SAudioSpectrumPlot::ContextMenuExtensionHook static private
Definition at line 255 of file SAudioSpectrumPlot.h.
CrosshairColor
TAttribute<FSlateColor> SAudioSpectrumPlot::CrosshairColor private
Definition at line 276 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
FrequencyAxisPixelBucketMode
TAttribute<EAudioSpectrumPlotFrequencyAxisPixelBucketMode> SAudioSpectrumPlot::FrequencyAxisPixelBucketMode private
Definition at line 272 of file SAudioSpectrumPlot.h.
Referenced by SetFrequencyAxisPixelBucketMode(), and SLATE_ATTRIBUTE().
FrequencyAxisScale
TAttribute<EAudioSpectrumPlotFrequencyAxisScale> SAudioSpectrumPlot::FrequencyAxisScale private
Definition at line 271 of file SAudioSpectrumPlot.h.
Referenced by SetFrequencyAxisScale(), and SLATE_ATTRIBUTE().
GridColor
TAttribute<FSlateColor> SAudioSpectrumPlot::GridColor private
Definition at line 274 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
OnContextMenuOpening
FOnContextMenuOpening SAudioSpectrumPlot::OnContextMenuOpening private
Definition at line 279 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
OnDisplayFrequencyAxisLabelsButtonToggled
FOnDisplayAxisLabelsButtonToggled SAudioSpectrumPlot::OnDisplayFrequencyAxisLabelsButtonToggled private
Definition at line 283 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT().
OnDisplaySoundLevelAxisLabelsButtonToggled
FOnDisplayAxisLabelsButtonToggled SAudioSpectrumPlot::OnDisplaySoundLevelAxisLabelsButtonToggled private
Definition at line 284 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT().
OnFrequencyAxisPixelBucketModeMenuEntryClicked
FOnFrequencyAxisPixelBucketModeMenuEntryClicked SAudioSpectrumPlot::OnFrequencyAxisPixelBucketModeMenuEntryClicked private
Definition at line 281 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT().
OnFrequencyAxisScaleMenuEntryClicked
FOnFrequencyAxisScaleMenuEntryClicked SAudioSpectrumPlot::OnFrequencyAxisScaleMenuEntryClicked private
Definition at line 282 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT().
OnGetAudioSpectrumData
FGetAudioSpectrumData SAudioSpectrumPlot::OnGetAudioSpectrumData private
Definition at line 285 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT(), and UnbindOnGetAudioSpectrumData().
OnTiltSpectrumMenuEntryClicked
FOnTiltSpectrumMenuEntryClicked SAudioSpectrumPlot::OnTiltSpectrumMenuEntryClicked private
Definition at line 280 of file SAudioSpectrumPlot.h.
Referenced by SLATE_EVENT().
SelectedFrequency
TAttribute<TOptional<float> > SAudioSpectrumPlot::SelectedFrequency private
Definition at line 265 of file SAudioSpectrumPlot.h.
Referenced by SetSelectedFrequency(), and SLATE_ATTRIBUTE().
SpectrumColor
TAttribute<FSlateColor> SAudioSpectrumPlot::SpectrumColor private
Definition at line 277 of file SAudioSpectrumPlot.h.
Referenced by SLATE_ATTRIBUTE().
Style
const FAudioSpectrumPlotStyle* SAudioSpectrumPlot::Style private
Definition at line 258 of file SAudioSpectrumPlot.h.
Referenced by SLATE_STYLE_ARGUMENT().
TiltExponent
TAttribute<float> SAudioSpectrumPlot::TiltExponent private
Definition at line 263 of file SAudioSpectrumPlot.h.
Referenced by SetTiltExponent(), and SLATE_ATTRIBUTE().
TiltPivotFrequency
TAttribute<float> SAudioSpectrumPlot::TiltPivotFrequency private
Definition at line 264 of file SAudioSpectrumPlot.h.
Referenced by SetTiltPivotFrequency(), and SLATE_ATTRIBUTE().
ViewMaxFrequency
TAttribute<float> SAudioSpectrumPlot::ViewMaxFrequency private
Definition at line 260 of file SAudioSpectrumPlot.h.
Referenced by SetViewMaxFrequency(), and SLATE_ATTRIBUTE().
ViewMaxSoundLevel
TAttribute<float> SAudioSpectrumPlot::ViewMaxSoundLevel private
Definition at line 262 of file SAudioSpectrumPlot.h.
Referenced by SetViewMaxSoundLevel(), and SLATE_ATTRIBUTE().
ViewMinFrequency
TAttribute<float> SAudioSpectrumPlot::ViewMinFrequency private
Definition at line 259 of file SAudioSpectrumPlot.h.
Referenced by SetViewMinFrequency(), and SLATE_STYLE_ARGUMENT().
ViewMinSoundLevel
TAttribute<float> SAudioSpectrumPlot::ViewMinSoundLevel private
Definition at line 261 of file SAudioSpectrumPlot.h.
Referenced by SetViewMinSoundLevel(), and SLATE_ATTRIBUTE().
The documentation for this class was generated from the following file:
SAudioSpectrumPlot.h