Unreal Engine 5.6 C++ API: FPinchBrushOp Class Reference
FPinchBrushOp Class Reference
#include "MeshPinchBrushOps.h"
Public Member Functions
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) override
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual ESculptBrushOpTargetType GetBrushTargetType () const
Public Member Functions inherited from FMeshSculptBrushOp
virtual ~FMeshSculptBrushOp ()
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual bool GetAlignStampToView () const
virtual EBrushRegionType GetBrushRegionType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool IgnoreZeroMovements () const
virtual bool SupportsVariableSpacing () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool UsesAlpha () const
virtual bool WantsStampRegionPlane () const
Data Fields
double BrushSpeedTuning = 3.0
FVector3d LastSmoothBrushNormalLocal
FVector3d LastSmoothBrushPosLocal
Data Fields inherited from FMeshSculptBrushOp
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Additional Inherited Members
Public Types inherited from FMeshSculptBrushOp
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Detailed Description
Definition at line 41 of file MeshPinchBrushOps.h.
Member Function Documentation
ApplyStamp()
virtual void FPinchBrushOp::ApplyStamp (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) inline override virtual
Implements FMeshSculptBrushOp.
Definition at line 57 of file MeshPinchBrushOps.h.
References BrushSpeedTuning, FSculptBrushStamp::DeltaTime, FSculptBrushStamp::Depth, FSculptBrushStamp::Direction, FMeshSculptBrushOp::GetPropertySetAs(), LastSmoothBrushNormalLocal, LastSmoothBrushPosLocal, UE::Math::TVector< T >::Length(), UE::Geometry::Lerp(), FSculptBrushStamp::LocalFrame, Mesh, UE::Geometry::Normalize, UE::Geometry::TFrame3< RealType >::Origin, ParallelFor(), FSculptBrushStamp::Power, FSculptBrushStamp::Radius, UE::Geometry::TFrame3< RealType >::Z(), and TMathUtilConstants< double >::ZeroTolerance.
BeginStroke()
virtual void FPinchBrushOp::BeginStroke (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & InitialVertices) inline virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 50 of file MeshPinchBrushOps.h.
References LastSmoothBrushNormalLocal, LastSmoothBrushPosLocal, FSculptBrushStamp::LocalFrame, Mesh, UE::Geometry::TFrame3< RealType >::Origin, and UE::Geometry::TFrame3< RealType >::Z().
GetBrushTargetType()
virtual ESculptBrushOpTargetType FPinchBrushOp::GetBrushTargetType () const inline virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 104 of file MeshPinchBrushOps.h.
References TargetMesh.
Field Documentation
BrushSpeedTuning
double FPinchBrushOp::BrushSpeedTuning = 3.0
Definition at line 45 of file MeshPinchBrushOps.h.
Referenced by ApplyStamp().
LastSmoothBrushNormalLocal
FVector3d FPinchBrushOp::LastSmoothBrushNormalLocal
Definition at line 48 of file MeshPinchBrushOps.h.
Referenced by ApplyStamp(), and BeginStroke().
LastSmoothBrushPosLocal
FVector3d FPinchBrushOp::LastSmoothBrushPosLocal
Definition at line 47 of file MeshPinchBrushOps.h.
Referenced by ApplyStamp(), and BeginStroke().
The documentation for this class was generated from the following file:
MeshPinchBrushOps.h