Unreal Engine 5.6 C++ API: IDetailRootObjectCustomization Class Reference
IDetailRootObjectCustomization Class Reference
Interface for any class that lays out details for a specific class.
#include "IDetailRootObjectCustomization.h"
Public Types
enum EExpansionArrowUsage { Custom , Default , None }
Public Member Functions
virtual ~IDetailRootObjectCustomization ()
virtual bool AreObjectsVisible (const FDetailsObjectSet &InRootObjectSet) const
Whether or not the objects and all of its children should be visible in the details panel.
virtual TSharedPtr< SWidget > CustomizeObjectHeader (const FDetailsObjectSet &InRootObjectSet)
Called when the details panel wants to display an object header widget for a given object.
virtual TSharedPtr< SWidget > CustomizeObjectHeader (const FDetailsObjectSet &InRootObjectSet, const TSharedPtr< ITableRow > &InTableRow)
Called when the details panel wants to display an object header widget for a given object.
virtual EExpansionArrowUsage GetExpansionArrowUsage () const
Gets the setup for expansion arrows in this customization.
virtual bool ShouldDisplayHeader (const FDetailsObjectSet &InRootObjectSet) const
Whether or not the object should have a header displayed or just show the children directly.
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (4.25, "Please use the AreObjectsVisible instead") virtual bool IsObjectVisible(const UObject *InRootObject) const
UE_DEPRECATED (4.25, "Please use the CustomizeObjectHeader version which takes in an array of root objects") virtual TSharedPtr< SWidget > CustomizeObjectHeader(const UObject *InRootObject
UE_DEPRECATED (4.25, "Please use the CustomizeObjectHeader version which takes in an array of root objects") virtual TSharedPtr< SWidget > CustomizeObjectHeader(const UObject *InRootObject)
UE_DEPRECATED (4.25, "Please use the ShouldDisplayHeader version which takes in an array of objects instead") virtual bool ShouldDisplayHeader(const UObject *InRootObject) const
Public Member Functions inherited from TSharedFromThis< IDetailRootObjectCustomization >
TSharedRef< IDetailRootObjectCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDetailRootObjectCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
const TSharedPtr< ITableRow > & InTableRow
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IDetailRootObjectCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IDetailRootObjectCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Interface for any class that lays out details for a specific class.
Definition at line 22 of file IDetailRootObjectCustomization.h.
Member Enumeration Documentation
EExpansionArrowUsage
enum IDetailRootObjectCustomization::EExpansionArrowUsage
Enumerator
Custom
Default
None
Definition at line 25 of file IDetailRootObjectCustomization.h.
Constructor & Destructor Documentation
~IDetailRootObjectCustomization()
virtual IDetailRootObjectCustomization::~IDetailRootObjectCustomization () inline virtual
Definition at line 32 of file IDetailRootObjectCustomization.h.
Member Function Documentation
AreObjectsVisible()
virtual bool IDetailRootObjectCustomization::AreObjectsVisible (const FDetailsObjectSet & InRootObjectSet) const inline virtual
Whether or not the objects and all of its children should be visible in the details panel.
Definition at line 62 of file IDetailRootObjectCustomization.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and FDetailsObjectSet::RootObjects.
CustomizeObjectHeader() [1/2]
virtual TSharedPtr< SWidget > IDetailRootObjectCustomization::CustomizeObjectHeader (const FDetailsObjectSet & InRootObjectSet) inline virtual
Called when the details panel wants to display an object header widget for a given object.
Parameters
InRootObjects The object set whose header is being customized
Definition at line 39 of file IDetailRootObjectCustomization.h.
References CustomizeObjectHeader(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and FDetailsObjectSet::RootObjects.
Referenced by CustomizeObjectHeader(), CustomizeObjectHeader(), and UE_DEPRECATED().
CustomizeObjectHeader() [2/2]
virtual TSharedPtr< SWidget > IDetailRootObjectCustomization::CustomizeObjectHeader (const FDetailsObjectSet & InRootObjectSet, const TSharedPtr< ITableRow > & InTableRow) inline virtual
Called when the details panel wants to display an object header widget for a given object.
Parameters
InRootObjects The object set whose header is being customized
InTableRow The ITableRow object (table views to talk to their rows) that will use the current IDetailRootObjectCustomization element. This may be null if the customization is not being shown in a table view
Definition at line 52 of file IDetailRootObjectCustomization.h.
References CustomizeObjectHeader(), InTableRow, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and FDetailsObjectSet::RootObjects.
GetExpansionArrowUsage()
virtual EExpansionArrowUsage IDetailRootObjectCustomization::GetExpansionArrowUsage () const inline virtual
Gets the setup for expansion arrows in this customization.
Definition at line 107 of file IDetailRootObjectCustomization.h.
References None.
ShouldDisplayHeader()
virtual bool IDetailRootObjectCustomization::ShouldDisplayHeader (const FDetailsObjectSet & InRootObjectSet) const inline virtual
Whether or not the object should have a header displayed or just show the children directly.
Returns
true if the this customization should be displayed or false to just show the children directly
Definition at line 74 of file IDetailRootObjectCustomization.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, FDetailsObjectSet::RootObjects, and ShouldDisplayHeader().
Referenced by ShouldDisplayHeader(), and UE_DEPRECATED().
UE_DEPRECATED() [1/4]
PRAGMA_ENABLE_DEPRECATION_WARNINGS IDetailRootObjectCustomization::UE_DEPRECATED (4. 25, "Please use the AreObjectsVisible instead") const inline
Definition at line 95 of file IDetailRootObjectCustomization.h.
UE_DEPRECATED() [2/4]
IDetailRootObjectCustomization::UE_DEPRECATED (4. 25, "Please use the CustomizeObjectHeader version which takes in an array of root objects") const
UE_DEPRECATED() [3/4]
IDetailRootObjectCustomization::UE_DEPRECATED (4. 25, "Please use the CustomizeObjectHeader version which takes in an array of root objects") const inline
Definition at line 81 of file IDetailRootObjectCustomization.h.
References CustomizeObjectHeader().
UE_DEPRECATED() [4/4]
IDetailRootObjectCustomization::UE_DEPRECATED (4. 25, "Please use the ShouldDisplayHeader version which takes in an array of objects instead") const inline
Definition at line 98 of file IDetailRootObjectCustomization.h.
References ShouldDisplayHeader().
Field Documentation
InTableRow
const TSharedPtr<ITableRow>& IDetailRootObjectCustomization::InTableRow
Initial value:
{
        PRAGMA_DISABLE_DEPRECATION_WARNINGS
        return CustomizeObjectHeader(InRootObject)
Definition at line 88 of file IDetailRootObjectCustomization.h.
Referenced by CustomizeObjectHeader().
The documentation for this class was generated from the following file:
IDetailRootObjectCustomization.h