Unreal Engine 5.6 C++ API: IStretcherAndPitchShifter Class Reference
IStretcherAndPitchShifter Class Reference abstract
#include "StretcherAndPitchShifter.h"
Public Member Functions
IStretcherAndPitchShifter (FName InFactoryName)
virtual ~IStretcherAndPitchShifter ()
virtual void Cleanup ()=0
virtual int32 GetCurrentSampleFrame () const
FName GetFactoryName () const
virtual int32 GetInputFramesNeeded (int32 NumOutFramesNeeded, float PitchShift, float SpeedShift)=0
virtual int32 GetLatencySamples () const
virtual size_t GetMemoryUsage () const =0
virtual bool HandlesSpeedCorrection () const
virtual bool HasCurrentSampleFrame () const
virtual bool InputSilence (int32 NumFrames)=0
virtual void PitchShift (float Pitch, float Speed, TAudioBuffer< float > &OutBuffer)=0
virtual double Render (TAudioBuffer< float > &OutputData, double Pos, int32 MaxFrame, double ResampleInc, double PitchShift, double Speed, bool MaintainPitchWhenSpeedChanges, bool ShouldHonorLoopPoints, const FGainMatrix &Gain)=0
virtual void SetSampleRateAndReset (float InSampleRate)
void SetSampleSourceReset (TSharedPtr< FSoundWaveProxy > InSoundWave, TSharedPtr< IAudioDataRenderer, ESPMode::ThreadSafe > InAudioRenderer, const FTimeStretchConfig *ShifterSettings)
virtual void StereoPitchShift (float InPitchShift, int32 NumOutputFrame, float *OutLeftData, float *OutRightData)=0
virtual void StereoPitchShift (float InPitchShift, int32 NumSampsToProcess, float *InLeftData, float *InRightData, float *OutLeftData, float *OutRightData)=0
virtual bool TakeInput (TAudioBuffer< float > &InBuffer)=0
virtual void UpdateOptions (const TMap< FName, FTypedParameter > &Options)
Protected Member Functions
virtual void SetupAndResetImpl (const FTimeStretchConfig *ShifterSettings)
Protected Attributes
TSharedPtr< FSoundWaveProxy > MyAudioData
TSharedPtr< IAudioDataRenderer, ESPMode::ThreadSafe > MyAudioRenderer
Private Attributes
const FName MyFactoryName
Detailed Description
Definition at line 39 of file StretcherAndPitchShifter.h.
Constructor & Destructor Documentation
IStretcherAndPitchShifter()
IStretcherAndPitchShifter::IStretcherAndPitchShifter (FName InFactoryName) inline
Definition at line 42 of file StretcherAndPitchShifter.h.
References MyFactoryName.
~IStretcherAndPitchShifter()
virtual IStretcherAndPitchShifter::~IStretcherAndPitchShifter () inline virtual
Definition at line 43 of file StretcherAndPitchShifter.h.
Member Function Documentation
Cleanup()
virtual void IStretcherAndPitchShifter::Cleanup () pure virtual
GetCurrentSampleFrame()
virtual int32 IStretcherAndPitchShifter::GetCurrentSampleFrame () const inline virtual
Definition at line 54 of file StretcherAndPitchShifter.h.
GetFactoryName()
FName IStretcherAndPitchShifter::GetFactoryName () const inline
Definition at line 45 of file StretcherAndPitchShifter.h.
References MyFactoryName.
GetInputFramesNeeded()
virtual int32 IStretcherAndPitchShifter::GetInputFramesNeeded (int32 NumOutFramesNeeded, float PitchShift, float SpeedShift) pure virtual
References PitchShift().
GetLatencySamples()
virtual int32 IStretcherAndPitchShifter::GetLatencySamples () const inline virtual
Definition at line 52 of file StretcherAndPitchShifter.h.
GetMemoryUsage()
virtual size_t IStretcherAndPitchShifter::GetMemoryUsage () const pure virtual
HandlesSpeedCorrection()
virtual bool IStretcherAndPitchShifter::HandlesSpeedCorrection () const inline virtual
Definition at line 50 of file StretcherAndPitchShifter.h.
HasCurrentSampleFrame()
virtual bool IStretcherAndPitchShifter::HasCurrentSampleFrame () const inline virtual
Definition at line 53 of file StretcherAndPitchShifter.h.
InputSilence()
virtual bool IStretcherAndPitchShifter::InputSilence (int32 NumFrames) pure virtual
References NumFrames.
PitchShift()
virtual void IStretcherAndPitchShifter::PitchShift (float Pitch, float Speed, TAudioBuffer< float > & OutBuffer) pure virtual
References Speed.
Referenced by GetInputFramesNeeded(), and Render().
Render()
virtual double IStretcherAndPitchShifter::Render (TAudioBuffer< float > & OutputData, double Pos, int32 MaxFrame, double ResampleInc, double PitchShift, double Speed, bool MaintainPitchWhenSpeedChanges, bool ShouldHonorLoopPoints, const FGainMatrix & Gain) pure virtual
References PitchShift(), and Speed.
SetSampleRateAndReset()
virtual void IStretcherAndPitchShifter::SetSampleRateAndReset (float InSampleRate) inline virtual
Definition at line 51 of file StretcherAndPitchShifter.h.
SetSampleSourceReset()
void IStretcherAndPitchShifter::SetSampleSourceReset (TSharedPtr< FSoundWaveProxy > InSoundWave, TSharedPtr< IAudioDataRenderer, ESPMode::ThreadSafe > InAudioRenderer, const FTimeStretchConfig * ShifterSettings) inline
Definition at line 56 of file StretcherAndPitchShifter.h.
References MyAudioData, MyAudioRenderer, and SetupAndResetImpl().
SetupAndResetImpl()
virtual void IStretcherAndPitchShifter::SetupAndResetImpl (const FTimeStretchConfig * ShifterSettings) inline protected virtual
Definition at line 80 of file StretcherAndPitchShifter.h.
Referenced by SetSampleSourceReset().
StereoPitchShift() [1/2]
virtual void IStretcherAndPitchShifter::StereoPitchShift (float InPitchShift, int32 NumOutputFrame, float * OutLeftData, float * OutRightData) pure virtual
StereoPitchShift() [2/2]
virtual void IStretcherAndPitchShifter::StereoPitchShift (float InPitchShift, int32 NumSampsToProcess, float * InLeftData, float * InRightData, float * OutLeftData, float * OutRightData) pure virtual
TakeInput()
virtual bool IStretcherAndPitchShifter::TakeInput (TAudioBuffer< float > & InBuffer) pure virtual
UpdateOptions()
virtual void IStretcherAndPitchShifter::UpdateOptions (const TMap< FName, FTypedParameter > & Options) inline virtual
Definition at line 47 of file StretcherAndPitchShifter.h.
Field Documentation
MyAudioData
TSharedPtr<FSoundWaveProxy> IStretcherAndPitchShifter::MyAudioData protected
Definition at line 77 of file StretcherAndPitchShifter.h.
Referenced by SetSampleSourceReset().
MyAudioRenderer
TSharedPtr<IAudioDataRenderer, ESPMode::ThreadSafe> IStretcherAndPitchShifter::MyAudioRenderer protected
Definition at line 78 of file StretcherAndPitchShifter.h.
Referenced by SetSampleSourceReset().
MyFactoryName
const FName IStretcherAndPitchShifter::MyFactoryName private
Definition at line 84 of file StretcherAndPitchShifter.h.
Referenced by IStretcherAndPitchShifter(), and GetFactoryName().
The documentation for this class was generated from the following file:
StretcherAndPitchShifter.h