Unreal Engine 5.6 C++ API: UE::Transaction::FSerializedObjectInfo Struct Reference
UE::Transaction::FSerializedObjectInfo Struct Reference
#include "TransactionCommon.h"
Public Member Functions
FSerializedObjectInfo ()=default
FSerializedObjectInfo (const UObject *InObject)
void Reset ()
void SetObject (const UObject *InObject)
void Swap (FSerializedObjectInfo &Other)
Public Member Functions inherited from FTransactionObjectId
FTransactionObjectId ()=default
FTransactionObjectId (const FName InObjectPackageName, const FName InObjectName, const FName InObjectPathName, const FName InObjectOuterPathName, const FName InObjectExternalPackageName, const FName InObjectClassPathName)
FTransactionObjectId (const UObject *Object)
void Reset ()
void SetObject (const UObject *Object)
void Swap (FTransactionObjectId &Other)
Data Fields
bool bIsPendingKill = false
The pending kill state of the object when it was serialized.
Data Fields inherited from FTransactionObjectId
FName ObjectClassPathName
The path name of the object's class.
FName ObjectExternalPackageName
The external package name of the object, if any.
FName ObjectName
The name of the object.
FName ObjectOuterPathName
The outer path name of the object.
FName ObjectPackageName
The package name of the object, can be dictated either by outer chain or external package.
FName ObjectPathName
The path name of the object.
Detailed Description
Definition at line 191 of file TransactionCommon.h.
Constructor & Destructor Documentation
FSerializedObjectInfo() [1/2]
UE::Transaction::FSerializedObjectInfo::FSerializedObjectInfo () default
Referenced by Swap().
FSerializedObjectInfo() [2/2]
UE::Transaction::FSerializedObjectInfo::FSerializedObjectInfo (const UObject * InObject) inline explicit
Definition at line 196 of file TransactionCommon.h.
References SetObject().
Member Function Documentation
Reset()
void UE::Transaction::FSerializedObjectInfo::Reset () inline
Definition at line 207 of file TransactionCommon.h.
References bIsPendingKill, and FTransactionObjectId::Reset().
SetObject()
void UE::Transaction::FSerializedObjectInfo::SetObject (const UObject * InObject) inline
Definition at line 201 of file TransactionCommon.h.
References bIsPendingKill, IsValid(), and FTransactionObjectId::SetObject().
Referenced by FSerializedObjectInfo().
Swap()
void UE::Transaction::FSerializedObjectInfo::Swap (FSerializedObjectInfo & Other) inline
Definition at line 213 of file TransactionCommon.h.
References FSerializedObjectInfo(), bIsPendingKill, Exchange(), Other, and FTransactionObjectId::Swap().
Field Documentation
bIsPendingKill
bool UE::Transaction::FSerializedObjectInfo::bIsPendingKill = false
The pending kill state of the object when it was serialized.
Definition at line 220 of file TransactionCommon.h.
Referenced by Reset(), SetObject(), and Swap().
The documentation for this struct was generated from the following file:
TransactionCommon.h