Unreal Engine 5.6 C++ API: FComponentReregisterContextBase Class Reference
FComponentReregisterContextBase Class Reference
Base class for Component Reregister objects, provides helper functions for performing the UnRegister and ReRegister.
#include "ComponentReregisterContext.h"
Protected Member Functions
void ReRegister (UActorComponent *InComponent, UWorld *InWorld)
UWorld * UnRegister (UActorComponent *InComponent)
Protected Attributes
TSet< FSceneInterface * > * ScenesToUpdateAllPrimitiveSceneInfos = nullptr
Detailed Description
Base class for Component Reregister objects, provides helper functions for performing the UnRegister and ReRegister.
Definition at line 17 of file ComponentReregisterContext.h.
Member Function Documentation
ReRegister()
void FComponentReregisterContextBase::ReRegister (UActorComponent * InComponent, UWorld * InWorld) protected
Referenced by FComponentReregisterContext::~FComponentReregisterContext(), and FMultiComponentReregisterContext::~FMultiComponentReregisterContext().
UnRegister()
UWorld * FComponentReregisterContextBase::UnRegister (UActorComponent * InComponent) protected
Referenced by FComponentReregisterContext::FComponentReregisterContext(), and FMultiComponentReregisterContext::FMultiComponentReregisterContext().
Field Documentation
ScenesToUpdateAllPrimitiveSceneInfos
TSet<FSceneInterface*>* FComponentReregisterContextBase::ScenesToUpdateAllPrimitiveSceneInfos = nullptr protected
Definition at line 20 of file ComponentReregisterContext.h.
Referenced by FComponentReregisterContext::FComponentReregisterContext().
The documentation for this class was generated from the following file:
ComponentReregisterContext.h