Unreal Engine 5.6 C++ API: ContainerAllocationPolicies.h File Reference
ContainerAllocationPolicies.h File Reference
#include "CoreTypes.h"
#include "Containers/ContainerHelpers.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "HAL/PlatformMath.h"
#include "HAL/UnrealMemory.h"
#include "Math/NumericLimits.h"
#include "Misc/AssertionMacros.h"
#include "Templates/IsPolymorphic.h"
#include "Templates/MemoryOps.h"
#include "Templates/TypeCompatibleBytes.h"
#include <type_traits>
Data Structures
class FContainerAllocatorInterface
This is the allocation policy interface; it exists purely to document the policy's interface, and should not be used.
class FContainerAllocatorInterface::ForElementType< ElementType >
A class that receives both the explicit allocation policy template parameters specified by the user of the container, but also the implicit ElementType template parameter from the container type.
class FDefaultBitArrayAllocator
class FDefaultSetAllocator
class FDefaultSparseArrayAllocator
struct FScriptContainerElement
A type which is used to represent a script type that is unknown at compile time.
class TAlignedHeapAllocator< Alignment >
The indirect allocation policy always allocates the elements indirectly.
class TAlignedHeapAllocator< Alignment >::ForAnyElementType
class TAlignedHeapAllocator< Alignment >::ForElementType< ElementType >
class TAlignedSparseArrayAllocator< Alignment, InElementAllocator, InBitArrayAllocator >
struct TAllocatorTraits< AllocatorType >
struct TAllocatorTraits< FDefaultAllocator >
struct TAllocatorTraits< FDefaultBitArrayAllocator >
struct TAllocatorTraits< FDefaultSetAllocator >
struct TAllocatorTraits< FDefaultSparseArrayAllocator >
struct TAllocatorTraits< TAlignedHeapAllocator< Alignment > >
struct TAllocatorTraits< TNonRelocatableInlineAllocator< NumInlineElements > >
struct TAllocatorTraits< TSetAllocator< InSparseArrayAllocator, InHashAllocator, AverageNumberOfElementsPerHashBucket, BaseNumberOfHashBuckets, MinNumberOfHashedElements > >
struct TAllocatorTraits< TSizedDefaultAllocator< IndexSize > >
struct TAllocatorTraits< TSizedHeapAllocator< IndexSize > >
struct TAllocatorTraits< TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator > >
struct TAllocatorTraits< TSparseArrayAllocator< InElementAllocator, InBitArrayAllocator > >
struct TAllocatorTraitsBase< AllocatorType >
struct TBitsToSizeType< IndexSize >
struct TBitsToSizeType< 16 >
struct TBitsToSizeType< 32 >
struct TBitsToSizeType< 64 >
struct TBitsToSizeType< 8 >
struct TCanMoveBetweenAllocators< FromAllocatorType, ToAllocatorType >
struct TCanMoveBetweenAllocators< TSizedDefaultAllocator< FromIndexSize >, TSizedDefaultAllocator< ToIndexSize > >
struct TCanMoveBetweenAllocators< TSizedHeapAllocator< FromIndexSize >, TSizedHeapAllocator< ToIndexSize > >
class TFixedAllocator< NumInlineElements >
The fixed allocation policy allocates up to a specified number of elements in the same allocation as the container.
class TFixedAllocator< NumInlineElements >::ForElementType< ElementType >
class TFixedSetAllocator< NumInlineElements, AverageNumberOfElementsPerHashBucket, MinNumberOfHashedElements >
An inline set allocator that doesn't have any secondary storage.
class TFixedSparseArrayAllocator< NumInlineElements >
An inline sparse array allocator that doesn't have any secondary storage.
class TInlineSetAllocator< NumInlineElements, SecondaryAllocator, AverageNumberOfElementsPerHashBucket, MinNumberOfHashedElements >
An inline set allocator that allows sizing of the inline allocations for a set number of elements.
class TInlineSparseArrayAllocator< NumInlineElements, SecondaryAllocator >
An inline sparse array allocator that allows sizing of the inline allocations for a set number of elements.
class TNonRelocatableInlineAllocator< NumInlineElements >
Implements a variant of TInlineAllocator with a secondary heap allocator that is allowed to store a pointer to its inline elements.
class TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >
class TSetAllocator< InSparseArrayAllocator, InHashAllocator, AverageNumberOfElementsPerHashBucket, BaseNumberOfHashBuckets, MinNumberOfHashedElements >
Encapsulates the allocators used by a set in a single type.
class TSizedDefaultAllocator< IndexSize >
'typedefs' for various allocator defaults.
class TSizedHeapAllocator< IndexSize, BaseMallocType >
The indirect allocation policy always allocates the elements indirectly.
class TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType
class TSizedHeapAllocator< IndexSize, BaseMallocType >::ForElementType< ElementType >
class TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >
The inline allocation policy allocates up to a specified number of elements in the same allocation as the container.
class TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >
class TSparseArrayAllocator< InElementAllocator, InBitArrayAllocator >
Encapsulates the allocators used by a sparse array in a single type.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define CONTAINER_INITIAL_ALLOC_ZERO_SLACK 1
#define DEFAULT_BASE_NUMBER_OF_HASH_BUCKETS 8
#define DEFAULT_MIN_NUMBER_OF_HASHED_ELEMENTS 4
#define DEFAULT_NUMBER_OF_ELEMENTS_PER_HASH_BUCKET 2
#define NumBitsPerDWORD ((int32)32)
#define NumBitsPerDWORDLogTwo ((int32)5)
#define UE_CONTAINER_SLACK_GROWTH_FACTOR_DENOMINATOR 8
#define UE_CONTAINER_SLACK_GROWTH_FACTOR_NUMERATOR 3
#define UE_ENABLE_ARRAY_SLACK_TRACKING (0 && !WITH_EDITOR)
Typedefs
using FDefaultAllocator = TSizedDefaultAllocator<32>
using FHeapAllocator = TSizedHeapAllocator<32>
template<uint32 NumInlineElements, typename SecondaryAllocator = FDefaultAllocator>
using TInlineAllocator = TSizedInlineAllocator<NumInlineElements, 32, SecondaryAllocator>
template<uint32 NumInlineElements, typename SecondaryAllocator = FDefaultAllocator64>
using TInlineAllocator64 = TSizedInlineAllocator<NumInlineElements, 64, SecondaryAllocator>
Functions
template<typename SizeType>
FORCEINLINE SizeType DefaultCalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment=DEFAULT_ALIGNMENT)
template<typename SizeType>
FORCEINLINE SizeType DefaultCalculateSlackReserve (SizeType NewMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment=DEFAULT_ALIGNMENT)
template<typename SizeType>
FORCEINLINE SizeType DefaultCalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment=DEFAULT_ALIGNMENT)
void UE::Core::Private::OnInvalidAlignedHeapAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
void UE::Core::Private::OnInvalidSizedHeapAllocatorNum (int32 IndexSize, int64 NewNum, SIZE_T NumBytesPerElement)
Macro Definition Documentation
CONTAINER_INITIAL_ALLOC_ZERO_SLACK
#define CONTAINER_INITIAL_ALLOC_ZERO_SLACK 1
Definition at line 109 of file ContainerAllocationPolicies.h.
DEFAULT_BASE_NUMBER_OF_HASH_BUCKETS
#define DEFAULT_BASE_NUMBER_OF_HASH_BUCKETS 8
Definition at line 1381 of file ContainerAllocationPolicies.h.
DEFAULT_MIN_NUMBER_OF_HASHED_ELEMENTS
#define DEFAULT_MIN_NUMBER_OF_HASHED_ELEMENTS 4
Definition at line 1382 of file ContainerAllocationPolicies.h.
DEFAULT_NUMBER_OF_ELEMENTS_PER_HASH_BUCKET
#define DEFAULT_NUMBER_OF_ELEMENTS_PER_HASH_BUCKET 2
Definition at line 1379 of file ContainerAllocationPolicies.h.
NumBitsPerDWORD
#define NumBitsPerDWORD ((int32)32)
Definition at line 1314 of file ContainerAllocationPolicies.h.
Referenced by FRelativeBitReference::FRelativeBitReference(), TBitArray< typename Allocator::BitArrayAllocator >::TBitArray(), TBitArray< typename Allocator::BitArrayAllocator >::TBitArray(), TConstDualSetBitIterator< Allocator, OtherAllocator, true >::TConstDualSetBitIterator(), TConstSetBitIterator< typename Allocator::BitArrayAllocator >::TConstSetBitIterator(), TBitArray< Allocator >::TWordIteratorBase< WordType >::TWordIteratorBase(), TBitArray< typename Allocator::BitArrayAllocator >::AccessCorrespondingBit(), TBitArray< typename Allocator::BitArrayAllocator >::AccessCorrespondingBit(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Add(), TBitArray< typename Allocator::BitArrayAllocator >::AddUninitialized(), TBitArray< typename Allocator::BitArrayAllocator >::CheckInvariants(), TBitArray< typename Allocator::BitArrayAllocator >::ClearPartialSlackBits(), TBitArray< typename Allocator::BitArrayAllocator >::Empty(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Empty(), TConstDualSetBitIterator< Allocator, OtherAllocator, true >::FindFirstSetBit(), TConstSetBitIterator< typename Allocator::BitArrayAllocator >::FindFirstSetBit(), TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::FindLastFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::Init(), TBitArray< Allocator >::FConstReverseIterator::operator++(), TBitArray< Allocator >::FReverseIterator::operator++(), TBitArray< typename Allocator::BitArrayAllocator >::operator[](), TBitArray< typename Allocator::BitArrayAllocator >::operator[](), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[](), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::operator[](), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Realloc(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::ReallocGrow(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAtSwap(), TBitArray< typename Allocator::BitArrayAllocator >::Reserve(), TBitArray< typename Allocator::BitArrayAllocator >::Serialize(), FStructTypeBitSet::FBitSetContainer::SetBitNoCheck(), TBitArray< typename Allocator::BitArrayAllocator >::SetBitNoCheck(), TBitArray< typename Allocator::BitArrayAllocator >::SetNumUninitialized(), TBitArray< typename Allocator::BitArrayAllocator >::SetRange(), USTRUCT(), and TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >::WriteMemoryImage().
NumBitsPerDWORDLogTwo
#define NumBitsPerDWORDLogTwo ((int32)5)
Definition at line 1315 of file ContainerAllocationPolicies.h.
Referenced by FRelativeBitReference::FRelativeBitReference(), TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl(), and TBitArray< typename Allocator::BitArrayAllocator >::FindLastFromImpl().
UE_CONTAINER_SLACK_GROWTH_FACTOR_DENOMINATOR
#define UE_CONTAINER_SLACK_GROWTH_FACTOR_DENOMINATOR 8
Definition at line 132 of file ContainerAllocationPolicies.h.
Referenced by DefaultCalculateSlackGrow().
UE_CONTAINER_SLACK_GROWTH_FACTOR_NUMERATOR
#define UE_CONTAINER_SLACK_GROWTH_FACTOR_NUMERATOR 3
Definition at line 124 of file ContainerAllocationPolicies.h.
Referenced by DefaultCalculateSlackGrow().
UE_ENABLE_ARRAY_SLACK_TRACKING
#define UE_ENABLE_ARRAY_SLACK_TRACKING (0 && !WITH_EDITOR)
Definition at line 24 of file ContainerAllocationPolicies.h.
Typedef Documentation
FDefaultAllocator
using FDefaultAllocator = TSizedDefaultAllocator<32>
Definition at line 142 of file ContainerAllocationPolicies.h.
FHeapAllocator
using FHeapAllocator = TSizedHeapAllocator<32>
Definition at line 842 of file ContainerAllocationPolicies.h.
TInlineAllocator
template<uint32 NumInlineElements, typename SecondaryAllocator = FDefaultAllocator> using TInlineAllocator = TSizedInlineAllocator<NumInlineElements, 32, SecondaryAllocator>
Definition at line 1020 of file ContainerAllocationPolicies.h.
TInlineAllocator64
template<uint32 NumInlineElements, typename SecondaryAllocator = FDefaultAllocator64> using TInlineAllocator64 = TSizedInlineAllocator<NumInlineElements, 64, SecondaryAllocator>
Definition at line 1023 of file ContainerAllocationPolicies.h.
Function Documentation
DefaultCalculateSlackGrow()
template<typename SizeType> FORCEINLINE SizeType DefaultCalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment = DEFAULT_ALIGNMENT)
Definition at line 175 of file ContainerAllocationPolicies.h.
References checkSlow, DEFAULT_ALIGNMENT, FORCEINLINE, FMemory::QuantizeSize(), UE_CONTAINER_SLACK_GROWTH_FACTOR_DENOMINATOR, and UE_CONTAINER_SLACK_GROWTH_FACTOR_NUMERATOR.
Referenced by TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow(), TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::CalculateSlackGrow(), TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackGrow(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackGrow(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackGrow(), TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackGrow(), and TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackGrow().
DefaultCalculateSlackReserve()
template<typename SizeType> FORCEINLINE SizeType DefaultCalculateSlackReserve (SizeType NewMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment = DEFAULT_ALIGNMENT)
Definition at line 229 of file ContainerAllocationPolicies.h.
References checkSlow, DEFAULT_ALIGNMENT, FORCEINLINE, and FMemory::QuantizeSize().
Referenced by TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve(), TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::CalculateSlackReserve(), TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackReserve(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackReserve(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackReserve(), TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackReserve(), and TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackReserve().
DefaultCalculateSlackShrink()
template<typename SizeType> FORCEINLINE SizeType DefaultCalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T BytesPerElement, bool bAllowQuantize, uint32 Alignment = DEFAULT_ALIGNMENT)
Definition at line 145 of file ContainerAllocationPolicies.h.
References checkSlow, DEFAULT_ALIGNMENT, FORCEINLINE, and FMemory::QuantizeSize().
Referenced by TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink(), TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::CalculateSlackShrink(), TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink(), TMemoryImageAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackShrink(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackShrink(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::CalculateSlackShrink(), TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackShrink(), and TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackShrink().