Unreal Engine 5.6 C++ API: IFileHandle Class Reference
IFileHandle Class Reference abstract
File handle interface.
#include "GenericPlatformFile.h"
Public Member Functions
virtual ~IFileHandle ()
Destructor, also the only way to close the file handle.
virtual bool Flush (const bool bFullFlush=false)=0
Flushes file handle to disk.
virtual bool Read (uint8 *Destination, int64 BytesToRead)=0
Read bytes from the file.
virtual bool ReadAt (uint8 *Destination, int64 BytesToRead, int64 Offset)=0
virtual bool Seek (int64 NewPosition)=0
Change the current write or read position.
virtual bool SeekFromEnd (int64 NewPositionRelativeToEnd=0)=0
Change the current write or read position, relative to the end of the file.
virtual void ShrinkBuffers ()
Minimizes optional system or process cache kept for the file.
virtual int64 Size ()
Return the total size of the file.
virtual int64 Tell ()=0
Return the current write or read position.
virtual bool Truncate (int64 NewSize)=0
Truncate the file to the given size (in bytes).
virtual bool Write (const uint8 *Source, int64 BytesToWrite)=0
Write bytes to the file.
Detailed Description
File handle interface.
Definition at line 116 of file GenericPlatformFile.h.
Constructor & Destructor Documentation
~IFileHandle()
virtual IFileHandle::~IFileHandle () inline virtual
Destructor, also the only way to close the file handle.
Definition at line 120 of file GenericPlatformFile.h.
Member Function Documentation
Flush()
virtual bool IFileHandle::Flush (const bool bFullFlush = false) pure virtual
Flushes file handle to disk.
Parameters
bFullFlush true to flush everything about the file (including its meta-data) with a strong guarantee that it will be on disk by the time this function returns, or false to let the operating/file system have more leeway about when the data actually gets written to disk
Returns
true if operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Read()
virtual bool IFileHandle::Read (uint8 * Destination, int64 BytesToRead) pure virtual
Read bytes from the file.
Parameters
Destination Buffer to holds the results, should be at least BytesToRead in size.
BytesToRead Number of bytes to read into the destination.
Returns
true if the operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Referenced by UE::FGenericPlatformIoDispatcher::ProcessFileIo().
ReadAt()
virtual bool IFileHandle::ReadAt (uint8 * Destination, int64 BytesToRead, int64 Offset) pure virtual
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Seek()
virtual bool IFileHandle::Seek (int64 NewPosition) pure virtual
Change the current write or read position.
Parameters
NewPosition new write or read position
Returns
true if the operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Referenced by UE::FGenericPlatformIoDispatcher::ProcessFileIo().
SeekFromEnd()
virtual bool IFileHandle::SeekFromEnd (int64 NewPositionRelativeToEnd = 0) pure virtual
Change the current write or read position, relative to the end of the file.
Parameters
NewPositionRelativeToEnd new write or read position, relative to the end of the file should be <=0!
Returns
true if the operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
ShrinkBuffers()
virtual void IFileHandle::ShrinkBuffers () inline virtual
Minimizes optional system or process cache kept for the file.
Reimplemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Definition at line 176 of file GenericPlatformFile.h.
Size()
virtual int64 IFileHandle::Size () virtual
Return the total size of the file.
Reimplemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Referenced by TManagedStoragePlatformFile< BaseClass >::OpenWrite().
Tell()
virtual int64 IFileHandle::Tell () pure virtual
Return the current write or read position.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Truncate()
virtual bool IFileHandle::Truncate (int64 NewSize) pure virtual
Truncate the file to the given size (in bytes).
Parameters
NewSize Truncated file size (in bytes).
Returns
true if the operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
Write()
virtual bool IFileHandle::Write (const uint8 * Source, int64 BytesToWrite) pure virtual
Write bytes to the file.
Parameters
Source Buffer to write, should be at least BytesToWrite in size.
BytesToWrite Number of bytes to write.
Returns
true if the operation completed successfully.
Implemented in FCachedFileHandle, FLoggedFileHandle, and FManagedStorageFileWriteHandle.
References Source.
The documentation for this class was generated from the following file:
GenericPlatformFile.h