Unreal Engine 5.6 C++ API: IAnimClassInterface Class Reference
IAnimClassInterface Class Reference abstract
#include "AnimClassInterface.h"
Public Member Functions
const IAnimClassInterface * GetRootClass () const
UE_DEPRECATED (4.23, "Please use GetAnimBlueprintFunctions()") virtual FStructProperty *GetRootAnimNodeProperty() const
UE_DEPRECATED (4.23, "Please use GetAnimBlueprintFunctions()") virtual int32 GetRootAnimNodeIndex() const
Static Public Member Functions
static const FAnimBlueprintFunction * FindAnimBlueprintFunction (IAnimClassInterface *AnimClassInterface, const FName &InFunctionName)
static const UClass * GetActualAnimClass (const IAnimClassInterface *AnimClassInterface)
static UClass * GetActualAnimClass (IAnimClassInterface *AnimClassInterface)
static const FAnimNode_Base * GetAnimNodeFromObjectPtr (const UObject *InObject, int32 InNodeIndex, UScriptStruct *InNodeType)
template<typename NodeType>
static const NodeType & GetAnimNodeFromObjectPtrChecked (const UObject *InObject, int32 InNodeIndex)
static const IAnimClassInterface * GetFromClass (const UClass *InClass)
static IAnimClassInterface * GetFromClass (UClass *InClass)
static const UObject * GetObjectPtrFromAnimNode (const IAnimClassInterface *InAnimClassInterface, const FAnimNode_Base *InNode)
static bool IsAnimBlueprintFunction (IAnimClassInterface *InAnimClassInterface, const UFunction *InFunction)
Check if a function is an anim function on this class.
Protected Member Functions
virtual int32 GetAnimNodePropertyCount (const UScriptStruct *InNodeType) const =0
virtual int32 GetAnimNodePropertyIndex (const UScriptStruct *InNodeType, FName InPropertyName) const =0
virtual const TArray< FAnimNotifyEvent > & GetAnimNotifies_Direct () const =0
virtual const TArray< FBakedAnimationStateMachine > & GetBakedStateMachines_Direct () const =0
virtual const void * GetConstantNodeData () const =0
virtual const void * GetConstantNodeValueRaw (int32 InIndex) const =0
virtual const TMap< FName, FGraphAssetPlayerInformation > & GetGraphAssetPlayerInformation_Direct () const =0
virtual const TMap< FName, FAnimGraphBlendOptions > & GetGraphBlendOptions_Direct () const =0
virtual const FAnimBlueprintMutableData * GetMutableNodeData (const UObject *InObject) const =0
virtual FAnimBlueprintMutableData * GetMutableNodeData (UObject *InObject) const =0
virtual const void * GetMutableNodeValueRaw (int32 InIndex, const UObject *InObject) const =0
virtual TArrayView< const FAnimNodeData > GetNodeData () const =0
virtual const TMap< FName, FCachedPoseIndices > & GetOrderedSavedPoseNodeIndicesMap_Direct () const =0
virtual const TArray< FName > & GetSyncGroupNames_Direct () const =0
UE_DEPRECATED (5.0, "Please use GetSubsystem<FAnimSubsystem_PropertyAccess>") 1 virtual const FPropertyAccessLibrary &GetPropertyAccessLibrary_Direct() const
Private Member Functions
template<typename SubsystemType>
const SubsystemType * FindSubsystem () const
virtual const FAnimSubsystem * FindSubsystem (UScriptStruct *InSubsystemType) const =0
virtual void ForEachSubsystem (TFunctionRef< EAnimSubsystemEnumeration(const FAnimSubsystemContext &)> InFunction) const =0
virtual void ForEachSubsystem (UObject *InObject, TFunctionRef< EAnimSubsystemEnumeration(const FAnimSubsystemInstanceContext &)> InFunction) const =0
virtual const TArray< FAnimBlueprintFunction > & GetAnimBlueprintFunctions () const =0
virtual const TArray< FStructProperty * > & GetAnimNodeProperties () const =0
virtual GENERATED_BODY() public const TArray< FAnimNotifyEvent > & GetAnimNotifies () const =0
virtual const TArray< FStructProperty * > & GetDynamicResetNodeProperties () const =0
virtual const TMap< FName, FGraphAssetPlayerInformation > & GetGraphAssetPlayerInformation () const =0
virtual const TMap< FName, FAnimGraphBlendOptions > & GetGraphBlendOptions () const =0
virtual const TArray< FStructProperty * > & GetInitializationNodeProperties () const =0
virtual const TArray< FStructProperty * > & GetLinkedAnimGraphNodeProperties () const =0
virtual const TArray< FStructProperty * > & GetLinkedAnimLayerNodeProperties () const =0
virtual const TMap< FName, FCachedPoseIndices > & GetOrderedSavedPoseNodeIndicesMap () const =0
virtual const TArray< FStructProperty * > & GetPreUpdateNodeProperties () const =0
virtual const TArray< FStructProperty * > & GetStateMachineNodeProperties () const =0
template<typename SubsystemType>
const SubsystemType & GetSubsystem () const
virtual int32 GetSyncGroupIndex (FName SyncGroupName) const =0
virtual const TArray< FName > & GetSyncGroupNames () const =0
virtual USkeleton * GetTargetSkeleton () const =0
UE_DEPRECATED (4.24, "Function has been renamed, please use GetLinkedAnimGraphNodeProperties") virtual const TArray< FStructProperty * > &GetSubInstanceNodeProperties() const
UE_DEPRECATED (4.24, "Function has been renamed, please use GetLinkedLayerNodeProperties") virtual const TArray< FStructProperty * > &GetLayerNodeProperties() const
UE_DEPRECATED (5.0, "Please use GetSubsystem<FAnimSubsystem_Base>") 1 virtual const TArray< FExposedValueHandler > &GetExposedValueHandlers() const
UE_DEPRECATED (5.0, "Please use GetSubsystem<FAnimSubsystem_PropertyAccess>") 1 virtual const FPropertyAccessLibrary &GetPropertyAccessLibrary() const
Static Private Member Functions
static bool HasNodeAnyFlags (IAnimClassInterface *InAnimClassInterface, int32 InNodeIndex, EAnimNodeDataFlags InNodeDataFlags)
Friends
struct FAnimNodeData
class UAnimBlueprintGeneratedClass
struct UE::Anim::FNodeDataId
Detailed Description
Definition at line 192 of file AnimClassInterface.h.
Member Function Documentation
FindAnimBlueprintFunction()
const FAnimBlueprintFunction * IAnimClassInterface::FindAnimBlueprintFunction (IAnimClassInterface * AnimClassInterface, const FName & InFunctionName) static
FindSubsystem() [1/2]
template<typename SubsystemType> const SubsystemType * IAnimClassInterface::FindSubsystem () const inline private
Definition at line 231 of file AnimClassInterface.h.
References FindSubsystem(), and FindSubsystem().
Referenced by FindSubsystem(), and GetSubsystem().
FindSubsystem() [2/2]
virtual const FAnimSubsystem * IAnimClassInterface::FindSubsystem (UScriptStruct * InSubsystemType) const private pure virtual
References FindSubsystem().
Referenced by FindSubsystem(), and FindSubsystem().
ForEachSubsystem() [1/2]
virtual void IAnimClassInterface::ForEachSubsystem (TFunctionRef< EAnimSubsystemEnumeration(const FAnimSubsystemContext &)> InFunction) const private pure virtual
References ForEachSubsystem().
Referenced by ForEachSubsystem(), and ForEachSubsystem().
ForEachSubsystem() [2/2]
virtual void IAnimClassInterface::ForEachSubsystem (UObject * InObject, TFunctionRef< EAnimSubsystemEnumeration(const FAnimSubsystemInstanceContext &)> InFunction) const private pure virtual
References ForEachSubsystem().
GetActualAnimClass() [1/2]
const UClass * IAnimClassInterface::GetActualAnimClass (const IAnimClassInterface * AnimClassInterface) static
GetActualAnimClass() [2/2]
UClass * IAnimClassInterface::GetActualAnimClass (IAnimClassInterface * AnimClassInterface) static
Referenced by USTRUCT().
GetAnimBlueprintFunctions()
virtual const TArray< FAnimBlueprintFunction > & IAnimClassInterface::GetAnimBlueprintFunctions () const private pure virtual
References GetAnimBlueprintFunctions().
Referenced by GetAnimBlueprintFunctions().
GetAnimNodeFromObjectPtr()
const FAnimNode_Base * IAnimClassInterface::GetAnimNodeFromObjectPtr (const UObject * InObject, int32 InNodeIndex, UScriptStruct * InNodeType) static
Referenced by GetAnimNodeFromObjectPtrChecked().
GetAnimNodeFromObjectPtrChecked()
template<typename NodeType> const NodeType & IAnimClassInterface::GetAnimNodeFromObjectPtrChecked (const UObject * InObject, int32 InNodeIndex) inline static
Definition at line 327 of file AnimClassInterface.h.
References check, and GetAnimNodeFromObjectPtr().
GetAnimNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetAnimNodeProperties () const private pure virtual
Referenced by GetNodeFromPropertyIndex().
GetAnimNodePropertyCount()
virtual int32 IAnimClassInterface::GetAnimNodePropertyCount (const UScriptStruct * InNodeType) const protected pure virtual
References GetAnimNodePropertyCount().
Referenced by GetAnimNodePropertyCount().
GetAnimNodePropertyIndex()
virtual int32 IAnimClassInterface::GetAnimNodePropertyIndex (const UScriptStruct * InNodeType, FName InPropertyName) const protected pure virtual
References GetAnimNodePropertyIndex().
Referenced by GetAnimNodePropertyIndex().
GetAnimNotifies()
virtual GENERATED_BODY() public const TArray< FAnimNotifyEvent > & IAnimClassInterface::GetAnimNotifies () const private pure virtual
GetAnimNotifies_Direct()
virtual const TArray< FAnimNotifyEvent > & IAnimClassInterface::GetAnimNotifies_Direct () const protected pure virtual
GetBakedStateMachines_Direct()
virtual const TArray< FBakedAnimationStateMachine > & IAnimClassInterface::GetBakedStateMachines_Direct () const protected pure virtual
GetConstantNodeData()
virtual const void * IAnimClassInterface::GetConstantNodeData () const protected pure virtual
References GetConstantNodeData().
Referenced by GetConstantNodeData().
GetConstantNodeValueRaw()
virtual const void * IAnimClassInterface::GetConstantNodeValueRaw (int32 InIndex) const protected pure virtual
References GetConstantNodeValueRaw().
Referenced by GetConstantNodeValueRaw().
GetDynamicResetNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetDynamicResetNodeProperties () const private pure virtual
GetFromClass() [1/2]
const IAnimClassInterface * IAnimClassInterface::GetFromClass (const UClass * InClass) static
GetFromClass() [2/2]
IAnimClassInterface * IAnimClassInterface::GetFromClass (UClass * InClass) static
GetGraphAssetPlayerInformation()
virtual const TMap< FName, FGraphAssetPlayerInformation > & IAnimClassInterface::GetGraphAssetPlayerInformation () const private pure virtual
References GetGraphAssetPlayerInformation().
Referenced by GetGraphAssetPlayerInformation().
GetGraphAssetPlayerInformation_Direct()
virtual const TMap< FName, FGraphAssetPlayerInformation > & IAnimClassInterface::GetGraphAssetPlayerInformation_Direct () const protected pure virtual
GetGraphBlendOptions()
virtual const TMap< FName, FAnimGraphBlendOptions > & IAnimClassInterface::GetGraphBlendOptions () const private pure virtual
References GetGraphBlendOptions().
Referenced by GetGraphBlendOptions().
GetGraphBlendOptions_Direct()
virtual const TMap< FName, FAnimGraphBlendOptions > & IAnimClassInterface::GetGraphBlendOptions_Direct () const protected pure virtual
GetInitializationNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetInitializationNodeProperties () const private pure virtual
GetLinkedAnimGraphNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetLinkedAnimGraphNodeProperties () const private pure virtual
Referenced by UE_DEPRECATED().
GetLinkedAnimLayerNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetLinkedAnimLayerNodeProperties () const private pure virtual
Referenced by UE_DEPRECATED().
GetMutableNodeData() [1/2]
virtual const FAnimBlueprintMutableData * IAnimClassInterface::GetMutableNodeData (const UObject * InObject) const protected pure virtual
References GetMutableNodeData().
Referenced by GetMutableNodeData(), and GetMutableNodeData().
GetMutableNodeData() [2/2]
virtual FAnimBlueprintMutableData * IAnimClassInterface::GetMutableNodeData (UObject * InObject) const protected pure virtual
References GetMutableNodeData().
GetMutableNodeValueRaw()
virtual const void * IAnimClassInterface::GetMutableNodeValueRaw (int32 InIndex, const UObject * InObject) const protected pure virtual
References GetMutableNodeValueRaw().
Referenced by GetMutableNodeValueRaw().
GetNodeData()
virtual TArrayView< const FAnimNodeData > IAnimClassInterface::GetNodeData () const protected pure virtual
References FAnimNodeData, and GetNodeData().
Referenced by GetNodeData().
GetObjectPtrFromAnimNode()
const UObject * IAnimClassInterface::GetObjectPtrFromAnimNode (const IAnimClassInterface * InAnimClassInterface, const FAnimNode_Base * InNode) static
GetOrderedSavedPoseNodeIndicesMap()
virtual const TMap< FName, FCachedPoseIndices > & IAnimClassInterface::GetOrderedSavedPoseNodeIndicesMap () const private pure virtual
References GetOrderedSavedPoseNodeIndicesMap().
Referenced by GetOrderedSavedPoseNodeIndicesMap().
GetOrderedSavedPoseNodeIndicesMap_Direct()
virtual const TMap< FName, FCachedPoseIndices > & IAnimClassInterface::GetOrderedSavedPoseNodeIndicesMap_Direct () const protected pure virtual
GetPreUpdateNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetPreUpdateNodeProperties () const private pure virtual
GetRootClass()
const IAnimClassInterface * IAnimClassInterface::GetRootClass () const
GetStateMachineNodeProperties()
virtual const TArray< FStructProperty * > & IAnimClassInterface::GetStateMachineNodeProperties () const private pure virtual
GetSubsystem()
template<typename SubsystemType> const SubsystemType & IAnimClassInterface::GetSubsystem () const inline private
Definition at line 239 of file AnimClassInterface.h.
References check, and FindSubsystem().
GetSyncGroupIndex()
virtual int32 IAnimClassInterface::GetSyncGroupIndex (FName SyncGroupName) const private pure virtual
References GetSyncGroupIndex().
Referenced by GetSyncGroupIndex().
GetSyncGroupNames()
virtual const TArray< FName > & IAnimClassInterface::GetSyncGroupNames () const private pure virtual
References GetSyncGroupNames().
Referenced by GetSyncGroupNames().
GetSyncGroupNames_Direct()
virtual const TArray< FName > & IAnimClassInterface::GetSyncGroupNames_Direct () const protected pure virtual
GetTargetSkeleton()
virtual USkeleton * IAnimClassInterface::GetTargetSkeleton () const private pure virtual
References GetTargetSkeleton().
Referenced by GetTargetSkeleton().
HasNodeAnyFlags()
bool IAnimClassInterface::HasNodeAnyFlags (IAnimClassInterface * InAnimClassInterface, int32 InNodeIndex, EAnimNodeDataFlags InNodeDataFlags) static private
IsAnimBlueprintFunction()
bool IAnimClassInterface::IsAnimBlueprintFunction (IAnimClassInterface * InAnimClassInterface, const UFunction * InFunction) static
Check if a function is an anim function on this class.
Parameters
InAnimClassInterface The interface to check
InFunction The function to check
Returns
true if the supplied function is an anim function on the specified class
UE_DEPRECATED() [1/7]
IAnimClassInterface::UE_DEPRECATED (4. 23, "Please use GetAnimBlueprintFunctions()") const inline
Definition at line 337 of file AnimClassInterface.h.
UE_DEPRECATED() [2/7]
IAnimClassInterface::UE_DEPRECATED (4. 23, "Please use GetAnimBlueprintFunctions()") const inline
Definition at line 334 of file AnimClassInterface.h.
References INDEX_NONE.
UE_DEPRECATED() [3/7]
IAnimClassInterface::UE_DEPRECATED (4. 24, "Function has been renamed, please use GetLinkedAnimGraphNodeProperties") const & inline private
Definition at line 199 of file AnimClassInterface.h.
References GetLinkedAnimGraphNodeProperties().
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [4/7]
IAnimClassInterface::UE_DEPRECATED (4. 24, "Function has been renamed, please use GetLinkedLayerNodeProperties") const & inline private
Definition at line 202 of file AnimClassInterface.h.
References GetLinkedAnimLayerNodeProperties().
UE_DEPRECATED() [5/7]
IAnimClassInterface::UE_DEPRECATED (5. 0, "Please use GetSubsystem<FAnimSubsystem_Base>") const & private
UE_DEPRECATED() [6/7]
IAnimClassInterface::UE_DEPRECATED (5. 0, "Please use GetSubsystem<FAnimSubsystem_PropertyAccess>") const & private
References UE_DEPRECATED().
UE_DEPRECATED() [7/7]
IAnimClassInterface::UE_DEPRECATED (5. 0, "Please use GetSubsystem<FAnimSubsystem_PropertyAccess>") const & protected
Friends And Related Symbol Documentation
FAnimNodeData
friend struct FAnimNodeData friend
Definition at line 262 of file AnimClassInterface.h.
References FAnimNodeData.
Referenced by FAnimNodeData, and GetNodeData().
UAnimBlueprintGeneratedClass
friend class UAnimBlueprintGeneratedClass friend
Definition at line 261 of file AnimClassInterface.h.
References UAnimBlueprintGeneratedClass.
Referenced by UAnimBlueprintGeneratedClass.
UE::Anim::FNodeDataId
friend struct UE::Anim::FNodeDataId friend
Definition at line 263 of file AnimClassInterface.h.
References UE::Anim::FNodeDataId.
Referenced by UE::Anim::FNodeDataId.
The documentation for this class was generated from the following file:
AnimClassInterface.h