Unreal Engine 5.6 C++ API: FInternationalization Class Reference
FInternationalization Class Reference
#include "Internationalization.h"
Data Structures
struct FCultureStateSnapshot
Struct that can be used to capture a snapshot of the active culture state in a way that can be re-applied losslessly.
Public Member Functions
void AddCustomCulture (const TSharedRef< ICustomCulture > &InCustomCulture)
Add a new custom culture.
void BackupCultureState (FCultureStateSnapshot &OutSnapshot) const
Backup the current culture state to the given snapshot struct.
void ClearCurrentAssetGroupCulture (const FName &InAssetGroupName)
Clear the given asset group category culture.
DECLARE_EVENT (FInternationalization, FCultureChangedEvent) FCultureChangedEvent &OnCultureChanged()
Broadcasts whenever the current culture changes.
TArray< FCultureRef > GetAvailableCultures (const TArray< FString > &InCultureNames, const bool bIncludeDerivedCultures)
Given some culture names, populate a list of cultures that are available to be used.
FCulturePtr GetCulture (const FString &InCultureName)
Get the culture corresponding to the given name.
void GetCultureNames (TArray< FString > &CultureNames) const
FCultureRef GetCurrentAssetGroupCulture (const FName &InAssetGroupName) const
Get the given asset group category culture.
FCultureRef GetCurrentCulture () const
Get the current culture.
TArray< FCultureRef > GetCurrentCultures (const bool bIncludeLanguage, const bool bIncludeLocale, const bool bIncludeAssetGroups) const
Get the current cultures in use, optionally including the current language, locale, and any asset groups.
FCultureRef GetCurrentLanguage () const
Get the current language (for localization).
FCultureRef GetCurrentLocale () const
Get the current locale (for internationalization).
FCulturePtr GetCustomCulture (const FString &InCultureName) const
Get a new custom culture from its name.
FCultureRef GetDefaultCulture () const
Get the default culture specified by the OS.
FCultureRef GetDefaultLanguage () const
Get the default language specified by the OS.
FCultureRef GetDefaultLocale () const
Get the default locale specified by the OS.
FCultureRef GetInvariantCulture () const
Get the invariant culture that can be used when you don't care about localization/internationalization.
TArray< FString > GetPrioritizedCultureNames (const FString &Name)
bool IsCultureAllowed (const FString &Name)
Is the given culture enabled or disabled in this build?
bool IsCultureRemapped (const FString &Name, FString *OutMappedCulture)
Has the given culture been remapped in this build?
bool IsInitialized () const
void LoadAllCultureData ()
Load and cache the data needed for every culture we know about (this is usually done per-culture as required)
void RefreshCachedConfigData ()
Refresh any config data that has been cached.
void RefreshCultureDisplayNames (const TArray< FString > &InPrioritizedDisplayCultureNames)
Refresh the display names of the cached cultures.
void RestoreCultureState (const FCultureStateSnapshot &InSnapshot)
Restore a previous culture state from the given snapshot struct.
bool SetCurrentAssetGroupCulture (const FName &InAssetGroupName, const FString &InCultureName)
Set the given asset group category culture by name.
bool SetCurrentCulture (const FString &InCultureName)
Set the current culture by name.
bool SetCurrentLanguage (const FString &InCultureName)
Set only the current language (for localization) by name.
bool SetCurrentLanguageAndLocale (const FString &InCultureName)
Set the current language (for localization) and locale (for internationalization) by name.
bool SetCurrentLocale (const FString &InCultureName)
Set only the current locale (for internationalization) by name.
UE_DEPRECATED (4.20, "FInternationalization::GetCulturesWithAvailableLocalization is deprecated in favor of calling FTextLocalizationManager::GetLocalizedCultureNames, potentially followed by FInternationalization::GetAvailableCultures") 1 void GetCulturesWithAvailableLocalization(const TArray< FString > &InLocalizationPaths
Given some paths to look at, populate a list of cultures that we have available localization information for.
UE_DEPRECATED (5.5, "FInternationalization::ForUseOnlyByLocMacroAndGraphNodeTextLiterals_CreateText is deprecated in favor of FText::AsLocalizable_Advanced (NOTE: FText::AsLocalizable_Advanced takes its arguments in a different order!).") static FORCEINLINE FText ForUseOnlyByLocMacroAndGraphNodeTextLiterals_CreateText(const TCHAR *InTextLiteral
Static Public Member Functions
static FInternationalization & Get ()
static bool IsAvailable ()
Checks to see that an internationalization instance exists, and has been initialized.
static void TearDown ()
Data Fields
TArray< FCultureRef > const bool bIncludeDerivedCultures
const TCHAR const TCHAR * InKey
const TCHAR * InNamespace
TArray< FCultureRef > & OutAvailableCultures
Private Types
typedef FLegacyInternationalization FImplementation
Private Member Functions
FInternationalization ()
~FInternationalization ()
void BroadcastCultureChanged ()
void Initialize ()
void Terminate ()
Private Attributes
bool bIsInitialized = false
FCultureChangedEvent CultureChangedEvent
TArray< TTuple< FName, FCulturePtr > > CurrentAssetGroupCultures
The currently active asset group cultures (for package localization).
FCulturePtr CurrentLanguage
The currently active language (for localization).
FCulturePtr CurrentLocale
The currently active locale (for internationalization).
TArray< FCultureRef > CustomCultures
Custom cultures registered via AddCustomCulture.
FCulturePtr DefaultLanguage
The default language specified by the OS.
FCulturePtr DefaultLocale
The default locale specified by the OS.
TUniqueObj< FImplementation > Implementation
FCulturePtr InvariantCulture
An invariant culture that can be used when you don't care about localization/internationalization.
Friends
class FLazySingleton
class FLegacyInternationalization
class FTextChronoFormatter
Detailed Description
Definition at line 23 of file Internationalization.h.
Member Typedef Documentation
FImplementation
typedef FLegacyInternationalization FInternationalization::FImplementation private
Definition at line 237 of file Internationalization.h.
Constructor & Destructor Documentation
FInternationalization()
FInternationalization::FInternationalization () private
Referenced by DECLARE_EVENT(), and Get().
~FInternationalization()
FInternationalization::~FInternationalization () private
Member Function Documentation
AddCustomCulture()
void FInternationalization::AddCustomCulture (const TSharedRef< ICustomCulture > & InCustomCulture)
Add a new custom culture.
BackupCultureState()
void FInternationalization::BackupCultureState (FCultureStateSnapshot & OutSnapshot) const
Backup the current culture state to the given snapshot struct.
BroadcastCultureChanged()
void FInternationalization::BroadcastCultureChanged () inline private
Definition at line 222 of file Internationalization.h.
References CultureChangedEvent.
ClearCurrentAssetGroupCulture()
void FInternationalization::ClearCurrentAssetGroupCulture (const FName & InAssetGroupName)
Clear the given asset group category culture.
DECLARE_EVENT()
FInternationalization::DECLARE_EVENT (FInternationalization , FCultureChangedEvent) & inline
Broadcasts whenever the current culture changes.
Definition at line 214 of file Internationalization.h.
References FInternationalization(), CultureChangedEvent, and DECLARE_EVENT().
Referenced by DECLARE_EVENT().
Get()
FInternationalization & FInternationalization::Get () static
References FInternationalization().
Referenced by UE::Private::LocGen::GetCultureByName().
GetAvailableCultures()
TArray< FCultureRef > FInternationalization::GetAvailableCultures (const TArray< FString > & InCultureNames, const bool bIncludeDerivedCultures)
Given some culture names, populate a list of cultures that are available to be used.
If bIncludeDerivedCultures, include cultures that are derived from those we passed.
References bIncludeDerivedCultures, and GetAvailableCultures().
Referenced by GetAvailableCultures().
GetCulture()
FCulturePtr FInternationalization::GetCulture (const FString & InCultureName)
Get the culture corresponding to the given name.
Returns
The culture for the given name, or null if it couldn't be found.
Referenced by UE::Private::LocGen::GetCultureByName().
GetCultureNames()
void FInternationalization::GetCultureNames (TArray< FString > & CultureNames) const
GetCurrentAssetGroupCulture()
FCultureRef FInternationalization::GetCurrentAssetGroupCulture (const FName & InAssetGroupName) const
Get the given asset group category culture.
Note
Returns the current language if the group category doesn't have a culture override.
GetCurrentCulture()
FCultureRef FInternationalization::GetCurrentCulture () const inline
Get the current culture.
Note
This function exists for legacy API parity with SetCurrentCulture and is equivalent to GetCurrentLanguage. It should never be used in internal localization/internationalization code!
Definition at line 63 of file Internationalization.h.
References CurrentLanguage.
GetCurrentCultures()
TArray< FCultureRef > FInternationalization::GetCurrentCultures (const bool bIncludeLanguage, const bool bIncludeLocale, const bool bIncludeAssetGroups) const
Get the current cultures in use, optionally including the current language, locale, and any asset groups.
GetCurrentLanguage()
FCultureRef FInternationalization::GetCurrentLanguage () const inline
Get the current language (for localization).
Definition at line 77 of file Internationalization.h.
References CurrentLanguage.
GetCurrentLocale()
FCultureRef FInternationalization::GetCurrentLocale () const inline
Get the current locale (for internationalization).
Definition at line 91 of file Internationalization.h.
References CurrentLocale.
GetCustomCulture()
FCulturePtr FInternationalization::GetCustomCulture (const FString & InCultureName) const
Get a new custom culture from its name.
GetDefaultCulture()
FCultureRef FInternationalization::GetDefaultCulture () const inline
Get the default culture specified by the OS.
Note
This function exists for legacy API parity with GetCurrentCulture and is equivalent to GetDefaultLanguage. It should never be used in internal localization/internationalization code!
Definition at line 127 of file Internationalization.h.
References DefaultLanguage.
GetDefaultLanguage()
FCultureRef FInternationalization::GetDefaultLanguage () const inline
Get the default language specified by the OS.
Definition at line 135 of file Internationalization.h.
References DefaultLanguage.
GetDefaultLocale()
FCultureRef FInternationalization::GetDefaultLocale () const inline
Get the default locale specified by the OS.
Definition at line 143 of file Internationalization.h.
References DefaultLocale.
GetInvariantCulture()
FCultureRef FInternationalization::GetInvariantCulture () const inline
Get the invariant culture that can be used when you don't care about localization/internationalization.
Definition at line 151 of file Internationalization.h.
References InvariantCulture.
GetPrioritizedCultureNames()
TArray< FString > FInternationalization::GetPrioritizedCultureNames (const FString & Name)
References Name.
Initialize()
void FInternationalization::Initialize () private
IsAvailable()
bool FInternationalization::IsAvailable () static
Checks to see that an internationalization instance exists, and has been initialized.
Usually you would use Get(), however this may be used to work out whether TearDown() has been called when cleaning up on shutdown.
Referenced by IStringTableEngineBridge::CanFindOrLoadStringTableAsset().
IsCultureAllowed()
bool FInternationalization::IsCultureAllowed (const FString & Name)
Is the given culture enabled or disabled in this build?
References Name.
IsCultureRemapped()
bool FInternationalization::IsCultureRemapped (const FString & Name, FString * OutMappedCulture)
Has the given culture been remapped in this build?
References Name.
IsInitialized()
bool FInternationalization::IsInitialized () const inline
Definition at line 171 of file Internationalization.h.
References bIsInitialized.
LoadAllCultureData()
void FInternationalization::LoadAllCultureData ()
Load and cache the data needed for every culture we know about (this is usually done per-culture as required)
RefreshCachedConfigData()
void FInternationalization::RefreshCachedConfigData ()
Refresh any config data that has been cached.
RefreshCultureDisplayNames()
void FInternationalization::RefreshCultureDisplayNames (const TArray< FString > & InPrioritizedDisplayCultureNames)
Refresh the display names of the cached cultures.
RestoreCultureState()
void FInternationalization::RestoreCultureState (const FCultureStateSnapshot & InSnapshot)
Restore a previous culture state from the given snapshot struct.
SetCurrentAssetGroupCulture()
bool FInternationalization::SetCurrentAssetGroupCulture (const FName & InAssetGroupName, const FString & InCultureName)
Set the given asset group category culture by name.
SetCurrentCulture()
bool FInternationalization::SetCurrentCulture (const FString & InCultureName)
Set the current culture by name.
Note
This function is a sledgehammer, and will set both the language and locale, as well as clear out any asset group cultures that may be set.
SetCurrentCulture should be avoided in Core/Engine code as it may stomp over Editor/Game user-settings.
SetCurrentLanguage()
bool FInternationalization::SetCurrentLanguage (const FString & InCultureName)
Set only the current language (for localization) by name.
Note
Unless you're doing something advanced, you likely want SetCurrentLanguageAndLocale or SetCurrentCulture instead.
SetCurrentLanguageAndLocale()
bool FInternationalization::SetCurrentLanguageAndLocale (const FString & InCultureName)
Set the current language (for localization) and locale (for internationalization) by name.
SetCurrentLocale()
bool FInternationalization::SetCurrentLocale (const FString & InCultureName)
Set only the current locale (for internationalization) by name.
Note
Unless you're doing something advanced, you likely want SetCurrentLanguageAndLocale or SetCurrentCulture instead.
TearDown()
void FInternationalization::TearDown () static
Terminate()
void FInternationalization::Terminate () private
UE_DEPRECATED() [1/2]
FInternationalization::UE_DEPRECATED (4. 20, "FInternationalization::GetCulturesWithAvailableLocalization is deprecated in favor of calling FTextLocalizationManager::GetLocalizedCultureNames , potentially followed by FInternationalization::GetAvailableCultures") const &
Given some paths to look at, populate a list of cultures that we have available localization information for.
If bIncludeDerivedCultures, include cultures that are derived from those we have localization data for.
Note
This function was deprecated as it only provides cultures that use localization resources. FTextLocalizationManager::GetLocalizedCultureNames provides a more complete list when using alternate sources, and FInternationalization::GetAvailableCultures can be used to build a culture array from that list.
UE_DEPRECATED() [2/2]
FInternationalization::UE_DEPRECATED (5. 5, "FInternationalization::ForUseOnlyByLocMacroAndGraphNodeTextLiterals_CreateText is deprecated in favor of FText::AsLocalizable_Advanced (NOTE: FText::AsLocalizable_Advanced takes its arguments in a different order!).") const
Friends And Related Symbol Documentation
FLazySingleton
friend class FLazySingleton friend
Definition at line 220 of file Internationalization.h.
References FLazySingleton.
Referenced by FLazySingleton.
FLegacyInternationalization
friend class FLegacyInternationalization friend
Definition at line 236 of file Internationalization.h.
References FLegacyInternationalization.
Referenced by FLegacyInternationalization.
FTextChronoFormatter
friend class FTextChronoFormatter friend
Definition at line 25 of file Internationalization.h.
References FTextChronoFormatter.
Referenced by FTextChronoFormatter.
Field Documentation
bIncludeDerivedCultures
TArray<FCultureRef> const bool FInternationalization::bIncludeDerivedCultures
Definition at line 208 of file Internationalization.h.
Referenced by GetAvailableCultures().
bIsInitialized
bool FInternationalization::bIsInitialized = false private
Definition at line 228 of file Internationalization.h.
Referenced by IsInitialized().
CultureChangedEvent
FCultureChangedEvent FInternationalization::CultureChangedEvent private
Definition at line 230 of file Internationalization.h.
Referenced by BroadcastCultureChanged(), and DECLARE_EVENT().
CurrentAssetGroupCultures
TArray<TTuple<FName, FCulturePtr> > FInternationalization::CurrentAssetGroupCultures private
The currently active asset group cultures (for package localization).
Note
This is deliberately an array for performance reasons (we expect to have a very small number of groups).
Definition at line 255 of file Internationalization.h.
CurrentLanguage
FCulturePtr FInternationalization::CurrentLanguage private
The currently active language (for localization).
Definition at line 244 of file Internationalization.h.
Referenced by GetCurrentCulture(), and GetCurrentLanguage().
CurrentLocale
FCulturePtr FInternationalization::CurrentLocale private
The currently active locale (for internationalization).
Definition at line 249 of file Internationalization.h.
Referenced by GetCurrentLocale().
CustomCultures
TArray<FCultureRef> FInternationalization::CustomCultures private
Custom cultures registered via AddCustomCulture.
Definition at line 275 of file Internationalization.h.
DefaultLanguage
FCulturePtr FInternationalization::DefaultLanguage private
The default language specified by the OS.
Definition at line 260 of file Internationalization.h.
Referenced by GetDefaultCulture(), and GetDefaultLanguage().
DefaultLocale
FCulturePtr FInternationalization::DefaultLocale private
The default locale specified by the OS.
Definition at line 265 of file Internationalization.h.
Referenced by GetDefaultLocale().
Implementation
TUniqueObj<FImplementation> FInternationalization::Implementation private
Definition at line 239 of file Internationalization.h.
InKey
const TCHAR const TCHAR* FInternationalization::InKey
Initial value:
{
        return FText::AsLocalizable_Advanced(InNamespace, InKey, InTextLiteral)
Definition at line 36 of file Internationalization.h.
InNamespace
const TCHAR* FInternationalization::InNamespace
Definition at line 36 of file Internationalization.h.
InvariantCulture
FCulturePtr FInternationalization::InvariantCulture private
An invariant culture that can be used when you don't care about localization/internationalization.
Definition at line 270 of file Internationalization.h.
Referenced by GetInvariantCulture().
OutAvailableCultures
TArray<FCultureRef>& FInternationalization::OutAvailableCultures
Definition at line 208 of file Internationalization.h.
The documentation for this class was generated from the following file:
Internationalization.h