Unreal Engine 5.6 C++ API: UE::AnimNext::FNodeTemplateRegistryHandle Struct Reference
UE::AnimNext::FNodeTemplateRegistryHandle Struct Reference final
FNodeTemplateRegistryHandle.
#include "NodeTemplateRegistryHandle.h"
Public Member Functions
FNodeTemplateRegistryHandle ()=default
int32 GetTemplateOffset () const
bool IsValid () const
bool operator!= (FNodeTemplateRegistryHandle RHS) const
bool operator== (FNodeTemplateRegistryHandle RHS) const
Private Member Functions
FNodeTemplateRegistryHandle (int16 TemplateOffset_)
Static Private Member Functions
static FNodeTemplateRegistryHandle MakeHandle (int32 TemplateOffset_)
Private Attributes
int16 TemplateOffset = 0
Friends
struct FNodeTemplateRegistry
Detailed Description
FNodeTemplateRegistryHandle.
Encapsulates a value used as a handle in the node template registry. When valid, it can be used to retrieve a pointer to the corresponding node template.
Definition at line 15 of file NodeTemplateRegistryHandle.h.
Constructor & Destructor Documentation
FNodeTemplateRegistryHandle() [1/2]
UE::AnimNext::FNodeTemplateRegistryHandle::FNodeTemplateRegistryHandle () default
Referenced by MakeHandle(), operator!=(), and operator==().
FNodeTemplateRegistryHandle() [2/2]
UE::AnimNext::FNodeTemplateRegistryHandle::FNodeTemplateRegistryHandle (int16 TemplateOffset_) inline explicit private
Definition at line 31 of file NodeTemplateRegistryHandle.h.
References TemplateOffset.
Member Function Documentation
GetTemplateOffset()
int32 UE::AnimNext::FNodeTemplateRegistryHandle::GetTemplateOffset () const inline
Definition at line 24 of file NodeTemplateRegistryHandle.h.
References INDEX_NONE, IsValid(), and TemplateOffset.
IsValid()
bool UE::AnimNext::FNodeTemplateRegistryHandle::IsValid () const inline
Definition at line 21 of file NodeTemplateRegistryHandle.h.
References TemplateOffset.
Referenced by GetTemplateOffset().
MakeHandle()
FNodeTemplateRegistryHandle UE::AnimNext::FNodeTemplateRegistryHandle::MakeHandle (int32 TemplateOffset_) inline static private
Definition at line 36 of file NodeTemplateRegistryHandle.h.
References FNodeTemplateRegistryHandle(), and check.
operator!=()
bool UE::AnimNext::FNodeTemplateRegistryHandle::operator!= (FNodeTemplateRegistryHandle RHS) const inline
Definition at line 28 of file NodeTemplateRegistryHandle.h.
References FNodeTemplateRegistryHandle(), and TemplateOffset.
operator==()
bool UE::AnimNext::FNodeTemplateRegistryHandle::operator== (FNodeTemplateRegistryHandle RHS) const inline
Definition at line 27 of file NodeTemplateRegistryHandle.h.
References FNodeTemplateRegistryHandle(), and TemplateOffset.
Friends And Related Symbol Documentation
FNodeTemplateRegistry
friend struct FNodeTemplateRegistry friend
Definition at line 46 of file NodeTemplateRegistryHandle.h.
References FNodeTemplateRegistry.
Referenced by FNodeTemplateRegistry.
Field Documentation
TemplateOffset
int16 UE::AnimNext::FNodeTemplateRegistryHandle::TemplateOffset = 0 private
Definition at line 44 of file NodeTemplateRegistryHandle.h.
Referenced by FNodeTemplateRegistryHandle(), GetTemplateOffset(), IsValid(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
NodeTemplateRegistryHandle.h