Unreal Engine 5.6 C++ API: ScopeExitSupport::TScopeGuard< FuncType > Class Template Reference
ScopeExitSupport::TScopeGuard< FuncType > Class Template Reference
Not meant for direct consumption : use ON_SCOPE_EXIT instead.
#include "ScopeExit.h"
Public Member Functions
TScopeGuard (FuncType &&InFunc)
~TScopeGuard ()
Private Member Functions
TScopeGuard (const TScopeGuard &)=delete
TScopeGuard (TScopeGuard &&)=delete
TScopeGuard & operator= (const TScopeGuard &)=delete
TScopeGuard & operator= (TScopeGuard &&)=delete
Private Attributes
FuncType Func
Detailed Description
template<typename FuncType>
class ScopeExitSupport::TScopeGuard< FuncType >
Not meant for direct consumption : use ON_SCOPE_EXIT instead.
RAII class that calls a lambda when it is destroyed.
Definition at line 13 of file ScopeExit.h.
Constructor & Destructor Documentation
TScopeGuard() [1/3]
template<typename FuncType> ScopeExitSupport::TScopeGuard< FuncType >::TScopeGuard (TScopeGuard< FuncType > &&) private delete
References TScopeGuard().
Referenced by TScopeGuard(), TScopeGuard(), operator=(), and operator=().
TScopeGuard() [2/3]
template<typename FuncType> ScopeExitSupport::TScopeGuard< FuncType >::TScopeGuard (const TScopeGuard< FuncType > &) private delete
References TScopeGuard().
TScopeGuard() [3/3]
template<typename FuncType> ScopeExitSupport::TScopeGuard< FuncType >::TScopeGuard (FuncType && InFunc) inline explicit
Definition at line 22 of file ScopeExit.h.
References Func.
~TScopeGuard()
template<typename FuncType> ScopeExitSupport::TScopeGuard< FuncType >::~TScopeGuard () inline
Definition at line 28 of file ScopeExit.h.
References Func.
Member Function Documentation
operator=() [1/2]
template<typename FuncType> TScopeGuard & ScopeExitSupport::TScopeGuard< FuncType >::operator= (const TScopeGuard< FuncType > &) private delete
References TScopeGuard().
operator=() [2/2]
template<typename FuncType> TScopeGuard & ScopeExitSupport::TScopeGuard< FuncType >::operator= (TScopeGuard< FuncType > &&) private delete
References TScopeGuard().
Field Documentation
Func
template<typename FuncType> FuncType ScopeExitSupport::TScopeGuard< FuncType >::Func private
Definition at line 35 of file ScopeExit.h.
Referenced by TScopeGuard(), and ~TScopeGuard().
The documentation for this class was generated from the following file:
ScopeExit.h