Unreal Engine 5.6 C++ API: UnFbx::FFbxCurvesAPI Class Reference
UnFbx::FFbxCurvesAPI Class Reference
#include "FbxImporter.h"
Public Member Functions
FFbxCurvesAPI ()
UNREALED_API void GetAllNodeNameArray (TArray< FString > &AllNodeNames) const
UNREALED_API void GetAllNodePropertyCurveHandles (const FString &NodeName, const FString &PropertyName, TArray< FFbxAnimCurveHandle > &PropertyCurveHandles) const
UNREALED_API void GetAnimatedNodeNameArray (TArray< FString > &AnimatedNodeNames) const
UNREALED_API void GetBakeCurveData (const FFbxAnimCurveHandle &CurveHandle, TArray< float > &CurveData, float PeriodTime, float StartTime=0.0f, float StopTime=-1.0f, bool bNegative=false, float Scale=1.0f) const
UNREALED_API void GetBakeCurveData (const FString &NodeName, const FString &PropertyName, int32 ChannelIndex, int32 CompositeIndex, TArray< float > &CurveData, float PeriodTime, float StartTime=0.0f, float StopTime=-1.0f, bool bNegative=false, float Scale=1.0f) const
UNREALED_API void GetConvertedNonTransformCurveData (const FString &NodeName, bool bUseSequencerCurve, float UniformScale, TMap< FName, FRichCurve > &OutCurves)
UNREALED_API void GetConvertedTransformCurveData (const FString &NodeName, FRichCurve &TranslationX, FRichCurve &TranslationY, FRichCurve &TranslationZ, FRichCurve &EulerRotationX, FRichCurve &EulerRotationY, FRichCurve &EulerRotationZ, FRichCurve &ScaleX, FRichCurve &ScaleY, FRichCurve &ScaleZ, FTransform &DefaultTransform, bool bUseSequencerCurve, float UniformScale=1.0f) const
UNREALED_API void GetCurveData (const FFbxAnimCurveHandle &CurveHandle, FRichCurve &CurveData, bool bNegative, float Scale=1.0f) const
UNREALED_API void GetCurveData (const FString &NodeName, const FString &PropertyName, int32 ChannelIndex, int32 CompositeIndex, FRichCurve &CurveData, bool bNegative) const
UNREALED_API void GetCurveDataForSequencer (const FFbxAnimCurveHandle &CurveHandle, FRichCurve &RichCurve, bool bNegative, float Scale=1.0f) const
UNREALED_API void GetCurveDataForSequencer (const FString &NodeName, const FString &PropertyName, int32 ChannelIndex, int32 CompositeIndex, FRichCurve &RichCurve, bool bNegative, float Scale=1.0f) const
UNREALED_API void GetCurveHandle (const FString &NodeName, const FString &PropertyName, int32 ChannelIndex, int32 CompositeIndex, FFbxAnimCurveHandle &CurveHandle) const
UNREALED_API void GetCustomStringPropertyArray (const FString &NodeName, TArray< TPair< FString, FString > > &CustomPropertyPairs) const
UNREALED_API void GetNodeAnimatedPropertyNameArray (const FString &NodeName, TArray< FString > &AnimatedPropertyNames) const
UE_DEPRECATED (4.21, "Please use FRichCurve version instead to get tangent weight support") UNREALED_API void GetConvertedTransformCurveData(const FString &NodeName
UE_DEPRECATED (4.21, "Please use FRichCurve version instead to get tangent weight support") UNREALED_API void GetCurveData(const FFbxAnimCurveHandle &CurveHandle
UE_DEPRECATED (4.21, "Please use FRichCurve version instead to get tangent weight support") UNREALED_API void GetCurveData(const FString &NodeName
Data Fields
const FString int32 ChannelIndex
const FString int32 int32 CompositeIndex
const FString int32 int32 FInterpCurveFloat bool bNegative const
FInterpCurveFloat bool bNegative const
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FTransform &DefaultTransform const
const FString int32 int32 FInterpCurveFloat & CurveData
FInterpCurveFloat & CurveData
TMap< uint64, FFbxAnimNodeHandle > CurvesData
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & EulerRotationX
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & EulerRotationY
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & EulerRotationZ
const FString & PropertyName
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & ScaleX
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & ScaleY
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & ScaleZ
FbxScene * Scene
TMap< uint64, FTransform > TransformData
FInterpCurveFloat & TranslationX
FInterpCurveFloat FInterpCurveFloat & TranslationY
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat & TranslationZ
Private Member Functions
EInterpCurveMode GetUnrealInterpMode (FbxAnimCurveKey FbxKey) const
Detailed Description
Definition at line 338 of file FbxImporter.h.
Constructor & Destructor Documentation
FFbxCurvesAPI()
UnFbx::FFbxCurvesAPI::FFbxCurvesAPI () inline
Definition at line 341 of file FbxImporter.h.
References Scene.
Member Function Documentation
GetAllNodeNameArray()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetAllNodeNameArray (TArray< FString > & AllNodeNames) const
GetAllNodePropertyCurveHandles()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetAllNodePropertyCurveHandles (const FString & NodeName, const FString & PropertyName, TArray< FFbxAnimCurveHandle > & PropertyCurveHandles) const
References const, GetAllNodePropertyCurveHandles(), and PropertyName.
Referenced by GetAllNodePropertyCurveHandles().
GetAnimatedNodeNameArray()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetAnimatedNodeNameArray (TArray< FString > & AnimatedNodeNames) const
GetBakeCurveData() [1/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetBakeCurveData (const FFbxAnimCurveHandle & CurveHandle, TArray< float > & CurveData, float PeriodTime, float StartTime = 0.0f, float StopTime = -1.0f, bool bNegative = false, float Scale = 1.0f) const
References const, CurveData, GetBakeCurveData(), and Scale.
GetBakeCurveData() [2/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetBakeCurveData (const FString & NodeName, const FString & PropertyName, int32 ChannelIndex, int32 CompositeIndex, TArray< float > & CurveData, float PeriodTime, float StartTime = 0.0f, float StopTime = -1.0f, bool bNegative = false, float Scale = 1.0f) const
References ChannelIndex, CompositeIndex, const, CurveData, GetBakeCurveData(), PropertyName, and Scale.
Referenced by GetBakeCurveData(), and GetBakeCurveData().
GetConvertedNonTransformCurveData()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetConvertedNonTransformCurveData (const FString & NodeName, bool bUseSequencerCurve, float UniformScale, TMap< FName, FRichCurve > & OutCurves)
References const, and GetConvertedNonTransformCurveData().
Referenced by GetConvertedNonTransformCurveData().
GetConvertedTransformCurveData()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetConvertedTransformCurveData (const FString & NodeName, FRichCurve & TranslationX, FRichCurve & TranslationY, FRichCurve & TranslationZ, FRichCurve & EulerRotationX, FRichCurve & EulerRotationY, FRichCurve & EulerRotationZ, FRichCurve & ScaleX, FRichCurve & ScaleY, FRichCurve & ScaleZ, FTransform & DefaultTransform, bool bUseSequencerCurve, float UniformScale = 1.0f) const
References const, EulerRotationX, EulerRotationY, EulerRotationZ, GetConvertedTransformCurveData(), ScaleX, ScaleY, ScaleZ, TranslationX, TranslationY, and TranslationZ.
Referenced by GetConvertedTransformCurveData().
GetCurveData() [1/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCurveData (const FFbxAnimCurveHandle & CurveHandle, FRichCurve & CurveData, bool bNegative, float Scale = 1.0f) const
References const, CurveData, GetCurveData(), and Scale.
GetCurveData() [2/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCurveData (const FString & NodeName, const FString & PropertyName, int32 ChannelIndex, int32 CompositeIndex, FRichCurve & CurveData, bool bNegative) const
References ChannelIndex, CompositeIndex, const, CurveData, GetCurveData(), and PropertyName.
Referenced by GetCurveData(), and GetCurveData().
GetCurveDataForSequencer() [1/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCurveDataForSequencer (const FFbxAnimCurveHandle & CurveHandle, FRichCurve & RichCurve, bool bNegative, float Scale = 1.0f) const
References const, GetCurveDataForSequencer(), and Scale.
GetCurveDataForSequencer() [2/2]
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCurveDataForSequencer (const FString & NodeName, const FString & PropertyName, int32 ChannelIndex, int32 CompositeIndex, FRichCurve & RichCurve, bool bNegative, float Scale = 1.0f) const
References ChannelIndex, CompositeIndex, const, GetCurveDataForSequencer(), PropertyName, and Scale.
Referenced by GetCurveDataForSequencer(), and GetCurveDataForSequencer().
GetCurveHandle()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCurveHandle (const FString & NodeName, const FString & PropertyName, int32 ChannelIndex, int32 CompositeIndex, FFbxAnimCurveHandle & CurveHandle) const
References ChannelIndex, CompositeIndex, const, GetCurveHandle(), and PropertyName.
Referenced by GetCurveHandle().
GetCustomStringPropertyArray()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetCustomStringPropertyArray (const FString & NodeName, TArray< TPair< FString, FString > > & CustomPropertyPairs) const
GetNodeAnimatedPropertyNameArray()
UNREALED_API void UnFbx::FFbxCurvesAPI::GetNodeAnimatedPropertyNameArray (const FString & NodeName, TArray< FString > & AnimatedPropertyNames) const
GetUnrealInterpMode()
EInterpCurveMode UnFbx::FFbxCurvesAPI::GetUnrealInterpMode (FbxAnimCurveKey FbxKey) const private
References const, and GetUnrealInterpMode().
Referenced by GetUnrealInterpMode().
UE_DEPRECATED() [1/3]
UnFbx::FFbxCurvesAPI::UE_DEPRECATED (4. 21, "Please use FRichCurve version instead to get tangent weight support") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UnFbx::FFbxCurvesAPI::UE_DEPRECATED (4. 21, "Please use FRichCurve version instead to get tangent weight support") const &
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
UnFbx::FFbxCurvesAPI::UE_DEPRECATED (4. 21, "Please use FRichCurve version instead to get tangent weight support") const &
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
ChannelIndex
const FString int32 UnFbx::FFbxCurvesAPI::ChannelIndex
Definition at line 352 of file FbxImporter.h.
Referenced by GetBakeCurveData(), GetCurveData(), GetCurveDataForSequencer(), and GetCurveHandle().
CompositeIndex
const FString int32 int32 UnFbx::FFbxCurvesAPI::CompositeIndex
Definition at line 352 of file FbxImporter.h.
Referenced by GetBakeCurveData(), GetCurveData(), GetCurveDataForSequencer(), and GetCurveHandle().
const [1/3]
const FString int32 int32 FInterpCurveFloat bool bNegative UnFbx::FFbxCurvesAPI::const
Definition at line 352 of file FbxImporter.h.
Referenced by GetAllNodePropertyCurveHandles(), GetBakeCurveData(), GetBakeCurveData(), GetConvertedNonTransformCurveData(), GetConvertedTransformCurveData(), GetCurveData(), GetCurveData(), GetCurveDataForSequencer(), GetCurveDataForSequencer(), GetCurveHandle(), and GetUnrealInterpMode().
const [2/3]
FInterpCurveFloat bool bNegative UnFbx::FFbxCurvesAPI::const
Definition at line 367 of file FbxImporter.h.
const [3/3]
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FTransform& DefaultTransform UnFbx::FFbxCurvesAPI::const
Definition at line 383 of file FbxImporter.h.
CurveData [1/2]
const FString int32 int32 FInterpCurveFloat& UnFbx::FFbxCurvesAPI::CurveData
Definition at line 352 of file FbxImporter.h.
Referenced by GetBakeCurveData(), GetBakeCurveData(), GetCurveData(), and GetCurveData().
CurveData [2/2]
FInterpCurveFloat& UnFbx::FFbxCurvesAPI::CurveData
Definition at line 367 of file FbxImporter.h.
CurvesData
TMap<uint64, FFbxAnimNodeHandle> UnFbx::FFbxCurvesAPI::CurvesData
Definition at line 391 of file FbxImporter.h.
EulerRotationX
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::EulerRotationX
Definition at line 381 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
EulerRotationY
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::EulerRotationY
Definition at line 381 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
EulerRotationZ
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::EulerRotationZ
Definition at line 381 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
PropertyName
const FString& UnFbx::FFbxCurvesAPI::PropertyName
Definition at line 352 of file FbxImporter.h.
Referenced by GetAllNodePropertyCurveHandles(), GetBakeCurveData(), GetCurveData(), GetCurveDataForSequencer(), and GetCurveHandle().
ScaleX
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::ScaleX
Definition at line 382 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
ScaleY
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::ScaleY
Definition at line 382 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
ScaleZ
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::ScaleZ
Definition at line 382 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
Scene
FbxScene* UnFbx::FFbxCurvesAPI::Scene
Definition at line 390 of file FbxImporter.h.
Referenced by FFbxCurvesAPI().
TransformData
TMap<uint64, FTransform> UnFbx::FFbxCurvesAPI::TransformData
Definition at line 392 of file FbxImporter.h.
TranslationX
FInterpCurveFloat& UnFbx::FFbxCurvesAPI::TranslationX
Definition at line 380 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
TranslationY
FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::TranslationY
Definition at line 380 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
TranslationZ
FInterpCurveFloat FInterpCurveFloat FInterpCurveFloat& UnFbx::FFbxCurvesAPI::TranslationZ
Definition at line 380 of file FbxImporter.h.
Referenced by GetConvertedTransformCurveData().
The documentation for this class was generated from the following file:
FbxImporter.h