Unreal Engine 5.6 C++ API: FIoRequest Class Reference
FIoRequest Class Reference final
#include "IoDispatcher.h"
Public Member Functions
FIoRequest ()=default
FIoRequest (const FIoRequest &Other)
FIoRequest (FIoRequest &&Other)
~FIoRequest ()
void Cancel ()
const FIoBuffer * GetResult () const
const FIoBuffer & GetResultOrDie () const
FIoRequest & operator= (const FIoRequest &Other)
FIoRequest & operator= (FIoRequest &&Other)
void Release ()
FIoStatus Status () const
void UpdatePriority (int32 NewPriority)
Private Member Functions
FIoRequest (FIoRequestImpl *InImpl)
Private Attributes
FIoRequestImpl * Impl = nullptr
Friends
class FIoBatch
class FIoDispatcher
class FIoDispatcherImpl
Detailed Description
Definition at line 236 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoRequest() [1/4]
FIoRequest::FIoRequest () default
Referenced by FIoRequest(), FIoRequest(), operator=(), and operator=().
~FIoRequest()
FIoRequest::~FIoRequest ()
FIoRequest() [2/4]
FIoRequest::FIoRequest (const FIoRequest & Other)
References FIoRequest(), and Other.
FIoRequest() [3/4]
FIoRequest::FIoRequest (FIoRequest && Other)
References FIoRequest(), and Other.
FIoRequest() [4/4]
FIoRequest::FIoRequest (FIoRequestImpl * InImpl) explicit private
Member Function Documentation
Cancel()
void FIoRequest::Cancel ()
GetResult()
const FIoBuffer * FIoRequest::GetResult () const
GetResultOrDie()
const FIoBuffer & FIoRequest::GetResultOrDie () const
operator=() [1/2]
FIoRequest & FIoRequest::operator= (const FIoRequest & Other)
References FIoRequest(), and Other.
operator=() [2/2]
FIoRequest & FIoRequest::operator= (FIoRequest && Other)
References FIoRequest(), and Other.
Release()
void FIoRequest::Release ()
Status()
FIoStatus FIoRequest::Status () const
UpdatePriority()
void FIoRequest::UpdatePriority (int32 NewPriority)
Friends And Related Symbol Documentation
FIoBatch
friend class FIoBatch friend
Definition at line 260 of file IoDispatcher.h.
References FIoBatch.
Referenced by FIoBatch.
FIoDispatcher
friend class FIoDispatcher friend
Definition at line 258 of file IoDispatcher.h.
References FIoDispatcher.
Referenced by FIoDispatcher.
FIoDispatcherImpl
friend class FIoDispatcherImpl friend
Definition at line 259 of file IoDispatcher.h.
References FIoDispatcherImpl.
Referenced by FIoDispatcherImpl.
Field Documentation
Impl
FIoRequestImpl* FIoRequest::Impl = nullptr private
Definition at line 254 of file IoDispatcher.h.
The documentation for this class was generated from the following file:
IoDispatcher.h