Unreal Engine 5.6 C++ API: FPropertyPath Class Reference
FPropertyPath Class Reference
#include "PropertyPath.h"
Public Member Functions
void AddProperty (const FPropertyInfo &InProperty)
Add another property to be associated with this path.
TSharedRef< FPropertyPath > ExtendPath (const FPropertyInfo &NewLeaf) const
TSharedRef< FPropertyPath > ExtendPath (const TSharedRef< FPropertyPath > &Extension) const
const FPropertyInfo & GetLeafMostProperty () const
int32 GetNumProperties () const
const FPropertyInfo & GetPropertyInfo (int32 index) const
FPropertyInfo & GetPropertyInfoRef (int32 index)
const FPropertyInfo & GetRootProperty () const
bool IsValid () const
PROPERTYEDITOR_API TArray< UE::FPropertyPathName > ToPropertyPathName () const
Converts this to an array of property path names that are split between objects in the path.
FString ToString (const TCHAR *Separator=TEXT("->")) const
TSharedRef< FPropertyPath > TrimPath (const int32 AmountToTrim) const
TSharedRef< FPropertyPath > TrimRoot (const int32 AmountToTrim) const
Static Public Member Functions
static bool AreEqual (const TSharedRef< FPropertyPath > &PathLhs, const TSharedRef< FPropertyPath > &PathRhs)
static TSharedRef< FPropertyPath > Create (const TWeakFieldPtr< FProperty > Property)
static TSharedRef< FPropertyPath > CreateEmpty ()
Private Attributes
TArray< FPropertyInfo > Properties
Detailed Description
Definition at line 39 of file PropertyPath.h.
Member Function Documentation
AddProperty()
void FPropertyPath::AddProperty (const FPropertyInfo & InProperty) inline
Add another property to be associated with this path.
Definition at line 172 of file PropertyPath.h.
References Properties.
AreEqual()
bool FPropertyPath::AreEqual (const TSharedRef< FPropertyPath > & PathLhs, const TSharedRef< FPropertyPath > & PathRhs) inline static
Definition at line 178 of file PropertyPath.h.
References FPropertyInfo::ArrayIndex, and FPropertyInfo::Property.
Create()
TSharedRef< FPropertyPath > FPropertyPath::Create (const TWeakFieldPtr< FProperty > Property) inline static
Definition at line 48 of file PropertyPath.h.
References FPropertyInfo::ArrayIndex, INDEX_NONE, MakeShareable(), Property, and FPropertyInfo::Property.
CreateEmpty()
TSharedRef< FPropertyPath > FPropertyPath::CreateEmpty () inline static
Definition at line 43 of file PropertyPath.h.
References MakeShareable().
ExtendPath() [1/2]
TSharedRef< FPropertyPath > FPropertyPath::ExtendPath (const FPropertyInfo & NewLeaf) const inline
Definition at line 91 of file PropertyPath.h.
References MakeShareable(), and Properties.
ExtendPath() [2/2]
TSharedRef< FPropertyPath > FPropertyPath::ExtendPath (const TSharedRef< FPropertyPath > & Extension) const inline
Definition at line 101 of file PropertyPath.h.
References MakeShareable(), and Properties.
GetLeafMostProperty()
const FPropertyInfo & FPropertyPath::GetLeafMostProperty () const inline
Definition at line 81 of file PropertyPath.h.
References Properties.
Referenced by FPropertyTrackEditor< TrackType >::InitializeNewTrack(), and FPropertyTrackEditor< TrackType >::OnKeyProperty().
GetNumProperties()
int32 FPropertyPath::GetNumProperties () const inline
Definition at line 66 of file PropertyPath.h.
References Properties.
Referenced by FPropertyTrackEditor< TrackType >::BuildNamingPropertyPath(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), and operator==().
GetPropertyInfo()
const FPropertyInfo & FPropertyPath::GetPropertyInfo (int32 index) const inline
Definition at line 71 of file PropertyPath.h.
References Properties.
Referenced by FPropertyTrackEditor< TrackType >::BuildNamingPropertyPath(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), and operator==().
GetPropertyInfoRef()
FPropertyInfo & FPropertyPath::GetPropertyInfoRef (int32 index) inline
Definition at line 76 of file PropertyPath.h.
References Properties.
GetRootProperty()
const FPropertyInfo & FPropertyPath::GetRootProperty () const inline
Definition at line 86 of file PropertyPath.h.
References Properties.
IsValid()
bool FPropertyPath::IsValid () const inline
Definition at line 61 of file PropertyPath.h.
References Properties.
ToPropertyPathName()
PROPERTYEDITOR_API TArray< UE::FPropertyPathName > FPropertyPath::ToPropertyPathName () const
Converts this to an array of property path names that are split between objects in the path.
ToString()
FString FPropertyPath::ToString (const TCHAR * Separator = TEXT("->")) const inline
Definition at line 141 of file PropertyPath.h.
References FPropertyInfo::ArrayIndex, FField::GetFName(), INDEX_NONE, FField::IsA(), Properties, FPropertyInfo::Property, FField::StaticClass(), TEXT, and FName::ToString().
Referenced by FPropertyTrackEditor< TrackType >::OnKeyProperty().
TrimPath()
TSharedRef< FPropertyPath > FPropertyPath::TrimPath (const int32 AmountToTrim) const inline
Definition at line 115 of file PropertyPath.h.
References Count, MakeShareable(), and Properties.
TrimRoot()
TSharedRef< FPropertyPath > FPropertyPath::TrimRoot (const int32 AmountToTrim) const inline
Definition at line 129 of file PropertyPath.h.
References Count, MakeShareable(), and Properties.
Field Documentation
Properties
TArray< FPropertyInfo > FPropertyPath::Properties private
Definition at line 212 of file PropertyPath.h.
Referenced by AddProperty(), ExtendPath(), ExtendPath(), GetLeafMostProperty(), GetNumProperties(), GetPropertyInfo(), GetPropertyInfoRef(), GetRootProperty(), IsValid(), ToString(), TrimPath(), and TrimRoot().
The documentation for this class was generated from the following file:
PropertyPath.h