Unreal Engine 5.6 C++ API: TSubclassOf< T > Class Template Reference
TSubclassOf< T > Class Template Reference
Template to allow UClass types to be passed around with type safety.
#include "SubclassOf.h"
Public Types
using ElementType = T
Public Member Functions
TSubclassOf ()=default
TSubclassOf (const TSubclassOf &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TSubclassOf (const TSubclassOf< OtherT > &Other)
Construct from another TSubclassOf, only if types are compatible.
TSubclassOf (TSubclassOf &&)=default
template<typename U UE_REQUIRES>
FORCEINLINE TSubclassOf (U &&From)
Construct from a UClass* (or something implicitly convertible to it)
FORCEINLINE TSubclassOf (UClass *From)
Constructor that takes a UClass*.
~TSubclassOf ()=default
FORCEINLINE UClass * Get () const
Dereference back into a UClass*, does runtime type checking.
FORCEINLINE T * GetDefaultObject () const
Get the CDO if we are referencing a valid class.
TObjectPtr< UClass > & GetGCPtr ()
FORCEINLINE operator UClass * () const
Implicit conversion to UClass*, does runtime type checking.
FORCEINLINE UClass * operator* () const
Dereference back into a UClass*, does runtime type checking.
FORCEINLINE UClass * operator-> () const
Dereference back into a UClass*, does runtime type checking.
TSubclassOf & operator= (const TSubclassOf &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TSubclassOf & operator= (const TSubclassOf< OtherT > &Other)
Assign from another TSubclassOf, only if types are compatible.
TSubclassOf & operator= (TSubclassOf &&)=default
template<typename U UE_REQUIRES>
FORCEINLINE TSubclassOf & operator= (U &&From)
Assign from a UClass* (or something implicitly convertible to it).
FORCEINLINE TSubclassOf & operator= (UClass *From)
Assign from a UClass*.
FORCEINLINE void Serialize (FArchive &Ar)
FORCEINLINE void Serialize (FStructuredArchiveSlot &Slot)
Private Attributes
TObjectPtr< UClass > Class = nullptr
Friends
template<typename U>
class TSubclassOf
uint32 GetTypeHash (const TSubclassOf &SubclassOf)
Detailed Description
template<typename T>
class TSubclassOf< T >
Template to allow UClass types to be passed around with type safety.
Definition at line 29 of file SubclassOf.h.
Member Typedef Documentation
ElementType
template<typename T> using TSubclassOf< T >::ElementType = T
Definition at line 36 of file SubclassOf.h.
Constructor & Destructor Documentation
TSubclassOf() [1/6]
template<typename T> TSubclassOf< T >::TSubclassOf () nodiscard default
TSubclassOf() [2/6]
template<typename T> TSubclassOf< T >::TSubclassOf (TSubclassOf< T > &&) nodiscard default
TSubclassOf() [3/6]
template<typename T> TSubclassOf< T >::TSubclassOf (const TSubclassOf< T > &) nodiscard default
~TSubclassOf()
template<typename T> TSubclassOf< T >::~TSubclassOf () default
TSubclassOf() [4/6]
template<typename T> FORCEINLINE TSubclassOf< T >::TSubclassOf (UClass * From) inline nodiscard
Constructor that takes a UClass*.
Definition at line 46 of file SubclassOf.h.
TSubclassOf() [5/6]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TSubclassOf< T >::TSubclassOf (U && From) inline nodiscard
Construct from a UClass* (or something implicitly convertible to it)
Definition at line 59 of file SubclassOf.h.
TSubclassOf() [6/6]
template<typename T> template<typename OtherT UE_REQUIRES> FORCEINLINE TSubclassOf< T >::TSubclassOf (const TSubclassOf< OtherT > & Other) inline nodiscard
Construct from another TSubclassOf, only if types are compatible.
Definition at line 69 of file SubclassOf.h.
Member Function Documentation
Get()
template<typename T> FORCEINLINE UClass * TSubclassOf< T >::Get () const inline nodiscard
Dereference back into a UClass*, does runtime type checking.
Definition at line 119 of file SubclassOf.h.
Referenced by FActorPartitionIdentifier::GetTypeHash, TNonNullSubclassOf< T >::operator==(), and IInterface_AssetUserData::UFUNCTION().
GetDefaultObject()
template<typename T> FORCEINLINE T * TSubclassOf< T >::GetDefaultObject () const inline nodiscard
Get the CDO if we are referencing a valid class.
Returns
the CDO, or null if class is null
Definition at line 141 of file SubclassOf.h.
GetGCPtr()
template<typename T> TObjectPtr< UClass > & TSubclassOf< T >::GetGCPtr () inline nodiscard
Definition at line 167 of file SubclassOf.h.
operator UClass *()
template<typename T> FORCEINLINE TSubclassOf< T >::operator UClass * () const inline nodiscard
Implicit conversion to UClass*, does runtime type checking.
Definition at line 131 of file SubclassOf.h.
operator*()
template<typename T> FORCEINLINE UClass * TSubclassOf< T >::operator* () const inline nodiscard
Dereference back into a UClass*, does runtime type checking.
Definition at line 109 of file SubclassOf.h.
operator->()
template<typename T> FORCEINLINE UClass * TSubclassOf< T >::operator-> () const inline nodiscard
Dereference back into a UClass*, does runtime type checking.
Definition at line 125 of file SubclassOf.h.
operator=() [1/5]
template<typename T> TSubclassOf & TSubclassOf< T >::operator= (const TSubclassOf< T > &) default
operator=() [2/5]
template<typename T> template<typename OtherT UE_REQUIRES> FORCEINLINE TSubclassOf & TSubclassOf< T >::operator= (const TSubclassOf< OtherT > & Other) inline
Assign from another TSubclassOf, only if types are compatible.
Definition at line 80 of file SubclassOf.h.
operator=() [3/5]
template<typename T> TSubclassOf & TSubclassOf< T >::operator= (TSubclassOf< T > &&) default
Referenced by TNonNullSubclassOf< T >::operator=(), and TNonNullSubclassOf< T >::operator=().
operator=() [4/5]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TSubclassOf & TSubclassOf< T >::operator= (U && From) inline
Assign from a UClass* (or something implicitly convertible to it).
Definition at line 102 of file SubclassOf.h.
operator=() [5/5]
template<typename T> FORCEINLINE TSubclassOf & TSubclassOf< T >::operator= (UClass * From) inline
Assign from a UClass*.
Definition at line 88 of file SubclassOf.h.
Serialize() [1/2]
template<typename T> FORCEINLINE void TSubclassOf< T >::Serialize (FArchive & Ar) inline
Definition at line 152 of file SubclassOf.h.
Referenced by operator<<(), and operator<<().
Serialize() [2/2]
template<typename T> FORCEINLINE void TSubclassOf< T >::Serialize (FStructuredArchiveSlot & Slot) inline
Definition at line 157 of file SubclassOf.h.
Friends And Related Symbol Documentation
TSubclassOf
template<typename T> template<typename U> friend class TSubclassOf friend
Definition at line 33 of file SubclassOf.h.
Referenced by TNonNullSubclassOf< T >::TNonNullSubclassOf(), and TNonNullSubclassOf< T >::operator=().
GetTypeHash
template<typename T> uint32 GetTypeHash (const TSubclassOf< T > & SubclassOf) friend
Definition at line 162 of file SubclassOf.h.
Referenced by TSubclassOf< const T >::GetTypeHash.
Field Documentation
Class
template<typename T> TObjectPtr<UClass> TSubclassOf< T >::Class = nullptr private
Definition at line 182 of file SubclassOf.h.
Referenced by TSubclassOf< const T >::GetTypeHash.
The documentation for this class was generated from the following files:
CacheAdapter.h
SubclassOf.h