Unreal Engine 5.6 C++ API: FMovieSceneChannelProxyData Struct Reference
FMovieSceneChannelProxyData Struct Reference
Construction helper that is required to create a new FMovieSceneChannelProxy from multiple channels.
#include "MovieSceneChannelProxy.h"
Public Member Functions
template<typename ChannelType>
void Add (ChannelType &InChannel, const FMovieSceneChannelMetaData &InMetaData)
Add a new channel to the proxy.
template<typename ChannelType, typename ExtendedEditorDataType>
void Add (ChannelType &InChannel, const FMovieSceneChannelMetaData &InMetaData, ExtendedEditorDataType &&InExtendedEditorData)
Add a new channel to the proxy.
template<typename ChannelType>
FMovieSceneChannelHandle AddWithDefaultEditorData (ChannelType &InChannel, const FMovieSceneChannelMetaData &InMetaData)
Add a new channel to the proxy.
template<typename ChannelType, typename ExtendedEditorDataType>
void SetExtendedEditorData (FMovieSceneChannelHandle ChannelHandle, ExtendedEditorDataType &&InExtendedEditorData)
Private Member Functions
template<typename ChannelType>
int32 AddInternal (ChannelType &InChannel)
Implementation that adds a channel to an entry, creating a new entry for this channel type if necessary.
Private Attributes
TArray< FMovieSceneChannelEntry, TInlineAllocator< 1 > > Entries
Array of entryies, one per channel type.
Friends
struct FMovieSceneChannelProxy
Detailed Description
Construction helper that is required to create a new FMovieSceneChannelProxy from multiple channels.
Definition at line 86 of file MovieSceneChannelProxy.h.
Member Function Documentation
Add() [1/2]
template<typename ChannelType> void FMovieSceneChannelProxyData::Add (ChannelType & InChannel, const FMovieSceneChannelMetaData & InMetaData) inline
Add a new channel to the proxy.
Channel's address is stored internally as a voic* and should exist as long as the channel proxy does
Parameters
InChannel The channel to add to this proxy. Should live for as long as the proxy does. Any re-allocation should be accompanied with a re-creation of the proxy
InMetaData The editor meta data to be associated with this channel
Definition at line 97 of file MovieSceneChannelProxy.h.
References AddInternal(), and Entries.
Referenced by UE::MovieScene::AddChannelProxy(), and UE::MovieScene::MakeChannelProxy().
Add() [2/2]
template<typename ChannelType, typename ExtendedEditorDataType> void FMovieSceneChannelProxyData::Add (ChannelType & InChannel, const FMovieSceneChannelMetaData & InMetaData, ExtendedEditorDataType && InExtendedEditorData) inline
Add a new channel to the proxy.
Channel's address is stored internally as a voic* and should exist as long as the channel proxy does
Parameters
InChannel The channel to add to this proxy. Should live for as long as the proxy does. Any re-allocation should be accompanied with a re-creation of the proxy
InMetaData The editor meta data to be associated with this channel
InExtendedEditorData Additional editor data to be associated with this channel as per its traits
Definition at line 137 of file MovieSceneChannelProxy.h.
References AddInternal(), Entries, and Forward().
AddInternal()
template<typename ChannelType> int32 FMovieSceneChannelProxyData::AddInternal (ChannelType & InChannel) private
Implementation that adds a channel to an entry, creating a new entry for this channel type if necessary.
Parameters
InChannel The channel to add to this proxy. Should live for as long as the proxy does. Any re-allocation should be accompanied with a re-creation of the proxy
Definition at line 399 of file MovieSceneChannelProxy.h.
References check, Entries, FMovieSceneChannelEntry::GetChannelTypeName(), Algo::LowerBoundBy(), and FMovieSceneChannelHandle::TrackChannelTypeName().
Referenced by Add(), Add(), and AddWithDefaultEditorData().
AddWithDefaultEditorData()
template<typename ChannelType> FMovieSceneChannelHandle FMovieSceneChannelProxyData::AddWithDefaultEditorData (ChannelType & InChannel, const FMovieSceneChannelMetaData & InMetaData) inline
Add a new channel to the proxy.
Channel's address is stored internally as a voic* and should exist as long as the channel proxy does
Parameters
InChannel The channel to add to this proxy. Should live for as long as the proxy does. Any re-allocation should be accompanied with a re-creation of the proxy
InMetaData The editor meta data to be associated with this channel
Definition at line 115 of file MovieSceneChannelProxy.h.
References AddInternal(), Entries, and Num.
SetExtendedEditorData()
template<typename ChannelType, typename ExtendedEditorDataType> void FMovieSceneChannelProxyData::SetExtendedEditorData (FMovieSceneChannelHandle ChannelHandle, ExtendedEditorDataType && InExtendedEditorData) inline
Definition at line 149 of file MovieSceneChannelProxy.h.
References FMovieSceneChannelEntry::ChannelTypeName, ensure, Entries, FMovieSceneChannelHandle::GetChannelIndex(), FMovieSceneChannelHandle::GetChannelTypeName(), and FMovieSceneChannelEditorDataEntry::SetExtendedEditorData().
Referenced by UE::MovieScene::AddChannelProxy(), and UE::MovieScene::MakeChannelProxy().
Friends And Related Symbol Documentation
FMovieSceneChannelProxy
friend struct FMovieSceneChannelProxy friend
Definition at line 187 of file MovieSceneChannelProxy.h.
References FMovieSceneChannelProxy.
Referenced by FMovieSceneChannelProxy.
Field Documentation
Entries
TArray<FMovieSceneChannelEntry, TInlineAllocator<1> > FMovieSceneChannelProxyData::Entries private
Array of entryies, one per channel type.
Inline allocation space for one entry since most sections only have one channel type.
Definition at line 189 of file MovieSceneChannelProxy.h.
Referenced by Add(), Add(), AddInternal(), AddWithDefaultEditorData(), and SetExtendedEditorData().
The documentation for this struct was generated from the following file:
MovieSceneChannelProxy.h