Unreal Engine 5.6 C++ API: TStructView< BaseStructT > Struct Template Reference
TStructView< BaseStructT > Struct Template Reference
TStructView is a type-safe FStructView wrapper against the given BaseStruct type.
#include "StructView.h"
Public Member Functions
TStructView ()=default
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TStructView (const TSharedStruct< T > &SharedStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TStructView (T &InStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TStructView (TInstancedStruct< T > &InstancedStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TStructView (uint8 *InStructMemory=nullptr)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
T & Get () const
Returns mutable reference to the struct, this getter assumes that all data is valid.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
T * GetPtr () const
Returns mutable pointer to the struct, or nullptr if cast is not valid.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator!= (const TStructView< T > &Other) const
BaseStructT * operator-> () const
Simplified accessor for members of the guaranteed minimum structure type.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator== (const TStructView< T > &Other) const
Comparison operators.
Public Member Functions inherited from FStructView
FStructView ()=default
FStructView (const FSharedStruct &SharedStruct)
FStructView (const UScriptStruct *InScriptStruct, uint8 *InStructMemory=nullptr)
FStructView (FInstancedStruct &InstancedStruct)
template<typename T>
T & Get () const
Returns mutable reference to the struct, this getter assumes that all data is valid.
uint8 * GetMemory () const
Returns pointer to struct memory.
template<typename T>
T * GetPtr () const
Returns mutable pointer to the struct, or nullptr if cast is not valid.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
bool IsValid () const
Returns True if the struct is valid.
template<typename OtherType>
bool operator!= (const OtherType &Other) const
template<typename OtherType>
bool operator== (const OtherType &Other) const
Comparison operators.
void Reset ()
Reset to empty.
Additional Inherited Members
Static Public Member Functions inherited from FStructView
template<typename T>
static FStructView Make (T &InStruct)
Creates a new FStructView from the templated struct.
Protected Attributes inherited from FStructView
const UScriptStruct * ScriptStruct = nullptr
uint8 * StructMemory = nullptr
Detailed Description
template<typename BaseStructT>
struct TStructView< BaseStructT >
TStructView is a type-safe FStructView wrapper against the given BaseStruct type.
Example:
TStructView<FTestStructBase> Test;
TArray<TStructView<FTestStructBase>> TestArray;
Definition at line 116 of file StructUtils/StructView.h.
Constructor & Destructor Documentation
TStructView() [1/5]
template<typename BaseStructT> TStructView< BaseStructT >::TStructView () explicit default
Referenced by operator!=(), and operator==().
TStructView() [2/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TStructView< BaseStructT >::TStructView (T & InStruct) inline
Definition at line 123 of file StructUtils/StructView.h.
References FStructView::FStructView(), and StaticStruct().
TStructView() [3/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TStructView< BaseStructT >::TStructView (uint8 * InStructMemory = nullptr) inline explicit
Definition at line 128 of file StructUtils/StructView.h.
References FStructView::FStructView(), and StaticStruct().
TStructView() [4/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TStructView< BaseStructT >::TStructView (TInstancedStruct< T > & InstancedStruct) inline
Definition at line 133 of file StructUtils/StructView.h.
References FStructView::FStructView(), and FStructView::GetScriptStruct().
TStructView() [5/5]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TStructView< BaseStructT >::TStructView (const TSharedStruct< T > & SharedStruct) inline
Definition at line 138 of file StructUtils/StructView.h.
References FStructView::FStructView(), FStructView::GetMemory(), and FStructView::GetScriptStruct().
Member Function Documentation
Get()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> T & TStructView< BaseStructT >::Get () const inline
Returns mutable reference to the struct, this getter assumes that all data is valid.
Definition at line 144 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructRef(), FStructView::ScriptStruct, and FStructView::StructMemory.
GetPtr()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> T * TStructView< BaseStructT >::GetPtr () const inline
Returns mutable pointer to the struct, or nullptr if cast is not valid.
Definition at line 151 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructPtr(), FStructView::ScriptStruct, and FStructView::StructMemory.
Referenced by operator->().
operator!=()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TStructView< BaseStructT >::operator!= (const TStructView< T > & Other) const inline
Definition at line 178 of file StructUtils/StructView.h.
References TStructView(), operator==(), and Other.
operator->()
template<typename BaseStructT> BaseStructT * TStructView< BaseStructT >::operator-> () const inline
Simplified accessor for members of the guaranteed minimum structure type.
Definition at line 164 of file StructUtils/StructView.h.
References check, GetPtr(), and IsValid().
operator==()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TStructView< BaseStructT >::operator== (const TStructView< T > & Other) const inline
Comparison operators.
Note: it does not compare the internal structure itself
Definition at line 172 of file StructUtils/StructView.h.
References TStructView(), Other, FStructView::ScriptStruct, and FStructView::StructMemory.
The documentation for this struct was generated from the following files:
StructUtils/SharedStruct.h
StructUtils/StructView.h