Unreal Engine 5.6 C++ API: FActorDeferredScriptManager Class Reference
FActorDeferredScriptManager Class Reference
#include "ActorDeferredScriptManager.h"
Public Member Functions
void AddActor (AActor *InActor)
Add an actor for the manager to run the construction of once dependent asset compilation are done (i.e Static Mesh)
void FinishAllCompilation () override
empty implementation since deferred actor scripts are not actually async
void Shutdown () override
Cancel any pending work and blocks until it is safe to shut down.
Static Public Member Functions
static FActorDeferredScriptManager & Get ()
static FName GetStaticAssetTypeName ()
Get the name of the asset type this compiler handles.
Private Member Functions
FActorDeferredScriptManager ()
void EnsureEventRegistered ()
FTextFormat GetAssetNameFormat () const override
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
FName GetAssetTypeName () const override
A unique name among all asset compiling manager to identify the type of asset this manager handles.
TArrayView< FName > GetDependentTypeNames () const override
Return other asset types that should preferably be handled before this one.
int32 GetNumRemainingAssets () const override
Returns the number of remaining compilations.
void OnAssetPostCompile (const TArray< FAssetCompileData > &CompiledAssets)
void OnWorldCleanup (class UWorld *InWorld, bool bInSessionEnded, bool bInCleanupResources)
void ProcessAsyncTasks (bool bLimitExecutionTime=false) override
Called once per frame, fetches completed tasks and applies them to the scene.
void UpdateCompilationNotification ()
Private Member Functions inherited from IAssetCompilingManager
virtual void FinishCompilationForObjects (TArrayView< UObject *const > InObjects)
Blocks until completion of the requested objects.
virtual void MarkCompilationAsCanceled (TArrayView< UObject *const > InObjects)
Mark compilation of the provided objects as canceled.
virtual ~IAssetCompilingManager ()
virtual void ProcessAsyncTasks (const AssetCompilation::FProcessAsyncTaskParams &Params)
Called once per frame, fetches completed tasks and applies them to the scene.
Private Attributes
int32 NextIndexToProcess = 0
Where to start on the next ProcessAsyncTasks iteration.
TUniquePtr< FAsyncCompilationNotification > Notification
Notification for the amount of pending construction scripts to run.
int32 NumLeftToProcess = 0
What's left to process if we were aborted because of execution time limit.
FDelegateHandle OnAssetChangeDelegateHandle
We need to monitor when static meshes have finished compiling to only work when necessary.
FDelegateHandle OnWorldCleanupDelegateHandle
We need to monitor when worlds are cleaned up to avoid triggering any construction script past this point.
TArray< TWeakObjectPtr< AActor > > PendingConstructionScriptActors
Actors awaiting outstanding asset compilation prior to running their non trivial construction scripts after loading this level.
Friends
class FAssetCompilingManager
Detailed Description
Definition at line 14 of file ActorDeferredScriptManager.h.
Constructor & Destructor Documentation
FActorDeferredScriptManager()
FActorDeferredScriptManager::FActorDeferredScriptManager () private
Referenced by Get().
Member Function Documentation
AddActor()
void FActorDeferredScriptManager::AddActor (AActor * InActor)
Add an actor for the manager to run the construction of once dependent asset compilation are done (i.e Static Mesh)
EnsureEventRegistered()
void FActorDeferredScriptManager::EnsureEventRegistered () private
FinishAllCompilation()
void FActorDeferredScriptManager::FinishAllCompilation () inline override virtual
empty implementation since deferred actor scripts are not actually async
Implements IAssetCompilingManager.
Definition at line 30 of file ActorDeferredScriptManager.h.
References ProcessAsyncTasks().
Get()
FActorDeferredScriptManager & FActorDeferredScriptManager::Get () static
References FActorDeferredScriptManager().
GetAssetNameFormat()
FTextFormat FActorDeferredScriptManager::GetAssetNameFormat () const override private virtual
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
Note: Should be in a similar form as "{0}|plural(one=Singular Name,other=Plural Name)"
Implements IAssetCompilingManager.
GetAssetTypeName()
FName FActorDeferredScriptManager::GetAssetTypeName () const override private virtual
A unique name among all asset compiling manager to identify the type of asset this manager handles.
Implements IAssetCompilingManager.
GetDependentTypeNames()
TArrayView< FName > FActorDeferredScriptManager::GetDependentTypeNames () const override private virtual
Return other asset types that should preferably be handled before this one.
Implements IAssetCompilingManager.
GetNumRemainingAssets()
int32 FActorDeferredScriptManager::GetNumRemainingAssets () const override private virtual
Returns the number of remaining compilations.
Implements IAssetCompilingManager.
GetStaticAssetTypeName()
FName FActorDeferredScriptManager::GetStaticAssetTypeName () static
Get the name of the asset type this compiler handles.
OnAssetPostCompile()
void FActorDeferredScriptManager::OnAssetPostCompile (const TArray< FAssetCompileData > & CompiledAssets) private
OnWorldCleanup()
void FActorDeferredScriptManager::OnWorldCleanup (class UWorld * InWorld, bool bInSessionEnded, bool bInCleanupResources) private
ProcessAsyncTasks()
void FActorDeferredScriptManager::ProcessAsyncTasks (bool bLimitExecutionTime = false) override private virtual
Called once per frame, fetches completed tasks and applies them to the scene.
Implements IAssetCompilingManager.
Referenced by FinishAllCompilation().
Shutdown()
void FActorDeferredScriptManager::Shutdown () override virtual
Cancel any pending work and blocks until it is safe to shut down.
Implements IAssetCompilingManager.
UpdateCompilationNotification()
void FActorDeferredScriptManager::UpdateCompilationNotification () private
Friends And Related Symbol Documentation
FAssetCompilingManager
friend class FAssetCompilingManager friend
Definition at line 41 of file ActorDeferredScriptManager.h.
References FAssetCompilingManager.
Referenced by FAssetCompilingManager.
Field Documentation
NextIndexToProcess
int32 FActorDeferredScriptManager::NextIndexToProcess = 0 private
Where to start on the next ProcessAsyncTasks iteration.
Definition at line 71 of file ActorDeferredScriptManager.h.
Notification
TUniquePtr<FAsyncCompilationNotification> FActorDeferredScriptManager::Notification private
Notification for the amount of pending construction scripts to run.
Definition at line 62 of file ActorDeferredScriptManager.h.
NumLeftToProcess
int32 FActorDeferredScriptManager::NumLeftToProcess = 0 private
What's left to process if we were aborted because of execution time limit.
Definition at line 74 of file ActorDeferredScriptManager.h.
OnAssetChangeDelegateHandle
FDelegateHandle FActorDeferredScriptManager::OnAssetChangeDelegateHandle private
We need to monitor when static meshes have finished compiling to only work when necessary.
Definition at line 65 of file ActorDeferredScriptManager.h.
OnWorldCleanupDelegateHandle
FDelegateHandle FActorDeferredScriptManager::OnWorldCleanupDelegateHandle private
We need to monitor when worlds are cleaned up to avoid triggering any construction script past this point.
Definition at line 68 of file ActorDeferredScriptManager.h.
PendingConstructionScriptActors
TArray<TWeakObjectPtr<AActor> > FActorDeferredScriptManager::PendingConstructionScriptActors private
Actors awaiting outstanding asset compilation prior to running their non trivial construction scripts after loading this level.
Definition at line 59 of file ActorDeferredScriptManager.h.
The documentation for this class was generated from the following file:
ActorDeferredScriptManager.h