Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicPointSet3< RealType > Class Template Reference
UE::Geometry::TDynamicPointSet3< RealType > Class Template Reference
TDynamicPointSet3 implements a dynamic 3D point set, templated on real-value type (float or double).
#include "DynamicPointSet3.h"
Public Member Functions
int AppendVertex (const TVector< RealType > &Position)
Append vertex at position, returns vid.
void BeginUnsafeVerticesInsert ()
Call this before a set of unsafe InsertVertex() calls.
void Clear ()
Discard all data.
RealType CompactMetric () const
returns measure of compactness in range [0,1], where 1 is fully compacted
void EndUnsafeVerticesInsert ()
Call after a set of unsafe InsertVertex() calls to rebuild free list.
TDynamicAttributeSetBase< TDynamicPointSet3< RealType > > * GetBaseAttributeSet () const
TAxisAlignedBox3< RealType > GetBounds () const
Returns bounding box of all points.
TVector< RealType > GetVertex (int VertexID) const
const TDynamicVector< double > & GetVerticesBuffer ()
const FRefCountVector & GetVerticesRefCounts ()
EMeshResult InsertVertex (int VertexID, const TVector< RealType > &Position, bool bUnsafe=false)
Insert vertex at given index, assuming it is unused.
bool IsCompact () const
bool IsVertex (int VertexID) const
int MaxVertexID () const
EMeshResult RemoveVertex (int VertexID)
Remove point.
void SetExternallyManagedAttributes (TDynamicAttributeSetBase< TDynamicPointSet3< RealType > > *AttributeSet)
void SetVertex (int VertexID, const TVector< RealType > &vNewPos)
Set vertex position.
int VertexCount () const
FRefCountVector::IndexEnumerable VertexIndicesItr () const
FRefCountVector::MappedEnumerable< TVector< RealType > > VerticesItr () const
Enumerate positions of all points.
Protected Attributes
TDynamicAttributeSetBase< TDynamicPointSet3< RealType > > * BaseAttributeSet = nullptr
Base attribute set.
FRefCountVector VertexRefCounts
Reference counts of vertex indices.
TDynamicVector< RealType > Vertices
List of vertex positions.
Detailed Description
template<typename RealType>
class UE::Geometry::TDynamicPointSet3< RealType >
TDynamicPointSet3 implements a dynamic 3D point set, templated on real-value type (float or double).
The points are indexed and the class allows for gaps in the index space.
The points are referred to as "Vertices" for consistency with higher-level Mesh and Graph classes. This class can be used interchangeably with the Vertices of those classes in some cases (for example in spatial data structures like TDynamicVerticesOctree3)
The point data is stored in via TDynamicVector<RealType>, which internally uses chunked storage and so is relatively efficient to grow/shrink/etc
Reference counts for the points are stored via a FRefCountVector instance
A per-point attribute set can optionally be attached. Currently the client is responsible for managing the memory for this attribute set. The attribute set will be automatically updated when points are added or removed.
Definition at line 43 of file DynamicPointSet3.h.
Member Function Documentation
AppendVertex()
template<typename RealType> int UE::Geometry::TDynamicPointSet3< RealType >::AppendVertex (const TVector< RealType > & Position) inline
Append vertex at position, returns vid.
Definition at line 116 of file DynamicPointSet3.h.
BeginUnsafeVerticesInsert()
template<typename RealType> void UE::Geometry::TDynamicPointSet3< RealType >::BeginUnsafeVerticesInsert () inline
Call this before a set of unsafe InsertVertex() calls.
Definition at line 133 of file DynamicPointSet3.h.
Clear()
template<typename RealType> void UE::Geometry::TDynamicPointSet3< RealType >::Clear () inline
Discard all data.
Definition at line 107 of file DynamicPointSet3.h.
CompactMetric()
template<typename RealType> RealType UE::Geometry::TDynamicPointSet3< RealType >::CompactMetric () const inline
returns measure of compactness in range [0,1], where 1 is fully compacted
Definition at line 232 of file DynamicPointSet3.h.
EndUnsafeVerticesInsert()
template<typename RealType> void UE::Geometry::TDynamicPointSet3< RealType >::EndUnsafeVerticesInsert () inline
Call after a set of unsafe InsertVertex() calls to rebuild free list.
Definition at line 139 of file DynamicPointSet3.h.
GetBaseAttributeSet()
template<typename RealType> TDynamicAttributeSetBase< TDynamicPointSet3< RealType > > * UE::Geometry::TDynamicPointSet3< RealType >::GetBaseAttributeSet () const inline
Definition at line 68 of file DynamicPointSet3.h.
Referenced by UE::Geometry::TDynamicPointSet3< float >::AppendVertex(), UE::Geometry::TDynamicPointSet3< float >::InsertVertex(), and UE::Geometry::TDynamicPointSet3< float >::RemoveVertex().
GetBounds()
template<typename RealType> TAxisAlignedBox3< RealType > UE::Geometry::TDynamicPointSet3< RealType >::GetBounds () const inline
Returns bounding box of all points.
Definition at line 243 of file DynamicPointSet3.h.
GetVertex()
template<typename RealType> TVector< RealType > UE::Geometry::TDynamicPointSet3< RealType >::GetVertex (int VertexID) const inline
Returns
the vertex position
Definition at line 183 of file DynamicPointSet3.h.
GetVerticesBuffer()
template<typename RealType> const TDynamicVector< double > & UE::Geometry::TDynamicPointSet3< RealType >::GetVerticesBuffer () inline
Definition at line 260 of file DynamicPointSet3.h.
GetVerticesRefCounts()
template<typename RealType> const FRefCountVector & UE::Geometry::TDynamicPointSet3< RealType >::GetVerticesRefCounts () inline
Definition at line 264 of file DynamicPointSet3.h.
InsertVertex()
template<typename RealType> EMeshResult UE::Geometry::TDynamicPointSet3< RealType >::InsertVertex (int VertexID, const TVector< RealType > & Position, bool bUnsafe = false) inline
Insert vertex at given index, assuming it is unused.
If bUnsafe, we use fast id allocation that does not update free list. You should only be using this between BeginUnsafeVerticesInsert() / EndUnsafeVerticesInsert() calls
Definition at line 149 of file DynamicPointSet3.h.
IsCompact()
template<typename RealType> bool UE::Geometry::TDynamicPointSet3< RealType >::IsCompact () const inline
Returns
true if vertex count == max vertex id
Definition at line 226 of file DynamicPointSet3.h.
IsVertex()
template<typename RealType> bool UE::Geometry::TDynamicPointSet3< RealType >::IsVertex (int VertexID) const inline
Returns
true if VertexID is a valid vertex in this point set
Definition at line 94 of file DynamicPointSet3.h.
Referenced by UE::Geometry::TDynamicPointSet3< float >::GetVertex(), and UE::Geometry::TDynamicPointSet3< float >::SetVertex().
MaxVertexID()
template<typename RealType> int UE::Geometry::TDynamicPointSet3< RealType >::MaxVertexID () const inline
Returns
upper bound on vertex IDs used in the point set, ie all vertex IDs in use are < MaxVertexID
Definition at line 87 of file DynamicPointSet3.h.
Referenced by UE::Geometry::TDynamicPointSet3< float >::CompactMetric().
RemoveVertex()
template<typename RealType> EMeshResult UE::Geometry::TDynamicPointSet3< RealType >::RemoveVertex (int VertexID) inline
Remove point.
Definition at line 282 of file DynamicPointSet3.h.
SetExternallyManagedAttributes()
template<typename RealType> void UE::Geometry::TDynamicPointSet3< RealType >::SetExternallyManagedAttributes (TDynamicAttributeSetBase< TDynamicPointSet3< RealType > > * AttributeSet) inline
Definition at line 63 of file DynamicPointSet3.h.
SetVertex()
template<typename RealType> void UE::Geometry::TDynamicPointSet3< RealType >::SetVertex (int VertexID, const TVector< RealType > & vNewPos) inline
Set vertex position.
Definition at line 191 of file DynamicPointSet3.h.
VertexCount()
template<typename RealType> int UE::Geometry::TDynamicPointSet3< RealType >::VertexCount () const inline
Returns
number of vertices in the point set
Definition at line 81 of file DynamicPointSet3.h.
Referenced by UE::Geometry::TDynamicPointSet3< float >::CompactMetric().
VertexIndicesItr()
template<typename RealType> FRefCountVector::IndexEnumerable UE::Geometry::TDynamicPointSet3< RealType >::VertexIndicesItr () const inline
Returns
enumerable object for valid vertex indices suitable for use with range-based for, ie for (int i : VertexIndicesItr())
Definition at line 208 of file DynamicPointSet3.h.
Referenced by UE::Geometry::TDynamicPointSet3< float >::GetBounds().
VerticesItr()
template<typename RealType> FRefCountVector::MappedEnumerable< TVector< RealType > > UE::Geometry::TDynamicPointSet3< RealType >::VerticesItr () const inline
Enumerate positions of all points.
Definition at line 214 of file DynamicPointSet3.h.
Field Documentation
BaseAttributeSet
template<typename RealType> TDynamicAttributeSetBase<TDynamicPointSet3<RealType> >* UE::Geometry::TDynamicPointSet3< RealType >::BaseAttributeSet = nullptr protected
Base attribute set.
Definition at line 53 of file DynamicPointSet3.h.
VertexRefCounts
template<typename RealType> FRefCountVector UE::Geometry::TDynamicPointSet3< RealType >::VertexRefCounts protected
Reference counts of vertex indices.
Iterate over this to find out which vertex indices are valid.
Definition at line 47 of file DynamicPointSet3.h.
Vertices
template<typename RealType> TDynamicVector<RealType> UE::Geometry::TDynamicPointSet3< RealType >::Vertices protected
List of vertex positions.
Definition at line 49 of file DynamicPointSet3.h.
The documentation for this class was generated from the following file:
DynamicPointSet3.h