Unreal Engine 5.6 C++ API: Metasound::FFrontendQueryKey Struct Reference
Metasound::FFrontendQueryKey Struct Reference
FFrontendQueryKey allows entries to be partitioned by their key.
#include "MetasoundFrontendQuery.h"
Data Structures
struct FNull
Public Member Functions
METASOUNDFRONTEND_API FFrontendQueryKey ()
FFrontendQueryKey (const FFrontendQueryKey &)=default
METASOUNDFRONTEND_API FFrontendQueryKey (const FName &InKey)
METASOUNDFRONTEND_API FFrontendQueryKey (const FString &InKey)
FFrontendQueryKey (FFrontendQueryKey &&)=default
METASOUNDFRONTEND_API FFrontendQueryKey (int32 InKey)
METASOUNDFRONTEND_API bool IsNull () const
FFrontendQueryKey & operator= (const FFrontendQueryKey &)=default
FFrontendQueryKey & operator= (FFrontendQueryKey &&)=default
Private Types
using FKeyType = TVariant<FNull, int32, FString, FName>
Private Attributes
uint32 Hash
FKeyType Key
Friends
uint32 GetTypeHash (const FFrontendQueryKey &InKey)
bool operator!= (const FFrontendQueryKey &InLHS, const FFrontendQueryKey &InRHS)
bool operator< (const FFrontendQueryKey &InLHS, const FFrontendQueryKey &InRHS)
bool operator== (const FFrontendQueryKey &InLHS, const FFrontendQueryKey &InRHS)
Detailed Description
FFrontendQueryKey allows entries to be partitioned by their key.
A key can be created by default constructor, int32, FString or FName.
Definition at line 207 of file MetasoundFrontendQuery.h.
Member Typedef Documentation
FKeyType
using Metasound::FFrontendQueryKey::FKeyType = TVariant<FNull, int32, FString, FName> private
Definition at line 229 of file MetasoundFrontendQuery.h.
Constructor & Destructor Documentation
FFrontendQueryKey() [1/6]
METASOUNDFRONTEND_API Metasound::FFrontendQueryKey::FFrontendQueryKey ()
References UE_API.
Referenced by FFrontendQueryKey(), FFrontendQueryKey(), GetTypeHash, operator!=, operator<, operator=(), operator=(), and operator==.
FFrontendQueryKey() [2/6]
METASOUNDFRONTEND_API Metasound::FFrontendQueryKey::FFrontendQueryKey (int32 InKey) explicit
References UE_API.
FFrontendQueryKey() [3/6]
METASOUNDFRONTEND_API Metasound::FFrontendQueryKey::FFrontendQueryKey (const FString & InKey) explicit
References UE_API.
FFrontendQueryKey() [4/6]
METASOUNDFRONTEND_API Metasound::FFrontendQueryKey::FFrontendQueryKey (const FName & InKey) explicit
References UE_API.
FFrontendQueryKey() [5/6]
Metasound::FFrontendQueryKey::FFrontendQueryKey (const FFrontendQueryKey &) default
References FFrontendQueryKey().
FFrontendQueryKey() [6/6]
Metasound::FFrontendQueryKey::FFrontendQueryKey (FFrontendQueryKey &&) default
References FFrontendQueryKey().
Member Function Documentation
IsNull()
METASOUNDFRONTEND_API bool Metasound::FFrontendQueryKey::IsNull () const
References UE_API.
operator=() [1/2]
FFrontendQueryKey & Metasound::FFrontendQueryKey::operator= (const FFrontendQueryKey &) default
References FFrontendQueryKey().
operator=() [2/2]
FFrontendQueryKey & Metasound::FFrontendQueryKey::operator= (FFrontendQueryKey &&) default
References FFrontendQueryKey().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFrontendQueryKey & InKey) friend
References FFrontendQueryKey().
operator!=
bool operator!= (const FFrontendQueryKey & InLHS, const FFrontendQueryKey & InRHS) friend
References FFrontendQueryKey().
operator<
bool operator< (const FFrontendQueryKey & InLHS, const FFrontendQueryKey & InRHS) friend
References FFrontendQueryKey().
operator==
bool operator== (const FFrontendQueryKey & InLHS, const FFrontendQueryKey & InRHS) friend
References FFrontendQueryKey().
Field Documentation
Hash
uint32 Metasound::FFrontendQueryKey::Hash private
Definition at line 231 of file MetasoundFrontendQuery.h.
Key
FKeyType Metasound::FFrontendQueryKey::Key private
Definition at line 230 of file MetasoundFrontendQuery.h.
The documentation for this struct was generated from the following file:
MetasoundFrontendQuery.h