Unreal Engine 5.6 C++ API: FShaderCompilerDefinitions Class Reference
FShaderCompilerDefinitions Class Reference
Container for shader compiler definitions.
#include "ShaderCompilerDefinitions.h"
Data Structures
class FConstIterator
struct FPairType
Public Member Functions
RENDERCORE_API FShaderCompilerDefinitions (bool bIncludeInitialDefines=false)
RENDERCORE_API FShaderCompilerDefinitions (const FShaderCompilerDefinitions &)
bool Contains (FName Name) const
void Empty ()
int32 GetIntegerValue (FName Name) const
int32 GetIntegerValue (FShaderCompilerDefineNameCache &NameCache, int32 ResultIfNotFound) const
void Merge (const FShaderCompilerDefinitions &Other)
FORCEINLINE int32 Num () const
FShaderCompilerDefinitions & operator= (const FShaderCompilerDefinitions &Other)
void SetDefine (FName Name, const FString &Value)
void SetDefine (FName Name, const TCHAR *Value)
template<typename ValueType>
void SetDefine (FName Name, ValueType Value)
Value types supported: bool, int32, uint32, float, const TCHAR*, FString&.
void SetDefine (FShaderCompilerDefineNameCache &Name, const FString &Value)
void SetDefine (FShaderCompilerDefineNameCache &Name, const TCHAR *Value)
template<typename ValueType>
void SetDefine (FShaderCompilerDefineNameCache &Name, ValueType Value)
Private Member Functions
int32 FindMapIndex (FName Key, uint32 KeyHash) const
int32 FindOrAddMapIndex (FName Name)
int32 FindOrAddMapIndex (FShaderCompilerDefineNameCache &NameCache)
void InternalSetValue (int32 Index, bool Value)
void InternalSetValue (int32 Index, const TCHAR *Value)
void InternalSetValue (int32 Index, float Value)
void InternalSetValue (int32 Index, int32 Value)
void InternalSetValue (int32 Index, uint32 Value)
FORCEINLINE void SetValueType (int32 Index, EShaderCompilerDefineVariant InValueType)
Static Private Member Functions
static RENDERCORE_API void InitializeInitialDefines (const FShaderCompilerDefinitions &InDefines)
Called from FShaderInitialDefinesInitializer.
Private Attributes
uint32 InitialDefineCount
FHashTable KeyHashTable
TArray< FPairType > Pairs
TArray< FString > StringValues
uint32 ValueCount
TArray< EShaderCompilerDefineVariant > ValueTypes
Static Private Attributes
static RENDERCORE_API FShaderCompilerDefinitions * GInitialDefines
Friends
struct FShaderInitialDefinesInitializer
FArchive & operator<< (FArchive &Ar, FShaderCompilerDefinitions &Defs)
Detailed Description
Container for shader compiler definitions.
Definition at line 23 of file ShaderCompilerDefinitions.h.
Constructor & Destructor Documentation
FShaderCompilerDefinitions() [1/2]
RENDERCORE_API FShaderCompilerDefinitions::FShaderCompilerDefinitions (bool bIncludeInitialDefines = false)
Referenced by FShaderCompilerDefinitions::FConstIterator::FConstIterator(), FShaderCompilerDefinitions(), InitializeInitialDefines(), Merge(), operator<<, and operator=().
FShaderCompilerDefinitions() [2/2]
RENDERCORE_API FShaderCompilerDefinitions::FShaderCompilerDefinitions (const FShaderCompilerDefinitions &)
References FShaderCompilerDefinitions().
Member Function Documentation
Contains()
bool FShaderCompilerDefinitions::Contains (FName Name) const inline
Definition at line 109 of file ShaderCompilerDefinitions.h.
References FindMapIndex(), GetTypeHash(), INDEX_NONE, Name, None, and ValueTypes.
Empty()
void FShaderCompilerDefinitions::Empty () inline
Definition at line 120 of file ShaderCompilerDefinitions.h.
References GInitialDefines, InitialDefineCount, KeyHashTable, Pairs, StringValues, ValueCount, and ValueTypes.
FindMapIndex()
int32 FShaderCompilerDefinitions::FindMapIndex (FName Key, uint32 KeyHash) const inline private
Definition at line 314 of file ShaderCompilerDefinitions.h.
References INDEX_NONE, Key, KeyHashTable, and Pairs.
Referenced by Contains(), FindOrAddMapIndex(), FindOrAddMapIndex(), GetIntegerValue(), and GetIntegerValue().
FindOrAddMapIndex() [1/2]
int32 FShaderCompilerDefinitions::FindOrAddMapIndex (FName Name) inline private
Definition at line 326 of file ShaderCompilerDefinitions.h.
References FindMapIndex(), GetTypeHash(), INDEX_NONE, KeyHashTable, Name, None, Pairs, and ValueTypes.
Referenced by operator<<, SetDefine(), SetDefine(), SetDefine(), SetDefine(), SetDefine(), and SetDefine().
FindOrAddMapIndex() [2/2]
int32 FShaderCompilerDefinitions::FindOrAddMapIndex (FShaderCompilerDefineNameCache & NameCache) inline private
Definition at line 339 of file ShaderCompilerDefinitions.h.
References FindMapIndex(), GetTypeHash(), INDEX_NONE, InitialDefineCount, KeyHashTable, FShaderCompilerDefineNameCache::MapIndex, FShaderCompilerDefineNameCache::Name, None, Pairs, and ValueTypes.
GetIntegerValue() [1/2]
int32 FShaderCompilerDefinitions::GetIntegerValue (FName Name) const inline
Definition at line 40 of file ShaderCompilerDefinitions.h.
References TCString< TCHAR >::Atoi(), FindMapIndex(), GetTypeHash(), INDEX_NONE, Name, Pairs, String, StringValues, Unsigned, and ValueTypes.
GetIntegerValue() [2/2]
int32 FShaderCompilerDefinitions::GetIntegerValue (FShaderCompilerDefineNameCache & NameCache, int32 ResultIfNotFound) const inline
Definition at line 64 of file ShaderCompilerDefinitions.h.
References TCString< TCHAR >::Atoi(), FindMapIndex(), Float, GetTypeHash(), INDEX_NONE, InitialDefineCount, Integer, FShaderCompilerDefineNameCache::MapIndex, FShaderCompilerDefineNameCache::Name, Pairs, String, StringValues, Unsigned, and ValueTypes.
InitializeInitialDefines()
RENDERCORE_API void FShaderCompilerDefinitions::InitializeInitialDefines (const FShaderCompilerDefinitions & InDefines) static private
Called from FShaderInitialDefinesInitializer.
References FShaderCompilerDefinitions().
InternalSetValue() [1/5]
void FShaderCompilerDefinitions::InternalSetValue (int32 Index, bool Value) inline private
Definition at line 388 of file ShaderCompilerDefinitions.h.
References Integer, Pairs, SetValueType(), and Value.
InternalSetValue() [2/5]
void FShaderCompilerDefinitions::InternalSetValue (int32 Index, const TCHAR * Value) inline private
Definition at line 366 of file ShaderCompilerDefinitions.h.
References Integer, Pairs, SetValueType(), String, StringValues, Value, and ValueTypes.
Referenced by SetDefine(), SetDefine(), SetDefine(), SetDefine(), SetDefine(), and SetDefine().
InternalSetValue() [3/5]
void FShaderCompilerDefinitions::InternalSetValue (int32 Index, float Value) inline private
Definition at line 406 of file ShaderCompilerDefinitions.h.
References Float, Pairs, SetValueType(), and Value.
InternalSetValue() [4/5]
void FShaderCompilerDefinitions::InternalSetValue (int32 Index, int32 Value) inline private
Definition at line 394 of file ShaderCompilerDefinitions.h.
References Integer, Pairs, SetValueType(), and Value.
InternalSetValue() [5/5]
void FShaderCompilerDefinitions::InternalSetValue (int32 Index, uint32 Value) inline private
Definition at line 400 of file ShaderCompilerDefinitions.h.
References Pairs, SetValueType(), Unsigned, and Value.
Merge()
void FShaderCompilerDefinitions::Merge (const FShaderCompilerDefinitions & Other) inline
Definition at line 138 of file ShaderCompilerDefinitions.h.
References FShaderCompilerDefinitions(), Float, Integer, Other, SetDefine(), String, and Unsigned.
Num()
FORCEINLINE int32 FShaderCompilerDefinitions::Num () const inline
Definition at line 115 of file ShaderCompilerDefinitions.h.
References FORCEINLINE, and ValueCount.
operator=()
FShaderCompilerDefinitions & FShaderCompilerDefinitions::operator= (const FShaderCompilerDefinitions & Other) inline
Definition at line 161 of file ShaderCompilerDefinitions.h.
References FShaderCompilerDefinitions(), InitialDefineCount, KeyHashTable, Other, Pairs, StringValues, ValueCount, and ValueTypes.
SetDefine() [1/6]
void FShaderCompilerDefinitions::SetDefine (FName Name, const FString & Value) inline
Definition at line 33 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
SetDefine() [2/6]
void FShaderCompilerDefinitions::SetDefine (FName Name, const TCHAR * Value) inline
Definition at line 32 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
SetDefine() [3/6]
template<typename ValueType> void FShaderCompilerDefinitions::SetDefine (FName Name, ValueType Value) inline
Value types supported: bool, int32, uint32, float, const TCHAR*, FString&.
Definition at line 31 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
Referenced by Merge().
SetDefine() [4/6]
void FShaderCompilerDefinitions::SetDefine (FShaderCompilerDefineNameCache & Name, const FString & Value) inline
Definition at line 38 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
SetDefine() [5/6]
void FShaderCompilerDefinitions::SetDefine (FShaderCompilerDefineNameCache & Name, const TCHAR * Value) inline
Definition at line 37 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
SetDefine() [6/6]
template<typename ValueType> void FShaderCompilerDefinitions::SetDefine (FShaderCompilerDefineNameCache & Name, ValueType Value) inline
Definition at line 36 of file ShaderCompilerDefinitions.h.
References FindOrAddMapIndex(), InternalSetValue(), Name, and Value.
SetValueType()
FORCEINLINE void FShaderCompilerDefinitions::SetValueType (int32 Index, EShaderCompilerDefineVariant InValueType) inline private
Definition at line 412 of file ShaderCompilerDefinitions.h.
References FORCEINLINE, None, ValueCount, and ValueTypes.
Referenced by InternalSetValue(), InternalSetValue(), InternalSetValue(), InternalSetValue(), and InternalSetValue().
Friends And Related Symbol Documentation
FShaderInitialDefinesInitializer
friend struct FShaderInitialDefinesInitializer friend
Definition at line 474 of file ShaderCompilerDefinitions.h.
References FShaderInitialDefinesInitializer.
Referenced by FShaderInitialDefinesInitializer.
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCompilerDefinitions & Defs) friend
Definition at line 172 of file ShaderCompilerDefinitions.h.
References FShaderCompilerDefinitions(), Ar, FindOrAddMapIndex(), FShaderCompilerDefinitions::FPairType::Key, Pairs, StringValues, ValueCount, and ValueTypes.
Field Documentation
GInitialDefines
RENDERCORE_API FShaderCompilerDefinitions* FShaderCompilerDefinitions::GInitialDefines static private
Definition at line 472 of file ShaderCompilerDefinitions.h.
Referenced by Empty().
InitialDefineCount
uint32 FShaderCompilerDefinitions::InitialDefineCount private
Definition at line 469 of file ShaderCompilerDefinitions.h.
Referenced by Empty(), FindOrAddMapIndex(), GetIntegerValue(), and operator=().
KeyHashTable
FHashTable FShaderCompilerDefinitions::KeyHashTable private
Definition at line 465 of file ShaderCompilerDefinitions.h.
Referenced by Empty(), FindMapIndex(), FindOrAddMapIndex(), FindOrAddMapIndex(), and operator=().
Pairs
TArray<FPairType> FShaderCompilerDefinitions::Pairs private
Definition at line 466 of file ShaderCompilerDefinitions.h.
Referenced by Empty(), FindMapIndex(), FindOrAddMapIndex(), FindOrAddMapIndex(), GetIntegerValue(), GetIntegerValue(), InternalSetValue(), InternalSetValue(), InternalSetValue(), InternalSetValue(), InternalSetValue(), operator<<, and operator=().
StringValues
TArray<FString> FShaderCompilerDefinitions::StringValues private
Definition at line 468 of file ShaderCompilerDefinitions.h.
Referenced by Empty(), GetIntegerValue(), GetIntegerValue(), InternalSetValue(), operator<<, and operator=().
ValueCount
uint32 FShaderCompilerDefinitions::ValueCount private
Definition at line 470 of file ShaderCompilerDefinitions.h.
Referenced by Empty(), Num(), operator<<, operator=(), and SetValueType().
ValueTypes
TArray<EShaderCompilerDefineVariant> FShaderCompilerDefinitions::ValueTypes private
Definition at line 467 of file ShaderCompilerDefinitions.h.
Referenced by Contains(), Empty(), FindOrAddMapIndex(), FindOrAddMapIndex(), GetIntegerValue(), GetIntegerValue(), InternalSetValue(), operator<<, operator=(), and SetValueType().
The documentation for this class was generated from the following file:
ShaderCompilerDefinitions.h