Unreal Engine 5.6 C++ API: TFunctionRef< Ret(ParamTypes...)> Class Template Reference
TFunctionRef< Ret(ParamTypes...)> Class Template Reference final
TFunctionRef<FuncType>
#include "Function.h"
Public Types
using IntrusiveUnsetOptionalStateType = TFunctionRef
Public Member Functions
TFunctionRef (const TFunctionRef &)=default
TFunctionRef (FIntrusiveUnsetOptionalState)
template<typename FunctorType UE_REQUIRES>
TFunctionRef (FunctorType &&InFunc UE_LIFETIMEBOUND)
Constructor which binds a TFunctionRef to a callable object.
~TFunctionRef ()=default
TFunctionRef & operator= (const TFunctionRef &) const =delete
bool operator== (FIntrusiveUnsetOptionalState) const
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
using Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::FFunctionRefStoragePolicy, Ret(ParamTypes...)>
Detailed Description
template<typename Ret, typename... ParamTypes>
class TFunctionRef< Ret(ParamTypes...)>
TFunctionRef<FuncType>
A class which represents a reference to something callable. The important part here is reference - if you bind it to a lambda and the lambda goes out of scope, you will be left with an invalid reference.
FuncType represents a function type and so TFunctionRef should be defined as follows:
// A function taking a string and float and returning int32. Parameter names are optional. TFunctionRef<int32 (const FString& Name, float Scale)>
If you also want to take ownership of the callable thing, e.g. you want to return a lambda from a function, you should use TFunction. TFunctionRef does not concern itself with ownership because it's intended to be FAST.
TFunctionRef is most useful when you want to parameterize a function with some caller-defined code without making it a template.
Example:
// Something.h void DoSomethingWithConvertingStringsToInts(TFunctionRef<int32 (const FString& Str)> Convert);
// Something.cpp void DoSomethingWithConvertingStringsToInts(TFunctionRef<int32 (const FString& Str)> Convert) { for (const FString& Str : SomeBunchOfStrings) { int32 Int = Convert(Str); DoSomething(Int); } }
// SomewhereElse.cpp #include "Something.h"
void Func() { // First do something using string length DoSomethingWithConvertingStringsToInts([](const FString& Str) { return Str.Len(); });
// Then do something using string conversion DoSomethingWithConvertingStringsToInts([](const FString& Str) { int32 Result; TTypeFromString<int32>::FromString(Result, *Str); return Result; }); }
Definition at line 619 of file Function.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
template<typename Ret, typename... ParamTypes> using TFunctionRef< Ret(ParamTypes...)>::IntrusiveUnsetOptionalStateType = TFunctionRef
Definition at line 647 of file Function.h.
Super
template<typename Ret, typename... ParamTypes> using TFunctionRef< Ret(ParamTypes...)>::Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::FFunctionRefStoragePolicy, Ret(ParamTypes...)> private
Definition at line 621 of file Function.h.
Constructor & Destructor Documentation
TFunctionRef() [1/3]
template<typename Ret, typename... ParamTypes> template<typename FunctorType UE_REQUIRES> TFunctionRef< Ret(ParamTypes...)>::TFunctionRef (FunctorType &&InFunc UE_LIFETIMEBOUND) inline
Constructor which binds a TFunctionRef to a callable object.
Definition at line 634 of file Function.h.
References Forward(), and UE_LIFETIMEBOUND.
Referenced by TFunctionRef(), and operator=().
TFunctionRef() [2/3]
template<typename Ret, typename... ParamTypes> TFunctionRef< Ret(ParamTypes...)>::TFunctionRef (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 649 of file Function.h.
TFunctionRef() [3/3]
template<typename Ret, typename... ParamTypes> TFunctionRef< Ret(ParamTypes...)>::TFunctionRef (const TFunctionRef< Ret(ParamTypes...)> &) default
References TFunctionRef().
~TFunctionRef()
template<typename Ret, typename... ParamTypes> TFunctionRef< Ret(ParamTypes...)>::~TFunctionRef () default
Member Function Documentation
operator=()
template<typename Ret, typename... ParamTypes> TFunctionRef & TFunctionRef< Ret(ParamTypes...)>::operator= (const TFunctionRef< Ret(ParamTypes...)> &) const delete
References TFunctionRef().
operator==()
template<typename Ret, typename... ParamTypes> bool TFunctionRef< Ret(ParamTypes...)>::operator== (FIntrusiveUnsetOptionalState) const inline
Definition at line 652 of file Function.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename Ret, typename... ParamTypes> bool TFunctionRef< Ret(ParamTypes...)>::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 646 of file Function.h.
The documentation for this class was generated from the following file:
Function.h