Unreal Engine 5.6 C++ API: FPhysicsUserData_Chaos Class Reference
FPhysicsUserData_Chaos Class Reference
#include "PhysicsUserData_Chaos.h"
Public Member Functions
FPhysicsUserData_Chaos ()
FPhysicsUserData_Chaos (FBodyInstance *InPayload)
FPhysicsUserData_Chaos (FConstraintInstanceBase *InPayload)
FPhysicsUserData_Chaos (FPhysScene *InPayload)
FPhysicsUserData_Chaos (UPhysicalMaterial *InPayload)
template<>
FORCEINLINE FBodyInstance * Get (void *UserData)
template<>
FORCEINLINE UPhysicalMaterial * Get (void *UserData)
template<>
FORCEINLINE FPhysScene * Get (void *UserData)
template<>
FORCEINLINE FConstraintInstanceBase * Get (void *UserData)
Static Public Member Functions
template<class T>
static T * Get (void *UserData)
template<class T>
static void Set (void *UserData, T *InPayload)
Private Types
enum EType {
Invalid , BodyInstance , PhysicalMaterial , PhysScene ,
ConstraintInstanceBase
}
Static Private Member Functions
template<class T, EType TType>
static T * Get (void *UserData)
Private Attributes
void * Payload
EType Type
Detailed Description
Definition at line 13 of file PhysicsUserData_Chaos.h.
Member Enumeration Documentation
EType
enum FPhysicsUserData_Chaos::EType private
Enumerator
Invalid
BodyInstance
PhysicalMaterial
PhysScene
ConstraintInstanceBase
Definition at line 16 of file PhysicsUserData_Chaos.h.
Constructor & Destructor Documentation
FPhysicsUserData_Chaos() [1/5]
FPhysicsUserData_Chaos::FPhysicsUserData_Chaos () inline
Definition at line 29 of file PhysicsUserData_Chaos.h.
References Invalid, Payload, and Type.
Referenced by Get().
FPhysicsUserData_Chaos() [2/5]
FPhysicsUserData_Chaos::FPhysicsUserData_Chaos (FBodyInstance * InPayload) inline
Definition at line 30 of file PhysicsUserData_Chaos.h.
References BodyInstance, Payload, and Type.
FPhysicsUserData_Chaos() [3/5]
FPhysicsUserData_Chaos::FPhysicsUserData_Chaos (UPhysicalMaterial * InPayload) inline
Definition at line 31 of file PhysicsUserData_Chaos.h.
References Payload, PhysicalMaterial, and Type.
FPhysicsUserData_Chaos() [4/5]
FPhysicsUserData_Chaos::FPhysicsUserData_Chaos (FPhysScene * InPayload) inline
Definition at line 32 of file PhysicsUserData_Chaos.h.
References Payload, PhysScene, and Type.
FPhysicsUserData_Chaos() [5/5]
FPhysicsUserData_Chaos::FPhysicsUserData_Chaos (FConstraintInstanceBase * InPayload) inline
Definition at line 33 of file PhysicsUserData_Chaos.h.
References ConstraintInstanceBase, Payload, and Type.
Member Function Documentation
Get() [1/6]
template<class T> T * FPhysicsUserData_Chaos::Get (void * UserData) static
Referenced by Get().
Get() [2/6]
template<class T, EType TType> T * FPhysicsUserData_Chaos::Get (void * UserData) inline static private
Definition at line 52 of file PhysicsUserData_Chaos.h.
References FPhysicsUserData_Chaos(), Payload, and Type.
Get() [3/6]
template<> FORCEINLINE FBodyInstance * FPhysicsUserData_Chaos::Get (void * UserData)
Definition at line 59 of file PhysicsUserData_Chaos.h.
References FORCEINLINE, and Get().
Get() [4/6]
template<> FORCEINLINE UPhysicalMaterial * FPhysicsUserData_Chaos::Get (void * UserData)
Definition at line 64 of file PhysicsUserData_Chaos.h.
References FORCEINLINE, and Get().
Get() [5/6]
template<> FORCEINLINE FPhysScene * FPhysicsUserData_Chaos::Get (void * UserData)
Definition at line 69 of file PhysicsUserData_Chaos.h.
References FORCEINLINE, and Get().
Get() [6/6]
template<> FORCEINLINE FConstraintInstanceBase * FPhysicsUserData_Chaos::Get (void * UserData)
Definition at line 74 of file PhysicsUserData_Chaos.h.
References FORCEINLINE, and Get().
Set()
template<class T> void FPhysicsUserData_Chaos::Set (void * UserData, T * InPayload) static
Field Documentation
Payload
void* FPhysicsUserData_Chaos::Payload private
Definition at line 26 of file PhysicsUserData_Chaos.h.
Referenced by FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), and Get().
Type
EType FPhysicsUserData_Chaos::Type private
Definition at line 25 of file PhysicsUserData_Chaos.h.
Referenced by FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), FPhysicsUserData_Chaos(), and Get().
The documentation for this class was generated from the following file:
PhysicsUserData_Chaos.h