Unreal Engine 5.6 C++ API: UE::UnifiedError::FDynamicErrorDetails Class Reference
UE::UnifiedError::FDynamicErrorDetails Class Reference
FDynamicErrorDetails; base implementation of inner error details, for use by derived classes to reduce unnessisary reimplementation.
#include "UnifiedError.h"
Public Member Functions
FDynamicErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails=nullptr)
virtual ~FDynamicErrorDetails ()
virtual uint32 GetErrorDetailsTypeId () const
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
virtual const FAnsiStringView GetErrorDetailsTypeName () const override
virtual const FText GetErrorFormatString (const FError &Error) const override
GetErrorFormatString; Pass through to the InnerErrorDetails.
virtual void GetErrorProperties (const FError &Error, IErrorPropertyExtractor &OutProperties) const override
GetErrorProperties; by default pass through to the InnerErrorDetails.
virtual TRefCountPtr< const IErrorDetails > GetInnerErrorDetails () const
GetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
virtual void SetInnerErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails)
SetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
virtual ~FRefCountedErrorDetails ()
virtual FReturnedRefCountValue AddRef () const final
virtual uint32 GetRefCount () const final
virtual uint32 Release () const final
Public Member Functions inherited from UE::UnifiedError::IErrorDetails
virtual ~IErrorDetails ()=default
virtual void SerializeForLog (FCbWriter &Writer) const
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Static Public Member Functions
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Member Functions inherited from UE::UnifiedError::FRefCountedErrorDetails
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Attributes
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FDynamicErrorDetails"), nullptr)
Static Public Attributes inherited from UE::UnifiedError::FRefCountedErrorDetails
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FRefCountedErrorDetails"), nullptr)
Private Attributes
TRefCountPtr< const IErrorDetails > InnerErrorDetails
Detailed Description
FDynamicErrorDetails; base implementation of inner error details, for use by derived classes to reduce unnessisary reimplementation.
Definition at line 205 of file UnifiedError.h.
Constructor & Destructor Documentation
FDynamicErrorDetails()
UE::UnifiedError::FDynamicErrorDetails::FDynamicErrorDetails (TRefCountPtr< const IErrorDetails > InInnerErrorDetails = nullptr)
Referenced by UE::UnifiedError::TErrorDetails< T >::TErrorDetails(), and GetErrorDetailsTypeId().
~FDynamicErrorDetails()
virtual UE::UnifiedError::FDynamicErrorDetails::~FDynamicErrorDetails () virtual
Member Function Documentation
GetErrorDetailsTypeId()
virtual uint32 UE::UnifiedError::FDynamicErrorDetails::GetErrorDetailsTypeId () const inline virtual
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
Returns
Reimplemented from UE::UnifiedError::FRefCountedErrorDetails.
Reimplemented in UE::UnifiedError::TErrorDetails< T >.
Definition at line 207 of file UnifiedError.h.
References FDynamicErrorDetails().
GetErrorDetailsTypeName()
virtual const FAnsiStringView UE::UnifiedError::FDynamicErrorDetails::GetErrorDetailsTypeName () const inline override virtual
Reimplemented from UE::UnifiedError::FRefCountedErrorDetails.
Definition at line 207 of file UnifiedError.h.
GetErrorFormatString()
virtual const FText UE::UnifiedError::FDynamicErrorDetails::GetErrorFormatString (const FError & Error) const override virtual
GetErrorFormatString; Pass through to the InnerErrorDetails.
Parameters
Error
Returns
Implements UE::UnifiedError::IErrorDetails.
Reimplemented in UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails.
References UE::Error.
GetErrorProperties()
virtual void UE::UnifiedError::FDynamicErrorDetails::GetErrorProperties (const FError & Error, IErrorPropertyExtractor & OutProperties) const override virtual
GetErrorProperties; by default pass through to the InnerErrorDetails.
It's expected FDynamicErrorDetails will be derived from and implement GetErrorProperties.
Parameters
Error
OutProperties
Implements UE::UnifiedError::IErrorDetails.
Reimplemented in UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails, and UE::UnifiedError::TErrorDetails< T >.
References UE::Error.
Referenced by UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorProperties(), and UE::UnifiedError::TErrorDetails< T >::GetErrorProperties().
GetInnerErrorDetails()
virtual TRefCountPtr< const IErrorDetails > UE::UnifiedError::FDynamicErrorDetails::GetInnerErrorDetails () const inline virtual
GetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Returns
Reimplemented from UE::UnifiedError::IErrorDetails.
Definition at line 217 of file UnifiedError.h.
References InnerErrorDetails.
Referenced by UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorFormatString(), and UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorProperties().
SetInnerErrorDetails()
virtual void UE::UnifiedError::FDynamicErrorDetails::SetInnerErrorDetails (TRefCountPtr< const IErrorDetails > ErrorDetails) virtual
SetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Returns
Reimplemented from UE::UnifiedError::IErrorDetails.
StaticGetErrorDetailsTypeId()
uint32 UE::UnifiedError::FDynamicErrorDetails::StaticGetErrorDetailsTypeId () inline static
Definition at line 207 of file UnifiedError.h.
Field Documentation
InnerErrorDetails
TRefCountPtr<const IErrorDetails> UE::UnifiedError::FDynamicErrorDetails::InnerErrorDetails private
Definition at line 209 of file UnifiedError.h.
Referenced by GetInnerErrorDetails().
StaticDetailsTypeId
const uint32 UE::UnifiedError::FDynamicErrorDetails::StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FDynamicErrorDetails"), nullptr) inline static
Definition at line 207 of file UnifiedError.h.
The documentation for this class was generated from the following file:
UnifiedError.h