Unreal Engine 5.6 C++ API: FStaticMeshOperations Class Reference
FStaticMeshOperations Class Reference
#include "StaticMeshOperations.h"
Data Structures
struct FAppendSettings
struct FGenerateUVOptions
Public Types
enum class EGenerateUVMethod {
Default , Legacy , UVAtlas , XAtlas ,
PatchBuilder
}
Public Member Functions
UE_DEPRECATED (4.26, "Please use ComputeTriangleTangentsAndNormals() instead.") static STATICMESHDESCRIPTION_API void ComputePolygonTangentsAndNormals(FMeshDescription &MeshDescription
Set the polygon tangent, normal, binormal and polygonCenter for all polygons in the mesh description.
UE_DEPRECATED (5.4, "Please use GenerateUV() instead.") static STATICMESHDESCRIPTION_API bool GenerateUniqueUVsForStaticMesh(const FMeshDescription &MeshDescription
Create some UVs from the specified mesh description data.
UE_DEPRECATED (5.5, "Use HasInvalidVertexInstanceNormalsOrTangents") static void AreNormalsAndTangentsValid(const FMeshDescription &MeshDescription
Static Public Member Functions
static STATICMESHDESCRIPTION_API bool AddUVChannel (FMeshDescription &MeshDescription)
Add a UV channel to the MeshDescription.
static STATICMESHDESCRIPTION_API void AppendMeshDescription (const FMeshDescription &SourceMesh, FMeshDescription &TargetMesh, FAppendSettings &AppendSettings)
static STATICMESHDESCRIPTION_API void AppendMeshDescriptions (const TArray< const FMeshDescription * > &SourceMeshes, FMeshDescription &TargetMesh, FAppendSettings &AppendSettings)
static STATICMESHDESCRIPTION_API void ApplyTransform (FMeshDescription &MeshDescription, const FMatrix &Transform, bool bApplyCorrectNormalTransform=false)
static STATICMESHDESCRIPTION_API void ApplyTransform (FMeshDescription &MeshDescription, const FTransform &Transform, bool bApplyCorrectNormalTransform=false)
Transforms the MeshDescription data using the provided transform.
static STATICMESHDESCRIPTION_API void BuildWeldedVertexIDRemap (const FMeshDescription &MeshDescription, const float WeldingThreshold, TMap< FVertexID, FVertexID > &OutVertexIDRemap)
static STATICMESHDESCRIPTION_API void ComputeMikktTangents (FMeshDescription &MeshDescription, bool bIgnoreDegenerateTriangles)
Compute tangent and Bi-Normal using mikkt space for every vertex in the mesh description.
static STATICMESHDESCRIPTION_API FSHAHash ComputeSHAHash (const FMeshDescription &MeshDescription, bool bSkipTransientAttributes=false)
Computes the SHA hash of all the attributes values in the MeshDescription.
static STATICMESHDESCRIPTION_API void ComputeTangentsAndNormals (FMeshDescription &MeshDescription, EComputeNTBsFlags ComputeNTBsOptions)
Recompute any invalid normal, tangent or Bi-Normal for every vertex in the mesh description with the given options.
static STATICMESHDESCRIPTION_API void ComputeTriangleTangentsAndNormals (FMeshDescription &MeshDescription, float ComparisonThreshold=0.0f, const TCHAR *DebugName=nullptr)
Set the triangle tangent, normal, binormal and triangleCenter for all triangles in the mesh description.
static STATICMESHDESCRIPTION_API void ConvertFromRawMesh (const FRawMesh &SourceRawMesh, FMeshDescription &DestinationMeshDescription, const TMap< int32, FName > &MaterialMap, bool bSkipNormalsAndTangents=false, const TCHAR *DebugName=nullptr)
Convert old FRawMesh format to MeshDescription.
static STATICMESHDESCRIPTION_API void ConvertHardEdgesToSmoothGroup (const FMeshDescription &SourceMeshDescription, TArray< uint32 > &FaceSmoothingMasks)
static STATICMESHDESCRIPTION_API void ConvertSmoothGroupToHardEdges (const TArray< uint32 > &FaceSmoothingMasks, FMeshDescription &DestinationMeshDescription)
static STATICMESHDESCRIPTION_API void ConvertToRawMesh (const FMeshDescription &SourceMeshDescription, FRawMesh &DestinationRawMesh, const TMap< FName, int32 > &MaterialMap)
Convert this mesh description into the old FRawMesh format.
static STATICMESHDESCRIPTION_API bool CreateLightMapUVLayout (FMeshDescription &MeshDescription, int32 SrcLightmapIndex, int32 DstLightmapIndex, int32 MinLightmapResolution, ELightmapUVVersion LightmapUVVersion, const FOverlappingCorners &OverlappingCorners)
Find and pack UV charts for lightmap.
static STATICMESHDESCRIPTION_API void DetermineEdgeHardnessesFromVertexInstanceNormals (FMeshDescription &MeshDescription, float Tolerance=UE_KINDA_SMALL_NUMBER)
Determine the edge hardnesses from existing normals.
static STATICMESHDESCRIPTION_API void FindOverlappingCorners (FOverlappingCorners &OverlappingCorners, const FMeshDescription &MeshDescription, float ComparisonThreshold)
Find all overlapping vertex using the threshold in the mesh description.
static STATICMESHDESCRIPTION_API void FlipPolygons (FMeshDescription &MeshDescription)
Flip the facing for a set of input polygons.
static STATICMESHDESCRIPTION_API void GenerateBoxUV (const FMeshDescription &MeshDescription, const FUVMapParameters &Params, TMap< FVertexInstanceID, FVector2D > &OutTexCoords)
Generate box UV mapping for the MeshDescription.
static STATICMESHDESCRIPTION_API void GenerateCylindricalUV (FMeshDescription &MeshDescription, const FUVMapParameters &Params, TMap< FVertexInstanceID, FVector2D > &OutTexCoords)
Generate cylindrical UV mapping for the MeshDescription.
static STATICMESHDESCRIPTION_API void GeneratePlanarUV (const FMeshDescription &MeshDescription, const FUVMapParameters &Params, TMap< FVertexInstanceID, FVector2D > &OutTexCoords)
Generate planar UV mapping for the MeshDescription.
static STATICMESHDESCRIPTION_API bool GenerateUV (const FMeshDescription &MeshDescription, const FGenerateUVOptions &Options, TArray< FVector2D > &OutTexCoords)
Generate UV coordinates from the specified mesh description data.
static STATICMESHDESCRIPTION_API int32 GetUniqueVertexCount (const FMeshDescription &MeshDescription)
Return the number of unique vertices, unique vertices are the result of welding all similar vertex instances (position, UV, tangent space, color,...)
static STATICMESHDESCRIPTION_API int32 GetUniqueVertexCount (const FMeshDescription &MeshDescription, const FOverlappingCorners &OverlappingCorners)
static STATICMESHDESCRIPTION_API int32 GetUVChartCount (FMeshDescription &MeshDescription, int32 SrcLightmapIndex, ELightmapUVVersion LightmapUVVersion, const FOverlappingCorners &OverlappingCorners)
Find all charts in the mesh description.
static STATICMESHDESCRIPTION_API void HasInvalidVertexInstanceNormalsOrTangents (const FMeshDescription &MeshDescription, bool &bHasInvalidNormals, bool &bHasInvalidTangents)
Check the mesh description's vertex instance normals and tangents to see if any of the values are invalid (e.g.
static STATICMESHDESCRIPTION_API bool HasVertexColor (const FMeshDescription &MeshDescription)
static STATICMESHDESCRIPTION_API bool InsertUVChannel (FMeshDescription &MeshDescription, int32 UVChannelIndex)
Insert a UV channel at the given index to the MeshDescription.
static STATICMESHDESCRIPTION_API void RecomputeNormalsAndTangentsIfNeeded (FMeshDescription &MeshDescription, EComputeNTBsFlags ComputeNTBsOptions)
static STATICMESHDESCRIPTION_API bool RemoveUVChannel (FMeshDescription &MeshDescription, int32 UVChannelIndex)
Remove the UV channel at the given index from the MeshDescription.
static STATICMESHDESCRIPTION_API void ReorderMeshDescriptionPolygonGroups (const FMeshDescription &SourceMeshDescription, FMeshDescription &DestinationMeshDescription, TOptional< const FString > UnmatchMaterialNameWarning, TOptional< const FString > DestinationPolygonGroupCountDifferFromSource_Msg)
Reorder the destination mesh description polygon groups in the same order has the source mesh description polygon groups.
static STATICMESHDESCRIPTION_API void SwapPolygonPolygonGroup (FMeshDescription &MeshDescription, int32 SectionIndex, int32 TriangleIndexStart, int32 TriangleIndexEnd, bool bRemoveEmptyPolygonGroup)
static STATICMESHDESCRIPTION_API bool ValidateAndFixData (FMeshDescription &MeshDescription, const FString &DebugName)
Verify the mesh data does not contain any NAN or INF float value, if such a case happen the value are set to zero or identity for matrix or quat.
Data Fields
bool & bHasInvalidNormals
bool bool & bHasInvalidTangents
int32 bool bMergeIdenticalMaterials
float ComparisonThreshold = 0.0f)
int32 bool TArray< FVector2D > & OutTexCoords
int32 TextureResolution
Detailed Description
Definition at line 46 of file StaticMeshOperations.h.
Member Enumeration Documentation
EGenerateUVMethod
enum class FStaticMeshOperations::EGenerateUVMethod strong
Enumerator
Default
Legacy
UVAtlas
XAtlas
PatchBuilder
Definition at line 148 of file StaticMeshOperations.h.
Member Function Documentation
AddUVChannel()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::AddUVChannel (FMeshDescription & MeshDescription) static
Add a UV channel to the MeshDescription.
AppendMeshDescription()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::AppendMeshDescription (const FMeshDescription & SourceMesh, FMeshDescription & TargetMesh, FAppendSettings & AppendSettings) static
References AppendMeshDescription(), and TargetMesh.
Referenced by AppendMeshDescription().
AppendMeshDescriptions()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::AppendMeshDescriptions (const TArray< const FMeshDescription * > & SourceMeshes, FMeshDescription & TargetMesh, FAppendSettings & AppendSettings) static
References AppendMeshDescriptions(), and TargetMesh.
Referenced by AppendMeshDescriptions().
ApplyTransform() [1/2]
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ApplyTransform (FMeshDescription & MeshDescription, const FMatrix & Transform, bool bApplyCorrectNormalTransform = false) static
References Transform.
ApplyTransform() [2/2]
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ApplyTransform (FMeshDescription & MeshDescription, const FTransform & Transform, bool bApplyCorrectNormalTransform = false) static
Transforms the MeshDescription data using the provided transform.
Parameters
bApplyCorrectNormalTransform Whether to correctly transform normals and tangents. Otherwise, will match the UE renderer and transform them without scale.
References Transform.
BuildWeldedVertexIDRemap()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::BuildWeldedVertexIDRemap (const FMeshDescription & MeshDescription, const float WeldingThreshold, TMap< FVertexID, FVertexID > & OutVertexIDRemap) static
ComputeMikktTangents()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ComputeMikktTangents (FMeshDescription & MeshDescription, bool bIgnoreDegenerateTriangles) static
Compute tangent and Bi-Normal using mikkt space for every vertex in the mesh description.
References ComputeMikktTangents().
Referenced by ComputeMikktTangents().
ComputeSHAHash()
STATICMESHDESCRIPTION_API FSHAHash FStaticMeshOperations::ComputeSHAHash (const FMeshDescription & MeshDescription, bool bSkipTransientAttributes = false) static
Computes the SHA hash of all the attributes values in the MeshDescription.
Parameters
bSkipTransientAttributes If param is true, do not include transient attributes in the hash computation.
ComputeTangentsAndNormals()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ComputeTangentsAndNormals (FMeshDescription & MeshDescription, EComputeNTBsFlags ComputeNTBsOptions) static
Recompute any invalid normal, tangent or Bi-Normal for every vertex in the mesh description with the given options.
If the EComputeNTBsFlags Normals or Tangents are set, the corresponding data will be force-recomputed.
References ComputeTangentsAndNormals().
Referenced by ComputeTangentsAndNormals().
ComputeTriangleTangentsAndNormals()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ComputeTriangleTangentsAndNormals (FMeshDescription & MeshDescription, float ComparisonThreshold = 0.0f, const TCHAR * DebugName = nullptr) static
Set the triangle tangent, normal, binormal and triangleCenter for all triangles in the mesh description.
References ComparisonThreshold, and ComputeTriangleTangentsAndNormals().
Referenced by ComputeTriangleTangentsAndNormals().
ConvertFromRawMesh()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ConvertFromRawMesh (const FRawMesh & SourceRawMesh, FMeshDescription & DestinationMeshDescription, const TMap< int32, FName > & MaterialMap, bool bSkipNormalsAndTangents = false, const TCHAR * DebugName = nullptr) static
Convert old FRawMesh format to MeshDescription.
References ConvertFromRawMesh().
Referenced by ConvertFromRawMesh().
ConvertHardEdgesToSmoothGroup()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ConvertHardEdgesToSmoothGroup (const FMeshDescription & SourceMeshDescription, TArray< uint32 > & FaceSmoothingMasks) static
ConvertSmoothGroupToHardEdges()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ConvertSmoothGroupToHardEdges (const TArray< uint32 > & FaceSmoothingMasks, FMeshDescription & DestinationMeshDescription) static
ConvertToRawMesh()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ConvertToRawMesh (const FMeshDescription & SourceMeshDescription, FRawMesh & DestinationRawMesh, const TMap< FName, int32 > & MaterialMap) static
Convert this mesh description into the old FRawMesh format.
References ConvertToRawMesh().
Referenced by ConvertToRawMesh().
CreateLightMapUVLayout()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::CreateLightMapUVLayout (FMeshDescription & MeshDescription, int32 SrcLightmapIndex, int32 DstLightmapIndex, int32 MinLightmapResolution, ELightmapUVVersion LightmapUVVersion, const FOverlappingCorners & OverlappingCorners) static
Find and pack UV charts for lightmap.
The packing algorithm uses a rasterization method, hence the resolution parameter.
If the given minimum resolution is not enough to handle all the charts, generation will fail.
Parameters
MeshDescription Edited mesh
SrcLightmapIndex index of the source UV channel
DstLightmapIndex index of the destination UV channel
MinLightmapResolution Minimum resolution used for the packing
LightmapUVVersion Algorithm version
OverlappingCorners Overlapping corners of the given mesh
Returns
UV layout correctly generated
References LightmapUVVersion.
DetermineEdgeHardnessesFromVertexInstanceNormals()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::DetermineEdgeHardnessesFromVertexInstanceNormals (FMeshDescription & MeshDescription, float Tolerance = UE_KINDA_SMALL_NUMBER) static
Determine the edge hardnesses from existing normals.
References DetermineEdgeHardnessesFromVertexInstanceNormals(), and UE_KINDA_SMALL_NUMBER.
Referenced by DetermineEdgeHardnessesFromVertexInstanceNormals().
FindOverlappingCorners()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::FindOverlappingCorners (FOverlappingCorners & OverlappingCorners, const FMeshDescription & MeshDescription, float ComparisonThreshold) static
Find all overlapping vertex using the threshold in the mesh description.
References ComparisonThreshold.
FlipPolygons()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::FlipPolygons (FMeshDescription & MeshDescription) static
Flip the facing for a set of input polygons.
GenerateBoxUV()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::GenerateBoxUV (const FMeshDescription & MeshDescription, const FUVMapParameters & Params, TMap< FVertexInstanceID, FVector2D > & OutTexCoords) static
Generate box UV mapping for the MeshDescription.
References OutTexCoords, and Params.
GenerateCylindricalUV()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::GenerateCylindricalUV (FMeshDescription & MeshDescription, const FUVMapParameters & Params, TMap< FVertexInstanceID, FVector2D > & OutTexCoords) static
Generate cylindrical UV mapping for the MeshDescription.
References OutTexCoords, and Params.
GeneratePlanarUV()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::GeneratePlanarUV (const FMeshDescription & MeshDescription, const FUVMapParameters & Params, TMap< FVertexInstanceID, FVector2D > & OutTexCoords) static
Generate planar UV mapping for the MeshDescription.
References OutTexCoords, and Params.
GenerateUV()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::GenerateUV (const FMeshDescription & MeshDescription, const FGenerateUVOptions & Options, TArray< FVector2D > & OutTexCoords) static
Generate UV coordinates from the specified mesh description data.
References OutTexCoords.
GetUniqueVertexCount() [1/2]
STATICMESHDESCRIPTION_API int32 FStaticMeshOperations::GetUniqueVertexCount (const FMeshDescription & MeshDescription) static
Return the number of unique vertices, unique vertices are the result of welding all similar vertex instances (position, UV, tangent space, color,...)
GetUniqueVertexCount() [2/2]
STATICMESHDESCRIPTION_API int32 FStaticMeshOperations::GetUniqueVertexCount (const FMeshDescription & MeshDescription, const FOverlappingCorners & OverlappingCorners) static
GetUVChartCount()
STATICMESHDESCRIPTION_API int32 FStaticMeshOperations::GetUVChartCount (FMeshDescription & MeshDescription, int32 SrcLightmapIndex, ELightmapUVVersion LightmapUVVersion, const FOverlappingCorners & OverlappingCorners) static
Find all charts in the mesh description.
References LightmapUVVersion.
HasInvalidVertexInstanceNormalsOrTangents()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::HasInvalidVertexInstanceNormalsOrTangents (const FMeshDescription & MeshDescription, bool & bHasInvalidNormals, bool & bHasInvalidTangents) static
Check the mesh description's vertex instance normals and tangents to see if any of the values are invalid (e.g.
nearly zero or they contain a NaN).
Note
This does not check if the vectors are normalized (which they should for correct normals and tangents).
Parameters
MeshDescription The mesh description object to check.
bHasInvalidNormals The vertex instance normal attribute contains a near zero-length vector or a NaN component value.
bHasInvalidTangents The vertex instance tangent attribute contains a near zero-length vector or a NaN component value.
References bHasInvalidNormals, bHasInvalidTangents, and HasInvalidVertexInstanceNormalsOrTangents().
Referenced by HasInvalidVertexInstanceNormalsOrTangents().
HasVertexColor()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::HasVertexColor (const FMeshDescription & MeshDescription) static
InsertUVChannel()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::InsertUVChannel (FMeshDescription & MeshDescription, int32 UVChannelIndex) static
Insert a UV channel at the given index to the MeshDescription.
RecomputeNormalsAndTangentsIfNeeded()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::RecomputeNormalsAndTangentsIfNeeded (FMeshDescription & MeshDescription, EComputeNTBsFlags ComputeNTBsOptions) static
References RecomputeNormalsAndTangentsIfNeeded().
Referenced by RecomputeNormalsAndTangentsIfNeeded().
RemoveUVChannel()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::RemoveUVChannel (FMeshDescription & MeshDescription, int32 UVChannelIndex) static
Remove the UV channel at the given index from the MeshDescription.
ReorderMeshDescriptionPolygonGroups()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::ReorderMeshDescriptionPolygonGroups (const FMeshDescription & SourceMeshDescription, FMeshDescription & DestinationMeshDescription, TOptional< const FString > UnmatchMaterialNameWarning, TOptional< const FString > DestinationPolygonGroupCountDifferFromSource_Msg) static
Reorder the destination mesh description polygon groups in the same order has the source mesh description polygon groups.
This function use the imported material name to reorder the section.
Note: The material count MUST be the same for both the source and the destination. It will not reorder anything if the count is different.
SwapPolygonPolygonGroup()
STATICMESHDESCRIPTION_API void FStaticMeshOperations::SwapPolygonPolygonGroup (FMeshDescription & MeshDescription, int32 SectionIndex, int32 TriangleIndexStart, int32 TriangleIndexEnd, bool bRemoveEmptyPolygonGroup) static
UE_DEPRECATED() [1/3]
FStaticMeshOperations::UE_DEPRECATED (4. 26, "Please use ComputeTriangleTangentsAndNormals() instead.") &
Set the polygon tangent, normal, binormal and polygonCenter for all polygons in the mesh description.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FStaticMeshOperations::UE_DEPRECATED (5. 4, "Please use GenerateUV() instead.") const &
Create some UVs from the specified mesh description data.
UE_DEPRECATED() [3/3]
FStaticMeshOperations::UE_DEPRECATED (5. 5, "Use HasInvalidVertexInstanceNormalsOrTangents") const &
References UE_DEPRECATED().
ValidateAndFixData()
STATICMESHDESCRIPTION_API bool FStaticMeshOperations::ValidateAndFixData (FMeshDescription & MeshDescription, const FString & DebugName) static
Verify the mesh data does not contain any NAN or INF float value, if such a case happen the value are set to zero or identity for matrix or quat.
Field Documentation
bHasInvalidNormals
bool& FStaticMeshOperations::bHasInvalidNormals
Definition at line 111 of file StaticMeshOperations.h.
Referenced by HasInvalidVertexInstanceNormalsOrTangents().
bHasInvalidTangents
bool bool& FStaticMeshOperations::bHasInvalidTangents
Initial value:
{
        HasInvalidVertexInstanceNormalsOrTangents(MeshDescription, bHasInvalidNormals, bHasInvalidTangents)
Definition at line 111 of file StaticMeshOperations.h.
Referenced by HasInvalidVertexInstanceNormalsOrTangents().
bMergeIdenticalMaterials
int32 bool FStaticMeshOperations::bMergeIdenticalMaterials
Definition at line 146 of file StaticMeshOperations.h.
ComparisonThreshold
float FStaticMeshOperations::ComparisonThreshold = 0.0f)
Definition at line 71 of file StaticMeshOperations.h.
Referenced by ComputeTriangleTangentsAndNormals(), and FindOverlappingCorners().
OutTexCoords
int32 bool TArray<FVector2D>& FStaticMeshOperations::OutTexCoords
Definition at line 146 of file StaticMeshOperations.h.
Referenced by GenerateBoxUV(), GenerateCylindricalUV(), GeneratePlanarUV(), and GenerateUV().
TextureResolution
int32 FStaticMeshOperations::TextureResolution
Definition at line 146 of file StaticMeshOperations.h.
The documentation for this class was generated from the following file:
StaticMeshOperations.h