Unreal Engine 5.6 C++ API: TVariant< T, Ts > Class Template Reference
TVariant< T, Ts > Class Template Reference final
A type-safe union based loosely on std::variant.
#include "TVariant.h"
Public Member Functions
TVariant ()
Default initialize the TVariant to the first type in the parameter pack.
TVariant (const TVariant &Other)
Copy construct the variant from another variant of the same type.
template<typename U, typename... ArgTypes UE_REQUIRES>
TVariant (TInPlaceType< U > &&, ArgTypes &&... Args)
Perform in-place construction of a type into the variant.
TVariant (TVariant &&Other)
Move construct the variant from another variant of the same type.
~TVariant ()=default
template<typename U, typename... ArgTypes UE_REQUIRES>
void Emplace (ArgTypes &&... Args)
Set a specifically-typed value into the variant using in-place construction.
template<typename U>
const U & Get () const UE_LIFETIMEBOUND
Get a reference to the held value.
template<typename U>
U & Get () UE_LIFETIMEBOUND
Get a reference to the held value.
template<typename U>
const U & Get (const TIdentity_T< U > &DefaultValue UE_LIFETIMEBOUND) const UE_LIFETIMEBOUND
Get a reference to the held value if set, otherwise the DefaultValue.
SIZE_T GetIndex () const
Returns the currently held type's index into the template parameter pack.
template<typename U>
bool IsType () const
Determine if the variant holds the specific type.
TVariant & operator= (const TVariant &Other)
Copy assign a variant from another variant of the same type.
TVariant & operator= (TVariant &&Other)
Move assign a variant from another variant of the same type.
template<typename U>
void Set (const typename TIdentity< U >::Type &Value)
Set a specifically-typed value into the variant.
template<typename U>
void Set (typename TIdentity< U >::Type &&Value)
Set a specifically-typed value into the variant.
template<typename U>
const U * TryGet () const UE_LIFETIMEBOUND
Get a pointer to the held value if the held type is the same as the one specified.
template<typename U>
U * TryGet () UE_LIFETIMEBOUND
Get a pointer to the held value if the held type is the same as the one specified.
Static Public Member Functions
template<typename U>
static constexpr SIZE_T IndexOfType ()
Lookup the index of a type in the template parameter pack at compile time.
Private Types
using Super = std::conditional_t<!std::is_trivially_destructible_v<T> || (!std::is_trivially_destructible_v<Ts> || ...), UE::Core::Private::TDestructibleVariantStorage<T, Ts...> , UE::Core::Private::TVariantStorage<T, Ts...>>
Detailed Description
template<typename T, typename... Ts>
class TVariant< T, Ts >
A type-safe union based loosely on std::variant.
This flavor of variant requires that all the types in the declaring template parameter pack be unique. Attempting to use the value of a Get() when the underlying type is different leads to undefined behavior.
Definition at line 32 of file TVariant.h.
Member Typedef Documentation
Super
template<typename T, typename... Ts> using TVariant< T, Ts >::Super = std::conditional_t<!std::is_trivially_destructible_v<T> || (!std::is_trivially_destructible_v<Ts> || ...), UE::Core::Private::TDestructibleVariantStorage<T, Ts...> , UE::Core::Private::TVariantStorage<T, Ts...>> private
Definition at line 42 of file TVariant.h.
Constructor & Destructor Documentation
TVariant() [1/4]
template<typename T, typename... Ts> TVariant< T, Ts >::TVariant () inline nodiscard
Default initialize the TVariant to the first type in the parameter pack.
Definition at line 53 of file TVariant.h.
TVariant() [2/4]
template<typename T, typename... Ts> template<typename U, typename... ArgTypes UE_REQUIRES> TVariant< T, Ts >::TVariant (TInPlaceType< U > && , ArgTypes &&... Args) inline explicit nodiscard
Perform in-place construction of a type into the variant.
Definition at line 66 of file TVariant.h.
TVariant() [3/4]
template<typename T, typename... Ts> TVariant< T, Ts >::TVariant (const TVariant< T, Ts > & Other) inline nodiscard
Copy construct the variant from another variant of the same type.
Definition at line 76 of file TVariant.h.
TVariant() [4/4]
template<typename T, typename... Ts> TVariant< T, Ts >::TVariant (TVariant< T, Ts > && Other) inline nodiscard
Move construct the variant from another variant of the same type.
Definition at line 83 of file TVariant.h.
~TVariant()
template<typename T, typename... Ts> TVariant< T, Ts >::~TVariant () default
Member Function Documentation
Emplace()
template<typename T, typename... Ts> template<typename U, typename... ArgTypes UE_REQUIRES> void TVariant< T, Ts >::Emplace (ArgTypes &&... Args) inline
Set a specifically-typed value into the variant using in-place construction.
Definition at line 201 of file TVariant.h.
Referenced by TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Set(), and TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Set().
Get() [1/3]
template<typename T, typename... Ts> template<typename U> const U & TVariant< T, Ts >::Get () const inline nodiscard
Get a reference to the held value.
Bad things can happen if this is called on a variant that does not hold the type asked for
Definition at line 149 of file TVariant.h.
Get() [2/3]
template<typename T, typename... Ts> template<typename U> U & TVariant< T, Ts >::Get () inline nodiscard
Get a reference to the held value.
Bad things can happen if this is called on a variant that does not hold the type asked for
Definition at line 136 of file TVariant.h.
Referenced by Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Get(), FShaderCompilerEnvironment::GetCompileArgument(), FShaderCompilerEnvironment::GetCompileArgument(), UE::Insights::FFilterContext::GetFilterData(), and UE::Net::GetTypeHash().
Get() [3/3]
template<typename T, typename... Ts> template<typename U> const U & TVariant< T, Ts >::Get (const TIdentity_T< U > &DefaultValue UE_LIFETIMEBOUND) const inline
Get a reference to the held value if set, otherwise the DefaultValue.
Definition at line 157 of file TVariant.h.
GetIndex()
template<typename T, typename... Ts> SIZE_T TVariant< T, Ts >::GetIndex () const inline nodiscard
Returns the currently held type's index into the template parameter pack.
Definition at line 221 of file TVariant.h.
Referenced by UE::MovieScene::TPropertyValueStorage< PropertyTraits >::FKeyType::GetTypeHash, and operator<<().
IndexOfType()
template<typename T, typename... Ts> template<typename U> constexpr SIZE_T TVariant< T, Ts >::IndexOfType () inline static nodiscard constexpr
Lookup the index of a type in the template parameter pack at compile time.
Definition at line 213 of file TVariant.h.
IsType()
template<typename T, typename... Ts> template<typename U> bool TVariant< T, Ts >::IsType () const inline nodiscard
Determine if the variant holds the specific type.
Definition at line 128 of file TVariant.h.
Referenced by TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Get(), FShaderCompilerEnvironment::GetCompileArgument(), FShaderCompilerEnvironment::GetCompileArgument(), UE::Insights::FFilterContext::GetFilterData(), and UE::Net::GetTypeHash().
operator=() [1/2]
template<typename T, typename... Ts> TVariant & TVariant< T, Ts >::operator= (const TVariant< T, Ts > & Other) inline
Copy assign a variant from another variant of the same type.
Definition at line 90 of file TVariant.h.
operator=() [2/2]
template<typename T, typename... Ts> TVariant & TVariant< T, Ts >::operator= (TVariant< T, Ts > && Other) inline
Move assign a variant from another variant of the same type.
Definition at line 101 of file TVariant.h.
Set() [1/2]
template<typename T, typename... Ts> template<typename U> void TVariant< T, Ts >::Set (const typename TIdentity< U >::Type & Value) inline
Set a specifically-typed value into the variant.
Definition at line 190 of file TVariant.h.
Set() [2/2]
template<typename T, typename... Ts> template<typename U> void TVariant< T, Ts >::Set (typename TIdentity< U >::Type && Value) inline
Set a specifically-typed value into the variant.
Definition at line 183 of file TVariant.h.
Referenced by UE::Insights::FFilterContext::AddFilterData().
TryGet() [1/2]
template<typename T, typename... Ts> template<typename U> const U * TVariant< T, Ts >::TryGet () const inline nodiscard
Get a pointer to the held value if the held type is the same as the one specified.
Definition at line 175 of file TVariant.h.
TryGet() [2/2]
template<typename T, typename... Ts> template<typename U> U * TVariant< T, Ts >::TryGet () inline nodiscard
Get a pointer to the held value if the held type is the same as the one specified.
Definition at line 164 of file TVariant.h.
The documentation for this class was generated from the following file:
TVariant.h