Unreal Engine 5.6 C++ API: FMeshElementContainer::FElementIDs::FConstIterator Class Reference
FMeshElementContainer::FElementIDs::FConstIterator Class Reference
#include "MeshElementContainer.h"
Public Member Functions
FORCEINLINE FConstIterator (TConstSetBitIterator<> &&It)
FORCEINLINE int32 operator* () const
FORCEINLINE FConstIterator & operator++ ()
Private Attributes
TConstSetBitIterator Iterator
Friends
FORCEINLINE bool operator!= (const FConstIterator &Lhs, const FConstIterator &Rhs)
FORCEINLINE bool operator== (const FConstIterator &Lhs, const FConstIterator &Rhs)
Detailed Description
Definition at line 174 of file MeshElementContainer.h.
Constructor & Destructor Documentation
FConstIterator()
FORCEINLINE FMeshElementContainer::FElementIDs::FConstIterator::FConstIterator (TConstSetBitIterator<> && It) inline explicit
Definition at line 177 of file MeshElementContainer.h.
References FORCEINLINE, Iterator, and MoveTemp().
Referenced by operator!=, operator++(), and operator==.
Member Function Documentation
operator*()
FORCEINLINE int32 FMeshElementContainer::FElementIDs::FConstIterator::operator* () const inline
Definition at line 187 of file MeshElementContainer.h.
References FORCEINLINE, INDEX_NONE, and Iterator.
operator++()
FORCEINLINE FConstIterator & FMeshElementContainer::FElementIDs::FConstIterator::operator++ () inline
Definition at line 181 of file MeshElementContainer.h.
References FConstIterator(), FORCEINLINE, and Iterator.
Friends And Related Symbol Documentation
operator!=
FORCEINLINE bool operator!= (const FConstIterator & Lhs, const FConstIterator & Rhs) friend
Definition at line 197 of file MeshElementContainer.h.
References FConstIterator(), FORCEINLINE, and Iterator.
operator==
FORCEINLINE bool operator== (const FConstIterator & Lhs, const FConstIterator & Rhs) friend
Definition at line 192 of file MeshElementContainer.h.
References FConstIterator(), FORCEINLINE, and Iterator.
Field Documentation
Iterator
TConstSetBitIterator FMeshElementContainer::FElementIDs::FConstIterator::Iterator private
Definition at line 203 of file MeshElementContainer.h.
Referenced by FConstIterator(), operator!=, operator*(), operator++(), and operator==.
The documentation for this class was generated from the following file:
MeshElementContainer.h