Unreal Engine 5.6 C++ API: UE::TDynamicSharedLock< FSharedRecursiveMutex > Class Reference
UE::TDynamicSharedLock< FSharedRecursiveMutex > Class Reference final
#include "SharedRecursiveMutex.h"
Public Member Functions
TDynamicSharedLock ()=default
TDynamicSharedLock (const TDynamicSharedLock &)=delete
TDynamicSharedLock (FSharedRecursiveMutex &Lock)
TDynamicSharedLock (FSharedRecursiveMutex &Lock, FDeferLock)
TDynamicSharedLock (TDynamicSharedLock &&Other)
~TDynamicSharedLock ()
void Lock ()
operator bool () const
TDynamicSharedLock & operator= (const TDynamicSharedLock &)=delete
TDynamicSharedLock & operator= (TDynamicSharedLock &&Other)
bool OwnsLock () const
bool TryLock ()
void Unlock ()
Private Attributes
bool bLocked = false
Core::Private::FSharedRecursiveMutexLink Link
FSharedRecursiveMutex * Mutex = nullptr
Detailed Description
Definition at line 99 of file SharedRecursiveMutex.h.
Constructor & Destructor Documentation
TDynamicSharedLock() [1/5]
UE::TDynamicSharedLock< FSharedRecursiveMutex >::TDynamicSharedLock () default
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), operator=(), and operator=().
TDynamicSharedLock() [2/5]
UE::TDynamicSharedLock< FSharedRecursiveMutex >::TDynamicSharedLock (const TDynamicSharedLock< FSharedRecursiveMutex > &) delete
References TDynamicSharedLock().
TDynamicSharedLock() [3/5]
UE::TDynamicSharedLock< FSharedRecursiveMutex >::TDynamicSharedLock (FSharedRecursiveMutex & Lock) inline explicit nodiscard
Definition at line 107 of file SharedRecursiveMutex.h.
References bLocked, Link, Lock(), and Mutex.
TDynamicSharedLock() [4/5]
UE::TDynamicSharedLock< FSharedRecursiveMutex >::TDynamicSharedLock (FSharedRecursiveMutex & Lock, FDeferLock) inline explicit nodiscard
Definition at line 114 of file SharedRecursiveMutex.h.
References Lock(), and Mutex.
TDynamicSharedLock() [5/5]
UE::TDynamicSharedLock< FSharedRecursiveMutex >::TDynamicSharedLock (TDynamicSharedLock< FSharedRecursiveMutex > && Other) inline nodiscard
Definition at line 119 of file SharedRecursiveMutex.h.
References TDynamicSharedLock(), bLocked, Link, Mutex, and Other.
~TDynamicSharedLock()
UE::TDynamicSharedLock< FSharedRecursiveMutex >::~TDynamicSharedLock () inline
Definition at line 150 of file SharedRecursiveMutex.h.
References bLocked, Link, and Mutex.
Member Function Documentation
Lock()
void UE::TDynamicSharedLock< FSharedRecursiveMutex >::Lock () inline
Definition at line 166 of file SharedRecursiveMutex.h.
References bLocked, check, Link, and Mutex.
Referenced by TDynamicSharedLock(), and TDynamicSharedLock().
operator bool()
UE::TDynamicSharedLock< FSharedRecursiveMutex >::operator bool () const inline explicit
Definition at line 186 of file SharedRecursiveMutex.h.
References UE::TDynamicSharedLock< LockType >::OwnsLock().
operator=() [1/2]
TDynamicSharedLock & UE::TDynamicSharedLock< FSharedRecursiveMutex >::operator= (const TDynamicSharedLock< FSharedRecursiveMutex > &) delete
References TDynamicSharedLock().
operator=() [2/2]
TDynamicSharedLock & UE::TDynamicSharedLock< FSharedRecursiveMutex >::operator= (TDynamicSharedLock< FSharedRecursiveMutex > && Other) inline
Definition at line 132 of file SharedRecursiveMutex.h.
References TDynamicSharedLock(), bLocked, Link, Mutex, and Other.
OwnsLock()
bool UE::TDynamicSharedLock< FSharedRecursiveMutex >::OwnsLock () const inline
Definition at line 181 of file SharedRecursiveMutex.h.
References bLocked.
TryLock()
bool UE::TDynamicSharedLock< FSharedRecursiveMutex >::TryLock () inline
Definition at line 158 of file SharedRecursiveMutex.h.
References bLocked, check, Link, and Mutex.
Unlock()
void UE::TDynamicSharedLock< FSharedRecursiveMutex >::Unlock () inline
Definition at line 174 of file SharedRecursiveMutex.h.
References bLocked, check, Link, and Mutex.
Field Documentation
bLocked
bool UE::TDynamicSharedLock< FSharedRecursiveMutex >::bLocked = false private
Definition at line 194 of file SharedRecursiveMutex.h.
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), ~TDynamicSharedLock(), Lock(), operator=(), OwnsLock(), TryLock(), and Unlock().
Link
Core::Private::FSharedRecursiveMutexLink UE::TDynamicSharedLock< FSharedRecursiveMutex >::Link private
Definition at line 193 of file SharedRecursiveMutex.h.
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), ~TDynamicSharedLock(), Lock(), operator=(), TryLock(), and Unlock().
Mutex
FSharedRecursiveMutex* UE::TDynamicSharedLock< FSharedRecursiveMutex >::Mutex = nullptr private
Definition at line 192 of file SharedRecursiveMutex.h.
Referenced by TDynamicSharedLock(), TDynamicSharedLock(), TDynamicSharedLock(), ~TDynamicSharedLock(), Lock(), operator=(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
SharedRecursiveMutex.h