Unreal Engine 5.6 C++ API: FGraphTraversalCounter Struct Reference
FGraphTraversalCounter Struct Reference
#include "AnimTypes.h"
Public Member Functions
FGraphTraversalCounter ()
int16 Get () const
int16 GetMaxSkippedFrames () const
Gets the number of expected frames to be skipped by URO.
bool HasEverBeenUpdated () const
void Increment ()
Increases the internal counter, and refreshes the current global frame counter.
bool IsSynchronized_All (const FGraphTraversalCounter &InOtherCounter) const
Check that both the internal counter and global frame are both in sync between this counter and another.
bool IsSynchronized_Counter (const FGraphTraversalCounter &InOtherCounter) const
Check whether the internal counter is synchronized between this and another counter.
bool IsSynchronized_Frame (const FGraphTraversalCounter &InOtherCounter) const
Check whether this counter and another were synchronized on the same global frame.
void Reset ()
Clear the internal counters and frame skip.
void SetMaxSkippedFrames (int16 InMaxSkippedFrames)
Sets the number of expected frames to be skipped by URO.
void SynchronizeWith (const FGraphTraversalCounter &InMasterCounter)
Sync this counter with another counter.
UE_DEPRECATED (4.19, "Use the specific IsSynchronized_* functions to determing sync state") bool IsSynchronizedWith(const FGraphTraversalCounter &InMasterCounter) const
UE_DEPRECATED (4.19, "Use the specific WasSynchronizedLast* functions to determine sync state") bool WasSynchronizedInTheLastFrame(const FGraphTraversalCounter &InMasterCounter) const
bool WasSynchronizedCounter (const FGraphTraversalCounter &InOtherCounter) const
Check if this counter is either synchronized with another or is one update behind.
bool WasSynchronizedLastFrame (const FGraphTraversalCounter &InOtherCounter) const
Check whether this counter and another were either synchronized this global frame or were synced one frame interval previously.
Private Attributes
int16 Counter
uint64 LastSyncronizedFrame
int16 SkipFrames
Detailed Description
Definition at line 143 of file AnimTypes.h.
Constructor & Destructor Documentation
FGraphTraversalCounter()
FGraphTraversalCounter::FGraphTraversalCounter () inline
Definition at line 157 of file AnimTypes.h.
References Counter, INDEX_NONE, LastSyncronizedFrame, and SkipFrames.
Referenced by IsSynchronized_All(), IsSynchronized_Counter(), IsSynchronized_Frame(), SynchronizeWith(), UE_DEPRECATED(), UE_DEPRECATED(), WasSynchronizedCounter(), and WasSynchronizedLastFrame().
Member Function Documentation
Get()
int16 FGraphTraversalCounter::Get () const inline
Definition at line 164 of file AnimTypes.h.
References Counter.
GetMaxSkippedFrames()
int16 FGraphTraversalCounter::GetMaxSkippedFrames () const inline
Gets the number of expected frames to be skipped by URO.
Definition at line 194 of file AnimTypes.h.
References SkipFrames.
HasEverBeenUpdated()
bool FGraphTraversalCounter::HasEverBeenUpdated () const inline
Definition at line 169 of file AnimTypes.h.
References Counter, INDEX_NONE, and LastSyncronizedFrame.
Referenced by IsSynchronized_All(), IsSynchronized_Counter(), and IsSynchronized_Frame().
Increment()
void FGraphTraversalCounter::Increment () inline
Increases the internal counter, and refreshes the current global frame counter.
Definition at line 175 of file AnimTypes.h.
References Counter, GFrameCounter, INDEX_NONE, and LastSyncronizedFrame.
Referenced by WasSynchronizedCounter().
IsSynchronized_All()
bool FGraphTraversalCounter::IsSynchronized_All (const FGraphTraversalCounter & InOtherCounter) const inline
Check that both the internal counter and global frame are both in sync between this counter and another.
Definition at line 240 of file AnimTypes.h.
References FGraphTraversalCounter(), Counter, HasEverBeenUpdated(), and LastSyncronizedFrame.
IsSynchronized_Counter()
bool FGraphTraversalCounter::IsSynchronized_Counter (const FGraphTraversalCounter & InOtherCounter) const inline
Check whether the internal counter is synchronized between this and another counter.
Definition at line 228 of file AnimTypes.h.
References FGraphTraversalCounter(), Counter, and HasEverBeenUpdated().
Referenced by UE_DEPRECATED(), and WasSynchronizedCounter().
IsSynchronized_Frame()
bool FGraphTraversalCounter::IsSynchronized_Frame (const FGraphTraversalCounter & InOtherCounter) const inline
Check whether this counter and another were synchronized on the same global frame.
Definition at line 234 of file AnimTypes.h.
References FGraphTraversalCounter(), HasEverBeenUpdated(), and LastSyncronizedFrame.
Referenced by WasSynchronizedLastFrame().
Reset()
void FGraphTraversalCounter::Reset () inline
Clear the internal counters and frame skip.
Definition at line 200 of file AnimTypes.h.
References Counter, INDEX_NONE, LastSyncronizedFrame, and SkipFrames.
Referenced by USTRUCT().
SetMaxSkippedFrames()
void FGraphTraversalCounter::SetMaxSkippedFrames (int16 InMaxSkippedFrames) inline
Sets the number of expected frames to be skipped by URO.
Definition at line 188 of file AnimTypes.h.
References SkipFrames.
SynchronizeWith()
void FGraphTraversalCounter::SynchronizeWith (const FGraphTraversalCounter & InMasterCounter) inline
Sync this counter with another counter.
Definition at line 208 of file AnimTypes.h.
References FGraphTraversalCounter(), Counter, LastSyncronizedFrame, and SkipFrames.
UE_DEPRECATED() [1/2]
FGraphTraversalCounter::UE_DEPRECATED (4. 19, "Use the specific IsSynchronized_* functions to determing sync state") const & inline
Definition at line 215 of file AnimTypes.h.
References FGraphTraversalCounter(), bool, and IsSynchronized_Counter().
UE_DEPRECATED() [2/2]
FGraphTraversalCounter::UE_DEPRECATED (4. 19, "Use the specific WasSynchronizedLast* functions to determine sync state") const & inline
Definition at line 221 of file AnimTypes.h.
References FGraphTraversalCounter(), bool, and WasSynchronizedCounter().
WasSynchronizedCounter()
bool FGraphTraversalCounter::WasSynchronizedCounter (const FGraphTraversalCounter & InOtherCounter) const inline
Check if this counter is either synchronized with another or is one update behind.
Definition at line 246 of file AnimTypes.h.
References FGraphTraversalCounter(), Increment(), and IsSynchronized_Counter().
Referenced by UE_DEPRECATED().
WasSynchronizedLastFrame()
bool FGraphTraversalCounter::WasSynchronizedLastFrame (const FGraphTraversalCounter & InOtherCounter) const inline
Check whether this counter and another were either synchronized this global frame or were synced one frame interval previously.
A frame interval is the size of SkipFrames. This means that if under URO a number of frames are skipped, this check will consider counters from the last frame before the skip and the first frame after the skip as "was synchronized"
Use this to test whether or not there's been a period when the owning animation instance has not been updated.
Definition at line 270 of file AnimTypes.h.
References FGraphTraversalCounter(), GFrameCounter, IsSynchronized_Frame(), LastSyncronizedFrame, and SkipFrames.
Field Documentation
Counter
int16 FGraphTraversalCounter::Counter private
Definition at line 150 of file AnimTypes.h.
Referenced by FGraphTraversalCounter(), Get(), HasEverBeenUpdated(), Increment(), IsSynchronized_All(), IsSynchronized_Counter(), Reset(), and SynchronizeWith().
LastSyncronizedFrame
uint64 FGraphTraversalCounter::LastSyncronizedFrame private
Definition at line 147 of file AnimTypes.h.
Referenced by FGraphTraversalCounter(), HasEverBeenUpdated(), Increment(), IsSynchronized_All(), IsSynchronized_Frame(), Reset(), SynchronizeWith(), and WasSynchronizedLastFrame().
SkipFrames
int16 FGraphTraversalCounter::SkipFrames private
Definition at line 153 of file AnimTypes.h.
Referenced by FGraphTraversalCounter(), GetMaxSkippedFrames(), Reset(), SetMaxSkippedFrames(), SynchronizeWith(), and WasSynchronizedLastFrame().
The documentation for this struct was generated from the following file:
AnimTypes.h