Unreal Engine 5.6 C++ API: FAndroidTLS Struct Reference
FAndroidTLS Struct Reference
Android implementation of the TLS OS functions.
#include "AndroidPlatformTLS.h"
Static Public Member Functions
static FORCEINLINE uint32 AllocTlsSlot (void)
Allocates a thread local store slot.
static FORCEINLINE void FreeTlsSlot (uint32 SlotIndex)
Frees a previously allocated TLS slot.
static FORCEINLINE uint32 GetCurrentThreadId (void)
Returns the currently executing thread's id.
static FORCEINLINE void * GetTlsValue (uint32 SlotIndex)
Reads the value stored at the specified TLS slot.
static FORCEINLINE void SetTlsValue (uint32 SlotIndex, void *Value)
Sets a value in the specified TLS slot.
Static Public Member Functions inherited from FGenericPlatformTLS
static FORCEINLINE bool IsValidTlsSlot (uint32 SlotIndex)
Return false if this is an invalid TLS slot.
Additional Inherited Members
Static Public Attributes inherited from FGenericPlatformTLS
static const uint32 InvalidTlsSlot = 0xFFFFFFFF
Detailed Description
Android implementation of the TLS OS functions.
Definition at line 15 of file AndroidPlatformTLS.h.
Member Function Documentation
AllocTlsSlot()
FORCEINLINE uint32 FAndroidTLS::AllocTlsSlot (void) inline static
Allocates a thread local store slot.
Definition at line 30 of file AndroidPlatformTLS.h.
References FORCEINLINE, FGenericPlatformTLS::InvalidTlsSlot, and Key.
Referenced by FHazardPointerCollection::FHazardPointerCollection(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::TLockFreeFixedSizeAllocator_TLSCacheBase(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::SetupTLSCachesOnCurrentThread().
FreeTlsSlot()
FORCEINLINE void FAndroidTLS::FreeTlsSlot (uint32 SlotIndex) inline static
Frees a previously allocated TLS slot.
Parameters
SlotIndex the TLS index to store it in
Definition at line 67 of file AndroidPlatformTLS.h.
References FORCEINLINE.
Referenced by TTypeContainer< Mode >::FThreadInstanceProvider::~FThreadInstanceProvider(), and TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::~TLockFreeFixedSizeAllocator_TLSCacheBase().
GetCurrentThreadId()
FORCEINLINE uint32 FAndroidTLS::GetCurrentThreadId (void) inline static
Returns the currently executing thread's id.
Definition at line 20 of file AndroidPlatformTLS.h.
References FORCEINLINE.
Referenced by TStripedMapBase< BucketCount, BaseMapType, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FDebuggableExclusiveLock::FDebuggableExclusiveLock(), UE::Tasks::Private::FTaskBase::IsAwaitable(), FLinkerLoad::Serialize(), and UE::Tasks::Private::FTaskBase::TryExecuteTask().
GetTlsValue()
FORCEINLINE void * FAndroidTLS::GetTlsValue (uint32 SlotIndex) inline static
Reads the value stored at the specified TLS slot.
Returns
the value stored in the slot
Definition at line 57 of file AndroidPlatformTLS.h.
References FORCEINLINE.
Referenced by FScopeDisableMallocStomp2::FScopeDisableMallocStomp2(), FScopeDisableMallocStomp2::~FScopeDisableMallocStomp2(), TThreadSingleton< T >::~TThreadSingleton(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS(), FMallocCallstackHandler::DecDisabled(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Get(), TTypeContainer< Mode >::TThreadInstanceProvider< T >::GetInstance(), FRunnableThread::GetRunnableThread(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetTLS(), FMallocCallstackHandler::IncDisabled(), FMallocCallstackHandler::IsDisabled(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::LockTLS(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::UnlockTLS().
SetTlsValue()
FORCEINLINE void FAndroidTLS::SetTlsValue (uint32 SlotIndex, void * Value) inline static
Sets a value in the specified TLS slot.
Parameters
SlotIndex the TLS index to store it in
Value the value to store in the slot
Definition at line 47 of file AndroidPlatformTLS.h.
References FORCEINLINE, and Value.
Referenced by FScopeDisableMallocStomp2::FScopeDisableMallocStomp2(), FScopeDisableMallocStomp2::~FScopeDisableMallocStomp2(), TThreadSingleton< T >::~TThreadSingleton(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS(), FMallocCallstackHandler::DecDisabled(), TTypeContainer< Mode >::TThreadInstanceProvider< T >::GetInstance(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetTLS(), FMallocCallstackHandler::IncDisabled(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS().
The documentation for this struct was generated from the following file:
AndroidPlatformTLS.h