Unreal Engine 5.6 C++ API: FRetargetSourceCachedDataKey Struct Reference
FRetargetSourceCachedDataKey Struct Reference
#include "BoneContainer.h"
Public Member Functions
FRetargetSourceCachedDataKey (const UObject *Skeleton, const FName &InSourceRetargetName)
bool operator== (const FRetargetSourceCachedDataKey &Other) const
Data Fields
FName SourceRetargetName
FTopLevelAssetPath SourceSkeletonPath
Friends
uint32 GetTypeHash (const FRetargetSourceCachedDataKey &Obj)
Detailed Description
Definition at line 164 of file BoneContainer.h.
Constructor & Destructor Documentation
FRetargetSourceCachedDataKey()
FRetargetSourceCachedDataKey::FRetargetSourceCachedDataKey (const UObject * Skeleton, const FName & InSourceRetargetName) inline
Definition at line 169 of file BoneContainer.h.
References Skeleton, SourceRetargetName, and SourceSkeletonPath.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FRetargetSourceCachedDataKey::operator== (const FRetargetSourceCachedDataKey & Other) const inline
Definition at line 175 of file BoneContainer.h.
References FRetargetSourceCachedDataKey(), Other, SourceRetargetName, and SourceSkeletonPath.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRetargetSourceCachedDataKey & Obj) friend
Definition at line 179 of file BoneContainer.h.
References FRetargetSourceCachedDataKey(), GetTypeHash, HashCombine(), SourceRetargetName, and SourceSkeletonPath.
Referenced by GetTypeHash.
Field Documentation
SourceRetargetName
FName FRetargetSourceCachedDataKey::SourceRetargetName
Definition at line 167 of file BoneContainer.h.
Referenced by FRetargetSourceCachedDataKey(), GetTypeHash, and operator==().
SourceSkeletonPath
FTopLevelAssetPath FRetargetSourceCachedDataKey::SourceSkeletonPath
Definition at line 166 of file BoneContainer.h.
Referenced by FRetargetSourceCachedDataKey(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
BoneContainer.h