Unreal Engine 5.6 C++ API: TAllocatorFixedSizeFreeList< AllocationSize, BlockSize > Class Template Reference
TAllocatorFixedSizeFreeList< AllocationSize, BlockSize > Class Template Reference
Fixed-sized allocator that uses a free list to cache allocations.
#include "AllocatorFixedSizeFreeList.h"
Data Structures
struct FreeListNode
Public Member Functions
TAllocatorFixedSizeFreeList (uint32 InitialBlockSize=0)
Ctor.
~TAllocatorFixedSizeFreeList ()
Destructor.
void * Allocate ()
Allocates one element from the free list.
void Free (void *Element)
Returns one element from the free list.
uint32 GetAllocatedSize () const
Get total memory allocated.
void Grow (uint32 NumElements)
Grows the free list by a specific number of elements.
Private Member Functions
void CheckInvariants () const
Private Attributes
FreeListNode * FreeList
Linked List of free memory blocks.
uint32 NumAllocated
The number of objects that have been allocated.
uint32 NumLive
The number of objects that are constructed and "out in the wild".
Detailed Description
template<uint32 AllocationSize, uint32 BlockSize>
class TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >
Fixed-sized allocator that uses a free list to cache allocations.
Initial allocation block can be specified in the ctor to warm the cache. Subsequent allocations are in multiples of the given blocksize.
Grow can be called at any time to warm the cache with a single block allocation. Initial allocation will want to be a reasonable guess as to how big the pool might grow. BlockSize should be small enough to cut down on allocations but not overcommit memory.
NOTE: Currently there is not way to flush the pool because it doesn't track each block's allocation status.
Not threadsafe <could be implemented using a ThreadingPolicy template parameter>.
Template params: AllocationSize - size of each allocation (must be at least as large as a pointer) BlockSize - number of allocations to reserve room for when a new block needs to be allocated.
Definition at line 29 of file AllocatorFixedSizeFreeList.h.
Constructor & Destructor Documentation
TAllocatorFixedSizeFreeList()
template<uint32 AllocationSize, uint32 BlockSize> TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::TAllocatorFixedSizeFreeList (uint32 InitialBlockSize = 0) inline
Ctor.
Parameters
InitialBlockSize - number of allocations to warm the cache with
Definition at line 37 of file AllocatorFixedSizeFreeList.h.
References FreeList, Grow(), NumAllocated, and NumLive.
~TAllocatorFixedSizeFreeList()
template<uint32 AllocationSize, uint32 BlockSize> TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::~TAllocatorFixedSizeFreeList () inline
Destructor.
Can't free memory, so only checks that allocations have been returned.
Definition at line 52 of file AllocatorFixedSizeFreeList.h.
References check, GIsCriticalError, and NumLive.
Member Function Documentation
Allocate()
template<uint32 AllocationSize, uint32 BlockSize> void * TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::Allocate () inline
Allocates one element from the free list.
Return it by calling Free.
Definition at line 63 of file AllocatorFixedSizeFreeList.h.
References CheckInvariants(), checkSlow, FreeList, Grow(), NumAllocated, and NumLive.
CheckInvariants()
template<uint32 AllocationSize, uint32 BlockSize> void TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::CheckInvariants () const inline private
Definition at line 142 of file AllocatorFixedSizeFreeList.h.
References checkSlow, NumAllocated, and NumLive.
Referenced by Allocate(), Free(), and GetAllocatedSize().
Free()
template<uint32 AllocationSize, uint32 BlockSize> void TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::Free (void * Element) inline
Returns one element from the free list.
Must have been acquired previously by Allocate.
Definition at line 83 of file AllocatorFixedSizeFreeList.h.
References CheckInvariants(), checkSlow, FreeList, TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::FreeListNode::NextFreeAllocation, and NumLive.
GetAllocatedSize()
template<uint32 AllocationSize, uint32 BlockSize> uint32 TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::GetAllocatedSize () const inline
Get total memory allocated.
Only returns the size of allocations made directly by the allocator, not the elements themselves.
Definition at line 98 of file AllocatorFixedSizeFreeList.h.
References CheckInvariants(), and NumAllocated.
Grow()
template<uint32 AllocationSize, uint32 BlockSize> void TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::Grow (uint32 NumElements) inline
Grows the free list by a specific number of elements.
Does one allocation for all elements. Safe to call at any time to warm the cache with a single block allocation.
Definition at line 108 of file AllocatorFixedSizeFreeList.h.
References check, FreeList, TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::FreeListNode::NextFreeAllocation, and NumAllocated.
Referenced by TAllocatorFixedSizeFreeList(), and Allocate().
Field Documentation
FreeList
template<uint32 AllocationSize, uint32 BlockSize> FreeListNode* TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::FreeList private
Linked List of free memory blocks.
Definition at line 150 of file AllocatorFixedSizeFreeList.h.
Referenced by TAllocatorFixedSizeFreeList(), Allocate(), Free(), and Grow().
NumAllocated
template<uint32 AllocationSize, uint32 BlockSize> uint32 TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::NumAllocated private
The number of objects that have been allocated.
Definition at line 153 of file AllocatorFixedSizeFreeList.h.
Referenced by TAllocatorFixedSizeFreeList(), Allocate(), CheckInvariants(), GetAllocatedSize(), and Grow().
NumLive
template<uint32 AllocationSize, uint32 BlockSize> uint32 TAllocatorFixedSizeFreeList< AllocationSize, BlockSize >::NumLive private
The number of objects that are constructed and "out in the wild".
Definition at line 156 of file AllocatorFixedSizeFreeList.h.
Referenced by TAllocatorFixedSizeFreeList(), ~TAllocatorFixedSizeFreeList(), Allocate(), CheckInvariants(), and Free().
The documentation for this class was generated from the following file:
AllocatorFixedSizeFreeList.h