Unreal Engine 5.6 C++ API: UE::Geometry::TIntrLine2Triangle2< Real > Class Template Reference
UE::Geometry::TIntrLine2Triangle2< Real > Class Template Reference
Compute intersection between 2D Line and 2D Triangle.
#include "IntrLine2Triangle2.h"
Public Member Functions
TIntrLine2Triangle2 ()
TIntrLine2Triangle2 (TLine2< Real > l, TTriangle2< Real > t)
TIntrLine2Triangle2 * Compute ()
bool Find ()
TLine2< Real > GetLine () const
TTriangle2< Real > GetTriangle () const
bool IsSimpleIntersection ()
void SetLine (const TLine2< Real > &LineIn)
void SetTriangle (const TTriangle2< Real > &TriangleIn)
Static Public Member Functions
static bool GetInterval (const TVector2< Real > &Origin, const TVector2< Real > &Direction, const TTriangle2< Real > &Tri, const TVector< Real > &Dist, const FVector3i &Sign, TVector2< Real > &param)
static void TriangleLineRelations (const TVector2< Real > &Origin, const TVector2< Real > &Direction, const TTriangle2< Real > &Tri, TVector< Real > &Dist, FVector3i &Sign, int &Positive, int &Negative, int &Zero, Real Tolerance=TMathUtil< Real >::ZeroTolerance)
Data Fields
double Param0
double Param1
TVector2< Real > Point0
TVector2< Real > Point1
int Quantity = 0
EIntersectionResult Result = EIntersectionResult::NotComputed
EIntersectionType Type = EIntersectionType::Empty
Protected Attributes
TLine2< Real > Line
TTriangle2< Real > Triangle
Detailed Description
template<typename Real>
class UE::Geometry::TIntrLine2Triangle2< Real >
Compute intersection between 2D Line and 2D Triangle.
Definition at line 26 of file IntrLine2Triangle2.h.
Constructor & Destructor Documentation
TIntrLine2Triangle2() [1/2]
template<typename Real> UE::Geometry::TIntrLine2Triangle2< Real >::TIntrLine2Triangle2 () inline
Definition at line 68 of file IntrLine2Triangle2.h.
TIntrLine2Triangle2() [2/2]
template<typename Real> UE::Geometry::TIntrLine2Triangle2< Real >::TIntrLine2Triangle2 (TLine2< Real > l, TTriangle2< Real > t) inline
Definition at line 70 of file IntrLine2Triangle2.h.
Member Function Documentation
Compute()
template<typename Real> TIntrLine2Triangle2 * UE::Geometry::TIntrLine2Triangle2< Real >::Compute () inline
Definition at line 75 of file IntrLine2Triangle2.h.
Find()
template<typename Real> bool UE::Geometry::TIntrLine2Triangle2< Real >::Find () inline
Definition at line 82 of file IntrLine2Triangle2.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Compute().
GetInterval()
template<typename Real> bool UE::Geometry::TIntrLine2Triangle2< Real >::GetInterval (const TVector2< Real > & Origin, const TVector2< Real > & Direction, const TTriangle2< Real > & Tri, const TVector< Real > & Dist, const FVector3i & Sign, TVector2< Real > & param) inline static
Definition at line 179 of file IntrLine2Triangle2.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
GetLine()
template<typename Real> TLine2< Real > UE::Geometry::TIntrLine2Triangle2< Real >::GetLine () const inline
Definition at line 44 of file IntrLine2Triangle2.h.
GetTriangle()
template<typename Real> TTriangle2< Real > UE::Geometry::TIntrLine2Triangle2< Real >::GetTriangle () const inline
Definition at line 48 of file IntrLine2Triangle2.h.
IsSimpleIntersection()
template<typename Real> bool UE::Geometry::TIntrLine2Triangle2< Real >::IsSimpleIntersection () inline
Definition at line 63 of file IntrLine2Triangle2.h.
SetLine()
template<typename Real> void UE::Geometry::TIntrLine2Triangle2< Real >::SetLine (const TLine2< Real > & LineIn) inline
Definition at line 52 of file IntrLine2Triangle2.h.
SetTriangle()
template<typename Real> void UE::Geometry::TIntrLine2Triangle2< Real >::SetTriangle (const TTriangle2< Real > & TriangleIn) inline
Definition at line 57 of file IntrLine2Triangle2.h.
TriangleLineRelations()
template<typename Real> void UE::Geometry::TIntrLine2Triangle2< Real >::TriangleLineRelations (const TVector2< Real > & Origin, const TVector2< Real > & Direction, const TTriangle2< Real > & Tri, TVector< Real > & Dist, FVector3i & Sign, int & Positive, int & Negative, int & Zero, Real Tolerance = TMathUtil<Real>::ZeroTolerance) inline static
Definition at line 148 of file IntrLine2Triangle2.h.
Referenced by UE::Geometry::TIntrLine2Triangle2< float >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
Field Documentation
Line
template<typename Real> TLine2<Real> UE::Geometry::TIntrLine2Triangle2< Real >::Line protected
Definition at line 30 of file IntrLine2Triangle2.h.
Param0
template<typename Real> double UE::Geometry::TIntrLine2Triangle2< Real >::Param0
Definition at line 41 of file IntrLine2Triangle2.h.
Param1
template<typename Real> double UE::Geometry::TIntrLine2Triangle2< Real >::Param1
Definition at line 42 of file IntrLine2Triangle2.h.
Point0
template<typename Real> TVector2<Real> UE::Geometry::TIntrLine2Triangle2< Real >::Point0
Definition at line 39 of file IntrLine2Triangle2.h.
Point1
template<typename Real> TVector2<Real> UE::Geometry::TIntrLine2Triangle2< Real >::Point1
Definition at line 40 of file IntrLine2Triangle2.h.
Quantity
template<typename Real> int UE::Geometry::TIntrLine2Triangle2< Real >::Quantity = 0
Definition at line 35 of file IntrLine2Triangle2.h.
Result
template<typename Real> EIntersectionResult UE::Geometry::TIntrLine2Triangle2< Real >::Result = EIntersectionResult::NotComputed
Definition at line 36 of file IntrLine2Triangle2.h.
Triangle
template<typename Real> TTriangle2<Real> UE::Geometry::TIntrLine2Triangle2< Real >::Triangle protected
Definition at line 31 of file IntrLine2Triangle2.h.
Type
template<typename Real> EIntersectionType UE::Geometry::TIntrLine2Triangle2< Real >::Type = EIntersectionType::Empty
Definition at line 37 of file IntrLine2Triangle2.h.
The documentation for this class was generated from the following file:
IntrLine2Triangle2.h