Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItem Class Reference
UE::SequenceNavigator::FNavigationToolItem Class Reference abstract
Base Implementation of INavigationToolItem.
#include "NavigationToolItem.h"
Public Member Functions
FNavigationToolItem (INavigationTool &InTool, const FNavigationToolItemPtr &InParentItem)
virtual FReply AcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Processes the Drag and Drop Event for this Item.
virtual bool AddChild (const FNavigationToolAddItemParams &InAddItemParams) override
Adds another Child under this Item if such Item is supported.
virtual void AddFlags (ENavigationToolItemFlags Flags) override
virtual TOptional< EItemDropZone > CanAcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Determines if and where the incoming Drag Drop Event can be processed by this item.
virtual bool CanAddChild (const FNavigationToolItemPtr &InChild) const override
Determines whether the given Child is supported and can be added under this Item.
virtual bool CanAutoExpand () const override
Whether the Item is able to expand when AutoExpand functionality is enabled.
virtual bool CanBeTopLevel () const override
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
virtual bool CanDelete () const override
Whether this Item can be deleted or not.
virtual bool CanReceiveParentVisibilityPropagation () const override
Whether a change in Parent Visibility should also affect this Item's Visibility.
DECLARE_DELEGATE_RetVal_OneParam (FNavigationToolSaveState *, FNavigationToolGetToolState, const FNavigationToolItemPtr)
virtual bool Delete () override
The implementation to delete the item.
virtual void FindChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive) override
Figures out the Children of this Item.
virtual TArray< FNavigationToolItemPtr > FindPath (const TArray< FNavigationToolItemPtr > &InItems) const override
virtual void FindValidChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive) override
virtual TSharedRef< SWidget > GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > &InRow) override
Function responsible of Generating the Label Widget for this Item (i.e.
virtual IndexType GetChildIndex (const FNavigationToolItemPtr &ChildItem) const override
Gets the Index that the given Child Item is at.
virtual const TArray< FNavigationToolItemPtr > & GetChildren () const override
Gets the current Child Items of this Item.
virtual TArray< FNavigationToolItemPtr > & GetChildrenMutable () override
Gets the current Child Items of this Item.
virtual FText GetClassName () const override
Gets the Class/Type of this Item (e.g.
virtual TOptional< FColor > GetColor () const override
virtual FText GetDisplayName () const override
Gets the Display Name Text of the Item.
virtual ENavigationToolItemFlags GetFlags () const override
virtual const FSlateBrush * GetIconBrush () const override
virtual FSlateColor GetIconColor () const override
Gets the color for the item icon.
virtual FNavigationToolItemId GetItemId () const override final
Gets the Id of this Item.
virtual FSlateColor GetItemLabelColor () const override
Gets the color to use for the item label.
virtual FLinearColor GetItemTintColor () const override
Gets the color to use to tint the entire item row (all column content)
virtual INavigationTool & GetOwnerTool () const final override
Gets the Navigation Tool that owns this item.
virtual FNavigationToolItemPtr GetParent () const override
Gets the Parent of this Item.
virtual TSharedPtr< FNavigationToolProvider > GetProvider () const final override
Gets the module provider responsible for the creation of this item.
virtual FNavigationToolSaveState * GetProviderSaveState () const override
Gets the providers saved state.
virtual ENavigationToolItemViewMode GetSupportedViewModes (const INavigationToolView &InToolView) const override
Gets the View Modes that this Item Supports.
virtual TArray< FName > GetTags () const override
Gets the Tags found for this Item (e.g.
virtual bool GetVisibility () const override
Whether this Item is currently visible or not for the Given Type.
virtual bool HasAllFlags (ENavigationToolItemFlags Flags) const override
virtual bool HasAnyFlags (ENavigationToolItemFlags Flags) const override
virtual bool IsAllowedInTool () const override
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
virtual bool IsExpanded () const override
Gets whether this item is expanded.
virtual bool IsItemValid () const override
Determines whether the Item properties are in a valid state.
virtual FOnExpansionChanged & OnExpansionChanged () override
Called when Expansion state (Expanded/Collapsed) has been changed.
virtual FOnRenameAction & OnRenameAction () override
Broadcasts whenever a rename action takes place from a given view (e.g.
virtual void RefreshChildren () override
Refreshes what the Parent and Children are of this Item.
virtual bool RemoveChild (const FNavigationToolRemoveItemParams &InRemoveItemParams) override
Removes the given child from this Item if it was ever indeed a child.
virtual void RemoveFlags (ENavigationToolItemFlags Flags) override
virtual void ResetChildren () override
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
virtual void SetColor (const TOptional< FColor > &InColor) override
virtual void SetExpansion (const bool bInExpand) override
Sets the expansion state of this item.
virtual void SetFlags (ENavigationToolItemFlags InFlags) override
virtual void SetParent (FNavigationToolItemPtr InParent) override
Sets the Parent.
virtual bool ShouldSort () const override
Determines whether this item can be sorted by the Navigation Tool or not.
virtual bool ShowVisibility () const override
Whether this Item supports Visibility for the Given Type.
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItem, INavigationToolItem, IColorExtension)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItem
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false)
Finds the first ancestor view model that implements the given type.
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false) const
template<typename InItemType>
TArray< InItemType * > FindAncestorsOfType (const bool bInIncludeThis=false) const
virtual FNavigationToolItemPtr GetChildAt (const IndexType Index) const
template<typename InItemType>
TArray< InItemType * > GetChildrenOfType (const bool bInIncludeThis=false) const
virtual const FSlateBrush * GetDefaultIconBrush () const
TArray< FNavigationToolItemPtr > GetDescendants (const bool bInIncludeThis=false)
template<typename InItemType>
TArray< InItemType * > GetDescendantsOfType (const bool bInIncludeThis=false) const
FString GetFullPath () const
Returns the path to this item in the tree.
virtual FSlateIcon GetIcon () const =0
Gets the slate icon for the item.
virtual FText GetIconTooltipText () const =0
Gets the tooltip text for the item icon.
virtual UObject * GetItemObject () const
Gets the UObject that this item represents.
virtual void GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > &OutItemProxies)
Gets the Item Proxies for this Item (e.g.
virtual int32 GetItemTreeHeight () const
Returns the item's height in tree, Root Item should return 0 as it has no Parent.
virtual TSet< FNavigationToolItemPtr > GetParents (const bool bInIncludeRoot=false) const
Gets the list of all parents up the tree from this Item.
bool IsIgnoringPendingKill () const
Whether Ignoring Pending Kill.
virtual bool IsSelectable () const
Whether the Item can be selected in Navigation Tool at all.
virtual bool IsSelected (const FNavigationToolScopedSelection &InSelection) const
Determines whether the given Item is selected in the given Scoped Selection.
virtual bool IsViewModeSupported (const ENavigationToolItemViewMode InViewMode, const INavigationToolView &InToolView) const
Whether this Item should be visualized in the given View Mode, for the given Navigation Tool View.
virtual FNavigationToolSerializedItem MakeSerializedItem ()
Converts this Navigation Tool item to a serialized item that can be saved in the sequence.
virtual void OnDoubleClick ()
Called when an Item is double-clicked with the mouse.
virtual void OnItemRegistered ()
Called when the Item has been registered into the Navigation Tool.
virtual void OnItemSelectionChanged (const bool bInIsSelected)
Called when the Item been selected/deselected from the Tree View.
virtual void OnItemUnregistered ()
Called when the Item has been unregistered from the Navigation Tool.
virtual void OnObjectsReplaced (const TMap< UObject *, UObject * > &InReplacementMap, const bool bInRecursive)
Called when objects have been replaced on the Engine side.
virtual void OnSelect ()
Called when an Item is selected.
virtual void OnVisibilityChanged (const bool bInNewVisibility)
Called when the Visibility on Item has been changed on the Navigation Tool side.
virtual void Select (FNavigationToolScopedSelection &InSelection) const
Used to signal the Scoped Selection that this Item should be Selected.
UE_NAVIGATIONTOOL_INHERITS (INavigationToolItem, INavigationToolItemTypeCastable)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
virtual ~INavigationToolItemTypeCastable ()=default
template<typename InType>
InType * CastTo ()
template<typename InType>
const InType * CastTo () const
virtual const void * CastTo_Impl (FNavigationToolItemTypeId InId) const =0
virtual FNavigationToolItemTypeId GetTypeId () const =0
template<typename InType>
bool IsA () const
template<typename InType>
bool IsExactlyA () const
Public Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedRef< INavigationToolItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< INavigationToolItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::SequenceNavigator::IColorExtension
UE_NAVIGATIONTOOL_INHERITS (IColorExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual TOptional< FColor > GetColor() const =0
Protected Member Functions
void AddChildChecked (const FNavigationToolAddItemParams &InAddItemParams)
The actual implementation of putting the given Item under the Children array.
virtual FNavigationToolItemId CalculateItemId () const =0
Gets the Item Id with the latest information (e.g.
void HandleNewSortableChildren (TArray< FNavigationToolItemPtr > InSortableChildren)
Careful handling of multiple children being detected and added to this item children array.
void RecalculateItemId ()
Sets the ItemId member var to what CalculateItemId returns.
bool RemoveChildChecked (const FNavigationToolRemoveItemParams &InRemoveItemParams)
The actual implementation of removing the given item from the Children array.
void SetProvider (const TWeakPtr< FNavigationToolProvider > &InWeakProvider)
Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< FNavigationToolItemPtr > Children
Array of Shared pointers to the Child Items.
ENavigationToolItemFlags ItemFlags = ENavigationToolItemFlags::None
The current flags set for this item.
FNavigationToolItemId ItemId
FOnExpansionChanged OnExpansionChangedDelegate
Delegate for when Expansion changes in the Item.
FOnRenameAction OnRenameActionDelegate
The delegate for renaming.
INavigationTool & Tool
Reference to the Owning Navigation Tool.
FNavigationToolItemWeakPtr WeakParent
Weak pointer to the Parent Item.
TWeakPtr< FNavigationToolProvider > WeakProvider
Tool provider that is responsible for the creation of this item.
Friends
class FNavigationTool
class INavigationTool
Additional Inherited Members
Public Types inherited from UE::SequenceNavigator::INavigationToolItem
using FOnExpansionChanged = TMulticastDelegate<void(const TSharedPtr<INavigationToolView>&, bool)>
Delegate signature for when the Item Expansion Changes const TSharedPtr<FNavigationToolView>& - The Navigation Tool View where this Expansion happened bool - Whether the Item is expanded.
using FOnRenameAction = TMulticastDelegate<void(ENavigationToolRenameAction, const TSharedPtr<INavigationToolView>&)>
Delegate signature for relaying an Item Rename action ENavigationToolRenameAction the type of action being relayed (e.g.
Public Types inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
using FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Static Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
static FNavigationToolItemTypeId GetStaticTypeId ()
Protected Types inherited from UE::SequenceNavigator::INavigationToolItem
using IndexType = TArray<INavigationToolItem>::SizeType
Static Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Base Implementation of INavigationToolItem.
Definition at line 19 of file NavigationToolItem.h.
Constructor & Destructor Documentation
FNavigationToolItem()
UE::SequenceNavigator::FNavigationToolItem::FNavigationToolItem (INavigationTool & InTool, const FNavigationToolItemPtr & InParentItem)
References INavigationTool.
Referenced by UE::SequenceNavigator::FNavigationToolBinding::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), UE::SequenceNavigator::FNavigationToolItemProxy::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), UE::SequenceNavigator::FNavigationToolMarker::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), UE::SequenceNavigator::FNavigationToolSequence::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), and UE::SequenceNavigator::FNavigationToolTrack::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER().
Member Function Documentation
AcceptDrop()
virtual FReply UE::SequenceNavigator::FNavigationToolItem::AcceptDrop (const FDragDropEvent & InDragDropEvent, EItemDropZone InDropZone) override virtual
Processes the Drag and Drop Event for this Item.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolSubTrack.
AddChild()
virtual bool UE::SequenceNavigator::FNavigationToolItem::AddChild (const FNavigationToolAddItemParams & InAddItemParams) override virtual
Adds another Child under this Item if such Item is supported.
Returns true if it did, false if it could not add it (e.g. item not supported).
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolSequence.
AddChildChecked()
void UE::SequenceNavigator::FNavigationToolItem::AddChildChecked (const FNavigationToolAddItemParams & InAddItemParams) protected
The actual implementation of putting the given Item under the Children array.
AddFlags()
virtual void UE::SequenceNavigator::FNavigationToolItem::AddFlags (ENavigationToolItemFlags Flags) override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
References Flags.
CalculateItemId()
virtual FNavigationToolItemId UE::SequenceNavigator::FNavigationToolItem::CalculateItemId () const protected pure virtual
Gets the Item Id with the latest information (e.g.
parent, object, etc)
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
CanAcceptDrop()
virtual TOptional< EItemDropZone > UE::SequenceNavigator::FNavigationToolItem::CanAcceptDrop (const FDragDropEvent & InDragDropEvent, EItemDropZone InDropZone) override virtual
Determines if and where the incoming Drag Drop Event can be processed by this item.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolSubTrack.
CanAddChild()
virtual bool UE::SequenceNavigator::FNavigationToolItem::CanAddChild (const FNavigationToolItemPtr & InChild) const override virtual
Determines whether the given Child is supported and can be added under this Item.
Implements UE::SequenceNavigator::INavigationToolItem.
CanAutoExpand()
virtual bool UE::SequenceNavigator::FNavigationToolItem::CanAutoExpand () const inline override virtual
Whether the Item is able to expand when AutoExpand functionality is enabled.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolItemProxy.
Definition at line 67 of file NavigationToolItem.h.
CanBeTopLevel()
virtual bool UE::SequenceNavigator::FNavigationToolItem::CanBeTopLevel () const inline override virtual
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
Actors can be Top Level, but Components or Materials can't
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 53 of file NavigationToolItem.h.
CanDelete()
virtual bool UE::SequenceNavigator::FNavigationToolItem::CanDelete () const inline override virtual
Whether this Item can be deleted or not.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, and UE::SequenceNavigator::FNavigationToolMarker.
Definition at line 68 of file NavigationToolItem.h.
CanReceiveParentVisibilityPropagation()
virtual bool UE::SequenceNavigator::FNavigationToolItem::CanReceiveParentVisibilityPropagation () const inline override virtual
Whether a change in Parent Visibility should also affect this Item's Visibility.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, and UE::SequenceNavigator::FNavigationToolComponent.
Definition at line 65 of file NavigationToolItem.h.
DECLARE_DELEGATE_RetVal_OneParam()
UE::SequenceNavigator::FNavigationToolItem::DECLARE_DELEGATE_RetVal_OneParam (FNavigationToolSaveState * , FNavigationToolGetToolState , const FNavigationToolItemPtr)
Delete()
virtual bool UE::SequenceNavigator::FNavigationToolItem::Delete () override virtual
The implementation to delete the item.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, and UE::SequenceNavigator::FNavigationToolMarker.
FindChildren()
virtual void UE::SequenceNavigator::FNavigationToolItem::FindChildren (TArray< FNavigationToolItemPtr > & OutChildren, const bool bInRecursive) override virtual
Figures out the Children of this Item.
This is only relevant for items that do have that functionality (e.g. Components or Actors)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolSequence, UE::SequenceNavigator::FNavigationToolSubTrack, and UE::SequenceNavigator::FNavigationToolTrack.
FindPath()
virtual TArray< FNavigationToolItemPtr > UE::SequenceNavigator::FNavigationToolItem::FindPath (const TArray< FNavigationToolItemPtr > & InItems) const override virtual
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
FindValidChildren()
virtual void UE::SequenceNavigator::FNavigationToolItem::FindValidChildren (TArray< FNavigationToolItemPtr > & OutChildren, const bool bInRecursive) override virtual
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
GenerateLabelWidget()
virtual TSharedRef< SWidget > UE::SequenceNavigator::FNavigationToolItem::GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > & InRow) override virtual
Function responsible of Generating the Label Widget for this Item (i.e.
the column containing the Icon and the Name)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolComponent.
References GenerateLabelWidget().
Referenced by GenerateLabelWidget().
GetChildIndex()
virtual IndexType UE::SequenceNavigator::FNavigationToolItem::GetChildIndex (const FNavigationToolItemPtr & ChildItem) const override virtual
Gets the Index that the given Child Item is at.
NOTE: This includes HIDDEN items as Item Visibility is relative to each Navigation Tool View. To consider only Visible Items, use FNavigationToolView::GetVisibleChildAt.
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
GetChildren()
virtual const TArray< FNavigationToolItemPtr > & UE::SequenceNavigator::FNavigationToolItem::GetChildren () const inline override virtual
Gets the current Child Items of this Item.
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 41 of file NavigationToolItem.h.
References Children, and GetChildren().
Referenced by GetChildren().
GetChildrenMutable()
virtual TArray< FNavigationToolItemPtr > & UE::SequenceNavigator::FNavigationToolItem::GetChildrenMutable () inline override virtual
Gets the current Child Items of this Item.
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 45 of file NavigationToolItem.h.
References Children.
GetClassName()
virtual FText UE::SequenceNavigator::FNavigationToolItem::GetClassName () const inline override virtual
Gets the Class/Type of this Item (e.g.
for Items that represent UObjects, it will be the UObject class)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 56 of file NavigationToolItem.h.
References FText::GetEmpty().
GetColor()
virtual TOptional< FColor > UE::SequenceNavigator::FNavigationToolItem::GetColor () const override virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolSequence.
GetDisplayName()
virtual FText UE::SequenceNavigator::FNavigationToolItem::GetDisplayName () const inline override virtual
Gets the Display Name Text of the Item.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 55 of file NavigationToolItem.h.
References FText::GetEmpty().
GetFlags()
virtual ENavigationToolItemFlags UE::SequenceNavigator::FNavigationToolItem::GetFlags () const inline override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 75 of file NavigationToolItem.h.
References ItemFlags.
GetIconBrush()
virtual const FSlateBrush * UE::SequenceNavigator::FNavigationToolItem::GetIconBrush () const override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolMarker.
References GetIconBrush().
Referenced by GetIconBrush().
GetIconColor()
virtual FSlateColor UE::SequenceNavigator::FNavigationToolItem::GetIconColor () const override virtual
Gets the color for the item icon.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, and UE::SequenceNavigator::FNavigationToolMarker.
References GetIconColor().
Referenced by GetIconColor().
GetItemId()
virtual FNavigationToolItemId UE::SequenceNavigator::FNavigationToolItem::GetItemId () const final override virtual
Gets the Id of this Item.
Implements UE::SequenceNavigator::INavigationToolItem.
GetItemLabelColor()
virtual FSlateColor UE::SequenceNavigator::FNavigationToolItem::GetItemLabelColor () const override virtual
Gets the color to use for the item label.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding.
References GetItemLabelColor().
Referenced by GetItemLabelColor().
GetItemTintColor()
virtual FLinearColor UE::SequenceNavigator::FNavigationToolItem::GetItemTintColor () const override virtual
Gets the color to use to tint the entire item row (all column content)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolComponent.
References GetItemTintColor().
Referenced by GetItemTintColor().
GetOwnerTool()
virtual INavigationTool & UE::SequenceNavigator::FNavigationToolItem::GetOwnerTool () const final override virtual
Gets the Navigation Tool that owns this item.
Implements UE::SequenceNavigator::INavigationToolItem.
References INavigationTool.
GetParent()
virtual FNavigationToolItemPtr UE::SequenceNavigator::FNavigationToolItem::GetParent () const inline override virtual
Gets the Parent of this Item.
Should only be null prior to registering it in Navigation Tool or if its Root Item
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 51 of file NavigationToolItem.h.
References WeakParent.
GetProvider()
virtual TSharedPtr< FNavigationToolProvider > UE::SequenceNavigator::FNavigationToolItem::GetProvider () const final override virtual
Gets the module provider responsible for the creation of this item.
Implements UE::SequenceNavigator::INavigationToolItem.
References GetProvider().
Referenced by GetProvider().
GetProviderSaveState()
virtual FNavigationToolSaveState * UE::SequenceNavigator::FNavigationToolItem::GetProviderSaveState () const override virtual
Gets the providers saved state.
Implements UE::SequenceNavigator::INavigationToolItem.
References GetProviderSaveState().
Referenced by GetProviderSaveState().
GetSupportedViewModes()
virtual ENavigationToolItemViewMode UE::SequenceNavigator::FNavigationToolItem::GetSupportedViewModes (const INavigationToolView & InToolView) const override virtual
Gets the View Modes that this Item Supports.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, and UE::SequenceNavigator::FNavigationToolSequence.
GetTags()
virtual TArray< FName > UE::SequenceNavigator::FNavigationToolItem::GetTags () const inline override virtual
Gets the Tags found for this Item (e.g.
for Actors, actor tags and for Components Component Tags)
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, and UE::SequenceNavigator::FNavigationToolComponent.
Definition at line 76 of file NavigationToolItem.h.
GetVisibility()
virtual bool UE::SequenceNavigator::FNavigationToolItem::GetVisibility () const inline override virtual
Whether this Item is currently visible or not for the Given Type.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, and UE::SequenceNavigator::FNavigationToolComponent.
Definition at line 66 of file NavigationToolItem.h.
HandleNewSortableChildren()
void UE::SequenceNavigator::FNavigationToolItem::HandleNewSortableChildren (TArray< FNavigationToolItemPtr > InSortableChildren) protected
Careful handling of multiple children being detected and added to this item children array.
HasAllFlags()
virtual bool UE::SequenceNavigator::FNavigationToolItem::HasAllFlags (ENavigationToolItemFlags Flags) const override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
References Flags.
HasAnyFlags()
virtual bool UE::SequenceNavigator::FNavigationToolItem::HasAnyFlags (ENavigationToolItemFlags Flags) const override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
References Flags.
IsAllowedInTool()
virtual bool UE::SequenceNavigator::FNavigationToolItem::IsAllowedInTool () const inline override virtual
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 54 of file NavigationToolItem.h.
IsExpanded()
virtual bool UE::SequenceNavigator::FNavigationToolItem::IsExpanded () const override virtual
Gets whether this item is expanded.
Implements UE::SequenceNavigator::INavigationToolItem.
IsItemValid()
virtual bool UE::SequenceNavigator::FNavigationToolItem::IsItemValid () const override virtual
Determines whether the Item properties are in a valid state.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
References IsItemValid().
Referenced by IsItemValid().
OnExpansionChanged()
virtual FOnExpansionChanged & UE::SequenceNavigator::FNavigationToolItem::OnExpansionChanged () inline override virtual
Called when Expansion state (Expanded/Collapsed) has been changed.
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 80 of file NavigationToolItem.h.
References OnExpansionChangedDelegate.
OnRenameAction()
virtual FOnRenameAction & UE::SequenceNavigator::FNavigationToolItem::OnRenameAction () inline override virtual
Broadcasts whenever a rename action takes place from a given view (e.g.
when pressing "F2" to rename, or committing the rename text)
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 79 of file NavigationToolItem.h.
References OnRenameActionDelegate.
RecalculateItemId()
void UE::SequenceNavigator::FNavigationToolItem::RecalculateItemId () protected
Sets the ItemId member var to what CalculateItemId returns.
RefreshChildren()
virtual void UE::SequenceNavigator::FNavigationToolItem::RefreshChildren () override virtual
Refreshes what the Parent and Children are of this Item.
(not recursive!)
Implements UE::SequenceNavigator::INavigationToolItem.
References RefreshChildren().
Referenced by RefreshChildren().
RemoveChild()
virtual bool UE::SequenceNavigator::FNavigationToolItem::RemoveChild (const FNavigationToolRemoveItemParams & InRemoveItemParams) override virtual
Removes the given child from this Item if it was ever indeed a child.
Returns true if the removal did happen.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolSequence.
RemoveChildChecked()
bool UE::SequenceNavigator::FNavigationToolItem::RemoveChildChecked (const FNavigationToolRemoveItemParams & InRemoveItemParams) protected
The actual implementation of removing the given item from the Children array.
RemoveFlags()
virtual void UE::SequenceNavigator::FNavigationToolItem::RemoveFlags (ENavigationToolItemFlags Flags) override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
References Flags.
ResetChildren()
virtual void UE::SequenceNavigator::FNavigationToolItem::ResetChildren () override virtual
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
Reimplemented from UE::SequenceNavigator::INavigationToolItem.
References ResetChildren().
Referenced by ResetChildren().
SetColor()
virtual void UE::SequenceNavigator::FNavigationToolItem::SetColor (const TOptional< FColor > & InColor) override virtual
Implements UE::SequenceNavigator::IColorExtension.
Reimplemented in UE::SequenceNavigator::FNavigationToolSequence.
SetExpansion()
virtual void UE::SequenceNavigator::FNavigationToolItem::SetExpansion (const bool bInIsExpanded) override virtual
Sets the expansion state of this item.
Implements UE::SequenceNavigator::INavigationToolItem.
SetFlags()
virtual void UE::SequenceNavigator::FNavigationToolItem::SetFlags (ENavigationToolItemFlags InFlags) inline override virtual
Implements UE::SequenceNavigator::INavigationToolItem.
Definition at line 74 of file NavigationToolItem.h.
References ItemFlags.
SetParent()
virtual void UE::SequenceNavigator::FNavigationToolItem::SetParent (FNavigationToolItemPtr InParent) override virtual
Sets the Parent.
Note that the Parent must've already have this instance as a child (check is done)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolItemProxy.
SetProvider()
void UE::SequenceNavigator::FNavigationToolItem::SetProvider (const TWeakPtr< FNavigationToolProvider > & InWeakProvider) protected
ShouldSort()
virtual bool UE::SequenceNavigator::FNavigationToolItem::ShouldSort () const inline override virtual
Determines whether this item can be sorted by the Navigation Tool or not.
Unsorted Items usually mean that they have their own way of sorting that Navigation Tool's Item Sorting Data should not interfere with. Note: Unsorted Children go before Sorted Items (e.g. Item Proxies go first before Actors below a Parent)
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding.
Definition at line 47 of file NavigationToolItem.h.
ShowVisibility()
virtual bool UE::SequenceNavigator::FNavigationToolItem::ShowVisibility () const inline override virtual
Whether this Item supports Visibility for the Given Type.
Implements UE::SequenceNavigator::INavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, and UE::SequenceNavigator::FNavigationToolComponent.
Definition at line 64 of file NavigationToolItem.h.
References ShowVisibility().
Referenced by ShowVisibility().
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER()
UE::SequenceNavigator::FNavigationToolItem::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItem , INavigationToolItem , IColorExtension)
References FNavigationToolItem().
Friends And Related Symbol Documentation
FNavigationTool
friend class FNavigationTool friend
Definition at line 23 of file NavigationToolItem.h.
References FNavigationTool.
Referenced by FNavigationTool.
INavigationTool
friend class INavigationTool friend
Definition at line 91 of file NavigationToolItem.h.
References INavigationTool.
Referenced by UE::SequenceNavigator::FNavigationToolBinding::FNavigationToolBinding(), FNavigationToolItem(), UE::SequenceNavigator::FNavigationToolItemProxy::FNavigationToolItemProxy(), UE::SequenceNavigator::FNavigationToolMarker::FNavigationToolMarker(), UE::SequenceNavigator::FNavigationToolSequence::FNavigationToolSequence(), UE::SequenceNavigator::FNavigationToolTrack::FNavigationToolTrack(), GetOwnerTool(), and INavigationTool.
Field Documentation
Children
TArray<FNavigationToolItemPtr> UE::SequenceNavigator::FNavigationToolItem::Children protected
Array of Shared pointers to the Child Items.
These Items should have their ParentWeak pointing to this item
Definition at line 120 of file NavigationToolItem.h.
Referenced by GetChildren(), and GetChildrenMutable().
ItemFlags
ENavigationToolItemFlags UE::SequenceNavigator::FNavigationToolItem::ItemFlags = ENavigationToolItemFlags::None protected
The current flags set for this item.
Definition at line 129 of file NavigationToolItem.h.
Referenced by GetFlags(), and SetFlags().
ItemId
FNavigationToolItemId UE::SequenceNavigator::FNavigationToolItem::ItemId protected
Definition at line 131 of file NavigationToolItem.h.
OnExpansionChangedDelegate
FOnExpansionChanged UE::SequenceNavigator::FNavigationToolItem::OnExpansionChangedDelegate protected
Delegate for when Expansion changes in the Item.
Definition at line 123 of file NavigationToolItem.h.
Referenced by OnExpansionChanged().
OnRenameActionDelegate
FOnRenameAction UE::SequenceNavigator::FNavigationToolItem::OnRenameActionDelegate protected
The delegate for renaming.
Definition at line 126 of file NavigationToolItem.h.
Referenced by OnRenameAction().
Tool
INavigationTool& UE::SequenceNavigator::FNavigationToolItem::Tool protected
Reference to the Owning Navigation Tool.
Definition at line 111 of file NavigationToolItem.h.
WeakParent
FNavigationToolItemWeakPtr UE::SequenceNavigator::FNavigationToolItem::WeakParent protected
Weak pointer to the Parent Item.
Can be null, but if valid, the Parent should have this item in the Children Array
Definition at line 117 of file NavigationToolItem.h.
Referenced by GetParent().
WeakProvider
TWeakPtr<FNavigationToolProvider> UE::SequenceNavigator::FNavigationToolItem::WeakProvider protected
Tool provider that is responsible for the creation of this item.
Definition at line 114 of file NavigationToolItem.h.
The documentation for this class was generated from the following file:
NavigationToolItem.h