Unreal Engine 5.6 C++ API: ToolBuilderUtil Namespace Reference
ToolBuilderUtil Namespace Reference
Helper functions that can be used in InteractiveToolBuilder implementations.
Functions
INTERACTIVETOOLSFRAMEWORK_API bool ComponentTypeCouldHaveUVs (const UActorComponent &Component)
Determine if component support UVs.
INTERACTIVETOOLSFRAMEWORK_API int32 CountActors (const FToolBuilderState &InputState, const TFunction< bool(AActor *)> &Predicate)
Count number of selected Actors that pass predicate.
INTERACTIVETOOLSFRAMEWORK_API int CountComponents (const FToolBuilderState &InputState, const TFunction< bool(UActorComponent *)> &Predicate)
Count number of selected components that pass predicate.
template<typename ActorType>
int CountSelectedActorsOfType (const FToolBuilderState &InputState)
Count number of selected Actors of given type.
template<typename ComponentType>
int CountSelectedComponentsOfType (const FToolBuilderState &InputState)
Count number of components of given type.
INTERACTIVETOOLSFRAMEWORK_API void EnumerateComponents (const FToolBuilderState &InputState, TFunctionRef< void(UActorComponent *)> ComponentFunc)
INTERACTIVETOOLSFRAMEWORK_API TArray< AActor * > FindAllActors (const FToolBuilderState &InputState, const TFunction< bool(AActor *)> &Predicate)
First all Actors that pass predicate.
INTERACTIVETOOLSFRAMEWORK_API TArray< UActorComponent * > FindAllComponents (const FToolBuilderState &InputState, const TFunction< bool(UActorComponent *)> &Predicate)
First all components that passes predicate.
INTERACTIVETOOLSFRAMEWORK_API AActor * FindFirstActor (const FToolBuilderState &InputState, const TFunction< bool(AActor *)> &Predicate)
First first available Actor that passes predicate.
template<typename ActorType>
ActorType * FindFirstActorOfType (const FToolBuilderState &InputState)
Find first first available Actor of given type, or return nullptr if not found.
INTERACTIVETOOLSFRAMEWORK_API UActorComponent * FindFirstComponent (const FToolBuilderState &InputState, const TFunction< bool(UActorComponent *)> &Predicate)
First first available component that passes predicate.
template<typename ComponentType>
ComponentType * FindFirstComponentOfType (const FToolBuilderState &InputState)
First first available component of given type.
INTERACTIVETOOLSFRAMEWORK_API bool IsVolume (const UActorComponent &Component)
Determine if component is a volume or not.
Detailed Description
Helper functions that can be used in InteractiveToolBuilder implementations.
Function Documentation
ComponentTypeCouldHaveUVs()
INTERACTIVETOOLSFRAMEWORK_API bool ToolBuilderUtil::ComponentTypeCouldHaveUVs (const UActorComponent & Component)
Determine if component support UVs.
References Component.
CountActors()
INTERACTIVETOOLSFRAMEWORK_API int32 ToolBuilderUtil::CountActors (const FToolBuilderState & InputState, const TFunction< bool(AActor *)> & Predicate)
Count number of selected Actors that pass predicate.
References Predicate.
Referenced by CountSelectedActorsOfType().
CountComponents()
INTERACTIVETOOLSFRAMEWORK_API int ToolBuilderUtil::CountComponents (const FToolBuilderState & InputState, const TFunction< bool(UActorComponent *)> & Predicate)
Count number of selected components that pass predicate.
If Component selection is not empty, returns that count, otherwise counts in all selected Actors
References Predicate.
Referenced by CountSelectedComponentsOfType().
CountSelectedActorsOfType()
template<typename ActorType> int ToolBuilderUtil::CountSelectedActorsOfType (const FToolBuilderState & InputState)
Count number of selected Actors of given type.
Definition at line 86 of file ToolBuilderUtil.h.
References Actor, Cast(), and CountActors().
CountSelectedComponentsOfType()
template<typename ComponentType> int ToolBuilderUtil::CountSelectedComponentsOfType (const FToolBuilderState & InputState)
Count number of components of given type.
If Component selection is not empty, returns that count, otherwise counts in all selected Actors
Definition at line 74 of file ToolBuilderUtil.h.
References Cast(), Component, and CountComponents().
EnumerateComponents()
INTERACTIVETOOLSFRAMEWORK_API void ToolBuilderUtil::EnumerateComponents (const FToolBuilderState & InputState, TFunctionRef< void(UActorComponent *)> ComponentFunc)
FindAllActors()
INTERACTIVETOOLSFRAMEWORK_API TArray< AActor * > ToolBuilderUtil::FindAllActors (const FToolBuilderState & InputState, const TFunction< bool(AActor *)> & Predicate)
First all Actors that pass predicate.
Searches Actors selection list.
References Predicate.
FindAllComponents()
INTERACTIVETOOLSFRAMEWORK_API TArray< UActorComponent * > ToolBuilderUtil::FindAllComponents (const FToolBuilderState & InputState, const TFunction< bool(UActorComponent *)> & Predicate)
First all components that passes predicate.
Searches Components selection list first, then all Actors
References Predicate.
FindFirstActor()
INTERACTIVETOOLSFRAMEWORK_API AActor * ToolBuilderUtil::FindFirstActor (const FToolBuilderState & InputState, const TFunction< bool(AActor *)> & Predicate)
First first available Actor that passes predicate.
Searches Actors selection list.
References Predicate.
Referenced by FindFirstActorOfType().
FindFirstActorOfType()
template<typename ActorType> ActorType * ToolBuilderUtil::FindFirstActorOfType (const FToolBuilderState & InputState)
Find first first available Actor of given type, or return nullptr if not found.
Definition at line 92 of file ToolBuilderUtil.h.
References Actor, Cast(), FindFirstActor(), and Found.
FindFirstComponent()
INTERACTIVETOOLSFRAMEWORK_API UActorComponent * ToolBuilderUtil::FindFirstComponent (const FToolBuilderState & InputState, const TFunction< bool(UActorComponent *)> & Predicate)
First first available component that passes predicate.
Searches Components selection list first, then all Actors
References Predicate.
Referenced by FindFirstComponentOfType().
FindFirstComponentOfType()
template<typename ComponentType> ComponentType * ToolBuilderUtil::FindFirstComponentOfType (const FToolBuilderState & InputState)
First first available component of given type.
Searches Components selection list first, then all Actors
Definition at line 80 of file ToolBuilderUtil.h.
References Cast(), Component, and FindFirstComponent().
IsVolume()
INTERACTIVETOOLSFRAMEWORK_API bool ToolBuilderUtil::IsVolume (const UActorComponent & Component)
Determine if component is a volume or not.
References Component.