Unreal Engine 5.6 C++ API: FObjectReplicator Class Reference
FObjectReplicator Class Reference
Represents an object that is currently being replicated or handling RPCs.
#include "DataReplication.h"
Data Structures
struct FRPCCallInfo
struct FRPCPendingLocalCall
Public Member Functions
FObjectReplicator ()
~FObjectReplicator ()
void CallRepNotifies (bool bSkipIfChannelHasQueuedBunches)
bool CanSkipUpdate (FReplicationFlags Flags)
void CleanUp ()
void CountBytes (FArchive &Ar) const
void ForceRefreshUnreliableProperties ()
FORCEINLINE UObject * GetObject () const
FORCEINLINE TWeakObjectPtr< UObject > GetWeakObjectPtr () const
void InitRecentProperties (uint8 *Source)
Recent/dirty related functions.
void InitWithObject (UObject *InObject, UNetConnection *InConnection, bool bUseDefaultState=true)
bool IsDirtyForReplay () const
bool MoveMappedObjectToUnmapped (const FNetworkGUID &GUID)
FORCEINLINE void PostNetReceive ()
void PostReceivedBunch ()
void PostSendBunch (FPacketIdRange &PacketRange, uint8 bReliable)
FORCEINLINE void PreNetReceive ()
void QueuePropertyRepNotify (UObject *Object, FProperty *Property, const int32 ElementIndex, TArray< uint8 > &MetaData)
void QueueRemoteFunctionBunch (UFunction *Func, FOutBunch &Bunch)
bool ReadyForDormancy (bool bDebug=false)
bool ReceivedBunch (FNetBitReader &Bunch, const FReplicationFlags &RepFlags, const bool bHasRepLayout, bool &bOutHasUnmapped)
void ReceivedNak (int32 NakPacketId)
Packet was dropped.
bool ReceivedRPC (FNetBitReader &Reader, const FReplicationFlags &RepFlags, const FFieldNetCache *FieldCache, const bool bCanDelayRPC, bool &bOutDelayRPC, TSet< FNetworkGUID > &OutUnmappedGuids)
void ReleaseStrongReference ()
void ReplicateCustomDeltaProperties (FNetBitWriter &Bunch, FReplicationFlags RepFlags, bool &bSkippedPropertyCondition)
bool ReplicateProperties (FOutBunch &Bunch, FReplicationFlags RepFlags)
bool ReplicateProperties (FOutBunch &Bunch, FReplicationFlags RepFlags, FNetBitWriter &Writer)
bool ReplicateProperties_r (FOutBunch &Bunch, FReplicationFlags RepFlags, FNetBitWriter &Writer)
void ResetReplayDirtyTracking ()
bool SendCustomDeltaProperty (UObject *InObject, uint16 CustomDeltaProperty, FNetBitWriter &OutBunch, TSharedPtr< INetDeltaBaseState > &NewFullState, TSharedPtr< INetDeltaBaseState > &OldState)
FORCEINLINE void SetObject (UObject *NewObj)
void StartBecomingDormant ()
void StartReplicating (class UActorChannel *InActorChannel)
void StopReplicating (class UActorChannel *InActorChannel)
void UpdateGuidToReplicatorMap ()
void UpdateUnmappedObjects (bool &bOutHasMoreUnmapped)
bool ValidateAgainstState (const UObject *ObjectState)
Takes Data, and compares against shadow state to log differences.
void WritePropertyHeaderAndPayload (UObject *Object, FProperty *Property, FNetFieldExportGroup *NetFieldExportGroup, FNetBitWriter &Bunch, FNetBitWriter &Payload) const
Data Fields
uint32 bForceUpdateUnmapped: 1
True if we need to do an unmapped check next frame.
uint32 bHasReplicatedProperties: 1
Whether or not we've already replicated properties this frame.
uint32 bLastUpdateEmpty: 1
True if last update (ReplicateActor) produced no replicated properties.
uint32 bOpenAckCalled: 1
Whether or not the Actor Channel on which we're replicating has been Opened / Acked by the receiver.
uint32 bSentSubObjectCreation: 1
Is this a subobject replicator and have we sent the creation data yet.
TSharedPtr< class FReplicationChangelistMgr > ChangelistMgr
TUniquePtr< FRepState > CheckpointRepState
UNetConnection * Connection
Connection this replicator was created on.
TObjectPtr< UClass > ObjectClass
FNetworkGUID ObjectNetGUID
Net GUID for the object we're replicating.
UObject * ObjectPtr
class UActorChannel * OwningChannel
The Actor Channel that we're replicating on.
TArray< FRPCPendingLocalCall > PendingLocalRPCs
Information on RPCs that have been received but not yet executed.
TSet< FNetworkGUID > ReferencedGuids
TArray< FRPCCallInfo > RemoteFuncInfo
Meta information on pending net RPCs (to be sent)
FOutBunch * RemoteFunctions
TSharedPtr< FRepLayout > RepLayout
TUniquePtr< FRepState > RepState
int32 TrackedGuidMemoryBytes
The amount of memory (in bytes) that we're using to track Unmapped GUIDs.
Static Private Member Functions
static void CallProcessEventForReceivedRPC (UObject *Object, UFunction *Function, uint8 *Params)
Private Attributes
uint32 bCanUseNonDirtyOptimization: 1
Whether or not this object replicator is eligible to skip replication calls based on simple flag checks.
uint32 bDirtyForReplay: 1
Used to track if we've replicated this object into a checkpoint.
uint32 bSupportsFastArrayDelta: 1
Whether or not we are going to use Fast Array Delta Struct Delta Serialization.
TWeakObjectPtr< UObject > WeakObjectPtr
Detailed Description
Represents an object that is currently being replicated or handling RPCs.
|----------------|
| NetGUID ObjRef |
    |----------------|
 |                |
| Properties...  |
|                |
| RPCs...        |
 |                |
 |----------------|
| </End Tag>     |
|----------------|
Definition at line 73 of file DataReplication.h.
Constructor & Destructor Documentation
FObjectReplicator()
FObjectReplicator::FObjectReplicator ()
~FObjectReplicator()
FObjectReplicator::~FObjectReplicator ()
Member Function Documentation
CallProcessEventForReceivedRPC()
void FObjectReplicator::CallProcessEventForReceivedRPC (UObject * Object, UFunction * Function, uint8 * Params) static private
References Function, Object, and Params.
CallRepNotifies()
void FObjectReplicator::CallRepNotifies (bool bSkipIfChannelHasQueuedBunches)
CanSkipUpdate()
bool FObjectReplicator::CanSkipUpdate (FReplicationFlags Flags)
Returns
True if we've determined nothing needs to be updated / resent by the replicator, meaning we can safely skip updating it this frame.
References Flags.
CleanUp()
void FObjectReplicator::CleanUp ()
CountBytes()
void FObjectReplicator::CountBytes (FArchive & Ar) const
References Ar.
ForceRefreshUnreliableProperties()
void FObjectReplicator::ForceRefreshUnreliableProperties ()
GetObject()
FORCEINLINE UObject * FObjectReplicator::GetObject () const inline
Definition at line 196 of file DataReplication.h.
References FORCEINLINE, ObjectPtr, and WeakObjectPtr.
Referenced by PostNetReceive(), and PreNetReceive().
GetWeakObjectPtr()
FORCEINLINE TWeakObjectPtr< UObject > FObjectReplicator::GetWeakObjectPtr () const inline
Definition at line 191 of file DataReplication.h.
References FORCEINLINE, and WeakObjectPtr.
InitRecentProperties()
void FObjectReplicator::InitRecentProperties (uint8 * Source)
Recent/dirty related functions.
References Source.
InitWithObject()
void FObjectReplicator::InitWithObject (UObject * InObject, UNetConnection * InConnection, bool bUseDefaultState = true)
IsDirtyForReplay()
bool FObjectReplicator::IsDirtyForReplay () const inline
Definition at line 250 of file DataReplication.h.
References bDirtyForReplay.
MoveMappedObjectToUnmapped()
bool FObjectReplicator::MoveMappedObjectToUnmapped (const FNetworkGUID & GUID)
PostNetReceive()
FORCEINLINE void FObjectReplicator::PostNetReceive () inline
Definition at line 222 of file DataReplication.h.
References FORCEINLINE, GetObject(), and Object.
PostReceivedBunch()
void FObjectReplicator::PostReceivedBunch ()
PostSendBunch()
void FObjectReplicator::PostSendBunch (FPacketIdRange & PacketRange, uint8 bReliable)
PreNetReceive()
FORCEINLINE void FObjectReplicator::PreNetReceive () inline
Definition at line 213 of file DataReplication.h.
References FORCEINLINE, GetObject(), and Object.
QueuePropertyRepNotify()
void FObjectReplicator::QueuePropertyRepNotify (UObject * Object, FProperty * Property, const int32 ElementIndex, TArray< uint8 > & MetaData)
References MetaData, Object, and Property.
QueueRemoteFunctionBunch()
void FObjectReplicator::QueueRemoteFunctionBunch (UFunction * Func, FOutBunch & Bunch)
ReadyForDormancy()
bool FObjectReplicator::ReadyForDormancy (bool bDebug = false)
ReceivedBunch()
bool FObjectReplicator::ReceivedBunch (FNetBitReader & Bunch, const FReplicationFlags & RepFlags, const bool bHasRepLayout, bool & bOutHasUnmapped)
ReceivedNak()
void FObjectReplicator::ReceivedNak (int32 NakPacketId)
Packet was dropped.
ReceivedRPC()
bool FObjectReplicator::ReceivedRPC (FNetBitReader & Reader, const FReplicationFlags & RepFlags, const FFieldNetCache * FieldCache, const bool bCanDelayRPC, bool & bOutDelayRPC, TSet< FNetworkGUID > & OutUnmappedGuids)
ReleaseStrongReference()
void FObjectReplicator::ReleaseStrongReference () inline
Definition at line 208 of file DataReplication.h.
References ObjectPtr.
ReplicateCustomDeltaProperties()
void FObjectReplicator::ReplicateCustomDeltaProperties (FNetBitWriter & Bunch, FReplicationFlags RepFlags, bool & bSkippedPropertyCondition)
ReplicateProperties() [1/2]
bool FObjectReplicator::ReplicateProperties (FOutBunch & Bunch, FReplicationFlags RepFlags)
ReplicateProperties() [2/2]
bool FObjectReplicator::ReplicateProperties (FOutBunch & Bunch, FReplicationFlags RepFlags, FNetBitWriter & Writer)
ReplicateProperties_r()
bool FObjectReplicator::ReplicateProperties_r (FOutBunch & Bunch, FReplicationFlags RepFlags, FNetBitWriter & Writer)
ResetReplayDirtyTracking()
void FObjectReplicator::ResetReplayDirtyTracking () inline
Definition at line 251 of file DataReplication.h.
References bDirtyForReplay.
SendCustomDeltaProperty()
bool FObjectReplicator::SendCustomDeltaProperty (UObject * InObject, uint16 CustomDeltaProperty, FNetBitWriter & OutBunch, TSharedPtr< INetDeltaBaseState > & NewFullState, TSharedPtr< INetDeltaBaseState > & OldState)
SetObject()
FORCEINLINE void FObjectReplicator::SetObject (UObject * NewObj) inline
Definition at line 202 of file DataReplication.h.
References FORCEINLINE, ObjectPtr, and WeakObjectPtr.
StartBecomingDormant()
void FObjectReplicator::StartBecomingDormant ()
StartReplicating()
void FObjectReplicator::StartReplicating (class UActorChannel * InActorChannel)
StopReplicating()
void FObjectReplicator::StopReplicating (class UActorChannel * InActorChannel)
UpdateGuidToReplicatorMap()
void FObjectReplicator::UpdateGuidToReplicatorMap ()
UpdateUnmappedObjects()
void FObjectReplicator::UpdateUnmappedObjects (bool & bOutHasMoreUnmapped)
ValidateAgainstState()
bool FObjectReplicator::ValidateAgainstState (const UObject * ObjectState)
Takes Data, and compares against shadow state to log differences.
WritePropertyHeaderAndPayload()
void FObjectReplicator::WritePropertyHeaderAndPayload (UObject * Object, FProperty * Property, FNetFieldExportGroup * NetFieldExportGroup, FNetBitWriter & Bunch, FNetBitWriter & Payload) const
References Object, and Property.
Field Documentation
bCanUseNonDirtyOptimization
uint32 FObjectReplicator::bCanUseNonDirtyOptimization private
Whether or not this object replicator is eligible to skip replication calls based on simple flag checks.
Definition at line 285 of file DataReplication.h.
bDirtyForReplay
uint32 FObjectReplicator::bDirtyForReplay private
Used to track if we've replicated this object into a checkpoint.
Definition at line 288 of file DataReplication.h.
Referenced by IsDirtyForReplay(), and ResetReplayDirtyTracking().
bForceUpdateUnmapped
uint32 FObjectReplicator::bForceUpdateUnmapped
True if we need to do an unmapped check next frame.
Definition at line 268 of file DataReplication.h.
bHasReplicatedProperties
uint32 FObjectReplicator::bHasReplicatedProperties
Whether or not we've already replicated properties this frame.
Definition at line 271 of file DataReplication.h.
bLastUpdateEmpty
uint32 FObjectReplicator::bLastUpdateEmpty
True if last update (ReplicateActor) produced no replicated properties.
Definition at line 262 of file DataReplication.h.
bOpenAckCalled
uint32 FObjectReplicator::bOpenAckCalled
Whether or not the Actor Channel on which we're replicating has been Opened / Acked by the receiver.
Definition at line 265 of file DataReplication.h.
bSentSubObjectCreation
uint32 FObjectReplicator::bSentSubObjectCreation
Is this a subobject replicator and have we sent the creation data yet.
Definition at line 274 of file DataReplication.h.
bSupportsFastArrayDelta
uint32 FObjectReplicator::bSupportsFastArrayDelta private
Whether or not we are going to use Fast Array Delta Struct Delta Serialization.
See FFastArraySerializer::FastArrayDeltaSerialize_DeltaSerializeStructs.
Definition at line 279 of file DataReplication.h.
ChangelistMgr
TSharedPtr<class FReplicationChangelistMgr> FObjectReplicator::ChangelistMgr
Definition at line 292 of file DataReplication.h.
CheckpointRepState
TUniquePtr<FRepState> FObjectReplicator::CheckpointRepState
Definition at line 295 of file DataReplication.h.
Connection
UNetConnection* FObjectReplicator::Connection
Connection this replicator was created on.
Definition at line 302 of file DataReplication.h.
ObjectClass
TObjectPtr<UClass> FObjectReplicator::ObjectClass
Definition at line 297 of file DataReplication.h.
ObjectNetGUID
FNetworkGUID FObjectReplicator::ObjectNetGUID
Net GUID for the object we're replicating.
Definition at line 256 of file DataReplication.h.
ObjectPtr
UObject* FObjectReplicator::ObjectPtr
Definition at line 299 of file DataReplication.h.
Referenced by GetObject(), ReleaseStrongReference(), and SetObject().
OwningChannel
class UActorChannel* FObjectReplicator::OwningChannel
The Actor Channel that we're replicating on.
This expected to be owned by Connection.
Definition at line 305 of file DataReplication.h.
PendingLocalRPCs
TArray<FRPCPendingLocalCall> FObjectReplicator::PendingLocalRPCs
Information on RPCs that have been received but not yet executed.
Definition at line 313 of file DataReplication.h.
ReferencedGuids
TSet<FNetworkGUID> FObjectReplicator::ReferencedGuids
Definition at line 319 of file DataReplication.h.
RemoteFuncInfo
TArray<FRPCCallInfo> FObjectReplicator::RemoteFuncInfo
Meta information on pending net RPCs (to be sent)
Definition at line 310 of file DataReplication.h.
RemoteFunctions
FOutBunch* FObjectReplicator::RemoteFunctions
Definition at line 307 of file DataReplication.h.
RepLayout
TSharedPtr<FRepLayout> FObjectReplicator::RepLayout
Definition at line 293 of file DataReplication.h.
RepState
TUniquePtr<FRepState> FObjectReplicator::RepState
Definition at line 294 of file DataReplication.h.
TrackedGuidMemoryBytes
int32 FObjectReplicator::TrackedGuidMemoryBytes
The amount of memory (in bytes) that we're using to track Unmapped GUIDs.
Definition at line 259 of file DataReplication.h.
WeakObjectPtr
TWeakObjectPtr<UObject> FObjectReplicator::WeakObjectPtr private
Definition at line 322 of file DataReplication.h.
Referenced by GetObject(), GetWeakObjectPtr(), and SetObject().
The documentation for this class was generated from the following file:
DataReplication.h