Unreal Engine 5.6 C++ API: Metasound::FMetasoundEnvironment Class Reference
Metasound::FMetasoundEnvironment Class Reference
FMetasoundEnvironment contains a set of TMetasoundEnvironmentVariables requiring that each environment variable has a unique name.
#include "MetasoundEnvironment.h"
Public Types
using FRangedForConstIteratorType = TSortedMap<FName, TUniquePtr<IMetasoundEnvironmentVariable>, FDefaultAllocator, FNameFastLess>::RangedForConstIteratorType
Public Member Functions
FMetasoundEnvironment ()=default
METASOUNDGRAPHCORE_API FMetasoundEnvironment (const FMetasoundEnvironment &InOther)
~FMetasoundEnvironment ()=default
FRangedForConstIteratorType begin () const
template<typename VarType>
bool Contains (const FName &InVariableName) const
Returns true if the environment contains a variable with the name InVariableName and the type VarType.
FRangedForConstIteratorType end () const
template<typename VarType>
VarType GetValue (const FName &InVariableName) const
Returns the environment variable data.
template<typename VarType>
bool IsType (const FName &InVariableName) const
Returns true if the environment variable with the given name contains the data of the same type as VarType
METASOUNDGRAPHCORE_API FMetasoundEnvironment & operator= (const FMetasoundEnvironment &InOther)
template<typename VarType>
void SetValue (const FName &InVariableName, const VarType &InValue)
Sets the environment variable data.
void SetValue (TUniquePtr< IMetasoundEnvironmentVariable > InValue)
Sets the environment variable data from a given environment variable.
Private Attributes
TSortedMap< FName, TUniquePtr< IMetasoundEnvironmentVariable >, FDefaultAllocator, FNameFastLess > Variables
Detailed Description
FMetasoundEnvironment contains a set of TMetasoundEnvironmentVariables requiring that each environment variable has a unique name.
Definition at line 187 of file MetasoundEnvironment.h.
Member Typedef Documentation
FRangedForConstIteratorType
using Metasound::FMetasoundEnvironment::FRangedForConstIteratorType = TSortedMap<FName, TUniquePtr<IMetasoundEnvironmentVariable>, FDefaultAllocator, FNameFastLess>::RangedForConstIteratorType
Definition at line 266 of file MetasoundEnvironment.h.
Constructor & Destructor Documentation
FMetasoundEnvironment() [1/2]
Metasound::FMetasoundEnvironment::FMetasoundEnvironment () default
Referenced by FMetasoundEnvironment(), and operator=().
~FMetasoundEnvironment()
Metasound::FMetasoundEnvironment::~FMetasoundEnvironment () default
FMetasoundEnvironment() [2/2]
METASOUNDGRAPHCORE_API Metasound::FMetasoundEnvironment::FMetasoundEnvironment (const FMetasoundEnvironment & InOther)
References FMetasoundEnvironment(), and UE_API.
Member Function Documentation
begin()
FRangedForConstIteratorType Metasound::FMetasoundEnvironment::begin () const inline
Definition at line 267 of file MetasoundEnvironment.h.
References Variables.
Contains()
template<typename VarType> bool Metasound::FMetasoundEnvironment::Contains (const FName & InVariableName) const inline
Returns true if the environment contains a variable with the name InVariableName and the type VarType.
Parameters
InVariableName - Name of environment variable.
Template Parameters
VarType - Type of the underlying data stored in the environment variable.
Definition at line 216 of file MetasoundEnvironment.h.
References IsType(), and Variables.
Referenced by Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), GetValue(), Metasound::TArrayRandomGetOperator< ArrayType >::Reset(), and Metasound::TArrayShuffleOperator< ArrayType >::Reset().
end()
FRangedForConstIteratorType Metasound::FMetasoundEnvironment::end () const inline
Definition at line 272 of file MetasoundEnvironment.h.
References Variables.
GetValue()
template<typename VarType> VarType Metasound::FMetasoundEnvironment::GetValue (const FName & InVariableName) const inline
Returns the environment variable data.
Parameters
InVariableName - Name of environment variable.
Template Parameters
VarType - Type of the underlying data stored in the environment variable.
Returns
copy of the underlying data.
Definition at line 233 of file MetasoundEnvironment.h.
References Metasound::CastMetasoundEnvironmentVariableChecked(), Contains(), ensure, Metasound::TMetasoundEnvironmentVariable< Type >::GetValue(), and Variables.
Referenced by Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), Metasound::TArrayRandomGetOperator< ArrayType >::Reset(), and Metasound::TArrayShuffleOperator< ArrayType >::Reset().
IsType()
template<typename VarType> bool Metasound::FMetasoundEnvironment::IsType (const FName & InVariableName) const inline
Returns true if the environment variable with the given name contains the data of the same type as VarType
Parameters
InVariableName - Name of environment variable.
Template Parameters
VarType - Type of the underlying data stored in the environment variable.
Definition at line 204 of file MetasoundEnvironment.h.
References Metasound::IsEnvironmentVariableOfType(), and Variables.
Referenced by Contains().
operator=()
METASOUNDGRAPHCORE_API FMetasoundEnvironment & Metasound::FMetasoundEnvironment::operator= (const FMetasoundEnvironment & InOther)
References FMetasoundEnvironment(), and UE_API.
SetValue() [1/2]
template<typename VarType> void Metasound::FMetasoundEnvironment::SetValue (const FName & InVariableName, const VarType & InValue) inline
Sets the environment variable data.
Parameters
InVariableName - Name of environment variable.
Template Parameters
VarType - Type of the underlying data stored in the environment variable.
Returns
const ref to the underlying data.
Definition at line 252 of file MetasoundEnvironment.h.
References MakeUnique(), and Variables.
SetValue() [2/2]
void Metasound::FMetasoundEnvironment::SetValue (TUniquePtr< IMetasoundEnvironmentVariable > InValue) inline
Sets the environment variable data from a given environment variable.
Parameters
InValue - Environment variable to set.
Definition at line 261 of file MetasoundEnvironment.h.
References MoveTemp(), and Variables.
Field Documentation
Variables
TSortedMap<FName, TUniquePtr<IMetasoundEnvironmentVariable>, FDefaultAllocator, FNameFastLess> Metasound::FMetasoundEnvironment::Variables private
Definition at line 278 of file MetasoundEnvironment.h.
Referenced by begin(), Contains(), end(), GetValue(), IsType(), SetValue(), and SetValue().
The documentation for this class was generated from the following file:
MetasoundEnvironment.h