Unreal Engine 5.6 C++ API: TSimpleCellGrid< CellType, InvalidCellValue > Struct Template Reference
TSimpleCellGrid< CellType, InvalidCellValue > Struct Template Reference
No virtuals on purpose.
#include "SimpleCellGrid.h"
Public Types
typedef CellType FCellType
Public Member Functions
TSimpleCellGrid ()
void AllocateMemory ()
void CleanUp ()
void FreeMemory ()
FORCEINLINE uint32 GetAllocatedSize () const
FCellType & GetCellAtCoordsUnsafe (int32 LocationX, int32 LocationY)
const FCellType & GetCellAtCoordsUnsafe (int32 LocationX, int32 LocationY) const
FORCEINLINE FCellType & GetCellAtIndexUnsafe (int32 CellIndex)
FORCEINLINE const FCellType & GetCellAtIndexUnsafe (int32 CellIndex) const
const FCellType & GetCellAtWorldLocation (const FVector &WorldLocation) const
const FCellType & GetCellAtWorldLocationUnsafe (const FVector &WorldLocation) const
FIntVector GetCellCoords (const FVector &WorldLocation) const
Convert world location to (X,Y) coords on grid, result is clamped to grid.
FORCEINLINE FIntVector GetCellCoords (int32 CellIndex) const
Convert cell index to (X,Y) coords on grid.
FORCEINLINE FIntVector GetCellCoordsUnsafe (const FVector &WorldLocation) const
Convert world location to (X,Y) coords on grid, result can be outside grid.
FORCEINLINE int32 GetCellCoordX (int32 CellIndex) const
Convert cell index to coord X on grid, result can be invalid.
FORCEINLINE int32 GetCellCoordY (int32 CellIndex) const
Convert cell index to coord Y on grid, result can be invalid.
int32 GetCellIndex (const FVector &WorldLocation) const
Convert world location to cell index, returns -1 for position outside grid.
FORCEINLINE int32 GetCellIndex (int32 LocationX, int32 LocationY) const
Convert (X,Y) coords on grid to cell index, returns -1 for position outside grid.
FORCEINLINE int32 GetCellIndexUnsafe (const FIntVector &CellCoords) const
Convert (X,Y) coords on grid to cell index, result can be invalid.
int32 GetCellIndexUnsafe (const FVector &WorldLocation) const
Convert world location to cell index, result can be invalid.
FORCEINLINE int32 GetCellIndexUnsafe (int32 LocationX, int32 LocationY) const
Convert (X,Y) coords on grid to cell index, result can be invalid.
FORCEINLINE FIntRect GetCellRectangleFromBox (const FBox &WorldBox) const
Compute a rectangle of cells overlapping the given WorldBox.
FORCEINLINE int32 GetCellsCount () const
FORCEINLINE FIntRect GetGridRectangle () const
Return an IntRect that includes all the cells of the grid.
FORCEINLINE FBox GetWorldCellBox (int32 CellIndex) const
Return the bounding box of a cell.
FORCEINLINE FBox GetWorldCellBox (int32 LocationX, int32 LocationY) const
Return the bounding box of a cell.
FORCEINLINE FBox2D GetWorldCellBox2D (int32 CellIndex) const
Return the 2D bounding box of a cell.
FORCEINLINE FBox2D GetWorldCellBox2D (int32 LocationX, int32 LocationY) const
Return the 2D bounding box of a cell.
FORCEINLINE FVector GetWorldCellCenter (int32 CellIndex) const
FORCEINLINE FVector GetWorldCellCenter (int32 LocationX, int32 LocationY) const
FORCEINLINE FBox GetWorldCellRectangleBox (const FIntRect &CellRect) const
Return the world bounding box of all cells included in the given rectangle.
bool Init (const float InCellSize, const FBox &Bounds)
Initialize the grid from a bounding box.
bool Init (const float InCellSize, const FGridSize2D &InGridSize, const FVector &InOrigin, const float VerticalBoundSize)
Initialize the grid.
FORCEINLINE bool IsValid () const
FORCEINLINE bool IsValidCoord (const FIntVector &CellCoords) const
FORCEINLINE bool IsValidCoord (int32 LocationX, int32 LocationY) const
FORCEINLINE bool IsValidIndex (const int32 CellIndex) const
FORCEINLINE int32 Num () const
FORCEINLINE FCellType & operator[] (int32 CellIndex)
FORCEINLINE const FCellType & operator[] (int32 CellIndex) const
void Serialize (FArchive &Ar)
void SetVerticalInterval (const FFloatInterval &VerticalInterval)
Change the vertical position of the grid by providing an interval.
void UpdateWorldBounds ()
void Zero ()
Data Fields
FVector BoundsSize
float GridCellSize
FGridSize2D GridSize
FVector Origin
FBox WorldBounds
Protected Attributes
TArray< FCellType > Cells
Detailed Description
template<typename CellType, int InvalidCellValue = 0>
struct TSimpleCellGrid< CellType, InvalidCellValue >
No virtuals on purpose.
Definition at line 27 of file SimpleCellGrid.h.
Member Typedef Documentation
FCellType
template<typename CellType, int InvalidCellValue = 0> typedef CellType TSimpleCellGrid< CellType, InvalidCellValue >::FCellType
Definition at line 29 of file SimpleCellGrid.h.
Constructor & Destructor Documentation
TSimpleCellGrid()
template<typename CellType, int InvalidCellValue = 0> TSimpleCellGrid< CellType, InvalidCellValue >::TSimpleCellGrid () inline
Definition at line 41 of file SimpleCellGrid.h.
References BoundsSize, ForceInitToZero, GridCellSize, Origin, and WorldBounds.
Member Function Documentation
AllocateMemory()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::AllocateMemory () inline
Definition at line 365 of file SimpleCellGrid.h.
References Cells, and GridSize.
CleanUp()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::CleanUp () inline
Definition at line 381 of file SimpleCellGrid.h.
References Cells, FVector, GridCellSize, and Origin.
FreeMemory()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::FreeMemory () inline
Definition at line 370 of file SimpleCellGrid.h.
References Cells.
GetAllocatedSize()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE uint32 TSimpleCellGrid< CellType, InvalidCellValue >::GetAllocatedSize () const inline
Definition at line 141 of file SimpleCellGrid.h.
References Cells, FORCEINLINE, and IntCastChecked().
Referenced by Serialize().
GetCellAtCoordsUnsafe() [1/2]
template<typename CellType, int InvalidCellValue = 0> FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtCoordsUnsafe (int32 LocationX, int32 LocationY) inline
Definition at line 299 of file SimpleCellGrid.h.
References GetCellAtIndexUnsafe(), and GetCellIndexUnsafe().
GetCellAtCoordsUnsafe() [2/2]
template<typename CellType, int InvalidCellValue = 0> const FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtCoordsUnsafe (int32 LocationX, int32 LocationY) const inline
Definition at line 300 of file SimpleCellGrid.h.
References GetCellAtIndexUnsafe(), and GetCellIndexUnsafe().
GetCellAtIndexUnsafe() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtIndexUnsafe (int32 CellIndex) inline
Definition at line 296 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
Referenced by GetCellAtCoordsUnsafe(), and GetCellAtCoordsUnsafe().
GetCellAtIndexUnsafe() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE const FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtIndexUnsafe (int32 CellIndex) const inline
Definition at line 297 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
GetCellAtWorldLocation()
template<typename CellType, int InvalidCellValue = 0> const FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtWorldLocation (const FVector & WorldLocation) const inline
Definition at line 286 of file SimpleCellGrid.h.
References Cells, FVector, GetCellIndex(), and INDEX_NONE.
GetCellAtWorldLocationUnsafe()
template<typename CellType, int InvalidCellValue = 0> const FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::GetCellAtWorldLocationUnsafe (const FVector & WorldLocation) const inline
Definition at line 280 of file SimpleCellGrid.h.
References Cells, FVector, and GetCellIndexUnsafe().
GetCellCoords() [1/2]
template<typename CellType, int InvalidCellValue = 0> FIntVector TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoords (const FVector & WorldLocation) const inline
Convert world location to (X,Y) coords on grid, result is clamped to grid.
Definition at line 156 of file SimpleCellGrid.h.
References FMath::Clamp(), FVector, GetCellCoordsUnsafe(), GridSize, UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
GetCellCoords() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FIntVector TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoords (int32 CellIndex) const inline
Convert cell index to (X,Y) coords on grid.
Definition at line 175 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellCoordX(), and GetCellCoordY().
GetCellCoordsUnsafe()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FIntVector TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordsUnsafe (const FVector & WorldLocation) const inline
Convert world location to (X,Y) coords on grid, result can be outside grid.
Definition at line 147 of file SimpleCellGrid.h.
References FORCEINLINE, FVector, GridCellSize, IntCastChecked(), Origin, UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Y.
Referenced by GetCellCoords(), GetCellIndex(), GetCellIndexUnsafe(), and GetCellRectangleFromBox().
GetCellCoordX()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordX (int32 CellIndex) const inline
Convert cell index to coord X on grid, result can be invalid.
Definition at line 163 of file SimpleCellGrid.h.
References FORCEINLINE, and GridSize.
Referenced by GetCellCoords(), GetWorldCellBox(), GetWorldCellBox2D(), and GetWorldCellCenter().
GetCellCoordY()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordY (int32 CellIndex) const inline
Convert cell index to coord Y on grid, result can be invalid.
Definition at line 169 of file SimpleCellGrid.h.
References FORCEINLINE, and GridSize.
Referenced by GetCellCoords(), GetWorldCellBox(), GetWorldCellBox2D(), and GetWorldCellCenter().
GetCellIndex() [1/2]
template<typename CellType, int InvalidCellValue = 0> int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellIndex (const FVector & WorldLocation) const inline
Convert world location to cell index, returns -1 for position outside grid.
Definition at line 206 of file SimpleCellGrid.h.
References FVector, GetCellCoordsUnsafe(), GetCellIndex(), UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
GetCellIndex() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellIndex (int32 LocationX, int32 LocationY) const inline
Convert (X,Y) coords on grid to cell index, returns -1 for position outside grid.
Definition at line 200 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellIndexUnsafe(), INDEX_NONE, and IsValidCoord().
Referenced by GetCellAtWorldLocation(), and GetCellIndex().
GetCellIndexUnsafe() [1/3]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellIndexUnsafe (const FIntVector & CellCoords) const inline
Convert (X,Y) coords on grid to cell index, result can be invalid.
Definition at line 188 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellIndexUnsafe(), UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
GetCellIndexUnsafe() [2/3]
template<typename CellType, int InvalidCellValue = 0> int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellIndexUnsafe (const FVector & WorldLocation) const inline
Convert world location to cell index, result can be invalid.
Definition at line 181 of file SimpleCellGrid.h.
References FVector, GetCellCoordsUnsafe(), GetCellIndexUnsafe(), UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
Referenced by GetCellAtCoordsUnsafe(), GetCellAtCoordsUnsafe(), GetCellAtWorldLocationUnsafe(), GetCellIndex(), GetCellIndexUnsafe(), and GetCellIndexUnsafe().
GetCellIndexUnsafe() [3/3]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellIndexUnsafe (int32 LocationX, int32 LocationY) const inline
Convert (X,Y) coords on grid to cell index, result can be invalid.
Definition at line 194 of file SimpleCellGrid.h.
References FORCEINLINE, and GridSize.
GetCellRectangleFromBox()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FIntRect TSimpleCellGrid< CellType, InvalidCellValue >::GetCellRectangleFromBox (const FBox & WorldBox) const inline
Compute a rectangle of cells overlapping the given WorldBox.
Definition at line 252 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellCoordsUnsafe(), UE::Math::TBox< T >::IsValid, UE::Math::TBox< T >::Max, UE::Math::TBox< T >::Min, UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
GetCellsCount()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::GetCellsCount () const inline
Definition at line 302 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
GetGridRectangle()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FIntRect TSimpleCellGrid< CellType, InvalidCellValue >::GetGridRectangle () const inline
Return an IntRect that includes all the cells of the grid.
Max is inclusive.
Definition at line 265 of file SimpleCellGrid.h.
References FORCEINLINE, and GridSize.
GetWorldCellBox() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FBox TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellBox (int32 CellIndex) const inline
Return the bounding box of a cell.
Definition at line 213 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellCoordX(), GetCellCoordY(), and GetWorldCellBox().
Referenced by GetWorldCellBox().
GetWorldCellBox() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FBox TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellBox (int32 LocationX, int32 LocationY) const inline
Return the bounding box of a cell.
Definition at line 219 of file SimpleCellGrid.h.
References BoundsSize, FORCEINLINE, FVector, GridCellSize, and Origin.
GetWorldCellBox2D() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FBox2D TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellBox2D (int32 CellIndex) const inline
Return the 2D bounding box of a cell.
Definition at line 228 of file SimpleCellGrid.h.
References FORCEINLINE, GetCellCoordX(), GetCellCoordY(), and GetWorldCellBox2D().
Referenced by GetWorldCellBox2D().
GetWorldCellBox2D() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FBox2D TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellBox2D (int32 LocationX, int32 LocationY) const inline
Return the 2D bounding box of a cell.
Definition at line 234 of file SimpleCellGrid.h.
References FORCEINLINE, GridCellSize, and Origin.
GetWorldCellCenter() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FVector TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellCenter (int32 CellIndex) const inline
Definition at line 270 of file SimpleCellGrid.h.
References FORCEINLINE, FVector, GetCellCoordX(), GetCellCoordY(), and GetWorldCellCenter().
Referenced by GetWorldCellCenter().
GetWorldCellCenter() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FVector TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellCenter (int32 LocationX, int32 LocationY) const inline
Definition at line 275 of file SimpleCellGrid.h.
References FORCEINLINE, FVector, GridCellSize, and Origin.
GetWorldCellRectangleBox()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FBox TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellRectangleBox (const FIntRect & CellRect) const inline
Return the world bounding box of all cells included in the given rectangle.
Definition at line 243 of file SimpleCellGrid.h.
References BoundsSize, FORCEINLINE, FVector, GridCellSize, UE::Math::TIntRect< InIntType >::Max, UE::Math::TIntRect< InIntType >::Min, Origin, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Init() [1/2]
template<typename CellType, int InvalidCellValue = 0> bool TSimpleCellGrid< CellType, InvalidCellValue >::Init (const float InCellSize, const FBox & Bounds) inline
Initialize the grid from a bounding box.
Parameters
InCellSize Size of a cell
Bounds Bounding box the grid needs to encapsulate
Returns
True if the grid was initialized properly
Definition at line 54 of file SimpleCellGrid.h.
References BoundsSize, Cells, ensureMsgf, FVector, UE::Math::TBox< T >::GetSize(), GridCellSize, GridSize, IntCastChecked(), UE::Math::TBox< T >::IsValid, Max, UE::Math::TBox< T >::Max, FMath::Min, UE::Math::TBox< T >::Min, Origin, TEXT, UpdateWorldBounds(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Init() [2/2]
template<typename CellType, int InvalidCellValue = 0> bool TSimpleCellGrid< CellType, InvalidCellValue >::Init (const float InCellSize, const FGridSize2D & InGridSize, const FVector & InOrigin, const float VerticalBoundSize) inline
Initialize the grid.
Parameters
InCellSize Size of a cell
InGridSize Amount of cells needed in each direction
InOrigin World location of the grid
VerticalBoundSize Size of the grid above and under the Origin
Returns
True if the grid was initialized properly
Definition at line 84 of file SimpleCellGrid.h.
References BoundsSize, Cells, ensureMsgf, FVector, GridCellSize, GridSize, FGridSize2D::Height, Max, FMath::Min, Origin, TEXT, UpdateWorldBounds(), and FGridSize2D::Width.
IsValid()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE bool TSimpleCellGrid< CellType, InvalidCellValue >::IsValid () const inline
Definition at line 121 of file SimpleCellGrid.h.
References Cells, FORCEINLINE, and GridCellSize.
IsValidCoord() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE bool TSimpleCellGrid< CellType, InvalidCellValue >::IsValidCoord (const FIntVector & CellCoords) const inline
Definition at line 136 of file SimpleCellGrid.h.
References FORCEINLINE, IsValidCoord(), UE::Math::TIntVector3< InIntType >::X, and UE::Math::TIntVector3< InIntType >::Y.
IsValidCoord() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE bool TSimpleCellGrid< CellType, InvalidCellValue >::IsValidCoord (int32 LocationX, int32 LocationY) const inline
Definition at line 131 of file SimpleCellGrid.h.
References FORCEINLINE, and GridSize.
Referenced by GetCellIndex(), and IsValidCoord().
IsValidIndex()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE bool TSimpleCellGrid< CellType, InvalidCellValue >::IsValidIndex (const int32 CellIndex) const inline
Definition at line 126 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
Num()
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE int32 TSimpleCellGrid< CellType, InvalidCellValue >::Num () const inline
Definition at line 307 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
operator[]() [1/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::operator[] (int32 CellIndex) inline
Definition at line 293 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
operator[]() [2/2]
template<typename CellType, int InvalidCellValue = 0> FORCEINLINE const FCellType & TSimpleCellGrid< CellType, InvalidCellValue >::operator[] (int32 CellIndex) const inline
Definition at line 294 of file SimpleCellGrid.h.
References Cells, and FORCEINLINE.
Serialize()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::Serialize (FArchive & Ar) inline
Definition at line 312 of file SimpleCellGrid.h.
References Ar, BoundsSize, Cells, FMath::Clamp(), ensureMsgf, GetAllocatedSize(), GridCellSize, GridSize, Max, MAX_uint32, FMath::Min, Origin, TEXT, and UpdateWorldBounds().
SetVerticalInterval()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::SetVerticalInterval (const FFloatInterval & VerticalInterval) inline
Change the vertical position of the grid by providing an interval.
Definition at line 106 of file SimpleCellGrid.h.
References BoundsSize, TInterval< ElementType >::Interpolate(), TInterval< ElementType >::IsValid(), Origin, TInterval< ElementType >::Size(), and UpdateWorldBounds().
UpdateWorldBounds()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::UpdateWorldBounds () inline
Definition at line 116 of file SimpleCellGrid.h.
References BoundsSize, FVector, Origin, and WorldBounds.
Referenced by Init(), Init(), Serialize(), and SetVerticalInterval().
Zero()
template<typename CellType, int InvalidCellValue = 0> void TSimpleCellGrid< CellType, InvalidCellValue >::Zero () inline
Definition at line 375 of file SimpleCellGrid.h.
References Cells, and GridSize.
Field Documentation
BoundsSize
template<typename CellType, int InvalidCellValue = 0> FVector TSimpleCellGrid< CellType, InvalidCellValue >::BoundsSize
Definition at line 34 of file SimpleCellGrid.h.
Referenced by TSimpleCellGrid(), GetWorldCellBox(), GetWorldCellRectangleBox(), Init(), Init(), Serialize(), SetVerticalInterval(), and UpdateWorldBounds().
Cells
template<typename CellType, int InvalidCellValue = 0> TArray<FCellType> TSimpleCellGrid< CellType, InvalidCellValue >::Cells protected
Definition at line 38 of file SimpleCellGrid.h.
Referenced by AllocateMemory(), CleanUp(), FreeMemory(), GetAllocatedSize(), GetCellAtIndexUnsafe(), GetCellAtIndexUnsafe(), GetCellAtWorldLocation(), GetCellAtWorldLocationUnsafe(), GetCellsCount(), Init(), Init(), IsValid(), IsValidIndex(), Num(), operator[](), operator[](), Serialize(), and Zero().
GridCellSize
template<typename CellType, int InvalidCellValue = 0> float TSimpleCellGrid< CellType, InvalidCellValue >::GridCellSize
Definition at line 31 of file SimpleCellGrid.h.
Referenced by TSimpleCellGrid(), CleanUp(), GetCellCoordsUnsafe(), GetWorldCellBox(), GetWorldCellBox2D(), GetWorldCellCenter(), GetWorldCellRectangleBox(), Init(), Init(), IsValid(), and Serialize().
GridSize
template<typename CellType, int InvalidCellValue = 0> FGridSize2D TSimpleCellGrid< CellType, InvalidCellValue >::GridSize
Definition at line 35 of file SimpleCellGrid.h.
Referenced by AllocateMemory(), GetCellCoords(), GetCellCoordX(), GetCellCoordY(), GetCellIndexUnsafe(), GetGridRectangle(), Init(), Init(), IsValidCoord(), Serialize(), and Zero().
Origin
template<typename CellType, int InvalidCellValue = 0> FVector TSimpleCellGrid< CellType, InvalidCellValue >::Origin
Definition at line 33 of file SimpleCellGrid.h.
Referenced by TSimpleCellGrid(), CleanUp(), GetCellCoordsUnsafe(), GetWorldCellBox(), GetWorldCellBox2D(), GetWorldCellCenter(), GetWorldCellRectangleBox(), Init(), Init(), Serialize(), SetVerticalInterval(), and UpdateWorldBounds().
WorldBounds
template<typename CellType, int InvalidCellValue = 0> FBox TSimpleCellGrid< CellType, InvalidCellValue >::WorldBounds
Definition at line 32 of file SimpleCellGrid.h.
Referenced by TSimpleCellGrid(), and UpdateWorldBounds().
The documentation for this struct was generated from the following file:
SimpleCellGrid.h