Unreal Engine 5.6 C++ API: ConstructorHelpers::FObjectFinderOptional< T > Struct Template Reference
ConstructorHelpers::FObjectFinderOptional< T > Struct Template Reference
#include "ConstructorHelpers.h"
Public Member Functions
FObjectFinderOptional (const TCHAR *InObjectToFind, uint32 InLoadFlags=LOAD_None)
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
T * Get ()
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
bool Succeeded ()
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Private Attributes
uint32 LoadFlags
TObjectPtr< T > Object
const TCHAR * ObjectToFind
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
template<class T>
struct ConstructorHelpers::FObjectFinderOptional< T >
Definition at line 106 of file ConstructorHelpers.h.
Constructor & Destructor Documentation
FObjectFinderOptional()
template<class T> ConstructorHelpers::FObjectFinderOptional< T >::FObjectFinderOptional (const TCHAR * InObjectToFind, uint32 InLoadFlags = LOAD_None) inline
Definition at line 113 of file ConstructorHelpers.h.
References LOAD_None, LoadFlags, Object, and ObjectToFind.
Member Function Documentation
AddReferencedObjects()
template<class T> virtual void ConstructorHelpers::FObjectFinderOptional< T >::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 145 of file ConstructorHelpers.h.
References Object.
Get()
template<class T> T * ConstructorHelpers::FObjectFinderOptional< T >::Get () inline
Definition at line 119 of file ConstructorHelpers.h.
References ConstructorHelpers::CheckIfIsInConstructor(), ConstructorHelpersInternal::FindOrLoadObject(), LOAD_NoWarn, LOAD_Quiet, LoadFlags, Object, ObjectToFind, ConstructorHelpers::StripObjectClass(), and ConstructorHelpers::ValidateObject().
Referenced by Succeeded().
GetReferencerName()
template<class T> virtual FString ConstructorHelpers::FObjectFinderOptional< T >::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 150 of file ConstructorHelpers.h.
References TEXT.
Succeeded()
template<class T> bool ConstructorHelpers::FObjectFinderOptional< T >::Succeeded () inline
Definition at line 140 of file ConstructorHelpers.h.
References Get().
Field Documentation
LoadFlags
template<class T> uint32 ConstructorHelpers::FObjectFinderOptional< T >::LoadFlags private
Definition at line 111 of file ConstructorHelpers.h.
Referenced by FObjectFinderOptional(), and Get().
Object
template<class T> TObjectPtr<T> ConstructorHelpers::FObjectFinderOptional< T >::Object private
Definition at line 109 of file ConstructorHelpers.h.
Referenced by FObjectFinderOptional(), AddReferencedObjects(), and Get().
ObjectToFind
template<class T> const TCHAR* ConstructorHelpers::FObjectFinderOptional< T >::ObjectToFind private
Definition at line 110 of file ConstructorHelpers.h.
Referenced by FObjectFinderOptional(), and Get().
The documentation for this struct was generated from the following file:
ConstructorHelpers.h