Unreal Engine 5.6 C++ API: FCanvasSimpleTextItem Class Reference
FCanvasSimpleTextItem Class Reference abstract
#include "CanvasItem.h"
Public Member Functions
FCanvasSimpleTextItem (const FVector2D &InPosition, const FSlateFontInfo &InFontInfo, const FLinearColor &InColor)
Constructor.
FCanvasSimpleTextItem (const FVector2D &InPosition, const UFont *InFont, const FLinearColor &InColor)
Constructor.
virtual ~FCanvasSimpleTextItem () override=default
Public Member Functions inherited from FCanvasTextItemBase
FCanvasTextItemBase (const FVector2D &InPosition, const FLinearColor &InColor)
virtual ~FCanvasTextItemBase ()
void DisableShadow ()
Disable the shadow.
virtual void Draw (FCanvas *InCanvas) override
Draw the item at the given coordinates.
virtual void Draw (FCanvas *InCanvas, const FVector2D &InPosition)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
virtual void Draw (FCanvas *InCanvas, float X, float Y)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
void EnableShadow (const FLinearColor &InColor, const FVector2D &InOffset=FVector2D(1.0f, 1.0f))
Set the shadow offset and color.
virtual void SetColor (const FLinearColor &InColor) override final
Public Member Functions inherited from FCanvasItem
FCanvasItem (const FVector2D &InPosition)
Basic render item.
virtual ~FCanvasItem ()
Data Fields
const UFont * Font
TOptional< FSlateFontInfo > SlateFontInfo
Font info to draw the text with.
Data Fields inherited from FCanvasTextItemBase
bool bCentreX
bool bCentreY
bool bDontCorrectStereoscopic
bool bOutlined
float Depth
FVector2D DrawnSize
FFontRenderInfo FontRenderInfo
float HorizSpacingAdjust
FLinearColor OutlineColor
FVector2D Scale
FLinearColor ShadowColor
FVector2D ShadowOffset
Data Fields inherited from FCanvasItem
FBatchedElementParameters * BatchedElementParameters
bool bFreezeTime
ESimpleElementBlendMode BlendMode
FVector2D Position
uint32 StereoDepth
Protected Member Functions
virtual void DrawStringInternal (FCanvas *InCanvas, const FVector2D &DrawPos, const FLinearColor &DrawColor, TArrayView< FTextEffect > Offsets) override=0
Internal string draw.
void DrawStringInternal (FCanvas *InCanvas, FStringView Text, const FVector2D &DrawPos, const FLinearColor &DrawColor, TArrayView< FTextEffect > TextEffects)
void DrawStringInternal_OfflineCache (FCanvas *InCanvas, FStringView Text, const FVector2D &DrawPos, const FLinearColor &DrawColor, TArrayView< FTextEffect > TextEffects)
Internal string draw.
void DrawStringInternal_RuntimeCache (FCanvas *InCanvas, FStringView Text, const FVector2D &DrawPos, const FLinearColor &DrawColor, TArrayView< FTextEffect > TextEffects)
EFontCacheType GetFontCacheType () const
Get the type of font cache the UFont is using.
virtual ESimpleElementBlendMode GetTextBlendMode (const bool bHasShadow) const override
Get the blend mode we should use to draw this text.
virtual FVector2D GetTextSize (float DPIScale) const override=0
Get the measured size of the text to draw.
FVector2D GetTextSizeInternal (FStringView Text, float DPIScale) const
virtual bool HasValidText () const override=0
Does this text item have valid text to draw?
Additional Inherited Members
Protected Attributes inherited from FCanvasTextItemBase
FBatchedElements * BatchedElements
These are used by the DrawStringInternal function.
FCanvasTileItem TileItem
Protected Attributes inherited from FCanvasItem
FLinearColor Color
Detailed Description
Definition at line 424 of file CanvasItem.h.
Constructor & Destructor Documentation
FCanvasSimpleTextItem() [1/2]
FCanvasSimpleTextItem::FCanvasSimpleTextItem (const FVector2D & InPosition, const UFont * InFont, const FLinearColor & InColor) inline
Constructor.
Parameters
InPosition Draw position.
InFont Font to draw with.
InColor Color to draw the text with.
Definition at line 435 of file CanvasItem.h.
References FCanvasTextItemBase::FCanvasTextItemBase(), FCanvasItem::BlendMode, Font, SE_BLEND_Translucent, and SlateFontInfo.
Referenced by FCanvasTextStringViewItem::FCanvasTextStringViewItem(), and FCanvasTextStringViewItem::FCanvasTextStringViewItem().
FCanvasSimpleTextItem() [2/2]
FCanvasSimpleTextItem::FCanvasSimpleTextItem (const FVector2D & InPosition, const FSlateFontInfo & InFontInfo, const FLinearColor & InColor) inline
Constructor.
Parameters
InPosition Draw position.
InFontInfo Font info to draw with.
InColor Color to draw the text with.
Definition at line 450 of file CanvasItem.h.
References FCanvasTextItemBase::FCanvasTextItemBase(), FCanvasItem::BlendMode, Cast(), Font, SE_BLEND_TranslucentAlphaOnly, and SlateFontInfo.
~FCanvasSimpleTextItem()
virtual FCanvasSimpleTextItem::~FCanvasSimpleTextItem () override virtual default
Member Function Documentation
DrawStringInternal() [1/2]
virtual void FCanvasSimpleTextItem::DrawStringInternal (FCanvas * InCanvas, const FVector2D & DrawPos, const FLinearColor & DrawColor, TArrayView< FTextEffect > Offsets) override protected pure virtual
Internal string draw.
In a method to make it simpler to do effects like shadow, outline
Implements FCanvasTextItemBase.
Implemented in FCanvasTextItem, and FCanvasTextStringViewItem.
DrawStringInternal() [2/2]
void FCanvasSimpleTextItem::DrawStringInternal (FCanvas * InCanvas, FStringView Text, const FVector2D & DrawPos, const FLinearColor & DrawColor, TArrayView< FTextEffect > TextEffects) protected
References Text.
DrawStringInternal_OfflineCache()
void FCanvasSimpleTextItem::DrawStringInternal_OfflineCache (FCanvas * InCanvas, FStringView Text, const FVector2D & DrawPos, const FLinearColor & DrawColor, TArrayView< FTextEffect > TextEffects) protected
Internal string draw.
In a method to make it simpler to do effects like shadow, outline
References Text.
DrawStringInternal_RuntimeCache()
void FCanvasSimpleTextItem::DrawStringInternal_RuntimeCache (FCanvas * InCanvas, FStringView Text, const FVector2D & DrawPos, const FLinearColor & DrawColor, TArrayView< FTextEffect > TextEffects) protected
References Text.
GetFontCacheType()
EFontCacheType FCanvasSimpleTextItem::GetFontCacheType () const protected
Get the type of font cache the UFont is using.
GetTextBlendMode()
virtual ESimpleElementBlendMode FCanvasSimpleTextItem::GetTextBlendMode (const bool bHasShadow) const override protected virtual
Get the blend mode we should use to draw this text.
Implements FCanvasTextItemBase.
GetTextSize()
virtual FVector2D FCanvasSimpleTextItem::GetTextSize (float DPIScale) const override protected pure virtual
Get the measured size of the text to draw.
Implements FCanvasTextItemBase.
Implemented in FCanvasTextItem, and FCanvasTextStringViewItem.
GetTextSizeInternal()
FVector2D FCanvasSimpleTextItem::GetTextSizeInternal (FStringView Text, float DPIScale) const protected
References Text.
HasValidText()
virtual bool FCanvasSimpleTextItem::HasValidText () const override protected pure virtual
Does this text item have valid text to draw?
Implements FCanvasTextItemBase.
Implemented in FCanvasTextItem, and FCanvasTextStringViewItem.
Field Documentation
Font
const UFont* FCanvasSimpleTextItem::Font
Definition at line 461 of file CanvasItem.h.
Referenced by FCanvasSimpleTextItem(), and FCanvasSimpleTextItem().
SlateFontInfo
TOptional<FSlateFontInfo> FCanvasSimpleTextItem::SlateFontInfo
Font info to draw the text with.
Definition at line 464 of file CanvasItem.h.
Referenced by FCanvasSimpleTextItem(), and FCanvasSimpleTextItem().
The documentation for this class was generated from the following file:
CanvasItem.h