Unreal Engine 5.6 C++ API: FIdentityPrimitiveUniformBuffer Class Reference
FIdentityPrimitiveUniformBuffer Class Reference
Primitive uniform buffer containing only identity transforms.
#include "PrimitiveUniformShaderParameters.h"
Public Member Functions
void InitContents ()
Public Member Functions inherited from TUniformBuffer< FPrimitiveUniformShaderParameters >
TUniformBuffer ()
~TUniformBuffer ()
const uint8 * GetContents () const
const TUniformBufferRef< FPrimitiveUniformShaderParameters > & GetUniformBufferRef () const
FRHIUniformBuffer * GetUniformBufferRHI () const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void SetContents (FRHICommandListBase &RHICmdList, const FPrimitiveUniformShaderParameters &NewContents)
Sets the contents of the uniform buffer.
void SetContentsToZero (FRHICommandListBase &RHICmdList)
Sets the contents of the uniform buffer to all zeros.
UE_DEPRECATED (5.4, "SetContents requires a command list.") void SetContents(const FPrimitiveUniformShaderParameters &NewContents)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from TUniformBuffer< FPrimitiveUniformShaderParameters >
EUniformBufferUsage BufferUsage
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from TUniformBuffer< FPrimitiveUniformShaderParameters >
void SetContentsNoUpdate (const FPrimitiveUniformShaderParameters &NewContents)
Sets the contents of the uniform buffer.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Primitive uniform buffer containing only identity transforms.
Definition at line 86 of file PrimitiveUniformShaderParameters.h.
Member Function Documentation
InitContents()
void FIdentityPrimitiveUniformBuffer::InitContents () inline
Definition at line 89 of file PrimitiveUniformShaderParameters.h.
References GetIdentityPrimitiveParameters(), FRenderResource::GetImmediateCommandList(), and TUniformBuffer< FPrimitiveUniformShaderParameters >::SetContents().
The documentation for this class was generated from the following file:
PrimitiveUniformShaderParameters.h