Unreal Engine 5.6 C++ API: Map.h File Reference
Map.h File Reference
#include "CoreTypes.h"
#include "Algo/Reverse.h"
#include "Containers/ContainerElementTypeCompatibility.h"
#include "Containers/Set.h"
#include "Containers/UnrealString.h"
#include "Misc/AssertionMacros.h"
#include "Misc/StructBuilder.h"
#include "Templates/Function.h"
#include "Templates/Sorting.h"
#include "Templates/Tuple.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include <type_traits>
Data Structures
class FScriptMap
struct FScriptMapLayout
struct TDefaultMapHashableKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >
struct TDefaultMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >
Defines how the map's pairs are hashed.
struct TIsTMap< T >
Traits class which determines whether or not a type is a TMap.
struct TIsTMap< const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > >
struct TIsTMap< const volatile TMap< KeyType, ValueType, SetAllocator, KeyFuncs > >
struct TIsTMap< TMap< KeyType, ValueType, SetAllocator, KeyFuncs > >
struct TIsTMap< volatile TMap< KeyType, ValueType, SetAllocator, KeyFuncs > >
struct TIsZeroConstructType< TScriptMap< AllocatorType > >
class TKeyInitializer< KeyInitType >
An initializer type for keys that's passed to the pair set when adding a new key.
class TMap< InKeyType, InValueType, SetAllocator, KeyFuncs >
A TMapBase specialization that only allows a single value associated with each key.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
The base class of maps from keys to values.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TBaseIterator< bConst, bRangedFor >
The base of TMapBase iterators.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TBaseKeyIterator< bConst >
The base type of iterators that iterate over the values associated with a specified key.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstIterator
Const map iterator.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstKeyIterator
Iterates over values associated with a specified key in a const map.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TIterator
Map iterator.
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TKeyIterator
Iterates over values associated with a specified key in a map.
struct TMapPrivateFriend
class TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >
A TMapBase specialization that allows multiple values to be associated with each key.
class TPairInitializer< KeyInitType, ValueInitType >
An initializer type for pairs that's passed to the pair set when adding a new pair.
class TScriptMap< AllocatorType, InDerivedType >
class TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
The base type of sortable maps.
class TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FKeyComparisonClass< PREDICATE_CLASS >
Extracts the pair's key from the map's pair structure and passes it to the user provided comparison class.
class TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FValueComparisonClass< PREDICATE_CLASS >
Extracts the pair's value from the map's pair structure and passes it to the user provided comparison class.
Namespaces
namespace Freeze
Macros
#define ExchangeB(A, B)
Functions
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs >),(TMap< KeyType, ValueType, SetAllocator, KeyFuncs >))
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs >),(TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >))
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 Freeze::IntrinsicAppendHash (const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 Freeze::IntrinsicAppendHash (const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, void *OutDst)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, void *OutDst)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, const FTypeLayoutDesc &)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, const FTypeLayoutDesc &)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
bool LegacyCompareEqual (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &A, const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &B)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
bool LegacyCompareNotEqual (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &A, const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &B)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
FORCEINLINE FArchive & operator<< (FArchive &Ar, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &Map)
Serializer.
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
FORCEINLINE void operator<< (FStructuredArchive::FSlot Slot, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &InMap)
Structured archive serializer.
Macro Definition Documentation
ExchangeB
#define ExchangeB (A, B)
Value:
{bool T=A; A=B; B=T;}
Definition at line 20 of file Map.h.
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [1/2]
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs >) , (TMap< KeyType, ValueType, SetAllocator, KeyFuncs >))
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [2/2]
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs >) , (TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs >))
LegacyCompareEqual()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool LegacyCompareEqual (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & A, const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & B) nodiscard
Definition at line 2206 of file Map.h.
References A, B, and TMapPrivateFriend::LegacyCompareEqual().
LegacyCompareNotEqual()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool LegacyCompareNotEqual (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & A, const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & B) nodiscard
Definition at line 2211 of file Map.h.
References A, B, and TMapPrivateFriend::LegacyCompareEqual().
operator<<() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE FArchive & operator<< (FArchive & Ar, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & Map)
Serializer.
Definition at line 2192 of file Map.h.
References Ar, FORCEINLINE, Map, and TMapPrivateFriend::Serialize().
operator<<() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void operator<< (FStructuredArchive::FSlot Slot, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & InMap)
Structured archive serializer.
Definition at line 2199 of file Map.h.
References FORCEINLINE, and TMapPrivateFriend::SerializeStructured().