Unreal Engine 5.6 C++ API: UE::Anim::FAttributeBlendData Struct Reference
UE::Anim::FAttributeBlendData Struct Reference
#include "AttributeBlendData.h"
Data Structures
struct FAttributeSet
Structure containing overlapping attributes.
struct FUniqueAttribute
Structure representing a unique (non-overlapping) attribute.
struct TAttributeSetIterator
struct TAttributeSetRawIterator
struct TSingleIterator
struct TSingleRawIterator
Public Member Functions
template<typename AttributeType>
void ForEachAttributeSet (TFunctionRef< void(TAttributeSetIterator< AttributeType > &)> ForEachFunction) const
void ForEachAttributeSet (TFunctionRef< void(TAttributeSetRawIterator &)> ForEachFunction) const
template<typename AttributeType>
void ForEachUniqueAttribute (TFunctionRef< void(TSingleIterator< AttributeType > &)> ForEachFunction) const
void ForEachUniqueAttribute (TFunctionRef< void(TSingleRawIterator &)> ForEachFunction) const
Static Protected Member Functions
static FAttributeBlendData PerBoneBlendSamples (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerBoneFilteredWeighted (const FStackAttributeContainer &BaseAttributes, const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerBoneRemappedBlendSamples (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, TArrayView< const int32 > InBlendSampleDataCacheIndices, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerBoneSingleContainerWeighted (const FStackAttributeContainer &SourceAttributes1, const FStackAttributeContainer &SourceAttributes2, const TArrayView< const float > WeightsOfSource2, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerBoneWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerContainerPtrWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerContainerRemappedWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData PerContainerWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData SingleAdditiveContainerUniformWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, EAdditiveAnimationType AdditiveType, const UScriptStruct *AttributeScriptStruct)
static FAttributeBlendData SingleContainerUniformWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, const UScriptStruct *AttributeScriptStruct)
Private Member Functions
FAttributeBlendData ()
FAttributeBlendData (const FStackAttributeContainer &BaseAttributes, const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const FStackAttributeContainer &SourceAttributes1, const FStackAttributeContainer &SourceAttributes2, const TArrayView< const float > WeightsOfSource2, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, EAdditiveAnimationType InAdditiveType, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, const UScriptStruct *AttributeScriptStruct)
FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, TArrayView< const int32 > InBlendSampleDataCacheIndices, const UScriptStruct *AttributeScriptStruct)
FORCEINLINE const TArrayView< const int32 > & GetBlendSampleDataCacheIndices () const
float GetBoneWeight (int32 AttributeIndex, int32 BoneIndex) const
FORCEINLINE const TArrayView< const float > & GetBoneWeights () const
float GetContainerWeight (int32 ContainerIndex) const
Retrieves the weight on a top-level container basis.
bool HasBoneWeights () const
Tests for different weight basis.
bool HasContainerWeights () const
void ProcessAttributes (const FStackAttributeContainer &AttributeContainers, int32 SourceAttributesIndex, const UScriptStruct *AttributeScriptStruct)
Private Attributes
EAdditiveAnimationType AdditiveType
Valid whenever performing an additive accumulate.
TArray< FAttributeSet > AttributeSets
Processed unique and sets of attributes.
TArrayView< const FBlendSampleData > BlendSampleDataCache
bool bPerBoneFilter = false
TArray< int32 > HighestBoneWeightedIndices
TArrayView< const int32 > PerBoneInterpolationIndices
Blend sample weight data.
TArrayView< const FPerBoneBlendWeight > PerBoneWeights
Bone level weight data.
float UniformWeight
Container level weight data.
TArray< FUniqueAttribute > UniqueAttributes
TArrayView< const int32 > WeightIndices
TArrayView< const float > Weights
Friends
struct Attributes
Detailed Description
Definition at line 12 of file AttributeBlendData.h.
Constructor & Destructor Documentation
FAttributeBlendData() [1/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct * AttributeScriptStruct) private
Referenced by PerBoneBlendSamples(), PerBoneFilteredWeighted(), PerBoneRemappedBlendSamples(), PerBoneSingleContainerWeighted(), PerBoneWeighted(), PerContainerPtrWeighted(), PerContainerRemappedWeighted(), PerContainerWeighted(), SingleAdditiveContainerUniformWeighted(), and SingleContainerUniformWeighted().
FAttributeBlendData() [2/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [3/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [4/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [5/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, EAdditiveAnimationType InAdditiveType, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [6/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [7/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [8/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, TArrayView< const int32 > InBlendSampleDataCacheIndices, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [9/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const FStackAttributeContainer & BaseAttributes, const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [10/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData (const FStackAttributeContainer & SourceAttributes1, const FStackAttributeContainer & SourceAttributes2, const TArrayView< const float > WeightsOfSource2, const UScriptStruct * AttributeScriptStruct) private
FAttributeBlendData() [11/11]
UE::Anim::FAttributeBlendData::FAttributeBlendData () private
Referenced by PerBoneBlendSamples(), PerBoneFilteredWeighted(), PerBoneRemappedBlendSamples(), PerBoneSingleContainerWeighted(), PerBoneWeighted(), PerContainerPtrWeighted(), PerContainerRemappedWeighted(), PerContainerWeighted(), SingleAdditiveContainerUniformWeighted(), and SingleContainerUniformWeighted().
Member Function Documentation
ForEachAttributeSet() [1/2]
template<typename AttributeType> void UE::Anim::FAttributeBlendData::ForEachAttributeSet (TFunctionRef< void(TAttributeSetIterator< AttributeType > &)> ForEachFunction) const inline
Definition at line 541 of file AttributeBlendData.h.
References AttributeSets.
Referenced by UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal(), and UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal().
ForEachAttributeSet() [2/2]
void UE::Anim::FAttributeBlendData::ForEachAttributeSet (TFunctionRef< void(TAttributeSetRawIterator &)> ForEachFunction) const inline
Definition at line 557 of file AttributeBlendData.h.
References AttributeSets.
ForEachUniqueAttribute() [1/2]
template<typename AttributeType> void UE::Anim::FAttributeBlendData::ForEachUniqueAttribute (TFunctionRef< void(TSingleIterator< AttributeType > &)> ForEachFunction) const inline
Definition at line 551 of file AttributeBlendData.h.
References UniqueAttributes.
Referenced by UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive_Internal(), and UE::Anim::TAttributeBlendOperator< AttributeType >::Override_Internal().
ForEachUniqueAttribute() [2/2]
void UE::Anim::FAttributeBlendData::ForEachUniqueAttribute (TFunctionRef< void(TSingleRawIterator &)> ForEachFunction) const inline
Definition at line 566 of file AttributeBlendData.h.
References UniqueAttributes.
GetBlendSampleDataCacheIndices()
FORCEINLINE const TArrayView< const int32 > & UE::Anim::FAttributeBlendData::GetBlendSampleDataCacheIndices () const inline private
Definition at line 165 of file AttributeBlendData.h.
References FORCEINLINE, and WeightIndices.
GetBoneWeight()
float UE::Anim::FAttributeBlendData::GetBoneWeight (int32 AttributeIndex, int32 BoneIndex) const private
GetBoneWeights()
FORCEINLINE const TArrayView< const float > & UE::Anim::FAttributeBlendData::GetBoneWeights () const inline private
Definition at line 159 of file AttributeBlendData.h.
References FORCEINLINE, and Weights.
GetContainerWeight()
float UE::Anim::FAttributeBlendData::GetContainerWeight (int32 ContainerIndex) const private
Retrieves the weight on a top-level container basis.
References ContainerIndex.
HasBoneWeights()
bool UE::Anim::FAttributeBlendData::HasBoneWeights () const private
Tests for different weight basis.
HasContainerWeights()
bool UE::Anim::FAttributeBlendData::HasContainerWeights () const private
PerBoneBlendSamples()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerBoneBlendSamples (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 49 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerBoneFilteredWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerBoneFilteredWeighted (const FStackAttributeContainer & BaseAttributes, const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 59 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerBoneRemappedBlendSamples()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerBoneRemappedBlendSamples (const TArrayView< const FStackAttributeContainer > SourceAttributes, TArrayView< const int32 > InPerBoneInterpolationIndices, const TArrayView< const FBlendSampleData > InBlendSampleDataCache, TArrayView< const int32 > InBlendSampleDataCacheIndices, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 54 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerBoneSingleContainerWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerBoneSingleContainerWeighted (const FStackAttributeContainer & SourceAttributes1, const FStackAttributeContainer & SourceAttributes2, const TArrayView< const float > WeightsOfSource2, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 64 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerBoneWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerBoneWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const FPerBoneBlendWeight > InPerBoneBlendWeights, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 44 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerContainerPtrWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerContainerPtrWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 22 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerContainerRemappedWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerContainerRemappedWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const TArrayView< const int32 > SourceWeightsIndices, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 27 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
PerContainerWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::PerContainerWeighted (const TArrayView< const FStackAttributeContainer > SourceAttributes, const TArrayView< const float > SourceWeights, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 17 of file AttributeBlendData.h.
References FAttributeBlendData(), and FAttributeBlendData().
ProcessAttributes()
void UE::Anim::FAttributeBlendData::ProcessAttributes (const FStackAttributeContainer & AttributeContainers, int32 SourceAttributesIndex, const UScriptStruct * AttributeScriptStruct) private
SingleAdditiveContainerUniformWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::SingleAdditiveContainerUniformWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, EAdditiveAnimationType AdditiveType, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 38 of file AttributeBlendData.h.
References FAttributeBlendData(), FAttributeBlendData(), AdditiveType, ensure, and TArrayView< InElementType, InSizeType >::Num().
SingleContainerUniformWeighted()
FAttributeBlendData UE::Anim::FAttributeBlendData::SingleContainerUniformWeighted (const TArrayView< const FStackAttributeContainer *const > SourceAttributes, const float InUniformWeight, const UScriptStruct * AttributeScriptStruct) inline static protected
Definition at line 32 of file AttributeBlendData.h.
References FAttributeBlendData(), FAttributeBlendData(), ensure, and TArrayView< InElementType, InSizeType >::Num().
Friends And Related Symbol Documentation
Attributes
friend struct Attributes friend
Definition at line 14 of file AttributeBlendData.h.
References Attributes.
Referenced by Attributes.
Field Documentation
AdditiveType
EAdditiveAnimationType UE::Anim::FAttributeBlendData::AdditiveType private
Valid whenever performing an additive accumulate.
Definition at line 154 of file AttributeBlendData.h.
Referenced by SingleAdditiveContainerUniformWeighted().
AttributeSets
TArray<FAttributeSet> UE::Anim::FAttributeBlendData::AttributeSets private
Processed unique and sets of attributes.
Definition at line 144 of file AttributeBlendData.h.
Referenced by ForEachAttributeSet(), and ForEachAttributeSet().
BlendSampleDataCache
TArrayView<const FBlendSampleData> UE::Anim::FAttributeBlendData::BlendSampleDataCache private
Definition at line 164 of file AttributeBlendData.h.
bPerBoneFilter
bool UE::Anim::FAttributeBlendData::bPerBoneFilter = false private
Definition at line 160 of file AttributeBlendData.h.
HighestBoneWeightedIndices
TArray<int32> UE::Anim::FAttributeBlendData::HighestBoneWeightedIndices private
Definition at line 158 of file AttributeBlendData.h.
PerBoneInterpolationIndices
TArrayView<const int32> UE::Anim::FAttributeBlendData::PerBoneInterpolationIndices private
Blend sample weight data.
Definition at line 163 of file AttributeBlendData.h.
PerBoneWeights
TArrayView<const FPerBoneBlendWeight> UE::Anim::FAttributeBlendData::PerBoneWeights private
Bone level weight data.
Definition at line 157 of file AttributeBlendData.h.
UniformWeight
float UE::Anim::FAttributeBlendData::UniformWeight private
Container level weight data.
Definition at line 148 of file AttributeBlendData.h.
UniqueAttributes
TArray<FUniqueAttribute> UE::Anim::FAttributeBlendData::UniqueAttributes private
Definition at line 145 of file AttributeBlendData.h.
Referenced by ForEachUniqueAttribute(), and ForEachUniqueAttribute().
WeightIndices
TArrayView<const int32> UE::Anim::FAttributeBlendData::WeightIndices private
Definition at line 152 of file AttributeBlendData.h.
Referenced by GetBlendSampleDataCacheIndices().
Weights
TArrayView<const float> UE::Anim::FAttributeBlendData::Weights private
Definition at line 150 of file AttributeBlendData.h.
Referenced by GetBoneWeights().
The documentation for this struct was generated from the following file:
AttributeBlendData.h