Unreal Engine 5.6 C++ API: SkyLightComponent.h File Reference
SkyLightComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "RenderCommandFence.h"
#include "RenderResource.h"
#include "RenderingThread.h"
#include "Components/LightComponentBase.h"
#include "Math/SHMath.h"
#include "Misc/TransactionallySafeCriticalSection.h"
#include "RenderDeferredCleanup.h"
#include "SkyLightComponent.generated.h"
Data Structures
class FSkyTextureCubeResource
A cubemap texture resource that knows how to upload the capture data from a sky capture.
class USkyLightComponent
Enumerations
enum class ESkyLightCaptureStatus { SLCS_Uninitialized , SLCS_CapturedButIncomplete , SLCS_CapturedAndComplete }
Functions
UCLASS ()
Variables
meta =(BlueprintSpawnableComponent)
Enumeration Type Documentation
ESkyLightCaptureStatus
enum class ESkyLightCaptureStatus strong
Enumerator
SLCS_Uninitialized
SLCS_CapturedButIncomplete
SLCS_CapturedAndComplete
Definition at line 93 of file SkyLightComponent.h.
Function Documentation
UCLASS()
UCLASS ()
Variable Documentation
meta
meta =(BlueprintSpawnableComponent)
Definition at line 100 of file SkyLightComponent.h.
Referenced by USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), USkyLightComponent::UPROPERTY(), and USkyLightComponent::UPROPERTY().