Unreal Engine 5.6 C++ API: UE::Geometry::TCapsule3< T > Struct Template Reference
UE::Geometry::TCapsule3< T > Struct Template Reference
#include "CapsuleTypes.h"
Public Member Functions
TCapsule3 ()=default
TCapsule3 (const TSegment3< T > &SegmentIn, T RadiusIn)
TCapsule3 (const TVector< T > &StartPoint, const TVector< T > &EndPoint, T RadiusIn)
const TVector< T > & Center () const
bool Contains (const TVector< T > &Point) const
const TVector< T > & Direction () const
T DistanceSquared (const TVector< T > &Point) const
T Extent () const
TAxisAlignedBox3< T > GetBounds () const
TOrientedBox3< T > GetOrientedBounds () const
T Length () const
T SignedDistance (const TVector< T > &Point) const
T Volume () const
Static Public Member Functions
static T Volume (T Radius, T Extent)
Data Fields
T Radius = (T)0
Radius of the capsule.
TSegment3< T > Segment
Line segment of the capsule.
Detailed Description
template<typename T>
struct UE::Geometry::TCapsule3< T >
Definition at line 23 of file CapsuleTypes.h.
Constructor & Destructor Documentation
TCapsule3() [1/3]
template<typename T> UE::Geometry::TCapsule3< T >::TCapsule3 () default
TCapsule3() [2/3]
template<typename T> UE::Geometry::TCapsule3< T >::TCapsule3 (const TSegment3< T > & SegmentIn, T RadiusIn) inline
Definition at line 33 of file CapsuleTypes.h.
TCapsule3() [3/3]
template<typename T> UE::Geometry::TCapsule3< T >::TCapsule3 (const TVector< T > & StartPoint, const TVector< T > & EndPoint, T RadiusIn) inline
Definition at line 36 of file CapsuleTypes.h.
Member Function Documentation
Center()
template<typename T> const TVector< T > & UE::Geometry::TCapsule3< T >::Center () const inline
Returns
Center of capsule line segment
Definition at line 41 of file CapsuleTypes.h.
Contains()
template<typename T> bool UE::Geometry::TCapsule3< T >::Contains (const TVector< T > & Point) const inline
Returns
true if Capsule contains the given Point
Definition at line 85 of file CapsuleTypes.h.
Referenced by UE::Geometry::IsInside().
Direction()
template<typename T> const TVector< T > & UE::Geometry::TCapsule3< T >::Direction () const inline
Returns
Direction of capsule line segment
Definition at line 47 of file CapsuleTypes.h.
DistanceSquared()
template<typename T> T UE::Geometry::TCapsule3< T >::DistanceSquared (const TVector< T > & Point) const inline
Returns
minimum squared distance from Point to Capsule surface for points outside capsule, 0 for points inside
Definition at line 95 of file CapsuleTypes.h.
Extent()
template<typename T> T UE::Geometry::TCapsule3< T >::Extent () const inline
Returns
Extent (half-length) of capsule line segment
Definition at line 59 of file CapsuleTypes.h.
GetBounds()
template<typename T> TAxisAlignedBox3< T > UE::Geometry::TCapsule3< T >::GetBounds () const inline
Returns
Bounding Box of Capsule
Definition at line 71 of file CapsuleTypes.h.
Referenced by UE::Geometry::IsInside().
GetOrientedBounds()
template<typename T> TOrientedBox3< T > UE::Geometry::TCapsule3< T >::GetOrientedBounds () const inline
Returns
Oriented Bounding Box of Capsule (orthogonal axes are arbitrary)
Definition at line 77 of file CapsuleTypes.h.
Length()
template<typename T> T UE::Geometry::TCapsule3< T >::Length () const inline
Returns
Length of capsule line segment
Definition at line 53 of file CapsuleTypes.h.
SignedDistance()
template<typename T> T UE::Geometry::TCapsule3< T >::SignedDistance (const TVector< T > & Point) const inline
Returns
signed distance from Point to Capsule surface. Points inside capsule return negative distance.
Definition at line 104 of file CapsuleTypes.h.
Referenced by UE::Geometry::TCapsule3< float >::DistanceSquared().
Volume() [1/2]
template<typename T> T UE::Geometry::TCapsule3< T >::Volume () const inline
Returns
Volume of Capsule
Definition at line 65 of file CapsuleTypes.h.
Referenced by UE::Geometry::TCapsule3< float >::Volume().
Volume() [2/2]
template<typename T> T UE::Geometry::TCapsule3< T >::Volume (T Radius, T Extent) inline static
Returns
Volume of Capsule with given Radius and Extent (half-length)
Definition at line 115 of file CapsuleTypes.h.
Field Documentation
Radius
template<typename T> T UE::Geometry::TCapsule3< T >::Radius = (T)0
Radius of the capsule.
Definition at line 29 of file CapsuleTypes.h.
Referenced by UE::Geometry::GetShape().
Segment
template<typename T> TSegment3<T> UE::Geometry::TCapsule3< T >::Segment
Line segment of the capsule.
Definition at line 27 of file CapsuleTypes.h.
Referenced by UE::Geometry::GetShape().
The documentation for this struct was generated from the following file:
CapsuleTypes.h