Unreal Engine 5.6 C++ API: FSequencerUtilities Struct Reference
FSequencerUtilities Struct Reference
#include "SequencerUtilities.h"
Public Member Functions
UE_DEPRECATED (5.5, "CopyFolders now gathers objects and tracks within the folders. Please use CopyFolders that outputs ObjectsExportedText and TracksExportedText") static void CopyFolders(const TArray< UMovieSceneFolder * > &Folders
Static Public Member Functions
static TArray< FGuid > AddActors (TSharedRef< ISequencer > Sequencer, const TArray< TWeakObjectPtr< AActor > > &InActors)
Add existing actors to Sequencer.
static void AddActorsToBinding (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > &Actors, const FMovieSceneBindingProxy &ObjectBinding)
static void AddChangeClassMenu (FMenuBuilder &MenuBuilder, TSharedRef< ISequencer > Sequencer, const TArray< FSequencerChangeBindingInfo > &BindingsToConvert, TFunction< void()> OnBindingChanged)
static void AddObjectsToBinding (TSharedRef< ISequencer > Sequencer, const TArray< UObject * > &Objects, const FMovieSceneBindingProxy &ObjectBinding, UObject *ResolutionContext)
static FGuid AssignActor (TSharedRef< ISequencer > Sequencer, AActor *Actor, FGuid InObjectBinding)
static bool CanConvertToCustomBinding (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, TSubclassOf< UMovieSceneCustomBinding > CustomBindingType, int32 BindingIndex=0)
Convert the selected object binding and object binding index to a custom binding of the chosen type.
static bool CanConvertToPossessable (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, int32 BindingIndex=0)
Convert the requested object binding and object binding index to a possessable.
static bool CanPasteBindings (TSharedRef< ISequencer > Sequencer, const FString &TextToImport)
static bool CanPasteFolders (const FString &TextToImport)
static bool CanPasteSections (const FString &TextToImport)
static bool CanPasteTracks (const FString &TextToImport)
static FMovieScenePossessable * ConvertToCustomBinding (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, TSubclassOf< UMovieSceneCustomBinding > CustomBindingType, int32 BindingIndex=0)
static FMovieScenePossessable * ConvertToPossessable (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, int32 BindingIndex=0)
static TArray< FMovieSceneSpawnable * > ConvertToSpawnable (TSharedRef< ISequencer > Sequencer, FGuid PossessableGuid)
Convert the requested object binding to old-style spawnable.
static void CopyBindings (TSharedRef< ISequencer > Sequencer, const TArray< FMovieSceneBindingProxy > &Bindings, const TArray< UMovieSceneFolder * > &InFolders, FOutputDevice &Ar)
static void CopyBindings (TSharedRef< ISequencer > Sequencer, const TArray< FMovieSceneBindingProxy > &Bindings, const TArray< UMovieSceneFolder * > &InFolders, FString &ExportedText)
Copy/paste object bindings.
static void CopyFolders (TSharedRef< ISequencer > Sequencer, const TArray< UMovieSceneFolder * > &Folders, FString &FoldersExportedText, FString &TracksExportedText, FString &ObjectsExportedText)
Copy/paste folders.
static void CopySections (const TArray< UMovieSceneSection * > &Sections, FString &ExportedText)
Copy/paste sections.
static void CopyTracks (const TArray< UMovieSceneTrack * > &Tracks, const TArray< UMovieSceneFolder * > &InFolders, FString &ExportedText)
Copy/paste tracks.
static FGuid CreateBinding (TSharedRef< ISequencer > Sequencer, UObject &InObject, const UE::Sequencer::FCreateBindingParams &Params=UE::Sequencer::FCreateBindingParams())
Utility functions for managing bindings.
static FGuid CreateCamera (TSharedRef< ISequencer > Sequencer, const bool bSpawnable, ACineCameraActor *&OutActor)
Create a new camera actor and add it to Sequencer.
static FGuid CreateCameraWithRig (TSharedRef< ISequencer > Sequencer, AActor *Actor, const bool bSpawnable, ACineCameraActor *&OutActor)
Create a new camera from a rig and add it to Sequencer.
static void CreateNewSection (UMovieSceneTrack *InTrack, TWeakPtr< ISequencer > InSequencer, int32 InRowIndex, EMovieSceneBlendType InBlendType)
static FGuid CreateOrReplaceBinding (TSharedPtr< ISequencer > Sequencer, UMovieSceneSequence *Sequence, UObject *Object, const UE::Sequencer::FCreateBindingParams &Params=UE::Sequencer::FCreateBindingParams())
static FGuid CreateOrReplaceBinding (TSharedRef< ISequencer > Sequencer, UObject *Object, const UE::Sequencer::FCreateBindingParams &Params=UE::Sequencer::FCreateBindingParams())
static UObject * FindResolutionContext (TSharedRef< ISequencer > Sequencer, UMovieSceneSequence &InSequence, UMovieScene &InMovieScene, const FGuid &InParentGuid, UObject *InPlaybackContext)
Recursively finds the most appropriate Resolution Context for a given Parent Guid of a Possessable.
static TArray< FString > GetAssociatedLevelSequenceMapPackages (const ULevelSequence *InSequence)
static TArray< FString > GetAssociatedLevelSequenceMapPackages (FName LevelSequencePackageName)
static UMovieSceneSequence * GetMovieSceneSequence (TSharedPtr< ISequencer > &InSequencer, const FMovieSceneSequenceID &SequenceID)
Get a movie scene sequence from a FMovideSceneSequenceID.
static TArray< FString > GetPasteBindingsObjectNames (TSharedRef< ISequencer > Sequencer, const FString &TextToImport)
static TRange< FFrameNumber > GetTimeBounds (TSharedRef< ISequencer > Sequencer)
static FName GetUniqueName (FName CandidateName, const TArray< FName > &ExistingNames)
Generates a unique FName from a candidate name given a set of already existing names.
static void HandleTemplateActorClassPicked (UClass *ChosenClass, TSharedRef< ISequencer > Sequencer, const TArray< FSequencerChangeBindingInfo > &BindingsToConvert, TFunction< void()> OnBindingChanged)
static TSharedRef< SWidget > MakeAddButton (FText HoverText, FOnClicked OnClicked, const TAttribute< bool > &HoverState, TWeakPtr< ISequencer > InSequencer)
static TSharedRef< SWidget > MakeAddButton (FText HoverText, FOnGetContent MenuContent, const TAttribute< bool > &HoverState, TWeakPtr< ISequencer > InSequencer)
static FGuid MakeNewSpawnable (TSharedRef< ISequencer > Sequencer, UObject &SourceObject, UActorFactory *ActorFactory=nullptr, bool bSetupDefaults=true, FName SpawnableName=NAME_None)
static void MakeTimeWarpMenuEntry (FMenuBuilder &MenuBuilder, UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel)
static bool PasteBindings (const FString &TextToImport, TSharedRef< ISequencer > Sequencer, FMovieScenePasteBindingsParams PasteBindingsParams, TArray< FMovieSceneBindingProxy > &OutBindings, TArray< FNotificationInfo > &OutErrors)
static bool PasteFolders (const FString &TextToImport, FMovieScenePasteFoldersParams PasteFoldersParams, TArray< UMovieSceneFolder * > &OutFolders, TArray< FNotificationInfo > &OutErrors)
static bool PasteSections (const FString &TextToImport, FMovieScenePasteSectionsParams PasteSectionsParams, TArray< UMovieSceneSection * > &OutSections, TArray< FNotificationInfo > &OutErrors)
static bool PasteTracks (const FString &TextToImport, FMovieScenePasteTracksParams PasteTracksParams, TArray< UMovieSceneTrack * > &OutTracks, TArray< FNotificationInfo > &OutErrors)
static void PopulateMenu_BlenderSubMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track, TWeakPtr< ISequencer > InSequencer)
static void PopulateMenu_CreateNewSection (FMenuBuilder &MenuBuilder, int32 RowIndex, UMovieSceneTrack *Track, TWeakPtr< ISequencer > InSequencer)
static void PopulateMenu_SetBlendType (FMenuBuilder &MenuBuilder, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InSections, TWeakPtr< ISequencer > InSequencer)
static void PopulateMenu_SetBlendType (FMenuBuilder &MenuBuilder, UMovieSceneSection *Section, TWeakPtr< ISequencer > InSequencer)
static void PopulateTimeWarpChannelSubMenu (FMenuBuilder &MenuBuilder, UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel)
static void PopulateTimeWarpSubMenu (FMenuBuilder &MenuBuilder, TFunction< void(TSubclassOf< UMovieSceneTimeWarpGetter >)> OnTimeWarpPicked)
static void RemoveActorsFromBinding (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > &Actors, const FMovieSceneBindingProxy &ObjectBinding)
static void ReplaceBindingWithActors (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > &Actors, const FMovieSceneBindingProxy &ObjectBinding)
static void SaveCurrentMovieSceneAs (TSharedRef< ISequencer > Sequencer)
static void ShowReadOnlyError ()
Show a read only error if the movie scene is locked.
static void ShowSpawnableNotAllowedError ()
Show an error if spawnable is not allowed in a movie scene.
static void SynchronizeExternalSelectionWithSequencerSelection (TSharedRef< ISequencer > Sequencer)
static void UpdateBindingIDs (TSharedRef< ISequencer > Sequencer, FGuid OldGuid, FGuid NewGuid)
Data Fields
FString & ExportedText
Detailed Description
Definition at line 228 of file SequencerUtilities.h.
Member Function Documentation
AddActors()
TArray< FGuid > FSequencerUtilities::AddActors (TSharedRef< ISequencer > Sequencer, const TArray< TWeakObjectPtr< AActor > > & InActors) static
Add existing actors to Sequencer.
AddActorsToBinding()
void FSequencerUtilities::AddActorsToBinding (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > & Actors, const FMovieSceneBindingProxy & ObjectBinding) static
References Actors, and AddActorsToBinding().
Referenced by AddActorsToBinding().
AddChangeClassMenu()
void FSequencerUtilities::AddChangeClassMenu (FMenuBuilder & MenuBuilder, TSharedRef< ISequencer > Sequencer, const TArray< FSequencerChangeBindingInfo > & BindingsToConvert, TFunction< void()> OnBindingChanged) static
References AddChangeClassMenu().
Referenced by AddChangeClassMenu().
AddObjectsToBinding()
void FSequencerUtilities::AddObjectsToBinding (TSharedRef< ISequencer > Sequencer, const TArray< UObject * > & Objects, const FMovieSceneBindingProxy & ObjectBinding, UObject * ResolutionContext) static
References AddObjectsToBinding().
Referenced by AddObjectsToBinding().
AssignActor()
FGuid FSequencerUtilities::AssignActor (TSharedRef< ISequencer > Sequencer, AActor * Actor, FGuid InObjectBinding) static
References Actor, and AssignActor().
Referenced by AssignActor().
CanConvertToCustomBinding()
bool FSequencerUtilities::CanConvertToCustomBinding (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, TSubclassOf< UMovieSceneCustomBinding > CustomBindingType, int32 BindingIndex = 0) static
Convert the selected object binding and object binding index to a custom binding of the chosen type.
CanConvertToPossessable()
bool FSequencerUtilities::CanConvertToPossessable (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, int32 BindingIndex = 0) static
Convert the requested object binding and object binding index to a possessable.
CanPasteBindings()
bool FSequencerUtilities::CanPasteBindings (TSharedRef< ISequencer > Sequencer, const FString & TextToImport) static
References CanPasteBindings().
Referenced by CanPasteBindings().
CanPasteFolders()
bool FSequencerUtilities::CanPasteFolders (const FString & TextToImport) static
CanPasteSections()
bool FSequencerUtilities::CanPasteSections (const FString & TextToImport) static
References CanPasteSections().
Referenced by CanPasteSections().
CanPasteTracks()
bool FSequencerUtilities::CanPasteTracks (const FString & TextToImport) static
References CanPasteTracks().
Referenced by CanPasteTracks().
ConvertToCustomBinding()
FMovieScenePossessable * FSequencerUtilities::ConvertToCustomBinding (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, TSubclassOf< UMovieSceneCustomBinding > CustomBindingType, int32 BindingIndex = 0) static
ConvertToPossessable()
FMovieScenePossessable * FSequencerUtilities::ConvertToPossessable (TSharedRef< ISequencer > Sequencer, FGuid BindingGuid, int32 BindingIndex = 0) static
ConvertToSpawnable()
TArray< FMovieSceneSpawnable * > FSequencerUtilities::ConvertToSpawnable (TSharedRef< ISequencer > Sequencer, FGuid PossessableGuid) static
Convert the requested object binding to old-style spawnable.
If there are multiple objects assigned to the possessable, multiple spawnables will be created
CopyBindings() [1/2]
void FSequencerUtilities::CopyBindings (TSharedRef< ISequencer > Sequencer, const TArray< FMovieSceneBindingProxy > & Bindings, const TArray< UMovieSceneFolder * > & InFolders, FOutputDevice & Ar) static
References Ar, and CopyBindings().
CopyBindings() [2/2]
void FSequencerUtilities::CopyBindings (TSharedRef< ISequencer > Sequencer, const TArray< FMovieSceneBindingProxy > & Bindings, const TArray< UMovieSceneFolder * > & InFolders, FString & ExportedText) static
Copy/paste object bindings.
References CopyBindings(), and ExportedText.
Referenced by CopyBindings(), and CopyBindings().
CopyFolders()
void FSequencerUtilities::CopyFolders (TSharedRef< ISequencer > Sequencer, const TArray< UMovieSceneFolder * > & Folders, FString & FoldersExportedText, FString & TracksExportedText, FString & ObjectsExportedText) static
Copy/paste folders.
References Folders.
CopySections()
void FSequencerUtilities::CopySections (const TArray< UMovieSceneSection * > & Sections, FString & ExportedText) static
Copy/paste sections.
References CopySections(), ExportedText, and Sections.
Referenced by CopySections().
CopyTracks()
void FSequencerUtilities::CopyTracks (const TArray< UMovieSceneTrack * > & Tracks, const TArray< UMovieSceneFolder * > & InFolders, FString & ExportedText) static
Copy/paste tracks.
References CopyTracks(), ExportedText, and Tracks.
Referenced by CopyTracks().
CreateBinding()
FGuid FSequencerUtilities::CreateBinding (TSharedRef< ISequencer > Sequencer, UObject & InObject, const UE::Sequencer::FCreateBindingParams & Params = UE::Sequencer::FCreateBindingParams()) static
Utility functions for managing bindings.
References CreateBinding(), and Params.
Referenced by CreateBinding().
CreateCamera()
FGuid FSequencerUtilities::CreateCamera (TSharedRef< ISequencer > Sequencer, const bool bSpawnable, ACineCameraActor *& OutActor) static
Create a new camera actor and add it to Sequencer.
CreateCameraWithRig()
FGuid FSequencerUtilities::CreateCameraWithRig (TSharedRef< ISequencer > Sequencer, AActor * Actor, const bool bSpawnable, ACineCameraActor *& OutActor) static
Create a new camera from a rig and add it to Sequencer.
References Actor.
CreateNewSection()
void FSequencerUtilities::CreateNewSection (UMovieSceneTrack * InTrack, TWeakPtr< ISequencer > InSequencer, int32 InRowIndex, EMovieSceneBlendType InBlendType) static
CreateOrReplaceBinding() [1/2]
FGuid FSequencerUtilities::CreateOrReplaceBinding (TSharedPtr< ISequencer > Sequencer, UMovieSceneSequence * Sequence, UObject * Object, const UE::Sequencer::FCreateBindingParams & Params = UE::Sequencer::FCreateBindingParams()) static
References CreateOrReplaceBinding(), Object, and Params.
CreateOrReplaceBinding() [2/2]
FGuid FSequencerUtilities::CreateOrReplaceBinding (TSharedRef< ISequencer > Sequencer, UObject * Object, const UE::Sequencer::FCreateBindingParams & Params = UE::Sequencer::FCreateBindingParams()) static
References CreateOrReplaceBinding(), Object, and Params.
Referenced by CreateOrReplaceBinding(), and CreateOrReplaceBinding().
FindResolutionContext()
UObject * FSequencerUtilities::FindResolutionContext (TSharedRef< ISequencer > Sequencer, UMovieSceneSequence & InSequence, UMovieScene & InMovieScene, const FGuid & InParentGuid, UObject * InPlaybackContext) static
Recursively finds the most appropriate Resolution Context for a given Parent Guid of a Possessable.
References FindResolutionContext().
Referenced by FindResolutionContext().
GetAssociatedLevelSequenceMapPackages() [1/2]
TArray< FString > FSequencerUtilities::GetAssociatedLevelSequenceMapPackages (const ULevelSequence * InSequence) static
GetAssociatedLevelSequenceMapPackages() [2/2]
TArray< FString > FSequencerUtilities::GetAssociatedLevelSequenceMapPackages (FName LevelSequencePackageName) static
GetMovieSceneSequence()
UMovieSceneSequence * FSequencerUtilities::GetMovieSceneSequence (TSharedPtr< ISequencer > & InSequencer, const FMovieSceneSequenceID & SequenceID) static
Get a movie scene sequence from a FMovideSceneSequenceID.
References GetMovieSceneSequence().
Referenced by GetMovieSceneSequence().
GetPasteBindingsObjectNames()
TArray< FString > FSequencerUtilities::GetPasteBindingsObjectNames (TSharedRef< ISequencer > Sequencer, const FString & TextToImport) static
References GetPasteBindingsObjectNames().
Referenced by GetPasteBindingsObjectNames().
GetTimeBounds()
TRange< FFrameNumber > FSequencerUtilities::GetTimeBounds (TSharedRef< ISequencer > Sequencer) static
References GetTimeBounds().
Referenced by GetTimeBounds().
GetUniqueName()
FName FSequencerUtilities::GetUniqueName (FName CandidateName, const TArray< FName > & ExistingNames) static
Generates a unique FName from a candidate name given a set of already existing names.
The name is made unique by appending a number to the end.
HandleTemplateActorClassPicked()
void FSequencerUtilities::HandleTemplateActorClassPicked (UClass * ChosenClass, TSharedRef< ISequencer > Sequencer, const TArray< FSequencerChangeBindingInfo > & BindingsToConvert, TFunction< void()> OnBindingChanged) static
References HandleTemplateActorClassPicked().
Referenced by HandleTemplateActorClassPicked().
MakeAddButton() [1/2]
TSharedRef< SWidget > FSequencerUtilities::MakeAddButton (FText HoverText, FOnClicked OnClicked, const TAttribute< bool > & HoverState, TWeakPtr< ISequencer > InSequencer) static
MakeAddButton() [2/2]
TSharedRef< SWidget > FSequencerUtilities::MakeAddButton (FText HoverText, FOnGetContent MenuContent, const TAttribute< bool > & HoverState, TWeakPtr< ISequencer > InSequencer) static
MakeNewSpawnable()
FGuid FSequencerUtilities::MakeNewSpawnable (TSharedRef< ISequencer > Sequencer, UObject & SourceObject, UActorFactory * ActorFactory = nullptr, bool bSetupDefaults = true, FName SpawnableName = NAME_None) static
MakeTimeWarpMenuEntry()
void FSequencerUtilities::MakeTimeWarpMenuEntry (FMenuBuilder & MenuBuilder, UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel) static
PasteBindings()
bool FSequencerUtilities::PasteBindings (const FString & TextToImport, TSharedRef< ISequencer > Sequencer, FMovieScenePasteBindingsParams PasteBindingsParams, TArray< FMovieSceneBindingProxy > & OutBindings, TArray< FNotificationInfo > & OutErrors) static
References PasteBindings().
Referenced by PasteBindings().
PasteFolders()
bool FSequencerUtilities::PasteFolders (const FString & TextToImport, FMovieScenePasteFoldersParams PasteFoldersParams, TArray< UMovieSceneFolder * > & OutFolders, TArray< FNotificationInfo > & OutErrors) static
PasteSections()
bool FSequencerUtilities::PasteSections (const FString & TextToImport, FMovieScenePasteSectionsParams PasteSectionsParams, TArray< UMovieSceneSection * > & OutSections, TArray< FNotificationInfo > & OutErrors) static
References PasteSections().
Referenced by PasteSections().
PasteTracks()
bool FSequencerUtilities::PasteTracks (const FString & TextToImport, FMovieScenePasteTracksParams PasteTracksParams, TArray< UMovieSceneTrack * > & OutTracks, TArray< FNotificationInfo > & OutErrors) static
References PasteTracks().
Referenced by PasteTracks().
PopulateMenu_BlenderSubMenu()
void FSequencerUtilities::PopulateMenu_BlenderSubMenu (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track, TWeakPtr< ISequencer > InSequencer) static
PopulateMenu_CreateNewSection()
void FSequencerUtilities::PopulateMenu_CreateNewSection (FMenuBuilder & MenuBuilder, int32 RowIndex, UMovieSceneTrack * Track, TWeakPtr< ISequencer > InSequencer) static
PopulateMenu_SetBlendType() [1/2]
void FSequencerUtilities::PopulateMenu_SetBlendType (FMenuBuilder & MenuBuilder, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InSections, TWeakPtr< ISequencer > InSequencer) static
PopulateMenu_SetBlendType() [2/2]
void FSequencerUtilities::PopulateMenu_SetBlendType (FMenuBuilder & MenuBuilder, UMovieSceneSection * Section, TWeakPtr< ISequencer > InSequencer) static
PopulateTimeWarpChannelSubMenu()
void FSequencerUtilities::PopulateTimeWarpChannelSubMenu (FMenuBuilder & MenuBuilder, UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel) static
PopulateTimeWarpSubMenu()
void FSequencerUtilities::PopulateTimeWarpSubMenu (FMenuBuilder & MenuBuilder, TFunction< void(TSubclassOf< UMovieSceneTimeWarpGetter >)> OnTimeWarpPicked) static
RemoveActorsFromBinding()
void FSequencerUtilities::RemoveActorsFromBinding (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > & Actors, const FMovieSceneBindingProxy & ObjectBinding) static
References Actors, and RemoveActorsFromBinding().
Referenced by RemoveActorsFromBinding().
ReplaceBindingWithActors()
void FSequencerUtilities::ReplaceBindingWithActors (TSharedRef< ISequencer > Sequencer, const TArray< AActor * > & Actors, const FMovieSceneBindingProxy & ObjectBinding) static
References Actors, and ReplaceBindingWithActors().
Referenced by ReplaceBindingWithActors().
SaveCurrentMovieSceneAs()
void FSequencerUtilities::SaveCurrentMovieSceneAs (TSharedRef< ISequencer > Sequencer) static
References SaveCurrentMovieSceneAs().
Referenced by SaveCurrentMovieSceneAs().
ShowReadOnlyError()
void FSequencerUtilities::ShowReadOnlyError () static
Show a read only error if the movie scene is locked.
References ShowReadOnlyError().
Referenced by ShowReadOnlyError().
ShowSpawnableNotAllowedError()
void FSequencerUtilities::ShowSpawnableNotAllowedError () static
Show an error if spawnable is not allowed in a movie scene.
References ShowSpawnableNotAllowedError().
Referenced by ShowSpawnableNotAllowedError().
SynchronizeExternalSelectionWithSequencerSelection()
void FSequencerUtilities::SynchronizeExternalSelectionWithSequencerSelection (TSharedRef< ISequencer > Sequencer) static
References SynchronizeExternalSelectionWithSequencerSelection().
Referenced by SynchronizeExternalSelectionWithSequencerSelection().
UE_DEPRECATED()
FSequencerUtilities::UE_DEPRECATED (5. 5, "CopyFolders now gathers objects and tracks within the folders. Please use CopyFolders that outputs ObjectsExportedText and TracksExportedText") const &
UpdateBindingIDs()
void FSequencerUtilities::UpdateBindingIDs (TSharedRef< ISequencer > Sequencer, FGuid OldGuid, FGuid NewGuid) static
References UpdateBindingIDs().
Referenced by UpdateBindingIDs().
Field Documentation
ExportedText
FString& FSequencerUtilities::ExportedText
Definition at line 289 of file SequencerUtilities.h.
Referenced by CopyBindings(), CopySections(), and CopyTracks().
The documentation for this struct was generated from the following file:
SequencerUtilities.h