Unreal Engine 5.6 C++ API: FScopedRepContext Struct Reference
FScopedRepContext Struct Reference
#include "NetConnection.h"
Public Member Functions
FScopedRepContext (const FScopedRepContext &)=delete
FScopedRepContext (FScopedRepContext &&)=delete
FScopedRepContext (UNetConnection *InConnection, AActor *InActor)
FScopedRepContext (UNetConnection *InConnection, ULevel *InLevel)
~FScopedRepContext ()
FScopedRepContext & operator= (const FScopedRepContext &)=delete
FScopedRepContext & operator= (FScopedRepContext &&)=delete
Private Attributes
UNetConnection * Connection
Detailed Description
Definition at line 1954 of file NetConnection.h.
Constructor & Destructor Documentation
FScopedRepContext() [1/4]
FScopedRepContext::FScopedRepContext (UNetConnection * InConnection, AActor * InActor)
Referenced by FScopedRepContext(), FScopedRepContext(), operator=(), and operator=().
FScopedRepContext() [2/4]
FScopedRepContext::FScopedRepContext (UNetConnection * InConnection, ULevel * InLevel) inline
Definition at line 1959 of file NetConnection.h.
References check, and Connection.
~FScopedRepContext()
FScopedRepContext::~FScopedRepContext () inline
Definition at line 1971 of file NetConnection.h.
References Connection.
FScopedRepContext() [3/4]
FScopedRepContext::FScopedRepContext (FScopedRepContext &&) delete
References FScopedRepContext().
FScopedRepContext() [4/4]
FScopedRepContext::FScopedRepContext (const FScopedRepContext &) delete
References FScopedRepContext().
Member Function Documentation
operator=() [1/2]
FScopedRepContext & FScopedRepContext::operator= (const FScopedRepContext &) delete
References FScopedRepContext().
operator=() [2/2]
FScopedRepContext & FScopedRepContext::operator= (FScopedRepContext &&) delete
References FScopedRepContext().
Field Documentation
Connection
UNetConnection* FScopedRepContext::Connection private
Definition at line 1986 of file NetConnection.h.
Referenced by FScopedRepContext(), and ~FScopedRepContext().
The documentation for this struct was generated from the following file:
NetConnection.h