Unreal Engine 5.6 C++ API: UBaseDynamicMeshComponent Class Reference
UBaseDynamicMeshComponent Class Reference
#include "BaseDynamicMeshComponent.h"
Public Member Functions
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * GetMaterial (int32 ElementIndex) const override
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * GetMaterialByName (FName MaterialSlotName) const override
virtual GEOMETRYFRAMEWORK_API FMaterialRelevance GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const override
Accesses the scene relevance information for the materials applied to the mesh.
virtual GEOMETRYFRAMEWORK_API TArray< FName > GetMaterialSlotNames () const override
virtual GEOMETRYFRAMEWORK_API int32 GetNumMaterials () const override
virtual GEOMETRYFRAMEWORK_API void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual bool HasOverrideSecondaryWireframeRenderMaterial () const
virtual bool HasOverrideWireframeRenderMaterial () const
virtual bool HasSecondaryRenderMaterial () const
virtual GEOMETRYFRAMEWORK_API bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
GEOMETRYFRAMEWORK_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual GEOMETRYFRAMEWORK_API void SetMaterial (int32 ElementIndex, UMaterialInterface *Material) override
virtual GEOMETRYFRAMEWORK_API void SetNumMaterials (int32 NumMaterials)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UFUNCTION()) virtual EDynamicMeshComponentDistanceFieldMode GetDistanceFieldMode() const
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UFUNCTION()) virtual void SetDistanceFieldMode(EDynamicMeshComponentDistanceFieldMode NewDistFieldMode)
Configure Distance Field computation mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual bool GetEnableRaytracing() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual bool GetSecondaryBuffersVisibility() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual EDynamicMeshDrawPath GetMeshDrawPath() const
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideRenderMaterial()
Clear any active override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideSecondaryWireframeRenderMaterial()
Clear any active secondary wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearOverrideWireframeRenderMaterial()
Clear any active wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void ClearSecondaryRenderMaterial()
Clear any active secondary render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetColorOverrideMode(EDynamicMeshComponentColorOverrideMode NewMode)
Configure the active Color Override.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetConstantOverrideColor(FColor NewColor)
Configure the Color used with Constant Color Override Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetEnableFlatShading(bool bEnable)
Configure the Color used with Constant Color Override Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetEnableRaytracing(bool bSetEnabled)
Enable/Disable raytracing support.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetMeshDrawPath(EDynamicMeshDrawPath NewDrawPath)
Set the mesh rendering to use the static or dynamic draw path.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideRenderMaterial(UMaterialInterface *Material)
Set an active override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideSecondaryWireframeRenderMaterial(UMaterialInterface *Material)
Set an active secondary wireframe override render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetOverrideWireframeRenderMaterial(UMaterialInterface *Material)
Set an active wireframe override render Material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetSecondaryBuffersVisibility(bool bSetVisible)
Show/Hide the secondary triangle buffers.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetSecondaryRenderMaterial(UMaterialInterface *Material)
Set an active secondary render material.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetShadowsEnabled(bool bEnabled)
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetVertexColorSpaceTransformMode(EDynamicMeshVertexColorTransformMode NewMode)
Configure the active Color Space Transform Mode.
UFUNCTION () GEOMETRYFRAMEWORK_API virtual void SetViewModeOverridesEnabled(bool bEnabled)
UFUNCTION () virtual bool GetEnableWireframeRenderPass() const
UFUNCTION () virtual bool GetFlatShadingEnabled() const
UFUNCTION () virtual bool GetShadowsEnabled() const
UFUNCTION () virtual bool GetViewModeOverridesEnabled() const
UFUNCTION () virtual bool HasOverrideRenderMaterial(int k) const
UFUNCTION () virtual EDynamicMeshComponentColorOverrideMode GetColorOverrideMode() const
UFUNCTION () virtual EDynamicMeshVertexColorTransformMode GetVertexColorSpaceTransformMode() const
UFUNCTION () virtual FColor GetConstantOverrideColor() const
UFUNCTION () virtual UMaterialInterface *GetOverrideRenderMaterial(int MaterialIndex) const
UFUNCTION () virtual UMaterialInterface *GetOverrideSecondaryWireframeRenderMaterial() const
UFUNCTION () virtual UMaterialInterface *GetOverrideWireframeRenderMaterial() const
UFUNCTION () virtual UMaterialInterface *GetSecondaryRenderMaterial() const
UFUNCTION () virtual void SetEnableWireframeRenderPass(bool bEnable)
Configure whether wireframe rendering is enabled or not.
UPROPERTY () bool bEnableRaytracing
Enable/disable Raytracing support on this Mesh, if Raytracing is currently enabled in the Project Settings.
UPROPERTY () TArray< TObjectPtr< UMaterialInterface > > BaseMaterials
UPROPERTY ()) bool bEnableFlatShading
Enable use of per-triangle facet normals in place of mesh normals.
UPROPERTY ()) bool bEnableViewModeOverrides
This flag controls whether Editor View Mode Overrides are enabled for this mesh.
UPROPERTY ()) bool bExplicitShowWireframe
If true, render the Wireframe on top of the Shaded Mesh.
UPROPERTY ()) EDynamicMeshComponentColorOverrideMode ColorMode
UPROPERTY ()) EDynamicMeshVertexColorTransformMode ColorSpaceMode
Color Space Transform that will be applied to the colors stored in the DynamicMesh Attribute Color Overlay when constructing render buffers.
UPROPERTY ()) FColor ConstantColor
Constant Color used when Override Color Mode is set to Constant.
UPROPERTY ()) FLinearColor WireframeColor
Constant Color used when Override Color Mode is set to Constant.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Static Public Member Functions
static GEOMETRYFRAMEWORK_API void SetDefaultVertexColorMaterial (UMaterialInterface *Material)
Set the vertex color material used for all BaseDynamicMeshComponent-derived Components.
static GEOMETRYFRAMEWORK_API void SetDefaultWireframeMaterial (UMaterialInterface *Material)
Set the wireframe material used for all BaseDynamicMeshComponent-derived Components.
Protected Member Functions
virtual bool AllowFastUpdate ()
virtual FBaseDynamicMeshSceneProxy * GetBaseSceneProxy ()
Subclass must implement this to return scene proxy if available, or nullptr.
virtual void NotifyMaterialSetUpdated ()
Subclass must implement this to notify allocated proxies of updated materials.
virtual GEOMETRYFRAMEWORK_API void OnRenderingStateChanged (bool bForceImmedateRebuild)
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") GEOMETRYFRAMEWORK_API virtual void OnNewDistanceFieldMode()
UE_DEPRECATED (5.6, "Dynamic Mesh distance field support has been deprecated") UPROPERTY()) EDynamicMeshComponentDistanceFieldMode DistanceFieldMode_DEPRECATED
Controls how distance field is computed.
UPROPERTY ()
UPROPERTY ()
UPROPERTY () EDynamicMeshDrawPath DrawPath
Controls whether to use the dynamic or static draw path.
UPROPERTY () TObjectPtr< UMaterialInterface > OverrideRenderMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > SecondaryRenderMaterial
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Static Protected Member Functions
static GEOMETRYFRAMEWORK_API UMaterialInterface * GetDefaultVertexColorMaterial_RenderThread ()
static GEOMETRYFRAMEWORK_API UMaterialInterface * GetDefaultWireframeMaterial_RenderThread ()
static GEOMETRYFRAMEWORK_API void InitializeDefaultMaterials ()
Protected Attributes
bool bDrawSecondaryBuffers = true
TObjectPtr< UMaterialInterface > SecondaryWireframeMaterialOverride = nullptr
TObjectPtr< UMaterialInterface > WireframeMaterialOverride = nullptr
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
virtual void ApplyChange (const FMeshChange *Change, bool bRevert) override
Apply a general mesh change to the internal mesh (implements IMeshCommandChangeTarget)
virtual void ApplyChange (const FMeshReplacementChange *Change, bool bRevert) override
Apply a full mesh replacement change to the internal mesh (implements IMeshReplacementCommandChangeTarget)
virtual void ApplyChange (const FMeshVertexChange *Change, bool bRevert) override
Apply a vertex deformation change to the internal mesh (implements IMeshVertexCommandChangeTarget)
virtual void ApplyTransform (const FTransform3d &Transform, bool bInvert)
Apply a transform to the mesh.
GENERATED_UCLASS_BODY () public
initialize the internal mesh from a DynamicMesh
virtual FDynamicMesh3 * GetMesh ()
virtual const FDynamicMesh3 * GetMesh () const
virtual void NotifyMeshUpdated ()
Call this if you update the mesh via GetMesh()
virtual void ProcessMesh (TFunctionRef< void(const UE::Geometry::FDynamicMesh3 &)> ProcessFunc) const
Allow external code to read the internal mesh.
UFUNCTION () virtual UDynamicMesh *GetDynamicMesh()
Static Private Attributes
static GEOMETRYFRAMEWORK_API UMaterialInterface * DefaultVertexColorMaterial
static GEOMETRYFRAMEWORK_API UMaterialInterface * DefaultWireframeMaterial
Friends
class FBaseDynamicMeshSceneProxy
class FGeometryFrameworkModule
Additional Inherited Members
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Detailed Description
Definition at line 124 of file BaseDynamicMeshComponent.h.
Member Function Documentation
AllowFastUpdate()
virtual bool UBaseDynamicMeshComponent::AllowFastUpdate () inline protected virtual
Definition at line 611 of file BaseDynamicMeshComponent.h.
References AllowFastUpdate().
Referenced by AllowFastUpdate().
ApplyChange() [1/3]
virtual void UBaseDynamicMeshComponent::ApplyChange (const FMeshChange * Change, bool bRevert) inline override private virtual
Apply a general mesh change to the internal mesh (implements IMeshCommandChangeTarget)
Reimplemented in UDynamicMeshComponent.
Definition at line 203 of file BaseDynamicMeshComponent.h.
References unimplemented.
ApplyChange() [2/3]
virtual void UBaseDynamicMeshComponent::ApplyChange (const FMeshReplacementChange * Change, bool bRevert) inline override private virtual
Apply a full mesh replacement change to the internal mesh (implements IMeshReplacementCommandChangeTarget)
Reimplemented in UDynamicMeshComponent.
Definition at line 211 of file BaseDynamicMeshComponent.h.
References unimplemented.
ApplyChange() [3/3]
virtual void UBaseDynamicMeshComponent::ApplyChange (const FMeshVertexChange * Change, bool bRevert) inline override private virtual
Apply a vertex deformation change to the internal mesh (implements IMeshVertexCommandChangeTarget)
Reimplemented in UDynamicMeshComponent.
Definition at line 195 of file BaseDynamicMeshComponent.h.
References unimplemented.
ApplyTransform()
virtual void UBaseDynamicMeshComponent::ApplyTransform (const FTransform3d & Transform, bool bInvert) inline private virtual
Apply a transform to the mesh.
Reimplemented in UDynamicMeshComponent.
Definition at line 219 of file BaseDynamicMeshComponent.h.
References Transform, and unimplemented.
GENERATED_UCLASS_BODY()
UBaseDynamicMeshComponent::GENERATED_UCLASS_BODY () inline private
initialize the internal mesh from a DynamicMesh
Definition at line 131 of file BaseDynamicMeshComponent.h.
References Geometry, and unimplemented.
GetBaseSceneProxy()
virtual FBaseDynamicMeshSceneProxy * UBaseDynamicMeshComponent::GetBaseSceneProxy () inline protected virtual
Subclass must implement this to return scene proxy if available, or nullptr.
Reimplemented in UDynamicMeshComponent.
Definition at line 230 of file BaseDynamicMeshComponent.h.
References FBaseDynamicMeshSceneProxy, and unimplemented.
GetDefaultVertexColorMaterial_RenderThread()
GEOMETRYFRAMEWORK_API UMaterialInterface * UBaseDynamicMeshComponent::GetDefaultVertexColorMaterial_RenderThread () static protected
References GetDefaultVertexColorMaterial_RenderThread().
Referenced by GetDefaultVertexColorMaterial_RenderThread().
GetDefaultWireframeMaterial_RenderThread()
GEOMETRYFRAMEWORK_API UMaterialInterface * UBaseDynamicMeshComponent::GetDefaultWireframeMaterial_RenderThread () static protected
References GetDefaultWireframeMaterial_RenderThread().
Referenced by GetDefaultWireframeMaterial_RenderThread().
GetMaterial()
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * UBaseDynamicMeshComponent::GetMaterial (int32 ElementIndex) const override virtual
Reimplemented from UMeshComponent.
GetMaterialByName()
virtual GEOMETRYFRAMEWORK_API UMaterialInterface * UBaseDynamicMeshComponent::GetMaterialByName (FName MaterialSlotName) const override virtual
Reimplemented from UMeshComponent.
GetMaterialRelevance()
virtual GEOMETRYFRAMEWORK_API FMaterialRelevance UBaseDynamicMeshComponent::GetMaterialRelevance (ERHIFeatureLevel::Type InFeatureLevel) const override virtual
Accesses the scene relevance information for the materials applied to the mesh.
Valid from game thread only.
Reimplemented from UMeshComponent.
GetMaterialSlotNames()
virtual GEOMETRYFRAMEWORK_API TArray< FName > UBaseDynamicMeshComponent::GetMaterialSlotNames () const override virtual
GetMesh() [1/2]
virtual FDynamicMesh3 * UBaseDynamicMeshComponent::GetMesh () inline private virtual
Returns
pointer to internal mesh
Warning
avoid usage of this function, access via GetDynamicMesh() instead
Definition at line 150 of file BaseDynamicMeshComponent.h.
References unimplemented.
GetMesh() [2/2]
virtual const FDynamicMesh3 * UBaseDynamicMeshComponent::GetMesh () const inline private virtual
Returns
pointer to internal mesh
Definition at line 159 of file BaseDynamicMeshComponent.h.
References unimplemented.
GetNumMaterials()
virtual GEOMETRYFRAMEWORK_API int32 UBaseDynamicMeshComponent::GetNumMaterials () const override virtual
Reimplemented from UMeshComponent.
GetUsedMaterials()
virtual GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override virtual
Reimplemented from UMeshComponent.
HasOverrideSecondaryWireframeRenderMaterial()
virtual bool UBaseDynamicMeshComponent::HasOverrideSecondaryWireframeRenderMaterial () const inline virtual
Returns
true if a active secondary wireframe override render material is set
Definition at line 548 of file BaseDynamicMeshComponent.h.
References HasOverrideSecondaryWireframeRenderMaterial(), and SecondaryWireframeMaterialOverride.
Referenced by HasOverrideSecondaryWireframeRenderMaterial().
HasOverrideWireframeRenderMaterial()
virtual bool UBaseDynamicMeshComponent::HasOverrideWireframeRenderMaterial () const inline virtual
Returns
true if a active wireframe override render material is set
Definition at line 510 of file BaseDynamicMeshComponent.h.
References HasOverrideWireframeRenderMaterial(), and WireframeMaterialOverride.
Referenced by HasOverrideWireframeRenderMaterial().
HasSecondaryRenderMaterial()
virtual bool UBaseDynamicMeshComponent::HasSecondaryRenderMaterial () const inline virtual
Returns
true if a secondary render material is set
Definition at line 458 of file BaseDynamicMeshComponent.h.
References HasSecondaryRenderMaterial().
Referenced by HasSecondaryRenderMaterial().
InitializeDefaultMaterials()
GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::InitializeDefaultMaterials () static protected
References InitializeDefaultMaterials().
Referenced by InitializeDefaultMaterials().
IsMaterialSlotNameValid()
virtual GEOMETRYFRAMEWORK_API bool UBaseDynamicMeshComponent::IsMaterialSlotNameValid (FName MaterialSlotName) const override virtual
NotifyMaterialSetUpdated()
virtual void UBaseDynamicMeshComponent::NotifyMaterialSetUpdated () inline protected virtual
Subclass must implement this to notify allocated proxies of updated materials.
Reimplemented in UDynamicMeshComponent.
Definition at line 239 of file BaseDynamicMeshComponent.h.
References unimplemented.
NotifyMeshUpdated()
virtual void UBaseDynamicMeshComponent::NotifyMeshUpdated () inline private virtual
Call this if you update the mesh via GetMesh()
Todo
should provide a function that calls a lambda to modify the mesh, and only return const mesh pointer
Reimplemented in UDynamicMeshComponent.
Definition at line 187 of file BaseDynamicMeshComponent.h.
References unimplemented.
OnRenderingStateChanged()
virtual GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::OnRenderingStateChanged (bool bForceImmedateRebuild) protected virtual
References OnRenderingStateChanged(), and UPROPERTY().
Referenced by OnRenderingStateChanged().
PostEditChangeProperty()
GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override
ProcessMesh()
virtual void UBaseDynamicMeshComponent::ProcessMesh (TFunctionRef< void(const UE::Geometry::FDynamicMesh3 &)> ProcessFunc) const inline private virtual
Allow external code to read the internal mesh.
Reimplemented in UDynamicMeshComponent.
Definition at line 168 of file BaseDynamicMeshComponent.h.
References unimplemented.
SetDefaultVertexColorMaterial()
GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::SetDefaultVertexColorMaterial (UMaterialInterface * Material) static
Set the vertex color material used for all BaseDynamicMeshComponent-derived Components.
References Material, and SetDefaultVertexColorMaterial().
Referenced by SetDefaultVertexColorMaterial().
SetDefaultWireframeMaterial()
GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::SetDefaultWireframeMaterial (UMaterialInterface * Material) static
Set the wireframe material used for all BaseDynamicMeshComponent-derived Components.
References Material, and SetDefaultWireframeMaterial().
Referenced by SetDefaultWireframeMaterial().
SetMaterial()
virtual GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::SetMaterial (int32 ElementIndex, UMaterialInterface * Material) override virtual
Reimplemented from UMeshComponent.
References Material.
SetNumMaterials()
virtual GEOMETRYFRAMEWORK_API void UBaseDynamicMeshComponent::SetNumMaterials (int32 NumMaterials) virtual
UE_DEPRECATED() [1/4]
UBaseDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") inline protected
Definition at line 656 of file BaseDynamicMeshComponent.h.
UE_DEPRECATED() [2/4]
UBaseDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") const inline
Returns
Method used to compute the distance field
Definition at line 649 of file BaseDynamicMeshComponent.h.
References Category, EDynamicMeshComponentDistanceFieldMode, meta, and UFUNCTION().
UE_DEPRECATED() [3/4]
UBaseDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") inline
Configure Distance Field computation mode.
Definition at line 642 of file BaseDynamicMeshComponent.h.
References Category, EDynamicMeshComponentDistanceFieldMode, meta, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [4/4]
UBaseDynamicMeshComponent::UE_DEPRECATED (5. 6, "Dynamic Mesh distance field support has been deprecated") protected
Controls how distance field is computed.
References EDynamicMeshComponentDistanceFieldMode, meta, UE_DEPRECATED(), and UPROPERTY().
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UFUNCTION() [1/34]
UBaseDynamicMeshComponent::UFUNCTION () const
Returns
true if raytracing support is currently enabled
References Category, and UFUNCTION().
UFUNCTION() [2/34]
UBaseDynamicMeshComponent::UFUNCTION () const
Returns
true if secondary buffers are currently set to be visible
References Category, and UFUNCTION().
UFUNCTION() [3/34]
UBaseDynamicMeshComponent::UFUNCTION () const
Returns
Whether the mesh renders using the static or dynamic draw path
References Category, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UFUNCTION().
UFUNCTION() [4/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Clear any active override render material.
References Category, and UFUNCTION().
UFUNCTION() [5/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Clear any active secondary wireframe override render material.
References Category, and UFUNCTION().
UFUNCTION() [6/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Clear any active wireframe override render material.
References Category, and UFUNCTION().
UFUNCTION() [7/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Clear any active secondary render material.
References Category, and UFUNCTION().
UFUNCTION() [8/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Configure the active Color Override.
References Category, and UFUNCTION().
UFUNCTION() [9/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Configure the Color used with Constant Color Override Mode.
References Category, and UFUNCTION().
UFUNCTION() [10/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Configure the Color used with Constant Color Override Mode.
References Category, and UFUNCTION().
UFUNCTION() [11/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Enable/Disable raytracing support.
This is an expensive call as it flushes the rendering queue and forces an immediate rebuild of the SceneProxy.
References Category, and UFUNCTION().
UFUNCTION() [12/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Set the mesh rendering to use the static or dynamic draw path.
References Category.
UFUNCTION() [13/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Set an active override render material.
This should replace all materials during rendering.
References Category, Material, and UFUNCTION().
UFUNCTION() [14/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Set an active secondary wireframe override render material.
References Category, and Material.
UFUNCTION() [15/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Set an active wireframe override render Material.
References Category, Material, and UFUNCTION().
UFUNCTION() [16/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Show/Hide the secondary triangle buffers.
Does not invalidate SceneProxy.
References Category.
UFUNCTION() [17/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Set an active secondary render material.
References Category, Material, and UFUNCTION().
UFUNCTION() [18/34]
UBaseDynamicMeshComponent::UFUNCTION ()
References Category.
UFUNCTION() [19/34]
UBaseDynamicMeshComponent::UFUNCTION ()
Configure the active Color Space Transform Mode.
References Category, and UFUNCTION().
UFUNCTION() [20/34]
UBaseDynamicMeshComponent::UFUNCTION ()
References Category.
UFUNCTION() [21/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
true if wireframe rendering pass is enabled
Definition at line 266 of file BaseDynamicMeshComponent.h.
References Category.
UFUNCTION() [22/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
Whether mesh will be rendered with per-triangle normals
Definition at line 360 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [23/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Definition at line 375 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [24/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Definition at line 381 of file BaseDynamicMeshComponent.h.
References FBaseDynamicMeshSceneProxy::bEnableViewModeOverrides, Category, and UFUNCTION().
UFUNCTION() [25/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
true if an override render material is currently enabled for the given MaterialIndex
Definition at line 414 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [26/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active Color Override mode
Definition at line 295 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [27/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active Color Override mode
Definition at line 335 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [28/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active Color used for Constant Color Override Mode
Definition at line 313 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [29/34]
UBaseDynamicMeshComponent::UFUNCTION () inline private
Returns
the child UDynamicMesh
Definition at line 176 of file BaseDynamicMeshComponent.h.
References Category, and unimplemented.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [30/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active override render material for the given MaterialIndex
Definition at line 423 of file BaseDynamicMeshComponent.h.
References Category.
UFUNCTION() [31/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active secondary wireframe override render material
Definition at line 556 of file BaseDynamicMeshComponent.h.
References Category, and SecondaryWireframeMaterialOverride.
UFUNCTION() [32/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active wireframe override render material
Definition at line 518 of file BaseDynamicMeshComponent.h.
References Category, and WireframeMaterialOverride.
UFUNCTION() [33/34]
UBaseDynamicMeshComponent::UFUNCTION () const inline
Returns
active secondary render material
Definition at line 466 of file BaseDynamicMeshComponent.h.
References Category.
UFUNCTION() [34/34]
UBaseDynamicMeshComponent::UFUNCTION () inline
Configure whether wireframe rendering is enabled or not.
Definition at line 260 of file BaseDynamicMeshComponent.h.
References Category, and UFUNCTION().
UPROPERTY() [1/14]
UBaseDynamicMeshComponent::UPROPERTY () protected
UPROPERTY() [2/14]
UBaseDynamicMeshComponent::UPROPERTY () protected
UPROPERTY() [3/14]
UBaseDynamicMeshComponent::UPROPERTY ()
Enable/disable Raytracing support on this Mesh, if Raytracing is currently enabled in the Project Settings.
Use SetEnableRaytracing() to configure this flag in Blueprints/C++.
References bool, and Category.
UPROPERTY() [4/14]
UBaseDynamicMeshComponent::UPROPERTY () protected
Controls whether to use the dynamic or static draw path.
References Category.
UPROPERTY() [5/14]
UBaseDynamicMeshComponent::UPROPERTY ()
UPROPERTY() [6/14]
UBaseDynamicMeshComponent::UPROPERTY () protected
UPROPERTY() [7/14]
UBaseDynamicMeshComponent::UPROPERTY () protected
References UPROPERTY().
UPROPERTY() [8/14]
UBaseDynamicMeshComponent::UPROPERTY ()
Enable use of per-triangle facet normals in place of mesh normals.
References bool, Category, and meta.
UPROPERTY() [9/14]
UBaseDynamicMeshComponent::UPROPERTY ()
This flag controls whether Editor View Mode Overrides are enabled for this mesh.
For example, this controls hidden-line removal on the wireframe in Wireframe View Mode, and whether the normal map will be disabled in Lighting-Only View Mode, as well as various other things. Use SetViewModeOverridesEnabled() to control this setting in Blueprints/C++.
References bool, Category, and meta.
UPROPERTY() [10/14]
UBaseDynamicMeshComponent::UPROPERTY ()
If true, render the Wireframe on top of the Shaded Mesh.
References bool, Category, and meta.
Referenced by OnRenderingStateChanged(), UE_DEPRECATED(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [11/14]
UBaseDynamicMeshComponent::UPROPERTY ()
References Category, meta, None, and UPROPERTY().
UPROPERTY() [12/14]
UBaseDynamicMeshComponent::UPROPERTY ()
Color Space Transform that will be applied to the colors stored in the DynamicMesh Attribute Color Overlay when constructing render buffers.
Default is "No Transform", ie color R/G/B/A will be independently converted from 32-bit float to 8-bit by direct mapping. LinearToSRGB mode will apply SRGB conversion, ie assumes colors in the Mesh are in Linear space. This will produce the same behavior as UStaticMesh. SRGBToLinear mode will invert SRGB conversion, ie assumes colors in the Mesh are in SRGB space.
References Category, and meta.
UPROPERTY() [13/14]
UBaseDynamicMeshComponent::UPROPERTY ()
Constant Color used when Override Color Mode is set to Constant.
References Category, and meta.
UPROPERTY() [14/14]
UBaseDynamicMeshComponent::UPROPERTY ()
Constant Color used when Override Color Mode is set to Constant.
References Category, and meta.
Friends And Related Symbol Documentation
FBaseDynamicMeshSceneProxy
friend class FBaseDynamicMeshSceneProxy friend
Definition at line 720 of file BaseDynamicMeshComponent.h.
References FBaseDynamicMeshSceneProxy.
Referenced by FBaseDynamicMeshSceneProxy, GetBaseSceneProxy(), and UDynamicMeshComponent::GetBaseSceneProxy().
FGeometryFrameworkModule
friend class FGeometryFrameworkModule friend
Definition at line 716 of file BaseDynamicMeshComponent.h.
References FGeometryFrameworkModule.
Referenced by FGeometryFrameworkModule.
Field Documentation
bDrawSecondaryBuffers
bool UBaseDynamicMeshComponent::bDrawSecondaryBuffers = true protected
Definition at line 488 of file BaseDynamicMeshComponent.h.
DefaultVertexColorMaterial
GEOMETRYFRAMEWORK_API UMaterialInterface* UBaseDynamicMeshComponent::DefaultVertexColorMaterial static private
Definition at line 726 of file BaseDynamicMeshComponent.h.
DefaultWireframeMaterial
GEOMETRYFRAMEWORK_API UMaterialInterface* UBaseDynamicMeshComponent::DefaultWireframeMaterial static private
Definition at line 725 of file BaseDynamicMeshComponent.h.
SecondaryWireframeMaterialOverride
TObjectPtr<UMaterialInterface> UBaseDynamicMeshComponent::SecondaryWireframeMaterialOverride = nullptr protected
Definition at line 564 of file BaseDynamicMeshComponent.h.
Referenced by HasOverrideSecondaryWireframeRenderMaterial(), and UFUNCTION().
WireframeMaterialOverride
TObjectPtr<UMaterialInterface> UBaseDynamicMeshComponent::WireframeMaterialOverride = nullptr protected
Definition at line 526 of file BaseDynamicMeshComponent.h.
Referenced by HasOverrideWireframeRenderMaterial(), and UFUNCTION().
The documentation for this class was generated from the following file:
BaseDynamicMeshComponent.h