Unreal Engine 5.6 C++ API: UE::Geometry::TDistPoint3Triangle3< Real > Class Template Reference
UE::Geometry::TDistPoint3Triangle3< Real > Class Template Reference
Compute unsigned distance between 3D Point and 3D Triangle.
#include "DistPoint3Triangle3.h"
Public Member Functions
TDistPoint3Triangle3 (const TVector< Real > &PointIn, const TTriangle3< Real > &TriangleIn)
Real ComputeResult ()
Real Get ()
Real GetSquared ()
Data Fields
TVector< Real > ClosestTrianglePoint
TVector< Real > Point
TTriangle3< Real > Triangle
TVector< Real > TriangleBaryCoords
Private Member Functions
void GetMinEdge02 (Real const &a11, Real const &b1, TVector2< Real > &p) const
void GetMinEdge12 (Real const &a01, Real const &a11, Real const &b1, Real const &f10, Real const &f01, TVector2< Real > &p) const
void GetMinInterior (TVector2< Real > const &p0, Real const &h0, TVector2< Real > const &p1, Real const &h1, TVector2< Real > &p) const
Detailed Description
template<typename Real>
class UE::Geometry::TDistPoint3Triangle3< Real >
Compute unsigned distance between 3D Point and 3D Triangle.
Definition at line 22 of file DistPoint3Triangle3.h.
Constructor & Destructor Documentation
TDistPoint3Triangle3()
template<typename Real> UE::Geometry::TDistPoint3Triangle3< Real >::TDistPoint3Triangle3 (const TVector< Real > & PointIn, const TTriangle3< Real > & TriangleIn) inline
Definition at line 34 of file DistPoint3Triangle3.h.
Member Function Documentation
ComputeResult()
template<typename Real> Real UE::Geometry::TDistPoint3Triangle3< Real >::ComputeResult () inline
Definition at line 49 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistPoint3Triangle3< float >::Get(), and UE::Geometry::TDistPoint3Triangle3< float >::GetSquared().
Get()
template<typename Real> Real UE::Geometry::TDistPoint3Triangle3< Real >::Get () inline
Definition at line 40 of file DistPoint3Triangle3.h.
GetMinEdge02()
template<typename Real> void UE::Geometry::TDistPoint3Triangle3< Real >::GetMinEdge02 (Real const & a11, Real const & b1, TVector2< Real > & p) const inline private
Definition at line 199 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult().
GetMinEdge12()
template<typename Real> void UE::Geometry::TDistPoint3Triangle3< Real >::GetMinEdge12 (Real const & a01, Real const & a11, Real const & b1, Real const & f10, Real const & f01, TVector2< Real > & p) const inline private
Definition at line 216 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult().
GetMinInterior()
template<typename Real> void UE::Geometry::TDistPoint3Triangle3< Real >::GetMinInterior (TVector2< Real > const & p0, Real const & h0, TVector2< Real > const & p1, Real const & h1, TVector2< Real > & p) const inline private
Definition at line 240 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult().
GetSquared()
template<typename Real> Real UE::Geometry::TDistPoint3Triangle3< Real >::GetSquared () inline
Definition at line 44 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestPoint_LinearSearch(), and UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleDistance().
Field Documentation
ClosestTrianglePoint
template<typename Real> TVector<Real> UE::Geometry::TDistPoint3Triangle3< Real >::ClosestTrianglePoint
Definition at line 31 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestPoint(), and UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestPoint_LinearSearch().
Point
template<typename Real> TVector<Real> UE::Geometry::TDistPoint3Triangle3< Real >::Point
Definition at line 26 of file DistPoint3Triangle3.h.
Triangle
template<typename Real> TTriangle3<Real> UE::Geometry::TDistPoint3Triangle3< Real >::Triangle
Definition at line 27 of file DistPoint3Triangle3.h.
TriangleBaryCoords
template<typename Real> TVector<Real> UE::Geometry::TDistPoint3Triangle3< Real >::TriangleBaryCoords
Definition at line 30 of file DistPoint3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
The documentation for this class was generated from the following file:
DistPoint3Triangle3.h