Unreal Engine 5.6 C++ API: FFileHandleRegistry Class Reference
FFileHandleRegistry Class Reference abstract
#include "PlatformFileCommon.h"
Public Member Functions
FFileHandleRegistry (int32 InMaxOpenHandles)
virtual ~FFileHandleRegistry ()=default
FRegisteredFileHandle * InitialOpenFile (const TCHAR *Filename)
void TrackEndRead (FRegisteredFileHandle *Handle)
bool TrackStartRead (FRegisteredFileHandle *Handle)
void UnTrackAndCloseFile (FRegisteredFileHandle *Handle)
Protected Member Functions
virtual void PlatformCloseFile (FRegisteredFileHandle *)=0
virtual FRegisteredFileHandle * PlatformInitialOpenFile (const TCHAR *Filename)=0
virtual bool PlatformReopenFile (FRegisteredFileHandle *)=0
Private Member Functions
void FreeHandles ()
void LinkToTail (FRegisteredFileHandle *Handle)
FRegisteredFileHandle * PopFromHead ()
void UnLink (FRegisteredFileHandle *Handle)
Private Attributes
FThreadSafeCounter HandlesCurrentlyInUse
FCriticalSection LockSection
int32 MaxOpenHandles = 0
FRegisteredFileHandle * OpenAndAvailableForClosingHead = nullptr
FRegisteredFileHandle * OpenAndAvailableForClosingTail = nullptr
Detailed Description
Definition at line 28 of file PlatformFileCommon.h.
Constructor & Destructor Documentation
FFileHandleRegistry()
FFileHandleRegistry::FFileHandleRegistry (int32 InMaxOpenHandles) inline
Definition at line 31 of file PlatformFileCommon.h.
References MaxOpenHandles.
~FFileHandleRegistry()
virtual FFileHandleRegistry::~FFileHandleRegistry () virtual default
Member Function Documentation
FreeHandles()
void FFileHandleRegistry::FreeHandles () inline private
Definition at line 131 of file PlatformFileCommon.h.
References HandlesCurrentlyInUse, LockSection, FGenericPlatformMisc::LowLevelOutputDebugString(), MaxOpenHandles, PlatformCloseFile(), PopFromHead(), and TEXT.
Referenced by InitialOpenFile(), and TrackStartRead().
InitialOpenFile()
FRegisteredFileHandle * FFileHandleRegistry::InitialOpenFile (const TCHAR * Filename) inline nodiscard
Definition at line 37 of file PlatformFileCommon.h.
References Filename, FreeHandles(), Handle, HandlesCurrentlyInUse, LinkToTail(), LockSection, MaxOpenHandles, and PlatformInitialOpenFile().
LinkToTail()
void FFileHandleRegistry::LinkToTail (FRegisteredFileHandle * Handle) inline private
Definition at line 155 of file PlatformFileCommon.h.
References check, Handle, OpenAndAvailableForClosingHead, and OpenAndAvailableForClosingTail.
Referenced by InitialOpenFile(), and TrackEndRead().
PlatformCloseFile()
virtual void FFileHandleRegistry::PlatformCloseFile (FRegisteredFileHandle *) protected pure virtual
Referenced by FreeHandles(), and UnTrackAndCloseFile().
PlatformInitialOpenFile()
virtual FRegisteredFileHandle * FFileHandleRegistry::PlatformInitialOpenFile (const TCHAR * Filename) protected pure virtual
References Filename.
Referenced by InitialOpenFile().
PlatformReopenFile()
virtual bool FFileHandleRegistry::PlatformReopenFile (FRegisteredFileHandle *) protected pure virtual
Referenced by TrackStartRead().
PopFromHead()
FRegisteredFileHandle * FFileHandleRegistry::PopFromHead () inline private
Definition at line 199 of file PlatformFileCommon.h.
References check, OpenAndAvailableForClosingHead, and OpenAndAvailableForClosingTail.
Referenced by FreeHandles(), and UnLink().
TrackEndRead()
void FFileHandleRegistry::TrackEndRead (FRegisteredFileHandle * Handle) inline
Definition at line 114 of file PlatformFileCommon.h.
References Handle, LinkToTail(), and LockSection.
TrackStartRead()
bool FFileHandleRegistry::TrackStartRead (FRegisteredFileHandle * Handle) inline nodiscard
Definition at line 79 of file PlatformFileCommon.h.
References FreeHandles(), Handle, HandlesCurrentlyInUse, LockSection, MaxOpenHandles, PlatformReopenFile(), and UnLink().
UnLink()
void FFileHandleRegistry::UnLink (FRegisteredFileHandle * Handle) inline private
Definition at line 173 of file PlatformFileCommon.h.
References check, Handle, OpenAndAvailableForClosingHead, OpenAndAvailableForClosingTail, PopFromHead(), and verify.
Referenced by TrackStartRead(), and UnTrackAndCloseFile().
UnTrackAndCloseFile()
void FFileHandleRegistry::UnTrackAndCloseFile (FRegisteredFileHandle * Handle) inline
Definition at line 58 of file PlatformFileCommon.h.
References check, Handle, HandlesCurrentlyInUse, LockSection, PlatformCloseFile(), and UnLink().
Field Documentation
HandlesCurrentlyInUse
FThreadSafeCounter FFileHandleRegistry::HandlesCurrentlyInUse private
Definition at line 232 of file PlatformFileCommon.h.
Referenced by FreeHandles(), InitialOpenFile(), TrackStartRead(), and UnTrackAndCloseFile().
LockSection
FCriticalSection FFileHandleRegistry::LockSection private
Definition at line 225 of file PlatformFileCommon.h.
Referenced by FreeHandles(), InitialOpenFile(), TrackEndRead(), TrackStartRead(), and UnTrackAndCloseFile().
MaxOpenHandles
int32 FFileHandleRegistry::MaxOpenHandles = 0 private
Definition at line 227 of file PlatformFileCommon.h.
Referenced by FFileHandleRegistry(), FreeHandles(), InitialOpenFile(), and TrackStartRead().
OpenAndAvailableForClosingHead
FRegisteredFileHandle* FFileHandleRegistry::OpenAndAvailableForClosingHead = nullptr private
Definition at line 229 of file PlatformFileCommon.h.
Referenced by LinkToTail(), PopFromHead(), and UnLink().
OpenAndAvailableForClosingTail
FRegisteredFileHandle* FFileHandleRegistry::OpenAndAvailableForClosingTail = nullptr private
Definition at line 230 of file PlatformFileCommon.h.
Referenced by LinkToTail(), PopFromHead(), and UnLink().
The documentation for this class was generated from the following file:
PlatformFileCommon.h