Unreal Engine 5.6 C++ API: FMemoryImageWriter Class Reference
FMemoryImageWriter Class Reference
#include "MemoryImageWriter.h"
Public Member Functions
FMemoryImageWriter (FMemoryImage &InImage)
FMemoryImageWriter (FMemoryImageSection *InSection)
~FMemoryImageWriter ()
int32 AddTypeDependency (const FTypeLayoutDesc &TypeDesc)
const FPlatformTypeLayoutParameters & GetHostLayoutParams () const
FMemoryImage & GetImage () const
uint32 GetOffset () const
FPointerTableBase & GetPointerTable () const
const FPlatformTypeLayoutParameters & GetTargetLayoutParams () const
bool Is32BitTarget () const
bool Is64BitTarget () const
const FPointerTableBase * TryGetPrevPointerTable () const
template<typename T>
uint32 WriteAlignment ()
uint32 WriteAlignment (uint32 Alignment)
template<typename T>
uint32 WriteBytes (const T &Data)
uint32 WriteBytes (const void *Data, uint32 Size)
uint32 WriteFMemoryImageName (int32 NumBytes, const FName &Name)
uint32 WriteFScriptName (const FScriptName &Name)
uint32 WriteNullPointer ()
template<typename T>
void WriteObject (const T &Object)
void WriteObject (const void *Object, const FTypeLayoutDesc &TypeDesc)
void WriteObjectArray (const void *Object, const FTypeLayoutDesc &TypeDesc, uint32_t NumArray)
void WritePaddingToSize (uint32 Offset)
FMemoryImageWriter WritePointer (const FTypeLayoutDesc &StaticTypeDesc, const FTypeLayoutDesc &DerivedTypeDesc, uint32 *OutOffsetToBase=nullptr)
FMemoryImageWriter WritePointer (const FTypeLayoutDesc &TypeDesc)
uint32 WriteRawPointerSizedBytes (uint64 PointerValue)
template<typename T>
void WriteRootObject (const T &Object)
void WriteRootObject (const void *Object, const FTypeLayoutDesc &TypeDesc)
uint32 WriteVTable (const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
Data Fields
FMemoryImageSection * Section
Detailed Description
Definition at line 13 of file MemoryImageWriter.h.
Constructor & Destructor Documentation
FMemoryImageWriter() [1/2]
FMemoryImageWriter::FMemoryImageWriter (FMemoryImage & InImage) explicit
Referenced by WritePointer(), and WritePointer().
FMemoryImageWriter() [2/2]
FMemoryImageWriter::FMemoryImageWriter (FMemoryImageSection * InSection) explicit
~FMemoryImageWriter()
FMemoryImageWriter::~FMemoryImageWriter ()
Member Function Documentation
AddTypeDependency()
int32 FMemoryImageWriter::AddTypeDependency (const FTypeLayoutDesc & TypeDesc)
GetHostLayoutParams()
const FPlatformTypeLayoutParameters & FMemoryImageWriter::GetHostLayoutParams () const
GetImage()
FMemoryImage & FMemoryImageWriter::GetImage () const
GetOffset()
uint32 FMemoryImageWriter::GetOffset () const
GetPointerTable()
FPointerTableBase & FMemoryImageWriter::GetPointerTable () const
Referenced by Freeze::IntrinsicWriteMemoryImage().
GetTargetLayoutParams()
const FPlatformTypeLayoutParameters & FMemoryImageWriter::GetTargetLayoutParams () const
Referenced by Is32BitTarget().
Is32BitTarget()
bool FMemoryImageWriter::Is32BitTarget () const inline
Definition at line 26 of file MemoryImageWriter.h.
References GetTargetLayoutParams(), and FPlatformTypeLayoutParameters::Is32Bit().
Referenced by Is64BitTarget(), TBitArray< typename Allocator::BitArrayAllocator >::WriteMemoryImage(), TSet< class UObject * >::WriteMemoryImage(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
Is64BitTarget()
bool FMemoryImageWriter::Is64BitTarget () const inline
Definition at line 27 of file MemoryImageWriter.h.
References Is32BitTarget().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::WriteMemoryImage().
TryGetPrevPointerTable()
const FPointerTableBase * FMemoryImageWriter::TryGetPrevPointerTable () const
Referenced by Freeze::IntrinsicWriteMemoryImage(), Freeze::IntrinsicWriteMemoryImage(), WriteObject(), and WriteRootObject().
WriteAlignment() [1/2]
template<typename T> uint32 FMemoryImageWriter::WriteAlignment () inline
Definition at line 62 of file MemoryImageWriter.h.
References WriteAlignment().
Referenced by WriteAlignment().
WriteAlignment() [2/2]
uint32 FMemoryImageWriter::WriteAlignment (uint32 Alignment)
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
WriteBytes() [1/2]
template<typename T> uint32 FMemoryImageWriter::WriteBytes (const T & Data) inline
Definition at line 68 of file MemoryImageWriter.h.
References WriteBytes().
WriteBytes() [2/2]
uint32 FMemoryImageWriter::WriteBytes (const void * Data, uint32 Size)
References TSequenceHistory< HistorySize >::Size.
Referenced by Freeze::IntrinsicWriteMemoryImage(), Freeze::IntrinsicWriteMemoryImage(), WriteBytes(), RangedForIteratorType< FAnimNextTraitEventPtr >::WriteMemoryImage(), TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy >::WriteMemoryImage(), TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >::WriteMemoryImage(), THashTable< FMemoryImageAllocator >::WriteMemoryImage(), TSet< class UObject * >::WriteMemoryImage(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
WriteFMemoryImageName()
uint32 FMemoryImageWriter::WriteFMemoryImageName (int32 NumBytes, const FName & Name)
References Name.
WriteFScriptName()
uint32 FMemoryImageWriter::WriteFScriptName (const FScriptName & Name)
References Name.
WriteNullPointer()
uint32 FMemoryImageWriter::WriteNullPointer ()
Referenced by Freeze::IntrinsicWriteMemoryImage(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage(), and TMemoryImagePtr< T >::WriteMemoryImageWithDerivedType().
WriteObject() [1/2]
template<typename T> void FMemoryImageWriter::WriteObject (const T & Object) inline
Definition at line 48 of file MemoryImageWriter.h.
References GetTypeLayoutDesc(), Object, TryGetPrevPointerTable(), and WriteObject().
WriteObject() [2/2]
void FMemoryImageWriter::WriteObject (const void * Object, const FTypeLayoutDesc & TypeDesc)
References Object.
Referenced by Freeze::IntrinsicWriteMemoryImage(), Freeze::IntrinsicWriteMemoryImage(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage(), TMemoryImagePtr< T >::WriteMemoryImageWithDerivedType(), and WriteObject().
WriteObjectArray()
void FMemoryImageWriter::WriteObjectArray (const void * Object, const FTypeLayoutDesc & TypeDesc, uint32_t NumArray)
References Object.
WritePaddingToSize()
void FMemoryImageWriter::WritePaddingToSize (uint32 Offset)
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
WritePointer() [1/2]
FMemoryImageWriter FMemoryImageWriter::WritePointer (const FTypeLayoutDesc & StaticTypeDesc, const FTypeLayoutDesc & DerivedTypeDesc, uint32 * OutOffsetToBase = nullptr)
References FMemoryImageWriter().
Referenced by Freeze::IntrinsicWriteMemoryImage(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage(), and TMemoryImagePtr< T >::WriteMemoryImageWithDerivedType().
WritePointer() [2/2]
FMemoryImageWriter FMemoryImageWriter::WritePointer (const FTypeLayoutDesc & TypeDesc)
References FMemoryImageWriter().
WriteRawPointerSizedBytes()
uint32 FMemoryImageWriter::WriteRawPointerSizedBytes (uint64 PointerValue)
WriteRootObject() [1/2]
template<typename T> void FMemoryImageWriter::WriteRootObject (const T & Object) inline
Definition at line 55 of file MemoryImageWriter.h.
References GetTypeLayoutDesc(), Object, TryGetPrevPointerTable(), and WriteRootObject().
WriteRootObject() [2/2]
void FMemoryImageWriter::WriteRootObject (const void * Object, const FTypeLayoutDesc & TypeDesc)
References Object.
Referenced by WriteRootObject().
WriteVTable()
uint32 FMemoryImageWriter::WriteVTable (const FTypeLayoutDesc & TypeDesc, const FTypeLayoutDesc & DerivedTypeDesc)
Field Documentation
Section
FMemoryImageSection* FMemoryImageWriter::Section
Definition at line 74 of file MemoryImageWriter.h.
The documentation for this class was generated from the following file:
MemoryImageWriter.h