Unreal Engine 5.6 C++ API: FPackageFileSummary Struct Reference
FPackageFileSummary Struct Reference
A "table of contents" for an Unreal package file.
#include "PackageFileSummary.h"
Public Member Functions
FPackageFileSummary ()
Constructor.
FPackageFileSummary (const FPackageFileSummary &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPackageFileSummary (FPackageFileSummary &&)=default
const FCustomVersionContainer & GetCustomVersionContainer () const
int32 GetFileVersionLicenseeUE () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS FPackageFileVersion GetFileVersionUE () const
uint32 GetPackageFlags () const
Get the summary package flags.
FPackageFileSummary & operator= (const FPackageFileSummary &)=default
FPackageFileSummary & operator= (FPackageFileSummary &&)=default
void SetCustomVersionContainer (const FCustomVersionContainer &InContainer)
void SetFileVersions (const int32 EpicUE4, const int32 EpicUE5, const int32 LicenseeUE, const bool bInSaveUnversioned=false)
Used to manually set the package file and licensee versions.
void SetPackageFlags (uint32 InPackageFlags)
Set the summary package flags while stripping out temporary flags (i.e.
UE_DEPRECATED (5.0, "Use GetFileVersionLicenseeUE instead") int32 GetFileVersionLicenseeUE4() const
UE_DEPRECATED (5.0, "Use the other overload of SetFileVersions that takes an UE5 version as well") inline void SetFileVersions(const int32 EpicUE
UE_DEPRECATED (5.0, "Use UEVer instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") int32 GetFileVersionUE4() const
Data Fields
int32 AssetRegistryDataOffset
Location into the file on disk for the asset registry tag data.
const int32 const bool bInSaveUnversioned
int64 BulkDataStartOffset
Offset to the location in the file where the bulkdata starts.
bool bUnversioned
If true, this file will not be saved with version numbers or was saved without version numbers.
int32 CellExportCount
Number of cells contained in this package.
int32 CellExportOffset
Location into the file on disk for the CellExportMap data.
int32 CellImportCount
Number of cell imports contained in this package.
int32 CellImportOffset
Location into the file on disk for the CellImportMap data.
TArray< int32 > ChunkIDs
Streaming install ChunkIDs.
FEngineVersion CompatibleWithEngineVersion
Engine version this package is compatible with.
uint32 CompressionFlags
Flags used to compress the file on save and uncompress on load.
int32 DataResourceOffset
Location into the file of the data resource(s)
int32 DependsOffset
Location into the file on disk for the DependsMap data.
int32 ExportCount
Number of exports contained in this package.
int32 ExportOffset
Location into the file on disk for the ExportMap data.
int32 GatherableTextDataCount
Number of gatherable text data items in this package.
int32 GatherableTextDataOffset
Location into the file on disk for the gatherable text data items.
TArray< FGenerationInfo > Generations
Data about previous versions of this package.
int32 ImportCount
Number of imports contained in this package.
int32 ImportOffset
Location into the file on disk for the ImportMap data.
const int32 LicenseeUE
FString LocalizationId
Localization ID of this package.
int32 MetaDataOffset
Location into the file on disk for the MetaData data.
int32 NameCount
Number of names used in this package.
int32 NameOffset
Location into the file on disk for the name data.
int32 NamesReferencedFromExportDataCount
Number of names that are referenced from serialized export data (sorted first in the name map)
FString PackageName
The package name the file was last saved with.
uint32 PackageSource
Value that is used to determine if the package was saved by Epic (or licensee) or by a modder, etc.
int64 PayloadTocOffset
Location into the file on disk for the payload table of contents data.
int32 PreloadDependencyCount
int32 PreloadDependencyOffset
Location into the file on disk for the preload dependency data.
FEngineVersion SavedByEngineVersion
Engine version this package was saved with.
int32 SearchableNamesOffset
Location into the file on disk for the SearchableNamesMap data.
int32 SoftObjectPathsCount
Number of soft object paths references contained in this package.
int32 SoftObjectPathsOffset
Location into the file on disk for the soft object paths reference list.
int32 SoftPackageReferencesCount
Number of soft package references contained in this package.
int32 SoftPackageReferencesOffset
Location into the file on disk for the soft package reference list.
int32 Tag
Magic tag compared against PACKAGE_FILE_TAG to ensure that package is an Unreal package.
int32 ThumbnailTableOffset
Thumbnail table offset.
int32 TotalHeaderSize
Total size of all information that needs to be read in to create a FLinkerLoad.
int32 WorldTileInfoDataOffset
Offset to the location in the file where the FWorldTileInfo data starts.
Private Member Functions
void InvalidateFileVersion ()
Set the UE4 version to below the oldest loadable version.
Private Attributes
FCustomVersionContainer CustomVersionContainer
int32 FileVersionLicenseeUE
FPackageFileVersion FileVersionUE
uint32 PackageFlags
The flags for the package.
FIoHash SavedHash
Hash of the Package's bytes when it was saved to disk.
Friends
FArchive & operator<< (FArchive &Ar, FPackageFileSummary &Sum)
I/O functions.
void operator<< (FStructuredArchive::FSlot Slot, FPackageFileSummary &Sum)
Detailed Description
A "table of contents" for an Unreal package file.
Stored at the top of the file.
Definition at line 56 of file PackageFileSummary.h.
Constructor & Destructor Documentation
FPackageFileSummary() [1/3]
FPackageFileSummary::FPackageFileSummary ()
Constructor.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FPackageFileSummary(), FPackageFileSummary(), operator<<, operator<<, operator=(), and operator=().
FPackageFileSummary() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FPackageFileSummary::FPackageFileSummary (FPackageFileSummary &&) default
References FPackageFileSummary().
FPackageFileSummary() [3/3]
FPackageFileSummary::FPackageFileSummary (const FPackageFileSummary &) default
References FPackageFileSummary().
Member Function Documentation
GetCustomVersionContainer()
const FCustomVersionContainer & FPackageFileSummary::GetCustomVersionContainer () const inline
Definition at line 313 of file PackageFileSummary.h.
References CustomVersionContainer.
GetFileVersionLicenseeUE()
int32 FPackageFileSummary::GetFileVersionLicenseeUE () const inline
Definition at line 302 of file PackageFileSummary.h.
References FileVersionLicenseeUE.
Referenced by UE_DEPRECATED().
GetFileVersionUE()
PRAGMA_ENABLE_DEPRECATION_WARNINGS FPackageFileVersion FPackageFileSummary::GetFileVersionUE () const inline
Definition at line 291 of file PackageFileSummary.h.
References FileVersionUE.
GetPackageFlags()
uint32 FPackageFileSummary::GetPackageFlags () const inline
Get the summary package flags.
Definition at line 357 of file PackageFileSummary.h.
References PackageFlags.
InvalidateFileVersion()
void FPackageFileSummary::InvalidateFileVersion () inline private
Set the UE4 version to below the oldest loadable version.
This is used when an error is encountered during serialization and we need to prevent the use of the package. When calling this make sure you log a warning with the 'LogLinker' category to inform the user of the problem.
Definition at line 383 of file PackageFileSummary.h.
References FPackageFileVersion::CreateUE4Version(), FileVersionUE, and VER_UE4_OLDEST_LOADABLE_PACKAGE.
operator=() [1/2]
FPackageFileSummary & FPackageFileSummary::operator= (const FPackageFileSummary &) default
References FPackageFileSummary(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FPackageFileSummary & FPackageFileSummary::operator= (FPackageFileSummary &&) default
References FPackageFileSummary().
SetCustomVersionContainer()
void FPackageFileSummary::SetCustomVersionContainer (const FCustomVersionContainer & InContainer)
References InContainer.
SetFileVersions()
void FPackageFileSummary::SetFileVersions (const int32 EpicUE4, const int32 EpicUE5, const int32 LicenseeUE, const bool bInSaveUnversioned = false)
Used to manually set the package file and licensee versions.
References bInSaveUnversioned, and LicenseeUE.
SetPackageFlags()
void FPackageFileSummary::SetPackageFlags (uint32 InPackageFlags)
Set the summary package flags while stripping out temporary flags (i.e.
NewlyCreated, IsSaving)
UE_DEPRECATED() [1/3]
FPackageFileSummary::UE_DEPRECATED (5. 0, "Use GetFileVersionLicenseeUE instead") const inline
Definition at line 307 of file PackageFileSummary.h.
References GetFileVersionLicenseeUE().
UE_DEPRECATED() [2/3]
FPackageFileSummary::UE_DEPRECATED (5. 0, "Use the other overload of SetFileVersions that takes an UE5 version as well") const
UE_DEPRECATED() [3/3]
FPackageFileSummary::UE_DEPRECATED (5. 0, "Use UEVer instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") const inline
Definition at line 296 of file PackageFileSummary.h.
References FileVersionUE.
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FPackageFileSummary & Sum) friend
I/O functions.
References FPackageFileSummary(), and Ar.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FPackageFileSummary & Sum) friend
References FPackageFileSummary().
Field Documentation
AssetRegistryDataOffset
int32 FPackageFileSummary::AssetRegistryDataOffset
Location into the file on disk for the asset registry tag data.
Definition at line 244 of file PackageFileSummary.h.
bInSaveUnversioned
const int32 const bool FPackageFileSummary::bInSaveUnversioned
Initial value:
= false)
    {
        SetFileVersions(EpicUE, GPackageFileUEVersion.FileVersionUE5, LicenseeUE, bInSaveUnversioned);
    }
    void SetToLatestFileVersions(const bool bInSaveUnversioned)
    {
        FileVersionUE = GPackageFileUEVersion;
        FileVersionLicenseeUE = GPackageFileLicenseeUEVersion;
        bUnversioned = bInSaveUnversioned;
    }
    bool IsFileVersionTooOld() const
    {
        return FileVersionUE < VER_UE4_OLDEST_LOADABLE_PACKAGE;
    }
    bool IsFileVersionTooNew() const
    {
        return FileVersionUE.FileVersionUE4 > GPackageFileUEVersion.FileVersionUE4 || FileVersionUE.FileVersionUE5 > GPackageFileUEVersion.FileVersionUE5;
    }
    1 bool IsFileVersionValid() const
Definition at line 324 of file PackageFileSummary.h.
Referenced by SetFileVersions().
BulkDataStartOffset
int64 FPackageFileSummary::BulkDataStartOffset
Offset to the location in the file where the bulkdata starts.
Definition at line 247 of file PackageFileSummary.h.
bUnversioned
bool FPackageFileSummary::bUnversioned
If true, this file will not be saved with version numbers or was saved without version numbers.
In this case they are assumed to be the current version. This is only used for full cooks for distribution because it is hard to guarantee correctness
Definition at line 239 of file PackageFileSummary.h.
CellExportCount
int32 FPackageFileSummary::CellExportCount
Number of cells contained in this package.
Definition at line 153 of file PackageFileSummary.h.
CellExportOffset
int32 FPackageFileSummary::CellExportOffset
Location into the file on disk for the CellExportMap data.
Definition at line 158 of file PackageFileSummary.h.
CellImportCount
int32 FPackageFileSummary::CellImportCount
Number of cell imports contained in this package.
Definition at line 163 of file PackageFileSummary.h.
CellImportOffset
int32 FPackageFileSummary::CellImportOffset
Location into the file on disk for the CellImportMap data.
Definition at line 168 of file PackageFileSummary.h.
ChunkIDs
TArray<int32> FPackageFileSummary::ChunkIDs
Streaming install ChunkIDs.
Definition at line 256 of file PackageFileSummary.h.
CompatibleWithEngineVersion
FEngineVersion FPackageFileSummary::CompatibleWithEngineVersion
Engine version this package is compatible with.
Assets saved by Hotfix releases and engine versions that maintain binary compatibility will have a CompatibleWithEngineVersion.Patch that matches the original release (as opposed to SavedByEngineVersion which will have a patch version of the new release).
Definition at line 223 of file PackageFileSummary.h.
CompressionFlags
uint32 FPackageFileSummary::CompressionFlags
Flags used to compress the file on save and uncompress on load.
Definition at line 228 of file PackageFileSummary.h.
CustomVersionContainer
FCustomVersionContainer FPackageFileSummary::CustomVersionContainer private
Definition at line 69 of file PackageFileSummary.h.
Referenced by GetCustomVersionContainer().
DataResourceOffset
int32 FPackageFileSummary::DataResourceOffset
Location into the file of the data resource(s)
Definition at line 278 of file PackageFileSummary.h.
DependsOffset
int32 FPackageFileSummary::DependsOffset
Location into the file on disk for the DependsMap data.
Definition at line 173 of file PackageFileSummary.h.
ExportCount
int32 FPackageFileSummary::ExportCount
Number of exports contained in this package.
Definition at line 133 of file PackageFileSummary.h.
ExportOffset
int32 FPackageFileSummary::ExportOffset
Location into the file on disk for the ExportMap data.
Definition at line 138 of file PackageFileSummary.h.
FileVersionLicenseeUE
int32 FPackageFileSummary::FileVersionLicenseeUE private
Definition at line 67 of file PackageFileSummary.h.
Referenced by GetFileVersionLicenseeUE().
FileVersionUE
FPackageFileVersion FPackageFileSummary::FileVersionUE private
Definition at line 65 of file PackageFileSummary.h.
Referenced by GetFileVersionUE(), InvalidateFileVersion(), and UE_DEPRECATED().
GatherableTextDataCount
int32 FPackageFileSummary::GatherableTextDataCount
Number of gatherable text data items in this package.
Definition at line 118 of file PackageFileSummary.h.
GatherableTextDataOffset
int32 FPackageFileSummary::GatherableTextDataOffset
Location into the file on disk for the gatherable text data items.
Definition at line 123 of file PackageFileSummary.h.
Generations
TArray<FGenerationInfo> FPackageFileSummary::Generations
Data about previous versions of this package.
Definition at line 212 of file PackageFileSummary.h.
ImportCount
int32 FPackageFileSummary::ImportCount
Number of imports contained in this package.
Definition at line 143 of file PackageFileSummary.h.
ImportOffset
int32 FPackageFileSummary::ImportOffset
Location into the file on disk for the ImportMap data.
Definition at line 148 of file PackageFileSummary.h.
LicenseeUE
const int32 FPackageFileSummary::LicenseeUE
Definition at line 324 of file PackageFileSummary.h.
Referenced by SetFileVersions().
LocalizationId
FString FPackageFileSummary::LocalizationId
Localization ID of this package.
Note
This is copy of the version stored in the package meta-data. It exists here so we can query it without having to load the whole package
Definition at line 113 of file PackageFileSummary.h.
MetaDataOffset
int32 FPackageFileSummary::MetaDataOffset
Location into the file on disk for the MetaData data.
Definition at line 128 of file PackageFileSummary.h.
NameCount
int32 FPackageFileSummary::NameCount
Number of names used in this package.
Definition at line 91 of file PackageFileSummary.h.
NameOffset
int32 FPackageFileSummary::NameOffset
Location into the file on disk for the name data.
Definition at line 96 of file PackageFileSummary.h.
NamesReferencedFromExportDataCount
int32 FPackageFileSummary::NamesReferencedFromExportDataCount
Number of names that are referenced from serialized export data (sorted first in the name map)
Definition at line 268 of file PackageFileSummary.h.
PackageFlags
uint32 FPackageFileSummary::PackageFlags private
The flags for the package.
Definition at line 74 of file PackageFileSummary.h.
Referenced by GetPackageFlags().
PackageName
FString FPackageFileSummary::PackageName
The package name the file was last saved with.
Definition at line 86 of file PackageFileSummary.h.
PackageSource
uint32 FPackageFileSummary::PackageSource
Value that is used to determine if the package was saved by Epic (or licensee) or by a modder, etc.
Definition at line 233 of file PackageFileSummary.h.
PayloadTocOffset
int64 FPackageFileSummary::PayloadTocOffset
Location into the file on disk for the payload table of contents data.
Definition at line 273 of file PackageFileSummary.h.
PreloadDependencyCount
int32 FPackageFileSummary::PreloadDependencyCount
Definition at line 258 of file PackageFileSummary.h.
PreloadDependencyOffset
int32 FPackageFileSummary::PreloadDependencyOffset
Location into the file on disk for the preload dependency data.
Definition at line 263 of file PackageFileSummary.h.
SavedByEngineVersion
FEngineVersion FPackageFileSummary::SavedByEngineVersion
Engine version this package was saved with.
This may differ from CompatibleWithEngineVersion for assets saved with a hotfix release.
Definition at line 217 of file PackageFileSummary.h.
SavedHash
FIoHash FPackageFileSummary::SavedHash private
Hash of the Package's bytes when it was saved to disk.
Accessed through GetSavedHash/SetSavedHash.
Definition at line 199 of file PackageFileSummary.h.
SearchableNamesOffset
int32 FPackageFileSummary::SearchableNamesOffset
Location into the file on disk for the SearchableNamesMap data.
Definition at line 188 of file PackageFileSummary.h.
SoftObjectPathsCount
int32 FPackageFileSummary::SoftObjectPathsCount
Number of soft object paths references contained in this package.
Note
: the soft object path lists slightly duplicate information found in the SoftPackageReferences list
Definition at line 102 of file PackageFileSummary.h.
SoftObjectPathsOffset
int32 FPackageFileSummary::SoftObjectPathsOffset
Location into the file on disk for the soft object paths reference list.
Definition at line 107 of file PackageFileSummary.h.
SoftPackageReferencesCount
int32 FPackageFileSummary::SoftPackageReferencesCount
Number of soft package references contained in this package.
Definition at line 178 of file PackageFileSummary.h.
SoftPackageReferencesOffset
int32 FPackageFileSummary::SoftPackageReferencesOffset
Location into the file on disk for the soft package reference list.
Definition at line 183 of file PackageFileSummary.h.
Tag
int32 FPackageFileSummary::Tag
Magic tag compared against PACKAGE_FILE_TAG to ensure that package is an Unreal package.
Definition at line 61 of file PackageFileSummary.h.
ThumbnailTableOffset
int32 FPackageFileSummary::ThumbnailTableOffset
Thumbnail table offset.
Definition at line 193 of file PackageFileSummary.h.
TotalHeaderSize
int32 FPackageFileSummary::TotalHeaderSize
Total size of all information that needs to be read in to create a FLinkerLoad.
This includes the package file summary, name table and import & export maps.
Definition at line 81 of file PackageFileSummary.h.
WorldTileInfoDataOffset
int32 FPackageFileSummary::WorldTileInfoDataOffset
Offset to the location in the file where the FWorldTileInfo data starts.
Definition at line 251 of file PackageFileSummary.h.
The documentation for this struct was generated from the following file:
PackageFileSummary.h