Unreal Engine 5.6 C++ API: FCurveEditorViewAxisID Struct Reference
FCurveEditorViewAxisID Struct Reference
Identifier for a specific axis on a view.
#include "SCurveEditorView.h"
Public Member Functions
FCurveEditorViewAxisID ()
FCurveEditorViewAxisID (uint8 InIndex)
operator bool () const
Private Member Functions
operator int32 () const
FCurveEditorViewAxisID & operator= (int32 InIndex)
Private Attributes
uint8 Index
friend SCurveEditorView
Friends
uint32 GetTypeHash (FCurveEditorViewAxisID In)
bool operator!= (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B)
bool operator< (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B)
bool operator== (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B)
Detailed Description
Identifier for a specific axis on a view.
These identifiers are transient and should not be stored externally.
Definition at line 38 of file SCurveEditorView.h.
Constructor & Destructor Documentation
FCurveEditorViewAxisID() [1/2]
FCurveEditorViewAxisID::FCurveEditorViewAxisID () inline
Definition at line 40 of file SCurveEditorView.h.
References Index.
Referenced by GetTypeHash, operator!=, operator<, operator=(), and operator==.
FCurveEditorViewAxisID() [2/2]
FCurveEditorViewAxisID::FCurveEditorViewAxisID (uint8 InIndex) inline explicit
Definition at line 43 of file SCurveEditorView.h.
References check, and Index.
Member Function Documentation
operator bool()
FCurveEditorViewAxisID::operator bool () const inline explicit
Definition at line 49 of file SCurveEditorView.h.
References Index.
operator int32()
FCurveEditorViewAxisID::operator int32 () const inline private
Definition at line 76 of file SCurveEditorView.h.
References check, and Index.
operator=()
FCurveEditorViewAxisID & FCurveEditorViewAxisID::operator= (int32 InIndex) inline private
Definition at line 82 of file SCurveEditorView.h.
References FCurveEditorViewAxisID(), check, and Index.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FCurveEditorViewAxisID In) friend
Definition at line 54 of file SCurveEditorView.h.
References FCurveEditorViewAxisID(), GetTypeHash, and Index.
Referenced by GetTypeHash.
operator!=
bool operator!= (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B) friend
Definition at line 64 of file SCurveEditorView.h.
References FCurveEditorViewAxisID(), A, and B.
operator<
bool operator< (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B) friend
Definition at line 69 of file SCurveEditorView.h.
References FCurveEditorViewAxisID(), A, and B.
operator==
bool operator== (FCurveEditorViewAxisID A, FCurveEditorViewAxisID B) friend
Definition at line 59 of file SCurveEditorView.h.
References FCurveEditorViewAxisID(), A, and B.
Field Documentation
Index
uint8 FCurveEditorViewAxisID::Index private
Definition at line 90 of file SCurveEditorView.h.
Referenced by FCurveEditorViewAxisID(), FCurveEditorViewAxisID(), GetTypeHash, operator bool(), operator int32(), and operator=().
SCurveEditorView
friend FCurveEditorViewAxisID::SCurveEditorView private
Definition at line 89 of file SCurveEditorView.h.
The documentation for this struct was generated from the following file:
SCurveEditorView.h