Unreal Engine 5.6 C++ API: FMaterialRenderProxy Class Reference
FMaterialRenderProxy Class Reference abstract
A material render proxy used by the renderer.
#include "MaterialRenderProxy.h"
Public Member Functions
FMaterialRenderProxy (FString InMaterialName)
Default constructor.
virtual ~FMaterialRenderProxy ()
Destructor.
void AddSpecularProfileRT (const USpecularProfile *Ptr)
void AddSubsurfaceProfileRT (const USubsurfaceProfile *Ptr)
void CacheUniformExpressions (FRHICommandListBase &RHICmdList, bool bRecreateUniformBuffer)
Caches uniform expressions for efficient runtime evaluation.
void CacheUniformExpressions_GameThread (bool bRecreateUniformBuffer)
Enqueues a rendering command to cache uniform expressions for efficient runtime evaluation.
void CancelCacheUniformExpressions ()
Cancels an in-flight cache operation.
void EvaluateUniformExpressions (FRHICommandListBase &RHICmdList, FUniformExpressionCache &OutUniformExpressionCache, const FMaterialRenderContext &Context, FUniformExpressionCacheAsyncUpdater *Updater=nullptr) const
Evaluates uniform expressions and stores them in OutUniformExpressionCache.
virtual EBlendableLocation GetBlendableLocation (const FMaterial *Base) const
virtual int32 GetBlendablePriority (const FMaterial *Base) const
int32 GetExpressionCacheSerialNumber () const
virtual const FMaterialRenderProxy * GetFallback (ERHIFeatureLevel::Type InFeatureLevel) const =0
const FMaterial & GetIncompleteMaterialWithFallback (ERHIFeatureLevel::Type InFeatureLevel) const
Finds the FMaterial to use for rendering this FMaterialRenderProxy.
virtual UMaterialInterface * GetMaterialInterface () const
const FString & GetMaterialName () const
virtual const FMaterial * GetMaterialNoFallback (ERHIFeatureLevel::Type InFeatureLevel) const =0
Returns the FMaterial, without using a fallback if the FMaterial doesn't have a valid shader map.
const FMaterial & GetMaterialWithFallback (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy *&OutFallbackMaterialRenderProxy) const
Finds the FMaterial to use for rendering this FMaterialRenderProxy.
const UNeuralProfile * GetNeuralProfileRT () const
virtual bool GetParameterValue (EMaterialParameterType Type, const FHashedMaterialParameterInfo &ParameterInfo, FMaterialParameterValue &OutValue, const FMaterialRenderContext &Context) const =0
bool GetScalarValue (const FHashedMaterialParameterInfo &ParameterInfo, float *OutValue, const FMaterialRenderContext &Context) const
const USpecularProfile * GetSpecularProfileOverrideRT () const
const USpecularProfile * GetSpecularProfileRT (uint32 Index) const
const USubsurfaceProfile * GetSubsurfaceProfileRT () const
const USubsurfaceProfile * GetSubsurfaceProfileRT (uint32 Index) const
bool GetTextureCollectionValue (const FHashedMaterialParameterInfo &ParameterInfo, const UTextureCollection **OutValue, const FMaterialRenderContext &Context) const
bool GetTextureValue (const FHashedMaterialParameterInfo &ParameterInfo, const URuntimeVirtualTexture **OutValue, const FMaterialRenderContext &Context) const
bool GetTextureValue (const FHashedMaterialParameterInfo &ParameterInfo, const USparseVolumeTexture **OutValue, const FMaterialRenderContext &Context) const
bool GetTextureValue (const FHashedMaterialParameterInfo &ParameterInfo, const UTexture **OutValue, const FMaterialRenderContext &Context) const
FName GetUserSceneTextureOutput (const FMaterial *Base) const
virtual bool GetUserSceneTextureOverride (FName &InOutValue) const
bool GetVectorValue (const FHashedMaterialParameterInfo &ParameterInfo, FLinearColor *OutValue, const FMaterialRenderContext &Context) const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InvalidateUniformExpressionCache (bool bRecreateUniformBuffer)
Invalidates the uniform expression cache.
bool IsDeleted () const
bool IsMarkedForGarbageCollection () const
void MarkForGarbageCollection ()
void MarkTransient ()
const uint32 NumSpecularProfileRT () const
const uint32 NumSubsurfaceProfileRT () const
virtual void ReleaseResource () override
Prepares the resource for deletion.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void SetNeuralProfileRT (const UNeuralProfile *Ptr)
void SetSpecularProfileOverrideRT (const USpecularProfile *Ptr)
void SetSubsurfaceProfileRT (const USubsurfaceProfile *Ptr)
void UpdateUniformExpressionCacheIfNeeded (ERHIFeatureLevel::Type InFeatureLevel) const
const FMaterial * UpdateUniformExpressionCacheIfNeeded (FRHICommandListBase &RHICmdList, ERHIFeatureLevel::Type InFeatureLevel) const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static const TSet< FMaterialRenderProxy * > & GetMaterialRenderProxyMap ()
static FCriticalSection & GetMaterialRenderProxyMapLock ()
static bool HasDeferredUniformExpressionCacheRequests ()
static void UpdateDeferredCachedUniformExpressions ()
static void UpdateDeferredCachedUniformExpressions (FRHICommandListBase &RHICmdList, UE::Tasks::FTask *TaskIfAsync=nullptr)
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields
FImmutableSamplerState ImmutableSamplerState
Cached external texture immutable samplers.
FUniformExpressionCacheContainer UniformExpressionCache
Cached uniform expressions.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Private Member Functions
IAllocatedVirtualTexture * AllocateVTStack (FRHICommandListBase &RHICmdList, const FMaterialRenderContext &Context, const FUniformExpressionSet &UniformExpressionSet, const FMaterialVirtualTextureStack &VTStack) const
virtual void FinishCacheUniformExpressions () const
IAllocatedVirtualTexture * GetPreallocatedVTStack (const FMaterialRenderContext &Context, const FUniformExpressionSet &UniformExpressionSet, const FMaterialVirtualTextureStack &VTStack) const
virtual void StartCacheUniformExpressions () const
Private Attributes
uint8 bHasVirtualTextureCallbacks: 1
If any VT producer destroyed callbacks have been registered.
uint8 bMarkedTransient: 1
Set true if this is a transient, one frame object.
uint8 DeletedFlag: 1
uint8 MarkedForGarbageCollection: 1
For tracking down a bug accessing a deleted proxy.
FString MaterialName
UE::FMutex Mutex
Mutex for locking uniform expression invalidation / evaluation for this material.
const UNeuralProfile * NeuralProfileRT
uint8 ReleaseResourceFlag: 1
const USpecularProfile * SpecularProfileOverrideRT = nullptr
TArray< const USpecularProfile * > SpecularProfilesRT
const USubsurfaceProfile * SubsurfaceProfileRT
0 if not set, game thread pointer, do not dereference, only for comparison
TArray< const USubsurfaceProfile * > SubsurfaceProfilesRT
int32 UniformExpressionCacheSerialNumber = 0
Incremented each time UniformExpressionCache is modified.
Static Private Attributes
static TSet< FMaterialRenderProxy * > DeferredUniformExpressionCacheRequests
static UE::FMutex DeferredUniformExpressionCacheRequestsMutex
static TSet< FMaterialRenderProxy * > MaterialRenderProxyMap
Tracks all material render proxies in all scenes.
static FCriticalSection MaterialRenderProxyMapLock
Lock that guards the access to the render proxy map.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A material render proxy used by the renderer.
Definition at line 96 of file MaterialRenderProxy.h.
Constructor & Destructor Documentation
FMaterialRenderProxy()
FMaterialRenderProxy::FMaterialRenderProxy (FString InMaterialName)
Default constructor.
Referenced by FColoredMaterialRenderProxy::FColoredMaterialRenderProxy(), FLandscapeDebugMaterialRenderProxy::FLandscapeDebugMaterialRenderProxy(), FLandscapeLayerUsageRenderProxy::FLandscapeLayerUsageRenderProxy(), FLandscapeMaskMaterialRenderProxy::FLandscapeMaskMaterialRenderProxy(), FLandscapeSelectMaterialRenderProxy::FLandscapeSelectMaterialRenderProxy(), FOverrideSelectionColorMaterialRenderProxy::FOverrideSelectionColorMaterialRenderProxy(), FColoredMaterialRenderProxy::GetFallback(), FLandscapeDebugMaterialRenderProxy::GetFallback(), FLandscapeLayerUsageRenderProxy::GetFallback(), FLandscapeMaskMaterialRenderProxy::GetFallback(), FLandscapeSelectMaterialRenderProxy::GetFallback(), GetFallback(), FOverrideSelectionColorMaterialRenderProxy::GetFallback(), and GetMaterialWithFallback().
~FMaterialRenderProxy()
virtual FMaterialRenderProxy::~FMaterialRenderProxy () virtual
Destructor.
Member Function Documentation
AddSpecularProfileRT()
void FMaterialRenderProxy::AddSpecularProfileRT (const USpecularProfile * Ptr) inline
Definition at line 226 of file MaterialRenderProxy.h.
References SpecularProfilesRT.
AddSubsurfaceProfileRT()
void FMaterialRenderProxy::AddSubsurfaceProfileRT (const USubsurfaceProfile * Ptr) inline
Definition at line 221 of file MaterialRenderProxy.h.
References SubsurfaceProfilesRT.
AllocateVTStack()
IAllocatedVirtualTexture * FMaterialRenderProxy::AllocateVTStack (FRHICommandListBase & RHICmdList, const FMaterialRenderContext & Context, const FUniformExpressionSet & UniformExpressionSet, const FMaterialVirtualTextureStack & VTStack) const private
CacheUniformExpressions()
void FMaterialRenderProxy::CacheUniformExpressions (FRHICommandListBase & RHICmdList, bool bRecreateUniformBuffer)
Caches uniform expressions for efficient runtime evaluation.
CacheUniformExpressions_GameThread()
void FMaterialRenderProxy::CacheUniformExpressions_GameThread (bool bRecreateUniformBuffer)
Enqueues a rendering command to cache uniform expressions for efficient runtime evaluation.
bRecreateUniformBuffer - whether to recreate the material uniform buffer. This is required if the FMaterial is being recompiled (the uniform buffer layout will change). This should only be done if the calling code is using FMaterialUpdateContext to recreate the rendering state of primitives using this material, since cached mesh commands also cache uniform buffer pointers.
CancelCacheUniformExpressions()
void FMaterialRenderProxy::CancelCacheUniformExpressions ()
Cancels an in-flight cache operation.
EvaluateUniformExpressions()
void FMaterialRenderProxy::EvaluateUniformExpressions (FRHICommandListBase & RHICmdList, FUniformExpressionCache & OutUniformExpressionCache, const FMaterialRenderContext & Context, FUniformExpressionCacheAsyncUpdater * Updater = nullptr) const
Evaluates uniform expressions and stores them in OutUniformExpressionCache.
Parameters
OutUniformExpressionCache - The uniform expression cache to build.
MaterialRenderContext - The context for which to cache expressions.
FinishCacheUniformExpressions()
virtual void FMaterialRenderProxy::FinishCacheUniformExpressions () const inline private virtual
Definition at line 251 of file MaterialRenderProxy.h.
GetBlendableLocation()
virtual EBlendableLocation FMaterialRenderProxy::GetBlendableLocation (const FMaterial * Base) const virtual
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetBlendablePriority()
virtual int32 FMaterialRenderProxy::GetBlendablePriority (const FMaterial * Base) const virtual
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetExpressionCacheSerialNumber()
int32 FMaterialRenderProxy::GetExpressionCacheSerialNumber () const inline
Definition at line 242 of file MaterialRenderProxy.h.
References UniformExpressionCacheSerialNumber.
GetFallback()
virtual const FMaterialRenderProxy * FMaterialRenderProxy::GetFallback (ERHIFeatureLevel::Type InFeatureLevel) const pure virtual
Implemented in FColoredMaterialRenderProxy, FLandscapeDebugMaterialRenderProxy, FLandscapeLayerUsageRenderProxy, FLandscapeMaskMaterialRenderProxy, FLandscapeSelectMaterialRenderProxy, and FOverrideSelectionColorMaterialRenderProxy.
References FMaterialRenderProxy().
GetIncompleteMaterialWithFallback()
const FMaterial & FMaterialRenderProxy::GetIncompleteMaterialWithFallback (ERHIFeatureLevel::Type InFeatureLevel) const
Finds the FMaterial to use for rendering this FMaterialRenderProxy.
Will fall back to a default material if needed due to a content error, or async compilation. Will always return a valid FMaterial, but unlike GetMaterialWithFallback, FMaterial's shader map may be incomplete
GetMaterialInterface()
virtual UMaterialInterface * FMaterialRenderProxy::GetMaterialInterface () const inline virtual
Definition at line 162 of file MaterialRenderProxy.h.
GetMaterialName()
const FString & FMaterialRenderProxy::GetMaterialName () const inline
Definition at line 244 of file MaterialRenderProxy.h.
References MaterialName.
Referenced by FLandscapeDebugMaterialRenderProxy::FLandscapeDebugMaterialRenderProxy(), FLandscapeLayerUsageRenderProxy::FLandscapeLayerUsageRenderProxy(), FLandscapeMaskMaterialRenderProxy::FLandscapeMaskMaterialRenderProxy(), and FLandscapeSelectMaterialRenderProxy::FLandscapeSelectMaterialRenderProxy().
GetMaterialNoFallback()
virtual const FMaterial * FMaterialRenderProxy::GetMaterialNoFallback (ERHIFeatureLevel::Type InFeatureLevel) const pure virtual
Returns the FMaterial, without using a fallback if the FMaterial doesn't have a valid shader map.
Can return NULL.
Implemented in FColoredMaterialRenderProxy, FLandscapeDebugMaterialRenderProxy, FLandscapeLayerUsageRenderProxy, FLandscapeMaskMaterialRenderProxy, FLandscapeSelectMaterialRenderProxy, and FOverrideSelectionColorMaterialRenderProxy.
GetMaterialRenderProxyMap()
const TSet< FMaterialRenderProxy * > & FMaterialRenderProxy::GetMaterialRenderProxyMap () inline static
Definition at line 203 of file MaterialRenderProxy.h.
References check, and MaterialRenderProxyMap.
GetMaterialRenderProxyMapLock()
FCriticalSection & FMaterialRenderProxy::GetMaterialRenderProxyMapLock () inline static
Definition at line 209 of file MaterialRenderProxy.h.
References MaterialRenderProxyMapLock.
GetMaterialWithFallback()
const FMaterial & FMaterialRenderProxy::GetMaterialWithFallback (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy *& OutFallbackMaterialRenderProxy) const
Finds the FMaterial to use for rendering this FMaterialRenderProxy.
Will fall back to a default material if needed due to a content error, or async compilation. The returned FMaterial is guaranteed to have a complete shader map, so all relevant shaders should be available OutFallbackMaterialRenderProxy - The proxy that corresponds to the returned FMaterial, should be used for further rendering. May be a fallback material, or 'this' if no fallback was needed
References FMaterialRenderProxy().
GetNeuralProfileRT()
const UNeuralProfile * FMaterialRenderProxy::GetNeuralProfileRT () const inline
Definition at line 235 of file MaterialRenderProxy.h.
References NeuralProfileRT.
GetParameterValue()
virtual bool FMaterialRenderProxy::GetParameterValue (EMaterialParameterType Type, const FHashedMaterialParameterInfo & ParameterInfo, FMaterialParameterValue & OutValue, const FMaterialRenderContext & Context) const pure virtual
Implemented in FColoredMaterialRenderProxy, FColoredTexturedMaterialRenderProxy, FLandscapeDebugMaterialRenderProxy, FLandscapeLayerUsageRenderProxy, FLandscapeMaskMaterialRenderProxy, FLandscapeSelectMaterialRenderProxy, FLightingDensityMaterialRenderProxy, and FOverrideSelectionColorMaterialRenderProxy.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetPreallocatedVTStack()
IAllocatedVirtualTexture * FMaterialRenderProxy::GetPreallocatedVTStack (const FMaterialRenderContext & Context, const FUniformExpressionSet & UniformExpressionSet, const FMaterialVirtualTextureStack & VTStack) const private
GetScalarValue()
bool FMaterialRenderProxy::GetScalarValue (const FHashedMaterialParameterInfo & ParameterInfo, float * OutValue, const FMaterialRenderContext & Context) const
GetSpecularProfileOverrideRT()
const USpecularProfile * FMaterialRenderProxy::GetSpecularProfileOverrideRT () const inline
Definition at line 231 of file MaterialRenderProxy.h.
References SpecularProfileOverrideRT.
GetSpecularProfileRT()
const USpecularProfile * FMaterialRenderProxy::GetSpecularProfileRT (uint32 Index) const inline
Definition at line 227 of file MaterialRenderProxy.h.
References check, and SpecularProfilesRT.
GetSubsurfaceProfileRT() [1/2]
const USubsurfaceProfile * FMaterialRenderProxy::GetSubsurfaceProfileRT () const inline
Definition at line 218 of file MaterialRenderProxy.h.
References SubsurfaceProfileRT.
GetSubsurfaceProfileRT() [2/2]
const USubsurfaceProfile * FMaterialRenderProxy::GetSubsurfaceProfileRT (uint32 Index) const inline
Definition at line 222 of file MaterialRenderProxy.h.
References check, and SubsurfaceProfilesRT.
GetTextureCollectionValue()
bool FMaterialRenderProxy::GetTextureCollectionValue (const FHashedMaterialParameterInfo & ParameterInfo, const UTextureCollection ** OutValue, const FMaterialRenderContext & Context) const
GetTextureValue() [1/3]
bool FMaterialRenderProxy::GetTextureValue (const FHashedMaterialParameterInfo & ParameterInfo, const URuntimeVirtualTexture ** OutValue, const FMaterialRenderContext & Context) const
GetTextureValue() [2/3]
bool FMaterialRenderProxy::GetTextureValue (const FHashedMaterialParameterInfo & ParameterInfo, const USparseVolumeTexture ** OutValue, const FMaterialRenderContext & Context) const
GetTextureValue() [3/3]
bool FMaterialRenderProxy::GetTextureValue (const FHashedMaterialParameterInfo & ParameterInfo, const UTexture ** OutValue, const FMaterialRenderContext & Context) const
GetUserSceneTextureOutput()
FName FMaterialRenderProxy::GetUserSceneTextureOutput (const FMaterial * Base) const
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetUserSceneTextureOverride()
virtual bool FMaterialRenderProxy::GetUserSceneTextureOverride (FName & InOutValue) const inline virtual
Definition at line 171 of file MaterialRenderProxy.h.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetVectorValue()
bool FMaterialRenderProxy::GetVectorValue (const FHashedMaterialParameterInfo & ParameterInfo, FLinearColor * OutValue, const FMaterialRenderContext & Context) const
HasDeferredUniformExpressionCacheRequests()
bool FMaterialRenderProxy::HasDeferredUniformExpressionCacheRequests () static
InitRHI()
virtual void FMaterialRenderProxy::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InvalidateUniformExpressionCache()
void FMaterialRenderProxy::InvalidateUniformExpressionCache (bool bRecreateUniformBuffer)
Invalidates the uniform expression cache.
IsDeleted()
bool FMaterialRenderProxy::IsDeleted () const inline
Definition at line 177 of file MaterialRenderProxy.h.
References DeletedFlag.
IsMarkedForGarbageCollection()
bool FMaterialRenderProxy::IsMarkedForGarbageCollection () const inline
Definition at line 187 of file MaterialRenderProxy.h.
References MarkedForGarbageCollection.
MarkForGarbageCollection()
void FMaterialRenderProxy::MarkForGarbageCollection () inline
Definition at line 182 of file MaterialRenderProxy.h.
References MarkedForGarbageCollection.
MarkTransient()
void FMaterialRenderProxy::MarkTransient () inline
Definition at line 192 of file MaterialRenderProxy.h.
References bMarkedTransient.
NumSpecularProfileRT()
const uint32 FMaterialRenderProxy::NumSpecularProfileRT () const inline
Definition at line 228 of file MaterialRenderProxy.h.
References SpecularProfilesRT.
NumSubsurfaceProfileRT()
const uint32 FMaterialRenderProxy::NumSubsurfaceProfileRT () const inline
Definition at line 223 of file MaterialRenderProxy.h.
References SubsurfaceProfilesRT.
ReleaseResource()
virtual void FMaterialRenderProxy::ReleaseResource () override virtual
Prepares the resource for deletion.
This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHI()
virtual void FMaterialRenderProxy::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
SetNeuralProfileRT()
void FMaterialRenderProxy::SetNeuralProfileRT (const UNeuralProfile * Ptr) inline
Definition at line 234 of file MaterialRenderProxy.h.
References NeuralProfileRT.
SetSpecularProfileOverrideRT()
void FMaterialRenderProxy::SetSpecularProfileOverrideRT (const USpecularProfile * Ptr) inline
Definition at line 230 of file MaterialRenderProxy.h.
References SpecularProfileOverrideRT.
SetSubsurfaceProfileRT()
void FMaterialRenderProxy::SetSubsurfaceProfileRT (const USubsurfaceProfile * Ptr) inline
Definition at line 217 of file MaterialRenderProxy.h.
References SubsurfaceProfileRT.
StartCacheUniformExpressions()
virtual void FMaterialRenderProxy::StartCacheUniformExpressions () const inline private virtual
Definition at line 250 of file MaterialRenderProxy.h.
UpdateDeferredCachedUniformExpressions() [1/2]
void FMaterialRenderProxy::UpdateDeferredCachedUniformExpressions () static
UpdateDeferredCachedUniformExpressions() [2/2]
void FMaterialRenderProxy::UpdateDeferredCachedUniformExpressions (FRHICommandListBase & RHICmdList, UE::Tasks::FTask * TaskIfAsync = nullptr) static
UpdateUniformExpressionCacheIfNeeded() [1/2]
void FMaterialRenderProxy::UpdateUniformExpressionCacheIfNeeded (ERHIFeatureLevel::Type InFeatureLevel) const
UpdateUniformExpressionCacheIfNeeded() [2/2]
const FMaterial * FMaterialRenderProxy::UpdateUniformExpressionCacheIfNeeded (FRHICommandListBase & RHICmdList, ERHIFeatureLevel::Type InFeatureLevel) const
Field Documentation
bHasVirtualTextureCallbacks
uint8 FMaterialRenderProxy::bHasVirtualTextureCallbacks mutable private
If any VT producer destroyed callbacks have been registered.
Definition at line 271 of file MaterialRenderProxy.h.
bMarkedTransient
uint8 FMaterialRenderProxy::bMarkedTransient private
Set true if this is a transient, one frame object.
Definition at line 269 of file MaterialRenderProxy.h.
Referenced by MarkTransient().
DeferredUniformExpressionCacheRequests
TSet<FMaterialRenderProxy*> FMaterialRenderProxy::DeferredUniformExpressionCacheRequests static private
Definition at line 289 of file MaterialRenderProxy.h.
DeferredUniformExpressionCacheRequestsMutex
UE::FMutex FMaterialRenderProxy::DeferredUniformExpressionCacheRequestsMutex static private
Definition at line 290 of file MaterialRenderProxy.h.
DeletedFlag
uint8 FMaterialRenderProxy::DeletedFlag mutable private
Definition at line 266 of file MaterialRenderProxy.h.
Referenced by IsDeleted().
ImmutableSamplerState
FImmutableSamplerState FMaterialRenderProxy::ImmutableSamplerState mutable
Cached external texture immutable samplers.
Definition at line 104 of file MaterialRenderProxy.h.
MarkedForGarbageCollection
uint8 FMaterialRenderProxy::MarkedForGarbageCollection mutable private
For tracking down a bug accessing a deleted proxy.
Definition at line 265 of file MaterialRenderProxy.h.
Referenced by IsMarkedForGarbageCollection(), and MarkForGarbageCollection().
MaterialName
FString FMaterialRenderProxy::MaterialName private
Definition at line 259 of file MaterialRenderProxy.h.
Referenced by GetMaterialName().
MaterialRenderProxyMap
TSet<FMaterialRenderProxy*> FMaterialRenderProxy::MaterialRenderProxyMap static private
Tracks all material render proxies in all scenes.
This is used to propagate new shader maps to materials being used for rendering.
Definition at line 281 of file MaterialRenderProxy.h.
Referenced by GetMaterialRenderProxyMap().
MaterialRenderProxyMapLock
FCriticalSection FMaterialRenderProxy::MaterialRenderProxyMapLock static private
Lock that guards the access to the render proxy map.
Definition at line 286 of file MaterialRenderProxy.h.
Referenced by GetMaterialRenderProxyMapLock().
Mutex
UE::FMutex FMaterialRenderProxy::Mutex mutable private
Mutex for locking uniform expression invalidation / evaluation for this material.
Definition at line 274 of file MaterialRenderProxy.h.
NeuralProfileRT
const UNeuralProfile* FMaterialRenderProxy::NeuralProfileRT private
Definition at line 258 of file MaterialRenderProxy.h.
Referenced by GetNeuralProfileRT(), and SetNeuralProfileRT().
ReleaseResourceFlag
uint8 FMaterialRenderProxy::ReleaseResourceFlag mutable private
Definition at line 267 of file MaterialRenderProxy.h.
SpecularProfileOverrideRT
const USpecularProfile* FMaterialRenderProxy::SpecularProfileOverrideRT = nullptr private
Definition at line 257 of file MaterialRenderProxy.h.
Referenced by GetSpecularProfileOverrideRT(), and SetSpecularProfileOverrideRT().
SpecularProfilesRT
TArray<const USpecularProfile*> FMaterialRenderProxy::SpecularProfilesRT private
Definition at line 256 of file MaterialRenderProxy.h.
Referenced by AddSpecularProfileRT(), GetSpecularProfileRT(), and NumSpecularProfileRT().
SubsurfaceProfileRT
const USubsurfaceProfile* FMaterialRenderProxy::SubsurfaceProfileRT private
0 if not set, game thread pointer, do not dereference, only for comparison
Definition at line 254 of file MaterialRenderProxy.h.
Referenced by GetSubsurfaceProfileRT(), and SetSubsurfaceProfileRT().
SubsurfaceProfilesRT
TArray<const USubsurfaceProfile*> FMaterialRenderProxy::SubsurfaceProfilesRT private
Definition at line 255 of file MaterialRenderProxy.h.
Referenced by AddSubsurfaceProfileRT(), GetSubsurfaceProfileRT(), and NumSubsurfaceProfileRT().
UniformExpressionCache
FUniformExpressionCacheContainer FMaterialRenderProxy::UniformExpressionCache mutable
Cached uniform expressions.
Definition at line 101 of file MaterialRenderProxy.h.
UniformExpressionCacheSerialNumber
int32 FMaterialRenderProxy::UniformExpressionCacheSerialNumber = 0 mutable private
Incremented each time UniformExpressionCache is modified.
Definition at line 262 of file MaterialRenderProxy.h.
Referenced by GetExpressionCacheSerialNumber().
The documentation for this class was generated from the following file:
MaterialRenderProxy.h