Unreal Engine 5.6 C++ API: FTextLocalizationManager Class Reference
FTextLocalizationManager Class Reference
Singleton class that manages display strings for FText.
#include "TextLocalizationManager.h"
Data Structures
struct FDisplayStringEntry
Data struct for tracking a display string.
struct FDisplayStringsByLocalizationTargetId
struct FDisplayStringsForLocalizationTarget
struct FUpdateLiveTableOptions
Public Member Functions
~FTextLocalizationManager ()
void CompactDataStructures ()
void ConfigureGameLocalizationPreviewLanguage (const FString &CultureName)
Configure the "preview language" setting used for the game localization preview.
DECLARE_EVENT (FTextLocalizationManager, FTextRevisionChangedEvent) FTextRevisionChangedEvent OnTextRevisionChangedEvent
Event type for immediately reacting to changes in display strings for text.
void DisableGameLocalizationPreview ()
Disable the game localization preview.
void DumpMemoryInfo () const
void EnableGameLocalizationPreview ()
Enable the game localization preview using the current "preview language" setting, or the native culture if no "preview language" is set.
void EnableGameLocalizationPreview (const FString &CultureName)
Enable the game localization preview using the given language, or the native language if the culture name is empty.
FTextConstDisplayStringPtr FindDisplayString (const FTextKey &Namespace, const FTextKey &Key, const FString *const SourceStringPtr=nullptr) const
Finds and returns the display string with the given namespace and key, if it exists.
FString GetConfiguredGameLocalizationPreviewLanguage () const
Get the configured "preview language" setting used for the game localization preview (if any).
FTextConstDisplayStringPtr GetDisplayString (const FTextKey &Namespace, const FTextKey &Key, const FString *const SourceStringPtr) const
Get the current display string for the given namespace and key, if any.
int32 GetLocalizationTargetPathId (FStringView InLocalizationTargetPath)
Given a localization target path, get the ID associated with it.
TArray< FString > GetLocalizedCultureNames (const ELocalizationLoadFlags InLoadFlags) const
Get a list of culture names that we have localized resource data for (ELocalizationLoadFlags controls which resources should be checked).
uint16 GetLocalRevisionForTextId (const FTextId &InTextId) const
Attempts to find a local revision history for the given text ID.
FString GetNativeCultureName (const ELocalizedTextSourceCategory InCategory) const
Given a localization category, get the native culture for the category (if known).
FString GetRequestedLanguageName () const
Get the language that will be requested during localization initialization, based on the hierarchy of: command line -> configs -> OS default.
FString GetRequestedLocaleName () const
Get the locale that will be requested during localization initialization, based on the hierarchy of: command line -> configs -> OS default.
uint16 GetTextRevision () const
Returns the current text revision number.
void GetTextRevisions (const FTextId &InTextId, uint16 &OutGlobalTextRevision, uint16 &OutLocalTextRevision) const
Get both the global and local revision for the given text ID.
void HandleLocalizationTargetsMounted (TArrayView< const FString > LocalizationTargetPaths, TUniqueFunction< void()> &&Notification=nullptr)
Called when paths containing additional localization target data (LocRes) are mounted, to allow the display strings to dynamically update without waiting for a refresh.
void HandleLocalizationTargetsUnmounted (TArrayView< const FString > LocalizationTargetPaths, TUniqueFunction< void()> &&Notification=nullptr)
Called when paths containing additional localization target data (LocRes) are unmounted, to allow the display strings to be unloaded.
bool IsGameLocalizationPreviewEnabled () const
Is the game localization preview enabled for a non-native language?
bool IsLocalizationLocked () const
Is the localization of this game currently locked?
void NotifyWhenAsyncTasksCompleted (TUniqueFunction< void()> &&Notification)
Call the given function when any current async tasks have finished.
void PopAutoEnableGameLocalizationPreview ()
Notify that the game localization preview should no longer automatically enable itself under certain circumstances (such as changing the preview language via the UI) due to a state change (such as PIE ending).
void PushAutoEnableGameLocalizationPreview ()
Notify that the game localization preview should automatically enable itself under certain circumstances (such as changing the preview language via the UI) due to a state change (such as PIE starting).
void RefreshResources (TUniqueFunction< void()> &&Notification=nullptr)
Reloads resources for the current culture.
void RegisterPolyglotTextData (const FPolyglotTextData &InPolyglotTextData, const bool InAddDisplayString=true)
Register a polyglot text data with the text localization manager.
void RegisterPolyglotTextData (TArrayView< const FPolyglotTextData > InPolyglotTextDataArray, const bool InAddDisplayStrings=true)
void RegisterTextSource (const TSharedRef< ILocalizedTextSource > &InLocalizedTextSource, const bool InRefreshResources=true)
Register a localized text source with the text localization manager.
bool ShouldForceLoadGameLocalization () const
True if we should force load game localization data.
bool ShouldGameLocalizationPreviewAutoEnable () const
Should the game localization preview automatically enable itself under certain circumstances?
UE_NONCOPYABLE (FTextLocalizationManager)
void UpdateFromLocalizationResource (const FString &LocalizationResourceFilePath)
Updates display string entries and adds new display string entries based on localizations found in a specified localization resource.
void UpdateFromLocalizationResource (const FTextLocalizationResource &TextLocalizationResource)
void WaitForAsyncTasks ()
Wait for any current async tasks to finish.
Static Public Member Functions
static FTextLocalizationManager & Get ()
Singleton accessor.
static bool IsDisplayStringSupportEnabled ()
static void TearDown ()
Private Types
typedef TMap< FTextId, FDisplayStringEntry > FDisplayStringLookupTable
Manages the currently loaded or registered text localizations.
Private Member Functions
FTextLocalizationManager ()
void DirtyLocalRevisionForTextId (const FTextId &InTextId)
Dirties the local revision counter for the given text ID by incrementing it (or adding it)
void DirtyTextRevision ()
Dirties the text revision counter by incrementing it, causing a revision mismatch for any information cached before this happens.
FTextConstDisplayStringPtr FindDisplayString_Internal (const FTextId &TextId, const FString &SourceString) const
Internal version of FindDisplayString, shared between FindDisplayString and GetDisplayString.
bool IsInitialized () const
void LoadChunkedLocalizationResources_Async (const int32 ChunkId, const FString &PakFilename)
void LoadChunkedLocalizationResources_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, const int32 ChunkId, const FString &PakFilename)
Loads the chunked localization resource data for the specified chunk.
void LoadLocalizationResourcesForCulture_Async (const FString &CultureName, const ELocalizationLoadFlags LocLoadFlags, TUniqueFunction< void()> &&Notification)
void LoadLocalizationResourcesForCulture_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, const FString &CultureName, const ELocalizationLoadFlags LocLoadFlags)
Loads localization resources for the specified culture, optionally loading localization resources that are editor-specific or game-specific.
void LoadLocalizationResourcesForPrioritizedCultures_Async (TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags)
void LoadLocalizationResourcesForPrioritizedCultures_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags)
Loads localization resources for the specified prioritized cultures, optionally loading localization resources that are editor-specific or game-specific.
void LoadLocalizationTargetsForPrioritizedCultures_Async (TArrayView< const FString > LocalizationTargetPaths, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags, TUniqueFunction< void()> &&Notification)
void LoadLocalizationTargetsForPrioritizedCultures_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, TArrayView< const FString > LocalizationTargetPaths, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags)
Loads the specified localization targets for the specified prioritized cultures, optionally loading localization resources that are editor-specific or game-specific.
void OnCultureChanged ()
Callback for changes in culture.
void OnPakFileMounted (const IPakFile &PakFile)
Callback for when a PAK file is loaded.
void QueueAsyncTask (TUniqueFunction< void()> &&Task)
Queue the given task to run async (where possible), chained to any existing AsyncLocalizationTask.
void UpdateLiveTable (FTextLocalizationResource &&TextLocalizationResource, const FUpdateLiveTableOptions &UpdateOptions=FUpdateLiveTableOptions())
Updates display string entries and adds new display string entries.
Private Attributes
FGraphEventRef AsyncLocalizationTask
The latest async localization task (if any).
bool bIsGameLocalizationPreviewEnabled
bool bIsLocalizationLocked
FDisplayStringLookupTable DisplayStringLookupTable
FDisplayStringsByLocalizationTargetId DisplayStringsByLocalizationTargetId
FRWLock DisplayStringTableRW
uint8 GameLocalizationPreviewAutoEnableCount
std::atomic< ETextLocalizationManagerInitializedFlags > InitializedFlags { ETextLocalizationManagerInitializedFlags::None }
TArray< TSharedPtr< ILocalizedTextSource > > LocalizedTextSources
Array of registered localized text sources, sorted by priority (.
TMap< FTextId, uint16 > LocalTextRevisions
TSharedPtr< class FLocalizationResourceTextSource > LocResTextSource
The LocRes text source (this is also added to LocalizedTextSources, but we keep a pointer to it directly so we can patch in chunked LocRes data at runtime)
TSharedPtr< class FPolyglotTextSource > PolyglotTextSource
The polyglot text source (this is also added to LocalizedTextSources, but we keep a pointer to it directly so we can add new polyglot data to it at runtime)
uint16 TextRevisionCounter
FRWLock TextRevisionRW
Friends
void BeginInitTextLocalization ()
void BeginPreInitTextLocalization ()
class FLazySingleton
void InitEngineTextLocalization ()
void InitGameTextLocalization ()
Detailed Description
Singleton class that manages display strings for FText.
Definition at line 41 of file TextLocalizationManager.h.
Member Typedef Documentation
FDisplayStringLookupTable
typedef TMap<FTextId, FDisplayStringEntry> FTextLocalizationManager::FDisplayStringLookupTable private
Manages the currently loaded or registered text localizations.
Definition at line 72 of file TextLocalizationManager.h.
Constructor & Destructor Documentation
FTextLocalizationManager()
FTextLocalizationManager::FTextLocalizationManager () private
Referenced by DECLARE_EVENT(), Get(), and UE_NONCOPYABLE().
~FTextLocalizationManager()
FTextLocalizationManager::~FTextLocalizationManager ()
Member Function Documentation
CompactDataStructures()
void FTextLocalizationManager::CompactDataStructures ()
References Key.
ConfigureGameLocalizationPreviewLanguage()
void FTextLocalizationManager::ConfigureGameLocalizationPreviewLanguage (const FString & CultureName)
Configure the "preview language" setting used for the game localization preview.
DECLARE_EVENT()
FTextLocalizationManager::DECLARE_EVENT (FTextLocalizationManager , FTextRevisionChangedEvent)
Event type for immediately reacting to changes in display strings for text.
References FTextLocalizationManager().
DirtyLocalRevisionForTextId()
void FTextLocalizationManager::DirtyLocalRevisionForTextId (const FTextId & InTextId) private
Dirties the local revision counter for the given text ID by incrementing it (or adding it)
DirtyTextRevision()
void FTextLocalizationManager::DirtyTextRevision () private
Dirties the text revision counter by incrementing it, causing a revision mismatch for any information cached before this happens.
DisableGameLocalizationPreview()
void FTextLocalizationManager::DisableGameLocalizationPreview ()
Disable the game localization preview.
Note
This is the same as calling EnableGameLocalizationPreview with the native game language (or an empty string).
DumpMemoryInfo()
void FTextLocalizationManager::DumpMemoryInfo () const
EnableGameLocalizationPreview() [1/2]
void FTextLocalizationManager::EnableGameLocalizationPreview ()
Enable the game localization preview using the current "preview language" setting, or the native culture if no "preview language" is set.
Note
This is the same as calling EnableGameLocalizationPreview with the current "preview language" setting.
EnableGameLocalizationPreview() [2/2]
void FTextLocalizationManager::EnableGameLocalizationPreview (const FString & CultureName)
Enable the game localization preview using the given language, or the native language if the culture name is empty.
Note
This will also lockdown localization editing if the given language is a non-native game language (to avoid accidentally baking out translations as source data in assets).
FindDisplayString()
FTextConstDisplayStringPtr FTextLocalizationManager::FindDisplayString (const FTextKey & Namespace, const FTextKey & Key, const FString *const SourceStringPtr = nullptr) const
Finds and returns the display string with the given namespace and key, if it exists.
Note
If a non-null and non-empty source string is specified and the found localized display string was not localized from that source string, null will be returned.
References Key.
FindDisplayString_Internal()
FTextConstDisplayStringPtr FTextLocalizationManager::FindDisplayString_Internal (const FTextId & TextId, const FString & SourceString) const private
Internal version of FindDisplayString, shared between FindDisplayString and GetDisplayString.
Get()
FTextLocalizationManager & FTextLocalizationManager::Get () static
Singleton accessor.
References FTextLocalizationManager().
GetConfiguredGameLocalizationPreviewLanguage()
FString FTextLocalizationManager::GetConfiguredGameLocalizationPreviewLanguage () const
Get the configured "preview language" setting used for the game localization preview (if any).
GetDisplayString()
FTextConstDisplayStringPtr FTextLocalizationManager::GetDisplayString (const FTextKey & Namespace, const FTextKey & Key, const FString *const SourceStringPtr) const
Get the current display string for the given namespace and key, if any.
Note
If a non-null and non-empty source string is specified and the found localized display string was not localized from that source string, it will be considered unlocalized.
Unlike FindDisplayString:
This function may adjust the given text ID (eg, when USE_STABLE_LOCALIZATION_KEYS is enabled).
This function may return a value for unlocalized strings (eg, when using -LEETifyUnlocalized).
References Key.
GetLocalizationTargetPathId()
int32 FTextLocalizationManager::GetLocalizationTargetPathId (FStringView InLocalizationTargetPath)
Given a localization target path, get the ID associated with it.
Note
This ID is unstable and should only be used for quick in-process comparison.
GetLocalizedCultureNames()
TArray< FString > FTextLocalizationManager::GetLocalizedCultureNames (const ELocalizationLoadFlags InLoadFlags) const
Get a list of culture names that we have localized resource data for (ELocalizationLoadFlags controls which resources should be checked).
GetLocalRevisionForTextId()
uint16 FTextLocalizationManager::GetLocalRevisionForTextId (const FTextId & InTextId) const
Attempts to find a local revision history for the given text ID.
This will only be set if the display string has been changed since the localization manager version has been changed (eg, if it has been edited while keeping the same key).
Returns
The local revision, or 0 if there have been no changes since a global history change.
GetNativeCultureName()
FString FTextLocalizationManager::GetNativeCultureName (const ELocalizedTextSourceCategory InCategory) const
Given a localization category, get the native culture for the category (if known).
Returns
The native culture for the given localization category, or an empty string if the native culture is unknown.
GetRequestedLanguageName()
FString FTextLocalizationManager::GetRequestedLanguageName () const
Get the language that will be requested during localization initialization, based on the hierarchy of: command line -> configs -> OS default.
GetRequestedLocaleName()
FString FTextLocalizationManager::GetRequestedLocaleName () const
Get the locale that will be requested during localization initialization, based on the hierarchy of: command line -> configs -> OS default.
GetTextRevision()
uint16 FTextLocalizationManager::GetTextRevision () const
Returns the current text revision number.
This value can be cached when caching information from the text localization manager. If the revision does not match, cached information may be invalid and should be recached.
GetTextRevisions()
void FTextLocalizationManager::GetTextRevisions (const FTextId & InTextId, uint16 & OutGlobalTextRevision, uint16 & OutLocalTextRevision) const
Get both the global and local revision for the given text ID.
See also
GetTextRevision and GetLocalRevisionForTextId.
HandleLocalizationTargetsMounted()
void FTextLocalizationManager::HandleLocalizationTargetsMounted (TArrayView< const FString > LocalizationTargetPaths, TUniqueFunction< void()> && Notification = nullptr)
Called when paths containing additional localization target data (LocRes) are mounted, to allow the display strings to dynamically update without waiting for a refresh.
Note
The loading is async, see WaitForAsyncTasks/NotifyWhenAsyncTasksCompleted, or pass the optional notification callback.
See also
FCoreDelegates::GatherAdditionalLocResPathsCallback.
References Notification.
HandleLocalizationTargetsUnmounted()
void FTextLocalizationManager::HandleLocalizationTargetsUnmounted (TArrayView< const FString > LocalizationTargetPaths, TUniqueFunction< void()> && Notification = nullptr)
Called when paths containing additional localization target data (LocRes) are unmounted, to allow the display strings to be unloaded.
Note
The unloading is async, see WaitForAsyncTasks/NotifyWhenAsyncTasksCompleted, or pass the optional notification callback.
See also
FCoreDelegates::GatherAdditionalLocResPathsCallback.
References Notification.
IsDisplayStringSupportEnabled()
bool FTextLocalizationManager::IsDisplayStringSupportEnabled () static
IsGameLocalizationPreviewEnabled()
bool FTextLocalizationManager::IsGameLocalizationPreviewEnabled () const
Is the game localization preview enabled for a non-native language?
IsInitialized()
bool FTextLocalizationManager::IsInitialized () const inline private
Definition at line 110 of file TextLocalizationManager.h.
References InitializedFlags, and None.
IsLocalizationLocked()
bool FTextLocalizationManager::IsLocalizationLocked () const
Is the localization of this game currently locked?
(ie, can it be edited in the UI?).
LoadChunkedLocalizationResources_Async()
void FTextLocalizationManager::LoadChunkedLocalizationResources_Async (const int32 ChunkId, const FString & PakFilename) private
LoadChunkedLocalizationResources_Sync()
void FTextLocalizationManager::LoadChunkedLocalizationResources_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, const int32 ChunkId, const FString & PakFilename) private
Loads the chunked localization resource data for the specified chunk.
LoadLocalizationResourcesForCulture_Async()
void FTextLocalizationManager::LoadLocalizationResourcesForCulture_Async (const FString & CultureName, const ELocalizationLoadFlags LocLoadFlags, TUniqueFunction< void()> && Notification) private
References Notification.
LoadLocalizationResourcesForCulture_Sync()
void FTextLocalizationManager::LoadLocalizationResourcesForCulture_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, const FString & CultureName, const ELocalizationLoadFlags LocLoadFlags) private
Loads localization resources for the specified culture, optionally loading localization resources that are editor-specific or game-specific.
LoadLocalizationResourcesForPrioritizedCultures_Async()
void FTextLocalizationManager::LoadLocalizationResourcesForPrioritizedCultures_Async (TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags) private
LoadLocalizationResourcesForPrioritizedCultures_Sync()
void FTextLocalizationManager::LoadLocalizationResourcesForPrioritizedCultures_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags) private
Loads localization resources for the specified prioritized cultures, optionally loading localization resources that are editor-specific or game-specific.
LoadLocalizationTargetsForPrioritizedCultures_Async()
void FTextLocalizationManager::LoadLocalizationTargetsForPrioritizedCultures_Async (TArrayView< const FString > LocalizationTargetPaths, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags, TUniqueFunction< void()> && Notification) private
References Notification.
LoadLocalizationTargetsForPrioritizedCultures_Sync()
void FTextLocalizationManager::LoadLocalizationTargetsForPrioritizedCultures_Sync (TArrayView< const TSharedPtr< ILocalizedTextSource > > AvailableTextSources, TArrayView< const FString > LocalizationTargetPaths, TArrayView< const FString > PrioritizedCultureNames, const ELocalizationLoadFlags LocLoadFlags) private
Loads the specified localization targets for the specified prioritized cultures, optionally loading localization resources that are editor-specific or game-specific.
NotifyWhenAsyncTasksCompleted()
void FTextLocalizationManager::NotifyWhenAsyncTasksCompleted (TUniqueFunction< void()> && Notification)
Call the given function when any current async tasks have finished.
Note
The notification may be called from any thread, to avoid blocking other async tasks in the queue while waiting for a given thread to be available.
See also
WaitForAsyncTasks for a blocking version.
References Notification.
OnCultureChanged()
void FTextLocalizationManager::OnCultureChanged () private
Callback for changes in culture.
Async loads the new culture's localization resources.
OnPakFileMounted()
void FTextLocalizationManager::OnPakFileMounted (const IPakFile & PakFile) private
Callback for when a PAK file is loaded.
Async loads any chunk specific localization resources.
PopAutoEnableGameLocalizationPreview()
void FTextLocalizationManager::PopAutoEnableGameLocalizationPreview ()
Notify that the game localization preview should no longer automatically enable itself under certain circumstances (such as changing the preview language via the UI) due to a state change (such as PIE ending).
Note
This must be paired with a call to PushAutoEnableGameLocalizationPreview.
PushAutoEnableGameLocalizationPreview()
void FTextLocalizationManager::PushAutoEnableGameLocalizationPreview ()
Notify that the game localization preview should automatically enable itself under certain circumstances (such as changing the preview language via the UI) due to a state change (such as PIE starting).
Note
This must be paired with a call to PopAutoEnableGameLocalizationPreview.
QueueAsyncTask()
void FTextLocalizationManager::QueueAsyncTask (TUniqueFunction< void()> && Task) private
Queue the given task to run async (where possible), chained to any existing AsyncLocalizationTask.
RefreshResources()
void FTextLocalizationManager::RefreshResources (TUniqueFunction< void()> && Notification = nullptr)
Reloads resources for the current culture.
Note
The loading is async, see WaitForAsyncTasks/NotifyWhenAsyncTasksCompleted, or pass the optional notification callback.
References Notification.
RegisterPolyglotTextData() [1/2]
void FTextLocalizationManager::RegisterPolyglotTextData (const FPolyglotTextData & InPolyglotTextData, const bool InAddDisplayString = true)
Register a polyglot text data with the text localization manager.
RegisterPolyglotTextData() [2/2]
void FTextLocalizationManager::RegisterPolyglotTextData (TArrayView< const FPolyglotTextData > InPolyglotTextDataArray, const bool InAddDisplayStrings = true)
RegisterTextSource()
void FTextLocalizationManager::RegisterTextSource (const TSharedRef< ILocalizedTextSource > & InLocalizedTextSource, const bool InRefreshResources = true)
Register a localized text source with the text localization manager.
ShouldForceLoadGameLocalization()
bool FTextLocalizationManager::ShouldForceLoadGameLocalization () const
True if we should force load game localization data.
ShouldGameLocalizationPreviewAutoEnable()
bool FTextLocalizationManager::ShouldGameLocalizationPreviewAutoEnable () const
Should the game localization preview automatically enable itself under certain circumstances?
TearDown()
void FTextLocalizationManager::TearDown () static
UE_NONCOPYABLE()
FTextLocalizationManager::UE_NONCOPYABLE (FTextLocalizationManager)
References FTextLocalizationManager().
UpdateFromLocalizationResource() [1/2]
void FTextLocalizationManager::UpdateFromLocalizationResource (const FString & LocalizationResourceFilePath)
Updates display string entries and adds new display string entries based on localizations found in a specified localization resource.
UpdateFromLocalizationResource() [2/2]
void FTextLocalizationManager::UpdateFromLocalizationResource (const FTextLocalizationResource & TextLocalizationResource)
UpdateLiveTable()
void FTextLocalizationManager::UpdateLiveTable (FTextLocalizationResource && TextLocalizationResource, const FUpdateLiveTableOptions & UpdateOptions = FUpdateLiveTableOptions()) private
Updates display string entries and adds new display string entries.
WaitForAsyncTasks()
void FTextLocalizationManager::WaitForAsyncTasks ()
Wait for any current async tasks to finish.
See also
NotifyWhenAsyncTasksCompleted for an non-blocking version.
Async tasks will be started for anything that loads localization data (eg, initialization, language changes, requests to refresh the localization data, requests to load additional localization data for chunked targets, or requests to load additional localization data for explicitly loaded plugins).
While the engine automatically waits at certain points during initialization, you may find that you need to add your own waits if you cause additional localization data to load post-initialization (eg, because you're using chunked localization targets or are explicitly loading plugins). A good place to add a wait in that case might be at the end of your loading screen, before showing your main menu or game world.
Friends And Related Symbol Documentation
BeginInitTextLocalization
void BeginInitTextLocalization () friend
BeginPreInitTextLocalization
void BeginPreInitTextLocalization () friend
FLazySingleton
friend class FLazySingleton friend
Definition at line 130 of file TextLocalizationManager.h.
References FLazySingleton.
Referenced by FLazySingleton.
InitEngineTextLocalization
void InitEngineTextLocalization () friend
InitGameTextLocalization
void InitGameTextLocalization () friend
Field Documentation
AsyncLocalizationTask
FGraphEventRef FTextLocalizationManager::AsyncLocalizationTask private
The latest async localization task (if any).
Additional requests are chained to this so that they run in sequence
Definition at line 407 of file TextLocalizationManager.h.
bIsGameLocalizationPreviewEnabled
bool FTextLocalizationManager::bIsGameLocalizationPreviewEnabled private
Definition at line 125 of file TextLocalizationManager.h.
bIsLocalizationLocked
bool FTextLocalizationManager::bIsLocalizationLocked private
Definition at line 126 of file TextLocalizationManager.h.
DisplayStringLookupTable
FDisplayStringLookupTable FTextLocalizationManager::DisplayStringLookupTable private
Definition at line 116 of file TextLocalizationManager.h.
DisplayStringsByLocalizationTargetId
FDisplayStringsByLocalizationTargetId FTextLocalizationManager::DisplayStringsByLocalizationTargetId private
Definition at line 117 of file TextLocalizationManager.h.
DisplayStringTableRW
FRWLock FTextLocalizationManager::DisplayStringTableRW mutable private
Definition at line 115 of file TextLocalizationManager.h.
GameLocalizationPreviewAutoEnableCount
uint8 FTextLocalizationManager::GameLocalizationPreviewAutoEnableCount private
Definition at line 124 of file TextLocalizationManager.h.
InitializedFlags
std::atomic<ETextLocalizationManagerInitializedFlags> FTextLocalizationManager::InitializedFlags { ETextLocalizationManagerInitializedFlags::None } private
Definition at line 108 of file TextLocalizationManager.h.
Referenced by IsInitialized().
LocalizedTextSources
TArray<TSharedPtr<ILocalizedTextSource> > FTextLocalizationManager::LocalizedTextSources private
Array of registered localized text sources, sorted by priority (.
See also
RegisterTextSource)
Definition at line 398 of file TextLocalizationManager.h.
LocalTextRevisions
TMap<FTextId, uint16> FTextLocalizationManager::LocalTextRevisions private
Definition at line 120 of file TextLocalizationManager.h.
LocResTextSource
TSharedPtr<class FLocalizationResourceTextSource> FTextLocalizationManager::LocResTextSource private
The LocRes text source (this is also added to LocalizedTextSources, but we keep a pointer to it directly so we can patch in chunked LocRes data at runtime)
Definition at line 401 of file TextLocalizationManager.h.
PolyglotTextSource
TSharedPtr<class FPolyglotTextSource> FTextLocalizationManager::PolyglotTextSource private
The polyglot text source (this is also added to LocalizedTextSources, but we keep a pointer to it directly so we can add new polyglot data to it at runtime)
Definition at line 404 of file TextLocalizationManager.h.
TextRevisionCounter
uint16 FTextLocalizationManager::TextRevisionCounter private
Definition at line 121 of file TextLocalizationManager.h.
TextRevisionRW
FRWLock FTextLocalizationManager::TextRevisionRW mutable private
Definition at line 119 of file TextLocalizationManager.h.
The documentation for this class was generated from the following file:
TextLocalizationManager.h