Unreal Engine 5.6 C++ API: TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator Class Reference
TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator Class Reference
Iterates over values associated with a specified key in a const map.
#include "SortedMap.h"
Public Member Functions
FORCEINLINE TConstKeyIterator (const TSortedMap &InMap, KeyInitType InKey)
FORCEINLINE TConstKeyIterator & operator++ ()
Public Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
FORCEINLINE FSetElementId GetId () const
FORCEINLINE ItKeyType & Key () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE PairType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE PairType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ItValueType & Value () const
Private Types
using Super = TBaseIterator<true>
Additional Inherited Members
Public Types inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
typedef std::conditional_t< bConst, typename ElementArrayType::TConstIterator, typename ElementArrayType::TIterator > PairItType
Protected Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
FORCEINLINE TBaseIterator (const PairItType &InElementIt)
Protected Attributes inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
PairItType PairIt
Detailed Description
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate>
class TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator
Iterates over values associated with a specified key in a const map.
This will be at most one value because keys must be unique
Definition at line 808 of file SortedMap.h.
Member Typedef Documentation
Super
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> using TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::Super = TBaseIterator<true> private
Definition at line 810 of file SortedMap.h.
Constructor & Destructor Documentation
TConstKeyIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::TConstKeyIterator (const TSortedMap & InMap, KeyInitType InKey) inline nodiscard
Definition at line 813 of file SortedMap.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap, TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateConstIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindIndex(), FORCEINLINE, INDEX_NONE, TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >::PairIt, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Pairs.
Referenced by operator++().
Member Function Documentation
operator++()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TConstKeyIterator & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::operator++ () inline
Definition at line 828 of file SortedMap.h.
References TConstKeyIterator(), FORCEINLINE, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >::PairIt.
The documentation for this class was generated from the following file:
SortedMap.h