Unreal Engine 5.6 C++ API: UE::AnimNext::IGraphFactory Struct Reference
UE::AnimNext::IGraphFactory Struct Reference
IGraphFactory.
#include "IGraphFactory.h"
Public Member Functions
virtual ANIMNEXTANIMGRAPH_API void CreatePayloadForObject (FExecutionContext &Context, const TTraitBinding< IGraphFactory > &Binding, const UObject *InObject, FAnimNextDataInterfacePayload &InOutPayload) const
DECLARE_ANIM_TRAIT_INTERFACE (IGraphFactory) ANIMNEXTANIMGRAPH_API virtual const UAnimNextAnimationGraph *GetGraphFromObject(FExecutionContext &Context
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API const UAnimNextAnimationGraph * GetGraphFromObjectWithFallback (FExecutionContext &Context, const FTraitBinding &InBinding, const UObject *InObject, FAnimNextDataInterfacePayload &InOutPayload)
Data Fields
const TTraitBinding< IGraphFactory > & Binding
const TTraitBinding< IGraphFactory > const UObject FAnimNextDataInterfacePayload &InOutPayload const
const TTraitBinding< IGraphFactory > const UObject * InObject
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
IGraphFactory.
This interface translates an object and payload struct into a UAnimNextAnimationGraph and payload instance(s), ready for instantiation
Definition at line 22 of file IGraphFactory.h.
Member Function Documentation
CreatePayloadForObject()
virtual ANIMNEXTANIMGRAPH_API void UE::AnimNext::IGraphFactory::CreatePayloadForObject (FExecutionContext & Context, const TTraitBinding< IGraphFactory > & Binding, const UObject * InObject, FAnimNextDataInterfacePayload & InOutPayload) const virtual
References Binding, const, CreatePayloadForObject(), InObject, and UE_API.
Referenced by CreatePayloadForObject().
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::IGraphFactory::DECLARE_ANIM_TRAIT_INTERFACE (IGraphFactory) const &
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IGraphFactory::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IGraphFactory::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetGraphFromObjectWithFallback()
ANIMNEXTANIMGRAPH_API const UAnimNextAnimationGraph * UE::AnimNext::IGraphFactory::GetGraphFromObjectWithFallback (FExecutionContext & Context, const FTraitBinding & InBinding, const UObject * InObject, FAnimNextDataInterfacePayload & InOutPayload) static
References const, GetGraphFromObjectWithFallback(), InObject, and UE_API.
Referenced by GetGraphFromObjectWithFallback().
Field Documentation
Binding
const TTraitBinding<IGraphFactory>& UE::AnimNext::IGraphFactory::Binding
Definition at line 30 of file IGraphFactory.h.
Referenced by CreatePayloadForObject().
const
const TTraitBinding<IGraphFactory> const UObject FAnimNextDataInterfacePayload& InOutPayload UE::AnimNext::IGraphFactory::const
Definition at line 30 of file IGraphFactory.h.
Referenced by CreatePayloadForObject(), and GetGraphFromObjectWithFallback().
InObject
const TTraitBinding<IGraphFactory> const UObject* UE::AnimNext::IGraphFactory::InObject
Definition at line 30 of file IGraphFactory.h.
Referenced by CreatePayloadForObject(), and GetGraphFromObjectWithFallback().
The documentation for this struct was generated from the following file:
IGraphFactory.h