Unreal Engine 5.6 C++ API: FPhysScene_Chaos Class Reference
FPhysScene_Chaos Class Reference
Low level Chaos scene used when building custom simulations that don't exist in the main world physics scene.
#include "PhysScene_Chaos.h"
Data Structures
struct FDeferredKinematicUpdateInfo
Information about how to perform kinematic update before physics.
struct FUniqueContactPairKey
Public Types
using Super = FChaosScene
Public Member Functions
FPhysScene_Chaos (AActor *InSolverActor=nullptr)
virtual ~FPhysScene_Chaos ()
void AddAggregateToScene (const FPhysicsAggregateHandle &InAggregate)
void AddCustomPhysics_AssumesLocked (FBodyInstance *BodyInstance, FCalculateCustomPhysics &CalculateCustomPhysics)
void AddForce_AssumesLocked (FBodyInstance *BodyInstance, const FVector &Force, bool bAllowSubstepping, bool bAccelChange)
void AddForceAtPosition_AssumesLocked (FBodyInstance *BodyInstance, const FVector &Force, const FVector &Position, bool bAllowSubstepping, bool bIsLocalForce=false)
void AddObject (UPrimitiveComponent *Component, Chaos::FClusterUnionPhysicsProxy *InObject)
void AddObject (UPrimitiveComponent *Component, Chaos::FSingleParticlePhysicsProxy *InObject)
void AddObject (UPrimitiveComponent *Component, FGeometryCollectionPhysicsProxy *InObject)
void AddObject (UPrimitiveComponent *Component, FSkeletalMeshPhysicsProxy *InObject)
Called during creation of the physics state for gamethread objects to pass off an object to the physics thread.
void AddObject (UPrimitiveComponent *Component, FStaticMeshPhysicsProxy *InObject)
void AddPendingOnConstraintBreak (FConstraintInstance *ConstraintInstance, int32 SceneType)
void AddPendingSleepingEvent (FBodyInstance *BI, ESleepEvent SleepEventType, int32 SceneType)
void AddRadialForceToBody_AssumesLocked (FBodyInstance *BodyInstance, const FVector &Origin, const float Radius, const float Strength, const uint8 Falloff, bool bAccelChange, bool bAllowSubstepping)
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
void AddToComponentMaps (UPrimitiveComponent *Component, IPhysicsProxyBase *InObject)
void AddTorque_AssumesLocked (FBodyInstance *BodyInstance, const FVector &Torque, bool bAllowSubstepping, bool bAccelChange)
void ApplyWorldOffset (FVector InOffset)
void ClearForces_AssumesLocked (FBodyInstance *BodyInstance, bool bAllowSubstepping)
void ClearPreSimKinematicUpdate (USkeletalMeshComponent *InSkelComp)
void ClearTorques_AssumesLocked (FBodyInstance *BodyInstance, bool bAllowSubstepping)
IPhysicsReplication * CreatePhysicsReplication ()
void CreatePhysicsReplicationCache ()
Create the replication cache if one doesn't exist.
IPhysicsReplicationLOD * CreatePhysicsReplicationLOD ()
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPhysScenePreTick, FPhysScene_Chaos *, float)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPhysSceneStep, FPhysScene_Chaos *, float)
void DeferPhysicsStateCreation (UPrimitiveComponent *Component)
int32 DirtyElementCount (Chaos::ISpatialAccelerationCollection< Chaos::FAccelerationStructureHandle, Chaos::FReal, 3 > &Collection)
void EnqueueAsyncPhysicsCommand (int32 PhysicsStep, UObject *OwningObject, const TFunction< void()> &Command, const bool bEnableResim=false)
void EnsureCollisionTreeIsBuilt (UWorld *World)
bool ExecApexVis (uint32 SceneType, const TCHAR *Cmd, FOutputDevice *Ar)
bool ExecPxVis (uint32 SceneType, const TCHAR *Cmd, FOutputDevice *Ar)
FBodyInstance * GetBodyInstanceFromProxy (const IPhysicsProxyBase *PhysicsProxy) const
Given a physics proxy, returns its associated body instance if any.
const FBodyInstance * GetBodyInstanceFromProxyAndShape (IPhysicsProxyBase *InProxy, int32 InShapeIndex) const
UChaosEventRelay * GetChaosEventRelay () const
bool GetKinematicTarget_AssumesLocked (const FBodyInstance *BodyInstance, FTransform &OutTM) const
int32 GetNumAwakeBodies () const
const TArray< IPhysicsProxyBase * > * GetOwnedPhysicsProxies (UPrimitiveComponent *Comp) const
Given a component, returns its associated solver objects.
template<class OwnerType>
OwnerType * GetOwningComponent (const IPhysicsProxyBase *PhysicsProxy) const
Given a solver object, returns its associated component.
template<>
UPrimitiveComponent * GetOwningComponent (const IPhysicsProxyBase *PhysicsProxy) const
UWorld * GetOwningWorld ()
const UWorld * GetOwningWorld () const
TArray< FCollisionNotifyInfo > & GetPendingCollisionNotifies (int32 SceneType)
IPhysicsReplication * GetPhysicsReplication ()
FPhysicsReplicationCache * GetPhysicsReplicationCache ()
Get the FPhysicsReplicationCache.
IPhysicsReplicationLOD * GetPhysicsReplicationLOD ()
AActor * GetSolverActor () const
Returns the actor that owns this solver.
const FRigidBodyState * GetStateFromReplicationCache (UPrimitiveComponent *RootComponent, int &ServerFrame)
Get cached state for replication, if no state is cached RegisterForReplicationCache() is called.
bool HandleExecCommands (const TCHAR *Cmd, FOutputDevice *Ar)
bool HasAsyncScene () const
void KillVisualDebugger ()
void ListAwakeRigidBodies (bool bIncludeKinematic)
bool MarkForPreSimKinematicUpdate (USkeletalMeshComponent *InSkelComp, ETeleportType InTeleport, bool bNeedsSkinning)
virtual float OnStartFrame (float InDeltaTime) override
void OnWorldBeginPlay ()
void OnWorldEndPlay ()
Callback when a world ends, to mark updated packages dirty.
Chaos::FSerializedDataBufferPtr PopPendingSerializedStateForObject (UObject *InComponent)
void ProcessAsyncPhysicsStateJobs (bool bWaitForCompletion=false)
void ProcessDeferredCreatePhysicsState ()
bool PushAsyncCreatePhysicsStateJob (IAsyncPhysicsStateProcessor *Processor)
bool PushAsyncDestroyPhysicsStateJob (IAsyncPhysicsStateProcessor *Processor)
void PushPendingSerializedStateForObject (UObject *InComponent, Chaos::FSerializedDataBufferPtr &&InState)
void RegisterAsyncPhysicsTickActor (AActor *Actor)
void RegisterAsyncPhysicsTickComponent (UActorComponent *Component)
void RegisterForCollisionEvents (UPrimitiveComponent *Component)
void RegisterForGlobalCollisionEvents (UPrimitiveComponent *Component)
void RegisterForGlobalRemovalEvents (UPrimitiveComponent *Component)
void RegisterForReplicationCache (UPrimitiveComponent *RootComponent)
Register a component for physics replication state caching, the component will deregister automatically if cache is not accessed within timelimit set by CVar: np2.ReplicationCache.LingerForNSeconds.
void RemoveAsyncPhysicsStateJobs (IAsyncPhysicsStateProcessor *Processor)
void RemoveBodyInstanceFromPendingLists_AssumesLocked (FBodyInstance *BodyInstance, int32 SceneType)
void RemoveDeferredPhysicsStateCreation (UPrimitiveComponent *Component)
void RemoveFromComponentMaps (IPhysicsProxyBase *InObject)
void RemoveObject (Chaos::FClusterUnionPhysicsProxy *InObject)
void RemoveObject (Chaos::FSingleParticlePhysicsProxy *InObject)
void RemoveObject (FGeometryCollectionPhysicsProxy *InObject)
void RemoveObject (FSkeletalMeshPhysicsProxy *InObject)
Called during physics state destruction for the game thread to remove objects from the simulation #BG TODO - Doesn't actually remove from the evolution at the moment.
void RemoveObject (FStaticMeshPhysicsProxy *InObject)
void ResimNFrames (int32 NumFrames)
void SetKinematicTarget_AssumesLocked (FBodyInstance *BodyInstance, const FTransform &TargetTM, bool bAllowSubstepping)
void SetOwningWorld (UWorld *InOwningWorld)
void SetPhysXTreeRebuildRate (int32 RebuildRate)
void StartAsync ()
UE_DEPRECATED (5.5, "Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache and it's getting populated automatically. Use GetStateFromReplicationCache() and RegisterForReplicationCache() to use the replication cache. ") void PopulateReplicationCache(const int32 PhysicsStep)
struct UE_DEPRECATED (5.5, "Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache") FPrimitiveComponentReplicationCache
struct UE_DEPRECATED (5.5, "Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache") FReplicationCacheData
void UnregisterAsyncPhysicsTickActor (AActor *Actor)
void UnregisterAsyncPhysicsTickComponent (UActorComponent *Component)
void UnRegisterForCollisionEvents (UPrimitiveComponent *Component)
void UnRegisterForGlobalCollisionEvents (UPrimitiveComponent *Component)
void UnRegisterForGlobalRemovalEvents (UPrimitiveComponent *Component)
Static Public Member Functions
static bool SupportsAsyncPhysicsStateCreation ()
static bool SupportsAsyncPhysicsStateDestruction ()
static bool SupportsOriginShifting ()
Data Fields
FOnPhysScenePreTick OnPhysScenePreTick
FOnPhysSceneStep OnPhysSceneStep
Static Public Attributes
static Chaos::FCollisionModifierCallback CollisionModifierCallback
static TSharedPtr< IPhysicsReplicationFactory > PhysicsReplicationFactory
Private Member Functions
FPhysicsConstraintHandle AddSpringConstraint (const TArray< TPair< FPhysicsActorHandle, FPhysicsActorHandle > > &Constraint)
void DispatchPendingCollisionNotifies ()
void EnableAsyncPhysicsTickCallback ()
FCollisionNotifyInfo & GetPendingCollisionForContactPair (const void *P0, const void *P1, Chaos::FReal SolverTime, bool &bNewEntry)
void HandleBreakingEvents (const Chaos::FBreakingEventData &Event)
void HandleCollisionEvents (const Chaos::FCollisionEventData &CollisionData)
void HandleCrumblingEvents (const Chaos::FCrumblingEventData &Event)
void HandleEachCollisionEvent (const TArray< int32 > &CollisionIndices, IPhysicsProxyBase *PhysicsProxy0, UPrimitiveComponent *const Comp0, Chaos::FCollisionDataArray const &CollisionData, Chaos::FReal MinDeltaVelocityThreshold)
void HandleGlobalCollisionEvent (Chaos::FCollisionDataArray const &CollisionData)
void HandleRemovalEvents (const Chaos::FRemovalEventData &Event)
bool IsOwningWorldEditor () const
virtual void OnSyncBodies (Chaos::FPhysicsSolverBase *Solver) override
void OnUpdateWorldPause ()
Callback that checks the status of the world settings for this scene before pausing/unpausing its solver.
void RemoveSpringConstraint (const FPhysicsConstraintHandle &Constraint)
void UpdateKinematicsOnDeferredSkelMeshes ()
Process kinematic updates on any deferred skeletal meshes.
Private Attributes
TUniquePtr< FPhysScene_AsyncPhysicsStateJobQueue > AsyncPhysicsStateJobQueue
class FAsyncPhysicsTickCallback * AsyncPhysicsTickCallback = nullptr
bool bIsWorldPaused
TUniquePtr< Chaos::TArrayCollectionArray< FBodyInstance * > > BodyInstances
TObjectPtr< UChaosEventRelay > ChaosEventRelay
TSet< UPrimitiveComponent * > CollisionEventRegistrations
FRWLock CollisionEventRegistrationsLock
TMap< UPrimitiveComponent *, TArray< IPhysicsProxyBase * > > ComponentToPhysicsProxyMap
TMultiMap< FUniqueContactPairKey, int32 > ContactPairToPendingNotifyMap
Key is the unique pair, value is index into PendingNotifies array.
TSet< UPrimitiveComponent * > DeferredCreatePhysicsStateComponents
TArray< TPair< TWeakObjectPtr< USkeletalMeshComponent >, FDeferredKinematicUpdateInfo > > DeferredKinematicUpdateSkelMeshes
Map of SkeletalMeshComponents that need their bone transforms sent to the physics engine before simulation.
TSet< UPrimitiveComponent * > GlobalCollisionEventRegistrations
TSet< UPrimitiveComponent * > GlobalRemovalEventRegistrations
Chaos::FReal LastBreakEventDispatchTime
Chaos::FReal LastCrumblingEventDispatchTime
Chaos::FReal LastEventDispatchTime
Chaos::FReal LastRemovalEventDispatchTime
TArray< FCollisionNotifyInfo > MNotifies
TArray< FCollisionNotifyInfo > PendingCollisionNotifies
Holds the list of pending legacy notifies that are to be processed.
TMap< UObject *, Chaos::FSerializedDataBufferPtr > PendingMigratedPhysicsStateByComponent
FRWLock PhysicsProxyComponentMapsLock
TMap< IPhysicsProxyBase *, TObjectPtr< UPrimitiveComponent > > PhysicsProxyToComponentMap
TUniquePtr< IPhysicsReplication > PhysicsReplication
Physics Replication manager which updates physics particles state to replicate towards networked target states.
TUniquePtr< FPhysicsReplicationCache > PhysicsReplicationCache
TUniquePtr< IPhysicsReplicationLOD > PhysicsReplicationLOD
Physics Replication "Level of Detail" that recommends physics replication mode and how much forward prediction should be applied for replicated physics particles.
int32 SingleStepCounter
TWeakObjectPtr< AActor > SolverActor
The SolverActor that spawned and owns this scene.
Friends
struct ChaosInterface::FScopedSceneReadLock
struct FScopedSceneLock_Chaos
Detailed Description
Low level Chaos scene used when building custom simulations that don't exist in the main world physics scene.
Definition at line 114 of file PhysScene_Chaos.h.
Member Typedef Documentation
Super
using FPhysScene_Chaos::Super = FChaosScene
Definition at line 118 of file PhysScene_Chaos.h.
Constructor & Destructor Documentation
FPhysScene_Chaos()
FPhysScene_Chaos::FPhysScene_Chaos (AActor * InSolverActor = nullptr)
References CHAOS_DEBUG_NAME.
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams(), and DECLARE_MULTICAST_DELEGATE_TwoParams().
~FPhysScene_Chaos()
virtual FPhysScene_Chaos::~FPhysScene_Chaos () virtual
Member Function Documentation
AddAggregateToScene()
void FPhysScene_Chaos::AddAggregateToScene (const FPhysicsAggregateHandle & InAggregate)
AddCustomPhysics_AssumesLocked()
void FPhysScene_Chaos::AddCustomPhysics_AssumesLocked (FBodyInstance * BodyInstance, FCalculateCustomPhysics & CalculateCustomPhysics)
AddForce_AssumesLocked()
void FPhysScene_Chaos::AddForce_AssumesLocked (FBodyInstance * BodyInstance, const FVector & Force, bool bAllowSubstepping, bool bAccelChange)
References Force, and FVector.
AddForceAtPosition_AssumesLocked()
void FPhysScene_Chaos::AddForceAtPosition_AssumesLocked (FBodyInstance * BodyInstance, const FVector & Force, const FVector & Position, bool bAllowSubstepping, bool bIsLocalForce = false)
References Force, FVector, and Position.
AddObject() [1/5]
void FPhysScene_Chaos::AddObject (UPrimitiveComponent * Component, Chaos::FClusterUnionPhysicsProxy * InObject)
References Component.
AddObject() [2/5]
void FPhysScene_Chaos::AddObject (UPrimitiveComponent * Component, Chaos::FSingleParticlePhysicsProxy * InObject)
References Component.
AddObject() [3/5]
void FPhysScene_Chaos::AddObject (UPrimitiveComponent * Component, FGeometryCollectionPhysicsProxy * InObject)
References Component.
AddObject() [4/5]
void FPhysScene_Chaos::AddObject (UPrimitiveComponent * Component, FSkeletalMeshPhysicsProxy * InObject)
Called during creation of the physics state for gamethread objects to pass off an object to the physics thread.
References Component.
AddObject() [5/5]
void FPhysScene_Chaos::AddObject (UPrimitiveComponent * Component, FStaticMeshPhysicsProxy * InObject)
References Component.
AddPendingOnConstraintBreak()
void FPhysScene_Chaos::AddPendingOnConstraintBreak (FConstraintInstance * ConstraintInstance, int32 SceneType)
AddPendingSleepingEvent()
void FPhysScene_Chaos::AddPendingSleepingEvent (FBodyInstance * BI, ESleepEvent SleepEventType, int32 SceneType)
AddRadialForceToBody_AssumesLocked()
void FPhysScene_Chaos::AddRadialForceToBody_AssumesLocked (FBodyInstance * BodyInstance, const FVector & Origin, const float Radius, const float Strength, const uint8 Falloff, bool bAccelChange, bool bAllowSubstepping)
References FVector, and Origin.
AddReferencedObjects()
virtual void FPhysScene_Chaos::AddReferencedObjects (FReferenceCollector & Collector) override virtual
AddSpringConstraint()
FPhysicsConstraintHandle FPhysScene_Chaos::AddSpringConstraint (const TArray< TPair< FPhysicsActorHandle, FPhysicsActorHandle > > & Constraint) private
AddToComponentMaps()
void FPhysScene_Chaos::AddToComponentMaps (UPrimitiveComponent * Component, IPhysicsProxyBase * InObject)
References Component.
AddTorque_AssumesLocked()
void FPhysScene_Chaos::AddTorque_AssumesLocked (FBodyInstance * BodyInstance, const FVector & Torque, bool bAllowSubstepping, bool bAccelChange)
References FVector, and Torque.
ApplyWorldOffset()
void FPhysScene_Chaos::ApplyWorldOffset (FVector InOffset)
References FVector.
ClearForces_AssumesLocked()
void FPhysScene_Chaos::ClearForces_AssumesLocked (FBodyInstance * BodyInstance, bool bAllowSubstepping)
ClearPreSimKinematicUpdate()
void FPhysScene_Chaos::ClearPreSimKinematicUpdate (USkeletalMeshComponent * InSkelComp)
ClearTorques_AssumesLocked()
void FPhysScene_Chaos::ClearTorques_AssumesLocked (FBodyInstance * BodyInstance, bool bAllowSubstepping)
CreatePhysicsReplication()
IPhysicsReplication * FPhysScene_Chaos::CreatePhysicsReplication ()
CreatePhysicsReplicationCache()
void FPhysScene_Chaos::CreatePhysicsReplicationCache ()
Create the replication cache if one doesn't exist.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
Referenced by GetPhysicsReplicationCache().
CreatePhysicsReplicationLOD()
IPhysicsReplicationLOD * FPhysScene_Chaos::CreatePhysicsReplicationLOD ()
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/2]
FPhysScene_Chaos::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPhysScenePreTick , FPhysScene_Chaos * , float)
References FPhysScene_Chaos().
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/2]
FPhysScene_Chaos::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPhysSceneStep , FPhysScene_Chaos * , float)
References FPhysScene_Chaos().
DeferPhysicsStateCreation()
void FPhysScene_Chaos::DeferPhysicsStateCreation (UPrimitiveComponent * Component)
References Component.
DirtyElementCount()
int32 FPhysScene_Chaos::DirtyElementCount (Chaos::ISpatialAccelerationCollection< Chaos::FAccelerationStructureHandle, Chaos::FReal, 3 > & Collection)
DispatchPendingCollisionNotifies()
void FPhysScene_Chaos::DispatchPendingCollisionNotifies () private
EnableAsyncPhysicsTickCallback()
void FPhysScene_Chaos::EnableAsyncPhysicsTickCallback () private
EnqueueAsyncPhysicsCommand()
void FPhysScene_Chaos::EnqueueAsyncPhysicsCommand (int32 PhysicsStep, UObject * OwningObject, const TFunction< void()> & Command, const bool bEnableResim = false)
EnsureCollisionTreeIsBuilt()
void FPhysScene_Chaos::EnsureCollisionTreeIsBuilt (UWorld * World)
ExecApexVis()
bool FPhysScene_Chaos::ExecApexVis (uint32 SceneType, const TCHAR * Cmd, FOutputDevice * Ar)
References Ar, and Cmd.
ExecPxVis()
bool FPhysScene_Chaos::ExecPxVis (uint32 SceneType, const TCHAR * Cmd, FOutputDevice * Ar)
References Ar, and Cmd.
GetBodyInstanceFromProxy()
FBodyInstance * FPhysScene_Chaos::GetBodyInstanceFromProxy (const IPhysicsProxyBase * PhysicsProxy) const
Given a physics proxy, returns its associated body instance if any.
GetBodyInstanceFromProxyAndShape()
const FBodyInstance * FPhysScene_Chaos::GetBodyInstanceFromProxyAndShape (IPhysicsProxyBase * InProxy, int32 InShapeIndex) const
GetChaosEventRelay()
UChaosEventRelay * FPhysScene_Chaos::GetChaosEventRelay () const inline
Definition at line 279 of file PhysScene_Chaos.h.
References ChaosEventRelay.
GetKinematicTarget_AssumesLocked()
bool FPhysScene_Chaos::GetKinematicTarget_AssumesLocked (const FBodyInstance * BodyInstance, FTransform & OutTM) const
GetNumAwakeBodies()
int32 FPhysScene_Chaos::GetNumAwakeBodies () const
GetOwnedPhysicsProxies()
const TArray< IPhysicsProxyBase * > * FPhysScene_Chaos::GetOwnedPhysicsProxies (UPrimitiveComponent * Comp) const inline
Given a component, returns its associated solver objects.
Definition at line 196 of file PhysScene_Chaos.h.
References ComponentToPhysicsProxyMap, and PhysicsProxyComponentMapsLock.
GetOwningComponent() [1/2]
template<class OwnerType> OwnerType * FPhysScene_Chaos::GetOwningComponent (const IPhysicsProxyBase * PhysicsProxy) const inline
Given a solver object, returns its associated component.
Definition at line 185 of file PhysScene_Chaos.h.
References Cast(), PhysicsProxyComponentMapsLock, and PhysicsProxyToComponentMap.
GetOwningComponent() [2/2]
template<> UPrimitiveComponent * FPhysScene_Chaos::GetOwningComponent (const IPhysicsProxyBase * PhysicsProxy) const
GetOwningWorld() [1/2]
UWorld * FPhysScene_Chaos::GetOwningWorld ()
GetOwningWorld() [2/2]
const UWorld * FPhysScene_Chaos::GetOwningWorld () const
GetPendingCollisionForContactPair()
FCollisionNotifyInfo & FPhysScene_Chaos::GetPendingCollisionForContactPair (const void * P0, const void * P1, Chaos::FReal SolverTime, bool & bNewEntry) private
GetPendingCollisionNotifies()
TArray< FCollisionNotifyInfo > & FPhysScene_Chaos::GetPendingCollisionNotifies (int32 SceneType)
GetPhysicsReplication()
IPhysicsReplication * FPhysScene_Chaos::GetPhysicsReplication ()
GetPhysicsReplicationCache()
FPhysicsReplicationCache * FPhysScene_Chaos::GetPhysicsReplicationCache () inline
Get the FPhysicsReplicationCache.
Definition at line 291 of file PhysScene_Chaos.h.
References CreatePhysicsReplicationCache(), and PhysicsReplicationCache.
GetPhysicsReplicationLOD()
IPhysicsReplicationLOD * FPhysScene_Chaos::GetPhysicsReplicationLOD ()
GetSolverActor()
AActor * FPhysScene_Chaos::GetSolverActor () const
Returns the actor that owns this solver.
GetStateFromReplicationCache()
const FRigidBodyState * FPhysScene_Chaos::GetStateFromReplicationCache (UPrimitiveComponent * RootComponent, int & ServerFrame)
Get cached state for replication, if no state is cached RegisterForReplicationCache() is called.
HandleBreakingEvents()
void FPhysScene_Chaos::HandleBreakingEvents (const Chaos::FBreakingEventData & Event) private
References Event.
HandleCollisionEvents()
void FPhysScene_Chaos::HandleCollisionEvents (const Chaos::FCollisionEventData & CollisionData) private
HandleCrumblingEvents()
void FPhysScene_Chaos::HandleCrumblingEvents (const Chaos::FCrumblingEventData & Event) private
References Event.
HandleEachCollisionEvent()
void FPhysScene_Chaos::HandleEachCollisionEvent (const TArray< int32 > & CollisionIndices, IPhysicsProxyBase * PhysicsProxy0, UPrimitiveComponent *const Comp0, Chaos::FCollisionDataArray const & CollisionData, Chaos::FReal MinDeltaVelocityThreshold) private
HandleExecCommands()
bool FPhysScene_Chaos::HandleExecCommands (const TCHAR * Cmd, FOutputDevice * Ar)
References Ar, and Cmd.
HandleGlobalCollisionEvent()
void FPhysScene_Chaos::HandleGlobalCollisionEvent (Chaos::FCollisionDataArray const & CollisionData) private
HandleRemovalEvents()
void FPhysScene_Chaos::HandleRemovalEvents (const Chaos::FRemovalEventData & Event) private
References Event.
HasAsyncScene()
bool FPhysScene_Chaos::HasAsyncScene () const
IsOwningWorldEditor()
bool FPhysScene_Chaos::IsOwningWorldEditor () const private
KillVisualDebugger()
void FPhysScene_Chaos::KillVisualDebugger ()
ListAwakeRigidBodies()
void FPhysScene_Chaos::ListAwakeRigidBodies (bool bIncludeKinematic)
MarkForPreSimKinematicUpdate()
bool FPhysScene_Chaos::MarkForPreSimKinematicUpdate (USkeletalMeshComponent * InSkelComp, ETeleportType InTeleport, bool bNeedsSkinning)
OnStartFrame()
virtual float FPhysScene_Chaos::OnStartFrame (float InDeltaTime) override virtual
OnSyncBodies()
virtual void FPhysScene_Chaos::OnSyncBodies (Chaos::FPhysicsSolverBase * Solver) override private virtual
OnUpdateWorldPause()
void FPhysScene_Chaos::OnUpdateWorldPause () private
Callback that checks the status of the world settings for this scene before pausing/unpausing its solver.
OnWorldBeginPlay()
void FPhysScene_Chaos::OnWorldBeginPlay ()
OnWorldEndPlay()
void FPhysScene_Chaos::OnWorldEndPlay ()
Callback when a world ends, to mark updated packages dirty.
This can't be done in final sync as the editor will ignore packages being dirtied in PIE. Also used to clean up any other references
PopPendingSerializedStateForObject()
Chaos::FSerializedDataBufferPtr FPhysScene_Chaos::PopPendingSerializedStateForObject (UObject * InComponent)
ProcessAsyncPhysicsStateJobs()
void FPhysScene_Chaos::ProcessAsyncPhysicsStateJobs (bool bWaitForCompletion = false)
ProcessDeferredCreatePhysicsState()
void FPhysScene_Chaos::ProcessDeferredCreatePhysicsState ()
PushAsyncCreatePhysicsStateJob()
bool FPhysScene_Chaos::PushAsyncCreatePhysicsStateJob (IAsyncPhysicsStateProcessor * Processor)
PushAsyncDestroyPhysicsStateJob()
bool FPhysScene_Chaos::PushAsyncDestroyPhysicsStateJob (IAsyncPhysicsStateProcessor * Processor)
PushPendingSerializedStateForObject()
void FPhysScene_Chaos::PushPendingSerializedStateForObject (UObject * InComponent, Chaos::FSerializedDataBufferPtr && InState)
RegisterAsyncPhysicsTickActor()
void FPhysScene_Chaos::RegisterAsyncPhysicsTickActor (AActor * Actor)
References Actor.
RegisterAsyncPhysicsTickComponent()
void FPhysScene_Chaos::RegisterAsyncPhysicsTickComponent (UActorComponent * Component)
References Component.
RegisterForCollisionEvents()
void FPhysScene_Chaos::RegisterForCollisionEvents (UPrimitiveComponent * Component)
References Component.
RegisterForGlobalCollisionEvents()
void FPhysScene_Chaos::RegisterForGlobalCollisionEvents (UPrimitiveComponent * Component)
References Component.
RegisterForGlobalRemovalEvents()
void FPhysScene_Chaos::RegisterForGlobalRemovalEvents (UPrimitiveComponent * Component)
References Component.
RegisterForReplicationCache()
void FPhysScene_Chaos::RegisterForReplicationCache (UPrimitiveComponent * RootComponent)
Register a component for physics replication state caching, the component will deregister automatically if cache is not accessed within timelimit set by CVar: np2.ReplicationCache.LingerForNSeconds.
RemoveAsyncPhysicsStateJobs()
void FPhysScene_Chaos::RemoveAsyncPhysicsStateJobs (IAsyncPhysicsStateProcessor * Processor)
RemoveBodyInstanceFromPendingLists_AssumesLocked()
void FPhysScene_Chaos::RemoveBodyInstanceFromPendingLists_AssumesLocked (FBodyInstance * BodyInstance, int32 SceneType)
RemoveDeferredPhysicsStateCreation()
void FPhysScene_Chaos::RemoveDeferredPhysicsStateCreation (UPrimitiveComponent * Component)
References Component.
RemoveFromComponentMaps()
void FPhysScene_Chaos::RemoveFromComponentMaps (IPhysicsProxyBase * InObject)
RemoveObject() [1/5]
void FPhysScene_Chaos::RemoveObject (Chaos::FClusterUnionPhysicsProxy * InObject)
RemoveObject() [2/5]
void FPhysScene_Chaos::RemoveObject (Chaos::FSingleParticlePhysicsProxy * InObject)
RemoveObject() [3/5]
void FPhysScene_Chaos::RemoveObject (FGeometryCollectionPhysicsProxy * InObject)
RemoveObject() [4/5]
void FPhysScene_Chaos::RemoveObject (FSkeletalMeshPhysicsProxy * InObject)
Called during physics state destruction for the game thread to remove objects from the simulation #BG TODO - Doesn't actually remove from the evolution at the moment.
RemoveObject() [5/5]
void FPhysScene_Chaos::RemoveObject (FStaticMeshPhysicsProxy * InObject)
RemoveSpringConstraint()
void FPhysScene_Chaos::RemoveSpringConstraint (const FPhysicsConstraintHandle & Constraint) private
References Force, and Handle.
ResimNFrames()
void FPhysScene_Chaos::ResimNFrames (int32 NumFrames)
References NumFrames.
SetKinematicTarget_AssumesLocked()
void FPhysScene_Chaos::SetKinematicTarget_AssumesLocked (FBodyInstance * BodyInstance, const FTransform & TargetTM, bool bAllowSubstepping)
SetOwningWorld()
void FPhysScene_Chaos::SetOwningWorld (UWorld * InOwningWorld)
SetPhysXTreeRebuildRate()
void FPhysScene_Chaos::SetPhysXTreeRebuildRate (int32 RebuildRate)
StartAsync()
void FPhysScene_Chaos::StartAsync ()
SupportsAsyncPhysicsStateCreation()
bool FPhysScene_Chaos::SupportsAsyncPhysicsStateCreation () static
SupportsAsyncPhysicsStateDestruction()
bool FPhysScene_Chaos::SupportsAsyncPhysicsStateDestruction () static
SupportsOriginShifting()
bool FPhysScene_Chaos::SupportsOriginShifting () static
UE_DEPRECATED() [1/3]
FPhysScene_Chaos::UE_DEPRECATED (5. 5, " Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache and it 's getting populated automatically. Use GetStateFromReplicationCache() and RegisterForReplicationCache() to use the replication cache. ") const inline
Definition at line 287 of file PhysScene_Chaos.h.
Referenced by CreatePhysicsReplicationCache().
UE_DEPRECATED() [2/3]
struct FPhysScene_Chaos::UE_DEPRECATED (5. 5, " Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache") inline
Definition at line 300 of file PhysScene_Chaos.h.
UE_DEPRECATED() [3/3]
struct FPhysScene_Chaos::UE_DEPRECATED (5. 5, " Deprecated, ReplicationCache has been moved to FPhysicsReplicationCache") inline
Definition at line 300 of file PhysScene_Chaos.h.
UnregisterAsyncPhysicsTickActor()
void FPhysScene_Chaos::UnregisterAsyncPhysicsTickActor (AActor * Actor)
References Actor.
UnregisterAsyncPhysicsTickComponent()
void FPhysScene_Chaos::UnregisterAsyncPhysicsTickComponent (UActorComponent * Component)
References Component.
UnRegisterForCollisionEvents()
void FPhysScene_Chaos::UnRegisterForCollisionEvents (UPrimitiveComponent * Component)
References Component.
UnRegisterForGlobalCollisionEvents()
void FPhysScene_Chaos::UnRegisterForGlobalCollisionEvents (UPrimitiveComponent * Component)
References Component.
UnRegisterForGlobalRemovalEvents()
void FPhysScene_Chaos::UnRegisterForGlobalRemovalEvents (UPrimitiveComponent * Component)
References Component.
UpdateKinematicsOnDeferredSkelMeshes()
void FPhysScene_Chaos::UpdateKinematicsOnDeferredSkelMeshes () private
Process kinematic updates on any deferred skeletal meshes.
Friends And Related Symbol Documentation
ChaosInterface::FScopedSceneReadLock
friend struct ChaosInterface::FScopedSceneReadLock friend
Definition at line 517 of file PhysScene_Chaos.h.
FScopedSceneLock_Chaos
friend struct FScopedSceneLock_Chaos friend
Definition at line 518 of file PhysScene_Chaos.h.
References FScopedSceneLock_Chaos.
Referenced by FScopedSceneLock_Chaos.
Field Documentation
AsyncPhysicsStateJobQueue
TUniquePtr<FPhysScene_AsyncPhysicsStateJobQueue> FPhysScene_Chaos::AsyncPhysicsStateJobQueue private
Definition at line 473 of file PhysScene_Chaos.h.
AsyncPhysicsTickCallback
class FAsyncPhysicsTickCallback* FPhysScene_Chaos::AsyncPhysicsTickCallback = nullptr private
Definition at line 505 of file PhysScene_Chaos.h.
bIsWorldPaused
bool FPhysScene_Chaos::bIsWorldPaused private
Definition at line 513 of file PhysScene_Chaos.h.
BodyInstances
TUniquePtr<Chaos::TArrayCollectionArray<FBodyInstance*> > FPhysScene_Chaos::BodyInstances private
Definition at line 482 of file PhysScene_Chaos.h.
ChaosEventRelay
TObjectPtr<UChaosEventRelay> FPhysScene_Chaos::ChaosEventRelay private
Definition at line 498 of file PhysScene_Chaos.h.
Referenced by GetChaosEventRelay().
CollisionEventRegistrations
TSet<UPrimitiveComponent*> FPhysScene_Chaos::CollisionEventRegistrations private
Definition at line 362 of file PhysScene_Chaos.h.
CollisionEventRegistrationsLock
FRWLock FPhysScene_Chaos::CollisionEventRegistrationsLock mutable private
Definition at line 479 of file PhysScene_Chaos.h.
CollisionModifierCallback
Chaos::FCollisionModifierCallback FPhysScene_Chaos::CollisionModifierCallback static
Definition at line 266 of file PhysScene_Chaos.h.
ComponentToPhysicsProxyMap
TMap<UPrimitiveComponent*, TArray<IPhysicsProxyBase*> > FPhysScene_Chaos::ComponentToPhysicsProxyMap private
Definition at line 490 of file PhysScene_Chaos.h.
Referenced by GetOwnedPhysicsProxies().
ContactPairToPendingNotifyMap
TMultiMap<FUniqueContactPairKey, int32> FPhysScene_Chaos::ContactPairToPendingNotifyMap private
Key is the unique pair, value is index into PendingNotifies array.
Definition at line 386 of file PhysScene_Chaos.h.
DeferredCreatePhysicsStateComponents
TSet<UPrimitiveComponent*> FPhysScene_Chaos::DeferredCreatePhysicsStateComponents private
Definition at line 470 of file PhysScene_Chaos.h.
DeferredKinematicUpdateSkelMeshes
TArray<TPair<TWeakObjectPtr<USkeletalMeshComponent>, FDeferredKinematicUpdateInfo> > FPhysScene_Chaos::DeferredKinematicUpdateSkelMeshes private
Map of SkeletalMeshComponents that need their bone transforms sent to the physics engine before simulation.
Definition at line 468 of file PhysScene_Chaos.h.
GlobalCollisionEventRegistrations
TSet<UPrimitiveComponent*> FPhysScene_Chaos::GlobalCollisionEventRegistrations private
Definition at line 363 of file PhysScene_Chaos.h.
GlobalRemovalEventRegistrations
TSet<UPrimitiveComponent*> FPhysScene_Chaos::GlobalRemovalEventRegistrations private
Definition at line 364 of file PhysScene_Chaos.h.
LastBreakEventDispatchTime
Chaos::FReal FPhysScene_Chaos::LastBreakEventDispatchTime private
Definition at line 501 of file PhysScene_Chaos.h.
LastCrumblingEventDispatchTime
Chaos::FReal FPhysScene_Chaos::LastCrumblingEventDispatchTime private
Definition at line 503 of file PhysScene_Chaos.h.
LastEventDispatchTime
Chaos::FReal FPhysScene_Chaos::LastEventDispatchTime private
Definition at line 500 of file PhysScene_Chaos.h.
LastRemovalEventDispatchTime
Chaos::FReal FPhysScene_Chaos::LastRemovalEventDispatchTime private
Definition at line 502 of file PhysScene_Chaos.h.
MNotifies
TArray<FCollisionNotifyInfo> FPhysScene_Chaos::MNotifies private
Definition at line 484 of file PhysScene_Chaos.h.
OnPhysScenePreTick
FOnPhysScenePreTick FPhysScene_Chaos::OnPhysScenePreTick
Definition at line 259 of file PhysScene_Chaos.h.
OnPhysSceneStep
FOnPhysSceneStep FPhysScene_Chaos::OnPhysSceneStep
Definition at line 261 of file PhysScene_Chaos.h.
PendingCollisionNotifies
TArray<FCollisionNotifyInfo> FPhysScene_Chaos::PendingCollisionNotifies private
Holds the list of pending legacy notifies that are to be processed.
Definition at line 389 of file PhysScene_Chaos.h.
PendingMigratedPhysicsStateByComponent
TMap<UObject*, Chaos::FSerializedDataBufferPtr> FPhysScene_Chaos::PendingMigratedPhysicsStateByComponent private
Definition at line 358 of file PhysScene_Chaos.h.
PhysicsProxyComponentMapsLock
FRWLock FPhysScene_Chaos::PhysicsProxyComponentMapsLock mutable private
Definition at line 476 of file PhysScene_Chaos.h.
Referenced by GetOwnedPhysicsProxies(), and GetOwningComponent().
PhysicsProxyToComponentMap
TMap<IPhysicsProxyBase*, TObjectPtr<UPrimitiveComponent> > FPhysScene_Chaos::PhysicsProxyToComponentMap private
Definition at line 487 of file PhysScene_Chaos.h.
Referenced by GetOwningComponent().
PhysicsReplication
TUniquePtr<IPhysicsReplication> FPhysScene_Chaos::PhysicsReplication private
Physics Replication manager which updates physics particles state to replicate towards networked target states.
Definition at line 402 of file PhysScene_Chaos.h.
PhysicsReplicationCache
TUniquePtr<FPhysicsReplicationCache> FPhysScene_Chaos::PhysicsReplicationCache private
Definition at line 360 of file PhysScene_Chaos.h.
Referenced by GetPhysicsReplicationCache().
PhysicsReplicationFactory
TSharedPtr<IPhysicsReplicationFactory> FPhysScene_Chaos::PhysicsReplicationFactory static
Definition at line 250 of file PhysScene_Chaos.h.
PhysicsReplicationLOD
TUniquePtr<IPhysicsReplicationLOD> FPhysScene_Chaos::PhysicsReplicationLOD private
Physics Replication "Level of Detail" that recommends physics replication mode and how much forward prediction should be applied for replicated physics particles.
Definition at line 405 of file PhysScene_Chaos.h.
SingleStepCounter
int32 FPhysScene_Chaos::SingleStepCounter private
Definition at line 509 of file PhysScene_Chaos.h.
SolverActor
TWeakObjectPtr<AActor> FPhysScene_Chaos::SolverActor private
The SolverActor that spawned and owns this scene.
Definition at line 496 of file PhysScene_Chaos.h.
The documentation for this class was generated from the following file:
PhysScene_Chaos.h