Unreal Engine 5.6 C++ API: ISequencerTextFilterExpressionContext Class Reference
ISequencerTextFilterExpressionContext Class Reference abstract
Extends the ITextFilterExpressionContext interface to add support for suggestions.
#include "ISequencerTextFilterExpressionContext.h"
Public Member Functions
virtual SEQUENCER_API FText GetCategory () const
virtual SEQUENCER_API FText GetDescription () const =0
virtual SEQUENCER_API TSet< FName > GetKeys () const =0
virtual SEQUENCER_API TArray< FSequencerTextFilterKeyword > GetValueKeywords () const
virtual SEQUENCER_API ESequencerTextFilterValueType GetValueType () const =0
Public Member Functions inherited from ITextFilterExpressionContext
virtual bool TestBasicStringExpression (const FTextFilterString &InValue, const ETextFilterTextComparisonMode InTextComparisonMode) const =0
Test the given value against the strings extracted from the current item.
virtual bool TestComplexExpression (const FName &InKey, const FTextFilterString &InValue, const ETextFilterComparisonOperation InComparisonOperation, const ETextFilterTextComparisonMode InTextComparisonMode) const =0
Perform a complex expression test for the current item.
Static Public Member Functions
static bool CompareFStringForExactBool (const FTextFilterString &InValue, const bool bInPassedFilter)
static bool CompareFStringForExactBool (const FTextFilterString &InValue, const ETextFilterComparisonOperation InComparisonOperation, const bool bInPassedFilter)
Additional Inherited Members
Protected Member Functions inherited from ITextFilterExpressionContext
virtual ~ITextFilterExpressionContext ()
Detailed Description
Extends the ITextFilterExpressionContext interface to add support for suggestions.
Definition at line 22 of file ISequencerTextFilterExpressionContext.h.
Member Function Documentation
CompareFStringForExactBool() [1/2]
bool ISequencerTextFilterExpressionContext::CompareFStringForExactBool (const FTextFilterString & InValue, const bool bInPassedFilter) inline static
Definition at line 33 of file ISequencerTextFilterExpressionContext.h.
References FTextFilterString::CompareFString(), Exact, and TEXT.
Referenced by CompareFStringForExactBool().
CompareFStringForExactBool() [2/2]
bool ISequencerTextFilterExpressionContext::CompareFStringForExactBool (const FTextFilterString & InValue, const ETextFilterComparisonOperation InComparisonOperation, const bool bInPassedFilter) inline static
Definition at line 46 of file ISequencerTextFilterExpressionContext.h.
References CompareFStringForExactBool(), Equal, and NotEqual.
GetCategory()
virtual SEQUENCER_API FText ISequencerTextFilterExpressionContext::GetCategory () const inline virtual
Definition at line 31 of file ISequencerTextFilterExpressionContext.h.
References FText::GetEmpty().
GetDescription()
virtual SEQUENCER_API FText ISequencerTextFilterExpressionContext::GetDescription () const pure virtual
GetKeys()
virtual SEQUENCER_API TSet< FName > ISequencerTextFilterExpressionContext::GetKeys () const pure virtual
GetValueKeywords()
virtual SEQUENCER_API TArray< FSequencerTextFilterKeyword > ISequencerTextFilterExpressionContext::GetValueKeywords () const inline virtual
Definition at line 28 of file ISequencerTextFilterExpressionContext.h.
GetValueType()
virtual SEQUENCER_API ESequencerTextFilterValueType ISequencerTextFilterExpressionContext::GetValueType () const pure virtual
References ESequencerTextFilterValueType::ESequencerTextFilterValueType.
The documentation for this class was generated from the following file:
ISequencerTextFilterExpressionContext.h