Unreal Engine 5.6 C++ API: FRDGShaderResourceView Class Reference
FRDGShaderResourceView Class Reference
Render graph tracked SRV.
#include "RenderGraphResources.h"
Public Member Functions
FRHIShaderResourceView * GetRHI () const
Returns the allocated RHI SRV.
Public Member Functions inherited from FRDGView
FRDGViewHandle GetHandle () const
virtual FRDGViewableResource * GetParent () const =0
Returns the referenced parent render graph resource.
ERDGViewableResourceType GetParentType () const
Public Member Functions inherited from FRDGResource
FRDGResource (const FRDGResource &)=delete
virtual ~FRDGResource ()=default
FRHIResource * GetRHI () const
virtual RENDERCORE_API void MarkResourceAsUsed ()
The following methods may only be called during pass execution.
Protected Member Functions
FRDGShaderResourceView (const TCHAR *InName, ERDGViewType InType)
FRHIShaderResourceView * GetRHIUnchecked () const
Returns the allocated RHI SRV without access checks.
Protected Member Functions inherited from FRDGView
FRDGView (const TCHAR *Name, ERDGViewType InType)
Protected Member Functions inherited from FRDGResource
FRDGResource (const TCHAR *InName)
FRHIResource * GetRHIUnchecked () const
bool HasRHI () const
RENDERCORE_API void ValidateRHIAccess () const
Additional Inherited Members
Data Fields inherited from FRDGView
const ERDGViewType Type
The type of this child resource; useful for casting between types.
Data Fields inherited from FRDGResource
const TCHAR *const Name = nullptr
Protected Attributes inherited from FRDGResource
FRHIResource * ResourceRHI = nullptr
Detailed Description
Render graph tracked SRV.
Definition at line 696 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGShaderResourceView()
FRDGShaderResourceView::FRDGShaderResourceView (const TCHAR * InName, ERDGViewType InType) inline protected
Definition at line 707 of file RenderGraphResources.h.
References FRDGView::FRDGView(), and InName.
Referenced by FRDGBufferSRV::FRDGBufferSRV(), and FRDGTextureSRV::FRDGTextureSRV().
Member Function Documentation
GetRHI()
FRHIShaderResourceView * FRDGShaderResourceView::GetRHI () const inline
Returns the allocated RHI SRV.
Definition at line 701 of file RenderGraphResources.h.
References FRDGResource::GetRHI().
GetRHIUnchecked()
FRHIShaderResourceView * FRDGShaderResourceView::GetRHIUnchecked () const inline protected
Returns the allocated RHI SRV without access checks.
Definition at line 712 of file RenderGraphResources.h.
References FRDGResource::GetRHIUnchecked().
The documentation for this class was generated from the following file:
RenderGraphResources.h