Unreal Engine 5.6 C++ API: UE::MovieScene::FMovieSceneTracksComponentTypes Struct Reference
UE::MovieScene::FMovieSceneTracksComponentTypes Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Data Structures
struct FAccessors
struct FObjectPropertyRegistration
Public Member Functions
MOVIESCENETRACKS_API ~FMovieSceneTracksComponentTypes ()
Static Public Member Functions
static MOVIESCENETRACKS_API void Destroy ()
static MOVIESCENETRACKS_API FMovieSceneTracksComponentTypes * Get ()
Data Fields
struct UE::MovieScene::FMovieSceneTracksComponentTypes::FAccessors Accessors
TComponentTypeID< FAttachmentComponent > AttachComponent
TComponentTypeID< TWeakObjectPtr< USceneComponent > > AttachParent
TComponentTypeID< FMovieSceneObjectBindingID > AttachParentBinding
TComponentTypeID< FMovieSceneAudioComponentData > Audio
TComponentTypeID< FMovieSceneAudioInputData > AudioInputs
TComponentTypeID< FName > AudioTriggerName
TPropertyComponents< FBoolPropertyTraits > Bool
TComponentTypeID< FName > BoolParameterName
TComponentTypeID< FObjectComponent > BoundMaterial
TPropertyComponents< FBytePropertyTraits > Byte
TComponentTypeID< FMovieSceneCameraShakeComponentData > CameraShake
TComponentTypeID< FMovieSceneCameraShakeInstanceData > CameraShakeInstance
TPropertyComponents< FColorPropertyTraits > Color
TComponentTypeID< FMaterialParameterInfo > ColorMaterialParameterInfo
TPropertyComponents< FColorParameterTraits > ColorParameter
TComponentTypeID< FName > ColorParameterName
TComponentTypeID< FComponentMaterialInfo > ComponentMaterialInfo
TPropertyComponents< FComponentTransformPropertyTraits > ComponentTransform
TComponentTypeID< FConstraintComponentData > ConstraintChannel
TComponentTypeID< FMovieSceneDataLayerComponentData > DataLayer
TPropertyComponents< FDoublePropertyTraits > Double
TComponentTypeID< FPerlinNoiseParams > DoublePerlinNoiseChannel
TPropertyComponents< FDoubleVectorPropertyTraits > DoubleVector
TPropertyComponents< FEnumPropertyTraits > Enum
TPropertyComponents< FEulerTransformPropertyTraits > EulerTransform
TComponentTypeID< FFadeComponentData > Fade
TPropertyComponents< FFloatPropertyTraits > Float
TPropertyComponents< FFloatParameterTraits > FloatParameter
TComponentTypeID< FPerlinNoiseParams > FloatPerlinNoiseChannel
TPropertyComponents< FFloatVectorPropertyTraits > FloatVector
TComponentTypeID< FName > GenericParameterName
TPropertyComponents< FIntPropertyTraits > Integer
TComponentTypeID< FLevelVisibilityComponentData > LevelVisibility
TComponentTypeID< TWeakObjectPtr< UMaterialParameterCollection > > MPC
TPropertyComponents< FObjectPropertyTraits > Object
struct {
TPropertyComponents< FBoolParameterTraits > Bool
TPropertyComponents< FByteParameterTraits > Byte
TPropertyComponents< FColorParameterTraits > Color
TPropertyComponents< FIntegerParameterTraits > Integer
TPropertyComponents< FFloatParameterTraits > Scalar
TPropertyComponents< FTransformParameterTraits > Transform
TPropertyComponents< FVector2ParameterTraits > Vector2
TPropertyComponents< FVector3ParameterTraits > Vector3
} Parameters
TComponentTypeID< FSourceDoubleChannel > QuaternionRotationChannel [3]
TPropertyComponents< FRotatorPropertyTraits > Rotator
TComponentTypeID< FSourceDoubleChannel > RotatorChannel [3]
TComponentTypeID< FMaterialParameterInfo > ScalarMaterialParameterInfo
TComponentTypeID< FName > ScalarParameterName
TComponentTypeID< FMovieSceneSkeletalAnimationComponentData > SkeletalAnimation
TPropertyComponents< FStringPropertyTraits > String
struct {
FComponentTypeID AnimMixerPoseProducer
FComponentTypeID BoundMaterialChanged
FComponentTypeID CustomPrimitiveData
FComponentTypeID Slomo
FComponentTypeID Visibility
} Tags
TPropertyComponents< FTransformPropertyTraits > Transform
TComponentTypeID< FName > TransformParameterName
TComponentTypeID< FName > Vector2DParameterName
TComponentTypeID< FMaterialParameterInfo > VectorMaterialParameterInfo
TComponentTypeID< FName > VectorParameterName
Private Member Functions
FMovieSceneTracksComponentTypes ()
Detailed Description
Definition at line 670 of file MovieSceneTracksComponentTypes.h.
Constructor & Destructor Documentation
~FMovieSceneTracksComponentTypes()
MOVIESCENETRACKS_API UE::MovieScene::FMovieSceneTracksComponentTypes::~FMovieSceneTracksComponentTypes ()
FMovieSceneTracksComponentTypes()
UE::MovieScene::FMovieSceneTracksComponentTypes::FMovieSceneTracksComponentTypes () private
Referenced by Get().
Member Function Documentation
Destroy()
MOVIESCENETRACKS_API void UE::MovieScene::FMovieSceneTracksComponentTypes::Destroy () static
Get()
MOVIESCENETRACKS_API FMovieSceneTracksComponentTypes * UE::MovieScene::FMovieSceneTracksComponentTypes::Get () static
References FMovieSceneTracksComponentTypes().
Referenced by UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::TAddBoundMaterialMutationImpl(), UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnPostSpawn(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), and UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::PostTask().
Field Documentation
Accessors
struct UE::MovieScene::FMovieSceneTracksComponentTypes::FAccessors UE::MovieScene::FMovieSceneTracksComponentTypes::Accessors
AnimMixerPoseProducer
FComponentTypeID UE::MovieScene::FMovieSceneTracksComponentTypes::AnimMixerPoseProducer
Definition at line 791 of file MovieSceneTracksComponentTypes.h.
AttachComponent
TComponentTypeID<FAttachmentComponent> UE::MovieScene::FMovieSceneTracksComponentTypes::AttachComponent
Definition at line 699 of file MovieSceneTracksComponentTypes.h.
AttachParent
TComponentTypeID<TWeakObjectPtr<USceneComponent> > UE::MovieScene::FMovieSceneTracksComponentTypes::AttachParent
Definition at line 698 of file MovieSceneTracksComponentTypes.h.
AttachParentBinding
TComponentTypeID<FMovieSceneObjectBindingID> UE::MovieScene::FMovieSceneTracksComponentTypes::AttachParentBinding
Definition at line 700 of file MovieSceneTracksComponentTypes.h.
Audio
TComponentTypeID<FMovieSceneAudioComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::Audio
Definition at line 738 of file MovieSceneTracksComponentTypes.h.
AudioInputs
TComponentTypeID<FMovieSceneAudioInputData> UE::MovieScene::FMovieSceneTracksComponentTypes::AudioInputs
Definition at line 739 of file MovieSceneTracksComponentTypes.h.
AudioTriggerName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::AudioTriggerName
Definition at line 740 of file MovieSceneTracksComponentTypes.h.
Bool [1/2]
TPropertyComponents<FBoolPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Bool
Definition at line 674 of file MovieSceneTracksComponentTypes.h.
Bool [2/2]
TPropertyComponents<FBoolParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Bool
Definition at line 719 of file MovieSceneTracksComponentTypes.h.
BoolParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::BoolParameterName
Definition at line 708 of file MovieSceneTracksComponentTypes.h.
BoundMaterial
TComponentTypeID<FObjectComponent> UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterial
Definition at line 733 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnPostSpawn(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun().
BoundMaterialChanged
FComponentTypeID UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterialChanged
Definition at line 786 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::PostTask().
Byte [1/2]
TPropertyComponents<FBytePropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Byte
Definition at line 675 of file MovieSceneTracksComponentTypes.h.
Byte [2/2]
TPropertyComponents<FByteParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Byte
Definition at line 720 of file MovieSceneTracksComponentTypes.h.
CameraShake
TComponentTypeID<FMovieSceneCameraShakeComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::CameraShake
Definition at line 742 of file MovieSceneTracksComponentTypes.h.
CameraShakeInstance
TComponentTypeID<FMovieSceneCameraShakeInstanceData> UE::MovieScene::FMovieSceneTracksComponentTypes::CameraShakeInstance
Definition at line 743 of file MovieSceneTracksComponentTypes.h.
Color [1/2]
TPropertyComponents<FColorPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Color
Definition at line 680 of file MovieSceneTracksComponentTypes.h.
Color [2/2]
TPropertyComponents<FColorParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Color
Definition at line 725 of file MovieSceneTracksComponentTypes.h.
ColorMaterialParameterInfo
TComponentTypeID<FMaterialParameterInfo> UE::MovieScene::FMovieSceneTracksComponentTypes::ColorMaterialParameterInfo
Definition at line 730 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
ColorParameter
TPropertyComponents<FColorParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::ColorParameter
Definition at line 691 of file MovieSceneTracksComponentTypes.h.
ColorParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::ColorParameterName
Definition at line 712 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
ComponentMaterialInfo
TComponentTypeID<FComponentMaterialInfo> UE::MovieScene::FMovieSceneTracksComponentTypes::ComponentMaterialInfo
Definition at line 706 of file MovieSceneTracksComponentTypes.h.
ComponentTransform
TPropertyComponents<FComponentTransformPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::ComponentTransform
Definition at line 685 of file MovieSceneTracksComponentTypes.h.
ConstraintChannel
TComponentTypeID<FConstraintComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::ConstraintChannel
Definition at line 696 of file MovieSceneTracksComponentTypes.h.
CustomPrimitiveData
FComponentTypeID UE::MovieScene::FMovieSceneTracksComponentTypes::CustomPrimitiveData
Definition at line 787 of file MovieSceneTracksComponentTypes.h.
DataLayer
TComponentTypeID<FMovieSceneDataLayerComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::DataLayer
Definition at line 795 of file MovieSceneTracksComponentTypes.h.
Double
TPropertyComponents<FDoublePropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Double
Definition at line 679 of file MovieSceneTracksComponentTypes.h.
DoublePerlinNoiseChannel
TComponentTypeID<FPerlinNoiseParams> UE::MovieScene::FMovieSceneTracksComponentTypes::DoublePerlinNoiseChannel
Definition at line 702 of file MovieSceneTracksComponentTypes.h.
DoubleVector
TPropertyComponents<FDoubleVectorPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::DoubleVector
Definition at line 682 of file MovieSceneTracksComponentTypes.h.
Enum
TPropertyComponents<FEnumPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Enum
Definition at line 676 of file MovieSceneTracksComponentTypes.h.
EulerTransform
TPropertyComponents<FEulerTransformPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::EulerTransform
Definition at line 684 of file MovieSceneTracksComponentTypes.h.
Fade
TComponentTypeID<FFadeComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::Fade
Definition at line 736 of file MovieSceneTracksComponentTypes.h.
Float
TPropertyComponents<FFloatPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Float
Definition at line 678 of file MovieSceneTracksComponentTypes.h.
FloatParameter
TPropertyComponents<FFloatParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::FloatParameter
Definition at line 690 of file MovieSceneTracksComponentTypes.h.
FloatPerlinNoiseChannel
TComponentTypeID<FPerlinNoiseParams> UE::MovieScene::FMovieSceneTracksComponentTypes::FloatPerlinNoiseChannel
Definition at line 701 of file MovieSceneTracksComponentTypes.h.
FloatVector
TPropertyComponents<FFloatVectorPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::FloatVector
Definition at line 681 of file MovieSceneTracksComponentTypes.h.
GenericParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::GenericParameterName
Definition at line 715 of file MovieSceneTracksComponentTypes.h.
Integer [1/2]
TPropertyComponents<FIntPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Integer
Definition at line 677 of file MovieSceneTracksComponentTypes.h.
Integer [2/2]
TPropertyComponents<FIntegerParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Integer
Definition at line 721 of file MovieSceneTracksComponentTypes.h.
LevelVisibility
TComponentTypeID<FLevelVisibilityComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::LevelVisibility
Definition at line 794 of file MovieSceneTracksComponentTypes.h.
MPC
TComponentTypeID<TWeakObjectPtr<UMaterialParameterCollection> > UE::MovieScene::FMovieSceneTracksComponentTypes::MPC
Definition at line 734 of file MovieSceneTracksComponentTypes.h.
Object
TPropertyComponents<FObjectPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Object
Definition at line 688 of file MovieSceneTracksComponentTypes.h.
[struct]
struct { ... } UE::MovieScene::FMovieSceneTracksComponentTypes::Parameters
QuaternionRotationChannel
TComponentTypeID<FSourceDoubleChannel> UE::MovieScene::FMovieSceneTracksComponentTypes::QuaternionRotationChannel[3]
Definition at line 693 of file MovieSceneTracksComponentTypes.h.
Rotator
TPropertyComponents<FRotatorPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Rotator
Definition at line 686 of file MovieSceneTracksComponentTypes.h.
RotatorChannel
TComponentTypeID<FSourceDoubleChannel> UE::MovieScene::FMovieSceneTracksComponentTypes::RotatorChannel[3]
Definition at line 694 of file MovieSceneTracksComponentTypes.h.
Scalar
TPropertyComponents<FFloatParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Scalar
Definition at line 722 of file MovieSceneTracksComponentTypes.h.
ScalarMaterialParameterInfo
TComponentTypeID<FMaterialParameterInfo> UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarMaterialParameterInfo
Definition at line 729 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
ScalarParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarParameterName
Definition at line 709 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
SkeletalAnimation
TComponentTypeID<FMovieSceneSkeletalAnimationComponentData> UE::MovieScene::FMovieSceneTracksComponentTypes::SkeletalAnimation
Definition at line 704 of file MovieSceneTracksComponentTypes.h.
Slomo
FComponentTypeID UE::MovieScene::FMovieSceneTracksComponentTypes::Slomo
Definition at line 788 of file MovieSceneTracksComponentTypes.h.
String
TPropertyComponents<FStringPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::String
Definition at line 687 of file MovieSceneTracksComponentTypes.h.
[struct]
struct { ... } UE::MovieScene::FMovieSceneTracksComponentTypes::Tags
Referenced by UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::PostTask().
Transform [1/2]
TPropertyComponents<FTransformPropertyTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Transform
Definition at line 683 of file MovieSceneTracksComponentTypes.h.
Transform [2/2]
TPropertyComponents<FTransformParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Transform
Definition at line 726 of file MovieSceneTracksComponentTypes.h.
TransformParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::TransformParameterName
Definition at line 713 of file MovieSceneTracksComponentTypes.h.
Vector2
TPropertyComponents<FVector2ParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Vector2
Definition at line 723 of file MovieSceneTracksComponentTypes.h.
Vector2DParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::Vector2DParameterName
Definition at line 710 of file MovieSceneTracksComponentTypes.h.
Vector3
TPropertyComponents<FVector3ParameterTraits> UE::MovieScene::FMovieSceneTracksComponentTypes::Vector3
Definition at line 724 of file MovieSceneTracksComponentTypes.h.
VectorMaterialParameterInfo
TComponentTypeID<FMaterialParameterInfo> UE::MovieScene::FMovieSceneTracksComponentTypes::VectorMaterialParameterInfo
Definition at line 731 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
VectorParameterName
TComponentTypeID<FName> UE::MovieScene::FMovieSceneTracksComponentTypes::VectorParameterName
Definition at line 711 of file MovieSceneTracksComponentTypes.h.
Referenced by UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), and UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink().
Visibility
FComponentTypeID UE::MovieScene::FMovieSceneTracksComponentTypes::Visibility
Definition at line 789 of file MovieSceneTracksComponentTypes.h.
The documentation for this struct was generated from the following file:
MovieSceneTracksComponentTypes.h