Unreal Engine 5.6 C++ API: UAssetManagerSettings Class Reference
UAssetManagerSettings Class Reference
#include "AssetManagerSettings.h"
Private Member Functions
void ApplyMetaDataTagsSettings ()
void ClearMetaDataTagsSettings ()
GENERATED_BODY () public
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded) override
virtual void PreEditChange (FProperty *PropertyAboutToChange) override
UPROPERTY () bool bOnlyCookProductionAssets
If true, DevelopmentCook assets will error when they are cooked, you should enable this on production branches.
UPROPERTY () bool bShouldAcquireMissingChunksOnLoad
If true, this will query the platform chunk install interface to request missing chunks for any requested primary asset loads.
UPROPERTY () bool bShouldGuessTypeAndNameInEditor
If true, PrimaryAsset Type/Name will be implied for assets in the editor even if bShouldManagerDetermineTypeAndName is false.
UPROPERTY () bool bShouldManagerDetermineTypeAndName
If true, the asset manager will determine the type and name for Primary Assets that do not implement GetPrimaryAssetId, by calling DeterminePrimaryAssetIdForObject and using the ini settings.
UPROPERTY () bool bShouldWarnAboutInvalidAssets
If true, the asset manager will warn when it is told to load or do something with assets it does not know about.
UPROPERTY () TArray< FAssetManagerRedirect > AssetPathRedirects
Redirect from /game/assetpath to /game/assetpathnew.
UPROPERTY () TArray< FAssetManagerRedirect > PrimaryAssetIdRedirects
Redirect from Type:Name to Type:NameNew.
UPROPERTY () TArray< FAssetManagerRedirect > PrimaryAssetTypeRedirects
Redirect from Type to TypeNew.
UPROPERTY () TArray< FPrimaryAssetRulesCustomOverride > CustomPrimaryAssetRules
List of game-specific asset rule overrides for types, this will not do anything by default.
UPROPERTY () TArray< FPrimaryAssetRulesOverride > PrimaryAssetRules
List of specific asset rule overrides.
UPROPERTY () TSet< FName > MetaDataTagsForAssetRegistry
The metadata tags to be transferred to the Asset Registry.
UPROPERTY ()) TArray< FDirectoryPath > DirectoriesToExclude
List of directories to exclude from scanning for Primary Assets, useful to exclude test assets.
UPROPERTY ()) TArray< FPrimaryAssetTypeInfo > PrimaryAssetTypesToScan
List of asset types to scan at startup.
Detailed Description
Definition at line 67 of file AssetManagerSettings.h.
Member Function Documentation
ApplyMetaDataTagsSettings()
void UAssetManagerSettings::ApplyMetaDataTagsSettings () private
ClearMetaDataTagsSettings()
void UAssetManagerSettings::ClearMetaDataTagsSettings () private
GENERATED_BODY()
UAssetManagerSettings::GENERATED_BODY () inline private
Definition at line 69 of file AssetManagerSettings.h.
PostEditChangeProperty()
virtual void UAssetManagerSettings::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UAssetManagerSettings::PostInitProperties () override private virtual
PostReloadConfig()
virtual void UAssetManagerSettings::PostReloadConfig (class FProperty * PropertyThatWasLoaded) override private virtual
References PostReloadConfig().
Referenced by PostReloadConfig().
PreEditChange()
virtual void UAssetManagerSettings::PreEditChange (FProperty * PropertyAboutToChange) override private virtual
UPROPERTY() [1/13]
UAssetManagerSettings::UPROPERTY () private
If true, DevelopmentCook assets will error when they are cooked, you should enable this on production branches.
References Category, config, and UPROPERTY().
UPROPERTY() [2/13]
UAssetManagerSettings::UPROPERTY () private
If true, this will query the platform chunk install interface to request missing chunks for any requested primary asset loads.
References Category, config, and UPROPERTY().
UPROPERTY() [3/13]
UAssetManagerSettings::UPROPERTY () private
If true, PrimaryAsset Type/Name will be implied for assets in the editor even if bShouldManagerDetermineTypeAndName is false.
This guesses the correct id for content that hasn't been resaved after GetPrimaryAssetId was implemented
References Category, config, and UPROPERTY().
UPROPERTY() [4/13]
UAssetManagerSettings::UPROPERTY () private
If true, the asset manager will determine the type and name for Primary Assets that do not implement GetPrimaryAssetId, by calling DeterminePrimaryAssetIdForObject and using the ini settings.
This works in both cooked and uncooked builds but is slower than directly implementing GetPrimaryAssetId on the native asset
References Category, config, and UPROPERTY().
UPROPERTY() [5/13]
UAssetManagerSettings::UPROPERTY () private
If true, the asset manager will warn when it is told to load or do something with assets it does not know about.
References Category, config, and UPROPERTY().
UPROPERTY() [6/13]
UAssetManagerSettings::UPROPERTY () private
Redirect from /game/assetpath to /game/assetpathnew.
References Category, config, and UPROPERTY().
UPROPERTY() [7/13]
UAssetManagerSettings::UPROPERTY () private
Redirect from Type:Name to Type:NameNew.
References Category, config, and UPROPERTY().
UPROPERTY() [8/13]
UAssetManagerSettings::UPROPERTY () private
Redirect from Type to TypeNew.
References Category, config, and UPROPERTY().
UPROPERTY() [9/13]
UAssetManagerSettings::UPROPERTY () private
List of game-specific asset rule overrides for types, this will not do anything by default.
References Category, config, and UPROPERTY().
UPROPERTY() [10/13]
UAssetManagerSettings::UPROPERTY () private
List of specific asset rule overrides.
References Category, config, and UPROPERTY().
UPROPERTY() [11/13]
UAssetManagerSettings::UPROPERTY () private
The metadata tags to be transferred to the Asset Registry.
References Category, config, and UPROPERTY().
UPROPERTY() [12/13]
UAssetManagerSettings::UPROPERTY () private
List of directories to exclude from scanning for Primary Assets, useful to exclude test assets.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [13/13]
UAssetManagerSettings::UPROPERTY () private
List of asset types to scan at startup.
References Category, config, and meta.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
AssetManagerSettings.h