Unreal Engine 5.6 C++ API: FExternalPackageHelper::FRenameExternalObjectsHelperContext Class Reference
FExternalPackageHelper::FRenameExternalObjectsHelperContext Class Reference
#include "ExternalPackageHelper.h"
Public Member Functions
FRenameExternalObjectsHelperContext ()=delete
FRenameExternalObjectsHelperContext (const UObject *SourceObject, ERenameFlags Flags)
FRenameExternalObjectsHelperContext (FRenameExternalObjectsHelperContext &)=delete
~FRenameExternalObjectsHelperContext ()
FRenameExternalObjectsHelperContext & operator= (FRenameExternalObjectsHelperContext &)=delete
Private Attributes
const UObject * OldObject = nullptr
const UPackage * SourcePackage = nullptr
Detailed Description
Definition at line 27 of file ExternalPackageHelper.h.
Constructor & Destructor Documentation
FRenameExternalObjectsHelperContext() [1/3]
FExternalPackageHelper::FRenameExternalObjectsHelperContext::FRenameExternalObjectsHelperContext () delete
Referenced by FRenameExternalObjectsHelperContext(), and operator=().
FRenameExternalObjectsHelperContext() [2/3]
FExternalPackageHelper::FRenameExternalObjectsHelperContext::FRenameExternalObjectsHelperContext (FRenameExternalObjectsHelperContext &) delete
References FRenameExternalObjectsHelperContext().
FRenameExternalObjectsHelperContext() [3/3]
FExternalPackageHelper::FRenameExternalObjectsHelperContext::FRenameExternalObjectsHelperContext (const UObject * SourceObject, ERenameFlags Flags) explicit
References Flags.
~FRenameExternalObjectsHelperContext()
FExternalPackageHelper::FRenameExternalObjectsHelperContext::~FRenameExternalObjectsHelperContext ()
Member Function Documentation
operator=()
FRenameExternalObjectsHelperContext & FExternalPackageHelper::FRenameExternalObjectsHelperContext::operator= (FRenameExternalObjectsHelperContext &) delete
References FRenameExternalObjectsHelperContext().
Field Documentation
OldObject
const UObject* FExternalPackageHelper::FRenameExternalObjectsHelperContext::OldObject = nullptr private
Definition at line 37 of file ExternalPackageHelper.h.
SourcePackage
const UPackage* FExternalPackageHelper::FRenameExternalObjectsHelperContext::SourcePackage = nullptr private
Definition at line 38 of file ExternalPackageHelper.h.
The documentation for this class was generated from the following file:
ExternalPackageHelper.h