Unreal Engine 5.6 C++ API: UE::Anim::Compression Namespace Reference
UE::Anim::Compression Namespace Reference
Data Structures
struct FAnimationCompressionMemorySummaryScope
struct FScopedCompressionGuard
Functions
bool CompressAnimationDataTracks (const USkeleton *Skeleton, const TArray< FTrackToSkeletonMap > &TrackToSkeleton, TArray< FRawAnimSequenceTrack > &RawAnimationData, int32 NumberOfKeys, FName ErrorName, float MaxPosDiff=0.0001f, float MaxAngleDiff=0.0003f, float MaxScaleDiff=0.0001f)
Compress the provided tracks using two methods.
bool CompressRawAnimSequenceTrack (FRawAnimSequenceTrack &RawTrack, int32 NumberOfKeys, FName ErrorName, float MaxPosDiff, float MaxAngleDiff, float MaxScaleDiff)
Compress the provided track by checking for uniform key data according to the provided error metrics.
void SanitizeRawAnimSequenceTrack (FRawAnimSequenceTrack &RawTrack)
Sanitize the provided track by snapping small scale values to 0, and normalizing any rotational keys.
UE_DEPRECATED (5.4, "CompressAnimationDataTracks has been deprecated use other signature with skeleton and bone mappings") 1 bool CompressAnimationDataTracks(TArray< FRawAnimSequenceTrack > &RawAnimationData
Compress the provided tracks using two methods.
UE_DEPRECATED (5.5, "CompressRawAnimSequenceTrack requires the MaxScaleDiff argument") 1 bool CompressRawAnimSequenceTrack(FRawAnimSequenceTrack &RawTrack
Compress the provided track by checking for uniform key data according to the provided error metrics.
Variables
static const FString AnimationCompressionVersionString = TEXT("0439926D560447329623BE4394FA11A6")
int32 FName ErrorName
int32 FName float float MaxAngleDiff = 0.0003f
int32 FName float MaxPosDiff = 0.0001f
int32 FName float float float MaxScaleDiff = 0.0001f)
int32 NumberOfKeys
Function Documentation
CompressAnimationDataTracks()
bool UE::Anim::Compression::CompressAnimationDataTracks (const USkeleton * Skeleton, const TArray< FTrackToSkeletonMap > & TrackToSkeleton, TArray< FRawAnimSequenceTrack > & RawAnimationData, int32 NumberOfKeys, FName ErrorName, float MaxPosDiff = 0.0001f, float MaxAngleDiff = 0.0003f, float MaxScaleDiff = 0.0001f)
Compress the provided tracks using two methods.
Checking for uniform key data according to the provided error metrics
Setting number of scale keys to 0 if it is uniform, equal to FVector::OneVector and matches the Skeleton reference bone pose(s)
Parameters
RawAnimationData Set of tracks to apply the reduction to
NumberOfKeys Expected number of keys for each component within the tracks
ErrorName Identifier for outer callsite when failing to reduce the data
MaxPosDiff Maximum positional delta when determining whether or not two positional keys are identical
MaxAngleDiff Maximum rotational delta when determining whether or not two rotational keys are identical
Returns
Whether or not the operation was succesful
References CompressAnimationDataTracks(), ErrorName, MaxAngleDiff, MaxPosDiff, MaxScaleDiff, NumberOfKeys, and Skeleton.
Referenced by CompressAnimationDataTracks().
CompressRawAnimSequenceTrack()
bool UE::Anim::Compression::CompressRawAnimSequenceTrack (FRawAnimSequenceTrack & RawTrack, int32 NumberOfKeys, FName ErrorName, float MaxPosDiff, float MaxAngleDiff, float MaxScaleDiff)
Compress the provided track by checking for uniform key data according to the provided error metrics.
Parameters
RawTrack Individual track to apply the reduction to
NumberOfKeys Expected number of keys for each component within the tracks
ErrorName Identifier for outer callsite when failing to reduce the data
MaxPosDiff Maximum positional delta when determining whether or not two positional keys are identical
MaxAngleDiff Maximum rotational delta when determining whether or not two rotational keys are identical
MaxScaleDiff Maximum scale delta when determining whether or not two scale keys are identical
Returns
Whether or not the operation was succesful
References CompressRawAnimSequenceTrack(), ErrorName, MaxAngleDiff, MaxPosDiff, MaxScaleDiff, and NumberOfKeys.
Referenced by CompressRawAnimSequenceTrack(), and UE_DEPRECATED().
SanitizeRawAnimSequenceTrack()
void UE::Anim::Compression::SanitizeRawAnimSequenceTrack (FRawAnimSequenceTrack & RawTrack)
Sanitize the provided track by snapping small scale values to 0, and normalizing any rotational keys.
Parameters
RawTrack Individual track to sanitize
References SanitizeRawAnimSequenceTrack().
Referenced by SanitizeRawAnimSequenceTrack().
UE_DEPRECATED() [1/2]
UE::Anim::Compression::UE_DEPRECATED (5. 4, "CompressAnimationDataTracks has been deprecated use other signature with skeleton and bone mappings") &
Compress the provided tracks using two methods.
Checking for uniform key data according to the provided error metrics
Setting number of scale keys to 0 if it is uniform and equal to FVector::OneVector
Parameters
RawAnimationData Set of tracks to apply the reduction to
NumberOfKeys Expected number of keys for each component within the tracks
ErrorName Identifier for outer callsite when failing to reduce the data
MaxPosDiff Maximum positional delta when determining whether or not two positional keys are identical
MaxAngleDiff Maximum rotational delta when determining whether or not two rotational keys are identical
Returns
Whether or not the operation was succesful
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Anim::Compression::UE_DEPRECATED (5. 5, "CompressRawAnimSequenceTrack requires the MaxScaleDiff argument") &
Compress the provided track by checking for uniform key data according to the provided error metrics.
Parameters
RawTrack Individual track to apply the reduction to
NumberOfKeys Expected number of keys for each component within the tracks
ErrorName Identifier for outer callsite when failing to reduce the data
MaxPosDiff Maximum positional delta when determining whether or not two positional keys are identical
MaxAngleDiff Maximum rotational delta when determining whether or not two rotational keys are identical
Returns
Whether or not the operation was succesful
References CompressRawAnimSequenceTrack(), ErrorName, MaxAngleDiff, MaxPosDiff, NumberOfKeys, and UE_DEPRECATED().
Variable Documentation
AnimationCompressionVersionString
const FString UE::Anim::Compression::AnimationCompressionVersionString = TEXT("0439926D560447329623BE4394FA11A6") static
Definition at line 275 of file AnimCompress.h.
ErrorName
int32 FName UE::Anim::Compression::ErrorName
Definition at line 245 of file AnimSequenceHelpers.h.
Referenced by CompressAnimationDataTracks(), CompressRawAnimSequenceTrack(), and UE_DEPRECATED().
MaxAngleDiff
int32 FName float float UE::Anim::Compression::MaxAngleDiff = 0.0003f
Definition at line 245 of file AnimSequenceHelpers.h.
Referenced by CompressAnimationDataTracks(), CompressRawAnimSequenceTrack(), and UE_DEPRECATED().
MaxPosDiff
int32 FName float UE::Anim::Compression::MaxPosDiff = 0.0001f
Definition at line 245 of file AnimSequenceHelpers.h.
Referenced by CompressAnimationDataTracks(), CompressRawAnimSequenceTrack(), and UE_DEPRECATED().
MaxScaleDiff
int32 FName float float float UE::Anim::Compression::MaxScaleDiff = 0.0001f)
Definition at line 245 of file AnimSequenceHelpers.h.
Referenced by CompressAnimationDataTracks(), and CompressRawAnimSequenceTrack().
NumberOfKeys
int32 UE::Anim::Compression::NumberOfKeys
Definition at line 245 of file AnimSequenceHelpers.h.
Referenced by CompressAnimationDataTracks(), CompressRawAnimSequenceTrack(), and UE_DEPRECATED().