Unreal Engine 5.6 C++ API: UE::Geometry::TDistLine3Triangle3< Real > Class Template Reference
UE::Geometry::TDistLine3Triangle3< Real > Class Template Reference
Compute unsigned distance between 3D line and 3D triangle.
#include "DistLine3Triangle3.h"
Public Member Functions
TDistLine3Triangle3 (const TLine3< Real > &LineIn, const TTriangle3< Real > &TriangleIn)
Real ComputeResult ()
Real Get ()
Real GetSquared ()
Data Fields
Real DistanceSquared = -1.0
TLine3< Real > Line
TVector< Real > LineClosest
Real LineParam
TTriangle3< Real > Triangle
TVector< Real > TriangleBaryCoords
TVector< Real > TriangleClosest
Detailed Description
template<typename Real>
class UE::Geometry::TDistLine3Triangle3< Real >
Compute unsigned distance between 3D line and 3D triangle.
Definition at line 24 of file DistLine3Triangle3.h.
Constructor & Destructor Documentation
TDistLine3Triangle3()
template<typename Real> UE::Geometry::TDistLine3Triangle3< Real >::TDistLine3Triangle3 (const TLine3< Real > & LineIn, const TTriangle3< Real > & TriangleIn) inline
Definition at line 37 of file DistLine3Triangle3.h.
Member Function Documentation
ComputeResult()
template<typename Real> Real UE::Geometry::TDistLine3Triangle3< Real >::ComputeResult () inline
Definition at line 50 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistLine3Triangle3< float >::Get(), and UE::Geometry::TDistLine3Triangle3< float >::GetSquared().
Get()
template<typename Real> Real UE::Geometry::TDistLine3Triangle3< Real >::Get () inline
Definition at line 41 of file DistLine3Triangle3.h.
GetSquared()
template<typename Real> Real UE::Geometry::TDistLine3Triangle3< Real >::GetSquared () inline
Definition at line 45 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
Field Documentation
DistanceSquared
template<typename Real> Real UE::Geometry::TDistLine3Triangle3< Real >::DistanceSquared = -1.0
Definition at line 32 of file DistLine3Triangle3.h.
Line
template<typename Real> TLine3<Real> UE::Geometry::TDistLine3Triangle3< Real >::Line
Definition at line 28 of file DistLine3Triangle3.h.
LineClosest
template<typename Real> TVector<Real> UE::Geometry::TDistLine3Triangle3< Real >::LineClosest
Definition at line 34 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
LineParam
template<typename Real> Real UE::Geometry::TDistLine3Triangle3< Real >::LineParam
Definition at line 33 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
Triangle
template<typename Real> TTriangle3<Real> UE::Geometry::TDistLine3Triangle3< Real >::Triangle
Definition at line 29 of file DistLine3Triangle3.h.
TriangleBaryCoords
template<typename Real> TVector<Real> UE::Geometry::TDistLine3Triangle3< Real >::TriangleBaryCoords
Definition at line 34 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
TriangleClosest
template<typename Real> TVector<Real> UE::Geometry::TDistLine3Triangle3< Real >::TriangleClosest
Definition at line 34 of file DistLine3Triangle3.h.
Referenced by UE::Geometry::TDistSegment3Triangle3< float >::ComputeResult().
The documentation for this class was generated from the following file:
DistLine3Triangle3.h