Unreal Engine 5.6 C++ API: UShapeComponent Class Reference
UShapeComponent Class Reference
#include "ShapeComponent.h"
Public Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual class UBodySetup * GetBodySetup () override
TSubclassOf< class UNavAreaBase > GetDesiredAreaClass () const
virtual bool GetIgnoreBoundsForEditorFocus () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual bool IsNavigationRelevant () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void Serialize (FArchive &Ar) override
void SetAreaClassOverride (TSubclassOf< class UNavAreaBase > InAreaClassOverride)
void SetUseSystemDefaultObstacleAreaClass ()
virtual bool ShouldCollideWhenPlacing () const override
UFUNCTION () 1 void SetLineThickness(float Thickness)
virtual void UpdateBodySetup ()
Update the body setup parameters based on shape information.
Protected Member Functions
template<typename ShapeElemType>
void AddShapeToGeomArray ()
template<typename ShapeElemType>
void CreateShapeBodySetupIfNeeded ()
template<typename ComponentType>
bool PrepareSharedBodySetup ()
Checks if a shared body setup is available (and if we're eligible for it).
template<typename ShapeElemType>
void SetShapeToNewGeom (const FPhysicsShapeHandle &Shape)
UPROPERTY () float LineThickness
Used to control the line thickness when rendering.
UPROPERTY ()) TSubclassOf< class UNavAreaBase > AreaClassOverride
Navigation area type override, null / none = no change to nav mesh.
Protected Attributes
UPROPERTY()) uint8 bUseSystemDefaultObstacleAreaClass uint8 bUseArchetypeBodySetup: 1
Only show this component if the actor is selected.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UBodySetup > ShapeBodySetup
Description of collision.
UPROPERTY () FColor ShapeColor
Color used to draw the shape.
Detailed Description
Definition at line 24 of file ShapeComponent.h.
Member Function Documentation
AddShapeToGeomArray()
template<typename ShapeElemType> void UShapeComponent::AddShapeToGeomArray () protected
CalcBounds()
virtual FBoxSphereBounds UShapeComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented in UBoxComponent, UCapsuleComponent, and USphereComponent.
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UShapeComponent::CreateSceneProxy () override virtual
Reimplemented in UBoxComponent, UCapsuleComponent, and USphereComponent.
CreateShapeBodySetupIfNeeded()
template<typename ShapeElemType> void UShapeComponent::CreateShapeBodySetupIfNeeded () protected
DoCustomNavigableGeometryExport()
virtual bool UShapeComponent::DoCustomNavigableGeometryExport (FNavigableGeometryExport & GeomExport) const override virtual
GENERATED_UCLASS_BODY()
UShapeComponent::GENERATED_UCLASS_BODY () private
Description of collision.
References transient, and UPROPERTY().
GetBodySetup()
virtual class UBodySetup * UShapeComponent::GetBodySetup () override virtual
GetDesiredAreaClass()
TSubclassOf< class UNavAreaBase > UShapeComponent::GetDesiredAreaClass () const
GetIgnoreBoundsForEditorFocus()
virtual bool UShapeComponent::GetIgnoreBoundsForEditorFocus () const inline override virtual
Definition at line 120 of file ShapeComponent.h.
GetNavigationData()
virtual void UShapeComponent::GetNavigationData (FNavigationRelevantData & Data) const override virtual
IsNavigationRelevant()
virtual bool UShapeComponent::IsNavigationRelevant () const override virtual
PostEditChangeProperty()
virtual void UShapeComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented in UCapsuleComponent.
PrepareSharedBodySetup()
template<typename ComponentType> bool UShapeComponent::PrepareSharedBodySetup () inline protected
Checks if a shared body setup is available (and if we're eligible for it).
If successful you must still check for staleness
Definition at line 78 of file ShapeComponent.h.
References bUseArchetypeBodySetup, CastChecked(), and PrepareSharedBodySetup().
Referenced by PrepareSharedBodySetup().
Serialize()
virtual void UShapeComponent::Serialize (FArchive & Ar) override virtual
References Ar.
Referenced by UCapsuleComponent::PostLoad().
SetAreaClassOverride()
void UShapeComponent::SetAreaClassOverride (TSubclassOf< class UNavAreaBase > InAreaClassOverride)
SetShapeToNewGeom()
template<typename ShapeElemType> void UShapeComponent::SetShapeToNewGeom (const FPhysicsShapeHandle & Shape) protected
SetUseSystemDefaultObstacleAreaClass()
void UShapeComponent::SetUseSystemDefaultObstacleAreaClass ()
ShouldCollideWhenPlacing()
virtual bool UShapeComponent::ShouldCollideWhenPlacing () const inline override virtual
Definition at line 112 of file ShapeComponent.h.
UFUNCTION()
UShapeComponent::UFUNCTION ()
References Category.
UpdateBodySetup()
virtual void UShapeComponent::UpdateBodySetup () virtual
Update the body setup parameters based on shape information.
Reimplemented in UBoxComponent, UCapsuleComponent, and USphereComponent.
UPROPERTY() [1/3]
UShapeComponent::UPROPERTY () private
Color used to draw the shape.
References Category, meta, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/3]
UShapeComponent::UPROPERTY () protected
Used to control the line thickness when rendering.
References Category, and UPROPERTY().
UPROPERTY() [3/3]
UShapeComponent::UPROPERTY () protected
Navigation area type override, null / none = no change to nav mesh.
bDynamicObstacle must be true and bUseSystemDefaultAreaClass false to use this.
References Category, meta, and UPROPERTY().
Field Documentation
bUseArchetypeBodySetup
UPROPERTY ()) uint8 bUseSystemDefaultObstacleAreaClass uint8 UShapeComponent::bUseArchetypeBodySetup protected
Only show this component if the actor is selected.
If true it allows Collision when placing even if collision is not enabled If set, shape will be exported for navigation as dynamic modifier instead of using regular collision data Uses FNavigationSystem::GetDefaultObstacleArea() by default instead of AreaClassOverride, bDynamicObstacle must be true to use this. If the body setup can be shared (i.e. there have been no alterations compared to the CDO)
Definition at line 64 of file ShapeComponent.h.
Referenced by PrepareSharedBodySetup().
The documentation for this class was generated from the following file:
ShapeComponent.h