Unreal Engine 5.6 C++ API: FOpenAsyncPackageResult Struct Reference
FOpenAsyncPackageResult Struct Reference
#include "PackageResourceManager.h"
Public Member Functions
FOpenAsyncPackageResult ()=default
FOpenAsyncPackageResult (const FOpenAsyncPackageResult &)=delete
FOpenAsyncPackageResult (FOpenAsyncPackageResult &&)=default
FOpenAsyncPackageResult (TUniquePtr< IAsyncReadFileHandle > &&InHandle, EPackageFormat InFormat, bool bInNeedsEngineVersionChecks=true)
~FOpenAsyncPackageResult ()
void CopyMetaData (const FOpenPackageResult &Other)
FOpenAsyncPackageResult & operator= (const FOpenAsyncPackageResult &)=delete
FOpenAsyncPackageResult & operator= (FOpenAsyncPackageResult &&)=default
Data Fields
bool bNeedsEngineVersionChecks = true
True if the package is of unknown version and needs to check for version and corruption.
EPackageFormat Format = EPackageFormat::Binary
Format of the archive, binary or text.
TUniquePtr< IAsyncReadFileHandle > Handle
AsyncReadFileHandle for the requested Segment bytes, in canceled state if it does not exist.
Detailed Description
Definition at line 74 of file PackageResourceManager.h.
Constructor & Destructor Documentation
FOpenAsyncPackageResult() [1/4]
FOpenAsyncPackageResult::FOpenAsyncPackageResult () default
Referenced by FOpenAsyncPackageResult(), FOpenAsyncPackageResult(), operator=(), and operator=().
FOpenAsyncPackageResult() [2/4]
FOpenAsyncPackageResult::FOpenAsyncPackageResult (const FOpenAsyncPackageResult &) delete
References FOpenAsyncPackageResult().
FOpenAsyncPackageResult() [3/4]
FOpenAsyncPackageResult::FOpenAsyncPackageResult (FOpenAsyncPackageResult &&) default
References FOpenAsyncPackageResult().
FOpenAsyncPackageResult() [4/4]
FOpenAsyncPackageResult::FOpenAsyncPackageResult (TUniquePtr< IAsyncReadFileHandle > && InHandle, EPackageFormat InFormat, bool bInNeedsEngineVersionChecks = true)
~FOpenAsyncPackageResult()
FOpenAsyncPackageResult::~FOpenAsyncPackageResult ()
Member Function Documentation
CopyMetaData()
void FOpenAsyncPackageResult::CopyMetaData (const FOpenPackageResult & Other) inline
Definition at line 99 of file PackageResourceManager.h.
References bNeedsEngineVersionChecks, Format, and Other.
operator=() [1/2]
FOpenAsyncPackageResult & FOpenAsyncPackageResult::operator= (const FOpenAsyncPackageResult &) delete
References FOpenAsyncPackageResult().
operator=() [2/2]
FOpenAsyncPackageResult & FOpenAsyncPackageResult::operator= (FOpenAsyncPackageResult &&) default
References FOpenAsyncPackageResult().
Field Documentation
bNeedsEngineVersionChecks
bool FOpenAsyncPackageResult::bNeedsEngineVersionChecks = true
True if the package is of unknown version and needs to check for version and corruption.
False if the package was loaded from a repository specifically for the current binary's versions and has already been checked for corruption.
Definition at line 88 of file PackageResourceManager.h.
Referenced by CopyMetaData().
Format
EPackageFormat FOpenAsyncPackageResult::Format = EPackageFormat::Binary
Format of the archive, binary or text.
Currently only header segments can have EPackageFormat::Text, all other segments have EPackageFormat::Binary
Definition at line 82 of file PackageResourceManager.h.
Referenced by CopyMetaData().
Handle
TUniquePtr<IAsyncReadFileHandle> FOpenAsyncPackageResult::Handle
AsyncReadFileHandle for the requested Segment bytes, in canceled state if it does not exist.
Definition at line 77 of file PackageResourceManager.h.
The documentation for this struct was generated from the following file:
PackageResourceManager.h