Unreal Engine 5.6 C++ API: FShaderCompileJobKey Struct Reference
FShaderCompileJobKey Struct Reference
#include "ShaderCompilerJobTypes.h"
Public Member Functions
FShaderCompileJobKey (const FShaderType *InType=nullptr, const FVertexFactoryType *InVFType=nullptr, int32 InPermutationId=0)
uint32 MakeHash (uint32 Id) const
RENDERCORE_API FString ToString () const
Data Fields
int32 PermutationId
const FShaderType * ShaderType
const FVertexFactoryType * VFType
Friends
bool operator!= (const FShaderCompileJobKey &Lhs, const FShaderCompileJobKey &Rhs)
bool operator== (const FShaderCompileJobKey &Lhs, const FShaderCompileJobKey &Rhs)
Detailed Description
Definition at line 299 of file ShaderCompilerJobTypes.h.
Constructor & Destructor Documentation
FShaderCompileJobKey()
FShaderCompileJobKey::FShaderCompileJobKey (const FShaderType * InType = nullptr, const FVertexFactoryType * InVFType = nullptr, int32 InPermutationId = 0) inline explicit
Definition at line 301 of file ShaderCompilerJobTypes.h.
References PermutationId, ShaderType, and VFType.
Referenced by operator!=, and operator==.
Member Function Documentation
MakeHash()
uint32 FShaderCompileJobKey::MakeHash (uint32 Id) const inline
Definition at line 305 of file ShaderCompilerJobTypes.h.
References GetTypeHash(), HashCombine(), PermutationId, ShaderType, and VFType.
ToString()
RENDERCORE_API FString FShaderCompileJobKey::ToString () const
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FShaderCompileJobKey & Lhs, const FShaderCompileJobKey & Rhs) friend
Definition at line 315 of file ShaderCompilerJobTypes.h.
References FShaderCompileJobKey(), and operator==.
operator==
bool operator== (const FShaderCompileJobKey & Lhs, const FShaderCompileJobKey & Rhs) friend
Definition at line 311 of file ShaderCompilerJobTypes.h.
References FShaderCompileJobKey(), PermutationId, ShaderType, and VFType.
Referenced by operator!=.
Field Documentation
PermutationId
int32 FShaderCompileJobKey::PermutationId
Definition at line 309 of file ShaderCompilerJobTypes.h.
Referenced by FShaderCompileJobKey(), MakeHash(), and operator==.
ShaderType
const FShaderType* FShaderCompileJobKey::ShaderType
Definition at line 307 of file ShaderCompilerJobTypes.h.
Referenced by FShaderCompileJobKey(), MakeHash(), and operator==.
VFType
const FVertexFactoryType* FShaderCompileJobKey::VFType
Definition at line 308 of file ShaderCompilerJobTypes.h.
Referenced by FShaderCompileJobKey(), MakeHash(), and operator==.
The documentation for this struct was generated from the following file:
ShaderCompilerJobTypes.h