Unreal Engine 5.6 C++ API: FSkeletonRemapping Struct Reference
FSkeletonRemapping Struct Reference
#include "SkeletonRemapping.h"
Public Member Functions
FSkeletonRemapping ()=default
FSkeletonRemapping (const USkeleton *InSourceSkeleton, const USkeleton *InTargetSkeleton)
void ComposeWith (const FSkeletonRemapping &OtherSkeletonRemapping)
Compose this remapping with another remapping in place.
const TWeakObjectPtr< const USkeleton > & GetSourceSkeleton () const
int32 GetSourceSkeletonBoneIndex (int32 TargetSkeletonBoneIndex) const
Get the source skeleton bone index that corresponds to the specified bone on the target skeleton.
const TWeakObjectPtr< const USkeleton > & GetTargetSkeleton () const
int32 GetTargetSkeletonBoneIndex (int32 SourceSkeletonBoneIndex) const
Get the target skeleton bone index that corresponds to the specified bone on the source skeleton.
bool IsValid () const
Check whether this mapping is valid - whether the source and target hierarchies still exist.
UE_DEPRECATED(5.3, "This function is no longer used") 1 const TArray< SmartName void RegenerateMapping ()
Refreshes the mapping.
bool RequiresReferencePoseRetarget () const
Check to see if a reference pose retarget is required between the source & target hierarchies.
FQuat RetargetAdditiveRotationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FQuat &SourceRotation) const
Get the specified additive rotation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
FTransform RetargetAdditiveTransformToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FTransform &SourceTransform) const
Get the specified additive transform retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
FVector RetargetAdditiveTranslationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FVector &SourceTranslation) const
Get the specified additive translation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
FQuat RetargetBoneRotationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FQuat &SourceRotation) const
Get the specified bone rotation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
FTransform RetargetBoneTransformToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FTransform &SourceTransform) const
Get the specified bone transform retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
FVector RetargetBoneTranslationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FVector &SourceTranslation) const
Get the specified bone translation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
UE_DEPRECATED (5.3, "This function is no longer used") void GenerateCurveMapping()
Private Member Functions
void GenerateMapping ()
Internal helper function - performs mapping generation.
Private Attributes
TArray< TTuple< FQuat, FQuat > > RetargetingTable
TWeakObjectPtr< const USkeleton > SourceSkeleton
TArray< int32 > SourceToTargetBoneIndexes
TWeakObjectPtr< const USkeleton > TargetSkeleton
TArray< int32 > TargetToSourceBoneIndexes
Detailed Description
Definition at line 10 of file SkeletonRemapping.h.
Constructor & Destructor Documentation
FSkeletonRemapping() [1/2]
FSkeletonRemapping::FSkeletonRemapping () default
Referenced by ComposeWith().
FSkeletonRemapping() [2/2]
FSkeletonRemapping::FSkeletonRemapping (const USkeleton * InSourceSkeleton, const USkeleton * InTargetSkeleton)
Member Function Documentation
ComposeWith()
void FSkeletonRemapping::ComposeWith (const FSkeletonRemapping & OtherSkeletonRemapping)
Compose this remapping with another remapping in place.
The other remapping's source skeleton must match this remapping's target skeleton. The result will map from this remapping's source skeleton to the other remapping's target skeleton
Parameters
OtherSkeletonRemapping Skeleton remapping to compose into this remapping
References FSkeletonRemapping().
GenerateMapping()
void FSkeletonRemapping::GenerateMapping () private
Internal helper function - performs mapping generation.
GetSourceSkeleton()
const TWeakObjectPtr< const USkeleton > & FSkeletonRemapping::GetSourceSkeleton () const inline
Definition at line 15 of file SkeletonRemapping.h.
References SourceSkeleton.
GetSourceSkeletonBoneIndex()
int32 FSkeletonRemapping::GetSourceSkeletonBoneIndex (int32 TargetSkeletonBoneIndex) const inline
Get the source skeleton bone index that corresponds to the specified bone on the target skeleton.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
Returns
Skeleton bone index on the source skeleton (or INDEX_NONE)
Definition at line 46 of file SkeletonRemapping.h.
References INDEX_NONE, and TargetToSourceBoneIndexes.
GetTargetSkeleton()
const TWeakObjectPtr< const USkeleton > & FSkeletonRemapping::GetTargetSkeleton () const inline
Definition at line 16 of file SkeletonRemapping.h.
References TargetSkeleton.
GetTargetSkeletonBoneIndex()
int32 FSkeletonRemapping::GetTargetSkeletonBoneIndex (int32 SourceSkeletonBoneIndex) const inline
Get the target skeleton bone index that corresponds to the specified bone on the source skeleton.
Parameters
SourceSkeletonBoneIndex Skeleton bone index on the source skeleton
Returns
Skeleton bone index on the target skeleton (or INDEX_NONE)
Definition at line 33 of file SkeletonRemapping.h.
References INDEX_NONE, and SourceToTargetBoneIndexes.
IsValid()
bool FSkeletonRemapping::IsValid () const inline
Check whether this mapping is valid - whether the source and target hierarchies still exist.
Definition at line 161 of file SkeletonRemapping.h.
References SourceSkeleton, and TargetSkeleton.
RegenerateMapping()
UE_DEPRECATED(5.3, "This function is no longer used") 1 const TArray< SmartName void FSkeletonRemapping::RegenerateMapping ()
Refreshes the mapping.
Empties mapping arrays and regenerates them against the stored skeletons.
References RegenerateMapping().
Referenced by RegenerateMapping().
RequiresReferencePoseRetarget()
bool FSkeletonRemapping::RequiresReferencePoseRetarget () const inline
Check to see if a reference pose retarget is required between the source & target hierarchies.
Definition at line 155 of file SkeletonRemapping.h.
References RetargetingTable.
RetargetAdditiveRotationToTargetSkeleton()
FQuat FSkeletonRemapping::RetargetAdditiveRotationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FQuat & SourceRotation) const inline
Get the specified additive rotation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceRotation Bone rotation from the corresponding bone on the source skeleton
Returns
Rotation mapped onto the target skeleton
Definition at line 138 of file SkeletonRemapping.h.
References RetargetingTable.
Referenced by RetargetAdditiveTransformToTargetSkeleton().
RetargetAdditiveTransformToTargetSkeleton()
FTransform FSkeletonRemapping::RetargetAdditiveTransformToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FTransform & SourceTransform) const inline
Get the specified additive transform retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceTransform Bone transform from the corresponding bone on the source skeleton
Returns
Transform mapped onto the target skeleton
Definition at line 107 of file SkeletonRemapping.h.
References UE::Math::TTransform< T >::GetRotation(), UE::Math::TTransform< T >::GetScale3D(), UE::Math::TTransform< T >::GetTranslation(), RetargetAdditiveRotationToTargetSkeleton(), and RetargetAdditiveTranslationToTargetSkeleton().
RetargetAdditiveTranslationToTargetSkeleton()
FVector FSkeletonRemapping::RetargetAdditiveTranslationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FVector & SourceTranslation) const inline
Get the specified additive translation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceTranslation Bone translation from the corresponding bone on the source skeleton
Returns
Translation mapped onto the target skeleton
Definition at line 123 of file SkeletonRemapping.h.
References FVector, and RetargetingTable.
Referenced by RetargetAdditiveTransformToTargetSkeleton().
RetargetBoneRotationToTargetSkeleton()
FQuat FSkeletonRemapping::RetargetBoneRotationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FQuat & SourceRotation) const inline
Get the specified bone rotation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceRotation Bone rotation from the corresponding bone on the source skeleton
Returns
Rotation mapped onto the target skeleton
Definition at line 92 of file SkeletonRemapping.h.
References RetargetingTable.
Referenced by RetargetBoneTransformToTargetSkeleton().
RetargetBoneTransformToTargetSkeleton()
FTransform FSkeletonRemapping::RetargetBoneTransformToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FTransform & SourceTransform) const inline
Get the specified bone transform retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceTransform Bone transform from the corresponding bone on the source skeleton
Returns
Transform mapped onto the target skeleton
Definition at line 61 of file SkeletonRemapping.h.
References UE::Math::TTransform< T >::GetRotation(), UE::Math::TTransform< T >::GetScale3D(), UE::Math::TTransform< T >::GetTranslation(), RetargetBoneRotationToTargetSkeleton(), and RetargetBoneTranslationToTargetSkeleton().
RetargetBoneTranslationToTargetSkeleton()
FVector FSkeletonRemapping::RetargetBoneTranslationToTargetSkeleton (int32 TargetSkeletonBoneIndex, const FVector & SourceTranslation) const inline
Get the specified bone translation retargeted from the source skeleton onto the target skeleton, corrected for differences between source and target rest poses.
Parameters
TargetSkeletonBoneIndex Skeleton bone index on the target skeleton
SourceTranslation Bone translation from the corresponding bone on the source skeleton
Returns
Translation mapped onto the target skeleton
Definition at line 77 of file SkeletonRemapping.h.
References FVector, and RetargetingTable.
Referenced by RetargetBoneTransformToTargetSkeleton().
UE_DEPRECATED()
FSkeletonRemapping::UE_DEPRECATED (5. 3, "This function is no longer used") inline
Definition at line 151 of file SkeletonRemapping.h.
References UE_DEPRECATED().
Referenced by UE_DEPRECATED().
Field Documentation
RetargetingTable
TArray<TTuple<FQuat, FQuat> > FSkeletonRemapping::RetargetingTable private
Definition at line 181 of file SkeletonRemapping.h.
Referenced by RequiresReferencePoseRetarget(), RetargetAdditiveRotationToTargetSkeleton(), RetargetAdditiveTranslationToTargetSkeleton(), RetargetBoneRotationToTargetSkeleton(), and RetargetBoneTranslationToTargetSkeleton().
SourceSkeleton
TWeakObjectPtr<const USkeleton> FSkeletonRemapping::SourceSkeleton private
Definition at line 171 of file SkeletonRemapping.h.
Referenced by GetSourceSkeleton(), and IsValid().
SourceToTargetBoneIndexes
TArray<int32> FSkeletonRemapping::SourceToTargetBoneIndexes private
Definition at line 175 of file SkeletonRemapping.h.
Referenced by GetTargetSkeletonBoneIndex().
TargetSkeleton
TWeakObjectPtr<const USkeleton> FSkeletonRemapping::TargetSkeleton private
Definition at line 172 of file SkeletonRemapping.h.
Referenced by GetTargetSkeleton(), and IsValid().
TargetToSourceBoneIndexes
TArray<int32> FSkeletonRemapping::TargetToSourceBoneIndexes private
Definition at line 178 of file SkeletonRemapping.h.
Referenced by GetSourceSkeletonBoneIndex().
The documentation for this struct was generated from the following file:
SkeletonRemapping.h