Unreal Engine 5.6 C++ API: FActorIteratorState Class Reference
FActorIteratorState Class Reference
Abstract base class for actor iteration.
#include "EngineUtils.h"
Public Member Functions
FActorIteratorState (const UWorld *InWorld, const TSubclassOf< AActor > InClass)
Default ctor, inits everything.
~FActorIteratorState ()
FORCEINLINE AActor * GetActorChecked () const
Returns the current suitable actor pointed at by the Iterator.
Data Fields
TArray< AActor * > ActorArray
Results from the GetObjectsOfClass query.
FDelegateHandle ActorSpawnedDelegateHandle
Handle to the registered OnActorSpawned delegate.
int32 ConsideredCount
Number of actors that have been considered thus far.
AActor * CurrentActor
Current actor pointed to by actor iterator.
const UWorld * CurrentWorld
Current world we are iterating upon.
UClass * DesiredClass
The class type we are iterating, kept for filtering.
int32 Index
index of the current element in the object array
bool ReachedEnd
Whether we already reached the end.
TArray< AActor * > SpawnedActorArray
Contains any actors spawned during iteration.
Private Member Functions
void OnActorSpawned (AActor *InActor)
Detailed Description
Abstract base class for actor iteration.
Implements all operators and relies on IsActorSuitable to be overridden by derived class. Note that when Playing In Editor, this will find actors only in CurrentWorld.
Definition at line 150 of file EngineUtils.h.
Constructor & Destructor Documentation
FActorIteratorState()
FActorIteratorState::FActorIteratorState (const UWorld * InWorld, const TSubclassOf< AActor > InClass) inline
Default ctor, inits everything.
Definition at line 175 of file EngineUtils.h.
References Actor, ActorArray, ActorSpawnedDelegateHandle, TArray< InElementType, InAllocatorType >::Append(), check, ConsideredCount, TSet< InElementType, KeyFuncs, Allocator >::Contains(), CurrentActor, CurrentWorld, DesiredClass, Garbage, GetObjectsOfClass(), Index, TArray< InElementType, InAllocatorType >::IsEmpty(), IsInGameThread(), TArray< InElementType, InAllocatorType >::Num(), OnActorSpawned(), ReachedEnd, TArray< InElementType, InAllocatorType >::Reserve(), RF_ClassDefaultObject, and Swap.
~FActorIteratorState()
FActorIteratorState::~FActorIteratorState () inline
Definition at line 264 of file EngineUtils.h.
References ActorSpawnedDelegateHandle, and CurrentWorld.
Member Function Documentation
GetActorChecked()
FORCEINLINE AActor * FActorIteratorState::GetActorChecked () const inline
Returns the current suitable actor pointed at by the Iterator.
Returns
Current suitable actor
Definition at line 274 of file EngineUtils.h.
References check, checkf, CurrentActor, FORCEINLINE, and TEXT.
OnActorSpawned()
void FActorIteratorState::OnActorSpawned (AActor * InActor) inline private
Definition at line 282 of file EngineUtils.h.
References CurrentWorld, DesiredClass, and SpawnedActorArray.
Referenced by FActorIteratorState().
Field Documentation
ActorArray
TArray<AActor*> FActorIteratorState::ActorArray
Results from the GetObjectsOfClass query.
Definition at line 156 of file EngineUtils.h.
Referenced by FActorIteratorState().
ActorSpawnedDelegateHandle
FDelegateHandle FActorIteratorState::ActorSpawnedDelegateHandle
Handle to the registered OnActorSpawned delegate.
Definition at line 170 of file EngineUtils.h.
Referenced by FActorIteratorState(), and ~FActorIteratorState().
ConsideredCount
int32 FActorIteratorState::ConsideredCount
Number of actors that have been considered thus far.
Definition at line 162 of file EngineUtils.h.
Referenced by FActorIteratorState().
CurrentActor
AActor* FActorIteratorState::CurrentActor
Current actor pointed to by actor iterator.
Definition at line 164 of file EngineUtils.h.
Referenced by FActorIteratorState(), and GetActorChecked().
CurrentWorld
const UWorld* FActorIteratorState::CurrentWorld
Current world we are iterating upon.
Definition at line 154 of file EngineUtils.h.
Referenced by FActorIteratorState(), ~FActorIteratorState(), and OnActorSpawned().
DesiredClass
UClass* FActorIteratorState::DesiredClass
The class type we are iterating, kept for filtering.
Definition at line 168 of file EngineUtils.h.
Referenced by FActorIteratorState(), and OnActorSpawned().
Index
int32 FActorIteratorState::Index
index of the current element in the object array
Definition at line 158 of file EngineUtils.h.
Referenced by FActorIteratorState().
ReachedEnd
bool FActorIteratorState::ReachedEnd
Whether we already reached the end.
Definition at line 160 of file EngineUtils.h.
Referenced by FActorIteratorState().
SpawnedActorArray
TArray<AActor*> FActorIteratorState::SpawnedActorArray
Contains any actors spawned during iteration.
Definition at line 166 of file EngineUtils.h.
Referenced by OnActorSpawned().
The documentation for this class was generated from the following file:
EngineUtils.h