Unreal Engine 5.6 C++ API: FStateTreePropertyRefExternalHandle Struct Reference
FStateTreePropertyRefExternalHandle Struct Reference
External Handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
#include "StateTreePropertyRef.h"
Public Member Functions
FStateTreePropertyRefExternalHandle (FStateTreePropertyRef InPropertyRef, FStateTreeExecutionContext &InContext)
template<class TRef>
TRef * GetMutablePtr () const
template<class... TRef>
TTuple< TRef *... > GetMutablePtrTuple () const
Protected Attributes
FStateTreePropertyRef PropertyRef
FStateTreeStateHandle RootState = FStateTreeStateHandle::Invalid
TWeakPtr< FStateTreeInstanceStorage > WeakInstanceStorage
TWeakObjectPtr< const UStateTree > WeakStateTree = nullptr
Detailed Description
External Handle allows to wrap-up property reference to make it accessible without having an access to StateTreeExecutionContext.
Useful for capturing property reference in callbacks.
Definition at line 256 of file StateTreePropertyRef.h.
Constructor & Destructor Documentation
FStateTreePropertyRefExternalHandle()
FStateTreePropertyRefExternalHandle::FStateTreePropertyRefExternalHandle (FStateTreePropertyRef InPropertyRef, FStateTreeExecutionContext & InContext) inline
Definition at line 258 of file StateTreePropertyRef.h.
References PropertyRef, RootState, WeakInstanceStorage, and WeakStateTree.
Member Function Documentation
GetMutablePtr()
template<class TRef> TRef * FStateTreePropertyRefExternalHandle::GetMutablePtr () const inline
Returns
pointer to the property if possible, nullptr otherwise.
Definition at line 268 of file StateTreePropertyRef.h.
References GetMutablePtrTuple().
Referenced by TStateTreePropertyRefExternalHandle< TRef >::GetMutablePtr().
GetMutablePtrTuple()
template<class... TRef> TTuple< TRef *... > FStateTreePropertyRefExternalHandle::GetMutablePtrTuple () const inline
Returns
a tuple of pointers of the given types to the property if possible, nullptr otherwise.
Definition at line 275 of file StateTreePropertyRef.h.
References FStateTreeExecutionContext::FindFrame(), UE::StateTree::PropertyRefHelpers::GetMutablePtrTupleToProperty(), PropertyRef, RootState, WeakInstanceStorage, and WeakStateTree.
Referenced by GetMutablePtr(), and TStateTreePropertyRefExternalHandle< TRef >::GetMutablePtrTuple().
Field Documentation
PropertyRef
FStateTreePropertyRef FStateTreePropertyRefExternalHandle::PropertyRef protected
Definition at line 299 of file StateTreePropertyRef.h.
Referenced by FStateTreePropertyRefExternalHandle(), and GetMutablePtrTuple().
RootState
FStateTreeStateHandle FStateTreePropertyRefExternalHandle::RootState = FStateTreeStateHandle::Invalid protected
Definition at line 298 of file StateTreePropertyRef.h.
Referenced by FStateTreePropertyRefExternalHandle(), and GetMutablePtrTuple().
WeakInstanceStorage
TWeakPtr<FStateTreeInstanceStorage> FStateTreePropertyRefExternalHandle::WeakInstanceStorage protected
Definition at line 296 of file StateTreePropertyRef.h.
Referenced by FStateTreePropertyRefExternalHandle(), and GetMutablePtrTuple().
WeakStateTree
TWeakObjectPtr<const UStateTree> FStateTreePropertyRefExternalHandle::WeakStateTree = nullptr protected
Definition at line 297 of file StateTreePropertyRef.h.
Referenced by FStateTreePropertyRefExternalHandle(), and GetMutablePtrTuple().
The documentation for this struct was generated from the following file:
StateTreePropertyRef.h