Unreal Engine 5.6 C++ API: ALODActor Class Reference
ALODActor Class Reference
#include "LODActor.h"
Public Member Functions
void AddInstances (const UStaticMesh *InStaticMesh, const UMaterialInterface *InMaterial, const TArray< FTransform > &InTransforms)
Add instances to this LODActor.
void AddInstances (const UStaticMesh *InStaticMesh, const UMaterialInterface *InMaterial, const TArray< FTransform > &InTransforms, const TArray< FCustomPrimitiveData > &InCustomPrimitiveData)
void AddSubActor (AActor *InActor)
Adds InActor to the SubActors array and set its LODParent to this.
void AddSubActors (const TArray< AActor * > &InActors)
Append the provided actors to the SubActors array and properly setup their LODParent.
virtual void CheckForErrors () override
void CleanSubActorArray ()
Cleans the SubActor array (removes all NULL entries)
void ClearInstances ()
Clear all instances stored in this LODActor.
void DetermineShadowingFlags ()
virtual void EditorApplyMirror (const FVector &MirrorScale, const FVector &PivotLocation) override
virtual void EditorApplyRotation (const FRotator &DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
virtual void EditorApplyScale (const FVector &DeltaScale, const FVector *PivotLocation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
virtual void EditorApplyTranslation (const FVector &DeltaTranslation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
void ForceUnbuilt ()
Force this actor to appear unbuilt (zeros-out key)
virtual FBox GetComponentsBoundingBox (bool bNonColliding=false, bool bIncludeFromChildActors=false) const override
virtual FString GetDetailedInfoInternal () const override
float GetDrawDistance () const
Gets the LOD draw distance.
TArray< UInstancedStaticMeshComponent * > GetInstancedStaticMeshComponents () const
Returns instanced static mesh components that represents the imposters found in this LODActor.
const FName & GetKey () const
Get the key that we use to check if we need to (re)build.
float GetLODDrawDistance () const
float GetLODDrawDistanceWithOverride () const
const uint32 GetNumTrianglesInMergedMesh ()
Returns the number of triangles this LODActor's SubActors contain.
const uint32 GetNumTrianglesInSubActors ()
Returns the number of triangles this LODActor's SubActors contain.
UHLODProxy * GetProxy () const
Get the proxy mesh we use to render.
const UHLODProxyDesc * GetProxyDesc () const
Get the proxy description used to generated this LODActor.
UStaticMeshComponent * GetStaticMeshComponent () const
Returns StaticMeshComponent subobject.
const bool HasAnySubActors () const
Determines whether or not this LODActor has any SubActors.
const bool HasValidLODChildren () const
Returns whether or not this LODActor has valid SubActors and whether or not their contained Primitive Components are linked (LODParentPrimitive) to StaticMeshComponent.
const bool HasValidSubActors () const
Determines whether or not this LODActor has valid SubActors and can be built.
const bool IsBuilt (bool bInForce=false) const
Check to see if this mesh is built.
virtual bool IsLevelBoundsRelevant () const override
virtual bool Modify (bool bAlwaysMarkDirty=true) override
void PauseDitherTransition ()
Forces the mesh into view by setting the MinDrawDistance to zero (this pops the mesh into view, no fading)
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
virtual void PostRegisterAllComponents () override
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
virtual void PreSave (FObjectPreSaveContext ObjectSaveContext) override
void RecalculateDrawingDistance (const float TransitionScreenSize)
Recalculates the drawing distance according to a fixed FOV of 90 and the transition screen size.
const bool RemoveSubActor (AActor *InActor)
Removes InActor from the SubActors array and sets its LODParent to nullptr.
virtual void Serialize (FArchive &Ar) override
void SetDrawDistance (float InDistance)
Sets the LOD draw distance and updates the Static Mesh Component's min drawing distance.
void SetForcedView (const bool InState)
Sets forcing the StaticMeshComponent drawing distance to 0 or LODDrawDistance according to InState.
void SetHiddenFromEditorView (const bool InState, const int32 ForceLODLevel)
Sets the state of whether or not this LODActor is hidden from the Editor view, used for forcing a HLOD to show.
void SetLODParent (UPrimitiveComponent *InLODParent, float InParentDrawDistance, bool bInApplyToImposters)
Set LOD Parent component for all of our components, normally associated with an ALODActor.
void SetStaticMesh (UStaticMesh *InStaticMesh)
Sets StaticMesh and IsPreviewActor to true if InStaticMesh equals nullptr.
void StartDitherTransition ()
Makes the actor tickable and according to r.HLOD.DitherPauseTime sets the MinDrawDistance back to non-zero.
virtual void Tick (float DeltaSeconds) override
void ToggleForceView ()
Toggles forcing the StaticMeshComponent drawing distance to 0 or LODDrawDistance.
bool UpdateProxyDesc ()
Update the proxy description that represent this LODActor.
void UpdateSubActorLODParents ()
Updates the LODParents for the SubActors (and the drawing distance)
UPROPERTY () int32 LODLevel
The hierarchy level of this actor; the first tier of HLOD is level 1, the second tier is level 2 and so on.
UPROPERTY () TArray< TObjectPtr< AActor > > SubActors
UPROPERTY () uint8 CachedNumHLODLevels
bool WasBuiltFromHLODDesc () const
Returns true if this LODActor was constructed from an HLODProxyDesc.
Static Public Member Functions
static const TArray< float > & GetHLODDistanceOverride ()
Returns an array of distances that are used to override individual LOD actors min draw distances.
static bool ShouldUseInstancing (const UStaticMeshComponent *InComponent)
Private Member Functions
GENERATED_UCLASS_BODY () friend class UHLODProxy
UInstancedStaticMeshComponent * GetISMComponent (const FHLODInstancingKey &InstancingKey) const
UStaticMeshComponent * GetLODComponentForActor (const AActor *InActor, bool bFallbackToDefault=true) const
UInstancedStaticMeshComponent * GetOrCreateISMComponent (const FHLODInstancingKey &InstancingKey)
UStaticMeshComponent * GetOrCreateLODComponentForActor (const AActor *InActor)
void RegisterMeshComponents ()
void SetComponentsMinDrawDistance (float InMinDrawDistance, bool bInMarkRenderStateDirty)
void SetupComponent (UStaticMeshComponent *InComponent)
UFUNCTION () 1 void OnSubActorEndPlay(AActor *Actor
void UnregisterMeshComponents ()
void UpdateOverrideTransitionDistance ()
void UpdateRegistrationToMatchMaximumLODLevel ()
UPROPERTY () float LODDrawDistance
what distance do you want this to show up instead of SubActors
UPROPERTY () FName Key
The key used to validate this actor against the proxy.
UPROPERTY () TMap< FHLODInstancingKey
Imposters to be rendered as instanced static meshes.
UPROPERTY () TObjectPtr< UHLODProxy > Proxy
The mesh proxy used to display this LOD.
UPROPERTY () TObjectPtr< UStaticMeshComponent > StaticMeshComponent
Static Private Member Functions
static void OnCVarsChanged ()
static void ParseOverrideDistancesCVar ()
Private Attributes
uint8 bCachedIsBuilt: 1
Cached flag we use to avoid checking the built status of this actor every frame.
uint8 bHasActorTriedToRegisterComponents: 1
uint8 bHasPatchedUpParent: 1
uint8 bNeedsDrawDistanceReset: 1
Flags for forcing a dithering transition.
uint8 bRequiresLODScreenSizeConversion: 1
If true on post load we need to calculate resolution independent Display Factors from the loaded LOD screen sizes.
TObjectPtr< UInstancedStaticMeshComponent > InstancedStaticMeshComponents
double LastIsBuiltTime
Timer we use to avoid checking the built status of this actor every frame.
EEndPlayReason::Type Reason
float ResetDrawDistanceTime
Static Private Attributes
static FAutoConsoleVariableSink CVarSink
static TArray< float > HLODDistances
Friends
class UHLODProxyDesc
Detailed Description
Definition at line 69 of file LODActor.h.
Member Function Documentation
AddInstances() [1/2]
void ALODActor::AddInstances (const UStaticMesh * InStaticMesh, const UMaterialInterface * InMaterial, const TArray< FTransform > & InTransforms)
Add instances to this LODActor.
AddInstances() [2/2]
void ALODActor::AddInstances (const UStaticMesh * InStaticMesh, const UMaterialInterface * InMaterial, const TArray< FTransform > & InTransforms, const TArray< FCustomPrimitiveData > & InCustomPrimitiveData)
AddSubActor()
void ALODActor::AddSubActor (AActor * InActor)
Adds InActor to the SubActors array and set its LODParent to this.
Parameters
InActor - Actor to add
AddSubActors()
void ALODActor::AddSubActors (const TArray< AActor * > & InActors)
Append the provided actors to the SubActors array and properly setup their LODParent.
Parameters
InActors - Array of actors to add
CheckForErrors()
virtual void ALODActor::CheckForErrors () override virtual
CleanSubActorArray()
void ALODActor::CleanSubActorArray ()
Cleans the SubActor array (removes all NULL entries)
ClearInstances()
void ALODActor::ClearInstances ()
Clear all instances stored in this LODActor.
DetermineShadowingFlags()
void ALODActor::DetermineShadowingFlags ()
EditorApplyMirror()
virtual void ALODActor::EditorApplyMirror (const FVector & MirrorScale, const FVector & PivotLocation) override virtual
References FVector.
EditorApplyRotation()
virtual void ALODActor::EditorApplyRotation (const FRotator & DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override virtual
EditorApplyScale()
virtual void ALODActor::EditorApplyScale (const FVector & DeltaScale, const FVector * PivotLocation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override virtual
References FVector.
EditorApplyTranslation()
virtual void ALODActor::EditorApplyTranslation (const FVector & DeltaTranslation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override virtual
References FVector.
ForceUnbuilt()
void ALODActor::ForceUnbuilt ()
Force this actor to appear unbuilt (zeros-out key)
GENERATED_UCLASS_BODY()
ALODActor::GENERATED_UCLASS_BODY () private
GetComponentsBoundingBox()
virtual FBox ALODActor::GetComponentsBoundingBox (bool bNonColliding = false, bool bIncludeFromChildActors = false) const override virtual
GetDetailedInfoInternal()
virtual FString ALODActor::GetDetailedInfoInternal () const override virtual
GetDrawDistance()
float ALODActor::GetDrawDistance () const inline
Gets the LOD draw distance.
Definition at line 141 of file LODActor.h.
GetHLODDistanceOverride()
const TArray< float > & ALODActor::GetHLODDistanceOverride () static
Returns an array of distances that are used to override individual LOD actors min draw distances.
GetInstancedStaticMeshComponents()
TArray< UInstancedStaticMeshComponent * > ALODActor::GetInstancedStaticMeshComponents () const inline
Returns instanced static mesh components that represents the imposters found in this LODActor.
Definition at line 317 of file LODActor.h.
References InstancedStaticMeshComponents.
GetISMComponent()
UInstancedStaticMeshComponent * ALODActor::GetISMComponent (const FHLODInstancingKey & InstancingKey) const private
GetKey()
const FName & ALODActor::GetKey () const inline
Get the key that we use to check if we need to (re)build.
Definition at line 170 of file LODActor.h.
References Key.
GetLODComponentForActor()
UStaticMeshComponent * ALODActor::GetLODComponentForActor (const AActor * InActor, bool bFallbackToDefault = true) const private
GetLODDrawDistance()
float ALODActor::GetLODDrawDistance () const inline
Definition at line 142 of file LODActor.h.
GetLODDrawDistanceWithOverride()
float ALODActor::GetLODDrawDistanceWithOverride () const
GetNumTrianglesInMergedMesh()
const uint32 ALODActor::GetNumTrianglesInMergedMesh ()
Returns the number of triangles this LODActor's SubActors contain.
GetNumTrianglesInSubActors()
const uint32 ALODActor::GetNumTrianglesInSubActors ()
Returns the number of triangles this LODActor's SubActors contain.
GetOrCreateISMComponent()
UInstancedStaticMeshComponent * ALODActor::GetOrCreateISMComponent (const FHLODInstancingKey & InstancingKey) private
GetOrCreateLODComponentForActor()
UStaticMeshComponent * ALODActor::GetOrCreateLODComponentForActor (const AActor * InActor) private
GetProxy()
UHLODProxy * ALODActor::GetProxy () const inline
Get the proxy mesh we use to render.
Definition at line 245 of file LODActor.h.
GetProxyDesc()
const UHLODProxyDesc * ALODActor::GetProxyDesc () const inline
Get the proxy description used to generated this LODActor.
Definition at line 248 of file LODActor.h.
References UHLODProxyDesc.
GetStaticMeshComponent()
UStaticMeshComponent * ALODActor::GetStaticMeshComponent () const inline
Returns StaticMeshComponent subobject.
Definition at line 314 of file LODActor.h.
HasAnySubActors()
const bool ALODActor::HasAnySubActors () const
Determines whether or not this LODActor has any SubActors.
Returns
true if it contains any subactors
HasValidLODChildren()
const bool ALODActor::HasValidLODChildren () const
Returns whether or not this LODActor has valid SubActors and whether or not their contained Primitive Components are linked (LODParentPrimitive) to StaticMeshComponent.
HasValidSubActors()
const bool ALODActor::HasValidSubActors () const
Determines whether or not this LODActor has valid SubActors and can be built.
Returns
true if the subactor(s) contain at least two static mesh components
IsBuilt()
const bool ALODActor::IsBuilt (bool bInForce = false) const
Check to see if this mesh is built.
Parameters
bInForce Whether to force the recalculation of this actor's build flag. If this is false then the cached flag is used an only recalculated every so often.
IsLevelBoundsRelevant()
virtual bool ALODActor::IsLevelBoundsRelevant () const inline override virtual
Definition at line 119 of file LODActor.h.
Modify()
virtual bool ALODActor::Modify (bool bAlwaysMarkDirty = true) override virtual
OnCVarsChanged()
void ALODActor::OnCVarsChanged () static private
ParseOverrideDistancesCVar()
void ALODActor::ParseOverrideDistancesCVar () static private
PauseDitherTransition()
void ALODActor::PauseDitherTransition ()
Forces the mesh into view by setting the MinDrawDistance to zero (this pops the mesh into view, no fading)
PostEditChangeProperty()
virtual void ALODActor::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostLoad()
virtual void ALODActor::PostLoad () override virtual
PostRegisterAllComponents()
virtual void ALODActor::PostRegisterAllComponents () override virtual
PreEditChange()
virtual void ALODActor::PreEditChange (FProperty * PropertyThatWillChange) override virtual
PreSave()
virtual void ALODActor::PreSave (FObjectPreSaveContext ObjectSaveContext) override virtual
References Category, meta, and UPROPERTY().
RecalculateDrawingDistance()
void ALODActor::RecalculateDrawingDistance (const float TransitionScreenSize)
Recalculates the drawing distance according to a fixed FOV of 90 and the transition screen size.
RegisterMeshComponents()
void ALODActor::RegisterMeshComponents () private
RemoveSubActor()
const bool ALODActor::RemoveSubActor (AActor * InActor)
Removes InActor from the SubActors array and sets its LODParent to nullptr.
Parameters
InActor - Actor to remove
Serialize()
virtual void ALODActor::Serialize (FArchive & Ar) override virtual
References Ar.
SetComponentsMinDrawDistance()
void ALODActor::SetComponentsMinDrawDistance (float InMinDrawDistance, bool bInMarkRenderStateDirty) private
SetDrawDistance()
void ALODActor::SetDrawDistance (float InDistance)
Sets the LOD draw distance and updates the Static Mesh Component's min drawing distance.
SetForcedView()
void ALODActor::SetForcedView (const bool InState)
Sets forcing the StaticMeshComponent drawing distance to 0 or LODDrawDistance according to InState.
SetHiddenFromEditorView()
void ALODActor::SetHiddenFromEditorView (const bool InState, const int32 ForceLODLevel)
Sets the state of whether or not this LODActor is hidden from the Editor view, used for forcing a HLOD to show.
SetLODParent()
void ALODActor::SetLODParent (UPrimitiveComponent * InLODParent, float InParentDrawDistance, bool bInApplyToImposters)
Set LOD Parent component for all of our components, normally associated with an ALODActor.
Parameters
InLODParent This component used to compute visibility when hierarchical LOD is enabled.
InParentDrawDistance Updates the MinDrawDistances of the LODParent
bInApplyToImposters Whether this should be applied to imposters instanced static meshes components.
SetStaticMesh()
void ALODActor::SetStaticMesh (UStaticMesh * InStaticMesh)
Sets StaticMesh and IsPreviewActor to true if InStaticMesh equals nullptr.
SetupComponent()
void ALODActor::SetupComponent (UStaticMeshComponent * InComponent) private
ShouldUseInstancing()
bool ALODActor::ShouldUseInstancing (const UStaticMeshComponent * InComponent) static
StartDitherTransition()
void ALODActor::StartDitherTransition ()
Makes the actor tickable and according to r.HLOD.DitherPauseTime sets the MinDrawDistance back to non-zero.
Tick()
virtual void ALODActor::Tick (float DeltaSeconds) override virtual
ToggleForceView()
void ALODActor::ToggleForceView ()
Toggles forcing the StaticMeshComponent drawing distance to 0 or LODDrawDistance.
UFUNCTION()
ALODActor::UFUNCTION () private
UnregisterMeshComponents()
void ALODActor::UnregisterMeshComponents () private
UpdateOverrideTransitionDistance()
void ALODActor::UpdateOverrideTransitionDistance () private
UpdateProxyDesc()
bool ALODActor::UpdateProxyDesc ()
Update the proxy description that represent this LODActor.
Returns
true if the description changed.
UpdateRegistrationToMatchMaximumLODLevel()
void ALODActor::UpdateRegistrationToMatchMaximumLODLevel () private
UpdateSubActorLODParents()
void ALODActor::UpdateSubActorLODParents ()
Updates the LODParents for the SubActors (and the drawing distance)
UPROPERTY() [1/8]
ALODActor::UPROPERTY () private
what distance do you want this to show up instead of SubActors
References Category, and UPROPERTY().
UPROPERTY() [2/8]
ALODActor::UPROPERTY () private
The key used to validate this actor against the proxy.
References Category, Key, and UPROPERTY().
UPROPERTY() [3/8]
ALODActor::UPROPERTY ()
The hierarchy level of this actor; the first tier of HLOD is level 1, the second tier is level 2 and so on.
References Category, and UPROPERTY().
UPROPERTY() [4/8]
ALODActor::UPROPERTY ()
References Category, and UPROPERTY().
UPROPERTY() [5/8]
ALODActor::UPROPERTY () private
Imposters to be rendered as instanced static meshes.
References Transient, and UPROPERTY().
UPROPERTY() [6/8]
ALODActor::UPROPERTY () private
The mesh proxy used to display this LOD.
References Category, and UPROPERTY().
UPROPERTY() [7/8]
ALODActor::UPROPERTY () private
References Category, and UPROPERTY().
Referenced by PreSave(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [8/8]
ALODActor::UPROPERTY ()
References UPROPERTY().
WasBuiltFromHLODDesc()
bool ALODActor::WasBuiltFromHLODDesc () const inline
Returns true if this LODActor was constructed from an HLODProxyDesc.
Definition at line 257 of file LODActor.h.
Friends And Related Symbol Documentation
UHLODProxyDesc
friend class UHLODProxyDesc friend
Definition at line 74 of file LODActor.h.
References UHLODProxyDesc.
Referenced by GetProxyDesc(), and UHLODProxyDesc.
Field Documentation
bCachedIsBuilt
uint8 ALODActor::bCachedIsBuilt mutable private
Cached flag we use to avoid checking the built status of this actor every frame.
Definition at line 376 of file LODActor.h.
bHasActorTriedToRegisterComponents
uint8 ALODActor::bHasActorTriedToRegisterComponents private
Definition at line 360 of file LODActor.h.
bHasPatchedUpParent
uint8 ALODActor::bHasPatchedUpParent private
Definition at line 363 of file LODActor.h.
bNeedsDrawDistanceReset
uint8 ALODActor::bNeedsDrawDistanceReset private
Flags for forcing a dithering transition.
Definition at line 372 of file LODActor.h.
bRequiresLODScreenSizeConversion
uint8 ALODActor::bRequiresLODScreenSizeConversion private
If true on post load we need to calculate resolution independent Display Factors from the loaded LOD screen sizes.
Definition at line 369 of file LODActor.h.
CVarSink
FAutoConsoleVariableSink ALODActor::CVarSink static private
Definition at line 385 of file LODActor.h.
HLODDistances
TArray<float> ALODActor::HLODDistances static private
Definition at line 326 of file LODActor.h.
InstancedStaticMeshComponents
TObjectPtr<UInstancedStaticMeshComponent> ALODActor::InstancedStaticMeshComponents private
Definition at line 83 of file LODActor.h.
Referenced by GetInstancedStaticMeshComponents().
LastIsBuiltTime
double ALODActor::LastIsBuiltTime mutable private
Timer we use to avoid checking the built status of this actor every frame.
Definition at line 379 of file LODActor.h.
Reason
EEndPlayReason::Type ALODActor::Reason private
Definition at line 343 of file LODActor.h.
ResetDrawDistanceTime
float ALODActor::ResetDrawDistanceTime private
Definition at line 382 of file LODActor.h.
The documentation for this class was generated from the following file:
LODActor.h