Unreal Engine 5.6 C++ API: UE::FWindowsSystemWideMutex Class Reference
UE::FWindowsSystemWideMutex Class Reference final
A system-wide mutex for Windows.
#include "WindowsPlatformMutex.h"
Public Member Functions
FWindowsSystemWideMutex (const FString &InName, FTimespan InTimeout=FTimespan::Zero())
Construct a named, system-wide mutex and attempt to get access/ownership of it.
FWindowsSystemWideMutex (const FWindowsSystemWideMutex &)=delete
~FWindowsSystemWideMutex ()
Destructor releases system-wide mutex if it is currently owned.
bool IsValid () const
Does the calling thread have ownership of the system-wide mutex?
FWindowsSystemWideMutex & operator= (const FWindowsSystemWideMutex &)=delete
void Release ()
Releases system-wide mutex if it is currently owned.
Private Attributes
Windows::HANDLE Mutex
Detailed Description
A system-wide mutex for Windows.
Uses a named mutex.
Definition at line 125 of file WindowsPlatformMutex.h.
Constructor & Destructor Documentation
FWindowsSystemWideMutex() [1/2]
UE::FWindowsSystemWideMutex::FWindowsSystemWideMutex (const FWindowsSystemWideMutex &) delete
References FWindowsSystemWideMutex().
Referenced by FWindowsSystemWideMutex(), and operator=().
FWindowsSystemWideMutex() [2/2]
UE::FWindowsSystemWideMutex::FWindowsSystemWideMutex (const FString & InName, FTimespan InTimeout = FTimespan::Zero()) explicit
Construct a named, system-wide mutex and attempt to get access/ownership of it.
References InName, and FTimespan::Zero().
~FWindowsSystemWideMutex()
UE::FWindowsSystemWideMutex::~FWindowsSystemWideMutex ()
Destructor releases system-wide mutex if it is currently owned.
Member Function Documentation
IsValid()
bool UE::FWindowsSystemWideMutex::IsValid () const
Does the calling thread have ownership of the system-wide mutex?
Returns
True if obtained. WARNING: Returns true for an owned but previously abandoned locks so shared resources can be in undetermined states. You must handle shared data robustly.
operator=()
FWindowsSystemWideMutex & UE::FWindowsSystemWideMutex::operator= (const FWindowsSystemWideMutex &) delete
References FWindowsSystemWideMutex().
Release()
void UE::FWindowsSystemWideMutex::Release ()
Releases system-wide mutex if it is currently owned.
Field Documentation
Mutex
Windows::HANDLE UE::FWindowsSystemWideMutex::Mutex private
Definition at line 148 of file WindowsPlatformMutex.h.
The documentation for this class was generated from the following file:
WindowsPlatformMutex.h