Unreal Engine 5.6 C++ API: Metasound::Frontend Namespace Reference
Metasound::Frontend Namespace Reference
Namespaces
namespace AssetTags
namespace DisplayStyle
namespace DocumentTransform
namespace MetasoundDataTypeRegistrationPrivate
namespace NodeClassRegistryKey
namespace NodeRegistrationPrivate
namespace SourceInterface
namespace SourceInterfaceV1_0
namespace SourceOneShotInterface
namespace SourceStartTimeInterface
Data Structures
class FAccessPoint
FAccessPoint acts as a lifecycle tracker for the TAccessPtrs it creates.
struct FAccessToken
The access token mirrors the lifespan of a object in a non-intrusive manner.
class FAnalyzerAddress
struct FAnalyzerOutput
class FAudioAnalyzerNodeTemplate
class FAutoUpdateRootGraph
Automatically updates all nodes and respective dependencies in graph where newer versions exist in the loaded MetaSound Class Node Registry.
class FClassAccessPtr
class FClassIDGenerator
struct FClassInterfaceUpdates
Provides list of interface members that have been added or removed when querying if a node's class has been updated.
struct FConnectability
class FConstClassAccessPtr
struct FConstDocumentAccess
class FConstDocumentAccessPtr
class FConstGraphClassAccessPtr
class FConstNodeAccessPtr
struct FConverterNodeClassInfo
struct FConverterNodeClassRegistryKey
struct FConverterNodeClassRegistryValue
struct FCreateAnalyzerParams
struct FDataTypeRegistryInfo
FDataTypeRegsitryInfo contains runtime inspectable behavior of a registered MetaSound data type.
struct FDocumentAccess
class FDocumentAccessPtr
class FDocumentIDGenerator
struct FDocumentModifyDelegates
struct FDocumentMutatePageArgs
struct FEdgeModifyDelegates
class FGraphAnalyzer
class FGraphAnalyzerAddress
class FGraphBuilder
FGraphBuilder builds a FFrontendGraph from a FMetasoundDocument or FMetasoundFrontendClass.
class FGraphClassAccessPtr
struct FGraphClassRegistryKey
class FGraphLinter
class FInputNodeTemplate
class FInterfaceBindingRegistryEntry
struct FInterfaceModifyDelegates
class FInterfaceRegistryTransaction
class FMetasoundAnalyzerView
struct FMetaSoundAssetClassInfo
At runtime, contains a minimal set of information needed to further query additional class data from the Node Class Registries.
struct FMetaSoundAssetRegistrationOptions
struct FMetaSoundClassInfo
class FMetasoundGraphAnalyzerView
struct FModifyInterfaceOptions
class FModifyRootGraphInterfaces
Adds or swaps document members (inputs, outputs) and removing any document members where necessary and adding those missing.
struct FNamedEdge
class FNodeAccessPtr
struct FNodeClassInfo
FNodeClassInfo contains a minimal set of information needed to find and query node classes.
struct FNodeClassRegistryKey
class FNodeClassRegistryTransaction
struct FNodeModifyDelegates
class FNodeTemplateBase
struct FPageModifyDelegates
class FRebuildPresetRootGraph
Completely rebuilds the graph connecting a preset's inputs to the reference document's root graph.
class FRenameRootGraphClass
Sets the document's graph class, optionally updating the namespace and variant.
class FRerouteNodeTemplate
class FUpdateRootGraphInterface
class FVertexAnalyzerAudioBuffer
class FVertexAnalyzerBase
class FVertexAnalyzerEnvelopeFollower
class FVertexAnalyzerForwardBool
class FVertexAnalyzerForwardFloat
class FVertexAnalyzerForwardInt
class FVertexAnalyzerForwardString
class FVertexAnalyzerForwardTime
class FVertexAnalyzerTriggerDensity
class FVertexAnalyzerTriggerToTime
class IBoundAnalyzerOutput
class IDataTypeRegistry
class IDataTypeRegistryEntry
Registry entry interface for a MetaSound data type.
class IDocumentAccessor
IDocumentAccessor describes an interface for various I*Controllers to interact with each other without exposing that interface publicly or requiring friendship between various controller implementation classes.
class IDocumentBuilderRegistry
class IDocumentBuilderTransactionListener
class IDocumentCache
Interface for querying cached document dependencies.
class IDocumentController
class IDocumentGraphEdgeCache
Interface for querying cached document edges.
class IDocumentGraphInterfaceCache
Interface for querying cached document interface.
class IDocumentGraphNodeCache
Interface for querying cached document nodes.
class IDocumentTransform
Interface for transforms applied to documents.
struct IEnumDataTypeInterface
Interface for metadata of a registered MetaSound enum type.
class IGraphController
class IGraphTransform
Interface for transforms applied to a graph.
class IInputController
class IInterfaceBindingRegistry
class IInterfaceRegistry
class IInterfaceRegistryEntry
class IMetaSoundAssetManager
class IMetaSoundDocumentBuilderRegistry
class INodeClassRegistry
Singleton registry for all types and nodes.
class INodeClassRegistryEntry
INodeClassRegistryEntry declares the interface for a node registry entry.
class INodeController
class INodeTemplate
Base interface for a node template, which acts in place of frontend node class and respective instance(s).
class INodeTemplateRegistry
class INodeTemplateTransform
class INodeTransform
Interface for transforming a node.
class IOutputController
class ISearchEngine
Interface for frontend search engine.
class IVariableController
class IVertexAnalyzer
class IVertexAnalyzerFactory
class IVertexAnalyzerRegistry
class TAccessPtr
TAccessPtr.
class TBoundAnalyzerOutput
struct TEnableVariables
Allow or disallow types to be registered as MetaSound Variables.
struct TMetasoundDataTypeRegistration
Registration info for a data type.
struct TVariablesSupport
Determine if data type supports necessary operations required of all MetaSound variable types.
class TVertexAnalyzerFactory
class TVertexAnalyzerForwardValue
Typedefs
using FClassInputAccessPtr = TAccessPtr<FMetasoundFrontendClassInput>
using FClassOutputAccessPtr = TAccessPtr<FMetasoundFrontendClassOutput>
using FConstClassAndNodeFunctionRef = TFunctionRef<void(const FMetasoundFrontendClass&, const FMetasoundFrontendNode&)>
using FConstClassInputAccessPtr = TAccessPtr<const FMetasoundFrontendClassInput>
using FConstClassOutputAccessPtr = TAccessPtr<const FMetasoundFrontendClassOutput>
using FConstDocumentHandle = TSharedRef<const IDocumentController>
using FConstGraphAccessPtr = TAccessPtr<const FMetasoundFrontendGraph>
using FConstGraphHandle = TSharedRef<const IGraphController>
using FConstInputHandle = TSharedRef<const IInputController>
using FConstNodeHandle = TSharedRef<const INodeController>
using FConstOutputHandle = TSharedRef<const IOutputController>
using FConstVariableAccessPtr = TAccessPtr<const FMetasoundFrontendVariable>
using FConstVariableHandle = TSharedRef<const IVariableController>
using FConstVertexAccessPtr = TAccessPtr<const FMetasoundFrontendVertex>
using FConverterNodeClassRegistryValue = FConverterNodeClassRegistryValue
using FConverterNodeInfo = FConverterNodeClassInfo
using FConverterNodeRegistryKey = FConverterNodeClassRegistryKey
using FDocumentHandle = TSharedRef<IDocumentController>
using FFinalizeNodeFunctionRef = TFunctionRef<void(FMetasoundFrontendNode&, const Metasound::Frontend::FNodeRegistryKey&)>
using FForEachLiteralFunctionRef = TFunctionRef<void(const FName& InDataTypeName, const FMetasoundFrontendLiteral&)>
Signature of function called for each found literal.
using FGraphAccessPtr = TAccessPtr<FMetasoundFrontendGraph>
using FGraphHandle = TSharedRef<IGraphController>
using FGraphRegistryKey = FGraphClassRegistryKey
using FInputHandle = TSharedRef<IInputController>
using FInterfaceRegistryKey = FString
using FIterateMetasoundFrontendClassFunction = TFunctionRef<void(const FMetasoundFrontendClass&)>
using FLiteralAssignmentFunction = void(*)(const FOperatorSettings& InOperatorSettings, const FLiteral& InLiteral, const FAnyDataReference& OutDataRef)
using FNodeHandle = TSharedRef<INodeController>
using FNodeRegistryKey = FNodeClassRegistryKey
using FNodeRegistryTransaction = FNodeClassRegistryTransaction
using FNodeVertexDataReferenceMap = TMap<FGuid, FDataReferenceCollection>
using FOutputHandle = TSharedRef<IOutputController>
using FRegistryTransactionID = int32
using FVariableAccessPtr = TAccessPtr<FMetasoundFrontendVariable>
using FVariableHandle = TSharedRef<IVariableController>
using FVertexAccessPtr = TAccessPtr<FMetasoundFrontendVertex>
using IParameterAssignmentFunction = TUniqueFunction<void(const void*,void*)>
Enumerations
enum class EInvalidEdgeReason : uint8 {
None = 0 , MismatchedAccessType , MismatchedDataType , MissingInput ,
MissingOutput , COUNT
}
Functions
template<typename ToAccessPtrType, typename FromAccessPtrType>
ToAccessPtrType ConstCastAccessPtr (const FromAccessPtrType &InAccessPtr)
METASOUNDFRONTEND_API FName ConvertParameterToDataType (EAudioParameterType InParameterType)
METASOUNDFRONTEND_API FLiteral ConvertParameterToLiteral (const FAudioParameter &InValue)
METASOUNDFRONTEND_API FLiteral ConvertParameterToLiteral (FAudioParameter &&InValue)
METASOUNDFRONTEND_API EMetasoundFrontendVertexAccessType CoreVertexAccessTypeToFrontendVertexAccessType (Metasound::EVertexAccessType InAccessType)
METASOUNDFRONTEND_API void CreateDefaults (const FOperatorSettings &InOperatorSettings, FInputVertexInterfaceData &OutVertexData)
Create data references for all inputs on the FInputVertexInterfaceData using the default literals which live on the FInputDataVertexes.
METASOUNDFRONTEND_API void CreateDefaultsIfNotBound (const FOperatorSettings &InOperatorSettings, FInputVertexInterfaceData &OutVertexData)
Create data references for all inputs on the FInputVertexInterfaceData which do not already have a data reference bound.
FVertexInterface CreateDefaultVertexInterfaceFromClass (const FMetasoundFrontendClass &InNodeClass, const FProxyDataCache *InProxyDataCache=nullptr)
FVertexInterface CreateDefaultVertexInterfaceFromClassNoProxy (const FMetasoundFrontendClass &InNodeClass)
METASOUNDFRONTEND_API FGuid CreateLocallyUniqueId ()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentPageAdded, const FDocumentMutatePageArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentPageSet, const FDocumentMutatePageArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentRemovingPage, const FDocumentMutatePageArgs &)
constexpr FGuid DefaultPageID (0, 0, 0, 0)
METASOUNDFRONTEND_API const FMetasoundFrontendInterface * FindMostSimilarInterfaceSupportingEnvironment (const FMetasoundFrontendDocument &InDocument, const TArray< FMetasoundFrontendInterface > &InCandidateInterfaces)
METASOUNDFRONTEND_API const FMetasoundFrontendInterface * FindMostSimilarInterfaceSupportingEnvironment (const FMetasoundFrontendGraphClass &InRootGraph, const TArray< FMetasoundFrontendClass > &InDependencies, const TArray< FMetasoundFrontendGraphClass > &InSubgraphs, const TArray< FMetasoundFrontendInterface > &InCandidateInterfaces)
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendClass &InClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendClass.
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendClassInterface &InClassInterface, FForEachLiteralFunctionRef OnLiteral)
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendDocument &InDoc, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendDocument.
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendDocument &InDoc, FForEachLiteralFunctionRef OnLiteral, const FGuid &InPageID)
Execute the provided function for each literal on a FMetasoundFrontendDocument filtered by the given PageID.
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendGraphClass &InGraphClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass.
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendGraphClass &InGraphClass, FForEachLiteralFunctionRef OnLiteral, const FGuid &InPageID)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass filtered by the given PageID.
METASOUNDFRONTEND_API void ForEachLiteral (const FMetasoundFrontendNode &InNode, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendNode.
METASOUNDFRONTEND_API EVertexAccessType FrontendVertexAccessTypeToCoreVertexAccessType (EMetasoundFrontendVertexAccessType InAccessType)
template<typename NodeType>
FMetasoundFrontendClass GenerateClass ()
Generates a new FMetasoundFrontendClass from a NodeType.
METASOUNDFRONTEND_API FMetasoundFrontendClass GenerateClass (const FNodeClassMetadata &InNodeMetadata, EMetasoundFrontendClassType ClassType=EMetasoundFrontendClassType::External)
Generates a new FMetasoundFrontendClass from Node Metadata.
template<typename NodeType>
FMetasoundFrontendClass GenerateClass (const FNodeInitData &InNodeInitData)
Generates a new FMetasoundFrontendClass from Node init data.
METASOUNDFRONTEND_API FMetasoundFrontendClass GenerateClass (const Metasound::Frontend::FNodeRegistryKey &InKey)
Generates a new FMetasoundFrontendClass from node lookup info.
METASOUNDFRONTEND_API TRange< float > GetBlockRateClampRange ()
METASOUNDFRONTEND_API float GetBlockRateOverride ()
METASOUNDFRONTEND_API FConsoleVariableMulticastDelegate & GetBlockRateOverrideChangedDelegate ()
METASOUNDFRONTEND_API FInterfaceRegistryKey GetInterfaceRegistryKey (const FMetasoundFrontendInterface &InInterface)
METASOUNDFRONTEND_API FInterfaceRegistryKey GetInterfaceRegistryKey (const FMetasoundFrontendVersion &InInterfaceVersion)
METASOUNDFRONTEND_API EMetasoundFrontendLiteralType GetMetasoundFrontendLiteralType (ELiteralType InLiteralType)
METASOUNDFRONTEND_API ELiteralType GetMetasoundLiteralType (EMetasoundFrontendLiteralType InLiteralType)
METASOUNDFRONTEND_API TRange< int32 > GetSampleRateClampRange ()
METASOUNDFRONTEND_API int32 GetSampleRateOverride ()
METASOUNDFRONTEND_API FConsoleVariableMulticastDelegate & GetSampleRateOverrideChangedDelegate ()
METASOUNDFRONTEND_API bool ImportJSONAssetToMetasound (const FString &InPath, FMetasoundFrontendDocument &OutMetasoundDocument)
METASOUNDFRONTEND_API bool ImportJSONToMetasound (const FString &InJSON, FMetasoundFrontendDocument &OutMetasoundDocument)
METASOUNDFRONTEND_API int32 InputOutputDifferenceCount (const FMetasoundFrontendClassInterface &InClass, const FMetasoundFrontendInterface &InInterface)
METASOUNDFRONTEND_API int32 InputOutputDifferenceCount (const FMetasoundFrontendInterface &InInterfaceA, const FMetasoundFrontendInterface &InInterfaceB)
METASOUNDFRONTEND_API bool IsEqualInterface (const FMetasoundFrontendInterface &InInputInterface, const FMetasoundFrontendInterface &InTargetInterface)
METASOUNDFRONTEND_API bool IsEquivalentInterface (const FMetasoundFrontendInterface &InInputInterface, const FMetasoundFrontendInterface &InTargetInterface)
METASOUNDFRONTEND_API bool IsSubsetOfClassInterface (const FMetasoundFrontendInterface &InSubsetInterface, const FMetasoundFrontendClassInterface &InSupersetClassInterface)
METASOUNDFRONTEND_API bool IsSubsetOfInterface (const FMetasoundFrontendInterface &InSubsetInterface, const FMetasoundFrontendInterface &InSupersetInterface)
METASOUNDFRONTEND_API bool IsValidInterfaceRegistryKey (const FInterfaceRegistryKey &InKey)
METASOUNDFRONTEND_API FString LexToString (const EInvalidEdgeReason &InReason)
template<typename AccessPtrType, typename Type>
AccessPtrType MakeAccessPtr (const FAccessPoint &InAccessPoint, Type &InRef)
template<typename ArrayType>
bool RegisterArrayNodes ()
Registers all available array nodes which can be instantiated for the given ArrayType.
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void>
bool RegisterDataType ()
Registers a data type with the MetaSound Frontend.
template<typename TNodeType, typename ConfigurationType = void>
bool RegisterNode ()
template<typename TNodeType, typename ConfigurationType = void>
bool RegisterNode (const FNodeClassMetadata &InMetadata)
void RegisterNodeTemplate (TUniquePtr< INodeTemplate > &&InTemplate)
METASOUNDFRONTEND_API bool StringToClassType (const FString &InString, EMetasoundFrontendClassType &OutClassType)
UE_DEPRECATED (5.5, "Reroute input recursion is now privately implemented in the reroute template node class. Use template registry to query reroute node input/output attributes") METASOUNDFRONTEND_API void FindReroutedInputs(FConstInputHandle InHandleToCheck
UE_DEPRECATED (5.5, "Reroute output recursion is now privately implemented in the reroute template node class. Use template registry to query reroute node input/output attributes") METASOUNDFRONTEND_API FConstOutputHandle FindReroutedOutput(FConstOutputHandle InOutputHandle)
UE_DEPRECATED (5.6, "All interface functionality is in the MetaSoundFrontendDocumentBuilder API") METASOUNDFRONTEND_API bool DeclaredInterfaceVersionsMatch(const FMetasoundFrontendDocument &InDocumentA
UE_DEPRECATED (5.6, "Use InputOutputDifferenceCount which accepts a FMetasoundFrontendClassInterface instead") METASOUNDFRONTEND_API int32 InputOutputDifferenceCount(const FMetasoundFrontendClass &InClass
UE_DEPRECATED (5.6, "Use IsSubsetOfClassInterface instead") METASOUNDFRONTEND_API bool IsSubsetOfClass(const FMetasoundFrontendInterface &InSubsetInterface
template<typename TNodeType>
bool UnregisterNode ()
void UnregisterNodeTemplate (const FMetasoundFrontendClassName &InClassName, const FMetasoundFrontendVersionNumber &InTemplateVersion)
Variables
constexpr TCHAR DefaultPageName [] = TEXT("Default")
TFunctionRef< void(FConstInputHandle)> Func
const FMetasoundFrontendDocument & InDocumentB
const FMetasoundFrontendInterface & InInterface
TArray< FConstInputHandle > & InOutInputHandles
const FMetasoundFrontendClass & InSupersetClass
METASOUNDFRONTEND_API int32 MetaSoundEnableCookDeterministicIDGeneration
template<typename Type>
Type TAccessPtr< Type >::FallbackObject = Type()
Typedef Documentation
FClassInputAccessPtr
using Metasound::Frontend::FClassInputAccessPtr = TAccessPtr<FMetasoundFrontendClassInput>
Definition at line 27 of file MetasoundFrontendDocumentAccessPtr.h.
FClassOutputAccessPtr
using Metasound::Frontend::FClassOutputAccessPtr = TAccessPtr<FMetasoundFrontendClassOutput>
Definition at line 29 of file MetasoundFrontendDocumentAccessPtr.h.
FConstClassAndNodeFunctionRef
using Metasound::Frontend::FConstClassAndNodeFunctionRef = TFunctionRef<void(const FMetasoundFrontendClass&, const FMetasoundFrontendNode&)>
Definition at line 30 of file MetasoundFrontendDocumentBuilder.h.
FConstClassInputAccessPtr
using Metasound::Frontend::FConstClassInputAccessPtr = TAccessPtr<const FMetasoundFrontendClassInput>
Definition at line 28 of file MetasoundFrontendDocumentAccessPtr.h.
FConstClassOutputAccessPtr
using Metasound::Frontend::FConstClassOutputAccessPtr = TAccessPtr<const FMetasoundFrontendClassOutput>
Definition at line 30 of file MetasoundFrontendDocumentAccessPtr.h.
FConstDocumentHandle
using Metasound::Frontend::FConstDocumentHandle = TSharedRef<const IDocumentController>
Definition at line 73 of file MetasoundFrontendController.h.
FConstGraphAccessPtr
using Metasound::Frontend::FConstGraphAccessPtr = TAccessPtr<const FMetasoundFrontendGraph>
Definition at line 68 of file MetasoundFrontendDocumentAccessPtr.h.
FConstGraphHandle
using Metasound::Frontend::FConstGraphHandle = TSharedRef<const IGraphController>
Definition at line 71 of file MetasoundFrontendController.h.
FConstInputHandle
using Metasound::Frontend::FConstInputHandle = TSharedRef<const IInputController>
Definition at line 63 of file MetasoundFrontendController.h.
FConstNodeHandle
typedef TSharedRef< const INodeController > Metasound::Frontend::FConstNodeHandle = TSharedRef<const INodeController>
Definition at line 69 of file MetasoundFrontendController.h.
FConstOutputHandle
using Metasound::Frontend::FConstOutputHandle = TSharedRef<const IOutputController>
Definition at line 65 of file MetasoundFrontendController.h.
FConstVariableAccessPtr
using Metasound::Frontend::FConstVariableAccessPtr = TAccessPtr<const FMetasoundFrontendVariable>
Definition at line 32 of file MetasoundFrontendDocumentAccessPtr.h.
FConstVariableHandle
using Metasound::Frontend::FConstVariableHandle = TSharedRef<const IVariableController>
Definition at line 67 of file MetasoundFrontendController.h.
FConstVertexAccessPtr
using Metasound::Frontend::FConstVertexAccessPtr = TAccessPtr<const FMetasoundFrontendVertex>
Definition at line 26 of file MetasoundFrontendDocumentAccessPtr.h.
FConverterNodeClassRegistryValue
using Metasound::Frontend::FConverterNodeClassRegistryValue = FConverterNodeClassRegistryValue
Definition at line 162 of file MetasoundFrontendNodeClassRegistry.h.
FConverterNodeInfo
using Metasound::Frontend::FConverterNodeInfo = FConverterNodeClassInfo
Definition at line 155 of file MetasoundFrontendNodeClassRegistry.h.
FConverterNodeRegistryKey
using Metasound::Frontend::FConverterNodeRegistryKey = FConverterNodeClassRegistryKey
Definition at line 137 of file MetasoundFrontendNodeClassRegistry.h.
FDocumentHandle
using Metasound::Frontend::FDocumentHandle = TSharedRef<IDocumentController>
Definition at line 72 of file MetasoundFrontendController.h.
FFinalizeNodeFunctionRef
using Metasound::Frontend::FFinalizeNodeFunctionRef = TFunctionRef<void(FMetasoundFrontendNode&, const Metasound::Frontend::FNodeRegistryKey&)>
Definition at line 31 of file MetasoundFrontendDocumentBuilder.h.
FForEachLiteralFunctionRef
using Metasound::Frontend::FForEachLiteralFunctionRef = TFunctionRef<void(const FName& InDataTypeName, const FMetasoundFrontendLiteral&)>
Signature of function called for each found literal.
Definition at line 2076 of file MetasoundFrontendDocument.h.
FGraphAccessPtr
using Metasound::Frontend::FGraphAccessPtr = TAccessPtr<FMetasoundFrontendGraph>
Definition at line 67 of file MetasoundFrontendDocumentAccessPtr.h.
FGraphHandle
using Metasound::Frontend::FGraphHandle = TSharedRef<IGraphController>
Definition at line 70 of file MetasoundFrontendController.h.
FGraphRegistryKey
using Metasound::Frontend::FGraphRegistryKey = FGraphClassRegistryKey
Definition at line 151 of file MetasoundFrontendRegistryKey.h.
FInputHandle
using Metasound::Frontend::FInputHandle = TSharedRef<IInputController>
Definition at line 62 of file MetasoundFrontendController.h.
FInterfaceRegistryKey
using Metasound::Frontend::FInterfaceRegistryKey = FString
Definition at line 13 of file MetasoundFrontendInterfaceRegistry.h.
FIterateMetasoundFrontendClassFunction
using Metasound::Frontend::FIterateMetasoundFrontendClassFunction = TFunctionRef<void(const FMetasoundFrontendClass&)>
Definition at line 25 of file MetasoundFrontendNodeClassRegistry.h.
FLiteralAssignmentFunction
using Metasound::Frontend::FLiteralAssignmentFunction = void(*)(const FOperatorSettings& InOperatorSettings, const FLiteral& InLiteral, const FAnyDataReference& OutDataRef)
Definition at line 27 of file MetasoundFrontendDataTypeRegistry.h.
FNodeHandle
using Metasound::Frontend::FNodeHandle = TSharedRef<INodeController>
Definition at line 68 of file MetasoundFrontendController.h.
FNodeRegistryKey
using Metasound::Frontend::FNodeRegistryKey = FNodeClassRegistryKey
Definition at line 126 of file MetasoundFrontendRegistryKey.h.
FNodeRegistryTransaction
using Metasound::Frontend::FNodeRegistryTransaction = FNodeClassRegistryTransaction
Definition at line 220 of file MetasoundFrontendNodeClassRegistry.h.
FNodeVertexDataReferenceMap
using Metasound::Frontend::FNodeVertexDataReferenceMap = TMap<FGuid, FDataReferenceCollection>
Definition at line 18 of file MetasoundFrontendGraphAnalyzer.h.
FOutputHandle
using Metasound::Frontend::FOutputHandle = TSharedRef<IOutputController>
Definition at line 64 of file MetasoundFrontendController.h.
FRegistryTransactionID
using Metasound::Frontend::FRegistryTransactionID = int32
Definition at line 14 of file MetasoundFrontendInterfaceRegistry.h.
FVariableAccessPtr
using Metasound::Frontend::FVariableAccessPtr = TAccessPtr<FMetasoundFrontendVariable>
Definition at line 31 of file MetasoundFrontendDocumentAccessPtr.h.
FVariableHandle
using Metasound::Frontend::FVariableHandle = TSharedRef<IVariableController>
Definition at line 66 of file MetasoundFrontendController.h.
FVertexAccessPtr
using Metasound::Frontend::FVertexAccessPtr = TAccessPtr<FMetasoundFrontendVertex>
Definition at line 25 of file MetasoundFrontendDocumentAccessPtr.h.
IParameterAssignmentFunction
using Metasound::Frontend::IParameterAssignmentFunction = TUniqueFunction<void(const void*,void*)>
Definition at line 24 of file MetasoundFrontendDataTypeRegistry.h.
Enumeration Type Documentation
EInvalidEdgeReason
enum class Metasound::Frontend::EInvalidEdgeReason : uint8 strong
Enumerator
None
MismatchedAccessType
MismatchedDataType
MissingInput
MissingOutput
COUNT
Definition at line 33 of file MetasoundFrontendDocumentBuilder.h.
Function Documentation
ConstCastAccessPtr()
template<typename ToAccessPtrType, typename FromAccessPtrType> ToAccessPtrType Metasound::Frontend::ConstCastAccessPtr (const FromAccessPtrType & InAccessPtr)
Definition at line 233 of file MetasoundAccessPtr.h.
ConvertParameterToDataType()
METASOUNDFRONTEND_API FName Metasound::Frontend::ConvertParameterToDataType (EAudioParameterType InParameterType)
ConvertParameterToLiteral() [1/2]
METASOUNDFRONTEND_API FLiteral Metasound::Frontend::ConvertParameterToLiteral (const FAudioParameter & InValue)
ConvertParameterToLiteral() [2/2]
METASOUNDFRONTEND_API FLiteral Metasound::Frontend::ConvertParameterToLiteral (FAudioParameter && InValue)
CoreVertexAccessTypeToFrontendVertexAccessType()
METASOUNDFRONTEND_API EMetasoundFrontendVertexAccessType Metasound::Frontend::CoreVertexAccessTypeToFrontendVertexAccessType (Metasound::EVertexAccessType InAccessType)
CreateDefaults()
METASOUNDFRONTEND_API void Metasound::Frontend::CreateDefaults (const FOperatorSettings & InOperatorSettings, FInputVertexInterfaceData & OutVertexData)
Create data references for all inputs on the FInputVertexInterfaceData using the default literals which live on the FInputDataVertexes.
If the vertex has access type EVertexAccessType::Reference, a writable data reference will be set, otherwise a value data reference will be set.
References CreateDefaults().
Referenced by CreateDefaults().
CreateDefaultsIfNotBound()
METASOUNDFRONTEND_API void Metasound::Frontend::CreateDefaultsIfNotBound (const FOperatorSettings & InOperatorSettings, FInputVertexInterfaceData & OutVertexData)
Create data references for all inputs on the FInputVertexInterfaceData which do not already have a data reference bound.
Defaults are created using the default literals which live on the FInputDataVertexes.
If the vertex has access type EVertexAccessType::Reference, a writable data reference will be set, otherwise a value data reference will be set.
References CreateDefaultsIfNotBound().
Referenced by CreateDefaultsIfNotBound().
CreateDefaultVertexInterfaceFromClass()
FVertexInterface Metasound::Frontend::CreateDefaultVertexInterfaceFromClass (const FMetasoundFrontendClass & InNodeClass, const FProxyDataCache * InProxyDataCache = nullptr)
CreateDefaultVertexInterfaceFromClassNoProxy()
FVertexInterface Metasound::Frontend::CreateDefaultVertexInterfaceFromClassNoProxy (const FMetasoundFrontendClass & InNodeClass)
CreateLocallyUniqueId()
METASOUNDFRONTEND_API FGuid Metasound::Frontend::CreateLocallyUniqueId ()
Referenced by Metasound::Frontend::FGraphBuilder::CreateGraph(), and Metasound::Frontend::FGraphBuilder::CreateGraph().
DECLARE_MULTICAST_DELEGATE_OneParam() [1/3]
Metasound::Frontend::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentPageAdded , const FDocumentMutatePageArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/3]
Metasound::Frontend::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentPageSet , const FDocumentMutatePageArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [3/3]
Metasound::Frontend::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDocumentRemovingPage , const FDocumentMutatePageArgs &)
DefaultPageID()
FGuid Metasound::Frontend::DefaultPageID (0 , 0 , 0 , 0) constexpr
Referenced by Metasound::Frontend::IDocumentCache::UE_DEPRECATED(), and Metasound::Frontend::IDocumentCache::UE_DEPRECATED().
FindMostSimilarInterfaceSupportingEnvironment() [1/2]
METASOUNDFRONTEND_API const FMetasoundFrontendInterface * Metasound::Frontend::FindMostSimilarInterfaceSupportingEnvironment (const FMetasoundFrontendDocument & InDocument, const TArray< FMetasoundFrontendInterface > & InCandidateInterfaces)
References FindMostSimilarInterfaceSupportingEnvironment().
FindMostSimilarInterfaceSupportingEnvironment() [2/2]
METASOUNDFRONTEND_API const FMetasoundFrontendInterface * Metasound::Frontend::FindMostSimilarInterfaceSupportingEnvironment (const FMetasoundFrontendGraphClass & InRootGraph, const TArray< FMetasoundFrontendClass > & InDependencies, const TArray< FMetasoundFrontendGraphClass > & InSubgraphs, const TArray< FMetasoundFrontendInterface > & InCandidateInterfaces)
References FindMostSimilarInterfaceSupportingEnvironment().
Referenced by FindMostSimilarInterfaceSupportingEnvironment(), and FindMostSimilarInterfaceSupportingEnvironment().
ForEachLiteral() [1/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendClass & InClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendClass.
ForEachLiteral() [2/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendClassInterface & InClassInterface, FForEachLiteralFunctionRef OnLiteral)
ForEachLiteral() [3/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendDocument & InDoc, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendDocument.
ForEachLiteral() [4/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendDocument & InDoc, FForEachLiteralFunctionRef OnLiteral, const FGuid & InPageID)
Execute the provided function for each literal on a FMetasoundFrontendDocument filtered by the given PageID.
ForEachLiteral() [5/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendGraphClass & InGraphClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass.
ForEachLiteral() [6/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendGraphClass & InGraphClass, FForEachLiteralFunctionRef OnLiteral, const FGuid & InPageID)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass filtered by the given PageID.
ForEachLiteral() [7/7]
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendNode & InNode, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendNode.
FrontendVertexAccessTypeToCoreVertexAccessType()
METASOUNDFRONTEND_API EVertexAccessType Metasound::Frontend::FrontendVertexAccessTypeToCoreVertexAccessType (EMetasoundFrontendVertexAccessType InAccessType)
GenerateClass() [1/4]
template<typename NodeType> FMetasoundFrontendClass Metasound::Frontend::GenerateClass ()
Generates a new FMetasoundFrontendClass from a NodeType.
Template Parameters
NodeType - Type of node.
Returns
FrontendClass for natively-defined node.
Definition at line 63 of file MetasoundFrontend.h.
References GenerateClass(), and Metasound::FNodeInitData::InstanceName.
Referenced by GenerateClass(), GenerateClass(), and Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
GenerateClass() [2/4]
METASOUNDFRONTEND_API FMetasoundFrontendClass Metasound::Frontend::GenerateClass (const FNodeClassMetadata & InNodeMetadata, EMetasoundFrontendClassType ClassType = EMetasoundFrontendClassType::External)
Generates a new FMetasoundFrontendClass from Node Metadata.
Parameters
InNodeMetadata - Metadata describing an external node.
Returns
FrontendClass for natively-defined node.
GenerateClass() [3/4]
template<typename NodeType> FMetasoundFrontendClass Metasound::Frontend::GenerateClass (const FNodeInitData & InNodeInitData)
Generates a new FMetasoundFrontendClass from Node init data.
Template Parameters
NodeType - Type of node to instantiate.
Parameters
InNodeInitData - Data used to call constructor of node.
Returns
FrontendClass for natively-defined node.
Definition at line 44 of file MetasoundFrontend.h.
References ensure, GenerateClass(), TUniquePtr< T, Deleter >::IsValid(), and MakeUnique().
GenerateClass() [4/4]
METASOUNDFRONTEND_API FMetasoundFrontendClass Metasound::Frontend::GenerateClass (const Metasound::Frontend::FNodeRegistryKey & InKey)
Generates a new FMetasoundFrontendClass from node lookup info.
Parameters
InInfo - Class info for a already registered external node.
Returns
FrontendClass for natively-defined node.
GetBlockRateClampRange()
METASOUNDFRONTEND_API TRange< float > Metasound::Frontend::GetBlockRateClampRange ()
GetBlockRateOverride()
METASOUNDFRONTEND_API float Metasound::Frontend::GetBlockRateOverride ()
GetBlockRateOverrideChangedDelegate()
METASOUNDFRONTEND_API FConsoleVariableMulticastDelegate & Metasound::Frontend::GetBlockRateOverrideChangedDelegate ()
GetInterfaceRegistryKey() [1/2]
METASOUNDFRONTEND_API FInterfaceRegistryKey Metasound::Frontend::GetInterfaceRegistryKey (const FMetasoundFrontendInterface & InInterface)
References InInterface.
GetInterfaceRegistryKey() [2/2]
METASOUNDFRONTEND_API FInterfaceRegistryKey Metasound::Frontend::GetInterfaceRegistryKey (const FMetasoundFrontendVersion & InInterfaceVersion)
GetMetasoundFrontendLiteralType()
METASOUNDFRONTEND_API EMetasoundFrontendLiteralType Metasound::Frontend::GetMetasoundFrontendLiteralType (ELiteralType InLiteralType)
GetMetasoundLiteralType()
METASOUNDFRONTEND_API ELiteralType Metasound::Frontend::GetMetasoundLiteralType (EMetasoundFrontendLiteralType InLiteralType)
GetSampleRateClampRange()
METASOUNDFRONTEND_API TRange< int32 > Metasound::Frontend::GetSampleRateClampRange ()
GetSampleRateOverride()
METASOUNDFRONTEND_API int32 Metasound::Frontend::GetSampleRateOverride ()
GetSampleRateOverrideChangedDelegate()
METASOUNDFRONTEND_API FConsoleVariableMulticastDelegate & Metasound::Frontend::GetSampleRateOverrideChangedDelegate ()
ImportJSONAssetToMetasound()
METASOUNDFRONTEND_API bool Metasound::Frontend::ImportJSONAssetToMetasound (const FString & InPath, FMetasoundFrontendDocument & OutMetasoundDocument)
ImportJSONToMetasound()
METASOUNDFRONTEND_API bool Metasound::Frontend::ImportJSONToMetasound (const FString & InJSON, FMetasoundFrontendDocument & OutMetasoundDocument)
InputOutputDifferenceCount() [1/2]
METASOUNDFRONTEND_API int32 Metasound::Frontend::InputOutputDifferenceCount (const FMetasoundFrontendClassInterface & InClass, const FMetasoundFrontendInterface & InInterface)
References InInterface, and InputOutputDifferenceCount().
Referenced by InputOutputDifferenceCount(), and InputOutputDifferenceCount().
InputOutputDifferenceCount() [2/2]
METASOUNDFRONTEND_API int32 Metasound::Frontend::InputOutputDifferenceCount (const FMetasoundFrontendInterface & InInterfaceA, const FMetasoundFrontendInterface & InInterfaceB)
References InputOutputDifferenceCount().
IsEqualInterface()
METASOUNDFRONTEND_API bool Metasound::Frontend::IsEqualInterface (const FMetasoundFrontendInterface & InInputInterface, const FMetasoundFrontendInterface & InTargetInterface)
References IsEqualInterface().
Referenced by IsEqualInterface().
IsEquivalentInterface()
METASOUNDFRONTEND_API bool Metasound::Frontend::IsEquivalentInterface (const FMetasoundFrontendInterface & InInputInterface, const FMetasoundFrontendInterface & InTargetInterface)
References IsEquivalentInterface().
Referenced by IsEquivalentInterface().
IsSubsetOfClassInterface()
METASOUNDFRONTEND_API bool Metasound::Frontend::IsSubsetOfClassInterface (const FMetasoundFrontendInterface & InSubsetInterface, const FMetasoundFrontendClassInterface & InSupersetClassInterface)
IsSubsetOfInterface()
METASOUNDFRONTEND_API bool Metasound::Frontend::IsSubsetOfInterface (const FMetasoundFrontendInterface & InSubsetInterface, const FMetasoundFrontendInterface & InSupersetInterface)
IsValidInterfaceRegistryKey()
METASOUNDFRONTEND_API bool Metasound::Frontend::IsValidInterfaceRegistryKey (const FInterfaceRegistryKey & InKey)
LexToString()
METASOUNDFRONTEND_API FString Metasound::Frontend::LexToString (const EInvalidEdgeReason & InReason)
MakeAccessPtr()
template<typename AccessPtrType, typename Type> AccessPtrType Metasound::Frontend::MakeAccessPtr (const FAccessPoint & InAccessPoint, Type & InRef)
Definition at line 227 of file MetasoundAccessPtr.h.
RegisterArrayNodes()
template<typename ArrayType> bool Metasound::Frontend::RegisterArrayNodes ()
Registers all available array nodes which can be instantiated for the given ArrayType.
Some nodes cannot be instantiated due to limitations of the array elements.
Definition at line 190 of file MetasoundArrayNodesRegistration.h.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeArrayWithFrontend(), and Metasound::UE_DEPRECATED().
RegisterDataType()
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void> bool Metasound::Frontend::RegisterDataType ()
Registers a data type with the MetaSound Frontend.
This allows the data type to be used in Input, Output, Send and Receive nodes by informing the Frontend how to instantiate an instance.
Template Parameters
TDataType - The data type to register.
PreferredArgType - The preferred constructor argument type to use when creating an instance of the data type.
UClassToUse - The preferred UObject class to use when constructing from an Audio::IProxyDataPtr. If the type is not constructible with an Audio::IProxyDataPtr, then this should be void.
Returns
True on success, false on failure.
Definition at line 832 of file MetasoundDataTypeRegistrationMacro.h.
References ensure.
Referenced by Metasound::UE_DEPRECATED().
RegisterNode() [1/2]
template<typename TNodeType, typename ConfigurationType = void> bool Metasound::Frontend::RegisterNode ()
Definition at line 196 of file MetasoundNodeRegistrationMacro.h.
References MakeUnique(), RegisterNode(), Metasound::TIsCreateNodeClassMetadataDeclared< U >::Value, and Metasound::TIsNodeConstructorSupported< T >::Value.
Referenced by Metasound::MetasoundArrayNodesPrivate::RegisterArrayConcatNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArrayGetNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArrayRandomGetNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArraySetNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArrayShuffleNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArraySubsetNode(), RegisterNode(), Metasound::UE_DEPRECATED(), and Metasound::UE_DEPRECATED().
RegisterNode() [2/2]
template<typename TNodeType, typename ConfigurationType = void> bool Metasound::Frontend::RegisterNode (const FNodeClassMetadata & InMetadata)
Definition at line 178 of file MetasoundNodeRegistrationMacro.h.
References ensureAlwaysMsgf, Metasound::Frontend::INodeClassRegistry::Get(), Key, MakeUnique(), Metasound::Frontend::INodeClassRegistry::RegisterNode(), RegisterNode(), TEXT, and Metasound::TIsOnlyDeprecatedNodeConstructorProvided< T >::Value.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::AttemptToRegisterConverter(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::AttemptToRegisterSendAndReceiveNodes(), Metasound::MetasoundArrayNodesPrivate::RegisterArrayLastIndexNode(), Metasound::MetasoundArrayNodesPrivate::RegisterArrayNumNode(), RegisterNode(), and Metasound::Frontend::NodeRegistrationPrivate::RegisterNodeUsingMacro().
RegisterNodeTemplate()
void Metasound::Frontend::RegisterNodeTemplate (TUniquePtr< INodeTemplate > && InTemplate)
StringToClassType()
METASOUNDFRONTEND_API bool Metasound::Frontend::StringToClassType (const FString & InString, EMetasoundFrontendClassType & OutClassType)
UE_DEPRECATED() [1/5]
Metasound::Frontend::UE_DEPRECATED (5. 5, "Reroute input recursion is now privately implemented in the reroute template node class. Use template registry to query reroute node input/output attributes")
References UE_DEPRECATED.
UE_DEPRECATED() [2/5]
Metasound::Frontend::UE_DEPRECATED (5. 5, "Reroute output recursion is now privately implemented in the reroute template node class. Use template registry to query reroute node input/output attributes")
UE_DEPRECATED() [3/5]
Metasound::Frontend::UE_DEPRECATED (5. 6, "All interface functionality is in the MetaSoundFrontendDocumentBuilder API") const &
References UE_DEPRECATED.
UE_DEPRECATED() [4/5]
Metasound::Frontend::UE_DEPRECATED (5. 6, "Use InputOutputDifferenceCount which accepts a FMetasoundFrontendClassInterface instead") const &
References UE_DEPRECATED.
UE_DEPRECATED() [5/5]
Metasound::Frontend::UE_DEPRECATED (5. 6, "Use IsSubsetOfClassInterface instead") const &
UnregisterNode()
template<typename TNodeType> bool Metasound::Frontend::UnregisterNode ()
Definition at line 216 of file MetasoundNodeRegistrationMacro.h.
References Metasound::Frontend::INodeClassRegistry::Get(), MakeUnique(), Metasound::Frontend::INodeClassRegistry::UnregisterNode(), and Metasound::TIsCreateNodeClassMetadataDeclared< U >::Value.
UnregisterNodeTemplate()
void Metasound::Frontend::UnregisterNodeTemplate (const FMetasoundFrontendClassName & InClassName, const FMetasoundFrontendVersionNumber & InTemplateVersion)
Variable Documentation
DefaultPageName
TCHAR Metasound::Frontend::DefaultPageName[] = TEXT("Default") constexpr
Definition at line 49 of file MetasoundFrontendDocument.h.
Func
TFunctionRef<void(FConstInputHandle)> Metasound::Frontend::Func
Definition at line 1165 of file MetasoundFrontendController.h.
Referenced by Metasound::Frontend::FDocumentModifyDelegates::IterateGraphEdgeDelegates(), and Metasound::Frontend::FDocumentModifyDelegates::IterateGraphNodeDelegates().
InDocumentB
const FMetasoundFrontendDocument& Metasound::Frontend::InDocumentB
Definition at line 31 of file MetasoundFrontendInterface.h.
InInterface
const FMetasoundFrontendInterface& Metasound::Frontend::InInterface
Definition at line 24 of file MetasoundFrontendInterface.h.
Referenced by GetInterfaceRegistryKey(), Metasound::Frontend::IMetaSoundAssetManager::Initialize(), InputOutputDifferenceCount(), and Metasound::Frontend::IMetaSoundAssetManager::UE_DEPRECATED().
InOutInputHandles
TArray<FConstInputHandle>& Metasound::Frontend::InOutInputHandles
Definition at line 1162 of file MetasoundFrontendController.h.
InSupersetClass
const FMetasoundFrontendClass& Metasound::Frontend::InSupersetClass
Definition at line 16 of file MetasoundFrontendInterface.h.
MetaSoundEnableCookDeterministicIDGeneration
METASOUNDFRONTEND_API int32 Metasound::Frontend::MetaSoundEnableCookDeterministicIDGeneration extern
TAccessPtr< Type >::FallbackObject
template<typename Type> Type Metasound::Frontend::TAccessPtr< Type >::FallbackObject = Type()
Definition at line 188 of file MetasoundAccessPtr.h.