Unreal Engine 5.6 C++ API: FMovieSceneChannelHandle Struct Reference
FMovieSceneChannelHandle Struct Reference
Handle to a specific channel in a UMovieSceneSection.
#include "MovieSceneChannelHandle.h"
Public Member Functions
MOVIESCENE_API FMovieSceneChannelHandle ()
Default constructor.
MOVIESCENE_API FMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, FName InChannelTypeName, int32 InChannelIndex)
Construction from a weak channel proxy, the channel's type, and its index.
template<typename OtherChannelType>
TMovieSceneChannelHandle< OtherChannelType > Cast () const
Cast this handle to a handle of a related type.
MOVIESCENE_API FMovieSceneChannel * Get () const
Get the channel pointer this handle represents.
MOVIESCENE_API int32 GetChannelIndex () const
Access this channel's index.
FMovieSceneChannelProxy * GetChannelProxy () const
Attempt to access the proxy for this channel.
MOVIESCENE_API FName GetChannelTypeName () const
Access this channel's type identifier.
MOVIESCENE_API const void * GetExtendedEditorData () const
Get the extended editor data associated with this channel.
MOVIESCENE_API const FMovieSceneChannelMetaData * GetMetaData () const
Get the meta data associated with this channel.
Static Public Member Functions
template<typename ChannelType>
static void TrackChannelTypeName ()
Private Attributes
int32 ChannelIndex
The index of the channel within the typed channels array.
FName ChannelTypeName
The type name for the channel in the proxy.
TWeakPtr< FMovieSceneChannelProxy > WeakChannelProxy
Weak pointer to the channel, proxy alisased to the channel proxy's shared reference controller to ensure it becomes null when the proxy is re-allocated.
Friends
bool operator!= (const FMovieSceneChannelHandle &A, const FMovieSceneChannelHandle &B)
Compare this channel handle for inequality against another.
bool operator== (const FMovieSceneChannelHandle &A, const FMovieSceneChannelHandle &B)
Compare this channel handle for equality against another.
Detailed Description
Handle to a specific channel in a UMovieSceneSection.
Will become nullptr when the FMovieSceneChannelProxy it was created with is reallocated.
Definition at line 19 of file MovieSceneChannelHandle.h.
Constructor & Destructor Documentation
FMovieSceneChannelHandle() [1/2]
MOVIESCENE_API FMovieSceneChannelHandle::FMovieSceneChannelHandle ()
Default constructor.
Referenced by operator!=, and operator==.
FMovieSceneChannelHandle() [2/2]
MOVIESCENE_API FMovieSceneChannelHandle::FMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, FName InChannelTypeName, int32 InChannelIndex)
Construction from a weak channel proxy, the channel's type, and its index.
Member Function Documentation
Cast()
template<typename OtherChannelType> TMovieSceneChannelHandle< OtherChannelType > FMovieSceneChannelHandle::Cast () const
Cast this handle to a handle of a related type.
Callee is responsible for ensuring that the type's are compatible.
Definition at line 213 of file MovieSceneChannelHandle.h.
References ChannelIndex, ChannelTypeName, checkf, TEXT, and WeakChannelProxy.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelModel_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelView_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::CreateCurveEditorModel_Raw(), TPerlinNoiseChannelInterface< ChannelContainerType >::CreateKeyEditor_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::CreateKeyEditor_Raw(), FMovieSceneChannelProxy::GetChannelByName(), TSequencerChannelInterfaceCommon< ChannelType >::GetKeyStruct_Raw(), and TSequencerChannelInterfaceCommon< ChannelType >::SupportsCurveEditorModels_Raw().
Get()
MOVIESCENE_API FMovieSceneChannel * FMovieSceneChannelHandle::Get () const
Get the channel pointer this handle represents.
Returns
the channel's pointer, or nullptr if the proxy it was created with is no longer alive.
Referenced by TMovieSceneChannelHandle< ChannelType >::Get().
GetChannelIndex()
MOVIESCENE_API int32 FMovieSceneChannelHandle::GetChannelIndex () const
Access this channel's index.
Referenced by FMovieSceneChannelProxyData::SetExtendedEditorData().
GetChannelProxy()
FMovieSceneChannelProxy * FMovieSceneChannelHandle::GetChannelProxy () const inline
Attempt to access the proxy for this channel.
Will return nullptr if it is no longer valid.
Definition at line 93 of file MovieSceneChannelHandle.h.
References WeakChannelProxy.
GetChannelTypeName()
MOVIESCENE_API FName FMovieSceneChannelHandle::GetChannelTypeName () const
Access this channel's type identifier.
Referenced by FMovieSceneChannelProxy::GetChannelByName(), and FMovieSceneChannelProxyData::SetExtendedEditorData().
GetExtendedEditorData()
MOVIESCENE_API const void * FMovieSceneChannelHandle::GetExtendedEditorData () const
Get the extended editor data associated with this channel.
Returns
the channel's extended editor data, or nullptr if the proxy it was created with is no longer alive.
Referenced by TMovieSceneChannelHandle< ChannelType >::GetExtendedEditorData().
GetMetaData()
MOVIESCENE_API const FMovieSceneChannelMetaData * FMovieSceneChannelHandle::GetMetaData () const
Get the meta data associated with this channel.
Returns
the channel's meta data, or nullptr if the proxy it was created with is no longer alive.
TrackChannelTypeName()
template<typename ChannelType> void FMovieSceneChannelHandle::TrackChannelTypeName () inline static
Definition at line 58 of file MovieSceneChannelHandle.h.
Referenced by FMovieSceneChannelProxyData::AddInternal().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FMovieSceneChannelHandle & A, const FMovieSceneChannelHandle & B) friend
Compare this channel handle for inequality against another.
Will return true for a handle that is to a different proxy even if it might have pointed to the same data (ie, one handle has expired)
Definition at line 52 of file MovieSceneChannelHandle.h.
References FMovieSceneChannelHandle(), A, and B.
operator==
bool operator== (const FMovieSceneChannelHandle & A, const FMovieSceneChannelHandle & B) friend
Compare this channel handle for equality against another.
Will return false for a handle that is to a different proxy even if it might have pointed to the same data (ie, one handle has expired)
Definition at line 36 of file MovieSceneChannelHandle.h.
References FMovieSceneChannelHandle(), A, and B.
Field Documentation
ChannelIndex
int32 FMovieSceneChannelHandle::ChannelIndex private
The index of the channel within the typed channels array.
Definition at line 139 of file MovieSceneChannelHandle.h.
Referenced by Cast().
ChannelTypeName
FName FMovieSceneChannelHandle::ChannelTypeName private
The type name for the channel in the proxy.
Definition at line 136 of file MovieSceneChannelHandle.h.
Referenced by Cast().
WeakChannelProxy
TWeakPtr<FMovieSceneChannelProxy> FMovieSceneChannelHandle::WeakChannelProxy private
Weak pointer to the channel, proxy alisased to the channel proxy's shared reference controller to ensure it becomes null when the proxy is re-allocated.
Definition at line 133 of file MovieSceneChannelHandle.h.
Referenced by Cast(), and GetChannelProxy().
The documentation for this struct was generated from the following file:
MovieSceneChannelHandle.h