Unreal Engine 5.6 C++ API: Metasound::Frontend::INodeClassRegistry Class Reference
Metasound::Frontend::INodeClassRegistry Class Reference abstract
Singleton registry for all types and nodes.
#include "MetasoundFrontendNodeClassRegistry.h"
Data Structures
class IObjectReferencer
Public Member Functions
INodeClassRegistry (const INodeClassRegistry &)=delete
virtual ~INodeClassRegistry ()=default
virtual TInstancedStruct< FMetaSoundFrontendNodeConfiguration > CreateFrontendNodeConfiguration (const FNodeClassRegistryKey &InKey) const =0
Return the node extension associated with the node.
virtual TUniquePtr< Metasound::INode > CreateNode (const FNodeClassRegistryKey &InKey, Metasound::FNodeData) const =0
Create a MetaSound Node with the given registration key and Node Data.
virtual bool EnqueueInitCommand (TUniqueFunction< void()> &&InFunc)=0
virtual bool FindDefaultVertexInterface (const FNodeClassRegistryKey &InKey, FVertexInterface &OutVertexInterface) const =0
virtual bool FindFrontendClassFromRegistered (const FNodeClassRegistryKey &InKey, FMetasoundFrontendClass &OutClass) const =0
virtual bool FindImplementedInterfacesFromRegistered (const FNodeClassRegistryKey &InKey, TSet< FMetasoundFrontendVersion > &OutInterfaceVersions) const =0
virtual bool FindInputNodeRegistryKeyForDataType (const FName &InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey &OutKey)=0
virtual bool FindOutputNodeRegistryKeyForDataType (const FName &InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey &OutKey)=0
virtual bool FindVariableNodeRegistryKeyForDataType (const FName &InDataTypeName, FNodeClassRegistryKey &OutKey)=0
virtual TSharedPtr< const Metasound::FGraph > GetGraph (const FGraphRegistryKey &InRegistryKey) const =0
UE_DEPRECATED(5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< Metasound virtual UE_DEPRECATED(5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< Metasound TArray< FConverterNodeClassInfo > GetPossibleConverterNodes (const FName &FromDataType, const FName &ToDataType)=0
Create a MetaSound Node with the given registration key and Init Data.
virtual bool IsGraphRegistered (const FGraphRegistryKey &InKey) const =0
Returns true if the provided registry key (node key and asset path) corresponds to a valid registered graph.
virtual bool IsNodeRegistered (const FNodeClassRegistryKey &InKey) const =0
Returns true if the provided registry key corresponds to a valid registered node.
virtual void IterateRegistry (FIterateMetasoundFrontendClassFunction InIterFunc, EMetasoundFrontendClassType InClassType=EMetasoundFrontendClassType::Invalid) const =0
INodeClassRegistry & operator= (const INodeClassRegistry &)=delete
virtual FNodeClassRegistryKey RegisterNode (TUniquePtr< INodeClassRegistryEntry > &&InEntry)=0
Register an external node with the frontend.
virtual void RegisterPendingNodes ()=0
virtual void SetObjectReferencer (TUniquePtr< IObjectReferencer > InReferencer)=0
UE_DEPRECATED (5.6, "Node class registry no longer tracks donor asset state/implementation at the interface " "level. Use the MetaSoundAssetManager to determine if the class has been defined within an asset(s).") virtual bool IsNodeNative(const FNodeClassRegistryKey &InKey) const
UE_DEPRECATED (5.6, "This function is no longer supported") static METASOUNDFRONTEND_API void ShutdownMetasoundFrontend()
virtual bool UnregisterNode (const FNodeClassRegistryKey &InKey)=0
Unregister an external node from the frontend.
virtual void WaitForAsyncGraphRegistration (const FGraphRegistryKey &InRegistryKey) const =0
Static Public Member Functions
static METASOUNDFRONTEND_API INodeClassRegistry * Get ()
static METASOUNDFRONTEND_API bool GetFrontendClassFromRegistered (const FNodeClassRegistryKey &InKey, FMetasoundFrontendClass &OutClass)
static METASOUNDFRONTEND_API bool GetInputNodeRegistryKeyForDataType (const FName &InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey &OutKey)
static METASOUNDFRONTEND_API bool GetOutputNodeRegistryKeyForDataType (const FName &InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey &OutKey)
static METASOUNDFRONTEND_API bool GetVariableNodeRegistryKeyForDataType (const FName &InDataTypeName, FNodeClassRegistryKey &OutKey)
Protected Member Functions
INodeClassRegistry ()=default
Detailed Description
Singleton registry for all types and nodes.
Definition at line 235 of file MetasoundFrontendNodeClassRegistry.h.
Constructor & Destructor Documentation
INodeClassRegistry() [1/2]
Metasound::Frontend::INodeClassRegistry::INodeClassRegistry () protected default
References INodeClassRegistry().
Referenced by INodeClassRegistry(), INodeClassRegistry(), ~INodeClassRegistry(), Get(), and operator=().
~INodeClassRegistry()
virtual Metasound::Frontend::INodeClassRegistry::~INodeClassRegistry () virtual default
References INodeClassRegistry().
INodeClassRegistry() [2/2]
Metasound::Frontend::INodeClassRegistry::INodeClassRegistry (const INodeClassRegistry &) delete
References INodeClassRegistry().
Member Function Documentation
CreateFrontendNodeConfiguration()
virtual TInstancedStruct< FMetaSoundFrontendNodeConfiguration > Metasound::Frontend::INodeClassRegistry::CreateFrontendNodeConfiguration (const FNodeClassRegistryKey & InKey) const pure virtual
Return the node extension associated with the node.
If there is no extension assoicated with the node, the returned TInstancedStruct will be invalid.
CreateNode()
virtual TUniquePtr< Metasound::INode > Metasound::Frontend::INodeClassRegistry::CreateNode (const FNodeClassRegistryKey & InKey, Metasound::FNodeData) const pure virtual
Create a MetaSound Node with the given registration key and Node Data.
Returns an invalid TUniquePtr<> if the key is not in the registry.
References CreateNode(), and UE_DEPRECATED().
Referenced by CreateNode().
EnqueueInitCommand()
virtual bool Metasound::Frontend::INodeClassRegistry::EnqueueInitCommand (TUniqueFunction< void()> && InFunc) pure virtual
References EnqueueInitCommand().
Referenced by EnqueueInitCommand().
FindDefaultVertexInterface()
virtual bool Metasound::Frontend::INodeClassRegistry::FindDefaultVertexInterface (const FNodeClassRegistryKey & InKey, FVertexInterface & OutVertexInterface) const pure virtual
FindFrontendClassFromRegistered()
virtual bool Metasound::Frontend::INodeClassRegistry::FindFrontendClassFromRegistered (const FNodeClassRegistryKey & InKey, FMetasoundFrontendClass & OutClass) const pure virtual
FindImplementedInterfacesFromRegistered()
virtual bool Metasound::Frontend::INodeClassRegistry::FindImplementedInterfacesFromRegistered (const FNodeClassRegistryKey & InKey, TSet< FMetasoundFrontendVersion > & OutInterfaceVersions) const pure virtual
FindInputNodeRegistryKeyForDataType()
virtual bool Metasound::Frontend::INodeClassRegistry::FindInputNodeRegistryKeyForDataType (const FName & InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey & OutKey) pure virtual
FindOutputNodeRegistryKeyForDataType()
virtual bool Metasound::Frontend::INodeClassRegistry::FindOutputNodeRegistryKeyForDataType (const FName & InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey & OutKey) pure virtual
FindVariableNodeRegistryKeyForDataType()
virtual bool Metasound::Frontend::INodeClassRegistry::FindVariableNodeRegistryKeyForDataType (const FName & InDataTypeName, FNodeClassRegistryKey & OutKey) pure virtual
Get()
METASOUNDFRONTEND_API INodeClassRegistry * Metasound::Frontend::INodeClassRegistry::Get () static
References INodeClassRegistry(), and UE_API.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::AttemptToRegisterConverter(), RegisterConversionNode(), Metasound::Frontend::RegisterNode(), and Metasound::Frontend::UnregisterNode().
GetFrontendClassFromRegistered()
METASOUNDFRONTEND_API bool Metasound::Frontend::INodeClassRegistry::GetFrontendClassFromRegistered (const FNodeClassRegistryKey & InKey, FMetasoundFrontendClass & OutClass) static
References GetFrontendClassFromRegistered(), and UE_API.
Referenced by GetFrontendClassFromRegistered().
GetGraph()
virtual TSharedPtr< const Metasound::FGraph > Metasound::Frontend::INodeClassRegistry::GetGraph (const FGraphRegistryKey & InRegistryKey) const pure virtual
References GetGraph().
Referenced by GetGraph().
GetInputNodeRegistryKeyForDataType()
METASOUNDFRONTEND_API bool Metasound::Frontend::INodeClassRegistry::GetInputNodeRegistryKeyForDataType (const FName & InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey & OutKey) static
References GetInputNodeRegistryKeyForDataType(), and UE_API.
Referenced by GetInputNodeRegistryKeyForDataType().
GetOutputNodeRegistryKeyForDataType()
METASOUNDFRONTEND_API bool Metasound::Frontend::INodeClassRegistry::GetOutputNodeRegistryKeyForDataType (const FName & InDataTypeName, const EMetasoundFrontendVertexAccessType InAccessType, FNodeClassRegistryKey & OutKey) static
References GetOutputNodeRegistryKeyForDataType(), and UE_API.
Referenced by GetOutputNodeRegistryKeyForDataType().
GetPossibleConverterNodes()
UE_DEPRECATED(5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< Metasound virtual UE_DEPRECATED(5.6, "Node classes should be constructed with FNodeData") virtual TUniquePtr< Metasound TArray< FConverterNodeClassInfo > Metasound::Frontend::INodeClassRegistry::GetPossibleConverterNodes (const FName & FromDataType, const FName & ToDataType) pure virtual
Create a MetaSound Node with the given registration key and Init Data.
The node will be created with a default interface.
Returns an invalid TUniquePtr<> if the key is not in the registry.
GetVariableNodeRegistryKeyForDataType()
METASOUNDFRONTEND_API bool Metasound::Frontend::INodeClassRegistry::GetVariableNodeRegistryKeyForDataType (const FName & InDataTypeName, FNodeClassRegistryKey & OutKey) static
References GetVariableNodeRegistryKeyForDataType(), and UE_API.
Referenced by GetVariableNodeRegistryKeyForDataType().
IsGraphRegistered()
virtual bool Metasound::Frontend::INodeClassRegistry::IsGraphRegistered (const FGraphRegistryKey & InKey) const pure virtual
Returns true if the provided registry key (node key and asset path) corresponds to a valid registered graph.
References IsGraphRegistered().
Referenced by IsGraphRegistered().
IsNodeRegistered()
virtual bool Metasound::Frontend::INodeClassRegistry::IsNodeRegistered (const FNodeClassRegistryKey & InKey) const pure virtual
Returns true if the provided registry key corresponds to a valid registered node.
References IsNodeRegistered().
Referenced by IsNodeRegistered().
IterateRegistry()
virtual void Metasound::Frontend::INodeClassRegistry::IterateRegistry (FIterateMetasoundFrontendClassFunction InIterFunc, EMetasoundFrontendClassType InClassType = EMetasoundFrontendClassType::Invalid) const pure virtual
operator=()
INodeClassRegistry & Metasound::Frontend::INodeClassRegistry::operator= (const INodeClassRegistry &) delete
References INodeClassRegistry().
RegisterNode()
virtual FNodeClassRegistryKey Metasound::Frontend::INodeClassRegistry::RegisterNode (TUniquePtr< INodeClassRegistryEntry > && InEntry) pure virtual
Register an external node with the frontend.
Parameters
InCreateNode - Function for creating node from FNodeInitData.
InCreateDescription - Function for creating a FMetasoundFrontendClass.
Returns
A node registration key. If the registration failed, then the registry key will be invalid.
References RegisterNode().
Referenced by RegisterNode(), and Metasound::Frontend::RegisterNode().
RegisterPendingNodes()
virtual void Metasound::Frontend::INodeClassRegistry::RegisterPendingNodes () pure virtual
References RegisterPendingNodes().
Referenced by RegisterPendingNodes().
SetObjectReferencer()
virtual void Metasound::Frontend::INodeClassRegistry::SetObjectReferencer (TUniquePtr< IObjectReferencer > InReferencer) pure virtual
References SetObjectReferencer().
Referenced by SetObjectReferencer().
UE_DEPRECATED() [1/2]
Metasound::Frontend::INodeClassRegistry::UE_DEPRECATED (5. 6, "Node class registry no longer tracks donor asset state/implementation at the interface " "level. Use the MetaSoundAssetManager to determine if the class has been defined within an asset(s).") const & inline
Definition at line 317 of file MetasoundFrontendNodeClassRegistry.h.
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
Metasound::Frontend::INodeClassRegistry::UE_DEPRECATED (5. 6, "This function is no longer supported")
References UE_API.
Referenced by CreateNode(), and UE_DEPRECATED().
UnregisterNode()
virtual bool Metasound::Frontend::INodeClassRegistry::UnregisterNode (const FNodeClassRegistryKey & InKey) pure virtual
Unregister an external node from the frontend.
Parameters
InKey - The registration key for the node.
Returns
True on success, false on failure.
References UnregisterNode().
Referenced by UnregisterNode(), and Metasound::Frontend::UnregisterNode().
WaitForAsyncGraphRegistration()
virtual void Metasound::Frontend::INodeClassRegistry::WaitForAsyncGraphRegistration (const FGraphRegistryKey & InRegistryKey) const pure virtual
References WaitForAsyncGraphRegistration().
Referenced by WaitForAsyncGraphRegistration().
The documentation for this class was generated from the following file:
MetasoundFrontendNodeClassRegistry.h