Unreal Engine 5.6 C++ API: FLoggedFileHandle Class Reference
FLoggedFileHandle Class Reference
#include "IPlatformFileLogWrapper.h"
Public Member Functions
FLoggedFileHandle (IFileHandle *InFileHandle, const TCHAR *InFilename, FLoggedPlatformFile &InOwner)
virtual ~FLoggedFileHandle ()
virtual bool Flush (const bool bFullFlush=false) override
Flushes file handle to disk.
virtual bool Read (uint8 *Destination, int64 BytesToRead) override
Read bytes from the file.
virtual bool ReadAt (uint8 *Destination, int64 BytesToRead, int64 Offset) override
virtual bool Seek (int64 NewPosition) override
Change the current write or read position.
virtual bool SeekFromEnd (int64 NewPositionRelativeToEnd) override
Change the current write or read position, relative to the end of the file.
virtual void ShrinkBuffers () override
Minimizes optional system or process cache kept for the file.
virtual int64 Size () override
Return the total size of the file.
virtual int64 Tell () override
Return the current write or read position.
virtual bool Truncate (int64 NewSize) override
Truncate the file to the given size (in bytes).
virtual bool Write (const uint8 *Source, int64 BytesToWrite) override
Write bytes to the file.
Public Member Functions inherited from IFileHandle
virtual ~IFileHandle ()
Destructor, also the only way to close the file handle.
Private Attributes
TUniquePtr< IFileHandle > FileHandle
FString Filename
FLoggedPlatformFile & PlatformFile
Detailed Description
Definition at line 42 of file IPlatformFileLogWrapper.h.
Constructor & Destructor Documentation
FLoggedFileHandle()
FLoggedFileHandle::FLoggedFileHandle (IFileHandle * InFileHandle, const TCHAR * InFilename, FLoggedPlatformFile & InOwner)
~FLoggedFileHandle()
virtual FLoggedFileHandle::~FLoggedFileHandle () virtual
Member Function Documentation
Flush()
virtual bool FLoggedFileHandle::Flush (const bool bFullFlush = false) inline override virtual
Flushes file handle to disk.
Parameters
bFullFlush true to flush everything about the file (including its meta-data) with a strong guarantee that it will be on disk by the time this function returns, or false to let the operating/file system have more leeway about when the data actually gets written to disk
Returns
true if operation completed successfully.
Implements IFileHandle.
Definition at line 117 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), TEXT, and Verbose.
Read()
virtual bool FLoggedFileHandle::Read (uint8 * Destination, int64 BytesToRead) inline override virtual
Read bytes from the file.
Parameters
Destination Buffer to holds the results, should be at least BytesToRead in size.
BytesToRead Number of bytes to read into the destination.
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 81 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), and TEXT.
ReadAt()
virtual bool FLoggedFileHandle::ReadAt (uint8 * Destination, int64 BytesToRead, int64 Offset) inline override virtual
Implements IFileHandle.
Definition at line 90 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), and TEXT.
Seek()
virtual bool FLoggedFileHandle::Seek (int64 NewPosition) inline override virtual
Change the current write or read position.
Parameters
NewPosition new write or read position
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 63 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), and TEXT.
SeekFromEnd()
virtual bool FLoggedFileHandle::SeekFromEnd (int64 NewPositionRelativeToEnd) inline override virtual
Change the current write or read position, relative to the end of the file.
Parameters
NewPositionRelativeToEnd new write or read position, relative to the end of the file should be <=0!
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 72 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), and TEXT.
ShrinkBuffers()
virtual void FLoggedFileHandle::ShrinkBuffers () inline override virtual
Minimizes optional system or process cache kept for the file.
Reimplemented from IFileHandle.
Definition at line 135 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), TEXT, and Verbose.
Size()
virtual int64 FLoggedFileHandle::Size () inline override virtual
Return the total size of the file.
Reimplemented from IFileHandle.
Definition at line 108 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), TEXT, and Verbose.
Tell()
virtual int64 FLoggedFileHandle::Tell () inline override virtual
Return the current write or read position.
Implements IFileHandle.
Definition at line 54 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), and TEXT.
Truncate()
virtual bool FLoggedFileHandle::Truncate (int64 NewSize) inline override virtual
Truncate the file to the given size (in bytes).
Parameters
NewSize Truncated file size (in bytes).
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 126 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), TEXT, and Verbose.
Write()
virtual bool FLoggedFileHandle::Write (const uint8 * Source, int64 BytesToWrite) inline override virtual
Write bytes to the file.
Parameters
Source Buffer to write, should be at least BytesToWrite in size.
BytesToWrite Number of bytes to write.
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 99 of file IPlatformFileLogWrapper.h.
References FILE_LOG, FileHandle, Filename, FAndroidTime::Seconds(), Source, and TEXT.
Field Documentation
FileHandle
TUniquePtr<IFileHandle> FLoggedFileHandle::FileHandle private
Definition at line 44 of file IPlatformFileLogWrapper.h.
Referenced by Flush(), Read(), ReadAt(), Seek(), SeekFromEnd(), ShrinkBuffers(), Size(), Tell(), Truncate(), and Write().
Filename
FString FLoggedFileHandle::Filename private
Definition at line 45 of file IPlatformFileLogWrapper.h.
Referenced by Flush(), Read(), ReadAt(), Seek(), SeekFromEnd(), ShrinkBuffers(), Size(), Tell(), Truncate(), and Write().
PlatformFile
FLoggedPlatformFile& FLoggedFileHandle::PlatformFile private
Definition at line 47 of file IPlatformFileLogWrapper.h.
The documentation for this class was generated from the following file:
IPlatformFileLogWrapper.h