Unreal Engine 5.6 C++ API: FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk > Class Template Reference
FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk > Class Template Reference
FUObjectAnnotationChunked is a helper class that is used to store dense, fast and temporary, editor only, external or other tangential information about subsets of UObjects.
#include "UObjectAnnotation.h"
Data Structures
struct TAnnotationChunk
Public Member Functions
FUObjectAnnotationChunked () TSAN_SAFE
Constructor : Probably not thread safe.
virtual ~FUObjectAnnotationChunked ()
void AddAnnotation (const UObjectBase *Object, const TAnnotation &Annotation)
Add an annotation to the annotation list.
void AddAnnotation (const UObjectBase *Object, TAnnotation &&Annotation)
void AddAnnotation (int32 Index, const TAnnotation &Annotation)
Add an annotation to the annotation list.
void AddAnnotation (int32 Index, TAnnotation &&Annotation)
TAnnotation & AddOrGetAnnotation (const UObjectBase *Object, TFunctionRef< TAnnotation()> NewAnnotationFn)
TAnnotation & AddOrGetAnnotation (int32 Index, TFunctionRef< TAnnotation()> NewAnnotationFn)
Add an annotation to the annotation list.
virtual SIZE_T GetAllocatedSize () const override
Returns the memory allocated by the internal array.
FORCEINLINE TAnnotation GetAnnotation (const UObjectBase *Object)
Return the annotation associated with a uobject.
FORCEINLINE TAnnotation GetAnnotation (int32 Index)
Return the annotation associated with a uobject.
FORCEINLINE int32 GetAnnotationCount () const
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
uint32 GetMaxAllocatedSize () const
Returns the maximum memory allocated by the internal arrays.
FORCEINLINE int32 GetMaxAnnotations () const TSAN_SAFE
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
FORCEINLINE bool IsValidIndex (int32 Index) const
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index)
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
void RemoveAnnotation (int32 Index)
Removes an annotation from the annotation list.
void TrimAnnotations ()
Frees chunk memory from empty chunks.
UE_DEPRECATED (5.3, "Use GetMaxAnnotations instead") FORCEINLINE int32 GetMaxAnnottations() const TSAN_SAFE
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Private Member Functions
template<typename T>
void AddAnnotationInternal (int32 Index, T &&Annotation)
Adds a new annotation for the specified index.
TAnnotation & AllocateAnnotation (int32 Index) TSAN_SAFE
Initializes an annotation for the specified index, makes sure the chunk it resides in is allocated.
void ExpandChunksToIndex (int32 Index) TSAN_SAFE
Makes sure we have enough chunks to fit the new index.
void FreeAllAnnotations () TSAN_SAFE
Releases all allocated memory and resets the annotation array.
void FreeAnnotation (int32 Index) TSAN_SAFE
Frees the annotation for the specified index.
Private Attributes
FTransactionallySafeRWLock AnnotationArrayCritical
Mutex.
TArray< TAnnotationChunk > Chunks
Primary table to chunks of pointers.
uint32 CurrentAllocatedMemory
Current allocated memory.
uint32 MaxAllocatedMemory
Max allocated memory.
int32 MaxAnnotations
Number of elements we can have.
int32 NumAnnotations
Number of elements we currently have.
Detailed Description
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024>
class FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >
FUObjectAnnotationChunked is a helper class that is used to store dense, fast and temporary, editor only, external or other tangential information about subsets of UObjects.
There is a notion of a default annotation and UObjects default to this annotation.
Annotations are automatically returned to the default when UObjects are destroyed. Annotation are not "garbage collection aware", so it isn't safe to store pointers to other UObjects in an annotation unless external guarantees are made such that destruction of the other object removes the annotation. The advantage of FUObjectAnnotationChunked is that it can reclaim memory if subsets of UObjects within predefined chunks no longer have any annotations associated with them.
Parameters
TAnnotation type of the annotation
bAutoRemove if true, annotation will automatically be removed, otherwise in non-final builds it will verify that the annotation was removed by other means prior to destruction.
Definition at line 634 of file UObjectAnnotation.h.
Constructor & Destructor Documentation
FUObjectAnnotationChunked()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::FUObjectAnnotationChunked () inline
Constructor : Probably not thread safe.
Definition at line 791 of file UObjectAnnotation.h.
References CurrentAllocatedMemory, MaxAllocatedMemory, MaxAnnotations, NumAnnotations, and TSAN_SAFE.
~FUObjectAnnotationChunked()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> virtual FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::~FUObjectAnnotationChunked () inline virtual
Definition at line 799 of file UObjectAnnotation.h.
References RemoveAllAnnotations().
Member Function Documentation
AddAnnotation() [1/4]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation (const UObjectBase * Object, const TAnnotation & Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Object Object to annotate.
Annotation Annotation to associate with Object.
Definition at line 812 of file UObjectAnnotation.h.
References AddAnnotation(), check, GUObjectArray, and Object.
Referenced by AddAnnotation(), and AddAnnotation().
AddAnnotation() [2/4]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation (const UObjectBase * Object, TAnnotation && Annotation) inline
Definition at line 818 of file UObjectAnnotation.h.
References AddAnnotation(), check, GUObjectArray, MoveTemp(), and Object.
AddAnnotation() [3/4]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation (int32 Index, const TAnnotation & Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Index Index of object to annotate.
Annotation Annotation to associate with Object.
Definition at line 830 of file UObjectAnnotation.h.
References AddAnnotationInternal(), and AnnotationArrayCritical.
AddAnnotation() [4/4]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotation (int32 Index, TAnnotation && Annotation) inline
Definition at line 836 of file UObjectAnnotation.h.
References AddAnnotationInternal(), AnnotationArrayCritical, and MoveTemp().
AddAnnotationInternal()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> template<typename T> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddAnnotationInternal (int32 Index, T && Annotation) inline private
Adds a new annotation for the specified index.
Definition at line 763 of file UObjectAnnotation.h.
References AllocateAnnotation(), check, Chunks, Forward(), FreeAnnotation(), GUObjectArray, and NumAnnotations.
Referenced by AddAnnotation(), and AddAnnotation().
AddOrGetAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> TAnnotation & FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddOrGetAnnotation (const UObjectBase * Object, TFunctionRef< TAnnotation()> NewAnnotationFn) inline
Definition at line 842 of file UObjectAnnotation.h.
References AddOrGetAnnotation(), check, GUObjectArray, and Object.
Referenced by AddOrGetAnnotation().
AddOrGetAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> TAnnotation & FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AddOrGetAnnotation (int32 Index, TFunctionRef< TAnnotation()> NewAnnotationFn) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Index Index of object to annotate.
Annotation Annotation to associate with Object.
Definition at line 853 of file UObjectAnnotation.h.
References AnnotationArrayCritical, check, Chunks, CurrentAllocatedMemory, ExpandChunksToIndex(), GUObjectArray, FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Items, FMath::Max, MaxAllocatedMemory, FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Num, and NumAnnotations.
AllocateAnnotation()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> TAnnotation & FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AllocateAnnotation (int32 Index) inline private
Initializes an annotation for the specified index, makes sure the chunk it resides in is allocated.
Definition at line 680 of file UObjectAnnotation.h.
References check, Chunks, CurrentAllocatedMemory, ExpandChunksToIndex(), FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Items, FMath::Max, MaxAllocatedMemory, FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Num, NumAnnotations, and TSAN_SAFE.
Referenced by AddAnnotationInternal().
ExpandChunksToIndex()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::ExpandChunksToIndex (int32 Index) inline private
Makes sure we have enough chunks to fit the new index.
Definition at line 665 of file UObjectAnnotation.h.
References check, Chunks, MaxAnnotations, and TSAN_SAFE.
Referenced by AddOrGetAnnotation(), and AllocateAnnotation().
FreeAllAnnotations()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::FreeAllAnnotations () inline private
Releases all allocated memory and resets the annotation array.
Definition at line 746 of file UObjectAnnotation.h.
References Chunks, CurrentAllocatedMemory, MaxAllocatedMemory, MaxAnnotations, NumAnnotations, and TSAN_SAFE.
Referenced by RemoveAllAnnotations().
FreeAnnotation()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::FreeAnnotation (int32 Index) inline private
Frees the annotation for the specified index.
Definition at line 707 of file UObjectAnnotation.h.
References check, Chunks, CurrentAllocatedMemory, FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Items, FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Num, NumAnnotations, and TSAN_SAFE.
Referenced by AddAnnotationInternal(), and RemoveAnnotation().
GetAllocatedSize()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> virtual SIZE_T FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetAllocatedSize () const inline override virtual
Returns the memory allocated by the internal array.
Reimplemented from FUObjectArray::FUObjectDeleteListener.
Definition at line 1036 of file UObjectAnnotation.h.
References Chunks.
GetAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FORCEINLINE TAnnotation FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetAnnotation (const UObjectBase * Object) inline
Return the annotation associated with a uobject.
Parameters
Object Object to return the annotation for
Definition at line 917 of file UObjectAnnotation.h.
References check, FORCEINLINE, GetAnnotation(), GUObjectArray, and Object.
Referenced by GetAnnotation(), and NotifyUObjectDeleted().
GetAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FORCEINLINE TAnnotation FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetAnnotation (int32 Index) inline
Return the annotation associated with a uobject.
Parameters
Index Index of the annotation to return
Definition at line 928 of file UObjectAnnotation.h.
References AnnotationArrayCritical, check, Chunks, FORCEINLINE, and FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TAnnotationChunk::Items.
GetAnnotationCount()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FORCEINLINE int32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetAnnotationCount () const inline
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the number of elements in the array
Definition at line 959 of file UObjectAnnotation.h.
References FORCEINLINE, and NumAnnotations.
GetMaxAllocatedSize()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> uint32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetMaxAllocatedSize () const inline
Returns the maximum memory allocated by the internal arrays.
Definition at line 1050 of file UObjectAnnotation.h.
References Chunks, and MaxAllocatedMemory.
GetMaxAnnotations()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FORCEINLINE int32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::GetMaxAnnotations () const inline
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the maximum number of elements in the array
Definition at line 969 of file UObjectAnnotation.h.
References FORCEINLINE, MaxAnnotations, and TSAN_SAFE.
IsValidIndex()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FORCEINLINE bool FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::IsValidIndex (int32 Index) const inline
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
Other threads might be adding during this call.
Parameters
Index Index to test
Returns
true, if this is a valid
Definition at line 991 of file UObjectAnnotation.h.
References FORCEINLINE, and MaxAnnotations.
NotifyUObjectDeleted()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> virtual void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) inline virtual
Interface for FUObjectAllocator::FUObjectDeleteListener.
Parameters
Object object that has been destroyed
Index index of object that is being deleted
Definition at line 1061 of file UObjectAnnotation.h.
References check, GetAnnotation(), MaxAnnotations, Object, and RemoveAnnotation().
OnUObjectArrayShutdown()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> virtual void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::OnUObjectArrayShutdown () inline override virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Implements FUObjectArray::FUObjectDeleteListener.
Definition at line 1076 of file UObjectAnnotation.h.
References GUObjectArray, and RemoveAllAnnotations().
RemoveAllAnnotations()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::RemoveAllAnnotations () inline
Removes all annotation from the annotation list.
Definition at line 999 of file UObjectAnnotation.h.
References AnnotationArrayCritical, FreeAllAnnotations(), GUObjectArray, and NumAnnotations.
Referenced by ~FUObjectAnnotationChunked(), and OnUObjectArrayShutdown().
RemoveAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::RemoveAnnotation (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 896 of file UObjectAnnotation.h.
References check, GUObjectArray, Object, and RemoveAnnotation().
Referenced by NotifyUObjectDeleted(), and RemoveAnnotation().
RemoveAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::RemoveAnnotation (int32 Index) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 906 of file UObjectAnnotation.h.
References AnnotationArrayCritical, and FreeAnnotation().
TrimAnnotations()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> void FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::TrimAnnotations () inline
Frees chunk memory from empty chunks.
Definition at line 1019 of file UObjectAnnotation.h.
References AnnotationArrayCritical, check, Chunks, and CurrentAllocatedMemory.
UE_DEPRECATED()
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::UE_DEPRECATED (5. 3, "Use GetMaxAnnotations instead") const inline
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the maximum number of elements in the array
Definition at line 979 of file UObjectAnnotation.h.
References FORCEINLINE, MaxAnnotations, and TSAN_SAFE.
Field Documentation
AnnotationArrayCritical
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> FTransactionallySafeRWLock FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::AnnotationArrayCritical private
Mutex.
Definition at line 660 of file UObjectAnnotation.h.
Referenced by AddAnnotation(), AddAnnotation(), AddOrGetAnnotation(), GetAnnotation(), RemoveAllAnnotations(), RemoveAnnotation(), and TrimAnnotations().
Chunks
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> TArray<TAnnotationChunk> FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::Chunks private
Primary table to chunks of pointers.
Definition at line 649 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), AddOrGetAnnotation(), AllocateAnnotation(), ExpandChunksToIndex(), FreeAllAnnotations(), FreeAnnotation(), GetAllocatedSize(), GetAnnotation(), GetMaxAllocatedSize(), and TrimAnnotations().
CurrentAllocatedMemory
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> uint32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::CurrentAllocatedMemory private
Current allocated memory.
Definition at line 655 of file UObjectAnnotation.h.
Referenced by FUObjectAnnotationChunked(), AddOrGetAnnotation(), AllocateAnnotation(), FreeAllAnnotations(), FreeAnnotation(), and TrimAnnotations().
MaxAllocatedMemory
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> uint32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::MaxAllocatedMemory private
Max allocated memory.
Definition at line 657 of file UObjectAnnotation.h.
Referenced by FUObjectAnnotationChunked(), AddOrGetAnnotation(), AllocateAnnotation(), FreeAllAnnotations(), and GetMaxAllocatedSize().
MaxAnnotations
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> int32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::MaxAnnotations private
Number of elements we can have.
Definition at line 653 of file UObjectAnnotation.h.
Referenced by FUObjectAnnotationChunked(), ExpandChunksToIndex(), FreeAllAnnotations(), GetMaxAnnotations(), IsValidIndex(), NotifyUObjectDeleted(), and UE_DEPRECATED().
NumAnnotations
template<typename TAnnotation, bool bAutoRemove, int32 NumAnnotationsPerChunk = 64 * 1024> int32 FUObjectAnnotationChunked< TAnnotation, bAutoRemove, NumAnnotationsPerChunk >::NumAnnotations private
Number of elements we currently have.
Definition at line 651 of file UObjectAnnotation.h.
Referenced by FUObjectAnnotationChunked(), AddAnnotationInternal(), AddOrGetAnnotation(), AllocateAnnotation(), FreeAllAnnotations(), FreeAnnotation(), GetAnnotationCount(), and RemoveAllAnnotations().
The documentation for this class was generated from the following file:
UObjectAnnotation.h