Unreal Engine 5.6 C++ API: FVertexFactoryTypeDependency Class Reference
FVertexFactoryTypeDependency Class Reference
Encapsulates a dependency on a vertex factory type and saved state from that vertex factory type.
#include "VertexFactory.h"
Public Member Functions
FVertexFactoryTypeDependency ()
bool operator!= (const FVertexFactoryTypeDependency &Reference) const
bool operator== (const FVertexFactoryTypeDependency &Reference) const
RENDERCORE_API void RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
Data Fields
FHashedName VertexFactoryTypeName
FSHAHash VFSourceHash
Used to detect changes to the vertex factory source files.
Private Member Functions
RENDERCORE_API void Save (FCbWriter &Writer) const
bool TryLoad (FCbFieldView Field)
Friends
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FVertexFactoryTypeDependency &OutValue)
FArchive & operator<< (FArchive &Ar, class FVertexFactoryTypeDependency &Ref)
FCbWriter & operator<< (FCbWriter &Writer, const FVertexFactoryTypeDependency &Value)
Detailed Description
Encapsulates a dependency on a vertex factory type and saved state from that vertex factory type.
Definition at line 598 of file VertexFactory.h.
Constructor & Destructor Documentation
FVertexFactoryTypeDependency()
FVertexFactoryTypeDependency::FVertexFactoryTypeDependency () inline
Definition at line 601 of file VertexFactory.h.
Referenced by LoadFromCompactBinary, operator!=(), operator<<, operator<<, and operator==().
Member Function Documentation
operator!=()
bool FVertexFactoryTypeDependency::operator!= (const FVertexFactoryTypeDependency & Reference) const inline
Definition at line 619 of file VertexFactory.h.
References FVertexFactoryTypeDependency().
operator==()
bool FVertexFactoryTypeDependency::operator== (const FVertexFactoryTypeDependency & Reference) const inline
Definition at line 614 of file VertexFactory.h.
References FVertexFactoryTypeDependency(), VertexFactoryTypeName, and VFSourceHash.
RefreshCachedSourceHash()
RENDERCORE_API void FVertexFactoryTypeDependency::RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
References ShaderPlatform.
Save()
RENDERCORE_API void FVertexFactoryTypeDependency::Save (FCbWriter & Writer) const private
TryLoad()
bool FVertexFactoryTypeDependency::TryLoad (FCbFieldView Field) private
Friends And Related Symbol Documentation
LoadFromCompactBinary
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FVertexFactoryTypeDependency & OutValue) friend
References FVertexFactoryTypeDependency().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, class FVertexFactoryTypeDependency & Ref) friend
Definition at line 608 of file VertexFactory.h.
References FVertexFactoryTypeDependency(), and Ar.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FVertexFactoryTypeDependency & Value) friend
Definition at line 632 of file VertexFactory.h.
References FVertexFactoryTypeDependency(), and Value.
Field Documentation
VertexFactoryTypeName
FHashedName FVertexFactoryTypeDependency::VertexFactoryTypeName
Definition at line 603 of file VertexFactory.h.
Referenced by operator==().
VFSourceHash
FSHAHash FVertexFactoryTypeDependency::VFSourceHash
Used to detect changes to the vertex factory source files.
Definition at line 606 of file VertexFactory.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
VertexFactory.h