Unreal Engine 5.6 C++ API: TObjectIterator< UObject > Class Reference
TObjectIterator< UObject > Class Reference
specialization for T == UObject that does not call IsA() unnecessarily
#include "UObjectIterator.h"
Public Types
enum EEndTagType
Public Types inherited from FUObjectArray::TIterator
enum EEndTagType { EndTag }
Public Member Functions
TObjectIterator (bool bOnlyGCedObjects)
Constructor.
TObjectIterator (EObjectFlags AdditionalExclusionFlags=RF_ClassDefaultObject, bool bIncludeDerivedClasses=true, EInternalObjectFlags InInternalExclusionFlags=EInternalObjectFlags::None)
Constructor.
TObjectIterator (TObjectIteratorBase::EEndTagType, const TObjectIterator &Begin)
Constructor.
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TObjectIterator &Rhs) const
FUNCTION_NON_NULL_RETURN_START FORCEINLINE UObject * operator* () const FUNCTION_NON_NULL_RETURN_END
Iterator dereference.
void operator++ ()
Iterator advance.
FUNCTION_NON_NULL_RETURN_START FORCEINLINE UObject * operator-> () const FUNCTION_NON_NULL_RETURN_END
Iterator dereference.
FORCEINLINE bool operator== (const TObjectIterator &Rhs) const
Public Member Functions inherited from TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >
TObjectIteratorBase (const TObjectIteratorBase &Other)
Copy Constructor.
TObjectIteratorBase (FUObjectArray::TIterator::EEndTagType, const TObjectIteratorBase &Begin)
Constructor.
TObjectIteratorBase (UClass *InClass=UObject::StaticClass(), bool bOnlyGCedObjects=false, EObjectFlags AdditionalExclusionFlags=RF_NoFlags, EInternalObjectFlags InInternalExclusionFlags=EInternalObjectFlags::None)
Constructor.
~TObjectIteratorBase ()
Destructor.
FORCEINLINE UObject * operator* () const
Iterator dereference.
void operator++ ()
Iterator advance.
FORCEINLINE UObject * operator-> () const
Iterator dereference.
Public Member Functions inherited from FUObjectArray::TIterator
TIterator (const FUObjectArray &InArray, bool bOnlyGCedObjects=false)
Constructor.
TIterator (EEndTagType, const TIterator &InIter)
Constructor.
FORCEINLINE int32 GetIndex () const
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
bool operator!= (const TIterator &Rhs) const
FORCEINLINE void operator++ ()
Iterator advance.
bool operator== (const TIterator &Rhs) const
Protected Member Functions
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
FORCEINLINE UObject * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Protected Member Functions inherited from TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >
FORCEINLINE bool AdvanceIterator ()
Wrapper around FUObjectArray::TIterator::Advance that locks the FUObjectArray mutex before advancing if necessary.
Protected Member Functions inherited from FUObjectArray::TIterator
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
const FUObjectArray & GetIteratedArray () const
Gets the array this iterator iterates over.
FORCEINLINE FUObjectItem * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Protected Attributes
int32 Index
index of the current element in the object array
TArray< UObject * > ObjectArray
Results from the GetObjectsOfClass query.
Protected Attributes inherited from TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >
EObjectFlags ExclusionFlags
Flags that returned objects must not have.
EInternalObjectFlags InternalExclusionFlags
Internal Flags that returned objects must not have.
Detailed Description
specialization for T == UObject that does not call IsA() unnecessarily
Definition at line 357 of file UObjectIterator.h.
Member Enumeration Documentation
EEndTagType
enum TObjectIterator::EEndTagType
Definition at line 255 of file UObjectIterator.h.
Constructor & Destructor Documentation
TObjectIterator() [1/3]
TObjectIterator< UObject >::TObjectIterator (EObjectFlags AdditionalExclusionFlags = RF_ClassDefaultObject, bool bIncludeDerivedClasses = true, EInternalObjectFlags InInternalExclusionFlags = EInternalObjectFlags::None) inline explicit
Constructor.
Parameters
AdditionalExclusionFlags RF_* flags that should not be included in results
InInternalExclusionFlags EInternalObjectFlags flagged objects that should not be included in results
Definition at line 367 of file UObjectIterator.h.
References GetObjectIteratorDefaultInternalExclusionFlags(), None, RF_ClassDefaultObject, and StaticClass().
Referenced by TObjectIterator().
TObjectIterator() [2/3]
TObjectIterator< UObject >::TObjectIterator (bool bOnlyGCedObjects) inline explicit
Constructor.
Parameters
bOnlyGCedObjects if true, skip all of the permanent objects
Definition at line 377 of file UObjectIterator.h.
References RF_ClassDefaultObject, and StaticClass().
TObjectIterator() [3/3]
TObjectIterator< UObject >::TObjectIterator (TObjectIteratorBase::EEndTagType , const TObjectIterator< UObject > & Begin) inline
Constructor.
Parameters
Begin The iterator to get the end iterator of.
Definition at line 387 of file UObjectIterator.h.
References FUObjectArray::TIterator::TIterator(), TObjectIterator(), and EndTag.
Member Function Documentation
Advance()
FORCEINLINE bool TObjectIterator< UObject >::Advance () inline protected
Iterator advance with ordinary name for clarity in subclasses.
Returns
true if the iterator points to a valid object, false if iteration is complete
Definition at line 336 of file UObjectIterator.h.
GetObject()
FORCEINLINE UObject * TObjectIterator< UObject >::GetObject () const inline protected
Dereferences the iterator with an ordinary name for clarity in derived classes.
Returns
the UObject at the iterator
Definition at line 327 of file UObjectIterator.h.
operator bool()
FORCEINLINE TObjectIterator< UObject >::operator bool () const inline explicit
Conversion to "bool" returning true if the iterator is valid.
Definition at line 287 of file UObjectIterator.h.
operator!()
FORCEINLINE bool TObjectIterator< UObject >::operator! () const inline
Conversion to "bool" returning true if the iterator is valid.
Definition at line 292 of file UObjectIterator.h.
operator!=()
FORCEINLINE bool TObjectIterator< UObject >::operator!= (const TObjectIterator< UObject > & Rhs) const inline
Definition at line 319 of file UObjectIterator.h.
operator*()
FUNCTION_NON_NULL_RETURN_START FORCEINLINE UObject * TObjectIterator< UObject >::operator* () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 302 of file UObjectIterator.h.
operator++()
void TObjectIterator< UObject >::operator++ () inline
Iterator advance.
Definition at line 395 of file UObjectIterator.h.
References TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >::AdvanceIterator(), checkSlow, EInternalObjectFlags_AsyncLoading, TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >::ExclusionFlags, TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::ThreadSafe >::InternalExclusionFlags, and IsInAsyncLoadingThread.
operator->()
FUNCTION_NON_NULL_RETURN_START FORCEINLINE UObject * TObjectIterator< UObject >::operator-> () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 312 of file UObjectIterator.h.
operator==()
FORCEINLINE bool TObjectIterator< UObject >::operator== (const TObjectIterator< UObject > & Rhs) const inline
Definition at line 318 of file UObjectIterator.h.
Field Documentation
Index
int32 TObjectIterator< UObject >::Index protected
index of the current element in the object array
Definition at line 353 of file UObjectIterator.h.
ObjectArray
TArray<UObject*> TObjectIterator< UObject >::ObjectArray protected
Results from the GetObjectsOfClass query.
Definition at line 351 of file UObjectIterator.h.
The documentation for this class was generated from the following file:
UObjectIterator.h