Unreal Engine 5.6 C++ API: FAudioThread Class Reference
FAudioThread Class Reference
#include "AudioThread.h"
Static Public Member Functions
static FString GetCurrentAudioThreadStatId ()
Retrieves the current audio thread stat id.
static void GetLongestTaskInfo (FString &OutLongestTask, double &OutLongestTaskTimeMs)
static bool IsUsingThreadedAudio ()
static void ProcessAllCommands ()
Processes all enqueued audio thread commands.
static void ResetAudioThreadTimers ()
static void ResumeAudioThread ()
static void RunCommandOnAudioThread (TUniqueFunction< void()> InFunction, const TStatId InStatId=TStatId())
Execute a command on the audio thread.
static void RunCommandOnGameThread (TUniqueFunction< void()> InFunction, const TStatId InStatId=TStatId())
Execute a (presumably audio) command on the game thread.
static void SetUseThreadedAudio (bool bInUseThreadedAudio)
static void StartAudioThread ()
Starts the audio thread.
static void StopAudioThread ()
Stops the audio thread.
static void SuspendAudioThread ()
Static Private Member Functions
static TUniqueFunction< void()> GetCommandWrapper (TUniqueFunction< void()> InFunction, const TStatId InStatId)
static double GetCurrentLongestTime ()
static void SetCurrentAudioThreadStatId (TStatId InStatId)
Sets the current audio thread stat id.
static void SetLongestTimeAndId (TStatId NewLongestId, double LongestTimeMsec)
Static Private Attributes
static bool bUseThreadedAudio
Whether to run with an audio thread.
static TStatId CurrentAudioThreadStatId
Stat id of the currently executing audio thread command.
static FCriticalSection CurrentAudioThreadStatIdCS
static TStatId LongestAudioThreadStatId
static double LongestAudioThreadTimeMsec
static FDelegateHandle PostGC
static FDelegateHandle PostGCDestroy
static FDelegateHandle PreGC
static FDelegateHandle PreGCDestroy
static TUniquePtr< UE::Tasks::FTaskEvent > ResumeEvent
static int32 SuspendCount
Detailed Description
Definition at line 21 of file AudioThread.h.
Member Function Documentation
GetCommandWrapper()
TUniqueFunction< void()> FAudioThread::GetCommandWrapper (TUniqueFunction< void()> InFunction, const TStatId InStatId) static private
GetCurrentAudioThreadStatId()
FString FAudioThread::GetCurrentAudioThreadStatId () static
Retrieves the current audio thread stat id.
Useful for reporting when an audio thread command stalls or deadlocks.
GetCurrentLongestTime()
double FAudioThread::GetCurrentLongestTime () inline static private
Definition at line 45 of file AudioThread.h.
References LongestAudioThreadTimeMsec.
GetLongestTaskInfo()
void FAudioThread::GetLongestTaskInfo (FString & OutLongestTask, double & OutLongestTaskTimeMs) static
IsUsingThreadedAudio()
bool FAudioThread::IsUsingThreadedAudio () static
ProcessAllCommands()
void FAudioThread::ProcessAllCommands () static
Processes all enqueued audio thread commands.
ResetAudioThreadTimers()
void FAudioThread::ResetAudioThreadTimers () static
ResumeAudioThread()
void FAudioThread::ResumeAudioThread () static
Referenced by FAudioThreadSuspendContext::~FAudioThreadSuspendContext(), and FAudioDevice::SetSpatializationInterfaceEnabled().
RunCommandOnAudioThread()
void FAudioThread::RunCommandOnAudioThread (TUniqueFunction< void()> InFunction, const TStatId InStatId = TStatId()) static
Execute a command on the audio thread.
If it's safe the command will execute immediately.
Referenced by FAudioDevice::SetHRTFDisabled(), and FAudioDevice::SetHRTFEnabledForAll().
RunCommandOnGameThread()
void FAudioThread::RunCommandOnGameThread (TUniqueFunction< void()> InFunction, const TStatId InStatId = TStatId()) static
Execute a (presumably audio) command on the game thread.
If GIsAudioThreadRunning is false the command will execute immediately
SetCurrentAudioThreadStatId()
void FAudioThread::SetCurrentAudioThreadStatId (TStatId InStatId) static private
Sets the current audio thread stat id.
SetLongestTimeAndId()
void FAudioThread::SetLongestTimeAndId (TStatId NewLongestId, double LongestTimeMsec) static private
SetUseThreadedAudio()
void FAudioThread::SetUseThreadedAudio (bool bInUseThreadedAudio) static
StartAudioThread()
void FAudioThread::StartAudioThread () static
Starts the audio thread.
StopAudioThread()
void FAudioThread::StopAudioThread () static
Stops the audio thread.
SuspendAudioThread()
void FAudioThread::SuspendAudioThread () static
Referenced by FAudioThreadSuspendContext::FAudioThreadSuspendContext(), and FAudioDevice::SetSpatializationInterfaceEnabled().
Field Documentation
bUseThreadedAudio
bool FAudioThread::bUseThreadedAudio static private
Whether to run with an audio thread.
Definition at line 25 of file AudioThread.h.
CurrentAudioThreadStatId
TStatId FAudioThread::CurrentAudioThreadStatId static private
Stat id of the currently executing audio thread command.
Definition at line 37 of file AudioThread.h.
CurrentAudioThreadStatIdCS
FCriticalSection FAudioThread::CurrentAudioThreadStatIdCS static private
Definition at line 40 of file AudioThread.h.
LongestAudioThreadStatId
TStatId FAudioThread::LongestAudioThreadStatId static private
Definition at line 38 of file AudioThread.h.
LongestAudioThreadTimeMsec
double FAudioThread::LongestAudioThreadTimeMsec static private
Definition at line 39 of file AudioThread.h.
Referenced by GetCurrentLongestTime().
PostGC
FDelegateHandle FAudioThread::PostGC static private
Definition at line 32 of file AudioThread.h.
PostGCDestroy
FDelegateHandle FAudioThread::PostGCDestroy static private
Definition at line 34 of file AudioThread.h.
PreGC
FDelegateHandle FAudioThread::PreGC static private
Definition at line 31 of file AudioThread.h.
PreGCDestroy
FDelegateHandle FAudioThread::PreGCDestroy static private
Definition at line 33 of file AudioThread.h.
ResumeEvent
TUniquePtr<UE::Tasks::FTaskEvent> FAudioThread::ResumeEvent static private
Definition at line 27 of file AudioThread.h.
SuspendCount
int32 FAudioThread::SuspendCount static private
Definition at line 28 of file AudioThread.h.
The documentation for this class was generated from the following file:
AudioThread.h