Unreal Engine 5.6 C++ API: UE::Tasks::Private::TExecutableTask< TaskBodyType > Class Template Reference
UE::Tasks::Private::TExecutableTask< TaskBodyType > Class Template Reference final
#include "TaskPrivate.h"
Public Member Functions
TExecutableTask (const TCHAR *InDebugName, TaskBodyType &&TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
Public Member Functions inherited from UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >
virtual void ExecuteTask () override final
Public Member Functions inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
ResultType & GetResult ()
Public Member Functions inherited from UE::Tasks::Private::FTaskBase
void AddNested (FTaskBase &Nested)
template<typename HigherLevelTaskType, decltype(std::declval< HigherLevelTaskType >().Pimpl) * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites)
bool AddPrerequisites (FTaskBase &Prerequisite)
void AddRef ()
bool AddSubsequent (FTaskBase &Subsequent)
EExtendedTaskPriority GetExtendedPriority () const
FPipe * GetPipe () const
ETaskPriority GetPriority () const
uint32 GetRefCount (std::memory_order MemoryOrder=std::memory_order_relaxed) const
TaskTrace::FId GetTraceId () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsNamedThreadTask () const
void Release ()
void ReleaseInternalReference ()
void SetPipe (FPipe &InPipe)
bool TryLaunch (uint64 TaskSize)
bool TryRetractAndExecute (FTimeout Timeout, uint32 RecursionDepth=0)
template<typename ConditionType>
UE_DEPRECATED (5.5, "This method will be removed.") bool BusyWait(ConditionType &&Condition)
UE_DEPRECATED (5.5, "Use Wait instead") bool BusyWait(FTimeout Timeout)
void Wait ()
bool Wait (FTimeout Timeout)
void WaitWithNamedThreadsSupport ()
Static Public Member Functions
static TExecutableTask * Create (const TCHAR *InDebugName, TaskBodyType &&TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
static void operator delete (void *Ptr, size_t Size)
static void * operator new (size_t Size)
Additional Inherited Members
Protected Member Functions inherited from UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >
TExecutableTaskBase (const TCHAR *InDebugName, TaskBodyType &&TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
Protected Member Functions inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
TTaskWithResult (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, uint32 InitRefCount, ETaskFlags Flags)
virtual ~TTaskWithResult () override
Protected Member Functions inherited from UE::Tasks::Private::FTaskBase
FTaskBase (uint32 InitRefCount, bool bUnlockPrerequisites=true)
virtual ~FTaskBase ()
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites, bool bLockPrerequisite)
void ClearPipe ()
void Close ()
void Init (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
bool TryExecuteTask ()
void UnlockPrerequisites ()
Protected Attributes inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
TTypeCompatibleBytes< ResultType > ResultStorage
Detailed Description
template<typename TaskBodyType>
class UE::Tasks::Private::TExecutableTask< TaskBodyType >
Definition at line 931 of file TaskPrivate.h.
Constructor & Destructor Documentation
TExecutableTask()
template<typename TaskBodyType> UE::Tasks::Private::TExecutableTask< TaskBodyType >::TExecutableTask (const TCHAR * InDebugName, TaskBodyType && TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags) inline
Definition at line 934 of file TaskPrivate.h.
References UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::TExecutableTaskBase(), Flags, and MoveTemp().
Referenced by Create(), and operator new().
Member Function Documentation
Create()
template<typename TaskBodyType> TExecutableTask * UE::Tasks::Private::TExecutableTask< TaskBodyType >::Create (const TCHAR * InDebugName, TaskBodyType && TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags) inline static
Definition at line 940 of file TaskPrivate.h.
References TExecutableTask(), Flags, and MoveTemp().
operator delete()
template<typename TaskBodyType> void UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator delete (void * Ptr, size_t Size) inline static
Definition at line 958 of file TaskPrivate.h.
References UE::Private::GMalloc, UE::Tasks::Private::SmallTaskAllocator, UE::Tasks::Private::SmallTaskSize, and TSequenceHistory< HistorySize >::Size.
operator new()
template<typename TaskBodyType> void * UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator new (size_t Size) inline static
Definition at line 945 of file TaskPrivate.h.
References TExecutableTask(), UE::Private::GMalloc, UE::Tasks::Private::LargeTaskAlignment, UE::Tasks::Private::SmallTaskAllocator, UE::Tasks::Private::SmallTaskSize, TASKGRAPH_VERBOSE_EVENT_SCOPE, and TSequenceHistory< HistorySize >::Size.
The documentation for this class was generated from the following file:
TaskPrivate.h