Unreal Engine 5.6 C++ API: ICommonUIModule Class Reference
ICommonUIModule Class Reference abstract
Interface for the purchase flow module.
#include "ICommonUIModule.h"
Public Member Functions
virtual TAsyncLoadPriority GetLazyLoadPriority () const =0
virtual FStreamableManager & GetStreamableManager () const =0
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static ICommonUIModule & Get ()
Singleton-like access to this module's interface.
static UCommonUIEditorSettings & GetEditorSettings ()
static UCommonUISettings & GetSettings ()
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Protected Member Functions
virtual UCommonUIEditorSettings * GetEditorSettingsInstance () const =0
virtual UCommonUISettings * GetSettingsInstance () const =0
Detailed Description
Interface for the purchase flow module.
Definition at line 16 of file ICommonUIModule.h.
Member Function Documentation
Get()
ICommonUIModule & ICommonUIModule::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 27 of file ICommonUIModule.h.
References FModuleManager::LoadModuleChecked().
Referenced by GetEditorSettings(), and GetSettings().
GetEditorSettings()
UCommonUIEditorSettings & ICommonUIModule::GetEditorSettings () inline static
Returns
reference to Common UI Editor settings
Definition at line 57 of file ICommonUIModule.h.
References check, Get(), GetEditorSettingsInstance(), FModuleManager::GetModuleChecked(), and IsInGameThread().
GetEditorSettingsInstance()
virtual UCommonUIEditorSettings * ICommonUIModule::GetEditorSettingsInstance () const protected pure virtual
Referenced by GetEditorSettings().
GetLazyLoadPriority()
virtual TAsyncLoadPriority ICommonUIModule::GetLazyLoadPriority () const pure virtual
GetSettings()
UCommonUISettings & ICommonUIModule::GetSettings () inline static
Returns
reference to Common UI settings
Definition at line 45 of file ICommonUIModule.h.
References check, Get(), FModuleManager::GetModuleChecked(), GetSettingsInstance(), and IsInGameThread().
GetSettingsInstance()
virtual UCommonUISettings * ICommonUIModule::GetSettingsInstance () const protected pure virtual
Referenced by GetSettings().
GetStreamableManager()
virtual FStreamableManager & ICommonUIModule::GetStreamableManager () const pure virtual
IsAvailable()
bool ICommonUIModule::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 37 of file ICommonUIModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
The documentation for this class was generated from the following file:
ICommonUIModule.h