Unreal Engine 5.6 C++ API: FGlobalTabmanager Class Reference
FGlobalTabmanager Class Reference
#include "TabManager.h"
Data Structures
struct FindByManager
struct FindByTab
struct FSubTabManager
Pairs of Major Tab and the TabManager that manages tabs within it.
Public Member Functions
void AddLegacyTabType (FName InLegacyTabType, FName InNewTabType)
Adds a legacy tab type to the tab type redirection map so tabs loaded with this type will be automatically converted to the new type.
virtual bool CanCloseManager (const TSet< TSharedRef< SDockTab > > &TabsToIgnore=TSet< TSharedRef< SDockTab > >()) override
Check these all tabs to see if it is OK to close them.
bool CanSavePersistentLayouts () const
Returns true if any layouts (across all tab managers) can be saved at this time.
bool CanSetAsActiveTab (const TSharedPtr< SDockTab > &Tab)
Can the manager activate this Tab as the new active tab?
DECLARE_DELEGATE (FOnOverrideDockableAreaRestore)
void DrawAttentionToTabManager (const TSharedRef< FTabManager > &ChildManager)
Draw the user's attention to a child tab manager.
TSharedPtr< SDockTab > GetActiveTab () const
const FText & GetApplicationTitle () const
TSharedPtr< FTabManager::FLayout > GetInitialLayoutSP ()
Gets the initial layout shared pointer, which can be used later to get the current layout for tabs which were not spawned on initialization.
TSharedPtr< SDockTab > GetMajorTabForTabManager (const TSharedRef< FTabManager > &ChildManager)
Gets the major tab for the manager.
int32 GetMaximumTabCount () const
Returns the highest number of tabs that were open simultaneously during this session.
int32 GetMaximumWindowCount () const
Returns the highest number of parent windows that were open simultaneously during this session.
TSharedPtr< SWindow > GetRootWindow () const
The window under which all other windows in our app nest; might be null.
bool GetShouldUseMiddleEllipsisForDockTabLabel () const
Get if the DockTab label should use the MiddleEllipsis overflow policy.
TSharedPtr< FTabManager > GetTabManagerForMajorTab (const TSharedPtr< SDockTab > DockTab) const
Gets the tab manager that a major tab owns.
FName GetTabTypeForPotentiallyLegacyTab (FName InTabType) const
If the specified TabType is deprecated, returns the new replacement tab type.
bool IsLegacyTabType (FName InTabType) const
Returns true if the specified tab type is registered as a legacy tab.
TSharedRef< FTabManager > NewTabManager (const TSharedRef< SDockTab > &InOwnerTab)
FDelegateHandle OnActiveTabChanged_Subscribe (const FOnActiveTabChanged::FDelegate &InDelegate)
Subscribe to notifications about the active tab changing.
void OnActiveTabChanged_Unsubscribe (FDelegateHandle Handle)
Unsubscribe to notifications about the active tab changing.
FDelegateHandle OnTabForegrounded_Subscribe (const FOnActiveTabChanged::FDelegate &InDelegate)
Subscribe to notifications about a foreground tab changing.
void OnTabForegrounded_Unsubscribe (FDelegateHandle Handle)
Unsubscribe to notifications about a foreground tab changing.
virtual void OnTabManagerClosing () override
Invoked when a tab manager is closing down.
FTabSpawnerEntry & RegisterNomadTabSpawner (const FName TabId, const FOnSpawnTab &OnSpawnTab, const FCanSpawnTab &CanSpawnTab=FCanSpawnTab())
Register a new nomad tab spawner with the tab manager.
void SaveAllVisualState ()
Persist and serialize the layout of every TabManager and the custom visual state of every Tab.
void SetActiveTab (const TSharedPtr< SDockTab > &NewActiveTab)
Activate the NewActiveTab.
void SetApplicationTitle (const FText &AppTitle)
void SetCanSavePersistentLayouts (bool bInCanSavePersistentLayouts)
Sets whether or not any layouts (across all tab managers) can be saved at this time.
void SetInitialLayoutSP (TSharedPtr< FTabManager::FLayout > InLayout)
Sets the initial layout shared pointer, which can be used later to get the current layout for tabs which were not spawned on initialization.
void SetProxyTabManager (TSharedPtr< FProxyTabmanager > InProxyTabManager)
void SetRootWindow (const TSharedRef< SWindow > InRootWindow)
Provide a window under which all other windows in this application should nest.
void SetShouldUseMiddleEllipsisForDockTabLabel (const bool bInShouldUseMiddleEllipsis)
Set whether the DockTab label should use the MiddleEllipsis overflow policy.
void UnregisterNomadTabSpawner (const FName TabId)
void UpdateMainMenu (const TSharedRef< SDockTab > &ForTab, bool const bForce)
Update the native, global menu bar if it is being used for a specific tab managed by the global tab manager.
Public Member Functions inherited from FTabManager
virtual ~FTabManager ()
TSharedRef< FWorkspaceItem > AddLocalWorkspaceMenuCategory (const FText &CategoryTitle)
Adds a category to the local workspace menu by name.
void AddLocalWorkspaceMenuItem (const TSharedRef< FWorkspaceItem > &CategoryItem)
Adds an existing workspace item to the local workspace menu.
bool AllowsWindowMenuBar () const
Whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
void ClearLocalWorkspaceMenuCategories ()
Clears all categories in the local workspace menu.
void ClearPendingLayoutSave ()
Clears the request for a deferred save of the layout.
void CloseAllAreas ()
Close all live areas and wipe all the persisted areas.
TArray< TWeakPtr< FTabSpawnerEntry > > CollectSpawners ()
Return an array of all tab spawners that should have menu items in the main menu.
DECLARE_DELEGATE_OneParam (FOnPersistLayout, const TSharedRef< FLayout > &)
virtual void DrawAttention (const TSharedRef< SDockTab > &TabToHighlight)
TSharedPtr< SDockTab > FindExistingLiveTab (const FTabId &TabId) const
Finds the first instance of an existing tab with the given tab id.
TSharedPtr< FTabSpawnerEntry > FindTabSpawnerFor (FName TabId)
Find a tab spawner by name.
const TSharedPtr< const FTabSpawnerEntry > FindTabSpawnerFor (FName TabId) const
Find a tab spawner by name.
TSharedPtr< FArea > GetAreaFromInitialLayoutWithTabType (const FTabId &InTabIdToMatch) const
Gets a TSharedPtr<FArea> with the given FTabId if present, else it return nullptr.
bool GetCanDoDragOperation ()
const TSharedRef< FWorkspaceItem > GetLocalWorkspaceMenuRoot () const
FOnReadOnlyModeChanged & GetOnReadOnlyModeChangedDelegate ()
TSharedPtr< SDockTab > GetOwnerTab ()
Returns the owner tab (if it exists)
FTabManager::FPrivateApi & GetPrivateApi ()
TSharedRef< FNamePermissionList > & GetTabPermissionList ()
Returns filter for additional control over available tabs.
TOptional< ETabReadOnlyBehavior > GetTabReadOnlyBehavior (const FTabId &TabId) const
FUIAction GetUIActionForTabSpawnerMenuEntry (TSharedPtr< FTabSpawnerEntry > InTabMenuEntry)
bool HasTabSpawner (FName TabId) const
bool HasValidOpenTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode) const
It searches for valid and open tabs on SomeNode.
void InsertNewDocumentTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
void InsertNewDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
void InsertNewDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
bool IsReadOnly ()
Is this Tab Manager in Read Only mode i.e all interactions with panels are disabled.
bool IsTabAllowedInSidebar (const FTabId TabId) const
bool IsTabCloseable (const TSharedRef< const SDockTab > &InTab) const
TSharedRef< FTabManager::FLayout > PersistLayout () const
Gather the persistent layout.
void PopulateLocalTabSpawnerMenu (FMenuBuilder &PopulateMe)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, const FName &TabType)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure, bool bIncludeOrphanedMenus)
FTabSpawnerEntry & RegisterTabSpawner (const FName TabId, const FOnSpawnTab &OnSpawnTab, const FCanSpawnTab &CanSpawnTab=FCanSpawnTab())
Register a new tab spawner with the tab manager.
void RequestSavePersistentLayout ()
Request a deferred save of the layout.
void RestoreDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Much like InsertNewDocumentTab, but the UnmanagedTab is not seen by the user as newly-created.
TSharedPtr< SWidget > RestoreFrom (const TSharedRef< FLayout > &Layout, const TSharedPtr< SWindow > &ParentWindow, const bool bEmbedTitleAreaContent=false, const EOutputCanBeNullptr RestoreAreaOutputCanBeNullptr=EOutputCanBeNullptr::Never)
void SavePersistentLayout ()
Gather the persistent layout and execute the custom delegate for saving it to persistent storage (e.g.
void SetAllowWindowMenuBar (bool bInAllowWindowMenuBar)
Sets whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
void SetCanDoDragOperation (bool CanDoDragOperation)
void SetMainTab (const FTabId &InMainTabID)
void SetMainTab (const TSharedRef< const SDockTab > &InTab)
Provide a tab that will be the main tab and cannot be closed.
void SetMenuMultiBox (const TSharedPtr< FMultiBox > NewMenuMutliBox, const TSharedPtr< SWidget > MenuWidget)
Set the multi-box to use for generating a global menu bar.
void SetOnPersistLayout (const FOnPersistLayout &InHandler)
void SetReadOnly (bool bInReadOnly)
void ToggleSidebarOpenTabs ()
Temporarily moves all open tabs in this tab manager to a sidebar or restores them from a temporary state.
virtual TSharedPtr< SDockTab > TryInvokeTab (const FTabId &TabId, bool bInvokeAsInactive=false)
Try to open tab if it is closed at the last known location.
void UnregisterAllTabSpawners ()
Unregisters all tab spawners.
bool UnregisterTabSpawner (const FName TabId)
Unregisters the tab spawner matching the provided TabId.
void UpdateMainMenu (TSharedPtr< SDockTab > ForTab, const bool bForce)
Update the native, global menu bar if it is being used.
Public Member Functions inherited from TSharedFromThis< FTabManager >
TSharedRef< FTabManager, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FTabManager, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const TSharedRef< FGlobalTabmanager > & Get ()
static TSharedRef< FGlobalTabmanager > New ()
Static Public Member Functions inherited from FTabManager
static TSharedRef< FArea > NewArea (const float Width, const float Height)
static TSharedRef< FArea > NewArea (const FVector2D &WindowSize)
static TSharedRef< FLayout > NewLayout (const FName LayoutName)
static TSharedRef< FArea > NewPrimaryArea ()
static TSharedRef< FSplitter > NewSplitter ()
static TSharedRef< FStack > NewStack ()
static void RegisterDefaultTabWindowSize (const FTabId &TabName, const FVector2D DefaultSize)
static void UnregisterDefaultTabWindowSize (const FTabId &TabName)
Data Fields
FOnOverrideDockableAreaRestore OnOverrideDockableAreaRestore_Handler
Used to override dockable area restoration behavior.
Protected Member Functions
virtual void FinishRestore () override
Called at the end of RestoreFrom for tab managers to complete any work after all tabs have been restored.
virtual void OnTabClosing (const TSharedRef< SDockTab > &TabBeingClosed) override
virtual void OnTabForegrounded (const TSharedPtr< SDockTab > &NewForegroundTab, const TSharedPtr< SDockTab > &BackgroundedTab) override
Notify the tab manager that the NewForegroundTab was brought to front and the BackgroundedTab was send to the background as a result.
virtual void OnTabRelocated (const TSharedRef< SDockTab > &RelocatedTab, const TSharedPtr< SWindow > &NewOwnerWindow) override
virtual void OpenUnmanagedTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab) override
virtual void UpdateStats () override
Called when tab(s) have been added or windows created.
Protected Member Functions inherited from FTabManager
FTabManager (const TSharedPtr< SDockTab > &InOwnerTab, const TSharedRef< FTabManager::FTabSpawner > &InNomadTabSpawner)
bool CanRestoreSplitterContent (TArray< TSharedRef< class SDockingNode > > &DockingNodes, const TSharedRef< FSplitter > &SplitterNode, const TSharedPtr< SWindow > &ParentWindow, FSidebarTabLists &OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr)
Use CanRestoreSplitterContent + RestoreSplitterContent when the output of its internal RestoreArea_Helper can be a nullptr.
TSharedPtr< SDockTab > FindLastTabInWindow (TSharedPtr< SWindow > Window) const
Finds the last major or nomad tab in a particular window.
TSharedPtr< SDockingTabStack > FindPotentiallyClosedTab (const FTabId &ClosedTabId)
int32 FindTabInCollapsedAreas (const FTabMatcher &Matcher)
TSharedPtr< class SDockingTabStack > FindTabInLiveAreas (const FTabMatcher &TabMatcher) const
bool HasTabSpawnerFor (FName TabId) const
bool HasValidTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode) const
void InsertDocumentTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab, bool bPlaySpawnAnim)
void InsertDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab, bool bPlaySpawnAnim)
TSharedPtr< SDockTab > InvokeTab_Internal (const FTabId &TabId, bool bInvokeAsInactive=false, bool bForceOpenWindowIfNeeded=false)
void InvokeTabForMenu (FName TabId)
bool IsAllowedTab (const FTabId &TabId) const
bool IsAllowedTabType (const FName TabType) const
bool IsValidTabForSpawning (const FTab &SomeTab) const
void MakeSpawnerMenuEntry (FMenuBuilder &PopulateMe, const TSharedPtr< FTabSpawnerEntry > &InSpawnerNode)
virtual void OnTabOpening (const TSharedRef< SDockTab > &TabBeingOpened)
void PopulateTabSpawnerMenu_Helper (FMenuBuilder &PopulateMe, struct FPopulateTabSpawnerMenu_Args Args)
void RemoveTabFromCollapsedAreas (const FTabMatcher &Matcher)
TSharedPtr< SDockingArea > RestoreArea (const TSharedRef< FArea > &AreaToRestore, const TSharedPtr< SWindow > &InParentWindow, const bool bEmbedTitleAreaContent=false, const EOutputCanBeNullptr OutputCanBeNullptr=EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded=false)
TSharedPtr< class SDockingNode > RestoreArea_Helper (const TSharedRef< FLayoutNode > &LayoutNode, const TSharedPtr< SWindow > &ParentWindow, const bool bEmbedTitleAreaContent, FSidebarTabLists &OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr=EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded=false)
void RestoreSplitterContent (const TArray< TSharedRef< class SDockingNode > > &DockingNodes, const TSharedRef< class SDockingSplitter > &SplitterWidget)
void RestoreSplitterContent (const TSharedRef< FSplitter > &SplitterNode, const TSharedRef< class SDockingSplitter > &SplitterWidget, const TSharedPtr< SWindow > &ParentWindow, FSidebarTabLists &OutSidebarTabs)
Use this standalone RestoreSplitterContent when the output of its internal RestoreArea_Helper cannot be a nullptr.
void SetTabsTo (const TSharedRef< FTabManager::FLayoutNode > &SomeNode, const ETabState::Type NewTabState, const ETabState::Type OriginalTabState) const
It sets the desired (or all) tabs in the FTabManager::FLayoutNode to the desired value.
TSharedPtr< SDockTab > SpawnTab (const FTabId &TabId, const TSharedPtr< SWindow > &ParentWindow, const bool bCanOutputBeNullptr=false)
Protected Member Functions inherited from TSharedFromThis< FTabManager >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
FGlobalTabmanager ()
Private Attributes
TWeakPtr< SDockTab > ActiveTabPtr
The currently active tab; NULL if there is no active tab.
int32 AllAreasWindowMaxCount
Keeps track of the running-maximum number of unique parent windows in all dock areas and sub-managers during this session.
int32 AllTabsMaxCount
Keeps track of the running-maximum number of tabs in all dock areas and sub-managers during this session.
FText AppTitle
bool bCanSavePersistentLayouts
true if any layouts (across all tab managers) can be saved at this time.
bool bShouldUseMiddleEllipsisForDockTabLabel = false
Whether tabs label should use MiddleEllipsis OverflowPolicy.
TSharedPtr< FTabManager::FLayout > InitialLayoutSP
the initial layout shared pointer, which can be used to get the current layout for tabs which were not spawned on initialization
TMap< FName, FName > LegacyTabTypeRedirectionMap
A map that correlates deprecated tab types to new tab types.
FOnActiveTabChanged OnActiveTabChanged
TSharedPtr< FProxyTabmanager > ProxyTabManager
TWeakPtr< SWindow > RootWindowPtr
A window under which all of the windows in this application will nest.
TArray< FSubTabManager > SubTabManagers
FOnActiveTabChanged TabForegrounded
Additional Inherited Members
Protected Types inherited from FTabManager
typedef TMap< FName, TSharedRef< FTabSpawnerEntry > > FTabSpawner
Static Protected Member Functions inherited from FTabManager
static TSharedPtr< class SDockingTabStack > FindTabInLiveArea (const FTabMatcher &TabMatcher, const TSharedRef< SDockingArea > &InArea)
static TSharedPtr< FTabManager::FStack > FindTabUnderNode (const FTabMatcher &Matcher, const TSharedRef< FTabManager::FLayoutNode > &NodeToSearchUnder)
static void GetAllStacks (const TSharedRef< SDockingArea > &InDockArea, TArray< TSharedRef< SDockingTabStack > > &OutTabStacks)
static FVector2D GetDefaultTabWindowSize (const FTabId &TabId)
Returns the default window size for the TabId, or the fallback window size if it wasn't registered.
static bool HasAnyMatchingTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode, const TFunctionRef< bool(const FTab &)> &Matcher)
static TSharedRef< FTabManager > New (const TSharedPtr< SDockTab > &InOwnerTab, const TSharedRef< FTabSpawner > &InNomadTabSpawner)
Static Protected Member Functions inherited from TSharedFromThis< FTabManager >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FTabManager
FName ActiveLayoutName
The name of the layout being used.
bool bAllowPerWindowMenu = false
Whether or not this tab manager puts any registered menus in the windows menu bar area.
bool bCanDoDeferredLayoutSave = true
Whether or not this tab manager can perform deferred layout saves at this time; used internally to disable layout saves during drag operations.
bool bCanDoDragOperation = true
bool bEnforceMainTab = false
If true, this tab manager will always have one non-closable tab.
bool bReadOnly = false
Whether this tab manager is in a read only mode (all tabs content disabled by default - overridable per tab)
TArray< TSharedRef< FTabManager::FArea > > CollapsedDockAreas
CollapsedDockAreas refers to areas that were closed (e.g., by the user).
TArray< TWeakPtr< SDockingArea > > DockAreas
TArray< TSharedRef< FTabManager::FArea > > InvalidDockAreas
InvalidDockAreas refers to areas that were not recognized by the Editor (e.g., LiveLink when its plugin its disabled).
int32 LastDocumentUID
Instance ID for document tabs.
TWeakPtr< SWindow > LastMajorDockWindow
The last window we docked a nomad or major tab into.
TSharedPtr< FWorkspaceItem > LocalWorkspaceMenuRoot
The root for the local editor's tab spawner workspace menu.
FTabId MainNonCloseableTabID
The ID of the main tab, which cannot be closed.
TSharedPtr< FMultiBox > MenuMultiBox
The current menu multi-box for the tab, used to construct platform native main menus.
TSharedPtr< SWidget > MenuWidget
TSharedRef< FTabSpawner > NomadTabSpawner
FOnPersistLayout OnPersistLayout_Handler
Invoked when the tab manager is about to close.
FOnReadOnlyModeChanged OnReadOnlyModeChanged
Delegate that broadcasts when the tab manager enters/leaves read only mode.
TWeakPtr< SDockTab > OwnerTabPtr
A Major tab that contains this TabManager's widgets.
FTSTicker::FDelegateHandle PendingLayoutSaveHandle
Handle to a pending layout save.
TSharedPtr< const SDockTab > PendingMainNonClosableTab
To keep track of any pending tabs that want to be the main tab, but don't have their ID set yet.
TSharedRef< FPrivateApi > PrivateApi
Protected private API that must only be accessed by the docking framework internals.
TSharedRef< FNamePermissionList > TabPermissionList
Allow systems to dynamically hide tabs.
FTabSpawner TabSpawner
TArray< TWeakPtr< SDockTab > > TemporarilySidebaredTabs
Tabs which have been temporarily put in the a sidebar.
Static Protected Attributes inherited from FTabManager
static TMap< FTabId, FVector2D > DefaultTabWindowSizeMap
Default tab window sizes for newly-created tabs.
static const FVector2D FallbackWindowSize
The fallback size for a window.
Detailed Description
Definition at line 1280 of file TabManager.h.
Constructor & Destructor Documentation
FGlobalTabmanager()
FGlobalTabmanager::FGlobalTabmanager () inline private
Definition at line 1467 of file TabManager.h.
References FTabManager::FTabManager(), AllAreasWindowMaxCount, AllTabsMaxCount, bCanSavePersistentLayouts, and MakeShareable().
Referenced by New().
Member Function Documentation
AddLegacyTabType()
void FGlobalTabmanager::AddLegacyTabType (FName InLegacyTabType, FName InNewTabType)
Adds a legacy tab type to the tab type redirection map so tabs loaded with this type will be automatically converted to the new type.
CanCloseManager()
virtual bool FGlobalTabmanager::CanCloseManager (const TSet< TSharedRef< SDockTab > > & TabsToIgnore = TSet< TSharedRef< SDockTab > >()) override virtual
Check these all tabs to see if it is OK to close them.
Ignore the TabsToIgnore
Reimplemented from FTabManager.
CanSavePersistentLayouts()
bool FGlobalTabmanager::CanSavePersistentLayouts () const
Returns true if any layouts (across all tab managers) can be saved at this time.
CanSetAsActiveTab()
bool FGlobalTabmanager::CanSetAsActiveTab (const TSharedPtr< SDockTab > & Tab)
Can the manager activate this Tab as the new active tab?
DECLARE_DELEGATE()
FGlobalTabmanager::DECLARE_DELEGATE (FOnOverrideDockableAreaRestore)
DrawAttentionToTabManager()
void FGlobalTabmanager::DrawAttentionToTabManager (const TSharedRef< FTabManager > & ChildManager)
Draw the user's attention to a child tab manager.
FinishRestore()
virtual void FGlobalTabmanager::FinishRestore () override protected virtual
Called at the end of RestoreFrom for tab managers to complete any work after all tabs have been restored.
Reimplemented from FTabManager.
Get()
const TSharedRef< FGlobalTabmanager > & FGlobalTabmanager::Get () static
GetActiveTab()
TSharedPtr< SDockTab > FGlobalTabmanager::GetActiveTab () const
Returns
the currently active tab; NULL pointer if there is no active tab
GetApplicationTitle()
const FText & FGlobalTabmanager::GetApplicationTitle () const
GetInitialLayoutSP()
TSharedPtr< FTabManager::FLayout > FGlobalTabmanager::GetInitialLayoutSP ()
Gets the initial layout shared pointer, which can be used later to get the current layout for tabs which were not spawned on initialization.
GetMajorTabForTabManager()
TSharedPtr< SDockTab > FGlobalTabmanager::GetMajorTabForTabManager (const TSharedRef< FTabManager > & ChildManager)
Gets the major tab for the manager.
GetMaximumTabCount()
int32 FGlobalTabmanager::GetMaximumTabCount () const inline
Returns the highest number of tabs that were open simultaneously during this session.
Definition at line 1370 of file TabManager.h.
References AllTabsMaxCount.
GetMaximumWindowCount()
int32 FGlobalTabmanager::GetMaximumWindowCount () const inline
Returns the highest number of parent windows that were open simultaneously during this session.
Definition at line 1373 of file TabManager.h.
References AllAreasWindowMaxCount.
GetRootWindow()
TSharedPtr< SWindow > FGlobalTabmanager::GetRootWindow () const
The window under which all other windows in our app nest; might be null.
GetShouldUseMiddleEllipsisForDockTabLabel()
bool FGlobalTabmanager::GetShouldUseMiddleEllipsisForDockTabLabel () const
Get if the DockTab label should use the MiddleEllipsis overflow policy.
GetTabManagerForMajorTab()
TSharedPtr< FTabManager > FGlobalTabmanager::GetTabManagerForMajorTab (const TSharedPtr< SDockTab > DockTab) const
Gets the tab manager that a major tab owns.
The returned tab manager is the tab manager that manages the minor tabs for a major tab. Note: this is not the same as DockTab->GetTabManager(). That function returns the tab manager the major tab is in
GetTabTypeForPotentiallyLegacyTab()
FName FGlobalTabmanager::GetTabTypeForPotentiallyLegacyTab (FName InTabType) const
If the specified TabType is deprecated, returns the new replacement tab type.
Otherwise, returns InTabType
IsLegacyTabType()
bool FGlobalTabmanager::IsLegacyTabType (FName InTabType) const
Returns true if the specified tab type is registered as a legacy tab.
New()
TSharedRef< FGlobalTabmanager > FGlobalTabmanager::New () inline static
Definition at line 1323 of file TabManager.h.
References FGlobalTabmanager(), and MakeShareable().
NewTabManager()
TSharedRef< FTabManager > FGlobalTabmanager::NewTabManager (const TSharedRef< SDockTab > & InOwnerTab)
OnActiveTabChanged_Subscribe()
FDelegateHandle FGlobalTabmanager::OnActiveTabChanged_Subscribe (const FOnActiveTabChanged::FDelegate & InDelegate)
Subscribe to notifications about the active tab changing.
OnActiveTabChanged_Unsubscribe()
void FGlobalTabmanager::OnActiveTabChanged_Unsubscribe (FDelegateHandle Handle)
Unsubscribe to notifications about the active tab changing.
References Handle.
OnTabClosing()
virtual void FGlobalTabmanager::OnTabClosing (const TSharedRef< SDockTab > & TabBeingClosed) override protected virtual
Reimplemented from FTabManager.
OnTabForegrounded()
virtual void FGlobalTabmanager::OnTabForegrounded (const TSharedPtr< SDockTab > & NewForegroundTab, const TSharedPtr< SDockTab > & BackgroundedTab) override protected virtual
Notify the tab manager that the NewForegroundTab was brought to front and the BackgroundedTab was send to the background as a result.
Reimplemented from FTabManager.
OnTabForegrounded_Subscribe()
FDelegateHandle FGlobalTabmanager::OnTabForegrounded_Subscribe (const FOnActiveTabChanged::FDelegate & InDelegate)
Subscribe to notifications about a foreground tab changing.
OnTabForegrounded_Unsubscribe()
void FGlobalTabmanager::OnTabForegrounded_Unsubscribe (FDelegateHandle Handle)
Unsubscribe to notifications about a foreground tab changing.
References Handle.
OnTabManagerClosing()
virtual void FGlobalTabmanager::OnTabManagerClosing () override virtual
Invoked when a tab manager is closing down.
Reimplemented from FTabManager.
OnTabRelocated()
virtual void FGlobalTabmanager::OnTabRelocated (const TSharedRef< SDockTab > & RelocatedTab, const TSharedPtr< SWindow > & NewOwnerWindow) override protected virtual
Reimplemented from FTabManager.
OpenUnmanagedTab()
virtual void FGlobalTabmanager::OpenUnmanagedTab (FName PlaceholderId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab) override protected virtual
Reimplemented from FTabManager.
RegisterNomadTabSpawner()
FTabSpawnerEntry & FGlobalTabmanager::RegisterNomadTabSpawner (const FName TabId, const FOnSpawnTab & OnSpawnTab, const FCanSpawnTab & CanSpawnTab = FCanSpawnTab())
Register a new nomad tab spawner with the tab manager.
The spawner will be called when anyone calls InvokeTab(). A nomad tab is a tab that can be placed with major tabs or minor tabs in any tab well.
Parameters
TabId The TabId to register the spawner for.
OnSpawnTab The callback that will be used to spawn the tab.
CanSpawnTab The callback that will be used to ask if spawning the tab is allowed.
Returns
The registration entry for the spawner.
SaveAllVisualState()
void FGlobalTabmanager::SaveAllVisualState ()
Persist and serialize the layout of every TabManager and the custom visual state of every Tab.
SetActiveTab()
void FGlobalTabmanager::SetActiveTab (const TSharedPtr< SDockTab > & NewActiveTab)
Activate the NewActiveTab.
If NewActiveTab is NULL, the active tab is cleared.
SetApplicationTitle()
void FGlobalTabmanager::SetApplicationTitle (const FText & AppTitle)
References AppTitle.
SetCanSavePersistentLayouts()
void FGlobalTabmanager::SetCanSavePersistentLayouts (bool bInCanSavePersistentLayouts)
Sets whether or not any layouts (across all tab managers) can be saved at this time.
SetInitialLayoutSP()
void FGlobalTabmanager::SetInitialLayoutSP (TSharedPtr< FTabManager::FLayout > InLayout)
Sets the initial layout shared pointer, which can be used later to get the current layout for tabs which were not spawned on initialization.
Parameters
InLayout the FLayout which was loaded at layout load time
SetProxyTabManager()
void FGlobalTabmanager::SetProxyTabManager (TSharedPtr< FProxyTabmanager > InProxyTabManager)
SetRootWindow()
void FGlobalTabmanager::SetRootWindow (const TSharedRef< SWindow > InRootWindow)
Provide a window under which all other windows in this application should nest.
SetShouldUseMiddleEllipsisForDockTabLabel()
void FGlobalTabmanager::SetShouldUseMiddleEllipsisForDockTabLabel (const bool bInShouldUseMiddleEllipsis)
Set whether the DockTab label should use the MiddleEllipsis overflow policy.
UnregisterNomadTabSpawner()
void FGlobalTabmanager::UnregisterNomadTabSpawner (const FName TabId)
UpdateMainMenu()
void FGlobalTabmanager::UpdateMainMenu (const TSharedRef< SDockTab > & ForTab, bool const bForce)
Update the native, global menu bar if it is being used for a specific tab managed by the global tab manager.
Parameters
ForTab The tab to update the main menu.
bForce Used to force an update even if the parent window doesn't contain the widget with keyboard focus.
UpdateStats()
virtual void FGlobalTabmanager::UpdateStats () override protected virtual
Called when tab(s) have been added or windows created.
Reimplemented from FTabManager.
Field Documentation
ActiveTabPtr
TWeakPtr<SDockTab> FGlobalTabmanager::ActiveTabPtr private
The currently active tab; NULL if there is no active tab.
Definition at line 1478 of file TabManager.h.
AllAreasWindowMaxCount
int32 FGlobalTabmanager::AllAreasWindowMaxCount private
Keeps track of the running-maximum number of unique parent windows in all dock areas and sub-managers during this session.
Definition at line 1496 of file TabManager.h.
Referenced by FGlobalTabmanager(), and GetMaximumWindowCount().
AllTabsMaxCount
int32 FGlobalTabmanager::AllTabsMaxCount private
Keeps track of the running-maximum number of tabs in all dock areas and sub-managers during this session.
Definition at line 1493 of file TabManager.h.
Referenced by FGlobalTabmanager(), and GetMaximumTabCount().
AppTitle
FText FGlobalTabmanager::AppTitle private
Definition at line 1484 of file TabManager.h.
Referenced by SetApplicationTitle().
bCanSavePersistentLayouts
bool FGlobalTabmanager::bCanSavePersistentLayouts private
true if any layouts (across all tab managers) can be saved at this time.
Definition at line 1499 of file TabManager.h.
Referenced by FGlobalTabmanager().
bShouldUseMiddleEllipsisForDockTabLabel
bool FGlobalTabmanager::bShouldUseMiddleEllipsisForDockTabLabel = false private
Whether tabs label should use MiddleEllipsis OverflowPolicy.
Definition at line 1422 of file TabManager.h.
InitialLayoutSP
TSharedPtr<FTabManager::FLayout> FGlobalTabmanager::InitialLayoutSP private
the initial layout shared pointer, which can be used to get the current layout for tabs which were not spawned on initialization
Definition at line 1508 of file TabManager.h.
LegacyTabTypeRedirectionMap
TMap<FName, FName> FGlobalTabmanager::LegacyTabTypeRedirectionMap private
A map that correlates deprecated tab types to new tab types.
Definition at line 1490 of file TabManager.h.
OnActiveTabChanged
FOnActiveTabChanged FGlobalTabmanager::OnActiveTabChanged private
Definition at line 1480 of file TabManager.h.
OnOverrideDockableAreaRestore_Handler
FOnOverrideDockableAreaRestore FGlobalTabmanager::OnOverrideDockableAreaRestore_Handler
Used to override dockable area restoration behavior.
Definition at line 1391 of file TabManager.h.
ProxyTabManager
TSharedPtr<FProxyTabmanager> FGlobalTabmanager::ProxyTabManager private
Definition at line 1502 of file TabManager.h.
RootWindowPtr
TWeakPtr<SWindow> FGlobalTabmanager::RootWindowPtr private
A window under which all of the windows in this application will nest.
Definition at line 1487 of file TabManager.h.
SubTabManagers
TArray< FSubTabManager > FGlobalTabmanager::SubTabManagers private
Definition at line 1475 of file TabManager.h.
TabForegrounded
FOnActiveTabChanged FGlobalTabmanager::TabForegrounded private
Definition at line 1482 of file TabManager.h.
The documentation for this class was generated from the following file:
TabManager.h