Unreal Engine 5.6 C++ API: UBasicTriangleSetComponentBase Class Reference
UBasicTriangleSetComponentBase Class Reference
UBasic2DTriangleSetComponent and UBasic3DTriangleSetComponent are components that draw a set of lines as small squares.
#include "BasicTriangleSetComponent.h"
Public Member Functions
UBasicTriangleSetComponentBase ()
void ClearComponent ()
Clears the component state and marks component as dirty.
void SetTriangleMaterial (UMaterialInterface *InTriangleMaterial)
Specify material that handles lines.
void SetTriangleSetParameters (FColor InColor, const FVector3f &NormalIn)
Set per line material parameters that are uniform for all lines.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Protected Member Functions
virtual int32 GetNumMaterials () const override
template<typename CalcTriangleBoxFn>
FBoxSphereBounds UpdateComponentBounds (const FTransform &LocalToWorld, bool bTrianglesDirty, CalcTriangleBoxFn &&CalcTriangleBox) const
Update component bounds using a provided function that determines the box around all line positions.
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
bool bBoundsDirty = true
FBoxSphereBounds Bounds
FColor Color
FVector3f Normal
TObjectPtr< const UMaterialInterface > TriangleMaterial
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Additional Inherited Members
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Detailed Description
UBasic2DTriangleSetComponent and UBasic3DTriangleSetComponent are components that draw a set of lines as small squares.
The 2D version stores XY coordinates with Z set to 0 whereas the 3D version stores XYZ coordinates. All lines have the same color, size, and depth bias based on what is set via SetTriangleSetParameters(). The lines are drawn as two triangles, i.e. a square, orthogonal to the view direction. The actual line size is calculated in the shader using a custom material.
Before inserting any lines via AddElement(), the maximum number of lines that will be added needs to be declared via ReserveElements(). The actual number of lines that were added is available via NumElements().
To support both 2D and 3D with minimal code duplication, the line set components are composed from the UBasicTriangleSetComponentBase class for the component specific functionality, and an instantiation of the TBasicElementSet template class for either FVector2f or FVector3f that encapsulates all line specific functionality. The final derived classes UBasic2DTriangleSetComponent and UBasic3DTriangleSetComponent contain identical boilerplate code to facilitate calls that need to go both to the component base class and the line base class, e.g. Clear() will both mark the component as dirty and delete all lines. Base class for component specific functionality independent of the type of line stored in the component.
Definition at line 30 of file BasicTriangleSetComponent.h.
Constructor & Destructor Documentation
UBasicTriangleSetComponentBase()
UBasicTriangleSetComponentBase::UBasicTriangleSetComponentBase ()
References UBasicTriangleSetComponentBase().
Referenced by UBasicTriangleSetComponentBase().
Member Function Documentation
ClearComponent()
void UBasicTriangleSetComponentBase::ClearComponent ()
Clears the component state and marks component as dirty.
References ClearComponent().
Referenced by UBasic2DTriangleSetComponent::Clear(), UBasic3DTriangleSetComponent::Clear(), and ClearComponent().
GetNumMaterials()
virtual int32 UBasicTriangleSetComponentBase::GetNumMaterials () const inline override protected virtual
Reimplemented from UMeshComponent.
Definition at line 50 of file BasicTriangleSetComponent.h.
References GetNumMaterials().
Referenced by GetNumMaterials().
SetTriangleMaterial()
void UBasicTriangleSetComponentBase::SetTriangleMaterial (UMaterialInterface * InTriangleMaterial)
Specify material that handles lines.
References SetTriangleMaterial().
Referenced by SetTriangleMaterial().
SetTriangleSetParameters()
void UBasicTriangleSetComponentBase::SetTriangleSetParameters (FColor InColor, const FVector3f & NormalIn)
Set per line material parameters that are uniform for all lines.
References SetTriangleSetParameters().
Referenced by SetTriangleSetParameters().
UpdateComponentBounds()
template<typename CalcTriangleBoxFn> FBoxSphereBounds UBasicTriangleSetComponentBase::UpdateComponentBounds (const FTransform & LocalToWorld, bool bTrianglesDirty, CalcTriangleBoxFn && CalcTriangleBox) const inline protected
Update component bounds using a provided function that determines the box around all line positions.
This unifies how the bounds are calculated while keeping the calculation of the box around all line positions generic.
Definition at line 55 of file BasicTriangleSetComponent.h.
References bBoundsDirty, Bounds, and Box.
Referenced by UBasic2DTriangleSetComponent::CalcBounds(), and UBasic3DTriangleSetComponent::CalcBounds().
Field Documentation
bBoundsDirty
bool UBasicTriangleSetComponentBase::bBoundsDirty = true mutable protected
Definition at line 76 of file BasicTriangleSetComponent.h.
Referenced by UpdateComponentBounds().
Bounds
FBoxSphereBounds UBasicTriangleSetComponentBase::Bounds mutable protected
Definition at line 73 of file BasicTriangleSetComponent.h.
Referenced by UpdateComponentBounds().
Color
FColor UBasicTriangleSetComponentBase::Color protected
Definition at line 79 of file BasicTriangleSetComponent.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UBasicTriangleSetComponentBase::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 32 of file BasicTriangleSetComponent.h.
Normal
FVector3f UBasicTriangleSetComponentBase::Normal protected
Definition at line 82 of file BasicTriangleSetComponent.h.
TriangleMaterial
TObjectPtr<const UMaterialInterface> UBasicTriangleSetComponentBase::TriangleMaterial protected
Definition at line 70 of file BasicTriangleSetComponent.h.
The documentation for this class was generated from the following file:
BasicTriangleSetComponent.h