Unreal Engine 5.6 C++ API: HazardPointer_Impl::FHazardDeleter Class Reference
HazardPointer_Impl::FHazardDeleter Class Reference
FHazardDeleter is used to erase the type of a class so that we can call the correct destructor.
#include "HazardPointer.h"
Public Member Functions
FHazardDeleter (const FHazardDeleter &Other)
FHazardDeleter & operator= (const FHazardDeleter &Other)
bool operator== (const FHazardDeleter &Other) const
Protected Member Functions
FHazardDeleter (void *InPointer)
virtual void Delete ()
Protected Attributes
void * Pointer
Friends
class ::FHazardPointerCollection
Detailed Description
FHazardDeleter is used to erase the type of a class so that we can call the correct destructor.
Definition at line 21 of file HazardPointer.h.
Constructor & Destructor Documentation
FHazardDeleter() [1/2]
HazardPointer_Impl::FHazardDeleter::FHazardDeleter (void * InPointer) inline protected
Definition at line 27 of file HazardPointer.h.
References Pointer.
Referenced by FHazardDeleter(), FHazardPointerCollection::THazardDeleter< D >::THazardDeleter(), operator=(), and operator==().
FHazardDeleter() [2/2]
HazardPointer_Impl::FHazardDeleter::FHazardDeleter (const FHazardDeleter & Other) inline
Definition at line 35 of file HazardPointer.h.
References FHazardDeleter(), FGenericPlatformMemory::Memcpy(), and Other.
Member Function Documentation
Delete()
virtual void HazardPointer_Impl::FHazardDeleter::Delete () inline protected virtual
Reimplemented in FHazardPointerCollection::THazardDeleter< D >.
Definition at line 29 of file HazardPointer.h.
References check.
operator=()
FHazardDeleter & HazardPointer_Impl::FHazardDeleter::operator= (const FHazardDeleter & Other) inline
Definition at line 41 of file HazardPointer.h.
References FHazardDeleter(), FGenericPlatformMemory::Memcpy(), and Other.
operator==()
bool HazardPointer_Impl::FHazardDeleter::operator== (const FHazardDeleter & Other) const inline
Definition at line 48 of file HazardPointer.h.
References FHazardDeleter(), Other, and Pointer.
Friends And Related Symbol Documentation
::FHazardPointerCollection
friend class ::FHazardPointerCollection friend
Definition at line 23 of file HazardPointer.h.
Field Documentation
Pointer
void* HazardPointer_Impl::FHazardDeleter::Pointer protected
Definition at line 26 of file HazardPointer.h.
Referenced by FHazardDeleter(), FHazardPointerCollection::THazardDeleter< D >::Delete(), and operator==().
The documentation for this class was generated from the following file:
HazardPointer.h