Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator Class Reference
UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator Class Reference
#include "DynamicVector.h"
Public Member Functions
bool operator!= (const FConstIterator &Itr2) const
const Type & operator* () const
FConstIterator & operator++ ()
FConstIterator operator++ (int)
bool operator== (const FConstIterator &Itr2) const
Private Member Functions
FConstIterator (const TDynamicVector *DVectorIn, unsigned int IdxIn)
Private Attributes
const TDynamicVector * DVector {}
unsigned int Idx {0}
Friends
class TDynamicVector
Detailed Description
template<typename Type, int32 BlockSize = 512>
class UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator
Definition at line 272 of file DynamicVector.h.
Constructor & Destructor Documentation
FConstIterator()
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::FConstIterator (const TDynamicVector * DVectorIn, unsigned int IdxIn) inline private
Definition at line 301 of file DynamicVector.h.
References DVector, Idx, and TDynamicVector.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename Type, int32 BlockSize = 512> bool UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::operator!= (const FConstIterator & Itr2) const inline
Definition at line 294 of file DynamicVector.h.
References FConstIterator(), DVector, and Idx.
operator*()
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::operator* () const inline
Definition at line 275 of file DynamicVector.h.
References DVector, and Idx.
operator++() [1/2]
template<typename Type, int32 BlockSize = 512> FConstIterator & UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::operator++ () inline
Definition at line 279 of file DynamicVector.h.
References FConstIterator(), and Idx.
operator++() [2/2]
template<typename Type, int32 BlockSize = 512> FConstIterator UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::operator++ (int) inline
Definition at line 284 of file DynamicVector.h.
References FConstIterator(), Copy, and Idx.
operator==()
template<typename Type, int32 BlockSize = 512> bool UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::operator== (const FConstIterator & Itr2) const inline
Definition at line 290 of file DynamicVector.h.
References FConstIterator(), DVector, and Idx.
Friends And Related Symbol Documentation
TDynamicVector
template<typename Type, int32 BlockSize = 512> friend class TDynamicVector friend
Definition at line 300 of file DynamicVector.h.
References TDynamicVector.
Referenced by FConstIterator(), and TDynamicVector.
Field Documentation
DVector
template<typename Type, int32 BlockSize = 512> const TDynamicVector* UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::DVector {} private
Definition at line 303 of file DynamicVector.h.
Referenced by FConstIterator(), operator!=(), operator*(), and operator==().
Idx
template<typename Type, int32 BlockSize = 512> unsigned int UE::Geometry::TDynamicVector< Type, BlockSize >::FConstIterator::Idx {0} private
Definition at line 304 of file DynamicVector.h.
Referenced by FConstIterator(), operator!=(), operator*(), operator++(), operator++(), and operator==().
The documentation for this class was generated from the following file:
DynamicVector.h