Unreal Engine 5.6 C++ API: UFbxStaticMeshImportData Class Reference
UFbxStaticMeshImportData Class Reference
#include "FbxStaticMeshImportData.h"
Private Member Functions
bool CanEditChange (const FProperty *InProperty) const override
GENERATED_UCLASS_BODY () UPROPERTY()) FName StaticMeshLODGroup
The LODGroup to associate with this mesh when it is imported.
UPROPERTY()) TEnumAsByte< EVertexColorImportOption UPROPERTY ()) FColor VertexOverrideColor
Specify how vertex colors should be imported.
UPROPERTY()) uint32 bRemoveDegenerates UPROPERTY()) uint32 bBuildReversedIndexBuffer UPROPERTY()) uint32 bBuildNanite UPROPERTY()) uint32 bGenerateLightmapUVs UPROPERTY()) uint32 bOneConvexHullPerUCX UPROPERTY()) uint32 bAutoGenerateCollision UPROPERTY()) uint32 bCombineMeshes UPROPERTY ()) float DistanceFieldResolutionScale
Disabling this option will keep degenerate triangles found.
Static Private Member Functions
static UFbxStaticMeshImportData * GetImportDataForStaticMesh (UStaticMesh *StaticMesh, UFbxStaticMeshImportData *TemplateForCreation)
Gets or creates fbx import data for the specified static mesh.
Detailed Description
Definition at line 17 of file FbxStaticMeshImportData.h.
Member Function Documentation
CanEditChange()
bool UFbxStaticMeshImportData::CanEditChange (const FProperty * InProperty) const override private
References CanEditChange().
Referenced by CanEditChange().
GENERATED_UCLASS_BODY()
UFbxStaticMeshImportData::GENERATED_UCLASS_BODY () private
The LODGroup to associate with this mesh when it is imported.
References Category, config, Mesh, meta, and UPROPERTY().
GetImportDataForStaticMesh()
UFbxStaticMeshImportData * UFbxStaticMeshImportData::GetImportDataForStaticMesh (UStaticMesh * StaticMesh, UFbxStaticMeshImportData * TemplateForCreation) static private
Gets or creates fbx import data for the specified static mesh.
References GetImportDataForStaticMesh(), and StaticMesh.
Referenced by GetImportDataForStaticMesh().
UPROPERTY() [1/2]
UPROPERTY()) TEnumAsByte< EVertexColorImportOption UFbxStaticMeshImportData::UPROPERTY () private
Specify how vertex colors should be imported.
Specify override color in the case that VertexColorImportOption is set to Override
References Category, config, Mesh, meta, ToolTip, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/2]
UPROPERTY()) uint32 bRemoveDegenerates UPROPERTY()) uint32 bBuildReversedIndexBuffer UPROPERTY()) uint32 bBuildNanite UPROPERTY()) uint32 bGenerateLightmapUVs UPROPERTY()) uint32 bOneConvexHullPerUCX UPROPERTY()) uint32 bAutoGenerateCollision UPROPERTY()) uint32 bCombineMeshes UFbxStaticMeshImportData::UPROPERTY () private
Disabling this option will keep degenerate triangles found.
In general you should leave this option on. For static meshes, enabling this option will allow you to use Nanite rendering at runtime. Can only be used with simple opaque materials. If checked, one convex hull per UCX_ prefixed collision mesh will be generated instead of decomposing into multiple hulls If checked, collision will automatically be generated (ignored if custom collision is imported or used). For static meshes, enabling this option will combine all meshes in the FBX into a single monolithic mesh in Unreal Scale to apply to the mesh when allocating the distance field volume texture. The default scale is 1, which is assuming that the mesh will be placed unscaled in the world.
References Category, config, Mesh, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
FbxStaticMeshImportData.h