Unreal Engine 5.6 C++ API: UE::Geometry::FMeshVertexSelection Class Reference
UE::Geometry::FMeshVertexSelection Class Reference
#include "MeshVertexSelection.h"
Public Member Functions
FMeshVertexSelection (const FDynamicMesh3 *mesh)
GEOMETRYCORE_API FMeshVertexSelection (const FDynamicMesh3 *mesh, const FMeshEdgeSelection &convertE)
GEOMETRYCORE_API FMeshVertexSelection (const FDynamicMesh3 *mesh, const FMeshFaceSelection &convertT)
TArray< int > AsArray () const
TBitArray< FDefaultBitArrayAllocator > AsBitArray () const
TSet< int > AsSet () const
TSet< int >::TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
TSet< int >::TRangedForConstIterator begin () const
void ContractByBorderVertices (int32 nRings=1)
Remove all vertices in current selection set that have at least one neighbour vertex that is not selected (ie vertices are on border of selection)
void Deselect (int vID)
void Deselect (TArrayView< const int > Vertices)
void DeselectEdge (int eid)
void DeselectEdges (TArrayView< const int > Edges)
TSet< int >::TRangedForIterator end ()
TSet< int >::TRangedForConstIterator end () const
void ExpandToOneRingNeighbours (const TUniqueFunction< bool(int)> &FilterF=nullptr)
Add all one-ring neighbours of current selection to set.
void ExpandToOneRingNeighbours (int nRings, const TUniqueFunction< bool(int)> &FilterF=nullptr)
void FloodFill (const TArray< int > &Seeds, const TUniqueFunction< bool(int)> &VertIncludedF=nullptr)
Grow selection outwards from seed vertex, until it hits boundaries defined by vertex filter.
void FloodFill (int vSeed, const TUniqueFunction< bool(int)> &VertIncludedF=nullptr)
Grow selection outwards from seed vertex, until it hits boundaries defined by vertex filter.
bool IsSelected (int vID) const
int Num () const
void Select (int vID)
void Select (TArrayView< const int > Vertices)
template<typename PredicateFuncType>
void SelectByPosition (PredicateFuncType PredicateFunc, bool bSelectTrue=true)
Select vertices where PredicteFunc(VertexPosition) == bSelectTrue.
template<typename PredicateFuncType>
void SelectByVertexID (PredicateFuncType PredicateFunc, bool bSelectTrue=true)
Select vertices where PredicteFunc(VertexID) == bSelectTrue.
void SelectConnectedBoundaryV (int vSeed)
Select set of boundary vertices connected to vSeed.
void SelectEdgeVertices (TArrayView< const int > Edges)
GEOMETRYCORE_API void SelectInteriorVertices (const FMeshFaceSelection &triangles)
for each vertex of input triangle set, select vertex if all one-ring triangles are contained in triangle set (ie vertex is not on boundary of triangle set).
GEOMETRYCORE_API void SelectTriangleVertices (const FMeshFaceSelection &Triangles)
void SelectTriangleVertices (TArrayView< const int > Triangles)
Private Member Functions
void add (int vID)
void remove (int vID)
Private Attributes
const FDynamicMesh3 * Mesh
TSet< int > Selected
Detailed Description
Definition at line 18 of file MeshVertexSelection.h.
Constructor & Destructor Documentation
FMeshVertexSelection() [1/3]
UE::Geometry::FMeshVertexSelection::FMeshVertexSelection (const FDynamicMesh3 * mesh) inline
Definition at line 26 of file MeshVertexSelection.h.
References Mesh.
FMeshVertexSelection() [2/3]
GEOMETRYCORE_API UE::Geometry::FMeshVertexSelection::FMeshVertexSelection (const FDynamicMesh3 * mesh, const FMeshFaceSelection & convertT)
FMeshVertexSelection() [3/3]
GEOMETRYCORE_API UE::Geometry::FMeshVertexSelection::FMeshVertexSelection (const FDynamicMesh3 * mesh, const FMeshEdgeSelection & convertE)
Member Function Documentation
add()
void UE::Geometry::FMeshVertexSelection::add (int vID) inline private
Definition at line 69 of file MeshVertexSelection.h.
References Selected.
Referenced by ExpandToOneRingNeighbours(), FloodFill(), Select(), Select(), SelectByPosition(), SelectByVertexID(), SelectEdgeVertices(), and SelectTriangleVertices().
AsArray()
TArray< int > UE::Geometry::FMeshVertexSelection::AsArray () const inline
Definition at line 42 of file MeshVertexSelection.h.
References Selected.
AsBitArray()
TBitArray< FDefaultBitArrayAllocator > UE::Geometry::FMeshVertexSelection::AsBitArray () const inline
Definition at line 46 of file MeshVertexSelection.h.
References Mesh, and Selected.
AsSet()
TSet< int > UE::Geometry::FMeshVertexSelection::AsSet () const inline
Definition at line 38 of file MeshVertexSelection.h.
References Selected.
begin() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshVertexSelection::begin () inline
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 63 of file MeshVertexSelection.h.
References Selected.
begin() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshVertexSelection::begin () const inline
Definition at line 64 of file MeshVertexSelection.h.
References Selected.
ContractByBorderVertices()
void UE::Geometry::FMeshVertexSelection::ContractByBorderVertices (int32 nRings = 1) inline
Remove all vertices in current selection set that have at least one neighbour vertex that is not selected (ie vertices are on border of selection)
Definition at line 272 of file MeshVertexSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), Deselect(), IsSelected(), Mesh, TArray< InElementType, InAllocatorType >::Reset(), and Selected.
Deselect() [1/2]
void UE::Geometry::FMeshVertexSelection::Deselect (int vID) inline
Definition at line 198 of file MeshVertexSelection.h.
References remove().
Referenced by ContractByBorderVertices().
Deselect() [2/2]
void UE::Geometry::FMeshVertexSelection::Deselect (TArrayView< const int > Vertices) inline
Definition at line 202 of file MeshVertexSelection.h.
References remove(), and UE::Geometry::Vertices.
DeselectEdge()
void UE::Geometry::FMeshVertexSelection::DeselectEdge (int eid) inline
Definition at line 209 of file MeshVertexSelection.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, Mesh, and remove().
DeselectEdges()
void UE::Geometry::FMeshVertexSelection::DeselectEdges (TArrayView< const int > Edges) inline
Definition at line 215 of file MeshVertexSelection.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, Mesh, and remove().
end() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshVertexSelection::end () inline
Definition at line 65 of file MeshVertexSelection.h.
References Selected.
end() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshVertexSelection::end () const inline
Definition at line 66 of file MeshVertexSelection.h.
References Selected.
ExpandToOneRingNeighbours() [1/2]
void UE::Geometry::FMeshVertexSelection::ExpandToOneRingNeighbours (const TUniqueFunction< bool(int)> & FilterF = nullptr) inline
Add all one-ring neighbours of current selection to set.
On a large selection this is quite expensive as we don't know the boundary, so we have to iterate over all selected vertices.
Return false from FilterF to prevent vertices from being included.
Definition at line 232 of file MeshVertexSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), add(), ID, IsSelected(), Mesh, and Selected.
Referenced by ExpandToOneRingNeighbours().
ExpandToOneRingNeighbours() [2/2]
void UE::Geometry::FMeshVertexSelection::ExpandToOneRingNeighbours (int nRings, const TUniqueFunction< bool(int)> & FilterF = nullptr) inline
Definition at line 259 of file MeshVertexSelection.h.
References ExpandToOneRingNeighbours().
FloodFill() [1/2]
void UE::Geometry::FMeshVertexSelection::FloodFill (const TArray< int > & Seeds, const TUniqueFunction< bool(int)> & VertIncludedF = nullptr) inline
Grow selection outwards from seed vertex, until it hits boundaries defined by vertex filter.
Definition at line 313 of file MeshVertexSelection.h.
References UE::Geometry::TDynamicVector< Type, BlockSize >::Add(), add(), UE::Geometry::TDynamicVector< Type, BlockSize >::Back(), IsSelected(), Mesh, UE::Geometry::TDynamicVector< Type, BlockSize >::Num(), UE::Geometry::TDynamicVector< Type, BlockSize >::PopBack(), and Seed.
FloodFill() [2/2]
void UE::Geometry::FMeshVertexSelection::FloodFill (int vSeed, const TUniqueFunction< bool(int)> & VertIncludedF = nullptr) inline
Grow selection outwards from seed vertex, until it hits boundaries defined by vertex filter.
Definition at line 305 of file MeshVertexSelection.h.
References FloodFill().
Referenced by FloodFill().
IsSelected()
bool UE::Geometry::FMeshVertexSelection::IsSelected (int vID) const inline
Definition at line 84 of file MeshVertexSelection.h.
References Selected.
Referenced by ContractByBorderVertices(), ExpandToOneRingNeighbours(), and FloodFill().
Num()
int UE::Geometry::FMeshVertexSelection::Num () const inline
Definition at line 79 of file MeshVertexSelection.h.
References Selected.
remove()
void UE::Geometry::FMeshVertexSelection::remove (int vID) inline private
Definition at line 73 of file MeshVertexSelection.h.
References Selected.
Referenced by Deselect(), Deselect(), DeselectEdge(), and DeselectEdges().
Select() [1/2]
void UE::Geometry::FMeshVertexSelection::Select (int vID) inline
Definition at line 89 of file MeshVertexSelection.h.
References add(), ensure, and Mesh.
Select() [2/2]
void UE::Geometry::FMeshVertexSelection::Select (TArrayView< const int > Vertices) inline
Definition at line 97 of file MeshVertexSelection.h.
References add(), Mesh, and UE::Geometry::Vertices.
SelectByPosition()
template<typename PredicateFuncType> void UE::Geometry::FMeshVertexSelection::SelectByPosition (PredicateFuncType PredicateFunc, bool bSelectTrue = true) inline
Select vertices where PredicteFunc(VertexPosition) == bSelectTrue.
Definition at line 128 of file MeshVertexSelection.h.
References add(), and Mesh.
SelectByVertexID()
template<typename PredicateFuncType> void UE::Geometry::FMeshVertexSelection::SelectByVertexID (PredicateFuncType PredicateFunc, bool bSelectTrue = true) inline
Select vertices where PredicteFunc(VertexID) == bSelectTrue.
Definition at line 112 of file MeshVertexSelection.h.
References add(), and Mesh.
SelectConnectedBoundaryV()
void UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV (int vSeed) inline
Select set of boundary vertices connected to vSeed.
Definition at line 162 of file MeshVertexSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Contains(), ensureMsgf, Mesh, No, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Pop(), Selected, and TEXT.
SelectEdgeVertices()
void UE::Geometry::FMeshVertexSelection::SelectEdgeVertices (TArrayView< const int > Edges) inline
Definition at line 188 of file MeshVertexSelection.h.
References UE::Geometry::FIndex2i::A, add(), UE::Geometry::FIndex2i::B, and Mesh.
SelectInteriorVertices()
GEOMETRYCORE_API void UE::Geometry::FMeshVertexSelection::SelectInteriorVertices (const FMeshFaceSelection & triangles)
for each vertex of input triangle set, select vertex if all one-ring triangles are contained in triangle set (ie vertex is not on boundary of triangle set).
SelectTriangleVertices() [1/2]
GEOMETRYCORE_API void UE::Geometry::FMeshVertexSelection::SelectTriangleVertices (const FMeshFaceSelection & Triangles)
SelectTriangleVertices() [2/2]
void UE::Geometry::FMeshVertexSelection::SelectTriangleVertices (TArrayView< const int > Triangles) inline
Definition at line 141 of file MeshVertexSelection.h.
References UE::Geometry::FIndex3i::A, add(), UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, and Mesh.
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FMeshVertexSelection::Mesh private
Definition at line 21 of file MeshVertexSelection.h.
Referenced by FMeshVertexSelection(), AsBitArray(), ContractByBorderVertices(), DeselectEdge(), DeselectEdges(), ExpandToOneRingNeighbours(), FloodFill(), Select(), Select(), SelectByPosition(), SelectByVertexID(), SelectConnectedBoundaryV(), SelectEdgeVertices(), and SelectTriangleVertices().
Selected
TSet<int> UE::Geometry::FMeshVertexSelection::Selected private
Definition at line 23 of file MeshVertexSelection.h.
Referenced by add(), AsArray(), AsBitArray(), AsSet(), begin(), begin(), ContractByBorderVertices(), end(), end(), ExpandToOneRingNeighbours(), IsSelected(), Num(), remove(), and SelectConnectedBoundaryV().
The documentation for this class was generated from the following file:
MeshVertexSelection.h