Unreal Engine 5.6 C++ API: FTransaction Class Reference
FTransaction Class Reference
Base class for tracking transactions for undo/redo.
#include "Transactor.h"
Data Structures
struct FChangedObjectValue
class FObjectRecord
struct FObjectRecords
struct FPackageRecord
Public Member Functions
FTransaction (const TCHAR *InContext=nullptr, const FText &InTitle=FText(), bool bInFlip=false)
virtual ~FTransaction ()
UNREALED_API void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
virtual UNREALED_API void Apply () override
Enacts the transaction.
virtual UNREALED_API void BeginOperation () override
BeginOperation should be called when a transaction or undo/redo starts.
virtual UNREALED_API bool ContainsObject (const UObject *Object) const override
Does the transaction know that the object is being modified.
virtual UNREALED_API bool ContainsPieObjects () const override
UNREALED_API SIZE_T DataSize () const
UNREALED_API void DumpObjectMap (FOutputDevice &Ar) const
Outputs the contents of the ObjectMap to the specified output device.
virtual UNREALED_API void EndOperation () override
EndOperation should be called when a transaction is finalized or canceled or undo/redo ends.
virtual UNREALED_API void Finalize () override
Finalize the transaction (try and work out what's changed).
UNREALED_API FTransactionDiff GenerateDiff () const
Create a map that holds information about objects of a given transaction compared to the current state of the object.
virtual FTransactionContext GetContext () const override
Gets the full context for the transaction.
FText GetDescription () const
Returns the description of each contained Object Record.
UNREALED_API FTransactionDiff GetHistoricDiff () const
Create a map that holds information about objects of a given transaction compared to their previous state the last time this transaction was applied to those objects (via PostTransacted).
FGuid GetId () const
Returns the unique identifier for this transaction, used to track it during its lifetime.
FGuid GetOperationId () const
Returns the unique identifier for the active operation on this transaction (if any)
const UObject * GetPrimaryObject () const
UNREALED_API int32 GetRecordCount () const
FText GetTitle () const
Returns the descriptive text for the transaction.
UNREALED_API void GetTransactionObjects (TArray< UObject * > &Objects) const
Get all the objects that are part of this transaction.
virtual const TCHAR * GetTransactionType () const
Returns a unique string to serve as a type ID for the FTranscationBase-derived type.
virtual UNREALED_API bool HasExpired () const
UNREALED_API bool IsObjectTransacting (const UObject *Object) const
Checks if a specific object is in the transaction currently underway.
virtual UNREALED_API bool IsTransient () const override
virtual UNREALED_API void SaveArray (UObject *Object, FScriptArray *Array, int32 Index, int32 Count, int32 Oper, int32 ElementSize, uint32 ElementAlignment, STRUCT_DC DefaultConstructor, STRUCT_AR Serializer, STRUCT_DTOR Destructor) override
Saves an array to the transaction.
virtual UNREALED_API void SaveObject (UObject *Object) override
Saves an UObject to the transaction.
virtual UNREALED_API void SetPrimaryObject (UObject *InObject) override
Sets the transaction's primary object.
virtual UNREALED_API void SnapshotObject (UObject *InObject, TArrayView< const FProperty * > Properties) override
Snapshots a UObject within the transaction.
virtual UNREALED_API void StoreUndo (UObject *Object, TUniquePtr< FChange > UndoChange) override
Stores a command that can be used to undo a change to the specified object.
Protected Attributes
bool bFlip = true
If true, on apply flip the direction of iteration over object records.
TMap< UObject *, FChangedObjectValue > ChangedObjects
Objects that will be changed directly by the transaction, empty when not transacting.
FString Context
A text string describing the context for the transaction.
TMap< FName, TSharedPtr< FTransactionObjectEvent > > HistoricDiffMap
Cached state of the diff the last time this transaction was applied to an object (via PostTransacted for non-snapshot transactions) to allow historic introspection of the diff regardless of the current state of the object.
FGuid Id
Unique identifier for this transaction, used to track it during its lifetime.
int32 Inc = -1
Used to track direction to iterate over transaction's object records.
TMap< UE::Transaction::FPersistentObjectRef, FObjectRecords > ObjectRecordsMap
Map of object records (non-array), for optimized look-up and to prevent an object being serialized to a transaction more than once.
FGuid OperationId
Unique identifier for the active operation on this transaction (if any).
TMap< UE::Transaction::FPersistentObjectRef, FPackageRecord > PackageRecordMap
Map of package records for tracking and restoring the dirty state of packages on undo/redo.
UObject * PrimaryObject = nullptr
The key object being edited in this transaction.
TIndirectArray< FObjectRecord > Records
List of object records in this transaction.
FText Title
Description of the transaction.
Private Member Functions
FTransaction (const FTransaction &)=delete
FTransaction & operator= (const FTransaction &)=delete
void PostTransactAndSaveHistoricDiff (UObject *Obj, FTransactionObjectEvent &&TransactionEvent)
UNREALED_API void SavePackage (UPackage *Package)
Friends
class FObjectRecord
class FObjectRecord::FReader
class FObjectRecord::FWriter
class FTransactionObjectEvent
FArchive & operator<< (FArchive &Ar, FTransaction &T)
Serializes a reference to a transaction in a given archive.
FArchive & operator<< (FArchive &Ar, FTransaction::FObjectRecord &R)
FArchive & operator<< (FArchive &Ar, TSharedRef< FTransaction > &SharedT)
Serializes a reference to a transaction in a given archive.
Detailed Description
Base class for tracking transactions for undo/redo.
A single transaction, representing a set of serialized, undo-able changes to a set of objects.
warning: The undo buffer cannot be made persistent because of its dependence on offsets of arrays from their owning UObjects.
warning: UObject::Serialize implicitly assumes that class properties do not change in between transaction resets.
Definition at line 36 of file Transactor.h.
Constructor & Destructor Documentation
FTransaction() [1/2]
FTransaction::FTransaction (const TCHAR * InContext = nullptr, const FText & InTitle = FText(), bool bInFlip = false) inline
Definition at line 330 of file Transactor.h.
References bFlip, Context, Id, and Title.
Referenced by FTransaction::FObjectRecord::FObjectRecord(), FTransaction::FObjectRecord::FReader::FReader(), FTransaction(), FTransaction::FObjectRecord::Finalize(), FTransaction::FObjectRecord::Load(), operator<<, operator=(), FTransaction::FObjectRecord::Restore(), FTransaction::FObjectRecord::Save(), and FTransaction::FObjectRecord::Snapshot().
~FTransaction()
virtual FTransaction::~FTransaction () inline virtual
Definition at line 338 of file Transactor.h.
FTransaction() [2/2]
FTransaction::FTransaction (const FTransaction &) private delete
References FTransaction().
Member Function Documentation
AddReferencedObjects()
UNREALED_API void FTransaction::AddReferencedObjects (FReferenceCollector & Collector)
Used by GC to collect referenced objects.
Apply()
virtual UNREALED_API void FTransaction::Apply () override virtual
Enacts the transaction.
Implements ITransaction.
BeginOperation()
virtual UNREALED_API void FTransaction::BeginOperation () override virtual
BeginOperation should be called when a transaction or undo/redo starts.
Implements ITransaction.
ContainsObject()
virtual UNREALED_API bool FTransaction::ContainsObject (const UObject * Object) const override virtual
Does the transaction know that the object is being modified.
Implements ITransaction.
References Object.
ContainsPieObjects()
virtual UNREALED_API bool FTransaction::ContainsPieObjects () const override virtual
Returns
True if this record contains a reference to a pie object
Implements ITransaction.
DataSize()
UNREALED_API SIZE_T FTransaction::DataSize () const
DumpObjectMap()
UNREALED_API void FTransaction::DumpObjectMap (FOutputDevice & Ar) const
Outputs the contents of the ObjectMap to the specified output device.
References Ar.
EndOperation()
virtual UNREALED_API void FTransaction::EndOperation () override virtual
EndOperation should be called when a transaction is finalized or canceled or undo/redo ends.
Implements ITransaction.
Finalize()
virtual UNREALED_API void FTransaction::Finalize () override virtual
Finalize the transaction (try and work out what's changed).
Implements ITransaction.
GenerateDiff()
UNREALED_API FTransactionDiff FTransaction::GenerateDiff () const
Create a map that holds information about objects of a given transaction compared to the current state of the object.
GetContext()
virtual FTransactionContext FTransaction::GetContext () const inline override virtual
Gets the full context for the transaction.
Implements ITransaction.
Definition at line 378 of file Transactor.h.
References Context, Id, OperationId, PrimaryObject, and Title.
GetDescription()
FText FTransaction::GetDescription () const inline
Returns the description of each contained Object Record.
Definition at line 421 of file Transactor.h.
References FText::FromString(), GetTitle(), Record, Records, and TEXT.
GetHistoricDiff()
UNREALED_API FTransactionDiff FTransaction::GetHistoricDiff () const
Create a map that holds information about objects of a given transaction compared to their previous state the last time this transaction was applied to those objects (via PostTransacted).
GetId()
FGuid FTransaction::GetId () const inline
Returns the unique identifier for this transaction, used to track it during its lifetime.
Definition at line 403 of file Transactor.h.
References Id.
GetOperationId()
FGuid FTransaction::GetOperationId () const inline
Returns the unique identifier for the active operation on this transaction (if any)
Definition at line 409 of file Transactor.h.
References OperationId.
GetPrimaryObject()
const UObject * FTransaction::GetPrimaryObject () const inline
Definition at line 480 of file Transactor.h.
References PrimaryObject.
GetRecordCount()
UNREALED_API int32 FTransaction::GetRecordCount () const
GetTitle()
FText FTransaction::GetTitle () const inline
Returns the descriptive text for the transaction.
Definition at line 415 of file Transactor.h.
References Title.
Referenced by GetDescription().
GetTransactionObjects()
UNREALED_API void FTransaction::GetTransactionObjects (TArray< UObject * > & Objects) const
Get all the objects that are part of this transaction.
Parameters
Objects [out] Receives the object list. Previous contents are cleared.
GetTransactionType()
virtual const TCHAR * FTransaction::GetTransactionType () const inline virtual
Returns a unique string to serve as a type ID for the FTranscationBase-derived type.
Definition at line 394 of file Transactor.h.
References TEXT.
HasExpired()
virtual UNREALED_API bool FTransaction::HasExpired () const virtual
Returns
true if the transaction contains custom changes and all the changes have expired
IsObjectTransacting()
UNREALED_API bool FTransaction::IsObjectTransacting (const UObject * Object) const
Checks if a specific object is in the transaction currently underway.
References Object.
IsTransient()
virtual UNREALED_API bool FTransaction::IsTransient () const override virtual
Returns
true if the transaction is transient.
Implements ITransaction.
operator=()
FTransaction & FTransaction::operator= (const FTransaction &) private delete
References FTransaction().
PostTransactAndSaveHistoricDiff()
void FTransaction::PostTransactAndSaveHistoricDiff (UObject * Obj, FTransactionObjectEvent && TransactionEvent) private
References FTransactionObjectEvent.
SaveArray()
virtual UNREALED_API void FTransaction::SaveArray (UObject * Object, FScriptArray * Array, int32 Index, int32 Count, int32 Oper, int32 ElementSize, uint32 ElementAlignment, STRUCT_DC DefaultConstructor, STRUCT_AR Serializer, STRUCT_DTOR Destructor) override virtual
Saves an array to the transaction.
Parameters
Object The object that owns the array.
Array The array to save.
Index
Count
Oper
ElementSize
ElementAlignment
Serializer
Destructor
See also
SaveObject
Implements ITransaction.
References Array, Count, and Object.
SaveObject()
virtual UNREALED_API void FTransaction::SaveObject (UObject * Object) override virtual
Saves an UObject to the transaction.
Parameters
Object The object to save.
See also
SaveArray
Implements ITransaction.
References Object.
SavePackage()
UNREALED_API void FTransaction::SavePackage (UPackage * Package) private
References Package.
SetPrimaryObject()
virtual UNREALED_API void FTransaction::SetPrimaryObject (UObject * Object) override virtual
Sets the transaction's primary object.
Parameters
Object The primary object to set.
Implements ITransaction.
SnapshotObject()
virtual UNREALED_API void FTransaction::SnapshotObject (UObject * Object, TArrayView< const FProperty * > Properties) override virtual
Snapshots a UObject within the transaction.
Parameters
Object The object to snapshot.
Property The optional list of properties that have potentially changed on the object (to avoid snapshotting the entire object).
Implements ITransaction.
StoreUndo()
virtual UNREALED_API void FTransaction::StoreUndo (UObject * Object, TUniquePtr< FChange > CustomChange) override virtual
Stores a command that can be used to undo a change to the specified object.
This may be called multiple times in the same transaction to stack up changes that will be rolled back in reverse order. No copy of the object itself is stored.
Parameters
Object The object the undo change will apply to
CustomChange The change that can be used to undo the changes to this object.
Implements ITransaction.
References Object.
Friends And Related Symbol Documentation
FObjectRecord
friend class FObjectRecord friend
Definition at line 506 of file Transactor.h.
FObjectRecord::FReader
friend class FObjectRecord::FReader friend
Definition at line 507 of file Transactor.h.
FObjectRecord::FWriter
friend class FObjectRecord::FWriter friend
Definition at line 508 of file Transactor.h.
FTransactionObjectEvent
friend class FTransactionObjectEvent friend
Definition at line 38 of file Transactor.h.
References FTransactionObjectEvent.
Referenced by FTransactionObjectEvent, and PostTransactAndSaveHistoricDiff().
operator<< [1/3]
FArchive & operator<< (FArchive & Ar, FTransaction & T) friend
Serializes a reference to a transaction in a given archive.
Definition at line 442 of file Transactor.h.
References FTransaction(), Ar, Record, and FTransaction::FObjectRecords::Records.
operator<< [2/3]
FArchive & operator<< (FArchive & Ar, FTransaction::FObjectRecord & R) friend
References Ar, and R.
operator<< [3/3]
FArchive & operator<< (FArchive & Ar, TSharedRef< FTransaction > & SharedT) friend
Serializes a reference to a transaction in a given archive.
Definition at line 465 of file Transactor.h.
References Ar, and TSharedRef< ObjectType, InMode >::Get().
Field Documentation
bFlip
bool FTransaction::bFlip = true protected
If true, on apply flip the direction of iteration over object records.
Definition at line 300 of file Transactor.h.
Referenced by FTransaction().
ChangedObjects
TMap<UObject*, FChangedObjectValue> FTransaction::ChangedObjects protected
Objects that will be changed directly by the transaction, empty when not transacting.
Definition at line 323 of file Transactor.h.
Context
FString FTransaction::Context protected
A text string describing the context for the transaction.
Typically the name of the system causing the transaction
Definition at line 294 of file Transactor.h.
Referenced by FTransaction(), and GetContext().
HistoricDiffMap
TMap<FName, TSharedPtr<FTransactionObjectEvent> > FTransaction::HistoricDiffMap protected
Cached state of the diff the last time this transaction was applied to an object (via PostTransacted for non-snapshot transactions) to allow historic introspection of the diff regardless of the current state of the object.
Definition at line 326 of file Transactor.h.
Id
FGuid FTransaction::Id protected
Unique identifier for this transaction, used to track it during its lifetime.
Definition at line 281 of file Transactor.h.
Referenced by FTransaction(), GetContext(), and GetId().
Inc
int32 FTransaction::Inc = -1 protected
Used to track direction to iterate over transaction's object records.
Typically -1 for Undo, 1 for Redo
Definition at line 304 of file Transactor.h.
ObjectRecordsMap
TMap<UE::Transaction::FPersistentObjectRef, FObjectRecords> FTransaction::ObjectRecordsMap protected
Map of object records (non-array), for optimized look-up and to prevent an object being serialized to a transaction more than once.
Definition at line 275 of file Transactor.h.
OperationId
FGuid FTransaction::OperationId protected
Unique identifier for the active operation on this transaction (if any).
This is set by a call to BeginOperation and cleared by a call to EndOperation. BeginOperation should be called when a transaction or undo/redo starts, and EndOperation should be called when a transaction is finalized or canceled or undo/redo ends.
Definition at line 288 of file Transactor.h.
Referenced by GetContext(), and GetOperationId().
PackageRecordMap
TMap<UE::Transaction::FPersistentObjectRef, FPackageRecord> FTransaction::PackageRecordMap protected
Map of package records for tracking and restoring the dirty state of packages on undo/redo.
The package itself may also be stored in ObjectRecordsMap.
Definition at line 278 of file Transactor.h.
PrimaryObject
UObject* FTransaction::PrimaryObject = nullptr protected
The key object being edited in this transaction.
For example the blueprint object. Can be NULL
Definition at line 297 of file Transactor.h.
Referenced by GetContext(), and GetPrimaryObject().
Records
TIndirectArray<FObjectRecord> FTransaction::Records protected
List of object records in this transaction.
Definition at line 272 of file Transactor.h.
Referenced by GetDescription().
Title
FText FTransaction::Title protected
Description of the transaction.
Can be used by UI
Definition at line 291 of file Transactor.h.
Referenced by FTransaction(), GetContext(), and GetTitle().
The documentation for this class was generated from the following file:
Transactor.h