Unreal Engine 5.6 C++ API: FIoOffsetAndLength Struct Reference
FIoOffsetAndLength Struct Reference
Combined offset and length.
#include "IoOffsetLength.h"
Public Member Functions
FIoOffsetAndLength ()=default
FIoOffsetAndLength (const uint64 Offset, const uint64 Length)
uint64 GetLength () const
uint64 GetOffset () const
void SetLength (uint64 Length)
void SetOffset (uint64 Offset)
Private Attributes
uint8 OffsetAndLength [5+5]
Detailed Description
Combined offset and length.
Definition at line 10 of file IoOffsetLength.h.
Constructor & Destructor Documentation
FIoOffsetAndLength() [1/2]
FIoOffsetAndLength::FIoOffsetAndLength () default
FIoOffsetAndLength() [2/2]
FIoOffsetAndLength::FIoOffsetAndLength (const uint64 Offset, const uint64 Length) inline explicit
Definition at line 14 of file IoOffsetLength.h.
References SetLength(), and SetOffset().
Member Function Documentation
GetLength()
uint64 FIoOffsetAndLength::GetLength () const inline
Definition at line 30 of file IoOffsetLength.h.
References OffsetAndLength.
GetOffset()
uint64 FIoOffsetAndLength::GetOffset () const inline
Definition at line 20 of file IoOffsetLength.h.
References OffsetAndLength.
SetLength()
void FIoOffsetAndLength::SetLength (uint64 Length) inline
Definition at line 49 of file IoOffsetLength.h.
References OffsetAndLength.
Referenced by FIoOffsetAndLength().
SetOffset()
void FIoOffsetAndLength::SetOffset (uint64 Offset) inline
Definition at line 40 of file IoOffsetLength.h.
References OffsetAndLength.
Referenced by FIoOffsetAndLength().
Field Documentation
OffsetAndLength
uint8 FIoOffsetAndLength::OffsetAndLength[5+5] private
Definition at line 61 of file IoOffsetLength.h.
Referenced by GetLength(), GetOffset(), SetLength(), and SetOffset().
The documentation for this struct was generated from the following file:
IoOffsetLength.h