Unreal Engine 5.6 C++ API: UE::Geometry::TMeshLocalParam< PointSetType > Class Template Reference
UE::Geometry::TMeshLocalParam< PointSetType > Class Template Reference
TMeshLocalParam computes a local UV parameterization of a set of connected PointsWithNormals, where "local" means "in a geodesic disc around a starting point".
#include "MeshLocalParam.h"
Data Structures
struct FGraphNode
Public Member Functions
TMeshLocalParam (const PointSetType *PointSetIn)
void ApplyUVs (TFunctionRef< void(int32 PointID, const FVector2d &UV)> ApplyFunc) const
Apply a function to each calculated UV.
void ComputeToMaxDistance (const FFrame3d &SeedFrameIn, const FIndex3i &SeedNbrs, double ComputeToMaxDistanceIn)
Computes UVs outwards from seed frame/nbrs to all points that are less/equal to ComputeToMaxDistance from the seed.
void ComputeToMaxDistance (int32 CenterPointVtxID, const FFrame3d &CenterPointFrame, double ComputeToMaxDistanceIn)
Computes UVs outwards from seed vertex to all points that are less/equal to ComputeToMaxDistance from the seed.
void GetAllComputedUVs (TArray< int32 > &PointIDsOut, TArray< FVector2d > &PointUVsOut, double MaxUVMagnitude=TNumericLimits< float >::Max(), double MaxGraphDist=TNumericLimits< float >::Max()) const
Find all computed UVs within the specified distances.
double GetMaxGraphDistance () const
double GetMaxUVDistance () const
void GetPointsWithUV (TArray< int32 > &Points) const
FVector2d GetUV (int32 PointID) const
FAxisAlignedBox2d GetUVBounds () const
bool HasUV (int32 PointID) const
void Reset ()
Reset internal data structures but keep allocated memory.
void TransformUV (double Scale, FVector2d Translate)
Scale and then Translate all calculated UV values.
Data Fields
bool bEnableExternalNormals = false
If true, ExternalNormalFunc will be used to fetch normals instead of requesting from PointSet->GetVertexNormal.
TFunction< FVector3d(int32)> ExternalNormalFunc
Normals will be requested from this function if bEnableExternalNormals == true.
ELocalParamTypes ParamMode = ELocalParamTypes::ExponentialMapUpwindAvg
Type of local parameterization to compute.
const PointSetType * PointSet
Protected Member Functions
FVector2d ComputeLocalUV (const FFrame3d &Frame, FVector3d Position) const
FFrame3d GetFrame (const FGraphNode &Node) const
const FGraphNode * GetNodeForPointSetID (int32 PointSetID) const
FGraphNode * GetNodeForPointSetID (int32 PointSetID, bool bCreateIfMissing)
FVector3d GetNormal (const int32 PointID) const
FVector3d GetPosition (const int32 PointID) const
void ProcessQueueUntilTermination (double MaxDistance)
FVector2d PropagateUV (const FVector3d &Position, const FVector2d &NbrUV, const FFrame3d &NbrFrame, const FFrame3d &SeedFrameIn) const
void UpdateNeighboursSparse (FGraphNode *Parent)
void UpdateUVExpmap (FGraphNode &Node)
void UpdateUVExpmapUpwind (FGraphNode &Node)
void UpdateUVPlanar (FGraphNode &Node)
Static Protected Member Functions
static FVector2d InvalidUV ()
Protected Attributes
TDynamicVector< FGraphNode > AllocatedNodes
TMap< int32, int32 > IDToNodeIndexMap
double MaxGraphDistance
double MaxUVDistance
FIndexPriorityQueue Queue
FFrame3d SeedFrame
Detailed Description
template<class PointSetType>
class UE::Geometry::TMeshLocalParam< PointSetType >
TMeshLocalParam computes a local UV parameterization of a set of connected PointsWithNormals, where "local" means "in a geodesic disc around a starting point".
The computation is based on region-growing, and geodesic distances are actually graph distances, measured with Dijkstras algorithm.
Templated on the point set type, which must provide positions, normals, and neighbours. Currently will only work for FDynamicMesh3 and FDynamicPointSet3 because of call to PointSetType->VtxVerticesItr()
Definition at line 42 of file MeshLocalParam.h.
Constructor & Destructor Documentation
TMeshLocalParam()
template<class PointSetType> UE::Geometry::TMeshLocalParam< PointSetType >::TMeshLocalParam (const PointSetType * PointSetIn) inline
Definition at line 61 of file MeshLocalParam.h.
References MaxGraphDistance, MaxUVDistance, PointSet, and Queue.
Member Function Documentation
ApplyUVs()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::ApplyUVs (TFunctionRef< void(int32 PointID, const FVector2d &UV)> ApplyFunc) const inline
Apply a function to each calculated UV.
Definition at line 232 of file MeshLocalParam.h.
References AllocatedNodes, and UV.
ComputeLocalUV()
template<class PointSetType> FVector2d UE::Geometry::TMeshLocalParam< PointSetType >::ComputeLocalUV (const FFrame3d & Frame, FVector3d Position) const inline protected
Definition at line 372 of file MeshLocalParam.h.
References UE::Geometry::Position, and UV.
Referenced by ComputeToMaxDistance(), PropagateUV(), and UpdateUVPlanar().
ComputeToMaxDistance() [1/2]
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::ComputeToMaxDistance (const FFrame3d & SeedFrameIn, const FIndex3i & SeedNbrs, double ComputeToMaxDistanceIn) inline
Computes UVs outwards from seed frame/nbrs to all points that are less/equal to ComputeToMaxDistance from the seed.
Parameters
SeedFrameIn 3D frame on surface of point set, parameterization is computed "in" this frame (eg will align u/v to x/y axes, at origin)
SeedNbrs 3 points that will be planar-projected into the SeedFrame, to initialize the region-growing (kind of triangle-mesh-specific)
ComputeToMaxDistanceIn target radius for parameterization, will not set UVs on points with graph-distance larger than this
Definition at line 92 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, check, ComputeLocalUV(), GetNodeForPointSetID(), GetPosition(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::GraphDistance, UE::Math::TVector2< T >::Length(), MaxGraphDistance, MaxUVDistance, ProcessQueueUntilTermination(), Queue, SeedFrame, and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV.
ComputeToMaxDistance() [2/2]
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::ComputeToMaxDistance (int32 CenterPointVtxID, const FFrame3d & CenterPointFrame, double ComputeToMaxDistanceIn) inline
Computes UVs outwards from seed vertex to all points that are less/equal to ComputeToMaxDistance from the seed.
Parameters
CenterPointVtxID ID of seed vertex
CenterPointFrame 3D frame on surface of point set, parameterization is computed "in" this frame (eg will align u/v to x/y axes, at origin)
ComputeToMaxDistanceIn target radius for parameterization, will not set UVs on points with graph-distance larger than this
Definition at line 119 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, GetNodeForPointSetID(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::GraphDistance, MaxGraphDistance, MaxUVDistance, ProcessQueueUntilTermination(), Queue, SeedFrame, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV, and UE::Math::TVector2< double >::Zero().
GetAllComputedUVs()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::GetAllComputedUVs (TArray< int32 > & PointIDsOut, TArray< FVector2d > & PointUVsOut, double MaxUVMagnitude = TNumericLimits<float>::Max(), double MaxGraphDist = TNumericLimits<float>::Max()) const inline
Find all computed UVs within the specified distances.
Parameters
PointIDsOut PointID corresponding to each computed UV is returned here
PointUVsOut UV value corresponding to each PointID is returned here
MaxUVMagnitude computed UVs will only be included if their magnitude is smaller than this value (eg, this is the UV-space radius)
MaxGraphDistance computed UVs will only be included if their graph distance is smaller than this value. Graph distance is generally always be larger than UV distance. This can be used to avoid problematic UVs that might result from algorithm failures.
Definition at line 210 of file MeshLocalParam.h.
References TArray< InElementType, InAllocatorType >::Add(), and AllocatedNodes.
GetFrame()
template<class PointSetType> FFrame3d UE::Geometry::TMeshLocalParam< PointSetType >::GetFrame (const FGraphNode & Node) const inline protected
Definition at line 303 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::CachedNormal, GetPosition(), and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::PointID.
Referenced by UpdateUVExpmap(), and UpdateUVExpmapUpwind().
GetMaxGraphDistance()
template<class PointSetType> double UE::Geometry::TMeshLocalParam< PointSetType >::GetMaxGraphDistance () const inline
Returns
the maximum graph distance/radius encountered during the computation
Definition at line 157 of file MeshLocalParam.h.
References MaxGraphDistance.
GetMaxUVDistance()
template<class PointSetType> double UE::Geometry::TMeshLocalParam< PointSetType >::GetMaxUVDistance () const inline
Returns
the maximum UV distance/radius encountered during the computation
Definition at line 165 of file MeshLocalParam.h.
References MaxUVDistance.
GetNodeForPointSetID() [1/2]
template<class PointSetType> const FGraphNode * UE::Geometry::TMeshLocalParam< PointSetType >::GetNodeForPointSetID (int32 PointSetID) const inline protected
Definition at line 495 of file MeshLocalParam.h.
References AllocatedNodes, and IDToNodeIndexMap.
GetNodeForPointSetID() [2/2]
template<class PointSetType> FGraphNode * UE::Geometry::TMeshLocalParam< PointSetType >::GetNodeForPointSetID (int32 PointSetID, bool bCreateIfMissing) inline protected
Definition at line 460 of file MeshLocalParam.h.
References AllocatedNodes, bEnableExternalNormals, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::CachedNormal, ExternalNormalFunc, GetNormal(), IDToNodeIndexMap, UE::Math::TVector< double >::UnitZ(), and UE::Math::TVector2< double >::Zero().
Referenced by ComputeToMaxDistance(), ComputeToMaxDistance(), GetUV(), HasUV(), ProcessQueueUntilTermination(), UpdateNeighboursSparse(), UpdateUVExpmap(), and UpdateUVExpmapUpwind().
GetNormal()
template<class PointSetType> FVector3d UE::Geometry::TMeshLocalParam< PointSetType >::GetNormal (const int32 PointID) const inline protected
Definition at line 270 of file MeshLocalParam.h.
References UE::Geometry::FMeshNormals::ComputeVertexNormal(), ensureMsgf, PointSet, TEXT, and UE::Math::TVector< double >::UnitY().
Referenced by GetNodeForPointSetID().
GetPointsWithUV()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::GetPointsWithUV (TArray< int32 > & Points) const inline
Returns
Array of points with set UVs.
Definition at line 182 of file MeshLocalParam.h.
References AllocatedNodes, and Points.
GetPosition()
template<class PointSetType> FVector3d UE::Geometry::TMeshLocalParam< PointSetType >::GetPosition (const int32 PointID) const inline protected
Definition at line 265 of file MeshLocalParam.h.
References PointSet.
Referenced by ComputeToMaxDistance(), GetFrame(), UpdateNeighboursSparse(), UpdateUVExpmap(), UpdateUVExpmapUpwind(), and UpdateUVPlanar().
GetUV()
template<class PointSetType> FVector2d UE::Geometry::TMeshLocalParam< PointSetType >::GetUV (int32 PointID) const inline
Returns
the UV calculated for index PointID
Definition at line 197 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, GetNodeForPointSetID(), InvalidUV(), and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV.
GetUVBounds()
template<class PointSetType> FAxisAlignedBox2d UE::Geometry::TMeshLocalParam< PointSetType >::GetUVBounds () const inline
Returns
2D Axis-Aligned Bounding Box of the calculated UVs
Definition at line 247 of file MeshLocalParam.h.
References AllocatedNodes, UE::Geometry::TAxisAlignedBox2< RealType >::Contain(), and UE::Geometry::TAxisAlignedBox2< double >::Empty().
HasUV()
template<class PointSetType> bool UE::Geometry::TMeshLocalParam< PointSetType >::HasUV (int32 PointID) const inline
Returns
true if the UV for index PointID was calculated
Definition at line 173 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, and GetNodeForPointSetID().
InvalidUV()
template<class PointSetType> FVector2d UE::Geometry::TMeshLocalParam< PointSetType >::InvalidUV () inline static protected
Definition at line 317 of file MeshLocalParam.h.
Referenced by GetUV().
ProcessQueueUntilTermination()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::ProcessQueueUntilTermination (double MaxDistance) inline protected
Definition at line 327 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, check, UE::Geometry::ExponentialMap, UE::Geometry::ExponentialMapUpwindAvg, GetNodeForPointSetID(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::GraphDistance, TMathUtil< RealType >::Max(), MaxGraphDistance, MaxUVDistance, ParamMode, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::ParentPointID, UE::Geometry::PlanarProjection, Queue, TMathUtil< RealType >::Sqrt(), UE::Math::TVector2< T >::SquaredLength(), UpdateNeighboursSparse(), UpdateUVExpmap(), UpdateUVExpmapUpwind(), UpdateUVPlanar(), and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV.
Referenced by ComputeToMaxDistance(), and ComputeToMaxDistance().
PropagateUV()
template<class PointSetType> FVector2d UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV (const FVector3d & Position, const FVector2d & NbrUV, const FFrame3d & NbrFrame, const FFrame3d & SeedFrameIn) const inline protected
Definition at line 380 of file MeshLocalParam.h.
References UE::Geometry::TFrame3< RealType >::AlignAxis(), ComputeLocalUV(), UE::Math::TVector< T >::Cross(), UE::Math::TVector< T >::Dot(), UE::Geometry::Position, TMathUtil< RealType >::Sqrt(), UE::Geometry::TFrame3< RealType >::X(), and UE::Geometry::TFrame3< RealType >::Z().
Referenced by UpdateUVExpmap(), and UpdateUVExpmapUpwind().
Reset()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::Reset () inline
Reset internal data structures but keep allocated memory.
Definition at line 75 of file MeshLocalParam.h.
References AllocatedNodes, IDToNodeIndexMap, MaxGraphDistance, MaxUVDistance, and Queue.
TransformUV()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::TransformUV (double Scale, FVector2d Translate) inline
Scale and then Translate all calculated UV values.
Definition at line 141 of file MeshLocalParam.h.
References AllocatedNodes, Scale, and Translate().
UpdateNeighboursSparse()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::UpdateNeighboursSparse (FGraphNode * Parent) inline protected
Definition at line 505 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, Distance, GetNodeForPointSetID(), GetPosition(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::GraphDistance, Parent, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::ParentPointID, PointSet, and Queue.
Referenced by ProcessQueueUntilTermination().
UpdateUVExpmap()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::UpdateUVExpmap (FGraphNode & Node) inline protected
Definition at line 410 of file MeshLocalParam.h.
References check, GetFrame(), GetNodeForPointSetID(), GetPosition(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::ParentPointID, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::PointID, PropagateUV(), SeedFrame, and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV.
Referenced by ProcessQueueUntilTermination().
UpdateUVExpmapUpwind()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::UpdateUVExpmapUpwind (FGraphNode & Node) inline protected
Definition at line 422 of file MeshLocalParam.h.
References UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::bFrozen, check, UE::Geometry::DistanceSquared(), GetFrame(), GetNodeForPointSetID(), GetPosition(), UE::Geometry::TFrame3< RealType >::Origin, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::ParentPointID, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::PointID, PointSet, PropagateUV(), SeedFrame, UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV, Weight, and UE::Math::TVector2< double >::Zero().
Referenced by ProcessQueueUntilTermination().
UpdateUVPlanar()
template<class PointSetType> void UE::Geometry::TMeshLocalParam< PointSetType >::UpdateUVPlanar (FGraphNode & Node) inline protected
Definition at line 452 of file MeshLocalParam.h.
References ComputeLocalUV(), GetPosition(), UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::PointID, SeedFrame, and UE::Geometry::TMeshLocalParam< PointSetType >::FGraphNode::UV.
Referenced by ProcessQueueUntilTermination().
Field Documentation
AllocatedNodes
template<class PointSetType> TDynamicVector<FGraphNode> UE::Geometry::TMeshLocalParam< PointSetType >::AllocatedNodes protected
Definition at line 312 of file MeshLocalParam.h.
Referenced by ApplyUVs(), GetAllComputedUVs(), GetNodeForPointSetID(), GetNodeForPointSetID(), GetPointsWithUV(), GetUVBounds(), Reset(), and TransformUV().
bEnableExternalNormals
template<class PointSetType> bool UE::Geometry::TMeshLocalParam< PointSetType >::bEnableExternalNormals = false
If true, ExternalNormalFunc will be used to fetch normals instead of requesting from PointSet->GetVertexNormal.
This allows for (1) vertex normals to be computed on the fly, if only a subset of the point set is being parameterizedx and (2) alternate normals (eg smoothed, etc) to be provided w/o having to define a separate class.
Definition at line 55 of file MeshLocalParam.h.
Referenced by GetNodeForPointSetID().
ExternalNormalFunc
template<class PointSetType> TFunction<FVector3d(int32)> UE::Geometry::TMeshLocalParam< PointSetType >::ExternalNormalFunc
Normals will be requested from this function if bEnableExternalNormals == true.
Definition at line 58 of file MeshLocalParam.h.
Referenced by GetNodeForPointSetID().
IDToNodeIndexMap
template<class PointSetType> TMap<int32, int32> UE::Geometry::TMeshLocalParam< PointSetType >::IDToNodeIndexMap protected
Definition at line 311 of file MeshLocalParam.h.
Referenced by GetNodeForPointSetID(), GetNodeForPointSetID(), and Reset().
MaxGraphDistance
template<class PointSetType> double UE::Geometry::TMeshLocalParam< PointSetType >::MaxGraphDistance protected
Definition at line 323 of file MeshLocalParam.h.
Referenced by TMeshLocalParam(), ComputeToMaxDistance(), ComputeToMaxDistance(), GetMaxGraphDistance(), ProcessQueueUntilTermination(), and Reset().
MaxUVDistance
template<class PointSetType> double UE::Geometry::TMeshLocalParam< PointSetType >::MaxUVDistance protected
Definition at line 324 of file MeshLocalParam.h.
Referenced by TMeshLocalParam(), ComputeToMaxDistance(), ComputeToMaxDistance(), GetMaxUVDistance(), ProcessQueueUntilTermination(), and Reset().
ParamMode
template<class PointSetType> ELocalParamTypes UE::Geometry::TMeshLocalParam< PointSetType >::ParamMode = ELocalParamTypes::ExponentialMapUpwindAvg
Type of local parameterization to compute.
Definition at line 48 of file MeshLocalParam.h.
Referenced by ProcessQueueUntilTermination().
PointSet
template<class PointSetType> const PointSetType* UE::Geometry::TMeshLocalParam< PointSetType >::PointSet
Definition at line 45 of file MeshLocalParam.h.
Referenced by TMeshLocalParam(), GetNormal(), GetPosition(), UpdateNeighboursSparse(), and UpdateUVExpmapUpwind().
Queue
template<class PointSetType> FIndexPriorityQueue UE::Geometry::TMeshLocalParam< PointSetType >::Queue protected
Definition at line 315 of file MeshLocalParam.h.
Referenced by TMeshLocalParam(), ComputeToMaxDistance(), ComputeToMaxDistance(), ProcessQueueUntilTermination(), Reset(), and UpdateNeighboursSparse().
SeedFrame
template<class PointSetType> FFrame3d UE::Geometry::TMeshLocalParam< PointSetType >::SeedFrame protected
Definition at line 320 of file MeshLocalParam.h.
Referenced by ComputeToMaxDistance(), ComputeToMaxDistance(), UpdateUVExpmap(), UpdateUVExpmapUpwind(), and UpdateUVPlanar().
The documentation for this class was generated from the following file:
MeshLocalParam.h