Unreal Engine 5.6 C++ API: FMD5Hash Struct Reference
FMD5Hash Struct Reference
Simple helper struct to ease the caching of MD5 hashes.
#include "SecureHash.h"
Public Member Functions
FMD5Hash ()
Default constructor.
const uint8 * GetBytes () const
const int32 GetSize () const
bool IsValid () const
Check whether this has hash is valid or not.
void Set (FMD5 &MD5)
Set up the MD5 hash from a container.
Static Public Member Functions
static FMD5Hash HashFile (const TCHAR *InFilename, TArray< uint8 > *Buffer=nullptr)
Hash the specified file contents (using the optionally supplied scratch buffer)
static FMD5Hash HashFileFromArchive (FArchive *Ar, TArray< uint8 > *ScratchPad=nullptr)
Private Member Functions
void LexFromString (const TCHAR *)
FString LexToString () const
bool LoadFromCompactBinary (const FCbFieldView &Field)
FCbWriter & WriteCompactBinary (FCbWriter &Writer) const
Private Attributes
bool bIsValid
Whether this hash is valid or not.
uint8 Bytes [16]
The bytes this hash comprises.
Friends
void LexFromString (FMD5Hash &Hash, const TCHAR *InString)
FString LexToString (const FMD5Hash &InHash)
bool LoadFromCompactBinary (const FCbFieldView &Field, FMD5Hash &OutHash)
bool operator!= (const FMD5Hash &LHS, const FMD5Hash &RHS)
Compare one hash with another.
FArchive & operator<< (FArchive &Ar, FMD5Hash &Hash)
Serialise this hash.
FCbWriter & operator<< (FCbWriter &Writer, const FMD5Hash &Hash)
bool operator== (const FMD5Hash &LHS, const FMD5Hash &RHS)
Compare one hash with another.
Detailed Description
Simple helper struct to ease the caching of MD5 hashes.
Definition at line 132 of file SecureHash.h.
Constructor & Destructor Documentation
FMD5Hash()
FMD5Hash::FMD5Hash () inline
Default constructor.
Definition at line 135 of file SecureHash.h.
References bIsValid.
Referenced by HashFile(), HashFileFromArchive(), LexFromString, LexToString, LoadFromCompactBinary, operator!=, operator<<, operator<<, and operator==.
Member Function Documentation
GetBytes()
const uint8 * FMD5Hash::GetBytes () const inline
Definition at line 175 of file SecureHash.h.
References Bytes.
GetSize()
const int32 FMD5Hash::GetSize () const inline
Definition at line 176 of file SecureHash.h.
References Bytes.
HashFile()
FMD5Hash FMD5Hash::HashFile (const TCHAR * InFilename, TArray< uint8 > * Buffer = nullptr) static
Hash the specified file contents (using the optionally supplied scratch buffer)
References FMD5Hash(), and Buffer.
HashFileFromArchive()
FMD5Hash FMD5Hash::HashFileFromArchive (FArchive * Ar, TArray< uint8 > * ScratchPad = nullptr) static
References FMD5Hash(), and Ar.
IsValid()
bool FMD5Hash::IsValid () const inline
Check whether this has hash is valid or not.
Definition at line 138 of file SecureHash.h.
References bIsValid.
LexFromString()
void FMD5Hash::LexFromString (const TCHAR *) private
LexToString()
FString FMD5Hash::LexToString () const private
LoadFromCompactBinary()
bool FMD5Hash::LoadFromCompactBinary (const FCbFieldView & Field) private
Set()
void FMD5Hash::Set (FMD5 & MD5) inline
Set up the MD5 hash from a container.
Definition at line 141 of file SecureHash.h.
References bIsValid, Bytes, and FMD5::Final().
WriteCompactBinary()
FCbWriter & FMD5Hash::WriteCompactBinary (FCbWriter & Writer) const private
Friends And Related Symbol Documentation
LexFromString
void LexFromString (FMD5Hash & Hash, const TCHAR * InString) friend
Definition at line 191 of file SecureHash.h.
References FMD5Hash(), and Hash.
LexToString
FString LexToString (const FMD5Hash & InHash) friend
Definition at line 190 of file SecureHash.h.
References FMD5Hash(), and LexToString.
Referenced by LexToString.
LoadFromCompactBinary
bool LoadFromCompactBinary (const FCbFieldView & Field, FMD5Hash & OutHash) friend
Definition at line 189 of file SecureHash.h.
References FMD5Hash(), and LoadFromCompactBinary.
Referenced by LoadFromCompactBinary.
operator!=
bool operator!= (const FMD5Hash & LHS, const FMD5Hash & RHS) friend
Compare one hash with another.
Definition at line 154 of file SecureHash.h.
References FMD5Hash(), bIsValid, Bytes, and FMemory::Memcmp().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FMD5Hash & Hash) friend
Serialise this hash.
Definition at line 160 of file SecureHash.h.
References FMD5Hash(), Ar, and Hash.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FMD5Hash & Hash) friend
Definition at line 185 of file SecureHash.h.
References FMD5Hash(), and Hash.
operator==
bool operator== (const FMD5Hash & LHS, const FMD5Hash & RHS) friend
Compare one hash with another.
Definition at line 148 of file SecureHash.h.
References FMD5Hash(), bIsValid, Bytes, and FMemory::Memcmp().
Field Documentation
bIsValid
bool FMD5Hash::bIsValid private
Whether this hash is valid or not.
Definition at line 180 of file SecureHash.h.
Referenced by FMD5Hash(), IsValid(), operator!=, operator==, and Set().
Bytes
uint8 FMD5Hash::Bytes[16] private
The bytes this hash comprises.
Definition at line 183 of file SecureHash.h.
Referenced by GetBytes(), GetSize(), operator!=, operator==, and Set().
The documentation for this struct was generated from the following file:
SecureHash.h