Unreal Engine 5.6 C++ API: USoundfieldSubmix Class Reference
USoundfieldSubmix Class Reference
#include "SoundSubmix.h"
Public Member Functions
const USoundfieldEncodingSettingsBase * GetEncodingSettings () const
FName GetSubmixFormat () const
void SanitizeLinks ()
UPROPERTY () FName SoundfieldEncodingFormat
Currently used format.
UPROPERTY () TArray< TObjectPtr< USoundfieldEffectBase > > SoundfieldEffectChain
Soundfield effect chain to use for the sound field.
UPROPERTY () TObjectPtr< USoundfieldEncodingSettingsBase > EncodingSettings
Which encoding settings to use the sound field.
UPROPERTY () TSubclassOf< USoundfieldEncodingSettingsBase > EncodingSettingsClass
Protected Member Functions
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
Private Member Functions
GENERATED_UCLASS_BODY() public const USoundfieldEncodingSettingsBase * GetSoundfieldEncodingSettings () const
TArray< USoundfieldEffectBase * > GetSoundfieldProcessors () const
Detailed Description
Definition at line 520 of file SoundSubmix.h.
Member Function Documentation
GetEncodingSettings()
const USoundfieldEncodingSettingsBase * USoundfieldSubmix::GetEncodingSettings () const
References GetEncodingSettings().
Referenced by GetEncodingSettings().
GetSoundfieldEncodingSettings()
GENERATED_UCLASS_BODY() public const USoundfieldEncodingSettingsBase * USoundfieldSubmix::GetSoundfieldEncodingSettings () const private
GetSoundfieldProcessors()
TArray< USoundfieldEffectBase * > USoundfieldSubmix::GetSoundfieldProcessors () const private
GetSubmixFormat()
FName USoundfieldSubmix::GetSubmixFormat () const
PostEditChangeProperty()
virtual void USoundfieldSubmix::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
PostLoad()
virtual void USoundfieldSubmix::PostLoad () override protected virtual
References PostLoad().
Referenced by PostLoad().
SanitizeLinks()
void USoundfieldSubmix::SanitizeLinks ()
References SanitizeLinks().
Referenced by SanitizeLinks().
UPROPERTY() [1/4]
USoundfieldSubmix::UPROPERTY ()
Currently used format.
References Category.
UPROPERTY() [2/4]
USoundfieldSubmix::UPROPERTY ()
Soundfield effect chain to use for the sound field.
References Category.
UPROPERTY() [3/4]
USoundfieldSubmix::UPROPERTY ()
Which encoding settings to use the sound field.
References Category.
UPROPERTY() [4/4]
USoundfieldSubmix::UPROPERTY ()
The documentation for this class was generated from the following file:
SoundSubmix.h