Unreal Engine 5.6 C++ API: UKismetInternationalizationLibrary Class Reference
UKismetInternationalizationLibrary Class Reference
#include "KismetInternationalizationLibrary.h"
Private Member Functions
UFUNCTION () static 1 bool IsCultureRightToLeft(const FString &Culture)
Returns if the given culture reads left to right.
UFUNCTION () static 1 FString GetCurrentAssetGroupCulture(const FName AssetGroup)
Get the given asset group category culture.
GENERATED_BODY() public UFUNCTION () static 1 FString GetCurrentCulture()
Set the current culture.
UFUNCTION () static 1 FString GetCurrentLanguage()
Get the current language (for localization) as an IETF language tag:
UFUNCTION () static 1 FString GetCurrentLocale()
Get the current locale (for internationalization) as an IETF language tag:
UFUNCTION () static 1 FString GetNativeCulture(const ELocalizedTextSourceCategory TextCategory)
Get the native culture for the given localization category.
UFUNCTION () static 1 FString GetSuitableCulture(const TArray< FString > &AvailableCultures
Given a list of available cultures, try and find the most suitable culture from the list based on culture prioritization.
UFUNCTION () static 1 TArray< FString > GetLocalizedCultures(const bool IncludeGame
Get the list of cultures that have localization data available for them.
UFUNCTION ()) static 1 bool SetCurrentAssetGroupCulture(const FName AssetGroup
Set the given asset group category culture from an IETF language tag (eg, "zh-Hans-CN").
UFUNCTION ()) static 1 bool SetCurrentLanguage(const FString &Culture
Set only the current language (for localization).
UFUNCTION ()) static 1 bool SetCurrentLanguageAndLocale(const FString &Culture
Set the current language (for localization) and locale (for internationalization).
UFUNCTION ()) static 1 bool SetCurrentLocale(const FString &Culture
Set only the current locale (for internationalization).
UFUNCTION ()) static 1 FString GetCultureDisplayName(const FString &Culture
Get the display name of the given culture.
UFUNCTION ()) static 1 void ClearCurrentAssetGroupCulture(const FName AssetGroup
Clear the given asset group category culture.
Static Private Member Functions
static TArray< FString > GetLocalizedCultures (const ELocalizationLoadFlags LoadFlags)
Get the list of cultures that have localization data available for them.
Private Attributes
const FString & Culture
const FString & CultureToMatch
const FString const FString & FallbackCulture = TEXT("en"))
const bool const bool const bool IncludeAdditional = false)
const bool const bool IncludeEditor = false
const bool IncludeEngine = false
const bool Localized = true)
const bool SaveToConfig = false)
const FString const bool SaveToConfig = false)
Detailed Description
Definition at line 15 of file KismetInternationalizationLibrary.h.
Member Function Documentation
GetLocalizedCultures()
TArray< FString > UKismetInternationalizationLibrary::GetLocalizedCultures (const ELocalizationLoadFlags LoadFlags) static private
Get the list of cultures that have localization data available for them.
Parameters
LoadFlags Controls which resource groups should be checked.
Returns
The list of cultures as IETF language tags (eg, "zh-Hans-CN").
References GetLocalizedCultures(), and LoadFlags.
Referenced by GetLocalizedCultures().
UFUNCTION() [1/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Returns if the given culture reads left to right.
Parameters
Culture The culture to get the display name of, as an IETF language tag (eg, "zh-Hans-CN")
Returns
True if the given culture reads left to right.
References Category, Culture, and UFUNCTION().
UFUNCTION() [2/14]
UKismetInternationalizationLibrary::UFUNCTION () const private
Get the given asset group category culture.
Note
Returns the current language if the group category doesn't have a culture override.
Parameters
AssetGroup The asset group to get the culture for.
Returns
The culture as an IETF language tag (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [3/14]
GENERATED_BODY() public UKismetInternationalizationLibrary::UFUNCTION () private
Set the current culture.
Note
This function is a sledgehammer, and will set both the language and locale, as well as clear out any asset group cultures that may be set.
Parameters
Culture The culture to set, as an IETF language tag (eg, "zh-Hans-CN").
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
Returns
True if the culture was set, false otherwise. Get the current culture as an IETF language tag:
A two-letter ISO 639-1 language code (eg, "zh").
An optional four-letter ISO 15924 script code (eg, "Hans").
An optional two-letter ISO 3166-1 country code (eg, "CN").
Note
This function exists for legacy API parity with SetCurrentCulture and is equivalent to GetCurrentLanguage.
Returns
The culture as an IETF language tag (eg, "zh-Hans-CN").
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/14]
UKismetInternationalizationLibrary::UFUNCTION () private
Get the current language (for localization) as an IETF language tag:
A two-letter ISO 639-1 language code (eg, "zh").
An optional four-letter ISO 15924 script code (eg, "Hans").
An optional two-letter ISO 3166-1 country code (eg, "CN").
Returns
The language as an IETF language tag (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [5/14]
UKismetInternationalizationLibrary::UFUNCTION () private
Get the current locale (for internationalization) as an IETF language tag:
A two-letter ISO 639-1 language code (eg, "zh").
An optional four-letter ISO 15924 script code (eg, "Hans").
An optional two-letter ISO 3166-1 country code (eg, "CN").
Returns
The locale as an IETF language tag (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [6/14]
UKismetInternationalizationLibrary::UFUNCTION () const private
Get the native culture for the given localization category.
Parameters
Category The localization category to query.
Returns
The culture as an IETF language tag (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [7/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Given a list of available cultures, try and find the most suitable culture from the list based on culture prioritization.
eg) If your list was [en, fr, de] and the given culture was "en-US", this function would return "en". eg) If your list was [zh, ar, pl] and the given culture was "en-US", this function would return the fallback culture.
Parameters
AvailableCultures List of available cultures to filter against (see GetLocalizedCultures).
CultureToMatch Culture to try and match (see GetCurrentLanguage).
FallbackCulture The culture to return if there is no suitable match in the list (typically your native culture, see GetNativeCulture).
Returns
The culture as an IETF language tag (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [8/14]
UKismetInternationalizationLibrary::UFUNCTION () const private
Get the list of cultures that have localization data available for them.
Parameters
IncludeGame Check for localized game resources.
IncludeEngine Check for localized engine resources.
IncludeEditor Check for localized editor resources.
IncludeAdditional Check for localized additional (eg, plugin) resources.
Returns
The list of cultures as IETF language tags (eg, "zh-Hans-CN").
References Category, and UFUNCTION().
UFUNCTION() [9/14]
UKismetInternationalizationLibrary::UFUNCTION () const private
Set the given asset group category culture from an IETF language tag (eg, "zh-Hans-CN").
Parameters
AssetGroup The asset group to set the culture for.
Culture The culture to set, as an IETF language tag (eg, "zh-Hans-CN").
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
Returns
True if the culture was set, false otherwise.
References Category, meta, and UFUNCTION().
UFUNCTION() [10/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Set only the current language (for localization).
Note
Unless you're doing something advanced, you likely want SetCurrentLanguageAndLocale or SetCurrentCulture instead.
Parameters
Culture The language to set, as an IETF language tag (eg, "zh-Hans-CN").
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
Returns
True if the language was set, false otherwise.
References Category, meta, and UFUNCTION().
UFUNCTION() [11/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Set the current language (for localization) and locale (for internationalization).
Parameters
Culture The language and locale to set, as an IETF language tag (eg, "zh-Hans-CN").
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
Returns
True if the language and locale were set, false otherwise.
References Category, Culture, meta, SaveToConfig, and UFUNCTION().
UFUNCTION() [12/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Set only the current locale (for internationalization).
Note
Unless you're doing something advanced, you likely want SetCurrentLanguageAndLocale or SetCurrentCulture instead.
Parameters
Culture The locale to set, as an IETF language tag (eg, "zh-Hans-CN").
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
Returns
True if the locale was set, false otherwise.
References Category, Culture, meta, SaveToConfig, and UFUNCTION().
UFUNCTION() [13/14]
UKismetInternationalizationLibrary::UFUNCTION () const & private
Get the display name of the given culture.
Parameters
Culture The culture to get the display name of, as an IETF language tag (eg, "zh-Hans-CN")
Localized True to get the localized display name (the name of the culture in its own language), or False to get the display name in the current language.
Returns
The display name of the culture, or the given culture code on failure.
References Category, meta, and UFUNCTION().
UFUNCTION() [14/14]
UKismetInternationalizationLibrary::UFUNCTION () const private
Clear the given asset group category culture.
Parameters
AssetGroup The asset group to clear the culture for.
SaveToConfig If true, save the new setting to the users' "GameUserSettings" config so that it persists after a reload.
References Category, meta, SaveToConfig, and UFUNCTION().
Field Documentation
Culture
const FString& UKismetInternationalizationLibrary::Culture private
Definition at line 98 of file KismetInternationalizationLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
CultureToMatch
const FString& UKismetInternationalizationLibrary::CultureToMatch private
Definition at line 153 of file KismetInternationalizationLibrary.h.
FallbackCulture
const FString const FString& UKismetInternationalizationLibrary::FallbackCulture = TEXT("en")) private
Definition at line 153 of file KismetInternationalizationLibrary.h.
IncludeAdditional
const bool const bool const bool UKismetInternationalizationLibrary::IncludeAdditional = false) private
Definition at line 134 of file KismetInternationalizationLibrary.h.
IncludeEditor
const bool const bool UKismetInternationalizationLibrary::IncludeEditor = false private
Definition at line 134 of file KismetInternationalizationLibrary.h.
IncludeEngine
const bool UKismetInternationalizationLibrary::IncludeEngine = false private
Definition at line 134 of file KismetInternationalizationLibrary.h.
Localized
const bool UKismetInternationalizationLibrary::Localized = true) private
Definition at line 162 of file KismetInternationalizationLibrary.h.
SaveToConfig [1/2]
const bool UKismetInternationalizationLibrary::SaveToConfig = false) private
Definition at line 49 of file KismetInternationalizationLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
SaveToConfig [2/2]
const FString const bool UKismetInternationalizationLibrary::SaveToConfig = false) private
Definition at line 98 of file KismetInternationalizationLibrary.h.
The documentation for this class was generated from the following file:
KismetInternationalizationLibrary.h