Unreal Engine 5.6 C++ API: FRigVMTreeNode Class Reference
FRigVMTreeNode Class Reference
A Node is the base element for anything that is shown within the tree.
#include "RigVMTreeToolkitNode.h"
Public Types
typedef FRigVMTreeElement Super
Public Member Functions
FRigVMTreeNode (const FString &InPath)
virtual void DirtyChildren ()
virtual void DirtyVisibleChildren ()
TSharedPtr< FRigVMTreeNode > FindVisibleChild (const FString &InFullPath, const TSharedRef< FRigVMTreeContext > &InContext) const
virtual FAssetData GetAssetData () const
virtual FSlateColor GetBackgroundColor (bool bIsHovered, bool bIsSelected) const
virtual const FSlateBrush * GetBackgroundImage (bool bIsHovered, bool bIsSelected) const
virtual URigVMBlueprint * GetBlueprint () const
ECheckBoxState GetCheckState () const
TArray< TSharedRef< FRigVMTreeNode > > GetChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
virtual void GetContextMenu (FMenuBuilder &InMenuBuilder)
int32 GetDepth () const
virtual const FSlateBrush * GetIconAndTint (FLinearColor &OutColor) const
virtual FText GetLabel () const
TSharedPtr< FRigVMTreeNode > GetParent () const
virtual const FString & GetPath () const
TSharedRef< FRigVMTreeNode > GetRoot () const
virtual const TArray< FRigVMTag > & GetTags () const
virtual FName GetType () const override
const TArray< TSharedRef< FRigVMTreeNode > > & GetVisibleChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
virtual bool HasVisibleChildren () const
virtual bool IsCheckable () const
virtual bool IsLoaded () const
virtual bool IsOfType (const FName &InType) const override
void RequestRefresh (bool bForce=false)
void ResetCheckState ()
void SetCheckState (ECheckBoxState InNewState)
virtual bool ShouldExpandByDefault () const
TSharedPtr< FRigVMTreeNode > ToSharedPtr () const
TSharedRef< FRigVMTreeNode > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreeNode > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeNode"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Protected Member Functions
void AddChildImpl (const TSharedRef< FRigVMTreeNode > &InChild) const
bool ContainsAnyVisibleCheckedNode () const
DECLARE_DELEGATE_OneParam (FRefreshDelegate, bool) FRefreshDelegate RefreshDelegate
void DirtyVisibleParent () const
virtual TArray< TSharedRef< FRigVMTreeNode > > GetChildrenImpl (const TSharedRef< FRigVMTreeContext > &InContext) const
void UpdateChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
void UpdateVisibleChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static TSharedPtr< FRigVMTreeNode > FindVisibleNodeInSet (const TArray< TSharedRef< FRigVMTreeNode > > &InNodes, const FString &InPath, const TSharedRef< FRigVMTreeContext > &InContext)
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
bool bIsDirtyingParent = false
TOptional< ECheckBoxState > CheckState
TOptional< TArray< TSharedRef< FRigVMTreeNode > > > Children
const FRigVMTreeNode * Parent = nullptr
FString Path
TArray< FRigVMTag > Tags
TArray< TSharedRef< FRigVMTreeNode > > VisibleChildren
uint32 VisibleChildrenHash = UINT32_MAX
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeNode > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeNode > &InElement)
class FRemoveNodeTask
class FRigVMTreePhase
class SRigVMChangesTreeRow
class SRigVMChangesTreeView
Detailed Description
A Node is the base element for anything that is shown within the tree.
Definition at line 17 of file RigVMTreeToolkitNode.h.
Member Typedef Documentation
Super
typedef FRigVMTreeElement FRigVMTreeNode::Super
Definition at line 20 of file RigVMTreeToolkitNode.h.
Constructor & Destructor Documentation
FRigVMTreeNode()
FRigVMTreeNode::FRigVMTreeNode (const FString & InPath) inline
Definition at line 22 of file RigVMTreeToolkitNode.h.
References FRigVMTreeNode(), and Path.
Referenced by FRigVMTreeCategoryNode::FRigVMTreeCategoryNode(), FRigVMTreeFunctionRefNode::FRigVMTreeFunctionRefNode(), FRigVMTreeNode(), FRigVMTreeRootNode::AddChild(), FRigVMTreeCategoryNode::Cast, Cast, FRigVMTreeRootNode::Cast, FRigVMTreeFunctionIdentifierNode::DEFINE_RIGVMTREETOOLKIT_ELEMENT(), FRigVMTreeFunctionRefGraphNode::DEFINE_RIGVMTREETOOLKIT_ELEMENT(), FRigVMTreeFunctionRefNode::DEFINE_RIGVMTREETOOLKIT_ELEMENT(), FRigVMTreeReferenceNode::DEFINE_RIGVMTREETOOLKIT_ELEMENT(), FRigVMTreeRootNode::RemoveChild(), and FRigVMTreeRootNode::SetChildren().
Member Function Documentation
AddChildImpl()
void FRigVMTreeNode::AddChildImpl (const TSharedRef< FRigVMTreeNode > & InChild) const protected
ContainsAnyVisibleCheckedNode()
bool FRigVMTreeNode::ContainsAnyVisibleCheckedNode () const protected
Create()
template<typename... Types> TSharedRef< FRigVMTreeNode > FRigVMTreeNode::Create (Types... Args) inline static
Definition at line 20 of file RigVMTreeToolkitNode.h.
DECLARE_DELEGATE_OneParam()
FRigVMTreeNode::DECLARE_DELEGATE_OneParam (FRefreshDelegate , bool) protected
DirtyChildren()
virtual void FRigVMTreeNode::DirtyChildren () virtual
Reimplemented in FRigVMTreeFunctionIdentifierAssetNode, FRigVMTreeFunctionRefAssetNode, and FRigVMTreeFunctionRefGraphNode.
DirtyVisibleChildren()
virtual void FRigVMTreeNode::DirtyVisibleChildren () virtual
DirtyVisibleParent()
void FRigVMTreeNode::DirtyVisibleParent () const protected
FindVisibleChild()
TSharedPtr< FRigVMTreeNode > FRigVMTreeNode::FindVisibleChild (const FString & InFullPath, const TSharedRef< FRigVMTreeContext > & InContext) const
FindVisibleNodeInSet()
TSharedPtr< FRigVMTreeNode > FRigVMTreeNode::FindVisibleNodeInSet (const TArray< TSharedRef< FRigVMTreeNode > > & InNodes, const FString & InPath, const TSharedRef< FRigVMTreeContext > & InContext) static protected
GetAssetData()
virtual FAssetData FRigVMTreeNode::GetAssetData () const virtual
GetBackgroundColor()
virtual FSlateColor FRigVMTreeNode::GetBackgroundColor (bool bIsHovered, bool bIsSelected) const virtual
Reimplemented in FRigVMTreeCategoryNode.
GetBackgroundImage()
virtual const FSlateBrush * FRigVMTreeNode::GetBackgroundImage (bool bIsHovered, bool bIsSelected) const virtual
Reimplemented in FRigVMTreeCategoryNode.
GetBlueprint()
virtual URigVMBlueprint * FRigVMTreeNode::GetBlueprint () const virtual
GetCheckState()
ECheckBoxState FRigVMTreeNode::GetCheckState () const
GetChildren()
TArray< TSharedRef< FRigVMTreeNode > > FRigVMTreeNode::GetChildren (const TSharedRef< FRigVMTreeContext > & InContext) const inline
Definition at line 80 of file RigVMTreeToolkitNode.h.
References Children, and UpdateChildren().
GetChildrenImpl()
virtual TArray< TSharedRef< FRigVMTreeNode > > FRigVMTreeNode::GetChildrenImpl (const TSharedRef< FRigVMTreeContext > & InContext) const inline protected virtual
Reimplemented in FRigVMTreeAssetRefAssetNode, FRigVMTreeFunctionRefAssetNode, and FRigVMTreeFunctionRefGraphNode.
Definition at line 107 of file RigVMTreeToolkitNode.h.
References Children.
GetContextMenu()
virtual void FRigVMTreeNode::GetContextMenu (FMenuBuilder & InMenuBuilder) inline virtual
Definition at line 37 of file RigVMTreeToolkitNode.h.
GetDepth()
int32 FRigVMTreeNode::GetDepth () const
GetIconAndTint()
virtual const FSlateBrush * FRigVMTreeNode::GetIconAndTint (FLinearColor & OutColor) const inline virtual
Reimplemented in FRigVMTreeFunctionIdentifierNode, FRigVMTreeFunctionRefGraphNode, FRigVMTreeFunctionRefNode, and FRigVMTreePackageNode.
Definition at line 97 of file RigVMTreeToolkitNode.h.
GetLabel()
virtual FText FRigVMTreeNode::GetLabel () const virtual
Reimplemented in FRigVMTreeFunctionIdentifierNode, FRigVMTreeFunctionRefGraphNode, and FRigVMTreePackageNode.
GetParent()
TSharedPtr< FRigVMTreeNode > FRigVMTreeNode::GetParent () const inline
Definition at line 63 of file RigVMTreeToolkitNode.h.
References Parent.
GetPath()
virtual const FString & FRigVMTreeNode::GetPath () const inline virtual
Definition at line 27 of file RigVMTreeToolkitNode.h.
References Path.
GetRoot()
TSharedRef< FRigVMTreeNode > FRigVMTreeNode::GetRoot () const
GetTags()
virtual const TArray< FRigVMTag > & FRigVMTreeNode::GetTags () const inline virtual
Reimplemented in FRigVMTreeFunctionIdentifierNode, and FRigVMTreePackageNode.
Definition at line 56 of file RigVMTreeToolkitNode.h.
References Tags.
GetType()
virtual FName FRigVMTreeNode::GetType () const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMTreeCategoryNode, FRigVMTreePackageNode, and FRigVMTreeRootNode.
Definition at line 20 of file RigVMTreeToolkitNode.h.
GetVisibleChildren()
const TArray< TSharedRef< FRigVMTreeNode > > & FRigVMTreeNode::GetVisibleChildren (const TSharedRef< FRigVMTreeContext > & InContext) const inline
Definition at line 74 of file RigVMTreeToolkitNode.h.
References UpdateVisibleChildren(), and VisibleChildren.
HasVisibleChildren()
virtual bool FRigVMTreeNode::HasVisibleChildren () const inline virtual
Definition at line 86 of file RigVMTreeToolkitNode.h.
References VisibleChildren.
IsCheckable()
virtual bool FRigVMTreeNode::IsCheckable () const inline virtual
Reimplemented in FRigVMTreeAssetRefAssetNode, FRigVMTreeFunctionIdentifierAssetNode, FRigVMTreeFunctionIdentifierNode, FRigVMTreeFunctionRefAssetNode, FRigVMTreeFunctionRefGraphNode, FRigVMTreeFunctionRefNode, and FRigVMTreeReferenceNode.
Definition at line 41 of file RigVMTreeToolkitNode.h.
IsLoaded()
virtual bool FRigVMTreeNode::IsLoaded () const virtual
Reimplemented in FRigVMTreePackageNode.
IsOfType()
virtual bool FRigVMTreeNode::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeElement.
Reimplemented in FRigVMTreeCategoryNode, FRigVMTreePackageNode, and FRigVMTreeRootNode.
Definition at line 20 of file RigVMTreeToolkitNode.h.
RequestRefresh()
void FRigVMTreeNode::RequestRefresh (bool bForce = false)
ResetCheckState()
void FRigVMTreeNode::ResetCheckState ()
SetCheckState()
void FRigVMTreeNode::SetCheckState (ECheckBoxState InNewState)
ShouldExpandByDefault()
virtual bool FRigVMTreeNode::ShouldExpandByDefault () const inline virtual
Reimplemented in FRigVMTreeFunctionIdentifierAssetNode.
Definition at line 51 of file RigVMTreeToolkitNode.h.
ToSharedPtr()
TSharedPtr< FRigVMTreeNode > FRigVMTreeNode::ToSharedPtr () const inline
Definition at line 20 of file RigVMTreeToolkitNode.h.
ToSharedRef()
TSharedRef< FRigVMTreeNode > FRigVMTreeNode::ToSharedRef () const inline
Definition at line 20 of file RigVMTreeToolkitNode.h.
UpdateChildren()
void FRigVMTreeNode::UpdateChildren (const TSharedRef< FRigVMTreeContext > & InContext) const protected
Referenced by GetChildren().
UpdateVisibleChildren()
void FRigVMTreeNode::UpdateVisibleChildren (const TSharedRef< FRigVMTreeContext > & InContext) const protected
Referenced by GetVisibleChildren().
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeNode > & InElement) friend
Definition at line 20 of file RigVMTreeToolkitNode.h.
References FRigVMTreeElement::FRigVMTreeElement(), and FRigVMTreeNode().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeNode > & InElement) friend
Definition at line 20 of file RigVMTreeToolkitNode.h.
FRemoveNodeTask
friend class FRemoveNodeTask friend
Definition at line 134 of file RigVMTreeToolkitNode.h.
References FRemoveNodeTask.
Referenced by FRemoveNodeTask.
FRigVMTreePhase
friend class FRigVMTreePhase friend
Definition at line 133 of file RigVMTreeToolkitNode.h.
References FRigVMTreePhase.
Referenced by FRigVMTreePhase.
SRigVMChangesTreeRow
friend class SRigVMChangesTreeRow friend
Definition at line 131 of file RigVMTreeToolkitNode.h.
References SRigVMChangesTreeRow.
Referenced by SRigVMChangesTreeRow.
SRigVMChangesTreeView
friend class SRigVMChangesTreeView friend
Definition at line 132 of file RigVMTreeToolkitNode.h.
References SRigVMChangesTreeView.
Referenced by SRigVMChangesTreeView.
Field Documentation
bIsDirtyingParent
bool FRigVMTreeNode::bIsDirtyingParent = false mutable protected
Definition at line 124 of file RigVMTreeToolkitNode.h.
CheckState
TOptional<ECheckBoxState> FRigVMTreeNode::CheckState protected
Definition at line 125 of file RigVMTreeToolkitNode.h.
Children
TOptional<TArray<TSharedRef<FRigVMTreeNode> > > FRigVMTreeNode::Children mutable protected
Definition at line 121 of file RigVMTreeToolkitNode.h.
Referenced by GetChildren(), and GetChildrenImpl().
Parent
const FRigVMTreeNode* FRigVMTreeNode::Parent = nullptr protected
Definition at line 120 of file RigVMTreeToolkitNode.h.
Referenced by GetParent().
Path
FString FRigVMTreeNode::Path protected
Definition at line 119 of file RigVMTreeToolkitNode.h.
Referenced by FRigVMTreeNode(), and GetPath().
Tags
TArray<FRigVMTag> FRigVMTreeNode::Tags mutable protected
Definition at line 126 of file RigVMTreeToolkitNode.h.
Referenced by GetTags().
Type
const FLazyName FRigVMTreeNode::Type = FLazyName(TEXT("FRigVMTreeNode")) inline static
Definition at line 20 of file RigVMTreeToolkitNode.h.
VisibleChildren
TArray<TSharedRef<FRigVMTreeNode> > FRigVMTreeNode::VisibleChildren mutable protected
Definition at line 123 of file RigVMTreeToolkitNode.h.
Referenced by GetVisibleChildren(), and HasVisibleChildren().
VisibleChildrenHash
uint32 FRigVMTreeNode::VisibleChildrenHash = UINT32_MAX mutable protected
Definition at line 122 of file RigVMTreeToolkitNode.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitNode.h