Unreal Engine 5.6 C++ API: FShaderLibraryCooker Struct Reference
FShaderLibraryCooker Struct Reference
#include "ShaderCodeLibrary.h"
Data Structures
struct FShaderFormatDescriptor
Public Member Functions
UE_DEPRECATED (5.6, "DumpShaderCodeStats is deprecated due to being incorrect w.r.t shader duplication due to chunking.") static RENDERCORE_API void DumpShaderCodeStats()
Static Public Member Functions
static RENDERCORE_API bool AddShaderCode (EShaderPlatform ShaderPlatform, const FShaderMapResourceCode *Code, const FShaderMapAssetPaths &AssociatedAssets)
static RENDERCORE_API void AddShaderStableKeyValue (EShaderPlatform ShaderPlatform, FStableShaderKeyAndValue &StableKeyValue)
static RENDERCORE_API bool AppendFromCompactBinary (FCbFieldView Field)
Called On the CookDirector to receive ShaderLibrary contents from a CookWorker.
static RENDERCORE_API bool BeginCookingLibrary (FString const &Name)
Opens a named library for cooking and sets it as the default.
static RENDERCORE_API void CleanDirectories (TArray< FName > const &ShaderFormats)
static RENDERCORE_API void CookShaderFormats (TArray< FShaderFormatDescriptor > const &ShaderFormats)
static RENDERCORE_API void CopyToCompactBinaryAndClear (FCbWriter &Writer, bool &bOutHasData, bool &bOutRanOutOfRoom, int64 MaxShaderSize)
Called from a CookWorker to send all contents of the ShaderLibrary to the CookDirector.
static RENDERCORE_API bool CreatePatchLibrary (TArray< FString > const &OldMetaDataDirs, FString const &NewMetaDataDir, FString const &OutDir, bool bNativeFormat, bool bNeedsDeterministicOrder)
static RENDERCORE_API void DumpShaderTypeStats (const FString &DebugInfoPath, const FString &MetaDataPath)
static RENDERCORE_API void EndCookingLibrary (FString const &Name)
Close a named library.
static RENDERCORE_API void FinishPopulateShaderLibrary (const ITargetPlatform *TargetPlatform, FString const &Name, FString const &SandboxDestinationPath, FString const &SandboxMetadataPath)
Finishes collection of data that should be in the named code library.
static RENDERCORE_API void InitForCooking (bool bNativeFormat, ICookArtifactReader *CookArtifactReader)
static RENDERCORE_API bool IsShaderLibraryEnabled ()
Whether storing shaders in the shader library is enabled.
static RENDERCORE_API bool MergeShaderCodeArchive (const TArray< FString > &CookedMetadataDirs, const FString &OutputDir, TArray< FString > &OutWrittenFiles)
Given multiple Cooked Metadata directories will attempt to merge the ShaderByteCode and the ShaderStableInfo into the given OutputDir.
static RENDERCORE_API bool NeedsShaderStableKeys (EShaderPlatform ShaderPlatform)
static RENDERCORE_API bool SaveShaderLibraryChunk (int32 ChunkId, const TSet< FName > &InPackagesInChunk, const ITargetPlatform *TargetPlatform, const FString &SandboxDestinationPath, const FString &SandboxMetadataPath, TArray< FString > &OutChunkFilenames, bool &bOutHasData)
Saves a single chunk of the collected shader code (per shader platform).
static RENDERCORE_API bool SaveShaderLibraryWithoutChunking (const ITargetPlatform *TargetPlatform, FString const &Name, FString const &SandboxDestinationPath, FString const &SandboxMetadataPath, TArray< FString > &PlatformSCLCSVPaths, FString &OutErrorMessage, bool &bOutHasData)
Saves collected shader code to a single file per shader platform When chunking is enabled, this call will not write the shader code, only the SCL.CSV file with the stable shader info.
static RENDERCORE_API void Shutdown ()
Detailed Description
Definition at line 269 of file ShaderCodeLibrary.h.
Member Function Documentation
AddShaderCode()
RENDERCORE_API bool FShaderLibraryCooker::AddShaderCode (EShaderPlatform ShaderPlatform, const FShaderMapResourceCode * Code, const FShaderMapAssetPaths & AssociatedAssets) static
References ShaderPlatform.
AddShaderStableKeyValue()
RENDERCORE_API void FShaderLibraryCooker::AddShaderStableKeyValue (EShaderPlatform ShaderPlatform, FStableShaderKeyAndValue & StableKeyValue) static
References ShaderPlatform.
AppendFromCompactBinary()
RENDERCORE_API bool FShaderLibraryCooker::AppendFromCompactBinary (FCbFieldView Field) static
Called On the CookDirector to receive ShaderLibrary contents from a CookWorker.
BeginCookingLibrary()
RENDERCORE_API bool FShaderLibraryCooker::BeginCookingLibrary (FString const & Name) static
Opens a named library for cooking and sets it as the default.
This will place all added shaders & pipelines into the library file with this name.
Parameters
Name is a high level description of the library (usually a project name or "Global")
Returns
true if successful
References Name.
CleanDirectories()
RENDERCORE_API void FShaderLibraryCooker::CleanDirectories (TArray< FName > const & ShaderFormats) static
CookShaderFormats()
RENDERCORE_API void FShaderLibraryCooker::CookShaderFormats (TArray< FShaderFormatDescriptor > const & ShaderFormats) static
CopyToCompactBinaryAndClear()
RENDERCORE_API void FShaderLibraryCooker::CopyToCompactBinaryAndClear (FCbWriter & Writer, bool & bOutHasData, bool & bOutRanOutOfRoom, int64 MaxShaderSize) static
Called from a CookWorker to send all contents of the ShaderLibrary to the CookDirector.
CreatePatchLibrary()
RENDERCORE_API bool FShaderLibraryCooker::CreatePatchLibrary (TArray< FString > const & OldMetaDataDirs, FString const & NewMetaDataDir, FString const & OutDir, bool bNativeFormat, bool bNeedsDeterministicOrder) static
References CreatePatchLibrary().
Referenced by CreatePatchLibrary().
DumpShaderTypeStats()
RENDERCORE_API void FShaderLibraryCooker::DumpShaderTypeStats (const FString & DebugInfoPath, const FString & MetaDataPath) static
References DumpShaderTypeStats().
Referenced by DumpShaderTypeStats().
EndCookingLibrary()
RENDERCORE_API void FShaderLibraryCooker::EndCookingLibrary (FString const & Name) static
Close a named library.
For cooking, after this point any AddShaderCode/AddShaderPipeline calls will be invalid until OpenLibrary is called again.
References Name.
FinishPopulateShaderLibrary()
RENDERCORE_API void FShaderLibraryCooker::FinishPopulateShaderLibrary (const ITargetPlatform * TargetPlatform, FString const & Name, FString const & SandboxDestinationPath, FString const & SandboxMetadataPath) static
Finishes collection of data that should be in the named code library.
This includes loading data from a previous iterative cook.
References Name.
InitForCooking()
RENDERCORE_API void FShaderLibraryCooker::InitForCooking (bool bNativeFormat, ICookArtifactReader * CookArtifactReader) static
IsShaderLibraryEnabled()
RENDERCORE_API bool FShaderLibraryCooker::IsShaderLibraryEnabled () static
Whether storing shaders in the shader library is enabled.
MergeShaderCodeArchive()
RENDERCORE_API bool FShaderLibraryCooker::MergeShaderCodeArchive (const TArray< FString > & CookedMetadataDirs, const FString & OutputDir, TArray< FString > & OutWrittenFiles) static
Given multiple Cooked Metadata directories will attempt to merge the ShaderByteCode and the ShaderStableInfo into the given OutputDir.
It would be expected that the OutputDir is another MetaData directory but this can be any dir. Sub directories for ShaderLibrarySource and PipelineCaches will be automatically generated.
Parameters
CookedMetadataDirs - the cooked metadata directories to merge the shader archives from
OutputDir - where to place the union of the shader archives
OutWrittenFiles - full path to all the files written
NeedsShaderStableKeys()
RENDERCORE_API bool FShaderLibraryCooker::NeedsShaderStableKeys (EShaderPlatform ShaderPlatform) static
References ShaderPlatform.
SaveShaderLibraryChunk()
RENDERCORE_API bool FShaderLibraryCooker::SaveShaderLibraryChunk (int32 ChunkId, const TSet< FName > & InPackagesInChunk, const ITargetPlatform * TargetPlatform, const FString & SandboxDestinationPath, const FString & SandboxMetadataPath, TArray< FString > & OutChunkFilenames, bool & bOutHasData) static
Saves a single chunk of the collected shader code (per shader platform).
Does not save SCL.CSV info. This code path is only called if we're chunking. FIXME: this function does not write build metadata
Parameters
ChunkId the chunk id
InPackagesInChunk packages that belong to the chunk
TargetPlatform target platform
SandboxDestinationPath where to put the .ushaderbytecode file(s)
OutChunkFilenames array where the function will append the full paths of the written files
bOutHasData Reports whether any files were written to OutChunkFilenames
Returns
true if successful
SaveShaderLibraryWithoutChunking()
RENDERCORE_API bool FShaderLibraryCooker::SaveShaderLibraryWithoutChunking (const ITargetPlatform * TargetPlatform, FString const & Name, FString const & SandboxDestinationPath, FString const & SandboxMetadataPath, TArray< FString > & PlatformSCLCSVPaths, FString & OutErrorMessage, bool & bOutHasData) static
Saves collected shader code to a single file per shader platform When chunking is enabled, this call will not write the shader code, only the SCL.CSV file with the stable shader info.
Parameters
TargetPlatform target platform
Name shader library name
SandboxDestinationPath where to put the .ushaderbytecode file(s)
SandboxMetadataPath path for the metadata (not a part of the build itself, but produced together with the build)
PlatformSCLCSVPaths path where to put the information about the shader hashes
OutErrorMessage used to return the details of the failure (if failed)
bOutHasData Reports whether any files were written to PlatformSCLCSVPaths
Returns
true if successful
References Name.
Shutdown()
RENDERCORE_API void FShaderLibraryCooker::Shutdown () static
UE_DEPRECATED()
FShaderLibraryCooker::UE_DEPRECATED (5. 6, "DumpShaderCodeStats is deprecated due to being incorrect w.r.t shader duplication due to chunking.")
The documentation for this struct was generated from the following file:
ShaderCodeLibrary.h