Unreal Engine 5.6 C++ API: FStructView Struct Reference
FStructView Struct Reference
FStructView is "typed" struct pointer, it contains pointer to struct plus UScriptStruct pointer.
#include "StructView.h"
Public Member Functions
FStructView ()=default
FStructView (const FSharedStruct &SharedStruct)
FStructView (const UScriptStruct *InScriptStruct, uint8 *InStructMemory=nullptr)
FStructView (FInstancedStruct &InstancedStruct)
template<typename T>
T & Get () const
Returns mutable reference to the struct, this getter assumes that all data is valid.
uint8 * GetMemory () const
Returns pointer to struct memory.
template<typename T>
T * GetPtr () const
Returns mutable pointer to the struct, or nullptr if cast is not valid.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
bool IsValid () const
Returns True if the struct is valid.
template<typename OtherType>
bool operator!= (const OtherType &Other) const
template<typename OtherType>
bool operator== (const OtherType &Other) const
Comparison operators.
void Reset ()
Reset to empty.
Static Public Member Functions
template<typename T>
static FStructView Make (T &InStruct)
Creates a new FStructView from the templated struct.
Protected Attributes
const UScriptStruct * ScriptStruct = nullptr
uint8 * StructMemory = nullptr
Detailed Description
FStructView is "typed" struct pointer, it contains pointer to struct plus UScriptStruct pointer.
FStructView does not own the memory and will not free it when out of scope. It should be only used to pass struct pointer in a limited scope, or when the user controls the lifetime of the struct being stored. E.g. instead of passing ref or pointer to a FInstancedStruct, you should use FConstStructView or FStructView to pass around a view to the contents. FStructView is passed by value. FStructView is similar to FStructOnScope, but FStructView is a view only (FStructOnScope can either own the memory or be a view) const FStructView prevents the struct from pointing at a different instance of a struct. However the actual struct data can be mutated. Use FConstStructView to prevent mutation of the actual struct data. See FConstStructView for examples.
Definition at line 22 of file StructUtils/StructView.h.
Constructor & Destructor Documentation
FStructView() [1/4]
FStructView::FStructView () default
Referenced by FStructView(), FStructView(), TStructView< BaseStructT >::TStructView(), TStructView< BaseStructT >::TStructView(), TStructView< BaseStructT >::TStructView(), TStructView< BaseStructT >::TStructView(), and Make().
FStructView() [2/4]
FStructView::FStructView (const UScriptStruct * InScriptStruct, uint8 * InStructMemory = nullptr) inline
Definition at line 28 of file StructUtils/StructView.h.
References ScriptStruct, and StructMemory.
FStructView() [3/4]
FStructView::FStructView (FInstancedStruct & InstancedStruct) inline
Definition at line 33 of file StructUtils/StructView.h.
References FStructView(), and GetScriptStruct().
FStructView() [4/4]
FStructView::FStructView (const FSharedStruct & SharedStruct) inline
Definition at line 37 of file StructUtils/StructView.h.
References FStructView(), GetMemory(), and GetScriptStruct().
Member Function Documentation
Get()
template<typename T> T & FStructView::Get () const inline
Returns mutable reference to the struct, this getter assumes that all data is valid.
Definition at line 51 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructRef(), ScriptStruct, and StructMemory.
GetMemory()
uint8 * FStructView::GetMemory () const inline
Returns pointer to struct memory.
Definition at line 70 of file StructUtils/StructView.h.
References StructMemory.
Referenced by FStructView(), and TStructView< BaseStructT >::TStructView().
GetPtr()
template<typename T> T * FStructView::GetPtr () const inline
Returns mutable pointer to the struct, or nullptr if cast is not valid.
Definition at line 58 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructPtr(), ScriptStruct, and StructMemory.
GetScriptStruct()
const UScriptStruct * FStructView::GetScriptStruct () const inline
Returns struct type.
Definition at line 64 of file StructUtils/StructView.h.
References ScriptStruct.
Referenced by FStructView(), FStructView(), TStructView< BaseStructT >::TStructView(), and TStructView< BaseStructT >::TStructView().
IsValid()
bool FStructView::IsValid () const inline
Returns True if the struct is valid.
Definition at line 83 of file StructUtils/StructView.h.
References ScriptStruct, and StructMemory.
Make()
template<typename T> FStructView FStructView::Make (T & InStruct) inline static
Creates a new FStructView from the templated struct.
Note its not safe to make InStruct const ref as the original object may have been declared const
Definition at line 43 of file StructUtils/StructView.h.
References FStructView(), UE::StructUtils::CheckStructType(), and TBaseStructureBase< T, bHasStaticStruct >::Get().
operator!=()
template<typename OtherType> bool FStructView::operator!= (const OtherType & Other) const inline
Definition at line 96 of file StructUtils/StructView.h.
References operator==(), and Other.
operator==()
template<typename OtherType> bool FStructView::operator== (const OtherType & Other) const inline
Comparison operators.
Note: it does not compare the internal structure itself
Definition at line 90 of file StructUtils/StructView.h.
References Other, ScriptStruct, and StructMemory.
Reset()
void FStructView::Reset () inline
Reset to empty.
Definition at line 76 of file StructUtils/StructView.h.
References ScriptStruct, and StructMemory.
Field Documentation
ScriptStruct
const UScriptStruct* FStructView::ScriptStruct = nullptr protected
Definition at line 102 of file StructUtils/StructView.h.
Referenced by FStructView(), Get(), TStructView< BaseStructT >::Get(), GetPtr(), TStructView< BaseStructT >::GetPtr(), GetScriptStruct(), IsValid(), operator==(), TStructView< BaseStructT >::operator==(), and Reset().
StructMemory
uint8* FStructView::StructMemory = nullptr protected
Definition at line 103 of file StructUtils/StructView.h.
Referenced by FStructView(), Get(), TStructView< BaseStructT >::Get(), GetMemory(), GetPtr(), TStructView< BaseStructT >::GetPtr(), IsValid(), operator==(), TStructView< BaseStructT >::operator==(), and Reset().
The documentation for this struct was generated from the following file:
StructUtils/StructView.h