Unreal Engine 5.6 C++ API: FHairStrandsLODRestRootResource Struct Reference
FHairStrandsLODRestRootResource Struct Reference
#include "GroomResources.h"
Public Types
enum class EStatus { Invalid , Initialized , Completed }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FHairStrandsLODRestRootResource (TArray< FHairStrandsRootBulkData > &InBulkDataArray, int32 InBulkDataIndex, EHairStrandsResourcesType CurveType, uint32 InMeshLODIndex, const FHairResourceName &ResourceName, const FName &OwnerName)
Build the hair strands resource.
FORCEINLINE FHairStrandsRootBulkData & GetBulkData ()
FORCEINLINE const FHairStrandsRootBulkData & GetBulkData () const
virtual FString GetFriendlyName () const override
uint32 GetResourcesSize () const
uint32 GetRootCount () const
virtual void InternalAllocate (FRDGBuilder &GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override
virtual FHairStrandsBulkCommon * InternalGetBulkData () override
virtual bool InternalGetOrRequestData (uint32 InRequestedCurveCount, uint32 InRequestedPointCount) override
virtual void InternalRelease () override
virtual void InternalResetLoadedSize () override
FORCEINLINE bool IsBulkDataValid () const
const bool IsDataValid () const
const bool IsValid () const
void Reset ()
Public Member Functions inherited from FHairCommonResource
FHairCommonResource (EHairStrandsAllocationType AllocationType, const FHairResourceName &InResourceName, const FName &InOwnerName, bool bUseRenderGraph=true)
Build the hair strands resource.
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status, uint32 InRequestedCurveCount, uint32 InRequestedPointCount, bool bAllowDeallocation=true)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void InternalAllocate ()
virtual void InternalAllocate (FRDGBuilder &GraphBuilder)
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void StreamInData ()
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
uint32 AvailableCurveCount = 0
TArray< FHairStrandsRootBulkData > & BulkDataArray
int32 BulkDataIndex = -1
const EHairStrandsResourcesType CurveType
FRDGExternalBuffer MeshInterpolationWeightsBuffer
const uint32 MeshLODIndex = 0
FRDGExternalBuffer MeshSampleIndicesAndSectionsBuffer
FRDGExternalBuffer RestSamplePositionsBuffer
FRDGExternalBuffer RestUniqueTrianglePositionBuffer
FRDGExternalBuffer RootBarycentricBuffer
FRDGExternalBuffer RootToUniqueTriangleIndexBuffer
uint32 SampleCount = 0
EStatus Status = EStatus::Invalid
FRDGExternalBuffer UniqueTriangleIndexBuffer
Data Fields inherited from FHairCommonResource
EHairStrandsAllocationType AllocationType = EHairStrandsAllocationType::Deferred
bool bIsInitialized = false
bool bUseRenderGraph = true
uint32 MaxAvailableCurveCount = HAIR_MAX_NUM_CURVE_PER_GROUP
FName OwnerName
FHairResourceName ResourceName
FHairStreamingRequest StreamingRequest
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Additional Inherited Members
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 403 of file GroomResources.h.
Member Enumeration Documentation
EStatus
enum class FHairStrandsLODRestRootResource::EStatus strong
Enumerator
Invalid
Initialized
Completed
Definition at line 453 of file GroomResources.h.
Constructor & Destructor Documentation
FHairStrandsLODRestRootResource()
FHairStrandsLODRestRootResource::FHairStrandsLODRestRootResource (TArray< FHairStrandsRootBulkData > & InBulkDataArray, int32 InBulkDataIndex, EHairStrandsResourcesType CurveType, uint32 InMeshLODIndex, const FHairResourceName & ResourceName, const FName & OwnerName)
Build the hair strands resource.
References CurveType, FHairCommonResource::OwnerName, and FHairCommonResource::ResourceName.
Member Function Documentation
GetBulkData() [1/2]
FORCEINLINE FHairStrandsRootBulkData & FHairStrandsLODRestRootResource::GetBulkData () inline
Definition at line 433 of file GroomResources.h.
References BulkDataArray, BulkDataIndex, check, and FORCEINLINE.
GetBulkData() [2/2]
FORCEINLINE const FHairStrandsRootBulkData & FHairStrandsLODRestRootResource::GetBulkData () const inline
Definition at line 427 of file GroomResources.h.
References BulkDataArray, BulkDataIndex, check, and FORCEINLINE.
Referenced by GetRootCount(), InternalGetBulkData(), and IsDataValid().
GetFriendlyName()
virtual FString FHairStrandsLODRestRootResource::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Definition at line 416 of file GroomResources.h.
References TEXT.
GetResourcesSize()
uint32 FHairStrandsLODRestRootResource::GetResourcesSize () const inline
Definition at line 440 of file GroomResources.h.
References GetBufferTotalNumBytes(), MeshInterpolationWeightsBuffer, MeshSampleIndicesAndSectionsBuffer, RestSamplePositionsBuffer, RestUniqueTrianglePositionBuffer, RootBarycentricBuffer, RootToUniqueTriangleIndexBuffer, and UniqueTriangleIndexBuffer.
GetRootCount()
uint32 FHairStrandsLODRestRootResource::GetRootCount () const inline
Definition at line 422 of file GroomResources.h.
References GetBulkData(), and FHairStrandsRootBulkData::GetRootCount().
InternalAllocate()
virtual void FHairStrandsLODRestRootResource::InternalAllocate (FRDGBuilder & GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override virtual
Reimplemented from FHairCommonResource.
InternalGetBulkData()
virtual FHairStrandsBulkCommon * FHairStrandsLODRestRootResource::InternalGetBulkData () inline override virtual
Reimplemented from FHairCommonResource.
Definition at line 413 of file GroomResources.h.
References GetBulkData().
InternalGetOrRequestData()
virtual bool FHairStrandsLODRestRootResource::InternalGetOrRequestData (uint32 InRequestedCurveCount, uint32 InRequestedPointCount) override virtual
Reimplemented from FHairCommonResource.
InternalRelease()
virtual void FHairStrandsLODRestRootResource::InternalRelease () override virtual
Reimplemented from FHairCommonResource.
InternalResetLoadedSize()
virtual void FHairStrandsLODRestRootResource::InternalResetLoadedSize () override virtual
Reimplemented from FHairCommonResource.
IsBulkDataValid()
FORCEINLINE bool FHairStrandsLODRestRootResource::IsBulkDataValid () const inline
Definition at line 425 of file GroomResources.h.
References BulkDataArray, BulkDataIndex, and FORCEINLINE.
IsDataValid()
const bool FHairStrandsLODRestRootResource::IsDataValid () const inline
Definition at line 455 of file GroomResources.h.
References GetBulkData(), FHairStrandsRootBulkData::Header, FHairStrandsRootBulkData::FHeader::LODIndex, and FHairStrandsRootBulkData::FHeader::RootCount.
IsValid()
const bool FHairStrandsLODRestRootResource::IsValid () const inline
Definition at line 456 of file GroomResources.h.
References Completed, and Status.
Reset()
void FHairStrandsLODRestRootResource::Reset ()
Field Documentation
AvailableCurveCount
uint32 FHairStrandsLODRestRootResource::AvailableCurveCount = 0
Definition at line 458 of file GroomResources.h.
BulkDataArray
TArray<FHairStrandsRootBulkData>& FHairStrandsLODRestRootResource::BulkDataArray
Definition at line 478 of file GroomResources.h.
Referenced by GetBulkData(), GetBulkData(), and IsBulkDataValid().
BulkDataIndex
int32 FHairStrandsLODRestRootResource::BulkDataIndex = -1
Definition at line 479 of file GroomResources.h.
Referenced by GetBulkData(), GetBulkData(), and IsBulkDataValid().
CurveType
const EHairStrandsResourcesType FHairStrandsLODRestRootResource::CurveType
Definition at line 482 of file GroomResources.h.
Referenced by FHairStrandsLODRestRootResource().
MeshInterpolationWeightsBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::MeshInterpolationWeightsBuffer
Definition at line 473 of file GroomResources.h.
Referenced by GetResourcesSize().
MeshLODIndex
const uint32 FHairStrandsLODRestRootResource::MeshLODIndex = 0
Definition at line 485 of file GroomResources.h.
MeshSampleIndicesAndSectionsBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::MeshSampleIndicesAndSectionsBuffer
Definition at line 474 of file GroomResources.h.
Referenced by GetResourcesSize().
RestSamplePositionsBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::RestSamplePositionsBuffer
Definition at line 475 of file GroomResources.h.
Referenced by GetResourcesSize().
RestUniqueTrianglePositionBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::RestUniqueTrianglePositionBuffer
Definition at line 469 of file GroomResources.h.
Referenced by GetResourcesSize().
RootBarycentricBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::RootBarycentricBuffer
Definition at line 466 of file GroomResources.h.
Referenced by GetResourcesSize().
RootToUniqueTriangleIndexBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::RootToUniqueTriangleIndexBuffer
Definition at line 465 of file GroomResources.h.
Referenced by GetResourcesSize().
SampleCount
uint32 FHairStrandsLODRestRootResource::SampleCount = 0
Definition at line 472 of file GroomResources.h.
Status
EStatus FHairStrandsLODRestRootResource::Status = EStatus::Invalid
Definition at line 457 of file GroomResources.h.
Referenced by IsValid().
UniqueTriangleIndexBuffer
FRDGExternalBuffer FHairStrandsLODRestRootResource::UniqueTriangleIndexBuffer
Definition at line 463 of file GroomResources.h.
Referenced by GetResourcesSize().
The documentation for this struct was generated from the following file:
GroomResources.h