Unreal Engine 5.6 C++ API: NetworkingPrivate::FRepPropertyDescriptor Struct Reference
NetworkingPrivate::FRepPropertyDescriptor Struct Reference
#include "UnrealNetwork.h"
Public Member Functions
FRepPropertyDescriptor (const TCHAR *InPropertyName, const int32 InRepIndex, const int32 InArrayDim)
UE_DEPRECATED (5.2, "No longer used") FRepPropertyDescriptor(const FProperty *Property)
Data Fields
const int32 ArrayDim
const TCHAR * PropertyName
const int32 RepIndex
Private Member Functions
void operator delete (void *)=delete
void operator delete[] (void *)=delete
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
UE_NONCOPYABLE (FRepPropertyDescriptor)
Detailed Description
Definition at line 157 of file UnrealNetwork.h.
Constructor & Destructor Documentation
FRepPropertyDescriptor()
NetworkingPrivate::FRepPropertyDescriptor::FRepPropertyDescriptor (const TCHAR * InPropertyName, const int32 InRepIndex, const int32 InArrayDim) inline
Definition at line 167 of file UnrealNetwork.h.
References ArrayDim, PropertyName, and RepIndex.
Referenced by UE_DEPRECATED(), and UE_NONCOPYABLE().
Member Function Documentation
operator delete()
void NetworkingPrivate::FRepPropertyDescriptor::operator delete (void *) private delete
operator delete[]()
void NetworkingPrivate::FRepPropertyDescriptor::operator delete[] (void *) private delete
operator new()
void * NetworkingPrivate::FRepPropertyDescriptor::operator new (size_t) private delete
operator new[]()
void * NetworkingPrivate::FRepPropertyDescriptor::operator new[] (size_t) private delete
UE_DEPRECATED()
NetworkingPrivate::FRepPropertyDescriptor::UE_DEPRECATED (5. 2, "No longer used") const inline
Definition at line 159 of file UnrealNetwork.h.
References FRepPropertyDescriptor(), ArrayDim, Property, PropertyName, RepIndex, and TEXT.
UE_NONCOPYABLE()
NetworkingPrivate::FRepPropertyDescriptor::UE_NONCOPYABLE (FRepPropertyDescriptor) private
References FRepPropertyDescriptor().
Field Documentation
ArrayDim
const int32 NetworkingPrivate::FRepPropertyDescriptor::ArrayDim
Definition at line 176 of file UnrealNetwork.h.
Referenced by FRepPropertyDescriptor(), and UE_DEPRECATED().
PropertyName
const TCHAR* NetworkingPrivate::FRepPropertyDescriptor::PropertyName
Definition at line 174 of file UnrealNetwork.h.
Referenced by FRepPropertyDescriptor(), and UE_DEPRECATED().
RepIndex
const int32 NetworkingPrivate::FRepPropertyDescriptor::RepIndex
Definition at line 175 of file UnrealNetwork.h.
Referenced by FRepPropertyDescriptor(), and UE_DEPRECATED().
The documentation for this struct was generated from the following file:
UnrealNetwork.h