Unreal Engine 5.6 C++ API: UE::BulkData::Private::FBulkMetaData Class Reference
UE::BulkData::Private::FBulkMetaData Class Reference
Bulk meta data, size, offset, flags and lock status packed in 16 bytes.
#include "BulkData.h"
Public Member Functions
FBulkMetaData ()
FBulkMetaData (EBulkDataFlags Flags)
void AddFlags (EBulkDataFlags Flags)
void ClearFlags (EBulkDataFlags Flags)
EBulkDataFlags GetFlags () const
EBulkDataLockStatus GetLockStatus () const
int64 GetOffset () const
FIoOffsetAndLength GetOffsetAndLength () const
int64 GetSize () const
int64 GetSizeOnDisk () const
bool HasAllFlags (EBulkDataFlags Flags) const
bool HasAnyFlags (EBulkDataFlags Flags) const
void SetFlags (EBulkDataFlags Flags)
void SetLockStatus (EBulkDataLockStatus Status)
void SetOffset (int64 Offset)
void SetSize (int64 Size)
void SetSizeOnDisk (int64 SizeOnDisk)
Static Public Member Functions
static bool FromSerialized (FArchive &Ar, int64 ElementSize, FBulkMetaData &OutMetaData)
Serializes FBulkMetaResource from the given archive and builds the returned FBulkMetaData from it.
static bool FromSerialized (FArchive &Ar, int64 ElementSize, FBulkMetaData &OutMetaData, int64 &OutDuplicateOffset)
Serializes FBulkMetaResource from the given archive and builds the returned FBulkMetaData from it.
Static Public Attributes
static constexpr int64 MaxOffset = 0xFFffFFffFE
39 bits for max bulk data offset and 1 bit to indicate INDEX_NONE.
static constexpr int64 MaxSize = 0xFFffFFffFF
40 bits for max bulk data size.
Static Private Member Functions
static uint64 ReadUInt40 (const uint8 *Memory)
static void WriteUInt40 (uint8 *Memory, uint64 Value)
Private Attributes
uint8 Data [24] = {0}
Detailed Description
Bulk meta data, size, offset, flags and lock status packed in 16 bytes.
Uses 5 bytes for size and offset. [0 - 4][5 - 9][ 10 ][ 11 ][12 - 15]([16 - 23]) [Size][Offset][Unused][LockFlags][BulkDataFlags]([SizeOnDisk])
Definition at line 307 of file BulkData.h.
Constructor & Destructor Documentation
FBulkMetaData() [1/2]
UE::BulkData::Private::FBulkMetaData::FBulkMetaData () inline
Definition at line 315 of file BulkData.h.
References SetOffset(), and SetSizeOnDisk().
Referenced by FBulkMetaData(), FromSerialized(), and FromSerialized().
FBulkMetaData() [2/2]
UE::BulkData::Private::FBulkMetaData::FBulkMetaData (EBulkDataFlags Flags) inline explicit
Definition at line 323 of file BulkData.h.
References FBulkMetaData(), Flags, and SetFlags().
Member Function Documentation
AddFlags()
void UE::BulkData::Private::FBulkMetaData::AddFlags (EBulkDataFlags Flags) inline
Definition at line 396 of file BulkData.h.
References Data, and Flags.
ClearFlags()
void UE::BulkData::Private::FBulkMetaData::ClearFlags (EBulkDataFlags Flags) inline
Definition at line 401 of file BulkData.h.
References Data, and Flags.
FromSerialized() [1/2]
bool UE::BulkData::Private::FBulkMetaData::FromSerialized (FArchive & Ar, int64 ElementSize, FBulkMetaData & OutMetaData) inline static
Serializes FBulkMetaResource from the given archive and builds the returned FBulkMetaData from it.
Definition at line 425 of file BulkData.h.
References FBulkMetaData(), Ar, FromSerialized(), and INDEX_NONE.
FromSerialized() [2/2]
bool UE::BulkData::Private::FBulkMetaData::FromSerialized (FArchive & Ar, int64 ElementSize, FBulkMetaData & OutMetaData, int64 & OutDuplicateOffset) static
Serializes FBulkMetaResource from the given archive and builds the returned FBulkMetaData from it.
The offset for duplicated data will also be returned
All fields of OutMetaData will be overwritten, including lock status.
References FBulkMetaData(), and Ar.
Referenced by FromSerialized().
GetFlags()
EBulkDataFlags UE::BulkData::Private::FBulkMetaData::GetFlags () const inline
Definition at line 386 of file BulkData.h.
References Data.
Referenced by HasAllFlags(), and HasAnyFlags().
GetLockStatus()
EBulkDataLockStatus UE::BulkData::Private::FBulkMetaData::GetLockStatus () const inline
Definition at line 376 of file BulkData.h.
References Data.
GetOffset()
int64 UE::BulkData::Private::FBulkMetaData::GetOffset () const inline
Definition at line 356 of file BulkData.h.
References Data, INDEX_NONE, MaxOffset, and ReadUInt40().
GetOffsetAndLength()
FIoOffsetAndLength UE::BulkData::Private::FBulkMetaData::GetOffsetAndLength () const
GetSize()
int64 UE::BulkData::Private::FBulkMetaData::GetSize () const inline
Definition at line 329 of file BulkData.h.
References Data, and ReadUInt40().
Referenced by GetSizeOnDisk().
GetSizeOnDisk()
int64 UE::BulkData::Private::FBulkMetaData::GetSizeOnDisk () const inline
Definition at line 340 of file BulkData.h.
References Data, and GetSize().
HasAllFlags()
bool UE::BulkData::Private::FBulkMetaData::HasAllFlags (EBulkDataFlags Flags) const inline
Definition at line 411 of file BulkData.h.
References Flags, and GetFlags().
HasAnyFlags()
bool UE::BulkData::Private::FBulkMetaData::HasAnyFlags (EBulkDataFlags Flags) const inline
Definition at line 406 of file BulkData.h.
References Flags, and GetFlags().
ReadUInt40()
uint64 UE::BulkData::Private::FBulkMetaData::ReadUInt40 (const uint8 * Memory) inline static private
Definition at line 432 of file BulkData.h.
References Memory.
Referenced by GetOffset(), and GetSize().
SetFlags()
void UE::BulkData::Private::FBulkMetaData::SetFlags (EBulkDataFlags Flags) inline
Definition at line 391 of file BulkData.h.
References Data, and Flags.
Referenced by FBulkMetaData().
SetLockStatus()
void UE::BulkData::Private::FBulkMetaData::SetLockStatus (EBulkDataLockStatus Status) inline
Definition at line 381 of file BulkData.h.
References Data.
SetOffset()
void UE::BulkData::Private::FBulkMetaData::SetOffset (int64 Offset) inline
Definition at line 362 of file BulkData.h.
References check, Data, MAX_int64, MaxOffset, and WriteUInt40().
Referenced by FBulkMetaData().
SetSize()
void UE::BulkData::Private::FBulkMetaData::SetSize (int64 Size) inline
Definition at line 334 of file BulkData.h.
References check, Data, MaxSize, TSequenceHistory< HistorySize >::Size, and WriteUInt40().
SetSizeOnDisk()
void UE::BulkData::Private::FBulkMetaData::SetSizeOnDisk (int64 SizeOnDisk) inline
Definition at line 349 of file BulkData.h.
References Data.
Referenced by FBulkMetaData().
WriteUInt40()
void UE::BulkData::Private::FBulkMetaData::WriteUInt40 (uint8 * Memory, uint64 Value) inline static private
Definition at line 437 of file BulkData.h.
References Memory, and Value.
Referenced by SetOffset(), and SetSize().
Field Documentation
Data
uint8 UE::BulkData::Private::FBulkMetaData::Data[24] = {0} private
Definition at line 444 of file BulkData.h.
Referenced by AddFlags(), ClearFlags(), GetFlags(), GetLockStatus(), GetOffset(), GetSize(), GetSizeOnDisk(), SetFlags(), SetLockStatus(), SetOffset(), SetSize(), and SetSizeOnDisk().
MaxOffset
int64 UE::BulkData::Private::FBulkMetaData::MaxOffset = 0xFFffFFffFE static constexpr
39 bits for max bulk data offset and 1 bit to indicate INDEX_NONE.
Definition at line 313 of file BulkData.h.
Referenced by GetOffset(), and SetOffset().
MaxSize
int64 UE::BulkData::Private::FBulkMetaData::MaxSize = 0xFFffFFffFF static constexpr
40 bits for max bulk data size.
Definition at line 311 of file BulkData.h.
Referenced by SetSize().
The documentation for this class was generated from the following file:
BulkData.h