Unreal Engine 5.6 C++ API: UE::Geometry::TPolyline< T, D > Class Template Reference
UE::Geometry::TPolyline< T, D > Class Template Reference
TPolyline represents a dimensional independent polyline stored as a list of Vertices.
#include "Polyline.h"
Data Structures
class SegmentEnumerable
Wrapper around SegmentIterator that has begin() and end() suitable for range-based for loop.
class SegmentIterator
SegmentIterator is used to iterate over the segments of the polyline.
Public Member Functions
TPolyline ()
TPolyline (const TArray< VectorType > &VertexList)
Construct polyline with given list of vertices.
TPolyline (const VectorType &Point0, const VectorType &Point1)
Construct a single-segment polyline.
void AppendVertex (const VectorType &Position)
Add a vertex to the polyline.
template<typename OtherVectorType>
void AppendVertices (const TArray< OtherVectorType > &NewVertices)
Add a list of Vertices to the polyline.
void AppendVertices (const TArray< VectorType > &NewVertices)
Add a list of Vertices to the polyline.
T AverageEdgeLength () const
void Clear ()
Discard all vertices of polyline.
T DistanceSquared (const VectorType &QueryPoint) const
Calculate the squared distance from a point to the polyline.
T DistanceSquared (const VectorType &QueryPoint, int &NearestSegIndexOut, T &NearestSegParamOut) const
Calculate the squared distance from a point to the polyline.
const VectorType & End () const
BoxType GetBounds () const
SegmentType GetSegment (int SegmentIndex) const
VectorType GetSegmentPoint (int SegmentIndex, T SegmentParam) const
VectorType GetSegmentPointUnitParam (int SegmentIndex, T SegmentParam) const
VectorType GetTangent (int VertexIndex) const
Get the tangent vector at a vertex of the polyline, which is the normalized vector from the previous vertex to the next vertex.
const TArray< VectorType > & GetVertices () const
T Length () const
VectorType & operator[] (int Index)
Get the vertex at a given index.
const VectorType & operator[] (int Index) const
Get the vertex at a given index.
void RemoveVertex (int VertexIndex)
Remove a vertex of the polyline (existing Vertices are shifted)
void Reverse ()
Reverse the order of the Vertices in the polyline (ie switch between Clockwise and CounterClockwise)
int SegmentCount () const
SegmentIterator SegmentItr () const
SegmentEnumerable Segments () const
void Set (int VertexIndex, const VectorType &Position)
Set vertex at given index to a new Position.
void SetVertices (const TArray< VectorType > &NewVertices)
Replace the list of Vertices with a new list.
void Simplify (T ClusterTolerance, T LineDeviationTolerance)
Simplify the Polyline to reduce the vertex count.
void SmoothSubdivide (TPolyline< T, D > &NewPolyline) const
Produce a new polyline that is smoother than this one.
const VectorType & Start () const
int VertexCount () const
Protected Types
typedef TPolylinePolicy< T, D >::BoxType BoxType
typedef TPolylinePolicy< T, D >::SegmentType SegmentType
typedef TPolylinePolicy< T, D >::VectorType VectorType
Protected Attributes
TArray< VectorType > Vertices
The list of vertices of the polyline.
Static Private Member Functions
static void SimplifyDouglasPeucker (T Tolerance, const TArray< VectorType > &Vertices, int32 j, int32 k, TArray< bool > &Marked)
Friends
class SegmentIterator
Detailed Description
template<typename T, int D>
class UE::Geometry::TPolyline< T, D >
TPolyline represents a dimensional independent polyline stored as a list of Vertices.
Definition at line 48 of file Polyline.h.
Member Typedef Documentation
BoxType
template<typename T, int D> typedef TPolylinePolicy<T,D>::BoxType UE::Geometry::TPolyline< T, D >::BoxType protected
Definition at line 53 of file Polyline.h.
SegmentType
template<typename T, int D> typedef TPolylinePolicy<T,D>::SegmentType UE::Geometry::TPolyline< T, D >::SegmentType protected
Definition at line 52 of file Polyline.h.
VectorType
template<typename T, int D> typedef TPolylinePolicy<T,D>::VectorType UE::Geometry::TPolyline< T, D >::VectorType protected
Definition at line 51 of file Polyline.h.
Constructor & Destructor Documentation
TPolyline() [1/3]
template<typename T, int D> UE::Geometry::TPolyline< T, D >::TPolyline () inline
Definition at line 61 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, D >::SegmentEnumerable::SegmentEnumerable().
TPolyline() [2/3]
template<typename T, int D> UE::Geometry::TPolyline< T, D >::TPolyline (const TArray< VectorType > & VertexList) inline
Construct polyline with given list of vertices.
Definition at line 68 of file Polyline.h.
TPolyline() [3/3]
template<typename T, int D> UE::Geometry::TPolyline< T, D >::TPolyline (const VectorType & Point0, const VectorType & Point1) inline
Construct a single-segment polyline.
Definition at line 75 of file Polyline.h.
Member Function Documentation
AppendVertex()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::AppendVertex (const VectorType & Position) inline
Add a vertex to the polyline.
Definition at line 149 of file Polyline.h.
Referenced by FBoundaryTopologyProvider::GetEdgePolyline().
AppendVertices() [1/2]
template<typename T, int D> template<typename OtherVectorType> void UE::Geometry::TPolyline< T, D >::AppendVertices (const TArray< OtherVectorType > & NewVertices) inline
Add a list of Vertices to the polyline.
Definition at line 166 of file Polyline.h.
AppendVertices() [2/2]
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::AppendVertices (const TArray< VectorType > & NewVertices) inline
Add a list of Vertices to the polyline.
Definition at line 157 of file Polyline.h.
AverageEdgeLength()
template<typename T, int D> T UE::Geometry::TPolyline< T, D >::AverageEdgeLength () const inline
Returns
average edge length of all the edges of the Polygon
Definition at line 432 of file Polyline.h.
Clear()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::Clear () inline
Discard all vertices of polyline.
Definition at line 141 of file Polyline.h.
Referenced by FBoundaryTopologyProvider::GetEdgePolyline().
DistanceSquared() [1/2]
template<typename T, int D> T UE::Geometry::TPolyline< T, D >::DistanceSquared (const VectorType & QueryPoint) const inline
Calculate the squared distance from a point to the polyline.
Parameters
QueryPoint the query point
Returns
squared distance to the polyline
Definition at line 420 of file Polyline.h.
DistanceSquared() [2/2]
template<typename T, int D> T UE::Geometry::TPolyline< T, D >::DistanceSquared (const VectorType & QueryPoint, int & NearestSegIndexOut, T & NearestSegParamOut) const inline
Calculate the squared distance from a point to the polyline.
Parameters
QueryPoint the query point
NearestSegIndexOut The index of the nearest segment
NearestSegParamOut the parameter value of the nearest point on the segment
Returns
squared distance to the polyline
Definition at line 379 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, 2 >< double >::DistanceSquared().
End()
template<typename T, int D> const VectorType & UE::Geometry::TPolyline< T, D >::End () const inline
Returns
last vertex of polyline
Definition at line 109 of file Polyline.h.
GetBounds()
template<typename T, int D> BoxType UE::Geometry::TPolyline< T, D >::GetBounds () const inline
Returns
the bounding box of the polyline Vertices
Definition at line 276 of file Polyline.h.
GetSegment()
template<typename T, int D> SegmentType UE::Geometry::TPolyline< T, D >::GetSegment (int SegmentIndex) const inline
Returns
edge of the polyline starting at vertex SegmentIndex
Definition at line 242 of file Polyline.h.
GetSegmentPoint()
template<typename T, int D> VectorType UE::Geometry::TPolyline< T, D >::GetSegmentPoint (int SegmentIndex, T SegmentParam) const inline
Parameters
SegmentIndex index of first vertex of the edge
SegmentParam parameter in range [-Extent,Extent] along segment
Returns
point on the segment at the given parameter value
Definition at line 253 of file Polyline.h.
GetSegmentPointUnitParam()
template<typename T, int D> VectorType UE::Geometry::TPolyline< T, D >::GetSegmentPointUnitParam (int SegmentIndex, T SegmentParam) const inline
Parameters
SegmentIndex index of first vertex of the edge
SegmentParam parameter in range [0,1] along segment
Returns
point on the segment at the given parameter value
Definition at line 265 of file Polyline.h.
GetTangent()
template<typename T, int D> VectorType UE::Geometry::TPolyline< T, D >::GetTangent (int VertexIndex) const inline
Get the tangent vector at a vertex of the polyline, which is the normalized vector from the previous vertex to the next vertex.
Definition at line 223 of file Polyline.h.
GetVertices()
template<typename T, int D> const TArray< VectorType > & UE::Geometry::TPolyline< T, D >::GetVertices () const inline
Returns
list of Vertices of polyline
Definition at line 118 of file Polyline.h.
Length()
template<typename T, int D> T UE::Geometry::TPolyline< T, D >::Length () const inline
Returns
the total perimeter length of the Polygon
Definition at line 292 of file Polyline.h.
operator[]() [1/2]
template<typename T, int D> VectorType & UE::Geometry::TPolyline< T, D >::operator[] (int Index) inline
Get the vertex at a given index.
Definition at line 92 of file Polyline.h.
operator[]() [2/2]
template<typename T, int D> const VectorType & UE::Geometry::TPolyline< T, D >::operator[] (int Index) const inline
Get the vertex at a given index.
Definition at line 84 of file Polyline.h.
RemoveVertex()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::RemoveVertex (int VertexIndex) inline
Remove a vertex of the polyline (existing Vertices are shifted)
Definition at line 187 of file Polyline.h.
Reverse()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::Reverse () inline
Reverse the order of the Vertices in the polyline (ie switch between Clockwise and CounterClockwise)
Definition at line 209 of file Polyline.h.
SegmentCount()
template<typename T, int D> int UE::Geometry::TPolyline< T, D >::SegmentCount () const inline
Returns
number of segments in polyline
Definition at line 134 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, 2 >< double >::DistanceSquared(), UE::Geometry::TPolyline< T, 2 >< double >::Length(), and UE::Geometry::TPolyline< T, D >::SegmentIterator::operator*().
SegmentItr()
template<typename T, int D> SegmentIterator UE::Geometry::TPolyline< T, D >::SegmentItr () const inline
Definition at line 341 of file Polyline.h.
Segments()
template<typename T, int D> SegmentEnumerable UE::Geometry::TPolyline< T, D >::Segments () const inline
Returns
an object that can be used in a range-based for loop to iterate over the Segments of the Polyline
Definition at line 362 of file Polyline.h.
Set()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::Set (int VertexIndex, const VectorType & Position) inline
Set vertex at given index to a new Position.
Definition at line 179 of file Polyline.h.
SetVertices()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::SetVertices (const TArray< VectorType > & NewVertices) inline
Replace the list of Vertices with a new list.
Definition at line 195 of file Polyline.h.
Simplify()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::Simplify (T ClusterTolerance, T LineDeviationTolerance) inline
Simplify the Polyline to reduce the vertex count.
Parameters
ClusterTolerance Vertices closer than this distance will be merged into a single vertex
LineDeviationTolerance Vertices are allowed to deviate this much from the polylines
Definition at line 471 of file Polyline.h.
SimplifyDouglasPeucker()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::SimplifyDouglasPeucker (T Tolerance, const TArray< VectorType > & Vertices, int32 j, int32 k, TArray< bool > & Marked) inline static private
Definition at line 547 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), and UE::Geometry::TPolyline< T, 2 >< double >::SimplifyDouglasPeucker().
SmoothSubdivide()
template<typename T, int D> void UE::Geometry::TPolyline< T, D >::SmoothSubdivide (TPolyline< T, D > & NewPolyline) const inline
Produce a new polyline that is smoother than this one.
Definition at line 446 of file Polyline.h.
Start()
template<typename T, int D> const VectorType & UE::Geometry::TPolyline< T, D >::Start () const inline
Returns
first vertex of polyline
Definition at line 101 of file Polyline.h.
VertexCount()
template<typename T, int D> int UE::Geometry::TPolyline< T, D >::VertexCount () const inline
Returns
number of Vertices in polyline
Definition at line 126 of file Polyline.h.
Friends And Related Symbol Documentation
SegmentIterator
template<typename T, int D> friend class SegmentIterator friend
Definition at line 339 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, D >::SegmentEnumerable::end(), and UE::Geometry::TPolyline< T, 2 >< double >::SegmentItr().
Field Documentation
Vertices
template<typename T, int D> TArray<VectorType> UE::Geometry::TPolyline< T, D >::Vertices protected
The list of vertices of the polyline.
Definition at line 56 of file Polyline.h.
Referenced by UE::Geometry::TPolyline< T, 2 >< double >::SmoothSubdivide().
The documentation for this class was generated from the following file:
Polyline.h