Unreal Engine 5.6 C++ API: FTextFormat Class Reference
FTextFormat Class Reference
Cached compiled expression used by the text formatter.
#include "Text.h"
Public Types
enum class EExpressionType { Invalid , Simple , Complex }
Public Member Functions
FTextFormat ()
Construct an instance using an empty FText.
FTextFormat (const FText &InText, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
Construct an instance from an FText.
FTextFormat (const FText &InText, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
Construct an instance from an FText and custom format pattern definition.
EExpressionType GetExpressionType () const
Get the type of expression currently compiled.
void GetFormatArgumentNames (TArray< FString > &OutArgumentNames) const
Append the names of any arguments to the given array.
ETextFormatFlags GetFormatFlags () const
Get the format flags being used.
FTextFormatPatternDefinitionConstRef GetPatternDefinition () const
Get the format pattern definition being used.
const FString & GetSourceString () const
Get the source string that we're holding.
FText GetSourceText () const
Get the source text that we're holding.
bool IdenticalTo (const FTextFormat &Other, const ETextIdenticalModeFlags CompareModeFlags) const
Check whether this instance is considered identical to the other instance, based on the comparison flags provided.
bool IsValid () const
Test to see whether this instance contains valid compiled data.
bool ValidatePattern (const FCulturePtr &InCulture, TArray< FString > &OutValidationErrors) const
Validate the format pattern is valid based on the rules of the given culture (or null to use the current language).
Static Public Member Functions
static FTextFormat FromString (const FString &InString, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
Construct an instance from an FString.
static FTextFormat FromString (const FString &InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
Construct an instance from an FString and custom format pattern definition.
static FTextFormat FromString (FString &&InString, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
static FTextFormat FromString (FString &&InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags=ETextFormatFlags::Default)
Private Member Functions
FTextFormat (FString &&InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags)
Construct an instance from an FString.
Private Attributes
TSharedRef< FTextFormatData, ESPMode::ThreadSafe > TextFormatData
Cached compiled expression data.
Friends
class FTextFormatter
Detailed Description
Cached compiled expression used by the text formatter.
The compiled expression will automatically update if the display string is changed, and is safe to be used as a function-level static. See TextFormatter.cpp for the definition.
Definition at line 277 of file Text.h.
Member Enumeration Documentation
EExpressionType
enum class FTextFormat::EExpressionType strong
Enumerator
Invalid
Invalid expression.
Simple
Simple expression, containing no arguments or argument modifiers.
Complex
Complex expression, containing arguments or argument modifiers.
Definition at line 282 of file Text.h.
Constructor & Destructor Documentation
FTextFormat() [1/4]
FTextFormat::FTextFormat ()
Construct an instance using an empty FText.
Referenced by FromString(), FromString(), FromString(), FromString(), and IdenticalTo().
FTextFormat() [2/4]
FTextFormat::FTextFormat (const FText & InText, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default)
Construct an instance from an FText.
The text will be immediately compiled.
References Default.
FTextFormat() [3/4]
FTextFormat::FTextFormat (const FText & InText, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default)
Construct an instance from an FText and custom format pattern definition.
The text will be immediately compiled.
References Default.
FTextFormat() [4/4]
FTextFormat::FTextFormat (FString && InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags) private
Construct an instance from an FString.
The string will be immediately compiled.
Member Function Documentation
FromString() [1/4]
FTextFormat FTextFormat::FromString (const FString & InString, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default) static
Construct an instance from an FString.
The string will be immediately compiled.
References FTextFormat(), and Default.
Referenced by TraceServices::FMetadataSchema::FReader::GetText().
FromString() [2/4]
FTextFormat FTextFormat::FromString (const FString & InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default) static
Construct an instance from an FString and custom format pattern definition.
The string will be immediately compiled.
References FTextFormat(), and Default.
FromString() [3/4]
FTextFormat FTextFormat::FromString (FString && InString, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default) static
References FTextFormat(), and Default.
FromString() [4/4]
FTextFormat FTextFormat::FromString (FString && InString, FTextFormatPatternDefinitionConstRef InCustomPatternDef, ETextFormatFlags InFormatFlags = ETextFormatFlags::Default) static
References FTextFormat(), and Default.
GetExpressionType()
EExpressionType FTextFormat::GetExpressionType () const
Get the type of expression currently compiled.
GetFormatArgumentNames()
void FTextFormat::GetFormatArgumentNames (TArray< FString > & OutArgumentNames) const
Append the names of any arguments to the given array.
GetFormatFlags()
ETextFormatFlags FTextFormat::GetFormatFlags () const
Get the format flags being used.
GetPatternDefinition()
FTextFormatPatternDefinitionConstRef FTextFormat::GetPatternDefinition () const
Get the format pattern definition being used.
GetSourceString()
const FString & FTextFormat::GetSourceString () const
Get the source string that we're holding.
If we're holding a text then we'll return its internal string.
GetSourceText()
FText FTextFormat::GetSourceText () const
Get the source text that we're holding.
If we're holding a string then we'll construct a new text.
IdenticalTo()
bool FTextFormat::IdenticalTo (const FTextFormat & Other, const ETextIdenticalModeFlags CompareModeFlags) const
Check whether this instance is considered identical to the other instance, based on the comparison flags provided.
References FTextFormat(), and Other.
IsValid()
bool FTextFormat::IsValid () const
Test to see whether this instance contains valid compiled data.
ValidatePattern()
bool FTextFormat::ValidatePattern (const FCulturePtr & InCulture, TArray< FString > & OutValidationErrors) const
Validate the format pattern is valid based on the rules of the given culture (or null to use the current language).
Returns
true if the pattern is valid, or false if not (false may also fill in OutValidationErrors).
Friends And Related Symbol Documentation
FTextFormatter
friend class FTextFormatter friend
Definition at line 279 of file Text.h.
References FTextFormatter.
Referenced by FTextFormatter.
Field Documentation
TextFormatData
TSharedRef<FTextFormatData, ESPMode::ThreadSafe> FTextFormat::TextFormatData private
Cached compiled expression data.
Definition at line 379 of file Text.h.
The documentation for this class was generated from the following file:
Text.h