Unreal Engine 5.6 C++ API: FStateTreeWeakExecutionContext Struct Reference
FStateTreeWeakExecutionContext Struct Reference
Execution context that can be saved/copied and used asynchronously.
#include "StateTreeAsyncExecutionContext.h"
Public Member Functions
FStateTreeWeakExecutionContext ()=default
STATETREEMODULE_API FStateTreeWeakExecutionContext (const FStateTreeExecutionContext &Context)
STATETREEMODULE_API bool BindDelegate (const FStateTreeDelegateListener &Listener, FSimpleDelegate Delegate) const
Registers the delegate to the listener.
STATETREEMODULE_API bool BroadcastDelegate (const FStateTreeDelegateDispatcher &Dispatcher) const
Broadcasts the delegate.
STATETREEMODULE_API bool FinishTask (EStateTreeFinishTaskType FinishType) const
Finishes a task.
TStrongObjectPtr< UObject > GetOwner () const
TStrongObjectPtr< const UStateTree > GetStateTree () const
FStateTreeStrongExecutionContext MakeStrongExecutionContext () const
FStateTreeStrongReadOnlyExecutionContext MakeStrongReadOnlyExecutionContext () const
STATETREEMODULE_API bool RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority=EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback=EStateTreeSelectionFallback::None) const
Requests transition to a state.
STATETREEMODULE_API bool SendEvent (const FGameplayTag Tag, const FConstStructView Payload=FConstStructView(), const FName Origin=FName()) const
Sends event for the StateTree.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Use the version without FStateTreeWeakTaskRef") STATETREEMODULE_API bool BindDelegate(const FStateTreeWeakTaskRef &Task
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Use the version without FStateTreeWeakTaskRef.") STATETREEMODULE_API bool FinishTask(const FStateTreeWeakTaskRef &Task
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Use UnbindDelegate") STATETREEMODULE_API bool RemoveDelegateListener(const FStateTreeDelegateListener &Listener) const
Removes Delegate Listener.
STATETREEMODULE_API bool UnbindDelegate (const FStateTreeDelegateListener &Listener) const
Unregisters the callback bound to the listener.
PRAGMA_ENABLE_DEPRECATION_WARNINGS STATETREEMODULE_API bool UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick) const
Updates the scheduled tick of a previous request.
Data Fields
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FStateTreeDelegateListener FSimpleDelegate Delegate const
PRAGMA_DISABLE_DEPRECATION_WARNINGS EStateTreeFinishTaskType FinishType const
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FStateTreeDelegateListener & Listener
Private Attributes
UE::StateTree::FActiveFrameID FrameID
FStateTreeIndex16 NodeIndex
TWeakObjectPtr< UObject > Owner
UE::StateTree::FActiveStateID StateID
TWeakObjectPtr< const UStateTree > StateTree
TWeakPtr< FStateTreeInstanceStorage > Storage
Friends
template<bool bRequireWriteAccess>
struct TStateTreeStrongExecutionContext
Detailed Description
Execution context that can be saved/copied and used asynchronously.
You are responsible for making it thread-safe if needed. The context is valid if the state (or global context) from which it was created is still active. The owner, state tree, and storage also need to be valid.
ThreadSafeAsyncCallback.AddLambda(
    [MyTag, WeakContext = Context.MakeWeakExecutionContext]()
    {
        if (WeakContext.SendEvent(MyTag))
        {
            ...
        }
    });
Definition at line 222 of file StateTreeAsyncExecutionContext.h.
Constructor & Destructor Documentation
FStateTreeWeakExecutionContext() [1/2]
FStateTreeWeakExecutionContext::FStateTreeWeakExecutionContext () default
FStateTreeWeakExecutionContext() [2/2]
STATETREEMODULE_API FStateTreeWeakExecutionContext::FStateTreeWeakExecutionContext (const FStateTreeExecutionContext & Context) explicit
References UE_API.
Member Function Documentation
BindDelegate()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::BindDelegate (const FStateTreeDelegateListener & Listener, FSimpleDelegate Delegate) const
Registers the delegate to the listener.
If the listener was previously registered, then unregister it first before registering it again with the new delegate callback. The listener is bound to a dispatcher in the editor.
Returns
false if the context is not valid or doesn't have a valid frame anymore or the bind failed.
References Listener, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
BroadcastDelegate()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::BroadcastDelegate (const FStateTreeDelegateDispatcher & Dispatcher) const
Broadcasts the delegate.
It executes bound delegates immediately and triggers bound transitions (when transitions are evaluated).
Returns
false if the context is not valid or doesn't have a valid frame anymore or the broadcast failed.
References UE_API.
FinishTask()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::FinishTask (EStateTreeFinishTaskType FinishType) const
Finishes a task.
If called during tick processing, then the state completes immediately. If called outside of the tick processing, then the request is buffered and handled on the next tick.
Returns
false if the context is not valid or doesn't have a valid frame anymore or finish task failed.
References const, FinishTask(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and UE_API.
Referenced by FinishTask().
GetOwner()
TStrongObjectPtr< UObject > FStateTreeWeakExecutionContext::GetOwner () const inline
Returns
The owner of the context
Definition at line 233 of file StateTreeAsyncExecutionContext.h.
References Owner.
GetStateTree()
TStrongObjectPtr< const UStateTree > FStateTreeWeakExecutionContext::GetStateTree () const inline
Returns
the StateTree asset in use.
Definition at line 239 of file StateTreeAsyncExecutionContext.h.
References StateTree.
MakeStrongExecutionContext()
FStateTreeStrongExecutionContext FStateTreeWeakExecutionContext::MakeStrongExecutionContext () const inline
Definition at line 249 of file StateTreeAsyncExecutionContext.h.
MakeStrongReadOnlyExecutionContext()
FStateTreeStrongReadOnlyExecutionContext FStateTreeWeakExecutionContext::MakeStrongReadOnlyExecutionContext () const inline
Definition at line 244 of file StateTreeAsyncExecutionContext.h.
RequestTransition()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::RequestTransition (FStateTreeStateHandle TargetState, EStateTreeTransitionPriority Priority = EStateTreeTransitionPriority::Normal, EStateTreeSelectionFallback Fallback = EStateTreeSelectionFallback::None) const
Requests transition to a state.
If called during transition processing (e.g. from FStateTreeTaskBase::TriggerTransitions()) the transition is attempted to be activated immediately (it can fail e.g. because of preconditions on a target state). If called outside the transition handling, the request is buffered and handled at the beginning of next transition processing.
Parameters
TargetState The state to transition to.
Priority The priority of the transition.
Fallback of the transition if it fails to select the target state.
Returns
false if the context is not valid or doesn't have a valid frame anymore or the request failed.
References UE_API.
SendEvent()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::SendEvent (const FGameplayTag Tag, const FConstStructView Payload = FConstStructView(), const FName Origin = FName()) const
Sends event for the StateTree.
Returns
false if the context is not valid or the event could not be sent.
References Origin, and UE_API.
UE_DEPRECATED() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeWeakExecutionContext::UE_DEPRECATED (5. 6, "Use the version without FStateTreeWeakTaskRef") const &
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FStateTreeWeakExecutionContext::UE_DEPRECATED (5. 6, "Use the version without FStateTreeWeakTaskRef.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FStateTreeWeakExecutionContext::UE_DEPRECATED (5. 6, "Use UnbindDelegate") const &
Removes Delegate Listener.
References const, Listener, UE_API, and UE_DEPRECATED().
UnbindDelegate()
STATETREEMODULE_API bool FStateTreeWeakExecutionContext::UnbindDelegate (const FStateTreeDelegateListener & Listener) const
Unregisters the callback bound to the listener.
Returns
false if the context is not valid or the unbind failed.
References const, Listener, UE_API, and UnbindDelegate().
Referenced by UnbindDelegate().
UpdateScheduledTickRequest()
PRAGMA_ENABLE_DEPRECATION_WARNINGS STATETREEMODULE_API bool FStateTreeWeakExecutionContext::UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick) const
Updates the scheduled tick of a previous request.
Returns
false if the context is not valid.
References const, Handle, StateTree, UE_API, and UpdateScheduledTickRequest().
Referenced by UpdateScheduledTickRequest().
Friends And Related Symbol Documentation
TStateTreeStrongExecutionContext
template<bool bRequireWriteAccess> friend struct TStateTreeStrongExecutionContext friend
Definition at line 225 of file StateTreeAsyncExecutionContext.h.
References TStateTreeStrongExecutionContext.
Referenced by TStateTreeStrongExecutionContext.
Field Documentation
const [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FStateTreeDelegateListener FSimpleDelegate Delegate FStateTreeWeakExecutionContext::const
Definition at line 289 of file StateTreeAsyncExecutionContext.h.
Referenced by FinishTask(), UE_DEPRECATED(), UnbindDelegate(), and UpdateScheduledTickRequest().
const [2/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS EStateTreeFinishTaskType FinishType FStateTreeWeakExecutionContext::const
Definition at line 312 of file StateTreeAsyncExecutionContext.h.
FrameID
UE::StateTree::FActiveFrameID FStateTreeWeakExecutionContext::FrameID private
Definition at line 326 of file StateTreeAsyncExecutionContext.h.
Listener
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FStateTreeDelegateListener& FStateTreeWeakExecutionContext::Listener
Definition at line 289 of file StateTreeAsyncExecutionContext.h.
Referenced by BindDelegate(), UE_DEPRECATED(), and UnbindDelegate().
NodeIndex
FStateTreeIndex16 FStateTreeWeakExecutionContext::NodeIndex private
Definition at line 328 of file StateTreeAsyncExecutionContext.h.
Owner
TWeakObjectPtr<UObject> FStateTreeWeakExecutionContext::Owner private
Definition at line 322 of file StateTreeAsyncExecutionContext.h.
Referenced by GetOwner().
StateID
UE::StateTree::FActiveStateID FStateTreeWeakExecutionContext::StateID private
Definition at line 327 of file StateTreeAsyncExecutionContext.h.
StateTree
TWeakObjectPtr<const UStateTree> FStateTreeWeakExecutionContext::StateTree private
Definition at line 323 of file StateTreeAsyncExecutionContext.h.
Referenced by GetStateTree(), and UpdateScheduledTickRequest().
Storage
TWeakPtr<FStateTreeInstanceStorage> FStateTreeWeakExecutionContext::Storage private
Definition at line 324 of file StateTreeAsyncExecutionContext.h.
The documentation for this struct was generated from the following file:
StateTreeAsyncExecutionContext.h