Unreal Engine 5.6 C++ API: WeakFieldPtr.h File Reference
WeakFieldPtr.h File Reference
#include "Templates/Requires.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "UObject/WeakObjectPtr.h"
#include "UObject/FieldPath.h"
#include <type_traits>
Data Structures
struct TIsPODType< TWeakFieldPtr< T > >
struct TIsWeakPointerType< TWeakFieldPtr< T > >
struct TIsZeroConstructType< TWeakFieldPtr< T > >
struct TWeakFieldPtr< T >
struct TWeakFieldPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >
MapKeyFuncs for TWeakFieldPtrs which allow the key to become stale without invalidating the map.
Functions
template<typename T>
FORCEINLINE TWeakFieldPtr< T > MakeWeakFieldPtr (T *Ptr)
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator!= (const LhsType *Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for inequality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator!= (const LhsType *Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for inequality.
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator!= (const TWeakFieldPtr< LhsType > &Lhs, const RhsType *Rhs)
Compare weak pointers for inequality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > &Lhs, const RhsType *Rhs)
Compare weak pointers for inequality.
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator!= (const TWeakFieldPtr< LhsType > &Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for inequality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > &Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for inequality.
template<typename LhsType>
FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > &Lhs, TYPE_OF_NULLPTR)
Test weak pointer for non-null.
template<typename RhsType>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, const TWeakFieldPtr< RhsType > &Rhs)
Test weak pointer for non-null.
template<class T>
FArchive & operator<< (FArchive &Ar, TWeakFieldPtr< T > &WeakFieldPtr)
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator== (const LhsType *Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for equality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator== (const LhsType *Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for equality.
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator== (const TWeakFieldPtr< LhsType > &Lhs, const RhsType *Rhs)
Compare weak pointers for equality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > &Lhs, const RhsType *Rhs)
Compare weak pointers for equality.
template<typename LhsType, typename RhsType UE_REQUIRES>
bool operator== (const TWeakFieldPtr< LhsType > &Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for equality.
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION>
FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > &Lhs, const TWeakFieldPtr< RhsType > &Rhs)
Compare weak pointers for equality.
template<typename LhsType>
FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > &Lhs, TYPE_OF_NULLPTR)
Test weak pointer for null.
template<typename RhsType>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, const TWeakFieldPtr< RhsType > &Rhs)
Test weak pointer for null.
Function Documentation
MakeWeakFieldPtr()
template<typename T> FORCEINLINE TWeakFieldPtr< T > MakeWeakFieldPtr (T * Ptr)
Definition at line 460 of file WeakFieldPtr.h.
References TWeakFieldPtr< T >::TWeakFieldPtr, and FORCEINLINE.
operator!=() [1/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator!= (const LhsType * Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for inequality.
Parameters
Lhs pointer to compare
Rhs weak pointer to compare
Definition at line 432 of file WeakFieldPtr.h.
operator!=() [2/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator!= (const LhsType * Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for inequality.
Parameters
Lhs pointer to compare
Rhs weak pointer to compare
Definition at line 432 of file WeakFieldPtr.h.
operator!=() [3/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator!= (const TWeakFieldPtr< LhsType > & Lhs, const RhsType * Rhs)
Compare weak pointers for inequality.
Parameters
Lhs weak pointer to compare
Rhs pointer to compare
Definition at line 417 of file WeakFieldPtr.h.
operator!=() [4/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > & Lhs, const RhsType * Rhs)
Compare weak pointers for inequality.
Parameters
Lhs weak pointer to compare
Rhs pointer to compare
Definition at line 417 of file WeakFieldPtr.h.
operator!=() [5/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator!= (const TWeakFieldPtr< LhsType > & Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for inequality.
Parameters
Lhs weak pointer to compare
Rhs weak pointer to compare
Definition at line 402 of file WeakFieldPtr.h.
operator!=() [6/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > & Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for inequality.
Parameters
Lhs weak pointer to compare
Rhs weak pointer to compare
Definition at line 402 of file WeakFieldPtr.h.
operator!=() [7/8]
template<typename LhsType> FORCEINLINE bool operator!= (const TWeakFieldPtr< LhsType > & Lhs, TYPE_OF_NULLPTR)
Test weak pointer for non-null.
Parameters
Lhs weak pointer to test
Definition at line 442 of file WeakFieldPtr.h.
References FORCEINLINE.
operator!=() [8/8]
template<typename RhsType> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , const TWeakFieldPtr< RhsType > & Rhs)
Test weak pointer for non-null.
Parameters
Rhs weak pointer to test
Definition at line 452 of file WeakFieldPtr.h.
References FORCEINLINE.
operator<<()
template<class T> FArchive & operator<< (FArchive & Ar, TWeakFieldPtr< T > & WeakFieldPtr)
Definition at line 490 of file WeakFieldPtr.h.
References Ar, and TWeakFieldPtr< T >::Serialize().
operator==() [1/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator== (const LhsType * Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for equality.
Parameters
Lhs pointer to compare
Rhs weak pointer to compare
Definition at line 366 of file WeakFieldPtr.h.
operator==() [2/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator== (const LhsType * Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for equality.
Parameters
Lhs pointer to compare
Rhs weak pointer to compare
Definition at line 366 of file WeakFieldPtr.h.
operator==() [3/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator== (const TWeakFieldPtr< LhsType > & Lhs, const RhsType * Rhs)
Compare weak pointers for equality.
Parameters
Lhs weak pointer to compare
Rhs pointer to compare
Definition at line 351 of file WeakFieldPtr.h.
operator==() [4/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > & Lhs, const RhsType * Rhs)
Compare weak pointers for equality.
Parameters
Lhs weak pointer to compare
Rhs pointer to compare
Definition at line 351 of file WeakFieldPtr.h.
operator==() [5/8]
template<typename LhsType, typename RhsType UE_REQUIRES> bool operator== (const TWeakFieldPtr< LhsType > & Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for equality.
Parameters
Lhs weak pointer to compare
Rhs weak pointer to compare
Definition at line 336 of file WeakFieldPtr.h.
operator==() [6/8]
template<typename LhsType, typename RhsType UE_REQUIRES_DEFINITION> FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > & Lhs, const TWeakFieldPtr< RhsType > & Rhs)
Compare weak pointers for equality.
Parameters
Lhs weak pointer to compare
Rhs weak pointer to compare
Definition at line 336 of file WeakFieldPtr.h.
operator==() [7/8]
template<typename LhsType> FORCEINLINE bool operator== (const TWeakFieldPtr< LhsType > & Lhs, TYPE_OF_NULLPTR)
Test weak pointer for null.
Parameters
Lhs weak pointer to test
Definition at line 376 of file WeakFieldPtr.h.
References FORCEINLINE, and TWeakFieldPtr< T >::Get().
operator==() [8/8]
template<typename RhsType> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , const TWeakFieldPtr< RhsType > & Rhs)
Test weak pointer for null.
Parameters
Rhs weak pointer to test
Definition at line 386 of file WeakFieldPtr.h.
References FORCEINLINE, and TWeakFieldPtr< T >::Get().