Unreal Engine 5.6 C++ API: FEvaluationTreeEntryHandle Struct Reference
FEvaluationTreeEntryHandle Struct Reference
A structure that uniquely identifies an entry within a TEvaluationTreeEntryContainer.
#include "MovieSceneEvaluationTree.h"
Public Member Functions
FEvaluationTreeEntryHandle ()
Default construction to an invalid handle.
bool IsValid () const
Check whether this identifier has been initialized.
Private Member Functions
FEvaluationTreeEntryHandle (int32 InEntryIndex)
Private Attributes
int32 EntryIndex
Specifies an index into TEvaluationTreeEntryContainer<T>::Entries.
Friends
bool operator!= (const FEvaluationTreeEntryHandle &A, const FEvaluationTreeEntryHandle &B)
Inequality operator.
FArchive & operator<< (FArchive &Ar, FEvaluationTreeEntryHandle &In)
Serialization operator.
bool operator== (const FEvaluationTreeEntryHandle &A, const FEvaluationTreeEntryHandle &B)
Equality operator.
template<typename T>
struct TEvaluationTreeEntryContainer
template<typename T>
struct TMovieSceneEvaluationTreeFormatter
Detailed Description
A structure that uniquely identifies an entry within a TEvaluationTreeEntryContainer.
Definition at line 25 of file MovieSceneEvaluationTree.h.
Constructor & Destructor Documentation
FEvaluationTreeEntryHandle() [1/2]
FEvaluationTreeEntryHandle::FEvaluationTreeEntryHandle () inline
Default construction to an invalid handle.
Definition at line 30 of file MovieSceneEvaluationTree.h.
References EntryIndex, and INDEX_NONE.
Referenced by operator!=, operator<<, and operator==.
FEvaluationTreeEntryHandle() [2/2]
FEvaluationTreeEntryHandle::FEvaluationTreeEntryHandle (int32 InEntryIndex) inline private
Definition at line 60 of file MovieSceneEvaluationTree.h.
References EntryIndex.
Member Function Documentation
IsValid()
bool FEvaluationTreeEntryHandle::IsValid () const inline
Check whether this identifier has been initialized.
Caution: does not check that the identifier is valid within a given TEvaluationTreeEntryContainer
Definition at line 37 of file MovieSceneEvaluationTree.h.
References EntryIndex, and INDEX_NONE.
Referenced by TMovieSceneEvaluationTree< DataType >::GetDataForSingleNode(), TMovieSceneEvaluationTree< DataType >::GetMutableDataForSingleNode(), FMovieSceneEvaluationTree::GetNode(), FMovieSceneEvaluationTree::GetNode(), TMovieSceneEvaluationTree< DataType >::FAddOperator::operator()(), and TMovieSceneEvaluationTree< DataType >::FAddUniqueOperator::operator()().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FEvaluationTreeEntryHandle & A, const FEvaluationTreeEntryHandle & B) friend
Inequality operator.
Definition at line 50 of file MovieSceneEvaluationTree.h.
References FEvaluationTreeEntryHandle(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FEvaluationTreeEntryHandle & In) friend
Serialization operator.
Definition at line 55 of file MovieSceneEvaluationTree.h.
References FEvaluationTreeEntryHandle(), Ar, and EntryIndex.
operator==
bool operator== (const FEvaluationTreeEntryHandle & A, const FEvaluationTreeEntryHandle & B) friend
Equality operator.
Definition at line 45 of file MovieSceneEvaluationTree.h.
References FEvaluationTreeEntryHandle(), A, and B.
TEvaluationTreeEntryContainer
template<typename T> friend struct TEvaluationTreeEntryContainer friend
Definition at line 58 of file MovieSceneEvaluationTree.h.
References TEvaluationTreeEntryContainer.
Referenced by TEvaluationTreeEntryContainer.
TMovieSceneEvaluationTreeFormatter
template<typename T> friend struct TMovieSceneEvaluationTreeFormatter friend
Definition at line 59 of file MovieSceneEvaluationTree.h.
References TMovieSceneEvaluationTreeFormatter.
Referenced by TMovieSceneEvaluationTreeFormatter.
Field Documentation
EntryIndex
int32 FEvaluationTreeEntryHandle::EntryIndex private
Specifies an index into TEvaluationTreeEntryContainer<T>::Entries.
Definition at line 63 of file MovieSceneEvaluationTree.h.
Referenced by FEvaluationTreeEntryHandle(), FEvaluationTreeEntryHandle(), IsValid(), and operator<<.
The documentation for this struct was generated from the following file:
MovieSceneEvaluationTree.h