Unreal Engine 5.6 C++ API: FPropertyVisitorPath Struct Reference
FPropertyVisitorPath Struct Reference
#include "PropertyVisitor.h"
Public Types
using Iterator = TArray<FPropertyVisitorInfo>::TConstIterator
Iterator for a property visitor path.
Public Member Functions
FPropertyVisitorPath ()=default
FPropertyVisitorPath (const FArchiveSerializedPropertyChain &PropertyChain)
FPropertyVisitorPath (const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
FPropertyVisitorPath (const FPropertyVisitorInfo &Info)
FPropertyVisitorPath (const FPropertyVisitorPath &)=default
FPropertyVisitorPath (FPropertyVisitorPath &&)=default
FPropertyVisitorPath (TArrayView< const FPropertyVisitorInfo > InPath)
void AppendString (FStringBuilderBase &Out, const TCHAR *Separator=TEXT(".")) const
bool Contained (const FPropertyVisitorPath &OtherPath, bool *bIsEqual=nullptr) const
Is this property path contained in the specified one.
const TArray< FPropertyVisitorInfo > & GetPath () const
void * GetPropertyDataPtr (UObject *Object) const
Retrieves the data using the specified root object.
Iterator GetRootIterator () const
Returns an iterator on the root path node, useful when calling methods that are recursive.
int32 Num () const
FPropertyVisitorPath & operator= (const FPropertyVisitorPath &)=default
FPropertyVisitorPath & operator= (FPropertyVisitorPath &&)=default
FPropertyVisitorInfo Pop ()
void Push (const FPropertyVisitorInfo &Info)
FPropertyVisitorInfo & Top ()
const FPropertyVisitorInfo & Top () const
FArchiveSerializedPropertyChain ToSerializedPropertyChain () const
Converts path to an archive serialized property chain This method useful when APIs like in the FOverridableManager are taking in a FArchiveSerializedPropertyChain parameter and would like to use them.
FString ToString (const TCHAR *Separator=TEXT(".")) const
void ToString (FStringBuilderBase &Out, const TCHAR *Separator=TEXT(".")) const
Static Public Member Functions
static Iterator InvalidIterator ()
Invalid iterator pointing to an empty path.
Protected Attributes
TArray< FPropertyVisitorInfo > Path
Friends
uint32 GetTypeHash (const FPropertyVisitorPath &A)
bool operator!= (const FPropertyVisitorPath &A, const FPropertyVisitorPath &B)
bool operator== (const FPropertyVisitorPath &A, const FPropertyVisitorPath &B)
Detailed Description
Definition at line 91 of file PropertyVisitor.h.
Member Typedef Documentation
Iterator
using FPropertyVisitorPath::Iterator = TArray<FPropertyVisitorInfo>::TConstIterator
Iterator for a property visitor path.
Definition at line 179 of file PropertyVisitor.h.
Constructor & Destructor Documentation
FPropertyVisitorPath() [1/7]
FPropertyVisitorPath::FPropertyVisitorPath () default
Referenced by FPropertyVisitorPath(), FPropertyVisitorPath(), Contained(), GetTypeHash, operator!=, operator=(), operator=(), and operator==.
FPropertyVisitorPath() [2/7]
FPropertyVisitorPath::FPropertyVisitorPath (const FPropertyVisitorPath &) default
References FPropertyVisitorPath().
FPropertyVisitorPath() [3/7]
FPropertyVisitorPath::FPropertyVisitorPath (FPropertyVisitorPath &&) default
References FPropertyVisitorPath().
FPropertyVisitorPath() [4/7]
FPropertyVisitorPath::FPropertyVisitorPath (const FPropertyVisitorInfo & Info) inline explicit
Definition at line 102 of file PropertyVisitor.h.
References Info, and Push().
FPropertyVisitorPath() [5/7]
FPropertyVisitorPath::FPropertyVisitorPath (TArrayView< const FPropertyVisitorInfo > InPath) inline explicit
Definition at line 107 of file PropertyVisitor.h.
References Path.
FPropertyVisitorPath() [6/7]
FPropertyVisitorPath::FPropertyVisitorPath (const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain) explicit
FPropertyVisitorPath() [7/7]
FPropertyVisitorPath::FPropertyVisitorPath (const FArchiveSerializedPropertyChain & PropertyChain) explicit
Member Function Documentation
AppendString()
void FPropertyVisitorPath::AppendString (FStringBuilderBase & Out, const TCHAR * Separator = TEXT(".")) const
Contained()
bool FPropertyVisitorPath::Contained (const FPropertyVisitorPath & OtherPath, bool * bIsEqual = nullptr) const
Is this property path contained in the specified one.
Parameters
OtherPath property path to check if it is contained in
bIsEqual optional parameter to know if it fully match
Returns
true if it is contained in the specified path
References FPropertyVisitorPath().
GetPath()
const TArray< FPropertyVisitorInfo > & FPropertyVisitorPath::GetPath () const inline
Definition at line 140 of file PropertyVisitor.h.
References Path.
GetPropertyDataPtr()
void * FPropertyVisitorPath::GetPropertyDataPtr (UObject * Object) const
Retrieves the data using the specified root object.
Parameters
Object to search into
Returns
References Object.
GetRootIterator()
Iterator FPropertyVisitorPath::GetRootIterator () const inline
Returns an iterator on the root path node, useful when calling methods that are recursive.
Returns
an iterator on the root path node
Definition at line 185 of file PropertyVisitor.h.
References Path.
Referenced by FOverridableManager::ClearOverriddenProperty(), and FOverridableManager::GetOverriddenPropertyOperation().
InvalidIterator()
Iterator FPropertyVisitorPath::InvalidIterator () static
Invalid iterator pointing to an empty path.
Returns
an iterator to an empty path
Num()
int32 FPropertyVisitorPath::Num () const inline
Definition at line 125 of file PropertyVisitor.h.
References Path.
operator=() [1/2]
FPropertyVisitorPath & FPropertyVisitorPath::operator= (const FPropertyVisitorPath &) default
References FPropertyVisitorPath().
operator=() [2/2]
FPropertyVisitorPath & FPropertyVisitorPath::operator= (FPropertyVisitorPath &&) default
References FPropertyVisitorPath().
Pop()
FPropertyVisitorInfo FPropertyVisitorPath::Pop () inline
Definition at line 120 of file PropertyVisitor.h.
References No, and Path.
Push()
void FPropertyVisitorPath::Push (const FPropertyVisitorInfo & Info) inline
Definition at line 115 of file PropertyVisitor.h.
References Info, and Path.
Referenced by FPropertyVisitorPath().
Top() [1/2]
FPropertyVisitorInfo & FPropertyVisitorPath::Top () inline
Definition at line 130 of file PropertyVisitor.h.
References Path.
Top() [2/2]
const FPropertyVisitorInfo & FPropertyVisitorPath::Top () const inline
Definition at line 135 of file PropertyVisitor.h.
References Path.
ToSerializedPropertyChain()
FArchiveSerializedPropertyChain FPropertyVisitorPath::ToSerializedPropertyChain () const
Converts path to an archive serialized property chain This method useful when APIs like in the FOverridableManager are taking in a FArchiveSerializedPropertyChain parameter and would like to use them.
It is used in many places in the FProperty::ImportText
Returns
the archive serialized property chain built from the property path
ToString() [1/2]
FString FPropertyVisitorPath::ToString (const TCHAR * Separator = TEXT(".")) const
ToString() [2/2]
void FPropertyVisitorPath::ToString (FStringBuilderBase & Out, const TCHAR * Separator = TEXT(".")) const
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPropertyVisitorPath & A) friend
Definition at line 154 of file PropertyVisitor.h.
References FPropertyVisitorPath(), A, and GetTypeHash.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FPropertyVisitorPath & A, const FPropertyVisitorPath & B) friend
Definition at line 149 of file PropertyVisitor.h.
References FPropertyVisitorPath(), A, and B.
operator==
bool operator== (const FPropertyVisitorPath & A, const FPropertyVisitorPath & B) friend
Definition at line 145 of file PropertyVisitor.h.
References FPropertyVisitorPath(), A, and B.
Field Documentation
Path
TArray<FPropertyVisitorInfo> FPropertyVisitorPath::Path protected
Definition at line 206 of file PropertyVisitor.h.
Referenced by FPropertyVisitorPath(), GetPath(), GetRootIterator(), Num(), Pop(), Push(), Top(), and Top().
The documentation for this struct was generated from the following file:
PropertyVisitor.h