Unreal Engine 5.6 C++ API: TArrayAttribute< AttributeType > Class Template Reference
TArrayAttribute< AttributeType > Class Template Reference
Proxy object which fields access to an unbounded array attribute container.
#include "AttributeArrayContainer.h"
Public Member Functions
TArrayAttribute (ArrayType &InArray, int32 InIndex)
template<typename T = AttributeType, typename TEnableIf< std::is_same_v< T, const T >, int >::Type = 0>
TArrayAttribute (TArrayAttribute< std::remove_cv_t< T > > InValue)
Construct a TArrayAttribute<const T> from a TArrayAttribute<T>.
int32 Add (const AttributeType &Value)
Adds the given value to the end of the array attribute, reserving extra space if necessary.
int32 AddUnique (const AttributeType &Value)
Adds the given value to the end of the array attribute, reserving extra space if necessary.
FORCEINLINE AttributeType * begin () const
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
bool Contains (const AttributeType &Value) const
Determines whether the array attribute contains a particular value.
template<typename Predicate>
bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains element for which the predicate is true.
FORCEINLINE AttributeType * end () const
int32 Find (const AttributeType &Value) const
Finds the given value in the array attribute and returns its index.
template<typename Predicate>
AttributeType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
AttributeType * GetData () const
Helper function for returning a typed pointer to the first array attribute entry.
template<typename Predicate>
int32 IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
void Insert (const AttributeType &Value, int32 StartIndex)
Inserts an element into the given index in the array attribute.
void InsertDefaulted (int32 StartIndex, int32 Count)
Inserts a number of default-constructed elements in the array attribute.
bool IsEmpty () const
Returns true if the array attribute is empty and contains no elements.
bool IsValidIndex (int32 ArrayAttributeIndex) const
Tests if index is valid, i.e.
AttributeType & Last (int32 IndexFromTheEnd=0) const
Returns n-th last element from the array attribute.
int32 Num () const
Returns number of elements in the array attribute.
operator TArrayView< AttributeType > ()
Implicitly coerce an array attribute to a TArrayView.
AttributeType & operator[] (int32 ArrayAttributeIndex) const
Array bracket operator.
int32 Remove (const AttributeType &Value)
template<typename Predicate>
int32 RemoveAll (Predicate Pred)
Removes all elements which match the predicate.
void RemoveAt (int32 StartIndex, int32 Count)
Removes a number of elements from the array attribute.
void Reserve (int32 Num)
Reserves the number of elements in the array attribute.
void SetNum (int32 Num)
Sets the number of elements in the array attribute.
void SetNumUninitialized (int32 Num)
Sets the number of elements in the array attribute without initializing any new elements.
void Sort ()
Sorts the array assuming < operator is defined for the item type.
template<typename Predicate>
void SortByPredicate (Predicate Pred)
Sorts the array using the given predicate.
void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
template<typename Predicate>
void StableSortByPredicate (Predicate Pred)
Sorts the array using the given predicate.
TArrayView< AttributeType > ToArrayView ()
Return a TArrayView representing this array attribute.
Private Types
using ArrayType = TCopyQualifiersFromTo_T<AttributeType, TAttributeArrayContainer<std::remove_cv_t<AttributeType>>>
Private Attributes
ArrayType * Array
int32 Index
Friends
template<typename T>
class TArrayAttribute
Detailed Description
template<typename AttributeType>
class TArrayAttribute< AttributeType >
Proxy object which fields access to an unbounded array attribute container.
Definition at line 392 of file AttributeArrayContainer.h.
Member Typedef Documentation
ArrayType
template<typename AttributeType> using TArrayAttribute< AttributeType >::ArrayType = TCopyQualifiersFromTo_T<AttributeType, TAttributeArrayContainer<std::remove_cv_t<AttributeType>>> private
Definition at line 395 of file AttributeArrayContainer.h.
Constructor & Destructor Documentation
TArrayAttribute() [1/2]
template<typename AttributeType> TArrayAttribute< AttributeType >::TArrayAttribute (ArrayType & InArray, int32 InIndex) inline explicit
Definition at line 398 of file AttributeArrayContainer.h.
TArrayAttribute() [2/2]
template<typename AttributeType> template<typename T = AttributeType, typename TEnableIf< std::is_same_v< T, const T >, int >::Type = 0> TArrayAttribute< AttributeType >::TArrayAttribute (TArrayAttribute< std::remove_cv_t< T > > InValue) inline
Construct a TArrayAttribute<const T> from a TArrayAttribute<T>.
Definition at line 407 of file AttributeArrayContainer.h.
Member Function Documentation
Add()
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::Add (const AttributeType & Value) inline
Adds the given value to the end of the array attribute, reserving extra space if necessary.
Definition at line 513 of file AttributeArrayContainer.h.
AddUnique()
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::AddUnique (const AttributeType & Value) inline
Adds the given value to the end of the array attribute, reserving extra space if necessary.
Definition at line 525 of file AttributeArrayContainer.h.
begin()
template<typename AttributeType> FORCEINLINE AttributeType * TArrayAttribute< AttributeType >::begin () const inline
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 713 of file AttributeArrayContainer.h.
Contains()
template<typename AttributeType> bool TArrayAttribute< AttributeType >::Contains (const AttributeType & Value) const inline
Determines whether the array attribute contains a particular value.
Definition at line 642 of file AttributeArrayContainer.h.
ContainsByPredicate()
template<typename AttributeType> template<typename Predicate> bool TArrayAttribute< AttributeType >::ContainsByPredicate (Predicate Pred) const inline
Checks if this array contains element for which the predicate is true.
Parameters
Predicate to use
Returns
True if found. False otherwise.
Definition at line 656 of file AttributeArrayContainer.h.
end()
template<typename AttributeType> FORCEINLINE AttributeType * TArrayAttribute< AttributeType >::end () const inline
Definition at line 714 of file AttributeArrayContainer.h.
Find()
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::Find (const AttributeType & Value) const inline
Finds the given value in the array attribute and returns its index.
Definition at line 603 of file AttributeArrayContainer.h.
FindByPredicate()
template<typename AttributeType> template<typename Predicate> AttributeType * TArrayAttribute< AttributeType >::FindByPredicate (Predicate Pred) const inline
Finds an element which matches a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
Pointer to the first element for which the predicate returns true, or nullptr if none is found.
Definition at line 618 of file AttributeArrayContainer.h.
GetData()
template<typename AttributeType> AttributeType * TArrayAttribute< AttributeType >::GetData () const inline
Helper function for returning a typed pointer to the first array attribute entry.
Definition at line 415 of file AttributeArrayContainer.h.
Referenced by TArrayAttribute< T >::begin(), and TArrayAttribute< T >::end().
IndexOfByPredicate()
template<typename AttributeType> template<typename Predicate> int32 TArrayAttribute< AttributeType >::IndexOfByPredicate (Predicate Pred) const inline
Finds an item by predicate.
Parameters
Pred The predicate to match.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 633 of file AttributeArrayContainer.h.
Insert()
template<typename AttributeType> void TArrayAttribute< AttributeType >::Insert (const AttributeType & Value, int32 StartIndex) inline
Inserts an element into the given index in the array attribute.
Definition at line 551 of file AttributeArrayContainer.h.
InsertDefaulted()
template<typename AttributeType> void TArrayAttribute< AttributeType >::InsertDefaulted (int32 StartIndex, int32 Count) inline
Inserts a number of default-constructed elements in the array attribute.
Definition at line 542 of file AttributeArrayContainer.h.
IsEmpty()
template<typename AttributeType> bool TArrayAttribute< AttributeType >::IsEmpty () const inline
Returns true if the array attribute is empty and contains no elements.
Returns
True if the array attribute is empty.
Definition at line 437 of file AttributeArrayContainer.h.
IsValidIndex()
template<typename AttributeType> bool TArrayAttribute< AttributeType >::IsValidIndex (int32 ArrayAttributeIndex) const inline
Tests if index is valid, i.e.
than or equal to zero, and less than the number of elements in the array attribute.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 427 of file AttributeArrayContainer.h.
Last()
template<typename AttributeType> AttributeType & TArrayAttribute< AttributeType >::Last (int32 IndexFromTheEnd = 0) const inline
Returns n-th last element from the array attribute.
Parameters
IndexFromTheEnd (Optional) Index from the end of array. Default is 0.
Returns
Reference to n-th last element from the array.
Definition at line 470 of file AttributeArrayContainer.h.
Num()
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::Num () const inline
Returns number of elements in the array attribute.
Returns
Number of elements in array attribute.
Definition at line 447 of file AttributeArrayContainer.h.
Referenced by TArrayAttribute< T >::end().
operator TArrayView< AttributeType >()
template<typename AttributeType> TArrayAttribute< AttributeType >::operator TArrayView< AttributeType > () inline
Implicitly coerce an array attribute to a TArrayView.
Definition at line 706 of file AttributeArrayContainer.h.
References Array, and Index.
operator[]()
template<typename AttributeType> AttributeType & TArrayAttribute< AttributeType >::operator[] (int32 ArrayAttributeIndex) const inline
Array bracket operator.
Returns reference to array attribute element at given index.
Returns
Reference to indexed element.
Definition at line 457 of file AttributeArrayContainer.h.
Remove()
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::Remove (const AttributeType & Value) inline
Definition at line 594 of file AttributeArrayContainer.h.
RemoveAll()
template<typename AttributeType> template<typename Predicate> int32 TArrayAttribute< AttributeType >::RemoveAll (Predicate Pred) inline
Removes all elements which match the predicate.
Definition at line 571 of file AttributeArrayContainer.h.
Referenced by TArrayAttribute< T >::Remove().
RemoveAt()
template<typename AttributeType> void TArrayAttribute< AttributeType >::RemoveAt (int32 StartIndex, int32 Count) inline
Removes a number of elements from the array attribute.
Definition at line 561 of file AttributeArrayContainer.h.
Reserve()
template<typename AttributeType> void TArrayAttribute< AttributeType >::Reserve (int32 Num) inline
Reserves the number of elements in the array attribute.
Definition at line 502 of file AttributeArrayContainer.h.
SetNum()
template<typename AttributeType> void TArrayAttribute< AttributeType >::SetNum (int32 Num) inline
Sets the number of elements in the array attribute.
Definition at line 478 of file AttributeArrayContainer.h.
SetNumUninitialized()
template<typename AttributeType> void TArrayAttribute< AttributeType >::SetNumUninitialized (int32 Num) inline
Sets the number of elements in the array attribute without initializing any new elements.
It is the responsibility of the caller to do so after this function returns.
Definition at line 491 of file AttributeArrayContainer.h.
Sort()
template<typename AttributeType> void TArrayAttribute< AttributeType >::Sort () inline
Sorts the array assuming < operator is defined for the item type.
Definition at line 665 of file AttributeArrayContainer.h.
Referenced by TArrayAttribute< T >::SortByPredicate().
SortByPredicate()
template<typename AttributeType> template<typename Predicate> void TArrayAttribute< AttributeType >::SortByPredicate (Predicate Pred) inline
Sorts the array using the given predicate.
Definition at line 674 of file AttributeArrayContainer.h.
StableSort()
template<typename AttributeType> void TArrayAttribute< AttributeType >::StableSort () inline
Stable sorts the array assuming < operator is defined for the item type.
Definition at line 683 of file AttributeArrayContainer.h.
Referenced by TArrayAttribute< T >::StableSortByPredicate().
StableSortByPredicate()
template<typename AttributeType> template<typename Predicate> void TArrayAttribute< AttributeType >::StableSortByPredicate (Predicate Pred) inline
Sorts the array using the given predicate.
Definition at line 693 of file AttributeArrayContainer.h.
ToArrayView()
template<typename AttributeType> TArrayView< AttributeType > TArrayAttribute< AttributeType >::ToArrayView () inline
Return a TArrayView representing this array attribute.
Definition at line 701 of file AttributeArrayContainer.h.
Friends And Related Symbol Documentation
TArrayAttribute
template<typename AttributeType> template<typename T> friend class TArrayAttribute friend
Definition at line 394 of file AttributeArrayContainer.h.
Field Documentation
Array
template<typename AttributeType> ArrayType* TArrayAttribute< AttributeType >::Array private
Definition at line 717 of file AttributeArrayContainer.h.
Referenced by operator TArrayView< AttributeType >().
Index
template<typename AttributeType> int32 TArrayAttribute< AttributeType >::Index private
Definition at line 718 of file AttributeArrayContainer.h.
Referenced by operator TArrayView< AttributeType >().
The documentation for this class was generated from the following file:
AttributeArrayContainer.h