Unreal Engine 5.6 C++ API: FNodeTitleTextTable Struct Reference
FNodeTitleTextTable Struct Reference
#include "EdGraphNodeUtils.h"
Public Member Functions
FORCEINLINE FText & GetCachedTitle (ENodeTitleType::Type TitleType) const
FORCEINLINE bool IsTitleCached (ENodeTitleType::Type InTitleType, const UEdGraphNode *InOwningNode) const
Checks if the title of the passed type is cached.
FORCEINLINE void MarkDirty () const
FORCEINLINE FText & operator[] (ENodeTitleType::Type TitleIndex) const
FORCEINLINE void SetCachedTitle (ENodeTitleType::Type InTitleType, FText const &InText, const UEdGraphNode *InOwningNode) const
Caches the specific title type.
Private Attributes
FNodeTextCache CachedNodeTitles [ENodeTitleType::MAX_TitleTypes]
Detailed Description
Definition at line 135 of file EdGraphNodeUtils.h.
Member Function Documentation
GetCachedTitle()
FORCEINLINE FText & FNodeTitleTextTable::GetCachedTitle (ENodeTitleType::Type TitleType) const inline
Definition at line 162 of file EdGraphNodeUtils.h.
References CachedNodeTitles, and FORCEINLINE.
Referenced by operator[]().
IsTitleCached()
FORCEINLINE bool FNodeTitleTextTable::IsTitleCached (ENodeTitleType::Type InTitleType, const UEdGraphNode * InOwningNode) const inline
Checks if the title of the passed type is cached.
Parameters
InTitleType Type of title to be examined
InOwningNode Node that owns this title
Definition at line 144 of file EdGraphNodeUtils.h.
References CachedNodeTitles, and FORCEINLINE.
MarkDirty()
FORCEINLINE void FNodeTitleTextTable::MarkDirty () const inline
Definition at line 168 of file EdGraphNodeUtils.h.
References CachedNodeTitles, and FORCEINLINE.
Referenced by FNodeTextTable::MarkDirty().
operator[]()
FORCEINLINE FText & FNodeTitleTextTable::operator[] (ENodeTitleType::Type TitleIndex) const inline
Definition at line 177 of file EdGraphNodeUtils.h.
References FORCEINLINE, and GetCachedTitle().
SetCachedTitle()
FORCEINLINE void FNodeTitleTextTable::SetCachedTitle (ENodeTitleType::Type InTitleType, FText const & InText, const UEdGraphNode * InOwningNode) const inline
Caches the specific title type.
Parameters
InTitleType Type of title to be examined
InText Text to cache
InOwningNode Node that owns this title
Definition at line 156 of file EdGraphNodeUtils.h.
References CachedNodeTitles, and FORCEINLINE.
Field Documentation
CachedNodeTitles
FNodeTextCache FNodeTitleTextTable::CachedNodeTitles[ENodeTitleType::MAX_TitleTypes] private
Definition at line 184 of file EdGraphNodeUtils.h.
Referenced by GetCachedTitle(), IsTitleCached(), MarkDirty(), and SetCachedTitle().
The documentation for this struct was generated from the following file:
EdGraphNodeUtils.h