Unreal Engine 5.6 C++ API: FSimulatedNavigationMetaData Class Reference
FSimulatedNavigationMetaData Class Reference
Navigation meta data to used when using the Navigation Event Simulator The OnNavigation function is not call by default on the widget, unless specified with "IsOnNavigationConst".
#include "NavigationMetaData.h"
Data Structures
struct SNavData
Public Types
enum EOnNavigationIsConst { OnNavigationIsConst }
Public Member Functions
FSimulatedNavigationMetaData (const FNavigationMetaData &InSimulatedNavigation)
FSimulatedNavigationMetaData (EOnNavigationIsConst)
FSimulatedNavigationMetaData (EUINavigationRule InNavigationRule)
EUINavigationRule GetBoundaryRule (EUINavigation InNavigation) const
Get the boundary rule for the provided navigation type.
const TWeakPtr< SWidget > & GetFocusRecipient (EUINavigation InNavigation) const
Get the focus recipient for the provided navigation type.
bool IsOnNavigationConst () const
Is the OnNavigation function const and should be called when simulating to determine the navigation rule.
SLATE_METADATA_TYPE (FSimulatedNavigationMetaData, ISlateMetaData) FSimulatedNavigationMetaData()=default
Public Member Functions inherited from ISlateMetaData
virtual ~ISlateMetaData ()
Virtual destructor.
template<class TType>
bool IsOfType () const
Check if this metadata operation can cast safely to the specified template type.
Private Attributes
bool bIsOnNavigationConst = false
SNavData Rules [(uint8) EUINavigation::Num]
Additional Inherited Members
Protected Member Functions inherited from ISlateMetaData
virtual bool IsOfTypeImpl (const FName &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
Detailed Description
Navigation meta data to used when using the Navigation Event Simulator The OnNavigation function is not call by default on the widget, unless specified with "IsOnNavigationConst".
Definition at line 143 of file NavigationMetaData.h.
Member Enumeration Documentation
EOnNavigationIsConst
enum FSimulatedNavigationMetaData::EOnNavigationIsConst
Enumerator
OnNavigationIsConst
Definition at line 167 of file NavigationMetaData.h.
Constructor & Destructor Documentation
FSimulatedNavigationMetaData() [1/3]
FSimulatedNavigationMetaData::FSimulatedNavigationMetaData (const FNavigationMetaData & InSimulatedNavigation) inline
Definition at line 150 of file NavigationMetaData.h.
References FNavigationMetaData::GetBoundaryRule(), FNavigationMetaData::GetFocusRecipient(), Rules, and UE_ARRAY_COUNT.
Referenced by SLATE_METADATA_TYPE().
FSimulatedNavigationMetaData() [2/3]
FSimulatedNavigationMetaData::FSimulatedNavigationMetaData (EUINavigationRule InNavigationRule) inline
Definition at line 159 of file NavigationMetaData.h.
References Rules.
FSimulatedNavigationMetaData() [3/3]
FSimulatedNavigationMetaData::FSimulatedNavigationMetaData (EOnNavigationIsConst) inline
Definition at line 168 of file NavigationMetaData.h.
References bIsOnNavigationConst, and Rules.
Member Function Documentation
GetBoundaryRule()
EUINavigationRule FSimulatedNavigationMetaData::GetBoundaryRule (EUINavigation InNavigation) const inline
Get the boundary rule for the provided navigation type.
Definition at line 179 of file NavigationMetaData.h.
References Rules.
GetFocusRecipient()
const TWeakPtr< SWidget > & FSimulatedNavigationMetaData::GetFocusRecipient (EUINavigation InNavigation) const inline
Get the focus recipient for the provided navigation type.
Definition at line 185 of file NavigationMetaData.h.
References Rules.
IsOnNavigationConst()
bool FSimulatedNavigationMetaData::IsOnNavigationConst () const inline
Is the OnNavigation function const and should be called when simulating to determine the navigation rule.
Definition at line 191 of file NavigationMetaData.h.
References bIsOnNavigationConst.
SLATE_METADATA_TYPE()
FSimulatedNavigationMetaData::SLATE_METADATA_TYPE (FSimulatedNavigationMetaData , ISlateMetaData) default
References FSimulatedNavigationMetaData().
Field Documentation
bIsOnNavigationConst
bool FSimulatedNavigationMetaData::bIsOnNavigationConst = false private
Definition at line 200 of file NavigationMetaData.h.
Referenced by FSimulatedNavigationMetaData(), and IsOnNavigationConst().
Rules
SNavData FSimulatedNavigationMetaData::Rules[(uint8) EUINavigation::Num] private
Definition at line 199 of file NavigationMetaData.h.
Referenced by FSimulatedNavigationMetaData(), FSimulatedNavigationMetaData(), FSimulatedNavigationMetaData(), GetBoundaryRule(), and GetFocusRecipient().
The documentation for this class was generated from the following file:
NavigationMetaData.h