Unreal Engine 5.6 C++ API: FAnimationRuntime Class Reference
FAnimationRuntime Class Reference
In AnimationRunTime Library, we extract animation data based on Skeleton hierarchy, not ref pose hierarchy.
#include "AnimationRuntime.h"
Public Types
enum class EBlendPosesPerBoneFilterFlags : uint32 { None = 0 , MeshSpaceRotation = (1 << 0) , MeshSpaceScale = (1 << 1) , RootSpaceRotation = (1 << 2) }
Blending flags for BlendPosesPerBoneFilter.
Public Member Functions
UE_DEPRECATED (4.26, "Please use the BlendPosesPerBoneFilterwith different signature.") static 1 void BlendPosesPerBoneFilter(FCompactPose &BasePose
Blend Poses per bone weights : The BasePoses + BlendPoses(SourceIndex) * Blend Weights(BoneIndex) Please note BlendWeights are array, so you can define per bone base This supports multi per bone blending, but only one pose as blend at a time per track PerBoneBlendWeights.Num() == Atoms.Num()
UE_DEPRECATED (4.26, "Use AccumulateAdditivePose with other signature") static 1 void AccumulateAdditivePose(FCompactPose &BasePose
Accumulate Additive Pose based on AdditiveType.
UE_DEPRECATED (4.26, "Use AccumulateAdditivePose with other signature") static 1 void AccumulateLocalSpaceAdditivePose(FCompactPose &BasePose
Accumulates weighted AdditivePose to BasePose.
UE_DEPRECATED (4.26, "Use AccumulateAdditivePose with other signature") static 1 void AccumulateMeshSpaceRotationAdditiveToLocalPose(FCompactPose &BasePose
Accumulate a MeshSpaceRotation Additive pose to a local pose.
UE_DEPRECATED (4.26, "Use BlendPosesTogether with other signature") static 1 void BlendPosesTogether(TArrayView< const FCompactPose > SourcePoses
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendPosesTogether with other signature") static 1 void BlendPosesTogether(TArrayView< const FCompactPose > SourcePoses
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendPosesTogetherIndirect with other signature") static 1 void BlendPosesTogetherIndirect(TArrayView< const FCompactPose *const > SourcePoses
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendPosesTogetherPerBone with other signature") static 1 void BlendPosesTogetherPerBone(TArrayView< const FCompactPose > SourcePoses
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendPosesTogetherPerBone with other signature") static 1 void BlendPosesTogetherPerBone(TArrayView< const FCompactPose > SourcePoses
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendPosesTogetherPerBone with other signature") static 1 void BlendPosesTogetherPerBoneInMeshSpace(TArrayView< FCompactPose > SourcePoses
Blends together a set of local space (not mesh space) poses, each with a given weight.
UE_DEPRECATED (4.26, "Use BlendTwoPosesTogether with other signature") static 1 void BlendTwoPosesTogether(const FCompactPose &SourcePose1
Blends together two poses.
UE_DEPRECATED (4.26, "Use BlendTwoPosesTogether with other signature") static 1 void BlendTwoPosesTogetherPerBone(const FCompactPose &SourcePose1
Blends together a set of poses, each with a given weight.
UE_DEPRECATED (4.26.0, "Please use BlendTransform() for weighted blending") static 1 void BlendTransformsByWeight(FTransform &OutTransform
Blend Array of Transforms by weight.
Static Public Member Functions
static void AccumulateAdditivePose (FAnimationPoseData &BaseAnimationPoseData, const FAnimationPoseData &AdditiveAnimationPoseData, float Weight, enum EAdditiveAnimationType AdditiveType)
static void AccumulateLocalSpaceAdditivePose (FAnimationPoseData &BaseAnimationPoseData, const FAnimationPoseData &AdditiveAnimationPoseData, float Weight)
static void AccumulateMeshSpaceRotationAdditiveToLocalPose (FAnimationPoseData &BaseAnimationPoseData, const FAnimationPoseData &MeshSpaceRotationAdditiveAnimationPoseData, float Weight)
static void AccumulateRootSpaceRotationAdditiveToLocalPose (FAnimationPoseData &BaseAnimationPoseData, const FAnimationPoseData &MeshSpaceRotationAdditiveAnimationPoseData, float Weight)
static ETypeAdvanceAnim AdvanceTime (const bool bAllowLooping, const float MoveDelta, float &InOutTime, const float EndTime)
Advance CurrentTime to CurrentTime + MoveDelta.
static void AppendActiveMorphTargets (const USkeletalMesh *InSkeletalMesh, const TMap< FName, float > &InMorphCurveAnims, FMorphTargetWeightMap &InOutActiveMorphTargets, TArray< float > &InOutMorphTargetWeights)
Combine CurveKeys (that reference morph targets by name) and ActiveAnims (that reference morphs by reference) into the ActiveMorphTargets array.
static void ApplyWeightToTransform (const FBoneContainer &RequiredBones, FTransformArrayA2 &Atoms, float Weight)
Apply Weight to the Transform Atoms = Weight * Atoms at the end.
static void BlendPosesPerBoneFilter (FCompactPose &BasePose, const TArray< FCompactPose > &BlendPoses, FBlendedCurve &BaseCurve, const TArray< FBlendedCurve > &BlendCurves, UE::Anim::FStackAttributeContainer &CustomAttributes, const TArray< UE::Anim::FStackAttributeContainer > &BlendAttributes, FAnimationPoseData &OutAnimationPoseData, TArray< FPerBoneBlendWeight > &BoneBlendWeights, EBlendPosesPerBoneFilterFlags blendFlags, enum ECurveBlendOption::Type CurveBlendOption)
static void BlendPosesTogether (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, TArrayView< const float > SourceWeights, FAnimationPoseData &OutAnimationPoseData)
static void BlendPosesTogether (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, TArrayView< const float > SourceWeights, TArrayView< const int32 > SourceWeightsIndices, FAnimationPoseData &OutPoseData)
static void BlendPosesTogetherIndirect (TArrayView< const FCompactPose *const > SourcePoses, TArrayView< const FBlendedCurve *const > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer *const > SourceAttributes, TArrayView< const float > SourceWeights, FAnimationPoseData &OutPoseData)
static void BlendPosesTogetherPerBone (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider *InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, FAnimationPoseData &OutAnimationPoseData)
static void BlendPosesTogetherPerBone (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider *InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, FAnimationPoseData &OutAnimationPoseData)
static void BlendPosesTogetherPerBoneInMeshSpace (TArrayView< FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const UBlendSpace *BlendSpace, TArrayView< const FBlendSampleData > BlendSampleDataCache, FAnimationPoseData &OutAnimationPoseData)
Blends together a set of local space (not mesh space) poses, each with a given weight.
static void BlendPosesTogetherPerBoneRemapped (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider *InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, const FSkeletonRemapping &SkeletonRemapping, FAnimationPoseData &OutAnimationPoseData)
static void BlendTwoPosesTogether (const FAnimationPoseData &SourcePoseOneData, const FAnimationPoseData &SourcePoseTwoData, const float WeightOfPoseOne, FAnimationPoseData &OutAnimationPoseData)
static void BlendTwoPosesTogetherPerBone (const FAnimationPoseData &SourcePoseOneData, const FAnimationPoseData &SourcePoseTwoData, const TArray< float > &WeightsOfSource2, FAnimationPoseData &OutAnimationPoseData)
static void BlendTwoPosesTogetherPerBone (const FCompactPose &SourcePoseOneData, const FCompactPose &SourcePoseTwoData, const TArray< float > &WeightsOfSource2, FCompactPose &OutAnimationPoseData)
static void CombineWithAdditiveAnimations (int32 NumAdditivePoses, const FTransformArrayA2 **SourceAdditivePoses, const float *SourceAdditiveWeights, const FBoneContainer &RequiredBones, FTransformArrayA2 &Atoms)
static void ConvertBoneSpaceTransformToCS (const FTransform &ComponentTransform, FCSPose< FCompactPose > &MeshBases, FTransform &InOutBoneSpaceTM, FCompactPoseBoneIndex BoneIndex, EBoneControlSpace Space)
Convert a FTransform in a specified bone space to ComponentSpace.
static void ConvertCSTransformToBoneSpace (const FTransform &ComponentTransform, FCSPose< FCompactPose > &MeshBases, FTransform &InOutCSBoneTM, FCompactPoseBoneIndex BoneIndex, EBoneControlSpace Space)
Convert a ComponentSpace FTransform to specified bone space.
static void ConvertMeshRotationPoseToLocalSpace (FCompactPose &Pose)
Convert a MeshSpaceRotation pose to Local Space.
static void ConvertPoseToAdditive (FCompactPose &TargetPose, const FCompactPose &BasePose)
Convert TargetPose into an AdditivePose, by doing TargetPose = TargetPose - BasePose.
static void ConvertPoseToMeshRotation (FCompactPose &LocalPose)
Convert LocalPose into MeshSpaceRotations.
static void ConvertPoseToMeshSpace (const TArray< FTransform > &LocalTransforms, TArray< FTransform > &MeshSpaceTransforms, const FBoneContainer &RequiredBones)
Convert LocalTransforms into MeshSpaceTransforms over RequiredBones.
static void ConvertTransformToAdditive (FTransform &TargetTrasnform, const FTransform &BaseTransform)
convert transform to additive
static void CreateMaskWeights (TArray< FPerBoneBlendWeight > &BoneBlendWeights, const TArray< class UBlendProfile * > &BlendMasks, const USkeleton *Skeleton)
Create Mask Weight for skeleton joints, not per mesh or per required bones Individual alphas are read from a BlendProfile using a BlendMask mode.
static void CreateMaskWeights (TArray< FPerBoneBlendWeight > &BoneBlendWeights, const TArray< FInputBlendPose > &BlendFilters, const USkeleton *Skeleton)
Create Mask Weight for skeleton joints, not per mesh or per required bones You'll have to filter properly with correct mesh joint or required bones The depth should not change based on LOD or mesh or skeleton They still should contain same depth.
static void EnsureParentsPresent (TArray< FBoneIndexType > &BoneIndices, const FReferenceSkeleton &RefSkeleton)
Utility for taking an array of bone indices and ensuring that all parents are present (ie.
static void ExcludeBonesWithNoParents (const TArray< int32 > &BoneIndices, const FReferenceSkeleton &RefSkeleton, TArray< int32 > &FilteredRequiredBones)
static void FillUpComponentSpaceTransforms (const FReferenceSkeleton &RefSkeleton, const TArrayView< const FTransform > &BoneSpaceTransforms, TArray< FTransform > &ComponentSpaceTransforms)
static void FillUpComponentSpaceTransformsRefPose (const USkeleton *Skeleton, TArray< FTransform > &ComponentSpaceTransforms)
static void FillWithRefPose (TArray< FTransform > &OutAtoms, const FBoneContainer &RequiredBones)
Fill ref pose.
static EBoneTranslationRetargetingMode::Type GetBoneTranslationRetargetingMode (const bool bUseSourceRetargetModes, const int32 SourceSkeletonBoneIndex, const int32 TargetSkeletonBoneIndex, const USkeleton *SourceSkeleton, const USkeleton *TargetSkeleton, const bool bDisableRetargeting)
Get the translational retargeting mode for a given bone on the target skeleton when sampling a given source animation.
static FTransform GetComponentSpaceRefPose (const FCompactPoseBoneIndex &CompactPoseBoneIndex, const FBoneContainer &BoneContainer)
Get Reference Component Space Transform.
static FTransform GetComponentSpaceTransform (const FReferenceSkeleton &RefSkeleton, const TArrayView< const FTransform > &BoneSpaceTransforms, int32 BoneIndex)
static FTransform GetComponentSpaceTransformRefPose (const FReferenceSkeleton &RefSkeleton, int32 BoneIndex)
static const FTransform & GetComponentSpaceTransformWithCache (const FReferenceSkeleton &InRefSkeleton, const TArray< FTransform > &InBoneSpaceTransforms, int32 BoneIndex, TArray< FTransform > &CachedTransforms, TArray< bool > &CachedTransformReady)
Calculate the component-space bone transform for the specified bone.
static void GetKeyIndicesFromTime (int32 &OutKeyIndex1, int32 &OutKeyIndex2, float &OutAlpha, const double Time, const FFrameRate &FrameRate, const int32 NumberOfKeys)
Get KeyIndices using FFrameRate::AsFrameTime to calculate the keys and alpha value.
static void GetKeyIndicesFromTime (int32 &OutKeyIndex1, int32 &OutKeyIndex2, float &OutAlpha, const double Time, const int32 NumKeys, const double SequenceLength, double FramesPerSecond=-1.0)
Get Key Indices (start/end with alpha from start) with input parameter Time, NumKeys from % from StartKeyIndex, meaning (CurrentKeyIndex(float)-StartKeyIndex)/(EndKeyIndex-StartKeyIndex) by this Start-End, it will be between 0-(NumKeys-1), not number of Pos/Rot key tracks The FramesPerSecond parameter must be the sample rate of the animation data, for example 30.
static FTransform GetSpaceTransform (FA2CSPose &Pose, int32 Index)
static FTransform GetSpaceTransform (FA2Pose &Pose, int32 Index)
static int32 GetStringDistance (const FString &First, const FString &Second)
Calculate distance how close two strings are.
static FORCEINLINE bool HasWeight (float Weight)
static void InitializeTransform (const FBoneContainer &RequiredBones, FTransformArrayA2 &Atoms)
static FORCEINLINE bool IsFullWeight (float Weight)
static void LerpBoneTransforms (TArray< FTransform > &A, const TArray< FTransform > &B, float Alpha, const TArray< FBoneIndexType > &RequiredBonesArray)
Lerp for BoneTransforms.
static void LerpPoses (FCompactPose &PoseA, const FCompactPose &PoseB, FBlendedCurve &CurveA, const FBlendedCurve &CurveB, float Alpha)
Lerp for FCompactPose.
static void LerpPosesPerBone (FCompactPose &PoseA, const FCompactPose &PoseB, FBlendedCurve &CurveA, const FBlendedCurve &CurveB, float Alpha, const TArray< float > &PerBoneWeights)
Lerp for FCompactPose.
static void LerpPosesWithBoneIndexList (FCompactPose &PoseA, const FCompactPose &PoseB, FBlendedCurve &CurveA, const FBlendedCurve &CurveB, float Alpha, const TArray< FCompactPoseBoneIndex > &BoneIndices)
Lerp for FCompactPose.
static void MakeSkeletonRefPoseFromMesh (const USkeletalMesh *InMesh, const USkeleton *InSkeleton, TArray< FTransform > &OutBoneBuffer)
static void MirrorCurves (FBlendedCurve &Curves, const UMirrorDataTable &MirrorDataTable)
Mirror (swap) curves with the specified MirrorDataTable.
static void MirrorPose (FCompactPose &Pose, const UMirrorDataTable &MirrorDataTable)
Mirror a pose with the specified MirrorDataTable.
static void MirrorPose (FCompactPose &Pose, EAxis::Type MirrorAxis, const TArray< FCompactPoseBoneIndex > &CompactPoseMirrorBones, const TCustomBoneIndexArray< FQuat, FCompactPoseBoneIndex > &ComponentSpaceRefRotations)
Mirror Pose using cached mirror bones and components space arrays.
static FQuat MirrorQuat (const FQuat &Q, EAxis::Type MirrorAxis)
Mirror a quaternion across the specified mirror axis.
static FVector MirrorVector (const FVector &V, EAxis::Type MirrorAxis)
Mirror a vector across the specified mirror axis.
static void NormalizeRotations (const FBoneContainer &RequiredBones, FTransformArrayA2 &Atoms)
static void NormalizeRotations (FTransformArrayA2 &Atoms)
static void RetargetBoneTransform (const USkeleton *MySkeleton, const FName &SourceName, const TArray< FTransform > &RetargetTransforms, FTransform &BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex &BoneIndex, const FBoneContainer &RequiredBones, const bool bIsBakedAdditive)
static void RetargetBoneTransform (const USkeleton *SourceSkeleton, const FName &RetargetSource, FTransform &BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex &BoneIndex, const FBoneContainer &RequiredBones, const bool bIsBakedAdditive)
Retarget a single bone transform, to apply right after extraction.
static void SetSpaceTransform (FA2CSPose &Pose, int32 Index, FTransform &NewTransform)
static void SetSpaceTransform (FA2Pose &Pose, int32 Index, FTransform &NewTransform)
static void TickBlendWeight (float DeltaTime, float DesiredWeight, float &Weight, float &BlendTime)
static void UpdateDesiredBoneWeight (const TArray< FPerBoneBlendWeight > &SrcBoneBlendWeights, TArray< FPerBoneBlendWeight > &TargetBoneBlendWeights, const TArray< float > &BlendWeights)
Data Fields
const FCompactPose FBlendedCurve const FBlendedCurve & AdditiveCurve
const FCompactPose & AdditivePose
const FCompactPose FBlendedCurve const FBlendedCurve float enum EAdditiveAnimationType AdditiveType
const TArray< FCompactPose > FBlendedCurve & BaseCurve
const FCompactPose FBlendedCurve & BaseCurve
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > & BlendCurves
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > FCompactPose FBlendedCurve TArray< FPerBoneBlendWeight > EBlendPosesPerBoneFilterFlags blendFlags
const TArray< FCompactPose > & BlendPoses
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > BlendSampleDataCache
TArrayView< const FBlendedCurve > const UBlendSpace TArrayView< const FBlendSampleData > BlendSampleDataCache
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > TArrayView< const int32 > BlendSampleDataCacheIndices
TArrayView< const FBlendedCurve > const UBlendSpace * BlendSpace
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > FCompactPose FBlendedCurve TArray< FPerBoneBlendWeight > & BoneBlendWeights
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > FCompactPose FBlendedCurve TArray< FPerBoneBlendWeight > EBlendPosesPerBoneFilterFlags enum ECurveBlendOption::Type CurveBlendOption
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider * InterpolationIndexProvider
const FCompactPose & MeshSpaceRotationAdditive
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > FCompactPose FBlendedCurve & OutCurve
const TArray< FCompactPose > FBlendedCurve const TArray< FBlendedCurve > FCompactPose & OutPose
TArrayView< const FBlendedCurve > const UBlendSpace TArrayView< const FBlendSampleData > FCompactPose FBlendedCurve & OutResultCurve
TArrayView< const FBlendedCurve > const UBlendSpace TArrayView< const FBlendSampleData > FCompactPose & OutResultPose
TArrayView< const FBlendedCurve > TArrayView< const float > FCompactPose FBlendedCurve & ResultCurve
TArrayView< const FBlendedCurve > TArrayView< const float > TArrayView< const int32 > FCompactPose FBlendedCurve & ResultCurve
TArrayView< const FBlendedCurve *const > TArrayView< const float > FCompactPose FBlendedCurve & ResultCurve
const FCompactPose const FBlendedCurve const FBlendedCurve const float FCompactPose FBlendedCurve & ResultCurve
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray< float > FCompactPose FBlendedCurve & ResultCurve
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > FCompactPose FBlendedCurve & ResultCurve
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > TArrayView< const int32 > FCompactPose FBlendedCurve & ResultCurve
TArrayView< const FBlendedCurve > TArrayView< const float > FCompactPose & ResultPose
TArrayView< const FBlendedCurve > TArrayView< const float > TArrayView< const int32 > FCompactPose & ResultPose
TArrayView< const FBlendedCurve *const > TArrayView< const float > FCompactPose & ResultPose
const FCompactPose const FBlendedCurve const FBlendedCurve const float FCompactPose & ResultPose
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray< float > FCompactPose & ResultPose
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > FCompactPose & ResultPose
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > TArrayView< const int32 > FCompactPose & ResultPose
const FCompactPose const FBlendedCurve & SourceCurve1
const FCompactPose const FBlendedCurve const FBlendedCurve & SourceCurve2
TArrayView< const FBlendedCurve > SourceCurves
TArrayView< const FBlendedCurve *const > SourceCurves
const FCompactPose & SourcePose2
TArrayView< const FBlendedCurve > TArrayView< const float > SourceWeights
TArrayView< const FBlendedCurve *const > TArrayView< const float > SourceWeights
TArrayView< const FBlendedCurve > TArrayView< const float > TArrayView< const int32 > SourceWeightsIndices
const TArray< FTransform > & Transforms
const FCompactPose FBlendedCurve const FBlendedCurve float Weight
const FCompactPose const FBlendedCurve const FBlendedCurve const float WeightOfPose1
const TArray< FTransform > const TArray< float > & Weights
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray< float > & WeightsOfSource2
Static Private Member Functions
static void AccumulateLocalSpaceAdditivePoseInternal (FCompactPose &BasePose, const FCompactPose &AdditivePose, float Weight)
Accumulates weighted AdditivePose to BasePose.
static void AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal (FCompactPose &BasePose, const FCompactPose &MeshSpaceRotationAdditive, float Weight)
Accumulate a MeshSpaceRotation Additive pose to a local pose.
static void AccumulateRootSpaceAdditivePoseInternal (FCompactPose &BasePose, const FCompactPose &RootSpaceAdditivePose, float Weight)
Accumulate a RootSpaceRotation Additive pose to a local pose.
Detailed Description
In AnimationRunTime Library, we extract animation data based on Skeleton hierarchy, not ref pose hierarchy.
Ref pose will need to be re-mapped later
Definition at line 104 of file AnimationRuntime.h.
Member Enumeration Documentation
EBlendPosesPerBoneFilterFlags
enum class FAnimationRuntime::EBlendPosesPerBoneFilterFlags : uint32 strong
Blending flags for BlendPosesPerBoneFilter.
Enumerator
None
MeshSpaceRotation
MeshSpaceScale
Blend bone rotations in mesh space instead of local space.
RootSpaceRotation
Blend bone scales in mesh space instead of local space.
Definition at line 349 of file AnimationRuntime.h.
Member Function Documentation
AccumulateAdditivePose()
void FAnimationRuntime::AccumulateAdditivePose (FAnimationPoseData & BaseAnimationPoseData, const FAnimationPoseData & AdditiveAnimationPoseData, float Weight, enum EAdditiveAnimationType AdditiveType) static
References AccumulateAdditivePose(), AdditiveType, and Weight.
Referenced by AccumulateAdditivePose().
AccumulateLocalSpaceAdditivePose()
void FAnimationRuntime::AccumulateLocalSpaceAdditivePose (FAnimationPoseData & BaseAnimationPoseData, const FAnimationPoseData & AdditiveAnimationPoseData, float Weight) static
References AccumulateLocalSpaceAdditivePose(), and Weight.
Referenced by AccumulateLocalSpaceAdditivePose(), and UE_DEPRECATED().
AccumulateLocalSpaceAdditivePoseInternal()
void FAnimationRuntime::AccumulateLocalSpaceAdditivePoseInternal (FCompactPose & BasePose, const FCompactPose & AdditivePose, float Weight) static private
Accumulates weighted AdditivePose to BasePose.
Rotations are NOT normalized.
References AccumulateLocalSpaceAdditivePoseInternal(), AdditivePose, and Weight.
Referenced by AccumulateLocalSpaceAdditivePoseInternal().
AccumulateMeshSpaceRotationAdditiveToLocalPose()
void FAnimationRuntime::AccumulateMeshSpaceRotationAdditiveToLocalPose (FAnimationPoseData & BaseAnimationPoseData, const FAnimationPoseData & MeshSpaceRotationAdditiveAnimationPoseData, float Weight) static
References AccumulateMeshSpaceRotationAdditiveToLocalPose(), and Weight.
Referenced by AccumulateMeshSpaceRotationAdditiveToLocalPose().
AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal()
void FAnimationRuntime::AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal (FCompactPose & BasePose, const FCompactPose & MeshSpaceRotationAdditive, float Weight) static private
Accumulate a MeshSpaceRotation Additive pose to a local pose.
Rotations are NOT normalized
References AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal(), MeshSpaceRotationAdditive, and Weight.
Referenced by AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal().
AccumulateRootSpaceAdditivePoseInternal()
void FAnimationRuntime::AccumulateRootSpaceAdditivePoseInternal (FCompactPose & BasePose, const FCompactPose & RootSpaceAdditivePose, float Weight) static private
Accumulate a RootSpaceRotation Additive pose to a local pose.
Rotations are NOT normalized
References AccumulateRootSpaceAdditivePoseInternal(), and Weight.
Referenced by AccumulateRootSpaceAdditivePoseInternal().
AccumulateRootSpaceRotationAdditiveToLocalPose()
void FAnimationRuntime::AccumulateRootSpaceRotationAdditiveToLocalPose (FAnimationPoseData & BaseAnimationPoseData, const FAnimationPoseData & MeshSpaceRotationAdditiveAnimationPoseData, float Weight) static
References AccumulateRootSpaceRotationAdditiveToLocalPose(), and Weight.
Referenced by AccumulateRootSpaceRotationAdditiveToLocalPose().
AdvanceTime()
ETypeAdvanceAnim FAnimationRuntime::AdvanceTime (const bool bAllowLooping, const float MoveDelta, float & InOutTime, const float EndTime) static
Advance CurrentTime to CurrentTime + MoveDelta.
It will handle wrapping if bAllowLooping is true
return ETypeAdvanceAnim type
References AdvanceTime().
Referenced by AdvanceTime().
AppendActiveMorphTargets()
void FAnimationRuntime::AppendActiveMorphTargets (const USkeletalMesh * InSkeletalMesh, const TMap< FName, float > & InMorphCurveAnims, FMorphTargetWeightMap & InOutActiveMorphTargets, TArray< float > & InOutMorphTargetWeights) static
Combine CurveKeys (that reference morph targets by name) and ActiveAnims (that reference morphs by reference) into the ActiveMorphTargets array.
ApplyWeightToTransform()
void FAnimationRuntime::ApplyWeightToTransform (const FBoneContainer & RequiredBones, FTransformArrayA2 & Atoms, float Weight) static
Apply Weight to the Transform Atoms = Weight * Atoms at the end.
References ApplyWeightToTransform(), and Weight.
Referenced by ApplyWeightToTransform().
BlendPosesPerBoneFilter()
void FAnimationRuntime::BlendPosesPerBoneFilter (FCompactPose & BasePose, const TArray< FCompactPose > & BlendPoses, FBlendedCurve & BaseCurve, const TArray< FBlendedCurve > & BlendCurves, UE::Anim::FStackAttributeContainer & CustomAttributes, const TArray< UE::Anim::FStackAttributeContainer > & BlendAttributes, FAnimationPoseData & OutAnimationPoseData, TArray< FPerBoneBlendWeight > & BoneBlendWeights, EBlendPosesPerBoneFilterFlags blendFlags, enum ECurveBlendOption::Type CurveBlendOption) static
References BaseCurve, BlendCurves, blendFlags, BlendPoses, BlendPosesPerBoneFilter(), BoneBlendWeights, and CurveBlendOption.
Referenced by BlendPosesPerBoneFilter(), and UE_DEPRECATED().
BlendPosesTogether() [1/2]
void FAnimationRuntime::BlendPosesTogether (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, TArrayView< const float > SourceWeights, FAnimationPoseData & OutAnimationPoseData) static
References BlendPosesTogether(), SourceCurves, and SourceWeights.
Referenced by BlendPosesTogether(), BlendPosesTogether(), and UE_DEPRECATED().
BlendPosesTogether() [2/2]
void FAnimationRuntime::BlendPosesTogether (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, TArrayView< const float > SourceWeights, TArrayView< const int32 > SourceWeightsIndices, FAnimationPoseData & OutPoseData) static
References BlendPosesTogether(), SourceCurves, SourceWeights, and SourceWeightsIndices.
BlendPosesTogetherIndirect()
void FAnimationRuntime::BlendPosesTogetherIndirect (TArrayView< const FCompactPose *const > SourcePoses, TArrayView< const FBlendedCurve *const > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer *const > SourceAttributes, TArrayView< const float > SourceWeights, FAnimationPoseData & OutPoseData) static
References BlendPosesTogetherIndirect(), SourceCurves, and SourceWeights.
Referenced by BlendPosesTogetherIndirect(), and UE_DEPRECATED().
BlendPosesTogetherPerBone() [1/2]
void FAnimationRuntime::BlendPosesTogetherPerBone (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider * InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, FAnimationPoseData & OutAnimationPoseData) static
References BlendPosesTogetherPerBone(), BlendSampleDataCache, InterpolationIndexProvider, and SourceCurves.
Referenced by BlendPosesTogetherPerBone(), BlendPosesTogetherPerBone(), and UE_DEPRECATED().
BlendPosesTogetherPerBone() [2/2]
void FAnimationRuntime::BlendPosesTogetherPerBone (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider * InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, FAnimationPoseData & OutAnimationPoseData) static
References BlendPosesTogetherPerBone(), BlendSampleDataCache, BlendSampleDataCacheIndices, InterpolationIndexProvider, and SourceCurves.
BlendPosesTogetherPerBoneInMeshSpace()
void FAnimationRuntime::BlendPosesTogetherPerBoneInMeshSpace (TArrayView< FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const UBlendSpace * BlendSpace, TArrayView< const FBlendSampleData > BlendSampleDataCache, FAnimationPoseData & OutAnimationPoseData) static
Blends together a set of local space (not mesh space) poses, each with a given weight.
This function is for BlendSpace per bone blending. BlendSampleDataCache contains the weight information
This blends the rotations in mesh space, so is performance intensive as it requires a conversion from joint rotations into mesh space, then the blend, then a conversion back.
Parameters
OutAnimationPoseData Output pose, curves and attributes.
References BlendPosesTogetherPerBoneInMeshSpace(), BlendSampleDataCache, BlendSpace, and SourceCurves.
Referenced by BlendPosesTogetherPerBoneInMeshSpace(), and UE_DEPRECATED().
BlendPosesTogetherPerBoneRemapped()
void FAnimationRuntime::BlendPosesTogetherPerBoneRemapped (TArrayView< const FCompactPose > SourcePoses, TArrayView< const FBlendedCurve > SourceCurves, TArrayView< const UE::Anim::FStackAttributeContainer > SourceAttributes, const IInterpolationIndexProvider * InterpolationIndexProvider, TArrayView< const FBlendSampleData > BlendSampleDataCache, TArrayView< const int32 > BlendSampleDataCacheIndices, const FSkeletonRemapping & SkeletonRemapping, FAnimationPoseData & OutAnimationPoseData) static
References BlendPosesTogetherPerBoneRemapped(), BlendSampleDataCache, BlendSampleDataCacheIndices, InterpolationIndexProvider, and SourceCurves.
Referenced by BlendPosesTogetherPerBoneRemapped().
BlendTwoPosesTogether()
void FAnimationRuntime::BlendTwoPosesTogether (const FAnimationPoseData & SourcePoseOneData, const FAnimationPoseData & SourcePoseTwoData, const float WeightOfPoseOne, FAnimationPoseData & OutAnimationPoseData) static
References BlendTwoPosesTogether().
Referenced by BlendTwoPosesTogether(), and UE_DEPRECATED().
BlendTwoPosesTogetherPerBone() [1/2]
void FAnimationRuntime::BlendTwoPosesTogetherPerBone (const FAnimationPoseData & SourcePoseOneData, const FAnimationPoseData & SourcePoseTwoData, const TArray< float > & WeightsOfSource2, FAnimationPoseData & OutAnimationPoseData) static
References BlendTwoPosesTogetherPerBone(), and WeightsOfSource2.
Referenced by BlendTwoPosesTogetherPerBone(), BlendTwoPosesTogetherPerBone(), and UE_DEPRECATED().
BlendTwoPosesTogetherPerBone() [2/2]
void FAnimationRuntime::BlendTwoPosesTogetherPerBone (const FCompactPose & SourcePoseOneData, const FCompactPose & SourcePoseTwoData, const TArray< float > & WeightsOfSource2, FCompactPose & OutAnimationPoseData) static
References BlendTwoPosesTogetherPerBone(), and WeightsOfSource2.
CombineWithAdditiveAnimations()
void FAnimationRuntime::CombineWithAdditiveAnimations (int32 NumAdditivePoses, const FTransformArrayA2 ** SourceAdditivePoses, const float * SourceAdditiveWeights, const FBoneContainer & RequiredBones, FTransformArrayA2 & Atoms) static
References CombineWithAdditiveAnimations().
Referenced by CombineWithAdditiveAnimations().
ConvertBoneSpaceTransformToCS()
void FAnimationRuntime::ConvertBoneSpaceTransformToCS (const FTransform & ComponentTransform, FCSPose< FCompactPose > & MeshBases, FTransform & InOutBoneSpaceTM, FCompactPoseBoneIndex BoneIndex, EBoneControlSpace Space) static
Convert a FTransform in a specified bone space to ComponentSpace.
Parameters
ComponentTransform The transform of the component. Only used if Space == BCS_WorldSpace
MeshBases The pose to use when transforming
InOutBoneSpaceTM The bone transform to convert
BoneIndex The bone index of the transform
Space The space that the transform is in.
References ConvertBoneSpaceTransformToCS().
Referenced by ConvertBoneSpaceTransformToCS().
ConvertCSTransformToBoneSpace()
void FAnimationRuntime::ConvertCSTransformToBoneSpace (const FTransform & ComponentTransform, FCSPose< FCompactPose > & MeshBases, FTransform & InOutCSBoneTM, FCompactPoseBoneIndex BoneIndex, EBoneControlSpace Space) static
Convert a ComponentSpace FTransform to specified bone space.
Parameters
ComponentTransform The transform of the component. Only used if Space == BCS_WorldSpace
MeshBases The pose to use when transforming
InOutCSBoneTM The component space transform to convert
BoneIndex The bone index of the transform
Space The space to convert the input transform into.
References ConvertCSTransformToBoneSpace().
Referenced by ConvertCSTransformToBoneSpace().
ConvertMeshRotationPoseToLocalSpace()
void FAnimationRuntime::ConvertMeshRotationPoseToLocalSpace (FCompactPose & Pose) static
Convert a MeshSpaceRotation pose to Local Space.
Rotations are NOT normalized.
References ConvertMeshRotationPoseToLocalSpace().
Referenced by ConvertMeshRotationPoseToLocalSpace().
ConvertPoseToAdditive()
void FAnimationRuntime::ConvertPoseToAdditive (FCompactPose & TargetPose, const FCompactPose & BasePose) static
Convert TargetPose into an AdditivePose, by doing TargetPose = TargetPose - BasePose.
References ConvertPoseToAdditive().
Referenced by ConvertPoseToAdditive().
ConvertPoseToMeshRotation()
void FAnimationRuntime::ConvertPoseToMeshRotation (FCompactPose & LocalPose) static
Convert LocalPose into MeshSpaceRotations.
Rotations are NOT normalized.
References ConvertPoseToMeshRotation().
Referenced by ConvertPoseToMeshRotation().
ConvertPoseToMeshSpace()
void FAnimationRuntime::ConvertPoseToMeshSpace (const TArray< FTransform > & LocalTransforms, TArray< FTransform > & MeshSpaceTransforms, const FBoneContainer & RequiredBones) static
Convert LocalTransforms into MeshSpaceTransforms over RequiredBones.
References ConvertPoseToMeshSpace().
Referenced by ConvertPoseToMeshSpace().
ConvertTransformToAdditive()
void FAnimationRuntime::ConvertTransformToAdditive (FTransform & TargetTrasnform, const FTransform & BaseTransform) static
convert transform to additive
References ConvertTransformToAdditive().
Referenced by ConvertTransformToAdditive().
CreateMaskWeights() [1/2]
void FAnimationRuntime::CreateMaskWeights (TArray< FPerBoneBlendWeight > & BoneBlendWeights, const TArray< class UBlendProfile * > & BlendMasks, const USkeleton * Skeleton) static
Create Mask Weight for skeleton joints, not per mesh or per required bones Individual alphas are read from a BlendProfile using a BlendMask mode.
References BoneBlendWeights, CreateMaskWeights(), and Skeleton.
CreateMaskWeights() [2/2]
void FAnimationRuntime::CreateMaskWeights (TArray< FPerBoneBlendWeight > & BoneBlendWeights, const TArray< FInputBlendPose > & BlendFilters, const USkeleton * Skeleton) static
Create Mask Weight for skeleton joints, not per mesh or per required bones You'll have to filter properly with correct mesh joint or required bones The depth should not change based on LOD or mesh or skeleton They still should contain same depth.
References BoneBlendWeights, CreateMaskWeights(), and Skeleton.
Referenced by CreateMaskWeights(), and CreateMaskWeights().
EnsureParentsPresent()
void FAnimationRuntime::EnsureParentsPresent (TArray< FBoneIndexType > & BoneIndices, const FReferenceSkeleton & RefSkeleton) static
Utility for taking an array of bone indices and ensuring that all parents are present (ie.
all bones between those in the array and the root are present). Note that this must ensure the invariant that parent occur before children in BoneIndices.
References EnsureParentsPresent().
Referenced by EnsureParentsPresent().
ExcludeBonesWithNoParents()
void FAnimationRuntime::ExcludeBonesWithNoParents (const TArray< int32 > & BoneIndices, const FReferenceSkeleton & RefSkeleton, TArray< int32 > & FilteredRequiredBones) static
References ExcludeBonesWithNoParents().
Referenced by ExcludeBonesWithNoParents().
FillUpComponentSpaceTransforms()
void FAnimationRuntime::FillUpComponentSpaceTransforms (const FReferenceSkeleton & RefSkeleton, const TArrayView< const FTransform > & BoneSpaceTransforms, TArray< FTransform > & ComponentSpaceTransforms) static
References FillUpComponentSpaceTransforms().
Referenced by FillUpComponentSpaceTransforms().
FillUpComponentSpaceTransformsRefPose()
void FAnimationRuntime::FillUpComponentSpaceTransformsRefPose (const USkeleton * Skeleton, TArray< FTransform > & ComponentSpaceTransforms) static
References Skeleton.
FillWithRefPose()
void FAnimationRuntime::FillWithRefPose (TArray< FTransform > & OutAtoms, const FBoneContainer & RequiredBones) static
Fill ref pose.
References FillWithRefPose().
Referenced by FillWithRefPose().
GetBoneTranslationRetargetingMode()
EBoneTranslationRetargetingMode::Type FAnimationRuntime::GetBoneTranslationRetargetingMode (const bool bUseSourceRetargetModes, const int32 SourceSkeletonBoneIndex, const int32 TargetSkeletonBoneIndex, const USkeleton * SourceSkeleton, const USkeleton * TargetSkeleton, const bool bDisableRetargeting) static
Get the translational retargeting mode for a given bone on the target skeleton when sampling a given source animation.
If bUseSourceRetargetModes is set to true, and SourceSkeletonBoneIndex is INDEX_NONE, then the target bone and target skeleton are used instead. If bUseSourceRetargetModes is set to false, the SourceSkeleton and SourceSkeletonBoneIndex values are ignored and we get the retarget mode directly from the target skeleton using the target bone index.
Parameters
bUseSourceRetargetModes Set to true when you wish to extract the retarget mode from the source skeleton instead of the target skeleton.
SourceSkeletonBoneIndex The skeleton bone index of the bone on the source skeleton to get the retarget mode from.
TargetSkeletonBoneIndex The target bone index of the bone on the target skeleton to get the retarget mode from.
SourceSkeleton A pointer to the skeleton of the source (the animation's skeleton for example).
TargetSkeleton A pointer to the target skeleton, which is the skeleton to apply transforms to.
bDisableRetargeting Is translational retargeting disabled?
Returns
The retargeting mode for the specific bone.
References GetBoneTranslationRetargetingMode(), and SourceSkeleton.
Referenced by GetBoneTranslationRetargetingMode().
GetComponentSpaceRefPose()
FTransform FAnimationRuntime::GetComponentSpaceRefPose (const FCompactPoseBoneIndex & CompactPoseBoneIndex, const FBoneContainer & BoneContainer) static
Get Reference Component Space Transform.
References GetComponentSpaceRefPose().
Referenced by GetComponentSpaceRefPose().
GetComponentSpaceTransform()
FTransform FAnimationRuntime::GetComponentSpaceTransform (const FReferenceSkeleton & RefSkeleton, const TArrayView< const FTransform > & BoneSpaceTransforms, int32 BoneIndex) static
References GetComponentSpaceTransform().
Referenced by GetComponentSpaceTransform().
GetComponentSpaceTransformRefPose()
FTransform FAnimationRuntime::GetComponentSpaceTransformRefPose (const FReferenceSkeleton & RefSkeleton, int32 BoneIndex) static
References GetComponentSpaceTransformRefPose().
Referenced by GetComponentSpaceTransformRefPose().
GetComponentSpaceTransformWithCache()
const FTransform & FAnimationRuntime::GetComponentSpaceTransformWithCache (const FReferenceSkeleton & InRefSkeleton, const TArray< FTransform > & InBoneSpaceTransforms, int32 BoneIndex, TArray< FTransform > & CachedTransforms, TArray< bool > & CachedTransformReady) static
Calculate the component-space bone transform for the specified bone.
This is similar to GetComponentSpaceTransform(), but uses a cached array of transforms to prevent re-calculations when requesting transforms for multiple bones with shared parents. This is only likely to be more efficient than FillUpComponentSpaceTransforms if you only need a relatively small number of bone transforms.
Parameters
InRefSkeleton The bone hierarchy
InBoneSpaceTransforms Bone-space transforms for all bones in the hierarchy
BoneIndex We calculate the component-space transform of this bone
CachedTransforms An array of transforms which holds the transforms of any bones whose transforms have been previously calculated. Should be initialized with CachedTransforms.SetNumUninitialized(BoneSpaceTransforms.Num()) before first use.
CachedTransformReady An array of flags indicating which bone transforms have been cached. Should be initialized with CachedTransformReady.SetNumZeroed(BoneSpaceTransforms.Num()) before first use.
References GetComponentSpaceTransformWithCache().
Referenced by GetComponentSpaceTransformWithCache().
GetKeyIndicesFromTime() [1/2]
void FAnimationRuntime::GetKeyIndicesFromTime (int32 & OutKeyIndex1, int32 & OutKeyIndex2, float & OutAlpha, const double Time, const FFrameRate & FrameRate, const int32 NumberOfKeys) static
Get KeyIndices using FFrameRate::AsFrameTime to calculate the keys and alpha value.
References FrameRate, GetKeyIndicesFromTime(), and Time.
GetKeyIndicesFromTime() [2/2]
void FAnimationRuntime::GetKeyIndicesFromTime (int32 & OutKeyIndex1, int32 & OutKeyIndex2, float & OutAlpha, const double Time, const int32 NumKeys, const double SequenceLength, double FramesPerSecond = -1.0) static
Get Key Indices (start/end with alpha from start) with input parameter Time, NumKeys from % from StartKeyIndex, meaning (CurrentKeyIndex(float)-StartKeyIndex)/(EndKeyIndex-StartKeyIndex) by this Start-End, it will be between 0-(NumKeys-1), not number of Pos/Rot key tracks The FramesPerSecond parameter must be the sample rate of the animation data, for example 30.
If the FramesPerSecond parameter is set to 0 or negative, it will automatically calculate the FramesPerSecond based on the sequence length and number of frames. The reason why you can provide a FramesPerSecond value is because this can be slightly more accurate than calculating it, in case super high precision is needed.
References GetKeyIndicesFromTime(), SequenceLength, and Time.
Referenced by GetKeyIndicesFromTime(), and GetKeyIndicesFromTime().
GetSpaceTransform() [1/2]
FTransform FAnimationRuntime::GetSpaceTransform (FA2CSPose & Pose, int32 Index) static
References GetSpaceTransform().
GetSpaceTransform() [2/2]
FTransform FAnimationRuntime::GetSpaceTransform (FA2Pose & Pose, int32 Index) static
References GetSpaceTransform().
Referenced by GetSpaceTransform(), and GetSpaceTransform().
GetStringDistance()
int32 FAnimationRuntime::GetStringDistance (const FString & First, const FString & Second) static
Calculate distance how close two strings are.
By close, it calculates how many operations to transform First to Second The return value is [0-MaxLengthString(First, Second)] 0 means it's identical, Max means it's completely different
References First, and Second.
HasWeight()
FORCEINLINE bool FAnimationRuntime::HasWeight (float Weight) inline static
Definition at line 651 of file AnimationRuntime.h.
References FORCEINLINE, FAnimWeight::IsRelevant(), and Weight.
InitializeTransform()
void FAnimationRuntime::InitializeTransform (const FBoneContainer & RequiredBones, FTransformArrayA2 & Atoms) static
IsFullWeight()
FORCEINLINE bool FAnimationRuntime::IsFullWeight (float Weight) inline static
Definition at line 650 of file AnimationRuntime.h.
References FORCEINLINE, FAnimWeight::IsFullWeight(), and Weight.
LerpBoneTransforms()
void FAnimationRuntime::LerpBoneTransforms (TArray< FTransform > & A, const TArray< FTransform > & B, float Alpha, const TArray< FBoneIndexType > & RequiredBonesArray) static
Lerp for BoneTransforms.
Stores results in A. Performs A = Lerp(A, B, Alpha);
Parameters
A : In/Out transform array.
B : B In transform array.
Alpha : Alpha.
RequiredBonesArray : Array of bone indices.
References A, Alpha, B, and LerpBoneTransforms().
Referenced by LerpBoneTransforms().
LerpPoses()
void FAnimationRuntime::LerpPoses (FCompactPose & PoseA, const FCompactPose & PoseB, FBlendedCurve & CurveA, const FBlendedCurve & CurveB, float Alpha) static
Lerp for FCompactPose.
Stores results in PoseA. Performs PoseA = Lerp(PoseA, PoseB, Alpha);
References Alpha, and LerpPoses().
Referenced by LerpPoses().
LerpPosesPerBone()
void FAnimationRuntime::LerpPosesPerBone (FCompactPose & PoseA, const FCompactPose & PoseB, FBlendedCurve & CurveA, const FBlendedCurve & CurveB, float Alpha, const TArray< float > & PerBoneWeights) static
Lerp for FCompactPose.
Stores results in PoseA. For each bone performs BoneA[i] = Lerp(BoneA[i], BoneB[i], Alpha * PerBoneWeights[i]);
References Alpha, and LerpPosesPerBone().
Referenced by LerpPosesPerBone().
LerpPosesWithBoneIndexList()
void FAnimationRuntime::LerpPosesWithBoneIndexList (FCompactPose & PoseA, const FCompactPose & PoseB, FBlendedCurve & CurveA, const FBlendedCurve & CurveB, float Alpha, const TArray< FCompactPoseBoneIndex > & BoneIndices) static
Lerp for FCompactPose.
Stores results in PoseA. Performs PoseA = Lerp(PoseA, PoseB, Alpha); on reduced set of bones defined in BoneIndices list.
References Alpha, and LerpPosesWithBoneIndexList().
Referenced by LerpPosesWithBoneIndexList().
MakeSkeletonRefPoseFromMesh()
void FAnimationRuntime::MakeSkeletonRefPoseFromMesh (const USkeletalMesh * InMesh, const USkeleton * InSkeleton, TArray< FTransform > & OutBoneBuffer) static
References MakeSkeletonRefPoseFromMesh().
Referenced by MakeSkeletonRefPoseFromMesh().
MirrorCurves()
void FAnimationRuntime::MirrorCurves (FBlendedCurve & Curves, const UMirrorDataTable & MirrorDataTable) static
Mirror (swap) curves with the specified MirrorDataTable.
Partial mirroring is supported, and curves with two entries (Right->Left and Left->Right) will be swapped while curves with a single entry will be overwritten
Parameters
Curves The Curves which are swapped
MirrorDataTable A UMirrorDataTable specifying which curves to swap
References Curves, and MirrorCurves().
Referenced by MirrorCurves().
MirrorPose() [1/2]
void FAnimationRuntime::MirrorPose (FCompactPose & Pose, const UMirrorDataTable & MirrorDataTable) static
Mirror a pose with the specified MirrorDataTable.
This method computes the required compact mirror pose and component space reference rotations each call and should not be used for repeated calculations
Parameters
Pose The pose which is mirrored in place
MirrorDataTable A UMirrorDataTable for the same Skeleton as the Pose
References MirrorPose().
Referenced by MirrorPose(), and MirrorPose().
MirrorPose() [2/2]
void FAnimationRuntime::MirrorPose (FCompactPose & Pose, EAxis::Type MirrorAxis, const TArray< FCompactPoseBoneIndex > & CompactPoseMirrorBones, const TCustomBoneIndexArray< FQuat, FCompactPoseBoneIndex > & ComponentSpaceRefRotations) static
Mirror Pose using cached mirror bones and components space arrays.
Parameters
Pose The pose which is mirrored in place
MirrorAxis The axis that all bones are mirrored across
CompactPoseMirrorBones Compact array of bone indices. Each index contains the bone to mirror or -1 to indicate mirroring should not apply to that bone.
ComponentSpaceRefRotations Compoenent space rotations of the reference pose for each bone.
References MirrorPose().
MirrorQuat()
FQuat FAnimationRuntime::MirrorQuat (const FQuat & Q, EAxis::Type MirrorAxis) static
Mirror a quaternion across the specified mirror axis.
Parameters
Q The quaternion to mirror
MirrorAxis The axis to mirror across
Returns
The quaternion mirrored across the specified axis
References MirrorQuat().
Referenced by MirrorQuat().
MirrorVector()
FVector FAnimationRuntime::MirrorVector (const FVector & V, EAxis::Type MirrorAxis) static
Mirror a vector across the specified mirror axis.
Parameters
V The vector to mirror
MirrorAxis The axis to mirror across
Returns
The vector mirrored across the specified axis
References FVector, and MirrorVector().
Referenced by MirrorVector().
NormalizeRotations() [1/2]
void FAnimationRuntime::NormalizeRotations (const FBoneContainer & RequiredBones, FTransformArrayA2 & Atoms) static
NormalizeRotations() [2/2]
void FAnimationRuntime::NormalizeRotations (FTransformArrayA2 & Atoms) static
RetargetBoneTransform() [1/2]
void FAnimationRuntime::RetargetBoneTransform (const USkeleton * MySkeleton, const FName & SourceName, const TArray< FTransform > & RetargetTransforms, FTransform & BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex & BoneIndex, const FBoneContainer & RequiredBones, const bool bIsBakedAdditive) static
References bIsBakedAdditive, RetargetTransforms, and SourceName.
RetargetBoneTransform() [2/2]
void FAnimationRuntime::RetargetBoneTransform (const USkeleton * SourceSkeleton, const FName & RetargetSource, FTransform & BoneTransform, const int32 SkeletonBoneIndex, const FCompactPoseBoneIndex & BoneIndex, const FBoneContainer & RequiredBones, const bool bIsBakedAdditive) static
Retarget a single bone transform, to apply right after extraction.
Parameters
SourceSkeleton Skeleton from which this is retargeting
RetargetSource Retarget Source for the retargeting
BoneTransform BoneTransform to read/write from
SkeletonBoneIndex Source Bone Index in SourceSkeleton
BoneIndex Target Bone Index in Bone Transform array
RequiredBones BoneContainer to which this is retargeting
References bIsBakedAdditive, RetargetSource, and SourceSkeleton.
SetSpaceTransform() [1/2]
void FAnimationRuntime::SetSpaceTransform (FA2CSPose & Pose, int32 Index, FTransform & NewTransform) static
References SetSpaceTransform().
SetSpaceTransform() [2/2]
void FAnimationRuntime::SetSpaceTransform (FA2Pose & Pose, int32 Index, FTransform & NewTransform) static
References SetSpaceTransform().
Referenced by SetSpaceTransform(), and SetSpaceTransform().
TickBlendWeight()
void FAnimationRuntime::TickBlendWeight (float DeltaTime, float DesiredWeight, float & Weight, float & BlendTime) static
References DeltaTime, TickBlendWeight(), and Weight.
Referenced by TickBlendWeight().
UE_DEPRECATED() [1/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Please use the BlendPosesPerBoneFilterwith different signature.") &
Blend Poses per bone weights : The BasePoses + BlendPoses(SourceIndex) * Blend Weights(BoneIndex) Please note BlendWeights are array, so you can define per bone base This supports multi per bone blending, but only one pose as blend at a time per track PerBoneBlendWeights.Num() == Atoms.Num()
Note
: This optionally blends rotation and/or scale in mesh space. Translation is always in local space.
I had multiple debates about having PerBoneBlendWeights array(for memory reasons), but it so much simplifies multiple purpose for this function instead of searching bonenames or having multiple bone names with multiple weights, and filtering through which one is correct one I assume all those things should be determined before coming here and this only cares about weights
References BlendPosesPerBoneFilter().
UE_DEPRECATED() [2/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use AccumulateAdditivePose with other signature") &
Accumulate Additive Pose based on AdditiveType.
References UE_DEPRECATED().
UE_DEPRECATED() [3/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use AccumulateAdditivePose with other signature") &
Accumulates weighted AdditivePose to BasePose.
Rotations are NOT normalized.
References AccumulateLocalSpaceAdditivePose(), AdditiveCurve, AdditivePose, BaseCurve, UE_DEPRECATED(), and Weight.
UE_DEPRECATED() [4/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use AccumulateAdditivePose with other signature") &
Accumulate a MeshSpaceRotation Additive pose to a local pose.
Rotations are NOT normalized
References UE_DEPRECATED().
UE_DEPRECATED() [5/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogether with other signature") const
Blends together a set of poses, each with a given weight.
This function is lightweight, it does not cull out nearly zero weights or check to make sure weights sum to 1.0, the caller should take care of that if needed.
The blend is done by taking a weighted sum of each atom, and re-normalizing the quaternion part at the end, not using SLERP. This allows n-way blends, and makes the code much faster, though the angular velocity will not be constant across the blend.
Parameters
ResultPose Output pose of relative bone transforms.
References BlendPosesTogether().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogether with other signature") const
Blends together a set of poses, each with a given weight.
This function is lightweight, it does not cull out nearly zero weights or check to make sure weights sum to 1.0, the caller should take care of that if needed.
The blend is done by taking a weighted sum of each atom, and re-normalizing the quaternion part at the end, not using SLERP. This allows n-way blends, and makes the code much faster, though the angular velocity will not be constant across the blend.
SourceWeightsIndices is used to index SourceWeights, to prevent caller having to supply an ordered weights array
Parameters
ResultPose Output pose of relative bone transforms.
References BlendPosesTogether(), SourceCurves, SourceWeights, and UE_DEPRECATED().
UE_DEPRECATED() [7/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogetherIndirect with other signature") const
Blends together a set of poses, each with a given weight.
This function is lightweight, it does not cull out nearly zero weights or check to make sure weights sum to 1.0, the caller should take care of that if needed.
The blend is done by taking a weighted sum of each atom, and re-normalizing the quaternion part at the end, not using SLERP. This allows n-way blends, and makes the code much faster, though the angular velocity will not be constant across the blend.
Parameters
ResultPose Output pose of relative bone transforms.
References BlendPosesTogetherIndirect(), and UE_DEPRECATED().
UE_DEPRECATED() [8/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogetherPerBone with other signature") const
Blends together a set of poses, each with a given weight.
This function is for BlendSpace per bone blending. BlendSampleDataCache contains the weight information
This blends in local space
Parameters
ResultPose Output pose of relative bone transforms.
References BlendPosesTogetherPerBone(), SourceCurves, and UE_DEPRECATED().
UE_DEPRECATED() [9/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogetherPerBone with other signature") const
Blends together a set of poses, each with a given weight.
This function is for BlendSpace per bone blending. BlendSampleDataCache contains the weight information and is indexed using BlendSampleDataCacheIndices, to prevent caller having to supply an ordered array
This blends in local space
Parameters
ResultPose Output pose of relative bone transforms.
References BlendPosesTogetherPerBone(), BlendSampleDataCache, InterpolationIndexProvider, SourceCurves, and UE_DEPRECATED().
UE_DEPRECATED() [10/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendPosesTogetherPerBone with other signature")
Blends together a set of local space (not mesh space) poses, each with a given weight.
This function is for BlendSpace per bone blending. BlendSampleDataCache contains the weight information
This blends the rotations in mesh space, so is performance intensive as it requires a conversion from joint rotations into mesh space, then the blend, then a conversion back.
Parameters
OutResultPose Output blended pose of relative bone transforms.
OutResultCurve Output blended curves
References BlendPosesTogetherPerBoneInMeshSpace(), SourceCurves, and UE_DEPRECATED().
UE_DEPRECATED() [11/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendTwoPosesTogether with other signature") const &
Blends together two poses.
This function is lightweight
The blend is done by taking a weighted sum of each atom, and re-normalizing the quaternion part at the end, not using SLERP.
Parameters
ResultPose Output pose of relative bone transforms.
References BlendTwoPosesTogether(), and UE_DEPRECATED().
UE_DEPRECATED() [12/13]
FAnimationRuntime::UE_DEPRECATED (4. 26, "Use BlendTwoPosesTogether with other signature") const &
Blends together a set of poses, each with a given weight.
This function is for BlendSpace per bone blending. BlendSampleDataCache contains the weight information
This blends in local space
Parameters
ResultPose Output pose of relative bone transforms.
References BlendTwoPosesTogetherPerBone(), SourceCurve1, SourceCurve2, SourcePose2, and UE_DEPRECATED().
UE_DEPRECATED() [13/13]
FAnimationRuntime::UE_DEPRECATED (4.26. 0, "Please use BlendTransform() for weighted blending") &
Blend Array of Transforms by weight.
Parameters
OutTransform : result
References UE_DEPRECATED().
UpdateDesiredBoneWeight()
void FAnimationRuntime::UpdateDesiredBoneWeight (const TArray< FPerBoneBlendWeight > & SrcBoneBlendWeights, TArray< FPerBoneBlendWeight > & TargetBoneBlendWeights, const TArray< float > & BlendWeights) static
References UpdateDesiredBoneWeight().
Referenced by UpdateDesiredBoneWeight().
Field Documentation
AdditiveCurve
const FCompactPose FBlendedCurve const FBlendedCurve & FAnimationRuntime::AdditiveCurve
Definition at line 446 of file AnimationRuntime.h.
Referenced by UE_DEPRECATED().
AdditivePose
const FCompactPose & FAnimationRuntime::AdditivePose
Definition at line 446 of file AnimationRuntime.h.
Referenced by AccumulateLocalSpaceAdditivePoseInternal(), and UE_DEPRECATED().
AdditiveType
const FCompactPose FBlendedCurve const FBlendedCurve float enum EAdditiveAnimationType FAnimationRuntime::AdditiveType
Definition at line 446 of file AnimationRuntime.h.
Referenced by AccumulateAdditivePose().
BaseCurve [1/2]
const FCompactPose FBlendedCurve & FAnimationRuntime::BaseCurve
Definition at line 374 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter(), and UE_DEPRECATED().
BaseCurve [2/2]
const FCompactPose FBlendedCurve& FAnimationRuntime::BaseCurve
Definition at line 446 of file AnimationRuntime.h.
BlendCurves
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve>& FAnimationRuntime::BlendCurves
Definition at line 375 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter().
blendFlags
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve> FCompactPose FBlendedCurve TArray<FPerBoneBlendWeight> EBlendPosesPerBoneFilterFlags FAnimationRuntime::blendFlags
Definition at line 379 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter().
BlendPoses
const TArray<FCompactPose>& FAnimationRuntime::BlendPoses
Definition at line 373 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter().
BlendSampleDataCache [1/2]
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider TArrayView< const FBlendSampleData > FAnimationRuntime::BlendSampleDataCache
Definition at line 259 of file AnimationRuntime.h.
Referenced by BlendPosesTogetherPerBone(), BlendPosesTogetherPerBone(), BlendPosesTogetherPerBoneInMeshSpace(), BlendPosesTogetherPerBoneRemapped(), and UE_DEPRECATED().
BlendSampleDataCache [2/2]
TArrayView<const FBlendedCurve> const UBlendSpace TArrayView<const FBlendSampleData> FAnimationRuntime::BlendSampleDataCache
Definition at line 326 of file AnimationRuntime.h.
BlendSampleDataCacheIndices
TArrayView<const FBlendedCurve> const IInterpolationIndexProvider TArrayView<const FBlendSampleData> TArrayView<const int32> FAnimationRuntime::BlendSampleDataCacheIndices
Definition at line 297 of file AnimationRuntime.h.
Referenced by BlendPosesTogetherPerBone(), and BlendPosesTogetherPerBoneRemapped().
BlendSpace
TArrayView<const FBlendedCurve> const UBlendSpace* FAnimationRuntime::BlendSpace
Definition at line 325 of file AnimationRuntime.h.
Referenced by BlendPosesTogetherPerBoneInMeshSpace().
BoneBlendWeights
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve> FCompactPose FBlendedCurve TArray<FPerBoneBlendWeight>& FAnimationRuntime::BoneBlendWeights
Definition at line 378 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter(), CreateMaskWeights(), and CreateMaskWeights().
CurveBlendOption
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve> FCompactPose FBlendedCurve TArray<FPerBoneBlendWeight> EBlendPosesPerBoneFilterFlags enum ECurveBlendOption::Type FAnimationRuntime::CurveBlendOption
Definition at line 380 of file AnimationRuntime.h.
Referenced by BlendPosesPerBoneFilter().
InterpolationIndexProvider
TArrayView< const FBlendedCurve > const IInterpolationIndexProvider * FAnimationRuntime::InterpolationIndexProvider
Definition at line 258 of file AnimationRuntime.h.
Referenced by BlendPosesTogetherPerBone(), BlendPosesTogetherPerBone(), BlendPosesTogetherPerBoneRemapped(), and UE_DEPRECATED().
MeshSpaceRotationAdditive
const FCompactPose& FAnimationRuntime::MeshSpaceRotationAdditive
Definition at line 470 of file AnimationRuntime.h.
Referenced by AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal().
OutCurve
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve> FCompactPose FBlendedCurve& FAnimationRuntime::OutCurve
Definition at line 377 of file AnimationRuntime.h.
OutPose
const TArray<FCompactPose> FBlendedCurve const TArray<FBlendedCurve> FCompactPose& FAnimationRuntime::OutPose
Definition at line 376 of file AnimationRuntime.h.
OutResultCurve
TArrayView<const FBlendedCurve> const UBlendSpace TArrayView<const FBlendSampleData> FCompactPose FBlendedCurve& FAnimationRuntime::OutResultCurve
Definition at line 328 of file AnimationRuntime.h.
OutResultPose
TArrayView<const FBlendedCurve> const UBlendSpace TArrayView<const FBlendSampleData> FCompactPose& FAnimationRuntime::OutResultPose
Definition at line 327 of file AnimationRuntime.h.
ResultCurve [1/7]
TArrayView<const FBlendedCurve> TArrayView<const float> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 130 of file AnimationRuntime.h.
ResultCurve [2/7]
TArrayView<const FBlendedCurve> TArrayView<const float> TArrayView<const int32> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 157 of file AnimationRuntime.h.
ResultCurve [3/7]
TArrayView<const FBlendedCurve* const> TArrayView<const float> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 183 of file AnimationRuntime.h.
ResultCurve [4/7]
const FCompactPose const FBlendedCurve const FBlendedCurve const float FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 208 of file AnimationRuntime.h.
ResultCurve [5/7]
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray<float> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 232 of file AnimationRuntime.h.
ResultCurve [6/7]
TArrayView<const FBlendedCurve> const IInterpolationIndexProvider TArrayView<const FBlendSampleData> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 261 of file AnimationRuntime.h.
ResultCurve [7/7]
TArrayView<const FBlendedCurve> const IInterpolationIndexProvider TArrayView<const FBlendSampleData> TArrayView<const int32> FCompactPose FBlendedCurve& FAnimationRuntime::ResultCurve
Definition at line 299 of file AnimationRuntime.h.
ResultPose [1/7]
TArrayView<const FBlendedCurve> TArrayView<const float> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 129 of file AnimationRuntime.h.
ResultPose [2/7]
TArrayView<const FBlendedCurve> TArrayView<const float> TArrayView<const int32> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 156 of file AnimationRuntime.h.
ResultPose [3/7]
TArrayView<const FBlendedCurve* const> TArrayView<const float> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 182 of file AnimationRuntime.h.
ResultPose [4/7]
const FCompactPose const FBlendedCurve const FBlendedCurve const float FCompactPose& FAnimationRuntime::ResultPose
Definition at line 207 of file AnimationRuntime.h.
ResultPose [5/7]
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray<float> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 231 of file AnimationRuntime.h.
ResultPose [6/7]
TArrayView<const FBlendedCurve> const IInterpolationIndexProvider TArrayView<const FBlendSampleData> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 260 of file AnimationRuntime.h.
ResultPose [7/7]
TArrayView<const FBlendedCurve> const IInterpolationIndexProvider TArrayView<const FBlendSampleData> TArrayView<const int32> FCompactPose& FAnimationRuntime::ResultPose
Definition at line 298 of file AnimationRuntime.h.
SourceCurve1
const FCompactPose const FBlendedCurve & FAnimationRuntime::SourceCurve1
Definition at line 204 of file AnimationRuntime.h.
Referenced by UE_DEPRECATED().
SourceCurve2
const FCompactPose const FBlendedCurve const FBlendedCurve & FAnimationRuntime::SourceCurve2
Definition at line 205 of file AnimationRuntime.h.
Referenced by UE_DEPRECATED().
SourceCurves [1/2]
TArrayView< const FBlendedCurve > FAnimationRuntime::SourceCurves
Definition at line 127 of file AnimationRuntime.h.
Referenced by BlendPosesTogether(), BlendPosesTogether(), BlendPosesTogetherIndirect(), BlendPosesTogetherPerBone(), BlendPosesTogetherPerBone(), BlendPosesTogetherPerBoneInMeshSpace(), BlendPosesTogetherPerBoneRemapped(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
SourceCurves [2/2]
TArrayView<const FBlendedCurve* const> FAnimationRuntime::SourceCurves
Definition at line 180 of file AnimationRuntime.h.
SourcePose2
const FCompactPose & FAnimationRuntime::SourcePose2
Definition at line 203 of file AnimationRuntime.h.
Referenced by UE_DEPRECATED().
SourceWeights [1/2]
TArrayView< const FBlendedCurve > TArrayView< const float > FAnimationRuntime::SourceWeights
Definition at line 128 of file AnimationRuntime.h.
Referenced by BlendPosesTogether(), BlendPosesTogether(), BlendPosesTogetherIndirect(), and UE_DEPRECATED().
SourceWeights [2/2]
TArrayView<const FBlendedCurve* const> TArrayView<const float> FAnimationRuntime::SourceWeights
Definition at line 181 of file AnimationRuntime.h.
SourceWeightsIndices
TArrayView<const FBlendedCurve> TArrayView<const float> TArrayView<const int32> FAnimationRuntime::SourceWeightsIndices
Definition at line 155 of file AnimationRuntime.h.
Referenced by BlendPosesTogether().
Transforms
const TArray<FTransform>& FAnimationRuntime::Transforms
Definition at line 503 of file AnimationRuntime.h.
Weight
const FCompactPose FBlendedCurve const FBlendedCurve float FAnimationRuntime::Weight
Definition at line 446 of file AnimationRuntime.h.
Referenced by AccumulateAdditivePose(), AccumulateLocalSpaceAdditivePose(), AccumulateLocalSpaceAdditivePoseInternal(), AccumulateMeshSpaceRotationAdditiveToLocalPose(), AccumulateMeshSpaceRotationAdditiveToLocalPoseInternal(), AccumulateRootSpaceAdditivePoseInternal(), AccumulateRootSpaceRotationAdditiveToLocalPose(), ApplyWeightToTransform(), HasWeight(), IsFullWeight(), TickBlendWeight(), and UE_DEPRECATED().
WeightOfPose1
const FCompactPose const FBlendedCurve const FBlendedCurve const float FAnimationRuntime::WeightOfPose1
Definition at line 206 of file AnimationRuntime.h.
Weights
const TArray<FTransform> const TArray<float>& FAnimationRuntime::Weights
Definition at line 503 of file AnimationRuntime.h.
WeightsOfSource2
const FCompactPose const FBlendedCurve const FBlendedCurve const TArray<float>& FAnimationRuntime::WeightsOfSource2
Definition at line 230 of file AnimationRuntime.h.
Referenced by BlendTwoPosesTogetherPerBone(), and BlendTwoPosesTogetherPerBone().
The documentation for this class was generated from the following file:
AnimationRuntime.h