Unreal Engine 5.6 C++ API: MovieSceneClipboard Namespace Reference
MovieSceneClipboard Namespace Reference
Helper functions for defining conversions between types.
Data Structures
struct TImplicitConversionFacade
struct TImplicitConversionFacade< From, bool >
Functions
template<typename From, typename To>
void DefineExplicitConversion (TFunction< To(const From &)> InConversion)
template<typename From, typename To>
void DefineImplicitConversion ()
template<typename T>
static FName GetKeyTypeName ()
template<>
FName GetKeyTypeName< bool > ()
template<>
FName GetKeyTypeName< FEventPayload > ()
template<>
FName GetKeyTypeName< FMovieSceneActorReferenceKey > ()
template<>
FName GetKeyTypeName< FMovieSceneCameraShakeSourceTrigger > ()
template<>
FName GetKeyTypeName< FMovieSceneDoubleValue > ()
template<>
FName GetKeyTypeName< FMovieSceneEvent > ()
template<>
FName GetKeyTypeName< FMovieSceneFloatValue > ()
template<>
FName GetKeyTypeName< FMovieSceneGameplayCueKey > ()
template<>
FName GetKeyTypeName< FMovieSceneObjectPathChannelKeyValue > ()
template<>
FName GetKeyTypeName< FName > ()
template<>
FName GetKeyTypeName< FString > ()
template<>
FName GetKeyTypeName< int32 > ()
template<>
FName GetKeyTypeName< int64 > ()
template<>
FName GetKeyTypeName< uint8 > ()
Detailed Description
Helper functions for defining conversions between types.
Function Documentation
DefineExplicitConversion()
template<typename From, typename To> void MovieSceneClipboard::DefineExplicitConversion (TFunction< To(const From &)> InConversion)
Definition at line 398 of file MovieSceneClipboard.h.
References FMovieSceneClipboardKey::DefineConversion().
Referenced by DefineImplicitConversion().
DefineImplicitConversion()
template<typename From, typename To> void MovieSceneClipboard::DefineImplicitConversion ()
Definition at line 404 of file MovieSceneClipboard.h.
References MovieSceneClipboard::TImplicitConversionFacade< From, To >::Cast(), and DefineExplicitConversion().
GetKeyTypeName()
template<typename T> FName MovieSceneClipboard::GetKeyTypeName () static
Definition at line 31 of file MovieSceneClipboard.h.
Referenced by FMovieSceneClipboardKeyTrack::Create(), FMovieSceneClipboardKey::DefineConversion(), FMovieSceneClipboardKey::TKey< T >::FindConversionTo(), FMovieSceneClipboardKey::TKey< T >::GetTypeName(), FMovieSceneClipboardKeyTrack::IsKeyOfType(), and FMovieSceneClipboardKey::TryGetValue().
GetKeyTypeName< bool >()
template<> FName MovieSceneClipboard::GetKeyTypeName< bool > () inline
Definition at line 51 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< FEventPayload >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FEventPayload > () inline
Definition at line 66 of file ClipboardTypes.h.
GetKeyTypeName< FMovieSceneActorReferenceKey >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneActorReferenceKey > () inline
Definition at line 61 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< FMovieSceneCameraShakeSourceTrigger >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneCameraShakeSourceTrigger > () inline
Definition at line 78 of file ClipboardTypes.h.
GetKeyTypeName< FMovieSceneDoubleValue >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneDoubleValue > () inline
Definition at line 41 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< FMovieSceneEvent >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneEvent > () inline
Definition at line 74 of file ClipboardTypes.h.
GetKeyTypeName< FMovieSceneFloatValue >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneFloatValue > () inline
Definition at line 36 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< FMovieSceneGameplayCueKey >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneGameplayCueKey > () inline
Definition at line 145 of file MovieSceneGameplayCueSections.h.
GetKeyTypeName< FMovieSceneObjectPathChannelKeyValue >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneObjectPathChannelKeyValue > () inline
Definition at line 70 of file ClipboardTypes.h.
GetKeyTypeName< FName >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FName > () inline
Definition at line 46 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< FString >()
template<> FName MovieSceneClipboard::GetKeyTypeName< FString > () inline
Definition at line 56 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< int32 >()
template<> FName MovieSceneClipboard::GetKeyTypeName< int32 > () inline
Definition at line 26 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< int64 >()
template<> FName MovieSceneClipboard::GetKeyTypeName< int64 > () inline
Definition at line 31 of file ClipboardTypes.h.
References Name.
GetKeyTypeName< uint8 >()
template<> FName MovieSceneClipboard::GetKeyTypeName< uint8 > () inline
Definition at line 21 of file ClipboardTypes.h.
References Name.