Unreal Engine 5.6 C++ API: FLockFreeLinkPolicy Struct Reference
FLockFreeLinkPolicy Struct Reference
#include "LockFreeList.h"
Public Types
enum { MAX_BITS_IN_TLinkPtr = (26) }
typedef TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 > TAllocator
typedef FIndexedPointer TDoublePtr
typedef FIndexedLockFreeLink TLink
typedef uint32 TLinkPtr
Static Public Member Functions
static uint32 AllocLockFreeLink ()
static FORCEINLINE FIndexedLockFreeLink * DerefLink (uint32 Ptr)
static void FreeLockFreeLink (uint32 Item)
static FORCEINLINE FIndexedLockFreeLink * IndexToLink (uint32 Index)
static FORCEINLINE uint32 IndexToPtr (uint32 Index)
Static Public Attributes
static TAllocator LinkAllocator
Detailed Description
Definition at line 231 of file LockFreeList.h.
Member Typedef Documentation
TAllocator
typedef TLockFreeAllocOnceIndexedAllocator<FIndexedLockFreeLink, (1 << 26) , 16384> FLockFreeLinkPolicy::TAllocator
Definition at line 240 of file LockFreeList.h.
TDoublePtr
typedef FIndexedPointer FLockFreeLinkPolicy::TDoublePtr
Definition at line 237 of file LockFreeList.h.
TLink
typedef FIndexedLockFreeLink FLockFreeLinkPolicy::TLink
Definition at line 238 of file LockFreeList.h.
TLinkPtr
typedef uint32 FLockFreeLinkPolicy::TLinkPtr
Definition at line 239 of file LockFreeList.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_BITS_IN_TLinkPtr
Definition at line 233 of file LockFreeList.h.
Member Function Documentation
AllocLockFreeLink()
uint32 FLockFreeLinkPolicy::AllocLockFreeLink () static
Referenced by FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::FLockFreePointerFIFOBase(), FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Push(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Push(), and FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PushIf().
DerefLink()
FORCEINLINE FIndexedLockFreeLink * FLockFreeLinkPolicy::DerefLink (uint32 Ptr) inline static nodiscard
Definition at line 242 of file LockFreeList.h.
References FORCEINLINE, and LinkAllocator.
Referenced by FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::IsEmpty(), FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop(), FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Pop(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndApply(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndChangeState(), FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Push(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Push(), FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::Push(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PushIf(), and FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::PushIf().
FreeLockFreeLink()
void FLockFreeLinkPolicy::FreeLockFreeLink (uint32 Item) static
References Item.
Referenced by FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::~FLockFreePointerFIFOBase(), FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndApply(), FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndChangeState(), and FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PushIf().
IndexToLink()
FORCEINLINE FIndexedLockFreeLink * FLockFreeLinkPolicy::IndexToLink (uint32 Index) inline static nodiscard
Definition at line 246 of file LockFreeList.h.
References FORCEINLINE, and LinkAllocator.
IndexToPtr()
FORCEINLINE uint32 FLockFreeLinkPolicy::IndexToPtr (uint32 Index) inline static nodiscard
Definition at line 250 of file LockFreeList.h.
References FORCEINLINE.
Field Documentation
LinkAllocator
TAllocator FLockFreeLinkPolicy::LinkAllocator static
Definition at line 257 of file LockFreeList.h.
Referenced by DerefLink(), and IndexToLink().
The documentation for this struct was generated from the following file:
LockFreeList.h