Unreal Engine 5.6 C++ API: UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize > Struct Template Reference
UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize > Struct Template Reference
#include "Tuple.h"
Public Member Functions
TTupleBaseElement ()
TTupleBaseElement (const TTupleBaseElement &)=default
template<typename ArgType UE_REQUIRES>
TTupleBaseElement (EForwardingConstructor, ArgType &&Arg)
TTupleBaseElement (TTupleBaseElement &&)=default
TTupleBaseElement & operator= (const TTupleBaseElement &)=default
TTupleBaseElement & operator= (TTupleBaseElement &&)=default
Data Fields
T Value
Detailed Description
template<typename T, uint32 Index, uint32 TupleSize>
struct UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >
Definition at line 67 of file Tuple.h.
Constructor & Destructor Documentation
TTupleBaseElement() [1/4]
template<typename T, uint32 Index, uint32 TupleSize> template<typename ArgType UE_REQUIRES> UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::TTupleBaseElement (EForwardingConstructor , ArgType && Arg) inline explicit
Definition at line 73 of file Tuple.h.
References Forward(), and Value.
Referenced by TTupleBaseElement(), TTupleBaseElement(), operator=(), and operator=().
TTupleBaseElement() [2/4]
template<typename T, uint32 Index, uint32 TupleSize> UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::TTupleBaseElement () inline
Definition at line 78 of file Tuple.h.
References Value.
TTupleBaseElement() [3/4]
template<typename T, uint32 Index, uint32 TupleSize> UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::TTupleBaseElement (TTupleBaseElement< T, Index, TupleSize > &&) default
References TTupleBaseElement().
TTupleBaseElement() [4/4]
template<typename T, uint32 Index, uint32 TupleSize> UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::TTupleBaseElement (const TTupleBaseElement< T, Index, TupleSize > &) default
References TTupleBaseElement().
Member Function Documentation
operator=() [1/2]
template<typename T, uint32 Index, uint32 TupleSize> TTupleBaseElement & UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::operator= (const TTupleBaseElement< T, Index, TupleSize > &) default
References TTupleBaseElement().
operator=() [2/2]
template<typename T, uint32 Index, uint32 TupleSize> TTupleBaseElement & UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::operator= (TTupleBaseElement< T, Index, TupleSize > &&) default
References TTupleBaseElement().
Field Documentation
Value
template<typename T, uint32 Index, uint32 TupleSize> T UE::Core::Private::Tuple::TTupleBaseElement< T, Index, TupleSize >::Value
Definition at line 91 of file Tuple.h.
Referenced by TTupleBaseElement(), and TTupleBaseElement().
The documentation for this struct was generated from the following file:
Tuple.h