Unreal Engine 5.6 C++ API: TOctree_DEPRECATED< ElementType, OctreeSemantics > Class Template Reference
TOctree_DEPRECATED< ElementType, OctreeSemantics > Class Template Reference
An octree.
#include "GenericOctree.h"
Data Structures
struct COctreeSemanticsV2
class FNode
A node in the octree.
class FNodeReference
A reference to an octree node, its context, and a read lock.
class TConstElementBoxIterator
Iterates over the elements in the octree that intersect a bounding box.
class TConstIterator
An octree node iterator.
Public Types
typedef TInlineAllocator< 7 *(14 - 1)+8 > DefaultStackAllocator
The default iterator allocator gives the stack enough inline space to contain a path and its siblings from root to leaf.
typedef TArray< ElementType, typename OctreeSemantics::ElementAllocator > ElementArrayType
typedef ElementArrayType::TConstIterator ElementConstIt
using FReal = FVector4::FReal
Public Member Functions
TOctree_DEPRECATED ()
DO NOT USE.
TOctree_DEPRECATED (const FVector &InOrigin, FReal InExtent)
Initialization constructor.
void AddElement (typename TTypeTraits< ElementType >::ConstInitType Element)
Adds an element to the octree.
void ApplyOffset (const FVector &InOffset, bool bGlobalOctree)
Apply an arbitrary offset to all elements in the tree InOffset - offset to apply bGlobalOctree - hint that this octree is used as a boundless global volume, so only content will be shifted but not origin of the octree.
void Destroy ()
void DumpStats () const
Writes stats for the octree to the log.
ElementType & GetElementById (FOctreeElementId ElementId)
Accesses an octree element by ID.
const ElementType & GetElementById (FOctreeElementId ElementId) const
Accesses an octree element by ID.
FReal GetNodeLevelExtent (int32 Level) const
FBoxCenterAndExtent GetRootBounds () const
SIZE_T GetSizeBytes () const
bool IsValidElementId (FOctreeElementId ElementId) const
Checks if given ElementId represents a valid Octree element.
void RemoveElement (FOctreeElementId ElementId)
Removes an element from the octree.
void ShrinkElements ()
Protected Member Functions
void SetElementId (const ElementType &Element, FOctreeElementId Id)
Private Member Functions
void AddElementToNode (typename TTypeTraits< ElementType >::ConstInitType Element, const FNode &InNode, const FOctreeNodeContext &InContext)
Adds an element to a node or its children.
void SetOctreeMemoryUsage (TOctree_DEPRECATED< ElementType, OctreeSemantics > *Octree, int32 NewSize)
this function basically set TotalSizeBytes, but gives opportunity to include this Octree in memory stats
template<typename Semantics>
void SetOctreeSemanticsElementId (const ElementType &Element, FOctreeElementId Id)
Private Attributes
FReal MinLeafExtent
The extent of a leaf at the maximum allowed depth of the tree.
FNode RootNode
The octree's root node.
FOctreeNodeContext RootNodeContext
The octree's root node's context.
SIZE_T TotalSizeBytes
Detailed Description
template<typename ElementType, typename OctreeSemantics>
class TOctree_DEPRECATED< ElementType, OctreeSemantics >
An octree.
Definition at line 1081 of file GenericOctree.h.
Member Typedef Documentation
DefaultStackAllocator
template<typename ElementType, typename OctreeSemantics> typedef TInlineAllocator<7 * (14 - 1) + 8> TOctree_DEPRECATED< ElementType, OctreeSemantics >::DefaultStackAllocator
The default iterator allocator gives the stack enough inline space to contain a path and its siblings from root to leaf.
Definition at line 1216 of file GenericOctree.h.
ElementArrayType
template<typename ElementType, typename OctreeSemantics> typedef TArray<ElementType, typename OctreeSemantics::ElementAllocator> TOctree_DEPRECATED< ElementType, OctreeSemantics >::ElementArrayType
Definition at line 1086 of file GenericOctree.h.
ElementConstIt
template<typename ElementType, typename OctreeSemantics> typedef ElementArrayType::TConstIterator TOctree_DEPRECATED< ElementType, OctreeSemantics >::ElementConstIt
Definition at line 1087 of file GenericOctree.h.
FReal
template<typename ElementType, typename OctreeSemantics> using TOctree_DEPRECATED< ElementType, OctreeSemantics >::FReal = FVector4::FReal
Definition at line 1085 of file GenericOctree.h.
Constructor & Destructor Documentation
TOctree_DEPRECATED() [1/2]
template<typename ElementType, typename OctreeSemantics> TOctree_DEPRECATED< ElementType, OctreeSemantics >::TOctree_DEPRECATED (const FVector & InOrigin, FReal InExtent) inline
Initialization constructor.
Definition at line 1663 of file GenericOctree.h.
References FVector, MinLeafExtent, RootNode, RootNodeContext, and TotalSizeBytes.
Referenced by TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::TConstElementBoxIterator(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::TConstIterator(), and SetOctreeMemoryUsage().
TOctree_DEPRECATED() [2/2]
template<typename ElementType, typename OctreeSemantics> TOctree_DEPRECATED< ElementType, OctreeSemantics >::TOctree_DEPRECATED () inline
DO NOT USE.
This constructor is for internal usage only for hot-reload purposes.
Definition at line 1672 of file GenericOctree.h.
References EnsureRetrievingVTablePtrDuringCtor(), RootNode, and TEXT.
Member Function Documentation
AddElement()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElement (typename TTypeTraits< ElementType >::ConstInitType Element) inline
Adds an element to the octree.
Parameters
Element - The element to add.
Returns
An identifier for the element in the octree.
Definition at line 1414 of file GenericOctree.h.
References AddElementToNode(), RootNode, and RootNodeContext.
Referenced by ApplyOffset().
AddElementToNode()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElementToNode (typename TTypeTraits< ElementType >::ConstInitType Element, const FNode & InNode, const FOctreeNodeContext & InContext) inline private
Adds an element to a node or its children.
Definition at line 1698 of file GenericOctree.h.
References AddElementToNode(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::bIsLeaf, FBoxCenterAndExtent::Center, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Children, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Elements, Exchange(), FBoxCenterAndExtent::Extent, Fatal, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::InclusiveNumElements, FOctreeChildNodeRef::Index, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::IsLeaf(), FOctreeChildNodeRef::IsNULL(), MinLeafExtent, TArray< InElementType, InAllocatorType >::Num(), SetElementId(), SetOctreeMemoryUsage(), TEXT, TotalSizeBytes, UE_LOG, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
Referenced by AddElement(), and AddElementToNode().
ApplyOffset()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::ApplyOffset (const FVector & InOffset, bool bGlobalOctree) inline
Apply an arbitrary offset to all elements in the tree InOffset - offset to apply bGlobalOctree - hint that this octree is used as a boundless global volume, so only content will be shifted but not origin of the octree.
Definition at line 1621 of file GenericOctree.h.
References AddElement(), Destroy(), FOREACH_OCTREE_CHILD_NODE, FVector, TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::HasPendingNodes(), RootNode, and RootNodeContext.
Destroy()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::Destroy () inline
Definition at line 1505 of file GenericOctree.h.
References RootNode, and SetOctreeMemoryUsage().
Referenced by ApplyOffset().
DumpStats()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::DumpStats () const inline
Writes stats for the octree to the log.
Definition at line 1541 of file GenericOctree.h.
References TArray< InElementType, InAllocatorType >::AddZeroed(), FOREACH_OCTREE_CHILD_NODE, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::GetElementCount(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::HasChild(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::HasPendingNodes(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::IsLeaf(), Log, FMath::Max, TArray< InElementType, InAllocatorType >::Num(), TEXT, and UE_LOG.
GetElementById() [1/2]
template<typename ElementType, typename OctreeSemantics> ElementType & TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetElementById (FOctreeElementId ElementId) inline nodiscard
Accesses an octree element by ID.
Definition at line 1517 of file GenericOctree.h.
References check, FOctreeElementId::ElementIndex, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Elements, FOctreeElementId::IsValidId(), and FOctreeElementId::Node.
GetElementById() [2/2]
template<typename ElementType, typename OctreeSemantics> const ElementType & TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetElementById (FOctreeElementId ElementId) const inline nodiscard
Accesses an octree element by ID.
Definition at line 1525 of file GenericOctree.h.
References check, FOctreeElementId::ElementIndex, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Elements, FOctreeElementId::IsValidId(), and FOctreeElementId::Node.
GetNodeLevelExtent()
template<typename ElementType, typename OctreeSemantics> FReal TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetNodeLevelExtent (int32 Level) const inline nodiscard
Definition at line 1599 of file GenericOctree.h.
References FMath::Clamp(), FOctreeNodeContext::LoosenessDenominator, and RootNodeContext.
GetRootBounds()
template<typename ElementType, typename OctreeSemantics> FBoxCenterAndExtent TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetRootBounds () const inline nodiscard
Definition at line 1605 of file GenericOctree.h.
References RootNodeContext.
GetSizeBytes()
template<typename ElementType, typename OctreeSemantics> SIZE_T TOctree_DEPRECATED< ElementType, OctreeSemantics >::GetSizeBytes () const inline nodiscard
Definition at line 1594 of file GenericOctree.h.
References TotalSizeBytes.
IsValidElementId()
template<typename ElementType, typename OctreeSemantics> bool TOctree_DEPRECATED< ElementType, OctreeSemantics >::IsValidElementId (FOctreeElementId ElementId) const inline nodiscard
Checks if given ElementId represents a valid Octree element.
Definition at line 1533 of file GenericOctree.h.
References FOctreeElementId::ElementIndex, INDEX_NONE, FOctreeElementId::IsValidId(), and FOctreeElementId::Node.
RemoveElement()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::RemoveElement (FOctreeElementId ElementId) inline
Removes an element from the octree.
Parameters
ElementId - The element to remove from the octree.
Definition at line 1423 of file GenericOctree.h.
References TArray< InElementType, InAllocatorType >::Add(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::bIsLeaf, check, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Children, FOctreeElementId::ElementIndex, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Elements, FOREACH_OCTREE_CHILD_NODE, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::HasChild(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::HasPendingNodes(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::InclusiveNumElements, FOctreeElementId::IsValidId(), MoveTemp(), FOctreeElementId::Node, TArray< InElementType, InAllocatorType >::Num(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::Parent, TArray< InElementType, InAllocatorType >::RemoveAtSwap(), TArray< InElementType, InAllocatorType >::Reserve(), RootNodeContext, SetElementId(), SetOctreeMemoryUsage(), and TotalSizeBytes.
SetElementId()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::SetElementId (const ElementType & Element, FOctreeElementId Id) inline protected
Definition at line 1818 of file GenericOctree.h.
References SetOctreeSemanticsElementId().
Referenced by AddElementToNode(), and RemoveElement().
SetOctreeMemoryUsage()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::SetOctreeMemoryUsage (TOctree_DEPRECATED< ElementType, OctreeSemantics > * Octree, int32 NewSize) inline private
this function basically set TotalSizeBytes, but gives opportunity to include this Octree in memory stats
Definition at line 1690 of file GenericOctree.h.
References TOctree_DEPRECATED(), and TotalSizeBytes.
Referenced by AddElementToNode(), Destroy(), and RemoveElement().
SetOctreeSemanticsElementId()
template<typename ElementType, typename OctreeSemantics> template<typename Semantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::SetOctreeSemanticsElementId (const ElementType & Element, FOctreeElementId Id) inline private
Definition at line 1804 of file GenericOctree.h.
References TModels_V.
Referenced by SetElementId().
ShrinkElements()
template<typename ElementType, typename OctreeSemantics> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::ShrinkElements () inline
Definition at line 1610 of file GenericOctree.h.
References RootNode.
Field Documentation
MinLeafExtent
template<typename ElementType, typename OctreeSemantics> FReal TOctree_DEPRECATED< ElementType, OctreeSemantics >::MinLeafExtent private
The extent of a leaf at the maximum allowed depth of the tree.
Definition at line 1686 of file GenericOctree.h.
Referenced by TOctree_DEPRECATED(), and AddElementToNode().
RootNode
template<typename ElementType, typename OctreeSemantics> FNode TOctree_DEPRECATED< ElementType, OctreeSemantics >::RootNode private
The octree's root node.
Definition at line 1680 of file GenericOctree.h.
Referenced by TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::TConstElementBoxIterator(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::TConstIterator(), TOctree_DEPRECATED(), TOctree_DEPRECATED(), AddElement(), ApplyOffset(), Destroy(), and ShrinkElements().
RootNodeContext
template<typename ElementType, typename OctreeSemantics> FOctreeNodeContext TOctree_DEPRECATED< ElementType, OctreeSemantics >::RootNodeContext private
The octree's root node's context.
Definition at line 1683 of file GenericOctree.h.
Referenced by TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstIterator< StackAllocator >::TConstIterator(), TOctree_DEPRECATED(), AddElement(), ApplyOffset(), GetNodeLevelExtent(), GetRootBounds(), and RemoveElement().
TotalSizeBytes
template<typename ElementType, typename OctreeSemantics> SIZE_T TOctree_DEPRECATED< ElementType, OctreeSemantics >::TotalSizeBytes private
Definition at line 1695 of file GenericOctree.h.
Referenced by TOctree_DEPRECATED(), AddElementToNode(), GetSizeBytes(), RemoveElement(), and SetOctreeMemoryUsage().
The documentation for this class was generated from the following file:
GenericOctree.h