Unreal Engine 5.6 C++ API: UE::FMonotonicTimeSpan Struct Reference
UE::FMonotonicTimeSpan Struct Reference
A span of time measured in seconds between two time points.
#include "MonotonicTime.h"
Public Member Functions
constexpr FMonotonicTimeSpan ()=default
constexpr bool IsInfinity () const
bool IsNaN () const
constexpr bool IsZero () const
constexpr bool operator!= (const FMonotonicTimeSpan Other) const
constexpr FMonotonicTimeSpan operator+ () const
constexpr FMonotonicTimeSpan operator+ (const FMonotonicTimeSpan Span) const
constexpr FMonotonicTimeSpan & operator+= (const FMonotonicTimeSpan Span)
constexpr FMonotonicTimeSpan operator- () const
constexpr FMonotonicTimeSpan operator- (const FMonotonicTimeSpan Span) const
constexpr FMonotonicTimeSpan & operator-= (const FMonotonicTimeSpan Span)
constexpr bool operator< (const FMonotonicTimeSpan Other) const
constexpr bool operator<= (const FMonotonicTimeSpan Other) const
constexpr bool operator== (const FMonotonicTimeSpan Other) const
constexpr bool operator> (const FMonotonicTimeSpan Other) const
constexpr bool operator>= (const FMonotonicTimeSpan Other) const
constexpr double ToMilliseconds () const
constexpr double ToSeconds () const
Static Public Member Functions
static constexpr FMonotonicTimeSpan FromMilliseconds (double Milliseconds)
static constexpr FMonotonicTimeSpan FromSeconds (double Seconds)
static constexpr FMonotonicTimeSpan Infinity ()
static constexpr FMonotonicTimeSpan Zero ()
Private Attributes
double Time = 0
Detailed Description
A span of time measured in seconds between two time points.
See also
FMonotonicTimePoint
Definition at line 19 of file MonotonicTime.h.
Constructor & Destructor Documentation
FMonotonicTimeSpan()
UE::FMonotonicTimeSpan::FMonotonicTimeSpan () constexpr default
Referenced by FromMilliseconds(), FromSeconds(), Infinity(), operator!=(), operator+(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and Zero().
Member Function Documentation
FromMilliseconds()
constexpr FMonotonicTimeSpan UE::FMonotonicTimeSpan::FromMilliseconds (double Milliseconds) inline static constexpr
Definition at line 35 of file MonotonicTime.h.
References FMonotonicTimeSpan(), FromSeconds(), and Milliseconds.
Referenced by UE::Tasks::WaitAny().
FromSeconds()
constexpr FMonotonicTimeSpan UE::FMonotonicTimeSpan::FromSeconds (double Seconds) inline static constexpr
Definition at line 28 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Seconds, and TimeSpan.
Referenced by FromMilliseconds(), Infinity(), operator+(), UE::FMonotonicTimePoint::operator-(), operator-(), and operator-().
Infinity()
constexpr FMonotonicTimeSpan UE::FMonotonicTimeSpan::Infinity () inline static constexpr
Definition at line 26 of file MonotonicTime.h.
References FMonotonicTimeSpan(), and FromSeconds().
Referenced by IsInfinity().
IsInfinity()
bool UE::FMonotonicTimeSpan::IsInfinity () const inline constexpr
Definition at line 41 of file MonotonicTime.h.
References Infinity().
IsNaN()
bool UE::FMonotonicTimeSpan::IsNaN () const inline
Definition at line 42 of file MonotonicTime.h.
References Time.
IsZero()
bool UE::FMonotonicTimeSpan::IsZero () const inline constexpr
Definition at line 40 of file MonotonicTime.h.
References Zero().
Referenced by UE::FManualResetEvent::WaitFor().
operator!=()
bool UE::FMonotonicTimeSpan::operator!= (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 45 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
operator+() [1/2]
FMonotonicTimeSpan UE::FMonotonicTimeSpan::operator+ () const inline constexpr
Definition at line 51 of file MonotonicTime.h.
References FMonotonicTimeSpan().
operator+() [2/2]
FMonotonicTimeSpan UE::FMonotonicTimeSpan::operator+ (const FMonotonicTimeSpan Span) const inline constexpr
Definition at line 54 of file MonotonicTime.h.
References FMonotonicTimeSpan(), FromSeconds(), and Time.
operator+=()
FMonotonicTimeSpan & UE::FMonotonicTimeSpan::operator+= (const FMonotonicTimeSpan Span) inline constexpr
Definition at line 57 of file MonotonicTime.h.
References FMonotonicTimeSpan().
operator-() [1/2]
FMonotonicTimeSpan UE::FMonotonicTimeSpan::operator- () const inline constexpr
Definition at line 52 of file MonotonicTime.h.
References FMonotonicTimeSpan(), FromSeconds(), and Time.
operator-() [2/2]
FMonotonicTimeSpan UE::FMonotonicTimeSpan::operator- (const FMonotonicTimeSpan Span) const inline constexpr
Definition at line 55 of file MonotonicTime.h.
References FMonotonicTimeSpan(), FromSeconds(), and Time.
operator-=()
FMonotonicTimeSpan & UE::FMonotonicTimeSpan::operator-= (const FMonotonicTimeSpan Span) inline constexpr
Definition at line 58 of file MonotonicTime.h.
References FMonotonicTimeSpan().
operator<()
bool UE::FMonotonicTimeSpan::operator< (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 47 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
operator<=()
bool UE::FMonotonicTimeSpan::operator<= (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 46 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
operator==()
bool UE::FMonotonicTimeSpan::operator== (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 44 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
operator>()
bool UE::FMonotonicTimeSpan::operator> (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 49 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
operator>=()
bool UE::FMonotonicTimeSpan::operator>= (const FMonotonicTimeSpan Other) const inline constexpr
Definition at line 48 of file MonotonicTime.h.
References FMonotonicTimeSpan(), Other, and Time.
ToMilliseconds()
double UE::FMonotonicTimeSpan::ToMilliseconds () const inline constexpr
Definition at line 38 of file MonotonicTime.h.
References Time.
ToSeconds()
double UE::FMonotonicTimeSpan::ToSeconds () const inline constexpr
Definition at line 37 of file MonotonicTime.h.
References Time.
Referenced by UE::FMonotonicTimePoint::operator+(), and UE::FMonotonicTimePoint::operator-().
Zero()
constexpr FMonotonicTimeSpan UE::FMonotonicTimeSpan::Zero () inline static constexpr
Definition at line 24 of file MonotonicTime.h.
References FMonotonicTimeSpan().
Referenced by IsZero().
Field Documentation
Time
double UE::FMonotonicTimeSpan::Time = 0 private
Definition at line 61 of file MonotonicTime.h.
Referenced by IsNaN(), operator!=(), operator+(), operator-(), operator-(), operator<(), operator<=(), operator==(), operator>(), operator>=(), ToMilliseconds(), and ToSeconds().
The documentation for this struct was generated from the following file:
MonotonicTime.h