Unreal Engine 5.6 C++ API: TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType > Struct Template Reference
TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType > Struct Template Reference
#include "VertexFactory.h"
Static Public Member Functions
static FVertexFactoryShaderParameters * Create (const class FShaderParameterMap &ParameterMap)
static void GetElementShaderBindings (const FVertexFactoryShaderParameters *Parameters, const class FSceneInterface *Scene, const class FSceneView *View, const class FMeshMaterialShader *Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory *VertexFactory, const struct FMeshBatchElement &BatchElement, class FMeshDrawSingleShaderBindings &ShaderBindings, FVertexInputStreamArray &VertexStreams)
static const FTypeLayoutDesc * GetLayout ()
Detailed Description
template<EShaderFrequency ShaderFrequency, typename VertexFactoryType>
struct TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >
Definition at line 198 of file VertexFactory.h.
Member Function Documentation
Create()
template<EShaderFrequency ShaderFrequency, typename VertexFactoryType> FVertexFactoryShaderParameters * TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::Create (const class FShaderParameterMap & ParameterMap) inline static
Definition at line 201 of file VertexFactory.h.
Referenced by ConstructVertexFactoryParameters().
GetElementShaderBindings()
template<EShaderFrequency ShaderFrequency, typename VertexFactoryType> void TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::GetElementShaderBindings (const FVertexFactoryShaderParameters * Parameters, const class FSceneInterface * Scene, const class FSceneView * View, const class FMeshMaterialShader * Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory * VertexFactory, const struct FMeshBatchElement & BatchElement, class FMeshDrawSingleShaderBindings & ShaderBindings, FVertexInputStreamArray & VertexStreams) inline static
Definition at line 203 of file VertexFactory.h.
References Scene, and VertexFactory.
Referenced by GetVertexFactoryParametersElementShaderBindings().
GetLayout()
template<EShaderFrequency ShaderFrequency, typename VertexFactoryType> const FTypeLayoutDesc * TVertexFactoryParameterTraits< ShaderFrequency, VertexFactoryType >::GetLayout () inline static
Definition at line 200 of file VertexFactory.h.
Referenced by GetVertexFactoryParametersLayout().
The documentation for this struct was generated from the following file:
VertexFactory.h