Unreal Engine 5.6 C++ API: TMaybeMappedAllocator< Alignment >::ForAnyElementType Class Reference
TMaybeMappedAllocator< Alignment >::ForAnyElementType Class Reference
#include "AnimCompressionTypes.h"
Public Member Functions
ForAnyElementType ()
Default constructor.
~ForAnyElementType ()
Destructor.
void AcceptFileMapping (IMappedFileHandle *InMappedHandle, IMappedFileRegion *InMappedRegion, void *MallocPtr)
SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FScriptContainerElement * GetAllocation () const
SizeType GetInitialCapacity () const
bool HasAllocation () const
bool IsMapped () const
void MoveToEmpty (ForAnyElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
Private Member Functions
ForAnyElementType (const ForAnyElementType &)
ForAnyElementType & operator= (const ForAnyElementType &)
void Reset ()
Private Attributes
FScriptContainerElement * Data
IMappedFileHandle * MappedHandle
IMappedFileRegion * MappedRegion
Detailed Description
template<uint32 Alignment = DEFAULT_ALIGNMENT>
class TMaybeMappedAllocator< Alignment >::ForAnyElementType
Definition at line 544 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
ForAnyElementType() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> TMaybeMappedAllocator< Alignment >::ForAnyElementType::ForAnyElementType () inline
Default constructor.
Definition at line 549 of file AnimCompressionTypes.h.
References Data, MappedHandle, and MappedRegion.
Referenced by ForAnyElementType(), MoveToEmpty(), and operator=().
~ForAnyElementType()
template<uint32 Alignment = DEFAULT_ALIGNMENT> TMaybeMappedAllocator< Alignment >::ForAnyElementType::~ForAnyElementType () inline
Destructor.
Definition at line 577 of file AnimCompressionTypes.h.
References Reset().
ForAnyElementType() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> TMaybeMappedAllocator< Alignment >::ForAnyElementType::ForAnyElementType (const ForAnyElementType &) private
References ForAnyElementType().
Member Function Documentation
AcceptFileMapping()
template<uint32 Alignment = DEFAULT_ALIGNMENT> void TMaybeMappedAllocator< Alignment >::ForAnyElementType::AcceptFileMapping (IMappedFileHandle * InMappedHandle, IMappedFileRegion * InMappedRegion, void * MallocPtr) inline
Definition at line 649 of file AnimCompressionTypes.h.
References check, Data, IsAligned(), MappedHandle, MappedRegion, and Reset().
CalculateSlackGrow()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SizeType TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 628 of file AnimCompressionTypes.h.
References check, DefaultCalculateSlackGrow(), MappedHandle, and MappedRegion.
CalculateSlackReserve()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SizeType TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 618 of file AnimCompressionTypes.h.
References check, DefaultCalculateSlackReserve(), MappedHandle, and MappedRegion.
CalculateSlackShrink()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SizeType TMaybeMappedAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 623 of file AnimCompressionTypes.h.
References check, DefaultCalculateSlackShrink(), MappedHandle, and MappedRegion.
GetAllocatedSize()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SIZE_T TMaybeMappedAllocator< Alignment >::ForAnyElementType::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 634 of file AnimCompressionTypes.h.
GetAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FScriptContainerElement * TMaybeMappedAllocator< Alignment >::ForAnyElementType::GetAllocation () const inline
Definition at line 583 of file AnimCompressionTypes.h.
References Data.
Referenced by TMaybeMappedAllocator< Alignment >::ForElementType< ElementType >::GetAllocation().
GetInitialCapacity()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SizeType TMaybeMappedAllocator< Alignment >::ForAnyElementType::GetInitialCapacity () const inline
Definition at line 644 of file AnimCompressionTypes.h.
HasAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> bool TMaybeMappedAllocator< Alignment >::ForAnyElementType::HasAllocation () const inline
Definition at line 639 of file AnimCompressionTypes.h.
References Data.
IsMapped()
template<uint32 Alignment = DEFAULT_ALIGNMENT> bool TMaybeMappedAllocator< Alignment >::ForAnyElementType::IsMapped () const inline
Definition at line 666 of file AnimCompressionTypes.h.
References MappedHandle, and MappedRegion.
MoveToEmpty()
template<uint32 Alignment = DEFAULT_ALIGNMENT> void TMaybeMappedAllocator< Alignment >::ForAnyElementType::MoveToEmpty (ForAnyElementType & Other) inline
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 560 of file AnimCompressionTypes.h.
References ForAnyElementType(), checkSlow, Data, MappedHandle, MappedRegion, Other, and Reset().
operator=()
template<uint32 Alignment = DEFAULT_ALIGNMENT> ForAnyElementType & TMaybeMappedAllocator< Alignment >::ForAnyElementType::operator= (const ForAnyElementType &) private
References ForAnyElementType().
Reset()
template<uint32 Alignment = DEFAULT_ALIGNMENT> void TMaybeMappedAllocator< Alignment >::ForAnyElementType::Reset () inline private
Definition at line 676 of file AnimCompressionTypes.h.
References Data, FMemory::Free(), MappedHandle, and MappedRegion.
Referenced by ~ForAnyElementType(), AcceptFileMapping(), and MoveToEmpty().
ResizeAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> template FORCENOINLINE void TMaybeMappedAllocator< Alignment >::ForAnyElementType::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 587 of file AnimCompressionTypes.h.
References check, Data, MappedHandle, MappedRegion, MAX_int32, UE::Animation::Private::OnInvalidMaybeMappedAllocatorNum(), and UNLIKELY.
Field Documentation
Data
template<uint32 Alignment = DEFAULT_ALIGNMENT> FScriptContainerElement* TMaybeMappedAllocator< Alignment >::ForAnyElementType::Data private
Definition at line 672 of file AnimCompressionTypes.h.
Referenced by ForAnyElementType(), AcceptFileMapping(), GetAllocation(), HasAllocation(), MoveToEmpty(), Reset(), and ResizeAllocation().
MappedHandle
template<uint32 Alignment = DEFAULT_ALIGNMENT> IMappedFileHandle* TMaybeMappedAllocator< Alignment >::ForAnyElementType::MappedHandle private
Definition at line 673 of file AnimCompressionTypes.h.
Referenced by ForAnyElementType(), AcceptFileMapping(), CalculateSlackGrow(), CalculateSlackReserve(), CalculateSlackShrink(), IsMapped(), MoveToEmpty(), Reset(), and ResizeAllocation().
MappedRegion
template<uint32 Alignment = DEFAULT_ALIGNMENT> IMappedFileRegion* TMaybeMappedAllocator< Alignment >::ForAnyElementType::MappedRegion private
Definition at line 674 of file AnimCompressionTypes.h.
Referenced by ForAnyElementType(), AcceptFileMapping(), CalculateSlackGrow(), CalculateSlackReserve(), CalculateSlackShrink(), IsMapped(), MoveToEmpty(), Reset(), and ResizeAllocation().
The documentation for this class was generated from the following file:
AnimCompressionTypes.h