Unreal Engine 5.6 C++ API: FTagMetaData Class Reference
FTagMetaData Class Reference
Simple tagging metadata.
#include "ISlateMetaData.h"
Public Member Functions
FTagMetaData (FName InTag)
virtual bool IsOfTypeImpl (const FName &Type) const override
Checks whether this drag and drop operation can cast safely to the specified type.
Public Member Functions inherited from ISlateMetaData
virtual ~ISlateMetaData ()
Virtual destructor.
template<class TType>
bool IsOfType () const
Check if this metadata operation can cast safely to the specified template type.
Static Public Member Functions
static const FName & GetTypeId ()
Data Fields
FName Tag
Tag name for a widget.
Detailed Description
Simple tagging metadata.
Definition at line 50 of file ISlateMetaData.h.
Constructor & Destructor Documentation
FTagMetaData()
FTagMetaData::FTagMetaData (FName InTag) inline
Definition at line 55 of file ISlateMetaData.h.
References FTagMetaData(), and Tag.
Referenced by FTagMetaData(), and GetTypeId().
Member Function Documentation
GetTypeId()
const FName & FTagMetaData::GetTypeId () inline static
Definition at line 53 of file ISlateMetaData.h.
References FTagMetaData().
IsOfTypeImpl()
virtual bool FTagMetaData::IsOfTypeImpl (const FName & Type) const inline override virtual
Checks whether this drag and drop operation can cast safely to the specified type.
Reimplemented from ISlateMetaData.
Definition at line 53 of file ISlateMetaData.h.
Field Documentation
Tag
FName FTagMetaData::Tag
Tag name for a widget.
Definition at line 60 of file ISlateMetaData.h.
Referenced by FTagMetaData().
The documentation for this class was generated from the following file:
ISlateMetaData.h