Unreal Engine 5.6 C++ API: UE::Geometry::FElementLinearization Class Reference
UE::Geometry::FElementLinearization Class Reference
FElementLinearization maps a potentially-sparse index list into a linear array.
#include "ElementLinearization.h"
Public Member Functions
FElementLinearization ()=default
void Empty ()
int32 GetId (int32 Index) const
int32 GetIndex (int32 Id) const
bool IsValidId (int32 Id) const
bool IsValidIndex (int32 Index) const
int32 MaxId () const
int32 NumIds () const
int32 NumIndices () const
template<typename IterableType>
void Populate (const int32 MaxId, const int32 Count, IterableType Iterable)
const TArray< int32 > & ToId () const
const TArray< int32 > & ToIndex () const
Protected Attributes
TArray< int32 > ToIdMap
TArray< int32 > ToIndexMap
Private Member Functions
FElementLinearization (const FElementLinearization &)
Detailed Description
FElementLinearization maps a potentially-sparse index list into a linear array.
Used linearize things like VtxIds of a mesh as a single array and allow bidirectional mapping between array offset and mesh VtxId. Linearized array offset can then be used for things like matrix row indexing when building a Laplacian matrix.
Definition at line 21 of file ElementLinearization.h.
Constructor & Destructor Documentation
FElementLinearization() [1/2]
UE::Geometry::FElementLinearization::FElementLinearization () default
Referenced by FElementLinearization().
FElementLinearization() [2/2]
UE::Geometry::FElementLinearization::FElementLinearization (const FElementLinearization &) private
References FElementLinearization().
Member Function Documentation
Empty()
void UE::Geometry::FElementLinearization::Empty () inline
Definition at line 67 of file ElementLinearization.h.
References ToIdMap, and ToIndexMap.
Referenced by UE::Geometry::FTriangleLinearization::Reset(), and UE::Geometry::FVertexLinearization::Reset().
GetId()
int32 UE::Geometry::FElementLinearization::GetId (int32 Index) const inline
Returns
Id for given Index
Definition at line 61 of file ElementLinearization.h.
References checkSlow, IsValidIndex(), and ToIdMap.
GetIndex()
int32 UE::Geometry::FElementLinearization::GetIndex (int32 Id) const inline
Returns
Index for given Id
Definition at line 54 of file ElementLinearization.h.
References checkSlow, IsValidId(), and ToIndexMap.
IsValidId()
bool UE::Geometry::FElementLinearization::IsValidId (int32 Id) const inline
Returns
true if Id is in valid range and maps to a valid index
Definition at line 42 of file ElementLinearization.h.
References ToIndexMap.
Referenced by GetIndex().
IsValidIndex()
bool UE::Geometry::FElementLinearization::IsValidIndex (int32 Index) const inline
Returns
true if Index is in valid range
Definition at line 48 of file ElementLinearization.h.
References ToIdMap.
Referenced by GetId().
MaxId()
int32 UE::Geometry::FElementLinearization::MaxId () const inline
Definition at line 36 of file ElementLinearization.h.
References ToIndexMap.
Referenced by Populate().
NumIds()
int32 UE::Geometry::FElementLinearization::NumIds () const inline
Returns
maximum number of IDs in linearization (However not all IDs necessarily have a linear index)
Definition at line 33 of file ElementLinearization.h.
References ToIdMap.
Referenced by UE::Geometry::FTriangleLinearization::NumTris(), and UE::Geometry::FVertexLinearization::NumVerts().
NumIndices()
int32 UE::Geometry::FElementLinearization::NumIndices () const inline
Returns
number of Indices in linearization
Definition at line 39 of file ElementLinearization.h.
References ToIdMap.
Populate()
template<typename IterableType> void UE::Geometry::FElementLinearization::Populate (const int32 MaxId, const int32 Count, IterableType Iterable) inline
Definition at line 70 of file ElementLinearization.h.
References UE::Count, IndexConstants::InvalidID, MaxId(), ToIdMap, and ToIndexMap.
Referenced by UE::Geometry::FTriangleLinearization::Reset(), and UE::Geometry::FVertexLinearization::Reset().
ToId()
const TArray< int32 > & UE::Geometry::FElementLinearization::ToId () const inline
Definition at line 27 of file ElementLinearization.h.
References ToIdMap.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), and UE::MeshDeformation::ConstructValenceWeightedLaplacian().
ToIndex()
const TArray< int32 > & UE::Geometry::FElementLinearization::ToIndex () const inline
Definition at line 30 of file ElementLinearization.h.
References ToIndexMap.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), and UE::MeshDeformation::ConstructValenceWeightedLaplacian().
Field Documentation
ToIdMap
TArray<int32> UE::Geometry::FElementLinearization::ToIdMap protected
Definition at line 93 of file ElementLinearization.h.
Referenced by Empty(), GetId(), IsValidIndex(), NumIds(), NumIndices(), Populate(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), and ToId().
ToIndexMap
TArray<int32> UE::Geometry::FElementLinearization::ToIndexMap protected
Definition at line 94 of file ElementLinearization.h.
Referenced by Empty(), GetIndex(), IsValidId(), MaxId(), Populate(), UE::Geometry::FVertexLinearization::RemapBoundaryVerts(), and ToIndex().
The documentation for this class was generated from the following file:
ElementLinearization.h