Unreal Engine 5.6 C++ API: TextureResource.h File Reference
TextureResource.h File Reference
#include "CoreMinimal.h"
#include "HAL/ThreadSafeCounter.h"
#include "Containers/IndirectArray.h"
#include "Stats/Stats.h"
#include "Containers/List.h"
#include "Async/AsyncWork.h"
#include "Async/AsyncFileHandle.h"
#include "RHI.h"
#include "RenderResource.h"
#include "Serialization/BulkData.h"
#include "Serialization/DerivedData.h"
#include "Engine/TextureDefines.h"
#include "UnrealClient.h"
#include "Templates/UniquePtr.h"
#include "VirtualTexturing.h"
Data Structures
class FDeferredUpdateResource
FDeferredUpdateResource for resources that need to be updated after scene rendering has begun (should only be used on the rendering thread)
class FTexture2DDynamicResource
A dynamic 2D texture resource.
struct FTexture2DMipMap
A 2D texture mip-map.
class FTextureRenderTarget2DResource
FTextureResource type for 2D render target textures.
class FTextureRenderTargetCubeResource
FTextureResource type for cube render target textures.
class FTextureRenderTargetResource
FTextureResource type for render target textures.
class FTextureResource
The rendering resource which represents a texture.
class FVirtualTexture2DResource
Macros
#define MAX_TEXTURE_SOURCE_SLICES 6
Maximum number of slices in texture source art.
Functions
void GetAllDefaultTextureFormats (const class ITargetPlatform *TargetPlatform, TArray< FName > &OutFormats)
void GetAllDefaultTextureFormats (const class ITargetPlatformSettings *TargetPlatformSettings, TArray< FName > &OutFormats)
FName GetDefaultTextureFormatName (const class ITargetPlatform *TargetPlatform, const class UTexture *Texture, int32 LayerIndex, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
Do not call these (GetDefaultTextureFormatName) directly, use GetPlatformTextureFormatNamesWithPrefix instead this should only be called by TargetPlatform::GetTextureFormats()
FName GetDefaultTextureFormatName (const class ITargetPlatformSettings *TargetPlatformSettings, const class ITargetPlatformControls *TargetPlatformControls, const class UTexture *Texture, int32 LayerIndex, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
void GetDefaultTextureFormatNamePerLayer (TArray< FName > &OutFormatNames, const class ITargetPlatform *TargetPlatform, const class UTexture *Texture, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
Gets an array of format names for each layer in the texture.
void GetDefaultTextureFormatNamePerLayer (TArray< FName > &OutFormatNames, const class ITargetPlatformSettings *TargetPlatformSettings, const class ITargetPlatformControls *TargetPlatformControls, const class UTexture *Texture, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
Macro Definition Documentation
MAX_TEXTURE_SOURCE_SLICES
#define MAX_TEXTURE_SOURCE_SLICES 6
Maximum number of slices in texture source art.
Definition at line 40 of file TextureResource.h.
Function Documentation
GetAllDefaultTextureFormats() [1/2]
void GetAllDefaultTextureFormats (const class ITargetPlatform * TargetPlatform, TArray< FName > & OutFormats)
References GetAllDefaultTextureFormats().
Referenced by GetAllDefaultTextureFormats(), and GetAllDefaultTextureFormats().
GetAllDefaultTextureFormats() [2/2]
void GetAllDefaultTextureFormats (const class ITargetPlatformSettings * TargetPlatformSettings, TArray< FName > & OutFormats)
References GetAllDefaultTextureFormats().
GetDefaultTextureFormatName() [1/2]
FName GetDefaultTextureFormatName (const class ITargetPlatform * TargetPlatform, const class UTexture * Texture, int32 LayerIndex, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
Do not call these (GetDefaultTextureFormatName) directly, use GetPlatformTextureFormatNamesWithPrefix instead this should only be called by TargetPlatform::GetTextureFormats()
Gets the name of a format for the given LayerIndex
References GetDefaultTextureFormatName(), and Texture.
Referenced by GetDefaultTextureFormatName(), and GetDefaultTextureFormatName().
GetDefaultTextureFormatName() [2/2]
FName GetDefaultTextureFormatName (const class ITargetPlatformSettings * TargetPlatformSettings, const class ITargetPlatformControls * TargetPlatformControls, const class UTexture * Texture, int32 LayerIndex, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
References GetDefaultTextureFormatName(), and Texture.
GetDefaultTextureFormatNamePerLayer() [1/2]
void GetDefaultTextureFormatNamePerLayer (TArray< FName > & OutFormatNames, const class ITargetPlatform * TargetPlatform, const class UTexture * Texture, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
Gets an array of format names for each layer in the texture.
References GetDefaultTextureFormatNamePerLayer(), and Texture.
Referenced by GetDefaultTextureFormatNamePerLayer(), and GetDefaultTextureFormatNamePerLayer().
GetDefaultTextureFormatNamePerLayer() [2/2]
void GetDefaultTextureFormatNamePerLayer (TArray< FName > & OutFormatNames, const class ITargetPlatformSettings * TargetPlatformSettings, const class ITargetPlatformControls * TargetPlatformControls, const class UTexture * Texture, bool bSupportCompressedVolumeTexture, int32 Unused_BlockSize, bool bSupportFilteredFloat32Textures)
References GetDefaultTextureFormatNamePerLayer(), and Texture.