Unreal Engine 5.6 C++ API: FRigVMTreeElement Class Reference
FRigVMTreeElement Class Reference
The Tree Element is the base class for anything within a tree and manages the lifetime as well as type checking.
#include "RigVMTreeToolkitDefines.h"
Public Member Functions
virtual ~FRigVMTreeElement ()
virtual FName GetType () const
virtual void Initialize ()
template<typename T>
bool IsA () const
virtual bool IsOfType (const FName &InType) const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Protected Member Functions
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The Tree Element is the base class for anything within a tree and manages the lifetime as well as type checking.
Definition at line 59 of file RigVMTreeToolkitDefines.h.
Constructor & Destructor Documentation
~FRigVMTreeElement()
virtual FRigVMTreeElement::~FRigVMTreeElement () inline virtual
Definition at line 79 of file RigVMTreeToolkitDefines.h.
FRigVMTreeElement()
FRigVMTreeElement::FRigVMTreeElement () inline protected
Definition at line 88 of file RigVMTreeToolkitDefines.h.
Referenced by FRigVMTreeContext::Cast, FRigVMTreeFilter::Cast, FRigVMTreeNode::Cast, FRigVMTreePhase::Cast, and FRigVMTreeTask::Cast.
Member Function Documentation
GetType()
virtual FName FRigVMTreeElement::GetType () const inline virtual
Reimplemented in FRigVMCompileBlueprintTask, FRigVMTreeCategoryNode, FRigVMTreeContext, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFilter, FRigVMTreeLoadPackageForNodeTask, FRigVMTreeNode, FRigVMTreePackageNode, FRigVMTreePathFilter, FRigVMTreePhase, FRigVMTreeRootNode, and FRigVMTreeTask.
Definition at line 63 of file RigVMTreeToolkitDefines.h.
References Type.
Initialize()
virtual void FRigVMTreeElement::Initialize () inline virtual
Reimplemented in FRigVMTreePackageNode.
Definition at line 83 of file RigVMTreeToolkitDefines.h.
IsA()
template<typename T> bool FRigVMTreeElement::IsA () const inline
Definition at line 74 of file RigVMTreeToolkitDefines.h.
References IsOfType().
IsOfType()
virtual bool FRigVMTreeElement::IsOfType (const FName & InType) const inline virtual
Reimplemented in FRigVMCompileBlueprintTask, FRigVMTreeCategoryNode, FRigVMTreeContext, FRigVMTreeDeveloperContentFilter, FRigVMTreeEngineContentFilter, FRigVMTreeFilter, FRigVMTreeLoadPackageForNodeTask, FRigVMTreeNode, FRigVMTreePackageNode, FRigVMTreePathFilter, FRigVMTreePhase, FRigVMTreeRootNode, and FRigVMTreeTask.
Definition at line 68 of file RigVMTreeToolkitDefines.h.
References Type.
Referenced by IsA().
Field Documentation
Type
const FLazyName FRigVMTreeElement::Type = FLazyName(TEXT("FRigVMTreeElement")) inline static
Definition at line 62 of file RigVMTreeToolkitDefines.h.
Referenced by GetType(), and IsOfType().
The documentation for this class was generated from the following file:
RigVMTreeToolkitDefines.h