Unreal Engine 5.6 C++ API: FRigVMRegistry_RWLock::FConditionalWriteScopeLock Class Reference
FRigVMRegistry_RWLock::FConditionalWriteScopeLock Class Reference
#include "RigVMRegistry.h"
Public Member Functions
UE_NODISCARD_CTOR FConditionalWriteScopeLock (bool bInLockEnabled=true)
UE_NODISCARD_CTOR FConditionalWriteScopeLock (const FRigVMRegistry_RWLock &InRegistry, bool bInLockEnabled=true)
Public Member Functions inherited from FRigVMRegistry_RWLock::FConditionalScopeLock
UE_NODISCARD_CTOR FConditionalScopeLock (const FRigVMRegistry_RWLock &InRegistry, ELockType InLockType, bool bInLockEnabled=true)
~FConditionalScopeLock ()
FRigVMRegistry_NoLock & GetRegistry ()
const FRigVMRegistry_NoLock & GetRegistry () const
Detailed Description
Definition at line 546 of file RigVMRegistry.h.
Constructor & Destructor Documentation
FConditionalWriteScopeLock() [1/2]
UE_NODISCARD_CTOR FRigVMRegistry_RWLock::FConditionalWriteScopeLock::FConditionalWriteScopeLock (const FRigVMRegistry_RWLock & InRegistry, bool bInLockEnabled = true) inline explicit
Definition at line 549 of file RigVMRegistry.h.
References FRigVMRegistry_RWLock::FConditionalScopeLock::FConditionalScopeLock(), FRigVMRegistry_RWLock::FRigVMRegistry_RWLock(), FRigVMRegistry_NoLock::LockType_Write, and UE_NODISCARD_CTOR.
Referenced by FConditionalWriteScopeLock().
FConditionalWriteScopeLock() [2/2]
UE_NODISCARD_CTOR FRigVMRegistry_RWLock::FConditionalWriteScopeLock::FConditionalWriteScopeLock (bool bInLockEnabled = true) inline explicit
Definition at line 554 of file RigVMRegistry.h.
References FConditionalWriteScopeLock(), FRigVMRegistry_RWLock::FRigVMRegistry_RWLock(), FRigVMRegistry_RWLock::Get(), and UE_NODISCARD_CTOR.
The documentation for this class was generated from the following file:
RigVMRegistry.h