Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicMeshChangeTracker Class Reference
UE::Geometry::FDynamicMeshChangeTracker Class Reference
FDynamicMeshChangeTracker tracks changes to a FDynamicMesh and returns a FDynamicMeshChange instance that represents this change and allows it to be reverted/reapplied.
#include "DynamicMeshChangeTracker.h"
Public Member Functions
GEOMETRYCORE_API FDynamicMeshChangeTracker (const FDynamicMesh3 *Mesh)
GEOMETRYCORE_API ~FDynamicMeshChangeTracker ()
GEOMETRYCORE_API void BeginChange ()
Initialize the change-tracking process.
GEOMETRYCORE_API TUniquePtr< FDynamicMeshChange > EndChange ()
Construct a change object that represents the delta between the Begin and End states.
void SaveEdge (int32 EdgeID, bool bVertices)
Save necessary information about an edge before it is modified.
GEOMETRYCORE_API void SaveTriangle (int32 TriangleID, bool bSaveVertices)
Save necessary information about a triangle before it is modified.
template<typename EnumerableType>
void SaveTriangles (EnumerableType TriangleIDs, bool bSaveVertices)
Save necessary information about a set of triangles before they are modified.
template<typename EnumerableType>
void SaveTrianglesAndNeighbourTris (EnumerableType TriangleIDs, bool bSaveVertices)
Save necessary information about a set of triangles before they are modified, and also include any direct triangle neighbours.
template<typename EnumerableType>
void SaveVertexOneRingTriangles (EnumerableType VertexIDs, bool bSaveVertices)
Save necessary information about a set of triangles in one-rings of a set of vertices.
void SaveVertexOneRingTriangles (int32 VertexID, bool bSaveVertices)
Save necessary information about a set of triangles in one-ring of a vertex.
GEOMETRYCORE_API void VerifySaveState ()
Do (limited) sanity checking to make sure that the change is well-formed.
Protected Member Functions
GEOMETRYCORE_API void SaveVertex (int32 VertexID)
Save necessary information about a vertex before it is modified.
template<typename EnumerableType>
void SaveVertices (EnumerableType VertexIDs)
Save necessary information about a set of vertices before they are modified.
Protected Attributes
FDynamicMeshAttributeSetChangeTracker * AttribChangeTracker = nullptr
Active attribute tracker, if Mesh has attribute overlays.
FDynamicMeshChange * Change = nullptr
Active change that is being constructed.
TBitArray ChangedTriangles
TBitArray ChangedVertices
int32 MaxTriangleID
int32 MaxVertexID
const FDynamicMesh3 * Mesh = nullptr
TBitArray StartTriangles
TBitArray StartVertices
Detailed Description
FDynamicMeshChangeTracker tracks changes to a FDynamicMesh and returns a FDynamicMeshChange instance that represents this change and allows it to be reverted/reapplied.
This is the top-level class you likely want to use to track mesh changes.
Call BeginChange() before making any changes to the mesh, then call SaveVertex() and SaveTriangle() before modifying the respective elements. Then call EndChange() to construct a FDynamicMeshChange that represents the mesh delta.
Warning
Currently only vertices that are part of saved triangles will be stored in the emitted FMeshChange!
Definition at line 295 of file DynamicMeshChangeTracker.h.
Constructor & Destructor Documentation
FDynamicMeshChangeTracker()
GEOMETRYCORE_API UE::Geometry::FDynamicMeshChangeTracker::FDynamicMeshChangeTracker (const FDynamicMesh3 * Mesh) explicit
References Mesh.
~FDynamicMeshChangeTracker()
GEOMETRYCORE_API UE::Geometry::FDynamicMeshChangeTracker::~FDynamicMeshChangeTracker ()
Member Function Documentation
BeginChange()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshChangeTracker::BeginChange ()
Initialize the change-tracking process.
EndChange()
GEOMETRYCORE_API TUniquePtr< FDynamicMeshChange > UE::Geometry::FDynamicMeshChangeTracker::EndChange ()
Construct a change object that represents the delta between the Begin and End states.
SaveEdge()
void UE::Geometry::FDynamicMeshChangeTracker::SaveEdge (int32 EdgeID, bool bVertices) inline
Save necessary information about an edge before it is modified.
Definition at line 366 of file DynamicMeshChangeTracker.h.
References UE::Geometry::Edge, UE::Geometry::FDynamicMesh3::InvalidID, Mesh, and SaveTriangle().
SaveTriangle()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshChangeTracker::SaveTriangle (int32 TriangleID, bool bSaveVertices)
Save necessary information about a triangle before it is modified.
Referenced by UE::Geometry::FSubRegionRemesher::SaveActiveROI(), SaveEdge(), SaveTriangles(), SaveTrianglesAndNeighbourTris(), and SaveVertexOneRingTriangles().
SaveTriangles()
template<typename EnumerableType> void UE::Geometry::FDynamicMeshChangeTracker::SaveTriangles (EnumerableType TriangleIDs, bool bSaveVertices)
Save necessary information about a set of triangles before they are modified.
Definition at line 386 of file DynamicMeshChangeTracker.h.
References SaveTriangle().
SaveTrianglesAndNeighbourTris()
template<typename EnumerableType> void UE::Geometry::FDynamicMeshChangeTracker::SaveTrianglesAndNeighbourTris (EnumerableType TriangleIDs, bool bSaveVertices)
Save necessary information about a set of triangles before they are modified, and also include any direct triangle neighbours.
Definition at line 396 of file DynamicMeshChangeTracker.h.
References UE::Geometry::FDynamicMesh3::InvalidID, Mesh, and SaveTriangle().
SaveVertex()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshChangeTracker::SaveVertex (int32 VertexID) protected
Save necessary information about a vertex before it is modified.
Referenced by SaveVertices().
SaveVertexOneRingTriangles() [1/2]
template<typename EnumerableType> void UE::Geometry::FDynamicMeshChangeTracker::SaveVertexOneRingTriangles (EnumerableType VertexIDs, bool bSaveVertices)
Save necessary information about a set of triangles in one-rings of a set of vertices.
Definition at line 423 of file DynamicMeshChangeTracker.h.
References SaveVertexOneRingTriangles().
SaveVertexOneRingTriangles() [2/2]
void UE::Geometry::FDynamicMeshChangeTracker::SaveVertexOneRingTriangles (int32 VertexID, bool bSaveVertices) inline
Save necessary information about a set of triangles in one-ring of a vertex.
Definition at line 414 of file DynamicMeshChangeTracker.h.
References Mesh, and SaveTriangle().
Referenced by SaveVertexOneRingTriangles().
SaveVertices()
template<typename EnumerableType> void UE::Geometry::FDynamicMeshChangeTracker::SaveVertices (EnumerableType VertexIDs) protected
Save necessary information about a set of vertices before they are modified.
Definition at line 377 of file DynamicMeshChangeTracker.h.
References SaveVertex().
VerifySaveState()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshChangeTracker::VerifySaveState ()
Do (limited) sanity checking to make sure that the change is well-formed.
Field Documentation
AttribChangeTracker
FDynamicMeshAttributeSetChangeTracker* UE::Geometry::FDynamicMeshChangeTracker::AttribChangeTracker = nullptr protected
Active attribute tracker, if Mesh has attribute overlays.
Definition at line 350 of file DynamicMeshChangeTracker.h.
Change
FDynamicMeshChange* UE::Geometry::FDynamicMeshChangeTracker::Change = nullptr protected
Active change that is being constructed.
Definition at line 353 of file DynamicMeshChangeTracker.h.
ChangedTriangles
TBitArray UE::Geometry::FDynamicMeshChangeTracker::ChangedTriangles protected
Definition at line 357 of file DynamicMeshChangeTracker.h.
ChangedVertices
TBitArray UE::Geometry::FDynamicMeshChangeTracker::ChangedVertices protected
Definition at line 361 of file DynamicMeshChangeTracker.h.
MaxTriangleID
int32 UE::Geometry::FDynamicMeshChangeTracker::MaxTriangleID protected
Definition at line 355 of file DynamicMeshChangeTracker.h.
MaxVertexID
int32 UE::Geometry::FDynamicMeshChangeTracker::MaxVertexID protected
Definition at line 359 of file DynamicMeshChangeTracker.h.
Mesh
const FDynamicMesh3* UE::Geometry::FDynamicMeshChangeTracker::Mesh = nullptr protected
Definition at line 347 of file DynamicMeshChangeTracker.h.
Referenced by FDynamicMeshChangeTracker(), SaveEdge(), SaveTrianglesAndNeighbourTris(), and SaveVertexOneRingTriangles().
StartTriangles
TBitArray UE::Geometry::FDynamicMeshChangeTracker::StartTriangles protected
Definition at line 356 of file DynamicMeshChangeTracker.h.
StartVertices
TBitArray UE::Geometry::FDynamicMeshChangeTracker::StartVertices protected
Definition at line 360 of file DynamicMeshChangeTracker.h.
The documentation for this class was generated from the following file:
DynamicMeshChangeTracker.h