Unreal Engine 5.6 C++ API: FConfigValue Struct Reference
FConfigValue Struct Reference
#include "ConfigCacheIni.h"
Public Types
enum class EValueType : uint8 {
Set , ArrayAdd , ArrayAddUnique , Remove ,
Clear , InitializeToEmpty , ArrayOfStructKey , POCArrayOfStructKey ,
Combined , ArrayCombined
}
Public Member Functions
FConfigValue ()
FConfigValue (const FConfigSection *InSection, FName InValueName, const FString &InValue, EValueType Type=EValueType::Combined)
FConfigValue (const FConfigSection *InSection, FName InValueName, const TCHAR *InValue, EValueType Type=EValueType::Combined)
FConfigValue (const FConfigSection *InSection, FName InValueName, EValueType Type=EValueType::Combined)
FConfigValue (const FConfigSection *InSection, FName InValueName, FString &&InValue, EValueType Type=EValueType::Combined)
FConfigValue (const FConfigValue &InConfigValue)
FConfigValue (const FString &InValue, EValueType Type=EValueType::Combined)
FConfigValue (const TCHAR *InValue, EValueType Type=EValueType::Combined)
FConfigValue (FConfigValue &&InConfigValue)
FConfigValue (FString &&InValue, EValueType Type=EValueType::Combined)
const FString & GetSavedValue () const
const FString & GetSavedValueForWriting () const
FORCEINLINE FString GetValue () const
FORCEINLINE FString GetValueForWriting () const
Gets the expanded value (GetValue) without marking it as having been accessed for e.g.
bool operator!= (const FConfigValue &Other) const
FConfigValue & operator= (const FConfigValue &RHS)
FConfigValue & operator= (const FString &RHS)
FConfigValue & operator= (const TCHAR *RHS)
FConfigValue & operator= (FConfigValue &&RHS)
FConfigValue & operator= (FString &&RHS)
bool operator== (const FConfigValue &Other) const
Static Public Member Functions
static FString CollapseValue (const FString &InExpandedValue)
Given an expanded config value, try and produce a collapsed version of it (adding any placeholder tokens).
static bool CollapseValue (const FString &InExpandedValue, FString &OutCollapsedValue)
Given an expanded config value, try and produce a collapsed version of it (adding any placeholder tokens).
static FString ExpandValue (const FString &InCollapsedValue)
Given a collapsed config value, try and produce an expanded version of it (removing any placeholder tokens).
static bool ExpandValue (const FString &InCollapsedValue, FString &OutExpandedValue)
Given a collapsed config value, try and produce an expanded version of it (removing any placeholder tokens).
Data Fields
FString Comment
EValueType ValueType
Private Member Functions
bool NeedsToExpandValue ()
Internal version of ExpandValue that expands SavedValue into ExpandedValue, or produces an empty ExpandedValue if no expansion occurred.
Private Attributes
bool bExpandOnDemand = false
FString SavedValue
uint32 SavedValueHash
Friends
class FConfigBranch
class FConfigCacheIni
Gets the SavedValue without marking it as having been accessed for e.g.
class FConfigFile
struct FDetailedConfigMemUsage
FArchive & operator<< (FArchive &Ar, FConfigValue &ConfigValue)
void operator<< (FStructuredArchive::FSlot Slot, FConfigValue &ConfigValue)
Detailed Description
Definition at line 123 of file ConfigCacheIni.h.
Member Enumeration Documentation
EValueType
enum class FConfigValue::EValueType : uint8 strong
Enumerator
Set
ArrayAdd
ArrayAddUnique
Remove
Clear
InitializeToEmpty
ArrayOfStructKey
POCArrayOfStructKey
Combined
ArrayCombined
Definition at line 126 of file ConfigCacheIni.h.
Constructor & Destructor Documentation
FConfigValue() [1/10]
FConfigValue::FConfigValue () inline
Definition at line 152 of file ConfigCacheIni.h.
References FConfigValue().
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), operator!=(), operator<<, operator<<, operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().
FConfigValue() [2/10]
FConfigValue::FConfigValue (const FConfigSection * InSection, FName InValueName, EValueType Type = EValueType::Combined) inline
Definition at line 156 of file ConfigCacheIni.h.
References Combined, UE_WITH_CONFIG_TRACKING, and ValueType.
FConfigValue() [3/10]
FConfigValue::FConfigValue (const TCHAR * InValue, EValueType Type = EValueType::Combined) inline
Definition at line 165 of file ConfigCacheIni.h.
References FConfigValue(), and Combined.
FConfigValue() [4/10]
FConfigValue::FConfigValue (const FConfigSection * InSection, FName InValueName, const TCHAR * InValue, EValueType Type = EValueType::Combined) inline
Definition at line 169 of file ConfigCacheIni.h.
References bExpandOnDemand, Combined, FTextLocalizationResource::HashString(), NeedsToExpandValue(), SavedValue, SavedValueHash, UE_WITH_CONFIG_TRACKING, and ValueType.
FConfigValue() [5/10]
FConfigValue::FConfigValue (const FString & InValue, EValueType Type = EValueType::Combined) inline
Definition at line 181 of file ConfigCacheIni.h.
References FConfigValue(), and Combined.
FConfigValue() [6/10]
FConfigValue::FConfigValue (const FConfigSection * InSection, FName InValueName, const FString & InValue, EValueType Type = EValueType::Combined) inline
Definition at line 185 of file ConfigCacheIni.h.
References bExpandOnDemand, Combined, FTextLocalizationResource::HashString(), NeedsToExpandValue(), SavedValue, SavedValueHash, UE_WITH_CONFIG_TRACKING, and ValueType.
FConfigValue() [7/10]
FConfigValue::FConfigValue (FString && InValue, EValueType Type = EValueType::Combined) inline
Definition at line 197 of file ConfigCacheIni.h.
References FConfigValue(), Combined, and MoveTemp().
FConfigValue() [8/10]
FConfigValue::FConfigValue (const FConfigSection * InSection, FName InValueName, FString && InValue, EValueType Type = EValueType::Combined) inline
Definition at line 201 of file ConfigCacheIni.h.
References bExpandOnDemand, Combined, FTextLocalizationResource::HashString(), MoveTemp(), NeedsToExpandValue(), SavedValue, SavedValueHash, UE_WITH_CONFIG_TRACKING, and ValueType.
FConfigValue() [9/10]
FConfigValue::FConfigValue (const FConfigValue & InConfigValue) inline
Definition at line 213 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, SavedValue, SavedValueHash, UE_WITH_CONFIG_TRACKING, and ValueType.
FConfigValue() [10/10]
FConfigValue::FConfigValue (FConfigValue && InConfigValue) inline
Definition at line 226 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, MoveTemp(), SavedValue, SavedValueHash, UE_WITH_CONFIG_TRACKING, and ValueType.
Member Function Documentation
CollapseValue() [1/2]
FString FConfigValue::CollapseValue (const FString & InExpandedValue) static
Given an expanded config value, try and produce a collapsed version of it (adding any placeholder tokens).
Parameters
InExpandedValue The expanded config value to try and expand.
Returns
The collapsed version of the config value.
CollapseValue() [2/2]
bool FConfigValue::CollapseValue (const FString & InExpandedValue, FString & OutCollapsedValue) static
Given an expanded config value, try and produce a collapsed version of it (adding any placeholder tokens).
Parameters
InExpandedValue The expanded config value to try and expand.
OutCollapsedValue String to fill with the collapsed version of the config value.
Returns
true if collapsing occurred, false if the collapsed and expanded values are equal.
ExpandValue() [1/2]
FString FConfigValue::ExpandValue (const FString & InCollapsedValue) static
Given a collapsed config value, try and produce an expanded version of it (removing any placeholder tokens).
Parameters
InCollapsedValue The collapsed config value to try and expand.
Returns
The expanded version of the config value.
ExpandValue() [2/2]
bool FConfigValue::ExpandValue (const FString & InCollapsedValue, FString & OutExpandedValue) static
Given a collapsed config value, try and produce an expanded version of it (removing any placeholder tokens).
Parameters
InCollapsedValue The collapsed config value to try and expand.
OutExpandedValue String to fill with the expanded version of the config value.
Returns
true if expansion occurred, false if the collapsed and expanded values are equal.
Referenced by GetValue(), and GetValueForWriting().
GetSavedValue()
const FString & FConfigValue::GetSavedValue () const inline
Definition at line 295 of file ConfigCacheIni.h.
References UE::ConfigAccessTracking::Private::OnConfigValueRead(), and SavedValue.
GetSavedValueForWriting()
const FString & FConfigValue::GetSavedValueForWriting () const inline
Definition at line 391 of file ConfigCacheIni.h.
References SavedValue.
GetValue()
FORCEINLINE FString FConfigValue::GetValue () const inline
Definition at line 286 of file ConfigCacheIni.h.
References bExpandOnDemand, ExpandValue(), FORCEINLINE, UE::ConfigAccessTracking::Private::OnConfigValueRead(), and SavedValue.
GetValueForWriting()
FORCEINLINE FString FConfigValue::GetValueForWriting () const inline
Gets the expanded value (GetValue) without marking it as having been accessed for e.g.
writing out to a ConfigFile to disk
Definition at line 381 of file ConfigCacheIni.h.
References bExpandOnDemand, ExpandValue(), FORCEINLINE, and SavedValue.
NeedsToExpandValue()
bool FConfigValue::NeedsToExpandValue () private
Internal version of ExpandValue that expands SavedValue into ExpandedValue, or produces an empty ExpandedValue if no expansion occurred.
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), operator<<, and operator=().
operator!=()
bool FConfigValue::operator!= (const FConfigValue & Other) const inline
Definition at line 320 of file ConfigCacheIni.h.
References FConfigValue(), operator==(), and Other.
operator=() [1/5]
FConfigValue & FConfigValue::operator= (const FConfigValue & RHS) inline
Definition at line 253 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, SavedValue, SavedValueHash, and ValueType.
operator=() [2/5]
FConfigValue & FConfigValue::operator= (const FString & RHS) inline
Definition at line 272 of file ConfigCacheIni.h.
References FConfigValue().
operator=() [3/5]
FConfigValue & FConfigValue::operator= (const TCHAR * RHS) inline
Definition at line 267 of file ConfigCacheIni.h.
References FConfigValue().
operator=() [4/5]
FConfigValue & FConfigValue::operator= (FConfigValue && RHS) inline
Definition at line 239 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, MoveTemp(), SavedValue, SavedValueHash, and ValueType.
operator=() [5/5]
FConfigValue & FConfigValue::operator= (FString && RHS) inline
Definition at line 277 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, FTextLocalizationResource::HashString(), MoveTemp(), NeedsToExpandValue(), SavedValue, and SavedValueHash.
operator==()
bool FConfigValue::operator== (const FConfigValue & Other) const inline
Definition at line 319 of file ConfigCacheIni.h.
References FConfigValue(), Other, and SavedValueHash.
Referenced by operator!=().
Friends And Related Symbol Documentation
FConfigBranch
friend class FConfigBranch friend
Definition at line 389 of file ConfigCacheIni.h.
References FConfigBranch.
Referenced by FConfigBranch.
FConfigCacheIni
friend class FConfigCacheIni friend
Gets the SavedValue without marking it as having been accessed for e.g.
writing out to a ConfigFile to disk
Definition at line 387 of file ConfigCacheIni.h.
References FConfigCacheIni.
Referenced by FConfigCacheIni.
FConfigFile
friend class FConfigFile friend
Definition at line 388 of file ConfigCacheIni.h.
References FConfigFile.
Referenced by FConfigFile.
FDetailedConfigMemUsage
friend struct FDetailedConfigMemUsage friend
Definition at line 390 of file ConfigCacheIni.h.
References FDetailedConfigMemUsage.
Referenced by FDetailedConfigMemUsage.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FConfigValue & ConfigValue) friend
Definition at line 322 of file ConfigCacheIni.h.
References FConfigValue(), Ar, and FStructuredArchiveFromArchive::GetSlot().
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FConfigValue & ConfigValue) friend
Definition at line 328 of file ConfigCacheIni.h.
References FConfigValue(), bExpandOnDemand, UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), NeedsToExpandValue(), and SavedValue.
Field Documentation
bExpandOnDemand
bool FConfigValue::bExpandOnDemand = false private
Definition at line 406 of file ConfigCacheIni.h.
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), GetValue(), GetValueForWriting(), operator<<, operator=(), operator=(), and operator=().
Comment
FString FConfigValue::Comment
Definition at line 377 of file ConfigCacheIni.h.
SavedValue
FString FConfigValue::SavedValue private
Definition at line 400 of file ConfigCacheIni.h.
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), GetSavedValue(), GetSavedValueForWriting(), GetValue(), GetValueForWriting(), operator<<, operator=(), operator=(), and operator=().
SavedValueHash
uint32 FConfigValue::SavedValueHash private
Definition at line 401 of file ConfigCacheIni.h.
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), operator=(), operator=(), operator=(), and operator==().
ValueType
EValueType FConfigValue::ValueType
Definition at line 404 of file ConfigCacheIni.h.
Referenced by FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), FConfigValue(), operator=(), and operator=().
The documentation for this struct was generated from the following file:
ConfigCacheIni.h