Unreal Engine 5.6 C++ API: IMovieSceneBindingEventReceiverInterface Class Reference
IMovieSceneBindingEventReceiverInterface Class Reference
Interface for objects to implement used by the binding lifetime track to provide events when sequnecer activates or deactivates a binding.
#include "MovieSceneBindingEventReceiverInterface.h"
Public Member Functions
GENERATED_BODY () UFUNCTION() void OnObjectBoundBySequencer(UMovieSceneSequencePlayer *Player
virtual void OnObjectBoundBySequencer_Implementation (UMovieSceneSequencePlayer *Player, FMovieSceneObjectBindingID BindingID)
virtual void OnObjectUnboundBySequencer_Implementation (UMovieSceneSequencePlayer *Player, FMovieSceneObjectBindingID BindingID)
UFUNCTION () void OnObjectUnboundBySequencer(UMovieSceneSequencePlayer *Player
Data Fields
FMovieSceneObjectBindingID BindingID
Detailed Description
Interface for objects to implement used by the binding lifetime track to provide events when sequnecer activates or deactivates a binding.
Definition at line 27 of file MovieSceneBindingEventReceiverInterface.h.
Member Function Documentation
GENERATED_BODY()
IMovieSceneBindingEventReceiverInterface::GENERATED_BODY ()
References UFUNCTION().
OnObjectBoundBySequencer_Implementation()
virtual void IMovieSceneBindingEventReceiverInterface::OnObjectBoundBySequencer_Implementation (UMovieSceneSequencePlayer * Player, FMovieSceneObjectBindingID BindingID) inline virtual
Definition at line 34 of file MovieSceneBindingEventReceiverInterface.h.
References BindingID, and OnObjectBoundBySequencer_Implementation().
Referenced by OnObjectBoundBySequencer_Implementation().
OnObjectUnboundBySequencer_Implementation()
virtual void IMovieSceneBindingEventReceiverInterface::OnObjectUnboundBySequencer_Implementation (UMovieSceneSequencePlayer * Player, FMovieSceneObjectBindingID BindingID) inline virtual
Definition at line 38 of file MovieSceneBindingEventReceiverInterface.h.
References BindingID.
UFUNCTION()
IMovieSceneBindingEventReceiverInterface::UFUNCTION ()
References BindingID.
Referenced by GENERATED_BODY().
Field Documentation
BindingID
FMovieSceneObjectBindingID IMovieSceneBindingEventReceiverInterface::BindingID
Definition at line 33 of file MovieSceneBindingEventReceiverInterface.h.
Referenced by OnObjectBoundBySequencer_Implementation(), OnObjectUnboundBySequencer_Implementation(), and UFUNCTION().
The documentation for this class was generated from the following file:
MovieSceneBindingEventReceiverInterface.h