Unreal Engine 5.6 C++ API: IRendererModule Class Reference
IRendererModule Class Reference abstract
The public interface of the renderer module.
#include "RendererInterface.h"
Public Member Functions
virtual void AddMeshBatchToGPUScene (FGPUScenePrimitiveCollector *Collector, FMeshBatch &MeshBatch)=0
virtual void AddVirtualTextureProducerDestroyedCallback (const FVirtualTextureProducerHandle &Handle, FVTProducerDestroyedFunction *Function, void *Baton)=0
RENDERCORE_API IAdaptiveVirtualTexture * AllocateAdaptiveVirtualTexture (const FAdaptiveVTDescription &AdaptiveVTDesc, const FAllocatedVTDescription &AllocatedVTDesc)
virtual IAdaptiveVirtualTexture * AllocateAdaptiveVirtualTexture (FRHICommandListBase &RHICmdList, const FAdaptiveVTDescription &AdaptiveVTDesc, const FAllocatedVTDescription &AllocatedVTDesc)=0
virtual FSceneInterface * AllocateScene (UWorld *World, bool bInRequiresHitProxies, bool bCreateFXSystem, ERHIFeatureLevel::Type InFeatureLevel)=0
Allocates a new instance of the private FScene implementation for the given world.
virtual class FSceneViewStateInterface * AllocateViewState (ERHIFeatureLevel::Type FeatureLevel)=0
Allocates a new instance of the private scene manager implementation of FSceneViewStateInterface.
virtual class FSceneViewStateInterface * AllocateViewState (ERHIFeatureLevel::Type FeatureLevel, FSceneViewStateInterface *ShareOriginTarget)=0
RENDERCORE_API IAllocatedVirtualTexture * AllocateVirtualTexture (const FAllocatedVTDescription &Desc)
virtual IAllocatedVirtualTexture * AllocateVirtualTexture (FRHICommandListBase &RHICmdList, const FAllocatedVTDescription &Desc)=0
virtual void BeginRenderingViewFamilies (FCanvas *Canvas, TConstArrayView< FSceneViewFamily * > ViewFamilies)=0
Experimental: Render multiple view families in a single scene render call.
virtual void BeginRenderingViewFamily (FCanvas *Canvas, FSceneViewFamily *ViewFamily)=0
Call from the game thread to send a message to the rendering thread to being rendering this view family.
virtual IScenePrimitiveRenderingContext * BeginScenePrimitiveRendering (FRDGBuilder &GraphBuilder, FSceneInterface &Scene)=0
virtual IScenePrimitiveRenderingContext * BeginScenePrimitiveRendering (FRDGBuilder &GraphBuilder, FSceneViewFamily *ViewFamily)=0
Prepare Scene primitive rendering and return context.
virtual void CreateAndInitSingleView (FRHICommandListImmediate &RHICmdList, class FSceneViewFamily *ViewFamily, const struct FSceneViewInitOptions *ViewInitOptions)=0
Call from the render thread to create and initalize a new FViewInfo with the specified options, and add it to the specified view family.
virtual TUniquePtr< ISceneRenderBuilder > CreateSceneRenderBuilder (FSceneInterface *Scene)=0
virtual FSceneUniformBuffer * CreateSinglePrimitiveSceneUniformBuffer (FRDGBuilder &GraphBuilder, const FViewInfo &SceneView, FMeshBatch &Mesh)=0
virtual FSceneUniformBuffer * CreateSinglePrimitiveSceneUniformBuffer (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FMeshBatch &Mesh)=0
Create a Scene Uniform Buffer containing only the scene representation for a single primitive.
virtual TRDGUniformBufferRef< FBatchedPrimitiveParameters > CreateSinglePrimitiveUniformView (FRDGBuilder &GraphBuilder, const FViewInfo &SceneView, FMeshBatch &Mesh)=0
virtual TRDGUniformBufferRef< FBatchedPrimitiveParameters > CreateSinglePrimitiveUniformView (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, EShaderPlatform ShaderPlatform, FMeshBatch &Mesh)=0
Create a Uniform Buffer containing representation for a single primitive.
virtual void DebugLogOnCrash ()=0
Renderer gets a chance to log some useful crash data.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnResolvedSceneColor, FRDGBuilder &, const FSceneTextures &)
Delegate that is called upon resolving scene color.
virtual void DestroyAdaptiveVirtualTexture (IAdaptiveVirtualTexture *AdaptiveVT)=0
virtual void DestroyVirtualTexture (IAllocatedVirtualTexture *AllocatedVT)=0
virtual void DrawRectangle (FRHICommandList &RHICmdList, float X, float Y, float SizeX, float SizeY, float U, float V, float SizeU, float SizeV, FIntPoint TargetSize, FIntPoint TextureSize, const TShaderRefBase< FShader, FShaderMapPointerTable > &VertexShader, EDrawRectangleFlags Flags=EDRF_Default)=0
Draws a quad with the given vertex positions and UVs in denormalized pixel/texel coordinates.
virtual void DrawTileMesh (FCanvasRenderContext &RenderContext, struct FMeshPassProcessorRenderState &DrawRenderState, const FSceneView &View, FMeshBatch &Mesh, bool bIsHitTesting, const class FHitProxyId &HitProxyId, bool bUse128bitRT=false)=0
Draws a tile mesh element with the specified view.
virtual void ExecVisualizeTextureCmd (const FString &Cmd)=0
virtual void FlushVirtualTextureCache ()=0
Evict all data from virtual texture caches.
virtual void FlushVirtualTextureCache (IAllocatedVirtualTexture *AllocatedVT, const FVector2f &InUV0, const FVector2f &InUV1)=0
Evict all data from virtual texture cache for a given allocated virtual texture.
virtual const TSet< FSceneInterface * > & GetAllocatedScenes ()=0
virtual const FGlobalDistanceFieldParameterData * GetGlobalDistanceFieldParameterData (const FSceneView &View)=0
virtual uint64 GetNaniteRequestRecordBuffer (TArray< uint32 > &OutRequestData)=0
Fetch the page requests recorded since the last call to SetNaniteRequestRecordBuffer.
virtual uint32 GetNumDynamicLightsAffectingPrimitive (const class FPrimitiveSceneInfo *PrimitiveSceneInfo, const class FLightCacheInterface *LCI)=0
virtual const FViewMatrices & GetPreviousViewMatrices (const FSceneView &View)=0
virtual FOnResolvedSceneColor & GetResolvedSceneColorCallbacks ()=0
Accessor for post scene color resolve delegates.
virtual uint64 GetVirtualTextureRequestRecordBuffer (TSet< uint64 > &OutPageRequests)=0
Fetch the virtual texture page requests recorded since the last call to SetVirtualTextureRequestRecordBuffer.
virtual void GPUBenchmark (FSynthBenchmarkResults &InOut, float WorkScale=10.0f)=0
virtual void InitializeSystemTextures (FRHICommandListImmediate &RHICmdList)=0
virtual void InvalidatePathTracedOutput (PathTracing::EInvalidateReason InvalidateReason=PathTracing::EInvalidateReason::Uncategorized)=0
Mark all the current scenes as needing to restart path tracer accumulation.
virtual void LoadPendingVirtualTextureTiles (FRHICommandListImmediate &RHICmdList, ERHIFeatureLevel::Type FeatureLevel)=0
Ensure that any tiles requested by 'RequestVirtualTextureTiles' are loaded, must be called from render thread.
virtual void LockVirtualTextureTiles (FVirtualTextureProducerHandle ProducerHandle, int32 InMipLevel)=0
Lock all tiles associated with a producer up to and including a given mip level.
virtual void OnWorldCleanup (UWorld *World, bool bSessionEnded, bool bCleanupResources, bool bWorldChanged)=0
virtual void PerFrameCleanupIfSkipRenderer ()=0
Performs necessary per-frame cleanup.
virtual void PostRenderAllViewports ()=0
virtual void PrefetchNaniteResource (const Nanite::FResources *Resource, uint32 NumFramesUntilRender)=0
Start prefetching streaming data for Nanite resource that will soon be used for rendering.
virtual void RegisterCustomCullingImpl (ICustomCulling *impl)=0
Register/unregister a custom occlusion culling implementation.
virtual FDelegateHandle RegisterOverlayRenderDelegate (const FPostOpaqueRenderDelegate &OverlayRenderDelegate)=0
virtual FDelegateHandle RegisterPostOpaqueRenderDelegate (const FPostOpaqueRenderDelegate &PostOpaqueRenderDelegate)=0
RENDERCORE_API FVirtualTextureProducerHandle RegisterVirtualTextureProducer (const FVTProducerDescription &Desc, IVirtualTexture *Producer)
virtual FVirtualTextureProducerHandle RegisterVirtualTextureProducer (FRHICommandListBase &RHICmdList, const FVTProducerDescription &Desc, IVirtualTexture *Producer)=0
virtual void ReleaseVirtualTexturePendingResources ()=0
virtual void ReleaseVirtualTextureProducer (const FVirtualTextureProducerHandle &Handle)=0
virtual uint32 RemoveAllVirtualTextureProducerDestroyedCallbacks (const void *Baton)=0
virtual void RemoveOverlayRenderDelegate (FDelegateHandle OverlayRenderDelegate)=0
virtual void RemovePostOpaqueRenderDelegate (FDelegateHandle PostOpaqueRenderDelegate)=0
virtual void RemoveScene (FSceneInterface *Scene)=0
virtual void RequestNanitePages (TArrayView< uint32 > InRequestData)=0
Request Nanite pages that were captured with SetNaniteRequestRecordBuffer.
virtual void RequestStaticMeshUpdate (FPrimitiveSceneInfo *Info)=0
virtual void RequestVirtualTextureTiles (const FMaterialRenderProxy *InMaterialRenderProxy, const FVector2D &InScreenSpaceSize, ERHIFeatureLevel::Type InFeatureLevel)=0
virtual void RequestVirtualTextureTiles (const FVector2D &InScreenSpaceSize, int32 InMipLevel)=0
virtual void RequestVirtualTextureTiles (IAllocatedVirtualTexture *AllocatedVT, const FVector2D &InScreenSpaceSize, const FVector2D &InViewportPosition, const FVector2D &InViewportSize, const FVector2D &InUV0, const FVector2D &InUV1, int32 InMipLevel)=0
Helper function to request loading of tiles for a virtual texture that will be displayed in the UI.
virtual void RequestVirtualTextureTiles (TArray< uint64 > &&InPageRequests)=0
Request an array of virtual texture page requests that was captured with SetVirtualTextureRequestRecordBuffer.
virtual void ResetSceneTextureExtentHistory ()=0
Resets the scene texture extent history.
virtual void SetNaniteRequestRecordBuffer (uint64 Handle)=0
Allocate a buffer and record all nanite page requests until the next call to either SetNaniteRequestRecordBuffer or GetNaniteRequestRecordBuffer.
virtual void SetVirtualTextureRequestRecordBuffer (uint64 Handle)=0
Allocate a buffer and record all virtual texture page requests until the next call to either SetVirtualTextureRequestRecordBuffer or GetVirtualTextureRequestRecordBuffer.
UE_DEPRECATED (5.4, "IPersistentViewUniformBufferExtension will be removed in a future version.") virtual void RegisterPersistentViewUniformBufferExtension(IPersistentViewUniformBufferExtension *Extension)=0
UE_DEPRECATED (5.4, "Use RequestVirtualTextureTiles() overloads that takes similar parameters. Make sure not to negate the InViewportPosition.") virtual void RequestVirtualTextureTilesForRegion(IAllocatedVirtualTexture *AllocatedVT
virtual void UnregisterCustomCullingImpl (ICustomCulling *impl)=0
virtual void UpdateMapNeedsLightingFullyRebuiltState (UWorld *World)=0
virtual void UpdateStaticDrawLists ()=0
Updates all static draw lists for each allocated scene.
virtual void UpdateStaticDrawListsForMaterials (const TArray< const FMaterial * > &Materials)=0
Updates static draw lists for the given set of materials for each allocated scene.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Data Fields
const FVector2D const FVector2D const FVector2D const FVector2D const FVector2D int32 InMipLevel = 0
const FVector2D & InScreenSpaceSize
const FVector2D const FVector2D const FVector2D const FVector2D & InUV0
const FVector2D const FVector2D const FVector2D const FVector2D const FVector2D & InUV1
const FVector2D const FVector2D & InViewportPosition
const FVector2D const FVector2D const FVector2D & InViewportSize
Detailed Description
The public interface of the renderer module.
Definition at line 681 of file RendererInterface.h.
Member Function Documentation
AddMeshBatchToGPUScene()
virtual void IRendererModule::AddMeshBatchToGPUScene (FGPUScenePrimitiveCollector * Collector, FMeshBatch & MeshBatch) pure virtual
References AddMeshBatchToGPUScene().
Referenced by AddMeshBatchToGPUScene().
AddVirtualTextureProducerDestroyedCallback()
virtual void IRendererModule::AddVirtualTextureProducerDestroyedCallback (const FVirtualTextureProducerHandle & Handle, FVTProducerDestroyedFunction * Function, void * Baton) pure virtual
References Function, and Handle.
AllocateAdaptiveVirtualTexture() [1/2]
RENDERCORE_API IAdaptiveVirtualTexture * IRendererModule::AllocateAdaptiveVirtualTexture (const FAdaptiveVTDescription & AdaptiveVTDesc, const FAllocatedVTDescription & AllocatedVTDesc)
AllocateAdaptiveVirtualTexture() [2/2]
virtual IAdaptiveVirtualTexture * IRendererModule::AllocateAdaptiveVirtualTexture (FRHICommandListBase & RHICmdList, const FAdaptiveVTDescription & AdaptiveVTDesc, const FAllocatedVTDescription & AllocatedVTDesc) pure virtual
AllocateScene()
virtual FSceneInterface * IRendererModule::AllocateScene (UWorld * World, bool bInRequiresHitProxies, bool bCreateFXSystem, ERHIFeatureLevel::Type InFeatureLevel) pure virtual
Allocates a new instance of the private FScene implementation for the given world.
Parameters
World - An optional world to associate with the scene.
bInRequiresHitProxies - Indicates that hit proxies should be rendered in the scene.
AllocateViewState() [1/2]
virtual class FSceneViewStateInterface * IRendererModule::AllocateViewState (ERHIFeatureLevel::Type FeatureLevel) pure virtual
Allocates a new instance of the private scene manager implementation of FSceneViewStateInterface.
AllocateViewState() [2/2]
virtual class FSceneViewStateInterface * IRendererModule::AllocateViewState (ERHIFeatureLevel::Type FeatureLevel, FSceneViewStateInterface * ShareOriginTarget) pure virtual
AllocateVirtualTexture() [1/2]
RENDERCORE_API IAllocatedVirtualTexture * IRendererModule::AllocateVirtualTexture (const FAllocatedVTDescription & Desc)
AllocateVirtualTexture() [2/2]
virtual IAllocatedVirtualTexture * IRendererModule::AllocateVirtualTexture (FRHICommandListBase & RHICmdList, const FAllocatedVTDescription & Desc) pure virtual
BeginRenderingViewFamilies()
virtual void IRendererModule::BeginRenderingViewFamilies (FCanvas * Canvas, TConstArrayView< FSceneViewFamily * > ViewFamilies) pure virtual
Experimental: Render multiple view families in a single scene render call.
All families must reference the same FScene. Scene Capture not yet supported.
References BeginRenderingViewFamilies().
Referenced by BeginRenderingViewFamilies().
BeginRenderingViewFamily()
virtual void IRendererModule::BeginRenderingViewFamily (FCanvas * Canvas, FSceneViewFamily * ViewFamily) pure virtual
Call from the game thread to send a message to the rendering thread to being rendering this view family.
BeginScenePrimitiveRendering() [1/2]
virtual IScenePrimitiveRenderingContext * IRendererModule::BeginScenePrimitiveRendering (FRDGBuilder & GraphBuilder, FSceneInterface & Scene) pure virtual
References BeginScenePrimitiveRendering(), and Scene.
BeginScenePrimitiveRendering() [2/2]
virtual IScenePrimitiveRenderingContext * IRendererModule::BeginScenePrimitiveRendering (FRDGBuilder & GraphBuilder, FSceneViewFamily * ViewFamily) pure virtual
Prepare Scene primitive rendering and return context.
Ensures all primitives that are created are commited and GPU-Scene is updated and allocates a dynamic primitive context. The intended use is for stand-alone rendering that involves Scene proxies (that then may need the machinery to render GPU-Scene aware primitives.
References BeginScenePrimitiveRendering().
Referenced by BeginScenePrimitiveRendering(), and BeginScenePrimitiveRendering().
CreateAndInitSingleView()
virtual void IRendererModule::CreateAndInitSingleView (FRHICommandListImmediate & RHICmdList, class FSceneViewFamily * ViewFamily, const struct FSceneViewInitOptions * ViewInitOptions) pure virtual
Call from the render thread to create and initalize a new FViewInfo with the specified options, and add it to the specified view family.
CreateSceneRenderBuilder()
virtual TUniquePtr< ISceneRenderBuilder > IRendererModule::CreateSceneRenderBuilder (FSceneInterface * Scene) pure virtual
References CreateSceneRenderBuilder(), and Scene.
Referenced by CreateSceneRenderBuilder().
CreateSinglePrimitiveSceneUniformBuffer() [1/2]
virtual FSceneUniformBuffer * IRendererModule::CreateSinglePrimitiveSceneUniformBuffer (FRDGBuilder & GraphBuilder, const FViewInfo & SceneView, FMeshBatch & Mesh) pure virtual
References Mesh.
CreateSinglePrimitiveSceneUniformBuffer() [2/2]
virtual FSceneUniformBuffer * IRendererModule::CreateSinglePrimitiveSceneUniformBuffer (FRDGBuilder & GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FMeshBatch & Mesh) pure virtual
Create a Scene Uniform Buffer containing only the scene representation for a single primitive.
References Mesh.
CreateSinglePrimitiveUniformView() [1/2]
virtual TRDGUniformBufferRef< FBatchedPrimitiveParameters > IRendererModule::CreateSinglePrimitiveUniformView (FRDGBuilder & GraphBuilder, const FViewInfo & SceneView, FMeshBatch & Mesh) pure virtual
References Mesh.
CreateSinglePrimitiveUniformView() [2/2]
virtual TRDGUniformBufferRef< FBatchedPrimitiveParameters > IRendererModule::CreateSinglePrimitiveUniformView (FRDGBuilder & GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, EShaderPlatform ShaderPlatform, FMeshBatch & Mesh) pure virtual
Create a Uniform Buffer containing representation for a single primitive.
(For platforms that use "UniformView" path)
References Mesh, and ShaderPlatform.
DebugLogOnCrash()
virtual void IRendererModule::DebugLogOnCrash () pure virtual
Renderer gets a chance to log some useful crash data.
DECLARE_MULTICAST_DELEGATE_TwoParams()
IRendererModule::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnResolvedSceneColor , FRDGBuilder & , const FSceneTextures &)
Delegate that is called upon resolving scene color.
DestroyAdaptiveVirtualTexture()
virtual void IRendererModule::DestroyAdaptiveVirtualTexture (IAdaptiveVirtualTexture * AdaptiveVT) pure virtual
DestroyVirtualTexture()
virtual void IRendererModule::DestroyVirtualTexture (IAllocatedVirtualTexture * AllocatedVT) pure virtual
DrawRectangle()
virtual void IRendererModule::DrawRectangle (FRHICommandList & RHICmdList, float X, float Y, float SizeX, float SizeY, float U, float V, float SizeU, float SizeV, FIntPoint TargetSize, FIntPoint TextureSize, const TShaderRefBase< FShader, FShaderMapPointerTable > & VertexShader, EDrawRectangleFlags Flags = EDRF_Default) pure virtual
Draws a quad with the given vertex positions and UVs in denormalized pixel/texel coordinates.
The platform-dependent mapping from pixels to texels is done automatically. Note that the positions are affected by the current viewport. NOTE: DrawRectangle should be used in the vertex shader to calculate the correct position and uv for vertices.
X, Y Position in screen pixels of the top left corner of the quad SizeX, SizeY Size in screen pixels of the quad U, V Position in texels of the top left corner of the quad's UV's SizeU, SizeV Size in texels of the quad's UV's TargetSizeX, TargetSizeY Size in screen pixels of the target surface TextureSize Size in texels of the source texture VertexShader The vertex shader used for rendering Flags see EDrawRectangleFlags
References EDRF_Default, Flags, X, and Y.
DrawTileMesh()
virtual void IRendererModule::DrawTileMesh (FCanvasRenderContext & RenderContext, struct FMeshPassProcessorRenderState & DrawRenderState, const FSceneView & View, FMeshBatch & Mesh, bool bIsHitTesting, const class FHitProxyId & HitProxyId, bool bUse128bitRT = false) pure virtual
Draws a tile mesh element with the specified view.
References Mesh.
ExecVisualizeTextureCmd()
virtual void IRendererModule::ExecVisualizeTextureCmd (const FString & Cmd) pure virtual
References Cmd.
FlushVirtualTextureCache() [1/2]
virtual void IRendererModule::FlushVirtualTextureCache () pure virtual
Evict all data from virtual texture caches.
References FlushVirtualTextureCache().
Referenced by FlushVirtualTextureCache(), and FlushVirtualTextureCache().
FlushVirtualTextureCache() [2/2]
virtual void IRendererModule::FlushVirtualTextureCache (IAllocatedVirtualTexture * AllocatedVT, const FVector2f & InUV0, const FVector2f & InUV1) pure virtual
Evict all data from virtual texture cache for a given allocated virtual texture.
References FlushVirtualTextureCache(), InUV0, and InUV1.
GetAllocatedScenes()
virtual const TSet< FSceneInterface * > & IRendererModule::GetAllocatedScenes () pure virtual
GetGlobalDistanceFieldParameterData()
virtual const FGlobalDistanceFieldParameterData * IRendererModule::GetGlobalDistanceFieldParameterData (const FSceneView & View) pure virtual
References GetGlobalDistanceFieldParameterData().
Referenced by GetGlobalDistanceFieldParameterData().
GetNaniteRequestRecordBuffer()
virtual uint64 IRendererModule::GetNaniteRequestRecordBuffer (TArray< uint32 > & OutRequestData) pure virtual
Fetch the page requests recorded since the last call to SetNaniteRequestRecordBuffer.
Returns the handle that was passed in.
References GetNaniteRequestRecordBuffer().
Referenced by GetNaniteRequestRecordBuffer().
GetNumDynamicLightsAffectingPrimitive()
virtual uint32 IRendererModule::GetNumDynamicLightsAffectingPrimitive (const class FPrimitiveSceneInfo * PrimitiveSceneInfo, const class FLightCacheInterface * LCI) pure virtual
Returns
The number of lights that affect a primitive.
GetPreviousViewMatrices()
virtual const FViewMatrices & IRendererModule::GetPreviousViewMatrices (const FSceneView & View) pure virtual
References GetPreviousViewMatrices().
Referenced by GetPreviousViewMatrices().
GetResolvedSceneColorCallbacks()
virtual FOnResolvedSceneColor & IRendererModule::GetResolvedSceneColorCallbacks () pure virtual
Accessor for post scene color resolve delegates.
GetVirtualTextureRequestRecordBuffer()
virtual uint64 IRendererModule::GetVirtualTextureRequestRecordBuffer (TSet< uint64 > & OutPageRequests) pure virtual
Fetch the virtual texture page requests recorded since the last call to SetVirtualTextureRequestRecordBuffer.
Returns the handle that was passed in.
References GetVirtualTextureRequestRecordBuffer().
Referenced by GetVirtualTextureRequestRecordBuffer().
GPUBenchmark()
virtual void IRendererModule::GPUBenchmark (FSynthBenchmarkResults & InOut, float WorkScale = 10.0f) pure virtual
InitializeSystemTextures()
virtual void IRendererModule::InitializeSystemTextures (FRHICommandListImmediate & RHICmdList) pure virtual
InvalidatePathTracedOutput()
virtual void IRendererModule::InvalidatePathTracedOutput (PathTracing::EInvalidateReason InvalidateReason = PathTracing::EInvalidateReason::Uncategorized) pure virtual
Mark all the current scenes as needing to restart path tracer accumulation.
References InvalidatePathTracedOutput(), and Uncategorized.
Referenced by InvalidatePathTracedOutput().
LoadPendingVirtualTextureTiles()
virtual void IRendererModule::LoadPendingVirtualTextureTiles (FRHICommandListImmediate & RHICmdList, ERHIFeatureLevel::Type FeatureLevel) pure virtual
Ensure that any tiles requested by 'RequestVirtualTextureTiles' are loaded, must be called from render thread.
References LoadPendingVirtualTextureTiles().
Referenced by LoadPendingVirtualTextureTiles().
LockVirtualTextureTiles()
virtual void IRendererModule::LockVirtualTextureTiles (FVirtualTextureProducerHandle ProducerHandle, int32 InMipLevel) pure virtual
Lock all tiles associated with a producer up to and including a given mip level.
The mip level is stored on the producer, so that if we call twice then the second call will either lock or unlock tiles to reach the new level. Locked tiles should remain resident once loaded, though there is no guarantee over how quickly they will be loaded. Also if the virtual texture pools are already oversubscribed then we will not be able to satisfy the loading.
References InMipLevel, and LockVirtualTextureTiles().
Referenced by LockVirtualTextureTiles().
OnWorldCleanup()
virtual void IRendererModule::OnWorldCleanup (UWorld * World, bool bSessionEnded, bool bCleanupResources, bool bWorldChanged) pure virtual
PerFrameCleanupIfSkipRenderer()
virtual void IRendererModule::PerFrameCleanupIfSkipRenderer () pure virtual
Performs necessary per-frame cleanup.
Only use when rendering through scene renderer (i.e. BeginRenderingViewFamily) is skipped
PostRenderAllViewports()
virtual void IRendererModule::PostRenderAllViewports () pure virtual
PrefetchNaniteResource()
virtual void IRendererModule::PrefetchNaniteResource (const Nanite::FResources * Resource, uint32 NumFramesUntilRender) pure virtual
Start prefetching streaming data for Nanite resource that will soon be used for rendering.
TODO: Implement callback mechanism
References PrefetchNaniteResource().
Referenced by PrefetchNaniteResource().
RegisterCustomCullingImpl()
virtual void IRendererModule::RegisterCustomCullingImpl (ICustomCulling * impl) pure virtual
Register/unregister a custom occlusion culling implementation.
RegisterOverlayRenderDelegate()
virtual FDelegateHandle IRendererModule::RegisterOverlayRenderDelegate (const FPostOpaqueRenderDelegate & OverlayRenderDelegate) pure virtual
RegisterPostOpaqueRenderDelegate()
virtual FDelegateHandle IRendererModule::RegisterPostOpaqueRenderDelegate (const FPostOpaqueRenderDelegate & PostOpaqueRenderDelegate) pure virtual
RegisterVirtualTextureProducer() [1/2]
RENDERCORE_API FVirtualTextureProducerHandle IRendererModule::RegisterVirtualTextureProducer (const FVTProducerDescription & Desc, IVirtualTexture * Producer)
RegisterVirtualTextureProducer() [2/2]
virtual FVirtualTextureProducerHandle IRendererModule::RegisterVirtualTextureProducer (FRHICommandListBase & RHICmdList, const FVTProducerDescription & Desc, IVirtualTexture * Producer) pure virtual
ReleaseVirtualTexturePendingResources()
virtual void IRendererModule::ReleaseVirtualTexturePendingResources () pure virtual
ReleaseVirtualTextureProducer()
virtual void IRendererModule::ReleaseVirtualTextureProducer (const FVirtualTextureProducerHandle & Handle) pure virtual
References Handle.
RemoveAllVirtualTextureProducerDestroyedCallbacks()
virtual uint32 IRendererModule::RemoveAllVirtualTextureProducerDestroyedCallbacks (const void * Baton) pure virtual
RemoveOverlayRenderDelegate()
virtual void IRendererModule::RemoveOverlayRenderDelegate (FDelegateHandle OverlayRenderDelegate) pure virtual
RemovePostOpaqueRenderDelegate()
virtual void IRendererModule::RemovePostOpaqueRenderDelegate (FDelegateHandle PostOpaqueRenderDelegate) pure virtual
RemoveScene()
virtual void IRendererModule::RemoveScene (FSceneInterface * Scene) pure virtual
References Scene.
RequestNanitePages()
virtual void IRendererModule::RequestNanitePages (TArrayView< uint32 > InRequestData) pure virtual
Request Nanite pages that were captured with SetNaniteRequestRecordBuffer.
Note that the array will be moved and ownership is taken.
References RequestNanitePages().
Referenced by RequestNanitePages().
RequestStaticMeshUpdate()
virtual void IRendererModule::RequestStaticMeshUpdate (FPrimitiveSceneInfo * Info) pure virtual
References Info, and RequestStaticMeshUpdate().
Referenced by RequestStaticMeshUpdate().
RequestVirtualTextureTiles() [1/4]
virtual void IRendererModule::RequestVirtualTextureTiles (const FMaterialRenderProxy * InMaterialRenderProxy, const FVector2D & InScreenSpaceSize, ERHIFeatureLevel::Type InFeatureLevel) pure virtual
References InScreenSpaceSize.
RequestVirtualTextureTiles() [2/4]
virtual void IRendererModule::RequestVirtualTextureTiles (const FVector2D & InScreenSpaceSize, int32 InMipLevel) pure virtual
References InMipLevel, and InScreenSpaceSize.
Referenced by RequestVirtualTextureTiles().
RequestVirtualTextureTiles() [3/4]
virtual void IRendererModule::RequestVirtualTextureTiles (IAllocatedVirtualTexture * AllocatedVT, const FVector2D & InScreenSpaceSize, const FVector2D & InViewportPosition, const FVector2D & InViewportSize, const FVector2D & InUV0, const FVector2D & InUV1, int32 InMipLevel) pure virtual
Helper function to request loading of tiles for a virtual texture that will be displayed in the UI.
It will request only the tiles that will be visible after clipping to the provided viewport.
Parameters
AllocatedVT The virtual texture.
InScreenSpaceSize Size on screen at which the texture is to be displayed.
InViewportPosition Position in the viewport where the texture will be displayed.
InViewportSize Size of the viewport.
InUV0 UV coordinate to use for the top left corner of the texture.
InUV1 UV coordinate to use for the bottom right corner of the texture.
InMipLevel [optional] Specific mip level to fetch tiles for.
References InMipLevel, InScreenSpaceSize, InUV0, InUV1, InViewportPosition, and InViewportSize.
RequestVirtualTextureTiles() [4/4]
virtual void IRendererModule::RequestVirtualTextureTiles (TArray< uint64 > && InPageRequests) pure virtual
Request an array of virtual texture page requests that was captured with SetVirtualTextureRequestRecordBuffer.
Note that the array will be moved and ownership is taken.
References RequestVirtualTextureTiles().
ResetSceneTextureExtentHistory()
virtual void IRendererModule::ResetSceneTextureExtentHistory () pure virtual
Resets the scene texture extent history.
Call this method after rendering with very large render targets. The next scene render will create them at the requested size.
References ResetSceneTextureExtentHistory().
Referenced by ResetSceneTextureExtentHistory().
SetNaniteRequestRecordBuffer()
virtual void IRendererModule::SetNaniteRequestRecordBuffer (uint64 Handle) pure virtual
Allocate a buffer and record all nanite page requests until the next call to either SetNaniteRequestRecordBuffer or GetNaniteRequestRecordBuffer.
References Handle, and SetNaniteRequestRecordBuffer().
Referenced by SetNaniteRequestRecordBuffer().
SetVirtualTextureRequestRecordBuffer()
virtual void IRendererModule::SetVirtualTextureRequestRecordBuffer (uint64 Handle) pure virtual
Allocate a buffer and record all virtual texture page requests until the next call to either SetVirtualTextureRequestRecordBuffer or GetVirtualTextureRequestRecordBuffer.
References Handle, and SetVirtualTextureRequestRecordBuffer().
Referenced by SetVirtualTextureRequestRecordBuffer().
UE_DEPRECATED() [1/2]
IRendererModule::UE_DEPRECATED (5. 4, "IPersistentViewUniformBufferExtension will be removed in a future version.") pure virtual
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
IRendererModule::UE_DEPRECATED (5. 4, "Use RequestVirtualTextureTiles() overloads that takes similar parameters. Make sure not to negate the InViewportPosition.")
Referenced by UE_DEPRECATED().
UnregisterCustomCullingImpl()
virtual void IRendererModule::UnregisterCustomCullingImpl (ICustomCulling * impl) pure virtual
UpdateMapNeedsLightingFullyRebuiltState()
virtual void IRendererModule::UpdateMapNeedsLightingFullyRebuiltState (UWorld * World) pure virtual
UpdateStaticDrawLists()
virtual void IRendererModule::UpdateStaticDrawLists () pure virtual
Updates all static draw lists for each allocated scene.
UpdateStaticDrawListsForMaterials()
virtual void IRendererModule::UpdateStaticDrawListsForMaterials (const TArray< const FMaterial * > & Materials) pure virtual
Updates static draw lists for the given set of materials for each allocated scene.
Field Documentation
InMipLevel
const FVector2D const FVector2D const FVector2D const FVector2D const FVector2D int32 IRendererModule::InMipLevel = 0
Definition at line 833 of file RendererInterface.h.
Referenced by LockVirtualTextureTiles(), RequestVirtualTextureTiles(), and RequestVirtualTextureTiles().
InScreenSpaceSize
const FVector2D& IRendererModule::InScreenSpaceSize
Definition at line 833 of file RendererInterface.h.
Referenced by RequestVirtualTextureTiles(), RequestVirtualTextureTiles(), and RequestVirtualTextureTiles().
InUV0
const FVector2D const FVector2D const FVector2D const FVector2D& IRendererModule::InUV0
Definition at line 833 of file RendererInterface.h.
Referenced by FlushVirtualTextureCache(), and RequestVirtualTextureTiles().
InUV1
const FVector2D const FVector2D const FVector2D const FVector2D const FVector2D& IRendererModule::InUV1
Definition at line 833 of file RendererInterface.h.
Referenced by FlushVirtualTextureCache(), and RequestVirtualTextureTiles().
InViewportPosition
const FVector2D const FVector2D& IRendererModule::InViewportPosition
Definition at line 833 of file RendererInterface.h.
Referenced by RequestVirtualTextureTiles().
InViewportSize
const FVector2D const FVector2D const FVector2D& IRendererModule::InViewportSize
Definition at line 833 of file RendererInterface.h.
Referenced by RequestVirtualTextureTiles().
The documentation for this class was generated from the following file:
RendererInterface.h