Unreal Engine 5.6 C++ API: UE::FChangeTransactor Struct Reference
UE::FChangeTransactor Struct Reference
Helper structure used for inserting FChange based undo/redo operations inside of the GUndo (ITransaction) instance.
#include "ChangeTransactor.h"
Public Member Functions
FChangeTransactor ()
FChangeTransactor (UObject *InTransactionObject)
~FChangeTransactor ()
template<typename T, typename... TArgs>
void AddTransactionChange (TArgs &&... Args)
Inserts a FChange instance into the compound change data.
void CloseTransaction ()
Closes the currently pending transaction, inserting a FCompoundChange object, containing any FChange's transacted during the transaction, into GUndo alongside of the currently targeted UObject instance.
bool IsTransactionPending ()
void OpenTransaction (const FText &TransactionDescription)
Opens a new transaction with the provided description.
void SetTransactionObject (UObject *InTransactionObject)
Set the UObject instance for which to transact FChange's.
Static Public Member Functions
static bool CanTransactChanges ()
Private Member Functions
void CheckTransactionObject ()
Private Attributes
TUniquePtr< FCompoundChangeInput > CompoundChangeData
int32 PendingTransactionIndex
Pending transaction index and compound change object.
int32 TransactedChanges
Number of non-FSwapChange based changes which have been transacted.
TWeakObjectPtr< UObject > TransactionObject
Weak reference to the target object.
Detailed Description
Helper structure used for inserting FChange based undo/redo operations inside of the GUndo (ITransaction) instance.
The operations are targeted a specific UObject, which is used as the 'transactional' object. The transactions themselves are initiated using the ITransactor API using GEngine as the instance.
Definition at line 18 of file ChangeTransactor.h.
Constructor & Destructor Documentation
FChangeTransactor() [1/2]
UE::FChangeTransactor::FChangeTransactor () inline
Definition at line 20 of file ChangeTransactor.h.
References INDEX_NONE, PendingTransactionIndex, TransactedChanges, and TransactionObject.
FChangeTransactor() [2/2]
UE::FChangeTransactor::FChangeTransactor (UObject * InTransactionObject) inline
Definition at line 21 of file ChangeTransactor.h.
References INDEX_NONE, PendingTransactionIndex, TransactedChanges, and TransactionObject.
~FChangeTransactor()
UE::FChangeTransactor::~FChangeTransactor () inline
Definition at line 22 of file ChangeTransactor.h.
Member Function Documentation
AddTransactionChange()
template<typename T, typename... TArgs> void UE::FChangeTransactor::AddTransactionChange (TArgs &&... Args) inline
Inserts a FChange instance into the compound change data.
Parameters
Args Template arguments for T's constructor
Definition at line 96 of file ChangeTransactor.h.
References CanTransactChanges(), checkf, CheckTransactionObject(), CompoundChangeData, Forward(), GUndo, IsTransactionPending(), MakeUnique(), MoveTemp(), TEXT, TransactedChanges, TransactionObject, and Value.
CanTransactChanges()
bool UE::FChangeTransactor::CanTransactChanges () inline static
Definition at line 122 of file ChangeTransactor.h.
References GEngine.
Referenced by UE::FScopedCompoundTransaction::FScopedCompoundTransaction(), AddTransactionChange(), IAnimationDataController::ConditionalAction(), IAnimationDataController::ConditionalBracket(), IAnimationDataController::ConditionalTransaction(), and OpenTransaction().
CheckTransactionObject()
void UE::FChangeTransactor::CheckTransactionObject () inline private
Definition at line 127 of file ChangeTransactor.h.
References checkf, TEXT, and TransactionObject.
Referenced by AddTransactionChange(), CloseTransaction(), and OpenTransaction().
CloseTransaction()
void UE::FChangeTransactor::CloseTransaction () inline
Closes the currently pending transaction, inserting a FCompoundChange object, containing any FChange's transacted during the transaction, into GUndo alongside of the currently targeted UObject instance.
Definition at line 56 of file ChangeTransactor.h.
References check, checkf, CheckTransactionObject(), CompoundChangeData, GEngine, GUndo, IsTransactionPending(), MakeUnique(), MoveTemp(), PendingTransactionIndex, TEXT, TransactedChanges, and TransactionObject.
IsTransactionPending()
bool UE::FChangeTransactor::IsTransactionPending () inline
Definition at line 85 of file ChangeTransactor.h.
References CompoundChangeData, and PendingTransactionIndex.
Referenced by AddTransactionChange(), CloseTransaction(), OpenTransaction(), and SetTransactionObject().
OpenTransaction()
void UE::FChangeTransactor::OpenTransaction (const FText & TransactionDescription) inline
Opens a new transaction with the provided description.
Parameters
TransactionDescription Description of the transaction taking place
Definition at line 40 of file ChangeTransactor.h.
References CanTransactChanges(), checkf, CheckTransactionObject(), CompoundChangeData, GEngine, IsTransactionPending(), MakeUnique(), PendingTransactionIndex, TEXT, and TransactionObject.
SetTransactionObject()
void UE::FChangeTransactor::SetTransactionObject (UObject * InTransactionObject) inline
Set the UObject instance for which to transact FChange's.
Parameters
InTransactionObject UObject instance to target
Definition at line 29 of file ChangeTransactor.h.
References checkf, IsTransactionPending(), TEXT, and TransactionObject.
Field Documentation
CompoundChangeData
TUniquePtr<FCompoundChangeInput> UE::FChangeTransactor::CompoundChangeData private
Definition at line 138 of file ChangeTransactor.h.
Referenced by AddTransactionChange(), CloseTransaction(), IsTransactionPending(), and OpenTransaction().
PendingTransactionIndex
int32 UE::FChangeTransactor::PendingTransactionIndex private
Pending transaction index and compound change object.
Definition at line 137 of file ChangeTransactor.h.
Referenced by FChangeTransactor(), FChangeTransactor(), CloseTransaction(), IsTransactionPending(), and OpenTransaction().
TransactedChanges
int32 UE::FChangeTransactor::TransactedChanges private
Number of non-FSwapChange based changes which have been transacted.
Definition at line 141 of file ChangeTransactor.h.
Referenced by FChangeTransactor(), FChangeTransactor(), AddTransactionChange(), and CloseTransaction().
TransactionObject
TWeakObjectPtr<UObject> UE::FChangeTransactor::TransactionObject private
Weak reference to the target object.
Definition at line 134 of file ChangeTransactor.h.
Referenced by FChangeTransactor(), FChangeTransactor(), AddTransactionChange(), CheckTransactionObject(), CloseTransaction(), OpenTransaction(), and SetTransactionObject().
The documentation for this struct was generated from the following file:
ChangeTransactor.h