Unreal Engine 5.6 C++ API: UE::CurveEditor Namespace Reference
UE::CurveEditor Namespace Reference
Namespaces
namespace KeySelection
namespace Private
Data Structures
struct FCurveBounds
class FCurveDrawParamsCache
Caches curve draw params for curves of a curve editor.
struct FCurveDrawParamsHandle
Handle for an entry in the draw params array.
class FCurveEditorCommandChange
Base class for actions that support undo / redo in the curve editor.
struct FCurveTangentMirrorData
Holds data about mirroring keys in a single curve.
struct FKeyPasteArgs
Arguments for pasting keys in FCurveEditor.
struct FMirrorableTangentInfo
class FPositionMirrorSolver
This class facilitates the movement of a dragged edge and recalculates the key heights for all specified keys.
class FPromotedFilterCommandBinder
Binds and unbinds commands that are created by FPromotedFilterContainer.
class FPromotedFilterContainer
Holds the state for surfacing filters to the toolbar from the SCurveEditorFilterPanel, so the user can access & apply them more quickly.
class FScopedSelectionTransaction
This util starts a transaction.
class FTangentMirrorSolver
Given keys that are between an imaginary, x-axis aligned mirror edge and dragged edge, this class facilitates recalculates the tangents for all specified keys.
class FTangentSelectionFlattener
Given some keys, this class squishes the curves based on how much the selection is squished vertically.
class FTransactionManager
Interacts with the transaction system to enable command-based actions for curve editor.
class ICurveEditorCurveCachePool
class TInvertedCurveModel
class TUniformMirrorSolver
This class computes linear interpolation for values involving the movement of edges in a rectangular selection of keys.
Enumerations
enum class ECurveEditorPasteFlags : uint8 { None , SetSelection = 1 << 0 , Relative = 1 << 1 , Default = SetSelection }
Enhances the paste operation.
enum class ECurveEditorPasteMode : uint8 { OverwriteRange , Merge }
Defines the merging behaviour of the paste operation.
Functions
ENUM_CLASS_FLAGS (ECurveEditorPasteFlags)
CURVEEDITOR_API FMirrorableTangentInfo FilterMirrorableTangents (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, TConstArrayView< FKeyHandle > InKeys)
CURVEEDITOR_API FCurveBounds FindMinMaxHeight (TConstArrayView< FKeyHandle > InKeys, const FCurveModel &InCurveModel)
FMenuEntryResizeParams MakeResizeParams (FStringView UISpecifier, const ISlateStyle &Style=FAppStyle::Get())
Looks up the CurveEditor.AllowClipping.
CURVEEDITOR_API void MirrorKeyPositions (TConstArrayView< FKeyHandle > InKeysToMirror, const FCurveModelID &InCurveId, double InBottomHeight, double InTopHeight, double InMirrorHeight, FCurveEditor &InCurveEditor)
Recomputes the key position OutputValues as if the points were mirrored accross an imaginary x-axis aligned mirror edge.
template<typename TCallback, typename TMapAllocator = FDefaultSetAllocator, typename TArrayAllocator = FDefaultAllocator>
requires std::is_invocable_v<TCallback, TConstArrayView<FKeyHandle>, const FCurveModelID&, double /*Min*/, double /*Max*/, double /*Midpoint*/>
void MirrorOnMidpoint (const TMap< FCurveModelID, TArray< FKeyHandle, TArrayAllocator >, TMapAllocator > &InKeysToMirror, FCurveEditor &InCurveEditor, TCallback &&InProcess)
Finds the mid-point of every curve's passed in key handles and mirrors all points on the imaginary line going through it.
CURVEEDITOR_API void MirrorTangents (TConstArrayView< FKeyHandle > InKeysToMirror, const FCurveModelID &InCurveId, double InBottomHeight, double InTopHeight, double InMirrorHeight, FCurveEditor &InCurveEditor)
Recomputes the tangents of specified keys as if the points were mirrored across an imaginary x-axis aligned mirror edge.
void ModifyCurves (TConstArrayView< FCurveModelID > InCurves, FCurveEditor &InCurveEditor)
Modifies all referenced curves.
void RecomputeMirroringParallel (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, FCurveTangentMirrorData &InCurveData, double InMirrorValue)
Mirrors the tangents stores in InCurveData.
template<typename TCallback>
requires std::is_invocable_r_v<FVector2D, TCallback, int32, const FVector2D&>
void RecomputeMirroringParallel (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, FCurveTangentMirrorData &InCurveData, double InMirrorValue, TCallback &&InPostProcessTangents)
Mirrors the tangents stores in InCurveData.
template<typename TCallback>
requires std::is_invocable_r_v<FVector2D, TCallback, int32/*KeyIndex*/, const FVector2D&/*InterpolatedTangents*/>
void RecomputeMirroringParallel (const FCurveEditor &InCurveEditor, const FCurveModelID &InCurveId, FCurveTangentMirrorData &InCurveData, double InMirrorValue, TCallback &&InPostProcessTangents)
Mirrors the tangents stores in InCurveData.
Enumeration Type Documentation
ECurveEditorPasteFlags
enum class UE::CurveEditor::ECurveEditorPasteFlags : uint8 strong
Enhances the paste operation.
Enumerator
None
SetSelection
Set the selection to the pasted keys.
Relative
Pastes the keys from the clipboard aligning them to the nearest key to the left of the scrubber.
Default
Definition at line 24 of file KeyPasteArgs.h.
ECurveEditorPasteMode
enum class UE::CurveEditor::ECurveEditorPasteMode : uint8 strong
Defines the merging behaviour of the paste operation.
Enumerator
OverwriteRange
Pastes the keys from the clipboard overwriting any key in destination track between the first and last pasted keys.
Merge
Existing keys are mostly retained.
Existing keys are only replaced by pasted keys that have the same X value.
Definition at line 15 of file KeyPasteArgs.h.
Function Documentation
ENUM_CLASS_FLAGS()
UE::CurveEditor::ENUM_CLASS_FLAGS (ECurveEditorPasteFlags)
FilterMirrorableTangents()
CURVEEDITOR_API FMirrorableTangentInfo UE::CurveEditor::FilterMirrorableTangents (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, TConstArrayView< FKeyHandle > InKeys)
Returns
Information you can use to FCurveTangentMirrorData.
Referenced by UE::CurveEditor::FTangentMirrorSolver::AddTangents().
FindMinMaxHeight()
CURVEEDITOR_API FCurveBounds UE::CurveEditor::FindMinMaxHeight (TConstArrayView< FKeyHandle > InKeys, const FCurveModel & InCurveModel)
Returns
Find the min and max height values.
Referenced by MirrorOnMidpoint().
MakeResizeParams()
FMenuEntryResizeParams UE::CurveEditor::MakeResizeParams (FStringView UISpecifier, const ISlateStyle & Style = FAppStyle::Get()) inline
Looks up the CurveEditor.AllowClipping.
[UISpecifier] and CurveEditor.ClipPriority.[UISpecifier] from the given style.
Returns
Resizing params to use for the toolbar item.
Definition at line 22 of file ResizeParamUtils.h.
References FMenuEntryResizeParams::DefaultAllowClipping, FMenuEntryResizeParams::DefaultClippingPriority, ensureAlwaysMsgf, TStringView< CharType >::GetData(), ISlateStyle::GetFloat(), and TEXT.
MirrorKeyPositions()
CURVEEDITOR_API void UE::CurveEditor::MirrorKeyPositions (TConstArrayView< FKeyHandle > InKeysToMirror, const FCurveModelID & InCurveId, double InBottomHeight, double InTopHeight, double InMirrorHeight, FCurveEditor & InCurveEditor)
Recomputes the key position OutputValues as if the points were mirrored accross an imaginary x-axis aligned mirror edge.
The mirror Edge is positioned between the top and bottom edge.
Note
This function only recalculates key positions. Tangents must be set separately.
Parameters
InKeysToMirror Keys located between BottomHeight and TopHeight, whose tangents will be recomputed.
InCurveId The curve the keys belong to
InBottomHeight The height of the bottom edge.
InTopHeight The height of the top edge.
InMirrorHeight The height of the imaginary x-axis-aligned mirror edge across which tangents are mirrored.
InCurveEditor Reference to the curve editor used to set key attributes.
MirrorOnMidpoint()
template<typename TCallback, typename TMapAllocator = FDefaultSetAllocator, typename TArrayAllocator = FDefaultAllocator> requires std::is_invocable_v<TCallback, TConstArrayView<FKeyHandle>, const FCurveModelID&, double /*Min*/, double /*Max*/, double /*Midpoint*/> void UE::CurveEditor::MirrorOnMidpoint (const TMap< FCurveModelID, TArray< FKeyHandle, TArrayAllocator >, TMapAllocator > & InKeysToMirror, FCurveEditor & InCurveEditor, TCallback && InProcess)
Finds the mid-point of every curve's passed in key handles and mirrors all points on the imaginary line going through it.
Parameters
InKeysToMirror Curve to the keys on it to mirror
InCurveEditor The editor to which the keys belong
Definition at line 82 of file MirrorUtils.h.
References FCurveEditor::FindCurve(), FindMinMaxHeight(), InProcess, UE::Max, and UE::Min.
MirrorTangents()
CURVEEDITOR_API void UE::CurveEditor::MirrorTangents (TConstArrayView< FKeyHandle > InKeysToMirror, const FCurveModelID & InCurveId, double InBottomHeight, double InTopHeight, double InMirrorHeight, FCurveEditor & InCurveEditor)
Recomputes the tangents of specified keys as if the points were mirrored across an imaginary x-axis aligned mirror edge.
The mirror edge is positioned between the top and bottom edges.
Note
This function only recalculates tangents. Key positions must be set separately.
Parameters
InKeysToMirror Keys located between BottomHeight and TopHeight, whose tangents will be recomputed.
InCurveId The curve the keys belong to
InBottomHeight The height of the bottom edge.
InTopHeight The height of the top edge.
InMirrorHeight The height of the imaginary x-axis-aligned mirror edge across which tangents are mirrored.
InCurveEditor Reference to the curve editor used to set key attributes.
ModifyCurves()
void UE::CurveEditor::ModifyCurves (TConstArrayView< FCurveModelID > InCurves, FCurveEditor & InCurveEditor) inline
Modifies all referenced curves.
Definition at line 12 of file CurveEditorUtils.h.
References FCurveEditor::FindCurve(), and FCurveModel::Modify().
RecomputeMirroringParallel() [1/3]
void UE::CurveEditor::RecomputeMirroringParallel (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, FCurveTangentMirrorData & InCurveData, double InMirrorValue) inline
Mirrors the tangents stores in InCurveData.
Definition at line 87 of file MultiCurveMirrorUtils.h.
References RecomputeMirroringParallel().
Referenced by UE::CurveEditor::FTangentMirrorSolver::OnMoveEdge(), and RecomputeMirroringParallel().
RecomputeMirroringParallel() [2/3]
template<typename TCallback> requires std::is_invocable_r_v<FVector2D, TCallback, int32, const FVector2D&> void UE::CurveEditor::RecomputeMirroringParallel (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, FCurveTangentMirrorData & InCurveData, double InMirrorValue, TCallback && InPostProcessTangents)
Mirrors the tangents stores in InCurveData.
This version accepts a callback for post-processing, which is useful for e.g. applying a falloff to the interpolated values.
Definition at line 100 of file MultiCurveMirrorUtils.h.
References UE::CurveEditor::FCurveTangentMirrorData::AttributesToSet, FCurveEditor::FindCurve(), UE::CurveEditor::FCurveTangentMirrorData::KeyHandles, FCurveModel::SetKeyAttributes(), and UE::CurveEditor::FCurveTangentMirrorData::TangentSolver.
RecomputeMirroringParallel() [3/3]
template<typename TCallback> requires std::is_invocable_r_v<FVector2D, TCallback, int32/*KeyIndex*/, const FVector2D&/*InterpolatedTangents*/> void UE::CurveEditor::RecomputeMirroringParallel (const FCurveEditor & InCurveEditor, const FCurveModelID & InCurveId, FCurveTangentMirrorData & InCurveData, double InMirrorValue, TCallback && InPostProcessTangents)
Mirrors the tangents stores in InCurveData.
This version accepts a callback for post-processing, which is useful for e.g. applying a falloff to the interpolated values.
Definition at line 100 of file MultiCurveMirrorUtils.h.
References UE::CurveEditor::FCurveTangentMirrorData::AttributesToSet, FCurveEditor::FindCurve(), UE::CurveEditor::FCurveTangentMirrorData::KeyHandles, FCurveModel::SetKeyAttributes(), and UE::CurveEditor::FCurveTangentMirrorData::TangentSolver.