Unreal Engine 5.6 C++ API: UMovieScenePiecewiseDoubleBlenderSystem Class Reference
UMovieScenePiecewiseDoubleBlenderSystem Class Reference
#include "MovieScenePiecewiseDoubleBlenderSystem.h"
Public Types
using FComponentTypeID = UE::MovieScene::FComponentTypeID
using FMovieSceneEntityID = UE::MovieScene::FMovieSceneEntityID
Public Member Functions
virtual MOVIESCENETRACKS_API FGraphEventRef DispatchDecomposeTask (const UE::MovieScene::FValueDecompositionParams &Params, UE::MovieScene::FAlignedDecomposedValue *Output) override
GENERATED_BODY () MOVIESCENETRACKS_API UMovieScenePiecewiseDoubleBlenderSystem(const FObjectInitializer &ObjInit)
virtual MOVIESCENETRACKS_API void OnRun (FSystemTaskPrerequisites &InPrerequisites, FSystemSubsequentTasks &Subsequents) override
virtual MOVIESCENETRACKS_API void OnSchedulePersistentTasks (UE::MovieScene::IEntitySystemScheduler *TaskScheduler) override
Private Member Functions
void ReinitializeAccumulationBuffers ()
void ZeroAccumulationBuffers ()
Private Attributes
UE::MovieScene::FAccumulationBuffers AccumulationBuffers
Buffers that contain accumulated blend values, separated by blend type.
bool bContainsNonPropertyBlends = false
Whether the current entity manager contains any non-property based blends.
FComponentMask BlendedPropertyMask
Mask that contains property tags for any property type that has has at least one BlendChannelOutput.
FComponentMask BlendedResultMask
Mask that contains value result components that have BlendChannelInput components.
TBitArray CachedRelevantProperties
Bit array specifying FCompositePropertyTypeID's for properties contained within BlendedPropertyMask.
UE::MovieScene::FCachedEntityManagerState ChannelRelevancyCache
Cache state that is used to invalidate and reset the accumulation buffers when the entity manager has structurally changed.
Detailed Description
Definition at line 124 of file MovieScenePiecewiseDoubleBlenderSystem.h.
Member Typedef Documentation
FComponentTypeID
using UMovieScenePiecewiseDoubleBlenderSystem::FComponentTypeID = UE::MovieScene::FComponentTypeID
Definition at line 132 of file MovieScenePiecewiseDoubleBlenderSystem.h.
FMovieSceneEntityID
using UMovieScenePiecewiseDoubleBlenderSystem::FMovieSceneEntityID = UE::MovieScene::FMovieSceneEntityID
Definition at line 131 of file MovieScenePiecewiseDoubleBlenderSystem.h.
Member Function Documentation
DispatchDecomposeTask()
virtual MOVIESCENETRACKS_API FGraphEventRef UMovieScenePiecewiseDoubleBlenderSystem::DispatchDecomposeTask (const UE::MovieScene::FValueDecompositionParams & Params, UE::MovieScene::FAlignedDecomposedValue * Output) override virtual
References DispatchDecomposeTask(), and Params.
Referenced by DispatchDecomposeTask().
GENERATED_BODY()
UMovieScenePiecewiseDoubleBlenderSystem::GENERATED_BODY () const &
OnRun()
virtual MOVIESCENETRACKS_API void UMovieScenePiecewiseDoubleBlenderSystem::OnRun (FSystemTaskPrerequisites & InPrerequisites, FSystemSubsequentTasks & Subsequents) override virtual
References OnRun().
Referenced by OnRun().
OnSchedulePersistentTasks()
virtual MOVIESCENETRACKS_API void UMovieScenePiecewiseDoubleBlenderSystem::OnSchedulePersistentTasks (UE::MovieScene::IEntitySystemScheduler * TaskScheduler) override virtual
References OnSchedulePersistentTasks().
Referenced by OnSchedulePersistentTasks().
ReinitializeAccumulationBuffers()
void UMovieScenePiecewiseDoubleBlenderSystem::ReinitializeAccumulationBuffers () private
References ReinitializeAccumulationBuffers().
Referenced by ReinitializeAccumulationBuffers().
ZeroAccumulationBuffers()
void UMovieScenePiecewiseDoubleBlenderSystem::ZeroAccumulationBuffers () private
References ZeroAccumulationBuffers().
Referenced by ZeroAccumulationBuffers().
Field Documentation
AccumulationBuffers
UE::MovieScene::FAccumulationBuffers UMovieScenePiecewiseDoubleBlenderSystem::AccumulationBuffers private
Buffers that contain accumulated blend values, separated by blend type.
Definition at line 145 of file MovieScenePiecewiseDoubleBlenderSystem.h.
bContainsNonPropertyBlends
bool UMovieScenePiecewiseDoubleBlenderSystem::bContainsNonPropertyBlends = false private
Whether the current entity manager contains any non-property based blends.
Definition at line 160 of file MovieScenePiecewiseDoubleBlenderSystem.h.
BlendedPropertyMask
FComponentMask UMovieScenePiecewiseDoubleBlenderSystem::BlendedPropertyMask private
Mask that contains property tags for any property type that has has at least one BlendChannelOutput.
Definition at line 151 of file MovieScenePiecewiseDoubleBlenderSystem.h.
BlendedResultMask
FComponentMask UMovieScenePiecewiseDoubleBlenderSystem::BlendedResultMask private
Mask that contains value result components that have BlendChannelInput components.
Definition at line 148 of file MovieScenePiecewiseDoubleBlenderSystem.h.
CachedRelevantProperties
TBitArray UMovieScenePiecewiseDoubleBlenderSystem::CachedRelevantProperties private
Bit array specifying FCompositePropertyTypeID's for properties contained within BlendedPropertyMask.
Definition at line 157 of file MovieScenePiecewiseDoubleBlenderSystem.h.
ChannelRelevancyCache
UE::MovieScene::FCachedEntityManagerState UMovieScenePiecewiseDoubleBlenderSystem::ChannelRelevancyCache private
Cache state that is used to invalidate and reset the accumulation buffers when the entity manager has structurally changed.
Definition at line 154 of file MovieScenePiecewiseDoubleBlenderSystem.h.
The documentation for this class was generated from the following file:
MovieScenePiecewiseDoubleBlenderSystem.h