Unreal Engine 5.6 C++ API: FRigVMTreePathFilter Class Reference
FRigVMTreePathFilter Class Reference
The Path filter is used to include elements only if they match a user provided path.
#include "RigVMTreeToolkitFilter.h"
Public Types
typedef FRigVMTreeFilter Super
Public Types inherited from FRigVMTreeFilter
typedef FRigVMTreeElement Super
Public Member Functions
virtual bool Filters (TSharedRef< FRigVMTreeNode > &InNode, const TSharedRef< FRigVMTreeContext > &InContext) override
const FString & GetFilterText () const
virtual FName GetType () const override
virtual uint32 GetVisibleChildrenHash () const override
virtual bool IsOfType (const FName &InType) const override
void SetFilterText (const FString &InFilterText)
TSharedPtr< FRigVMTreePathFilter > ToSharedPtr () const
TSharedRef< FRigVMTreePathFilter > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeFilter
virtual bool CanBeToggledInUI () const
virtual FText GetLabel () const
virtual FText GetToolTip () const
bool IsEnabled () const
virtual bool IsInvertedInUI () const
void SetEnabled (bool InEnabled)
TSharedPtr< FRigVMTreeFilter > ToSharedPtr () const
TSharedRef< FRigVMTreeFilter > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreePathFilter > Create (Types... Args)
Static Public Member Functions inherited from FRigVMTreeFilter
template<typename... Types>
static TSharedRef< FRigVMTreeFilter > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreePathFilter"))
Static Public Attributes inherited from FRigVMTreeFilter
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeFilter"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
FString FilterText
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreePathFilter > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreePathFilter > &InElement)
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The Path filter is used to include elements only if they match a user provided path.
Definition at line 62 of file RigVMTreeToolkitFilter.h.
Member Typedef Documentation
Super
typedef FRigVMTreeFilter FRigVMTreePathFilter::Super
Definition at line 65 of file RigVMTreeToolkitFilter.h.
Member Function Documentation
Create()
template<typename... Types> TSharedRef< FRigVMTreePathFilter > FRigVMTreePathFilter::Create (Types... Args) inline static
Definition at line 65 of file RigVMTreeToolkitFilter.h.
Filters()
virtual bool FRigVMTreePathFilter::Filters (TSharedRef< FRigVMTreeNode > & InNode, const TSharedRef< FRigVMTreeContext > & InContext) override virtual
Reimplemented from FRigVMTreeFilter.
References Filters().
Referenced by Filters().
GetFilterText()
const FString & FRigVMTreePathFilter::GetFilterText () const inline
Definition at line 71 of file RigVMTreeToolkitFilter.h.
References FilterText, and GetFilterText().
Referenced by GetFilterText().
GetType()
virtual FName FRigVMTreePathFilter::GetType () const inline override virtual
Reimplemented from FRigVMTreeFilter.
Definition at line 65 of file RigVMTreeToolkitFilter.h.
GetVisibleChildrenHash()
virtual uint32 FRigVMTreePathFilter::GetVisibleChildrenHash () const override virtual
Reimplemented from FRigVMTreeFilter.
References GetVisibleChildrenHash().
Referenced by GetVisibleChildrenHash().
IsOfType()
virtual bool FRigVMTreePathFilter::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeFilter.
Definition at line 65 of file RigVMTreeToolkitFilter.h.
SetFilterText()
void FRigVMTreePathFilter::SetFilterText (const FString & InFilterText) inline
Definition at line 75 of file RigVMTreeToolkitFilter.h.
References FilterText.
ToSharedPtr()
TSharedPtr< FRigVMTreePathFilter > FRigVMTreePathFilter::ToSharedPtr () const inline
Definition at line 65 of file RigVMTreeToolkitFilter.h.
ToSharedRef()
TSharedRef< FRigVMTreePathFilter > FRigVMTreePathFilter::ToSharedRef () const inline
Definition at line 65 of file RigVMTreeToolkitFilter.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreePathFilter > & InElement) friend
Definition at line 65 of file RigVMTreeToolkitFilter.h.
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreePathFilter > & InElement) friend
Definition at line 65 of file RigVMTreeToolkitFilter.h.
Field Documentation
FilterText
FString FRigVMTreePathFilter::FilterText private
Definition at line 81 of file RigVMTreeToolkitFilter.h.
Referenced by GetFilterText(), and SetFilterText().
Type
const FLazyName FRigVMTreePathFilter::Type = FLazyName(TEXT("FRigVMTreePathFilter")) inline static
Definition at line 65 of file RigVMTreeToolkitFilter.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitFilter.h