Unreal Engine 5.6 C++ API: FShaderResourceParameterInfo Class Reference
FShaderResourceParameterInfo Class Reference
#include "Shader.h"
Public Member Functions
FShaderResourceParameterInfo ()=default
FShaderResourceParameterInfo (uint16 InBaseIndex, uint8 InBufferIndex, EShaderParameterType InType)
LAYOUT_FIELD (EShaderParameterType, Type)
LAYOUT_FIELD (uint16, BaseIndex)
LAYOUT_FIELD (uint8, BufferIndex)
bool operator< (const FShaderResourceParameterInfo &Rhs) const
bool operator== (const FShaderResourceParameterInfo &Rhs) const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderResourceParameterInfo, RENDERCORE_API, NonVirtual)
Friends
FArchive & operator<< (FArchive &Ar, FShaderResourceParameterInfo &Info)
Detailed Description
Definition at line 176 of file Shader.h.
Constructor & Destructor Documentation
FShaderResourceParameterInfo() [1/2]
FShaderResourceParameterInfo::FShaderResourceParameterInfo () default
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), operator<(), operator<<, and operator==().
FShaderResourceParameterInfo() [2/2]
FShaderResourceParameterInfo::FShaderResourceParameterInfo (uint16 InBaseIndex, uint8 InBufferIndex, EShaderParameterType InType) inline
Definition at line 186 of file Shader.h.
References checkf, and TEXT.
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderResourceParameterInfo::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderResourceParameterInfo , RENDERCORE_API , NonVirtual) private
References FShaderResourceParameterInfo().
LAYOUT_FIELD() [1/3]
FShaderResourceParameterInfo::LAYOUT_FIELD (EShaderParameterType , Type)
LAYOUT_FIELD() [2/3]
FShaderResourceParameterInfo::LAYOUT_FIELD (uint16 , BaseIndex)
LAYOUT_FIELD() [3/3]
FShaderResourceParameterInfo::LAYOUT_FIELD (uint8 , BufferIndex)
operator<()
bool FShaderResourceParameterInfo::operator< (const FShaderResourceParameterInfo & Rhs) const inline
Definition at line 209 of file Shader.h.
References FShaderResourceParameterInfo().
operator==()
bool FShaderResourceParameterInfo::operator== (const FShaderResourceParameterInfo & Rhs) const inline
Definition at line 202 of file Shader.h.
References FShaderResourceParameterInfo().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderResourceParameterInfo & Info) friend
Definition at line 194 of file Shader.h.
References FShaderResourceParameterInfo(), Ar, and Info.
The documentation for this class was generated from the following file:
Shader.h