Unreal Engine 5.6 C++ API: MetasoundAssetKey.h File Reference
MetasoundAssetKey.h File Reference
#include "MetasoundFrontendDocument.h"
#include "MetasoundFrontendRegistryKey.h"
#include "MetasoundVertex.h"
#include "UObject/Package.h"
#include "UObject/SoftObjectPath.h"
#include "UObject/TopLevelAssetPath.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "MetasoundAssetKey.generated.h"
Namespaces
namespace Metasound
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
namespace Metasound::Frontend
Macros
#define UE_API METASOUNDFRONTEND_API
#define Metasound::Frontend::UE_DEPRECATED(Version, Message)
Macro for marking up deprecated code, functions and types.
#define Metasound::Frontend::USTRUCT(...)
Functions
USTRUCT () struct FMetaSoundAssetKey
Macro Definition Documentation
UE_API
#define UE_API METASOUNDFRONTEND_API
Definition at line 15 of file MetasoundAssetKey.h.
Function Documentation
USTRUCT()
USTRUCT ()
Definition at line 18 of file MetasoundAssetKey.h.
References FORCEINLINE, GENERATED_BODY, GetTypeHash(), HashCombineFast(), IsValid(), operator<(), operator==(), ToString(), UE_API, and UPROPERTY.