Unreal Engine 5.6 C++ API: TFixedAllocator< NumInlineElements >::ForElementType< ElementType > Class Template Reference
TFixedAllocator< NumInlineElements >::ForElementType< ElementType > Class Template Reference
#include "ContainerAllocationPolicies.h"
Public Member Functions
ForElementType ()
Default constructor.
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE ElementType * GetAllocation () const
SizeType GetInitialCapacity () const
bool HasAllocation () const
FORCEINLINE void MoveToEmpty (ForElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
Private Member Functions
ForElementType (const ForElementType &)
ElementType * GetInlineElements () const
ForElementType & operator= (const ForElementType &)
Private Attributes
TTypeCompatibleBytes< ElementType > InlineData [NumInlineElements]
The data is stored in this array if less than NumInlineElements is needed.
Detailed Description
template<uint32 NumInlineElements>
template<typename ElementType>
class TFixedAllocator< NumInlineElements >::ForElementType< ElementType >
Definition at line 1228 of file ContainerAllocationPolicies.h.
Constructor & Destructor Documentation
ForElementType() [1/2]
template<uint32 NumInlineElements> template<typename ElementType> TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::ForElementType () inline
Default constructor.
Definition at line 1233 of file ContainerAllocationPolicies.h.
Referenced by ForElementType(), MoveToEmpty(), and operator=().
ForElementType() [2/2]
template<uint32 NumInlineElements> template<typename ElementType> TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::ForElementType (const ForElementType< ElementType > &) private
References ForElementType().
Member Function Documentation
CalculateSlackGrow()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1274 of file ContainerAllocationPolicies.h.
References check, and FORCEINLINE.
CalculateSlackReserve()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1262 of file ContainerAllocationPolicies.h.
References check, and FORCEINLINE.
CalculateSlackShrink()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1268 of file ContainerAllocationPolicies.h.
References check, and FORCEINLINE.
GetAllocatedSize()
template<uint32 NumInlineElements> template<typename ElementType> SIZE_T TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1281 of file ContainerAllocationPolicies.h.
GetAllocation()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE ElementType * TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::GetAllocation () const inline
Definition at line 1251 of file ContainerAllocationPolicies.h.
References FORCEINLINE, and GetInlineElements().
GetInitialCapacity()
template<uint32 NumInlineElements> template<typename ElementType> SizeType TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::GetInitialCapacity () const inline
Definition at line 1291 of file ContainerAllocationPolicies.h.
GetInlineElements()
template<uint32 NumInlineElements> template<typename ElementType> ElementType * TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::GetInlineElements () const inline private
Returns
the base of the aligned inline element data
Definition at line 1304 of file ContainerAllocationPolicies.h.
References InlineData.
Referenced by GetAllocation().
HasAllocation()
template<uint32 NumInlineElements> template<typename ElementType> bool TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::HasAllocation () const inline
Definition at line 1286 of file ContainerAllocationPolicies.h.
MoveToEmpty()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE void TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::MoveToEmpty (ForElementType< ElementType > & Other) inline
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 1242 of file ContainerAllocationPolicies.h.
References ForElementType(), checkSlow, FORCEINLINE, InlineData, Other, and RelocateConstructItems().
operator=()
template<uint32 NumInlineElements> template<typename ElementType> ForElementType & TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::operator= (const ForElementType< ElementType > &) private
References ForElementType().
ResizeAllocation()
template<uint32 NumInlineElements> template<typename ElementType> void TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 1256 of file ContainerAllocationPolicies.h.
References check.
Field Documentation
InlineData
template<uint32 NumInlineElements> template<typename ElementType> TTypeCompatibleBytes<ElementType> TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::InlineData[NumInlineElements] private
The data is stored in this array if less than NumInlineElements is needed.
Definition at line 1301 of file ContainerAllocationPolicies.h.
Referenced by GetInlineElements(), and MoveToEmpty().
The documentation for this class was generated from the following file:
ContainerAllocationPolicies.h