Unreal Engine 5.6 C++ API: FRigVMTraitScope Class Reference
FRigVMTraitScope Class Reference
#include "RigVMTraitScope.h"
Public Member Functions
FRigVMTraitScope ()
FRigVMTraitScope (FRigVMTrait *InTrait, const UScriptStruct *InScriptStruct)
FRigVMTraitScope (FRigVMTrait *InTrait, const UScriptStruct *InScriptStruct, TConstArrayView< FRigVMMemoryHandle > InAdditionalMemoryHandles)
TConstArrayView< FRigVMMemoryHandle > GetAdditionalMemoryHandles () const
const UScriptStruct * GetScriptStruct () const
template<typename T = FRigVMTrait>
T * GetTrait ()
template<typename T = FRigVMTrait>
const T * GetTrait () const
template<typename T = FRigVMTrait>
T * GetTraitChecked ()
template<typename T = FRigVMTrait>
const T * GetTraitChecked () const
template<typename T>
bool IsA () const
bool IsValid () const
Private Attributes
TConstArrayView< FRigVMMemoryHandle > AdditionalMemoryHandles
const UScriptStruct * ScriptStruct
FRigVMTrait * Trait
Detailed Description
Definition at line 12 of file RigVMTraitScope.h.
Constructor & Destructor Documentation
FRigVMTraitScope() [1/3]
FRigVMTraitScope::FRigVMTraitScope () inline
Definition at line 15 of file RigVMTraitScope.h.
References ScriptStruct, and Trait.
FRigVMTraitScope() [2/3]
FRigVMTraitScope::FRigVMTraitScope (FRigVMTrait * InTrait, const UScriptStruct * InScriptStruct) inline
Definition at line 21 of file RigVMTraitScope.h.
References ScriptStruct, and Trait.
FRigVMTraitScope() [3/3]
FRigVMTraitScope::FRigVMTraitScope (FRigVMTrait * InTrait, const UScriptStruct * InScriptStruct, TConstArrayView< FRigVMMemoryHandle > InAdditionalMemoryHandles) inline
Definition at line 27 of file RigVMTraitScope.h.
References AdditionalMemoryHandles, ScriptStruct, and Trait.
Member Function Documentation
GetAdditionalMemoryHandles()
TConstArrayView< FRigVMMemoryHandle > FRigVMTraitScope::GetAdditionalMemoryHandles () const inline
Definition at line 84 of file RigVMTraitScope.h.
References AdditionalMemoryHandles.
GetScriptStruct()
const UScriptStruct * FRigVMTraitScope::GetScriptStruct () const inline
Definition at line 79 of file RigVMTraitScope.h.
References ScriptStruct.
GetTrait() [1/2]
template<typename T = FRigVMTrait> T * FRigVMTraitScope::GetTrait () inline
Definition at line 63 of file RigVMTraitScope.h.
References IsA(), and Trait.
GetTrait() [2/2]
template<typename T = FRigVMTrait> const T * FRigVMTraitScope::GetTrait () const inline
Definition at line 46 of file RigVMTraitScope.h.
References IsA(), and Trait.
GetTraitChecked() [1/2]
template<typename T = FRigVMTrait> T * FRigVMTraitScope::GetTraitChecked () inline
Definition at line 73 of file RigVMTraitScope.h.
References check, IsA(), and Trait.
GetTraitChecked() [2/2]
template<typename T = FRigVMTrait> const T * FRigVMTraitScope::GetTraitChecked () const inline
Definition at line 56 of file RigVMTraitScope.h.
References check, IsA(), and Trait.
IsA()
template<typename T> bool FRigVMTraitScope::IsA () const inline
Definition at line 40 of file RigVMTraitScope.h.
References ScriptStruct.
Referenced by GetTrait(), GetTrait(), GetTraitChecked(), and GetTraitChecked().
IsValid()
bool FRigVMTraitScope::IsValid () const inline
Definition at line 34 of file RigVMTraitScope.h.
References ScriptStruct, and Trait.
Field Documentation
AdditionalMemoryHandles
TConstArrayView<FRigVMMemoryHandle> FRigVMTraitScope::AdditionalMemoryHandles private
Definition at line 93 of file RigVMTraitScope.h.
Referenced by FRigVMTraitScope(), and GetAdditionalMemoryHandles().
ScriptStruct
const UScriptStruct* FRigVMTraitScope::ScriptStruct private
Definition at line 92 of file RigVMTraitScope.h.
Referenced by FRigVMTraitScope(), FRigVMTraitScope(), FRigVMTraitScope(), GetScriptStruct(), IsA(), and IsValid().
Trait
FRigVMTrait* FRigVMTraitScope::Trait private
Definition at line 91 of file RigVMTraitScope.h.
Referenced by FRigVMTraitScope(), FRigVMTraitScope(), FRigVMTraitScope(), GetTrait(), GetTrait(), GetTraitChecked(), GetTraitChecked(), and IsValid().
The documentation for this class was generated from the following file:
RigVMTraitScope.h