Unreal Engine 5.6 C++ API: FDriverConfigEntryConstraints Struct Reference
FDriverConfigEntryConstraints Struct Reference
#include "GenericPlatformDriver.h"
Public Member Functions
FDriverConfigEntryConstraints ()=default
FDriverConfigEntryConstraints (const TCHAR *Entry)
bool AreConstraintsSatisfied (const FGPUDriverInfo &Info, uint32 &OutNumSatisfiedConstraints) const
bool HasConstraints ()
Data Fields
TOptional< FRegexPattern > AdapterNameRegexConstraint
TOptional< FString > RHINameConstraint
Detailed Description
Definition at line 271 of file GenericPlatformDriver.h.
Constructor & Destructor Documentation
FDriverConfigEntryConstraints() [1/2]
FDriverConfigEntryConstraints::FDriverConfigEntryConstraints () default
Referenced by FDriverDenyListEntry::FDriverDenyListEntry(), and FSuggestedDriverEntry::FSuggestedDriverEntry().
FDriverConfigEntryConstraints() [2/2]
FDriverConfigEntryConstraints::FDriverConfigEntryConstraints (const TCHAR * Entry) inline
Definition at line 277 of file GenericPlatformDriver.h.
References AdapterNameRegexConstraint, RHINameConstraint, TEXT, and FParse::Value().
Member Function Documentation
AreConstraintsSatisfied()
bool FDriverConfigEntryConstraints::AreConstraintsSatisfied (const FGPUDriverInfo & Info, uint32 & OutNumSatisfiedConstraints) const inline
Definition at line 294 of file GenericPlatformDriver.h.
References AdapterNameRegexConstraint, FRegexMatcher::FindNext(), Info, and RHINameConstraint.
Referenced by FDriverDenyListEntry::AppliesToDriver(), and FSuggestedDriverEntry::AppliesToDriver().
HasConstraints()
bool FDriverConfigEntryConstraints::HasConstraints () inline
Definition at line 320 of file GenericPlatformDriver.h.
References AdapterNameRegexConstraint, and RHINameConstraint.
Referenced by FSuggestedDriverEntry::FSuggestedDriverEntry().
Field Documentation
AdapterNameRegexConstraint
TOptional<FRegexPattern> FDriverConfigEntryConstraints::AdapterNameRegexConstraint
Definition at line 273 of file GenericPlatformDriver.h.
Referenced by FDriverConfigEntryConstraints(), AreConstraintsSatisfied(), and HasConstraints().
RHINameConstraint
TOptional<FString> FDriverConfigEntryConstraints::RHINameConstraint
Definition at line 272 of file GenericPlatformDriver.h.
Referenced by FDriverConfigEntryConstraints(), AreConstraintsSatisfied(), and HasConstraints().
The documentation for this struct was generated from the following file:
GenericPlatformDriver.h