Unreal Engine 5.6 C++ API: UE::FSpinLock Class Reference
UE::FSpinLock Class Reference
#include "SpinLock.h"
Public Member Functions
FSpinLock ()=default
void Lock ()
bool TryLock ()
UE_NONCOPYABLE (FSpinLock)
void Unlock ()
Private Attributes
std::atomic< bool > bFlag { false }
Detailed Description
Definition at line 14 of file SpinLock.h.
Constructor & Destructor Documentation
FSpinLock()
UE::FSpinLock::FSpinLock () default
Referenced by UE_NONCOPYABLE().
Member Function Documentation
Lock()
void UE::FSpinLock::Lock () inline
Definition at line 21 of file SpinLock.h.
References bFlag, and FGenericPlatformProcess::Yield().
TryLock()
bool UE::FSpinLock::TryLock () inline
Definition at line 37 of file SpinLock.h.
References bFlag.
UE_NONCOPYABLE()
UE::FSpinLock::UE_NONCOPYABLE (FSpinLock)
References FSpinLock().
Unlock()
void UE::FSpinLock::Unlock () inline
Definition at line 42 of file SpinLock.h.
References bFlag.
Field Documentation
bFlag
std::atomic<bool> UE::FSpinLock::bFlag { false } private
Definition at line 48 of file SpinLock.h.
Referenced by Lock(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
SpinLock.h