Unreal Engine 5.6 C++ API: FParticlePerfStats Struct Reference
FParticlePerfStats Struct Reference
#include "ParticlePerfStats.h"
Public Member Functions
FParticlePerfStats ()
FORCEINLINE FParticlePerfStats_GT & GetGameThreadStats ()
Returns the current frame Game Thread stats.
FORCEINLINE FParticlePerfStats_GPU & GetGPUStats ()
Returns the current frame GPU stats.
FORCEINLINE FParticlePerfStats_RT & GetRenderThreadStats ()
Returns the current frame Render Thread stats.
void Reset (bool bSyncWithRT)
void ResetGT ()
void ResetRT ()
void Tick ()
void TickRT ()
Static Public Member Functions
static FORCEINLINE void AddComponentStatReader ()
static FORCEINLINE void AddSystemStatReader ()
static FORCEINLINE void AddWorldStatReader ()
static FORCEINLINE bool GetCSVStatsEnabled ()
static FORCEINLINE bool GetGatherComponentStats ()
static FORCEINLINE bool GetGatherSystemStats ()
static FORCEINLINE bool GetGatherWorldStats ()
static FORCEINLINE FParticlePerfStats * GetStats (const UFXSystemAsset *System)
static FORCEINLINE FParticlePerfStats * GetStats (const UFXSystemComponent *Component)
static FORCEINLINE FParticlePerfStats * GetStats (const UWorld *World)
static FORCEINLINE bool GetStatsEnabled ()
static FORCEINLINE void RemoveComponentStatReader ()
static FORCEINLINE void RemoveSystemStatReader ()
static FORCEINLINE void RemoveWorldStatReader ()
static FORCEINLINE void SetCSVStatsEnabled (bool bEnabled)
static FORCEINLINE void SetStatsEnabled (bool bEnabled)
static FORCEINLINE bool ShouldGatherStats ()
Data Fields
FParticlePerfStats_GT GameThreadStats
Stats on GT and GT spawned concurrent work.
FParticlePerfStats_GPU GPUStats
Stats from GPU work.
FParticlePerfStats_RT RenderThreadStats
Stats on RT work.
Static Public Attributes
static TAtomic< bool > bCSVStatsEnabled
static TAtomic< bool > bStatsEnabled
static TAtomic< int32 > ComponentStatsReaders
static TAtomic< int32 > SystemStatsReaders
static TAtomic< int32 > WorldStatsReaders
Static Private Member Functions
static FParticlePerfStats * GetComponentPerfStats (const UFXSystemComponent *FXComponent)
static FParticlePerfStats * GetSystemPerfStats (const UFXSystemAsset *FXAsset)
static FParticlePerfStats * GetWorldPerfStats (const UWorld *World)
Detailed Description
Definition at line 170 of file ParticlePerfStats.h.
Constructor & Destructor Documentation
FParticlePerfStats()
FParticlePerfStats::FParticlePerfStats ()
Referenced by GetComponentPerfStats(), GetStats(), GetStats(), GetStats(), GetSystemPerfStats(), and GetWorldPerfStats().
Member Function Documentation
AddComponentStatReader()
FORCEINLINE void FParticlePerfStats::AddComponentStatReader () inline static
Definition at line 205 of file ParticlePerfStats.h.
References ComponentStatsReaders, and FORCEINLINE.
AddSystemStatReader()
FORCEINLINE void FParticlePerfStats::AddSystemStatReader () inline static
Definition at line 203 of file ParticlePerfStats.h.
References FORCEINLINE, and SystemStatsReaders.
AddWorldStatReader()
FORCEINLINE void FParticlePerfStats::AddWorldStatReader () inline static
Definition at line 201 of file ParticlePerfStats.h.
References FORCEINLINE, and WorldStatsReaders.
GetComponentPerfStats()
FParticlePerfStats * FParticlePerfStats::GetComponentPerfStats (const UFXSystemComponent * FXComponent) static private
References FParticlePerfStats().
Referenced by GetStats().
GetCSVStatsEnabled()
FORCEINLINE bool FParticlePerfStats::GetCSVStatsEnabled () inline static
Definition at line 180 of file ParticlePerfStats.h.
References bCSVStatsEnabled, FORCEINLINE, and Relaxed.
GetGameThreadStats()
FORCEINLINE FParticlePerfStats_GT & FParticlePerfStats::GetGameThreadStats () inline
Returns the current frame Game Thread stats.
Definition at line 256 of file ParticlePerfStats.h.
References FORCEINLINE, and GameThreadStats.
GetGatherComponentStats()
FORCEINLINE bool FParticlePerfStats::GetGatherComponentStats () inline static
Definition at line 184 of file ParticlePerfStats.h.
References ComponentStatsReaders, FORCEINLINE, and Relaxed.
Referenced by GetStats(), and ShouldGatherStats().
GetGatherSystemStats()
FORCEINLINE bool FParticlePerfStats::GetGatherSystemStats () inline static
Definition at line 183 of file ParticlePerfStats.h.
References FORCEINLINE, Relaxed, and SystemStatsReaders.
Referenced by GetStats(), and ShouldGatherStats().
GetGatherWorldStats()
FORCEINLINE bool FParticlePerfStats::GetGatherWorldStats () inline static
Definition at line 182 of file ParticlePerfStats.h.
References FORCEINLINE, Relaxed, and WorldStatsReaders.
Referenced by GetStats(), and ShouldGatherStats().
GetGPUStats()
FORCEINLINE FParticlePerfStats_GPU & FParticlePerfStats::GetGPUStats () inline
Returns the current frame GPU stats.
Definition at line 268 of file ParticlePerfStats.h.
References FORCEINLINE, and GPUStats.
GetRenderThreadStats()
FORCEINLINE FParticlePerfStats_RT & FParticlePerfStats::GetRenderThreadStats () inline
Returns the current frame Render Thread stats.
Definition at line 262 of file ParticlePerfStats.h.
References FORCEINLINE, and RenderThreadStats.
GetStats() [1/3]
FORCEINLINE FParticlePerfStats * FParticlePerfStats::GetStats (const UFXSystemAsset * System) inline static
Definition at line 217 of file ParticlePerfStats.h.
References FParticlePerfStats(), FORCEINLINE, GetGatherSystemStats(), GetStatsEnabled(), and GetSystemPerfStats().
GetStats() [2/3]
FORCEINLINE FParticlePerfStats * FParticlePerfStats::GetStats (const UFXSystemComponent * Component) inline static
Definition at line 228 of file ParticlePerfStats.h.
References FParticlePerfStats(), Component, FORCEINLINE, GetComponentPerfStats(), GetGatherComponentStats(), and GetStatsEnabled().
GetStats() [3/3]
FORCEINLINE FParticlePerfStats * FParticlePerfStats::GetStats (const UWorld * World) inline static
Definition at line 208 of file ParticlePerfStats.h.
References FParticlePerfStats(), FORCEINLINE, GetGatherWorldStats(), GetStatsEnabled(), and GetWorldPerfStats().
Referenced by FParticlePerfStatsContext::FParticlePerfStatsContext(), FParticlePerfStatsContext::FParticlePerfStatsContext(), and FParticlePerfStatsContext::FParticlePerfStatsContext().
GetStatsEnabled()
FORCEINLINE bool FParticlePerfStats::GetStatsEnabled () inline static
Definition at line 181 of file ParticlePerfStats.h.
References bStatsEnabled, FORCEINLINE, and Relaxed.
Referenced by GetStats(), GetStats(), GetStats(), and ShouldGatherStats().
GetSystemPerfStats()
FParticlePerfStats * FParticlePerfStats::GetSystemPerfStats (const UFXSystemAsset * FXAsset) static private
References FParticlePerfStats().
Referenced by GetStats().
GetWorldPerfStats()
FParticlePerfStats * FParticlePerfStats::GetWorldPerfStats (const UWorld * World) static private
References FParticlePerfStats().
Referenced by GetStats().
RemoveComponentStatReader()
FORCEINLINE void FParticlePerfStats::RemoveComponentStatReader () inline static
Definition at line 206 of file ParticlePerfStats.h.
References ComponentStatsReaders, and FORCEINLINE.
RemoveSystemStatReader()
FORCEINLINE void FParticlePerfStats::RemoveSystemStatReader () inline static
Definition at line 204 of file ParticlePerfStats.h.
References FORCEINLINE, and SystemStatsReaders.
RemoveWorldStatReader()
FORCEINLINE void FParticlePerfStats::RemoveWorldStatReader () inline static
Definition at line 202 of file ParticlePerfStats.h.
References FORCEINLINE, and WorldStatsReaders.
Reset()
void FParticlePerfStats::Reset (bool bSyncWithRT)
ResetGT()
void FParticlePerfStats::ResetGT ()
ResetRT()
void FParticlePerfStats::ResetRT ()
SetCSVStatsEnabled()
FORCEINLINE void FParticlePerfStats::SetCSVStatsEnabled (bool bEnabled) inline static
Definition at line 199 of file ParticlePerfStats.h.
References bCSVStatsEnabled, and FORCEINLINE.
SetStatsEnabled()
FORCEINLINE void FParticlePerfStats::SetStatsEnabled (bool bEnabled) inline static
Definition at line 200 of file ParticlePerfStats.h.
References bStatsEnabled, and FORCEINLINE.
ShouldGatherStats()
FORCEINLINE bool FParticlePerfStats::ShouldGatherStats () inline static
Definition at line 185 of file ParticlePerfStats.h.
References FORCEINLINE, GetGatherComponentStats(), GetGatherSystemStats(), GetGatherWorldStats(), and GetStatsEnabled().
Tick()
void FParticlePerfStats::Tick ()
TickRT()
void FParticlePerfStats::TickRT ()
Field Documentation
bCSVStatsEnabled
TAtomic<bool> FParticlePerfStats::bCSVStatsEnabled static
Definition at line 244 of file ParticlePerfStats.h.
Referenced by GetCSVStatsEnabled(), and SetCSVStatsEnabled().
bStatsEnabled
TAtomic<bool> FParticlePerfStats::bStatsEnabled static
Definition at line 239 of file ParticlePerfStats.h.
Referenced by GetStatsEnabled(), and SetStatsEnabled().
ComponentStatsReaders
TAtomic<int32> FParticlePerfStats::ComponentStatsReaders static
Definition at line 242 of file ParticlePerfStats.h.
Referenced by AddComponentStatReader(), GetGatherComponentStats(), and RemoveComponentStatReader().
GameThreadStats
FParticlePerfStats_GT FParticlePerfStats::GameThreadStats
Stats on GT and GT spawned concurrent work.
Definition at line 247 of file ParticlePerfStats.h.
Referenced by GetGameThreadStats().
GPUStats
FParticlePerfStats_GPU FParticlePerfStats::GPUStats
Stats from GPU work.
Definition at line 253 of file ParticlePerfStats.h.
Referenced by GetGPUStats().
RenderThreadStats
FParticlePerfStats_RT FParticlePerfStats::RenderThreadStats
Stats on RT work.
Definition at line 250 of file ParticlePerfStats.h.
Referenced by GetRenderThreadStats().
SystemStatsReaders
TAtomic<int32> FParticlePerfStats::SystemStatsReaders static
Definition at line 241 of file ParticlePerfStats.h.
Referenced by AddSystemStatReader(), GetGatherSystemStats(), and RemoveSystemStatReader().
WorldStatsReaders
TAtomic<int32> FParticlePerfStats::WorldStatsReaders static
Definition at line 240 of file ParticlePerfStats.h.
Referenced by AddWorldStatReader(), GetGatherWorldStats(), and RemoveWorldStatReader().
The documentation for this struct was generated from the following file:
ParticlePerfStats.h