Unreal Engine 5.6 C++ API: FLocKey Class Reference
FLocKey Class Reference
Case sensitive immutable hashed string used as a localization key.
#include "LocKeyFuncs.h"
Public Member Functions
FLocKey ()
FLocKey (const FLocKey &InOther)
FLocKey (const FString &InStr)
FLocKey (const TCHAR *InStr)
FLocKey (FLocKey &&InOther)
FLocKey (FString &&InStr)
FORCEINLINE int32 Compare (const FLocKey &Other) const
FORCEINLINE bool Equals (const FLocKey &Other) const
FORCEINLINE const FString & GetString () const
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool operator!= (const FLocKey &Other) const
FORCEINLINE bool operator< (const FLocKey &Other) const
FORCEINLINE bool operator<= (const FLocKey &Other) const
FLocKey & operator= (const FLocKey &InOther)
FLocKey & operator= (FLocKey &&InOther)
FORCEINLINE bool operator== (const FLocKey &Other) const
FORCEINLINE bool operator> (const FLocKey &Other) const
FORCEINLINE bool operator>= (const FLocKey &Other) const
Static Public Member Functions
static FORCEINLINE uint32 ProduceHash (const FString &InStr, const uint32 InBaseHash=0)
Private Attributes
uint32 Hash
Hash representation of this LocKey.
FString Str
String representation of this LocKey.
Friends
uint32 GetTypeHash (const FLocKey &Id)
Detailed Description
Case sensitive immutable hashed string used as a localization key.
Definition at line 9 of file LocKeyFuncs.h.
Constructor & Destructor Documentation
FLocKey() [1/6]
FLocKey::FLocKey () inline
Definition at line 12 of file LocKeyFuncs.h.
References Hash, and Str.
Referenced by FLocKey(), FLocKey(), Compare(), Equals(), GetTypeHash, operator!=(), operator<(), operator<=(), operator=(), operator=(), operator==(), operator>(), and operator>=().
FLocKey() [2/6]
FLocKey::FLocKey (const TCHAR * InStr) inline
Definition at line 18 of file LocKeyFuncs.h.
References Hash, ProduceHash(), and Str.
FLocKey() [3/6]
FLocKey::FLocKey (const FString & InStr) inline
Definition at line 24 of file LocKeyFuncs.h.
References Hash, ProduceHash(), and Str.
FLocKey() [4/6]
FLocKey::FLocKey (FString && InStr) inline
Definition at line 30 of file LocKeyFuncs.h.
References Hash, MoveTemp(), ProduceHash(), and Str.
FLocKey() [5/6]
FLocKey::FLocKey (const FLocKey & InOther) inline
Definition at line 36 of file LocKeyFuncs.h.
References FLocKey(), Hash, and Str.
FLocKey() [6/6]
FLocKey::FLocKey (FLocKey && InOther) inline
Definition at line 42 of file LocKeyFuncs.h.
References FLocKey(), Hash, MoveTemp(), and Str.
Member Function Documentation
Compare()
FORCEINLINE int32 FLocKey::Compare (const FLocKey & Other) const inline
Definition at line 118 of file LocKeyFuncs.h.
References FLocKey(), FORCEINLINE, Other, Str, and TCString< TCHAR >::Strcmp().
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
Equals()
FORCEINLINE bool FLocKey::Equals (const FLocKey & Other) const inline
Definition at line 113 of file LocKeyFuncs.h.
References FLocKey(), FORCEINLINE, and Other.
GetString()
FORCEINLINE const FString & FLocKey::GetString () const inline
Definition at line 123 of file LocKeyFuncs.h.
References FORCEINLINE, and Str.
IsEmpty()
FORCEINLINE bool FLocKey::IsEmpty () const inline
Definition at line 108 of file LocKeyFuncs.h.
References FORCEINLINE, and Str.
operator!=()
FORCEINLINE bool FLocKey::operator!= (const FLocKey & Other) const inline
Definition at line 78 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, Hash, and Other.
operator<()
FORCEINLINE bool FLocKey::operator< (const FLocKey & Other) const inline
Definition at line 83 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, and Other.
operator<=()
FORCEINLINE bool FLocKey::operator<= (const FLocKey & Other) const inline
Definition at line 88 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, and Other.
operator=() [1/2]
FLocKey & FLocKey::operator= (const FLocKey & InOther) inline
Definition at line 49 of file LocKeyFuncs.h.
References FLocKey(), Hash, and Str.
operator=() [2/2]
FLocKey & FLocKey::operator= (FLocKey && InOther) inline
Definition at line 60 of file LocKeyFuncs.h.
References FLocKey(), Hash, MoveTemp(), and Str.
operator==()
FORCEINLINE bool FLocKey::operator== (const FLocKey & Other) const inline
Definition at line 73 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, Hash, and Other.
operator>()
FORCEINLINE bool FLocKey::operator> (const FLocKey & Other) const inline
Definition at line 93 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, and Other.
operator>=()
FORCEINLINE bool FLocKey::operator>= (const FLocKey & Other) const inline
Definition at line 98 of file LocKeyFuncs.h.
References FLocKey(), Compare(), FORCEINLINE, and Other.
ProduceHash()
FORCEINLINE uint32 FLocKey::ProduceHash (const FString & InStr, const uint32 InBaseHash = 0) inline static
Definition at line 128 of file LocKeyFuncs.h.
References FORCEINLINE, and FCrc::StrCrc32().
Referenced by FLocKey(), FLocKey(), FLocKey(), FLocKeyMapFuncs< ValueType >::GetKeyHash(), FLocKeyMultiMapFuncs< ValueType >::GetKeyHash(), and FLocKeySetFuncs::GetKeyHash().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FLocKey & Id) friend
Definition at line 103 of file LocKeyFuncs.h.
References FLocKey(), and Hash.
Field Documentation
Hash
uint32 FLocKey::Hash private
Hash representation of this LocKey.
Definition at line 138 of file LocKeyFuncs.h.
Referenced by FLocKey(), FLocKey(), FLocKey(), FLocKey(), FLocKey(), FLocKey(), GetTypeHash, operator!=(), operator=(), operator=(), and operator==().
Str
FString FLocKey::Str private
String representation of this LocKey.
Definition at line 135 of file LocKeyFuncs.h.
Referenced by FLocKey(), FLocKey(), FLocKey(), FLocKey(), FLocKey(), FLocKey(), Compare(), GetString(), IsEmpty(), operator=(), and operator=().
The documentation for this class was generated from the following file:
LocKeyFuncs.h