Unreal Engine 5.6 C++ API: TAsyncQueuedWork< ResultType > Class Template Reference
TAsyncQueuedWork< ResultType > Class Template Reference
Template for asynchronous functions that are executed in the queued thread pool.
#include "Async.h"
Public Member Functions
TAsyncQueuedWork (TUniqueFunction< ResultType()> &&InFunction, TPromise< ResultType > &&InPromise)
Creates and initializes a new instance.
virtual void Abandon () override
Tells the queued work that it is being abandoned so that it can do per object clean up as needed.
virtual void DoThreadedWork () override
This is where the real thread work is done.
Public Member Functions inherited from IQueuedWork
virtual ~IQueuedWork ()
Virtual destructor so that child implementations are guaranteed a chance to clean up any resources they allocated.
virtual const TCHAR * GetDebugName () const
Returns text to identify the Work, for debug/log purposes only.
virtual EQueuedWorkFlags GetQueuedWorkFlags () const
Returns any special work flags.
virtual int64 GetRequiredMemory () const
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
Private Attributes
TUniqueFunction< ResultType()> Function
The function to execute on the Task Graph.
TPromise< ResultType > Promise
The promise to assign the result to.
Additional Inherited Members
Public Types inherited from IQueuedWork
using IInternalDataType = TRefCountPtr<IQueuedWorkInternalData>
Internal data can be used by the pool.
Data Fields inherited from IQueuedWork
IInternalDataType InternalData
Detailed Description
template<typename ResultType>
class TAsyncQueuedWork< ResultType >
Template for asynchronous functions that are executed in the queued thread pool.
Definition at line 214 of file Async.h.
Constructor & Destructor Documentation
TAsyncQueuedWork()
template<typename ResultType> TAsyncQueuedWork< ResultType >::TAsyncQueuedWork (TUniqueFunction< ResultType()> && InFunction, TPromise< ResultType > && InPromise) inline
Creates and initializes a new instance.
Parameters
InFunction The function to execute asynchronously.
InPromise The promise object used to return the function's result.
Definition at line 225 of file Async.h.
References Function, MoveTemp(), and Promise.
Member Function Documentation
Abandon()
template<typename ResultType> virtual void TAsyncQueuedWork< ResultType >::Abandon () inline override virtual
Tells the queued work that it is being abandoned so that it can do per object clean up as needed.
This will only be called if it is being abandoned before completion. NOTE: This requires the object to delete itself using whatever heap it was allocated in.
Implements IQueuedWork.
Definition at line 240 of file Async.h.
DoThreadedWork()
template<typename ResultType> virtual void TAsyncQueuedWork< ResultType >::DoThreadedWork () inline override virtual
This is where the real thread work is done.
All work that is done for this queued object should be done from within the call to this function.
Implements IQueuedWork.
Definition at line 234 of file Async.h.
References Function, Promise, and SetPromise().
Field Documentation
Function
template<typename ResultType> TUniqueFunction<ResultType()> TAsyncQueuedWork< ResultType >::Function private
The function to execute on the Task Graph.
Definition at line 248 of file Async.h.
Referenced by TAsyncQueuedWork(), and DoThreadedWork().
Promise
template<typename ResultType> TPromise<ResultType> TAsyncQueuedWork< ResultType >::Promise private
The promise to assign the result to.
Definition at line 251 of file Async.h.
Referenced by TAsyncQueuedWork(), and DoThreadedWork().
The documentation for this class was generated from the following file:
Async.h