Unreal Engine 5.6 C++ API: TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > Class Template Reference
TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > Class Template Reference
Fixed size block allocated container class.
#include "PagedArray.h"
Public Types
using AllocatorType = InAllocatorType
using ConstIteratorType = UE::Core::PagedArray::Private::TIterator<const ElementType, const PageType, PageTraits>
using ElementAllocatorType
using ElementType = InElementType
using IteratorType = UE::Core::PagedArray::Private::TIterator<ElementType, PageType, PageTraits>
using SizeType = typename InAllocatorType::SizeType
Public Member Functions
TPagedArray ()=default
TPagedArray (const ElementType *InSource, SizeType InSize)
TPagedArray (const TPagedArray &Other)=default
TPagedArray (std::initializer_list< ElementType > InList)
TPagedArray (TPagedArray &&Other)
~TPagedArray ()=default
FORCEINLINE SizeType Add (const ElementType &Element)
FORCEINLINE SizeType Add (ElementType &&Element)
FORCEINLINE ElementType & Add_GetRef (const ElementType &Element)
FORCEINLINE ElementType & Add_GetRef (ElementType &&Element)
void Append (const ElementType *InSource, SizeType InSize)
template<int32 OtherPageSizeInBytes, typename OtherAllocator>
void Append (const TPagedArray< ElementType, OtherPageSizeInBytes, OtherAllocator > &Other)
template<typename ContainerType UE_REQUIRES>
FORCEINLINE void Append (ContainerType &&Container)
void Append (std::initializer_list< ElementType > InList)
void Assign (const ElementType *InSource, SizeType InSize)
Assigns the parameter contiguous range to this container.
template<int32 OtherPageSizeInBytes, typename OtherAllocator>
void Assign (const TPagedArray< ElementType, OtherPageSizeInBytes, OtherAllocator > &Other)
Assigns a compatible paged array to this container.
template<typename ContainerType UE_REQUIRES>
void Assign (ContainerType &&Container)
void Assign (std::initializer_list< ElementType > InList)
FORCEINLINE IteratorType begin ()
FORCEINLINE ConstIteratorType begin () const
STL IteratorType model compliance methods.
void CountBytes (FArchive &Ar) const
Count bytes needed to serialize this paged array.
template<typename... ArgsType>
SizeType Emplace (ArgsType &&... Args)
template<typename... ArgsType>
ElementType & Emplace_GetRef (ArgsType &&... Args)
void Empty ()
void Empty (SizeType InCapacity)
FORCEINLINE IteratorType end ()
FORCEINLINE ConstIteratorType end () const
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool IsValidIndex (SizeType Index) const
FORCEINLINE ElementType & Last ()
FORCEINLINE const ElementType & Last () const
FORCEINLINE SizeType Max () const
FORCEINLINE SizeType Num () const
FORCEINLINE SizeType NumPages () const
FORCEINLINE bool operator!= (const TPagedArray &Right) const
TPagedArray & operator= (const TPagedArray &Other)=default
TPagedArray & operator= (std::initializer_list< ElementType > InList)
TPagedArray & operator= (TPagedArray &&Other)
bool operator== (const TPagedArray &Right) const
FORCEINLINE ElementType & operator[] (SizeType Index)
FORCEINLINE const ElementType & operator[] (SizeType Index) const
void Pop (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
FORCEINLINE void Push (const ElementType &Element)
FORCEINLINE void Push (ElementType &&Element)
void RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the element at the parameter index position and swaps the last element if existent to the same position to ensure the range is contiguous.
FORCEINLINE void Reserve (SizeType InCount)
void Reset ()
void Reset (SizeType InCapacity)
void SetMem (uint8 ByteValue)
void SetNum (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to the parameter number of elements.
FORCEINLINE void SetZero ()
template<typename AnyAllocator>
void ToArray (TArray< ElementType, AnyAllocator > &OutDestination) &&
template<typename AnyAllocator>
void ToArray (TArray< ElementType, AnyAllocator > &OutDestination) const &
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") FORCEINLINE void Pop(bool bAllowShrinking)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") FORCEINLINE void RemoveAtSwap(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum") FORCEINLINE void SetNum(SizeType NewNum
Static Public Member Functions
static constexpr SizeType MaxPerPage ()
Data Fields
bool bAllowShrinking
Private Types
using PageTraits = UE::Core::PagedArray::Private::TPageTraits<InElementType, InPageSizeInBytes>
using PageType = TArray<InElementType, InAllocatorType>
Private Member Functions
PageType & AddPage ()
FORCEINLINE void CheckValidIndex (SizeType Index) const
void CopyToEmpty (const ElementType *InSource, SizeType InSize)
void CopyUnchecked (const ElementType *InSource, SizeType InSize)
FORCEINLINE IteratorType GetIterator (SizeType Offset)
FORCEINLINE ConstIteratorType GetIterator (SizeType Offset) const
void Grow (SizeType InCapacity)
void GrowIfRequired ()
void GrowIfRequired (SizeType InCapacity)
Static Private Member Functions
static constexpr SizeType GetPageIndex (SizeType Index)
static constexpr SizeType GetPageOffset (SizeType Index)
static constexpr SizeType NumRequiredPages (SizeType Count)
Private Attributes
SizeType Count = 0
TArray< PageType > Pages
Friends
template<typename AnyElementType, int32 AnyPageSizeInBytes, typename AnyAllocatorType>
class TPagedArray
Detailed Description
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType>
class TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >
Fixed size block allocated container class.
This container mimics the behavior of an array without fulfilling the contiguous storage guarantee. Instead, it allocates memory in pages. Each page is a block of memory of the parameter page size in bytes. Elements within a page are guaranteed to be contiguous. Paged arrays have the following advantages v normal arrays:
It's more suited for large sized arrays as they don't require a single contiguous memory block. This make them less vulnerable to memory fragmentation.
The contained elements' addresses are persistent as long as the container isn't resized.
Definition at line 158 of file Runtime/Core/Public/Containers/PagedArray.h.
Member Typedef Documentation
AllocatorType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::AllocatorType = InAllocatorType
Definition at line 167 of file Runtime/Core/Public/Containers/PagedArray.h.
ConstIteratorType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ConstIteratorType = UE::Core::PagedArray::Private::TIterator<const ElementType, const PageType, PageTraits>
Definition at line 193 of file Runtime/Core/Public/Containers/PagedArray.h.
ElementAllocatorType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ElementAllocatorType
Initial value:
 std::conditional_t<
        AllocatorType::NeedsElementType,
        typename AllocatorType::template ForElementType<ElementType>,
        typename AllocatorType::ForAnyElementType>
Definition at line 170 of file Runtime/Core/Public/Containers/PagedArray.h.
ElementType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ElementType = InElementType
Definition at line 169 of file Runtime/Core/Public/Containers/PagedArray.h.
IteratorType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::IteratorType = UE::Core::PagedArray::Private::TIterator<ElementType, PageType, PageTraits>
Definition at line 194 of file Runtime/Core/Public/Containers/PagedArray.h.
PageTraits
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::PageTraits = UE::Core::PagedArray::Private::TPageTraits<InElementType, InPageSizeInBytes> private
Definition at line 164 of file Runtime/Core/Public/Containers/PagedArray.h.
PageType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::PageType = TArray<InElementType, InAllocatorType> private
Definition at line 163 of file Runtime/Core/Public/Containers/PagedArray.h.
SizeType
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> using TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::SizeType = typename InAllocatorType::SizeType
Definition at line 168 of file Runtime/Core/Public/Containers/PagedArray.h.
Constructor & Destructor Documentation
TPagedArray() [1/5]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray () nodiscard default
TPagedArray() [2/5]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray (TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > && Other) inline nodiscard
Definition at line 203 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, Count, MoveTemp(), Other, and Pages.
TPagedArray() [3/5]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray (const TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > & Other) nodiscard default
References TPagedArray, and Other.
TPagedArray() [4/5]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray (std::initializer_list< ElementType > InList) inline nodiscard
Definition at line 210 of file Runtime/Core/Public/Containers/PagedArray.h.
References CopyToEmpty().
TPagedArray() [5/5]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::TPagedArray (const ElementType * InSource, SizeType InSize) inline nodiscard
Definition at line 215 of file Runtime/Core/Public/Containers/PagedArray.h.
References check, and CopyToEmpty().
~TPagedArray()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::~TPagedArray () default
Member Function Documentation
Add() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add (const ElementType & Element) inline
Definition at line 493 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace(), and FORCEINLINE.
Add() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add (ElementType && Element) inline
Definition at line 498 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
Add_GetRef() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add_GetRef (const ElementType & Element) inline nodiscard
Definition at line 503 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace_GetRef(), and FORCEINLINE.
Add_GetRef() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Add_GetRef (ElementType && Element) inline nodiscard
Definition at line 508 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace_GetRef(), FORCEINLINE, and MoveTempIfPossible().
AddPage()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> PageType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::AddPage () inline private
Definition at line 731 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, Pages, and TArray< InElementType, InAllocatorType >::Reserve().
Referenced by Grow(), and GrowIfRequired().
Append() [1/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append (const ElementType * InSource, SizeType InSize) inline
Definition at line 386 of file Runtime/Core/Public/Containers/PagedArray.h.
References check, CopyUnchecked(), Count, and GrowIfRequired().
Referenced by Append(), Append(), Assign(), Assign(), Assign(), and Assign().
Append() [2/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<int32 OtherPageSizeInBytes, typename OtherAllocator> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append (const TPagedArray< ElementType, OtherPageSizeInBytes, OtherAllocator > & Other) inline
Definition at line 412 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, CopyUnchecked(), Count, GrowIfRequired(), and Other.
Append() [3/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename ContainerType UE_REQUIRES> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append (ContainerType && Container) inline
Definition at line 402 of file Runtime/Core/Public/Containers/PagedArray.h.
References Append(), Container, FORCEINLINE, GetData(), and GetNum().
Append() [4/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append (std::initializer_list< ElementType > InList) inline
Definition at line 393 of file Runtime/Core/Public/Containers/PagedArray.h.
References Append().
Assign() [1/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign (const ElementType * InSource, SizeType InSize) inline
Assigns the parameter contiguous range to this container.
Any pre-existing content is removed.
Definition at line 427 of file Runtime/Core/Public/Containers/PagedArray.h.
References Append(), and Reset().
Referenced by operator=().
Assign() [2/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<int32 OtherPageSizeInBytes, typename OtherAllocator> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign (const TPagedArray< ElementType, OtherPageSizeInBytes, OtherAllocator > & Other) inline
Assigns a compatible paged array to this container.
Any pre-existing content is removed. Note TPagedArray doesn't meet TIsContiguousContainer traits so it won't use the contiguous container overload.
Definition at line 455 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, Append(), Other, and Reset().
Assign() [3/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename ContainerType UE_REQUIRES> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign (ContainerType && Container) inline
Definition at line 443 of file Runtime/Core/Public/Containers/PagedArray.h.
References Append(), Container, GetData(), GetNum(), and Reset().
Assign() [4/4]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign (std::initializer_list< ElementType > InList) inline
Definition at line 433 of file Runtime/Core/Public/Containers/PagedArray.h.
References Append(), and Reset().
begin() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE IteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::begin () inline nodiscard
Definition at line 678 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, and GetIterator().
begin() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ConstIteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::begin () const inline nodiscard
STL IteratorType model compliance methods.
Definition at line 674 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, and GetIterator().
CheckValidIndex()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CheckValidIndex (SizeType Index) const inline private
Definition at line 822 of file Runtime/Core/Public/Containers/PagedArray.h.
References checkf, Count, FORCEINLINE, and TEXT.
Referenced by Last(), Last(), operator[](), operator[](), Pop(), and RemoveAtSwap().
CopyToEmpty()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CopyToEmpty (const ElementType * InSource, SizeType InSize) inline private
Definition at line 742 of file Runtime/Core/Public/Containers/PagedArray.h.
References checkSlow, CopyUnchecked(), Count, and Grow().
Referenced by TPagedArray(), and TPagedArray().
CopyUnchecked()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CopyUnchecked (const ElementType * InSource, SizeType InSize) inline private
Definition at line 755 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, Count, GetPageIndex(), GetPageOffset(), FMath::Min, and Pages.
Referenced by Append(), Append(), and CopyToEmpty().
CountBytes()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::CountBytes (FArchive & Ar) const inline
Count bytes needed to serialize this paged array.
Parameters
Ar Archive to count for.
Definition at line 276 of file Runtime/Core/Public/Containers/PagedArray.h.
References Ar, Max(), and Num().
Referenced by UE::Core::PagedArray::Private::Serialize().
Emplace()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename... ArgsType> SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace (ArgsType &&... Args) inline
Definition at line 466 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, Forward(), GetPageIndex(), GrowIfRequired(), Num(), and Pages.
Referenced by Add(), Add(), Push(), and Push().
Emplace_GetRef()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename... ArgsType> ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Emplace_GetRef (ArgsType &&... Args) inline nodiscard
Definition at line 481 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, Forward(), GetPageIndex(), GrowIfRequired(), Num(), and Pages.
Referenced by Add_GetRef(), Add_GetRef(), UE::Core::PagedArray::Private::Serialize(), and UE::Core::PagedArray::Private::SerializeStructured().
Empty() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Empty () inline
Definition at line 582 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and Pages.
Referenced by UE::Core::PagedArray::Private::Serialize(), and UE::Core::PagedArray::Private::SerializeStructured().
Empty() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Empty (SizeType InCapacity) inline
Definition at line 592 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, NumRequiredPages(), Pages, and Reset().
end() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE IteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::end () inline nodiscard
Definition at line 686 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, FORCEINLINE, and GetIterator().
end() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ConstIteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::end () const inline nodiscard
Definition at line 682 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, FORCEINLINE, and GetIterator().
GetAllocatedSize()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SIZE_T TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetAllocatedSize () const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
Number of bytes allocated by this container.
Definition at line 260 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, Pages, and TSequenceHistory< HistorySize >::Size.
GetIterator() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE IteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetIterator (SizeType Offset) inline nodiscard private
Definition at line 723 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, InPlace, and Pages.
GetIterator() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ConstIteratorType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetIterator (SizeType Offset) const inline nodiscard private
Definition at line 718 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, InPlace, and Pages.
Referenced by begin(), begin(), end(), and end().
GetPageIndex()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> constexpr SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetPageIndex (SizeType Index) inline static nodiscard constexpr private
Definition at line 176 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity.
Referenced by CopyUnchecked(), Emplace(), Emplace_GetRef(), Last(), Last(), operator[](), operator[](), Pop(), and RemoveAtSwap().
GetPageOffset()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> constexpr SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GetPageOffset (SizeType Index) inline static nodiscard constexpr private
Definition at line 181 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity.
Referenced by CopyUnchecked(), Last(), Last(), operator[](), operator[](), Pop(), and RemoveAtSwap().
Grow()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Grow (SizeType InCapacity) inline private
Definition at line 787 of file Runtime/Core/Public/Containers/PagedArray.h.
References AddPage(), checkSlow, Max(), NumRequiredPages(), and Pages.
Referenced by CopyToEmpty(), and GrowIfRequired().
GrowIfRequired() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GrowIfRequired () inline private
Definition at line 802 of file Runtime/Core/Public/Containers/PagedArray.h.
References AddPage(), Count, and Max().
Referenced by Append(), Append(), Emplace(), Emplace_GetRef(), and Reserve().
GrowIfRequired() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::GrowIfRequired (SizeType InCapacity) inline private
Definition at line 814 of file Runtime/Core/Public/Containers/PagedArray.h.
References Grow(), and Max().
IsEmpty()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE bool TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::IsEmpty () const inline nodiscard
Definition at line 301 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and FORCEINLINE.
Referenced by RemoveAtSwap().
IsValidIndex()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE bool TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::IsValidIndex (SizeType Index) const inline nodiscard
Definition at line 296 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and FORCEINLINE.
Last() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Last () inline nodiscard
Definition at line 313 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), FORCEINLINE, GetPageIndex(), GetPageOffset(), Num(), and Pages.
Last() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE const ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Last () const inline nodiscard
Definition at line 306 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), FORCEINLINE, GetPageIndex(), GetPageOffset(), Num(), and Pages.
Max()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Max () const inline nodiscard
Definition at line 281 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, FORCEINLINE, and Pages.
Referenced by CountBytes(), Grow(), GrowIfRequired(), and GrowIfRequired().
MaxPerPage()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> constexpr SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::MaxPerPage () inline static nodiscard constexpr
Definition at line 196 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity.
Num()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Num () const inline nodiscard
Definition at line 286 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and FORCEINLINE.
Referenced by CountBytes(), Emplace(), Emplace_GetRef(), Last(), Last(), operator==(), Pop(), RemoveAtSwap(), UE::Core::PagedArray::Private::Serialize(), UE::Core::PagedArray::Private::SerializeStructured(), and SetNum().
NumPages()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::NumPages () const inline nodiscard
Definition at line 291 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, and Pages.
NumRequiredPages()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> constexpr SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::NumRequiredPages (SizeType Count) inline static nodiscard constexpr private
Definition at line 186 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, and Count.
Referenced by Empty(), Grow(), operator==(), and SetNum().
operator!=()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE bool TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator!= (const TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > & Right) const inline nodiscard
Definition at line 709 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, FORCEINLINE, and Right.
operator=() [1/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator= (const TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > & Other) default
References TPagedArray, and Other.
operator=() [2/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator= (std::initializer_list< ElementType > InList) inline
Definition at line 236 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, and Assign().
operator=() [3/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator= (TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > && Other) inline
Definition at line 223 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, Count, MoveTemp(), Other, and Pages.
operator==()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> bool TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator== (const TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType > & Right) const inline nodiscard
Definition at line 692 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray, Count, Num(), NumRequiredPages(), Pages, and Right.
operator[]() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator[] (SizeType Index) inline nodiscard
Definition at line 248 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), FORCEINLINE, GetPageIndex(), GetPageOffset(), and Pages.
operator[]() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE const ElementType & TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::operator[] (SizeType Index) const inline nodiscard
Definition at line 242 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), FORCEINLINE, GetPageIndex(), GetPageOffset(), and Pages.
Pop()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Pop (EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 526 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), Count, Default, GetPageIndex(), GetPageOffset(), No, Num(), Pages, and Yes.
Referenced by UE_ALLOWSHRINKING_BOOL_DEPRECATED().
Push() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Push (const ElementType & Element) inline
Definition at line 513 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace(), and FORCEINLINE.
Push() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Push (ElementType && Element) inline
Definition at line 518 of file Runtime/Core/Public/Containers/PagedArray.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
RemoveAtSwap()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Removes the element at the parameter index position and swaps the last element if existent to the same position to ensure the range is contiguous.
This method provides efficient removal O(1) but it doesn't preserve the insertion order.
Definition at line 550 of file Runtime/Core/Public/Containers/PagedArray.h.
References CheckValidIndex(), Count, Default, GetPageIndex(), GetPageOffset(), IsEmpty(), MoveTempIfPossible(), No, Num(), Pages, and Yes.
Referenced by UE_ALLOWSHRINKING_BOOL_DEPRECATED().
Reserve()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Reserve (SizeType InCount) inline
Definition at line 630 of file Runtime/Core/Public/Containers/PagedArray.h.
References check, FORCEINLINE, and GrowIfRequired().
Referenced by Reset().
Reset() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Reset () inline
Definition at line 608 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and Pages.
Referenced by Assign(), Assign(), Assign(), Assign(), Empty(), and Reset().
Reset() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Reset (SizeType InCapacity) inline
Definition at line 621 of file Runtime/Core/Public/Containers/PagedArray.h.
References Reserve(), and Reset().
SetMem()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::SetMem (uint8 ByteValue) inline
Definition at line 363 of file Runtime/Core/Public/Containers/PagedArray.h.
References Pages.
Referenced by SetZero().
SetNum()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::SetNum (SizeType NewNum, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Resizes array to the parameter number of elements.
The allow shrinking parameter indicates whether the container page allocation can be reduced if possible.
Definition at line 324 of file Runtime/Core/Public/Containers/PagedArray.h.
References UE::Core::PagedArray::Private::TPageTraits< InElementType, InPageSizeInBytes >::Capacity, Count, Default, No, Num(), NumRequiredPages(), and Pages.
SetZero()
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> FORCEINLINE void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::SetZero () inline
Definition at line 378 of file Runtime/Core/Public/Containers/PagedArray.h.
References FORCEINLINE, and SetMem().
ToArray() [1/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename AnyAllocator> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ToArray (TArray< ElementType, AnyAllocator > & OutDestination) && inline
Definition at line 658 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, MoveTemp(), and Pages.
ToArray() [2/2]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename AnyAllocator> void TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::ToArray (TArray< ElementType, AnyAllocator > & OutDestination) const & inline
Definition at line 640 of file Runtime/Core/Public/Containers/PagedArray.h.
References Count, and Pages.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") inline
Definition at line 539 of file Runtime/Core/Public/Containers/PagedArray.h.
References bAllowShrinking, FORCEINLINE, No, Pop(), and Yes.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap")
References bAllowShrinking, FORCEINLINE, No, RemoveAtSwap(), and Yes.
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [3/3]
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum")
Friends And Related Symbol Documentation
TPagedArray
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> template<typename AnyElementType, int32 AnyPageSizeInBytes, typename AnyAllocatorType> friend class TPagedArray friend
Definition at line 161 of file Runtime/Core/Public/Containers/PagedArray.h.
References TPagedArray.
Referenced by TPagedArray, TPagedArray(), TPagedArray(), Append(), Assign(), operator!=(), operator=(), operator=(), operator=(), and operator==().
Field Documentation
bAllowShrinking
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> bool TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::bAllowShrinking
Initial value:
{
        SetNum(NewNum, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 355 of file Runtime/Core/Public/Containers/PagedArray.h.
Referenced by UE_ALLOWSHRINKING_BOOL_DEPRECATED(), and UE_ALLOWSHRINKING_BOOL_DEPRECATED().
Count
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> SizeType TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Count = 0 private
Definition at line 716 of file Runtime/Core/Public/Containers/PagedArray.h.
Referenced by TPagedArray(), Append(), Append(), CheckValidIndex(), CopyToEmpty(), CopyUnchecked(), Emplace(), Emplace_GetRef(), Empty(), end(), end(), GrowIfRequired(), IsEmpty(), IsValidIndex(), Num(), NumRequiredPages(), operator=(), operator==(), Pop(), RemoveAtSwap(), Reset(), SetNum(), ToArray(), and ToArray().
Pages
template<typename InElementType, int32 InPageSizeInBytes, typename InAllocatorType> TArray<PageType> TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Pages private
Definition at line 715 of file Runtime/Core/Public/Containers/PagedArray.h.
Referenced by TPagedArray(), AddPage(), CopyUnchecked(), Emplace(), Emplace_GetRef(), Empty(), Empty(), GetAllocatedSize(), GetIterator(), GetIterator(), Grow(), Last(), Last(), Max(), NumPages(), operator=(), operator==(), operator[](), operator[](), Pop(), RemoveAtSwap(), Reset(), SetMem(), SetNum(), ToArray(), and ToArray().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/PagedArray.h