Unreal Engine 5.6 C++ API: ICameraLensEffectInterface Class Reference
ICameraLensEffectInterface Class Reference abstract
#include "CameraLensEffectInterface.h"
Private Member Functions
virtual void ActivateLensEffect ()=0
This will actually activate the lens Effect.
virtual void AdjustBaseFOV (float NewFOV)=0
virtual void DeactivateLensEffect ()=0
Deactivtes the particle system.
virtual float GetBaseFOV () const =0
virtual const FTransform & GetRelativeTransform () const =0
virtual bool IsLooping () const =0
Returns true if any associated particle system is set to looping.
virtual void NotifyRetriggered ()=0
Called when this emitter is re-triggered, for bAllowMultipleInstances=false emitters.
virtual void NotifyWillBePooled ()
If this type needs to handle being pooled, override this function.
virtual void RegisterCamera (APlayerCameraManager *CameraManager)=0
Called when being added to the player camera manager.
virtual bool ResetWhenTriggered () const =0
virtual bool ShouldAllowMultipleInstances () const =0
virtual bool ShouldTreatEmitterAsSame (TSubclassOf< AActor > OtherEmitter) const =0
Is this emitter functionally equivalent to the class OtherEmitter?
GENERATED_BODY() public UFUNCTION () 1 virtual UFXSystemComponent *GetPrimaryParticleComponent() const
virtual void UpdateLocation (const FVector &CamLoc, const FRotator &CamRot, float CamFOVDeg)
Given updated camera information, adjust this effect to display appropriately.
Static Private Member Functions
static FTransform GetAttachedEmitterTransform (const AActor *Emitter, const FVector &CamLoc, const FRotator &CamRot, float CamFOVDeg)
Detailed Description
Definition at line 21 of file CameraLensEffectInterface.h.
Member Function Documentation
ActivateLensEffect()
virtual void ICameraLensEffectInterface::ActivateLensEffect () private pure virtual
This will actually activate the lens Effect.
We want this separated from PostInitializeComponents so we can cache these emitters
AdjustBaseFOV()
virtual void ICameraLensEffectInterface::AdjustBaseFOV (float NewFOV) private pure virtual
DeactivateLensEffect()
virtual void ICameraLensEffectInterface::DeactivateLensEffect () private pure virtual
Deactivtes the particle system.
If bDestroyOnSystemFinish is true, actor will die after particles are all dead.
GetAttachedEmitterTransform()
FTransform ICameraLensEffectInterface::GetAttachedEmitterTransform (const AActor * Emitter, const FVector & CamLoc, const FRotator & CamRot, float CamFOVDeg) static private
References FVector.
GetBaseFOV()
virtual float ICameraLensEffectInterface::GetBaseFOV () const private pure virtual
References GetBaseFOV().
Referenced by GetBaseFOV().
GetRelativeTransform()
virtual const FTransform & ICameraLensEffectInterface::GetRelativeTransform () const private pure virtual
References GetRelativeTransform().
Referenced by GetRelativeTransform().
IsLooping()
virtual bool ICameraLensEffectInterface::IsLooping () const private pure virtual
Returns true if any associated particle system is set to looping.
NotifyRetriggered()
virtual void ICameraLensEffectInterface::NotifyRetriggered () private pure virtual
Called when this emitter is re-triggered, for bAllowMultipleInstances=false emitters.
NotifyWillBePooled()
virtual void ICameraLensEffectInterface::NotifyWillBePooled () inline private virtual
If this type needs to handle being pooled, override this function.
Definition at line 39 of file CameraLensEffectInterface.h.
References NotifyWillBePooled().
Referenced by NotifyWillBePooled().
RegisterCamera()
virtual void ICameraLensEffectInterface::RegisterCamera (APlayerCameraManager * CameraManager) private pure virtual
Called when being added to the player camera manager.
Typically happens before PreInitializeComponents (when handled from PlayerCameraManager).
ResetWhenTriggered()
virtual bool ICameraLensEffectInterface::ResetWhenTriggered () const private pure virtual
References ResetWhenTriggered().
Referenced by ResetWhenTriggered().
ShouldAllowMultipleInstances()
virtual bool ICameraLensEffectInterface::ShouldAllowMultipleInstances () const private pure virtual
References ShouldAllowMultipleInstances().
Referenced by ShouldAllowMultipleInstances().
ShouldTreatEmitterAsSame()
virtual bool ICameraLensEffectInterface::ShouldTreatEmitterAsSame (TSubclassOf< AActor > OtherEmitter) const private pure virtual
Is this emitter functionally equivalent to the class OtherEmitter?
UFUNCTION()
GENERATED_BODY() public ICameraLensEffectInterface::UFUNCTION () const private
References Category.
UpdateLocation()
virtual void ICameraLensEffectInterface::UpdateLocation (const FVector & CamLoc, const FRotator & CamRot, float CamFOVDeg) private virtual
Given updated camera information, adjust this effect to display appropriately.
References FVector.
The documentation for this class was generated from the following file:
CameraLensEffectInterface.h